; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -global-isel=0 -mtriple=amdgcn--amdpal -mcpu=gfx1200 < %s | FileCheck --check-prefix=DAGISEL %s
; RUN: llc -global-isel=1 -mtriple=amdgcn--amdpal -mcpu=gfx1200 < %s | FileCheck --check-prefix=GISEL %s
; RUN: llc -global-isel=0 -mtriple=amdgcn--amdpal -mcpu=gfx1200 -mattr=+wavefrontsize64 < %s | FileCheck --check-prefix=DAGISEL64 %s
; RUN: llc -global-isel=1 -mtriple=amdgcn--amdpal -mcpu=gfx1200 -mattr=+wavefrontsize64 < %s | FileCheck --check-prefix=GISEL64 %s
; RUN: llc -global-isel=0 -mtriple=amdgcn--amdpal -mcpu=gfx1250 < %s | FileCheck --check-prefix=GFX1250-DAGISEL %s

; Make sure the i1 %active is passed through EXEC.
; The EXEC mask should be set to -1 for the duration of the function
; and restored to its original value in the epilogue.
; We will also need to restore the inactive lanes for any allocated VGPRs.
define amdgpu_gfx_whole_wave i32 @basic_test(i1 %active, i32 %a, i32 %b) #0 {
; DAGISEL-LABEL: basic_test:
; DAGISEL:       ; %bb.0:
; DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL-NEXT:    s_wait_expcnt 0x0
; DAGISEL-NEXT:    s_wait_samplecnt 0x0
; DAGISEL-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL-NEXT:    s_wait_kmcnt 0x0
; DAGISEL-NEXT:    s_xor_saveexec_b32 vcc_lo, -1
; DAGISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v0, s32
; DAGISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    v_dual_cndmask_b32 v0, 5, v0 :: v_dual_cndmask_b32 v1, 3, v1
; DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; DAGISEL-NEXT:    v_mov_b32_dpp v0, v1 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; DAGISEL-NEXT:    s_xor_b32 exec_lo, vcc_lo, -1
; DAGISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v0, off, s32
; DAGISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; DAGISEL-NEXT:    s_mov_b32 exec_lo, vcc_lo
; DAGISEL-NEXT:    s_wait_loadcnt 0x0
; DAGISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL-LABEL: basic_test:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL-NEXT:    s_wait_expcnt 0x0
; GISEL-NEXT:    s_wait_samplecnt 0x0
; GISEL-NEXT:    s_wait_bvhcnt 0x0
; GISEL-NEXT:    s_wait_kmcnt 0x0
; GISEL-NEXT:    s_xor_saveexec_b32 vcc_lo, -1
; GISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v0, s32
; GISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; GISEL-NEXT:    s_mov_b32 exec_lo, -1
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    v_dual_cndmask_b32 v0, 5, v0 :: v_dual_cndmask_b32 v1, 3, v1
; GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GISEL-NEXT:    v_mov_b32_dpp v0, v1 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; GISEL-NEXT:    s_xor_b32 exec_lo, vcc_lo, -1
; GISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v0, off, s32
; GISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; GISEL-NEXT:    s_mov_b32 exec_lo, vcc_lo
; GISEL-NEXT:    s_wait_loadcnt 0x0
; GISEL-NEXT:    s_setpc_b64 s[30:31]
;
; DAGISEL64-LABEL: basic_test:
; DAGISEL64:       ; %bb.0:
; DAGISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL64-NEXT:    s_wait_expcnt 0x0
; DAGISEL64-NEXT:    s_wait_samplecnt 0x0
; DAGISEL64-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL64-NEXT:    s_wait_kmcnt 0x0
; DAGISEL64-NEXT:    s_xor_saveexec_b64 vcc, -1
; DAGISEL64-NEXT:    s_clause 0x1 ; 8-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v0, s32
; DAGISEL64-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; DAGISEL64-NEXT:    s_mov_b64 exec, -1
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    v_cndmask_b32_e32 v0, 5, v0, vcc
; DAGISEL64-NEXT:    v_cndmask_b32_e32 v1, 3, v1, vcc
; DAGISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; DAGISEL64-NEXT:    v_mov_b32_dpp v0, v1 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; DAGISEL64-NEXT:    s_xor_b64 exec, vcc, -1
; DAGISEL64-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v0, off, s32
; DAGISEL64-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; DAGISEL64-NEXT:    s_mov_b64 exec, vcc
; DAGISEL64-NEXT:    s_wait_loadcnt 0x0
; DAGISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL64-LABEL: basic_test:
; GISEL64:       ; %bb.0:
; GISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL64-NEXT:    s_wait_expcnt 0x0
; GISEL64-NEXT:    s_wait_samplecnt 0x0
; GISEL64-NEXT:    s_wait_bvhcnt 0x0
; GISEL64-NEXT:    s_wait_kmcnt 0x0
; GISEL64-NEXT:    s_xor_saveexec_b64 vcc, -1
; GISEL64-NEXT:    s_clause 0x1 ; 8-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v0, s32
; GISEL64-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; GISEL64-NEXT:    s_mov_b64 exec, -1
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    v_cndmask_b32_e32 v0, 5, v0, vcc
; GISEL64-NEXT:    v_cndmask_b32_e32 v1, 3, v1, vcc
; GISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GISEL64-NEXT:    v_mov_b32_dpp v0, v1 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; GISEL64-NEXT:    s_xor_b64 exec, vcc, -1
; GISEL64-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v0, off, s32
; GISEL64-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; GISEL64-NEXT:    s_mov_b64 exec, vcc
; GISEL64-NEXT:    s_wait_loadcnt 0x0
; GISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-DAGISEL-LABEL: basic_test:
; GFX1250-DAGISEL:       ; %bb.0:
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-DAGISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_xor_saveexec_b32 vcc_lo, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0, s32 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; GFX1250-DAGISEL-NEXT:    v_dual_cndmask_b32 v0, 5, v0 :: v_dual_cndmask_b32 v1, 3, v1
; GFX1250-DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1250-DAGISEL-NEXT:    v_mov_b32_dpp v0, v1 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; GFX1250-DAGISEL-NEXT:    s_xor_b32 exec_lo, vcc_lo, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0, off, s32 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, vcc_lo
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_set_pc_i64 s[30:31]
  %x = select i1 %active, i32 %a, i32 5
  %y = select i1 %active, i32 %b, i32 3
  %ret = call i32 @llvm.amdgcn.update.dpp.i32(i32 %x, i32 %y, i32 1, i32 1, i32 1, i1 false)
  ret i32 %ret
}

; Make sure we don't crash if there's only one use for %active.
define amdgpu_gfx_whole_wave i32 @single_use_of_active(i1 %active, i32 %a, i32 %b) #0 {
; DAGISEL-LABEL: single_use_of_active:
; DAGISEL:       ; %bb.0:
; DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL-NEXT:    s_wait_expcnt 0x0
; DAGISEL-NEXT:    s_wait_samplecnt 0x0
; DAGISEL-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL-NEXT:    s_wait_kmcnt 0x0
; DAGISEL-NEXT:    s_xor_saveexec_b32 vcc_lo, -1
; DAGISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v0, s32
; DAGISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    v_cndmask_b32_e32 v1, 17, v1, vcc_lo
; DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; DAGISEL-NEXT:    v_mov_b32_dpp v0, v1 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; DAGISEL-NEXT:    s_xor_b32 exec_lo, vcc_lo, -1
; DAGISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v0, off, s32
; DAGISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; DAGISEL-NEXT:    s_mov_b32 exec_lo, vcc_lo
; DAGISEL-NEXT:    s_wait_loadcnt 0x0
; DAGISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL-LABEL: single_use_of_active:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL-NEXT:    s_wait_expcnt 0x0
; GISEL-NEXT:    s_wait_samplecnt 0x0
; GISEL-NEXT:    s_wait_bvhcnt 0x0
; GISEL-NEXT:    s_wait_kmcnt 0x0
; GISEL-NEXT:    s_xor_saveexec_b32 vcc_lo, -1
; GISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v0, s32
; GISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; GISEL-NEXT:    s_mov_b32 exec_lo, -1
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    v_cndmask_b32_e32 v1, 17, v1, vcc_lo
; GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GISEL-NEXT:    v_mov_b32_dpp v0, v1 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; GISEL-NEXT:    s_xor_b32 exec_lo, vcc_lo, -1
; GISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v0, off, s32
; GISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; GISEL-NEXT:    s_mov_b32 exec_lo, vcc_lo
; GISEL-NEXT:    s_wait_loadcnt 0x0
; GISEL-NEXT:    s_setpc_b64 s[30:31]
;
; DAGISEL64-LABEL: single_use_of_active:
; DAGISEL64:       ; %bb.0:
; DAGISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL64-NEXT:    s_wait_expcnt 0x0
; DAGISEL64-NEXT:    s_wait_samplecnt 0x0
; DAGISEL64-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL64-NEXT:    s_wait_kmcnt 0x0
; DAGISEL64-NEXT:    s_xor_saveexec_b64 vcc, -1
; DAGISEL64-NEXT:    s_clause 0x1 ; 8-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v0, s32
; DAGISEL64-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; DAGISEL64-NEXT:    s_mov_b64 exec, -1
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    v_cndmask_b32_e32 v1, 17, v1, vcc
; DAGISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; DAGISEL64-NEXT:    v_mov_b32_dpp v0, v1 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; DAGISEL64-NEXT:    s_xor_b64 exec, vcc, -1
; DAGISEL64-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v0, off, s32
; DAGISEL64-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; DAGISEL64-NEXT:    s_mov_b64 exec, vcc
; DAGISEL64-NEXT:    s_wait_loadcnt 0x0
; DAGISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL64-LABEL: single_use_of_active:
; GISEL64:       ; %bb.0:
; GISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL64-NEXT:    s_wait_expcnt 0x0
; GISEL64-NEXT:    s_wait_samplecnt 0x0
; GISEL64-NEXT:    s_wait_bvhcnt 0x0
; GISEL64-NEXT:    s_wait_kmcnt 0x0
; GISEL64-NEXT:    s_xor_saveexec_b64 vcc, -1
; GISEL64-NEXT:    s_clause 0x1 ; 8-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v0, s32
; GISEL64-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; GISEL64-NEXT:    s_mov_b64 exec, -1
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    v_cndmask_b32_e32 v1, 17, v1, vcc
; GISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GISEL64-NEXT:    v_mov_b32_dpp v0, v1 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; GISEL64-NEXT:    s_xor_b64 exec, vcc, -1
; GISEL64-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v0, off, s32
; GISEL64-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; GISEL64-NEXT:    s_mov_b64 exec, vcc
; GISEL64-NEXT:    s_wait_loadcnt 0x0
; GISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-DAGISEL-LABEL: single_use_of_active:
; GFX1250-DAGISEL:       ; %bb.0:
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-DAGISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_xor_saveexec_b32 vcc_lo, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0, s32 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; GFX1250-DAGISEL-NEXT:    v_cndmask_b32_e32 v1, 17, v1, vcc_lo
; GFX1250-DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1250-DAGISEL-NEXT:    v_mov_b32_dpp v0, v1 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; GFX1250-DAGISEL-NEXT:    s_xor_b32 exec_lo, vcc_lo, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0, off, s32 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, vcc_lo
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_set_pc_i64 s[30:31]
  %y = select i1 %active, i32 %b, i32 17
  %ret = call i32 @llvm.amdgcn.update.dpp.i32(i32 %a, i32 %y, i32 1, i32 1, i32 1, i1 false)
  ret i32 %ret
}

; Make sure we don't crash if %active is not used at all.
define amdgpu_gfx_whole_wave i32 @unused_active(i1 %active, i32 %a, i32 %b) #0 {
; DAGISEL-LABEL: unused_active:
; DAGISEL:       ; %bb.0:
; DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL-NEXT:    s_wait_expcnt 0x0
; DAGISEL-NEXT:    s_wait_samplecnt 0x0
; DAGISEL-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL-NEXT:    s_wait_kmcnt 0x0
; DAGISEL-NEXT:    s_xor_saveexec_b32 s0, -1
; DAGISEL-NEXT:    scratch_store_b32 off, v0, s32 ; 4-byte Folded Spill
; DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; DAGISEL-NEXT:    v_mov_b32_e32 v0, 14
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    s_xor_b32 exec_lo, s0, -1
; DAGISEL-NEXT:    scratch_load_b32 v0, off, s32 ; 4-byte Folded Reload
; DAGISEL-NEXT:    s_mov_b32 exec_lo, s0
; DAGISEL-NEXT:    s_wait_loadcnt 0x0
; DAGISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL-LABEL: unused_active:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL-NEXT:    s_wait_expcnt 0x0
; GISEL-NEXT:    s_wait_samplecnt 0x0
; GISEL-NEXT:    s_wait_bvhcnt 0x0
; GISEL-NEXT:    s_wait_kmcnt 0x0
; GISEL-NEXT:    s_xor_saveexec_b32 s0, -1
; GISEL-NEXT:    scratch_store_b32 off, v0, s32 ; 4-byte Folded Spill
; GISEL-NEXT:    s_mov_b32 exec_lo, -1
; GISEL-NEXT:    v_mov_b32_e32 v0, 14
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    s_xor_b32 exec_lo, s0, -1
; GISEL-NEXT:    scratch_load_b32 v0, off, s32 ; 4-byte Folded Reload
; GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GISEL-NEXT:    s_wait_loadcnt 0x0
; GISEL-NEXT:    s_setpc_b64 s[30:31]
;
; DAGISEL64-LABEL: unused_active:
; DAGISEL64:       ; %bb.0:
; DAGISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL64-NEXT:    s_wait_expcnt 0x0
; DAGISEL64-NEXT:    s_wait_samplecnt 0x0
; DAGISEL64-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL64-NEXT:    s_wait_kmcnt 0x0
; DAGISEL64-NEXT:    s_xor_saveexec_b64 s[0:1], -1
; DAGISEL64-NEXT:    scratch_store_b32 off, v0, s32 ; 4-byte Folded Spill
; DAGISEL64-NEXT:    s_mov_b64 exec, -1
; DAGISEL64-NEXT:    v_mov_b32_e32 v0, 14
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    s_xor_b64 exec, s[0:1], -1
; DAGISEL64-NEXT:    scratch_load_b32 v0, off, s32 ; 4-byte Folded Reload
; DAGISEL64-NEXT:    s_mov_b64 exec, s[0:1]
; DAGISEL64-NEXT:    s_wait_loadcnt 0x0
; DAGISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL64-LABEL: unused_active:
; GISEL64:       ; %bb.0:
; GISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL64-NEXT:    s_wait_expcnt 0x0
; GISEL64-NEXT:    s_wait_samplecnt 0x0
; GISEL64-NEXT:    s_wait_bvhcnt 0x0
; GISEL64-NEXT:    s_wait_kmcnt 0x0
; GISEL64-NEXT:    s_xor_saveexec_b64 s[0:1], -1
; GISEL64-NEXT:    scratch_store_b32 off, v0, s32 ; 4-byte Folded Spill
; GISEL64-NEXT:    s_mov_b64 exec, -1
; GISEL64-NEXT:    v_mov_b32_e32 v0, 14
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    s_xor_b64 exec, s[0:1], -1
; GISEL64-NEXT:    scratch_load_b32 v0, off, s32 ; 4-byte Folded Reload
; GISEL64-NEXT:    s_mov_b64 exec, s[0:1]
; GISEL64-NEXT:    s_wait_loadcnt 0x0
; GISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-DAGISEL-LABEL: unused_active:
; GFX1250-DAGISEL:       ; %bb.0:
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-DAGISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_xor_saveexec_b32 s0, -1
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0, s32 nv ; 4-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; GFX1250-DAGISEL-NEXT:    v_mov_b32_e32 v0, 14
; GFX1250-DAGISEL-NEXT:    s_xor_b32 exec_lo, s0, -1
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0, off, s32 nv ; 4-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_set_pc_i64 s[30:31]
  ret i32 14
}

; For any used VGPRs (including those used for SGPR spills), we need to restore the inactive lanes.
; For CSR VGPRs, we need to restore all lanes.
define amdgpu_gfx_whole_wave i32 @csr(i1 %active, i32 %a, i32 %b) #0 {
; DAGISEL-LABEL: csr:
; DAGISEL:       ; %bb.0:
; DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL-NEXT:    s_wait_expcnt 0x0
; DAGISEL-NEXT:    s_wait_samplecnt 0x0
; DAGISEL-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL-NEXT:    s_wait_kmcnt 0x0
; DAGISEL-NEXT:    s_xor_saveexec_b32 vcc_lo, -1
; DAGISEL-NEXT:    s_clause 0x3 ; 16-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v2, s32
; DAGISEL-NEXT:    scratch_store_b32 off, v0, s32 offset:4
; DAGISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:8
; DAGISEL-NEXT:    scratch_store_b32 off, v49, s32 offset:16
; DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; DAGISEL-NEXT:    scratch_store_b32 off, v40, s32 offset:12 ; 4-byte Folded Spill
; DAGISEL-NEXT:    ;;#ASMSTART
; DAGISEL-NEXT:    ; clobber CSR
; DAGISEL-NEXT:    ;;#ASMEND
; DAGISEL-NEXT:    v_writelane_b32 v2, s20, 0
; DAGISEL-NEXT:    ;;#ASMSTART
; DAGISEL-NEXT:    ; clobber non-CSR
; DAGISEL-NEXT:    ;;#ASMEND
; DAGISEL-NEXT:    scratch_load_b32 v40, off, s32 offset:12 ; 4-byte Folded Reload
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    v_dual_cndmask_b32 v0, 5, v0 :: v_dual_cndmask_b32 v1, 3, v1
; DAGISEL-NEXT:    v_readlane_b32 s20, v2, 0
; DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; DAGISEL-NEXT:    v_mov_b32_dpp v0, v1 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; DAGISEL-NEXT:    s_xor_b32 exec_lo, vcc_lo, -1
; DAGISEL-NEXT:    s_clause 0x3 ; 16-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v2, off, s32
; DAGISEL-NEXT:    scratch_load_b32 v0, off, s32 offset:4
; DAGISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:8
; DAGISEL-NEXT:    scratch_load_b32 v49, off, s32 offset:16
; DAGISEL-NEXT:    s_mov_b32 exec_lo, vcc_lo
; DAGISEL-NEXT:    s_wait_loadcnt 0x0
; DAGISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; DAGISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL-LABEL: csr:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL-NEXT:    s_wait_expcnt 0x0
; GISEL-NEXT:    s_wait_samplecnt 0x0
; GISEL-NEXT:    s_wait_bvhcnt 0x0
; GISEL-NEXT:    s_wait_kmcnt 0x0
; GISEL-NEXT:    s_xor_saveexec_b32 vcc_lo, -1
; GISEL-NEXT:    s_clause 0x3 ; 16-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v2, s32
; GISEL-NEXT:    scratch_store_b32 off, v0, s32 offset:4
; GISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:8
; GISEL-NEXT:    scratch_store_b32 off, v49, s32 offset:16
; GISEL-NEXT:    s_mov_b32 exec_lo, -1
; GISEL-NEXT:    scratch_store_b32 off, v40, s32 offset:12 ; 4-byte Folded Spill
; GISEL-NEXT:    ;;#ASMSTART
; GISEL-NEXT:    ; clobber CSR
; GISEL-NEXT:    ;;#ASMEND
; GISEL-NEXT:    v_writelane_b32 v2, s20, 0
; GISEL-NEXT:    ;;#ASMSTART
; GISEL-NEXT:    ; clobber non-CSR
; GISEL-NEXT:    ;;#ASMEND
; GISEL-NEXT:    scratch_load_b32 v40, off, s32 offset:12 ; 4-byte Folded Reload
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    v_dual_cndmask_b32 v0, 5, v0 :: v_dual_cndmask_b32 v1, 3, v1
; GISEL-NEXT:    v_readlane_b32 s20, v2, 0
; GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GISEL-NEXT:    v_mov_b32_dpp v0, v1 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; GISEL-NEXT:    s_xor_b32 exec_lo, vcc_lo, -1
; GISEL-NEXT:    s_clause 0x3 ; 16-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v2, off, s32
; GISEL-NEXT:    scratch_load_b32 v0, off, s32 offset:4
; GISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:8
; GISEL-NEXT:    scratch_load_b32 v49, off, s32 offset:16
; GISEL-NEXT:    s_mov_b32 exec_lo, vcc_lo
; GISEL-NEXT:    s_wait_loadcnt 0x0
; GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GISEL-NEXT:    s_setpc_b64 s[30:31]
;
; DAGISEL64-LABEL: csr:
; DAGISEL64:       ; %bb.0:
; DAGISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL64-NEXT:    s_wait_expcnt 0x0
; DAGISEL64-NEXT:    s_wait_samplecnt 0x0
; DAGISEL64-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL64-NEXT:    s_wait_kmcnt 0x0
; DAGISEL64-NEXT:    s_xor_saveexec_b64 vcc, -1
; DAGISEL64-NEXT:    s_clause 0x3 ; 16-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v2, s32
; DAGISEL64-NEXT:    scratch_store_b32 off, v0, s32 offset:4
; DAGISEL64-NEXT:    scratch_store_b32 off, v1, s32 offset:8
; DAGISEL64-NEXT:    scratch_store_b32 off, v49, s32 offset:16
; DAGISEL64-NEXT:    s_mov_b64 exec, -1
; DAGISEL64-NEXT:    scratch_store_b32 off, v40, s32 offset:12 ; 4-byte Folded Spill
; DAGISEL64-NEXT:    ;;#ASMSTART
; DAGISEL64-NEXT:    ; clobber CSR
; DAGISEL64-NEXT:    ;;#ASMEND
; DAGISEL64-NEXT:    v_writelane_b32 v2, s20, 0
; DAGISEL64-NEXT:    ;;#ASMSTART
; DAGISEL64-NEXT:    ; clobber non-CSR
; DAGISEL64-NEXT:    ;;#ASMEND
; DAGISEL64-NEXT:    scratch_load_b32 v40, off, s32 offset:12 ; 4-byte Folded Reload
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    v_cndmask_b32_e32 v0, 5, v0, vcc
; DAGISEL64-NEXT:    v_cndmask_b32_e32 v1, 3, v1, vcc
; DAGISEL64-NEXT:    v_readlane_b32 s20, v2, 0
; DAGISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; DAGISEL64-NEXT:    v_mov_b32_dpp v0, v1 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; DAGISEL64-NEXT:    s_xor_b64 exec, vcc, -1
; DAGISEL64-NEXT:    s_clause 0x3 ; 16-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v2, off, s32
; DAGISEL64-NEXT:    scratch_load_b32 v0, off, s32 offset:4
; DAGISEL64-NEXT:    scratch_load_b32 v1, off, s32 offset:8
; DAGISEL64-NEXT:    scratch_load_b32 v49, off, s32 offset:16
; DAGISEL64-NEXT:    s_mov_b64 exec, vcc
; DAGISEL64-NEXT:    s_wait_loadcnt 0x0
; DAGISEL64-NEXT:    s_wait_alu depctr_va_sdst(0)
; DAGISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL64-LABEL: csr:
; GISEL64:       ; %bb.0:
; GISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL64-NEXT:    s_wait_expcnt 0x0
; GISEL64-NEXT:    s_wait_samplecnt 0x0
; GISEL64-NEXT:    s_wait_bvhcnt 0x0
; GISEL64-NEXT:    s_wait_kmcnt 0x0
; GISEL64-NEXT:    s_xor_saveexec_b64 vcc, -1
; GISEL64-NEXT:    s_clause 0x3 ; 16-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v2, s32
; GISEL64-NEXT:    scratch_store_b32 off, v0, s32 offset:4
; GISEL64-NEXT:    scratch_store_b32 off, v1, s32 offset:8
; GISEL64-NEXT:    scratch_store_b32 off, v49, s32 offset:16
; GISEL64-NEXT:    s_mov_b64 exec, -1
; GISEL64-NEXT:    scratch_store_b32 off, v40, s32 offset:12 ; 4-byte Folded Spill
; GISEL64-NEXT:    ;;#ASMSTART
; GISEL64-NEXT:    ; clobber CSR
; GISEL64-NEXT:    ;;#ASMEND
; GISEL64-NEXT:    v_writelane_b32 v2, s20, 0
; GISEL64-NEXT:    ;;#ASMSTART
; GISEL64-NEXT:    ; clobber non-CSR
; GISEL64-NEXT:    ;;#ASMEND
; GISEL64-NEXT:    scratch_load_b32 v40, off, s32 offset:12 ; 4-byte Folded Reload
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    v_cndmask_b32_e32 v0, 5, v0, vcc
; GISEL64-NEXT:    v_cndmask_b32_e32 v1, 3, v1, vcc
; GISEL64-NEXT:    v_readlane_b32 s20, v2, 0
; GISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GISEL64-NEXT:    v_mov_b32_dpp v0, v1 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; GISEL64-NEXT:    s_xor_b64 exec, vcc, -1
; GISEL64-NEXT:    s_clause 0x3 ; 16-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v2, off, s32
; GISEL64-NEXT:    scratch_load_b32 v0, off, s32 offset:4
; GISEL64-NEXT:    scratch_load_b32 v1, off, s32 offset:8
; GISEL64-NEXT:    scratch_load_b32 v49, off, s32 offset:16
; GISEL64-NEXT:    s_mov_b64 exec, vcc
; GISEL64-NEXT:    s_wait_loadcnt 0x0
; GISEL64-NEXT:    s_wait_alu depctr_va_sdst(0)
; GISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-DAGISEL-LABEL: csr:
; GFX1250-DAGISEL:       ; %bb.0:
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-DAGISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_xor_saveexec_b32 vcc_lo, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x3 ; 16-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v2, s32 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0, s32 offset:4 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:8 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v49, s32 offset:16 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v40, s32 offset:12 nv ; 4-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    ;;#ASMSTART
; GFX1250-DAGISEL-NEXT:    ; clobber CSR
; GFX1250-DAGISEL-NEXT:    ;;#ASMEND
; GFX1250-DAGISEL-NEXT:    v_writelane_b32 v2, s20, 0
; GFX1250-DAGISEL-NEXT:    ;;#ASMSTART
; GFX1250-DAGISEL-NEXT:    ; clobber non-CSR
; GFX1250-DAGISEL-NEXT:    ;;#ASMEND
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v40, off, s32 offset:12 nv ; 4-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    v_dual_cndmask_b32 v0, 5, v0 :: v_dual_cndmask_b32 v1, 3, v1
; GFX1250-DAGISEL-NEXT:    v_readlane_b32 s20, v2, 0
; GFX1250-DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX1250-DAGISEL-NEXT:    v_mov_b32_dpp v0, v1 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_xor_b32 exec_lo, vcc_lo, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x3 ; 16-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v2, off, s32 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0, off, s32 offset:4 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:8 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v49, off, s32 offset:16 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, vcc_lo
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_set_pc_i64 s[30:31]
  %x = select i1 %active, i32 %a, i32 5
  %y = select i1 %active, i32 %b, i32 3
  call void asm sideeffect "; clobber CSR", "~{v40},~{s48}"()
  call void asm sideeffect "; clobber non-CSR", "~{v49},~{s20}"()
  %ret = call i32 @llvm.amdgcn.update.dpp.i32(i32 %x, i32 %y, i32 1, i32 1, i32 1, i1 false)
  ret i32 %ret
}

; Save and restore all lanes of v40.
define amdgpu_gfx_whole_wave void @csr_vgpr_only(i1 %active, i32 %a, i32 %b) #0 {
; DAGISEL-LABEL: csr_vgpr_only:
; DAGISEL:       ; %bb.0:
; DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL-NEXT:    s_wait_expcnt 0x0
; DAGISEL-NEXT:    s_wait_samplecnt 0x0
; DAGISEL-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL-NEXT:    s_wait_kmcnt 0x0
; DAGISEL-NEXT:    s_or_saveexec_b32 s0, -1
; DAGISEL-NEXT:    scratch_store_b32 off, v40, s32 ; 4-byte Folded Spill
; DAGISEL-NEXT:    ;;#ASMSTART
; DAGISEL-NEXT:    ; clobber CSR VGPR
; DAGISEL-NEXT:    ;;#ASMEND
; DAGISEL-NEXT:    scratch_load_b32 v40, off, s32 ; 4-byte Folded Reload
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    s_mov_b32 exec_lo, s0
; DAGISEL-NEXT:    s_wait_loadcnt 0x0
; DAGISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL-LABEL: csr_vgpr_only:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL-NEXT:    s_wait_expcnt 0x0
; GISEL-NEXT:    s_wait_samplecnt 0x0
; GISEL-NEXT:    s_wait_bvhcnt 0x0
; GISEL-NEXT:    s_wait_kmcnt 0x0
; GISEL-NEXT:    s_or_saveexec_b32 s0, -1
; GISEL-NEXT:    scratch_store_b32 off, v40, s32 ; 4-byte Folded Spill
; GISEL-NEXT:    ;;#ASMSTART
; GISEL-NEXT:    ; clobber CSR VGPR
; GISEL-NEXT:    ;;#ASMEND
; GISEL-NEXT:    scratch_load_b32 v40, off, s32 ; 4-byte Folded Reload
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GISEL-NEXT:    s_wait_loadcnt 0x0
; GISEL-NEXT:    s_setpc_b64 s[30:31]
;
; DAGISEL64-LABEL: csr_vgpr_only:
; DAGISEL64:       ; %bb.0:
; DAGISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL64-NEXT:    s_wait_expcnt 0x0
; DAGISEL64-NEXT:    s_wait_samplecnt 0x0
; DAGISEL64-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL64-NEXT:    s_wait_kmcnt 0x0
; DAGISEL64-NEXT:    s_or_saveexec_b64 s[0:1], -1
; DAGISEL64-NEXT:    scratch_store_b32 off, v40, s32 ; 4-byte Folded Spill
; DAGISEL64-NEXT:    ;;#ASMSTART
; DAGISEL64-NEXT:    ; clobber CSR VGPR
; DAGISEL64-NEXT:    ;;#ASMEND
; DAGISEL64-NEXT:    scratch_load_b32 v40, off, s32 ; 4-byte Folded Reload
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    s_mov_b64 exec, s[0:1]
; DAGISEL64-NEXT:    s_wait_loadcnt 0x0
; DAGISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL64-LABEL: csr_vgpr_only:
; GISEL64:       ; %bb.0:
; GISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL64-NEXT:    s_wait_expcnt 0x0
; GISEL64-NEXT:    s_wait_samplecnt 0x0
; GISEL64-NEXT:    s_wait_bvhcnt 0x0
; GISEL64-NEXT:    s_wait_kmcnt 0x0
; GISEL64-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GISEL64-NEXT:    scratch_store_b32 off, v40, s32 ; 4-byte Folded Spill
; GISEL64-NEXT:    ;;#ASMSTART
; GISEL64-NEXT:    ; clobber CSR VGPR
; GISEL64-NEXT:    ;;#ASMEND
; GISEL64-NEXT:    scratch_load_b32 v40, off, s32 ; 4-byte Folded Reload
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    s_mov_b64 exec, s[0:1]
; GISEL64-NEXT:    s_wait_loadcnt 0x0
; GISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-DAGISEL-LABEL: csr_vgpr_only:
; GFX1250-DAGISEL:       ; %bb.0:
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-DAGISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_or_saveexec_b32 s0, -1
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v40, s32 nv ; 4-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    ;;#ASMSTART
; GFX1250-DAGISEL-NEXT:    ; clobber CSR VGPR
; GFX1250-DAGISEL-NEXT:    ;;#ASMEND
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v40, off, s32 nv ; 4-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_set_pc_i64 s[30:31]
  call void asm sideeffect "; clobber CSR VGPR", "~{v40}"()
  ret void
}

define amdgpu_gfx_whole_wave void @sgpr_spill_only(i1 %active, i32 %a, i32 %b) #0 {
; DAGISEL-LABEL: sgpr_spill_only:
; DAGISEL:       ; %bb.0:
; DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL-NEXT:    s_wait_expcnt 0x0
; DAGISEL-NEXT:    s_wait_samplecnt 0x0
; DAGISEL-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL-NEXT:    s_wait_kmcnt 0x0
; DAGISEL-NEXT:    s_xor_saveexec_b32 s0, -1
; DAGISEL-NEXT:    scratch_store_b32 off, v0, s32 ; 4-byte Folded Spill
; DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; DAGISEL-NEXT:    v_writelane_b32 v0, s68, 0
; DAGISEL-NEXT:    ;;#ASMSTART
; DAGISEL-NEXT:    ; clobber CSR SGPR
; DAGISEL-NEXT:    ;;#ASMEND
; DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; DAGISEL-NEXT:    v_readlane_b32 s68, v0, 0
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    s_xor_b32 exec_lo, s0, -1
; DAGISEL-NEXT:    scratch_load_b32 v0, off, s32 ; 4-byte Folded Reload
; DAGISEL-NEXT:    s_mov_b32 exec_lo, s0
; DAGISEL-NEXT:    s_wait_loadcnt 0x0
; DAGISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL-LABEL: sgpr_spill_only:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL-NEXT:    s_wait_expcnt 0x0
; GISEL-NEXT:    s_wait_samplecnt 0x0
; GISEL-NEXT:    s_wait_bvhcnt 0x0
; GISEL-NEXT:    s_wait_kmcnt 0x0
; GISEL-NEXT:    s_xor_saveexec_b32 s0, -1
; GISEL-NEXT:    scratch_store_b32 off, v0, s32 ; 4-byte Folded Spill
; GISEL-NEXT:    s_mov_b32 exec_lo, -1
; GISEL-NEXT:    v_writelane_b32 v0, s68, 0
; GISEL-NEXT:    ;;#ASMSTART
; GISEL-NEXT:    ; clobber CSR SGPR
; GISEL-NEXT:    ;;#ASMEND
; GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GISEL-NEXT:    v_readlane_b32 s68, v0, 0
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    s_xor_b32 exec_lo, s0, -1
; GISEL-NEXT:    scratch_load_b32 v0, off, s32 ; 4-byte Folded Reload
; GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GISEL-NEXT:    s_wait_loadcnt 0x0
; GISEL-NEXT:    s_setpc_b64 s[30:31]
;
; DAGISEL64-LABEL: sgpr_spill_only:
; DAGISEL64:       ; %bb.0:
; DAGISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL64-NEXT:    s_wait_expcnt 0x0
; DAGISEL64-NEXT:    s_wait_samplecnt 0x0
; DAGISEL64-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL64-NEXT:    s_wait_kmcnt 0x0
; DAGISEL64-NEXT:    s_xor_saveexec_b64 s[0:1], -1
; DAGISEL64-NEXT:    scratch_store_b32 off, v0, s32 ; 4-byte Folded Spill
; DAGISEL64-NEXT:    s_mov_b64 exec, -1
; DAGISEL64-NEXT:    v_writelane_b32 v0, s68, 0
; DAGISEL64-NEXT:    ;;#ASMSTART
; DAGISEL64-NEXT:    ; clobber CSR SGPR
; DAGISEL64-NEXT:    ;;#ASMEND
; DAGISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; DAGISEL64-NEXT:    v_readlane_b32 s68, v0, 0
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    s_xor_b64 exec, s[0:1], -1
; DAGISEL64-NEXT:    scratch_load_b32 v0, off, s32 ; 4-byte Folded Reload
; DAGISEL64-NEXT:    s_mov_b64 exec, s[0:1]
; DAGISEL64-NEXT:    s_wait_loadcnt 0x0
; DAGISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL64-LABEL: sgpr_spill_only:
; GISEL64:       ; %bb.0:
; GISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL64-NEXT:    s_wait_expcnt 0x0
; GISEL64-NEXT:    s_wait_samplecnt 0x0
; GISEL64-NEXT:    s_wait_bvhcnt 0x0
; GISEL64-NEXT:    s_wait_kmcnt 0x0
; GISEL64-NEXT:    s_xor_saveexec_b64 s[0:1], -1
; GISEL64-NEXT:    scratch_store_b32 off, v0, s32 ; 4-byte Folded Spill
; GISEL64-NEXT:    s_mov_b64 exec, -1
; GISEL64-NEXT:    v_writelane_b32 v0, s68, 0
; GISEL64-NEXT:    ;;#ASMSTART
; GISEL64-NEXT:    ; clobber CSR SGPR
; GISEL64-NEXT:    ;;#ASMEND
; GISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GISEL64-NEXT:    v_readlane_b32 s68, v0, 0
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    s_xor_b64 exec, s[0:1], -1
; GISEL64-NEXT:    scratch_load_b32 v0, off, s32 ; 4-byte Folded Reload
; GISEL64-NEXT:    s_mov_b64 exec, s[0:1]
; GISEL64-NEXT:    s_wait_loadcnt 0x0
; GISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-DAGISEL-LABEL: sgpr_spill_only:
; GFX1250-DAGISEL:       ; %bb.0:
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-DAGISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_xor_saveexec_b32 s0, -1
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0, s32 nv ; 4-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; GFX1250-DAGISEL-NEXT:    v_writelane_b32 v0, s68, 0
; GFX1250-DAGISEL-NEXT:    ;;#ASMSTART
; GFX1250-DAGISEL-NEXT:    ; clobber CSR SGPR
; GFX1250-DAGISEL-NEXT:    ;;#ASMEND
; GFX1250-DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1250-DAGISEL-NEXT:    v_readlane_b32 s68, v0, 0
; GFX1250-DAGISEL-NEXT:    s_xor_b32 exec_lo, s0, -1
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0, off, s32 nv ; 4-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_set_pc_i64 s[30:31]
  call void asm sideeffect "; clobber CSR SGPR", "~{s68}"()
  ret void
}

define amdgpu_gfx_whole_wave void @realign_stack(i1 %active, i32 %x) #0 {
; DAGISEL-LABEL: realign_stack:
; DAGISEL:       ; %bb.0:
; DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL-NEXT:    s_wait_expcnt 0x0
; DAGISEL-NEXT:    s_wait_samplecnt 0x0
; DAGISEL-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL-NEXT:    s_wait_kmcnt 0x0
; DAGISEL-NEXT:    s_mov_b32 s1, s33
; DAGISEL-NEXT:    s_add_co_i32 s33, s32, 0x3ff
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    s_and_b32 s33, s33, 0xfffffc00
; DAGISEL-NEXT:    s_xor_saveexec_b32 s0, -1
; DAGISEL-NEXT:    s_mov_b32 s2, s34
; DAGISEL-NEXT:    s_mov_b32 s34, s32
; DAGISEL-NEXT:    s_addk_co_i32 s32, 0x800
; DAGISEL-NEXT:    s_wait_storecnt 0x0
; DAGISEL-NEXT:    scratch_store_b32 off, v0, s33 scope:SCOPE_SYS
; DAGISEL-NEXT:    s_wait_storecnt 0x0
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    s_mov_b32 s32, s34
; DAGISEL-NEXT:    s_mov_b32 s34, s2
; DAGISEL-NEXT:    s_mov_b32 exec_lo, s0
; DAGISEL-NEXT:    s_mov_b32 s33, s1
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL-LABEL: realign_stack:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL-NEXT:    s_wait_expcnt 0x0
; GISEL-NEXT:    s_wait_samplecnt 0x0
; GISEL-NEXT:    s_wait_bvhcnt 0x0
; GISEL-NEXT:    s_wait_kmcnt 0x0
; GISEL-NEXT:    s_mov_b32 s1, s33
; GISEL-NEXT:    s_add_co_i32 s33, s32, 0x3ff
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    s_and_b32 s33, s33, 0xfffffc00
; GISEL-NEXT:    s_xor_saveexec_b32 s0, -1
; GISEL-NEXT:    s_mov_b32 s2, s34
; GISEL-NEXT:    s_mov_b32 s34, s32
; GISEL-NEXT:    s_addk_co_i32 s32, 0x800
; GISEL-NEXT:    s_wait_storecnt 0x0
; GISEL-NEXT:    scratch_store_b32 off, v0, s33 scope:SCOPE_SYS
; GISEL-NEXT:    s_wait_storecnt 0x0
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    s_mov_b32 s32, s34
; GISEL-NEXT:    s_mov_b32 s34, s2
; GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GISEL-NEXT:    s_mov_b32 s33, s1
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    s_setpc_b64 s[30:31]
;
; DAGISEL64-LABEL: realign_stack:
; DAGISEL64:       ; %bb.0:
; DAGISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL64-NEXT:    s_wait_expcnt 0x0
; DAGISEL64-NEXT:    s_wait_samplecnt 0x0
; DAGISEL64-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL64-NEXT:    s_wait_kmcnt 0x0
; DAGISEL64-NEXT:    s_mov_b32 s2, s33
; DAGISEL64-NEXT:    s_add_co_i32 s33, s32, 0x3ff
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    s_and_b32 s33, s33, 0xfffffc00
; DAGISEL64-NEXT:    s_xor_saveexec_b64 s[0:1], -1
; DAGISEL64-NEXT:    s_mov_b32 s3, s34
; DAGISEL64-NEXT:    s_mov_b32 s34, s32
; DAGISEL64-NEXT:    s_addk_co_i32 s32, 0x800
; DAGISEL64-NEXT:    s_wait_storecnt 0x0
; DAGISEL64-NEXT:    scratch_store_b32 off, v0, s33 scope:SCOPE_SYS
; DAGISEL64-NEXT:    s_wait_storecnt 0x0
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    s_mov_b32 s32, s34
; DAGISEL64-NEXT:    s_mov_b32 s34, s3
; DAGISEL64-NEXT:    s_mov_b64 exec, s[0:1]
; DAGISEL64-NEXT:    s_mov_b32 s33, s2
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL64-LABEL: realign_stack:
; GISEL64:       ; %bb.0:
; GISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL64-NEXT:    s_wait_expcnt 0x0
; GISEL64-NEXT:    s_wait_samplecnt 0x0
; GISEL64-NEXT:    s_wait_bvhcnt 0x0
; GISEL64-NEXT:    s_wait_kmcnt 0x0
; GISEL64-NEXT:    s_mov_b32 s2, s33
; GISEL64-NEXT:    s_add_co_i32 s33, s32, 0x3ff
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    s_and_b32 s33, s33, 0xfffffc00
; GISEL64-NEXT:    s_xor_saveexec_b64 s[0:1], -1
; GISEL64-NEXT:    s_mov_b32 s3, s34
; GISEL64-NEXT:    s_mov_b32 s34, s32
; GISEL64-NEXT:    s_addk_co_i32 s32, 0x800
; GISEL64-NEXT:    s_wait_storecnt 0x0
; GISEL64-NEXT:    scratch_store_b32 off, v0, s33 scope:SCOPE_SYS
; GISEL64-NEXT:    s_wait_storecnt 0x0
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    s_mov_b32 s32, s34
; GISEL64-NEXT:    s_mov_b32 s34, s3
; GISEL64-NEXT:    s_mov_b64 exec, s[0:1]
; GISEL64-NEXT:    s_mov_b32 s33, s2
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-DAGISEL-LABEL: realign_stack:
; GFX1250-DAGISEL:       ; %bb.0:
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-DAGISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s1, s33
; GFX1250-DAGISEL-NEXT:    s_add_co_i32 s33, s32, 0x3ff
; GFX1250-DAGISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1250-DAGISEL-NEXT:    s_and_b32 s33, s33, 0xfffffc00
; GFX1250-DAGISEL-NEXT:    s_xor_saveexec_b32 s0, -1
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s2, s34
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s34, s32
; GFX1250-DAGISEL-NEXT:    s_addk_co_i32 s32, 0x800
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0, s33 scope:SCOPE_SYS
; GFX1250-DAGISEL-NEXT:    s_wait_storecnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s32, s34
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s34, s2
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s33, s1
; GFX1250-DAGISEL-NEXT:    s_set_pc_i64 s[30:31]
  %fussy = alloca i32, align 1024, addrspace(5)
  store volatile i32 %x, ptr addrspace(5) %fussy, align 1024
  ret void
}

define amdgpu_gfx_whole_wave i32 @multiple_blocks(i1 %active, i32 %a, i32 %b) #0 {
; DAGISEL-LABEL: multiple_blocks:
; DAGISEL:       ; %bb.0:
; DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL-NEXT:    s_wait_expcnt 0x0
; DAGISEL-NEXT:    s_wait_samplecnt 0x0
; DAGISEL-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL-NEXT:    s_wait_kmcnt 0x0
; DAGISEL-NEXT:    s_xor_saveexec_b32 vcc_lo, -1
; DAGISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v0, s32
; DAGISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; DAGISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; DAGISEL-NEXT:    s_mov_b32 s1, exec_lo
; DAGISEL-NEXT:    v_cmpx_eq_u32_e64 v0, v1
; DAGISEL-NEXT:  ; %bb.1: ; %if.then
; DAGISEL-NEXT:    v_add_nc_u32_e32 v1, v0, v1
; DAGISEL-NEXT:  ; %bb.2: ; %if.end
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    s_or_b32 exec_lo, exec_lo, s1
; DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; DAGISEL-NEXT:    v_cndmask_b32_e32 v0, v1, v0, vcc_lo
; DAGISEL-NEXT:    s_xor_b32 exec_lo, vcc_lo, -1
; DAGISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v0, off, s32
; DAGISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; DAGISEL-NEXT:    s_mov_b32 exec_lo, vcc_lo
; DAGISEL-NEXT:    s_wait_loadcnt 0x0
; DAGISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL-LABEL: multiple_blocks:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL-NEXT:    s_wait_expcnt 0x0
; GISEL-NEXT:    s_wait_samplecnt 0x0
; GISEL-NEXT:    s_wait_bvhcnt 0x0
; GISEL-NEXT:    s_wait_kmcnt 0x0
; GISEL-NEXT:    s_xor_saveexec_b32 vcc_lo, -1
; GISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v0, s32
; GISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; GISEL-NEXT:    s_mov_b32 exec_lo, -1
; GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GISEL-NEXT:    s_mov_b32 s1, exec_lo
; GISEL-NEXT:    v_cmpx_eq_u32_e64 v0, v1
; GISEL-NEXT:  ; %bb.1: ; %if.then
; GISEL-NEXT:    v_add_nc_u32_e32 v1, v0, v1
; GISEL-NEXT:  ; %bb.2: ; %if.end
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    s_or_b32 exec_lo, exec_lo, s1
; GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GISEL-NEXT:    v_cndmask_b32_e32 v0, v1, v0, vcc_lo
; GISEL-NEXT:    s_xor_b32 exec_lo, vcc_lo, -1
; GISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v0, off, s32
; GISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; GISEL-NEXT:    s_mov_b32 exec_lo, vcc_lo
; GISEL-NEXT:    s_wait_loadcnt 0x0
; GISEL-NEXT:    s_setpc_b64 s[30:31]
;
; DAGISEL64-LABEL: multiple_blocks:
; DAGISEL64:       ; %bb.0:
; DAGISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL64-NEXT:    s_wait_expcnt 0x0
; DAGISEL64-NEXT:    s_wait_samplecnt 0x0
; DAGISEL64-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL64-NEXT:    s_wait_kmcnt 0x0
; DAGISEL64-NEXT:    s_xor_saveexec_b64 vcc, -1
; DAGISEL64-NEXT:    s_clause 0x1 ; 8-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v0, s32
; DAGISEL64-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; DAGISEL64-NEXT:    s_mov_b64 exec, -1
; DAGISEL64-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; DAGISEL64-NEXT:    s_mov_b64 s[2:3], exec
; DAGISEL64-NEXT:    v_cmpx_eq_u32_e64 v0, v1
; DAGISEL64-NEXT:  ; %bb.1: ; %if.then
; DAGISEL64-NEXT:    v_add_nc_u32_e32 v1, v0, v1
; DAGISEL64-NEXT:  ; %bb.2: ; %if.end
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    s_or_b64 exec, exec, s[2:3]
; DAGISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; DAGISEL64-NEXT:    v_cndmask_b32_e32 v0, v1, v0, vcc
; DAGISEL64-NEXT:    s_xor_b64 exec, vcc, -1
; DAGISEL64-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v0, off, s32
; DAGISEL64-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; DAGISEL64-NEXT:    s_mov_b64 exec, vcc
; DAGISEL64-NEXT:    s_wait_loadcnt 0x0
; DAGISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL64-LABEL: multiple_blocks:
; GISEL64:       ; %bb.0:
; GISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL64-NEXT:    s_wait_expcnt 0x0
; GISEL64-NEXT:    s_wait_samplecnt 0x0
; GISEL64-NEXT:    s_wait_bvhcnt 0x0
; GISEL64-NEXT:    s_wait_kmcnt 0x0
; GISEL64-NEXT:    s_xor_saveexec_b64 vcc, -1
; GISEL64-NEXT:    s_clause 0x1 ; 8-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v0, s32
; GISEL64-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; GISEL64-NEXT:    s_mov_b64 exec, -1
; GISEL64-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GISEL64-NEXT:    s_mov_b64 s[2:3], exec
; GISEL64-NEXT:    v_cmpx_eq_u32_e64 v0, v1
; GISEL64-NEXT:  ; %bb.1: ; %if.then
; GISEL64-NEXT:    v_add_nc_u32_e32 v1, v0, v1
; GISEL64-NEXT:  ; %bb.2: ; %if.end
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    s_or_b64 exec, exec, s[2:3]
; GISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GISEL64-NEXT:    v_cndmask_b32_e32 v0, v1, v0, vcc
; GISEL64-NEXT:    s_xor_b64 exec, vcc, -1
; GISEL64-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v0, off, s32
; GISEL64-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; GISEL64-NEXT:    s_mov_b64 exec, vcc
; GISEL64-NEXT:    s_wait_loadcnt 0x0
; GISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-DAGISEL-LABEL: multiple_blocks:
; GFX1250-DAGISEL:       ; %bb.0:
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-DAGISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_xor_saveexec_b32 vcc_lo, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0, s32 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; GFX1250-DAGISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s1, exec_lo
; GFX1250-DAGISEL-NEXT:    v_cmpx_eq_u32_e64 v0, v1
; GFX1250-DAGISEL-NEXT:  ; %bb.1: ; %if.then
; GFX1250-DAGISEL-NEXT:    v_add_nc_u32_e32 v1, v0, v1
; GFX1250-DAGISEL-NEXT:  ; %bb.2: ; %if.end
; GFX1250-DAGISEL-NEXT:    s_or_b32 exec_lo, exec_lo, s1
; GFX1250-DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1250-DAGISEL-NEXT:    v_cndmask_b32_e32 v0, v1, v0, vcc_lo
; GFX1250-DAGISEL-NEXT:    s_xor_b32 exec_lo, vcc_lo, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0, off, s32 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, vcc_lo
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_set_pc_i64 s[30:31]
  %c = icmp eq i32 %a, %b
  br i1 %c, label %if.then, label %if.end

if.then:                                          ; preds = %0
  %d = add i32 %a, %b
  br label %if.end

if.end:
  %f = phi i32 [ %d, %if.then ], [ %b, %0 ]
  %e = select i1 %active, i32 %a, i32 %f
  ret i32 %e
}

define amdgpu_gfx_whole_wave i64 @ret_64(i1 %active, i64 %a, i64 %b) #0 {
; DAGISEL-LABEL: ret_64:
; DAGISEL:       ; %bb.0:
; DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL-NEXT:    s_wait_expcnt 0x0
; DAGISEL-NEXT:    s_wait_samplecnt 0x0
; DAGISEL-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL-NEXT:    s_wait_kmcnt 0x0
; DAGISEL-NEXT:    s_xor_saveexec_b32 vcc_lo, -1
; DAGISEL-NEXT:    s_clause 0x3 ; 16-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v0, s32
; DAGISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; DAGISEL-NEXT:    scratch_store_b32 off, v2, s32 offset:8
; DAGISEL-NEXT:    scratch_store_b32 off, v3, s32 offset:12
; DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    v_dual_cndmask_b32 v1, 0, v1 :: v_dual_cndmask_b32 v0, 5, v0
; DAGISEL-NEXT:    v_dual_cndmask_b32 v2, 3, v2 :: v_dual_cndmask_b32 v3, 0, v3
; DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_2)
; DAGISEL-NEXT:    v_mov_b32_dpp v0, v2 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; DAGISEL-NEXT:    v_mov_b32_dpp v1, v3 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; DAGISEL-NEXT:    s_xor_b32 exec_lo, vcc_lo, -1
; DAGISEL-NEXT:    s_clause 0x3 ; 16-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v0, off, s32
; DAGISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; DAGISEL-NEXT:    scratch_load_b32 v2, off, s32 offset:8
; DAGISEL-NEXT:    scratch_load_b32 v3, off, s32 offset:12
; DAGISEL-NEXT:    s_mov_b32 exec_lo, vcc_lo
; DAGISEL-NEXT:    s_wait_loadcnt 0x0
; DAGISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL-LABEL: ret_64:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL-NEXT:    s_wait_expcnt 0x0
; GISEL-NEXT:    s_wait_samplecnt 0x0
; GISEL-NEXT:    s_wait_bvhcnt 0x0
; GISEL-NEXT:    s_wait_kmcnt 0x0
; GISEL-NEXT:    s_xor_saveexec_b32 vcc_lo, -1
; GISEL-NEXT:    s_clause 0x3 ; 16-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v0, s32
; GISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; GISEL-NEXT:    scratch_store_b32 off, v2, s32 offset:8
; GISEL-NEXT:    scratch_store_b32 off, v3, s32 offset:12
; GISEL-NEXT:    s_mov_b32 exec_lo, -1
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    v_dual_cndmask_b32 v0, 5, v0 :: v_dual_cndmask_b32 v1, 0, v1
; GISEL-NEXT:    v_dual_cndmask_b32 v2, 3, v2 :: v_dual_cndmask_b32 v3, 0, v3
; GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_2)
; GISEL-NEXT:    v_mov_b32_dpp v0, v2 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; GISEL-NEXT:    v_mov_b32_dpp v1, v3 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; GISEL-NEXT:    s_xor_b32 exec_lo, vcc_lo, -1
; GISEL-NEXT:    s_clause 0x3 ; 16-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v0, off, s32
; GISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; GISEL-NEXT:    scratch_load_b32 v2, off, s32 offset:8
; GISEL-NEXT:    scratch_load_b32 v3, off, s32 offset:12
; GISEL-NEXT:    s_mov_b32 exec_lo, vcc_lo
; GISEL-NEXT:    s_wait_loadcnt 0x0
; GISEL-NEXT:    s_setpc_b64 s[30:31]
;
; DAGISEL64-LABEL: ret_64:
; DAGISEL64:       ; %bb.0:
; DAGISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL64-NEXT:    s_wait_expcnt 0x0
; DAGISEL64-NEXT:    s_wait_samplecnt 0x0
; DAGISEL64-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL64-NEXT:    s_wait_kmcnt 0x0
; DAGISEL64-NEXT:    s_xor_saveexec_b64 vcc, -1
; DAGISEL64-NEXT:    s_clause 0x3 ; 16-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v0, s32
; DAGISEL64-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; DAGISEL64-NEXT:    scratch_store_b32 off, v2, s32 offset:8
; DAGISEL64-NEXT:    scratch_store_b32 off, v3, s32 offset:12
; DAGISEL64-NEXT:    s_mov_b64 exec, -1
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    v_cndmask_b32_e32 v1, 0, v1, vcc
; DAGISEL64-NEXT:    v_cndmask_b32_e32 v0, 5, v0, vcc
; DAGISEL64-NEXT:    v_cndmask_b32_e32 v2, 3, v2, vcc
; DAGISEL64-NEXT:    v_cndmask_b32_e32 v3, 0, v3, vcc
; DAGISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; DAGISEL64-NEXT:    v_mov_b32_dpp v0, v2 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; DAGISEL64-NEXT:    v_mov_b32_dpp v1, v3 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; DAGISEL64-NEXT:    s_xor_b64 exec, vcc, -1
; DAGISEL64-NEXT:    s_clause 0x3 ; 16-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v0, off, s32
; DAGISEL64-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; DAGISEL64-NEXT:    scratch_load_b32 v2, off, s32 offset:8
; DAGISEL64-NEXT:    scratch_load_b32 v3, off, s32 offset:12
; DAGISEL64-NEXT:    s_mov_b64 exec, vcc
; DAGISEL64-NEXT:    s_wait_loadcnt 0x0
; DAGISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL64-LABEL: ret_64:
; GISEL64:       ; %bb.0:
; GISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL64-NEXT:    s_wait_expcnt 0x0
; GISEL64-NEXT:    s_wait_samplecnt 0x0
; GISEL64-NEXT:    s_wait_bvhcnt 0x0
; GISEL64-NEXT:    s_wait_kmcnt 0x0
; GISEL64-NEXT:    s_xor_saveexec_b64 vcc, -1
; GISEL64-NEXT:    s_clause 0x3 ; 16-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v0, s32
; GISEL64-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; GISEL64-NEXT:    scratch_store_b32 off, v2, s32 offset:8
; GISEL64-NEXT:    scratch_store_b32 off, v3, s32 offset:12
; GISEL64-NEXT:    s_mov_b64 exec, -1
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    v_cndmask_b32_e32 v0, 5, v0, vcc
; GISEL64-NEXT:    v_cndmask_b32_e32 v1, 0, v1, vcc
; GISEL64-NEXT:    v_cndmask_b32_e32 v2, 3, v2, vcc
; GISEL64-NEXT:    v_cndmask_b32_e32 v3, 0, v3, vcc
; GISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GISEL64-NEXT:    v_mov_b32_dpp v0, v2 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; GISEL64-NEXT:    v_mov_b32_dpp v1, v3 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; GISEL64-NEXT:    s_xor_b64 exec, vcc, -1
; GISEL64-NEXT:    s_clause 0x3 ; 16-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v0, off, s32
; GISEL64-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; GISEL64-NEXT:    scratch_load_b32 v2, off, s32 offset:8
; GISEL64-NEXT:    scratch_load_b32 v3, off, s32 offset:12
; GISEL64-NEXT:    s_mov_b64 exec, vcc
; GISEL64-NEXT:    s_wait_loadcnt 0x0
; GISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-DAGISEL-LABEL: ret_64:
; GFX1250-DAGISEL:       ; %bb.0:
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-DAGISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_xor_saveexec_b32 vcc_lo, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x3 ; 16-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0, s32 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v2, s32 offset:8 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v3, s32 offset:12 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; GFX1250-DAGISEL-NEXT:    v_dual_cndmask_b32 v1, 0, v1 :: v_dual_cndmask_b32 v0, 5, v0
; GFX1250-DAGISEL-NEXT:    v_dual_cndmask_b32 v2, 3, v2 :: v_dual_cndmask_b32 v3, 0, v3
; GFX1250-DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1250-DAGISEL-NEXT:    v_mov_b32_dpp v0, v2 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; GFX1250-DAGISEL-NEXT:    v_mov_b32_dpp v1, v3 quad_perm:[1,0,0,0] row_mask:0x1 bank_mask:0x1
; GFX1250-DAGISEL-NEXT:    s_xor_b32 exec_lo, vcc_lo, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x3 ; 16-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0, off, s32 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v2, off, s32 offset:8 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v3, off, s32 offset:12 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, vcc_lo
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_set_pc_i64 s[30:31]
  %x = select i1 %active, i64 %a, i64 5
  %y = select i1 %active, i64 %b, i64 3
  %ret = call i64 @llvm.amdgcn.update.dpp.i64(i64 %x, i64 %y, i32 1, i32 1, i32 1, i1 false)
  ret i64 %ret
}

define amdgpu_gfx_whole_wave void @inreg_args(i1 %active, i32 inreg %i32, <4 x i32> inreg %v4i32, float inreg %float, ptr addrspace(5) inreg %ptr, ptr addrspace(5) inreg %ptr2) #0 {
; DAGISEL-LABEL: inreg_args:
; DAGISEL:       ; %bb.0:
; DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL-NEXT:    s_wait_expcnt 0x0
; DAGISEL-NEXT:    s_wait_samplecnt 0x0
; DAGISEL-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL-NEXT:    s_wait_kmcnt 0x0
; DAGISEL-NEXT:    s_xor_saveexec_b32 s0, -1
; DAGISEL-NEXT:    s_clause 0x5 ; 24-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v0, s32
; DAGISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; DAGISEL-NEXT:    scratch_store_b32 off, v2, s32 offset:8
; DAGISEL-NEXT:    scratch_store_b32 off, v3, s32 offset:12
; DAGISEL-NEXT:    scratch_store_b32 off, v4, s32 offset:16
; DAGISEL-NEXT:    scratch_store_b32 off, v5, s32 offset:20
; DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; DAGISEL-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s9
; DAGISEL-NEXT:    v_dual_mov_b32 v0, s5 :: v_dual_mov_b32 v1, s6
; DAGISEL-NEXT:    v_dual_mov_b32 v2, s7 :: v_dual_mov_b32 v3, s8
; DAGISEL-NEXT:    scratch_store_b32 off, v4, s10
; DAGISEL-NEXT:    s_clause 0x1
; DAGISEL-NEXT:    scratch_store_b128 off, v[0:3], s11
; DAGISEL-NEXT:    scratch_store_b32 off, v5, s11
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    s_xor_b32 exec_lo, s0, -1
; DAGISEL-NEXT:    s_clause 0x5 ; 24-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v0, off, s32
; DAGISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; DAGISEL-NEXT:    scratch_load_b32 v2, off, s32 offset:8
; DAGISEL-NEXT:    scratch_load_b32 v3, off, s32 offset:12
; DAGISEL-NEXT:    scratch_load_b32 v4, off, s32 offset:16
; DAGISEL-NEXT:    scratch_load_b32 v5, off, s32 offset:20
; DAGISEL-NEXT:    s_mov_b32 exec_lo, s0
; DAGISEL-NEXT:    s_wait_loadcnt 0x0
; DAGISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL-LABEL: inreg_args:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL-NEXT:    s_wait_expcnt 0x0
; GISEL-NEXT:    s_wait_samplecnt 0x0
; GISEL-NEXT:    s_wait_bvhcnt 0x0
; GISEL-NEXT:    s_wait_kmcnt 0x0
; GISEL-NEXT:    s_xor_saveexec_b32 s34, -1
; GISEL-NEXT:    s_clause 0x5 ; 24-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v0, s32
; GISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; GISEL-NEXT:    scratch_store_b32 off, v2, s32 offset:8
; GISEL-NEXT:    scratch_store_b32 off, v3, s32 offset:12
; GISEL-NEXT:    scratch_store_b32 off, v4, s32 offset:16
; GISEL-NEXT:    scratch_store_b32 off, v5, s32 offset:20
; GISEL-NEXT:    s_mov_b32 exec_lo, -1
; GISEL-NEXT:    s_mov_b32 s0, s5
; GISEL-NEXT:    s_mov_b32 s1, s6
; GISEL-NEXT:    s_mov_b32 s2, s7
; GISEL-NEXT:    s_mov_b32 s3, s8
; GISEL-NEXT:    v_mov_b32_e32 v4, s4
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v3, s3
; GISEL-NEXT:    v_dual_mov_b32 v1, s1 :: v_dual_mov_b32 v2, s2
; GISEL-NEXT:    v_mov_b32_e32 v5, s9
; GISEL-NEXT:    scratch_store_b32 off, v4, s10
; GISEL-NEXT:    s_clause 0x1
; GISEL-NEXT:    scratch_store_b128 off, v[0:3], s11
; GISEL-NEXT:    scratch_store_b32 off, v5, s11
; GISEL-NEXT:    s_xor_b32 exec_lo, s34, -1
; GISEL-NEXT:    s_clause 0x5 ; 24-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v0, off, s32
; GISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; GISEL-NEXT:    scratch_load_b32 v2, off, s32 offset:8
; GISEL-NEXT:    scratch_load_b32 v3, off, s32 offset:12
; GISEL-NEXT:    scratch_load_b32 v4, off, s32 offset:16
; GISEL-NEXT:    scratch_load_b32 v5, off, s32 offset:20
; GISEL-NEXT:    s_mov_b32 exec_lo, s34
; GISEL-NEXT:    s_wait_loadcnt 0x0
; GISEL-NEXT:    s_setpc_b64 s[30:31]
;
; DAGISEL64-LABEL: inreg_args:
; DAGISEL64:       ; %bb.0:
; DAGISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL64-NEXT:    s_wait_expcnt 0x0
; DAGISEL64-NEXT:    s_wait_samplecnt 0x0
; DAGISEL64-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL64-NEXT:    s_wait_kmcnt 0x0
; DAGISEL64-NEXT:    s_xor_saveexec_b64 s[0:1], -1
; DAGISEL64-NEXT:    s_clause 0x5 ; 24-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v0, s32
; DAGISEL64-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; DAGISEL64-NEXT:    scratch_store_b32 off, v2, s32 offset:8
; DAGISEL64-NEXT:    scratch_store_b32 off, v3, s32 offset:12
; DAGISEL64-NEXT:    scratch_store_b32 off, v4, s32 offset:16
; DAGISEL64-NEXT:    scratch_store_b32 off, v5, s32 offset:20
; DAGISEL64-NEXT:    s_mov_b64 exec, -1
; DAGISEL64-NEXT:    v_mov_b32_e32 v4, s4
; DAGISEL64-NEXT:    v_mov_b32_e32 v0, s5
; DAGISEL64-NEXT:    v_mov_b32_e32 v1, s6
; DAGISEL64-NEXT:    v_mov_b32_e32 v2, s7
; DAGISEL64-NEXT:    v_mov_b32_e32 v3, s8
; DAGISEL64-NEXT:    v_mov_b32_e32 v5, s9
; DAGISEL64-NEXT:    scratch_store_b32 off, v4, s10
; DAGISEL64-NEXT:    s_clause 0x1
; DAGISEL64-NEXT:    scratch_store_b128 off, v[0:3], s11
; DAGISEL64-NEXT:    scratch_store_b32 off, v5, s11
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    s_xor_b64 exec, s[0:1], -1
; DAGISEL64-NEXT:    s_clause 0x5 ; 24-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v0, off, s32
; DAGISEL64-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; DAGISEL64-NEXT:    scratch_load_b32 v2, off, s32 offset:8
; DAGISEL64-NEXT:    scratch_load_b32 v3, off, s32 offset:12
; DAGISEL64-NEXT:    scratch_load_b32 v4, off, s32 offset:16
; DAGISEL64-NEXT:    scratch_load_b32 v5, off, s32 offset:20
; DAGISEL64-NEXT:    s_mov_b64 exec, s[0:1]
; DAGISEL64-NEXT:    s_wait_loadcnt 0x0
; DAGISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL64-LABEL: inreg_args:
; GISEL64:       ; %bb.0:
; GISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL64-NEXT:    s_wait_expcnt 0x0
; GISEL64-NEXT:    s_wait_samplecnt 0x0
; GISEL64-NEXT:    s_wait_bvhcnt 0x0
; GISEL64-NEXT:    s_wait_kmcnt 0x0
; GISEL64-NEXT:    s_xor_saveexec_b64 s[34:35], -1
; GISEL64-NEXT:    s_clause 0x5 ; 24-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v0, s32
; GISEL64-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; GISEL64-NEXT:    scratch_store_b32 off, v2, s32 offset:8
; GISEL64-NEXT:    scratch_store_b32 off, v3, s32 offset:12
; GISEL64-NEXT:    scratch_store_b32 off, v4, s32 offset:16
; GISEL64-NEXT:    scratch_store_b32 off, v5, s32 offset:20
; GISEL64-NEXT:    s_mov_b64 exec, -1
; GISEL64-NEXT:    s_mov_b32 s0, s5
; GISEL64-NEXT:    s_mov_b32 s1, s6
; GISEL64-NEXT:    s_mov_b32 s2, s7
; GISEL64-NEXT:    s_mov_b32 s3, s8
; GISEL64-NEXT:    v_mov_b32_e32 v4, s4
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    v_mov_b32_e32 v0, s0
; GISEL64-NEXT:    v_mov_b32_e32 v1, s1
; GISEL64-NEXT:    v_mov_b32_e32 v2, s2
; GISEL64-NEXT:    v_mov_b32_e32 v3, s3
; GISEL64-NEXT:    v_mov_b32_e32 v5, s9
; GISEL64-NEXT:    scratch_store_b32 off, v4, s10
; GISEL64-NEXT:    s_clause 0x1
; GISEL64-NEXT:    scratch_store_b128 off, v[0:3], s11
; GISEL64-NEXT:    scratch_store_b32 off, v5, s11
; GISEL64-NEXT:    s_xor_b64 exec, s[34:35], -1
; GISEL64-NEXT:    s_clause 0x5 ; 24-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v0, off, s32
; GISEL64-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; GISEL64-NEXT:    scratch_load_b32 v2, off, s32 offset:8
; GISEL64-NEXT:    scratch_load_b32 v3, off, s32 offset:12
; GISEL64-NEXT:    scratch_load_b32 v4, off, s32 offset:16
; GISEL64-NEXT:    scratch_load_b32 v5, off, s32 offset:20
; GISEL64-NEXT:    s_mov_b64 exec, s[34:35]
; GISEL64-NEXT:    s_wait_loadcnt 0x0
; GISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-DAGISEL-LABEL: inreg_args:
; GFX1250-DAGISEL:       ; %bb.0:
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-DAGISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_xor_saveexec_b32 s0, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x5 ; 24-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0, s32 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v2, s32 offset:8 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v3, s32 offset:12 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v4, s32 offset:16 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v5, s32 offset:20 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; GFX1250-DAGISEL-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s9
; GFX1250-DAGISEL-NEXT:    v_dual_mov_b32 v0, s5 :: v_dual_mov_b32 v1, s6
; GFX1250-DAGISEL-NEXT:    v_dual_mov_b32 v2, s7 :: v_dual_mov_b32 v3, s8
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v4, s10
; GFX1250-DAGISEL-NEXT:    s_clause 0x1
; GFX1250-DAGISEL-NEXT:    scratch_store_b128 off, v[0:3], s11
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v5, s11
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_xor_b32 exec_lo, s0, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x5 ; 24-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0, off, s32 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v2, off, s32 offset:8 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v3, off, s32 offset:12 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v4, off, s32 offset:16 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v5, off, s32 offset:20 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_set_pc_i64 s[30:31]
  store i32 %i32, ptr addrspace(5) %ptr
  store <4 x i32> %v4i32, ptr addrspace(5) %ptr2
  store float %float, ptr addrspace(5) %ptr2
  ret void
}

declare amdgpu_gfx <2 x half> @gfx_callee(<2 x half> %x, <2 x half> %y)

define amdgpu_gfx_whole_wave <2 x half> @call_gfx_from_whole_wave(i1 %active, <2 x half> %x, <2 x half> %y) #0 {
; DAGISEL-LABEL: call_gfx_from_whole_wave:
; DAGISEL:       ; %bb.0:
; DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL-NEXT:    s_wait_expcnt 0x0
; DAGISEL-NEXT:    s_wait_samplecnt 0x0
; DAGISEL-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL-NEXT:    s_wait_kmcnt 0x0
; DAGISEL-NEXT:    s_mov_b32 s0, s33
; DAGISEL-NEXT:    s_mov_b32 s33, s32
; DAGISEL-NEXT:    s_xor_saveexec_b32 s4, -1
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v0, s33 offset:4
; DAGISEL-NEXT:    scratch_store_b32 off, v1, s33 offset:8
; DAGISEL-NEXT:    scratch_store_b32 off, v2, s33 offset:12
; DAGISEL-NEXT:    scratch_store_b32 off, v3, s33 offset:16
; DAGISEL-NEXT:    scratch_store_b32 off, v4, s33 offset:20
; DAGISEL-NEXT:    scratch_store_b32 off, v5, s33 offset:24
; DAGISEL-NEXT:    scratch_store_b32 off, v6, s33 offset:28
; DAGISEL-NEXT:    scratch_store_b32 off, v7, s33 offset:32
; DAGISEL-NEXT:    scratch_store_b32 off, v8, s33 offset:36
; DAGISEL-NEXT:    scratch_store_b32 off, v9, s33 offset:40
; DAGISEL-NEXT:    scratch_store_b32 off, v10, s33 offset:44
; DAGISEL-NEXT:    scratch_store_b32 off, v11, s33 offset:48
; DAGISEL-NEXT:    scratch_store_b32 off, v12, s33 offset:52
; DAGISEL-NEXT:    scratch_store_b32 off, v13, s33 offset:56
; DAGISEL-NEXT:    scratch_store_b32 off, v14, s33 offset:60
; DAGISEL-NEXT:    scratch_store_b32 off, v15, s33 offset:64
; DAGISEL-NEXT:    scratch_store_b32 off, v16, s33 offset:68
; DAGISEL-NEXT:    scratch_store_b32 off, v17, s33 offset:72
; DAGISEL-NEXT:    scratch_store_b32 off, v18, s33 offset:76
; DAGISEL-NEXT:    scratch_store_b32 off, v19, s33 offset:80
; DAGISEL-NEXT:    scratch_store_b32 off, v20, s33 offset:84
; DAGISEL-NEXT:    scratch_store_b32 off, v21, s33 offset:88
; DAGISEL-NEXT:    scratch_store_b32 off, v22, s33 offset:92
; DAGISEL-NEXT:    scratch_store_b32 off, v23, s33 offset:96
; DAGISEL-NEXT:    scratch_store_b32 off, v24, s33 offset:100
; DAGISEL-NEXT:    scratch_store_b32 off, v25, s33 offset:104
; DAGISEL-NEXT:    scratch_store_b32 off, v26, s33 offset:108
; DAGISEL-NEXT:    scratch_store_b32 off, v27, s33 offset:112
; DAGISEL-NEXT:    scratch_store_b32 off, v28, s33 offset:116
; DAGISEL-NEXT:    scratch_store_b32 off, v29, s33 offset:120
; DAGISEL-NEXT:    scratch_store_b32 off, v30, s33 offset:124
; DAGISEL-NEXT:    scratch_store_b32 off, v31, s33 offset:128
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v32, s33 offset:132
; DAGISEL-NEXT:    scratch_store_b32 off, v33, s33 offset:136
; DAGISEL-NEXT:    scratch_store_b32 off, v34, s33 offset:140
; DAGISEL-NEXT:    scratch_store_b32 off, v35, s33 offset:144
; DAGISEL-NEXT:    scratch_store_b32 off, v36, s33 offset:148
; DAGISEL-NEXT:    scratch_store_b32 off, v37, s33 offset:152
; DAGISEL-NEXT:    scratch_store_b32 off, v38, s33 offset:156
; DAGISEL-NEXT:    scratch_store_b32 off, v39, s33 offset:160
; DAGISEL-NEXT:    scratch_store_b32 off, v48, s33 offset:164
; DAGISEL-NEXT:    scratch_store_b32 off, v49, s33 offset:168
; DAGISEL-NEXT:    scratch_store_b32 off, v50, s33 offset:172
; DAGISEL-NEXT:    scratch_store_b32 off, v51, s33 offset:176
; DAGISEL-NEXT:    scratch_store_b32 off, v52, s33 offset:180
; DAGISEL-NEXT:    scratch_store_b32 off, v53, s33 offset:184
; DAGISEL-NEXT:    scratch_store_b32 off, v54, s33 offset:188
; DAGISEL-NEXT:    scratch_store_b32 off, v55, s33 offset:192
; DAGISEL-NEXT:    scratch_store_b32 off, v64, s33 offset:196
; DAGISEL-NEXT:    scratch_store_b32 off, v65, s33 offset:200
; DAGISEL-NEXT:    scratch_store_b32 off, v66, s33 offset:204
; DAGISEL-NEXT:    scratch_store_b32 off, v67, s33 offset:208
; DAGISEL-NEXT:    scratch_store_b32 off, v68, s33 offset:212
; DAGISEL-NEXT:    scratch_store_b32 off, v69, s33 offset:216
; DAGISEL-NEXT:    scratch_store_b32 off, v70, s33 offset:220
; DAGISEL-NEXT:    scratch_store_b32 off, v71, s33 offset:224
; DAGISEL-NEXT:    scratch_store_b32 off, v80, s33 offset:228
; DAGISEL-NEXT:    scratch_store_b32 off, v81, s33 offset:232
; DAGISEL-NEXT:    scratch_store_b32 off, v82, s33 offset:236
; DAGISEL-NEXT:    scratch_store_b32 off, v83, s33 offset:240
; DAGISEL-NEXT:    scratch_store_b32 off, v84, s33 offset:244
; DAGISEL-NEXT:    scratch_store_b32 off, v85, s33 offset:248
; DAGISEL-NEXT:    scratch_store_b32 off, v86, s33 offset:252
; DAGISEL-NEXT:    scratch_store_b32 off, v87, s33 offset:256
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v96, s33 offset:260
; DAGISEL-NEXT:    scratch_store_b32 off, v97, s33 offset:264
; DAGISEL-NEXT:    scratch_store_b32 off, v98, s33 offset:268
; DAGISEL-NEXT:    scratch_store_b32 off, v99, s33 offset:272
; DAGISEL-NEXT:    scratch_store_b32 off, v100, s33 offset:276
; DAGISEL-NEXT:    scratch_store_b32 off, v101, s33 offset:280
; DAGISEL-NEXT:    scratch_store_b32 off, v102, s33 offset:284
; DAGISEL-NEXT:    scratch_store_b32 off, v103, s33 offset:288
; DAGISEL-NEXT:    scratch_store_b32 off, v112, s33 offset:292
; DAGISEL-NEXT:    scratch_store_b32 off, v113, s33 offset:296
; DAGISEL-NEXT:    scratch_store_b32 off, v114, s33 offset:300
; DAGISEL-NEXT:    scratch_store_b32 off, v115, s33 offset:304
; DAGISEL-NEXT:    scratch_store_b32 off, v116, s33 offset:308
; DAGISEL-NEXT:    scratch_store_b32 off, v117, s33 offset:312
; DAGISEL-NEXT:    scratch_store_b32 off, v118, s33 offset:316
; DAGISEL-NEXT:    scratch_store_b32 off, v119, s33 offset:320
; DAGISEL-NEXT:    scratch_store_b32 off, v128, s33 offset:324
; DAGISEL-NEXT:    scratch_store_b32 off, v129, s33 offset:328
; DAGISEL-NEXT:    scratch_store_b32 off, v130, s33 offset:332
; DAGISEL-NEXT:    scratch_store_b32 off, v131, s33 offset:336
; DAGISEL-NEXT:    scratch_store_b32 off, v132, s33 offset:340
; DAGISEL-NEXT:    scratch_store_b32 off, v133, s33 offset:344
; DAGISEL-NEXT:    scratch_store_b32 off, v134, s33 offset:348
; DAGISEL-NEXT:    scratch_store_b32 off, v135, s33 offset:352
; DAGISEL-NEXT:    scratch_store_b32 off, v144, s33 offset:356
; DAGISEL-NEXT:    scratch_store_b32 off, v145, s33 offset:360
; DAGISEL-NEXT:    scratch_store_b32 off, v146, s33 offset:364
; DAGISEL-NEXT:    scratch_store_b32 off, v147, s33 offset:368
; DAGISEL-NEXT:    scratch_store_b32 off, v148, s33 offset:372
; DAGISEL-NEXT:    scratch_store_b32 off, v149, s33 offset:376
; DAGISEL-NEXT:    scratch_store_b32 off, v150, s33 offset:380
; DAGISEL-NEXT:    scratch_store_b32 off, v151, s33 offset:384
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v160, s33 offset:388
; DAGISEL-NEXT:    scratch_store_b32 off, v161, s33 offset:392
; DAGISEL-NEXT:    scratch_store_b32 off, v162, s33 offset:396
; DAGISEL-NEXT:    scratch_store_b32 off, v163, s33 offset:400
; DAGISEL-NEXT:    scratch_store_b32 off, v164, s33 offset:404
; DAGISEL-NEXT:    scratch_store_b32 off, v165, s33 offset:408
; DAGISEL-NEXT:    scratch_store_b32 off, v166, s33 offset:412
; DAGISEL-NEXT:    scratch_store_b32 off, v167, s33 offset:416
; DAGISEL-NEXT:    scratch_store_b32 off, v176, s33 offset:420
; DAGISEL-NEXT:    scratch_store_b32 off, v177, s33 offset:424
; DAGISEL-NEXT:    scratch_store_b32 off, v178, s33 offset:428
; DAGISEL-NEXT:    scratch_store_b32 off, v179, s33 offset:432
; DAGISEL-NEXT:    scratch_store_b32 off, v180, s33 offset:436
; DAGISEL-NEXT:    scratch_store_b32 off, v181, s33 offset:440
; DAGISEL-NEXT:    scratch_store_b32 off, v182, s33 offset:444
; DAGISEL-NEXT:    scratch_store_b32 off, v183, s33 offset:448
; DAGISEL-NEXT:    scratch_store_b32 off, v192, s33 offset:452
; DAGISEL-NEXT:    scratch_store_b32 off, v193, s33 offset:456
; DAGISEL-NEXT:    scratch_store_b32 off, v194, s33 offset:460
; DAGISEL-NEXT:    scratch_store_b32 off, v195, s33 offset:464
; DAGISEL-NEXT:    scratch_store_b32 off, v196, s33 offset:468
; DAGISEL-NEXT:    scratch_store_b32 off, v197, s33 offset:472
; DAGISEL-NEXT:    scratch_store_b32 off, v198, s33 offset:476
; DAGISEL-NEXT:    scratch_store_b32 off, v199, s33 offset:480
; DAGISEL-NEXT:    scratch_store_b32 off, v208, s33 offset:484
; DAGISEL-NEXT:    scratch_store_b32 off, v209, s33 offset:488
; DAGISEL-NEXT:    scratch_store_b32 off, v210, s33 offset:492
; DAGISEL-NEXT:    scratch_store_b32 off, v211, s33 offset:496
; DAGISEL-NEXT:    scratch_store_b32 off, v212, s33 offset:500
; DAGISEL-NEXT:    scratch_store_b32 off, v213, s33 offset:504
; DAGISEL-NEXT:    scratch_store_b32 off, v214, s33 offset:508
; DAGISEL-NEXT:    scratch_store_b32 off, v215, s33 offset:512
; DAGISEL-NEXT:    s_clause 0xf ; 64-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v224, s33 offset:516
; DAGISEL-NEXT:    scratch_store_b32 off, v225, s33 offset:520
; DAGISEL-NEXT:    scratch_store_b32 off, v226, s33 offset:524
; DAGISEL-NEXT:    scratch_store_b32 off, v227, s33 offset:528
; DAGISEL-NEXT:    scratch_store_b32 off, v228, s33 offset:532
; DAGISEL-NEXT:    scratch_store_b32 off, v229, s33 offset:536
; DAGISEL-NEXT:    scratch_store_b32 off, v230, s33 offset:540
; DAGISEL-NEXT:    scratch_store_b32 off, v231, s33 offset:544
; DAGISEL-NEXT:    scratch_store_b32 off, v240, s33 offset:548
; DAGISEL-NEXT:    scratch_store_b32 off, v241, s33 offset:552
; DAGISEL-NEXT:    scratch_store_b32 off, v242, s33 offset:556
; DAGISEL-NEXT:    scratch_store_b32 off, v243, s33 offset:560
; DAGISEL-NEXT:    scratch_store_b32 off, v244, s33 offset:564
; DAGISEL-NEXT:    scratch_store_b32 off, v245, s33 offset:568
; DAGISEL-NEXT:    scratch_store_b32 off, v246, s33 offset:572
; DAGISEL-NEXT:    scratch_store_b32 off, v247, s33 offset:576
; DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; DAGISEL-NEXT:    scratch_store_b32 off, v40, s33 ; 4-byte Folded Spill
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    v_writelane_b32 v40, s0, 3
; DAGISEL-NEXT:    v_mov_b32_e32 v2, v0
; DAGISEL-NEXT:    v_swap_b32 v0, v1
; DAGISEL-NEXT:    s_mov_b32 s1, gfx_callee@abs32@hi
; DAGISEL-NEXT:    v_writelane_b32 v40, s4, 0
; DAGISEL-NEXT:    s_mov_b32 s0, gfx_callee@abs32@lo
; DAGISEL-NEXT:    s_addk_co_i32 s32, 0x250
; DAGISEL-NEXT:    v_writelane_b32 v40, s30, 1
; DAGISEL-NEXT:    v_writelane_b32 v40, s31, 2
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    s_swappc_b64 s[30:31], s[0:1]
; DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; DAGISEL-NEXT:    v_readlane_b32 s30, v40, 1
; DAGISEL-NEXT:    v_readlane_b32 s31, v40, 2
; DAGISEL-NEXT:    v_readlane_b32 s4, v40, 0
; DAGISEL-NEXT:    v_readlane_b32 s0, v40, 3
; DAGISEL-NEXT:    scratch_load_b32 v40, off, s33 ; 4-byte Folded Reload
; DAGISEL-NEXT:    s_mov_b32 s32, s33
; DAGISEL-NEXT:    s_xor_b32 exec_lo, s4, -1
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v0, off, s33 offset:4
; DAGISEL-NEXT:    scratch_load_b32 v1, off, s33 offset:8
; DAGISEL-NEXT:    scratch_load_b32 v2, off, s33 offset:12
; DAGISEL-NEXT:    scratch_load_b32 v3, off, s33 offset:16
; DAGISEL-NEXT:    scratch_load_b32 v4, off, s33 offset:20
; DAGISEL-NEXT:    scratch_load_b32 v5, off, s33 offset:24
; DAGISEL-NEXT:    scratch_load_b32 v6, off, s33 offset:28
; DAGISEL-NEXT:    scratch_load_b32 v7, off, s33 offset:32
; DAGISEL-NEXT:    scratch_load_b32 v8, off, s33 offset:36
; DAGISEL-NEXT:    scratch_load_b32 v9, off, s33 offset:40
; DAGISEL-NEXT:    scratch_load_b32 v10, off, s33 offset:44
; DAGISEL-NEXT:    scratch_load_b32 v11, off, s33 offset:48
; DAGISEL-NEXT:    scratch_load_b32 v12, off, s33 offset:52
; DAGISEL-NEXT:    scratch_load_b32 v13, off, s33 offset:56
; DAGISEL-NEXT:    scratch_load_b32 v14, off, s33 offset:60
; DAGISEL-NEXT:    scratch_load_b32 v15, off, s33 offset:64
; DAGISEL-NEXT:    scratch_load_b32 v16, off, s33 offset:68
; DAGISEL-NEXT:    scratch_load_b32 v17, off, s33 offset:72
; DAGISEL-NEXT:    scratch_load_b32 v18, off, s33 offset:76
; DAGISEL-NEXT:    scratch_load_b32 v19, off, s33 offset:80
; DAGISEL-NEXT:    scratch_load_b32 v20, off, s33 offset:84
; DAGISEL-NEXT:    scratch_load_b32 v21, off, s33 offset:88
; DAGISEL-NEXT:    scratch_load_b32 v22, off, s33 offset:92
; DAGISEL-NEXT:    scratch_load_b32 v23, off, s33 offset:96
; DAGISEL-NEXT:    scratch_load_b32 v24, off, s33 offset:100
; DAGISEL-NEXT:    scratch_load_b32 v25, off, s33 offset:104
; DAGISEL-NEXT:    scratch_load_b32 v26, off, s33 offset:108
; DAGISEL-NEXT:    scratch_load_b32 v27, off, s33 offset:112
; DAGISEL-NEXT:    scratch_load_b32 v28, off, s33 offset:116
; DAGISEL-NEXT:    scratch_load_b32 v29, off, s33 offset:120
; DAGISEL-NEXT:    scratch_load_b32 v30, off, s33 offset:124
; DAGISEL-NEXT:    scratch_load_b32 v31, off, s33 offset:128
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v32, off, s33 offset:132
; DAGISEL-NEXT:    scratch_load_b32 v33, off, s33 offset:136
; DAGISEL-NEXT:    scratch_load_b32 v34, off, s33 offset:140
; DAGISEL-NEXT:    scratch_load_b32 v35, off, s33 offset:144
; DAGISEL-NEXT:    scratch_load_b32 v36, off, s33 offset:148
; DAGISEL-NEXT:    scratch_load_b32 v37, off, s33 offset:152
; DAGISEL-NEXT:    scratch_load_b32 v38, off, s33 offset:156
; DAGISEL-NEXT:    scratch_load_b32 v39, off, s33 offset:160
; DAGISEL-NEXT:    scratch_load_b32 v48, off, s33 offset:164
; DAGISEL-NEXT:    scratch_load_b32 v49, off, s33 offset:168
; DAGISEL-NEXT:    scratch_load_b32 v50, off, s33 offset:172
; DAGISEL-NEXT:    scratch_load_b32 v51, off, s33 offset:176
; DAGISEL-NEXT:    scratch_load_b32 v52, off, s33 offset:180
; DAGISEL-NEXT:    scratch_load_b32 v53, off, s33 offset:184
; DAGISEL-NEXT:    scratch_load_b32 v54, off, s33 offset:188
; DAGISEL-NEXT:    scratch_load_b32 v55, off, s33 offset:192
; DAGISEL-NEXT:    scratch_load_b32 v64, off, s33 offset:196
; DAGISEL-NEXT:    scratch_load_b32 v65, off, s33 offset:200
; DAGISEL-NEXT:    scratch_load_b32 v66, off, s33 offset:204
; DAGISEL-NEXT:    scratch_load_b32 v67, off, s33 offset:208
; DAGISEL-NEXT:    scratch_load_b32 v68, off, s33 offset:212
; DAGISEL-NEXT:    scratch_load_b32 v69, off, s33 offset:216
; DAGISEL-NEXT:    scratch_load_b32 v70, off, s33 offset:220
; DAGISEL-NEXT:    scratch_load_b32 v71, off, s33 offset:224
; DAGISEL-NEXT:    scratch_load_b32 v80, off, s33 offset:228
; DAGISEL-NEXT:    scratch_load_b32 v81, off, s33 offset:232
; DAGISEL-NEXT:    scratch_load_b32 v82, off, s33 offset:236
; DAGISEL-NEXT:    scratch_load_b32 v83, off, s33 offset:240
; DAGISEL-NEXT:    scratch_load_b32 v84, off, s33 offset:244
; DAGISEL-NEXT:    scratch_load_b32 v85, off, s33 offset:248
; DAGISEL-NEXT:    scratch_load_b32 v86, off, s33 offset:252
; DAGISEL-NEXT:    scratch_load_b32 v87, off, s33 offset:256
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v96, off, s33 offset:260
; DAGISEL-NEXT:    scratch_load_b32 v97, off, s33 offset:264
; DAGISEL-NEXT:    scratch_load_b32 v98, off, s33 offset:268
; DAGISEL-NEXT:    scratch_load_b32 v99, off, s33 offset:272
; DAGISEL-NEXT:    scratch_load_b32 v100, off, s33 offset:276
; DAGISEL-NEXT:    scratch_load_b32 v101, off, s33 offset:280
; DAGISEL-NEXT:    scratch_load_b32 v102, off, s33 offset:284
; DAGISEL-NEXT:    scratch_load_b32 v103, off, s33 offset:288
; DAGISEL-NEXT:    scratch_load_b32 v112, off, s33 offset:292
; DAGISEL-NEXT:    scratch_load_b32 v113, off, s33 offset:296
; DAGISEL-NEXT:    scratch_load_b32 v114, off, s33 offset:300
; DAGISEL-NEXT:    scratch_load_b32 v115, off, s33 offset:304
; DAGISEL-NEXT:    scratch_load_b32 v116, off, s33 offset:308
; DAGISEL-NEXT:    scratch_load_b32 v117, off, s33 offset:312
; DAGISEL-NEXT:    scratch_load_b32 v118, off, s33 offset:316
; DAGISEL-NEXT:    scratch_load_b32 v119, off, s33 offset:320
; DAGISEL-NEXT:    scratch_load_b32 v128, off, s33 offset:324
; DAGISEL-NEXT:    scratch_load_b32 v129, off, s33 offset:328
; DAGISEL-NEXT:    scratch_load_b32 v130, off, s33 offset:332
; DAGISEL-NEXT:    scratch_load_b32 v131, off, s33 offset:336
; DAGISEL-NEXT:    scratch_load_b32 v132, off, s33 offset:340
; DAGISEL-NEXT:    scratch_load_b32 v133, off, s33 offset:344
; DAGISEL-NEXT:    scratch_load_b32 v134, off, s33 offset:348
; DAGISEL-NEXT:    scratch_load_b32 v135, off, s33 offset:352
; DAGISEL-NEXT:    scratch_load_b32 v144, off, s33 offset:356
; DAGISEL-NEXT:    scratch_load_b32 v145, off, s33 offset:360
; DAGISEL-NEXT:    scratch_load_b32 v146, off, s33 offset:364
; DAGISEL-NEXT:    scratch_load_b32 v147, off, s33 offset:368
; DAGISEL-NEXT:    scratch_load_b32 v148, off, s33 offset:372
; DAGISEL-NEXT:    scratch_load_b32 v149, off, s33 offset:376
; DAGISEL-NEXT:    scratch_load_b32 v150, off, s33 offset:380
; DAGISEL-NEXT:    scratch_load_b32 v151, off, s33 offset:384
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v160, off, s33 offset:388
; DAGISEL-NEXT:    scratch_load_b32 v161, off, s33 offset:392
; DAGISEL-NEXT:    scratch_load_b32 v162, off, s33 offset:396
; DAGISEL-NEXT:    scratch_load_b32 v163, off, s33 offset:400
; DAGISEL-NEXT:    scratch_load_b32 v164, off, s33 offset:404
; DAGISEL-NEXT:    scratch_load_b32 v165, off, s33 offset:408
; DAGISEL-NEXT:    scratch_load_b32 v166, off, s33 offset:412
; DAGISEL-NEXT:    scratch_load_b32 v167, off, s33 offset:416
; DAGISEL-NEXT:    scratch_load_b32 v176, off, s33 offset:420
; DAGISEL-NEXT:    scratch_load_b32 v177, off, s33 offset:424
; DAGISEL-NEXT:    scratch_load_b32 v178, off, s33 offset:428
; DAGISEL-NEXT:    scratch_load_b32 v179, off, s33 offset:432
; DAGISEL-NEXT:    scratch_load_b32 v180, off, s33 offset:436
; DAGISEL-NEXT:    scratch_load_b32 v181, off, s33 offset:440
; DAGISEL-NEXT:    scratch_load_b32 v182, off, s33 offset:444
; DAGISEL-NEXT:    scratch_load_b32 v183, off, s33 offset:448
; DAGISEL-NEXT:    scratch_load_b32 v192, off, s33 offset:452
; DAGISEL-NEXT:    scratch_load_b32 v193, off, s33 offset:456
; DAGISEL-NEXT:    scratch_load_b32 v194, off, s33 offset:460
; DAGISEL-NEXT:    scratch_load_b32 v195, off, s33 offset:464
; DAGISEL-NEXT:    scratch_load_b32 v196, off, s33 offset:468
; DAGISEL-NEXT:    scratch_load_b32 v197, off, s33 offset:472
; DAGISEL-NEXT:    scratch_load_b32 v198, off, s33 offset:476
; DAGISEL-NEXT:    scratch_load_b32 v199, off, s33 offset:480
; DAGISEL-NEXT:    scratch_load_b32 v208, off, s33 offset:484
; DAGISEL-NEXT:    scratch_load_b32 v209, off, s33 offset:488
; DAGISEL-NEXT:    scratch_load_b32 v210, off, s33 offset:492
; DAGISEL-NEXT:    scratch_load_b32 v211, off, s33 offset:496
; DAGISEL-NEXT:    scratch_load_b32 v212, off, s33 offset:500
; DAGISEL-NEXT:    scratch_load_b32 v213, off, s33 offset:504
; DAGISEL-NEXT:    scratch_load_b32 v214, off, s33 offset:508
; DAGISEL-NEXT:    scratch_load_b32 v215, off, s33 offset:512
; DAGISEL-NEXT:    s_clause 0xf ; 64-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v224, off, s33 offset:516
; DAGISEL-NEXT:    scratch_load_b32 v225, off, s33 offset:520
; DAGISEL-NEXT:    scratch_load_b32 v226, off, s33 offset:524
; DAGISEL-NEXT:    scratch_load_b32 v227, off, s33 offset:528
; DAGISEL-NEXT:    scratch_load_b32 v228, off, s33 offset:532
; DAGISEL-NEXT:    scratch_load_b32 v229, off, s33 offset:536
; DAGISEL-NEXT:    scratch_load_b32 v230, off, s33 offset:540
; DAGISEL-NEXT:    scratch_load_b32 v231, off, s33 offset:544
; DAGISEL-NEXT:    scratch_load_b32 v240, off, s33 offset:548
; DAGISEL-NEXT:    scratch_load_b32 v241, off, s33 offset:552
; DAGISEL-NEXT:    scratch_load_b32 v242, off, s33 offset:556
; DAGISEL-NEXT:    scratch_load_b32 v243, off, s33 offset:560
; DAGISEL-NEXT:    scratch_load_b32 v244, off, s33 offset:564
; DAGISEL-NEXT:    scratch_load_b32 v245, off, s33 offset:568
; DAGISEL-NEXT:    scratch_load_b32 v246, off, s33 offset:572
; DAGISEL-NEXT:    scratch_load_b32 v247, off, s33 offset:576
; DAGISEL-NEXT:    s_mov_b32 exec_lo, s4
; DAGISEL-NEXT:    s_mov_b32 s33, s0
; DAGISEL-NEXT:    s_wait_loadcnt 0x0
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL-LABEL: call_gfx_from_whole_wave:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL-NEXT:    s_wait_expcnt 0x0
; GISEL-NEXT:    s_wait_samplecnt 0x0
; GISEL-NEXT:    s_wait_bvhcnt 0x0
; GISEL-NEXT:    s_wait_kmcnt 0x0
; GISEL-NEXT:    s_mov_b32 s0, s33
; GISEL-NEXT:    s_mov_b32 s33, s32
; GISEL-NEXT:    s_xor_saveexec_b32 s4, -1
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v0, s33 offset:4
; GISEL-NEXT:    scratch_store_b32 off, v1, s33 offset:8
; GISEL-NEXT:    scratch_store_b32 off, v2, s33 offset:12
; GISEL-NEXT:    scratch_store_b32 off, v3, s33 offset:16
; GISEL-NEXT:    scratch_store_b32 off, v4, s33 offset:20
; GISEL-NEXT:    scratch_store_b32 off, v5, s33 offset:24
; GISEL-NEXT:    scratch_store_b32 off, v6, s33 offset:28
; GISEL-NEXT:    scratch_store_b32 off, v7, s33 offset:32
; GISEL-NEXT:    scratch_store_b32 off, v8, s33 offset:36
; GISEL-NEXT:    scratch_store_b32 off, v9, s33 offset:40
; GISEL-NEXT:    scratch_store_b32 off, v10, s33 offset:44
; GISEL-NEXT:    scratch_store_b32 off, v11, s33 offset:48
; GISEL-NEXT:    scratch_store_b32 off, v12, s33 offset:52
; GISEL-NEXT:    scratch_store_b32 off, v13, s33 offset:56
; GISEL-NEXT:    scratch_store_b32 off, v14, s33 offset:60
; GISEL-NEXT:    scratch_store_b32 off, v15, s33 offset:64
; GISEL-NEXT:    scratch_store_b32 off, v16, s33 offset:68
; GISEL-NEXT:    scratch_store_b32 off, v17, s33 offset:72
; GISEL-NEXT:    scratch_store_b32 off, v18, s33 offset:76
; GISEL-NEXT:    scratch_store_b32 off, v19, s33 offset:80
; GISEL-NEXT:    scratch_store_b32 off, v20, s33 offset:84
; GISEL-NEXT:    scratch_store_b32 off, v21, s33 offset:88
; GISEL-NEXT:    scratch_store_b32 off, v22, s33 offset:92
; GISEL-NEXT:    scratch_store_b32 off, v23, s33 offset:96
; GISEL-NEXT:    scratch_store_b32 off, v24, s33 offset:100
; GISEL-NEXT:    scratch_store_b32 off, v25, s33 offset:104
; GISEL-NEXT:    scratch_store_b32 off, v26, s33 offset:108
; GISEL-NEXT:    scratch_store_b32 off, v27, s33 offset:112
; GISEL-NEXT:    scratch_store_b32 off, v28, s33 offset:116
; GISEL-NEXT:    scratch_store_b32 off, v29, s33 offset:120
; GISEL-NEXT:    scratch_store_b32 off, v30, s33 offset:124
; GISEL-NEXT:    scratch_store_b32 off, v31, s33 offset:128
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v32, s33 offset:132
; GISEL-NEXT:    scratch_store_b32 off, v33, s33 offset:136
; GISEL-NEXT:    scratch_store_b32 off, v34, s33 offset:140
; GISEL-NEXT:    scratch_store_b32 off, v35, s33 offset:144
; GISEL-NEXT:    scratch_store_b32 off, v36, s33 offset:148
; GISEL-NEXT:    scratch_store_b32 off, v37, s33 offset:152
; GISEL-NEXT:    scratch_store_b32 off, v38, s33 offset:156
; GISEL-NEXT:    scratch_store_b32 off, v39, s33 offset:160
; GISEL-NEXT:    scratch_store_b32 off, v48, s33 offset:164
; GISEL-NEXT:    scratch_store_b32 off, v49, s33 offset:168
; GISEL-NEXT:    scratch_store_b32 off, v50, s33 offset:172
; GISEL-NEXT:    scratch_store_b32 off, v51, s33 offset:176
; GISEL-NEXT:    scratch_store_b32 off, v52, s33 offset:180
; GISEL-NEXT:    scratch_store_b32 off, v53, s33 offset:184
; GISEL-NEXT:    scratch_store_b32 off, v54, s33 offset:188
; GISEL-NEXT:    scratch_store_b32 off, v55, s33 offset:192
; GISEL-NEXT:    scratch_store_b32 off, v64, s33 offset:196
; GISEL-NEXT:    scratch_store_b32 off, v65, s33 offset:200
; GISEL-NEXT:    scratch_store_b32 off, v66, s33 offset:204
; GISEL-NEXT:    scratch_store_b32 off, v67, s33 offset:208
; GISEL-NEXT:    scratch_store_b32 off, v68, s33 offset:212
; GISEL-NEXT:    scratch_store_b32 off, v69, s33 offset:216
; GISEL-NEXT:    scratch_store_b32 off, v70, s33 offset:220
; GISEL-NEXT:    scratch_store_b32 off, v71, s33 offset:224
; GISEL-NEXT:    scratch_store_b32 off, v80, s33 offset:228
; GISEL-NEXT:    scratch_store_b32 off, v81, s33 offset:232
; GISEL-NEXT:    scratch_store_b32 off, v82, s33 offset:236
; GISEL-NEXT:    scratch_store_b32 off, v83, s33 offset:240
; GISEL-NEXT:    scratch_store_b32 off, v84, s33 offset:244
; GISEL-NEXT:    scratch_store_b32 off, v85, s33 offset:248
; GISEL-NEXT:    scratch_store_b32 off, v86, s33 offset:252
; GISEL-NEXT:    scratch_store_b32 off, v87, s33 offset:256
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v96, s33 offset:260
; GISEL-NEXT:    scratch_store_b32 off, v97, s33 offset:264
; GISEL-NEXT:    scratch_store_b32 off, v98, s33 offset:268
; GISEL-NEXT:    scratch_store_b32 off, v99, s33 offset:272
; GISEL-NEXT:    scratch_store_b32 off, v100, s33 offset:276
; GISEL-NEXT:    scratch_store_b32 off, v101, s33 offset:280
; GISEL-NEXT:    scratch_store_b32 off, v102, s33 offset:284
; GISEL-NEXT:    scratch_store_b32 off, v103, s33 offset:288
; GISEL-NEXT:    scratch_store_b32 off, v112, s33 offset:292
; GISEL-NEXT:    scratch_store_b32 off, v113, s33 offset:296
; GISEL-NEXT:    scratch_store_b32 off, v114, s33 offset:300
; GISEL-NEXT:    scratch_store_b32 off, v115, s33 offset:304
; GISEL-NEXT:    scratch_store_b32 off, v116, s33 offset:308
; GISEL-NEXT:    scratch_store_b32 off, v117, s33 offset:312
; GISEL-NEXT:    scratch_store_b32 off, v118, s33 offset:316
; GISEL-NEXT:    scratch_store_b32 off, v119, s33 offset:320
; GISEL-NEXT:    scratch_store_b32 off, v128, s33 offset:324
; GISEL-NEXT:    scratch_store_b32 off, v129, s33 offset:328
; GISEL-NEXT:    scratch_store_b32 off, v130, s33 offset:332
; GISEL-NEXT:    scratch_store_b32 off, v131, s33 offset:336
; GISEL-NEXT:    scratch_store_b32 off, v132, s33 offset:340
; GISEL-NEXT:    scratch_store_b32 off, v133, s33 offset:344
; GISEL-NEXT:    scratch_store_b32 off, v134, s33 offset:348
; GISEL-NEXT:    scratch_store_b32 off, v135, s33 offset:352
; GISEL-NEXT:    scratch_store_b32 off, v144, s33 offset:356
; GISEL-NEXT:    scratch_store_b32 off, v145, s33 offset:360
; GISEL-NEXT:    scratch_store_b32 off, v146, s33 offset:364
; GISEL-NEXT:    scratch_store_b32 off, v147, s33 offset:368
; GISEL-NEXT:    scratch_store_b32 off, v148, s33 offset:372
; GISEL-NEXT:    scratch_store_b32 off, v149, s33 offset:376
; GISEL-NEXT:    scratch_store_b32 off, v150, s33 offset:380
; GISEL-NEXT:    scratch_store_b32 off, v151, s33 offset:384
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v160, s33 offset:388
; GISEL-NEXT:    scratch_store_b32 off, v161, s33 offset:392
; GISEL-NEXT:    scratch_store_b32 off, v162, s33 offset:396
; GISEL-NEXT:    scratch_store_b32 off, v163, s33 offset:400
; GISEL-NEXT:    scratch_store_b32 off, v164, s33 offset:404
; GISEL-NEXT:    scratch_store_b32 off, v165, s33 offset:408
; GISEL-NEXT:    scratch_store_b32 off, v166, s33 offset:412
; GISEL-NEXT:    scratch_store_b32 off, v167, s33 offset:416
; GISEL-NEXT:    scratch_store_b32 off, v176, s33 offset:420
; GISEL-NEXT:    scratch_store_b32 off, v177, s33 offset:424
; GISEL-NEXT:    scratch_store_b32 off, v178, s33 offset:428
; GISEL-NEXT:    scratch_store_b32 off, v179, s33 offset:432
; GISEL-NEXT:    scratch_store_b32 off, v180, s33 offset:436
; GISEL-NEXT:    scratch_store_b32 off, v181, s33 offset:440
; GISEL-NEXT:    scratch_store_b32 off, v182, s33 offset:444
; GISEL-NEXT:    scratch_store_b32 off, v183, s33 offset:448
; GISEL-NEXT:    scratch_store_b32 off, v192, s33 offset:452
; GISEL-NEXT:    scratch_store_b32 off, v193, s33 offset:456
; GISEL-NEXT:    scratch_store_b32 off, v194, s33 offset:460
; GISEL-NEXT:    scratch_store_b32 off, v195, s33 offset:464
; GISEL-NEXT:    scratch_store_b32 off, v196, s33 offset:468
; GISEL-NEXT:    scratch_store_b32 off, v197, s33 offset:472
; GISEL-NEXT:    scratch_store_b32 off, v198, s33 offset:476
; GISEL-NEXT:    scratch_store_b32 off, v199, s33 offset:480
; GISEL-NEXT:    scratch_store_b32 off, v208, s33 offset:484
; GISEL-NEXT:    scratch_store_b32 off, v209, s33 offset:488
; GISEL-NEXT:    scratch_store_b32 off, v210, s33 offset:492
; GISEL-NEXT:    scratch_store_b32 off, v211, s33 offset:496
; GISEL-NEXT:    scratch_store_b32 off, v212, s33 offset:500
; GISEL-NEXT:    scratch_store_b32 off, v213, s33 offset:504
; GISEL-NEXT:    scratch_store_b32 off, v214, s33 offset:508
; GISEL-NEXT:    scratch_store_b32 off, v215, s33 offset:512
; GISEL-NEXT:    s_clause 0xf ; 64-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v224, s33 offset:516
; GISEL-NEXT:    scratch_store_b32 off, v225, s33 offset:520
; GISEL-NEXT:    scratch_store_b32 off, v226, s33 offset:524
; GISEL-NEXT:    scratch_store_b32 off, v227, s33 offset:528
; GISEL-NEXT:    scratch_store_b32 off, v228, s33 offset:532
; GISEL-NEXT:    scratch_store_b32 off, v229, s33 offset:536
; GISEL-NEXT:    scratch_store_b32 off, v230, s33 offset:540
; GISEL-NEXT:    scratch_store_b32 off, v231, s33 offset:544
; GISEL-NEXT:    scratch_store_b32 off, v240, s33 offset:548
; GISEL-NEXT:    scratch_store_b32 off, v241, s33 offset:552
; GISEL-NEXT:    scratch_store_b32 off, v242, s33 offset:556
; GISEL-NEXT:    scratch_store_b32 off, v243, s33 offset:560
; GISEL-NEXT:    scratch_store_b32 off, v244, s33 offset:564
; GISEL-NEXT:    scratch_store_b32 off, v245, s33 offset:568
; GISEL-NEXT:    scratch_store_b32 off, v246, s33 offset:572
; GISEL-NEXT:    scratch_store_b32 off, v247, s33 offset:576
; GISEL-NEXT:    s_mov_b32 exec_lo, -1
; GISEL-NEXT:    scratch_store_b32 off, v40, s33 ; 4-byte Folded Spill
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    v_writelane_b32 v40, s0, 3
; GISEL-NEXT:    v_mov_b32_e32 v2, v0
; GISEL-NEXT:    v_swap_b32 v0, v1
; GISEL-NEXT:    s_mov_b32 s0, gfx_callee@abs32@lo
; GISEL-NEXT:    v_writelane_b32 v40, s4, 0
; GISEL-NEXT:    s_mov_b32 s1, gfx_callee@abs32@hi
; GISEL-NEXT:    s_addk_co_i32 s32, 0x250
; GISEL-NEXT:    v_writelane_b32 v40, s30, 1
; GISEL-NEXT:    v_writelane_b32 v40, s31, 2
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    s_swappc_b64 s[30:31], s[0:1]
; GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GISEL-NEXT:    v_readlane_b32 s30, v40, 1
; GISEL-NEXT:    v_readlane_b32 s31, v40, 2
; GISEL-NEXT:    v_readlane_b32 s4, v40, 0
; GISEL-NEXT:    v_readlane_b32 s0, v40, 3
; GISEL-NEXT:    scratch_load_b32 v40, off, s33 ; 4-byte Folded Reload
; GISEL-NEXT:    s_mov_b32 s32, s33
; GISEL-NEXT:    s_xor_b32 exec_lo, s4, -1
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v0, off, s33 offset:4
; GISEL-NEXT:    scratch_load_b32 v1, off, s33 offset:8
; GISEL-NEXT:    scratch_load_b32 v2, off, s33 offset:12
; GISEL-NEXT:    scratch_load_b32 v3, off, s33 offset:16
; GISEL-NEXT:    scratch_load_b32 v4, off, s33 offset:20
; GISEL-NEXT:    scratch_load_b32 v5, off, s33 offset:24
; GISEL-NEXT:    scratch_load_b32 v6, off, s33 offset:28
; GISEL-NEXT:    scratch_load_b32 v7, off, s33 offset:32
; GISEL-NEXT:    scratch_load_b32 v8, off, s33 offset:36
; GISEL-NEXT:    scratch_load_b32 v9, off, s33 offset:40
; GISEL-NEXT:    scratch_load_b32 v10, off, s33 offset:44
; GISEL-NEXT:    scratch_load_b32 v11, off, s33 offset:48
; GISEL-NEXT:    scratch_load_b32 v12, off, s33 offset:52
; GISEL-NEXT:    scratch_load_b32 v13, off, s33 offset:56
; GISEL-NEXT:    scratch_load_b32 v14, off, s33 offset:60
; GISEL-NEXT:    scratch_load_b32 v15, off, s33 offset:64
; GISEL-NEXT:    scratch_load_b32 v16, off, s33 offset:68
; GISEL-NEXT:    scratch_load_b32 v17, off, s33 offset:72
; GISEL-NEXT:    scratch_load_b32 v18, off, s33 offset:76
; GISEL-NEXT:    scratch_load_b32 v19, off, s33 offset:80
; GISEL-NEXT:    scratch_load_b32 v20, off, s33 offset:84
; GISEL-NEXT:    scratch_load_b32 v21, off, s33 offset:88
; GISEL-NEXT:    scratch_load_b32 v22, off, s33 offset:92
; GISEL-NEXT:    scratch_load_b32 v23, off, s33 offset:96
; GISEL-NEXT:    scratch_load_b32 v24, off, s33 offset:100
; GISEL-NEXT:    scratch_load_b32 v25, off, s33 offset:104
; GISEL-NEXT:    scratch_load_b32 v26, off, s33 offset:108
; GISEL-NEXT:    scratch_load_b32 v27, off, s33 offset:112
; GISEL-NEXT:    scratch_load_b32 v28, off, s33 offset:116
; GISEL-NEXT:    scratch_load_b32 v29, off, s33 offset:120
; GISEL-NEXT:    scratch_load_b32 v30, off, s33 offset:124
; GISEL-NEXT:    scratch_load_b32 v31, off, s33 offset:128
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v32, off, s33 offset:132
; GISEL-NEXT:    scratch_load_b32 v33, off, s33 offset:136
; GISEL-NEXT:    scratch_load_b32 v34, off, s33 offset:140
; GISEL-NEXT:    scratch_load_b32 v35, off, s33 offset:144
; GISEL-NEXT:    scratch_load_b32 v36, off, s33 offset:148
; GISEL-NEXT:    scratch_load_b32 v37, off, s33 offset:152
; GISEL-NEXT:    scratch_load_b32 v38, off, s33 offset:156
; GISEL-NEXT:    scratch_load_b32 v39, off, s33 offset:160
; GISEL-NEXT:    scratch_load_b32 v48, off, s33 offset:164
; GISEL-NEXT:    scratch_load_b32 v49, off, s33 offset:168
; GISEL-NEXT:    scratch_load_b32 v50, off, s33 offset:172
; GISEL-NEXT:    scratch_load_b32 v51, off, s33 offset:176
; GISEL-NEXT:    scratch_load_b32 v52, off, s33 offset:180
; GISEL-NEXT:    scratch_load_b32 v53, off, s33 offset:184
; GISEL-NEXT:    scratch_load_b32 v54, off, s33 offset:188
; GISEL-NEXT:    scratch_load_b32 v55, off, s33 offset:192
; GISEL-NEXT:    scratch_load_b32 v64, off, s33 offset:196
; GISEL-NEXT:    scratch_load_b32 v65, off, s33 offset:200
; GISEL-NEXT:    scratch_load_b32 v66, off, s33 offset:204
; GISEL-NEXT:    scratch_load_b32 v67, off, s33 offset:208
; GISEL-NEXT:    scratch_load_b32 v68, off, s33 offset:212
; GISEL-NEXT:    scratch_load_b32 v69, off, s33 offset:216
; GISEL-NEXT:    scratch_load_b32 v70, off, s33 offset:220
; GISEL-NEXT:    scratch_load_b32 v71, off, s33 offset:224
; GISEL-NEXT:    scratch_load_b32 v80, off, s33 offset:228
; GISEL-NEXT:    scratch_load_b32 v81, off, s33 offset:232
; GISEL-NEXT:    scratch_load_b32 v82, off, s33 offset:236
; GISEL-NEXT:    scratch_load_b32 v83, off, s33 offset:240
; GISEL-NEXT:    scratch_load_b32 v84, off, s33 offset:244
; GISEL-NEXT:    scratch_load_b32 v85, off, s33 offset:248
; GISEL-NEXT:    scratch_load_b32 v86, off, s33 offset:252
; GISEL-NEXT:    scratch_load_b32 v87, off, s33 offset:256
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v96, off, s33 offset:260
; GISEL-NEXT:    scratch_load_b32 v97, off, s33 offset:264
; GISEL-NEXT:    scratch_load_b32 v98, off, s33 offset:268
; GISEL-NEXT:    scratch_load_b32 v99, off, s33 offset:272
; GISEL-NEXT:    scratch_load_b32 v100, off, s33 offset:276
; GISEL-NEXT:    scratch_load_b32 v101, off, s33 offset:280
; GISEL-NEXT:    scratch_load_b32 v102, off, s33 offset:284
; GISEL-NEXT:    scratch_load_b32 v103, off, s33 offset:288
; GISEL-NEXT:    scratch_load_b32 v112, off, s33 offset:292
; GISEL-NEXT:    scratch_load_b32 v113, off, s33 offset:296
; GISEL-NEXT:    scratch_load_b32 v114, off, s33 offset:300
; GISEL-NEXT:    scratch_load_b32 v115, off, s33 offset:304
; GISEL-NEXT:    scratch_load_b32 v116, off, s33 offset:308
; GISEL-NEXT:    scratch_load_b32 v117, off, s33 offset:312
; GISEL-NEXT:    scratch_load_b32 v118, off, s33 offset:316
; GISEL-NEXT:    scratch_load_b32 v119, off, s33 offset:320
; GISEL-NEXT:    scratch_load_b32 v128, off, s33 offset:324
; GISEL-NEXT:    scratch_load_b32 v129, off, s33 offset:328
; GISEL-NEXT:    scratch_load_b32 v130, off, s33 offset:332
; GISEL-NEXT:    scratch_load_b32 v131, off, s33 offset:336
; GISEL-NEXT:    scratch_load_b32 v132, off, s33 offset:340
; GISEL-NEXT:    scratch_load_b32 v133, off, s33 offset:344
; GISEL-NEXT:    scratch_load_b32 v134, off, s33 offset:348
; GISEL-NEXT:    scratch_load_b32 v135, off, s33 offset:352
; GISEL-NEXT:    scratch_load_b32 v144, off, s33 offset:356
; GISEL-NEXT:    scratch_load_b32 v145, off, s33 offset:360
; GISEL-NEXT:    scratch_load_b32 v146, off, s33 offset:364
; GISEL-NEXT:    scratch_load_b32 v147, off, s33 offset:368
; GISEL-NEXT:    scratch_load_b32 v148, off, s33 offset:372
; GISEL-NEXT:    scratch_load_b32 v149, off, s33 offset:376
; GISEL-NEXT:    scratch_load_b32 v150, off, s33 offset:380
; GISEL-NEXT:    scratch_load_b32 v151, off, s33 offset:384
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v160, off, s33 offset:388
; GISEL-NEXT:    scratch_load_b32 v161, off, s33 offset:392
; GISEL-NEXT:    scratch_load_b32 v162, off, s33 offset:396
; GISEL-NEXT:    scratch_load_b32 v163, off, s33 offset:400
; GISEL-NEXT:    scratch_load_b32 v164, off, s33 offset:404
; GISEL-NEXT:    scratch_load_b32 v165, off, s33 offset:408
; GISEL-NEXT:    scratch_load_b32 v166, off, s33 offset:412
; GISEL-NEXT:    scratch_load_b32 v167, off, s33 offset:416
; GISEL-NEXT:    scratch_load_b32 v176, off, s33 offset:420
; GISEL-NEXT:    scratch_load_b32 v177, off, s33 offset:424
; GISEL-NEXT:    scratch_load_b32 v178, off, s33 offset:428
; GISEL-NEXT:    scratch_load_b32 v179, off, s33 offset:432
; GISEL-NEXT:    scratch_load_b32 v180, off, s33 offset:436
; GISEL-NEXT:    scratch_load_b32 v181, off, s33 offset:440
; GISEL-NEXT:    scratch_load_b32 v182, off, s33 offset:444
; GISEL-NEXT:    scratch_load_b32 v183, off, s33 offset:448
; GISEL-NEXT:    scratch_load_b32 v192, off, s33 offset:452
; GISEL-NEXT:    scratch_load_b32 v193, off, s33 offset:456
; GISEL-NEXT:    scratch_load_b32 v194, off, s33 offset:460
; GISEL-NEXT:    scratch_load_b32 v195, off, s33 offset:464
; GISEL-NEXT:    scratch_load_b32 v196, off, s33 offset:468
; GISEL-NEXT:    scratch_load_b32 v197, off, s33 offset:472
; GISEL-NEXT:    scratch_load_b32 v198, off, s33 offset:476
; GISEL-NEXT:    scratch_load_b32 v199, off, s33 offset:480
; GISEL-NEXT:    scratch_load_b32 v208, off, s33 offset:484
; GISEL-NEXT:    scratch_load_b32 v209, off, s33 offset:488
; GISEL-NEXT:    scratch_load_b32 v210, off, s33 offset:492
; GISEL-NEXT:    scratch_load_b32 v211, off, s33 offset:496
; GISEL-NEXT:    scratch_load_b32 v212, off, s33 offset:500
; GISEL-NEXT:    scratch_load_b32 v213, off, s33 offset:504
; GISEL-NEXT:    scratch_load_b32 v214, off, s33 offset:508
; GISEL-NEXT:    scratch_load_b32 v215, off, s33 offset:512
; GISEL-NEXT:    s_clause 0xf ; 64-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v224, off, s33 offset:516
; GISEL-NEXT:    scratch_load_b32 v225, off, s33 offset:520
; GISEL-NEXT:    scratch_load_b32 v226, off, s33 offset:524
; GISEL-NEXT:    scratch_load_b32 v227, off, s33 offset:528
; GISEL-NEXT:    scratch_load_b32 v228, off, s33 offset:532
; GISEL-NEXT:    scratch_load_b32 v229, off, s33 offset:536
; GISEL-NEXT:    scratch_load_b32 v230, off, s33 offset:540
; GISEL-NEXT:    scratch_load_b32 v231, off, s33 offset:544
; GISEL-NEXT:    scratch_load_b32 v240, off, s33 offset:548
; GISEL-NEXT:    scratch_load_b32 v241, off, s33 offset:552
; GISEL-NEXT:    scratch_load_b32 v242, off, s33 offset:556
; GISEL-NEXT:    scratch_load_b32 v243, off, s33 offset:560
; GISEL-NEXT:    scratch_load_b32 v244, off, s33 offset:564
; GISEL-NEXT:    scratch_load_b32 v245, off, s33 offset:568
; GISEL-NEXT:    scratch_load_b32 v246, off, s33 offset:572
; GISEL-NEXT:    scratch_load_b32 v247, off, s33 offset:576
; GISEL-NEXT:    s_mov_b32 exec_lo, s4
; GISEL-NEXT:    s_mov_b32 s33, s0
; GISEL-NEXT:    s_wait_loadcnt 0x0
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    s_setpc_b64 s[30:31]
;
; DAGISEL64-LABEL: call_gfx_from_whole_wave:
; DAGISEL64:       ; %bb.0:
; DAGISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL64-NEXT:    s_wait_expcnt 0x0
; DAGISEL64-NEXT:    s_wait_samplecnt 0x0
; DAGISEL64-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL64-NEXT:    s_wait_kmcnt 0x0
; DAGISEL64-NEXT:    s_mov_b32 s0, s33
; DAGISEL64-NEXT:    s_mov_b32 s33, s32
; DAGISEL64-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v0, s33 offset:4
; DAGISEL64-NEXT:    scratch_store_b32 off, v1, s33 offset:8
; DAGISEL64-NEXT:    scratch_store_b32 off, v2, s33 offset:12
; DAGISEL64-NEXT:    scratch_store_b32 off, v3, s33 offset:16
; DAGISEL64-NEXT:    scratch_store_b32 off, v4, s33 offset:20
; DAGISEL64-NEXT:    scratch_store_b32 off, v5, s33 offset:24
; DAGISEL64-NEXT:    scratch_store_b32 off, v6, s33 offset:28
; DAGISEL64-NEXT:    scratch_store_b32 off, v7, s33 offset:32
; DAGISEL64-NEXT:    scratch_store_b32 off, v8, s33 offset:36
; DAGISEL64-NEXT:    scratch_store_b32 off, v9, s33 offset:40
; DAGISEL64-NEXT:    scratch_store_b32 off, v10, s33 offset:44
; DAGISEL64-NEXT:    scratch_store_b32 off, v11, s33 offset:48
; DAGISEL64-NEXT:    scratch_store_b32 off, v12, s33 offset:52
; DAGISEL64-NEXT:    scratch_store_b32 off, v13, s33 offset:56
; DAGISEL64-NEXT:    scratch_store_b32 off, v14, s33 offset:60
; DAGISEL64-NEXT:    scratch_store_b32 off, v15, s33 offset:64
; DAGISEL64-NEXT:    scratch_store_b32 off, v16, s33 offset:68
; DAGISEL64-NEXT:    scratch_store_b32 off, v17, s33 offset:72
; DAGISEL64-NEXT:    scratch_store_b32 off, v18, s33 offset:76
; DAGISEL64-NEXT:    scratch_store_b32 off, v19, s33 offset:80
; DAGISEL64-NEXT:    scratch_store_b32 off, v20, s33 offset:84
; DAGISEL64-NEXT:    scratch_store_b32 off, v21, s33 offset:88
; DAGISEL64-NEXT:    scratch_store_b32 off, v22, s33 offset:92
; DAGISEL64-NEXT:    scratch_store_b32 off, v23, s33 offset:96
; DAGISEL64-NEXT:    scratch_store_b32 off, v24, s33 offset:100
; DAGISEL64-NEXT:    scratch_store_b32 off, v25, s33 offset:104
; DAGISEL64-NEXT:    scratch_store_b32 off, v26, s33 offset:108
; DAGISEL64-NEXT:    scratch_store_b32 off, v27, s33 offset:112
; DAGISEL64-NEXT:    scratch_store_b32 off, v28, s33 offset:116
; DAGISEL64-NEXT:    scratch_store_b32 off, v29, s33 offset:120
; DAGISEL64-NEXT:    scratch_store_b32 off, v30, s33 offset:124
; DAGISEL64-NEXT:    scratch_store_b32 off, v31, s33 offset:128
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v32, s33 offset:132
; DAGISEL64-NEXT:    scratch_store_b32 off, v33, s33 offset:136
; DAGISEL64-NEXT:    scratch_store_b32 off, v34, s33 offset:140
; DAGISEL64-NEXT:    scratch_store_b32 off, v35, s33 offset:144
; DAGISEL64-NEXT:    scratch_store_b32 off, v36, s33 offset:148
; DAGISEL64-NEXT:    scratch_store_b32 off, v37, s33 offset:152
; DAGISEL64-NEXT:    scratch_store_b32 off, v38, s33 offset:156
; DAGISEL64-NEXT:    scratch_store_b32 off, v39, s33 offset:160
; DAGISEL64-NEXT:    scratch_store_b32 off, v48, s33 offset:164
; DAGISEL64-NEXT:    scratch_store_b32 off, v49, s33 offset:168
; DAGISEL64-NEXT:    scratch_store_b32 off, v50, s33 offset:172
; DAGISEL64-NEXT:    scratch_store_b32 off, v51, s33 offset:176
; DAGISEL64-NEXT:    scratch_store_b32 off, v52, s33 offset:180
; DAGISEL64-NEXT:    scratch_store_b32 off, v53, s33 offset:184
; DAGISEL64-NEXT:    scratch_store_b32 off, v54, s33 offset:188
; DAGISEL64-NEXT:    scratch_store_b32 off, v55, s33 offset:192
; DAGISEL64-NEXT:    scratch_store_b32 off, v64, s33 offset:196
; DAGISEL64-NEXT:    scratch_store_b32 off, v65, s33 offset:200
; DAGISEL64-NEXT:    scratch_store_b32 off, v66, s33 offset:204
; DAGISEL64-NEXT:    scratch_store_b32 off, v67, s33 offset:208
; DAGISEL64-NEXT:    scratch_store_b32 off, v68, s33 offset:212
; DAGISEL64-NEXT:    scratch_store_b32 off, v69, s33 offset:216
; DAGISEL64-NEXT:    scratch_store_b32 off, v70, s33 offset:220
; DAGISEL64-NEXT:    scratch_store_b32 off, v71, s33 offset:224
; DAGISEL64-NEXT:    scratch_store_b32 off, v80, s33 offset:228
; DAGISEL64-NEXT:    scratch_store_b32 off, v81, s33 offset:232
; DAGISEL64-NEXT:    scratch_store_b32 off, v82, s33 offset:236
; DAGISEL64-NEXT:    scratch_store_b32 off, v83, s33 offset:240
; DAGISEL64-NEXT:    scratch_store_b32 off, v84, s33 offset:244
; DAGISEL64-NEXT:    scratch_store_b32 off, v85, s33 offset:248
; DAGISEL64-NEXT:    scratch_store_b32 off, v86, s33 offset:252
; DAGISEL64-NEXT:    scratch_store_b32 off, v87, s33 offset:256
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v96, s33 offset:260
; DAGISEL64-NEXT:    scratch_store_b32 off, v97, s33 offset:264
; DAGISEL64-NEXT:    scratch_store_b32 off, v98, s33 offset:268
; DAGISEL64-NEXT:    scratch_store_b32 off, v99, s33 offset:272
; DAGISEL64-NEXT:    scratch_store_b32 off, v100, s33 offset:276
; DAGISEL64-NEXT:    scratch_store_b32 off, v101, s33 offset:280
; DAGISEL64-NEXT:    scratch_store_b32 off, v102, s33 offset:284
; DAGISEL64-NEXT:    scratch_store_b32 off, v103, s33 offset:288
; DAGISEL64-NEXT:    scratch_store_b32 off, v112, s33 offset:292
; DAGISEL64-NEXT:    scratch_store_b32 off, v113, s33 offset:296
; DAGISEL64-NEXT:    scratch_store_b32 off, v114, s33 offset:300
; DAGISEL64-NEXT:    scratch_store_b32 off, v115, s33 offset:304
; DAGISEL64-NEXT:    scratch_store_b32 off, v116, s33 offset:308
; DAGISEL64-NEXT:    scratch_store_b32 off, v117, s33 offset:312
; DAGISEL64-NEXT:    scratch_store_b32 off, v118, s33 offset:316
; DAGISEL64-NEXT:    scratch_store_b32 off, v119, s33 offset:320
; DAGISEL64-NEXT:    scratch_store_b32 off, v128, s33 offset:324
; DAGISEL64-NEXT:    scratch_store_b32 off, v129, s33 offset:328
; DAGISEL64-NEXT:    scratch_store_b32 off, v130, s33 offset:332
; DAGISEL64-NEXT:    scratch_store_b32 off, v131, s33 offset:336
; DAGISEL64-NEXT:    scratch_store_b32 off, v132, s33 offset:340
; DAGISEL64-NEXT:    scratch_store_b32 off, v133, s33 offset:344
; DAGISEL64-NEXT:    scratch_store_b32 off, v134, s33 offset:348
; DAGISEL64-NEXT:    scratch_store_b32 off, v135, s33 offset:352
; DAGISEL64-NEXT:    scratch_store_b32 off, v144, s33 offset:356
; DAGISEL64-NEXT:    scratch_store_b32 off, v145, s33 offset:360
; DAGISEL64-NEXT:    scratch_store_b32 off, v146, s33 offset:364
; DAGISEL64-NEXT:    scratch_store_b32 off, v147, s33 offset:368
; DAGISEL64-NEXT:    scratch_store_b32 off, v148, s33 offset:372
; DAGISEL64-NEXT:    scratch_store_b32 off, v149, s33 offset:376
; DAGISEL64-NEXT:    scratch_store_b32 off, v150, s33 offset:380
; DAGISEL64-NEXT:    scratch_store_b32 off, v151, s33 offset:384
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v160, s33 offset:388
; DAGISEL64-NEXT:    scratch_store_b32 off, v161, s33 offset:392
; DAGISEL64-NEXT:    scratch_store_b32 off, v162, s33 offset:396
; DAGISEL64-NEXT:    scratch_store_b32 off, v163, s33 offset:400
; DAGISEL64-NEXT:    scratch_store_b32 off, v164, s33 offset:404
; DAGISEL64-NEXT:    scratch_store_b32 off, v165, s33 offset:408
; DAGISEL64-NEXT:    scratch_store_b32 off, v166, s33 offset:412
; DAGISEL64-NEXT:    scratch_store_b32 off, v167, s33 offset:416
; DAGISEL64-NEXT:    scratch_store_b32 off, v176, s33 offset:420
; DAGISEL64-NEXT:    scratch_store_b32 off, v177, s33 offset:424
; DAGISEL64-NEXT:    scratch_store_b32 off, v178, s33 offset:428
; DAGISEL64-NEXT:    scratch_store_b32 off, v179, s33 offset:432
; DAGISEL64-NEXT:    scratch_store_b32 off, v180, s33 offset:436
; DAGISEL64-NEXT:    scratch_store_b32 off, v181, s33 offset:440
; DAGISEL64-NEXT:    scratch_store_b32 off, v182, s33 offset:444
; DAGISEL64-NEXT:    scratch_store_b32 off, v183, s33 offset:448
; DAGISEL64-NEXT:    scratch_store_b32 off, v192, s33 offset:452
; DAGISEL64-NEXT:    scratch_store_b32 off, v193, s33 offset:456
; DAGISEL64-NEXT:    scratch_store_b32 off, v194, s33 offset:460
; DAGISEL64-NEXT:    scratch_store_b32 off, v195, s33 offset:464
; DAGISEL64-NEXT:    scratch_store_b32 off, v196, s33 offset:468
; DAGISEL64-NEXT:    scratch_store_b32 off, v197, s33 offset:472
; DAGISEL64-NEXT:    scratch_store_b32 off, v198, s33 offset:476
; DAGISEL64-NEXT:    scratch_store_b32 off, v199, s33 offset:480
; DAGISEL64-NEXT:    scratch_store_b32 off, v208, s33 offset:484
; DAGISEL64-NEXT:    scratch_store_b32 off, v209, s33 offset:488
; DAGISEL64-NEXT:    scratch_store_b32 off, v210, s33 offset:492
; DAGISEL64-NEXT:    scratch_store_b32 off, v211, s33 offset:496
; DAGISEL64-NEXT:    scratch_store_b32 off, v212, s33 offset:500
; DAGISEL64-NEXT:    scratch_store_b32 off, v213, s33 offset:504
; DAGISEL64-NEXT:    scratch_store_b32 off, v214, s33 offset:508
; DAGISEL64-NEXT:    scratch_store_b32 off, v215, s33 offset:512
; DAGISEL64-NEXT:    s_clause 0xf ; 64-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v224, s33 offset:516
; DAGISEL64-NEXT:    scratch_store_b32 off, v225, s33 offset:520
; DAGISEL64-NEXT:    scratch_store_b32 off, v226, s33 offset:524
; DAGISEL64-NEXT:    scratch_store_b32 off, v227, s33 offset:528
; DAGISEL64-NEXT:    scratch_store_b32 off, v228, s33 offset:532
; DAGISEL64-NEXT:    scratch_store_b32 off, v229, s33 offset:536
; DAGISEL64-NEXT:    scratch_store_b32 off, v230, s33 offset:540
; DAGISEL64-NEXT:    scratch_store_b32 off, v231, s33 offset:544
; DAGISEL64-NEXT:    scratch_store_b32 off, v240, s33 offset:548
; DAGISEL64-NEXT:    scratch_store_b32 off, v241, s33 offset:552
; DAGISEL64-NEXT:    scratch_store_b32 off, v242, s33 offset:556
; DAGISEL64-NEXT:    scratch_store_b32 off, v243, s33 offset:560
; DAGISEL64-NEXT:    scratch_store_b32 off, v244, s33 offset:564
; DAGISEL64-NEXT:    scratch_store_b32 off, v245, s33 offset:568
; DAGISEL64-NEXT:    scratch_store_b32 off, v246, s33 offset:572
; DAGISEL64-NEXT:    scratch_store_b32 off, v247, s33 offset:576
; DAGISEL64-NEXT:    s_mov_b64 exec, -1
; DAGISEL64-NEXT:    scratch_store_b32 off, v40, s33 ; 4-byte Folded Spill
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    v_writelane_b32 v40, s0, 4
; DAGISEL64-NEXT:    v_mov_b32_e32 v2, v0
; DAGISEL64-NEXT:    v_swap_b32 v0, v1
; DAGISEL64-NEXT:    s_mov_b32 s1, gfx_callee@abs32@hi
; DAGISEL64-NEXT:    v_writelane_b32 v40, s4, 0
; DAGISEL64-NEXT:    s_mov_b32 s0, gfx_callee@abs32@lo
; DAGISEL64-NEXT:    s_addk_co_i32 s32, 0x250
; DAGISEL64-NEXT:    v_writelane_b32 v40, s5, 1
; DAGISEL64-NEXT:    v_writelane_b32 v40, s30, 2
; DAGISEL64-NEXT:    v_writelane_b32 v40, s31, 3
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    s_swappc_b64 s[30:31], s[0:1]
; DAGISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; DAGISEL64-NEXT:    v_readlane_b32 s30, v40, 2
; DAGISEL64-NEXT:    v_readlane_b32 s31, v40, 3
; DAGISEL64-NEXT:    v_readlane_b32 s5, v40, 1
; DAGISEL64-NEXT:    v_readlane_b32 s4, v40, 0
; DAGISEL64-NEXT:    v_readlane_b32 s0, v40, 4
; DAGISEL64-NEXT:    scratch_load_b32 v40, off, s33 ; 4-byte Folded Reload
; DAGISEL64-NEXT:    s_mov_b32 s32, s33
; DAGISEL64-NEXT:    s_xor_b64 exec, s[4:5], -1
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v0, off, s33 offset:4
; DAGISEL64-NEXT:    scratch_load_b32 v1, off, s33 offset:8
; DAGISEL64-NEXT:    scratch_load_b32 v2, off, s33 offset:12
; DAGISEL64-NEXT:    scratch_load_b32 v3, off, s33 offset:16
; DAGISEL64-NEXT:    scratch_load_b32 v4, off, s33 offset:20
; DAGISEL64-NEXT:    scratch_load_b32 v5, off, s33 offset:24
; DAGISEL64-NEXT:    scratch_load_b32 v6, off, s33 offset:28
; DAGISEL64-NEXT:    scratch_load_b32 v7, off, s33 offset:32
; DAGISEL64-NEXT:    scratch_load_b32 v8, off, s33 offset:36
; DAGISEL64-NEXT:    scratch_load_b32 v9, off, s33 offset:40
; DAGISEL64-NEXT:    scratch_load_b32 v10, off, s33 offset:44
; DAGISEL64-NEXT:    scratch_load_b32 v11, off, s33 offset:48
; DAGISEL64-NEXT:    scratch_load_b32 v12, off, s33 offset:52
; DAGISEL64-NEXT:    scratch_load_b32 v13, off, s33 offset:56
; DAGISEL64-NEXT:    scratch_load_b32 v14, off, s33 offset:60
; DAGISEL64-NEXT:    scratch_load_b32 v15, off, s33 offset:64
; DAGISEL64-NEXT:    scratch_load_b32 v16, off, s33 offset:68
; DAGISEL64-NEXT:    scratch_load_b32 v17, off, s33 offset:72
; DAGISEL64-NEXT:    scratch_load_b32 v18, off, s33 offset:76
; DAGISEL64-NEXT:    scratch_load_b32 v19, off, s33 offset:80
; DAGISEL64-NEXT:    scratch_load_b32 v20, off, s33 offset:84
; DAGISEL64-NEXT:    scratch_load_b32 v21, off, s33 offset:88
; DAGISEL64-NEXT:    scratch_load_b32 v22, off, s33 offset:92
; DAGISEL64-NEXT:    scratch_load_b32 v23, off, s33 offset:96
; DAGISEL64-NEXT:    scratch_load_b32 v24, off, s33 offset:100
; DAGISEL64-NEXT:    scratch_load_b32 v25, off, s33 offset:104
; DAGISEL64-NEXT:    scratch_load_b32 v26, off, s33 offset:108
; DAGISEL64-NEXT:    scratch_load_b32 v27, off, s33 offset:112
; DAGISEL64-NEXT:    scratch_load_b32 v28, off, s33 offset:116
; DAGISEL64-NEXT:    scratch_load_b32 v29, off, s33 offset:120
; DAGISEL64-NEXT:    scratch_load_b32 v30, off, s33 offset:124
; DAGISEL64-NEXT:    scratch_load_b32 v31, off, s33 offset:128
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v32, off, s33 offset:132
; DAGISEL64-NEXT:    scratch_load_b32 v33, off, s33 offset:136
; DAGISEL64-NEXT:    scratch_load_b32 v34, off, s33 offset:140
; DAGISEL64-NEXT:    scratch_load_b32 v35, off, s33 offset:144
; DAGISEL64-NEXT:    scratch_load_b32 v36, off, s33 offset:148
; DAGISEL64-NEXT:    scratch_load_b32 v37, off, s33 offset:152
; DAGISEL64-NEXT:    scratch_load_b32 v38, off, s33 offset:156
; DAGISEL64-NEXT:    scratch_load_b32 v39, off, s33 offset:160
; DAGISEL64-NEXT:    scratch_load_b32 v48, off, s33 offset:164
; DAGISEL64-NEXT:    scratch_load_b32 v49, off, s33 offset:168
; DAGISEL64-NEXT:    scratch_load_b32 v50, off, s33 offset:172
; DAGISEL64-NEXT:    scratch_load_b32 v51, off, s33 offset:176
; DAGISEL64-NEXT:    scratch_load_b32 v52, off, s33 offset:180
; DAGISEL64-NEXT:    scratch_load_b32 v53, off, s33 offset:184
; DAGISEL64-NEXT:    scratch_load_b32 v54, off, s33 offset:188
; DAGISEL64-NEXT:    scratch_load_b32 v55, off, s33 offset:192
; DAGISEL64-NEXT:    scratch_load_b32 v64, off, s33 offset:196
; DAGISEL64-NEXT:    scratch_load_b32 v65, off, s33 offset:200
; DAGISEL64-NEXT:    scratch_load_b32 v66, off, s33 offset:204
; DAGISEL64-NEXT:    scratch_load_b32 v67, off, s33 offset:208
; DAGISEL64-NEXT:    scratch_load_b32 v68, off, s33 offset:212
; DAGISEL64-NEXT:    scratch_load_b32 v69, off, s33 offset:216
; DAGISEL64-NEXT:    scratch_load_b32 v70, off, s33 offset:220
; DAGISEL64-NEXT:    scratch_load_b32 v71, off, s33 offset:224
; DAGISEL64-NEXT:    scratch_load_b32 v80, off, s33 offset:228
; DAGISEL64-NEXT:    scratch_load_b32 v81, off, s33 offset:232
; DAGISEL64-NEXT:    scratch_load_b32 v82, off, s33 offset:236
; DAGISEL64-NEXT:    scratch_load_b32 v83, off, s33 offset:240
; DAGISEL64-NEXT:    scratch_load_b32 v84, off, s33 offset:244
; DAGISEL64-NEXT:    scratch_load_b32 v85, off, s33 offset:248
; DAGISEL64-NEXT:    scratch_load_b32 v86, off, s33 offset:252
; DAGISEL64-NEXT:    scratch_load_b32 v87, off, s33 offset:256
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v96, off, s33 offset:260
; DAGISEL64-NEXT:    scratch_load_b32 v97, off, s33 offset:264
; DAGISEL64-NEXT:    scratch_load_b32 v98, off, s33 offset:268
; DAGISEL64-NEXT:    scratch_load_b32 v99, off, s33 offset:272
; DAGISEL64-NEXT:    scratch_load_b32 v100, off, s33 offset:276
; DAGISEL64-NEXT:    scratch_load_b32 v101, off, s33 offset:280
; DAGISEL64-NEXT:    scratch_load_b32 v102, off, s33 offset:284
; DAGISEL64-NEXT:    scratch_load_b32 v103, off, s33 offset:288
; DAGISEL64-NEXT:    scratch_load_b32 v112, off, s33 offset:292
; DAGISEL64-NEXT:    scratch_load_b32 v113, off, s33 offset:296
; DAGISEL64-NEXT:    scratch_load_b32 v114, off, s33 offset:300
; DAGISEL64-NEXT:    scratch_load_b32 v115, off, s33 offset:304
; DAGISEL64-NEXT:    scratch_load_b32 v116, off, s33 offset:308
; DAGISEL64-NEXT:    scratch_load_b32 v117, off, s33 offset:312
; DAGISEL64-NEXT:    scratch_load_b32 v118, off, s33 offset:316
; DAGISEL64-NEXT:    scratch_load_b32 v119, off, s33 offset:320
; DAGISEL64-NEXT:    scratch_load_b32 v128, off, s33 offset:324
; DAGISEL64-NEXT:    scratch_load_b32 v129, off, s33 offset:328
; DAGISEL64-NEXT:    scratch_load_b32 v130, off, s33 offset:332
; DAGISEL64-NEXT:    scratch_load_b32 v131, off, s33 offset:336
; DAGISEL64-NEXT:    scratch_load_b32 v132, off, s33 offset:340
; DAGISEL64-NEXT:    scratch_load_b32 v133, off, s33 offset:344
; DAGISEL64-NEXT:    scratch_load_b32 v134, off, s33 offset:348
; DAGISEL64-NEXT:    scratch_load_b32 v135, off, s33 offset:352
; DAGISEL64-NEXT:    scratch_load_b32 v144, off, s33 offset:356
; DAGISEL64-NEXT:    scratch_load_b32 v145, off, s33 offset:360
; DAGISEL64-NEXT:    scratch_load_b32 v146, off, s33 offset:364
; DAGISEL64-NEXT:    scratch_load_b32 v147, off, s33 offset:368
; DAGISEL64-NEXT:    scratch_load_b32 v148, off, s33 offset:372
; DAGISEL64-NEXT:    scratch_load_b32 v149, off, s33 offset:376
; DAGISEL64-NEXT:    scratch_load_b32 v150, off, s33 offset:380
; DAGISEL64-NEXT:    scratch_load_b32 v151, off, s33 offset:384
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v160, off, s33 offset:388
; DAGISEL64-NEXT:    scratch_load_b32 v161, off, s33 offset:392
; DAGISEL64-NEXT:    scratch_load_b32 v162, off, s33 offset:396
; DAGISEL64-NEXT:    scratch_load_b32 v163, off, s33 offset:400
; DAGISEL64-NEXT:    scratch_load_b32 v164, off, s33 offset:404
; DAGISEL64-NEXT:    scratch_load_b32 v165, off, s33 offset:408
; DAGISEL64-NEXT:    scratch_load_b32 v166, off, s33 offset:412
; DAGISEL64-NEXT:    scratch_load_b32 v167, off, s33 offset:416
; DAGISEL64-NEXT:    scratch_load_b32 v176, off, s33 offset:420
; DAGISEL64-NEXT:    scratch_load_b32 v177, off, s33 offset:424
; DAGISEL64-NEXT:    scratch_load_b32 v178, off, s33 offset:428
; DAGISEL64-NEXT:    scratch_load_b32 v179, off, s33 offset:432
; DAGISEL64-NEXT:    scratch_load_b32 v180, off, s33 offset:436
; DAGISEL64-NEXT:    scratch_load_b32 v181, off, s33 offset:440
; DAGISEL64-NEXT:    scratch_load_b32 v182, off, s33 offset:444
; DAGISEL64-NEXT:    scratch_load_b32 v183, off, s33 offset:448
; DAGISEL64-NEXT:    scratch_load_b32 v192, off, s33 offset:452
; DAGISEL64-NEXT:    scratch_load_b32 v193, off, s33 offset:456
; DAGISEL64-NEXT:    scratch_load_b32 v194, off, s33 offset:460
; DAGISEL64-NEXT:    scratch_load_b32 v195, off, s33 offset:464
; DAGISEL64-NEXT:    scratch_load_b32 v196, off, s33 offset:468
; DAGISEL64-NEXT:    scratch_load_b32 v197, off, s33 offset:472
; DAGISEL64-NEXT:    scratch_load_b32 v198, off, s33 offset:476
; DAGISEL64-NEXT:    scratch_load_b32 v199, off, s33 offset:480
; DAGISEL64-NEXT:    scratch_load_b32 v208, off, s33 offset:484
; DAGISEL64-NEXT:    scratch_load_b32 v209, off, s33 offset:488
; DAGISEL64-NEXT:    scratch_load_b32 v210, off, s33 offset:492
; DAGISEL64-NEXT:    scratch_load_b32 v211, off, s33 offset:496
; DAGISEL64-NEXT:    scratch_load_b32 v212, off, s33 offset:500
; DAGISEL64-NEXT:    scratch_load_b32 v213, off, s33 offset:504
; DAGISEL64-NEXT:    scratch_load_b32 v214, off, s33 offset:508
; DAGISEL64-NEXT:    scratch_load_b32 v215, off, s33 offset:512
; DAGISEL64-NEXT:    s_clause 0xf ; 64-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v224, off, s33 offset:516
; DAGISEL64-NEXT:    scratch_load_b32 v225, off, s33 offset:520
; DAGISEL64-NEXT:    scratch_load_b32 v226, off, s33 offset:524
; DAGISEL64-NEXT:    scratch_load_b32 v227, off, s33 offset:528
; DAGISEL64-NEXT:    scratch_load_b32 v228, off, s33 offset:532
; DAGISEL64-NEXT:    scratch_load_b32 v229, off, s33 offset:536
; DAGISEL64-NEXT:    scratch_load_b32 v230, off, s33 offset:540
; DAGISEL64-NEXT:    scratch_load_b32 v231, off, s33 offset:544
; DAGISEL64-NEXT:    scratch_load_b32 v240, off, s33 offset:548
; DAGISEL64-NEXT:    scratch_load_b32 v241, off, s33 offset:552
; DAGISEL64-NEXT:    scratch_load_b32 v242, off, s33 offset:556
; DAGISEL64-NEXT:    scratch_load_b32 v243, off, s33 offset:560
; DAGISEL64-NEXT:    scratch_load_b32 v244, off, s33 offset:564
; DAGISEL64-NEXT:    scratch_load_b32 v245, off, s33 offset:568
; DAGISEL64-NEXT:    scratch_load_b32 v246, off, s33 offset:572
; DAGISEL64-NEXT:    scratch_load_b32 v247, off, s33 offset:576
; DAGISEL64-NEXT:    s_mov_b64 exec, s[4:5]
; DAGISEL64-NEXT:    s_mov_b32 s33, s0
; DAGISEL64-NEXT:    s_wait_loadcnt 0x0
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL64-LABEL: call_gfx_from_whole_wave:
; GISEL64:       ; %bb.0:
; GISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL64-NEXT:    s_wait_expcnt 0x0
; GISEL64-NEXT:    s_wait_samplecnt 0x0
; GISEL64-NEXT:    s_wait_bvhcnt 0x0
; GISEL64-NEXT:    s_wait_kmcnt 0x0
; GISEL64-NEXT:    s_mov_b32 s0, s33
; GISEL64-NEXT:    s_mov_b32 s33, s32
; GISEL64-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v0, s33 offset:4
; GISEL64-NEXT:    scratch_store_b32 off, v1, s33 offset:8
; GISEL64-NEXT:    scratch_store_b32 off, v2, s33 offset:12
; GISEL64-NEXT:    scratch_store_b32 off, v3, s33 offset:16
; GISEL64-NEXT:    scratch_store_b32 off, v4, s33 offset:20
; GISEL64-NEXT:    scratch_store_b32 off, v5, s33 offset:24
; GISEL64-NEXT:    scratch_store_b32 off, v6, s33 offset:28
; GISEL64-NEXT:    scratch_store_b32 off, v7, s33 offset:32
; GISEL64-NEXT:    scratch_store_b32 off, v8, s33 offset:36
; GISEL64-NEXT:    scratch_store_b32 off, v9, s33 offset:40
; GISEL64-NEXT:    scratch_store_b32 off, v10, s33 offset:44
; GISEL64-NEXT:    scratch_store_b32 off, v11, s33 offset:48
; GISEL64-NEXT:    scratch_store_b32 off, v12, s33 offset:52
; GISEL64-NEXT:    scratch_store_b32 off, v13, s33 offset:56
; GISEL64-NEXT:    scratch_store_b32 off, v14, s33 offset:60
; GISEL64-NEXT:    scratch_store_b32 off, v15, s33 offset:64
; GISEL64-NEXT:    scratch_store_b32 off, v16, s33 offset:68
; GISEL64-NEXT:    scratch_store_b32 off, v17, s33 offset:72
; GISEL64-NEXT:    scratch_store_b32 off, v18, s33 offset:76
; GISEL64-NEXT:    scratch_store_b32 off, v19, s33 offset:80
; GISEL64-NEXT:    scratch_store_b32 off, v20, s33 offset:84
; GISEL64-NEXT:    scratch_store_b32 off, v21, s33 offset:88
; GISEL64-NEXT:    scratch_store_b32 off, v22, s33 offset:92
; GISEL64-NEXT:    scratch_store_b32 off, v23, s33 offset:96
; GISEL64-NEXT:    scratch_store_b32 off, v24, s33 offset:100
; GISEL64-NEXT:    scratch_store_b32 off, v25, s33 offset:104
; GISEL64-NEXT:    scratch_store_b32 off, v26, s33 offset:108
; GISEL64-NEXT:    scratch_store_b32 off, v27, s33 offset:112
; GISEL64-NEXT:    scratch_store_b32 off, v28, s33 offset:116
; GISEL64-NEXT:    scratch_store_b32 off, v29, s33 offset:120
; GISEL64-NEXT:    scratch_store_b32 off, v30, s33 offset:124
; GISEL64-NEXT:    scratch_store_b32 off, v31, s33 offset:128
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v32, s33 offset:132
; GISEL64-NEXT:    scratch_store_b32 off, v33, s33 offset:136
; GISEL64-NEXT:    scratch_store_b32 off, v34, s33 offset:140
; GISEL64-NEXT:    scratch_store_b32 off, v35, s33 offset:144
; GISEL64-NEXT:    scratch_store_b32 off, v36, s33 offset:148
; GISEL64-NEXT:    scratch_store_b32 off, v37, s33 offset:152
; GISEL64-NEXT:    scratch_store_b32 off, v38, s33 offset:156
; GISEL64-NEXT:    scratch_store_b32 off, v39, s33 offset:160
; GISEL64-NEXT:    scratch_store_b32 off, v48, s33 offset:164
; GISEL64-NEXT:    scratch_store_b32 off, v49, s33 offset:168
; GISEL64-NEXT:    scratch_store_b32 off, v50, s33 offset:172
; GISEL64-NEXT:    scratch_store_b32 off, v51, s33 offset:176
; GISEL64-NEXT:    scratch_store_b32 off, v52, s33 offset:180
; GISEL64-NEXT:    scratch_store_b32 off, v53, s33 offset:184
; GISEL64-NEXT:    scratch_store_b32 off, v54, s33 offset:188
; GISEL64-NEXT:    scratch_store_b32 off, v55, s33 offset:192
; GISEL64-NEXT:    scratch_store_b32 off, v64, s33 offset:196
; GISEL64-NEXT:    scratch_store_b32 off, v65, s33 offset:200
; GISEL64-NEXT:    scratch_store_b32 off, v66, s33 offset:204
; GISEL64-NEXT:    scratch_store_b32 off, v67, s33 offset:208
; GISEL64-NEXT:    scratch_store_b32 off, v68, s33 offset:212
; GISEL64-NEXT:    scratch_store_b32 off, v69, s33 offset:216
; GISEL64-NEXT:    scratch_store_b32 off, v70, s33 offset:220
; GISEL64-NEXT:    scratch_store_b32 off, v71, s33 offset:224
; GISEL64-NEXT:    scratch_store_b32 off, v80, s33 offset:228
; GISEL64-NEXT:    scratch_store_b32 off, v81, s33 offset:232
; GISEL64-NEXT:    scratch_store_b32 off, v82, s33 offset:236
; GISEL64-NEXT:    scratch_store_b32 off, v83, s33 offset:240
; GISEL64-NEXT:    scratch_store_b32 off, v84, s33 offset:244
; GISEL64-NEXT:    scratch_store_b32 off, v85, s33 offset:248
; GISEL64-NEXT:    scratch_store_b32 off, v86, s33 offset:252
; GISEL64-NEXT:    scratch_store_b32 off, v87, s33 offset:256
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v96, s33 offset:260
; GISEL64-NEXT:    scratch_store_b32 off, v97, s33 offset:264
; GISEL64-NEXT:    scratch_store_b32 off, v98, s33 offset:268
; GISEL64-NEXT:    scratch_store_b32 off, v99, s33 offset:272
; GISEL64-NEXT:    scratch_store_b32 off, v100, s33 offset:276
; GISEL64-NEXT:    scratch_store_b32 off, v101, s33 offset:280
; GISEL64-NEXT:    scratch_store_b32 off, v102, s33 offset:284
; GISEL64-NEXT:    scratch_store_b32 off, v103, s33 offset:288
; GISEL64-NEXT:    scratch_store_b32 off, v112, s33 offset:292
; GISEL64-NEXT:    scratch_store_b32 off, v113, s33 offset:296
; GISEL64-NEXT:    scratch_store_b32 off, v114, s33 offset:300
; GISEL64-NEXT:    scratch_store_b32 off, v115, s33 offset:304
; GISEL64-NEXT:    scratch_store_b32 off, v116, s33 offset:308
; GISEL64-NEXT:    scratch_store_b32 off, v117, s33 offset:312
; GISEL64-NEXT:    scratch_store_b32 off, v118, s33 offset:316
; GISEL64-NEXT:    scratch_store_b32 off, v119, s33 offset:320
; GISEL64-NEXT:    scratch_store_b32 off, v128, s33 offset:324
; GISEL64-NEXT:    scratch_store_b32 off, v129, s33 offset:328
; GISEL64-NEXT:    scratch_store_b32 off, v130, s33 offset:332
; GISEL64-NEXT:    scratch_store_b32 off, v131, s33 offset:336
; GISEL64-NEXT:    scratch_store_b32 off, v132, s33 offset:340
; GISEL64-NEXT:    scratch_store_b32 off, v133, s33 offset:344
; GISEL64-NEXT:    scratch_store_b32 off, v134, s33 offset:348
; GISEL64-NEXT:    scratch_store_b32 off, v135, s33 offset:352
; GISEL64-NEXT:    scratch_store_b32 off, v144, s33 offset:356
; GISEL64-NEXT:    scratch_store_b32 off, v145, s33 offset:360
; GISEL64-NEXT:    scratch_store_b32 off, v146, s33 offset:364
; GISEL64-NEXT:    scratch_store_b32 off, v147, s33 offset:368
; GISEL64-NEXT:    scratch_store_b32 off, v148, s33 offset:372
; GISEL64-NEXT:    scratch_store_b32 off, v149, s33 offset:376
; GISEL64-NEXT:    scratch_store_b32 off, v150, s33 offset:380
; GISEL64-NEXT:    scratch_store_b32 off, v151, s33 offset:384
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v160, s33 offset:388
; GISEL64-NEXT:    scratch_store_b32 off, v161, s33 offset:392
; GISEL64-NEXT:    scratch_store_b32 off, v162, s33 offset:396
; GISEL64-NEXT:    scratch_store_b32 off, v163, s33 offset:400
; GISEL64-NEXT:    scratch_store_b32 off, v164, s33 offset:404
; GISEL64-NEXT:    scratch_store_b32 off, v165, s33 offset:408
; GISEL64-NEXT:    scratch_store_b32 off, v166, s33 offset:412
; GISEL64-NEXT:    scratch_store_b32 off, v167, s33 offset:416
; GISEL64-NEXT:    scratch_store_b32 off, v176, s33 offset:420
; GISEL64-NEXT:    scratch_store_b32 off, v177, s33 offset:424
; GISEL64-NEXT:    scratch_store_b32 off, v178, s33 offset:428
; GISEL64-NEXT:    scratch_store_b32 off, v179, s33 offset:432
; GISEL64-NEXT:    scratch_store_b32 off, v180, s33 offset:436
; GISEL64-NEXT:    scratch_store_b32 off, v181, s33 offset:440
; GISEL64-NEXT:    scratch_store_b32 off, v182, s33 offset:444
; GISEL64-NEXT:    scratch_store_b32 off, v183, s33 offset:448
; GISEL64-NEXT:    scratch_store_b32 off, v192, s33 offset:452
; GISEL64-NEXT:    scratch_store_b32 off, v193, s33 offset:456
; GISEL64-NEXT:    scratch_store_b32 off, v194, s33 offset:460
; GISEL64-NEXT:    scratch_store_b32 off, v195, s33 offset:464
; GISEL64-NEXT:    scratch_store_b32 off, v196, s33 offset:468
; GISEL64-NEXT:    scratch_store_b32 off, v197, s33 offset:472
; GISEL64-NEXT:    scratch_store_b32 off, v198, s33 offset:476
; GISEL64-NEXT:    scratch_store_b32 off, v199, s33 offset:480
; GISEL64-NEXT:    scratch_store_b32 off, v208, s33 offset:484
; GISEL64-NEXT:    scratch_store_b32 off, v209, s33 offset:488
; GISEL64-NEXT:    scratch_store_b32 off, v210, s33 offset:492
; GISEL64-NEXT:    scratch_store_b32 off, v211, s33 offset:496
; GISEL64-NEXT:    scratch_store_b32 off, v212, s33 offset:500
; GISEL64-NEXT:    scratch_store_b32 off, v213, s33 offset:504
; GISEL64-NEXT:    scratch_store_b32 off, v214, s33 offset:508
; GISEL64-NEXT:    scratch_store_b32 off, v215, s33 offset:512
; GISEL64-NEXT:    s_clause 0xf ; 64-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v224, s33 offset:516
; GISEL64-NEXT:    scratch_store_b32 off, v225, s33 offset:520
; GISEL64-NEXT:    scratch_store_b32 off, v226, s33 offset:524
; GISEL64-NEXT:    scratch_store_b32 off, v227, s33 offset:528
; GISEL64-NEXT:    scratch_store_b32 off, v228, s33 offset:532
; GISEL64-NEXT:    scratch_store_b32 off, v229, s33 offset:536
; GISEL64-NEXT:    scratch_store_b32 off, v230, s33 offset:540
; GISEL64-NEXT:    scratch_store_b32 off, v231, s33 offset:544
; GISEL64-NEXT:    scratch_store_b32 off, v240, s33 offset:548
; GISEL64-NEXT:    scratch_store_b32 off, v241, s33 offset:552
; GISEL64-NEXT:    scratch_store_b32 off, v242, s33 offset:556
; GISEL64-NEXT:    scratch_store_b32 off, v243, s33 offset:560
; GISEL64-NEXT:    scratch_store_b32 off, v244, s33 offset:564
; GISEL64-NEXT:    scratch_store_b32 off, v245, s33 offset:568
; GISEL64-NEXT:    scratch_store_b32 off, v246, s33 offset:572
; GISEL64-NEXT:    scratch_store_b32 off, v247, s33 offset:576
; GISEL64-NEXT:    s_mov_b64 exec, -1
; GISEL64-NEXT:    scratch_store_b32 off, v40, s33 ; 4-byte Folded Spill
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    v_writelane_b32 v40, s0, 4
; GISEL64-NEXT:    v_mov_b32_e32 v2, v0
; GISEL64-NEXT:    v_swap_b32 v0, v1
; GISEL64-NEXT:    s_mov_b32 s0, gfx_callee@abs32@lo
; GISEL64-NEXT:    v_writelane_b32 v40, s4, 0
; GISEL64-NEXT:    s_mov_b32 s1, gfx_callee@abs32@hi
; GISEL64-NEXT:    s_addk_co_i32 s32, 0x250
; GISEL64-NEXT:    v_writelane_b32 v40, s5, 1
; GISEL64-NEXT:    v_writelane_b32 v40, s30, 2
; GISEL64-NEXT:    v_writelane_b32 v40, s31, 3
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    s_swappc_b64 s[30:31], s[0:1]
; GISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GISEL64-NEXT:    v_readlane_b32 s30, v40, 2
; GISEL64-NEXT:    v_readlane_b32 s31, v40, 3
; GISEL64-NEXT:    v_readlane_b32 s5, v40, 1
; GISEL64-NEXT:    v_readlane_b32 s4, v40, 0
; GISEL64-NEXT:    v_readlane_b32 s0, v40, 4
; GISEL64-NEXT:    scratch_load_b32 v40, off, s33 ; 4-byte Folded Reload
; GISEL64-NEXT:    s_mov_b32 s32, s33
; GISEL64-NEXT:    s_xor_b64 exec, s[4:5], -1
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v0, off, s33 offset:4
; GISEL64-NEXT:    scratch_load_b32 v1, off, s33 offset:8
; GISEL64-NEXT:    scratch_load_b32 v2, off, s33 offset:12
; GISEL64-NEXT:    scratch_load_b32 v3, off, s33 offset:16
; GISEL64-NEXT:    scratch_load_b32 v4, off, s33 offset:20
; GISEL64-NEXT:    scratch_load_b32 v5, off, s33 offset:24
; GISEL64-NEXT:    scratch_load_b32 v6, off, s33 offset:28
; GISEL64-NEXT:    scratch_load_b32 v7, off, s33 offset:32
; GISEL64-NEXT:    scratch_load_b32 v8, off, s33 offset:36
; GISEL64-NEXT:    scratch_load_b32 v9, off, s33 offset:40
; GISEL64-NEXT:    scratch_load_b32 v10, off, s33 offset:44
; GISEL64-NEXT:    scratch_load_b32 v11, off, s33 offset:48
; GISEL64-NEXT:    scratch_load_b32 v12, off, s33 offset:52
; GISEL64-NEXT:    scratch_load_b32 v13, off, s33 offset:56
; GISEL64-NEXT:    scratch_load_b32 v14, off, s33 offset:60
; GISEL64-NEXT:    scratch_load_b32 v15, off, s33 offset:64
; GISEL64-NEXT:    scratch_load_b32 v16, off, s33 offset:68
; GISEL64-NEXT:    scratch_load_b32 v17, off, s33 offset:72
; GISEL64-NEXT:    scratch_load_b32 v18, off, s33 offset:76
; GISEL64-NEXT:    scratch_load_b32 v19, off, s33 offset:80
; GISEL64-NEXT:    scratch_load_b32 v20, off, s33 offset:84
; GISEL64-NEXT:    scratch_load_b32 v21, off, s33 offset:88
; GISEL64-NEXT:    scratch_load_b32 v22, off, s33 offset:92
; GISEL64-NEXT:    scratch_load_b32 v23, off, s33 offset:96
; GISEL64-NEXT:    scratch_load_b32 v24, off, s33 offset:100
; GISEL64-NEXT:    scratch_load_b32 v25, off, s33 offset:104
; GISEL64-NEXT:    scratch_load_b32 v26, off, s33 offset:108
; GISEL64-NEXT:    scratch_load_b32 v27, off, s33 offset:112
; GISEL64-NEXT:    scratch_load_b32 v28, off, s33 offset:116
; GISEL64-NEXT:    scratch_load_b32 v29, off, s33 offset:120
; GISEL64-NEXT:    scratch_load_b32 v30, off, s33 offset:124
; GISEL64-NEXT:    scratch_load_b32 v31, off, s33 offset:128
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v32, off, s33 offset:132
; GISEL64-NEXT:    scratch_load_b32 v33, off, s33 offset:136
; GISEL64-NEXT:    scratch_load_b32 v34, off, s33 offset:140
; GISEL64-NEXT:    scratch_load_b32 v35, off, s33 offset:144
; GISEL64-NEXT:    scratch_load_b32 v36, off, s33 offset:148
; GISEL64-NEXT:    scratch_load_b32 v37, off, s33 offset:152
; GISEL64-NEXT:    scratch_load_b32 v38, off, s33 offset:156
; GISEL64-NEXT:    scratch_load_b32 v39, off, s33 offset:160
; GISEL64-NEXT:    scratch_load_b32 v48, off, s33 offset:164
; GISEL64-NEXT:    scratch_load_b32 v49, off, s33 offset:168
; GISEL64-NEXT:    scratch_load_b32 v50, off, s33 offset:172
; GISEL64-NEXT:    scratch_load_b32 v51, off, s33 offset:176
; GISEL64-NEXT:    scratch_load_b32 v52, off, s33 offset:180
; GISEL64-NEXT:    scratch_load_b32 v53, off, s33 offset:184
; GISEL64-NEXT:    scratch_load_b32 v54, off, s33 offset:188
; GISEL64-NEXT:    scratch_load_b32 v55, off, s33 offset:192
; GISEL64-NEXT:    scratch_load_b32 v64, off, s33 offset:196
; GISEL64-NEXT:    scratch_load_b32 v65, off, s33 offset:200
; GISEL64-NEXT:    scratch_load_b32 v66, off, s33 offset:204
; GISEL64-NEXT:    scratch_load_b32 v67, off, s33 offset:208
; GISEL64-NEXT:    scratch_load_b32 v68, off, s33 offset:212
; GISEL64-NEXT:    scratch_load_b32 v69, off, s33 offset:216
; GISEL64-NEXT:    scratch_load_b32 v70, off, s33 offset:220
; GISEL64-NEXT:    scratch_load_b32 v71, off, s33 offset:224
; GISEL64-NEXT:    scratch_load_b32 v80, off, s33 offset:228
; GISEL64-NEXT:    scratch_load_b32 v81, off, s33 offset:232
; GISEL64-NEXT:    scratch_load_b32 v82, off, s33 offset:236
; GISEL64-NEXT:    scratch_load_b32 v83, off, s33 offset:240
; GISEL64-NEXT:    scratch_load_b32 v84, off, s33 offset:244
; GISEL64-NEXT:    scratch_load_b32 v85, off, s33 offset:248
; GISEL64-NEXT:    scratch_load_b32 v86, off, s33 offset:252
; GISEL64-NEXT:    scratch_load_b32 v87, off, s33 offset:256
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v96, off, s33 offset:260
; GISEL64-NEXT:    scratch_load_b32 v97, off, s33 offset:264
; GISEL64-NEXT:    scratch_load_b32 v98, off, s33 offset:268
; GISEL64-NEXT:    scratch_load_b32 v99, off, s33 offset:272
; GISEL64-NEXT:    scratch_load_b32 v100, off, s33 offset:276
; GISEL64-NEXT:    scratch_load_b32 v101, off, s33 offset:280
; GISEL64-NEXT:    scratch_load_b32 v102, off, s33 offset:284
; GISEL64-NEXT:    scratch_load_b32 v103, off, s33 offset:288
; GISEL64-NEXT:    scratch_load_b32 v112, off, s33 offset:292
; GISEL64-NEXT:    scratch_load_b32 v113, off, s33 offset:296
; GISEL64-NEXT:    scratch_load_b32 v114, off, s33 offset:300
; GISEL64-NEXT:    scratch_load_b32 v115, off, s33 offset:304
; GISEL64-NEXT:    scratch_load_b32 v116, off, s33 offset:308
; GISEL64-NEXT:    scratch_load_b32 v117, off, s33 offset:312
; GISEL64-NEXT:    scratch_load_b32 v118, off, s33 offset:316
; GISEL64-NEXT:    scratch_load_b32 v119, off, s33 offset:320
; GISEL64-NEXT:    scratch_load_b32 v128, off, s33 offset:324
; GISEL64-NEXT:    scratch_load_b32 v129, off, s33 offset:328
; GISEL64-NEXT:    scratch_load_b32 v130, off, s33 offset:332
; GISEL64-NEXT:    scratch_load_b32 v131, off, s33 offset:336
; GISEL64-NEXT:    scratch_load_b32 v132, off, s33 offset:340
; GISEL64-NEXT:    scratch_load_b32 v133, off, s33 offset:344
; GISEL64-NEXT:    scratch_load_b32 v134, off, s33 offset:348
; GISEL64-NEXT:    scratch_load_b32 v135, off, s33 offset:352
; GISEL64-NEXT:    scratch_load_b32 v144, off, s33 offset:356
; GISEL64-NEXT:    scratch_load_b32 v145, off, s33 offset:360
; GISEL64-NEXT:    scratch_load_b32 v146, off, s33 offset:364
; GISEL64-NEXT:    scratch_load_b32 v147, off, s33 offset:368
; GISEL64-NEXT:    scratch_load_b32 v148, off, s33 offset:372
; GISEL64-NEXT:    scratch_load_b32 v149, off, s33 offset:376
; GISEL64-NEXT:    scratch_load_b32 v150, off, s33 offset:380
; GISEL64-NEXT:    scratch_load_b32 v151, off, s33 offset:384
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v160, off, s33 offset:388
; GISEL64-NEXT:    scratch_load_b32 v161, off, s33 offset:392
; GISEL64-NEXT:    scratch_load_b32 v162, off, s33 offset:396
; GISEL64-NEXT:    scratch_load_b32 v163, off, s33 offset:400
; GISEL64-NEXT:    scratch_load_b32 v164, off, s33 offset:404
; GISEL64-NEXT:    scratch_load_b32 v165, off, s33 offset:408
; GISEL64-NEXT:    scratch_load_b32 v166, off, s33 offset:412
; GISEL64-NEXT:    scratch_load_b32 v167, off, s33 offset:416
; GISEL64-NEXT:    scratch_load_b32 v176, off, s33 offset:420
; GISEL64-NEXT:    scratch_load_b32 v177, off, s33 offset:424
; GISEL64-NEXT:    scratch_load_b32 v178, off, s33 offset:428
; GISEL64-NEXT:    scratch_load_b32 v179, off, s33 offset:432
; GISEL64-NEXT:    scratch_load_b32 v180, off, s33 offset:436
; GISEL64-NEXT:    scratch_load_b32 v181, off, s33 offset:440
; GISEL64-NEXT:    scratch_load_b32 v182, off, s33 offset:444
; GISEL64-NEXT:    scratch_load_b32 v183, off, s33 offset:448
; GISEL64-NEXT:    scratch_load_b32 v192, off, s33 offset:452
; GISEL64-NEXT:    scratch_load_b32 v193, off, s33 offset:456
; GISEL64-NEXT:    scratch_load_b32 v194, off, s33 offset:460
; GISEL64-NEXT:    scratch_load_b32 v195, off, s33 offset:464
; GISEL64-NEXT:    scratch_load_b32 v196, off, s33 offset:468
; GISEL64-NEXT:    scratch_load_b32 v197, off, s33 offset:472
; GISEL64-NEXT:    scratch_load_b32 v198, off, s33 offset:476
; GISEL64-NEXT:    scratch_load_b32 v199, off, s33 offset:480
; GISEL64-NEXT:    scratch_load_b32 v208, off, s33 offset:484
; GISEL64-NEXT:    scratch_load_b32 v209, off, s33 offset:488
; GISEL64-NEXT:    scratch_load_b32 v210, off, s33 offset:492
; GISEL64-NEXT:    scratch_load_b32 v211, off, s33 offset:496
; GISEL64-NEXT:    scratch_load_b32 v212, off, s33 offset:500
; GISEL64-NEXT:    scratch_load_b32 v213, off, s33 offset:504
; GISEL64-NEXT:    scratch_load_b32 v214, off, s33 offset:508
; GISEL64-NEXT:    scratch_load_b32 v215, off, s33 offset:512
; GISEL64-NEXT:    s_clause 0xf ; 64-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v224, off, s33 offset:516
; GISEL64-NEXT:    scratch_load_b32 v225, off, s33 offset:520
; GISEL64-NEXT:    scratch_load_b32 v226, off, s33 offset:524
; GISEL64-NEXT:    scratch_load_b32 v227, off, s33 offset:528
; GISEL64-NEXT:    scratch_load_b32 v228, off, s33 offset:532
; GISEL64-NEXT:    scratch_load_b32 v229, off, s33 offset:536
; GISEL64-NEXT:    scratch_load_b32 v230, off, s33 offset:540
; GISEL64-NEXT:    scratch_load_b32 v231, off, s33 offset:544
; GISEL64-NEXT:    scratch_load_b32 v240, off, s33 offset:548
; GISEL64-NEXT:    scratch_load_b32 v241, off, s33 offset:552
; GISEL64-NEXT:    scratch_load_b32 v242, off, s33 offset:556
; GISEL64-NEXT:    scratch_load_b32 v243, off, s33 offset:560
; GISEL64-NEXT:    scratch_load_b32 v244, off, s33 offset:564
; GISEL64-NEXT:    scratch_load_b32 v245, off, s33 offset:568
; GISEL64-NEXT:    scratch_load_b32 v246, off, s33 offset:572
; GISEL64-NEXT:    scratch_load_b32 v247, off, s33 offset:576
; GISEL64-NEXT:    s_mov_b64 exec, s[4:5]
; GISEL64-NEXT:    s_mov_b32 s33, s0
; GISEL64-NEXT:    s_wait_loadcnt 0x0
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-DAGISEL-LABEL: call_gfx_from_whole_wave:
; GFX1250-DAGISEL:       ; %bb.0:
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-DAGISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s0, s33
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s33, s32
; GFX1250-DAGISEL-NEXT:    s_xor_saveexec_b32 s4, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0, s33 offset:4 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1, s33 offset:8 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v2, s33 offset:12 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v3, s33 offset:16 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v4, s33 offset:20 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v5, s33 offset:24 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v6, s33 offset:28 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v7, s33 offset:32 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v8, s33 offset:36 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v9, s33 offset:40 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v10, s33 offset:44 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v11, s33 offset:48 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v12, s33 offset:52 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v13, s33 offset:56 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v14, s33 offset:60 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v15, s33 offset:64 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v16, s33 offset:68 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v17, s33 offset:72 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v18, s33 offset:76 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v19, s33 offset:80 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v20, s33 offset:84 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v21, s33 offset:88 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v22, s33 offset:92 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v23, s33 offset:96 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v24, s33 offset:100 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v25, s33 offset:104 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v26, s33 offset:108 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v27, s33 offset:112 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v28, s33 offset:116 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v29, s33 offset:120 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v30, s33 offset:124 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v31, s33 offset:128 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v32, s33 offset:132 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v33, s33 offset:136 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v34, s33 offset:140 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v35, s33 offset:144 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v36, s33 offset:148 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v37, s33 offset:152 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v38, s33 offset:156 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v39, s33 offset:160 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v48, s33 offset:164 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v49, s33 offset:168 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v50, s33 offset:172 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v51, s33 offset:176 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v52, s33 offset:180 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v53, s33 offset:184 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v54, s33 offset:188 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v55, s33 offset:192 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v64, s33 offset:196 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v65, s33 offset:200 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v66, s33 offset:204 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v67, s33 offset:208 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v68, s33 offset:212 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v69, s33 offset:216 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v70, s33 offset:220 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v71, s33 offset:224 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v80, s33 offset:228 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v81, s33 offset:232 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v82, s33 offset:236 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v83, s33 offset:240 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v84, s33 offset:244 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v85, s33 offset:248 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v86, s33 offset:252 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v87, s33 offset:256 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v96, s33 offset:260 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v97, s33 offset:264 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v98, s33 offset:268 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v99, s33 offset:272 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v100, s33 offset:276 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v101, s33 offset:280 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v102, s33 offset:284 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v103, s33 offset:288 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v112, s33 offset:292 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v113, s33 offset:296 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v114, s33 offset:300 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v115, s33 offset:304 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v116, s33 offset:308 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v117, s33 offset:312 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v118, s33 offset:316 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v119, s33 offset:320 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v128, s33 offset:324 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v129, s33 offset:328 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v130, s33 offset:332 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v131, s33 offset:336 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v132, s33 offset:340 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v133, s33 offset:344 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v134, s33 offset:348 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v135, s33 offset:352 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v144, s33 offset:356 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v145, s33 offset:360 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v146, s33 offset:364 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v147, s33 offset:368 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v148, s33 offset:372 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v149, s33 offset:376 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v150, s33 offset:380 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v151, s33 offset:384 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v160, s33 offset:388 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v161, s33 offset:392 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v162, s33 offset:396 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v163, s33 offset:400 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v164, s33 offset:404 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v165, s33 offset:408 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v166, s33 offset:412 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v167, s33 offset:416 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v176, s33 offset:420 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v177, s33 offset:424 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v178, s33 offset:428 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v179, s33 offset:432 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v180, s33 offset:436 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v181, s33 offset:440 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v182, s33 offset:444 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v183, s33 offset:448 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v192, s33 offset:452 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v193, s33 offset:456 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v194, s33 offset:460 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v195, s33 offset:464 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v196, s33 offset:468 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v197, s33 offset:472 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v198, s33 offset:476 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v199, s33 offset:480 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v208, s33 offset:484 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v209, s33 offset:488 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v210, s33 offset:492 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v211, s33 offset:496 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v212, s33 offset:500 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v213, s33 offset:504 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v214, s33 offset:508 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v215, s33 offset:512 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v224, s33 offset:516 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v225, s33 offset:520 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v226, s33 offset:524 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v227, s33 offset:528 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v228, s33 offset:532 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v229, s33 offset:536 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v230, s33 offset:540 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v231, s33 offset:544 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v240, s33 offset:548 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v241, s33 offset:552 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v242, s33 offset:556 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v243, s33 offset:560 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v244, s33 offset:564 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v245, s33 offset:568 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v246, s33 offset:572 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v247, s33 offset:576 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 4 ; msbs: dst=0 src0=0 src1=1 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0 /*v256*/, s33 offset:580 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1 /*v257*/, s33 offset:584 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v2 /*v258*/, s33 offset:588 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v3 /*v259*/, s33 offset:592 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v4 /*v260*/, s33 offset:596 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v5 /*v261*/, s33 offset:600 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v6 /*v262*/, s33 offset:604 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v7 /*v263*/, s33 offset:608 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v8 /*v264*/, s33 offset:612 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v9 /*v265*/, s33 offset:616 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v10 /*v266*/, s33 offset:620 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v11 /*v267*/, s33 offset:624 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v12 /*v268*/, s33 offset:628 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v13 /*v269*/, s33 offset:632 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v14 /*v270*/, s33 offset:636 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v15 /*v271*/, s33 offset:640 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v16 /*v272*/, s33 offset:644 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v17 /*v273*/, s33 offset:648 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v18 /*v274*/, s33 offset:652 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v19 /*v275*/, s33 offset:656 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v20 /*v276*/, s33 offset:660 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v21 /*v277*/, s33 offset:664 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v22 /*v278*/, s33 offset:668 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v23 /*v279*/, s33 offset:672 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v24 /*v280*/, s33 offset:676 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v25 /*v281*/, s33 offset:680 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v26 /*v282*/, s33 offset:684 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v27 /*v283*/, s33 offset:688 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v28 /*v284*/, s33 offset:692 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v29 /*v285*/, s33 offset:696 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v30 /*v286*/, s33 offset:700 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v31 /*v287*/, s33 offset:704 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v32 /*v288*/, s33 offset:708 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v33 /*v289*/, s33 offset:712 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v34 /*v290*/, s33 offset:716 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v35 /*v291*/, s33 offset:720 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v36 /*v292*/, s33 offset:724 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v37 /*v293*/, s33 offset:728 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v38 /*v294*/, s33 offset:732 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v39 /*v295*/, s33 offset:736 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v40 /*v296*/, s33 offset:740 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v41 /*v297*/, s33 offset:744 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v42 /*v298*/, s33 offset:748 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v43 /*v299*/, s33 offset:752 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v44 /*v300*/, s33 offset:756 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v45 /*v301*/, s33 offset:760 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v46 /*v302*/, s33 offset:764 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v47 /*v303*/, s33 offset:768 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v48 /*v304*/, s33 offset:772 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v49 /*v305*/, s33 offset:776 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v50 /*v306*/, s33 offset:780 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v51 /*v307*/, s33 offset:784 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v52 /*v308*/, s33 offset:788 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v53 /*v309*/, s33 offset:792 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v54 /*v310*/, s33 offset:796 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v55 /*v311*/, s33 offset:800 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v56 /*v312*/, s33 offset:804 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v57 /*v313*/, s33 offset:808 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v58 /*v314*/, s33 offset:812 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v59 /*v315*/, s33 offset:816 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v60 /*v316*/, s33 offset:820 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v61 /*v317*/, s33 offset:824 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v62 /*v318*/, s33 offset:828 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v63 /*v319*/, s33 offset:832 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v64 /*v320*/, s33 offset:836 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v65 /*v321*/, s33 offset:840 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v66 /*v322*/, s33 offset:844 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v67 /*v323*/, s33 offset:848 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v68 /*v324*/, s33 offset:852 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v69 /*v325*/, s33 offset:856 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v70 /*v326*/, s33 offset:860 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v71 /*v327*/, s33 offset:864 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v72 /*v328*/, s33 offset:868 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v73 /*v329*/, s33 offset:872 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v74 /*v330*/, s33 offset:876 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v75 /*v331*/, s33 offset:880 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v76 /*v332*/, s33 offset:884 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v77 /*v333*/, s33 offset:888 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v78 /*v334*/, s33 offset:892 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v79 /*v335*/, s33 offset:896 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v80 /*v336*/, s33 offset:900 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v81 /*v337*/, s33 offset:904 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v82 /*v338*/, s33 offset:908 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v83 /*v339*/, s33 offset:912 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v84 /*v340*/, s33 offset:916 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v85 /*v341*/, s33 offset:920 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v86 /*v342*/, s33 offset:924 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v87 /*v343*/, s33 offset:928 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v88 /*v344*/, s33 offset:932 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v89 /*v345*/, s33 offset:936 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v90 /*v346*/, s33 offset:940 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v91 /*v347*/, s33 offset:944 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v92 /*v348*/, s33 offset:948 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v93 /*v349*/, s33 offset:952 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v94 /*v350*/, s33 offset:956 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v95 /*v351*/, s33 offset:960 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v96 /*v352*/, s33 offset:964 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v97 /*v353*/, s33 offset:968 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v98 /*v354*/, s33 offset:972 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v99 /*v355*/, s33 offset:976 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v100 /*v356*/, s33 offset:980 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v101 /*v357*/, s33 offset:984 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v102 /*v358*/, s33 offset:988 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v103 /*v359*/, s33 offset:992 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v104 /*v360*/, s33 offset:996 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v105 /*v361*/, s33 offset:1000 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v106 /*v362*/, s33 offset:1004 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v107 /*v363*/, s33 offset:1008 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v108 /*v364*/, s33 offset:1012 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v109 /*v365*/, s33 offset:1016 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v110 /*v366*/, s33 offset:1020 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v111 /*v367*/, s33 offset:1024 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v112 /*v368*/, s33 offset:1028 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v113 /*v369*/, s33 offset:1032 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v114 /*v370*/, s33 offset:1036 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v115 /*v371*/, s33 offset:1040 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v116 /*v372*/, s33 offset:1044 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v117 /*v373*/, s33 offset:1048 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v118 /*v374*/, s33 offset:1052 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v119 /*v375*/, s33 offset:1056 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v120 /*v376*/, s33 offset:1060 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v121 /*v377*/, s33 offset:1064 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v122 /*v378*/, s33 offset:1068 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v123 /*v379*/, s33 offset:1072 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v124 /*v380*/, s33 offset:1076 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v125 /*v381*/, s33 offset:1080 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v126 /*v382*/, s33 offset:1084 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v127 /*v383*/, s33 offset:1088 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v128 /*v384*/, s33 offset:1092 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v129 /*v385*/, s33 offset:1096 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v130 /*v386*/, s33 offset:1100 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v131 /*v387*/, s33 offset:1104 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v132 /*v388*/, s33 offset:1108 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v133 /*v389*/, s33 offset:1112 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v134 /*v390*/, s33 offset:1116 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v135 /*v391*/, s33 offset:1120 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v136 /*v392*/, s33 offset:1124 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v137 /*v393*/, s33 offset:1128 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v138 /*v394*/, s33 offset:1132 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v139 /*v395*/, s33 offset:1136 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v140 /*v396*/, s33 offset:1140 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v141 /*v397*/, s33 offset:1144 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v142 /*v398*/, s33 offset:1148 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v143 /*v399*/, s33 offset:1152 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v144 /*v400*/, s33 offset:1156 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v145 /*v401*/, s33 offset:1160 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v146 /*v402*/, s33 offset:1164 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v147 /*v403*/, s33 offset:1168 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v148 /*v404*/, s33 offset:1172 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v149 /*v405*/, s33 offset:1176 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v150 /*v406*/, s33 offset:1180 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v151 /*v407*/, s33 offset:1184 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v152 /*v408*/, s33 offset:1188 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v153 /*v409*/, s33 offset:1192 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v154 /*v410*/, s33 offset:1196 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v155 /*v411*/, s33 offset:1200 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v156 /*v412*/, s33 offset:1204 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v157 /*v413*/, s33 offset:1208 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v158 /*v414*/, s33 offset:1212 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v159 /*v415*/, s33 offset:1216 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v160 /*v416*/, s33 offset:1220 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v161 /*v417*/, s33 offset:1224 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v162 /*v418*/, s33 offset:1228 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v163 /*v419*/, s33 offset:1232 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v164 /*v420*/, s33 offset:1236 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v165 /*v421*/, s33 offset:1240 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v166 /*v422*/, s33 offset:1244 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v167 /*v423*/, s33 offset:1248 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v168 /*v424*/, s33 offset:1252 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v169 /*v425*/, s33 offset:1256 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v170 /*v426*/, s33 offset:1260 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v171 /*v427*/, s33 offset:1264 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v172 /*v428*/, s33 offset:1268 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v173 /*v429*/, s33 offset:1272 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v174 /*v430*/, s33 offset:1276 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v175 /*v431*/, s33 offset:1280 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v176 /*v432*/, s33 offset:1284 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v177 /*v433*/, s33 offset:1288 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v178 /*v434*/, s33 offset:1292 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v179 /*v435*/, s33 offset:1296 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v180 /*v436*/, s33 offset:1300 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v181 /*v437*/, s33 offset:1304 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v182 /*v438*/, s33 offset:1308 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v183 /*v439*/, s33 offset:1312 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v184 /*v440*/, s33 offset:1316 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v185 /*v441*/, s33 offset:1320 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v186 /*v442*/, s33 offset:1324 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v187 /*v443*/, s33 offset:1328 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v188 /*v444*/, s33 offset:1332 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v189 /*v445*/, s33 offset:1336 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v190 /*v446*/, s33 offset:1340 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v191 /*v447*/, s33 offset:1344 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v192 /*v448*/, s33 offset:1348 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v193 /*v449*/, s33 offset:1352 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v194 /*v450*/, s33 offset:1356 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v195 /*v451*/, s33 offset:1360 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v196 /*v452*/, s33 offset:1364 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v197 /*v453*/, s33 offset:1368 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v198 /*v454*/, s33 offset:1372 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v199 /*v455*/, s33 offset:1376 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v200 /*v456*/, s33 offset:1380 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v201 /*v457*/, s33 offset:1384 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v202 /*v458*/, s33 offset:1388 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v203 /*v459*/, s33 offset:1392 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v204 /*v460*/, s33 offset:1396 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v205 /*v461*/, s33 offset:1400 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v206 /*v462*/, s33 offset:1404 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v207 /*v463*/, s33 offset:1408 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v208 /*v464*/, s33 offset:1412 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v209 /*v465*/, s33 offset:1416 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v210 /*v466*/, s33 offset:1420 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v211 /*v467*/, s33 offset:1424 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v212 /*v468*/, s33 offset:1428 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v213 /*v469*/, s33 offset:1432 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v214 /*v470*/, s33 offset:1436 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v215 /*v471*/, s33 offset:1440 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v216 /*v472*/, s33 offset:1444 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v217 /*v473*/, s33 offset:1448 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v218 /*v474*/, s33 offset:1452 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v219 /*v475*/, s33 offset:1456 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v220 /*v476*/, s33 offset:1460 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v221 /*v477*/, s33 offset:1464 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v222 /*v478*/, s33 offset:1468 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v223 /*v479*/, s33 offset:1472 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v224 /*v480*/, s33 offset:1476 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v225 /*v481*/, s33 offset:1480 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v226 /*v482*/, s33 offset:1484 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v227 /*v483*/, s33 offset:1488 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v228 /*v484*/, s33 offset:1492 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v229 /*v485*/, s33 offset:1496 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v230 /*v486*/, s33 offset:1500 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v231 /*v487*/, s33 offset:1504 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v232 /*v488*/, s33 offset:1508 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v233 /*v489*/, s33 offset:1512 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v234 /*v490*/, s33 offset:1516 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v235 /*v491*/, s33 offset:1520 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v236 /*v492*/, s33 offset:1524 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v237 /*v493*/, s33 offset:1528 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v238 /*v494*/, s33 offset:1532 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v239 /*v495*/, s33 offset:1536 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v240 /*v496*/, s33 offset:1540 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v241 /*v497*/, s33 offset:1544 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v242 /*v498*/, s33 offset:1548 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v243 /*v499*/, s33 offset:1552 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v244 /*v500*/, s33 offset:1556 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v245 /*v501*/, s33 offset:1560 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v246 /*v502*/, s33 offset:1564 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v247 /*v503*/, s33 offset:1568 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v248 /*v504*/, s33 offset:1572 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v249 /*v505*/, s33 offset:1576 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v250 /*v506*/, s33 offset:1580 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v251 /*v507*/, s33 offset:1584 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v252 /*v508*/, s33 offset:1588 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v253 /*v509*/, s33 offset:1592 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v254 /*v510*/, s33 offset:1596 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v255 /*v511*/, s33 offset:1600 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0x408 ; msbs: dst=0 src0=0 src1=2 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0 /*v512*/, s33 offset:1604 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1 /*v513*/, s33 offset:1608 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v2 /*v514*/, s33 offset:1612 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v3 /*v515*/, s33 offset:1616 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v4 /*v516*/, s33 offset:1620 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v5 /*v517*/, s33 offset:1624 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v6 /*v518*/, s33 offset:1628 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v7 /*v519*/, s33 offset:1632 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v8 /*v520*/, s33 offset:1636 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v9 /*v521*/, s33 offset:1640 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v10 /*v522*/, s33 offset:1644 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v11 /*v523*/, s33 offset:1648 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v12 /*v524*/, s33 offset:1652 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v13 /*v525*/, s33 offset:1656 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v14 /*v526*/, s33 offset:1660 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v15 /*v527*/, s33 offset:1664 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v16 /*v528*/, s33 offset:1668 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v17 /*v529*/, s33 offset:1672 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v18 /*v530*/, s33 offset:1676 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v19 /*v531*/, s33 offset:1680 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v20 /*v532*/, s33 offset:1684 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v21 /*v533*/, s33 offset:1688 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v22 /*v534*/, s33 offset:1692 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v23 /*v535*/, s33 offset:1696 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v24 /*v536*/, s33 offset:1700 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v25 /*v537*/, s33 offset:1704 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v26 /*v538*/, s33 offset:1708 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v27 /*v539*/, s33 offset:1712 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v28 /*v540*/, s33 offset:1716 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v29 /*v541*/, s33 offset:1720 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v30 /*v542*/, s33 offset:1724 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v31 /*v543*/, s33 offset:1728 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v32 /*v544*/, s33 offset:1732 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v33 /*v545*/, s33 offset:1736 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v34 /*v546*/, s33 offset:1740 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v35 /*v547*/, s33 offset:1744 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v36 /*v548*/, s33 offset:1748 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v37 /*v549*/, s33 offset:1752 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v38 /*v550*/, s33 offset:1756 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v39 /*v551*/, s33 offset:1760 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v40 /*v552*/, s33 offset:1764 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v41 /*v553*/, s33 offset:1768 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v42 /*v554*/, s33 offset:1772 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v43 /*v555*/, s33 offset:1776 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v44 /*v556*/, s33 offset:1780 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v45 /*v557*/, s33 offset:1784 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v46 /*v558*/, s33 offset:1788 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v47 /*v559*/, s33 offset:1792 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v48 /*v560*/, s33 offset:1796 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v49 /*v561*/, s33 offset:1800 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v50 /*v562*/, s33 offset:1804 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v51 /*v563*/, s33 offset:1808 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v52 /*v564*/, s33 offset:1812 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v53 /*v565*/, s33 offset:1816 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v54 /*v566*/, s33 offset:1820 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v55 /*v567*/, s33 offset:1824 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v56 /*v568*/, s33 offset:1828 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v57 /*v569*/, s33 offset:1832 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v58 /*v570*/, s33 offset:1836 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v59 /*v571*/, s33 offset:1840 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v60 /*v572*/, s33 offset:1844 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v61 /*v573*/, s33 offset:1848 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v62 /*v574*/, s33 offset:1852 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v63 /*v575*/, s33 offset:1856 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v64 /*v576*/, s33 offset:1860 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v65 /*v577*/, s33 offset:1864 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v66 /*v578*/, s33 offset:1868 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v67 /*v579*/, s33 offset:1872 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v68 /*v580*/, s33 offset:1876 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v69 /*v581*/, s33 offset:1880 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v70 /*v582*/, s33 offset:1884 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v71 /*v583*/, s33 offset:1888 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v72 /*v584*/, s33 offset:1892 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v73 /*v585*/, s33 offset:1896 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v74 /*v586*/, s33 offset:1900 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v75 /*v587*/, s33 offset:1904 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v76 /*v588*/, s33 offset:1908 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v77 /*v589*/, s33 offset:1912 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v78 /*v590*/, s33 offset:1916 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v79 /*v591*/, s33 offset:1920 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v80 /*v592*/, s33 offset:1924 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v81 /*v593*/, s33 offset:1928 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v82 /*v594*/, s33 offset:1932 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v83 /*v595*/, s33 offset:1936 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v84 /*v596*/, s33 offset:1940 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v85 /*v597*/, s33 offset:1944 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v86 /*v598*/, s33 offset:1948 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v87 /*v599*/, s33 offset:1952 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v88 /*v600*/, s33 offset:1956 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v89 /*v601*/, s33 offset:1960 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v90 /*v602*/, s33 offset:1964 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v91 /*v603*/, s33 offset:1968 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v92 /*v604*/, s33 offset:1972 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v93 /*v605*/, s33 offset:1976 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v94 /*v606*/, s33 offset:1980 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v95 /*v607*/, s33 offset:1984 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v96 /*v608*/, s33 offset:1988 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v97 /*v609*/, s33 offset:1992 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v98 /*v610*/, s33 offset:1996 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v99 /*v611*/, s33 offset:2000 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v100 /*v612*/, s33 offset:2004 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v101 /*v613*/, s33 offset:2008 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v102 /*v614*/, s33 offset:2012 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v103 /*v615*/, s33 offset:2016 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v104 /*v616*/, s33 offset:2020 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v105 /*v617*/, s33 offset:2024 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v106 /*v618*/, s33 offset:2028 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v107 /*v619*/, s33 offset:2032 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v108 /*v620*/, s33 offset:2036 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v109 /*v621*/, s33 offset:2040 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v110 /*v622*/, s33 offset:2044 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v111 /*v623*/, s33 offset:2048 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v112 /*v624*/, s33 offset:2052 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v113 /*v625*/, s33 offset:2056 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v114 /*v626*/, s33 offset:2060 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v115 /*v627*/, s33 offset:2064 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v116 /*v628*/, s33 offset:2068 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v117 /*v629*/, s33 offset:2072 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v118 /*v630*/, s33 offset:2076 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v119 /*v631*/, s33 offset:2080 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v120 /*v632*/, s33 offset:2084 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v121 /*v633*/, s33 offset:2088 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v122 /*v634*/, s33 offset:2092 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v123 /*v635*/, s33 offset:2096 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v124 /*v636*/, s33 offset:2100 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v125 /*v637*/, s33 offset:2104 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v126 /*v638*/, s33 offset:2108 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v127 /*v639*/, s33 offset:2112 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v128 /*v640*/, s33 offset:2116 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v129 /*v641*/, s33 offset:2120 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v130 /*v642*/, s33 offset:2124 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v131 /*v643*/, s33 offset:2128 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v132 /*v644*/, s33 offset:2132 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v133 /*v645*/, s33 offset:2136 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v134 /*v646*/, s33 offset:2140 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v135 /*v647*/, s33 offset:2144 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v136 /*v648*/, s33 offset:2148 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v137 /*v649*/, s33 offset:2152 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v138 /*v650*/, s33 offset:2156 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v139 /*v651*/, s33 offset:2160 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v140 /*v652*/, s33 offset:2164 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v141 /*v653*/, s33 offset:2168 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v142 /*v654*/, s33 offset:2172 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v143 /*v655*/, s33 offset:2176 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v144 /*v656*/, s33 offset:2180 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v145 /*v657*/, s33 offset:2184 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v146 /*v658*/, s33 offset:2188 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v147 /*v659*/, s33 offset:2192 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v148 /*v660*/, s33 offset:2196 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v149 /*v661*/, s33 offset:2200 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v150 /*v662*/, s33 offset:2204 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v151 /*v663*/, s33 offset:2208 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v152 /*v664*/, s33 offset:2212 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v153 /*v665*/, s33 offset:2216 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v154 /*v666*/, s33 offset:2220 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v155 /*v667*/, s33 offset:2224 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v156 /*v668*/, s33 offset:2228 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v157 /*v669*/, s33 offset:2232 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v158 /*v670*/, s33 offset:2236 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v159 /*v671*/, s33 offset:2240 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v160 /*v672*/, s33 offset:2244 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v161 /*v673*/, s33 offset:2248 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v162 /*v674*/, s33 offset:2252 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v163 /*v675*/, s33 offset:2256 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v164 /*v676*/, s33 offset:2260 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v165 /*v677*/, s33 offset:2264 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v166 /*v678*/, s33 offset:2268 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v167 /*v679*/, s33 offset:2272 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v168 /*v680*/, s33 offset:2276 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v169 /*v681*/, s33 offset:2280 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v170 /*v682*/, s33 offset:2284 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v171 /*v683*/, s33 offset:2288 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v172 /*v684*/, s33 offset:2292 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v173 /*v685*/, s33 offset:2296 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v174 /*v686*/, s33 offset:2300 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v175 /*v687*/, s33 offset:2304 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v176 /*v688*/, s33 offset:2308 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v177 /*v689*/, s33 offset:2312 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v178 /*v690*/, s33 offset:2316 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v179 /*v691*/, s33 offset:2320 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v180 /*v692*/, s33 offset:2324 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v181 /*v693*/, s33 offset:2328 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v182 /*v694*/, s33 offset:2332 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v183 /*v695*/, s33 offset:2336 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v184 /*v696*/, s33 offset:2340 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v185 /*v697*/, s33 offset:2344 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v186 /*v698*/, s33 offset:2348 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v187 /*v699*/, s33 offset:2352 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v188 /*v700*/, s33 offset:2356 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v189 /*v701*/, s33 offset:2360 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v190 /*v702*/, s33 offset:2364 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v191 /*v703*/, s33 offset:2368 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v192 /*v704*/, s33 offset:2372 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v193 /*v705*/, s33 offset:2376 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v194 /*v706*/, s33 offset:2380 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v195 /*v707*/, s33 offset:2384 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v196 /*v708*/, s33 offset:2388 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v197 /*v709*/, s33 offset:2392 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v198 /*v710*/, s33 offset:2396 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v199 /*v711*/, s33 offset:2400 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v200 /*v712*/, s33 offset:2404 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v201 /*v713*/, s33 offset:2408 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v202 /*v714*/, s33 offset:2412 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v203 /*v715*/, s33 offset:2416 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v204 /*v716*/, s33 offset:2420 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v205 /*v717*/, s33 offset:2424 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v206 /*v718*/, s33 offset:2428 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v207 /*v719*/, s33 offset:2432 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v208 /*v720*/, s33 offset:2436 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v209 /*v721*/, s33 offset:2440 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v210 /*v722*/, s33 offset:2444 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v211 /*v723*/, s33 offset:2448 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v212 /*v724*/, s33 offset:2452 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v213 /*v725*/, s33 offset:2456 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v214 /*v726*/, s33 offset:2460 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v215 /*v727*/, s33 offset:2464 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v216 /*v728*/, s33 offset:2468 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v217 /*v729*/, s33 offset:2472 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v218 /*v730*/, s33 offset:2476 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v219 /*v731*/, s33 offset:2480 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v220 /*v732*/, s33 offset:2484 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v221 /*v733*/, s33 offset:2488 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v222 /*v734*/, s33 offset:2492 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v223 /*v735*/, s33 offset:2496 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v224 /*v736*/, s33 offset:2500 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v225 /*v737*/, s33 offset:2504 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v226 /*v738*/, s33 offset:2508 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v227 /*v739*/, s33 offset:2512 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v228 /*v740*/, s33 offset:2516 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v229 /*v741*/, s33 offset:2520 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v230 /*v742*/, s33 offset:2524 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v231 /*v743*/, s33 offset:2528 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v232 /*v744*/, s33 offset:2532 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v233 /*v745*/, s33 offset:2536 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v234 /*v746*/, s33 offset:2540 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v235 /*v747*/, s33 offset:2544 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v236 /*v748*/, s33 offset:2548 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v237 /*v749*/, s33 offset:2552 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v238 /*v750*/, s33 offset:2556 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v239 /*v751*/, s33 offset:2560 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v240 /*v752*/, s33 offset:2564 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v241 /*v753*/, s33 offset:2568 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v242 /*v754*/, s33 offset:2572 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v243 /*v755*/, s33 offset:2576 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v244 /*v756*/, s33 offset:2580 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v245 /*v757*/, s33 offset:2584 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v246 /*v758*/, s33 offset:2588 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v247 /*v759*/, s33 offset:2592 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v248 /*v760*/, s33 offset:2596 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v249 /*v761*/, s33 offset:2600 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v250 /*v762*/, s33 offset:2604 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v251 /*v763*/, s33 offset:2608 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v252 /*v764*/, s33 offset:2612 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v253 /*v765*/, s33 offset:2616 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v254 /*v766*/, s33 offset:2620 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v255 /*v767*/, s33 offset:2624 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0x80c ; msbs: dst=0 src0=0 src1=3 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0 /*v768*/, s33 offset:2628 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1 /*v769*/, s33 offset:2632 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v2 /*v770*/, s33 offset:2636 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v3 /*v771*/, s33 offset:2640 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v4 /*v772*/, s33 offset:2644 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v5 /*v773*/, s33 offset:2648 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v6 /*v774*/, s33 offset:2652 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v7 /*v775*/, s33 offset:2656 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v8 /*v776*/, s33 offset:2660 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v9 /*v777*/, s33 offset:2664 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v10 /*v778*/, s33 offset:2668 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v11 /*v779*/, s33 offset:2672 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v12 /*v780*/, s33 offset:2676 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v13 /*v781*/, s33 offset:2680 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v14 /*v782*/, s33 offset:2684 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v15 /*v783*/, s33 offset:2688 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v16 /*v784*/, s33 offset:2692 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v17 /*v785*/, s33 offset:2696 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v18 /*v786*/, s33 offset:2700 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v19 /*v787*/, s33 offset:2704 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v20 /*v788*/, s33 offset:2708 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v21 /*v789*/, s33 offset:2712 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v22 /*v790*/, s33 offset:2716 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v23 /*v791*/, s33 offset:2720 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v24 /*v792*/, s33 offset:2724 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v25 /*v793*/, s33 offset:2728 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v26 /*v794*/, s33 offset:2732 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v27 /*v795*/, s33 offset:2736 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v28 /*v796*/, s33 offset:2740 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v29 /*v797*/, s33 offset:2744 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v30 /*v798*/, s33 offset:2748 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v31 /*v799*/, s33 offset:2752 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v32 /*v800*/, s33 offset:2756 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v33 /*v801*/, s33 offset:2760 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v34 /*v802*/, s33 offset:2764 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v35 /*v803*/, s33 offset:2768 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v36 /*v804*/, s33 offset:2772 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v37 /*v805*/, s33 offset:2776 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v38 /*v806*/, s33 offset:2780 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v39 /*v807*/, s33 offset:2784 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v40 /*v808*/, s33 offset:2788 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v41 /*v809*/, s33 offset:2792 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v42 /*v810*/, s33 offset:2796 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v43 /*v811*/, s33 offset:2800 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v44 /*v812*/, s33 offset:2804 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v45 /*v813*/, s33 offset:2808 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v46 /*v814*/, s33 offset:2812 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v47 /*v815*/, s33 offset:2816 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v48 /*v816*/, s33 offset:2820 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v49 /*v817*/, s33 offset:2824 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v50 /*v818*/, s33 offset:2828 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v51 /*v819*/, s33 offset:2832 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v52 /*v820*/, s33 offset:2836 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v53 /*v821*/, s33 offset:2840 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v54 /*v822*/, s33 offset:2844 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v55 /*v823*/, s33 offset:2848 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v56 /*v824*/, s33 offset:2852 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v57 /*v825*/, s33 offset:2856 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v58 /*v826*/, s33 offset:2860 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v59 /*v827*/, s33 offset:2864 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v60 /*v828*/, s33 offset:2868 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v61 /*v829*/, s33 offset:2872 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v62 /*v830*/, s33 offset:2876 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v63 /*v831*/, s33 offset:2880 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v64 /*v832*/, s33 offset:2884 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v65 /*v833*/, s33 offset:2888 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v66 /*v834*/, s33 offset:2892 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v67 /*v835*/, s33 offset:2896 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v68 /*v836*/, s33 offset:2900 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v69 /*v837*/, s33 offset:2904 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v70 /*v838*/, s33 offset:2908 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v71 /*v839*/, s33 offset:2912 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v72 /*v840*/, s33 offset:2916 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v73 /*v841*/, s33 offset:2920 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v74 /*v842*/, s33 offset:2924 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v75 /*v843*/, s33 offset:2928 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v76 /*v844*/, s33 offset:2932 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v77 /*v845*/, s33 offset:2936 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v78 /*v846*/, s33 offset:2940 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v79 /*v847*/, s33 offset:2944 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v80 /*v848*/, s33 offset:2948 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v81 /*v849*/, s33 offset:2952 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v82 /*v850*/, s33 offset:2956 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v83 /*v851*/, s33 offset:2960 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v84 /*v852*/, s33 offset:2964 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v85 /*v853*/, s33 offset:2968 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v86 /*v854*/, s33 offset:2972 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v87 /*v855*/, s33 offset:2976 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v88 /*v856*/, s33 offset:2980 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v89 /*v857*/, s33 offset:2984 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v90 /*v858*/, s33 offset:2988 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v91 /*v859*/, s33 offset:2992 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v92 /*v860*/, s33 offset:2996 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v93 /*v861*/, s33 offset:3000 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v94 /*v862*/, s33 offset:3004 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v95 /*v863*/, s33 offset:3008 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v96 /*v864*/, s33 offset:3012 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v97 /*v865*/, s33 offset:3016 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v98 /*v866*/, s33 offset:3020 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v99 /*v867*/, s33 offset:3024 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v100 /*v868*/, s33 offset:3028 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v101 /*v869*/, s33 offset:3032 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v102 /*v870*/, s33 offset:3036 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v103 /*v871*/, s33 offset:3040 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v104 /*v872*/, s33 offset:3044 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v105 /*v873*/, s33 offset:3048 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v106 /*v874*/, s33 offset:3052 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v107 /*v875*/, s33 offset:3056 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v108 /*v876*/, s33 offset:3060 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v109 /*v877*/, s33 offset:3064 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v110 /*v878*/, s33 offset:3068 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v111 /*v879*/, s33 offset:3072 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v112 /*v880*/, s33 offset:3076 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v113 /*v881*/, s33 offset:3080 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v114 /*v882*/, s33 offset:3084 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v115 /*v883*/, s33 offset:3088 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v116 /*v884*/, s33 offset:3092 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v117 /*v885*/, s33 offset:3096 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v118 /*v886*/, s33 offset:3100 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v119 /*v887*/, s33 offset:3104 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v120 /*v888*/, s33 offset:3108 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v121 /*v889*/, s33 offset:3112 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v122 /*v890*/, s33 offset:3116 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v123 /*v891*/, s33 offset:3120 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v124 /*v892*/, s33 offset:3124 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v125 /*v893*/, s33 offset:3128 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v126 /*v894*/, s33 offset:3132 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v127 /*v895*/, s33 offset:3136 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v128 /*v896*/, s33 offset:3140 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v129 /*v897*/, s33 offset:3144 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v130 /*v898*/, s33 offset:3148 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v131 /*v899*/, s33 offset:3152 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v132 /*v900*/, s33 offset:3156 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v133 /*v901*/, s33 offset:3160 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v134 /*v902*/, s33 offset:3164 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v135 /*v903*/, s33 offset:3168 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v136 /*v904*/, s33 offset:3172 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v137 /*v905*/, s33 offset:3176 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v138 /*v906*/, s33 offset:3180 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v139 /*v907*/, s33 offset:3184 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v140 /*v908*/, s33 offset:3188 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v141 /*v909*/, s33 offset:3192 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v142 /*v910*/, s33 offset:3196 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v143 /*v911*/, s33 offset:3200 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v144 /*v912*/, s33 offset:3204 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v145 /*v913*/, s33 offset:3208 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v146 /*v914*/, s33 offset:3212 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v147 /*v915*/, s33 offset:3216 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v148 /*v916*/, s33 offset:3220 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v149 /*v917*/, s33 offset:3224 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v150 /*v918*/, s33 offset:3228 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v151 /*v919*/, s33 offset:3232 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v152 /*v920*/, s33 offset:3236 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v153 /*v921*/, s33 offset:3240 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v154 /*v922*/, s33 offset:3244 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v155 /*v923*/, s33 offset:3248 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v156 /*v924*/, s33 offset:3252 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v157 /*v925*/, s33 offset:3256 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v158 /*v926*/, s33 offset:3260 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v159 /*v927*/, s33 offset:3264 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v160 /*v928*/, s33 offset:3268 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v161 /*v929*/, s33 offset:3272 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v162 /*v930*/, s33 offset:3276 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v163 /*v931*/, s33 offset:3280 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v164 /*v932*/, s33 offset:3284 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v165 /*v933*/, s33 offset:3288 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v166 /*v934*/, s33 offset:3292 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v167 /*v935*/, s33 offset:3296 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v168 /*v936*/, s33 offset:3300 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v169 /*v937*/, s33 offset:3304 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v170 /*v938*/, s33 offset:3308 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v171 /*v939*/, s33 offset:3312 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v172 /*v940*/, s33 offset:3316 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v173 /*v941*/, s33 offset:3320 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v174 /*v942*/, s33 offset:3324 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v175 /*v943*/, s33 offset:3328 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v176 /*v944*/, s33 offset:3332 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v177 /*v945*/, s33 offset:3336 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v178 /*v946*/, s33 offset:3340 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v179 /*v947*/, s33 offset:3344 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v180 /*v948*/, s33 offset:3348 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v181 /*v949*/, s33 offset:3352 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v182 /*v950*/, s33 offset:3356 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v183 /*v951*/, s33 offset:3360 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v184 /*v952*/, s33 offset:3364 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v185 /*v953*/, s33 offset:3368 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v186 /*v954*/, s33 offset:3372 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v187 /*v955*/, s33 offset:3376 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v188 /*v956*/, s33 offset:3380 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v189 /*v957*/, s33 offset:3384 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v190 /*v958*/, s33 offset:3388 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v191 /*v959*/, s33 offset:3392 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v192 /*v960*/, s33 offset:3396 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v193 /*v961*/, s33 offset:3400 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v194 /*v962*/, s33 offset:3404 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v195 /*v963*/, s33 offset:3408 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v196 /*v964*/, s33 offset:3412 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v197 /*v965*/, s33 offset:3416 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v198 /*v966*/, s33 offset:3420 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v199 /*v967*/, s33 offset:3424 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v200 /*v968*/, s33 offset:3428 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v201 /*v969*/, s33 offset:3432 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v202 /*v970*/, s33 offset:3436 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v203 /*v971*/, s33 offset:3440 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v204 /*v972*/, s33 offset:3444 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v205 /*v973*/, s33 offset:3448 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v206 /*v974*/, s33 offset:3452 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v207 /*v975*/, s33 offset:3456 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v208 /*v976*/, s33 offset:3460 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v209 /*v977*/, s33 offset:3464 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v210 /*v978*/, s33 offset:3468 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v211 /*v979*/, s33 offset:3472 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v212 /*v980*/, s33 offset:3476 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v213 /*v981*/, s33 offset:3480 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v214 /*v982*/, s33 offset:3484 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v215 /*v983*/, s33 offset:3488 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v216 /*v984*/, s33 offset:3492 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v217 /*v985*/, s33 offset:3496 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v218 /*v986*/, s33 offset:3500 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v219 /*v987*/, s33 offset:3504 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v220 /*v988*/, s33 offset:3508 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v221 /*v989*/, s33 offset:3512 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v222 /*v990*/, s33 offset:3516 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v223 /*v991*/, s33 offset:3520 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v224 /*v992*/, s33 offset:3524 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v225 /*v993*/, s33 offset:3528 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x1d ; 120-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v226 /*v994*/, s33 offset:3532 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v227 /*v995*/, s33 offset:3536 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v228 /*v996*/, s33 offset:3540 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v229 /*v997*/, s33 offset:3544 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v230 /*v998*/, s33 offset:3548 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v231 /*v999*/, s33 offset:3552 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v232 /*v1000*/, s33 offset:3556 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v233 /*v1001*/, s33 offset:3560 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v234 /*v1002*/, s33 offset:3564 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v235 /*v1003*/, s33 offset:3568 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v236 /*v1004*/, s33 offset:3572 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v237 /*v1005*/, s33 offset:3576 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v238 /*v1006*/, s33 offset:3580 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v239 /*v1007*/, s33 offset:3584 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v240 /*v1008*/, s33 offset:3588 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v241 /*v1009*/, s33 offset:3592 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v242 /*v1010*/, s33 offset:3596 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v243 /*v1011*/, s33 offset:3600 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v244 /*v1012*/, s33 offset:3604 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v245 /*v1013*/, s33 offset:3608 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v246 /*v1014*/, s33 offset:3612 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v247 /*v1015*/, s33 offset:3616 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v248 /*v1016*/, s33 offset:3620 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v249 /*v1017*/, s33 offset:3624 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v250 /*v1018*/, s33 offset:3628 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v251 /*v1019*/, s33 offset:3632 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v252 /*v1020*/, s33 offset:3636 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v253 /*v1021*/, s33 offset:3640 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v254 /*v1022*/, s33 offset:3644 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v255 /*v1023*/, s33 offset:3648 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0xc00 ; msbs: dst=0 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v40, s33 nv ; 4-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    v_writelane_b32 v40, s0, 3
; GFX1250-DAGISEL-NEXT:    v_mov_b32_e32 v2, v0
; GFX1250-DAGISEL-NEXT:    v_swap_b32 v0, v1
; GFX1250-DAGISEL-NEXT:    s_mov_b64 s[0:1], gfx_callee@abs64
; GFX1250-DAGISEL-NEXT:    v_writelane_b32 v40, s4, 0
; GFX1250-DAGISEL-NEXT:    s_addk_co_i32 s32, 0xe50
; GFX1250-DAGISEL-NEXT:    v_writelane_b32 v40, s30, 1
; GFX1250-DAGISEL-NEXT:    v_writelane_b32 v40, s31, 2
; GFX1250-DAGISEL-NEXT:    s_swap_pc_i64 s[30:31], s[0:1]
; GFX1250-DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1250-DAGISEL-NEXT:    v_readlane_b32 s30, v40, 1
; GFX1250-DAGISEL-NEXT:    v_readlane_b32 s31, v40, 2
; GFX1250-DAGISEL-NEXT:    v_readlane_b32 s4, v40, 0
; GFX1250-DAGISEL-NEXT:    v_readlane_b32 s0, v40, 3
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v40, off, s33 nv ; 4-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s32, s33
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_xor_b32 exec_lo, s4, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0, off, s33 offset:4 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1, off, s33 offset:8 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v2, off, s33 offset:12 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v3, off, s33 offset:16 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v4, off, s33 offset:20 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v5, off, s33 offset:24 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v6, off, s33 offset:28 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v7, off, s33 offset:32 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v8, off, s33 offset:36 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v9, off, s33 offset:40 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v10, off, s33 offset:44 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v11, off, s33 offset:48 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v12, off, s33 offset:52 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v13, off, s33 offset:56 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v14, off, s33 offset:60 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v15, off, s33 offset:64 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v16, off, s33 offset:68 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v17, off, s33 offset:72 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v18, off, s33 offset:76 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v19, off, s33 offset:80 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v20, off, s33 offset:84 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v21, off, s33 offset:88 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v22, off, s33 offset:92 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v23, off, s33 offset:96 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v24, off, s33 offset:100 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v25, off, s33 offset:104 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v26, off, s33 offset:108 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v27, off, s33 offset:112 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v28, off, s33 offset:116 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v29, off, s33 offset:120 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v30, off, s33 offset:124 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v31, off, s33 offset:128 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v32, off, s33 offset:132 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v33, off, s33 offset:136 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v34, off, s33 offset:140 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v35, off, s33 offset:144 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v36, off, s33 offset:148 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v37, off, s33 offset:152 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v38, off, s33 offset:156 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v39, off, s33 offset:160 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v48, off, s33 offset:164 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v49, off, s33 offset:168 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v50, off, s33 offset:172 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v51, off, s33 offset:176 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v52, off, s33 offset:180 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v53, off, s33 offset:184 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v54, off, s33 offset:188 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v55, off, s33 offset:192 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v64, off, s33 offset:196 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v65, off, s33 offset:200 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v66, off, s33 offset:204 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v67, off, s33 offset:208 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v68, off, s33 offset:212 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v69, off, s33 offset:216 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v70, off, s33 offset:220 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v71, off, s33 offset:224 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v80, off, s33 offset:228 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v81, off, s33 offset:232 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v82, off, s33 offset:236 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v83, off, s33 offset:240 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v84, off, s33 offset:244 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v85, off, s33 offset:248 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v86, off, s33 offset:252 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v87, off, s33 offset:256 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v96, off, s33 offset:260 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v97, off, s33 offset:264 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v98, off, s33 offset:268 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v99, off, s33 offset:272 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v100, off, s33 offset:276 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v101, off, s33 offset:280 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v102, off, s33 offset:284 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v103, off, s33 offset:288 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v112, off, s33 offset:292 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v113, off, s33 offset:296 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v114, off, s33 offset:300 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v115, off, s33 offset:304 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v116, off, s33 offset:308 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v117, off, s33 offset:312 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v118, off, s33 offset:316 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v119, off, s33 offset:320 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v128, off, s33 offset:324 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v129, off, s33 offset:328 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v130, off, s33 offset:332 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v131, off, s33 offset:336 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v132, off, s33 offset:340 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v133, off, s33 offset:344 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v134, off, s33 offset:348 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v135, off, s33 offset:352 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v144, off, s33 offset:356 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v145, off, s33 offset:360 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v146, off, s33 offset:364 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v147, off, s33 offset:368 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v148, off, s33 offset:372 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v149, off, s33 offset:376 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v150, off, s33 offset:380 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v151, off, s33 offset:384 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v160, off, s33 offset:388 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v161, off, s33 offset:392 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v162, off, s33 offset:396 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v163, off, s33 offset:400 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v164, off, s33 offset:404 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v165, off, s33 offset:408 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v166, off, s33 offset:412 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v167, off, s33 offset:416 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v176, off, s33 offset:420 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v177, off, s33 offset:424 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v178, off, s33 offset:428 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v179, off, s33 offset:432 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v180, off, s33 offset:436 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v181, off, s33 offset:440 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v182, off, s33 offset:444 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v183, off, s33 offset:448 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v192, off, s33 offset:452 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v193, off, s33 offset:456 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v194, off, s33 offset:460 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v195, off, s33 offset:464 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v196, off, s33 offset:468 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v197, off, s33 offset:472 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v198, off, s33 offset:476 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v199, off, s33 offset:480 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v208, off, s33 offset:484 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v209, off, s33 offset:488 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v210, off, s33 offset:492 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v211, off, s33 offset:496 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v212, off, s33 offset:500 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v213, off, s33 offset:504 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v214, off, s33 offset:508 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v215, off, s33 offset:512 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v224, off, s33 offset:516 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v225, off, s33 offset:520 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v226, off, s33 offset:524 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v227, off, s33 offset:528 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v228, off, s33 offset:532 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v229, off, s33 offset:536 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v230, off, s33 offset:540 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v231, off, s33 offset:544 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v240, off, s33 offset:548 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v241, off, s33 offset:552 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v242, off, s33 offset:556 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v243, off, s33 offset:560 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v244, off, s33 offset:564 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v245, off, s33 offset:568 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v246, off, s33 offset:572 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v247, off, s33 offset:576 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 64 ; msbs: dst=1 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0 /*v256*/, off, s33 offset:580 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1 /*v257*/, off, s33 offset:584 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v2 /*v258*/, off, s33 offset:588 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v3 /*v259*/, off, s33 offset:592 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v4 /*v260*/, off, s33 offset:596 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v5 /*v261*/, off, s33 offset:600 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v6 /*v262*/, off, s33 offset:604 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v7 /*v263*/, off, s33 offset:608 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v8 /*v264*/, off, s33 offset:612 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v9 /*v265*/, off, s33 offset:616 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v10 /*v266*/, off, s33 offset:620 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v11 /*v267*/, off, s33 offset:624 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v12 /*v268*/, off, s33 offset:628 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v13 /*v269*/, off, s33 offset:632 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v14 /*v270*/, off, s33 offset:636 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v15 /*v271*/, off, s33 offset:640 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v16 /*v272*/, off, s33 offset:644 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v17 /*v273*/, off, s33 offset:648 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v18 /*v274*/, off, s33 offset:652 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v19 /*v275*/, off, s33 offset:656 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v20 /*v276*/, off, s33 offset:660 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v21 /*v277*/, off, s33 offset:664 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v22 /*v278*/, off, s33 offset:668 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v23 /*v279*/, off, s33 offset:672 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v24 /*v280*/, off, s33 offset:676 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v25 /*v281*/, off, s33 offset:680 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v26 /*v282*/, off, s33 offset:684 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v27 /*v283*/, off, s33 offset:688 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v28 /*v284*/, off, s33 offset:692 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v29 /*v285*/, off, s33 offset:696 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v30 /*v286*/, off, s33 offset:700 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v31 /*v287*/, off, s33 offset:704 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v32 /*v288*/, off, s33 offset:708 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v33 /*v289*/, off, s33 offset:712 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v34 /*v290*/, off, s33 offset:716 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v35 /*v291*/, off, s33 offset:720 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v36 /*v292*/, off, s33 offset:724 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v37 /*v293*/, off, s33 offset:728 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v38 /*v294*/, off, s33 offset:732 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v39 /*v295*/, off, s33 offset:736 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v40 /*v296*/, off, s33 offset:740 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v41 /*v297*/, off, s33 offset:744 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v42 /*v298*/, off, s33 offset:748 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v43 /*v299*/, off, s33 offset:752 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v44 /*v300*/, off, s33 offset:756 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v45 /*v301*/, off, s33 offset:760 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v46 /*v302*/, off, s33 offset:764 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v47 /*v303*/, off, s33 offset:768 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v48 /*v304*/, off, s33 offset:772 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v49 /*v305*/, off, s33 offset:776 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v50 /*v306*/, off, s33 offset:780 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v51 /*v307*/, off, s33 offset:784 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v52 /*v308*/, off, s33 offset:788 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v53 /*v309*/, off, s33 offset:792 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v54 /*v310*/, off, s33 offset:796 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v55 /*v311*/, off, s33 offset:800 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v56 /*v312*/, off, s33 offset:804 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v57 /*v313*/, off, s33 offset:808 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v58 /*v314*/, off, s33 offset:812 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v59 /*v315*/, off, s33 offset:816 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v60 /*v316*/, off, s33 offset:820 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v61 /*v317*/, off, s33 offset:824 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v62 /*v318*/, off, s33 offset:828 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v63 /*v319*/, off, s33 offset:832 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v64 /*v320*/, off, s33 offset:836 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v65 /*v321*/, off, s33 offset:840 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v66 /*v322*/, off, s33 offset:844 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v67 /*v323*/, off, s33 offset:848 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v68 /*v324*/, off, s33 offset:852 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v69 /*v325*/, off, s33 offset:856 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v70 /*v326*/, off, s33 offset:860 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v71 /*v327*/, off, s33 offset:864 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v72 /*v328*/, off, s33 offset:868 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v73 /*v329*/, off, s33 offset:872 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v74 /*v330*/, off, s33 offset:876 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v75 /*v331*/, off, s33 offset:880 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v76 /*v332*/, off, s33 offset:884 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v77 /*v333*/, off, s33 offset:888 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v78 /*v334*/, off, s33 offset:892 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v79 /*v335*/, off, s33 offset:896 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v80 /*v336*/, off, s33 offset:900 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v81 /*v337*/, off, s33 offset:904 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v82 /*v338*/, off, s33 offset:908 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v83 /*v339*/, off, s33 offset:912 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v84 /*v340*/, off, s33 offset:916 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v85 /*v341*/, off, s33 offset:920 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v86 /*v342*/, off, s33 offset:924 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v87 /*v343*/, off, s33 offset:928 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v88 /*v344*/, off, s33 offset:932 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v89 /*v345*/, off, s33 offset:936 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v90 /*v346*/, off, s33 offset:940 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v91 /*v347*/, off, s33 offset:944 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v92 /*v348*/, off, s33 offset:948 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v93 /*v349*/, off, s33 offset:952 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v94 /*v350*/, off, s33 offset:956 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v95 /*v351*/, off, s33 offset:960 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v96 /*v352*/, off, s33 offset:964 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v97 /*v353*/, off, s33 offset:968 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v98 /*v354*/, off, s33 offset:972 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v99 /*v355*/, off, s33 offset:976 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v100 /*v356*/, off, s33 offset:980 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v101 /*v357*/, off, s33 offset:984 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v102 /*v358*/, off, s33 offset:988 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v103 /*v359*/, off, s33 offset:992 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v104 /*v360*/, off, s33 offset:996 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v105 /*v361*/, off, s33 offset:1000 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v106 /*v362*/, off, s33 offset:1004 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v107 /*v363*/, off, s33 offset:1008 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v108 /*v364*/, off, s33 offset:1012 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v109 /*v365*/, off, s33 offset:1016 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v110 /*v366*/, off, s33 offset:1020 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v111 /*v367*/, off, s33 offset:1024 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v112 /*v368*/, off, s33 offset:1028 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v113 /*v369*/, off, s33 offset:1032 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v114 /*v370*/, off, s33 offset:1036 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v115 /*v371*/, off, s33 offset:1040 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v116 /*v372*/, off, s33 offset:1044 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v117 /*v373*/, off, s33 offset:1048 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v118 /*v374*/, off, s33 offset:1052 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v119 /*v375*/, off, s33 offset:1056 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v120 /*v376*/, off, s33 offset:1060 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v121 /*v377*/, off, s33 offset:1064 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v122 /*v378*/, off, s33 offset:1068 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v123 /*v379*/, off, s33 offset:1072 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v124 /*v380*/, off, s33 offset:1076 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v125 /*v381*/, off, s33 offset:1080 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v126 /*v382*/, off, s33 offset:1084 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v127 /*v383*/, off, s33 offset:1088 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v128 /*v384*/, off, s33 offset:1092 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v129 /*v385*/, off, s33 offset:1096 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v130 /*v386*/, off, s33 offset:1100 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v131 /*v387*/, off, s33 offset:1104 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v132 /*v388*/, off, s33 offset:1108 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v133 /*v389*/, off, s33 offset:1112 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v134 /*v390*/, off, s33 offset:1116 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v135 /*v391*/, off, s33 offset:1120 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v136 /*v392*/, off, s33 offset:1124 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v137 /*v393*/, off, s33 offset:1128 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v138 /*v394*/, off, s33 offset:1132 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v139 /*v395*/, off, s33 offset:1136 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v140 /*v396*/, off, s33 offset:1140 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v141 /*v397*/, off, s33 offset:1144 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v142 /*v398*/, off, s33 offset:1148 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v143 /*v399*/, off, s33 offset:1152 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v144 /*v400*/, off, s33 offset:1156 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v145 /*v401*/, off, s33 offset:1160 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v146 /*v402*/, off, s33 offset:1164 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v147 /*v403*/, off, s33 offset:1168 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v148 /*v404*/, off, s33 offset:1172 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v149 /*v405*/, off, s33 offset:1176 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v150 /*v406*/, off, s33 offset:1180 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v151 /*v407*/, off, s33 offset:1184 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v152 /*v408*/, off, s33 offset:1188 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v153 /*v409*/, off, s33 offset:1192 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v154 /*v410*/, off, s33 offset:1196 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v155 /*v411*/, off, s33 offset:1200 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v156 /*v412*/, off, s33 offset:1204 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v157 /*v413*/, off, s33 offset:1208 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v158 /*v414*/, off, s33 offset:1212 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v159 /*v415*/, off, s33 offset:1216 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v160 /*v416*/, off, s33 offset:1220 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v161 /*v417*/, off, s33 offset:1224 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v162 /*v418*/, off, s33 offset:1228 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v163 /*v419*/, off, s33 offset:1232 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v164 /*v420*/, off, s33 offset:1236 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v165 /*v421*/, off, s33 offset:1240 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v166 /*v422*/, off, s33 offset:1244 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v167 /*v423*/, off, s33 offset:1248 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v168 /*v424*/, off, s33 offset:1252 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v169 /*v425*/, off, s33 offset:1256 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v170 /*v426*/, off, s33 offset:1260 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v171 /*v427*/, off, s33 offset:1264 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v172 /*v428*/, off, s33 offset:1268 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v173 /*v429*/, off, s33 offset:1272 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v174 /*v430*/, off, s33 offset:1276 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v175 /*v431*/, off, s33 offset:1280 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v176 /*v432*/, off, s33 offset:1284 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v177 /*v433*/, off, s33 offset:1288 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v178 /*v434*/, off, s33 offset:1292 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v179 /*v435*/, off, s33 offset:1296 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v180 /*v436*/, off, s33 offset:1300 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v181 /*v437*/, off, s33 offset:1304 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v182 /*v438*/, off, s33 offset:1308 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v183 /*v439*/, off, s33 offset:1312 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v184 /*v440*/, off, s33 offset:1316 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v185 /*v441*/, off, s33 offset:1320 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v186 /*v442*/, off, s33 offset:1324 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v187 /*v443*/, off, s33 offset:1328 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v188 /*v444*/, off, s33 offset:1332 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v189 /*v445*/, off, s33 offset:1336 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v190 /*v446*/, off, s33 offset:1340 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v191 /*v447*/, off, s33 offset:1344 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v192 /*v448*/, off, s33 offset:1348 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v193 /*v449*/, off, s33 offset:1352 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v194 /*v450*/, off, s33 offset:1356 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v195 /*v451*/, off, s33 offset:1360 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v196 /*v452*/, off, s33 offset:1364 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v197 /*v453*/, off, s33 offset:1368 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v198 /*v454*/, off, s33 offset:1372 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v199 /*v455*/, off, s33 offset:1376 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v200 /*v456*/, off, s33 offset:1380 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v201 /*v457*/, off, s33 offset:1384 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v202 /*v458*/, off, s33 offset:1388 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v203 /*v459*/, off, s33 offset:1392 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v204 /*v460*/, off, s33 offset:1396 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v205 /*v461*/, off, s33 offset:1400 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v206 /*v462*/, off, s33 offset:1404 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v207 /*v463*/, off, s33 offset:1408 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v208 /*v464*/, off, s33 offset:1412 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v209 /*v465*/, off, s33 offset:1416 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v210 /*v466*/, off, s33 offset:1420 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v211 /*v467*/, off, s33 offset:1424 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v212 /*v468*/, off, s33 offset:1428 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v213 /*v469*/, off, s33 offset:1432 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v214 /*v470*/, off, s33 offset:1436 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v215 /*v471*/, off, s33 offset:1440 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v216 /*v472*/, off, s33 offset:1444 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v217 /*v473*/, off, s33 offset:1448 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v218 /*v474*/, off, s33 offset:1452 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v219 /*v475*/, off, s33 offset:1456 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v220 /*v476*/, off, s33 offset:1460 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v221 /*v477*/, off, s33 offset:1464 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v222 /*v478*/, off, s33 offset:1468 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v223 /*v479*/, off, s33 offset:1472 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v224 /*v480*/, off, s33 offset:1476 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v225 /*v481*/, off, s33 offset:1480 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v226 /*v482*/, off, s33 offset:1484 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v227 /*v483*/, off, s33 offset:1488 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v228 /*v484*/, off, s33 offset:1492 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v229 /*v485*/, off, s33 offset:1496 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v230 /*v486*/, off, s33 offset:1500 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v231 /*v487*/, off, s33 offset:1504 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v232 /*v488*/, off, s33 offset:1508 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v233 /*v489*/, off, s33 offset:1512 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v234 /*v490*/, off, s33 offset:1516 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v235 /*v491*/, off, s33 offset:1520 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v236 /*v492*/, off, s33 offset:1524 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v237 /*v493*/, off, s33 offset:1528 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v238 /*v494*/, off, s33 offset:1532 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v239 /*v495*/, off, s33 offset:1536 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v240 /*v496*/, off, s33 offset:1540 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v241 /*v497*/, off, s33 offset:1544 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v242 /*v498*/, off, s33 offset:1548 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v243 /*v499*/, off, s33 offset:1552 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v244 /*v500*/, off, s33 offset:1556 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v245 /*v501*/, off, s33 offset:1560 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v246 /*v502*/, off, s33 offset:1564 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v247 /*v503*/, off, s33 offset:1568 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v248 /*v504*/, off, s33 offset:1572 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v249 /*v505*/, off, s33 offset:1576 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v250 /*v506*/, off, s33 offset:1580 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v251 /*v507*/, off, s33 offset:1584 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v252 /*v508*/, off, s33 offset:1588 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v253 /*v509*/, off, s33 offset:1592 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v254 /*v510*/, off, s33 offset:1596 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v255 /*v511*/, off, s33 offset:1600 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0x4080 ; msbs: dst=2 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0 /*v512*/, off, s33 offset:1604 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1 /*v513*/, off, s33 offset:1608 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v2 /*v514*/, off, s33 offset:1612 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v3 /*v515*/, off, s33 offset:1616 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v4 /*v516*/, off, s33 offset:1620 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v5 /*v517*/, off, s33 offset:1624 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v6 /*v518*/, off, s33 offset:1628 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v7 /*v519*/, off, s33 offset:1632 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v8 /*v520*/, off, s33 offset:1636 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v9 /*v521*/, off, s33 offset:1640 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v10 /*v522*/, off, s33 offset:1644 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v11 /*v523*/, off, s33 offset:1648 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v12 /*v524*/, off, s33 offset:1652 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v13 /*v525*/, off, s33 offset:1656 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v14 /*v526*/, off, s33 offset:1660 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v15 /*v527*/, off, s33 offset:1664 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v16 /*v528*/, off, s33 offset:1668 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v17 /*v529*/, off, s33 offset:1672 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v18 /*v530*/, off, s33 offset:1676 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v19 /*v531*/, off, s33 offset:1680 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v20 /*v532*/, off, s33 offset:1684 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v21 /*v533*/, off, s33 offset:1688 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v22 /*v534*/, off, s33 offset:1692 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v23 /*v535*/, off, s33 offset:1696 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v24 /*v536*/, off, s33 offset:1700 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v25 /*v537*/, off, s33 offset:1704 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v26 /*v538*/, off, s33 offset:1708 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v27 /*v539*/, off, s33 offset:1712 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v28 /*v540*/, off, s33 offset:1716 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v29 /*v541*/, off, s33 offset:1720 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v30 /*v542*/, off, s33 offset:1724 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v31 /*v543*/, off, s33 offset:1728 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v32 /*v544*/, off, s33 offset:1732 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v33 /*v545*/, off, s33 offset:1736 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v34 /*v546*/, off, s33 offset:1740 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v35 /*v547*/, off, s33 offset:1744 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v36 /*v548*/, off, s33 offset:1748 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v37 /*v549*/, off, s33 offset:1752 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v38 /*v550*/, off, s33 offset:1756 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v39 /*v551*/, off, s33 offset:1760 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v40 /*v552*/, off, s33 offset:1764 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v41 /*v553*/, off, s33 offset:1768 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v42 /*v554*/, off, s33 offset:1772 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v43 /*v555*/, off, s33 offset:1776 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v44 /*v556*/, off, s33 offset:1780 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v45 /*v557*/, off, s33 offset:1784 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v46 /*v558*/, off, s33 offset:1788 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v47 /*v559*/, off, s33 offset:1792 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v48 /*v560*/, off, s33 offset:1796 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v49 /*v561*/, off, s33 offset:1800 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v50 /*v562*/, off, s33 offset:1804 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v51 /*v563*/, off, s33 offset:1808 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v52 /*v564*/, off, s33 offset:1812 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v53 /*v565*/, off, s33 offset:1816 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v54 /*v566*/, off, s33 offset:1820 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v55 /*v567*/, off, s33 offset:1824 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v56 /*v568*/, off, s33 offset:1828 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v57 /*v569*/, off, s33 offset:1832 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v58 /*v570*/, off, s33 offset:1836 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v59 /*v571*/, off, s33 offset:1840 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v60 /*v572*/, off, s33 offset:1844 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v61 /*v573*/, off, s33 offset:1848 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v62 /*v574*/, off, s33 offset:1852 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v63 /*v575*/, off, s33 offset:1856 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v64 /*v576*/, off, s33 offset:1860 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v65 /*v577*/, off, s33 offset:1864 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v66 /*v578*/, off, s33 offset:1868 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v67 /*v579*/, off, s33 offset:1872 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v68 /*v580*/, off, s33 offset:1876 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v69 /*v581*/, off, s33 offset:1880 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v70 /*v582*/, off, s33 offset:1884 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v71 /*v583*/, off, s33 offset:1888 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v72 /*v584*/, off, s33 offset:1892 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v73 /*v585*/, off, s33 offset:1896 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v74 /*v586*/, off, s33 offset:1900 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v75 /*v587*/, off, s33 offset:1904 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v76 /*v588*/, off, s33 offset:1908 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v77 /*v589*/, off, s33 offset:1912 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v78 /*v590*/, off, s33 offset:1916 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v79 /*v591*/, off, s33 offset:1920 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v80 /*v592*/, off, s33 offset:1924 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v81 /*v593*/, off, s33 offset:1928 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v82 /*v594*/, off, s33 offset:1932 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v83 /*v595*/, off, s33 offset:1936 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v84 /*v596*/, off, s33 offset:1940 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v85 /*v597*/, off, s33 offset:1944 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v86 /*v598*/, off, s33 offset:1948 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v87 /*v599*/, off, s33 offset:1952 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v88 /*v600*/, off, s33 offset:1956 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v89 /*v601*/, off, s33 offset:1960 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v90 /*v602*/, off, s33 offset:1964 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v91 /*v603*/, off, s33 offset:1968 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v92 /*v604*/, off, s33 offset:1972 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v93 /*v605*/, off, s33 offset:1976 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v94 /*v606*/, off, s33 offset:1980 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v95 /*v607*/, off, s33 offset:1984 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v96 /*v608*/, off, s33 offset:1988 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v97 /*v609*/, off, s33 offset:1992 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v98 /*v610*/, off, s33 offset:1996 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v99 /*v611*/, off, s33 offset:2000 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v100 /*v612*/, off, s33 offset:2004 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v101 /*v613*/, off, s33 offset:2008 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v102 /*v614*/, off, s33 offset:2012 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v103 /*v615*/, off, s33 offset:2016 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v104 /*v616*/, off, s33 offset:2020 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v105 /*v617*/, off, s33 offset:2024 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v106 /*v618*/, off, s33 offset:2028 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v107 /*v619*/, off, s33 offset:2032 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v108 /*v620*/, off, s33 offset:2036 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v109 /*v621*/, off, s33 offset:2040 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v110 /*v622*/, off, s33 offset:2044 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v111 /*v623*/, off, s33 offset:2048 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v112 /*v624*/, off, s33 offset:2052 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v113 /*v625*/, off, s33 offset:2056 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v114 /*v626*/, off, s33 offset:2060 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v115 /*v627*/, off, s33 offset:2064 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v116 /*v628*/, off, s33 offset:2068 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v117 /*v629*/, off, s33 offset:2072 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v118 /*v630*/, off, s33 offset:2076 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v119 /*v631*/, off, s33 offset:2080 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v120 /*v632*/, off, s33 offset:2084 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v121 /*v633*/, off, s33 offset:2088 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v122 /*v634*/, off, s33 offset:2092 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v123 /*v635*/, off, s33 offset:2096 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v124 /*v636*/, off, s33 offset:2100 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v125 /*v637*/, off, s33 offset:2104 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v126 /*v638*/, off, s33 offset:2108 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v127 /*v639*/, off, s33 offset:2112 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v128 /*v640*/, off, s33 offset:2116 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v129 /*v641*/, off, s33 offset:2120 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v130 /*v642*/, off, s33 offset:2124 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v131 /*v643*/, off, s33 offset:2128 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v132 /*v644*/, off, s33 offset:2132 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v133 /*v645*/, off, s33 offset:2136 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v134 /*v646*/, off, s33 offset:2140 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v135 /*v647*/, off, s33 offset:2144 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v136 /*v648*/, off, s33 offset:2148 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v137 /*v649*/, off, s33 offset:2152 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v138 /*v650*/, off, s33 offset:2156 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v139 /*v651*/, off, s33 offset:2160 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v140 /*v652*/, off, s33 offset:2164 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v141 /*v653*/, off, s33 offset:2168 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v142 /*v654*/, off, s33 offset:2172 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v143 /*v655*/, off, s33 offset:2176 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v144 /*v656*/, off, s33 offset:2180 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v145 /*v657*/, off, s33 offset:2184 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v146 /*v658*/, off, s33 offset:2188 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v147 /*v659*/, off, s33 offset:2192 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v148 /*v660*/, off, s33 offset:2196 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v149 /*v661*/, off, s33 offset:2200 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v150 /*v662*/, off, s33 offset:2204 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v151 /*v663*/, off, s33 offset:2208 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v152 /*v664*/, off, s33 offset:2212 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v153 /*v665*/, off, s33 offset:2216 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v154 /*v666*/, off, s33 offset:2220 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v155 /*v667*/, off, s33 offset:2224 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v156 /*v668*/, off, s33 offset:2228 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v157 /*v669*/, off, s33 offset:2232 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v158 /*v670*/, off, s33 offset:2236 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v159 /*v671*/, off, s33 offset:2240 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v160 /*v672*/, off, s33 offset:2244 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v161 /*v673*/, off, s33 offset:2248 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v162 /*v674*/, off, s33 offset:2252 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v163 /*v675*/, off, s33 offset:2256 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v164 /*v676*/, off, s33 offset:2260 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v165 /*v677*/, off, s33 offset:2264 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v166 /*v678*/, off, s33 offset:2268 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v167 /*v679*/, off, s33 offset:2272 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v168 /*v680*/, off, s33 offset:2276 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v169 /*v681*/, off, s33 offset:2280 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v170 /*v682*/, off, s33 offset:2284 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v171 /*v683*/, off, s33 offset:2288 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v172 /*v684*/, off, s33 offset:2292 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v173 /*v685*/, off, s33 offset:2296 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v174 /*v686*/, off, s33 offset:2300 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v175 /*v687*/, off, s33 offset:2304 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v176 /*v688*/, off, s33 offset:2308 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v177 /*v689*/, off, s33 offset:2312 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v178 /*v690*/, off, s33 offset:2316 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v179 /*v691*/, off, s33 offset:2320 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v180 /*v692*/, off, s33 offset:2324 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v181 /*v693*/, off, s33 offset:2328 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v182 /*v694*/, off, s33 offset:2332 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v183 /*v695*/, off, s33 offset:2336 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v184 /*v696*/, off, s33 offset:2340 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v185 /*v697*/, off, s33 offset:2344 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v186 /*v698*/, off, s33 offset:2348 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v187 /*v699*/, off, s33 offset:2352 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v188 /*v700*/, off, s33 offset:2356 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v189 /*v701*/, off, s33 offset:2360 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v190 /*v702*/, off, s33 offset:2364 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v191 /*v703*/, off, s33 offset:2368 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v192 /*v704*/, off, s33 offset:2372 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v193 /*v705*/, off, s33 offset:2376 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v194 /*v706*/, off, s33 offset:2380 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v195 /*v707*/, off, s33 offset:2384 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v196 /*v708*/, off, s33 offset:2388 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v197 /*v709*/, off, s33 offset:2392 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v198 /*v710*/, off, s33 offset:2396 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v199 /*v711*/, off, s33 offset:2400 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v200 /*v712*/, off, s33 offset:2404 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v201 /*v713*/, off, s33 offset:2408 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v202 /*v714*/, off, s33 offset:2412 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v203 /*v715*/, off, s33 offset:2416 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v204 /*v716*/, off, s33 offset:2420 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v205 /*v717*/, off, s33 offset:2424 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v206 /*v718*/, off, s33 offset:2428 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v207 /*v719*/, off, s33 offset:2432 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v208 /*v720*/, off, s33 offset:2436 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v209 /*v721*/, off, s33 offset:2440 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v210 /*v722*/, off, s33 offset:2444 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v211 /*v723*/, off, s33 offset:2448 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v212 /*v724*/, off, s33 offset:2452 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v213 /*v725*/, off, s33 offset:2456 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v214 /*v726*/, off, s33 offset:2460 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v215 /*v727*/, off, s33 offset:2464 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v216 /*v728*/, off, s33 offset:2468 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v217 /*v729*/, off, s33 offset:2472 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v218 /*v730*/, off, s33 offset:2476 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v219 /*v731*/, off, s33 offset:2480 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v220 /*v732*/, off, s33 offset:2484 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v221 /*v733*/, off, s33 offset:2488 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v222 /*v734*/, off, s33 offset:2492 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v223 /*v735*/, off, s33 offset:2496 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v224 /*v736*/, off, s33 offset:2500 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v225 /*v737*/, off, s33 offset:2504 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v226 /*v738*/, off, s33 offset:2508 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v227 /*v739*/, off, s33 offset:2512 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v228 /*v740*/, off, s33 offset:2516 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v229 /*v741*/, off, s33 offset:2520 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v230 /*v742*/, off, s33 offset:2524 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v231 /*v743*/, off, s33 offset:2528 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v232 /*v744*/, off, s33 offset:2532 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v233 /*v745*/, off, s33 offset:2536 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v234 /*v746*/, off, s33 offset:2540 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v235 /*v747*/, off, s33 offset:2544 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v236 /*v748*/, off, s33 offset:2548 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v237 /*v749*/, off, s33 offset:2552 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v238 /*v750*/, off, s33 offset:2556 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v239 /*v751*/, off, s33 offset:2560 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v240 /*v752*/, off, s33 offset:2564 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v241 /*v753*/, off, s33 offset:2568 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v242 /*v754*/, off, s33 offset:2572 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v243 /*v755*/, off, s33 offset:2576 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v244 /*v756*/, off, s33 offset:2580 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v245 /*v757*/, off, s33 offset:2584 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v246 /*v758*/, off, s33 offset:2588 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v247 /*v759*/, off, s33 offset:2592 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v248 /*v760*/, off, s33 offset:2596 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v249 /*v761*/, off, s33 offset:2600 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v250 /*v762*/, off, s33 offset:2604 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v251 /*v763*/, off, s33 offset:2608 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v252 /*v764*/, off, s33 offset:2612 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v253 /*v765*/, off, s33 offset:2616 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v254 /*v766*/, off, s33 offset:2620 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v255 /*v767*/, off, s33 offset:2624 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0x80c0 ; msbs: dst=3 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0 /*v768*/, off, s33 offset:2628 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1 /*v769*/, off, s33 offset:2632 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v2 /*v770*/, off, s33 offset:2636 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v3 /*v771*/, off, s33 offset:2640 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v4 /*v772*/, off, s33 offset:2644 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v5 /*v773*/, off, s33 offset:2648 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v6 /*v774*/, off, s33 offset:2652 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v7 /*v775*/, off, s33 offset:2656 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v8 /*v776*/, off, s33 offset:2660 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v9 /*v777*/, off, s33 offset:2664 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v10 /*v778*/, off, s33 offset:2668 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v11 /*v779*/, off, s33 offset:2672 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v12 /*v780*/, off, s33 offset:2676 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v13 /*v781*/, off, s33 offset:2680 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v14 /*v782*/, off, s33 offset:2684 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v15 /*v783*/, off, s33 offset:2688 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v16 /*v784*/, off, s33 offset:2692 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v17 /*v785*/, off, s33 offset:2696 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v18 /*v786*/, off, s33 offset:2700 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v19 /*v787*/, off, s33 offset:2704 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v20 /*v788*/, off, s33 offset:2708 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v21 /*v789*/, off, s33 offset:2712 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v22 /*v790*/, off, s33 offset:2716 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v23 /*v791*/, off, s33 offset:2720 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v24 /*v792*/, off, s33 offset:2724 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v25 /*v793*/, off, s33 offset:2728 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v26 /*v794*/, off, s33 offset:2732 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v27 /*v795*/, off, s33 offset:2736 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v28 /*v796*/, off, s33 offset:2740 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v29 /*v797*/, off, s33 offset:2744 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v30 /*v798*/, off, s33 offset:2748 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v31 /*v799*/, off, s33 offset:2752 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v32 /*v800*/, off, s33 offset:2756 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v33 /*v801*/, off, s33 offset:2760 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v34 /*v802*/, off, s33 offset:2764 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v35 /*v803*/, off, s33 offset:2768 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v36 /*v804*/, off, s33 offset:2772 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v37 /*v805*/, off, s33 offset:2776 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v38 /*v806*/, off, s33 offset:2780 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v39 /*v807*/, off, s33 offset:2784 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v40 /*v808*/, off, s33 offset:2788 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v41 /*v809*/, off, s33 offset:2792 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v42 /*v810*/, off, s33 offset:2796 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v43 /*v811*/, off, s33 offset:2800 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v44 /*v812*/, off, s33 offset:2804 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v45 /*v813*/, off, s33 offset:2808 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v46 /*v814*/, off, s33 offset:2812 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v47 /*v815*/, off, s33 offset:2816 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v48 /*v816*/, off, s33 offset:2820 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v49 /*v817*/, off, s33 offset:2824 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v50 /*v818*/, off, s33 offset:2828 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v51 /*v819*/, off, s33 offset:2832 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v52 /*v820*/, off, s33 offset:2836 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v53 /*v821*/, off, s33 offset:2840 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v54 /*v822*/, off, s33 offset:2844 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v55 /*v823*/, off, s33 offset:2848 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v56 /*v824*/, off, s33 offset:2852 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v57 /*v825*/, off, s33 offset:2856 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v58 /*v826*/, off, s33 offset:2860 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v59 /*v827*/, off, s33 offset:2864 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v60 /*v828*/, off, s33 offset:2868 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v61 /*v829*/, off, s33 offset:2872 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v62 /*v830*/, off, s33 offset:2876 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v63 /*v831*/, off, s33 offset:2880 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v64 /*v832*/, off, s33 offset:2884 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v65 /*v833*/, off, s33 offset:2888 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v66 /*v834*/, off, s33 offset:2892 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v67 /*v835*/, off, s33 offset:2896 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v68 /*v836*/, off, s33 offset:2900 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v69 /*v837*/, off, s33 offset:2904 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v70 /*v838*/, off, s33 offset:2908 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v71 /*v839*/, off, s33 offset:2912 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v72 /*v840*/, off, s33 offset:2916 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v73 /*v841*/, off, s33 offset:2920 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v74 /*v842*/, off, s33 offset:2924 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v75 /*v843*/, off, s33 offset:2928 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v76 /*v844*/, off, s33 offset:2932 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v77 /*v845*/, off, s33 offset:2936 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v78 /*v846*/, off, s33 offset:2940 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v79 /*v847*/, off, s33 offset:2944 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v80 /*v848*/, off, s33 offset:2948 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v81 /*v849*/, off, s33 offset:2952 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v82 /*v850*/, off, s33 offset:2956 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v83 /*v851*/, off, s33 offset:2960 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v84 /*v852*/, off, s33 offset:2964 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v85 /*v853*/, off, s33 offset:2968 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v86 /*v854*/, off, s33 offset:2972 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v87 /*v855*/, off, s33 offset:2976 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v88 /*v856*/, off, s33 offset:2980 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v89 /*v857*/, off, s33 offset:2984 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v90 /*v858*/, off, s33 offset:2988 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v91 /*v859*/, off, s33 offset:2992 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v92 /*v860*/, off, s33 offset:2996 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v93 /*v861*/, off, s33 offset:3000 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v94 /*v862*/, off, s33 offset:3004 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v95 /*v863*/, off, s33 offset:3008 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v96 /*v864*/, off, s33 offset:3012 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v97 /*v865*/, off, s33 offset:3016 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v98 /*v866*/, off, s33 offset:3020 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v99 /*v867*/, off, s33 offset:3024 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v100 /*v868*/, off, s33 offset:3028 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v101 /*v869*/, off, s33 offset:3032 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v102 /*v870*/, off, s33 offset:3036 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v103 /*v871*/, off, s33 offset:3040 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v104 /*v872*/, off, s33 offset:3044 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v105 /*v873*/, off, s33 offset:3048 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v106 /*v874*/, off, s33 offset:3052 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v107 /*v875*/, off, s33 offset:3056 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v108 /*v876*/, off, s33 offset:3060 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v109 /*v877*/, off, s33 offset:3064 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v110 /*v878*/, off, s33 offset:3068 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v111 /*v879*/, off, s33 offset:3072 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v112 /*v880*/, off, s33 offset:3076 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v113 /*v881*/, off, s33 offset:3080 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v114 /*v882*/, off, s33 offset:3084 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v115 /*v883*/, off, s33 offset:3088 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v116 /*v884*/, off, s33 offset:3092 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v117 /*v885*/, off, s33 offset:3096 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v118 /*v886*/, off, s33 offset:3100 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v119 /*v887*/, off, s33 offset:3104 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v120 /*v888*/, off, s33 offset:3108 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v121 /*v889*/, off, s33 offset:3112 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v122 /*v890*/, off, s33 offset:3116 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v123 /*v891*/, off, s33 offset:3120 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v124 /*v892*/, off, s33 offset:3124 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v125 /*v893*/, off, s33 offset:3128 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v126 /*v894*/, off, s33 offset:3132 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v127 /*v895*/, off, s33 offset:3136 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v128 /*v896*/, off, s33 offset:3140 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v129 /*v897*/, off, s33 offset:3144 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v130 /*v898*/, off, s33 offset:3148 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v131 /*v899*/, off, s33 offset:3152 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v132 /*v900*/, off, s33 offset:3156 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v133 /*v901*/, off, s33 offset:3160 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v134 /*v902*/, off, s33 offset:3164 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v135 /*v903*/, off, s33 offset:3168 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v136 /*v904*/, off, s33 offset:3172 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v137 /*v905*/, off, s33 offset:3176 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v138 /*v906*/, off, s33 offset:3180 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v139 /*v907*/, off, s33 offset:3184 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v140 /*v908*/, off, s33 offset:3188 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v141 /*v909*/, off, s33 offset:3192 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v142 /*v910*/, off, s33 offset:3196 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v143 /*v911*/, off, s33 offset:3200 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v144 /*v912*/, off, s33 offset:3204 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v145 /*v913*/, off, s33 offset:3208 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v146 /*v914*/, off, s33 offset:3212 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v147 /*v915*/, off, s33 offset:3216 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v148 /*v916*/, off, s33 offset:3220 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v149 /*v917*/, off, s33 offset:3224 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v150 /*v918*/, off, s33 offset:3228 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v151 /*v919*/, off, s33 offset:3232 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v152 /*v920*/, off, s33 offset:3236 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v153 /*v921*/, off, s33 offset:3240 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v154 /*v922*/, off, s33 offset:3244 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v155 /*v923*/, off, s33 offset:3248 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v156 /*v924*/, off, s33 offset:3252 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v157 /*v925*/, off, s33 offset:3256 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v158 /*v926*/, off, s33 offset:3260 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v159 /*v927*/, off, s33 offset:3264 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v160 /*v928*/, off, s33 offset:3268 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v161 /*v929*/, off, s33 offset:3272 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v162 /*v930*/, off, s33 offset:3276 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v163 /*v931*/, off, s33 offset:3280 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v164 /*v932*/, off, s33 offset:3284 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v165 /*v933*/, off, s33 offset:3288 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v166 /*v934*/, off, s33 offset:3292 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v167 /*v935*/, off, s33 offset:3296 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v168 /*v936*/, off, s33 offset:3300 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v169 /*v937*/, off, s33 offset:3304 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v170 /*v938*/, off, s33 offset:3308 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v171 /*v939*/, off, s33 offset:3312 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v172 /*v940*/, off, s33 offset:3316 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v173 /*v941*/, off, s33 offset:3320 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v174 /*v942*/, off, s33 offset:3324 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v175 /*v943*/, off, s33 offset:3328 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v176 /*v944*/, off, s33 offset:3332 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v177 /*v945*/, off, s33 offset:3336 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v178 /*v946*/, off, s33 offset:3340 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v179 /*v947*/, off, s33 offset:3344 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v180 /*v948*/, off, s33 offset:3348 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v181 /*v949*/, off, s33 offset:3352 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v182 /*v950*/, off, s33 offset:3356 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v183 /*v951*/, off, s33 offset:3360 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v184 /*v952*/, off, s33 offset:3364 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v185 /*v953*/, off, s33 offset:3368 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v186 /*v954*/, off, s33 offset:3372 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v187 /*v955*/, off, s33 offset:3376 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v188 /*v956*/, off, s33 offset:3380 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v189 /*v957*/, off, s33 offset:3384 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v190 /*v958*/, off, s33 offset:3388 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v191 /*v959*/, off, s33 offset:3392 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v192 /*v960*/, off, s33 offset:3396 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v193 /*v961*/, off, s33 offset:3400 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v194 /*v962*/, off, s33 offset:3404 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v195 /*v963*/, off, s33 offset:3408 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v196 /*v964*/, off, s33 offset:3412 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v197 /*v965*/, off, s33 offset:3416 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v198 /*v966*/, off, s33 offset:3420 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v199 /*v967*/, off, s33 offset:3424 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v200 /*v968*/, off, s33 offset:3428 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v201 /*v969*/, off, s33 offset:3432 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v202 /*v970*/, off, s33 offset:3436 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v203 /*v971*/, off, s33 offset:3440 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v204 /*v972*/, off, s33 offset:3444 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v205 /*v973*/, off, s33 offset:3448 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v206 /*v974*/, off, s33 offset:3452 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v207 /*v975*/, off, s33 offset:3456 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v208 /*v976*/, off, s33 offset:3460 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v209 /*v977*/, off, s33 offset:3464 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v210 /*v978*/, off, s33 offset:3468 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v211 /*v979*/, off, s33 offset:3472 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v212 /*v980*/, off, s33 offset:3476 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v213 /*v981*/, off, s33 offset:3480 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v214 /*v982*/, off, s33 offset:3484 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v215 /*v983*/, off, s33 offset:3488 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v216 /*v984*/, off, s33 offset:3492 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v217 /*v985*/, off, s33 offset:3496 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v218 /*v986*/, off, s33 offset:3500 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v219 /*v987*/, off, s33 offset:3504 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v220 /*v988*/, off, s33 offset:3508 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v221 /*v989*/, off, s33 offset:3512 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v222 /*v990*/, off, s33 offset:3516 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v223 /*v991*/, off, s33 offset:3520 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v224 /*v992*/, off, s33 offset:3524 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v225 /*v993*/, off, s33 offset:3528 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x1d ; 120-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v226 /*v994*/, off, s33 offset:3532 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v227 /*v995*/, off, s33 offset:3536 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v228 /*v996*/, off, s33 offset:3540 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v229 /*v997*/, off, s33 offset:3544 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v230 /*v998*/, off, s33 offset:3548 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v231 /*v999*/, off, s33 offset:3552 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v232 /*v1000*/, off, s33 offset:3556 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v233 /*v1001*/, off, s33 offset:3560 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v234 /*v1002*/, off, s33 offset:3564 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v235 /*v1003*/, off, s33 offset:3568 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v236 /*v1004*/, off, s33 offset:3572 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v237 /*v1005*/, off, s33 offset:3576 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v238 /*v1006*/, off, s33 offset:3580 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v239 /*v1007*/, off, s33 offset:3584 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v240 /*v1008*/, off, s33 offset:3588 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v241 /*v1009*/, off, s33 offset:3592 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v242 /*v1010*/, off, s33 offset:3596 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v243 /*v1011*/, off, s33 offset:3600 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v244 /*v1012*/, off, s33 offset:3604 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v245 /*v1013*/, off, s33 offset:3608 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v246 /*v1014*/, off, s33 offset:3612 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v247 /*v1015*/, off, s33 offset:3616 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v248 /*v1016*/, off, s33 offset:3620 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v249 /*v1017*/, off, s33 offset:3624 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v250 /*v1018*/, off, s33 offset:3628 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v251 /*v1019*/, off, s33 offset:3632 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v252 /*v1020*/, off, s33 offset:3636 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v253 /*v1021*/, off, s33 offset:3640 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v254 /*v1022*/, off, s33 offset:3644 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v255 /*v1023*/, off, s33 offset:3648 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, s4
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s33, s0
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0xc000 ; msbs: dst=0 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_set_pc_i64 s[30:31]
  %ret = call amdgpu_gfx <2 x half>(<2 x half>, <2 x half>) @gfx_callee(<2 x half> %y, <2 x half> %x) convergent
  ret <2 x half> %ret
}

define amdgpu_gfx_whole_wave <2 x half> @tail_call_gfx_from_whole_wave(i1 %active, <2 x half> %x, <2 x half> %y) #0 {
  ; This should not be turned into a tail call.
; DAGISEL-LABEL: tail_call_gfx_from_whole_wave:
; DAGISEL:       ; %bb.0:
; DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL-NEXT:    s_wait_expcnt 0x0
; DAGISEL-NEXT:    s_wait_samplecnt 0x0
; DAGISEL-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL-NEXT:    s_wait_kmcnt 0x0
; DAGISEL-NEXT:    s_xor_saveexec_b32 s0, -1
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v0, s32
; DAGISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; DAGISEL-NEXT:    scratch_store_b32 off, v2, s32 offset:8
; DAGISEL-NEXT:    scratch_store_b32 off, v3, s32 offset:12
; DAGISEL-NEXT:    scratch_store_b32 off, v4, s32 offset:16
; DAGISEL-NEXT:    scratch_store_b32 off, v5, s32 offset:20
; DAGISEL-NEXT:    scratch_store_b32 off, v6, s32 offset:24
; DAGISEL-NEXT:    scratch_store_b32 off, v7, s32 offset:28
; DAGISEL-NEXT:    scratch_store_b32 off, v8, s32 offset:32
; DAGISEL-NEXT:    scratch_store_b32 off, v9, s32 offset:36
; DAGISEL-NEXT:    scratch_store_b32 off, v10, s32 offset:40
; DAGISEL-NEXT:    scratch_store_b32 off, v11, s32 offset:44
; DAGISEL-NEXT:    scratch_store_b32 off, v12, s32 offset:48
; DAGISEL-NEXT:    scratch_store_b32 off, v13, s32 offset:52
; DAGISEL-NEXT:    scratch_store_b32 off, v14, s32 offset:56
; DAGISEL-NEXT:    scratch_store_b32 off, v15, s32 offset:60
; DAGISEL-NEXT:    scratch_store_b32 off, v16, s32 offset:64
; DAGISEL-NEXT:    scratch_store_b32 off, v17, s32 offset:68
; DAGISEL-NEXT:    scratch_store_b32 off, v18, s32 offset:72
; DAGISEL-NEXT:    scratch_store_b32 off, v19, s32 offset:76
; DAGISEL-NEXT:    scratch_store_b32 off, v20, s32 offset:80
; DAGISEL-NEXT:    scratch_store_b32 off, v21, s32 offset:84
; DAGISEL-NEXT:    scratch_store_b32 off, v22, s32 offset:88
; DAGISEL-NEXT:    scratch_store_b32 off, v23, s32 offset:92
; DAGISEL-NEXT:    scratch_store_b32 off, v24, s32 offset:96
; DAGISEL-NEXT:    scratch_store_b32 off, v25, s32 offset:100
; DAGISEL-NEXT:    scratch_store_b32 off, v26, s32 offset:104
; DAGISEL-NEXT:    scratch_store_b32 off, v27, s32 offset:108
; DAGISEL-NEXT:    scratch_store_b32 off, v28, s32 offset:112
; DAGISEL-NEXT:    scratch_store_b32 off, v29, s32 offset:116
; DAGISEL-NEXT:    scratch_store_b32 off, v30, s32 offset:120
; DAGISEL-NEXT:    scratch_store_b32 off, v31, s32 offset:124
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v32, s32 offset:128
; DAGISEL-NEXT:    scratch_store_b32 off, v33, s32 offset:132
; DAGISEL-NEXT:    scratch_store_b32 off, v34, s32 offset:136
; DAGISEL-NEXT:    scratch_store_b32 off, v35, s32 offset:140
; DAGISEL-NEXT:    scratch_store_b32 off, v36, s32 offset:144
; DAGISEL-NEXT:    scratch_store_b32 off, v37, s32 offset:148
; DAGISEL-NEXT:    scratch_store_b32 off, v38, s32 offset:152
; DAGISEL-NEXT:    scratch_store_b32 off, v39, s32 offset:156
; DAGISEL-NEXT:    scratch_store_b32 off, v48, s32 offset:160
; DAGISEL-NEXT:    scratch_store_b32 off, v49, s32 offset:164
; DAGISEL-NEXT:    scratch_store_b32 off, v50, s32 offset:168
; DAGISEL-NEXT:    scratch_store_b32 off, v51, s32 offset:172
; DAGISEL-NEXT:    scratch_store_b32 off, v52, s32 offset:176
; DAGISEL-NEXT:    scratch_store_b32 off, v53, s32 offset:180
; DAGISEL-NEXT:    scratch_store_b32 off, v54, s32 offset:184
; DAGISEL-NEXT:    scratch_store_b32 off, v55, s32 offset:188
; DAGISEL-NEXT:    scratch_store_b32 off, v64, s32 offset:192
; DAGISEL-NEXT:    scratch_store_b32 off, v65, s32 offset:196
; DAGISEL-NEXT:    scratch_store_b32 off, v66, s32 offset:200
; DAGISEL-NEXT:    scratch_store_b32 off, v67, s32 offset:204
; DAGISEL-NEXT:    scratch_store_b32 off, v68, s32 offset:208
; DAGISEL-NEXT:    scratch_store_b32 off, v69, s32 offset:212
; DAGISEL-NEXT:    scratch_store_b32 off, v70, s32 offset:216
; DAGISEL-NEXT:    scratch_store_b32 off, v71, s32 offset:220
; DAGISEL-NEXT:    scratch_store_b32 off, v80, s32 offset:224
; DAGISEL-NEXT:    scratch_store_b32 off, v81, s32 offset:228
; DAGISEL-NEXT:    scratch_store_b32 off, v82, s32 offset:232
; DAGISEL-NEXT:    scratch_store_b32 off, v83, s32 offset:236
; DAGISEL-NEXT:    scratch_store_b32 off, v84, s32 offset:240
; DAGISEL-NEXT:    scratch_store_b32 off, v85, s32 offset:244
; DAGISEL-NEXT:    scratch_store_b32 off, v86, s32 offset:248
; DAGISEL-NEXT:    scratch_store_b32 off, v87, s32 offset:252
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v96, s32 offset:256
; DAGISEL-NEXT:    scratch_store_b32 off, v97, s32 offset:260
; DAGISEL-NEXT:    scratch_store_b32 off, v98, s32 offset:264
; DAGISEL-NEXT:    scratch_store_b32 off, v99, s32 offset:268
; DAGISEL-NEXT:    scratch_store_b32 off, v100, s32 offset:272
; DAGISEL-NEXT:    scratch_store_b32 off, v101, s32 offset:276
; DAGISEL-NEXT:    scratch_store_b32 off, v102, s32 offset:280
; DAGISEL-NEXT:    scratch_store_b32 off, v103, s32 offset:284
; DAGISEL-NEXT:    scratch_store_b32 off, v112, s32 offset:288
; DAGISEL-NEXT:    scratch_store_b32 off, v113, s32 offset:292
; DAGISEL-NEXT:    scratch_store_b32 off, v114, s32 offset:296
; DAGISEL-NEXT:    scratch_store_b32 off, v115, s32 offset:300
; DAGISEL-NEXT:    scratch_store_b32 off, v116, s32 offset:304
; DAGISEL-NEXT:    scratch_store_b32 off, v117, s32 offset:308
; DAGISEL-NEXT:    scratch_store_b32 off, v118, s32 offset:312
; DAGISEL-NEXT:    scratch_store_b32 off, v119, s32 offset:316
; DAGISEL-NEXT:    scratch_store_b32 off, v128, s32 offset:320
; DAGISEL-NEXT:    scratch_store_b32 off, v129, s32 offset:324
; DAGISEL-NEXT:    scratch_store_b32 off, v130, s32 offset:328
; DAGISEL-NEXT:    scratch_store_b32 off, v131, s32 offset:332
; DAGISEL-NEXT:    scratch_store_b32 off, v132, s32 offset:336
; DAGISEL-NEXT:    scratch_store_b32 off, v133, s32 offset:340
; DAGISEL-NEXT:    scratch_store_b32 off, v134, s32 offset:344
; DAGISEL-NEXT:    scratch_store_b32 off, v135, s32 offset:348
; DAGISEL-NEXT:    scratch_store_b32 off, v144, s32 offset:352
; DAGISEL-NEXT:    scratch_store_b32 off, v145, s32 offset:356
; DAGISEL-NEXT:    scratch_store_b32 off, v146, s32 offset:360
; DAGISEL-NEXT:    scratch_store_b32 off, v147, s32 offset:364
; DAGISEL-NEXT:    scratch_store_b32 off, v148, s32 offset:368
; DAGISEL-NEXT:    scratch_store_b32 off, v149, s32 offset:372
; DAGISEL-NEXT:    scratch_store_b32 off, v150, s32 offset:376
; DAGISEL-NEXT:    scratch_store_b32 off, v151, s32 offset:380
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v160, s32 offset:384
; DAGISEL-NEXT:    scratch_store_b32 off, v161, s32 offset:388
; DAGISEL-NEXT:    scratch_store_b32 off, v162, s32 offset:392
; DAGISEL-NEXT:    scratch_store_b32 off, v163, s32 offset:396
; DAGISEL-NEXT:    scratch_store_b32 off, v164, s32 offset:400
; DAGISEL-NEXT:    scratch_store_b32 off, v165, s32 offset:404
; DAGISEL-NEXT:    scratch_store_b32 off, v166, s32 offset:408
; DAGISEL-NEXT:    scratch_store_b32 off, v167, s32 offset:412
; DAGISEL-NEXT:    scratch_store_b32 off, v176, s32 offset:416
; DAGISEL-NEXT:    scratch_store_b32 off, v177, s32 offset:420
; DAGISEL-NEXT:    scratch_store_b32 off, v178, s32 offset:424
; DAGISEL-NEXT:    scratch_store_b32 off, v179, s32 offset:428
; DAGISEL-NEXT:    scratch_store_b32 off, v180, s32 offset:432
; DAGISEL-NEXT:    scratch_store_b32 off, v181, s32 offset:436
; DAGISEL-NEXT:    scratch_store_b32 off, v182, s32 offset:440
; DAGISEL-NEXT:    scratch_store_b32 off, v183, s32 offset:444
; DAGISEL-NEXT:    scratch_store_b32 off, v192, s32 offset:448
; DAGISEL-NEXT:    scratch_store_b32 off, v193, s32 offset:452
; DAGISEL-NEXT:    scratch_store_b32 off, v194, s32 offset:456
; DAGISEL-NEXT:    scratch_store_b32 off, v195, s32 offset:460
; DAGISEL-NEXT:    scratch_store_b32 off, v196, s32 offset:464
; DAGISEL-NEXT:    scratch_store_b32 off, v197, s32 offset:468
; DAGISEL-NEXT:    scratch_store_b32 off, v198, s32 offset:472
; DAGISEL-NEXT:    scratch_store_b32 off, v199, s32 offset:476
; DAGISEL-NEXT:    scratch_store_b32 off, v208, s32 offset:480
; DAGISEL-NEXT:    scratch_store_b32 off, v209, s32 offset:484
; DAGISEL-NEXT:    scratch_store_b32 off, v210, s32 offset:488
; DAGISEL-NEXT:    scratch_store_b32 off, v211, s32 offset:492
; DAGISEL-NEXT:    scratch_store_b32 off, v212, s32 offset:496
; DAGISEL-NEXT:    scratch_store_b32 off, v213, s32 offset:500
; DAGISEL-NEXT:    scratch_store_b32 off, v214, s32 offset:504
; DAGISEL-NEXT:    scratch_store_b32 off, v215, s32 offset:508
; DAGISEL-NEXT:    s_clause 0xf ; 64-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v224, s32 offset:512
; DAGISEL-NEXT:    scratch_store_b32 off, v225, s32 offset:516
; DAGISEL-NEXT:    scratch_store_b32 off, v226, s32 offset:520
; DAGISEL-NEXT:    scratch_store_b32 off, v227, s32 offset:524
; DAGISEL-NEXT:    scratch_store_b32 off, v228, s32 offset:528
; DAGISEL-NEXT:    scratch_store_b32 off, v229, s32 offset:532
; DAGISEL-NEXT:    scratch_store_b32 off, v230, s32 offset:536
; DAGISEL-NEXT:    scratch_store_b32 off, v231, s32 offset:540
; DAGISEL-NEXT:    scratch_store_b32 off, v240, s32 offset:544
; DAGISEL-NEXT:    scratch_store_b32 off, v241, s32 offset:548
; DAGISEL-NEXT:    scratch_store_b32 off, v242, s32 offset:552
; DAGISEL-NEXT:    scratch_store_b32 off, v243, s32 offset:556
; DAGISEL-NEXT:    scratch_store_b32 off, v244, s32 offset:560
; DAGISEL-NEXT:    scratch_store_b32 off, v245, s32 offset:564
; DAGISEL-NEXT:    scratch_store_b32 off, v246, s32 offset:568
; DAGISEL-NEXT:    scratch_store_b32 off, v247, s32 offset:572
; DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; DAGISEL-NEXT:    v_mov_b32_e32 v2, v0
; DAGISEL-NEXT:    s_mov_b32 s37, gfx_callee@abs32@hi
; DAGISEL-NEXT:    s_mov_b32 s36, gfx_callee@abs32@lo
; DAGISEL-NEXT:    v_swap_b32 v0, v1
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    s_xor_b32 exec_lo, s0, -1
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v0, off, s32
; DAGISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; DAGISEL-NEXT:    scratch_load_b32 v2, off, s32 offset:8
; DAGISEL-NEXT:    scratch_load_b32 v3, off, s32 offset:12
; DAGISEL-NEXT:    scratch_load_b32 v4, off, s32 offset:16
; DAGISEL-NEXT:    scratch_load_b32 v5, off, s32 offset:20
; DAGISEL-NEXT:    scratch_load_b32 v6, off, s32 offset:24
; DAGISEL-NEXT:    scratch_load_b32 v7, off, s32 offset:28
; DAGISEL-NEXT:    scratch_load_b32 v8, off, s32 offset:32
; DAGISEL-NEXT:    scratch_load_b32 v9, off, s32 offset:36
; DAGISEL-NEXT:    scratch_load_b32 v10, off, s32 offset:40
; DAGISEL-NEXT:    scratch_load_b32 v11, off, s32 offset:44
; DAGISEL-NEXT:    scratch_load_b32 v12, off, s32 offset:48
; DAGISEL-NEXT:    scratch_load_b32 v13, off, s32 offset:52
; DAGISEL-NEXT:    scratch_load_b32 v14, off, s32 offset:56
; DAGISEL-NEXT:    scratch_load_b32 v15, off, s32 offset:60
; DAGISEL-NEXT:    scratch_load_b32 v16, off, s32 offset:64
; DAGISEL-NEXT:    scratch_load_b32 v17, off, s32 offset:68
; DAGISEL-NEXT:    scratch_load_b32 v18, off, s32 offset:72
; DAGISEL-NEXT:    scratch_load_b32 v19, off, s32 offset:76
; DAGISEL-NEXT:    scratch_load_b32 v20, off, s32 offset:80
; DAGISEL-NEXT:    scratch_load_b32 v21, off, s32 offset:84
; DAGISEL-NEXT:    scratch_load_b32 v22, off, s32 offset:88
; DAGISEL-NEXT:    scratch_load_b32 v23, off, s32 offset:92
; DAGISEL-NEXT:    scratch_load_b32 v24, off, s32 offset:96
; DAGISEL-NEXT:    scratch_load_b32 v25, off, s32 offset:100
; DAGISEL-NEXT:    scratch_load_b32 v26, off, s32 offset:104
; DAGISEL-NEXT:    scratch_load_b32 v27, off, s32 offset:108
; DAGISEL-NEXT:    scratch_load_b32 v28, off, s32 offset:112
; DAGISEL-NEXT:    scratch_load_b32 v29, off, s32 offset:116
; DAGISEL-NEXT:    scratch_load_b32 v30, off, s32 offset:120
; DAGISEL-NEXT:    scratch_load_b32 v31, off, s32 offset:124
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v32, off, s32 offset:128
; DAGISEL-NEXT:    scratch_load_b32 v33, off, s32 offset:132
; DAGISEL-NEXT:    scratch_load_b32 v34, off, s32 offset:136
; DAGISEL-NEXT:    scratch_load_b32 v35, off, s32 offset:140
; DAGISEL-NEXT:    scratch_load_b32 v36, off, s32 offset:144
; DAGISEL-NEXT:    scratch_load_b32 v37, off, s32 offset:148
; DAGISEL-NEXT:    scratch_load_b32 v38, off, s32 offset:152
; DAGISEL-NEXT:    scratch_load_b32 v39, off, s32 offset:156
; DAGISEL-NEXT:    scratch_load_b32 v48, off, s32 offset:160
; DAGISEL-NEXT:    scratch_load_b32 v49, off, s32 offset:164
; DAGISEL-NEXT:    scratch_load_b32 v50, off, s32 offset:168
; DAGISEL-NEXT:    scratch_load_b32 v51, off, s32 offset:172
; DAGISEL-NEXT:    scratch_load_b32 v52, off, s32 offset:176
; DAGISEL-NEXT:    scratch_load_b32 v53, off, s32 offset:180
; DAGISEL-NEXT:    scratch_load_b32 v54, off, s32 offset:184
; DAGISEL-NEXT:    scratch_load_b32 v55, off, s32 offset:188
; DAGISEL-NEXT:    scratch_load_b32 v64, off, s32 offset:192
; DAGISEL-NEXT:    scratch_load_b32 v65, off, s32 offset:196
; DAGISEL-NEXT:    scratch_load_b32 v66, off, s32 offset:200
; DAGISEL-NEXT:    scratch_load_b32 v67, off, s32 offset:204
; DAGISEL-NEXT:    scratch_load_b32 v68, off, s32 offset:208
; DAGISEL-NEXT:    scratch_load_b32 v69, off, s32 offset:212
; DAGISEL-NEXT:    scratch_load_b32 v70, off, s32 offset:216
; DAGISEL-NEXT:    scratch_load_b32 v71, off, s32 offset:220
; DAGISEL-NEXT:    scratch_load_b32 v80, off, s32 offset:224
; DAGISEL-NEXT:    scratch_load_b32 v81, off, s32 offset:228
; DAGISEL-NEXT:    scratch_load_b32 v82, off, s32 offset:232
; DAGISEL-NEXT:    scratch_load_b32 v83, off, s32 offset:236
; DAGISEL-NEXT:    scratch_load_b32 v84, off, s32 offset:240
; DAGISEL-NEXT:    scratch_load_b32 v85, off, s32 offset:244
; DAGISEL-NEXT:    scratch_load_b32 v86, off, s32 offset:248
; DAGISEL-NEXT:    scratch_load_b32 v87, off, s32 offset:252
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v96, off, s32 offset:256
; DAGISEL-NEXT:    scratch_load_b32 v97, off, s32 offset:260
; DAGISEL-NEXT:    scratch_load_b32 v98, off, s32 offset:264
; DAGISEL-NEXT:    scratch_load_b32 v99, off, s32 offset:268
; DAGISEL-NEXT:    scratch_load_b32 v100, off, s32 offset:272
; DAGISEL-NEXT:    scratch_load_b32 v101, off, s32 offset:276
; DAGISEL-NEXT:    scratch_load_b32 v102, off, s32 offset:280
; DAGISEL-NEXT:    scratch_load_b32 v103, off, s32 offset:284
; DAGISEL-NEXT:    scratch_load_b32 v112, off, s32 offset:288
; DAGISEL-NEXT:    scratch_load_b32 v113, off, s32 offset:292
; DAGISEL-NEXT:    scratch_load_b32 v114, off, s32 offset:296
; DAGISEL-NEXT:    scratch_load_b32 v115, off, s32 offset:300
; DAGISEL-NEXT:    scratch_load_b32 v116, off, s32 offset:304
; DAGISEL-NEXT:    scratch_load_b32 v117, off, s32 offset:308
; DAGISEL-NEXT:    scratch_load_b32 v118, off, s32 offset:312
; DAGISEL-NEXT:    scratch_load_b32 v119, off, s32 offset:316
; DAGISEL-NEXT:    scratch_load_b32 v128, off, s32 offset:320
; DAGISEL-NEXT:    scratch_load_b32 v129, off, s32 offset:324
; DAGISEL-NEXT:    scratch_load_b32 v130, off, s32 offset:328
; DAGISEL-NEXT:    scratch_load_b32 v131, off, s32 offset:332
; DAGISEL-NEXT:    scratch_load_b32 v132, off, s32 offset:336
; DAGISEL-NEXT:    scratch_load_b32 v133, off, s32 offset:340
; DAGISEL-NEXT:    scratch_load_b32 v134, off, s32 offset:344
; DAGISEL-NEXT:    scratch_load_b32 v135, off, s32 offset:348
; DAGISEL-NEXT:    scratch_load_b32 v144, off, s32 offset:352
; DAGISEL-NEXT:    scratch_load_b32 v145, off, s32 offset:356
; DAGISEL-NEXT:    scratch_load_b32 v146, off, s32 offset:360
; DAGISEL-NEXT:    scratch_load_b32 v147, off, s32 offset:364
; DAGISEL-NEXT:    scratch_load_b32 v148, off, s32 offset:368
; DAGISEL-NEXT:    scratch_load_b32 v149, off, s32 offset:372
; DAGISEL-NEXT:    scratch_load_b32 v150, off, s32 offset:376
; DAGISEL-NEXT:    scratch_load_b32 v151, off, s32 offset:380
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v160, off, s32 offset:384
; DAGISEL-NEXT:    scratch_load_b32 v161, off, s32 offset:388
; DAGISEL-NEXT:    scratch_load_b32 v162, off, s32 offset:392
; DAGISEL-NEXT:    scratch_load_b32 v163, off, s32 offset:396
; DAGISEL-NEXT:    scratch_load_b32 v164, off, s32 offset:400
; DAGISEL-NEXT:    scratch_load_b32 v165, off, s32 offset:404
; DAGISEL-NEXT:    scratch_load_b32 v166, off, s32 offset:408
; DAGISEL-NEXT:    scratch_load_b32 v167, off, s32 offset:412
; DAGISEL-NEXT:    scratch_load_b32 v176, off, s32 offset:416
; DAGISEL-NEXT:    scratch_load_b32 v177, off, s32 offset:420
; DAGISEL-NEXT:    scratch_load_b32 v178, off, s32 offset:424
; DAGISEL-NEXT:    scratch_load_b32 v179, off, s32 offset:428
; DAGISEL-NEXT:    scratch_load_b32 v180, off, s32 offset:432
; DAGISEL-NEXT:    scratch_load_b32 v181, off, s32 offset:436
; DAGISEL-NEXT:    scratch_load_b32 v182, off, s32 offset:440
; DAGISEL-NEXT:    scratch_load_b32 v183, off, s32 offset:444
; DAGISEL-NEXT:    scratch_load_b32 v192, off, s32 offset:448
; DAGISEL-NEXT:    scratch_load_b32 v193, off, s32 offset:452
; DAGISEL-NEXT:    scratch_load_b32 v194, off, s32 offset:456
; DAGISEL-NEXT:    scratch_load_b32 v195, off, s32 offset:460
; DAGISEL-NEXT:    scratch_load_b32 v196, off, s32 offset:464
; DAGISEL-NEXT:    scratch_load_b32 v197, off, s32 offset:468
; DAGISEL-NEXT:    scratch_load_b32 v198, off, s32 offset:472
; DAGISEL-NEXT:    scratch_load_b32 v199, off, s32 offset:476
; DAGISEL-NEXT:    scratch_load_b32 v208, off, s32 offset:480
; DAGISEL-NEXT:    scratch_load_b32 v209, off, s32 offset:484
; DAGISEL-NEXT:    scratch_load_b32 v210, off, s32 offset:488
; DAGISEL-NEXT:    scratch_load_b32 v211, off, s32 offset:492
; DAGISEL-NEXT:    scratch_load_b32 v212, off, s32 offset:496
; DAGISEL-NEXT:    scratch_load_b32 v213, off, s32 offset:500
; DAGISEL-NEXT:    scratch_load_b32 v214, off, s32 offset:504
; DAGISEL-NEXT:    scratch_load_b32 v215, off, s32 offset:508
; DAGISEL-NEXT:    s_clause 0xf ; 64-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v224, off, s32 offset:512
; DAGISEL-NEXT:    scratch_load_b32 v225, off, s32 offset:516
; DAGISEL-NEXT:    scratch_load_b32 v226, off, s32 offset:520
; DAGISEL-NEXT:    scratch_load_b32 v227, off, s32 offset:524
; DAGISEL-NEXT:    scratch_load_b32 v228, off, s32 offset:528
; DAGISEL-NEXT:    scratch_load_b32 v229, off, s32 offset:532
; DAGISEL-NEXT:    scratch_load_b32 v230, off, s32 offset:536
; DAGISEL-NEXT:    scratch_load_b32 v231, off, s32 offset:540
; DAGISEL-NEXT:    scratch_load_b32 v240, off, s32 offset:544
; DAGISEL-NEXT:    scratch_load_b32 v241, off, s32 offset:548
; DAGISEL-NEXT:    scratch_load_b32 v242, off, s32 offset:552
; DAGISEL-NEXT:    scratch_load_b32 v243, off, s32 offset:556
; DAGISEL-NEXT:    scratch_load_b32 v244, off, s32 offset:560
; DAGISEL-NEXT:    scratch_load_b32 v245, off, s32 offset:564
; DAGISEL-NEXT:    scratch_load_b32 v246, off, s32 offset:568
; DAGISEL-NEXT:    scratch_load_b32 v247, off, s32 offset:572
; DAGISEL-NEXT:    s_mov_b32 exec_lo, s0
; DAGISEL-NEXT:    s_setpc_b64 s[36:37]
;
; GISEL-LABEL: tail_call_gfx_from_whole_wave:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL-NEXT:    s_wait_expcnt 0x0
; GISEL-NEXT:    s_wait_samplecnt 0x0
; GISEL-NEXT:    s_wait_bvhcnt 0x0
; GISEL-NEXT:    s_wait_kmcnt 0x0
; GISEL-NEXT:    s_xor_saveexec_b32 s0, -1
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v0, s32
; GISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; GISEL-NEXT:    scratch_store_b32 off, v2, s32 offset:8
; GISEL-NEXT:    scratch_store_b32 off, v3, s32 offset:12
; GISEL-NEXT:    scratch_store_b32 off, v4, s32 offset:16
; GISEL-NEXT:    scratch_store_b32 off, v5, s32 offset:20
; GISEL-NEXT:    scratch_store_b32 off, v6, s32 offset:24
; GISEL-NEXT:    scratch_store_b32 off, v7, s32 offset:28
; GISEL-NEXT:    scratch_store_b32 off, v8, s32 offset:32
; GISEL-NEXT:    scratch_store_b32 off, v9, s32 offset:36
; GISEL-NEXT:    scratch_store_b32 off, v10, s32 offset:40
; GISEL-NEXT:    scratch_store_b32 off, v11, s32 offset:44
; GISEL-NEXT:    scratch_store_b32 off, v12, s32 offset:48
; GISEL-NEXT:    scratch_store_b32 off, v13, s32 offset:52
; GISEL-NEXT:    scratch_store_b32 off, v14, s32 offset:56
; GISEL-NEXT:    scratch_store_b32 off, v15, s32 offset:60
; GISEL-NEXT:    scratch_store_b32 off, v16, s32 offset:64
; GISEL-NEXT:    scratch_store_b32 off, v17, s32 offset:68
; GISEL-NEXT:    scratch_store_b32 off, v18, s32 offset:72
; GISEL-NEXT:    scratch_store_b32 off, v19, s32 offset:76
; GISEL-NEXT:    scratch_store_b32 off, v20, s32 offset:80
; GISEL-NEXT:    scratch_store_b32 off, v21, s32 offset:84
; GISEL-NEXT:    scratch_store_b32 off, v22, s32 offset:88
; GISEL-NEXT:    scratch_store_b32 off, v23, s32 offset:92
; GISEL-NEXT:    scratch_store_b32 off, v24, s32 offset:96
; GISEL-NEXT:    scratch_store_b32 off, v25, s32 offset:100
; GISEL-NEXT:    scratch_store_b32 off, v26, s32 offset:104
; GISEL-NEXT:    scratch_store_b32 off, v27, s32 offset:108
; GISEL-NEXT:    scratch_store_b32 off, v28, s32 offset:112
; GISEL-NEXT:    scratch_store_b32 off, v29, s32 offset:116
; GISEL-NEXT:    scratch_store_b32 off, v30, s32 offset:120
; GISEL-NEXT:    scratch_store_b32 off, v31, s32 offset:124
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v32, s32 offset:128
; GISEL-NEXT:    scratch_store_b32 off, v33, s32 offset:132
; GISEL-NEXT:    scratch_store_b32 off, v34, s32 offset:136
; GISEL-NEXT:    scratch_store_b32 off, v35, s32 offset:140
; GISEL-NEXT:    scratch_store_b32 off, v36, s32 offset:144
; GISEL-NEXT:    scratch_store_b32 off, v37, s32 offset:148
; GISEL-NEXT:    scratch_store_b32 off, v38, s32 offset:152
; GISEL-NEXT:    scratch_store_b32 off, v39, s32 offset:156
; GISEL-NEXT:    scratch_store_b32 off, v48, s32 offset:160
; GISEL-NEXT:    scratch_store_b32 off, v49, s32 offset:164
; GISEL-NEXT:    scratch_store_b32 off, v50, s32 offset:168
; GISEL-NEXT:    scratch_store_b32 off, v51, s32 offset:172
; GISEL-NEXT:    scratch_store_b32 off, v52, s32 offset:176
; GISEL-NEXT:    scratch_store_b32 off, v53, s32 offset:180
; GISEL-NEXT:    scratch_store_b32 off, v54, s32 offset:184
; GISEL-NEXT:    scratch_store_b32 off, v55, s32 offset:188
; GISEL-NEXT:    scratch_store_b32 off, v64, s32 offset:192
; GISEL-NEXT:    scratch_store_b32 off, v65, s32 offset:196
; GISEL-NEXT:    scratch_store_b32 off, v66, s32 offset:200
; GISEL-NEXT:    scratch_store_b32 off, v67, s32 offset:204
; GISEL-NEXT:    scratch_store_b32 off, v68, s32 offset:208
; GISEL-NEXT:    scratch_store_b32 off, v69, s32 offset:212
; GISEL-NEXT:    scratch_store_b32 off, v70, s32 offset:216
; GISEL-NEXT:    scratch_store_b32 off, v71, s32 offset:220
; GISEL-NEXT:    scratch_store_b32 off, v80, s32 offset:224
; GISEL-NEXT:    scratch_store_b32 off, v81, s32 offset:228
; GISEL-NEXT:    scratch_store_b32 off, v82, s32 offset:232
; GISEL-NEXT:    scratch_store_b32 off, v83, s32 offset:236
; GISEL-NEXT:    scratch_store_b32 off, v84, s32 offset:240
; GISEL-NEXT:    scratch_store_b32 off, v85, s32 offset:244
; GISEL-NEXT:    scratch_store_b32 off, v86, s32 offset:248
; GISEL-NEXT:    scratch_store_b32 off, v87, s32 offset:252
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v96, s32 offset:256
; GISEL-NEXT:    scratch_store_b32 off, v97, s32 offset:260
; GISEL-NEXT:    scratch_store_b32 off, v98, s32 offset:264
; GISEL-NEXT:    scratch_store_b32 off, v99, s32 offset:268
; GISEL-NEXT:    scratch_store_b32 off, v100, s32 offset:272
; GISEL-NEXT:    scratch_store_b32 off, v101, s32 offset:276
; GISEL-NEXT:    scratch_store_b32 off, v102, s32 offset:280
; GISEL-NEXT:    scratch_store_b32 off, v103, s32 offset:284
; GISEL-NEXT:    scratch_store_b32 off, v112, s32 offset:288
; GISEL-NEXT:    scratch_store_b32 off, v113, s32 offset:292
; GISEL-NEXT:    scratch_store_b32 off, v114, s32 offset:296
; GISEL-NEXT:    scratch_store_b32 off, v115, s32 offset:300
; GISEL-NEXT:    scratch_store_b32 off, v116, s32 offset:304
; GISEL-NEXT:    scratch_store_b32 off, v117, s32 offset:308
; GISEL-NEXT:    scratch_store_b32 off, v118, s32 offset:312
; GISEL-NEXT:    scratch_store_b32 off, v119, s32 offset:316
; GISEL-NEXT:    scratch_store_b32 off, v128, s32 offset:320
; GISEL-NEXT:    scratch_store_b32 off, v129, s32 offset:324
; GISEL-NEXT:    scratch_store_b32 off, v130, s32 offset:328
; GISEL-NEXT:    scratch_store_b32 off, v131, s32 offset:332
; GISEL-NEXT:    scratch_store_b32 off, v132, s32 offset:336
; GISEL-NEXT:    scratch_store_b32 off, v133, s32 offset:340
; GISEL-NEXT:    scratch_store_b32 off, v134, s32 offset:344
; GISEL-NEXT:    scratch_store_b32 off, v135, s32 offset:348
; GISEL-NEXT:    scratch_store_b32 off, v144, s32 offset:352
; GISEL-NEXT:    scratch_store_b32 off, v145, s32 offset:356
; GISEL-NEXT:    scratch_store_b32 off, v146, s32 offset:360
; GISEL-NEXT:    scratch_store_b32 off, v147, s32 offset:364
; GISEL-NEXT:    scratch_store_b32 off, v148, s32 offset:368
; GISEL-NEXT:    scratch_store_b32 off, v149, s32 offset:372
; GISEL-NEXT:    scratch_store_b32 off, v150, s32 offset:376
; GISEL-NEXT:    scratch_store_b32 off, v151, s32 offset:380
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v160, s32 offset:384
; GISEL-NEXT:    scratch_store_b32 off, v161, s32 offset:388
; GISEL-NEXT:    scratch_store_b32 off, v162, s32 offset:392
; GISEL-NEXT:    scratch_store_b32 off, v163, s32 offset:396
; GISEL-NEXT:    scratch_store_b32 off, v164, s32 offset:400
; GISEL-NEXT:    scratch_store_b32 off, v165, s32 offset:404
; GISEL-NEXT:    scratch_store_b32 off, v166, s32 offset:408
; GISEL-NEXT:    scratch_store_b32 off, v167, s32 offset:412
; GISEL-NEXT:    scratch_store_b32 off, v176, s32 offset:416
; GISEL-NEXT:    scratch_store_b32 off, v177, s32 offset:420
; GISEL-NEXT:    scratch_store_b32 off, v178, s32 offset:424
; GISEL-NEXT:    scratch_store_b32 off, v179, s32 offset:428
; GISEL-NEXT:    scratch_store_b32 off, v180, s32 offset:432
; GISEL-NEXT:    scratch_store_b32 off, v181, s32 offset:436
; GISEL-NEXT:    scratch_store_b32 off, v182, s32 offset:440
; GISEL-NEXT:    scratch_store_b32 off, v183, s32 offset:444
; GISEL-NEXT:    scratch_store_b32 off, v192, s32 offset:448
; GISEL-NEXT:    scratch_store_b32 off, v193, s32 offset:452
; GISEL-NEXT:    scratch_store_b32 off, v194, s32 offset:456
; GISEL-NEXT:    scratch_store_b32 off, v195, s32 offset:460
; GISEL-NEXT:    scratch_store_b32 off, v196, s32 offset:464
; GISEL-NEXT:    scratch_store_b32 off, v197, s32 offset:468
; GISEL-NEXT:    scratch_store_b32 off, v198, s32 offset:472
; GISEL-NEXT:    scratch_store_b32 off, v199, s32 offset:476
; GISEL-NEXT:    scratch_store_b32 off, v208, s32 offset:480
; GISEL-NEXT:    scratch_store_b32 off, v209, s32 offset:484
; GISEL-NEXT:    scratch_store_b32 off, v210, s32 offset:488
; GISEL-NEXT:    scratch_store_b32 off, v211, s32 offset:492
; GISEL-NEXT:    scratch_store_b32 off, v212, s32 offset:496
; GISEL-NEXT:    scratch_store_b32 off, v213, s32 offset:500
; GISEL-NEXT:    scratch_store_b32 off, v214, s32 offset:504
; GISEL-NEXT:    scratch_store_b32 off, v215, s32 offset:508
; GISEL-NEXT:    s_clause 0xf ; 64-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v224, s32 offset:512
; GISEL-NEXT:    scratch_store_b32 off, v225, s32 offset:516
; GISEL-NEXT:    scratch_store_b32 off, v226, s32 offset:520
; GISEL-NEXT:    scratch_store_b32 off, v227, s32 offset:524
; GISEL-NEXT:    scratch_store_b32 off, v228, s32 offset:528
; GISEL-NEXT:    scratch_store_b32 off, v229, s32 offset:532
; GISEL-NEXT:    scratch_store_b32 off, v230, s32 offset:536
; GISEL-NEXT:    scratch_store_b32 off, v231, s32 offset:540
; GISEL-NEXT:    scratch_store_b32 off, v240, s32 offset:544
; GISEL-NEXT:    scratch_store_b32 off, v241, s32 offset:548
; GISEL-NEXT:    scratch_store_b32 off, v242, s32 offset:552
; GISEL-NEXT:    scratch_store_b32 off, v243, s32 offset:556
; GISEL-NEXT:    scratch_store_b32 off, v244, s32 offset:560
; GISEL-NEXT:    scratch_store_b32 off, v245, s32 offset:564
; GISEL-NEXT:    scratch_store_b32 off, v246, s32 offset:568
; GISEL-NEXT:    scratch_store_b32 off, v247, s32 offset:572
; GISEL-NEXT:    s_mov_b32 exec_lo, -1
; GISEL-NEXT:    v_mov_b32_e32 v2, v0
; GISEL-NEXT:    s_mov_b32 s36, gfx_callee@abs32@lo
; GISEL-NEXT:    s_mov_b32 s37, gfx_callee@abs32@hi
; GISEL-NEXT:    v_swap_b32 v0, v1
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    s_xor_b32 exec_lo, s0, -1
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v0, off, s32
; GISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; GISEL-NEXT:    scratch_load_b32 v2, off, s32 offset:8
; GISEL-NEXT:    scratch_load_b32 v3, off, s32 offset:12
; GISEL-NEXT:    scratch_load_b32 v4, off, s32 offset:16
; GISEL-NEXT:    scratch_load_b32 v5, off, s32 offset:20
; GISEL-NEXT:    scratch_load_b32 v6, off, s32 offset:24
; GISEL-NEXT:    scratch_load_b32 v7, off, s32 offset:28
; GISEL-NEXT:    scratch_load_b32 v8, off, s32 offset:32
; GISEL-NEXT:    scratch_load_b32 v9, off, s32 offset:36
; GISEL-NEXT:    scratch_load_b32 v10, off, s32 offset:40
; GISEL-NEXT:    scratch_load_b32 v11, off, s32 offset:44
; GISEL-NEXT:    scratch_load_b32 v12, off, s32 offset:48
; GISEL-NEXT:    scratch_load_b32 v13, off, s32 offset:52
; GISEL-NEXT:    scratch_load_b32 v14, off, s32 offset:56
; GISEL-NEXT:    scratch_load_b32 v15, off, s32 offset:60
; GISEL-NEXT:    scratch_load_b32 v16, off, s32 offset:64
; GISEL-NEXT:    scratch_load_b32 v17, off, s32 offset:68
; GISEL-NEXT:    scratch_load_b32 v18, off, s32 offset:72
; GISEL-NEXT:    scratch_load_b32 v19, off, s32 offset:76
; GISEL-NEXT:    scratch_load_b32 v20, off, s32 offset:80
; GISEL-NEXT:    scratch_load_b32 v21, off, s32 offset:84
; GISEL-NEXT:    scratch_load_b32 v22, off, s32 offset:88
; GISEL-NEXT:    scratch_load_b32 v23, off, s32 offset:92
; GISEL-NEXT:    scratch_load_b32 v24, off, s32 offset:96
; GISEL-NEXT:    scratch_load_b32 v25, off, s32 offset:100
; GISEL-NEXT:    scratch_load_b32 v26, off, s32 offset:104
; GISEL-NEXT:    scratch_load_b32 v27, off, s32 offset:108
; GISEL-NEXT:    scratch_load_b32 v28, off, s32 offset:112
; GISEL-NEXT:    scratch_load_b32 v29, off, s32 offset:116
; GISEL-NEXT:    scratch_load_b32 v30, off, s32 offset:120
; GISEL-NEXT:    scratch_load_b32 v31, off, s32 offset:124
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v32, off, s32 offset:128
; GISEL-NEXT:    scratch_load_b32 v33, off, s32 offset:132
; GISEL-NEXT:    scratch_load_b32 v34, off, s32 offset:136
; GISEL-NEXT:    scratch_load_b32 v35, off, s32 offset:140
; GISEL-NEXT:    scratch_load_b32 v36, off, s32 offset:144
; GISEL-NEXT:    scratch_load_b32 v37, off, s32 offset:148
; GISEL-NEXT:    scratch_load_b32 v38, off, s32 offset:152
; GISEL-NEXT:    scratch_load_b32 v39, off, s32 offset:156
; GISEL-NEXT:    scratch_load_b32 v48, off, s32 offset:160
; GISEL-NEXT:    scratch_load_b32 v49, off, s32 offset:164
; GISEL-NEXT:    scratch_load_b32 v50, off, s32 offset:168
; GISEL-NEXT:    scratch_load_b32 v51, off, s32 offset:172
; GISEL-NEXT:    scratch_load_b32 v52, off, s32 offset:176
; GISEL-NEXT:    scratch_load_b32 v53, off, s32 offset:180
; GISEL-NEXT:    scratch_load_b32 v54, off, s32 offset:184
; GISEL-NEXT:    scratch_load_b32 v55, off, s32 offset:188
; GISEL-NEXT:    scratch_load_b32 v64, off, s32 offset:192
; GISEL-NEXT:    scratch_load_b32 v65, off, s32 offset:196
; GISEL-NEXT:    scratch_load_b32 v66, off, s32 offset:200
; GISEL-NEXT:    scratch_load_b32 v67, off, s32 offset:204
; GISEL-NEXT:    scratch_load_b32 v68, off, s32 offset:208
; GISEL-NEXT:    scratch_load_b32 v69, off, s32 offset:212
; GISEL-NEXT:    scratch_load_b32 v70, off, s32 offset:216
; GISEL-NEXT:    scratch_load_b32 v71, off, s32 offset:220
; GISEL-NEXT:    scratch_load_b32 v80, off, s32 offset:224
; GISEL-NEXT:    scratch_load_b32 v81, off, s32 offset:228
; GISEL-NEXT:    scratch_load_b32 v82, off, s32 offset:232
; GISEL-NEXT:    scratch_load_b32 v83, off, s32 offset:236
; GISEL-NEXT:    scratch_load_b32 v84, off, s32 offset:240
; GISEL-NEXT:    scratch_load_b32 v85, off, s32 offset:244
; GISEL-NEXT:    scratch_load_b32 v86, off, s32 offset:248
; GISEL-NEXT:    scratch_load_b32 v87, off, s32 offset:252
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v96, off, s32 offset:256
; GISEL-NEXT:    scratch_load_b32 v97, off, s32 offset:260
; GISEL-NEXT:    scratch_load_b32 v98, off, s32 offset:264
; GISEL-NEXT:    scratch_load_b32 v99, off, s32 offset:268
; GISEL-NEXT:    scratch_load_b32 v100, off, s32 offset:272
; GISEL-NEXT:    scratch_load_b32 v101, off, s32 offset:276
; GISEL-NEXT:    scratch_load_b32 v102, off, s32 offset:280
; GISEL-NEXT:    scratch_load_b32 v103, off, s32 offset:284
; GISEL-NEXT:    scratch_load_b32 v112, off, s32 offset:288
; GISEL-NEXT:    scratch_load_b32 v113, off, s32 offset:292
; GISEL-NEXT:    scratch_load_b32 v114, off, s32 offset:296
; GISEL-NEXT:    scratch_load_b32 v115, off, s32 offset:300
; GISEL-NEXT:    scratch_load_b32 v116, off, s32 offset:304
; GISEL-NEXT:    scratch_load_b32 v117, off, s32 offset:308
; GISEL-NEXT:    scratch_load_b32 v118, off, s32 offset:312
; GISEL-NEXT:    scratch_load_b32 v119, off, s32 offset:316
; GISEL-NEXT:    scratch_load_b32 v128, off, s32 offset:320
; GISEL-NEXT:    scratch_load_b32 v129, off, s32 offset:324
; GISEL-NEXT:    scratch_load_b32 v130, off, s32 offset:328
; GISEL-NEXT:    scratch_load_b32 v131, off, s32 offset:332
; GISEL-NEXT:    scratch_load_b32 v132, off, s32 offset:336
; GISEL-NEXT:    scratch_load_b32 v133, off, s32 offset:340
; GISEL-NEXT:    scratch_load_b32 v134, off, s32 offset:344
; GISEL-NEXT:    scratch_load_b32 v135, off, s32 offset:348
; GISEL-NEXT:    scratch_load_b32 v144, off, s32 offset:352
; GISEL-NEXT:    scratch_load_b32 v145, off, s32 offset:356
; GISEL-NEXT:    scratch_load_b32 v146, off, s32 offset:360
; GISEL-NEXT:    scratch_load_b32 v147, off, s32 offset:364
; GISEL-NEXT:    scratch_load_b32 v148, off, s32 offset:368
; GISEL-NEXT:    scratch_load_b32 v149, off, s32 offset:372
; GISEL-NEXT:    scratch_load_b32 v150, off, s32 offset:376
; GISEL-NEXT:    scratch_load_b32 v151, off, s32 offset:380
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v160, off, s32 offset:384
; GISEL-NEXT:    scratch_load_b32 v161, off, s32 offset:388
; GISEL-NEXT:    scratch_load_b32 v162, off, s32 offset:392
; GISEL-NEXT:    scratch_load_b32 v163, off, s32 offset:396
; GISEL-NEXT:    scratch_load_b32 v164, off, s32 offset:400
; GISEL-NEXT:    scratch_load_b32 v165, off, s32 offset:404
; GISEL-NEXT:    scratch_load_b32 v166, off, s32 offset:408
; GISEL-NEXT:    scratch_load_b32 v167, off, s32 offset:412
; GISEL-NEXT:    scratch_load_b32 v176, off, s32 offset:416
; GISEL-NEXT:    scratch_load_b32 v177, off, s32 offset:420
; GISEL-NEXT:    scratch_load_b32 v178, off, s32 offset:424
; GISEL-NEXT:    scratch_load_b32 v179, off, s32 offset:428
; GISEL-NEXT:    scratch_load_b32 v180, off, s32 offset:432
; GISEL-NEXT:    scratch_load_b32 v181, off, s32 offset:436
; GISEL-NEXT:    scratch_load_b32 v182, off, s32 offset:440
; GISEL-NEXT:    scratch_load_b32 v183, off, s32 offset:444
; GISEL-NEXT:    scratch_load_b32 v192, off, s32 offset:448
; GISEL-NEXT:    scratch_load_b32 v193, off, s32 offset:452
; GISEL-NEXT:    scratch_load_b32 v194, off, s32 offset:456
; GISEL-NEXT:    scratch_load_b32 v195, off, s32 offset:460
; GISEL-NEXT:    scratch_load_b32 v196, off, s32 offset:464
; GISEL-NEXT:    scratch_load_b32 v197, off, s32 offset:468
; GISEL-NEXT:    scratch_load_b32 v198, off, s32 offset:472
; GISEL-NEXT:    scratch_load_b32 v199, off, s32 offset:476
; GISEL-NEXT:    scratch_load_b32 v208, off, s32 offset:480
; GISEL-NEXT:    scratch_load_b32 v209, off, s32 offset:484
; GISEL-NEXT:    scratch_load_b32 v210, off, s32 offset:488
; GISEL-NEXT:    scratch_load_b32 v211, off, s32 offset:492
; GISEL-NEXT:    scratch_load_b32 v212, off, s32 offset:496
; GISEL-NEXT:    scratch_load_b32 v213, off, s32 offset:500
; GISEL-NEXT:    scratch_load_b32 v214, off, s32 offset:504
; GISEL-NEXT:    scratch_load_b32 v215, off, s32 offset:508
; GISEL-NEXT:    s_clause 0xf ; 64-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v224, off, s32 offset:512
; GISEL-NEXT:    scratch_load_b32 v225, off, s32 offset:516
; GISEL-NEXT:    scratch_load_b32 v226, off, s32 offset:520
; GISEL-NEXT:    scratch_load_b32 v227, off, s32 offset:524
; GISEL-NEXT:    scratch_load_b32 v228, off, s32 offset:528
; GISEL-NEXT:    scratch_load_b32 v229, off, s32 offset:532
; GISEL-NEXT:    scratch_load_b32 v230, off, s32 offset:536
; GISEL-NEXT:    scratch_load_b32 v231, off, s32 offset:540
; GISEL-NEXT:    scratch_load_b32 v240, off, s32 offset:544
; GISEL-NEXT:    scratch_load_b32 v241, off, s32 offset:548
; GISEL-NEXT:    scratch_load_b32 v242, off, s32 offset:552
; GISEL-NEXT:    scratch_load_b32 v243, off, s32 offset:556
; GISEL-NEXT:    scratch_load_b32 v244, off, s32 offset:560
; GISEL-NEXT:    scratch_load_b32 v245, off, s32 offset:564
; GISEL-NEXT:    scratch_load_b32 v246, off, s32 offset:568
; GISEL-NEXT:    scratch_load_b32 v247, off, s32 offset:572
; GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GISEL-NEXT:    s_setpc_b64 s[36:37]
;
; DAGISEL64-LABEL: tail_call_gfx_from_whole_wave:
; DAGISEL64:       ; %bb.0:
; DAGISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL64-NEXT:    s_wait_expcnt 0x0
; DAGISEL64-NEXT:    s_wait_samplecnt 0x0
; DAGISEL64-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL64-NEXT:    s_wait_kmcnt 0x0
; DAGISEL64-NEXT:    s_xor_saveexec_b64 s[0:1], -1
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v0, s32
; DAGISEL64-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; DAGISEL64-NEXT:    scratch_store_b32 off, v2, s32 offset:8
; DAGISEL64-NEXT:    scratch_store_b32 off, v3, s32 offset:12
; DAGISEL64-NEXT:    scratch_store_b32 off, v4, s32 offset:16
; DAGISEL64-NEXT:    scratch_store_b32 off, v5, s32 offset:20
; DAGISEL64-NEXT:    scratch_store_b32 off, v6, s32 offset:24
; DAGISEL64-NEXT:    scratch_store_b32 off, v7, s32 offset:28
; DAGISEL64-NEXT:    scratch_store_b32 off, v8, s32 offset:32
; DAGISEL64-NEXT:    scratch_store_b32 off, v9, s32 offset:36
; DAGISEL64-NEXT:    scratch_store_b32 off, v10, s32 offset:40
; DAGISEL64-NEXT:    scratch_store_b32 off, v11, s32 offset:44
; DAGISEL64-NEXT:    scratch_store_b32 off, v12, s32 offset:48
; DAGISEL64-NEXT:    scratch_store_b32 off, v13, s32 offset:52
; DAGISEL64-NEXT:    scratch_store_b32 off, v14, s32 offset:56
; DAGISEL64-NEXT:    scratch_store_b32 off, v15, s32 offset:60
; DAGISEL64-NEXT:    scratch_store_b32 off, v16, s32 offset:64
; DAGISEL64-NEXT:    scratch_store_b32 off, v17, s32 offset:68
; DAGISEL64-NEXT:    scratch_store_b32 off, v18, s32 offset:72
; DAGISEL64-NEXT:    scratch_store_b32 off, v19, s32 offset:76
; DAGISEL64-NEXT:    scratch_store_b32 off, v20, s32 offset:80
; DAGISEL64-NEXT:    scratch_store_b32 off, v21, s32 offset:84
; DAGISEL64-NEXT:    scratch_store_b32 off, v22, s32 offset:88
; DAGISEL64-NEXT:    scratch_store_b32 off, v23, s32 offset:92
; DAGISEL64-NEXT:    scratch_store_b32 off, v24, s32 offset:96
; DAGISEL64-NEXT:    scratch_store_b32 off, v25, s32 offset:100
; DAGISEL64-NEXT:    scratch_store_b32 off, v26, s32 offset:104
; DAGISEL64-NEXT:    scratch_store_b32 off, v27, s32 offset:108
; DAGISEL64-NEXT:    scratch_store_b32 off, v28, s32 offset:112
; DAGISEL64-NEXT:    scratch_store_b32 off, v29, s32 offset:116
; DAGISEL64-NEXT:    scratch_store_b32 off, v30, s32 offset:120
; DAGISEL64-NEXT:    scratch_store_b32 off, v31, s32 offset:124
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v32, s32 offset:128
; DAGISEL64-NEXT:    scratch_store_b32 off, v33, s32 offset:132
; DAGISEL64-NEXT:    scratch_store_b32 off, v34, s32 offset:136
; DAGISEL64-NEXT:    scratch_store_b32 off, v35, s32 offset:140
; DAGISEL64-NEXT:    scratch_store_b32 off, v36, s32 offset:144
; DAGISEL64-NEXT:    scratch_store_b32 off, v37, s32 offset:148
; DAGISEL64-NEXT:    scratch_store_b32 off, v38, s32 offset:152
; DAGISEL64-NEXT:    scratch_store_b32 off, v39, s32 offset:156
; DAGISEL64-NEXT:    scratch_store_b32 off, v48, s32 offset:160
; DAGISEL64-NEXT:    scratch_store_b32 off, v49, s32 offset:164
; DAGISEL64-NEXT:    scratch_store_b32 off, v50, s32 offset:168
; DAGISEL64-NEXT:    scratch_store_b32 off, v51, s32 offset:172
; DAGISEL64-NEXT:    scratch_store_b32 off, v52, s32 offset:176
; DAGISEL64-NEXT:    scratch_store_b32 off, v53, s32 offset:180
; DAGISEL64-NEXT:    scratch_store_b32 off, v54, s32 offset:184
; DAGISEL64-NEXT:    scratch_store_b32 off, v55, s32 offset:188
; DAGISEL64-NEXT:    scratch_store_b32 off, v64, s32 offset:192
; DAGISEL64-NEXT:    scratch_store_b32 off, v65, s32 offset:196
; DAGISEL64-NEXT:    scratch_store_b32 off, v66, s32 offset:200
; DAGISEL64-NEXT:    scratch_store_b32 off, v67, s32 offset:204
; DAGISEL64-NEXT:    scratch_store_b32 off, v68, s32 offset:208
; DAGISEL64-NEXT:    scratch_store_b32 off, v69, s32 offset:212
; DAGISEL64-NEXT:    scratch_store_b32 off, v70, s32 offset:216
; DAGISEL64-NEXT:    scratch_store_b32 off, v71, s32 offset:220
; DAGISEL64-NEXT:    scratch_store_b32 off, v80, s32 offset:224
; DAGISEL64-NEXT:    scratch_store_b32 off, v81, s32 offset:228
; DAGISEL64-NEXT:    scratch_store_b32 off, v82, s32 offset:232
; DAGISEL64-NEXT:    scratch_store_b32 off, v83, s32 offset:236
; DAGISEL64-NEXT:    scratch_store_b32 off, v84, s32 offset:240
; DAGISEL64-NEXT:    scratch_store_b32 off, v85, s32 offset:244
; DAGISEL64-NEXT:    scratch_store_b32 off, v86, s32 offset:248
; DAGISEL64-NEXT:    scratch_store_b32 off, v87, s32 offset:252
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v96, s32 offset:256
; DAGISEL64-NEXT:    scratch_store_b32 off, v97, s32 offset:260
; DAGISEL64-NEXT:    scratch_store_b32 off, v98, s32 offset:264
; DAGISEL64-NEXT:    scratch_store_b32 off, v99, s32 offset:268
; DAGISEL64-NEXT:    scratch_store_b32 off, v100, s32 offset:272
; DAGISEL64-NEXT:    scratch_store_b32 off, v101, s32 offset:276
; DAGISEL64-NEXT:    scratch_store_b32 off, v102, s32 offset:280
; DAGISEL64-NEXT:    scratch_store_b32 off, v103, s32 offset:284
; DAGISEL64-NEXT:    scratch_store_b32 off, v112, s32 offset:288
; DAGISEL64-NEXT:    scratch_store_b32 off, v113, s32 offset:292
; DAGISEL64-NEXT:    scratch_store_b32 off, v114, s32 offset:296
; DAGISEL64-NEXT:    scratch_store_b32 off, v115, s32 offset:300
; DAGISEL64-NEXT:    scratch_store_b32 off, v116, s32 offset:304
; DAGISEL64-NEXT:    scratch_store_b32 off, v117, s32 offset:308
; DAGISEL64-NEXT:    scratch_store_b32 off, v118, s32 offset:312
; DAGISEL64-NEXT:    scratch_store_b32 off, v119, s32 offset:316
; DAGISEL64-NEXT:    scratch_store_b32 off, v128, s32 offset:320
; DAGISEL64-NEXT:    scratch_store_b32 off, v129, s32 offset:324
; DAGISEL64-NEXT:    scratch_store_b32 off, v130, s32 offset:328
; DAGISEL64-NEXT:    scratch_store_b32 off, v131, s32 offset:332
; DAGISEL64-NEXT:    scratch_store_b32 off, v132, s32 offset:336
; DAGISEL64-NEXT:    scratch_store_b32 off, v133, s32 offset:340
; DAGISEL64-NEXT:    scratch_store_b32 off, v134, s32 offset:344
; DAGISEL64-NEXT:    scratch_store_b32 off, v135, s32 offset:348
; DAGISEL64-NEXT:    scratch_store_b32 off, v144, s32 offset:352
; DAGISEL64-NEXT:    scratch_store_b32 off, v145, s32 offset:356
; DAGISEL64-NEXT:    scratch_store_b32 off, v146, s32 offset:360
; DAGISEL64-NEXT:    scratch_store_b32 off, v147, s32 offset:364
; DAGISEL64-NEXT:    scratch_store_b32 off, v148, s32 offset:368
; DAGISEL64-NEXT:    scratch_store_b32 off, v149, s32 offset:372
; DAGISEL64-NEXT:    scratch_store_b32 off, v150, s32 offset:376
; DAGISEL64-NEXT:    scratch_store_b32 off, v151, s32 offset:380
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v160, s32 offset:384
; DAGISEL64-NEXT:    scratch_store_b32 off, v161, s32 offset:388
; DAGISEL64-NEXT:    scratch_store_b32 off, v162, s32 offset:392
; DAGISEL64-NEXT:    scratch_store_b32 off, v163, s32 offset:396
; DAGISEL64-NEXT:    scratch_store_b32 off, v164, s32 offset:400
; DAGISEL64-NEXT:    scratch_store_b32 off, v165, s32 offset:404
; DAGISEL64-NEXT:    scratch_store_b32 off, v166, s32 offset:408
; DAGISEL64-NEXT:    scratch_store_b32 off, v167, s32 offset:412
; DAGISEL64-NEXT:    scratch_store_b32 off, v176, s32 offset:416
; DAGISEL64-NEXT:    scratch_store_b32 off, v177, s32 offset:420
; DAGISEL64-NEXT:    scratch_store_b32 off, v178, s32 offset:424
; DAGISEL64-NEXT:    scratch_store_b32 off, v179, s32 offset:428
; DAGISEL64-NEXT:    scratch_store_b32 off, v180, s32 offset:432
; DAGISEL64-NEXT:    scratch_store_b32 off, v181, s32 offset:436
; DAGISEL64-NEXT:    scratch_store_b32 off, v182, s32 offset:440
; DAGISEL64-NEXT:    scratch_store_b32 off, v183, s32 offset:444
; DAGISEL64-NEXT:    scratch_store_b32 off, v192, s32 offset:448
; DAGISEL64-NEXT:    scratch_store_b32 off, v193, s32 offset:452
; DAGISEL64-NEXT:    scratch_store_b32 off, v194, s32 offset:456
; DAGISEL64-NEXT:    scratch_store_b32 off, v195, s32 offset:460
; DAGISEL64-NEXT:    scratch_store_b32 off, v196, s32 offset:464
; DAGISEL64-NEXT:    scratch_store_b32 off, v197, s32 offset:468
; DAGISEL64-NEXT:    scratch_store_b32 off, v198, s32 offset:472
; DAGISEL64-NEXT:    scratch_store_b32 off, v199, s32 offset:476
; DAGISEL64-NEXT:    scratch_store_b32 off, v208, s32 offset:480
; DAGISEL64-NEXT:    scratch_store_b32 off, v209, s32 offset:484
; DAGISEL64-NEXT:    scratch_store_b32 off, v210, s32 offset:488
; DAGISEL64-NEXT:    scratch_store_b32 off, v211, s32 offset:492
; DAGISEL64-NEXT:    scratch_store_b32 off, v212, s32 offset:496
; DAGISEL64-NEXT:    scratch_store_b32 off, v213, s32 offset:500
; DAGISEL64-NEXT:    scratch_store_b32 off, v214, s32 offset:504
; DAGISEL64-NEXT:    scratch_store_b32 off, v215, s32 offset:508
; DAGISEL64-NEXT:    s_clause 0xf ; 64-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v224, s32 offset:512
; DAGISEL64-NEXT:    scratch_store_b32 off, v225, s32 offset:516
; DAGISEL64-NEXT:    scratch_store_b32 off, v226, s32 offset:520
; DAGISEL64-NEXT:    scratch_store_b32 off, v227, s32 offset:524
; DAGISEL64-NEXT:    scratch_store_b32 off, v228, s32 offset:528
; DAGISEL64-NEXT:    scratch_store_b32 off, v229, s32 offset:532
; DAGISEL64-NEXT:    scratch_store_b32 off, v230, s32 offset:536
; DAGISEL64-NEXT:    scratch_store_b32 off, v231, s32 offset:540
; DAGISEL64-NEXT:    scratch_store_b32 off, v240, s32 offset:544
; DAGISEL64-NEXT:    scratch_store_b32 off, v241, s32 offset:548
; DAGISEL64-NEXT:    scratch_store_b32 off, v242, s32 offset:552
; DAGISEL64-NEXT:    scratch_store_b32 off, v243, s32 offset:556
; DAGISEL64-NEXT:    scratch_store_b32 off, v244, s32 offset:560
; DAGISEL64-NEXT:    scratch_store_b32 off, v245, s32 offset:564
; DAGISEL64-NEXT:    scratch_store_b32 off, v246, s32 offset:568
; DAGISEL64-NEXT:    scratch_store_b32 off, v247, s32 offset:572
; DAGISEL64-NEXT:    s_mov_b64 exec, -1
; DAGISEL64-NEXT:    v_mov_b32_e32 v2, v0
; DAGISEL64-NEXT:    s_mov_b32 s37, gfx_callee@abs32@hi
; DAGISEL64-NEXT:    s_mov_b32 s36, gfx_callee@abs32@lo
; DAGISEL64-NEXT:    v_swap_b32 v0, v1
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    s_xor_b64 exec, s[0:1], -1
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v0, off, s32
; DAGISEL64-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; DAGISEL64-NEXT:    scratch_load_b32 v2, off, s32 offset:8
; DAGISEL64-NEXT:    scratch_load_b32 v3, off, s32 offset:12
; DAGISEL64-NEXT:    scratch_load_b32 v4, off, s32 offset:16
; DAGISEL64-NEXT:    scratch_load_b32 v5, off, s32 offset:20
; DAGISEL64-NEXT:    scratch_load_b32 v6, off, s32 offset:24
; DAGISEL64-NEXT:    scratch_load_b32 v7, off, s32 offset:28
; DAGISEL64-NEXT:    scratch_load_b32 v8, off, s32 offset:32
; DAGISEL64-NEXT:    scratch_load_b32 v9, off, s32 offset:36
; DAGISEL64-NEXT:    scratch_load_b32 v10, off, s32 offset:40
; DAGISEL64-NEXT:    scratch_load_b32 v11, off, s32 offset:44
; DAGISEL64-NEXT:    scratch_load_b32 v12, off, s32 offset:48
; DAGISEL64-NEXT:    scratch_load_b32 v13, off, s32 offset:52
; DAGISEL64-NEXT:    scratch_load_b32 v14, off, s32 offset:56
; DAGISEL64-NEXT:    scratch_load_b32 v15, off, s32 offset:60
; DAGISEL64-NEXT:    scratch_load_b32 v16, off, s32 offset:64
; DAGISEL64-NEXT:    scratch_load_b32 v17, off, s32 offset:68
; DAGISEL64-NEXT:    scratch_load_b32 v18, off, s32 offset:72
; DAGISEL64-NEXT:    scratch_load_b32 v19, off, s32 offset:76
; DAGISEL64-NEXT:    scratch_load_b32 v20, off, s32 offset:80
; DAGISEL64-NEXT:    scratch_load_b32 v21, off, s32 offset:84
; DAGISEL64-NEXT:    scratch_load_b32 v22, off, s32 offset:88
; DAGISEL64-NEXT:    scratch_load_b32 v23, off, s32 offset:92
; DAGISEL64-NEXT:    scratch_load_b32 v24, off, s32 offset:96
; DAGISEL64-NEXT:    scratch_load_b32 v25, off, s32 offset:100
; DAGISEL64-NEXT:    scratch_load_b32 v26, off, s32 offset:104
; DAGISEL64-NEXT:    scratch_load_b32 v27, off, s32 offset:108
; DAGISEL64-NEXT:    scratch_load_b32 v28, off, s32 offset:112
; DAGISEL64-NEXT:    scratch_load_b32 v29, off, s32 offset:116
; DAGISEL64-NEXT:    scratch_load_b32 v30, off, s32 offset:120
; DAGISEL64-NEXT:    scratch_load_b32 v31, off, s32 offset:124
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v32, off, s32 offset:128
; DAGISEL64-NEXT:    scratch_load_b32 v33, off, s32 offset:132
; DAGISEL64-NEXT:    scratch_load_b32 v34, off, s32 offset:136
; DAGISEL64-NEXT:    scratch_load_b32 v35, off, s32 offset:140
; DAGISEL64-NEXT:    scratch_load_b32 v36, off, s32 offset:144
; DAGISEL64-NEXT:    scratch_load_b32 v37, off, s32 offset:148
; DAGISEL64-NEXT:    scratch_load_b32 v38, off, s32 offset:152
; DAGISEL64-NEXT:    scratch_load_b32 v39, off, s32 offset:156
; DAGISEL64-NEXT:    scratch_load_b32 v48, off, s32 offset:160
; DAGISEL64-NEXT:    scratch_load_b32 v49, off, s32 offset:164
; DAGISEL64-NEXT:    scratch_load_b32 v50, off, s32 offset:168
; DAGISEL64-NEXT:    scratch_load_b32 v51, off, s32 offset:172
; DAGISEL64-NEXT:    scratch_load_b32 v52, off, s32 offset:176
; DAGISEL64-NEXT:    scratch_load_b32 v53, off, s32 offset:180
; DAGISEL64-NEXT:    scratch_load_b32 v54, off, s32 offset:184
; DAGISEL64-NEXT:    scratch_load_b32 v55, off, s32 offset:188
; DAGISEL64-NEXT:    scratch_load_b32 v64, off, s32 offset:192
; DAGISEL64-NEXT:    scratch_load_b32 v65, off, s32 offset:196
; DAGISEL64-NEXT:    scratch_load_b32 v66, off, s32 offset:200
; DAGISEL64-NEXT:    scratch_load_b32 v67, off, s32 offset:204
; DAGISEL64-NEXT:    scratch_load_b32 v68, off, s32 offset:208
; DAGISEL64-NEXT:    scratch_load_b32 v69, off, s32 offset:212
; DAGISEL64-NEXT:    scratch_load_b32 v70, off, s32 offset:216
; DAGISEL64-NEXT:    scratch_load_b32 v71, off, s32 offset:220
; DAGISEL64-NEXT:    scratch_load_b32 v80, off, s32 offset:224
; DAGISEL64-NEXT:    scratch_load_b32 v81, off, s32 offset:228
; DAGISEL64-NEXT:    scratch_load_b32 v82, off, s32 offset:232
; DAGISEL64-NEXT:    scratch_load_b32 v83, off, s32 offset:236
; DAGISEL64-NEXT:    scratch_load_b32 v84, off, s32 offset:240
; DAGISEL64-NEXT:    scratch_load_b32 v85, off, s32 offset:244
; DAGISEL64-NEXT:    scratch_load_b32 v86, off, s32 offset:248
; DAGISEL64-NEXT:    scratch_load_b32 v87, off, s32 offset:252
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v96, off, s32 offset:256
; DAGISEL64-NEXT:    scratch_load_b32 v97, off, s32 offset:260
; DAGISEL64-NEXT:    scratch_load_b32 v98, off, s32 offset:264
; DAGISEL64-NEXT:    scratch_load_b32 v99, off, s32 offset:268
; DAGISEL64-NEXT:    scratch_load_b32 v100, off, s32 offset:272
; DAGISEL64-NEXT:    scratch_load_b32 v101, off, s32 offset:276
; DAGISEL64-NEXT:    scratch_load_b32 v102, off, s32 offset:280
; DAGISEL64-NEXT:    scratch_load_b32 v103, off, s32 offset:284
; DAGISEL64-NEXT:    scratch_load_b32 v112, off, s32 offset:288
; DAGISEL64-NEXT:    scratch_load_b32 v113, off, s32 offset:292
; DAGISEL64-NEXT:    scratch_load_b32 v114, off, s32 offset:296
; DAGISEL64-NEXT:    scratch_load_b32 v115, off, s32 offset:300
; DAGISEL64-NEXT:    scratch_load_b32 v116, off, s32 offset:304
; DAGISEL64-NEXT:    scratch_load_b32 v117, off, s32 offset:308
; DAGISEL64-NEXT:    scratch_load_b32 v118, off, s32 offset:312
; DAGISEL64-NEXT:    scratch_load_b32 v119, off, s32 offset:316
; DAGISEL64-NEXT:    scratch_load_b32 v128, off, s32 offset:320
; DAGISEL64-NEXT:    scratch_load_b32 v129, off, s32 offset:324
; DAGISEL64-NEXT:    scratch_load_b32 v130, off, s32 offset:328
; DAGISEL64-NEXT:    scratch_load_b32 v131, off, s32 offset:332
; DAGISEL64-NEXT:    scratch_load_b32 v132, off, s32 offset:336
; DAGISEL64-NEXT:    scratch_load_b32 v133, off, s32 offset:340
; DAGISEL64-NEXT:    scratch_load_b32 v134, off, s32 offset:344
; DAGISEL64-NEXT:    scratch_load_b32 v135, off, s32 offset:348
; DAGISEL64-NEXT:    scratch_load_b32 v144, off, s32 offset:352
; DAGISEL64-NEXT:    scratch_load_b32 v145, off, s32 offset:356
; DAGISEL64-NEXT:    scratch_load_b32 v146, off, s32 offset:360
; DAGISEL64-NEXT:    scratch_load_b32 v147, off, s32 offset:364
; DAGISEL64-NEXT:    scratch_load_b32 v148, off, s32 offset:368
; DAGISEL64-NEXT:    scratch_load_b32 v149, off, s32 offset:372
; DAGISEL64-NEXT:    scratch_load_b32 v150, off, s32 offset:376
; DAGISEL64-NEXT:    scratch_load_b32 v151, off, s32 offset:380
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v160, off, s32 offset:384
; DAGISEL64-NEXT:    scratch_load_b32 v161, off, s32 offset:388
; DAGISEL64-NEXT:    scratch_load_b32 v162, off, s32 offset:392
; DAGISEL64-NEXT:    scratch_load_b32 v163, off, s32 offset:396
; DAGISEL64-NEXT:    scratch_load_b32 v164, off, s32 offset:400
; DAGISEL64-NEXT:    scratch_load_b32 v165, off, s32 offset:404
; DAGISEL64-NEXT:    scratch_load_b32 v166, off, s32 offset:408
; DAGISEL64-NEXT:    scratch_load_b32 v167, off, s32 offset:412
; DAGISEL64-NEXT:    scratch_load_b32 v176, off, s32 offset:416
; DAGISEL64-NEXT:    scratch_load_b32 v177, off, s32 offset:420
; DAGISEL64-NEXT:    scratch_load_b32 v178, off, s32 offset:424
; DAGISEL64-NEXT:    scratch_load_b32 v179, off, s32 offset:428
; DAGISEL64-NEXT:    scratch_load_b32 v180, off, s32 offset:432
; DAGISEL64-NEXT:    scratch_load_b32 v181, off, s32 offset:436
; DAGISEL64-NEXT:    scratch_load_b32 v182, off, s32 offset:440
; DAGISEL64-NEXT:    scratch_load_b32 v183, off, s32 offset:444
; DAGISEL64-NEXT:    scratch_load_b32 v192, off, s32 offset:448
; DAGISEL64-NEXT:    scratch_load_b32 v193, off, s32 offset:452
; DAGISEL64-NEXT:    scratch_load_b32 v194, off, s32 offset:456
; DAGISEL64-NEXT:    scratch_load_b32 v195, off, s32 offset:460
; DAGISEL64-NEXT:    scratch_load_b32 v196, off, s32 offset:464
; DAGISEL64-NEXT:    scratch_load_b32 v197, off, s32 offset:468
; DAGISEL64-NEXT:    scratch_load_b32 v198, off, s32 offset:472
; DAGISEL64-NEXT:    scratch_load_b32 v199, off, s32 offset:476
; DAGISEL64-NEXT:    scratch_load_b32 v208, off, s32 offset:480
; DAGISEL64-NEXT:    scratch_load_b32 v209, off, s32 offset:484
; DAGISEL64-NEXT:    scratch_load_b32 v210, off, s32 offset:488
; DAGISEL64-NEXT:    scratch_load_b32 v211, off, s32 offset:492
; DAGISEL64-NEXT:    scratch_load_b32 v212, off, s32 offset:496
; DAGISEL64-NEXT:    scratch_load_b32 v213, off, s32 offset:500
; DAGISEL64-NEXT:    scratch_load_b32 v214, off, s32 offset:504
; DAGISEL64-NEXT:    scratch_load_b32 v215, off, s32 offset:508
; DAGISEL64-NEXT:    s_clause 0xf ; 64-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v224, off, s32 offset:512
; DAGISEL64-NEXT:    scratch_load_b32 v225, off, s32 offset:516
; DAGISEL64-NEXT:    scratch_load_b32 v226, off, s32 offset:520
; DAGISEL64-NEXT:    scratch_load_b32 v227, off, s32 offset:524
; DAGISEL64-NEXT:    scratch_load_b32 v228, off, s32 offset:528
; DAGISEL64-NEXT:    scratch_load_b32 v229, off, s32 offset:532
; DAGISEL64-NEXT:    scratch_load_b32 v230, off, s32 offset:536
; DAGISEL64-NEXT:    scratch_load_b32 v231, off, s32 offset:540
; DAGISEL64-NEXT:    scratch_load_b32 v240, off, s32 offset:544
; DAGISEL64-NEXT:    scratch_load_b32 v241, off, s32 offset:548
; DAGISEL64-NEXT:    scratch_load_b32 v242, off, s32 offset:552
; DAGISEL64-NEXT:    scratch_load_b32 v243, off, s32 offset:556
; DAGISEL64-NEXT:    scratch_load_b32 v244, off, s32 offset:560
; DAGISEL64-NEXT:    scratch_load_b32 v245, off, s32 offset:564
; DAGISEL64-NEXT:    scratch_load_b32 v246, off, s32 offset:568
; DAGISEL64-NEXT:    scratch_load_b32 v247, off, s32 offset:572
; DAGISEL64-NEXT:    s_mov_b64 exec, s[0:1]
; DAGISEL64-NEXT:    s_setpc_b64 s[36:37]
;
; GISEL64-LABEL: tail_call_gfx_from_whole_wave:
; GISEL64:       ; %bb.0:
; GISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL64-NEXT:    s_wait_expcnt 0x0
; GISEL64-NEXT:    s_wait_samplecnt 0x0
; GISEL64-NEXT:    s_wait_bvhcnt 0x0
; GISEL64-NEXT:    s_wait_kmcnt 0x0
; GISEL64-NEXT:    s_xor_saveexec_b64 s[0:1], -1
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v0, s32
; GISEL64-NEXT:    scratch_store_b32 off, v1, s32 offset:4
; GISEL64-NEXT:    scratch_store_b32 off, v2, s32 offset:8
; GISEL64-NEXT:    scratch_store_b32 off, v3, s32 offset:12
; GISEL64-NEXT:    scratch_store_b32 off, v4, s32 offset:16
; GISEL64-NEXT:    scratch_store_b32 off, v5, s32 offset:20
; GISEL64-NEXT:    scratch_store_b32 off, v6, s32 offset:24
; GISEL64-NEXT:    scratch_store_b32 off, v7, s32 offset:28
; GISEL64-NEXT:    scratch_store_b32 off, v8, s32 offset:32
; GISEL64-NEXT:    scratch_store_b32 off, v9, s32 offset:36
; GISEL64-NEXT:    scratch_store_b32 off, v10, s32 offset:40
; GISEL64-NEXT:    scratch_store_b32 off, v11, s32 offset:44
; GISEL64-NEXT:    scratch_store_b32 off, v12, s32 offset:48
; GISEL64-NEXT:    scratch_store_b32 off, v13, s32 offset:52
; GISEL64-NEXT:    scratch_store_b32 off, v14, s32 offset:56
; GISEL64-NEXT:    scratch_store_b32 off, v15, s32 offset:60
; GISEL64-NEXT:    scratch_store_b32 off, v16, s32 offset:64
; GISEL64-NEXT:    scratch_store_b32 off, v17, s32 offset:68
; GISEL64-NEXT:    scratch_store_b32 off, v18, s32 offset:72
; GISEL64-NEXT:    scratch_store_b32 off, v19, s32 offset:76
; GISEL64-NEXT:    scratch_store_b32 off, v20, s32 offset:80
; GISEL64-NEXT:    scratch_store_b32 off, v21, s32 offset:84
; GISEL64-NEXT:    scratch_store_b32 off, v22, s32 offset:88
; GISEL64-NEXT:    scratch_store_b32 off, v23, s32 offset:92
; GISEL64-NEXT:    scratch_store_b32 off, v24, s32 offset:96
; GISEL64-NEXT:    scratch_store_b32 off, v25, s32 offset:100
; GISEL64-NEXT:    scratch_store_b32 off, v26, s32 offset:104
; GISEL64-NEXT:    scratch_store_b32 off, v27, s32 offset:108
; GISEL64-NEXT:    scratch_store_b32 off, v28, s32 offset:112
; GISEL64-NEXT:    scratch_store_b32 off, v29, s32 offset:116
; GISEL64-NEXT:    scratch_store_b32 off, v30, s32 offset:120
; GISEL64-NEXT:    scratch_store_b32 off, v31, s32 offset:124
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v32, s32 offset:128
; GISEL64-NEXT:    scratch_store_b32 off, v33, s32 offset:132
; GISEL64-NEXT:    scratch_store_b32 off, v34, s32 offset:136
; GISEL64-NEXT:    scratch_store_b32 off, v35, s32 offset:140
; GISEL64-NEXT:    scratch_store_b32 off, v36, s32 offset:144
; GISEL64-NEXT:    scratch_store_b32 off, v37, s32 offset:148
; GISEL64-NEXT:    scratch_store_b32 off, v38, s32 offset:152
; GISEL64-NEXT:    scratch_store_b32 off, v39, s32 offset:156
; GISEL64-NEXT:    scratch_store_b32 off, v48, s32 offset:160
; GISEL64-NEXT:    scratch_store_b32 off, v49, s32 offset:164
; GISEL64-NEXT:    scratch_store_b32 off, v50, s32 offset:168
; GISEL64-NEXT:    scratch_store_b32 off, v51, s32 offset:172
; GISEL64-NEXT:    scratch_store_b32 off, v52, s32 offset:176
; GISEL64-NEXT:    scratch_store_b32 off, v53, s32 offset:180
; GISEL64-NEXT:    scratch_store_b32 off, v54, s32 offset:184
; GISEL64-NEXT:    scratch_store_b32 off, v55, s32 offset:188
; GISEL64-NEXT:    scratch_store_b32 off, v64, s32 offset:192
; GISEL64-NEXT:    scratch_store_b32 off, v65, s32 offset:196
; GISEL64-NEXT:    scratch_store_b32 off, v66, s32 offset:200
; GISEL64-NEXT:    scratch_store_b32 off, v67, s32 offset:204
; GISEL64-NEXT:    scratch_store_b32 off, v68, s32 offset:208
; GISEL64-NEXT:    scratch_store_b32 off, v69, s32 offset:212
; GISEL64-NEXT:    scratch_store_b32 off, v70, s32 offset:216
; GISEL64-NEXT:    scratch_store_b32 off, v71, s32 offset:220
; GISEL64-NEXT:    scratch_store_b32 off, v80, s32 offset:224
; GISEL64-NEXT:    scratch_store_b32 off, v81, s32 offset:228
; GISEL64-NEXT:    scratch_store_b32 off, v82, s32 offset:232
; GISEL64-NEXT:    scratch_store_b32 off, v83, s32 offset:236
; GISEL64-NEXT:    scratch_store_b32 off, v84, s32 offset:240
; GISEL64-NEXT:    scratch_store_b32 off, v85, s32 offset:244
; GISEL64-NEXT:    scratch_store_b32 off, v86, s32 offset:248
; GISEL64-NEXT:    scratch_store_b32 off, v87, s32 offset:252
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v96, s32 offset:256
; GISEL64-NEXT:    scratch_store_b32 off, v97, s32 offset:260
; GISEL64-NEXT:    scratch_store_b32 off, v98, s32 offset:264
; GISEL64-NEXT:    scratch_store_b32 off, v99, s32 offset:268
; GISEL64-NEXT:    scratch_store_b32 off, v100, s32 offset:272
; GISEL64-NEXT:    scratch_store_b32 off, v101, s32 offset:276
; GISEL64-NEXT:    scratch_store_b32 off, v102, s32 offset:280
; GISEL64-NEXT:    scratch_store_b32 off, v103, s32 offset:284
; GISEL64-NEXT:    scratch_store_b32 off, v112, s32 offset:288
; GISEL64-NEXT:    scratch_store_b32 off, v113, s32 offset:292
; GISEL64-NEXT:    scratch_store_b32 off, v114, s32 offset:296
; GISEL64-NEXT:    scratch_store_b32 off, v115, s32 offset:300
; GISEL64-NEXT:    scratch_store_b32 off, v116, s32 offset:304
; GISEL64-NEXT:    scratch_store_b32 off, v117, s32 offset:308
; GISEL64-NEXT:    scratch_store_b32 off, v118, s32 offset:312
; GISEL64-NEXT:    scratch_store_b32 off, v119, s32 offset:316
; GISEL64-NEXT:    scratch_store_b32 off, v128, s32 offset:320
; GISEL64-NEXT:    scratch_store_b32 off, v129, s32 offset:324
; GISEL64-NEXT:    scratch_store_b32 off, v130, s32 offset:328
; GISEL64-NEXT:    scratch_store_b32 off, v131, s32 offset:332
; GISEL64-NEXT:    scratch_store_b32 off, v132, s32 offset:336
; GISEL64-NEXT:    scratch_store_b32 off, v133, s32 offset:340
; GISEL64-NEXT:    scratch_store_b32 off, v134, s32 offset:344
; GISEL64-NEXT:    scratch_store_b32 off, v135, s32 offset:348
; GISEL64-NEXT:    scratch_store_b32 off, v144, s32 offset:352
; GISEL64-NEXT:    scratch_store_b32 off, v145, s32 offset:356
; GISEL64-NEXT:    scratch_store_b32 off, v146, s32 offset:360
; GISEL64-NEXT:    scratch_store_b32 off, v147, s32 offset:364
; GISEL64-NEXT:    scratch_store_b32 off, v148, s32 offset:368
; GISEL64-NEXT:    scratch_store_b32 off, v149, s32 offset:372
; GISEL64-NEXT:    scratch_store_b32 off, v150, s32 offset:376
; GISEL64-NEXT:    scratch_store_b32 off, v151, s32 offset:380
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v160, s32 offset:384
; GISEL64-NEXT:    scratch_store_b32 off, v161, s32 offset:388
; GISEL64-NEXT:    scratch_store_b32 off, v162, s32 offset:392
; GISEL64-NEXT:    scratch_store_b32 off, v163, s32 offset:396
; GISEL64-NEXT:    scratch_store_b32 off, v164, s32 offset:400
; GISEL64-NEXT:    scratch_store_b32 off, v165, s32 offset:404
; GISEL64-NEXT:    scratch_store_b32 off, v166, s32 offset:408
; GISEL64-NEXT:    scratch_store_b32 off, v167, s32 offset:412
; GISEL64-NEXT:    scratch_store_b32 off, v176, s32 offset:416
; GISEL64-NEXT:    scratch_store_b32 off, v177, s32 offset:420
; GISEL64-NEXT:    scratch_store_b32 off, v178, s32 offset:424
; GISEL64-NEXT:    scratch_store_b32 off, v179, s32 offset:428
; GISEL64-NEXT:    scratch_store_b32 off, v180, s32 offset:432
; GISEL64-NEXT:    scratch_store_b32 off, v181, s32 offset:436
; GISEL64-NEXT:    scratch_store_b32 off, v182, s32 offset:440
; GISEL64-NEXT:    scratch_store_b32 off, v183, s32 offset:444
; GISEL64-NEXT:    scratch_store_b32 off, v192, s32 offset:448
; GISEL64-NEXT:    scratch_store_b32 off, v193, s32 offset:452
; GISEL64-NEXT:    scratch_store_b32 off, v194, s32 offset:456
; GISEL64-NEXT:    scratch_store_b32 off, v195, s32 offset:460
; GISEL64-NEXT:    scratch_store_b32 off, v196, s32 offset:464
; GISEL64-NEXT:    scratch_store_b32 off, v197, s32 offset:468
; GISEL64-NEXT:    scratch_store_b32 off, v198, s32 offset:472
; GISEL64-NEXT:    scratch_store_b32 off, v199, s32 offset:476
; GISEL64-NEXT:    scratch_store_b32 off, v208, s32 offset:480
; GISEL64-NEXT:    scratch_store_b32 off, v209, s32 offset:484
; GISEL64-NEXT:    scratch_store_b32 off, v210, s32 offset:488
; GISEL64-NEXT:    scratch_store_b32 off, v211, s32 offset:492
; GISEL64-NEXT:    scratch_store_b32 off, v212, s32 offset:496
; GISEL64-NEXT:    scratch_store_b32 off, v213, s32 offset:500
; GISEL64-NEXT:    scratch_store_b32 off, v214, s32 offset:504
; GISEL64-NEXT:    scratch_store_b32 off, v215, s32 offset:508
; GISEL64-NEXT:    s_clause 0xf ; 64-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v224, s32 offset:512
; GISEL64-NEXT:    scratch_store_b32 off, v225, s32 offset:516
; GISEL64-NEXT:    scratch_store_b32 off, v226, s32 offset:520
; GISEL64-NEXT:    scratch_store_b32 off, v227, s32 offset:524
; GISEL64-NEXT:    scratch_store_b32 off, v228, s32 offset:528
; GISEL64-NEXT:    scratch_store_b32 off, v229, s32 offset:532
; GISEL64-NEXT:    scratch_store_b32 off, v230, s32 offset:536
; GISEL64-NEXT:    scratch_store_b32 off, v231, s32 offset:540
; GISEL64-NEXT:    scratch_store_b32 off, v240, s32 offset:544
; GISEL64-NEXT:    scratch_store_b32 off, v241, s32 offset:548
; GISEL64-NEXT:    scratch_store_b32 off, v242, s32 offset:552
; GISEL64-NEXT:    scratch_store_b32 off, v243, s32 offset:556
; GISEL64-NEXT:    scratch_store_b32 off, v244, s32 offset:560
; GISEL64-NEXT:    scratch_store_b32 off, v245, s32 offset:564
; GISEL64-NEXT:    scratch_store_b32 off, v246, s32 offset:568
; GISEL64-NEXT:    scratch_store_b32 off, v247, s32 offset:572
; GISEL64-NEXT:    s_mov_b64 exec, -1
; GISEL64-NEXT:    v_mov_b32_e32 v2, v0
; GISEL64-NEXT:    s_mov_b32 s36, gfx_callee@abs32@lo
; GISEL64-NEXT:    s_mov_b32 s37, gfx_callee@abs32@hi
; GISEL64-NEXT:    v_swap_b32 v0, v1
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    s_xor_b64 exec, s[0:1], -1
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v0, off, s32
; GISEL64-NEXT:    scratch_load_b32 v1, off, s32 offset:4
; GISEL64-NEXT:    scratch_load_b32 v2, off, s32 offset:8
; GISEL64-NEXT:    scratch_load_b32 v3, off, s32 offset:12
; GISEL64-NEXT:    scratch_load_b32 v4, off, s32 offset:16
; GISEL64-NEXT:    scratch_load_b32 v5, off, s32 offset:20
; GISEL64-NEXT:    scratch_load_b32 v6, off, s32 offset:24
; GISEL64-NEXT:    scratch_load_b32 v7, off, s32 offset:28
; GISEL64-NEXT:    scratch_load_b32 v8, off, s32 offset:32
; GISEL64-NEXT:    scratch_load_b32 v9, off, s32 offset:36
; GISEL64-NEXT:    scratch_load_b32 v10, off, s32 offset:40
; GISEL64-NEXT:    scratch_load_b32 v11, off, s32 offset:44
; GISEL64-NEXT:    scratch_load_b32 v12, off, s32 offset:48
; GISEL64-NEXT:    scratch_load_b32 v13, off, s32 offset:52
; GISEL64-NEXT:    scratch_load_b32 v14, off, s32 offset:56
; GISEL64-NEXT:    scratch_load_b32 v15, off, s32 offset:60
; GISEL64-NEXT:    scratch_load_b32 v16, off, s32 offset:64
; GISEL64-NEXT:    scratch_load_b32 v17, off, s32 offset:68
; GISEL64-NEXT:    scratch_load_b32 v18, off, s32 offset:72
; GISEL64-NEXT:    scratch_load_b32 v19, off, s32 offset:76
; GISEL64-NEXT:    scratch_load_b32 v20, off, s32 offset:80
; GISEL64-NEXT:    scratch_load_b32 v21, off, s32 offset:84
; GISEL64-NEXT:    scratch_load_b32 v22, off, s32 offset:88
; GISEL64-NEXT:    scratch_load_b32 v23, off, s32 offset:92
; GISEL64-NEXT:    scratch_load_b32 v24, off, s32 offset:96
; GISEL64-NEXT:    scratch_load_b32 v25, off, s32 offset:100
; GISEL64-NEXT:    scratch_load_b32 v26, off, s32 offset:104
; GISEL64-NEXT:    scratch_load_b32 v27, off, s32 offset:108
; GISEL64-NEXT:    scratch_load_b32 v28, off, s32 offset:112
; GISEL64-NEXT:    scratch_load_b32 v29, off, s32 offset:116
; GISEL64-NEXT:    scratch_load_b32 v30, off, s32 offset:120
; GISEL64-NEXT:    scratch_load_b32 v31, off, s32 offset:124
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v32, off, s32 offset:128
; GISEL64-NEXT:    scratch_load_b32 v33, off, s32 offset:132
; GISEL64-NEXT:    scratch_load_b32 v34, off, s32 offset:136
; GISEL64-NEXT:    scratch_load_b32 v35, off, s32 offset:140
; GISEL64-NEXT:    scratch_load_b32 v36, off, s32 offset:144
; GISEL64-NEXT:    scratch_load_b32 v37, off, s32 offset:148
; GISEL64-NEXT:    scratch_load_b32 v38, off, s32 offset:152
; GISEL64-NEXT:    scratch_load_b32 v39, off, s32 offset:156
; GISEL64-NEXT:    scratch_load_b32 v48, off, s32 offset:160
; GISEL64-NEXT:    scratch_load_b32 v49, off, s32 offset:164
; GISEL64-NEXT:    scratch_load_b32 v50, off, s32 offset:168
; GISEL64-NEXT:    scratch_load_b32 v51, off, s32 offset:172
; GISEL64-NEXT:    scratch_load_b32 v52, off, s32 offset:176
; GISEL64-NEXT:    scratch_load_b32 v53, off, s32 offset:180
; GISEL64-NEXT:    scratch_load_b32 v54, off, s32 offset:184
; GISEL64-NEXT:    scratch_load_b32 v55, off, s32 offset:188
; GISEL64-NEXT:    scratch_load_b32 v64, off, s32 offset:192
; GISEL64-NEXT:    scratch_load_b32 v65, off, s32 offset:196
; GISEL64-NEXT:    scratch_load_b32 v66, off, s32 offset:200
; GISEL64-NEXT:    scratch_load_b32 v67, off, s32 offset:204
; GISEL64-NEXT:    scratch_load_b32 v68, off, s32 offset:208
; GISEL64-NEXT:    scratch_load_b32 v69, off, s32 offset:212
; GISEL64-NEXT:    scratch_load_b32 v70, off, s32 offset:216
; GISEL64-NEXT:    scratch_load_b32 v71, off, s32 offset:220
; GISEL64-NEXT:    scratch_load_b32 v80, off, s32 offset:224
; GISEL64-NEXT:    scratch_load_b32 v81, off, s32 offset:228
; GISEL64-NEXT:    scratch_load_b32 v82, off, s32 offset:232
; GISEL64-NEXT:    scratch_load_b32 v83, off, s32 offset:236
; GISEL64-NEXT:    scratch_load_b32 v84, off, s32 offset:240
; GISEL64-NEXT:    scratch_load_b32 v85, off, s32 offset:244
; GISEL64-NEXT:    scratch_load_b32 v86, off, s32 offset:248
; GISEL64-NEXT:    scratch_load_b32 v87, off, s32 offset:252
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v96, off, s32 offset:256
; GISEL64-NEXT:    scratch_load_b32 v97, off, s32 offset:260
; GISEL64-NEXT:    scratch_load_b32 v98, off, s32 offset:264
; GISEL64-NEXT:    scratch_load_b32 v99, off, s32 offset:268
; GISEL64-NEXT:    scratch_load_b32 v100, off, s32 offset:272
; GISEL64-NEXT:    scratch_load_b32 v101, off, s32 offset:276
; GISEL64-NEXT:    scratch_load_b32 v102, off, s32 offset:280
; GISEL64-NEXT:    scratch_load_b32 v103, off, s32 offset:284
; GISEL64-NEXT:    scratch_load_b32 v112, off, s32 offset:288
; GISEL64-NEXT:    scratch_load_b32 v113, off, s32 offset:292
; GISEL64-NEXT:    scratch_load_b32 v114, off, s32 offset:296
; GISEL64-NEXT:    scratch_load_b32 v115, off, s32 offset:300
; GISEL64-NEXT:    scratch_load_b32 v116, off, s32 offset:304
; GISEL64-NEXT:    scratch_load_b32 v117, off, s32 offset:308
; GISEL64-NEXT:    scratch_load_b32 v118, off, s32 offset:312
; GISEL64-NEXT:    scratch_load_b32 v119, off, s32 offset:316
; GISEL64-NEXT:    scratch_load_b32 v128, off, s32 offset:320
; GISEL64-NEXT:    scratch_load_b32 v129, off, s32 offset:324
; GISEL64-NEXT:    scratch_load_b32 v130, off, s32 offset:328
; GISEL64-NEXT:    scratch_load_b32 v131, off, s32 offset:332
; GISEL64-NEXT:    scratch_load_b32 v132, off, s32 offset:336
; GISEL64-NEXT:    scratch_load_b32 v133, off, s32 offset:340
; GISEL64-NEXT:    scratch_load_b32 v134, off, s32 offset:344
; GISEL64-NEXT:    scratch_load_b32 v135, off, s32 offset:348
; GISEL64-NEXT:    scratch_load_b32 v144, off, s32 offset:352
; GISEL64-NEXT:    scratch_load_b32 v145, off, s32 offset:356
; GISEL64-NEXT:    scratch_load_b32 v146, off, s32 offset:360
; GISEL64-NEXT:    scratch_load_b32 v147, off, s32 offset:364
; GISEL64-NEXT:    scratch_load_b32 v148, off, s32 offset:368
; GISEL64-NEXT:    scratch_load_b32 v149, off, s32 offset:372
; GISEL64-NEXT:    scratch_load_b32 v150, off, s32 offset:376
; GISEL64-NEXT:    scratch_load_b32 v151, off, s32 offset:380
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v160, off, s32 offset:384
; GISEL64-NEXT:    scratch_load_b32 v161, off, s32 offset:388
; GISEL64-NEXT:    scratch_load_b32 v162, off, s32 offset:392
; GISEL64-NEXT:    scratch_load_b32 v163, off, s32 offset:396
; GISEL64-NEXT:    scratch_load_b32 v164, off, s32 offset:400
; GISEL64-NEXT:    scratch_load_b32 v165, off, s32 offset:404
; GISEL64-NEXT:    scratch_load_b32 v166, off, s32 offset:408
; GISEL64-NEXT:    scratch_load_b32 v167, off, s32 offset:412
; GISEL64-NEXT:    scratch_load_b32 v176, off, s32 offset:416
; GISEL64-NEXT:    scratch_load_b32 v177, off, s32 offset:420
; GISEL64-NEXT:    scratch_load_b32 v178, off, s32 offset:424
; GISEL64-NEXT:    scratch_load_b32 v179, off, s32 offset:428
; GISEL64-NEXT:    scratch_load_b32 v180, off, s32 offset:432
; GISEL64-NEXT:    scratch_load_b32 v181, off, s32 offset:436
; GISEL64-NEXT:    scratch_load_b32 v182, off, s32 offset:440
; GISEL64-NEXT:    scratch_load_b32 v183, off, s32 offset:444
; GISEL64-NEXT:    scratch_load_b32 v192, off, s32 offset:448
; GISEL64-NEXT:    scratch_load_b32 v193, off, s32 offset:452
; GISEL64-NEXT:    scratch_load_b32 v194, off, s32 offset:456
; GISEL64-NEXT:    scratch_load_b32 v195, off, s32 offset:460
; GISEL64-NEXT:    scratch_load_b32 v196, off, s32 offset:464
; GISEL64-NEXT:    scratch_load_b32 v197, off, s32 offset:468
; GISEL64-NEXT:    scratch_load_b32 v198, off, s32 offset:472
; GISEL64-NEXT:    scratch_load_b32 v199, off, s32 offset:476
; GISEL64-NEXT:    scratch_load_b32 v208, off, s32 offset:480
; GISEL64-NEXT:    scratch_load_b32 v209, off, s32 offset:484
; GISEL64-NEXT:    scratch_load_b32 v210, off, s32 offset:488
; GISEL64-NEXT:    scratch_load_b32 v211, off, s32 offset:492
; GISEL64-NEXT:    scratch_load_b32 v212, off, s32 offset:496
; GISEL64-NEXT:    scratch_load_b32 v213, off, s32 offset:500
; GISEL64-NEXT:    scratch_load_b32 v214, off, s32 offset:504
; GISEL64-NEXT:    scratch_load_b32 v215, off, s32 offset:508
; GISEL64-NEXT:    s_clause 0xf ; 64-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v224, off, s32 offset:512
; GISEL64-NEXT:    scratch_load_b32 v225, off, s32 offset:516
; GISEL64-NEXT:    scratch_load_b32 v226, off, s32 offset:520
; GISEL64-NEXT:    scratch_load_b32 v227, off, s32 offset:524
; GISEL64-NEXT:    scratch_load_b32 v228, off, s32 offset:528
; GISEL64-NEXT:    scratch_load_b32 v229, off, s32 offset:532
; GISEL64-NEXT:    scratch_load_b32 v230, off, s32 offset:536
; GISEL64-NEXT:    scratch_load_b32 v231, off, s32 offset:540
; GISEL64-NEXT:    scratch_load_b32 v240, off, s32 offset:544
; GISEL64-NEXT:    scratch_load_b32 v241, off, s32 offset:548
; GISEL64-NEXT:    scratch_load_b32 v242, off, s32 offset:552
; GISEL64-NEXT:    scratch_load_b32 v243, off, s32 offset:556
; GISEL64-NEXT:    scratch_load_b32 v244, off, s32 offset:560
; GISEL64-NEXT:    scratch_load_b32 v245, off, s32 offset:564
; GISEL64-NEXT:    scratch_load_b32 v246, off, s32 offset:568
; GISEL64-NEXT:    scratch_load_b32 v247, off, s32 offset:572
; GISEL64-NEXT:    s_mov_b64 exec, s[0:1]
; GISEL64-NEXT:    s_setpc_b64 s[36:37]
;
; GFX1250-DAGISEL-LABEL: tail_call_gfx_from_whole_wave:
; GFX1250-DAGISEL:       ; %bb.0:
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-DAGISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_xor_saveexec_b32 s0, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0, s32 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1, s32 offset:4 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v2, s32 offset:8 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v3, s32 offset:12 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v4, s32 offset:16 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v5, s32 offset:20 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v6, s32 offset:24 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v7, s32 offset:28 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v8, s32 offset:32 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v9, s32 offset:36 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v10, s32 offset:40 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v11, s32 offset:44 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v12, s32 offset:48 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v13, s32 offset:52 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v14, s32 offset:56 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v15, s32 offset:60 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v16, s32 offset:64 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v17, s32 offset:68 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v18, s32 offset:72 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v19, s32 offset:76 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v20, s32 offset:80 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v21, s32 offset:84 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v22, s32 offset:88 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v23, s32 offset:92 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v24, s32 offset:96 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v25, s32 offset:100 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v26, s32 offset:104 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v27, s32 offset:108 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v28, s32 offset:112 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v29, s32 offset:116 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v30, s32 offset:120 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v31, s32 offset:124 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v32, s32 offset:128 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v33, s32 offset:132 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v34, s32 offset:136 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v35, s32 offset:140 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v36, s32 offset:144 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v37, s32 offset:148 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v38, s32 offset:152 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v39, s32 offset:156 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v48, s32 offset:160 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v49, s32 offset:164 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v50, s32 offset:168 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v51, s32 offset:172 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v52, s32 offset:176 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v53, s32 offset:180 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v54, s32 offset:184 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v55, s32 offset:188 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v64, s32 offset:192 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v65, s32 offset:196 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v66, s32 offset:200 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v67, s32 offset:204 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v68, s32 offset:208 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v69, s32 offset:212 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v70, s32 offset:216 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v71, s32 offset:220 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v80, s32 offset:224 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v81, s32 offset:228 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v82, s32 offset:232 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v83, s32 offset:236 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v84, s32 offset:240 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v85, s32 offset:244 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v86, s32 offset:248 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v87, s32 offset:252 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v96, s32 offset:256 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v97, s32 offset:260 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v98, s32 offset:264 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v99, s32 offset:268 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v100, s32 offset:272 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v101, s32 offset:276 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v102, s32 offset:280 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v103, s32 offset:284 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v112, s32 offset:288 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v113, s32 offset:292 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v114, s32 offset:296 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v115, s32 offset:300 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v116, s32 offset:304 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v117, s32 offset:308 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v118, s32 offset:312 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v119, s32 offset:316 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v128, s32 offset:320 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v129, s32 offset:324 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v130, s32 offset:328 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v131, s32 offset:332 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v132, s32 offset:336 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v133, s32 offset:340 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v134, s32 offset:344 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v135, s32 offset:348 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v144, s32 offset:352 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v145, s32 offset:356 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v146, s32 offset:360 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v147, s32 offset:364 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v148, s32 offset:368 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v149, s32 offset:372 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v150, s32 offset:376 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v151, s32 offset:380 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v160, s32 offset:384 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v161, s32 offset:388 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v162, s32 offset:392 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v163, s32 offset:396 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v164, s32 offset:400 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v165, s32 offset:404 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v166, s32 offset:408 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v167, s32 offset:412 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v176, s32 offset:416 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v177, s32 offset:420 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v178, s32 offset:424 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v179, s32 offset:428 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v180, s32 offset:432 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v181, s32 offset:436 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v182, s32 offset:440 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v183, s32 offset:444 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v192, s32 offset:448 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v193, s32 offset:452 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v194, s32 offset:456 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v195, s32 offset:460 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v196, s32 offset:464 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v197, s32 offset:468 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v198, s32 offset:472 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v199, s32 offset:476 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v208, s32 offset:480 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v209, s32 offset:484 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v210, s32 offset:488 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v211, s32 offset:492 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v212, s32 offset:496 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v213, s32 offset:500 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v214, s32 offset:504 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v215, s32 offset:508 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v224, s32 offset:512 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v225, s32 offset:516 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v226, s32 offset:520 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v227, s32 offset:524 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v228, s32 offset:528 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v229, s32 offset:532 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v230, s32 offset:536 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v231, s32 offset:540 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v240, s32 offset:544 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v241, s32 offset:548 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v242, s32 offset:552 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v243, s32 offset:556 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v244, s32 offset:560 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v245, s32 offset:564 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v246, s32 offset:568 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v247, s32 offset:572 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 4 ; msbs: dst=0 src0=0 src1=1 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0 /*v256*/, s32 offset:576 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1 /*v257*/, s32 offset:580 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v2 /*v258*/, s32 offset:584 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v3 /*v259*/, s32 offset:588 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v4 /*v260*/, s32 offset:592 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v5 /*v261*/, s32 offset:596 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v6 /*v262*/, s32 offset:600 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v7 /*v263*/, s32 offset:604 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v8 /*v264*/, s32 offset:608 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v9 /*v265*/, s32 offset:612 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v10 /*v266*/, s32 offset:616 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v11 /*v267*/, s32 offset:620 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v12 /*v268*/, s32 offset:624 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v13 /*v269*/, s32 offset:628 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v14 /*v270*/, s32 offset:632 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v15 /*v271*/, s32 offset:636 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v16 /*v272*/, s32 offset:640 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v17 /*v273*/, s32 offset:644 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v18 /*v274*/, s32 offset:648 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v19 /*v275*/, s32 offset:652 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v20 /*v276*/, s32 offset:656 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v21 /*v277*/, s32 offset:660 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v22 /*v278*/, s32 offset:664 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v23 /*v279*/, s32 offset:668 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v24 /*v280*/, s32 offset:672 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v25 /*v281*/, s32 offset:676 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v26 /*v282*/, s32 offset:680 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v27 /*v283*/, s32 offset:684 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v28 /*v284*/, s32 offset:688 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v29 /*v285*/, s32 offset:692 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v30 /*v286*/, s32 offset:696 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v31 /*v287*/, s32 offset:700 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v32 /*v288*/, s32 offset:704 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v33 /*v289*/, s32 offset:708 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v34 /*v290*/, s32 offset:712 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v35 /*v291*/, s32 offset:716 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v36 /*v292*/, s32 offset:720 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v37 /*v293*/, s32 offset:724 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v38 /*v294*/, s32 offset:728 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v39 /*v295*/, s32 offset:732 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v40 /*v296*/, s32 offset:736 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v41 /*v297*/, s32 offset:740 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v42 /*v298*/, s32 offset:744 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v43 /*v299*/, s32 offset:748 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v44 /*v300*/, s32 offset:752 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v45 /*v301*/, s32 offset:756 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v46 /*v302*/, s32 offset:760 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v47 /*v303*/, s32 offset:764 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v48 /*v304*/, s32 offset:768 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v49 /*v305*/, s32 offset:772 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v50 /*v306*/, s32 offset:776 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v51 /*v307*/, s32 offset:780 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v52 /*v308*/, s32 offset:784 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v53 /*v309*/, s32 offset:788 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v54 /*v310*/, s32 offset:792 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v55 /*v311*/, s32 offset:796 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v56 /*v312*/, s32 offset:800 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v57 /*v313*/, s32 offset:804 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v58 /*v314*/, s32 offset:808 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v59 /*v315*/, s32 offset:812 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v60 /*v316*/, s32 offset:816 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v61 /*v317*/, s32 offset:820 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v62 /*v318*/, s32 offset:824 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v63 /*v319*/, s32 offset:828 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v64 /*v320*/, s32 offset:832 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v65 /*v321*/, s32 offset:836 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v66 /*v322*/, s32 offset:840 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v67 /*v323*/, s32 offset:844 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v68 /*v324*/, s32 offset:848 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v69 /*v325*/, s32 offset:852 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v70 /*v326*/, s32 offset:856 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v71 /*v327*/, s32 offset:860 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v72 /*v328*/, s32 offset:864 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v73 /*v329*/, s32 offset:868 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v74 /*v330*/, s32 offset:872 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v75 /*v331*/, s32 offset:876 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v76 /*v332*/, s32 offset:880 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v77 /*v333*/, s32 offset:884 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v78 /*v334*/, s32 offset:888 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v79 /*v335*/, s32 offset:892 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v80 /*v336*/, s32 offset:896 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v81 /*v337*/, s32 offset:900 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v82 /*v338*/, s32 offset:904 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v83 /*v339*/, s32 offset:908 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v84 /*v340*/, s32 offset:912 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v85 /*v341*/, s32 offset:916 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v86 /*v342*/, s32 offset:920 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v87 /*v343*/, s32 offset:924 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v88 /*v344*/, s32 offset:928 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v89 /*v345*/, s32 offset:932 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v90 /*v346*/, s32 offset:936 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v91 /*v347*/, s32 offset:940 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v92 /*v348*/, s32 offset:944 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v93 /*v349*/, s32 offset:948 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v94 /*v350*/, s32 offset:952 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v95 /*v351*/, s32 offset:956 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v96 /*v352*/, s32 offset:960 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v97 /*v353*/, s32 offset:964 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v98 /*v354*/, s32 offset:968 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v99 /*v355*/, s32 offset:972 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v100 /*v356*/, s32 offset:976 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v101 /*v357*/, s32 offset:980 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v102 /*v358*/, s32 offset:984 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v103 /*v359*/, s32 offset:988 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v104 /*v360*/, s32 offset:992 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v105 /*v361*/, s32 offset:996 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v106 /*v362*/, s32 offset:1000 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v107 /*v363*/, s32 offset:1004 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v108 /*v364*/, s32 offset:1008 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v109 /*v365*/, s32 offset:1012 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v110 /*v366*/, s32 offset:1016 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v111 /*v367*/, s32 offset:1020 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v112 /*v368*/, s32 offset:1024 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v113 /*v369*/, s32 offset:1028 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v114 /*v370*/, s32 offset:1032 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v115 /*v371*/, s32 offset:1036 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v116 /*v372*/, s32 offset:1040 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v117 /*v373*/, s32 offset:1044 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v118 /*v374*/, s32 offset:1048 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v119 /*v375*/, s32 offset:1052 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v120 /*v376*/, s32 offset:1056 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v121 /*v377*/, s32 offset:1060 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v122 /*v378*/, s32 offset:1064 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v123 /*v379*/, s32 offset:1068 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v124 /*v380*/, s32 offset:1072 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v125 /*v381*/, s32 offset:1076 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v126 /*v382*/, s32 offset:1080 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v127 /*v383*/, s32 offset:1084 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v128 /*v384*/, s32 offset:1088 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v129 /*v385*/, s32 offset:1092 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v130 /*v386*/, s32 offset:1096 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v131 /*v387*/, s32 offset:1100 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v132 /*v388*/, s32 offset:1104 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v133 /*v389*/, s32 offset:1108 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v134 /*v390*/, s32 offset:1112 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v135 /*v391*/, s32 offset:1116 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v136 /*v392*/, s32 offset:1120 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v137 /*v393*/, s32 offset:1124 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v138 /*v394*/, s32 offset:1128 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v139 /*v395*/, s32 offset:1132 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v140 /*v396*/, s32 offset:1136 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v141 /*v397*/, s32 offset:1140 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v142 /*v398*/, s32 offset:1144 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v143 /*v399*/, s32 offset:1148 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v144 /*v400*/, s32 offset:1152 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v145 /*v401*/, s32 offset:1156 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v146 /*v402*/, s32 offset:1160 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v147 /*v403*/, s32 offset:1164 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v148 /*v404*/, s32 offset:1168 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v149 /*v405*/, s32 offset:1172 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v150 /*v406*/, s32 offset:1176 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v151 /*v407*/, s32 offset:1180 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v152 /*v408*/, s32 offset:1184 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v153 /*v409*/, s32 offset:1188 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v154 /*v410*/, s32 offset:1192 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v155 /*v411*/, s32 offset:1196 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v156 /*v412*/, s32 offset:1200 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v157 /*v413*/, s32 offset:1204 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v158 /*v414*/, s32 offset:1208 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v159 /*v415*/, s32 offset:1212 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v160 /*v416*/, s32 offset:1216 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v161 /*v417*/, s32 offset:1220 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v162 /*v418*/, s32 offset:1224 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v163 /*v419*/, s32 offset:1228 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v164 /*v420*/, s32 offset:1232 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v165 /*v421*/, s32 offset:1236 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v166 /*v422*/, s32 offset:1240 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v167 /*v423*/, s32 offset:1244 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v168 /*v424*/, s32 offset:1248 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v169 /*v425*/, s32 offset:1252 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v170 /*v426*/, s32 offset:1256 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v171 /*v427*/, s32 offset:1260 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v172 /*v428*/, s32 offset:1264 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v173 /*v429*/, s32 offset:1268 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v174 /*v430*/, s32 offset:1272 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v175 /*v431*/, s32 offset:1276 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v176 /*v432*/, s32 offset:1280 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v177 /*v433*/, s32 offset:1284 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v178 /*v434*/, s32 offset:1288 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v179 /*v435*/, s32 offset:1292 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v180 /*v436*/, s32 offset:1296 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v181 /*v437*/, s32 offset:1300 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v182 /*v438*/, s32 offset:1304 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v183 /*v439*/, s32 offset:1308 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v184 /*v440*/, s32 offset:1312 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v185 /*v441*/, s32 offset:1316 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v186 /*v442*/, s32 offset:1320 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v187 /*v443*/, s32 offset:1324 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v188 /*v444*/, s32 offset:1328 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v189 /*v445*/, s32 offset:1332 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v190 /*v446*/, s32 offset:1336 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v191 /*v447*/, s32 offset:1340 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v192 /*v448*/, s32 offset:1344 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v193 /*v449*/, s32 offset:1348 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v194 /*v450*/, s32 offset:1352 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v195 /*v451*/, s32 offset:1356 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v196 /*v452*/, s32 offset:1360 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v197 /*v453*/, s32 offset:1364 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v198 /*v454*/, s32 offset:1368 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v199 /*v455*/, s32 offset:1372 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v200 /*v456*/, s32 offset:1376 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v201 /*v457*/, s32 offset:1380 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v202 /*v458*/, s32 offset:1384 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v203 /*v459*/, s32 offset:1388 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v204 /*v460*/, s32 offset:1392 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v205 /*v461*/, s32 offset:1396 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v206 /*v462*/, s32 offset:1400 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v207 /*v463*/, s32 offset:1404 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v208 /*v464*/, s32 offset:1408 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v209 /*v465*/, s32 offset:1412 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v210 /*v466*/, s32 offset:1416 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v211 /*v467*/, s32 offset:1420 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v212 /*v468*/, s32 offset:1424 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v213 /*v469*/, s32 offset:1428 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v214 /*v470*/, s32 offset:1432 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v215 /*v471*/, s32 offset:1436 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v216 /*v472*/, s32 offset:1440 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v217 /*v473*/, s32 offset:1444 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v218 /*v474*/, s32 offset:1448 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v219 /*v475*/, s32 offset:1452 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v220 /*v476*/, s32 offset:1456 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v221 /*v477*/, s32 offset:1460 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v222 /*v478*/, s32 offset:1464 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v223 /*v479*/, s32 offset:1468 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v224 /*v480*/, s32 offset:1472 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v225 /*v481*/, s32 offset:1476 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v226 /*v482*/, s32 offset:1480 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v227 /*v483*/, s32 offset:1484 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v228 /*v484*/, s32 offset:1488 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v229 /*v485*/, s32 offset:1492 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v230 /*v486*/, s32 offset:1496 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v231 /*v487*/, s32 offset:1500 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v232 /*v488*/, s32 offset:1504 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v233 /*v489*/, s32 offset:1508 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v234 /*v490*/, s32 offset:1512 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v235 /*v491*/, s32 offset:1516 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v236 /*v492*/, s32 offset:1520 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v237 /*v493*/, s32 offset:1524 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v238 /*v494*/, s32 offset:1528 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v239 /*v495*/, s32 offset:1532 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v240 /*v496*/, s32 offset:1536 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v241 /*v497*/, s32 offset:1540 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v242 /*v498*/, s32 offset:1544 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v243 /*v499*/, s32 offset:1548 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v244 /*v500*/, s32 offset:1552 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v245 /*v501*/, s32 offset:1556 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v246 /*v502*/, s32 offset:1560 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v247 /*v503*/, s32 offset:1564 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v248 /*v504*/, s32 offset:1568 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v249 /*v505*/, s32 offset:1572 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v250 /*v506*/, s32 offset:1576 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v251 /*v507*/, s32 offset:1580 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v252 /*v508*/, s32 offset:1584 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v253 /*v509*/, s32 offset:1588 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v254 /*v510*/, s32 offset:1592 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v255 /*v511*/, s32 offset:1596 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0x408 ; msbs: dst=0 src0=0 src1=2 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0 /*v512*/, s32 offset:1600 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1 /*v513*/, s32 offset:1604 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v2 /*v514*/, s32 offset:1608 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v3 /*v515*/, s32 offset:1612 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v4 /*v516*/, s32 offset:1616 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v5 /*v517*/, s32 offset:1620 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v6 /*v518*/, s32 offset:1624 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v7 /*v519*/, s32 offset:1628 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v8 /*v520*/, s32 offset:1632 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v9 /*v521*/, s32 offset:1636 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v10 /*v522*/, s32 offset:1640 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v11 /*v523*/, s32 offset:1644 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v12 /*v524*/, s32 offset:1648 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v13 /*v525*/, s32 offset:1652 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v14 /*v526*/, s32 offset:1656 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v15 /*v527*/, s32 offset:1660 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v16 /*v528*/, s32 offset:1664 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v17 /*v529*/, s32 offset:1668 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v18 /*v530*/, s32 offset:1672 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v19 /*v531*/, s32 offset:1676 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v20 /*v532*/, s32 offset:1680 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v21 /*v533*/, s32 offset:1684 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v22 /*v534*/, s32 offset:1688 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v23 /*v535*/, s32 offset:1692 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v24 /*v536*/, s32 offset:1696 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v25 /*v537*/, s32 offset:1700 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v26 /*v538*/, s32 offset:1704 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v27 /*v539*/, s32 offset:1708 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v28 /*v540*/, s32 offset:1712 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v29 /*v541*/, s32 offset:1716 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v30 /*v542*/, s32 offset:1720 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v31 /*v543*/, s32 offset:1724 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v32 /*v544*/, s32 offset:1728 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v33 /*v545*/, s32 offset:1732 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v34 /*v546*/, s32 offset:1736 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v35 /*v547*/, s32 offset:1740 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v36 /*v548*/, s32 offset:1744 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v37 /*v549*/, s32 offset:1748 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v38 /*v550*/, s32 offset:1752 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v39 /*v551*/, s32 offset:1756 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v40 /*v552*/, s32 offset:1760 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v41 /*v553*/, s32 offset:1764 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v42 /*v554*/, s32 offset:1768 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v43 /*v555*/, s32 offset:1772 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v44 /*v556*/, s32 offset:1776 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v45 /*v557*/, s32 offset:1780 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v46 /*v558*/, s32 offset:1784 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v47 /*v559*/, s32 offset:1788 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v48 /*v560*/, s32 offset:1792 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v49 /*v561*/, s32 offset:1796 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v50 /*v562*/, s32 offset:1800 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v51 /*v563*/, s32 offset:1804 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v52 /*v564*/, s32 offset:1808 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v53 /*v565*/, s32 offset:1812 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v54 /*v566*/, s32 offset:1816 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v55 /*v567*/, s32 offset:1820 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v56 /*v568*/, s32 offset:1824 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v57 /*v569*/, s32 offset:1828 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v58 /*v570*/, s32 offset:1832 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v59 /*v571*/, s32 offset:1836 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v60 /*v572*/, s32 offset:1840 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v61 /*v573*/, s32 offset:1844 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v62 /*v574*/, s32 offset:1848 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v63 /*v575*/, s32 offset:1852 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v64 /*v576*/, s32 offset:1856 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v65 /*v577*/, s32 offset:1860 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v66 /*v578*/, s32 offset:1864 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v67 /*v579*/, s32 offset:1868 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v68 /*v580*/, s32 offset:1872 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v69 /*v581*/, s32 offset:1876 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v70 /*v582*/, s32 offset:1880 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v71 /*v583*/, s32 offset:1884 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v72 /*v584*/, s32 offset:1888 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v73 /*v585*/, s32 offset:1892 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v74 /*v586*/, s32 offset:1896 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v75 /*v587*/, s32 offset:1900 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v76 /*v588*/, s32 offset:1904 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v77 /*v589*/, s32 offset:1908 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v78 /*v590*/, s32 offset:1912 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v79 /*v591*/, s32 offset:1916 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v80 /*v592*/, s32 offset:1920 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v81 /*v593*/, s32 offset:1924 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v82 /*v594*/, s32 offset:1928 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v83 /*v595*/, s32 offset:1932 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v84 /*v596*/, s32 offset:1936 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v85 /*v597*/, s32 offset:1940 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v86 /*v598*/, s32 offset:1944 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v87 /*v599*/, s32 offset:1948 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v88 /*v600*/, s32 offset:1952 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v89 /*v601*/, s32 offset:1956 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v90 /*v602*/, s32 offset:1960 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v91 /*v603*/, s32 offset:1964 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v92 /*v604*/, s32 offset:1968 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v93 /*v605*/, s32 offset:1972 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v94 /*v606*/, s32 offset:1976 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v95 /*v607*/, s32 offset:1980 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v96 /*v608*/, s32 offset:1984 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v97 /*v609*/, s32 offset:1988 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v98 /*v610*/, s32 offset:1992 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v99 /*v611*/, s32 offset:1996 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v100 /*v612*/, s32 offset:2000 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v101 /*v613*/, s32 offset:2004 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v102 /*v614*/, s32 offset:2008 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v103 /*v615*/, s32 offset:2012 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v104 /*v616*/, s32 offset:2016 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v105 /*v617*/, s32 offset:2020 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v106 /*v618*/, s32 offset:2024 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v107 /*v619*/, s32 offset:2028 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v108 /*v620*/, s32 offset:2032 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v109 /*v621*/, s32 offset:2036 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v110 /*v622*/, s32 offset:2040 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v111 /*v623*/, s32 offset:2044 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v112 /*v624*/, s32 offset:2048 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v113 /*v625*/, s32 offset:2052 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v114 /*v626*/, s32 offset:2056 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v115 /*v627*/, s32 offset:2060 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v116 /*v628*/, s32 offset:2064 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v117 /*v629*/, s32 offset:2068 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v118 /*v630*/, s32 offset:2072 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v119 /*v631*/, s32 offset:2076 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v120 /*v632*/, s32 offset:2080 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v121 /*v633*/, s32 offset:2084 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v122 /*v634*/, s32 offset:2088 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v123 /*v635*/, s32 offset:2092 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v124 /*v636*/, s32 offset:2096 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v125 /*v637*/, s32 offset:2100 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v126 /*v638*/, s32 offset:2104 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v127 /*v639*/, s32 offset:2108 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v128 /*v640*/, s32 offset:2112 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v129 /*v641*/, s32 offset:2116 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v130 /*v642*/, s32 offset:2120 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v131 /*v643*/, s32 offset:2124 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v132 /*v644*/, s32 offset:2128 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v133 /*v645*/, s32 offset:2132 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v134 /*v646*/, s32 offset:2136 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v135 /*v647*/, s32 offset:2140 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v136 /*v648*/, s32 offset:2144 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v137 /*v649*/, s32 offset:2148 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v138 /*v650*/, s32 offset:2152 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v139 /*v651*/, s32 offset:2156 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v140 /*v652*/, s32 offset:2160 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v141 /*v653*/, s32 offset:2164 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v142 /*v654*/, s32 offset:2168 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v143 /*v655*/, s32 offset:2172 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v144 /*v656*/, s32 offset:2176 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v145 /*v657*/, s32 offset:2180 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v146 /*v658*/, s32 offset:2184 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v147 /*v659*/, s32 offset:2188 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v148 /*v660*/, s32 offset:2192 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v149 /*v661*/, s32 offset:2196 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v150 /*v662*/, s32 offset:2200 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v151 /*v663*/, s32 offset:2204 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v152 /*v664*/, s32 offset:2208 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v153 /*v665*/, s32 offset:2212 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v154 /*v666*/, s32 offset:2216 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v155 /*v667*/, s32 offset:2220 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v156 /*v668*/, s32 offset:2224 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v157 /*v669*/, s32 offset:2228 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v158 /*v670*/, s32 offset:2232 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v159 /*v671*/, s32 offset:2236 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v160 /*v672*/, s32 offset:2240 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v161 /*v673*/, s32 offset:2244 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v162 /*v674*/, s32 offset:2248 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v163 /*v675*/, s32 offset:2252 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v164 /*v676*/, s32 offset:2256 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v165 /*v677*/, s32 offset:2260 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v166 /*v678*/, s32 offset:2264 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v167 /*v679*/, s32 offset:2268 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v168 /*v680*/, s32 offset:2272 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v169 /*v681*/, s32 offset:2276 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v170 /*v682*/, s32 offset:2280 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v171 /*v683*/, s32 offset:2284 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v172 /*v684*/, s32 offset:2288 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v173 /*v685*/, s32 offset:2292 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v174 /*v686*/, s32 offset:2296 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v175 /*v687*/, s32 offset:2300 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v176 /*v688*/, s32 offset:2304 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v177 /*v689*/, s32 offset:2308 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v178 /*v690*/, s32 offset:2312 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v179 /*v691*/, s32 offset:2316 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v180 /*v692*/, s32 offset:2320 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v181 /*v693*/, s32 offset:2324 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v182 /*v694*/, s32 offset:2328 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v183 /*v695*/, s32 offset:2332 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v184 /*v696*/, s32 offset:2336 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v185 /*v697*/, s32 offset:2340 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v186 /*v698*/, s32 offset:2344 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v187 /*v699*/, s32 offset:2348 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v188 /*v700*/, s32 offset:2352 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v189 /*v701*/, s32 offset:2356 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v190 /*v702*/, s32 offset:2360 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v191 /*v703*/, s32 offset:2364 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v192 /*v704*/, s32 offset:2368 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v193 /*v705*/, s32 offset:2372 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v194 /*v706*/, s32 offset:2376 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v195 /*v707*/, s32 offset:2380 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v196 /*v708*/, s32 offset:2384 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v197 /*v709*/, s32 offset:2388 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v198 /*v710*/, s32 offset:2392 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v199 /*v711*/, s32 offset:2396 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v200 /*v712*/, s32 offset:2400 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v201 /*v713*/, s32 offset:2404 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v202 /*v714*/, s32 offset:2408 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v203 /*v715*/, s32 offset:2412 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v204 /*v716*/, s32 offset:2416 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v205 /*v717*/, s32 offset:2420 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v206 /*v718*/, s32 offset:2424 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v207 /*v719*/, s32 offset:2428 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v208 /*v720*/, s32 offset:2432 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v209 /*v721*/, s32 offset:2436 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v210 /*v722*/, s32 offset:2440 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v211 /*v723*/, s32 offset:2444 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v212 /*v724*/, s32 offset:2448 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v213 /*v725*/, s32 offset:2452 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v214 /*v726*/, s32 offset:2456 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v215 /*v727*/, s32 offset:2460 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v216 /*v728*/, s32 offset:2464 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v217 /*v729*/, s32 offset:2468 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v218 /*v730*/, s32 offset:2472 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v219 /*v731*/, s32 offset:2476 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v220 /*v732*/, s32 offset:2480 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v221 /*v733*/, s32 offset:2484 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v222 /*v734*/, s32 offset:2488 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v223 /*v735*/, s32 offset:2492 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v224 /*v736*/, s32 offset:2496 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v225 /*v737*/, s32 offset:2500 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v226 /*v738*/, s32 offset:2504 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v227 /*v739*/, s32 offset:2508 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v228 /*v740*/, s32 offset:2512 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v229 /*v741*/, s32 offset:2516 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v230 /*v742*/, s32 offset:2520 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v231 /*v743*/, s32 offset:2524 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v232 /*v744*/, s32 offset:2528 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v233 /*v745*/, s32 offset:2532 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v234 /*v746*/, s32 offset:2536 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v235 /*v747*/, s32 offset:2540 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v236 /*v748*/, s32 offset:2544 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v237 /*v749*/, s32 offset:2548 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v238 /*v750*/, s32 offset:2552 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v239 /*v751*/, s32 offset:2556 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v240 /*v752*/, s32 offset:2560 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v241 /*v753*/, s32 offset:2564 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v242 /*v754*/, s32 offset:2568 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v243 /*v755*/, s32 offset:2572 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v244 /*v756*/, s32 offset:2576 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v245 /*v757*/, s32 offset:2580 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v246 /*v758*/, s32 offset:2584 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v247 /*v759*/, s32 offset:2588 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v248 /*v760*/, s32 offset:2592 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v249 /*v761*/, s32 offset:2596 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v250 /*v762*/, s32 offset:2600 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v251 /*v763*/, s32 offset:2604 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v252 /*v764*/, s32 offset:2608 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v253 /*v765*/, s32 offset:2612 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v254 /*v766*/, s32 offset:2616 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v255 /*v767*/, s32 offset:2620 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0x80c ; msbs: dst=0 src0=0 src1=3 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0 /*v768*/, s32 offset:2624 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1 /*v769*/, s32 offset:2628 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v2 /*v770*/, s32 offset:2632 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v3 /*v771*/, s32 offset:2636 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v4 /*v772*/, s32 offset:2640 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v5 /*v773*/, s32 offset:2644 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v6 /*v774*/, s32 offset:2648 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v7 /*v775*/, s32 offset:2652 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v8 /*v776*/, s32 offset:2656 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v9 /*v777*/, s32 offset:2660 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v10 /*v778*/, s32 offset:2664 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v11 /*v779*/, s32 offset:2668 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v12 /*v780*/, s32 offset:2672 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v13 /*v781*/, s32 offset:2676 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v14 /*v782*/, s32 offset:2680 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v15 /*v783*/, s32 offset:2684 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v16 /*v784*/, s32 offset:2688 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v17 /*v785*/, s32 offset:2692 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v18 /*v786*/, s32 offset:2696 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v19 /*v787*/, s32 offset:2700 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v20 /*v788*/, s32 offset:2704 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v21 /*v789*/, s32 offset:2708 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v22 /*v790*/, s32 offset:2712 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v23 /*v791*/, s32 offset:2716 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v24 /*v792*/, s32 offset:2720 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v25 /*v793*/, s32 offset:2724 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v26 /*v794*/, s32 offset:2728 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v27 /*v795*/, s32 offset:2732 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v28 /*v796*/, s32 offset:2736 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v29 /*v797*/, s32 offset:2740 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v30 /*v798*/, s32 offset:2744 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v31 /*v799*/, s32 offset:2748 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v32 /*v800*/, s32 offset:2752 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v33 /*v801*/, s32 offset:2756 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v34 /*v802*/, s32 offset:2760 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v35 /*v803*/, s32 offset:2764 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v36 /*v804*/, s32 offset:2768 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v37 /*v805*/, s32 offset:2772 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v38 /*v806*/, s32 offset:2776 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v39 /*v807*/, s32 offset:2780 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v40 /*v808*/, s32 offset:2784 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v41 /*v809*/, s32 offset:2788 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v42 /*v810*/, s32 offset:2792 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v43 /*v811*/, s32 offset:2796 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v44 /*v812*/, s32 offset:2800 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v45 /*v813*/, s32 offset:2804 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v46 /*v814*/, s32 offset:2808 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v47 /*v815*/, s32 offset:2812 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v48 /*v816*/, s32 offset:2816 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v49 /*v817*/, s32 offset:2820 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v50 /*v818*/, s32 offset:2824 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v51 /*v819*/, s32 offset:2828 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v52 /*v820*/, s32 offset:2832 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v53 /*v821*/, s32 offset:2836 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v54 /*v822*/, s32 offset:2840 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v55 /*v823*/, s32 offset:2844 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v56 /*v824*/, s32 offset:2848 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v57 /*v825*/, s32 offset:2852 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v58 /*v826*/, s32 offset:2856 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v59 /*v827*/, s32 offset:2860 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v60 /*v828*/, s32 offset:2864 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v61 /*v829*/, s32 offset:2868 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v62 /*v830*/, s32 offset:2872 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v63 /*v831*/, s32 offset:2876 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v64 /*v832*/, s32 offset:2880 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v65 /*v833*/, s32 offset:2884 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v66 /*v834*/, s32 offset:2888 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v67 /*v835*/, s32 offset:2892 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v68 /*v836*/, s32 offset:2896 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v69 /*v837*/, s32 offset:2900 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v70 /*v838*/, s32 offset:2904 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v71 /*v839*/, s32 offset:2908 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v72 /*v840*/, s32 offset:2912 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v73 /*v841*/, s32 offset:2916 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v74 /*v842*/, s32 offset:2920 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v75 /*v843*/, s32 offset:2924 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v76 /*v844*/, s32 offset:2928 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v77 /*v845*/, s32 offset:2932 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v78 /*v846*/, s32 offset:2936 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v79 /*v847*/, s32 offset:2940 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v80 /*v848*/, s32 offset:2944 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v81 /*v849*/, s32 offset:2948 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v82 /*v850*/, s32 offset:2952 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v83 /*v851*/, s32 offset:2956 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v84 /*v852*/, s32 offset:2960 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v85 /*v853*/, s32 offset:2964 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v86 /*v854*/, s32 offset:2968 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v87 /*v855*/, s32 offset:2972 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v88 /*v856*/, s32 offset:2976 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v89 /*v857*/, s32 offset:2980 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v90 /*v858*/, s32 offset:2984 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v91 /*v859*/, s32 offset:2988 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v92 /*v860*/, s32 offset:2992 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v93 /*v861*/, s32 offset:2996 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v94 /*v862*/, s32 offset:3000 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v95 /*v863*/, s32 offset:3004 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v96 /*v864*/, s32 offset:3008 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v97 /*v865*/, s32 offset:3012 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v98 /*v866*/, s32 offset:3016 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v99 /*v867*/, s32 offset:3020 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v100 /*v868*/, s32 offset:3024 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v101 /*v869*/, s32 offset:3028 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v102 /*v870*/, s32 offset:3032 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v103 /*v871*/, s32 offset:3036 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v104 /*v872*/, s32 offset:3040 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v105 /*v873*/, s32 offset:3044 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v106 /*v874*/, s32 offset:3048 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v107 /*v875*/, s32 offset:3052 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v108 /*v876*/, s32 offset:3056 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v109 /*v877*/, s32 offset:3060 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v110 /*v878*/, s32 offset:3064 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v111 /*v879*/, s32 offset:3068 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v112 /*v880*/, s32 offset:3072 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v113 /*v881*/, s32 offset:3076 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v114 /*v882*/, s32 offset:3080 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v115 /*v883*/, s32 offset:3084 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v116 /*v884*/, s32 offset:3088 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v117 /*v885*/, s32 offset:3092 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v118 /*v886*/, s32 offset:3096 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v119 /*v887*/, s32 offset:3100 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v120 /*v888*/, s32 offset:3104 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v121 /*v889*/, s32 offset:3108 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v122 /*v890*/, s32 offset:3112 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v123 /*v891*/, s32 offset:3116 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v124 /*v892*/, s32 offset:3120 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v125 /*v893*/, s32 offset:3124 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v126 /*v894*/, s32 offset:3128 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v127 /*v895*/, s32 offset:3132 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v128 /*v896*/, s32 offset:3136 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v129 /*v897*/, s32 offset:3140 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v130 /*v898*/, s32 offset:3144 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v131 /*v899*/, s32 offset:3148 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v132 /*v900*/, s32 offset:3152 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v133 /*v901*/, s32 offset:3156 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v134 /*v902*/, s32 offset:3160 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v135 /*v903*/, s32 offset:3164 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v136 /*v904*/, s32 offset:3168 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v137 /*v905*/, s32 offset:3172 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v138 /*v906*/, s32 offset:3176 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v139 /*v907*/, s32 offset:3180 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v140 /*v908*/, s32 offset:3184 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v141 /*v909*/, s32 offset:3188 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v142 /*v910*/, s32 offset:3192 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v143 /*v911*/, s32 offset:3196 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v144 /*v912*/, s32 offset:3200 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v145 /*v913*/, s32 offset:3204 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v146 /*v914*/, s32 offset:3208 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v147 /*v915*/, s32 offset:3212 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v148 /*v916*/, s32 offset:3216 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v149 /*v917*/, s32 offset:3220 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v150 /*v918*/, s32 offset:3224 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v151 /*v919*/, s32 offset:3228 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v152 /*v920*/, s32 offset:3232 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v153 /*v921*/, s32 offset:3236 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v154 /*v922*/, s32 offset:3240 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v155 /*v923*/, s32 offset:3244 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v156 /*v924*/, s32 offset:3248 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v157 /*v925*/, s32 offset:3252 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v158 /*v926*/, s32 offset:3256 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v159 /*v927*/, s32 offset:3260 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v160 /*v928*/, s32 offset:3264 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v161 /*v929*/, s32 offset:3268 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v162 /*v930*/, s32 offset:3272 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v163 /*v931*/, s32 offset:3276 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v164 /*v932*/, s32 offset:3280 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v165 /*v933*/, s32 offset:3284 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v166 /*v934*/, s32 offset:3288 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v167 /*v935*/, s32 offset:3292 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v168 /*v936*/, s32 offset:3296 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v169 /*v937*/, s32 offset:3300 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v170 /*v938*/, s32 offset:3304 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v171 /*v939*/, s32 offset:3308 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v172 /*v940*/, s32 offset:3312 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v173 /*v941*/, s32 offset:3316 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v174 /*v942*/, s32 offset:3320 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v175 /*v943*/, s32 offset:3324 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v176 /*v944*/, s32 offset:3328 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v177 /*v945*/, s32 offset:3332 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v178 /*v946*/, s32 offset:3336 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v179 /*v947*/, s32 offset:3340 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v180 /*v948*/, s32 offset:3344 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v181 /*v949*/, s32 offset:3348 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v182 /*v950*/, s32 offset:3352 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v183 /*v951*/, s32 offset:3356 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v184 /*v952*/, s32 offset:3360 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v185 /*v953*/, s32 offset:3364 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v186 /*v954*/, s32 offset:3368 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v187 /*v955*/, s32 offset:3372 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v188 /*v956*/, s32 offset:3376 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v189 /*v957*/, s32 offset:3380 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v190 /*v958*/, s32 offset:3384 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v191 /*v959*/, s32 offset:3388 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v192 /*v960*/, s32 offset:3392 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v193 /*v961*/, s32 offset:3396 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v194 /*v962*/, s32 offset:3400 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v195 /*v963*/, s32 offset:3404 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v196 /*v964*/, s32 offset:3408 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v197 /*v965*/, s32 offset:3412 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v198 /*v966*/, s32 offset:3416 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v199 /*v967*/, s32 offset:3420 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v200 /*v968*/, s32 offset:3424 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v201 /*v969*/, s32 offset:3428 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v202 /*v970*/, s32 offset:3432 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v203 /*v971*/, s32 offset:3436 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v204 /*v972*/, s32 offset:3440 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v205 /*v973*/, s32 offset:3444 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v206 /*v974*/, s32 offset:3448 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v207 /*v975*/, s32 offset:3452 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v208 /*v976*/, s32 offset:3456 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v209 /*v977*/, s32 offset:3460 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v210 /*v978*/, s32 offset:3464 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v211 /*v979*/, s32 offset:3468 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v212 /*v980*/, s32 offset:3472 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v213 /*v981*/, s32 offset:3476 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v214 /*v982*/, s32 offset:3480 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v215 /*v983*/, s32 offset:3484 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v216 /*v984*/, s32 offset:3488 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v217 /*v985*/, s32 offset:3492 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v218 /*v986*/, s32 offset:3496 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v219 /*v987*/, s32 offset:3500 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v220 /*v988*/, s32 offset:3504 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v221 /*v989*/, s32 offset:3508 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v222 /*v990*/, s32 offset:3512 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v223 /*v991*/, s32 offset:3516 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v224 /*v992*/, s32 offset:3520 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v225 /*v993*/, s32 offset:3524 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x1d ; 120-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v226 /*v994*/, s32 offset:3528 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v227 /*v995*/, s32 offset:3532 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v228 /*v996*/, s32 offset:3536 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v229 /*v997*/, s32 offset:3540 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v230 /*v998*/, s32 offset:3544 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v231 /*v999*/, s32 offset:3548 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v232 /*v1000*/, s32 offset:3552 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v233 /*v1001*/, s32 offset:3556 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v234 /*v1002*/, s32 offset:3560 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v235 /*v1003*/, s32 offset:3564 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v236 /*v1004*/, s32 offset:3568 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v237 /*v1005*/, s32 offset:3572 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v238 /*v1006*/, s32 offset:3576 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v239 /*v1007*/, s32 offset:3580 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v240 /*v1008*/, s32 offset:3584 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v241 /*v1009*/, s32 offset:3588 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v242 /*v1010*/, s32 offset:3592 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v243 /*v1011*/, s32 offset:3596 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v244 /*v1012*/, s32 offset:3600 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v245 /*v1013*/, s32 offset:3604 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v246 /*v1014*/, s32 offset:3608 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v247 /*v1015*/, s32 offset:3612 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v248 /*v1016*/, s32 offset:3616 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v249 /*v1017*/, s32 offset:3620 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v250 /*v1018*/, s32 offset:3624 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v251 /*v1019*/, s32 offset:3628 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v252 /*v1020*/, s32 offset:3632 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v253 /*v1021*/, s32 offset:3636 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v254 /*v1022*/, s32 offset:3640 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v255 /*v1023*/, s32 offset:3644 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; GFX1250-DAGISEL-NEXT:    v_mov_b32_e32 v2, v0
; GFX1250-DAGISEL-NEXT:    s_mov_b64 s[36:37], gfx_callee@abs64
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0xc00 ; msbs: dst=0 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    v_swap_b32 v0, v1
; GFX1250-DAGISEL-NEXT:    s_xor_b32 exec_lo, s0, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0, off, s32 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1, off, s32 offset:4 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v2, off, s32 offset:8 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v3, off, s32 offset:12 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v4, off, s32 offset:16 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v5, off, s32 offset:20 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v6, off, s32 offset:24 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v7, off, s32 offset:28 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v8, off, s32 offset:32 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v9, off, s32 offset:36 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v10, off, s32 offset:40 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v11, off, s32 offset:44 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v12, off, s32 offset:48 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v13, off, s32 offset:52 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v14, off, s32 offset:56 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v15, off, s32 offset:60 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v16, off, s32 offset:64 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v17, off, s32 offset:68 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v18, off, s32 offset:72 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v19, off, s32 offset:76 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v20, off, s32 offset:80 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v21, off, s32 offset:84 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v22, off, s32 offset:88 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v23, off, s32 offset:92 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v24, off, s32 offset:96 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v25, off, s32 offset:100 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v26, off, s32 offset:104 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v27, off, s32 offset:108 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v28, off, s32 offset:112 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v29, off, s32 offset:116 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v30, off, s32 offset:120 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v31, off, s32 offset:124 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v32, off, s32 offset:128 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v33, off, s32 offset:132 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v34, off, s32 offset:136 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v35, off, s32 offset:140 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v36, off, s32 offset:144 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v37, off, s32 offset:148 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v38, off, s32 offset:152 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v39, off, s32 offset:156 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v48, off, s32 offset:160 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v49, off, s32 offset:164 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v50, off, s32 offset:168 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v51, off, s32 offset:172 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v52, off, s32 offset:176 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v53, off, s32 offset:180 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v54, off, s32 offset:184 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v55, off, s32 offset:188 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v64, off, s32 offset:192 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v65, off, s32 offset:196 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v66, off, s32 offset:200 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v67, off, s32 offset:204 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v68, off, s32 offset:208 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v69, off, s32 offset:212 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v70, off, s32 offset:216 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v71, off, s32 offset:220 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v80, off, s32 offset:224 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v81, off, s32 offset:228 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v82, off, s32 offset:232 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v83, off, s32 offset:236 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v84, off, s32 offset:240 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v85, off, s32 offset:244 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v86, off, s32 offset:248 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v87, off, s32 offset:252 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v96, off, s32 offset:256 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v97, off, s32 offset:260 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v98, off, s32 offset:264 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v99, off, s32 offset:268 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v100, off, s32 offset:272 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v101, off, s32 offset:276 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v102, off, s32 offset:280 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v103, off, s32 offset:284 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v112, off, s32 offset:288 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v113, off, s32 offset:292 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v114, off, s32 offset:296 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v115, off, s32 offset:300 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v116, off, s32 offset:304 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v117, off, s32 offset:308 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v118, off, s32 offset:312 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v119, off, s32 offset:316 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v128, off, s32 offset:320 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v129, off, s32 offset:324 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v130, off, s32 offset:328 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v131, off, s32 offset:332 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v132, off, s32 offset:336 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v133, off, s32 offset:340 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v134, off, s32 offset:344 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v135, off, s32 offset:348 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v144, off, s32 offset:352 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v145, off, s32 offset:356 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v146, off, s32 offset:360 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v147, off, s32 offset:364 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v148, off, s32 offset:368 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v149, off, s32 offset:372 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v150, off, s32 offset:376 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v151, off, s32 offset:380 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v160, off, s32 offset:384 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v161, off, s32 offset:388 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v162, off, s32 offset:392 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v163, off, s32 offset:396 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v164, off, s32 offset:400 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v165, off, s32 offset:404 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v166, off, s32 offset:408 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v167, off, s32 offset:412 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v176, off, s32 offset:416 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v177, off, s32 offset:420 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v178, off, s32 offset:424 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v179, off, s32 offset:428 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v180, off, s32 offset:432 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v181, off, s32 offset:436 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v182, off, s32 offset:440 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v183, off, s32 offset:444 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v192, off, s32 offset:448 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v193, off, s32 offset:452 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v194, off, s32 offset:456 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v195, off, s32 offset:460 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v196, off, s32 offset:464 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v197, off, s32 offset:468 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v198, off, s32 offset:472 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v199, off, s32 offset:476 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v208, off, s32 offset:480 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v209, off, s32 offset:484 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v210, off, s32 offset:488 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v211, off, s32 offset:492 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v212, off, s32 offset:496 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v213, off, s32 offset:500 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v214, off, s32 offset:504 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v215, off, s32 offset:508 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v224, off, s32 offset:512 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v225, off, s32 offset:516 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v226, off, s32 offset:520 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v227, off, s32 offset:524 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v228, off, s32 offset:528 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v229, off, s32 offset:532 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v230, off, s32 offset:536 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v231, off, s32 offset:540 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v240, off, s32 offset:544 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v241, off, s32 offset:548 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v242, off, s32 offset:552 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v243, off, s32 offset:556 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v244, off, s32 offset:560 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v245, off, s32 offset:564 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v246, off, s32 offset:568 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v247, off, s32 offset:572 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 64 ; msbs: dst=1 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0 /*v256*/, off, s32 offset:576 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1 /*v257*/, off, s32 offset:580 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v2 /*v258*/, off, s32 offset:584 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v3 /*v259*/, off, s32 offset:588 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v4 /*v260*/, off, s32 offset:592 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v5 /*v261*/, off, s32 offset:596 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v6 /*v262*/, off, s32 offset:600 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v7 /*v263*/, off, s32 offset:604 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v8 /*v264*/, off, s32 offset:608 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v9 /*v265*/, off, s32 offset:612 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v10 /*v266*/, off, s32 offset:616 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v11 /*v267*/, off, s32 offset:620 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v12 /*v268*/, off, s32 offset:624 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v13 /*v269*/, off, s32 offset:628 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v14 /*v270*/, off, s32 offset:632 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v15 /*v271*/, off, s32 offset:636 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v16 /*v272*/, off, s32 offset:640 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v17 /*v273*/, off, s32 offset:644 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v18 /*v274*/, off, s32 offset:648 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v19 /*v275*/, off, s32 offset:652 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v20 /*v276*/, off, s32 offset:656 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v21 /*v277*/, off, s32 offset:660 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v22 /*v278*/, off, s32 offset:664 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v23 /*v279*/, off, s32 offset:668 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v24 /*v280*/, off, s32 offset:672 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v25 /*v281*/, off, s32 offset:676 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v26 /*v282*/, off, s32 offset:680 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v27 /*v283*/, off, s32 offset:684 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v28 /*v284*/, off, s32 offset:688 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v29 /*v285*/, off, s32 offset:692 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v30 /*v286*/, off, s32 offset:696 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v31 /*v287*/, off, s32 offset:700 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v32 /*v288*/, off, s32 offset:704 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v33 /*v289*/, off, s32 offset:708 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v34 /*v290*/, off, s32 offset:712 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v35 /*v291*/, off, s32 offset:716 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v36 /*v292*/, off, s32 offset:720 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v37 /*v293*/, off, s32 offset:724 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v38 /*v294*/, off, s32 offset:728 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v39 /*v295*/, off, s32 offset:732 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v40 /*v296*/, off, s32 offset:736 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v41 /*v297*/, off, s32 offset:740 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v42 /*v298*/, off, s32 offset:744 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v43 /*v299*/, off, s32 offset:748 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v44 /*v300*/, off, s32 offset:752 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v45 /*v301*/, off, s32 offset:756 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v46 /*v302*/, off, s32 offset:760 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v47 /*v303*/, off, s32 offset:764 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v48 /*v304*/, off, s32 offset:768 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v49 /*v305*/, off, s32 offset:772 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v50 /*v306*/, off, s32 offset:776 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v51 /*v307*/, off, s32 offset:780 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v52 /*v308*/, off, s32 offset:784 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v53 /*v309*/, off, s32 offset:788 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v54 /*v310*/, off, s32 offset:792 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v55 /*v311*/, off, s32 offset:796 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v56 /*v312*/, off, s32 offset:800 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v57 /*v313*/, off, s32 offset:804 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v58 /*v314*/, off, s32 offset:808 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v59 /*v315*/, off, s32 offset:812 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v60 /*v316*/, off, s32 offset:816 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v61 /*v317*/, off, s32 offset:820 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v62 /*v318*/, off, s32 offset:824 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v63 /*v319*/, off, s32 offset:828 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v64 /*v320*/, off, s32 offset:832 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v65 /*v321*/, off, s32 offset:836 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v66 /*v322*/, off, s32 offset:840 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v67 /*v323*/, off, s32 offset:844 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v68 /*v324*/, off, s32 offset:848 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v69 /*v325*/, off, s32 offset:852 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v70 /*v326*/, off, s32 offset:856 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v71 /*v327*/, off, s32 offset:860 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v72 /*v328*/, off, s32 offset:864 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v73 /*v329*/, off, s32 offset:868 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v74 /*v330*/, off, s32 offset:872 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v75 /*v331*/, off, s32 offset:876 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v76 /*v332*/, off, s32 offset:880 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v77 /*v333*/, off, s32 offset:884 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v78 /*v334*/, off, s32 offset:888 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v79 /*v335*/, off, s32 offset:892 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v80 /*v336*/, off, s32 offset:896 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v81 /*v337*/, off, s32 offset:900 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v82 /*v338*/, off, s32 offset:904 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v83 /*v339*/, off, s32 offset:908 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v84 /*v340*/, off, s32 offset:912 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v85 /*v341*/, off, s32 offset:916 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v86 /*v342*/, off, s32 offset:920 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v87 /*v343*/, off, s32 offset:924 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v88 /*v344*/, off, s32 offset:928 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v89 /*v345*/, off, s32 offset:932 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v90 /*v346*/, off, s32 offset:936 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v91 /*v347*/, off, s32 offset:940 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v92 /*v348*/, off, s32 offset:944 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v93 /*v349*/, off, s32 offset:948 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v94 /*v350*/, off, s32 offset:952 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v95 /*v351*/, off, s32 offset:956 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v96 /*v352*/, off, s32 offset:960 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v97 /*v353*/, off, s32 offset:964 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v98 /*v354*/, off, s32 offset:968 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v99 /*v355*/, off, s32 offset:972 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v100 /*v356*/, off, s32 offset:976 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v101 /*v357*/, off, s32 offset:980 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v102 /*v358*/, off, s32 offset:984 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v103 /*v359*/, off, s32 offset:988 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v104 /*v360*/, off, s32 offset:992 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v105 /*v361*/, off, s32 offset:996 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v106 /*v362*/, off, s32 offset:1000 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v107 /*v363*/, off, s32 offset:1004 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v108 /*v364*/, off, s32 offset:1008 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v109 /*v365*/, off, s32 offset:1012 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v110 /*v366*/, off, s32 offset:1016 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v111 /*v367*/, off, s32 offset:1020 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v112 /*v368*/, off, s32 offset:1024 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v113 /*v369*/, off, s32 offset:1028 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v114 /*v370*/, off, s32 offset:1032 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v115 /*v371*/, off, s32 offset:1036 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v116 /*v372*/, off, s32 offset:1040 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v117 /*v373*/, off, s32 offset:1044 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v118 /*v374*/, off, s32 offset:1048 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v119 /*v375*/, off, s32 offset:1052 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v120 /*v376*/, off, s32 offset:1056 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v121 /*v377*/, off, s32 offset:1060 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v122 /*v378*/, off, s32 offset:1064 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v123 /*v379*/, off, s32 offset:1068 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v124 /*v380*/, off, s32 offset:1072 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v125 /*v381*/, off, s32 offset:1076 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v126 /*v382*/, off, s32 offset:1080 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v127 /*v383*/, off, s32 offset:1084 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v128 /*v384*/, off, s32 offset:1088 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v129 /*v385*/, off, s32 offset:1092 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v130 /*v386*/, off, s32 offset:1096 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v131 /*v387*/, off, s32 offset:1100 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v132 /*v388*/, off, s32 offset:1104 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v133 /*v389*/, off, s32 offset:1108 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v134 /*v390*/, off, s32 offset:1112 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v135 /*v391*/, off, s32 offset:1116 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v136 /*v392*/, off, s32 offset:1120 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v137 /*v393*/, off, s32 offset:1124 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v138 /*v394*/, off, s32 offset:1128 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v139 /*v395*/, off, s32 offset:1132 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v140 /*v396*/, off, s32 offset:1136 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v141 /*v397*/, off, s32 offset:1140 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v142 /*v398*/, off, s32 offset:1144 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v143 /*v399*/, off, s32 offset:1148 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v144 /*v400*/, off, s32 offset:1152 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v145 /*v401*/, off, s32 offset:1156 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v146 /*v402*/, off, s32 offset:1160 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v147 /*v403*/, off, s32 offset:1164 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v148 /*v404*/, off, s32 offset:1168 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v149 /*v405*/, off, s32 offset:1172 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v150 /*v406*/, off, s32 offset:1176 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v151 /*v407*/, off, s32 offset:1180 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v152 /*v408*/, off, s32 offset:1184 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v153 /*v409*/, off, s32 offset:1188 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v154 /*v410*/, off, s32 offset:1192 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v155 /*v411*/, off, s32 offset:1196 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v156 /*v412*/, off, s32 offset:1200 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v157 /*v413*/, off, s32 offset:1204 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v158 /*v414*/, off, s32 offset:1208 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v159 /*v415*/, off, s32 offset:1212 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v160 /*v416*/, off, s32 offset:1216 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v161 /*v417*/, off, s32 offset:1220 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v162 /*v418*/, off, s32 offset:1224 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v163 /*v419*/, off, s32 offset:1228 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v164 /*v420*/, off, s32 offset:1232 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v165 /*v421*/, off, s32 offset:1236 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v166 /*v422*/, off, s32 offset:1240 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v167 /*v423*/, off, s32 offset:1244 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v168 /*v424*/, off, s32 offset:1248 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v169 /*v425*/, off, s32 offset:1252 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v170 /*v426*/, off, s32 offset:1256 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v171 /*v427*/, off, s32 offset:1260 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v172 /*v428*/, off, s32 offset:1264 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v173 /*v429*/, off, s32 offset:1268 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v174 /*v430*/, off, s32 offset:1272 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v175 /*v431*/, off, s32 offset:1276 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v176 /*v432*/, off, s32 offset:1280 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v177 /*v433*/, off, s32 offset:1284 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v178 /*v434*/, off, s32 offset:1288 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v179 /*v435*/, off, s32 offset:1292 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v180 /*v436*/, off, s32 offset:1296 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v181 /*v437*/, off, s32 offset:1300 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v182 /*v438*/, off, s32 offset:1304 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v183 /*v439*/, off, s32 offset:1308 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v184 /*v440*/, off, s32 offset:1312 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v185 /*v441*/, off, s32 offset:1316 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v186 /*v442*/, off, s32 offset:1320 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v187 /*v443*/, off, s32 offset:1324 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v188 /*v444*/, off, s32 offset:1328 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v189 /*v445*/, off, s32 offset:1332 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v190 /*v446*/, off, s32 offset:1336 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v191 /*v447*/, off, s32 offset:1340 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v192 /*v448*/, off, s32 offset:1344 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v193 /*v449*/, off, s32 offset:1348 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v194 /*v450*/, off, s32 offset:1352 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v195 /*v451*/, off, s32 offset:1356 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v196 /*v452*/, off, s32 offset:1360 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v197 /*v453*/, off, s32 offset:1364 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v198 /*v454*/, off, s32 offset:1368 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v199 /*v455*/, off, s32 offset:1372 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v200 /*v456*/, off, s32 offset:1376 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v201 /*v457*/, off, s32 offset:1380 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v202 /*v458*/, off, s32 offset:1384 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v203 /*v459*/, off, s32 offset:1388 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v204 /*v460*/, off, s32 offset:1392 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v205 /*v461*/, off, s32 offset:1396 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v206 /*v462*/, off, s32 offset:1400 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v207 /*v463*/, off, s32 offset:1404 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v208 /*v464*/, off, s32 offset:1408 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v209 /*v465*/, off, s32 offset:1412 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v210 /*v466*/, off, s32 offset:1416 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v211 /*v467*/, off, s32 offset:1420 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v212 /*v468*/, off, s32 offset:1424 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v213 /*v469*/, off, s32 offset:1428 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v214 /*v470*/, off, s32 offset:1432 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v215 /*v471*/, off, s32 offset:1436 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v216 /*v472*/, off, s32 offset:1440 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v217 /*v473*/, off, s32 offset:1444 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v218 /*v474*/, off, s32 offset:1448 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v219 /*v475*/, off, s32 offset:1452 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v220 /*v476*/, off, s32 offset:1456 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v221 /*v477*/, off, s32 offset:1460 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v222 /*v478*/, off, s32 offset:1464 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v223 /*v479*/, off, s32 offset:1468 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v224 /*v480*/, off, s32 offset:1472 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v225 /*v481*/, off, s32 offset:1476 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v226 /*v482*/, off, s32 offset:1480 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v227 /*v483*/, off, s32 offset:1484 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v228 /*v484*/, off, s32 offset:1488 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v229 /*v485*/, off, s32 offset:1492 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v230 /*v486*/, off, s32 offset:1496 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v231 /*v487*/, off, s32 offset:1500 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v232 /*v488*/, off, s32 offset:1504 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v233 /*v489*/, off, s32 offset:1508 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v234 /*v490*/, off, s32 offset:1512 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v235 /*v491*/, off, s32 offset:1516 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v236 /*v492*/, off, s32 offset:1520 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v237 /*v493*/, off, s32 offset:1524 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v238 /*v494*/, off, s32 offset:1528 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v239 /*v495*/, off, s32 offset:1532 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v240 /*v496*/, off, s32 offset:1536 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v241 /*v497*/, off, s32 offset:1540 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v242 /*v498*/, off, s32 offset:1544 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v243 /*v499*/, off, s32 offset:1548 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v244 /*v500*/, off, s32 offset:1552 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v245 /*v501*/, off, s32 offset:1556 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v246 /*v502*/, off, s32 offset:1560 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v247 /*v503*/, off, s32 offset:1564 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v248 /*v504*/, off, s32 offset:1568 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v249 /*v505*/, off, s32 offset:1572 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v250 /*v506*/, off, s32 offset:1576 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v251 /*v507*/, off, s32 offset:1580 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v252 /*v508*/, off, s32 offset:1584 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v253 /*v509*/, off, s32 offset:1588 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v254 /*v510*/, off, s32 offset:1592 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v255 /*v511*/, off, s32 offset:1596 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0x4080 ; msbs: dst=2 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0 /*v512*/, off, s32 offset:1600 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1 /*v513*/, off, s32 offset:1604 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v2 /*v514*/, off, s32 offset:1608 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v3 /*v515*/, off, s32 offset:1612 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v4 /*v516*/, off, s32 offset:1616 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v5 /*v517*/, off, s32 offset:1620 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v6 /*v518*/, off, s32 offset:1624 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v7 /*v519*/, off, s32 offset:1628 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v8 /*v520*/, off, s32 offset:1632 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v9 /*v521*/, off, s32 offset:1636 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v10 /*v522*/, off, s32 offset:1640 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v11 /*v523*/, off, s32 offset:1644 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v12 /*v524*/, off, s32 offset:1648 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v13 /*v525*/, off, s32 offset:1652 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v14 /*v526*/, off, s32 offset:1656 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v15 /*v527*/, off, s32 offset:1660 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v16 /*v528*/, off, s32 offset:1664 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v17 /*v529*/, off, s32 offset:1668 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v18 /*v530*/, off, s32 offset:1672 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v19 /*v531*/, off, s32 offset:1676 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v20 /*v532*/, off, s32 offset:1680 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v21 /*v533*/, off, s32 offset:1684 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v22 /*v534*/, off, s32 offset:1688 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v23 /*v535*/, off, s32 offset:1692 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v24 /*v536*/, off, s32 offset:1696 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v25 /*v537*/, off, s32 offset:1700 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v26 /*v538*/, off, s32 offset:1704 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v27 /*v539*/, off, s32 offset:1708 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v28 /*v540*/, off, s32 offset:1712 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v29 /*v541*/, off, s32 offset:1716 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v30 /*v542*/, off, s32 offset:1720 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v31 /*v543*/, off, s32 offset:1724 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v32 /*v544*/, off, s32 offset:1728 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v33 /*v545*/, off, s32 offset:1732 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v34 /*v546*/, off, s32 offset:1736 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v35 /*v547*/, off, s32 offset:1740 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v36 /*v548*/, off, s32 offset:1744 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v37 /*v549*/, off, s32 offset:1748 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v38 /*v550*/, off, s32 offset:1752 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v39 /*v551*/, off, s32 offset:1756 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v40 /*v552*/, off, s32 offset:1760 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v41 /*v553*/, off, s32 offset:1764 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v42 /*v554*/, off, s32 offset:1768 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v43 /*v555*/, off, s32 offset:1772 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v44 /*v556*/, off, s32 offset:1776 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v45 /*v557*/, off, s32 offset:1780 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v46 /*v558*/, off, s32 offset:1784 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v47 /*v559*/, off, s32 offset:1788 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v48 /*v560*/, off, s32 offset:1792 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v49 /*v561*/, off, s32 offset:1796 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v50 /*v562*/, off, s32 offset:1800 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v51 /*v563*/, off, s32 offset:1804 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v52 /*v564*/, off, s32 offset:1808 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v53 /*v565*/, off, s32 offset:1812 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v54 /*v566*/, off, s32 offset:1816 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v55 /*v567*/, off, s32 offset:1820 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v56 /*v568*/, off, s32 offset:1824 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v57 /*v569*/, off, s32 offset:1828 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v58 /*v570*/, off, s32 offset:1832 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v59 /*v571*/, off, s32 offset:1836 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v60 /*v572*/, off, s32 offset:1840 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v61 /*v573*/, off, s32 offset:1844 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v62 /*v574*/, off, s32 offset:1848 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v63 /*v575*/, off, s32 offset:1852 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v64 /*v576*/, off, s32 offset:1856 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v65 /*v577*/, off, s32 offset:1860 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v66 /*v578*/, off, s32 offset:1864 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v67 /*v579*/, off, s32 offset:1868 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v68 /*v580*/, off, s32 offset:1872 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v69 /*v581*/, off, s32 offset:1876 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v70 /*v582*/, off, s32 offset:1880 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v71 /*v583*/, off, s32 offset:1884 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v72 /*v584*/, off, s32 offset:1888 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v73 /*v585*/, off, s32 offset:1892 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v74 /*v586*/, off, s32 offset:1896 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v75 /*v587*/, off, s32 offset:1900 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v76 /*v588*/, off, s32 offset:1904 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v77 /*v589*/, off, s32 offset:1908 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v78 /*v590*/, off, s32 offset:1912 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v79 /*v591*/, off, s32 offset:1916 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v80 /*v592*/, off, s32 offset:1920 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v81 /*v593*/, off, s32 offset:1924 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v82 /*v594*/, off, s32 offset:1928 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v83 /*v595*/, off, s32 offset:1932 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v84 /*v596*/, off, s32 offset:1936 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v85 /*v597*/, off, s32 offset:1940 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v86 /*v598*/, off, s32 offset:1944 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v87 /*v599*/, off, s32 offset:1948 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v88 /*v600*/, off, s32 offset:1952 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v89 /*v601*/, off, s32 offset:1956 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v90 /*v602*/, off, s32 offset:1960 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v91 /*v603*/, off, s32 offset:1964 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v92 /*v604*/, off, s32 offset:1968 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v93 /*v605*/, off, s32 offset:1972 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v94 /*v606*/, off, s32 offset:1976 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v95 /*v607*/, off, s32 offset:1980 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v96 /*v608*/, off, s32 offset:1984 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v97 /*v609*/, off, s32 offset:1988 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v98 /*v610*/, off, s32 offset:1992 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v99 /*v611*/, off, s32 offset:1996 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v100 /*v612*/, off, s32 offset:2000 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v101 /*v613*/, off, s32 offset:2004 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v102 /*v614*/, off, s32 offset:2008 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v103 /*v615*/, off, s32 offset:2012 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v104 /*v616*/, off, s32 offset:2016 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v105 /*v617*/, off, s32 offset:2020 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v106 /*v618*/, off, s32 offset:2024 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v107 /*v619*/, off, s32 offset:2028 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v108 /*v620*/, off, s32 offset:2032 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v109 /*v621*/, off, s32 offset:2036 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v110 /*v622*/, off, s32 offset:2040 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v111 /*v623*/, off, s32 offset:2044 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v112 /*v624*/, off, s32 offset:2048 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v113 /*v625*/, off, s32 offset:2052 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v114 /*v626*/, off, s32 offset:2056 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v115 /*v627*/, off, s32 offset:2060 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v116 /*v628*/, off, s32 offset:2064 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v117 /*v629*/, off, s32 offset:2068 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v118 /*v630*/, off, s32 offset:2072 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v119 /*v631*/, off, s32 offset:2076 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v120 /*v632*/, off, s32 offset:2080 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v121 /*v633*/, off, s32 offset:2084 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v122 /*v634*/, off, s32 offset:2088 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v123 /*v635*/, off, s32 offset:2092 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v124 /*v636*/, off, s32 offset:2096 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v125 /*v637*/, off, s32 offset:2100 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v126 /*v638*/, off, s32 offset:2104 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v127 /*v639*/, off, s32 offset:2108 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v128 /*v640*/, off, s32 offset:2112 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v129 /*v641*/, off, s32 offset:2116 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v130 /*v642*/, off, s32 offset:2120 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v131 /*v643*/, off, s32 offset:2124 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v132 /*v644*/, off, s32 offset:2128 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v133 /*v645*/, off, s32 offset:2132 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v134 /*v646*/, off, s32 offset:2136 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v135 /*v647*/, off, s32 offset:2140 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v136 /*v648*/, off, s32 offset:2144 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v137 /*v649*/, off, s32 offset:2148 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v138 /*v650*/, off, s32 offset:2152 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v139 /*v651*/, off, s32 offset:2156 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v140 /*v652*/, off, s32 offset:2160 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v141 /*v653*/, off, s32 offset:2164 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v142 /*v654*/, off, s32 offset:2168 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v143 /*v655*/, off, s32 offset:2172 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v144 /*v656*/, off, s32 offset:2176 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v145 /*v657*/, off, s32 offset:2180 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v146 /*v658*/, off, s32 offset:2184 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v147 /*v659*/, off, s32 offset:2188 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v148 /*v660*/, off, s32 offset:2192 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v149 /*v661*/, off, s32 offset:2196 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v150 /*v662*/, off, s32 offset:2200 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v151 /*v663*/, off, s32 offset:2204 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v152 /*v664*/, off, s32 offset:2208 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v153 /*v665*/, off, s32 offset:2212 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v154 /*v666*/, off, s32 offset:2216 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v155 /*v667*/, off, s32 offset:2220 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v156 /*v668*/, off, s32 offset:2224 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v157 /*v669*/, off, s32 offset:2228 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v158 /*v670*/, off, s32 offset:2232 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v159 /*v671*/, off, s32 offset:2236 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v160 /*v672*/, off, s32 offset:2240 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v161 /*v673*/, off, s32 offset:2244 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v162 /*v674*/, off, s32 offset:2248 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v163 /*v675*/, off, s32 offset:2252 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v164 /*v676*/, off, s32 offset:2256 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v165 /*v677*/, off, s32 offset:2260 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v166 /*v678*/, off, s32 offset:2264 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v167 /*v679*/, off, s32 offset:2268 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v168 /*v680*/, off, s32 offset:2272 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v169 /*v681*/, off, s32 offset:2276 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v170 /*v682*/, off, s32 offset:2280 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v171 /*v683*/, off, s32 offset:2284 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v172 /*v684*/, off, s32 offset:2288 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v173 /*v685*/, off, s32 offset:2292 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v174 /*v686*/, off, s32 offset:2296 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v175 /*v687*/, off, s32 offset:2300 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v176 /*v688*/, off, s32 offset:2304 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v177 /*v689*/, off, s32 offset:2308 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v178 /*v690*/, off, s32 offset:2312 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v179 /*v691*/, off, s32 offset:2316 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v180 /*v692*/, off, s32 offset:2320 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v181 /*v693*/, off, s32 offset:2324 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v182 /*v694*/, off, s32 offset:2328 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v183 /*v695*/, off, s32 offset:2332 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v184 /*v696*/, off, s32 offset:2336 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v185 /*v697*/, off, s32 offset:2340 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v186 /*v698*/, off, s32 offset:2344 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v187 /*v699*/, off, s32 offset:2348 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v188 /*v700*/, off, s32 offset:2352 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v189 /*v701*/, off, s32 offset:2356 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v190 /*v702*/, off, s32 offset:2360 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v191 /*v703*/, off, s32 offset:2364 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v192 /*v704*/, off, s32 offset:2368 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v193 /*v705*/, off, s32 offset:2372 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v194 /*v706*/, off, s32 offset:2376 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v195 /*v707*/, off, s32 offset:2380 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v196 /*v708*/, off, s32 offset:2384 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v197 /*v709*/, off, s32 offset:2388 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v198 /*v710*/, off, s32 offset:2392 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v199 /*v711*/, off, s32 offset:2396 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v200 /*v712*/, off, s32 offset:2400 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v201 /*v713*/, off, s32 offset:2404 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v202 /*v714*/, off, s32 offset:2408 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v203 /*v715*/, off, s32 offset:2412 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v204 /*v716*/, off, s32 offset:2416 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v205 /*v717*/, off, s32 offset:2420 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v206 /*v718*/, off, s32 offset:2424 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v207 /*v719*/, off, s32 offset:2428 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v208 /*v720*/, off, s32 offset:2432 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v209 /*v721*/, off, s32 offset:2436 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v210 /*v722*/, off, s32 offset:2440 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v211 /*v723*/, off, s32 offset:2444 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v212 /*v724*/, off, s32 offset:2448 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v213 /*v725*/, off, s32 offset:2452 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v214 /*v726*/, off, s32 offset:2456 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v215 /*v727*/, off, s32 offset:2460 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v216 /*v728*/, off, s32 offset:2464 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v217 /*v729*/, off, s32 offset:2468 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v218 /*v730*/, off, s32 offset:2472 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v219 /*v731*/, off, s32 offset:2476 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v220 /*v732*/, off, s32 offset:2480 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v221 /*v733*/, off, s32 offset:2484 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v222 /*v734*/, off, s32 offset:2488 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v223 /*v735*/, off, s32 offset:2492 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v224 /*v736*/, off, s32 offset:2496 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v225 /*v737*/, off, s32 offset:2500 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v226 /*v738*/, off, s32 offset:2504 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v227 /*v739*/, off, s32 offset:2508 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v228 /*v740*/, off, s32 offset:2512 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v229 /*v741*/, off, s32 offset:2516 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v230 /*v742*/, off, s32 offset:2520 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v231 /*v743*/, off, s32 offset:2524 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v232 /*v744*/, off, s32 offset:2528 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v233 /*v745*/, off, s32 offset:2532 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v234 /*v746*/, off, s32 offset:2536 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v235 /*v747*/, off, s32 offset:2540 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v236 /*v748*/, off, s32 offset:2544 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v237 /*v749*/, off, s32 offset:2548 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v238 /*v750*/, off, s32 offset:2552 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v239 /*v751*/, off, s32 offset:2556 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v240 /*v752*/, off, s32 offset:2560 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v241 /*v753*/, off, s32 offset:2564 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v242 /*v754*/, off, s32 offset:2568 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v243 /*v755*/, off, s32 offset:2572 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v244 /*v756*/, off, s32 offset:2576 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v245 /*v757*/, off, s32 offset:2580 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v246 /*v758*/, off, s32 offset:2584 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v247 /*v759*/, off, s32 offset:2588 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v248 /*v760*/, off, s32 offset:2592 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v249 /*v761*/, off, s32 offset:2596 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v250 /*v762*/, off, s32 offset:2600 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v251 /*v763*/, off, s32 offset:2604 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v252 /*v764*/, off, s32 offset:2608 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v253 /*v765*/, off, s32 offset:2612 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v254 /*v766*/, off, s32 offset:2616 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v255 /*v767*/, off, s32 offset:2620 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0x80c0 ; msbs: dst=3 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0 /*v768*/, off, s32 offset:2624 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1 /*v769*/, off, s32 offset:2628 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v2 /*v770*/, off, s32 offset:2632 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v3 /*v771*/, off, s32 offset:2636 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v4 /*v772*/, off, s32 offset:2640 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v5 /*v773*/, off, s32 offset:2644 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v6 /*v774*/, off, s32 offset:2648 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v7 /*v775*/, off, s32 offset:2652 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v8 /*v776*/, off, s32 offset:2656 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v9 /*v777*/, off, s32 offset:2660 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v10 /*v778*/, off, s32 offset:2664 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v11 /*v779*/, off, s32 offset:2668 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v12 /*v780*/, off, s32 offset:2672 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v13 /*v781*/, off, s32 offset:2676 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v14 /*v782*/, off, s32 offset:2680 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v15 /*v783*/, off, s32 offset:2684 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v16 /*v784*/, off, s32 offset:2688 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v17 /*v785*/, off, s32 offset:2692 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v18 /*v786*/, off, s32 offset:2696 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v19 /*v787*/, off, s32 offset:2700 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v20 /*v788*/, off, s32 offset:2704 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v21 /*v789*/, off, s32 offset:2708 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v22 /*v790*/, off, s32 offset:2712 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v23 /*v791*/, off, s32 offset:2716 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v24 /*v792*/, off, s32 offset:2720 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v25 /*v793*/, off, s32 offset:2724 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v26 /*v794*/, off, s32 offset:2728 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v27 /*v795*/, off, s32 offset:2732 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v28 /*v796*/, off, s32 offset:2736 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v29 /*v797*/, off, s32 offset:2740 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v30 /*v798*/, off, s32 offset:2744 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v31 /*v799*/, off, s32 offset:2748 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v32 /*v800*/, off, s32 offset:2752 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v33 /*v801*/, off, s32 offset:2756 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v34 /*v802*/, off, s32 offset:2760 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v35 /*v803*/, off, s32 offset:2764 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v36 /*v804*/, off, s32 offset:2768 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v37 /*v805*/, off, s32 offset:2772 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v38 /*v806*/, off, s32 offset:2776 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v39 /*v807*/, off, s32 offset:2780 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v40 /*v808*/, off, s32 offset:2784 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v41 /*v809*/, off, s32 offset:2788 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v42 /*v810*/, off, s32 offset:2792 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v43 /*v811*/, off, s32 offset:2796 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v44 /*v812*/, off, s32 offset:2800 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v45 /*v813*/, off, s32 offset:2804 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v46 /*v814*/, off, s32 offset:2808 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v47 /*v815*/, off, s32 offset:2812 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v48 /*v816*/, off, s32 offset:2816 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v49 /*v817*/, off, s32 offset:2820 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v50 /*v818*/, off, s32 offset:2824 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v51 /*v819*/, off, s32 offset:2828 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v52 /*v820*/, off, s32 offset:2832 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v53 /*v821*/, off, s32 offset:2836 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v54 /*v822*/, off, s32 offset:2840 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v55 /*v823*/, off, s32 offset:2844 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v56 /*v824*/, off, s32 offset:2848 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v57 /*v825*/, off, s32 offset:2852 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v58 /*v826*/, off, s32 offset:2856 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v59 /*v827*/, off, s32 offset:2860 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v60 /*v828*/, off, s32 offset:2864 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v61 /*v829*/, off, s32 offset:2868 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v62 /*v830*/, off, s32 offset:2872 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v63 /*v831*/, off, s32 offset:2876 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v64 /*v832*/, off, s32 offset:2880 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v65 /*v833*/, off, s32 offset:2884 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v66 /*v834*/, off, s32 offset:2888 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v67 /*v835*/, off, s32 offset:2892 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v68 /*v836*/, off, s32 offset:2896 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v69 /*v837*/, off, s32 offset:2900 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v70 /*v838*/, off, s32 offset:2904 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v71 /*v839*/, off, s32 offset:2908 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v72 /*v840*/, off, s32 offset:2912 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v73 /*v841*/, off, s32 offset:2916 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v74 /*v842*/, off, s32 offset:2920 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v75 /*v843*/, off, s32 offset:2924 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v76 /*v844*/, off, s32 offset:2928 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v77 /*v845*/, off, s32 offset:2932 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v78 /*v846*/, off, s32 offset:2936 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v79 /*v847*/, off, s32 offset:2940 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v80 /*v848*/, off, s32 offset:2944 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v81 /*v849*/, off, s32 offset:2948 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v82 /*v850*/, off, s32 offset:2952 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v83 /*v851*/, off, s32 offset:2956 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v84 /*v852*/, off, s32 offset:2960 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v85 /*v853*/, off, s32 offset:2964 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v86 /*v854*/, off, s32 offset:2968 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v87 /*v855*/, off, s32 offset:2972 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v88 /*v856*/, off, s32 offset:2976 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v89 /*v857*/, off, s32 offset:2980 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v90 /*v858*/, off, s32 offset:2984 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v91 /*v859*/, off, s32 offset:2988 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v92 /*v860*/, off, s32 offset:2992 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v93 /*v861*/, off, s32 offset:2996 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v94 /*v862*/, off, s32 offset:3000 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v95 /*v863*/, off, s32 offset:3004 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v96 /*v864*/, off, s32 offset:3008 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v97 /*v865*/, off, s32 offset:3012 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v98 /*v866*/, off, s32 offset:3016 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v99 /*v867*/, off, s32 offset:3020 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v100 /*v868*/, off, s32 offset:3024 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v101 /*v869*/, off, s32 offset:3028 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v102 /*v870*/, off, s32 offset:3032 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v103 /*v871*/, off, s32 offset:3036 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v104 /*v872*/, off, s32 offset:3040 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v105 /*v873*/, off, s32 offset:3044 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v106 /*v874*/, off, s32 offset:3048 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v107 /*v875*/, off, s32 offset:3052 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v108 /*v876*/, off, s32 offset:3056 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v109 /*v877*/, off, s32 offset:3060 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v110 /*v878*/, off, s32 offset:3064 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v111 /*v879*/, off, s32 offset:3068 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v112 /*v880*/, off, s32 offset:3072 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v113 /*v881*/, off, s32 offset:3076 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v114 /*v882*/, off, s32 offset:3080 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v115 /*v883*/, off, s32 offset:3084 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v116 /*v884*/, off, s32 offset:3088 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v117 /*v885*/, off, s32 offset:3092 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v118 /*v886*/, off, s32 offset:3096 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v119 /*v887*/, off, s32 offset:3100 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v120 /*v888*/, off, s32 offset:3104 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v121 /*v889*/, off, s32 offset:3108 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v122 /*v890*/, off, s32 offset:3112 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v123 /*v891*/, off, s32 offset:3116 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v124 /*v892*/, off, s32 offset:3120 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v125 /*v893*/, off, s32 offset:3124 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v126 /*v894*/, off, s32 offset:3128 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v127 /*v895*/, off, s32 offset:3132 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v128 /*v896*/, off, s32 offset:3136 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v129 /*v897*/, off, s32 offset:3140 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v130 /*v898*/, off, s32 offset:3144 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v131 /*v899*/, off, s32 offset:3148 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v132 /*v900*/, off, s32 offset:3152 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v133 /*v901*/, off, s32 offset:3156 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v134 /*v902*/, off, s32 offset:3160 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v135 /*v903*/, off, s32 offset:3164 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v136 /*v904*/, off, s32 offset:3168 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v137 /*v905*/, off, s32 offset:3172 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v138 /*v906*/, off, s32 offset:3176 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v139 /*v907*/, off, s32 offset:3180 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v140 /*v908*/, off, s32 offset:3184 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v141 /*v909*/, off, s32 offset:3188 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v142 /*v910*/, off, s32 offset:3192 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v143 /*v911*/, off, s32 offset:3196 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v144 /*v912*/, off, s32 offset:3200 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v145 /*v913*/, off, s32 offset:3204 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v146 /*v914*/, off, s32 offset:3208 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v147 /*v915*/, off, s32 offset:3212 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v148 /*v916*/, off, s32 offset:3216 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v149 /*v917*/, off, s32 offset:3220 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v150 /*v918*/, off, s32 offset:3224 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v151 /*v919*/, off, s32 offset:3228 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v152 /*v920*/, off, s32 offset:3232 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v153 /*v921*/, off, s32 offset:3236 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v154 /*v922*/, off, s32 offset:3240 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v155 /*v923*/, off, s32 offset:3244 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v156 /*v924*/, off, s32 offset:3248 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v157 /*v925*/, off, s32 offset:3252 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v158 /*v926*/, off, s32 offset:3256 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v159 /*v927*/, off, s32 offset:3260 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v160 /*v928*/, off, s32 offset:3264 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v161 /*v929*/, off, s32 offset:3268 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v162 /*v930*/, off, s32 offset:3272 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v163 /*v931*/, off, s32 offset:3276 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v164 /*v932*/, off, s32 offset:3280 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v165 /*v933*/, off, s32 offset:3284 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v166 /*v934*/, off, s32 offset:3288 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v167 /*v935*/, off, s32 offset:3292 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v168 /*v936*/, off, s32 offset:3296 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v169 /*v937*/, off, s32 offset:3300 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v170 /*v938*/, off, s32 offset:3304 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v171 /*v939*/, off, s32 offset:3308 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v172 /*v940*/, off, s32 offset:3312 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v173 /*v941*/, off, s32 offset:3316 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v174 /*v942*/, off, s32 offset:3320 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v175 /*v943*/, off, s32 offset:3324 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v176 /*v944*/, off, s32 offset:3328 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v177 /*v945*/, off, s32 offset:3332 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v178 /*v946*/, off, s32 offset:3336 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v179 /*v947*/, off, s32 offset:3340 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v180 /*v948*/, off, s32 offset:3344 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v181 /*v949*/, off, s32 offset:3348 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v182 /*v950*/, off, s32 offset:3352 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v183 /*v951*/, off, s32 offset:3356 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v184 /*v952*/, off, s32 offset:3360 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v185 /*v953*/, off, s32 offset:3364 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v186 /*v954*/, off, s32 offset:3368 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v187 /*v955*/, off, s32 offset:3372 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v188 /*v956*/, off, s32 offset:3376 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v189 /*v957*/, off, s32 offset:3380 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v190 /*v958*/, off, s32 offset:3384 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v191 /*v959*/, off, s32 offset:3388 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v192 /*v960*/, off, s32 offset:3392 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v193 /*v961*/, off, s32 offset:3396 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v194 /*v962*/, off, s32 offset:3400 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v195 /*v963*/, off, s32 offset:3404 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v196 /*v964*/, off, s32 offset:3408 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v197 /*v965*/, off, s32 offset:3412 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v198 /*v966*/, off, s32 offset:3416 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v199 /*v967*/, off, s32 offset:3420 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v200 /*v968*/, off, s32 offset:3424 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v201 /*v969*/, off, s32 offset:3428 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v202 /*v970*/, off, s32 offset:3432 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v203 /*v971*/, off, s32 offset:3436 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v204 /*v972*/, off, s32 offset:3440 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v205 /*v973*/, off, s32 offset:3444 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v206 /*v974*/, off, s32 offset:3448 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v207 /*v975*/, off, s32 offset:3452 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v208 /*v976*/, off, s32 offset:3456 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v209 /*v977*/, off, s32 offset:3460 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v210 /*v978*/, off, s32 offset:3464 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v211 /*v979*/, off, s32 offset:3468 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v212 /*v980*/, off, s32 offset:3472 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v213 /*v981*/, off, s32 offset:3476 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v214 /*v982*/, off, s32 offset:3480 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v215 /*v983*/, off, s32 offset:3484 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v216 /*v984*/, off, s32 offset:3488 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v217 /*v985*/, off, s32 offset:3492 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v218 /*v986*/, off, s32 offset:3496 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v219 /*v987*/, off, s32 offset:3500 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v220 /*v988*/, off, s32 offset:3504 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v221 /*v989*/, off, s32 offset:3508 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v222 /*v990*/, off, s32 offset:3512 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v223 /*v991*/, off, s32 offset:3516 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v224 /*v992*/, off, s32 offset:3520 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v225 /*v993*/, off, s32 offset:3524 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x1d ; 120-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v226 /*v994*/, off, s32 offset:3528 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v227 /*v995*/, off, s32 offset:3532 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v228 /*v996*/, off, s32 offset:3536 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v229 /*v997*/, off, s32 offset:3540 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v230 /*v998*/, off, s32 offset:3544 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v231 /*v999*/, off, s32 offset:3548 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v232 /*v1000*/, off, s32 offset:3552 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v233 /*v1001*/, off, s32 offset:3556 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v234 /*v1002*/, off, s32 offset:3560 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v235 /*v1003*/, off, s32 offset:3564 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v236 /*v1004*/, off, s32 offset:3568 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v237 /*v1005*/, off, s32 offset:3572 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v238 /*v1006*/, off, s32 offset:3576 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v239 /*v1007*/, off, s32 offset:3580 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v240 /*v1008*/, off, s32 offset:3584 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v241 /*v1009*/, off, s32 offset:3588 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v242 /*v1010*/, off, s32 offset:3592 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v243 /*v1011*/, off, s32 offset:3596 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v244 /*v1012*/, off, s32 offset:3600 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v245 /*v1013*/, off, s32 offset:3604 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v246 /*v1014*/, off, s32 offset:3608 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v247 /*v1015*/, off, s32 offset:3612 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v248 /*v1016*/, off, s32 offset:3616 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v249 /*v1017*/, off, s32 offset:3620 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v250 /*v1018*/, off, s32 offset:3624 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v251 /*v1019*/, off, s32 offset:3628 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v252 /*v1020*/, off, s32 offset:3632 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v253 /*v1021*/, off, s32 offset:3636 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v254 /*v1022*/, off, s32 offset:3640 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v255 /*v1023*/, off, s32 offset:3644 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0xc000 ; msbs: dst=0 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    s_set_pc_i64 s[36:37]
  %ret = tail call amdgpu_gfx <2 x half>(<2 x half>, <2 x half>) @gfx_callee(<2 x half> %y, <2 x half> %x) convergent
  ret <2 x half> %ret
}

declare amdgpu_gfx_whole_wave float @callee(i1 %active, <8 x float> %x)

define amdgpu_cs void @call_from_entry(<8 x float> %x, ptr %p) #0 {
; DAGISEL-LABEL: call_from_entry:
; DAGISEL:       ; %bb.0:
; DAGISEL-NEXT:    s_mov_b32 s1, callee@abs32@hi
; DAGISEL-NEXT:    s_mov_b32 s0, callee@abs32@lo
; DAGISEL-NEXT:    s_mov_b32 s32, 0
; DAGISEL-NEXT:    v_dual_mov_b32 v41, v9 :: v_dual_mov_b32 v40, v8
; DAGISEL-NEXT:    s_swappc_b64 s[30:31], s[0:1]
; DAGISEL-NEXT:    flat_store_b32 v[40:41], v0
; DAGISEL-NEXT:    s_endpgm
;
; GISEL-LABEL: call_from_entry:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_mov_b32 s0, callee@abs32@lo
; GISEL-NEXT:    s_mov_b32 s1, callee@abs32@hi
; GISEL-NEXT:    s_mov_b32 s32, 0
; GISEL-NEXT:    v_dual_mov_b32 v40, v8 :: v_dual_mov_b32 v41, v9
; GISEL-NEXT:    s_swappc_b64 s[30:31], s[0:1]
; GISEL-NEXT:    flat_store_b32 v[40:41], v0
; GISEL-NEXT:    s_endpgm
;
; DAGISEL64-LABEL: call_from_entry:
; DAGISEL64:       ; %bb.0:
; DAGISEL64-NEXT:    s_mov_b32 s1, callee@abs32@hi
; DAGISEL64-NEXT:    s_mov_b32 s0, callee@abs32@lo
; DAGISEL64-NEXT:    s_mov_b32 s32, 0
; DAGISEL64-NEXT:    v_mov_b32_e32 v41, v9
; DAGISEL64-NEXT:    v_mov_b32_e32 v40, v8
; DAGISEL64-NEXT:    s_swappc_b64 s[30:31], s[0:1]
; DAGISEL64-NEXT:    flat_store_b32 v[40:41], v0
; DAGISEL64-NEXT:    s_endpgm
;
; GISEL64-LABEL: call_from_entry:
; GISEL64:       ; %bb.0:
; GISEL64-NEXT:    s_mov_b32 s0, callee@abs32@lo
; GISEL64-NEXT:    s_mov_b32 s1, callee@abs32@hi
; GISEL64-NEXT:    s_mov_b32 s32, 0
; GISEL64-NEXT:    v_mov_b32_e32 v40, v8
; GISEL64-NEXT:    v_mov_b32_e32 v41, v9
; GISEL64-NEXT:    s_swappc_b64 s[30:31], s[0:1]
; GISEL64-NEXT:    flat_store_b32 v[40:41], v0
; GISEL64-NEXT:    s_endpgm
;
; GFX1250-DAGISEL-LABEL: call_from_entry:
; GFX1250-DAGISEL:       ; %bb.0:
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s32, 0
; GFX1250-DAGISEL-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    s_mov_b64 s[0:1], callee@abs64
; GFX1250-DAGISEL-NEXT:    v_dual_mov_b32 v41, v9 :: v_dual_mov_b32 v40, v8
; GFX1250-DAGISEL-NEXT:    s_swap_pc_i64 s[30:31], s[0:1]
; GFX1250-DAGISEL-NEXT:    flat_store_b32 v[40:41], v0
; GFX1250-DAGISEL-NEXT:    s_endpgm
  %ret = call float(ptr, ...) @llvm.amdgcn.call.whole.wave(ptr @callee, <8 x float> %x) convergent
  store float %ret, ptr %p
  ret void
}

define amdgpu_gfx_whole_wave void @call_from_whole_wave(i1 %unused, <8 x float> %x, ptr %p) #0 {
; DAGISEL-LABEL: call_from_whole_wave:
; DAGISEL:       ; %bb.0:
; DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL-NEXT:    s_wait_expcnt 0x0
; DAGISEL-NEXT:    s_wait_samplecnt 0x0
; DAGISEL-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL-NEXT:    s_wait_kmcnt 0x0
; DAGISEL-NEXT:    s_mov_b32 s0, s33
; DAGISEL-NEXT:    s_mov_b32 s33, s32
; DAGISEL-NEXT:    s_xor_saveexec_b32 s4, -1
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v0, s33 offset:4
; DAGISEL-NEXT:    scratch_store_b32 off, v1, s33 offset:8
; DAGISEL-NEXT:    scratch_store_b32 off, v2, s33 offset:12
; DAGISEL-NEXT:    scratch_store_b32 off, v3, s33 offset:16
; DAGISEL-NEXT:    scratch_store_b32 off, v4, s33 offset:20
; DAGISEL-NEXT:    scratch_store_b32 off, v5, s33 offset:24
; DAGISEL-NEXT:    scratch_store_b32 off, v6, s33 offset:28
; DAGISEL-NEXT:    scratch_store_b32 off, v7, s33 offset:32
; DAGISEL-NEXT:    scratch_store_b32 off, v8, s33 offset:36
; DAGISEL-NEXT:    scratch_store_b32 off, v9, s33 offset:40
; DAGISEL-NEXT:    scratch_store_b32 off, v10, s33 offset:44
; DAGISEL-NEXT:    scratch_store_b32 off, v11, s33 offset:48
; DAGISEL-NEXT:    scratch_store_b32 off, v12, s33 offset:52
; DAGISEL-NEXT:    scratch_store_b32 off, v13, s33 offset:56
; DAGISEL-NEXT:    scratch_store_b32 off, v14, s33 offset:60
; DAGISEL-NEXT:    scratch_store_b32 off, v15, s33 offset:64
; DAGISEL-NEXT:    scratch_store_b32 off, v16, s33 offset:68
; DAGISEL-NEXT:    scratch_store_b32 off, v17, s33 offset:72
; DAGISEL-NEXT:    scratch_store_b32 off, v18, s33 offset:76
; DAGISEL-NEXT:    scratch_store_b32 off, v19, s33 offset:80
; DAGISEL-NEXT:    scratch_store_b32 off, v20, s33 offset:84
; DAGISEL-NEXT:    scratch_store_b32 off, v21, s33 offset:88
; DAGISEL-NEXT:    scratch_store_b32 off, v22, s33 offset:92
; DAGISEL-NEXT:    scratch_store_b32 off, v23, s33 offset:96
; DAGISEL-NEXT:    scratch_store_b32 off, v24, s33 offset:100
; DAGISEL-NEXT:    scratch_store_b32 off, v25, s33 offset:104
; DAGISEL-NEXT:    scratch_store_b32 off, v26, s33 offset:108
; DAGISEL-NEXT:    scratch_store_b32 off, v27, s33 offset:112
; DAGISEL-NEXT:    scratch_store_b32 off, v28, s33 offset:116
; DAGISEL-NEXT:    scratch_store_b32 off, v29, s33 offset:120
; DAGISEL-NEXT:    scratch_store_b32 off, v30, s33 offset:124
; DAGISEL-NEXT:    scratch_store_b32 off, v31, s33 offset:128
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v32, s33 offset:132
; DAGISEL-NEXT:    scratch_store_b32 off, v33, s33 offset:136
; DAGISEL-NEXT:    scratch_store_b32 off, v34, s33 offset:140
; DAGISEL-NEXT:    scratch_store_b32 off, v35, s33 offset:144
; DAGISEL-NEXT:    scratch_store_b32 off, v36, s33 offset:148
; DAGISEL-NEXT:    scratch_store_b32 off, v37, s33 offset:152
; DAGISEL-NEXT:    scratch_store_b32 off, v38, s33 offset:156
; DAGISEL-NEXT:    scratch_store_b32 off, v39, s33 offset:160
; DAGISEL-NEXT:    scratch_store_b32 off, v48, s33 offset:172
; DAGISEL-NEXT:    scratch_store_b32 off, v49, s33 offset:176
; DAGISEL-NEXT:    scratch_store_b32 off, v50, s33 offset:180
; DAGISEL-NEXT:    scratch_store_b32 off, v51, s33 offset:184
; DAGISEL-NEXT:    scratch_store_b32 off, v52, s33 offset:188
; DAGISEL-NEXT:    scratch_store_b32 off, v53, s33 offset:192
; DAGISEL-NEXT:    scratch_store_b32 off, v54, s33 offset:196
; DAGISEL-NEXT:    scratch_store_b32 off, v55, s33 offset:200
; DAGISEL-NEXT:    scratch_store_b32 off, v64, s33 offset:204
; DAGISEL-NEXT:    scratch_store_b32 off, v65, s33 offset:208
; DAGISEL-NEXT:    scratch_store_b32 off, v66, s33 offset:212
; DAGISEL-NEXT:    scratch_store_b32 off, v67, s33 offset:216
; DAGISEL-NEXT:    scratch_store_b32 off, v68, s33 offset:220
; DAGISEL-NEXT:    scratch_store_b32 off, v69, s33 offset:224
; DAGISEL-NEXT:    scratch_store_b32 off, v70, s33 offset:228
; DAGISEL-NEXT:    scratch_store_b32 off, v71, s33 offset:232
; DAGISEL-NEXT:    scratch_store_b32 off, v80, s33 offset:236
; DAGISEL-NEXT:    scratch_store_b32 off, v81, s33 offset:240
; DAGISEL-NEXT:    scratch_store_b32 off, v82, s33 offset:244
; DAGISEL-NEXT:    scratch_store_b32 off, v83, s33 offset:248
; DAGISEL-NEXT:    scratch_store_b32 off, v84, s33 offset:252
; DAGISEL-NEXT:    scratch_store_b32 off, v85, s33 offset:256
; DAGISEL-NEXT:    scratch_store_b32 off, v86, s33 offset:260
; DAGISEL-NEXT:    scratch_store_b32 off, v87, s33 offset:264
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v96, s33 offset:268
; DAGISEL-NEXT:    scratch_store_b32 off, v97, s33 offset:272
; DAGISEL-NEXT:    scratch_store_b32 off, v98, s33 offset:276
; DAGISEL-NEXT:    scratch_store_b32 off, v99, s33 offset:280
; DAGISEL-NEXT:    scratch_store_b32 off, v100, s33 offset:284
; DAGISEL-NEXT:    scratch_store_b32 off, v101, s33 offset:288
; DAGISEL-NEXT:    scratch_store_b32 off, v102, s33 offset:292
; DAGISEL-NEXT:    scratch_store_b32 off, v103, s33 offset:296
; DAGISEL-NEXT:    scratch_store_b32 off, v112, s33 offset:300
; DAGISEL-NEXT:    scratch_store_b32 off, v113, s33 offset:304
; DAGISEL-NEXT:    scratch_store_b32 off, v114, s33 offset:308
; DAGISEL-NEXT:    scratch_store_b32 off, v115, s33 offset:312
; DAGISEL-NEXT:    scratch_store_b32 off, v116, s33 offset:316
; DAGISEL-NEXT:    scratch_store_b32 off, v117, s33 offset:320
; DAGISEL-NEXT:    scratch_store_b32 off, v118, s33 offset:324
; DAGISEL-NEXT:    scratch_store_b32 off, v119, s33 offset:328
; DAGISEL-NEXT:    scratch_store_b32 off, v128, s33 offset:332
; DAGISEL-NEXT:    scratch_store_b32 off, v129, s33 offset:336
; DAGISEL-NEXT:    scratch_store_b32 off, v130, s33 offset:340
; DAGISEL-NEXT:    scratch_store_b32 off, v131, s33 offset:344
; DAGISEL-NEXT:    scratch_store_b32 off, v132, s33 offset:348
; DAGISEL-NEXT:    scratch_store_b32 off, v133, s33 offset:352
; DAGISEL-NEXT:    scratch_store_b32 off, v134, s33 offset:356
; DAGISEL-NEXT:    scratch_store_b32 off, v135, s33 offset:360
; DAGISEL-NEXT:    scratch_store_b32 off, v144, s33 offset:364
; DAGISEL-NEXT:    scratch_store_b32 off, v145, s33 offset:368
; DAGISEL-NEXT:    scratch_store_b32 off, v146, s33 offset:372
; DAGISEL-NEXT:    scratch_store_b32 off, v147, s33 offset:376
; DAGISEL-NEXT:    scratch_store_b32 off, v148, s33 offset:380
; DAGISEL-NEXT:    scratch_store_b32 off, v149, s33 offset:384
; DAGISEL-NEXT:    scratch_store_b32 off, v150, s33 offset:388
; DAGISEL-NEXT:    scratch_store_b32 off, v151, s33 offset:392
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v160, s33 offset:396
; DAGISEL-NEXT:    scratch_store_b32 off, v161, s33 offset:400
; DAGISEL-NEXT:    scratch_store_b32 off, v162, s33 offset:404
; DAGISEL-NEXT:    scratch_store_b32 off, v163, s33 offset:408
; DAGISEL-NEXT:    scratch_store_b32 off, v164, s33 offset:412
; DAGISEL-NEXT:    scratch_store_b32 off, v165, s33 offset:416
; DAGISEL-NEXT:    scratch_store_b32 off, v166, s33 offset:420
; DAGISEL-NEXT:    scratch_store_b32 off, v167, s33 offset:424
; DAGISEL-NEXT:    scratch_store_b32 off, v176, s33 offset:428
; DAGISEL-NEXT:    scratch_store_b32 off, v177, s33 offset:432
; DAGISEL-NEXT:    scratch_store_b32 off, v178, s33 offset:436
; DAGISEL-NEXT:    scratch_store_b32 off, v179, s33 offset:440
; DAGISEL-NEXT:    scratch_store_b32 off, v180, s33 offset:444
; DAGISEL-NEXT:    scratch_store_b32 off, v181, s33 offset:448
; DAGISEL-NEXT:    scratch_store_b32 off, v182, s33 offset:452
; DAGISEL-NEXT:    scratch_store_b32 off, v183, s33 offset:456
; DAGISEL-NEXT:    scratch_store_b32 off, v192, s33 offset:460
; DAGISEL-NEXT:    scratch_store_b32 off, v193, s33 offset:464
; DAGISEL-NEXT:    scratch_store_b32 off, v194, s33 offset:468
; DAGISEL-NEXT:    scratch_store_b32 off, v195, s33 offset:472
; DAGISEL-NEXT:    scratch_store_b32 off, v196, s33 offset:476
; DAGISEL-NEXT:    scratch_store_b32 off, v197, s33 offset:480
; DAGISEL-NEXT:    scratch_store_b32 off, v198, s33 offset:484
; DAGISEL-NEXT:    scratch_store_b32 off, v199, s33 offset:488
; DAGISEL-NEXT:    scratch_store_b32 off, v208, s33 offset:492
; DAGISEL-NEXT:    scratch_store_b32 off, v209, s33 offset:496
; DAGISEL-NEXT:    scratch_store_b32 off, v210, s33 offset:500
; DAGISEL-NEXT:    scratch_store_b32 off, v211, s33 offset:504
; DAGISEL-NEXT:    scratch_store_b32 off, v212, s33 offset:508
; DAGISEL-NEXT:    scratch_store_b32 off, v213, s33 offset:512
; DAGISEL-NEXT:    scratch_store_b32 off, v214, s33 offset:516
; DAGISEL-NEXT:    scratch_store_b32 off, v215, s33 offset:520
; DAGISEL-NEXT:    s_clause 0xf ; 64-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v224, s33 offset:524
; DAGISEL-NEXT:    scratch_store_b32 off, v225, s33 offset:528
; DAGISEL-NEXT:    scratch_store_b32 off, v226, s33 offset:532
; DAGISEL-NEXT:    scratch_store_b32 off, v227, s33 offset:536
; DAGISEL-NEXT:    scratch_store_b32 off, v228, s33 offset:540
; DAGISEL-NEXT:    scratch_store_b32 off, v229, s33 offset:544
; DAGISEL-NEXT:    scratch_store_b32 off, v230, s33 offset:548
; DAGISEL-NEXT:    scratch_store_b32 off, v231, s33 offset:552
; DAGISEL-NEXT:    scratch_store_b32 off, v240, s33 offset:556
; DAGISEL-NEXT:    scratch_store_b32 off, v241, s33 offset:560
; DAGISEL-NEXT:    scratch_store_b32 off, v242, s33 offset:564
; DAGISEL-NEXT:    scratch_store_b32 off, v243, s33 offset:568
; DAGISEL-NEXT:    scratch_store_b32 off, v244, s33 offset:572
; DAGISEL-NEXT:    scratch_store_b32 off, v245, s33 offset:576
; DAGISEL-NEXT:    scratch_store_b32 off, v246, s33 offset:580
; DAGISEL-NEXT:    scratch_store_b32 off, v247, s33 offset:584
; DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; DAGISEL-NEXT:    s_clause 0x2 ; 12-byte Folded Spill
; DAGISEL-NEXT:    scratch_store_b32 off, v42, s33
; DAGISEL-NEXT:    scratch_store_b32 off, v40, s33 offset:164
; DAGISEL-NEXT:    scratch_store_b32 off, v41, s33 offset:168
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    v_writelane_b32 v42, s0, 3
; DAGISEL-NEXT:    s_mov_b32 s1, callee@abs32@hi
; DAGISEL-NEXT:    s_mov_b32 s0, callee@abs32@lo
; DAGISEL-NEXT:    s_addk_co_i32 s32, 0x250
; DAGISEL-NEXT:    v_dual_mov_b32 v41, v9 :: v_dual_mov_b32 v40, v8
; DAGISEL-NEXT:    v_writelane_b32 v42, s4, 0
; DAGISEL-NEXT:    v_writelane_b32 v42, s30, 1
; DAGISEL-NEXT:    v_writelane_b32 v42, s31, 2
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    s_swappc_b64 s[30:31], s[0:1]
; DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; DAGISEL-NEXT:    v_readlane_b32 s30, v42, 1
; DAGISEL-NEXT:    flat_store_b32 v[40:41], v0
; DAGISEL-NEXT:    v_readlane_b32 s31, v42, 2
; DAGISEL-NEXT:    v_readlane_b32 s4, v42, 0
; DAGISEL-NEXT:    v_readlane_b32 s0, v42, 3
; DAGISEL-NEXT:    s_clause 0x2 ; 12-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v42, off, s33
; DAGISEL-NEXT:    scratch_load_b32 v40, off, s33 offset:164
; DAGISEL-NEXT:    scratch_load_b32 v41, off, s33 offset:168
; DAGISEL-NEXT:    s_mov_b32 s32, s33
; DAGISEL-NEXT:    s_xor_b32 exec_lo, s4, -1
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v0, off, s33 offset:4
; DAGISEL-NEXT:    scratch_load_b32 v1, off, s33 offset:8
; DAGISEL-NEXT:    scratch_load_b32 v2, off, s33 offset:12
; DAGISEL-NEXT:    scratch_load_b32 v3, off, s33 offset:16
; DAGISEL-NEXT:    scratch_load_b32 v4, off, s33 offset:20
; DAGISEL-NEXT:    scratch_load_b32 v5, off, s33 offset:24
; DAGISEL-NEXT:    scratch_load_b32 v6, off, s33 offset:28
; DAGISEL-NEXT:    scratch_load_b32 v7, off, s33 offset:32
; DAGISEL-NEXT:    scratch_load_b32 v8, off, s33 offset:36
; DAGISEL-NEXT:    scratch_load_b32 v9, off, s33 offset:40
; DAGISEL-NEXT:    scratch_load_b32 v10, off, s33 offset:44
; DAGISEL-NEXT:    scratch_load_b32 v11, off, s33 offset:48
; DAGISEL-NEXT:    scratch_load_b32 v12, off, s33 offset:52
; DAGISEL-NEXT:    scratch_load_b32 v13, off, s33 offset:56
; DAGISEL-NEXT:    scratch_load_b32 v14, off, s33 offset:60
; DAGISEL-NEXT:    scratch_load_b32 v15, off, s33 offset:64
; DAGISEL-NEXT:    scratch_load_b32 v16, off, s33 offset:68
; DAGISEL-NEXT:    scratch_load_b32 v17, off, s33 offset:72
; DAGISEL-NEXT:    scratch_load_b32 v18, off, s33 offset:76
; DAGISEL-NEXT:    scratch_load_b32 v19, off, s33 offset:80
; DAGISEL-NEXT:    scratch_load_b32 v20, off, s33 offset:84
; DAGISEL-NEXT:    scratch_load_b32 v21, off, s33 offset:88
; DAGISEL-NEXT:    scratch_load_b32 v22, off, s33 offset:92
; DAGISEL-NEXT:    scratch_load_b32 v23, off, s33 offset:96
; DAGISEL-NEXT:    scratch_load_b32 v24, off, s33 offset:100
; DAGISEL-NEXT:    scratch_load_b32 v25, off, s33 offset:104
; DAGISEL-NEXT:    scratch_load_b32 v26, off, s33 offset:108
; DAGISEL-NEXT:    scratch_load_b32 v27, off, s33 offset:112
; DAGISEL-NEXT:    scratch_load_b32 v28, off, s33 offset:116
; DAGISEL-NEXT:    scratch_load_b32 v29, off, s33 offset:120
; DAGISEL-NEXT:    scratch_load_b32 v30, off, s33 offset:124
; DAGISEL-NEXT:    scratch_load_b32 v31, off, s33 offset:128
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v32, off, s33 offset:132
; DAGISEL-NEXT:    scratch_load_b32 v33, off, s33 offset:136
; DAGISEL-NEXT:    scratch_load_b32 v34, off, s33 offset:140
; DAGISEL-NEXT:    scratch_load_b32 v35, off, s33 offset:144
; DAGISEL-NEXT:    scratch_load_b32 v36, off, s33 offset:148
; DAGISEL-NEXT:    scratch_load_b32 v37, off, s33 offset:152
; DAGISEL-NEXT:    scratch_load_b32 v38, off, s33 offset:156
; DAGISEL-NEXT:    scratch_load_b32 v39, off, s33 offset:160
; DAGISEL-NEXT:    scratch_load_b32 v48, off, s33 offset:172
; DAGISEL-NEXT:    scratch_load_b32 v49, off, s33 offset:176
; DAGISEL-NEXT:    scratch_load_b32 v50, off, s33 offset:180
; DAGISEL-NEXT:    scratch_load_b32 v51, off, s33 offset:184
; DAGISEL-NEXT:    scratch_load_b32 v52, off, s33 offset:188
; DAGISEL-NEXT:    scratch_load_b32 v53, off, s33 offset:192
; DAGISEL-NEXT:    scratch_load_b32 v54, off, s33 offset:196
; DAGISEL-NEXT:    scratch_load_b32 v55, off, s33 offset:200
; DAGISEL-NEXT:    scratch_load_b32 v64, off, s33 offset:204
; DAGISEL-NEXT:    scratch_load_b32 v65, off, s33 offset:208
; DAGISEL-NEXT:    scratch_load_b32 v66, off, s33 offset:212
; DAGISEL-NEXT:    scratch_load_b32 v67, off, s33 offset:216
; DAGISEL-NEXT:    scratch_load_b32 v68, off, s33 offset:220
; DAGISEL-NEXT:    scratch_load_b32 v69, off, s33 offset:224
; DAGISEL-NEXT:    scratch_load_b32 v70, off, s33 offset:228
; DAGISEL-NEXT:    scratch_load_b32 v71, off, s33 offset:232
; DAGISEL-NEXT:    scratch_load_b32 v80, off, s33 offset:236
; DAGISEL-NEXT:    scratch_load_b32 v81, off, s33 offset:240
; DAGISEL-NEXT:    scratch_load_b32 v82, off, s33 offset:244
; DAGISEL-NEXT:    scratch_load_b32 v83, off, s33 offset:248
; DAGISEL-NEXT:    scratch_load_b32 v84, off, s33 offset:252
; DAGISEL-NEXT:    scratch_load_b32 v85, off, s33 offset:256
; DAGISEL-NEXT:    scratch_load_b32 v86, off, s33 offset:260
; DAGISEL-NEXT:    scratch_load_b32 v87, off, s33 offset:264
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v96, off, s33 offset:268
; DAGISEL-NEXT:    scratch_load_b32 v97, off, s33 offset:272
; DAGISEL-NEXT:    scratch_load_b32 v98, off, s33 offset:276
; DAGISEL-NEXT:    scratch_load_b32 v99, off, s33 offset:280
; DAGISEL-NEXT:    scratch_load_b32 v100, off, s33 offset:284
; DAGISEL-NEXT:    scratch_load_b32 v101, off, s33 offset:288
; DAGISEL-NEXT:    scratch_load_b32 v102, off, s33 offset:292
; DAGISEL-NEXT:    scratch_load_b32 v103, off, s33 offset:296
; DAGISEL-NEXT:    scratch_load_b32 v112, off, s33 offset:300
; DAGISEL-NEXT:    scratch_load_b32 v113, off, s33 offset:304
; DAGISEL-NEXT:    scratch_load_b32 v114, off, s33 offset:308
; DAGISEL-NEXT:    scratch_load_b32 v115, off, s33 offset:312
; DAGISEL-NEXT:    scratch_load_b32 v116, off, s33 offset:316
; DAGISEL-NEXT:    scratch_load_b32 v117, off, s33 offset:320
; DAGISEL-NEXT:    scratch_load_b32 v118, off, s33 offset:324
; DAGISEL-NEXT:    scratch_load_b32 v119, off, s33 offset:328
; DAGISEL-NEXT:    scratch_load_b32 v128, off, s33 offset:332
; DAGISEL-NEXT:    scratch_load_b32 v129, off, s33 offset:336
; DAGISEL-NEXT:    scratch_load_b32 v130, off, s33 offset:340
; DAGISEL-NEXT:    scratch_load_b32 v131, off, s33 offset:344
; DAGISEL-NEXT:    scratch_load_b32 v132, off, s33 offset:348
; DAGISEL-NEXT:    scratch_load_b32 v133, off, s33 offset:352
; DAGISEL-NEXT:    scratch_load_b32 v134, off, s33 offset:356
; DAGISEL-NEXT:    scratch_load_b32 v135, off, s33 offset:360
; DAGISEL-NEXT:    scratch_load_b32 v144, off, s33 offset:364
; DAGISEL-NEXT:    scratch_load_b32 v145, off, s33 offset:368
; DAGISEL-NEXT:    scratch_load_b32 v146, off, s33 offset:372
; DAGISEL-NEXT:    scratch_load_b32 v147, off, s33 offset:376
; DAGISEL-NEXT:    scratch_load_b32 v148, off, s33 offset:380
; DAGISEL-NEXT:    scratch_load_b32 v149, off, s33 offset:384
; DAGISEL-NEXT:    scratch_load_b32 v150, off, s33 offset:388
; DAGISEL-NEXT:    scratch_load_b32 v151, off, s33 offset:392
; DAGISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v160, off, s33 offset:396
; DAGISEL-NEXT:    scratch_load_b32 v161, off, s33 offset:400
; DAGISEL-NEXT:    scratch_load_b32 v162, off, s33 offset:404
; DAGISEL-NEXT:    scratch_load_b32 v163, off, s33 offset:408
; DAGISEL-NEXT:    scratch_load_b32 v164, off, s33 offset:412
; DAGISEL-NEXT:    scratch_load_b32 v165, off, s33 offset:416
; DAGISEL-NEXT:    scratch_load_b32 v166, off, s33 offset:420
; DAGISEL-NEXT:    scratch_load_b32 v167, off, s33 offset:424
; DAGISEL-NEXT:    scratch_load_b32 v176, off, s33 offset:428
; DAGISEL-NEXT:    scratch_load_b32 v177, off, s33 offset:432
; DAGISEL-NEXT:    scratch_load_b32 v178, off, s33 offset:436
; DAGISEL-NEXT:    scratch_load_b32 v179, off, s33 offset:440
; DAGISEL-NEXT:    scratch_load_b32 v180, off, s33 offset:444
; DAGISEL-NEXT:    scratch_load_b32 v181, off, s33 offset:448
; DAGISEL-NEXT:    scratch_load_b32 v182, off, s33 offset:452
; DAGISEL-NEXT:    scratch_load_b32 v183, off, s33 offset:456
; DAGISEL-NEXT:    scratch_load_b32 v192, off, s33 offset:460
; DAGISEL-NEXT:    scratch_load_b32 v193, off, s33 offset:464
; DAGISEL-NEXT:    scratch_load_b32 v194, off, s33 offset:468
; DAGISEL-NEXT:    scratch_load_b32 v195, off, s33 offset:472
; DAGISEL-NEXT:    scratch_load_b32 v196, off, s33 offset:476
; DAGISEL-NEXT:    scratch_load_b32 v197, off, s33 offset:480
; DAGISEL-NEXT:    scratch_load_b32 v198, off, s33 offset:484
; DAGISEL-NEXT:    scratch_load_b32 v199, off, s33 offset:488
; DAGISEL-NEXT:    scratch_load_b32 v208, off, s33 offset:492
; DAGISEL-NEXT:    scratch_load_b32 v209, off, s33 offset:496
; DAGISEL-NEXT:    scratch_load_b32 v210, off, s33 offset:500
; DAGISEL-NEXT:    scratch_load_b32 v211, off, s33 offset:504
; DAGISEL-NEXT:    scratch_load_b32 v212, off, s33 offset:508
; DAGISEL-NEXT:    scratch_load_b32 v213, off, s33 offset:512
; DAGISEL-NEXT:    scratch_load_b32 v214, off, s33 offset:516
; DAGISEL-NEXT:    scratch_load_b32 v215, off, s33 offset:520
; DAGISEL-NEXT:    s_clause 0xf ; 64-byte Folded Reload
; DAGISEL-NEXT:    scratch_load_b32 v224, off, s33 offset:524
; DAGISEL-NEXT:    scratch_load_b32 v225, off, s33 offset:528
; DAGISEL-NEXT:    scratch_load_b32 v226, off, s33 offset:532
; DAGISEL-NEXT:    scratch_load_b32 v227, off, s33 offset:536
; DAGISEL-NEXT:    scratch_load_b32 v228, off, s33 offset:540
; DAGISEL-NEXT:    scratch_load_b32 v229, off, s33 offset:544
; DAGISEL-NEXT:    scratch_load_b32 v230, off, s33 offset:548
; DAGISEL-NEXT:    scratch_load_b32 v231, off, s33 offset:552
; DAGISEL-NEXT:    scratch_load_b32 v240, off, s33 offset:556
; DAGISEL-NEXT:    scratch_load_b32 v241, off, s33 offset:560
; DAGISEL-NEXT:    scratch_load_b32 v242, off, s33 offset:564
; DAGISEL-NEXT:    scratch_load_b32 v243, off, s33 offset:568
; DAGISEL-NEXT:    scratch_load_b32 v244, off, s33 offset:572
; DAGISEL-NEXT:    scratch_load_b32 v245, off, s33 offset:576
; DAGISEL-NEXT:    scratch_load_b32 v246, off, s33 offset:580
; DAGISEL-NEXT:    scratch_load_b32 v247, off, s33 offset:584
; DAGISEL-NEXT:    s_mov_b32 exec_lo, s4
; DAGISEL-NEXT:    s_mov_b32 s33, s0
; DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL-LABEL: call_from_whole_wave:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL-NEXT:    s_wait_expcnt 0x0
; GISEL-NEXT:    s_wait_samplecnt 0x0
; GISEL-NEXT:    s_wait_bvhcnt 0x0
; GISEL-NEXT:    s_wait_kmcnt 0x0
; GISEL-NEXT:    s_mov_b32 s0, s33
; GISEL-NEXT:    s_mov_b32 s33, s32
; GISEL-NEXT:    s_xor_saveexec_b32 s4, -1
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v0, s33 offset:4
; GISEL-NEXT:    scratch_store_b32 off, v1, s33 offset:8
; GISEL-NEXT:    scratch_store_b32 off, v2, s33 offset:12
; GISEL-NEXT:    scratch_store_b32 off, v3, s33 offset:16
; GISEL-NEXT:    scratch_store_b32 off, v4, s33 offset:20
; GISEL-NEXT:    scratch_store_b32 off, v5, s33 offset:24
; GISEL-NEXT:    scratch_store_b32 off, v6, s33 offset:28
; GISEL-NEXT:    scratch_store_b32 off, v7, s33 offset:32
; GISEL-NEXT:    scratch_store_b32 off, v8, s33 offset:36
; GISEL-NEXT:    scratch_store_b32 off, v9, s33 offset:40
; GISEL-NEXT:    scratch_store_b32 off, v10, s33 offset:44
; GISEL-NEXT:    scratch_store_b32 off, v11, s33 offset:48
; GISEL-NEXT:    scratch_store_b32 off, v12, s33 offset:52
; GISEL-NEXT:    scratch_store_b32 off, v13, s33 offset:56
; GISEL-NEXT:    scratch_store_b32 off, v14, s33 offset:60
; GISEL-NEXT:    scratch_store_b32 off, v15, s33 offset:64
; GISEL-NEXT:    scratch_store_b32 off, v16, s33 offset:68
; GISEL-NEXT:    scratch_store_b32 off, v17, s33 offset:72
; GISEL-NEXT:    scratch_store_b32 off, v18, s33 offset:76
; GISEL-NEXT:    scratch_store_b32 off, v19, s33 offset:80
; GISEL-NEXT:    scratch_store_b32 off, v20, s33 offset:84
; GISEL-NEXT:    scratch_store_b32 off, v21, s33 offset:88
; GISEL-NEXT:    scratch_store_b32 off, v22, s33 offset:92
; GISEL-NEXT:    scratch_store_b32 off, v23, s33 offset:96
; GISEL-NEXT:    scratch_store_b32 off, v24, s33 offset:100
; GISEL-NEXT:    scratch_store_b32 off, v25, s33 offset:104
; GISEL-NEXT:    scratch_store_b32 off, v26, s33 offset:108
; GISEL-NEXT:    scratch_store_b32 off, v27, s33 offset:112
; GISEL-NEXT:    scratch_store_b32 off, v28, s33 offset:116
; GISEL-NEXT:    scratch_store_b32 off, v29, s33 offset:120
; GISEL-NEXT:    scratch_store_b32 off, v30, s33 offset:124
; GISEL-NEXT:    scratch_store_b32 off, v31, s33 offset:128
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v32, s33 offset:132
; GISEL-NEXT:    scratch_store_b32 off, v33, s33 offset:136
; GISEL-NEXT:    scratch_store_b32 off, v34, s33 offset:140
; GISEL-NEXT:    scratch_store_b32 off, v35, s33 offset:144
; GISEL-NEXT:    scratch_store_b32 off, v36, s33 offset:148
; GISEL-NEXT:    scratch_store_b32 off, v37, s33 offset:152
; GISEL-NEXT:    scratch_store_b32 off, v38, s33 offset:156
; GISEL-NEXT:    scratch_store_b32 off, v39, s33 offset:160
; GISEL-NEXT:    scratch_store_b32 off, v48, s33 offset:172
; GISEL-NEXT:    scratch_store_b32 off, v49, s33 offset:176
; GISEL-NEXT:    scratch_store_b32 off, v50, s33 offset:180
; GISEL-NEXT:    scratch_store_b32 off, v51, s33 offset:184
; GISEL-NEXT:    scratch_store_b32 off, v52, s33 offset:188
; GISEL-NEXT:    scratch_store_b32 off, v53, s33 offset:192
; GISEL-NEXT:    scratch_store_b32 off, v54, s33 offset:196
; GISEL-NEXT:    scratch_store_b32 off, v55, s33 offset:200
; GISEL-NEXT:    scratch_store_b32 off, v64, s33 offset:204
; GISEL-NEXT:    scratch_store_b32 off, v65, s33 offset:208
; GISEL-NEXT:    scratch_store_b32 off, v66, s33 offset:212
; GISEL-NEXT:    scratch_store_b32 off, v67, s33 offset:216
; GISEL-NEXT:    scratch_store_b32 off, v68, s33 offset:220
; GISEL-NEXT:    scratch_store_b32 off, v69, s33 offset:224
; GISEL-NEXT:    scratch_store_b32 off, v70, s33 offset:228
; GISEL-NEXT:    scratch_store_b32 off, v71, s33 offset:232
; GISEL-NEXT:    scratch_store_b32 off, v80, s33 offset:236
; GISEL-NEXT:    scratch_store_b32 off, v81, s33 offset:240
; GISEL-NEXT:    scratch_store_b32 off, v82, s33 offset:244
; GISEL-NEXT:    scratch_store_b32 off, v83, s33 offset:248
; GISEL-NEXT:    scratch_store_b32 off, v84, s33 offset:252
; GISEL-NEXT:    scratch_store_b32 off, v85, s33 offset:256
; GISEL-NEXT:    scratch_store_b32 off, v86, s33 offset:260
; GISEL-NEXT:    scratch_store_b32 off, v87, s33 offset:264
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v96, s33 offset:268
; GISEL-NEXT:    scratch_store_b32 off, v97, s33 offset:272
; GISEL-NEXT:    scratch_store_b32 off, v98, s33 offset:276
; GISEL-NEXT:    scratch_store_b32 off, v99, s33 offset:280
; GISEL-NEXT:    scratch_store_b32 off, v100, s33 offset:284
; GISEL-NEXT:    scratch_store_b32 off, v101, s33 offset:288
; GISEL-NEXT:    scratch_store_b32 off, v102, s33 offset:292
; GISEL-NEXT:    scratch_store_b32 off, v103, s33 offset:296
; GISEL-NEXT:    scratch_store_b32 off, v112, s33 offset:300
; GISEL-NEXT:    scratch_store_b32 off, v113, s33 offset:304
; GISEL-NEXT:    scratch_store_b32 off, v114, s33 offset:308
; GISEL-NEXT:    scratch_store_b32 off, v115, s33 offset:312
; GISEL-NEXT:    scratch_store_b32 off, v116, s33 offset:316
; GISEL-NEXT:    scratch_store_b32 off, v117, s33 offset:320
; GISEL-NEXT:    scratch_store_b32 off, v118, s33 offset:324
; GISEL-NEXT:    scratch_store_b32 off, v119, s33 offset:328
; GISEL-NEXT:    scratch_store_b32 off, v128, s33 offset:332
; GISEL-NEXT:    scratch_store_b32 off, v129, s33 offset:336
; GISEL-NEXT:    scratch_store_b32 off, v130, s33 offset:340
; GISEL-NEXT:    scratch_store_b32 off, v131, s33 offset:344
; GISEL-NEXT:    scratch_store_b32 off, v132, s33 offset:348
; GISEL-NEXT:    scratch_store_b32 off, v133, s33 offset:352
; GISEL-NEXT:    scratch_store_b32 off, v134, s33 offset:356
; GISEL-NEXT:    scratch_store_b32 off, v135, s33 offset:360
; GISEL-NEXT:    scratch_store_b32 off, v144, s33 offset:364
; GISEL-NEXT:    scratch_store_b32 off, v145, s33 offset:368
; GISEL-NEXT:    scratch_store_b32 off, v146, s33 offset:372
; GISEL-NEXT:    scratch_store_b32 off, v147, s33 offset:376
; GISEL-NEXT:    scratch_store_b32 off, v148, s33 offset:380
; GISEL-NEXT:    scratch_store_b32 off, v149, s33 offset:384
; GISEL-NEXT:    scratch_store_b32 off, v150, s33 offset:388
; GISEL-NEXT:    scratch_store_b32 off, v151, s33 offset:392
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v160, s33 offset:396
; GISEL-NEXT:    scratch_store_b32 off, v161, s33 offset:400
; GISEL-NEXT:    scratch_store_b32 off, v162, s33 offset:404
; GISEL-NEXT:    scratch_store_b32 off, v163, s33 offset:408
; GISEL-NEXT:    scratch_store_b32 off, v164, s33 offset:412
; GISEL-NEXT:    scratch_store_b32 off, v165, s33 offset:416
; GISEL-NEXT:    scratch_store_b32 off, v166, s33 offset:420
; GISEL-NEXT:    scratch_store_b32 off, v167, s33 offset:424
; GISEL-NEXT:    scratch_store_b32 off, v176, s33 offset:428
; GISEL-NEXT:    scratch_store_b32 off, v177, s33 offset:432
; GISEL-NEXT:    scratch_store_b32 off, v178, s33 offset:436
; GISEL-NEXT:    scratch_store_b32 off, v179, s33 offset:440
; GISEL-NEXT:    scratch_store_b32 off, v180, s33 offset:444
; GISEL-NEXT:    scratch_store_b32 off, v181, s33 offset:448
; GISEL-NEXT:    scratch_store_b32 off, v182, s33 offset:452
; GISEL-NEXT:    scratch_store_b32 off, v183, s33 offset:456
; GISEL-NEXT:    scratch_store_b32 off, v192, s33 offset:460
; GISEL-NEXT:    scratch_store_b32 off, v193, s33 offset:464
; GISEL-NEXT:    scratch_store_b32 off, v194, s33 offset:468
; GISEL-NEXT:    scratch_store_b32 off, v195, s33 offset:472
; GISEL-NEXT:    scratch_store_b32 off, v196, s33 offset:476
; GISEL-NEXT:    scratch_store_b32 off, v197, s33 offset:480
; GISEL-NEXT:    scratch_store_b32 off, v198, s33 offset:484
; GISEL-NEXT:    scratch_store_b32 off, v199, s33 offset:488
; GISEL-NEXT:    scratch_store_b32 off, v208, s33 offset:492
; GISEL-NEXT:    scratch_store_b32 off, v209, s33 offset:496
; GISEL-NEXT:    scratch_store_b32 off, v210, s33 offset:500
; GISEL-NEXT:    scratch_store_b32 off, v211, s33 offset:504
; GISEL-NEXT:    scratch_store_b32 off, v212, s33 offset:508
; GISEL-NEXT:    scratch_store_b32 off, v213, s33 offset:512
; GISEL-NEXT:    scratch_store_b32 off, v214, s33 offset:516
; GISEL-NEXT:    scratch_store_b32 off, v215, s33 offset:520
; GISEL-NEXT:    s_clause 0xf ; 64-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v224, s33 offset:524
; GISEL-NEXT:    scratch_store_b32 off, v225, s33 offset:528
; GISEL-NEXT:    scratch_store_b32 off, v226, s33 offset:532
; GISEL-NEXT:    scratch_store_b32 off, v227, s33 offset:536
; GISEL-NEXT:    scratch_store_b32 off, v228, s33 offset:540
; GISEL-NEXT:    scratch_store_b32 off, v229, s33 offset:544
; GISEL-NEXT:    scratch_store_b32 off, v230, s33 offset:548
; GISEL-NEXT:    scratch_store_b32 off, v231, s33 offset:552
; GISEL-NEXT:    scratch_store_b32 off, v240, s33 offset:556
; GISEL-NEXT:    scratch_store_b32 off, v241, s33 offset:560
; GISEL-NEXT:    scratch_store_b32 off, v242, s33 offset:564
; GISEL-NEXT:    scratch_store_b32 off, v243, s33 offset:568
; GISEL-NEXT:    scratch_store_b32 off, v244, s33 offset:572
; GISEL-NEXT:    scratch_store_b32 off, v245, s33 offset:576
; GISEL-NEXT:    scratch_store_b32 off, v246, s33 offset:580
; GISEL-NEXT:    scratch_store_b32 off, v247, s33 offset:584
; GISEL-NEXT:    s_mov_b32 exec_lo, -1
; GISEL-NEXT:    s_clause 0x2 ; 12-byte Folded Spill
; GISEL-NEXT:    scratch_store_b32 off, v42, s33
; GISEL-NEXT:    scratch_store_b32 off, v40, s33 offset:164
; GISEL-NEXT:    scratch_store_b32 off, v41, s33 offset:168
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    v_writelane_b32 v42, s0, 3
; GISEL-NEXT:    s_mov_b32 s0, callee@abs32@lo
; GISEL-NEXT:    s_mov_b32 s1, callee@abs32@hi
; GISEL-NEXT:    s_addk_co_i32 s32, 0x250
; GISEL-NEXT:    v_dual_mov_b32 v40, v8 :: v_dual_mov_b32 v41, v9
; GISEL-NEXT:    v_writelane_b32 v42, s4, 0
; GISEL-NEXT:    v_writelane_b32 v42, s30, 1
; GISEL-NEXT:    v_writelane_b32 v42, s31, 2
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    s_swappc_b64 s[30:31], s[0:1]
; GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GISEL-NEXT:    v_readlane_b32 s30, v42, 1
; GISEL-NEXT:    flat_store_b32 v[40:41], v0
; GISEL-NEXT:    v_readlane_b32 s31, v42, 2
; GISEL-NEXT:    v_readlane_b32 s4, v42, 0
; GISEL-NEXT:    v_readlane_b32 s0, v42, 3
; GISEL-NEXT:    s_clause 0x2 ; 12-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v42, off, s33
; GISEL-NEXT:    scratch_load_b32 v40, off, s33 offset:164
; GISEL-NEXT:    scratch_load_b32 v41, off, s33 offset:168
; GISEL-NEXT:    s_mov_b32 s32, s33
; GISEL-NEXT:    s_xor_b32 exec_lo, s4, -1
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v0, off, s33 offset:4
; GISEL-NEXT:    scratch_load_b32 v1, off, s33 offset:8
; GISEL-NEXT:    scratch_load_b32 v2, off, s33 offset:12
; GISEL-NEXT:    scratch_load_b32 v3, off, s33 offset:16
; GISEL-NEXT:    scratch_load_b32 v4, off, s33 offset:20
; GISEL-NEXT:    scratch_load_b32 v5, off, s33 offset:24
; GISEL-NEXT:    scratch_load_b32 v6, off, s33 offset:28
; GISEL-NEXT:    scratch_load_b32 v7, off, s33 offset:32
; GISEL-NEXT:    scratch_load_b32 v8, off, s33 offset:36
; GISEL-NEXT:    scratch_load_b32 v9, off, s33 offset:40
; GISEL-NEXT:    scratch_load_b32 v10, off, s33 offset:44
; GISEL-NEXT:    scratch_load_b32 v11, off, s33 offset:48
; GISEL-NEXT:    scratch_load_b32 v12, off, s33 offset:52
; GISEL-NEXT:    scratch_load_b32 v13, off, s33 offset:56
; GISEL-NEXT:    scratch_load_b32 v14, off, s33 offset:60
; GISEL-NEXT:    scratch_load_b32 v15, off, s33 offset:64
; GISEL-NEXT:    scratch_load_b32 v16, off, s33 offset:68
; GISEL-NEXT:    scratch_load_b32 v17, off, s33 offset:72
; GISEL-NEXT:    scratch_load_b32 v18, off, s33 offset:76
; GISEL-NEXT:    scratch_load_b32 v19, off, s33 offset:80
; GISEL-NEXT:    scratch_load_b32 v20, off, s33 offset:84
; GISEL-NEXT:    scratch_load_b32 v21, off, s33 offset:88
; GISEL-NEXT:    scratch_load_b32 v22, off, s33 offset:92
; GISEL-NEXT:    scratch_load_b32 v23, off, s33 offset:96
; GISEL-NEXT:    scratch_load_b32 v24, off, s33 offset:100
; GISEL-NEXT:    scratch_load_b32 v25, off, s33 offset:104
; GISEL-NEXT:    scratch_load_b32 v26, off, s33 offset:108
; GISEL-NEXT:    scratch_load_b32 v27, off, s33 offset:112
; GISEL-NEXT:    scratch_load_b32 v28, off, s33 offset:116
; GISEL-NEXT:    scratch_load_b32 v29, off, s33 offset:120
; GISEL-NEXT:    scratch_load_b32 v30, off, s33 offset:124
; GISEL-NEXT:    scratch_load_b32 v31, off, s33 offset:128
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v32, off, s33 offset:132
; GISEL-NEXT:    scratch_load_b32 v33, off, s33 offset:136
; GISEL-NEXT:    scratch_load_b32 v34, off, s33 offset:140
; GISEL-NEXT:    scratch_load_b32 v35, off, s33 offset:144
; GISEL-NEXT:    scratch_load_b32 v36, off, s33 offset:148
; GISEL-NEXT:    scratch_load_b32 v37, off, s33 offset:152
; GISEL-NEXT:    scratch_load_b32 v38, off, s33 offset:156
; GISEL-NEXT:    scratch_load_b32 v39, off, s33 offset:160
; GISEL-NEXT:    scratch_load_b32 v48, off, s33 offset:172
; GISEL-NEXT:    scratch_load_b32 v49, off, s33 offset:176
; GISEL-NEXT:    scratch_load_b32 v50, off, s33 offset:180
; GISEL-NEXT:    scratch_load_b32 v51, off, s33 offset:184
; GISEL-NEXT:    scratch_load_b32 v52, off, s33 offset:188
; GISEL-NEXT:    scratch_load_b32 v53, off, s33 offset:192
; GISEL-NEXT:    scratch_load_b32 v54, off, s33 offset:196
; GISEL-NEXT:    scratch_load_b32 v55, off, s33 offset:200
; GISEL-NEXT:    scratch_load_b32 v64, off, s33 offset:204
; GISEL-NEXT:    scratch_load_b32 v65, off, s33 offset:208
; GISEL-NEXT:    scratch_load_b32 v66, off, s33 offset:212
; GISEL-NEXT:    scratch_load_b32 v67, off, s33 offset:216
; GISEL-NEXT:    scratch_load_b32 v68, off, s33 offset:220
; GISEL-NEXT:    scratch_load_b32 v69, off, s33 offset:224
; GISEL-NEXT:    scratch_load_b32 v70, off, s33 offset:228
; GISEL-NEXT:    scratch_load_b32 v71, off, s33 offset:232
; GISEL-NEXT:    scratch_load_b32 v80, off, s33 offset:236
; GISEL-NEXT:    scratch_load_b32 v81, off, s33 offset:240
; GISEL-NEXT:    scratch_load_b32 v82, off, s33 offset:244
; GISEL-NEXT:    scratch_load_b32 v83, off, s33 offset:248
; GISEL-NEXT:    scratch_load_b32 v84, off, s33 offset:252
; GISEL-NEXT:    scratch_load_b32 v85, off, s33 offset:256
; GISEL-NEXT:    scratch_load_b32 v86, off, s33 offset:260
; GISEL-NEXT:    scratch_load_b32 v87, off, s33 offset:264
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v96, off, s33 offset:268
; GISEL-NEXT:    scratch_load_b32 v97, off, s33 offset:272
; GISEL-NEXT:    scratch_load_b32 v98, off, s33 offset:276
; GISEL-NEXT:    scratch_load_b32 v99, off, s33 offset:280
; GISEL-NEXT:    scratch_load_b32 v100, off, s33 offset:284
; GISEL-NEXT:    scratch_load_b32 v101, off, s33 offset:288
; GISEL-NEXT:    scratch_load_b32 v102, off, s33 offset:292
; GISEL-NEXT:    scratch_load_b32 v103, off, s33 offset:296
; GISEL-NEXT:    scratch_load_b32 v112, off, s33 offset:300
; GISEL-NEXT:    scratch_load_b32 v113, off, s33 offset:304
; GISEL-NEXT:    scratch_load_b32 v114, off, s33 offset:308
; GISEL-NEXT:    scratch_load_b32 v115, off, s33 offset:312
; GISEL-NEXT:    scratch_load_b32 v116, off, s33 offset:316
; GISEL-NEXT:    scratch_load_b32 v117, off, s33 offset:320
; GISEL-NEXT:    scratch_load_b32 v118, off, s33 offset:324
; GISEL-NEXT:    scratch_load_b32 v119, off, s33 offset:328
; GISEL-NEXT:    scratch_load_b32 v128, off, s33 offset:332
; GISEL-NEXT:    scratch_load_b32 v129, off, s33 offset:336
; GISEL-NEXT:    scratch_load_b32 v130, off, s33 offset:340
; GISEL-NEXT:    scratch_load_b32 v131, off, s33 offset:344
; GISEL-NEXT:    scratch_load_b32 v132, off, s33 offset:348
; GISEL-NEXT:    scratch_load_b32 v133, off, s33 offset:352
; GISEL-NEXT:    scratch_load_b32 v134, off, s33 offset:356
; GISEL-NEXT:    scratch_load_b32 v135, off, s33 offset:360
; GISEL-NEXT:    scratch_load_b32 v144, off, s33 offset:364
; GISEL-NEXT:    scratch_load_b32 v145, off, s33 offset:368
; GISEL-NEXT:    scratch_load_b32 v146, off, s33 offset:372
; GISEL-NEXT:    scratch_load_b32 v147, off, s33 offset:376
; GISEL-NEXT:    scratch_load_b32 v148, off, s33 offset:380
; GISEL-NEXT:    scratch_load_b32 v149, off, s33 offset:384
; GISEL-NEXT:    scratch_load_b32 v150, off, s33 offset:388
; GISEL-NEXT:    scratch_load_b32 v151, off, s33 offset:392
; GISEL-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v160, off, s33 offset:396
; GISEL-NEXT:    scratch_load_b32 v161, off, s33 offset:400
; GISEL-NEXT:    scratch_load_b32 v162, off, s33 offset:404
; GISEL-NEXT:    scratch_load_b32 v163, off, s33 offset:408
; GISEL-NEXT:    scratch_load_b32 v164, off, s33 offset:412
; GISEL-NEXT:    scratch_load_b32 v165, off, s33 offset:416
; GISEL-NEXT:    scratch_load_b32 v166, off, s33 offset:420
; GISEL-NEXT:    scratch_load_b32 v167, off, s33 offset:424
; GISEL-NEXT:    scratch_load_b32 v176, off, s33 offset:428
; GISEL-NEXT:    scratch_load_b32 v177, off, s33 offset:432
; GISEL-NEXT:    scratch_load_b32 v178, off, s33 offset:436
; GISEL-NEXT:    scratch_load_b32 v179, off, s33 offset:440
; GISEL-NEXT:    scratch_load_b32 v180, off, s33 offset:444
; GISEL-NEXT:    scratch_load_b32 v181, off, s33 offset:448
; GISEL-NEXT:    scratch_load_b32 v182, off, s33 offset:452
; GISEL-NEXT:    scratch_load_b32 v183, off, s33 offset:456
; GISEL-NEXT:    scratch_load_b32 v192, off, s33 offset:460
; GISEL-NEXT:    scratch_load_b32 v193, off, s33 offset:464
; GISEL-NEXT:    scratch_load_b32 v194, off, s33 offset:468
; GISEL-NEXT:    scratch_load_b32 v195, off, s33 offset:472
; GISEL-NEXT:    scratch_load_b32 v196, off, s33 offset:476
; GISEL-NEXT:    scratch_load_b32 v197, off, s33 offset:480
; GISEL-NEXT:    scratch_load_b32 v198, off, s33 offset:484
; GISEL-NEXT:    scratch_load_b32 v199, off, s33 offset:488
; GISEL-NEXT:    scratch_load_b32 v208, off, s33 offset:492
; GISEL-NEXT:    scratch_load_b32 v209, off, s33 offset:496
; GISEL-NEXT:    scratch_load_b32 v210, off, s33 offset:500
; GISEL-NEXT:    scratch_load_b32 v211, off, s33 offset:504
; GISEL-NEXT:    scratch_load_b32 v212, off, s33 offset:508
; GISEL-NEXT:    scratch_load_b32 v213, off, s33 offset:512
; GISEL-NEXT:    scratch_load_b32 v214, off, s33 offset:516
; GISEL-NEXT:    scratch_load_b32 v215, off, s33 offset:520
; GISEL-NEXT:    s_clause 0xf ; 64-byte Folded Reload
; GISEL-NEXT:    scratch_load_b32 v224, off, s33 offset:524
; GISEL-NEXT:    scratch_load_b32 v225, off, s33 offset:528
; GISEL-NEXT:    scratch_load_b32 v226, off, s33 offset:532
; GISEL-NEXT:    scratch_load_b32 v227, off, s33 offset:536
; GISEL-NEXT:    scratch_load_b32 v228, off, s33 offset:540
; GISEL-NEXT:    scratch_load_b32 v229, off, s33 offset:544
; GISEL-NEXT:    scratch_load_b32 v230, off, s33 offset:548
; GISEL-NEXT:    scratch_load_b32 v231, off, s33 offset:552
; GISEL-NEXT:    scratch_load_b32 v240, off, s33 offset:556
; GISEL-NEXT:    scratch_load_b32 v241, off, s33 offset:560
; GISEL-NEXT:    scratch_load_b32 v242, off, s33 offset:564
; GISEL-NEXT:    scratch_load_b32 v243, off, s33 offset:568
; GISEL-NEXT:    scratch_load_b32 v244, off, s33 offset:572
; GISEL-NEXT:    scratch_load_b32 v245, off, s33 offset:576
; GISEL-NEXT:    scratch_load_b32 v246, off, s33 offset:580
; GISEL-NEXT:    scratch_load_b32 v247, off, s33 offset:584
; GISEL-NEXT:    s_mov_b32 exec_lo, s4
; GISEL-NEXT:    s_mov_b32 s33, s0
; GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL-NEXT:    s_setpc_b64 s[30:31]
;
; DAGISEL64-LABEL: call_from_whole_wave:
; DAGISEL64:       ; %bb.0:
; DAGISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL64-NEXT:    s_wait_expcnt 0x0
; DAGISEL64-NEXT:    s_wait_samplecnt 0x0
; DAGISEL64-NEXT:    s_wait_bvhcnt 0x0
; DAGISEL64-NEXT:    s_wait_kmcnt 0x0
; DAGISEL64-NEXT:    s_mov_b32 s0, s33
; DAGISEL64-NEXT:    s_mov_b32 s33, s32
; DAGISEL64-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v0, s33 offset:4
; DAGISEL64-NEXT:    scratch_store_b32 off, v1, s33 offset:8
; DAGISEL64-NEXT:    scratch_store_b32 off, v2, s33 offset:12
; DAGISEL64-NEXT:    scratch_store_b32 off, v3, s33 offset:16
; DAGISEL64-NEXT:    scratch_store_b32 off, v4, s33 offset:20
; DAGISEL64-NEXT:    scratch_store_b32 off, v5, s33 offset:24
; DAGISEL64-NEXT:    scratch_store_b32 off, v6, s33 offset:28
; DAGISEL64-NEXT:    scratch_store_b32 off, v7, s33 offset:32
; DAGISEL64-NEXT:    scratch_store_b32 off, v8, s33 offset:36
; DAGISEL64-NEXT:    scratch_store_b32 off, v9, s33 offset:40
; DAGISEL64-NEXT:    scratch_store_b32 off, v10, s33 offset:44
; DAGISEL64-NEXT:    scratch_store_b32 off, v11, s33 offset:48
; DAGISEL64-NEXT:    scratch_store_b32 off, v12, s33 offset:52
; DAGISEL64-NEXT:    scratch_store_b32 off, v13, s33 offset:56
; DAGISEL64-NEXT:    scratch_store_b32 off, v14, s33 offset:60
; DAGISEL64-NEXT:    scratch_store_b32 off, v15, s33 offset:64
; DAGISEL64-NEXT:    scratch_store_b32 off, v16, s33 offset:68
; DAGISEL64-NEXT:    scratch_store_b32 off, v17, s33 offset:72
; DAGISEL64-NEXT:    scratch_store_b32 off, v18, s33 offset:76
; DAGISEL64-NEXT:    scratch_store_b32 off, v19, s33 offset:80
; DAGISEL64-NEXT:    scratch_store_b32 off, v20, s33 offset:84
; DAGISEL64-NEXT:    scratch_store_b32 off, v21, s33 offset:88
; DAGISEL64-NEXT:    scratch_store_b32 off, v22, s33 offset:92
; DAGISEL64-NEXT:    scratch_store_b32 off, v23, s33 offset:96
; DAGISEL64-NEXT:    scratch_store_b32 off, v24, s33 offset:100
; DAGISEL64-NEXT:    scratch_store_b32 off, v25, s33 offset:104
; DAGISEL64-NEXT:    scratch_store_b32 off, v26, s33 offset:108
; DAGISEL64-NEXT:    scratch_store_b32 off, v27, s33 offset:112
; DAGISEL64-NEXT:    scratch_store_b32 off, v28, s33 offset:116
; DAGISEL64-NEXT:    scratch_store_b32 off, v29, s33 offset:120
; DAGISEL64-NEXT:    scratch_store_b32 off, v30, s33 offset:124
; DAGISEL64-NEXT:    scratch_store_b32 off, v31, s33 offset:128
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v32, s33 offset:132
; DAGISEL64-NEXT:    scratch_store_b32 off, v33, s33 offset:136
; DAGISEL64-NEXT:    scratch_store_b32 off, v34, s33 offset:140
; DAGISEL64-NEXT:    scratch_store_b32 off, v35, s33 offset:144
; DAGISEL64-NEXT:    scratch_store_b32 off, v36, s33 offset:148
; DAGISEL64-NEXT:    scratch_store_b32 off, v37, s33 offset:152
; DAGISEL64-NEXT:    scratch_store_b32 off, v38, s33 offset:156
; DAGISEL64-NEXT:    scratch_store_b32 off, v39, s33 offset:160
; DAGISEL64-NEXT:    scratch_store_b32 off, v48, s33 offset:172
; DAGISEL64-NEXT:    scratch_store_b32 off, v49, s33 offset:176
; DAGISEL64-NEXT:    scratch_store_b32 off, v50, s33 offset:180
; DAGISEL64-NEXT:    scratch_store_b32 off, v51, s33 offset:184
; DAGISEL64-NEXT:    scratch_store_b32 off, v52, s33 offset:188
; DAGISEL64-NEXT:    scratch_store_b32 off, v53, s33 offset:192
; DAGISEL64-NEXT:    scratch_store_b32 off, v54, s33 offset:196
; DAGISEL64-NEXT:    scratch_store_b32 off, v55, s33 offset:200
; DAGISEL64-NEXT:    scratch_store_b32 off, v64, s33 offset:204
; DAGISEL64-NEXT:    scratch_store_b32 off, v65, s33 offset:208
; DAGISEL64-NEXT:    scratch_store_b32 off, v66, s33 offset:212
; DAGISEL64-NEXT:    scratch_store_b32 off, v67, s33 offset:216
; DAGISEL64-NEXT:    scratch_store_b32 off, v68, s33 offset:220
; DAGISEL64-NEXT:    scratch_store_b32 off, v69, s33 offset:224
; DAGISEL64-NEXT:    scratch_store_b32 off, v70, s33 offset:228
; DAGISEL64-NEXT:    scratch_store_b32 off, v71, s33 offset:232
; DAGISEL64-NEXT:    scratch_store_b32 off, v80, s33 offset:236
; DAGISEL64-NEXT:    scratch_store_b32 off, v81, s33 offset:240
; DAGISEL64-NEXT:    scratch_store_b32 off, v82, s33 offset:244
; DAGISEL64-NEXT:    scratch_store_b32 off, v83, s33 offset:248
; DAGISEL64-NEXT:    scratch_store_b32 off, v84, s33 offset:252
; DAGISEL64-NEXT:    scratch_store_b32 off, v85, s33 offset:256
; DAGISEL64-NEXT:    scratch_store_b32 off, v86, s33 offset:260
; DAGISEL64-NEXT:    scratch_store_b32 off, v87, s33 offset:264
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v96, s33 offset:268
; DAGISEL64-NEXT:    scratch_store_b32 off, v97, s33 offset:272
; DAGISEL64-NEXT:    scratch_store_b32 off, v98, s33 offset:276
; DAGISEL64-NEXT:    scratch_store_b32 off, v99, s33 offset:280
; DAGISEL64-NEXT:    scratch_store_b32 off, v100, s33 offset:284
; DAGISEL64-NEXT:    scratch_store_b32 off, v101, s33 offset:288
; DAGISEL64-NEXT:    scratch_store_b32 off, v102, s33 offset:292
; DAGISEL64-NEXT:    scratch_store_b32 off, v103, s33 offset:296
; DAGISEL64-NEXT:    scratch_store_b32 off, v112, s33 offset:300
; DAGISEL64-NEXT:    scratch_store_b32 off, v113, s33 offset:304
; DAGISEL64-NEXT:    scratch_store_b32 off, v114, s33 offset:308
; DAGISEL64-NEXT:    scratch_store_b32 off, v115, s33 offset:312
; DAGISEL64-NEXT:    scratch_store_b32 off, v116, s33 offset:316
; DAGISEL64-NEXT:    scratch_store_b32 off, v117, s33 offset:320
; DAGISEL64-NEXT:    scratch_store_b32 off, v118, s33 offset:324
; DAGISEL64-NEXT:    scratch_store_b32 off, v119, s33 offset:328
; DAGISEL64-NEXT:    scratch_store_b32 off, v128, s33 offset:332
; DAGISEL64-NEXT:    scratch_store_b32 off, v129, s33 offset:336
; DAGISEL64-NEXT:    scratch_store_b32 off, v130, s33 offset:340
; DAGISEL64-NEXT:    scratch_store_b32 off, v131, s33 offset:344
; DAGISEL64-NEXT:    scratch_store_b32 off, v132, s33 offset:348
; DAGISEL64-NEXT:    scratch_store_b32 off, v133, s33 offset:352
; DAGISEL64-NEXT:    scratch_store_b32 off, v134, s33 offset:356
; DAGISEL64-NEXT:    scratch_store_b32 off, v135, s33 offset:360
; DAGISEL64-NEXT:    scratch_store_b32 off, v144, s33 offset:364
; DAGISEL64-NEXT:    scratch_store_b32 off, v145, s33 offset:368
; DAGISEL64-NEXT:    scratch_store_b32 off, v146, s33 offset:372
; DAGISEL64-NEXT:    scratch_store_b32 off, v147, s33 offset:376
; DAGISEL64-NEXT:    scratch_store_b32 off, v148, s33 offset:380
; DAGISEL64-NEXT:    scratch_store_b32 off, v149, s33 offset:384
; DAGISEL64-NEXT:    scratch_store_b32 off, v150, s33 offset:388
; DAGISEL64-NEXT:    scratch_store_b32 off, v151, s33 offset:392
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v160, s33 offset:396
; DAGISEL64-NEXT:    scratch_store_b32 off, v161, s33 offset:400
; DAGISEL64-NEXT:    scratch_store_b32 off, v162, s33 offset:404
; DAGISEL64-NEXT:    scratch_store_b32 off, v163, s33 offset:408
; DAGISEL64-NEXT:    scratch_store_b32 off, v164, s33 offset:412
; DAGISEL64-NEXT:    scratch_store_b32 off, v165, s33 offset:416
; DAGISEL64-NEXT:    scratch_store_b32 off, v166, s33 offset:420
; DAGISEL64-NEXT:    scratch_store_b32 off, v167, s33 offset:424
; DAGISEL64-NEXT:    scratch_store_b32 off, v176, s33 offset:428
; DAGISEL64-NEXT:    scratch_store_b32 off, v177, s33 offset:432
; DAGISEL64-NEXT:    scratch_store_b32 off, v178, s33 offset:436
; DAGISEL64-NEXT:    scratch_store_b32 off, v179, s33 offset:440
; DAGISEL64-NEXT:    scratch_store_b32 off, v180, s33 offset:444
; DAGISEL64-NEXT:    scratch_store_b32 off, v181, s33 offset:448
; DAGISEL64-NEXT:    scratch_store_b32 off, v182, s33 offset:452
; DAGISEL64-NEXT:    scratch_store_b32 off, v183, s33 offset:456
; DAGISEL64-NEXT:    scratch_store_b32 off, v192, s33 offset:460
; DAGISEL64-NEXT:    scratch_store_b32 off, v193, s33 offset:464
; DAGISEL64-NEXT:    scratch_store_b32 off, v194, s33 offset:468
; DAGISEL64-NEXT:    scratch_store_b32 off, v195, s33 offset:472
; DAGISEL64-NEXT:    scratch_store_b32 off, v196, s33 offset:476
; DAGISEL64-NEXT:    scratch_store_b32 off, v197, s33 offset:480
; DAGISEL64-NEXT:    scratch_store_b32 off, v198, s33 offset:484
; DAGISEL64-NEXT:    scratch_store_b32 off, v199, s33 offset:488
; DAGISEL64-NEXT:    scratch_store_b32 off, v208, s33 offset:492
; DAGISEL64-NEXT:    scratch_store_b32 off, v209, s33 offset:496
; DAGISEL64-NEXT:    scratch_store_b32 off, v210, s33 offset:500
; DAGISEL64-NEXT:    scratch_store_b32 off, v211, s33 offset:504
; DAGISEL64-NEXT:    scratch_store_b32 off, v212, s33 offset:508
; DAGISEL64-NEXT:    scratch_store_b32 off, v213, s33 offset:512
; DAGISEL64-NEXT:    scratch_store_b32 off, v214, s33 offset:516
; DAGISEL64-NEXT:    scratch_store_b32 off, v215, s33 offset:520
; DAGISEL64-NEXT:    s_clause 0xf ; 64-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v224, s33 offset:524
; DAGISEL64-NEXT:    scratch_store_b32 off, v225, s33 offset:528
; DAGISEL64-NEXT:    scratch_store_b32 off, v226, s33 offset:532
; DAGISEL64-NEXT:    scratch_store_b32 off, v227, s33 offset:536
; DAGISEL64-NEXT:    scratch_store_b32 off, v228, s33 offset:540
; DAGISEL64-NEXT:    scratch_store_b32 off, v229, s33 offset:544
; DAGISEL64-NEXT:    scratch_store_b32 off, v230, s33 offset:548
; DAGISEL64-NEXT:    scratch_store_b32 off, v231, s33 offset:552
; DAGISEL64-NEXT:    scratch_store_b32 off, v240, s33 offset:556
; DAGISEL64-NEXT:    scratch_store_b32 off, v241, s33 offset:560
; DAGISEL64-NEXT:    scratch_store_b32 off, v242, s33 offset:564
; DAGISEL64-NEXT:    scratch_store_b32 off, v243, s33 offset:568
; DAGISEL64-NEXT:    scratch_store_b32 off, v244, s33 offset:572
; DAGISEL64-NEXT:    scratch_store_b32 off, v245, s33 offset:576
; DAGISEL64-NEXT:    scratch_store_b32 off, v246, s33 offset:580
; DAGISEL64-NEXT:    scratch_store_b32 off, v247, s33 offset:584
; DAGISEL64-NEXT:    s_mov_b64 exec, -1
; DAGISEL64-NEXT:    s_clause 0x2 ; 12-byte Folded Spill
; DAGISEL64-NEXT:    scratch_store_b32 off, v42, s33
; DAGISEL64-NEXT:    scratch_store_b32 off, v40, s33 offset:164
; DAGISEL64-NEXT:    scratch_store_b32 off, v41, s33 offset:168
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    v_writelane_b32 v42, s0, 4
; DAGISEL64-NEXT:    s_mov_b32 s1, callee@abs32@hi
; DAGISEL64-NEXT:    s_mov_b32 s0, callee@abs32@lo
; DAGISEL64-NEXT:    s_addk_co_i32 s32, 0x250
; DAGISEL64-NEXT:    v_mov_b32_e32 v41, v9
; DAGISEL64-NEXT:    v_writelane_b32 v42, s4, 0
; DAGISEL64-NEXT:    v_mov_b32_e32 v40, v8
; DAGISEL64-NEXT:    v_writelane_b32 v42, s5, 1
; DAGISEL64-NEXT:    v_writelane_b32 v42, s30, 2
; DAGISEL64-NEXT:    v_writelane_b32 v42, s31, 3
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    s_swappc_b64 s[30:31], s[0:1]
; DAGISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; DAGISEL64-NEXT:    v_readlane_b32 s30, v42, 2
; DAGISEL64-NEXT:    flat_store_b32 v[40:41], v0
; DAGISEL64-NEXT:    v_readlane_b32 s31, v42, 3
; DAGISEL64-NEXT:    v_readlane_b32 s5, v42, 1
; DAGISEL64-NEXT:    v_readlane_b32 s4, v42, 0
; DAGISEL64-NEXT:    v_readlane_b32 s0, v42, 4
; DAGISEL64-NEXT:    s_clause 0x2 ; 12-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v42, off, s33
; DAGISEL64-NEXT:    scratch_load_b32 v40, off, s33 offset:164
; DAGISEL64-NEXT:    scratch_load_b32 v41, off, s33 offset:168
; DAGISEL64-NEXT:    s_mov_b32 s32, s33
; DAGISEL64-NEXT:    s_xor_b64 exec, s[4:5], -1
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v0, off, s33 offset:4
; DAGISEL64-NEXT:    scratch_load_b32 v1, off, s33 offset:8
; DAGISEL64-NEXT:    scratch_load_b32 v2, off, s33 offset:12
; DAGISEL64-NEXT:    scratch_load_b32 v3, off, s33 offset:16
; DAGISEL64-NEXT:    scratch_load_b32 v4, off, s33 offset:20
; DAGISEL64-NEXT:    scratch_load_b32 v5, off, s33 offset:24
; DAGISEL64-NEXT:    scratch_load_b32 v6, off, s33 offset:28
; DAGISEL64-NEXT:    scratch_load_b32 v7, off, s33 offset:32
; DAGISEL64-NEXT:    scratch_load_b32 v8, off, s33 offset:36
; DAGISEL64-NEXT:    scratch_load_b32 v9, off, s33 offset:40
; DAGISEL64-NEXT:    scratch_load_b32 v10, off, s33 offset:44
; DAGISEL64-NEXT:    scratch_load_b32 v11, off, s33 offset:48
; DAGISEL64-NEXT:    scratch_load_b32 v12, off, s33 offset:52
; DAGISEL64-NEXT:    scratch_load_b32 v13, off, s33 offset:56
; DAGISEL64-NEXT:    scratch_load_b32 v14, off, s33 offset:60
; DAGISEL64-NEXT:    scratch_load_b32 v15, off, s33 offset:64
; DAGISEL64-NEXT:    scratch_load_b32 v16, off, s33 offset:68
; DAGISEL64-NEXT:    scratch_load_b32 v17, off, s33 offset:72
; DAGISEL64-NEXT:    scratch_load_b32 v18, off, s33 offset:76
; DAGISEL64-NEXT:    scratch_load_b32 v19, off, s33 offset:80
; DAGISEL64-NEXT:    scratch_load_b32 v20, off, s33 offset:84
; DAGISEL64-NEXT:    scratch_load_b32 v21, off, s33 offset:88
; DAGISEL64-NEXT:    scratch_load_b32 v22, off, s33 offset:92
; DAGISEL64-NEXT:    scratch_load_b32 v23, off, s33 offset:96
; DAGISEL64-NEXT:    scratch_load_b32 v24, off, s33 offset:100
; DAGISEL64-NEXT:    scratch_load_b32 v25, off, s33 offset:104
; DAGISEL64-NEXT:    scratch_load_b32 v26, off, s33 offset:108
; DAGISEL64-NEXT:    scratch_load_b32 v27, off, s33 offset:112
; DAGISEL64-NEXT:    scratch_load_b32 v28, off, s33 offset:116
; DAGISEL64-NEXT:    scratch_load_b32 v29, off, s33 offset:120
; DAGISEL64-NEXT:    scratch_load_b32 v30, off, s33 offset:124
; DAGISEL64-NEXT:    scratch_load_b32 v31, off, s33 offset:128
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v32, off, s33 offset:132
; DAGISEL64-NEXT:    scratch_load_b32 v33, off, s33 offset:136
; DAGISEL64-NEXT:    scratch_load_b32 v34, off, s33 offset:140
; DAGISEL64-NEXT:    scratch_load_b32 v35, off, s33 offset:144
; DAGISEL64-NEXT:    scratch_load_b32 v36, off, s33 offset:148
; DAGISEL64-NEXT:    scratch_load_b32 v37, off, s33 offset:152
; DAGISEL64-NEXT:    scratch_load_b32 v38, off, s33 offset:156
; DAGISEL64-NEXT:    scratch_load_b32 v39, off, s33 offset:160
; DAGISEL64-NEXT:    scratch_load_b32 v48, off, s33 offset:172
; DAGISEL64-NEXT:    scratch_load_b32 v49, off, s33 offset:176
; DAGISEL64-NEXT:    scratch_load_b32 v50, off, s33 offset:180
; DAGISEL64-NEXT:    scratch_load_b32 v51, off, s33 offset:184
; DAGISEL64-NEXT:    scratch_load_b32 v52, off, s33 offset:188
; DAGISEL64-NEXT:    scratch_load_b32 v53, off, s33 offset:192
; DAGISEL64-NEXT:    scratch_load_b32 v54, off, s33 offset:196
; DAGISEL64-NEXT:    scratch_load_b32 v55, off, s33 offset:200
; DAGISEL64-NEXT:    scratch_load_b32 v64, off, s33 offset:204
; DAGISEL64-NEXT:    scratch_load_b32 v65, off, s33 offset:208
; DAGISEL64-NEXT:    scratch_load_b32 v66, off, s33 offset:212
; DAGISEL64-NEXT:    scratch_load_b32 v67, off, s33 offset:216
; DAGISEL64-NEXT:    scratch_load_b32 v68, off, s33 offset:220
; DAGISEL64-NEXT:    scratch_load_b32 v69, off, s33 offset:224
; DAGISEL64-NEXT:    scratch_load_b32 v70, off, s33 offset:228
; DAGISEL64-NEXT:    scratch_load_b32 v71, off, s33 offset:232
; DAGISEL64-NEXT:    scratch_load_b32 v80, off, s33 offset:236
; DAGISEL64-NEXT:    scratch_load_b32 v81, off, s33 offset:240
; DAGISEL64-NEXT:    scratch_load_b32 v82, off, s33 offset:244
; DAGISEL64-NEXT:    scratch_load_b32 v83, off, s33 offset:248
; DAGISEL64-NEXT:    scratch_load_b32 v84, off, s33 offset:252
; DAGISEL64-NEXT:    scratch_load_b32 v85, off, s33 offset:256
; DAGISEL64-NEXT:    scratch_load_b32 v86, off, s33 offset:260
; DAGISEL64-NEXT:    scratch_load_b32 v87, off, s33 offset:264
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v96, off, s33 offset:268
; DAGISEL64-NEXT:    scratch_load_b32 v97, off, s33 offset:272
; DAGISEL64-NEXT:    scratch_load_b32 v98, off, s33 offset:276
; DAGISEL64-NEXT:    scratch_load_b32 v99, off, s33 offset:280
; DAGISEL64-NEXT:    scratch_load_b32 v100, off, s33 offset:284
; DAGISEL64-NEXT:    scratch_load_b32 v101, off, s33 offset:288
; DAGISEL64-NEXT:    scratch_load_b32 v102, off, s33 offset:292
; DAGISEL64-NEXT:    scratch_load_b32 v103, off, s33 offset:296
; DAGISEL64-NEXT:    scratch_load_b32 v112, off, s33 offset:300
; DAGISEL64-NEXT:    scratch_load_b32 v113, off, s33 offset:304
; DAGISEL64-NEXT:    scratch_load_b32 v114, off, s33 offset:308
; DAGISEL64-NEXT:    scratch_load_b32 v115, off, s33 offset:312
; DAGISEL64-NEXT:    scratch_load_b32 v116, off, s33 offset:316
; DAGISEL64-NEXT:    scratch_load_b32 v117, off, s33 offset:320
; DAGISEL64-NEXT:    scratch_load_b32 v118, off, s33 offset:324
; DAGISEL64-NEXT:    scratch_load_b32 v119, off, s33 offset:328
; DAGISEL64-NEXT:    scratch_load_b32 v128, off, s33 offset:332
; DAGISEL64-NEXT:    scratch_load_b32 v129, off, s33 offset:336
; DAGISEL64-NEXT:    scratch_load_b32 v130, off, s33 offset:340
; DAGISEL64-NEXT:    scratch_load_b32 v131, off, s33 offset:344
; DAGISEL64-NEXT:    scratch_load_b32 v132, off, s33 offset:348
; DAGISEL64-NEXT:    scratch_load_b32 v133, off, s33 offset:352
; DAGISEL64-NEXT:    scratch_load_b32 v134, off, s33 offset:356
; DAGISEL64-NEXT:    scratch_load_b32 v135, off, s33 offset:360
; DAGISEL64-NEXT:    scratch_load_b32 v144, off, s33 offset:364
; DAGISEL64-NEXT:    scratch_load_b32 v145, off, s33 offset:368
; DAGISEL64-NEXT:    scratch_load_b32 v146, off, s33 offset:372
; DAGISEL64-NEXT:    scratch_load_b32 v147, off, s33 offset:376
; DAGISEL64-NEXT:    scratch_load_b32 v148, off, s33 offset:380
; DAGISEL64-NEXT:    scratch_load_b32 v149, off, s33 offset:384
; DAGISEL64-NEXT:    scratch_load_b32 v150, off, s33 offset:388
; DAGISEL64-NEXT:    scratch_load_b32 v151, off, s33 offset:392
; DAGISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v160, off, s33 offset:396
; DAGISEL64-NEXT:    scratch_load_b32 v161, off, s33 offset:400
; DAGISEL64-NEXT:    scratch_load_b32 v162, off, s33 offset:404
; DAGISEL64-NEXT:    scratch_load_b32 v163, off, s33 offset:408
; DAGISEL64-NEXT:    scratch_load_b32 v164, off, s33 offset:412
; DAGISEL64-NEXT:    scratch_load_b32 v165, off, s33 offset:416
; DAGISEL64-NEXT:    scratch_load_b32 v166, off, s33 offset:420
; DAGISEL64-NEXT:    scratch_load_b32 v167, off, s33 offset:424
; DAGISEL64-NEXT:    scratch_load_b32 v176, off, s33 offset:428
; DAGISEL64-NEXT:    scratch_load_b32 v177, off, s33 offset:432
; DAGISEL64-NEXT:    scratch_load_b32 v178, off, s33 offset:436
; DAGISEL64-NEXT:    scratch_load_b32 v179, off, s33 offset:440
; DAGISEL64-NEXT:    scratch_load_b32 v180, off, s33 offset:444
; DAGISEL64-NEXT:    scratch_load_b32 v181, off, s33 offset:448
; DAGISEL64-NEXT:    scratch_load_b32 v182, off, s33 offset:452
; DAGISEL64-NEXT:    scratch_load_b32 v183, off, s33 offset:456
; DAGISEL64-NEXT:    scratch_load_b32 v192, off, s33 offset:460
; DAGISEL64-NEXT:    scratch_load_b32 v193, off, s33 offset:464
; DAGISEL64-NEXT:    scratch_load_b32 v194, off, s33 offset:468
; DAGISEL64-NEXT:    scratch_load_b32 v195, off, s33 offset:472
; DAGISEL64-NEXT:    scratch_load_b32 v196, off, s33 offset:476
; DAGISEL64-NEXT:    scratch_load_b32 v197, off, s33 offset:480
; DAGISEL64-NEXT:    scratch_load_b32 v198, off, s33 offset:484
; DAGISEL64-NEXT:    scratch_load_b32 v199, off, s33 offset:488
; DAGISEL64-NEXT:    scratch_load_b32 v208, off, s33 offset:492
; DAGISEL64-NEXT:    scratch_load_b32 v209, off, s33 offset:496
; DAGISEL64-NEXT:    scratch_load_b32 v210, off, s33 offset:500
; DAGISEL64-NEXT:    scratch_load_b32 v211, off, s33 offset:504
; DAGISEL64-NEXT:    scratch_load_b32 v212, off, s33 offset:508
; DAGISEL64-NEXT:    scratch_load_b32 v213, off, s33 offset:512
; DAGISEL64-NEXT:    scratch_load_b32 v214, off, s33 offset:516
; DAGISEL64-NEXT:    scratch_load_b32 v215, off, s33 offset:520
; DAGISEL64-NEXT:    s_clause 0xf ; 64-byte Folded Reload
; DAGISEL64-NEXT:    scratch_load_b32 v224, off, s33 offset:524
; DAGISEL64-NEXT:    scratch_load_b32 v225, off, s33 offset:528
; DAGISEL64-NEXT:    scratch_load_b32 v226, off, s33 offset:532
; DAGISEL64-NEXT:    scratch_load_b32 v227, off, s33 offset:536
; DAGISEL64-NEXT:    scratch_load_b32 v228, off, s33 offset:540
; DAGISEL64-NEXT:    scratch_load_b32 v229, off, s33 offset:544
; DAGISEL64-NEXT:    scratch_load_b32 v230, off, s33 offset:548
; DAGISEL64-NEXT:    scratch_load_b32 v231, off, s33 offset:552
; DAGISEL64-NEXT:    scratch_load_b32 v240, off, s33 offset:556
; DAGISEL64-NEXT:    scratch_load_b32 v241, off, s33 offset:560
; DAGISEL64-NEXT:    scratch_load_b32 v242, off, s33 offset:564
; DAGISEL64-NEXT:    scratch_load_b32 v243, off, s33 offset:568
; DAGISEL64-NEXT:    scratch_load_b32 v244, off, s33 offset:572
; DAGISEL64-NEXT:    scratch_load_b32 v245, off, s33 offset:576
; DAGISEL64-NEXT:    scratch_load_b32 v246, off, s33 offset:580
; DAGISEL64-NEXT:    scratch_load_b32 v247, off, s33 offset:584
; DAGISEL64-NEXT:    s_mov_b64 exec, s[4:5]
; DAGISEL64-NEXT:    s_mov_b32 s33, s0
; DAGISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; DAGISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; DAGISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GISEL64-LABEL: call_from_whole_wave:
; GISEL64:       ; %bb.0:
; GISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL64-NEXT:    s_wait_expcnt 0x0
; GISEL64-NEXT:    s_wait_samplecnt 0x0
; GISEL64-NEXT:    s_wait_bvhcnt 0x0
; GISEL64-NEXT:    s_wait_kmcnt 0x0
; GISEL64-NEXT:    s_mov_b32 s0, s33
; GISEL64-NEXT:    s_mov_b32 s33, s32
; GISEL64-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v0, s33 offset:4
; GISEL64-NEXT:    scratch_store_b32 off, v1, s33 offset:8
; GISEL64-NEXT:    scratch_store_b32 off, v2, s33 offset:12
; GISEL64-NEXT:    scratch_store_b32 off, v3, s33 offset:16
; GISEL64-NEXT:    scratch_store_b32 off, v4, s33 offset:20
; GISEL64-NEXT:    scratch_store_b32 off, v5, s33 offset:24
; GISEL64-NEXT:    scratch_store_b32 off, v6, s33 offset:28
; GISEL64-NEXT:    scratch_store_b32 off, v7, s33 offset:32
; GISEL64-NEXT:    scratch_store_b32 off, v8, s33 offset:36
; GISEL64-NEXT:    scratch_store_b32 off, v9, s33 offset:40
; GISEL64-NEXT:    scratch_store_b32 off, v10, s33 offset:44
; GISEL64-NEXT:    scratch_store_b32 off, v11, s33 offset:48
; GISEL64-NEXT:    scratch_store_b32 off, v12, s33 offset:52
; GISEL64-NEXT:    scratch_store_b32 off, v13, s33 offset:56
; GISEL64-NEXT:    scratch_store_b32 off, v14, s33 offset:60
; GISEL64-NEXT:    scratch_store_b32 off, v15, s33 offset:64
; GISEL64-NEXT:    scratch_store_b32 off, v16, s33 offset:68
; GISEL64-NEXT:    scratch_store_b32 off, v17, s33 offset:72
; GISEL64-NEXT:    scratch_store_b32 off, v18, s33 offset:76
; GISEL64-NEXT:    scratch_store_b32 off, v19, s33 offset:80
; GISEL64-NEXT:    scratch_store_b32 off, v20, s33 offset:84
; GISEL64-NEXT:    scratch_store_b32 off, v21, s33 offset:88
; GISEL64-NEXT:    scratch_store_b32 off, v22, s33 offset:92
; GISEL64-NEXT:    scratch_store_b32 off, v23, s33 offset:96
; GISEL64-NEXT:    scratch_store_b32 off, v24, s33 offset:100
; GISEL64-NEXT:    scratch_store_b32 off, v25, s33 offset:104
; GISEL64-NEXT:    scratch_store_b32 off, v26, s33 offset:108
; GISEL64-NEXT:    scratch_store_b32 off, v27, s33 offset:112
; GISEL64-NEXT:    scratch_store_b32 off, v28, s33 offset:116
; GISEL64-NEXT:    scratch_store_b32 off, v29, s33 offset:120
; GISEL64-NEXT:    scratch_store_b32 off, v30, s33 offset:124
; GISEL64-NEXT:    scratch_store_b32 off, v31, s33 offset:128
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v32, s33 offset:132
; GISEL64-NEXT:    scratch_store_b32 off, v33, s33 offset:136
; GISEL64-NEXT:    scratch_store_b32 off, v34, s33 offset:140
; GISEL64-NEXT:    scratch_store_b32 off, v35, s33 offset:144
; GISEL64-NEXT:    scratch_store_b32 off, v36, s33 offset:148
; GISEL64-NEXT:    scratch_store_b32 off, v37, s33 offset:152
; GISEL64-NEXT:    scratch_store_b32 off, v38, s33 offset:156
; GISEL64-NEXT:    scratch_store_b32 off, v39, s33 offset:160
; GISEL64-NEXT:    scratch_store_b32 off, v48, s33 offset:172
; GISEL64-NEXT:    scratch_store_b32 off, v49, s33 offset:176
; GISEL64-NEXT:    scratch_store_b32 off, v50, s33 offset:180
; GISEL64-NEXT:    scratch_store_b32 off, v51, s33 offset:184
; GISEL64-NEXT:    scratch_store_b32 off, v52, s33 offset:188
; GISEL64-NEXT:    scratch_store_b32 off, v53, s33 offset:192
; GISEL64-NEXT:    scratch_store_b32 off, v54, s33 offset:196
; GISEL64-NEXT:    scratch_store_b32 off, v55, s33 offset:200
; GISEL64-NEXT:    scratch_store_b32 off, v64, s33 offset:204
; GISEL64-NEXT:    scratch_store_b32 off, v65, s33 offset:208
; GISEL64-NEXT:    scratch_store_b32 off, v66, s33 offset:212
; GISEL64-NEXT:    scratch_store_b32 off, v67, s33 offset:216
; GISEL64-NEXT:    scratch_store_b32 off, v68, s33 offset:220
; GISEL64-NEXT:    scratch_store_b32 off, v69, s33 offset:224
; GISEL64-NEXT:    scratch_store_b32 off, v70, s33 offset:228
; GISEL64-NEXT:    scratch_store_b32 off, v71, s33 offset:232
; GISEL64-NEXT:    scratch_store_b32 off, v80, s33 offset:236
; GISEL64-NEXT:    scratch_store_b32 off, v81, s33 offset:240
; GISEL64-NEXT:    scratch_store_b32 off, v82, s33 offset:244
; GISEL64-NEXT:    scratch_store_b32 off, v83, s33 offset:248
; GISEL64-NEXT:    scratch_store_b32 off, v84, s33 offset:252
; GISEL64-NEXT:    scratch_store_b32 off, v85, s33 offset:256
; GISEL64-NEXT:    scratch_store_b32 off, v86, s33 offset:260
; GISEL64-NEXT:    scratch_store_b32 off, v87, s33 offset:264
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v96, s33 offset:268
; GISEL64-NEXT:    scratch_store_b32 off, v97, s33 offset:272
; GISEL64-NEXT:    scratch_store_b32 off, v98, s33 offset:276
; GISEL64-NEXT:    scratch_store_b32 off, v99, s33 offset:280
; GISEL64-NEXT:    scratch_store_b32 off, v100, s33 offset:284
; GISEL64-NEXT:    scratch_store_b32 off, v101, s33 offset:288
; GISEL64-NEXT:    scratch_store_b32 off, v102, s33 offset:292
; GISEL64-NEXT:    scratch_store_b32 off, v103, s33 offset:296
; GISEL64-NEXT:    scratch_store_b32 off, v112, s33 offset:300
; GISEL64-NEXT:    scratch_store_b32 off, v113, s33 offset:304
; GISEL64-NEXT:    scratch_store_b32 off, v114, s33 offset:308
; GISEL64-NEXT:    scratch_store_b32 off, v115, s33 offset:312
; GISEL64-NEXT:    scratch_store_b32 off, v116, s33 offset:316
; GISEL64-NEXT:    scratch_store_b32 off, v117, s33 offset:320
; GISEL64-NEXT:    scratch_store_b32 off, v118, s33 offset:324
; GISEL64-NEXT:    scratch_store_b32 off, v119, s33 offset:328
; GISEL64-NEXT:    scratch_store_b32 off, v128, s33 offset:332
; GISEL64-NEXT:    scratch_store_b32 off, v129, s33 offset:336
; GISEL64-NEXT:    scratch_store_b32 off, v130, s33 offset:340
; GISEL64-NEXT:    scratch_store_b32 off, v131, s33 offset:344
; GISEL64-NEXT:    scratch_store_b32 off, v132, s33 offset:348
; GISEL64-NEXT:    scratch_store_b32 off, v133, s33 offset:352
; GISEL64-NEXT:    scratch_store_b32 off, v134, s33 offset:356
; GISEL64-NEXT:    scratch_store_b32 off, v135, s33 offset:360
; GISEL64-NEXT:    scratch_store_b32 off, v144, s33 offset:364
; GISEL64-NEXT:    scratch_store_b32 off, v145, s33 offset:368
; GISEL64-NEXT:    scratch_store_b32 off, v146, s33 offset:372
; GISEL64-NEXT:    scratch_store_b32 off, v147, s33 offset:376
; GISEL64-NEXT:    scratch_store_b32 off, v148, s33 offset:380
; GISEL64-NEXT:    scratch_store_b32 off, v149, s33 offset:384
; GISEL64-NEXT:    scratch_store_b32 off, v150, s33 offset:388
; GISEL64-NEXT:    scratch_store_b32 off, v151, s33 offset:392
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v160, s33 offset:396
; GISEL64-NEXT:    scratch_store_b32 off, v161, s33 offset:400
; GISEL64-NEXT:    scratch_store_b32 off, v162, s33 offset:404
; GISEL64-NEXT:    scratch_store_b32 off, v163, s33 offset:408
; GISEL64-NEXT:    scratch_store_b32 off, v164, s33 offset:412
; GISEL64-NEXT:    scratch_store_b32 off, v165, s33 offset:416
; GISEL64-NEXT:    scratch_store_b32 off, v166, s33 offset:420
; GISEL64-NEXT:    scratch_store_b32 off, v167, s33 offset:424
; GISEL64-NEXT:    scratch_store_b32 off, v176, s33 offset:428
; GISEL64-NEXT:    scratch_store_b32 off, v177, s33 offset:432
; GISEL64-NEXT:    scratch_store_b32 off, v178, s33 offset:436
; GISEL64-NEXT:    scratch_store_b32 off, v179, s33 offset:440
; GISEL64-NEXT:    scratch_store_b32 off, v180, s33 offset:444
; GISEL64-NEXT:    scratch_store_b32 off, v181, s33 offset:448
; GISEL64-NEXT:    scratch_store_b32 off, v182, s33 offset:452
; GISEL64-NEXT:    scratch_store_b32 off, v183, s33 offset:456
; GISEL64-NEXT:    scratch_store_b32 off, v192, s33 offset:460
; GISEL64-NEXT:    scratch_store_b32 off, v193, s33 offset:464
; GISEL64-NEXT:    scratch_store_b32 off, v194, s33 offset:468
; GISEL64-NEXT:    scratch_store_b32 off, v195, s33 offset:472
; GISEL64-NEXT:    scratch_store_b32 off, v196, s33 offset:476
; GISEL64-NEXT:    scratch_store_b32 off, v197, s33 offset:480
; GISEL64-NEXT:    scratch_store_b32 off, v198, s33 offset:484
; GISEL64-NEXT:    scratch_store_b32 off, v199, s33 offset:488
; GISEL64-NEXT:    scratch_store_b32 off, v208, s33 offset:492
; GISEL64-NEXT:    scratch_store_b32 off, v209, s33 offset:496
; GISEL64-NEXT:    scratch_store_b32 off, v210, s33 offset:500
; GISEL64-NEXT:    scratch_store_b32 off, v211, s33 offset:504
; GISEL64-NEXT:    scratch_store_b32 off, v212, s33 offset:508
; GISEL64-NEXT:    scratch_store_b32 off, v213, s33 offset:512
; GISEL64-NEXT:    scratch_store_b32 off, v214, s33 offset:516
; GISEL64-NEXT:    scratch_store_b32 off, v215, s33 offset:520
; GISEL64-NEXT:    s_clause 0xf ; 64-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v224, s33 offset:524
; GISEL64-NEXT:    scratch_store_b32 off, v225, s33 offset:528
; GISEL64-NEXT:    scratch_store_b32 off, v226, s33 offset:532
; GISEL64-NEXT:    scratch_store_b32 off, v227, s33 offset:536
; GISEL64-NEXT:    scratch_store_b32 off, v228, s33 offset:540
; GISEL64-NEXT:    scratch_store_b32 off, v229, s33 offset:544
; GISEL64-NEXT:    scratch_store_b32 off, v230, s33 offset:548
; GISEL64-NEXT:    scratch_store_b32 off, v231, s33 offset:552
; GISEL64-NEXT:    scratch_store_b32 off, v240, s33 offset:556
; GISEL64-NEXT:    scratch_store_b32 off, v241, s33 offset:560
; GISEL64-NEXT:    scratch_store_b32 off, v242, s33 offset:564
; GISEL64-NEXT:    scratch_store_b32 off, v243, s33 offset:568
; GISEL64-NEXT:    scratch_store_b32 off, v244, s33 offset:572
; GISEL64-NEXT:    scratch_store_b32 off, v245, s33 offset:576
; GISEL64-NEXT:    scratch_store_b32 off, v246, s33 offset:580
; GISEL64-NEXT:    scratch_store_b32 off, v247, s33 offset:584
; GISEL64-NEXT:    s_mov_b64 exec, -1
; GISEL64-NEXT:    s_clause 0x2 ; 12-byte Folded Spill
; GISEL64-NEXT:    scratch_store_b32 off, v42, s33
; GISEL64-NEXT:    scratch_store_b32 off, v40, s33 offset:164
; GISEL64-NEXT:    scratch_store_b32 off, v41, s33 offset:168
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    v_writelane_b32 v42, s0, 4
; GISEL64-NEXT:    s_mov_b32 s0, callee@abs32@lo
; GISEL64-NEXT:    s_mov_b32 s1, callee@abs32@hi
; GISEL64-NEXT:    s_addk_co_i32 s32, 0x250
; GISEL64-NEXT:    v_mov_b32_e32 v40, v8
; GISEL64-NEXT:    v_writelane_b32 v42, s4, 0
; GISEL64-NEXT:    v_mov_b32_e32 v41, v9
; GISEL64-NEXT:    v_writelane_b32 v42, s5, 1
; GISEL64-NEXT:    v_writelane_b32 v42, s30, 2
; GISEL64-NEXT:    v_writelane_b32 v42, s31, 3
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    s_swappc_b64 s[30:31], s[0:1]
; GISEL64-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GISEL64-NEXT:    v_readlane_b32 s30, v42, 2
; GISEL64-NEXT:    flat_store_b32 v[40:41], v0
; GISEL64-NEXT:    v_readlane_b32 s31, v42, 3
; GISEL64-NEXT:    v_readlane_b32 s5, v42, 1
; GISEL64-NEXT:    v_readlane_b32 s4, v42, 0
; GISEL64-NEXT:    v_readlane_b32 s0, v42, 4
; GISEL64-NEXT:    s_clause 0x2 ; 12-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v42, off, s33
; GISEL64-NEXT:    scratch_load_b32 v40, off, s33 offset:164
; GISEL64-NEXT:    scratch_load_b32 v41, off, s33 offset:168
; GISEL64-NEXT:    s_mov_b32 s32, s33
; GISEL64-NEXT:    s_xor_b64 exec, s[4:5], -1
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v0, off, s33 offset:4
; GISEL64-NEXT:    scratch_load_b32 v1, off, s33 offset:8
; GISEL64-NEXT:    scratch_load_b32 v2, off, s33 offset:12
; GISEL64-NEXT:    scratch_load_b32 v3, off, s33 offset:16
; GISEL64-NEXT:    scratch_load_b32 v4, off, s33 offset:20
; GISEL64-NEXT:    scratch_load_b32 v5, off, s33 offset:24
; GISEL64-NEXT:    scratch_load_b32 v6, off, s33 offset:28
; GISEL64-NEXT:    scratch_load_b32 v7, off, s33 offset:32
; GISEL64-NEXT:    scratch_load_b32 v8, off, s33 offset:36
; GISEL64-NEXT:    scratch_load_b32 v9, off, s33 offset:40
; GISEL64-NEXT:    scratch_load_b32 v10, off, s33 offset:44
; GISEL64-NEXT:    scratch_load_b32 v11, off, s33 offset:48
; GISEL64-NEXT:    scratch_load_b32 v12, off, s33 offset:52
; GISEL64-NEXT:    scratch_load_b32 v13, off, s33 offset:56
; GISEL64-NEXT:    scratch_load_b32 v14, off, s33 offset:60
; GISEL64-NEXT:    scratch_load_b32 v15, off, s33 offset:64
; GISEL64-NEXT:    scratch_load_b32 v16, off, s33 offset:68
; GISEL64-NEXT:    scratch_load_b32 v17, off, s33 offset:72
; GISEL64-NEXT:    scratch_load_b32 v18, off, s33 offset:76
; GISEL64-NEXT:    scratch_load_b32 v19, off, s33 offset:80
; GISEL64-NEXT:    scratch_load_b32 v20, off, s33 offset:84
; GISEL64-NEXT:    scratch_load_b32 v21, off, s33 offset:88
; GISEL64-NEXT:    scratch_load_b32 v22, off, s33 offset:92
; GISEL64-NEXT:    scratch_load_b32 v23, off, s33 offset:96
; GISEL64-NEXT:    scratch_load_b32 v24, off, s33 offset:100
; GISEL64-NEXT:    scratch_load_b32 v25, off, s33 offset:104
; GISEL64-NEXT:    scratch_load_b32 v26, off, s33 offset:108
; GISEL64-NEXT:    scratch_load_b32 v27, off, s33 offset:112
; GISEL64-NEXT:    scratch_load_b32 v28, off, s33 offset:116
; GISEL64-NEXT:    scratch_load_b32 v29, off, s33 offset:120
; GISEL64-NEXT:    scratch_load_b32 v30, off, s33 offset:124
; GISEL64-NEXT:    scratch_load_b32 v31, off, s33 offset:128
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v32, off, s33 offset:132
; GISEL64-NEXT:    scratch_load_b32 v33, off, s33 offset:136
; GISEL64-NEXT:    scratch_load_b32 v34, off, s33 offset:140
; GISEL64-NEXT:    scratch_load_b32 v35, off, s33 offset:144
; GISEL64-NEXT:    scratch_load_b32 v36, off, s33 offset:148
; GISEL64-NEXT:    scratch_load_b32 v37, off, s33 offset:152
; GISEL64-NEXT:    scratch_load_b32 v38, off, s33 offset:156
; GISEL64-NEXT:    scratch_load_b32 v39, off, s33 offset:160
; GISEL64-NEXT:    scratch_load_b32 v48, off, s33 offset:172
; GISEL64-NEXT:    scratch_load_b32 v49, off, s33 offset:176
; GISEL64-NEXT:    scratch_load_b32 v50, off, s33 offset:180
; GISEL64-NEXT:    scratch_load_b32 v51, off, s33 offset:184
; GISEL64-NEXT:    scratch_load_b32 v52, off, s33 offset:188
; GISEL64-NEXT:    scratch_load_b32 v53, off, s33 offset:192
; GISEL64-NEXT:    scratch_load_b32 v54, off, s33 offset:196
; GISEL64-NEXT:    scratch_load_b32 v55, off, s33 offset:200
; GISEL64-NEXT:    scratch_load_b32 v64, off, s33 offset:204
; GISEL64-NEXT:    scratch_load_b32 v65, off, s33 offset:208
; GISEL64-NEXT:    scratch_load_b32 v66, off, s33 offset:212
; GISEL64-NEXT:    scratch_load_b32 v67, off, s33 offset:216
; GISEL64-NEXT:    scratch_load_b32 v68, off, s33 offset:220
; GISEL64-NEXT:    scratch_load_b32 v69, off, s33 offset:224
; GISEL64-NEXT:    scratch_load_b32 v70, off, s33 offset:228
; GISEL64-NEXT:    scratch_load_b32 v71, off, s33 offset:232
; GISEL64-NEXT:    scratch_load_b32 v80, off, s33 offset:236
; GISEL64-NEXT:    scratch_load_b32 v81, off, s33 offset:240
; GISEL64-NEXT:    scratch_load_b32 v82, off, s33 offset:244
; GISEL64-NEXT:    scratch_load_b32 v83, off, s33 offset:248
; GISEL64-NEXT:    scratch_load_b32 v84, off, s33 offset:252
; GISEL64-NEXT:    scratch_load_b32 v85, off, s33 offset:256
; GISEL64-NEXT:    scratch_load_b32 v86, off, s33 offset:260
; GISEL64-NEXT:    scratch_load_b32 v87, off, s33 offset:264
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v96, off, s33 offset:268
; GISEL64-NEXT:    scratch_load_b32 v97, off, s33 offset:272
; GISEL64-NEXT:    scratch_load_b32 v98, off, s33 offset:276
; GISEL64-NEXT:    scratch_load_b32 v99, off, s33 offset:280
; GISEL64-NEXT:    scratch_load_b32 v100, off, s33 offset:284
; GISEL64-NEXT:    scratch_load_b32 v101, off, s33 offset:288
; GISEL64-NEXT:    scratch_load_b32 v102, off, s33 offset:292
; GISEL64-NEXT:    scratch_load_b32 v103, off, s33 offset:296
; GISEL64-NEXT:    scratch_load_b32 v112, off, s33 offset:300
; GISEL64-NEXT:    scratch_load_b32 v113, off, s33 offset:304
; GISEL64-NEXT:    scratch_load_b32 v114, off, s33 offset:308
; GISEL64-NEXT:    scratch_load_b32 v115, off, s33 offset:312
; GISEL64-NEXT:    scratch_load_b32 v116, off, s33 offset:316
; GISEL64-NEXT:    scratch_load_b32 v117, off, s33 offset:320
; GISEL64-NEXT:    scratch_load_b32 v118, off, s33 offset:324
; GISEL64-NEXT:    scratch_load_b32 v119, off, s33 offset:328
; GISEL64-NEXT:    scratch_load_b32 v128, off, s33 offset:332
; GISEL64-NEXT:    scratch_load_b32 v129, off, s33 offset:336
; GISEL64-NEXT:    scratch_load_b32 v130, off, s33 offset:340
; GISEL64-NEXT:    scratch_load_b32 v131, off, s33 offset:344
; GISEL64-NEXT:    scratch_load_b32 v132, off, s33 offset:348
; GISEL64-NEXT:    scratch_load_b32 v133, off, s33 offset:352
; GISEL64-NEXT:    scratch_load_b32 v134, off, s33 offset:356
; GISEL64-NEXT:    scratch_load_b32 v135, off, s33 offset:360
; GISEL64-NEXT:    scratch_load_b32 v144, off, s33 offset:364
; GISEL64-NEXT:    scratch_load_b32 v145, off, s33 offset:368
; GISEL64-NEXT:    scratch_load_b32 v146, off, s33 offset:372
; GISEL64-NEXT:    scratch_load_b32 v147, off, s33 offset:376
; GISEL64-NEXT:    scratch_load_b32 v148, off, s33 offset:380
; GISEL64-NEXT:    scratch_load_b32 v149, off, s33 offset:384
; GISEL64-NEXT:    scratch_load_b32 v150, off, s33 offset:388
; GISEL64-NEXT:    scratch_load_b32 v151, off, s33 offset:392
; GISEL64-NEXT:    s_clause 0x1f ; 128-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v160, off, s33 offset:396
; GISEL64-NEXT:    scratch_load_b32 v161, off, s33 offset:400
; GISEL64-NEXT:    scratch_load_b32 v162, off, s33 offset:404
; GISEL64-NEXT:    scratch_load_b32 v163, off, s33 offset:408
; GISEL64-NEXT:    scratch_load_b32 v164, off, s33 offset:412
; GISEL64-NEXT:    scratch_load_b32 v165, off, s33 offset:416
; GISEL64-NEXT:    scratch_load_b32 v166, off, s33 offset:420
; GISEL64-NEXT:    scratch_load_b32 v167, off, s33 offset:424
; GISEL64-NEXT:    scratch_load_b32 v176, off, s33 offset:428
; GISEL64-NEXT:    scratch_load_b32 v177, off, s33 offset:432
; GISEL64-NEXT:    scratch_load_b32 v178, off, s33 offset:436
; GISEL64-NEXT:    scratch_load_b32 v179, off, s33 offset:440
; GISEL64-NEXT:    scratch_load_b32 v180, off, s33 offset:444
; GISEL64-NEXT:    scratch_load_b32 v181, off, s33 offset:448
; GISEL64-NEXT:    scratch_load_b32 v182, off, s33 offset:452
; GISEL64-NEXT:    scratch_load_b32 v183, off, s33 offset:456
; GISEL64-NEXT:    scratch_load_b32 v192, off, s33 offset:460
; GISEL64-NEXT:    scratch_load_b32 v193, off, s33 offset:464
; GISEL64-NEXT:    scratch_load_b32 v194, off, s33 offset:468
; GISEL64-NEXT:    scratch_load_b32 v195, off, s33 offset:472
; GISEL64-NEXT:    scratch_load_b32 v196, off, s33 offset:476
; GISEL64-NEXT:    scratch_load_b32 v197, off, s33 offset:480
; GISEL64-NEXT:    scratch_load_b32 v198, off, s33 offset:484
; GISEL64-NEXT:    scratch_load_b32 v199, off, s33 offset:488
; GISEL64-NEXT:    scratch_load_b32 v208, off, s33 offset:492
; GISEL64-NEXT:    scratch_load_b32 v209, off, s33 offset:496
; GISEL64-NEXT:    scratch_load_b32 v210, off, s33 offset:500
; GISEL64-NEXT:    scratch_load_b32 v211, off, s33 offset:504
; GISEL64-NEXT:    scratch_load_b32 v212, off, s33 offset:508
; GISEL64-NEXT:    scratch_load_b32 v213, off, s33 offset:512
; GISEL64-NEXT:    scratch_load_b32 v214, off, s33 offset:516
; GISEL64-NEXT:    scratch_load_b32 v215, off, s33 offset:520
; GISEL64-NEXT:    s_clause 0xf ; 64-byte Folded Reload
; GISEL64-NEXT:    scratch_load_b32 v224, off, s33 offset:524
; GISEL64-NEXT:    scratch_load_b32 v225, off, s33 offset:528
; GISEL64-NEXT:    scratch_load_b32 v226, off, s33 offset:532
; GISEL64-NEXT:    scratch_load_b32 v227, off, s33 offset:536
; GISEL64-NEXT:    scratch_load_b32 v228, off, s33 offset:540
; GISEL64-NEXT:    scratch_load_b32 v229, off, s33 offset:544
; GISEL64-NEXT:    scratch_load_b32 v230, off, s33 offset:548
; GISEL64-NEXT:    scratch_load_b32 v231, off, s33 offset:552
; GISEL64-NEXT:    scratch_load_b32 v240, off, s33 offset:556
; GISEL64-NEXT:    scratch_load_b32 v241, off, s33 offset:560
; GISEL64-NEXT:    scratch_load_b32 v242, off, s33 offset:564
; GISEL64-NEXT:    scratch_load_b32 v243, off, s33 offset:568
; GISEL64-NEXT:    scratch_load_b32 v244, off, s33 offset:572
; GISEL64-NEXT:    scratch_load_b32 v245, off, s33 offset:576
; GISEL64-NEXT:    scratch_load_b32 v246, off, s33 offset:580
; GISEL64-NEXT:    scratch_load_b32 v247, off, s33 offset:584
; GISEL64-NEXT:    s_mov_b64 exec, s[4:5]
; GISEL64-NEXT:    s_mov_b32 s33, s0
; GISEL64-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL64-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GISEL64-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-DAGISEL-LABEL: call_from_whole_wave:
; GFX1250-DAGISEL:       ; %bb.0:
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-DAGISEL-NEXT:    s_wait_kmcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s0, s33
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s33, s32
; GFX1250-DAGISEL-NEXT:    s_xor_saveexec_b32 s4, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0, s33 offset:4 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1, s33 offset:8 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v2, s33 offset:12 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v3, s33 offset:16 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v4, s33 offset:20 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v5, s33 offset:24 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v6, s33 offset:28 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v7, s33 offset:32 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v8, s33 offset:36 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v9, s33 offset:40 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v10, s33 offset:44 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v11, s33 offset:48 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v12, s33 offset:52 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v13, s33 offset:56 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v14, s33 offset:60 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v15, s33 offset:64 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v16, s33 offset:68 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v17, s33 offset:72 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v18, s33 offset:76 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v19, s33 offset:80 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v20, s33 offset:84 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v21, s33 offset:88 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v22, s33 offset:92 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v23, s33 offset:96 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v24, s33 offset:100 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v25, s33 offset:104 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v26, s33 offset:108 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v27, s33 offset:112 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v28, s33 offset:116 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v29, s33 offset:120 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v30, s33 offset:124 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v31, s33 offset:128 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v32, s33 offset:132 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v33, s33 offset:136 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v34, s33 offset:140 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v35, s33 offset:144 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v36, s33 offset:148 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v37, s33 offset:152 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v38, s33 offset:156 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v39, s33 offset:160 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v48, s33 offset:172 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v49, s33 offset:176 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v50, s33 offset:180 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v51, s33 offset:184 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v52, s33 offset:188 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v53, s33 offset:192 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v54, s33 offset:196 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v55, s33 offset:200 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v64, s33 offset:204 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v65, s33 offset:208 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v66, s33 offset:212 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v67, s33 offset:216 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v68, s33 offset:220 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v69, s33 offset:224 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v70, s33 offset:228 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v71, s33 offset:232 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v80, s33 offset:236 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v81, s33 offset:240 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v82, s33 offset:244 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v83, s33 offset:248 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v84, s33 offset:252 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v85, s33 offset:256 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v86, s33 offset:260 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v87, s33 offset:264 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v96, s33 offset:268 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v97, s33 offset:272 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v98, s33 offset:276 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v99, s33 offset:280 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v100, s33 offset:284 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v101, s33 offset:288 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v102, s33 offset:292 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v103, s33 offset:296 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v112, s33 offset:300 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v113, s33 offset:304 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v114, s33 offset:308 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v115, s33 offset:312 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v116, s33 offset:316 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v117, s33 offset:320 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v118, s33 offset:324 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v119, s33 offset:328 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v128, s33 offset:332 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v129, s33 offset:336 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v130, s33 offset:340 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v131, s33 offset:344 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v132, s33 offset:348 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v133, s33 offset:352 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v134, s33 offset:356 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v135, s33 offset:360 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v144, s33 offset:364 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v145, s33 offset:368 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v146, s33 offset:372 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v147, s33 offset:376 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v148, s33 offset:380 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v149, s33 offset:384 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v150, s33 offset:388 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v151, s33 offset:392 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v160, s33 offset:396 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v161, s33 offset:400 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v162, s33 offset:404 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v163, s33 offset:408 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v164, s33 offset:412 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v165, s33 offset:416 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v166, s33 offset:420 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v167, s33 offset:424 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v176, s33 offset:428 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v177, s33 offset:432 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v178, s33 offset:436 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v179, s33 offset:440 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v180, s33 offset:444 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v181, s33 offset:448 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v182, s33 offset:452 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v183, s33 offset:456 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v192, s33 offset:460 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v193, s33 offset:464 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v194, s33 offset:468 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v195, s33 offset:472 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v196, s33 offset:476 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v197, s33 offset:480 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v198, s33 offset:484 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v199, s33 offset:488 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v208, s33 offset:492 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v209, s33 offset:496 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v210, s33 offset:500 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v211, s33 offset:504 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v212, s33 offset:508 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v213, s33 offset:512 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v214, s33 offset:516 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v215, s33 offset:520 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v224, s33 offset:524 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v225, s33 offset:528 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v226, s33 offset:532 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v227, s33 offset:536 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v228, s33 offset:540 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v229, s33 offset:544 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v230, s33 offset:548 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v231, s33 offset:552 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v240, s33 offset:556 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v241, s33 offset:560 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v242, s33 offset:564 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v243, s33 offset:568 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v244, s33 offset:572 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v245, s33 offset:576 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v246, s33 offset:580 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v247, s33 offset:584 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 4 ; msbs: dst=0 src0=0 src1=1 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0 /*v256*/, s33 offset:588 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1 /*v257*/, s33 offset:592 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v2 /*v258*/, s33 offset:596 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v3 /*v259*/, s33 offset:600 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v4 /*v260*/, s33 offset:604 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v5 /*v261*/, s33 offset:608 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v6 /*v262*/, s33 offset:612 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v7 /*v263*/, s33 offset:616 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v8 /*v264*/, s33 offset:620 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v9 /*v265*/, s33 offset:624 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v10 /*v266*/, s33 offset:628 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v11 /*v267*/, s33 offset:632 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v12 /*v268*/, s33 offset:636 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v13 /*v269*/, s33 offset:640 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v14 /*v270*/, s33 offset:644 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v15 /*v271*/, s33 offset:648 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v16 /*v272*/, s33 offset:652 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v17 /*v273*/, s33 offset:656 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v18 /*v274*/, s33 offset:660 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v19 /*v275*/, s33 offset:664 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v20 /*v276*/, s33 offset:668 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v21 /*v277*/, s33 offset:672 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v22 /*v278*/, s33 offset:676 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v23 /*v279*/, s33 offset:680 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v24 /*v280*/, s33 offset:684 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v25 /*v281*/, s33 offset:688 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v26 /*v282*/, s33 offset:692 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v27 /*v283*/, s33 offset:696 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v28 /*v284*/, s33 offset:700 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v29 /*v285*/, s33 offset:704 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v30 /*v286*/, s33 offset:708 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v31 /*v287*/, s33 offset:712 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v32 /*v288*/, s33 offset:716 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v33 /*v289*/, s33 offset:720 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v34 /*v290*/, s33 offset:724 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v35 /*v291*/, s33 offset:728 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v36 /*v292*/, s33 offset:732 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v37 /*v293*/, s33 offset:736 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v38 /*v294*/, s33 offset:740 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v39 /*v295*/, s33 offset:744 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v40 /*v296*/, s33 offset:748 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v41 /*v297*/, s33 offset:752 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v42 /*v298*/, s33 offset:756 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v43 /*v299*/, s33 offset:760 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v44 /*v300*/, s33 offset:764 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v45 /*v301*/, s33 offset:768 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v46 /*v302*/, s33 offset:772 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v47 /*v303*/, s33 offset:776 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v48 /*v304*/, s33 offset:780 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v49 /*v305*/, s33 offset:784 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v50 /*v306*/, s33 offset:788 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v51 /*v307*/, s33 offset:792 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v52 /*v308*/, s33 offset:796 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v53 /*v309*/, s33 offset:800 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v54 /*v310*/, s33 offset:804 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v55 /*v311*/, s33 offset:808 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v56 /*v312*/, s33 offset:812 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v57 /*v313*/, s33 offset:816 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v58 /*v314*/, s33 offset:820 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v59 /*v315*/, s33 offset:824 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v60 /*v316*/, s33 offset:828 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v61 /*v317*/, s33 offset:832 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v62 /*v318*/, s33 offset:836 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v63 /*v319*/, s33 offset:840 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v64 /*v320*/, s33 offset:844 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v65 /*v321*/, s33 offset:848 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v66 /*v322*/, s33 offset:852 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v67 /*v323*/, s33 offset:856 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v68 /*v324*/, s33 offset:860 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v69 /*v325*/, s33 offset:864 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v70 /*v326*/, s33 offset:868 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v71 /*v327*/, s33 offset:872 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v72 /*v328*/, s33 offset:876 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v73 /*v329*/, s33 offset:880 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v74 /*v330*/, s33 offset:884 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v75 /*v331*/, s33 offset:888 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v76 /*v332*/, s33 offset:892 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v77 /*v333*/, s33 offset:896 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v78 /*v334*/, s33 offset:900 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v79 /*v335*/, s33 offset:904 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v80 /*v336*/, s33 offset:908 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v81 /*v337*/, s33 offset:912 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v82 /*v338*/, s33 offset:916 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v83 /*v339*/, s33 offset:920 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v84 /*v340*/, s33 offset:924 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v85 /*v341*/, s33 offset:928 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v86 /*v342*/, s33 offset:932 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v87 /*v343*/, s33 offset:936 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v88 /*v344*/, s33 offset:940 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v89 /*v345*/, s33 offset:944 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v90 /*v346*/, s33 offset:948 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v91 /*v347*/, s33 offset:952 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v92 /*v348*/, s33 offset:956 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v93 /*v349*/, s33 offset:960 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v94 /*v350*/, s33 offset:964 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v95 /*v351*/, s33 offset:968 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v96 /*v352*/, s33 offset:972 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v97 /*v353*/, s33 offset:976 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v98 /*v354*/, s33 offset:980 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v99 /*v355*/, s33 offset:984 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v100 /*v356*/, s33 offset:988 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v101 /*v357*/, s33 offset:992 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v102 /*v358*/, s33 offset:996 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v103 /*v359*/, s33 offset:1000 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v104 /*v360*/, s33 offset:1004 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v105 /*v361*/, s33 offset:1008 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v106 /*v362*/, s33 offset:1012 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v107 /*v363*/, s33 offset:1016 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v108 /*v364*/, s33 offset:1020 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v109 /*v365*/, s33 offset:1024 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v110 /*v366*/, s33 offset:1028 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v111 /*v367*/, s33 offset:1032 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v112 /*v368*/, s33 offset:1036 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v113 /*v369*/, s33 offset:1040 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v114 /*v370*/, s33 offset:1044 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v115 /*v371*/, s33 offset:1048 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v116 /*v372*/, s33 offset:1052 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v117 /*v373*/, s33 offset:1056 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v118 /*v374*/, s33 offset:1060 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v119 /*v375*/, s33 offset:1064 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v120 /*v376*/, s33 offset:1068 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v121 /*v377*/, s33 offset:1072 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v122 /*v378*/, s33 offset:1076 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v123 /*v379*/, s33 offset:1080 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v124 /*v380*/, s33 offset:1084 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v125 /*v381*/, s33 offset:1088 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v126 /*v382*/, s33 offset:1092 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v127 /*v383*/, s33 offset:1096 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v128 /*v384*/, s33 offset:1100 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v129 /*v385*/, s33 offset:1104 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v130 /*v386*/, s33 offset:1108 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v131 /*v387*/, s33 offset:1112 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v132 /*v388*/, s33 offset:1116 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v133 /*v389*/, s33 offset:1120 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v134 /*v390*/, s33 offset:1124 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v135 /*v391*/, s33 offset:1128 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v136 /*v392*/, s33 offset:1132 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v137 /*v393*/, s33 offset:1136 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v138 /*v394*/, s33 offset:1140 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v139 /*v395*/, s33 offset:1144 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v140 /*v396*/, s33 offset:1148 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v141 /*v397*/, s33 offset:1152 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v142 /*v398*/, s33 offset:1156 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v143 /*v399*/, s33 offset:1160 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v144 /*v400*/, s33 offset:1164 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v145 /*v401*/, s33 offset:1168 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v146 /*v402*/, s33 offset:1172 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v147 /*v403*/, s33 offset:1176 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v148 /*v404*/, s33 offset:1180 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v149 /*v405*/, s33 offset:1184 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v150 /*v406*/, s33 offset:1188 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v151 /*v407*/, s33 offset:1192 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v152 /*v408*/, s33 offset:1196 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v153 /*v409*/, s33 offset:1200 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v154 /*v410*/, s33 offset:1204 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v155 /*v411*/, s33 offset:1208 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v156 /*v412*/, s33 offset:1212 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v157 /*v413*/, s33 offset:1216 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v158 /*v414*/, s33 offset:1220 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v159 /*v415*/, s33 offset:1224 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v160 /*v416*/, s33 offset:1228 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v161 /*v417*/, s33 offset:1232 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v162 /*v418*/, s33 offset:1236 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v163 /*v419*/, s33 offset:1240 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v164 /*v420*/, s33 offset:1244 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v165 /*v421*/, s33 offset:1248 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v166 /*v422*/, s33 offset:1252 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v167 /*v423*/, s33 offset:1256 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v168 /*v424*/, s33 offset:1260 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v169 /*v425*/, s33 offset:1264 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v170 /*v426*/, s33 offset:1268 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v171 /*v427*/, s33 offset:1272 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v172 /*v428*/, s33 offset:1276 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v173 /*v429*/, s33 offset:1280 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v174 /*v430*/, s33 offset:1284 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v175 /*v431*/, s33 offset:1288 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v176 /*v432*/, s33 offset:1292 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v177 /*v433*/, s33 offset:1296 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v178 /*v434*/, s33 offset:1300 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v179 /*v435*/, s33 offset:1304 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v180 /*v436*/, s33 offset:1308 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v181 /*v437*/, s33 offset:1312 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v182 /*v438*/, s33 offset:1316 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v183 /*v439*/, s33 offset:1320 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v184 /*v440*/, s33 offset:1324 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v185 /*v441*/, s33 offset:1328 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v186 /*v442*/, s33 offset:1332 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v187 /*v443*/, s33 offset:1336 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v188 /*v444*/, s33 offset:1340 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v189 /*v445*/, s33 offset:1344 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v190 /*v446*/, s33 offset:1348 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v191 /*v447*/, s33 offset:1352 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v192 /*v448*/, s33 offset:1356 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v193 /*v449*/, s33 offset:1360 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v194 /*v450*/, s33 offset:1364 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v195 /*v451*/, s33 offset:1368 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v196 /*v452*/, s33 offset:1372 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v197 /*v453*/, s33 offset:1376 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v198 /*v454*/, s33 offset:1380 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v199 /*v455*/, s33 offset:1384 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v200 /*v456*/, s33 offset:1388 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v201 /*v457*/, s33 offset:1392 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v202 /*v458*/, s33 offset:1396 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v203 /*v459*/, s33 offset:1400 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v204 /*v460*/, s33 offset:1404 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v205 /*v461*/, s33 offset:1408 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v206 /*v462*/, s33 offset:1412 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v207 /*v463*/, s33 offset:1416 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v208 /*v464*/, s33 offset:1420 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v209 /*v465*/, s33 offset:1424 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v210 /*v466*/, s33 offset:1428 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v211 /*v467*/, s33 offset:1432 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v212 /*v468*/, s33 offset:1436 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v213 /*v469*/, s33 offset:1440 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v214 /*v470*/, s33 offset:1444 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v215 /*v471*/, s33 offset:1448 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v216 /*v472*/, s33 offset:1452 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v217 /*v473*/, s33 offset:1456 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v218 /*v474*/, s33 offset:1460 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v219 /*v475*/, s33 offset:1464 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v220 /*v476*/, s33 offset:1468 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v221 /*v477*/, s33 offset:1472 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v222 /*v478*/, s33 offset:1476 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v223 /*v479*/, s33 offset:1480 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v224 /*v480*/, s33 offset:1484 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v225 /*v481*/, s33 offset:1488 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v226 /*v482*/, s33 offset:1492 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v227 /*v483*/, s33 offset:1496 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v228 /*v484*/, s33 offset:1500 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v229 /*v485*/, s33 offset:1504 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v230 /*v486*/, s33 offset:1508 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v231 /*v487*/, s33 offset:1512 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v232 /*v488*/, s33 offset:1516 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v233 /*v489*/, s33 offset:1520 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v234 /*v490*/, s33 offset:1524 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v235 /*v491*/, s33 offset:1528 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v236 /*v492*/, s33 offset:1532 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v237 /*v493*/, s33 offset:1536 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v238 /*v494*/, s33 offset:1540 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v239 /*v495*/, s33 offset:1544 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v240 /*v496*/, s33 offset:1548 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v241 /*v497*/, s33 offset:1552 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v242 /*v498*/, s33 offset:1556 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v243 /*v499*/, s33 offset:1560 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v244 /*v500*/, s33 offset:1564 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v245 /*v501*/, s33 offset:1568 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v246 /*v502*/, s33 offset:1572 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v247 /*v503*/, s33 offset:1576 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v248 /*v504*/, s33 offset:1580 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v249 /*v505*/, s33 offset:1584 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v250 /*v506*/, s33 offset:1588 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v251 /*v507*/, s33 offset:1592 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v252 /*v508*/, s33 offset:1596 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v253 /*v509*/, s33 offset:1600 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v254 /*v510*/, s33 offset:1604 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v255 /*v511*/, s33 offset:1608 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0x408 ; msbs: dst=0 src0=0 src1=2 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0 /*v512*/, s33 offset:1612 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1 /*v513*/, s33 offset:1616 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v2 /*v514*/, s33 offset:1620 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v3 /*v515*/, s33 offset:1624 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v4 /*v516*/, s33 offset:1628 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v5 /*v517*/, s33 offset:1632 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v6 /*v518*/, s33 offset:1636 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v7 /*v519*/, s33 offset:1640 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v8 /*v520*/, s33 offset:1644 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v9 /*v521*/, s33 offset:1648 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v10 /*v522*/, s33 offset:1652 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v11 /*v523*/, s33 offset:1656 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v12 /*v524*/, s33 offset:1660 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v13 /*v525*/, s33 offset:1664 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v14 /*v526*/, s33 offset:1668 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v15 /*v527*/, s33 offset:1672 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v16 /*v528*/, s33 offset:1676 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v17 /*v529*/, s33 offset:1680 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v18 /*v530*/, s33 offset:1684 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v19 /*v531*/, s33 offset:1688 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v20 /*v532*/, s33 offset:1692 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v21 /*v533*/, s33 offset:1696 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v22 /*v534*/, s33 offset:1700 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v23 /*v535*/, s33 offset:1704 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v24 /*v536*/, s33 offset:1708 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v25 /*v537*/, s33 offset:1712 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v26 /*v538*/, s33 offset:1716 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v27 /*v539*/, s33 offset:1720 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v28 /*v540*/, s33 offset:1724 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v29 /*v541*/, s33 offset:1728 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v30 /*v542*/, s33 offset:1732 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v31 /*v543*/, s33 offset:1736 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v32 /*v544*/, s33 offset:1740 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v33 /*v545*/, s33 offset:1744 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v34 /*v546*/, s33 offset:1748 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v35 /*v547*/, s33 offset:1752 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v36 /*v548*/, s33 offset:1756 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v37 /*v549*/, s33 offset:1760 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v38 /*v550*/, s33 offset:1764 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v39 /*v551*/, s33 offset:1768 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v40 /*v552*/, s33 offset:1772 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v41 /*v553*/, s33 offset:1776 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v42 /*v554*/, s33 offset:1780 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v43 /*v555*/, s33 offset:1784 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v44 /*v556*/, s33 offset:1788 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v45 /*v557*/, s33 offset:1792 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v46 /*v558*/, s33 offset:1796 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v47 /*v559*/, s33 offset:1800 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v48 /*v560*/, s33 offset:1804 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v49 /*v561*/, s33 offset:1808 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v50 /*v562*/, s33 offset:1812 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v51 /*v563*/, s33 offset:1816 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v52 /*v564*/, s33 offset:1820 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v53 /*v565*/, s33 offset:1824 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v54 /*v566*/, s33 offset:1828 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v55 /*v567*/, s33 offset:1832 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v56 /*v568*/, s33 offset:1836 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v57 /*v569*/, s33 offset:1840 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v58 /*v570*/, s33 offset:1844 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v59 /*v571*/, s33 offset:1848 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v60 /*v572*/, s33 offset:1852 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v61 /*v573*/, s33 offset:1856 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v62 /*v574*/, s33 offset:1860 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v63 /*v575*/, s33 offset:1864 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v64 /*v576*/, s33 offset:1868 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v65 /*v577*/, s33 offset:1872 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v66 /*v578*/, s33 offset:1876 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v67 /*v579*/, s33 offset:1880 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v68 /*v580*/, s33 offset:1884 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v69 /*v581*/, s33 offset:1888 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v70 /*v582*/, s33 offset:1892 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v71 /*v583*/, s33 offset:1896 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v72 /*v584*/, s33 offset:1900 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v73 /*v585*/, s33 offset:1904 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v74 /*v586*/, s33 offset:1908 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v75 /*v587*/, s33 offset:1912 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v76 /*v588*/, s33 offset:1916 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v77 /*v589*/, s33 offset:1920 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v78 /*v590*/, s33 offset:1924 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v79 /*v591*/, s33 offset:1928 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v80 /*v592*/, s33 offset:1932 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v81 /*v593*/, s33 offset:1936 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v82 /*v594*/, s33 offset:1940 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v83 /*v595*/, s33 offset:1944 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v84 /*v596*/, s33 offset:1948 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v85 /*v597*/, s33 offset:1952 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v86 /*v598*/, s33 offset:1956 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v87 /*v599*/, s33 offset:1960 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v88 /*v600*/, s33 offset:1964 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v89 /*v601*/, s33 offset:1968 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v90 /*v602*/, s33 offset:1972 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v91 /*v603*/, s33 offset:1976 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v92 /*v604*/, s33 offset:1980 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v93 /*v605*/, s33 offset:1984 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v94 /*v606*/, s33 offset:1988 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v95 /*v607*/, s33 offset:1992 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v96 /*v608*/, s33 offset:1996 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v97 /*v609*/, s33 offset:2000 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v98 /*v610*/, s33 offset:2004 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v99 /*v611*/, s33 offset:2008 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v100 /*v612*/, s33 offset:2012 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v101 /*v613*/, s33 offset:2016 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v102 /*v614*/, s33 offset:2020 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v103 /*v615*/, s33 offset:2024 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v104 /*v616*/, s33 offset:2028 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v105 /*v617*/, s33 offset:2032 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v106 /*v618*/, s33 offset:2036 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v107 /*v619*/, s33 offset:2040 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v108 /*v620*/, s33 offset:2044 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v109 /*v621*/, s33 offset:2048 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v110 /*v622*/, s33 offset:2052 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v111 /*v623*/, s33 offset:2056 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v112 /*v624*/, s33 offset:2060 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v113 /*v625*/, s33 offset:2064 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v114 /*v626*/, s33 offset:2068 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v115 /*v627*/, s33 offset:2072 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v116 /*v628*/, s33 offset:2076 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v117 /*v629*/, s33 offset:2080 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v118 /*v630*/, s33 offset:2084 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v119 /*v631*/, s33 offset:2088 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v120 /*v632*/, s33 offset:2092 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v121 /*v633*/, s33 offset:2096 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v122 /*v634*/, s33 offset:2100 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v123 /*v635*/, s33 offset:2104 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v124 /*v636*/, s33 offset:2108 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v125 /*v637*/, s33 offset:2112 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v126 /*v638*/, s33 offset:2116 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v127 /*v639*/, s33 offset:2120 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v128 /*v640*/, s33 offset:2124 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v129 /*v641*/, s33 offset:2128 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v130 /*v642*/, s33 offset:2132 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v131 /*v643*/, s33 offset:2136 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v132 /*v644*/, s33 offset:2140 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v133 /*v645*/, s33 offset:2144 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v134 /*v646*/, s33 offset:2148 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v135 /*v647*/, s33 offset:2152 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v136 /*v648*/, s33 offset:2156 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v137 /*v649*/, s33 offset:2160 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v138 /*v650*/, s33 offset:2164 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v139 /*v651*/, s33 offset:2168 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v140 /*v652*/, s33 offset:2172 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v141 /*v653*/, s33 offset:2176 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v142 /*v654*/, s33 offset:2180 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v143 /*v655*/, s33 offset:2184 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v144 /*v656*/, s33 offset:2188 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v145 /*v657*/, s33 offset:2192 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v146 /*v658*/, s33 offset:2196 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v147 /*v659*/, s33 offset:2200 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v148 /*v660*/, s33 offset:2204 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v149 /*v661*/, s33 offset:2208 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v150 /*v662*/, s33 offset:2212 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v151 /*v663*/, s33 offset:2216 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v152 /*v664*/, s33 offset:2220 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v153 /*v665*/, s33 offset:2224 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v154 /*v666*/, s33 offset:2228 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v155 /*v667*/, s33 offset:2232 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v156 /*v668*/, s33 offset:2236 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v157 /*v669*/, s33 offset:2240 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v158 /*v670*/, s33 offset:2244 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v159 /*v671*/, s33 offset:2248 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v160 /*v672*/, s33 offset:2252 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v161 /*v673*/, s33 offset:2256 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v162 /*v674*/, s33 offset:2260 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v163 /*v675*/, s33 offset:2264 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v164 /*v676*/, s33 offset:2268 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v165 /*v677*/, s33 offset:2272 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v166 /*v678*/, s33 offset:2276 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v167 /*v679*/, s33 offset:2280 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v168 /*v680*/, s33 offset:2284 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v169 /*v681*/, s33 offset:2288 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v170 /*v682*/, s33 offset:2292 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v171 /*v683*/, s33 offset:2296 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v172 /*v684*/, s33 offset:2300 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v173 /*v685*/, s33 offset:2304 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v174 /*v686*/, s33 offset:2308 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v175 /*v687*/, s33 offset:2312 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v176 /*v688*/, s33 offset:2316 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v177 /*v689*/, s33 offset:2320 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v178 /*v690*/, s33 offset:2324 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v179 /*v691*/, s33 offset:2328 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v180 /*v692*/, s33 offset:2332 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v181 /*v693*/, s33 offset:2336 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v182 /*v694*/, s33 offset:2340 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v183 /*v695*/, s33 offset:2344 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v184 /*v696*/, s33 offset:2348 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v185 /*v697*/, s33 offset:2352 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v186 /*v698*/, s33 offset:2356 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v187 /*v699*/, s33 offset:2360 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v188 /*v700*/, s33 offset:2364 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v189 /*v701*/, s33 offset:2368 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v190 /*v702*/, s33 offset:2372 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v191 /*v703*/, s33 offset:2376 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v192 /*v704*/, s33 offset:2380 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v193 /*v705*/, s33 offset:2384 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v194 /*v706*/, s33 offset:2388 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v195 /*v707*/, s33 offset:2392 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v196 /*v708*/, s33 offset:2396 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v197 /*v709*/, s33 offset:2400 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v198 /*v710*/, s33 offset:2404 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v199 /*v711*/, s33 offset:2408 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v200 /*v712*/, s33 offset:2412 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v201 /*v713*/, s33 offset:2416 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v202 /*v714*/, s33 offset:2420 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v203 /*v715*/, s33 offset:2424 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v204 /*v716*/, s33 offset:2428 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v205 /*v717*/, s33 offset:2432 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v206 /*v718*/, s33 offset:2436 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v207 /*v719*/, s33 offset:2440 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v208 /*v720*/, s33 offset:2444 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v209 /*v721*/, s33 offset:2448 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v210 /*v722*/, s33 offset:2452 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v211 /*v723*/, s33 offset:2456 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v212 /*v724*/, s33 offset:2460 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v213 /*v725*/, s33 offset:2464 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v214 /*v726*/, s33 offset:2468 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v215 /*v727*/, s33 offset:2472 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v216 /*v728*/, s33 offset:2476 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v217 /*v729*/, s33 offset:2480 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v218 /*v730*/, s33 offset:2484 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v219 /*v731*/, s33 offset:2488 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v220 /*v732*/, s33 offset:2492 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v221 /*v733*/, s33 offset:2496 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v222 /*v734*/, s33 offset:2500 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v223 /*v735*/, s33 offset:2504 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v224 /*v736*/, s33 offset:2508 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v225 /*v737*/, s33 offset:2512 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v226 /*v738*/, s33 offset:2516 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v227 /*v739*/, s33 offset:2520 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v228 /*v740*/, s33 offset:2524 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v229 /*v741*/, s33 offset:2528 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v230 /*v742*/, s33 offset:2532 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v231 /*v743*/, s33 offset:2536 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v232 /*v744*/, s33 offset:2540 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v233 /*v745*/, s33 offset:2544 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v234 /*v746*/, s33 offset:2548 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v235 /*v747*/, s33 offset:2552 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v236 /*v748*/, s33 offset:2556 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v237 /*v749*/, s33 offset:2560 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v238 /*v750*/, s33 offset:2564 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v239 /*v751*/, s33 offset:2568 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v240 /*v752*/, s33 offset:2572 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v241 /*v753*/, s33 offset:2576 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v242 /*v754*/, s33 offset:2580 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v243 /*v755*/, s33 offset:2584 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v244 /*v756*/, s33 offset:2588 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v245 /*v757*/, s33 offset:2592 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v246 /*v758*/, s33 offset:2596 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v247 /*v759*/, s33 offset:2600 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v248 /*v760*/, s33 offset:2604 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v249 /*v761*/, s33 offset:2608 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v250 /*v762*/, s33 offset:2612 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v251 /*v763*/, s33 offset:2616 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v252 /*v764*/, s33 offset:2620 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v253 /*v765*/, s33 offset:2624 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v254 /*v766*/, s33 offset:2628 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v255 /*v767*/, s33 offset:2632 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0x80c ; msbs: dst=0 src0=0 src1=3 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v0 /*v768*/, s33 offset:2636 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v1 /*v769*/, s33 offset:2640 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v2 /*v770*/, s33 offset:2644 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v3 /*v771*/, s33 offset:2648 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v4 /*v772*/, s33 offset:2652 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v5 /*v773*/, s33 offset:2656 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v6 /*v774*/, s33 offset:2660 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v7 /*v775*/, s33 offset:2664 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v8 /*v776*/, s33 offset:2668 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v9 /*v777*/, s33 offset:2672 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v10 /*v778*/, s33 offset:2676 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v11 /*v779*/, s33 offset:2680 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v12 /*v780*/, s33 offset:2684 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v13 /*v781*/, s33 offset:2688 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v14 /*v782*/, s33 offset:2692 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v15 /*v783*/, s33 offset:2696 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v16 /*v784*/, s33 offset:2700 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v17 /*v785*/, s33 offset:2704 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v18 /*v786*/, s33 offset:2708 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v19 /*v787*/, s33 offset:2712 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v20 /*v788*/, s33 offset:2716 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v21 /*v789*/, s33 offset:2720 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v22 /*v790*/, s33 offset:2724 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v23 /*v791*/, s33 offset:2728 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v24 /*v792*/, s33 offset:2732 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v25 /*v793*/, s33 offset:2736 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v26 /*v794*/, s33 offset:2740 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v27 /*v795*/, s33 offset:2744 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v28 /*v796*/, s33 offset:2748 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v29 /*v797*/, s33 offset:2752 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v30 /*v798*/, s33 offset:2756 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v31 /*v799*/, s33 offset:2760 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v32 /*v800*/, s33 offset:2764 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v33 /*v801*/, s33 offset:2768 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v34 /*v802*/, s33 offset:2772 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v35 /*v803*/, s33 offset:2776 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v36 /*v804*/, s33 offset:2780 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v37 /*v805*/, s33 offset:2784 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v38 /*v806*/, s33 offset:2788 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v39 /*v807*/, s33 offset:2792 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v40 /*v808*/, s33 offset:2796 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v41 /*v809*/, s33 offset:2800 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v42 /*v810*/, s33 offset:2804 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v43 /*v811*/, s33 offset:2808 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v44 /*v812*/, s33 offset:2812 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v45 /*v813*/, s33 offset:2816 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v46 /*v814*/, s33 offset:2820 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v47 /*v815*/, s33 offset:2824 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v48 /*v816*/, s33 offset:2828 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v49 /*v817*/, s33 offset:2832 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v50 /*v818*/, s33 offset:2836 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v51 /*v819*/, s33 offset:2840 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v52 /*v820*/, s33 offset:2844 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v53 /*v821*/, s33 offset:2848 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v54 /*v822*/, s33 offset:2852 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v55 /*v823*/, s33 offset:2856 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v56 /*v824*/, s33 offset:2860 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v57 /*v825*/, s33 offset:2864 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v58 /*v826*/, s33 offset:2868 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v59 /*v827*/, s33 offset:2872 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v60 /*v828*/, s33 offset:2876 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v61 /*v829*/, s33 offset:2880 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v62 /*v830*/, s33 offset:2884 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v63 /*v831*/, s33 offset:2888 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v64 /*v832*/, s33 offset:2892 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v65 /*v833*/, s33 offset:2896 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v66 /*v834*/, s33 offset:2900 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v67 /*v835*/, s33 offset:2904 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v68 /*v836*/, s33 offset:2908 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v69 /*v837*/, s33 offset:2912 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v70 /*v838*/, s33 offset:2916 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v71 /*v839*/, s33 offset:2920 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v72 /*v840*/, s33 offset:2924 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v73 /*v841*/, s33 offset:2928 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v74 /*v842*/, s33 offset:2932 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v75 /*v843*/, s33 offset:2936 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v76 /*v844*/, s33 offset:2940 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v77 /*v845*/, s33 offset:2944 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v78 /*v846*/, s33 offset:2948 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v79 /*v847*/, s33 offset:2952 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v80 /*v848*/, s33 offset:2956 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v81 /*v849*/, s33 offset:2960 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v82 /*v850*/, s33 offset:2964 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v83 /*v851*/, s33 offset:2968 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v84 /*v852*/, s33 offset:2972 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v85 /*v853*/, s33 offset:2976 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v86 /*v854*/, s33 offset:2980 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v87 /*v855*/, s33 offset:2984 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v88 /*v856*/, s33 offset:2988 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v89 /*v857*/, s33 offset:2992 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v90 /*v858*/, s33 offset:2996 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v91 /*v859*/, s33 offset:3000 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v92 /*v860*/, s33 offset:3004 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v93 /*v861*/, s33 offset:3008 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v94 /*v862*/, s33 offset:3012 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v95 /*v863*/, s33 offset:3016 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v96 /*v864*/, s33 offset:3020 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v97 /*v865*/, s33 offset:3024 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v98 /*v866*/, s33 offset:3028 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v99 /*v867*/, s33 offset:3032 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v100 /*v868*/, s33 offset:3036 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v101 /*v869*/, s33 offset:3040 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v102 /*v870*/, s33 offset:3044 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v103 /*v871*/, s33 offset:3048 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v104 /*v872*/, s33 offset:3052 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v105 /*v873*/, s33 offset:3056 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v106 /*v874*/, s33 offset:3060 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v107 /*v875*/, s33 offset:3064 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v108 /*v876*/, s33 offset:3068 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v109 /*v877*/, s33 offset:3072 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v110 /*v878*/, s33 offset:3076 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v111 /*v879*/, s33 offset:3080 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v112 /*v880*/, s33 offset:3084 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v113 /*v881*/, s33 offset:3088 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v114 /*v882*/, s33 offset:3092 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v115 /*v883*/, s33 offset:3096 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v116 /*v884*/, s33 offset:3100 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v117 /*v885*/, s33 offset:3104 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v118 /*v886*/, s33 offset:3108 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v119 /*v887*/, s33 offset:3112 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v120 /*v888*/, s33 offset:3116 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v121 /*v889*/, s33 offset:3120 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v122 /*v890*/, s33 offset:3124 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v123 /*v891*/, s33 offset:3128 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v124 /*v892*/, s33 offset:3132 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v125 /*v893*/, s33 offset:3136 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v126 /*v894*/, s33 offset:3140 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v127 /*v895*/, s33 offset:3144 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v128 /*v896*/, s33 offset:3148 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v129 /*v897*/, s33 offset:3152 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v130 /*v898*/, s33 offset:3156 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v131 /*v899*/, s33 offset:3160 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v132 /*v900*/, s33 offset:3164 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v133 /*v901*/, s33 offset:3168 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v134 /*v902*/, s33 offset:3172 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v135 /*v903*/, s33 offset:3176 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v136 /*v904*/, s33 offset:3180 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v137 /*v905*/, s33 offset:3184 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v138 /*v906*/, s33 offset:3188 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v139 /*v907*/, s33 offset:3192 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v140 /*v908*/, s33 offset:3196 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v141 /*v909*/, s33 offset:3200 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v142 /*v910*/, s33 offset:3204 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v143 /*v911*/, s33 offset:3208 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v144 /*v912*/, s33 offset:3212 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v145 /*v913*/, s33 offset:3216 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v146 /*v914*/, s33 offset:3220 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v147 /*v915*/, s33 offset:3224 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v148 /*v916*/, s33 offset:3228 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v149 /*v917*/, s33 offset:3232 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v150 /*v918*/, s33 offset:3236 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v151 /*v919*/, s33 offset:3240 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v152 /*v920*/, s33 offset:3244 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v153 /*v921*/, s33 offset:3248 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v154 /*v922*/, s33 offset:3252 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v155 /*v923*/, s33 offset:3256 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v156 /*v924*/, s33 offset:3260 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v157 /*v925*/, s33 offset:3264 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v158 /*v926*/, s33 offset:3268 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v159 /*v927*/, s33 offset:3272 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v160 /*v928*/, s33 offset:3276 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v161 /*v929*/, s33 offset:3280 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v162 /*v930*/, s33 offset:3284 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v163 /*v931*/, s33 offset:3288 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v164 /*v932*/, s33 offset:3292 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v165 /*v933*/, s33 offset:3296 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v166 /*v934*/, s33 offset:3300 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v167 /*v935*/, s33 offset:3304 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v168 /*v936*/, s33 offset:3308 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v169 /*v937*/, s33 offset:3312 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v170 /*v938*/, s33 offset:3316 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v171 /*v939*/, s33 offset:3320 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v172 /*v940*/, s33 offset:3324 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v173 /*v941*/, s33 offset:3328 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v174 /*v942*/, s33 offset:3332 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v175 /*v943*/, s33 offset:3336 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v176 /*v944*/, s33 offset:3340 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v177 /*v945*/, s33 offset:3344 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v178 /*v946*/, s33 offset:3348 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v179 /*v947*/, s33 offset:3352 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v180 /*v948*/, s33 offset:3356 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v181 /*v949*/, s33 offset:3360 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v182 /*v950*/, s33 offset:3364 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v183 /*v951*/, s33 offset:3368 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v184 /*v952*/, s33 offset:3372 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v185 /*v953*/, s33 offset:3376 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v186 /*v954*/, s33 offset:3380 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v187 /*v955*/, s33 offset:3384 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v188 /*v956*/, s33 offset:3388 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v189 /*v957*/, s33 offset:3392 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v190 /*v958*/, s33 offset:3396 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v191 /*v959*/, s33 offset:3400 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v192 /*v960*/, s33 offset:3404 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v193 /*v961*/, s33 offset:3408 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v194 /*v962*/, s33 offset:3412 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v195 /*v963*/, s33 offset:3416 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v196 /*v964*/, s33 offset:3420 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v197 /*v965*/, s33 offset:3424 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v198 /*v966*/, s33 offset:3428 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v199 /*v967*/, s33 offset:3432 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v200 /*v968*/, s33 offset:3436 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v201 /*v969*/, s33 offset:3440 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v202 /*v970*/, s33 offset:3444 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v203 /*v971*/, s33 offset:3448 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v204 /*v972*/, s33 offset:3452 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v205 /*v973*/, s33 offset:3456 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v206 /*v974*/, s33 offset:3460 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v207 /*v975*/, s33 offset:3464 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v208 /*v976*/, s33 offset:3468 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v209 /*v977*/, s33 offset:3472 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v210 /*v978*/, s33 offset:3476 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v211 /*v979*/, s33 offset:3480 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v212 /*v980*/, s33 offset:3484 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v213 /*v981*/, s33 offset:3488 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v214 /*v982*/, s33 offset:3492 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v215 /*v983*/, s33 offset:3496 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v216 /*v984*/, s33 offset:3500 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v217 /*v985*/, s33 offset:3504 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v218 /*v986*/, s33 offset:3508 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v219 /*v987*/, s33 offset:3512 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v220 /*v988*/, s33 offset:3516 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v221 /*v989*/, s33 offset:3520 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v222 /*v990*/, s33 offset:3524 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v223 /*v991*/, s33 offset:3528 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v224 /*v992*/, s33 offset:3532 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v225 /*v993*/, s33 offset:3536 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x1d ; 120-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v226 /*v994*/, s33 offset:3540 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v227 /*v995*/, s33 offset:3544 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v228 /*v996*/, s33 offset:3548 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v229 /*v997*/, s33 offset:3552 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v230 /*v998*/, s33 offset:3556 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v231 /*v999*/, s33 offset:3560 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v232 /*v1000*/, s33 offset:3564 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v233 /*v1001*/, s33 offset:3568 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v234 /*v1002*/, s33 offset:3572 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v235 /*v1003*/, s33 offset:3576 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v236 /*v1004*/, s33 offset:3580 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v237 /*v1005*/, s33 offset:3584 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v238 /*v1006*/, s33 offset:3588 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v239 /*v1007*/, s33 offset:3592 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v240 /*v1008*/, s33 offset:3596 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v241 /*v1009*/, s33 offset:3600 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v242 /*v1010*/, s33 offset:3604 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v243 /*v1011*/, s33 offset:3608 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v244 /*v1012*/, s33 offset:3612 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v245 /*v1013*/, s33 offset:3616 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v246 /*v1014*/, s33 offset:3620 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v247 /*v1015*/, s33 offset:3624 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v248 /*v1016*/, s33 offset:3628 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v249 /*v1017*/, s33 offset:3632 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v250 /*v1018*/, s33 offset:3636 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v251 /*v1019*/, s33 offset:3640 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v252 /*v1020*/, s33 offset:3644 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v253 /*v1021*/, s33 offset:3648 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v254 /*v1022*/, s33 offset:3652 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v255 /*v1023*/, s33 offset:3656 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, -1
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0xc00 ; msbs: dst=0 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    s_clause 0x2 ; 12-byte Folded Spill
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v42, s33 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v40, s33 offset:164 nv
; GFX1250-DAGISEL-NEXT:    scratch_store_b32 off, v41, s33 offset:168 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x2
; GFX1250-DAGISEL-NEXT:    v_writelane_b32 v42, s0, 3
; GFX1250-DAGISEL-NEXT:    s_mov_b64 s[0:1], callee@abs64
; GFX1250-DAGISEL-NEXT:    s_addk_co_i32 s32, 0xe50
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    v_dual_mov_b32 v41, v9 :: v_dual_mov_b32 v40, v8
; GFX1250-DAGISEL-NEXT:    v_writelane_b32 v42, s4, 0
; GFX1250-DAGISEL-NEXT:    v_writelane_b32 v42, s30, 1
; GFX1250-DAGISEL-NEXT:    v_writelane_b32 v42, s31, 2
; GFX1250-DAGISEL-NEXT:    s_swap_pc_i64 s[30:31], s[0:1]
; GFX1250-DAGISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1250-DAGISEL-NEXT:    v_readlane_b32 s30, v42, 1
; GFX1250-DAGISEL-NEXT:    flat_store_b32 v[40:41], v0
; GFX1250-DAGISEL-NEXT:    v_readlane_b32 s31, v42, 2
; GFX1250-DAGISEL-NEXT:    v_readlane_b32 s4, v42, 0
; GFX1250-DAGISEL-NEXT:    v_readlane_b32 s0, v42, 3
; GFX1250-DAGISEL-NEXT:    s_clause 0x2 ; 12-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v42, off, s33 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v40, off, s33 offset:164 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v41, off, s33 offset:168 nv
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s32, s33
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_xor_b32 exec_lo, s4, -1
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0, off, s33 offset:4 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1, off, s33 offset:8 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v2, off, s33 offset:12 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v3, off, s33 offset:16 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v4, off, s33 offset:20 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v5, off, s33 offset:24 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v6, off, s33 offset:28 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v7, off, s33 offset:32 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v8, off, s33 offset:36 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v9, off, s33 offset:40 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v10, off, s33 offset:44 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v11, off, s33 offset:48 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v12, off, s33 offset:52 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v13, off, s33 offset:56 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v14, off, s33 offset:60 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v15, off, s33 offset:64 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v16, off, s33 offset:68 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v17, off, s33 offset:72 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v18, off, s33 offset:76 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v19, off, s33 offset:80 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v20, off, s33 offset:84 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v21, off, s33 offset:88 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v22, off, s33 offset:92 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v23, off, s33 offset:96 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v24, off, s33 offset:100 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v25, off, s33 offset:104 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v26, off, s33 offset:108 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v27, off, s33 offset:112 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v28, off, s33 offset:116 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v29, off, s33 offset:120 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v30, off, s33 offset:124 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v31, off, s33 offset:128 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v32, off, s33 offset:132 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v33, off, s33 offset:136 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v34, off, s33 offset:140 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v35, off, s33 offset:144 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v36, off, s33 offset:148 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v37, off, s33 offset:152 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v38, off, s33 offset:156 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v39, off, s33 offset:160 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v48, off, s33 offset:172 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v49, off, s33 offset:176 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v50, off, s33 offset:180 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v51, off, s33 offset:184 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v52, off, s33 offset:188 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v53, off, s33 offset:192 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v54, off, s33 offset:196 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v55, off, s33 offset:200 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v64, off, s33 offset:204 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v65, off, s33 offset:208 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v66, off, s33 offset:212 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v67, off, s33 offset:216 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v68, off, s33 offset:220 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v69, off, s33 offset:224 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v70, off, s33 offset:228 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v71, off, s33 offset:232 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v80, off, s33 offset:236 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v81, off, s33 offset:240 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v82, off, s33 offset:244 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v83, off, s33 offset:248 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v84, off, s33 offset:252 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v85, off, s33 offset:256 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v86, off, s33 offset:260 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v87, off, s33 offset:264 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v96, off, s33 offset:268 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v97, off, s33 offset:272 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v98, off, s33 offset:276 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v99, off, s33 offset:280 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v100, off, s33 offset:284 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v101, off, s33 offset:288 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v102, off, s33 offset:292 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v103, off, s33 offset:296 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v112, off, s33 offset:300 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v113, off, s33 offset:304 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v114, off, s33 offset:308 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v115, off, s33 offset:312 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v116, off, s33 offset:316 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v117, off, s33 offset:320 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v118, off, s33 offset:324 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v119, off, s33 offset:328 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v128, off, s33 offset:332 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v129, off, s33 offset:336 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v130, off, s33 offset:340 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v131, off, s33 offset:344 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v132, off, s33 offset:348 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v133, off, s33 offset:352 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v134, off, s33 offset:356 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v135, off, s33 offset:360 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v144, off, s33 offset:364 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v145, off, s33 offset:368 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v146, off, s33 offset:372 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v147, off, s33 offset:376 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v148, off, s33 offset:380 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v149, off, s33 offset:384 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v150, off, s33 offset:388 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v151, off, s33 offset:392 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v160, off, s33 offset:396 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v161, off, s33 offset:400 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v162, off, s33 offset:404 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v163, off, s33 offset:408 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v164, off, s33 offset:412 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v165, off, s33 offset:416 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v166, off, s33 offset:420 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v167, off, s33 offset:424 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v176, off, s33 offset:428 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v177, off, s33 offset:432 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v178, off, s33 offset:436 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v179, off, s33 offset:440 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v180, off, s33 offset:444 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v181, off, s33 offset:448 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v182, off, s33 offset:452 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v183, off, s33 offset:456 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v192, off, s33 offset:460 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v193, off, s33 offset:464 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v194, off, s33 offset:468 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v195, off, s33 offset:472 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v196, off, s33 offset:476 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v197, off, s33 offset:480 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v198, off, s33 offset:484 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v199, off, s33 offset:488 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v208, off, s33 offset:492 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v209, off, s33 offset:496 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v210, off, s33 offset:500 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v211, off, s33 offset:504 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v212, off, s33 offset:508 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v213, off, s33 offset:512 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v214, off, s33 offset:516 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v215, off, s33 offset:520 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v224, off, s33 offset:524 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v225, off, s33 offset:528 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v226, off, s33 offset:532 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v227, off, s33 offset:536 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v228, off, s33 offset:540 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v229, off, s33 offset:544 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v230, off, s33 offset:548 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v231, off, s33 offset:552 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v240, off, s33 offset:556 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v241, off, s33 offset:560 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v242, off, s33 offset:564 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v243, off, s33 offset:568 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v244, off, s33 offset:572 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v245, off, s33 offset:576 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v246, off, s33 offset:580 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v247, off, s33 offset:584 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 64 ; msbs: dst=1 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0 /*v256*/, off, s33 offset:588 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1 /*v257*/, off, s33 offset:592 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v2 /*v258*/, off, s33 offset:596 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v3 /*v259*/, off, s33 offset:600 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v4 /*v260*/, off, s33 offset:604 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v5 /*v261*/, off, s33 offset:608 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v6 /*v262*/, off, s33 offset:612 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v7 /*v263*/, off, s33 offset:616 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v8 /*v264*/, off, s33 offset:620 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v9 /*v265*/, off, s33 offset:624 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v10 /*v266*/, off, s33 offset:628 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v11 /*v267*/, off, s33 offset:632 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v12 /*v268*/, off, s33 offset:636 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v13 /*v269*/, off, s33 offset:640 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v14 /*v270*/, off, s33 offset:644 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v15 /*v271*/, off, s33 offset:648 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v16 /*v272*/, off, s33 offset:652 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v17 /*v273*/, off, s33 offset:656 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v18 /*v274*/, off, s33 offset:660 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v19 /*v275*/, off, s33 offset:664 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v20 /*v276*/, off, s33 offset:668 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v21 /*v277*/, off, s33 offset:672 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v22 /*v278*/, off, s33 offset:676 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v23 /*v279*/, off, s33 offset:680 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v24 /*v280*/, off, s33 offset:684 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v25 /*v281*/, off, s33 offset:688 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v26 /*v282*/, off, s33 offset:692 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v27 /*v283*/, off, s33 offset:696 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v28 /*v284*/, off, s33 offset:700 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v29 /*v285*/, off, s33 offset:704 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v30 /*v286*/, off, s33 offset:708 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v31 /*v287*/, off, s33 offset:712 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v32 /*v288*/, off, s33 offset:716 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v33 /*v289*/, off, s33 offset:720 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v34 /*v290*/, off, s33 offset:724 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v35 /*v291*/, off, s33 offset:728 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v36 /*v292*/, off, s33 offset:732 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v37 /*v293*/, off, s33 offset:736 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v38 /*v294*/, off, s33 offset:740 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v39 /*v295*/, off, s33 offset:744 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v40 /*v296*/, off, s33 offset:748 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v41 /*v297*/, off, s33 offset:752 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v42 /*v298*/, off, s33 offset:756 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v43 /*v299*/, off, s33 offset:760 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v44 /*v300*/, off, s33 offset:764 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v45 /*v301*/, off, s33 offset:768 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v46 /*v302*/, off, s33 offset:772 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v47 /*v303*/, off, s33 offset:776 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v48 /*v304*/, off, s33 offset:780 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v49 /*v305*/, off, s33 offset:784 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v50 /*v306*/, off, s33 offset:788 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v51 /*v307*/, off, s33 offset:792 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v52 /*v308*/, off, s33 offset:796 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v53 /*v309*/, off, s33 offset:800 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v54 /*v310*/, off, s33 offset:804 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v55 /*v311*/, off, s33 offset:808 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v56 /*v312*/, off, s33 offset:812 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v57 /*v313*/, off, s33 offset:816 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v58 /*v314*/, off, s33 offset:820 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v59 /*v315*/, off, s33 offset:824 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v60 /*v316*/, off, s33 offset:828 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v61 /*v317*/, off, s33 offset:832 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v62 /*v318*/, off, s33 offset:836 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v63 /*v319*/, off, s33 offset:840 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v64 /*v320*/, off, s33 offset:844 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v65 /*v321*/, off, s33 offset:848 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v66 /*v322*/, off, s33 offset:852 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v67 /*v323*/, off, s33 offset:856 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v68 /*v324*/, off, s33 offset:860 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v69 /*v325*/, off, s33 offset:864 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v70 /*v326*/, off, s33 offset:868 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v71 /*v327*/, off, s33 offset:872 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v72 /*v328*/, off, s33 offset:876 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v73 /*v329*/, off, s33 offset:880 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v74 /*v330*/, off, s33 offset:884 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v75 /*v331*/, off, s33 offset:888 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v76 /*v332*/, off, s33 offset:892 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v77 /*v333*/, off, s33 offset:896 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v78 /*v334*/, off, s33 offset:900 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v79 /*v335*/, off, s33 offset:904 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v80 /*v336*/, off, s33 offset:908 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v81 /*v337*/, off, s33 offset:912 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v82 /*v338*/, off, s33 offset:916 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v83 /*v339*/, off, s33 offset:920 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v84 /*v340*/, off, s33 offset:924 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v85 /*v341*/, off, s33 offset:928 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v86 /*v342*/, off, s33 offset:932 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v87 /*v343*/, off, s33 offset:936 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v88 /*v344*/, off, s33 offset:940 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v89 /*v345*/, off, s33 offset:944 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v90 /*v346*/, off, s33 offset:948 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v91 /*v347*/, off, s33 offset:952 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v92 /*v348*/, off, s33 offset:956 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v93 /*v349*/, off, s33 offset:960 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v94 /*v350*/, off, s33 offset:964 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v95 /*v351*/, off, s33 offset:968 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v96 /*v352*/, off, s33 offset:972 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v97 /*v353*/, off, s33 offset:976 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v98 /*v354*/, off, s33 offset:980 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v99 /*v355*/, off, s33 offset:984 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v100 /*v356*/, off, s33 offset:988 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v101 /*v357*/, off, s33 offset:992 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v102 /*v358*/, off, s33 offset:996 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v103 /*v359*/, off, s33 offset:1000 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v104 /*v360*/, off, s33 offset:1004 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v105 /*v361*/, off, s33 offset:1008 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v106 /*v362*/, off, s33 offset:1012 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v107 /*v363*/, off, s33 offset:1016 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v108 /*v364*/, off, s33 offset:1020 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v109 /*v365*/, off, s33 offset:1024 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v110 /*v366*/, off, s33 offset:1028 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v111 /*v367*/, off, s33 offset:1032 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v112 /*v368*/, off, s33 offset:1036 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v113 /*v369*/, off, s33 offset:1040 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v114 /*v370*/, off, s33 offset:1044 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v115 /*v371*/, off, s33 offset:1048 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v116 /*v372*/, off, s33 offset:1052 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v117 /*v373*/, off, s33 offset:1056 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v118 /*v374*/, off, s33 offset:1060 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v119 /*v375*/, off, s33 offset:1064 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v120 /*v376*/, off, s33 offset:1068 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v121 /*v377*/, off, s33 offset:1072 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v122 /*v378*/, off, s33 offset:1076 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v123 /*v379*/, off, s33 offset:1080 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v124 /*v380*/, off, s33 offset:1084 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v125 /*v381*/, off, s33 offset:1088 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v126 /*v382*/, off, s33 offset:1092 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v127 /*v383*/, off, s33 offset:1096 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v128 /*v384*/, off, s33 offset:1100 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v129 /*v385*/, off, s33 offset:1104 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v130 /*v386*/, off, s33 offset:1108 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v131 /*v387*/, off, s33 offset:1112 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v132 /*v388*/, off, s33 offset:1116 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v133 /*v389*/, off, s33 offset:1120 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v134 /*v390*/, off, s33 offset:1124 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v135 /*v391*/, off, s33 offset:1128 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v136 /*v392*/, off, s33 offset:1132 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v137 /*v393*/, off, s33 offset:1136 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v138 /*v394*/, off, s33 offset:1140 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v139 /*v395*/, off, s33 offset:1144 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v140 /*v396*/, off, s33 offset:1148 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v141 /*v397*/, off, s33 offset:1152 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v142 /*v398*/, off, s33 offset:1156 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v143 /*v399*/, off, s33 offset:1160 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v144 /*v400*/, off, s33 offset:1164 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v145 /*v401*/, off, s33 offset:1168 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v146 /*v402*/, off, s33 offset:1172 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v147 /*v403*/, off, s33 offset:1176 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v148 /*v404*/, off, s33 offset:1180 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v149 /*v405*/, off, s33 offset:1184 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v150 /*v406*/, off, s33 offset:1188 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v151 /*v407*/, off, s33 offset:1192 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v152 /*v408*/, off, s33 offset:1196 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v153 /*v409*/, off, s33 offset:1200 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v154 /*v410*/, off, s33 offset:1204 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v155 /*v411*/, off, s33 offset:1208 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v156 /*v412*/, off, s33 offset:1212 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v157 /*v413*/, off, s33 offset:1216 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v158 /*v414*/, off, s33 offset:1220 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v159 /*v415*/, off, s33 offset:1224 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v160 /*v416*/, off, s33 offset:1228 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v161 /*v417*/, off, s33 offset:1232 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v162 /*v418*/, off, s33 offset:1236 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v163 /*v419*/, off, s33 offset:1240 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v164 /*v420*/, off, s33 offset:1244 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v165 /*v421*/, off, s33 offset:1248 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v166 /*v422*/, off, s33 offset:1252 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v167 /*v423*/, off, s33 offset:1256 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v168 /*v424*/, off, s33 offset:1260 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v169 /*v425*/, off, s33 offset:1264 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v170 /*v426*/, off, s33 offset:1268 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v171 /*v427*/, off, s33 offset:1272 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v172 /*v428*/, off, s33 offset:1276 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v173 /*v429*/, off, s33 offset:1280 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v174 /*v430*/, off, s33 offset:1284 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v175 /*v431*/, off, s33 offset:1288 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v176 /*v432*/, off, s33 offset:1292 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v177 /*v433*/, off, s33 offset:1296 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v178 /*v434*/, off, s33 offset:1300 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v179 /*v435*/, off, s33 offset:1304 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v180 /*v436*/, off, s33 offset:1308 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v181 /*v437*/, off, s33 offset:1312 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v182 /*v438*/, off, s33 offset:1316 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v183 /*v439*/, off, s33 offset:1320 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v184 /*v440*/, off, s33 offset:1324 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v185 /*v441*/, off, s33 offset:1328 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v186 /*v442*/, off, s33 offset:1332 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v187 /*v443*/, off, s33 offset:1336 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v188 /*v444*/, off, s33 offset:1340 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v189 /*v445*/, off, s33 offset:1344 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v190 /*v446*/, off, s33 offset:1348 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v191 /*v447*/, off, s33 offset:1352 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v192 /*v448*/, off, s33 offset:1356 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v193 /*v449*/, off, s33 offset:1360 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v194 /*v450*/, off, s33 offset:1364 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v195 /*v451*/, off, s33 offset:1368 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v196 /*v452*/, off, s33 offset:1372 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v197 /*v453*/, off, s33 offset:1376 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v198 /*v454*/, off, s33 offset:1380 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v199 /*v455*/, off, s33 offset:1384 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v200 /*v456*/, off, s33 offset:1388 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v201 /*v457*/, off, s33 offset:1392 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v202 /*v458*/, off, s33 offset:1396 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v203 /*v459*/, off, s33 offset:1400 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v204 /*v460*/, off, s33 offset:1404 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v205 /*v461*/, off, s33 offset:1408 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v206 /*v462*/, off, s33 offset:1412 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v207 /*v463*/, off, s33 offset:1416 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v208 /*v464*/, off, s33 offset:1420 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v209 /*v465*/, off, s33 offset:1424 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v210 /*v466*/, off, s33 offset:1428 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v211 /*v467*/, off, s33 offset:1432 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v212 /*v468*/, off, s33 offset:1436 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v213 /*v469*/, off, s33 offset:1440 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v214 /*v470*/, off, s33 offset:1444 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v215 /*v471*/, off, s33 offset:1448 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v216 /*v472*/, off, s33 offset:1452 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v217 /*v473*/, off, s33 offset:1456 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v218 /*v474*/, off, s33 offset:1460 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v219 /*v475*/, off, s33 offset:1464 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v220 /*v476*/, off, s33 offset:1468 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v221 /*v477*/, off, s33 offset:1472 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v222 /*v478*/, off, s33 offset:1476 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v223 /*v479*/, off, s33 offset:1480 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v224 /*v480*/, off, s33 offset:1484 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v225 /*v481*/, off, s33 offset:1488 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v226 /*v482*/, off, s33 offset:1492 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v227 /*v483*/, off, s33 offset:1496 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v228 /*v484*/, off, s33 offset:1500 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v229 /*v485*/, off, s33 offset:1504 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v230 /*v486*/, off, s33 offset:1508 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v231 /*v487*/, off, s33 offset:1512 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v232 /*v488*/, off, s33 offset:1516 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v233 /*v489*/, off, s33 offset:1520 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v234 /*v490*/, off, s33 offset:1524 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v235 /*v491*/, off, s33 offset:1528 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v236 /*v492*/, off, s33 offset:1532 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v237 /*v493*/, off, s33 offset:1536 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v238 /*v494*/, off, s33 offset:1540 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v239 /*v495*/, off, s33 offset:1544 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v240 /*v496*/, off, s33 offset:1548 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v241 /*v497*/, off, s33 offset:1552 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v242 /*v498*/, off, s33 offset:1556 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v243 /*v499*/, off, s33 offset:1560 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v244 /*v500*/, off, s33 offset:1564 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v245 /*v501*/, off, s33 offset:1568 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v246 /*v502*/, off, s33 offset:1572 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v247 /*v503*/, off, s33 offset:1576 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v248 /*v504*/, off, s33 offset:1580 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v249 /*v505*/, off, s33 offset:1584 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v250 /*v506*/, off, s33 offset:1588 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v251 /*v507*/, off, s33 offset:1592 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v252 /*v508*/, off, s33 offset:1596 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v253 /*v509*/, off, s33 offset:1600 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v254 /*v510*/, off, s33 offset:1604 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v255 /*v511*/, off, s33 offset:1608 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0x4080 ; msbs: dst=2 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0 /*v512*/, off, s33 offset:1612 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1 /*v513*/, off, s33 offset:1616 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v2 /*v514*/, off, s33 offset:1620 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v3 /*v515*/, off, s33 offset:1624 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v4 /*v516*/, off, s33 offset:1628 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v5 /*v517*/, off, s33 offset:1632 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v6 /*v518*/, off, s33 offset:1636 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v7 /*v519*/, off, s33 offset:1640 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v8 /*v520*/, off, s33 offset:1644 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v9 /*v521*/, off, s33 offset:1648 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v10 /*v522*/, off, s33 offset:1652 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v11 /*v523*/, off, s33 offset:1656 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v12 /*v524*/, off, s33 offset:1660 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v13 /*v525*/, off, s33 offset:1664 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v14 /*v526*/, off, s33 offset:1668 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v15 /*v527*/, off, s33 offset:1672 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v16 /*v528*/, off, s33 offset:1676 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v17 /*v529*/, off, s33 offset:1680 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v18 /*v530*/, off, s33 offset:1684 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v19 /*v531*/, off, s33 offset:1688 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v20 /*v532*/, off, s33 offset:1692 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v21 /*v533*/, off, s33 offset:1696 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v22 /*v534*/, off, s33 offset:1700 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v23 /*v535*/, off, s33 offset:1704 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v24 /*v536*/, off, s33 offset:1708 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v25 /*v537*/, off, s33 offset:1712 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v26 /*v538*/, off, s33 offset:1716 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v27 /*v539*/, off, s33 offset:1720 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v28 /*v540*/, off, s33 offset:1724 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v29 /*v541*/, off, s33 offset:1728 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v30 /*v542*/, off, s33 offset:1732 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v31 /*v543*/, off, s33 offset:1736 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v32 /*v544*/, off, s33 offset:1740 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v33 /*v545*/, off, s33 offset:1744 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v34 /*v546*/, off, s33 offset:1748 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v35 /*v547*/, off, s33 offset:1752 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v36 /*v548*/, off, s33 offset:1756 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v37 /*v549*/, off, s33 offset:1760 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v38 /*v550*/, off, s33 offset:1764 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v39 /*v551*/, off, s33 offset:1768 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v40 /*v552*/, off, s33 offset:1772 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v41 /*v553*/, off, s33 offset:1776 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v42 /*v554*/, off, s33 offset:1780 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v43 /*v555*/, off, s33 offset:1784 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v44 /*v556*/, off, s33 offset:1788 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v45 /*v557*/, off, s33 offset:1792 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v46 /*v558*/, off, s33 offset:1796 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v47 /*v559*/, off, s33 offset:1800 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v48 /*v560*/, off, s33 offset:1804 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v49 /*v561*/, off, s33 offset:1808 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v50 /*v562*/, off, s33 offset:1812 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v51 /*v563*/, off, s33 offset:1816 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v52 /*v564*/, off, s33 offset:1820 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v53 /*v565*/, off, s33 offset:1824 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v54 /*v566*/, off, s33 offset:1828 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v55 /*v567*/, off, s33 offset:1832 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v56 /*v568*/, off, s33 offset:1836 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v57 /*v569*/, off, s33 offset:1840 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v58 /*v570*/, off, s33 offset:1844 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v59 /*v571*/, off, s33 offset:1848 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v60 /*v572*/, off, s33 offset:1852 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v61 /*v573*/, off, s33 offset:1856 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v62 /*v574*/, off, s33 offset:1860 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v63 /*v575*/, off, s33 offset:1864 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v64 /*v576*/, off, s33 offset:1868 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v65 /*v577*/, off, s33 offset:1872 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v66 /*v578*/, off, s33 offset:1876 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v67 /*v579*/, off, s33 offset:1880 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v68 /*v580*/, off, s33 offset:1884 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v69 /*v581*/, off, s33 offset:1888 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v70 /*v582*/, off, s33 offset:1892 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v71 /*v583*/, off, s33 offset:1896 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v72 /*v584*/, off, s33 offset:1900 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v73 /*v585*/, off, s33 offset:1904 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v74 /*v586*/, off, s33 offset:1908 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v75 /*v587*/, off, s33 offset:1912 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v76 /*v588*/, off, s33 offset:1916 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v77 /*v589*/, off, s33 offset:1920 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v78 /*v590*/, off, s33 offset:1924 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v79 /*v591*/, off, s33 offset:1928 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v80 /*v592*/, off, s33 offset:1932 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v81 /*v593*/, off, s33 offset:1936 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v82 /*v594*/, off, s33 offset:1940 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v83 /*v595*/, off, s33 offset:1944 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v84 /*v596*/, off, s33 offset:1948 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v85 /*v597*/, off, s33 offset:1952 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v86 /*v598*/, off, s33 offset:1956 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v87 /*v599*/, off, s33 offset:1960 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v88 /*v600*/, off, s33 offset:1964 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v89 /*v601*/, off, s33 offset:1968 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v90 /*v602*/, off, s33 offset:1972 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v91 /*v603*/, off, s33 offset:1976 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v92 /*v604*/, off, s33 offset:1980 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v93 /*v605*/, off, s33 offset:1984 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v94 /*v606*/, off, s33 offset:1988 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v95 /*v607*/, off, s33 offset:1992 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v96 /*v608*/, off, s33 offset:1996 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v97 /*v609*/, off, s33 offset:2000 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v98 /*v610*/, off, s33 offset:2004 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v99 /*v611*/, off, s33 offset:2008 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v100 /*v612*/, off, s33 offset:2012 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v101 /*v613*/, off, s33 offset:2016 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v102 /*v614*/, off, s33 offset:2020 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v103 /*v615*/, off, s33 offset:2024 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v104 /*v616*/, off, s33 offset:2028 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v105 /*v617*/, off, s33 offset:2032 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v106 /*v618*/, off, s33 offset:2036 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v107 /*v619*/, off, s33 offset:2040 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v108 /*v620*/, off, s33 offset:2044 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v109 /*v621*/, off, s33 offset:2048 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v110 /*v622*/, off, s33 offset:2052 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v111 /*v623*/, off, s33 offset:2056 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v112 /*v624*/, off, s33 offset:2060 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v113 /*v625*/, off, s33 offset:2064 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v114 /*v626*/, off, s33 offset:2068 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v115 /*v627*/, off, s33 offset:2072 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v116 /*v628*/, off, s33 offset:2076 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v117 /*v629*/, off, s33 offset:2080 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v118 /*v630*/, off, s33 offset:2084 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v119 /*v631*/, off, s33 offset:2088 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v120 /*v632*/, off, s33 offset:2092 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v121 /*v633*/, off, s33 offset:2096 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v122 /*v634*/, off, s33 offset:2100 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v123 /*v635*/, off, s33 offset:2104 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v124 /*v636*/, off, s33 offset:2108 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v125 /*v637*/, off, s33 offset:2112 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v126 /*v638*/, off, s33 offset:2116 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v127 /*v639*/, off, s33 offset:2120 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v128 /*v640*/, off, s33 offset:2124 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v129 /*v641*/, off, s33 offset:2128 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v130 /*v642*/, off, s33 offset:2132 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v131 /*v643*/, off, s33 offset:2136 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v132 /*v644*/, off, s33 offset:2140 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v133 /*v645*/, off, s33 offset:2144 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v134 /*v646*/, off, s33 offset:2148 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v135 /*v647*/, off, s33 offset:2152 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v136 /*v648*/, off, s33 offset:2156 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v137 /*v649*/, off, s33 offset:2160 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v138 /*v650*/, off, s33 offset:2164 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v139 /*v651*/, off, s33 offset:2168 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v140 /*v652*/, off, s33 offset:2172 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v141 /*v653*/, off, s33 offset:2176 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v142 /*v654*/, off, s33 offset:2180 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v143 /*v655*/, off, s33 offset:2184 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v144 /*v656*/, off, s33 offset:2188 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v145 /*v657*/, off, s33 offset:2192 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v146 /*v658*/, off, s33 offset:2196 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v147 /*v659*/, off, s33 offset:2200 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v148 /*v660*/, off, s33 offset:2204 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v149 /*v661*/, off, s33 offset:2208 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v150 /*v662*/, off, s33 offset:2212 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v151 /*v663*/, off, s33 offset:2216 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v152 /*v664*/, off, s33 offset:2220 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v153 /*v665*/, off, s33 offset:2224 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v154 /*v666*/, off, s33 offset:2228 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v155 /*v667*/, off, s33 offset:2232 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v156 /*v668*/, off, s33 offset:2236 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v157 /*v669*/, off, s33 offset:2240 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v158 /*v670*/, off, s33 offset:2244 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v159 /*v671*/, off, s33 offset:2248 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v160 /*v672*/, off, s33 offset:2252 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v161 /*v673*/, off, s33 offset:2256 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v162 /*v674*/, off, s33 offset:2260 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v163 /*v675*/, off, s33 offset:2264 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v164 /*v676*/, off, s33 offset:2268 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v165 /*v677*/, off, s33 offset:2272 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v166 /*v678*/, off, s33 offset:2276 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v167 /*v679*/, off, s33 offset:2280 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v168 /*v680*/, off, s33 offset:2284 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v169 /*v681*/, off, s33 offset:2288 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v170 /*v682*/, off, s33 offset:2292 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v171 /*v683*/, off, s33 offset:2296 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v172 /*v684*/, off, s33 offset:2300 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v173 /*v685*/, off, s33 offset:2304 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v174 /*v686*/, off, s33 offset:2308 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v175 /*v687*/, off, s33 offset:2312 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v176 /*v688*/, off, s33 offset:2316 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v177 /*v689*/, off, s33 offset:2320 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v178 /*v690*/, off, s33 offset:2324 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v179 /*v691*/, off, s33 offset:2328 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v180 /*v692*/, off, s33 offset:2332 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v181 /*v693*/, off, s33 offset:2336 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v182 /*v694*/, off, s33 offset:2340 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v183 /*v695*/, off, s33 offset:2344 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v184 /*v696*/, off, s33 offset:2348 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v185 /*v697*/, off, s33 offset:2352 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v186 /*v698*/, off, s33 offset:2356 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v187 /*v699*/, off, s33 offset:2360 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v188 /*v700*/, off, s33 offset:2364 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v189 /*v701*/, off, s33 offset:2368 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v190 /*v702*/, off, s33 offset:2372 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v191 /*v703*/, off, s33 offset:2376 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v192 /*v704*/, off, s33 offset:2380 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v193 /*v705*/, off, s33 offset:2384 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v194 /*v706*/, off, s33 offset:2388 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v195 /*v707*/, off, s33 offset:2392 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v196 /*v708*/, off, s33 offset:2396 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v197 /*v709*/, off, s33 offset:2400 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v198 /*v710*/, off, s33 offset:2404 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v199 /*v711*/, off, s33 offset:2408 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v200 /*v712*/, off, s33 offset:2412 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v201 /*v713*/, off, s33 offset:2416 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v202 /*v714*/, off, s33 offset:2420 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v203 /*v715*/, off, s33 offset:2424 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v204 /*v716*/, off, s33 offset:2428 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v205 /*v717*/, off, s33 offset:2432 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v206 /*v718*/, off, s33 offset:2436 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v207 /*v719*/, off, s33 offset:2440 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v208 /*v720*/, off, s33 offset:2444 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v209 /*v721*/, off, s33 offset:2448 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v210 /*v722*/, off, s33 offset:2452 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v211 /*v723*/, off, s33 offset:2456 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v212 /*v724*/, off, s33 offset:2460 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v213 /*v725*/, off, s33 offset:2464 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v214 /*v726*/, off, s33 offset:2468 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v215 /*v727*/, off, s33 offset:2472 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v216 /*v728*/, off, s33 offset:2476 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v217 /*v729*/, off, s33 offset:2480 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v218 /*v730*/, off, s33 offset:2484 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v219 /*v731*/, off, s33 offset:2488 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v220 /*v732*/, off, s33 offset:2492 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v221 /*v733*/, off, s33 offset:2496 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v222 /*v734*/, off, s33 offset:2500 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v223 /*v735*/, off, s33 offset:2504 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v224 /*v736*/, off, s33 offset:2508 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v225 /*v737*/, off, s33 offset:2512 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v226 /*v738*/, off, s33 offset:2516 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v227 /*v739*/, off, s33 offset:2520 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v228 /*v740*/, off, s33 offset:2524 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v229 /*v741*/, off, s33 offset:2528 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v230 /*v742*/, off, s33 offset:2532 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v231 /*v743*/, off, s33 offset:2536 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v232 /*v744*/, off, s33 offset:2540 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v233 /*v745*/, off, s33 offset:2544 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v234 /*v746*/, off, s33 offset:2548 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v235 /*v747*/, off, s33 offset:2552 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v236 /*v748*/, off, s33 offset:2556 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v237 /*v749*/, off, s33 offset:2560 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v238 /*v750*/, off, s33 offset:2564 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v239 /*v751*/, off, s33 offset:2568 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v240 /*v752*/, off, s33 offset:2572 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v241 /*v753*/, off, s33 offset:2576 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v242 /*v754*/, off, s33 offset:2580 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v243 /*v755*/, off, s33 offset:2584 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v244 /*v756*/, off, s33 offset:2588 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v245 /*v757*/, off, s33 offset:2592 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v246 /*v758*/, off, s33 offset:2596 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v247 /*v759*/, off, s33 offset:2600 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v248 /*v760*/, off, s33 offset:2604 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v249 /*v761*/, off, s33 offset:2608 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v250 /*v762*/, off, s33 offset:2612 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v251 /*v763*/, off, s33 offset:2616 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v252 /*v764*/, off, s33 offset:2620 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v253 /*v765*/, off, s33 offset:2624 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v254 /*v766*/, off, s33 offset:2628 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v255 /*v767*/, off, s33 offset:2632 nv
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0x80c0 ; msbs: dst=3 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v0 /*v768*/, off, s33 offset:2636 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v1 /*v769*/, off, s33 offset:2640 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v2 /*v770*/, off, s33 offset:2644 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v3 /*v771*/, off, s33 offset:2648 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v4 /*v772*/, off, s33 offset:2652 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v5 /*v773*/, off, s33 offset:2656 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v6 /*v774*/, off, s33 offset:2660 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v7 /*v775*/, off, s33 offset:2664 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v8 /*v776*/, off, s33 offset:2668 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v9 /*v777*/, off, s33 offset:2672 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v10 /*v778*/, off, s33 offset:2676 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v11 /*v779*/, off, s33 offset:2680 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v12 /*v780*/, off, s33 offset:2684 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v13 /*v781*/, off, s33 offset:2688 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v14 /*v782*/, off, s33 offset:2692 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v15 /*v783*/, off, s33 offset:2696 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v16 /*v784*/, off, s33 offset:2700 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v17 /*v785*/, off, s33 offset:2704 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v18 /*v786*/, off, s33 offset:2708 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v19 /*v787*/, off, s33 offset:2712 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v20 /*v788*/, off, s33 offset:2716 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v21 /*v789*/, off, s33 offset:2720 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v22 /*v790*/, off, s33 offset:2724 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v23 /*v791*/, off, s33 offset:2728 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v24 /*v792*/, off, s33 offset:2732 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v25 /*v793*/, off, s33 offset:2736 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v26 /*v794*/, off, s33 offset:2740 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v27 /*v795*/, off, s33 offset:2744 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v28 /*v796*/, off, s33 offset:2748 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v29 /*v797*/, off, s33 offset:2752 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v30 /*v798*/, off, s33 offset:2756 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v31 /*v799*/, off, s33 offset:2760 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v32 /*v800*/, off, s33 offset:2764 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v33 /*v801*/, off, s33 offset:2768 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v34 /*v802*/, off, s33 offset:2772 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v35 /*v803*/, off, s33 offset:2776 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v36 /*v804*/, off, s33 offset:2780 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v37 /*v805*/, off, s33 offset:2784 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v38 /*v806*/, off, s33 offset:2788 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v39 /*v807*/, off, s33 offset:2792 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v40 /*v808*/, off, s33 offset:2796 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v41 /*v809*/, off, s33 offset:2800 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v42 /*v810*/, off, s33 offset:2804 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v43 /*v811*/, off, s33 offset:2808 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v44 /*v812*/, off, s33 offset:2812 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v45 /*v813*/, off, s33 offset:2816 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v46 /*v814*/, off, s33 offset:2820 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v47 /*v815*/, off, s33 offset:2824 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v48 /*v816*/, off, s33 offset:2828 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v49 /*v817*/, off, s33 offset:2832 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v50 /*v818*/, off, s33 offset:2836 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v51 /*v819*/, off, s33 offset:2840 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v52 /*v820*/, off, s33 offset:2844 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v53 /*v821*/, off, s33 offset:2848 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v54 /*v822*/, off, s33 offset:2852 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v55 /*v823*/, off, s33 offset:2856 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v56 /*v824*/, off, s33 offset:2860 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v57 /*v825*/, off, s33 offset:2864 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v58 /*v826*/, off, s33 offset:2868 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v59 /*v827*/, off, s33 offset:2872 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v60 /*v828*/, off, s33 offset:2876 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v61 /*v829*/, off, s33 offset:2880 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v62 /*v830*/, off, s33 offset:2884 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v63 /*v831*/, off, s33 offset:2888 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v64 /*v832*/, off, s33 offset:2892 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v65 /*v833*/, off, s33 offset:2896 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v66 /*v834*/, off, s33 offset:2900 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v67 /*v835*/, off, s33 offset:2904 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v68 /*v836*/, off, s33 offset:2908 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v69 /*v837*/, off, s33 offset:2912 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v70 /*v838*/, off, s33 offset:2916 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v71 /*v839*/, off, s33 offset:2920 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v72 /*v840*/, off, s33 offset:2924 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v73 /*v841*/, off, s33 offset:2928 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v74 /*v842*/, off, s33 offset:2932 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v75 /*v843*/, off, s33 offset:2936 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v76 /*v844*/, off, s33 offset:2940 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v77 /*v845*/, off, s33 offset:2944 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v78 /*v846*/, off, s33 offset:2948 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v79 /*v847*/, off, s33 offset:2952 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v80 /*v848*/, off, s33 offset:2956 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v81 /*v849*/, off, s33 offset:2960 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v82 /*v850*/, off, s33 offset:2964 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v83 /*v851*/, off, s33 offset:2968 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v84 /*v852*/, off, s33 offset:2972 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v85 /*v853*/, off, s33 offset:2976 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v86 /*v854*/, off, s33 offset:2980 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v87 /*v855*/, off, s33 offset:2984 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v88 /*v856*/, off, s33 offset:2988 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v89 /*v857*/, off, s33 offset:2992 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v90 /*v858*/, off, s33 offset:2996 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v91 /*v859*/, off, s33 offset:3000 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v92 /*v860*/, off, s33 offset:3004 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v93 /*v861*/, off, s33 offset:3008 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v94 /*v862*/, off, s33 offset:3012 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v95 /*v863*/, off, s33 offset:3016 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v96 /*v864*/, off, s33 offset:3020 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v97 /*v865*/, off, s33 offset:3024 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v98 /*v866*/, off, s33 offset:3028 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v99 /*v867*/, off, s33 offset:3032 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v100 /*v868*/, off, s33 offset:3036 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v101 /*v869*/, off, s33 offset:3040 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v102 /*v870*/, off, s33 offset:3044 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v103 /*v871*/, off, s33 offset:3048 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v104 /*v872*/, off, s33 offset:3052 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v105 /*v873*/, off, s33 offset:3056 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v106 /*v874*/, off, s33 offset:3060 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v107 /*v875*/, off, s33 offset:3064 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v108 /*v876*/, off, s33 offset:3068 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v109 /*v877*/, off, s33 offset:3072 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v110 /*v878*/, off, s33 offset:3076 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v111 /*v879*/, off, s33 offset:3080 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v112 /*v880*/, off, s33 offset:3084 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v113 /*v881*/, off, s33 offset:3088 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v114 /*v882*/, off, s33 offset:3092 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v115 /*v883*/, off, s33 offset:3096 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v116 /*v884*/, off, s33 offset:3100 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v117 /*v885*/, off, s33 offset:3104 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v118 /*v886*/, off, s33 offset:3108 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v119 /*v887*/, off, s33 offset:3112 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v120 /*v888*/, off, s33 offset:3116 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v121 /*v889*/, off, s33 offset:3120 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v122 /*v890*/, off, s33 offset:3124 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v123 /*v891*/, off, s33 offset:3128 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v124 /*v892*/, off, s33 offset:3132 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v125 /*v893*/, off, s33 offset:3136 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v126 /*v894*/, off, s33 offset:3140 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v127 /*v895*/, off, s33 offset:3144 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v128 /*v896*/, off, s33 offset:3148 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v129 /*v897*/, off, s33 offset:3152 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v130 /*v898*/, off, s33 offset:3156 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v131 /*v899*/, off, s33 offset:3160 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v132 /*v900*/, off, s33 offset:3164 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v133 /*v901*/, off, s33 offset:3168 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v134 /*v902*/, off, s33 offset:3172 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v135 /*v903*/, off, s33 offset:3176 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v136 /*v904*/, off, s33 offset:3180 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v137 /*v905*/, off, s33 offset:3184 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v138 /*v906*/, off, s33 offset:3188 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v139 /*v907*/, off, s33 offset:3192 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v140 /*v908*/, off, s33 offset:3196 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v141 /*v909*/, off, s33 offset:3200 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v142 /*v910*/, off, s33 offset:3204 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v143 /*v911*/, off, s33 offset:3208 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v144 /*v912*/, off, s33 offset:3212 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v145 /*v913*/, off, s33 offset:3216 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v146 /*v914*/, off, s33 offset:3220 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v147 /*v915*/, off, s33 offset:3224 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v148 /*v916*/, off, s33 offset:3228 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v149 /*v917*/, off, s33 offset:3232 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v150 /*v918*/, off, s33 offset:3236 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v151 /*v919*/, off, s33 offset:3240 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v152 /*v920*/, off, s33 offset:3244 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v153 /*v921*/, off, s33 offset:3248 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v154 /*v922*/, off, s33 offset:3252 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v155 /*v923*/, off, s33 offset:3256 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v156 /*v924*/, off, s33 offset:3260 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v157 /*v925*/, off, s33 offset:3264 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v158 /*v926*/, off, s33 offset:3268 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v159 /*v927*/, off, s33 offset:3272 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v160 /*v928*/, off, s33 offset:3276 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v161 /*v929*/, off, s33 offset:3280 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v162 /*v930*/, off, s33 offset:3284 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v163 /*v931*/, off, s33 offset:3288 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v164 /*v932*/, off, s33 offset:3292 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v165 /*v933*/, off, s33 offset:3296 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v166 /*v934*/, off, s33 offset:3300 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v167 /*v935*/, off, s33 offset:3304 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v168 /*v936*/, off, s33 offset:3308 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v169 /*v937*/, off, s33 offset:3312 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v170 /*v938*/, off, s33 offset:3316 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v171 /*v939*/, off, s33 offset:3320 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v172 /*v940*/, off, s33 offset:3324 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v173 /*v941*/, off, s33 offset:3328 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v174 /*v942*/, off, s33 offset:3332 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v175 /*v943*/, off, s33 offset:3336 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v176 /*v944*/, off, s33 offset:3340 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v177 /*v945*/, off, s33 offset:3344 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v178 /*v946*/, off, s33 offset:3348 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v179 /*v947*/, off, s33 offset:3352 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v180 /*v948*/, off, s33 offset:3356 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v181 /*v949*/, off, s33 offset:3360 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v182 /*v950*/, off, s33 offset:3364 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v183 /*v951*/, off, s33 offset:3368 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v184 /*v952*/, off, s33 offset:3372 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v185 /*v953*/, off, s33 offset:3376 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v186 /*v954*/, off, s33 offset:3380 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v187 /*v955*/, off, s33 offset:3384 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v188 /*v956*/, off, s33 offset:3388 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v189 /*v957*/, off, s33 offset:3392 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v190 /*v958*/, off, s33 offset:3396 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v191 /*v959*/, off, s33 offset:3400 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v192 /*v960*/, off, s33 offset:3404 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v193 /*v961*/, off, s33 offset:3408 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v194 /*v962*/, off, s33 offset:3412 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v195 /*v963*/, off, s33 offset:3416 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v196 /*v964*/, off, s33 offset:3420 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v197 /*v965*/, off, s33 offset:3424 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v198 /*v966*/, off, s33 offset:3428 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v199 /*v967*/, off, s33 offset:3432 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v200 /*v968*/, off, s33 offset:3436 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v201 /*v969*/, off, s33 offset:3440 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v202 /*v970*/, off, s33 offset:3444 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v203 /*v971*/, off, s33 offset:3448 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v204 /*v972*/, off, s33 offset:3452 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v205 /*v973*/, off, s33 offset:3456 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v206 /*v974*/, off, s33 offset:3460 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v207 /*v975*/, off, s33 offset:3464 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v208 /*v976*/, off, s33 offset:3468 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v209 /*v977*/, off, s33 offset:3472 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v210 /*v978*/, off, s33 offset:3476 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v211 /*v979*/, off, s33 offset:3480 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v212 /*v980*/, off, s33 offset:3484 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v213 /*v981*/, off, s33 offset:3488 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v214 /*v982*/, off, s33 offset:3492 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v215 /*v983*/, off, s33 offset:3496 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v216 /*v984*/, off, s33 offset:3500 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v217 /*v985*/, off, s33 offset:3504 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v218 /*v986*/, off, s33 offset:3508 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v219 /*v987*/, off, s33 offset:3512 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v220 /*v988*/, off, s33 offset:3516 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v221 /*v989*/, off, s33 offset:3520 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v222 /*v990*/, off, s33 offset:3524 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v223 /*v991*/, off, s33 offset:3528 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v224 /*v992*/, off, s33 offset:3532 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v225 /*v993*/, off, s33 offset:3536 nv
; GFX1250-DAGISEL-NEXT:    s_clause 0x1d ; 120-byte Folded Reload
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v226 /*v994*/, off, s33 offset:3540 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v227 /*v995*/, off, s33 offset:3544 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v228 /*v996*/, off, s33 offset:3548 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v229 /*v997*/, off, s33 offset:3552 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v230 /*v998*/, off, s33 offset:3556 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v231 /*v999*/, off, s33 offset:3560 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v232 /*v1000*/, off, s33 offset:3564 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v233 /*v1001*/, off, s33 offset:3568 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v234 /*v1002*/, off, s33 offset:3572 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v235 /*v1003*/, off, s33 offset:3576 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v236 /*v1004*/, off, s33 offset:3580 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v237 /*v1005*/, off, s33 offset:3584 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v238 /*v1006*/, off, s33 offset:3588 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v239 /*v1007*/, off, s33 offset:3592 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v240 /*v1008*/, off, s33 offset:3596 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v241 /*v1009*/, off, s33 offset:3600 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v242 /*v1010*/, off, s33 offset:3604 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v243 /*v1011*/, off, s33 offset:3608 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v244 /*v1012*/, off, s33 offset:3612 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v245 /*v1013*/, off, s33 offset:3616 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v246 /*v1014*/, off, s33 offset:3620 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v247 /*v1015*/, off, s33 offset:3624 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v248 /*v1016*/, off, s33 offset:3628 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v249 /*v1017*/, off, s33 offset:3632 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v250 /*v1018*/, off, s33 offset:3636 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v251 /*v1019*/, off, s33 offset:3640 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v252 /*v1020*/, off, s33 offset:3644 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v253 /*v1021*/, off, s33 offset:3648 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v254 /*v1022*/, off, s33 offset:3652 nv
; GFX1250-DAGISEL-NEXT:    scratch_load_b32 v255 /*v1023*/, off, s33 offset:3656 nv
; GFX1250-DAGISEL-NEXT:    s_wait_xcnt 0x0
; GFX1250-DAGISEL-NEXT:    s_mov_b32 exec_lo, s4
; GFX1250-DAGISEL-NEXT:    s_mov_b32 s33, s0
; GFX1250-DAGISEL-NEXT:    s_set_vgpr_msb 0xc000 ; msbs: dst=0 src0=0 src1=0 src2=0
; GFX1250-DAGISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-DAGISEL-NEXT:    s_set_pc_i64 s[30:31]
  %ret = call float(ptr, ...) @llvm.amdgcn.call.whole.wave(ptr @callee, <8 x float> %x) convergent
  store float %ret, ptr %p
  ret void
}

attributes #0 = { nounwind }
