# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn -mcpu=gfx1250 -amdgpu-gfx1250-b0-specific=0 -run-pass post-RA-hazard-rec %s -o - | FileCheck -check-prefixes=GFX1250,GFX1250-A0 %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx1250 -amdgpu-gfx1250-b0-specific=1 -run-pass post-RA-hazard-rec %s -o - | FileCheck -check-prefixes=GFX1250,GFX1250-B0 %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx1251 -run-pass post-RA-hazard-rec %s -o - | FileCheck -check-prefix=GFX1251 %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx1310 -run-pass post-RA-hazard-rec %s -o - | FileCheck -check-prefix=GFX1310 %s
# Same hazards as gfx1251
# RUN: llc -mtriple=amdgcn -mcpu=gfx12-5-generic -run-pass post-RA-hazard-rec %s -o - | FileCheck -check-prefix=GFX1251 %s

# WMMA writes: D0, WMMA reads: A0/B0/Index0
# VALU writes: D1, VALU reads: Use1
# Hards could be:
#   RAW: D0 overlaps Use1
#   WAW: D0 overlaps D1
#   WAR: A0/B0/Index0 overlaps D1

---
name: test_wmma_f32_16x16x32_bf16_D0_overlaps_Use1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_f32_16x16x32_bf16_D0_overlaps_Use1
    ; GFX1250: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr25 = V_ADD_F32_e32 $vgpr24, $vgpr16, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_f32_16x16x32_bf16_D0_overlaps_Use1
    ; GFX1251: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr25 = V_ADD_F32_e32 $vgpr24, $vgpr16, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_f32_16x16x32_bf16_D0_overlaps_Use1
    ; GFX1310: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr25 = V_ADD_F32_e32 $vgpr24, $vgpr16, implicit $mode, implicit $exec
    $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    $vgpr25 = V_ADD_F32_e32 $vgpr24, $vgpr16, implicit $mode, implicit $exec
...

---
name: test_wmma_f32_16x16x32_bf16_D0_overlaps_Use1_with_4_valus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_f32_16x16x32_bf16_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1250: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: $vgpr26 = V_MOV_B32_e32 26, implicit $exec
    ; GFX1250-NEXT: $vgpr27 = V_MOV_B32_e32 27, implicit $exec
    ; GFX1250-NEXT: $vgpr28 = V_MOV_B32_e32 28, implicit $exec
    ; GFX1250-NEXT: $vgpr29 = V_MOV_B32_e32 29, implicit $exec
    ; GFX1250-NEXT: $vgpr25 = V_ADD_F32_e32 $vgpr24, $vgpr16, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_f32_16x16x32_bf16_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1251: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: $vgpr26 = V_MOV_B32_e32 26, implicit $exec
    ; GFX1251-NEXT: $vgpr27 = V_MOV_B32_e32 27, implicit $exec
    ; GFX1251-NEXT: $vgpr28 = V_MOV_B32_e32 28, implicit $exec
    ; GFX1251-NEXT: $vgpr29 = V_MOV_B32_e32 29, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr25 = V_ADD_F32_e32 $vgpr24, $vgpr16, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_f32_16x16x32_bf16_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1310: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr26 = V_MOV_B32_e32 26, implicit $exec
    ; GFX1310-NEXT: $vgpr27 = V_MOV_B32_e32 27, implicit $exec
    ; GFX1310-NEXT: $vgpr28 = V_MOV_B32_e32 28, implicit $exec
    ; GFX1310-NEXT: $vgpr29 = V_MOV_B32_e32 29, implicit $exec
    ; GFX1310-NEXT: $vgpr25 = V_ADD_F32_e32 $vgpr24, $vgpr16, implicit $mode, implicit $exec
    $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    $vgpr26 = V_MOV_B32_e32 26, implicit $exec
    $vgpr27 = V_MOV_B32_e32 27, implicit $exec
    $vgpr28 = V_MOV_B32_e32 28, implicit $exec
    $vgpr29 = V_MOV_B32_e32 29, implicit $exec
    $vgpr25 = V_ADD_F32_e32 $vgpr24, $vgpr16, implicit $mode, implicit $exec
...

---
name: test_wmma_f32_16x16x32_bf16_D0_overlaps_Use1_with_4_salus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_f32_16x16x32_bf16_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1250: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1250-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1250-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1250-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr25 = V_ADD_F32_e32 $vgpr24, $vgpr16, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_f32_16x16x32_bf16_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1251: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1251-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1251-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1251-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr25 = V_ADD_F32_e32 $vgpr24, $vgpr16, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_f32_16x16x32_bf16_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1310: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1310-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1310-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1310-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1310-NEXT: $vgpr25 = V_ADD_F32_e32 $vgpr24, $vgpr16, implicit $mode, implicit $exec
    $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    $sgpr0 = S_MOV_B32 0
    $sgpr1 = S_MOV_B32 1
    $sgpr2 = S_MOV_B32 2
    $sgpr3 = S_MOV_B32 3
    $vgpr25 = V_ADD_F32_e32 $vgpr24, $vgpr16, implicit $mode, implicit $exec
...

---
name: test_wmma_f32_16x16x32_bf16_D0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_f32_16x16x32_bf16_D0_overlaps_D1
    ; GFX1250: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr24, $vgpr25, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_f32_16x16x32_bf16_D0_overlaps_D1
    ; GFX1251: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr24, $vgpr25, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_f32_16x16x32_bf16_D0_overlaps_D1
    ; GFX1310: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr24, $vgpr25, implicit $mode, implicit $exec
    $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    $vgpr16 = V_ADD_F32_e32 $vgpr24, $vgpr25, implicit $mode, implicit $exec
...

---
name: test_wmma_f32_16x16x32_bf16_D0_overlaps_vopd_vdstX
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_f32_16x16x32_bf16_D0_overlaps_vopd_vdstX
    ; GFX1250: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr16, $vgpr255 = V_DUAL_SUB_F32_e32_X_MUL_F32_e32_gfx1250 undef $vgpr1, undef $vgpr1, undef $vgpr0, undef $vgpr0, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_f32_16x16x32_bf16_D0_overlaps_vopd_vdstX
    ; GFX1251: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr16, $vgpr255 = V_DUAL_SUB_F32_e32_X_MUL_F32_e32_gfx1250 undef $vgpr1, undef $vgpr1, undef $vgpr0, undef $vgpr0, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_f32_16x16x32_bf16_D0_overlaps_vopd_vdstX
    ; GFX1310: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr16, $vgpr255 = V_DUAL_SUB_F32_e32_X_MUL_F32_e32_gfx1250 undef $vgpr1, undef $vgpr1, undef $vgpr0, undef $vgpr0, implicit $mode, implicit $exec
    $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    $vgpr16, $vgpr255 = V_DUAL_SUB_F32_e32_X_MUL_F32_e32_gfx1250 undef $vgpr1, undef $vgpr1, undef $vgpr0, undef $vgpr0, implicit $mode, implicit $exec
...

---
name: test_wmma_f32_16x16x32_bf16_A0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_f32_16x16x32_bf16_A0_overlaps_D1
    ; GFX1250: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr24, $vgpr25, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_f32_16x16x32_bf16_A0_overlaps_D1
    ; GFX1251: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr24, $vgpr25, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_f32_16x16x32_bf16_A0_overlaps_D1
    ; GFX1310: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr24, $vgpr25, implicit $mode, implicit $exec
    $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    $vgpr0 = V_ADD_F32_e32 $vgpr24, $vgpr25, implicit $mode, implicit $exec
...

---
name: test_wmma_f32_16x16x32_bf16_A0_overlaps_vopd_vdstY
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_f32_16x16x32_bf16_A0_overlaps_vopd_vdstY
    ; GFX1250: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr255, $vgpr0 = V_DUAL_SUB_F32_e32_X_MUL_F32_e32_gfx1250 undef $vgpr1, undef $vgpr1, undef $vgpr0, undef $vgpr0, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_f32_16x16x32_bf16_A0_overlaps_vopd_vdstY
    ; GFX1251: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr255, $vgpr0 = V_DUAL_SUB_F32_e32_X_MUL_F32_e32_gfx1250 undef $vgpr1, undef $vgpr1, undef $vgpr0, undef $vgpr0, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_f32_16x16x32_bf16_A0_overlaps_vopd_vdstY
    ; GFX1310: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr255, $vgpr0 = V_DUAL_SUB_F32_e32_X_MUL_F32_e32_gfx1250 undef $vgpr1, undef $vgpr1, undef $vgpr0, undef $vgpr0, implicit $mode, implicit $exec
    $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    $vgpr255, $vgpr0 = V_DUAL_SUB_F32_e32_X_MUL_F32_e32_gfx1250 undef $vgpr1, undef $vgpr1, undef $vgpr0, undef $vgpr0, implicit $mode, implicit $exec
...

---
name: test_wmma_f32_16x16x32_bf16_B0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_f32_16x16x32_bf16_B0_overlaps_D1
    ; GFX1250: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr24, $vgpr25, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_f32_16x16x32_bf16_B0_overlaps_D1
    ; GFX1251: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr24, $vgpr25, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_f32_16x16x32_bf16_B0_overlaps_D1
    ; GFX1310: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr24, $vgpr25, implicit $mode, implicit $exec
    $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    $vgpr8 = V_ADD_F32_e32 $vgpr24, $vgpr25, implicit $mode, implicit $exec
...

---
name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_Use1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_Use1
    ; GFX1250: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr27 = V_ADD_F32_e32 $vgpr22, $vgpr26, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_Use1
    ; GFX1251: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr27 = V_ADD_F32_e32 $vgpr22, $vgpr26, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_Use1
    ; GFX1310: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr27 = V_ADD_F32_e32 $vgpr22, $vgpr26, implicit $mode, implicit $exec
    $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    $vgpr27 = V_ADD_F32_e32 $vgpr22, $vgpr26, implicit $mode, implicit $exec
...

---
name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_Use1_with_4_valus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1250: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: $vgpr26 = V_MOV_B32_e32 26, implicit $exec
    ; GFX1250-NEXT: $vgpr27 = V_MOV_B32_e32 27, implicit $exec
    ; GFX1250-NEXT: $vgpr28 = V_MOV_B32_e32 28, implicit $exec
    ; GFX1250-NEXT: $vgpr29 = V_MOV_B32_e32 29, implicit $exec
    ; GFX1250-NEXT: $vgpr31 = V_ADD_F32_e32 $vgpr22, $vgpr30, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1251: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: $vgpr26 = V_MOV_B32_e32 26, implicit $exec
    ; GFX1251-NEXT: $vgpr27 = V_MOV_B32_e32 27, implicit $exec
    ; GFX1251-NEXT: $vgpr28 = V_MOV_B32_e32 28, implicit $exec
    ; GFX1251-NEXT: $vgpr29 = V_MOV_B32_e32 29, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr31 = V_ADD_F32_e32 $vgpr22, $vgpr30, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1310: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr26 = V_MOV_B32_e32 26, implicit $exec
    ; GFX1310-NEXT: $vgpr27 = V_MOV_B32_e32 27, implicit $exec
    ; GFX1310-NEXT: $vgpr28 = V_MOV_B32_e32 28, implicit $exec
    ; GFX1310-NEXT: $vgpr29 = V_MOV_B32_e32 29, implicit $exec
    ; GFX1310-NEXT: $vgpr31 = V_ADD_F32_e32 $vgpr22, $vgpr30, implicit $mode, implicit $exec
    $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    $vgpr26 = V_MOV_B32_e32 26, implicit $exec
    $vgpr27 = V_MOV_B32_e32 27, implicit $exec
    $vgpr28 = V_MOV_B32_e32 28, implicit $exec
    $vgpr29 = V_MOV_B32_e32 29, implicit $exec
    $vgpr31 = V_ADD_F32_e32 $vgpr22, $vgpr30, implicit $mode, implicit $exec
...

---
name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_Use1_with_4_salus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1250: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1250-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1250-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1250-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr27 = V_ADD_F32_e32 $vgpr22, $vgpr26, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1251: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1251-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1251-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1251-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr27 = V_ADD_F32_e32 $vgpr22, $vgpr26, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1310: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1310-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1310-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1310-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1310-NEXT: $vgpr27 = V_ADD_F32_e32 $vgpr22, $vgpr26, implicit $mode, implicit $exec
    $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    $sgpr0 = S_MOV_B32 0
    $sgpr1 = S_MOV_B32 1
    $sgpr2 = S_MOV_B32 2
    $sgpr3 = S_MOV_B32 3
    $vgpr27 = V_ADD_F32_e32 $vgpr22, $vgpr26, implicit $mode, implicit $exec
...

---
name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_D1
    ; GFX1250: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr22 = V_ADD_F32_e32 $vgpr26, $vgpr27, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_D1
    ; GFX1251: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr22 = V_ADD_F32_e32 $vgpr26, $vgpr27, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_D0_overlaps_D1
    ; GFX1310: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr22 = V_ADD_F32_e32 $vgpr26, $vgpr27, implicit $mode, implicit $exec
    $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    $vgpr22 = V_ADD_F32_e32 $vgpr26, $vgpr27, implicit $mode, implicit $exec
...

---
name: test_wmma_f16_16x16x64_fp8_fp8_A0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_A0_overlaps_D1
    ; GFX1250: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr26, $vgpr27, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_A0_overlaps_D1
    ; GFX1251: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr26, $vgpr27, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_A0_overlaps_D1
    ; GFX1310: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr26, $vgpr27, implicit $mode, implicit $exec
    $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    $vgpr0 = V_ADD_F32_e32 $vgpr26, $vgpr27, implicit $mode, implicit $exec
...

---
name: test_wmma_f16_16x16x64_fp8_fp8_B0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_B0_overlaps_D1
    ; GFX1250: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr26, $vgpr27, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_B0_overlaps_D1
    ; GFX1251: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr26, $vgpr27, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_f16_16x16x64_fp8_fp8_B0_overlaps_D1
    ; GFX1310: early-clobber $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr26, $vgpr27, implicit $mode, implicit $exec
    $vgpr22_vgpr23_vgpr24_vgpr25 = V_WMMA_F16_16X16X64_FP8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, killed $vgpr22_vgpr23_vgpr24_vgpr25, 0, 0, 0, 0, implicit $exec
    $vgpr8 = V_ADD_F32_e32 $vgpr26, $vgpr27, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_Use1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_Use1
    ; GFX1250: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_Use1
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_Use1
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_Use1_with_4_valus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1250: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1250-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1250-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1250-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1250-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1250-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1251-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1251-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1251-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1310-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1310-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1310-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1310-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_Use1_with_4_salus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1250: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1250-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1250-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1250-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1250-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1251-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1251-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1251-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1310-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1310-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1310-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1310-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    $sgpr0 = S_MOV_B32 0
    $sgpr1 = S_MOV_B32 1
    $sgpr2 = S_MOV_B32 2
    $sgpr3 = S_MOV_B32 3
    $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_D1
    ; GFX1250: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_D1
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_D0_overlaps_D1
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_A0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_A0_overlaps_D1
    ; GFX1250: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_A0_overlaps_D1
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_A0_overlaps_D1
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_B0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_B0_overlaps_D1
    ; GFX1250: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_B0_overlaps_D1
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F6_F4_B0_overlaps_D1
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f6_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 2, 4, 0, 0, implicit $exec
    $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_D0_overlaps_Use1_with_4_valus_in_between
body: |
  bb.0:
    ; GFX1250-A0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1250-A0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1250-A0-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1250-A0-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1250-A0-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1250-A0-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1250-B0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1250-B0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1250-B0-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1250-B0-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1250-B0-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1250-B0-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1250-B0-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1251-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1251-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1251-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1310-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1310-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1310-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1310-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_D0_overlaps_Use1_with_4_salus_in_between
body: |
  bb.0:
    ; GFX1250-A0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1250-A0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1250-A0-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1250-A0-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1250-A0-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1250-A0-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1250-B0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1250-B0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1250-B0-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1250-B0-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1250-B0-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1250-B0-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1251-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1251-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1251-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1310-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1310-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1310-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1310-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    $sgpr0 = S_MOV_B32 0
    $sgpr1 = S_MOV_B32 1
    $sgpr2 = S_MOV_B32 2
    $sgpr3 = S_MOV_B32 3
    $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_D0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-A0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_D0_overlaps_D1
    ; GFX1250-A0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1250-B0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_D0_overlaps_D1
    ; GFX1250-B0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_D0_overlaps_D1
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_D0_overlaps_D1
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_A0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-A0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_A0_overlaps_D1
    ; GFX1250-A0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1250-B0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_A0_overlaps_D1
    ; GFX1250-B0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_A0_overlaps_D1
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_A0_overlaps_D1
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_B0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-A0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_B0_overlaps_D1
    ; GFX1250-A0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1250-B0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_B0_overlaps_D1
    ; GFX1250-B0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_B0_overlaps_D1
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_F4_B0_overlaps_D1
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 4, 0, 0, implicit $exec
    $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_D0_overlaps_Use1_with_4_valus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1250: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    ; GFX1250-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1250-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1250-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1250-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1250-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1251-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1251-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1251-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1310-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1310-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1310-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1310-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_D0_overlaps_Use1_with_4_salus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1250: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    ; GFX1250-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1250-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1250-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1250-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1251-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1251-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1251-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1310-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1310-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1310-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1310-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    $sgpr0 = S_MOV_B32 0
    $sgpr1 = S_MOV_B32 1
    $sgpr2 = S_MOV_B32 2
    $sgpr3 = S_MOV_B32 3
    $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_D0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_D0_overlaps_D1
    ; GFX1250: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_D0_overlaps_D1
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_D0_overlaps_D1
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_A0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_A0_overlaps_D1
    ; GFX1250: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_A0_overlaps_D1
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F4_F4_A0_overlaps_D1
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F4_B0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F4_B0_overlaps_D1
    ; GFX1250: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F4_B0_overlaps_D1
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F4_B0_overlaps_D1
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f4_f4_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 4, 4, 0, 0, implicit $exec
    $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
...

---
name: test_wmma_I32_16x16x64_IU8_D0_overlaps_Use1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_I32_16x16x64_IU8_D0_overlaps_Use1
    ; GFX1250: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr16, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_I32_16x16x64_IU8_D0_overlaps_Use1
    ; GFX1251: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr16, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_I32_16x16x64_IU8_D0_overlaps_Use1
    ; GFX1310: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr16, $vgpr33, implicit $mode, implicit $exec
    $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    $vgpr32 = V_ADD_F32_e32 $vgpr16, $vgpr33, implicit $mode, implicit $exec
...

---
name: test_wmma_I32_16x16x64_IU8_D0_overlaps_Use1_with_8_valus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_I32_16x16x64_IU8_D0_overlaps_Use1_with_8_valus_in_between
    ; GFX1250: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1250-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1250-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1250-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1250-NEXT: $vgpr44 = V_MOV_B32_e32 44, implicit $exec
    ; GFX1250-NEXT: $vgpr45 = V_MOV_B32_e32 45, implicit $exec
    ; GFX1250-NEXT: $vgpr46 = V_MOV_B32_e32 46, implicit $exec
    ; GFX1250-NEXT: $vgpr47 = V_MOV_B32_e32 47, implicit $exec
    ; GFX1250-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr16, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_I32_16x16x64_IU8_D0_overlaps_Use1_with_8_valus_in_between
    ; GFX1251: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1251-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1251-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1251-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1251-NEXT: $vgpr44 = V_MOV_B32_e32 44, implicit $exec
    ; GFX1251-NEXT: $vgpr45 = V_MOV_B32_e32 45, implicit $exec
    ; GFX1251-NEXT: $vgpr46 = V_MOV_B32_e32 46, implicit $exec
    ; GFX1251-NEXT: $vgpr47 = V_MOV_B32_e32 47, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr16, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_I32_16x16x64_IU8_D0_overlaps_Use1_with_8_valus_in_between
    ; GFX1310: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1310-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1310-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1310-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1310-NEXT: $vgpr44 = V_MOV_B32_e32 44, implicit $exec
    ; GFX1310-NEXT: $vgpr45 = V_MOV_B32_e32 45, implicit $exec
    ; GFX1310-NEXT: $vgpr46 = V_MOV_B32_e32 46, implicit $exec
    ; GFX1310-NEXT: $vgpr47 = V_MOV_B32_e32 47, implicit $exec
    ; GFX1310-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr16, $vgpr33, implicit $mode, implicit $exec
    $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    $vgpr44 = V_MOV_B32_e32 44, implicit $exec
    $vgpr45 = V_MOV_B32_e32 45, implicit $exec
    $vgpr46 = V_MOV_B32_e32 46, implicit $exec
    $vgpr47 = V_MOV_B32_e32 47, implicit $exec
    $vgpr32 = V_ADD_F32_e32 $vgpr16, $vgpr33, implicit $mode, implicit $exec
...

---
name: test_wmma_I32_16x16x64_IU8_D0_overlaps_Use1_with_8_salus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_I32_16x16x64_IU8_D0_overlaps_Use1_with_8_salus_in_between
    ; GFX1250: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1250-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1250-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1250-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1250-NEXT: $sgpr4 = S_MOV_B32 4
    ; GFX1250-NEXT: $sgpr5 = S_MOV_B32 5
    ; GFX1250-NEXT: $sgpr6 = S_MOV_B32 6
    ; GFX1250-NEXT: $sgpr7 = S_MOV_B32 7
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr16, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_I32_16x16x64_IU8_D0_overlaps_Use1_with_8_salus_in_between
    ; GFX1251: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1251-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1251-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1251-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1251-NEXT: $sgpr4 = S_MOV_B32 4
    ; GFX1251-NEXT: $sgpr5 = S_MOV_B32 5
    ; GFX1251-NEXT: $sgpr6 = S_MOV_B32 6
    ; GFX1251-NEXT: $sgpr7 = S_MOV_B32 7
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr16, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_I32_16x16x64_IU8_D0_overlaps_Use1_with_8_salus_in_between
    ; GFX1310: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1310-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1310-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1310-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1310-NEXT: $sgpr4 = S_MOV_B32 4
    ; GFX1310-NEXT: $sgpr5 = S_MOV_B32 5
    ; GFX1310-NEXT: $sgpr6 = S_MOV_B32 6
    ; GFX1310-NEXT: $sgpr7 = S_MOV_B32 7
    ; GFX1310-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr16, $vgpr33, implicit $mode, implicit $exec
    $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    $sgpr0 = S_MOV_B32 0
    $sgpr1 = S_MOV_B32 1
    $sgpr2 = S_MOV_B32 2
    $sgpr3 = S_MOV_B32 3
    $sgpr4 = S_MOV_B32 4
    $sgpr5 = S_MOV_B32 5
    $sgpr6 = S_MOV_B32 6
    $sgpr7 = S_MOV_B32 7
    $vgpr32 = V_ADD_F32_e32 $vgpr16, $vgpr33, implicit $mode, implicit $exec
...

---
name: test_wmma_I32_16x16x64_IU8_D0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_I32_16x16x64_IU8_D0_overlaps_D1
    ; GFX1250: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr32, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_I32_16x16x64_IU8_D0_overlaps_D1
    ; GFX1251: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr32, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_I32_16x16x64_IU8_D0_overlaps_D1
    ; GFX1310: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr32, $vgpr33, implicit $mode, implicit $exec
    $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    $vgpr16 = V_ADD_F32_e32 $vgpr32, $vgpr33, implicit $mode, implicit $exec
...

---
name: test_wmma_I32_16x16x64_IU8_A0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_I32_16x16x64_IU8_A0_overlaps_D1
    ; GFX1250: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr32, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_I32_16x16x64_IU8_A0_overlaps_D1
    ; GFX1251: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr32, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_I32_16x16x64_IU8_A0_overlaps_D1
    ; GFX1310: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr32, $vgpr33, implicit $mode, implicit $exec
    $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    $vgpr0 = V_ADD_F32_e32 $vgpr32, $vgpr33, implicit $mode, implicit $exec
...

---
name: test_wmma_I32_16x16x64_IU8_B0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_I32_16x16x64_IU8_B0_overlaps_D1
    ; GFX1250: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr32, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_I32_16x16x64_IU8_B0_overlaps_D1
    ; GFX1251: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr32, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_I32_16x16x64_IU8_B0_overlaps_D1
    ; GFX1310: early-clobber $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr32, $vgpr33, implicit $mode, implicit $exec
    $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23 = V_WMMA_I32_16X16X64_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, 0, 0, 0, 0, implicit $exec
    $vgpr8 = V_ADD_F32_e32 $vgpr32, $vgpr33, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_Use1
body: |
  bb.0:
    ; GFX1250-A0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_Use1
    ; GFX1250-A0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 2, 0, 0, implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1250-B0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_Use1
    ; GFX1250-B0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 2, 0, 0, implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_Use1
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 2, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_Use1
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 2, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 2, 0, 0, implicit $exec
    $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_Use1_with_8_valus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_Use1_with_8_valus_in_between
    ; GFX1250: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 2, 0, 0, implicit $exec
    ; GFX1250-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1250-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1250-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1250-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1250-NEXT: $vgpr44 = V_MOV_B32_e32 44, implicit $exec
    ; GFX1250-NEXT: $vgpr45 = V_MOV_B32_e32 45, implicit $exec
    ; GFX1250-NEXT: $vgpr46 = V_MOV_B32_e32 46, implicit $exec
    ; GFX1250-NEXT: $vgpr47 = V_MOV_B32_e32 47, implicit $exec
    ; GFX1250-NEXT: $vgpr49 = V_ADD_F32_e32 $vgpr32, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_Use1_with_8_valus_in_between
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 2, 0, 0, implicit $exec
    ; GFX1251-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1251-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1251-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1251-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1251-NEXT: $vgpr44 = V_MOV_B32_e32 44, implicit $exec
    ; GFX1251-NEXT: $vgpr45 = V_MOV_B32_e32 45, implicit $exec
    ; GFX1251-NEXT: $vgpr46 = V_MOV_B32_e32 46, implicit $exec
    ; GFX1251-NEXT: $vgpr47 = V_MOV_B32_e32 47, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr49 = V_ADD_F32_e32 $vgpr32, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_Use1_with_8_valus_in_between
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 2, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1310-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1310-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1310-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1310-NEXT: $vgpr44 = V_MOV_B32_e32 44, implicit $exec
    ; GFX1310-NEXT: $vgpr45 = V_MOV_B32_e32 45, implicit $exec
    ; GFX1310-NEXT: $vgpr46 = V_MOV_B32_e32 46, implicit $exec
    ; GFX1310-NEXT: $vgpr47 = V_MOV_B32_e32 47, implicit $exec
    ; GFX1310-NEXT: $vgpr49 = V_ADD_F32_e32 $vgpr32, $vgpr48, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 2, 0, 0, implicit $exec
    $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    $vgpr44 = V_MOV_B32_e32 44, implicit $exec
    $vgpr45 = V_MOV_B32_e32 45, implicit $exec
    $vgpr46 = V_MOV_B32_e32 46, implicit $exec
    $vgpr47 = V_MOV_B32_e32 47, implicit $exec
    $vgpr49 = V_ADD_F32_e32 $vgpr32, $vgpr48, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_Use1_with_8_salus_in_between
body: |
  bb.0:
    ; GFX1250-A0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_Use1_with_8_salus_in_between
    ; GFX1250-A0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1250-A0-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1250-A0-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1250-A0-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1250-A0-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1250-A0-NEXT: $sgpr4 = S_MOV_B32 4
    ; GFX1250-A0-NEXT: $sgpr5 = S_MOV_B32 5
    ; GFX1250-A0-NEXT: $sgpr6 = S_MOV_B32 6
    ; GFX1250-A0-NEXT: $sgpr7 = S_MOV_B32 7
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1250-B0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_Use1_with_8_salus_in_between
    ; GFX1250-B0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1250-B0-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1250-B0-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1250-B0-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1250-B0-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1250-B0-NEXT: $sgpr4 = S_MOV_B32 4
    ; GFX1250-B0-NEXT: $sgpr5 = S_MOV_B32 5
    ; GFX1250-B0-NEXT: $sgpr6 = S_MOV_B32 6
    ; GFX1250-B0-NEXT: $sgpr7 = S_MOV_B32 7
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_Use1_with_8_salus_in_between
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1251-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1251-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1251-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1251-NEXT: $sgpr4 = S_MOV_B32 4
    ; GFX1251-NEXT: $sgpr5 = S_MOV_B32 5
    ; GFX1251-NEXT: $sgpr6 = S_MOV_B32 6
    ; GFX1251-NEXT: $sgpr7 = S_MOV_B32 7
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_Use1_with_8_salus_in_between
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1310-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1310-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1310-NEXT: $sgpr3 = S_MOV_B32 3
    ; GFX1310-NEXT: $sgpr4 = S_MOV_B32 4
    ; GFX1310-NEXT: $sgpr5 = S_MOV_B32 5
    ; GFX1310-NEXT: $sgpr6 = S_MOV_B32 6
    ; GFX1310-NEXT: $sgpr7 = S_MOV_B32 7
    ; GFX1310-NEXT: $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    $sgpr0 = S_MOV_B32 0
    $sgpr1 = S_MOV_B32 1
    $sgpr2 = S_MOV_B32 2
    $sgpr3 = S_MOV_B32 3
    $sgpr4 = S_MOV_B32 4
    $sgpr5 = S_MOV_B32 5
    $sgpr6 = S_MOV_B32 6
    $sgpr7 = S_MOV_B32 7
    $vgpr48 = V_ADD_F32_e32 $vgpr32, $vgpr47, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-A0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_D1
    ; GFX1250-A0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1250-B0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_D1
    ; GFX1250-B0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_D1
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_D0_overlaps_D1
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    $vgpr32 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F8_A0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-A0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_A0_overlaps_D1
    ; GFX1250-A0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1250-B0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_A0_overlaps_D1
    ; GFX1250-B0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_A0_overlaps_D1
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_A0_overlaps_D1
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    $vgpr0 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
...

---
name: test_wmma_F32_16x16x128_F8F6F4_F8_B0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-A0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_B0_overlaps_D1
    ; GFX1250-A0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-A0-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1250-B0-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_B0_overlaps_D1
    ; GFX1250-B0: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-B0-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_B0_overlaps_D1
    ; GFX1251: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_F32_16x16x128_F8F6F4_F8_B0_overlaps_D1
    ; GFX1310: early-clobber $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
    $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39 = V_WMMA_F32_16X16X128_F8F6F4_f8_f8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, killed $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 8, killed $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39, 0, 0, 0, 0, implicit $exec
    $vgpr16 = V_ADD_F32_e32 $vgpr47, $vgpr48, implicit $mode, implicit $exec
...

---
name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_Use1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_Use1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr24, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_Use1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr24, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_Use1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr24, $vgpr33, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    $vgpr34 = V_ADD_F32_e32 $vgpr24, $vgpr33, implicit $mode, implicit $exec
...

---
name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_Use1_with_2_valus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_Use1_with_2_valus_in_between
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1250-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1250-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr24, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_Use1_with_2_valus_in_between
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1251-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr24, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_Use1_with_2_valus_in_between
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1310-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1310-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr24, $vgpr33, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    $vgpr34 = V_ADD_F32_e32 $vgpr24, $vgpr33, implicit $mode, implicit $exec
...

---
name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_Use1_with_2_salus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_Use1_with_2_salus_in_between
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1250-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr24, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_Use1_with_2_salus_in_between
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1251-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr24, $vgpr33, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_Use1_with_2_salus_in_between
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1310-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1310-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr24, $vgpr33, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    $sgpr0 = S_MOV_B32 0
    $sgpr1 = S_MOV_B32 1
    $vgpr34 = V_ADD_F32_e32 $vgpr24, $vgpr33, implicit $mode, implicit $exec
...

---
name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_D1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr24 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_D1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr24 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_f32_16x16x64_bf16_D0_overlaps_D1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr24 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    $vgpr24 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
...

---
name: test_swmmac_f32_16x16x64_bf16_A0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_f32_16x16x64_bf16_A0_overlaps_D1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_f32_16x16x64_bf16_A0_overlaps_D1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_f32_16x16x64_bf16_A0_overlaps_D1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    $vgpr0 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
...

---
name: test_swmmac_f32_16x16x64_bf16_B0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_f32_16x16x64_bf16_B0_overlaps_D1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_f32_16x16x64_bf16_B0_overlaps_D1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_f32_16x16x64_bf16_B0_overlaps_D1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    $vgpr8 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
...

---
name: test_swmmac_f32_16x16x64_bf16_Index0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_f32_16x16x64_bf16_Index0_overlaps_D1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_f32_16x16x64_bf16_Index0_overlaps_D1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_f32_16x16x64_bf16_Index0_overlaps_D1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_F32_16X16X64_BF16_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32, 0, 0, 0, 0, 0, implicit $exec
    $vgpr32 = V_ADD_F32_e32 $vgpr33, $vgpr34, implicit $mode, implicit $exec
...

---
name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_Use1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_Use1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr31 = V_ADD_F32_e32 $vgpr24, $vgpr30, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_Use1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr31 = V_ADD_F32_e32 $vgpr24, $vgpr30, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_Use1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr31 = V_ADD_F32_e32 $vgpr24, $vgpr30, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    $vgpr31 = V_ADD_F32_e32 $vgpr24, $vgpr30, implicit $mode, implicit $exec
...

---
name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_Use1_with_2_valus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_Use1_with_2_valus_in_between
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1250-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1250-NEXT: $vgpr31 = V_ADD_F32_e32 $vgpr24, $vgpr30, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_Use1_with_2_valus_in_between
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1251-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr31 = V_ADD_F32_e32 $vgpr24, $vgpr30, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_Use1_with_2_valus_in_between
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1310-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1310-NEXT: $vgpr31 = V_ADD_F32_e32 $vgpr24, $vgpr30, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    $vgpr31 = V_ADD_F32_e32 $vgpr24, $vgpr30, implicit $mode, implicit $exec
...

---
name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_Use1_with_2_salus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_Use1_with_2_salus_in_between
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1250-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr31 = V_ADD_F32_e32 $vgpr24, $vgpr30, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_Use1_with_2_salus_in_between
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1251-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr31 = V_ADD_F32_e32 $vgpr24, $vgpr30, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_Use1_with_2_salus_in_between
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1310-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1310-NEXT: $vgpr31 = V_ADD_F32_e32 $vgpr24, $vgpr30, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    $sgpr0 = S_MOV_B32 0
    $sgpr1 = S_MOV_B32 1
    $vgpr31 = V_ADD_F32_e32 $vgpr24, $vgpr30, implicit $mode, implicit $exec
...

---
name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_D1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr24 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_D1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr24 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_D0_overlaps_D1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr24 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    $vgpr24 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
...

---
name: test_swmmac_f16_16x16x128_bf8_fp8_A0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_A0_overlaps_D1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_A0_overlaps_D1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_A0_overlaps_D1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    $vgpr0 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
...

---
name: test_swmmac_f16_16x16x128_bf8_fp8_B0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_B0_overlaps_D1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_B0_overlaps_D1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_B0_overlaps_D1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    $vgpr8 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
...

---
name: test_swmmac_f16_16x16x128_bf8_fp8_Index0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_Index0_overlaps_D1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr28 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_Index0_overlaps_D1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr28 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_f16_16x16x128_bf8_fp8_Index0_overlaps_D1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr28 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27 = V_SWMMAC_F16_16X16X128_BF8_FP8_w32_twoaddr killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27, killed $vgpr28_vgpr29, 0, 0, 0, implicit $exec
    $vgpr28 = V_ADD_F32_e32 $vgpr30, $vgpr31, implicit $mode, implicit $exec
...

---
name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_Use1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_Use1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr33, $vgpr24, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_Use1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr33, $vgpr24, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_Use1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr33, $vgpr24, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    $vgpr34 = V_ADD_F32_e32 $vgpr33, $vgpr24, implicit $mode, implicit $exec
...

---
name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_Use1_with_4_valus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1250-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1250-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1250-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1250-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr34, $vgpr24, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1251-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1251-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1251-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr34, $vgpr24, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_Use1_with_4_valus_in_between
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    ; GFX1310-NEXT: $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    ; GFX1310-NEXT: $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    ; GFX1310-NEXT: $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    ; GFX1310-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr34, $vgpr24, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    $vgpr40 = V_MOV_B32_e32 40, implicit $exec
    $vgpr41 = V_MOV_B32_e32 41, implicit $exec
    $vgpr42 = V_MOV_B32_e32 42, implicit $exec
    $vgpr43 = V_MOV_B32_e32 43, implicit $exec
    $vgpr34 = V_ADD_F32_e32 $vgpr34, $vgpr24, implicit $mode, implicit $exec
...

---
name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_Use1_with_4_salus_in_between
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1250-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1250-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1250-NEXT: $sgpr3 = S_MOV_B32 4
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr34, $vgpr24, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1251-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1251-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1251-NEXT: $sgpr3 = S_MOV_B32 4
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr34, $vgpr24, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_Use1_with_4_salus_in_between
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $sgpr0 = S_MOV_B32 0
    ; GFX1310-NEXT: $sgpr1 = S_MOV_B32 1
    ; GFX1310-NEXT: $sgpr2 = S_MOV_B32 2
    ; GFX1310-NEXT: $sgpr3 = S_MOV_B32 4
    ; GFX1310-NEXT: $vgpr34 = V_ADD_F32_e32 $vgpr34, $vgpr24, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    $sgpr0 = S_MOV_B32 0
    $sgpr1 = S_MOV_B32 1
    $sgpr2 = S_MOV_B32 2
    $sgpr3 = S_MOV_B32 4
    $vgpr34 = V_ADD_F32_e32 $vgpr34, $vgpr24, implicit $mode, implicit $exec
...

---
name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_D1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr24 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_D1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr24 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_i32_16x16x128_iu8_D0_overlaps_D1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr24 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    $vgpr24 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
...

---
name: test_swmmac_i32_16x16x128_iu8_A0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_i32_16x16x128_iu8_A0_overlaps_D1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_i32_16x16x128_iu8_A0_overlaps_D1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_i32_16x16x128_iu8_A0_overlaps_D1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr0 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    $vgpr0 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
...

---
name: test_swmmac_i32_16x16x128_iu8_B0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_i32_16x16x128_iu8_B0_overlaps_D1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_i32_16x16x128_iu8_B0_overlaps_D1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_i32_16x16x128_iu8_B0_overlaps_D1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr8 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    $vgpr8 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
...

---
name: test_swmmac_i32_16x16x128_iu8_Index0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_swmmac_i32_16x16x128_iu8_Index0_overlaps_D1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_swmmac_i32_16x16x128_iu8_Index0_overlaps_D1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_swmmac_i32_16x16x128_iu8_Index0_overlaps_D1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr32 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_SWMMAC_I32_16X16X128_IU8_w32_twoaddr 8, killed $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, 8, killed $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, killed $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, killed $vgpr32_vgpr33, 0, 0, 0, 0, 0, implicit $exec
    $vgpr32 = V_ADD_F32_e32 $vgpr34, $vgpr35, implicit $mode, implicit $exec
...

---
name: test_wmma_trans_B0_overlaps_D1
body: |
  bb.0:
    ; GFX1250-LABEL: name: test_wmma_trans_B0_overlaps_D1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: V_NOP_e32 implicit $exec
    ; GFX1250-NEXT: $vgpr8 = V_EXP_F32_e32 $vgpr34, implicit $mode, implicit $exec
    ;
    ; GFX1251-LABEL: name: test_wmma_trans_B0_overlaps_D1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: V_NOP_e32 implicit $exec
    ; GFX1251-NEXT: $vgpr8 = V_EXP_F32_e32 $vgpr34, implicit $mode, implicit $exec
    ;
    ; GFX1310-LABEL: name: test_wmma_trans_B0_overlaps_D1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: $vgpr8 = V_EXP_F32_e32 $vgpr34, implicit $mode, implicit $exec
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 0, 0, 0, 0, implicit $exec
    $vgpr8 = V_EXP_F32_e32 $vgpr34, implicit $mode, implicit $exec
...

---
name: test_wmma_tdm_load_D0_overlaps_Use1
body: |
  bb.0:
    ; GFX125X-LABEL: name: test_wmma_tdm_load_D0_overlaps_Use1
    ; GFX125X: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 0, 0, 0, 0, implicit $exec
    ; GFX125X-NEXT: GLOBAL_STORE_ASYNC_FROM_LDS_B8_SADDR killed $sgpr0_sgpr1, killed $vgpr24, killed $vgpr0, 16, 0, implicit-def dead $asynccnt, implicit $exec, implicit $asynccnt
    ; GFX1250-LABEL: name: test_wmma_tdm_load_D0_overlaps_Use1
    ; GFX1250: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 0, 0, 0, 0, implicit $exec
    ; GFX1250-NEXT: GLOBAL_STORE_ASYNC_FROM_LDS_B8_SADDR killed $sgpr0_sgpr1, killed $vgpr24, killed $vgpr0, 16, 0, implicit-def dead $asynccnt, implicit $exec, implicit $asynccnt
    ;
    ; GFX1251-LABEL: name: test_wmma_tdm_load_D0_overlaps_Use1
    ; GFX1251: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 0, 0, 0, 0, implicit $exec
    ; GFX1251-NEXT: GLOBAL_STORE_ASYNC_FROM_LDS_B8_SADDR killed $sgpr0_sgpr1, killed $vgpr24, killed $vgpr0, 16, 0, implicit-def dead $asynccnt, implicit $exec, implicit $asynccnt
    ;
    ; GFX1310-LABEL: name: test_wmma_tdm_load_D0_overlaps_Use1
    ; GFX1310: early-clobber $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 0, 0, 0, 0, implicit $exec
    ; GFX1310-NEXT: GLOBAL_STORE_ASYNC_FROM_LDS_B8_SADDR killed $sgpr0_sgpr1, killed $vgpr24, killed $vgpr0, 16, 0, implicit-def dead $asynccnt, implicit $exec, implicit $asynccnt
    $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31 = V_WMMA_F32_16X16X32_BF16_w32_twoaddr $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7, $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 8, $vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, 0, 0, 0, 0, implicit $exec
    GLOBAL_STORE_ASYNC_FROM_LDS_B8_SADDR killed $sgpr0_sgpr1, killed $vgpr24, killed $vgpr0, 16, 0, implicit-def dead $asynccnt, implicit $exec, implicit $asynccnt
...
