; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 < %s | FileCheck -check-prefix=GCN,GFX1100 %s
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1151 < %s | FileCheck -check-prefix=GCN,GFX1151 %s

; Bank-conflict avoidance hint for v_wmma_* operands: the allocator should keep
; the WMMA source operands (and the accumulator/result) in distinct VGPR banks
; (bank = first VGPR % 4) without inflating the VGPR footprint on low-pressure
; functions. See issue #204254.

declare i32 @llvm.amdgcn.workitem.id.x()
declare i32 @llvm.amdgcn.workgroup.id.x()
declare <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half>, <16 x half>, <8 x float>)

; A single WMMA in an ordinary (non-kernel) function. This must not blow up the
; VGPR footprint: separating banks here would require climbing above the
; argument registers, which costs more occupancy than it saves, so the hint
; should stay opportunistic and keep the footprint near baseline.
define void @wmma_f32_single(ptr %a, ptr %b, ptr %c, ptr %out) {
; GCN-LABEL: wmma_f32_single:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    s_clause 0x1
; GCN-NEXT:    flat_load_b128 v[13:16], v[0:1] offset:16
; GCN-NEXT:    flat_load_b128 v[9:12], v[0:1]
; GCN-NEXT:    s_clause 0x1
; GCN-NEXT:    flat_load_b128 v[22:25], v[2:3] offset:16
; GCN-NEXT:    flat_load_b128 v[18:21], v[2:3]
; GCN-NEXT:    s_clause 0x1
; GCN-NEXT:    flat_load_b128 v[31:34], v[4:5] offset:16
; GCN-NEXT:    flat_load_b128 v[27:30], v[4:5]
; GCN-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[27:34], v[9:16], v[18:25], v[27:34]
; GCN-NEXT:    s_clause 0x1
; GCN-NEXT:    flat_store_b128 v[6:7], v[31:34] offset:16
; GCN-NEXT:    flat_store_b128 v[6:7], v[27:30]
; GCN-NEXT:    s_waitcnt lgkmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %loada = load <16 x half>, ptr %a
  %loadb = load <16 x half>, ptr %b
  %loadc = load <8 x float>, ptr %c
  %wmma = tail call contract <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %loada, <16 x half> %loadb, <8 x float> %loadc)
  store <8 x float> %wmma, ptr %out
  ret void
}

; A WMMA accumulated across a loop in a kernel. The A/B operands and the
; accumulator should land in separate banks.
define protected amdgpu_kernel void @wmma_f32_accumulate_loop(ptr addrspace(1) noundef writeonly captures(none) %0, ptr addrspace(1) noundef readonly captures(none) %1, ptr addrspace(1) noundef readonly captures(none) %2, i32 noundef %3) local_unnamed_addr {
; GFX1100-LABEL: wmma_f32_accumulate_loop:
; GFX1100:       ; %bb.0:
; GFX1100-NEXT:    s_clause 0x2
; GFX1100-NEXT:    s_load_b32 s7, s[4:5], 0x18
; GFX1100-NEXT:    s_load_b128 s[0:3], s[4:5], 0x0
; GFX1100-NEXT:    s_load_b64 s[4:5], s[4:5], 0x10
; GFX1100-NEXT:    v_and_b32_e32 v8, 0x3ff, v0
; GFX1100-NEXT:    s_mov_b32 s6, s13
; GFX1100-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1100-NEXT:    s_cmp_lt_i32 s7, 1
; GFX1100-NEXT:    s_cbranch_scc1 .LBB1_3
; GFX1100-NEXT:  ; %bb.1: ; %.preheader
; GFX1100-NEXT:    v_lshlrev_b32_e32 v0, 5, v8
; GFX1100-NEXT:    s_clause 0x3
; GFX1100-NEXT:    global_load_b128 v[13:16], v0, s[2:3] offset:16
; GFX1100-NEXT:    global_load_b128 v[9:12], v0, s[2:3]
; GFX1100-NEXT:    global_load_b128 v[22:25], v0, s[4:5] offset:16
; GFX1100-NEXT:    global_load_b128 v[18:21], v0, s[4:5]
; GFX1100-NEXT:    v_mov_b32_e32 v0, 0
; GFX1100-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1100-NEXT:    v_mov_b32_e32 v1, v0
; GFX1100-NEXT:    v_mov_b32_e32 v2, v0
; GFX1100-NEXT:    v_mov_b32_e32 v3, v0
; GFX1100-NEXT:    v_mov_b32_e32 v4, v0
; GFX1100-NEXT:    v_mov_b32_e32 v5, v0
; GFX1100-NEXT:    v_mov_b32_e32 v6, v0
; GFX1100-NEXT:    v_mov_b32_e32 v7, v0
; GFX1100-NEXT:  .LBB1_2: ; =>This Inner Loop Header: Depth=1
; GFX1100-NEXT:    s_waitcnt vmcnt(0)
; GFX1100-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(SALU_CYCLE_1)
; GFX1100-NEXT:    v_wmma_f32_16x16x16_f16 v[0:7], v[9:16], v[18:25], v[0:7]
; GFX1100-NEXT:    s_add_i32 s7, s7, -1
; GFX1100-NEXT:    s_cmp_eq_u32 s7, 0
; GFX1100-NEXT:    s_cbranch_scc0 .LBB1_2
; GFX1100-NEXT:    s_branch .LBB1_4
; GFX1100-NEXT:  .LBB1_3:
; GFX1100-NEXT:    v_mov_b32_e32 v0, 0
; GFX1100-NEXT:  .LBB1_4: ; %Flow26
; GFX1100-NEXT:    s_mov_b32 s7, 0
; GFX1100-NEXT:    s_mov_b32 s2, exec_lo
; GFX1100-NEXT:    v_cmpx_eq_u32_e32 0, v8
; GFX1100-NEXT:    s_cbranch_execz .LBB1_6
; GFX1100-NEXT:  ; %bb.5:
; GFX1100-NEXT:    s_lshl_b64 s[2:3], s[6:7], 2
; GFX1100-NEXT:    v_mov_b32_e32 v1, 0
; GFX1100-NEXT:    s_add_u32 s0, s0, s2
; GFX1100-NEXT:    s_addc_u32 s1, s1, s3
; GFX1100-NEXT:    global_store_b32 v1, v0, s[0:1]
; GFX1100-NEXT:  .LBB1_6:
; GFX1100-NEXT:    s_endpgm
;
; GFX1151-LABEL: wmma_f32_accumulate_loop:
; GFX1151:       ; %bb.0:
; GFX1151-NEXT:    s_clause 0x2
; GFX1151-NEXT:    s_load_b32 s6, s[4:5], 0x18
; GFX1151-NEXT:    s_load_b128 s[0:3], s[4:5], 0x0
; GFX1151-NEXT:    s_load_b64 s[4:5], s[4:5], 0x10
; GFX1151-NEXT:    v_and_b32_e32 v8, 0x3ff, v0
; GFX1151-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1151-NEXT:    s_cmp_lt_i32 s6, 1
; GFX1151-NEXT:    s_cbranch_scc1 .LBB1_3
; GFX1151-NEXT:  ; %bb.1: ; %.preheader
; GFX1151-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1151-NEXT:    v_lshlrev_b32_e32 v0, 5, v8
; GFX1151-NEXT:    s_clause 0x3
; GFX1151-NEXT:    global_load_b128 v[13:16], v0, s[2:3] offset:16
; GFX1151-NEXT:    global_load_b128 v[9:12], v0, s[2:3]
; GFX1151-NEXT:    global_load_b128 v[22:25], v0, s[4:5] offset:16
; GFX1151-NEXT:    global_load_b128 v[18:21], v0, s[4:5]
; GFX1151-NEXT:    v_mov_b32_e32 v0, 0
; GFX1151-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1151-NEXT:    v_mov_b32_e32 v1, v0
; GFX1151-NEXT:    v_mov_b32_e32 v2, v0
; GFX1151-NEXT:    v_mov_b32_e32 v3, v0
; GFX1151-NEXT:    v_mov_b32_e32 v4, v0
; GFX1151-NEXT:    v_mov_b32_e32 v5, v0
; GFX1151-NEXT:    v_mov_b32_e32 v6, v0
; GFX1151-NEXT:    v_mov_b32_e32 v7, v0
; GFX1151-NEXT:  .LBB1_2: ; =>This Inner Loop Header: Depth=1
; GFX1151-NEXT:    s_waitcnt vmcnt(0)
; GFX1151-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(SALU_CYCLE_1)
; GFX1151-NEXT:    v_wmma_f32_16x16x16_f16 v[0:7], v[9:16], v[18:25], v[0:7]
; GFX1151-NEXT:    s_add_i32 s6, s6, -1
; GFX1151-NEXT:    s_cmp_eq_u32 s6, 0
; GFX1151-NEXT:    s_cbranch_scc0 .LBB1_2
; GFX1151-NEXT:    s_branch .LBB1_4
; GFX1151-NEXT:  .LBB1_3:
; GFX1151-NEXT:    v_mov_b32_e32 v0, 0
; GFX1151-NEXT:  .LBB1_4: ; %Flow26
; GFX1151-NEXT:    s_mov_b32 s9, 0
; GFX1151-NEXT:    s_mov_b32 s2, exec_lo
; GFX1151-NEXT:    v_cmpx_eq_u32_e32 0, v8
; GFX1151-NEXT:    s_cbranch_execz .LBB1_6
; GFX1151-NEXT:  ; %bb.5:
; GFX1151-NEXT:    s_lshl_b64 s[2:3], s[8:9], 2
; GFX1151-NEXT:    v_mov_b32_e32 v1, 0
; GFX1151-NEXT:    s_add_u32 s0, s0, s2
; GFX1151-NEXT:    s_addc_u32 s1, s1, s3
; GFX1151-NEXT:    global_store_b32 v1, v0, s[0:1]
; GFX1151-NEXT:  .LBB1_6:
; GFX1151-NEXT:    s_endpgm
  %5 = tail call i32 @llvm.amdgcn.workitem.id.x()
  %6 = zext nneg i32 %5 to i64
  %7 = getelementptr inbounds nuw <16 x half>, ptr addrspace(1) %1, i64 %6
  %8 = load <16 x half>, ptr addrspace(1) %7, align 32
  %9 = getelementptr inbounds nuw <16 x half>, ptr addrspace(1) %2, i64 %6
  %10 = load <16 x half>, ptr addrspace(1) %9, align 32
  %11 = icmp sgt i32 %3, 0
  br i1 %11, label %15, label %12

12:                                               ; preds = %15, %4
  %13 = phi <8 x float> [ zeroinitializer, %4 ], [ %18, %15 ]
  %14 = icmp eq i32 %5, 0
  br i1 %14, label %21, label %26

15:                                               ; preds = %4, %15
  %16 = phi i32 [ %19, %15 ], [ 0, %4 ]
  %17 = phi <8 x float> [ %18, %15 ], [ zeroinitializer, %4 ]
  %18 = tail call contract <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %8, <16 x half> %10, <8 x float> %17)
  %19 = add nuw nsw i32 %16, 1
  %20 = icmp eq i32 %19, %3
  br i1 %20, label %12, label %15

21:                                               ; preds = %12
  %22 = tail call i32 @llvm.amdgcn.workgroup.id.x()
  %23 = zext i32 %22 to i64
  %24 = getelementptr inbounds nuw float, ptr addrspace(1) %0, i64 %23
  %25 = extractelement <8 x float> %13, i64 0
  store float %25, ptr addrspace(1) %24, align 4
  br label %26

26:                                               ; preds = %21, %12
  ret void
}

; Three independent WMMAs under maximum register pressure
; ("amdgpu-waves-per-eu"="256,256" clamps to the smallest VGPR budget). Even
; with no slack, all three should get their A/B/C operands in distinct banks.
define amdgpu_kernel void @wmma_f32_3x_high_pressure(ptr addrspace(1) %pa, ptr addrspace(1) %pb, ptr addrspace(1) %out) #1 {
; GCN-LABEL: wmma_f32_3x_high_pressure:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_clause 0x1
; GCN-NEXT:    s_load_b128 s[44:47], s[4:5], 0x0
; GCN-NEXT:    s_load_b64 s[34:35], s[4:5], 0x10
; GCN-NEXT:    s_mov_b32 s52, 0
; GCN-NEXT:    s_waitcnt lgkmcnt(0)
; GCN-NEXT:    s_load_b256 s[0:7], s[44:45], 0x0
; GCN-NEXT:    s_load_b256 s[8:15], s[46:47], 0x0
; GCN-NEXT:    s_load_b256 s[16:23], s[44:45], 0x20
; GCN-NEXT:    s_load_b256 s[24:31], s[46:47], 0x20
; GCN-NEXT:    s_load_b256 s[36:43], s[44:45], 0x40
; GCN-NEXT:    s_load_b256 s[44:51], s[46:47], 0x40
; GCN-NEXT:    s_mov_b32 s53, s52
; GCN-NEXT:    s_mov_b32 s54, s52
; GCN-NEXT:    s_mov_b32 s55, s52
; GCN-NEXT:    s_mov_b32 s56, s52
; GCN-NEXT:    s_mov_b32 s57, s52
; GCN-NEXT:    s_mov_b32 s58, s52
; GCN-NEXT:    s_mov_b32 s59, s52
; GCN-NEXT:    v_dual_mov_b32 v0, s52 :: v_dual_mov_b32 v3, s55
; GCN-NEXT:    v_dual_mov_b32 v16, 0 :: v_dual_mov_b32 v1, s53
; GCN-NEXT:    v_dual_mov_b32 v2, s54 :: v_dual_mov_b32 v5, s57
; GCN-NEXT:    v_dual_mov_b32 v4, s56 :: v_dual_mov_b32 v7, s59
; GCN-NEXT:    s_waitcnt lgkmcnt(0)
; GCN-NEXT:    v_dual_mov_b32 v24, s7 :: v_dual_mov_b32 v21, s4
; GCN-NEXT:    v_dual_mov_b32 v18, s1 :: v_dual_mov_b32 v41, s15
; GCN-NEXT:    v_dual_mov_b32 v6, s58 :: v_dual_mov_b32 v23, s6
; GCN-NEXT:    v_dual_mov_b32 v22, s5 :: v_dual_mov_b32 v19, s2
; GCN-NEXT:    v_dual_mov_b32 v20, s3 :: v_dual_mov_b32 v17, s0
; GCN-NEXT:    v_dual_mov_b32 v40, s14 :: v_dual_mov_b32 v39, s13
; GCN-NEXT:    v_dual_mov_b32 v38, s12 :: v_dual_mov_b32 v37, s11
; GCN-NEXT:    v_dual_mov_b32 v36, s10 :: v_dual_mov_b32 v35, s9
; GCN-NEXT:    v_mov_b32_e32 v34, s8
; GCN-NEXT:    v_dual_mov_b32 v58, s23 :: v_dual_mov_b32 v55, s20
; GCN-NEXT:    v_dual_mov_b32 v32, s31 :: v_dual_mov_b32 v29, s28
; GCN-NEXT:    v_dual_mov_b32 v57, s22 :: v_dual_mov_b32 v56, s21
; GCN-NEXT:    v_dual_mov_b32 v53, s18 :: v_dual_mov_b32 v54, s19
; GCN-NEXT:    v_dual_mov_b32 v51, s16 :: v_dual_mov_b32 v52, s17
; GCN-NEXT:    v_dual_mov_b32 v31, s30 :: v_dual_mov_b32 v30, s29
; GCN-NEXT:    v_dual_mov_b32 v27, s26 :: v_dual_mov_b32 v28, s27
; GCN-NEXT:    v_dual_mov_b32 v25, s24 :: v_dual_mov_b32 v26, s25
; GCN-NEXT:    v_dual_mov_b32 v49, s43 :: v_dual_mov_b32 v66, s51
; GCN-NEXT:    v_dual_mov_b32 v63, s48 :: v_dual_mov_b32 v48, s42
; GCN-NEXT:    v_dual_mov_b32 v47, s41 :: v_dual_mov_b32 v46, s40
; GCN-NEXT:    v_dual_mov_b32 v45, s39 :: v_dual_mov_b32 v44, s38
; GCN-NEXT:    v_dual_mov_b32 v43, s37 :: v_dual_mov_b32 v42, s36
; GCN-NEXT:    v_dual_mov_b32 v65, s50 :: v_dual_mov_b32 v64, s49
; GCN-NEXT:    v_dual_mov_b32 v61, s46 :: v_dual_mov_b32 v62, s47
; GCN-NEXT:    v_dual_mov_b32 v59, s44 :: v_dual_mov_b32 v60, s45
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[8:15], v[17:24], v[34:41], v[0:7]
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[34:41], v[51:58], v[25:32], v[0:7]
; GCN-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[0:7], v[42:49], v[59:66], v[0:7]
; GCN-NEXT:    s_clause 0x5
; GCN-NEXT:    global_store_b128 v16, v[12:15], s[34:35] offset:16
; GCN-NEXT:    global_store_b128 v16, v[8:11], s[34:35]
; GCN-NEXT:    global_store_b128 v16, v[38:41], s[34:35] offset:48
; GCN-NEXT:    global_store_b128 v16, v[34:37], s[34:35] offset:32
; GCN-NEXT:    global_store_b128 v16, v[4:7], s[34:35] offset:80
; GCN-NEXT:    global_store_b128 v16, v[0:3], s[34:35] offset:64
; GCN-NEXT:    s_endpgm
  %pa0 = getelementptr <16 x half>, ptr addrspace(1) %pa, i64 0
  %a0 = load <16 x half>, ptr addrspace(1) %pa0
  %pb0 = getelementptr <16 x half>, ptr addrspace(1) %pb, i64 0
  %b0 = load <16 x half>, ptr addrspace(1) %pb0
  %c0 = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %a0, <16 x half> %b0, <8 x float> zeroinitializer)
  %pa1 = getelementptr <16 x half>, ptr addrspace(1) %pa, i64 1
  %a1 = load <16 x half>, ptr addrspace(1) %pa1
  %pb1 = getelementptr <16 x half>, ptr addrspace(1) %pb, i64 1
  %b1 = load <16 x half>, ptr addrspace(1) %pb1
  %c1 = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %a1, <16 x half> %b1, <8 x float> zeroinitializer)
  %pa2 = getelementptr <16 x half>, ptr addrspace(1) %pa, i64 2
  %a2 = load <16 x half>, ptr addrspace(1) %pa2
  %pb2 = getelementptr <16 x half>, ptr addrspace(1) %pb, i64 2
  %b2 = load <16 x half>, ptr addrspace(1) %pb2
  %c2 = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %a2, <16 x half> %b2, <8 x float> zeroinitializer)
  %po0 = getelementptr <8 x float>, ptr addrspace(1) %out, i64 0
  store <8 x float> %c0, ptr addrspace(1) %po0
  %po1 = getelementptr <8 x float>, ptr addrspace(1) %out, i64 1
  store <8 x float> %c1, ptr addrspace(1) %po1
  %po2 = getelementptr <8 x float>, ptr addrspace(1) %out, i64 2
  store <8 x float> %c2, ptr addrspace(1) %po2
  ret void
}

; Twelve independent WMMAs near the VGPR budget ("amdgpu-waves-per-eu"="10,10").
; This is the high-pressure stress case: the hint should separate banks on as
; many WMMAs as the per-bank region capacity allows without introducing spills.
define amdgpu_kernel void @wmma_f32_12x_pressure(ptr addrspace(1) %pa, ptr addrspace(1) %pb, ptr addrspace(1) %out) #2 {
; GCN-LABEL: wmma_f32_12x_pressure:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_load_b128 s[0:3], s[4:5], 0x0
; GCN-NEXT:    ; implicit-def: $vgpr65 : SGPR spill to VGPR lane
; GCN-NEXT:    s_mov_b32 s8, 0
; GCN-NEXT:    s_load_b64 s[4:5], s[4:5], 0x10
; GCN-NEXT:    s_mov_b32 s14, s8
; GCN-NEXT:    s_mov_b32 s9, s8
; GCN-NEXT:    s_mov_b32 s10, s8
; GCN-NEXT:    s_mov_b32 s11, s8
; GCN-NEXT:    s_mov_b32 s12, s8
; GCN-NEXT:    s_mov_b32 s13, s8
; GCN-NEXT:    s_mov_b32 s15, s8
; GCN-NEXT:    v_dual_mov_b32 v0, s8 :: v_dual_mov_b32 v3, s11
; GCN-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v1, s9
; GCN-NEXT:    v_dual_mov_b32 v2, s10 :: v_dual_mov_b32 v5, s13
; GCN-NEXT:    v_dual_mov_b32 v4, s12 :: v_dual_mov_b32 v7, s15
; GCN-NEXT:    s_waitcnt lgkmcnt(0)
; GCN-NEXT:    s_load_b256 s[68:75], s[0:1], 0x60
; GCN-NEXT:    s_load_b256 s[76:83], s[2:3], 0x60
; GCN-NEXT:    s_load_b256 s[84:91], s[0:1], 0x80
; GCN-NEXT:    s_clause 0x1
; GCN-NEXT:    s_load_b256 s[92:99], s[2:3], 0x80
; GCN-NEXT:    s_load_b256 s[16:23], s[2:3], 0x20
; GCN-NEXT:    s_load_b256 s[24:31], s[0:1], 0x0
; GCN-NEXT:    s_load_b256 s[44:51], s[2:3], 0x0
; GCN-NEXT:    v_mov_b32_e32 v6, s14
; GCN-NEXT:    s_clause 0x1
; GCN-NEXT:    s_load_b256 s[36:43], s[0:1], 0x20
; GCN-NEXT:    s_load_b256 s[52:59], s[0:1], 0x40
; GCN-NEXT:    s_load_b256 s[60:67], s[2:3], 0x40
; GCN-NEXT:    s_waitcnt lgkmcnt(0)
; GCN-NEXT:    v_dual_mov_b32 v49, s68 :: v_dual_mov_b32 v56, s75
; GCN-NEXT:    v_dual_mov_b32 v89, s83 :: v_dual_mov_b32 v122, s91
; GCN-NEXT:    v_mov_b32_e32 v119, s88
; GCN-NEXT:    v_writelane_b32 v65, s16, 0
; GCN-NEXT:    v_dual_mov_b32 v40, s31 :: v_dual_mov_b32 v37, s28
; GCN-NEXT:    v_dual_mov_b32 v39, s30 :: v_dual_mov_b32 v38, s29
; GCN-NEXT:    v_mov_b32_e32 v35, s26
; GCN-NEXT:    v_writelane_b32 v65, s17, 1
; GCN-NEXT:    v_dual_mov_b32 v36, s27 :: v_dual_mov_b32 v33, s24
; GCN-NEXT:    v_dual_mov_b32 v34, s25 :: v_dual_mov_b32 v73, s51
; GCN-NEXT:    v_writelane_b32 v65, s18, 2
; GCN-NEXT:    s_load_b256 s[24:31], s[0:1], 0xc0
; GCN-NEXT:    v_dual_mov_b32 v106, s43 :: v_dual_mov_b32 v103, s40
; GCN-NEXT:    v_dual_mov_b32 v66, s44 :: v_dual_mov_b32 v105, s42
; GCN-NEXT:    v_writelane_b32 v65, s19, 3
; GCN-NEXT:    v_dual_mov_b32 v104, s41 :: v_dual_mov_b32 v101, s38
; GCN-NEXT:    v_dual_mov_b32 v102, s39 :: v_dual_mov_b32 v99, s36
; GCN-NEXT:    v_writelane_b32 v65, s20, 4
; GCN-NEXT:    v_dual_mov_b32 v114, s67 :: v_dual_mov_b32 v111, s64
; GCN-NEXT:    v_dual_mov_b32 v72, s50 :: v_dual_mov_b32 v71, s49
; GCN-NEXT:    v_writelane_b32 v65, s21, 5
; GCN-NEXT:    v_dual_mov_b32 v70, s48 :: v_dual_mov_b32 v69, s47
; GCN-NEXT:    v_dual_mov_b32 v68, s46 :: v_dual_mov_b32 v67, s45
; GCN-NEXT:    v_writelane_b32 v65, s22, 6
; GCN-NEXT:    v_dual_mov_b32 v112, s65 :: v_dual_mov_b32 v109, s62
; GCN-NEXT:    v_dual_mov_b32 v110, s63 :: v_dual_mov_b32 v107, s60
; GCN-NEXT:    v_writelane_b32 v65, s23, 7
; GCN-NEXT:    s_load_b256 s[8:15], s[0:1], 0xa0
; GCN-NEXT:    s_load_b256 s[16:23], s[2:3], 0xa0
; GCN-NEXT:    v_mov_b32_e32 v108, s61
; GCN-NEXT:    v_dual_mov_b32 v116, s85 :: v_dual_mov_b32 v57, s92
; GCN-NEXT:    s_waitcnt lgkmcnt(0)
; GCN-NEXT:    v_writelane_b32 v65, s24, 8
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[123:130], v[33:40], v[66:73], v[0:7]
; GCN-NEXT:    v_dual_mov_b32 v50, s69 :: v_dual_mov_b32 v51, s70
; GCN-NEXT:    v_writelane_b32 v65, s25, 9
; GCN-NEXT:    v_dual_mov_b32 v52, s71 :: v_dual_mov_b32 v53, s72
; GCN-NEXT:    v_dual_mov_b32 v54, s73 :: v_dual_mov_b32 v55, s74
; GCN-NEXT:    v_writelane_b32 v65, s26, 10
; GCN-NEXT:    v_dual_mov_b32 v88, s82 :: v_dual_mov_b32 v87, s81
; GCN-NEXT:    v_dual_mov_b32 v86, s80 :: v_dual_mov_b32 v85, s79
; GCN-NEXT:    v_writelane_b32 v65, s27, 11
; GCN-NEXT:    v_dual_mov_b32 v84, s78 :: v_dual_mov_b32 v83, s77
; GCN-NEXT:    v_dual_mov_b32 v82, s76 :: v_dual_mov_b32 v121, s90
; GCN-NEXT:    v_writelane_b32 v65, s28, 12
; GCN-NEXT:    v_mov_b32_e32 v64, s99
; GCN-NEXT:    v_dual_mov_b32 v120, s89 :: v_dual_mov_b32 v117, s86
; GCN-NEXT:    v_dual_mov_b32 v118, s87 :: v_dual_mov_b32 v115, s84
; GCN-NEXT:    v_writelane_b32 v65, s29, 13
; GCN-NEXT:    v_dual_mov_b32 v58, s93 :: v_dual_mov_b32 v59, s94
; GCN-NEXT:    v_dual_mov_b32 v60, s95 :: v_dual_mov_b32 v61, s96
; GCN-NEXT:    v_writelane_b32 v65, s30, 14
; GCN-NEXT:    v_dual_mov_b32 v62, s97 :: v_dual_mov_b32 v63, s98
; GCN-NEXT:    v_dual_mov_b32 v81, s59 :: v_dual_mov_b32 v80, s58
; GCN-NEXT:    v_mov_b32_e32 v79, s57
; GCN-NEXT:    v_writelane_b32 v65, s31, 15
; GCN-NEXT:    s_load_b256 s[24:31], s[2:3], 0xc0
; GCN-NEXT:    v_dual_mov_b32 v78, s56 :: v_dual_mov_b32 v77, s55
; GCN-NEXT:    v_dual_mov_b32 v76, s54 :: v_dual_mov_b32 v75, s53
; GCN-NEXT:    v_dual_mov_b32 v74, s52 :: v_dual_mov_b32 v113, s66
; GCN-NEXT:    s_load_b256 s[52:59], s[0:1], 0x100
; GCN-NEXT:    s_load_b256 s[60:67], s[2:3], 0x100
; GCN-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[33:40], v[74:81], v[107:114], v[0:7]
; GCN-NEXT:    v_dual_mov_b32 v114, s23 :: v_dual_mov_b32 v111, s20
; GCN-NEXT:    v_dual_mov_b32 v113, s22 :: v_dual_mov_b32 v112, s21
; GCN-NEXT:    v_dual_mov_b32 v109, s18 :: v_dual_mov_b32 v110, s19
; GCN-NEXT:    v_mov_b32_e32 v107, s16
; GCN-NEXT:    s_waitcnt lgkmcnt(0)
; GCN-NEXT:    v_writelane_b32 v65, s24, 16
; GCN-NEXT:    v_writelane_b32 v65, s25, 17
; GCN-NEXT:    v_dual_mov_b32 v97, s67 :: v_dual_mov_b32 v96, s66
; GCN-NEXT:    v_mov_b32_e32 v95, s65
; GCN-NEXT:    v_writelane_b32 v65, s26, 18
; GCN-NEXT:    v_dual_mov_b32 v94, s64 :: v_dual_mov_b32 v93, s63
; GCN-NEXT:    v_dual_mov_b32 v92, s62 :: v_dual_mov_b32 v91, s61
; GCN-NEXT:    v_writelane_b32 v65, s27, 19
; GCN-NEXT:    v_writelane_b32 v65, s28, 20
; GCN-NEXT:    v_writelane_b32 v65, s29, 21
; GCN-NEXT:    v_writelane_b32 v65, s30, 22
; GCN-NEXT:    v_writelane_b32 v65, s31, 23
; GCN-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GCN-NEXT:    v_readlane_b32 s24, v65, 0
; GCN-NEXT:    v_readlane_b32 s31, v65, 7
; GCN-NEXT:    v_readlane_b32 s25, v65, 1
; GCN-NEXT:    v_readlane_b32 s26, v65, 2
; GCN-NEXT:    v_readlane_b32 s27, v65, 3
; GCN-NEXT:    v_readlane_b32 s28, v65, 4
; GCN-NEXT:    v_readlane_b32 s29, v65, 5
; GCN-NEXT:    v_readlane_b32 s30, v65, 6
; GCN-NEXT:    v_mov_b32_e32 v48, s31
; GCN-NEXT:    v_mov_b32_e32 v100, s37
; GCN-NEXT:    s_load_b256 s[36:43], s[0:1], 0xe0
; GCN-NEXT:    v_dual_mov_b32 v46, s29 :: v_dual_mov_b32 v43, s26
; GCN-NEXT:    v_mov_b32_e32 v47, s30
; GCN-NEXT:    v_dual_mov_b32 v45, s28 :: v_dual_mov_b32 v44, s27
; GCN-NEXT:    v_dual_mov_b32 v41, s24 :: v_dual_mov_b32 v42, s25
; GCN-NEXT:    s_load_b256 s[24:31], s[2:3], 0xe0
; GCN-NEXT:    v_readlane_b32 s44, v65, 8
; GCN-NEXT:    v_readlane_b32 s45, v65, 9
; GCN-NEXT:    v_readlane_b32 s46, v65, 10
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[66:73], v[99:106], v[41:48], v[0:7]
; GCN-NEXT:    v_dual_mov_b32 v48, s15 :: v_dual_mov_b32 v45, s12
; GCN-NEXT:    v_dual_mov_b32 v47, s14 :: v_dual_mov_b32 v46, s13
; GCN-NEXT:    v_dual_mov_b32 v43, s10 :: v_dual_mov_b32 v44, s11
; GCN-NEXT:    v_dual_mov_b32 v41, s8 :: v_dual_mov_b32 v42, s9
; GCN-NEXT:    v_readlane_b32 s47, v65, 11
; GCN-NEXT:    v_readlane_b32 s48, v65, 12
; GCN-NEXT:    v_readlane_b32 s49, v65, 13
; GCN-NEXT:    v_readlane_b32 s50, v65, 14
; GCN-NEXT:    v_readlane_b32 s51, v65, 15
; GCN-NEXT:    v_mov_b32_e32 v108, s17
; GCN-NEXT:    s_load_b256 s[8:15], s[0:1], 0x120
; GCN-NEXT:    s_load_b256 s[16:23], s[2:3], 0x120
; GCN-NEXT:    s_load_b256 s[68:75], s[0:1], 0x140
; GCN-NEXT:    s_load_b256 s[76:83], s[2:3], 0x140
; GCN-NEXT:    s_load_b256 s[84:91], s[0:1], 0x160
; GCN-NEXT:    s_load_b256 s[92:99], s[2:3], 0x160
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[99:106], v[49:56], v[82:89], v[0:7]
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[74:81], v[115:122], v[57:64], v[0:7]
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[82:89], v[41:48], v[107:114], v[0:7]
; GCN-NEXT:    v_dual_mov_b32 v41, s44 :: v_dual_mov_b32 v42, s45
; GCN-NEXT:    v_dual_mov_b32 v43, s46 :: v_dual_mov_b32 v44, s47
; GCN-NEXT:    v_dual_mov_b32 v45, s48 :: v_dual_mov_b32 v46, s49
; GCN-NEXT:    v_dual_mov_b32 v47, s50 :: v_dual_mov_b32 v48, s51
; GCN-NEXT:    v_readlane_b32 s44, v65, 16
; GCN-NEXT:    v_readlane_b32 s51, v65, 23
; GCN-NEXT:    v_readlane_b32 s45, v65, 17
; GCN-NEXT:    v_readlane_b32 s46, v65, 18
; GCN-NEXT:    v_readlane_b32 s47, v65, 19
; GCN-NEXT:    v_readlane_b32 s48, v65, 20
; GCN-NEXT:    v_readlane_b32 s49, v65, 21
; GCN-NEXT:    v_readlane_b32 s50, v65, 22
; GCN-NEXT:    v_mov_b32_e32 v114, s51
; GCN-NEXT:    s_waitcnt lgkmcnt(0)
; GCN-NEXT:    v_dual_mov_b32 v56, s43 :: v_dual_mov_b32 v53, s40
; GCN-NEXT:    v_dual_mov_b32 v122, s31 :: v_dual_mov_b32 v119, s28
; GCN-NEXT:    v_dual_mov_b32 v108, s45 :: v_dual_mov_b32 v55, s42
; GCN-NEXT:    v_dual_mov_b32 v54, s41 :: v_dual_mov_b32 v51, s38
; GCN-NEXT:    v_dual_mov_b32 v52, s39 :: v_dual_mov_b32 v49, s36
; GCN-NEXT:    v_dual_mov_b32 v50, s37 :: v_dual_mov_b32 v121, s30
; GCN-NEXT:    v_dual_mov_b32 v120, s29 :: v_dual_mov_b32 v117, s26
; GCN-NEXT:    v_dual_mov_b32 v118, s27 :: v_dual_mov_b32 v115, s24
; GCN-NEXT:    v_mov_b32_e32 v116, s25
; GCN-NEXT:    v_dual_mov_b32 v64, s59 :: v_dual_mov_b32 v61, s56
; GCN-NEXT:    v_dual_mov_b32 v113, s50 :: v_dual_mov_b32 v112, s49
; GCN-NEXT:    v_mov_b32_e32 v109, s46
; GCN-NEXT:    v_dual_mov_b32 v111, s48 :: v_dual_mov_b32 v110, s47
; GCN-NEXT:    v_dual_mov_b32 v107, s44 :: v_dual_mov_b32 v58, s53
; GCN-NEXT:    v_dual_mov_b32 v63, s58 :: v_dual_mov_b32 v62, s57
; GCN-NEXT:    v_dual_mov_b32 v59, s54 :: v_dual_mov_b32 v60, s55
; GCN-NEXT:    v_dual_mov_b32 v57, s52 :: v_dual_mov_b32 v90, s60
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[16:23], v[49:56], v[115:122], v[0:7]
; GCN-NEXT:    v_dual_mov_b32 v122, s23 :: v_dual_mov_b32 v119, s20
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[8:15], v[41:48], v[107:114], v[0:7]
; GCN-NEXT:    v_dual_mov_b32 v48, s15 :: v_dual_mov_b32 v45, s12
; GCN-NEXT:    v_dual_mov_b32 v116, s17 :: v_dual_mov_b32 v49, s68
; GCN-NEXT:    v_mov_b32_e32 v47, s14
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[107:114], v[57:64], v[90:97], v[0:7]
; GCN-NEXT:    v_dual_mov_b32 v56, s75 :: v_dual_mov_b32 v97, s83
; GCN-NEXT:    v_dual_mov_b32 v90, s76 :: v_dual_mov_b32 v57, s84
; GCN-NEXT:    v_dual_mov_b32 v24, s92 :: v_dual_mov_b32 v27, s95
; GCN-NEXT:    v_dual_mov_b32 v46, s13 :: v_dual_mov_b32 v43, s10
; GCN-NEXT:    v_dual_mov_b32 v44, s11 :: v_dual_mov_b32 v41, s8
; GCN-NEXT:    v_dual_mov_b32 v42, s9 :: v_dual_mov_b32 v121, s22
; GCN-NEXT:    v_dual_mov_b32 v120, s21 :: v_dual_mov_b32 v117, s18
; GCN-NEXT:    v_dual_mov_b32 v118, s19 :: v_dual_mov_b32 v115, s16
; GCN-NEXT:    v_dual_mov_b32 v50, s69 :: v_dual_mov_b32 v51, s70
; GCN-NEXT:    v_dual_mov_b32 v52, s71 :: v_dual_mov_b32 v53, s72
; GCN-NEXT:    v_dual_mov_b32 v54, s73 :: v_dual_mov_b32 v55, s74
; GCN-NEXT:    v_dual_mov_b32 v96, s82 :: v_dual_mov_b32 v95, s81
; GCN-NEXT:    v_dual_mov_b32 v94, s80 :: v_dual_mov_b32 v93, s79
; GCN-NEXT:    v_dual_mov_b32 v92, s78 :: v_dual_mov_b32 v91, s77
; GCN-NEXT:    v_dual_mov_b32 v58, s85 :: v_dual_mov_b32 v59, s86
; GCN-NEXT:    v_dual_mov_b32 v60, s87 :: v_dual_mov_b32 v61, s88
; GCN-NEXT:    v_dual_mov_b32 v62, s89 :: v_dual_mov_b32 v63, s90
; GCN-NEXT:    v_dual_mov_b32 v64, s91 :: v_dual_mov_b32 v25, s93
; GCN-NEXT:    v_dual_mov_b32 v26, s94 :: v_dual_mov_b32 v29, s97
; GCN-NEXT:    v_dual_mov_b32 v28, s96 :: v_dual_mov_b32 v31, s99
; GCN-NEXT:    v_mov_b32_e32 v30, s98
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[131:138], v[41:48], v[115:122], v[0:7]
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[115:122], v[49:56], v[90:97], v[0:7]
; GCN-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GCN-NEXT:    v_wmma_f32_16x16x16_f16 v[0:7], v[57:64], v[24:31], v[0:7]
; GCN-NEXT:    s_clause 0x17
; GCN-NEXT:    global_store_b128 v32, v[127:130], s[4:5] offset:16
; GCN-NEXT:    global_store_b128 v32, v[123:126], s[4:5]
; GCN-NEXT:    global_store_b128 v32, v[70:73], s[4:5] offset:48
; GCN-NEXT:    global_store_b128 v32, v[66:69], s[4:5] offset:32
; GCN-NEXT:    global_store_b128 v32, v[37:40], s[4:5] offset:80
; GCN-NEXT:    global_store_b128 v32, v[33:36], s[4:5] offset:64
; GCN-NEXT:    global_store_b128 v32, v[103:106], s[4:5] offset:112
; GCN-NEXT:    global_store_b128 v32, v[99:102], s[4:5] offset:96
; GCN-NEXT:    global_store_b128 v32, v[78:81], s[4:5] offset:144
; GCN-NEXT:    global_store_b128 v32, v[74:77], s[4:5] offset:128
; GCN-NEXT:    global_store_b128 v32, v[86:89], s[4:5] offset:176
; GCN-NEXT:    global_store_b128 v32, v[82:85], s[4:5] offset:160
; GCN-NEXT:    global_store_b128 v32, v[12:15], s[4:5] offset:208
; GCN-NEXT:    global_store_b128 v32, v[8:11], s[4:5] offset:192
; GCN-NEXT:    global_store_b128 v32, v[20:23], s[4:5] offset:240
; GCN-NEXT:    global_store_b128 v32, v[16:19], s[4:5] offset:224
; GCN-NEXT:    global_store_b128 v32, v[111:114], s[4:5] offset:272
; GCN-NEXT:    global_store_b128 v32, v[107:110], s[4:5] offset:256
; GCN-NEXT:    global_store_b128 v32, v[135:138], s[4:5] offset:304
; GCN-NEXT:    global_store_b128 v32, v[131:134], s[4:5] offset:288
; GCN-NEXT:    global_store_b128 v32, v[119:122], s[4:5] offset:336
; GCN-NEXT:    global_store_b128 v32, v[115:118], s[4:5] offset:320
; GCN-NEXT:    global_store_b128 v32, v[4:7], s[4:5] offset:368
; GCN-NEXT:    global_store_b128 v32, v[0:3], s[4:5] offset:352
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
; GCN-NEXT:    s_endpgm
  %pa0 = getelementptr <16 x half>, ptr addrspace(1) %pa, i64 0
  %a0 = load <16 x half>, ptr addrspace(1) %pa0
  %pb0 = getelementptr <16 x half>, ptr addrspace(1) %pb, i64 0
  %b0 = load <16 x half>, ptr addrspace(1) %pb0
  %c0 = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %a0, <16 x half> %b0, <8 x float> zeroinitializer)
  %pa1 = getelementptr <16 x half>, ptr addrspace(1) %pa, i64 1
  %a1 = load <16 x half>, ptr addrspace(1) %pa1
  %pb1 = getelementptr <16 x half>, ptr addrspace(1) %pb, i64 1
  %b1 = load <16 x half>, ptr addrspace(1) %pb1
  %c1 = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %a1, <16 x half> %b1, <8 x float> zeroinitializer)
  %pa2 = getelementptr <16 x half>, ptr addrspace(1) %pa, i64 2
  %a2 = load <16 x half>, ptr addrspace(1) %pa2
  %pb2 = getelementptr <16 x half>, ptr addrspace(1) %pb, i64 2
  %b2 = load <16 x half>, ptr addrspace(1) %pb2
  %c2 = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %a2, <16 x half> %b2, <8 x float> zeroinitializer)
  %pa3 = getelementptr <16 x half>, ptr addrspace(1) %pa, i64 3
  %a3 = load <16 x half>, ptr addrspace(1) %pa3
  %pb3 = getelementptr <16 x half>, ptr addrspace(1) %pb, i64 3
  %b3 = load <16 x half>, ptr addrspace(1) %pb3
  %c3 = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %a3, <16 x half> %b3, <8 x float> zeroinitializer)
  %pa4 = getelementptr <16 x half>, ptr addrspace(1) %pa, i64 4
  %a4 = load <16 x half>, ptr addrspace(1) %pa4
  %pb4 = getelementptr <16 x half>, ptr addrspace(1) %pb, i64 4
  %b4 = load <16 x half>, ptr addrspace(1) %pb4
  %c4 = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %a4, <16 x half> %b4, <8 x float> zeroinitializer)
  %pa5 = getelementptr <16 x half>, ptr addrspace(1) %pa, i64 5
  %a5 = load <16 x half>, ptr addrspace(1) %pa5
  %pb5 = getelementptr <16 x half>, ptr addrspace(1) %pb, i64 5
  %b5 = load <16 x half>, ptr addrspace(1) %pb5
  %c5 = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %a5, <16 x half> %b5, <8 x float> zeroinitializer)
  %pa6 = getelementptr <16 x half>, ptr addrspace(1) %pa, i64 6
  %a6 = load <16 x half>, ptr addrspace(1) %pa6
  %pb6 = getelementptr <16 x half>, ptr addrspace(1) %pb, i64 6
  %b6 = load <16 x half>, ptr addrspace(1) %pb6
  %c6 = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %a6, <16 x half> %b6, <8 x float> zeroinitializer)
  %pa7 = getelementptr <16 x half>, ptr addrspace(1) %pa, i64 7
  %a7 = load <16 x half>, ptr addrspace(1) %pa7
  %pb7 = getelementptr <16 x half>, ptr addrspace(1) %pb, i64 7
  %b7 = load <16 x half>, ptr addrspace(1) %pb7
  %c7 = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %a7, <16 x half> %b7, <8 x float> zeroinitializer)
  %pa8 = getelementptr <16 x half>, ptr addrspace(1) %pa, i64 8
  %a8 = load <16 x half>, ptr addrspace(1) %pa8
  %pb8 = getelementptr <16 x half>, ptr addrspace(1) %pb, i64 8
  %b8 = load <16 x half>, ptr addrspace(1) %pb8
  %c8 = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %a8, <16 x half> %b8, <8 x float> zeroinitializer)
  %pa9 = getelementptr <16 x half>, ptr addrspace(1) %pa, i64 9
  %a9 = load <16 x half>, ptr addrspace(1) %pa9
  %pb9 = getelementptr <16 x half>, ptr addrspace(1) %pb, i64 9
  %b9 = load <16 x half>, ptr addrspace(1) %pb9
  %c9 = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %a9, <16 x half> %b9, <8 x float> zeroinitializer)
  %pa10 = getelementptr <16 x half>, ptr addrspace(1) %pa, i64 10
  %a10 = load <16 x half>, ptr addrspace(1) %pa10
  %pb10 = getelementptr <16 x half>, ptr addrspace(1) %pb, i64 10
  %b10 = load <16 x half>, ptr addrspace(1) %pb10
  %c10 = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %a10, <16 x half> %b10, <8 x float> zeroinitializer)
  %pa11 = getelementptr <16 x half>, ptr addrspace(1) %pa, i64 11
  %a11 = load <16 x half>, ptr addrspace(1) %pa11
  %pb11 = getelementptr <16 x half>, ptr addrspace(1) %pb, i64 11
  %b11 = load <16 x half>, ptr addrspace(1) %pb11
  %c11 = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.v8f32.v16f16(<16 x half> %a11, <16 x half> %b11, <8 x float> zeroinitializer)
  %po0 = getelementptr <8 x float>, ptr addrspace(1) %out, i64 0
  store <8 x float> %c0, ptr addrspace(1) %po0
  %po1 = getelementptr <8 x float>, ptr addrspace(1) %out, i64 1
  store <8 x float> %c1, ptr addrspace(1) %po1
  %po2 = getelementptr <8 x float>, ptr addrspace(1) %out, i64 2
  store <8 x float> %c2, ptr addrspace(1) %po2
  %po3 = getelementptr <8 x float>, ptr addrspace(1) %out, i64 3
  store <8 x float> %c3, ptr addrspace(1) %po3
  %po4 = getelementptr <8 x float>, ptr addrspace(1) %out, i64 4
  store <8 x float> %c4, ptr addrspace(1) %po4
  %po5 = getelementptr <8 x float>, ptr addrspace(1) %out, i64 5
  store <8 x float> %c5, ptr addrspace(1) %po5
  %po6 = getelementptr <8 x float>, ptr addrspace(1) %out, i64 6
  store <8 x float> %c6, ptr addrspace(1) %po6
  %po7 = getelementptr <8 x float>, ptr addrspace(1) %out, i64 7
  store <8 x float> %c7, ptr addrspace(1) %po7
  %po8 = getelementptr <8 x float>, ptr addrspace(1) %out, i64 8
  store <8 x float> %c8, ptr addrspace(1) %po8
  %po9 = getelementptr <8 x float>, ptr addrspace(1) %out, i64 9
  store <8 x float> %c9, ptr addrspace(1) %po9
  %po10 = getelementptr <8 x float>, ptr addrspace(1) %out, i64 10
  store <8 x float> %c10, ptr addrspace(1) %po10
  %po11 = getelementptr <8 x float>, ptr addrspace(1) %out, i64 11
  store <8 x float> %c11, ptr addrspace(1) %po11
  ret void
}

attributes #1 = { "amdgpu-waves-per-eu"="256,256" }
attributes #2 = { "amdgpu-waves-per-eu"="10,10" }
