# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn -verify-machineinstrs --run-pass=postrapseudos -o - %s | FileCheck -check-prefix=GCN %s

# This testcase shows the necessity of removing the killed flag from the $sgpr source when
# creating a V_WRITELANE_B32.  The SI_SPILL_S32_TO_VGPR will be converted in postrapseudos from:
#
#   $X = SI_SPILL_S32_TO_VGPR killed $sgpr0, 6, $X, implicit-def $sgpr0_sgpr1
#
# to:
#
#   $X = V_WRITELANE_B32 $sgpr0, 6, $X(tied-def 0)
#
# The killed flag must be removed since $sgpr0 is no longer an implicit-def and
# will be subsequently used in the S_MOV_B64.

---
name:            non_uniform_loop
tracksRegLiveness: true
machineFunctionInfo:
  wwmReservedRegs:
    - '$vgpr63'
body:             |
  bb.0:
    liveins: $vgpr0
    ; GCN-LABEL: name: non_uniform_loop
    ; GCN: liveins: $vgpr0
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: $sgpr0 = V_READLANE_B32 $vgpr63, 2
    ; GCN-NEXT: $vgpr63 = V_WRITELANE_B32 undef $sgpr0, 6, $vgpr63
    ; GCN-NEXT: $exec = S_MOV_B64 killed renamable $sgpr0_sgpr1
    ; GCN-NEXT: S_ENDPGM 0
    $sgpr0 = SI_RESTORE_S32_FROM_VGPR $vgpr63, 2, implicit-def $sgpr0_sgpr1
    $vgpr63 = SI_SPILL_S32_TO_VGPR killed $sgpr0, 6, $vgpr63, implicit-def $sgpr0_sgpr1
    $exec = S_MOV_B64_term killed renamable $sgpr0_sgpr1
    S_ENDPGM 0
...

# This test shows the necessity of adding an undef flag to the $sgpr source when
# creating a V_WRITELANE_B32.
#
# The prologepilog creates:
#
#   $exec = S_MOV_B64 killed $sgpr4_sgpr5
#
# but $sgpr5 will be spilled by a:
#
#   $vgpr1 = SI_SPILL_S32_TO_VGPR $sgpr5, 1, killed $vgpr1(tied-def 0), implicit $sgpr4_sgpr5
#
# The SI_SPILL_S32_TO_VGPR will be converted in postrapseudos to:
#
#   $vgpr1 = V_WRITELANE_B32 undef $sgpr5, 1, killed $vgpr1(tied-def 0)
#
# The undef flag is necessary to satisfy the MachineVerifier since $sgpr5 is used after a kill.
# This testcase was derived from function bitcast_v32i16_to_v64i8_scalar in amdgcn.bitcast.512bit.ll.

---
name:            bitcast_v32i16_to_v64i8_scalar
tracksRegLiveness: true
machineFunctionInfo:
  scratchRSrcReg:  '$sgpr0_sgpr1_sgpr2_sgpr3'
  stackPtrOffsetReg: '$sgpr32'
  wwmReservedRegs:
    - '$vgpr62'
body:             |
  bb.0:
    ; GCN-LABEL: name: bitcast_v32i16_to_v64i8_scalar
    ; GCN: $sgpr4_sgpr5 = S_XOR_SAVEEXEC_B64 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    ; GCN-NEXT: $exec = S_MOV_B64 killed $sgpr4_sgpr5
    ; GCN-NEXT: renamable $sgpr4 = IMPLICIT_DEF
    ; GCN-NEXT: $vgpr62 = V_WRITELANE_B32 undef $sgpr5, 1, killed $vgpr62
    ; GCN-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31
    $sgpr4_sgpr5 = S_XOR_SAVEEXEC_B64 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    $exec = S_MOV_B64 killed $sgpr4_sgpr5
    renamable $sgpr4 = IMPLICIT_DEF
    $vgpr62 = SI_SPILL_S32_TO_VGPR $sgpr5, 1, killed $vgpr62, implicit $sgpr4_sgpr5
    SI_RETURN
...

