//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

_CLC_DEF _CLC_OVERLOAD _CLC_CONST int
__clc_sub_group_non_uniform_reduce_add(int x) {
  return __clc_sub_group_reduce_add(x);
}

_CLC_DEF _CLC_OVERLOAD _CLC_CONST uint
__clc_sub_group_non_uniform_reduce_add(uint x) {
  return __clc_sub_group_reduce_add(x);
}

_CLC_DEF _CLC_OVERLOAD _CLC_CONST int
__clc_sub_group_non_uniform_reduce_mul(int x) {
  return __clc_sub_group_reduce_mul(x);
}

_CLC_DEF _CLC_OVERLOAD _CLC_CONST uint
__clc_sub_group_non_uniform_reduce_mul(uint x) {
  return __clc_sub_group_reduce_mul(x);
}

_CLC_DEF _CLC_OVERLOAD _CLC_CONST int
__clc_sub_group_non_uniform_reduce_min(int x) {
  return __clc_sub_group_reduce_min(x);
}

_CLC_DEF _CLC_OVERLOAD _CLC_CONST uint
__clc_sub_group_non_uniform_reduce_min(uint x) {
  return __clc_sub_group_reduce_min(x);
}

_CLC_DEF _CLC_OVERLOAD _CLC_CONST int
__clc_sub_group_non_uniform_reduce_max(int x) {
  return __clc_sub_group_reduce_max(x);
}

_CLC_DEF _CLC_OVERLOAD _CLC_CONST uint
__clc_sub_group_non_uniform_reduce_max(uint x) {
  return __clc_sub_group_reduce_max(x);
}

_CLC_DEF _CLC_OVERLOAD _CLC_CONST long
__clc_sub_group_non_uniform_reduce_add(long x) {
  return __clc_sub_group_reduce_add(x);
}

_CLC_DEF _CLC_OVERLOAD _CLC_CONST ulong
__clc_sub_group_non_uniform_reduce_add(ulong x) {
  return __clc_sub_group_reduce_add(x);
}

_CLC_DEF _CLC_OVERLOAD _CLC_CONST long
__clc_sub_group_non_uniform_reduce_mul(long x) {
  return __clc_sub_group_reduce_mul(x);
}

_CLC_DEF _CLC_OVERLOAD _CLC_CONST ulong
__clc_sub_group_non_uniform_reduce_mul(ulong x) {
  return __clc_sub_group_reduce_mul(x);
}

_CLC_DEF _CLC_OVERLOAD _CLC_CONST long
__clc_sub_group_non_uniform_reduce_min(long x) {
  return __clc_sub_group_reduce_min(x);
}

_CLC_DEF _CLC_OVERLOAD _CLC_CONST ulong
__clc_sub_group_non_uniform_reduce_min(ulong x) {
  return __clc_sub_group_reduce_min(x);
}

_CLC_DEF _CLC_OVERLOAD _CLC_CONST long
__clc_sub_group_non_uniform_reduce_max(long x) {
  return __clc_sub_group_reduce_max(x);
}

_CLC_DEF _CLC_OVERLOAD _CLC_CONST ulong
__clc_sub_group_non_uniform_reduce_max(ulong x) {
  return __clc_sub_group_reduce_max(x);
}
