; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature
; RUN: opt < %s -passes=globalopt -S | FileCheck %s

declare token @llvm.call.preallocated.setup(i32)
declare i8* @llvm.call.preallocated.arg(token, i32)
declare i32 @__CxxFrameHandler3(...)

; Don't touch functions with any musttail calls
define internal i32 @preallocated_musttail(i32* preallocated(i32) %p) {
; CHECK-LABEL: define {{[^@]+}}@preallocated_musttail
; CHECK-SAME: (i32* preallocated(i32) [[P:%.*]]) unnamed_addr {
; CHECK-NEXT:    [[RV:%.*]] = load i32, i32* [[P]], align 4
; CHECK-NEXT:    ret i32 [[RV]]
;
  %rv = load i32, i32* %p
  ret i32 %rv
}

define i32 @call_preallocated_musttail(i32* preallocated(i32) %a) {
; CHECK-LABEL: define {{[^@]+}}@call_preallocated_musttail
; CHECK-SAME: (i32* preallocated(i32) [[A:%.*]]) local_unnamed_addr {
; CHECK-NEXT:    [[R:%.*]] = musttail call i32 @preallocated_musttail(i32* preallocated(i32) [[A]])
; CHECK-NEXT:    ret i32 [[R]]
;
  %r = musttail call i32 @preallocated_musttail(i32* preallocated(i32) %a)
  ret i32 %r
}

define i32 @call_preallocated_musttail_without_musttail() {
; CHECK-LABEL: define {{[^@]+}}@call_preallocated_musttail_without_musttail() local_unnamed_addr {
; CHECK-NEXT:    [[C:%.*]] = call token @llvm.call.preallocated.setup(i32 1)
; CHECK-NEXT:    [[N:%.*]] = call i8* @llvm.call.preallocated.arg(token [[C]], i32 0) #[[ATTR1:[0-9]+]]
; CHECK-NEXT:    [[N2:%.*]] = bitcast i8* [[N]] to i32*
; CHECK-NEXT:    [[R:%.*]] = call i32 @preallocated_musttail(i32* preallocated(i32) [[N2]]) [ "preallocated"(token [[C]]) ]
; CHECK-NEXT:    ret i32 [[R]]
;
  %c = call token @llvm.call.preallocated.setup(i32 1)
  %N = call i8* @llvm.call.preallocated.arg(token %c, i32 0) preallocated(i32)
  %N2 = bitcast i8* %N to i32*
  %r = call i32 @preallocated_musttail(i32* preallocated(i32) %N2) ["preallocated"(token %c)]
  ret i32 %r
}

; Check that only one alloca per preallocated arg
define internal i32 @preallocated(i32* preallocated(i32) %a) {
; CHECK-LABEL: define {{[^@]+}}@preallocated
; CHECK-SAME: (i32* [[A:%.*]]) unnamed_addr {
; CHECK-NEXT:    [[RV:%.*]] = load i32, i32* [[A]], align 4
; CHECK-NEXT:    ret i32 [[RV]]
;
  %rv = load i32, i32* %a
  ret i32 %rv
}

declare void @foo(i8*)

define i32 @call_preallocated_multiple_args() {
; CHECK-LABEL: define {{[^@]+}}@call_preallocated_multiple_args() local_unnamed_addr {
; CHECK-NEXT:    [[TMP1:%.*]] = call i8* @llvm.stacksave()
; CHECK-NEXT:    [[PAARG:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[A32:%.*]] = bitcast i32* [[PAARG]] to i8*
; CHECK-NEXT:    call void @foo(i8* [[A32]])
; CHECK-NEXT:    call void @foo(i8* [[A32]])
; CHECK-NEXT:    call void @foo(i8* [[A32]])
; CHECK-NEXT:    [[B:%.*]] = bitcast i8* [[A32]] to i32*
; CHECK-NEXT:    [[R:%.*]] = call fastcc i32 @preallocated(i32* [[B]])
; CHECK-NEXT:    call void @llvm.stackrestore(i8* [[TMP1]])
; CHECK-NEXT:    ret i32 [[R]]
;
  %c = call token @llvm.call.preallocated.setup(i32 1)
  %a1 = call i8* @llvm.call.preallocated.arg(token %c, i32 0) preallocated(i32)
  call void @foo(i8* %a1)
  %a2 = call i8* @llvm.call.preallocated.arg(token %c, i32 0) preallocated(i32)
  call void @foo(i8* %a2)
  %a3 = call i8* @llvm.call.preallocated.arg(token %c, i32 0) preallocated(i32)
  call void @foo(i8* %a3)
  %b = bitcast i8* %a3 to i32*
  %r = call i32 @preallocated(i32* preallocated(i32) %b) ["preallocated"(token %c)]
  ret i32 %r
}

; Don't touch functions with any invokes
define internal i32 @preallocated_invoke(i32* preallocated(i32) %p) {
; CHECK-LABEL: define {{[^@]+}}@preallocated_invoke
; CHECK-SAME: (i32* preallocated(i32) [[P:%.*]]) unnamed_addr {
; CHECK-NEXT:    [[RV:%.*]] = load i32, i32* [[P]], align 4
; CHECK-NEXT:    ret i32 [[RV]]
;
  %rv = load i32, i32* %p
  ret i32 %rv
}

define i32 @call_preallocated_invoke() personality i8* bitcast (i32 (...)* @__CxxFrameHandler3 to i8*) {
; CHECK-LABEL: define {{[^@]+}}@call_preallocated_invoke() local_unnamed_addr personality i8* bitcast (i32 (...)* @__CxxFrameHandler3 to i8*) {
; CHECK-NEXT:    [[C:%.*]] = call token @llvm.call.preallocated.setup(i32 1)
; CHECK-NEXT:    [[A:%.*]] = call i8* @llvm.call.preallocated.arg(token [[C]], i32 0) #[[ATTR1]]
; CHECK-NEXT:    [[B:%.*]] = bitcast i8* [[A]] to i32*
; CHECK-NEXT:    [[R:%.*]] = invoke i32 @preallocated_invoke(i32* preallocated(i32) [[B]]) [ "preallocated"(token [[C]]) ]
; CHECK-NEXT:    to label [[CONTA:%.*]] unwind label [[CONTB:%.*]]
; CHECK:       conta:
; CHECK-NEXT:    ret i32 [[R]]
; CHECK:       contb:
; CHECK-NEXT:    [[S:%.*]] = catchswitch within none [label %catch] unwind to caller
; CHECK:       catch:
; CHECK-NEXT:    [[P:%.*]] = catchpad within [[S]] []
; CHECK-NEXT:    catchret from [[P]] to label [[CONT:%.*]]
; CHECK:       cont:
; CHECK-NEXT:    ret i32 42
;
  %c = call token @llvm.call.preallocated.setup(i32 1)
  %a = call i8* @llvm.call.preallocated.arg(token %c, i32 0) preallocated(i32)
  %b = bitcast i8* %a to i32*
  %r = invoke i32 @preallocated_invoke(i32* preallocated(i32) %b) ["preallocated"(token %c)]
  to label %conta unwind label %contb
conta:
  ret i32 %r
contb:
  %s = catchswitch within none [label %catch] unwind to caller
catch:
  %p = catchpad within %s []
  catchret from %p to label %cont
cont:
  ret i32 42
}
