# Expects target triple to be passed as `ARCH_TRIPLE`

set(CMAKE_SYSTEM_NAME Generic CACHE STRING "")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY CACHE STRING "")
set(LLVM_ENABLE_RUNTIMES "libc" CACHE STRING "")
set(LLVM_INCLUDE_TESTS OFF CACHE BOOL "")
set(CMAKE_C_COMPILER_WORKS ON CACHE BOOL "")
set(CMAKE_CXX_COMPILER_WORKS ON CACHE BOOL "")
set(CMAKE_SYSROOT "" CACHE STRING "")

set(CMAKE_C_COMPILER_TARGET ${ARCH_TRIPLE} CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET ${ARCH_TRIPLE} CACHE STRING "")
set(CMAKE_ASM_COMPILER_TARGET ${ARCH_TRIPLE} CACHE STRING "")
set(LLVM_DEFAULT_TARGET_TRIPLE ${ARCH_TRIPLE} CACHE STRING "")
set(LIBC_TARGET_TRIPLE ${ARCH_TRIPLE} CACHE STRING "")

set(LLVM_LIBC_FULL_BUILD "ON" CACHE BOOL "")
