; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -aa-pipeline=basic-aa -passes='require<aa>,require<target-ir>,loop-mssa(licm)' < %s -S | FileCheck %s

;; It should hoist fn_write_inaccessible_mem
;; because there is no conflict between inaccessible memory and argmem
define dso_local i32 @hoist_inaccessible_with_argmem(i32 %x, ptr %a, ptr %b) #0 {
; CHECK-LABEL: define dso_local i32 @hoist_inaccessible_with_argmem(
; CHECK-SAME: i32 [[X:%.*]], ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[VAL:%.*]] = getelementptr inbounds nuw i32, ptr [[A]], i64 1
; CHECK-NEXT:    call void @fn_write_inaccessible_mem()
; CHECK-NEXT:    call void @fn_read_inaccessible_mem()
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi ptr [ [[GEP:%.*]], %[[LOOP]] ], [ [[VAL]], %[[ENTRY]] ]
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr i8, ptr [[PHI]], i64 0
; CHECK-NEXT:    [[VAL2:%.*]] = call i32 @fn_args(ptr [[GEP2]])
; CHECK-NEXT:    [[GEP]] = getelementptr inbounds nuw i32, ptr [[PHI]], i64 0
; CHECK-NEXT:    [[ACC:%.*]] = add nuw nsw i32 [[VAL2]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[ACC]], 10
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[AFTER_LOOP:.*]]
; CHECK:       [[AFTER_LOOP]]:
; CHECK-NEXT:    [[ACC_LCSSA:%.*]] = phi i32 [ [[ACC]], %[[LOOP]] ]
; CHECK-NEXT:    ret i32 [[ACC_LCSSA]]
;
entry:
  %val = getelementptr inbounds nuw i32, ptr %a, i64 1
  br label %loop
loop:
  %phi = phi ptr [ %gep, %loop ], [ %val, %entry ]
  %44 = load i32, ptr %phi, align 16
  %gep2 = getelementptr i8, ptr %phi, i64 0
  %val2 = call i32 @fn_args(ptr  %gep2)
  call void @fn_write_inaccessible_mem()
  call void @fn_read_inaccessible_mem()
  %gep = getelementptr inbounds nuw i32, ptr %phi, i64 0
  %acc = add nuw nsw i32 %val2, 1
  %cmp = icmp ult i32 %acc, 10
  br i1 %cmp, label %loop, label %after_loop
after_loop:
  ret i32 %acc
}

declare i32  @fn_args(ptr) nounwind willreturn
memory(argmem: read)

;; It should NOT hoist fn_write_inaccessible_mem
;; Because fn_args_2 reads inaccessible memory
define dso_local i32 @no_hoist_inaccessible_conflict(i32 %x, ptr %a, ptr %b) #0 {
; CHECK-LABEL: define dso_local i32 @no_hoist_inaccessible_conflict(
; CHECK-SAME: i32 [[X:%.*]], ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[VAL:%.*]] = getelementptr inbounds nuw i32, ptr [[A]], i64 1
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi ptr [ [[GEP:%.*]], %[[LOOP]] ], [ [[VAL]], %[[ENTRY]] ]
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr i8, ptr [[PHI]], i64 0
; CHECK-NEXT:    [[VAL2:%.*]] = call i32 @fn_args_2(ptr [[GEP2]])
; CHECK-NEXT:    call void @fn_write_inaccessible_mem()
; CHECK-NEXT:    call void @fn_read_inaccessible_mem()
; CHECK-NEXT:    [[GEP]] = getelementptr inbounds nuw i32, ptr [[PHI]], i64 0
; CHECK-NEXT:    [[ACC:%.*]] = add nuw nsw i32 [[VAL2]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[ACC]], 10
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[AFTER_LOOP:.*]]
; CHECK:       [[AFTER_LOOP]]:
; CHECK-NEXT:    [[ACC_LCSSA:%.*]] = phi i32 [ [[ACC]], %[[LOOP]] ]
; CHECK-NEXT:    ret i32 [[ACC_LCSSA]]
;
entry:
  %val = getelementptr inbounds nuw i32, ptr %a, i64 1
  br label %loop
loop:
  %phi = phi ptr [ %gep, %loop ], [ %val, %entry ]
  %44 = load i32, ptr %phi, align 16
  %gep2 = getelementptr i8, ptr %phi, i64 0
  %val2 = call i32 @fn_args_2(ptr  %gep2)
  call void @fn_write_inaccessible_mem()
  call void @fn_read_inaccessible_mem()
  %gep = getelementptr inbounds nuw i32, ptr %phi, i64 0
  %acc = add nuw nsw i32 %val2, 1
  %cmp = icmp ult i32 %acc, 10
  br i1 %cmp, label %loop, label %after_loop
after_loop:
  ret i32 %acc
}
declare i32  @fn_args_2(ptr) nounwind willreturn
memory(inaccessiblemem:read)

;; Should hoist fn_write_inaccessible_mem
;; It does not alias with store to noalias ptr
define void @hoist_inaccessible_with_store(ptr noalias %loc, ptr noalias %loc2){
; CHECK-LABEL: define void @hoist_inaccessible_with_store(
; CHECK-SAME: ptr noalias [[LOC:%.*]], ptr noalias [[LOC2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[LOC2]], align 4
; CHECK-NEXT:    store i32 [[VAL]], ptr [[LOC]], align 4
; CHECK-NEXT:    call void @fn_write_inaccessible_mem()
; CHECK-NEXT:    call void @fn_read_inaccessible_mem()
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*:]]
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    br label %[[FOR_BODY]]
;
entry:
  br label %for.body
for.cond.cleanup:
  ret void
for.body:
  %val = load i32, ptr %loc2
  store i32 %val, ptr %loc
  call void @fn_write_inaccessible_mem()
  call void @fn_read_inaccessible_mem()
  br label %for.body
}

;; Should NOT hoist fn_write_inaccessible_mem
;; because fn_read_inaccessible_mem reads the same memory location
define void @no_hoist_inaccessible_read_conflict(ptr noalias %loc, ptr noalias %loc2){
; CHECK-LABEL: define void @no_hoist_inaccessible_read_conflict(
; CHECK-SAME: ptr noalias [[LOC:%.*]], ptr noalias [[LOC2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[LOC2]], align 4
; CHECK-NEXT:    store i32 [[VAL]], ptr [[LOC]], align 4
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    call void @fn_read_inaccessible_mem()
; CHECK-NEXT:    call void @fn_write_inaccessible_mem()
; CHECK-NEXT:    call void @fn_read_inaccessible_mem()
; CHECK-NEXT:    br label %[[FOR_BODY]]
;
entry:
  br label %for.body
for.body:
  %val = load i32, ptr %loc2
  store i32 %val, ptr %loc
  call void @fn_read_inaccessible_mem()
  call void @fn_write_inaccessible_mem()
  call void @fn_read_inaccessible_mem()
  br label %for.body
}

;; Nothing should be hoisted from the loop because volatile
define void @no_hoist_volatile(ptr %loc, ptr %loc2) {
; CHECK-LABEL: define void @no_hoist_volatile(
; CHECK-SAME: ptr [[LOC:%.*]], ptr [[LOC2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    store volatile i32 0, ptr [[LOC]], align 4
; CHECK-NEXT:    call void @fn_write_inaccessible_mem()
; CHECK-NEXT:    call void @fn_read_inaccessible_mem()
; CHECK-NEXT:    br label %[[LOOP]]
;
entry:
  br label %loop
loop:
  %val = load i32, ptr %loc2
  store volatile i32 0, ptr %loc
  call void @fn_write_inaccessible_mem()
  call void @fn_read_inaccessible_mem()
  br label %loop
}

;; Should hoist FPMR write (inaccessible mem) past unrelated vector load
define void @hoist_inaccessible_past_load(ptr %p, ptr %q) #0 {
; CHECK-LABEL: define void @hoist_inaccessible_past_load(
; CHECK-SAME: ptr [[P:%.*]], ptr [[Q:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    call void @fn_write_inaccessible_mem()
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr i8, ptr [[P]], i32 [[IV]]
; CHECK-NEXT:    [[LD:%.*]] = load <16 x i8>, ptr [[ADD_PTR]], align 1
; CHECK-NEXT:    call void @use_vec(<16 x i8> [[LD]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 16
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[IV]], 1024
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %add.ptr = getelementptr i8, ptr %p, i32 %iv
  %ld = load <16 x i8>, ptr %add.ptr, align 1
  call void @fn_write_inaccessible_mem()
  call void @use_vec(<16 x i8> %ld)
  %iv.next = add i32 %iv, 16
  %cmp = icmp slt i32 %iv, 1024
  br i1 %cmp, label %loop, label %exit
exit:
  ret void
}

declare void @fn_write_inaccessible_mem()#0
  memory(inaccessiblemem:  write)

declare void @fn_read_inaccessible_mem()#0
  memory(inaccessiblemem: read)

declare void @use_vec(<16 x i8>) #0
  memory(argmem: read)

attributes #0 = { mustprogress nofree norecurse nosync nounwind}
