; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=licm -licm-hoist-bo-association-user-limit=0 < %s | FileCheck %s --check-prefix=LIMIT0
; RUN: opt -S -passes=licm -licm-hoist-bo-association-user-limit=1 < %s | FileCheck %s --check-prefix=LIMIT1
; RUN: opt -S -passes=licm -licm-hoist-bo-association-user-limit=2 < %s | FileCheck %s --check-prefix=LIMIT2

; Hoisted if the limit is at least 1.
define void @single_use(i64 %c1, i64 %c2) {
; LIMIT0-LABEL: @single_use(
; LIMIT0-NEXT:  entry:
; LIMIT0-NEXT:    br label [[LOOP:%.*]]
; LIMIT0:       loop:
; LIMIT0-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT:%.*]], [[LOOP]] ]
; LIMIT0-NEXT:    [[STEP_ADD:%.*]] = add i64 [[INDEX]], [[C1:%.*]]
; LIMIT0-NEXT:    [[INDEX_NEXT]] = add i64 [[STEP_ADD]], [[C2:%.*]]
; LIMIT0-NEXT:    br label [[LOOP]]
;
; LIMIT1-LABEL: @single_use(
; LIMIT1-NEXT:  entry:
; LIMIT1-NEXT:    [[INVARIANT_OP:%.*]] = add i64 [[C1:%.*]], [[C2:%.*]]
; LIMIT1-NEXT:    br label [[LOOP:%.*]]
; LIMIT1:       loop:
; LIMIT1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT_REASS:%.*]], [[LOOP]] ]
; LIMIT1-NEXT:    [[INDEX_NEXT_REASS]] = add i64 [[INDEX]], [[INVARIANT_OP]]
; LIMIT1-NEXT:    br label [[LOOP]]
;
; LIMIT2-LABEL: @single_use(
; LIMIT2-NEXT:  entry:
; LIMIT2-NEXT:    [[INVARIANT_OP:%.*]] = add i64 [[C1:%.*]], [[C2:%.*]]
; LIMIT2-NEXT:    br label [[LOOP:%.*]]
; LIMIT2:       loop:
; LIMIT2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT_REASS:%.*]], [[LOOP]] ]
; LIMIT2-NEXT:    [[INDEX_NEXT_REASS]] = add i64 [[INDEX]], [[INVARIANT_OP]]
; LIMIT2-NEXT:    br label [[LOOP]]
;
entry:
  br label %loop

loop:
  %index = phi i64 [ 0, %entry ], [ %index.next, %loop ]
  %step.add = add i64 %index, %c1
  %index.next = add i64 %step.add, %c2
  br label %loop
}

; Hoisted if the limit is at least 2.
define void @two_uses(i64 %c1, i64 %c2) {
; LIMIT0-LABEL: @two_uses(
; LIMIT0-NEXT:  entry:
; LIMIT0-NEXT:    br label [[LOOP:%.*]]
; LIMIT0:       loop:
; LIMIT0-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT:%.*]], [[LOOP]] ]
; LIMIT0-NEXT:    [[STEP_ADD:%.*]] = add i64 [[INDEX]], [[C1:%.*]]
; LIMIT0-NEXT:    call void @use(i64 [[STEP_ADD]])
; LIMIT0-NEXT:    [[INDEX_NEXT]] = add i64 [[STEP_ADD]], [[C2:%.*]]
; LIMIT0-NEXT:    br label [[LOOP]]
;
; LIMIT1-LABEL: @two_uses(
; LIMIT1-NEXT:  entry:
; LIMIT1-NEXT:    br label [[LOOP:%.*]]
; LIMIT1:       loop:
; LIMIT1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT_REASS:%.*]], [[LOOP]] ]
; LIMIT1-NEXT:    [[STEP_ADD:%.*]] = add i64 [[INDEX]], [[C1:%.*]]
; LIMIT1-NEXT:    call void @use(i64 [[STEP_ADD]])
; LIMIT1-NEXT:    [[INDEX_NEXT_REASS]] = add i64 [[STEP_ADD]], [[C2:%.*]]
; LIMIT1-NEXT:    br label [[LOOP]]
;
; LIMIT2-LABEL: @two_uses(
; LIMIT2-NEXT:  entry:
; LIMIT2-NEXT:    [[INVARIANT_OP:%.*]] = add i64 [[C1:%.*]], [[C2:%.*]]
; LIMIT2-NEXT:    br label [[LOOP:%.*]]
; LIMIT2:       loop:
; LIMIT2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT_REASS:%.*]], [[LOOP]] ]
; LIMIT2-NEXT:    [[STEP_ADD:%.*]] = add i64 [[INDEX]], [[C1]]
; LIMIT2-NEXT:    call void @use(i64 [[STEP_ADD]])
; LIMIT2-NEXT:    [[INDEX_NEXT_REASS]] = add i64 [[INDEX]], [[INVARIANT_OP]]
; LIMIT2-NEXT:    br label [[LOOP]]
;
entry:
  br label %loop

loop:
  %index = phi i64 [ 0, %entry ], [ %index.next, %loop ]
  %step.add = add i64 %index, %c1
  call void @use(i64 %step.add)
  %index.next = add i64 %step.add, %c2
  br label %loop
}


declare void @use()
