; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='loop-mssa(licm)' -S %s | FileCheck %s
;
; Test that LICM can hoist an FPMR write (inaccessible memory) past
; unrelated vector loads in a loop.
;
; Reduced from:
;   float16x8_t test(const uint8_t *A, const uint8_t *B, int N) {
;     fpm_t fpm = __arm_fpm_init();
;     fpm = __arm_set_fpm_src1_format(fpm, __ARM_FPM_E5M2);
;     fpm = __arm_set_fpm_src2_format(fpm, __ARM_FPM_E5M2);
;     fpm = __arm_set_fpm_lscale2(fpm, 5);
;     float16x8_t acc = vdupq_n_f16(0.0f);
;     for (int i = 0; i < 1024; i += 16) {
;       mfloat8x16_t za = vreinterpretq_mf8_u8(vld1q_u8(A + i));
;       mfloat8x8_t  zb = vreinterpret_mf8_u8(vld1_u8(B + i));
;       acc = vdotq_lane_f16_mf8_fpm(acc, za, zb, 0, fpm);
;     }
;     return acc;
;   }

define <8 x half> @fpmr_hoist(ptr readonly %A, ptr readonly %B) {
; CHECK-LABEL: define <8 x half> @fpmr_hoist(
; CHECK-SAME: ptr readonly [[A:%.*]], ptr readonly [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    call void @llvm.aarch64.set.fpmr(i64 21474836480)
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi <8 x half> [ zeroinitializer, %[[ENTRY]] ], [ [[DOT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[PA:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 [[IV]]
; CHECK-NEXT:    [[LDA:%.*]] = load <16 x i8>, ptr [[PA]], align 1
; CHECK-NEXT:    [[PB:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 [[IV]]
; CHECK-NEXT:    [[LDB:%.*]] = load <8 x i8>, ptr [[PB]], align 1
; CHECK-NEXT:    [[WIDE:%.*]] = shufflevector <8 x i8> [[LDB]], <8 x i8> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[DOT]] = call <8 x half> @llvm.aarch64.neon.fp8.fdot2.lane.v8f16.v16i8(<8 x half> [[ACC]], <16 x i8> [[LDA]], <16 x i8> [[WIDE]], i32 0)
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 16
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[IV]], 1008
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[DOT_LCSSA:%.*]] = phi <8 x half> [ [[DOT]], %[[LOOP]] ]
; CHECK-NEXT:    ret <8 x half> [[DOT_LCSSA]]
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %acc = phi <8 x half> [ zeroinitializer, %entry ], [ %dot, %loop ]
  %pA = getelementptr inbounds i8, ptr %A, i64 %iv
  %ldA = load <16 x i8>, ptr %pA, align 1
  %pB = getelementptr inbounds i8, ptr %B, i64 %iv
  %ldB = load <8 x i8>, ptr %pB, align 1
  %wide = shufflevector <8 x i8> %ldB, <8 x i8> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  call void @llvm.aarch64.set.fpmr(i64 21474836480)
  %dot = call <8 x half> @llvm.aarch64.neon.fp8.fdot2.lane.v8f16.v16i8(<8 x half> %acc, <16 x i8> %ldA, <16 x i8> %wide, i32 0)
  %iv.next = add nuw nsw i64 %iv, 16
  %cmp = icmp ult i64 %iv, 1008
  br i1 %cmp, label %loop, label %exit

exit:
  ret <8 x half> %dot
}

declare void @llvm.aarch64.set.fpmr(i64) #0
declare <8 x half> @llvm.aarch64.neon.fp8.fdot2.lane.v8f16.v16i8(<8 x half>, <16 x i8>, <16 x i8>, i32 immarg) #1

attributes #0 = { mustprogress nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write) }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) }
