; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes='loop-mssa(licm)' -S %s | FileCheck %s

; Check that NSW/NUW flags are correctly dropped after reassociation

define void @test(i32 %a) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i32 [[A:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[VAL:%.*]] = phi i32 [ 1, [[LOOP]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = or i32 [[VAL]], [[A]]
; CHECK-NEXT:    [[TMP1:%.*]] = mul i32 [[TMP0]], -589824
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 null(i32 [[TMP1]])
; CHECK-NEXT:    br label [[LOOP]]
;
entry:
  br label %loop

loop:                              ; preds = %loop, %entry
  %val = phi i32 [ 1, %loop ], [ 0, %entry ]
  %0 = or i32 %val, %a
  %1 = mul nuw i32 %0, 65536
  %sext = mul nsw i32 %1, -9
  %2 = call i32 null(i32 %sext)
  br label %loop
}

