; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=licm -S < %s | FileCheck %s

; Base positive case
define <4 x i32> @hoist_simple_swap(ptr %base, <4 x i32> %inv, i32 %n) {
; CHECK-LABEL: define <4 x i32> @hoist_simple_swap(
; CHECK-SAME: ptr [[BASE:%.*]], <4 x i32> [[INV:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VARIANT:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x i32> poison, i32 [[VARIANT]], i32 0
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[INS]], <4 x i32> [[INV]], <4 x i32> <i32 0, i32 5, i32 6, i32 7>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %variant = load i32, ptr %idx, align 4
  %ins = insertelement <4 x i32> poison, i32 %variant, i32 0
  %res = shufflevector <4 x i32> %ins, <4 x i32> %inv, <4 x i32> <i32 0, i32 5, i32 6, i32 7>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test moving multiple shuffles past an insert
define <4 x i32> @hoist_multiple_shuffles_past_insert(ptr %base, <4 x i32> %inv0, <4 x i32> %inv1, i32 %n) {
; CHECK-LABEL: define <4 x i32> @hoist_multiple_shuffles_past_insert(
; CHECK-SAME: ptr [[BASE:%.*]], <4 x i32> [[INV0:%.*]], <4 x i32> [[INV1:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VARIANT:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x i32> poison, i32 [[VARIANT]], i32 0
; CHECK-NEXT:    [[S0:%.*]] = shufflevector <4 x i32> [[INS]], <4 x i32> [[INV0]], <4 x i32> <i32 0, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[S0]], <4 x i32> [[INV1]], <4 x i32> <i32 0, i32 1, i32 4, i32 7>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %variant = load i32, ptr %idx, align 4
  %ins = insertelement <4 x i32> poison, i32 %variant, i32 0
  %s0 = shufflevector <4 x i32> %ins, <4 x i32> %inv0, <4 x i32> <i32 0, i32 5, i32 6, i32 7>
  %res = shufflevector <4 x i32> %s0, <4 x i32> %inv1, <4 x i32> <i32 0, i32 1, i32 4, i32 7>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test moving a shuffle past multiple inserts
define <4 x i32> @hoist_shuffle_past_multiple_inserts(ptr %base, <4 x i32> %inv, i32 %n) {
; CHECK-LABEL: define <4 x i32> @hoist_shuffle_past_multiple_inserts(
; CHECK-SAME: ptr [[BASE:%.*]], <4 x i32> [[INV:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VARIANT:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[I0:%.*]] = insertelement <4 x i32> poison, i32 [[VARIANT]], i32 0
; CHECK-NEXT:    [[I1:%.*]] = insertelement <4 x i32> [[I0]], i32 [[VARIANT]], i32 1
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[I1]], <4 x i32> [[INV]], <4 x i32> <i32 0, i32 1, i32 6, i32 4>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %variant = load i32, ptr %idx, align 4
  %i0 = insertelement <4 x i32> poison, i32 %variant, i32 0
  %i1 = insertelement <4 x i32> %i0, i32 %variant, i32 1
  %res = shufflevector <4 x i32> %i1, <4 x i32> %inv, <4 x i32> <i32 0, i32 1, i32 6, i32 4>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test moving a shuffle of a non-invariant vector
define <4 x i32> @no_hoist_shuffle_non_invariant_rhs(ptr %base, ptr %rhs, i32 %n) {
; CHECK-LABEL: define <4 x i32> @no_hoist_shuffle_non_invariant_rhs(
; CHECK-SAME: ptr [[BASE:%.*]], ptr [[RHS:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VARIANT:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[VARIANT_VEC:%.*]] = load <4 x i32>, ptr [[IDX]], align 16
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x i32> poison, i32 [[VARIANT]], i32 0
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[INS]], <4 x i32> [[VARIANT_VEC]], <4 x i32> <i32 0, i32 5, i32 6, i32 7>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %variant = load i32, ptr %idx, align 4
  %variant_vec = load <4 x i32>, ptr %idx
  %ins = insertelement <4 x i32> poison, i32 %variant, i32 0
  %res = shufflevector <4 x i32> %ins, <4 x i32> %variant_vec, <4 x i32> <i32 0, i32 5, i32 6, i32 7>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test the commutative case for the shuffle (insert is operand 1)
define <4 x i32> @no_hoist_commutative_case(ptr %base, <4 x i32> %lhs, i32 %n) {
; CHECK-LABEL: define <4 x i32> @no_hoist_commutative_case(
; CHECK-SAME: ptr [[BASE:%.*]], <4 x i32> [[LHS:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VARIANT:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x i32> poison, i32 [[VARIANT]], i32 0
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[LHS]], <4 x i32> [[INS]], <4 x i32> <i32 0, i32 1, i32 6, i32 7>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %variant = load i32, ptr %idx, align 4
  %ins = insertelement <4 x i32> poison, i32 %variant, i32 0
  %res = shufflevector <4 x i32> %lhs, <4 x i32> %ins, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test when the insertion doesn't have a known index
define <4 x i32> @no_hoist_unknown_insert_index(ptr %base, <4 x i32> %inv, i32 %n, i32 %insidx) {
; CHECK-LABEL: define <4 x i32> @no_hoist_unknown_insert_index(
; CHECK-SAME: ptr [[BASE:%.*]], <4 x i32> [[INV:%.*]], i32 [[N:%.*]], i32 [[INSIDX:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VARIANT:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x i32> poison, i32 [[VARIANT]], i32 [[INSIDX]]
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[INS]], <4 x i32> [[INV]], <4 x i32> <i32 0, i32 5, i32 6, i32 7>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %variant = load i32, ptr %idx, align 4
  %ins = insertelement <4 x i32> poison, i32 %variant, i32 %insidx
  %res = shufflevector <4 x i32> %ins, <4 x i32> %inv, <4 x i32> <i32 0, i32 5, i32 6, i32 7>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test for out of bounds index for the insertion
define <4 x i32> @no_hoist_out_of_bounds_insert_index(ptr %base, <4 x i32> %inv, i32 %n) {
; CHECK-LABEL: define <4 x i32> @no_hoist_out_of_bounds_insert_index(
; CHECK-SAME: ptr [[BASE:%.*]], <4 x i32> [[INV:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VARIANT:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x i32> poison, i32 [[VARIANT]], i32 9
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[INS]], <4 x i32> [[INV]], <4 x i32> <i32 0, i32 5, i32 6, i32 7>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %variant = load i32, ptr %idx, align 4
  %ins = insertelement <4 x i32> poison, i32 %variant, i32 9
  %res = shufflevector <4 x i32> %ins, <4 x i32> %inv, <4 x i32> <i32 0, i32 5, i32 6, i32 7>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test for when shuffle indices are not constants (poison lane entries)
define <4 x i32> @no_hoist_poison_shuffle_lanes(ptr %base, <4 x i32> %inv, i32 %n) {
; CHECK-LABEL: define <4 x i32> @no_hoist_poison_shuffle_lanes(
; CHECK-SAME: ptr [[BASE:%.*]], <4 x i32> [[INV:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VAR:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x i32> poison, i32 [[VAR]], i32 0
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[INS]], <4 x i32> [[INV]], <4 x i32> <i32 poison, i32 5, i32 6, i32 7>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %variant = load i32, ptr %idx, align 4
  %ins = insertelement <4 x i32> poison, i32 %variant, i32 0
  %res = shufflevector <4 x i32> %ins, <4 x i32> %inv, <4 x i32> <i32 poison, i32 5, i32 6, i32 7>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test for when the shuffle uses the inserted position multiple times
define <4 x i32> @no_hoist_inserted_position_used_multiple_times(ptr %base, <4 x i32> %inv, i32 %n) {
; CHECK-LABEL: define <4 x i32> @no_hoist_inserted_position_used_multiple_times(
; CHECK-SAME: ptr [[BASE:%.*]], <4 x i32> [[INV:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VARIANT:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x i32> poison, i32 [[VARIANT]], i32 0
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[INS]], <4 x i32> [[INV]], <4 x i32> <i32 0, i32 0, i32 6, i32 7>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %variant = load i32, ptr %idx, align 4
  %ins = insertelement <4 x i32> poison, i32 %variant, i32 0
  %res = shufflevector <4 x i32> %ins, <4 x i32> %inv, <4 x i32> <i32 0, i32 0, i32 6, i32 7>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test for when the shuffle moves the inserted position
define <4 x i32> @no_hoist_when_shuffle_moves_inserted_position(ptr %base, <4 x i32> %inv, i32 %n) {
; CHECK-LABEL: define <4 x i32> @no_hoist_when_shuffle_moves_inserted_position(
; CHECK-SAME: ptr [[BASE:%.*]], <4 x i32> [[INV:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VARIANT:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x i32> poison, i32 [[VARIANT]], i32 0
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[INS]], <4 x i32> [[INV]], <4 x i32> <i32 5, i32 6, i32 7, i32 0>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %variant = load i32, ptr %idx, align 4
  %ins = insertelement <4 x i32> poison, i32 %variant, i32 0
  %res = shufflevector <4 x i32> %ins, <4 x i32> %inv, <4 x i32> <i32 5, i32 6, i32 7, i32 0>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test moving a shuffle past an insert-like shuffle.
define <4 x i32> @hoist_shuffle_past_shuffle(ptr %base, <4 x i32> %inv0, <4 x i32> %inv1, i32 %n) {
; CHECK-LABEL: define <4 x i32> @hoist_shuffle_past_shuffle(
; CHECK-SAME: ptr [[BASE:%.*]], <4 x i32> [[INV0:%.*]], <4 x i32> [[INV1:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VARIANT:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[RHS:%.*]] = insertelement <4 x i32> poison, i32 [[VARIANT]], i32 0
; CHECK-NEXT:    [[INNER:%.*]] = shufflevector <4 x i32> [[INV0]], <4 x i32> [[RHS]], <4 x i32> <i32 4, i32 1, i32 2, i32 3>
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[INNER]], <4 x i32> [[INV1]], <4 x i32> <i32 0, i32 5, i32 6, i32 7>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %variant = load i32, ptr %idx, align 4
  %rhs = insertelement <4 x i32> poison, i32 %variant, i32 0
  %inner = shufflevector <4 x i32> %inv0, <4 x i32> %rhs, <4 x i32> <i32 4, i32 1, i32 2, i32 3>
  %res = shufflevector <4 x i32> %inner, <4 x i32> %inv1, <4 x i32> <i32 0, i32 5, i32 6, i32 7>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test moving a shuffle past an insert-like shuffle with multiple inserted lanes.
define <4 x i32> @hoist_shuffle_past_shuffle_multi_lane(ptr %base, <4 x i32> %inv0, <4 x i32> %inv1, i32 %n) {
; CHECK-LABEL: define <4 x i32> @hoist_shuffle_past_shuffle_multi_lane(
; CHECK-SAME: ptr [[BASE:%.*]], <4 x i32> [[INV0:%.*]], <4 x i32> [[INV1:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VARIANT:%.*]] = load <4 x i32>, ptr [[IDX]], align 16
; CHECK-NEXT:    [[INNER:%.*]] = shufflevector <4 x i32> [[INV0]], <4 x i32> [[VARIANT]], <4 x i32> <i32 4, i32 5, i32 2, i32 3>
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[INNER]], <4 x i32> [[INV1]], <4 x i32> <i32 0, i32 1, i32 6, i32 7>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %variant = load <4 x i32>, ptr %idx, align 16
  %inner = shufflevector <4 x i32> %inv0, <4 x i32> %variant, <4 x i32> <i32 4, i32 5, i32 2, i32 3>
  %res = shufflevector <4 x i32> %inner, <4 x i32> %inv1, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test moving a shuffle past an insert-like shuffle.
define <4 x i32> @hoist_shuffle_past_shuffle_poison(ptr %base, <4 x i32> %inv0, <4 x i32> %inv1, i32 %n) {
; CHECK-LABEL: define <4 x i32> @hoist_shuffle_past_shuffle_poison(
; CHECK-SAME: ptr [[BASE:%.*]], <4 x i32> [[INV0:%.*]], <4 x i32> [[INV1:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VARIANT:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[RHS:%.*]] = insertelement <4 x i32> poison, i32 [[VARIANT]], i32 0
; CHECK-NEXT:    [[INNER:%.*]] = shufflevector <4 x i32> [[INV0]], <4 x i32> [[RHS]], <4 x i32> <i32 4, i32 1, i32 2, i32 poison>
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[INNER]], <4 x i32> [[INV1]], <4 x i32> <i32 0, i32 5, i32 6, i32 3>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %variant = load i32, ptr %idx, align 4
  %rhs = insertelement <4 x i32> poison, i32 %variant, i32 0
  %inner = shufflevector <4 x i32> %inv0, <4 x i32> %rhs, <4 x i32> <i32 4, i32 1, i32 2, i32 poison>
  %res = shufflevector <4 x i32> %inner, <4 x i32> %inv1, <4 x i32> <i32 0, i32 5, i32 6, i32 3>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test for when shuffle and insert both modify the same lane
define <4 x i32> @no_hoist_same_lanes(ptr %base, <4 x i32> %inv, i32 %n) {
; CHECK-LABEL: define <4 x i32> @no_hoist_same_lanes(
; CHECK-SAME: ptr [[BASE:%.*]], <4 x i32> [[INV:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VARIANT:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x i32> poison, i32 [[VARIANT]], i32 0
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[INS]], <4 x i32> [[INV]], <4 x i32> <i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %variant = load i32, ptr %idx, align 4
  %ins = insertelement <4 x i32> poison, i32 %variant, i32 0
  %res = shufflevector <4 x i32> %ins, <4 x i32> %inv, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test moving a shuffle past a mixed sequence of inserts and shuffles.
define <4 x i32> @hoist_shuffle_past_mixed_sequence(ptr %base, <4 x i32> %inv, i32 %n) {
; CHECK-LABEL: define <4 x i32> @hoist_shuffle_past_mixed_sequence(
; CHECK-SAME: ptr [[BASE:%.*]], <4 x i32> [[INV:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VAR:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[VARVEC:%.*]] = load <4 x i32>, ptr [[IDX]], align 16
; CHECK-NEXT:    [[I0:%.*]] = insertelement <4 x i32> poison, i32 [[VAR]], i32 0
; CHECK-NEXT:    [[S0:%.*]] = shufflevector <4 x i32> [[I0]], <4 x i32> [[VARVEC]], <4 x i32> <i32 0, i32 5, i32 2, i32 3>
; CHECK-NEXT:    [[I1:%.*]] = insertelement <4 x i32> [[S0]], i32 [[VAR]], i32 1
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[I1]], <4 x i32> [[INV]], <4 x i32> <i32 0, i32 1, i32 2, i32 7>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %var = load i32, ptr %idx, align 4
  %varvec = load <4 x i32>, ptr %idx, align 16
  %i0 = insertelement <4 x i32> poison, i32 %var, i32 0
  %s0 = shufflevector <4 x i32> %i0, <4 x i32> %varvec, <4 x i32> <i32 0, i32 5, i32 2, i32 3>
  %i1 = insertelement <4 x i32> %s0, i32 %var, i32 1
  %res = shufflevector <4 x i32> %i1, <4 x i32> %inv, <4 x i32> <i32 0, i32 1, i32 2, i32 7>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test recursively moving a shuffle past a deeper mixed sequence.
define <4 x i32> @hoist_shuffle_past_mixed_recursive_sequence(ptr %base, <4 x i32> %inv0, <4 x i32> %inv1, i32 %n) {
; CHECK-LABEL: define <4 x i32> @hoist_shuffle_past_mixed_recursive_sequence(
; CHECK-SAME: ptr [[BASE:%.*]], <4 x i32> [[INV0:%.*]], <4 x i32> [[INV1:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VAR:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[VARVEC:%.*]] = load <4 x i32>, ptr [[IDX]], align 16
; CHECK-NEXT:    [[I0:%.*]] = insertelement <4 x i32> poison, i32 [[VAR]], i32 0
; CHECK-NEXT:    [[S0:%.*]] = shufflevector <4 x i32> [[I0]], <4 x i32> [[INV0]], <4 x i32> <i32 0, i32 5, i32 2, i32 3>
; CHECK-NEXT:    [[I1:%.*]] = insertelement <4 x i32> [[S0]], i32 [[VAR]], i32 2
; CHECK-NEXT:    [[S1:%.*]] = shufflevector <4 x i32> [[I1]], <4 x i32> [[VARVEC]], <4 x i32> <i32 0, i32 5, i32 2, i32 3>
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <4 x i32> [[S1]], <4 x i32> [[INV1]], <4 x i32> <i32 0, i32 1, i32 2, i32 7>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %var = load i32, ptr %idx, align 4
  %varvec = load <4 x i32>, ptr %idx, align 16
  %i0 = insertelement <4 x i32> poison, i32 %var, i32 0
  %s0 = shufflevector <4 x i32> %i0, <4 x i32> %inv0, <4 x i32> <i32 0, i32 5, i32 2, i32 3>
  %i1 = insertelement <4 x i32> %s0, i32 %var, i32 2
  %s1 = shufflevector <4 x i32> %i1, <4 x i32> %varvec, <4 x i32> <i32 0, i32 5, i32 2, i32 3>
  %res = shufflevector <4 x i32> %s1, <4 x i32> %inv1, <4 x i32> <i32 0, i32 1, i32 2, i32 7>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}

; Test that length-changing shuffles are not treated as build-vectors.
define <4 x i32> @no_hoist_length_changing_shuffle(ptr %base, <8 x i32> %inv, i32 %n) {
; CHECK-LABEL: define <4 x i32> @no_hoist_length_changing_shuffle(
; CHECK-SAME: ptr [[BASE:%.*]], <8 x i32> [[INV:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i32 [[IV]]
; CHECK-NEXT:    [[VARIANT:%.*]] = load i32, ptr [[IDX]], align 4
; CHECK-NEXT:    [[INS:%.*]] = insertelement <8 x i32> poison, i32 [[VARIANT]], i32 0
; CHECK-NEXT:    [[RES:%.*]] = shufflevector <8 x i32> [[INS]], <8 x i32> [[INV]], <4 x i32> <i32 0, i32 5, i32 6, i32 7>
; CHECK-NEXT:    store <4 x i32> [[RES]], ptr [[IDX]], align 16
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES_LCSSA:%.*]] = phi <4 x i32> [ [[RES]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x i32> [[RES_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %idx = getelementptr inbounds i32, ptr %base, i32 %iv
  %variant = load i32, ptr %idx, align 4
  %ins = insertelement <8 x i32> poison, i32 %variant, i32 0
  %res = shufflevector <8 x i32> %ins, <8 x i32> %inv, <4 x i32> <i32 0, i32 5, i32 6, i32 7>
  store <4 x i32> %res, ptr %idx, align 16
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv, %n
  br i1 %done, label %exit, label %loop
exit:
  ret <4 x i32> %res
}
