; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=wasm32 -global-isel -stop-after=irtranslator -verify-machineinstrs < %s | FileCheck %s -check-prefixes=CHECK,WASM32
; RUN: llc -mtriple=wasm64 -global-isel -stop-after=irtranslator -verify-machineinstrs < %s | FileCheck %s -check-prefixes=CHECK,WASM64

define swiftcc void @test_implicit_self_and_error(float %arg) {


  ; CHECK-LABEL: name: test_implicit_self_and_error
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_f32_:%[0-9]+]]:f32(f32) = ARGUMENT_f32 0, implicit $arguments
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}

define swiftcc void @test_explicit_self_and_implicit_error(ptr swiftself %self, float %arg) {



  ; WASM32-LABEL: name: test_explicit_self_and_implicit_error
  ; WASM32: bb.1 (%ir-block.0):
  ; WASM32-NEXT:   liveins: $arguments
  ; WASM32-NEXT: {{  $}}
  ; WASM32-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(p0) = ARGUMENT_i32 0, implicit $arguments
  ; WASM32-NEXT:   [[ARGUMENT_f32_:%[0-9]+]]:f32(f32) = ARGUMENT_f32 1, implicit $arguments
  ; WASM32-NEXT:   RETURN implicit-def $arguments
  ;
  ; WASM64-LABEL: name: test_explicit_self_and_implicit_error
  ; WASM64: bb.1 (%ir-block.0):
  ; WASM64-NEXT:   liveins: $arguments
  ; WASM64-NEXT: {{  $}}
  ; WASM64-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(p0) = ARGUMENT_i64 0, implicit $arguments
  ; WASM64-NEXT:   [[ARGUMENT_f32_:%[0-9]+]]:f32(f32) = ARGUMENT_f32 1, implicit $arguments
  ; WASM64-NEXT:   RETURN implicit-def $arguments
  ret void
}

define swiftcc void @test_implicit_self_and_explicit_error(ptr swifterror %error, float %arg) {



  ; WASM32-LABEL: name: test_implicit_self_and_explicit_error
  ; WASM32: bb.1 (%ir-block.0):
  ; WASM32-NEXT:   liveins: $arguments
  ; WASM32-NEXT: {{  $}}
  ; WASM32-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(p0) = ARGUMENT_i32 0, implicit $arguments
  ; WASM32-NEXT:   [[ARGUMENT_f32_:%[0-9]+]]:f32(f32) = ARGUMENT_f32 1, implicit $arguments
  ; WASM32-NEXT:   RETURN implicit-def $arguments
  ;
  ; WASM64-LABEL: name: test_implicit_self_and_explicit_error
  ; WASM64: bb.1 (%ir-block.0):
  ; WASM64-NEXT:   liveins: $arguments
  ; WASM64-NEXT: {{  $}}
  ; WASM64-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(p0) = ARGUMENT_i64 0, implicit $arguments
  ; WASM64-NEXT:   [[ARGUMENT_f32_:%[0-9]+]]:f32(f32) = ARGUMENT_f32 1, implicit $arguments
  ; WASM64-NEXT:   RETURN implicit-def $arguments
  ret void
}

define swiftcc void @test_explicit_self_and_error(ptr swiftself %self, ptr swifterror %error, float %arg) {



  ; WASM32-LABEL: name: test_explicit_self_and_error
  ; WASM32: bb.1 (%ir-block.0):
  ; WASM32-NEXT:   liveins: $arguments
  ; WASM32-NEXT: {{  $}}
  ; WASM32-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(p0) = ARGUMENT_i32 0, implicit $arguments
  ; WASM32-NEXT:   [[ARGUMENT_i32_1:%[0-9]+]]:i32(p0) = ARGUMENT_i32 1, implicit $arguments
  ; WASM32-NEXT:   [[ARGUMENT_f32_:%[0-9]+]]:f32(f32) = ARGUMENT_f32 2, implicit $arguments
  ; WASM32-NEXT:   RETURN implicit-def $arguments
  ;
  ; WASM64-LABEL: name: test_explicit_self_and_error
  ; WASM64: bb.1 (%ir-block.0):
  ; WASM64-NEXT:   liveins: $arguments
  ; WASM64-NEXT: {{  $}}
  ; WASM64-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(p0) = ARGUMENT_i64 0, implicit $arguments
  ; WASM64-NEXT:   [[ARGUMENT_i64_1:%[0-9]+]]:i64(p0) = ARGUMENT_i64 1, implicit $arguments
  ; WASM64-NEXT:   [[ARGUMENT_f32_:%[0-9]+]]:f32(f32) = ARGUMENT_f32 2, implicit $arguments
  ; WASM64-NEXT:   RETURN implicit-def $arguments
  ret void
}
