; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=wasm32 -global-isel -stop-after=irtranslator < %s | FileCheck %s -check-prefixes=CHECK,WASM32
; RUN: llc -mtriple=wasm64 -global-isel -stop-after=irtranslator < %s | FileCheck %s -check-prefixes=CHECK,WASM64

define void @test_i8_arg(i8 %arg) {
  ; CHECK-LABEL: name: test_i8_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(i32) = ARGUMENT_i32 0, implicit $arguments
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i8) = G_TRUNC [[ARGUMENT_i32_]](i32)
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}

define void @test_i8_zeroext_arg(i8 zeroext %arg) {
  ; CHECK-LABEL: name: test_i8_zeroext_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(i32) = ARGUMENT_i32 0, implicit $arguments
  ; CHECK-NEXT:   [[ASSERT_ZEXT:%[0-9]+]]:_(i32) = G_ASSERT_ZEXT [[ARGUMENT_i32_]], 8
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i8) = G_TRUNC [[ASSERT_ZEXT]](i32)
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}

define void @test_i8_signext_arg(i8 signext %arg) {
  ; CHECK-LABEL: name: test_i8_signext_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(i32) = ARGUMENT_i32 0, implicit $arguments
  ; CHECK-NEXT:   [[ASSERT_SEXT:%[0-9]+]]:_(i32) = G_ASSERT_SEXT [[ARGUMENT_i32_]], 8
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i8) = G_TRUNC [[ASSERT_SEXT]](i32)
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}

define void @test_i16_arg(i16 %arg) {
  ; CHECK-LABEL: name: test_i16_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(i32) = ARGUMENT_i32 0, implicit $arguments
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i16) = G_TRUNC [[ARGUMENT_i32_]](i32)
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}


define void @test_i32_arg(i32 %arg) {
  ; CHECK-LABEL: name: test_i32_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(i32) = ARGUMENT_i32 0, implicit $arguments
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}


define void @test_i64_arg(i64 %arg) {
  ; CHECK-LABEL: name: test_i64_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(i64) = ARGUMENT_i64 0, implicit $arguments
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}

define void @test_ptr_arg(ptr %arg) {
  ; WASM32-LABEL: name: test_ptr_arg
  ; WASM32: bb.1 (%ir-block.0):
  ; WASM32-NEXT:   liveins: $arguments
  ; WASM32-NEXT: {{  $}}
  ; WASM32-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(p0) = ARGUMENT_i32 0, implicit $arguments
  ; WASM32-NEXT:   RETURN implicit-def $arguments
  ;
  ; WASM64-LABEL: name: test_ptr_arg
  ; WASM64: bb.1 (%ir-block.0):
  ; WASM64-NEXT:   liveins: $arguments
  ; WASM64-NEXT: {{  $}}
  ; WASM64-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(p0) = ARGUMENT_i64 0, implicit $arguments
  ; WASM64-NEXT:   RETURN implicit-def $arguments
  ret void
}

define void @test_i128_arg(i128 %arg) {
  ; CHECK-LABEL: name: test_i128_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(i64) = ARGUMENT_i64 0, implicit $arguments
  ; CHECK-NEXT:   [[ARGUMENT_i64_1:%[0-9]+]]:i64(i64) = ARGUMENT_i64 1, implicit $arguments
  ; CHECK-NEXT:   [[MV:%[0-9]+]]:_(i128) = G_MERGE_VALUES [[ARGUMENT_i64_]](i64), [[ARGUMENT_i64_1]](i64)
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}

define void @test_f16_arg(half %arg) {
  ; CHECK-LABEL: name: test_f16_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(i32) = ARGUMENT_i32 0, implicit $arguments
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(f16) = G_TRUNC [[ARGUMENT_i32_]](i32)
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}


define void @test_f32_arg(float %arg) {
  ; CHECK-LABEL: name: test_f32_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_f32_:%[0-9]+]]:f32(f32) = ARGUMENT_f32 0, implicit $arguments
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}


define void @test_f64_arg(double %arg) {
  ; CHECK-LABEL: name: test_f64_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_f64_:%[0-9]+]]:f64(f64) = ARGUMENT_f64 0, implicit $arguments
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}

define void @test_f128_arg(fp128 %arg) {
  ; CHECK-LABEL: name: test_f128_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(i64) = ARGUMENT_i64 0, implicit $arguments
  ; CHECK-NEXT:   [[ARGUMENT_i64_1:%[0-9]+]]:i64(i64) = ARGUMENT_i64 1, implicit $arguments
  ; CHECK-NEXT:   [[MV:%[0-9]+]]:_(f128) = G_MERGE_VALUES [[ARGUMENT_i64_]](i64), [[ARGUMENT_i64_1]](i64)
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}

%externref = type ptr addrspace(10)
define void @test_externref_arg(%externref %arg) {
  ; CHECK-LABEL: name: test_externref_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_externref:%[0-9]+]]:externref(p10) = ARGUMENT_externref 0, implicit $arguments
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}

%funcref = type ptr addrspace(20)
define void @test_funcref_arg(%funcref %arg) {
  ; CHECK-LABEL: name: test_funcref_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_funcref:%[0-9]+]]:funcref(p20) = ARGUMENT_funcref 0, implicit $arguments
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}

define void @test_multiple_args(ptr %arg1, float %arg2, i1 %arg3) {
  ; WASM32-LABEL: name: test_multiple_args
  ; WASM32: bb.1 (%ir-block.0):
  ; WASM32-NEXT:   liveins: $arguments
  ; WASM32-NEXT: {{  $}}
  ; WASM32-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(p0) = ARGUMENT_i32 0, implicit $arguments
  ; WASM32-NEXT:   [[ARGUMENT_f32_:%[0-9]+]]:f32(f32) = ARGUMENT_f32 1, implicit $arguments
  ; WASM32-NEXT:   [[ARGUMENT_i32_1:%[0-9]+]]:i32(i32) = ARGUMENT_i32 2, implicit $arguments
  ; WASM32-NEXT:   [[TRUNC:%[0-9]+]]:_(i1) = G_TRUNC [[ARGUMENT_i32_1]](i32)
  ; WASM32-NEXT:   RETURN implicit-def $arguments
  ;
  ; WASM64-LABEL: name: test_multiple_args
  ; WASM64: bb.1 (%ir-block.0):
  ; WASM64-NEXT:   liveins: $arguments
  ; WASM64-NEXT: {{  $}}
  ; WASM64-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(p0) = ARGUMENT_i64 0, implicit $arguments
  ; WASM64-NEXT:   [[ARGUMENT_f32_:%[0-9]+]]:f32(f32) = ARGUMENT_f32 1, implicit $arguments
  ; WASM64-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(i32) = ARGUMENT_i32 2, implicit $arguments
  ; WASM64-NEXT:   [[TRUNC:%[0-9]+]]:_(i1) = G_TRUNC [[ARGUMENT_i32_]](i32)
  ; WASM64-NEXT:   RETURN implicit-def $arguments
  ret void
}

define void @test_array_arg([5 x i16] %arg) {
  ; CHECK-LABEL: name: test_array_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(i32) = ARGUMENT_i32 0, implicit $arguments
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i16) = G_TRUNC [[ARGUMENT_i32_]](i32)
  ; CHECK-NEXT:   [[ARGUMENT_i32_1:%[0-9]+]]:i32(i32) = ARGUMENT_i32 1, implicit $arguments
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(i16) = G_TRUNC [[ARGUMENT_i32_1]](i32)
  ; CHECK-NEXT:   [[ARGUMENT_i32_2:%[0-9]+]]:i32(i32) = ARGUMENT_i32 2, implicit $arguments
  ; CHECK-NEXT:   [[TRUNC2:%[0-9]+]]:_(i16) = G_TRUNC [[ARGUMENT_i32_2]](i32)
  ; CHECK-NEXT:   [[ARGUMENT_i32_3:%[0-9]+]]:i32(i32) = ARGUMENT_i32 3, implicit $arguments
  ; CHECK-NEXT:   [[TRUNC3:%[0-9]+]]:_(i16) = G_TRUNC [[ARGUMENT_i32_3]](i32)
  ; CHECK-NEXT:   [[ARGUMENT_i32_4:%[0-9]+]]:i32(i32) = ARGUMENT_i32 4, implicit $arguments
  ; CHECK-NEXT:   [[TRUNC4:%[0-9]+]]:_(i16) = G_TRUNC [[ARGUMENT_i32_4]](i32)
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}

%StructTy = type { i8, i64, i16, i1, float }

define void @test_struct_arg(%StructTy %arg) {
  ; CHECK-LABEL: name: test_struct_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(i32) = ARGUMENT_i32 0, implicit $arguments
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i8) = G_TRUNC [[ARGUMENT_i32_]](i32)
  ; CHECK-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(i64) = ARGUMENT_i64 1, implicit $arguments
  ; CHECK-NEXT:   [[ARGUMENT_i32_1:%[0-9]+]]:i32(i32) = ARGUMENT_i32 2, implicit $arguments
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(i16) = G_TRUNC [[ARGUMENT_i32_1]](i32)
  ; CHECK-NEXT:   [[ARGUMENT_i32_2:%[0-9]+]]:i32(i32) = ARGUMENT_i32 3, implicit $arguments
  ; CHECK-NEXT:   [[TRUNC2:%[0-9]+]]:_(i1) = G_TRUNC [[ARGUMENT_i32_2]](i32)
  ; CHECK-NEXT:   [[ARGUMENT_f32_:%[0-9]+]]:f32(f32) = ARGUMENT_f32 4, implicit $arguments
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}
