; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=wasm32 -mattr=-simd128,-multivalue -global-isel -stop-after=irtranslator < %s | FileCheck %s -check-prefixes=CHECK,WASM32,WASM32-BASIC
; RUN: llc -mtriple=wasm64 -mattr=-simd128,-multivalue -global-isel -stop-after=irtranslator < %s | FileCheck %s -check-prefixes=CHECK,WASM64,WASM64-BASIC
; RUN: llc -mtriple=wasm32 -mattr=+simd128,+multivalue -target-abi=experimental-mv -global-isel -stop-after=irtranslator < %s | FileCheck %s -check-prefixes=CHECK,WASM32,MULTIVAL-SIMD,WASM32-MULTIVAL-SIMD
; RUN: llc -mtriple=wasm64 -mattr=+simd128,+multivalue -target-abi=experimental-mv -global-isel -stop-after=irtranslator < %s | FileCheck %s -check-prefixes=CHECK,WASM64,MULTIVAL-SIMD,WASM64-MULTIVAL-SIMD


%externref = type ptr addrspace(10)
%funcref = type ptr addrspace(20)

declare void @ret_void_args_none()
define void @call_ret_void_args_none() {
  ; CHECK-LABEL: name: call_ret_void_args_none
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   CALL @ret_void_args_none, implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  call void @ret_void_args_none()
  ret void
}

declare i32 @ret_i32_args_none()
define i32 @call_ret_i32_args_none() {
  ; CHECK-LABEL: name: call_ret_i32_args_none
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CALL:%[0-9]+]]:i32(i32) = CALL @ret_i32_args_none, implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN [[CALL]](i32), implicit-def $arguments
  %ret = call i32 @ret_i32_args_none()
  ret i32 %ret
}

declare i64 @ret_i64_args_none()
define i64 @call_ret_i64_args_none() {
  ; CHECK-LABEL: name: call_ret_i64_args_none
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CALL:%[0-9]+]]:i64(i64) = CALL @ret_i64_args_none, implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN [[CALL]](i64), implicit-def $arguments
  %ret = call i64 @ret_i64_args_none()
  ret i64 %ret
}

declare float @ret_f32_args_none()
define float @call_ret_f32_args_none() {
  ; CHECK-LABEL: name: call_ret_f32_args_none
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CALL:%[0-9]+]]:f32(f32) = CALL @ret_f32_args_none, implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN [[CALL]](f32), implicit-def $arguments
  %ret = call float @ret_f32_args_none()
  ret float %ret
}

declare double @ret_f64_args_none()
define double @call_ret_f64_args_none() {
  ; CHECK-LABEL: name: call_ret_f64_args_none
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CALL:%[0-9]+]]:f64(f64) = CALL @ret_f64_args_none, implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN [[CALL]](f64), implicit-def $arguments
  %ret = call double @ret_f64_args_none()
  ret double %ret
}

declare ptr @ret_ptr_args_none()
define ptr @call_ret_ptr_args_none() {
  ; WASM32-LABEL: name: call_ret_ptr_args_none
  ; WASM32: bb.1 (%ir-block.0):
  ; WASM32-NEXT:   liveins: $arguments
  ; WASM32-NEXT: {{  $}}
  ; WASM32-NEXT:   [[CALL:%[0-9]+]]:i32(p0) = CALL @ret_ptr_args_none, implicit-def $arguments, implicit $sp32, implicit $sp64
  ; WASM32-NEXT:   RETURN [[CALL]](p0), implicit-def $arguments
  ;
  ; WASM64-LABEL: name: call_ret_ptr_args_none
  ; WASM64: bb.1 (%ir-block.0):
  ; WASM64-NEXT:   liveins: $arguments
  ; WASM64-NEXT: {{  $}}
  ; WASM64-NEXT:   [[CALL:%[0-9]+]]:i64(p0) = CALL @ret_ptr_args_none, implicit-def $arguments, implicit $sp32, implicit $sp64
  ; WASM64-NEXT:   RETURN [[CALL]](p0), implicit-def $arguments
  %ret = call ptr @ret_ptr_args_none()
  ret ptr %ret
}

declare %externref @ret_externref_args_none()
define %externref @call_ret_externref_args_none() {
  ; CHECK-LABEL: name: call_ret_externref_args_none
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CALL:%[0-9]+]]:externref(p10) = CALL @ret_externref_args_none, implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN [[CALL]](p10), implicit-def $arguments
  %ret = call %externref @ret_externref_args_none()
  ret %externref %ret
}

declare %funcref @ret_funcref_args_none()
define %funcref @call_ret_funcref_args_none() {
  ; CHECK-LABEL: name: call_ret_funcref_args_none
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CALL:%[0-9]+]]:funcref(p20) = CALL @ret_funcref_args_none, implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN [[CALL]](p20), implicit-def $arguments
  %ret = call %funcref @ret_funcref_args_none()
  ret %funcref %ret
}

declare i128 @ret_i128_args_none()
define i128 @call_ret_i128_args_none() {
  ; WASM32-BASIC-LABEL: name: call_ret_i128_args_none
  ; WASM32-BASIC: bb.1 (%ir-block.0):
  ; WASM32-BASIC-NEXT:   liveins: $arguments
  ; WASM32-BASIC-NEXT: {{  $}}
  ; WASM32-BASIC-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(p0) = ARGUMENT_i32 0, implicit $arguments
  ; WASM32-BASIC-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0
  ; WASM32-BASIC-NEXT:   CALL @ret_i128_args_none, [[FRAME_INDEX]](p0), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; WASM32-BASIC-NEXT:   [[LOAD:%[0-9]+]]:_(i128) = G_LOAD [[FRAME_INDEX]](p0) :: (load (i128) from %stack.0)
  ; WASM32-BASIC-NEXT:   G_STORE [[LOAD]](i128), [[ARGUMENT_i32_]](p0) :: (store (i128))
  ; WASM32-BASIC-NEXT:   RETURN implicit-def $arguments
  ;
  ; WASM64-BASIC-LABEL: name: call_ret_i128_args_none
  ; WASM64-BASIC: bb.1 (%ir-block.0):
  ; WASM64-BASIC-NEXT:   liveins: $arguments
  ; WASM64-BASIC-NEXT: {{  $}}
  ; WASM64-BASIC-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(p0) = ARGUMENT_i64 0, implicit $arguments
  ; WASM64-BASIC-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0
  ; WASM64-BASIC-NEXT:   CALL @ret_i128_args_none, [[FRAME_INDEX]](p0), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; WASM64-BASIC-NEXT:   [[LOAD:%[0-9]+]]:_(i128) = G_LOAD [[FRAME_INDEX]](p0) :: (load (i128) from %stack.0)
  ; WASM64-BASIC-NEXT:   G_STORE [[LOAD]](i128), [[ARGUMENT_i64_]](p0) :: (store (i128))
  ; WASM64-BASIC-NEXT:   RETURN implicit-def $arguments
  ;
  ; MULTIVAL-SIMD-LABEL: name: call_ret_i128_args_none
  ; MULTIVAL-SIMD: bb.1 (%ir-block.0):
  ; MULTIVAL-SIMD-NEXT:   liveins: $arguments
  ; MULTIVAL-SIMD-NEXT: {{  $}}
  ; MULTIVAL-SIMD-NEXT:   [[CALL:%[0-9]+]]:i64(i64), [[CALL1:%[0-9]+]]:i64(i64) = CALL @ret_i128_args_none, implicit-def $arguments, implicit $sp32, implicit $sp64
  ; MULTIVAL-SIMD-NEXT:   [[MV:%[0-9]+]]:_(i128) = G_MERGE_VALUES [[CALL]](i64), [[CALL1]](i64)
  ; MULTIVAL-SIMD-NEXT:   [[UV:%[0-9]+]]:i64(i64), [[UV1:%[0-9]+]]:i64(i64) = G_UNMERGE_VALUES [[MV]](i128)
  ; MULTIVAL-SIMD-NEXT:   RETURN [[UV]](i64), [[UV1]](i64), implicit-def $arguments
  %ret = call i128 @ret_i128_args_none()
  ret i128 %ret
}

declare half @ret_f16_args_none()
define half @call_ret_f16_args_none() {
  ; CHECK-LABEL: name: call_ret_f16_args_none
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CALL:%[0-9]+]]:i32(i32) = CALL @ret_f16_args_none, implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(f16) = G_TRUNC [[CALL]](i32)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:i32(i32) = G_ANYEXT [[TRUNC]](f16)
  ; CHECK-NEXT:   RETURN [[ANYEXT]](i32), implicit-def $arguments
  %ret = call half @ret_f16_args_none()
  ret half %ret
}

declare void @ret_void_args_i32(i32)
define void @call_ret_void_args_i32(i32 %a) {
  ; CHECK-LABEL: name: call_ret_void_args_i32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(i32) = ARGUMENT_i32 0, implicit $arguments
  ; CHECK-NEXT:   CALL @ret_void_args_i32, [[ARGUMENT_i32_]](i32), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  call void @ret_void_args_i32(i32 %a)
  ret void
}

declare void @ret_void_args_i64(i64)
define void @call_ret_void_args_i64(i64 %a) {
  ; CHECK-LABEL: name: call_ret_void_args_i64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(i64) = ARGUMENT_i64 0, implicit $arguments
  ; CHECK-NEXT:   CALL @ret_void_args_i64, [[ARGUMENT_i64_]](i64), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  call void @ret_void_args_i64(i64 %a)
  ret void
}

declare void @ret_void_args_f32(float)
define void @call_ret_void_args_f32(float %a) {
  ; CHECK-LABEL: name: call_ret_void_args_f32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_f32_:%[0-9]+]]:f32(f32) = ARGUMENT_f32 0, implicit $arguments
  ; CHECK-NEXT:   CALL @ret_void_args_f32, [[ARGUMENT_f32_]](f32), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  call void @ret_void_args_f32(float %a)
  ret void
}

declare void @ret_void_args_f64(double)
define void @call_ret_void_args_f64(double %a) {
  ; CHECK-LABEL: name: call_ret_void_args_f64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_f64_:%[0-9]+]]:f64(f64) = ARGUMENT_f64 0, implicit $arguments
  ; CHECK-NEXT:   CALL @ret_void_args_f64, [[ARGUMENT_f64_]](f64), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  call void @ret_void_args_f64(double %a)
  ret void
}

declare void @ret_void_args_ptr(ptr)
define void @call_ret_void_args_ptr(ptr %a) {
  ; WASM32-LABEL: name: call_ret_void_args_ptr
  ; WASM32: bb.1 (%ir-block.0):
  ; WASM32-NEXT:   liveins: $arguments
  ; WASM32-NEXT: {{  $}}
  ; WASM32-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(p0) = ARGUMENT_i32 0, implicit $arguments
  ; WASM32-NEXT:   CALL @ret_void_args_ptr, [[ARGUMENT_i32_]](p0), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; WASM32-NEXT:   RETURN implicit-def $arguments
  ;
  ; WASM64-LABEL: name: call_ret_void_args_ptr
  ; WASM64: bb.1 (%ir-block.0):
  ; WASM64-NEXT:   liveins: $arguments
  ; WASM64-NEXT: {{  $}}
  ; WASM64-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(p0) = ARGUMENT_i64 0, implicit $arguments
  ; WASM64-NEXT:   CALL @ret_void_args_ptr, [[ARGUMENT_i64_]](p0), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; WASM64-NEXT:   RETURN implicit-def $arguments
  call void @ret_void_args_ptr(ptr %a)
  ret void
}

declare void @ret_void_args_externref(%externref)
define void @call_ret_void_args_externref(%externref %a) {
  ; CHECK-LABEL: name: call_ret_void_args_externref
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_externref:%[0-9]+]]:externref(p10) = ARGUMENT_externref 0, implicit $arguments
  ; CHECK-NEXT:   CALL @ret_void_args_externref, [[ARGUMENT_externref]](p10), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  call void @ret_void_args_externref(%externref %a)
  ret void
}

declare void @ret_void_args_funcref(%funcref)
define void @call_ret_void_args_funcref(%funcref %a) {
  ; CHECK-LABEL: name: call_ret_void_args_funcref
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_funcref:%[0-9]+]]:funcref(p20) = ARGUMENT_funcref 0, implicit $arguments
  ; CHECK-NEXT:   CALL @ret_void_args_funcref, [[ARGUMENT_funcref]](p20), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  call void @ret_void_args_funcref(%funcref %a)
  ret void
}

declare void @ret_void_args_i128(i128)
define void @call_ret_void_args_i128(i128 %a) {
  ; CHECK-LABEL: name: call_ret_void_args_i128
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(i64) = ARGUMENT_i64 0, implicit $arguments
  ; CHECK-NEXT:   [[ARGUMENT_i64_1:%[0-9]+]]:i64(i64) = ARGUMENT_i64 1, implicit $arguments
  ; CHECK-NEXT:   [[MV:%[0-9]+]]:_(i128) = G_MERGE_VALUES [[ARGUMENT_i64_]](i64), [[ARGUMENT_i64_1]](i64)
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:i64(i64), [[UV1:%[0-9]+]]:i64(i64) = G_UNMERGE_VALUES [[MV]](i128)
  ; CHECK-NEXT:   CALL @ret_void_args_i128, [[UV]](i64), [[UV1]](i64), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  call void @ret_void_args_i128(i128 %a)
  ret void
}

declare void @ret_void_args_f16(half)
define void @call_ret_void_args_f16(half %a) {
  ; CHECK-LABEL: name: call_ret_void_args_f16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(i32) = ARGUMENT_i32 0, implicit $arguments
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(f16) = G_TRUNC [[ARGUMENT_i32_]](i32)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:i32(i32) = G_ANYEXT [[TRUNC]](f16)
  ; CHECK-NEXT:   CALL @ret_void_args_f16, [[ANYEXT]](i32), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  call void @ret_void_args_f16(half %a)
  ret void
}

%complexret = type { i32, ptr, <4 x float> }
declare %complexret @complex(<8 x i16>, [3 x ptr], i1)
define %complexret @call_complex(<8 x i16> %a, [3 x ptr] %b, i1 %c) {
  ; WASM32-BASIC-LABEL: name: call_complex
  ; WASM32-BASIC: bb.1 (%ir-block.0):
  ; WASM32-BASIC-NEXT:   liveins: $arguments
  ; WASM32-BASIC-NEXT: {{  $}}
  ; WASM32-BASIC-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(p0) = ARGUMENT_i32 0, implicit $arguments
  ; WASM32-BASIC-NEXT:   [[ARGUMENT_i32_1:%[0-9]+]]:i32(i32) = ARGUMENT_i32 1, implicit $arguments
  ; WASM32-BASIC-NEXT:   [[ARGUMENT_i32_2:%[0-9]+]]:i32(i32) = ARGUMENT_i32 2, implicit $arguments
  ; WASM32-BASIC-NEXT:   [[ARGUMENT_i32_3:%[0-9]+]]:i32(i32) = ARGUMENT_i32 3, implicit $arguments
  ; WASM32-BASIC-NEXT:   [[ARGUMENT_i32_4:%[0-9]+]]:i32(i32) = ARGUMENT_i32 4, implicit $arguments
  ; WASM32-BASIC-NEXT:   [[ARGUMENT_i32_5:%[0-9]+]]:i32(i32) = ARGUMENT_i32 5, implicit $arguments
  ; WASM32-BASIC-NEXT:   [[ARGUMENT_i32_6:%[0-9]+]]:i32(i32) = ARGUMENT_i32 6, implicit $arguments
  ; WASM32-BASIC-NEXT:   [[ARGUMENT_i32_7:%[0-9]+]]:i32(i32) = ARGUMENT_i32 7, implicit $arguments
  ; WASM32-BASIC-NEXT:   [[ARGUMENT_i32_8:%[0-9]+]]:i32(i32) = ARGUMENT_i32 8, implicit $arguments
  ; WASM32-BASIC-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x i32>) = G_BUILD_VECTOR [[ARGUMENT_i32_1]](i32), [[ARGUMENT_i32_2]](i32), [[ARGUMENT_i32_3]](i32), [[ARGUMENT_i32_4]](i32), [[ARGUMENT_i32_5]](i32), [[ARGUMENT_i32_6]](i32), [[ARGUMENT_i32_7]](i32), [[ARGUMENT_i32_8]](i32)
  ; WASM32-BASIC-NEXT:   [[TRUNC:%[0-9]+]]:_(<8 x i16>) = G_TRUNC [[BUILD_VECTOR]](<8 x i32>)
  ; WASM32-BASIC-NEXT:   [[ARGUMENT_i32_9:%[0-9]+]]:i32(p0) = ARGUMENT_i32 9, implicit $arguments
  ; WASM32-BASIC-NEXT:   [[ARGUMENT_i32_10:%[0-9]+]]:i32(p0) = ARGUMENT_i32 10, implicit $arguments
  ; WASM32-BASIC-NEXT:   [[ARGUMENT_i32_11:%[0-9]+]]:i32(p0) = ARGUMENT_i32 11, implicit $arguments
  ; WASM32-BASIC-NEXT:   [[ARGUMENT_i32_12:%[0-9]+]]:i32(i32) = ARGUMENT_i32 12, implicit $arguments
  ; WASM32-BASIC-NEXT:   [[TRUNC1:%[0-9]+]]:_(i1) = G_TRUNC [[ARGUMENT_i32_12]](i32)
  ; WASM32-BASIC-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0
  ; WASM32-BASIC-NEXT:   [[UV:%[0-9]+]]:_(i16), [[UV1:%[0-9]+]]:_(i16), [[UV2:%[0-9]+]]:_(i16), [[UV3:%[0-9]+]]:_(i16), [[UV4:%[0-9]+]]:_(i16), [[UV5:%[0-9]+]]:_(i16), [[UV6:%[0-9]+]]:_(i16), [[UV7:%[0-9]+]]:_(i16) = G_UNMERGE_VALUES [[TRUNC]](<8 x i16>)
  ; WASM32-BASIC-NEXT:   [[ANYEXT:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV]](i16)
  ; WASM32-BASIC-NEXT:   [[ANYEXT1:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV1]](i16)
  ; WASM32-BASIC-NEXT:   [[ANYEXT2:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV2]](i16)
  ; WASM32-BASIC-NEXT:   [[ANYEXT3:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV3]](i16)
  ; WASM32-BASIC-NEXT:   [[ANYEXT4:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV4]](i16)
  ; WASM32-BASIC-NEXT:   [[ANYEXT5:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV5]](i16)
  ; WASM32-BASIC-NEXT:   [[ANYEXT6:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV6]](i16)
  ; WASM32-BASIC-NEXT:   [[ANYEXT7:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV7]](i16)
  ; WASM32-BASIC-NEXT:   [[ANYEXT8:%[0-9]+]]:i32(i32) = G_ANYEXT [[TRUNC1]](i1)
  ; WASM32-BASIC-NEXT:   CALL @complex, [[FRAME_INDEX]](p0), [[ANYEXT]](i32), [[ANYEXT1]](i32), [[ANYEXT2]](i32), [[ANYEXT3]](i32), [[ANYEXT4]](i32), [[ANYEXT5]](i32), [[ANYEXT6]](i32), [[ANYEXT7]](i32), [[ARGUMENT_i32_9]](p0), [[ARGUMENT_i32_10]](p0), [[ARGUMENT_i32_11]](p0), [[ANYEXT8]](i32), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; WASM32-BASIC-NEXT:   [[LOAD:%[0-9]+]]:_(i32) = G_LOAD [[FRAME_INDEX]](p0) :: (load (i32) from %stack.0, align 16)
  ; WASM32-BASIC-NEXT:   [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 4
  ; WASM32-BASIC-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[FRAME_INDEX]], [[C]](i32)
  ; WASM32-BASIC-NEXT:   [[LOAD1:%[0-9]+]]:_(p0) = G_LOAD [[PTR_ADD]](p0) :: (load (p0) from %stack.0)
  ; WASM32-BASIC-NEXT:   [[C1:%[0-9]+]]:_(i32) = G_CONSTANT i32 16
  ; WASM32-BASIC-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[FRAME_INDEX]], [[C1]](i32)
  ; WASM32-BASIC-NEXT:   [[LOAD2:%[0-9]+]]:_(<4 x f32>) = G_LOAD [[PTR_ADD1]](p0) :: (load (<4 x f32>) from %stack.0)
  ; WASM32-BASIC-NEXT:   G_STORE [[LOAD]](i32), [[ARGUMENT_i32_]](p0) :: (store (i32), align 16)
  ; WASM32-BASIC-NEXT:   [[C2:%[0-9]+]]:_(i32) = G_CONSTANT i32 4
  ; WASM32-BASIC-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i32_]], [[C2]](i32)
  ; WASM32-BASIC-NEXT:   G_STORE [[LOAD1]](p0), [[PTR_ADD2]](p0) :: (store (p0))
  ; WASM32-BASIC-NEXT:   [[C3:%[0-9]+]]:_(i32) = G_CONSTANT i32 16
  ; WASM32-BASIC-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i32_]], [[C3]](i32)
  ; WASM32-BASIC-NEXT:   G_STORE [[LOAD2]](<4 x f32>), [[PTR_ADD3]](p0) :: (store (<4 x f32>))
  ; WASM32-BASIC-NEXT:   RETURN implicit-def $arguments
  ;
  ; WASM64-BASIC-LABEL: name: call_complex
  ; WASM64-BASIC: bb.1 (%ir-block.0):
  ; WASM64-BASIC-NEXT:   liveins: $arguments
  ; WASM64-BASIC-NEXT: {{  $}}
  ; WASM64-BASIC-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(p0) = ARGUMENT_i64 0, implicit $arguments
  ; WASM64-BASIC-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(i32) = ARGUMENT_i32 1, implicit $arguments
  ; WASM64-BASIC-NEXT:   [[ARGUMENT_i32_1:%[0-9]+]]:i32(i32) = ARGUMENT_i32 2, implicit $arguments
  ; WASM64-BASIC-NEXT:   [[ARGUMENT_i32_2:%[0-9]+]]:i32(i32) = ARGUMENT_i32 3, implicit $arguments
  ; WASM64-BASIC-NEXT:   [[ARGUMENT_i32_3:%[0-9]+]]:i32(i32) = ARGUMENT_i32 4, implicit $arguments
  ; WASM64-BASIC-NEXT:   [[ARGUMENT_i32_4:%[0-9]+]]:i32(i32) = ARGUMENT_i32 5, implicit $arguments
  ; WASM64-BASIC-NEXT:   [[ARGUMENT_i32_5:%[0-9]+]]:i32(i32) = ARGUMENT_i32 6, implicit $arguments
  ; WASM64-BASIC-NEXT:   [[ARGUMENT_i32_6:%[0-9]+]]:i32(i32) = ARGUMENT_i32 7, implicit $arguments
  ; WASM64-BASIC-NEXT:   [[ARGUMENT_i32_7:%[0-9]+]]:i32(i32) = ARGUMENT_i32 8, implicit $arguments
  ; WASM64-BASIC-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x i32>) = G_BUILD_VECTOR [[ARGUMENT_i32_]](i32), [[ARGUMENT_i32_1]](i32), [[ARGUMENT_i32_2]](i32), [[ARGUMENT_i32_3]](i32), [[ARGUMENT_i32_4]](i32), [[ARGUMENT_i32_5]](i32), [[ARGUMENT_i32_6]](i32), [[ARGUMENT_i32_7]](i32)
  ; WASM64-BASIC-NEXT:   [[TRUNC:%[0-9]+]]:_(<8 x i16>) = G_TRUNC [[BUILD_VECTOR]](<8 x i32>)
  ; WASM64-BASIC-NEXT:   [[ARGUMENT_i64_1:%[0-9]+]]:i64(p0) = ARGUMENT_i64 9, implicit $arguments
  ; WASM64-BASIC-NEXT:   [[ARGUMENT_i64_2:%[0-9]+]]:i64(p0) = ARGUMENT_i64 10, implicit $arguments
  ; WASM64-BASIC-NEXT:   [[ARGUMENT_i64_3:%[0-9]+]]:i64(p0) = ARGUMENT_i64 11, implicit $arguments
  ; WASM64-BASIC-NEXT:   [[ARGUMENT_i32_8:%[0-9]+]]:i32(i32) = ARGUMENT_i32 12, implicit $arguments
  ; WASM64-BASIC-NEXT:   [[TRUNC1:%[0-9]+]]:_(i1) = G_TRUNC [[ARGUMENT_i32_8]](i32)
  ; WASM64-BASIC-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0
  ; WASM64-BASIC-NEXT:   [[UV:%[0-9]+]]:_(i16), [[UV1:%[0-9]+]]:_(i16), [[UV2:%[0-9]+]]:_(i16), [[UV3:%[0-9]+]]:_(i16), [[UV4:%[0-9]+]]:_(i16), [[UV5:%[0-9]+]]:_(i16), [[UV6:%[0-9]+]]:_(i16), [[UV7:%[0-9]+]]:_(i16) = G_UNMERGE_VALUES [[TRUNC]](<8 x i16>)
  ; WASM64-BASIC-NEXT:   [[ANYEXT:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV]](i16)
  ; WASM64-BASIC-NEXT:   [[ANYEXT1:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV1]](i16)
  ; WASM64-BASIC-NEXT:   [[ANYEXT2:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV2]](i16)
  ; WASM64-BASIC-NEXT:   [[ANYEXT3:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV3]](i16)
  ; WASM64-BASIC-NEXT:   [[ANYEXT4:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV4]](i16)
  ; WASM64-BASIC-NEXT:   [[ANYEXT5:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV5]](i16)
  ; WASM64-BASIC-NEXT:   [[ANYEXT6:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV6]](i16)
  ; WASM64-BASIC-NEXT:   [[ANYEXT7:%[0-9]+]]:i32(i32) = G_ANYEXT [[UV7]](i16)
  ; WASM64-BASIC-NEXT:   [[ANYEXT8:%[0-9]+]]:i32(i32) = G_ANYEXT [[TRUNC1]](i1)
  ; WASM64-BASIC-NEXT:   CALL @complex, [[FRAME_INDEX]](p0), [[ANYEXT]](i32), [[ANYEXT1]](i32), [[ANYEXT2]](i32), [[ANYEXT3]](i32), [[ANYEXT4]](i32), [[ANYEXT5]](i32), [[ANYEXT6]](i32), [[ANYEXT7]](i32), [[ARGUMENT_i64_1]](p0), [[ARGUMENT_i64_2]](p0), [[ARGUMENT_i64_3]](p0), [[ANYEXT8]](i32), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; WASM64-BASIC-NEXT:   [[LOAD:%[0-9]+]]:_(i32) = G_LOAD [[FRAME_INDEX]](p0) :: (load (i32) from %stack.0, align 16)
  ; WASM64-BASIC-NEXT:   [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 8
  ; WASM64-BASIC-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[FRAME_INDEX]], [[C]](i64)
  ; WASM64-BASIC-NEXT:   [[LOAD1:%[0-9]+]]:_(p0) = G_LOAD [[PTR_ADD]](p0) :: (load (p0) from %stack.0)
  ; WASM64-BASIC-NEXT:   [[C1:%[0-9]+]]:_(i64) = G_CONSTANT i64 16
  ; WASM64-BASIC-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[FRAME_INDEX]], [[C1]](i64)
  ; WASM64-BASIC-NEXT:   [[LOAD2:%[0-9]+]]:_(<4 x f32>) = G_LOAD [[PTR_ADD1]](p0) :: (load (<4 x f32>) from %stack.0)
  ; WASM64-BASIC-NEXT:   G_STORE [[LOAD]](i32), [[ARGUMENT_i64_]](p0) :: (store (i32), align 16)
  ; WASM64-BASIC-NEXT:   [[C2:%[0-9]+]]:_(i64) = G_CONSTANT i64 8
  ; WASM64-BASIC-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i64_]], [[C2]](i64)
  ; WASM64-BASIC-NEXT:   G_STORE [[LOAD1]](p0), [[PTR_ADD2]](p0) :: (store (p0))
  ; WASM64-BASIC-NEXT:   [[C3:%[0-9]+]]:_(i64) = G_CONSTANT i64 16
  ; WASM64-BASIC-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i64_]], [[C3]](i64)
  ; WASM64-BASIC-NEXT:   G_STORE [[LOAD2]](<4 x f32>), [[PTR_ADD3]](p0) :: (store (<4 x f32>))
  ; WASM64-BASIC-NEXT:   RETURN implicit-def $arguments
  ;
  ; WASM32-MULTIVAL-SIMD-LABEL: name: call_complex
  ; WASM32-MULTIVAL-SIMD: bb.1 (%ir-block.0):
  ; WASM32-MULTIVAL-SIMD-NEXT:   liveins: $arguments
  ; WASM32-MULTIVAL-SIMD-NEXT: {{  $}}
  ; WASM32-MULTIVAL-SIMD-NEXT:   [[ARGUMENT_v8i16_:%[0-9]+]]:v128(<8 x i16>) = ARGUMENT_v8i16 0, implicit $arguments
  ; WASM32-MULTIVAL-SIMD-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(p0) = ARGUMENT_i32 1, implicit $arguments
  ; WASM32-MULTIVAL-SIMD-NEXT:   [[ARGUMENT_i32_1:%[0-9]+]]:i32(p0) = ARGUMENT_i32 2, implicit $arguments
  ; WASM32-MULTIVAL-SIMD-NEXT:   [[ARGUMENT_i32_2:%[0-9]+]]:i32(p0) = ARGUMENT_i32 3, implicit $arguments
  ; WASM32-MULTIVAL-SIMD-NEXT:   [[ARGUMENT_i32_3:%[0-9]+]]:i32(i32) = ARGUMENT_i32 4, implicit $arguments
  ; WASM32-MULTIVAL-SIMD-NEXT:   [[TRUNC:%[0-9]+]]:_(i1) = G_TRUNC [[ARGUMENT_i32_3]](i32)
  ; WASM32-MULTIVAL-SIMD-NEXT:   [[ANYEXT:%[0-9]+]]:i32(i32) = G_ANYEXT [[TRUNC]](i1)
  ; WASM32-MULTIVAL-SIMD-NEXT:   [[CALL:%[0-9]+]]:i32(i32), [[CALL1:%[0-9]+]]:i32(p0), [[CALL2:%[0-9]+]]:v128(<4 x f32>) = CALL @complex, [[ARGUMENT_v8i16_]](<8 x i16>), [[ARGUMENT_i32_]](p0), [[ARGUMENT_i32_1]](p0), [[ARGUMENT_i32_2]](p0), [[ANYEXT]](i32), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; WASM32-MULTIVAL-SIMD-NEXT:   RETURN [[CALL]](i32), [[CALL1]](p0), [[CALL2]](<4 x f32>), implicit-def $arguments
  ;
  ; WASM64-MULTIVAL-SIMD-LABEL: name: call_complex
  ; WASM64-MULTIVAL-SIMD: bb.1 (%ir-block.0):
  ; WASM64-MULTIVAL-SIMD-NEXT:   liveins: $arguments
  ; WASM64-MULTIVAL-SIMD-NEXT: {{  $}}
  ; WASM64-MULTIVAL-SIMD-NEXT:   [[ARGUMENT_v8i16_:%[0-9]+]]:v128(<8 x i16>) = ARGUMENT_v8i16 0, implicit $arguments
  ; WASM64-MULTIVAL-SIMD-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(p0) = ARGUMENT_i64 1, implicit $arguments
  ; WASM64-MULTIVAL-SIMD-NEXT:   [[ARGUMENT_i64_1:%[0-9]+]]:i64(p0) = ARGUMENT_i64 2, implicit $arguments
  ; WASM64-MULTIVAL-SIMD-NEXT:   [[ARGUMENT_i64_2:%[0-9]+]]:i64(p0) = ARGUMENT_i64 3, implicit $arguments
  ; WASM64-MULTIVAL-SIMD-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(i32) = ARGUMENT_i32 4, implicit $arguments
  ; WASM64-MULTIVAL-SIMD-NEXT:   [[TRUNC:%[0-9]+]]:_(i1) = G_TRUNC [[ARGUMENT_i32_]](i32)
  ; WASM64-MULTIVAL-SIMD-NEXT:   [[ANYEXT:%[0-9]+]]:i32(i32) = G_ANYEXT [[TRUNC]](i1)
  ; WASM64-MULTIVAL-SIMD-NEXT:   [[CALL:%[0-9]+]]:i32(i32), [[CALL1:%[0-9]+]]:i64(p0), [[CALL2:%[0-9]+]]:v128(<4 x f32>) = CALL @complex, [[ARGUMENT_v8i16_]](<8 x i16>), [[ARGUMENT_i64_]](p0), [[ARGUMENT_i64_1]](p0), [[ARGUMENT_i64_2]](p0), [[ANYEXT]](i32), implicit-def $arguments, implicit $sp32, implicit $sp64
  ; WASM64-MULTIVAL-SIMD-NEXT:   RETURN [[CALL]](i32), [[CALL1]](p0), [[CALL2]](<4 x f32>), implicit-def $arguments
  %ret = call %complexret @complex(<8 x i16> %a, [3 x ptr] %b, i1 %c)
  ret %complexret %ret
}
