; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=wasm32 -mattr=-simd128 -global-isel -stop-after=irtranslator < %s | FileCheck %s -check-prefixes=WASM32-NOMULTIVAL
; RUN: llc -mtriple=wasm64 -mattr=-simd128 -global-isel -stop-after=irtranslator < %s | FileCheck %s -check-prefixes=WASM64-NOMULTIVAL
; RUN: llc -mtriple=wasm32 -mattr=-simd128,+multivalue -target-abi=experimental-mv -global-isel -stop-after=irtranslator < %s | FileCheck %s -check-prefixes=MULTIVAL,WASM32-MULTIVAL
; RUN: llc -mtriple=wasm64 -mattr=-simd128,+multivalue -target-abi=experimental-mv -global-isel -stop-after=irtranslator < %s | FileCheck %s -check-prefixes=MULTIVAL,WASM64-MULTIVAL

define i128 @test_ret_i128() {
  ; WASM32-NOMULTIVAL-LABEL: name: test_ret_i128
  ; WASM32-NOMULTIVAL: bb.1 (%ir-block.0):
  ; WASM32-NOMULTIVAL-NEXT:   liveins: $arguments
  ; WASM32-NOMULTIVAL-NEXT: {{  $}}
  ; WASM32-NOMULTIVAL-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(p0) = ARGUMENT_i32 0, implicit $arguments
  ; WASM32-NOMULTIVAL-NEXT:   [[C:%[0-9]+]]:_(i128) = G_CONSTANT i128 0
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[C]](i128), [[ARGUMENT_i32_]](p0) :: (store (i128))
  ; WASM32-NOMULTIVAL-NEXT:   RETURN implicit-def $arguments
  ;
  ; WASM64-NOMULTIVAL-LABEL: name: test_ret_i128
  ; WASM64-NOMULTIVAL: bb.1 (%ir-block.0):
  ; WASM64-NOMULTIVAL-NEXT:   liveins: $arguments
  ; WASM64-NOMULTIVAL-NEXT: {{  $}}
  ; WASM64-NOMULTIVAL-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(p0) = ARGUMENT_i64 0, implicit $arguments
  ; WASM64-NOMULTIVAL-NEXT:   [[C:%[0-9]+]]:_(i128) = G_CONSTANT i128 0
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[C]](i128), [[ARGUMENT_i64_]](p0) :: (store (i128))
  ; WASM64-NOMULTIVAL-NEXT:   RETURN implicit-def $arguments
  ;
  ; MULTIVAL-LABEL: name: test_ret_i128
  ; MULTIVAL: bb.1 (%ir-block.0):
  ; MULTIVAL-NEXT:   liveins: $arguments
  ; MULTIVAL-NEXT: {{  $}}
  ; MULTIVAL-NEXT:   [[C:%[0-9]+]]:_(i128) = G_CONSTANT i128 0
  ; MULTIVAL-NEXT:   [[UV:%[0-9]+]]:i64(i64), [[UV1:%[0-9]+]]:i64(i64) = G_UNMERGE_VALUES [[C]](i128)
  ; MULTIVAL-NEXT:   RETURN [[UV]](i64), [[UV1]](i64), implicit-def $arguments
  ret i128 0
}

define fp128 @test_ret_f128() {
  ; WASM32-NOMULTIVAL-LABEL: name: test_ret_f128
  ; WASM32-NOMULTIVAL: bb.1 (%ir-block.0):
  ; WASM32-NOMULTIVAL-NEXT:   liveins: $arguments
  ; WASM32-NOMULTIVAL-NEXT: {{  $}}
  ; WASM32-NOMULTIVAL-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(p0) = ARGUMENT_i32 0, implicit $arguments
  ; WASM32-NOMULTIVAL-NEXT:   [[C:%[0-9]+]]:_(f128) = G_FCONSTANT fp128 0xL00000000000000000000000000000000
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[C]](f128), [[ARGUMENT_i32_]](p0) :: (store (f128))
  ; WASM32-NOMULTIVAL-NEXT:   RETURN implicit-def $arguments
  ;
  ; WASM64-NOMULTIVAL-LABEL: name: test_ret_f128
  ; WASM64-NOMULTIVAL: bb.1 (%ir-block.0):
  ; WASM64-NOMULTIVAL-NEXT:   liveins: $arguments
  ; WASM64-NOMULTIVAL-NEXT: {{  $}}
  ; WASM64-NOMULTIVAL-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(p0) = ARGUMENT_i64 0, implicit $arguments
  ; WASM64-NOMULTIVAL-NEXT:   [[C:%[0-9]+]]:_(f128) = G_FCONSTANT fp128 0xL00000000000000000000000000000000
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[C]](f128), [[ARGUMENT_i64_]](p0) :: (store (f128))
  ; WASM64-NOMULTIVAL-NEXT:   RETURN implicit-def $arguments
  ;
  ; MULTIVAL-LABEL: name: test_ret_f128
  ; MULTIVAL: bb.1 (%ir-block.0):
  ; MULTIVAL-NEXT:   liveins: $arguments
  ; MULTIVAL-NEXT: {{  $}}
  ; MULTIVAL-NEXT:   [[C:%[0-9]+]]:_(f128) = G_FCONSTANT fp128 0xL00000000000000000000000000000000
  ; MULTIVAL-NEXT:   [[UV:%[0-9]+]]:i64(i64), [[UV1:%[0-9]+]]:i64(i64) = G_UNMERGE_VALUES [[C]](f128)
  ; MULTIVAL-NEXT:   RETURN [[UV]](i64), [[UV1]](i64), implicit-def $arguments
  ret fp128 zeroinitializer
}

define <4 x i32> @test_ret_v4i32() {
  ; WASM32-NOMULTIVAL-LABEL: name: test_ret_v4i32
  ; WASM32-NOMULTIVAL: bb.1 (%ir-block.0):
  ; WASM32-NOMULTIVAL-NEXT:   liveins: $arguments
  ; WASM32-NOMULTIVAL-NEXT: {{  $}}
  ; WASM32-NOMULTIVAL-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(p0) = ARGUMENT_i32 0, implicit $arguments
  ; WASM32-NOMULTIVAL-NEXT:   [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 0
  ; WASM32-NOMULTIVAL-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<4 x i32>) = G_BUILD_VECTOR [[C]](i32), [[C]](i32), [[C]](i32), [[C]](i32)
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[BUILD_VECTOR]](<4 x i32>), [[ARGUMENT_i32_]](p0) :: (store (<4 x i32>))
  ; WASM32-NOMULTIVAL-NEXT:   RETURN implicit-def $arguments
  ;
  ; WASM64-NOMULTIVAL-LABEL: name: test_ret_v4i32
  ; WASM64-NOMULTIVAL: bb.1 (%ir-block.0):
  ; WASM64-NOMULTIVAL-NEXT:   liveins: $arguments
  ; WASM64-NOMULTIVAL-NEXT: {{  $}}
  ; WASM64-NOMULTIVAL-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(p0) = ARGUMENT_i64 0, implicit $arguments
  ; WASM64-NOMULTIVAL-NEXT:   [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 0
  ; WASM64-NOMULTIVAL-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<4 x i32>) = G_BUILD_VECTOR [[C]](i32), [[C]](i32), [[C]](i32), [[C]](i32)
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[BUILD_VECTOR]](<4 x i32>), [[ARGUMENT_i64_]](p0) :: (store (<4 x i32>))
  ; WASM64-NOMULTIVAL-NEXT:   RETURN implicit-def $arguments
  ;
  ; MULTIVAL-LABEL: name: test_ret_v4i32
  ; MULTIVAL: bb.1 (%ir-block.0):
  ; MULTIVAL-NEXT:   liveins: $arguments
  ; MULTIVAL-NEXT: {{  $}}
  ; MULTIVAL-NEXT:   [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 0
  ; MULTIVAL-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<4 x i32>) = G_BUILD_VECTOR [[C]](i32), [[C]](i32), [[C]](i32), [[C]](i32)
  ; MULTIVAL-NEXT:   [[UV:%[0-9]+]]:i32(i32), [[UV1:%[0-9]+]]:i32(i32), [[UV2:%[0-9]+]]:i32(i32), [[UV3:%[0-9]+]]:i32(i32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<4 x i32>)
  ; MULTIVAL-NEXT:   RETURN [[UV]](i32), [[UV1]](i32), [[UV2]](i32), [[UV3]](i32), implicit-def $arguments
  ret <4 x i32> zeroinitializer
}

define [5 x i16] @test_array_arg() {
  ; WASM32-NOMULTIVAL-LABEL: name: test_array_arg
  ; WASM32-NOMULTIVAL: bb.1 (%ir-block.0):
  ; WASM32-NOMULTIVAL-NEXT:   liveins: $arguments
  ; WASM32-NOMULTIVAL-NEXT: {{  $}}
  ; WASM32-NOMULTIVAL-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(p0) = ARGUMENT_i32 0, implicit $arguments
  ; WASM32-NOMULTIVAL-NEXT:   [[C:%[0-9]+]]:_(i16) = G_CONSTANT i16 0
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[C]](i16), [[ARGUMENT_i32_]](p0) :: (store (i16))
  ; WASM32-NOMULTIVAL-NEXT:   [[C1:%[0-9]+]]:_(i32) = G_CONSTANT i32 2
  ; WASM32-NOMULTIVAL-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i32_]], [[C1]](i32)
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[C]](i16), [[PTR_ADD]](p0) :: (store (i16))
  ; WASM32-NOMULTIVAL-NEXT:   [[C2:%[0-9]+]]:_(i32) = G_CONSTANT i32 4
  ; WASM32-NOMULTIVAL-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i32_]], [[C2]](i32)
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[C]](i16), [[PTR_ADD1]](p0) :: (store (i16))
  ; WASM32-NOMULTIVAL-NEXT:   [[C3:%[0-9]+]]:_(i32) = G_CONSTANT i32 6
  ; WASM32-NOMULTIVAL-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i32_]], [[C3]](i32)
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[C]](i16), [[PTR_ADD2]](p0) :: (store (i16))
  ; WASM32-NOMULTIVAL-NEXT:   [[C4:%[0-9]+]]:_(i32) = G_CONSTANT i32 8
  ; WASM32-NOMULTIVAL-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i32_]], [[C4]](i32)
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[C]](i16), [[PTR_ADD3]](p0) :: (store (i16))
  ; WASM32-NOMULTIVAL-NEXT:   RETURN implicit-def $arguments
  ;
  ; WASM64-NOMULTIVAL-LABEL: name: test_array_arg
  ; WASM64-NOMULTIVAL: bb.1 (%ir-block.0):
  ; WASM64-NOMULTIVAL-NEXT:   liveins: $arguments
  ; WASM64-NOMULTIVAL-NEXT: {{  $}}
  ; WASM64-NOMULTIVAL-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(p0) = ARGUMENT_i64 0, implicit $arguments
  ; WASM64-NOMULTIVAL-NEXT:   [[C:%[0-9]+]]:_(i16) = G_CONSTANT i16 0
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[C]](i16), [[ARGUMENT_i64_]](p0) :: (store (i16))
  ; WASM64-NOMULTIVAL-NEXT:   [[C1:%[0-9]+]]:_(i64) = G_CONSTANT i64 2
  ; WASM64-NOMULTIVAL-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i64_]], [[C1]](i64)
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[C]](i16), [[PTR_ADD]](p0) :: (store (i16))
  ; WASM64-NOMULTIVAL-NEXT:   [[C2:%[0-9]+]]:_(i64) = G_CONSTANT i64 4
  ; WASM64-NOMULTIVAL-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i64_]], [[C2]](i64)
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[C]](i16), [[PTR_ADD1]](p0) :: (store (i16))
  ; WASM64-NOMULTIVAL-NEXT:   [[C3:%[0-9]+]]:_(i64) = G_CONSTANT i64 6
  ; WASM64-NOMULTIVAL-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i64_]], [[C3]](i64)
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[C]](i16), [[PTR_ADD2]](p0) :: (store (i16))
  ; WASM64-NOMULTIVAL-NEXT:   [[C4:%[0-9]+]]:_(i64) = G_CONSTANT i64 8
  ; WASM64-NOMULTIVAL-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i64_]], [[C4]](i64)
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[C]](i16), [[PTR_ADD3]](p0) :: (store (i16))
  ; WASM64-NOMULTIVAL-NEXT:   RETURN implicit-def $arguments
  ;
  ; MULTIVAL-LABEL: name: test_array_arg
  ; MULTIVAL: bb.1 (%ir-block.0):
  ; MULTIVAL-NEXT:   liveins: $arguments
  ; MULTIVAL-NEXT: {{  $}}
  ; MULTIVAL-NEXT:   [[C:%[0-9]+]]:_(i16) = G_CONSTANT i16 0
  ; MULTIVAL-NEXT:   [[ANYEXT:%[0-9]+]]:i32(i32) = G_ANYEXT [[C]](i16)
  ; MULTIVAL-NEXT:   [[ANYEXT1:%[0-9]+]]:i32(i32) = G_ANYEXT [[C]](i16)
  ; MULTIVAL-NEXT:   [[ANYEXT2:%[0-9]+]]:i32(i32) = G_ANYEXT [[C]](i16)
  ; MULTIVAL-NEXT:   [[ANYEXT3:%[0-9]+]]:i32(i32) = G_ANYEXT [[C]](i16)
  ; MULTIVAL-NEXT:   [[ANYEXT4:%[0-9]+]]:i32(i32) = G_ANYEXT [[C]](i16)
  ; MULTIVAL-NEXT:   RETURN [[ANYEXT]](i32), [[ANYEXT1]](i32), [[ANYEXT2]](i32), [[ANYEXT3]](i32), [[ANYEXT4]](i32), implicit-def $arguments
  ret [5 x i16] zeroinitializer
}

%StructTy = type { i8, i16, i32, i64, ptr, float, double, i128 }

define %StructTy @test_ret_struct() {
  ; WASM32-NOMULTIVAL-LABEL: name: test_ret_struct
  ; WASM32-NOMULTIVAL: bb.1 (%ir-block.0):
  ; WASM32-NOMULTIVAL-NEXT:   liveins: $arguments
  ; WASM32-NOMULTIVAL-NEXT: {{  $}}
  ; WASM32-NOMULTIVAL-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(p0) = ARGUMENT_i32 0, implicit $arguments
  ; WASM32-NOMULTIVAL-NEXT:   [[C:%[0-9]+]]:_(i8) = G_CONSTANT i8 0
  ; WASM32-NOMULTIVAL-NEXT:   [[C1:%[0-9]+]]:_(i16) = G_CONSTANT i16 0
  ; WASM32-NOMULTIVAL-NEXT:   [[C2:%[0-9]+]]:_(i32) = G_CONSTANT i32 0
  ; WASM32-NOMULTIVAL-NEXT:   [[C3:%[0-9]+]]:_(i64) = G_CONSTANT i64 0
  ; WASM32-NOMULTIVAL-NEXT:   [[C4:%[0-9]+]]:_(p0) = G_CONSTANT i32 0
  ; WASM32-NOMULTIVAL-NEXT:   [[C5:%[0-9]+]]:_(f32) = G_FCONSTANT float 0.000000e+00
  ; WASM32-NOMULTIVAL-NEXT:   [[C6:%[0-9]+]]:_(f64) = G_FCONSTANT double 0.000000e+00
  ; WASM32-NOMULTIVAL-NEXT:   [[C7:%[0-9]+]]:_(i128) = G_CONSTANT i128 0
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[C]](i8), [[ARGUMENT_i32_]](p0) :: (store (i8), align 16)
  ; WASM32-NOMULTIVAL-NEXT:   [[C8:%[0-9]+]]:_(i32) = G_CONSTANT i32 2
  ; WASM32-NOMULTIVAL-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i32_]], [[C8]](i32)
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[C1]](i16), [[PTR_ADD]](p0) :: (store (i16))
  ; WASM32-NOMULTIVAL-NEXT:   [[C9:%[0-9]+]]:_(i32) = G_CONSTANT i32 4
  ; WASM32-NOMULTIVAL-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i32_]], [[C9]](i32)
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[C2]](i32), [[PTR_ADD1]](p0) :: (store (i32))
  ; WASM32-NOMULTIVAL-NEXT:   [[C10:%[0-9]+]]:_(i32) = G_CONSTANT i32 8
  ; WASM32-NOMULTIVAL-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i32_]], [[C10]](i32)
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[C3]](i64), [[PTR_ADD2]](p0) :: (store (i64))
  ; WASM32-NOMULTIVAL-NEXT:   [[C11:%[0-9]+]]:_(i32) = G_CONSTANT i32 16
  ; WASM32-NOMULTIVAL-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i32_]], [[C11]](i32)
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[C4]](p0), [[PTR_ADD3]](p0) :: (store (p0), align 16)
  ; WASM32-NOMULTIVAL-NEXT:   [[C12:%[0-9]+]]:_(i32) = G_CONSTANT i32 20
  ; WASM32-NOMULTIVAL-NEXT:   [[PTR_ADD4:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i32_]], [[C12]](i32)
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[C5]](f32), [[PTR_ADD4]](p0) :: (store (f32))
  ; WASM32-NOMULTIVAL-NEXT:   [[C13:%[0-9]+]]:_(i32) = G_CONSTANT i32 24
  ; WASM32-NOMULTIVAL-NEXT:   [[PTR_ADD5:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i32_]], [[C13]](i32)
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[C6]](f64), [[PTR_ADD5]](p0) :: (store (f64))
  ; WASM32-NOMULTIVAL-NEXT:   [[C14:%[0-9]+]]:_(i32) = G_CONSTANT i32 32
  ; WASM32-NOMULTIVAL-NEXT:   [[PTR_ADD6:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i32_]], [[C14]](i32)
  ; WASM32-NOMULTIVAL-NEXT:   G_STORE [[C7]](i128), [[PTR_ADD6]](p0) :: (store (i128))
  ; WASM32-NOMULTIVAL-NEXT:   RETURN implicit-def $arguments
  ;
  ; WASM64-NOMULTIVAL-LABEL: name: test_ret_struct
  ; WASM64-NOMULTIVAL: bb.1 (%ir-block.0):
  ; WASM64-NOMULTIVAL-NEXT:   liveins: $arguments
  ; WASM64-NOMULTIVAL-NEXT: {{  $}}
  ; WASM64-NOMULTIVAL-NEXT:   [[ARGUMENT_i64_:%[0-9]+]]:i64(p0) = ARGUMENT_i64 0, implicit $arguments
  ; WASM64-NOMULTIVAL-NEXT:   [[C:%[0-9]+]]:_(i8) = G_CONSTANT i8 0
  ; WASM64-NOMULTIVAL-NEXT:   [[C1:%[0-9]+]]:_(i16) = G_CONSTANT i16 0
  ; WASM64-NOMULTIVAL-NEXT:   [[C2:%[0-9]+]]:_(i32) = G_CONSTANT i32 0
  ; WASM64-NOMULTIVAL-NEXT:   [[C3:%[0-9]+]]:_(i64) = G_CONSTANT i64 0
  ; WASM64-NOMULTIVAL-NEXT:   [[C4:%[0-9]+]]:_(p0) = G_CONSTANT i64 0
  ; WASM64-NOMULTIVAL-NEXT:   [[C5:%[0-9]+]]:_(f32) = G_FCONSTANT float 0.000000e+00
  ; WASM64-NOMULTIVAL-NEXT:   [[C6:%[0-9]+]]:_(f64) = G_FCONSTANT double 0.000000e+00
  ; WASM64-NOMULTIVAL-NEXT:   [[C7:%[0-9]+]]:_(i128) = G_CONSTANT i128 0
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[C]](i8), [[ARGUMENT_i64_]](p0) :: (store (i8), align 16)
  ; WASM64-NOMULTIVAL-NEXT:   [[C8:%[0-9]+]]:_(i64) = G_CONSTANT i64 2
  ; WASM64-NOMULTIVAL-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i64_]], [[C8]](i64)
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[C1]](i16), [[PTR_ADD]](p0) :: (store (i16))
  ; WASM64-NOMULTIVAL-NEXT:   [[C9:%[0-9]+]]:_(i64) = G_CONSTANT i64 4
  ; WASM64-NOMULTIVAL-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i64_]], [[C9]](i64)
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[C2]](i32), [[PTR_ADD1]](p0) :: (store (i32))
  ; WASM64-NOMULTIVAL-NEXT:   [[C10:%[0-9]+]]:_(i64) = G_CONSTANT i64 8
  ; WASM64-NOMULTIVAL-NEXT:   [[PTR_ADD2:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i64_]], [[C10]](i64)
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[C3]](i64), [[PTR_ADD2]](p0) :: (store (i64))
  ; WASM64-NOMULTIVAL-NEXT:   [[C11:%[0-9]+]]:_(i64) = G_CONSTANT i64 16
  ; WASM64-NOMULTIVAL-NEXT:   [[PTR_ADD3:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i64_]], [[C11]](i64)
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[C4]](p0), [[PTR_ADD3]](p0) :: (store (p0), align 16)
  ; WASM64-NOMULTIVAL-NEXT:   [[C12:%[0-9]+]]:_(i64) = G_CONSTANT i64 24
  ; WASM64-NOMULTIVAL-NEXT:   [[PTR_ADD4:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i64_]], [[C12]](i64)
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[C5]](f32), [[PTR_ADD4]](p0) :: (store (f32), align 8)
  ; WASM64-NOMULTIVAL-NEXT:   [[C13:%[0-9]+]]:_(i64) = G_CONSTANT i64 32
  ; WASM64-NOMULTIVAL-NEXT:   [[PTR_ADD5:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i64_]], [[C13]](i64)
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[C6]](f64), [[PTR_ADD5]](p0) :: (store (f64), align 16)
  ; WASM64-NOMULTIVAL-NEXT:   [[C14:%[0-9]+]]:_(i64) = G_CONSTANT i64 48
  ; WASM64-NOMULTIVAL-NEXT:   [[PTR_ADD6:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[ARGUMENT_i64_]], [[C14]](i64)
  ; WASM64-NOMULTIVAL-NEXT:   G_STORE [[C7]](i128), [[PTR_ADD6]](p0) :: (store (i128))
  ; WASM64-NOMULTIVAL-NEXT:   RETURN implicit-def $arguments
  ;
  ; WASM32-MULTIVAL-LABEL: name: test_ret_struct
  ; WASM32-MULTIVAL: bb.1 (%ir-block.0):
  ; WASM32-MULTIVAL-NEXT:   liveins: $arguments
  ; WASM32-MULTIVAL-NEXT: {{  $}}
  ; WASM32-MULTIVAL-NEXT:   [[C:%[0-9]+]]:_(i8) = G_CONSTANT i8 0
  ; WASM32-MULTIVAL-NEXT:   [[C1:%[0-9]+]]:_(i16) = G_CONSTANT i16 0
  ; WASM32-MULTIVAL-NEXT:   [[C2:%[0-9]+]]:_(i32) = G_CONSTANT i32 0
  ; WASM32-MULTIVAL-NEXT:   [[C3:%[0-9]+]]:_(i64) = G_CONSTANT i64 0
  ; WASM32-MULTIVAL-NEXT:   [[C4:%[0-9]+]]:_(p0) = G_CONSTANT i32 0
  ; WASM32-MULTIVAL-NEXT:   [[C5:%[0-9]+]]:_(f32) = G_FCONSTANT float 0.000000e+00
  ; WASM32-MULTIVAL-NEXT:   [[C6:%[0-9]+]]:_(f64) = G_FCONSTANT double 0.000000e+00
  ; WASM32-MULTIVAL-NEXT:   [[C7:%[0-9]+]]:_(i128) = G_CONSTANT i128 0
  ; WASM32-MULTIVAL-NEXT:   [[ANYEXT:%[0-9]+]]:i32(i32) = G_ANYEXT [[C]](i8)
  ; WASM32-MULTIVAL-NEXT:   [[ANYEXT1:%[0-9]+]]:i32(i32) = G_ANYEXT [[C1]](i16)
  ; WASM32-MULTIVAL-NEXT:   [[UV:%[0-9]+]]:i64(i64), [[UV1:%[0-9]+]]:i64(i64) = G_UNMERGE_VALUES [[C7]](i128)
  ; WASM32-MULTIVAL-NEXT:   RETURN [[ANYEXT]](i32), [[ANYEXT1]](i32), [[C2]](i32), [[C3]](i64), [[C4]](p0), [[C5]](f32), [[C6]](f64), [[UV]](i64), [[UV1]](i64), implicit-def $arguments
  ;
  ; WASM64-MULTIVAL-LABEL: name: test_ret_struct
  ; WASM64-MULTIVAL: bb.1 (%ir-block.0):
  ; WASM64-MULTIVAL-NEXT:   liveins: $arguments
  ; WASM64-MULTIVAL-NEXT: {{  $}}
  ; WASM64-MULTIVAL-NEXT:   [[C:%[0-9]+]]:_(i8) = G_CONSTANT i8 0
  ; WASM64-MULTIVAL-NEXT:   [[C1:%[0-9]+]]:_(i16) = G_CONSTANT i16 0
  ; WASM64-MULTIVAL-NEXT:   [[C2:%[0-9]+]]:_(i32) = G_CONSTANT i32 0
  ; WASM64-MULTIVAL-NEXT:   [[C3:%[0-9]+]]:_(i64) = G_CONSTANT i64 0
  ; WASM64-MULTIVAL-NEXT:   [[C4:%[0-9]+]]:_(p0) = G_CONSTANT i64 0
  ; WASM64-MULTIVAL-NEXT:   [[C5:%[0-9]+]]:_(f32) = G_FCONSTANT float 0.000000e+00
  ; WASM64-MULTIVAL-NEXT:   [[C6:%[0-9]+]]:_(f64) = G_FCONSTANT double 0.000000e+00
  ; WASM64-MULTIVAL-NEXT:   [[C7:%[0-9]+]]:_(i128) = G_CONSTANT i128 0
  ; WASM64-MULTIVAL-NEXT:   [[ANYEXT:%[0-9]+]]:i32(i32) = G_ANYEXT [[C]](i8)
  ; WASM64-MULTIVAL-NEXT:   [[ANYEXT1:%[0-9]+]]:i32(i32) = G_ANYEXT [[C1]](i16)
  ; WASM64-MULTIVAL-NEXT:   [[UV:%[0-9]+]]:i64(i64), [[UV1:%[0-9]+]]:i64(i64) = G_UNMERGE_VALUES [[C7]](i128)
  ; WASM64-MULTIVAL-NEXT:   RETURN [[ANYEXT]](i32), [[ANYEXT1]](i32), [[C2]](i32), [[C3]](i64), [[C4]](p0), [[C5]](f32), [[C6]](f64), [[UV]](i64), [[UV1]](i64), implicit-def $arguments
  ret %StructTy zeroinitializer
}
