; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=wasm32 -mattr=+simd128 -global-isel -stop-after=irtranslator < %s | FileCheck %s -check-prefixes=CHECK,NO-FP16
; RUN: llc -mtriple=wasm32 -mattr=+fp16,+simd128 -global-isel -stop-after=irtranslator < %s | FileCheck %s -check-prefixes=CHECK,FP16

define <16 x i8> @test_ret_v16i8() {
  ; CHECK-LABEL: name: test_ret_v16i8
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i8) = G_CONSTANT i8 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<16 x i8>) = G_BUILD_VECTOR [[C]](i8), [[C]](i8), [[C]](i8), [[C]](i8), [[C]](i8), [[C]](i8), [[C]](i8), [[C]](i8), [[C]](i8), [[C]](i8), [[C]](i8), [[C]](i8), [[C]](i8), [[C]](i8), [[C]](i8), [[C]](i8)
  ; CHECK-NEXT:   RETURN [[BUILD_VECTOR]](<16 x i8>), implicit-def $arguments
  ret <16 x i8> zeroinitializer
}

define <8 x i16> @test_ret_v8i16() {
  ; CHECK-LABEL: name: test_ret_v8i16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i16) = G_CONSTANT i16 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x i16>) = G_BUILD_VECTOR [[C]](i16), [[C]](i16), [[C]](i16), [[C]](i16), [[C]](i16), [[C]](i16), [[C]](i16), [[C]](i16)
  ; CHECK-NEXT:   RETURN [[BUILD_VECTOR]](<8 x i16>), implicit-def $arguments
  ret <8 x i16> zeroinitializer
}

define <4 x i32> @test_ret_v4i32() {
  ; CHECK-LABEL: name: test_ret_v4i32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<4 x i32>) = G_BUILD_VECTOR [[C]](i32), [[C]](i32), [[C]](i32), [[C]](i32)
  ; CHECK-NEXT:   RETURN [[BUILD_VECTOR]](<4 x i32>), implicit-def $arguments
  ret <4 x i32> zeroinitializer
}

define <2 x i64> @test_ret_v2i64() {
  ; CHECK-LABEL: name: test_ret_v2i64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<2 x i64>) = G_BUILD_VECTOR [[C]](i64), [[C]](i64)
  ; CHECK-NEXT:   RETURN [[BUILD_VECTOR]](<2 x i64>), implicit-def $arguments
  ret <2 x i64> zeroinitializer
}

define <8 x half> @test_ret_v8f16() {
  ; NO-FP16-LABEL: name: test_ret_v8f16
  ; NO-FP16: bb.1 (%ir-block.0):
  ; NO-FP16-NEXT:   liveins: $arguments
  ; NO-FP16-NEXT: {{  $}}
  ; NO-FP16-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32(p0) = ARGUMENT_i32 0, implicit $arguments
  ; NO-FP16-NEXT:   [[C:%[0-9]+]]:_(f16) = G_FCONSTANT half 0xH0000
  ; NO-FP16-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x f16>) = G_BUILD_VECTOR [[C]](f16), [[C]](f16), [[C]](f16), [[C]](f16), [[C]](f16), [[C]](f16), [[C]](f16), [[C]](f16)
  ; NO-FP16-NEXT:   G_STORE [[BUILD_VECTOR]](<8 x f16>), [[ARGUMENT_i32_]](p0) :: (store (<8 x f16>))
  ; NO-FP16-NEXT:   RETURN implicit-def $arguments
  ;
  ; FP16-LABEL: name: test_ret_v8f16
  ; FP16: bb.1 (%ir-block.0):
  ; FP16-NEXT:   liveins: $arguments
  ; FP16-NEXT: {{  $}}
  ; FP16-NEXT:   [[C:%[0-9]+]]:_(f16) = G_FCONSTANT half 0xH0000
  ; FP16-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x f16>) = G_BUILD_VECTOR [[C]](f16), [[C]](f16), [[C]](f16), [[C]](f16), [[C]](f16), [[C]](f16), [[C]](f16), [[C]](f16)
  ; FP16-NEXT:   RETURN [[BUILD_VECTOR]](<8 x f16>), implicit-def $arguments
  ret <8 x half> zeroinitializer
}

define <4 x float> @test_ret_v4f32() {
  ; CHECK-LABEL: name: test_ret_v4f32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(f32) = G_FCONSTANT float 0.000000e+00
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<4 x f32>) = G_BUILD_VECTOR [[C]](f32), [[C]](f32), [[C]](f32), [[C]](f32)
  ; CHECK-NEXT:   RETURN [[BUILD_VECTOR]](<4 x f32>), implicit-def $arguments
  ret <4 x float> zeroinitializer
}

define <2 x double> @test_ret_v2f64() {
  ; CHECK-LABEL: name: test_ret_v2f64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(f64) = G_FCONSTANT double 0.000000e+00
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<2 x f64>) = G_BUILD_VECTOR [[C]](f64), [[C]](f64)
  ; CHECK-NEXT:   RETURN [[BUILD_VECTOR]](<2 x f64>), implicit-def $arguments
  ret <2 x double> zeroinitializer
}
