; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=wasm32 -global-isel -stop-after=irtranslator < %s | FileCheck %s -check-prefixes=CHECK,WASM32
; RUN: llc -mtriple=wasm64 -global-isel -stop-after=irtranslator < %s | FileCheck %s -check-prefixes=CHECK,WASM64

define void @test_ret_void() {
  ; CHECK-LABEL: name: test_ret_void
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   RETURN implicit-def $arguments
  ret void
}

define i8 @test_ret_i8() {
  ; CHECK-LABEL: name: test_ret_i8
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i8) = G_CONSTANT i8 0
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:i32(i32) = G_ANYEXT [[C]](i8)
  ; CHECK-NEXT:   RETURN [[ANYEXT]](i32), implicit-def $arguments
  ret i8 0
}

define zeroext i8 @test_ret_i8_zeroext() {
  ; CHECK-LABEL: name: test_ret_i8_zeroext
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i8) = G_CONSTANT i8 -1
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:i32(i32) = G_ZEXT [[C]](i8)
  ; CHECK-NEXT:   RETURN [[ZEXT]](i32), implicit-def $arguments
  ret i8 -1
}

define signext i8 @test_ret_i8_signext() {
  ; CHECK-LABEL: name: test_ret_i8_signext
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i8) = G_CONSTANT i8 -1
  ; CHECK-NEXT:   [[SEXT:%[0-9]+]]:i32(i32) = G_SEXT [[C]](i8)
  ; CHECK-NEXT:   RETURN [[SEXT]](i32), implicit-def $arguments
  ret i8 -1
}


define i16 @test_ret_i16() {
  ; CHECK-LABEL: name: test_ret_i16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i16) = G_CONSTANT i16 0
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:i32(i32) = G_ANYEXT [[C]](i16)
  ; CHECK-NEXT:   RETURN [[ANYEXT]](i32), implicit-def $arguments
  ret i16 0
}

define i32 @test_ret_i32() {
  ; CHECK-LABEL: name: test_ret_i32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   RETURN [[C]](i32), implicit-def $arguments
  ret i32 0
}

define i64 @test_ret_i64() {
  ; CHECK-LABEL: name: test_ret_i64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 0
  ; CHECK-NEXT:   RETURN [[C]](i64), implicit-def $arguments
  ret i64 0
}

define ptr @test_ret_ptr() {
  ; WASM32-LABEL: name: test_ret_ptr
  ; WASM32: bb.1 (%ir-block.0):
  ; WASM32-NEXT:   liveins: $arguments
  ; WASM32-NEXT: {{  $}}
  ; WASM32-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i32 0
  ; WASM32-NEXT:   RETURN [[C]](p0), implicit-def $arguments
  ;
  ; WASM64-LABEL: name: test_ret_ptr
  ; WASM64: bb.1 (%ir-block.0):
  ; WASM64-NEXT:   liveins: $arguments
  ; WASM64-NEXT: {{  $}}
  ; WASM64-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i64 0
  ; WASM64-NEXT:   RETURN [[C]](p0), implicit-def $arguments
  ret ptr null
}

define half @test_ret_f16() {
  ; CHECK-LABEL: name: test_ret_f16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(f16) = G_FCONSTANT half 0.000000e+00
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:i32(i32) = G_ANYEXT [[C]](f16)
  ; CHECK-NEXT:   RETURN [[ANYEXT]](i32), implicit-def $arguments
  ret half 0.0
}

define float @test_ret_f32() {
  ; CHECK-LABEL: name: test_ret_f32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(f32) = G_FCONSTANT float 0.000000e+00
  ; CHECK-NEXT:   RETURN [[C]](f32), implicit-def $arguments
  ret float 0.0
}

define double @test_ret_f64() {
  ; CHECK-LABEL: name: test_ret_f64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(f64) = G_FCONSTANT double 0.000000e+00
  ; CHECK-NEXT:   RETURN [[C]](f64), implicit-def $arguments
  ret double 0.0
}

%externref = type ptr addrspace(10)
define %externref @test_ret_externref() {
  ; CHECK-LABEL: name: test_ret_externref
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.ref_ptr
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(p10) = G_LOAD [[FRAME_INDEX]](p0) :: (load (p10) from %ir.ref_ptr)
  ; CHECK-NEXT:   RETURN [[LOAD]](p10), implicit-def $arguments
  %ref_ptr = alloca %externref
  %ref = load %externref, ptr %ref_ptr
  ret %externref %ref
}

%funcref = type ptr addrspace(20)
define %funcref @test_ret_funcref() {
  ; CHECK-LABEL: name: test_ret_funcref
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.ref_ptr
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(p20) = G_LOAD [[FRAME_INDEX]](p0) :: (load (p20) from %ir.ref_ptr)
  ; CHECK-NEXT:   RETURN [[LOAD]](p20), implicit-def $arguments
  %ref_ptr = alloca %funcref
  %ref = load %funcref, ptr %ref_ptr
  ret %funcref %ref
}
