; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -S -passes=lowertypetests -lowertypetests-summary-action=import -lowertypetests-read-summary=%S/Inputs/import.yaml %s | FileCheck %s

target datalayout = "e-p:64:64"
target triple = "x86_64-unknown-linux"

define void @allones7(ptr %p) {
; CHECK-LABEL: define void @allones7(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[P]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = sub i64 ptrtoint (ptr @__typeid_allones7_global_addr to i64), [[TMP1]]
; CHECK-NEXT:    [[TMP7:%.*]] = call i64 @llvm.fshr.i64(i64 [[TMP2]], i64 [[TMP2]], i64 ptrtoint (ptr @__typeid_allones7_align to i64))
; CHECK-NEXT:    [[TMP8:%.*]] = icmp ule i64 [[TMP7]], ptrtoint (ptr @__typeid_allones7_size_m1 to i64)
; CHECK-NEXT:    [[NOT:%.*]] = xor i1 [[TMP8]], true
; CHECK-NEXT:    call void @llvm.cond.loop(i1 [[NOT]])
; CHECK-NEXT:    ret void
;
  %x = call i1 @llvm.type.test(ptr %p, metadata !"allones7")
  %not = xor i1 %x, true
  call void @llvm.cond.loop(i1 %not)
  ret void
}

define void @bytearray7(ptr %p) {
; CHECK-LABEL: define void @bytearray7(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[P]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = sub i64 ptrtoint (ptr @__typeid_bytearray7_global_addr to i64), [[TMP1]]
; CHECK-NEXT:    [[TMP7:%.*]] = call i64 @llvm.fshr.i64(i64 [[TMP2]], i64 [[TMP2]], i64 ptrtoint (ptr @__typeid_bytearray7_align to i64))
; CHECK-NEXT:    [[TMP8:%.*]] = icmp ule i64 [[TMP7]], ptrtoint (ptr @__typeid_bytearray7_size_m1 to i64)
; CHECK-NEXT:    [[TMP5:%.*]] = xor i1 [[TMP8]], true
; CHECK-NEXT:    call void @llvm.cond.loop(i1 [[TMP5]])
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr @__typeid_bytearray7_byte_array, i64 [[TMP7]]
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[TMP10]], align 1
; CHECK-NEXT:    [[TMP12:%.*]] = and i8 [[TMP11]], ptrtoint (ptr @__typeid_bytearray7_bit_mask to i8)
; CHECK-NEXT:    [[TMP13:%.*]] = icmp ne i8 [[TMP12]], 0
; CHECK-NEXT:    [[NOT:%.*]] = xor i1 [[TMP13]], true
; CHECK-NEXT:    call void @llvm.cond.loop(i1 [[NOT]])
; CHECK-NEXT:    ret void
;
  %x = call i1 @llvm.type.test(ptr %p, metadata !"bytearray7")
  %not = xor i1 %x, true
  call void @llvm.cond.loop(i1 %not)
  ret void
}
