// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +zve64x -target-feature +zvfbfmin -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:   opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefixes=CHECK-RV64,CHECK-RV64-OGCG %s
// RUN: %if cir-enabled %{%clang_cc1 -triple riscv64 -target-feature +zve64x -target-feature +zvfbfmin -disable-O0-optnone -emit-llvm -fclangir %s -o - | \
// RUN:   opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s %}
// RUN: %if cir-enabled %{%clang_cc1 -triple riscv64 -target-feature +zve64x -target-feature +zvfbfmin -disable-O0-optnone -emit-cir -fclangir %s -o - | \
// RUN:   FileCheck --check-prefix=CIR %s %}

#include <riscv_vector.h>

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16mf4_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei" {{%.*}} : (!cir.vector<[1] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[1] x !u8i>, !u64i) -> !cir.vector<[1] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x bfloat> @test_vloxei8_v_bf16mf4_tu(
// CHECK-RV64-SAME: <vscale x 1 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 1 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x bfloat> @llvm.riscv.vloxei.nxv1bf16.p0.nxv1i8.i64(<vscale x 1 x bfloat> [[VD]], ptr [[RS1]], <vscale x 1 x i8> [[RS2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x bfloat> [[TMP0]]
//
vbfloat16mf4_t test_vloxei8_v_bf16mf4_tu(vbfloat16mf4_t vd, const __bf16 *rs1, vuint8mf8_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16mf4_tu(vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16mf2_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei" {{%.*}} : (!cir.vector<[2] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[2] x !u8i>, !u64i) -> !cir.vector<[2] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x bfloat> @test_vloxei8_v_bf16mf2_tu(
// CHECK-RV64-SAME: <vscale x 2 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 2 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x bfloat> @llvm.riscv.vloxei.nxv2bf16.p0.nxv2i8.i64(<vscale x 2 x bfloat> [[VD]], ptr [[RS1]], <vscale x 2 x i8> [[RS2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x bfloat> [[TMP0]]
//
vbfloat16mf2_t test_vloxei8_v_bf16mf2_tu(vbfloat16mf2_t vd, const __bf16 *rs1, vuint8mf4_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16mf2_tu(vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei" {{%.*}} : (!cir.vector<[4] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[4] x !u8i>, !u64i) -> !cir.vector<[4] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x bfloat> @test_vloxei8_v_bf16m1_tu(
// CHECK-RV64-SAME: <vscale x 4 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 4 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x bfloat> @llvm.riscv.vloxei.nxv4bf16.p0.nxv4i8.i64(<vscale x 4 x bfloat> [[VD]], ptr [[RS1]], <vscale x 4 x i8> [[RS2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x bfloat> [[TMP0]]
//
vbfloat16m1_t test_vloxei8_v_bf16m1_tu(vbfloat16m1_t vd, const __bf16 *rs1, vuint8mf2_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m1_tu(vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m2_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei" {{%.*}} : (!cir.vector<[8] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[8] x !u8i>, !u64i) -> !cir.vector<[8] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x bfloat> @test_vloxei8_v_bf16m2_tu(
// CHECK-RV64-SAME: <vscale x 8 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 8 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x bfloat> @llvm.riscv.vloxei.nxv8bf16.p0.nxv8i8.i64(<vscale x 8 x bfloat> [[VD]], ptr [[RS1]], <vscale x 8 x i8> [[RS2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x bfloat> [[TMP0]]
//
vbfloat16m2_t test_vloxei8_v_bf16m2_tu(vbfloat16m2_t vd, const __bf16 *rs1, vuint8m1_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m2_tu(vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m4_tu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei" {{%.*}} : (!cir.vector<[16] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[16] x !u8i>, !u64i) -> !cir.vector<[16] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x bfloat> @test_vloxei8_v_bf16m4_tu(
// CHECK-RV64-SAME: <vscale x 16 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 16 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x bfloat> @llvm.riscv.vloxei.nxv16bf16.p0.nxv16i8.i64(<vscale x 16 x bfloat> [[VD]], ptr [[RS1]], <vscale x 16 x i8> [[RS2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x bfloat> [[TMP0]]
//
vbfloat16m4_t test_vloxei8_v_bf16m4_tu(vbfloat16m4_t vd, const __bf16 *rs1, vuint8m2_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m4_tu(vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m8_tu(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei" {{%.*}} : (!cir.vector<[32] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[32] x !u8i>, !u64i) -> !cir.vector<[32] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x bfloat> @test_vloxei8_v_bf16m8_tu(
// CHECK-RV64-SAME: <vscale x 32 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 32 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x bfloat> @llvm.riscv.vloxei.nxv32bf16.p0.nxv32i8.i64(<vscale x 32 x bfloat> [[VD]], ptr [[RS1]], <vscale x 32 x i8> [[RS2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x bfloat> [[TMP0]]
//
vbfloat16m8_t test_vloxei8_v_bf16m8_tu(vbfloat16m8_t vd, const __bf16 *rs1, vuint8m4_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m8_tu(vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16mf4_tum(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[1] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[1] x !u8i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x bfloat> @test_vloxei8_v_bf16mf4_tum(
// CHECK-RV64-SAME: <vscale x 1 x i1> [[VM:%.*]], <vscale x 1 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 1 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x bfloat> @llvm.riscv.vloxei.mask.nxv1bf16.p0.nxv1i8.i64(<vscale x 1 x bfloat> [[VD]], ptr [[RS1]], <vscale x 1 x i8> [[RS2]], <vscale x 1 x i1> [[VM]], i64 [[VL]], i64 2)
// CHECK-RV64-NEXT:    ret <vscale x 1 x bfloat> [[TMP0]]
//
vbfloat16mf4_t test_vloxei8_v_bf16mf4_tum(vbool64_t vm, vbfloat16mf4_t vd, const __bf16 *rs1, vuint8mf8_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16mf4_tum(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16mf2_tum(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[2] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[2] x !u8i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x bfloat> @test_vloxei8_v_bf16mf2_tum(
// CHECK-RV64-SAME: <vscale x 2 x i1> [[VM:%.*]], <vscale x 2 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 2 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x bfloat> @llvm.riscv.vloxei.mask.nxv2bf16.p0.nxv2i8.i64(<vscale x 2 x bfloat> [[VD]], ptr [[RS1]], <vscale x 2 x i8> [[RS2]], <vscale x 2 x i1> [[VM]], i64 [[VL]], i64 2)
// CHECK-RV64-NEXT:    ret <vscale x 2 x bfloat> [[TMP0]]
//
vbfloat16mf2_t test_vloxei8_v_bf16mf2_tum(vbool32_t vm, vbfloat16mf2_t vd, const __bf16 *rs1, vuint8mf4_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16mf2_tum(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m1_tum(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[4] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[4] x !u8i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x bfloat> @test_vloxei8_v_bf16m1_tum(
// CHECK-RV64-SAME: <vscale x 4 x i1> [[VM:%.*]], <vscale x 4 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 4 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x bfloat> @llvm.riscv.vloxei.mask.nxv4bf16.p0.nxv4i8.i64(<vscale x 4 x bfloat> [[VD]], ptr [[RS1]], <vscale x 4 x i8> [[RS2]], <vscale x 4 x i1> [[VM]], i64 [[VL]], i64 2)
// CHECK-RV64-NEXT:    ret <vscale x 4 x bfloat> [[TMP0]]
//
vbfloat16m1_t test_vloxei8_v_bf16m1_tum(vbool16_t vm, vbfloat16m1_t vd, const __bf16 *rs1, vuint8mf2_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m1_tum(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m2_tum(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[8] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[8] x !u8i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x bfloat> @test_vloxei8_v_bf16m2_tum(
// CHECK-RV64-SAME: <vscale x 8 x i1> [[VM:%.*]], <vscale x 8 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 8 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x bfloat> @llvm.riscv.vloxei.mask.nxv8bf16.p0.nxv8i8.i64(<vscale x 8 x bfloat> [[VD]], ptr [[RS1]], <vscale x 8 x i8> [[RS2]], <vscale x 8 x i1> [[VM]], i64 [[VL]], i64 2)
// CHECK-RV64-NEXT:    ret <vscale x 8 x bfloat> [[TMP0]]
//
vbfloat16m2_t test_vloxei8_v_bf16m2_tum(vbool8_t vm, vbfloat16m2_t vd, const __bf16 *rs1, vuint8m1_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m2_tum(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m4_tum(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[16] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[16] x !u8i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[16] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x bfloat> @test_vloxei8_v_bf16m4_tum(
// CHECK-RV64-SAME: <vscale x 16 x i1> [[VM:%.*]], <vscale x 16 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 16 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x bfloat> @llvm.riscv.vloxei.mask.nxv16bf16.p0.nxv16i8.i64(<vscale x 16 x bfloat> [[VD]], ptr [[RS1]], <vscale x 16 x i8> [[RS2]], <vscale x 16 x i1> [[VM]], i64 [[VL]], i64 2)
// CHECK-RV64-NEXT:    ret <vscale x 16 x bfloat> [[TMP0]]
//
vbfloat16m4_t test_vloxei8_v_bf16m4_tum(vbool4_t vm, vbfloat16m4_t vd, const __bf16 *rs1, vuint8m2_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m4_tum(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m8_tum(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[32] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[32] x !u8i>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[32] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x bfloat> @test_vloxei8_v_bf16m8_tum(
// CHECK-RV64-SAME: <vscale x 32 x i1> [[VM:%.*]], <vscale x 32 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 32 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x bfloat> @llvm.riscv.vloxei.mask.nxv32bf16.p0.nxv32i8.i64(<vscale x 32 x bfloat> [[VD]], ptr [[RS1]], <vscale x 32 x i8> [[RS2]], <vscale x 32 x i1> [[VM]], i64 [[VL]], i64 2)
// CHECK-RV64-NEXT:    ret <vscale x 32 x bfloat> [[TMP0]]
//
vbfloat16m8_t test_vloxei8_v_bf16m8_tum(vbool2_t vm, vbfloat16m8_t vd, const __bf16 *rs1, vuint8m4_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m8_tum(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16mf4_tumu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[1] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[1] x !u8i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x bfloat> @test_vloxei8_v_bf16mf4_tumu(
// CHECK-RV64-SAME: <vscale x 1 x i1> [[VM:%.*]], <vscale x 1 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 1 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x bfloat> @llvm.riscv.vloxei.mask.nxv1bf16.p0.nxv1i8.i64(<vscale x 1 x bfloat> [[VD]], ptr [[RS1]], <vscale x 1 x i8> [[RS2]], <vscale x 1 x i1> [[VM]], i64 [[VL]], i64 0)
// CHECK-RV64-NEXT:    ret <vscale x 1 x bfloat> [[TMP0]]
//
vbfloat16mf4_t test_vloxei8_v_bf16mf4_tumu(vbool64_t vm, vbfloat16mf4_t vd, const __bf16 *rs1, vuint8mf8_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16mf4_tumu(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16mf2_tumu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[2] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[2] x !u8i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x bfloat> @test_vloxei8_v_bf16mf2_tumu(
// CHECK-RV64-SAME: <vscale x 2 x i1> [[VM:%.*]], <vscale x 2 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 2 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x bfloat> @llvm.riscv.vloxei.mask.nxv2bf16.p0.nxv2i8.i64(<vscale x 2 x bfloat> [[VD]], ptr [[RS1]], <vscale x 2 x i8> [[RS2]], <vscale x 2 x i1> [[VM]], i64 [[VL]], i64 0)
// CHECK-RV64-NEXT:    ret <vscale x 2 x bfloat> [[TMP0]]
//
vbfloat16mf2_t test_vloxei8_v_bf16mf2_tumu(vbool32_t vm, vbfloat16mf2_t vd, const __bf16 *rs1, vuint8mf4_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16mf2_tumu(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m1_tumu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[4] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[4] x !u8i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x bfloat> @test_vloxei8_v_bf16m1_tumu(
// CHECK-RV64-SAME: <vscale x 4 x i1> [[VM:%.*]], <vscale x 4 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 4 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x bfloat> @llvm.riscv.vloxei.mask.nxv4bf16.p0.nxv4i8.i64(<vscale x 4 x bfloat> [[VD]], ptr [[RS1]], <vscale x 4 x i8> [[RS2]], <vscale x 4 x i1> [[VM]], i64 [[VL]], i64 0)
// CHECK-RV64-NEXT:    ret <vscale x 4 x bfloat> [[TMP0]]
//
vbfloat16m1_t test_vloxei8_v_bf16m1_tumu(vbool16_t vm, vbfloat16m1_t vd, const __bf16 *rs1, vuint8mf2_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m1_tumu(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m2_tumu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[8] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[8] x !u8i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x bfloat> @test_vloxei8_v_bf16m2_tumu(
// CHECK-RV64-SAME: <vscale x 8 x i1> [[VM:%.*]], <vscale x 8 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 8 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x bfloat> @llvm.riscv.vloxei.mask.nxv8bf16.p0.nxv8i8.i64(<vscale x 8 x bfloat> [[VD]], ptr [[RS1]], <vscale x 8 x i8> [[RS2]], <vscale x 8 x i1> [[VM]], i64 [[VL]], i64 0)
// CHECK-RV64-NEXT:    ret <vscale x 8 x bfloat> [[TMP0]]
//
vbfloat16m2_t test_vloxei8_v_bf16m2_tumu(vbool8_t vm, vbfloat16m2_t vd, const __bf16 *rs1, vuint8m1_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m2_tumu(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m4_tumu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[16] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[16] x !u8i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[16] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x bfloat> @test_vloxei8_v_bf16m4_tumu(
// CHECK-RV64-SAME: <vscale x 16 x i1> [[VM:%.*]], <vscale x 16 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 16 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x bfloat> @llvm.riscv.vloxei.mask.nxv16bf16.p0.nxv16i8.i64(<vscale x 16 x bfloat> [[VD]], ptr [[RS1]], <vscale x 16 x i8> [[RS2]], <vscale x 16 x i1> [[VM]], i64 [[VL]], i64 0)
// CHECK-RV64-NEXT:    ret <vscale x 16 x bfloat> [[TMP0]]
//
vbfloat16m4_t test_vloxei8_v_bf16m4_tumu(vbool4_t vm, vbfloat16m4_t vd, const __bf16 *rs1, vuint8m2_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m4_tumu(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m8_tumu(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[32] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[32] x !u8i>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[32] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x bfloat> @test_vloxei8_v_bf16m8_tumu(
// CHECK-RV64-SAME: <vscale x 32 x i1> [[VM:%.*]], <vscale x 32 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 32 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x bfloat> @llvm.riscv.vloxei.mask.nxv32bf16.p0.nxv32i8.i64(<vscale x 32 x bfloat> [[VD]], ptr [[RS1]], <vscale x 32 x i8> [[RS2]], <vscale x 32 x i1> [[VM]], i64 [[VL]], i64 0)
// CHECK-RV64-NEXT:    ret <vscale x 32 x bfloat> [[TMP0]]
//
vbfloat16m8_t test_vloxei8_v_bf16m8_tumu(vbool2_t vm, vbfloat16m8_t vd, const __bf16 *rs1, vuint8m4_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m8_tumu(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16mf4_mu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[1] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[1] x !u8i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x bfloat> @test_vloxei8_v_bf16mf4_mu(
// CHECK-RV64-SAME: <vscale x 1 x i1> [[VM:%.*]], <vscale x 1 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 1 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x bfloat> @llvm.riscv.vloxei.mask.nxv1bf16.p0.nxv1i8.i64(<vscale x 1 x bfloat> [[VD]], ptr [[RS1]], <vscale x 1 x i8> [[RS2]], <vscale x 1 x i1> [[VM]], i64 [[VL]], i64 1)
// CHECK-RV64-NEXT:    ret <vscale x 1 x bfloat> [[TMP0]]
//
vbfloat16mf4_t test_vloxei8_v_bf16mf4_mu(vbool64_t vm, vbfloat16mf4_t vd, const __bf16 *rs1, vuint8mf8_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16mf4_mu(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16mf2_mu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[2] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[2] x !u8i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x bfloat> @test_vloxei8_v_bf16mf2_mu(
// CHECK-RV64-SAME: <vscale x 2 x i1> [[VM:%.*]], <vscale x 2 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 2 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x bfloat> @llvm.riscv.vloxei.mask.nxv2bf16.p0.nxv2i8.i64(<vscale x 2 x bfloat> [[VD]], ptr [[RS1]], <vscale x 2 x i8> [[RS2]], <vscale x 2 x i1> [[VM]], i64 [[VL]], i64 1)
// CHECK-RV64-NEXT:    ret <vscale x 2 x bfloat> [[TMP0]]
//
vbfloat16mf2_t test_vloxei8_v_bf16mf2_mu(vbool32_t vm, vbfloat16mf2_t vd, const __bf16 *rs1, vuint8mf4_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16mf2_mu(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m1_mu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[4] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[4] x !u8i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x bfloat> @test_vloxei8_v_bf16m1_mu(
// CHECK-RV64-SAME: <vscale x 4 x i1> [[VM:%.*]], <vscale x 4 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 4 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x bfloat> @llvm.riscv.vloxei.mask.nxv4bf16.p0.nxv4i8.i64(<vscale x 4 x bfloat> [[VD]], ptr [[RS1]], <vscale x 4 x i8> [[RS2]], <vscale x 4 x i1> [[VM]], i64 [[VL]], i64 1)
// CHECK-RV64-NEXT:    ret <vscale x 4 x bfloat> [[TMP0]]
//
vbfloat16m1_t test_vloxei8_v_bf16m1_mu(vbool16_t vm, vbfloat16m1_t vd, const __bf16 *rs1, vuint8mf2_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m1_mu(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m2_mu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[8] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[8] x !u8i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x bfloat> @test_vloxei8_v_bf16m2_mu(
// CHECK-RV64-SAME: <vscale x 8 x i1> [[VM:%.*]], <vscale x 8 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 8 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x bfloat> @llvm.riscv.vloxei.mask.nxv8bf16.p0.nxv8i8.i64(<vscale x 8 x bfloat> [[VD]], ptr [[RS1]], <vscale x 8 x i8> [[RS2]], <vscale x 8 x i1> [[VM]], i64 [[VL]], i64 1)
// CHECK-RV64-NEXT:    ret <vscale x 8 x bfloat> [[TMP0]]
//
vbfloat16m2_t test_vloxei8_v_bf16m2_mu(vbool8_t vm, vbfloat16m2_t vd, const __bf16 *rs1, vuint8m1_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m2_mu(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m4_mu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[16] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[16] x !u8i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[16] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x bfloat> @test_vloxei8_v_bf16m4_mu(
// CHECK-RV64-SAME: <vscale x 16 x i1> [[VM:%.*]], <vscale x 16 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 16 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x bfloat> @llvm.riscv.vloxei.mask.nxv16bf16.p0.nxv16i8.i64(<vscale x 16 x bfloat> [[VD]], ptr [[RS1]], <vscale x 16 x i8> [[RS2]], <vscale x 16 x i1> [[VM]], i64 [[VL]], i64 1)
// CHECK-RV64-NEXT:    ret <vscale x 16 x bfloat> [[TMP0]]
//
vbfloat16m4_t test_vloxei8_v_bf16m4_mu(vbool4_t vm, vbfloat16m4_t vd, const __bf16 *rs1, vuint8m2_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m4_mu(vm, vd, rs1, rs2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vloxei8_v_bf16m8_mu(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vloxei.mask" {{%.*}} : (!cir.vector<[32] x !cir.bf16>, !cir.ptr<!cir.bf16>, !cir.vector<[32] x !u8i>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[32] x !cir.bf16>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x bfloat> @test_vloxei8_v_bf16m8_mu(
// CHECK-RV64-SAME: <vscale x 32 x i1> [[VM:%.*]], <vscale x 32 x bfloat> [[VD:%.*]], ptr noundef [[RS1:%.*]], <vscale x 32 x i8> [[RS2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x bfloat> @llvm.riscv.vloxei.mask.nxv32bf16.p0.nxv32i8.i64(<vscale x 32 x bfloat> [[VD]], ptr [[RS1]], <vscale x 32 x i8> [[RS2]], <vscale x 32 x i1> [[VM]], i64 [[VL]], i64 1)
// CHECK-RV64-NEXT:    ret <vscale x 32 x bfloat> [[TMP0]]
//
vbfloat16m8_t test_vloxei8_v_bf16m8_mu(vbool2_t vm, vbfloat16m8_t vd, const __bf16 *rs1, vuint8m4_t rs2, size_t vl) {
  return __riscv_vloxei8_v_bf16m8_mu(vm, vd, rs1, rs2, vl);
}
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-RV64: {{.*}}
