; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-attributes --include-generated-funcs
; RUN: opt -S -passes=next-silicon-ir-fixup < %s | FileCheck %s

define dso_local i32 @main(i32 noundef %0, ptr noundef %1) {
  %call1 = call i32 @f90io_ldra(ptr null, ptr null, ptr null, ptr null)
  %call2 = call i32 @f90io_sc_ch_ldw(ptr null, i32 0, i64 0)
  %call3 = call i32 @f90_str_index_klen(ptr null, ptr null, i64 0, i64 0)
  %call4 = call i32 @__fenv_fegetenv(ptr null)
  call void @f90_set_intrin_type_i8(ptr null, i32 0)
  %call6 = call i64 @__fort_time()
  ret i32 0
}

declare i32 @f90io_ldra(...)

declare i32 @f90io_sc_ch_ldw(...)

declare i64 @f90_str_index_klen(...)

declare signext i32 @__fenv_fegetenv(...)

declare void @f90_set_intrin_type_i8(...)

declare i32 @__fort_time()

; CHECK-LABEL: @main(
; CHECK-NEXT:    [[CALL1:%.*]] = call i32 @f90io_ldra(ptr null, ptr null, ptr null, ptr null, i64 0)
; CHECK-NEXT:    [[CALL2:%.*]] = call i32 @f90io_sc_ch_ldw(ptr null, i32 0, i32 0)
; CHECK-NEXT:    [[TMP3:%.*]] = call i64 @f90_str_index_klen(ptr null, ptr null, i64 0, i64 0)
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
; CHECK-NEXT:    [[CALL4:%.*]] = call signext i32 @__fenv_fegetenv(ptr null)
; CHECK-NEXT:    call void @f90_set_intrin_type_i8(ptr null, i64 0)
; CHECK-NEXT:    [[TMP5:%.*]] = call i32 @__fort_time()
; CHECK-NEXT:    [[TMP6:%.*]] = sext i32 [[TMP5]] to i64
; CHECK-NEXT:    ret i32 0
;
