; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --include-generated-funcs --version 5
; RUN: opt -S -passes=mergefunc < %s | FileCheck %s
; RUN: opt -S -passes=mergefunc -mergefunc-use-aliases < %s | FileCheck %s --check-prefix=ALIAS

define internal i32 @basic_a(i32 %x) !prof !1 {
entry:
  %add = add nsw i32 %x, 1
  ret i32 %add
}

define internal i32 @basic_b(i32 %x) !prof !1 {
entry:
  %add = add nsw i32 %x, 1
  ret i32 %add
}

define internal i32 @asym_a(i32 %x) !prof !2 {
entry:
  %add = add nsw i32 %x, 2
  ret i32 %add
}

define internal i32 @asym_b(i32 %x) !prof !3 {
entry:
  %add = add nsw i32 %x, 2
  ret i32 %add
}

define internal i32 @onesided_a(i32 %x) {
entry:
  %add = add nsw i32 %x, 3
  ret i32 %add
}

define internal i32 @onesided_b(i32 %x) !prof !4 {
entry:
  %add = add nsw i32 %x, 3
  ret i32 %add
}

define internal i32 @real_synth_a(i32 %x) !prof !5 {
entry:
  %add = add nsw i32 %x, 4
  ret i32 %add
}

define internal i32 @real_synth_b(i32 %x) !prof !6 {
entry:
  %add = add nsw i32 %x, 4
  ret i32 %add
}

define linkonce_odr i32 @odr_a(i32 %x) !prof !1 {
entry:
  %add = add nsw i32 %x, 5
  ret i32 %add
}

define linkonce_odr i32 @odr_b(i32 %x) !prof !1 {
entry:
  %add = add nsw i32 %x, 5
  ret i32 %add
}

@llvm.used = appending global [2 x ptr] [ptr @odr_a, ptr @odr_b], section "llvm.metadata"

define void @alias_a() unnamed_addr !prof !7 {
  ret void
}

define void @alias_b() unnamed_addr !prof !8 {
  ret void
}

define i32 @use_counts(i32 %x) {
entry:
  %basic = call i32 @basic_a(i32 %x)
  %basic2 = call i32 @basic_b(i32 %x)
  %asym = call i32 @asym_a(i32 %x)
  %asym2 = call i32 @asym_b(i32 %x)
  %onesided = call i32 @onesided_a(i32 %x)
  %onesided2 = call i32 @onesided_b(i32 %x)
  %real_synth = call i32 @real_synth_a(i32 %x)
  %real_synth2 = call i32 @real_synth_b(i32 %x)
  %odr = call i32 @odr_a(i32 %x)
  %odr2 = call i32 @odr_b(i32 %x)
  call void @alias_a()
  call void @alias_b()
  %sum0 = add i32 %basic, %basic2
  %sum1 = add i32 %sum0, %asym
  %sum2 = add i32 %sum1, %asym2
  %sum3 = add i32 %sum2, %onesided
  %sum4 = add i32 %sum3, %onesided2
  %sum5 = add i32 %sum4, %real_synth
  %sum6 = add i32 %sum5, %real_synth2
  %sum7 = add i32 %sum6, %odr
  %sum8 = add i32 %sum7, %odr2
  ret i32 %sum8
}

!llvm.module.flags = !{!0}

!0 = !{i32 1, !"ProfileSummary", !9}
!1 = !{!"function_entry_count", i64 1}
!2 = !{!"function_entry_count", i64 2000}
!3 = !{!"function_entry_count", i64 1000}
!4 = !{!"function_entry_count", i64 500}
!5 = !{!"function_entry_count", i64 10}
!6 = !{!"synthetic_function_entry_count", i64 5}
!7 = !{!"function_entry_count", i64 7}
!8 = !{!"function_entry_count", i64 5}
!9 = !{!10, !11, !12, !13, !14, !15, !16, !17}
!10 = !{!"ProfileFormat", !"InstrProf"}
!11 = !{!"TotalCount", i64 3531}
!12 = !{!"MaxCount", i64 2000}
!13 = !{!"MaxInternalCount", i64 2000}
!14 = !{!"MaxFunctionCount", i64 2000}
!15 = !{!"NumCounts", i64 12}
!16 = !{!"NumFunctions", i64 12}
!17 = !{!"DetailedSummary", !18}
!18 = !{!19}
!19 = !{i32 10000, i64 1, i32 1}
;.
; CHECK: @llvm.used = appending global [2 x ptr] [ptr @odr_a, ptr @odr_b], section "llvm.metadata"
;.
; ALIAS: @llvm.used = appending global [2 x ptr] [ptr @odr_a, ptr @odr_b], section "llvm.metadata"
; ALIAS: @alias_b = unnamed_addr alias void (), ptr @alias_a
;.
; CHECK-LABEL: define internal i32 @basic_a(
; CHECK-SAME: i32 [[X:%.*]]) !prof [[PROF12:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[X]], 1
; CHECK-NEXT:    ret i32 [[ADD]]
;
;
; CHECK-LABEL: define internal i32 @asym_a(
; CHECK-SAME: i32 [[X:%.*]]) !prof [[PROF13:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[X]], 2
; CHECK-NEXT:    ret i32 [[ADD]]
;
;
; CHECK-LABEL: define internal i32 @onesided_a(
; CHECK-SAME: i32 [[X:%.*]]) !prof [[PROF14:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[X]], 3
; CHECK-NEXT:    ret i32 [[ADD]]
;
;
; CHECK-LABEL: define internal i32 @real_synth_a(
; CHECK-SAME: i32 [[X:%.*]]) !prof [[PROF15:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[X]], 4
; CHECK-NEXT:    ret i32 [[ADD]]
;
;
; CHECK-LABEL: define private i32 @0(
; CHECK-SAME: i32 [[X:%.*]]) !prof [[PROF12]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[X]], 5
; CHECK-NEXT:    ret i32 [[ADD]]
;
;
; CHECK-LABEL: define void @alias_a(
; CHECK-SAME: ) unnamed_addr !prof [[PROF16:![0-9]+]] {
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define void @alias_b(
; CHECK-SAME: ) unnamed_addr !prof [[PROF17:![0-9]+]] {
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define i32 @use_counts(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[BASIC:%.*]] = call i32 @basic_a(i32 [[X]])
; CHECK-NEXT:    [[BASIC2:%.*]] = call i32 @basic_a(i32 [[X]])
; CHECK-NEXT:    [[ASYM:%.*]] = call i32 @asym_a(i32 [[X]])
; CHECK-NEXT:    [[ASYM2:%.*]] = call i32 @asym_a(i32 [[X]])
; CHECK-NEXT:    [[ONESIDED:%.*]] = call i32 @onesided_a(i32 [[X]])
; CHECK-NEXT:    [[ONESIDED2:%.*]] = call i32 @onesided_a(i32 [[X]])
; CHECK-NEXT:    [[REAL_SYNTH:%.*]] = call i32 @real_synth_a(i32 [[X]])
; CHECK-NEXT:    [[REAL_SYNTH2:%.*]] = call i32 @real_synth_a(i32 [[X]])
; CHECK-NEXT:    [[ODR:%.*]] = call i32 @[[GLOB0:[0-9]+]](i32 [[X]])
; CHECK-NEXT:    [[ODR2:%.*]] = call i32 @[[GLOB0]](i32 [[X]])
; CHECK-NEXT:    call void @alias_a()
; CHECK-NEXT:    call void @alias_a()
; CHECK-NEXT:    [[SUM0:%.*]] = add i32 [[BASIC]], [[BASIC2]]
; CHECK-NEXT:    [[SUM1:%.*]] = add i32 [[SUM0]], [[ASYM]]
; CHECK-NEXT:    [[SUM2:%.*]] = add i32 [[SUM1]], [[ASYM2]]
; CHECK-NEXT:    [[SUM3:%.*]] = add i32 [[SUM2]], [[ONESIDED]]
; CHECK-NEXT:    [[SUM4:%.*]] = add i32 [[SUM3]], [[ONESIDED2]]
; CHECK-NEXT:    [[SUM5:%.*]] = add i32 [[SUM4]], [[REAL_SYNTH]]
; CHECK-NEXT:    [[SUM6:%.*]] = add i32 [[SUM5]], [[REAL_SYNTH2]]
; CHECK-NEXT:    [[SUM7:%.*]] = add i32 [[SUM6]], [[ODR]]
; CHECK-NEXT:    [[SUM8:%.*]] = add i32 [[SUM7]], [[ODR2]]
; CHECK-NEXT:    ret i32 [[SUM8]]
;
;
; CHECK-LABEL: define linkonce_odr i32 @odr_b(
; CHECK-SAME: i32 [[TMP0:%.*]]) !prof [[PROF18:![0-9]+]] {
; CHECK-NEXT:    [[TMP2:%.*]] = tail call i32 @[[GLOB0]](i32 [[TMP0]])
; CHECK-NEXT:    ret i32 [[TMP2]]
;
;
; CHECK-LABEL: define linkonce_odr i32 @odr_a(
; CHECK-SAME: i32 [[TMP0:%.*]]) !prof [[PROF18]] {
; CHECK-NEXT:    [[TMP2:%.*]] = tail call i32 @[[GLOB0]](i32 [[TMP0]])
; CHECK-NEXT:    ret i32 [[TMP2]]
;
;
; ALIAS-LABEL: define internal i32 @basic_a(
; ALIAS-SAME: i32 [[X:%.*]]) !prof [[PROF12:![0-9]+]] {
; ALIAS-NEXT:  [[ENTRY:.*:]]
; ALIAS-NEXT:    [[ADD:%.*]] = add nsw i32 [[X]], 1
; ALIAS-NEXT:    ret i32 [[ADD]]
;
;
; ALIAS-LABEL: define internal i32 @asym_a(
; ALIAS-SAME: i32 [[X:%.*]]) !prof [[PROF13:![0-9]+]] {
; ALIAS-NEXT:  [[ENTRY:.*:]]
; ALIAS-NEXT:    [[ADD:%.*]] = add nsw i32 [[X]], 2
; ALIAS-NEXT:    ret i32 [[ADD]]
;
;
; ALIAS-LABEL: define internal i32 @onesided_a(
; ALIAS-SAME: i32 [[X:%.*]]) !prof [[PROF14:![0-9]+]] {
; ALIAS-NEXT:  [[ENTRY:.*:]]
; ALIAS-NEXT:    [[ADD:%.*]] = add nsw i32 [[X]], 3
; ALIAS-NEXT:    ret i32 [[ADD]]
;
;
; ALIAS-LABEL: define internal i32 @real_synth_a(
; ALIAS-SAME: i32 [[X:%.*]]) !prof [[PROF15:![0-9]+]] {
; ALIAS-NEXT:  [[ENTRY:.*:]]
; ALIAS-NEXT:    [[ADD:%.*]] = add nsw i32 [[X]], 4
; ALIAS-NEXT:    ret i32 [[ADD]]
;
;
; ALIAS-LABEL: define private i32 @0(
; ALIAS-SAME: i32 [[X:%.*]]) !prof [[PROF12]] {
; ALIAS-NEXT:  [[ENTRY:.*:]]
; ALIAS-NEXT:    [[ADD:%.*]] = add nsw i32 [[X]], 5
; ALIAS-NEXT:    ret i32 [[ADD]]
;
;
; ALIAS-LABEL: define void @alias_a(
; ALIAS-SAME: ) unnamed_addr !prof [[PROF16:![0-9]+]] {
; ALIAS-NEXT:    ret void
;
;
; ALIAS-LABEL: define i32 @use_counts(
; ALIAS-SAME: i32 [[X:%.*]]) {
; ALIAS-NEXT:  [[ENTRY:.*:]]
; ALIAS-NEXT:    [[BASIC:%.*]] = call i32 @basic_a(i32 [[X]])
; ALIAS-NEXT:    [[BASIC2:%.*]] = call i32 @basic_a(i32 [[X]])
; ALIAS-NEXT:    [[ASYM:%.*]] = call i32 @asym_a(i32 [[X]])
; ALIAS-NEXT:    [[ASYM2:%.*]] = call i32 @asym_a(i32 [[X]])
; ALIAS-NEXT:    [[ONESIDED:%.*]] = call i32 @onesided_a(i32 [[X]])
; ALIAS-NEXT:    [[ONESIDED2:%.*]] = call i32 @onesided_a(i32 [[X]])
; ALIAS-NEXT:    [[REAL_SYNTH:%.*]] = call i32 @real_synth_a(i32 [[X]])
; ALIAS-NEXT:    [[REAL_SYNTH2:%.*]] = call i32 @real_synth_a(i32 [[X]])
; ALIAS-NEXT:    [[ODR:%.*]] = call i32 @[[GLOB0:[0-9]+]](i32 [[X]])
; ALIAS-NEXT:    [[ODR2:%.*]] = call i32 @[[GLOB0]](i32 [[X]])
; ALIAS-NEXT:    call void @alias_a()
; ALIAS-NEXT:    call void @alias_a()
; ALIAS-NEXT:    [[SUM0:%.*]] = add i32 [[BASIC]], [[BASIC2]]
; ALIAS-NEXT:    [[SUM1:%.*]] = add i32 [[SUM0]], [[ASYM]]
; ALIAS-NEXT:    [[SUM2:%.*]] = add i32 [[SUM1]], [[ASYM2]]
; ALIAS-NEXT:    [[SUM3:%.*]] = add i32 [[SUM2]], [[ONESIDED]]
; ALIAS-NEXT:    [[SUM4:%.*]] = add i32 [[SUM3]], [[ONESIDED2]]
; ALIAS-NEXT:    [[SUM5:%.*]] = add i32 [[SUM4]], [[REAL_SYNTH]]
; ALIAS-NEXT:    [[SUM6:%.*]] = add i32 [[SUM5]], [[REAL_SYNTH2]]
; ALIAS-NEXT:    [[SUM7:%.*]] = add i32 [[SUM6]], [[ODR]]
; ALIAS-NEXT:    [[SUM8:%.*]] = add i32 [[SUM7]], [[ODR2]]
; ALIAS-NEXT:    ret i32 [[SUM8]]
;
;
; ALIAS-LABEL: define linkonce_odr i32 @odr_b(
; ALIAS-SAME: i32 [[TMP0:%.*]]) !prof [[PROF17:![0-9]+]] {
; ALIAS-NEXT:    [[TMP2:%.*]] = tail call i32 @[[GLOB0]](i32 [[TMP0]])
; ALIAS-NEXT:    ret i32 [[TMP2]]
;
;
; ALIAS-LABEL: define linkonce_odr i32 @odr_a(
; ALIAS-SAME: i32 [[TMP0:%.*]]) !prof [[PROF17]] {
; ALIAS-NEXT:    [[TMP2:%.*]] = tail call i32 @[[GLOB0]](i32 [[TMP0]])
; ALIAS-NEXT:    ret i32 [[TMP2]]
;
;.
; CHECK: [[META0:![0-9]+]] = !{i32 1, !"ProfileSummary", [[META1:![0-9]+]]}
; CHECK: [[META1]] = !{[[META2:![0-9]+]], [[META3:![0-9]+]], [[META4:![0-9]+]], [[META5:![0-9]+]], [[META6:![0-9]+]], [[META7:![0-9]+]], [[META8:![0-9]+]], [[META9:![0-9]+]]}
; CHECK: [[META2]] = !{!"ProfileFormat", !"InstrProf"}
; CHECK: [[META3]] = !{!"TotalCount", i64 3531}
; CHECK: [[META4]] = !{!"MaxCount", i64 2000}
; CHECK: [[META5]] = !{!"MaxInternalCount", i64 2000}
; CHECK: [[META6]] = !{!"MaxFunctionCount", i64 2000}
; CHECK: [[META7]] = !{!"NumCounts", i64 12}
; CHECK: [[META8]] = !{!"NumFunctions", i64 12}
; CHECK: [[META9]] = !{!"DetailedSummary", [[META10:![0-9]+]]}
; CHECK: [[META10]] = !{[[META11:![0-9]+]]}
; CHECK: [[META11]] = !{i32 10000, i64 1, i32 1}
; CHECK: [[PROF12]] = !{!"function_entry_count", i64 2}
; CHECK: [[PROF13]] = !{!"function_entry_count", i64 3000}
; CHECK: [[PROF14]] = !{!"function_entry_count", i64 500}
; CHECK: [[PROF15]] = !{!"synthetic_function_entry_count", i64 15}
; CHECK: [[PROF16]] = !{!"function_entry_count", i64 7}
; CHECK: [[PROF17]] = !{!"function_entry_count", i64 5}
; CHECK: [[PROF18]] = !{!"function_entry_count", i64 1}
;.
; ALIAS: [[META0:![0-9]+]] = !{i32 1, !"ProfileSummary", [[META1:![0-9]+]]}
; ALIAS: [[META1]] = !{[[META2:![0-9]+]], [[META3:![0-9]+]], [[META4:![0-9]+]], [[META5:![0-9]+]], [[META6:![0-9]+]], [[META7:![0-9]+]], [[META8:![0-9]+]], [[META9:![0-9]+]]}
; ALIAS: [[META2]] = !{!"ProfileFormat", !"InstrProf"}
; ALIAS: [[META3]] = !{!"TotalCount", i64 3531}
; ALIAS: [[META4]] = !{!"MaxCount", i64 2000}
; ALIAS: [[META5]] = !{!"MaxInternalCount", i64 2000}
; ALIAS: [[META6]] = !{!"MaxFunctionCount", i64 2000}
; ALIAS: [[META7]] = !{!"NumCounts", i64 12}
; ALIAS: [[META8]] = !{!"NumFunctions", i64 12}
; ALIAS: [[META9]] = !{!"DetailedSummary", [[META10:![0-9]+]]}
; ALIAS: [[META10]] = !{[[META11:![0-9]+]]}
; ALIAS: [[META11]] = !{i32 10000, i64 1, i32 1}
; ALIAS: [[PROF12]] = !{!"function_entry_count", i64 2}
; ALIAS: [[PROF13]] = !{!"function_entry_count", i64 3000}
; ALIAS: [[PROF14]] = !{!"function_entry_count", i64 500}
; ALIAS: [[PROF15]] = !{!"synthetic_function_entry_count", i64 15}
; ALIAS: [[PROF16]] = !{!"function_entry_count", i64 12}
; ALIAS: [[PROF17]] = !{!"function_entry_count", i64 1}
;.
