; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=mergefunc -mergefunc-use-aliases < %s | FileCheck %s

define void @alias_a() unnamed_addr !prof !12 {
; CHECK-LABEL: define void @alias_a(
; CHECK-SAME: ) unnamed_addr !prof [[PROF12:![0-9]+]] {
; CHECK-NEXT:    ret void
;
  ret void
}

define void @alias_b() unnamed_addr !prof !13 {
  ret void
}

define i32 @use(i32 %x) {
; CHECK-LABEL: define i32 @use(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @alias_a()
; CHECK-NEXT:    call void @alias_a()
; CHECK-NEXT:    ret i32 [[X]]
;
entry:
  call void @alias_a()
  call void @alias_b()
  ret i32 %x
}

!llvm.module.flags = !{!0}

!0 = !{i32 1, !"ProfileSummary", !1}
!1 = !{!2, !3, !4, !5, !6, !7, !8, !9}
!2 = !{!"ProfileFormat", !"InstrProf"}
!3 = !{!"TotalCount", i64 3531}
!4 = !{!"MaxCount", i64 2000}
!5 = !{!"MaxInternalCount", i64 2000}
!6 = !{!"MaxFunctionCount", i64 2000}
!7 = !{!"NumCounts", i64 12}
!8 = !{!"NumFunctions", i64 12}
!9 = !{!"DetailedSummary", !10}
!10 = !{!11}
!11 = !{i32 10000, i64 1, i32 1}
!12 = !{!"function_entry_count", i64 7}
!13 = !{!"function_entry_count", i64 5}
;
;
;
;.
; CHECK: [[PROF12]] = !{!"function_entry_count", i64 12}
;.
