; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=hexagon -mcpu=hexagonv67 < %s | FileCheck %s

define float @maxf(float %a, float %b) {
; CHECK-LABEL: maxf:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     r0 = sfmax(r0,r1)
; CHECK-NEXT:     jumpr r31
; CHECK-NEXT:    }
entry:
  %cmp = fcmp nnan nsz oge float %a, %b
  %cond = select nnan nsz i1 %cmp, float %a, float %b
  ret float %cond
}

define float @minf(float %a, float %b) {
; CHECK-LABEL: minf:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     r0 = sfmin(r0,r1)
; CHECK-NEXT:     jumpr r31
; CHECK-NEXT:    }
entry:
  %cmp = fcmp nnan nsz olt float %a, %b
  %cond = select nnan nsz i1 %cmp, float %a, float %b
  ret float %cond
}

define double @maxd(double %a, double %b) {
; CHECK-LABEL: maxd:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     r1:0 = dfmax(r1:0,r3:2)
; CHECK-NEXT:     jumpr r31
; CHECK-NEXT:    }
entry:
  %cmp = fcmp nnan nsz oge double %a, %b
  %cond = select nnan nsz i1 %cmp, double %a, double %b
  ret double %cond
}

define double @mind(double %a, double %b) {
; CHECK-LABEL: mind:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     r1:0 = dfmin(r1:0,r3:2)
; CHECK-NEXT:     jumpr r31
; CHECK-NEXT:    }
entry:
  %cmp = fcmp nnan nsz olt double %a, %b
  %cond = select nnan nsz i1 %cmp, double %a, double %b
  ret double %cond
}
