; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=hexagon-unknown-linux < %s | FileCheck %s

; Make sure we do not assert on negative constants during constant
; propagation.

define i64 @test(i1 %tobool) {
; CHECK-LABEL: test:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     r3:2 = combine(#0,r0)
; CHECK-NEXT:     r1:0 = combine(#-1,#-1)
; CHECK-NEXT:    }
; CHECK-NEXT:    {
; CHECK-NEXT:     p0 = tstbit(r2,#0)
; CHECK-NEXT:     r2 = #0
; CHECK-NEXT:    }
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_1: // %while.body
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    {
; CHECK-NEXT:     p1 = cmp.eq(r2,#0)
; CHECK-NEXT:     r2 = #1
; CHECK-NEXT:     if (!p1.new) r0 = add(r3,#0)
; CHECK-NEXT:     if (!p1.new) r1 = add(r3,#0)
; CHECK-NEXT:    }
; CHECK-NEXT:    {
; CHECK-NEXT:     if (p0) jump:nt .LBB0_1
; CHECK-NEXT:    }
; CHECK-NEXT:  // %bb.2: // %while.end
; CHECK-NEXT:    {
; CHECK-NEXT:     jumpr r31
; CHECK-NEXT:    }
entry:
  br label %while.body

while.body:
  %sel.iv = phi i64 [ %sel, %while.body ], [ -1, %entry ]
  %phi = phi i32 [ 1, %while.body ], [ 0, %entry ]
  %cmp = icmp eq i32 %phi, 0
  %sel = select i1 %cmp, i64 %sel.iv, i64 0
  br i1 %tobool, label %while.body, label %while.end

while.end:
  ret i64 %sel
}
