; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=hexagon -mcpu=hexagonv67 < %s | FileCheck %s

; test expandFMINNUM_FMAXNUM on backend with FMINIMUMNUM/FMAXIMUMNUM.
; N -> not NaN
; S -> not SNaN
; Y -> may be NaN or SNaN

define double @test_maxnumNN(double nofpclass(nan) %f1, double nofpclass(nan) %f2) {
; CHECK-LABEL: test_maxnumNN:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     r1:0 = dfmax(r1:0,r3:2)
; CHECK-NEXT:     jumpr r31
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumSS(double nofpclass(snan) %f1, double nofpclass(snan) %f2) {
; CHECK-LABEL: test_maxnumSS:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     r1:0 = dfmax(r1:0,r3:2)
; CHECK-NEXT:     jumpr r31
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumYY(double nofpclass(zero) %f1, double nofpclass(zero) %f2) {
; CHECK-LABEL: test_maxnumYY:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     jump fmax
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumNS(double nofpclass(nan) %f1, double nofpclass(snan) %f2) {
; CHECK-LABEL: test_maxnumNS:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     r1:0 = dfmax(r1:0,r3:2)
; CHECK-NEXT:     jumpr r31
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumNY(double nofpclass(nan) %f1, double nofpclass(zero) %f2) {
; CHECK-LABEL: test_maxnumNY:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     jump fmax
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumSN(double nofpclass(snan) %f1, double nofpclass(nan) %f2) {
; CHECK-LABEL: test_maxnumSN:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     r1:0 = dfmax(r1:0,r3:2)
; CHECK-NEXT:     jumpr r31
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumSY(double nofpclass(snan) %f1, double nofpclass(zero) %f2) {
; CHECK-LABEL: test_maxnumSY:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     jump fmax
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumYN(double nofpclass(zero) %f1, double nofpclass(nan) %f2) {
; CHECK-LABEL: test_maxnumYN:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     jump fmax
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumYS(double nofpclass(zero) %f1, double nofpclass(snan) %f2) {
; CHECK-LABEL: test_maxnumYS:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     jump fmax
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}


define double @test_minnumNN(double nofpclass(nan) %f1, double nofpclass(nan) %f2) {
; CHECK-LABEL: test_minnumNN:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     r1:0 = dfmin(r1:0,r3:2)
; CHECK-NEXT:     jumpr r31
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumSS(double nofpclass(snan) %f1, double nofpclass(snan) %f2) {
; CHECK-LABEL: test_minnumSS:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     r1:0 = dfmin(r1:0,r3:2)
; CHECK-NEXT:     jumpr r31
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumYY(double nofpclass(zero) %f1, double nofpclass(zero) %f2) {
; CHECK-LABEL: test_minnumYY:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     jump fmin
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumNS(double nofpclass(nan) %f1, double nofpclass(snan) %f2) {
; CHECK-LABEL: test_minnumNS:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     r1:0 = dfmin(r1:0,r3:2)
; CHECK-NEXT:     jumpr r31
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumNY(double nofpclass(nan) %f1, double nofpclass(zero) %f2) {
; CHECK-LABEL: test_minnumNY:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     jump fmin
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumSN(double nofpclass(snan) %f1, double nofpclass(nan) %f2) {
; CHECK-LABEL: test_minnumSN:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     r1:0 = dfmin(r1:0,r3:2)
; CHECK-NEXT:     jumpr r31
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumSY(double nofpclass(snan) %f1, double nofpclass(zero) %f2) {
; CHECK-LABEL: test_minnumSY:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     jump fmin
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumYN(double nofpclass(zero) %f1, double nofpclass(nan) %f2) {
; CHECK-LABEL: test_minnumYN:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     jump fmin
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumYS(double nofpclass(zero) %f1, double nofpclass(snan) %f2) {
; CHECK-LABEL: test_minnumYS:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     jump fmin
; CHECK-NEXT:    }
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

