; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=hexagon -hexagon-small-data-threshold=8 -verify-machineinstrs  < %s | FileCheck %s

@.str = private unnamed_addr constant [31 x i8] c"DHRYSTONE PROGRAM, 3'RD STRING\00", align 1
@.str1 = private unnamed_addr constant [3 x i8] c"%s\00", align 1

declare i32 @printf(i8* nocapture readonly, ...)

; Function Attrs: nounwind
define i32 @main() nounwind {
; CHECK-LABEL: main:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    {
; CHECK-NEXT:     r0 = ##.L.str1
; CHECK-NEXT:     r3:2 = CONST64(#2325073635944967245)
; CHECK-NEXT:     allocframe(r29,#40):raw
; CHECK-NEXT:    }
; CHECK-NEXT:    {
; CHECK-NEXT:     r1 = add(r29,#8)
; CHECK-NEXT:     r7:6 = CONST64(#4706902966564560965)
; CHECK-NEXT:     r5:4 = CONST64(#5642821575076104260)
; CHECK-NEXT:    }
; CHECK-NEXT:    {
; CHECK-NEXT:     memb(r29+#38) = #0
; CHECK-NEXT:     memw(r29+#0) = r1
; CHECK-NEXT:    }
; CHECK-NEXT:    {
; CHECK-NEXT:     memd(r29+#24) = r3:2
; CHECK-NEXT:     memd(r29+#16) = r7:6
; CHECK-NEXT:    }
; CHECK-NEXT:    {
; CHECK-NEXT:     memd(r29+#8) = r5:4
; CHECK-NEXT:     memh(r29+#36) = ##18254
; CHECK-NEXT:    }
; CHECK-NEXT:    {
; CHECK-NEXT:     call printf
; CHECK-NEXT:     memw(r29+#32) = ##1230132307
; CHECK-NEXT:    }
; CHECK-NEXT:    {
; CHECK-NEXT:     r0 = #0
; CHECK-NEXT:     dealloc_return
; CHECK-NEXT:    }
entry:
  %blah = alloca [30 x i8], align 8
  %arraydecay = getelementptr inbounds [30 x i8], [30 x i8]* %blah, i32 0, i32 0
  call void @llvm.memcpy.p0i8.p0i8.i32(i8* %arraydecay, i8* getelementptr inbounds ([31 x i8], [31 x i8]* @.str, i32 0, i32 0), i32 31, i32 1, i1 false)
  %call2 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @.str1, i32 0, i32 0), i8* %arraydecay)
  ret i32 0
}

declare void @llvm.memcpy.p0i8.p0i8.i32(i8* nocapture, i8* nocapture readonly, i32, i32, i1)
