# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=hexagon -run-pass=postra-machine-sink -o - %s | FileCheck %s

---
name:            test_undef_use_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_undef_use_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r0 = A2_tfrsi 1
  ; CHECK-NEXT:   $r2 = A2_tfrsi 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r1 = COPY killed renamable $r0, implicit undef $r2
  ; CHECK-NEXT:   J2_jumpr $r31, implicit-def $pc, implicit $r1
  bb.0:
    successors: %bb.1

    renamable $r0 = A2_tfrsi 1
    renamable $r1 = COPY killed renamable $r0, implicit undef $r2
    $r2 = A2_tfrsi 0

  bb.1:
    liveins: $r1
    J2_jumpr $r31, implicit-def $pc, implicit $r1
...
---
name:            test_internal_read_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_internal_read_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r0 = A2_tfrsi 1
  ; CHECK-NEXT:   renamable $r1 = COPY killed renamable $r0, implicit-def $r2, implicit internal $r2
  ; CHECK-NEXT:   $r3 = A2_tfrsi 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   J2_jumpr $r31, implicit-def $pc, implicit $r1
  bb.0:
    successors: %bb.1

    renamable $r0 = A2_tfrsi 1
    renamable $r1 = COPY killed renamable $r0, implicit-def $r2, implicit internal $r2
    $r3 = A2_tfrsi 0

  bb.1:
    liveins: $r1
    J2_jumpr $r31, implicit-def $pc, implicit $r1
...
