# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc --mtriple=hexagon %s -run-pass=pipeliner -o -| FileCheck %s

...
---
name:            test_swp_ws_live_intervals
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_swp_ws_live_intervals
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:intregs = COPY $r0
  ; CHECK-NEXT:   J2_loop0i %bb.1, 1, implicit-def $lc0, implicit-def $sa0, implicit-def $usr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x04000000), %bb.1(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[L2_loadri_io:%[0-9]+]]:intregs = L2_loadri_io [[COPY]], 0
  ; CHECK-NEXT:   [[L2_loadrub_io:%[0-9]+]]:intregs = L2_loadrub_io [[L2_loadri_io]], 0
  ; CHECK-NEXT:   [[PS_loadriabs:%[0-9]+]]:intregs = PS_loadriabs 0
  ; CHECK-NEXT:   S2_storerb_io [[PS_loadriabs]], 0, [[L2_loadrub_io]]
  ; CHECK-NEXT:   ENDLOOP0 %bb.1, implicit-def $pc, implicit-def $lc0, implicit $sa0, implicit $lc0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[A2_tfrsi:%[0-9]+]]:intregs = A2_tfrsi 0
  ; CHECK-NEXT:   [[A2_tfrsi1:%[0-9]+]]:intregs = A2_tfrsi -1
  ; CHECK-NEXT:   J2_jump %bb.5, implicit-def $pc
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   S2_storeri_io [[COPY]], 0, %18
  ; CHECK-NEXT:   PS_jmpret $r31, implicit-def dead $pc
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[A2_addi:%[0-9]+]]:intregs = A2_addi [[A2_tfrsi1]], 1
  ; CHECK-NEXT:   J2_jump %bb.7, implicit-def $pc
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:intregs = PHI [[A2_tfrsi]], %bb.5
  ; CHECK-NEXT:   J2_jump %bb.3, implicit-def $pc
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $r0

    %0:intregs = COPY $r0
    J2_loop0i %bb.1, 1, implicit-def $lc0, implicit-def $sa0, implicit-def $usr

  bb.1:
    successors: %bb.2(0x04000000), %bb.1(0x7c000000)

    %1:intregs = L2_loadri_io %0, 0
    %2:intregs = L2_loadrub_io killed %1, 0
    %3:intregs = PS_loadriabs 0
    S2_storerb_io killed %3, 0, killed %2
    ENDLOOP0 %bb.1, implicit-def $pc, implicit-def $lc0, implicit $sa0, implicit $lc0

  bb.2:
    successors: %bb.4(0x80000000)

    %4:intregs = A2_tfrsi 0
    %5:intregs = A2_tfrsi -1
    J2_loop0i %bb.4, 1, implicit-def $lc0, implicit-def $sa0, implicit-def $usr
    J2_jump %bb.4, implicit-def $pc

  bb.3:
    S2_storeri_io %0, 0, %6
    PS_jmpret $r31, implicit-def dead $pc

  bb.4:
    successors: %bb.3(0x04000000), %bb.4(0x7c000000)

    %7:intregs = PHI %5, %bb.2, %8, %bb.4
    %6:intregs = PHI %4, %bb.2, %9, %bb.4
    %8:intregs = A2_addi %7, 1
    %9:intregs = S2_setbit_i %8, 0
    ENDLOOP0 %bb.4, implicit-def $pc, implicit-def $lc0, implicit $sa0, implicit $lc0
    J2_jump %bb.3, implicit-def $pc

...
