; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -mtriple=x86_64-unknown-unknown -S | FileCheck %s
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

; The AVX512 packed/scalar "_round" arithmetic intrinsics take a rounding-mode
; immediate.  A value of 4 (_MM_FROUND_CUR_DIRECTION) means "use whatever the
; MXCSR register currently selects".  InstCombine rewrites these to plain
; unconstrained FP operations, which are semantically round-to-nearest-even and
; are then free to be constant-folded.
;
; These tests document that behavior.  The 'constfold' tests are the dangerous
; case: with constant operands chosen so that round-to-nearest and
; round-toward-zero disagree, the result is baked in as the round-to-nearest
; value (0x3F800001 == 1.00000012f), even though a caller that set MXCSR to
; round-toward-zero before the call expects 1.0 (0x3F800000).

declare <16 x float> @llvm.x86.avx512.add.ps.512(<16 x float>, <16 x float>, i32)
declare <16 x float> @llvm.x86.avx512.sub.ps.512(<16 x float>, <16 x float>, i32)
declare <16 x float> @llvm.x86.avx512.mul.ps.512(<16 x float>, <16 x float>, i32)
declare <16 x float> @llvm.x86.avx512.div.ps.512(<16 x float>, <16 x float>, i32)
declare <8 x double> @llvm.x86.avx512.add.pd.512(<8 x double>, <8 x double>, i32)
declare <4 x float> @llvm.x86.avx512.mask.add.ss.round(<4 x float>, <4 x float>, <4 x float>, i8, i32)

; In a strictfp function the FP environment may have been changed (e.g. via
; fesetround), so CUR_DIRECTION must NOT be folded to an unconstrained fadd:
; the intrinsic has to be preserved so the live MXCSR rounding mode is honored.
define <16 x float> @add_ps_512_cur_direction_strictfp(<16 x float> %a, <16 x float> %b) strictfp {
; CHECK-LABEL: @add_ps_512_cur_direction_strictfp(
; CHECK-NEXT:    [[R:%.*]] = call <16 x float> @llvm.x86.avx512.add.ps.512(<16 x float> [[A:%.*]], <16 x float> [[B:%.*]], i32 4) #[[ATTR1:[0-9]+]]
; CHECK-NEXT:    ret <16 x float> [[R]]
;
  %r = call <16 x float> @llvm.x86.avx512.add.ps.512(<16 x float> %a, <16 x float> %b, i32 4) strictfp
  ret <16 x float> %r
}

; Same constants as the constfold test above, but strictfp: must stay an
; intrinsic instead of constant-folding to the round-to-nearest value.
define <16 x float> @add_ps_512_cur_direction_constfold_strictfp() strictfp {
; CHECK-LABEL: @add_ps_512_cur_direction_constfold_strictfp(
; CHECK-NEXT:    [[R:%.*]] = call <16 x float> @llvm.x86.avx512.add.ps.512(<16 x float> splat (float 1.000000e+00), <16 x float> splat (float f0x33C00000), i32 4) #[[ATTR1]]
; CHECK-NEXT:    ret <16 x float> [[R]]
;
  %r = call <16 x float> @llvm.x86.avx512.add.ps.512(
  <16 x float> <float 1.0, float 1.0, float 1.0, float 1.0,
  float 1.0, float 1.0, float 1.0, float 1.0,
  float 1.0, float 1.0, float 1.0, float 1.0,
  float 1.0, float 1.0, float 1.0, float 1.0>,
  <16 x float> <float 0x3E78000000000000, float 0x3E78000000000000,
  float 0x3E78000000000000, float 0x3E78000000000000,
  float 0x3E78000000000000, float 0x3E78000000000000,
  float 0x3E78000000000000, float 0x3E78000000000000,
  float 0x3E78000000000000, float 0x3E78000000000000,
  float 0x3E78000000000000, float 0x3E78000000000000,
  float 0x3E78000000000000, float 0x3E78000000000000,
  float 0x3E78000000000000, float 0x3E78000000000000>,
  i32 4) strictfp
  ret <16 x float> %r
}

; Masked scalar variant must likewise be preserved under strictfp.
define <4 x float> @mask_add_ss_round_cur_direction_strictfp(<4 x float> %a, <4 x float> %b, <4 x float> %c) strictfp {
; CHECK-LABEL: @mask_add_ss_round_cur_direction_strictfp(
; CHECK-NEXT:    [[R:%.*]] = call <4 x float> @llvm.x86.avx512.mask.add.ss.round(<4 x float> [[A:%.*]], <4 x float> [[B:%.*]], <4 x float> [[C:%.*]], i8 -1, i32 4) #[[ATTR1]]
; CHECK-NEXT:    ret <4 x float> [[R]]
;
  %r = call <4 x float> @llvm.x86.avx512.mask.add.ss.round(<4 x float> %a, <4 x float> %b, <4 x float> %c, i8 -1, i32 4) strictfp
  ret <4 x float> %r
}

; The rounding-mode operand is dropped: CUR_DIRECTION folds to a plain fadd that
; no longer carries any MXCSR dependence.
define <16 x float> @add_ps_512_cur_direction(<16 x float> %a, <16 x float> %b) {
; CHECK-LABEL: @add_ps_512_cur_direction(
; CHECK-NEXT:    [[R:%.*]] = fadd <16 x float> [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    ret <16 x float> [[R]]
;
  %r = call <16 x float> @llvm.x86.avx512.add.ps.512(<16 x float> %a, <16 x float> %b, i32 4)
  ret <16 x float> %r
}

define <16 x float> @sub_ps_512_cur_direction(<16 x float> %a, <16 x float> %b) {
; CHECK-LABEL: @sub_ps_512_cur_direction(
; CHECK-NEXT:    [[R:%.*]] = fsub <16 x float> [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    ret <16 x float> [[R]]
;
  %r = call <16 x float> @llvm.x86.avx512.sub.ps.512(<16 x float> %a, <16 x float> %b, i32 4)
  ret <16 x float> %r
}

define <16 x float> @mul_ps_512_cur_direction(<16 x float> %a, <16 x float> %b) {
; CHECK-LABEL: @mul_ps_512_cur_direction(
; CHECK-NEXT:    [[R:%.*]] = fmul <16 x float> [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    ret <16 x float> [[R]]
;
  %r = call <16 x float> @llvm.x86.avx512.mul.ps.512(<16 x float> %a, <16 x float> %b, i32 4)
  ret <16 x float> %r
}

define <16 x float> @div_ps_512_cur_direction(<16 x float> %a, <16 x float> %b) {
; CHECK-LABEL: @div_ps_512_cur_direction(
; CHECK-NEXT:    [[R:%.*]] = fdiv <16 x float> [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    ret <16 x float> [[R]]
;
  %r = call <16 x float> @llvm.x86.avx512.div.ps.512(<16 x float> %a, <16 x float> %b, i32 4)
  ret <16 x float> %r
}

define <8 x double> @add_pd_512_cur_direction(<8 x double> %a, <8 x double> %b) {
; CHECK-LABEL: @add_pd_512_cur_direction(
; CHECK-NEXT:    [[R:%.*]] = fadd <8 x double> [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    ret <8 x double> [[R]]
;
  %r = call <8 x double> @llvm.x86.avx512.add.pd.512(<8 x double> %a, <8 x double> %b, i32 4)
  ret <8 x double> %r
}

; A non-CUR_DIRECTION rounding mode (8 == round-to-nearest, no exceptions) must
; NOT be folded, since it overrides MXCSR.  Kept as a negative control.
define <16 x float> @add_ps_512_round_to_nearest(<16 x float> %a, <16 x float> %b) {
; CHECK-LABEL: @add_ps_512_round_to_nearest(
; CHECK-NEXT:    [[R:%.*]] = call <16 x float> @llvm.x86.avx512.add.ps.512(<16 x float> [[A:%.*]], <16 x float> [[B:%.*]], i32 8)
; CHECK-NEXT:    ret <16 x float> [[R]]
;
  %r = call <16 x float> @llvm.x86.avx512.add.ps.512(<16 x float> %a, <16 x float> %b, i32 8)
  ret <16 x float> %r
}

; Constant operands: a = 1.0, b = 3*2^-25 (0x3E78000000000000 in double-encoded
; literal form == 0x33C00000 as f32).  1.0 + b lies between 1.0 and 1.0+ulp and
; is closer to the upper neighbor, so:
;   round-to-nearest-even -> 0x3F800001 (1.00000012)
;   round-toward-zero     -> 0x3F800000 (1.0)
; The fold bakes in the round-to-nearest value, which is wrong whenever the
; caller's live MXCSR rounding mode is not round-to-nearest.
define <16 x float> @add_ps_512_cur_direction_constfold() {
; CHECK-LABEL: @add_ps_512_cur_direction_constfold(
; CHECK-NEXT:    ret <16 x float> splat (float f0x3F800001)
;
  %r = call <16 x float> @llvm.x86.avx512.add.ps.512(
  <16 x float> <float 1.0, float 1.0, float 1.0, float 1.0,
  float 1.0, float 1.0, float 1.0, float 1.0,
  float 1.0, float 1.0, float 1.0, float 1.0,
  float 1.0, float 1.0, float 1.0, float 1.0>,
  <16 x float> <float 0x3E78000000000000, float 0x3E78000000000000,
  float 0x3E78000000000000, float 0x3E78000000000000,
  float 0x3E78000000000000, float 0x3E78000000000000,
  float 0x3E78000000000000, float 0x3E78000000000000,
  float 0x3E78000000000000, float 0x3E78000000000000,
  float 0x3E78000000000000, float 0x3E78000000000000,
  float 0x3E78000000000000, float 0x3E78000000000000,
  float 0x3E78000000000000, float 0x3E78000000000000>,
  i32 4)
  ret <16 x float> %r
}

; Masked scalar variant (arg 4 is the rounding mode); all-ones mask + constants.
; Lane 0 likewise constant-folds to the round-to-nearest value 0x3F800001.
define <4 x float> @mask_add_ss_round_cur_direction_constfold() {
; CHECK-LABEL: @mask_add_ss_round_cur_direction_constfold(
; CHECK-NEXT:    ret <4 x float> <float f0x3F800001, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00>
;
  %r = call <4 x float> @llvm.x86.avx512.mask.add.ss.round(
  <4 x float> <float 1.0, float 0.0, float 0.0, float 0.0>,
  <4 x float> <float 0x3E78000000000000, float 0.0, float 0.0, float 0.0>,
  <4 x float> zeroinitializer,
  i8 -1, i32 4)
  ret <4 x float> %r
}
