; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -mtriple=x86_64-- -mattr=+avx512ifma -S | FileCheck %s

; ---- Positive cases should fold ----

define <2 x i64> @fold_h_128(<2 x i64> %x, <2 x i64> %a, <2 x i64> %b) {
; CHECK-LABEL: @fold_h_128(
; CHECK-NEXT:    [[R:%.*]] = call <2 x i64> @llvm.x86.avx512.vpmadd52h.uq.128(<2 x i64> [[X:%.*]], <2 x i64> [[A:%.*]], <2 x i64> [[B:%.*]])
; CHECK-NEXT:    ret <2 x i64> [[R]]
;
  %m = call <2 x i64> @llvm.x86.avx512.vpmadd52h.uq.128(<2 x i64> zeroinitializer, <2 x i64> %a, <2 x i64> %b)
  %r = add <2 x i64> %m, %x
  ret <2 x i64> %r
}

define <2 x i64> @fold_l_128(<2 x i64> %x, <2 x i64> %a, <2 x i64> %b) {
; CHECK-LABEL: @fold_l_128(
; CHECK-NEXT:    [[R:%.*]] = call <2 x i64> @llvm.x86.avx512.vpmadd52l.uq.128(<2 x i64> [[X:%.*]], <2 x i64> [[A:%.*]], <2 x i64> [[B:%.*]])
; CHECK-NEXT:    ret <2 x i64> [[R]]
;
  %m = call <2 x i64> @llvm.x86.avx512.vpmadd52l.uq.128(<2 x i64> zeroinitializer, <2 x i64> %a, <2 x i64> %b)
  %r = add <2 x i64> %m, %x
  ret <2 x i64> %r
}

define <4 x i64> @fold_h_256(<4 x i64> %x, <4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: @fold_h_256(
; CHECK-NEXT:    [[R:%.*]] = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> [[X:%.*]], <4 x i64> [[A:%.*]], <4 x i64> [[B:%.*]])
; CHECK-NEXT:    ret <4 x i64> [[R]]
;
  %m = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> %a, <4 x i64> %b)
  %r = add <4 x i64> %m, %x
  ret <4 x i64> %r
}

define <4 x i64> @fold_l_256(<4 x i64> %x, <4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: @fold_l_256(
; CHECK-NEXT:    [[R:%.*]] = call <4 x i64> @llvm.x86.avx512.vpmadd52l.uq.256(<4 x i64> [[X:%.*]], <4 x i64> [[A:%.*]], <4 x i64> [[B:%.*]])
; CHECK-NEXT:    ret <4 x i64> [[R]]
;
  %m = call <4 x i64> @llvm.x86.avx512.vpmadd52l.uq.256(<4 x i64> zeroinitializer, <4 x i64> %a, <4 x i64> %b)
  %r = add <4 x i64> %m, %x
  ret <4 x i64> %r
}

define <8 x i64> @fold_h_512(<8 x i64> %x, <8 x i64> %a, <8 x i64> %b) {
; CHECK-LABEL: @fold_h_512(
; CHECK-NEXT:    [[R:%.*]] = call <8 x i64> @llvm.x86.avx512.vpmadd52h.uq.512(<8 x i64> [[X:%.*]], <8 x i64> [[A:%.*]], <8 x i64> [[B:%.*]])
; CHECK-NEXT:    ret <8 x i64> [[R]]
;
  %m = call <8 x i64> @llvm.x86.avx512.vpmadd52h.uq.512(<8 x i64> zeroinitializer, <8 x i64> %a, <8 x i64> %b)
  %r = add <8 x i64> %m, %x
  ret <8 x i64> %r
}

define <8 x i64> @fold_l_512(<8 x i64> %x, <8 x i64> %a, <8 x i64> %b) {
; CHECK-LABEL: @fold_l_512(
; CHECK-NEXT:    [[R:%.*]] = call <8 x i64> @llvm.x86.avx512.vpmadd52l.uq.512(<8 x i64> [[X:%.*]], <8 x i64> [[A:%.*]], <8 x i64> [[B:%.*]])
; CHECK-NEXT:    ret <8 x i64> [[R]]
;
  %m = call <8 x i64> @llvm.x86.avx512.vpmadd52l.uq.512(<8 x i64> zeroinitializer, <8 x i64> %a, <8 x i64> %b)
  %r = add <8 x i64> %m, %x
  ret <8 x i64> %r
}

define <4 x i64> @fold_commuted(<4 x i64> %x, <4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: @fold_commuted(
; CHECK-NEXT:    [[R:%.*]] = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> [[X:%.*]], <4 x i64> [[A:%.*]], <4 x i64> [[B:%.*]])
; CHECK-NEXT:    ret <4 x i64> [[R]]
;
  %m = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> %a, <4 x i64> %b)
  %r = add <4 x i64> %x, %m
  ret <4 x i64> %r
}

define <4 x i64> @fold_two_madd52_calls(<4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: @fold_two_madd52_calls(
; CHECK-NEXT:    [[M2:%.*]] = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> [[A:%.*]], <4 x i64> [[B:%.*]])
; CHECK-NEXT:    [[R:%.*]] = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> [[M2]], <4 x i64> [[A]], <4 x i64> [[B]])
; CHECK-NEXT:    ret <4 x i64> [[R]]
;
  %m1 = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> %a, <4 x i64> %b)
  %m2 = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> %a, <4 x i64> %b)
  %r = add <4 x i64> %m1, %m2
  ret <4 x i64> %r
}

define <4 x i64> @fold_three_madd52_chain(<4 x i64> %a, <4 x i64> %b, <4 x i64> %c, <4 x i64> %d, <4 x i64> %e, <4 x i64> %f) {
; CHECK-LABEL: @fold_three_madd52_chain(
; CHECK-NEXT:    [[M2:%.*]] = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> [[C:%.*]], <4 x i64> [[D:%.*]])
; CHECK-NEXT:    [[T1:%.*]] = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> [[M2]], <4 x i64> [[A:%.*]], <4 x i64> [[B:%.*]])
; CHECK-NEXT:    [[R:%.*]] = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> [[T1]], <4 x i64> [[E:%.*]], <4 x i64> [[F:%.*]])
; CHECK-NEXT:    ret <4 x i64> [[R]]
;
  %m1 = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> %a, <4 x i64> %b)
  %m2 = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> %c, <4 x i64> %d)
  %m3 = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> %e, <4 x i64> %f)
  %t1 = add <4 x i64> %m1, %m2
  %r  = add <4 x i64> %t1, %m3
  ret <4 x i64> %r
}

; ---- Negative cases should NOT fold ----

define <4 x i64> @nofold_nonzero_acc(<4 x i64> %x, <4 x i64> %acc, <4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: @nofold_nonzero_acc(
; CHECK-NEXT:    [[M:%.*]] = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> [[ACC:%.*]], <4 x i64> [[A:%.*]], <4 x i64> [[B:%.*]])
; CHECK-NEXT:    [[R:%.*]] = add <4 x i64> [[M]], [[X:%.*]]
; CHECK-NEXT:    ret <4 x i64> [[R]]
;
  %m = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> %acc, <4 x i64> %a, <4 x i64> %b)
  %r = add <4 x i64> %m, %x
  ret <4 x i64> %r
}

define <4 x i64> @nofold_multi_use(<4 x i64> %x, <4 x i64> %a, <4 x i64> %b, ptr %p) {
; CHECK-LABEL: @nofold_multi_use(
; CHECK-NEXT:    [[M:%.*]] = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> [[A:%.*]], <4 x i64> [[B:%.*]])
; CHECK-NEXT:    store <4 x i64> [[M]], ptr [[P:%.*]], align 32
; CHECK-NEXT:    [[R:%.*]] = add <4 x i64> [[M]], [[X:%.*]]
; CHECK-NEXT:    ret <4 x i64> [[R]]
;
  %m = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> %a, <4 x i64> %b)
  store <4 x i64> %m, ptr %p
  %r = add <4 x i64> %m, %x
  ret <4 x i64> %r
}

define <4 x i64> @nofold_madd_double_use(<4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: @nofold_madd_double_use(
; CHECK-NEXT:    [[M:%.*]] = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> [[A:%.*]], <4 x i64> [[B:%.*]])
; CHECK-NEXT:    [[R:%.*]] = shl <4 x i64> [[M]], splat (i64 1)
; CHECK-NEXT:    ret <4 x i64> [[R]]
;
  %m = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> %a, <4 x i64> %b)
  %r = add <4 x i64> %m, %m
  ret <4 x i64> %r
}

define <4 x i64> @nofold_sub(<4 x i64> %x, <4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: @nofold_sub(
; CHECK-NEXT:    [[M:%.*]] = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> [[A:%.*]], <4 x i64> [[B:%.*]])
; CHECK-NEXT:    [[R:%.*]] = sub <4 x i64> [[M]], [[X:%.*]]
; CHECK-NEXT:    ret <4 x i64> [[R]]
;
  %m = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> %a, <4 x i64> %b)
  %r = sub <4 x i64> %m, %x
  ret <4 x i64> %r
}

define <4 x i64> @nofold_no_add(<4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: @nofold_no_add(
; CHECK-NEXT:    [[R:%.*]] = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> [[A:%.*]], <4 x i64> [[B:%.*]])
; CHECK-NEXT:    ret <4 x i64> [[R]]
;
  %r = call <4 x i64> @llvm.x86.avx512.vpmadd52h.uq.256(<4 x i64> zeroinitializer, <4 x i64> %a, <4 x i64> %b)
  ret <4 x i64> %r
}
