; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=ipsccp -S %s | FileCheck %s --check-prefix=IPSCCP
; RUN: opt -passes=sccp -S %s | FileCheck %s --check-prefix=SCCP

define i16 @mustRetOne() {
; CHECK-LABEL: define i16 @mustRetOne() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret i16 1
;
; IPSCCP-LABEL: define range(i16 1, 2) i16 @mustRetOne() {
; IPSCCP-NEXT:  [[ENTRY:.*:]]
; IPSCCP-NEXT:    ret i16 1
;
; SCCP-LABEL: define range(i16 1, 2) i16 @mustRetOne() {
; SCCP-NEXT:  [[ENTRY:.*:]]
; SCCP-NEXT:    ret i16 1
;
entry:
  ret i16 1
}

define void @test() {
; IPSCCP-LABEL: define void @test() {
; IPSCCP-NEXT:  [[ENTRY:.*:]]
; IPSCCP-NEXT:    [[CALL:%.*]] = call i16 @mustRetOne()
; IPSCCP-NEXT:    br label %[[IF_END:.*]]
; IPSCCP:       [[RET:.*]]:
; IPSCCP-NEXT:    ret void
; IPSCCP:       [[IF_END]]:
; IPSCCP-NEXT:    br label %[[RET]]
;
; SCCP-LABEL: define void @test() {
; SCCP-NEXT:  [[ENTRY:.*:]]
; SCCP-NEXT:    [[CALL:%.*]] = call i16 @mustRetOne()
; SCCP-NEXT:    br label %[[IF_END:.*]]
; SCCP:       [[RET:.*]]:
; SCCP-NEXT:    ret void
; SCCP:       [[IF_END]]:
; SCCP-NEXT:    br label %[[RET]]
;
entry:
  %call = call i16 @mustRetOne()
  %cond = trunc i16 %call to i1
  br i1 %cond, label %if.end, label %ret

ret:                                              ; preds = %if.end, %entry
  ret void

if.end:                                           ; preds = %entry
  br label %ret
}
