; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=sccp -S | FileCheck %s --check-prefix=SCCP
; RUN: opt < %s -passes=ipsccp -S | FileCheck %s --check-prefix=IPSCCP

define i1 @mul_preimage_only_in_late_sccp(i8 range(i8 0, 5) %x) {
; SCCP-LABEL: define i1 @mul_preimage_only_in_late_sccp(
; SCCP-SAME: i8 range(i8 0, 5) [[X:%.*]]) {
; SCCP-NEXT:    [[M:%.*]] = mul nuw nsw i8 [[X]], 17
; SCCP-NEXT:    [[CMP:%.*]] = icmp eq i8 [[X]], 0
; SCCP-NEXT:    ret i1 [[CMP]]
;
; IPSCCP-LABEL: define i1 @mul_preimage_only_in_late_sccp(
; IPSCCP-SAME: i8 range(i8 0, 5) [[X:%.*]]) {
; IPSCCP-NEXT:    [[M:%.*]] = mul nuw nsw i8 [[X]], 17
; IPSCCP-NEXT:    [[CMP:%.*]] = icmp slt i8 [[M]], 17
; IPSCCP-NEXT:    ret i1 [[CMP]]
;
  %m = mul i8 %x, 17
  %cmp = icmp slt i8 %m, 17
  ret i1 %cmp
}
