; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes=sccp < %s -S | FileCheck %s

define i8 @ashr_to_lshr(i8 %x, i8 %y) {
; CHECK-LABEL: define range(i8 0, -128) i8 @ashr_to_lshr(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]]) {
; CHECK-NEXT:    [[P:%.*]] = and i8 [[X]], 127
; CHECK-NEXT:    [[R:%.*]] = lshr exact i8 [[P]], [[Y]]
; CHECK-NEXT:    ret i8 [[R]]
;
  %p = and i8 %x, 127
  %r = ashr exact i8 %p, %y
  ret i8 %r
}

define i8 @sdiv_to_udiv(i8 %x, i8 %y) {
; CHECK-LABEL: define range(i8 0, -128) i8 @sdiv_to_udiv(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]]) {
; CHECK-NEXT:    [[X1:%.*]] = and i8 [[X]], 127
; CHECK-NEXT:    [[Y1:%.*]] = and i8 [[Y]], 127
; CHECK-NEXT:    [[R:%.*]] = udiv exact i8 [[X1]], [[Y1]]
; CHECK-NEXT:    ret i8 [[R]]
;
  %x1 = and i8 %x, 127
  %y1 = and i8 %y, 127
  %r = sdiv exact i8 %x1, %y1
  ret i8 %r
}
