; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=sccp < %s | FileCheck %s

define ptr @gep_nusw_nneg(ptr %p, i32 %x, i32 %y) {
; CHECK-LABEL: define ptr @gep_nusw_nneg(
; CHECK-SAME: ptr [[P:%.*]], i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:    [[X_EXT:%.*]] = zext i32 [[X]] to i64
; CHECK-NEXT:    [[Y_EXT:%.*]] = zext i32 [[Y]] to i64
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr nusw nuw [1 x i8], ptr [[P]], i64 [[X_EXT]], i64 [[Y_EXT]]
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %x.ext = zext i32 %x to i64
  %y.ext = zext i32 %y to i64
  %gep = getelementptr nusw [1 x i8], ptr %p, i64 %x.ext, i64 %y.ext
  ret ptr %gep
}

define ptr @gep_inbounds_nneg(ptr %p, i32 %x, i32 %y) {
; CHECK-LABEL: define ptr @gep_inbounds_nneg(
; CHECK-SAME: ptr [[P:%.*]], i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:    [[X_EXT:%.*]] = zext i32 [[X]] to i64
; CHECK-NEXT:    [[Y_EXT:%.*]] = zext i32 [[Y]] to i64
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw [1 x i8], ptr [[P]], i64 [[X_EXT]], i64 [[Y_EXT]]
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %x.ext = zext i32 %x to i64
  %y.ext = zext i32 %y to i64
  %gep = getelementptr inbounds [1 x i8], ptr %p, i64 %x.ext, i64 %y.ext
  ret ptr %gep
}

define ptr @gep_nothin_nneg(ptr %p, i32 %x, i32 %y) {
; CHECK-LABEL: define ptr @gep_nothin_nneg(
; CHECK-SAME: ptr [[P:%.*]], i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:    [[X_EXT:%.*]] = zext i32 [[X]] to i64
; CHECK-NEXT:    [[Y_EXT:%.*]] = zext i32 [[Y]] to i64
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr [1 x i8], ptr [[P]], i64 [[X_EXT]], i64 [[Y_EXT]]
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %x.ext = zext i32 %x to i64
  %y.ext = zext i32 %y to i64
  %gep = getelementptr [1 x i8], ptr %p, i64 %x.ext, i64 %y.ext
  ret ptr %gep
}

define ptr @gep_nusw_not_nneg(ptr %p, i32 %x, i64 %y) {
; CHECK-LABEL: define ptr @gep_nusw_not_nneg(
; CHECK-SAME: ptr [[P:%.*]], i32 [[X:%.*]], i64 [[Y:%.*]]) {
; CHECK-NEXT:    [[X_EXT:%.*]] = zext i32 [[X]] to i64
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr nusw [1 x i8], ptr [[P]], i64 [[X_EXT]], i64 [[Y]]
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %x.ext = zext i32 %x to i64
  %gep = getelementptr nusw [1 x i8], ptr %p, i64 %x.ext, i64 %y
  ret ptr %gep
}
