; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=sccp,dce -S | FileCheck %s

; Test for icmp (mul (zext x), C) to icmp x,
; if mul is invertible on given predicate constraint
; Refer to https://github.com/llvm/llvm-project/pull/186347 to understand
; the mathematical model.

; Comes from https://github.com/llvm/llvm-project/pull/185907#discussion_r2919506475
; N = 9, M = 27
; n = 2^9 = 512, m = 2^27 = 134217728, C = 262657
; k = floor((n - 1) * C / m) = floor(511 * 262657 / 134217728) = 0
; CR = [-2^26, 262657), Y = [0, 134217728)
; Invertible: yes
define i1 @slt_invertible_zext_mul_full_image(<2 x i9> %v) {
; CHECK-LABEL: define i1 @slt_invertible_zext_mul_full_image(
; CHECK-SAME: <2 x i9> [[V:%.*]]) {
; CHECK-NEXT:    [[E:%.*]] = extractelement <2 x i9> [[V]], i64 0
; CHECK-NEXT:    [[Z:%.*]] = zext i9 [[E]] to i27
; CHECK-NEXT:    [[TMP1:%.*]] = add i27 [[Z]], -256
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ult i27 [[TMP1]], -255
; CHECK-NEXT:    ret i1 [[TMP2]]
;
  %e = extractelement <2 x i9> %v, i64 0
  %z = zext i9 %e to i27
  %m = mul i27 %z, 262657
  %cmp = icmp slt i27 %m, 262657
  ret i1 %cmp
}

; N = 8, M = 16
; n = 2^8 = 256, m = 2^16 = 65536, C = 257
; k = floor((n - 1) * C / m) = floor(255 * 257 / 65536) = 0
; CR = [-2^15, 257), Y = [0, 65536)
; Invertible: yes
define i1 @slt_invertible_zext_mul_full_image_i16(i8 %v) {
; CHECK-LABEL: define i1 @slt_invertible_zext_mul_full_image_i16(
; CHECK-SAME: i8 [[V:%.*]]) {
; CHECK-NEXT:    [[Z:%.*]] = zext i8 [[V]] to i16
; CHECK-NEXT:    [[TMP1:%.*]] = add i16 [[Z]], -128
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ult i16 [[TMP1]], -127
; CHECK-NEXT:    ret i1 [[TMP2]]
;
  %z = zext i8 %v to i16
  %m = mul nuw i16 %z, 257
  %cmp = icmp slt i16 %m, 257
  ret i1 %cmp
}

; N = 4, M = 8
; n = 2^4 = 16, m = 2^8 = 256, C = 17
; k = floor((n - 1) * C / m) = floor(15 * 17 / 256) = 0
; CR = [-2^7, 17), Y = [0, 256)
; Invertible: yes
define i1 @slt_invertible_zext_mul_full_image_i8(i4 %v) {
; CHECK-LABEL: define i1 @slt_invertible_zext_mul_full_image_i8(
; CHECK-SAME: i4 [[V:%.*]]) {
; CHECK-NEXT:    [[Z:%.*]] = zext i4 [[V]] to i8
; CHECK-NEXT:    [[TMP1:%.*]] = add i8 [[Z]], -8
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ult i8 [[TMP1]], -7
; CHECK-NEXT:    ret i1 [[TMP2]]
;
  %z = zext i4 %v to i8
  %m = mul nuw i8 %z, 17
  %cmp = icmp slt i8 %m, 17
  ret i1 %cmp
}

; N = 4, M = 8
; n = 2^4 = 16, m = 2^8 = 256, C = 10
; k = floor((n - 1) * C / m) = floor(15 * 10 / 256) = 0
; CR = [0, 50), Y = [0, 151)
; Invertible: yes, because CR ⊆ Y
define i1 @ult_invertible_zext_mul_partial_image(i4 %x) {
; CHECK-LABEL: define i1 @ult_invertible_zext_mul_partial_image(
; CHECK-SAME: i4 [[X:%.*]]) {
; CHECK-NEXT:    [[Z:%.*]] = zext i4 [[X]] to i8
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i8 [[Z]], 5
; CHECK-NEXT:    ret i1 [[TMP1]]
;
  %z = zext i4 %x to i8
  %m = mul i8 %z, 10
  %cmp = icmp ult i8 %m, 50
  ret i1 %cmp
}

; N = 4, M = 8
; n = 2^4 = 16, m = 2^8 = 256, C = 10
; k = floor((n - 1) * C / m) = floor(15 * 10 / 256) = 0
; CR = [0, 200), Y = [0, 151)
; Invertible: yes
define i1 @ult_invertible_zext_mul_all_true(i4 %x) {
; CHECK-LABEL: define i1 @ult_invertible_zext_mul_all_true(
; CHECK-SAME: i4 [[X:%.*]]) {
; CHECK-NEXT:    ret i1 true
;
  %z = zext i4 %x to i8
  %m = mul i8 %z, 10
  %cmp = icmp ult i8 %m, 200
  ret i1 %cmp
}

; N = 4, M = 8
; n = 2^4 = 16, m = 2^8 = 256, C = 10
; k = floor((n - 1) * C / m) = floor(15 * 10 / 256) = 0
; CR = [200, 256), Y = [0, 151)
; Invertible: yes
define i1 @uge_invertible_zext_mul_all_false(i4 %x) {
; CHECK-LABEL: define i1 @uge_invertible_zext_mul_all_false(
; CHECK-SAME: i4 [[X:%.*]]) {
; CHECK-NEXT:    ret i1 false
;
  %z = zext i4 %x to i8
  %m = mul i8 %z, 10
  %cmp = icmp uge i8 %m, 200
  ret i1 %cmp
}

; N = 4, M = 8
; n = 2^4 = 16, m = 2^8 = 256, C = 20
; k = floor((n - 1) * C / m) = floor(15 * 20 / 256) = 1
; CR = [60, 128), Y = [45, 256)
; Invertible: yes
define i1 @sge_invertible_tail_of_zext_mul(i4 %x) {
; CHECK-LABEL: define i1 @sge_invertible_tail_of_zext_mul(
; CHECK-SAME: i4 [[X:%.*]]) {
; CHECK-NEXT:    [[Z:%.*]] = zext i4 [[X]] to i8
; CHECK-NEXT:    [[TMP1:%.*]] = add i8 [[Z]], -3
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ult i8 [[TMP1]], 4
; CHECK-NEXT:    ret i1 [[TMP2]]
;
  %z = zext i4 %x to i8
  %m = mul i8 %z, 20
  %cmp = icmp sge i8 %m, 60
  ret i1 %cmp
}

; N = 4, M = 8
; n = 2^4 = 16, m = 2^8 = 256, C = 20
; k = floor((n - 1) * C / m) = floor(15 * 20 / 256) = 1
; CR = [60, 256), Y = [45, 256)
; Invertible: yes
define i1 @uge_invertible_tail_of_zext_mul(i4 %x) {
; CHECK-LABEL: define i1 @uge_invertible_tail_of_zext_mul(
; CHECK-SAME: i4 [[X:%.*]]) {
; CHECK-NEXT:    [[Z:%.*]] = zext i4 [[X]] to i8
; CHECK-NEXT:    [[TMP1:%.*]] = add i8 [[Z]], -3
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ult i8 [[TMP1]], 10
; CHECK-NEXT:    ret i1 [[TMP2]]
;
  %z = zext i4 %x to i8
  %m = mul i8 %z, 20
  %cmp = icmp uge i8 %m, 60
  ret i1 %cmp
}

; N = 4, M = 8
; n = 2^4 = 16, m = 2^8 = 256, C = 18
; k = floor((n - 1) * C / m) = floor(15 * 18 / 256) = 1
; CR = [-2^7, 16), Y = [15, 256)
; Invertible: yes on Y.inverse() = [16, 2^7)
define i1 @slt_noninvertible_signed_range_before_tail(i4 %v) {
; CHECK-LABEL: define i1 @slt_noninvertible_signed_range_before_tail(
; CHECK-SAME: i4 [[V:%.*]]) {
; CHECK-NEXT:    [[Z:%.*]] = zext i4 [[V]] to i8
; CHECK-NEXT:    [[TMP1:%.*]] = add i8 [[Z]], -8
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP1]], -7
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %z = zext i4 %v to i8
  %cast = mul nuw i8 %z, 18
  %cmp = icmp slt i8 %cast, 16
  ret i1 %cmp
}

; N = 4, M = 8
; n = 2^4 = 16, m = 2^8 = 256, C = 20
; k = floor((n - 1) * C / m) = floor(15 * 20 / 256) = 1
; CR = [0, 45), Y = [45, 256)
; Invertible: yes on Y.inverse() = [45, 256)
define i1 @ult_noninvertible_zext_mul_range(i4 %x) {
; CHECK-LABEL: define i1 @ult_noninvertible_zext_mul_range(
; CHECK-SAME: i4 [[X:%.*]]) {
; CHECK-NEXT:    [[Z:%.*]] = zext i4 [[X]] to i8
; CHECK-NEXT:    [[TMP1:%.*]] = add i8 [[Z]], -13
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP1]], -10
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %z = zext i4 %x to i8
  %m = mul i8 %z, 20
  %cmp = icmp ult i8 %m, 45
  ret i1 %cmp
}

; N = 4, M = 8
; n = 2^4 = 16, m = 2^8 = 256, C = 18
; k = floor((n - 1) * C / m) = floor(15 * 18 / 256) = 1
; CR = [0, 16), Y = [15, 256)
; Invertible: yes on Y.inverse() = [16, 256)
define i1 @ult_noninvertible_zext_mul_before_tail(i4 %v) {
; CHECK-LABEL: define i1 @ult_noninvertible_zext_mul_before_tail(
; CHECK-SAME: i4 [[V:%.*]]) {
; CHECK-NEXT:    [[Z:%.*]] = zext i4 [[V]] to i8
; CHECK-NEXT:    [[TMP1:%.*]] = add i8 [[Z]], -15
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP1]], -14
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %z = zext i4 %v to i8
  %cast = mul i8 %z, 18
  %cmp = icmp ult i8 %cast, 16
  ret i1 %cmp
}

; N = 4, M = 8
; n = 2^4 = 16, m = 2^8 = 256, C = 20
; k = floor((n - 1) * C / m) = floor(15 * 20 / 256) = 1
; CR = [-2^7, 60), Y = [45, 256)
; Invertible: yes on Y.inverse() = [60, 2^7)
define i1 @slt_noninvertible_crosses_wrap(i4 %v) {
; CHECK-LABEL: define i1 @slt_noninvertible_crosses_wrap(
; CHECK-SAME: i4 [[V:%.*]]) {
; CHECK-NEXT:    [[Z:%.*]] = zext i4 [[V]] to i8
; CHECK-NEXT:    [[TMP1:%.*]] = add i8 [[Z]], -7
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP1]], -4
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %z = zext i4 %v to i8
  %cast = mul i8 %z, 20
  %cmp = icmp slt i8 %cast, 60
  ret i1 %cmp
}

; Negative test
; N = 5, M = 8
; n = 2^5 = 32, m = 2^8 = 256, C = 20
; k = floor((n - 1) * C / m) = floor(31 * 20 / 256) = 2
; CR = [60, 256), Y = none
; Invertible: no
define i1 @uge_noninvertible_multiple_wraps(i5 %x) {
; CHECK-LABEL: define i1 @uge_noninvertible_multiple_wraps(
; CHECK-SAME: i5 [[X:%.*]]) {
; CHECK-NEXT:    [[Z:%.*]] = zext i5 [[X]] to i8
; CHECK-NEXT:    [[M:%.*]] = mul i8 [[Z]], 20
; CHECK-NEXT:    [[CMP:%.*]] = icmp uge i8 [[M]], 60
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %z = zext i5 %x to i8
  %m = mul i8 %z, 20
  %cmp = icmp uge i8 %m, 60
  ret i1 %cmp
}

; Tests for CmpCR built through add.

; N = 4, M = 8
; n = 2^4 = 16, m = 2^8 = 256, C = 20
; k = floor((n - 1) * C / m) = floor(15 * 20 / 256) = 1
; CmpCR = [110, 228), Y = [45, 256)
; Invertible: yes
define i1 @sge_invertible_tail_of_zext_mul_plus_offset(i4 %x) {
; CHECK-LABEL: define i1 @sge_invertible_tail_of_zext_mul_plus_offset(
; CHECK-SAME: i4 [[X:%.*]]) {
; CHECK-NEXT:    [[Z:%.*]] = zext i4 [[X]] to i8
; CHECK-NEXT:    [[TMP1:%.*]] = add i8 [[Z]], -6
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP1]], 6
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %z = zext i4 %x to i8
  %m = mul i8 %z, 20
  %a = sub i8 %m, 100
  %cmp = icmp sge i8 %a, 10
  ret i1 %cmp
}

; N = 4, M = 8
; n = 2^4 = 16, m = 2^8 = 256, C = 20
; k = floor((n - 1) * C / m) = floor(15 * 20 / 256) = 1
; CmpCR = [100, 200), Y = [45, 256)
; Invertible: yes
define i1 @ult_invertible_zext_mul_plus_offset(i4 %x) {
; CHECK-LABEL: define i1 @ult_invertible_zext_mul_plus_offset(
; CHECK-SAME: i4 [[X:%.*]]) {
; CHECK-NEXT:    [[Z:%.*]] = zext i4 [[X]] to i8
; CHECK-NEXT:    [[TMP1:%.*]] = add i8 [[Z]], -5
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ult i8 [[TMP1]], 5
; CHECK-NEXT:    ret i1 [[TMP2]]
;
  %z = zext i4 %x to i8
  %m = mul i8 %z, 20
  %a = add i8 %m, -100
  %cmp = icmp ult i8 %a, 100
  ret i1 %cmp
}

; N = 4, M = 8
; n = 2^4 = 16, m = 2^8 = 256, C = 20
; k = floor((n - 1) * C / m) = floor(15 * 20 / 256) = 1
; CmpCR = [122, 60), Y = [45, 256)
; Invertible: yes on CmpCR.inverse() = [60, 122)
define i1 @slt_inverse_invertible_zext_mul_plus_offset(i4 %x) {
; CHECK-LABEL: define i1 @slt_inverse_invertible_zext_mul_plus_offset(
; CHECK-SAME: i4 [[X:%.*]]) {
; CHECK-NEXT:    [[Z:%.*]] = zext i4 [[X]] to i8
; CHECK-NEXT:    [[TMP1:%.*]] = add i8 [[Z]], -7
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP1]], -4
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %z = zext i4 %x to i8
  %m = mul i8 %z, 20
  %a = add i8 %m, 6
  %cmp = icmp slt i8 %a, 66
  ret i1 %cmp
}


; TODO: support sext
; Test for icmp (mul (sext x), C) to icmp x.

; Use plain i4 -> i8 sext instead of extra range metadata so the tests cover
; the extension pattern directly.
define i1 @sccp_sext_mul_shrinks_to_prefix(i4 %x) {
; CHECK-LABEL: define i1 @sccp_sext_mul_shrinks_to_prefix(
; CHECK-SAME: i4 [[X:%.*]]) {
; CHECK-NEXT:    [[S:%.*]] = sext i4 [[X]] to i8
; CHECK-NEXT:    [[M:%.*]] = mul i8 [[S]], 20
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i8 [[M]], 60
; CHECK-NEXT:    ret i1 [[TMP1]]
;
  %s = sext i4 %x to i8
  %m = mul i8 %s, 20
  %cmp = icmp ult i8 %m, 60
  ret i1 %cmp
}


define i1 @sccp_sext_mul_shrinks_to_negative_suffix(i4 %x) {
; CHECK-LABEL: define i1 @sccp_sext_mul_shrinks_to_negative_suffix(
; CHECK-SAME: i4 [[X:%.*]]) {
; CHECK-NEXT:    [[S:%.*]] = sext i4 [[X]] to i8
; CHECK-NEXT:    [[M:%.*]] = mul i8 [[S]], 20
; CHECK-NEXT:    [[TMP1:%.*]] = icmp uge i8 [[M]], -60
; CHECK-NEXT:    ret i1 [[TMP1]]
;
  %s = sext i4 %x to i8
  %m = mul i8 %s, 20
  %cmp = icmp uge i8 %m, 196
  ret i1 %cmp
}


; Test for icmp (f(x), C) to icmp x

define i1 @sccp_mul_wraps_once_shrinks_to_middle_window(i8 range(i8 0, 18) %x) {
; CHECK-LABEL: define i1 @sccp_mul_wraps_once_shrinks_to_middle_window(
; CHECK-SAME: i8 range(i8 0, 18) [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = add i8 [[X]], -5
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ult i8 [[TMP1]], 8
; CHECK-NEXT:    ret i1 [[TMP2]]
;
  %m = mul i8 %x, 20
  %cmp = icmp uge i8 %m, 100
  ret i1 %cmp
}

define i1 @sccp_urem_wraps_once_shrinks_to_middle_window(i8 range(i8 8, 19) %x) {
; CHECK-LABEL: define i1 @sccp_urem_wraps_once_shrinks_to_middle_window(
; CHECK-SAME: i8 range(i8 8, 19) [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = add i8 [[X]], -10
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ult i8 [[TMP1]], 3
; CHECK-NEXT:    ret i1 [[TMP2]]
;
  %r = urem i8 %x, 10
  %cmp = icmp ult i8 %r, 3
  ret i1 %cmp
}

define i1 @sccp_negative_mul_wraps_once_shrinks_to_middle_window(i8 range(i8 3, 17) %x) {
; CHECK-LABEL: define i1 @sccp_negative_mul_wraps_once_shrinks_to_middle_window(
; CHECK-SAME: i8 range(i8 3, 17) [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = add i8 [[X]], -10
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ult i8 [[TMP1]], 3
; CHECK-NEXT:    ret i1 [[TMP2]]
;
  %m = mul i8 %x, -20
  %cmp = icmp ult i8 %m, 60
  ret i1 %cmp
}

define i1 @sccp_shl_wraps_once_shrinks_to_upper_window(i8 range(i8 5, 23) %x) {
; CHECK-LABEL: define i1 @sccp_shl_wraps_once_shrinks_to_upper_window(
; CHECK-SAME: i8 range(i8 5, 23) [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = add i8 [[X]], -10
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ult i8 [[TMP1]], 6
; CHECK-NEXT:    ret i1 [[TMP2]]
;
  %y = shl i8 %x, 4
  %cmp = icmp uge i8 %y, 160
  ret i1 %cmp
}

define i1 @sccp_mul_wraps_once_shrinks_to_two_value_window1(i8 range(i8 2, 6) %x) {
; CHECK-LABEL: define i1 @sccp_mul_wraps_once_shrinks_to_two_value_window1(
; CHECK-SAME: i8 range(i8 2, 6) [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = add i8 [[X]], -3
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP1]], 2
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %m = mul i8 %x, 100
  %a = add i8 %m, -200
  %cmp = icmp uge i8 %a, 100
  ret i1 %cmp
}

; TODO: support wrapped-range
define i1 @sccp_mul_wraps_once_shrinks_to_two_value_window2(i8 range(i8 -2, 2) %x) {
; CHECK-LABEL: define i1 @sccp_mul_wraps_once_shrinks_to_two_value_window2(
; CHECK-SAME: i8 range(i8 -2, 2) [[X:%.*]]) {
; CHECK-NEXT:    [[M:%.*]] = mul i8 [[X]], 100
; CHECK-NEXT:    [[A:%.*]] = add i8 [[M]], 56
; CHECK-NEXT:    [[CMP:%.*]] = icmp uge i8 [[A]], 100
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %m = mul i8 %x, 100
  %a = add i8 %m, -200
  %cmp = icmp uge i8 %a, 100
  ret i1 %cmp
}

define i1 @sccp_mul_wraps_once_shrinks_to_singleton(i8 range(i8 0, 18) %x) {
; CHECK-LABEL: define i1 @sccp_mul_wraps_once_shrinks_to_singleton(
; CHECK-SAME: i8 range(i8 0, 18) [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq i8 [[X]], 7
; CHECK-NEXT:    ret i1 [[TMP1]]
;
  %m = mul i8 %x, 20
  %cmp = icmp eq i8 %m, 140
  ret i1 %cmp
}

; TODO: support wrapped-range
; Wrapped-range counterparts for the generic f(x) tests above.

define i1 @sccp_mul_wraps_once_shrinks_to_wrapped_window(i8 range(i8 250, 6) %x) {
; CHECK-LABEL: define i1 @sccp_mul_wraps_once_shrinks_to_wrapped_window(
; CHECK-SAME: i8 range(i8 -6, 6) [[X:%.*]]) {
; CHECK-NEXT:    [[M:%.*]] = mul nsw i8 [[X]], 20
; CHECK-NEXT:    [[TMP2:%.*]] = icmp uge i8 [[M]], 100
; CHECK-NEXT:    ret i1 [[TMP2]]
;
  %m = mul i8 %x, 20
  %cmp = icmp uge i8 %m, 100
  ret i1 %cmp
}

define i1 @sccp_urem_wraps_once_shrinks_to_wrapped_window(i8 range(i8 250, 10) %x) {
; CHECK-LABEL: define i1 @sccp_urem_wraps_once_shrinks_to_wrapped_window(
; CHECK-SAME: i8 range(i8 -6, 10) [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[X]], 10
; CHECK-NEXT:    [[TMP2:%.*]] = icmp uge i8 [[R]], 6
; CHECK-NEXT:    ret i1 [[TMP2]]
;
  %r = urem i8 %x, 10
  %cmp = icmp uge i8 %r, 6
  ret i1 %cmp
}

define i1 @sccp_negative_mul_wraps_once_shrinks_to_wrapped_window(i8 range(i8 250, 6) %x) {
; CHECK-LABEL: define i1 @sccp_negative_mul_wraps_once_shrinks_to_wrapped_window(
; CHECK-SAME: i8 range(i8 -6, 6) [[X:%.*]]) {
; CHECK-NEXT:    [[M:%.*]] = mul nsw i8 [[X]], -20
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ult i8 [[M]], 60
; CHECK-NEXT:    ret i1 [[TMP2]]
;
  %m = mul i8 %x, -20
  %cmp = icmp ult i8 %m, 60
  ret i1 %cmp
}

define i1 @sccp_shl_wraps_once_shrinks_to_wrapped_suffix(i8 range(i8 250, 6) %x) {
; CHECK-LABEL: define i1 @sccp_shl_wraps_once_shrinks_to_wrapped_suffix(
; CHECK-SAME: i8 range(i8 -6, 6) [[X:%.*]]) {
; CHECK-NEXT:    [[Y:%.*]] = shl nsw i8 [[X]], 4
; CHECK-NEXT:    [[TMP1:%.*]] = icmp uge i8 [[Y]], -96
; CHECK-NEXT:    ret i1 [[TMP1]]
;
  %y = shl i8 %x, 4
  %cmp = icmp uge i8 %y, 160
  ret i1 %cmp
}

define i1 @sccp_mul_with_offset_wraps_once_shrinks_to_wrapped_window(i8 range(i8 250, 6) %x) {
; CHECK-LABEL: define i1 @sccp_mul_with_offset_wraps_once_shrinks_to_wrapped_window(
; CHECK-SAME: i8 range(i8 -6, 6) [[X:%.*]]) {
; CHECK-NEXT:    [[M:%.*]] = mul nsw i8 [[X]], 20
; CHECK-NEXT:    [[A:%.*]] = add i8 [[M]], 56
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i8 [[A]], 37
; CHECK-NEXT:    ret i1 [[TMP1]]
;
  %m = mul i8 %x, 20
  %a = add i8 %m, -200
  %cmp = icmp ult i8 %a, 37
  ret i1 %cmp
}

define i1 @sccp_mul_wraps_once_shrinks_to_wrapped_domain_singleton(i8 range(i8 252, 8) %x) {
; CHECK-LABEL: define i1 @sccp_mul_wraps_once_shrinks_to_wrapped_domain_singleton(
; CHECK-SAME: i8 range(i8 -4, 8) [[X:%.*]]) {
; CHECK-NEXT:    [[M:%.*]] = mul i8 [[X]], 20
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq i8 [[M]], -116
; CHECK-NEXT:    ret i1 [[TMP1]]
;
  %m = mul i8 %x, 20
  %cmp = icmp eq i8 %m, 140
  ret i1 %cmp
}

; Test for vector : f(vec) = C * vec, C is a splat constant.

define <4 x i1> @vec_splat_and(<4 x i32> range(i32 100, 456) %x) {
; CHECK-LABEL: define <4 x i1> @vec_splat_and(
; CHECK-SAME: <4 x i32> range(i32 100, 456) [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = add <4 x i32> [[X]], splat (i32 -230)
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult <4 x i32> [[TMP1]], splat (i32 26)
; CHECK-NEXT:    ret <4 x i1> [[CMP]]
;
  %m = and <4 x i32> %x, splat (i32 255)
  %cmp = icmp uge <4 x i32> %m, splat (i32 230)
  ret <4 x i1> %cmp
}

define <4 x i1> @vec_splat_mul(<4 x i8> range(i8 10, 17) %x) {
; CHECK-LABEL: define <4 x i1> @vec_splat_mul(
; CHECK-SAME: <4 x i8> range(i8 10, 17) [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = add <4 x i8> [[X]], splat (i8 -12)
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult <4 x i8> [[TMP1]], splat (i8 2)
; CHECK-NEXT:    ret <4 x i1> [[CMP]]
;
  %m = mul <4 x i8> %x, splat (i8 50)
  %add = add <4 x i8> %m, splat (i8 -40)
  %cmp = icmp ult <4 x i8> %add, splat (i8 110)
  ret <4 x i1> %cmp
}

define <4 x i1> @vec_splat_urem(<4 x i32> range(i32 1, 10) %x) {
; CHECK-LABEL: define <4 x i1> @vec_splat_urem(
; CHECK-SAME: <4 x i32> range(i32 1, 10) [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = add <4 x i32> [[X]], splat (i32 -2)
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult <4 x i32> [[TMP1]], splat (i32 6)
; CHECK-NEXT:    ret <4 x i1> [[CMP]]
;
  %m = urem <4 x i32> %x, splat (i32 8)
  %cmp = icmp uge <4 x i32> %m, splat (i32 2)
  ret <4 x i1> %cmp
}

define <4 x i1> @vec_splat_shl(<4 x i8> range(i8 1, 4) %x) {
; CHECK-LABEL: define <4 x i1> @vec_splat_shl(
; CHECK-SAME: <4 x i8> range(i8 1, 4) [[X:%.*]]) {
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne <4 x i8> [[X]], splat (i8 2)
; CHECK-NEXT:    ret <4 x i1> [[CMP]]
;
  %m = shl <4 x i8> %x, splat (i8 7)
  %cmp = icmp uge <4 x i8> %m, splat (i8 100)
  ret <4 x i1> %cmp
}
