; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=ipsccp -S %s | FileCheck %s

declare i1 @cond()

define i32 @test() {
; CHECK-LABEL: @test(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[P:%.*]] = phi i32 [ undef, [[ENTRY:%.*]] ], [ 0, [[LATCH_2:%.*]] ], [ [[P]], [[LOOP]] ]
; CHECK-NEXT:    [[C_1:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C_1]], label [[LOOP]], label [[LATCH_2]]
; CHECK:       latch.2:
; CHECK-NEXT:    [[C_2:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C_2]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret i32 [[P]]
;
entry:
  br label %loop

loop:
  %p = phi i32 [ undef, %entry ], [ 0, %latch.2 ], [ %p, %loop]
  %c.1 = call i1 @cond()
  br i1 %c.1, label %loop, label %latch.2

latch.2:
  %c.2 = call i1 @cond()
  br i1 %c.2, label %loop, label %exit

exit:
  ret i32 %p
}
