; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=ipsccp -S %s | FileCheck %s

define i1 @range_from_mul_nuw_nsw(i32 %a) {
; CHECK-LABEL: @range_from_mul_nuw_nsw(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i32 [[A:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    [[MUL:%.*]] = mul nuw nsw i32 [[A]], 10000
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[MUL]], -5000
; CHECK-NEXT:    ret i1 false
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp ne i32 %a, 0
  br i1 %cmp, label %then, label %else
then:
  %mul = mul nuw nsw i32 %a, 10000 ; Refined range via mul_nuw: [10000, 0)
  %add = add nsw i32 %mul, -5000   ; Range: [5000, UINT_MAX - 5000 + 1)
  %cond = icmp ult i32 %add, 4999
  ret i1 %cond
else:
  ret i1 0
}
