; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=sccp -S | FileCheck %s

define i1 @relax_range_check(i8 range(i8 0, 5) %x)  {
; CHECK-LABEL: define i1 @relax_range_check(
; CHECK-SAME: i8 range(i8 0, 5) [[X:%.*]]) {
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i8 [[X]], -3
; CHECK-NEXT:    [[RET:%.*]] = icmp uge i8 [[X]], 3
; CHECK-NEXT:    ret i1 [[RET]]
;
  %add = add i8 %x, -3
  %ret = icmp ult i8 %add, 2
  ret i1 %ret
}

define i1 @relax_range_check_highbits_check(i8 range(i8 2, 0) %x)  {
; CHECK-LABEL: define i1 @relax_range_check_highbits_check(
; CHECK-SAME: i8 range(i8 2, 0) [[X:%.*]]) {
; CHECK-NEXT:    [[AND:%.*]] = and i8 [[X]], -2
; CHECK-NEXT:    [[RET:%.*]] = icmp ult i8 [[X]], 4
; CHECK-NEXT:    ret i1 [[RET]]
;
  %and = and i8 %x, -2
  %ret = icmp eq i8 %and, 2
  ret i1 %ret
}

; Negative tests.

define i1 @relax_range_check_one_instruction(i8 range(i8 0, 5) %x)  {
; CHECK-LABEL: define i1 @relax_range_check_one_instruction(
; CHECK-SAME: i8 range(i8 0, 5) [[X:%.*]]) {
; CHECK-NEXT:    [[RET:%.*]] = icmp ult i8 [[X]], 2
; CHECK-NEXT:    ret i1 [[RET]]
;
  %ret = icmp ult i8 %x, 2
  ret i1 %ret
}

define i1 @relax_range_check_not_profitable(i8 range(i8 0, 6) %x)  {
; CHECK-LABEL: define i1 @relax_range_check_not_profitable(
; CHECK-SAME: i8 range(i8 0, 6) [[X:%.*]]) {
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i8 [[X]], -3
; CHECK-NEXT:    [[RET:%.*]] = icmp ult i8 [[ADD]], 2
; CHECK-NEXT:    ret i1 [[RET]]
;
  %add = add i8 %x, -3
  %ret = icmp ult i8 %add, 2
  ret i1 %ret
}

define i1 @relax_range_check_unknown_range(i64 %x)  {
; CHECK-LABEL: define i1 @relax_range_check_unknown_range(
; CHECK-SAME: i64 [[X:%.*]]) {
; CHECK-NEXT:    [[AND:%.*]] = and i64 [[X]], -67108864
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[AND]], 0
; CHECK-NEXT:    ret i1 [[TMP1]]
;
  %and = and i64 %x, -67108864
  %test = icmp eq i64 %and, 0
  ret i1 %test
}

define i1 @relax_range_check_highbits_check_multiuse(i8 range(i8 2, 0) %x)  {
; CHECK-LABEL: define i1 @relax_range_check_highbits_check_multiuse(
; CHECK-SAME: i8 range(i8 2, 0) [[X:%.*]]) {
; CHECK-NEXT:    [[AND:%.*]] = and i8 [[X]], -2
; CHECK-NEXT:    call void @use(i8 [[AND]])
; CHECK-NEXT:    [[RET:%.*]] = icmp eq i8 [[AND]], 2
; CHECK-NEXT:    ret i1 [[RET]]
;
  %and = and i8 %x, -2
  call void @use(i8 %and)
  %ret = icmp eq i8 %and, 2
  ret i1 %ret
}

define i1 @relax_range_check_multiuse(i8 range(i8 0, 5) %x)  {
; CHECK-LABEL: define i1 @relax_range_check_multiuse(
; CHECK-SAME: i8 range(i8 0, 5) [[X:%.*]]) {
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i8 [[X]], -3
; CHECK-NEXT:    call void @use(i8 [[ADD]])
; CHECK-NEXT:    [[RET:%.*]] = icmp ult i8 [[ADD]], 2
; CHECK-NEXT:    ret i1 [[RET]]
;
  %add = add i8 %x, -3
  call void @use(i8 %add)
  %ret = icmp ult i8 %add, 2
  ret i1 %ret
}

define i1 @range_check_to_icmp_eq1(i32 range(i32 0, 4) %x) {
; CHECK-LABEL: define i1 @range_check_to_icmp_eq1(
; CHECK-SAME: i32 range(i32 0, 4) [[X:%.*]]) {
; CHECK-NEXT:    [[OFF:%.*]] = add nsw i32 [[X]], -3
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq i32 [[X]], 3
; CHECK-NEXT:    ret i1 [[TMP1]]
;
  %off = add nsw i32 %x, -3
  %cmp = icmp ult i32 %off, 2
  ret i1 %cmp
}

define i1 @range_check_to_icmp_eq2(i32 range(i32 -1, 2) %x) {
; CHECK-LABEL: define i1 @range_check_to_icmp_eq2(
; CHECK-SAME: i32 range(i32 -1, 2) [[X:%.*]]) {
; CHECK-NEXT:    [[OFF:%.*]] = add nsw i32 [[X]], -1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[X]], 1
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %off = add nsw i32 %x, -1
  %cmp = icmp ult i32 %off, -2
  ret i1 %cmp
}

define i1 @range_check_to_icmp_ult(i8 range(i8 2, 10) %x) {
; CHECK-LABEL: define i1 @range_check_to_icmp_ult(
; CHECK-SAME: i8 range(i8 2, 10) [[X:%.*]]) {
; CHECK-NEXT:    [[OFF:%.*]] = add nsw i8 [[X]], -2
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i8 [[X]], 6
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %off = add i8 %x, -2
  %cmp = icmp ult i8 %off, 4
  ret i1 %cmp
}

define i1 @range_check_to_icmp_uge(i8 range(i8 2, 6) %x) {
; CHECK-LABEL: define i1 @range_check_to_icmp_uge(
; CHECK-SAME: i8 range(i8 2, 6) [[X:%.*]]) {
; CHECK-NEXT:    [[OFF:%.*]] = add nsw i8 [[X]], -4
; CHECK-NEXT:    [[CMP:%.*]] = icmp uge i8 [[X]], 4
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %off = add nsw i8 %x, -4
  %cmp = icmp ult i8 %off, 2
  ret i1 %cmp
}

define i1 @range_check_to_icmp_slt(i8 range(i8 -56, 20) %x) {
; CHECK-LABEL: define i1 @range_check_to_icmp_slt(
; CHECK-SAME: i8 range(i8 -56, 20) [[X:%.*]]) {
; CHECK-NEXT:    [[OFF:%.*]] = add nsw i8 [[X]], 56
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i8 [[X]], -6
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %off = add nsw i8 %x, 56
  %cmp = icmp ult i8 %off, 50
  ret i1 %cmp
}

define i1 @range_check_to_icmp_sge(i8 range(i8 -56, 20) %x) {
; CHECK-LABEL: define i1 @range_check_to_icmp_sge(
; CHECK-SAME: i8 range(i8 -56, 20) [[X:%.*]]) {
; CHECK-NEXT:    [[OFF:%.*]] = add nsw i8 [[X]], 16
; CHECK-NEXT:    [[CMP:%.*]] = icmp sge i8 [[X]], -16
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %off = add nsw i8 %x, 16
  %cmp = icmp ult i8 %off, 36
  ret i1 %cmp
}

; Cover the early exit when ActiveCmpCR is already a one-icmp check.

define i1 @range_check_intersection_to_icmp_eq(i32 range(i32 0, 4) %x) {
; CHECK-LABEL: define i1 @range_check_intersection_to_icmp_eq(
; CHECK-SAME: i32 range(i32 0, 4) [[X:%.*]]) {
; CHECK-NEXT:    [[OFF:%.*]] = add nsw i32 [[X]], -3
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[X]], 3
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %off = add nsw i32 %x, -3
  %cmp = icmp ult i32 %off, 2
  ret i1 %cmp
}

define i1 @range_check_intersection_to_icmp_ult(i8 range(i8 0, 10) %x) {
; CHECK-LABEL: define i1 @range_check_intersection_to_icmp_ult(
; CHECK-SAME: i8 range(i8 0, 10) [[X:%.*]]) {
; CHECK-NEXT:    [[OFF:%.*]] = add nuw nsw i8 [[X]], 2
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i8 [[X]], 4
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %off = add i8 %x, 2
  %cmp = icmp ult i8 %off, 6
  ret i1 %cmp
}

define i1 @range_check_intersection_to_icmp_slt(i8 range(i8 -128, -100) %x) {
; CHECK-LABEL: define i1 @range_check_intersection_to_icmp_slt(
; CHECK-SAME: i8 range(i8 -128, -100) [[X:%.*]]) {
; CHECK-NEXT:    [[OFF:%.*]] = add i8 [[X]], -120
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i8 [[X]], -118
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %off = add i8 %x, -120
  %cmp = icmp ult i8 %off, 18
  ret i1 %cmp
}

define i1 @range_check_intersection_to_icmp_uge(i8 range(i8 -6, 0) %x) {
; CHECK-LABEL: define i1 @range_check_intersection_to_icmp_uge(
; CHECK-SAME: i8 range(i8 -6, 0) [[X:%.*]]) {
; CHECK-NEXT:    [[OFF:%.*]] = add nsw i8 [[X]], 2
; CHECK-NEXT:    [[CMP:%.*]] = icmp uge i8 [[X]], -2
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %off = add i8 %x, 2
  %cmp = icmp ult i8 %off, 6
  ret i1 %cmp
}

define i1 @range_check_intersection_to_icmp_sge(i8 range(i8 120, -128) %x) {
; CHECK-LABEL: define i1 @range_check_intersection_to_icmp_sge(
; CHECK-SAME: i8 range(i8 120, -128) [[X:%.*]]) {
; CHECK-NEXT:    [[OFF:%.*]] = add nsw i8 [[X]], -122
; CHECK-NEXT:    [[CMP:%.*]] = icmp sge i8 [[X]], 122
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %off = add i8 %x, -122
  %cmp = icmp ult i8 %off, 14
  ret i1 %cmp
}

; Negative test: CmpCR relaxation cannot perform when x's range is nuw and nsw.
define i1 @range_check_nsw_nuw(i8 range(i8 -20, -56) %x) {
; CHECK-LABEL: define i1 @range_check_nsw_nuw(
; CHECK-SAME: i8 range(i8 -20, -56) [[X:%.*]]) {
; CHECK-NEXT:    [[OFF:%.*]] = add i8 [[X]], 20
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i8 [[OFF]], 14
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %off = add i8 %x, 20
  %cmp = icmp ult i8 %off, 14
  ret i1 %cmp
}

declare void @use(i8)
