; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=ipsccp -S | FileCheck %s

define internal i32 @testf(i1 %c, i1 %arg) {
; CHECK-LABEL: define internal range(i32 10, 12) i32 @testf(
; CHECK-SAME: i1 [[C:%.*]], i1 [[ARG:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C]], label %[[IF_COND:.*]], label %[[IF_END:.*]]
; CHECK:       [[IF_COND]]:
; CHECK-NEXT:    br i1 [[ARG]], label %[[IF_THEN:.*]], label %[[IF_END]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    ret i32 11
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    ret i32 10
;
entry:
  br i1 %c, label %if.cond, label %if.end

if.cond:
  br i1 %arg, label %if.then, label %if.end

if.then:                                          ; preds = %entry, %if.then
  ret i32 11

if.end:                                          ; preds = %if.then1, %entry
  ret i32 10
}

;
define internal i32 @test1(i1 %c, i1 %arg) {
; CHECK-LABEL: define internal range(i32 0, 100) i32 @test1(
; CHECK-SAME: i1 [[C:%.*]], i1 [[ARG:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[IF_THEN:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @testf(i1 [[C]], i1 [[ARG]])
; CHECK-NEXT:    [[RES:%.*]] = icmp eq i32 [[CALL]], 10
; CHECK-NEXT:    br i1 [[RES]], label %[[RET1:.*]], label %[[RET2:.*]]
; CHECK:       [[RET1]]:
; CHECK-NEXT:    ret i32 99
; CHECK:       [[RET2]]:
; CHECK-NEXT:    ret i32 0
;
entry:
  br label %if.then

if.then:                                          ; preds = %entry, %if.then
  %call = call i32 @testf(i1 %c, i1 %arg)
  %res = icmp eq i32 %call, 10
  br i1 %res, label %ret1, label %ret2

ret1:                                           ; preds = %if.then, %entry
  ret i32 99

ret2:                                           ; preds = %if.then, %entry
  ret i32 0
}

;
define i32 @main(i1 %c) {
; CHECK-LABEL: define i32 @main(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:    [[RES:%.*]] = call i32 @test1(i1 [[C]])
; CHECK-NEXT:    ret i32 [[RES]]
;
  %res = call i32 @test1(i1 %c)
  ret i32 %res
}
