; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -mtriple=riscv32 -mattr=+a,+zabha < %s | FileCheck %s --check-prefixes=RV32IA-ZABHA
; RUN: llc -global-isel -mtriple=riscv32 -mattr=+a < %s | FileCheck %s --check-prefixes=RV32IA
; RUN: llc -global-isel -mtriple=riscv32 < %s | FileCheck %s --check-prefixes=RV32I
; RUN: llc -global-isel -mtriple=riscv64 -mattr=+a,+zabha < %s | FileCheck %s --check-prefixes=RV64IA-ZABHA
; RUN: llc -global-isel -mtriple=riscv64 -mattr=+a < %s | FileCheck %s --check-prefixes=RV64IA
; RUN: llc -global-isel -mtriple=riscv64 < %s | FileCheck %s --check-prefixes=RV64I

define i8 @atomicrmw_and_i8_monotonic(ptr %ptr, i8 %val) nounwind {
; RV32IA-ZABHA-LABEL: atomicrmw_and_i8_monotonic:
; RV32IA-ZABHA:       # %bb.0:
; RV32IA-ZABHA-NEXT:    amoand.b a0, a1, (a0)
; RV32IA-ZABHA-NEXT:    ret
;
; RV32IA-LABEL: atomicrmw_and_i8_monotonic:
; RV32IA:       # %bb.0:
; RV32IA-NEXT:    andi a2, a0, 3
; RV32IA-NEXT:    li a3, 255
; RV32IA-NEXT:    slli a2, a2, 3
; RV32IA-NEXT:    sll a3, a3, a2
; RV32IA-NEXT:    zext.b a1, a1
; RV32IA-NEXT:    not a3, a3
; RV32IA-NEXT:    sll a1, a1, a2
; RV32IA-NEXT:    andi a0, a0, -4
; RV32IA-NEXT:    or a1, a1, a3
; RV32IA-NEXT:    amoand.w a0, a1, (a0)
; RV32IA-NEXT:    srl a0, a0, a2
; RV32IA-NEXT:    ret
;
; RV32I-LABEL: atomicrmw_and_i8_monotonic:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    li a2, 0
; RV32I-NEXT:    call __atomic_fetch_and_1
; RV32I-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    ret
;
; RV64IA-ZABHA-LABEL: atomicrmw_and_i8_monotonic:
; RV64IA-ZABHA:       # %bb.0:
; RV64IA-ZABHA-NEXT:    amoand.b a0, a1, (a0)
; RV64IA-ZABHA-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    slli a2, a2, 3
; RV64IA-NEXT:    sllw a3, a3, a2
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sllw a1, a1, a2
; RV64IA-NEXT:    andi a0, a0, -4
; RV64IA-NEXT:    or a1, a1, a3
; RV64IA-NEXT:    amoand.w a0, a1, (a0)
; RV64IA-NEXT:    srlw a0, a0, a2
; RV64IA-NEXT:    ret
;
; RV64I-LABEL: atomicrmw_and_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    li a2, 0
; RV64I-NEXT:    call __atomic_fetch_and_1
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    ret
  %res = atomicrmw and ptr %ptr, i8 %val monotonic
  ret i8 %res
}

define i16 @atomicrmw_and_i16_monotonic(ptr %ptr, i16 %val) nounwind {
; RV32IA-ZABHA-LABEL: atomicrmw_and_i16_monotonic:
; RV32IA-ZABHA:       # %bb.0:
; RV32IA-ZABHA-NEXT:    amoand.h a0, a1, (a0)
; RV32IA-ZABHA-NEXT:    ret
;
; RV32IA-LABEL: atomicrmw_and_i16_monotonic:
; RV32IA:       # %bb.0:
; RV32IA-NEXT:    lui a2, 16
; RV32IA-NEXT:    andi a3, a0, 3
; RV32IA-NEXT:    addi a2, a2, -1
; RV32IA-NEXT:    slli a3, a3, 3
; RV32IA-NEXT:    sll a4, a2, a3
; RV32IA-NEXT:    and a1, a1, a2
; RV32IA-NEXT:    not a2, a4
; RV32IA-NEXT:    sll a1, a1, a3
; RV32IA-NEXT:    andi a0, a0, -4
; RV32IA-NEXT:    or a1, a1, a2
; RV32IA-NEXT:    amoand.w a0, a1, (a0)
; RV32IA-NEXT:    srl a0, a0, a3
; RV32IA-NEXT:    ret
;
; RV32I-LABEL: atomicrmw_and_i16_monotonic:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    li a2, 0
; RV32I-NEXT:    call __atomic_fetch_and_2
; RV32I-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    ret
;
; RV64IA-ZABHA-LABEL: atomicrmw_and_i16_monotonic:
; RV64IA-ZABHA:       # %bb.0:
; RV64IA-ZABHA-NEXT:    amoand.h a0, a1, (a0)
; RV64IA-ZABHA-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lui a2, 16
; RV64IA-NEXT:    andi a3, a0, 3
; RV64IA-NEXT:    addi a2, a2, -1
; RV64IA-NEXT:    slli a3, a3, 3
; RV64IA-NEXT:    sllw a4, a2, a3
; RV64IA-NEXT:    and a1, a1, a2
; RV64IA-NEXT:    not a2, a4
; RV64IA-NEXT:    sllw a1, a1, a3
; RV64IA-NEXT:    andi a0, a0, -4
; RV64IA-NEXT:    or a1, a1, a2
; RV64IA-NEXT:    amoand.w a0, a1, (a0)
; RV64IA-NEXT:    srlw a0, a0, a3
; RV64IA-NEXT:    ret
;
; RV64I-LABEL: atomicrmw_and_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    li a2, 0
; RV64I-NEXT:    call __atomic_fetch_and_2
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    ret
  %res = atomicrmw and ptr %ptr, i16 %val monotonic
  ret i16 %res
}

define i32 @atomicrmw_and_i32_monotonic(ptr %ptr, i32 %val) nounwind {
; RV32IA-ZABHA-LABEL: atomicrmw_and_i32_monotonic:
; RV32IA-ZABHA:       # %bb.0:
; RV32IA-ZABHA-NEXT:    amoand.w a0, a1, (a0)
; RV32IA-ZABHA-NEXT:    ret
;
; RV32IA-LABEL: atomicrmw_and_i32_monotonic:
; RV32IA:       # %bb.0:
; RV32IA-NEXT:    amoand.w a0, a1, (a0)
; RV32IA-NEXT:    ret
;
; RV32I-LABEL: atomicrmw_and_i32_monotonic:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    li a2, 0
; RV32I-NEXT:    call __atomic_fetch_and_4
; RV32I-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    ret
;
; RV64IA-ZABHA-LABEL: atomicrmw_and_i32_monotonic:
; RV64IA-ZABHA:       # %bb.0:
; RV64IA-ZABHA-NEXT:    amoand.w a0, a1, (a0)
; RV64IA-ZABHA-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoand.w a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-LABEL: atomicrmw_and_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    li a2, 0
; RV64I-NEXT:    call __atomic_fetch_and_4
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    ret
  %res = atomicrmw and ptr %ptr, i32 %val monotonic
  ret i32 %res
}

define i64 @atomicrmw_and_i64_monotonic(ptr %ptr, i64 %val) nounwind {
; RV32IA-ZABHA-LABEL: atomicrmw_and_i64_monotonic:
; RV32IA-ZABHA:       # %bb.0:
; RV32IA-ZABHA-NEXT:    addi sp, sp, -16
; RV32IA-ZABHA-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32IA-ZABHA-NEXT:    li a3, 0
; RV32IA-ZABHA-NEXT:    call __atomic_fetch_and_8
; RV32IA-ZABHA-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32IA-ZABHA-NEXT:    addi sp, sp, 16
; RV32IA-ZABHA-NEXT:    ret
;
; RV32IA-LABEL: atomicrmw_and_i64_monotonic:
; RV32IA:       # %bb.0:
; RV32IA-NEXT:    addi sp, sp, -16
; RV32IA-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32IA-NEXT:    li a3, 0
; RV32IA-NEXT:    call __atomic_fetch_and_8
; RV32IA-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32IA-NEXT:    addi sp, sp, 16
; RV32IA-NEXT:    ret
;
; RV32I-LABEL: atomicrmw_and_i64_monotonic:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    li a3, 0
; RV32I-NEXT:    call __atomic_fetch_and_8
; RV32I-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    ret
;
; RV64IA-ZABHA-LABEL: atomicrmw_and_i64_monotonic:
; RV64IA-ZABHA:       # %bb.0:
; RV64IA-ZABHA-NEXT:    amoand.d a0, a1, (a0)
; RV64IA-ZABHA-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoand.d a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-LABEL: atomicrmw_and_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    li a2, 0
; RV64I-NEXT:    call __atomic_fetch_and_8
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    ret
  %res = atomicrmw and ptr %ptr, i64 %val monotonic
  ret i64 %res
}

define i8 @atomicrmw_or_i8_monotonic(ptr %ptr, i8 %val) nounwind {
; RV32IA-ZABHA-LABEL: atomicrmw_or_i8_monotonic:
; RV32IA-ZABHA:       # %bb.0:
; RV32IA-ZABHA-NEXT:    amoor.b a0, a1, (a0)
; RV32IA-ZABHA-NEXT:    ret
;
; RV32IA-LABEL: atomicrmw_or_i8_monotonic:
; RV32IA:       # %bb.0:
; RV32IA-NEXT:    andi a2, a0, 3
; RV32IA-NEXT:    slli a2, a2, 3
; RV32IA-NEXT:    zext.b a1, a1
; RV32IA-NEXT:    andi a0, a0, -4
; RV32IA-NEXT:    sll a1, a1, a2
; RV32IA-NEXT:    amoor.w a0, a1, (a0)
; RV32IA-NEXT:    srl a0, a0, a2
; RV32IA-NEXT:    ret
;
; RV32I-LABEL: atomicrmw_or_i8_monotonic:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    li a2, 0
; RV32I-NEXT:    call __atomic_fetch_or_1
; RV32I-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    ret
;
; RV64IA-ZABHA-LABEL: atomicrmw_or_i8_monotonic:
; RV64IA-ZABHA:       # %bb.0:
; RV64IA-ZABHA-NEXT:    amoor.b a0, a1, (a0)
; RV64IA-ZABHA-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, 3
; RV64IA-NEXT:    slli a2, a2, 3
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    andi a0, a0, -4
; RV64IA-NEXT:    sllw a1, a1, a2
; RV64IA-NEXT:    amoor.w a0, a1, (a0)
; RV64IA-NEXT:    srlw a0, a0, a2
; RV64IA-NEXT:    ret
;
; RV64I-LABEL: atomicrmw_or_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    li a2, 0
; RV64I-NEXT:    call __atomic_fetch_or_1
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    ret
  %res = atomicrmw or ptr %ptr, i8 %val monotonic
  ret i8 %res
}

define i16 @atomicrmw_or_i16_monotonic(ptr %ptr, i16 %val) nounwind {
; RV32IA-ZABHA-LABEL: atomicrmw_or_i16_monotonic:
; RV32IA-ZABHA:       # %bb.0:
; RV32IA-ZABHA-NEXT:    amoor.h a0, a1, (a0)
; RV32IA-ZABHA-NEXT:    ret
;
; RV32IA-LABEL: atomicrmw_or_i16_monotonic:
; RV32IA:       # %bb.0:
; RV32IA-NEXT:    andi a2, a0, 3
; RV32IA-NEXT:    slli a1, a1, 16
; RV32IA-NEXT:    slli a2, a2, 3
; RV32IA-NEXT:    srli a1, a1, 16
; RV32IA-NEXT:    andi a0, a0, -4
; RV32IA-NEXT:    sll a1, a1, a2
; RV32IA-NEXT:    amoor.w a0, a1, (a0)
; RV32IA-NEXT:    srl a0, a0, a2
; RV32IA-NEXT:    ret
;
; RV32I-LABEL: atomicrmw_or_i16_monotonic:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    li a2, 0
; RV32I-NEXT:    call __atomic_fetch_or_2
; RV32I-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    ret
;
; RV64IA-ZABHA-LABEL: atomicrmw_or_i16_monotonic:
; RV64IA-ZABHA:       # %bb.0:
; RV64IA-ZABHA-NEXT:    amoor.h a0, a1, (a0)
; RV64IA-ZABHA-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, 3
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    slli a2, a2, 3
; RV64IA-NEXT:    srli a1, a1, 48
; RV64IA-NEXT:    andi a0, a0, -4
; RV64IA-NEXT:    sllw a1, a1, a2
; RV64IA-NEXT:    amoor.w a0, a1, (a0)
; RV64IA-NEXT:    srlw a0, a0, a2
; RV64IA-NEXT:    ret
;
; RV64I-LABEL: atomicrmw_or_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    li a2, 0
; RV64I-NEXT:    call __atomic_fetch_or_2
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    ret
  %res = atomicrmw or ptr %ptr, i16 %val monotonic
  ret i16 %res
}

define i32 @atomicrmw_or_i32_monotonic(ptr %ptr, i32 %val) nounwind {
; RV32IA-ZABHA-LABEL: atomicrmw_or_i32_monotonic:
; RV32IA-ZABHA:       # %bb.0:
; RV32IA-ZABHA-NEXT:    amoor.w a0, a1, (a0)
; RV32IA-ZABHA-NEXT:    ret
;
; RV32IA-LABEL: atomicrmw_or_i32_monotonic:
; RV32IA:       # %bb.0:
; RV32IA-NEXT:    amoor.w a0, a1, (a0)
; RV32IA-NEXT:    ret
;
; RV32I-LABEL: atomicrmw_or_i32_monotonic:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    li a2, 0
; RV32I-NEXT:    call __atomic_fetch_or_4
; RV32I-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    ret
;
; RV64IA-ZABHA-LABEL: atomicrmw_or_i32_monotonic:
; RV64IA-ZABHA:       # %bb.0:
; RV64IA-ZABHA-NEXT:    amoor.w a0, a1, (a0)
; RV64IA-ZABHA-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoor.w a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-LABEL: atomicrmw_or_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    li a2, 0
; RV64I-NEXT:    call __atomic_fetch_or_4
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    ret
  %res = atomicrmw or ptr %ptr, i32 %val monotonic
  ret i32 %res
}

define i64 @atomicrmw_or_i64_monotonic(ptr %ptr, i64 %val) nounwind {
; RV32IA-ZABHA-LABEL: atomicrmw_or_i64_monotonic:
; RV32IA-ZABHA:       # %bb.0:
; RV32IA-ZABHA-NEXT:    addi sp, sp, -16
; RV32IA-ZABHA-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32IA-ZABHA-NEXT:    li a3, 0
; RV32IA-ZABHA-NEXT:    call __atomic_fetch_or_8
; RV32IA-ZABHA-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32IA-ZABHA-NEXT:    addi sp, sp, 16
; RV32IA-ZABHA-NEXT:    ret
;
; RV32IA-LABEL: atomicrmw_or_i64_monotonic:
; RV32IA:       # %bb.0:
; RV32IA-NEXT:    addi sp, sp, -16
; RV32IA-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32IA-NEXT:    li a3, 0
; RV32IA-NEXT:    call __atomic_fetch_or_8
; RV32IA-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32IA-NEXT:    addi sp, sp, 16
; RV32IA-NEXT:    ret
;
; RV32I-LABEL: atomicrmw_or_i64_monotonic:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    li a3, 0
; RV32I-NEXT:    call __atomic_fetch_or_8
; RV32I-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    ret
;
; RV64IA-ZABHA-LABEL: atomicrmw_or_i64_monotonic:
; RV64IA-ZABHA:       # %bb.0:
; RV64IA-ZABHA-NEXT:    amoor.d a0, a1, (a0)
; RV64IA-ZABHA-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoor.d a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-LABEL: atomicrmw_or_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    li a2, 0
; RV64I-NEXT:    call __atomic_fetch_or_8
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    ret
  %res = atomicrmw or ptr %ptr, i64 %val monotonic
  ret i64 %res
}

define i8 @atomicrmw_xor_i8_monotonic(ptr %ptr, i8 %val) nounwind {
; RV32IA-ZABHA-LABEL: atomicrmw_xor_i8_monotonic:
; RV32IA-ZABHA:       # %bb.0:
; RV32IA-ZABHA-NEXT:    amoxor.b a0, a1, (a0)
; RV32IA-ZABHA-NEXT:    ret
;
; RV32IA-LABEL: atomicrmw_xor_i8_monotonic:
; RV32IA:       # %bb.0:
; RV32IA-NEXT:    andi a2, a0, 3
; RV32IA-NEXT:    slli a2, a2, 3
; RV32IA-NEXT:    zext.b a1, a1
; RV32IA-NEXT:    andi a0, a0, -4
; RV32IA-NEXT:    sll a1, a1, a2
; RV32IA-NEXT:    amoxor.w a0, a1, (a0)
; RV32IA-NEXT:    srl a0, a0, a2
; RV32IA-NEXT:    ret
;
; RV32I-LABEL: atomicrmw_xor_i8_monotonic:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    li a2, 0
; RV32I-NEXT:    call __atomic_fetch_xor_1
; RV32I-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    ret
;
; RV64IA-ZABHA-LABEL: atomicrmw_xor_i8_monotonic:
; RV64IA-ZABHA:       # %bb.0:
; RV64IA-ZABHA-NEXT:    amoxor.b a0, a1, (a0)
; RV64IA-ZABHA-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, 3
; RV64IA-NEXT:    slli a2, a2, 3
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    andi a0, a0, -4
; RV64IA-NEXT:    sllw a1, a1, a2
; RV64IA-NEXT:    amoxor.w a0, a1, (a0)
; RV64IA-NEXT:    srlw a0, a0, a2
; RV64IA-NEXT:    ret
;
; RV64I-LABEL: atomicrmw_xor_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    li a2, 0
; RV64I-NEXT:    call __atomic_fetch_xor_1
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    ret
  %res = atomicrmw xor ptr %ptr, i8 %val monotonic
  ret i8 %res
}

define i16 @atomicrmw_xor_i16_monotonic(ptr %ptr, i16 %val) nounwind {
; RV32IA-ZABHA-LABEL: atomicrmw_xor_i16_monotonic:
; RV32IA-ZABHA:       # %bb.0:
; RV32IA-ZABHA-NEXT:    amoxor.h a0, a1, (a0)
; RV32IA-ZABHA-NEXT:    ret
;
; RV32IA-LABEL: atomicrmw_xor_i16_monotonic:
; RV32IA:       # %bb.0:
; RV32IA-NEXT:    andi a2, a0, 3
; RV32IA-NEXT:    slli a1, a1, 16
; RV32IA-NEXT:    slli a2, a2, 3
; RV32IA-NEXT:    srli a1, a1, 16
; RV32IA-NEXT:    andi a0, a0, -4
; RV32IA-NEXT:    sll a1, a1, a2
; RV32IA-NEXT:    amoxor.w a0, a1, (a0)
; RV32IA-NEXT:    srl a0, a0, a2
; RV32IA-NEXT:    ret
;
; RV32I-LABEL: atomicrmw_xor_i16_monotonic:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    li a2, 0
; RV32I-NEXT:    call __atomic_fetch_xor_2
; RV32I-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    ret
;
; RV64IA-ZABHA-LABEL: atomicrmw_xor_i16_monotonic:
; RV64IA-ZABHA:       # %bb.0:
; RV64IA-ZABHA-NEXT:    amoxor.h a0, a1, (a0)
; RV64IA-ZABHA-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, 3
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    slli a2, a2, 3
; RV64IA-NEXT:    srli a1, a1, 48
; RV64IA-NEXT:    andi a0, a0, -4
; RV64IA-NEXT:    sllw a1, a1, a2
; RV64IA-NEXT:    amoxor.w a0, a1, (a0)
; RV64IA-NEXT:    srlw a0, a0, a2
; RV64IA-NEXT:    ret
;
; RV64I-LABEL: atomicrmw_xor_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    li a2, 0
; RV64I-NEXT:    call __atomic_fetch_xor_2
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    ret
  %res = atomicrmw xor ptr %ptr, i16 %val monotonic
  ret i16 %res
}

define i32 @atomicrmw_xor_i32_monotonic(ptr %ptr, i32 %val) nounwind {
; RV32IA-ZABHA-LABEL: atomicrmw_xor_i32_monotonic:
; RV32IA-ZABHA:       # %bb.0:
; RV32IA-ZABHA-NEXT:    amoxor.w a0, a1, (a0)
; RV32IA-ZABHA-NEXT:    ret
;
; RV32IA-LABEL: atomicrmw_xor_i32_monotonic:
; RV32IA:       # %bb.0:
; RV32IA-NEXT:    amoxor.w a0, a1, (a0)
; RV32IA-NEXT:    ret
;
; RV32I-LABEL: atomicrmw_xor_i32_monotonic:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    li a2, 0
; RV32I-NEXT:    call __atomic_fetch_xor_4
; RV32I-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    ret
;
; RV64IA-ZABHA-LABEL: atomicrmw_xor_i32_monotonic:
; RV64IA-ZABHA:       # %bb.0:
; RV64IA-ZABHA-NEXT:    amoxor.w a0, a1, (a0)
; RV64IA-ZABHA-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoxor.w a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-LABEL: atomicrmw_xor_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    li a2, 0
; RV64I-NEXT:    call __atomic_fetch_xor_4
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    ret
  %res = atomicrmw xor ptr %ptr, i32 %val monotonic
  ret i32 %res
}

define i64 @atomicrmw_xor_i64_monotonic(ptr %ptr, i64 %val) nounwind {
; RV32IA-ZABHA-LABEL: atomicrmw_xor_i64_monotonic:
; RV32IA-ZABHA:       # %bb.0:
; RV32IA-ZABHA-NEXT:    addi sp, sp, -16
; RV32IA-ZABHA-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32IA-ZABHA-NEXT:    li a3, 0
; RV32IA-ZABHA-NEXT:    call __atomic_fetch_xor_8
; RV32IA-ZABHA-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32IA-ZABHA-NEXT:    addi sp, sp, 16
; RV32IA-ZABHA-NEXT:    ret
;
; RV32IA-LABEL: atomicrmw_xor_i64_monotonic:
; RV32IA:       # %bb.0:
; RV32IA-NEXT:    addi sp, sp, -16
; RV32IA-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32IA-NEXT:    li a3, 0
; RV32IA-NEXT:    call __atomic_fetch_xor_8
; RV32IA-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32IA-NEXT:    addi sp, sp, 16
; RV32IA-NEXT:    ret
;
; RV32I-LABEL: atomicrmw_xor_i64_monotonic:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    li a3, 0
; RV32I-NEXT:    call __atomic_fetch_xor_8
; RV32I-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    ret
;
; RV64IA-ZABHA-LABEL: atomicrmw_xor_i64_monotonic:
; RV64IA-ZABHA:       # %bb.0:
; RV64IA-ZABHA-NEXT:    amoxor.d a0, a1, (a0)
; RV64IA-ZABHA-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoxor.d a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-LABEL: atomicrmw_xor_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    li a2, 0
; RV64I-NEXT:    call __atomic_fetch_xor_8
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    ret
  %res = atomicrmw xor ptr %ptr, i64 %val monotonic
  ret i64 %res
}
