; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel=1 -mtriple=riscv32 -mattr=+f,+d < %s | FileCheck %s

; Check the GHC call convention works (rv32)

@base  = external global i32 ; assigned to register: s1
@sp    = external global i32 ; assigned to register: s2
@hp    = external global i32 ; assigned to register: s3
@r1    = external global i32 ; assigned to register: s4
@r2    = external global i32 ; assigned to register: s5
@r3    = external global i32 ; assigned to register: s6
@r4    = external global i32 ; assigned to register: s7
@r5    = external global i32 ; assigned to register: s8
@r6    = external global i32 ; assigned to register: s9
@r7    = external global i32 ; assigned to register: s10
@splim = external global i32 ; assigned to register: s11

@f1 = external global float  ; assigned to register: fs0
@f2 = external global float  ; assigned to register: fs1
@f3 = external global float  ; assigned to register: fs2
@f4 = external global float  ; assigned to register: fs3
@f5 = external global float  ; assigned to register: fs4
@f6 = external global float  ; assigned to register: fs5

@d1 = external global double ; assigned to register: fs6
@d2 = external global double ; assigned to register: fs7
@d3 = external global double ; assigned to register: fs8
@d4 = external global double ; assigned to register: fs9
@d5 = external global double ; assigned to register: fs10
@d6 = external global double ; assigned to register: fs11

define ghccc void @foo() nounwind {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lui a0, %hi(d6)
; CHECK-NEXT:    lui a1, %hi(d5)
; CHECK-NEXT:    lui a2, %hi(d4)
; CHECK-NEXT:    lui a3, %hi(d3)
; CHECK-NEXT:    lui a4, %hi(d2)
; CHECK-NEXT:    lui a5, %hi(d1)
; CHECK-NEXT:    lui a6, %hi(f6)
; CHECK-NEXT:    lui a7, %hi(f5)
; CHECK-NEXT:    lui t0, %hi(f4)
; CHECK-NEXT:    lui t1, %hi(f3)
; CHECK-NEXT:    lui t2, %hi(f2)
; CHECK-NEXT:    lui t3, %hi(f1)
; CHECK-NEXT:    lui t4, %hi(splim)
; CHECK-NEXT:    lui t5, %hi(r7)
; CHECK-NEXT:    lui t6, %hi(r6)
; CHECK-NEXT:    lui s0, %hi(r5)
; CHECK-NEXT:    lui s1, %hi(r4)
; CHECK-NEXT:    lui s2, %hi(r3)
; CHECK-NEXT:    lui s3, %hi(r2)
; CHECK-NEXT:    lui s4, %hi(r1)
; CHECK-NEXT:    lui s5, %hi(hp)
; CHECK-NEXT:    lui s6, %hi(sp)
; CHECK-NEXT:    lui s7, %hi(base)
; CHECK-NEXT:    fld ft0, %lo(d6)(a0)
; CHECK-NEXT:    fld ft1, %lo(d5)(a1)
; CHECK-NEXT:    fld ft2, %lo(d4)(a2)
; CHECK-NEXT:    fld ft3, %lo(d3)(a3)
; CHECK-NEXT:    fld fa7, %lo(d2)(a4)
; CHECK-NEXT:    fld fa6, %lo(d1)(a5)
; CHECK-NEXT:    flw fa5, %lo(f6)(a6)
; CHECK-NEXT:    flw fa4, %lo(f5)(a7)
; CHECK-NEXT:    flw fa3, %lo(f4)(t0)
; CHECK-NEXT:    flw fa2, %lo(f3)(t1)
; CHECK-NEXT:    flw fa1, %lo(f2)(t2)
; CHECK-NEXT:    flw fa0, %lo(f1)(t3)
; CHECK-NEXT:    lw t0, %lo(splim)(t4)
; CHECK-NEXT:    lw t1, %lo(r7)(t5)
; CHECK-NEXT:    lw t2, %lo(r6)(t6)
; CHECK-NEXT:    lw a7, %lo(r5)(s0)
; CHECK-NEXT:    lw a6, %lo(r4)(s1)
; CHECK-NEXT:    lw a5, %lo(r3)(s2)
; CHECK-NEXT:    lw a4, %lo(r2)(s3)
; CHECK-NEXT:    lw a3, %lo(r1)(s4)
; CHECK-NEXT:    lw a2, %lo(hp)(s5)
; CHECK-NEXT:    lw a1, %lo(sp)(s6)
; CHECK-NEXT:    lw a0, %lo(base)(s7)
; CHECK-NEXT:    sw t2, 0(sp)
; CHECK-NEXT:    sw t1, 4(sp)
; CHECK-NEXT:    sw t0, 8(sp)
; CHECK-NEXT:    fsd ft3, 16(sp)
; CHECK-NEXT:    fsd ft2, 24(sp)
; CHECK-NEXT:    fsd ft1, 32(sp)
; CHECK-NEXT:    fsd ft0, 40(sp)
; CHECK-NEXT:    call bar
; CHECK-NEXT:    ret
entry:
  %0  = load double, ptr @d6
  %1  = load double, ptr @d5
  %2  = load double, ptr @d4
  %3  = load double, ptr @d3
  %4  = load double, ptr @d2
  %5  = load double, ptr @d1
  %6  = load float, ptr @f6
  %7  = load float, ptr @f5
  %8  = load float, ptr @f4
  %9  = load float, ptr @f3
  %10 = load float, ptr @f2
  %11 = load float, ptr @f1
  %12 = load i32, ptr @splim
  %13 = load i32, ptr @r7
  %14 = load i32, ptr @r6
  %15 = load i32, ptr @r5
  %16 = load i32, ptr @r4
  %17 = load i32, ptr @r3
  %18 = load i32, ptr @r2
  %19 = load i32, ptr @r1
  %20 = load i32, ptr @hp
  %21 = load i32, ptr @sp
  %22 = load i32, ptr @base
  tail call ghccc void @bar(i32 %22, i32 %21, i32 %20, i32 %19, i32 %18, i32 %17, i32 %16, i32 %15, i32 %14, i32 %13, i32 %12,
                            float %11, float %10, float %9, float %8, float %7, float %6,
                            double %5, double %4, double %3, double %2, double %1, double %0) nounwind
  ret void
}

declare ghccc void @bar(i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32,
                        float, float, float, float, float, float,
                        double, double, double, double, double, double)
