; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 -target-abi=ilp32f -mattr=+f,+zbs -global-isel < %s \
; RUN: | FileCheck %s -check-prefix=RV32I

; Excerpt from condops.ll
; Test that we don't crash on types larger than 64 bits.
define i64 @single_bit3(i80 %x, i64 %y) {
; RV32I-LABEL: single_bit3:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    mv a3, a0
; RV32I-NEXT:    li a0, 0
; RV32I-NEXT:    lh a3, 8(a3)
; RV32I-NEXT:    andi a4, a3, 1
; RV32I-NEXT:    li a3, 0
; RV32I-NEXT:    beqz a4, .LBB0_2
; RV32I-NEXT:  # %bb.1: # %entry
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:    mv a3, a2
; RV32I-NEXT:  .LBB0_2: # %entry
; RV32I-NEXT:    mv a1, a3
; RV32I-NEXT:    ret
entry:
  %and = and i80 %x, 18446744073709551616 ; 1 << 64
  %tobool.not = icmp eq i80 %and, 0
  %cond = select i1 %tobool.not, i64 0, i64 %y
  ret i64 %cond
}
