; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -global-isel -mtriple=riscv32 < %s \
; RUN:   | FileCheck -check-prefix=RV32I %s
; RUN: llc -global-isel -mtriple=riscv64 < %s \
; RUN:   | FileCheck -check-prefix=RV64I %s

declare void @llvm.memcpy.inline.p0.p0.i64(ptr noalias nocapture writeonly,
                                           ptr noalias nocapture readonly,
                                           i64 immarg, i1 immarg) #0

define void @test_memcpy_inline(ptr %dst, ptr readonly %src) {
; RV32I-LABEL: test_memcpy_inline:
; RV32I:       # %bb.0:
; RV32I-NEXT:    lbu a2, 0(a1)
; RV32I-NEXT:    sb a2, 0(a0)
; RV32I-NEXT:    lbu a1, 1(a1)
; RV32I-NEXT:    sb a1, 1(a0)
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_memcpy_inline:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lbu a2, 0(a1)
; RV64I-NEXT:    sb a2, 0(a0)
; RV64I-NEXT:    lbu a1, 1(a1)
; RV64I-NEXT:    sb a1, 1(a0)
; RV64I-NEXT:    ret
  call void @llvm.memcpy.inline.p0.p0.i64(ptr align 4 %dst, ptr align 4 %src, i64 2, i1 false)
  ret void
}

attributes #0 = { argmemonly nofree nounwind willreturn }
