; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -O3 -mtriple=riscv32 -mattr=+m -verify-machineinstrs -global-isel < %s \
; RUN:   | FileCheck %s -check-prefix=RV32I
; RUN: llc -O3 -mtriple=riscv64 -mattr=+m -verify-machineinstrs -global-isel < %s \
; RUN:   | FileCheck %s -check-prefix=RV64I

define i32 @smulfix_i32_scale_0(i32 %1, i32 %2) {
; RV32I-LABEL: smulfix_i32_scale_0:
; RV32I:       # %bb.0:
; RV32I-NEXT:    mul a0, a0, a1
; RV32I-NEXT:    ret
;
; RV64I-LABEL: smulfix_i32_scale_0:
; RV64I:       # %bb.0:
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    ret
  %m = call i32 @llvm.smul.fix.i32(i32 %1, i32 %2, i32 0)
  ret i32 %m
}

define i32 @smulfix_i32(i32 %1, i32 %2) {
; RV32I-LABEL: smulfix_i32:
; RV32I:       # %bb.0:
; RV32I-NEXT:    srai a2, a0, 31
; RV32I-NEXT:    srai a3, a1, 31
; RV32I-NEXT:    mul a4, a0, a1
; RV32I-NEXT:    mul a2, a2, a1
; RV32I-NEXT:    mulhu a1, a0, a1
; RV32I-NEXT:    mul a0, a0, a3
; RV32I-NEXT:    add a0, a2, a0
; RV32I-NEXT:    add a0, a0, a1
; RV32I-NEXT:    srli a4, a4, 15
; RV32I-NEXT:    slli a0, a0, 17
; RV32I-NEXT:    or a0, a4, a0
; RV32I-NEXT:    ret
;
; RV64I-LABEL: smulfix_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    sext.w a1, a1
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    srai a0, a0, 15
; RV64I-NEXT:    ret
  %m = call i32 @llvm.smul.fix.i32(i32 %1, i32 %2, i32 15)
  ret i32 %m
}

define i64 @smulfix_i64(i64 %1, i64 %2) {
; RV32I-LABEL: smulfix_i64:
; RV32I:       # %bb.0:
; RV32I-NEXT:    srai a4, a1, 31
; RV32I-NEXT:    srai a5, a3, 31
; RV32I-NEXT:    mul a6, a0, a2
; RV32I-NEXT:    mul a7, a1, a2
; RV32I-NEXT:    mul t0, a0, a3
; RV32I-NEXT:    mulhu t1, a0, a2
; RV32I-NEXT:    mul a4, a4, a2
; RV32I-NEXT:    mulhu a2, a1, a2
; RV32I-NEXT:    mul a1, a1, a3
; RV32I-NEXT:    mulhu a3, a0, a3
; RV32I-NEXT:    add a7, a7, t0
; RV32I-NEXT:    mul a0, a0, a5
; RV32I-NEXT:    srli a5, a6, 15
; RV32I-NEXT:    sltu a6, a7, t0
; RV32I-NEXT:    add a7, a7, t1
; RV32I-NEXT:    add a1, a4, a1
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    sltu a2, a7, t1
; RV32I-NEXT:    add a0, a1, a0
; RV32I-NEXT:    slli a1, a7, 17
; RV32I-NEXT:    add a2, a6, a2
; RV32I-NEXT:    add a3, a0, a3
; RV32I-NEXT:    or a0, a5, a1
; RV32I-NEXT:    add a2, a3, a2
; RV32I-NEXT:    srli a1, a7, 15
; RV32I-NEXT:    slli a2, a2, 17
; RV32I-NEXT:    or a1, a1, a2
; RV32I-NEXT:    ret
;
; RV64I-LABEL: smulfix_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    srai a2, a0, 63
; RV64I-NEXT:    srai a3, a1, 63
; RV64I-NEXT:    mul a4, a0, a1
; RV64I-NEXT:    mul a2, a2, a1
; RV64I-NEXT:    mulhu a1, a0, a1
; RV64I-NEXT:    mul a0, a0, a3
; RV64I-NEXT:    add a0, a2, a0
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    srli a4, a4, 15
; RV64I-NEXT:    slli a0, a0, 49
; RV64I-NEXT:    or a0, a4, a0
; RV64I-NEXT:    ret
  %m = call i64 @llvm.smul.fix.i64(i64 %1, i64 %2, i32 15)
  ret i64 %m
}
