import hudson.model.Result

/* groovylint-disable-next-line CompileStatic */
String actualTarget = env.CHANGE_TARGET ?: env.BRANCH_NAME
String upstreamBranch = 'upstream-main', stagingBranch = 'amd-staging'
String releaseBranchPrefix = 'aocc_'

Boolean targetIsRelBranch = actualTarget.startsWith(releaseBranchPrefix)

// Code smell: should be enabled for staging once the underlying llvm code catches up:
Boolean dualFlangBuild = actualTarget != upstreamBranch && actualTarget != stagingBranch

/**
 * Coerce Result enums to String, seems to
 * be required by CatchErrorStep.setStageResult()
 */
String abortedResultStr = Result.ABORTED, failureResultStr = Result.FAILURE
String notBuiltResultStr = Result.NOT_BUILT, successResultStr = Result.SUCCESS

if (!(actualTarget in [stagingBranch, upstreamBranch]) &&
    !targetIsRelBranch) {
    echo 'Pipeline skipped for base branch ' + actualTarget
    return this
}

String actualHead = env.CHANGE_BRANCH ?: env.BRANCH_NAME
Boolean isPrBranch = env.CHANGE_BRANCH != null

if (!isPrBranch &&
    !(actualTarget in [stagingBranch, upstreamBranch]) &&
    !targetIsRelBranch) {
    echo 'Pipeline skipped for non-PR branch ' + actualHead + ' of base ' + actualTarget
    return this
}

String manualCause = 'hudson.model.Cause$UserIdCause'
if (isPrBranch &&
    pullRequest.draft &&
    !currentBuild.getBuildCauses(manualCause)) {
    String cause = currentBuild.getBuildCauses().shortDescription // groovylint-disable-line UnnecessaryGetter
    echo 'Draft PR aborted for cause ' + cause
    echo 'Pipeline only runs for draft PRs if manually triggered.'
    currentBuild.result = abortedResultStr
    return this
}

// Code smell: buildTypes are also defined in CommitCheck
String buildTypePresub = 'PRESUB' // groovylint-disable-line UnusedVariable
String buildTypeRelease = 'RELEASE' // groovylint-disable-line UnusedVariable
String buildTypeStaging = 'STAGING' // groovylint-disable-line UnusedVariable
// buildType is processed during branch creation:
String buildType = (isPrBranch ? buildTypePresub : buildTypeRelease)

if (!isPrBranch &&
    env.BRANCH_NAME != stagingBranch &&
    !env.BRANCH_NAME.startsWith(releaseBranchPrefix)) {
    // Treat it as 'presub'.
    buildType = buildTypePresub
}

Boolean postsub = (
    !isPrBranch &&
        (
        (actualTarget == upstreamBranch && actualHead == upstreamBranch) ||
            (actualTarget == stagingBranch && actualHead == stagingBranch) ||
            (targetIsRelBranch &&
             actualHead.startsWith(releaseBranchPrefix))
    )
)

if (postsub && !(env.BRANCH_NAME in [stagingBranch, upstreamBranch]) &&
    !(env.BRANCH_NAME.startsWith(releaseBranchPrefix))) {
    echo 'Pipeline postsub not supported for branch ' + env.BRANCH_NAME
    return this
}

Boolean disableStaging = false, disableRelease = true
Boolean timerTrigger = currentBuild.getBuildCauses('hudson.triggers.TimerTrigger$TimerTriggerCause')
if (((disableStaging &&
     actualTarget == stagingBranch) ||
     (disableRelease &&
      targetIsRelBranch)) &&
    !currentBuild.getBuildCauses(manualCause) &&
    !timerTrigger) {
    String cause = currentBuild.getBuildCauses().shortDescription // groovylint-disable-line UnnecessaryGetter
    echo 'Pipeline for base ' + actualTarget + ' not built for cause ' + cause
    echo 'Pipeline only runs if manually or timer triggered.'
    currentBuild.result = notBuiltResultStr
    return this
}

Boolean runDownstream = (
    actualTarget == upstreamBranch ||
        (actualTarget == stagingBranch && isPrBranch) ||
        targetIsRelBranch
)

String space = ' ', andChain = '&&', underScore = '_', slash = '/', dash = '-'
String gitCommitEnv = 'GIT_COMMIT', bashCmd = 'bash'
String skipStr = 'Skipping build.', contStr = 'Continuing build.'
String contTimerReason = 'Timer trigger.' + space + contStr

List propsList = []
if (isPrBranch) {
    propsList.add(
        disableConcurrentBuilds(abortPrevious: true)
    )
    propsList.add(
        buildDiscarder(
            logRotator(
                daysToKeepStr: '7',
                numToKeepStr: '10'
            )
        )
    )
}
if (postsub) {
    propsList.add(
        pipelineTriggers([cron('TZ=Asia/Kolkata\nH 0 * * *')])
    )
}
properties(propsList)

String linuxBasePath = '/usr/sbin:/usr/bin:/bin'
String gitHubAppCredsId = 'Jenkins-AOCC-nonER'
String gitTool = 'LinuxGit2.45'
String gitPathEnv = (
    'PATH=/proj/csse_jenkins2/swtools/c/rhel7-gcc8.3.1/git-2.45.2-ilh23rcg/bin:' +
        linuxBasePath
)
String llvmProj = 'llvm-project', llvmProjRepo = llvmProj + '.git'
String theUrl
Boolean hasSourceChanges = true, isSkippableMerge = false
Integer zero = 0, successStat = zero

// llvmVer is processed by automation:
String llvmVer = '23.0.0'
// stageBuildNum is processed during branch creation:
String stageBuildNum = env.BUILD_NUMBER
// versionVal is processed during branch creation:
String versionVal = 'AOCC_' + llvmVer + dash + (buildType == buildTypePresub ? 'Presub' : 'Stage')

// relMode should be changed to 'CANDIDATE' when the release is close to readiness:
String relMode = 'PRE'

String jobName
if (postsub && targetIsRelBranch) {
    jobName = 'aocc-compiler-llvm-flang-rel' + dash + llvmVer + dash + stageBuildNum
} else {
    jobName = (
        (isPrBranch ? 'presub' : 'update') + underScore +
            (env.CHANGE_TARGET ?: (env.BRANCH_NAME ?: 'NoSuchBranchName'))
    )
    if (env.CHANGE_BRANCH) {
        jobName += underScore + env.BRANCH_NAME // Sic, the PR-<n> string.
    }
}

def gitVars // groovylint-disable-line NoDef,VariableTypeRequired

Integer fullTimeoutH = 15

String compilerTar

try {
    timeout(time: fullTimeoutH, unit: 'HOURS') {
        node ('atl && apptainer') {
            skipDefaultCheckout()
            List cleanExcludes = [
                [pattern: 'llvm-project/.git/**', type: 'EXCLUDE']
            ]
            stage ('prepare') {
                String referenceRepo = env.JENKINS_REMOTE_GIT_CACHE ?: 'NoSuchReferenceRepo'
                cleanWs(
                    deleteDirs: true,
                    patterns: cleanExcludes
                )
                String essDir
                if (actualTarget == upstreamBranch) {
                    dir('aocc-devops') {
                        checkout(
                            changelog: false,
                            scm: scmGit(
                                gitTool: gitTool,
                                branches: [[name: 'main']],
                                extensions: [
                                    cloneOption(
                                        reference: referenceRepo + '/aocc-devops.git'
                                    )
                                ],
                                userRemoteConfigs: [
                                    [
                                        credentialsId: gitHubAppCredsId,
                                        url: 'https://github.amd.com/cpu-compilers/aocc-devops.git'
                                    ]
                                ]
                            )
                        )
                    }
                    withCredentials([
                        gitUsernamePassword(
                            credentialsId: gitHubAppCredsId,
                            gitToolName: gitTool
                        )
                    ]) {
                        withEnv([gitPathEnv]) {
                            sh(
                                label: 'clone-essentials',
                                script: (
                                    'set +x; . aocc-devops/utils.sh' + space + andChain + space +
                                        'export BRANCH_NAME=' + stagingBranch + space + andChain + space +
                                        'sparse_clone_essentials' + space + andChain + space +
                                        'mv llvm-project/aocc-essentials . '  + space + andChain + space +
                                        'rm -rf llvm-project'
                                )
                            )
                        }
                    }
                    essDir = '../aocc-essentials'
                } else {
                    essDir = 'aocc-essentials'
                }
                theUrl = 'https://github.amd.com/cpu-compilers/llvm-project'
                dir (llvmProj) {
                    gitVars = checkout(
                        changelog: true,
                        scm: scmGit(
                            gitTool: gitTool,
                            branches: scm.branches,
                            browser: github(theUrl),
                            extensions: scm.extensions + [
                                cloneOption(
                                    depth: 2, // To compute the changelog.
                                    honorRefspec: true, noTags: true, shallow: true,
                                    reference: referenceRepo + slash + llvmProjRepo
                                ),
                                firstBuildChangelog()
                            ],
                            userRemoteConfigs: [
                                [
                                    credentialsId: gitHubAppCredsId,
                                    refspec: (
                                        '+refs/heads/' + actualHead + ':' +
                                            'refs/remotes/origin/' + actualHead
                                    ),
                                    url: theUrl
                                ]
                            ]
                        )
                    )
                    assert gitVars.GIT_COMMIT
                    Integer activeStat = successStat
                    withEnv([gitPathEnv]) {
                        if (
                            gitVars.GIT_PREVIOUS_SUCCESSFUL_COMMIT &&
                                gitVars.GIT_PREVIOUS_SUCCESSFUL_COMMIT != gitVars.GIT_COMMIT
                        ) {
                            withCredentials([
                                gitUsernamePassword(
                                    credentialsId: gitHubAppCredsId,
                                    gitToolName: gitTool
                                )
                            ]) {
                                activeStat = sh(
                                    label: 'has-file-changes',
                                    script: (
                                        bashCmd + space + essDir + '/build_essentials/has_file_changes.sh' + space +
                                            gitVars.GIT_COMMIT + space + gitVars.GIT_PREVIOUS_SUCCESSFUL_COMMIT
                                    ),
                                    returnStatus: true
                                )
                            }
                        }
                        if (activeStat == successStat) {
                            activeStat = sh(
                                label: 'has-active-files',
                                script: (
                                    bashCmd + space + essDir + '/build_essentials/has_active_files.sh' + space +
                                        gitVars.GIT_COMMIT + space +
                                        gitVars.GIT_PREVIOUS_SUCCESSFUL_COMMIT + space +
                                        '.amd-ci/upstream/upstream_jenkins_excludes.txt'
                                ),
                                returnStatus: true
                            )
                        }
                    }
                    if (activeStat != successStat && activeStat != 1) {
                        error 'Unexpected exit checking file activity.'
                    }
                    if (activeStat == 1) {
                        echo(skipStr)
                        hasSourceChanges = false
                        return // From stage
                    }

                    String mstat
                    withEnv([gitPathEnv, gitCommitEnv + '=' + gitVars.GIT_COMMIT]) {
                        withCredentials([
                            usernamePassword(
                                credentialsId: gitHubAppCredsId,
                                usernameVariable: 'GH_APP_USR_NOTREQUIRED',
                                passwordVariable: 'GH_ENTERPRISE_TOKEN'
                            )
                        ]) {
                            mstat = sh(
                                label: 'merge-stat',
                                script: (
                                    bashCmd + space + essDir + '/build_essentials/merge_commit_status.sh' + space +
                                        gitVars.GIT_COMMIT
                                ),
                                returnStdout: true
                            ).trim()
                        }
                    }
                    if (mstat && mstat != 'None') {
                        echo('Merge status is ' + mstat)
                        if (timerTrigger) {
                            echo(contTimerReason)
                        } else {
                            echo(skipStr)
                            isSkippableMerge = true
                            return // From stage
                        }
                    }
                }
            }
            if (isSkippableMerge || !hasSourceChanges) {
                cleanWs(
                    deleteDirs: true,
                    patterns: cleanExcludes
                )
                return // From node
            }
            stage ('run') {
                try {
                    withEnv([
                        'PATH=' + linuxBasePath,
                        'JOB_NAME=' + jobName,
                        'AOCC_DUAL_FLANG_BUILD=' + dualFlangBuild,
                        'STAGE_BUILD_NUM=' + stageBuildNum,
                        'VERSION_VAL=' + versionVal,
                        'REL_MODE=' + relMode,
                        'BUILD_TYPE=' + buildType
                    ]) {
                        sh 'llvm-project/.amd-ci/upstream/apptainer_run.sh'
                    }
                    currentBuild.result = successResultStr
                } finally {
                    def compilerZips = findFiles( // groovylint-disable-line NoDef,VariableTypeRequired
                        glob: "*-${env.BUILD_NUMBER}*.tar.xz"
                    )
                    if (compilerZips) {
                        compilerTar = compilerZips[zero].path
                    }
                    archiveArtifacts(
                        allowEmptyArchive: true,
                        artifacts: '*_logs/**,*.tar.xz,*.txt'
                    )
                    cleanWs(
                        deleteDirs: true,
                        patterns: cleanExcludes
                    )
                }
            }
        }
        if (isSkippableMerge || !hasSourceChanges) {
            return // From timeout
        }
        if (runDownstream && compilerTar) {
            stage ('downstream-tasks') {
                Map allTasks = [
                    failFast: false,
                ]
                List<String> downstreamSuites = ['GFortran', 'NAGLLVM']
                if (timerTrigger) {
                    downstreamSuites.addAll(['Fujitsu', 'Polyhedron'])
                }
                for (suite in downstreamSuites) {
                    String suiteName = suite
                    allTasks[suiteName] = {
                        stage ('downstream-suite-' + suiteName) {
                            build(
                                propagate: true,
                                wait: true,
                                job: 'AOCC-Workloads/TestSuites/' + suiteName,
                                parameters: [
                                    string(
                                        name: 'CUT',
                                        value: env.BUILD_URL + 'artifact/' + compilerTar
                                    ),
                                    string(name: 'BRANCH_CONTEXT', value: actualTarget),
                                    string(name: 'CHANGE_ID', value: env.CHANGE_ID ?: ''),
                                    string(name: gitCommitEnv, value: gitVars.GIT_COMMIT ?: '')
                                ]
                            )
                        }
                    }
                }
                parallel(allTasks)
            }
        }
    }
} catch (org.jenkinsci.plugins.workflow.steps.FlowInterruptedException e) {
    /*
     * This may be raised if the run is 'superseded' by a new patch,
     * when result will be NOT_BUILT. Don't overwrite this.
     */
    if (currentBuild.result != notBuiltResultStr) {
        currentBuild.result = abortedResultStr
    }
    throw e
} catch (Exception e) {
    currentBuild.result = failureResultStr
    throw e
}

/*
 * For when work is skipped.
 * Code smell: this method is also in the main AOCC CommitCheck class.
 */
void setStatusToLastCompleted() {
    def previousBuild = currentBuild.previousBuild // groovylint-disable-line NoDef,VariableTypeRequired
    // Default fallback:
    String previousResult = 'SUCCESS' // Keep as a literal string because of scoping.
    String nBStr = 'NOT_BUILT' // Keep as a literal string because of scoping.

    while (previousBuild &&
           (!(previousBuild.result) || previousBuild.result == nBStr)) {
        previousBuild = previousBuild.previousBuild
    }

    if (previousBuild && previousBuild.result) {
        previousResult = previousBuild.result
    } else {
        previousResult = nBStr
    }

    echo('Setting build result to ' + previousResult + ' from a previous build.')
    currentBuild.result = previousResult
}
