import hudson.model.Result

/* groovylint-disable-next-line CompileStatic */
String actualTarget = env.CHANGE_TARGET ?: env.BRANCH_NAME
String upstreamBranch = 'upstream-main', stagingBranch = 'amd-staging'

if (!(actualTarget in [stagingBranch, upstreamBranch])) {
    echo 'Pipeline skipped for base branch ' + actualTarget
    return this
}

String actualHead = env.CHANGE_BRANCH ?: env.BRANCH_NAME
Boolean isPrBranch = env.CHANGE_BRANCH != null

if (!isPrBranch && actualTarget != upstreamBranch) {
    echo 'Pipeline skipped for non-PR branch ' + actualHead + ' of base ' + actualTarget
    return this
}

Boolean postsub = !isPrBranch && actualTarget == upstreamBranch && actualHead == upstreamBranch

if (postsub && env.BRANCH_NAME != upstreamBranch) {
    echo 'Pipeline postsub not supported for branch ' + env.BRANCH_NAME
    return this
}

/**
 * Coerce Result enums to String, seems to
 * be required by CatchErrorStep.setStageResult()
 */
String abortedResultStr = Result.ABORTED, failureResultStr = Result.FAILURE
String notBuiltResultStr = Result.NOT_BUILT, successResultStr = Result.SUCCESS

String space = ' ', andChain = '&&', underScore = '_', slash = '/'

List propsList = []
if (isPrBranch) {
    propsList.add(
        disableConcurrentBuilds(abortPrevious: true)
    )
    propsList.add(
        buildDiscarder(
            logRotator(
                daysToKeepStr: '7',
                numToKeepStr: '10'
            )
        )
    )
}
if (postsub) {
    propsList.add(
        pipelineTriggers([cron('@midnight')])
    )
}
properties(propsList)

String linuxBasePath = '/usr/sbin:/usr/bin:/bin'
String gitHubAppCredsId = 'Jenkins-AOCC-nonER'
String gitTool = 'LinuxGit2.45'
String gitPathEnv = (
    'PATH=/proj/csse_jenkins2/swtools/c/rhel7-gcc8.3.1/git-2.45.2-ilh23rcg/bin:' +
        linuxBasePath
)
String llvmProj = 'llvm-project', llvmProjRepo = llvmProj + '.git'
String theUrl
Boolean hasSourceChanges = true
Integer successStat = 0

String jobName = (
    (isPrBranch ? 'presub' : 'update') + underScore +
        (env.CHANGE_TARGET ?: (env.BRANCH_NAME ?: 'NoSuchBranchName'))
)
if (env.CHANGE_BRANCH) {
    jobName += underScore + env.BRANCH_NAME // Sic, the PR-<n> string.
}

Integer fullTimeoutH = 15

try {
    timeout(time: fullTimeoutH, unit: 'HOURS') {
        node ('atl && apptainer') {
            skipDefaultCheckout()
            List cleanExcludes = [
                [pattern: 'llvm-project/.git/**', type: 'EXCLUDE']
            ]
            stage ('prepare') {
                String referenceRepo = env.JENKINS_REMOTE_GIT_CACHE ?: 'NoSuchReferenceRepo'
                cleanWs(
                    deleteDirs: true,
                    patterns: cleanExcludes
                )
                dir('aocc-devops') {
                    checkout(
                        changelog: false,
                        scm: scmGit(
                            gitTool: gitTool,
                            branches: [[name: 'main']],
                            extensions: [
                                cloneOption(
                                    reference: referenceRepo + '/aocc-devops.git'
                                )
                            ],
                            userRemoteConfigs: [
                                [
                                    credentialsId: gitHubAppCredsId,
                                    url: 'https://github.amd.com/AOCC/aocc-devops.git'
                                ]
                            ]
                        )
                    )
                }
                withCredentials([
                    gitUsernamePassword(
                        credentialsId: gitHubAppCredsId,
                        gitToolName: gitTool
                    )
                ]) {
                    withEnv([gitPathEnv]) {
                        sh(
                            label: 'clone-essentials',
                            script: (
                                'set +x; . aocc-devops/utils.sh' + space + andChain + space +
                                    'export BRANCH_NAME=' + stagingBranch + space + andChain + space +
                                    'sparse_clone_essentials' + space + andChain + space +
                                    'mv llvm-project/aocc-essentials . '  + space + andChain + space +
                                    'rm -rf llvm-project'
                            )
                        )
                    }
                }
                if (postsub) {
                    theUrl = 'ssh://git@github.amd.com/AOCC/llvm-project.git'
                    /*
                     * Direct CLI clone using the system's orequest SSH credentials,
                     * so that the later pushes in repo_sync.sh are successful.
                     */
                    withEnv([gitPathEnv]) {
                        sh(
                            label: 'clone-direct',
                            script: (
                                'git clone -q --reference ' +
                                    referenceRepo + slash + llvmProjRepo + ' -b main ' + theUrl + andChain +
                                    'cd ' + llvmProj + andChain +
                                    'git checkout ' + env.BRANCH_NAME + andChain +
                                    '''git merge main -m "Merge from main on $(date +'%Y-%m-%d')"'''
                            )
                        )
                    }
                } else {
                    theUrl = 'https://github.amd.com/AOCC/llvm-project'
                    dir (llvmProj) {
                        def gitVars = checkout( // groovylint-disable-line NoDef,VariableTypeRequired
                            changelog: true,
                            scm: scmGit(
                                gitTool: gitTool,
                                branches: scm.branches,
                                browser: github(theUrl),
                                extensions: scm.extensions + [
                                    cloneOption(
                                        depth: 2, // To compute the changelog.
                                        honorRefspec: true, noTags: true, shallow: true,
                                        reference: referenceRepo + slash + llvmProjRepo
                                    ),
                                    firstBuildChangelog()
                                ],
                                userRemoteConfigs: [
                                    [
                                        credentialsId: gitHubAppCredsId,
                                        refspec: (
                                            '+refs/heads/' + actualHead + ':' +
                                                'refs/remotes/origin/' + actualHead
                                        ),
                                        url: theUrl
                                    ]
                                ]
                            )
                        )
                        assert gitVars.GIT_COMMIT
                        Integer activeStat = successStat
                        withEnv([gitPathEnv]) {
                            if (
                                gitVars.GIT_PREVIOUS_SUCCESSFUL_COMMIT &&
                                    gitVars.GIT_PREVIOUS_SUCCESSFUL_COMMIT != gitVars.GIT_COMMIT
                            ) {
                                withCredentials([
                                    gitUsernamePassword(
                                        credentialsId: gitHubAppCredsId,
                                        gitToolName: gitTool
                                    )
                                ]) {
                                    activeStat = sh(
                                        label: 'has-file-changes',
                                        script: (
                                            'bash ../aocc-essentials/build_essentials/has_file_changes.sh' + space +
                                                gitVars.GIT_COMMIT + space + gitVars.GIT_PREVIOUS_SUCCESSFUL_COMMIT
                                        ),
                                        returnStatus: true
                                    )
                                }
                            }
                            if (activeStat == successStat) {
                                String dummyFile = env.BUILD_TAG + '_dummy.txt'
                                activeStat = sh(
                                    label: 'has-active-files',
                                    script: (
                                        'set +x; echo "# Dummy" > ' + dummyFile + andChain +
                                            'bash ../aocc-essentials/build_essentials/has_active_files.sh' + space +
                                            gitVars.GIT_COMMIT + space + dummyFile + ' && rm -f ' + dummyFile
                                    ),
                                    returnStatus: true
                                )
                            }
                        }
                        if (activeStat != successStat && activeStat != 1) {
                            error 'Unexpected exit checking file activity.'
                        }
                        if (activeStat == 1) {
                            echo('Skipping build.')
                            hasSourceChanges = false
                            return // From stage
                        }
                    }
                }
            }
            if (!hasSourceChanges) {
                cleanWs(
                    deleteDirs: true,
                    patterns: cleanExcludes
                )
                return this
            }
            stage ('run') {
                try {
                    withEnv([
                        'PATH=' + linuxBasePath,
                        'JOB_NAME=' + jobName
                    ]) {
                        sh 'llvm-project/.amd-ci/upstream/apptainer_run.sh'
                    }
                    currentBuild.result = successResultStr
                } finally {
                    if (postsub) {
                        stage ('merge-post') {
                            withEnv([gitPathEnv]) {
                                sh 'llvm-project/.amd-ci/upstream/repo_sync.sh'
                            }
                        }
                    }
                    archiveArtifacts(
                        allowEmptyArchive: true,
                        artifacts: '*.tar.xz,*.txt'
                    )
                    cleanWs(
                        deleteDirs: true,
                        patterns: cleanExcludes
                    )
                }
            }
        }
        build(
            propagate: true,
            wait: true,
            job: 'AOCC-Workloads/TestSuites/NAGLLVM',
            parameters: [
                // Use the name of build tar as defined in the run script:
                string(
                    name: 'CUT',
                    value: (
                        env.BUILD_URL + 'artifact/' +
                            jobName + '-' + env.BUILD_NUMBER + '.tar.xz'
                    )
                ),
                string(name: 'CHANGE_ID', value: env.CHANGE_ID)
            ]
        )
    }
} catch (org.jenkinsci.plugins.workflow.steps.FlowInterruptedException e) {
    /*
     * This may be raised if the run is 'superseded' by a new patch,
     * when result will be NOT_BUILT. Don't overwrite this.
     */
    if (currentBuild.result != notBuiltResultStr) {
        currentBuild.result = abortedResultStr
    }
    throw e
} catch (Exception e) {
    currentBuild.result = failureResultStr
    throw e
}
