; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=x86_64-unknown-unknown -passes=emit-changed-func-debuginfo < %s | FileCheck %s

; Source code:
;   // clang -S -emit-llvm -O3 -g test.c -mllvm -disable-changed-func-dbinfo
;   __attribute__((noinline)) static int callee(const int *p) { return *p + 42; }
;   int caller(void) {
;     int x = 100;
;     return callee(&x);
;   }

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none) uwtable
define dso_local range(i32 -2147483606, -2147483648) i32 @caller() local_unnamed_addr #0 !dbg !10 {
; CHECK-LABEL: define dso_local range(i32 -2147483606, -2147483648) i32 @caller(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] !dbg [[DBG10:![0-9]+]] {
; CHECK-NEXT:      #dbg_value(i32 100, [[META15:![0-9]+]], !DIExpression(), [[META16:![0-9]+]])
; CHECK-NEXT:    [[TMP1:%.*]] = tail call fastcc i32 @callee(i32 100), !dbg [[DBG17:![0-9]+]]
; CHECK-NEXT:    ret i32 [[TMP1]], !dbg [[DBG18:![0-9]+]]
;
    #dbg_value(i32 100, !15, !DIExpression(), !16)
  %1 = tail call fastcc i32 @callee(i32 100), !dbg !17
  ret i32 %1, !dbg !18
}

; Function Attrs: mustprogress nofree noinline norecurse nosync nounwind willreturn memory(none) uwtable
define internal fastcc range(i32 -2147483606, -2147483648) i32 @callee(i32 %0) unnamed_addr #1 !dbg !19 {
; CHECK-LABEL: define internal fastcc range(i32 -2147483606, -2147483648) i32 @callee(
; CHECK-SAME: i32 [[TMP0:%.*]]) unnamed_addr #[[ATTR1:[0-9]+]] !dbg [[DBG19:![0-9]+]] {
; CHECK-NEXT:      #dbg_value(i32 [[TMP0]], [[META24:![0-9]+]], !DIExpression(), [[META25:![0-9]+]])
; CHECK-NEXT:      #dbg_value(ptr poison, [[META26:![0-9]+]], !DIExpression(), [[META33:![0-9]+]])
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw i32 [[TMP0]], 42, !dbg [[DBG34:![0-9]+]]
; CHECK-NEXT:    ret i32 [[TMP2]], !dbg [[DBG35:![0-9]+]]
;
    #dbg_value(ptr poison, !25, !DIExpression(), !26)
  %2 = add nsw i32 %0, 42, !dbg !27
  ret i32 %2, !dbg !28
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(none) uwtable "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { mustprogress nofree noinline norecurse nosync nounwind willreturn memory(none) uwtable "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!2, !3, !4, !5, !6, !7, !8}
!llvm.ident = !{!9}

!0 = distinct !DICompileUnit(language: DW_LANG_C11, file: !1, producer: "clang version 22.0.0git (git@github.com:yonghong-song/llvm-project.git 8e5d24efc7dac78e8ba568dfe2fc6cfbe9663b13)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "test.c", directory: "/tmp/home/yhs/tests/sig-change/prom", checksumkind: CSK_MD5, checksum: "f42f3fd1477418a2e17b444f656351ff")
!2 = !{i32 7, !"Dwarf Version", i32 5}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = !{i32 1, !"wchar_size", i32 4}
!5 = !{i32 8, !"PIC Level", i32 2}
!6 = !{i32 7, !"PIE Level", i32 2}
!7 = !{i32 7, !"uwtable", i32 2}
!8 = !{i32 7, !"debug-info-assignment-tracking", i1 true}
!9 = !{!"clang version 22.0.0git (git@github.com:yonghong-song/llvm-project.git 8e5d24efc7dac78e8ba568dfe2fc6cfbe9663b13)"}
!10 = distinct !DISubprogram(name: "caller", scope: !1, file: !1, line: 2, type: !11, scopeLine: 2, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !14, keyInstructions: true)
!11 = !DISubroutineType(types: !12)
!12 = !{!13}
!13 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!14 = !{!15}
!15 = !DILocalVariable(name: "x", scope: !10, file: !1, line: 3, type: !13)
!16 = !DILocation(line: 0, scope: !10)
!17 = !DILocation(line: 4, column: 10, scope: !10, atomGroup: 3, atomRank: 2)
!18 = !DILocation(line: 4, column: 3, scope: !10, atomGroup: 3, atomRank: 1)
!19 = distinct !DISubprogram(name: "callee", scope: !1, file: !1, line: 1, type: !20, scopeLine: 1, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !24, keyInstructions: true)
!20 = !DISubroutineType(cc: DW_CC_nocall, types: !21)
!21 = !{!13, !22}
!22 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !23, size: 64)
!23 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !13)
!24 = !{!25}
!25 = !DILocalVariable(name: "p", arg: 1, scope: !19, file: !1, line: 1, type: !22)
!26 = !DILocation(line: 0, scope: !19)
!27 = !DILocation(line: 1, column: 71, scope: !19, atomGroup: 1, atomRank: 2)
!28 = !DILocation(line: 1, column: 61, scope: !19, atomGroup: 1, atomRank: 1)
;.
; CHECK: [[META0:![0-9]+]] = distinct !DICompileUnit(language: DW_LANG_C11, file: [[META1:![0-9]+]], producer: "{{.*}}clang version {{.*}}", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, splitDebugInlining: false, nameTableKind: None)
; CHECK: [[META1]] = !DIFile(filename: "{{.*}}test.c", directory: {{.*}})
; CHECK: [[DBG10]] = distinct !DISubprogram(name: "caller", scope: [[META1]], file: [[META1]], line: 2, type: [[META11:![0-9]+]], scopeLine: 2, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: [[META0]], retainedNodes: [[META14:![0-9]+]], keyInstructions: true)
; CHECK: [[META11]] = !DISubroutineType(types: [[META12:![0-9]+]])
; CHECK: [[META12]] = !{[[META13:![0-9]+]]}
; CHECK: [[META13]] = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
; CHECK: [[META14]] = !{[[META15]]}
; CHECK: [[META15]] = !DILocalVariable(name: "x", scope: [[DBG10]], file: [[META1]], line: 3, type: [[META13]])
; CHECK: [[META16]] = !DILocation(line: 0, scope: [[DBG10]])
; CHECK: [[DBG17]] = !DILocation(line: 4, column: 10, scope: [[DBG10]], atomGroup: 3, atomRank: 2)
; CHECK: [[DBG18]] = !DILocation(line: 4, column: 3, scope: [[DBG10]], atomGroup: 3, atomRank: 1)
; CHECK: [[DBG19]] = distinct !DISubprogram(name: "callee", linkageName: "callee", scope: [[META1]], file: [[META1]], line: 1, type: [[META20:![0-9]+]], scopeLine: 1, flags: DIFlagArtificial, spFlags: DISPFlagDefinition, unit: [[META0]], retainedNodes: [[META23:![0-9]+]])
; CHECK: [[META20]] = !DISubroutineType(types: [[META21:![0-9]+]])
; CHECK: [[META21]] = !{[[META13]], [[META22:![0-9]+]]}
; CHECK: [[META22]] = !DIBasicType(name: "int32", size: 32, encoding: DW_ATE_signed)
; CHECK: [[META23]] = !{}
; CHECK: [[META24]] = !DILocalVariable(name: "__0", arg: 1, scope: [[DBG19]], file: [[META1]], line: 1, type: [[META22]])
; CHECK: [[META25]] = !DILocation(line: 0, scope: [[DBG19]])
; CHECK: [[META26]] = !DILocalVariable(name: "p", arg: 1, scope: [[META27:![0-9]+]], file: [[META1]], line: 1, type: [[META30:![0-9]+]])
; CHECK: [[META27]] = distinct !DISubprogram(name: "callee", scope: [[META1]], file: [[META1]], line: 1, type: [[META28:![0-9]+]], scopeLine: 1, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: [[META0]], retainedNodes: [[META32:![0-9]+]], keyInstructions: true)
; CHECK: [[META28]] = !DISubroutineType(cc: DW_CC_normal, types: [[META29:![0-9]+]])
; CHECK: [[META29]] = !{[[META13]], [[META30]]}
; CHECK: [[META30]] = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: [[META31:![0-9]+]], size: 64)
; CHECK: [[META31]] = !DIDerivedType(tag: DW_TAG_const_type, baseType: [[META13]])
; CHECK: [[META32]] = !{[[META26]]}
; CHECK: [[META33]] = !DILocation(line: 0, scope: [[META27]], inlinedAt: [[META25]])
; CHECK: [[DBG34]] = !DILocation(line: 1, column: 71, scope: [[META27]], inlinedAt: [[META25]], atomGroup: 1, atomRank: 2)
; CHECK: [[DBG35]] = !DILocation(line: 1, column: 61, scope: [[META27]], inlinedAt: [[META25]], atomGroup: 1, atomRank: 1)
;.
