; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=libcalls-shrinkwrap -S | FileCheck %s

; #include <math.h>
; #include <fenv.h>
; #include <stdlib.h>
;
; void() {
;   volatile double d;
;   d = __builtin_nan ("");
;   feclearexcept (FE_ALL_EXCEPT);
;   acos(d);
;   if (fetestexcept (FE_ALL_EXCEPT))  // expect no fp exception raised
;     abort();
; }

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @test_quiet_nan() {
; CHECK-LABEL: define void @test_quiet_nan() {
; CHECK-NEXT:    [[TMP1:%.*]] = alloca double, align 8
; CHECK-NEXT:    store volatile double 0x7FF8000000000000, ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = tail call i32 @feclearexcept(i32 noundef 61)
; CHECK-NEXT:    [[TMP3:%.*]] = load volatile double, ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = fcmp ogt double [[TMP3]], 1.000000e+00
; CHECK-NEXT:    [[TMP5:%.*]] = fcmp olt double [[TMP3]], -1.000000e+00
; CHECK-NEXT:    [[TMP6:%.*]] = or i1 [[TMP5]], [[TMP4]]
; CHECK-NEXT:    br i1 [[TMP6]], label %[[CDCE_CALL:.*]], label %[[CDCE_END:.*]], !prof [[PROF0:![0-9]+]]
; CHECK:       [[CDCE_CALL]]:
; CHECK-NEXT:    [[TMP7:%.*]] = call double @acos(double noundef [[TMP3]])
; CHECK-NEXT:    br label %[[CDCE_END]]
; CHECK:       [[CDCE_END]]:
; CHECK-NEXT:    [[TMP8:%.*]] = call i32 @fetestexcept(i32 noundef 61)
; CHECK-NEXT:    [[TMP9:%.*]] = icmp ne i32 [[TMP8]], 0
; CHECK-NEXT:    br i1 [[TMP9]], label %[[ABORT:.*]], label %[[RET:.*]]
; CHECK:       [[ABORT]]:
; CHECK-NEXT:    call void @abort()
; CHECK-NEXT:    unreachable
; CHECK:       [[RET]]:
; CHECK-NEXT:    ret void
;
  %1 = alloca double, align 8
  store volatile double 0x7FF8000000000000, ptr %1, align 8
  %2 = tail call i32 @feclearexcept(i32 noundef 61)
  %3 = load volatile double, ptr %1, align 8
  %4 = call double @acos(double noundef %3)
  %5 = call i32 @fetestexcept(i32 noundef 61)
  %6 = icmp ne i32 %5, 0
  br i1 %6, label %abort, label %ret

abort:
  call void @abort()
  unreachable

ret:
  ret void
}

define void @test_quiet_nan_strictfp() strictfp {
; CHECK-LABEL: define void @test_quiet_nan_strictfp(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP1:%.*]] = alloca double, align 8
; CHECK-NEXT:    store volatile double 0x7FF8000000000000, ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = tail call i32 @feclearexcept(i32 noundef 61) #[[ATTR0]]
; CHECK-NEXT:    [[TMP3:%.*]] = load volatile double, ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = fcmp ogt double [[TMP3]], 1.000000e+00
; CHECK-NEXT:    [[TMP5:%.*]] = fcmp olt double [[TMP3]], -1.000000e+00
; CHECK-NEXT:    [[TMP6:%.*]] = or i1 [[TMP5]], [[TMP4]]
; CHECK-NEXT:    br i1 [[TMP6]], label %[[CDCE_CALL:.*]], label %[[CDCE_END:.*]], !prof [[PROF0]]
; CHECK:       [[CDCE_CALL]]:
; CHECK-NEXT:    [[TMP7:%.*]] = call double @acos(double noundef [[TMP3]]) #[[ATTR0]]
; CHECK-NEXT:    br label %[[CDCE_END]]
; CHECK:       [[CDCE_END]]:
; CHECK-NEXT:    [[TMP8:%.*]] = call i32 @fetestexcept(i32 noundef 61) #[[ATTR0]]
; CHECK-NEXT:    [[TMP9:%.*]] = icmp ne i32 [[TMP8]], 0
; CHECK-NEXT:    br i1 [[TMP9]], label %[[ABORT:.*]], label %[[RET:.*]]
; CHECK:       [[ABORT]]:
; CHECK-NEXT:    call void @abort() #[[ATTR0]]
; CHECK-NEXT:    unreachable
; CHECK:       [[RET]]:
; CHECK-NEXT:    ret void
;
  %1 = alloca double, align 8
  store volatile double 0x7FF8000000000000, ptr %1, align 8
  %2 = tail call i32 @feclearexcept(i32 noundef 61) strictfp
  %3 = load volatile double, ptr %1, align 8
  %4 = call double @acos(double noundef %3) strictfp
; Generate constrained fcmp if function has strictfp attribute.
; That avoids raising fp exception with quiet nan input.
  %5 = call i32 @fetestexcept(i32 noundef 61) strictfp
  %6 = icmp ne i32 %5, 0
  br i1 %6, label %abort, label %ret

abort:
  call void @abort() strictfp
  unreachable

ret:
  ret void
}

declare i32 @feclearexcept(i32 noundef)

declare i32 @fetestexcept(i32 noundef)

declare double @acos(double noundef)

declare void @abort()
;.
; CHECK: [[PROF0]] = !{!"branch_weights", i32 1, i32 1048575}
;.
