; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes='scopes2aliasscopemetadata' -S %s | FileCheck %s

define dso_local signext i32 @foo(ptr %x, ptr %y, i32 %cond) {
; CHECK-LABEL: define dso_local signext i32 @foo(
; CHECK-SAME: ptr [[X:%.*]], ptr [[Y:%.*]], i32 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[X_ADDR:%.*]] = alloca ptr, align 8, !scope [[META0:![0-9]+]]
; CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca ptr, align 8, !scope [[META0]]
; CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[TMP:%.*]] = alloca ptr, align 8, !scope [[META2:![0-9]+]]
; CHECK-NEXT:    [[P:%.*]] = alloca ptr, align 8, !scope [[META0]]
; CHECK-NEXT:    store ptr [[X]], ptr [[X_ADDR]], align 8
; CHECK-NEXT:    store ptr [[Y]], ptr [[Y_ADDR]], align 8
; CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[TMP]])
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[X_ADDR]], align 8, !scope [[META0]]
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[P]])
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[COND_ADDR]], align 4
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP1]], 0
; CHECK-NEXT:    br i1 [[TOBOOL]], label %[[COND_TRUE:.*]], label %[[COND_FALSE:.*]]
; CHECK:       [[COND_TRUE]]:
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[TMP]], align 8, !scope [[META2]]
; CHECK-NEXT:    br label %[[COND_END:.*]]
; CHECK:       [[COND_FALSE]]:
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP]], align 8, !scope [[META2]]
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP3]], i64 2, !scope [[META2]]
; CHECK-NEXT:    br label %[[COND_END]]
; CHECK:       [[COND_END]]:
; CHECK-NEXT:    [[COND1:%.*]] = phi ptr [ [[TMP2]], %[[COND_TRUE]] ], [ [[ADD_PTR]], %[[COND_FALSE]] ], !scope [[META2]]
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COND1]], align 4, !alias.scope [[META4:![0-9]+]], !noalias [[META7:![0-9]+]]
; CHECK-NEXT:    [[TOBOOL2:%.*]] = icmp ne i32 [[TMP4]], 0
; CHECK-NEXT:    br i1 [[TOBOOL2]], label %[[COND_TRUE3:.*]], label %[[COND_FALSE4:.*]]
; CHECK:       [[COND_TRUE3]]:
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP]], align 8, !scope [[META2]]
; CHECK-NEXT:    br label %[[COND_END6:.*]]
; CHECK:       [[COND_FALSE4]]:
; CHECK-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[TMP]], align 8, !scope [[META2]]
; CHECK-NEXT:    [[ADD_PTR5:%.*]] = getelementptr inbounds i32, ptr [[TMP6]], i64 2, !scope [[META2]]
; CHECK-NEXT:    br label %[[COND_END6]]
; CHECK:       [[COND_END6]]:
; CHECK-NEXT:    [[COND7:%.*]] = phi ptr [ [[TMP5]], %[[COND_TRUE3]] ], [ [[ADD_PTR5]], %[[COND_FALSE4]] ], !scope [[META2]]
; CHECK-NEXT:    store ptr [[COND7]], ptr [[P]], align 8
; CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[Y_ADDR]], align 8, !scope [[META0]]
; CHECK-NEXT:    store i32 42, ptr [[TMP7]], align 4, !alias.scope [[META7]]
; CHECK-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[P]], align 8, !scope [[META2]]
; CHECK-NEXT:    store i32 14, ptr [[TMP8]], align 4, !alias.scope [[META4]], !noalias [[META7]]
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[Y_ADDR]], align 8, !scope [[META0]]
; CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr [[TMP9]], align 4, !alias.scope [[META7]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[P]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[TMP]])
; CHECK-NEXT:    ret i32 [[TMP10]]
;
entry:
  %x.addr = alloca ptr, align 8, !scope !1
  %y.addr = alloca ptr, align 8, !scope !1
  %cond.addr = alloca i32, align 4
  %tmp = alloca ptr, align 8, !scope !3
  %p = alloca ptr, align 8, !scope !1
  store ptr %x, ptr %x.addr, align 8
  store ptr %y, ptr %y.addr, align 8
  store i32 %cond, ptr %cond.addr, align 4
  call void @llvm.lifetime.start.p0(i64 8, ptr %tmp)
  %0 = load ptr, ptr %x.addr, align 8
  store ptr %0, ptr %tmp, align 8
  call void @llvm.lifetime.start.p0(i64 8, ptr %p)
  %1 = load i32, ptr %cond.addr, align 4
  %tobool = icmp ne i32 %1, 0
  br i1 %tobool, label %cond.true, label %cond.false

cond.true:                                        ; preds = %entry
  %2 = load ptr, ptr %tmp, align 8
  br label %cond.end

cond.false:                                       ; preds = %entry
  %3 = load ptr, ptr %tmp, align 8
  %add.ptr = getelementptr inbounds i32, ptr %3, i64 2
  br label %cond.end

cond.end:                                         ; preds = %cond.false, %cond.true
  %cond1 = phi ptr [ %2, %cond.true ], [ %add.ptr, %cond.false ]
  %4 = load i32, ptr %cond1, align 4
  %tobool2 = icmp ne i32 %4, 0
  br i1 %tobool2, label %cond.true3, label %cond.false4

cond.true3:                                       ; preds = %cond.end
  %5 = load ptr, ptr %tmp, align 8
  br label %cond.end6

cond.false4:                                      ; preds = %cond.end
  %6 = load ptr, ptr %tmp, align 8
  %add.ptr5 = getelementptr inbounds i32, ptr %6, i64 2
  br label %cond.end6

cond.end6:                                        ; preds = %cond.false4, %cond.true3
  %cond7 = phi ptr [ %5, %cond.true3 ], [ %add.ptr5, %cond.false4 ]
  store ptr %cond7, ptr %p, align 8
  %7 = load ptr, ptr %y.addr, align 8
  store i32 42, ptr %7, align 4
  %8 = load ptr, ptr %p, align 8
  store i32 14, ptr %8, align 4
  %9 = load ptr, ptr %y.addr, align 8
  %10 = load i32, ptr %9, align 4
  call void @llvm.lifetime.end.p0(i64 8, ptr %p)
  call void @llvm.lifetime.end.p0(i64 8, ptr %tmp)
  ret i32 %10
}

declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)

declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)

!1 = !{!"foo_1", !2}
!2 = !{i64 0}
!3 = !{!"foo_1", !4}
!4 = !{i64 1}
;.
; CHECK: [[META0]] = !{!"foo_1", [[META1:![0-9]+]]}
; CHECK: [[META1]] = !{i64 0}
; CHECK: [[META2]] = !{!"foo_1", [[META3:![0-9]+]]}
; CHECK: [[META3]] = !{i64 1}
; CHECK: [[META4]] = !{[[META5:![0-9]+]]}
; CHECK: [[META5]] = distinct !{[[META5]], [[META6:![0-9]+]], !"foo_1#1"}
; CHECK: [[META6]] = distinct !{[[META6]], !"fooDomain"}
; CHECK: [[META7]] = !{[[META8:![0-9]+]]}
; CHECK: [[META8]] = distinct !{[[META8]], [[META6]], !"foo_1"}
;.
