; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes='scopes2aliasscopemetadata' -S %s | FileCheck %s

define dso_local signext i32 @foo(ptr %x, ptr %y, i32 %cond) {
; CHECK-LABEL: define dso_local signext i32 @foo(
; CHECK-SAME: ptr [[X:%.*]], ptr [[Y:%.*]], i32 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[X_ADDR:%.*]] = alloca ptr, align 8, !scope [[META0:![0-9]+]]
; CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca ptr, align 8, !scope [[META0]]
; CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[Z:%.*]] = alloca ptr, align 8, !scope [[META0]]
; CHECK-NEXT:    [[P:%.*]] = alloca ptr, align 8, !scope [[META2:![0-9]+]]
; CHECK-NEXT:    store ptr [[X]], ptr [[X_ADDR]], align 8
; CHECK-NEXT:    store ptr [[Y]], ptr [[Y_ADDR]], align 8
; CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[Z]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[P]])
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[X_ADDR]], align 8, !scope [[META0]]
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[P]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[Y_ADDR]], align 8, !scope [[META0]]
; CHECK-NEXT:    store i32 14, ptr [[TMP1]], align 4, !alias.scope [[META4:![0-9]+]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[COND_ADDR]], align 4
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP2]], 0
; CHECK-NEXT:    br i1 [[TOBOOL]], label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[P]], align 8, !scope [[META2]]
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP3]], i64 1, !scope [[META2]]
; CHECK-NEXT:    store ptr [[ADD_PTR]], ptr [[Z]], align 8
; CHECK-NEXT:    br label %[[IF_END:.*]]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[P]], align 8, !scope [[META2]]
; CHECK-NEXT:    [[ADD_PTR1:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i64 2, !scope [[META2]]
; CHECK-NEXT:    store ptr [[ADD_PTR1]], ptr [[Z]], align 8
; CHECK-NEXT:    br label %[[IF_END]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[Z]], align 8, !scope [[META2]]
; CHECK-NEXT:    store i32 42, ptr [[TMP5]], align 4, !alias.scope [[META7:![0-9]+]], !noalias [[META4]]
; CHECK-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[Y_ADDR]], align 8, !scope [[META0]]
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[TMP6]], align 4, !alias.scope [[META4]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[P]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[Z]])
; CHECK-NEXT:    ret i32 [[TMP7]]
;
entry:
  %x.addr = alloca ptr, align 8, !scope !1
  %y.addr = alloca ptr, align 8, !scope !1
  %cond.addr = alloca i32, align 4
  %z = alloca ptr, align 8, !scope !1
  %p = alloca ptr, align 8, !scope !3
  store ptr %x, ptr %x.addr, align 8
  store ptr %y, ptr %y.addr, align 8
  store i32 %cond, ptr %cond.addr, align 4
  call void @llvm.lifetime.start.p0(i64 8, ptr %z)
  call void @llvm.lifetime.start.p0(i64 8, ptr %p)
  %0 = load ptr, ptr %x.addr, align 8
  store ptr %0, ptr %p, align 8
  %1 = load ptr, ptr %y.addr, align 8
  store i32 14, ptr %1, align 4
  %2 = load i32, ptr %cond.addr, align 4
  %tobool = icmp ne i32 %2, 0
  br i1 %tobool, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %3 = load ptr, ptr %p, align 8
  %add.ptr = getelementptr inbounds i32, ptr %3, i64 1
  store ptr %add.ptr, ptr %z, align 8
  br label %if.end

if.else:                                          ; preds = %entry
  %4 = load ptr, ptr %p, align 8
  %add.ptr1 = getelementptr inbounds i32, ptr %4, i64 2
  store ptr %add.ptr1, ptr %z, align 8
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  %5 = load ptr, ptr %z, align 8
  store i32 42, ptr %5, align 4
  %6 = load ptr, ptr %y.addr, align 8
  %7 = load i32, ptr %6, align 4
  call void @llvm.lifetime.end.p0(i64 8, ptr %p)
  call void @llvm.lifetime.end.p0(i64 8, ptr %z)
  ret i32 %7
}

declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)

declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)

!1 = !{!"foo_1", !2}
!2 = !{i64 0}
!3 = !{!"foo_1", !4}
!4 = !{i64 1}
;.
; CHECK: [[META0]] = !{!"foo_1", [[META1:![0-9]+]]}
; CHECK: [[META1]] = !{i64 0}
; CHECK: [[META2]] = !{!"foo_1", [[META3:![0-9]+]]}
; CHECK: [[META3]] = !{i64 1}
; CHECK: [[META4]] = !{[[META5:![0-9]+]]}
; CHECK: [[META5]] = distinct !{[[META5]], [[META6:![0-9]+]], !"foo_1"}
; CHECK: [[META6]] = distinct !{[[META6]], !"fooDomain"}
; CHECK: [[META7]] = !{[[META8:![0-9]+]]}
; CHECK: [[META8]] = distinct !{[[META8]], [[META6]], !"foo_1#1"}
;.
