; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes='scopes2aliasscopemetadata' -S %s | FileCheck %s

define dso_local signext i32 @foo(ptr %x, ptr %y) {
; CHECK-LABEL: define dso_local signext i32 @foo(
; CHECK-SAME: ptr [[X:%.*]], ptr [[Y:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[X_ADDR:%.*]] = alloca ptr, align 8, !scope [[META0:![0-9]+]]
; CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca ptr, align 8, !scope [[META0]]
; CHECK-NEXT:    [[P:%.*]] = alloca ptr, align 8, !scope [[META2:![0-9]+]]
; CHECK-NEXT:    store ptr [[X]], ptr [[X_ADDR]], align 8
; CHECK-NEXT:    store ptr [[Y]], ptr [[Y_ADDR]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[X_ADDR]], align 8, !scope [[META0]]
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[P]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[Y_ADDR]], align 8, !scope [[META0]]
; CHECK-NEXT:    store i32 14, ptr [[TMP1]], align 4, !alias.scope [[META4:![0-9]+]]
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P]], align 8, !scope [[META2]]
; CHECK-NEXT:    store i32 42, ptr [[TMP2]], align 4, !alias.scope [[META7:![0-9]+]], !noalias [[META4]]
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[Y_ADDR]], align 8, !scope [[META0]]
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[TMP3]], align 4, !alias.scope [[META4]]
; CHECK-NEXT:    ret i32 [[TMP4]]
;
entry:
  %x.addr = alloca ptr, align 8, !scope !1
  %y.addr = alloca ptr, align 8, !scope !1
  %p = alloca ptr, align 8, !scope !3
  store ptr %x, ptr %x.addr, align 8
  store ptr %y, ptr %y.addr, align 8
  %0 = load ptr, ptr %x.addr, align 8
  store ptr %0, ptr %p, align 8
  %1 = load ptr, ptr %y.addr, align 8
  store i32 14, ptr %1, align 4
  %2 = load ptr, ptr %p, align 8
  store i32 42, ptr %2, align 4
  %3 = load ptr, ptr %y.addr, align 8
  %4 = load i32, ptr %3, align 4
  ret i32 %4
}


!1 = !{!"foo_1", !2}
!2 = !{i64 0}
!3 = !{!"foo_1", !4}
!4 = !{i64 1}

;.
; CHECK: [[META0]] = !{!"foo_1", [[META1:![0-9]+]]}
; CHECK: [[META1]] = !{i64 0}
; CHECK: [[META2]] = !{!"foo_1", [[META3:![0-9]+]]}
; CHECK: [[META3]] = !{i64 1}
; CHECK: [[META4]] = !{[[META5:![0-9]+]]}
; CHECK: [[META5]] = distinct !{[[META5]], [[META6:![0-9]+]], !"foo_1"}
; CHECK: [[META6]] = distinct !{[[META6]], !"fooDomain"}
; CHECK: [[META7]] = !{[[META8:![0-9]+]]}
; CHECK: [[META8]] = distinct !{[[META8]], [[META6]], !"foo_1#1"}
;.
