; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes='scopes2aliasscopemetadata' -S %s | FileCheck %s

define dso_local signext i32 @foo(ptr %x, ptr %y, i32 %cond) {
; CHECK-LABEL: define dso_local signext i32 @foo(
; CHECK-SAME: ptr [[X:%.*]], ptr [[Y:%.*]], i32 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[X_ADDR:%.*]] = alloca ptr, align 8, !scope [[META0:![0-9]+]]
; CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca ptr, align 8, !scope [[META0]]
; CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[TMP1:%.*]] = alloca ptr, align 8, !scope [[META2:![0-9]+]]
; CHECK-NEXT:    [[TMP2:%.*]] = alloca ptr, align 8, !scope [[META0]]
; CHECK-NEXT:    [[P:%.*]] = alloca ptr, align 8, !scope [[META0]]
; CHECK-NEXT:    store ptr [[X]], ptr [[X_ADDR]], align 8
; CHECK-NEXT:    store ptr [[Y]], ptr [[Y_ADDR]], align 8
; CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[TMP1]])
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[X_ADDR]], align 8, !scope [[META0]]
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[TMP2]])
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[X_ADDR]], align 8, !scope [[META0]]
; CHECK-NEXT:    store ptr [[TMP9]], ptr [[TMP2]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[P]])
; CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr [[COND_ADDR]], align 4
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP10]], 0
; CHECK-NEXT:    br i1 [[TOBOOL]], label %[[COND_TRUE:.*]], label %[[COND_FALSE:.*]]
; CHECK:       [[COND_TRUE]]:
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP1]], align 8, !scope [[META2]]
; CHECK-NEXT:    br label %[[COND_END:.*]]
; CHECK:       [[COND_FALSE]]:
; CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP2]], align 8, !scope [[META0]]
; CHECK-NEXT:    br label %[[COND_END]]
; CHECK:       [[COND_END]]:
; CHECK-NEXT:    [[COND1:%.*]] = phi ptr [ [[TMP3]], %[[COND_TRUE]] ], [ [[TMP4]], %[[COND_FALSE]] ]
; CHECK-NEXT:    store ptr [[COND1]], ptr [[P]], align 8
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[Y_ADDR]], align 8, !scope [[META0]]
; CHECK-NEXT:    store i32 42, ptr [[TMP5]], align 4, !alias.scope [[META4:![0-9]+]]
; CHECK-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[P]], align 8
; CHECK-NEXT:    store i32 14, ptr [[TMP6]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[Y_ADDR]], align 8, !scope [[META0]]
; CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[TMP7]], align 4, !alias.scope [[META4]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[P]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[TMP1]])
; CHECK-NEXT:    ret i32 [[TMP8]]
;
entry:
  %x.addr = alloca ptr, align 8, !scope !1
  %y.addr = alloca ptr, align 8, !scope !1
  %cond.addr = alloca i32, align 4
  %tmp_1 = alloca ptr, align 8, !scope !3
  %tmp_2 = alloca ptr, align 8, !scope !1
  %p = alloca ptr, align 8, !scope !1
  store ptr %x, ptr %x.addr, align 8
  store ptr %y, ptr %y.addr, align 8
  store i32 %cond, ptr %cond.addr, align 4
  call void @llvm.lifetime.start.p0(i64 8, ptr %tmp_1)
  %0 = load ptr, ptr %x.addr, align 8
  store ptr %0, ptr %tmp_1, align 8
  call void @llvm.lifetime.start.p0(i64 8, ptr %tmp_2)
  %1 = load ptr, ptr %x.addr, align 8
  store ptr %1, ptr %tmp_2, align 8
  call void @llvm.lifetime.start.p0(i64 8, ptr %p)
  %2 = load i32, ptr %cond.addr, align 4
  %tobool = icmp ne i32 %2, 0
  br i1 %tobool, label %cond.true, label %cond.false

cond.true:                                        ; preds = %entry
  %3 = load ptr, ptr %tmp_1, align 8
  br label %cond.end

cond.false:                                       ; preds = %entry
  %4 = load ptr, ptr %tmp_2, align 8
  br label %cond.end

cond.end:                                         ; preds = %cond.false, %cond.true
  %cond1 = phi ptr [ %3, %cond.true ], [ %4, %cond.false ]
  store ptr %cond1, ptr %p, align 8
  %5 = load ptr, ptr %y.addr, align 8
  store i32 42, ptr %5, align 4
  %6 = load ptr, ptr %p, align 8
  store i32 14, ptr %6, align 4
  %7 = load ptr, ptr %y.addr, align 8
  %8 = load i32, ptr %7, align 4
  call void @llvm.lifetime.end.p0(i64 8, ptr %p)
  call void @llvm.lifetime.end.p0(i64 8, ptr %tmp_2)
  call void @llvm.lifetime.end.p0(i64 8, ptr %tmp_1)
  ret i32 %8
}


!1 = !{!"foo_1", !2}
!2 = !{i64 0}
!3 = !{!"foo_1", !4}
!4 = !{i64 1}
;.
; CHECK: [[META0]] = !{!"foo_1", [[META1:![0-9]+]]}
; CHECK: [[META1]] = !{i64 0}
; CHECK: [[META2]] = !{!"foo_1", [[META3:![0-9]+]]}
; CHECK: [[META3]] = !{i64 1}
; CHECK: [[META4]] = !{[[META5:![0-9]+]]}
; CHECK: [[META5]] = distinct !{[[META5]], [[META6:![0-9]+]], !"foo_1"}
; CHECK: [[META6]] = distinct !{[[META6]], !"fooDomain"}
;.
