# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv32 -run-pass=legalizer %s -o - \
# RUN: | FileCheck %s
---
name:            xor_i7
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: xor_i7
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $x11
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[XOR]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s7) = G_TRUNC %0(s32)
    %3:_(s7) = G_TRUNC %1(s32)
    %4:_(s7) = G_XOR %2, %3
    %5:_(s32) = G_ANYEXT %4(s7)
    $x10 = COPY %5(s32)
    PseudoRET implicit $x10

...
---
name:            xor_i8
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: xor_i8
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $x11
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[XOR]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s8) = G_TRUNC %0(s32)
    %3:_(s8) = G_TRUNC %1(s32)
    %4:_(s8) = G_XOR %2, %3
    %5:_(s32) = G_ANYEXT %4(s8)
    $x10 = COPY %5(s32)
    PseudoRET implicit $x10

...
---
name:            xor_i16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: xor_i16
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $x11
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[XOR]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s16) = G_TRUNC %0(s32)
    %3:_(s16) = G_TRUNC %1(s32)
    %4:_(s16) = G_XOR %2, %3
    %5:_(s32) = G_ANYEXT %4(s16)
    $x10 = COPY %5(s32)
    PseudoRET implicit $x10

...
---
name:            xor_i32
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: xor_i32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $x11
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[XOR]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = G_XOR %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            xor_i48
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: xor_i48
    ; CHECK: %xhi:_(s32) = COPY $x10
    ; CHECK-NEXT: %xlo:_(s32) = COPY $x11
    ; CHECK-NEXT: %yhi:_(s32) = COPY $x12
    ; CHECK-NEXT: %ylo:_(s32) = COPY $x13
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR %xhi, %yhi
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR %xlo, %ylo
    ; CHECK-NEXT: $x10 = COPY [[XOR]](s32)
    ; CHECK-NEXT: $x11 = COPY [[XOR1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10, implicit $x11
    %xhi:_(s32) = COPY $x10
    %xlo:_(s32) = COPY $x11
    %yhi:_(s32) = COPY $x12
    %ylo:_(s32) = COPY $x13
    %x0:_(s64) = G_MERGE_VALUES %xhi(s32), %xlo(s32)
    %y0:_(s64) = G_MERGE_VALUES %yhi(s32), %ylo(s32)
    %x:_(s48) = G_TRUNC %x0(s64)
    %y:_(s48) = G_TRUNC %y0(s64)
    %z:_(s48) = G_XOR %x, %y
    %z0:_(s64) = G_ANYEXT %z(s48)
    %zhi:_(s32), %zlo:_(s32) = G_UNMERGE_VALUES %z0(s64)
    $x10 = COPY %zhi(s32)
    $x11 = COPY %zlo(s32)
    PseudoRET implicit $x10, implicit $x11

...
---
name:            xor_i64
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: xor_i64
    ; CHECK: %hi1:_(s32) = COPY $x10
    ; CHECK-NEXT: %lo1:_(s32) = COPY $x11
    ; CHECK-NEXT: %hi2:_(s32) = COPY $x12
    ; CHECK-NEXT: %lo2:_(s32) = COPY $x13
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR %hi1, %hi2
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR %lo1, %lo2
    ; CHECK-NEXT: $x10 = COPY [[XOR]](s32)
    ; CHECK-NEXT: $x11 = COPY [[XOR1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10, implicit $x11
    %hi1:_(s32) = COPY $x10
    %lo1:_(s32) = COPY $x11
    %hi2:_(s32) = COPY $x12
    %lo2:_(s32) = COPY $x13
    %x1:_(s64) = G_MERGE_VALUES %hi1(s32), %lo1(s32)
    %x2:_(s64) = G_MERGE_VALUES %hi2(s32), %lo2(s32)
    %y:_(s64) = G_XOR %x1, %x2
    %hiy:_(s32), %loy:_(s32) = G_UNMERGE_VALUES %y(s64)
    $x10 = COPY %hiy(s32)
    $x11 = COPY %loy(s32)
    PseudoRET implicit $x10, implicit $x11

...
---
name:            xor_i96
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: xor_i96
    ; CHECK: %hi1:_(s32) = COPY $x10
    ; CHECK-NEXT: %mid1:_(s32) = COPY $x11
    ; CHECK-NEXT: %lo1:_(s32) = COPY $x12
    ; CHECK-NEXT: %hi2:_(s32) = COPY $x13
    ; CHECK-NEXT: %mid2:_(s32) = COPY $x14
    ; CHECK-NEXT: %lo2:_(s32) = COPY $x15
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR %hi1, %hi2
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR %mid1, %mid2
    ; CHECK-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR %lo1, %lo2
    ; CHECK-NEXT: $x10 = COPY [[XOR]](s32)
    ; CHECK-NEXT: $x11 = COPY [[XOR1]](s32)
    ; CHECK-NEXT: $x12 = COPY [[XOR2]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10, implicit $x11, implicit $x12
    %hi1:_(s32) = COPY $x10
    %mid1:_(s32) = COPY $x11
    %lo1:_(s32) = COPY $x12
    %hi2:_(s32) = COPY $x13
    %mid2:_(s32) = COPY $x14
    %lo2:_(s32) = COPY $x15
    %x1:_(s96) = G_MERGE_VALUES %hi1(s32), %mid1(s32), %lo1(s32)
    %x2:_(s96) = G_MERGE_VALUES %hi2(s32), %mid2(s32), %lo2(s32)
    %y:_(s96) = G_XOR %x1, %x2
    %hi:_(s32), %mid:_(s32), %lo:_(s32) = G_UNMERGE_VALUES %y(s96)
    $x10 = COPY %hi(s32)
    $x11 = COPY %mid(s32)
    $x12 = COPY %lo(s32)
    PseudoRET implicit $x10, implicit $x11, implicit $x12

...
