import("//llvm/utils/TableGen/tablegen.gni")

tablegen("InstCombineCLOptions") {
  visibility = [ ":InstCombine" ]
  args = [ "-gen-opt-parser-defs" ]
}

static_library("InstCombine") {
  output_name = "LLVMInstCombine"
  deps = [
    ":InstCombineCLOptions",
    "//llvm/lib/Analysis",
    "//llvm/lib/IR",
    "//llvm/lib/Option",
    "//llvm/lib/Support",
    "//llvm/lib/Transforms/Utils",
  ]
  sources = [
    "InstCombineAddSub.cpp",
    "InstCombineAndOrXor.cpp",
    "InstCombineAtomicRMW.cpp",
    "InstCombineCLOptions.cpp",
    "InstCombineCalls.cpp",
    "InstCombineCasts.cpp",
    "InstCombineCompares.cpp",
    "InstCombineLoadStoreAlloca.cpp",
    "InstCombineMulDivRem.cpp",
    "InstCombineNegator.cpp",
    "InstCombinePHI.cpp",
    "InstCombineSelect.cpp",
    "InstCombineShifts.cpp",
    "InstCombineSimplifyDemanded.cpp",
    "InstCombineVectorOps.cpp",
    "InstructionCombining.cpp",
  ]
}
