SWIFT_SOURCES := main.swift
SWIFTFLAGS_EXTRAS = -Xfrontend -enable-builtin-module -Xfrontend -enable-experimental-feature -Xfrontend ValueGenerics -Xfrontend -disable-experimental-parser-round-trip -Xfrontend -disable-availability-checking

include Makefile.rules
