include(${CMAKE_CURRENT_LIST_DIR}/../../../cmake/Modules/LLVMVersion.cmake)

# If build end2end. Expect FUCHSIA_TOOLCHAIN_RUNTIME_BUILD_MODE set to END2END
# if build standalone. Expect FUCHSIA_TOOLCHAIN_RUNTIME_BUILD_MODE set to BUILTIN or RUNTIMES
set(FUCHSIA_TOOLCHAIN_RUNTIME_BUILD_MODE "" CACHE STRING "")

if(NOT (FUCHSIA_TOOLCHAIN_RUNTIME_BUILD_MODE STREQUAL "END2END" OR FUCHSIA_TOOLCHAIN_RUNTIME_BUILD_MODE STREQUAL "BUILTIN" OR FUCHSIA_TOOLCHAIN_RUNTIME_BUILD_MODE STREQUAL "RUNTIMES"))
  message(FATAL_ERROR "FUCHSIA_TOOLCHAIN_RUNTIME_BUILD_MODE needs to be set to END2END or BUILTIN or RUNTIMES")
endif()

function(SET_COMMON_ENTRIES RUNTIME_TARGET CONFIG_PREFIX SYSTEM_NAME SYSROOT_PATH COMPILER_FLAGS LINKER_FLAGS)
  set(target ${RUNTIME_TARGET})
  set(${CONFIG_PREFIX}CMAKE_SYSTEM_NAME ${SYSTEM_NAME} CACHE STRING "")
  set(${CONFIG_PREFIX}CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "")
  set(${CONFIG_PREFIX}CMAKE_C_FLAGS ${COMPILER_FLAGS} CACHE STRING "")
  set(${CONFIG_PREFIX}CMAKE_CXX_FLAGS ${COMPILER_FLAGS} CACHE STRING "")
  set(${CONFIG_PREFIX}CMAKE_ASM_FLAGS ${COMPILER_FLAGS} CACHE STRING "")
  set(${CONFIG_PREFIX}CMAKE_SYSROOT ${SYSROOT_PATH} CACHE STRING "")
  set(${CONFIG_PREFIX}CMAKE_SHARED_LINKER_FLAGS ${LINKER_FLAGS} CACHE STRING "")
  set(${CONFIG_PREFIX}CMAKE_MODULE_LINKER_FLAGS ${LINKER_FLAGS} CACHE STRING "")
  set(${CONFIG_PREFIX}CMAKE_EXE_LINKER_FLAGS ${LINKER_FLAGS} CACHE STRING "")
endfunction()