// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --version 5
// REQUIRES: system-darwin
// RUN: %clang_cc1 -O0 -fbounds-safety -fbounds-safety-bringup-missing-checks=access_size -triple arm64-apple-iphoneos -emit-llvm %s -o - | FileCheck --check-prefix ACCESS-SIZE %s
// RUN: %clang_cc1 -O0 -fbounds-safety -fno-bounds-safety-bringup-missing-checks=access_size -triple arm64-apple-iphoneos -emit-llvm %s -o - | FileCheck --check-prefix ACCESS-SIZE %s
#include <ptrcheck.h>
int get_int(void*);
typedef int fn_t(void *);

void receive(fn_t);

// The codegen with and without `access_size` should be identical

// ACCESS-SIZE-LABEL: define dso_local void @borked(
// ACCESS-SIZE-SAME: ) #[[ATTR0:[0-9]+]] {
// ACCESS-SIZE-NEXT:  [[ENTRY:.*:]]
// ACCESS-SIZE-NEXT:    [[F:%.*]] = alloca ptr, align 8
// ACCESS-SIZE-NEXT:    [[W:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// ACCESS-SIZE-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// ACCESS-SIZE-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// ACCESS-SIZE-NEXT:    store ptr @get_int, ptr [[F]], align 8
// ACCESS-SIZE-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[W]], i8 0, i64 24, i1 false)
// ACCESS-SIZE-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[W]], i64 24, i1 false)
// ACCESS-SIZE-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// ACCESS-SIZE-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// ACCESS-SIZE-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// ACCESS-SIZE-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// ACCESS-SIZE-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2
// ACCESS-SIZE-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// ACCESS-SIZE-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// ACCESS-SIZE-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP0]], align 8
// ACCESS-SIZE-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// ACCESS-SIZE-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP1]], align 8
// ACCESS-SIZE-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// ACCESS-SIZE-NEXT:    store ptr [[WIDE_PTR_LB]], ptr [[TMP2]], align 8
// ACCESS-SIZE-NEXT:    [[WIDE_PTR_PTR_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// ACCESS-SIZE-NEXT:    [[WIDE_PTR_PTR3:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR2]], align 8
// ACCESS-SIZE-NEXT:    [[WIDE_PTR_UB_ADDR4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// ACCESS-SIZE-NEXT:    [[WIDE_PTR_UB5:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR4]], align 8
// ACCESS-SIZE-NEXT:    [[WIDE_PTR_LB_ADDR6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// ACCESS-SIZE-NEXT:    [[WIDE_PTR_LB7:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR6]], align 8
// ACCESS-SIZE-NEXT:    [[TMP3:%.*]] = icmp ne ptr [[WIDE_PTR_PTR3]], null, !annotation [[META1:![0-9]+]]
// ACCESS-SIZE-NEXT:    br i1 [[TMP3]], label %[[BOUNDSCHECK_NOTNULL:.*]], label %[[BOUNDSCHECK_NULL:.*]], !annotation [[META1]]
// ACCESS-SIZE:       [[BOUNDSCHECK_NOTNULL]]:
// ACCESS-SIZE-NEXT:    [[TMP4:%.*]] = icmp ult ptr [[WIDE_PTR_PTR3]], [[WIDE_PTR_UB5]], !annotation [[META2:![0-9]+]]
// ACCESS-SIZE-NEXT:    br i1 [[TMP4]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// ACCESS-SIZE:       [[TRAP]]:
// ACCESS-SIZE-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], !annotation [[META2]]
// ACCESS-SIZE-NEXT:    unreachable, !annotation [[META2]]
// ACCESS-SIZE:       [[CONT]]:
// ACCESS-SIZE-NEXT:    [[TMP5:%.*]] = icmp uge ptr [[WIDE_PTR_PTR3]], [[WIDE_PTR_LB7]], !annotation [[META4:![0-9]+]]
// ACCESS-SIZE-NEXT:    br i1 [[TMP5]], label %[[CONT9:.*]], label %[[TRAP8:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// ACCESS-SIZE:       [[TRAP8]]:
// ACCESS-SIZE-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META4]]
// ACCESS-SIZE-NEXT:    unreachable, !annotation [[META4]]
// ACCESS-SIZE:       [[CONT9]]:
// ACCESS-SIZE-NEXT:    br label %[[BOUNDSCHECK_NULL]]
// ACCESS-SIZE:       [[BOUNDSCHECK_NULL]]:
// ACCESS-SIZE-NEXT:    store ptr [[WIDE_PTR_PTR3]], ptr [[F]], align 8
// ACCESS-SIZE-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[F]], align 8
// ACCESS-SIZE-NEXT:    call void @receive(ptr noundef [[TMP6]])
// ACCESS-SIZE-NEXT:    ret void
//
void borked(void)
{
  fn_t *f = get_int; // This is implicitly __single, not __bidi_indexable
  void *w = 0; // Implicitly __bidi_indexable
  // Bounds check here
  // Converting
  // int (*__bidi_indexable)(void *__single) -> rn_matchf_t *__single
  //
  // requires checking that the wide pointer is in bounds.
  f = w;
  receive(f);
}
//.
// ACCESS-SIZE: [[META1]] = !{!"bounds-safety-check-ptr-neq-null"}
// ACCESS-SIZE: [[META2]] = !{!"bounds-safety-check-ptr-lt-upper-bound"}
// ACCESS-SIZE: [[META4]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
//.
