// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --version 5
// REQUIRES: system-darwin
// RUN: %clang_cc1 -O0 -fbounds-safety -fbounds-safety-bringup-missing-checks=access_size -triple arm64-apple-iphoneos -emit-llvm %s -o - | FileCheck --check-prefixes=NEW %s
// RUN: %clang_cc1 -O0 -fbounds-safety -fno-bounds-safety-bringup-missing-checks=access_size -triple arm64-apple-iphoneos -emit-llvm %s -o - | FileCheck --check-prefixes=LEGACY %s
#include <ptrcheck.h>
#include <stdint.h>


// NEW-LABEL: define dso_local i8 @access_uint8(
// NEW-SAME: ptr noundef dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]]) #[[ATTR0:[0-9]+]] {
// NEW-NEXT:  [[ENTRY:.*:]]
// NEW-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// NEW-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// NEW-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// NEW-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// NEW-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// NEW-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4
// NEW-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP0]] to i64
// NEW-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i8, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// NEW-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// NEW-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// NEW-NEXT:    [[TMP1:%.*]] = icmp ult ptr [[ARRAYIDX]], [[WIDE_PTR_UB]], !annotation [[META1:![0-9]+]]
// NEW-NEXT:    br i1 [[TMP1]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation [[META1]]
// NEW-NEXT:    unreachable, !annotation [[META1]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[TMP2:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META3:![0-9]+]]
// NEW-NEXT:    br i1 [[TMP2]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// NEW:       [[TRAP1]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META3]]
// NEW-NEXT:    unreachable, !annotation [[META3]]
// NEW:       [[CONT2]]:
// NEW-NEXT:    [[TMP3:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
// NEW-NEXT:    ret i8 [[TMP3]]
//
// LEGACY-LABEL: define dso_local i8 @access_uint8(
// LEGACY-SAME: ptr noundef dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]]) #[[ATTR0:[0-9]+]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// LEGACY-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// LEGACY-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// LEGACY-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// LEGACY-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4
// LEGACY-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// LEGACY-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// LEGACY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4
// LEGACY-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP0]] to i64
// LEGACY-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i8, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// LEGACY-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// LEGACY-NEXT:    [[TMP1:%.*]] = icmp ult ptr [[ARRAYIDX]], [[WIDE_PTR_UB]], !annotation [[META1:![0-9]+]]
// LEGACY-NEXT:    br i1 [[TMP1]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// LEGACY:       [[TRAP]]:
// LEGACY-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation [[META1]]
// LEGACY-NEXT:    unreachable, !annotation [[META1]]
// LEGACY:       [[CONT]]:
// LEGACY-NEXT:    [[TMP2:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META3:![0-9]+]]
// LEGACY-NEXT:    br i1 [[TMP2]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// LEGACY:       [[TRAP1]]:
// LEGACY-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META3]]
// LEGACY-NEXT:    unreachable, !annotation [[META3]]
// LEGACY:       [[CONT2]]:
// LEGACY-NEXT:    [[TMP3:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
// LEGACY-NEXT:    ret i8 [[TMP3]]
//
uint8_t access_uint8(uint8_t* __bidi_indexable ptr, int idx) {
  return ptr[idx];
}

// NEW-LABEL: define dso_local i16 @access_uint16(
// NEW-SAME: ptr noundef dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]]) #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*:]]
// NEW-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// NEW-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// NEW-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// NEW-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// NEW-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// NEW-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4
// NEW-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP0]] to i64
// NEW-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i16, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// NEW-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// NEW-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// NEW-NEXT:    [[TMP1:%.*]] = getelementptr i16, ptr [[ARRAYIDX]], i64 1, !annotation [[META4:![0-9]+]]
// NEW-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[TMP1]], [[WIDE_PTR_UB]], !annotation [[META4]]
// NEW-NEXT:    br i1 [[TMP2]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META4]]
// NEW-NEXT:    unreachable, !annotation [[META4]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[TMP3:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP1]], !annotation [[META4]]
// NEW-NEXT:    br i1 [[TMP3]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// NEW:       [[TRAP1]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META4]]
// NEW-NEXT:    unreachable, !annotation [[META4]]
// NEW:       [[CONT2]]:
// NEW-NEXT:    [[TMP4:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META3]]
// NEW-NEXT:    br i1 [[TMP4]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// NEW:       [[TRAP3]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META3]]
// NEW-NEXT:    unreachable, !annotation [[META3]]
// NEW:       [[CONT4]]:
// NEW-NEXT:    [[TMP5:%.*]] = load i16, ptr [[ARRAYIDX]], align 2
// NEW-NEXT:    ret i16 [[TMP5]]
//
// LEGACY-LABEL: define dso_local i16 @access_uint16(
// LEGACY-SAME: ptr noundef dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]]) #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// LEGACY-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// LEGACY-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// LEGACY-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// LEGACY-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4
// LEGACY-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// LEGACY-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// LEGACY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4
// LEGACY-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP0]] to i64
// LEGACY-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i16, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// LEGACY-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// LEGACY-NEXT:    [[TMP1:%.*]] = icmp ult ptr [[ARRAYIDX]], [[WIDE_PTR_UB]], !annotation [[META1]]
// LEGACY-NEXT:    br i1 [[TMP1]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// LEGACY:       [[TRAP]]:
// LEGACY-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META1]]
// LEGACY-NEXT:    unreachable, !annotation [[META1]]
// LEGACY:       [[CONT]]:
// LEGACY-NEXT:    [[TMP2:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META3]]
// LEGACY-NEXT:    br i1 [[TMP2]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// LEGACY:       [[TRAP1]]:
// LEGACY-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META3]]
// LEGACY-NEXT:    unreachable, !annotation [[META3]]
// LEGACY:       [[CONT2]]:
// LEGACY-NEXT:    [[TMP3:%.*]] = load i16, ptr [[ARRAYIDX]], align 2
// LEGACY-NEXT:    ret i16 [[TMP3]]
//
uint16_t access_uint16(uint16_t* __bidi_indexable ptr, int idx) {
  return ptr[idx];
}

// NEW-LABEL: define dso_local i32 @access_uint32(
// NEW-SAME: ptr noundef dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]]) #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*:]]
// NEW-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// NEW-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// NEW-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// NEW-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// NEW-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP]], i32 0, i32 0
// NEW-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// NEW-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4
// NEW-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP0]] to i64
// NEW-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP]], i32 0, i32 1
// NEW-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP]], i32 0, i32 2
// NEW-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// NEW-NEXT:    [[TMP1:%.*]] = getelementptr i32, ptr [[ARRAYIDX]], i64 1, !annotation [[META4]]
// NEW-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[TMP1]], [[WIDE_PTR_UB]], !annotation [[META4]]
// NEW-NEXT:    br i1 [[TMP2]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META4]]
// NEW-NEXT:    unreachable, !annotation [[META4]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[TMP3:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP1]], !annotation [[META4]]
// NEW-NEXT:    br i1 [[TMP3]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// NEW:       [[TRAP1]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META4]]
// NEW-NEXT:    unreachable, !annotation [[META4]]
// NEW:       [[CONT2]]:
// NEW-NEXT:    [[TMP4:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META3]]
// NEW-NEXT:    br i1 [[TMP4]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// NEW:       [[TRAP3]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META3]]
// NEW-NEXT:    unreachable, !annotation [[META3]]
// NEW:       [[CONT4]]:
// NEW-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// NEW-NEXT:    ret i32 [[TMP5]]
//
// LEGACY-LABEL: define dso_local i32 @access_uint32(
// LEGACY-SAME: ptr noundef dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]]) #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// LEGACY-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// LEGACY-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// LEGACY-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// LEGACY-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4
// LEGACY-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// LEGACY-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// LEGACY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4
// LEGACY-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP0]] to i64
// LEGACY-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// LEGACY-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// LEGACY-NEXT:    [[TMP1:%.*]] = icmp ult ptr [[ARRAYIDX]], [[WIDE_PTR_UB]], !annotation [[META1]]
// LEGACY-NEXT:    br i1 [[TMP1]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// LEGACY:       [[TRAP]]:
// LEGACY-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META1]]
// LEGACY-NEXT:    unreachable, !annotation [[META1]]
// LEGACY:       [[CONT]]:
// LEGACY-NEXT:    [[TMP2:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META3]]
// LEGACY-NEXT:    br i1 [[TMP2]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// LEGACY:       [[TRAP1]]:
// LEGACY-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META3]]
// LEGACY-NEXT:    unreachable, !annotation [[META3]]
// LEGACY:       [[CONT2]]:
// LEGACY-NEXT:    [[TMP3:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// LEGACY-NEXT:    ret i32 [[TMP3]]
//
uint32_t access_uint32(uint32_t* __bidi_indexable ptr, int idx) {
  return ptr[idx];
}

// NEW-LABEL: define dso_local i64 @access_uint64(
// NEW-SAME: ptr noundef dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]]) #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*:]]
// NEW-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// NEW-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// NEW-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.2", align 8
// NEW-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// NEW-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP]], i32 0, i32 0
// NEW-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// NEW-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4
// NEW-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP0]] to i64
// NEW-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i64, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP]], i32 0, i32 1
// NEW-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP]], i32 0, i32 2
// NEW-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// NEW-NEXT:    [[TMP1:%.*]] = getelementptr i64, ptr [[ARRAYIDX]], i64 1, !annotation [[META4]]
// NEW-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[TMP1]], [[WIDE_PTR_UB]], !annotation [[META4]]
// NEW-NEXT:    br i1 [[TMP2]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META4]]
// NEW-NEXT:    unreachable, !annotation [[META4]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[TMP3:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP1]], !annotation [[META4]]
// NEW-NEXT:    br i1 [[TMP3]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// NEW:       [[TRAP1]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META4]]
// NEW-NEXT:    unreachable, !annotation [[META4]]
// NEW:       [[CONT2]]:
// NEW-NEXT:    [[TMP4:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META3]]
// NEW-NEXT:    br i1 [[TMP4]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// NEW:       [[TRAP3]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META3]]
// NEW-NEXT:    unreachable, !annotation [[META3]]
// NEW:       [[CONT4]]:
// NEW-NEXT:    [[TMP5:%.*]] = load i64, ptr [[ARRAYIDX]], align 8
// NEW-NEXT:    ret i64 [[TMP5]]
//
// LEGACY-LABEL: define dso_local i64 @access_uint64(
// LEGACY-SAME: ptr noundef dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]]) #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// LEGACY-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// LEGACY-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.2", align 8
// LEGACY-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// LEGACY-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4
// LEGACY-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// LEGACY-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// LEGACY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4
// LEGACY-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP0]] to i64
// LEGACY-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i64, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// LEGACY-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// LEGACY-NEXT:    [[TMP1:%.*]] = icmp ult ptr [[ARRAYIDX]], [[WIDE_PTR_UB]], !annotation [[META1]]
// LEGACY-NEXT:    br i1 [[TMP1]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// LEGACY:       [[TRAP]]:
// LEGACY-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META1]]
// LEGACY-NEXT:    unreachable, !annotation [[META1]]
// LEGACY:       [[CONT]]:
// LEGACY-NEXT:    [[TMP2:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META3]]
// LEGACY-NEXT:    br i1 [[TMP2]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// LEGACY:       [[TRAP1]]:
// LEGACY-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META3]]
// LEGACY-NEXT:    unreachable, !annotation [[META3]]
// LEGACY:       [[CONT2]]:
// LEGACY-NEXT:    [[TMP3:%.*]] = load i64, ptr [[ARRAYIDX]], align 8
// LEGACY-NEXT:    ret i64 [[TMP3]]
//
uint64_t access_uint64(uint64_t* __bidi_indexable ptr, int idx) {
  return ptr[idx];
}

//.
// NEW: [[META1]] = !{!"bounds-safety-check-ptr-lt-upper-bound"}
// NEW: [[META3]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
// NEW: [[META4]] = !{!"bounds-safety-check-ptr-le-upper-bound"}
//.
// LEGACY: [[META1]] = !{!"bounds-safety-check-ptr-lt-upper-bound"}
// LEGACY: [[META3]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
//.
