// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6

// RUN: %clang_cc1 -O2  -fbounds-safety -triple arm64e-apple-iphoneos -Wno-bounds-safety-init-list -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2  -fbounds-safety -triple arm64e-apple-iphoneos -Wno-bounds-safety-init-list -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>
#include <stddef.h>

// CHECK-LABEL: define dso_local void @count_ok(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], i32 noundef [[LEN:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void count_ok(int *__counted_by(len - 2) buf, int len) {
  int arr[10];
  buf = arr;
  len = 12;
}

// CHECK-LABEL: define dso_local void @negative_count_trap(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], i32 noundef [[LEN:%.*]]) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void negative_count_trap(int *__counted_by(len - 2) buf, int len) {
  int arr[10];
  int n = 0;
  len = n;
  buf = arr;
}

// CHECK-LABEL: define dso_local void @too_big_count_trap(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], i32 noundef [[LEN:%.*]]) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void too_big_count_trap(int *__counted_by(len - 2) buf, int len) {
  int arr[10];
  int n = 13;
  buf = arr;
  len = n;
}

// CHECK-LABEL: define dso_local void @overflow_unsigned_count_trap(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], i64 noundef [[LEN:%.*]]) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void overflow_unsigned_count_trap(int *__counted_by(len - 2) buf, size_t len) {
  int arr[10];
  int n = 0;
  buf = arr;
  len = n;
}

// CHECK-LABEL: define dso_local void @local_count_ok(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void local_count_ok(void) {
  int arr[10];
  int len = 12;
  int *__counted_by(len - 2) buf = arr;
}

// CHECK-LABEL: define dso_local void @local_count_ok_2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void local_count_ok_2(void) {
  int arr[10];
  int len = 2;
  int *__counted_by(len - 2) buf;
  len = 12;
  buf = arr;
}

// CHECK-LABEL: define dso_local void @local_count_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void local_count_trap(void) {
  int arr[10];
  int n = 0;
  int len = n;
  int *__counted_by(len - 2) buf = arr;
}

// CHECK-LABEL: define dso_local void @loob_local_count_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ARR:%.*]] = alloca [10 x i32], align 4
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[ARR]]) #[[ATTR6:[0-9]+]]
// CHECK-NEXT:    [[UPPER:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i64 40
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[ARR]], i64 -4
// CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH]], [[UPPER]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP16_NOT:%.*]] = icmp ugt ptr [[ARR]], [[BOUND_PTR_ARITH]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP_NOT]], [[CMP16_NOT]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[TRAP:.*]], label %[[CONT:.*]], {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[ARR]]) #[[ATTR6]]
// CHECK-NEXT:    ret void
//
void loob_local_count_trap(void) {
  int arr[10];
  int len = 12;
  int *__counted_by(len - 2) buf = arr - 1;
}

// CHECK-LABEL: define dso_local void @uoob_local_count_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void uoob_local_count_trap(void) {
  int arr[10];
  int len = 12;
  int *__counted_by(len - 2) buf = arr + 1;
}

// CHECK-LABEL: define dso_local void @too_big_local_count_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void too_big_local_count_trap(void) {
  int arr[10];
  int n = 13;
  int len = 2;
  int *__counted_by(len - 2) buf;
  buf = arr;
  len = n;
}

// CHECK-LABEL: define dso_local void @overflow_local_unsigned_count_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void overflow_local_unsigned_count_trap(void) {
  int arr[10];
  int n = 0;
  int len = n;
  int *__counted_by(len - 2) buf = arr;
}

// CHECK-LABEL: define dso_local void @overflow_unsigned_count_size_ok(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], i64 noundef [[COUNT:%.*]], i64 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void overflow_unsigned_count_size_ok(void *__sized_by(count * size) buf, size_t count, size_t size) {
  int arr[10];
  buf = arr;
  count = __SIZE_MAX__;
  size = __SIZE_MAX__;
}

// CHECK-LABEL: define dso_local void @overflow_unsigned_count_size_trap2(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], i64 noundef [[COUNT:%.*]], i64 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void overflow_unsigned_count_size_trap2(void *__sized_by(count * size) buf, size_t count, size_t size) {
  int arr[10];
  buf = arr;
  count = __SIZE_MAX__;
  size = __SIZE_MAX__;

  char *p = buf;
  p[1] = 0;
}

// CHECK-LABEL: define dso_local void @overflow_unsigned_count_size_index_trap(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], i64 noundef [[COUNT:%.*]], i64 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void overflow_unsigned_count_size_index_trap(int *__counted_by(count * size) buf, size_t count, size_t size) {
  buf = buf;
  count = (size_t)(__SIZE_MAX__ >> 2) + (size_t)1;
  size = 1;

  buf[0] = 0;
}
