// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6


// RUN: %clang_cc1 -O0  -fbounds-safety -triple arm64-apple-darwin -emit-llvm %s -o - | FileCheck %s --check-prefix=NOPT
// RUN: %clang_cc1 -O2  -fbounds-safety -triple arm64-apple-darwin -emit-llvm %s -o - | FileCheck %s --check-prefix=OPT
// RUN: %clang_cc1 -O0  -fbounds-safety -triple arm64-apple-ios -emit-llvm %s -o - | FileCheck %s --check-prefix=NOPT
// RUN: %clang_cc1 -O2  -fbounds-safety -triple arm64-apple-ios -emit-llvm %s -o - | FileCheck %s --check-prefix=OPT
// RUN: %clang_cc1 -O0  -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -triple arm64-apple-darwin -emit-llvm %s -o - | FileCheck %s --check-prefix=NOPT
// RUN: %clang_cc1 -O2  -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -triple arm64-apple-darwin -emit-llvm %s -o - | FileCheck %s --check-prefix=OPT
// RUN: %clang_cc1 -O0  -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -triple arm64-apple-ios -emit-llvm %s -o - | FileCheck %s --check-prefix=NOPT
// RUN: %clang_cc1 -O2  -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -triple arm64-apple-ios -emit-llvm %s -o - | FileCheck %s --check-prefix=OPT


// NOPT-LABEL: define i32 @main(
// NOPT-SAME: ) #[[ATTR0:[0-9]+]] {
// NOPT-NEXT:  [[ENTRY:.*:]]
// NOPT-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// NOPT-NEXT:    [[ARR:%.*]] = alloca [10 x i32], align 4
// NOPT-NEXT:    [[A:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NOPT-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NOPT-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// NOPT-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// NOPT-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY]], i64 10
// NOPT-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[A]], i32 0, i32 0
// NOPT-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP0]], align 8
// NOPT-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[A]], i32 0, i32 1
// NOPT-NEXT:    store ptr [[UPPER]], ptr [[TMP1]], align 8
// NOPT-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[A]], i32 0, i32 2
// NOPT-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP2]], align 8
// NOPT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[A]], i64 24, i1 false)
// NOPT-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// NOPT-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// NOPT-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// NOPT-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// NOPT-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// NOPT-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// NOPT-NEXT:    [[CMP:%.*]] = icmp eq ptr [[WIDE_PTR_PTR]], null
// NOPT-NEXT:    br i1 [[CMP]], label %[[IF_THEN:.*]], label %[[IF_END:.*]]
// NOPT:       [[IF_THEN]]:
// NOPT-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// NOPT-NEXT:    br label %[[RETURN:.*]]
// NOPT:       [[IF_END]]:
// NOPT-NEXT:    store i32 1, ptr [[RETVAL]], align 4
// NOPT-NEXT:    br label %[[RETURN]]
// NOPT:       [[RETURN]]:
// NOPT-NEXT:    [[TMP3:%.*]] = load i32, ptr [[RETVAL]], align 4
// NOPT-NEXT:    ret i32 [[TMP3]]
//
// OPT-LABEL: define noundef i32 @main(
// OPT-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// OPT-NEXT:  [[ENTRY:.*:]]
// OPT-NEXT:    ret i32 1
//
int main() {
    int arr[10];
    int *a = arr;
    if (a == 0)
        return 0;
    return 1;
}


//
