// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6

// REQUIRES: x86-registered-target

// RUN: %clang_cc1 -O2 -fbounds-safety -emit-llvm -triple x86_64 -fsanitize=pointer-overflow,signed-integer-overflow,unsigned-integer-overflow -fsanitize-trap=pointer-overflow,signed-integer-overflow,unsigned-integer-overflow %s -o - | FileCheck %s --check-prefix=UBSAN
// RUN: %clang_cc1 -O2 -fbounds-safety -emit-llvm -triple x86_64 %s -o - | FileCheck %s --check-prefix=NOUBSAN
// RUN: %clang_cc1 -O2 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm -triple x86_64 -fsanitize=pointer-overflow,signed-integer-overflow,unsigned-integer-overflow -fsanitize-trap=pointer-overflow,signed-integer-overflow,unsigned-integer-overflow %s -o - | FileCheck %s --check-prefix=UBSAN
// RUN: %clang_cc1 -O2 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm -triple x86_64 %s -o - | FileCheck %s --check-prefix=NOUBSAN

#include <ptrcheck.h>

void f_callee(char *__counted_by(inLen), unsigned long long inLen);
// UBSAN-LABEL: define dso_local void @f_unsafe_outlen(
// UBSAN-SAME: ptr noundef [[DEROUT:%.*]], ptr noundef readonly captures(none) [[OUTLEN:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// UBSAN-NEXT:  [[ENTRY:.*:]]
// UBSAN-NEXT:    [[TMP0:%.*]] = load i64, ptr [[OUTLEN]], align 8, {{!tbaa ![0-9]+}}
// UBSAN-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[DEROUT]], i64 [[TMP0]]
// UBSAN-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[DEROUT]], [[TMP1]], {{!annotation ![0-9]+}}
// UBSAN-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[CONT:.*]], {{!annotation ![0-9]+}}
// UBSAN:       [[TRAP]]:
// UBSAN-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], {{!annotation ![0-9]+}}
// UBSAN-NEXT:    unreachable, {{!annotation ![0-9]+}}
// UBSAN:       [[CONT]]:
// UBSAN-NEXT:    tail call void @f_callee(ptr noundef [[DEROUT]], i64 noundef [[TMP0]]) #[[ATTR5:[0-9]+]]
// UBSAN-NEXT:    ret void
//
// NOUBSAN-LABEL: define dso_local void @f_unsafe_outlen(
// NOUBSAN-SAME: ptr noundef [[DEROUT:%.*]], ptr noundef readonly captures(none) [[OUTLEN:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// NOUBSAN-NEXT:  [[ENTRY:.*:]]
// NOUBSAN-NEXT:    [[TMP0:%.*]] = load i64, ptr [[OUTLEN]], align 8, {{!tbaa ![0-9]+}}
// NOUBSAN-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[DEROUT]], i64 [[TMP0]]
// NOUBSAN-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[DEROUT]], [[TMP1]], {{!annotation ![0-9]+}}
// NOUBSAN-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[CONT:.*]], {{!annotation ![0-9]+}}
// NOUBSAN:       [[TRAP]]:
// NOUBSAN-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], {{!annotation ![0-9]+}}
// NOUBSAN-NEXT:    unreachable, {{!annotation ![0-9]+}}
// NOUBSAN:       [[CONT]]:
// NOUBSAN-NEXT:    tail call void @f_callee(ptr noundef [[DEROUT]], i64 noundef [[TMP0]]) #[[ATTR5:[0-9]+]]
// NOUBSAN-NEXT:    ret void
//
void f_unsafe_outlen(char *__unsafe_indexable derOut, unsigned long long *outLen) {
  f_callee(__unsafe_forge_bidi_indexable(char *, derOut, *outLen), *outLen);
}

// UBSAN-LABEL: define dso_local void @f_outlen(
// UBSAN-SAME: ptr noundef [[DEROUT:%.*]], ptr noundef readonly captures(none) [[OUTLEN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// UBSAN-NEXT:  [[ENTRY:.*:]]
// UBSAN-NEXT:    [[TMP0:%.*]] = load i64, ptr [[OUTLEN]], align 8, {{!tbaa ![0-9]+}}
// UBSAN-NEXT:    [[CMP:%.*]] = icmp sgt i64 [[TMP0]], -1
// UBSAN-NEXT:    tail call void @llvm.assume(i1 [[CMP]])
// UBSAN-NEXT:    tail call void @f_callee(ptr noundef [[DEROUT]], i64 noundef [[TMP0]]) #[[ATTR5]]
// UBSAN-NEXT:    ret void
//
// NOUBSAN-LABEL: define dso_local void @f_outlen(
// NOUBSAN-SAME: ptr noundef [[DEROUT:%.*]], ptr noundef readonly captures(none) [[OUTLEN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOUBSAN-NEXT:  [[ENTRY:.*:]]
// NOUBSAN-NEXT:    [[TMP0:%.*]] = load i64, ptr [[OUTLEN]], align 8, {{!tbaa ![0-9]+}}
// NOUBSAN-NEXT:    [[CMP:%.*]] = icmp sgt i64 [[TMP0]], -1
// NOUBSAN-NEXT:    tail call void @llvm.assume(i1 [[CMP]])
// NOUBSAN-NEXT:    tail call void @f_callee(ptr noundef [[DEROUT]], i64 noundef [[TMP0]]) #[[ATTR5]]
// NOUBSAN-NEXT:    ret void
//
void f_outlen(char *__counted_by(*outLen) derOut, unsigned long long *outLen) {
  f_callee(derOut, *outLen);
}

// UBSAN-LABEL: define dso_local void @f_call_bound_checks(
// UBSAN-SAME: ptr noundef readonly byval(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 captures(none) [[BUF:%.*]], i64 noundef [[OFFSET:%.*]], i64 noundef [[LEN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// UBSAN-NEXT:  [[ENTRY:.*:]]
// UBSAN-NEXT:    [[TMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[BUF]], align 8
// UBSAN-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[TMP_SROA_0_0_COPYLOAD]], i64 [[OFFSET]]
// UBSAN-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[TMP_SROA_0_0_COPYLOAD]] to i64, {{!nosanitize ![0-9]+}}
// UBSAN-NEXT:    [[TMP1:%.*]] = add i64 [[OFFSET]], [[TMP0]], {{!nosanitize ![0-9]+}}
// UBSAN-NEXT:    [[TMP2:%.*]] = icmp ne ptr [[TMP_SROA_0_0_COPYLOAD]], null, {{!nosanitize ![0-9]+}}
// UBSAN-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[TMP1]], 0
// UBSAN-NEXT:    [[TMP4:%.*]] = xor i1 [[TMP2]], [[TMP3]]
// UBSAN-NEXT:    [[TMP5:%.*]] = icmp uge i64 [[TMP1]], [[TMP0]], {{!nosanitize ![0-9]+}}
// UBSAN-NEXT:    [[TMP6:%.*]] = and i1 [[TMP5]], [[TMP4]], {{!nosanitize ![0-9]+}}
// UBSAN-NEXT:    br i1 [[TMP6]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!nosanitize ![0-9]+}}
// UBSAN:       [[TRAP]]:
// UBSAN-NEXT:    tail call void @llvm.ubsantrap(i8 19) #[[ATTR6:[0-9]+]], {{!nosanitize ![0-9]+}}
// UBSAN-NEXT:    unreachable, {{!nosanitize ![0-9]+}}
// UBSAN:       [[CONT]]:
// UBSAN-NEXT:    [[TMP_SROA_4_0_BUF_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[BUF]], i64 16
// UBSAN-NEXT:    [[TMP_SROA_4_0_COPYLOAD:%.*]] = load ptr, ptr [[TMP_SROA_4_0_BUF_SROA_IDX]], align 8, {{!tbaa ![0-9]+}}
// UBSAN-NEXT:    [[TMP_SROA_3_0_BUF_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[BUF]], i64 8
// UBSAN-NEXT:    [[TMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[TMP_SROA_3_0_BUF_SROA_IDX]], align 8
// UBSAN-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH]], [[TMP_SROA_3_0_COPYLOAD]], {{!annotation ![0-9]+}}
// UBSAN-NEXT:    [[CMP27_NOT:%.*]] = icmp ugt ptr [[TMP_SROA_4_0_COPYLOAD]], [[BOUND_PTR_ARITH]], {{!annotation ![0-9]+}}
// UBSAN-NEXT:    [[OR_COND:%.*]] = select i1 [[CMP_NOT]], i1 true, i1 [[CMP27_NOT]], {{!annotation ![0-9]+}}
// UBSAN-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[TMP_SROA_3_0_COPYLOAD]] to i64, {{!annotation ![0-9]+}}
// UBSAN-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[BOUND_PTR_ARITH]] to i64, {{!annotation ![0-9]+}}
// UBSAN-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], {{!annotation ![0-9]+}}
// UBSAN-NEXT:    [[CMP44_NOT:%.*]] = icmp ugt i64 [[LEN]], [[SUB_PTR_SUB]], {{!annotation ![0-9]+}}
// UBSAN-NEXT:    [[OR_COND55:%.*]] = or i1 [[OR_COND]], [[CMP44_NOT]], {{!annotation ![0-9]+}}
// UBSAN-NEXT:    br i1 [[OR_COND55]], label %[[TRAP45:.*]], label %[[CONT46:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// UBSAN:       [[TRAP45]]:
// UBSAN-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// UBSAN-NEXT:    unreachable, {{!annotation ![0-9]+}}
// UBSAN:       [[CONT46]]:
// UBSAN-NEXT:    tail call void @f_callee(ptr noundef [[BOUND_PTR_ARITH]], i64 noundef [[LEN]]) #[[ATTR5]]
// UBSAN-NEXT:    ret void
//
// NOUBSAN-LABEL: define dso_local void @f_call_bound_checks(
// NOUBSAN-SAME: ptr noundef readonly byval(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 captures(none) [[BUF:%.*]], i64 noundef [[OFFSET:%.*]], i64 noundef [[LEN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NOUBSAN-NEXT:  [[ENTRY:.*:]]
// NOUBSAN-NEXT:    [[TMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[BUF]], align 8
// NOUBSAN-NEXT:    [[TMP_SROA_2_0_BUF_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[BUF]], i64 8
// NOUBSAN-NEXT:    [[TMP_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[TMP_SROA_2_0_BUF_SROA_IDX]], align 8
// NOUBSAN-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[TMP_SROA_0_0_COPYLOAD]], i64 [[OFFSET]]
// NOUBSAN-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH]], [[TMP_SROA_2_0_COPYLOAD]], {{!annotation ![0-9]+}}
// NOUBSAN-NEXT:    [[TMP_SROA_3_0_BUF_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[BUF]], i64 16
// NOUBSAN-NEXT:    [[TMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[TMP_SROA_3_0_BUF_SROA_IDX]], align 8
// NOUBSAN-NEXT:    [[CMP27_NOT:%.*]] = icmp ugt ptr [[TMP_SROA_3_0_COPYLOAD]], [[BOUND_PTR_ARITH]], {{!annotation ![0-9]+}}
// NOUBSAN-NEXT:    [[OR_COND:%.*]] = select i1 [[CMP_NOT]], i1 true, i1 [[CMP27_NOT]], {{!annotation ![0-9]+}}
// NOUBSAN-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[TMP_SROA_2_0_COPYLOAD]] to i64, {{!annotation ![0-9]+}}
// NOUBSAN-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[BOUND_PTR_ARITH]] to i64, {{!annotation ![0-9]+}}
// NOUBSAN-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], {{!annotation ![0-9]+}}
// NOUBSAN-NEXT:    [[CMP44_NOT:%.*]] = icmp ugt i64 [[LEN]], [[SUB_PTR_SUB]], {{!annotation ![0-9]+}}
// NOUBSAN-NEXT:    [[OR_COND52:%.*]] = or i1 [[OR_COND]], [[CMP44_NOT]], {{!annotation ![0-9]+}}
// NOUBSAN-NEXT:    br i1 [[OR_COND52]], label %[[TRAP:.*]], label %[[CONT:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// NOUBSAN:       [[TRAP]]:
// NOUBSAN-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// NOUBSAN-NEXT:    unreachable, {{!annotation ![0-9]+}}
// NOUBSAN:       [[CONT]]:
// NOUBSAN-NEXT:    tail call void @f_callee(ptr noundef [[BOUND_PTR_ARITH]], i64 noundef [[LEN]]) #[[ATTR5]]
// NOUBSAN-NEXT:    ret void
//
void f_call_bound_checks(char *__bidi_indexable buf, unsigned long long offset,
                         unsigned long long len) {
  f_callee(buf + offset, len);
}
