// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6


// RUN: %clang_cc1 -O0 -triple arm64e -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O0 -triple arm64e -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s
#include <ptrcheck.h>

int top_level_array[10];

int *__unsafe_indexable top_level_lower = __builtin_get_pointer_lower_bound(top_level_array);
int *__unsafe_indexable top_level_upper = __builtin_get_pointer_upper_bound(top_level_array);

int *__unsafe_indexable top_level_added_lower = __builtin_get_pointer_lower_bound(top_level_array + 5);
int *__unsafe_indexable top_level_added_upper = __builtin_get_pointer_upper_bound(top_level_array + 5);

int *__unsafe_indexable top_level_indexed_lower = __builtin_get_pointer_lower_bound(&top_level_array[5]);
int *__unsafe_indexable top_level_indexed_upper = __builtin_get_pointer_upper_bound(&top_level_array[5]);


struct subobject_array {
    int foo;
    int array[10];
    int bar;
};

struct subobject_array subobj;

int *__unsafe_indexable subobject_lower = __builtin_get_pointer_lower_bound(subobj.array);
int *__unsafe_indexable subobject_upper = __builtin_get_pointer_upper_bound(subobj.array);

int *__unsafe_indexable subobject_added_lower = __builtin_get_pointer_lower_bound(subobj.array + 5);
int *__unsafe_indexable subobject_added_upper = __builtin_get_pointer_upper_bound(subobj.array + 5);

int *__unsafe_indexable subobject_indexed_lower = __builtin_get_pointer_lower_bound(&subobj.array[5]);
int *__unsafe_indexable subobject_indexed_upper = __builtin_get_pointer_upper_bound(&subobj.array[5]);

struct subobject_array *__unsafe_indexable lower = __builtin_get_pointer_lower_bound(&subobj);
struct subobject_array *__unsafe_indexable upper = __builtin_get_pointer_upper_bound(&subobj);


// CHECK-LABEL: define dso_local void @getLowerBound(
// CHECK-SAME: ptr dead_on_unwind noalias writable sret(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 [[AGG_RESULT:%.*]], ptr noundef dead_on_return [[PTR:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_RESULT]], ptr align 8 [[PTR]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB]], ptr [[TMP0]], align 8
// CHECK-NEXT:    ret void
//
int *__bidi_indexable getLowerBound(int *__bidi_indexable ptr) {
    return __builtin_get_pointer_lower_bound(ptr);
}


// CHECK-LABEL: define dso_local void @getUpperBound(
// CHECK-SAME: ptr dead_on_unwind noalias writable sret(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 [[AGG_RESULT:%.*]], ptr noundef dead_on_return [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_RESULT]], ptr align 8 [[PTR]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP0]], align 8
// CHECK-NEXT:    ret void
//
int *__bidi_indexable getUpperBound(int *__bidi_indexable ptr) {
    return __builtin_get_pointer_upper_bound(ptr);
}

