// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --prefix-filecheck-ir-name FOO_ --version 
// REQUIRES: system-darwin

// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>


//

// CHECK-LABEL: define dso_local void @foo(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[DST:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[SRC:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[FOO_TMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// CHECK-NEXT:    [[AGG_TEMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP9:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// CHECK-NEXT:    [[AGG_TEMP16:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// CHECK-NEXT:    [[AGG_TEMP25:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// CHECK-NEXT:    [[AGG_TEMP34:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// CHECK-NEXT:    [[AGG_TEMP42:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.2", align 8
// CHECK-NEXT:    [[AGG_TEMP43:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// CHECK-NEXT:    [[AGG_TEMP58:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.2", align 8
// CHECK-NEXT:    [[AGG_TEMP59:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// CHECK-NEXT:    [[AGG_TEMP73:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP80:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP91:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP100:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP109:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP110:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP125:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP126:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP146:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP153:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[DST]], i8 0, i64 24, i1 false), !annotation [[META1:![0-9]+]]
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[SRC]], i8 0, i64 24, i1 false), !annotation [[META1]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[DST]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB]], ptr [[TMP2]], align 8
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP2]], ptr align 8 [[SRC]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR4:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR3]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB6:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR5]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB8:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR7]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[FOO_TMP1]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR4]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[FOO_TMP1]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB6]], ptr [[TMP4]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[FOO_TMP1]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB8]], ptr [[TMP5]], align 8
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP9]], ptr align 8 [[FOO_TMP1]], i64 24, i1 false), !annotation [[META2:![0-9]+]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP9]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR11:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR10]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP9]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB13:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR12]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP9]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB15:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR14]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP16]], ptr align 8 [[FOO_TMP1]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR17:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP16]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB18:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR17]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP16]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB18]], ptr [[TMP6]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP16]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR20:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR19]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP16]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB22:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR21]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP16]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB24:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR23]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR11]], [[WIDE_PTR_PTR20]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END:.*]], !annotation [[META2]]
// CHECK:       [[LAND_LHS_TRUE]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP25]], ptr align 8 [[FOO_TMP1]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR26:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP25]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB27:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR26]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP25]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB27]], ptr [[TMP7]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP25]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR29:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR28]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR30:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP25]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB31:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR30]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR32:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP25]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB33:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR32]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP34]], ptr align 8 [[FOO_TMP1]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR35:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP34]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR36:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR35]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR37:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP34]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB38:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR37]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR39:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP34]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB40:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR39]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP41:%.*]] = icmp ule ptr [[WIDE_PTR_PTR29]], [[WIDE_PTR_PTR36]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP41]], label %[[LAND_RHS:.*]], label %[[LAND_END]], !annotation [[META2]]
// CHECK:       [[LAND_RHS]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP43]], ptr align 8 [[FOO_TMP1]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR44:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP43]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB45:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR44]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP43]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB45]], ptr [[TMP8]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR46:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP43]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR47:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR46]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR48:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP43]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB49:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR48]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR50:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP43]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB51:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR50]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP42]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR47]], ptr [[TMP9]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP42]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB49]], ptr [[TMP10]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP42]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB51]], ptr [[TMP11]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR52:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP42]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR53:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR52]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR54:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP42]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB55:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR54]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR56:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP42]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB57:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR56]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP59]], ptr align 8 [[FOO_TMP1]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR60:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP59]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR61:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR60]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR62:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP59]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB63:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR62]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR64:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP59]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB65:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR64]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP58]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR61]], ptr [[TMP12]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP58]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB63]], ptr [[TMP13]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP58]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB65]], ptr [[TMP14]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR66:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP58]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR67:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR66]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR68:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP58]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB69:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR68]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR70:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP58]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB71:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR70]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR53]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR67]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META2]]
// CHECK-NEXT:    [[CMP72:%.*]] = icmp ule i64 10, [[SUB_PTR_SUB]], !annotation [[META2]]
// CHECK-NEXT:    br label %[[LAND_END]], !annotation [[META2]]
// CHECK:       [[LAND_END]]:
// CHECK-NEXT:    [[TMP15:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[CMP72]], %[[LAND_RHS]] ], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TMP15]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP73]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR74:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP73]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR75:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR74]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR76:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP73]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB77:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR76]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR78:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP73]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB79:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR78]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP80]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR81:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP80]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB82:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR81]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP80]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB82]], ptr [[TMP16]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR83:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP80]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR84:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR83]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR85:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP80]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB86:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR85]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR87:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP80]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB88:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR87]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP89:%.*]] = icmp ule ptr [[WIDE_PTR_PTR75]], [[WIDE_PTR_PTR84]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP89]], label %[[LAND_LHS_TRUE90:.*]], label %[[LAND_END143:.*]], !annotation [[META2]]
// CHECK:       [[LAND_LHS_TRUE90]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP91]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR92:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP91]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB93:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR92]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP91]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB93]], ptr [[TMP17]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR94:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP91]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR95:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR94]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR96:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP91]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB97:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR96]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR98:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP91]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB99:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR98]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP100]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR101:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP100]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR102:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR101]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR103:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP100]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB104:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR103]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR105:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP100]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB106:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR105]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP107:%.*]] = icmp ule ptr [[WIDE_PTR_PTR95]], [[WIDE_PTR_PTR102]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP107]], label %[[LAND_RHS108:.*]], label %[[LAND_END143]], !annotation [[META2]]
// CHECK:       [[LAND_RHS108]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP110]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR111:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP110]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB112:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR111]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP110]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB112]], ptr [[TMP18]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR113:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP110]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR114:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR113]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR115:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP110]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB116:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR115]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR117:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP110]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB118:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR117]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP109]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR114]], ptr [[TMP19]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP109]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB116]], ptr [[TMP20]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP109]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB118]], ptr [[TMP21]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR119:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP109]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR120:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR119]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR121:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP109]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB122:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR121]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR123:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP109]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB124:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR123]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP126]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR127:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP126]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR128:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR127]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR129:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP126]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB130:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR129]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR131:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP126]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB132:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR131]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP125]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR128]], ptr [[TMP22]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP125]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB130]], ptr [[TMP23]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP24:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP125]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB132]], ptr [[TMP24]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR133:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP125]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR134:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR133]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR135:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP125]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB136:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR135]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR137:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP125]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB138:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR137]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST139:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR120]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST140:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR134]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_SUB141:%.*]] = sub i64 [[SUB_PTR_LHS_CAST139]], [[SUB_PTR_RHS_CAST140]], !annotation [[META2]]
// CHECK-NEXT:    [[CMP142:%.*]] = icmp ule i64 10, [[SUB_PTR_SUB141]], !annotation [[META2]]
// CHECK-NEXT:    br label %[[LAND_END143]], !annotation [[META2]]
// CHECK:       [[LAND_END143]]:
// CHECK-NEXT:    [[TMP25:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE90]] ], [ false, %[[CONT]] ], [ [[CMP142]], %[[LAND_RHS108]] ], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TMP25]], label %[[CONT145:.*]], label %[[TRAP144:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// CHECK:       [[TRAP144]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT145]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP146]], ptr align 8 [[TMP]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR147:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP146]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR148:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR147]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR149:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP146]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB150:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR149]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR151:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP146]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB152:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR151]], align 8
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP153]], ptr align 8 [[FOO_TMP1]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR154:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP153]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR155:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR154]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR156:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP153]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB157:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR156]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR158:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP153]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB159:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR158]], align 8
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 1 [[WIDE_PTR_PTR148]], ptr align 1 [[WIDE_PTR_PTR155]], i64 10, i1 false)
// CHECK-NEXT:    call void @llvm.assume(i1 true)
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[WIDE_PTR_PTR148]], i64 10
// CHECK-NEXT:    ret void
//
void foo(void) {
    char *dst, *src;
    __builtin_memcpy(dst, src, 10);
}
//.
// CHECK: [[META1]] = !{!"bounds-safety-zero-init"}
// CHECK: [[META2]] = !{!"bounds-safety-generic"}
//.
