// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

static struct {
  int _a[42];
  int array[3];
  int _b[42];
} foo;

// CHECK-LABEL: define dso_local { ptr, ptr } @good(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret { ptr, ptr } { ptr getelementptr inbounds nuw (i8, ptr @foo, i64 168), ptr getelementptr inbounds nuw (i8, ptr @foo, i64 180) }
//
int *__indexable good(void) {
  int *__bidi_indexable p = foo.array;
  return p;
}

// CHECK-LABEL: define dso_local { ptr, ptr } @good_upper(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret { ptr, ptr } { ptr getelementptr inbounds nuw (i8, ptr @foo, i64 176), ptr getelementptr inbounds nuw (i8, ptr @foo, i64 180) }
//
int *__indexable good_upper(void) {
  int *__bidi_indexable p = foo.array;
  p += 2;
  return p;
}

// CHECK-LABEL: define dso_local { ptr, ptr } @good_upper2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret { ptr, ptr } { ptr getelementptr inbounds nuw (i8, ptr @foo, i64 208), ptr getelementptr inbounds nuw (i8, ptr @foo, i64 180) }
//
int *__indexable good_upper2(void) {
  int *__bidi_indexable p = foo.array;
  p += 10;
  return p;
}

// CHECK-LABEL: define dso_local noundef { ptr, ptr } @bad_lower(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
int *__indexable bad_lower(void) {
  int *__bidi_indexable p = foo.array;
  p -= 1;
  return p;
}

// CHECK-LABEL: define dso_local { ptr, ptr } @good_null(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret { ptr, ptr } zeroinitializer
//
int *__indexable good_null(void) {
  int *__bidi_indexable p = 0;
  return p;
}

// CHECK-LABEL: define dso_local noundef { ptr, ptr } @bad_null(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
int *__indexable bad_null(void) {
  // Try to cast { null, non-null, non-null } and make sure that we don't
  // return { null, non-null }.
  int *__bidi_indexable p = foo.array;
  while (--p)
    ;
  return p;
}
