// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6


// RUN: %clang_cc1 -O2 -fbounds-safety -emit-llvm -triple x86_64 %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm -triple x86_64 %s -o - | FileCheck %s

#include <ptrcheck.h>

typedef struct {
    int len;
    int *__counted_by(len) buf;
} S;

void Foo(int *__indexable ptr);

//

// CHECK-LABEL: define dso_local void @TestOK(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ARR:%.*]] = alloca [10 x i32], align 16
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[ARR]]) #[[ATTR5:[0-9]+]]
// CHECK-NEXT:    [[UPPER:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i64 40
// CHECK-NEXT:    call void @Foo(ptr noundef nonnull [[UPPER]], ptr noundef nonnull [[UPPER]]) #[[ATTR5]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[ARR]]) #[[ATTR5]]
// CHECK-NEXT:    ret void
//
void TestOK(void) {
  int arr[10];
  int *end_ptr = arr + 10;

  Foo(({
    S s = {10, arr};
    int *ptr;
    s.buf = end_ptr;
    s.len = 0;
    ptr = s.buf;
  }));
}

void FooCount1(int *__counted_by(1) ptr);

// CHECK-LABEL: define dso_local void @TestCountArgFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR6:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestCountArgFail(void) {
  int arr[10];
  int *end_ptr = arr + 10;

  FooCount1(({
    S s = {10, arr};
    int *ptr;
    s.buf = end_ptr;
    s.len = 0;
    ptr = s.buf;
  }));
}

void FooSingle(int *ptr);

// CHECK-LABEL: define dso_local void @TestSingleArgFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR4]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR6]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestSingleArgFail(void) {
  int arr[10];
  int *end_ptr = arr + 10;

  FooSingle(({
    S s = {10, arr};
    int *ptr;
    s.buf = end_ptr;
    s.len = 0;
    ptr = s.buf;
  }));
}

void *__sized_by(siz) my_alloc(unsigned long siz);

// CHECK-LABEL: define dso_local void @TestCountArgOK(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @my_alloc(i64 noundef 10) #[[ATTR5]]
// CHECK-NEXT:    tail call void @FooCount1(ptr noundef [[CALL]]) #[[ATTR5]]
// CHECK-NEXT:    ret void
//
void TestCountArgOK(void) {
  FooCount1(my_alloc(10));
}













