// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s


#include <ptrcheck.h>

struct Foo {
	unsigned count;
	int *__counted_by(count) bytes;
};

// CHECK-LABEL: @TestOK(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
void TestOK() {
	int arr[10];
	struct Foo f = { 10, arr };

	unsigned amt = 10;

	f.bytes += amt;
	f.count -= amt;
}

// CHECK-LABEL: @TestOK2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
void TestOK2() {
	int arr[10];
	struct Foo f = { 10, arr };

	unsigned amt = 10;

	f.count -= amt;
	f.bytes += amt;
}

// CHECK-LABEL: @TestFail(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation !{{[0-9]+}}
// CHECK-NEXT:    unreachable
//
void TestFail() {
	int arr[10];
	struct Foo f = { 10, arr };

	unsigned amt = 10;
	unsigned amt_1 = 9;

	f.bytes += amt;
	f.count -= amt_1;
}

// CHECK-LABEL: @TestFail2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation !{{[0-9]+}}
// CHECK-NEXT:    unreachable
//
void TestFail2() {
	int arr[10];
	struct Foo f = { 10, arr };

	unsigned amt = 10;
	unsigned amt_1 = 9;

	f.count -= amt_1;
	f.bytes += amt;
}
