// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --version 6

// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s --check-prefix=CHECK_O0
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s --check-prefix=CHECK_O2
// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s --check-prefix=CHECK_O0
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s --check-prefix=CHECK_O2
// CHECK_O0-LABEL: define dso_local i32 @foo(
// CHECK_O0-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK_O0-NEXT:  [[ENTRY:.*:]]
// CHECK_O0-NEXT:    [[ARRAY:%.*]] = alloca [10 x i32], align 16
// CHECK_O0-NEXT:    [[PTR:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK_O0-NEXT:    [[LOCAL:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK_O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK_O0-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[ARRAY]], i8 0, i64 40, i1 false)
// CHECK_O0-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARRAY]], i64 0, i64 0
// CHECK_O0-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY]], i64 10
// CHECK_O0-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[PTR]], i32 0, i32 0
// CHECK_O0-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP0]], align 8
// CHECK_O0-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[PTR]], i32 0, i32 1
// CHECK_O0-NEXT:    store ptr [[UPPER]], ptr [[TMP1]], align 8
// CHECK_O0-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[PTR]], i32 0, i32 2
// CHECK_O0-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP2]], align 8
// CHECK_O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[LOCAL]], ptr align 8 [[PTR]], i64 24, i1 false)
// CHECK_O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[LOCAL]], i64 24, i1 false)
// CHECK_O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK_O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK_O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK_O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK_O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK_O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK_O0-NEXT:    [[TMP3:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 1, {{!annotation ![0-9]+}}
// CHECK_O0-NEXT:    [[TMP4:%.*]] = icmp ule ptr [[TMP3]], [[WIDE_PTR_UB]], {{!annotation ![0-9]+}}
// CHECK_O0-NEXT:    br i1 [[TMP4]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK_O0:       [[TRAP]]:
// CHECK_O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK_O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK_O0:       [[CONT]]:
// CHECK_O0-NEXT:    [[TMP5:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[TMP3]], {{!annotation ![0-9]+}}
// CHECK_O0-NEXT:    br i1 [[TMP5]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK_O0:       [[TRAP1]]:
// CHECK_O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK_O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK_O0:       [[CONT2]]:
// CHECK_O0-NEXT:    [[TMP6:%.*]] = icmp uge ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_LB]], {{!annotation ![0-9]+}}
// CHECK_O0-NEXT:    br i1 [[TMP6]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK_O0:       [[TRAP3]]:
// CHECK_O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK_O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK_O0:       [[CONT4]]:
// CHECK_O0-NEXT:    [[TMP7:%.*]] = load i32, ptr [[WIDE_PTR_PTR]], align 4
// CHECK_O0-NEXT:    ret i32 [[TMP7]]
//
// CHECK_O2-LABEL: define dso_local noundef i32 @foo(
// CHECK_O2-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK_O2-NEXT:  [[ENTRY:.*:]]
// CHECK_O2-NEXT:    ret i32 0
//
int foo(void) {
    int array[10] = {0};
    int *ptr = array;
    const int *local = ptr;

    return *local;
}
