// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>
struct Item {
  int *__counted_by(len) buf;
  unsigned len;
};

// CHECK-LABEL: define dso_local void @TestIncOK(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void TestIncOK() {
  int arr[10];
  struct Item s = {arr, 10};
  s.buf++;
  s.len--;
}

// CHECK-LABEL: define dso_local void @TestIncOK2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void TestIncOK2() {
  int arr[10];
  struct Item s = {arr, 10};
  s.buf++;
  s.len = 9;
}

// CHECK-LABEL: define dso_local void @TestIncOK3(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void TestIncOK3() {
  int arr[10];
  struct Item s = {arr, 10};
  s.buf = arr + 1;
  s.len--;
}

// CHECK-LABEL: define dso_local void @TestIncTrap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestIncTrap() {
  int arr[10];
  struct Item s = {arr, 10};
  s.buf++;
  s.len = 10;
}

// CHECK-LABEL: define dso_local void @TestIncTrap2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestIncTrap2() {
  int arr[10];
  struct Item s = {arr, 10};
  s.buf++;
  s.len = s.len;
}
