// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 3


// RUN: %clang_cc1 -fbounds-safety -O2 -triple arm64 -emit-llvm -Wno-bounds-safety-init-list %s -o - | FileCheck %s

#include <ptrcheck.h>
#include <stddef.h>

// CHECK-LABEL: define dso_local void @to_bidi(
// CHECK-SAME: ptr dead_on_unwind noalias writable writeonly sret(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 captures(none) [[AGG_RESULT:%.*]], ptr noundef readnone captures(address_is_null) [[ARG:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq ptr [[ARG]], null, !annotation [[META6:![0-9]+]]
// CHECK-NEXT:    br i1 [[TOBOOL_NOT]], label [[BOUNDSCHECK_NULL:%.*]], label [[TRAP:%.*]], !annotation [[META6]]
// CHECK:       trap:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], !annotation [[META6]]
// CHECK-NEXT:    unreachable, !annotation [[META6]]
// CHECK:       boundscheck.null:
// CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(24) [[AGG_RESULT]], i8 0, i64 24, i1 false)
// CHECK-NEXT:    ret void
//
int *__bidi_indexable to_bidi(int * arg) {
    int len = -1;
    int * __counted_by_or_null(len) p = arg;
    return p;
}

// CHECK-LABEL: define dso_local void @to_bidi_literal_count(
// CHECK-SAME: ptr dead_on_unwind noalias writable writeonly sret(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 captures(none) [[AGG_RESULT:%.*]], ptr noundef readnone captures(address_is_null) [[ARG:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq ptr [[ARG]], null, !annotation [[META6]]
// CHECK-NEXT:    br i1 [[TOBOOL_NOT]], label [[BOUNDSCHECK_NULL:%.*]], label [[TRAP_CRITEDGE:%.*]], !annotation [[META6]]
// CHECK:       trap.critedge:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META6]]
// CHECK-NEXT:    unreachable, !annotation [[META6]]
// CHECK:       boundscheck.null:
// CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(24) [[AGG_RESULT]], i8 0, i64 24, i1 false)
// CHECK-NEXT:    ret void
//
int *__bidi_indexable to_bidi_literal_count(int * arg) {
    int * __counted_by_or_null(-1) p = arg;
    return p;
}

// CHECK-LABEL: define dso_local void @to_bidi_const_count(
// CHECK-SAME: ptr dead_on_unwind noalias writable writeonly sret(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 captures(none) [[AGG_RESULT:%.*]], ptr noundef readnone captures(address_is_null) [[ARG:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq ptr [[ARG]], null, !annotation [[META6]]
// CHECK-NEXT:    br i1 [[TOBOOL_NOT]], label [[BOUNDSCHECK_NULL:%.*]], label [[TRAP_CRITEDGE:%.*]], !annotation [[META6]]
// CHECK:       trap.critedge:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META6]]
// CHECK-NEXT:    unreachable, !annotation [[META6]]
// CHECK:       boundscheck.null:
// CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(24) [[AGG_RESULT]], i8 0, i64 24, i1 false)
// CHECK-NEXT:    ret void
//
int *__bidi_indexable to_bidi_const_count(int * arg) {
    const int len = -1;
    int * __counted_by_or_null(len) p = arg;
    return p;
}

// CHECK-LABEL: define dso_local void @back_and_forth_to_bidi(
// CHECK-SAME: ptr noundef readnone captures(none) dead_on_return [[ARG:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  boundscheck.null49:
// CHECK-NEXT:    ret void
//
void back_and_forth_to_bidi(int * __bidi_indexable arg) {
    int len = -1;
    int * __counted_by_or_null(len) p = NULL;
    arg = p;
    p = arg;
    len = len;
    arg = p;
}

