// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --version 6


// RUN: %clang_cc1 -O2 -fbounds-safety -triple x86_64 -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -triple x86_64 -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

struct Packet {
    int *__counted_by(len) buf;
    int len;
};

struct PacketUnsigned {
  int *__counted_by(len) buf;
  unsigned long long len;
};

int *__counted_by(cnt) my_alloc_int(int cnt);
void *__sized_by(siz) my_alloc(int siz);
int *__sized_by(siz) my_alloc_int_siz(int siz);


// CHECK-LABEL: define dso_local void @TestCountIntFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @my_alloc_int(i32 noundef 9) #[[ATTR4:[0-9]+]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestCountIntFail(void) {
    struct Packet p;
    int siz = 9;
    p.buf = my_alloc_int(siz);
    p.len = 10;
}

// CHECK-LABEL: define dso_local void @TestCountNegFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @my_alloc_int(i32 noundef -1) #[[ATTR4]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestCountNegFail(void) {
  struct Packet p;
  int siz = -1;
  p.buf = my_alloc_int(siz);
  p.len = 10;
}

// CHECK-LABEL: define dso_local void @TestUCountNegFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @my_alloc_int(i32 noundef -1) #[[ATTR4]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestUCountNegFail(void) {
  struct PacketUnsigned p;
  int siz = -1;
  p.buf = my_alloc_int(siz);
  p.len = 10;
}

// CHECK-LABEL: define dso_local void @TestCountNegRetFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @my_alloc_int(i32 noundef -1) #[[ATTR4]]
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[CALL]], i64 -4
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[CALL]], i64 4, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[ADD_PTR]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[CALL]], [[TMP0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = and i1 [[TMP1]], [[TMP2]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[CONT2:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT2]]:
// CHECK-NEXT:    ret void
//
void TestCountNegRetFail(void) {
  int *local_p = my_alloc_int(-1); //rdar://80808704
  (void)*local_p;
}

// CHECK-LABEL: define dso_local void @TestCountIntOK(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @my_alloc_int(i32 noundef 10) #[[ATTR4]]
// CHECK-NEXT:    ret void
//
void TestCountIntOK(void) {
  struct Packet p;
  int siz = 10;
  p.buf = my_alloc_int(siz);
  p.len = 10;
}

// CHECK-LABEL: define dso_local void @TestSizeFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @my_alloc(i32 noundef 39) #[[ATTR4]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestSizeFail(void) {
  struct Packet p;
  int siz = 10 * sizeof(int) - 1;
  p.buf = my_alloc(siz);
  p.len = 10;
}

// CHECK-LABEL: define dso_local void @TestSizeOK(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @my_alloc(i32 noundef 40) #[[ATTR4]]
// CHECK-NEXT:    ret void
//
void TestSizeOK(void) {
  struct Packet p;
  int siz = 10 * sizeof(int);
  p.buf = my_alloc(siz);
  p.len = 10;
}

// CHECK-LABEL: define dso_local void @TestIntSizeFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @my_alloc_int_siz(i32 noundef 39) #[[ATTR4]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestIntSizeFail(void) {
  struct Packet p;
  int siz = 10 * sizeof(int) - 1;
  p.buf = my_alloc_int_siz(siz);
  p.len = 10;
}

// CHECK-LABEL: define dso_local void @TestIntSizeOK(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @my_alloc_int_siz(i32 noundef 40) #[[ATTR4]]
// CHECK-NEXT:    ret void
//
void TestIntSizeOK(void) {
  struct Packet p;
  int siz = 10 * sizeof(int);
  p.buf = my_alloc_int_siz(siz);
  p.len = 10;
}
