// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 5


// RUN: %clang_cc1 -triple x86_64 -fbounds-safety -emit-llvm -fbounds-safety-bringup-missing-checks=indirect_count_update -DWITH -O2 %s -o - | FileCheck %s
// RUN: %clang_cc1 -triple x86_64 -fbounds-safety -emit-llvm -fno-bounds-safety-bringup-missing-checks=indirect_count_update -O2 %s -o - | FileCheck %s --check-prefix WITHOUT
#include <ptrcheck.h>

// CHECK-LABEL: define dso_local void @foo(
// CHECK-SAME: ptr noundef writeonly captures(address) [[X:%.*]], i32 noundef [[COUNT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[IDX_EXT:%.*]] = zext i32 [[COUNT]] to i64
// CHECK-NEXT:    [[ADD_PTR_IDX:%.*]] = shl nuw nsw i64 [[IDX_EXT]], 2, !annotation [[META5:![0-9]+]]
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[X]], i64 [[ADD_PTR_IDX]], !annotation [[META5]]
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[X]], i64 4
// CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH]], [[ADD_PTR]], !annotation [[META5]]
// CHECK-NEXT:    [[CMP15_NOT:%.*]] = icmp ugt ptr [[X]], [[BOUND_PTR_ARITH]], !annotation [[META5]]
// CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP15_NOT]], [[CMP_NOT]], !annotation [[META5]]
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[TRAP:.*]], label %[[LAND_RHS:.*]], !annotation [[META5]]
// CHECK:       [[LAND_RHS]]:
// CHECK-NEXT:    [[SUB:%.*]] = add i32 [[COUNT]], -1, !annotation [[META6:![0-9]+]]
// CHECK-NEXT:    [[CONV:%.*]] = zext i32 [[SUB]] to i64, !annotation [[META5]]
// CHECK-NEXT:    [[GEPDIFF:%.*]] = add nsw i64 [[ADD_PTR_IDX]], -4, !annotation [[META8:![0-9]+]]
// CHECK-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[GEPDIFF]], 2, !annotation [[META5]]
// CHECK-NEXT:    [[CMP26_NOT:%.*]] = icmp slt i64 [[SUB_PTR_DIV]], [[CONV]], !annotation [[META5]]
// CHECK-NEXT:    br i1 [[CMP26_NOT]], label %[[TRAP]], label %[[CONT:.*]], {{!prof ![0-9]+}}, !annotation [[META5]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR2:[0-9]+]], !annotation [[META5]]
// CHECK-NEXT:    unreachable, !annotation [[META5]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    store i32 0, ptr [[X]], align 4, !tbaa [[TBAA1:![0-9]+]]
// CHECK-NEXT:    ret void
//
// WITHOUT-LABEL: define dso_local void @foo(
// WITHOUT-SAME: ptr noundef writeonly captures(none) initializes((0, 4)) [[X:%.*]], i32 noundef [[COUNT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// WITHOUT-NEXT:  [[ENTRY:.*:]]
// WITHOUT-NEXT:    store i32 0, ptr [[X]], align 4, !tbaa [[TBAA1:![0-9]+]]
// WITHOUT-NEXT:    ret void
//
void foo(int *__counted_by(count) x, unsigned count) {
	*x++ = 0;
    #ifdef WITH
    // NOTE: It's necessary to exclude the count update with
    // indirect_count_update disabled otherwise we'll get diagnostics about
    // the a missing assignment to `x`.
    count--;
    #endif
}

// CHECK-LABEL: define dso_local void @bar(
// CHECK-SAME: ptr noundef writeonly captures(address) [[X:%.*]], i32 noundef [[COUNT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[COUNT]] to i64
// CHECK-NEXT:    [[ADD_PTR_IDX:%.*]] = shl nsw i64 [[IDX_EXT]], 2, !annotation [[META8]]
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[X]], i64 [[ADD_PTR_IDX]], !annotation [[META5]]
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[X]], i64 4
// CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH]], [[ADD_PTR]], !annotation [[META5]]
// CHECK-NEXT:    [[CMP15_NOT:%.*]] = icmp ugt ptr [[X]], [[BOUND_PTR_ARITH]], !annotation [[META5]]
// CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP15_NOT]], [[CMP_NOT]], !annotation [[META5]]
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[TRAP:.*]], label %[[LAND_RHS:.*]], !annotation [[META5]]
// CHECK:       [[LAND_RHS]]:
// CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[COUNT]], -1, !annotation [[META11:![0-9]+]]
// CHECK-NEXT:    [[CONV:%.*]] = sext i32 [[SUB]] to i64, !annotation [[META5]]
// CHECK-NEXT:    [[GEPDIFF:%.*]] = add nsw i64 [[ADD_PTR_IDX]], -4, !annotation [[META8]]
// CHECK-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[GEPDIFF]], 2, !annotation [[META5]]
// CHECK-NEXT:    [[CMP26:%.*]] = icmp sge i64 [[SUB_PTR_DIV]], [[CONV]], !annotation [[META5]]
// CHECK-NEXT:    [[CMP29:%.*]] = icmp sgt i32 [[COUNT]], 0, !annotation [[META5]]
// CHECK-NEXT:    [[SPEC_SELECT:%.*]] = and i1 [[CMP29]], [[CMP26]]
// CHECK-NEXT:    br i1 [[SPEC_SELECT]], label %[[CONT:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, !annotation [[META5]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR2]], !annotation [[META5]]
// CHECK-NEXT:    unreachable, !annotation [[META5]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    store i32 0, ptr [[BOUND_PTR_ARITH]], align 4, !tbaa [[TBAA1]]
// CHECK-NEXT:    ret void
//
// WITHOUT-LABEL: define dso_local void @bar(
// WITHOUT-SAME: ptr noundef writeonly captures(none) initializes((4, 8)) [[X:%.*]], i32 noundef [[COUNT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// WITHOUT-NEXT:  [[ENTRY:.*:]]
// WITHOUT-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[X]], i64 4
// WITHOUT-NEXT:    store i32 0, ptr [[BOUND_PTR_ARITH]], align 4, !tbaa [[TBAA1]]
// WITHOUT-NEXT:    ret void
//
void bar(int *__counted_by(count) x, int count) {
    #ifdef WITH
    // NOTE: It's necessary to exclude the count update with
    // indirect_count_update disabled otherwise we'll get diagnostics about
    // the a missing assignment to `x`.
    count = count - 1;
    #endif
	*(x = x+1) = 0;
}

//.
// CHECK: [[TBAA1]] = !{[[META2:![0-9]+]], [[META2]], i64 0}
// CHECK: [[META2]] = !{!"int", [[META3:![0-9]+]], i64 0}
// CHECK: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// CHECK: [[META4]] = !{!"Simple C/C++ TBAA"}
// CHECK: [[META5]] = !{!"bounds-safety-generic"}
// CHECK: [[META6]] = !{[[META7:![0-9]+]]}
// CHECK: [[META7]] = !{!"bounds-safety-missed-optimization-nsw", !"Check can not be removed because the arithmetic operation might wrap in the signed sense. Optimize the check by adding conditions to check for overflow before doing the operation"}
// CHECK: [[META8]] = !{!"bounds-safety-generic", [[META9:![0-9]+]]}
// CHECK: [[META9]] = !{!"bounds-safety-missed-optimization-nuw", !"Check can not be removed because the arithmetic operation might wrap in the unsigned sense. Optimize the check by adding conditions to check for overflow before doing the operation"}
// CHECK: [[META11]] = !{[[META9]]}
//.
// WITHOUT: [[TBAA1]] = !{[[META2:![0-9]+]], [[META2]], i64 0}
// WITHOUT: [[META2]] = !{!"int", [[META3:![0-9]+]], i64 0}
// WITHOUT: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// WITHOUT: [[META4]] = !{!"Simple C/C++ TBAA"}
//.
