// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

__attribute__((const)) static int get_const_count() {
  return 4;
}

// CHECK-LABEL: define dso_local void @test_assign_const_count_ok(
// CHECK-SAME: ptr noundef readnone captures(none) [[COUNTED_PTR:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void test_assign_const_count_ok(int *__counted_by(get_const_count()) counted_ptr) {
  int arr[4];
  counted_ptr = arr;
}

// CHECK-LABEL: define dso_local void @test_assign_const_count_fail(
// CHECK-SAME: ptr noundef readnone captures(none) [[COUNTED_PTR:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void test_assign_const_count_fail(int *__counted_by(get_const_count()) counted_ptr) {
  int arr[3];
  counted_ptr = arr;
}

__attribute__((const)) static int get_const_size() {
  return 10;
}

// CHECK-LABEL: define dso_local void @test_assign_const_size_ok(
// CHECK-SAME: ptr noundef readnone captures(none) [[SIZED_PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void test_assign_const_size_ok(void *__sized_by(get_const_size()) sized_ptr) {
  char arr[10];
  sized_ptr = arr;
}

// CHECK-LABEL: define dso_local void @test_assign_const_size_fail(
// CHECK-SAME: ptr noundef readnone captures(none) [[SIZED_PTR:%.*]]) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void test_assign_const_size_fail(void *__sized_by(get_const_size()) sized_ptr) {
  char arr[9];
  sized_ptr = arr;
}

// flexible array member
struct struct_flex {
  long dummy;
  long fam[__counted_by(get_const_count())];
};

// CHECK-LABEL: define dso_local void @test_flexible_assign_const_count_ok(
// CHECK-SAME: ptr noundef readnone captures(none) [[FLEX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void test_flexible_assign_const_count_ok(struct struct_flex *flex) {
  char arr[sizeof(long) * 5];
  flex = (struct struct_flex *)arr;
}

// CHECK-LABEL: define dso_local void @test_flexible_assign_const_count_fail(
// CHECK-SAME: ptr noundef readnone captures(none) [[FLEX:%.*]]) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void test_flexible_assign_const_count_fail(struct struct_flex *flex) {
  char arr[sizeof(long) * 4];
  flex = (struct struct_flex *)arr;
}
