// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py


// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

struct Foo {
  int *__counted_by(l) bp;
  int l;
};

struct FooUnsigned {
  int *__counted_by(l) bp;
  unsigned long long l;
};

// CHECK-LABEL: @TestOK(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
void TestOK(void) {
  int arr[11];
  struct Foo f = {arr, 11};
  f.bp = f.bp;
  f.l--;
}

// CHECK-LABEL: @TestEdgeOK(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
void TestEdgeOK(void) {
  int arr[11];
  struct Foo f = {arr, 1};
  f.bp = f.bp;
  f.l--;
}

// CHECK-LABEL: @TestUnsignedEdgeOK(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
void TestUnsignedEdgeOK(void) {
  int arr[11];
  struct FooUnsigned f = {arr, 1};
  f.bp = f.bp;
  f.l--;
}

// CHECK-LABEL: @TestFail1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation !{{[0-9]+}}
// CHECK-NEXT:    unreachable
//
void TestFail1(void) {
  int arr[11];
  struct Foo f = {arr, 0};
  f.bp = f.bp;
  f.l--;
}


// CHECK-LABEL: @TestUnsignedCountFail(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation !{{[0-9]+}}
// CHECK-NEXT:    unreachable
//
void TestUnsignedCountFail(void) {
  int arr[11];
  struct FooUnsigned f = {arr, 0};
  f.bp = f.bp;
  f.l--;
}

struct Bar {
  int *__counted_by(l - m) bp;
  int l;
  int m;
};

// CHECK-LABEL: @TestBarFail(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation !{{[0-9]+}}
// CHECK-NEXT:    unreachable
//
void TestBarFail(void) {
  int arr[11];
  struct Bar f = {arr, 11, 1};
  f.bp = f.bp;
  f.l = f.l;
  f.m--; // FIXME: rdar://80811527
}
