// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --version 6

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

// CHECK-LABEL: define dso_local void @foo1(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], ptr noundef captures(none) [[LEN:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LEN]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP26:%.*]] = icmp ugt i32 [[TMP0]], 41, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP26]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    store i32 42, ptr [[LEN]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    ret void
//
void foo1(int *__counted_by(*len) buf, unsigned *len) {
  *len = 42;
}

// CHECK-LABEL: define dso_local void @foo2(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], ptr noundef captures(none) [[LEN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LEN]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP26:%.*]] = icmp ugt i32 [[TMP0]], 41, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP26]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    store i32 42, ptr [[LEN]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    ret void
//
void foo2(int *__counted_by(*len) buf, unsigned *len) {
  buf = buf;
  *len = 42;
}

// CHECK-LABEL: define dso_local void @bar1(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], ptr noundef captures(none) [[LEN:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LEN]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP26:%.*]] = icmp ugt i32 [[TMP0]], 41, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP26]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    store i32 10, ptr [[LEN]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    ret void
//
void bar1(int *__counted_by(*len) buf, unsigned *len) {
  *len = 42;
bb:
  *len = 10;
}

// CHECK-LABEL: define dso_local void @bar2(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], ptr noundef captures(none) [[LEN:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LEN]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP26:%.*]] = icmp ugt i32 [[TMP0]], 41, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP26]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    store i32 42, ptr [[LEN]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    br label %[[TRAP]]
//
void bar2(int *__counted_by(*len) buf, unsigned *len) {
  *len = 42;
bb:
  *len = 100;
}

inline void baz1(int *__counted_by(*len) buf, unsigned *len) { *len = 11; }

// CHECK-LABEL: define dso_local void @baz2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  [[TRAP_I:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void baz2(void) {
  int arr[10];
  unsigned len = 10;
  int *__counted_by(len) buf = arr;
  baz1(buf, &len);
}
