// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

// CHECK-LABEL: define dso_local void @foo1(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], ptr noundef captures(none) [[SIZE:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[SIZE]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP33:%.*]] = icmp ugt i32 [[TMP0]], 39, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP33]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    store i32 40, ptr [[SIZE]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    ret void
//
void foo1(int *__sized_by(*size) buf, unsigned *size) {
  *size = 40;
}

// CHECK-LABEL: define dso_local void @foo2(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], ptr noundef captures(none) [[SIZE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[SIZE]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP33:%.*]] = icmp ugt i32 [[TMP0]], 39, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP33]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    store i32 40, ptr [[SIZE]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    ret void
//
void foo2(int *__sized_by(*size) buf, unsigned *size) {
  buf = buf;
  *size = 40;
}

// CHECK-LABEL: define dso_local void @bar1(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], ptr noundef captures(none) [[SIZE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[SIZE]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP33:%.*]] = icmp ugt i32 [[TMP0]], 39, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP33]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    store i32 8, ptr [[SIZE]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    ret void
//
void bar1(int *__sized_by(*size) buf, unsigned *size) {
  *size = 40;
bb:
  *size = 8;
}

// CHECK-LABEL: define dso_local void @bar2(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], ptr noundef captures(none) [[SIZE:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[SIZE]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP33:%.*]] = icmp ugt i32 [[TMP0]], 39, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP33]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    store i32 40, ptr [[SIZE]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    br label %[[TRAP]]
//
void bar2(int *__sized_by(*size) buf, unsigned *size) {
  *size = 40;
bb:
  *size = 100;
}

inline void baz1(int *__sized_by(*size) buf, unsigned *size) { *size = 64; }

// CHECK-LABEL: define dso_local void @baz2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  [[TRAP_I:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void baz2(void) {
  int arr[10];
  unsigned size = 40;
  int *__sized_by(size) buf = arr;
  baz1(buf, &size);
}
