// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --prefix-filecheck-ir-name TMP_ --version 6

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s


#include <ptrcheck.h>

// CHECK-LABEL: define dso_local void @f_inout_count(
// CHECK-SAME: ptr noundef readnone captures(none) [[BUF:%.*]], ptr noundef readnone captures(none) [[OUT_LEN:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void f_inout_count(int *__counted_by(*out_len) buf, int *out_len) {}

// CHECK-LABEL: define dso_local void @success(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void success() {
  int arr[10];
  int len = 10;
  f_inout_count(arr, &len);
}

// CHECK-LABEL: define dso_local void @fail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], !annotation [[META5:![0-9]+]]
// CHECK-NEXT:    unreachable, !annotation [[META5]]
//
void fail() {
  int arr[10];
  int len = 11;
  f_inout_count(arr, &len);
}

// CHECK-LABEL: define dso_local void @pass_out_len(
// CHECK-SAME: ptr noundef readnone captures(none) [[ARR:%.*]], ptr noundef readonly captures(none) [[OUT_LEN:%.*]]) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[OUT_LEN]], align 4, !tbaa [[INT_TBAA1:![0-9]+]]
// CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp slt i32 [[TMP0]], 0, !annotation [[META6:![0-9]+]]
// CHECK-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !annotation [[META6]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META6]]
// CHECK-NEXT:    unreachable, !annotation [[META6]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    ret void
//
void pass_out_len(int *__counted_by(*out_len) arr, int *out_len) {
  f_inout_count(arr, out_len);
}

// CHECK-LABEL: define dso_local void @pass_addr_of_len(
// CHECK-SAME: ptr noundef readnone captures(none) [[ARR:%.*]], i32 noundef [[LEN:%.*]]) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp slt i32 [[LEN]], 0, !annotation [[META6]]
// CHECK-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[BOUNDSCHECK_NULL:.*]], !annotation [[META6]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META5]]
// CHECK-NEXT:    unreachable, !annotation [[META5]]
// CHECK:       [[BOUNDSCHECK_NULL]]:
// CHECK-NEXT:    ret void
//
void pass_addr_of_len(int *__counted_by(len) arr, int len) {
  f_inout_count(arr, &len);
}
//.
// CHECK: [[INT_TBAA1]] = !{[[META2:![0-9]+]], [[META2]], i64 0}
// CHECK: [[META2]] = !{!"int", [[META3:![0-9]+]], i64 0}
// CHECK: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// CHECK: [[META4]] = !{!"Simple C/C++ TBAA"}
// CHECK: [[META5]] = !{!"bounds-safety-check-ptr-le-upper-bound", !"bounds-safety-check-ptr-ge-lower-bound", !"bounds-safety-generic"}
// CHECK: [[META6]] = !{!"bounds-safety-generic"}
//.
