// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

static inline void TestOKImpl(int *__ended_by(*out_end) *out_start,
                              int **out_end) {
  int arr[10];
  *out_start = arr;
  *out_end = arr + 10;
}

// CHECK-LABEL: define dso_local void @TestOK(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void TestOK() {
  int *end;
  int *__ended_by(end) start;
  TestOKImpl(&start, &end);
}

static inline void TestStartFailImpl(int *__ended_by(*out_end) *out_start,
                                     int **out_end) {
  int arr[10];
  *out_start = arr - 1;
  *out_end = arr + 10;
}

// CHECK-LABEL: define dso_local void @TestStartFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ARR_I:%.*]] = alloca [10 x i32], align 16
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[ARR_I]]) #[[ATTR5:[0-9]+]]
// CHECK-NEXT:    [[UPPER_I:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR_I]], i64 40
// CHECK-NEXT:    [[BOUND_PTR_ARITH_I:%.*]] = getelementptr i8, ptr [[ARR_I]], i64 -4
// CHECK-NEXT:    [[CMP24_NOT_I:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH_I]], [[UPPER_I]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP35_NOT_I:%.*]] = icmp ugt ptr [[ARR_I]], [[BOUND_PTR_ARITH_I]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND_I:%.*]] = or i1 [[CMP24_NOT_I]], [[CMP35_NOT_I]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND_I]], label %[[TRAP_I:.*]], label %[[TESTSTARTFAILIMPL_EXIT:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP_I]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR6:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[TESTSTARTFAILIMPL_EXIT]]:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[ARR_I]]) #[[ATTR5]]
// CHECK-NEXT:    ret void
//
void TestStartFail() {
  int *end;
  int *__ended_by(end) start;
  TestStartFailImpl(&start, &end);
}

static inline void TestEndFailImpl(int *__ended_by(*out_end) *out_start,
                                   int **out_end) {
  int arr[10];
  *out_start = arr;
  *out_end = arr + 11;
}

// CHECK-LABEL: define dso_local void @TestEndFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ARR_I:%.*]] = alloca [10 x i32], align 16
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[ARR_I]]) #[[ATTR5]]
// CHECK-NEXT:    [[UPPER_I:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR_I]], i64 40
// CHECK-NEXT:    [[BOUND_PTR_ARITH_I:%.*]] = getelementptr i8, ptr [[ARR_I]], i64 44
// CHECK-NEXT:    [[CMP_NOT_I:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH_I]], [[UPPER_I]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP22_NOT_I:%.*]] = icmp ugt ptr [[ARR_I]], [[BOUND_PTR_ARITH_I]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND_I:%.*]] = or i1 [[CMP_NOT_I]], [[CMP22_NOT_I]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND_I]], label %[[TRAP_I:.*]], label %[[TESTENDFAILIMPL_EXIT:.*]], {{!annotation ![0-9]+}}
// CHECK:       [[TRAP_I]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR6]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[TESTENDFAILIMPL_EXIT]]:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[ARR_I]]) #[[ATTR5]]
// CHECK-NEXT:    ret void
//
void TestEndFail() {
  int *end;
  int *__ended_by(end) start;
  TestEndFailImpl(&start, &end);
}

static inline void TestRangeFailImpl(int *__ended_by(*out_end) *out_start,
                                     int **out_end) {
  int arr[10];
  *out_start = arr + 1;
  *out_end = arr;
}

// CHECK-LABEL: define dso_local void @TestRangeFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR6]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestRangeFail() {
  int *end;
  int *__ended_by(end) start;
  TestRangeFailImpl(&start, &end);
}
