// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --prefix-filecheck-ir-name _TMP_ --version 5

// Note: Specifying the triple seems to be necessary for `update_cc_test_checks.py` to work
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -emit-llvm -fbounds-safety -fbounds-safety-bringup-missing-checks=ended_by_lower_bound -o - %s | FileCheck %s
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -x objective-c  -emit-llvm -fexperimental-bounds-safety-objc -fbounds-safety -fbounds-safety-bringup-missing-checks=ended_by_lower_bound -o - %s | FileCheck %s
#include <ptrcheck.h>


void ended_by(const char *__ended_by(end) start, const char *end);

// CHECK-LABEL: define dso_local void @pass_const_size_arr_in_bounds(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[LOCAL:%.*]] = alloca [10 x i8], align 1
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[LOCAL]]) #[[ATTR4:[0-9]+]]
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr inbounds nuw i8, ptr [[LOCAL]], i64 10
// CHECK-NEXT:    call void @ended_by(ptr noundef nonnull [[LOCAL]], ptr noundef nonnull [[BOUND_PTR_ARITH]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[LOCAL]]) #[[ATTR4]]
// CHECK-NEXT:    ret void
//
void pass_const_size_arr_in_bounds(void) {
  char local[10];
  ended_by(local, &local[10]);
}

// CHECK-LABEL: define dso_local void @pass_const_size_arr_start_oob(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[LOCAL:%.*]] = alloca [10 x i8], align 1
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[LOCAL]]) #[[ATTR4]]
// CHECK-NEXT:    [[UPPER:%.*]] = getelementptr inbounds nuw i8, ptr [[LOCAL]], i64 10
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[LOCAL]], i64 -2
// CHECK-NEXT:    [[CMP30_NOT:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH]], [[UPPER]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[CMP47_NOT:%.*]] = icmp ugt ptr [[LOCAL]], [[BOUND_PTR_ARITH]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP30_NOT]], [[CMP47_NOT]], !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[TRAP:.*]], label %[[CONT:.*]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    call void @ended_by(ptr noundef [[BOUND_PTR_ARITH]], ptr noundef nonnull [[UPPER]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[LOCAL]]) #[[ATTR4]]
// CHECK-NEXT:    ret void
//
void pass_const_size_arr_start_oob(void) {
  char local[10];
  ended_by(local - 2, &local[10]);
}

// CHECK-LABEL: define dso_local void @pass_const_size_arr_end_oob(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[LOCAL:%.*]] = alloca [10 x i8], align 1
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[LOCAL]]) #[[ATTR4]]
// CHECK-NEXT:    [[UPPER:%.*]] = getelementptr inbounds nuw i8, ptr [[LOCAL]], i64 10
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[LOCAL]], i64 11
// CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH]], [[UPPER]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[CMP28_NOT:%.*]] = icmp ugt ptr [[LOCAL]], [[BOUND_PTR_ARITH]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP_NOT]], [[CMP28_NOT]], !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[TRAP:.*]], label %[[CONT:.*]], !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    call void @ended_by(ptr noundef nonnull [[LOCAL]], ptr noundef [[BOUND_PTR_ARITH]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[LOCAL]]) #[[ATTR4]]
// CHECK-NEXT:    ret void
//
void pass_const_size_arr_end_oob(void) {
  char local[10];
  ended_by(local, local + 11);
}

// CHECK-LABEL: define dso_local void @pass_explicit_indexable(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[LOCAL:%.*]] = alloca [10 x i8], align 1
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[LOCAL]]) #[[ATTR4]]
// CHECK-NEXT:    [[UPPER:%.*]] = getelementptr inbounds nuw i8, ptr [[LOCAL]], i64 10
// CHECK-NEXT:    call void @ended_by(ptr noundef nonnull [[LOCAL]], ptr noundef nonnull [[UPPER]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[LOCAL]]) #[[ATTR4]]
// CHECK-NEXT:    ret void
//
void pass_explicit_indexable(void) {
  char local[10];
  char* __indexable ilocal = local;
  ended_by(ilocal, &ilocal[10]);
}

// CHECK-LABEL: define dso_local void @pass_explict_bidi_indexable(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[LOCAL:%.*]] = alloca [10 x i8], align 1
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[LOCAL]]) #[[ATTR4]]
// CHECK-NEXT:    [[UPPER:%.*]] = getelementptr inbounds nuw i8, ptr [[LOCAL]], i64 10
// CHECK-NEXT:    call void @ended_by(ptr noundef nonnull [[LOCAL]], ptr noundef nonnull [[UPPER]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[LOCAL]]) #[[ATTR4]]
// CHECK-NEXT:    ret void
//
void pass_explict_bidi_indexable(void) {
  char local[10];
  char* __bidi_indexable bilocal = local;
  ended_by(bilocal, &bilocal[10]);
}

// CHECK-LABEL: define dso_local void @pass_ended_by(
// CHECK-SAME: ptr noundef [[START:%.*]], ptr noundef [[END:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CMP26_NOT:%.*]] = icmp ugt ptr [[START]], [[END]], !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP26_NOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    tail call void @ended_by(ptr noundef [[START]], ptr noundef [[END]]) #[[ATTR4]]
// CHECK-NEXT:    ret void
//
void pass_ended_by(char* __ended_by(end) start, const char* end) {
  ended_by(start, end);
}

// CHECK-LABEL: define dso_local void @pass_counted_by(
// CHECK-SAME: ptr noundef [[START:%.*]], i32 noundef [[COUNT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CMP28_NOT:%.*]] = icmp slt i32 [[COUNT]], 0, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP28_NOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    [[IDX_EXT:%.*]] = zext nneg i32 [[COUNT]] to i64
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[START]], i64 [[IDX_EXT]]
// CHECK-NEXT:    tail call void @ended_by(ptr noundef [[START]], ptr noundef [[ADD_PTR]]) #[[ATTR4]]
// CHECK-NEXT:    ret void
//
void pass_counted_by(char* __counted_by(count) start, int count) {
  ended_by(start, start + count);
}
