// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s
#include <ptrcheck.h>
struct S {
    int *__ended_by(end) iter;
    int *end;
    int *__ended_by(iter) start;
};

void foo(void);

// CHECK-LABEL: define dso_local void @TestRangeOK1(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void TestRangeOK1(void) {
  int arr[10];
  struct S s;
  s.start = arr;
  s.iter = arr;
  s.end = arr + 1;
}

// CHECK-LABEL: define dso_local void @TestRangeOK2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void TestRangeOK2(void) {
  int arr[10];
  struct S s;
  s.start = arr;
  s.iter = arr;
  s.end = arr;
}

// CHECK-LABEL: define dso_local void @TestRangeOK3(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void TestRangeOK3(void) {
  int arr[10];
  struct S s;
  s.start = arr;
  s.iter = arr + 10;
  s.end = arr + 10;
}

// CHECK-LABEL: define dso_local void @TestRangeOK4(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void TestRangeOK4(void) {
  int arr[10];
  struct S s;
  s.start = arr + 10;
  s.iter = arr + 10;
  s.end = arr + 10;
}

// CHECK-LABEL: define dso_local void @TestIterFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ARR:%.*]] = alloca [10 x i32], align 16
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[ARR]]) #[[ATTR7:[0-9]+]]
// CHECK-NEXT:    [[BOUND_PTR_ARITH8:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i64 40
// CHECK-NEXT:    tail call void @foo() #[[ATTR7]]
// CHECK-NEXT:    [[BOUND_PTR_ARITH58:%.*]] = getelementptr i8, ptr [[ARR]], i64 -4
// CHECK-NEXT:    [[CMP77_NOT:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH58]], [[BOUND_PTR_ARITH8]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP92_NOT:%.*]] = icmp ugt ptr [[ARR]], [[BOUND_PTR_ARITH58]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP77_NOT]], [[CMP92_NOT]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[TRAP:.*]], label %[[CONT93:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR8:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT93]]:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[ARR]]) #[[ATTR7]]
// CHECK-NEXT:    ret void
//
void TestIterFail(void) {
    int arr[10];
    struct S s;
    s.start = arr;
    s.iter = arr + 2;
    s.end = arr + 10;
    foo();
    s.start = s.start;
    s.iter = s.iter - 3; // is prevented since s.iter - 3 < s.start
    s.end = s.end;
}

// XXX: Why this can be optimized when the next case can't?
// CHECK-LABEL: define dso_local void @TestStartFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR5:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR8]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestStartFail(void) {
  int arr[10];
  struct S s;
  s.start = arr - 1;
  s.iter = arr;
  s.end = arr + 1;
}

// CHECK-LABEL: define dso_local void @TestEndFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR6:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ARR:%.*]] = alloca [10 x i32], align 16
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[ARR]]) #[[ATTR7]]
// CHECK-NEXT:    [[UPPER3:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i64 40
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[ARR]], i64 44
// CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH]], [[UPPER3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP25_NOT:%.*]] = icmp ugt ptr [[ARR]], [[BOUND_PTR_ARITH]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP_NOT]], [[CMP25_NOT]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[TRAP:.*]], label %[[CONT48:.*]], {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR8]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT48]]:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[ARR]]) #[[ATTR7]]
// CHECK-NEXT:    ret void
//
void TestEndFail(void) {
  int arr[10];
  struct S s;
  s.start = arr;
  s.iter = arr;
  s.end = arr + 11;
}

// CHECK-LABEL: define dso_local void @TestRangeFail1(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR5]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR8]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestRangeFail1(void) {
  int arr[10];
  struct S s;
  s.start = arr + 1;
  s.iter = arr;
  s.end = arr + 1;
}

// CHECK-LABEL: define dso_local void @TestRangeFail2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR5]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR8]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestRangeFail2(void) {
  int arr[10];
  struct S s;
  s.start = arr + 1;
  s.iter = arr + 2;
  s.end = arr + 1;
}

// CHECK-LABEL: define dso_local void @TestRangeFail3(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR5]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR8]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestRangeFail3(void) {
  int arr[10];
  struct S s;
  s.start = arr - 1;
  s.iter = s.iter;
  s.end = s.end;
}

// CHECK-LABEL: define dso_local void @TestRangeFail4(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR5]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR8]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestRangeFail4(void) {
  int arr[10];
  struct S s;
  s.start = s.start;
  s.iter = s.iter;
  s.end = s.end + 1;
}
