// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 5


// RUN: %clang_cc1 -triple x86_64 -fbounds-safety -emit-llvm -O2 -fbounds-safety-bringup-missing-checks=indirect_count_update %s -o - | FileCheck %s
// RUN: %clang_cc1 -triple x86_64 -fbounds-safety -emit-llvm -O2 -fno-bounds-safety-bringup-missing-checks=indirect_count_update %s -o - | FileCheck --check-prefix WITHOUT %s
#include <ptrcheck.h>

// CHECK-LABEL: define dso_local void @foo(
// CHECK-SAME: ptr noundef writeonly captures(address) [[START:%.*]], ptr noundef writeonly captures(address) [[END:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[END]], i64 -4
// CHECK-NEXT:    [[BOUND_PTR_ARITH3:%.*]] = getelementptr i8, ptr [[START]], i64 4
// CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH]], [[END]], !annotation [[META5:![0-9]+]]
// CHECK-NEXT:    [[CMP22_NOT:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH3]], [[BOUND_PTR_ARITH]], !annotation [[META5]]
// CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP_NOT]], [[CMP22_NOT]], !annotation [[META5]]
// CHECK-NEXT:    [[CMP33_NOT:%.*]] = icmp ugt ptr [[START]], [[BOUND_PTR_ARITH3]], !annotation [[META5]]
// CHECK-NEXT:    [[OR_COND41:%.*]] = or i1 [[CMP33_NOT]], [[OR_COND]], !annotation [[META5]]
// CHECK-NEXT:    br i1 [[OR_COND41]], label %[[TRAP:.*]], label %[[CONT:.*]], {{!prof ![0-9]+}}, !annotation [[META5]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR2:[0-9]+]], !annotation [[META5]]
// CHECK-NEXT:    unreachable, !annotation [[META5]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    store i32 0, ptr [[END]], align 4, !tbaa [[TBAA1:![0-9]+]]
// CHECK-NEXT:    store i32 0, ptr [[START]], align 4, !tbaa [[TBAA1]]
// CHECK-NEXT:    ret void
//
// WITHOUT-LABEL: define dso_local void @foo(
// WITHOUT-SAME: ptr noundef writeonly captures(none) initializes((0, 4)) [[START:%.*]], ptr noundef writeonly captures(none) initializes((0, 4)) [[END:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// WITHOUT-NEXT:  [[ENTRY:.*:]]
// WITHOUT-NEXT:    store i32 0, ptr [[END]], align 4, !tbaa [[TBAA1:![0-9]+]]
// WITHOUT-NEXT:    store i32 0, ptr [[START]], align 4, !tbaa [[TBAA1]]
// WITHOUT-NEXT:    ret void
//
void foo(int *__ended_by(end) start, int * end) {
    *end-- = 0;
	*start++ = 0;
}

// CHECK-LABEL: define dso_local void @bar(
// CHECK-SAME: ptr noundef writeonly captures(address) [[START:%.*]], ptr noundef writeonly captures(address) [[END:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[START]], i64 4
// CHECK-NEXT:    [[BOUND_PTR_ARITH3:%.*]] = getelementptr i8, ptr [[END]], i64 -4
// CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH3]], [[END]], !annotation [[META5]]
// CHECK-NEXT:    [[CMP22_NOT:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH]], [[BOUND_PTR_ARITH3]], !annotation [[META5]]
// CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP_NOT]], [[CMP22_NOT]], !annotation [[META5]]
// CHECK-NEXT:    [[CMP33_NOT:%.*]] = icmp ugt ptr [[START]], [[BOUND_PTR_ARITH]], !annotation [[META5]]
// CHECK-NEXT:    [[OR_COND52:%.*]] = or i1 [[CMP33_NOT]], [[OR_COND]], !annotation [[META5]]
// CHECK-NEXT:    br i1 [[OR_COND52]], label %[[TRAP:.*]], label %[[CONT:.*]], {{!prof ![0-9]+}}, !annotation [[META5]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR2]], !annotation [[META5]]
// CHECK-NEXT:    unreachable, !annotation [[META5]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    store i32 0, ptr [[BOUND_PTR_ARITH]], align 4, !tbaa [[TBAA1]]
// CHECK-NEXT:    store i32 0, ptr [[BOUND_PTR_ARITH3]], align 4, !tbaa [[TBAA1]]
// CHECK-NEXT:    ret void
//
// WITHOUT-LABEL: define dso_local void @bar(
// WITHOUT-SAME: ptr noundef writeonly captures(none) initializes((4, 8)) [[START:%.*]], ptr noundef writeonly captures(none) initializes((-4, 0)) [[END:%.*]]) local_unnamed_addr #[[ATTR0]] {
// WITHOUT-NEXT:  [[ENTRY:.*:]]
// WITHOUT-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[START]], i64 4
// WITHOUT-NEXT:    store i32 0, ptr [[BOUND_PTR_ARITH]], align 4, !tbaa [[TBAA1]]
// WITHOUT-NEXT:    [[BOUND_PTR_ARITH3:%.*]] = getelementptr i8, ptr [[END]], i64 -4
// WITHOUT-NEXT:    store i32 0, ptr [[BOUND_PTR_ARITH3]], align 4, !tbaa [[TBAA1]]
// WITHOUT-NEXT:    ret void
//
void bar(int *__ended_by(end) start, int * end) {
	*(start = start+1) = 0;
    *(end = end-1) = 0;
}
//.
// CHECK: [[TBAA1]] = !{[[META2:![0-9]+]], [[META2]], i64 0}
// CHECK: [[META2]] = !{!"int", [[META3:![0-9]+]], i64 0}
// CHECK: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// CHECK: [[META4]] = !{!"Simple C/C++ TBAA"}
// CHECK: [[META5]] = !{!"bounds-safety-generic"}
//.
// WITHOUT: [[TBAA1]] = !{[[META2:![0-9]+]], [[META2]], i64 0}
// WITHOUT: [[META2]] = !{!"int", [[META3:![0-9]+]], i64 0}
// WITHOUT: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// WITHOUT: [[META4]] = !{!"Simple C/C++ TBAA"}
//.
