// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6

// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>
struct T {
  int *__ended_by(iter) start;
  int *__ended_by(end) iter;
  int *end;
};

// CHECK-LABEL: define dso_local void @Test(
// CHECK-SAME: ptr noundef [[T:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[T_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[TMP_TMP3:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[TMP_TMP8:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP11:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP12:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP22:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP30:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP33:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP41:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP48:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP53:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP60:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP69:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP72:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    store ptr [[T]], ptr [[T_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[T_ADDR]], align 8
// CHECK-NEXT:    [[START:%.*]] = getelementptr inbounds nuw [[STRUCT_T:%.*]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[ITER:%.*]] = getelementptr inbounds nuw [[STRUCT_T]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[ITER]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[START]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[START]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[TMP2]], ptr [[TMP4]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TMP1]], ptr [[TMP5]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[TMP6]], align 8
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[TMP7]], align 8
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i32, ptr [[TMP8]], i64 1
// CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP9]], align 8
// CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[TMP10]], align 8
// CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TMP11]], ptr [[TMP12]], align 8
// CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[TMP13]], align 8
// CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[TMP14]], ptr [[TMP15]], align 8
// CHECK-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[T_ADDR]], align 8
// CHECK-NEXT:    [[ITER1:%.*]] = getelementptr inbounds nuw [[STRUCT_T]], ptr [[TMP16]], i32 0, i32 1
// CHECK-NEXT:    [[START4:%.*]] = getelementptr inbounds nuw [[STRUCT_T]], ptr [[TMP16]], i32 0, i32 0
// CHECK-NEXT:    [[TMP17:%.*]] = load ptr, ptr [[START4]], align 8
// CHECK-NEXT:    [[END:%.*]] = getelementptr inbounds nuw [[STRUCT_T]], ptr [[TMP16]], i32 0, i32 2
// CHECK-NEXT:    [[TMP18:%.*]] = load ptr, ptr [[END]], align 8
// CHECK-NEXT:    [[TMP19:%.*]] = load ptr, ptr [[ITER1]], align 8
// CHECK-NEXT:    [[TMP20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP3]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[TMP19]], ptr [[TMP20]], align 8
// CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP3]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TMP18]], ptr [[TMP21]], align 8
// CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP3]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[TMP17]], ptr [[TMP22]], align 8
// CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP3]], i32 0, i32 0
// CHECK-NEXT:    [[TMP24:%.*]] = load ptr, ptr [[TMP23]], align 8
// CHECK-NEXT:    [[BOUND_PTR_ARITH5:%.*]] = getelementptr i32, ptr [[TMP24]], i64 -1
// CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[BOUND_PTR_ARITH5]], ptr [[TMP25]], align 8
// CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP3]], i32 0, i32 1
// CHECK-NEXT:    [[TMP27:%.*]] = load ptr, ptr [[TMP26]], align 8
// CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TMP27]], ptr [[TMP28]], align 8
// CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP3]], i32 0, i32 2
// CHECK-NEXT:    [[TMP30:%.*]] = load ptr, ptr [[TMP29]], align 8
// CHECK-NEXT:    [[TMP31:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[TMP30]], ptr [[TMP31]], align 8
// CHECK-NEXT:    [[TMP32:%.*]] = load ptr, ptr [[T_ADDR]], align 8
// CHECK-NEXT:    [[END6:%.*]] = getelementptr inbounds nuw [[STRUCT_T]], ptr [[TMP32]], i32 0, i32 2
// CHECK-NEXT:    [[ITER9:%.*]] = getelementptr inbounds nuw [[STRUCT_T]], ptr [[TMP32]], i32 0, i32 1
// CHECK-NEXT:    [[TMP33:%.*]] = load ptr, ptr [[ITER9]], align 8
// CHECK-NEXT:    [[TMP34:%.*]] = load ptr, ptr [[END6]], align 8
// CHECK-NEXT:    [[TMP35:%.*]] = load ptr, ptr [[END6]], align 8
// CHECK-NEXT:    [[TMP36:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP8]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[TMP34]], ptr [[TMP36]], align 8
// CHECK-NEXT:    [[TMP37:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP8]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TMP35]], ptr [[TMP37]], align 8
// CHECK-NEXT:    [[TMP38:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP8]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[TMP33]], ptr [[TMP38]], align 8
// CHECK-NEXT:    [[TMP39:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP8]], i32 0, i32 0
// CHECK-NEXT:    [[TMP40:%.*]] = load ptr, ptr [[TMP39]], align 8
// CHECK-NEXT:    [[BOUND_PTR_ARITH10:%.*]] = getelementptr i32, ptr [[TMP40]], i64 -1
// CHECK-NEXT:    [[TMP41:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[BOUND_PTR_ARITH10]], ptr [[TMP41]], align 8
// CHECK-NEXT:    [[TMP42:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP8]], i32 0, i32 1
// CHECK-NEXT:    [[TMP43:%.*]] = load ptr, ptr [[TMP42]], align 8
// CHECK-NEXT:    [[TMP44:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TMP43]], ptr [[TMP44]], align 8
// CHECK-NEXT:    [[TMP45:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP8]], i32 0, i32 2
// CHECK-NEXT:    [[TMP46:%.*]] = load ptr, ptr [[TMP45]], align 8
// CHECK-NEXT:    [[TMP47:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[TMP46]], ptr [[TMP47]], align 8
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP11]], ptr align 8 [[AGG_TEMP7]], i64 24, i1 false), {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 0, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 1, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP12]], ptr align 8 [[AGG_TEMP2]], i64 24, i1 false), {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP12]], i32 0, i32 1, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB14:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR13]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB14]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END:.*]], {{!annotation ![0-9]+}}
// CHECK:       [[LAND_LHS_TRUE]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[AGG_TEMP2]], i64 24, i1 false), {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 0, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR17:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR16]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 1, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB19:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR18]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB21:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR20]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP22]], ptr align 8 [[AGG_TEMP7]], i64 24, i1 false), {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP22]], i32 0, i32 0, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR24:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR23]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR25:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP22]], i32 0, i32 1, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB26:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR25]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR27:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP22]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB28:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR27]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP29:%.*]] = icmp ule ptr [[WIDE_PTR_PTR17]], [[WIDE_PTR_PTR24]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP29]], label %[[LAND_RHS:.*]], label %[[LAND_END]], {{!annotation ![0-9]+}}
// CHECK:       [[LAND_RHS]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP30]], ptr align 8 [[AGG_TEMP2]], i64 24, i1 false), {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR31:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP30]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB32:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR31]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP33]], ptr align 8 [[AGG_TEMP2]], i64 24, i1 false), {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR34:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP33]], i32 0, i32 0, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR35:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR34]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR36:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP33]], i32 0, i32 1, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB37:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR36]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR38:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP33]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB39:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR38]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP40:%.*]] = icmp ule ptr [[WIDE_PTR_LB32]], [[WIDE_PTR_PTR35]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br label %[[LAND_END]], {{!annotation ![0-9]+}}
// CHECK:       [[LAND_END]]:
// CHECK-NEXT:    [[TMP48:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[CMP40]], %[[LAND_RHS]] ], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[TMP48]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP41]], ptr align 8 [[AGG_TEMP2]], i64 24, i1 false), {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR42:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP41]], i32 0, i32 0, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR43:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR42]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR44:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP41]], i32 0, i32 1, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB45:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR44]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR46:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP41]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB47:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR46]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP48]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR49:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP48]], i32 0, i32 1, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB50:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR49]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP51:%.*]] = icmp ule ptr [[WIDE_PTR_PTR43]], [[WIDE_PTR_UB50]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP51]], label %[[LAND_LHS_TRUE52:.*]], label %[[LAND_END80:.*]], {{!annotation ![0-9]+}}
// CHECK:       [[LAND_LHS_TRUE52]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP53]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR54:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP53]], i32 0, i32 0, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR55:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR54]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR56:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP53]], i32 0, i32 1, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB57:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR56]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR58:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP53]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB59:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR58]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP60]], ptr align 8 [[AGG_TEMP2]], i64 24, i1 false), {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR61:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP60]], i32 0, i32 0, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR62:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR61]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR63:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP60]], i32 0, i32 1, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB64:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR63]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR65:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP60]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB66:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR65]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP67:%.*]] = icmp ule ptr [[WIDE_PTR_PTR55]], [[WIDE_PTR_PTR62]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP67]], label %[[LAND_RHS68:.*]], label %[[LAND_END80]], {{!annotation ![0-9]+}}
// CHECK:       [[LAND_RHS68]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP69]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR70:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP69]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB71:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR70]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP72]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR73:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP72]], i32 0, i32 0, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_PTR74:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR73]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR75:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP72]], i32 0, i32 1, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_UB76:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR75]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR77:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP72]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB78:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR77]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP79:%.*]] = icmp ule ptr [[WIDE_PTR_LB71]], [[WIDE_PTR_PTR74]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br label %[[LAND_END80]], {{!annotation ![0-9]+}}
// CHECK:       [[LAND_END80]]:
// CHECK-NEXT:    [[TMP49:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE52]] ], [ false, %[[CONT]] ], [ [[CMP79]], %[[LAND_RHS68]] ], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[TMP49]], label %[[CONT82:.*]], label %[[TRAP81:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP81]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT82]]:
// CHECK-NEXT:    [[TMP50:%.*]] = load ptr, ptr [[START]], align 8
// CHECK-NEXT:    [[INCDEC_PTR:%.*]] = getelementptr inbounds nuw i32, ptr [[TMP50]], i32 1
// CHECK-NEXT:    store ptr [[INCDEC_PTR]], ptr [[START]], align 8
// CHECK-NEXT:    [[TMP51:%.*]] = load ptr, ptr [[ITER1]], align 8
// CHECK-NEXT:    [[INCDEC_PTR83:%.*]] = getelementptr inbounds i32, ptr [[TMP51]], i32 -1
// CHECK-NEXT:    store ptr [[INCDEC_PTR83]], ptr [[ITER1]], align 8
// CHECK-NEXT:    [[TMP52:%.*]] = load ptr, ptr [[END6]], align 8
// CHECK-NEXT:    [[INCDEC_PTR84:%.*]] = getelementptr inbounds i32, ptr [[TMP52]], i32 -1
// CHECK-NEXT:    store ptr [[INCDEC_PTR84]], ptr [[END6]], align 8
// CHECK-NEXT:    ret void
//
void Test(struct T *t) {
  t->start++;
  --t->iter;
  t->end--;
}
