// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>
struct EndedByData {
  int *__ended_by(iter) start;
  int *__ended_by(end) iter;
  int *end;
};

// CHECK-LABEL: @TestIncDecOK(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
void TestIncDecOK() {
  int arr[10];
  struct EndedByData s = { arr, arr + 2, arr + 10 };

  s.start++;
  s.iter--; // start == iter
  s.end--;
}

// CHECK-LABEL: @TestIncDecTrap(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation
// CHECK-NEXT:    unreachable
//
void TestIncDecTrap() {
  int arr[10];
  struct EndedByData s = { arr + 1, arr + 1, arr + 10 };

  s.start = s.start;
  --s.iter; // trap: start > iter
  s.end = s.end;
}

// CHECK-LABEL: @TestIncDecTrap2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation
// CHECK-NEXT:    unreachable
//
void TestIncDecTrap2() {
  int arr[10];
  struct EndedByData s = { arr, arr + 9, arr + 10 };

  s.start++;
  s.iter++;
  s.end--; // trap : iter > end
}
