// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s


#include <ptrcheck.h>

typedef struct {
  int count;
  int elems[__counted_by(count)];
} flex_t;

inline flex_t *return_flex(int *__counted_by(11) buf) {
  return (flex_t *)buf;
}

// CHECK-LABEL: define dso_local void @pointer_assign_good(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[BOUNDSCHECK_NULL47:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_assign_good() {
  int arr[11] = {10};
  flex_t *__single a;
  a = return_flex(arr);
}

// CHECK-LABEL: define dso_local void @pointer_assign_good2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[BOUNDSCHECK_NULL47:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_assign_good2() {
  int arr[11] = {10};
  flex_t *__single a;
  a = (flex_t *)return_flex(arr);
}

// CHECK-LABEL: define dso_local void @pointer_init_good(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[BOUNDSCHECK_NULL47:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_init_good() {
  int arr[11] = {10};
  flex_t *__single a = return_flex(arr);
}

// CHECK-LABEL: define dso_local void @pointer_init_good2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[BOUNDSCHECK_NULL47:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_init_good2() {
  int arr[11] = {10};
  flex_t *__single a = (flex_t *)return_flex(arr);
}

// CHECK-LABEL: define dso_local void @pointer_count_assign_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void pointer_count_assign_trap() {
  int arr[11] = {10};
  flex_t *__single a;
  a = return_flex(arr);
  a->count = 11;
}

// CHECK-LABEL: define dso_local void @pointer_count_init_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void pointer_count_init_trap() {
  int arr[11] = {10};
  flex_t *__single a = return_flex(arr);
  a->count = 11;
}

// CHECK-LABEL: define dso_local void @pointer_count_assign_good(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_count_assign_good() {
  int arr[11] = {10};
  flex_t *__single a;
  a = return_flex(arr);
  a->count = 9;
}

// CHECK-LABEL: define dso_local void @pointer_count_init_good(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_count_init_good() {
  int arr[11] = {10};
  flex_t *__single a = return_flex(arr);
  a->count = 9;
}

// CHECK-LABEL: define dso_local void @elem_access_good(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[CONT69:.*:]]
// CHECK-NEXT:    ret void
//
void elem_access_good() {
  int arr[11] = {10};
  flex_t *__single a;
  a = return_flex(arr);
  a->elems[9] = 0;
}

// CHECK-LABEL: define dso_local void @elem_access_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-NEXT:  [[BOUNDSCHECK_NULL47:.*:]]
// CHECK-NEXT:    [[ARR:%.*]] = alloca [11 x i32], align 4
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[ARR]]) #[[ATTR6:[0-9]+]]
// CHECK-NEXT:    [[ADD_PTR_I:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i64 44
// CHECK-NEXT:    [[AGG_TEMP_SROA_12_0_SROA_GEP87:%.*]] = getelementptr i8, ptr [[ARR]], i64 48
// CHECK-NEXT:    [[ADD_PTR56:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i64 44
// CHECK-NEXT:    [[TMP0:%.*]] = icmp ule ptr [[AGG_TEMP_SROA_12_0_SROA_GEP87]], [[ADD_PTR56]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[ADD_PTR_I]], [[AGG_TEMP_SROA_12_0_SROA_GEP87]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND75:%.*]] = and i1 [[TMP1]], [[TMP0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND75]], label %[[CONT69:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT69]]:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[ARR]]) #[[ATTR6]]
// CHECK-NEXT:    ret void
//
void elem_access_trap() {
  int arr[11] = {10};
  flex_t *__single a;
  a = return_flex(arr);
  a->elems[10] = 0;
}
