// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 5


// RUN: %clang_cc1 -O2  -fbounds-safety -triple arm64e-apple-iphoneos -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2  -fbounds-safety -triple arm64e-apple-iphoneos -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

struct Simple {
    int len;
    int fam[__counted_by(len)];
};

// rdar://132731845 the flexible arrays are not bounds checked

// CHECK-LABEL: define dso_local void @simple_no_flexbase_update(
// CHECK-SAME: ptr noundef readonly captures(none) dead_on_return [[P:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 16
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_P_SROA_IDX]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 4
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[AGG_TEMP_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[AGG_TEMP_SROA_3_0_COPYLOAD]], [[AGG_TEMP_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[TMP1]], i1 [[TMP2]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[CONT1:.*]], label %[[TRAP:.*]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT1]]:
// CHECK-NEXT:    store i32 11, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], align 4, !tbaa {{![0-9]+}}
// CHECK-NEXT:    ret void
//
void simple_no_flexbase_update(struct Simple * __bidi_indexable p) {
    p->len = 11;
}

// CHECK-LABEL: define dso_local void @simple_flexbase_update(
// CHECK-SAME: ptr noundef readonly captures(none) dead_on_return [[P:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[P2_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[P2_SROA_4_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
// CHECK-NEXT:    [[P2_SROA_4_0_COPYLOAD:%.*]] = load ptr, ptr [[P2_SROA_4_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[P2_SROA_5_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 16
// CHECK-NEXT:    [[P2_SROA_5_0_COPYLOAD:%.*]] = load ptr, ptr [[P2_SROA_5_0_P_SROA_IDX]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[P2_SROA_0_0_COPYLOAD]], i64 4
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[P2_SROA_4_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[P2_SROA_5_0_COPYLOAD]], [[P2_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[TMP1]], i1 [[TMP2]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[CONT1:.*]], label %[[TRAP:.*]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT1]]:
// CHECK-NEXT:    store i32 11, ptr [[P2_SROA_0_0_COPYLOAD]], align 4, !tbaa {{![0-9]+}}
// CHECK-NEXT:    ret void
//
void simple_flexbase_update(struct Simple * __bidi_indexable p) {
    struct Simple * __bidi_indexable p2 = p;
    p2->len = 11;
}

// CHECK-LABEL: define dso_local void @simple_flexbase_self_assign(
// CHECK-SAME: ptr noundef readonly captures(none) dead_on_return [[P:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 16
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_P_SROA_IDX]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 4
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[AGG_TEMP_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[AGG_TEMP_SROA_3_0_COPYLOAD]], [[AGG_TEMP_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[TMP1]], i1 [[TMP2]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[CONT1:.*]], label %[[TRAP:.*]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT1]]:
// CHECK-NEXT:    store i32 11, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], align 4, !tbaa {{![0-9]+}}
// CHECK-NEXT:    ret void
//
void simple_flexbase_self_assign(struct Simple * __bidi_indexable p) {
    p = p;
    p->len = 11;
}

struct Shared {
    int len;
    int * __counted_by(len) ptr;
    int fam[__counted_by(len)];
};
int * __counted_by(len) baz(int len);

// CHECK-LABEL: define dso_local void @shared_no_flexbase_update(
// CHECK-SAME: ptr noundef readonly captures(none) dead_on_return [[P:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @baz(i32 noundef 11) #[[ATTR6:[0-9]+]]
// CHECK-NEXT:    [[AGG_TEMP29_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP29_SROA_2_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
// CHECK-NEXT:    [[AGG_TEMP29_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP29_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP29_SROA_3_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 16
// CHECK-NEXT:    [[AGG_TEMP29_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP29_SROA_3_0_P_SROA_IDX]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[AGG_TEMP29_SROA_0_0_COPYLOAD]], i64 16
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[AGG_TEMP29_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[AGG_TEMP29_SROA_3_0_COPYLOAD]], [[AGG_TEMP29_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[TMP1]], i1 [[TMP2]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[CONT37:.*]], label %[[TRAP:.*]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT37]]:
// CHECK-NEXT:    store i32 11, ptr [[AGG_TEMP29_SROA_0_0_COPYLOAD]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[AGG_TEMP45_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP45_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP29_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[AGG_TEMP45_SROA_0_0_COPYLOAD]], i64 16
// CHECK-NEXT:    [[TMP4:%.*]] = icmp ule ptr [[TMP3]], [[AGG_TEMP45_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP5:%.*]] = icmp ule ptr [[AGG_TEMP29_SROA_3_0_COPYLOAD]], [[AGG_TEMP45_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND54:%.*]] = select i1 [[TMP4]], i1 [[TMP5]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND54]], label %[[CONT53:.*]], label %[[TRAP]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[CONT53]]:
// CHECK-NEXT:    [[PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_TEMP45_SROA_0_0_COPYLOAD]], i64 8
// CHECK-NEXT:    store ptr [[CALL]], ptr [[PTR]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    ret void
//
void shared_no_flexbase_update(struct Shared * __bidi_indexable p) {
    int * p2 = baz(11);
    p->len = 11;
    p->ptr = p2;
}

// CHECK-LABEL: define dso_local void @shared_no_flexbase_update_reverse(
// CHECK-SAME: ptr noundef readonly captures(none) dead_on_return [[P:%.*]]) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @baz(i32 noundef 11) #[[ATTR6]]
// CHECK-NEXT:    [[AGG_TEMP36_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP36_SROA_2_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
// CHECK-NEXT:    [[AGG_TEMP36_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP36_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP36_SROA_3_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 16
// CHECK-NEXT:    [[AGG_TEMP36_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP36_SROA_3_0_P_SROA_IDX]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[AGG_TEMP36_SROA_0_0_COPYLOAD]], i64 16
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[AGG_TEMP36_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[AGG_TEMP36_SROA_3_0_COPYLOAD]], [[AGG_TEMP36_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[TMP1]], i1 [[TMP2]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[CONT44:.*]], label %[[TRAP:.*]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT44]]:
// CHECK-NEXT:    [[PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_TEMP36_SROA_0_0_COPYLOAD]], i64 8
// CHECK-NEXT:    store ptr [[CALL]], ptr [[PTR]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[AGG_TEMP45_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP45_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP36_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[AGG_TEMP45_SROA_0_0_COPYLOAD]], i64 16
// CHECK-NEXT:    [[TMP4:%.*]] = icmp ule ptr [[TMP3]], [[AGG_TEMP45_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP5:%.*]] = icmp ule ptr [[AGG_TEMP36_SROA_3_0_COPYLOAD]], [[AGG_TEMP45_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND54:%.*]] = select i1 [[TMP4]], i1 [[TMP5]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND54]], label %[[CONT53:.*]], label %[[TRAP]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[CONT53]]:
// CHECK-NEXT:    store i32 11, ptr [[AGG_TEMP45_SROA_0_0_COPYLOAD]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    ret void
//
void shared_no_flexbase_update_reverse(struct Shared * __bidi_indexable p) {
    p->ptr = baz(11);
    p->len = 11;
}

// CHECK-LABEL: define dso_local void @shared_flexbase_update(
// CHECK-SAME: ptr noundef readonly captures(none) dead_on_return [[P:%.*]]) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @baz(i32 noundef 11) #[[ATTR6]]
// CHECK-NEXT:    [[P2_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[P2_SROA_5_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
// CHECK-NEXT:    [[P2_SROA_5_0_COPYLOAD:%.*]] = load ptr, ptr [[P2_SROA_5_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[P2_SROA_7_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 16
// CHECK-NEXT:    [[P2_SROA_7_0_COPYLOAD:%.*]] = load ptr, ptr [[P2_SROA_7_0_P_SROA_IDX]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[P2_SROA_0_0_COPYLOAD]], i64 16
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[P2_SROA_5_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[P2_SROA_7_0_COPYLOAD]], [[P2_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[TMP1]], i1 [[TMP2]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[CONT44:.*]], label %[[TRAP:.*]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT44]]:
// CHECK-NEXT:    [[PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[P2_SROA_0_0_COPYLOAD]], i64 8
// CHECK-NEXT:    store ptr [[CALL]], ptr [[PTR]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    store i32 11, ptr [[P2_SROA_0_0_COPYLOAD]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    ret void
//
void shared_flexbase_update(struct Shared * __bidi_indexable p) {
    int * p3 = baz(11);
    struct Shared * __bidi_indexable p2 = p;
    p2->ptr = p3;
    p2->len = 11;
}

// CHECK-LABEL: define dso_local void @shared_flexbase_update_reverse(
// CHECK-SAME: ptr noundef readonly captures(none) dead_on_return [[P:%.*]]) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @baz(i32 noundef 11) #[[ATTR6]]
// CHECK-NEXT:    [[P2_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[P2_SROA_5_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
// CHECK-NEXT:    [[P2_SROA_5_0_COPYLOAD:%.*]] = load ptr, ptr [[P2_SROA_5_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[P2_SROA_7_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 16
// CHECK-NEXT:    [[P2_SROA_7_0_COPYLOAD:%.*]] = load ptr, ptr [[P2_SROA_7_0_P_SROA_IDX]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[P2_SROA_0_0_COPYLOAD]], i64 16
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[P2_SROA_5_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[P2_SROA_7_0_COPYLOAD]], [[P2_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[TMP1]], i1 [[TMP2]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[CONT37:.*]], label %[[TRAP:.*]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT37]]:
// CHECK-NEXT:    store i32 11, ptr [[P2_SROA_0_0_COPYLOAD]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[P2_SROA_0_0_COPYLOAD]], i64 8
// CHECK-NEXT:    store ptr [[CALL]], ptr [[PTR]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    ret void
//
void shared_flexbase_update_reverse(struct Shared * __bidi_indexable p) {
    int * p3 = baz(11);
    struct Shared * __bidi_indexable p2 = p;
    p2->len = 11;
    p2->ptr = p3;
}

// CHECK-LABEL: define dso_local void @shared_flexbase_self_assign(
// CHECK-SAME: ptr noundef readonly captures(none) dead_on_return [[P:%.*]]) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @baz(i32 noundef 11) #[[ATTR6]]
// CHECK-NEXT:    [[AGG_TEMP36_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP36_SROA_2_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
// CHECK-NEXT:    [[AGG_TEMP36_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP36_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP36_SROA_3_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 16
// CHECK-NEXT:    [[AGG_TEMP36_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP36_SROA_3_0_P_SROA_IDX]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[AGG_TEMP36_SROA_0_0_COPYLOAD]], i64 16
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[AGG_TEMP36_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[AGG_TEMP36_SROA_3_0_COPYLOAD]], [[AGG_TEMP36_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[TMP1]], i1 [[TMP2]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[CONT44:.*]], label %[[TRAP:.*]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT44]]:
// CHECK-NEXT:    [[PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_TEMP36_SROA_0_0_COPYLOAD]], i64 8
// CHECK-NEXT:    store ptr [[CALL]], ptr [[PTR]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[AGG_TEMP45_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP45_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP36_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[AGG_TEMP45_SROA_0_0_COPYLOAD]], i64 16
// CHECK-NEXT:    [[TMP4:%.*]] = icmp ule ptr [[TMP3]], [[AGG_TEMP45_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP5:%.*]] = icmp ule ptr [[AGG_TEMP36_SROA_3_0_COPYLOAD]], [[AGG_TEMP45_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND54:%.*]] = select i1 [[TMP4]], i1 [[TMP5]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND54]], label %[[CONT53:.*]], label %[[TRAP]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[CONT53]]:
// CHECK-NEXT:    store i32 11, ptr [[AGG_TEMP45_SROA_0_0_COPYLOAD]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    ret void
//
void shared_flexbase_self_assign(struct Shared * __bidi_indexable p) {
    int * p2 = baz(11);
    p = p;
    p->ptr = p2;
    p->len = 11;
}

// CHECK-LABEL: define dso_local void @shared_flexbase_self_assign_reverse(
// CHECK-SAME: ptr noundef readonly captures(none) dead_on_return [[P:%.*]]) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @baz(i32 noundef 11) #[[ATTR6]]
// CHECK-NEXT:    [[AGG_TEMP29_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP29_SROA_2_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
// CHECK-NEXT:    [[AGG_TEMP29_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP29_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP29_SROA_3_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 16
// CHECK-NEXT:    [[AGG_TEMP29_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP29_SROA_3_0_P_SROA_IDX]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[AGG_TEMP29_SROA_0_0_COPYLOAD]], i64 16
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[AGG_TEMP29_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[AGG_TEMP29_SROA_3_0_COPYLOAD]], [[AGG_TEMP29_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[TMP1]], i1 [[TMP2]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[CONT37:.*]], label %[[TRAP:.*]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT37]]:
// CHECK-NEXT:    store i32 11, ptr [[AGG_TEMP29_SROA_0_0_COPYLOAD]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[AGG_TEMP45_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP45_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP29_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[AGG_TEMP45_SROA_0_0_COPYLOAD]], i64 16
// CHECK-NEXT:    [[TMP4:%.*]] = icmp ule ptr [[TMP3]], [[AGG_TEMP45_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP5:%.*]] = icmp ule ptr [[AGG_TEMP29_SROA_3_0_COPYLOAD]], [[AGG_TEMP45_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND54:%.*]] = select i1 [[TMP4]], i1 [[TMP5]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND54]], label %[[CONT53:.*]], label %[[TRAP]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[CONT53]]:
// CHECK-NEXT:    [[PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_TEMP45_SROA_0_0_COPYLOAD]], i64 8
// CHECK-NEXT:    store ptr [[CALL]], ptr [[PTR]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    ret void
//
void shared_flexbase_self_assign_reverse(struct Shared * __bidi_indexable p) {
    int * p2 = baz(11);
    p = p;
    p->len = 11;
    p->ptr = p2;
}

// CHECK-LABEL: define dso_local void @shared_flexbase_self_assign_fr(
// CHECK-SAME: ptr noundef readonly captures(none) dead_on_return [[P:%.*]]) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AGG_TEMP1_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP1_SROA_2_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
// CHECK-NEXT:    [[AGG_TEMP1_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP1_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP1_SROA_3_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 16
// CHECK-NEXT:    [[AGG_TEMP1_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP1_SROA_3_0_P_SROA_IDX]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[AGG_TEMP1_SROA_0_0_COPYLOAD]], i64 16
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[AGG_TEMP1_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[AGG_TEMP1_SROA_3_0_COPYLOAD]], [[AGG_TEMP1_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[TMP1]], i1 [[TMP2]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[CONT11:.*]], label %[[TRAP:.*]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT11]]:
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[AGG_TEMP1_SROA_0_0_COPYLOAD]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[CMP43:%.*]] = icmp sgt i32 [[TMP3]], 10, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP43]], label %[[CONT72:.*]], label %[[TRAP]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[CONT72]]:
// CHECK-NEXT:    store i32 11, ptr [[AGG_TEMP1_SROA_0_0_COPYLOAD]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    ret void
//
void shared_flexbase_self_assign_fr(struct Shared * __bidi_indexable p) {
    p = p;
    p->ptr = p->ptr;
    p->len = 11;
}

// CHECK-LABEL: define dso_local void @shared_flexbase_self_assign_fr_reverse(
// CHECK-SAME: ptr noundef readonly captures(none) dead_on_return [[P:%.*]]) local_unnamed_addr #[[ATTR4]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AGG_TEMP1_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP1_SROA_2_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
// CHECK-NEXT:    [[AGG_TEMP1_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP1_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP1_SROA_3_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 16
// CHECK-NEXT:    [[AGG_TEMP1_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP1_SROA_3_0_P_SROA_IDX]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[AGG_TEMP1_SROA_0_0_COPYLOAD]], i64 16
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[AGG_TEMP1_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[AGG_TEMP1_SROA_3_0_COPYLOAD]], [[AGG_TEMP1_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[TMP1]], i1 [[TMP2]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[CONT11:.*]], label %[[TRAP:.*]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT11]]:
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[AGG_TEMP1_SROA_0_0_COPYLOAD]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_TEMP1_SROA_0_0_COPYLOAD]], i64 8
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[PTR]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[CMP43:%.*]] = icmp sgt i32 [[TMP3]], 10, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP43]], label %[[CONT55:.*]], label %[[TRAP]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[CONT55]]:
// CHECK-NEXT:    store i32 11, ptr [[AGG_TEMP1_SROA_0_0_COPYLOAD]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[AGG_TEMP64_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP64_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP1_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[AGG_TEMP64_SROA_0_0_COPYLOAD]], i64 16
// CHECK-NEXT:    [[TMP6:%.*]] = icmp ule ptr [[TMP5]], [[AGG_TEMP64_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP7:%.*]] = icmp ule ptr [[AGG_TEMP1_SROA_3_0_COPYLOAD]], [[AGG_TEMP64_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND76:%.*]] = select i1 [[TMP6]], i1 [[TMP7]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND76]], label %[[CONT72:.*]], label %[[TRAP]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[CONT72]]:
// CHECK-NEXT:    [[PTR73:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_TEMP64_SROA_0_0_COPYLOAD]], i64 8
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[PTR73]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    ret void
//
void shared_flexbase_self_assign_fr_reverse(struct Shared * __bidi_indexable p) {
    p = p;
    p->len = 11;
    p->ptr = p->ptr;
}

struct Double {
    int len;
    int len2;
    int fam[__counted_by(len + len2)];
};

// CHECK-LABEL: define dso_local void @double_no_flexbase_update_once(
// CHECK-SAME: ptr noundef readonly captures(none) dead_on_return [[P:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 16
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_P_SROA_IDX]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 8
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[AGG_TEMP_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[AGG_TEMP_SROA_3_0_COPYLOAD]], [[AGG_TEMP_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[TMP1]], i1 [[TMP2]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[CONT1:.*]], label %[[TRAP:.*]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT1]]:
// CHECK-NEXT:    store i32 11, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], align 4, !tbaa {{![0-9]+}}
// CHECK-NEXT:    ret void
//
void double_no_flexbase_update_once(struct Double * __bidi_indexable p) {
    p->len = 11;
}

// CHECK-LABEL: define dso_local void @double_no_flexbase_update_both(
// CHECK-SAME: ptr noundef readonly captures(none) dead_on_return [[P:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_P_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 16
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_P_SROA_IDX]], align 8, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 8
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[AGG_TEMP_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[AGG_TEMP_SROA_3_0_COPYLOAD]], [[AGG_TEMP_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[TMP1]], i1 [[TMP2]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[CONT1:.*]], label %[[TRAP:.*]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation {{![0-9]+}}
// CHECK-NEXT:    unreachable, !annotation {{![0-9]+}}
// CHECK:       [[CONT1]]:
// CHECK-NEXT:    store i32 11, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], align 4, !tbaa {{![0-9]+}}
// CHECK-NEXT:    [[AGG_TEMP2_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[AGG_TEMP2_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_P_SROA_IDX]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[AGG_TEMP2_SROA_0_0_COPYLOAD]], i64 8
// CHECK-NEXT:    [[TMP4:%.*]] = icmp ule ptr [[TMP3]], [[AGG_TEMP2_SROA_2_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[TMP5:%.*]] = icmp ule ptr [[AGG_TEMP_SROA_3_0_COPYLOAD]], [[AGG_TEMP2_SROA_0_0_COPYLOAD]], !annotation {{![0-9]+}}
// CHECK-NEXT:    [[OR_COND11:%.*]] = select i1 [[TMP4]], i1 [[TMP5]], i1 false, !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND11]], label %[[CONT10:.*]], label %[[TRAP]], !prof {{![0-9]+}}, !annotation {{![0-9]+}}
// CHECK:       [[CONT10]]:
// CHECK-NEXT:    [[LEN2:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_TEMP2_SROA_0_0_COPYLOAD]], i64 4
// CHECK-NEXT:    store i32 11, ptr [[LEN2]], align 4, !tbaa {{![0-9]+}}
// CHECK-NEXT:    ret void
//
void double_no_flexbase_update_both(struct Double * __bidi_indexable p) {
    p->len = 11;
    p->len2 = 11;
}
