// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s


#include <ptrcheck.h>

typedef struct {
  int count;
  int elems[__counted_by(count)];
} flex_t;


// CHECK-LABEL: define dso_local void @test_lvalue_base_count_fail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[DOTB:%.*]] = load i1, ptr @test_lvalue_base_count_fail.g_flex.0, align 4
// CHECK-NEXT:    br i1 [[DOTB]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR11:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    store i1 true, ptr @test_lvalue_base_count_fail.g_flex.0, align 4
// CHECK-NEXT:    ret void
//
void test_lvalue_base_count_fail() {
  static flex_t g_flex = {4, {1, 2, 3, 4}};
  g_flex.count = 5;
}

// CHECK-LABEL: define dso_local void @test_lvalue_base_count_may_fail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr @test_lvalue_base_count_may_fail.g_flex.0, align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP1:%.*]] = icmp sgt i32 [[TMP0]], 0, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP1]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR11]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    [[DEC:%.*]] = add nsw i32 [[TMP0]], -1
// CHECK-NEXT:    store i32 [[DEC]], ptr @test_lvalue_base_count_may_fail.g_flex.0, align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    ret void
//
void test_lvalue_base_count_may_fail() {
  static flex_t g_flex = {4, {1, 2, 3, 4}};
  g_flex.count--;
}


// CHECK-LABEL: define dso_local void @test_under_base_fail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR11]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void test_under_base_fail() {
  char arr[20];
  char *oob_ptr = arr - 1;
  flex_t *__single flex = (flex_t *)oob_ptr;
}

// CHECK-LABEL: define dso_local void @test_under_base_ok(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR5:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void test_under_base_ok() {
  char arr[20];
  char *oob_ptr = arr - 1;
  flex_t *flex = (flex_t *)oob_ptr;
}


// CHECK-LABEL: define dso_local void @test_under_base_fail2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR6:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ARR:%.*]] = alloca [20 x i8], align 1
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[ARR]]) #[[ATTR12:[0-9]+]]
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[ARR]], i64 -1
// CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ugt ptr [[ARR]], [[BOUND_PTR_ARITH]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[DOTNOT]], label %[[TRAP:.*]], label %[[CONT8:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR11]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT8]]:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[ARR]]) #[[ATTR12]]
// CHECK-NEXT:    ret void
//
void test_under_base_fail2() {
  char arr[20];
  char *oob_ptr = arr - 1;
  flex_t *flex = (flex_t *)oob_ptr;
  int a = flex->count;
}


// CHECK-LABEL: define dso_local void @test_over_base_fail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR7:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR11]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void test_over_base_fail() {
  char arr[20];
  char *oob_ptr = arr + 20;
  flex_t *__single flex = (flex_t *)oob_ptr;
}

// CHECK-LABEL: define dso_local void @test_over_base_ok(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR5]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void test_over_base_ok() {
  char arr[20];
  char *oob_ptr = arr + 20;
  flex_t *flex = (flex_t *)oob_ptr;
}

// CHECK-LABEL: define dso_local void @test_over_base_fail2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR6]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ARR:%.*]] = alloca [20 x i8], align 1
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[ARR]]) #[[ATTR12]]
// CHECK-NEXT:    [[UPPER:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i64 20
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[ARR]], i64 24
// CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ugt ptr [[TMP0]], [[UPPER]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[DOTNOT]], label %[[TRAP:.*]], label %[[CONT8:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR11]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT8]]:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[ARR]]) #[[ATTR12]]
// CHECK-NEXT:    ret void
//
void test_over_base_fail2() {
  char arr[20];
  char *oob_ptr = arr + 20;
  flex_t *flex = (flex_t *)oob_ptr;
  int a = flex->count;
}

// CHECK-LABEL: define dso_local void @test_small_base_fail(
// CHECK-SAME: ptr noundef readnone captures(none) [[FLEX:%.*]]) local_unnamed_addr #[[ATTR7]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR11]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void test_small_base_fail(flex_t *flex) {
  char arr[3];
  flex = (flex_t *)arr;
}

// CHECK-LABEL: define dso_local void @test_small_base_ok(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR5]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void test_small_base_ok() {
  char arr[3];
  flex_t *flex = (flex_t *)arr;
}

// CHECK-LABEL: define dso_local void @test_small_base_fail2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR7]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR11]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void test_small_base_fail2() {
  char arr[3];
  flex_t *flex = (flex_t *)arr;
  (void)(*flex);
}

// CHECK-LABEL: define dso_local void @test_count_from_buf_ok(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR5]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void test_count_from_buf_ok() {
  char arr[20] = {4, 0};
  flex_t *__single flex = (flex_t *)arr;
}

// CHECK-LABEL: define dso_local void @test_count_from_buf_ok2(
// CHECK-SAME: ptr noundef readnone captures(none) [[FLEX:%.*]]) local_unnamed_addr #[[ATTR5]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void test_count_from_buf_ok2(flex_t *flex) {
  char arr[20] = {4, 0};
  flex = (flex_t *)arr;
}

// CHECK-LABEL: define dso_local void @test_count_from_buf_fail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR7]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR11]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void test_count_from_buf_fail() {
  char arr[20] = {5, 0};
  flex_t *__single flex = (flex_t *)arr;
}

// CHECK-LABEL: define dso_local void @test_count_from_buf_fail2(
// CHECK-SAME: ptr noundef readnone captures(none) [[FLEX:%.*]]) local_unnamed_addr #[[ATTR7]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR11]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void test_count_from_buf_fail2(flex_t *flex) {
  char arr[20] = {5, 0};
  flex = (flex_t *)arr;
}

// CHECK-LABEL: define dso_local void @test_base_count_ok(
// CHECK-SAME: ptr noundef readnone captures(none) [[FLEX:%.*]]) local_unnamed_addr #[[ATTR5]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void test_base_count_ok(flex_t *__single flex) {
  char arr[20];
  flex = (flex_t *)arr;
  flex->count = 4;
}

// CHECK-LABEL: define dso_local void @test_base_count_fail(
// CHECK-SAME: ptr noundef readnone captures(none) [[FLEX:%.*]]) local_unnamed_addr #[[ATTR7]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR11]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void test_base_count_fail(flex_t *__single flex) {
  char arr[20];
  flex = (flex_t *)arr;
  flex->count = 5;
}

// CHECK-LABEL: define dso_local void @test_base_fam_access(
// CHECK-SAME: ptr noundef readnone captures(none) [[FLEX:%.*]]) local_unnamed_addr #[[ATTR5]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void test_base_fam_access(flex_t *__single flex) {
  char arr[20];
  flex = (flex_t *)arr;
  flex->count = 4;

  flex->elems[3] = 0;
}

// CHECK-LABEL: define dso_local void @test_base_fam_access_fail(
// CHECK-SAME: ptr noundef readnone captures(none) [[FLEX:%.*]]) local_unnamed_addr #[[ATTR7]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR11]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void test_base_fam_access_fail(flex_t *__single flex) {
  char arr[20];
  flex = (flex_t *)arr;
  flex->count = 4;

  flex->elems[4] = 0;
}

// CHECK-LABEL: define dso_local void @test_unsafe_base_fam_access(
// CHECK-SAME: ptr noundef readnone captures(none) [[FLEX:%.*]]) local_unnamed_addr #[[ATTR5]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void test_unsafe_base_fam_access(flex_t *__unsafe_indexable flex) {
  char arr[20];
  flex = (flex_t *)arr;
  flex->count = 4;

  flex->elems[3] = 0;
}

// CHECK-LABEL: define dso_local void @test_unsafe_base_fam_access_fail(
// CHECK-SAME: ptr noundef readnone captures(none) [[FLEX:%.*]]) local_unnamed_addr #[[ATTR7]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR11]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void test_unsafe_base_fam_access_fail(flex_t *__unsafe_indexable flex) {
  char arr[20];
  flex = (flex_t *)arr;
  flex->count = 4;

  flex->elems[4] = 0;
}

// CHECK-LABEL: define dso_local void @test_null_base_fail(
// CHECK-SAME: ptr noundef readnone captures(none) [[FLEX:%.*]]) local_unnamed_addr #[[ATTR8:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    unreachable
//
void test_null_base_fail(flex_t *__single flex) {
  void *p = 0;
  flex = p;
  flex->count = 4;
}

// CHECK-LABEL: define dso_local void @test_null_base_ok(
// CHECK-SAME: ptr noundef readnone captures(none) [[FLEX:%.*]]) local_unnamed_addr #[[ATTR5]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void test_null_base_ok(flex_t *__single flex) {
  flex = 0;
}

// CHECK-LABEL: define dso_local void @test_null_base_fam_access_fail(
// CHECK-SAME: ptr noundef readnone captures(none) [[FLEX:%.*]]) local_unnamed_addr #[[ATTR7]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR11]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void test_null_base_fam_access_fail(flex_t *__single flex) {
  flex = 0;

  flex->elems[4] = 42;
}

typedef struct {
  unsigned dummy;
  flex_t *flex;
} flex_wrapper_t;

// CHECK-LABEL: define dso_local void @test_flex_init_list_ok(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR5]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void test_flex_init_list_ok() {
  char buf[20] = {4, 0};
  flex_t *flex = (flex_t *)buf;
  flex_wrapper_t flex_wrap = {0, flex};
}

// CHECK-LABEL: define dso_local void @test_flex_init_list_fail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR7]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR11]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void test_flex_init_list_fail() {
  char buf[20] = {5, 0};
  flex_t *flex = (flex_t *)buf;
  flex_wrapper_t flex_wrap = {0, flex};
}

void sink(flex_t *__single flex);

// CHECK-LABEL: define dso_local void @test_flex_argument_ok(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR9:[0-9]+]] {
// CHECK-NEXT:  [[BOUNDSCHECK_NULL:.*:]]
// CHECK-NEXT:    [[BUF:%.*]] = alloca [20 x i8], align 1
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[BUF]]) #[[ATTR12]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 1 dereferenceable(20) [[BUF]], ptr noundef nonnull align 1 dereferenceable(20) @__const.test_flex_argument_ok.buf, i64 20, i1 false)
// CHECK-NEXT:    call void @sink(ptr noundef nonnull [[BUF]]) #[[ATTR12]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[BUF]]) #[[ATTR12]]
// CHECK-NEXT:    ret void
//
void test_flex_argument_ok() {
  char buf[20] = {4, 0};
  flex_t *flex = (flex_t *)buf;
  sink(flex);
}

// CHECK-LABEL: define dso_local void @test_flex_argument_fail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR7]] {
// CHECK-NEXT:  [[TRAP:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR11]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void test_flex_argument_fail() {
  char buf[20] = {5, 0};
  flex_t *flex = (flex_t *)buf;
  sink(flex);
}
