// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s


#include <ptrcheck.h>

typedef struct {
  int count;
  int elems[__counted_by(count)];
} flex_t;

// CHECK-LABEL: define dso_local void @pointer_assign_good(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[CONT78:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_assign_good() {
  int arr[11] = {10};
  flex_t *__single a = (flex_t *)arr;
  flex_t *__single b = a;
}

// CHECK-LABEL: define dso_local void @pointer_assign_good2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[CONT78:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_assign_good2() {
  int arr[11] = {10};
  flex_t *__single a = (flex_t *)arr;
  flex_t *__single b = (flex_t *)a;
}

// CHECK-LABEL: define dso_local void @pointer_count_assign_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[TRAP:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void pointer_count_assign_trap() {
  int arr[11] = {10};
  flex_t *__single a = (flex_t *)arr;
  flex_t *__single b = (flex_t *)a;
  b->count = 11;
}

typedef struct {
  int count;
  int elems[__counted_by(count+1)];
} flex1_t;

// CHECK-LABEL: define dso_local void @pointer_assign_bidi_oob_notrap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_assign_bidi_oob_notrap() {
  int arr[11] = {10};
  flex_t *__single a = (flex_t *)arr;
  flex1_t *b = (flex1_t *)a;
}

// CHECK-LABEL: define dso_local void @pointer_assign_bidi_to_single_oob_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[TRAP:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void pointer_assign_bidi_to_single_oob_trap() {
  int arr[11] = {10};
  flex_t *__single a = (flex_t *)arr;
  flex1_t *b = (flex1_t *)a;
  flex1_t *__single c = b;
}

// CHECK-LABEL: define dso_local void @pointer_assign_single_oob_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[TRAP:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void pointer_assign_single_oob_trap() {
  int arr[11] = {10};
  flex_t *__single a = (flex_t *)arr;
  flex1_t *__single b = (flex1_t *)a;
}

// CHECK-LABEL: define dso_local void @pointer_count_assign_single_good(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_count_assign_single_good() {
  int arr[11] = {10};
  flex_t *__single a = (flex_t *)arr;
  flex1_t *__single b = (flex1_t *)a;
  b->count = 9;
}

// CHECK-LABEL: define dso_local void @pointer_assign_single_good(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_assign_single_good() {
  int arr[11] = {9};
  flex1_t *__single a = (flex1_t *)arr;
  flex_t *__single b = (flex_t *)a;
}

// CHECK-LABEL: define dso_local void @pointer_assign_bidi_good(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_assign_bidi_good() {
  int arr[11] = {9};
  flex1_t *__single a = (flex1_t *)arr;
  flex_t *b = (flex_t *)a;
}

// CHECK-LABEL: define dso_local void @pointer_count_assign_single_good2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_count_assign_single_good2() {
  int arr[11] = {9};
  flex1_t *__single a = (flex1_t *)arr;
  flex_t *__single b = (flex_t *)a;
  b->count = 9;
}

// CHECK-LABEL: define dso_local void @pointer_count_assign_single_oob_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[TRAP:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void pointer_count_assign_single_oob_trap() {
  int arr[11] = {9};
  flex1_t *__single a = (flex1_t *)arr;
  flex_t *__single b = (flex_t *)a;
  b->count = 11;
}

// CHECK-LABEL: define dso_local void @pointer_count_assign_single_negative_count_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void pointer_count_assign_single_negative_count_trap() {
  int arr[11] = {9};
  flex1_t *__single a = (flex1_t *)arr;
  flex_t *__single b = (flex_t *)a;
  b->count = -1;
}
