// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

typedef struct {
  int count;
  int elems[__counted_by(count)];
} flex_t;

// CHECK-LABEL: define dso_local noundef ptr @set(
// CHECK-SAME: ptr noundef returned [[FLEX:%.*]], i32 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq ptr [[FLEX]], null, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[DOTNOT]], label %[[BOUNDSCHECK_CONT:.*]], label %[[BOUNDSCHECK_NOTNULL:.*]], {{!annotation ![0-9]+}}
// CHECK:       [[BOUNDSCHECK_NOTNULL]]:
// CHECK-NEXT:    [[ELEMS:%.*]] = getelementptr inbounds nuw i8, ptr [[FLEX]], i64 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[FLEX]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP0]] to i64
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds [4 x i8], ptr [[ELEMS]], i64 [[IDX_EXT]]
// CHECK-NEXT:    br label %[[BOUNDSCHECK_CONT]]
// CHECK:       [[BOUNDSCHECK_CONT]]:
// CHECK-NEXT:    [[AGG_TEMP1_SROA_3_0:%.*]] = phi ptr [ [[ADD_PTR]], %[[BOUNDSCHECK_NOTNULL]] ], [ null, %[[ENTRY]] ]
// CHECK-NEXT:    [[CONV:%.*]] = zext i32 [[SIZE]] to i64
// CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[FLEX]], [[AGG_TEMP1_SROA_3_0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP1_SROA_3_0]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[FLEX]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP67_NOT:%.*]] = icmp ult i64 [[SUB_PTR_SUB]], [[CONV]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP_NOT]], [[CMP67_NOT]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[TRAP:.*]], label %[[CONT:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr align 1 [[FLEX]], i8 0, i64 [[CONV]], i1 false)
// CHECK-NEXT:    [[DOTNOT89:%.*]] = icmp ne ptr [[FLEX]], null, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[DOTNOT90:%.*]] = icmp eq i32 [[SIZE]], 0, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND91:%.*]] = and i1 [[DOTNOT89]], [[DOTNOT90]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND91]], label %[[TRAP]], label %[[BOUNDSCHECK_NULL88:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[BOUNDSCHECK_NULL88]]:
// CHECK-NEXT:    ret ptr [[FLEX]]
//
void *set(flex_t *flex, unsigned size) {
  return __builtin_memset(flex, 0, size);
}

// CHECK-LABEL: define dso_local noundef ptr @cpy(
// CHECK-SAME: ptr noundef returned [[DEST:%.*]], ptr noundef [[SRC:%.*]], i32 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq ptr [[DEST]], null, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[DOTNOT]], label %[[BOUNDSCHECK_CONT:.*]], label %[[BOUNDSCHECK_NOTNULL:.*]], {{!annotation ![0-9]+}}
// CHECK:       [[BOUNDSCHECK_NOTNULL]]:
// CHECK-NEXT:    [[ELEMS:%.*]] = getelementptr inbounds nuw i8, ptr [[DEST]], i64 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[DEST]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP0]] to i64
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds [4 x i8], ptr [[ELEMS]], i64 [[IDX_EXT]]
// CHECK-NEXT:    br label %[[BOUNDSCHECK_CONT]]
// CHECK:       [[BOUNDSCHECK_CONT]]:
// CHECK-NEXT:    [[AGG_TEMP1_SROA_3_0:%.*]] = phi ptr [ [[ADD_PTR]], %[[BOUNDSCHECK_NOTNULL]] ], [ null, %[[ENTRY]] ]
// CHECK-NEXT:    [[DOTNOT188:%.*]] = icmp eq ptr [[SRC]], null, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[DOTNOT188]], label %[[BOUNDSCHECK_CONT11:.*]], label %[[BOUNDSCHECK_NOTNULL4:.*]], {{!annotation ![0-9]+}}
// CHECK:       [[BOUNDSCHECK_NOTNULL4]]:
// CHECK-NEXT:    [[ELEMS5:%.*]] = getelementptr inbounds nuw i8, ptr [[SRC]], i64 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[SRC]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[IDX_EXT8:%.*]] = sext i32 [[TMP1]] to i64
// CHECK-NEXT:    [[ADD_PTR9:%.*]] = getelementptr inbounds [4 x i8], ptr [[ELEMS5]], i64 [[IDX_EXT8]]
// CHECK-NEXT:    br label %[[BOUNDSCHECK_CONT11]]
// CHECK:       [[BOUNDSCHECK_CONT11]]:
// CHECK-NEXT:    [[AGG_TEMP3_SROA_3_0:%.*]] = phi ptr [ [[ADD_PTR9]], %[[BOUNDSCHECK_NOTNULL4]] ], [ null, %[[BOUNDSCHECK_CONT]] ]
// CHECK-NEXT:    [[CONV:%.*]] = zext i32 [[SIZE]] to i64
// CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[SRC]], [[AGG_TEMP3_SROA_3_0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP3_SROA_3_0]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[SRC]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP83_NOT:%.*]] = icmp ult i64 [[SUB_PTR_SUB]], [[CONV]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP_NOT]], [[CMP83_NOT]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP101_NOT:%.*]] = icmp ugt ptr [[DEST]], [[AGG_TEMP1_SROA_3_0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND191:%.*]] = select i1 [[OR_COND]], i1 true, i1 [[CMP101_NOT]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST153:%.*]] = ptrtoint ptr [[AGG_TEMP1_SROA_3_0]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST154:%.*]] = ptrtoint ptr [[DEST]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_SUB155:%.*]] = sub i64 [[SUB_PTR_LHS_CAST153]], [[SUB_PTR_RHS_CAST154]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP156_NOT:%.*]] = icmp ult i64 [[SUB_PTR_SUB155]], [[CONV]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND192:%.*]] = select i1 [[OR_COND191]], i1 true, i1 [[CMP156_NOT]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND192]], label %[[TRAP:.*]], label %[[CONT159:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT159]]:
// CHECK-NEXT:    tail call void @llvm.memcpy.p0.p0.i64(ptr align 1 [[DEST]], ptr align 1 [[SRC]], i64 [[CONV]], i1 false)
// CHECK-NEXT:    [[DOTNOT189:%.*]] = icmp ne ptr [[DEST]], null, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[DOTNOT190:%.*]] = icmp eq i32 [[SIZE]], 0, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND193:%.*]] = and i1 [[DOTNOT189]], [[DOTNOT190]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND193]], label %[[TRAP]], label %[[BOUNDSCHECK_NULL186:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[BOUNDSCHECK_NULL186]]:
// CHECK-NEXT:    ret ptr [[DEST]]
//
void *cpy(flex_t *dest, const flex_t *src, unsigned size) {
  return __builtin_memcpy(dest, src, size);
}

// CHECK-LABEL: define dso_local ptr @pcpy(
// CHECK-SAME: ptr noundef [[DEST:%.*]], ptr noundef [[SRC:%.*]], i32 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq ptr [[DEST]], null, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[DOTNOT]], label %[[BOUNDSCHECK_CONT:.*]], label %[[BOUNDSCHECK_NOTNULL:.*]], {{!annotation ![0-9]+}}
// CHECK:       [[BOUNDSCHECK_NOTNULL]]:
// CHECK-NEXT:    [[ELEMS:%.*]] = getelementptr inbounds nuw i8, ptr [[DEST]], i64 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[DEST]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP0]] to i64
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds [4 x i8], ptr [[ELEMS]], i64 [[IDX_EXT]]
// CHECK-NEXT:    br label %[[BOUNDSCHECK_CONT]]
// CHECK:       [[BOUNDSCHECK_CONT]]:
// CHECK-NEXT:    [[AGG_TEMP1_SROA_3_0:%.*]] = phi ptr [ [[ADD_PTR]], %[[BOUNDSCHECK_NOTNULL]] ], [ null, %[[ENTRY]] ]
// CHECK-NEXT:    [[DOTNOT175:%.*]] = icmp eq ptr [[SRC]], null, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[DOTNOT175]], label %[[BOUNDSCHECK_CONT11:.*]], label %[[BOUNDSCHECK_NOTNULL4:.*]], {{!annotation ![0-9]+}}
// CHECK:       [[BOUNDSCHECK_NOTNULL4]]:
// CHECK-NEXT:    [[ELEMS5:%.*]] = getelementptr inbounds nuw i8, ptr [[SRC]], i64 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[SRC]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[IDX_EXT8:%.*]] = sext i32 [[TMP1]] to i64
// CHECK-NEXT:    [[ADD_PTR9:%.*]] = getelementptr inbounds [4 x i8], ptr [[ELEMS5]], i64 [[IDX_EXT8]]
// CHECK-NEXT:    br label %[[BOUNDSCHECK_CONT11]]
// CHECK:       [[BOUNDSCHECK_CONT11]]:
// CHECK-NEXT:    [[AGG_TEMP3_SROA_3_0:%.*]] = phi ptr [ [[ADD_PTR9]], %[[BOUNDSCHECK_NOTNULL4]] ], [ null, %[[BOUNDSCHECK_CONT]] ]
// CHECK-NEXT:    [[CONV:%.*]] = zext i32 [[SIZE]] to i64
// CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[SRC]], [[AGG_TEMP3_SROA_3_0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP3_SROA_3_0]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[SRC]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP83_NOT:%.*]] = icmp ult i64 [[SUB_PTR_SUB]], [[CONV]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP_NOT]], [[CMP83_NOT]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP101_NOT:%.*]] = icmp ugt ptr [[DEST]], [[AGG_TEMP1_SROA_3_0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND176:%.*]] = select i1 [[OR_COND]], i1 true, i1 [[CMP101_NOT]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST153:%.*]] = ptrtoint ptr [[AGG_TEMP1_SROA_3_0]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST154:%.*]] = ptrtoint ptr [[DEST]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_SUB155:%.*]] = sub i64 [[SUB_PTR_LHS_CAST153]], [[SUB_PTR_RHS_CAST154]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP156_NOT:%.*]] = icmp ult i64 [[SUB_PTR_SUB155]], [[CONV]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND177:%.*]] = select i1 [[OR_COND176]], i1 true, i1 [[CMP156_NOT]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND177]], label %[[TRAP:.*]], label %[[CONT159:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT159]]:
// CHECK-NEXT:    tail call void @llvm.memcpy.p0.p0.i64(ptr align 1 [[DEST]], ptr align 1 [[SRC]], i64 [[CONV]], i1 false)
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw i8, ptr [[DEST]], i64 [[CONV]]
// CHECK-NEXT:    ret ptr [[TMP2]]
//
void *__unsafe_indexable pcpy(flex_t *dest, const flex_t *src, unsigned size) {
  return __builtin_mempcpy(dest, src, size);
}

// CHECK-LABEL: define dso_local noundef ptr @move(
// CHECK-SAME: ptr noundef returned [[DEST:%.*]], ptr noundef [[SRC:%.*]], i32 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq ptr [[DEST]], null, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[DOTNOT]], label %[[BOUNDSCHECK_CONT:.*]], label %[[BOUNDSCHECK_NOTNULL:.*]], {{!annotation ![0-9]+}}
// CHECK:       [[BOUNDSCHECK_NOTNULL]]:
// CHECK-NEXT:    [[ELEMS:%.*]] = getelementptr inbounds nuw i8, ptr [[DEST]], i64 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[DEST]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP0]] to i64
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds [4 x i8], ptr [[ELEMS]], i64 [[IDX_EXT]]
// CHECK-NEXT:    br label %[[BOUNDSCHECK_CONT]]
// CHECK:       [[BOUNDSCHECK_CONT]]:
// CHECK-NEXT:    [[AGG_TEMP1_SROA_3_0:%.*]] = phi ptr [ [[ADD_PTR]], %[[BOUNDSCHECK_NOTNULL]] ], [ null, %[[ENTRY]] ]
// CHECK-NEXT:    [[DOTNOT188:%.*]] = icmp eq ptr [[SRC]], null, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[DOTNOT188]], label %[[BOUNDSCHECK_CONT11:.*]], label %[[BOUNDSCHECK_NOTNULL4:.*]], {{!annotation ![0-9]+}}
// CHECK:       [[BOUNDSCHECK_NOTNULL4]]:
// CHECK-NEXT:    [[ELEMS5:%.*]] = getelementptr inbounds nuw i8, ptr [[SRC]], i64 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[SRC]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[IDX_EXT8:%.*]] = sext i32 [[TMP1]] to i64
// CHECK-NEXT:    [[ADD_PTR9:%.*]] = getelementptr inbounds [4 x i8], ptr [[ELEMS5]], i64 [[IDX_EXT8]]
// CHECK-NEXT:    br label %[[BOUNDSCHECK_CONT11]]
// CHECK:       [[BOUNDSCHECK_CONT11]]:
// CHECK-NEXT:    [[AGG_TEMP3_SROA_3_0:%.*]] = phi ptr [ [[ADD_PTR9]], %[[BOUNDSCHECK_NOTNULL4]] ], [ null, %[[BOUNDSCHECK_CONT]] ]
// CHECK-NEXT:    [[CONV:%.*]] = zext i32 [[SIZE]] to i64
// CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[SRC]], [[AGG_TEMP3_SROA_3_0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP3_SROA_3_0]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[SRC]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP83_NOT:%.*]] = icmp ult i64 [[SUB_PTR_SUB]], [[CONV]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP_NOT]], [[CMP83_NOT]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP101_NOT:%.*]] = icmp ugt ptr [[DEST]], [[AGG_TEMP1_SROA_3_0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND191:%.*]] = select i1 [[OR_COND]], i1 true, i1 [[CMP101_NOT]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST153:%.*]] = ptrtoint ptr [[AGG_TEMP1_SROA_3_0]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST154:%.*]] = ptrtoint ptr [[DEST]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_SUB155:%.*]] = sub i64 [[SUB_PTR_LHS_CAST153]], [[SUB_PTR_RHS_CAST154]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP156_NOT:%.*]] = icmp ult i64 [[SUB_PTR_SUB155]], [[CONV]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND192:%.*]] = select i1 [[OR_COND191]], i1 true, i1 [[CMP156_NOT]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND192]], label %[[TRAP:.*]], label %[[CONT159:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT159]]:
// CHECK-NEXT:    tail call void @llvm.memmove.p0.p0.i64(ptr align 1 [[DEST]], ptr align 1 [[SRC]], i64 [[CONV]], i1 false)
// CHECK-NEXT:    [[DOTNOT189:%.*]] = icmp ne ptr [[DEST]], null, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[DOTNOT190:%.*]] = icmp eq i32 [[SIZE]], 0, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND193:%.*]] = and i1 [[DOTNOT189]], [[DOTNOT190]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND193]], label %[[TRAP]], label %[[BOUNDSCHECK_NULL186:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[BOUNDSCHECK_NULL186]]:
// CHECK-NEXT:    ret ptr [[DEST]]
//
void *move(flex_t *dest, const flex_t *src, unsigned size) {
  return __builtin_memmove(dest, src, size);
}
