// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -fbounds-safety -emit-llvm %s -o - | FileCheck %s


#include <ptrcheck.h>

typedef struct {
  int len;
  int offs;
  int fam[__counted_by(len - offs)];
} S;

// CHECK-LABEL: define dso_local void @good_fit(
// CHECK-SAME: ptr noundef readnone captures(none) [[S:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_fit(S *s) {
  char arr[40] = {0};
  s = (S *)arr;
  s->offs = 2;
  s->len = 10;
}

// CHECK-LABEL: define dso_local void @good_fit2(
// CHECK-SAME: ptr noundef readnone captures(none) [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_fit2(S *s) {
  char arr[40] = {0};
  s = (S *)&arr[1];
  s->offs = 2;
  s->len = 9;
}

// CHECK-LABEL: define dso_local void @good_shrink(
// CHECK-SAME: ptr noundef readnone captures(none) [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_shrink(S *s) {
  char arr[40] = {0};
  s = (S *)arr;
  s->offs = 2;
  s->len = 9;
}

// CHECK-LABEL: define dso_local void @good_zero(
// CHECK-SAME: ptr noundef readnone captures(none) [[S:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_zero(S *s) {
  char arr[40] = {0};
  s = (S *)arr;
  s->offs = 2;
  s->len = 2;
}

// CHECK-LABEL: define dso_local void @trap_access_to_count_zero(
// CHECK-SAME: ptr noundef readnone captures(none) [[S:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void trap_access_to_count_zero(S *s) {
  char arr[40] = {0};
  s = (S *)arr;
  s->offs = 2;
  s->len = 2;
  s->fam[0] = 0;
}

// CHECK-LABEL: define dso_local void @trap_len_too_big(
// CHECK-SAME: ptr noundef readnone captures(none) [[S:%.*]]) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void trap_len_too_big(S *s) {
  char arr[40] = {0};
  s = (S *)arr;
  s->offs = 2;
  s->len = 11;
}

// CHECK-LABEL: define dso_local void @trap_negative_count(
// CHECK-SAME: ptr noundef readnone captures(none) [[S:%.*]]) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void trap_negative_count(S *s) {
  char arr[40] = {0};
  s = (S *)arr;
  s->offs = 10;
  s->len = 2;
}
