// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6

// RUN: %clang_cc1 -O0 -triple arm64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O0 -triple arm64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

#define NULL ((void *__single)0)

// CHECK-LABEL: define dso_local void @test_null_to_bidi(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[IMPL_BIDI_PTR:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[IMPL_BIDI_PTR2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[IMPL_BIDI_PTR]], i8 0, i64 24, i1 false)
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[IMPL_BIDI_PTR]], i32 0, i32 0
// CHECK-NEXT:    store ptr null, ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[IMPL_BIDI_PTR]], i32 0, i32 1
// CHECK-NEXT:    store ptr inttoptr (i64 4 to ptr), ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[IMPL_BIDI_PTR]], i32 0, i32 2
// CHECK-NEXT:    store ptr null, ptr [[TMP2]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[IMPL_BIDI_PTR2]], i8 0, i64 24, i1 false)
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[IMPL_BIDI_PTR2]], i32 0, i32 0
// CHECK-NEXT:    store ptr null, ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[IMPL_BIDI_PTR2]], i32 0, i32 1
// CHECK-NEXT:    store ptr inttoptr (i64 4 to ptr), ptr [[TMP4]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[IMPL_BIDI_PTR2]], i32 0, i32 2
// CHECK-NEXT:    store ptr null, ptr [[TMP5]], align 8
// CHECK-NEXT:    ret void
//
void test_null_to_bidi() {
  int *impl_bidi_ptr = (int *__bidi_indexable)NULL;
  int *impl_bidi_ptr2 = (void *)(char *)NULL;
}
