// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

static struct {
  int _a[10];
  int array[3];
  int _b[10];
} foo;

// CHECK-LABEL: define dso_local { ptr, ptr } @good_add_one(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret { ptr, ptr } { ptr getelementptr inbounds nuw (i8, ptr @foo, i64 44), ptr getelementptr inbounds nuw (i8, ptr @foo, i64 52) }
//
int *__indexable good_add_one(void) {
  int *__indexable p = foo.array;
  int index = 1;
  p += index;
  return p;
}

// CHECK-LABEL: define dso_local { ptr, ptr } @good_sub_neg_one(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret { ptr, ptr } { ptr getelementptr inbounds nuw (i8, ptr @foo, i64 44), ptr getelementptr inbounds nuw (i8, ptr @foo, i64 52) }
//
int *__indexable good_sub_neg_one(void) {
  int *__indexable p = foo.array;
  int index = -1;
  p -= index;
  return p;
}

// CHECK-LABEL: define dso_local { ptr, ptr } @good_oob(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret { ptr, ptr } { ptr getelementptr inbounds nuw (i8, ptr @foo, i64 80), ptr getelementptr inbounds nuw (i8, ptr @foo, i64 52) }
//
int *__indexable good_oob(void) {
  int *__indexable p = foo.array;
  int index = 10;
  p += index;
  return p;
}

// CHECK-LABEL: define dso_local noundef { ptr, ptr } @bad_sub_one(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
int *__indexable bad_sub_one(void) {
  int *__indexable p = foo.array;
  int index = 1;
  p -= index;
  return p;
}

// CHECK-LABEL: define dso_local noundef { ptr, ptr } @bad_add_neg_one(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
int *__indexable bad_add_neg_one(void) {
  int *__indexable p = foo.array;
  int index = -1;
  p += index;
  return p;
}

// CHECK-LABEL: define dso_local noundef { ptr, ptr } @bad_add_one_sub_one(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
int *__indexable bad_add_one_sub_one(void) {
  int *__indexable p = foo.array;
  int index = 1;
  p += index;
  p -= index;
  return p;
}
