// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6


// RUN: %clang_cc1 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s --check-prefix=X86_64
// RUN: %clang_cc1 -triple aarch64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s --check-prefix=AARCH64
// RUN: %clang_cc1 -triple i686 -fbounds-safety -emit-llvm %s -o - | FileCheck %s --check-prefix=I686
// RUN: %clang_cc1 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s --check-prefix=X86_64
// RUN: %clang_cc1 -triple aarch64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s --check-prefix=AARCH64
// RUN: %clang_cc1 -triple i686 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s --check-prefix=I686

#include <ptrcheck.h>

// X86_64-LABEL: define dso_local { ptr, ptr } @bar(
// X86_64-SAME: ptr noundef [[PTRARG_COERCE0:%.*]], ptr noundef [[PTRARG_COERCE1:%.*]]) #[[ATTR0:[0-9]+]] {
// X86_64-NEXT:  [[ENTRY:.*:]]
// X86_64-NEXT:    [[RETVAL:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// X86_64-NEXT:    [[PTRARG:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// X86_64-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[PTRARG]], i32 0, i32 0
// X86_64-NEXT:    store ptr [[PTRARG_COERCE0]], ptr [[TMP0]], align 8
// X86_64-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[PTRARG]], i32 0, i32 1
// X86_64-NEXT:    store ptr [[PTRARG_COERCE1]], ptr [[TMP1]], align 8
// X86_64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[RETVAL]], ptr align 8 [[PTRARG]], i64 16, i1 false)
// X86_64-NEXT:    [[TMP2:%.*]] = load { ptr, ptr }, ptr [[RETVAL]], align 8
// X86_64-NEXT:    ret { ptr, ptr } [[TMP2]]
//
// AARCH64-LABEL: define dso_local [2 x i64] @bar(
// AARCH64-SAME: [2 x i64] noundef [[PTRARG_COERCE:%.*]]) #[[ATTR0:[0-9]+]] {
// AARCH64-NEXT:  [[ENTRY:.*:]]
// AARCH64-NEXT:    [[RETVAL:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// AARCH64-NEXT:    [[PTRARG:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// AARCH64-NEXT:    store [2 x i64] [[PTRARG_COERCE]], ptr [[PTRARG]], align 8
// AARCH64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[RETVAL]], ptr align 8 [[PTRARG]], i64 16, i1 false)
// AARCH64-NEXT:    [[TMP0:%.*]] = load [2 x i64], ptr [[RETVAL]], align 8
// AARCH64-NEXT:    ret [2 x i64] [[TMP0]]
//
// I686-LABEL: define dso_local void @bar(
// I686-SAME: ptr dead_on_unwind noalias writable sret(%"__bounds_safety::wide_ptr.indexable") align 4 [[AGG_RESULT:%.*]], ptr noundef byval(%"__bounds_safety::wide_ptr.indexable") align 4 [[PTRARG:%.*]]) #[[ATTR0:[0-9]+]] {
// I686-NEXT:  [[ENTRY:.*:]]
// I686-NEXT:    [[RESULT_PTR:%.*]] = alloca ptr, align 4
// I686-NEXT:    store ptr [[AGG_RESULT]], ptr [[RESULT_PTR]], align 4
// I686-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[AGG_RESULT]], ptr align 4 [[PTRARG]], i32 8, i1 false)
// I686-NEXT:    ret void
//
int*__indexable bar(int *__indexable ptrArg) {
    return ptrArg;
}

//
//
//




