// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6


// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

static struct {
  int _a[10];
  int array[3];
  int _b[10];
} foo;

// CHECK-LABEL: define dso_local void @good_add_one(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_add_one(void) {
  int *__indexable p = foo.array;
  int index = 1;
  (void)(p + index);
}

// CHECK-LABEL: define dso_local void @good_add_one_assign(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_add_one_assign(void) {
  int *__indexable p = foo.array;
  int index = 1;
  p = p + index;
}

// CHECK-LABEL: define dso_local void @good_add_one_deref(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_add_one_deref(void) {
  int *__indexable p = foo.array;
  int index = 1;
  (void)*(p + index);
}

// CHECK-LABEL: define dso_local void @good_add_neg_one(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_add_neg_one(void) {
  int *__indexable p = foo.array;
  int index = -1;
  (void)(p + index);
}

// CHECK-LABEL: define dso_local void @bad_add_neg_one_assign(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void bad_add_neg_one_assign(void) {
  int *__indexable p = foo.array;
  int index = -1;
  p = p + index;
}

// CHECK-LABEL: define dso_local void @bad_add_neg_one_deref(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void bad_add_neg_one_deref(void) {
  int *__indexable p = foo.array;
  int index = -1;
  (void)*(p + index);
}

// CHECK-LABEL: define dso_local void @good_sub_one(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_sub_one(void) {
  int *__indexable p = foo.array;
  int index = 1;
  (void)(p - index);
}

// CHECK-LABEL: define dso_local void @bad_sub_one_assign(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void bad_sub_one_assign(void) {
  int *__indexable p = foo.array;
  int index = 1;
  p = p - index;
}

// CHECK-LABEL: define dso_local void @bad_sub_one_deref(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void bad_sub_one_deref(void) {
  int *__indexable p = foo.array;
  int index = 1;
  (void)*(p - index);
}

// CHECK-LABEL: define dso_local void @good_sub_neg_one(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_sub_neg_one(void) {
  int *__indexable p = foo.array;
  int index = -1;
  (void)(p - index);
}

// CHECK-LABEL: define dso_local void @good_sub_neg_one_assign(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_sub_neg_one_assign(void) {
  int *__indexable p = foo.array;
  int index = -1;
  p = p - index;
}

// CHECK-LABEL: define dso_local void @good_sub_neg_one_deref(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_sub_neg_one_deref(void) {
  int *__indexable p = foo.array;
  int index = -1;
  (void)*(p - index);
}

// CHECK-LABEL: define dso_local void @good_add_oob(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_add_oob(void) {
  int *__indexable p = foo.array;
  int index = 10;
  (void)(p + index);
}

// CHECK-LABEL: define dso_local void @good_add_oob_assign(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_add_oob_assign(void) {
  int *__indexable p = foo.array;
  int index = 10;
  p = p + index;
}

// CHECK-LABEL: define dso_local void @bad_add_oob_deref(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void bad_add_oob_deref(void) {
  int *__indexable p = foo.array;
  int index = 10;
  (void)*(p + index);
}
