// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --version 6


// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-O0 %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-O2 %s
// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-O0 %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-O2 %s

#include <ptrcheck.h>

// CHECK-O0-LABEL: define dso_local { ptr, ptr } @add(
// CHECK-O0-SAME: ptr noundef [[P_COERCE0:%.*]], ptr noundef [[P_COERCE1:%.*]], i32 noundef [[INDEX:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-O0-NEXT:  [[ENTRY:.*:]]
// CHECK-O0-NEXT:    [[RETVAL:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-O0-NEXT:    [[P:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-O0-NEXT:    [[INDEX_ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-O0-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[P]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[P_COERCE0]], ptr [[TMP0]], align 8
// CHECK-O0-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[P]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[P_COERCE1]], ptr [[TMP1]], align 8
// CHECK-O0-NEXT:    store i32 [[INDEX]], ptr [[INDEX_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP2:%.*]] = load i32, ptr [[INDEX_ADDR]], align 4
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[P]], i64 16, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP3]], align 8
// CHECK-O0-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP4]], align 8
// CHECK-O0-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP5]], align 8
// CHECK-O0-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
// CHECK-O0-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP2]] to i64
// CHECK-O0-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i32, ptr [[TMP7]], i64 [[IDXPROM]]
// CHECK-O0-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP8]], align 8
// CHECK-O0-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[TMP9]], align 8
// CHECK-O0-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[TMP10]], ptr [[TMP11]], align 8
// CHECK-O0-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[TMP12]], align 8
// CHECK-O0-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[TMP13]], ptr [[TMP14]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR3:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR2]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB5:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR4]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[TMP15:%.*]] = icmp uge ptr [[WIDE_PTR_PTR3]], [[WIDE_PTR_LB]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP15]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT]]:
// CHECK-O0-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR3]], ptr [[TMP16]], align 8
// CHECK-O0-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_UB5]], ptr [[TMP17]], align 8
// CHECK-O0-NEXT:    [[TMP18:%.*]] = load { ptr, ptr }, ptr [[RETVAL]], align 8
// CHECK-O0-NEXT:    ret { ptr, ptr } [[TMP18]]
//
// CHECK-O2-LABEL: define dso_local { ptr, ptr } @add(
// CHECK-O2-SAME: ptr noundef [[P_COERCE0:%.*]], ptr noundef [[P_COERCE1:%.*]], i32 noundef [[INDEX:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-O2-NEXT:  [[ENTRY:.*:]]
// CHECK-O2-NEXT:    [[IDXPROM:%.*]] = sext i32 [[INDEX]] to i64
// CHECK-O2-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr [4 x i8], ptr [[P_COERCE0]], i64 [[IDXPROM]]
// CHECK-O2-NEXT:    [[DOTNOT:%.*]] = icmp ult ptr [[BOUND_PTR_ARITH]], [[P_COERCE0]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    br i1 [[DOTNOT]], label %[[TRAP:.*]], label %[[CONT:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O2:       [[TRAP]]:
// CHECK-O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O2:       [[CONT]]:
// CHECK-O2-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue { ptr, ptr } poison, ptr [[BOUND_PTR_ARITH]], 0
// CHECK-O2-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue { ptr, ptr } [[DOTFCA_0_INSERT]], ptr [[P_COERCE1]], 1
// CHECK-O2-NEXT:    ret { ptr, ptr } [[DOTFCA_1_INSERT]]
//
int *__indexable add(int *__indexable p, int index) {
  return p + index;
}

// CHECK-O0-LABEL: define dso_local { ptr, ptr } @add2(
// CHECK-O0-SAME: ptr noundef [[P_COERCE0:%.*]], ptr noundef [[P_COERCE1:%.*]], i32 noundef [[INDEX:%.*]]) #[[ATTR0]] {
// CHECK-O0-NEXT:  [[ENTRY:.*:]]
// CHECK-O0-NEXT:    [[RETVAL:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-O0-NEXT:    [[P:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-O0-NEXT:    [[INDEX_ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-O0-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[P]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[P_COERCE0]], ptr [[TMP0]], align 8
// CHECK-O0-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[P]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[P_COERCE1]], ptr [[TMP1]], align 8
// CHECK-O0-NEXT:    store i32 [[INDEX]], ptr [[INDEX_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP2:%.*]] = load i32, ptr [[INDEX_ADDR]], align 4
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[P]], i64 16, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP3]], align 8
// CHECK-O0-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP4]], align 8
// CHECK-O0-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP5]], align 8
// CHECK-O0-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
// CHECK-O0-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP2]] to i64
// CHECK-O0-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i32, ptr [[TMP7]], i64 [[IDXPROM]]
// CHECK-O0-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP8]], align 8
// CHECK-O0-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[TMP9]], align 8
// CHECK-O0-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[TMP10]], ptr [[TMP11]], align 8
// CHECK-O0-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[TMP12]], align 8
// CHECK-O0-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[TMP13]], ptr [[TMP14]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR3:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR2]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB5:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR4]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[TMP15:%.*]] = icmp uge ptr [[WIDE_PTR_PTR3]], [[WIDE_PTR_LB]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP15]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT]]:
// CHECK-O0-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR3]], ptr [[TMP16]], align 8
// CHECK-O0-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_UB5]], ptr [[TMP17]], align 8
// CHECK-O0-NEXT:    [[TMP18:%.*]] = load { ptr, ptr }, ptr [[RETVAL]], align 8
// CHECK-O0-NEXT:    ret { ptr, ptr } [[TMP18]]
//
// CHECK-O2-LABEL: define dso_local { ptr, ptr } @add2(
// CHECK-O2-SAME: ptr noundef [[P_COERCE0:%.*]], ptr noundef [[P_COERCE1:%.*]], i32 noundef [[INDEX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-O2-NEXT:  [[ENTRY:.*:]]
// CHECK-O2-NEXT:    [[IDXPROM:%.*]] = sext i32 [[INDEX]] to i64
// CHECK-O2-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr [4 x i8], ptr [[P_COERCE0]], i64 [[IDXPROM]]
// CHECK-O2-NEXT:    [[DOTNOT:%.*]] = icmp ult ptr [[BOUND_PTR_ARITH]], [[P_COERCE0]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    br i1 [[DOTNOT]], label %[[TRAP:.*]], label %[[CONT:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O2:       [[TRAP]]:
// CHECK-O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O2:       [[CONT]]:
// CHECK-O2-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue { ptr, ptr } poison, ptr [[BOUND_PTR_ARITH]], 0
// CHECK-O2-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue { ptr, ptr } [[DOTFCA_0_INSERT]], ptr [[P_COERCE1]], 1
// CHECK-O2-NEXT:    ret { ptr, ptr } [[DOTFCA_1_INSERT]]
//
int *__indexable add2(int *__indexable p, int index) {
  return index + p;
}

// CHECK-O0-LABEL: define dso_local { ptr, ptr } @sub(
// CHECK-O0-SAME: ptr noundef [[P_COERCE0:%.*]], ptr noundef [[P_COERCE1:%.*]], i32 noundef [[INDEX:%.*]]) #[[ATTR0]] {
// CHECK-O0-NEXT:  [[ENTRY:.*:]]
// CHECK-O0-NEXT:    [[RETVAL:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-O0-NEXT:    [[P:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-O0-NEXT:    [[INDEX_ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-O0-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[P]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[P_COERCE0]], ptr [[TMP0]], align 8
// CHECK-O0-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[P]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[P_COERCE1]], ptr [[TMP1]], align 8
// CHECK-O0-NEXT:    store i32 [[INDEX]], ptr [[INDEX_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP2:%.*]] = load i32, ptr [[INDEX_ADDR]], align 4
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[P]], i64 16, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP3]], align 8
// CHECK-O0-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP4]], align 8
// CHECK-O0-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP5]], align 8
// CHECK-O0-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
// CHECK-O0-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP2]] to i64
// CHECK-O0-NEXT:    [[IDX_NEG:%.*]] = sub i64 0, [[IDXPROM]]
// CHECK-O0-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i32, ptr [[TMP7]], i64 [[IDX_NEG]]
// CHECK-O0-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP8]], align 8
// CHECK-O0-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[TMP9]], align 8
// CHECK-O0-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[TMP10]], ptr [[TMP11]], align 8
// CHECK-O0-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[TMP12]], align 8
// CHECK-O0-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[TMP13]], ptr [[TMP14]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR3:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR2]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB5:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR4]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[TMP15:%.*]] = icmp uge ptr [[WIDE_PTR_PTR3]], [[WIDE_PTR_LB]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP15]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT]]:
// CHECK-O0-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR3]], ptr [[TMP16]], align 8
// CHECK-O0-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_UB5]], ptr [[TMP17]], align 8
// CHECK-O0-NEXT:    [[TMP18:%.*]] = load { ptr, ptr }, ptr [[RETVAL]], align 8
// CHECK-O0-NEXT:    ret { ptr, ptr } [[TMP18]]
//
// CHECK-O2-LABEL: define dso_local { ptr, ptr } @sub(
// CHECK-O2-SAME: ptr noundef [[P_COERCE0:%.*]], ptr noundef [[P_COERCE1:%.*]], i32 noundef [[INDEX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-O2-NEXT:  [[ENTRY:.*:]]
// CHECK-O2-NEXT:    [[IDXPROM:%.*]] = sext i32 [[INDEX]] to i64
// CHECK-O2-NEXT:    [[IDX_NEG:%.*]] = sub nsw i64 0, [[IDXPROM]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr [4 x i8], ptr [[P_COERCE0]], i64 [[IDX_NEG]]
// CHECK-O2-NEXT:    [[DOTNOT:%.*]] = icmp ult ptr [[BOUND_PTR_ARITH]], [[P_COERCE0]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    br i1 [[DOTNOT]], label %[[TRAP:.*]], label %[[CONT:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O2:       [[TRAP]]:
// CHECK-O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O2:       [[CONT]]:
// CHECK-O2-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue { ptr, ptr } poison, ptr [[BOUND_PTR_ARITH]], 0
// CHECK-O2-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue { ptr, ptr } [[DOTFCA_0_INSERT]], ptr [[P_COERCE1]], 1
// CHECK-O2-NEXT:    ret { ptr, ptr } [[DOTFCA_1_INSERT]]
//
int *__indexable sub(int *__indexable p, int index) {
  return p - index;
}

// CHECK-O0-LABEL: define dso_local void @add_bidi(
// CHECK-O0-SAME: ptr dead_on_unwind noalias writable sret(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 [[AGG_RESULT:%.*]], ptr noundef [[P_COERCE0:%.*]], ptr noundef [[P_COERCE1:%.*]], i32 noundef [[INDEX:%.*]]) #[[ATTR0]] {
// CHECK-O0-NEXT:  [[ENTRY:.*:]]
// CHECK-O0-NEXT:    [[P:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-O0-NEXT:    [[INDEX_ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-O0-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[P]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[P_COERCE0]], ptr [[TMP0]], align 8
// CHECK-O0-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[P]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[P_COERCE1]], ptr [[TMP1]], align 8
// CHECK-O0-NEXT:    store i32 [[INDEX]], ptr [[INDEX_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP2:%.*]] = load i32, ptr [[INDEX_ADDR]], align 4
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[P]], i64 16, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP3]], align 8
// CHECK-O0-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP4]], align 8
// CHECK-O0-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP5]], align 8
// CHECK-O0-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
// CHECK-O0-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP2]] to i64
// CHECK-O0-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i32, ptr [[TMP7]], i64 [[IDXPROM]]
// CHECK-O0-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP8]], align 8
// CHECK-O0-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[TMP9]], align 8
// CHECK-O0-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[TMP10]], ptr [[TMP11]], align 8
// CHECK-O0-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[TMP12]], align 8
// CHECK-O0-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[TMP13]], ptr [[TMP14]], align 8
// CHECK-O0-NEXT:    ret void
//
// CHECK-O2-LABEL: define dso_local void @add_bidi(
// CHECK-O2-SAME: ptr dead_on_unwind noalias writable writeonly sret(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 captures(none) initializes((0, 24)) [[AGG_RESULT:%.*]], ptr noundef [[P_COERCE0:%.*]], ptr noundef [[P_COERCE1:%.*]], i32 noundef [[INDEX:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-O2-NEXT:  [[ENTRY:.*:]]
// CHECK-O2-NEXT:    [[IDXPROM:%.*]] = sext i32 [[INDEX]] to i64
// CHECK-O2-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr [4 x i8], ptr [[P_COERCE0]], i64 [[IDXPROM]]
// CHECK-O2-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[AGG_RESULT]], align 8
// CHECK-O2-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i64 8
// CHECK-O2-NEXT:    store ptr [[P_COERCE1]], ptr [[TMP0]], align 8
// CHECK-O2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_RESULT]], i64 16
// CHECK-O2-NEXT:    store ptr [[P_COERCE0]], ptr [[TMP1]], align 8
// CHECK-O2-NEXT:    ret void
//
int *__bidi_indexable add_bidi(int *__indexable p, int index) {
  return index + p;
}
