// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --version 5
// Checks that are the same between -fbounds-safety-bringup-missing-checks flags
// RUN: %clang_cc1 -O2 -emit-llvm -triple arm64-apple-iphoneos -fbounds-safety -fno-bounds-safety-bringup-missing-checks=all %s -o - | FileCheck --check-prefix=SAME %s
// RUN: %clang_cc1 -O2 -emit-llvm -triple arm64-apple-iphoneos -fbounds-safety -fbounds-safety-bringup-missing-checks=all %s -o - | FileCheck --check-prefix=SAME %s

// Checks that differ with -fbounds-safety-bringup-missing-checks
// RUN: %clang_cc1 -O2 -DCOMPOUND_LITERAL -emit-llvm -triple arm64-apple-iphoneos -fbounds-safety -fno-bounds-safety-bringup-missing-checks=all %s -o - | FileCheck --check-prefix=LEGACY %s
// RUN: %clang_cc1 -O2 -DCOMPOUND_LITERAL -emit-llvm -triple arm64-apple-iphoneos -fbounds-safety -fbounds-safety-bringup-missing-checks=all %s -o - | FileCheck --check-prefix=NEW %s
#include <ptrcheck.h>


// =============================================================================
// __counted_by
// =============================================================================

struct cb {
  const int count;
  int* __counted_by(count) ptr;
};

void consume_cb(struct cb);

#ifndef COMPOUND_LITERAL

// SAME-LABEL: define dso_local void @init_list_cb(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// SAME-NEXT:  [[ENTRY:.*:]]
// SAME-NEXT:    [[CMP_NOT:%.*]] = icmp slt i32 [[COUNT_PARAM]], 0, !annotation [[META5:![0-9]+]]
// SAME-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !annotation [[META5]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation [[META5]]
// SAME-NEXT:    unreachable, !annotation [[META5]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[PTR]] to i64, !annotation [[META5]]
// SAME-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext nneg i32 [[COUNT_PARAM]] to i64
// SAME-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// SAME-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[SUB_PTR_RHS_CAST]], 1
// SAME-NEXT:    tail call void @consume_cb([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4:[0-9]+]]
// SAME-NEXT:    ret void
//
void init_list_cb(int count_param, int*__counted_by(count_param) ptr) {
  struct cb c = {.count = count_param, .ptr = ptr };
  consume_cb(c);
}

// SAME-LABEL: define dso_local void @init_list_cb_bidi(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef readonly captures(none) dead_on_return [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// SAME-NEXT:  [[ENTRY:.*:]]
// SAME-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// SAME-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// SAME-NEXT:    [[AGG_TEMP1_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// SAME-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], [[AGG_TEMP1_SROA_1_0_COPYLOAD]], !annotation [[META5]]
// SAME-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[LAND_LHS_TRUE:.*]], !annotation [[META5]]
// SAME:       [[LAND_LHS_TRUE]]:
// SAME-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// SAME-NEXT:    [[AGG_TEMP4_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[TBAA6:![0-9]+]]
// SAME-NEXT:    [[CMP14_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP4_SROA_1_0_COPYLOAD]], [[AGG_TEMP_SROA_0_0_COPYLOAD]], !annotation [[META5]]
// SAME-NEXT:    br i1 [[CMP14_NOT]], label %[[TRAP]], label %[[LAND_RHS:.*]], !annotation [[META5]]
// SAME:       [[LAND_RHS]]:
// SAME-NEXT:    [[CONV:%.*]] = sext i32 [[COUNT_PARAM]] to i64, !annotation [[META5]]
// SAME-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP1_SROA_1_0_COPYLOAD]] to i64, !annotation [[META5]]
// SAME-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]] to i64, !annotation [[META5]]
// SAME-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META9:![0-9]+]]
// SAME-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 2, !annotation [[META5]]
// SAME-NEXT:    [[CMP25:%.*]] = icmp sge i64 [[SUB_PTR_DIV]], [[CONV]], !annotation [[META5]]
// SAME-NEXT:    [[CMP28:%.*]] = icmp sgt i32 [[COUNT_PARAM]], -1, !annotation [[META5]]
// SAME-NEXT:    [[SPEC_SELECT:%.*]] = and i1 [[CMP28]], [[CMP25]]
// SAME-NEXT:    br i1 [[SPEC_SELECT]], label %[[CONT:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, !annotation [[META5]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META5]]
// SAME-NEXT:    unreachable, !annotation [[META5]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext nneg i32 [[COUNT_PARAM]] to i64
// SAME-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// SAME-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[SUB_PTR_RHS_CAST]], 1
// SAME-NEXT:    tail call void @consume_cb([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4]]
// SAME-NEXT:    ret void
//
void init_list_cb_bidi(int count_param, int* __bidi_indexable ptr) {
  struct cb c = {.count = count_param, .ptr = ptr };
  consume_cb(c);
}

#else

// LEGACY-LABEL: define dso_local void @compound_literal_init_cb(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// LEGACY-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// LEGACY-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[PTR]] to i64
// LEGACY-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[TMP0]], 1
// LEGACY-NEXT:    tail call void @consume_cb([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR2:[0-9]+]]
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_cb(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// NEW-NEXT:  [[ENTRY:.*:]]
// NEW-NEXT:    [[CMP_NOT:%.*]] = icmp slt i32 [[COUNT_PARAM]], 0, !annotation [[META5:![0-9]+]]
// NEW-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !annotation [[META5]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation [[META5]]
// NEW-NEXT:    unreachable, !annotation [[META5]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[PTR]] to i64, !annotation [[META5]]
// NEW-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext nneg i32 [[COUNT_PARAM]] to i64
// NEW-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// NEW-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[SUB_PTR_RHS_CAST]], 1
// NEW-NEXT:    tail call void @consume_cb([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4:[0-9]+]]
// NEW-NEXT:    ret void
//
void compound_literal_init_cb(int count_param, int*__counted_by(count_param) ptr) {
  struct cb c = (struct cb){.count = count_param, .ptr = ptr };
  consume_cb(c);
}

// LEGACY-LABEL: define dso_local void @compound_literal_init_cb_bidi(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef readonly captures(none) dead_on_return [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// LEGACY-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// LEGACY-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// LEGACY-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]] to i64
// LEGACY-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[TMP0]], 1
// LEGACY-NEXT:    tail call void @consume_cb([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR2]]
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_cb_bidi(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef readonly captures(none) dead_on_return [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*:]]
// NEW-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// NEW-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// NEW-NEXT:    [[AGG_TEMP1_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// NEW-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], [[AGG_TEMP1_SROA_1_0_COPYLOAD]], !annotation [[META5]]
// NEW-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[LAND_LHS_TRUE:.*]], !annotation [[META5]]
// NEW:       [[LAND_LHS_TRUE]]:
// NEW-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// NEW-NEXT:    [[AGG_TEMP4_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[TBAA6:![0-9]+]]
// NEW-NEXT:    [[CMP14_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP4_SROA_1_0_COPYLOAD]], [[AGG_TEMP_SROA_0_0_COPYLOAD]], !annotation [[META5]]
// NEW-NEXT:    br i1 [[CMP14_NOT]], label %[[TRAP]], label %[[LAND_RHS:.*]], !annotation [[META5]]
// NEW:       [[LAND_RHS]]:
// NEW-NEXT:    [[CONV:%.*]] = sext i32 [[COUNT_PARAM]] to i64, !annotation [[META5]]
// NEW-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP1_SROA_1_0_COPYLOAD]] to i64, !annotation [[META5]]
// NEW-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]] to i64, !annotation [[META5]]
// NEW-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META9:![0-9]+]]
// NEW-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 2, !annotation [[META5]]
// NEW-NEXT:    [[CMP25:%.*]] = icmp sge i64 [[SUB_PTR_DIV]], [[CONV]], !annotation [[META5]]
// NEW-NEXT:    [[CMP28:%.*]] = icmp sgt i32 [[COUNT_PARAM]], -1, !annotation [[META5]]
// NEW-NEXT:    [[SPEC_SELECT:%.*]] = and i1 [[CMP28]], [[CMP25]]
// NEW-NEXT:    br i1 [[SPEC_SELECT]], label %[[CONT:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, !annotation [[META5]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META5]]
// NEW-NEXT:    unreachable, !annotation [[META5]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext nneg i32 [[COUNT_PARAM]] to i64
// NEW-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// NEW-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[SUB_PTR_RHS_CAST]], 1
// NEW-NEXT:    tail call void @consume_cb([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4]]
// NEW-NEXT:    ret void
//
void compound_literal_init_cb_bidi(int count_param, int*__bidi_indexable ptr) {
  struct cb c = (struct cb){.count = count_param, .ptr = ptr };
  consume_cb(c);
}

#endif

// =============================================================================
// __counted_by_or_null
// =============================================================================

struct cbon {
  const int count;
  int* __counted_by_or_null(count) ptr;
};

void consume_cbon(struct cbon);

#ifndef COMPOUND_LITERAL

// SAME-LABEL: define dso_local void @init_list_cbon(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// SAME-NEXT:  [[ENTRY:.*:]]
// SAME-NEXT:    [[DOTNOT:%.*]] = icmp ne ptr [[PTR]], null, !annotation [[META12:![0-9]+]]
// SAME-NEXT:    [[CMP_NOT47:%.*]] = icmp slt i32 [[COUNT_PARAM]], 0
// SAME-NEXT:    [[CMP_NOT:%.*]] = and i1 [[CMP_NOT47]], [[DOTNOT]], !annotation [[META5]]
// SAME-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !annotation [[META5]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META5]]
// SAME-NEXT:    unreachable, !annotation [[META5]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// SAME-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// SAME-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[PTR]] to i64
// SAME-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[TMP0]], 1
// SAME-NEXT:    tail call void @consume_cbon([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4]]
// SAME-NEXT:    ret void
//
void init_list_cbon(int count_param, int*__counted_by_or_null(count_param) ptr) {
  struct cbon c = {.count = count_param, .ptr = ptr };
  consume_cbon(c);
}

// SAME-LABEL: define dso_local void @init_list_cbon_bidi(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef readonly captures(none) dead_on_return [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// SAME-NEXT:  [[ENTRY:.*:]]
// SAME-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// SAME-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// SAME-NEXT:    [[AGG_TEMP1_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// SAME-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], [[AGG_TEMP1_SROA_1_0_COPYLOAD]], !annotation [[META5]]
// SAME-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[LAND_LHS_TRUE:.*]], !annotation [[META5]]
// SAME:       [[LAND_LHS_TRUE]]:
// SAME-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// SAME-NEXT:    [[AGG_TEMP4_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[TBAA6]]
// SAME-NEXT:    [[CMP14_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP4_SROA_1_0_COPYLOAD]], [[AGG_TEMP_SROA_0_0_COPYLOAD]], !annotation [[META5]]
// SAME-NEXT:    br i1 [[CMP14_NOT]], label %[[TRAP]], label %[[LAND_RHS:.*]], !annotation [[META5]]
// SAME:       [[LAND_RHS]]:
// SAME-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], null, !annotation [[META5]]
// SAME-NEXT:    br i1 [[TOBOOL_NOT]], label %[[CONT:.*]], label %[[LOR_RHS:.*]], !annotation [[META5]]
// SAME:       [[LOR_RHS]]:
// SAME-NEXT:    [[CONV:%.*]] = sext i32 [[COUNT_PARAM]] to i64, !annotation [[META5]]
// SAME-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP1_SROA_1_0_COPYLOAD]] to i64, !annotation [[META5]]
// SAME-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]] to i64
// SAME-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META9]]
// SAME-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 2, !annotation [[META5]]
// SAME-NEXT:    [[CMP32:%.*]] = icmp sge i64 [[SUB_PTR_DIV]], [[CONV]], !annotation [[META5]]
// SAME-NEXT:    [[CMP35:%.*]] = icmp sgt i32 [[COUNT_PARAM]], -1, !annotation [[META5]]
// SAME-NEXT:    [[SPEC_SELECT:%.*]] = and i1 [[CMP35]], [[CMP32]]
// SAME-NEXT:    br i1 [[SPEC_SELECT]], label %[[CONT]], label %[[TRAP]], {{!prof ![0-9]+}}, !annotation [[META5]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META5]]
// SAME-NEXT:    unreachable, !annotation [[META5]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[DOTPRE_PHI:%.*]] = phi i64 [ [[SUB_PTR_RHS_CAST]], %[[LOR_RHS]] ], [ 0, %[[LAND_RHS]] ]
// SAME-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// SAME-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// SAME-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[DOTPRE_PHI]], 1
// SAME-NEXT:    tail call void @consume_cbon([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4]]
// SAME-NEXT:    ret void
//
void init_list_cbon_bidi(int count_param, int*__bidi_indexable ptr) {
  struct cbon c = {.count = count_param, .ptr = ptr };
  consume_cbon(c);
}

#else

// LEGACY-LABEL: define dso_local void @compound_literal_init_cbon(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[PTR]] to i64
// LEGACY-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// LEGACY-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// LEGACY-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[TMP0]], 1
// LEGACY-NEXT:    tail call void @consume_cbon([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR2]]
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_cbon(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*:]]
// NEW-NEXT:    [[DOTNOT:%.*]] = icmp ne ptr [[PTR]], null, !annotation [[META12:![0-9]+]]
// NEW-NEXT:    [[CMP_NOT47:%.*]] = icmp slt i32 [[COUNT_PARAM]], 0
// NEW-NEXT:    [[CMP_NOT:%.*]] = and i1 [[CMP_NOT47]], [[DOTNOT]], !annotation [[META5]]
// NEW-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !annotation [[META5]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META5]]
// NEW-NEXT:    unreachable, !annotation [[META5]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// NEW-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// NEW-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[PTR]] to i64
// NEW-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[TMP0]], 1
// NEW-NEXT:    tail call void @consume_cbon([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4]]
// NEW-NEXT:    ret void
//
void compound_literal_init_cbon(int count_param, int*__counted_by_or_null(count_param) ptr) {
  struct cbon c = (struct cbon){.count = count_param, .ptr = ptr };
  consume_cbon(c);
}

// LEGACY-LABEL: define dso_local void @compound_literal_init_cbon_bidi(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef readonly captures(none) dead_on_return [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// LEGACY-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// LEGACY-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// LEGACY-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]] to i64
// LEGACY-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[TMP0]], 1
// LEGACY-NEXT:    tail call void @consume_cbon([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR2]]
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_cbon_bidi(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef readonly captures(none) dead_on_return [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*:]]
// NEW-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// NEW-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// NEW-NEXT:    [[AGG_TEMP1_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// NEW-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], [[AGG_TEMP1_SROA_1_0_COPYLOAD]], !annotation [[META5]]
// NEW-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[LAND_LHS_TRUE:.*]], !annotation [[META5]]
// NEW:       [[LAND_LHS_TRUE]]:
// NEW-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// NEW-NEXT:    [[AGG_TEMP4_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[TBAA6]]
// NEW-NEXT:    [[CMP14_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP4_SROA_1_0_COPYLOAD]], [[AGG_TEMP_SROA_0_0_COPYLOAD]], !annotation [[META5]]
// NEW-NEXT:    br i1 [[CMP14_NOT]], label %[[TRAP]], label %[[LAND_RHS:.*]], !annotation [[META5]]
// NEW:       [[LAND_RHS]]:
// NEW-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], null, !annotation [[META5]]
// NEW-NEXT:    br i1 [[TOBOOL_NOT]], label %[[CONT:.*]], label %[[LOR_RHS:.*]], !annotation [[META5]]
// NEW:       [[LOR_RHS]]:
// NEW-NEXT:    [[CONV:%.*]] = sext i32 [[COUNT_PARAM]] to i64, !annotation [[META5]]
// NEW-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP1_SROA_1_0_COPYLOAD]] to i64, !annotation [[META5]]
// NEW-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]] to i64
// NEW-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META9]]
// NEW-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 2, !annotation [[META5]]
// NEW-NEXT:    [[CMP32:%.*]] = icmp sge i64 [[SUB_PTR_DIV]], [[CONV]], !annotation [[META5]]
// NEW-NEXT:    [[CMP35:%.*]] = icmp sgt i32 [[COUNT_PARAM]], -1, !annotation [[META5]]
// NEW-NEXT:    [[SPEC_SELECT:%.*]] = and i1 [[CMP35]], [[CMP32]]
// NEW-NEXT:    br i1 [[SPEC_SELECT]], label %[[CONT]], label %[[TRAP]], {{!prof ![0-9]+}}, !annotation [[META5]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META5]]
// NEW-NEXT:    unreachable, !annotation [[META5]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[DOTPRE_PHI:%.*]] = phi i64 [ [[SUB_PTR_RHS_CAST]], %[[LOR_RHS]] ], [ 0, %[[LAND_RHS]] ]
// NEW-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// NEW-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// NEW-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[DOTPRE_PHI]], 1
// NEW-NEXT:    tail call void @consume_cbon([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4]]
// NEW-NEXT:    ret void
//
void compound_literal_init_cbon_bidi(int count_param, int*__bidi_indexable ptr) {
  struct cbon c = (struct cbon){.count = count_param, .ptr = ptr };
  consume_cbon(c);
}

#endif

// =============================================================================
// __sized_by
// =============================================================================

struct sb {
  const int count;
  char* __sized_by(count) ptr;
};

void consume_sb(struct sb);

#ifndef COMPOUND_LITERAL

// SAME-LABEL: define dso_local void @init_list_sb(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// SAME-NEXT:  [[ENTRY:.*:]]
// SAME-NEXT:    [[CMP_NOT:%.*]] = icmp slt i32 [[COUNT_PARAM]], 0, !annotation [[META5]]
// SAME-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !annotation [[META5]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META5]]
// SAME-NEXT:    unreachable, !annotation [[META5]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[PTR]] to i64, !annotation [[META5]]
// SAME-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext nneg i32 [[COUNT_PARAM]] to i64
// SAME-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// SAME-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[SUB_PTR_RHS_CAST]], 1
// SAME-NEXT:    tail call void @consume_sb([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4]]
// SAME-NEXT:    ret void
//
void init_list_sb(int count_param, char*__sized_by(count_param) ptr) {
  struct sb c = {.count = count_param, .ptr = ptr };
  consume_sb(c);
}

// SAME-LABEL: define dso_local void @init_list_bidi(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef readonly captures(none) dead_on_return [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// SAME-NEXT:  [[ENTRY:.*:]]
// SAME-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// SAME-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// SAME-NEXT:    [[AGG_TEMP1_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// SAME-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], [[AGG_TEMP1_SROA_1_0_COPYLOAD]], !annotation [[META5]]
// SAME-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[LAND_LHS_TRUE:.*]], !annotation [[META5]]
// SAME:       [[LAND_LHS_TRUE]]:
// SAME-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// SAME-NEXT:    [[AGG_TEMP4_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[TBAA13:![0-9]+]]
// SAME-NEXT:    [[CMP14_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP4_SROA_1_0_COPYLOAD]], [[AGG_TEMP_SROA_0_0_COPYLOAD]], !annotation [[META5]]
// SAME-NEXT:    br i1 [[CMP14_NOT]], label %[[TRAP]], label %[[LAND_RHS:.*]], !annotation [[META5]]
// SAME:       [[LAND_RHS]]:
// SAME-NEXT:    [[CONV:%.*]] = sext i32 [[COUNT_PARAM]] to i64, !annotation [[META5]]
// SAME-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP1_SROA_1_0_COPYLOAD]] to i64, !annotation [[META5]]
// SAME-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]] to i64, !annotation [[META5]]
// SAME-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META9]]
// SAME-NEXT:    [[CMP25:%.*]] = icmp sge i64 [[SUB_PTR_SUB]], [[CONV]], !annotation [[META5]]
// SAME-NEXT:    [[CMP28:%.*]] = icmp sgt i32 [[COUNT_PARAM]], -1, !annotation [[META5]]
// SAME-NEXT:    [[SPEC_SELECT:%.*]] = and i1 [[CMP28]], [[CMP25]]
// SAME-NEXT:    br i1 [[SPEC_SELECT]], label %[[CONT:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, !annotation [[META5]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META5]]
// SAME-NEXT:    unreachable, !annotation [[META5]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext nneg i32 [[COUNT_PARAM]] to i64
// SAME-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// SAME-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[SUB_PTR_RHS_CAST]], 1
// SAME-NEXT:    tail call void @consume_sb([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4]]
// SAME-NEXT:    ret void
//
void init_list_bidi(int count_param, char*__bidi_indexable ptr) {
  struct sb c = {.count = count_param, .ptr = ptr };
  consume_sb(c);
}

#else

// LEGACY-LABEL: define dso_local void @compound_literal_init_sb(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// LEGACY-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// LEGACY-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[PTR]] to i64
// LEGACY-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[TMP0]], 1
// LEGACY-NEXT:    tail call void @consume_sb([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR2]]
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_sb(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*:]]
// NEW-NEXT:    [[CMP_NOT:%.*]] = icmp slt i32 [[COUNT_PARAM]], 0, !annotation [[META5]]
// NEW-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !annotation [[META5]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META5]]
// NEW-NEXT:    unreachable, !annotation [[META5]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[PTR]] to i64, !annotation [[META5]]
// NEW-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext nneg i32 [[COUNT_PARAM]] to i64
// NEW-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// NEW-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[SUB_PTR_RHS_CAST]], 1
// NEW-NEXT:    tail call void @consume_sb([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4]]
// NEW-NEXT:    ret void
//
void compound_literal_init_sb(int count_param, char*__sized_by(count_param) ptr) {
  struct sb c = (struct sb){.count = count_param, .ptr = ptr };
  consume_sb(c);
}

// LEGACY-LABEL: define dso_local void @compound_literal_init_sb_bidi(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef readonly captures(none) dead_on_return [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// LEGACY-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// LEGACY-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// LEGACY-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]] to i64
// LEGACY-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[TMP0]], 1
// LEGACY-NEXT:    tail call void @consume_sb([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR2]]
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_sb_bidi(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef readonly captures(none) dead_on_return [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*:]]
// NEW-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// NEW-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// NEW-NEXT:    [[AGG_TEMP1_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// NEW-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], [[AGG_TEMP1_SROA_1_0_COPYLOAD]], !annotation [[META5]]
// NEW-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[LAND_LHS_TRUE:.*]], !annotation [[META5]]
// NEW:       [[LAND_LHS_TRUE]]:
// NEW-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// NEW-NEXT:    [[AGG_TEMP4_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[TBAA13:![0-9]+]]
// NEW-NEXT:    [[CMP14_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP4_SROA_1_0_COPYLOAD]], [[AGG_TEMP_SROA_0_0_COPYLOAD]], !annotation [[META5]]
// NEW-NEXT:    br i1 [[CMP14_NOT]], label %[[TRAP]], label %[[LAND_RHS:.*]], !annotation [[META5]]
// NEW:       [[LAND_RHS]]:
// NEW-NEXT:    [[CONV:%.*]] = sext i32 [[COUNT_PARAM]] to i64, !annotation [[META5]]
// NEW-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP1_SROA_1_0_COPYLOAD]] to i64, !annotation [[META5]]
// NEW-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]] to i64, !annotation [[META5]]
// NEW-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META9]]
// NEW-NEXT:    [[CMP25:%.*]] = icmp sge i64 [[SUB_PTR_SUB]], [[CONV]], !annotation [[META5]]
// NEW-NEXT:    [[CMP28:%.*]] = icmp sgt i32 [[COUNT_PARAM]], -1, !annotation [[META5]]
// NEW-NEXT:    [[SPEC_SELECT:%.*]] = and i1 [[CMP28]], [[CMP25]]
// NEW-NEXT:    br i1 [[SPEC_SELECT]], label %[[CONT:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, !annotation [[META5]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META5]]
// NEW-NEXT:    unreachable, !annotation [[META5]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext nneg i32 [[COUNT_PARAM]] to i64
// NEW-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// NEW-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[SUB_PTR_RHS_CAST]], 1
// NEW-NEXT:    tail call void @consume_sb([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4]]
// NEW-NEXT:    ret void
//
void compound_literal_init_sb_bidi(int count_param, char*__bidi_indexable ptr) {
  struct sb c = (struct sb){.count = count_param, .ptr = ptr };
  consume_sb(c);
}

#endif

// =============================================================================
// __sized_by_or_null
// =============================================================================

struct sbon {
  const int count;
  char* __sized_by_or_null(count) ptr;
};

void consume_sbon(struct sbon);

#ifndef COMPOUND_LITERAL

// SAME-LABEL: define dso_local void @init_list_sbon(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// SAME-NEXT:  [[ENTRY:.*:]]
// SAME-NEXT:    [[DOTNOT:%.*]] = icmp ne ptr [[PTR]], null, !annotation [[META12]]
// SAME-NEXT:    [[CMP_NOT47:%.*]] = icmp slt i32 [[COUNT_PARAM]], 0
// SAME-NEXT:    [[CMP_NOT:%.*]] = and i1 [[CMP_NOT47]], [[DOTNOT]], !annotation [[META5]]
// SAME-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !annotation [[META5]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META5]]
// SAME-NEXT:    unreachable, !annotation [[META5]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// SAME-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// SAME-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[PTR]] to i64
// SAME-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[TMP0]], 1
// SAME-NEXT:    tail call void @consume_sbon([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4]]
// SAME-NEXT:    ret void
//
void init_list_sbon(int count_param, char*__sized_by_or_null(count_param) ptr) {
  struct sbon c = {.count = count_param, .ptr = ptr };
  consume_sbon(c);
}

// SAME-LABEL: define dso_local void @init_list_sbon_bidi(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef readonly captures(none) dead_on_return [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// SAME-NEXT:  [[ENTRY:.*:]]
// SAME-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// SAME-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// SAME-NEXT:    [[AGG_TEMP1_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// SAME-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], [[AGG_TEMP1_SROA_1_0_COPYLOAD]], !annotation [[META5]]
// SAME-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[LAND_LHS_TRUE:.*]], !annotation [[META5]]
// SAME:       [[LAND_LHS_TRUE]]:
// SAME-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// SAME-NEXT:    [[AGG_TEMP4_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[TBAA13]]
// SAME-NEXT:    [[CMP14_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP4_SROA_1_0_COPYLOAD]], [[AGG_TEMP_SROA_0_0_COPYLOAD]], !annotation [[META5]]
// SAME-NEXT:    br i1 [[CMP14_NOT]], label %[[TRAP]], label %[[LAND_RHS:.*]], !annotation [[META5]]
// SAME:       [[LAND_RHS]]:
// SAME-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], null, !annotation [[META5]]
// SAME-NEXT:    br i1 [[TOBOOL_NOT]], label %[[CONT:.*]], label %[[LOR_RHS:.*]], !annotation [[META5]]
// SAME:       [[LOR_RHS]]:
// SAME-NEXT:    [[CONV:%.*]] = sext i32 [[COUNT_PARAM]] to i64, !annotation [[META5]]
// SAME-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP1_SROA_1_0_COPYLOAD]] to i64, !annotation [[META5]]
// SAME-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]] to i64
// SAME-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META9]]
// SAME-NEXT:    [[CMP32:%.*]] = icmp sge i64 [[SUB_PTR_SUB]], [[CONV]], !annotation [[META5]]
// SAME-NEXT:    [[CMP35:%.*]] = icmp sgt i32 [[COUNT_PARAM]], -1, !annotation [[META5]]
// SAME-NEXT:    [[SPEC_SELECT:%.*]] = and i1 [[CMP35]], [[CMP32]]
// SAME-NEXT:    br i1 [[SPEC_SELECT]], label %[[CONT]], label %[[TRAP]], {{!prof ![0-9]+}}, !annotation [[META5]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META5]]
// SAME-NEXT:    unreachable, !annotation [[META5]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[DOTPRE_PHI:%.*]] = phi i64 [ [[SUB_PTR_RHS_CAST]], %[[LOR_RHS]] ], [ 0, %[[LAND_RHS]] ]
// SAME-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// SAME-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// SAME-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[DOTPRE_PHI]], 1
// SAME-NEXT:    tail call void @consume_sbon([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4]]
// SAME-NEXT:    ret void
//
void init_list_sbon_bidi(int count_param, char*__bidi_indexable ptr) {
  struct sbon c = {.count = count_param, .ptr = ptr };
  consume_sbon(c);
}

#else

// LEGACY-LABEL: define dso_local void @compound_literal_init_sbon(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[PTR]] to i64
// LEGACY-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// LEGACY-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// LEGACY-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[TMP0]], 1
// LEGACY-NEXT:    tail call void @consume_sbon([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR2]]
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_sbon(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*:]]
// NEW-NEXT:    [[DOTNOT:%.*]] = icmp ne ptr [[PTR]], null, !annotation [[META12]]
// NEW-NEXT:    [[CMP_NOT47:%.*]] = icmp slt i32 [[COUNT_PARAM]], 0
// NEW-NEXT:    [[CMP_NOT:%.*]] = and i1 [[CMP_NOT47]], [[DOTNOT]], !annotation [[META5]]
// NEW-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !annotation [[META5]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META5]]
// NEW-NEXT:    unreachable, !annotation [[META5]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// NEW-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// NEW-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[PTR]] to i64
// NEW-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[TMP0]], 1
// NEW-NEXT:    tail call void @consume_sbon([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4]]
// NEW-NEXT:    ret void
//
void compound_literal_init_sbon(int count_param, char*__sized_by_or_null(count_param) ptr) {
  struct sbon c = (struct sbon){.count = count_param, .ptr = ptr };
  consume_sbon(c);
}

// LEGACY-LABEL: define dso_local void @compound_literal_init_sbon_bidi(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef readonly captures(none) dead_on_return [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// LEGACY-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// LEGACY-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// LEGACY-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]] to i64
// LEGACY-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[TMP0]], 1
// LEGACY-NEXT:    tail call void @consume_sbon([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR2]]
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_sbon_bidi(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef readonly captures(none) dead_on_return [[PTR:%.*]]) local_unnamed_addr #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*:]]
// NEW-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// NEW-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// NEW-NEXT:    [[AGG_TEMP1_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// NEW-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], [[AGG_TEMP1_SROA_1_0_COPYLOAD]], !annotation [[META5]]
// NEW-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[LAND_LHS_TRUE:.*]], !annotation [[META5]]
// NEW:       [[LAND_LHS_TRUE]]:
// NEW-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// NEW-NEXT:    [[AGG_TEMP4_SROA_1_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[TBAA13]]
// NEW-NEXT:    [[CMP14_NOT:%.*]] = icmp ugt ptr [[AGG_TEMP4_SROA_1_0_COPYLOAD]], [[AGG_TEMP_SROA_0_0_COPYLOAD]], !annotation [[META5]]
// NEW-NEXT:    br i1 [[CMP14_NOT]], label %[[TRAP]], label %[[LAND_RHS:.*]], !annotation [[META5]]
// NEW:       [[LAND_RHS]]:
// NEW-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], null, !annotation [[META5]]
// NEW-NEXT:    br i1 [[TOBOOL_NOT]], label %[[CONT:.*]], label %[[LOR_RHS:.*]], !annotation [[META5]]
// NEW:       [[LOR_RHS]]:
// NEW-NEXT:    [[CONV:%.*]] = sext i32 [[COUNT_PARAM]] to i64, !annotation [[META5]]
// NEW-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP1_SROA_1_0_COPYLOAD]] to i64, !annotation [[META5]]
// NEW-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]] to i64
// NEW-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META9]]
// NEW-NEXT:    [[CMP32:%.*]] = icmp sge i64 [[SUB_PTR_SUB]], [[CONV]], !annotation [[META5]]
// NEW-NEXT:    [[CMP35:%.*]] = icmp sgt i32 [[COUNT_PARAM]], -1, !annotation [[META5]]
// NEW-NEXT:    [[SPEC_SELECT:%.*]] = and i1 [[CMP35]], [[CMP32]]
// NEW-NEXT:    br i1 [[SPEC_SELECT]], label %[[CONT]], label %[[TRAP]], {{!prof ![0-9]+}}, !annotation [[META5]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META5]]
// NEW-NEXT:    unreachable, !annotation [[META5]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[DOTPRE_PHI:%.*]] = phi i64 [ [[SUB_PTR_RHS_CAST]], %[[LOR_RHS]] ], [ 0, %[[LAND_RHS]] ]
// NEW-NEXT:    [[C_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[COUNT_PARAM]] to i64
// NEW-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue [2 x i64] poison, i64 [[C_SROA_0_0_INSERT_EXT]], 0
// NEW-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue [2 x i64] [[DOTFCA_0_INSERT]], i64 [[DOTPRE_PHI]], 1
// NEW-NEXT:    tail call void @consume_sbon([2 x i64] [[DOTFCA_1_INSERT]]) #[[ATTR4]]
// NEW-NEXT:    ret void
//
void compound_literal_init_sbon_bidi(int count_param, char*__bidi_indexable ptr) {
  struct sbon c = (struct sbon){.count = count_param, .ptr = ptr };
  consume_sbon(c);
}

#endif
//.
// SAME: [[META3:![0-9]+]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// SAME: [[META4]] = !{!"Simple C/C++ TBAA"}
// SAME: [[META5]] = !{!"bounds-safety-generic"}
// SAME: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
// SAME: [[META7]] = !{!"p1 int", [[META8:![0-9]+]], i64 0}
// SAME: [[META8]] = !{!"any pointer", [[META3]], i64 0}
// SAME: [[META9]] = !{!"bounds-safety-generic", [[META10:![0-9]+]]}
// SAME: [[META10]] = !{!"bounds-safety-missed-optimization-nsw", !"Check can not be removed because the arithmetic operation might wrap in the signed sense. Optimize the check by adding conditions to check for overflow before doing the operation"}
// SAME: [[META12]] = !{!"bounds-safety-check-ptr-neq-null"}
// SAME: [[TBAA13]] = !{[[META14:![0-9]+]], [[META14]], i64 0}
// SAME: [[META14]] = !{!"p1 omnipotent char", [[META8]], i64 0}
//.
// NEW: [[META3:![0-9]+]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// NEW: [[META4]] = !{!"Simple C/C++ TBAA"}
// NEW: [[META5]] = !{!"bounds-safety-generic"}
// NEW: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
// NEW: [[META7]] = !{!"p1 int", [[META8:![0-9]+]], i64 0}
// NEW: [[META8]] = !{!"any pointer", [[META3]], i64 0}
// NEW: [[META9]] = !{!"bounds-safety-generic", [[META10:![0-9]+]]}
// NEW: [[META10]] = !{!"bounds-safety-missed-optimization-nsw", !"Check can not be removed because the arithmetic operation might wrap in the signed sense. Optimize the check by adding conditions to check for overflow before doing the operation"}
// NEW: [[META12]] = !{!"bounds-safety-check-ptr-neq-null"}
// NEW: [[TBAA13]] = !{[[META14:![0-9]+]], [[META14]], i64 0}
// NEW: [[META14]] = !{!"p1 omnipotent char", [[META8]], i64 0}
//.
