// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --version 5
// Checks that are the same between -fbounds-safety-bringup-missing-checks flags
// RUN: %clang_cc1 -O0 -emit-llvm -triple arm64-apple-iphoneos -fbounds-safety -fno-bounds-safety-bringup-missing-checks=all %s -o - | FileCheck --check-prefix=SAME %s
// RUN: %clang_cc1 -O0 -emit-llvm -triple arm64-apple-iphoneos -fbounds-safety -fbounds-safety-bringup-missing-checks=all %s -o - | FileCheck --check-prefix=SAME %s

// Checks that differ with -fbounds-safety-bringup-missing-checks
// RUN: %clang_cc1 -O0 -DCOMPOUND_LITERAL -emit-llvm -triple arm64-apple-iphoneos -fbounds-safety -fno-bounds-safety-bringup-missing-checks=all %s -o - | FileCheck --check-prefix=LEGACY %s
// RUN: %clang_cc1 -O0 -DCOMPOUND_LITERAL -emit-llvm -triple arm64-apple-iphoneos -fbounds-safety -fbounds-safety-bringup-missing-checks=all %s -o - | FileCheck --check-prefix=NEW %s
#include <ptrcheck.h>


// =============================================================================
// __counted_by
// =============================================================================

struct cb {
  const int count;
  int* __counted_by(count) ptr;
};

void consume_cb(struct cb);

#ifndef COMPOUND_LITERAL

// SAME-LABEL: define dso_local void @init_list_cb(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0:[0-9]+]] {
// SAME-NEXT:  [[ENTRY:.*]]:
// SAME-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// SAME-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr, align 8
// SAME-NEXT:    [[C:%.*]] = alloca [[STRUCT_CB:%.*]], align 8
// SAME-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP18:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP32:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    store ptr [[PTR]], ptr [[PTR_ADDR]], align 8
// SAME-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[PTR_ADDR]], align 8
// SAME-NEXT:    [[TMP2:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP2]] to i64
// SAME-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i64 [[IDX_EXT]]
// SAME-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// SAME-NEXT:    store ptr [[TMP1]], ptr [[TMP3]], align 8
// SAME-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// SAME-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP4]], align 8
// SAME-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// SAME-NEXT:    store ptr [[TMP1]], ptr [[TMP5]], align 8
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1:![0-9]+]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END30:.*]], !annotation [[META1]]
// SAME:       [[LAND_LHS_TRUE]]:
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END30]], !annotation [[META1]]
// SAME:       [[LAND_RHS]]:
// SAME-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB17:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR16]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP18]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP18]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR20:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR19]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP18]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB22:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR21]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP18]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB24:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR23]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB17]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR20]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_DIV:%.*]] = sdiv exact i64 [[SUB_PTR_SUB]], 4, !annotation [[META1]]
// SAME-NEXT:    [[CMP25:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_DIV]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP25]], label %[[LAND_RHS27:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// SAME:       [[LAND_RHS27]]:
// SAME-NEXT:    [[CMP28:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// SAME-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// SAME:       [[LAND_END]]:
// SAME-NEXT:    [[TMP6:%.*]] = phi i1 [ false, %[[LAND_RHS]] ], [ [[CMP28]], %[[LAND_RHS27]] ]
// SAME-NEXT:    br label %[[LAND_END30]], !annotation [[META1]]
// SAME:       [[LAND_END30]]:
// SAME-NEXT:    [[TMP7:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP6]], %[[LAND_END]] ], !annotation [[META1]]
// SAME-NEXT:    br i1 [[TMP7]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], !annotation [[META1]]
// SAME-NEXT:    unreachable, !annotation [[META1]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_CB]], ptr [[C]], i32 0, i32 0
// SAME-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// SAME-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[C]], i64 4
// SAME-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP8]], i8 0, i64 4, i1 false)
// SAME-NEXT:    [[PTR31:%.*]] = getelementptr inbounds nuw [[STRUCT_CB]], ptr [[C]], i32 0, i32 1
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP32]], ptr align 8 [[TMP]], i64 24, i1 false)
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP32]], i32 0, i32 0
// SAME-NEXT:    [[WIDE_PTR_PTR34:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR33]], align 8
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR35:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP32]], i32 0, i32 1
// SAME-NEXT:    [[WIDE_PTR_UB36:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR35]], align 8
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR37:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP32]], i32 0, i32 2
// SAME-NEXT:    [[WIDE_PTR_LB38:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR37]], align 8
// SAME-NEXT:    store ptr [[WIDE_PTR_PTR34]], ptr [[PTR31]], align 8
// SAME-NEXT:    [[TMP9:%.*]] = load [2 x i64], ptr [[C]], align 8
// SAME-NEXT:    call void @consume_cb([2 x i64] [[TMP9]])
// SAME-NEXT:    ret void
//
void init_list_cb(int count_param, int*__counted_by(count_param) ptr) {
  struct cb c = {.count = count_param, .ptr = ptr };
  consume_cb(c);
}

// SAME-LABEL: define dso_local void @init_list_cb_bidi(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef dead_on_return [[PTR:%.*]]) #[[ATTR0]] {
// SAME-NEXT:  [[ENTRY:.*]]:
// SAME-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// SAME-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// SAME-NEXT:    [[C:%.*]] = alloca [[STRUCT_CB:%.*]], align 8
// SAME-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP18:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP32:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// SAME-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END30:.*]], !annotation [[META1]]
// SAME:       [[LAND_LHS_TRUE]]:
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END30]], !annotation [[META1]]
// SAME:       [[LAND_RHS]]:
// SAME-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB17:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR16]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP18]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP18]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR20:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR19]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP18]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB22:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR21]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP18]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB24:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR23]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB17]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR20]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_DIV:%.*]] = sdiv exact i64 [[SUB_PTR_SUB]], 4, !annotation [[META1]]
// SAME-NEXT:    [[CMP25:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_DIV]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP25]], label %[[LAND_RHS27:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// SAME:       [[LAND_RHS27]]:
// SAME-NEXT:    [[CMP28:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// SAME-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// SAME:       [[LAND_END]]:
// SAME-NEXT:    [[TMP1:%.*]] = phi i1 [ false, %[[LAND_RHS]] ], [ [[CMP28]], %[[LAND_RHS27]] ]
// SAME-NEXT:    br label %[[LAND_END30]], !annotation [[META1]]
// SAME:       [[LAND_END30]]:
// SAME-NEXT:    [[TMP2:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP1]], %[[LAND_END]] ], !annotation [[META1]]
// SAME-NEXT:    br i1 [[TMP2]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META1]]
// SAME-NEXT:    unreachable, !annotation [[META1]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_CB]], ptr [[C]], i32 0, i32 0
// SAME-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// SAME-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[C]], i64 4
// SAME-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP3]], i8 0, i64 4, i1 false)
// SAME-NEXT:    [[PTR31:%.*]] = getelementptr inbounds nuw [[STRUCT_CB]], ptr [[C]], i32 0, i32 1
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP32]], ptr align 8 [[PTR]], i64 24, i1 false)
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP32]], i32 0, i32 0
// SAME-NEXT:    [[WIDE_PTR_PTR34:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR33]], align 8
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR35:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP32]], i32 0, i32 1
// SAME-NEXT:    [[WIDE_PTR_UB36:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR35]], align 8
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR37:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP32]], i32 0, i32 2
// SAME-NEXT:    [[WIDE_PTR_LB38:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR37]], align 8
// SAME-NEXT:    store ptr [[WIDE_PTR_PTR34]], ptr [[PTR31]], align 8
// SAME-NEXT:    [[TMP4:%.*]] = load [2 x i64], ptr [[C]], align 8
// SAME-NEXT:    call void @consume_cb([2 x i64] [[TMP4]])
// SAME-NEXT:    ret void
//
void init_list_cb_bidi(int count_param, int* __bidi_indexable ptr) {
  struct cb c = {.count = count_param, .ptr = ptr };
  consume_cb(c);
}

#else

// LEGACY-LABEL: define dso_local void @compound_literal_init_cb(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0:[0-9]+]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// LEGACY-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr, align 8
// LEGACY-NEXT:    [[C:%.*]] = alloca [[STRUCT_CB:%.*]], align 8
// LEGACY-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// LEGACY-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store ptr [[PTR]], ptr [[PTR_ADDR]], align 8
// LEGACY-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_CB]], ptr [[C]], i32 0, i32 0
// LEGACY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// LEGACY-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[C]], i64 4
// LEGACY-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP1]], i8 0, i64 4, i1 false)
// LEGACY-NEXT:    [[PTR1:%.*]] = getelementptr inbounds nuw [[STRUCT_CB]], ptr [[C]], i32 0, i32 1
// LEGACY-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[PTR_ADDR]], align 8
// LEGACY-NEXT:    [[TMP3:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP3]] to i64
// LEGACY-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP2]], i64 [[IDX_EXT]]
// LEGACY-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    store ptr [[TMP2]], ptr [[TMP4]], align 8
// LEGACY-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP5]], align 8
// LEGACY-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    store ptr [[TMP2]], ptr [[TMP6]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// LEGACY-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[PTR1]], align 8
// LEGACY-NEXT:    [[TMP7:%.*]] = load [2 x i64], ptr [[C]], align 8
// LEGACY-NEXT:    call void @consume_cb([2 x i64] [[TMP7]])
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_cb(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0:[0-9]+]] {
// NEW-NEXT:  [[ENTRY:.*]]:
// NEW-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// NEW-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr, align 8
// NEW-NEXT:    [[C:%.*]] = alloca [[STRUCT_CB:%.*]], align 8
// NEW-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP18:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP32:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    store ptr [[PTR]], ptr [[PTR_ADDR]], align 8
// NEW-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[PTR_ADDR]], align 8
// NEW-NEXT:    [[TMP2:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP2]] to i64
// NEW-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i64 [[IDX_EXT]]
// NEW-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// NEW-NEXT:    store ptr [[TMP1]], ptr [[TMP3]], align 8
// NEW-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// NEW-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP4]], align 8
// NEW-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// NEW-NEXT:    store ptr [[TMP1]], ptr [[TMP5]], align 8
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1:![0-9]+]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END30:.*]], !annotation [[META1]]
// NEW:       [[LAND_LHS_TRUE]]:
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END30]], !annotation [[META1]]
// NEW:       [[LAND_RHS]]:
// NEW-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB17:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR16]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP18]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP18]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR20:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR19]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP18]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB22:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR21]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP18]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB24:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR23]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB17]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR20]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_DIV:%.*]] = sdiv exact i64 [[SUB_PTR_SUB]], 4, !annotation [[META1]]
// NEW-NEXT:    [[CMP25:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_DIV]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP25]], label %[[LAND_RHS27:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// NEW:       [[LAND_RHS27]]:
// NEW-NEXT:    [[CMP28:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// NEW-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// NEW:       [[LAND_END]]:
// NEW-NEXT:    [[TMP6:%.*]] = phi i1 [ false, %[[LAND_RHS]] ], [ [[CMP28]], %[[LAND_RHS27]] ]
// NEW-NEXT:    br label %[[LAND_END30]], !annotation [[META1]]
// NEW:       [[LAND_END30]]:
// NEW-NEXT:    [[TMP7:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP6]], %[[LAND_END]] ], !annotation [[META1]]
// NEW-NEXT:    br i1 [[TMP7]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], !annotation [[META1]]
// NEW-NEXT:    unreachable, !annotation [[META1]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_CB]], ptr [[C]], i32 0, i32 0
// NEW-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// NEW-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[C]], i64 4
// NEW-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP8]], i8 0, i64 4, i1 false)
// NEW-NEXT:    [[PTR31:%.*]] = getelementptr inbounds nuw [[STRUCT_CB]], ptr [[C]], i32 0, i32 1
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP32]], ptr align 8 [[TMP]], i64 24, i1 false)
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP32]], i32 0, i32 0
// NEW-NEXT:    [[WIDE_PTR_PTR34:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR33]], align 8
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR35:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP32]], i32 0, i32 1
// NEW-NEXT:    [[WIDE_PTR_UB36:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR35]], align 8
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR37:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP32]], i32 0, i32 2
// NEW-NEXT:    [[WIDE_PTR_LB38:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR37]], align 8
// NEW-NEXT:    store ptr [[WIDE_PTR_PTR34]], ptr [[PTR31]], align 8
// NEW-NEXT:    [[TMP9:%.*]] = load [2 x i64], ptr [[C]], align 8
// NEW-NEXT:    call void @consume_cb([2 x i64] [[TMP9]])
// NEW-NEXT:    ret void
//
void compound_literal_init_cb(int count_param, int*__counted_by(count_param) ptr) {
  struct cb c = (struct cb){.count = count_param, .ptr = ptr };
  consume_cb(c);
}

// LEGACY-LABEL: define dso_local void @compound_literal_init_cb_bidi(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef dead_on_return [[PTR:%.*]]) #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// LEGACY-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// LEGACY-NEXT:    [[C:%.*]] = alloca [[STRUCT_CB:%.*]], align 8
// LEGACY-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// LEGACY-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// LEGACY-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_CB]], ptr [[C]], i32 0, i32 0
// LEGACY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// LEGACY-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[C]], i64 4
// LEGACY-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP1]], i8 0, i64 4, i1 false)
// LEGACY-NEXT:    [[PTR1:%.*]] = getelementptr inbounds nuw [[STRUCT_CB]], ptr [[C]], i32 0, i32 1
// LEGACY-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// LEGACY-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// LEGACY-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[PTR1]], align 8
// LEGACY-NEXT:    [[TMP2:%.*]] = load [2 x i64], ptr [[C]], align 8
// LEGACY-NEXT:    call void @consume_cb([2 x i64] [[TMP2]])
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_cb_bidi(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef dead_on_return [[PTR:%.*]]) #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*]]:
// NEW-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// NEW-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// NEW-NEXT:    [[C:%.*]] = alloca [[STRUCT_CB:%.*]], align 8
// NEW-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP18:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP32:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// NEW-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END30:.*]], !annotation [[META1]]
// NEW:       [[LAND_LHS_TRUE]]:
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END30]], !annotation [[META1]]
// NEW:       [[LAND_RHS]]:
// NEW-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB17:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR16]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP18]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP18]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR20:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR19]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP18]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB22:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR21]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP18]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB24:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR23]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB17]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR20]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_DIV:%.*]] = sdiv exact i64 [[SUB_PTR_SUB]], 4, !annotation [[META1]]
// NEW-NEXT:    [[CMP25:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_DIV]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP25]], label %[[LAND_RHS27:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// NEW:       [[LAND_RHS27]]:
// NEW-NEXT:    [[CMP28:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// NEW-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// NEW:       [[LAND_END]]:
// NEW-NEXT:    [[TMP1:%.*]] = phi i1 [ false, %[[LAND_RHS]] ], [ [[CMP28]], %[[LAND_RHS27]] ]
// NEW-NEXT:    br label %[[LAND_END30]], !annotation [[META1]]
// NEW:       [[LAND_END30]]:
// NEW-NEXT:    [[TMP2:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP1]], %[[LAND_END]] ], !annotation [[META1]]
// NEW-NEXT:    br i1 [[TMP2]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META1]]
// NEW-NEXT:    unreachable, !annotation [[META1]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_CB]], ptr [[C]], i32 0, i32 0
// NEW-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// NEW-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[C]], i64 4
// NEW-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP3]], i8 0, i64 4, i1 false)
// NEW-NEXT:    [[PTR31:%.*]] = getelementptr inbounds nuw [[STRUCT_CB]], ptr [[C]], i32 0, i32 1
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP32]], ptr align 8 [[PTR]], i64 24, i1 false)
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP32]], i32 0, i32 0
// NEW-NEXT:    [[WIDE_PTR_PTR34:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR33]], align 8
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR35:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP32]], i32 0, i32 1
// NEW-NEXT:    [[WIDE_PTR_UB36:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR35]], align 8
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR37:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP32]], i32 0, i32 2
// NEW-NEXT:    [[WIDE_PTR_LB38:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR37]], align 8
// NEW-NEXT:    store ptr [[WIDE_PTR_PTR34]], ptr [[PTR31]], align 8
// NEW-NEXT:    [[TMP4:%.*]] = load [2 x i64], ptr [[C]], align 8
// NEW-NEXT:    call void @consume_cb([2 x i64] [[TMP4]])
// NEW-NEXT:    ret void
//
void compound_literal_init_cb_bidi(int count_param, int*__bidi_indexable ptr) {
  struct cb c = (struct cb){.count = count_param, .ptr = ptr };
  consume_cb(c);
}

#endif

// =============================================================================
// __counted_by_or_null
// =============================================================================

struct cbon {
  const int count;
  int* __counted_by_or_null(count) ptr;
};

void consume_cbon(struct cbon);

#ifndef COMPOUND_LITERAL

// SAME-LABEL: define dso_local void @init_list_cbon(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// SAME-NEXT:  [[ENTRY:.*:]]
// SAME-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// SAME-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr, align 8
// SAME-NEXT:    [[C:%.*]] = alloca [[STRUCT_CBON:%.*]], align 8
// SAME-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP22:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP25:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP39:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    store ptr [[PTR]], ptr [[PTR_ADDR]], align 8
// SAME-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[PTR_ADDR]], align 8
// SAME-NEXT:    [[TMP2:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    [[TMP3:%.*]] = icmp ne ptr [[TMP1]], null, !annotation [[META3:![0-9]+]]
// SAME-NEXT:    br i1 [[TMP3]], label %[[BOUNDSCHECK_NOTNULL:.*]], label %[[BOUNDSCHECK_NULL:.*]], !annotation [[META3]]
// SAME:       [[BOUNDSCHECK_NOTNULL]]:
// SAME-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP2]] to i64
// SAME-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i64 [[IDX_EXT]]
// SAME-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// SAME-NEXT:    store ptr [[TMP1]], ptr [[TMP4]], align 8
// SAME-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// SAME-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP5]], align 8
// SAME-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// SAME-NEXT:    store ptr [[TMP1]], ptr [[TMP6]], align 8
// SAME-NEXT:    br label %[[BOUNDSCHECK_CONT:.*]]
// SAME:       [[BOUNDSCHECK_NULL]]:
// SAME-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// SAME-NEXT:    store ptr null, ptr [[TMP7]], align 8
// SAME-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// SAME-NEXT:    store ptr null, ptr [[TMP8]], align 8
// SAME-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// SAME-NEXT:    store ptr null, ptr [[TMP9]], align 8
// SAME-NEXT:    br label %[[BOUNDSCHECK_CONT]]
// SAME:       [[BOUNDSCHECK_CONT]]:
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END37:.*]], !annotation [[META1]]
// SAME:       [[LAND_LHS_TRUE]]:
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END37]], !annotation [[META1]]
// SAME:       [[LAND_RHS]]:
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR17:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR16]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB19:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR18]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB21:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR20]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[TOBOOL:%.*]] = icmp ne ptr [[WIDE_PTR_PTR17]], null, !annotation [[META1]]
// SAME-NEXT:    br i1 [[TOBOOL]], label %[[LOR_RHS:.*]], label %[[LOR_END:.*]], !annotation [[META1]]
// SAME:       [[LOR_RHS]]:
// SAME-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP22]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP22]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB24:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR23]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP25]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR26:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP25]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR27:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR26]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP25]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB29:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR28]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR30:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP25]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB31:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR30]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB24]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR27]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_DIV:%.*]] = sdiv exact i64 [[SUB_PTR_SUB]], 4, !annotation [[META1]]
// SAME-NEXT:    [[CMP32:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_DIV]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP32]], label %[[LAND_RHS34:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// SAME:       [[LAND_RHS34]]:
// SAME-NEXT:    [[CMP35:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// SAME-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// SAME:       [[LAND_END]]:
// SAME-NEXT:    [[TMP10:%.*]] = phi i1 [ false, %[[LOR_RHS]] ], [ [[CMP35]], %[[LAND_RHS34]] ]
// SAME-NEXT:    br label %[[LOR_END]], !annotation [[META1]]
// SAME:       [[LOR_END]]:
// SAME-NEXT:    [[TMP11:%.*]] = phi i1 [ true, %[[LAND_RHS]] ], [ [[TMP10]], %[[LAND_END]] ]
// SAME-NEXT:    br label %[[LAND_END37]], !annotation [[META1]]
// SAME:       [[LAND_END37]]:
// SAME-NEXT:    [[TMP12:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[BOUNDSCHECK_CONT]] ], [ [[TMP11]], %[[LOR_END]] ], !annotation [[META1]]
// SAME-NEXT:    br i1 [[TMP12]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META1]]
// SAME-NEXT:    unreachable, !annotation [[META1]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_CBON]], ptr [[C]], i32 0, i32 0
// SAME-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// SAME-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[C]], i64 4
// SAME-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP13]], i8 0, i64 4, i1 false)
// SAME-NEXT:    [[PTR38:%.*]] = getelementptr inbounds nuw [[STRUCT_CBON]], ptr [[C]], i32 0, i32 1
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP39]], ptr align 8 [[TMP]], i64 24, i1 false)
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR40:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP39]], i32 0, i32 0
// SAME-NEXT:    [[WIDE_PTR_PTR41:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR40]], align 8
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR42:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP39]], i32 0, i32 1
// SAME-NEXT:    [[WIDE_PTR_UB43:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR42]], align 8
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR44:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP39]], i32 0, i32 2
// SAME-NEXT:    [[WIDE_PTR_LB45:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR44]], align 8
// SAME-NEXT:    store ptr [[WIDE_PTR_PTR41]], ptr [[PTR38]], align 8
// SAME-NEXT:    [[TMP14:%.*]] = load [2 x i64], ptr [[C]], align 8
// SAME-NEXT:    call void @consume_cbon([2 x i64] [[TMP14]])
// SAME-NEXT:    ret void
//
void init_list_cbon(int count_param, int*__counted_by_or_null(count_param) ptr) {
  struct cbon c = {.count = count_param, .ptr = ptr };
  consume_cbon(c);
}

// SAME-LABEL: define dso_local void @init_list_cbon_bidi(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef dead_on_return [[PTR:%.*]]) #[[ATTR0]] {
// SAME-NEXT:  [[ENTRY:.*]]:
// SAME-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// SAME-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// SAME-NEXT:    [[C:%.*]] = alloca [[STRUCT_CBON:%.*]], align 8
// SAME-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP22:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP25:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    [[AGG_TEMP39:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// SAME-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// SAME-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END37:.*]], !annotation [[META1]]
// SAME:       [[LAND_LHS_TRUE]]:
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END37]], !annotation [[META1]]
// SAME:       [[LAND_RHS]]:
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR17:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR16]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB19:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR18]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB21:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR20]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[TOBOOL:%.*]] = icmp ne ptr [[WIDE_PTR_PTR17]], null, !annotation [[META1]]
// SAME-NEXT:    br i1 [[TOBOOL]], label %[[LOR_RHS:.*]], label %[[LOR_END:.*]], !annotation [[META1]]
// SAME:       [[LOR_RHS]]:
// SAME-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP22]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP22]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB24:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR23]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP25]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR26:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP25]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR27:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR26]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP25]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB29:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR28]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR30:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP25]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB31:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR30]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB24]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR27]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_DIV:%.*]] = sdiv exact i64 [[SUB_PTR_SUB]], 4, !annotation [[META1]]
// SAME-NEXT:    [[CMP32:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_DIV]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP32]], label %[[LAND_RHS34:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// SAME:       [[LAND_RHS34]]:
// SAME-NEXT:    [[CMP35:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// SAME-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// SAME:       [[LAND_END]]:
// SAME-NEXT:    [[TMP1:%.*]] = phi i1 [ false, %[[LOR_RHS]] ], [ [[CMP35]], %[[LAND_RHS34]] ]
// SAME-NEXT:    br label %[[LOR_END]], !annotation [[META1]]
// SAME:       [[LOR_END]]:
// SAME-NEXT:    [[TMP2:%.*]] = phi i1 [ true, %[[LAND_RHS]] ], [ [[TMP1]], %[[LAND_END]] ]
// SAME-NEXT:    br label %[[LAND_END37]], !annotation [[META1]]
// SAME:       [[LAND_END37]]:
// SAME-NEXT:    [[TMP3:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP2]], %[[LOR_END]] ], !annotation [[META1]]
// SAME-NEXT:    br i1 [[TMP3]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META1]]
// SAME-NEXT:    unreachable, !annotation [[META1]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_CBON]], ptr [[C]], i32 0, i32 0
// SAME-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// SAME-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[C]], i64 4
// SAME-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP4]], i8 0, i64 4, i1 false)
// SAME-NEXT:    [[PTR38:%.*]] = getelementptr inbounds nuw [[STRUCT_CBON]], ptr [[C]], i32 0, i32 1
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP39]], ptr align 8 [[PTR]], i64 24, i1 false)
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR40:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP39]], i32 0, i32 0
// SAME-NEXT:    [[WIDE_PTR_PTR41:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR40]], align 8
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR42:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP39]], i32 0, i32 1
// SAME-NEXT:    [[WIDE_PTR_UB43:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR42]], align 8
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR44:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP39]], i32 0, i32 2
// SAME-NEXT:    [[WIDE_PTR_LB45:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR44]], align 8
// SAME-NEXT:    store ptr [[WIDE_PTR_PTR41]], ptr [[PTR38]], align 8
// SAME-NEXT:    [[TMP5:%.*]] = load [2 x i64], ptr [[C]], align 8
// SAME-NEXT:    call void @consume_cbon([2 x i64] [[TMP5]])
// SAME-NEXT:    ret void
//
void init_list_cbon_bidi(int count_param, int*__bidi_indexable ptr) {
  struct cbon c = {.count = count_param, .ptr = ptr };
  consume_cbon(c);
}

#else

// LEGACY-LABEL: define dso_local void @compound_literal_init_cbon(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// LEGACY-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr, align 8
// LEGACY-NEXT:    [[C:%.*]] = alloca [[STRUCT_CBON:%.*]], align 8
// LEGACY-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// LEGACY-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store ptr [[PTR]], ptr [[PTR_ADDR]], align 8
// LEGACY-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_CBON]], ptr [[C]], i32 0, i32 0
// LEGACY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// LEGACY-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[C]], i64 4
// LEGACY-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP1]], i8 0, i64 4, i1 false)
// LEGACY-NEXT:    [[PTR1:%.*]] = getelementptr inbounds nuw [[STRUCT_CBON]], ptr [[C]], i32 0, i32 1
// LEGACY-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[PTR_ADDR]], align 8
// LEGACY-NEXT:    [[TMP3:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    [[TMP4:%.*]] = icmp ne ptr [[TMP2]], null, !annotation [[META1:![0-9]+]]
// LEGACY-NEXT:    br i1 [[TMP4]], label %[[BOUNDSCHECK_NOTNULL:.*]], label %[[BOUNDSCHECK_NULL:.*]], !annotation [[META1]]
// LEGACY:       [[BOUNDSCHECK_NOTNULL]]:
// LEGACY-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP3]] to i64
// LEGACY-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP2]], i64 [[IDX_EXT]]
// LEGACY-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    store ptr [[TMP2]], ptr [[TMP5]], align 8
// LEGACY-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP6]], align 8
// LEGACY-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    store ptr [[TMP2]], ptr [[TMP7]], align 8
// LEGACY-NEXT:    br label %[[BOUNDSCHECK_CONT:.*]]
// LEGACY:       [[BOUNDSCHECK_NULL]]:
// LEGACY-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    store ptr null, ptr [[TMP8]], align 8
// LEGACY-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    store ptr null, ptr [[TMP9]], align 8
// LEGACY-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    store ptr null, ptr [[TMP10]], align 8
// LEGACY-NEXT:    br label %[[BOUNDSCHECK_CONT]]
// LEGACY:       [[BOUNDSCHECK_CONT]]:
// LEGACY-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// LEGACY-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[PTR1]], align 8
// LEGACY-NEXT:    [[TMP11:%.*]] = load [2 x i64], ptr [[C]], align 8
// LEGACY-NEXT:    call void @consume_cbon([2 x i64] [[TMP11]])
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_cbon(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*:]]
// NEW-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// NEW-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr, align 8
// NEW-NEXT:    [[C:%.*]] = alloca [[STRUCT_CBON:%.*]], align 8
// NEW-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP22:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP25:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP39:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    store ptr [[PTR]], ptr [[PTR_ADDR]], align 8
// NEW-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[PTR_ADDR]], align 8
// NEW-NEXT:    [[TMP2:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    [[TMP3:%.*]] = icmp ne ptr [[TMP1]], null, !annotation [[META3:![0-9]+]]
// NEW-NEXT:    br i1 [[TMP3]], label %[[BOUNDSCHECK_NOTNULL:.*]], label %[[BOUNDSCHECK_NULL:.*]], !annotation [[META3]]
// NEW:       [[BOUNDSCHECK_NOTNULL]]:
// NEW-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP2]] to i64
// NEW-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i64 [[IDX_EXT]]
// NEW-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// NEW-NEXT:    store ptr [[TMP1]], ptr [[TMP4]], align 8
// NEW-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// NEW-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP5]], align 8
// NEW-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// NEW-NEXT:    store ptr [[TMP1]], ptr [[TMP6]], align 8
// NEW-NEXT:    br label %[[BOUNDSCHECK_CONT:.*]]
// NEW:       [[BOUNDSCHECK_NULL]]:
// NEW-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// NEW-NEXT:    store ptr null, ptr [[TMP7]], align 8
// NEW-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// NEW-NEXT:    store ptr null, ptr [[TMP8]], align 8
// NEW-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// NEW-NEXT:    store ptr null, ptr [[TMP9]], align 8
// NEW-NEXT:    br label %[[BOUNDSCHECK_CONT]]
// NEW:       [[BOUNDSCHECK_CONT]]:
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END37:.*]], !annotation [[META1]]
// NEW:       [[LAND_LHS_TRUE]]:
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END37]], !annotation [[META1]]
// NEW:       [[LAND_RHS]]:
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR17:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR16]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB19:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR18]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB21:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR20]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[TOBOOL:%.*]] = icmp ne ptr [[WIDE_PTR_PTR17]], null, !annotation [[META1]]
// NEW-NEXT:    br i1 [[TOBOOL]], label %[[LOR_RHS:.*]], label %[[LOR_END:.*]], !annotation [[META1]]
// NEW:       [[LOR_RHS]]:
// NEW-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP22]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP22]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB24:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR23]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP25]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR26:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP25]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR27:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR26]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP25]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB29:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR28]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR30:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP25]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB31:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR30]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB24]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR27]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_DIV:%.*]] = sdiv exact i64 [[SUB_PTR_SUB]], 4, !annotation [[META1]]
// NEW-NEXT:    [[CMP32:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_DIV]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP32]], label %[[LAND_RHS34:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// NEW:       [[LAND_RHS34]]:
// NEW-NEXT:    [[CMP35:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// NEW-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// NEW:       [[LAND_END]]:
// NEW-NEXT:    [[TMP10:%.*]] = phi i1 [ false, %[[LOR_RHS]] ], [ [[CMP35]], %[[LAND_RHS34]] ]
// NEW-NEXT:    br label %[[LOR_END]], !annotation [[META1]]
// NEW:       [[LOR_END]]:
// NEW-NEXT:    [[TMP11:%.*]] = phi i1 [ true, %[[LAND_RHS]] ], [ [[TMP10]], %[[LAND_END]] ]
// NEW-NEXT:    br label %[[LAND_END37]], !annotation [[META1]]
// NEW:       [[LAND_END37]]:
// NEW-NEXT:    [[TMP12:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[BOUNDSCHECK_CONT]] ], [ [[TMP11]], %[[LOR_END]] ], !annotation [[META1]]
// NEW-NEXT:    br i1 [[TMP12]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META1]]
// NEW-NEXT:    unreachable, !annotation [[META1]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_CBON]], ptr [[C]], i32 0, i32 0
// NEW-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// NEW-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[C]], i64 4
// NEW-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP13]], i8 0, i64 4, i1 false)
// NEW-NEXT:    [[PTR38:%.*]] = getelementptr inbounds nuw [[STRUCT_CBON]], ptr [[C]], i32 0, i32 1
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP39]], ptr align 8 [[TMP]], i64 24, i1 false)
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR40:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP39]], i32 0, i32 0
// NEW-NEXT:    [[WIDE_PTR_PTR41:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR40]], align 8
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR42:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP39]], i32 0, i32 1
// NEW-NEXT:    [[WIDE_PTR_UB43:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR42]], align 8
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR44:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP39]], i32 0, i32 2
// NEW-NEXT:    [[WIDE_PTR_LB45:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR44]], align 8
// NEW-NEXT:    store ptr [[WIDE_PTR_PTR41]], ptr [[PTR38]], align 8
// NEW-NEXT:    [[TMP14:%.*]] = load [2 x i64], ptr [[C]], align 8
// NEW-NEXT:    call void @consume_cbon([2 x i64] [[TMP14]])
// NEW-NEXT:    ret void
//
void compound_literal_init_cbon(int count_param, int*__counted_by_or_null(count_param) ptr) {
  struct cbon c = (struct cbon){.count = count_param, .ptr = ptr };
  consume_cbon(c);
}

// LEGACY-LABEL: define dso_local void @compound_literal_init_cbon_bidi(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef dead_on_return [[PTR:%.*]]) #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// LEGACY-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// LEGACY-NEXT:    [[C:%.*]] = alloca [[STRUCT_CBON:%.*]], align 8
// LEGACY-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// LEGACY-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// LEGACY-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_CBON]], ptr [[C]], i32 0, i32 0
// LEGACY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// LEGACY-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[C]], i64 4
// LEGACY-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP1]], i8 0, i64 4, i1 false)
// LEGACY-NEXT:    [[PTR1:%.*]] = getelementptr inbounds nuw [[STRUCT_CBON]], ptr [[C]], i32 0, i32 1
// LEGACY-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// LEGACY-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// LEGACY-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[PTR1]], align 8
// LEGACY-NEXT:    [[TMP2:%.*]] = load [2 x i64], ptr [[C]], align 8
// LEGACY-NEXT:    call void @consume_cbon([2 x i64] [[TMP2]])
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_cbon_bidi(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef dead_on_return [[PTR:%.*]]) #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*]]:
// NEW-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// NEW-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// NEW-NEXT:    [[C:%.*]] = alloca [[STRUCT_CBON:%.*]], align 8
// NEW-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP22:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP25:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    [[AGG_TEMP39:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NEW-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// NEW-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END37:.*]], !annotation [[META1]]
// NEW:       [[LAND_LHS_TRUE]]:
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END37]], !annotation [[META1]]
// NEW:       [[LAND_RHS]]:
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR17:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR16]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB19:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR18]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB21:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR20]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[TOBOOL:%.*]] = icmp ne ptr [[WIDE_PTR_PTR17]], null, !annotation [[META1]]
// NEW-NEXT:    br i1 [[TOBOOL]], label %[[LOR_RHS:.*]], label %[[LOR_END:.*]], !annotation [[META1]]
// NEW:       [[LOR_RHS]]:
// NEW-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP22]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP22]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB24:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR23]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP25]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR26:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP25]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR27:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR26]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP25]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB29:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR28]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR30:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP25]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB31:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR30]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB24]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR27]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_DIV:%.*]] = sdiv exact i64 [[SUB_PTR_SUB]], 4, !annotation [[META1]]
// NEW-NEXT:    [[CMP32:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_DIV]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP32]], label %[[LAND_RHS34:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// NEW:       [[LAND_RHS34]]:
// NEW-NEXT:    [[CMP35:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// NEW-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// NEW:       [[LAND_END]]:
// NEW-NEXT:    [[TMP1:%.*]] = phi i1 [ false, %[[LOR_RHS]] ], [ [[CMP35]], %[[LAND_RHS34]] ]
// NEW-NEXT:    br label %[[LOR_END]], !annotation [[META1]]
// NEW:       [[LOR_END]]:
// NEW-NEXT:    [[TMP2:%.*]] = phi i1 [ true, %[[LAND_RHS]] ], [ [[TMP1]], %[[LAND_END]] ]
// NEW-NEXT:    br label %[[LAND_END37]], !annotation [[META1]]
// NEW:       [[LAND_END37]]:
// NEW-NEXT:    [[TMP3:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP2]], %[[LOR_END]] ], !annotation [[META1]]
// NEW-NEXT:    br i1 [[TMP3]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META1]]
// NEW-NEXT:    unreachable, !annotation [[META1]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_CBON]], ptr [[C]], i32 0, i32 0
// NEW-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// NEW-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[C]], i64 4
// NEW-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP4]], i8 0, i64 4, i1 false)
// NEW-NEXT:    [[PTR38:%.*]] = getelementptr inbounds nuw [[STRUCT_CBON]], ptr [[C]], i32 0, i32 1
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP39]], ptr align 8 [[PTR]], i64 24, i1 false)
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR40:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP39]], i32 0, i32 0
// NEW-NEXT:    [[WIDE_PTR_PTR41:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR40]], align 8
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR42:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP39]], i32 0, i32 1
// NEW-NEXT:    [[WIDE_PTR_UB43:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR42]], align 8
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR44:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP39]], i32 0, i32 2
// NEW-NEXT:    [[WIDE_PTR_LB45:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR44]], align 8
// NEW-NEXT:    store ptr [[WIDE_PTR_PTR41]], ptr [[PTR38]], align 8
// NEW-NEXT:    [[TMP5:%.*]] = load [2 x i64], ptr [[C]], align 8
// NEW-NEXT:    call void @consume_cbon([2 x i64] [[TMP5]])
// NEW-NEXT:    ret void
//
void compound_literal_init_cbon_bidi(int count_param, int*__bidi_indexable ptr) {
  struct cbon c = (struct cbon){.count = count_param, .ptr = ptr };
  consume_cbon(c);
}

#endif

// =============================================================================
// __sized_by
// =============================================================================

struct sb {
  const int count;
  char* __sized_by(count) ptr;
};

void consume_sb(struct sb);

#ifndef COMPOUND_LITERAL

// SAME-LABEL: define dso_local void @init_list_sb(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// SAME-NEXT:  [[ENTRY:.*]]:
// SAME-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// SAME-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr, align 8
// SAME-NEXT:    [[C:%.*]] = alloca [[STRUCT_SB:%.*]], align 8
// SAME-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP18:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP32:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    store ptr [[PTR]], ptr [[PTR_ADDR]], align 8
// SAME-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[PTR_ADDR]], align 8
// SAME-NEXT:    [[TMP2:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP2]] to i64
// SAME-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 [[IDX_EXT]]
// SAME-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 0
// SAME-NEXT:    store ptr [[TMP1]], ptr [[TMP3]], align 8
// SAME-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 1
// SAME-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP4]], align 8
// SAME-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 2
// SAME-NEXT:    store ptr [[TMP1]], ptr [[TMP5]], align 8
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END30:.*]], !annotation [[META1]]
// SAME:       [[LAND_LHS_TRUE]]:
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END30]], !annotation [[META1]]
// SAME:       [[LAND_RHS]]:
// SAME-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB17:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR16]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP18]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP18]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR20:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR19]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP18]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB22:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR21]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP18]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB24:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR23]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB17]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR20]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// SAME-NEXT:    [[CMP25:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_SUB]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP25]], label %[[LAND_RHS27:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// SAME:       [[LAND_RHS27]]:
// SAME-NEXT:    [[CMP28:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// SAME-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// SAME:       [[LAND_END]]:
// SAME-NEXT:    [[TMP6:%.*]] = phi i1 [ false, %[[LAND_RHS]] ], [ [[CMP28]], %[[LAND_RHS27]] ]
// SAME-NEXT:    br label %[[LAND_END30]], !annotation [[META1]]
// SAME:       [[LAND_END30]]:
// SAME-NEXT:    [[TMP7:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP6]], %[[LAND_END]] ], !annotation [[META1]]
// SAME-NEXT:    br i1 [[TMP7]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META1]]
// SAME-NEXT:    unreachable, !annotation [[META1]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_SB]], ptr [[C]], i32 0, i32 0
// SAME-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// SAME-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[C]], i64 4
// SAME-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP8]], i8 0, i64 4, i1 false)
// SAME-NEXT:    [[PTR31:%.*]] = getelementptr inbounds nuw [[STRUCT_SB]], ptr [[C]], i32 0, i32 1
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP32]], ptr align 8 [[TMP]], i64 24, i1 false)
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP32]], i32 0, i32 0
// SAME-NEXT:    [[WIDE_PTR_PTR34:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR33]], align 8
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR35:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP32]], i32 0, i32 1
// SAME-NEXT:    [[WIDE_PTR_UB36:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR35]], align 8
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR37:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP32]], i32 0, i32 2
// SAME-NEXT:    [[WIDE_PTR_LB38:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR37]], align 8
// SAME-NEXT:    store ptr [[WIDE_PTR_PTR34]], ptr [[PTR31]], align 8
// SAME-NEXT:    [[TMP9:%.*]] = load [2 x i64], ptr [[C]], align 8
// SAME-NEXT:    call void @consume_sb([2 x i64] [[TMP9]])
// SAME-NEXT:    ret void
//
void init_list_sb(int count_param, char*__sized_by(count_param) ptr) {
  struct sb c = {.count = count_param, .ptr = ptr };
  consume_sb(c);
}

// SAME-LABEL: define dso_local void @init_list_bidi(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef dead_on_return [[PTR:%.*]]) #[[ATTR0]] {
// SAME-NEXT:  [[ENTRY:.*]]:
// SAME-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// SAME-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// SAME-NEXT:    [[C:%.*]] = alloca [[STRUCT_SB:%.*]], align 8
// SAME-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP18:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP32:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// SAME-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END30:.*]], !annotation [[META1]]
// SAME:       [[LAND_LHS_TRUE]]:
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END30]], !annotation [[META1]]
// SAME:       [[LAND_RHS]]:
// SAME-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB17:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR16]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP18]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP18]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR20:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR19]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP18]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB22:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR21]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP18]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB24:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR23]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB17]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR20]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// SAME-NEXT:    [[CMP25:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_SUB]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP25]], label %[[LAND_RHS27:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// SAME:       [[LAND_RHS27]]:
// SAME-NEXT:    [[CMP28:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// SAME-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// SAME:       [[LAND_END]]:
// SAME-NEXT:    [[TMP1:%.*]] = phi i1 [ false, %[[LAND_RHS]] ], [ [[CMP28]], %[[LAND_RHS27]] ]
// SAME-NEXT:    br label %[[LAND_END30]], !annotation [[META1]]
// SAME:       [[LAND_END30]]:
// SAME-NEXT:    [[TMP2:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP1]], %[[LAND_END]] ], !annotation [[META1]]
// SAME-NEXT:    br i1 [[TMP2]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META1]]
// SAME-NEXT:    unreachable, !annotation [[META1]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_SB]], ptr [[C]], i32 0, i32 0
// SAME-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// SAME-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[C]], i64 4
// SAME-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP3]], i8 0, i64 4, i1 false)
// SAME-NEXT:    [[PTR31:%.*]] = getelementptr inbounds nuw [[STRUCT_SB]], ptr [[C]], i32 0, i32 1
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP32]], ptr align 8 [[PTR]], i64 24, i1 false)
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP32]], i32 0, i32 0
// SAME-NEXT:    [[WIDE_PTR_PTR34:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR33]], align 8
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR35:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP32]], i32 0, i32 1
// SAME-NEXT:    [[WIDE_PTR_UB36:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR35]], align 8
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR37:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP32]], i32 0, i32 2
// SAME-NEXT:    [[WIDE_PTR_LB38:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR37]], align 8
// SAME-NEXT:    store ptr [[WIDE_PTR_PTR34]], ptr [[PTR31]], align 8
// SAME-NEXT:    [[TMP4:%.*]] = load [2 x i64], ptr [[C]], align 8
// SAME-NEXT:    call void @consume_sb([2 x i64] [[TMP4]])
// SAME-NEXT:    ret void
//
void init_list_bidi(int count_param, char*__bidi_indexable ptr) {
  struct sb c = {.count = count_param, .ptr = ptr };
  consume_sb(c);
}

#else

// LEGACY-LABEL: define dso_local void @compound_literal_init_sb(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// LEGACY-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr, align 8
// LEGACY-NEXT:    [[C:%.*]] = alloca [[STRUCT_SB:%.*]], align 8
// LEGACY-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// LEGACY-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store ptr [[PTR]], ptr [[PTR_ADDR]], align 8
// LEGACY-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_SB]], ptr [[C]], i32 0, i32 0
// LEGACY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// LEGACY-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[C]], i64 4
// LEGACY-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP1]], i8 0, i64 4, i1 false)
// LEGACY-NEXT:    [[PTR1:%.*]] = getelementptr inbounds nuw [[STRUCT_SB]], ptr [[C]], i32 0, i32 1
// LEGACY-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[PTR_ADDR]], align 8
// LEGACY-NEXT:    [[TMP3:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP3]] to i64
// LEGACY-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[TMP2]], i64 [[IDX_EXT]]
// LEGACY-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    store ptr [[TMP2]], ptr [[TMP4]], align 8
// LEGACY-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP5]], align 8
// LEGACY-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    store ptr [[TMP2]], ptr [[TMP6]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// LEGACY-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[PTR1]], align 8
// LEGACY-NEXT:    [[TMP7:%.*]] = load [2 x i64], ptr [[C]], align 8
// LEGACY-NEXT:    call void @consume_sb([2 x i64] [[TMP7]])
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_sb(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*]]:
// NEW-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// NEW-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr, align 8
// NEW-NEXT:    [[C:%.*]] = alloca [[STRUCT_SB:%.*]], align 8
// NEW-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP18:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP32:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    store ptr [[PTR]], ptr [[PTR_ADDR]], align 8
// NEW-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[PTR_ADDR]], align 8
// NEW-NEXT:    [[TMP2:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP2]] to i64
// NEW-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 [[IDX_EXT]]
// NEW-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 0
// NEW-NEXT:    store ptr [[TMP1]], ptr [[TMP3]], align 8
// NEW-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 1
// NEW-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP4]], align 8
// NEW-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 2
// NEW-NEXT:    store ptr [[TMP1]], ptr [[TMP5]], align 8
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END30:.*]], !annotation [[META1]]
// NEW:       [[LAND_LHS_TRUE]]:
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END30]], !annotation [[META1]]
// NEW:       [[LAND_RHS]]:
// NEW-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB17:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR16]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP18]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP18]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR20:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR19]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP18]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB22:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR21]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP18]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB24:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR23]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB17]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR20]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// NEW-NEXT:    [[CMP25:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_SUB]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP25]], label %[[LAND_RHS27:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// NEW:       [[LAND_RHS27]]:
// NEW-NEXT:    [[CMP28:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// NEW-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// NEW:       [[LAND_END]]:
// NEW-NEXT:    [[TMP6:%.*]] = phi i1 [ false, %[[LAND_RHS]] ], [ [[CMP28]], %[[LAND_RHS27]] ]
// NEW-NEXT:    br label %[[LAND_END30]], !annotation [[META1]]
// NEW:       [[LAND_END30]]:
// NEW-NEXT:    [[TMP7:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP6]], %[[LAND_END]] ], !annotation [[META1]]
// NEW-NEXT:    br i1 [[TMP7]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META1]]
// NEW-NEXT:    unreachable, !annotation [[META1]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_SB]], ptr [[C]], i32 0, i32 0
// NEW-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// NEW-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[C]], i64 4
// NEW-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP8]], i8 0, i64 4, i1 false)
// NEW-NEXT:    [[PTR31:%.*]] = getelementptr inbounds nuw [[STRUCT_SB]], ptr [[C]], i32 0, i32 1
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP32]], ptr align 8 [[TMP]], i64 24, i1 false)
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP32]], i32 0, i32 0
// NEW-NEXT:    [[WIDE_PTR_PTR34:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR33]], align 8
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR35:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP32]], i32 0, i32 1
// NEW-NEXT:    [[WIDE_PTR_UB36:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR35]], align 8
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR37:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP32]], i32 0, i32 2
// NEW-NEXT:    [[WIDE_PTR_LB38:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR37]], align 8
// NEW-NEXT:    store ptr [[WIDE_PTR_PTR34]], ptr [[PTR31]], align 8
// NEW-NEXT:    [[TMP9:%.*]] = load [2 x i64], ptr [[C]], align 8
// NEW-NEXT:    call void @consume_sb([2 x i64] [[TMP9]])
// NEW-NEXT:    ret void
//
void compound_literal_init_sb(int count_param, char*__sized_by(count_param) ptr) {
  struct sb c = (struct sb){.count = count_param, .ptr = ptr };
  consume_sb(c);
}

// LEGACY-LABEL: define dso_local void @compound_literal_init_sb_bidi(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef dead_on_return [[PTR:%.*]]) #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// LEGACY-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// LEGACY-NEXT:    [[C:%.*]] = alloca [[STRUCT_SB:%.*]], align 8
// LEGACY-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// LEGACY-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// LEGACY-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_SB]], ptr [[C]], i32 0, i32 0
// LEGACY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// LEGACY-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[C]], i64 4
// LEGACY-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP1]], i8 0, i64 4, i1 false)
// LEGACY-NEXT:    [[PTR1:%.*]] = getelementptr inbounds nuw [[STRUCT_SB]], ptr [[C]], i32 0, i32 1
// LEGACY-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// LEGACY-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// LEGACY-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[PTR1]], align 8
// LEGACY-NEXT:    [[TMP2:%.*]] = load [2 x i64], ptr [[C]], align 8
// LEGACY-NEXT:    call void @consume_sb([2 x i64] [[TMP2]])
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_sb_bidi(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef dead_on_return [[PTR:%.*]]) #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*]]:
// NEW-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// NEW-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// NEW-NEXT:    [[C:%.*]] = alloca [[STRUCT_SB:%.*]], align 8
// NEW-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP18:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP32:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// NEW-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END30:.*]], !annotation [[META1]]
// NEW:       [[LAND_LHS_TRUE]]:
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END30]], !annotation [[META1]]
// NEW:       [[LAND_RHS]]:
// NEW-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB17:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR16]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP18]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP18]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR20:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR19]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP18]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB22:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR21]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP18]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB24:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR23]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB17]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR20]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// NEW-NEXT:    [[CMP25:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_SUB]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP25]], label %[[LAND_RHS27:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// NEW:       [[LAND_RHS27]]:
// NEW-NEXT:    [[CMP28:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// NEW-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// NEW:       [[LAND_END]]:
// NEW-NEXT:    [[TMP1:%.*]] = phi i1 [ false, %[[LAND_RHS]] ], [ [[CMP28]], %[[LAND_RHS27]] ]
// NEW-NEXT:    br label %[[LAND_END30]], !annotation [[META1]]
// NEW:       [[LAND_END30]]:
// NEW-NEXT:    [[TMP2:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP1]], %[[LAND_END]] ], !annotation [[META1]]
// NEW-NEXT:    br i1 [[TMP2]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META1]]
// NEW-NEXT:    unreachable, !annotation [[META1]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_SB]], ptr [[C]], i32 0, i32 0
// NEW-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// NEW-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[C]], i64 4
// NEW-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP3]], i8 0, i64 4, i1 false)
// NEW-NEXT:    [[PTR31:%.*]] = getelementptr inbounds nuw [[STRUCT_SB]], ptr [[C]], i32 0, i32 1
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP32]], ptr align 8 [[PTR]], i64 24, i1 false)
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP32]], i32 0, i32 0
// NEW-NEXT:    [[WIDE_PTR_PTR34:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR33]], align 8
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR35:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP32]], i32 0, i32 1
// NEW-NEXT:    [[WIDE_PTR_UB36:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR35]], align 8
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR37:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP32]], i32 0, i32 2
// NEW-NEXT:    [[WIDE_PTR_LB38:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR37]], align 8
// NEW-NEXT:    store ptr [[WIDE_PTR_PTR34]], ptr [[PTR31]], align 8
// NEW-NEXT:    [[TMP4:%.*]] = load [2 x i64], ptr [[C]], align 8
// NEW-NEXT:    call void @consume_sb([2 x i64] [[TMP4]])
// NEW-NEXT:    ret void
//
void compound_literal_init_sb_bidi(int count_param, char*__bidi_indexable ptr) {
  struct sb c = (struct sb){.count = count_param, .ptr = ptr };
  consume_sb(c);
}

#endif

// =============================================================================
// __sized_by_or_null
// =============================================================================

struct sbon {
  const int count;
  char* __sized_by_or_null(count) ptr;
};

void consume_sbon(struct sbon);

#ifndef COMPOUND_LITERAL

// SAME-LABEL: define dso_local void @init_list_sbon(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// SAME-NEXT:  [[ENTRY:.*:]]
// SAME-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// SAME-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr, align 8
// SAME-NEXT:    [[C:%.*]] = alloca [[STRUCT_SBON:%.*]], align 8
// SAME-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP22:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP25:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP39:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    store ptr [[PTR]], ptr [[PTR_ADDR]], align 8
// SAME-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[PTR_ADDR]], align 8
// SAME-NEXT:    [[TMP2:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    [[TMP3:%.*]] = icmp ne ptr [[TMP1]], null, !annotation [[META3]]
// SAME-NEXT:    br i1 [[TMP3]], label %[[BOUNDSCHECK_NOTNULL:.*]], label %[[BOUNDSCHECK_NULL:.*]], !annotation [[META3]]
// SAME:       [[BOUNDSCHECK_NOTNULL]]:
// SAME-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP2]] to i64
// SAME-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 [[IDX_EXT]]
// SAME-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 0
// SAME-NEXT:    store ptr [[TMP1]], ptr [[TMP4]], align 8
// SAME-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 1
// SAME-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP5]], align 8
// SAME-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 2
// SAME-NEXT:    store ptr [[TMP1]], ptr [[TMP6]], align 8
// SAME-NEXT:    br label %[[BOUNDSCHECK_CONT:.*]]
// SAME:       [[BOUNDSCHECK_NULL]]:
// SAME-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 0
// SAME-NEXT:    store ptr null, ptr [[TMP7]], align 8
// SAME-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 1
// SAME-NEXT:    store ptr null, ptr [[TMP8]], align 8
// SAME-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 2
// SAME-NEXT:    store ptr null, ptr [[TMP9]], align 8
// SAME-NEXT:    br label %[[BOUNDSCHECK_CONT]]
// SAME:       [[BOUNDSCHECK_CONT]]:
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END37:.*]], !annotation [[META1]]
// SAME:       [[LAND_LHS_TRUE]]:
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END37]], !annotation [[META1]]
// SAME:       [[LAND_RHS]]:
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR17:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR16]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB19:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR18]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB21:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR20]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[TOBOOL:%.*]] = icmp ne ptr [[WIDE_PTR_PTR17]], null, !annotation [[META1]]
// SAME-NEXT:    br i1 [[TOBOOL]], label %[[LOR_RHS:.*]], label %[[LOR_END:.*]], !annotation [[META1]]
// SAME:       [[LOR_RHS]]:
// SAME-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP22]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP22]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB24:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR23]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP25]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR26:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP25]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR27:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR26]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP25]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB29:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR28]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR30:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP25]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB31:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR30]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB24]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR27]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// SAME-NEXT:    [[CMP32:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_SUB]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP32]], label %[[LAND_RHS34:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// SAME:       [[LAND_RHS34]]:
// SAME-NEXT:    [[CMP35:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// SAME-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// SAME:       [[LAND_END]]:
// SAME-NEXT:    [[TMP10:%.*]] = phi i1 [ false, %[[LOR_RHS]] ], [ [[CMP35]], %[[LAND_RHS34]] ]
// SAME-NEXT:    br label %[[LOR_END]], !annotation [[META1]]
// SAME:       [[LOR_END]]:
// SAME-NEXT:    [[TMP11:%.*]] = phi i1 [ true, %[[LAND_RHS]] ], [ [[TMP10]], %[[LAND_END]] ]
// SAME-NEXT:    br label %[[LAND_END37]], !annotation [[META1]]
// SAME:       [[LAND_END37]]:
// SAME-NEXT:    [[TMP12:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[BOUNDSCHECK_CONT]] ], [ [[TMP11]], %[[LOR_END]] ], !annotation [[META1]]
// SAME-NEXT:    br i1 [[TMP12]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META1]]
// SAME-NEXT:    unreachable, !annotation [[META1]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_SBON]], ptr [[C]], i32 0, i32 0
// SAME-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// SAME-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[C]], i64 4
// SAME-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP13]], i8 0, i64 4, i1 false)
// SAME-NEXT:    [[PTR38:%.*]] = getelementptr inbounds nuw [[STRUCT_SBON]], ptr [[C]], i32 0, i32 1
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP39]], ptr align 8 [[TMP]], i64 24, i1 false)
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR40:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP39]], i32 0, i32 0
// SAME-NEXT:    [[WIDE_PTR_PTR41:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR40]], align 8
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR42:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP39]], i32 0, i32 1
// SAME-NEXT:    [[WIDE_PTR_UB43:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR42]], align 8
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR44:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP39]], i32 0, i32 2
// SAME-NEXT:    [[WIDE_PTR_LB45:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR44]], align 8
// SAME-NEXT:    store ptr [[WIDE_PTR_PTR41]], ptr [[PTR38]], align 8
// SAME-NEXT:    [[TMP14:%.*]] = load [2 x i64], ptr [[C]], align 8
// SAME-NEXT:    call void @consume_sbon([2 x i64] [[TMP14]])
// SAME-NEXT:    ret void
//
void init_list_sbon(int count_param, char*__sized_by_or_null(count_param) ptr) {
  struct sbon c = {.count = count_param, .ptr = ptr };
  consume_sbon(c);
}

// SAME-LABEL: define dso_local void @init_list_sbon_bidi(
// SAME-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef dead_on_return [[PTR:%.*]]) #[[ATTR0]] {
// SAME-NEXT:  [[ENTRY:.*]]:
// SAME-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// SAME-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// SAME-NEXT:    [[C:%.*]] = alloca [[STRUCT_SBON:%.*]], align 8
// SAME-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP22:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP25:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    [[AGG_TEMP39:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// SAME-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// SAME-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END37:.*]], !annotation [[META1]]
// SAME:       [[LAND_LHS_TRUE]]:
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END37]], !annotation [[META1]]
// SAME:       [[LAND_RHS]]:
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR17:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR16]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB19:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR18]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB21:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR20]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[TOBOOL:%.*]] = icmp ne ptr [[WIDE_PTR_PTR17]], null, !annotation [[META1]]
// SAME-NEXT:    br i1 [[TOBOOL]], label %[[LOR_RHS:.*]], label %[[LOR_END:.*]], !annotation [[META1]]
// SAME:       [[LOR_RHS]]:
// SAME-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP22]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP22]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB24:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR23]], align 8, !annotation [[META1]]
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP25]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR26:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP25]], i32 0, i32 0, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_PTR27:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR26]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP25]], i32 0, i32 1, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_UB29:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR28]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR30:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP25]], i32 0, i32 2, !annotation [[META1]]
// SAME-NEXT:    [[WIDE_PTR_LB31:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR30]], align 8, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB24]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR27]] to i64, !annotation [[META1]]
// SAME-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// SAME-NEXT:    [[CMP32:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_SUB]], !annotation [[META1]]
// SAME-NEXT:    br i1 [[CMP32]], label %[[LAND_RHS34:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// SAME:       [[LAND_RHS34]]:
// SAME-NEXT:    [[CMP35:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// SAME-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// SAME:       [[LAND_END]]:
// SAME-NEXT:    [[TMP1:%.*]] = phi i1 [ false, %[[LOR_RHS]] ], [ [[CMP35]], %[[LAND_RHS34]] ]
// SAME-NEXT:    br label %[[LOR_END]], !annotation [[META1]]
// SAME:       [[LOR_END]]:
// SAME-NEXT:    [[TMP2:%.*]] = phi i1 [ true, %[[LAND_RHS]] ], [ [[TMP1]], %[[LAND_END]] ]
// SAME-NEXT:    br label %[[LAND_END37]], !annotation [[META1]]
// SAME:       [[LAND_END37]]:
// SAME-NEXT:    [[TMP3:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP2]], %[[LOR_END]] ], !annotation [[META1]]
// SAME-NEXT:    br i1 [[TMP3]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// SAME:       [[TRAP]]:
// SAME-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META1]]
// SAME-NEXT:    unreachable, !annotation [[META1]]
// SAME:       [[CONT]]:
// SAME-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_SBON]], ptr [[C]], i32 0, i32 0
// SAME-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// SAME-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[C]], i64 4
// SAME-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP4]], i8 0, i64 4, i1 false)
// SAME-NEXT:    [[PTR38:%.*]] = getelementptr inbounds nuw [[STRUCT_SBON]], ptr [[C]], i32 0, i32 1
// SAME-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP39]], ptr align 8 [[PTR]], i64 24, i1 false)
// SAME-NEXT:    [[WIDE_PTR_PTR_ADDR40:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP39]], i32 0, i32 0
// SAME-NEXT:    [[WIDE_PTR_PTR41:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR40]], align 8
// SAME-NEXT:    [[WIDE_PTR_UB_ADDR42:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP39]], i32 0, i32 1
// SAME-NEXT:    [[WIDE_PTR_UB43:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR42]], align 8
// SAME-NEXT:    [[WIDE_PTR_LB_ADDR44:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP39]], i32 0, i32 2
// SAME-NEXT:    [[WIDE_PTR_LB45:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR44]], align 8
// SAME-NEXT:    store ptr [[WIDE_PTR_PTR41]], ptr [[PTR38]], align 8
// SAME-NEXT:    [[TMP5:%.*]] = load [2 x i64], ptr [[C]], align 8
// SAME-NEXT:    call void @consume_sbon([2 x i64] [[TMP5]])
// SAME-NEXT:    ret void
//
void init_list_sbon_bidi(int count_param, char*__bidi_indexable ptr) {
  struct sbon c = {.count = count_param, .ptr = ptr };
  consume_sbon(c);
}

#else

// LEGACY-LABEL: define dso_local void @compound_literal_init_sbon(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// LEGACY-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr, align 8
// LEGACY-NEXT:    [[C:%.*]] = alloca [[STRUCT_SBON:%.*]], align 8
// LEGACY-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// LEGACY-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store ptr [[PTR]], ptr [[PTR_ADDR]], align 8
// LEGACY-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_SBON]], ptr [[C]], i32 0, i32 0
// LEGACY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// LEGACY-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[C]], i64 4
// LEGACY-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP1]], i8 0, i64 4, i1 false)
// LEGACY-NEXT:    [[PTR1:%.*]] = getelementptr inbounds nuw [[STRUCT_SBON]], ptr [[C]], i32 0, i32 1
// LEGACY-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[PTR_ADDR]], align 8
// LEGACY-NEXT:    [[TMP3:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    [[TMP4:%.*]] = icmp ne ptr [[TMP2]], null, !annotation [[META1]]
// LEGACY-NEXT:    br i1 [[TMP4]], label %[[BOUNDSCHECK_NOTNULL:.*]], label %[[BOUNDSCHECK_NULL:.*]], !annotation [[META1]]
// LEGACY:       [[BOUNDSCHECK_NOTNULL]]:
// LEGACY-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP3]] to i64
// LEGACY-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[TMP2]], i64 [[IDX_EXT]]
// LEGACY-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    store ptr [[TMP2]], ptr [[TMP5]], align 8
// LEGACY-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP6]], align 8
// LEGACY-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    store ptr [[TMP2]], ptr [[TMP7]], align 8
// LEGACY-NEXT:    br label %[[BOUNDSCHECK_CONT:.*]]
// LEGACY:       [[BOUNDSCHECK_NULL]]:
// LEGACY-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    store ptr null, ptr [[TMP8]], align 8
// LEGACY-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    store ptr null, ptr [[TMP9]], align 8
// LEGACY-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    store ptr null, ptr [[TMP10]], align 8
// LEGACY-NEXT:    br label %[[BOUNDSCHECK_CONT]]
// LEGACY:       [[BOUNDSCHECK_CONT]]:
// LEGACY-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// LEGACY-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[PTR1]], align 8
// LEGACY-NEXT:    [[TMP11:%.*]] = load [2 x i64], ptr [[C]], align 8
// LEGACY-NEXT:    call void @consume_sbon([2 x i64] [[TMP11]])
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_sbon(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*:]]
// NEW-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// NEW-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr, align 8
// NEW-NEXT:    [[C:%.*]] = alloca [[STRUCT_SBON:%.*]], align 8
// NEW-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP22:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP25:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP39:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    store ptr [[PTR]], ptr [[PTR_ADDR]], align 8
// NEW-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[PTR_ADDR]], align 8
// NEW-NEXT:    [[TMP2:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    [[TMP3:%.*]] = icmp ne ptr [[TMP1]], null, !annotation [[META3]]
// NEW-NEXT:    br i1 [[TMP3]], label %[[BOUNDSCHECK_NOTNULL:.*]], label %[[BOUNDSCHECK_NULL:.*]], !annotation [[META3]]
// NEW:       [[BOUNDSCHECK_NOTNULL]]:
// NEW-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP2]] to i64
// NEW-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 [[IDX_EXT]]
// NEW-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 0
// NEW-NEXT:    store ptr [[TMP1]], ptr [[TMP4]], align 8
// NEW-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 1
// NEW-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP5]], align 8
// NEW-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 2
// NEW-NEXT:    store ptr [[TMP1]], ptr [[TMP6]], align 8
// NEW-NEXT:    br label %[[BOUNDSCHECK_CONT:.*]]
// NEW:       [[BOUNDSCHECK_NULL]]:
// NEW-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 0
// NEW-NEXT:    store ptr null, ptr [[TMP7]], align 8
// NEW-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 1
// NEW-NEXT:    store ptr null, ptr [[TMP8]], align 8
// NEW-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[TMP]], i32 0, i32 2
// NEW-NEXT:    store ptr null, ptr [[TMP9]], align 8
// NEW-NEXT:    br label %[[BOUNDSCHECK_CONT]]
// NEW:       [[BOUNDSCHECK_CONT]]:
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END37:.*]], !annotation [[META1]]
// NEW:       [[LAND_LHS_TRUE]]:
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END37]], !annotation [[META1]]
// NEW:       [[LAND_RHS]]:
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR17:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR16]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB19:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR18]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB21:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR20]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[TOBOOL:%.*]] = icmp ne ptr [[WIDE_PTR_PTR17]], null, !annotation [[META1]]
// NEW-NEXT:    br i1 [[TOBOOL]], label %[[LOR_RHS:.*]], label %[[LOR_END:.*]], !annotation [[META1]]
// NEW:       [[LOR_RHS]]:
// NEW-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP22]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP22]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB24:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR23]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP25]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR26:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP25]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR27:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR26]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP25]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB29:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR28]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR30:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP25]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB31:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR30]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB24]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR27]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// NEW-NEXT:    [[CMP32:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_SUB]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP32]], label %[[LAND_RHS34:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// NEW:       [[LAND_RHS34]]:
// NEW-NEXT:    [[CMP35:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// NEW-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// NEW:       [[LAND_END]]:
// NEW-NEXT:    [[TMP10:%.*]] = phi i1 [ false, %[[LOR_RHS]] ], [ [[CMP35]], %[[LAND_RHS34]] ]
// NEW-NEXT:    br label %[[LOR_END]], !annotation [[META1]]
// NEW:       [[LOR_END]]:
// NEW-NEXT:    [[TMP11:%.*]] = phi i1 [ true, %[[LAND_RHS]] ], [ [[TMP10]], %[[LAND_END]] ]
// NEW-NEXT:    br label %[[LAND_END37]], !annotation [[META1]]
// NEW:       [[LAND_END37]]:
// NEW-NEXT:    [[TMP12:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[BOUNDSCHECK_CONT]] ], [ [[TMP11]], %[[LOR_END]] ], !annotation [[META1]]
// NEW-NEXT:    br i1 [[TMP12]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META1]]
// NEW-NEXT:    unreachable, !annotation [[META1]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_SBON]], ptr [[C]], i32 0, i32 0
// NEW-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// NEW-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[C]], i64 4
// NEW-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP13]], i8 0, i64 4, i1 false)
// NEW-NEXT:    [[PTR38:%.*]] = getelementptr inbounds nuw [[STRUCT_SBON]], ptr [[C]], i32 0, i32 1
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP39]], ptr align 8 [[TMP]], i64 24, i1 false)
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR40:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP39]], i32 0, i32 0
// NEW-NEXT:    [[WIDE_PTR_PTR41:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR40]], align 8
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR42:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP39]], i32 0, i32 1
// NEW-NEXT:    [[WIDE_PTR_UB43:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR42]], align 8
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR44:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP39]], i32 0, i32 2
// NEW-NEXT:    [[WIDE_PTR_LB45:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR44]], align 8
// NEW-NEXT:    store ptr [[WIDE_PTR_PTR41]], ptr [[PTR38]], align 8
// NEW-NEXT:    [[TMP14:%.*]] = load [2 x i64], ptr [[C]], align 8
// NEW-NEXT:    call void @consume_sbon([2 x i64] [[TMP14]])
// NEW-NEXT:    ret void
//
void compound_literal_init_sbon(int count_param, char*__sized_by_or_null(count_param) ptr) {
  struct sbon c = (struct sbon){.count = count_param, .ptr = ptr };
  consume_sbon(c);
}

// LEGACY-LABEL: define dso_local void @compound_literal_init_sbon_bidi(
// LEGACY-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef dead_on_return [[PTR:%.*]]) #[[ATTR0]] {
// LEGACY-NEXT:  [[ENTRY:.*:]]
// LEGACY-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// LEGACY-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// LEGACY-NEXT:    [[C:%.*]] = alloca [[STRUCT_SBON:%.*]], align 8
// LEGACY-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// LEGACY-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// LEGACY-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_SBON]], ptr [[C]], i32 0, i32 0
// LEGACY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// LEGACY-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// LEGACY-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[C]], i64 4
// LEGACY-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP1]], i8 0, i64 4, i1 false)
// LEGACY-NEXT:    [[PTR1:%.*]] = getelementptr inbounds nuw [[STRUCT_SBON]], ptr [[C]], i32 0, i32 1
// LEGACY-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// LEGACY-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// LEGACY-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// LEGACY-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// LEGACY-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// LEGACY-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// LEGACY-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[PTR1]], align 8
// LEGACY-NEXT:    [[TMP2:%.*]] = load [2 x i64], ptr [[C]], align 8
// LEGACY-NEXT:    call void @consume_sbon([2 x i64] [[TMP2]])
// LEGACY-NEXT:    ret void
//
// NEW-LABEL: define dso_local void @compound_literal_init_sbon_bidi(
// NEW-SAME: i32 noundef [[COUNT_PARAM:%.*]], ptr noundef dead_on_return [[PTR:%.*]]) #[[ATTR0]] {
// NEW-NEXT:  [[ENTRY:.*]]:
// NEW-NEXT:    [[COUNT_PARAM_ADDR:%.*]] = alloca i32, align 4
// NEW-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// NEW-NEXT:    [[C:%.*]] = alloca [[STRUCT_SBON:%.*]], align 8
// NEW-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP4:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP22:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP25:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    [[AGG_TEMP39:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NEW-NEXT:    store i32 [[COUNT_PARAM]], ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// NEW-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT_PARAM_ADDR]], align 4
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB3]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END37:.*]], !annotation [[META1]]
// NEW:       [[LAND_LHS_TRUE]]:
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP4]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP4]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP7]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[CMP14:%.*]] = icmp ule ptr [[WIDE_PTR_LB6]], [[WIDE_PTR_PTR9]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP14]], label %[[LAND_RHS:.*]], label %[[LAND_END37]], !annotation [[META1]]
// NEW:       [[LAND_RHS]]:
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP15]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR17:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR16]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB19:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR18]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP15]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB21:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR20]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[TOBOOL:%.*]] = icmp ne ptr [[WIDE_PTR_PTR17]], null, !annotation [[META1]]
// NEW-NEXT:    br i1 [[TOBOOL]], label %[[LOR_RHS:.*]], label %[[LOR_END:.*]], !annotation [[META1]]
// NEW:       [[LOR_RHS]]:
// NEW-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP22]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP22]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB24:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR23]], align 8, !annotation [[META1]]
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP25]], ptr align 8 [[PTR]], i64 24, i1 false), !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR26:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP25]], i32 0, i32 0, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_PTR27:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR26]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP25]], i32 0, i32 1, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_UB29:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR28]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR30:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP25]], i32 0, i32 2, !annotation [[META1]]
// NEW-NEXT:    [[WIDE_PTR_LB31:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR30]], align 8, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB24]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR27]] to i64, !annotation [[META1]]
// NEW-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META1]]
// NEW-NEXT:    [[CMP32:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_SUB]], !annotation [[META1]]
// NEW-NEXT:    br i1 [[CMP32]], label %[[LAND_RHS34:.*]], label %[[LAND_END:.*]], !annotation [[META1]]
// NEW:       [[LAND_RHS34]]:
// NEW-NEXT:    [[CMP35:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META1]]
// NEW-NEXT:    br label %[[LAND_END]], !annotation [[META1]]
// NEW:       [[LAND_END]]:
// NEW-NEXT:    [[TMP1:%.*]] = phi i1 [ false, %[[LOR_RHS]] ], [ [[CMP35]], %[[LAND_RHS34]] ]
// NEW-NEXT:    br label %[[LOR_END]], !annotation [[META1]]
// NEW:       [[LOR_END]]:
// NEW-NEXT:    [[TMP2:%.*]] = phi i1 [ true, %[[LAND_RHS]] ], [ [[TMP1]], %[[LAND_END]] ]
// NEW-NEXT:    br label %[[LAND_END37]], !annotation [[META1]]
// NEW:       [[LAND_END37]]:
// NEW-NEXT:    [[TMP3:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP2]], %[[LOR_END]] ], !annotation [[META1]]
// NEW-NEXT:    br i1 [[TMP3]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// NEW:       [[TRAP]]:
// NEW-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], !annotation [[META1]]
// NEW-NEXT:    unreachable, !annotation [[META1]]
// NEW:       [[CONT]]:
// NEW-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_SBON]], ptr [[C]], i32 0, i32 0
// NEW-NEXT:    store i32 [[TMP0]], ptr [[COUNT]], align 8
// NEW-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[C]], i64 4
// NEW-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP4]], i8 0, i64 4, i1 false)
// NEW-NEXT:    [[PTR38:%.*]] = getelementptr inbounds nuw [[STRUCT_SBON]], ptr [[C]], i32 0, i32 1
// NEW-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP39]], ptr align 8 [[PTR]], i64 24, i1 false)
// NEW-NEXT:    [[WIDE_PTR_PTR_ADDR40:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP39]], i32 0, i32 0
// NEW-NEXT:    [[WIDE_PTR_PTR41:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR40]], align 8
// NEW-NEXT:    [[WIDE_PTR_UB_ADDR42:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP39]], i32 0, i32 1
// NEW-NEXT:    [[WIDE_PTR_UB43:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR42]], align 8
// NEW-NEXT:    [[WIDE_PTR_LB_ADDR44:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP39]], i32 0, i32 2
// NEW-NEXT:    [[WIDE_PTR_LB45:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR44]], align 8
// NEW-NEXT:    store ptr [[WIDE_PTR_PTR41]], ptr [[PTR38]], align 8
// NEW-NEXT:    [[TMP5:%.*]] = load [2 x i64], ptr [[C]], align 8
// NEW-NEXT:    call void @consume_sbon([2 x i64] [[TMP5]])
// NEW-NEXT:    ret void
//
void compound_literal_init_sbon_bidi(int count_param, char*__bidi_indexable ptr) {
  struct sbon c = (struct sbon){.count = count_param, .ptr = ptr };
  consume_sbon(c);
}

#endif
//.
// SAME: [[META1]] = !{!"bounds-safety-generic"}
// SAME: [[META3]] = !{!"bounds-safety-check-ptr-neq-null"}
//.
// LEGACY: [[META1]] = !{!"bounds-safety-check-ptr-neq-null"}
//.
// NEW: [[META1]] = !{!"bounds-safety-generic"}
// NEW: [[META3]] = !{!"bounds-safety-check-ptr-neq-null"}
//.
