// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py


// RUN: %clang_cc1 %s -O2 -fbounds-safety -emit-llvm -triple x86_64 -o - | FileCheck %s
// RUN: %clang_cc1 %s -O2 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm -triple x86_64 -o - | FileCheck %s

#include <ptrcheck.h>

struct T {
    int cnt1;
    int cnt2;
    int *__counted_by(2 * cnt1 + 3 * cnt2) ptr;
};

// CHECK-LABEL: @TestOK(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
void TestOK() {
    int arr[16] = { 0 };
    struct T t;
    t.cnt1 = 5;
    t.cnt2 = 2;
    t.ptr = arr;
}

// CHECK-LABEL: @TestFail(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation !{{.*}}
// CHECK-NEXT:    unreachable
//
void TestFail() {
  int arr[16] = { 0 };
  int n = 7;
  struct T t;
  t.cnt1 = n;
  t.cnt2 = 1;
  t.ptr = arr;
}

// CHECK-LABEL: @TestOK2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
void TestOK2() {
  int arr[16] = { 0 };
  struct T t;
  t.cnt1 = 7;
  t.cnt2 = -1;
  t.ptr = arr;
}

// CHECK-LABEL: @TestFail2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation !{{.*}}
// CHECK-NEXT:    unreachable
//
void TestFail2() {
  int arr[16] = { 0 };
  int n = 7;
  struct T t;
  t.cnt1 = n;
  t.cnt2 = -5;
  t.ptr = arr;
}
