// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --version 5
// REQUIRES: system-darwin
// RUN: %clang_cc1 -O0 -triple arm64-apple-iphoneos -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O0 -triple arm64-apple-iphoneos -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

struct Inner {
    int dummy;
    int len;
};

struct Outer {
    struct Inner hdr;
    char fam[__counted_by(hdr.len)];
};

// CHECK-LABEL: define dso_local i8 @access(
// CHECK-SAME: ptr noundef [[BAR:%.*]], i32 noundef [[INDEX:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[BAR_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[INDEX_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    store ptr [[BAR]], ptr [[BAR_ADDR]], align 8
// CHECK-NEXT:    store i32 [[INDEX]], ptr [[INDEX_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[BAR_ADDR]], align 8
// CHECK-NEXT:    [[FAM:%.*]] = getelementptr inbounds nuw [[STRUCT_OUTER:%.*]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [0 x i8], ptr [[FAM]], i64 0, i64 0
// CHECK-NEXT:    [[FAM2:%.*]] = getelementptr inbounds nuw [[STRUCT_OUTER]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[ARRAYDECAY3:%.*]] = getelementptr inbounds [0 x i8], ptr [[FAM2]], i64 0, i64 0
// CHECK-NEXT:    [[HDR:%.*]] = getelementptr inbounds nuw [[STRUCT_OUTER]], ptr [[TMP0]], i32 0, i32 0
// CHECK-NEXT:    [[LEN:%.*]] = getelementptr inbounds nuw [[STRUCT_INNER:%.*]], ptr [[HDR]], i32 0, i32 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[LEN]], align 4
// CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP1]] to i64
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[ARRAYDECAY3]], i64 [[IDX_EXT]]
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP4]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP5]], align 8
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP6]], align 8
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP7]], align 8
// CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP8]], align 8
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR5:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR4]], align 8
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[INDEX_ADDR]], align 4
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP9]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i8, ptr [[WIDE_PTR_PTR5]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB7:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR6]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-NEXT:    [[TMP10:%.*]] = icmp ult ptr [[ARRAYIDX]], [[WIDE_PTR_UB7]], !annotation [[META1:![0-9]+]]
// CHECK-NEXT:    br i1 [[TMP10]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation [[META1]]
// CHECK-NEXT:    unreachable, !annotation [[META1]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    [[TMP11:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META3:![0-9]+]]
// CHECK-NEXT:    br i1 [[TMP11]], label %[[CONT9:.*]], label %[[TRAP8:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// CHECK:       [[TRAP8]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META3]]
// CHECK-NEXT:    unreachable, !annotation [[META3]]
// CHECK:       [[CONT9]]:
// CHECK-NEXT:    [[TMP12:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
// CHECK-NEXT:    ret i8 [[TMP12]]
//
char access(struct Outer *bar, int index) {
    return bar->fam[index];
}


// CHECK-LABEL: define dso_local ptr @assign(
// CHECK-SAME: ptr noundef dead_on_return [[BAR:%.*]], i32 noundef [[LEN:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[BAR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[LEN_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[S:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// CHECK-NEXT:    [[AGG_TEMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP3:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP10:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP42:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    store ptr [[BAR]], ptr [[BAR_INDIRECT_ADDR]], align 8
// CHECK-NEXT:    store i32 [[LEN]], ptr [[LEN_ADDR]], align 4
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[BAR]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP1]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB]], ptr [[TMP2]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[LEN_ADDR]], align 4
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP3]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP3]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR5:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR4]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP3]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB7:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR6]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP3]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB9:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR8]], align 8
// CHECK-NEXT:    [[FLEX_BASE_NULL_CHECK:%.*]] = icmp ne ptr [[WIDE_PTR_PTR5]], null, !annotation [[META4:![0-9]+]]
// CHECK-NEXT:    br i1 [[FLEX_BASE_NULL_CHECK]], label %[[FLEX_BASE_NONNULL:.*]], label %[[FLEX_BASE_NULL:.*]], !annotation [[META4]]
// CHECK:       [[FLEX_BASE_NONNULL]]:
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [[STRUCT_OUTER:%.*]], ptr [[WIDE_PTR_PTR5]], i64 1
// CHECK-NEXT:    [[TMP5:%.*]] = icmp ule ptr [[WIDE_PTR_PTR5]], [[TMP4]], !annotation [[META5:![0-9]+]]
// CHECK-NEXT:    br i1 [[TMP5]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META5]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META5]]
// CHECK-NEXT:    unreachable, !annotation [[META5]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP10]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP10]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR12:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR11]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP10]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB14:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR13]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR15:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP10]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB16:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR15]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = getelementptr [[STRUCT_OUTER]], ptr [[WIDE_PTR_PTR12]], i64 1
// CHECK-NEXT:    [[TMP7:%.*]] = icmp ule ptr [[TMP6]], [[WIDE_PTR_UB14]], !annotation [[META1]]
// CHECK-NEXT:    br i1 [[TMP7]], label %[[CONT18:.*]], label %[[TRAP17:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// CHECK:       [[TRAP17]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META1]]
// CHECK-NEXT:    unreachable, !annotation [[META1]]
// CHECK:       [[CONT18]]:
// CHECK-NEXT:    [[TMP8:%.*]] = icmp ule ptr [[WIDE_PTR_LB16]], [[WIDE_PTR_PTR12]], !annotation [[META3]]
// CHECK-NEXT:    br i1 [[TMP8]], label %[[CONT20:.*]], label %[[TRAP19:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// CHECK:       [[TRAP19]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META3]]
// CHECK-NEXT:    unreachable, !annotation [[META3]]
// CHECK:       [[CONT20]]:
// CHECK-NEXT:    [[FAM:%.*]] = getelementptr inbounds nuw [[STRUCT_OUTER]], ptr [[WIDE_PTR_PTR12]], i32 0, i32 1
// CHECK-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [0 x i8], ptr [[FAM]], i64 0, i64 0
// CHECK-NEXT:    [[FLEX_COUNT_MINUS:%.*]] = icmp sle i32 0, [[TMP3]], !annotation [[META6:![0-9]+]]
// CHECK-NEXT:    br i1 [[FLEX_COUNT_MINUS]], label %[[CONT22:.*]], label %[[TRAP21:.*]], {{!prof ![0-9]+}}, !annotation [[META6]]
// CHECK:       [[TRAP21]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META6]]
// CHECK-NEXT:    unreachable, !annotation [[META6]]
// CHECK:       [[CONT22]]:
// CHECK-NEXT:    [[TMP9:%.*]] = icmp ule ptr [[ARRAYDECAY]], [[WIDE_PTR_UB7]], !annotation [[META7:![0-9]+]]
// CHECK-NEXT:    br i1 [[TMP9]], label %[[CONT24:.*]], label %[[TRAP23:.*]], {{!prof ![0-9]+}}, !annotation [[META7]]
// CHECK:       [[TRAP23]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META7]]
// CHECK-NEXT:    unreachable, !annotation [[META7]]
// CHECK:       [[CONT24]]:
// CHECK-NEXT:    [[TMP10:%.*]] = icmp uge ptr [[WIDE_PTR_PTR5]], [[WIDE_PTR_LB9]], !annotation [[META8:![0-9]+]]
// CHECK-NEXT:    br i1 [[TMP10]], label %[[CONT26:.*]], label %[[TRAP25:.*]], {{!prof ![0-9]+}}, !annotation [[META8]]
// CHECK:       [[TRAP25]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META8]]
// CHECK-NEXT:    unreachable, !annotation [[META8]]
// CHECK:       [[CONT26]]:
// CHECK-NEXT:    [[UPPER_INTPTR:%.*]] = ptrtoint ptr [[WIDE_PTR_UB7]] to i64, !annotation [[META9:![0-9]+]]
// CHECK-NEXT:    [[FAM_INTPTR:%.*]] = ptrtoint ptr [[ARRAYDECAY]] to i64, !annotation [[META9]]
// CHECK-NEXT:    [[FLEX_AVAIL_COUNT:%.*]] = sub nuw i64 [[UPPER_INTPTR]], [[FAM_INTPTR]], !annotation [[META9]]
// CHECK-NEXT:    [[FLEX_COUNT_INTPTR:%.*]] = zext i32 [[TMP3]] to i64, !annotation [[META9]]
// CHECK-NEXT:    [[FLEX_COUNT_CHECK:%.*]] = icmp ule i64 [[FLEX_COUNT_INTPTR]], [[FLEX_AVAIL_COUNT]], !annotation [[META9]]
// CHECK-NEXT:    br i1 [[FLEX_COUNT_CHECK]], label %[[CONT28:.*]], label %[[TRAP27:.*]], {{!prof ![0-9]+}}, !annotation [[META9]]
// CHECK:       [[TRAP27]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META9]]
// CHECK-NEXT:    unreachable, !annotation [[META9]]
// CHECK:       [[CONT28]]:
// CHECK-NEXT:    br label %[[FLEX_BASE_NULL]]
// CHECK:       [[FLEX_BASE_NULL]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP2]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR29:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP2]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR30:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR29]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR31:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP2]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB32:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR31]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP2]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB34:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR33]], align 8
// CHECK-NEXT:    [[TMP11:%.*]] = icmp ne ptr [[WIDE_PTR_PTR30]], null, !annotation [[META4]]
// CHECK-NEXT:    br i1 [[TMP11]], label %[[BOUNDSCHECK_NOTNULL:.*]], label %[[BOUNDSCHECK_NULL:.*]], !annotation [[META4]]
// CHECK:       [[BOUNDSCHECK_NOTNULL]]:
// CHECK-NEXT:    [[TMP12:%.*]] = getelementptr [[STRUCT_OUTER]], ptr [[WIDE_PTR_PTR30]], i64 1, !annotation [[META10:![0-9]+]]
// CHECK-NEXT:    [[TMP13:%.*]] = icmp ule ptr [[TMP12]], [[WIDE_PTR_UB32]], !annotation [[META10]]
// CHECK-NEXT:    br i1 [[TMP13]], label %[[CONT36:.*]], label %[[TRAP35:.*]], {{!prof ![0-9]+}}, !annotation [[META10]]
// CHECK:       [[TRAP35]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META10]]
// CHECK-NEXT:    unreachable, !annotation [[META10]]
// CHECK:       [[CONT36]]:
// CHECK-NEXT:    [[TMP14:%.*]] = icmp ule ptr [[WIDE_PTR_PTR30]], [[TMP12]], !annotation [[META10]]
// CHECK-NEXT:    br i1 [[TMP14]], label %[[CONT38:.*]], label %[[TRAP37:.*]], {{!prof ![0-9]+}}, !annotation [[META10]]
// CHECK:       [[TRAP37]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META10]]
// CHECK-NEXT:    unreachable, !annotation [[META10]]
// CHECK:       [[CONT38]]:
// CHECK-NEXT:    [[TMP15:%.*]] = icmp uge ptr [[WIDE_PTR_PTR30]], [[WIDE_PTR_LB34]], !annotation [[META3]]
// CHECK-NEXT:    br i1 [[TMP15]], label %[[CONT40:.*]], label %[[TRAP39:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// CHECK:       [[TRAP39]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META3]]
// CHECK-NEXT:    unreachable, !annotation [[META3]]
// CHECK:       [[CONT40]]:
// CHECK-NEXT:    br label %[[BOUNDSCHECK_NULL]]
// CHECK:       [[BOUNDSCHECK_NULL]]:
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR30]], ptr [[S]], align 8
// CHECK-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[S]], align 8
// CHECK-NEXT:    [[HDR:%.*]] = getelementptr inbounds nuw [[STRUCT_OUTER]], ptr [[TMP16]], i32 0, i32 0
// CHECK-NEXT:    [[LEN41:%.*]] = getelementptr inbounds nuw [[STRUCT_INNER:%.*]], ptr [[HDR]], i32 0, i32 1
// CHECK-NEXT:    store i32 [[TMP3]], ptr [[LEN41]], align 4
// CHECK-NEXT:    [[TMP17:%.*]] = load ptr, ptr [[S]], align 8
// CHECK-NEXT:    [[TMP18:%.*]] = icmp ne ptr [[TMP17]], null, !annotation [[META4]]
// CHECK-NEXT:    br i1 [[TMP18]], label %[[BOUNDSCHECK_NOTNULL43:.*]], label %[[BOUNDSCHECK_NULL48:.*]], !annotation [[META4]]
// CHECK:       [[BOUNDSCHECK_NOTNULL43]]:
// CHECK-NEXT:    [[FAM44:%.*]] = getelementptr inbounds nuw [[STRUCT_OUTER]], ptr [[TMP17]], i32 0, i32 1
// CHECK-NEXT:    [[ARRAYDECAY45:%.*]] = getelementptr inbounds [0 x i8], ptr [[FAM44]], i64 0, i64 0
// CHECK-NEXT:    [[HDR46:%.*]] = getelementptr inbounds nuw [[STRUCT_OUTER]], ptr [[TMP17]], i32 0, i32 0
// CHECK-NEXT:    [[LEN47:%.*]] = getelementptr inbounds nuw [[STRUCT_INNER]], ptr [[HDR46]], i32 0, i32 1
// CHECK-NEXT:    [[TMP19:%.*]] = load i32, ptr [[LEN47]], align 4
// CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP19]] to i64
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[ARRAYDECAY45]], i64 [[IDX_EXT]]
// CHECK-NEXT:    [[TMP20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP42]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[TMP17]], ptr [[TMP20]], align 8
// CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP42]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP21]], align 8
// CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP42]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[TMP17]], ptr [[TMP22]], align 8
// CHECK-NEXT:    br label %[[BOUNDSCHECK_CONT:.*]]
// CHECK:       [[BOUNDSCHECK_NULL48]]:
// CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP42]], i32 0, i32 0
// CHECK-NEXT:    store ptr null, ptr [[TMP23]], align 8
// CHECK-NEXT:    [[TMP24:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP42]], i32 0, i32 1
// CHECK-NEXT:    store ptr null, ptr [[TMP24]], align 8
// CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP42]], i32 0, i32 2
// CHECK-NEXT:    store ptr null, ptr [[TMP25]], align 8
// CHECK-NEXT:    br label %[[BOUNDSCHECK_CONT]]
// CHECK:       [[BOUNDSCHECK_CONT]]:
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR49:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP42]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR50:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR49]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR51:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP42]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB52:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR51]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR53:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP42]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB54:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR53]], align 8
// CHECK-NEXT:    [[TMP26:%.*]] = icmp ne ptr [[WIDE_PTR_PTR50]], null, !annotation [[META4]]
// CHECK-NEXT:    br i1 [[TMP26]], label %[[BOUNDSCHECK_NOTNULL55:.*]], label %[[BOUNDSCHECK_NULL62:.*]], !annotation [[META4]]
// CHECK:       [[BOUNDSCHECK_NOTNULL55]]:
// CHECK-NEXT:    [[TMP27:%.*]] = getelementptr [[STRUCT_OUTER]], ptr [[WIDE_PTR_PTR50]], i64 1, !annotation [[META10]]
// CHECK-NEXT:    [[TMP28:%.*]] = icmp ule ptr [[TMP27]], [[WIDE_PTR_UB52]], !annotation [[META10]]
// CHECK-NEXT:    br i1 [[TMP28]], label %[[CONT57:.*]], label %[[TRAP56:.*]], {{!prof ![0-9]+}}, !annotation [[META10]]
// CHECK:       [[TRAP56]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META10]]
// CHECK-NEXT:    unreachable, !annotation [[META10]]
// CHECK:       [[CONT57]]:
// CHECK-NEXT:    [[TMP29:%.*]] = icmp ule ptr [[WIDE_PTR_PTR50]], [[TMP27]], !annotation [[META10]]
// CHECK-NEXT:    br i1 [[TMP29]], label %[[CONT59:.*]], label %[[TRAP58:.*]], {{!prof ![0-9]+}}, !annotation [[META10]]
// CHECK:       [[TRAP58]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META10]]
// CHECK-NEXT:    unreachable, !annotation [[META10]]
// CHECK:       [[CONT59]]:
// CHECK-NEXT:    [[TMP30:%.*]] = icmp uge ptr [[WIDE_PTR_PTR50]], [[WIDE_PTR_LB54]], !annotation [[META3]]
// CHECK-NEXT:    br i1 [[TMP30]], label %[[CONT61:.*]], label %[[TRAP60:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// CHECK:       [[TRAP60]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META3]]
// CHECK-NEXT:    unreachable, !annotation [[META3]]
// CHECK:       [[CONT61]]:
// CHECK-NEXT:    br label %[[BOUNDSCHECK_NULL62]]
// CHECK:       [[BOUNDSCHECK_NULL62]]:
// CHECK-NEXT:    ret ptr [[WIDE_PTR_PTR50]]
//
struct Outer * assign(void * __bidi_indexable bar, int len) {
    struct Outer * __single s = (struct Outer *) bar;
    s->hdr.len = len;
    return s;
}
//.
// CHECK: [[META1]] = !{!"bounds-safety-check-ptr-lt-upper-bound"}
// CHECK: [[META3]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
// CHECK: [[META4]] = !{!"bounds-safety-check-ptr-neq-null"}
// CHECK: [[META5]] = !{!"bounds-safety-check-one-past-end-overflow"}
// CHECK: [[META6]] = !{!"bounds-safety-check-count-negative"}
// CHECK: [[META7]] = !{!"bounds-safety-check-flexible-count-gt-bounds", !"bounds-safety-check-ptr-le-upper-bound"}
// CHECK: [[META8]] = !{!"bounds-safety-check-flexible-count-gt-bounds", !"bounds-safety-check-ptr-ge-lower-bound"}
// CHECK: [[META9]] = !{!"bounds-safety-check-flexible-count-gt-bounds"}
// CHECK: [[META10]] = !{!"bounds-safety-check-ptr-le-upper-bound"}
//.
