// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --version 5

// RUN: %clang_cc1 -O2 -fbounds-safety -triple arm64e-apple-ios -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

typedef struct {
  int count;
} header_t;

typedef struct {
  header_t header;
  char arr[__counted_by(header.count)];
} flex_t;

typedef struct {
  flex_t f;
} outer_flex_t;

void use(void *__unsafe_indexable);

// CHECK-LABEL: define void @process_frame(
// CHECK-SAME: ptr noundef [[FRAME:%.*]], i32 noundef [[FRAME_SIZE:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[IDX_EXT:%.*]] = zext i32 [[FRAME_SIZE]] to i64
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[FRAME]], i64 [[IDX_EXT]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[FRAME]], i64 4
// CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ugt ptr [[TMP0]], [[ADD_PTR]], !annotation [[META5:![0-9]+]]
// CHECK-NEXT:    br i1 [[DOTNOT]], label %[[TRAP:.*]], label %[[CONT10:.*]], {{!prof ![0-9]+}}, !annotation [[META5]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation [[META7:![0-9]+]]
// CHECK-NEXT:    unreachable, !annotation [[META7]]
// CHECK:       [[CONT10]]:
// CHECK-NEXT:    tail call void @use(ptr noundef [[FRAME]]) #[[ATTR4:[0-9]+]]
// CHECK-NEXT:    tail call void @use(ptr noundef [[TMP0]]) #[[ATTR4]]
// CHECK-NEXT:    tail call void @use(ptr noundef [[TMP0]]) #[[ATTR4]]
// CHECK-NEXT:    ret void
//
void process_frame(char *__counted_by(frame_size) frame, unsigned frame_size) {
  outer_flex_t *of = (outer_flex_t *) frame;
  use(&of->f);
  use(of->f.arr);
  use(&of->f.arr[0]);
}
//.
// CHECK: [[META5]] = !{!"bounds-safety-check-ptr-lt-upper-bound"}
// CHECK: [[META7]] = !{!"bounds-safety-check-ptr-lt-upper-bound", !"bounds-safety-check-ptr-ge-lower-bound"}
//.
