// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --version 6
// REQUIRES: system-darwin

// RUN: %clang_cc1 -O0 -fbounds-safety -emit-llvm -triple aarch64  %s -o - | FileCheck %s --check-prefix=NOPQ
// RUN: %clang_cc1 -opaque-pointers -O0  -fbounds-safety -emit-llvm -triple aarch64 %s -o - | FileCheck %s --check-prefixes=OPQ

#include <ptrcheck.h>

struct s1 {
  int dummy;
  _Bool flag;
};

// NOPQ-LABEL: define dso_local ptr @f1(
// NOPQ-SAME: ptr noundef [[P:%.*]]) #[[ATTR0:[0-9]+]] {
// NOPQ-NEXT:  [[ENTRY:.*:]]
// NOPQ-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// NOPQ-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NOPQ-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// NOPQ-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// NOPQ-NEXT:    [[TMP1:%.*]] = getelementptr inbounds [[STRUCT_S1:%.*]], ptr [[TMP0]], i32 0, i32 1
// NOPQ-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 1
// NOPQ-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// NOPQ-NEXT:    store ptr [[TMP1]], ptr [[TMP3]], align 8
// NOPQ-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// NOPQ-NEXT:    store ptr [[TMP2]], ptr [[TMP4]], align 8
// NOPQ-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// NOPQ-NEXT:    store ptr [[TMP1]], ptr [[TMP5]], align 8
// NOPQ-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// NOPQ-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// NOPQ-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// NOPQ-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// NOPQ-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// NOPQ-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// NOPQ-NEXT:    [[TMP6:%.*]] = icmp ne ptr [[WIDE_PTR_PTR]], null, !annotation [[META1:![0-9]+]]
// NOPQ-NEXT:    br i1 [[TMP6]], label %[[BOUNDSCHECK_NOTNULL:.*]], label %[[BOUNDSCHECK_NULL:.*]], !annotation [[META1]]
// NOPQ:       [[BOUNDSCHECK_NOTNULL]]:
// NOPQ-NEXT:    [[TMP7:%.*]] = icmp ult ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB]], !annotation [[META2:![0-9]+]]
// NOPQ-NEXT:    br i1 [[TMP7]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// NOPQ:       [[TRAP]]:
// NOPQ-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation [[META2]]
// NOPQ-NEXT:    unreachable, !annotation [[META2]]
// NOPQ:       [[CONT]]:
// NOPQ-NEXT:    [[TMP8:%.*]] = icmp uge ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_LB]], !annotation [[META4:![0-9]+]]
// NOPQ-NEXT:    br i1 [[TMP8]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// NOPQ:       [[TRAP1]]:
// NOPQ-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META4]]
// NOPQ-NEXT:    unreachable, !annotation [[META4]]
// NOPQ:       [[CONT2]]:
// NOPQ-NEXT:    br label %[[BOUNDSCHECK_NULL]]
// NOPQ:       [[BOUNDSCHECK_NULL]]:
// NOPQ-NEXT:    ret ptr [[WIDE_PTR_PTR]]
//
// OPQ-LABEL: define dso_local ptr @f1(
// OPQ-SAME: ptr noundef [[P:%.*]]) #[[ATTR0:[0-9]+]] {
// OPQ-NEXT:  [[ENTRY:.*:]]
// OPQ-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// OPQ-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OPQ-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// OPQ-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// OPQ-NEXT:    [[TMP1:%.*]] = getelementptr inbounds [[STRUCT_S1:%.*]], ptr [[TMP0]], i32 0, i32 1
// OPQ-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 1
// OPQ-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OPQ-NEXT:    store ptr [[TMP1]], ptr [[TMP3]], align 8
// OPQ-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OPQ-NEXT:    store ptr [[TMP2]], ptr [[TMP4]], align 8
// OPQ-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OPQ-NEXT:    store ptr [[TMP1]], ptr [[TMP5]], align 8
// OPQ-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OPQ-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// OPQ-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OPQ-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// OPQ-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OPQ-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// OPQ-NEXT:    [[TMP6:%.*]] = icmp ne ptr [[WIDE_PTR_PTR]], null, !annotation [[META1:![0-9]+]]
// OPQ-NEXT:    br i1 [[TMP6]], label %[[BOUNDSCHECK_NOTNULL:.*]], label %[[BOUNDSCHECK_NULL:.*]], !annotation [[META1]]
// OPQ:       [[BOUNDSCHECK_NOTNULL]]:
// OPQ-NEXT:    [[TMP7:%.*]] = icmp ult ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB]], !annotation [[META2:![0-9]+]]
// OPQ-NEXT:    br i1 [[TMP7]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// OPQ:       [[TRAP]]:
// OPQ-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation [[META2]]
// OPQ-NEXT:    unreachable, !annotation [[META2]]
// OPQ:       [[CONT]]:
// OPQ-NEXT:    [[TMP8:%.*]] = icmp uge ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_LB]], !annotation [[META4:![0-9]+]]
// OPQ-NEXT:    br i1 [[TMP8]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// OPQ:       [[TRAP1]]:
// OPQ-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META4]]
// OPQ-NEXT:    unreachable, !annotation [[META4]]
// OPQ:       [[CONT2]]:
// OPQ-NEXT:    br label %[[BOUNDSCHECK_NULL]]
// OPQ:       [[BOUNDSCHECK_NULL]]:
// OPQ-NEXT:    ret ptr [[WIDE_PTR_PTR]]
//
_Bool *f1(struct s1 *p) {
  return &p->flag;
}

// NOPQ-LABEL: define dso_local i1 @f2(
// NOPQ-SAME: ptr noundef dead_on_return [[P:%.*]], i32 noundef [[I:%.*]]) #[[ATTR0]] {
// NOPQ-NEXT:  [[ENTRY:.*:]]
// NOPQ-NEXT:    [[P_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// NOPQ-NEXT:    [[I_ADDR:%.*]] = alloca i32, align 4
// NOPQ-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NOPQ-NEXT:    store ptr [[P]], ptr [[P_INDIRECT_ADDR]], align 8
// NOPQ-NEXT:    store i32 [[I]], ptr [[I_ADDR]], align 4
// NOPQ-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[P]], i64 24, i1 false)
// NOPQ-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// NOPQ-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// NOPQ-NEXT:    [[TMP0:%.*]] = load i32, ptr [[I_ADDR]], align 4
// NOPQ-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP0]] to i64
// NOPQ-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i8, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// NOPQ-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// NOPQ-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// NOPQ-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// NOPQ-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// NOPQ-NEXT:    [[TMP1:%.*]] = icmp ult ptr [[ARRAYIDX]], [[WIDE_PTR_UB]], !annotation [[META2]]
// NOPQ-NEXT:    br i1 [[TMP1]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// NOPQ:       [[TRAP]]:
// NOPQ-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META2]]
// NOPQ-NEXT:    unreachable, !annotation [[META2]]
// NOPQ:       [[CONT]]:
// NOPQ-NEXT:    [[TMP2:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META4]]
// NOPQ-NEXT:    br i1 [[TMP2]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// NOPQ:       [[TRAP1]]:
// NOPQ-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META4]]
// NOPQ-NEXT:    unreachable, !annotation [[META4]]
// NOPQ:       [[CONT2]]:
// NOPQ-NEXT:    [[TMP3:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
// NOPQ-NEXT:    [[LOADEDV:%.*]] = icmp ne i8 [[TMP3]], 0
// NOPQ-NEXT:    ret i1 [[LOADEDV]]
//
// OPQ-LABEL: define dso_local i1 @f2(
// OPQ-SAME: ptr noundef dead_on_return [[P:%.*]], i32 noundef [[I:%.*]]) #[[ATTR0]] {
// OPQ-NEXT:  [[ENTRY:.*:]]
// OPQ-NEXT:    [[P_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// OPQ-NEXT:    [[I_ADDR:%.*]] = alloca i32, align 4
// OPQ-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OPQ-NEXT:    store ptr [[P]], ptr [[P_INDIRECT_ADDR]], align 8
// OPQ-NEXT:    store i32 [[I]], ptr [[I_ADDR]], align 4
// OPQ-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[P]], i64 24, i1 false)
// OPQ-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OPQ-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// OPQ-NEXT:    [[TMP0:%.*]] = load i32, ptr [[I_ADDR]], align 4
// OPQ-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP0]] to i64
// OPQ-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i8, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// OPQ-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OPQ-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// OPQ-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OPQ-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// OPQ-NEXT:    [[TMP1:%.*]] = icmp ult ptr [[ARRAYIDX]], [[WIDE_PTR_UB]], !annotation [[META2]]
// OPQ-NEXT:    br i1 [[TMP1]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// OPQ:       [[TRAP]]:
// OPQ-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META2]]
// OPQ-NEXT:    unreachable, !annotation [[META2]]
// OPQ:       [[CONT]]:
// OPQ-NEXT:    [[TMP2:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META4]]
// OPQ-NEXT:    br i1 [[TMP2]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// OPQ:       [[TRAP1]]:
// OPQ-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META4]]
// OPQ-NEXT:    unreachable, !annotation [[META4]]
// OPQ:       [[CONT2]]:
// OPQ-NEXT:    [[TMP3:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
// OPQ-NEXT:    [[LOADEDV:%.*]] = icmp ne i8 [[TMP3]], 0
// OPQ-NEXT:    ret i1 [[LOADEDV]]
//
_Bool f2(_Bool *__bidi_indexable p, int i) {
  return p[i];
}

// NOPQ-LABEL: define dso_local void @f3(
// NOPQ-SAME: ptr dead_on_unwind noalias writable sret(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 [[AGG_RESULT:%.*]], ptr noundef [[P:%.*]], i32 noundef [[SIZE:%.*]]) #[[ATTR0]] {
// NOPQ-NEXT:  [[ENTRY:.*:]]
// NOPQ-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// NOPQ-NEXT:    [[SIZE_ADDR:%.*]] = alloca i32, align 4
// NOPQ-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// NOPQ-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// NOPQ-NEXT:    store i32 [[SIZE]], ptr [[SIZE_ADDR]], align 4
// NOPQ-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// NOPQ-NEXT:    [[TMP1:%.*]] = load i32, ptr [[SIZE_ADDR]], align 4
// NOPQ-NEXT:    [[CONV:%.*]] = zext i32 [[TMP1]] to i64
// NOPQ-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[TMP0]], i64 [[CONV]]
// NOPQ-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// NOPQ-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// NOPQ-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// NOPQ-NEXT:    store ptr [[TMP2]], ptr [[TMP4]], align 8
// NOPQ-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// NOPQ-NEXT:    store ptr [[TMP0]], ptr [[TMP5]], align 8
// NOPQ-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// NOPQ-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// NOPQ-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// NOPQ-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// NOPQ-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// NOPQ-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// NOPQ-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 0
// NOPQ-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP6]], align 8
// NOPQ-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 1
// NOPQ-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP7]], align 8
// NOPQ-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 2
// NOPQ-NEXT:    store ptr [[WIDE_PTR_LB]], ptr [[TMP8]], align 8
// NOPQ-NEXT:    ret void
//
// OPQ-LABEL: define dso_local void @f3(
// OPQ-SAME: ptr dead_on_unwind noalias writable sret(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 [[AGG_RESULT:%.*]], ptr noundef [[P:%.*]], i32 noundef [[SIZE:%.*]]) #[[ATTR0]] {
// OPQ-NEXT:  [[ENTRY:.*:]]
// OPQ-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// OPQ-NEXT:    [[SIZE_ADDR:%.*]] = alloca i32, align 4
// OPQ-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// OPQ-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// OPQ-NEXT:    store i32 [[SIZE]], ptr [[SIZE_ADDR]], align 4
// OPQ-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// OPQ-NEXT:    [[TMP1:%.*]] = load i32, ptr [[SIZE_ADDR]], align 4
// OPQ-NEXT:    [[CONV:%.*]] = zext i32 [[TMP1]] to i64
// OPQ-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[TMP0]], i64 [[CONV]]
// OPQ-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// OPQ-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// OPQ-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// OPQ-NEXT:    store ptr [[TMP2]], ptr [[TMP4]], align 8
// OPQ-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// OPQ-NEXT:    store ptr [[TMP0]], ptr [[TMP5]], align 8
// OPQ-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// OPQ-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// OPQ-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// OPQ-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// OPQ-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP]], i32 0, i32 2
// OPQ-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// OPQ-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 0
// OPQ-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP6]], align 8
// OPQ-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 1
// OPQ-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP7]], align 8
// OPQ-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 2
// OPQ-NEXT:    store ptr [[WIDE_PTR_LB]], ptr [[TMP8]], align 8
// OPQ-NEXT:    ret void
//
_Bool *__bidi_indexable f3(_Bool *p, unsigned size) {
  return __unsafe_forge_bidi_indexable(_Bool *, p, size);
}

// NOPQ-LABEL: define dso_local [2 x i64] @f4(
// NOPQ-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// NOPQ-NEXT:  [[ENTRY:.*:]]
// NOPQ-NEXT:    [[RETVAL:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// NOPQ-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// NOPQ-NEXT:    [[TERMINATED_BY_LEN:%.*]] = alloca i64, align 8
// NOPQ-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// NOPQ-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// NOPQ-NEXT:    store i64 0, ptr [[TERMINATED_BY_LEN]], align 8
// NOPQ-NEXT:    br label %[[TERMINATED_BY_LOOP_COND:.*]]
// NOPQ:       [[TERMINATED_BY_LOOP_COND]]:
// NOPQ-NEXT:    [[TERMINATED_BY_LEN1:%.*]] = load i64, ptr [[TERMINATED_BY_LEN]], align 8
// NOPQ-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 [[TERMINATED_BY_LEN1]]
// NOPQ-NEXT:    [[TERMINATED_BY_ELEM:%.*]] = load i8, ptr [[TMP1]], align 1
// NOPQ-NEXT:    [[TERMINTED_BY_CHECK_TERMINATOR:%.*]] = icmp eq i8 [[TERMINATED_BY_ELEM]], 0
// NOPQ-NEXT:    br i1 [[TERMINTED_BY_CHECK_TERMINATOR]], label %[[TERMINATED_BY_LOOP_END:.*]], label %[[TERMINATED_BY_LOOP_CONT:.*]]
// NOPQ:       [[TERMINATED_BY_LOOP_CONT]]:
// NOPQ-NEXT:    [[TERMINATED_BY_NEW_LEN:%.*]] = add i64 [[TERMINATED_BY_LEN1]], 1
// NOPQ-NEXT:    store i64 [[TERMINATED_BY_NEW_LEN]], ptr [[TERMINATED_BY_LEN]], align 8
// NOPQ-NEXT:    br label %[[TERMINATED_BY_LOOP_COND]]
// NOPQ:       [[TERMINATED_BY_LOOP_END]]:
// NOPQ-NEXT:    [[TMP2:%.*]] = load i64, ptr [[TERMINATED_BY_LEN]], align 8
// NOPQ-NEXT:    [[TERMINATED_BY_UPPER:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 [[TMP2]]
// NOPQ-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 0
// NOPQ-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// NOPQ-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 1
// NOPQ-NEXT:    store ptr [[TERMINATED_BY_UPPER]], ptr [[TMP4]], align 8
// NOPQ-NEXT:    [[TMP5:%.*]] = load [2 x i64], ptr [[RETVAL]], align 8
// NOPQ-NEXT:    ret [2 x i64] [[TMP5]]
//
// OPQ-LABEL: define dso_local [2 x i64] @f4(
// OPQ-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// OPQ-NEXT:  [[ENTRY:.*:]]
// OPQ-NEXT:    [[RETVAL:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// OPQ-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// OPQ-NEXT:    [[TERMINATED_BY_LEN:%.*]] = alloca i64, align 8
// OPQ-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// OPQ-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// OPQ-NEXT:    store i64 0, ptr [[TERMINATED_BY_LEN]], align 8
// OPQ-NEXT:    br label %[[TERMINATED_BY_LOOP_COND:.*]]
// OPQ:       [[TERMINATED_BY_LOOP_COND]]:
// OPQ-NEXT:    [[TERMINATED_BY_LEN1:%.*]] = load i64, ptr [[TERMINATED_BY_LEN]], align 8
// OPQ-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 [[TERMINATED_BY_LEN1]]
// OPQ-NEXT:    [[TERMINATED_BY_ELEM:%.*]] = load i8, ptr [[TMP1]], align 1
// OPQ-NEXT:    [[TERMINTED_BY_CHECK_TERMINATOR:%.*]] = icmp eq i8 [[TERMINATED_BY_ELEM]], 0
// OPQ-NEXT:    br i1 [[TERMINTED_BY_CHECK_TERMINATOR]], label %[[TERMINATED_BY_LOOP_END:.*]], label %[[TERMINATED_BY_LOOP_CONT:.*]]
// OPQ:       [[TERMINATED_BY_LOOP_CONT]]:
// OPQ-NEXT:    [[TERMINATED_BY_NEW_LEN:%.*]] = add i64 [[TERMINATED_BY_LEN1]], 1
// OPQ-NEXT:    store i64 [[TERMINATED_BY_NEW_LEN]], ptr [[TERMINATED_BY_LEN]], align 8
// OPQ-NEXT:    br label %[[TERMINATED_BY_LOOP_COND]]
// OPQ:       [[TERMINATED_BY_LOOP_END]]:
// OPQ-NEXT:    [[TMP2:%.*]] = load i64, ptr [[TERMINATED_BY_LEN]], align 8
// OPQ-NEXT:    [[TERMINATED_BY_UPPER:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 [[TMP2]]
// OPQ-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 0
// OPQ-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// OPQ-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 1
// OPQ-NEXT:    store ptr [[TERMINATED_BY_UPPER]], ptr [[TMP4]], align 8
// OPQ-NEXT:    [[TMP5:%.*]] = load [2 x i64], ptr [[RETVAL]], align 8
// OPQ-NEXT:    ret [2 x i64] [[TMP5]]
//
_Bool *__indexable f4(_Bool *__null_terminated p) {
  return __null_terminated_to_indexable(p);
}

// NOPQ-LABEL: define dso_local void @f5(
// NOPQ-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// NOPQ-NEXT:  [[ENTRY:.*:]]
// NOPQ-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// NOPQ-NEXT:    [[L:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// NOPQ-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// NOPQ-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// NOPQ-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 1
// NOPQ-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[L]], i32 0, i32 0
// NOPQ-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 8
// NOPQ-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[L]], i32 0, i32 1
// NOPQ-NEXT:    store ptr [[UPPER]], ptr [[TMP2]], align 8
// NOPQ-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[L]], i32 0, i32 2
// NOPQ-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// NOPQ-NEXT:    ret void
//
// OPQ-LABEL: define dso_local void @f5(
// OPQ-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// OPQ-NEXT:  [[ENTRY:.*:]]
// OPQ-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// OPQ-NEXT:    [[L:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OPQ-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// OPQ-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// OPQ-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 1
// OPQ-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[L]], i32 0, i32 0
// OPQ-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 8
// OPQ-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[L]], i32 0, i32 1
// OPQ-NEXT:    store ptr [[UPPER]], ptr [[TMP2]], align 8
// OPQ-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[L]], i32 0, i32 2
// OPQ-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// OPQ-NEXT:    ret void
//
void f5(_Bool *p) {
  _Bool *l = p;
}

// no trap
// NOPQ-LABEL: define dso_local void @f6(
// NOPQ-SAME: ptr dead_on_unwind noalias writable sret(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 [[AGG_RESULT:%.*]], [2 x i64] noundef [[P_COERCE:%.*]]) #[[ATTR0]] {
// NOPQ-NEXT:  [[ENTRY:.*:]]
// NOPQ-NEXT:    [[P:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// NOPQ-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// NOPQ-NEXT:    store [2 x i64] [[P_COERCE]], ptr [[P]], align 8
// NOPQ-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[P]], i64 16, i1 false)
// NOPQ-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// NOPQ-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// NOPQ-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// NOPQ-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// NOPQ-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 0
// NOPQ-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP0]], align 8
// NOPQ-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 1
// NOPQ-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP1]], align 8
// NOPQ-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 2
// NOPQ-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP2]], align 8
// NOPQ-NEXT:    ret void
//
// OPQ-LABEL: define dso_local void @f6(
// OPQ-SAME: ptr dead_on_unwind noalias writable sret(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 [[AGG_RESULT:%.*]], [2 x i64] noundef [[P_COERCE:%.*]]) #[[ATTR0]] {
// OPQ-NEXT:  [[ENTRY:.*:]]
// OPQ-NEXT:    [[P:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// OPQ-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// OPQ-NEXT:    store [2 x i64] [[P_COERCE]], ptr [[P]], align 8
// OPQ-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[P]], i64 16, i1 false)
// OPQ-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OPQ-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// OPQ-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OPQ-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// OPQ-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 0
// OPQ-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP0]], align 8
// OPQ-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 1
// OPQ-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP1]], align 8
// OPQ-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_RESULT]], i32 0, i32 2
// OPQ-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP2]], align 8
// OPQ-NEXT:    ret void
//
_Bool *__bidi_indexable f6(_Bool *__indexable p) {
  return p;
}

//.
// NOPQ: [[META1]] = !{!"bounds-safety-check-ptr-neq-null"}
// NOPQ: [[META2]] = !{!"bounds-safety-check-ptr-lt-upper-bound"}
// NOPQ: [[META4]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
//.
// OPQ: [[META1]] = !{!"bounds-safety-check-ptr-neq-null"}
// OPQ: [[META2]] = !{!"bounds-safety-check-ptr-lt-upper-bound"}
// OPQ: [[META4]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
//.
