// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6


// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck --check-prefix=CHECK %s
// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefix=CHECK %s

#include <ptrcheck.h>
#include <stdint.h>

char buf[42];

uintptr_t buf_ptr = (uintptr_t)buf;

// CHECK-LABEL: define dso_local void @foo(
// CHECK-SAME: ptr noundef [[S:%.*]], ptr noundef [[I_COERCE0:%.*]], ptr noundef [[I_COERCE1:%.*]], ptr noundef byval(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 [[BI:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[I:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[S_PTR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[I_PTR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-NEXT:    [[BI_PTR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[I]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[I_COERCE0]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[I]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[I_COERCE1]], ptr [[TMP1]], align 8
// CHECK-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8
// CHECK-NEXT:    br label %[[_S:.*]]
// CHECK:       [[_S]]:
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[TMP2]] to i64
// CHECK-NEXT:    store i64 [[TMP3]], ptr [[S_PTR]], align 8
// CHECK-NEXT:    br label %[[_I:.*]]
// CHECK:       [[_I]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[I]], i64 16, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// CHECK-NEXT:    store i64 [[TMP4]], ptr [[I_PTR]], align 8
// CHECK-NEXT:    br label %[[_BI:.*]]
// CHECK:       [[_BI]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[BI]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR3:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR2]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB5:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR4]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR3]] to i64
// CHECK-NEXT:    store i64 [[TMP5]], ptr [[BI_PTR]], align 8
// CHECK-NEXT:    ret void
//
void foo(int *__single s, int *__indexable i, int *__bidi_indexable bi) {
_s:;
  uintptr_t s_ptr = (uintptr_t)s;
_i:;
  uintptr_t i_ptr = (uintptr_t)i;
_bi:;
  uintptr_t bi_ptr = (uintptr_t)bi;
}
