// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 3

// RUN: %clang_cc1 -triple arm64e -fbounds-safety -fptrauth-returns -fptrauth-calls -emit-llvm %s -o - | FileCheck --check-prefix NO_FPTR_DISC %s
// RUN: %clang_cc1 -triple arm64e -fbounds-safety -fptrauth-returns -fptrauth-calls -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefix NO_FPTR_DISC %s
// RUN: %clang_cc1 -triple arm64e -fbounds-safety -fptrauth-function-pointer-type-discrimination -fptrauth-returns -fptrauth-calls -emit-llvm %s -o - | FileCheck --check-prefix FPTR_DISC %s
// RUN: %clang_cc1 -triple arm64e -fbounds-safety -fptrauth-function-pointer-type-discrimination -fptrauth-returns -fptrauth-calls -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefix FPTR_DISC %s
// RUN: %clang_cc1 -triple arm64e -fptrauth-function-pointer-type-discrimination -fptrauth-returns -fptrauth-calls -emit-llvm %s -o - | FileCheck --check-prefix FPTR_DISC_NO_BOUNDS_SAFETY %s
// RUN: %clang_cc1 -triple arm64e -fptrauth-function-pointer-type-discrimination -fptrauth-returns -fptrauth-calls -x objective-c -emit-llvm %s -o - | FileCheck --check-prefix FPTR_DISC_NO_BOUNDS_SAFETY %s




#include <ptrauth.h>
#include <ptrcheck.h>

typedef void(*f_t)(void);

f_t __unsafe_indexable bar(void);

// NO_FPTR_DISC-LABEL: define dso_local ptr @foo
// NO_FPTR_DISC-SAME: () #[[ATTR0:[0-9]+]] {
// NO_FPTR_DISC-NEXT:  entry:
// NO_FPTR_DISC-NEXT:    [[CALL:%.*]] = call ptr @bar()
// NO_FPTR_DISC-NEXT:    ret ptr [[CALL]]
//
// FPTR_DISC-LABEL: define dso_local ptr @foo
// FPTR_DISC-SAME: () #[[ATTR0:[0-9]+]] {
// FPTR_DISC-NEXT:  entry:
// FPTR_DISC-NEXT:    [[CALL:%.*]] = call ptr @bar()
// FPTR_DISC-NEXT:    [[TMP0:%.*]] = icmp ne ptr [[CALL]], null
// FPTR_DISC-NEXT:    br i1 [[TMP0]], label [[RESIGN_NONNULL:%.*]], label [[RESIGN_CONT:%.*]]
// FPTR_DISC:       resign.nonnull:
// FPTR_DISC-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[CALL]] to i64
// FPTR_DISC-NEXT:    [[TMP2:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[TMP1]], i32 0, i64 18983, i32 0, i64 0)
// FPTR_DISC-NEXT:    [[TMP3:%.*]] = inttoptr i64 [[TMP2]] to ptr
// FPTR_DISC-NEXT:    br label [[RESIGN_CONT]]
// FPTR_DISC:       resign.cont:
// FPTR_DISC-NEXT:    [[TMP4:%.*]] = phi ptr [ null, [[ENTRY:%.*]] ], [ [[TMP3]], [[RESIGN_NONNULL]] ]
// FPTR_DISC-NEXT:    ret ptr [[TMP4]]
//
// FPTR_DISC_NO_BOUNDS_SAFETY-LABEL: define dso_local ptr @foo
// FPTR_DISC_NO_BOUNDS_SAFETY-SAME: () #[[ATTR0:[0-9]+]] {
// FPTR_DISC_NO_BOUNDS_SAFETY-NEXT:  entry:
// FPTR_DISC_NO_BOUNDS_SAFETY-NEXT:    [[CALL:%.*]] = call ptr @bar()
// FPTR_DISC_NO_BOUNDS_SAFETY-NEXT:    [[TMP0:%.*]] = icmp ne ptr [[CALL]], null
// FPTR_DISC_NO_BOUNDS_SAFETY-NEXT:    br i1 [[TMP0]], label [[RESIGN_NONNULL:%.*]], label [[RESIGN_CONT:%.*]]
// FPTR_DISC_NO_BOUNDS_SAFETY:       resign.nonnull:
// FPTR_DISC_NO_BOUNDS_SAFETY-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[CALL]] to i64
// FPTR_DISC_NO_BOUNDS_SAFETY-NEXT:    [[TMP2:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[TMP1]], i32 0, i64 18983, i32 0, i64 0)
// FPTR_DISC_NO_BOUNDS_SAFETY-NEXT:    [[TMP3:%.*]] = inttoptr i64 [[TMP2]] to ptr
// FPTR_DISC_NO_BOUNDS_SAFETY-NEXT:    br label [[RESIGN_CONT]]
// FPTR_DISC_NO_BOUNDS_SAFETY:       resign.cont:
// FPTR_DISC_NO_BOUNDS_SAFETY-NEXT:    [[TMP4:%.*]] = phi ptr [ null, [[ENTRY:%.*]] ], [ [[TMP3]], [[RESIGN_NONNULL]] ]
// FPTR_DISC_NO_BOUNDS_SAFETY-NEXT:    ret ptr [[TMP4]]
//
const char *foo(void) {
    return __unsafe_forge_null_terminated(char *, bar());
}
