// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!llvm.loop ![0-9]+" "#[0-9]+" "!prof ![0-9]+" --version 6

//
// RUN: %clang_cc1 -O2 -fbounds-safety -emit-llvm -triple x86_64 %s -o - | FileCheck %s

#include <ptrcheck.h>
#include <stdint.h>

int a[4];
int b[4];
int c[4];
int d[4];

// CHECK-LABEL: define dso_local i32 @read_from_global_array_can_remove_checks(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr @a, align 16, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr getelementptr inbounds nuw (i8, ptr @a, i64 4), align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ADD_1:%.*]] = add nsw i32 [[TMP1]], [[TMP0]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr getelementptr inbounds nuw (i8, ptr @a, i64 8), align 8, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ADD_2:%.*]] = add nsw i32 [[TMP2]], [[ADD_1]]
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr getelementptr inbounds nuw (i8, ptr @a, i64 12), align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ADD_3:%.*]] = add nsw i32 [[TMP3]], [[ADD_2]]
// CHECK-NEXT:    ret i32 [[ADD_3]]
//
int read_from_global_array_can_remove_checks() {
    int res = 0;
  for (unsigned char i = 0; i < 4; i++) {
    res += a[i];
  }
  return res;
}

// CHECK-LABEL: define dso_local noundef i32 @read_from_global_array_trap_last_iter(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[TRAP:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) {{#[0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
int read_from_global_array_trap_last_iter() {
    int res = 0;
  for (unsigned char i = 0; i < 5; i++) {
    res += a[i];
  }
  return res;
}

// CHECK-LABEL: define dso_local i32 @read_from_global_array_cannot_rename(
// CHECK-SAME: i32 noundef [[N:%.*]]) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[CMP9_NOT:%.*]] = icmp eq i32 [[N]], 0
// CHECK-NEXT:    br i1 [[CMP9_NOT]], label %[[FOR_COND_CLEANUP:.*]], label %[[FOR_BODY:.*]]
// CHECK:       [[FOR_COND_CLEANUP]]:
// CHECK-NEXT:    [[RES_0_LCSSA:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ADD:%.*]], %[[CONT3:.*]] ]
// CHECK-NEXT:    ret i32 [[RES_0_LCSSA]]
// CHECK:       [[FOR_BODY]]:
// CHECK-NEXT:    [[I_011:%.*]] = phi i8 [ [[INC:%.*]], %[[CONT3]] ], [ 0, %[[ENTRY]] ]
// CHECK-NEXT:    [[RES_010:%.*]] = phi i32 [ [[ADD]], %[[CONT3]] ], [ 0, %[[ENTRY]] ]
// CHECK-NEXT:    [[IDXPROM:%.*]] = zext i8 [[I_011]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [4 x i8], ptr @a, i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[ARRAYIDX]], i64 4, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], getelementptr inbounds nuw (i8, ptr @a, i64 16), {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = and i1 [[TMP1]], [[TMP2]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP3:%.*]] = icmp uge ptr [[ARRAYIDX]], @a, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND4:%.*]] = and i1 [[TMP3]], [[OR_COND]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND4]], label %[[CONT3]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) {{#[0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT3]]:
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ADD]] = add nsw i32 [[TMP4]], [[RES_010]]
// CHECK-NEXT:    [[INC]] = add i8 [[I_011]], 1, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[INC]] to i32
// CHECK-NEXT:    [[CMP:%.*]] = icmp ugt i32 [[N]], [[CONV]]
// CHECK-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_COND_CLEANUP]], {{!llvm.loop ![0-9]+}}
//
int read_from_global_array_cannot_rename(unsigned n) {
    int res = 0;
  for (unsigned char i = 0; i < n; i++) {
    res += a[i];
  }
  return res;
}

typedef struct {
  uint16_t len;
  uint16_t offset;
  uint8_t payload[__counted_by(offset + len)];
} hdr_t;

// CHECK-LABEL: define dso_local void @concat_to_separate_clobals(
// CHECK-SAME: ptr noundef readonly captures(address) [[P_BUF:%.*]]) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[PAYLOAD:%.*]] = getelementptr inbounds nuw i8, ptr [[P_BUF]], i64 4
// CHECK-NEXT:    [[OFFSET:%.*]] = getelementptr inbounds nuw i8, ptr [[P_BUF]], i64 2
// CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[OFFSET]], align 2, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV:%.*]] = zext i16 [[TMP0]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[P_BUF]], align 2, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV3:%.*]] = zext i16 [[TMP1]] to i64
// CHECK-NEXT:    [[TMP2:%.*]] = add nuw nsw i64 [[CONV]], [[CONV3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[PAYLOAD]], i64 [[TMP2]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 7
// CHECK-NEXT:    [[CMP14_NOT:%.*]] = icmp ule ptr [[BOUND_PTR_ARITH]], [[ADD_PTR]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP26_NOT:%.*]] = icmp uge ptr [[BOUND_PTR_ARITH]], [[PAYLOAD]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND136_NOT138:%.*]] = and i1 [[CMP14_NOT]], [[CMP26_NOT]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP38:%.*]] = icmp samesign ugt i64 [[TMP2]], 6, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND137:%.*]] = and i1 [[OR_COND136_NOT138]], [[CMP38]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND137]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) {{#[0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 10
// CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[ARRAYIDX]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV59:%.*]] = zext i8 [[TMP3]] to i32
// CHECK-NEXT:    store i32 [[CONV59]], ptr @a, align 16, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX68:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 8
// CHECK-NEXT:    [[TMP4:%.*]] = load i8, ptr [[ARRAYIDX68]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV75:%.*]] = zext i8 [[TMP4]] to i32
// CHECK-NEXT:    store i32 [[CONV75]], ptr @b, align 16, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX85:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 9
// CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[ARRAYIDX85]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV92:%.*]] = zext i8 [[TMP5]] to i32
// CHECK-NEXT:    store i32 [[CONV92]], ptr @c, align 16, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[BOUND_PTR_ARITH]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV109:%.*]] = zext i8 [[TMP6]] to i32
// CHECK-NEXT:    store i32 [[CONV109]], ptr @d, align 16, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP38_1:%.*]] = icmp samesign ugt i64 [[TMP2]], 10, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP38_1]], label %[[CONT_1:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT_1]]:
// CHECK-NEXT:    [[ADD_PTR50:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 11
// CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 14
// CHECK-NEXT:    [[TMP7:%.*]] = load i8, ptr [[ARRAYIDX_1]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV59_1:%.*]] = zext i8 [[TMP7]] to i32
// CHECK-NEXT:    store i32 [[CONV59_1]], ptr getelementptr inbounds nuw (i8, ptr @a, i64 4), align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX68_1:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 12
// CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[ARRAYIDX68_1]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV75_1:%.*]] = zext i8 [[TMP8]] to i32
// CHECK-NEXT:    store i32 [[CONV75_1]], ptr getelementptr inbounds nuw (i8, ptr @b, i64 4), align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX85_1:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 13
// CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[ARRAYIDX85_1]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV92_1:%.*]] = zext i8 [[TMP9]] to i32
// CHECK-NEXT:    store i32 [[CONV92_1]], ptr getelementptr inbounds nuw (i8, ptr @c, i64 4), align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[TMP10:%.*]] = load i8, ptr [[ADD_PTR50]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV109_1:%.*]] = zext i8 [[TMP10]] to i32
// CHECK-NEXT:    store i32 [[CONV109_1]], ptr getelementptr inbounds nuw (i8, ptr @d, i64 4), align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP38_2:%.*]] = icmp samesign ugt i64 [[TMP2]], 14, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP38_2]], label %[[CONT_2:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT_2]]:
// CHECK-NEXT:    [[ADD_PTR50_1:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 15
// CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 18
// CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[ARRAYIDX_2]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV59_2:%.*]] = zext i8 [[TMP11]] to i32
// CHECK-NEXT:    store i32 [[CONV59_2]], ptr getelementptr inbounds nuw (i8, ptr @a, i64 8), align 8, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX68_2:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 16
// CHECK-NEXT:    [[TMP12:%.*]] = load i8, ptr [[ARRAYIDX68_2]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV75_2:%.*]] = zext i8 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[CONV75_2]], ptr getelementptr inbounds nuw (i8, ptr @b, i64 8), align 8, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX85_2:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 17
// CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[ARRAYIDX85_2]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV92_2:%.*]] = zext i8 [[TMP13]] to i32
// CHECK-NEXT:    store i32 [[CONV92_2]], ptr getelementptr inbounds nuw (i8, ptr @c, i64 8), align 8, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[TMP14:%.*]] = load i8, ptr [[ADD_PTR50_1]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV109_2:%.*]] = zext i8 [[TMP14]] to i32
// CHECK-NEXT:    store i32 [[CONV109_2]], ptr getelementptr inbounds nuw (i8, ptr @d, i64 8), align 8, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP38_3:%.*]] = icmp samesign ugt i64 [[TMP2]], 18, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP38_3]], label %[[CONT_3:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT_3]]:
// CHECK-NEXT:    [[ADD_PTR50_2:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 19
// CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 22
// CHECK-NEXT:    [[TMP15:%.*]] = load i8, ptr [[ARRAYIDX_3]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV59_3:%.*]] = zext i8 [[TMP15]] to i32
// CHECK-NEXT:    store i32 [[CONV59_3]], ptr getelementptr inbounds nuw (i8, ptr @a, i64 12), align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX68_3:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 20
// CHECK-NEXT:    [[TMP16:%.*]] = load i8, ptr [[ARRAYIDX68_3]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV75_3:%.*]] = zext i8 [[TMP16]] to i32
// CHECK-NEXT:    store i32 [[CONV75_3]], ptr getelementptr inbounds nuw (i8, ptr @b, i64 12), align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX85_3:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 21
// CHECK-NEXT:    [[TMP17:%.*]] = load i8, ptr [[ARRAYIDX85_3]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV92_3:%.*]] = zext i8 [[TMP17]] to i32
// CHECK-NEXT:    store i32 [[CONV92_3]], ptr getelementptr inbounds nuw (i8, ptr @c, i64 12), align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[TMP18:%.*]] = load i8, ptr [[ADD_PTR50_2]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV109_3:%.*]] = zext i8 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[CONV109_3]], ptr getelementptr inbounds nuw (i8, ptr @d, i64 12), align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    ret void
//
void concat_to_separate_clobals(hdr_t *p_buf) {
  uint8_t *params = p_buf->payload + 3;
  for (unsigned char i = 0; i < 4; i++) {
    uint8_t *__counted_by(4) p = params;
    a[i] = p[3]; // checks not removed for p[]
    b[i] = p[1]; // checks not removed for b[] and p[]
    c[i] = p[2]; // checks not removed for c[] and p[]
    d[i] = p[0]; // checks not removed for d[]
    params += 4;
  }
}

struct arrays {
  int a[4];
  int b[4];
  int c[4];
  int d[4];
};

// CHECK-LABEL: define dso_local void @concat_to_arrays_struct_can_remove_arrays_check(
// CHECK-SAME: ptr noundef writeonly captures(none) [[ARRAYS:%.*]], ptr noundef readonly captures(address) [[P_BUF:%.*]]) local_unnamed_addr #[[ATTR5:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[PAYLOAD:%.*]] = getelementptr inbounds nuw i8, ptr [[P_BUF]], i64 4
// CHECK-NEXT:    [[OFFSET:%.*]] = getelementptr inbounds nuw i8, ptr [[P_BUF]], i64 2
// CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[OFFSET]], align 2, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV:%.*]] = zext i16 [[TMP0]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[P_BUF]], align 2, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV3:%.*]] = zext i16 [[TMP1]] to i64
// CHECK-NEXT:    [[TMP2:%.*]] = add nuw nsw i64 [[CONV]], [[CONV3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[PAYLOAD]], i64 [[TMP2]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 7
// CHECK-NEXT:    [[CMP14_NOT:%.*]] = icmp ule ptr [[BOUND_PTR_ARITH]], [[ADD_PTR]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP26_NOT:%.*]] = icmp uge ptr [[BOUND_PTR_ARITH]], [[PAYLOAD]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND146_NOT148:%.*]] = and i1 [[CMP14_NOT]], [[CMP26_NOT]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP38:%.*]] = icmp samesign ugt i64 [[TMP2]], 6, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND147:%.*]] = and i1 [[OR_COND146_NOT148]], [[CMP38]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND147]], label %[[CONT121:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) {{#[0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT121]]:
// CHECK-NEXT:    [[UPPER97:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYS]], i64 48
// CHECK-NEXT:    [[UPPER78:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYS]], i64 32
// CHECK-NEXT:    [[UPPER:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYS]], i64 16
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 10
// CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[ARRAYIDX]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV59:%.*]] = zext i8 [[TMP3]] to i32
// CHECK-NEXT:    store i32 [[CONV59]], ptr [[ARRAYS]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX69:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 8
// CHECK-NEXT:    [[TMP4:%.*]] = load i8, ptr [[ARRAYIDX69]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV76:%.*]] = zext i8 [[TMP4]] to i32
// CHECK-NEXT:    store i32 [[CONV76]], ptr [[UPPER]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX88:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 9
// CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[ARRAYIDX88]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV95:%.*]] = zext i8 [[TMP5]] to i32
// CHECK-NEXT:    store i32 [[CONV95]], ptr [[UPPER78]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[BOUND_PTR_ARITH]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV114:%.*]] = zext i8 [[TMP6]] to i32
// CHECK-NEXT:    store i32 [[CONV114]], ptr [[UPPER97]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP38_1:%.*]] = icmp samesign ugt i64 [[TMP2]], 10, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP38_1]], label %[[CONT121_1:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT121_1]]:
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 52
// CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 36
// CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 20
// CHECK-NEXT:    [[ADD_PTR50:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 11
// CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 14
// CHECK-NEXT:    [[ARRAYIDX61_1:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 4
// CHECK-NEXT:    [[TMP10:%.*]] = load i8, ptr [[ARRAYIDX_1]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV59_1:%.*]] = zext i8 [[TMP10]] to i32
// CHECK-NEXT:    store i32 [[CONV59_1]], ptr [[ARRAYIDX61_1]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX69_1:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 12
// CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[ARRAYIDX69_1]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV76_1:%.*]] = zext i8 [[TMP11]] to i32
// CHECK-NEXT:    store i32 [[CONV76_1]], ptr [[TMP9]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX88_1:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 13
// CHECK-NEXT:    [[TMP12:%.*]] = load i8, ptr [[ARRAYIDX88_1]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV95_1:%.*]] = zext i8 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[CONV95_1]], ptr [[TMP8]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[ADD_PTR50]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV114_1:%.*]] = zext i8 [[TMP13]] to i32
// CHECK-NEXT:    store i32 [[CONV114_1]], ptr [[TMP7]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP38_2:%.*]] = icmp samesign ugt i64 [[TMP2]], 14, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP38_2]], label %[[CONT121_2:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT121_2]]:
// CHECK-NEXT:    [[ADD_PTR50_1:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 15
// CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 18
// CHECK-NEXT:    [[ARRAYIDX61_2:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 8
// CHECK-NEXT:    [[TMP14:%.*]] = load i8, ptr [[ARRAYIDX_2]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV59_2:%.*]] = zext i8 [[TMP14]] to i32
// CHECK-NEXT:    store i32 [[CONV59_2]], ptr [[ARRAYIDX61_2]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX80_2:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 24
// CHECK-NEXT:    [[ARRAYIDX69_2:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 16
// CHECK-NEXT:    [[TMP15:%.*]] = load i8, ptr [[ARRAYIDX69_2]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV76_2:%.*]] = zext i8 [[TMP15]] to i32
// CHECK-NEXT:    store i32 [[CONV76_2]], ptr [[ARRAYIDX80_2]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX99_2:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 40
// CHECK-NEXT:    [[ARRAYIDX88_2:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 17
// CHECK-NEXT:    [[TMP16:%.*]] = load i8, ptr [[ARRAYIDX88_2]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV95_2:%.*]] = zext i8 [[TMP16]] to i32
// CHECK-NEXT:    store i32 [[CONV95_2]], ptr [[ARRAYIDX99_2]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX118_2:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 56
// CHECK-NEXT:    [[TMP17:%.*]] = load i8, ptr [[ADD_PTR50_1]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV114_2:%.*]] = zext i8 [[TMP17]] to i32
// CHECK-NEXT:    store i32 [[CONV114_2]], ptr [[ARRAYIDX118_2]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP38_3:%.*]] = icmp samesign ugt i64 [[TMP2]], 18, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP38_3]], label %[[CONT121_3:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT121_3]]:
// CHECK-NEXT:    [[ADD_PTR50_2:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 19
// CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 22
// CHECK-NEXT:    [[ARRAYIDX61_3:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 12
// CHECK-NEXT:    [[TMP18:%.*]] = load i8, ptr [[ARRAYIDX_3]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV59_3:%.*]] = zext i8 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[CONV59_3]], ptr [[ARRAYIDX61_3]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX80_3:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 28
// CHECK-NEXT:    [[ARRAYIDX69_3:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 20
// CHECK-NEXT:    [[TMP19:%.*]] = load i8, ptr [[ARRAYIDX69_3]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV76_3:%.*]] = zext i8 [[TMP19]] to i32
// CHECK-NEXT:    store i32 [[CONV76_3]], ptr [[ARRAYIDX80_3]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX99_3:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 44
// CHECK-NEXT:    [[ARRAYIDX88_3:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 21
// CHECK-NEXT:    [[TMP20:%.*]] = load i8, ptr [[ARRAYIDX88_3]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV95_3:%.*]] = zext i8 [[TMP20]] to i32
// CHECK-NEXT:    store i32 [[CONV95_3]], ptr [[ARRAYIDX99_3]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX118_3:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 60
// CHECK-NEXT:    [[TMP21:%.*]] = load i8, ptr [[ADD_PTR50_2]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV114_3:%.*]] = zext i8 [[TMP21]] to i32
// CHECK-NEXT:    store i32 [[CONV114_3]], ptr [[ARRAYIDX118_3]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    ret void
//
void concat_to_arrays_struct_can_remove_arrays_check(struct arrays *arrays, hdr_t *p_buf) {
  uint8_t *params = p_buf->payload + 3;

  for (unsigned char i = 0; i < 4; i++) {
    uint8_t *__counted_by(4) p = params;
    arrays->a[i] = p[3]; // checks not removed for p[]
    arrays->b[i] = p[1]; // checks not removed for b[] and p[]
    arrays->c[i] = p[2]; // checks not removed for c[] and p[]
    arrays->d[i] = p[0]; // checks not removed for d[]
    params += 4;
  }
}

// CHECK-LABEL: define dso_local void @concat_to_arrays_struct_trap_on_last_iter(
// CHECK-SAME: ptr noundef writeonly captures(address) [[ARRAYS:%.*]], ptr noundef readonly captures(address) [[P_BUF:%.*]]) local_unnamed_addr #[[ATTR6:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[PAYLOAD:%.*]] = getelementptr inbounds nuw i8, ptr [[P_BUF]], i64 4
// CHECK-NEXT:    [[OFFSET:%.*]] = getelementptr inbounds nuw i8, ptr [[P_BUF]], i64 2
// CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[OFFSET]], align 2, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV:%.*]] = zext i16 [[TMP0]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[P_BUF]], align 2, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV3:%.*]] = zext i16 [[TMP1]] to i64
// CHECK-NEXT:    [[TMP2:%.*]] = add nuw nsw i64 [[CONV]], [[CONV3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[PAYLOAD]], i64 [[TMP2]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 7
// CHECK-NEXT:    [[UPPER:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 16
// CHECK-NEXT:    [[UPPER78:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYS]], i64 32
// CHECK-NEXT:    [[UPPER97:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYS]], i64 48
// CHECK-NEXT:    [[CMP14_NOT:%.*]] = icmp ule ptr [[BOUND_PTR_ARITH]], [[ADD_PTR]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP26_NOT:%.*]] = icmp uge ptr [[BOUND_PTR_ARITH]], [[PAYLOAD]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND146_NOT148:%.*]] = and i1 [[CMP14_NOT]], [[CMP26_NOT]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP38:%.*]] = icmp samesign ugt i64 [[TMP2]], 6, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND147:%.*]] = and i1 [[OR_COND146_NOT148]], [[CMP38]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND147]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) {{#[0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    [[ADD_PTR50:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 11
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 4
// CHECK-NEXT:    [[TMP4:%.*]] = icmp ule ptr [[TMP3]], [[UPPER]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP5:%.*]] = icmp ule ptr [[ARRAYS]], [[TMP3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND124:%.*]] = and i1 [[TMP4]], [[TMP5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND124]], label %[[CONT121:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT121]]:
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 10
// CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[ARRAYIDX]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV59:%.*]] = zext i8 [[TMP6]] to i32
// CHECK-NEXT:    store i32 [[CONV59]], ptr [[ARRAYS]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX69:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 8
// CHECK-NEXT:    [[TMP7:%.*]] = load i8, ptr [[ARRAYIDX69]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV76:%.*]] = zext i8 [[TMP7]] to i32
// CHECK-NEXT:    store i32 [[CONV76]], ptr [[UPPER]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX88:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 9
// CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[ARRAYIDX88]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV95:%.*]] = zext i8 [[TMP8]] to i32
// CHECK-NEXT:    store i32 [[CONV95]], ptr [[UPPER78]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[BOUND_PTR_ARITH]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV114:%.*]] = zext i8 [[TMP9]] to i32
// CHECK-NEXT:    store i32 [[CONV114]], ptr [[UPPER97]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP38_1:%.*]] = icmp samesign ugt i64 [[TMP2]], 10, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP38_1]], label %[[CONT121_1:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT121_1]]:
// CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 52
// CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 36
// CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 20
// CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 14
// CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[ARRAYIDX_1]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV59_1:%.*]] = zext i8 [[TMP13]] to i32
// CHECK-NEXT:    store i32 [[CONV59_1]], ptr [[TMP3]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX69_1:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 12
// CHECK-NEXT:    [[TMP14:%.*]] = load i8, ptr [[ARRAYIDX69_1]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV76_1:%.*]] = zext i8 [[TMP14]] to i32
// CHECK-NEXT:    store i32 [[CONV76_1]], ptr [[TMP12]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX88_1:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 13
// CHECK-NEXT:    [[TMP15:%.*]] = load i8, ptr [[ARRAYIDX88_1]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV95_1:%.*]] = zext i8 [[TMP15]] to i32
// CHECK-NEXT:    store i32 [[CONV95_1]], ptr [[TMP11]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[TMP16:%.*]] = load i8, ptr [[ADD_PTR50]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV114_1:%.*]] = zext i8 [[TMP16]] to i32
// CHECK-NEXT:    store i32 [[CONV114_1]], ptr [[TMP10]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP38_2:%.*]] = icmp samesign ugt i64 [[TMP2]], 14, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP38_2]], label %[[CONT121_2:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT121_2]]:
// CHECK-NEXT:    [[ADD_PTR50_1:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 15
// CHECK-NEXT:    [[ARRAYIDX61_2:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 8
// CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 18
// CHECK-NEXT:    [[TMP17:%.*]] = load i8, ptr [[ARRAYIDX_2]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV59_2:%.*]] = zext i8 [[TMP17]] to i32
// CHECK-NEXT:    store i32 [[CONV59_2]], ptr [[ARRAYIDX61_2]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX80_2:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 24
// CHECK-NEXT:    [[ARRAYIDX69_2:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 16
// CHECK-NEXT:    [[TMP18:%.*]] = load i8, ptr [[ARRAYIDX69_2]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV76_2:%.*]] = zext i8 [[TMP18]] to i32
// CHECK-NEXT:    store i32 [[CONV76_2]], ptr [[ARRAYIDX80_2]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX99_2:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 40
// CHECK-NEXT:    [[ARRAYIDX88_2:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 17
// CHECK-NEXT:    [[TMP19:%.*]] = load i8, ptr [[ARRAYIDX88_2]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV95_2:%.*]] = zext i8 [[TMP19]] to i32
// CHECK-NEXT:    store i32 [[CONV95_2]], ptr [[ARRAYIDX99_2]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX118_2:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 56
// CHECK-NEXT:    [[TMP20:%.*]] = load i8, ptr [[ADD_PTR50_1]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV114_2:%.*]] = zext i8 [[TMP20]] to i32
// CHECK-NEXT:    store i32 [[CONV114_2]], ptr [[ARRAYIDX118_2]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CMP38_3:%.*]] = icmp samesign ugt i64 [[TMP2]], 18, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[CMP38_3]], label %[[CONT121_3:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT121_3]]:
// CHECK-NEXT:    [[ADD_PTR50_2:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 19
// CHECK-NEXT:    [[ARRAYIDX61_3:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 12
// CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 22
// CHECK-NEXT:    [[TMP21:%.*]] = load i8, ptr [[ARRAYIDX_3]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV59_3:%.*]] = zext i8 [[TMP21]] to i32
// CHECK-NEXT:    store i32 [[CONV59_3]], ptr [[ARRAYIDX61_3]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX80_3:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 28
// CHECK-NEXT:    [[ARRAYIDX69_3:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 20
// CHECK-NEXT:    [[TMP22:%.*]] = load i8, ptr [[ARRAYIDX69_3]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV76_3:%.*]] = zext i8 [[TMP22]] to i32
// CHECK-NEXT:    store i32 [[CONV76_3]], ptr [[ARRAYIDX80_3]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX99_3:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 44
// CHECK-NEXT:    [[ARRAYIDX88_3:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 21
// CHECK-NEXT:    [[TMP23:%.*]] = load i8, ptr [[ARRAYIDX88_3]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV95_3:%.*]] = zext i8 [[TMP23]] to i32
// CHECK-NEXT:    store i32 [[CONV95_3]], ptr [[ARRAYIDX99_3]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX118_3:%.*]] = getelementptr i8, ptr [[ARRAYS]], i64 60
// CHECK-NEXT:    [[TMP24:%.*]] = load i8, ptr [[ADD_PTR50_2]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV114_3:%.*]] = zext i8 [[TMP24]] to i32
// CHECK-NEXT:    store i32 [[CONV114_3]], ptr [[ARRAYIDX118_3]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    br label %[[TRAP]], {{!annotation ![0-9]+}}
//
void concat_to_arrays_struct_trap_on_last_iter(struct arrays *arrays, hdr_t *p_buf) {
  uint8_t *params = p_buf->payload + 3;

  for (unsigned char i = 0; i < 5; i++) {
    uint8_t *__counted_by(4) p = params;
    arrays->a[i] = p[3]; // checks not removed for p[]
    arrays->b[i] = p[1]; // checks not removed for b[] and p[]
    arrays->c[i] = p[2]; // checks not removed for c[] and p[]
    arrays->d[i] = p[0]; // checks not removed for d[]
    params += 4;
  }
}

// CHECK-LABEL: define dso_local void @concat_to_arrays_struct_cannot_remove_arrays_check(
// CHECK-SAME: ptr noundef writeonly captures(address) [[ARRAYS:%.*]], ptr noundef [[P_BUF:%.*]], i32 noundef [[N:%.*]]) local_unnamed_addr #[[ATTR5]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[PAYLOAD:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 4
// CHECK-NEXT:    [[OFFSET:%.*]] = getelementptr inbounds nuw i8, ptr [[P_BUF]], i64 2
// CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[OFFSET]], align 2, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV:%.*]] = zext i16 [[TMP0]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[P_BUF]], align 2, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV3:%.*]] = zext i16 [[TMP1]] to i64
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw i8, ptr [[PAYLOAD]], i64 [[CONV]]
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP2]], i64 [[CONV3]]
// CHECK-NEXT:    [[CMP149_NOT:%.*]] = icmp eq i32 [[N]], 0
// CHECK-NEXT:    br i1 [[CMP149_NOT]], label %[[FOR_COND_CLEANUP:.*]], label %[[FOR_BODY_LR_PH:.*]]
// CHECK:       [[FOR_BODY_LR_PH]]:
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[P_BUF]], i64 7
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[ADD_PTR]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[UPPER:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYS]], i64 16
// CHECK-NEXT:    [[UPPER78:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYS]], i64 32
// CHECK-NEXT:    [[UPPER97:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYS]], i64 48
// CHECK-NEXT:    [[UPPER116:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYS]], i64 64
// CHECK-NEXT:    [[CMP26_NOT:%.*]] = icmp uge ptr [[BOUND_PTR_ARITH]], [[PAYLOAD]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br label %[[FOR_BODY:.*]]
// CHECK:       [[FOR_COND_CLEANUP]]:
// CHECK-NEXT:    ret void
// CHECK:       [[FOR_BODY]]:
// CHECK-NEXT:    [[PARAMS_SROA_0_0151:%.*]] = phi ptr [ [[BOUND_PTR_ARITH]], %[[FOR_BODY_LR_PH]] ], [ [[ADD_PTR50:%.*]], %[[CONT121:.*]] ]
// CHECK-NEXT:    [[I_0150:%.*]] = phi i8 [ 0, %[[FOR_BODY_LR_PH]] ], [ [[INC:%.*]], %[[CONT121]] ]
// CHECK-NEXT:    [[CMP14_NOT:%.*]] = icmp ule ptr [[PARAMS_SROA_0_0151]], [[ADD_PTR]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND146_NOT148:%.*]] = and i1 [[CMP14_NOT]], [[CMP26_NOT]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[PARAMS_SROA_0_0151]] to i64, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP38:%.*]] = icmp sgt i64 [[SUB_PTR_SUB]], 3, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND147:%.*]] = select i1 [[OR_COND146_NOT148]], i1 [[CMP38]], i1 false, {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND147]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) {{#[0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    [[ADD_PTR50]] = getelementptr inbounds nuw i8, ptr [[PARAMS_SROA_0_0151]], i64 4
// CHECK-NEXT:    [[IDXPROM:%.*]] = zext i8 [[I_0150]] to i64
// CHECK-NEXT:    [[ARRAYIDX61:%.*]] = getelementptr [4 x i8], ptr [[ARRAYS]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[ARRAYIDX61]], i64 4, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP4:%.*]] = icmp ule ptr [[TMP3]], [[UPPER]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP5:%.*]] = icmp ule ptr [[ARRAYIDX61]], [[TMP3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND124:%.*]] = and i1 [[TMP4]], [[TMP5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP6:%.*]] = icmp uge ptr [[ARRAYIDX61]], [[ARRAYS]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND125:%.*]] = and i1 [[TMP6]], [[OR_COND124]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND125]], label %[[CONT64:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT64]]:
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i8, ptr [[PARAMS_SROA_0_0151]], i64 3
// CHECK-NEXT:    [[TMP7:%.*]] = load i8, ptr [[ARRAYIDX]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV59:%.*]] = zext i8 [[TMP7]] to i32
// CHECK-NEXT:    store i32 [[CONV59]], ptr [[ARRAYIDX61]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX80:%.*]] = getelementptr [4 x i8], ptr [[UPPER]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[ARRAYIDX80]], i64 4, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP9:%.*]] = icmp ule ptr [[TMP8]], [[UPPER78]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP10:%.*]] = icmp ule ptr [[ARRAYIDX80]], [[TMP8]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND127:%.*]] = and i1 [[TMP9]], [[TMP10]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP11:%.*]] = icmp uge ptr [[ARRAYIDX80]], [[UPPER]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND128:%.*]] = and i1 [[TMP11]], [[OR_COND127]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND128]], label %[[CONT83:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT83]]:
// CHECK-NEXT:    [[ARRAYIDX69:%.*]] = getelementptr i8, ptr [[PARAMS_SROA_0_0151]], i64 1
// CHECK-NEXT:    [[TMP12:%.*]] = load i8, ptr [[ARRAYIDX69]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV76:%.*]] = zext i8 [[TMP12]] to i32
// CHECK-NEXT:    store i32 [[CONV76]], ptr [[ARRAYIDX80]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX99:%.*]] = getelementptr [4 x i8], ptr [[UPPER78]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[ARRAYIDX99]], i64 4, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP14:%.*]] = icmp ule ptr [[TMP13]], [[UPPER97]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP15:%.*]] = icmp ule ptr [[ARRAYIDX99]], [[TMP13]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND130:%.*]] = and i1 [[TMP14]], [[TMP15]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND130]], label %[[CONT102:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT102]]:
// CHECK-NEXT:    [[ARRAYIDX88:%.*]] = getelementptr i8, ptr [[PARAMS_SROA_0_0151]], i64 2
// CHECK-NEXT:    [[TMP16:%.*]] = load i8, ptr [[ARRAYIDX88]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV95:%.*]] = zext i8 [[TMP16]] to i32
// CHECK-NEXT:    store i32 [[CONV95]], ptr [[ARRAYIDX99]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ARRAYIDX118:%.*]] = getelementptr [4 x i8], ptr [[UPPER97]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP17:%.*]] = getelementptr i8, ptr [[ARRAYIDX118]], i64 4, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP18:%.*]] = icmp ule ptr [[TMP17]], [[UPPER116]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP19:%.*]] = icmp ule ptr [[ARRAYIDX118]], [[TMP17]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND133:%.*]] = and i1 [[TMP18]], [[TMP19]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND133]], label %[[CONT121]], label %[[TRAP]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT121]]:
// CHECK-NEXT:    [[TMP20:%.*]] = load i8, ptr [[PARAMS_SROA_0_0151]], align 1, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[CONV114:%.*]] = zext i8 [[TMP20]] to i32
// CHECK-NEXT:    store i32 [[CONV114]], ptr [[ARRAYIDX118]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[INC]] = add i8 [[I_0150]], 1, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CONV4:%.*]] = zext i8 [[INC]] to i32
// CHECK-NEXT:    [[CMP:%.*]] = icmp ugt i32 [[N]], [[CONV4]]
// CHECK-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_COND_CLEANUP]], {{!llvm.loop ![0-9]+}}
//
void concat_to_arrays_struct_cannot_remove_arrays_check(struct arrays *arrays, hdr_t *p_buf, unsigned n) {
  uint8_t *params = p_buf->payload + 3;

  for (unsigned char i = 0; i < n; i++) {
    uint8_t *__counted_by(4) p = params;
    arrays->a[i] = p[3]; // checks not removed for p[]
    arrays->b[i] = p[1]; // checks not removed for b[] and p[]
    arrays->c[i] = p[2]; // checks not removed for c[] and p[]
    arrays->d[i] = p[0]; // checks not removed for d[]
    params += 4;
  }
}
