// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --version 6

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -Wno-error=incompatible-pointer-types -emit-llvm %s -o - | FileCheck %s --check-prefix=CHECK-O2
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -Wno-error=incompatible-pointer-types -emit-llvm %s -o - | FileCheck %s --check-prefix=CHECK-O2

#include <ptrcheck.h>

// CHECK-O2-LABEL: define dso_local noundef i32 @TestOK(
// CHECK-O2-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-O2-NEXT:  [[ENTRY:.*:]]
// CHECK-O2-NEXT:    ret i32 0
//
int TestOK() {
    int len = 0;
    int *__single __counted_by(len) dcp = 0;
    int *__single tp = dcp;
    return 0;
}

// FIXME
// CHECK-O2-LABEL: define dso_local void @TestTrap(
// CHECK-O2-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-O2-NEXT:  [[ENTRY:.*:]]
// CHECK-O2-NEXT:    [[P:%.*]] = alloca i8, align 1
// CHECK-O2-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[P]]) #[[ATTR4:[0-9]+]]
// CHECK-O2-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 1
// CHECK-O2-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[P]], i64 4, {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[TMP1]], [[TMP0]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    [[TMP3:%.*]] = icmp ule ptr [[P]], [[TMP1]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    [[OR_COND:%.*]] = and i1 [[TMP2]], [[TMP3]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    br i1 [[OR_COND]], label %[[BOUNDSCHECK_NULL:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O2:       [[TRAP]]:
// CHECK-O2-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O2:       [[BOUNDSCHECK_NULL]]:
// CHECK-O2-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[P]]) #[[ATTR4]]
// CHECK-O2-NEXT:    ret void
//
void TestTrap() {
  int len = 1;
  char p;
  char *__counted_by(len) dcp = &p;
  int *__single tp = dcp; // rdar://80816535
}
