// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --version 5
// REQUIRES: system-darwin
// RUN: %clang_cc1 -O0 -triple arm64-apple-iphoneos -fbounds-safety -Wno-bounds-safety-init-list -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O0 -triple arm64-apple-iphoneos -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -Wno-bounds-safety-init-list -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

void foo(int *__sized_by_or_null(len) p, int len);

// CHECK-LABEL: define dso_local void @caller_1(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    br i1 true, label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2:![0-9]+]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    call void @foo(ptr noundef null, i32 noundef 2)
// CHECK-NEXT:    ret void
//
void caller_1() {
  foo(0, 2);
}

// CHECK-LABEL: define dso_local void @caller_2(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    br i1 true, label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    call void @foo(ptr noundef null, i32 noundef 0)
// CHECK-NEXT:    ret void
//
void caller_2() {
  foo(0, 0);
}

// CHECK-LABEL: define dso_local void @caller_3(
// CHECK-SAME: ptr noundef [[P:%.*]], i32 noundef [[LEN:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[LEN_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP11:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP20:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP28:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP35:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP36:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP51:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP52:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP71:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store i32 [[LEN]], ptr [[LEN_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[LEN_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ne ptr [[TMP0]], null, !annotation [[META3:![0-9]+]]
// CHECK-NEXT:    br i1 [[TMP2]], label %[[BOUNDSCHECK_NOTNULL:.*]], label %[[BOUNDSCHECK_NULL:.*]], !annotation [[META3]]
// CHECK:       [[BOUNDSCHECK_NOTNULL]]:
// CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP1]] to i64
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 [[IDX_EXT]]
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP4]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP5]], align 8
// CHECK-NEXT:    br label %[[BOUNDSCHECK_CONT:.*]]
// CHECK:       [[BOUNDSCHECK_NULL]]:
// CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr null, ptr [[TMP6]], align 8
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr null, ptr [[TMP7]], align 8
// CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-NEXT:    store ptr null, ptr [[TMP8]], align 8
// CHECK-NEXT:    br label %[[BOUNDSCHECK_CONT]]
// CHECK:       [[BOUNDSCHECK_CONT]]:
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[LEN_ADDR]], align 4
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP2]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB4:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR3]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB4]], ptr [[TMP10]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR6:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR5]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB8:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR7]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB10:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR9]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_PTR6]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END70:.*]], !annotation [[META2]]
// CHECK:       [[LAND_LHS_TRUE]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP11]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB13]], ptr [[TMP11]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR15:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR14]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB17:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR16]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB19:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR18]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP20]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR22:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR21]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB24:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR23]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR25:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB26:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR25]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP27:%.*]] = icmp ule ptr [[WIDE_PTR_PTR15]], [[WIDE_PTR_PTR22]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP27]], label %[[LAND_RHS:.*]], label %[[LAND_END70]], !annotation [[META2]]
// CHECK:       [[LAND_RHS]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP28]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR29:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR30:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR29]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR31:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB32:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR31]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB34:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR33]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne ptr [[WIDE_PTR_PTR30]], null, !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TOBOOL]], label %[[LOR_RHS:.*]], label %[[LOR_END:.*]], !annotation [[META2]]
// CHECK:       [[LOR_RHS]]:
// CHECK-NEXT:    [[CONV:%.*]] = sext i32 [[TMP9]] to i64, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP36]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR37:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP36]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB38:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR37]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP36]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB38]], ptr [[TMP12]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR39:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP36]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR40:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR39]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR41:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP36]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB42:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR41]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR43:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP36]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB44:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR43]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR40]], ptr [[TMP13]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB42]], ptr [[TMP14]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB44]], ptr [[TMP15]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR45:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR46:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR45]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR47:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB48:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR47]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR49:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB50:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR49]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP52]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR53:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP52]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR54:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR53]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR55:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP52]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB56:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR55]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR57:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP52]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB58:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR57]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR54]], ptr [[TMP16]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB56]], ptr [[TMP17]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB58]], ptr [[TMP18]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR59:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR60:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR59]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR61:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB62:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR61]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR63:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB64:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR63]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR46]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR60]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META2]]
// CHECK-NEXT:    [[CMP65:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_SUB]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP65]], label %[[LAND_RHS67:.*]], label %[[LAND_END:.*]], !annotation [[META2]]
// CHECK:       [[LAND_RHS67]]:
// CHECK-NEXT:    [[CMP68:%.*]] = icmp sle i32 0, [[TMP9]], !annotation [[META2]]
// CHECK-NEXT:    br label %[[LAND_END]], !annotation [[META2]]
// CHECK:       [[LAND_END]]:
// CHECK-NEXT:    [[TMP19:%.*]] = phi i1 [ false, %[[LOR_RHS]] ], [ [[CMP68]], %[[LAND_RHS67]] ]
// CHECK-NEXT:    br label %[[LOR_END]], !annotation [[META2]]
// CHECK:       [[LOR_END]]:
// CHECK-NEXT:    [[TMP20:%.*]] = phi i1 [ true, %[[LAND_RHS]] ], [ [[TMP19]], %[[LAND_END]] ]
// CHECK-NEXT:    br label %[[LAND_END70]], !annotation [[META2]]
// CHECK:       [[LAND_END70]]:
// CHECK-NEXT:    [[TMP21:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[BOUNDSCHECK_CONT]] ], [ [[TMP20]], %[[LOR_END]] ], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TMP21]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP71]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR72:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP71]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR73:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR72]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR74:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP71]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB75:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR74]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR76:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP71]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB77:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR76]], align 8
// CHECK-NEXT:    call void @foo(ptr noundef [[WIDE_PTR_PTR73]], i32 noundef [[TMP9]])
// CHECK-NEXT:    ret void
//
void caller_3(int *__sized_by_or_null(len) p, int len) {
  foo(p, len);
}

// CHECK-LABEL: define dso_local void @caller_4(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    store i32 0, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i32, ptr [[I]], i64 1
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[I]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[I]], ptr [[TMP3]], align 8
// CHECK-NEXT:    br i1 false, label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-NEXT:    call void @foo(ptr noundef [[WIDE_PTR_PTR]], i32 noundef -1)
// CHECK-NEXT:    ret void
//
void caller_4() {
    int i = 0;
    foo(&i, -1);
}

// CHECK-LABEL: define dso_local void @caller_5(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    store i32 0, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i32, ptr [[I]], i64 1
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[I]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[I]], ptr [[TMP3]], align 8
// CHECK-NEXT:    br i1 true, label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-NEXT:    call void @foo(ptr noundef [[WIDE_PTR_PTR]], i32 noundef 2)
// CHECK-NEXT:    ret void
//
void caller_5() {
    int i = 0;
    foo(&i, 2);
}

// CHECK-LABEL: define dso_local void @caller_6(
// CHECK-SAME: ptr noundef [[P:%.*]], i32 noundef [[LEN:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[LEN_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP11:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP20:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP28:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP35:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP36:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP51:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP52:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP71:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store i32 [[LEN]], ptr [[LEN_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[LEN_ADDR]], align 4
// CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP1]] to i64
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 [[IDX_EXT]]
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP4]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[LEN_ADDR]], align 4
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP2]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB4:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR3]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB4]], ptr [[TMP6]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR6:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR5]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB8:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR7]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB10:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR9]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_PTR6]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END70:.*]], !annotation [[META2]]
// CHECK:       [[LAND_LHS_TRUE]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP11]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB13]], ptr [[TMP7]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR15:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR14]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB17:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR16]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB19:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR18]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP20]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR22:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR21]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB24:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR23]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR25:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB26:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR25]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP27:%.*]] = icmp ule ptr [[WIDE_PTR_PTR15]], [[WIDE_PTR_PTR22]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP27]], label %[[LAND_RHS:.*]], label %[[LAND_END70]], !annotation [[META2]]
// CHECK:       [[LAND_RHS]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP28]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR29:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR30:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR29]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR31:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB32:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR31]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB34:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR33]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne ptr [[WIDE_PTR_PTR30]], null, !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TOBOOL]], label %[[LOR_RHS:.*]], label %[[LOR_END:.*]], !annotation [[META2]]
// CHECK:       [[LOR_RHS]]:
// CHECK-NEXT:    [[CONV:%.*]] = sext i32 [[TMP5]] to i64, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP36]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR37:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP36]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB38:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR37]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP36]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB38]], ptr [[TMP8]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR39:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP36]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR40:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR39]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR41:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP36]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB42:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR41]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR43:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP36]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB44:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR43]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR40]], ptr [[TMP9]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB42]], ptr [[TMP10]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB44]], ptr [[TMP11]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR45:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR46:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR45]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR47:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB48:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR47]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR49:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB50:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR49]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP52]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR53:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP52]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR54:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR53]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR55:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP52]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB56:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR55]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR57:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP52]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB58:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR57]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR54]], ptr [[TMP12]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB56]], ptr [[TMP13]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB58]], ptr [[TMP14]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR59:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR60:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR59]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR61:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB62:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR61]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR63:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB64:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR63]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR46]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR60]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META2]]
// CHECK-NEXT:    [[CMP65:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_SUB]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP65]], label %[[LAND_RHS67:.*]], label %[[LAND_END:.*]], !annotation [[META2]]
// CHECK:       [[LAND_RHS67]]:
// CHECK-NEXT:    [[CMP68:%.*]] = icmp sle i32 0, [[TMP5]], !annotation [[META2]]
// CHECK-NEXT:    br label %[[LAND_END]], !annotation [[META2]]
// CHECK:       [[LAND_END]]:
// CHECK-NEXT:    [[TMP15:%.*]] = phi i1 [ false, %[[LOR_RHS]] ], [ [[CMP68]], %[[LAND_RHS67]] ]
// CHECK-NEXT:    br label %[[LOR_END]], !annotation [[META2]]
// CHECK:       [[LOR_END]]:
// CHECK-NEXT:    [[TMP16:%.*]] = phi i1 [ true, %[[LAND_RHS]] ], [ [[TMP15]], %[[LAND_END]] ]
// CHECK-NEXT:    br label %[[LAND_END70]], !annotation [[META2]]
// CHECK:       [[LAND_END70]]:
// CHECK-NEXT:    [[TMP17:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP16]], %[[LOR_END]] ], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TMP17]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP71]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR72:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP71]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR73:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR72]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR74:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP71]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB75:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR74]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR76:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP71]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB77:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR76]], align 8
// CHECK-NEXT:    call void @foo(ptr noundef [[WIDE_PTR_PTR73]], i32 noundef [[TMP5]])
// CHECK-NEXT:    ret void
//
void caller_6(int *__sized_by(len) p, int len) {
  foo(p, len);
}

// CHECK-LABEL: define dso_local void @caller_7(
// CHECK-SAME: ptr noundef dead_on_return [[P:%.*]], i32 noundef [[LEN:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[P_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[LEN_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP11:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP20:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP28:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP35:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP36:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP51:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP52:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP71:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_INDIRECT_ADDR]], align 8
// CHECK-NEXT:    store i32 [[LEN]], ptr [[LEN_ADDR]], align 4
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[P]], i64 24, i1 false)
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LEN_ADDR]], align 4
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP2]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB4:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR3]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB4]], ptr [[TMP1]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR6:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR5]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB8:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR7]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB10:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR9]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_PTR6]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END70:.*]], !annotation [[META2]]
// CHECK:       [[LAND_LHS_TRUE]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP11]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB13]], ptr [[TMP2]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR15:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR14]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB17:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR16]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB19:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR18]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP20]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR22:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR21]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB24:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR23]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR25:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB26:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR25]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP27:%.*]] = icmp ule ptr [[WIDE_PTR_PTR15]], [[WIDE_PTR_PTR22]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP27]], label %[[LAND_RHS:.*]], label %[[LAND_END70]], !annotation [[META2]]
// CHECK:       [[LAND_RHS]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP28]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR29:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR30:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR29]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR31:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB32:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR31]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB34:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR33]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne ptr [[WIDE_PTR_PTR30]], null, !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TOBOOL]], label %[[LOR_RHS:.*]], label %[[LOR_END:.*]], !annotation [[META2]]
// CHECK:       [[LOR_RHS]]:
// CHECK-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP36]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR37:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP36]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB38:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR37]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP36]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB38]], ptr [[TMP3]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR39:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP36]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR40:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR39]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR41:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP36]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB42:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR41]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR43:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP36]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB44:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR43]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR40]], ptr [[TMP4]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB42]], ptr [[TMP5]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB44]], ptr [[TMP6]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR45:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR46:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR45]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR47:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB48:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR47]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR49:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP35]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB50:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR49]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP52]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR53:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP52]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR54:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR53]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR55:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP52]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB56:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR55]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR57:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP52]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB58:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR57]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR54]], ptr [[TMP7]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB56]], ptr [[TMP8]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB58]], ptr [[TMP9]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR59:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR60:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR59]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR61:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB62:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR61]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR63:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP51]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB64:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR63]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR46]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR60]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META2]]
// CHECK-NEXT:    [[CMP65:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_SUB]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP65]], label %[[LAND_RHS67:.*]], label %[[LAND_END:.*]], !annotation [[META2]]
// CHECK:       [[LAND_RHS67]]:
// CHECK-NEXT:    [[CMP68:%.*]] = icmp sle i32 0, [[TMP0]], !annotation [[META2]]
// CHECK-NEXT:    br label %[[LAND_END]], !annotation [[META2]]
// CHECK:       [[LAND_END]]:
// CHECK-NEXT:    [[TMP10:%.*]] = phi i1 [ false, %[[LOR_RHS]] ], [ [[CMP68]], %[[LAND_RHS67]] ]
// CHECK-NEXT:    br label %[[LOR_END]], !annotation [[META2]]
// CHECK:       [[LOR_END]]:
// CHECK-NEXT:    [[TMP11:%.*]] = phi i1 [ true, %[[LAND_RHS]] ], [ [[TMP10]], %[[LAND_END]] ]
// CHECK-NEXT:    br label %[[LAND_END70]], !annotation [[META2]]
// CHECK:       [[LAND_END70]]:
// CHECK-NEXT:    [[TMP12:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP11]], %[[LOR_END]] ], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TMP12]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP71]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR72:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP71]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR73:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR72]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR74:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP71]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB75:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR74]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR76:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP71]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB77:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR76]], align 8
// CHECK-NEXT:    call void @foo(ptr noundef [[WIDE_PTR_PTR73]], i32 noundef [[TMP0]])
// CHECK-NEXT:    ret void
//
void caller_7(int *__bidi_indexable p, int len) {
  foo(p, len);
}

// CHECK-LABEL: define dso_local void @caller_8(
// CHECK-SAME: ptr noundef [[P:%.*]], i32 noundef [[LEN:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[LEN_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP3:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP14:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP15:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store i32 [[LEN]], ptr [[LEN_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[LEN_ADDR]], align 4
// CHECK-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 1, !annotation [[META2]]
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[UPPER]], ptr [[TMP3]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP4]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP5]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB2:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR1]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP:%.*]] = icmp ule ptr [[TMP0]], [[WIDE_PTR_PTR]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END36:.*]], !annotation [[META2]]
// CHECK:       [[LAND_LHS_TRUE]]:
// CHECK-NEXT:    [[UPPER4:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 1, !annotation [[META2]]
// CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP3]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP6]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP3]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[UPPER4]], ptr [[TMP7]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP3]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP8]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP3]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB6:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR5]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP3]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB6]], ptr [[TMP9]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP3]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR8:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR7]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP3]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB10:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR9]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP3]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB12:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR11]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP13:%.*]] = icmp ule ptr [[WIDE_PTR_PTR8]], [[TMP0]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP13]], label %[[LAND_RHS:.*]], label %[[LAND_END36]], !annotation [[META2]]
// CHECK:       [[LAND_RHS]]:
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne ptr [[TMP0]], null, !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TOBOOL]], label %[[LOR_RHS:.*]], label %[[LOR_END:.*]], !annotation [[META2]]
// CHECK:       [[LOR_RHS]]:
// CHECK-NEXT:    [[CONV:%.*]] = sext i32 [[TMP1]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[UPPER16:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 1, !annotation [[META2]]
// CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP10]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[UPPER16]], ptr [[TMP11]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP12]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR17:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB18:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR17]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB18]], ptr [[TMP13]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR20:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR19]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB22:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR21]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP15]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB24:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR23]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP14]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR20]], ptr [[TMP14]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP14]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB22]], ptr [[TMP15]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP14]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB24]], ptr [[TMP16]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR25:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP14]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR26:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR25]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR27:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP14]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB28:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR27]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR29:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP14]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB30:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR29]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR26]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[TMP0]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META2]]
// CHECK-NEXT:    [[CMP31:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_SUB]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP31]], label %[[LAND_RHS33:.*]], label %[[LAND_END:.*]], !annotation [[META2]]
// CHECK:       [[LAND_RHS33]]:
// CHECK-NEXT:    [[CMP34:%.*]] = icmp sle i32 0, [[TMP1]], !annotation [[META2]]
// CHECK-NEXT:    br label %[[LAND_END]], !annotation [[META2]]
// CHECK:       [[LAND_END]]:
// CHECK-NEXT:    [[TMP17:%.*]] = phi i1 [ false, %[[LOR_RHS]] ], [ [[CMP34]], %[[LAND_RHS33]] ]
// CHECK-NEXT:    br label %[[LOR_END]], !annotation [[META2]]
// CHECK:       [[LOR_END]]:
// CHECK-NEXT:    [[TMP18:%.*]] = phi i1 [ true, %[[LAND_RHS]] ], [ [[TMP17]], %[[LAND_END]] ]
// CHECK-NEXT:    br label %[[LAND_END36]], !annotation [[META2]]
// CHECK:       [[LAND_END36]]:
// CHECK-NEXT:    [[TMP19:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP18]], %[[LOR_END]] ], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TMP19]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    call void @foo(ptr noundef [[TMP0]], i32 noundef [[TMP1]])
// CHECK-NEXT:    ret void
//
void caller_8(int *__single p, int len) {
  foo(p, len);
}

void bar(int *__sized_by(*len) *out, int *len);

// CHECK-LABEL: define dso_local void @caller_9(
// CHECK-SAME: ptr noundef [[OUT:%.*]], ptr noundef [[LEN:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[OUT_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[LEN_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[OUT]], ptr [[OUT_ADDR]], align 8
// CHECK-NEXT:    store ptr [[LEN]], ptr [[LEN_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[OUT_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[LEN_ADDR]], align 8
// CHECK-NEXT:    call void @bar(ptr noundef [[TMP0]], ptr noundef [[TMP1]])
// CHECK-NEXT:    ret void
//
void caller_9(int *__sized_by(*len) *out, int *len){
    bar(out, len);
}

// CHECK-LABEL: define dso_local ptr @caller_10(
// CHECK-SAME: i32 noundef [[LEN:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[LEN_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[COUNT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[P:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// CHECK-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// CHECK-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP22:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP25:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP32:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP35:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP38:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP46:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP53:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP56:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP57:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP78:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP90:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP97:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP103:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP106:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP116:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP126:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP129:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP130:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP156:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    store i32 [[LEN]], ptr [[LEN_ADDR]], align 4
// CHECK-NEXT:    store i32 0, ptr [[COUNT]], align 4, !annotation [[META4:![0-9]+]]
// CHECK-NEXT:    store ptr null, ptr [[P]], align 8, !annotation [[META4]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr ptr, ptr [[P]], i64 1
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[P]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[P]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i32, ptr [[COUNT]], i64 1
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[COUNT]], ptr [[TMP5]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[TMP6]], align 8
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[COUNT]], ptr [[TMP7]], align 8
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP2]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP2]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP2]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP2]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-NEXT:    [[TMP8:%.*]] = icmp ne ptr [[WIDE_PTR_PTR]], null, !annotation [[META3]]
// CHECK-NEXT:    br i1 [[TMP8]], label %[[BOUNDSCHECK_NOTNULL:.*]], label %[[BOUNDSCHECK_NULL:.*]], !annotation [[META3]]
// CHECK:       [[BOUNDSCHECK_NOTNULL]]:
// CHECK-NEXT:    [[TMP9:%.*]] = getelementptr ptr, ptr [[WIDE_PTR_PTR]], i64 1, !annotation [[META5:![0-9]+]]
// CHECK-NEXT:    [[TMP10:%.*]] = icmp ule ptr [[TMP9]], [[WIDE_PTR_UB]], !annotation [[META5]]
// CHECK-NEXT:    br i1 [[TMP10]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META5]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META5]]
// CHECK-NEXT:    unreachable, !annotation [[META5]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    [[TMP11:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[TMP9]], !annotation [[META5]]
// CHECK-NEXT:    br i1 [[TMP11]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, !annotation [[META5]]
// CHECK:       [[TRAP3]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META5]]
// CHECK-NEXT:    unreachable, !annotation [[META5]]
// CHECK:       [[CONT4]]:
// CHECK-NEXT:    [[TMP12:%.*]] = icmp uge ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_LB]], !annotation [[META6:![0-9]+]]
// CHECK-NEXT:    br i1 [[TMP12]], label %[[CONT6:.*]], label %[[TRAP5:.*]], {{!prof ![0-9]+}}, !annotation [[META6]]
// CHECK:       [[TRAP5]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META6]]
// CHECK-NEXT:    unreachable, !annotation [[META6]]
// CHECK:       [[CONT6]]:
// CHECK-NEXT:    br label %[[BOUNDSCHECK_NULL]]
// CHECK:       [[BOUNDSCHECK_NULL]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[AGG_TEMP1]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8
// CHECK-NEXT:    [[TMP13:%.*]] = icmp ne ptr [[WIDE_PTR_PTR9]], null, !annotation [[META3]]
// CHECK-NEXT:    br i1 [[TMP13]], label %[[BOUNDSCHECK_NOTNULL14:.*]], label %[[BOUNDSCHECK_NULL21:.*]], !annotation [[META3]]
// CHECK:       [[BOUNDSCHECK_NOTNULL14]]:
// CHECK-NEXT:    [[TMP14:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR9]], i64 1, !annotation [[META5]]
// CHECK-NEXT:    [[TMP15:%.*]] = icmp ule ptr [[TMP14]], [[WIDE_PTR_UB11]], !annotation [[META5]]
// CHECK-NEXT:    br i1 [[TMP15]], label %[[CONT16:.*]], label %[[TRAP15:.*]], {{!prof ![0-9]+}}, !annotation [[META5]]
// CHECK:       [[TRAP15]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META5]]
// CHECK-NEXT:    unreachable, !annotation [[META5]]
// CHECK:       [[CONT16]]:
// CHECK-NEXT:    [[TMP16:%.*]] = icmp ule ptr [[WIDE_PTR_PTR9]], [[TMP14]], !annotation [[META5]]
// CHECK-NEXT:    br i1 [[TMP16]], label %[[CONT18:.*]], label %[[TRAP17:.*]], {{!prof ![0-9]+}}, !annotation [[META5]]
// CHECK:       [[TRAP17]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META5]]
// CHECK-NEXT:    unreachable, !annotation [[META5]]
// CHECK:       [[CONT18]]:
// CHECK-NEXT:    [[TMP17:%.*]] = icmp uge ptr [[WIDE_PTR_PTR9]], [[WIDE_PTR_LB13]], !annotation [[META6]]
// CHECK-NEXT:    br i1 [[TMP17]], label %[[CONT20:.*]], label %[[TRAP19:.*]], {{!prof ![0-9]+}}, !annotation [[META6]]
// CHECK:       [[TRAP19]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META6]]
// CHECK-NEXT:    unreachable, !annotation [[META6]]
// CHECK:       [[CONT20]]:
// CHECK-NEXT:    br label %[[BOUNDSCHECK_NULL21]]
// CHECK:       [[BOUNDSCHECK_NULL21]]:
// CHECK-NEXT:    call void @bar(ptr noundef [[WIDE_PTR_PTR]], ptr noundef [[WIDE_PTR_PTR9]])
// CHECK-NEXT:    [[TMP18:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[TMP19:%.*]] = load i32, ptr [[COUNT]], align 4
// CHECK-NEXT:    [[TMP20:%.*]] = icmp ne ptr [[TMP18]], null, !annotation [[META3]]
// CHECK-NEXT:    br i1 [[TMP20]], label %[[BOUNDSCHECK_NOTNULL23:.*]], label %[[BOUNDSCHECK_NULL24:.*]], !annotation [[META3]]
// CHECK:       [[BOUNDSCHECK_NOTNULL23]]:
// CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP19]] to i64
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[TMP18]], i64 [[IDX_EXT]]
// CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP22]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[TMP18]], ptr [[TMP21]], align 8
// CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP22]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP22]], align 8
// CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP22]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[TMP18]], ptr [[TMP23]], align 8
// CHECK-NEXT:    br label %[[BOUNDSCHECK_CONT:.*]]
// CHECK:       [[BOUNDSCHECK_NULL24]]:
// CHECK-NEXT:    [[TMP24:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP22]], i32 0, i32 0
// CHECK-NEXT:    store ptr null, ptr [[TMP24]], align 8
// CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP22]], i32 0, i32 1
// CHECK-NEXT:    store ptr null, ptr [[TMP25]], align 8
// CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP22]], i32 0, i32 2
// CHECK-NEXT:    store ptr null, ptr [[TMP26]], align 8
// CHECK-NEXT:    br label %[[BOUNDSCHECK_CONT]]
// CHECK:       [[BOUNDSCHECK_CONT]]:
// CHECK-NEXT:    [[TMP27:%.*]] = load i32, ptr [[LEN_ADDR]], align 4
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP25]], ptr align 8 [[AGG_TEMP22]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR26:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP25]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR27:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR26]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP25]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB29:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR28]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR30:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP25]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB31:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR30]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP32]], ptr align 8 [[AGG_TEMP22]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP32]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB34:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR33]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR27]], [[WIDE_PTR_UB34]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END75:.*]], !annotation [[META2]]
// CHECK:       [[LAND_LHS_TRUE]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP35]], ptr align 8 [[AGG_TEMP22]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR36:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP35]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB37:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR36]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP38]], ptr align 8 [[AGG_TEMP22]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR39:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP38]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR40:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR39]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR41:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP38]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB42:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR41]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR43:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP38]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB44:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR43]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP45:%.*]] = icmp ule ptr [[WIDE_PTR_LB37]], [[WIDE_PTR_PTR40]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP45]], label %[[LAND_RHS:.*]], label %[[LAND_END75]], !annotation [[META2]]
// CHECK:       [[LAND_RHS]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP46]], ptr align 8 [[AGG_TEMP22]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR47:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP46]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR48:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR47]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR49:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP46]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB50:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR49]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR51:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP46]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB52:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR51]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne ptr [[WIDE_PTR_PTR48]], null, !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TOBOOL]], label %[[LOR_RHS:.*]], label %[[LOR_END:.*]], !annotation [[META2]]
// CHECK:       [[LOR_RHS]]:
// CHECK-NEXT:    [[CONV:%.*]] = sext i32 [[TMP27]] to i64, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP53]], ptr align 8 [[AGG_TEMP22]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR54:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP53]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB55:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR54]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP57]], ptr align 8 [[AGG_TEMP22]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR58:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP57]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR59:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR58]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR60:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP57]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB61:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR60]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR62:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP57]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB63:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR62]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP56]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR59]], ptr [[TMP28]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP56]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB61]], ptr [[TMP29]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP30:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP56]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB63]], ptr [[TMP30]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR64:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP56]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR65:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR64]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR66:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP56]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB67:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR66]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR68:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP56]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB69:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR68]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB55]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR65]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META2]]
// CHECK-NEXT:    [[CMP70:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_SUB]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP70]], label %[[LAND_RHS72:.*]], label %[[LAND_END:.*]], !annotation [[META2]]
// CHECK:       [[LAND_RHS72]]:
// CHECK-NEXT:    [[CMP73:%.*]] = icmp sle i32 0, [[TMP27]], !annotation [[META2]]
// CHECK-NEXT:    br label %[[LAND_END]], !annotation [[META2]]
// CHECK:       [[LAND_END]]:
// CHECK-NEXT:    [[TMP31:%.*]] = phi i1 [ false, %[[LOR_RHS]] ], [ [[CMP73]], %[[LAND_RHS72]] ]
// CHECK-NEXT:    br label %[[LOR_END]], !annotation [[META2]]
// CHECK:       [[LOR_END]]:
// CHECK-NEXT:    [[TMP32:%.*]] = phi i1 [ true, %[[LAND_RHS]] ], [ [[TMP31]], %[[LAND_END]] ]
// CHECK-NEXT:    br label %[[LAND_END75]], !annotation [[META2]]
// CHECK:       [[LAND_END75]]:
// CHECK-NEXT:    [[TMP33:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[BOUNDSCHECK_CONT]] ], [ [[TMP32]], %[[LOR_END]] ], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TMP33]], label %[[CONT77:.*]], label %[[TRAP76:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// CHECK:       [[TRAP76]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT77]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP78]], ptr align 8 [[AGG_TEMP22]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR79:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP78]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR80:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR79]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR81:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP78]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB82:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR81]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR83:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP78]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB84:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR83]], align 8
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR80]], ptr [[P]], align 8
// CHECK-NEXT:    store i32 [[TMP27]], ptr [[COUNT]], align 4
// CHECK-NEXT:    [[TMP34:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[TMP35:%.*]] = load i32, ptr [[COUNT]], align 4
// CHECK-NEXT:    [[TMP36:%.*]] = icmp ne ptr [[TMP34]], null, !annotation [[META3]]
// CHECK-NEXT:    br i1 [[TMP36]], label %[[BOUNDSCHECK_NOTNULL85:.*]], label %[[BOUNDSCHECK_NULL88:.*]], !annotation [[META3]]
// CHECK:       [[BOUNDSCHECK_NOTNULL85]]:
// CHECK-NEXT:    [[IDX_EXT86:%.*]] = sext i32 [[TMP35]] to i64
// CHECK-NEXT:    [[ADD_PTR87:%.*]] = getelementptr inbounds i8, ptr [[TMP34]], i64 [[IDX_EXT86]]
// CHECK-NEXT:    [[TMP37:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[TMP34]], ptr [[TMP37]], align 8
// CHECK-NEXT:    [[TMP38:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[ADD_PTR87]], ptr [[TMP38]], align 8
// CHECK-NEXT:    [[TMP39:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[TMP34]], ptr [[TMP39]], align 8
// CHECK-NEXT:    br label %[[BOUNDSCHECK_CONT89:.*]]
// CHECK:       [[BOUNDSCHECK_NULL88]]:
// CHECK-NEXT:    [[TMP40:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr null, ptr [[TMP40]], align 8
// CHECK-NEXT:    [[TMP41:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr null, ptr [[TMP41]], align 8
// CHECK-NEXT:    [[TMP42:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-NEXT:    store ptr null, ptr [[TMP42]], align 8
// CHECK-NEXT:    br label %[[BOUNDSCHECK_CONT89]]
// CHECK:       [[BOUNDSCHECK_CONT89]]:
// CHECK-NEXT:    [[TMP43:%.*]] = load i32, ptr [[LEN_ADDR]], align 4
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP90]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR91:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP90]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR92:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR91]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR93:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP90]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB94:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR93]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR95:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP90]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB96:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR95]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP97]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR98:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP97]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB99:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR98]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP100:%.*]] = icmp ule ptr [[WIDE_PTR_PTR92]], [[WIDE_PTR_UB99]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP100]], label %[[LAND_LHS_TRUE102:.*]], label %[[LAND_END153:.*]], !annotation [[META2]]
// CHECK:       [[LAND_LHS_TRUE102]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP103]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR104:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP103]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB105:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR104]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP106]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR107:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP106]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR108:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR107]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR109:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP106]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB110:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR109]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR111:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP106]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB112:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR111]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[CMP113:%.*]] = icmp ule ptr [[WIDE_PTR_LB105]], [[WIDE_PTR_PTR108]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP113]], label %[[LAND_RHS115:.*]], label %[[LAND_END153]], !annotation [[META2]]
// CHECK:       [[LAND_RHS115]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP116]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR117:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP116]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR118:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR117]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR119:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP116]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB120:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR119]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR121:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP116]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB122:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR121]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TOBOOL123:%.*]] = icmp ne ptr [[WIDE_PTR_PTR118]], null, !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TOBOOL123]], label %[[LOR_RHS124:.*]], label %[[LOR_END152:.*]], !annotation [[META2]]
// CHECK:       [[LOR_RHS124]]:
// CHECK-NEXT:    [[CONV125:%.*]] = sext i32 [[TMP43]] to i64, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP126]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR127:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP126]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB128:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR127]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP130]], ptr align 8 [[TMP]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR131:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP130]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR132:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR131]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR133:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP130]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB134:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR133]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR135:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP130]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB136:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR135]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP44:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP129]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR132]], ptr [[TMP44]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP45:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP129]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB134]], ptr [[TMP45]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP46:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP129]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB136]], ptr [[TMP46]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR137:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP129]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR138:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR137]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR139:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP129]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB140:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR139]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR141:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP129]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB142:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR141]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST143:%.*]] = ptrtoint ptr [[WIDE_PTR_UB128]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST144:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR138]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_SUB145:%.*]] = sub i64 [[SUB_PTR_LHS_CAST143]], [[SUB_PTR_RHS_CAST144]], !annotation [[META2]]
// CHECK-NEXT:    [[CMP146:%.*]] = icmp sle i64 [[CONV125]], [[SUB_PTR_SUB145]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP146]], label %[[LAND_RHS148:.*]], label %[[LAND_END151:.*]], !annotation [[META2]]
// CHECK:       [[LAND_RHS148]]:
// CHECK-NEXT:    [[CMP149:%.*]] = icmp sle i32 0, [[TMP43]], !annotation [[META2]]
// CHECK-NEXT:    br label %[[LAND_END151]], !annotation [[META2]]
// CHECK:       [[LAND_END151]]:
// CHECK-NEXT:    [[TMP47:%.*]] = phi i1 [ false, %[[LOR_RHS124]] ], [ [[CMP149]], %[[LAND_RHS148]] ]
// CHECK-NEXT:    br label %[[LOR_END152]], !annotation [[META2]]
// CHECK:       [[LOR_END152]]:
// CHECK-NEXT:    [[TMP48:%.*]] = phi i1 [ true, %[[LAND_RHS115]] ], [ [[TMP47]], %[[LAND_END151]] ]
// CHECK-NEXT:    br label %[[LAND_END153]], !annotation [[META2]]
// CHECK:       [[LAND_END153]]:
// CHECK-NEXT:    [[TMP49:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE102]] ], [ false, %[[BOUNDSCHECK_CONT89]] ], [ [[TMP48]], %[[LOR_END152]] ], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TMP49]], label %[[CONT155:.*]], label %[[TRAP154:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// CHECK:       [[TRAP154]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT155]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP156]], ptr align 8 [[TMP]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR157:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP156]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR158:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR157]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR159:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP156]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB160:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR159]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR161:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP156]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB162:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR161]], align 8
// CHECK-NEXT:    ret ptr [[WIDE_PTR_PTR158]]
//
int *__sized_by_or_null(len) caller_10(int len) {
    int count;
    int *__sized_by_or_null(count) p;
    bar(&p, &count);
    p = p; // workaround for missing return bounds check
    count = len;
    return p;
}
//.
// CHECK: [[META2]] = !{!"bounds-safety-generic"}
// CHECK: [[META3]] = !{!"bounds-safety-check-ptr-neq-null"}
// CHECK: [[META4]] = !{!"bounds-safety-zero-init"}
// CHECK: [[META5]] = !{!"bounds-safety-check-ptr-le-upper-bound"}
// CHECK: [[META6]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
//.
