// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6

// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

// CHECK-LABEL: define dso_local { ptr, ptr } @safe(
// CHECK-SAME: ptr noundef [[P:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[TERMINATED_BY_LEN:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store i64 0, ptr [[TERMINATED_BY_LEN]], align 8
// CHECK-NEXT:    br label %[[TERMINATED_BY_LOOP_COND:.*]]
// CHECK:       [[TERMINATED_BY_LOOP_COND]]:
// CHECK-NEXT:    [[TERMINATED_BY_LEN1:%.*]] = load i64, ptr [[TERMINATED_BY_LEN]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 [[TERMINATED_BY_LEN1]]
// CHECK-NEXT:    [[TERMINATED_BY_ELEM:%.*]] = load i32, ptr [[TMP1]], align 4
// CHECK-NEXT:    [[TERMINTED_BY_CHECK_TERMINATOR:%.*]] = icmp eq i32 [[TERMINATED_BY_ELEM]], 0
// CHECK-NEXT:    br i1 [[TERMINTED_BY_CHECK_TERMINATOR]], label %[[TERMINATED_BY_LOOP_END:.*]], label %[[TERMINATED_BY_LOOP_CONT:.*]]
// CHECK:       [[TERMINATED_BY_LOOP_CONT]]:
// CHECK-NEXT:    [[TERMINATED_BY_NEW_LEN:%.*]] = add i64 [[TERMINATED_BY_LEN1]], 1
// CHECK-NEXT:    store i64 [[TERMINATED_BY_NEW_LEN]], ptr [[TERMINATED_BY_LEN]], align 8
// CHECK-NEXT:    br label %[[TERMINATED_BY_LOOP_COND]]
// CHECK:       [[TERMINATED_BY_LOOP_END]]:
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[TERMINATED_BY_LEN]], align 8
// CHECK-NEXT:    [[TERMINATED_BY_UPPER:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 [[TMP2]]
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TERMINATED_BY_UPPER]], ptr [[TMP4]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = load { ptr, ptr }, ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret { ptr, ptr } [[TMP5]]
//
int *__indexable safe(int *__null_terminated p) {
  return __terminated_by_to_indexable(p);
}

// CHECK-LABEL: define dso_local { ptr, ptr } @unsafe(
// CHECK-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[TERMINATED_BY_LEN:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store i64 0, ptr [[TERMINATED_BY_LEN]], align 8
// CHECK-NEXT:    br label %[[TERMINATED_BY_LOOP_COND:.*]]
// CHECK:       [[TERMINATED_BY_LOOP_COND]]:
// CHECK-NEXT:    [[TERMINATED_BY_LEN1:%.*]] = load i64, ptr [[TERMINATED_BY_LEN]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 [[TERMINATED_BY_LEN1]]
// CHECK-NEXT:    [[TERMINATED_BY_ELEM:%.*]] = load i32, ptr [[TMP1]], align 4
// CHECK-NEXT:    [[TERMINTED_BY_CHECK_TERMINATOR:%.*]] = icmp eq i32 [[TERMINATED_BY_ELEM]], 0
// CHECK-NEXT:    br i1 [[TERMINTED_BY_CHECK_TERMINATOR]], label %[[TERMINATED_BY_LOOP_END:.*]], label %[[TERMINATED_BY_LOOP_CONT:.*]]
// CHECK:       [[TERMINATED_BY_LOOP_CONT]]:
// CHECK-NEXT:    [[TERMINATED_BY_NEW_LEN:%.*]] = add i64 [[TERMINATED_BY_LEN1]], 1
// CHECK-NEXT:    store i64 [[TERMINATED_BY_NEW_LEN]], ptr [[TERMINATED_BY_LEN]], align 8
// CHECK-NEXT:    br label %[[TERMINATED_BY_LOOP_COND]]
// CHECK:       [[TERMINATED_BY_LOOP_END]]:
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[TERMINATED_BY_LEN]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = add i64 [[TMP2]], 1
// CHECK-NEXT:    [[TERMINATED_BY_UPPER:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 [[TMP3]]
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP4]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TERMINATED_BY_UPPER]], ptr [[TMP5]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = load { ptr, ptr }, ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret { ptr, ptr } [[TMP6]]
//
int *__indexable unsafe(int *__null_terminated p) {
  return __unsafe_terminated_by_to_indexable(p);
}

// CHECK-LABEL: define dso_local { ptr, ptr } @nested(
// CHECK-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable.0", align 8
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[TERMINATED_BY_LEN:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store i64 0, ptr [[TERMINATED_BY_LEN]], align 8
// CHECK-NEXT:    br label %[[TERMINATED_BY_LOOP_COND:.*]]
// CHECK:       [[TERMINATED_BY_LOOP_COND]]:
// CHECK-NEXT:    [[TERMINATED_BY_LEN1:%.*]] = load i64, ptr [[TERMINATED_BY_LEN]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds ptr, ptr [[TMP0]], i64 [[TERMINATED_BY_LEN1]]
// CHECK-NEXT:    [[TERMINATED_BY_ELEM:%.*]] = load ptr, ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TERMINTED_BY_CHECK_TERMINATOR:%.*]] = icmp eq ptr [[TERMINATED_BY_ELEM]], inttoptr (i64 -1 to ptr)
// CHECK-NEXT:    br i1 [[TERMINTED_BY_CHECK_TERMINATOR]], label %[[TERMINATED_BY_LOOP_END:.*]], label %[[TERMINATED_BY_LOOP_CONT:.*]]
// CHECK:       [[TERMINATED_BY_LOOP_CONT]]:
// CHECK-NEXT:    [[TERMINATED_BY_NEW_LEN:%.*]] = add i64 [[TERMINATED_BY_LEN1]], 1
// CHECK-NEXT:    store i64 [[TERMINATED_BY_NEW_LEN]], ptr [[TERMINATED_BY_LEN]], align 8
// CHECK-NEXT:    br label %[[TERMINATED_BY_LOOP_COND]]
// CHECK:       [[TERMINATED_BY_LOOP_END]]:
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[TERMINATED_BY_LEN]], align 8
// CHECK-NEXT:    [[TERMINATED_BY_UPPER:%.*]] = getelementptr inbounds ptr, ptr [[TMP0]], i64 [[TMP2]]
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable.0", ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable.0", ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TERMINATED_BY_UPPER]], ptr [[TMP4]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = load { ptr, ptr }, ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret { ptr, ptr } [[TMP5]]
//
int *__single *__indexable nested(int *__single *__terminated_by(-1) p) {
  return __terminated_by_to_indexable(p);
}
