// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

// CHECK-LABEL: define dso_local void @good_assign(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_assign(void) {
  char array[__null_terminated 2] = {1, 0};
  char *__null_terminated p = array;
  *p = 42;
}

// CHECK-LABEL: define dso_local void @good_compound_assign(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_compound_assign(void) {
  char array[__null_terminated 2] = {1, 0};
  char *__null_terminated p = array;
  *p += 42;
}

// CHECK-LABEL: define dso_local void @good_subscript(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void good_subscript(void) {
  char array[__null_terminated 2] = {1, 0};
  char *__null_terminated p = array;
  p[0] = 42;
}

// CHECK-LABEL: define dso_local void @bad_assign(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void bad_assign(void) {
  char array[__null_terminated 2] = {1, 0};
  char *__null_terminated p = array;
  p++;
  *p = 42;
}

// CHECK-LABEL: define dso_local void @bad_compound_assign(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void bad_compound_assign(void) {
  char array[__null_terminated 2] = {1, 0};
  char *__null_terminated p = array;
  p++;
  *p += 42;
}

// CHECK-LABEL: define dso_local void @bad_subscript(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void bad_subscript(void) {
  char array[__null_terminated 2] = {1, 0};
  char *__null_terminated p = array;
  p++;
  p[0] = 42;
}
