// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6

// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

// CHECK-LABEL: define dso_local { ptr, ptr } @safe(
// CHECK-SAME: ptr noundef [[P:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[CALL:%.*]] = call i64 @strlen(ptr noundef [[TMP0]])
// CHECK-NEXT:    [[TERMINATED_BY_UPPER:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 [[CALL]]
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TERMINATED_BY_UPPER]], ptr [[TMP2]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load { ptr, ptr }, ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret { ptr, ptr } [[TMP3]]
//
const char *__indexable safe(const char *__null_terminated p) {
  return __terminated_by_to_indexable(p);
}

// CHECK-LABEL: define dso_local { ptr, ptr } @unsafe(
// CHECK-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[CALL:%.*]] = call i64 @strlen(ptr noundef [[TMP0]])
// CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[CALL]], 1
// CHECK-NEXT:    [[TERMINATED_BY_UPPER:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 [[TMP1]]
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TERMINATED_BY_UPPER]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = load { ptr, ptr }, ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret { ptr, ptr } [[TMP4]]
//
const char *__indexable unsafe(const char *__null_terminated p) {
  return __unsafe_terminated_by_to_indexable(p);
}
