// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6

// REQUIRES: x86-registered-target

// Disable loop idiom recognize for wcslen() as a workaround for rdar://148775324
// (https://github.com/llvm/llvm-project/issues/134736).
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -mllvm -disable-loop-idiom-wcslen -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -mllvm -disable-loop-idiom-wcslen -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

// CHECK-LABEL: define dso_local { ptr, ptr } @safe(
// CHECK-SAME: ptr noundef [[P:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    br label %[[TERMINATED_BY_LOOP_COND:.*]]
// CHECK:       [[TERMINATED_BY_LOOP_COND]]:
// CHECK-NEXT:    [[TERMINATED_BY_LEN_0:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[TERMINATED_BY_NEW_LEN:%.*]], %[[TERMINATED_BY_LOOP_COND]] ]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds [4 x i8], ptr [[P]], i64 [[TERMINATED_BY_LEN_0]]
// CHECK-NEXT:    [[TERMINATED_BY_ELEM:%.*]] = load i32, ptr [[TMP0]], align 4
// CHECK-NEXT:    [[TERMINTED_BY_CHECK_TERMINATOR:%.*]] = icmp eq i32 [[TERMINATED_BY_ELEM]], 0
// CHECK-NEXT:    [[TERMINATED_BY_NEW_LEN]] = add i64 [[TERMINATED_BY_LEN_0]], 1
// CHECK-NEXT:    br i1 [[TERMINTED_BY_CHECK_TERMINATOR]], label %[[TERMINATED_BY_LOOP_END:.*]], label %[[TERMINATED_BY_LOOP_COND]]
// CHECK:       [[TERMINATED_BY_LOOP_END]]:
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds [4 x i8], ptr [[P]], i64 [[TERMINATED_BY_LEN_0]]
// CHECK-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue { ptr, ptr } poison, ptr [[P]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue { ptr, ptr } [[DOTFCA_0_INSERT]], ptr [[TMP1]], 1
// CHECK-NEXT:    ret { ptr, ptr } [[DOTFCA_1_INSERT]]
//
int *__indexable safe(int *__null_terminated p) {
  return __terminated_by_to_indexable(p);
}

// CHECK-LABEL: define dso_local { ptr, ptr } @unsafe(
// CHECK-SAME: ptr noundef [[P:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    br label %[[TERMINATED_BY_LOOP_COND:.*]]
// CHECK:       [[TERMINATED_BY_LOOP_COND]]:
// CHECK-NEXT:    [[TERMINATED_BY_LEN_0:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[TERMINATED_BY_NEW_LEN:%.*]], %[[TERMINATED_BY_LOOP_COND]] ]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds [4 x i8], ptr [[P]], i64 [[TERMINATED_BY_LEN_0]]
// CHECK-NEXT:    [[TERMINATED_BY_ELEM:%.*]] = load i32, ptr [[TMP0]], align 4
// CHECK-NEXT:    [[TERMINTED_BY_CHECK_TERMINATOR:%.*]] = icmp eq i32 [[TERMINATED_BY_ELEM]], 0
// CHECK-NEXT:    [[TERMINATED_BY_NEW_LEN]] = add i64 [[TERMINATED_BY_LEN_0]], 1
// CHECK-NEXT:    br i1 [[TERMINTED_BY_CHECK_TERMINATOR]], label %[[TERMINATED_BY_LOOP_END:.*]], label %[[TERMINATED_BY_LOOP_COND]]
// CHECK:       [[TERMINATED_BY_LOOP_END]]:
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds [4 x i8], ptr [[P]], i64 [[TERMINATED_BY_LEN_0]]
// CHECK-NEXT:    [[TERMINATED_BY_UPPER:%.*]] = getelementptr i8, ptr [[TMP1]], i64 4
// CHECK-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue { ptr, ptr } poison, ptr [[P]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue { ptr, ptr } [[DOTFCA_0_INSERT]], ptr [[TERMINATED_BY_UPPER]], 1
// CHECK-NEXT:    ret { ptr, ptr } [[DOTFCA_1_INSERT]]
//
int *__indexable unsafe(int *__null_terminated p) {
  return __unsafe_terminated_by_to_indexable(p);
}

// CHECK-LABEL: define dso_local { ptr, ptr } @nested(
// CHECK-SAME: ptr noundef [[P:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    br label %[[TERMINATED_BY_LOOP_COND:.*]]
// CHECK:       [[TERMINATED_BY_LOOP_COND]]:
// CHECK-NEXT:    [[TERMINATED_BY_LEN_0:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[TERMINATED_BY_NEW_LEN:%.*]], %[[TERMINATED_BY_LOOP_COND]] ]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds [8 x i8], ptr [[P]], i64 [[TERMINATED_BY_LEN_0]]
// CHECK-NEXT:    [[TERMINATED_BY_ELEM:%.*]] = load ptr, ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TERMINTED_BY_CHECK_TERMINATOR:%.*]] = icmp eq ptr [[TERMINATED_BY_ELEM]], inttoptr (i64 -1 to ptr)
// CHECK-NEXT:    [[TERMINATED_BY_NEW_LEN]] = add i64 [[TERMINATED_BY_LEN_0]], 1
// CHECK-NEXT:    br i1 [[TERMINTED_BY_CHECK_TERMINATOR]], label %[[TERMINATED_BY_LOOP_END:.*]], label %[[TERMINATED_BY_LOOP_COND]]
// CHECK:       [[TERMINATED_BY_LOOP_END]]:
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds [8 x i8], ptr [[P]], i64 [[TERMINATED_BY_LEN_0]]
// CHECK-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue { ptr, ptr } poison, ptr [[P]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue { ptr, ptr } [[DOTFCA_0_INSERT]], ptr [[TMP1]], 1
// CHECK-NEXT:    ret { ptr, ptr } [[DOTFCA_1_INSERT]]
//
int *__single *__indexable nested(int *__single *__terminated_by(-1) p) {
  return __terminated_by_to_indexable(p);
}
