// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --version 6
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

// CHECK-LABEL: define dso_local noundef ptr @indexable(
// CHECK-SAME: ptr noundef readonly returned captures(address, ret: address, provenance) [[PTR_COERCE0:%.*]], ptr noundef readnone captures(address) [[PTR_COERCE1:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[PTR_COERCE0]], i64 4, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[PTR_COERCE1]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[PTR_COERCE0]], [[TMP0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = and i1 [[TMP1]], [[TMP2]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[TERMINATED_BY_LOOP_COND:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[TERMINATED_BY_LOOP_COND]]:
// CHECK-NEXT:    [[TERMINATED_BY_CUR_0:%.*]] = phi ptr [ [[TERMINATED_BY_ONE_PAST_CUR:%.*]], %[[CONT3:.*]] ], [ [[PTR_COERCE0]], %[[ENTRY]] ]
// CHECK-NEXT:    [[TERMINATED_BY_ONE_PAST_CUR]] = getelementptr inbounds nuw i8, ptr [[TERMINATED_BY_CUR_0]], i64 4, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TERMINATED_BY_CHECK_ACCESS_NOT:%.*]] = icmp ugt ptr [[TERMINATED_BY_ONE_PAST_CUR]], [[PTR_COERCE1]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[TERMINATED_BY_CHECK_ACCESS_NOT]], label %[[TRAP]], label %[[CONT3]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT3]]:
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TERMINATED_BY_CUR_0]], align 4
// CHECK-NEXT:    [[TERMINATED_BY_CHECK_TERMINATOR:%.*]] = icmp eq i32 [[TMP3]], 0
// CHECK-NEXT:    br i1 [[TERMINATED_BY_CHECK_TERMINATOR]], label %[[TERMINATED_BY_LOOP_END:.*]], label %[[TERMINATED_BY_LOOP_COND]]
// CHECK:       [[TERMINATED_BY_LOOP_END]]:
// CHECK-NEXT:    ret ptr [[PTR_COERCE0]]
//
int *__null_terminated indexable(int *__indexable ptr) {
  return __unsafe_null_terminated_from_indexable(ptr);
}

// CHECK-LABEL: define dso_local ptr @bidi_indexable(
// CHECK-SAME: ptr noundef readonly byval(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 captures(none) [[PTR:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AGG_TEMP1_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// CHECK-NEXT:    [[AGG_TEMP1_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// CHECK-NEXT:    [[AGG_TEMP1_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP1_SROA_2_0_PTR_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP1_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// CHECK-NEXT:    [[AGG_TEMP1_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP1_SROA_3_0_PTR_SROA_IDX]], align 8, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ult ptr [[AGG_TEMP1_SROA_0_0_COPYLOAD]], [[AGG_TEMP1_SROA_3_0_COPYLOAD]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[DOTNOT]], label %[[TRAP:.*]], label %[[CONT:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[AGG_TEMP1_SROA_0_0_COPYLOAD]], i64 4, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[AGG_TEMP1_SROA_2_0_COPYLOAD]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[AGG_TEMP1_SROA_0_0_COPYLOAD]], [[TMP0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = and i1 [[TMP1]], [[TMP2]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[TERMINATED_BY_LOOP_COND:.*]], label %[[TRAP]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TERMINATED_BY_LOOP_COND]]:
// CHECK-NEXT:    [[TERMINATED_BY_CUR_0:%.*]] = phi ptr [ [[TERMINATED_BY_ONE_PAST_CUR:%.*]], %[[CONT9:.*]] ], [ [[AGG_TEMP1_SROA_0_0_COPYLOAD]], %[[CONT]] ]
// CHECK-NEXT:    [[TERMINATED_BY_ONE_PAST_CUR]] = getelementptr inbounds nuw i8, ptr [[TERMINATED_BY_CUR_0]], i64 4, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TERMINATED_BY_CHECK_ACCESS_NOT:%.*]] = icmp ugt ptr [[TERMINATED_BY_ONE_PAST_CUR]], [[AGG_TEMP1_SROA_2_0_COPYLOAD]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[TERMINATED_BY_CHECK_ACCESS_NOT]], label %[[TRAP]], label %[[CONT9]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT9]]:
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TERMINATED_BY_CUR_0]], align 4
// CHECK-NEXT:    [[TERMINATED_BY_CHECK_TERMINATOR:%.*]] = icmp eq i32 [[TMP3]], 0
// CHECK-NEXT:    br i1 [[TERMINATED_BY_CHECK_TERMINATOR]], label %[[TERMINATED_BY_LOOP_END:.*]], label %[[TERMINATED_BY_LOOP_COND]]
// CHECK:       [[TERMINATED_BY_LOOP_END]]:
// CHECK-NEXT:    ret ptr [[AGG_TEMP1_SROA_0_0_COPYLOAD]]
//
int *__null_terminated bidi_indexable(int *__bidi_indexable ptr) {
  return __unsafe_null_terminated_from_indexable(ptr);
}

// CHECK-LABEL: define dso_local noundef ptr @nested_indexable(
// CHECK-SAME: ptr noundef readonly returned captures(address, ret: address, provenance) [[PTR_COERCE0:%.*]], ptr noundef readnone captures(address) [[PTR_COERCE1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[PTR_COERCE0]], i64 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[PTR_COERCE1]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[PTR_COERCE0]], [[TMP0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = and i1 [[TMP1]], [[TMP2]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[TERMINATED_BY_LOOP_COND:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[TERMINATED_BY_LOOP_COND]]:
// CHECK-NEXT:    [[TERMINATED_BY_CUR_0:%.*]] = phi ptr [ [[TERMINATED_BY_ONE_PAST_CUR:%.*]], %[[CONT3:.*]] ], [ [[PTR_COERCE0]], %[[ENTRY]] ]
// CHECK-NEXT:    [[TERMINATED_BY_ONE_PAST_CUR]] = getelementptr inbounds nuw i8, ptr [[TERMINATED_BY_CUR_0]], i64 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TERMINATED_BY_CHECK_ACCESS_NOT:%.*]] = icmp ugt ptr [[TERMINATED_BY_ONE_PAST_CUR]], [[PTR_COERCE1]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[TERMINATED_BY_CHECK_ACCESS_NOT]], label %[[TRAP]], label %[[CONT3]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[CONT3]]:
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TERMINATED_BY_CUR_0]], align 8
// CHECK-NEXT:    [[TERMINATED_BY_CHECK_TERMINATOR:%.*]] = icmp eq ptr [[TMP3]], inttoptr (i64 -1 to ptr)
// CHECK-NEXT:    br i1 [[TERMINATED_BY_CHECK_TERMINATOR]], label %[[TERMINATED_BY_LOOP_END:.*]], label %[[TERMINATED_BY_LOOP_COND]]
// CHECK:       [[TERMINATED_BY_LOOP_END]]:
// CHECK-NEXT:    ret ptr [[PTR_COERCE0]]
//
int *__single *__terminated_by(-1) nested_indexable(int *__single *__indexable ptr) {
  return __unsafe_terminated_by_from_indexable(-1, ptr);
}
