// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 3
// RUN: %clang_cc1 -triple x86_64 -fbounds-safety -ftrap-function=fb_trap -ftrap-function-returns -emit-llvm %s -o - | FileCheck %s --check-prefix=X86_64

#include <ptrcheck.h>

// X86_64-LABEL: define dso_local i32 @foo(
// X86_64-SAME: ptr noundef [[BAR:%.*]], i32 noundef [[COUNT:%.*]]) #[[ATTR0:[0-9]+]] {
// X86_64-NEXT:  entry:
// X86_64-NEXT:    [[BAR_ADDR:%.*]] = alloca ptr, align 8
// X86_64-NEXT:    [[COUNT_ADDR:%.*]] = alloca i32, align 4
// X86_64-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// X86_64-NEXT:    store ptr [[BAR]], ptr [[BAR_ADDR]], align 8
// X86_64-NEXT:    store i32 [[COUNT]], ptr [[COUNT_ADDR]], align 4
// X86_64-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[BAR_ADDR]], align 8
// X86_64-NEXT:    [[TMP1:%.*]] = load i32, ptr [[COUNT_ADDR]], align 4
// X86_64-NEXT:    [[IDX_EXT:%.*]] = zext i32 [[TMP1]] to i64
// X86_64-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i32, ptr [[TMP0]], i64 [[IDX_EXT]]
// X86_64-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// X86_64-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
// X86_64-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// X86_64-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP3]], align 8
// X86_64-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// X86_64-NEXT:    store ptr [[TMP0]], ptr [[TMP4]], align 8
// X86_64-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// X86_64-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// X86_64-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 1
// X86_64-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// X86_64-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// X86_64-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// X86_64-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// X86_64-NEXT:    [[TMP5:%.*]] = getelementptr i32, ptr [[ARRAYIDX]], i64 1, !annotation [[META1:![0-9]+]]
// X86_64-NEXT:    [[TMP6:%.*]] = icmp ule ptr [[TMP5]], [[WIDE_PTR_UB]], !annotation [[META1]]
// X86_64-NEXT:    br i1 [[TMP6]], label [[CONT:%.*]], label [[TRAP:%.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// X86_64:       trap:
// X86_64-NEXT:    call void @fb_trap(i8 25) #[[ATTR1:[0-9]+]], !annotation [[META1]]
// X86_64-NEXT:    br label [[CONT]], !annotation [[META1]]
// X86_64:       cont:
// X86_64-NEXT:    [[TMP7:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP5]], !annotation [[META1]]
// X86_64-NEXT:    br i1 [[TMP7]], label [[CONT2:%.*]], label [[TRAP1:%.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// X86_64:       trap1:
// X86_64-NEXT:    call void @fb_trap(i8 25) #[[ATTR1]], !annotation [[META1]]
// X86_64-NEXT:    br label [[CONT2]], !annotation [[META1]]
// X86_64:       cont2:
// X86_64-NEXT:    [[TMP8:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META3:![0-9]+]]
// X86_64-NEXT:    br i1 [[TMP8]], label [[CONT4:%.*]], label [[TRAP3:%.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// X86_64:       trap3:
// X86_64-NEXT:    call void @fb_trap(i8 25) #[[ATTR1]], !annotation [[META3]]
// X86_64-NEXT:    br label [[CONT4]], !annotation [[META3]]
// X86_64:       cont4:
// X86_64-NEXT:    [[TMP9:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// X86_64-NEXT:    ret i32 [[TMP9]]
//
int foo(int *__counted_by(count) bar, unsigned count) {
    return bar[1];
}
