// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --version 6
// RUN: %clang_cc1 -fbounds-safety -fbounds-safety-bringup-missing-checks=batch_0 -fno-bounds-safety-bringup-missing-checks=array_subscript_agg -triple x86_64-linux-gnu -emit-llvm -fsanitize=null,alignment,array-bounds -Wno-array-bounds -std=c11 -O0 %s -o - | FileCheck %s --check-prefixes=STRUCT
// RUN: %clang_cc1 -fbounds-safety -fbounds-safety-bringup-missing-checks=batch_0 -fno-bounds-safety-bringup-missing-checks=array_subscript_agg -triple x86_64-linux-gnu -emit-llvm -fsanitize=null,alignment,array-bounds -Wno-array-bounds -std=c11 -O0 -DUSE_UNION %s -o - | FileCheck %s --check-prefixes=UNION

#ifdef USE_UNION
union Agg { int x; };
#define AGG union Agg
#else
struct Agg { int x; };
#define AGG struct Agg
#endif

// LHS checks
// STRUCT-LABEL: define dso_local void @test_lhs_ptrcheck_deref(
// STRUCT-SAME: ptr noundef [[DEST:%.*]]) #[[ATTR0:[0-9]+]] {
// STRUCT-NEXT:  [[ENTRY:.*:]]
// STRUCT-NEXT:    [[DEST_ADDR:%.*]] = alloca ptr, align 8
// STRUCT-NEXT:    [[LOCAL:%.*]] = alloca [[STRUCT_AGG:%.*]], align 4
// STRUCT-NEXT:    store ptr [[DEST]], ptr [[DEST_ADDR]], align 8
// STRUCT-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[LOCAL]], i8 0, i64 4, i1 false)
// STRUCT-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[DEST_ADDR]], align 8
// STRUCT-NEXT:    [[TMP1:%.*]] = icmp ne ptr [[TMP0]], null, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[TMP0]] to i64, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP3:%.*]] = and i64 [[TMP2]], 3, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP4:%.*]] = icmp eq i64 [[TMP3]], 0, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP5:%.*]] = and i1 [[TMP1]], [[TMP4]], {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    br i1 [[TMP5]], label %[[CONT:.*]], label %[[HANDLER_TYPE_MISMATCH:.*]], {{!prof ![0-9]+}}, {{!nosanitize ![0-9]+}}
// STRUCT:       [[HANDLER_TYPE_MISMATCH]]:
// STRUCT-NEXT:    call void @__ubsan_handle_type_mismatch_v1_abort(ptr @[[GLOB1:[0-9]+]], i64 [[TMP2]]) #[[ATTR5:[0-9]+]], {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    unreachable, {{!nosanitize ![0-9]+}}
// STRUCT:       [[CONT]]:
// STRUCT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[TMP0]], ptr align 4 [[LOCAL]], i64 4, i1 false)
// STRUCT-NEXT:    ret void
//
// UNION-LABEL: define dso_local void @test_lhs_ptrcheck_deref(
// UNION-SAME: ptr noundef [[DEST:%.*]]) #[[ATTR0:[0-9]+]] {
// UNION-NEXT:  [[ENTRY:.*:]]
// UNION-NEXT:    [[DEST_ADDR:%.*]] = alloca ptr, align 8
// UNION-NEXT:    [[LOCAL:%.*]] = alloca [[UNION_AGG:%.*]], align 4
// UNION-NEXT:    store ptr [[DEST]], ptr [[DEST_ADDR]], align 8
// UNION-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[LOCAL]], i8 0, i64 4, i1 false)
// UNION-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[DEST_ADDR]], align 8
// UNION-NEXT:    [[TMP1:%.*]] = icmp ne ptr [[TMP0]], null, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[TMP0]] to i64, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP3:%.*]] = and i64 [[TMP2]], 3, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP4:%.*]] = icmp eq i64 [[TMP3]], 0, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP5:%.*]] = and i1 [[TMP1]], [[TMP4]], {{!nosanitize ![0-9]+}}
// UNION-NEXT:    br i1 [[TMP5]], label %[[CONT:.*]], label %[[HANDLER_TYPE_MISMATCH:.*]], {{!prof ![0-9]+}}, {{!nosanitize ![0-9]+}}
// UNION:       [[HANDLER_TYPE_MISMATCH]]:
// UNION-NEXT:    call void @__ubsan_handle_type_mismatch_v1_abort(ptr @[[GLOB1:[0-9]+]], i64 [[TMP2]]) #[[ATTR5:[0-9]+]], {{!nosanitize ![0-9]+}}
// UNION-NEXT:    unreachable, {{!nosanitize ![0-9]+}}
// UNION:       [[CONT]]:
// UNION-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[TMP0]], ptr align 4 [[LOCAL]], i64 4, i1 false)
// UNION-NEXT:    ret void
//
void test_lhs_ptrcheck_deref(AGG *dest) {
  AGG local = {0};
  *dest = local;
}

// STRUCT-LABEL: define dso_local void @test_lhs_ptrcheck_subscript(
// STRUCT-SAME: ptr noundef [[ARR:%.*]]) #[[ATTR0]] {
// STRUCT-NEXT:  [[ENTRY:.*:]]
// STRUCT-NEXT:    [[ARR_ADDR:%.*]] = alloca ptr, align 8
// STRUCT-NEXT:    [[LOCAL:%.*]] = alloca [[STRUCT_AGG:%.*]], align 4
// STRUCT-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// STRUCT-NEXT:    store ptr [[ARR]], ptr [[ARR_ADDR]], align 8
// STRUCT-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[LOCAL]], i8 0, i64 4, i1 false)
// STRUCT-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[ARR_ADDR]], align 8
// STRUCT-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds [[STRUCT_AGG]], ptr [[TMP0]], i64 4
// STRUCT-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// STRUCT-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 8
// STRUCT-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// STRUCT-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP2]], align 8
// STRUCT-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// STRUCT-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// STRUCT-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// STRUCT-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// STRUCT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [[STRUCT_AGG]], ptr [[WIDE_PTR_PTR]], i64 0
// STRUCT-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// STRUCT-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// STRUCT-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// STRUCT-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// STRUCT-NEXT:    [[TMP4:%.*]] = getelementptr [[STRUCT_AGG]], ptr [[ARRAYIDX]], i64 1, {{!annotation ![0-9]+}}
// STRUCT-NEXT:    [[TMP5:%.*]] = icmp ule ptr [[TMP4]], [[WIDE_PTR_UB]], {{!annotation ![0-9]+}}
// STRUCT-NEXT:    br i1 [[TMP5]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// STRUCT:       [[TRAP]]:
// STRUCT-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// STRUCT-NEXT:    unreachable, {{!annotation ![0-9]+}}
// STRUCT:       [[CONT]]:
// STRUCT-NEXT:    [[TMP6:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP4]], {{!annotation ![0-9]+}}
// STRUCT-NEXT:    br i1 [[TMP6]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// STRUCT:       [[TRAP1]]:
// STRUCT-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// STRUCT-NEXT:    unreachable, {{!annotation ![0-9]+}}
// STRUCT:       [[CONT2]]:
// STRUCT-NEXT:    [[TMP7:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], {{!annotation ![0-9]+}}
// STRUCT-NEXT:    br i1 [[TMP7]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// STRUCT:       [[TRAP3]]:
// STRUCT-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// STRUCT-NEXT:    unreachable, {{!annotation ![0-9]+}}
// STRUCT:       [[CONT4]]:
// STRUCT-NEXT:    [[TMP8:%.*]] = icmp ne ptr [[ARRAYIDX]], null, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP9:%.*]] = ptrtoint ptr [[ARRAYIDX]] to i64, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP10:%.*]] = and i64 [[TMP9]], 3, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[TMP10]], 0, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP12:%.*]] = and i1 [[TMP8]], [[TMP11]], {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    br i1 [[TMP12]], label %[[CONT5:.*]], label %[[HANDLER_TYPE_MISMATCH:.*]], {{!prof ![0-9]+}}, {{!nosanitize ![0-9]+}}
// STRUCT:       [[HANDLER_TYPE_MISMATCH]]:
// STRUCT-NEXT:    call void @__ubsan_handle_type_mismatch_v1_abort(ptr @[[GLOB2:[0-9]+]], i64 [[TMP9]]) #[[ATTR5]], {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    unreachable, {{!nosanitize ![0-9]+}}
// STRUCT:       [[CONT5]]:
// STRUCT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[ARRAYIDX]], ptr align 4 [[LOCAL]], i64 4, i1 false)
// STRUCT-NEXT:    ret void
//
// UNION-LABEL: define dso_local void @test_lhs_ptrcheck_subscript(
// UNION-SAME: ptr noundef [[ARR:%.*]]) #[[ATTR0]] {
// UNION-NEXT:  [[ENTRY:.*:]]
// UNION-NEXT:    [[ARR_ADDR:%.*]] = alloca ptr, align 8
// UNION-NEXT:    [[LOCAL:%.*]] = alloca [[UNION_AGG:%.*]], align 4
// UNION-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNION-NEXT:    store ptr [[ARR]], ptr [[ARR_ADDR]], align 8
// UNION-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[LOCAL]], i8 0, i64 4, i1 false)
// UNION-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[ARR_ADDR]], align 8
// UNION-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds [[UNION_AGG]], ptr [[TMP0]], i64 4
// UNION-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// UNION-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 8
// UNION-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// UNION-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP2]], align 8
// UNION-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// UNION-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// UNION-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// UNION-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// UNION-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [[UNION_AGG]], ptr [[WIDE_PTR_PTR]], i64 0
// UNION-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// UNION-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// UNION-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// UNION-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// UNION-NEXT:    [[TMP4:%.*]] = getelementptr [[UNION_AGG]], ptr [[ARRAYIDX]], i64 1, {{!annotation ![0-9]+}}
// UNION-NEXT:    [[TMP5:%.*]] = icmp ule ptr [[TMP4]], [[WIDE_PTR_UB]], {{!annotation ![0-9]+}}
// UNION-NEXT:    br i1 [[TMP5]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// UNION:       [[TRAP]]:
// UNION-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// UNION-NEXT:    unreachable, {{!annotation ![0-9]+}}
// UNION:       [[CONT]]:
// UNION-NEXT:    [[TMP6:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP4]], {{!annotation ![0-9]+}}
// UNION-NEXT:    br i1 [[TMP6]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// UNION:       [[TRAP1]]:
// UNION-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// UNION-NEXT:    unreachable, {{!annotation ![0-9]+}}
// UNION:       [[CONT2]]:
// UNION-NEXT:    [[TMP7:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], {{!annotation ![0-9]+}}
// UNION-NEXT:    br i1 [[TMP7]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// UNION:       [[TRAP3]]:
// UNION-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// UNION-NEXT:    unreachable, {{!annotation ![0-9]+}}
// UNION:       [[CONT4]]:
// UNION-NEXT:    [[TMP8:%.*]] = icmp ne ptr [[ARRAYIDX]], null, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP9:%.*]] = ptrtoint ptr [[ARRAYIDX]] to i64, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP10:%.*]] = and i64 [[TMP9]], 3, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[TMP10]], 0, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP12:%.*]] = and i1 [[TMP8]], [[TMP11]], {{!nosanitize ![0-9]+}}
// UNION-NEXT:    br i1 [[TMP12]], label %[[CONT5:.*]], label %[[HANDLER_TYPE_MISMATCH:.*]], {{!prof ![0-9]+}}, {{!nosanitize ![0-9]+}}
// UNION:       [[HANDLER_TYPE_MISMATCH]]:
// UNION-NEXT:    call void @__ubsan_handle_type_mismatch_v1_abort(ptr @[[GLOB2:[0-9]+]], i64 [[TMP9]]) #[[ATTR5]], {{!nosanitize ![0-9]+}}
// UNION-NEXT:    unreachable, {{!nosanitize ![0-9]+}}
// UNION:       [[CONT5]]:
// UNION-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[ARRAYIDX]], ptr align 4 [[LOCAL]], i64 4, i1 false)
// UNION-NEXT:    ret void
//
void test_lhs_ptrcheck_subscript(AGG arr[4]) {
  AGG local = {0};
  arr[0] = local;
}

// RHS checks
//
//
// STRUCT-LABEL: define dso_local void @test_rhs_ptrcheck_deref(
// STRUCT-SAME: ptr noundef [[SRC:%.*]]) #[[ATTR0]] {
// STRUCT-NEXT:  [[ENTRY:.*:]]
// STRUCT-NEXT:    [[SRC_ADDR:%.*]] = alloca ptr, align 8
// STRUCT-NEXT:    [[LOCAL:%.*]] = alloca [[STRUCT_AGG:%.*]], align 4
// STRUCT-NEXT:    store ptr [[SRC]], ptr [[SRC_ADDR]], align 8
// STRUCT-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[SRC_ADDR]], align 8
// STRUCT-NEXT:    [[TMP1:%.*]] = icmp ne ptr [[TMP0]], null, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[TMP0]] to i64, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP3:%.*]] = and i64 [[TMP2]], 3, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP4:%.*]] = icmp eq i64 [[TMP3]], 0, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP5:%.*]] = and i1 [[TMP1]], [[TMP4]], {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    br i1 [[TMP5]], label %[[CONT:.*]], label %[[HANDLER_TYPE_MISMATCH:.*]], {{!prof ![0-9]+}}, {{!nosanitize ![0-9]+}}
// STRUCT:       [[HANDLER_TYPE_MISMATCH]]:
// STRUCT-NEXT:    call void @__ubsan_handle_type_mismatch_v1_abort(ptr @[[GLOB3:[0-9]+]], i64 [[TMP2]]) #[[ATTR5]], {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    unreachable, {{!nosanitize ![0-9]+}}
// STRUCT:       [[CONT]]:
// STRUCT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[LOCAL]], ptr align 4 [[TMP0]], i64 4, i1 false)
// STRUCT-NEXT:    ret void
//
// UNION-LABEL: define dso_local void @test_rhs_ptrcheck_deref(
// UNION-SAME: ptr noundef [[SRC:%.*]]) #[[ATTR0]] {
// UNION-NEXT:  [[ENTRY:.*:]]
// UNION-NEXT:    [[SRC_ADDR:%.*]] = alloca ptr, align 8
// UNION-NEXT:    [[LOCAL:%.*]] = alloca [[UNION_AGG:%.*]], align 4
// UNION-NEXT:    store ptr [[SRC]], ptr [[SRC_ADDR]], align 8
// UNION-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[SRC_ADDR]], align 8
// UNION-NEXT:    [[TMP1:%.*]] = icmp ne ptr [[TMP0]], null, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[TMP0]] to i64, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP3:%.*]] = and i64 [[TMP2]], 3, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP4:%.*]] = icmp eq i64 [[TMP3]], 0, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP5:%.*]] = and i1 [[TMP1]], [[TMP4]], {{!nosanitize ![0-9]+}}
// UNION-NEXT:    br i1 [[TMP5]], label %[[CONT:.*]], label %[[HANDLER_TYPE_MISMATCH:.*]], {{!prof ![0-9]+}}, {{!nosanitize ![0-9]+}}
// UNION:       [[HANDLER_TYPE_MISMATCH]]:
// UNION-NEXT:    call void @__ubsan_handle_type_mismatch_v1_abort(ptr @[[GLOB3:[0-9]+]], i64 [[TMP2]]) #[[ATTR5]], {{!nosanitize ![0-9]+}}
// UNION-NEXT:    unreachable, {{!nosanitize ![0-9]+}}
// UNION:       [[CONT]]:
// UNION-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[LOCAL]], ptr align 4 [[TMP0]], i64 4, i1 false)
// UNION-NEXT:    ret void
//
void test_rhs_ptrcheck_deref(AGG *src) {
  AGG local;
  local = *src;
  (void)local;
}

//
//
// -fbounds-safety bounds checks missing here due to `-fno-bounds-safety-bringup-missing-checks=array_subscript_agg`
// UBSan checks missing here due to `-fno-bounds-safety-bringup-missing-checks=array_subscript_agg`
// STRUCT-LABEL: define dso_local void @test_rhs_ptrcheck_subscript(
// STRUCT-SAME: ptr noundef [[ARR:%.*]]) #[[ATTR0]] {
// STRUCT-NEXT:  [[ENTRY:.*:]]
// STRUCT-NEXT:    [[ARR_ADDR:%.*]] = alloca ptr, align 8
// STRUCT-NEXT:    [[LOCAL:%.*]] = alloca [[STRUCT_AGG:%.*]], align 4
// STRUCT-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// STRUCT-NEXT:    store ptr [[ARR]], ptr [[ARR_ADDR]], align 8
// STRUCT-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[ARR_ADDR]], align 8
// STRUCT-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds [[STRUCT_AGG]], ptr [[TMP0]], i64 4
// STRUCT-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// STRUCT-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 8
// STRUCT-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// STRUCT-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP2]], align 8
// STRUCT-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// STRUCT-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// STRUCT-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// STRUCT-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// STRUCT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [[STRUCT_AGG]], ptr [[WIDE_PTR_PTR]], i64 0
// STRUCT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[LOCAL]], ptr align 4 [[ARRAYIDX]], i64 4, i1 false)
// STRUCT-NEXT:    ret void
//
// UNION-LABEL: define dso_local void @test_rhs_ptrcheck_subscript(
// UNION-SAME: ptr noundef [[ARR:%.*]]) #[[ATTR0]] {
// UNION-NEXT:  [[ENTRY:.*:]]
// UNION-NEXT:    [[ARR_ADDR:%.*]] = alloca ptr, align 8
// UNION-NEXT:    [[LOCAL:%.*]] = alloca [[UNION_AGG:%.*]], align 4
// UNION-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNION-NEXT:    store ptr [[ARR]], ptr [[ARR_ADDR]], align 8
// UNION-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[ARR_ADDR]], align 8
// UNION-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds [[UNION_AGG]], ptr [[TMP0]], i64 4
// UNION-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// UNION-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 8
// UNION-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// UNION-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP2]], align 8
// UNION-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// UNION-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// UNION-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// UNION-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// UNION-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [[UNION_AGG]], ptr [[WIDE_PTR_PTR]], i64 0
// UNION-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[LOCAL]], ptr align 4 [[ARRAYIDX]], i64 4, i1 false)
// UNION-NEXT:    ret void
//
void test_rhs_ptrcheck_subscript(AGG arr[4]) {
  AGG local;
  local = arr[0];
  (void)local;
}

// RHS cases - handler call only
//
//
// STRUCT-LABEL: define dso_local void @test_init_from_ptr(
// STRUCT-SAME: ptr noundef [[SRC:%.*]]) #[[ATTR0]] {
// STRUCT-NEXT:  [[ENTRY:.*:]]
// STRUCT-NEXT:    [[SRC_ADDR:%.*]] = alloca ptr, align 8
// STRUCT-NEXT:    [[LOCAL:%.*]] = alloca [[STRUCT_AGG:%.*]], align 4
// STRUCT-NEXT:    store ptr [[SRC]], ptr [[SRC_ADDR]], align 8
// STRUCT-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[SRC_ADDR]], align 8
// STRUCT-NEXT:    [[TMP1:%.*]] = icmp ne ptr [[TMP0]], null, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[TMP0]] to i64, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP3:%.*]] = and i64 [[TMP2]], 3, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP4:%.*]] = icmp eq i64 [[TMP3]], 0, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP5:%.*]] = and i1 [[TMP1]], [[TMP4]], {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    br i1 [[TMP5]], label %[[CONT:.*]], label %[[HANDLER_TYPE_MISMATCH:.*]], {{!prof ![0-9]+}}, {{!nosanitize ![0-9]+}}
// STRUCT:       [[HANDLER_TYPE_MISMATCH]]:
// STRUCT-NEXT:    call void @__ubsan_handle_type_mismatch_v1_abort(ptr @[[GLOB4:[0-9]+]], i64 [[TMP2]]) #[[ATTR5]], {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    unreachable, {{!nosanitize ![0-9]+}}
// STRUCT:       [[CONT]]:
// STRUCT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[LOCAL]], ptr align 4 [[TMP0]], i64 4, i1 false)
// STRUCT-NEXT:    ret void
//
// UNION-LABEL: define dso_local void @test_init_from_ptr(
// UNION-SAME: ptr noundef [[SRC:%.*]]) #[[ATTR0]] {
// UNION-NEXT:  [[ENTRY:.*:]]
// UNION-NEXT:    [[SRC_ADDR:%.*]] = alloca ptr, align 8
// UNION-NEXT:    [[LOCAL:%.*]] = alloca [[UNION_AGG:%.*]], align 4
// UNION-NEXT:    store ptr [[SRC]], ptr [[SRC_ADDR]], align 8
// UNION-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[SRC_ADDR]], align 8
// UNION-NEXT:    [[TMP1:%.*]] = icmp ne ptr [[TMP0]], null, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[TMP0]] to i64, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP3:%.*]] = and i64 [[TMP2]], 3, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP4:%.*]] = icmp eq i64 [[TMP3]], 0, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP5:%.*]] = and i1 [[TMP1]], [[TMP4]], {{!nosanitize ![0-9]+}}
// UNION-NEXT:    br i1 [[TMP5]], label %[[CONT:.*]], label %[[HANDLER_TYPE_MISMATCH:.*]], {{!prof ![0-9]+}}, {{!nosanitize ![0-9]+}}
// UNION:       [[HANDLER_TYPE_MISMATCH]]:
// UNION-NEXT:    call void @__ubsan_handle_type_mismatch_v1_abort(ptr @[[GLOB4:[0-9]+]], i64 [[TMP2]]) #[[ATTR5]], {{!nosanitize ![0-9]+}}
// UNION-NEXT:    unreachable, {{!nosanitize ![0-9]+}}
// UNION:       [[CONT]]:
// UNION-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[LOCAL]], ptr align 4 [[TMP0]], i64 4, i1 false)
// UNION-NEXT:    ret void
//
void test_init_from_ptr(AGG *src) {
  AGG local = *src;
  (void)local;
}

//
//
// UBSan checks missing here due to `-fno-bounds-safety-bringup-missing-checks=array_subscript_agg`
// -fbounds-safety bounds checks missing here due to `-fno-bounds-safety-bringup-missing-checks=array_subscript_agg`
// STRUCT-LABEL: define dso_local void @test_init_from_array(
// STRUCT-SAME: ptr noundef [[ARR:%.*]]) #[[ATTR0]] {
// STRUCT-NEXT:  [[ENTRY:.*:]]
// STRUCT-NEXT:    [[ARR_ADDR:%.*]] = alloca ptr, align 8
// STRUCT-NEXT:    [[LOCAL:%.*]] = alloca [[STRUCT_AGG:%.*]], align 4
// STRUCT-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// STRUCT-NEXT:    store ptr [[ARR]], ptr [[ARR_ADDR]], align 8
// STRUCT-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[ARR_ADDR]], align 8
// STRUCT-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds [[STRUCT_AGG]], ptr [[TMP0]], i64 4
// STRUCT-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// STRUCT-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 8
// STRUCT-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// STRUCT-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP2]], align 8
// STRUCT-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// STRUCT-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// STRUCT-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// STRUCT-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// STRUCT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [[STRUCT_AGG]], ptr [[WIDE_PTR_PTR]], i64 0
// STRUCT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[LOCAL]], ptr align 4 [[ARRAYIDX]], i64 4, i1 false)
// STRUCT-NEXT:    ret void
//
// UNION-LABEL: define dso_local void @test_init_from_array(
// UNION-SAME: ptr noundef [[ARR:%.*]]) #[[ATTR0]] {
// UNION-NEXT:  [[ENTRY:.*:]]
// UNION-NEXT:    [[ARR_ADDR:%.*]] = alloca ptr, align 8
// UNION-NEXT:    [[LOCAL:%.*]] = alloca [[UNION_AGG:%.*]], align 4
// UNION-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNION-NEXT:    store ptr [[ARR]], ptr [[ARR_ADDR]], align 8
// UNION-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[ARR_ADDR]], align 8
// UNION-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds [[UNION_AGG]], ptr [[TMP0]], i64 4
// UNION-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// UNION-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 8
// UNION-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// UNION-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP2]], align 8
// UNION-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// UNION-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// UNION-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// UNION-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// UNION-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [[UNION_AGG]], ptr [[WIDE_PTR_PTR]], i64 0
// UNION-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[LOCAL]], ptr align 4 [[ARRAYIDX]], i64 4, i1 false)
// UNION-NEXT:    ret void
//
void test_init_from_array(AGG arr[4]) {
  AGG local = arr[0];
  (void)local;
}

// Array bounds - out-of-bounds access (RHS)
//
//
// UBSan checks missing here due to `-fno-bounds-safety-bringup-missing-checks=array_subscript_agg`
// -fbounds-safety bounds checks missing here due to `-fno-bounds-safety-bringup-missing-checks=array_subscript_agg`
// STRUCT-LABEL: define dso_local void @test_oob_rhs(
// STRUCT-SAME: ) #[[ATTR0]] {
// STRUCT-NEXT:  [[ENTRY:.*:]]
// STRUCT-NEXT:    [[ARR:%.*]] = alloca [4 x [[STRUCT_AGG:%.*]]], align 16
// STRUCT-NEXT:    [[LOCAL:%.*]] = alloca [[STRUCT_AGG]], align 4
// STRUCT-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [4 x [[STRUCT_AGG]]], ptr [[ARR]], i64 0, i64 0
// STRUCT-NEXT:    [[UPPER:%.*]] = getelementptr inbounds [[STRUCT_AGG]], ptr [[ARRAYDECAY]], i64 4
// STRUCT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [[STRUCT_AGG]], ptr [[ARRAYDECAY]], i64 4
// STRUCT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[LOCAL]], ptr align 16 [[ARRAYIDX]], i64 4, i1 false)
// STRUCT-NEXT:    ret void
//
// UNION-LABEL: define dso_local void @test_oob_rhs(
// UNION-SAME: ) #[[ATTR0]] {
// UNION-NEXT:  [[ENTRY:.*:]]
// UNION-NEXT:    [[ARR:%.*]] = alloca [4 x [[UNION_AGG:%.*]]], align 16
// UNION-NEXT:    [[LOCAL:%.*]] = alloca [[UNION_AGG]], align 4
// UNION-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [4 x [[UNION_AGG]]], ptr [[ARR]], i64 0, i64 0
// UNION-NEXT:    [[UPPER:%.*]] = getelementptr inbounds [[UNION_AGG]], ptr [[ARRAYDECAY]], i64 4
// UNION-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [[UNION_AGG]], ptr [[ARRAYDECAY]], i64 4
// UNION-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[LOCAL]], ptr align 16 [[ARRAYIDX]], i64 4, i1 false)
// UNION-NEXT:    ret void
//
void test_oob_rhs(void) {
  AGG arr[4];
  AGG local;
  local = arr[4];
  (void)local;
}

// Array bounds - out-of-bounds access (LHS)
// STRUCT-LABEL: define dso_local void @test_oob_lhs(
// STRUCT-SAME: ) #[[ATTR0]] {
// STRUCT-NEXT:  [[ENTRY:.*:]]
// STRUCT-NEXT:    [[ARR:%.*]] = alloca [4 x [[STRUCT_AGG:%.*]]], align 16
// STRUCT-NEXT:    [[LOCAL:%.*]] = alloca [[STRUCT_AGG]], align 4
// STRUCT-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[LOCAL]], i8 0, i64 4, i1 false)
// STRUCT-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [4 x [[STRUCT_AGG]]], ptr [[ARR]], i64 0, i64 0
// STRUCT-NEXT:    [[UPPER:%.*]] = getelementptr inbounds [[STRUCT_AGG]], ptr [[ARRAYDECAY]], i64 4
// STRUCT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [[STRUCT_AGG]], ptr [[ARRAYDECAY]], i64 4
// STRUCT-NEXT:    [[TMP0:%.*]] = getelementptr [[STRUCT_AGG]], ptr [[ARRAYIDX]], i64 1, {{!annotation ![0-9]+}}
// STRUCT-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[UPPER]], {{!annotation ![0-9]+}}
// STRUCT-NEXT:    br i1 [[TMP1]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// STRUCT:       [[TRAP]]:
// STRUCT-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// STRUCT-NEXT:    unreachable, {{!annotation ![0-9]+}}
// STRUCT:       [[CONT]]:
// STRUCT-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP0]], {{!annotation ![0-9]+}}
// STRUCT-NEXT:    br i1 [[TMP2]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// STRUCT:       [[TRAP1]]:
// STRUCT-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// STRUCT-NEXT:    unreachable, {{!annotation ![0-9]+}}
// STRUCT:       [[CONT2]]:
// STRUCT-NEXT:    [[TMP3:%.*]] = icmp uge ptr [[ARRAYIDX]], [[ARRAYDECAY]], {{!annotation ![0-9]+}}
// STRUCT-NEXT:    br i1 [[TMP3]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// STRUCT:       [[TRAP3]]:
// STRUCT-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// STRUCT-NEXT:    unreachable, {{!annotation ![0-9]+}}
// STRUCT:       [[CONT4]]:
// STRUCT-NEXT:    [[TMP4:%.*]] = icmp ne ptr [[ARRAYIDX]], null, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP5:%.*]] = ptrtoint ptr [[ARRAYIDX]] to i64, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP6:%.*]] = and i64 [[TMP5]], 15, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[TMP6]], 0, {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    [[TMP8:%.*]] = and i1 [[TMP4]], [[TMP7]], {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    br i1 [[TMP8]], label %[[CONT5:.*]], label %[[HANDLER_TYPE_MISMATCH:.*]], {{!prof ![0-9]+}}, {{!nosanitize ![0-9]+}}
// STRUCT:       [[HANDLER_TYPE_MISMATCH]]:
// STRUCT-NEXT:    call void @__ubsan_handle_type_mismatch_v1_abort(ptr @[[GLOB5:[0-9]+]], i64 [[TMP5]]) #[[ATTR5]], {{!nosanitize ![0-9]+}}
// STRUCT-NEXT:    unreachable, {{!nosanitize ![0-9]+}}
// STRUCT:       [[CONT5]]:
// STRUCT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 16 [[ARRAYIDX]], ptr align 4 [[LOCAL]], i64 4, i1 false)
// STRUCT-NEXT:    [[ARRAYDECAY6:%.*]] = getelementptr inbounds [4 x [[STRUCT_AGG]]], ptr [[ARR]], i64 0, i64 0
// STRUCT-NEXT:    [[UPPER7:%.*]] = getelementptr inbounds [[STRUCT_AGG]], ptr [[ARRAYDECAY6]], i64 4
// STRUCT-NEXT:    ret void
//
// UNION-LABEL: define dso_local void @test_oob_lhs(
// UNION-SAME: ) #[[ATTR0]] {
// UNION-NEXT:  [[ENTRY:.*:]]
// UNION-NEXT:    [[ARR:%.*]] = alloca [4 x [[UNION_AGG:%.*]]], align 16
// UNION-NEXT:    [[LOCAL:%.*]] = alloca [[UNION_AGG]], align 4
// UNION-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[LOCAL]], i8 0, i64 4, i1 false)
// UNION-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [4 x [[UNION_AGG]]], ptr [[ARR]], i64 0, i64 0
// UNION-NEXT:    [[UPPER:%.*]] = getelementptr inbounds [[UNION_AGG]], ptr [[ARRAYDECAY]], i64 4
// UNION-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [[UNION_AGG]], ptr [[ARRAYDECAY]], i64 4
// UNION-NEXT:    [[TMP0:%.*]] = getelementptr [[UNION_AGG]], ptr [[ARRAYIDX]], i64 1, {{!annotation ![0-9]+}}
// UNION-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[UPPER]], {{!annotation ![0-9]+}}
// UNION-NEXT:    br i1 [[TMP1]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// UNION:       [[TRAP]]:
// UNION-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// UNION-NEXT:    unreachable, {{!annotation ![0-9]+}}
// UNION:       [[CONT]]:
// UNION-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP0]], {{!annotation ![0-9]+}}
// UNION-NEXT:    br i1 [[TMP2]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// UNION:       [[TRAP1]]:
// UNION-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// UNION-NEXT:    unreachable, {{!annotation ![0-9]+}}
// UNION:       [[CONT2]]:
// UNION-NEXT:    [[TMP3:%.*]] = icmp uge ptr [[ARRAYIDX]], [[ARRAYDECAY]], {{!annotation ![0-9]+}}
// UNION-NEXT:    br i1 [[TMP3]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// UNION:       [[TRAP3]]:
// UNION-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// UNION-NEXT:    unreachable, {{!annotation ![0-9]+}}
// UNION:       [[CONT4]]:
// UNION-NEXT:    [[TMP4:%.*]] = icmp ne ptr [[ARRAYIDX]], null, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP5:%.*]] = ptrtoint ptr [[ARRAYIDX]] to i64, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP6:%.*]] = and i64 [[TMP5]], 15, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[TMP6]], 0, {{!nosanitize ![0-9]+}}
// UNION-NEXT:    [[TMP8:%.*]] = and i1 [[TMP4]], [[TMP7]], {{!nosanitize ![0-9]+}}
// UNION-NEXT:    br i1 [[TMP8]], label %[[CONT5:.*]], label %[[HANDLER_TYPE_MISMATCH:.*]], {{!prof ![0-9]+}}, {{!nosanitize ![0-9]+}}
// UNION:       [[HANDLER_TYPE_MISMATCH]]:
// UNION-NEXT:    call void @__ubsan_handle_type_mismatch_v1_abort(ptr @[[GLOB5:[0-9]+]], i64 [[TMP5]]) #[[ATTR5]], {{!nosanitize ![0-9]+}}
// UNION-NEXT:    unreachable, {{!nosanitize ![0-9]+}}
// UNION:       [[CONT5]]:
// UNION-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 16 [[ARRAYIDX]], ptr align 4 [[LOCAL]], i64 4, i1 false)
// UNION-NEXT:    [[ARRAYDECAY6:%.*]] = getelementptr inbounds [4 x [[UNION_AGG]]], ptr [[ARR]], i64 0, i64 0
// UNION-NEXT:    [[UPPER7:%.*]] = getelementptr inbounds [[UNION_AGG]], ptr [[ARRAYDECAY6]], i64 4
// UNION-NEXT:    ret void
//
void test_oob_lhs(void) {
  AGG arr[4];
  AGG local = {0};
  arr[4] = local;
  (void)arr;
}
