// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6


// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-O0 %s
// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-O0 %s

#include <ptrcheck.h>

// CHECK-O0-LABEL: define dso_local i64 @diff_2d(
// CHECK-O0-SAME: i32 noundef [[M:%.*]], i32 noundef [[N:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-O0-NEXT:  [[ENTRY:.*:]]
// CHECK-O0-NEXT:    [[M_ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[N_ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[SAVED_STACK:%.*]] = alloca ptr, align 8
// CHECK-O0-NEXT:    [[__VLA_EXPR0:%.*]] = alloca i64, align 8
// CHECK-O0-NEXT:    [[__VLA_EXPR1:%.*]] = alloca i64, align 8
// CHECK-O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP5:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP6:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-O0-NEXT:    store i32 [[M]], ptr [[M_ADDR]], align 4
// CHECK-O0-NEXT:    store i32 [[N]], ptr [[N_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[M_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// CHECK-O0-NEXT:    [[TMP2:%.*]] = load i32, ptr [[N_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP2]] to i64
// CHECK-O0-NEXT:    [[TMP4:%.*]] = call ptr @llvm.stacksave.p0()
// CHECK-O0-NEXT:    store ptr [[TMP4]], ptr [[SAVED_STACK]], align 8
// CHECK-O0-NEXT:    [[TMP5:%.*]] = mul nuw i64 [[TMP1]], [[TMP3]]
// CHECK-O0-NEXT:    [[VLA:%.*]] = alloca i32, i64 [[TMP5]], align 16
// CHECK-O0-NEXT:    store i64 [[TMP1]], ptr [[__VLA_EXPR0]], align 8
// CHECK-O0-NEXT:    store i64 [[TMP3]], ptr [[__VLA_EXPR1]], align 8
// CHECK-O0-NEXT:    [[TMP6:%.*]] = mul nuw i64 [[TMP1]], [[TMP3]]
// CHECK-O0-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i32, ptr [[VLA]], i64 [[TMP6]]
// CHECK-O0-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[VLA]], ptr [[TMP7]], align 8
// CHECK-O0-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER]], ptr [[TMP8]], align 8
// CHECK-O0-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[VLA]], ptr [[TMP9]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP10:%.*]] = mul i64 1, [[TMP3]]
// CHECK-O0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 [[TMP10]]
// CHECK-O0-NEXT:    [[UPPER2:%.*]] = getelementptr inbounds i32, ptr [[ARRAYIDX]], i64 [[TMP3]]
// CHECK-O0-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX]], ptr [[TMP11]], align 8
// CHECK-O0-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER2]], ptr [[TMP12]], align 8
// CHECK-O0-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX]], ptr [[TMP13]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR4:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR3]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP14:%.*]] = mul nuw i64 [[TMP1]], [[TMP3]]
// CHECK-O0-NEXT:    [[UPPER7:%.*]] = getelementptr inbounds i32, ptr [[VLA]], i64 [[TMP14]]
// CHECK-O0-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP6]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[VLA]], ptr [[TMP15]], align 8
// CHECK-O0-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP6]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER7]], ptr [[TMP16]], align 8
// CHECK-O0-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP6]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[VLA]], ptr [[TMP17]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP6]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8
// CHECK-O0-NEXT:    [[TMP18:%.*]] = mul i64 0, [[TMP3]]
// CHECK-O0-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR9]], i64 [[TMP18]]
// CHECK-O0-NEXT:    [[UPPER11:%.*]] = getelementptr inbounds i32, ptr [[ARRAYIDX10]], i64 [[TMP3]]
// CHECK-O0-NEXT:    [[TMP19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP5]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX10]], ptr [[TMP19]], align 8
// CHECK-O0-NEXT:    [[TMP20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP5]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER11]], ptr [[TMP20]], align 8
// CHECK-O0-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP5]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX10]], ptr [[TMP21]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP5]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR13:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR12]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP5]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB15:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR14]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP5]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB17:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR16]], align 8
// CHECK-O0-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR4]] to i64
// CHECK-O0-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR13]] to i64
// CHECK-O0-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
// CHECK-O0-NEXT:    [[SUB_PTR_DIV:%.*]] = sdiv exact i64 [[SUB_PTR_SUB]], 4
// CHECK-O0-NEXT:    [[TMP22:%.*]] = load ptr, ptr [[SAVED_STACK]], align 8
// CHECK-O0-NEXT:    call void @llvm.stackrestore.p0(ptr [[TMP22]])
// CHECK-O0-NEXT:    ret i64 [[SUB_PTR_DIV]]
//
unsigned long long diff_2d(int m, int n) {
  int vla[m][n];
  return vla[1] - vla[0];
}

// CHECK-O0-LABEL: define dso_local i64 @diff_3d(
// CHECK-O0-SAME: i32 noundef [[M:%.*]], i32 noundef [[N:%.*]], i32 noundef [[L:%.*]]) #[[ATTR0]] {
// CHECK-O0-NEXT:  [[ENTRY:.*:]]
// CHECK-O0-NEXT:    [[M_ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[N_ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[L_ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[SAVED_STACK:%.*]] = alloca ptr, align 8
// CHECK-O0-NEXT:    [[__VLA_EXPR0:%.*]] = alloca i64, align 8
// CHECK-O0-NEXT:    [[__VLA_EXPR1:%.*]] = alloca i64, align 8
// CHECK-O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.2", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP5:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP6:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.2", align 8
// CHECK-O0-NEXT:    store i32 [[M]], ptr [[M_ADDR]], align 4
// CHECK-O0-NEXT:    store i32 [[N]], ptr [[N_ADDR]], align 4
// CHECK-O0-NEXT:    store i32 [[L]], ptr [[L_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[M_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// CHECK-O0-NEXT:    [[TMP2:%.*]] = load i32, ptr [[N_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP2]] to i64
// CHECK-O0-NEXT:    [[TMP4:%.*]] = call ptr @llvm.stacksave.p0()
// CHECK-O0-NEXT:    store ptr [[TMP4]], ptr [[SAVED_STACK]], align 8
// CHECK-O0-NEXT:    [[TMP5:%.*]] = mul nuw i64 [[TMP1]], [[TMP3]]
// CHECK-O0-NEXT:    [[VLA:%.*]] = alloca [15 x i32], i64 [[TMP5]], align 16
// CHECK-O0-NEXT:    store i64 [[TMP1]], ptr [[__VLA_EXPR0]], align 8
// CHECK-O0-NEXT:    store i64 [[TMP3]], ptr [[__VLA_EXPR1]], align 8
// CHECK-O0-NEXT:    [[TMP6:%.*]] = mul nuw i64 [[TMP1]], [[TMP3]]
// CHECK-O0-NEXT:    [[UPPER:%.*]] = getelementptr inbounds [15 x i32], ptr [[VLA]], i64 [[TMP6]]
// CHECK-O0-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[VLA]], ptr [[TMP7]], align 8
// CHECK-O0-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER]], ptr [[TMP8]], align 8
// CHECK-O0-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP1]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[VLA]], ptr [[TMP9]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP10:%.*]] = mul i64 1, [[TMP3]]
// CHECK-O0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [15 x i32], ptr [[WIDE_PTR_PTR]], i64 [[TMP10]]
// CHECK-O0-NEXT:    [[UPPER2:%.*]] = getelementptr inbounds [15 x i32], ptr [[ARRAYIDX]], i64 [[TMP3]]
// CHECK-O0-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX]], ptr [[TMP11]], align 8
// CHECK-O0-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER2]], ptr [[TMP12]], align 8
// CHECK-O0-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX]], ptr [[TMP13]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR4:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR3]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP14:%.*]] = mul nuw i64 [[TMP1]], [[TMP3]]
// CHECK-O0-NEXT:    [[UPPER7:%.*]] = getelementptr inbounds [15 x i32], ptr [[VLA]], i64 [[TMP14]]
// CHECK-O0-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP6]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[VLA]], ptr [[TMP15]], align 8
// CHECK-O0-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP6]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER7]], ptr [[TMP16]], align 8
// CHECK-O0-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP6]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[VLA]], ptr [[TMP17]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.2", ptr [[AGG_TEMP6]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8
// CHECK-O0-NEXT:    [[TMP18:%.*]] = mul i64 0, [[TMP3]]
// CHECK-O0-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr [15 x i32], ptr [[WIDE_PTR_PTR9]], i64 [[TMP18]]
// CHECK-O0-NEXT:    [[UPPER11:%.*]] = getelementptr inbounds [15 x i32], ptr [[ARRAYIDX10]], i64 [[TMP3]]
// CHECK-O0-NEXT:    [[TMP19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP5]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX10]], ptr [[TMP19]], align 8
// CHECK-O0-NEXT:    [[TMP20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP5]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER11]], ptr [[TMP20]], align 8
// CHECK-O0-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP5]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX10]], ptr [[TMP21]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP5]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR13:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR12]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP5]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB15:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR14]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP5]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB17:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR16]], align 8
// CHECK-O0-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR4]] to i64
// CHECK-O0-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR13]] to i64
// CHECK-O0-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
// CHECK-O0-NEXT:    [[SUB_PTR_DIV:%.*]] = sdiv exact i64 [[SUB_PTR_SUB]], 60
// CHECK-O0-NEXT:    [[TMP22:%.*]] = load ptr, ptr [[SAVED_STACK]], align 8
// CHECK-O0-NEXT:    call void @llvm.stackrestore.p0(ptr [[TMP22]])
// CHECK-O0-NEXT:    ret i64 [[SUB_PTR_DIV]]
//
unsigned long long diff_3d(int m, int n, int l) {
  int vla[m][n][15];
  return vla[1] - vla[0];
}


// CHECK-O0-LABEL: define dso_local i64 @diff_3d_2(
// CHECK-O0-SAME: i32 noundef [[M:%.*]], i32 noundef [[N:%.*]], i32 noundef [[L:%.*]]) #[[ATTR0]] {
// CHECK-O0-NEXT:  [[ENTRY:.*:]]
// CHECK-O0-NEXT:    [[M_ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[N_ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[L_ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[SAVED_STACK:%.*]] = alloca ptr, align 8
// CHECK-O0-NEXT:    [[__VLA_EXPR0:%.*]] = alloca i64, align 8
// CHECK-O0-NEXT:    [[__VLA_EXPR1:%.*]] = alloca i64, align 8
// CHECK-O0-NEXT:    [[__VLA_EXPR2:%.*]] = alloca i64, align 8
// CHECK-O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.3", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.4", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP10:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP11:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.3", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP12:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.4", align 8
// CHECK-O0-NEXT:    store i32 [[M]], ptr [[M_ADDR]], align 4
// CHECK-O0-NEXT:    store i32 [[N]], ptr [[N_ADDR]], align 4
// CHECK-O0-NEXT:    store i32 [[L]], ptr [[L_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[M_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// CHECK-O0-NEXT:    [[TMP2:%.*]] = load i32, ptr [[N_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP2]] to i64
// CHECK-O0-NEXT:    [[TMP4:%.*]] = load i32, ptr [[L_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP5:%.*]] = zext i32 [[TMP4]] to i64
// CHECK-O0-NEXT:    [[TMP6:%.*]] = call ptr @llvm.stacksave.p0()
// CHECK-O0-NEXT:    store ptr [[TMP6]], ptr [[SAVED_STACK]], align 8
// CHECK-O0-NEXT:    [[TMP7:%.*]] = mul nuw i64 [[TMP1]], [[TMP3]]
// CHECK-O0-NEXT:    [[TMP8:%.*]] = mul nuw i64 [[TMP7]], [[TMP5]]
// CHECK-O0-NEXT:    [[VLA:%.*]] = alloca i32, i64 [[TMP8]], align 16
// CHECK-O0-NEXT:    store i64 [[TMP1]], ptr [[__VLA_EXPR0]], align 8
// CHECK-O0-NEXT:    store i64 [[TMP3]], ptr [[__VLA_EXPR1]], align 8
// CHECK-O0-NEXT:    store i64 [[TMP5]], ptr [[__VLA_EXPR2]], align 8
// CHECK-O0-NEXT:    [[TMP9:%.*]] = mul nuw i64 [[TMP1]], [[TMP3]]
// CHECK-O0-NEXT:    [[TMP10:%.*]] = mul nuw i64 [[TMP9]], [[TMP5]]
// CHECK-O0-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i32, ptr [[VLA]], i64 [[TMP10]]
// CHECK-O0-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.4", ptr [[AGG_TEMP2]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[VLA]], ptr [[TMP11]], align 8
// CHECK-O0-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.4", ptr [[AGG_TEMP2]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER]], ptr [[TMP12]], align 8
// CHECK-O0-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.4", ptr [[AGG_TEMP2]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[VLA]], ptr [[TMP13]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.4", ptr [[AGG_TEMP2]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP14:%.*]] = mul nuw i64 [[TMP3]], [[TMP5]]
// CHECK-O0-NEXT:    [[TMP15:%.*]] = mul i64 0, [[TMP14]]
// CHECK-O0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 [[TMP15]]
// CHECK-O0-NEXT:    [[TMP16:%.*]] = mul nuw i64 [[TMP3]], [[TMP5]]
// CHECK-O0-NEXT:    [[UPPER3:%.*]] = getelementptr inbounds i32, ptr [[ARRAYIDX]], i64 [[TMP16]]
// CHECK-O0-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.3", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX]], ptr [[TMP17]], align 8
// CHECK-O0-NEXT:    [[TMP18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.3", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER3]], ptr [[TMP18]], align 8
// CHECK-O0-NEXT:    [[TMP19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.3", ptr [[AGG_TEMP1]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX]], ptr [[TMP19]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.3", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR5:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR4]], align 8
// CHECK-O0-NEXT:    [[TMP20:%.*]] = mul i64 1, [[TMP5]]
// CHECK-O0-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR5]], i64 [[TMP20]]
// CHECK-O0-NEXT:    [[UPPER7:%.*]] = getelementptr inbounds i32, ptr [[ARRAYIDX6]], i64 [[TMP5]]
// CHECK-O0-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX6]], ptr [[TMP21]], align 8
// CHECK-O0-NEXT:    [[TMP22:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER7]], ptr [[TMP22]], align 8
// CHECK-O0-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX6]], ptr [[TMP23]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP24:%.*]] = mul nuw i64 [[TMP1]], [[TMP3]]
// CHECK-O0-NEXT:    [[TMP25:%.*]] = mul nuw i64 [[TMP24]], [[TMP5]]
// CHECK-O0-NEXT:    [[UPPER13:%.*]] = getelementptr inbounds i32, ptr [[VLA]], i64 [[TMP25]]
// CHECK-O0-NEXT:    [[TMP26:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.4", ptr [[AGG_TEMP12]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[VLA]], ptr [[TMP26]], align 8
// CHECK-O0-NEXT:    [[TMP27:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.4", ptr [[AGG_TEMP12]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER13]], ptr [[TMP27]], align 8
// CHECK-O0-NEXT:    [[TMP28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.4", ptr [[AGG_TEMP12]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[VLA]], ptr [[TMP28]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.4", ptr [[AGG_TEMP12]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR15:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR14]], align 8
// CHECK-O0-NEXT:    [[TMP29:%.*]] = mul nuw i64 [[TMP3]], [[TMP5]]
// CHECK-O0-NEXT:    [[TMP30:%.*]] = mul i64 0, [[TMP29]]
// CHECK-O0-NEXT:    [[ARRAYIDX16:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR15]], i64 [[TMP30]]
// CHECK-O0-NEXT:    [[TMP31:%.*]] = mul nuw i64 [[TMP3]], [[TMP5]]
// CHECK-O0-NEXT:    [[UPPER17:%.*]] = getelementptr inbounds i32, ptr [[ARRAYIDX16]], i64 [[TMP31]]
// CHECK-O0-NEXT:    [[TMP32:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.3", ptr [[AGG_TEMP11]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX16]], ptr [[TMP32]], align 8
// CHECK-O0-NEXT:    [[TMP33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.3", ptr [[AGG_TEMP11]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER17]], ptr [[TMP33]], align 8
// CHECK-O0-NEXT:    [[TMP34:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.3", ptr [[AGG_TEMP11]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX16]], ptr [[TMP34]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.3", ptr [[AGG_TEMP11]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR19:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR18]], align 8
// CHECK-O0-NEXT:    [[TMP35:%.*]] = mul i64 0, [[TMP5]]
// CHECK-O0-NEXT:    [[ARRAYIDX20:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR19]], i64 [[TMP35]]
// CHECK-O0-NEXT:    [[UPPER21:%.*]] = getelementptr inbounds i32, ptr [[ARRAYIDX20]], i64 [[TMP5]]
// CHECK-O0-NEXT:    [[TMP36:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP10]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX20]], ptr [[TMP36]], align 8
// CHECK-O0-NEXT:    [[TMP37:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP10]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER21]], ptr [[TMP37]], align 8
// CHECK-O0-NEXT:    [[TMP38:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP10]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYIDX20]], ptr [[TMP38]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR22:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP10]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR23:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR22]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR24:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP10]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB25:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR24]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR26:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP10]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB27:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR26]], align 8
// CHECK-O0-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR9]] to i64
// CHECK-O0-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR23]] to i64
// CHECK-O0-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
// CHECK-O0-NEXT:    [[SUB_PTR_DIV:%.*]] = sdiv exact i64 [[SUB_PTR_SUB]], 4
// CHECK-O0-NEXT:    [[TMP39:%.*]] = load ptr, ptr [[SAVED_STACK]], align 8
// CHECK-O0-NEXT:    call void @llvm.stackrestore.p0(ptr [[TMP39]])
// CHECK-O0-NEXT:    ret i64 [[SUB_PTR_DIV]]
//
unsigned long long diff_3d_2(int m, int n, int l) {
  int vla[m][n][l];
  return vla[0][1] - vla[0][0];
}
