// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6


// Showing the results are the same with or without -fbounds-safety
// RUN: %clang_cc1 -O2 -triple x86_64 -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -x objective-c -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

// CHECK-LABEL: define dso_local noundef i64 @diff_2d(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret i64 13
//
unsigned long long diff_2d(void) {
  int n = 10, m = 13;
  int vla[n][m];
  return vla[1] - vla[0];
}

// CHECK-LABEL: define dso_local noundef i64 @diff_3d(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret i64 13
//
unsigned long long diff_3d(void) {
  int n = 10, m = 13;
  int vla[n][m][15];
  return vla[1] - vla[0];
}

// CHECK-LABEL: define dso_local noundef i64 @diff_3d_2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret i64 15
//
unsigned long long diff_3d_2(void) {
  int n = 10, m = 13, l = 15;
  int vla[n][m][l];
  return vla[0][1] - vla[0][0];
}

// CHECK-LABEL: define dso_local noundef i64 @diff_2d_cast(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret i64 13
//
unsigned long long diff_2d_cast(void) {
  int n = 10, m = 13;
  int vla[n][m];
  return (int*)vla[1] - (int*)vla[0];
}

// CHECK-LABEL: define dso_local noundef i64 @diff_3d_cast(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret i64 195
//
unsigned long long diff_3d_cast(void) {
  int n = 10, m = 13, l = 15;
  int vla[n][m][l];
  return (int*)vla[1] - (int*)vla[0];
}

// CHECK-LABEL: define dso_local noundef i64 @diff_3d_cast_2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret i64 15
//
unsigned long long diff_3d_cast_2(void) {
  int n = 10, m = 13, l = 15;
  int vla[n][m][l];
  return (int*)vla[0][1] - (int*)vla[0][0];
}
