// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6
// RUN: %clang_cc1 -O2 -fbounds-safety -emit-llvm -triple arm64 %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm -triple arm64 %s -o - | FileCheck %s

#include <ptrcheck.h>

// CHECK-LABEL: define dso_local void @wide_array_subscript_ok(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void wide_array_subscript_ok() {
  int *__indexable arr[5];
  int *__indexable *__indexable buf = arr;
  buf[4] = 0;
}

// CHECK-LABEL: define dso_local void @wide_array_subscript_trap1(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void wide_array_subscript_trap1() {
  int *__indexable arr[5];
  int *__indexable *__indexable buf = arr;
  buf[5] = 0;
}

// CHECK-LABEL: define dso_local void @wide_array_subscript_trap2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void wide_array_subscript_trap2() {
  int *__indexable arr[5];
  int *__indexable *buf = arr;
  buf[-1] = 0;
}

// CHECK-LABEL: define dso_local void @wide_array_subscript_read_ok(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void wide_array_subscript_read_ok() {
  int *__indexable arr[5];
  int *__indexable *__indexable buf = arr;
  (void)buf[4];
}

// CHECK-LABEL: define dso_local void @wide_array_subscript_read_ok2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void wide_array_subscript_read_ok2() {
  int *__indexable arr[5];
  int *__indexable *__indexable buf = arr;
  (void)&buf[5];
}

// CHECK-LABEL: define dso_local void @wide_array_subscript_read_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void wide_array_subscript_read_trap() {
  int *__indexable arr[5];
  int *__indexable *__indexable buf = arr;
  (void)buf[5];
}

// CHECK-LABEL: define dso_local void @wide_deref_ok(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void wide_deref_ok() {
  int *__indexable arr[5];
  int *__indexable *buf = arr;
  *(buf + 4) = 0;
}

// CHECK-LABEL: define dso_local void @wide_deref_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void wide_deref_trap() {
  int *__indexable arr[5];
  int *__indexable *buf = arr;
  *(buf + 5) = 0;
}

struct wide_member_t {
  int *__bidi_indexable ptr;
};
// CHECK-LABEL: define dso_local void @wide_member_assign_ok(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void wide_member_assign_ok() {
  struct wide_member_t w;
  struct wide_member_t *wp = &w;
  wp->ptr = 0;
}

// CHECK-LABEL: define dso_local void @wide_member_assign_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[W:%.*]] = alloca [[STRUCT_WIDE_MEMBER_T:%.*]], align 8
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[W]]) #[[ATTR6:[0-9]+]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i8, ptr [[W]], i64 24
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[W]], i64 48
// CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ugt ptr [[TMP1]], [[TMP0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[DOTNOT]], label %[[TRAP:.*]], label %[[CONT1:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT1]]:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[W]]) #[[ATTR6]]
// CHECK-NEXT:    ret void
//
void wide_member_assign_trap() {
  struct wide_member_t w;
  struct wide_member_t *wp = &w + 1;
  wp->ptr = 0;
}
