// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6

// RUN: %clang_cc1 -O0 -fbounds-safety -emit-llvm -triple x86_64 %s -o - | FileCheck %s
// RUN: %clang_cc1 -O0 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm -triple x86_64 %s -o - | FileCheck %s
#include <ptrcheck.h>

struct foo {
    int *__counted_by(count) ptr;
    int count;
    int not_initialized;
};


// CHECK-LABEL: define dso_local i32 @bar(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[F:%.*]] = alloca [[STRUCT_FOO:%.*]], align 8
// CHECK-NEXT:    [[PTR:%.*]] = getelementptr inbounds nuw [[STRUCT_FOO]], ptr [[F]], i32 0, i32 0
// CHECK-NEXT:    store ptr null, ptr [[PTR]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw [[STRUCT_FOO]], ptr [[F]], i32 0, i32 1
// CHECK-NEXT:    store i32 0, ptr [[COUNT]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[COUNT1:%.*]] = getelementptr inbounds nuw [[STRUCT_FOO]], ptr [[F]], i32 0, i32 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT1]], align 8
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int bar(void) {
    struct foo f;
    return f.count;
}
