; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=riscv64 -mattr=+v -passes=vector-combine -S %s | FileCheck %s

; Case from #176218, final shuffle consists of all elements from %shuff0 followed by elements from %shuff1
; Was not profitable before since the combined shuffle was costed as a VRGATHER-VRGATHER.MASKED
; Now the combined shuffle is costed as a VRGATHER-VRGATHER-VRSLIDEUP
define <16 x i16> @shuffle_shuffle_disjoint(<16 x i16> %op0, <16 x i16> %op1) {
; CHECK-LABEL: define <16 x i16> @shuffle_shuffle_disjoint(
; CHECK-SAME: <16 x i16> [[OP0:%.*]], <16 x i16> [[OP1:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[SHUFF0:%.*]] = shufflevector <16 x i16> [[OP0]], <16 x i16> poison, <16 x i32> <i32 0, i32 4, i32 8, i32 12, i32 1, i32 5, i32 9, i32 13, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[SHUFF1:%.*]] = shufflevector <16 x i16> [[OP1]], <16 x i16> poison, <16 x i32> <i32 3, i32 7, i32 11, i32 15, i32 2, i32 6, i32 10, i32 14, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[MERGE:%.*]] = shufflevector <16 x i16> [[SHUFF0]], <16 x i16> [[SHUFF1]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
; CHECK-NEXT:    ret <16 x i16> [[MERGE]]
;
  %shuff0 = shufflevector <16 x i16> %op0, <16 x i16> poison, <16 x i32> <i32 0, i32 4, i32 8, i32 12, i32 1, i32 5, i32 9, i32 13, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuff1 = shufflevector <16 x i16> %op1, <16 x i16> poison, <16 x i32> <i32 3, i32 7, i32 11, i32 15, i32 2, i32 6, i32 10, i32 14, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %merge = shufflevector <16 x i16> %shuff0, <16 x i16> %shuff1, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
  ret <16 x i16> %merge
}

; The uncombined case gets costed as VRGATHER-VRGATHER-VRGATHER-VRGATHER.MASKED
define <16 x i16> @shuffle_shuffle_disjoint_unordered(<16 x i16> %op0, <16 x i16> %op1) {
; CHECK-LABEL: define <16 x i16> @shuffle_shuffle_disjoint_unordered(
; CHECK-SAME: <16 x i16> [[OP0:%.*]], <16 x i16> [[OP1:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[MERGE:%.*]] = shufflevector <16 x i16> [[OP0]], <16 x i16> [[OP1]], <16 x i32> <i32 0, i32 4, i32 26, i32 30, i32 1, i32 5, i32 9, i32 13, i32 19, i32 23, i32 27, i32 31, i32 18, i32 22, i32 8, i32 12>
; CHECK-NEXT:    ret <16 x i16> [[MERGE]]
;
  %shuff0 = shufflevector <16 x i16> %op0, <16 x i16> poison, <16 x i32> <i32 0, i32 4, i32 8, i32 12, i32 1, i32 5, i32 9, i32 13, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shuff1 = shufflevector <16 x i16> %op1, <16 x i16> poison, <16 x i32> <i32 3, i32 7, i32 11, i32 15, i32 2, i32 6, i32 10, i32 14, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %merge = shufflevector <16 x i16> %shuff0, <16 x i16> %shuff1, <16 x i32> <i32 0, i32 1, i32 22, i32 23, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 2, i32 3>
  ret <16 x i16> %merge
}
