; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=riscv64 -mcpu=sifive-p470 -p vector-combine < %s | FileCheck %s

define void @narrow_deinterleave2(ptr %p, ptr %out, i32 %evl) {
; CHECK-LABEL: define void @narrow_deinterleave2(
; CHECK-SAME: ptr [[P:%.*]], ptr [[OUT:%.*]], i32 [[EVL:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[WIDE_VP_LOAD:%.*]] = tail call <vscale x 16 x i32> @llvm.vp.load.nxv16i32.p0(ptr align 4 [[P]], <vscale x 16 x i1> splat (i1 true), i32 [[EVL]])
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <vscale x 16 x i32> [[WIDE_VP_LOAD]] to <vscale x 32 x i16>
; CHECK-NEXT:    [[TMP2:%.*]] = call { <vscale x 16 x i16>, <vscale x 16 x i16> } @llvm.vector.deinterleave2.nxv32i16(<vscale x 32 x i16> [[TMP1]])
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 16 x i16>, <vscale x 16 x i16> } [[TMP2]], 0
; CHECK-NEXT:    [[MERGE0:%.*]] = bitcast <vscale x 16 x i16> [[TMP3]] to <vscale x 8 x i32>
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <vscale x 16 x i16>, <vscale x 16 x i16> } [[TMP2]], 1
; CHECK-NEXT:    [[MERGE1:%.*]] = bitcast <vscale x 16 x i16> [[TMP4]] to <vscale x 8 x i32>
; CHECK-NEXT:    [[INTERLEAVED_VEC:%.*]] = tail call <vscale x 16 x i32> @llvm.vector.interleave2.nxv16i32(<vscale x 8 x i32> [[MERGE0]], <vscale x 8 x i32> [[MERGE1]])
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv16i32.p0(<vscale x 16 x i32> [[INTERLEAVED_VEC]], ptr align 4 [[OUT]], <vscale x 16 x i1> splat (i1 true), i32 [[EVL]])
; CHECK-NEXT:    ret void
;
  %wide.vp.load = tail call <vscale x 16 x i32> @llvm.vp.load.nxv16i32.p0(ptr align 4 %p, <vscale x 16 x i1> splat (i1 true), i32 %evl)
  %d = tail call { <vscale x 8 x i32>, <vscale x 8 x i32> } @llvm.vector.deinterleave2.nxv16i32(<vscale x 16 x i32> %wide.vp.load)
  %f0 = extractvalue { <vscale x 8 x i32>, <vscale x 8 x i32> } %d, 0
  %f1 = extractvalue { <vscale x 8 x i32>, <vscale x 8 x i32> } %d, 1
  %low0 = and <vscale x 8 x i32> %f0, splat (i32 65535)
  %low1 = shl <vscale x 8 x i32> %f1, splat (i32 16)
  %merge0 = or disjoint <vscale x 8 x i32> %low0, %low1
  %high0 = and <vscale x 8 x i32> %f1, splat (i32 -65536)
  %high1 = lshr <vscale x 8 x i32> %f0, splat (i32 16)
  %merge1 = or disjoint <vscale x 8 x i32> %high0, %high1
  %interleaved.vec = tail call <vscale x 16 x i32> @llvm.vector.interleave2.nxv16i32(<vscale x 8 x i32> %merge0, <vscale x 8 x i32> %merge1)
  tail call void @llvm.vp.store.nxv16i32.p0(<vscale x 16 x i32> %interleaved.vec, ptr align 4 %out, <vscale x 16 x i1> splat (i1 true), i32 %evl)
  ret void
}

define void @narrow_deinterleave2_commute(ptr %p, ptr %out, i32 %evl) {
; CHECK-LABEL: define void @narrow_deinterleave2_commute(
; CHECK-SAME: ptr [[P:%.*]], ptr [[OUT:%.*]], i32 [[EVL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[WIDE_VP_LOAD:%.*]] = tail call <vscale x 16 x i32> @llvm.vp.load.nxv16i32.p0(ptr align 4 [[P]], <vscale x 16 x i1> splat (i1 true), i32 [[EVL]])
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <vscale x 16 x i32> [[WIDE_VP_LOAD]] to <vscale x 32 x i16>
; CHECK-NEXT:    [[TMP2:%.*]] = call { <vscale x 16 x i16>, <vscale x 16 x i16> } @llvm.vector.deinterleave2.nxv32i16(<vscale x 32 x i16> [[TMP1]])
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 16 x i16>, <vscale x 16 x i16> } [[TMP2]], 0
; CHECK-NEXT:    [[MERGE0:%.*]] = bitcast <vscale x 16 x i16> [[TMP3]] to <vscale x 8 x i32>
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <vscale x 16 x i16>, <vscale x 16 x i16> } [[TMP2]], 1
; CHECK-NEXT:    [[MERGE1:%.*]] = bitcast <vscale x 16 x i16> [[TMP4]] to <vscale x 8 x i32>
; CHECK-NEXT:    [[INTERLEAVED_VEC:%.*]] = tail call <vscale x 16 x i32> @llvm.vector.interleave2.nxv16i32(<vscale x 8 x i32> [[MERGE0]], <vscale x 8 x i32> [[MERGE1]])
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv16i32.p0(<vscale x 16 x i32> [[INTERLEAVED_VEC]], ptr align 4 [[OUT]], <vscale x 16 x i1> splat (i1 true), i32 [[EVL]])
; CHECK-NEXT:    ret void
;
  %wide.vp.load = tail call <vscale x 16 x i32> @llvm.vp.load.nxv16i32.p0(ptr align 4 %p, <vscale x 16 x i1> splat (i1 true), i32 %evl)
  %d = tail call { <vscale x 8 x i32>, <vscale x 8 x i32> } @llvm.vector.deinterleave2.nxv16i32(<vscale x 16 x i32> %wide.vp.load)
  %f0 = extractvalue { <vscale x 8 x i32>, <vscale x 8 x i32> } %d, 0
  %f1 = extractvalue { <vscale x 8 x i32>, <vscale x 8 x i32> } %d, 1
  %high0 = and <vscale x 8 x i32> %f1, splat (i32 -65536)
  %high1 = lshr <vscale x 8 x i32> %f0, splat (i32 16)
  %merge1 = or disjoint <vscale x 8 x i32> %high1, %high0
  %low0 = and <vscale x 8 x i32> %f0, splat (i32 65535)
  %low1 = shl <vscale x 8 x i32> %f1, splat (i32 16)
  %merge0 = or disjoint <vscale x 8 x i32> %low1, %low0
  %interleaved.vec = tail call <vscale x 16 x i32> @llvm.vector.interleave2.nxv16i32(<vscale x 8 x i32> %merge0, <vscale x 8 x i32> %merge1)
  tail call void @llvm.vp.store.nxv16i32.p0(<vscale x 16 x i32> %interleaved.vec, ptr align 4 %out, <vscale x 16 x i1> splat (i1 true), i32 %evl)
  ret void
}

define void @narrow_deinterleave2_nxv4i64(ptr %p, ptr %out, i32 %evl) {
; CHECK-LABEL: define void @narrow_deinterleave2_nxv4i64(
; CHECK-SAME: ptr [[P:%.*]], ptr [[OUT:%.*]], i32 [[EVL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[WIDE_VP_LOAD:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 4 [[P]], <vscale x 4 x i1> splat (i1 true), i32 [[EVL]])
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <vscale x 4 x i64> [[WIDE_VP_LOAD]] to <vscale x 8 x i32>
; CHECK-NEXT:    [[TMP2:%.*]] = call { <vscale x 4 x i32>, <vscale x 4 x i32> } @llvm.vector.deinterleave2.nxv8i32(<vscale x 8 x i32> [[TMP1]])
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32> } [[TMP2]], 0
; CHECK-NEXT:    [[MERGE0:%.*]] = bitcast <vscale x 4 x i32> [[TMP3]] to <vscale x 2 x i64>
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32> } [[TMP2]], 1
; CHECK-NEXT:    [[MERGE1:%.*]] = bitcast <vscale x 4 x i32> [[TMP4]] to <vscale x 2 x i64>
; CHECK-NEXT:    [[INTERLEAVED_VEC:%.*]] = tail call <vscale x 4 x i64> @llvm.vector.interleave2.nxv4i64(<vscale x 2 x i64> [[MERGE0]], <vscale x 2 x i64> [[MERGE1]])
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[INTERLEAVED_VEC]], ptr align 4 [[OUT]], <vscale x 4 x i1> splat (i1 true), i32 [[EVL]])
; CHECK-NEXT:    ret void
;
  %wide.vp.load = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 4 %p, <vscale x 4 x i1> splat (i1 true), i32 %evl)
  %d = tail call { <vscale x 2 x i64>, <vscale x 2 x i64> } @llvm.vector.deinterleave2.nxv4i64(<vscale x 4 x i64> %wide.vp.load)
  %f0 = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64> } %d, 0
  %f1 = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64> } %d, 1
  %low0 = and <vscale x 2 x i64> %f0, splat (i64 4294967295)
  %low1 = shl <vscale x 2 x i64> %f1, splat (i64 32)
  %merge0 = or disjoint <vscale x 2 x i64> %low0, %low1
  %high0 = and <vscale x 2 x i64> %f1, splat (i64 -4294967296)
  %high1 = lshr <vscale x 2 x i64> %f0, splat (i64 32)
  %merge1 = or disjoint <vscale x 2 x i64> %high0, %high1
  %interleaved.vec = tail call <vscale x 4 x i64> @llvm.vector.interleave2.nxv4i64(<vscale x 2 x i64> %merge0, <vscale x 2 x i64> %merge1)
  tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %interleaved.vec, ptr align 4 %out, <vscale x 4 x i1> splat (i1 true), i32 %evl)
  ret void
}

define void @negative_narrow_deinterleave2_incorrect_mask(ptr %p, ptr %out, i32 %evl) {
; CHECK-LABEL: define void @negative_narrow_deinterleave2_incorrect_mask(
; CHECK-SAME: ptr [[P:%.*]], ptr [[OUT:%.*]], i32 [[EVL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[WIDE_VP_LOAD:%.*]] = tail call <vscale x 16 x i32> @llvm.vp.load.nxv16i32.p0(ptr align 4 [[P]], <vscale x 16 x i1> splat (i1 true), i32 [[EVL]])
; CHECK-NEXT:    [[D:%.*]] = tail call { <vscale x 8 x i32>, <vscale x 8 x i32> } @llvm.vector.deinterleave2.nxv16i32(<vscale x 16 x i32> [[WIDE_VP_LOAD]])
; CHECK-NEXT:    [[F0:%.*]] = extractvalue { <vscale x 8 x i32>, <vscale x 8 x i32> } [[D]], 0
; CHECK-NEXT:    [[F1:%.*]] = extractvalue { <vscale x 8 x i32>, <vscale x 8 x i32> } [[D]], 1
; CHECK-NEXT:    [[HIGH0:%.*]] = and <vscale x 8 x i32> [[F0]], splat (i32 -65536)
; CHECK-NEXT:    [[HIGH1:%.*]] = lshr <vscale x 8 x i32> [[F1]], splat (i32 16)
; CHECK-NEXT:    [[MERGE1:%.*]] = or disjoint <vscale x 8 x i32> [[HIGH1]], [[HIGH0]]
; CHECK-NEXT:    [[LOW0:%.*]] = and <vscale x 8 x i32> [[F0]], splat (i32 65535)
; CHECK-NEXT:    [[LOW1:%.*]] = shl <vscale x 8 x i32> [[F1]], splat (i32 16)
; CHECK-NEXT:    [[MERGE0:%.*]] = or disjoint <vscale x 8 x i32> [[LOW1]], [[LOW0]]
; CHECK-NEXT:    [[INTERLEAVED_VEC:%.*]] = tail call <vscale x 16 x i32> @llvm.vector.interleave2.nxv16i32(<vscale x 8 x i32> [[MERGE0]], <vscale x 8 x i32> [[MERGE1]])
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv16i32.p0(<vscale x 16 x i32> [[INTERLEAVED_VEC]], ptr align 4 [[OUT]], <vscale x 16 x i1> splat (i1 true), i32 [[EVL]])
; CHECK-NEXT:    ret void
;
  %wide.vp.load = tail call <vscale x 16 x i32> @llvm.vp.load.nxv16i32.p0(ptr align 4 %p, <vscale x 16 x i1> splat (i1 true), i32 %evl)
  %d = tail call { <vscale x 8 x i32>, <vscale x 8 x i32> } @llvm.vector.deinterleave2.nxv16i32(<vscale x 16 x i32> %wide.vp.load)
  %f0 = extractvalue { <vscale x 8 x i32>, <vscale x 8 x i32> } %d, 0
  %f1 = extractvalue { <vscale x 8 x i32>, <vscale x 8 x i32> } %d, 1
  ; Incorrect field to mask
  %high0 = and <vscale x 8 x i32> %f0, splat (i32 -65536)
  %high1 = lshr <vscale x 8 x i32> %f1, splat (i32 16)
  %merge1 = or disjoint <vscale x 8 x i32> %high1, %high0
  %low0 = and <vscale x 8 x i32> %f0, splat (i32 65535)
  %low1 = shl <vscale x 8 x i32> %f1, splat (i32 16)
  %merge0 = or disjoint <vscale x 8 x i32> %low1, %low0
  %interleaved.vec = tail call <vscale x 16 x i32> @llvm.vector.interleave2.nxv16i32(<vscale x 8 x i32> %merge0, <vscale x 8 x i32> %merge1)
  tail call void @llvm.vp.store.nxv16i32.p0(<vscale x 16 x i32> %interleaved.vec, ptr align 4 %out, <vscale x 16 x i1> splat (i1 true), i32 %evl)
  ret void
}

; Should bail out on non-power-of-two element widths.
define void @negative_narrow_deinterleave2_incorrect_element_width(ptr %p, ptr %out, i32 %evl) {
; CHECK-LABEL: define void @negative_narrow_deinterleave2_incorrect_element_width(
; CHECK-SAME: ptr [[P:%.*]], ptr [[OUT:%.*]], i32 [[EVL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[WIDE_VP_LOAD:%.*]] = tail call <vscale x 16 x i7> @llvm.vp.load.nxv16i7.p0(ptr align 4 [[P]], <vscale x 16 x i1> splat (i1 true), i32 [[EVL]])
; CHECK-NEXT:    [[D:%.*]] = tail call { <vscale x 8 x i7>, <vscale x 8 x i7> } @llvm.vector.deinterleave2.nxv16i7(<vscale x 16 x i7> [[WIDE_VP_LOAD]])
; CHECK-NEXT:    [[F0:%.*]] = extractvalue { <vscale x 8 x i7>, <vscale x 8 x i7> } [[D]], 0
; CHECK-NEXT:    [[F1:%.*]] = extractvalue { <vscale x 8 x i7>, <vscale x 8 x i7> } [[D]], 1
; CHECK-NEXT:    [[LOW0:%.*]] = and <vscale x 8 x i7> [[F0]], splat (i7 15)
; CHECK-NEXT:    [[LOW1:%.*]] = shl <vscale x 8 x i7> [[F1]], splat (i7 4)
; CHECK-NEXT:    [[MERGE0:%.*]] = or disjoint <vscale x 8 x i7> [[LOW0]], [[LOW1]]
; CHECK-NEXT:    [[HIGH0:%.*]] = and <vscale x 8 x i7> [[F1]], splat (i7 -16)
; CHECK-NEXT:    [[HIGH1:%.*]] = lshr <vscale x 8 x i7> [[F0]], splat (i7 3)
; CHECK-NEXT:    [[MERGE1:%.*]] = or disjoint <vscale x 8 x i7> [[HIGH0]], [[HIGH1]]
; CHECK-NEXT:    [[INTERLEAVED_VEC:%.*]] = tail call <vscale x 16 x i7> @llvm.vector.interleave2.nxv16i7(<vscale x 8 x i7> [[MERGE0]], <vscale x 8 x i7> [[MERGE1]])
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv16i7.p0(<vscale x 16 x i7> [[INTERLEAVED_VEC]], ptr align 4 [[OUT]], <vscale x 16 x i1> splat (i1 true), i32 [[EVL]])
; CHECK-NEXT:    ret void
;
  %wide.vp.load = tail call <vscale x 16 x i7> @llvm.vp.load.nxv16i7.p0(ptr align 4 %p, <vscale x 16 x i1> splat (i1 true), i32 %evl)
  %d = tail call { <vscale x 8 x i7>, <vscale x 8 x i7> } @llvm.vector.deinterleave2.nxv16i7(<vscale x 16 x i7> %wide.vp.load)
  %f0 = extractvalue { <vscale x 8 x i7>, <vscale x 8 x i7> } %d, 0
  %f1 = extractvalue { <vscale x 8 x i7>, <vscale x 8 x i7> } %d, 1
  %low0 = and <vscale x 8 x i7> %f0, splat (i7 15)
  %low1 = shl <vscale x 8 x i7> %f1, splat (i7 4)
  %merge0 = or disjoint <vscale x 8 x i7> %low0, %low1
  %high0 = and <vscale x 8 x i7> %f1, splat (i7 -16)
  %high1 = lshr <vscale x 8 x i7> %f0, splat (i7 3)
  %merge1 = or disjoint <vscale x 8 x i7> %high0, %high1
  %interleaved.vec = tail call <vscale x 16 x i7> @llvm.vector.interleave2.nxv16i7(<vscale x 8 x i7> %merge0, <vscale x 8 x i7> %merge1)
  tail call void @llvm.vp.store.nxv16i32.p0(<vscale x 16 x i7> %interleaved.vec, ptr align 4 %out, <vscale x 16 x i1> splat (i1 true), i32 %evl)
  ret void
}
