// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv32 -target-feature +v \
// RUN:     -target-feature +experimental-zvvmm -disable-O0-optnone \
// RUN:     -emit-llvm -o - %s | FileCheck --check-prefix=RV32 %s
// RUN: %clang_cc1 -triple riscv64 -target-feature +v \
// RUN:     -target-feature +experimental-zvvmm -disable-O0-optnone \
// RUN:     -emit-llvm -o - %s | FileCheck --check-prefix=RV64 %s

#include <stddef.h>
#include <riscv_vector.h>

// RV32-LABEL: define dso_local i32 @test_ime_vlen(
// RV32-SAME: ) #[[ATTR0:[0-9]+]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.ime.vlen.i32()
// RV32-NEXT:    ret i32 [[TMP0]]
//
// RV64-LABEL: define dso_local i64 @test_ime_vlen(
// RV64-SAME: ) #[[ATTR0:[0-9]+]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.ime.vlen.i64()
// RV64-NEXT:    ret i64 [[TMP0]]
//
size_t test_ime_vlen(void) {
  return __riscv_ime_vlen();
}

// RV32-LABEL: define dso_local i32 @test_ime_lambda(
// RV32-SAME: ) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.ime.lambda.i32()
// RV32-NEXT:    ret i32 [[TMP0]]
//
// RV64-LABEL: define dso_local i64 @test_ime_lambda(
// RV64-SAME: ) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.ime.lambda.i64()
// RV64-NEXT:    ret i64 [[TMP0]]
//
size_t test_ime_lambda(void) {
  return __riscv_ime_lambda();
}

// RV32-LABEL: define dso_local i32 @test_vsetlambda(
// RV32-SAME: ) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.ime.vsetlambda.nonzero.i32(i32 4)
// RV32-NEXT:    ret i32 [[TMP0]]
//
// RV64-LABEL: define dso_local i64 @test_vsetlambda(
// RV64-SAME: ) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.ime.vsetlambda.nonzero.i64(i64 4)
// RV64-NEXT:    ret i64 [[TMP0]]
//
size_t test_vsetlambda(void) {
  return __riscv_vsetlambda(4);
}

// RV32-LABEL: define dso_local i32 @test_vsetlambda_zero(
// RV32-SAME: ) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.ime.readlambda.i32()
// RV32-NEXT:    ret i32 [[TMP0]]
//
// RV64-LABEL: define dso_local i64 @test_vsetlambda_zero(
// RV64-SAME: ) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.ime.readlambda.i64()
// RV64-NEXT:    ret i64 [[TMP0]]
//
size_t test_vsetlambda_zero(void) {
  return __riscv_vsetlambda(0);
}

// RV32-LABEL: define dso_local i32 @test_vsetlambda_runtime(
// RV32-SAME: i32 noundef [[X:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// RV32-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// RV32-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// RV32-NEXT:    [[TMP1:%.*]] = icmp eq i32 [[TMP0]], 0
// RV32-NEXT:    br i1 [[TMP1]], label %[[IME_VSETLAMBDA_READ:.*]], label %[[IME_VSETLAMBDA_SET:.*]]
// RV32:       [[IME_VSETLAMBDA_READ]]:
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.ime.readlambda.i32()
// RV32-NEXT:    br label %[[IME_VSETLAMBDA_CONT:.*]]
// RV32:       [[IME_VSETLAMBDA_SET]]:
// RV32-NEXT:    [[TMP3:%.*]] = call i32 @llvm.riscv.ime.vsetlambda.nonzero.i32(i32 [[TMP0]])
// RV32-NEXT:    br label %[[IME_VSETLAMBDA_CONT]]
// RV32:       [[IME_VSETLAMBDA_CONT]]:
// RV32-NEXT:    [[TMP4:%.*]] = phi i32 [ [[TMP2]], %[[IME_VSETLAMBDA_READ]] ], [ [[TMP3]], %[[IME_VSETLAMBDA_SET]] ]
// RV32-NEXT:    ret i32 [[TMP4]]
//
// RV64-LABEL: define dso_local i64 @test_vsetlambda_runtime(
// RV64-SAME: i64 noundef [[X:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[X_ADDR:%.*]] = alloca i64, align 8
// RV64-NEXT:    store i64 [[X]], ptr [[X_ADDR]], align 8
// RV64-NEXT:    [[TMP0:%.*]] = load i64, ptr [[X_ADDR]], align 8
// RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[TMP0]], 0
// RV64-NEXT:    br i1 [[TMP1]], label %[[IME_VSETLAMBDA_READ:.*]], label %[[IME_VSETLAMBDA_SET:.*]]
// RV64:       [[IME_VSETLAMBDA_READ]]:
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.ime.readlambda.i64()
// RV64-NEXT:    br label %[[IME_VSETLAMBDA_CONT:.*]]
// RV64:       [[IME_VSETLAMBDA_SET]]:
// RV64-NEXT:    [[TMP3:%.*]] = call i64 @llvm.riscv.ime.vsetlambda.nonzero.i64(i64 [[TMP0]])
// RV64-NEXT:    br label %[[IME_VSETLAMBDA_CONT]]
// RV64:       [[IME_VSETLAMBDA_CONT]]:
// RV64-NEXT:    [[TMP4:%.*]] = phi i64 [ [[TMP2]], %[[IME_VSETLAMBDA_READ]] ], [ [[TMP3]], %[[IME_VSETLAMBDA_SET]] ]
// RV64-NEXT:    ret i64 [[TMP4]]
//
size_t test_vsetlambda_runtime(size_t x) {
  return __riscv_vsetlambda(x);
}

// RV32-LABEL: define dso_local i32 @test_vsetlambda_save_restore(
// RV32-SAME: ) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[SAVED:%.*]] = alloca i32, align 4
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.ime.readlambda.i32()
// RV32-NEXT:    store i32 [[TMP0]], ptr [[SAVED]], align 4
// RV32-NEXT:    [[TMP1:%.*]] = load i32, ptr [[SAVED]], align 4
// RV32-NEXT:    [[TMP2:%.*]] = icmp eq i32 [[TMP1]], 0
// RV32-NEXT:    br i1 [[TMP2]], label %[[IME_VSETLAMBDA_READ:.*]], label %[[IME_VSETLAMBDA_SET:.*]]
// RV32:       [[IME_VSETLAMBDA_READ]]:
// RV32-NEXT:    [[TMP3:%.*]] = call i32 @llvm.riscv.ime.readlambda.i32()
// RV32-NEXT:    br label %[[IME_VSETLAMBDA_CONT:.*]]
// RV32:       [[IME_VSETLAMBDA_SET]]:
// RV32-NEXT:    [[TMP4:%.*]] = call i32 @llvm.riscv.ime.vsetlambda.nonzero.i32(i32 [[TMP1]])
// RV32-NEXT:    br label %[[IME_VSETLAMBDA_CONT]]
// RV32:       [[IME_VSETLAMBDA_CONT]]:
// RV32-NEXT:    [[TMP5:%.*]] = phi i32 [ [[TMP3]], %[[IME_VSETLAMBDA_READ]] ], [ [[TMP4]], %[[IME_VSETLAMBDA_SET]] ]
// RV32-NEXT:    ret i32 [[TMP5]]
//
// RV64-LABEL: define dso_local i64 @test_vsetlambda_save_restore(
// RV64-SAME: ) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[SAVED:%.*]] = alloca i64, align 8
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.ime.readlambda.i64()
// RV64-NEXT:    store i64 [[TMP0]], ptr [[SAVED]], align 8
// RV64-NEXT:    [[TMP1:%.*]] = load i64, ptr [[SAVED]], align 8
// RV64-NEXT:    [[TMP2:%.*]] = icmp eq i64 [[TMP1]], 0
// RV64-NEXT:    br i1 [[TMP2]], label %[[IME_VSETLAMBDA_READ:.*]], label %[[IME_VSETLAMBDA_SET:.*]]
// RV64:       [[IME_VSETLAMBDA_READ]]:
// RV64-NEXT:    [[TMP3:%.*]] = call i64 @llvm.riscv.ime.readlambda.i64()
// RV64-NEXT:    br label %[[IME_VSETLAMBDA_CONT:.*]]
// RV64:       [[IME_VSETLAMBDA_SET]]:
// RV64-NEXT:    [[TMP4:%.*]] = call i64 @llvm.riscv.ime.vsetlambda.nonzero.i64(i64 [[TMP1]])
// RV64-NEXT:    br label %[[IME_VSETLAMBDA_CONT]]
// RV64:       [[IME_VSETLAMBDA_CONT]]:
// RV64-NEXT:    [[TMP5:%.*]] = phi i64 [ [[TMP3]], %[[IME_VSETLAMBDA_READ]] ], [ [[TMP4]], %[[IME_VSETLAMBDA_SET]] ]
// RV64-NEXT:    ret i64 [[TMP5]]
//
size_t test_vsetlambda_save_restore(void) {
  size_t saved = __riscv_vsetlambda(0);
  return __riscv_vsetlambda(saved);
}
