#C_SOURCES := main.c
SWIFT_SOURCES := a.swift
#HIDE_SWIFTMODULE = YES
SWIFTFLAGS_EXTRAS = -Xfrontend -disable-round-trip-debug-types -enable-experimental-feature VariadicGenerics -Xfrontend -disable-availability-checking

include Makefile.rules
