; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -mtriple aarch64-- -passes=consthoist -S | FileCheck %s

; The PHI node has some inbound edges with constants that originate from
; basic blocks that aren't reachable from entry. Those could be tricky
; to update when trying to find insertion points etc for a common base
; constant.

; The test case was added as a regression test to show that that we no longer
; hit assertion failures about number of users updated/rebased. The workaround
; is to ignore phi edges from basic blocks that aren't reachable from entry
; when looking for candidate constants.

define i64 @func(i1 %b0, i1 %b1) {
; CHECK-LABEL: define i64 @func(
; CHECK-SAME: i1 [[B0:%.*]], i1 [[B1:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[B0]], label %[[BLOCK1:.*]], label %[[BLOCK2:.*]]
; CHECK:       [[BLOCK1]]:
; CHECK-NEXT:    [[CONST1:%.*]] = bitcast i64 4886718345 to i64
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[BLOCK2]]:
; CHECK-NEXT:    br i1 [[B1]], label %[[BLOCK3:.*]], label %[[MERGE]]
; CHECK:       [[BLOCK3]]:
; CHECK-NEXT:    [[CONST:%.*]] = bitcast i64 4886718345 to i64
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[UNREACHABLE1:.*]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[UNREACHABLE2:.*]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[V:%.*]] = phi i64 [ 4886718345, %[[UNREACHABLE1]] ], [ 4886718345, %[[UNREACHABLE2]] ], [ [[CONST1]], %[[BLOCK1]] ], [ [[CONST]], %[[BLOCK3]] ], [ 0, %[[BLOCK2]] ]
; CHECK-NEXT:    ret i64 [[V]]
;
entry:
  br i1 %b0, label %block1, label %block2

block1:
  br label %merge

block2:
  br i1 %b1, label %block3, label %merge

block3:
  br label %merge

unreachable1:
  br label %merge

unreachable2:
  br label %merge

merge:
  %v = phi i64 [ 4886718345, %unreachable1 ], [ 4886718345, %unreachable2 ], [ 4886718345, %block1 ], [ 4886718345, %block3 ], [ 0, %block2 ]
  ret i64 %v
}


