llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/GlobalISel/cvt_f32_ubyte.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/GlobalISel/fshl.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/GlobalISel/fshr.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/GlobalISel/llvm.abs.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/GlobalISel/saddsat.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/GlobalISel/ssubsat.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/GlobalISel/uaddsat.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/cvt_f32_ubyte.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/fract-match.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/idiv-licm.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/idot4u.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/llvm.fmuladd.f16.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/llvm.frexp.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/machine-sink-temporal-divergence-swdev407790.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/permute_i8.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/reassoc-mul-add-1-to-mad.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/sdwa-peephole-instr.mir
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/sdwa-peephole.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/sdwa-preserve.mir
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/sminmax.v2i16.ll
llvm\utils\update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/v_mac_f16.ll
