// RUN: cir-opt %s -cir-canonicalize -o - | FileCheck %s

!s32i = !cir.int<s, 32>

module {
  cir.func @fold_complex_create_test() -> !cir.complex<!s32i>  {
    %0 = cir.alloca "__retval" align(4) !cir.complex<!s32i> -> !cir.ptr<!cir.complex<!s32i>>
    %1 = cir.alloca "c" align(4) init !cir.complex<!s32i> -> !cir.ptr<!cir.complex<!s32i>>
    %2 = cir.const #cir.int<1> : !s32i
    %3 = cir.const #cir.int<2> : !s32i
    %4 = cir.complex.create %2, %3 : !s32i -> !cir.complex<!s32i>
    cir.store align(4) %4, %1 : !cir.complex<!s32i>, !cir.ptr<!cir.complex<!s32i>>
    %5 = cir.load align(4) %1 : !cir.ptr<!cir.complex<!s32i>>, !cir.complex<!s32i>
    cir.store align(4) %5, %0 : !cir.complex<!s32i>, !cir.ptr<!cir.complex<!s32i>>
    %6 = cir.load %0 : !cir.ptr<!cir.complex<!s32i>>, !cir.complex<!s32i>
    cir.return %6 : !cir.complex<!s32i>
  }

// CHECK: cir.func{{.*}} @fold_complex_create_test() -> !cir.complex<!s32i> {
// CHECK:   %[[RET:.*]] = cir.alloca "__retval" {{.*}} !cir.complex<!s32i> -> !cir.ptr<!cir.complex<!s32i>>
// CHECK:   %[[INIT:.*]] = cir.alloca "c" {{.*}} init !cir.complex<!s32i> -> !cir.ptr<!cir.complex<!s32i>>
// CHECK:   %[[COMPLEX:.*]] = cir.const #cir.const_complex<#cir.int<1> : !s32i, #cir.int<2> : !s32i> : !cir.complex<!s32i>
// CHECK:   cir.store{{.*}} %[[COMPLEX]], %[[INIT]] : !cir.complex<!s32i>, !cir.ptr<!cir.complex<!s32i>>
// CHECK:   %[[TMP:.*]] = cir.load{{.*}} %[[INIT]] : !cir.ptr<!cir.complex<!s32i>>, !cir.complex<!s32i>
// CHECK:   cir.store{{.*}} %[[TMP:.*]], %[[RET]] : !cir.complex<!s32i>, !cir.ptr<!cir.complex<!s32i>>
// CHECK:   %[[TMP_2:.*]] = cir.load %[[RET]] : !cir.ptr<!cir.complex<!s32i>>, !cir.complex<!s32i>
// CHECK:   cir.return %[[TMP_2]] : !cir.complex<!s32i>
// CHECK: }

}
