; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=loop-unroll -S -unroll-threshold=20 < %s | FileCheck %s

define void @test() {
; CHECK-LABEL: define void @test() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    call void asm sideeffect "nop", ""()
; CHECK-NEXT:    store i32 0, ptr null, align 4
; CHECK-NEXT:    call void asm sideeffect "nop", ""()
; CHECK-NEXT:    store i32 0, ptr null, align 4
; CHECK-NEXT:    call void asm sideeffect "nop", ""()
; CHECK-NEXT:    store i32 0, ptr null, align 4
; CHECK-NEXT:    call void asm sideeffect "nop", ""()
; CHECK-NEXT:    store i32 0, ptr null, align 4
; CHECK-NEXT:    call void asm sideeffect "nop", ""()
; CHECK-NEXT:    store i32 0, ptr null, align 4
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  call void asm sideeffect "nop", ""()
  store i32 0, ptr null, align 4
  %iv.next = add i32 %iv, 1
  %cmp = icmp ult i32 %iv, 4
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}
