; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-unroll -S < %s | FileCheck %s

define void @full_and_enable(ptr %p, i32 %n) {
; CHECK-LABEL: define void @full_and_enable(
; CHECK-SAME: ptr [[P:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[MASK:%.*]] = and i32 [[N]], 1
; CHECK-NEXT:    [[BOUND:%.*]] = add nuw i32 [[MASK]], 1
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    store i32 0, ptr [[P]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 1, [[BOUND]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP_1:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP_1]]:
; CHECK-NEXT:    [[PTR_1:%.*]] = getelementptr inbounds i32, ptr [[P]], i32 1
; CHECK-NEXT:    store i32 0, ptr [[PTR_1]], align 4
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %mask = and i32 %n, 1
  %bound = add nuw i32 %mask, 1
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %ptr = getelementptr inbounds i32, ptr %p, i32 %iv
  store i32 0, ptr %ptr, align 4
  %iv.next = add nuw i32 %iv, 1
  %cmp = icmp ult i32 %iv.next, %bound
  br i1 %cmp, label %loop, label %exit, !llvm.loop !0

exit:
  ret void
}

define void @full_only(ptr %p, i32 %n) {
; CHECK-LABEL: define void @full_only(
; CHECK-SAME: ptr [[P:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[MASK:%.*]] = and i32 [[N]], 1
; CHECK-NEXT:    [[BOUND:%.*]] = add nuw i32 [[MASK]], 1
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[PTR:%.*]] = getelementptr inbounds i32, ptr [[P]], i32 [[IV]]
; CHECK-NEXT:    store i32 0, ptr [[PTR]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add nuw i32 [[IV]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[IV_NEXT]], [[BOUND]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %mask = and i32 %n, 1
  %bound = add nuw i32 %mask, 1
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %ptr = getelementptr inbounds i32, ptr %p, i32 %iv
  store i32 0, ptr %ptr, align 4
  %iv.next = add nuw i32 %iv, 1
  %cmp = icmp ult i32 %iv.next, %bound
  br i1 %cmp, label %loop, label %exit, !llvm.loop !1

exit:
  ret void
}

!0 = distinct !{!0, !2, !3}
!1 = distinct !{!1, !2}
!2 = !{!"llvm.loop.unroll.full"}
!3 = !{!"llvm.loop.unroll.enable"}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.unroll.full"}
;.
