; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals
; RUN: opt < %s -S -passes=loop-unroll -unroll-force-peel-count=2 2>&1 | FileCheck %s

declare void @f(i32)

; Test branch weights and estimated trip count metadata for simple loop after
; peeling.
define void @test(i32 %n) {
; CHECK-LABEL: @test(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[DO_BODY_PEEL_BEGIN:%.*]]
; CHECK:       do.body.peel.begin:
; CHECK-NEXT:    br label [[DO_BODY_PEEL:%.*]]
; CHECK:       do.body.peel:
; CHECK-NEXT:    [[INC_PEEL:%.*]] = add i32 0, 1
; CHECK-NEXT:    call void @f(i32 0)
; CHECK-NEXT:    [[C_PEEL:%.*]] = icmp sge i32 [[INC_PEEL]], [[N:%.*]]
; CHECK-NEXT:    br i1 [[C_PEEL]], label [[DO_END:%.*]], label [[DO_BODY_PEEL_NEXT:%.*]], !prof [[PROF0:![0-9]+]]
; CHECK:       do.body.peel.next:
; CHECK-NEXT:    br label [[DO_BODY_PEEL2:%.*]]
; CHECK:       do.body.peel2:
; CHECK-NEXT:    [[INC_PEEL3:%.*]] = add i32 [[INC_PEEL]], 1
; CHECK-NEXT:    call void @f(i32 [[INC_PEEL]])
; CHECK-NEXT:    [[C_PEEL4:%.*]] = icmp sge i32 [[INC_PEEL3]], [[N]]
; CHECK-NEXT:    br i1 [[C_PEEL4]], label [[DO_END]], label [[DO_BODY_PEEL_NEXT1:%.*]], !prof [[PROF0]]
; CHECK:       do.body.peel.next1:
; CHECK-NEXT:    br label [[DO_BODY_PEEL_NEXT5:%.*]]
; CHECK:       do.body.peel.next5:
; CHECK-NEXT:    br label [[ENTRY_PEEL_NEWPH:%.*]]
; CHECK:       entry.peel.newph:
; CHECK-NEXT:    br label [[DO_BODY:%.*]]
; CHECK:       do.body:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ [[INC_PEEL3]], [[ENTRY_PEEL_NEWPH]] ], [ [[INC:%.*]], [[DO_BODY]] ]
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I]], 1
; CHECK-NEXT:    call void @f(i32 [[I]])
; CHECK-NEXT:    [[C:%.*]] = icmp sge i32 [[INC]], [[N]]
; CHECK-NEXT:    br i1 [[C]], label [[DO_END_LOOPEXIT:%.*]], label [[DO_BODY]], !prof [[PROF0]], !llvm.loop [[LOOP1:![0-9]+]]
; CHECK:       do.end.loopexit:
; CHECK-NEXT:    br label [[DO_END]]
; CHECK:       do.end:
; CHECK-NEXT:    ret void
;

entry:
  br label %do.body

do.body:
  %i = phi i32 [ 0, %entry ], [ %inc, %do.body ]
  %inc = add i32 %i, 1
  call void @f(i32 %i)
  %c = icmp sge i32 %inc, %n
  br i1 %c, label %do.end, label %do.body, !prof !0

do.end:
  ret void
}

!0 = !{!"branch_weights", i32 1, i32 9}

;.
; CHECK: [[PROF0]] = !{!"branch_weights", i32 1, i32 9}
; CHECK: [[LOOP1]] = distinct !{[[LOOP1]], [[META2:![0-9]+]], [[META3:![0-9]+]], [[META4:![0-9]+]]}
; CHECK: [[META2]] = !{!"llvm.loop.peeled.count", i32 2}
; CHECK: [[META3]] = !{!"llvm.loop.estimated_trip_count", i32 8}
; CHECK: [[META4]] = !{!"llvm.loop.unroll.disable"}
;.
