; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes='loop-unroll<upperbound>' < %s | FileCheck %s --check-prefixes=DEFAULT
; RUN: opt -S -passes='loop-unroll<upperbound>' -unroll-max-upperbound-with-early-exits=5 < %s | FileCheck %s --check-prefixes=LIMIT

; -unroll-max-upperbound-with-early-exits only limits loops that can exit early.
; Loops that run their max count or zero times still use -unroll-max-upperbound.

; This loop can exit on any iteration and runs at most 6 times. The bound of 5
; is below that, so it is not unrolled.
define i32 @early_exit(i32 %serial_type) {
; DEFAULT-LABEL: @early_exit(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    [[V0:%.*]] = zext i32 [[SERIAL_TYPE:%.*]] to i64
; DEFAULT-NEXT:    br label [[LOOP:%.*]]
; DEFAULT:       loop:
; DEFAULT-NEXT:    [[V_SHR:%.*]] = lshr i64 [[V0]], 7
; DEFAULT-NEXT:    [[CMP:%.*]] = icmp ne i64 [[V_SHR]], 0
; DEFAULT-NEXT:    br i1 [[CMP]], label [[LOOP_1:%.*]], label [[EXIT:%.*]]
; DEFAULT:       loop.1:
; DEFAULT-NEXT:    [[V_SHR_1:%.*]] = lshr i64 [[V_SHR]], 7
; DEFAULT-NEXT:    [[CMP_1:%.*]] = icmp ne i64 [[V_SHR_1]], 0
; DEFAULT-NEXT:    br i1 [[CMP_1]], label [[LOOP_2:%.*]], label [[EXIT]]
; DEFAULT:       loop.2:
; DEFAULT-NEXT:    [[V_SHR_2:%.*]] = lshr i64 [[V_SHR_1]], 7
; DEFAULT-NEXT:    [[CMP_2:%.*]] = icmp ne i64 [[V_SHR_2]], 0
; DEFAULT-NEXT:    br i1 [[CMP_2]], label [[LOOP_3:%.*]], label [[EXIT]]
; DEFAULT:       loop.3:
; DEFAULT-NEXT:    [[V_SHR_3:%.*]] = lshr i64 [[V_SHR_2]], 7
; DEFAULT-NEXT:    [[CMP_3:%.*]] = icmp ne i64 [[V_SHR_3]], 0
; DEFAULT-NEXT:    br i1 [[CMP_3]], label [[LOOP_4:%.*]], label [[EXIT]]
; DEFAULT:       loop.4:
; DEFAULT-NEXT:    [[V_SHR_4:%.*]] = lshr i64 [[V_SHR_3]], 7
; DEFAULT-NEXT:    [[CMP_4:%.*]] = icmp ne i64 [[V_SHR_4]], 0
; DEFAULT-NEXT:    br i1 [[CMP_4]], label [[LOOP_5:%.*]], label [[EXIT]]
; DEFAULT:       loop.5:
; DEFAULT-NEXT:    br label [[EXIT]]
; DEFAULT:       exit:
; DEFAULT-NEXT:    [[I_LCSSA:%.*]] = phi i32 [ 1, [[LOOP]] ], [ 2, [[LOOP_1]] ], [ 3, [[LOOP_2]] ], [ 4, [[LOOP_3]] ], [ 5, [[LOOP_4]] ], [ 6, [[LOOP_5]] ]
; DEFAULT-NEXT:    ret i32 [[I_LCSSA]]
;
; LIMIT-LABEL: @early_exit(
; LIMIT-NEXT:  entry:
; LIMIT-NEXT:    [[V0:%.*]] = zext i32 [[SERIAL_TYPE:%.*]] to i64
; LIMIT-NEXT:    br label [[LOOP:%.*]]
; LIMIT:       loop:
; LIMIT-NEXT:    [[I:%.*]] = phi i32 [ 1, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[LOOP]] ]
; LIMIT-NEXT:    [[V:%.*]] = phi i64 [ [[V0]], [[ENTRY]] ], [ [[V_SHR:%.*]], [[LOOP]] ]
; LIMIT-NEXT:    [[V_SHR]] = lshr i64 [[V]], 7
; LIMIT-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; LIMIT-NEXT:    [[CMP:%.*]] = icmp ne i64 [[V_SHR]], 0
; LIMIT-NEXT:    br i1 [[CMP]], label [[LOOP]], label [[EXIT:%.*]]
; LIMIT:       exit:
; LIMIT-NEXT:    [[I_LCSSA:%.*]] = phi i32 [ [[I]], [[LOOP]] ]
; LIMIT-NEXT:    ret i32 [[I_LCSSA]]
;
entry:
  %v0 = zext i32 %serial_type to i64
  br label %loop

loop:
  %i = phi i32 [ 1, %entry ], [ %i.next, %loop ]
  %v = phi i64 [ %v0, %entry ], [ %v.shr, %loop ]
  %v.shr = lshr i64 %v, 7
  %i.next = add i32 %i, 1
  %cmp = icmp ne i64 %v.shr, 0
  br i1 %cmp, label %loop, label %exit

exit:
  %i.lcssa = phi i32 [ %i, %loop ]
  ret i32 %i.lcssa
}

; This loop runs at most 6 times, but always its max count or zero times, so the
; option does not affect it. It is fully unrolled in both runs.
define i32 @max_or_zero(i32 %n, ptr %p) {
; DEFAULT-LABEL: @max_or_zero(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    [[END:%.*]] = add i32 [[N:%.*]], 6
; DEFAULT-NEXT:    br label [[LOOP:%.*]]
; DEFAULT:       loop:
; DEFAULT-NEXT:    store i32 [[N]], ptr [[P:%.*]], align 4
; DEFAULT-NEXT:    [[I_NEXT:%.*]] = add i32 [[N]], 1
; DEFAULT-NEXT:    [[C:%.*]] = icmp ult i32 [[I_NEXT]], [[END]]
; DEFAULT-NEXT:    br i1 [[C]], label [[LOOP_1:%.*]], label [[EXIT:%.*]]
; DEFAULT:       loop.1:
; DEFAULT-NEXT:    store i32 [[I_NEXT]], ptr [[P]], align 4
; DEFAULT-NEXT:    [[I_NEXT_1:%.*]] = add i32 [[N]], 2
; DEFAULT-NEXT:    store i32 [[I_NEXT_1]], ptr [[P]], align 4
; DEFAULT-NEXT:    [[I_NEXT_2:%.*]] = add i32 [[N]], 3
; DEFAULT-NEXT:    store i32 [[I_NEXT_2]], ptr [[P]], align 4
; DEFAULT-NEXT:    [[I_NEXT_3:%.*]] = add i32 [[N]], 4
; DEFAULT-NEXT:    store i32 [[I_NEXT_3]], ptr [[P]], align 4
; DEFAULT-NEXT:    [[I_NEXT_4:%.*]] = add i32 [[N]], 5
; DEFAULT-NEXT:    store i32 [[I_NEXT_4]], ptr [[P]], align 4
; DEFAULT-NEXT:    br label [[EXIT]]
; DEFAULT:       exit:
; DEFAULT-NEXT:    [[I_LCSSA:%.*]] = phi i32 [ [[N]], [[LOOP]] ], [ [[I_NEXT_4]], [[LOOP_1]] ]
; DEFAULT-NEXT:    ret i32 [[I_LCSSA]]
;
; LIMIT-LABEL: @max_or_zero(
; LIMIT-NEXT:  entry:
; LIMIT-NEXT:    [[END:%.*]] = add i32 [[N:%.*]], 6
; LIMIT-NEXT:    br label [[LOOP:%.*]]
; LIMIT:       loop:
; LIMIT-NEXT:    store i32 [[N]], ptr [[P:%.*]], align 4
; LIMIT-NEXT:    [[I_NEXT:%.*]] = add i32 [[N]], 1
; LIMIT-NEXT:    [[C:%.*]] = icmp ult i32 [[I_NEXT]], [[END]]
; LIMIT-NEXT:    br i1 [[C]], label [[LOOP_1:%.*]], label [[EXIT:%.*]]
; LIMIT:       loop.1:
; LIMIT-NEXT:    store i32 [[I_NEXT]], ptr [[P]], align 4
; LIMIT-NEXT:    [[I_NEXT_1:%.*]] = add i32 [[N]], 2
; LIMIT-NEXT:    store i32 [[I_NEXT_1]], ptr [[P]], align 4
; LIMIT-NEXT:    [[I_NEXT_2:%.*]] = add i32 [[N]], 3
; LIMIT-NEXT:    store i32 [[I_NEXT_2]], ptr [[P]], align 4
; LIMIT-NEXT:    [[I_NEXT_3:%.*]] = add i32 [[N]], 4
; LIMIT-NEXT:    store i32 [[I_NEXT_3]], ptr [[P]], align 4
; LIMIT-NEXT:    [[I_NEXT_4:%.*]] = add i32 [[N]], 5
; LIMIT-NEXT:    store i32 [[I_NEXT_4]], ptr [[P]], align 4
; LIMIT-NEXT:    br label [[EXIT]]
; LIMIT:       exit:
; LIMIT-NEXT:    [[I_LCSSA:%.*]] = phi i32 [ [[N]], [[LOOP]] ], [ [[I_NEXT_4]], [[LOOP_1]] ]
; LIMIT-NEXT:    ret i32 [[I_LCSSA]]
;
entry:
  %end = add i32 %n, 6
  br label %loop

loop:
  %i = phi i32 [ %n, %entry ], [ %i.next, %loop ]
  store i32 %i, ptr %p
  %i.next = add i32 %i, 1
  %c = icmp ult i32 %i.next, %end
  br i1 %c, label %loop, label %exit

exit:
  ret i32 %i
}
