import("//llvm/include/llvm/Config/config.gni")
import("//third-party/unittest/unittest.gni")

unittest("CASTests") {
  deps = [
    "//llvm/lib/CAS",
    "//llvm/lib/Support",
    "//llvm/lib/Testing/Support",
  ]
  sources = [
    "ActionCacheTest.cpp",
    "BuiltinObjectHasherTest.cpp",
    "CASTestConfig.cpp",
    "NamedValuesSchemaTest.cpp",
    "ObjectStoreTest.cpp",
    "OnDiskCommonUtils.cpp",
  ]

  if (llvm_enable_ondisk_cas) {
    sources += [
      "BuiltinUnifiedCASDatabasesTest.cpp",
      "OnDiskCASLoggerTest.cpp",
      "OnDiskDataAllocatorTest.cpp",
      "OnDiskGraphDBTest.cpp",
      "OnDiskKeyValueDBTest.cpp",
      "OnDiskTrieRawHashMapTest.cpp",
      "PluginCASTest.cpp",
      "ProgramTest.cpp",
      "UnifiedOnDiskCacheTest.cpp",
    ]
    data_deps = [ "CASPluginTest" ]

    if (current_os == "mac") {
      shlib_ext = ".dylib"
    } else if (current_os == "win") {
      shlib_ext = ".dll"
    } else {
      shlib_ext = ".so"
    }
    # FIXME: Make this not an absolute path.
    plugin_path = rebase_path("$root_build_dir/lib") + "/CASPluginTest"
    defines = [ "CAS_PLUGIN_PATH=\"$plugin_path$shlib_ext\"" ]

    # Support plugins.
    # FIXME: Disable dead stripping once other binaries are dead-stripped.
    if (host_os != "mac" && host_os != "win") {
      # Corresponds to export_executable_symbols() in cmake.
      ldflags = [ "-rdynamic" ]
    }
    configs -= [ "//llvm/utils/gn/build:no_exported_symbols" ]
  }
}
