// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:   opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefixes=CHECK-RV64,CHECK-RV64-OGCG %s
// RUN: %if cir-enabled %{%clang_cc1 -triple riscv64 -target-feature +v -disable-O0-optnone -emit-llvm -fclangir %s -o - | \
// RUN:   opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s %}
// RUN: %if cir-enabled %{%clang_cc1 -triple riscv64 -target-feature +v -disable-O0-optnone -emit-cir -fclangir %s -o - | \
// RUN:   FileCheck --check-prefix=CIR %s %}

#include <riscv_vector.h>

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i8mf8_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !s8i>, !cir.vector<[1] x !s8i>, !cir.vector<[1] x !s8i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vadc_vvm_i8mf8_tu
// CHECK-RV64-SAME: (<vscale x 1 x i8> [[MASKEDOFF:%.*]], <vscale x 1 x i8> [[OP1:%.*]], <vscale x 1 x i8> [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vadc.nxv1i8.nxv1i8.i64(<vscale x 1 x i8> [[MASKEDOFF]], <vscale x 1 x i8> [[OP1]], <vscale x 1 x i8> [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vadc_vvm_i8mf8_tu(vint8mf8_t maskedoff, vint8mf8_t op1, vint8mf8_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i8mf8_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !s8i>, !cir.vector<[1] x !s8i>, !s8i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vadc_vxm_i8mf8_tu
// CHECK-RV64-SAME: (<vscale x 1 x i8> [[MASKEDOFF:%.*]], <vscale x 1 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vadc.nxv1i8.i8.i64(<vscale x 1 x i8> [[MASKEDOFF]], <vscale x 1 x i8> [[OP1]], i8 [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vadc_vxm_i8mf8_tu(vint8mf8_t maskedoff, vint8mf8_t op1, int8_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i8mf4_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !s8i>, !cir.vector<[2] x !s8i>, !cir.vector<[2] x !s8i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vadc_vvm_i8mf4_tu
// CHECK-RV64-SAME: (<vscale x 2 x i8> [[MASKEDOFF:%.*]], <vscale x 2 x i8> [[OP1:%.*]], <vscale x 2 x i8> [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vadc.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> [[MASKEDOFF]], <vscale x 2 x i8> [[OP1]], <vscale x 2 x i8> [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vadc_vvm_i8mf4_tu(vint8mf4_t maskedoff, vint8mf4_t op1, vint8mf4_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i8mf4_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !s8i>, !cir.vector<[2] x !s8i>, !s8i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vadc_vxm_i8mf4_tu
// CHECK-RV64-SAME: (<vscale x 2 x i8> [[MASKEDOFF:%.*]], <vscale x 2 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vadc.nxv2i8.i8.i64(<vscale x 2 x i8> [[MASKEDOFF]], <vscale x 2 x i8> [[OP1]], i8 [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vadc_vxm_i8mf4_tu(vint8mf4_t maskedoff, vint8mf4_t op1, int8_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i8mf2_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !s8i>, !cir.vector<[4] x !s8i>, !cir.vector<[4] x !s8i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vadc_vvm_i8mf2_tu
// CHECK-RV64-SAME: (<vscale x 4 x i8> [[MASKEDOFF:%.*]], <vscale x 4 x i8> [[OP1:%.*]], <vscale x 4 x i8> [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vadc.nxv4i8.nxv4i8.i64(<vscale x 4 x i8> [[MASKEDOFF]], <vscale x 4 x i8> [[OP1]], <vscale x 4 x i8> [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vadc_vvm_i8mf2_tu(vint8mf2_t maskedoff, vint8mf2_t op1, vint8mf2_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i8mf2_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !s8i>, !cir.vector<[4] x !s8i>, !s8i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vadc_vxm_i8mf2_tu
// CHECK-RV64-SAME: (<vscale x 4 x i8> [[MASKEDOFF:%.*]], <vscale x 4 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vadc.nxv4i8.i8.i64(<vscale x 4 x i8> [[MASKEDOFF]], <vscale x 4 x i8> [[OP1]], i8 [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vadc_vxm_i8mf2_tu(vint8mf2_t maskedoff, vint8mf2_t op1, int8_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[8] x !s8i>, !cir.vector<[8] x !s8i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vadc_vvm_i8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 8 x i8> [[OP1:%.*]], <vscale x 8 x i8> [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vadc.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 8 x i8> [[OP1]], <vscale x 8 x i8> [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vadc_vvm_i8m1_tu(vint8m1_t maskedoff, vint8m1_t op1, vint8m1_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[8] x !s8i>, !s8i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vadc_vxm_i8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 8 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vadc.nxv8i8.i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 8 x i8> [[OP1]], i8 [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vadc_vxm_i8m1_tu(vint8m1_t maskedoff, vint8m1_t op1, int8_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i8m2_tu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[16] x !s8i>, !cir.vector<[16] x !s8i>, !cir.vector<[16] x !s8i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vadc_vvm_i8m2_tu
// CHECK-RV64-SAME: (<vscale x 16 x i8> [[MASKEDOFF:%.*]], <vscale x 16 x i8> [[OP1:%.*]], <vscale x 16 x i8> [[OP2:%.*]], <vscale x 16 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vadc.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> [[MASKEDOFF]], <vscale x 16 x i8> [[OP1]], <vscale x 16 x i8> [[OP2]], <vscale x 16 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vadc_vvm_i8m2_tu(vint8m2_t maskedoff, vint8m2_t op1, vint8m2_t op2, vbool4_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i8m2_tu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[16] x !s8i>, !cir.vector<[16] x !s8i>, !s8i, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vadc_vxm_i8m2_tu
// CHECK-RV64-SAME: (<vscale x 16 x i8> [[MASKEDOFF:%.*]], <vscale x 16 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 16 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vadc.nxv16i8.i8.i64(<vscale x 16 x i8> [[MASKEDOFF]], <vscale x 16 x i8> [[OP1]], i8 [[OP2]], <vscale x 16 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vadc_vxm_i8m2_tu(vint8m2_t maskedoff, vint8m2_t op1, int8_t op2, vbool4_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i8m4_tu(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[32] x !s8i>, !cir.vector<[32] x !s8i>, !cir.vector<[32] x !s8i>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[32] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vadc_vvm_i8m4_tu
// CHECK-RV64-SAME: (<vscale x 32 x i8> [[MASKEDOFF:%.*]], <vscale x 32 x i8> [[OP1:%.*]], <vscale x 32 x i8> [[OP2:%.*]], <vscale x 32 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vadc.nxv32i8.nxv32i8.i64(<vscale x 32 x i8> [[MASKEDOFF]], <vscale x 32 x i8> [[OP1]], <vscale x 32 x i8> [[OP2]], <vscale x 32 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vadc_vvm_i8m4_tu(vint8m4_t maskedoff, vint8m4_t op1, vint8m4_t op2, vbool2_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i8m4_tu(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[32] x !s8i>, !cir.vector<[32] x !s8i>, !s8i, !cir.vector<[32] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[32] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vadc_vxm_i8m4_tu
// CHECK-RV64-SAME: (<vscale x 32 x i8> [[MASKEDOFF:%.*]], <vscale x 32 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 32 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vadc.nxv32i8.i8.i64(<vscale x 32 x i8> [[MASKEDOFF]], <vscale x 32 x i8> [[OP1]], i8 [[OP2]], <vscale x 32 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vadc_vxm_i8m4_tu(vint8m4_t maskedoff, vint8m4_t op1, int8_t op2, vbool2_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i8m8_tu(
// CIR-SAME: -> !cir.vector<[64]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[64] x !s8i>, !cir.vector<[64] x !s8i>, !cir.vector<[64] x !s8i>, !cir.vector<[64] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[64] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vadc_vvm_i8m8_tu
// CHECK-RV64-SAME: (<vscale x 64 x i8> [[MASKEDOFF:%.*]], <vscale x 64 x i8> [[OP1:%.*]], <vscale x 64 x i8> [[OP2:%.*]], <vscale x 64 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vadc.nxv64i8.nxv64i8.i64(<vscale x 64 x i8> [[MASKEDOFF]], <vscale x 64 x i8> [[OP1]], <vscale x 64 x i8> [[OP2]], <vscale x 64 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vint8m8_t test_vadc_vvm_i8m8_tu(vint8m8_t maskedoff, vint8m8_t op1, vint8m8_t op2, vbool1_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i8m8_tu(
// CIR-SAME: -> !cir.vector<[64]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[64] x !s8i>, !cir.vector<[64] x !s8i>, !s8i, !cir.vector<[64] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[64] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vadc_vxm_i8m8_tu
// CHECK-RV64-SAME: (<vscale x 64 x i8> [[MASKEDOFF:%.*]], <vscale x 64 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 64 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vadc.nxv64i8.i8.i64(<vscale x 64 x i8> [[MASKEDOFF]], <vscale x 64 x i8> [[OP1]], i8 [[OP2]], <vscale x 64 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vint8m8_t test_vadc_vxm_i8m8_tu(vint8m8_t maskedoff, vint8m8_t op1, int8_t op2, vbool1_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i16mf4_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !s16i>, !cir.vector<[1] x !s16i>, !cir.vector<[1] x !s16i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vadc_vvm_i16mf4_tu
// CHECK-RV64-SAME: (<vscale x 1 x i16> [[MASKEDOFF:%.*]], <vscale x 1 x i16> [[OP1:%.*]], <vscale x 1 x i16> [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vadc.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> [[MASKEDOFF]], <vscale x 1 x i16> [[OP1]], <vscale x 1 x i16> [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vadc_vvm_i16mf4_tu(vint16mf4_t maskedoff, vint16mf4_t op1, vint16mf4_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i16mf4_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !s16i>, !cir.vector<[1] x !s16i>, !s16i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vadc_vxm_i16mf4_tu
// CHECK-RV64-SAME: (<vscale x 1 x i16> [[MASKEDOFF:%.*]], <vscale x 1 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vadc.nxv1i16.i16.i64(<vscale x 1 x i16> [[MASKEDOFF]], <vscale x 1 x i16> [[OP1]], i16 [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vadc_vxm_i16mf4_tu(vint16mf4_t maskedoff, vint16mf4_t op1, int16_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i16mf2_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !s16i>, !cir.vector<[2] x !s16i>, !cir.vector<[2] x !s16i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vadc_vvm_i16mf2_tu
// CHECK-RV64-SAME: (<vscale x 2 x i16> [[MASKEDOFF:%.*]], <vscale x 2 x i16> [[OP1:%.*]], <vscale x 2 x i16> [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vadc.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> [[MASKEDOFF]], <vscale x 2 x i16> [[OP1]], <vscale x 2 x i16> [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vadc_vvm_i16mf2_tu(vint16mf2_t maskedoff, vint16mf2_t op1, vint16mf2_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i16mf2_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !s16i>, !cir.vector<[2] x !s16i>, !s16i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vadc_vxm_i16mf2_tu
// CHECK-RV64-SAME: (<vscale x 2 x i16> [[MASKEDOFF:%.*]], <vscale x 2 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vadc.nxv2i16.i16.i64(<vscale x 2 x i16> [[MASKEDOFF]], <vscale x 2 x i16> [[OP1]], i16 [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vadc_vxm_i16mf2_tu(vint16mf2_t maskedoff, vint16mf2_t op1, int16_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[4] x !s16i>, !cir.vector<[4] x !s16i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vadc_vvm_i16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 4 x i16> [[OP1:%.*]], <vscale x 4 x i16> [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vadc.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 4 x i16> [[OP1]], <vscale x 4 x i16> [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vadc_vvm_i16m1_tu(vint16m1_t maskedoff, vint16m1_t op1, vint16m1_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[4] x !s16i>, !s16i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vadc_vxm_i16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 4 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vadc.nxv4i16.i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 4 x i16> [[OP1]], i16 [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vadc_vxm_i16m1_tu(vint16m1_t maskedoff, vint16m1_t op1, int16_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i16m2_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !s16i>, !cir.vector<[8] x !s16i>, !cir.vector<[8] x !s16i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vadc_vvm_i16m2_tu
// CHECK-RV64-SAME: (<vscale x 8 x i16> [[MASKEDOFF:%.*]], <vscale x 8 x i16> [[OP1:%.*]], <vscale x 8 x i16> [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vadc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> [[MASKEDOFF]], <vscale x 8 x i16> [[OP1]], <vscale x 8 x i16> [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vadc_vvm_i16m2_tu(vint16m2_t maskedoff, vint16m2_t op1, vint16m2_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i16m2_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !s16i>, !cir.vector<[8] x !s16i>, !s16i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vadc_vxm_i16m2_tu
// CHECK-RV64-SAME: (<vscale x 8 x i16> [[MASKEDOFF:%.*]], <vscale x 8 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vadc.nxv8i16.i16.i64(<vscale x 8 x i16> [[MASKEDOFF]], <vscale x 8 x i16> [[OP1]], i16 [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vadc_vxm_i16m2_tu(vint16m2_t maskedoff, vint16m2_t op1, int16_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i16m4_tu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[16] x !s16i>, !cir.vector<[16] x !s16i>, !cir.vector<[16] x !s16i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vadc_vvm_i16m4_tu
// CHECK-RV64-SAME: (<vscale x 16 x i16> [[MASKEDOFF:%.*]], <vscale x 16 x i16> [[OP1:%.*]], <vscale x 16 x i16> [[OP2:%.*]], <vscale x 16 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vadc.nxv16i16.nxv16i16.i64(<vscale x 16 x i16> [[MASKEDOFF]], <vscale x 16 x i16> [[OP1]], <vscale x 16 x i16> [[OP2]], <vscale x 16 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vadc_vvm_i16m4_tu(vint16m4_t maskedoff, vint16m4_t op1, vint16m4_t op2, vbool4_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i16m4_tu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[16] x !s16i>, !cir.vector<[16] x !s16i>, !s16i, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vadc_vxm_i16m4_tu
// CHECK-RV64-SAME: (<vscale x 16 x i16> [[MASKEDOFF:%.*]], <vscale x 16 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 16 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vadc.nxv16i16.i16.i64(<vscale x 16 x i16> [[MASKEDOFF]], <vscale x 16 x i16> [[OP1]], i16 [[OP2]], <vscale x 16 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vadc_vxm_i16m4_tu(vint16m4_t maskedoff, vint16m4_t op1, int16_t op2, vbool4_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i16m8_tu(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[32] x !s16i>, !cir.vector<[32] x !s16i>, !cir.vector<[32] x !s16i>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[32] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vadc_vvm_i16m8_tu
// CHECK-RV64-SAME: (<vscale x 32 x i16> [[MASKEDOFF:%.*]], <vscale x 32 x i16> [[OP1:%.*]], <vscale x 32 x i16> [[OP2:%.*]], <vscale x 32 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vadc.nxv32i16.nxv32i16.i64(<vscale x 32 x i16> [[MASKEDOFF]], <vscale x 32 x i16> [[OP1]], <vscale x 32 x i16> [[OP2]], <vscale x 32 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vadc_vvm_i16m8_tu(vint16m8_t maskedoff, vint16m8_t op1, vint16m8_t op2, vbool2_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i16m8_tu(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[32] x !s16i>, !cir.vector<[32] x !s16i>, !s16i, !cir.vector<[32] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[32] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vadc_vxm_i16m8_tu
// CHECK-RV64-SAME: (<vscale x 32 x i16> [[MASKEDOFF:%.*]], <vscale x 32 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 32 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vadc.nxv32i16.i16.i64(<vscale x 32 x i16> [[MASKEDOFF]], <vscale x 32 x i16> [[OP1]], i16 [[OP2]], <vscale x 32 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vadc_vxm_i16m8_tu(vint16m8_t maskedoff, vint16m8_t op1, int16_t op2, vbool2_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i32mf2_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !s32i>, !cir.vector<[1] x !s32i>, !cir.vector<[1] x !s32i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vadc_vvm_i32mf2_tu
// CHECK-RV64-SAME: (<vscale x 1 x i32> [[MASKEDOFF:%.*]], <vscale x 1 x i32> [[OP1:%.*]], <vscale x 1 x i32> [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vadc.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> [[MASKEDOFF]], <vscale x 1 x i32> [[OP1]], <vscale x 1 x i32> [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vadc_vvm_i32mf2_tu(vint32mf2_t maskedoff, vint32mf2_t op1, vint32mf2_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i32mf2_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !s32i>, !cir.vector<[1] x !s32i>, !s32i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vadc_vxm_i32mf2_tu
// CHECK-RV64-SAME: (<vscale x 1 x i32> [[MASKEDOFF:%.*]], <vscale x 1 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vadc.nxv1i32.i32.i64(<vscale x 1 x i32> [[MASKEDOFF]], <vscale x 1 x i32> [[OP1]], i32 [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vadc_vxm_i32mf2_tu(vint32mf2_t maskedoff, vint32mf2_t op1, int32_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i32m1_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[2] x !s32i>, !cir.vector<[2] x !s32i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vadc_vvm_i32m1_tu
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 2 x i32> [[OP1:%.*]], <vscale x 2 x i32> [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vadc.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 2 x i32> [[OP1]], <vscale x 2 x i32> [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vadc_vvm_i32m1_tu(vint32m1_t maskedoff, vint32m1_t op1, vint32m1_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i32m1_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[2] x !s32i>, !s32i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vadc_vxm_i32m1_tu
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 2 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vadc.nxv2i32.i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 2 x i32> [[OP1]], i32 [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vadc_vxm_i32m1_tu(vint32m1_t maskedoff, vint32m1_t op1, int32_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i32m2_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !s32i>, !cir.vector<[4] x !s32i>, !cir.vector<[4] x !s32i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vadc_vvm_i32m2_tu
// CHECK-RV64-SAME: (<vscale x 4 x i32> [[MASKEDOFF:%.*]], <vscale x 4 x i32> [[OP1:%.*]], <vscale x 4 x i32> [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vadc.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> [[MASKEDOFF]], <vscale x 4 x i32> [[OP1]], <vscale x 4 x i32> [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vadc_vvm_i32m2_tu(vint32m2_t maskedoff, vint32m2_t op1, vint32m2_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i32m2_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !s32i>, !cir.vector<[4] x !s32i>, !s32i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vadc_vxm_i32m2_tu
// CHECK-RV64-SAME: (<vscale x 4 x i32> [[MASKEDOFF:%.*]], <vscale x 4 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vadc.nxv4i32.i32.i64(<vscale x 4 x i32> [[MASKEDOFF]], <vscale x 4 x i32> [[OP1]], i32 [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vadc_vxm_i32m2_tu(vint32m2_t maskedoff, vint32m2_t op1, int32_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i32m4_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !s32i>, !cir.vector<[8] x !s32i>, !cir.vector<[8] x !s32i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vadc_vvm_i32m4_tu
// CHECK-RV64-SAME: (<vscale x 8 x i32> [[MASKEDOFF:%.*]], <vscale x 8 x i32> [[OP1:%.*]], <vscale x 8 x i32> [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vadc.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> [[MASKEDOFF]], <vscale x 8 x i32> [[OP1]], <vscale x 8 x i32> [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vadc_vvm_i32m4_tu(vint32m4_t maskedoff, vint32m4_t op1, vint32m4_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i32m4_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !s32i>, !cir.vector<[8] x !s32i>, !s32i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vadc_vxm_i32m4_tu
// CHECK-RV64-SAME: (<vscale x 8 x i32> [[MASKEDOFF:%.*]], <vscale x 8 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vadc.nxv8i32.i32.i64(<vscale x 8 x i32> [[MASKEDOFF]], <vscale x 8 x i32> [[OP1]], i32 [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vadc_vxm_i32m4_tu(vint32m4_t maskedoff, vint32m4_t op1, int32_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i32m8_tu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[16] x !s32i>, !cir.vector<[16] x !s32i>, !cir.vector<[16] x !s32i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vadc_vvm_i32m8_tu
// CHECK-RV64-SAME: (<vscale x 16 x i32> [[MASKEDOFF:%.*]], <vscale x 16 x i32> [[OP1:%.*]], <vscale x 16 x i32> [[OP2:%.*]], <vscale x 16 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vadc.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> [[MASKEDOFF]], <vscale x 16 x i32> [[OP1]], <vscale x 16 x i32> [[OP2]], <vscale x 16 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vadc_vvm_i32m8_tu(vint32m8_t maskedoff, vint32m8_t op1, vint32m8_t op2, vbool4_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i32m8_tu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[16] x !s32i>, !cir.vector<[16] x !s32i>, !s32i, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vadc_vxm_i32m8_tu
// CHECK-RV64-SAME: (<vscale x 16 x i32> [[MASKEDOFF:%.*]], <vscale x 16 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 16 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vadc.nxv16i32.i32.i64(<vscale x 16 x i32> [[MASKEDOFF]], <vscale x 16 x i32> [[OP1]], i32 [[OP2]], <vscale x 16 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vadc_vxm_i32m8_tu(vint32m8_t maskedoff, vint32m8_t op1, int32_t op2, vbool4_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i64m1_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !s64i>, !cir.vector<[1] x !s64i>, !cir.vector<[1] x !s64i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vadc_vvm_i64m1_tu
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 1 x i64> [[OP1:%.*]], <vscale x 1 x i64> [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vadc.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 1 x i64> [[OP1]], <vscale x 1 x i64> [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vadc_vvm_i64m1_tu(vint64m1_t maskedoff, vint64m1_t op1, vint64m1_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i64m1_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !s64i>, !cir.vector<[1] x !s64i>, !s64i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vadc_vxm_i64m1_tu
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 1 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vadc.nxv1i64.i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 1 x i64> [[OP1]], i64 [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vadc_vxm_i64m1_tu(vint64m1_t maskedoff, vint64m1_t op1, int64_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i64m2_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !s64i>, !cir.vector<[2] x !s64i>, !cir.vector<[2] x !s64i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vadc_vvm_i64m2_tu
// CHECK-RV64-SAME: (<vscale x 2 x i64> [[MASKEDOFF:%.*]], <vscale x 2 x i64> [[OP1:%.*]], <vscale x 2 x i64> [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vadc.nxv2i64.nxv2i64.i64(<vscale x 2 x i64> [[MASKEDOFF]], <vscale x 2 x i64> [[OP1]], <vscale x 2 x i64> [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vadc_vvm_i64m2_tu(vint64m2_t maskedoff, vint64m2_t op1, vint64m2_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i64m2_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !s64i>, !cir.vector<[2] x !s64i>, !s64i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vadc_vxm_i64m2_tu
// CHECK-RV64-SAME: (<vscale x 2 x i64> [[MASKEDOFF:%.*]], <vscale x 2 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vadc.nxv2i64.i64.i64(<vscale x 2 x i64> [[MASKEDOFF]], <vscale x 2 x i64> [[OP1]], i64 [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vadc_vxm_i64m2_tu(vint64m2_t maskedoff, vint64m2_t op1, int64_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i64m4_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !s64i>, !cir.vector<[4] x !s64i>, !cir.vector<[4] x !s64i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vadc_vvm_i64m4_tu
// CHECK-RV64-SAME: (<vscale x 4 x i64> [[MASKEDOFF:%.*]], <vscale x 4 x i64> [[OP1:%.*]], <vscale x 4 x i64> [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vadc.nxv4i64.nxv4i64.i64(<vscale x 4 x i64> [[MASKEDOFF]], <vscale x 4 x i64> [[OP1]], <vscale x 4 x i64> [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vadc_vvm_i64m4_tu(vint64m4_t maskedoff, vint64m4_t op1, vint64m4_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i64m4_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !s64i>, !cir.vector<[4] x !s64i>, !s64i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vadc_vxm_i64m4_tu
// CHECK-RV64-SAME: (<vscale x 4 x i64> [[MASKEDOFF:%.*]], <vscale x 4 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vadc.nxv4i64.i64.i64(<vscale x 4 x i64> [[MASKEDOFF]], <vscale x 4 x i64> [[OP1]], i64 [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vadc_vxm_i64m4_tu(vint64m4_t maskedoff, vint64m4_t op1, int64_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_i64m8_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !s64i>, !cir.vector<[8] x !s64i>, !cir.vector<[8] x !s64i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vadc_vvm_i64m8_tu
// CHECK-RV64-SAME: (<vscale x 8 x i64> [[MASKEDOFF:%.*]], <vscale x 8 x i64> [[OP1:%.*]], <vscale x 8 x i64> [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vadc.nxv8i64.nxv8i64.i64(<vscale x 8 x i64> [[MASKEDOFF]], <vscale x 8 x i64> [[OP1]], <vscale x 8 x i64> [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vadc_vvm_i64m8_tu(vint64m8_t maskedoff, vint64m8_t op1, vint64m8_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_i64m8_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !s64i>, !cir.vector<[8] x !s64i>, !s64i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vadc_vxm_i64m8_tu
// CHECK-RV64-SAME: (<vscale x 8 x i64> [[MASKEDOFF:%.*]], <vscale x 8 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vadc.nxv8i64.i64.i64(<vscale x 8 x i64> [[MASKEDOFF]], <vscale x 8 x i64> [[OP1]], i64 [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vadc_vxm_i64m8_tu(vint64m8_t maskedoff, vint64m8_t op1, int64_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u8mf8_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !u8i>, !cir.vector<[1] x !u8i>, !cir.vector<[1] x !u8i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vadc_vvm_u8mf8_tu
// CHECK-RV64-SAME: (<vscale x 1 x i8> [[MASKEDOFF:%.*]], <vscale x 1 x i8> [[OP1:%.*]], <vscale x 1 x i8> [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vadc.nxv1i8.nxv1i8.i64(<vscale x 1 x i8> [[MASKEDOFF]], <vscale x 1 x i8> [[OP1]], <vscale x 1 x i8> [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vadc_vvm_u8mf8_tu(vuint8mf8_t maskedoff, vuint8mf8_t op1, vuint8mf8_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u8mf8_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !u8i>, !cir.vector<[1] x !u8i>, !u8i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vadc_vxm_u8mf8_tu
// CHECK-RV64-SAME: (<vscale x 1 x i8> [[MASKEDOFF:%.*]], <vscale x 1 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vadc.nxv1i8.i8.i64(<vscale x 1 x i8> [[MASKEDOFF]], <vscale x 1 x i8> [[OP1]], i8 [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vadc_vxm_u8mf8_tu(vuint8mf8_t maskedoff, vuint8mf8_t op1, uint8_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u8mf4_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !u8i>, !cir.vector<[2] x !u8i>, !cir.vector<[2] x !u8i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vadc_vvm_u8mf4_tu
// CHECK-RV64-SAME: (<vscale x 2 x i8> [[MASKEDOFF:%.*]], <vscale x 2 x i8> [[OP1:%.*]], <vscale x 2 x i8> [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vadc.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> [[MASKEDOFF]], <vscale x 2 x i8> [[OP1]], <vscale x 2 x i8> [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vadc_vvm_u8mf4_tu(vuint8mf4_t maskedoff, vuint8mf4_t op1, vuint8mf4_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u8mf4_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !u8i>, !cir.vector<[2] x !u8i>, !u8i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vadc_vxm_u8mf4_tu
// CHECK-RV64-SAME: (<vscale x 2 x i8> [[MASKEDOFF:%.*]], <vscale x 2 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vadc.nxv2i8.i8.i64(<vscale x 2 x i8> [[MASKEDOFF]], <vscale x 2 x i8> [[OP1]], i8 [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vadc_vxm_u8mf4_tu(vuint8mf4_t maskedoff, vuint8mf4_t op1, uint8_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u8mf2_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !u8i>, !cir.vector<[4] x !u8i>, !cir.vector<[4] x !u8i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vadc_vvm_u8mf2_tu
// CHECK-RV64-SAME: (<vscale x 4 x i8> [[MASKEDOFF:%.*]], <vscale x 4 x i8> [[OP1:%.*]], <vscale x 4 x i8> [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vadc.nxv4i8.nxv4i8.i64(<vscale x 4 x i8> [[MASKEDOFF]], <vscale x 4 x i8> [[OP1]], <vscale x 4 x i8> [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vadc_vvm_u8mf2_tu(vuint8mf2_t maskedoff, vuint8mf2_t op1, vuint8mf2_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u8mf2_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !u8i>, !cir.vector<[4] x !u8i>, !u8i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vadc_vxm_u8mf2_tu
// CHECK-RV64-SAME: (<vscale x 4 x i8> [[MASKEDOFF:%.*]], <vscale x 4 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vadc.nxv4i8.i8.i64(<vscale x 4 x i8> [[MASKEDOFF]], <vscale x 4 x i8> [[OP1]], i8 [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vadc_vxm_u8mf2_tu(vuint8mf2_t maskedoff, vuint8mf2_t op1, uint8_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[8] x !u8i>, !cir.vector<[8] x !u8i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vadc_vvm_u8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 8 x i8> [[OP1:%.*]], <vscale x 8 x i8> [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vadc.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 8 x i8> [[OP1]], <vscale x 8 x i8> [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vadc_vvm_u8m1_tu(vuint8m1_t maskedoff, vuint8m1_t op1, vuint8m1_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[8] x !u8i>, !u8i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vadc_vxm_u8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 8 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vadc.nxv8i8.i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 8 x i8> [[OP1]], i8 [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vadc_vxm_u8m1_tu(vuint8m1_t maskedoff, vuint8m1_t op1, uint8_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u8m2_tu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[16] x !u8i>, !cir.vector<[16] x !u8i>, !cir.vector<[16] x !u8i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vadc_vvm_u8m2_tu
// CHECK-RV64-SAME: (<vscale x 16 x i8> [[MASKEDOFF:%.*]], <vscale x 16 x i8> [[OP1:%.*]], <vscale x 16 x i8> [[OP2:%.*]], <vscale x 16 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vadc.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> [[MASKEDOFF]], <vscale x 16 x i8> [[OP1]], <vscale x 16 x i8> [[OP2]], <vscale x 16 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vadc_vvm_u8m2_tu(vuint8m2_t maskedoff, vuint8m2_t op1, vuint8m2_t op2, vbool4_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u8m2_tu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[16] x !u8i>, !cir.vector<[16] x !u8i>, !u8i, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vadc_vxm_u8m2_tu
// CHECK-RV64-SAME: (<vscale x 16 x i8> [[MASKEDOFF:%.*]], <vscale x 16 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], <vscale x 16 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vadc.nxv16i8.i8.i64(<vscale x 16 x i8> [[MASKEDOFF]], <vscale x 16 x i8> [[OP1]], i8 [[OP2]], <vscale x 16 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vadc_vxm_u8m2_tu(vuint8m2_t maskedoff, vuint8m2_t op1, uint8_t op2, vbool4_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u8m4_tu(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[32] x !u8i>, !cir.vector<[32] x !u8i>, !cir.vector<[32] x !u8i>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[32] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vadc_vvm_u8m4_tu
// CHECK-RV64-SAME: (<vscale x 32 x i8> [[MASKEDOFF:%.*]], <vscale x 32 x i8> [[OP1:%.*]], <vscale x 32 x i8> [[OP2:%.*]], <vscale x 32 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vadc.nxv32i8.nxv32i8.i64(<vscale x 32 x i8> [[MASKEDOFF]], <vscale x 32 x i8> [[OP1]], <vscale x 32 x i8> [[OP2]], <vscale x 32 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vadc_vvm_u8m4_tu(vuint8m4_t maskedoff, vuint8m4_t op1, vuint8m4_t op2, vbool2_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u8m4_tu(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[32] x !u8i>, !cir.vector<[32] x !u8i>, !u8i, !cir.vector<[32] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[32] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vadc_vxm_u8m4_tu
// CHECK-RV64-SAME: (<vscale x 32 x i8> [[MASKEDOFF:%.*]], <vscale x 32 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], <vscale x 32 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vadc.nxv32i8.i8.i64(<vscale x 32 x i8> [[MASKEDOFF]], <vscale x 32 x i8> [[OP1]], i8 [[OP2]], <vscale x 32 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vadc_vxm_u8m4_tu(vuint8m4_t maskedoff, vuint8m4_t op1, uint8_t op2, vbool2_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u8m8_tu(
// CIR-SAME: -> !cir.vector<[64]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[64] x !u8i>, !cir.vector<[64] x !u8i>, !cir.vector<[64] x !u8i>, !cir.vector<[64] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[64] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vadc_vvm_u8m8_tu
// CHECK-RV64-SAME: (<vscale x 64 x i8> [[MASKEDOFF:%.*]], <vscale x 64 x i8> [[OP1:%.*]], <vscale x 64 x i8> [[OP2:%.*]], <vscale x 64 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vadc.nxv64i8.nxv64i8.i64(<vscale x 64 x i8> [[MASKEDOFF]], <vscale x 64 x i8> [[OP1]], <vscale x 64 x i8> [[OP2]], <vscale x 64 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vuint8m8_t test_vadc_vvm_u8m8_tu(vuint8m8_t maskedoff, vuint8m8_t op1, vuint8m8_t op2, vbool1_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u8m8_tu(
// CIR-SAME: -> !cir.vector<[64]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[64] x !u8i>, !cir.vector<[64] x !u8i>, !u8i, !cir.vector<[64] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[64] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vadc_vxm_u8m8_tu
// CHECK-RV64-SAME: (<vscale x 64 x i8> [[MASKEDOFF:%.*]], <vscale x 64 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], <vscale x 64 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vadc.nxv64i8.i8.i64(<vscale x 64 x i8> [[MASKEDOFF]], <vscale x 64 x i8> [[OP1]], i8 [[OP2]], <vscale x 64 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vuint8m8_t test_vadc_vxm_u8m8_tu(vuint8m8_t maskedoff, vuint8m8_t op1, uint8_t op2, vbool1_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u16mf4_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !u16i>, !cir.vector<[1] x !u16i>, !cir.vector<[1] x !u16i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vadc_vvm_u16mf4_tu
// CHECK-RV64-SAME: (<vscale x 1 x i16> [[MASKEDOFF:%.*]], <vscale x 1 x i16> [[OP1:%.*]], <vscale x 1 x i16> [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vadc.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> [[MASKEDOFF]], <vscale x 1 x i16> [[OP1]], <vscale x 1 x i16> [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vadc_vvm_u16mf4_tu(vuint16mf4_t maskedoff, vuint16mf4_t op1, vuint16mf4_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u16mf4_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !u16i>, !cir.vector<[1] x !u16i>, !u16i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vadc_vxm_u16mf4_tu
// CHECK-RV64-SAME: (<vscale x 1 x i16> [[MASKEDOFF:%.*]], <vscale x 1 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vadc.nxv1i16.i16.i64(<vscale x 1 x i16> [[MASKEDOFF]], <vscale x 1 x i16> [[OP1]], i16 [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vadc_vxm_u16mf4_tu(vuint16mf4_t maskedoff, vuint16mf4_t op1, uint16_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u16mf2_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !u16i>, !cir.vector<[2] x !u16i>, !cir.vector<[2] x !u16i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vadc_vvm_u16mf2_tu
// CHECK-RV64-SAME: (<vscale x 2 x i16> [[MASKEDOFF:%.*]], <vscale x 2 x i16> [[OP1:%.*]], <vscale x 2 x i16> [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vadc.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> [[MASKEDOFF]], <vscale x 2 x i16> [[OP1]], <vscale x 2 x i16> [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vadc_vvm_u16mf2_tu(vuint16mf2_t maskedoff, vuint16mf2_t op1, vuint16mf2_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u16mf2_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !u16i>, !cir.vector<[2] x !u16i>, !u16i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vadc_vxm_u16mf2_tu
// CHECK-RV64-SAME: (<vscale x 2 x i16> [[MASKEDOFF:%.*]], <vscale x 2 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vadc.nxv2i16.i16.i64(<vscale x 2 x i16> [[MASKEDOFF]], <vscale x 2 x i16> [[OP1]], i16 [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vadc_vxm_u16mf2_tu(vuint16mf2_t maskedoff, vuint16mf2_t op1, uint16_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[4] x !u16i>, !cir.vector<[4] x !u16i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vadc_vvm_u16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 4 x i16> [[OP1:%.*]], <vscale x 4 x i16> [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vadc.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 4 x i16> [[OP1]], <vscale x 4 x i16> [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vadc_vvm_u16m1_tu(vuint16m1_t maskedoff, vuint16m1_t op1, vuint16m1_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[4] x !u16i>, !u16i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vadc_vxm_u16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 4 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vadc.nxv4i16.i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 4 x i16> [[OP1]], i16 [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vadc_vxm_u16m1_tu(vuint16m1_t maskedoff, vuint16m1_t op1, uint16_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u16m2_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !u16i>, !cir.vector<[8] x !u16i>, !cir.vector<[8] x !u16i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vadc_vvm_u16m2_tu
// CHECK-RV64-SAME: (<vscale x 8 x i16> [[MASKEDOFF:%.*]], <vscale x 8 x i16> [[OP1:%.*]], <vscale x 8 x i16> [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vadc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> [[MASKEDOFF]], <vscale x 8 x i16> [[OP1]], <vscale x 8 x i16> [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vadc_vvm_u16m2_tu(vuint16m2_t maskedoff, vuint16m2_t op1, vuint16m2_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u16m2_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !u16i>, !cir.vector<[8] x !u16i>, !u16i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vadc_vxm_u16m2_tu
// CHECK-RV64-SAME: (<vscale x 8 x i16> [[MASKEDOFF:%.*]], <vscale x 8 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vadc.nxv8i16.i16.i64(<vscale x 8 x i16> [[MASKEDOFF]], <vscale x 8 x i16> [[OP1]], i16 [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vadc_vxm_u16m2_tu(vuint16m2_t maskedoff, vuint16m2_t op1, uint16_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u16m4_tu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[16] x !u16i>, !cir.vector<[16] x !u16i>, !cir.vector<[16] x !u16i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vadc_vvm_u16m4_tu
// CHECK-RV64-SAME: (<vscale x 16 x i16> [[MASKEDOFF:%.*]], <vscale x 16 x i16> [[OP1:%.*]], <vscale x 16 x i16> [[OP2:%.*]], <vscale x 16 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vadc.nxv16i16.nxv16i16.i64(<vscale x 16 x i16> [[MASKEDOFF]], <vscale x 16 x i16> [[OP1]], <vscale x 16 x i16> [[OP2]], <vscale x 16 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vadc_vvm_u16m4_tu(vuint16m4_t maskedoff, vuint16m4_t op1, vuint16m4_t op2, vbool4_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u16m4_tu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[16] x !u16i>, !cir.vector<[16] x !u16i>, !u16i, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vadc_vxm_u16m4_tu
// CHECK-RV64-SAME: (<vscale x 16 x i16> [[MASKEDOFF:%.*]], <vscale x 16 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], <vscale x 16 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vadc.nxv16i16.i16.i64(<vscale x 16 x i16> [[MASKEDOFF]], <vscale x 16 x i16> [[OP1]], i16 [[OP2]], <vscale x 16 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vadc_vxm_u16m4_tu(vuint16m4_t maskedoff, vuint16m4_t op1, uint16_t op2, vbool4_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u16m8_tu(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[32] x !u16i>, !cir.vector<[32] x !u16i>, !cir.vector<[32] x !u16i>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[32] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vadc_vvm_u16m8_tu
// CHECK-RV64-SAME: (<vscale x 32 x i16> [[MASKEDOFF:%.*]], <vscale x 32 x i16> [[OP1:%.*]], <vscale x 32 x i16> [[OP2:%.*]], <vscale x 32 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vadc.nxv32i16.nxv32i16.i64(<vscale x 32 x i16> [[MASKEDOFF]], <vscale x 32 x i16> [[OP1]], <vscale x 32 x i16> [[OP2]], <vscale x 32 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vadc_vvm_u16m8_tu(vuint16m8_t maskedoff, vuint16m8_t op1, vuint16m8_t op2, vbool2_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u16m8_tu(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[32] x !u16i>, !cir.vector<[32] x !u16i>, !u16i, !cir.vector<[32] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[32] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vadc_vxm_u16m8_tu
// CHECK-RV64-SAME: (<vscale x 32 x i16> [[MASKEDOFF:%.*]], <vscale x 32 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], <vscale x 32 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vadc.nxv32i16.i16.i64(<vscale x 32 x i16> [[MASKEDOFF]], <vscale x 32 x i16> [[OP1]], i16 [[OP2]], <vscale x 32 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vadc_vxm_u16m8_tu(vuint16m8_t maskedoff, vuint16m8_t op1, uint16_t op2, vbool2_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u32mf2_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !u32i>, !cir.vector<[1] x !u32i>, !cir.vector<[1] x !u32i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vadc_vvm_u32mf2_tu
// CHECK-RV64-SAME: (<vscale x 1 x i32> [[MASKEDOFF:%.*]], <vscale x 1 x i32> [[OP1:%.*]], <vscale x 1 x i32> [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vadc.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> [[MASKEDOFF]], <vscale x 1 x i32> [[OP1]], <vscale x 1 x i32> [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vadc_vvm_u32mf2_tu(vuint32mf2_t maskedoff, vuint32mf2_t op1, vuint32mf2_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u32mf2_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !u32i>, !cir.vector<[1] x !u32i>, !u32i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vadc_vxm_u32mf2_tu
// CHECK-RV64-SAME: (<vscale x 1 x i32> [[MASKEDOFF:%.*]], <vscale x 1 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vadc.nxv1i32.i32.i64(<vscale x 1 x i32> [[MASKEDOFF]], <vscale x 1 x i32> [[OP1]], i32 [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vadc_vxm_u32mf2_tu(vuint32mf2_t maskedoff, vuint32mf2_t op1, uint32_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u32m1_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[2] x !u32i>, !cir.vector<[2] x !u32i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vadc_vvm_u32m1_tu
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 2 x i32> [[OP1:%.*]], <vscale x 2 x i32> [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vadc.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 2 x i32> [[OP1]], <vscale x 2 x i32> [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vadc_vvm_u32m1_tu(vuint32m1_t maskedoff, vuint32m1_t op1, vuint32m1_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u32m1_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[2] x !u32i>, !u32i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vadc_vxm_u32m1_tu
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 2 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vadc.nxv2i32.i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 2 x i32> [[OP1]], i32 [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vadc_vxm_u32m1_tu(vuint32m1_t maskedoff, vuint32m1_t op1, uint32_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u32m2_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !u32i>, !cir.vector<[4] x !u32i>, !cir.vector<[4] x !u32i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vadc_vvm_u32m2_tu
// CHECK-RV64-SAME: (<vscale x 4 x i32> [[MASKEDOFF:%.*]], <vscale x 4 x i32> [[OP1:%.*]], <vscale x 4 x i32> [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vadc.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> [[MASKEDOFF]], <vscale x 4 x i32> [[OP1]], <vscale x 4 x i32> [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vadc_vvm_u32m2_tu(vuint32m2_t maskedoff, vuint32m2_t op1, vuint32m2_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u32m2_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !u32i>, !cir.vector<[4] x !u32i>, !u32i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vadc_vxm_u32m2_tu
// CHECK-RV64-SAME: (<vscale x 4 x i32> [[MASKEDOFF:%.*]], <vscale x 4 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vadc.nxv4i32.i32.i64(<vscale x 4 x i32> [[MASKEDOFF]], <vscale x 4 x i32> [[OP1]], i32 [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vadc_vxm_u32m2_tu(vuint32m2_t maskedoff, vuint32m2_t op1, uint32_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u32m4_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !u32i>, !cir.vector<[8] x !u32i>, !cir.vector<[8] x !u32i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vadc_vvm_u32m4_tu
// CHECK-RV64-SAME: (<vscale x 8 x i32> [[MASKEDOFF:%.*]], <vscale x 8 x i32> [[OP1:%.*]], <vscale x 8 x i32> [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vadc.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> [[MASKEDOFF]], <vscale x 8 x i32> [[OP1]], <vscale x 8 x i32> [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vadc_vvm_u32m4_tu(vuint32m4_t maskedoff, vuint32m4_t op1, vuint32m4_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u32m4_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !u32i>, !cir.vector<[8] x !u32i>, !u32i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vadc_vxm_u32m4_tu
// CHECK-RV64-SAME: (<vscale x 8 x i32> [[MASKEDOFF:%.*]], <vscale x 8 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vadc.nxv8i32.i32.i64(<vscale x 8 x i32> [[MASKEDOFF]], <vscale x 8 x i32> [[OP1]], i32 [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vadc_vxm_u32m4_tu(vuint32m4_t maskedoff, vuint32m4_t op1, uint32_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u32m8_tu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[16] x !u32i>, !cir.vector<[16] x !u32i>, !cir.vector<[16] x !u32i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vadc_vvm_u32m8_tu
// CHECK-RV64-SAME: (<vscale x 16 x i32> [[MASKEDOFF:%.*]], <vscale x 16 x i32> [[OP1:%.*]], <vscale x 16 x i32> [[OP2:%.*]], <vscale x 16 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vadc.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> [[MASKEDOFF]], <vscale x 16 x i32> [[OP1]], <vscale x 16 x i32> [[OP2]], <vscale x 16 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vadc_vvm_u32m8_tu(vuint32m8_t maskedoff, vuint32m8_t op1, vuint32m8_t op2, vbool4_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u32m8_tu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[16] x !u32i>, !cir.vector<[16] x !u32i>, !u32i, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vadc_vxm_u32m8_tu
// CHECK-RV64-SAME: (<vscale x 16 x i32> [[MASKEDOFF:%.*]], <vscale x 16 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], <vscale x 16 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vadc.nxv16i32.i32.i64(<vscale x 16 x i32> [[MASKEDOFF]], <vscale x 16 x i32> [[OP1]], i32 [[OP2]], <vscale x 16 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vadc_vxm_u32m8_tu(vuint32m8_t maskedoff, vuint32m8_t op1, uint32_t op2, vbool4_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u64m1_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !u64i>, !cir.vector<[1] x !u64i>, !cir.vector<[1] x !u64i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vadc_vvm_u64m1_tu
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 1 x i64> [[OP1:%.*]], <vscale x 1 x i64> [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vadc.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 1 x i64> [[OP1]], <vscale x 1 x i64> [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vadc_vvm_u64m1_tu(vuint64m1_t maskedoff, vuint64m1_t op1, vuint64m1_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u64m1_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[1] x !u64i>, !cir.vector<[1] x !u64i>, !u64i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vadc_vxm_u64m1_tu
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 1 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], <vscale x 1 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vadc.nxv1i64.i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 1 x i64> [[OP1]], i64 [[OP2]], <vscale x 1 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vadc_vxm_u64m1_tu(vuint64m1_t maskedoff, vuint64m1_t op1, uint64_t op2, vbool64_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u64m2_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !u64i>, !cir.vector<[2] x !u64i>, !cir.vector<[2] x !u64i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vadc_vvm_u64m2_tu
// CHECK-RV64-SAME: (<vscale x 2 x i64> [[MASKEDOFF:%.*]], <vscale x 2 x i64> [[OP1:%.*]], <vscale x 2 x i64> [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vadc.nxv2i64.nxv2i64.i64(<vscale x 2 x i64> [[MASKEDOFF]], <vscale x 2 x i64> [[OP1]], <vscale x 2 x i64> [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vadc_vvm_u64m2_tu(vuint64m2_t maskedoff, vuint64m2_t op1, vuint64m2_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u64m2_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[2] x !u64i>, !cir.vector<[2] x !u64i>, !u64i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vadc_vxm_u64m2_tu
// CHECK-RV64-SAME: (<vscale x 2 x i64> [[MASKEDOFF:%.*]], <vscale x 2 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], <vscale x 2 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vadc.nxv2i64.i64.i64(<vscale x 2 x i64> [[MASKEDOFF]], <vscale x 2 x i64> [[OP1]], i64 [[OP2]], <vscale x 2 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vadc_vxm_u64m2_tu(vuint64m2_t maskedoff, vuint64m2_t op1, uint64_t op2, vbool32_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u64m4_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !u64i>, !cir.vector<[4] x !u64i>, !cir.vector<[4] x !u64i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vadc_vvm_u64m4_tu
// CHECK-RV64-SAME: (<vscale x 4 x i64> [[MASKEDOFF:%.*]], <vscale x 4 x i64> [[OP1:%.*]], <vscale x 4 x i64> [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vadc.nxv4i64.nxv4i64.i64(<vscale x 4 x i64> [[MASKEDOFF]], <vscale x 4 x i64> [[OP1]], <vscale x 4 x i64> [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vadc_vvm_u64m4_tu(vuint64m4_t maskedoff, vuint64m4_t op1, vuint64m4_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u64m4_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[4] x !u64i>, !cir.vector<[4] x !u64i>, !u64i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vadc_vxm_u64m4_tu
// CHECK-RV64-SAME: (<vscale x 4 x i64> [[MASKEDOFF:%.*]], <vscale x 4 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], <vscale x 4 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vadc.nxv4i64.i64.i64(<vscale x 4 x i64> [[MASKEDOFF]], <vscale x 4 x i64> [[OP1]], i64 [[OP2]], <vscale x 4 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vadc_vxm_u64m4_tu(vuint64m4_t maskedoff, vuint64m4_t op1, uint64_t op2, vbool16_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vvm_u64m8_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !u64i>, !cir.vector<[8] x !u64i>, !cir.vector<[8] x !u64i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vadc_vvm_u64m8_tu
// CHECK-RV64-SAME: (<vscale x 8 x i64> [[MASKEDOFF:%.*]], <vscale x 8 x i64> [[OP1:%.*]], <vscale x 8 x i64> [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vadc.nxv8i64.nxv8i64.i64(<vscale x 8 x i64> [[MASKEDOFF]], <vscale x 8 x i64> [[OP1]], <vscale x 8 x i64> [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vadc_vvm_u64m8_tu(vuint64m8_t maskedoff, vuint64m8_t op1, vuint64m8_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vadc_vxm_u64m8_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vadc" {{%.*}} : (!cir.vector<[8] x !u64i>, !cir.vector<[8] x !u64i>, !u64i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vadc_vxm_u64m8_tu
// CHECK-RV64-SAME: (<vscale x 8 x i64> [[MASKEDOFF:%.*]], <vscale x 8 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], <vscale x 8 x i1> [[CARRYIN:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vadc.nxv8i64.i64.i64(<vscale x 8 x i64> [[MASKEDOFF]], <vscale x 8 x i64> [[OP1]], i64 [[OP2]], <vscale x 8 x i1> [[CARRYIN]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vadc_vxm_u64m8_tu(vuint64m8_t maskedoff, vuint64m8_t op1, uint64_t op2, vbool8_t carryin, size_t vl) {
  return __riscv_vadc_tu(maskedoff, op1, op2, carryin, vl);
}

//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-RV64: {{.*}}
