// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v -target-feature +zfh -target-feature +zvfh -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:   opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefixes=CHECK-RV64,CHECK-RV64-OGCG %s
// RUN: %if cir-enabled %{%clang_cc1 -triple riscv64 -target-feature +v -target-feature +zfh -target-feature +zvfh -disable-O0-optnone -emit-llvm -fclangir %s -o - | \
// RUN:   opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s %}
// RUN: %if cir-enabled %{%clang_cc1 -triple riscv64 -target-feature +v -target-feature +zfh -target-feature +zvfh -disable-O0-optnone -emit-cir -fclangir %s -o - | \
// RUN:   FileCheck --check-prefix=CIR %s %}

#include <riscv_vector.h>

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vv_f16mf4_b64_mu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[1] x !cir.int<u, 1>>, !cir.vector<[1] x !cir.f16>, !cir.vector<[1] x !cir.f16>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i1> @test_vmfne_vv_f16mf4_b64_mu
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i1> [[MASKEDOFF:%.*]], <vscale x 1 x half> [[OP1:%.*]], <vscale x 1 x half> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i1> @llvm.riscv.vmfne.mask.nxv1f16.nxv1f16.i64(<vscale x 1 x i1> [[MASKEDOFF]], <vscale x 1 x half> [[OP1]], <vscale x 1 x half> [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i1> [[TMP0]]
//
vbool64_t test_vmfne_vv_f16mf4_b64_mu(vbool64_t mask, vbool64_t maskedoff, vfloat16mf4_t op1, vfloat16mf4_t op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vf_f16mf4_b64_mu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[1] x !cir.int<u, 1>>, !cir.vector<[1] x !cir.f16>, !cir.f16, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i1> @test_vmfne_vf_f16mf4_b64_mu
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i1> [[MASKEDOFF:%.*]], <vscale x 1 x half> [[OP1:%.*]], half noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i1> @llvm.riscv.vmfne.mask.nxv1f16.f16.i64(<vscale x 1 x i1> [[MASKEDOFF]], <vscale x 1 x half> [[OP1]], half [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i1> [[TMP0]]
//
vbool64_t test_vmfne_vf_f16mf4_b64_mu(vbool64_t mask, vbool64_t maskedoff, vfloat16mf4_t op1, _Float16 op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vv_f16mf2_b32_mu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[2] x !cir.int<u, 1>>, !cir.vector<[2] x !cir.f16>, !cir.vector<[2] x !cir.f16>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i1> @test_vmfne_vv_f16mf2_b32_mu
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i1> [[MASKEDOFF:%.*]], <vscale x 2 x half> [[OP1:%.*]], <vscale x 2 x half> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i1> @llvm.riscv.vmfne.mask.nxv2f16.nxv2f16.i64(<vscale x 2 x i1> [[MASKEDOFF]], <vscale x 2 x half> [[OP1]], <vscale x 2 x half> [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i1> [[TMP0]]
//
vbool32_t test_vmfne_vv_f16mf2_b32_mu(vbool32_t mask, vbool32_t maskedoff, vfloat16mf2_t op1, vfloat16mf2_t op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vf_f16mf2_b32_mu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[2] x !cir.int<u, 1>>, !cir.vector<[2] x !cir.f16>, !cir.f16, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i1> @test_vmfne_vf_f16mf2_b32_mu
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i1> [[MASKEDOFF:%.*]], <vscale x 2 x half> [[OP1:%.*]], half noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i1> @llvm.riscv.vmfne.mask.nxv2f16.f16.i64(<vscale x 2 x i1> [[MASKEDOFF]], <vscale x 2 x half> [[OP1]], half [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i1> [[TMP0]]
//
vbool32_t test_vmfne_vf_f16mf2_b32_mu(vbool32_t mask, vbool32_t maskedoff, vfloat16mf2_t op1, _Float16 op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vv_f16m1_b16_mu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[4] x !cir.int<u, 1>>, !cir.vector<[4] x !cir.f16>, !cir.vector<[4] x !cir.f16>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i1> @test_vmfne_vv_f16m1_b16_mu
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i1> [[MASKEDOFF:%.*]], <vscale x 4 x half> [[OP1:%.*]], <vscale x 4 x half> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfne.mask.nxv4f16.nxv4f16.i64(<vscale x 4 x i1> [[MASKEDOFF]], <vscale x 4 x half> [[OP1]], <vscale x 4 x half> [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i1> [[TMP0]]
//
vbool16_t test_vmfne_vv_f16m1_b16_mu(vbool16_t mask, vbool16_t maskedoff, vfloat16m1_t op1, vfloat16m1_t op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vf_f16m1_b16_mu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[4] x !cir.int<u, 1>>, !cir.vector<[4] x !cir.f16>, !cir.f16, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i1> @test_vmfne_vf_f16m1_b16_mu
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i1> [[MASKEDOFF:%.*]], <vscale x 4 x half> [[OP1:%.*]], half noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfne.mask.nxv4f16.f16.i64(<vscale x 4 x i1> [[MASKEDOFF]], <vscale x 4 x half> [[OP1]], half [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i1> [[TMP0]]
//
vbool16_t test_vmfne_vf_f16m1_b16_mu(vbool16_t mask, vbool16_t maskedoff, vfloat16m1_t op1, _Float16 op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vv_f16m2_b8_mu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[8] x !cir.int<u, 1>>, !cir.vector<[8] x !cir.f16>, !cir.vector<[8] x !cir.f16>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i1> @test_vmfne_vv_f16m2_b8_mu
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i1> [[MASKEDOFF:%.*]], <vscale x 8 x half> [[OP1:%.*]], <vscale x 8 x half> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i1> @llvm.riscv.vmfne.mask.nxv8f16.nxv8f16.i64(<vscale x 8 x i1> [[MASKEDOFF]], <vscale x 8 x half> [[OP1]], <vscale x 8 x half> [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i1> [[TMP0]]
//
vbool8_t test_vmfne_vv_f16m2_b8_mu(vbool8_t mask, vbool8_t maskedoff, vfloat16m2_t op1, vfloat16m2_t op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vf_f16m2_b8_mu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[8] x !cir.int<u, 1>>, !cir.vector<[8] x !cir.f16>, !cir.f16, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i1> @test_vmfne_vf_f16m2_b8_mu
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i1> [[MASKEDOFF:%.*]], <vscale x 8 x half> [[OP1:%.*]], half noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i1> @llvm.riscv.vmfne.mask.nxv8f16.f16.i64(<vscale x 8 x i1> [[MASKEDOFF]], <vscale x 8 x half> [[OP1]], half [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i1> [[TMP0]]
//
vbool8_t test_vmfne_vf_f16m2_b8_mu(vbool8_t mask, vbool8_t maskedoff, vfloat16m2_t op1, _Float16 op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vv_f16m4_b4_mu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[16] x !cir.int<u, 1>>, !cir.vector<[16] x !cir.f16>, !cir.vector<[16] x !cir.f16>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i1> @test_vmfne_vv_f16m4_b4_mu
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i1> [[MASKEDOFF:%.*]], <vscale x 16 x half> [[OP1:%.*]], <vscale x 16 x half> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i1> @llvm.riscv.vmfne.mask.nxv16f16.nxv16f16.i64(<vscale x 16 x i1> [[MASKEDOFF]], <vscale x 16 x half> [[OP1]], <vscale x 16 x half> [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i1> [[TMP0]]
//
vbool4_t test_vmfne_vv_f16m4_b4_mu(vbool4_t mask, vbool4_t maskedoff, vfloat16m4_t op1, vfloat16m4_t op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vf_f16m4_b4_mu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[16] x !cir.int<u, 1>>, !cir.vector<[16] x !cir.f16>, !cir.f16, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i1> @test_vmfne_vf_f16m4_b4_mu
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i1> [[MASKEDOFF:%.*]], <vscale x 16 x half> [[OP1:%.*]], half noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i1> @llvm.riscv.vmfne.mask.nxv16f16.f16.i64(<vscale x 16 x i1> [[MASKEDOFF]], <vscale x 16 x half> [[OP1]], half [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i1> [[TMP0]]
//
vbool4_t test_vmfne_vf_f16m4_b4_mu(vbool4_t mask, vbool4_t maskedoff, vfloat16m4_t op1, _Float16 op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vv_f16m8_b2_mu(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[32] x !cir.int<u, 1>>, !cir.vector<[32] x !cir.f16>, !cir.vector<[32] x !cir.f16>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[32] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i1> @test_vmfne_vv_f16m8_b2_mu
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], <vscale x 32 x i1> [[MASKEDOFF:%.*]], <vscale x 32 x half> [[OP1:%.*]], <vscale x 32 x half> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i1> @llvm.riscv.vmfne.mask.nxv32f16.nxv32f16.i64(<vscale x 32 x i1> [[MASKEDOFF]], <vscale x 32 x half> [[OP1]], <vscale x 32 x half> [[OP2]], <vscale x 32 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i1> [[TMP0]]
//
vbool2_t test_vmfne_vv_f16m8_b2_mu(vbool2_t mask, vbool2_t maskedoff, vfloat16m8_t op1, vfloat16m8_t op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vf_f16m8_b2_mu(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[32] x !cir.int<u, 1>>, !cir.vector<[32] x !cir.f16>, !cir.f16, !cir.vector<[32] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[32] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i1> @test_vmfne_vf_f16m8_b2_mu
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], <vscale x 32 x i1> [[MASKEDOFF:%.*]], <vscale x 32 x half> [[OP1:%.*]], half noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i1> @llvm.riscv.vmfne.mask.nxv32f16.f16.i64(<vscale x 32 x i1> [[MASKEDOFF]], <vscale x 32 x half> [[OP1]], half [[OP2]], <vscale x 32 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i1> [[TMP0]]
//
vbool2_t test_vmfne_vf_f16m8_b2_mu(vbool2_t mask, vbool2_t maskedoff, vfloat16m8_t op1, _Float16 op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vv_f32mf2_b64_mu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[1] x !cir.int<u, 1>>, !cir.vector<[1] x !cir.float>, !cir.vector<[1] x !cir.float>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i1> @test_vmfne_vv_f32mf2_b64_mu
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i1> [[MASKEDOFF:%.*]], <vscale x 1 x float> [[OP1:%.*]], <vscale x 1 x float> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i1> @llvm.riscv.vmfne.mask.nxv1f32.nxv1f32.i64(<vscale x 1 x i1> [[MASKEDOFF]], <vscale x 1 x float> [[OP1]], <vscale x 1 x float> [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i1> [[TMP0]]
//
vbool64_t test_vmfne_vv_f32mf2_b64_mu(vbool64_t mask, vbool64_t maskedoff, vfloat32mf2_t op1, vfloat32mf2_t op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vf_f32mf2_b64_mu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[1] x !cir.int<u, 1>>, !cir.vector<[1] x !cir.float>, !cir.float, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i1> @test_vmfne_vf_f32mf2_b64_mu
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i1> [[MASKEDOFF:%.*]], <vscale x 1 x float> [[OP1:%.*]], float noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i1> @llvm.riscv.vmfne.mask.nxv1f32.f32.i64(<vscale x 1 x i1> [[MASKEDOFF]], <vscale x 1 x float> [[OP1]], float [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i1> [[TMP0]]
//
vbool64_t test_vmfne_vf_f32mf2_b64_mu(vbool64_t mask, vbool64_t maskedoff, vfloat32mf2_t op1, float op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vv_f32m1_b32_mu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[2] x !cir.int<u, 1>>, !cir.vector<[2] x !cir.float>, !cir.vector<[2] x !cir.float>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i1> @test_vmfne_vv_f32m1_b32_mu
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i1> [[MASKEDOFF:%.*]], <vscale x 2 x float> [[OP1:%.*]], <vscale x 2 x float> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i1> @llvm.riscv.vmfne.mask.nxv2f32.nxv2f32.i64(<vscale x 2 x i1> [[MASKEDOFF]], <vscale x 2 x float> [[OP1]], <vscale x 2 x float> [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i1> [[TMP0]]
//
vbool32_t test_vmfne_vv_f32m1_b32_mu(vbool32_t mask, vbool32_t maskedoff, vfloat32m1_t op1, vfloat32m1_t op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vf_f32m1_b32_mu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[2] x !cir.int<u, 1>>, !cir.vector<[2] x !cir.float>, !cir.float, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i1> @test_vmfne_vf_f32m1_b32_mu
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i1> [[MASKEDOFF:%.*]], <vscale x 2 x float> [[OP1:%.*]], float noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i1> @llvm.riscv.vmfne.mask.nxv2f32.f32.i64(<vscale x 2 x i1> [[MASKEDOFF]], <vscale x 2 x float> [[OP1]], float [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i1> [[TMP0]]
//
vbool32_t test_vmfne_vf_f32m1_b32_mu(vbool32_t mask, vbool32_t maskedoff, vfloat32m1_t op1, float op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vv_f32m2_b16_mu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[4] x !cir.int<u, 1>>, !cir.vector<[4] x !cir.float>, !cir.vector<[4] x !cir.float>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i1> @test_vmfne_vv_f32m2_b16_mu
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i1> [[MASKEDOFF:%.*]], <vscale x 4 x float> [[OP1:%.*]], <vscale x 4 x float> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfne.mask.nxv4f32.nxv4f32.i64(<vscale x 4 x i1> [[MASKEDOFF]], <vscale x 4 x float> [[OP1]], <vscale x 4 x float> [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i1> [[TMP0]]
//
vbool16_t test_vmfne_vv_f32m2_b16_mu(vbool16_t mask, vbool16_t maskedoff, vfloat32m2_t op1, vfloat32m2_t op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vf_f32m2_b16_mu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[4] x !cir.int<u, 1>>, !cir.vector<[4] x !cir.float>, !cir.float, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i1> @test_vmfne_vf_f32m2_b16_mu
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i1> [[MASKEDOFF:%.*]], <vscale x 4 x float> [[OP1:%.*]], float noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfne.mask.nxv4f32.f32.i64(<vscale x 4 x i1> [[MASKEDOFF]], <vscale x 4 x float> [[OP1]], float [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i1> [[TMP0]]
//
vbool16_t test_vmfne_vf_f32m2_b16_mu(vbool16_t mask, vbool16_t maskedoff, vfloat32m2_t op1, float op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vv_f32m4_b8_mu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[8] x !cir.int<u, 1>>, !cir.vector<[8] x !cir.float>, !cir.vector<[8] x !cir.float>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i1> @test_vmfne_vv_f32m4_b8_mu
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i1> [[MASKEDOFF:%.*]], <vscale x 8 x float> [[OP1:%.*]], <vscale x 8 x float> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i1> @llvm.riscv.vmfne.mask.nxv8f32.nxv8f32.i64(<vscale x 8 x i1> [[MASKEDOFF]], <vscale x 8 x float> [[OP1]], <vscale x 8 x float> [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i1> [[TMP0]]
//
vbool8_t test_vmfne_vv_f32m4_b8_mu(vbool8_t mask, vbool8_t maskedoff, vfloat32m4_t op1, vfloat32m4_t op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vf_f32m4_b8_mu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[8] x !cir.int<u, 1>>, !cir.vector<[8] x !cir.float>, !cir.float, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i1> @test_vmfne_vf_f32m4_b8_mu
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i1> [[MASKEDOFF:%.*]], <vscale x 8 x float> [[OP1:%.*]], float noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i1> @llvm.riscv.vmfne.mask.nxv8f32.f32.i64(<vscale x 8 x i1> [[MASKEDOFF]], <vscale x 8 x float> [[OP1]], float [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i1> [[TMP0]]
//
vbool8_t test_vmfne_vf_f32m4_b8_mu(vbool8_t mask, vbool8_t maskedoff, vfloat32m4_t op1, float op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vv_f32m8_b4_mu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[16] x !cir.int<u, 1>>, !cir.vector<[16] x !cir.float>, !cir.vector<[16] x !cir.float>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i1> @test_vmfne_vv_f32m8_b4_mu
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i1> [[MASKEDOFF:%.*]], <vscale x 16 x float> [[OP1:%.*]], <vscale x 16 x float> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i1> @llvm.riscv.vmfne.mask.nxv16f32.nxv16f32.i64(<vscale x 16 x i1> [[MASKEDOFF]], <vscale x 16 x float> [[OP1]], <vscale x 16 x float> [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i1> [[TMP0]]
//
vbool4_t test_vmfne_vv_f32m8_b4_mu(vbool4_t mask, vbool4_t maskedoff, vfloat32m8_t op1, vfloat32m8_t op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vf_f32m8_b4_mu(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[16] x !cir.int<u, 1>>, !cir.vector<[16] x !cir.float>, !cir.float, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[16] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i1> @test_vmfne_vf_f32m8_b4_mu
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i1> [[MASKEDOFF:%.*]], <vscale x 16 x float> [[OP1:%.*]], float noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i1> @llvm.riscv.vmfne.mask.nxv16f32.f32.i64(<vscale x 16 x i1> [[MASKEDOFF]], <vscale x 16 x float> [[OP1]], float [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i1> [[TMP0]]
//
vbool4_t test_vmfne_vf_f32m8_b4_mu(vbool4_t mask, vbool4_t maskedoff, vfloat32m8_t op1, float op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vv_f64m1_b64_mu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[1] x !cir.int<u, 1>>, !cir.vector<[1] x !cir.double>, !cir.vector<[1] x !cir.double>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i1> @test_vmfne_vv_f64m1_b64_mu
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i1> [[MASKEDOFF:%.*]], <vscale x 1 x double> [[OP1:%.*]], <vscale x 1 x double> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i1> @llvm.riscv.vmfne.mask.nxv1f64.nxv1f64.i64(<vscale x 1 x i1> [[MASKEDOFF]], <vscale x 1 x double> [[OP1]], <vscale x 1 x double> [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i1> [[TMP0]]
//
vbool64_t test_vmfne_vv_f64m1_b64_mu(vbool64_t mask, vbool64_t maskedoff, vfloat64m1_t op1, vfloat64m1_t op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vf_f64m1_b64_mu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[1] x !cir.int<u, 1>>, !cir.vector<[1] x !cir.double>, !cir.double, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i1> @test_vmfne_vf_f64m1_b64_mu
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i1> [[MASKEDOFF:%.*]], <vscale x 1 x double> [[OP1:%.*]], double noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i1> @llvm.riscv.vmfne.mask.nxv1f64.f64.i64(<vscale x 1 x i1> [[MASKEDOFF]], <vscale x 1 x double> [[OP1]], double [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i1> [[TMP0]]
//
vbool64_t test_vmfne_vf_f64m1_b64_mu(vbool64_t mask, vbool64_t maskedoff, vfloat64m1_t op1, double op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vv_f64m2_b32_mu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[2] x !cir.int<u, 1>>, !cir.vector<[2] x !cir.double>, !cir.vector<[2] x !cir.double>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i1> @test_vmfne_vv_f64m2_b32_mu
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i1> [[MASKEDOFF:%.*]], <vscale x 2 x double> [[OP1:%.*]], <vscale x 2 x double> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i1> @llvm.riscv.vmfne.mask.nxv2f64.nxv2f64.i64(<vscale x 2 x i1> [[MASKEDOFF]], <vscale x 2 x double> [[OP1]], <vscale x 2 x double> [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i1> [[TMP0]]
//
vbool32_t test_vmfne_vv_f64m2_b32_mu(vbool32_t mask, vbool32_t maskedoff, vfloat64m2_t op1, vfloat64m2_t op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vf_f64m2_b32_mu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[2] x !cir.int<u, 1>>, !cir.vector<[2] x !cir.double>, !cir.double, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i1> @test_vmfne_vf_f64m2_b32_mu
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i1> [[MASKEDOFF:%.*]], <vscale x 2 x double> [[OP1:%.*]], double noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i1> @llvm.riscv.vmfne.mask.nxv2f64.f64.i64(<vscale x 2 x i1> [[MASKEDOFF]], <vscale x 2 x double> [[OP1]], double [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i1> [[TMP0]]
//
vbool32_t test_vmfne_vf_f64m2_b32_mu(vbool32_t mask, vbool32_t maskedoff, vfloat64m2_t op1, double op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vv_f64m4_b16_mu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[4] x !cir.int<u, 1>>, !cir.vector<[4] x !cir.double>, !cir.vector<[4] x !cir.double>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i1> @test_vmfne_vv_f64m4_b16_mu
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i1> [[MASKEDOFF:%.*]], <vscale x 4 x double> [[OP1:%.*]], <vscale x 4 x double> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfne.mask.nxv4f64.nxv4f64.i64(<vscale x 4 x i1> [[MASKEDOFF]], <vscale x 4 x double> [[OP1]], <vscale x 4 x double> [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i1> [[TMP0]]
//
vbool16_t test_vmfne_vv_f64m4_b16_mu(vbool16_t mask, vbool16_t maskedoff, vfloat64m4_t op1, vfloat64m4_t op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vf_f64m4_b16_mu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[4] x !cir.int<u, 1>>, !cir.vector<[4] x !cir.double>, !cir.double, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i1> @test_vmfne_vf_f64m4_b16_mu
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i1> [[MASKEDOFF:%.*]], <vscale x 4 x double> [[OP1:%.*]], double noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfne.mask.nxv4f64.f64.i64(<vscale x 4 x i1> [[MASKEDOFF]], <vscale x 4 x double> [[OP1]], double [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i1> [[TMP0]]
//
vbool16_t test_vmfne_vf_f64m4_b16_mu(vbool16_t mask, vbool16_t maskedoff, vfloat64m4_t op1, double op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vv_f64m8_b8_mu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[8] x !cir.int<u, 1>>, !cir.vector<[8] x !cir.double>, !cir.vector<[8] x !cir.double>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i1> @test_vmfne_vv_f64m8_b8_mu
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i1> [[MASKEDOFF:%.*]], <vscale x 8 x double> [[OP1:%.*]], <vscale x 8 x double> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i1> @llvm.riscv.vmfne.mask.nxv8f64.nxv8f64.i64(<vscale x 8 x i1> [[MASKEDOFF]], <vscale x 8 x double> [[OP1]], <vscale x 8 x double> [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i1> [[TMP0]]
//
vbool8_t test_vmfne_vv_f64m8_b8_mu(vbool8_t mask, vbool8_t maskedoff, vfloat64m8_t op1, vfloat64m8_t op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmfne_vf_f64m8_b8_mu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmfne.mask" {{%.*}} : (!cir.vector<[8] x !cir.int<u, 1>>, !cir.vector<[8] x !cir.double>, !cir.double, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !cir.int<u, 1>>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i1> @test_vmfne_vf_f64m8_b8_mu
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i1> [[MASKEDOFF:%.*]], <vscale x 8 x double> [[OP1:%.*]], double noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i1> @llvm.riscv.vmfne.mask.nxv8f64.f64.i64(<vscale x 8 x i1> [[MASKEDOFF]], <vscale x 8 x double> [[OP1]], double [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i1> [[TMP0]]
//
vbool8_t test_vmfne_vf_f64m8_b8_mu(vbool8_t mask, vbool8_t maskedoff, vfloat64m8_t op1, double op2, size_t vl) {
  return __riscv_vmfne_mu(mask, maskedoff, op1, op2, vl);
}

//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-RV64: {{.*}}
