; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=gvn -S < %s | FileCheck %s

declare void @clobber(ptr)
declare ptr @readonly_call(ptr, i32) memory(read)
declare <4 x i32> @llvm.masked.load.v4i32.p0(ptr, <4 x i1>, <4 x i32>)
declare ptr @llvm.load.relative.i32(ptr, i32)
declare i32 @llvm.read_register.i32(metadata)
declare <4 x i32> @llvm.vp.gather.v4i32.v4p0(<4 x ptr>, <4 x i1>, i32)

define <4 x i32> @masked_load_invariant(ptr %p, <4 x i1> %mask, <4 x i32> %passthru) {
; CHECK-LABEL: define <4 x i32> @masked_load_invariant(
; CHECK-SAME: ptr [[P:%.*]], <4 x i1> [[MASK:%.*]], <4 x i32> [[PASSTHRU:%.*]]) {
; CHECK-NEXT:    [[A1:%.*]] = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr align 4 [[P]], <4 x i1> [[MASK]], <4 x i32> [[PASSTHRU]]), !invariant.load [[META0:![0-9]+]]
; CHECK-NEXT:    call void @clobber(ptr [[P]])
; CHECK-NEXT:    [[A:%.*]] = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr align 4 [[P]], <4 x i1> [[MASK]], <4 x i32> [[PASSTHRU]]), !invariant.load [[META0]]
; CHECK-NEXT:    ret <4 x i32> [[A]]
;
  %a = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr align 4 %p, <4 x i1> %mask, <4 x i32> %passthru), !invariant.load !0
  call void @clobber(ptr %p)
  %b = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr align 4 %p, <4 x i1> %mask, <4 x i32> %passthru), !invariant.load !0
  ret <4 x i32> %b
}

define <4 x i32> @masked_load_without_metadata(ptr %p, <4 x i1> %mask, <4 x i32> %passthru) {
; CHECK-LABEL: define <4 x i32> @masked_load_without_metadata(
; CHECK-SAME: ptr [[P:%.*]], <4 x i1> [[MASK:%.*]], <4 x i32> [[PASSTHRU:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr align 4 [[P]], <4 x i1> [[MASK]], <4 x i32> [[PASSTHRU]])
; CHECK-NEXT:    call void @clobber(ptr [[P]])
; CHECK-NEXT:    [[B:%.*]] = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr align 4 [[P]], <4 x i1> [[MASK]], <4 x i32> [[PASSTHRU]])
; CHECK-NEXT:    ret <4 x i32> [[B]]
;
  %a = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr align 4 %p, <4 x i1> %mask, <4 x i32> %passthru)
  call void @clobber(ptr %p)
  %b = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr align 4 %p, <4 x i1> %mask, <4 x i32> %passthru)
  ret <4 x i32> %b
}

define ptr @load_relative_invariant(ptr %p, i32 %off) {
; CHECK-LABEL: define ptr @load_relative_invariant(
; CHECK-SAME: ptr [[P:%.*]], i32 [[OFF:%.*]]) {
; CHECK-NEXT:    [[A1:%.*]] = call ptr @llvm.load.relative.i32(ptr [[P]], i32 [[OFF]]), !invariant.load [[META0]]
; CHECK-NEXT:    call void @clobber(ptr [[P]])
; CHECK-NEXT:    [[A:%.*]] = call ptr @llvm.load.relative.i32(ptr [[P]], i32 [[OFF]]), !invariant.load [[META0]]
; CHECK-NEXT:    ret ptr [[A]]
;
  %a = call ptr @llvm.load.relative.i32(ptr %p, i32 %off), !invariant.load !0
  call void @clobber(ptr %p)
  %b = call ptr @llvm.load.relative.i32(ptr %p, i32 %off), !invariant.load !0
  ret ptr %b
}

define ptr @load_relative_without_metadata(ptr %p, i32 %off) {
; CHECK-LABEL: define ptr @load_relative_without_metadata(
; CHECK-SAME: ptr [[P:%.*]], i32 [[OFF:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = call ptr @llvm.load.relative.i32(ptr [[P]], i32 [[OFF]])
; CHECK-NEXT:    call void @clobber(ptr [[P]])
; CHECK-NEXT:    [[B:%.*]] = call ptr @llvm.load.relative.i32(ptr [[P]], i32 [[OFF]])
; CHECK-NEXT:    ret ptr [[B]]
;
  %a = call ptr @llvm.load.relative.i32(ptr %p, i32 %off)
  call void @clobber(ptr %p)
  %b = call ptr @llvm.load.relative.i32(ptr %p, i32 %off)
  ret ptr %b
}

define <4 x i32> @vp_gather_invariant(ptr %p, <4 x ptr> %ptrs, <4 x i1> %mask, i32 %vl) {
; CHECK-LABEL: define <4 x i32> @vp_gather_invariant(
; CHECK-SAME: ptr [[P:%.*]], <4 x ptr> [[PTRS:%.*]], <4 x i1> [[MASK:%.*]], i32 [[VL:%.*]]) {
; CHECK-NEXT:    [[A1:%.*]] = call <4 x i32> @llvm.vp.gather.v4i32.v4p0(<4 x ptr> [[PTRS]], <4 x i1> [[MASK]], i32 [[VL]]), !invariant.load [[META0]]
; CHECK-NEXT:    call void @clobber(ptr [[P]])
; CHECK-NEXT:    [[A:%.*]] = call <4 x i32> @llvm.vp.gather.v4i32.v4p0(<4 x ptr> [[PTRS]], <4 x i1> [[MASK]], i32 [[VL]]), !invariant.load [[META0]]
; CHECK-NEXT:    ret <4 x i32> [[A]]
;
  %a = call <4 x i32> @llvm.vp.gather.v4i32.v4p0(<4 x ptr> %ptrs, <4 x i1> %mask, i32 %vl), !invariant.load !0
  call void @clobber(ptr %p)
  %b = call <4 x i32> @llvm.vp.gather.v4i32.v4p0(<4 x ptr> %ptrs, <4 x i1> %mask, i32 %vl), !invariant.load !0
  ret <4 x i32> %b
}

define ptr @ordinary_readonly_call_with_metadata(ptr %p, i32 %off) {
; CHECK-LABEL: define ptr @ordinary_readonly_call_with_metadata(
; CHECK-SAME: ptr [[P:%.*]], i32 [[OFF:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = call ptr @readonly_call(ptr [[P]], i32 [[OFF]]), !invariant.load [[META0]]
; CHECK-NEXT:    call void @clobber(ptr [[P]])
; CHECK-NEXT:    [[B:%.*]] = call ptr @readonly_call(ptr [[P]], i32 [[OFF]]), !invariant.load [[META0]]
; CHECK-NEXT:    ret ptr [[B]]
;
  %a = call ptr @readonly_call(ptr %p, i32 %off), !invariant.load !0
  call void @clobber(ptr %p)
  %b = call ptr @readonly_call(ptr %p, i32 %off), !invariant.load !0
  ret ptr %b
}

define i32 @read_register_with_metadata(ptr %p) {
; CHECK-LABEL: define i32 @read_register_with_metadata(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = call i32 @llvm.read_register.i32(metadata [[META1:![0-9]+]]), !invariant.load [[META0]]
; CHECK-NEXT:    call void @clobber(ptr [[P]])
; CHECK-NEXT:    [[B:%.*]] = call i32 @llvm.read_register.i32(metadata [[META1]]), !invariant.load [[META0]]
; CHECK-NEXT:    ret i32 [[B]]
;
  %a = call i32 @llvm.read_register.i32(metadata !1), !invariant.load !0
  call void @clobber(ptr %p)
  %b = call i32 @llvm.read_register.i32(metadata !1), !invariant.load !0
  ret i32 %b
}

!0 = !{}
!1 = !{!"reg"}
;.
; CHECK: [[META0]] = !{}
; CHECK: [[META1]] = !{!"reg"}
;.
