; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=gvn -S < %s | FileCheck %s

; Check that an unreachable predecessor to a PHI node doesn't cause a crash.
; PR21625. The first load should be removed, since it's ignored.
define i32 @f(ptr %f) {
; CHECK-LABEL: define i32 @f(
; CHECK-SAME: ptr [[F:%.*]]) {
; CHECK-NEXT:  [[BB0:.*]]:
; CHECK-NEXT:    br label %[[BB2:.*]]
; CHECK:       [[BB1:.*]]:
; CHECK-NEXT:    [[ZED:%.*]] = load ptr, ptr [[F]], align 8
; CHECK-NEXT:    br i1 false, label %[[BB1]], label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[FOO:%.*]] = phi ptr [ null, %[[BB0]] ], [ [[ZED]], %[[BB1]] ]
; CHECK-NEXT:    [[STOREMERGE:%.*]] = load i32, ptr [[FOO]], align 4
; CHECK-NEXT:    ret i32 [[STOREMERGE]]
;
bb0:
  %bar = load ptr, ptr %f
  br label %bb2
bb1:
  %zed = load ptr, ptr %f
  br i1 false, label %bb1, label %bb2
bb2:
  %foo = phi ptr [ null, %bb0 ], [ %zed, %bb1 ]
  %storemerge = load i32, ptr %foo
  ret i32 %storemerge
}
