; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=gvn -passes=instnamer -S %s | FileCheck %s

; This test ensures that given spv.resource.counterhandlefrombinding is marked
; convergent, the GVN pass is prevented from sinking these intrinsics out of
; branches which would create phi nodes on the returned counter handle.
;
; The CHECK lines below match the input IR exactly, so this test verifies that
; the pass makes no changes to the IR.
;
; It models the following HLSL:
;
;   RWStructuredBuffer<int> Out[4] : register(u0);
;
;   [numthreads(4,1,1)]
;   void main(uint GI : SV_GroupIndex) {
;     for (int i = 0; i < GI; i++)
;       Out[NonUniformResourceIndex(GI)].IncrementCounter();
;
;     Out[NonUniformResourceIndex(GI)][0] = Out[NonUniformResourceIndex(GI)].IncrementCounter();
;   }

target datalayout = "e-ve-i64:64-n8:16:32:64-G10"
target triple = "spirv1.6-unknown-vulkan1.3-compute"

@Out.str = private unnamed_addr constant [4 x i8] c"Out\00", align 1
@cond = external hidden local_unnamed_addr addrspace(2) global i32, align 4

define void @main() local_unnamed_addr {
; CHECK-LABEL: define void @main() local_unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[I:%.*]] = tail call target("spirv.VulkanBuffer", [0 x i32], 12, 1) @llvm.spv.resource.handlefrombinding.tspirv.VulkanBuffer_a0i32_12_1t(i32 0, i32 0, i32 4, i32 0, ptr nonnull @Out.str)
; CHECK-NEXT:    [[I1:%.*]] = load i32, ptr addrspace(2) @cond, align 4
; CHECK-NEXT:    [[LOADEDV:%.*]] = trunc nuw i32 [[I1]] to i1
; CHECK-NEXT:    br i1 [[LOADEDV]], label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    [[I2:%.*]] = tail call target("spirv.VulkanBuffer", i32, 12, 1) @llvm.spv.resource.counterhandlefrombinding.tspirv.VulkanBuffer_i32_12_1t.tspirv.VulkanBuffer_a0i32_12_1t(target("spirv.VulkanBuffer", [0 x i32], 12, 1) [[I]], i32 0, i32 0)
; CHECK-NEXT:    [[I3:%.*]] = tail call i32 @llvm.spv.resource.updatecounter.tspirv.VulkanBuffer_i32_12_1t(target("spirv.VulkanBuffer", i32, 12, 1) [[I2]], i8 1)
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    [[I4:%.*]] = tail call target("spirv.VulkanBuffer", i32, 12, 1) @llvm.spv.resource.counterhandlefrombinding.tspirv.VulkanBuffer_i32_12_1t.tspirv.VulkanBuffer_a0i32_12_1t(target("spirv.VulkanBuffer", [0 x i32], 12, 1) [[I]], i32 0, i32 0)
; CHECK-NEXT:    [[I5:%.*]] = tail call i32 @llvm.spv.resource.updatecounter.tspirv.VulkanBuffer_i32_12_1t(target("spirv.VulkanBuffer", i32, 12, 1) [[I4]], i8 1)
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[I6:%.*]] = tail call target("spirv.VulkanBuffer", i32, 12, 1) @llvm.spv.resource.counterhandlefrombinding.tspirv.VulkanBuffer_i32_12_1t.tspirv.VulkanBuffer_a0i32_12_1t(target("spirv.VulkanBuffer", [0 x i32], 12, 1) [[I]], i32 0, i32 0)
; CHECK-NEXT:    [[I7:%.*]] = tail call i32 @llvm.spv.resource.updatecounter.tspirv.VulkanBuffer_i32_12_1t(target("spirv.VulkanBuffer", i32, 12, 1) [[I6]], i8 1)
; CHECK-NEXT:    [[I8:%.*]] = tail call noundef nonnull align 4 dereferenceable(4) ptr addrspace(11) @llvm.spv.resource.getpointer.p11.tspirv.VulkanBuffer_a0i32_12_1t.i32(target("spirv.VulkanBuffer", [0 x i32], 12, 1) [[I]], i32 0)
; CHECK-NEXT:    store i32 [[I7]], ptr addrspace(11) [[I8]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %0 = tail call target("spirv.VulkanBuffer", [0 x i32], 12, 1) @llvm.spv.resource.handlefrombinding.tspirv.VulkanBuffer_a0i32_12_1t(i32 0, i32 0, i32 4, i32 0, ptr nonnull @Out.str)
  %1 = load i32, ptr addrspace(2) @cond, align 4
  %loadedv = trunc nuw i32 %1 to i1
  br i1 %loadedv, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %2 = tail call target("spirv.VulkanBuffer", i32, 12, 1) @llvm.spv.resource.counterhandlefrombinding.tspirv.VulkanBuffer_i32_12_1t.tspirv.VulkanBuffer_a0i32_12_1t(target("spirv.VulkanBuffer", [0 x i32], 12, 1) %0, i32 0, i32 0)
  %3 = tail call i32 @llvm.spv.resource.updatecounter.tspirv.VulkanBuffer_i32_12_1t(target("spirv.VulkanBuffer", i32, 12, 1) %2, i8 1)
  br label %exit

if.else:                                          ; preds = %entry
  %4 = tail call target("spirv.VulkanBuffer", i32, 12, 1) @llvm.spv.resource.counterhandlefrombinding.tspirv.VulkanBuffer_i32_12_1t.tspirv.VulkanBuffer_a0i32_12_1t(target("spirv.VulkanBuffer", [0 x i32], 12, 1) %0, i32 0, i32 0)
  %5 = tail call i32 @llvm.spv.resource.updatecounter.tspirv.VulkanBuffer_i32_12_1t(target("spirv.VulkanBuffer", i32, 12, 1) %4, i8 1)
  br label %exit

exit:                                             ; preds = %if.else, %if.then
  %6 = tail call target("spirv.VulkanBuffer", i32, 12, 1) @llvm.spv.resource.counterhandlefrombinding.tspirv.VulkanBuffer_i32_12_1t.tspirv.VulkanBuffer_a0i32_12_1t(target("spirv.VulkanBuffer", [0 x i32], 12, 1) %0, i32 0, i32 0)
  %7 = tail call i32 @llvm.spv.resource.updatecounter.tspirv.VulkanBuffer_i32_12_1t(target("spirv.VulkanBuffer", i32, 12, 1) %6, i8 1)
  %8 = tail call noundef nonnull align 4 dereferenceable(4) ptr addrspace(11) @llvm.spv.resource.getpointer.p11.tspirv.VulkanBuffer_a0i32_12_1t.i32(target("spirv.VulkanBuffer", [0 x i32], 12, 1) %0, i32 0)
  store i32 %7, ptr addrspace(11) %8, align 4
  ret void
}
