; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=gvn -S %s | FileCheck %s

%MyStruct = type { i32, i32 }

define i8 @foo(i64 %in, ptr %arr, i1 %arg) {
; CHECK-LABEL: define i8 @foo(
; CHECK-SAME: i64 [[IN:%.*]], ptr [[ARR:%.*]], i1 [[ARG:%.*]]) {
; CHECK-NEXT:    [[ADDR:%.*]] = alloca [[MYSTRUCT:%.*]], align 8
; CHECK-NEXT:    [[DEAD:%.*]] = trunc i64 [[IN]] to i32
; CHECK-NEXT:    br i1 [[ARG]], label %[[NEXT:.*]], label %[[TMP:.*]]
; CHECK:       [[TMP]]:
; CHECK-NEXT:    call void @bar()
; CHECK-NEXT:    br label %[[NEXT]]
; CHECK:       [[NEXT]]:
; CHECK-NEXT:    store i64 [[IN]], ptr [[ADDR]], align 4
; CHECK-NEXT:    [[RESPTR:%.*]] = getelementptr i8, ptr [[ARR]], i32 [[DEAD]]
; CHECK-NEXT:    [[RES:%.*]] = load i8, ptr [[RESPTR]], align 1
; CHECK-NEXT:    ret i8 [[RES]]
;
  %addr = alloca %MyStruct
  %dead = trunc i64 %in to i32
  br i1 %arg, label %next, label %tmp

tmp:
  call void @bar()
  br label %next

next:
  store i64 %in, ptr %addr
  br label %final

final:
  %idx32 = load i32, ptr %addr
  %resptr = getelementptr i8, ptr %arr, i32 %idx32
  %res = load i8, ptr %resptr
  ret i8 %res
}

declare void @bar()
