; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=gvn < %s | FileCheck %s

; When GVN coerces a wider load into a narrower load at an offset, it strips
; !noalias and !alias.scope from the surviving wider load. That load is
; unchanged and still accesses the same memory, so the metadata stays valid
; and should be kept. It is currently dropped.

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

; The i8 load at P+1 partially aliases the i32 load at P and is coerced from
; it. The surviving i32 load should keep its !noalias.
define i32 @noalias_dropped_local(ptr %p) {
; CHECK-LABEL: define i32 @noalias_dropped_local(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[WIDE:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    [[P1:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = lshr i32 [[WIDE]], 8
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i32 [[TMP0]] to i8
; CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[WIDE]], [[CONV]]
; CHECK-NEXT:    ret i32 [[ADD]]
;
entry:
  %wide = load i32, ptr %p, align 4, !noalias !0
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %narrow = load i8, ptr %p1, align 1
  %conv = zext i8 %narrow to i32
  %add = add nsw i32 %wide, %conv
  ret i32 %add
}

; Same as above for !alias.scope on the surviving wider load.
define i32 @alias_scope_dropped_local(ptr %p) {
; CHECK-LABEL: define i32 @alias_scope_dropped_local(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[WIDE:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    [[P1:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = lshr i32 [[WIDE]], 8
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i32 [[TMP0]] to i8
; CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[WIDE]], [[CONV]]
; CHECK-NEXT:    ret i32 [[ADD]]
;
entry:
  %wide = load i32, ptr %p, align 4, !alias.scope !0
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %narrow = load i8, ptr %p1, align 1
  %conv = zext i8 %narrow to i32
  %add = add nsw i32 %wide, %conv
  ret i32 %add
}

; Cross-block (non-local) coerced load. The i32 load in entry is forwarded to
; the i8 load at P+1 in the taken block. The surviving i32 load should keep
; its !noalias.
define i32 @noalias_dropped_nonlocal(ptr %p) {
; CHECK-LABEL: define i32 @noalias_dropped_nonlocal(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[WIDE:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[WIDE]], 127
; CHECK-NEXT:    [[TMP0:%.*]] = lshr i32 [[WIDE]], 8
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i32 [[TMP0]] to i8
; CHECK-NEXT:    br i1 [[CMP]], label %[[T:.*]], label %[[F:.*]]
; CHECK:       [[T]]:
; CHECK-NEXT:    [[P1:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 1
; CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
; CHECK:       [[F]]:
; CHECK-NEXT:    ret i32 52
;
entry:
  %wide = load i32, ptr %p, align 4, !noalias !0
  %cmp = icmp eq i32 %wide, 127
  br i1 %cmp, label %t, label %f

t:
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %narrow = load i8, ptr %p1, align 1
  %conv = zext i8 %narrow to i32
  ret i32 %conv

f:
  ret i32 52
}

; Alias-scope metadata domain.
!1 = distinct !{!1, !2, !"scope A"}
!2 = distinct !{!2, !"test domain"}

!0 = !{!1}
