; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=gvn %s -S | FileCheck %s
define <2 x float> @fmul_extract_basic(<2 x float> %v0, <2 x float> %v1, <2 x float> %v2, <2 x float> %v3) {
; CHECK-LABEL: define <2 x float> @fmul_extract_basic(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]], <2 x float> [[V2:%.*]], <2 x float> [[V3:%.*]]) {
; CHECK-NEXT:    [[R0:%.*]] = extractelement <2 x float> [[V0]], i64 1
; CHECK-NEXT:    [[R3:%.*]] = extractelement <2 x float> [[V3]], i64 1
; CHECK-NEXT:    [[V:%.*]] = fmul <2 x float> [[V0]], [[V3]]
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[V]], i64 1
; CHECK-NEXT:    ret <2 x float> [[V]]
;
  %r0 = extractelement <2 x float> %v0, i64 1
  %r3 = extractelement <2 x float> %v3, i64 1
  %v = fmul <2 x float> %v0, %v3
  %mul = fmul float %r0, %r3
  %ins = insertelement <2 x float> %v, float %mul, i64 1
  ret <2 x float> %ins
}

define float @fmul_simple(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @fmul_simple(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[V]], i64 0
; CHECK-NEXT:    ret float [[TMP1]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul <2 x float> %v0, %v1
  %mul = fmul float %e0, %e1
  ret float %mul
}

define i32 @mul_simple(<2 x i32> %v0, <2 x i32> %v1) {
; CHECK-LABEL: define i32 @mul_simple(
; CHECK-SAME: <2 x i32> [[V0:%.*]], <2 x i32> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x i32> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x i32> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = mul <2 x i32> [[V0]], [[V1]]
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x i32> [[V]], i64 0
; CHECK-NEXT:    ret i32 [[TMP1]]
;
  %e0 = extractelement <2 x i32> %v0, i64 0
  %e1 = extractelement <2 x i32> %v1, i64 0
  %v = mul <2 x i32> %v0, %v1
  %mul = mul i32 %e0, %e1
  ret i32 %mul
}

; Scalar operands are in the reverse order of the vector operands.
define float @fmul_commutative(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @fmul_commutative(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[V]], i64 0
; CHECK-NEXT:    ret float [[TMP1]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul <2 x float> %v0, %v1
  %mul = fmul float %e1, %e0
  ret float %mul
}

; Both scalar and vector have nnan - ok to fold.
define float @fmul_both_nnan(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @fmul_both_nnan(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul nnan <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[V]], i64 0
; CHECK-NEXT:    ret float [[TMP1]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul nnan <2 x float> %v0, %v1
  %mul = fmul nnan float %e0, %e1
  ret float %mul
}

; Both scalar and vector have nsw - ok to fold.
define i32 @mul_both_nsw(<2 x i32> %v0, <2 x i32> %v1) {
; CHECK-LABEL: define i32 @mul_both_nsw(
; CHECK-SAME: <2 x i32> [[V0:%.*]], <2 x i32> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x i32> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x i32> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = mul nsw <2 x i32> [[V0]], [[V1]]
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x i32> [[V]], i64 0
; CHECK-NEXT:    ret i32 [[TMP1]]
;
  %e0 = extractelement <2 x i32> %v0, i64 0
  %e1 = extractelement <2 x i32> %v1, i64 0
  %v = mul nsw <2 x i32> %v0, %v1
  %mul = mul nsw i32 %e0, %e1
  ret i32 %mul
}

; Negative test: extracts from different indices.
define float @neg_different_indices(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @neg_different_indices(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 1
; CHECK-NEXT:    [[V:%.*]] = fmul <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[E0]], [[E1]]
; CHECK-NEXT:    ret float [[MUL]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 1
  %v = fmul <2 x float> %v0, %v1
  %mul = fmul float %e0, %e1
  ret float %mul
}

; Negative test: vector fmul has nnan but scalar does not.
define float @neg_vector_has_nnan(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @neg_vector_has_nnan(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul nnan <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[E0]], [[E1]]
; CHECK-NEXT:    ret float [[MUL]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul nnan <2 x float> %v0, %v1
  %mul = fmul float %e0, %e1
  ret float %mul
}

; Negative test: vector fmul has ninf but scalar does not.
define float @neg_vector_has_ninf(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @neg_vector_has_ninf(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul ninf <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[E0]], [[E1]]
; CHECK-NEXT:    ret float [[MUL]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul ninf <2 x float> %v0, %v1
  %mul = fmul float %e0, %e1
  ret float %mul
}

; Negative test: vector fmul has nsz but scalar does not.
define float @neg_vector_has_nsz(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @neg_vector_has_nsz(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul nsz <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[E0]], [[E1]]
; CHECK-NEXT:    ret float [[MUL]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul nsz <2 x float> %v0, %v1
  %mul = fmul float %e0, %e1
  ret float %mul
}

; Negative test: vector fmul has reassoc but scalar does not.
define float @neg_vector_has_reassoc(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @neg_vector_has_reassoc(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul reassoc <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[E0]], [[E1]]
; CHECK-NEXT:    ret float [[MUL]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul reassoc <2 x float> %v0, %v1
  %mul = fmul float %e0, %e1
  ret float %mul
}

; Negative test: vector fmul has arcp but scalar does not.
define float @neg_vector_has_arcp(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @neg_vector_has_arcp(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul arcp <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[E0]], [[E1]]
; CHECK-NEXT:    ret float [[MUL]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul arcp <2 x float> %v0, %v1
  %mul = fmul float %e0, %e1
  ret float %mul
}

; Negative test: vector fmul has contract but scalar does not.
define float @neg_vector_has_contract(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @neg_vector_has_contract(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul contract <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[E0]], [[E1]]
; CHECK-NEXT:    ret float [[MUL]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul contract <2 x float> %v0, %v1
  %mul = fmul float %e0, %e1
  ret float %mul
}

; Negative test: vector fmul has afn but scalar does not.
define float @neg_vector_has_afn(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @neg_vector_has_afn(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul afn <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[E0]], [[E1]]
; CHECK-NEXT:    ret float [[MUL]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul afn <2 x float> %v0, %v1
  %mul = fmul float %e0, %e1
  ret float %mul
}

; Negative test: vector fmul has !fpmath but scalar does not.
define float @neg_vector_has_fpmath(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @neg_vector_has_fpmath(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul <2 x float> [[V0]], [[V1]], !fpmath [[META0:![0-9]+]]
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[E0]], [[E1]]
; CHECK-NEXT:    ret float [[MUL]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul <2 x float> %v0, %v1, !fpmath !0
  %mul = fmul float %e0, %e1
  ret float %mul
}

; Scalar fmul allows looser error than the vector fmul - ok to fold.
define float @fmul_scalar_has_fpmath(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @fmul_scalar_has_fpmath(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul <2 x float> [[V0]], [[V1]], !fpmath [[META0:![0-9]+]]
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[V]], i64 0
; CHECK-NEXT:    ret float [[TMP1]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul <2 x float> %v0, %v1, !fpmath !0
  %mul = fmul float %e0, %e1, !fpmath !1
  ret float %mul
}

; Negative test: scalar fmul has nnan but vector does not.
define float @neg_scalar_has_nnan(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @neg_scalar_has_nnan(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    [[MUL:%.*]] = fmul nnan float [[E0]], [[E1]]
; CHECK-NEXT:    ret float [[MUL]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul <2 x float> %v0, %v1
  %mul = fmul nnan float %e0, %e1
  ret float %mul
}

; Negative test: scalar fmul has ninf but vector does not.
define float @neg_scalar_has_ninf(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @neg_scalar_has_ninf(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    [[MUL:%.*]] = fmul ninf float [[E0]], [[E1]]
; CHECK-NEXT:    ret float [[MUL]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul <2 x float> %v0, %v1
  %mul = fmul ninf float %e0, %e1
  ret float %mul
}

; Scalar rewrite FMF can fold to an exact vector fmul result.
define float @fmul_scalar_has_rewrite_fmf(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @fmul_scalar_has_rewrite_fmf(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[V]], i64 0
; CHECK-NEXT:    ret float [[TMP1]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul <2 x float> %v0, %v1
  %mul = fmul reassoc arcp contract afn float %e0, %e1
  ret float %mul
}

; Scalar nsz can fold to an exact vector fmul result.
define float @fmul_scalar_has_nsz(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @fmul_scalar_has_nsz(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = fmul <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[V]], i64 0
; CHECK-NEXT:    ret float [[TMP1]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %v = fmul <2 x float> %v0, %v1
  %mul = fmul nsz float %e0, %e1
  ret float %mul
}

; Negative test: vector mul has nsw but scalar does not.
define i32 @neg_vector_has_nsw(<2 x i32> %v0, <2 x i32> %v1) {
; CHECK-LABEL: define i32 @neg_vector_has_nsw(
; CHECK-SAME: <2 x i32> [[V0:%.*]], <2 x i32> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x i32> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x i32> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = mul nsw <2 x i32> [[V0]], [[V1]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 [[E0]], [[E1]]
; CHECK-NEXT:    ret i32 [[MUL]]
;
  %e0 = extractelement <2 x i32> %v0, i64 0
  %e1 = extractelement <2 x i32> %v1, i64 0
  %v = mul nsw <2 x i32> %v0, %v1
  %mul = mul i32 %e0, %e1
  ret i32 %mul
}

; Negative test: scalar mul has nsw but vector does not.
define i32 @neg_scalar_has_nsw(<2 x i32> %v0, <2 x i32> %v1) {
; CHECK-LABEL: define i32 @neg_scalar_has_nsw(
; CHECK-SAME: <2 x i32> [[V0:%.*]], <2 x i32> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x i32> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x i32> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = mul <2 x i32> [[V0]], [[V1]]
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[E0]], [[E1]]
; CHECK-NEXT:    ret i32 [[MUL]]
;
  %e0 = extractelement <2 x i32> %v0, i64 0
  %e1 = extractelement <2 x i32> %v1, i64 0
  %v = mul <2 x i32> %v0, %v1
  %mul = mul nsw i32 %e0, %e1
  ret i32 %mul
}

; Negative test: vector mul has nuw but scalar does not.
define i32 @neg_vector_has_nuw(<2 x i32> %v0, <2 x i32> %v1) {
; CHECK-LABEL: define i32 @neg_vector_has_nuw(
; CHECK-SAME: <2 x i32> [[V0:%.*]], <2 x i32> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x i32> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x i32> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = mul nuw <2 x i32> [[V0]], [[V1]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 [[E0]], [[E1]]
; CHECK-NEXT:    ret i32 [[MUL]]
;
  %e0 = extractelement <2 x i32> %v0, i64 0
  %e1 = extractelement <2 x i32> %v1, i64 0
  %v = mul nuw <2 x i32> %v0, %v1
  %mul = mul i32 %e0, %e1
  ret i32 %mul
}

; Negative test: scalar mul has nuw but vector does not.
define i32 @neg_scalar_has_nuw(<2 x i32> %v0, <2 x i32> %v1) {
; CHECK-LABEL: define i32 @neg_scalar_has_nuw(
; CHECK-SAME: <2 x i32> [[V0:%.*]], <2 x i32> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x i32> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x i32> [[V1]], i64 0
; CHECK-NEXT:    [[V:%.*]] = mul <2 x i32> [[V0]], [[V1]]
; CHECK-NEXT:    [[MUL:%.*]] = mul nuw i32 [[E0]], [[E1]]
; CHECK-NEXT:    ret i32 [[MUL]]
;
  %e0 = extractelement <2 x i32> %v0, i64 0
  %e1 = extractelement <2 x i32> %v1, i64 0
  %v = mul <2 x i32> %v0, %v1
  %mul = mul nuw i32 %e0, %e1
  ret i32 %mul
}

; Negative test: no existing vector mul.
define float @neg_no_vector_mul(<2 x float> %v0, <2 x float> %v1) {
; CHECK-LABEL: define float @neg_no_vector_mul(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]]) {
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[E0]], [[E1]]
; CHECK-NEXT:    ret float [[MUL]]
;
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %mul = fmul float %e0, %e1
  ret float %mul
}

; Negative test: vector mul does not dominate scalar mul.
define float @neg_no_dominance(<2 x float> %v0, <2 x float> %v1, i1 %cond) {
; CHECK-LABEL: define float @neg_no_dominance(
; CHECK-SAME: <2 x float> [[V0:%.*]], <2 x float> [[V1:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[E0:%.*]] = extractelement <2 x float> [[V0]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <2 x float> [[V1]], i64 0
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[E0]], [[E1]]
; CHECK-NEXT:    br i1 [[COND]], label %[[IF:.*]], label %[[END:.*]]
; CHECK:       [[IF]]:
; CHECK-NEXT:    [[V:%.*]] = fmul <2 x float> [[V0]], [[V1]]
; CHECK-NEXT:    br label %[[END]]
; CHECK:       [[END]]:
; CHECK-NEXT:    ret float [[MUL]]
;
entry:
  %e0 = extractelement <2 x float> %v0, i64 0
  %e1 = extractelement <2 x float> %v1, i64 0
  %mul = fmul float %e0, %e1
  br i1 %cond, label %if, label %end

if:
  %v = fmul <2 x float> %v0, %v1
  br label %end

end:
  ret float %mul
}

!0 = !{float 2.500000e+00}
!1 = !{float 3.000000e+00}
