; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=xtensa -verify-machineinstrs < %s \
; RUN: | FileCheck -check-prefix=XTENSA %s

define i32 @jump(i1 %a) {
; XTENSA-LABEL: jump:
; XTENSA:         movi a8, 1
; XTENSA-NEXT:    and a8, a2, a8
; XTENSA-NEXT:    beqz a8, .LBB0_2
; XTENSA-NEXT:  # %bb.1: # %iftrue
; XTENSA-NEXT:    #APP
; XTENSA-NEXT:    #NO_APP
; XTENSA-NEXT:    #APP
; XTENSA-NEXT:    .space 1024
; XTENSA-NEXT:    #NO_APP
; XTENSA-NEXT:    movi a2, 1
; XTENSA-NEXT:    ret
; XTENSA-NEXT:  .LBB0_2: # %jmp
; XTENSA-NEXT:    #APP
; XTENSA-NEXT:    #NO_APP
; XTENSA-NEXT:    movi a2, 1
; XTENSA-NEXT:    ret
  br i1 %a, label %iftrue, label %jmp

jmp:
  call void asm sideeffect "", ""()
  br label %tail

iftrue:
  call void asm sideeffect "", ""()
  br label %space

space:
  call void asm sideeffect ".space 1024", ""()
  br label %tail

tail:
  ret i32 1
}

define i32 @jx(i1 %a) {
; XTENSA-LABEL: jx:
; XTENSA:         addi a8, a1, -16
; XTENSA-NEXT:    or a1, a8, a8
; XTENSA-NEXT:    .cfi_def_cfa_offset 16
; XTENSA-NEXT:    movi a8, 1
; XTENSA-NEXT:    and a8, a2, a8
; XTENSA-NEXT:    bnez a8, .LBB1_1
; XTENSA-NEXT:  # %bb.4:
; XTENSA-NEXT:    l32r a8, .LCPI1_0
; XTENSA-NEXT:    jx a8
; XTENSA-NEXT:  .LBB1_1: # %iftrue
; XTENSA-NEXT:    #APP
; XTENSA-NEXT:    #NO_APP
; XTENSA-NEXT:    #APP
; XTENSA-NEXT:    .space 1048576
; XTENSA-NEXT:    #NO_APP
; XTENSA-NEXT:    j .LBB1_3
; XTENSA-NEXT:  .LBB1_2: # %jmp
; XTENSA-NEXT:    #APP
; XTENSA-NEXT:    #NO_APP
; XTENSA-NEXT:  .LBB1_3: # %tail
; XTENSA-NEXT:    movi a2, 1
; XTENSA-NEXT:    addi a8, a1, 16
; XTENSA-NEXT:    or a1, a8, a8
; XTENSA-NEXT:    ret
  br i1 %a, label %iftrue, label %jmp

jmp:
  call void asm sideeffect "", ""()
  br label %tail

iftrue:
  call void asm sideeffect "", ""()
  br label %space

space:
  call void asm sideeffect ".space 1048576", ""()
  br label %tail

tail:
  ret i32 1
}
