/*===--------------------------------------------------------------------------
 *                   ROCm Device Libraries
 *
 * This file is distributed under the University of Illinois Open Source
 * License. See LICENSE.TXT for details.
 *===------------------------------------------------------------------------*/

#include "test_opencl.h"

TEST_KERNEL_FUNC(acos, float, float)
TEST_KERNEL_FUNC(acosh, float, float)
TEST_KERNEL_FUNC(acospi, float, float)
TEST_KERNEL_FUNC(asin, float, float)
TEST_KERNEL_FUNC(asinh, float, float)
TEST_KERNEL_FUNC(asinpi, float, float)
TEST_KERNEL_FUNC(atan, float, float)
TEST_KERNEL_FUNC2(atan2, float, float, float)
TEST_KERNEL_FUNC(atanh, float, float)
TEST_KERNEL_FUNC(atanpi, float, float)
TEST_KERNEL_FUNC2(atan2pi, float, float, float)
TEST_KERNEL_FUNC(cbrt, float, float)
TEST_KERNEL_FUNC(ceil, float, float)
TEST_KERNEL_FUNC2(copysign, float, float, float)
TEST_KERNEL_FUNC(cos, float, float)
TEST_KERNEL_FUNC(cosh, float, float)
TEST_KERNEL_FUNC(cospi, float, float)
TEST_KERNEL_FUNC(erfc, float, float)
TEST_KERNEL_FUNC(erf, float, float)
TEST_KERNEL_FUNC(exp, float, float)
TEST_KERNEL_FUNC(exp2, float, float)
TEST_KERNEL_FUNC(exp10, float, float)
TEST_KERNEL_FUNC(expm1, float, float)
TEST_KERNEL_FUNC(fabs, float, float)
TEST_KERNEL_FUNC2(fdim, float, float, float)
TEST_KERNEL_FUNC(floor, float, float)
TEST_KERNEL_FUNC3(fma, float, float, float, float)
TEST_KERNEL_FUNC2(fmax, float, float, float)
TEST_KERNEL_FUNC2(fmin, float, float, float)
TEST_KERNEL_FUNC2(fmod, float, float, float)
TEST_KERNEL_FUNC2p(fract, float, float, float)
TEST_KERNEL_FUNC2p(frexp, float, int, float)
TEST_KERNEL_FUNC2(hypot, float, float, float)
TEST_KERNEL_FUNC(ilogb, float, float)
TEST_KERNEL_FUNC2(ldexp, float, float, int)
TEST_KERNEL_FUNC(lgamma, float, float)
TEST_KERNEL_FUNC2p(lgamma_r, float, int, float)
TEST_KERNEL_FUNC(log, float, float)
TEST_KERNEL_FUNC(log2, float, float)
TEST_KERNEL_FUNC(log10, float, float)
TEST_KERNEL_FUNC(log1p, float, float)
TEST_KERNEL_FUNC(logb, float, float)
TEST_KERNEL_FUNC3(mad, float, float, float, float)
TEST_KERNEL_FUNC2(maxmag, float, float, float)
TEST_KERNEL_FUNC2(minmag, float, float, float)
TEST_KERNEL_FUNC2p(modf, float, float, float)
TEST_KERNEL_FUNC(nan, float, uint)
TEST_KERNEL_FUNC2(nextafter, float, float, float)
TEST_KERNEL_FUNC2(pow, float, float, float)
TEST_KERNEL_FUNC2(pown, float, float, int)
TEST_KERNEL_FUNC2(powr, float, float, float)
TEST_KERNEL_FUNC2(remainder, float, float, float)
TEST_KERNEL_FUNC3p(remquo, float, int, float, float)
TEST_KERNEL_FUNC(rint, float, float)
TEST_KERNEL_FUNC2(rootn, float, float, int)
TEST_KERNEL_FUNC(round, float, float)
TEST_KERNEL_FUNC(rsqrt, float, float)
TEST_KERNEL_FUNC(sin, float, float)
TEST_KERNEL_FUNC2p(sincos, float, float, float)
TEST_KERNEL_FUNC(sinh, float, float)
TEST_KERNEL_FUNC(sinpi, float, float)
TEST_KERNEL_FUNC(sqrt, float, float)
TEST_KERNEL_FUNC(tan, float, float)
TEST_KERNEL_FUNC(tanh, float, float)
TEST_KERNEL_FUNC(tanpi, float, float)
TEST_KERNEL_FUNC(tgamma, float, float)
TEST_KERNEL_FUNC(trunc, float, float)
TEST_KERNEL_FUNC(half_cos, float, float)
TEST_KERNEL_FUNC(native_cos, float, float)
TEST_KERNEL_FUNC2(half_divide, float, float, float)
TEST_KERNEL_FUNC2(native_divide, float, float, float)
TEST_KERNEL_FUNC(half_exp, float, float)
TEST_KERNEL_FUNC(native_exp, float, float)
TEST_KERNEL_FUNC(half_exp2, float, float)
TEST_KERNEL_FUNC(native_exp2, float, float)
TEST_KERNEL_FUNC(half_exp10, float, float)
TEST_KERNEL_FUNC(native_exp10, float, float)
TEST_KERNEL_FUNC(half_log, float, float)
TEST_KERNEL_FUNC(native_log, float, float)
TEST_KERNEL_FUNC(half_log2, float, float)
TEST_KERNEL_FUNC(native_log2, float, float)
TEST_KERNEL_FUNC(half_log10, float, float)
TEST_KERNEL_FUNC(native_log10, float, float)
TEST_KERNEL_FUNC2(half_powr, float, float, float)
TEST_KERNEL_FUNC2(native_powr, float, float, float)
TEST_KERNEL_FUNC(half_recip, float, float)
TEST_KERNEL_FUNC(native_recip, float, float)
TEST_KERNEL_FUNC(half_rsqrt, float, float)
TEST_KERNEL_FUNC(native_rsqrt, float, float)
TEST_KERNEL_FUNC(half_sin, float, float)
TEST_KERNEL_FUNC(native_sin, float, float)
TEST_KERNEL_FUNC(half_sqrt, float, float)
TEST_KERNEL_FUNC(native_sqrt, float, float)
TEST_KERNEL_FUNC(half_tan, float, float)
TEST_KERNEL_FUNC(native_tan, float, float)

TEST_KERNEL_FUNC(acos, double, double)
TEST_KERNEL_FUNC(acosh, double, double)
TEST_KERNEL_FUNC(acospi, double, double)
TEST_KERNEL_FUNC(asin, double, double)
TEST_KERNEL_FUNC(asinh, double, double)
TEST_KERNEL_FUNC(asinpi, double, double)
TEST_KERNEL_FUNC(atan, double, double)
TEST_KERNEL_FUNC2(atan2, double, double, double)
TEST_KERNEL_FUNC(atanh, double, double)
TEST_KERNEL_FUNC(atanpi, double, double)
TEST_KERNEL_FUNC2(atan2pi, double, double, double)
TEST_KERNEL_FUNC(cbrt, double, double)
TEST_KERNEL_FUNC(ceil, double, double)
TEST_KERNEL_FUNC2(copysign, double, double, double)
TEST_KERNEL_FUNC(cos, double, double)
TEST_KERNEL_FUNC(cosh, double, double)
TEST_KERNEL_FUNC(cospi, double, double)
TEST_KERNEL_FUNC(erfc, double, double)
TEST_KERNEL_FUNC(erf, double, double)
TEST_KERNEL_FUNC(exp, double, double)
TEST_KERNEL_FUNC(exp2, double, double)
TEST_KERNEL_FUNC(exp10, double, double)
TEST_KERNEL_FUNC(expm1, double, double)
TEST_KERNEL_FUNC(fabs, double, double)
TEST_KERNEL_FUNC2(fdim, double, double, double)
TEST_KERNEL_FUNC(floor, double, double)
TEST_KERNEL_FUNC3(fma, double, double, double, double)
TEST_KERNEL_FUNC2(fmax, double, double, double)
TEST_KERNEL_FUNC2(fmin, double, double, double)
TEST_KERNEL_FUNC2(fmod, double, double, double)
TEST_KERNEL_FUNC2p(fract, double, double, double)
TEST_KERNEL_FUNC2p(frexp, double, int, double)
TEST_KERNEL_FUNC2(hypot, double, double, double)
TEST_KERNEL_FUNC(ilogb, double, double)
TEST_KERNEL_FUNC2(ldexp, double, double, long)
TEST_KERNEL_FUNC(lgamma, double, double)
TEST_KERNEL_FUNC2p(lgamma_r, double, int, double)
TEST_KERNEL_FUNC(log, double, double)
TEST_KERNEL_FUNC(log2, double, double)
TEST_KERNEL_FUNC(log10, double, double)
TEST_KERNEL_FUNC(log1p, double, double)
TEST_KERNEL_FUNC(logb, double, double)
TEST_KERNEL_FUNC3(mad, double, double, double, double)
TEST_KERNEL_FUNC2(maxmag, double, double, double)
TEST_KERNEL_FUNC2(minmag, double, double, double)
TEST_KERNEL_FUNC2p(modf, double, double, double)
TEST_KERNEL_FUNC(nan, double, ulong)
TEST_KERNEL_FUNC2(nextafter, double, double, double)
TEST_KERNEL_FUNC2(pow, double, double, double)
TEST_KERNEL_FUNC2(pown, double, double, long)
TEST_KERNEL_FUNC2(powr, double, double, double)
TEST_KERNEL_FUNC2(remainder, double, double, double)
TEST_KERNEL_FUNC3p(remquo, double, int, double, double)
TEST_KERNEL_FUNC(rint, double, double)
TEST_KERNEL_FUNC2(rootn, double, double, long)
TEST_KERNEL_FUNC(round, double, double)
TEST_KERNEL_FUNC(rsqrt, double, double)
TEST_KERNEL_FUNC(sin, double, double)
TEST_KERNEL_FUNC2p(sincos, double, double, double)
TEST_KERNEL_FUNC(sinh, double, double)
TEST_KERNEL_FUNC(sinpi, double, double)
TEST_KERNEL_FUNC(sqrt, double, double)
TEST_KERNEL_FUNC(tan, double, double)
TEST_KERNEL_FUNC(tanh, double, double)
TEST_KERNEL_FUNC(tanpi, double, double)
TEST_KERNEL_FUNC(tgamma, double, double)
TEST_KERNEL_FUNC(trunc, double, double)
//TEST_KERNEL_FUNC(half_cos, double, double)
TEST_KERNEL_FUNC(native_cos, double, double)
//TEST_KERNEL_FUNC2(half_divide, double, double, double)
TEST_KERNEL_FUNC2(native_divide, double, double, double)
//TEST_KERNEL_FUNC(half_exp, double, double)
TEST_KERNEL_FUNC(native_exp, double, double)
//TEST_KERNEL_FUNC(half_exp2, double, double)
TEST_KERNEL_FUNC(native_exp2, double, double)
//TEST_KERNEL_FUNC(half_exp10, double, double)
TEST_KERNEL_FUNC(native_exp10, double, double)
//TEST_KERNEL_FUNC(half_log, double, double)
TEST_KERNEL_FUNC(native_log, double, double)
//TEST_KERNEL_FUNC(half_log2, double, double)
TEST_KERNEL_FUNC(native_log2, double, double)
//TEST_KERNEL_FUNC(half_log10, double, double)
TEST_KERNEL_FUNC(native_log10, double, double)
//TEST_KERNEL_FUNC2(half_powr, double, double, double)
TEST_KERNEL_FUNC2(native_powr, double, double, double)
//TEST_KERNEL_FUNC(half_recip, double, double)
TEST_KERNEL_FUNC(native_recip, double, double)
//TEST_KERNEL_FUNC(half_rsqrt, double, double)
TEST_KERNEL_FUNC(native_rsqrt, double, double)
//TEST_KERNEL_FUNC(half_sin, double, double)
TEST_KERNEL_FUNC(native_sin, double, double)
//TEST_KERNEL_FUNC(half_sqrt, double, double)
TEST_KERNEL_FUNC(native_sqrt, double, double)
//TEST_KERNEL_FUNC(half_tan, double, double)
TEST_KERNEL_FUNC(native_tan, double, double)
