/*===--------------------------------------------------------------------------
 *                   ROCm Device Libraries
 *
 * This file is distributed under the University of Illinois Open Source
 * License. See LICENSE.TXT for details.
 *===------------------------------------------------------------------------*/

#include "test_opencl.h"

TEST_KERNEL_FUNC_VEC(acos, float, float)
TEST_KERNEL_FUNC_VEC(acosh, float, float)
TEST_KERNEL_FUNC_VEC(acospi, float, float)
TEST_KERNEL_FUNC_VEC(asin, float, float)
TEST_KERNEL_FUNC_VEC(asinh, float, float)
TEST_KERNEL_FUNC_VEC(asinpi, float, float)
TEST_KERNEL_FUNC_VEC(atan, float, float)
TEST_KERNEL_FUNC2_VEC(atan2, float, float, float)
TEST_KERNEL_FUNC_VEC(atanh, float, float)
TEST_KERNEL_FUNC_VEC(atanpi, float, float)
TEST_KERNEL_FUNC2_VEC(atan2pi, float, float, float)
TEST_KERNEL_FUNC_VEC(cbrt, float, float)
TEST_KERNEL_FUNC_VEC(ceil, float, float)
TEST_KERNEL_FUNC2_VEC(copysign, float, float, float)
TEST_KERNEL_FUNC_VEC(cos, float, float)
TEST_KERNEL_FUNC_VEC(cosh, float, float)
TEST_KERNEL_FUNC_VEC(cospi, float, float)
TEST_KERNEL_FUNC_VEC(erfc, float, float)
TEST_KERNEL_FUNC_VEC(erf, float, float)
TEST_KERNEL_FUNC_VEC(exp, float, float)
TEST_KERNEL_FUNC_VEC(exp2, float, float)
TEST_KERNEL_FUNC_VEC(exp10, float, float)
TEST_KERNEL_FUNC_VEC(expm1, float, float)
TEST_KERNEL_FUNC_VEC(fabs, float, float)
TEST_KERNEL_FUNC2_VEC(fdim, float, float, float)
TEST_KERNEL_FUNC_VEC(floor, float, float)
TEST_KERNEL_FUNC3_VEC(fma, float, float, float, float)
TEST_KERNEL_FUNC2_VEC(fmax, float, float, float)
TEST_KERNEL_FUNC2_VEC(fmin, float, float, float)
TEST_KERNEL_FUNC2_VEC(fmod, float, float, float)
TEST_KERNEL_FUNC2p_VEC(fract, float, float, float)
TEST_KERNEL_FUNC2p_VEC(frexp, float, int, float)
TEST_KERNEL_FUNC2_VEC(hypot, float, float, float)
TEST_KERNEL_FUNC_VEC(ilogb, int, float)
TEST_KERNEL_FUNC2_VEC(ldexp, float, float, int)
TEST_KERNEL_FUNC_VEC(lgamma, float, float)
TEST_KERNEL_FUNC2p_VEC(lgamma_r, float, int, float)
TEST_KERNEL_FUNC_VEC(log, float, float)
TEST_KERNEL_FUNC_VEC(log2, float, float)
TEST_KERNEL_FUNC_VEC(log10, float, float)
TEST_KERNEL_FUNC_VEC(log1p, float, float)
TEST_KERNEL_FUNC_VEC(logb, float, float)
TEST_KERNEL_FUNC3_VEC(mad, float, float, float, float)
TEST_KERNEL_FUNC2_VEC(maxmag, float, float, float)
TEST_KERNEL_FUNC2_VEC(minmag, float, float, float)
TEST_KERNEL_FUNC2p_VEC(modf, float, float, float)
TEST_KERNEL_FUNC_VEC(nan, float, uint)
TEST_KERNEL_FUNC2_VEC(nextafter, float, float, float)
TEST_KERNEL_FUNC2_VEC(pow, float, float, float)
TEST_KERNEL_FUNC2_VEC(pown, float, float, int)
TEST_KERNEL_FUNC2_VEC(powr, float, float, float)
TEST_KERNEL_FUNC2_VEC(remainder, float, float, float)
TEST_KERNEL_FUNC3p_VEC(remquo, float, int, float, float)
TEST_KERNEL_FUNC_VEC(rint, float, float)
TEST_KERNEL_FUNC2_VEC(rootn, float, float, int)
TEST_KERNEL_FUNC_VEC(round, float, float)
TEST_KERNEL_FUNC_VEC(rsqrt, float, float)
TEST_KERNEL_FUNC_VEC(sin, float, float)
TEST_KERNEL_FUNC2p_VEC(sincos, float, float, float)
TEST_KERNEL_FUNC_VEC(sinh, float, float)
TEST_KERNEL_FUNC_VEC(sinpi, float, float)
TEST_KERNEL_FUNC_VEC(sqrt, float, float)
TEST_KERNEL_FUNC_VEC(tan, float, float)
TEST_KERNEL_FUNC_VEC(tanh, float, float)
TEST_KERNEL_FUNC_VEC(tanpi, float, float)
TEST_KERNEL_FUNC_VEC(tgamma, float, float)
TEST_KERNEL_FUNC_VEC(trunc, float, float)
TEST_KERNEL_FUNC_VEC(half_cos, float, float)
TEST_KERNEL_FUNC_VEC(native_cos, float, float)
TEST_KERNEL_FUNC2_VEC(half_divide, float, float, float)
TEST_KERNEL_FUNC2_VEC(native_divide, float, float, float)
TEST_KERNEL_FUNC_VEC(half_exp, float, float)
TEST_KERNEL_FUNC_VEC(native_exp, float, float)
TEST_KERNEL_FUNC_VEC(half_exp2, float, float)
TEST_KERNEL_FUNC_VEC(native_exp2, float, float)
TEST_KERNEL_FUNC_VEC(half_exp10, float, float)
TEST_KERNEL_FUNC_VEC(native_exp10, float, float)
TEST_KERNEL_FUNC_VEC(half_log, float, float)
TEST_KERNEL_FUNC_VEC(native_log, float, float)
TEST_KERNEL_FUNC_VEC(half_log2, float, float)
TEST_KERNEL_FUNC_VEC(native_log2, float, float)
TEST_KERNEL_FUNC_VEC(half_log10, float, float)
TEST_KERNEL_FUNC_VEC(native_log10, float, float)
TEST_KERNEL_FUNC2_VEC(half_powr, float, float, float)
TEST_KERNEL_FUNC2_VEC(native_powr, float, float, float)
TEST_KERNEL_FUNC_VEC(half_recip, float, float)
TEST_KERNEL_FUNC(native_recip, float, float)
TEST_KERNEL_FUNC_VEC(half_rsqrt, float, float)
TEST_KERNEL_FUNC(native_rsqrt, float, float)
TEST_KERNEL_FUNC_VEC(half_sin, float, float)
TEST_KERNEL_FUNC(native_sin, float, float)
TEST_KERNEL_FUNC_VEC(half_sqrt, float, float)
TEST_KERNEL_FUNC(native_sqrt, float, float)
TEST_KERNEL_FUNC_VEC(half_tan, float, float)
TEST_KERNEL_FUNC_VEC(native_tan, float, float)

TEST_KERNEL_FUNC_VEC(acos, double, double)
TEST_KERNEL_FUNC_VEC(acosh, double, double)
TEST_KERNEL_FUNC_VEC(acospi, double, double)
TEST_KERNEL_FUNC_VEC(asin, double, double)
TEST_KERNEL_FUNC_VEC(asinh, double, double)
TEST_KERNEL_FUNC_VEC(asinpi, double, double)
TEST_KERNEL_FUNC_VEC(atan, double, double)
TEST_KERNEL_FUNC2_VEC(atan2, double, double, double)
TEST_KERNEL_FUNC_VEC(atanh, double, double)
TEST_KERNEL_FUNC_VEC(atanpi, double, double)
TEST_KERNEL_FUNC2_VEC(atan2pi, double, double, double)
TEST_KERNEL_FUNC_VEC(cbrt, double, double)
TEST_KERNEL_FUNC_VEC(ceil, double, double)
TEST_KERNEL_FUNC2_VEC(copysign, double, double, double)
TEST_KERNEL_FUNC_VEC(cos, double, double)
TEST_KERNEL_FUNC_VEC(cosh, double, double)
TEST_KERNEL_FUNC_VEC(cospi, double, double)
TEST_KERNEL_FUNC_VEC(erfc, double, double)
TEST_KERNEL_FUNC_VEC(erf, double, double)
TEST_KERNEL_FUNC_VEC(exp, double, double)
TEST_KERNEL_FUNC_VEC(exp2, double, double)
TEST_KERNEL_FUNC_VEC(exp10, double, double)
TEST_KERNEL_FUNC_VEC(expm1, double, double)
TEST_KERNEL_FUNC_VEC(fabs, double, double)
TEST_KERNEL_FUNC2_VEC(fdim, double, double, double)
TEST_KERNEL_FUNC_VEC(floor, double, double)
TEST_KERNEL_FUNC3_VEC(fma, double, double, double, double)
TEST_KERNEL_FUNC2_VEC(fmax, double, double, double)
TEST_KERNEL_FUNC2_VEC(fmin, double, double, double)
TEST_KERNEL_FUNC2_VEC(fmod, double, double, double)
TEST_KERNEL_FUNC2p_VEC(fract, double, double, double)
TEST_KERNEL_FUNC2p_VEC(frexp, double, int, double)
TEST_KERNEL_FUNC2_VEC(hypot, double, double, double)
TEST_KERNEL_FUNC_VEC(ilogb, int, double)
TEST_KERNEL_FUNC2_VEC(ldexp, double, double, int)
TEST_KERNEL_FUNC_VEC(lgamma, double, double)
TEST_KERNEL_FUNC2p_VEC(lgamma_r, double, int, double)
TEST_KERNEL_FUNC_VEC(log, double, double)
TEST_KERNEL_FUNC_VEC(log2, double, double)
TEST_KERNEL_FUNC_VEC(log10, double, double)
TEST_KERNEL_FUNC_VEC(log1p, double, double)
TEST_KERNEL_FUNC_VEC(logb, double, double)
TEST_KERNEL_FUNC3_VEC(mad, double, double, double, double)
TEST_KERNEL_FUNC2_VEC(maxmag, double, double, double)
TEST_KERNEL_FUNC2_VEC(minmag, double, double, double)
TEST_KERNEL_FUNC2p_VEC(modf, double, double, double)
TEST_KERNEL_FUNC_VEC(nan, double, ulong)
TEST_KERNEL_FUNC2_VEC(nextafter, double, double, double)
TEST_KERNEL_FUNC2_VEC(pow, double, double, double)
TEST_KERNEL_FUNC2_VEC(pown, double, double, int)
TEST_KERNEL_FUNC2_VEC(powr, double, double, double)
TEST_KERNEL_FUNC2_VEC(remainder, double, double, double)
TEST_KERNEL_FUNC3p_VEC(remquo, double, int, double, double)
TEST_KERNEL_FUNC_VEC(rint, double, double)
TEST_KERNEL_FUNC2_VEC(rootn, double, double, int)
TEST_KERNEL_FUNC_VEC(round, double, double)
TEST_KERNEL_FUNC_VEC(rsqrt, double, double)
TEST_KERNEL_FUNC_VEC(sin, double, double)
TEST_KERNEL_FUNC2p_VEC(sincos, double, double, double)
TEST_KERNEL_FUNC_VEC(sinh, double, double)
TEST_KERNEL_FUNC_VEC(sinpi, double, double)
TEST_KERNEL_FUNC_VEC(sqrt, double, double)
TEST_KERNEL_FUNC_VEC(tan, double, double)
TEST_KERNEL_FUNC_VEC(tanh, double, double)
TEST_KERNEL_FUNC_VEC(tanpi, double, double)
TEST_KERNEL_FUNC_VEC(tgamma, double, double)
TEST_KERNEL_FUNC_VEC(trunc, double, double)
