; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=sparc -mattr=+soft-mul-div < %s | FileCheck %s

; Test mul-by-constant expansion for SparcV7 (no hardware multiply).

define i32 @mul_by_3(i32 %a) nounwind {
; CHECK-LABEL: mul_by_3:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    save %sp, -96, %sp
; CHECK-NEXT:    mov %i0, %o0
; CHECK-NEXT:    call .umul
; CHECK-NEXT:    mov 3, %o1
; CHECK-NEXT:    ret
; CHECK-NEXT:    restore %g0, %o0, %o0
  %1 = mul i32 %a, 3
  ret i32 %1
}

define i32 @mul_by_5(i32 %a) nounwind {
; CHECK-LABEL: mul_by_5:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    save %sp, -96, %sp
; CHECK-NEXT:    mov %i0, %o0
; CHECK-NEXT:    call .umul
; CHECK-NEXT:    mov 5, %o1
; CHECK-NEXT:    ret
; CHECK-NEXT:    restore %g0, %o0, %o0
  %1 = mul i32 %a, 5
  ret i32 %1
}

define i32 @mul_by_7(i32 %a) nounwind {
; CHECK-LABEL: mul_by_7:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    save %sp, -96, %sp
; CHECK-NEXT:    mov %i0, %o0
; CHECK-NEXT:    call .umul
; CHECK-NEXT:    mov 7, %o1
; CHECK-NEXT:    ret
; CHECK-NEXT:    restore %g0, %o0, %o0
  %1 = mul i32 %a, 7
  ret i32 %1
}

define i32 @mul_by_9(i32 %a) nounwind {
; CHECK-LABEL: mul_by_9:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    save %sp, -96, %sp
; CHECK-NEXT:    mov %i0, %o0
; CHECK-NEXT:    call .umul
; CHECK-NEXT:    mov 9, %o1
; CHECK-NEXT:    ret
; CHECK-NEXT:    restore %g0, %o0, %o0
  %1 = mul i32 %a, 9
  ret i32 %1
}

define i32 @mul_by_10(i32 %a) nounwind {
; CHECK-LABEL: mul_by_10:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    save %sp, -96, %sp
; CHECK-NEXT:    mov %i0, %o0
; CHECK-NEXT:    call .umul
; CHECK-NEXT:    mov 10, %o1
; CHECK-NEXT:    ret
; CHECK-NEXT:    restore %g0, %o0, %o0
  %1 = mul i32 %a, 10
  ret i32 %1
}

define i32 @mul_by_15(i32 %a) nounwind {
; CHECK-LABEL: mul_by_15:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    save %sp, -96, %sp
; CHECK-NEXT:    mov %i0, %o0
; CHECK-NEXT:    call .umul
; CHECK-NEXT:    mov 15, %o1
; CHECK-NEXT:    ret
; CHECK-NEXT:    restore %g0, %o0, %o0
  %1 = mul i32 %a, 15
  ret i32 %1
}

define i32 @mul_by_neg7(i32 %a) nounwind {
; CHECK-LABEL: mul_by_neg7:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    save %sp, -96, %sp
; CHECK-NEXT:    mov %i0, %o0
; CHECK-NEXT:    call .umul
; CHECK-NEXT:    mov -7, %o1
; CHECK-NEXT:    ret
; CHECK-NEXT:    restore %g0, %o0, %o0
  %1 = mul i32 %a, -7
  ret i32 %1
}

define i32 @mul_by_neg9(i32 %a) nounwind {
; CHECK-LABEL: mul_by_neg9:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    save %sp, -96, %sp
; CHECK-NEXT:    mov %i0, %o0
; CHECK-NEXT:    call .umul
; CHECK-NEXT:    mov -9, %o1
; CHECK-NEXT:    ret
; CHECK-NEXT:    restore %g0, %o0, %o0
  %1 = mul i32 %a, -9
  ret i32 %1
}

define i32 @mul_by_65(i32 %a) nounwind {
; CHECK-LABEL: mul_by_65:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    save %sp, -96, %sp
; CHECK-NEXT:    mov %i0, %o0
; CHECK-NEXT:    call .umul
; CHECK-NEXT:    mov 65, %o1
; CHECK-NEXT:    ret
; CHECK-NEXT:    restore %g0, %o0, %o0
  %1 = mul i32 %a, 65
  ret i32 %1
}

define i32 @mul_by_384(i32 %a) nounwind {
; CHECK-LABEL: mul_by_384:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    save %sp, -96, %sp
; CHECK-NEXT:    mov %i0, %o0
; CHECK-NEXT:    call .umul
; CHECK-NEXT:    mov 384, %o1
; CHECK-NEXT:    ret
; CHECK-NEXT:    restore %g0, %o0, %o0
  %1 = mul i32 %a, 384
  ret i32 %1
}

; Non-constant multiply should still use the libcall.
define i32 @mul_variable(i32 %a, i32 %b) nounwind {
; CHECK-LABEL: mul_variable:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    save %sp, -96, %sp
; CHECK-NEXT:    mov %i1, %o1
; CHECK-NEXT:    call .umul
; CHECK-NEXT:    mov %i0, %o0
; CHECK-NEXT:    ret
; CHECK-NEXT:    restore %g0, %o0, %o0
  %1 = mul i32 %a, %b
  ret i32 %1
}
