; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=sparc | FileCheck %s -check-prefix=SPARC

; Materializing constants

define i32 @zero() nounwind {
; SPARC-LABEL: zero:
; SPARC:       ! %bb.0:
; SPARC-NEXT:    retl
; SPARC-NEXT:    mov %g0, %o0
ret i32 0
}

define i32 @pos_small() nounwind {
; SPARC-LABEL: pos_small:
; SPARC:       ! %bb.0:
; SPARC-NEXT:    retl
; SPARC-NEXT:    mov 2047, %o0
  ret i32 2047
}

define i32 @neg_small() nounwind {
; SPARC-LABEL: neg_small:
; SPARC:       ! %bb.0:
; SPARC-NEXT:    retl
; SPARC-NEXT:    mov -2047, %o0
  ret i32 -2047
}

define i32 @pos_i32() nounwind {
; SPARC-LABEL: pos_i32:
; SPARC:       ! %bb.0:
; SPARC-NEXT:    sethi 1695242, %o0
; SPARC-NEXT:    retl
; SPARC-NEXT:    or %o0, 751, %o0
  ret i32 1735928559
}

define i32 @neg_i32() nounwind {
; SPARC-LABEL: neg_i32:
; SPARC:       ! %bb.0:
; SPARC-NEXT:    sethi 3648367, %o0
; SPARC-NEXT:    retl
; SPARC-NEXT:    or %o0, 751, %o0
  ret i32 -559038737
}
