; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple sparc | FileCheck %s -check-prefixes=CHECK-32
; RUN: llc < %s -mtriple sparc64 | FileCheck %s -check-prefixes=CHECK-64

declare dso_local void @main()

define dso_local void @naked() naked "frame-pointer"="all" {
; CHECK-32-LABEL: naked:
; CHECK-32:         .cfi_startproc
; CHECK-32-NEXT:  ! %bb.0:
; CHECK-32-NEXT:    call main
; CHECK-32-NEXT:    nop
;
; CHECK-64-LABEL: naked:
; CHECK-64:         .cfi_startproc
; CHECK-64-NEXT:  ! %bb.0:
; CHECK-64-NEXT:    call main
; CHECK-64-NEXT:    nop
  call void @main()
  unreachable
}

define dso_local void @normal() "frame-pointer"="all" {
; CHECK-32-LABEL: normal:
; CHECK-32:         .cfi_startproc
; CHECK-32-NEXT:  ! %bb.0:
; CHECK-32-NEXT:    save %sp, -96, %sp
; CHECK-32-NEXT:    .cfi_def_cfa_register %fp
; CHECK-32-NEXT:    .cfi_window_save
; CHECK-32-NEXT:    .cfi_register %o7, %i7
; CHECK-32-NEXT:    call main
; CHECK-32-NEXT:    nop
;
; CHECK-64-LABEL: normal:
; CHECK-64:         .cfi_startproc
; CHECK-64-NEXT:  ! %bb.0:
; CHECK-64-NEXT:    save %sp, -176, %sp
; CHECK-64-NEXT:    .cfi_def_cfa_register %fp
; CHECK-64-NEXT:    .cfi_window_save
; CHECK-64-NEXT:    .cfi_register %o7, %i7
; CHECK-64-NEXT:    call main
; CHECK-64-NEXT:    nop
  call void @main()
  unreachable
}
