; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O3 < %s -relocation-model=pic -mtriple=sparc -mcpu=v9 | FileCheck --check-prefix=SPARC %s
; RUN: llc -O3 < %s -relocation-model=pic -mtriple=sparcv9 -mcpu=v9 | FileCheck --check-prefix=SPARC64 %s

;; Early Niagara processors should prefer conditional moves over branches
;; even when it's predictable.

define i32 @cinc(i32 %cond, i32 %num) #0 {
; SPARC-LABEL: cinc:
; SPARC:       ! %bb.0: ! %entry
; SPARC-NEXT:    add %o1, 1, %o2
; SPARC-NEXT:    cmp %o0, 0
; SPARC-NEXT:    move %icc, %o2, %o1
; SPARC-NEXT:    retl
; SPARC-NEXT:    mov %o1, %o0
;
; SPARC64-LABEL: cinc:
; SPARC64:       ! %bb.0: ! %entry
; SPARC64-NEXT:    add %o1, 1, %o2
; SPARC64-NEXT:    cmp %o0, 0
; SPARC64-NEXT:    move %icc, %o2, %o1
; SPARC64-NEXT:    retl
; SPARC64-NEXT:    mov %o1, %o0
entry:
  %add = add nsw i32 %num, 1
  %cmp = icmp eq i32 %cond, 0
  %exp = call i1 @llvm.expect.i1(i1 %cmp, i1 0)
  %ret = select i1 %exp, i32 %add, i32 %num
  ret i32 %ret
}
declare i1 @llvm.expect.i1(i1, i1)

attributes #0 = { nounwind "tune-cpu"="niagara" }
