; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: %if x86-registered-target %{ opt -S -passes=slp-vectorizer -mtriple=x86_64-grtev4-linux-gnu -o - < %s | FileCheck %s --check-prefixes=CHECK,X86 %}
; RUN: %if aarch64-registered-target %{ opt -S -passes=slp-vectorizer -mtriple=aarch64-unknown-linux-gnu -o - < %s | FileCheck %s --check-prefixes=CHECK,AARCH64 %}

define i32 @crash() {
; X86-LABEL: @crash(
; X86-NEXT:  label:
; X86-NEXT:    [[ADD:%.*]] = fadd <2 x double> zeroinitializer, zeroinitializer
; X86-NEXT:    [[TMP0:%.*]] = shufflevector <2 x double> [[ADD]], <2 x double> poison, <2 x i32> <i32 1, i32 0>
; X86-NEXT:    [[TMP1:%.*]] = shufflevector <2 x double> zeroinitializer, <2 x double> [[TMP0]], <2 x i32> <i32 2, i32 1>
; X86-NEXT:    [[TMP2:%.*]] = fmul <2 x double> [[TMP0]], zeroinitializer
; X86-NEXT:    [[TMP3:%.*]] = call double @llvm.vector.reduce.fadd.v2f64(double -0.000000e+00, <2 x double> [[TMP2]])
; X86-NEXT:    [[MUL1:%.*]] = fmul double [[TMP3]], 0.000000e+00
; X86-NEXT:    store double [[MUL1]], ptr null, align 16
; X86-NEXT:    ret i32 0
;
; AARCH64-LABEL: @crash(
; AARCH64-NEXT:  label:
; AARCH64-NEXT:    [[ADD:%.*]] = fadd <2 x double> zeroinitializer, zeroinitializer
; AARCH64-NEXT:    [[TMP0:%.*]] = shufflevector <2 x double> [[ADD]], <2 x double> poison, <2 x i32> <i32 1, i32 0>
; AARCH64-NEXT:    [[TMP1:%.*]] = shufflevector <2 x double> zeroinitializer, <2 x double> [[TMP0]], <2 x i32> <i32 2, i32 1>
; AARCH64-NEXT:    [[TMP2:%.*]] = fmul <2 x double> [[TMP0]], zeroinitializer
; AARCH64-NEXT:    [[TMP3:%.*]] = extractelement <2 x double> [[TMP2]], i32 0
; AARCH64-NEXT:    [[TMP4:%.*]] = extractelement <2 x double> [[TMP2]], i32 1
; AARCH64-NEXT:    [[ADD1:%.*]] = fadd double [[TMP3]], [[TMP4]]
; AARCH64-NEXT:    [[MUL1:%.*]] = fmul double [[ADD1]], 0.000000e+00
; AARCH64-NEXT:    store double [[MUL1]], ptr null, align 16
; AARCH64-NEXT:    ret i32 0
;
label:
  %0 = extractelement <2 x double> zeroinitializer, i64 1
  %1 = extractelement <2 x double> zeroinitializer, i64 0
  %add = fadd <2 x double> zeroinitializer, zeroinitializer
  %extract1 = extractelement <2 x double> %add, i64 1
  %2 = fmul double %extract1, %1
  %insert = insertelement <2 x double> zeroinitializer, double %extract1, i64 0
  %extract0 = extractelement <2 x double> %add, i64 0
  %mul = fmul double %extract0, %0
  %add1 = fadd double %2, %mul
  %mul1 = fmul double %add1, 0.000000e+00
  store double %mul1, ptr null, align 16
  ret i32 0
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
