; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: %if x86-registered-target %{ opt < %s -passes=slp-vectorizer -S -mtriple=x86_64--linux-gnu | FileCheck %s --check-prefixes=CHECK,X86 %}
; RUN: %if aarch64-registered-target %{ opt < %s -passes=slp-vectorizer -S -mtriple=aarch64-unknown-linux-gnu | FileCheck %s --check-prefixes=CHECK,AARCH64 %}

@a = common global [4 x double] zeroinitializer, align 8
@b = common global [4 x double] zeroinitializer, align 8

; [4], b[4];
; double foo() {
;  double sum =0;
;  sum = (a[0]+b[0]) + (a[1]+b[1]);
;  return sum;
; }

define double @return1() {
; X86-LABEL: @return1(
; X86-NEXT:  entry:
; X86-NEXT:    [[TMP0:%.*]] = load <2 x double>, ptr @a, align 8
; X86-NEXT:    [[TMP1:%.*]] = load <2 x double>, ptr @b, align 8
; X86-NEXT:    [[TMP2:%.*]] = fadd <2 x double> [[TMP0]], [[TMP1]]
; X86-NEXT:    [[TMP3:%.*]] = call double @llvm.vector.reduce.fadd.v2f64(double -0.000000e+00, <2 x double> [[TMP2]])
; X86-NEXT:    ret double [[TMP3]]
;
; AARCH64-LABEL: @return1(
; AARCH64-NEXT:  entry:
; AARCH64-NEXT:    [[TMP0:%.*]] = load <2 x double>, ptr @a, align 8
; AARCH64-NEXT:    [[TMP1:%.*]] = load <2 x double>, ptr @b, align 8
; AARCH64-NEXT:    [[TMP2:%.*]] = fadd <2 x double> [[TMP0]], [[TMP1]]
; AARCH64-NEXT:    [[TMP3:%.*]] = extractelement <2 x double> [[TMP2]], i32 0
; AARCH64-NEXT:    [[TMP4:%.*]] = extractelement <2 x double> [[TMP2]], i32 1
; AARCH64-NEXT:    [[ADD2:%.*]] = fadd double [[TMP3]], [[TMP4]]
; AARCH64-NEXT:    ret double [[ADD2]]
;
entry:
  %a0 = load double, ptr @a, align 8
  %b0 = load double, ptr @b, align 8
  %add0 = fadd double %a0, %b0
  %a1 = load double, ptr getelementptr inbounds ([4 x double], ptr @a, i32 0, i32 1), align 8
  %b1 = load double, ptr getelementptr inbounds ([4 x double], ptr @b, i32 0, i32 1), align 8
  %add1 = fadd double %a1, %b1
  %add2 = fadd double %add0, %add1
  ret double %add2
}

; double hadd(ptr x) {
;   return ((x[0] + x[2]) + (x[1] + x[3]));
; }

define double @return2(ptr nocapture readonly %x) {
; X86-LABEL: @return2(
; X86-NEXT:  entry:
; X86-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds double, ptr [[X:%.*]], i32 2
; X86-NEXT:    [[TMP0:%.*]] = load <2 x double>, ptr [[X]], align 4
; X86-NEXT:    [[TMP1:%.*]] = load <2 x double>, ptr [[ARRAYIDX1]], align 4
; X86-NEXT:    [[TMP2:%.*]] = fadd <2 x double> [[TMP0]], [[TMP1]]
; X86-NEXT:    [[TMP3:%.*]] = call double @llvm.vector.reduce.fadd.v2f64(double -0.000000e+00, <2 x double> [[TMP2]])
; X86-NEXT:    ret double [[TMP3]]
;
; AARCH64-LABEL: @return2(
; AARCH64-NEXT:  entry:
; AARCH64-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds double, ptr [[X:%.*]], i32 2
; AARCH64-NEXT:    [[TMP0:%.*]] = load <2 x double>, ptr [[X]], align 4
; AARCH64-NEXT:    [[TMP1:%.*]] = load <2 x double>, ptr [[ARRAYIDX1]], align 4
; AARCH64-NEXT:    [[TMP2:%.*]] = fadd <2 x double> [[TMP0]], [[TMP1]]
; AARCH64-NEXT:    [[TMP3:%.*]] = extractelement <2 x double> [[TMP2]], i32 0
; AARCH64-NEXT:    [[TMP4:%.*]] = extractelement <2 x double> [[TMP2]], i32 1
; AARCH64-NEXT:    [[ADD5:%.*]] = fadd double [[TMP3]], [[TMP4]]
; AARCH64-NEXT:    ret double [[ADD5]]
;
entry:
  %x0 = load double, ptr %x, align 4
  %arrayidx1 = getelementptr inbounds double, ptr %x, i32 2
  %x2 = load double, ptr %arrayidx1, align 4
  %add3 = fadd double %x0, %x2
  %arrayidx2 = getelementptr inbounds double, ptr %x, i32 1
  %x1 = load double, ptr %arrayidx2, align 4
  %arrayidx3 = getelementptr inbounds double, ptr %x, i32 3
  %x3 = load double, ptr %arrayidx3, align 4
  %add4 = fadd double %x1, %x3
  %add5 = fadd double %add3, %add4
  ret double %add5
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
