; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: %if x86-registered-target %{ opt -passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu -S < %s | FileCheck %s --check-prefix=X86 %}
; RUN: %if aarch64-registered-target %{ opt -passes=slp-vectorizer -mtriple=aarch64-unknown-linux-gnu -S < %s | FileCheck %s --check-prefix=AARCH64 %}

define void @test() {
; X86-LABEL: @test(
; X86-NEXT:  entry:
; X86-NEXT:    ret void
;
; AARCH64-LABEL: @test(
; AARCH64-NEXT:  entry:
; AARCH64-NEXT:    [[TMP0:%.*]] = extractelement <8 x half> zeroinitializer, i64 1
; AARCH64-NEXT:    [[TOBOOL:%.*]] = fcmp une half [[TMP0]], 0xH0000
; AARCH64-NEXT:    [[TMP1:%.*]] = extractelement <8 x half> zeroinitializer, i64 1
; AARCH64-NEXT:    [[TOBOOL3:%.*]] = fcmp une half [[TMP1]], 0xH0000
; AARCH64-NEXT:    ret void
;
entry:
  %0 = extractelement <8 x half> zeroinitializer, i64 1
  %tobool = fcmp une half %0, 0xH0000
  %1 = extractelement <8 x half> zeroinitializer, i64 1
  %tobool3 = fcmp une half %1, 0xH0000
  ret void
}
