; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer < %s | FileCheck %s

@phase = dso_local local_unnamed_addr global [8 x double] zeroinitializer, align 16
@sinval = dso_local local_unnamed_addr global [8 x double] zeroinitializer, align 16
@cosval = dso_local local_unnamed_addr global [8 x double] zeroinitializer, align 16

define i32 @test() {
; CHECK-LABEL: define i32 @test() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <8 x double>, ptr @phase, align 16
; CHECK-NEXT:    [[TMP1:%.*]] = call fast { <8 x double>, <8 x double> } @llvm.sincos.v8f64(<8 x double> [[TMP0]])
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x double>, <8 x double> } [[TMP1]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <8 x double> [[TMP5]], i32 0
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x double>, <8 x double> } [[TMP1]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <8 x double> [[TMP4]], i32 0
; CHECK-NEXT:    store double [[TMP2]], ptr @sinval, align 16
; CHECK-NEXT:    store double [[TMP3]], ptr @cosval, align 16
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <8 x double> [[TMP5]], i32 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <8 x double> [[TMP4]], i32 1
; CHECK-NEXT:    store double [[TMP6]], ptr getelementptr inbounds nuw (i8, ptr @sinval, i64 8), align 8
; CHECK-NEXT:    store double [[TMP7]], ptr getelementptr inbounds nuw (i8, ptr @cosval, i64 8), align 8
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <8 x double> [[TMP5]], i32 2
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <8 x double> [[TMP4]], i32 2
; CHECK-NEXT:    store double [[TMP10]], ptr getelementptr inbounds nuw (i8, ptr @sinval, i64 16), align 16
; CHECK-NEXT:    store double [[TMP11]], ptr getelementptr inbounds nuw (i8, ptr @cosval, i64 16), align 16
; CHECK-NEXT:    [[TMP14:%.*]] = extractelement <8 x double> [[TMP5]], i32 3
; CHECK-NEXT:    [[TMP15:%.*]] = extractelement <8 x double> [[TMP4]], i32 3
; CHECK-NEXT:    store double [[TMP14]], ptr getelementptr inbounds nuw (i8, ptr @sinval, i64 24), align 8
; CHECK-NEXT:    store double [[TMP15]], ptr getelementptr inbounds nuw (i8, ptr @cosval, i64 24), align 8
; CHECK-NEXT:    [[TMP18:%.*]] = extractelement <8 x double> [[TMP5]], i32 4
; CHECK-NEXT:    [[TMP19:%.*]] = extractelement <8 x double> [[TMP4]], i32 4
; CHECK-NEXT:    store double [[TMP18]], ptr getelementptr inbounds nuw (i8, ptr @sinval, i64 32), align 16
; CHECK-NEXT:    store double [[TMP19]], ptr getelementptr inbounds nuw (i8, ptr @cosval, i64 32), align 16
; CHECK-NEXT:    [[TMP22:%.*]] = extractelement <8 x double> [[TMP5]], i32 5
; CHECK-NEXT:    [[TMP23:%.*]] = extractelement <8 x double> [[TMP4]], i32 5
; CHECK-NEXT:    store double [[TMP22]], ptr getelementptr inbounds nuw (i8, ptr @sinval, i64 40), align 8
; CHECK-NEXT:    store double [[TMP23]], ptr getelementptr inbounds nuw (i8, ptr @cosval, i64 40), align 8
; CHECK-NEXT:    [[TMP26:%.*]] = extractelement <8 x double> [[TMP5]], i32 6
; CHECK-NEXT:    [[TMP27:%.*]] = extractelement <8 x double> [[TMP4]], i32 6
; CHECK-NEXT:    store double [[TMP26]], ptr getelementptr inbounds nuw (i8, ptr @sinval, i64 48), align 16
; CHECK-NEXT:    store double [[TMP27]], ptr getelementptr inbounds nuw (i8, ptr @cosval, i64 48), align 16
; CHECK-NEXT:    [[TMP30:%.*]] = extractelement <8 x double> [[TMP5]], i32 7
; CHECK-NEXT:    [[TMP31:%.*]] = extractelement <8 x double> [[TMP4]], i32 7
; CHECK-NEXT:    store double [[TMP30]], ptr getelementptr inbounds nuw (i8, ptr @sinval, i64 56), align 8
; CHECK-NEXT:    store double [[TMP31]], ptr getelementptr inbounds nuw (i8, ptr @cosval, i64 56), align 8
; CHECK-NEXT:    ret i32 0
;
entry:
  %0 = load double, ptr @phase, align 16
  %1 = tail call fast { double, double } @llvm.sincos.f64(double %0)
  %2 = extractvalue { double, double } %1, 0
  %3 = extractvalue { double, double } %1, 1
  store double %2, ptr @sinval, align 16
  store double %3, ptr @cosval, align 16
  %4 = load double, ptr getelementptr inbounds nuw (i8, ptr @phase, i64 8), align 8
  %5 = tail call fast { double, double } @llvm.sincos.f64(double %4)
  %6 = extractvalue { double, double } %5, 0
  %7 = extractvalue { double, double } %5, 1
  store double %6, ptr getelementptr inbounds nuw (i8, ptr @sinval, i64 8), align 8
  store double %7, ptr getelementptr inbounds nuw (i8, ptr @cosval, i64 8), align 8
  %8 = load double, ptr getelementptr inbounds nuw (i8, ptr @phase, i64 16), align 16
  %9 = tail call fast { double, double } @llvm.sincos.f64(double %8)
  %10 = extractvalue { double, double } %9, 0
  %11 = extractvalue { double, double } %9, 1
  store double %10, ptr getelementptr inbounds nuw (i8, ptr @sinval, i64 16), align 16
  store double %11, ptr getelementptr inbounds nuw (i8, ptr @cosval, i64 16), align 16
  %12 = load double, ptr getelementptr inbounds nuw (i8, ptr @phase, i64 24), align 8
  %13 = tail call fast { double, double } @llvm.sincos.f64(double %12)
  %14 = extractvalue { double, double } %13, 0
  %15 = extractvalue { double, double } %13, 1
  store double %14, ptr getelementptr inbounds nuw (i8, ptr @sinval, i64 24), align 8
  store double %15, ptr getelementptr inbounds nuw (i8, ptr @cosval, i64 24), align 8
  %16 = load double, ptr getelementptr inbounds nuw (i8, ptr @phase, i64 32), align 16
  %17 = tail call fast { double, double } @llvm.sincos.f64(double %16)
  %18 = extractvalue { double, double } %17, 0
  %19 = extractvalue { double, double } %17, 1
  store double %18, ptr getelementptr inbounds nuw (i8, ptr @sinval, i64 32), align 16
  store double %19, ptr getelementptr inbounds nuw (i8, ptr @cosval, i64 32), align 16
  %20 = load double, ptr getelementptr inbounds nuw (i8, ptr @phase, i64 40), align 8
  %21 = tail call fast { double, double } @llvm.sincos.f64(double %20)
  %22 = extractvalue { double, double } %21, 0
  %23 = extractvalue { double, double } %21, 1
  store double %22, ptr getelementptr inbounds nuw (i8, ptr @sinval, i64 40), align 8
  store double %23, ptr getelementptr inbounds nuw (i8, ptr @cosval, i64 40), align 8
  %24 = load double, ptr getelementptr inbounds nuw (i8, ptr @phase, i64 48), align 16
  %25 = tail call fast { double, double } @llvm.sincos.f64(double %24)
  %26 = extractvalue { double, double } %25, 0
  %27 = extractvalue { double, double } %25, 1
  store double %26, ptr getelementptr inbounds nuw (i8, ptr @sinval, i64 48), align 16
  store double %27, ptr getelementptr inbounds nuw (i8, ptr @cosval, i64 48), align 16
  %28 = load double, ptr getelementptr inbounds nuw (i8, ptr @phase, i64 56), align 8
  %29 = tail call fast { double, double } @llvm.sincos.f64(double %28)
  %30 = extractvalue { double, double } %29, 0
  %31 = extractvalue { double, double } %29, 1
  store double %30, ptr getelementptr inbounds nuw (i8, ptr @sinval, i64 56), align 8
  store double %31, ptr getelementptr inbounds nuw (i8, ptr @cosval, i64 56), align 8
  ret i32 0
}

declare { double, double } @llvm.sincos.f64(double)

