; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -S --passes=slp-vectorizer < %s | FileCheck %s

; Test where the outermost loop doesn't contain exactly one latch;
; ScalarEvolution shouldn't crash in this case.

define void @f(ptr %a0) {
; CHECK-LABEL: define void @f(
; CHECK-SAME: ptr [[A0:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[B1:.*]]
; CHECK:       [[B1]]:
; CHECK-NEXT:    [[PHI1:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[INC:%.*]], %[[B3:.*]] ], [ [[INC]], %[[B4:.*]] ]
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq ptr [[PHI1]], null
; CHECK-NEXT:    br i1 [[CMP1]], label %[[RET:.*]], label %[[B2:.*]]
; CHECK:       [[B2]]:
; CHECK-NEXT:    [[INC]] = getelementptr i8, ptr [[PHI1]], i64 -32
; CHECK-NEXT:    br label %[[B3]]
; CHECK:       [[B3]]:
; CHECK-NEXT:    [[PHI2:%.*]] = phi ptr [ [[A0]], %[[B2]] ], [ [[INC2:%.*]], %[[B5:.*]] ]
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq ptr [[PHI2]], null
; CHECK-NEXT:    br i1 [[CMP2]], label %[[B1]], label %[[B4]]
; CHECK:       [[B4]]:
; CHECK-NEXT:    [[LD1:%.*]] = load i8, ptr [[PHI2]], align 1
; CHECK-NEXT:    [[LD2:%.*]] = load i8, ptr null, align 1
; CHECK-NEXT:    [[CMP3:%.*]] = icmp slt i8 [[LD1]], [[LD2]]
; CHECK-NEXT:    br i1 false, label %[[B1]], label %[[B5]]
; CHECK:       [[B5]]:
; CHECK-NEXT:    [[INC2]] = getelementptr i8, ptr [[PHI2]], i64 1
; CHECK-NEXT:    br label %[[B3]]
; CHECK:       [[RET]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %b1
b1:
  %phi1 = phi ptr [ null, %entry ], [ %inc, %b3 ], [ %inc, %b4 ]
  %cmp1 = icmp eq ptr %phi1, null
  br i1 %cmp1, label %ret, label %b2
b2:
  %inc = getelementptr i8, ptr %phi1, i64 -32
  br label %b3
b3:
  %phi2 = phi ptr [ %a0, %b2 ], [ %inc2, %b5 ]
  %cmp2 = icmp eq ptr %phi2, null
  br i1 %cmp2, label %b1, label %b4
b4:
  %ld1 = load i8, ptr %phi2, align 1
  %ld2 = load i8, ptr null, align 1
  %cmp3 = icmp slt i8 %ld1, %ld2
  br i1 false, label %b1, label %b5
b5:
  %inc2 = getelementptr i8, ptr %phi2, i64 1
  br label %b3
ret:
  ret void
}
