; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mcpu=gfx1250 -mtriple=amdgcn-amd-amdhsa -slp-look-through-intrinsics=true -o - %s | FileCheck %s --check-prefix=ENABLED
; RUN: opt -passes=slp-vectorizer -S -mcpu=gfx1250 -mtriple=amdgcn-amd-amdhsa -slp-look-through-intrinsics=false -o - %s | FileCheck %s --check-prefix=DISABLED
target triple = "amdgcn-amd-amdhsa"

define amdgpu_kernel void @test_with_wmma( ptr addrspace(1) %input, ptr addrspace(1) %output, float %scaled_max, <16 x i32> %A, <16 x i32> %B, i32 %scale_idx) {
; ENABLED-LABEL: define amdgpu_kernel void @test_with_wmma(
; ENABLED-SAME: ptr addrspace(1) [[INPUT:%.*]], ptr addrspace(1) [[OUTPUT:%.*]], float [[SCALED_MAX:%.*]], <16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[SCALE_IDX:%.*]]) #[[ATTR0:[0-9]+]] {
; ENABLED-NEXT:  [[ENTRY:.*:]]
; ENABLED-NEXT:    [[TMP0:%.*]] = load <2 x float>, ptr addrspace(1) [[INPUT]], align 4
; ENABLED-NEXT:    [[TMP1:%.*]] = fmul contract <2 x float> [[TMP0]], splat (float 0x3FC0527DC0000000)
; ENABLED-NEXT:    [[TMP2:%.*]] = insertelement <2 x float> poison, float [[SCALED_MAX]], i32 0
; ENABLED-NEXT:    [[TMP3:%.*]] = shufflevector <2 x float> [[TMP2]], <2 x float> poison, <2 x i32> zeroinitializer
; ENABLED-NEXT:    [[TMP4:%.*]] = fsub contract <2 x float> [[TMP1]], [[TMP3]]
; ENABLED-NEXT:    [[TMP5:%.*]] = extractelement <2 x float> [[TMP4]], i32 0
; ENABLED-NEXT:    [[EXP0:%.*]] = tail call float @llvm.amdgcn.exp2.f32(float [[TMP5]])
; ENABLED-NEXT:    [[TMP9:%.*]] = extractelement <2 x float> [[TMP4]], i32 1
; ENABLED-NEXT:    [[EXP1:%.*]] = tail call float @llvm.amdgcn.exp2.f32(float [[TMP9]])
; ENABLED-NEXT:    [[TMP10:%.*]] = insertelement <2 x float> poison, float [[EXP0]], i32 0
; ENABLED-NEXT:    [[TMP8:%.*]] = insertelement <2 x float> [[TMP10]], float [[EXP1]], i32 1
; ENABLED-NEXT:    [[VEC_I32:%.*]] = bitcast <2 x float> [[TMP8]] to <2 x i32>
; ENABLED-NEXT:    [[SCALE0:%.*]] = extractelement <2 x i32> [[VEC_I32]], i64 0
; ENABLED-NEXT:    [[SCALE1:%.*]] = extractelement <2 x i32> [[VEC_I32]], i64 1
; ENABLED-NEXT:    [[WMMA0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.scale.f32.16x16x128.f8f6f4.v8f32.v16i32.v16i32(i32 0, <16 x i32> [[A]], i32 0, <16 x i32> [[B]], i16 0, <8 x float> zeroinitializer, i32 0, i32 0, i32 [[SCALE0]], i32 0, i32 0, i32 [[SCALE_IDX]], i1 false, i1 false)
; ENABLED-NEXT:    [[WMMA1:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.scale.f32.16x16x128.f8f6f4.v8f32.v16i32.v16i32(i32 0, <16 x i32> [[A]], i32 0, <16 x i32> [[B]], i16 0, <8 x float> [[WMMA0]], i32 0, i32 0, i32 [[SCALE1]], i32 0, i32 0, i32 [[SCALE_IDX]], i1 false, i1 false)
; ENABLED-NEXT:    store <8 x float> [[WMMA1]], ptr addrspace(1) [[OUTPUT]], align 32
; ENABLED-NEXT:    ret void
;
; DISABLED-LABEL: define amdgpu_kernel void @test_with_wmma(
; DISABLED-SAME: ptr addrspace(1) [[INPUT:%.*]], ptr addrspace(1) [[OUTPUT:%.*]], float [[SCALED_MAX:%.*]], <16 x i32> [[A:%.*]], <16 x i32> [[B:%.*]], i32 [[SCALE_IDX:%.*]]) #[[ATTR0:[0-9]+]] {
; DISABLED-NEXT:  [[ENTRY:.*:]]
; DISABLED-NEXT:    [[IN0:%.*]] = load float, ptr addrspace(1) [[INPUT]], align 4
; DISABLED-NEXT:    [[PTR1:%.*]] = getelementptr float, ptr addrspace(1) [[INPUT]], i64 1
; DISABLED-NEXT:    [[IN1:%.*]] = load float, ptr addrspace(1) [[PTR1]], align 4
; DISABLED-NEXT:    [[MUL0:%.*]] = fmul contract float [[IN0]], 0x3FC0527DC0000000
; DISABLED-NEXT:    [[MUL1:%.*]] = fmul contract float [[IN1]], 0x3FC0527DC0000000
; DISABLED-NEXT:    [[SUB0:%.*]] = fsub contract float [[MUL0]], [[SCALED_MAX]]
; DISABLED-NEXT:    [[SUB1:%.*]] = fsub contract float [[MUL1]], [[SCALED_MAX]]
; DISABLED-NEXT:    [[EXP0:%.*]] = tail call float @llvm.amdgcn.exp2.f32(float [[SUB0]])
; DISABLED-NEXT:    [[EXP1:%.*]] = tail call float @llvm.amdgcn.exp2.f32(float [[SUB1]])
; DISABLED-NEXT:    [[VEC0:%.*]] = insertelement <2 x float> poison, float [[EXP0]], i64 0
; DISABLED-NEXT:    [[VEC1:%.*]] = insertelement <2 x float> [[VEC0]], float [[EXP1]], i64 1
; DISABLED-NEXT:    [[VEC_I32:%.*]] = bitcast <2 x float> [[VEC1]] to <2 x i32>
; DISABLED-NEXT:    [[SCALE0:%.*]] = extractelement <2 x i32> [[VEC_I32]], i64 0
; DISABLED-NEXT:    [[SCALE1:%.*]] = extractelement <2 x i32> [[VEC_I32]], i64 1
; DISABLED-NEXT:    [[WMMA0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.scale.f32.16x16x128.f8f6f4.v8f32.v16i32.v16i32(i32 0, <16 x i32> [[A]], i32 0, <16 x i32> [[B]], i16 0, <8 x float> zeroinitializer, i32 0, i32 0, i32 [[SCALE0]], i32 0, i32 0, i32 [[SCALE_IDX]], i1 false, i1 false)
; DISABLED-NEXT:    [[WMMA1:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.scale.f32.16x16x128.f8f6f4.v8f32.v16i32.v16i32(i32 0, <16 x i32> [[A]], i32 0, <16 x i32> [[B]], i16 0, <8 x float> [[WMMA0]], i32 0, i32 0, i32 [[SCALE1]], i32 0, i32 0, i32 [[SCALE_IDX]], i1 false, i1 false)
; DISABLED-NEXT:    store <8 x float> [[WMMA1]], ptr addrspace(1) [[OUTPUT]], align 32
; DISABLED-NEXT:    ret void
;
entry:

  %in0 = load float, ptr addrspace(1) %input, align 4
  %ptr1 = getelementptr float, ptr addrspace(1) %input, i64 1
  %in1 = load float, ptr addrspace(1) %ptr1, align 4

  %mul0 = fmul contract float %in0, 0x3FC0527DC0000000
  %mul1 = fmul contract float %in1, 0x3FC0527DC0000000

  %sub0 = fsub contract float %mul0, %scaled_max
  %sub1 = fsub contract float %mul1, %scaled_max

  %exp0 = tail call float @llvm.amdgcn.exp2.f32(float %sub0)
  %exp1 = tail call float @llvm.amdgcn.exp2.f32(float %sub1)

  %vec0 = insertelement <2 x float> poison, float %exp0, i64 0
  %vec1 = insertelement <2 x float> %vec0, float %exp1, i64 1

  %vec_i32 = bitcast <2 x float> %vec1 to <2 x i32>

  %scale0 = extractelement <2 x i32> %vec_i32, i64 0
  %scale1 = extractelement <2 x i32> %vec_i32, i64 1

  %wmma0 = tail call <8 x float> @llvm.amdgcn.wmma.scale.f32.16x16x128.f8f6f4.v8f32.v16i32.v16i32(
  i32 0, <16 x i32> %A, i32 0, <16 x i32> %B, i16 0, <8 x float> zeroinitializer,
  i32 0, i32 0, i32 %scale0, i32 0, i32 0, i32 %scale_idx, i1 false, i1 false)

  %wmma1 = tail call <8 x float> @llvm.amdgcn.wmma.scale.f32.16x16x128.f8f6f4.v8f32.v16i32.v16i32(
  i32 0, <16 x i32> %A, i32 0, <16 x i32> %B, i16 0, <8 x float> %wmma0,
  i32 0, i32 0, i32 %scale1, i32 0, i32 0, i32 %scale_idx, i1 false, i1 false)

  store <8 x float> %wmma1, ptr addrspace(1) %output, align 32
  ret void
}

define amdgpu_kernel void @test_amdgcn_exp_log(ptr addrspace(1) %input, ptr addrspace(1) %scales, ptr addrspace(1) %output) {
; ENABLED-LABEL: define amdgpu_kernel void @test_amdgcn_exp_log(
; ENABLED-SAME: ptr addrspace(1) [[INPUT:%.*]], ptr addrspace(1) [[SCALES:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; ENABLED-NEXT:  [[ENTRY:.*:]]
; ENABLED-NEXT:    [[TMP0:%.*]] = load <2 x float>, ptr addrspace(1) [[INPUT]], align 4
; ENABLED-NEXT:    [[TMP1:%.*]] = load <2 x float>, ptr addrspace(1) [[SCALES]], align 4
; ENABLED-NEXT:    [[TMP2:%.*]] = fmul contract <2 x float> [[TMP0]], splat (float 0x3FC0527DC0000000)
; ENABLED-NEXT:    [[TMP3:%.*]] = fsub contract <2 x float> [[TMP2]], [[TMP1]]
; ENABLED-NEXT:    [[TMP4:%.*]] = extractelement <2 x float> [[TMP3]], i32 0
; ENABLED-NEXT:    [[TMP5:%.*]] = tail call float @llvm.amdgcn.exp2.f32(float [[TMP4]])
; ENABLED-NEXT:    [[TMP6:%.*]] = extractelement <2 x float> [[TMP3]], i32 1
; ENABLED-NEXT:    [[TMP7:%.*]] = tail call float @llvm.amdgcn.exp2.f32(float [[TMP6]])
; ENABLED-NEXT:    [[TMP8:%.*]] = tail call float @llvm.amdgcn.log.f32(float [[TMP5]])
; ENABLED-NEXT:    [[TMP9:%.*]] = tail call float @llvm.amdgcn.log.f32(float [[TMP7]])
; ENABLED-NEXT:    [[TMP10:%.*]] = insertelement <2 x float> poison, float [[TMP8]], i32 0
; ENABLED-NEXT:    [[TMP11:%.*]] = insertelement <2 x float> [[TMP10]], float [[TMP9]], i32 1
; ENABLED-NEXT:    [[TMP12:%.*]] = extractelement <2 x float> [[TMP11]], i32 0
; ENABLED-NEXT:    [[TMP13:%.*]] = extractelement <2 x float> [[TMP11]], i32 1
; ENABLED-NEXT:    [[SUM:%.*]] = fadd fast float [[TMP12]], [[TMP13]]
; ENABLED-NEXT:    store float [[SUM]], ptr addrspace(1) [[OUTPUT]], align 4
; ENABLED-NEXT:    ret void
;
; DISABLED-LABEL: define amdgpu_kernel void @test_amdgcn_exp_log(
; DISABLED-SAME: ptr addrspace(1) [[INPUT:%.*]], ptr addrspace(1) [[SCALES:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; DISABLED-NEXT:  [[ENTRY:.*:]]
; DISABLED-NEXT:    [[IN0:%.*]] = load float, ptr addrspace(1) [[INPUT]], align 4
; DISABLED-NEXT:    [[PTR1:%.*]] = getelementptr float, ptr addrspace(1) [[INPUT]], i64 1
; DISABLED-NEXT:    [[IN1:%.*]] = load float, ptr addrspace(1) [[PTR1]], align 4
; DISABLED-NEXT:    [[SCALE0:%.*]] = load float, ptr addrspace(1) [[SCALES]], align 4
; DISABLED-NEXT:    [[SPTR1:%.*]] = getelementptr float, ptr addrspace(1) [[SCALES]], i64 1
; DISABLED-NEXT:    [[SCALE1:%.*]] = load float, ptr addrspace(1) [[SPTR1]], align 4
; DISABLED-NEXT:    [[MUL0:%.*]] = fmul contract float [[IN0]], 0x3FC0527DC0000000
; DISABLED-NEXT:    [[MUL1:%.*]] = fmul contract float [[IN1]], 0x3FC0527DC0000000
; DISABLED-NEXT:    [[SUB0:%.*]] = fsub contract float [[MUL0]], [[SCALE0]]
; DISABLED-NEXT:    [[SUB1:%.*]] = fsub contract float [[MUL1]], [[SCALE1]]
; DISABLED-NEXT:    [[EXP0:%.*]] = tail call float @llvm.amdgcn.exp2.f32(float [[SUB0]])
; DISABLED-NEXT:    [[LOG0:%.*]] = tail call float @llvm.amdgcn.log.f32(float [[EXP0]])
; DISABLED-NEXT:    [[EXP1:%.*]] = tail call float @llvm.amdgcn.exp2.f32(float [[SUB1]])
; DISABLED-NEXT:    [[LOG1:%.*]] = tail call float @llvm.amdgcn.log.f32(float [[EXP1]])
; DISABLED-NEXT:    [[SUM:%.*]] = fadd fast float [[LOG0]], [[LOG1]]
; DISABLED-NEXT:    store float [[SUM]], ptr addrspace(1) [[OUTPUT]], align 4
; DISABLED-NEXT:    ret void
;
entry:
  %in0 = load float, ptr addrspace(1) %input, align 4
  %ptr1 = getelementptr float, ptr addrspace(1) %input, i64 1
  %in1 = load float, ptr addrspace(1) %ptr1, align 4
  %scale0 = load float, ptr addrspace(1) %scales, align 4
  %sptr1 = getelementptr float, ptr addrspace(1) %scales, i64 1
  %scale1 = load float, ptr addrspace(1) %sptr1, align 4
  %mul0 = fmul contract float %in0, 0x3FC0527DC0000000
  %mul1 = fmul contract float %in1, 0x3FC0527DC0000000
  %sub0 = fsub contract float %mul0, %scale0
  %sub1 = fsub contract float %mul1, %scale1
  %exp0 = tail call float @llvm.amdgcn.exp2.f32(float %sub0)
  %log0 = tail call float @llvm.amdgcn.log.f32(float %exp0)
  %exp1 = tail call float @llvm.amdgcn.exp2.f32(float %sub1)
  %log1 = tail call float @llvm.amdgcn.log.f32(float %exp1)
  %sum = fadd fast float %log0, %log1
  store float %sum, ptr addrspace(1) %output, align 4
  ret void
}

define amdgpu_kernel void @test_amdgcn_exp_f16(ptr addrspace(1) %input, ptr addrspace(1) %scales, ptr addrspace(1) %output) {
; ENABLED-LABEL: define amdgpu_kernel void @test_amdgcn_exp_f16(
; ENABLED-SAME: ptr addrspace(1) [[INPUT:%.*]], ptr addrspace(1) [[SCALES:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; ENABLED-NEXT:  [[ENTRY:.*:]]
; ENABLED-NEXT:    [[TMP0:%.*]] = load <2 x half>, ptr addrspace(1) [[INPUT]], align 2
; ENABLED-NEXT:    [[TMP1:%.*]] = load <2 x half>, ptr addrspace(1) [[SCALES]], align 2
; ENABLED-NEXT:    [[TMP2:%.*]] = fmul contract <2 x half> [[TMP0]], splat (half 0xH3E14)
; ENABLED-NEXT:    [[TMP3:%.*]] = fsub contract <2 x half> [[TMP2]], [[TMP1]]
; ENABLED-NEXT:    [[TMP4:%.*]] = extractelement <2 x half> [[TMP3]], i32 0
; ENABLED-NEXT:    [[TMP5:%.*]] = tail call half @llvm.amdgcn.exp2.f16(half [[TMP4]])
; ENABLED-NEXT:    [[TMP6:%.*]] = extractelement <2 x half> [[TMP3]], i32 1
; ENABLED-NEXT:    [[TMP7:%.*]] = tail call half @llvm.amdgcn.exp2.f16(half [[TMP6]])
; ENABLED-NEXT:    [[TMP8:%.*]] = insertelement <2 x half> poison, half [[TMP5]], i32 0
; ENABLED-NEXT:    [[TMP9:%.*]] = insertelement <2 x half> [[TMP8]], half [[TMP7]], i32 1
; ENABLED-NEXT:    [[TMP10:%.*]] = call fast half @llvm.vector.reduce.fadd.v2f16(half 0xH0000, <2 x half> [[TMP9]])
; ENABLED-NEXT:    store half [[TMP10]], ptr addrspace(1) [[OUTPUT]], align 2
; ENABLED-NEXT:    ret void
;
; DISABLED-LABEL: define amdgpu_kernel void @test_amdgcn_exp_f16(
; DISABLED-SAME: ptr addrspace(1) [[INPUT:%.*]], ptr addrspace(1) [[SCALES:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; DISABLED-NEXT:  [[ENTRY:.*:]]
; DISABLED-NEXT:    [[IN0:%.*]] = load half, ptr addrspace(1) [[INPUT]], align 2
; DISABLED-NEXT:    [[PTR1:%.*]] = getelementptr half, ptr addrspace(1) [[INPUT]], i64 1
; DISABLED-NEXT:    [[IN1:%.*]] = load half, ptr addrspace(1) [[PTR1]], align 2
; DISABLED-NEXT:    [[SCALE0:%.*]] = load half, ptr addrspace(1) [[SCALES]], align 2
; DISABLED-NEXT:    [[SPTR1:%.*]] = getelementptr half, ptr addrspace(1) [[SCALES]], i64 1
; DISABLED-NEXT:    [[SCALE1:%.*]] = load half, ptr addrspace(1) [[SPTR1]], align 2
; DISABLED-NEXT:    [[MUL0:%.*]] = fmul contract half [[IN0]], 0xH3E14
; DISABLED-NEXT:    [[MUL1:%.*]] = fmul contract half [[IN1]], 0xH3E14
; DISABLED-NEXT:    [[SUB0:%.*]] = fsub contract half [[MUL0]], [[SCALE0]]
; DISABLED-NEXT:    [[SUB1:%.*]] = fsub contract half [[MUL1]], [[SCALE1]]
; DISABLED-NEXT:    [[EXP0:%.*]] = tail call half @llvm.amdgcn.exp2.f16(half [[SUB0]])
; DISABLED-NEXT:    [[EXP1:%.*]] = tail call half @llvm.amdgcn.exp2.f16(half [[SUB1]])
; DISABLED-NEXT:    [[SUM:%.*]] = fadd fast half [[EXP0]], [[EXP1]]
; DISABLED-NEXT:    store half [[SUM]], ptr addrspace(1) [[OUTPUT]], align 2
; DISABLED-NEXT:    ret void
;
entry:
  %in0 = load half, ptr addrspace(1) %input, align 2
  %ptr1 = getelementptr half, ptr addrspace(1) %input, i64 1
  %in1 = load half, ptr addrspace(1) %ptr1, align 2
  %scale0 = load half, ptr addrspace(1) %scales, align 2
  %sptr1 = getelementptr half, ptr addrspace(1) %scales, i64 1
  %scale1 = load half, ptr addrspace(1) %sptr1, align 2
  %mul0 = fmul contract half %in0, 0xH3E14
  %mul1 = fmul contract half %in1, 0xH3E14
  %sub0 = fsub contract half %mul0, %scale0
  %sub1 = fsub contract half %mul1, %scale1
  %exp0 = tail call half @llvm.amdgcn.exp2.f16(half %sub0)
  %exp1 = tail call half @llvm.amdgcn.exp2.f16(half %sub1)
  %sum = fadd fast half %exp0, %exp1
  store half %sum, ptr addrspace(1) %output, align 2
  ret void
}

define amdgpu_kernel void @kernel_f16(ptr addrspace(1) %input, ptr addrspace(1) %scales, ptr addrspace(1) %output) {
; ENABLED-LABEL: define amdgpu_kernel void @kernel_f16(
; ENABLED-SAME: ptr addrspace(1) [[INPUT:%.*]], ptr addrspace(1) [[SCALES:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; ENABLED-NEXT:  [[ENTRY:.*:]]
; ENABLED-NEXT:    [[TMP0:%.*]] = load <2 x half>, ptr addrspace(1) [[INPUT]], align 2
; ENABLED-NEXT:    [[TMP1:%.*]] = load <2 x half>, ptr addrspace(1) [[SCALES]], align 2
; ENABLED-NEXT:    [[TMP2:%.*]] = fmul contract <2 x half> [[TMP0]], splat (half 0xH3E14)
; ENABLED-NEXT:    [[TMP3:%.*]] = fsub contract <2 x half> [[TMP2]], [[TMP1]]
; ENABLED-NEXT:    [[SUB0:%.*]] = extractelement <2 x half> [[TMP3]], i32 0
; ENABLED-NEXT:    [[EXP0:%.*]] = tail call half @llvm.amdgcn.exp2.f16(half [[SUB0]])
; ENABLED-NEXT:    [[SUB1:%.*]] = extractelement <2 x half> [[TMP3]], i32 1
; ENABLED-NEXT:    [[EXP1:%.*]] = tail call half @llvm.amdgcn.exp2.f16(half [[SUB1]])
; ENABLED-NEXT:    [[LOG0:%.*]] = tail call half @llvm.amdgcn.log.f16(half [[EXP0]])
; ENABLED-NEXT:    [[LOG1:%.*]] = tail call half @llvm.amdgcn.log.f16(half [[EXP1]])
; ENABLED-NEXT:    [[TMP10:%.*]] = insertelement <2 x half> poison, half [[LOG0]], i32 0
; ENABLED-NEXT:    [[TMP11:%.*]] = insertelement <2 x half> [[TMP10]], half [[LOG1]], i32 1
; ENABLED-NEXT:    [[SUM:%.*]] = call fast half @llvm.vector.reduce.fadd.v2f16(half 0xH0000, <2 x half> [[TMP11]])
; ENABLED-NEXT:    store half [[SUM]], ptr addrspace(1) [[OUTPUT]], align 2
; ENABLED-NEXT:    ret void
;
; DISABLED-LABEL: define amdgpu_kernel void @kernel_f16(
; DISABLED-SAME: ptr addrspace(1) [[INPUT:%.*]], ptr addrspace(1) [[SCALES:%.*]], ptr addrspace(1) [[OUTPUT:%.*]]) #[[ATTR0]] {
; DISABLED-NEXT:  [[ENTRY:.*:]]
; DISABLED-NEXT:    [[IN0:%.*]] = load half, ptr addrspace(1) [[INPUT]], align 2
; DISABLED-NEXT:    [[PTR1:%.*]] = getelementptr half, ptr addrspace(1) [[INPUT]], i64 1
; DISABLED-NEXT:    [[IN1:%.*]] = load half, ptr addrspace(1) [[PTR1]], align 2
; DISABLED-NEXT:    [[SCALE0:%.*]] = load half, ptr addrspace(1) [[SCALES]], align 2
; DISABLED-NEXT:    [[SPTR1:%.*]] = getelementptr half, ptr addrspace(1) [[SCALES]], i64 1
; DISABLED-NEXT:    [[SCALE1:%.*]] = load half, ptr addrspace(1) [[SPTR1]], align 2
; DISABLED-NEXT:    [[MUL0:%.*]] = fmul contract half [[IN0]], 0xH3E14
; DISABLED-NEXT:    [[MUL1:%.*]] = fmul contract half [[IN1]], 0xH3E14
; DISABLED-NEXT:    [[SUB0:%.*]] = fsub contract half [[MUL0]], [[SCALE0]]
; DISABLED-NEXT:    [[SUB1:%.*]] = fsub contract half [[MUL1]], [[SCALE1]]
; DISABLED-NEXT:    [[EXP0:%.*]] = tail call half @llvm.amdgcn.exp2.f16(half [[SUB0]])
; DISABLED-NEXT:    [[EXP1:%.*]] = tail call half @llvm.amdgcn.exp2.f16(half [[SUB1]])
; DISABLED-NEXT:    [[LOG0:%.*]] = tail call half @llvm.amdgcn.log.f16(half [[EXP0]])
; DISABLED-NEXT:    [[LOG1:%.*]] = tail call half @llvm.amdgcn.log.f16(half [[EXP1]])
; DISABLED-NEXT:    [[SUM:%.*]] = fadd fast half [[LOG0]], [[LOG1]]
; DISABLED-NEXT:    store half [[SUM]], ptr addrspace(1) [[OUTPUT]], align 2
; DISABLED-NEXT:    ret void
;
entry:
  %in0 = load half, ptr addrspace(1) %input, align 2
  %ptr1 = getelementptr half, ptr addrspace(1) %input, i64 1
  %in1 = load half, ptr addrspace(1) %ptr1, align 2
  %scale0 = load half, ptr addrspace(1) %scales, align 2
  %sptr1 = getelementptr half, ptr addrspace(1) %scales, i64 1
  %scale1 = load half, ptr addrspace(1) %sptr1, align 2
  %mul0 = fmul contract half %in0, 0xH3E14
  %mul1 = fmul contract half %in1, 0xH3E14
  %sub0 = fsub contract half %mul0, %scale0
  %sub1 = fsub contract half %mul1, %scale1
  %exp0 = tail call half @llvm.amdgcn.exp2.f16(half %sub0)
  %exp1 = tail call half @llvm.amdgcn.exp2.f16(half %sub1)
  %log0 = tail call half @llvm.amdgcn.log.f16(half %exp0)
  %log1 = tail call half @llvm.amdgcn.log.f16(half %exp1)
  %sum = fadd fast half %log0, %log1
  store half %sum, ptr addrspace(1) %output, align 2
  ret void
}

define amdgpu_kernel void @look_through_reuse_shuffle(
; ENABLED-LABEL: define amdgpu_kernel void @look_through_reuse_shuffle(
; ENABLED-SAME: ptr addrspace(1) noalias [[INPUT:%.*]], ptr addrspace(1) noalias [[SCALES:%.*]], ptr addrspace(1) noalias [[OUTPUT:%.*]]) #[[ATTR0]] {
; ENABLED-NEXT:  [[ENTRY:.*:]]
; ENABLED-NEXT:    [[TMP0:%.*]] = load <2 x half>, ptr addrspace(1) [[INPUT]], align 2
; ENABLED-NEXT:    [[TMP1:%.*]] = load <2 x half>, ptr addrspace(1) [[SCALES]], align 2
; ENABLED-NEXT:    [[TMP8:%.*]] = fadd contract <2 x half> [[TMP0]], splat (half 0xH3E14)
; ENABLED-NEXT:    [[TMP10:%.*]] = fmul contract <2 x half> [[TMP8]], [[TMP1]]
; ENABLED-NEXT:    [[TMP3:%.*]] = extractelement <2 x half> [[TMP10]], i32 0
; ENABLED-NEXT:    [[TMP4:%.*]] = tail call half @llvm.amdgcn.exp2.f16(half [[TMP3]])
; ENABLED-NEXT:    [[TMP5:%.*]] = extractelement <2 x half> [[TMP10]], i32 1
; ENABLED-NEXT:    [[TMP6:%.*]] = tail call half @llvm.amdgcn.exp2.f16(half [[TMP5]])
; ENABLED-NEXT:    [[TMP2:%.*]] = insertelement <2 x half> poison, half [[TMP4]], i32 0
; ENABLED-NEXT:    [[TMP7:%.*]] = insertelement <2 x half> [[TMP2]], half [[TMP6]], i32 1
; ENABLED-NEXT:    [[TMP9:%.*]] = shufflevector <2 x half> [[TMP7]], <2 x half> poison, <4 x i32> <i32 0, i32 1, i32 1, i32 1>
; ENABLED-NEXT:    store <4 x half> [[TMP9]], ptr addrspace(1) [[OUTPUT]], align 2
; ENABLED-NEXT:    ret void
;
; DISABLED-LABEL: define amdgpu_kernel void @look_through_reuse_shuffle(
; DISABLED-SAME: ptr addrspace(1) noalias [[INPUT:%.*]], ptr addrspace(1) noalias [[SCALES:%.*]], ptr addrspace(1) noalias [[OUTPUT:%.*]]) #[[ATTR0]] {
; DISABLED-NEXT:  [[ENTRY:.*:]]
; DISABLED-NEXT:    [[IPTR1:%.*]] = getelementptr half, ptr addrspace(1) [[INPUT]], i64 1
; DISABLED-NEXT:    [[SPTR1:%.*]] = getelementptr half, ptr addrspace(1) [[SCALES]], i64 1
; DISABLED-NEXT:    [[IN0:%.*]] = load half, ptr addrspace(1) [[INPUT]], align 2
; DISABLED-NEXT:    [[IN1:%.*]] = load half, ptr addrspace(1) [[IPTR1]], align 2
; DISABLED-NEXT:    [[S0:%.*]] = load half, ptr addrspace(1) [[SCALES]], align 2
; DISABLED-NEXT:    [[S1:%.*]] = load half, ptr addrspace(1) [[SPTR1]], align 2
; DISABLED-NEXT:    [[ADD0:%.*]] = fadd contract half [[IN0]], 0xH3E14
; DISABLED-NEXT:    [[ADD1:%.*]] = fadd contract half [[IN1]], 0xH3E14
; DISABLED-NEXT:    [[MUL0:%.*]] = fmul contract half [[ADD0]], [[S0]]
; DISABLED-NEXT:    [[MUL1:%.*]] = fmul contract half [[ADD1]], [[S1]]
; DISABLED-NEXT:    [[EXP0:%.*]] = tail call half @llvm.amdgcn.exp2.f16(half [[MUL0]])
; DISABLED-NEXT:    [[EXP1:%.*]] = tail call half @llvm.amdgcn.exp2.f16(half [[MUL1]])
; DISABLED-NEXT:    [[TMP0:%.*]] = insertelement <4 x half> poison, half [[EXP0]], i32 0
; DISABLED-NEXT:    [[TMP1:%.*]] = insertelement <4 x half> [[TMP0]], half [[EXP1]], i32 1
; DISABLED-NEXT:    [[TMP2:%.*]] = shufflevector <4 x half> [[TMP1]], <4 x half> poison, <4 x i32> <i32 0, i32 1, i32 1, i32 1>
; DISABLED-NEXT:    store <4 x half> [[TMP2]], ptr addrspace(1) [[OUTPUT]], align 2
; DISABLED-NEXT:    ret void
;
  ptr addrspace(1) noalias %input, ptr addrspace(1) noalias %scales,
  ptr addrspace(1) noalias %output) {
entry:
  %iptr1 = getelementptr half, ptr addrspace(1) %input, i64 1
  %sptr1 = getelementptr half, ptr addrspace(1) %scales, i64 1
  %optr1 = getelementptr half, ptr addrspace(1) %output, i64 1
  %optr2 = getelementptr half, ptr addrspace(1) %output, i64 2
  %optr3 = getelementptr half, ptr addrspace(1) %output, i64 3

  %in0 = load half, ptr addrspace(1) %input, align 2
  %in1 = load half, ptr addrspace(1) %iptr1, align 2
  %s0 = load half, ptr addrspace(1) %scales, align 2
  %s1 = load half, ptr addrspace(1) %sptr1, align 2

  %add0 = fadd contract half %in0, 0xH3E14
  %add1 = fadd contract half %in1, 0xH3E14

  %mul0 = fmul contract half %add0, %s0
  %mul1 = fmul contract half %add1, %s1

  %exp0 = tail call half @llvm.amdgcn.exp2.f16(half %mul0)
  %exp1 = tail call half @llvm.amdgcn.exp2.f16(half %mul1)

  store half %exp0, ptr addrspace(1) %output, align 2
  store half %exp1, ptr addrspace(1) %optr1, align 2
  store half %exp1, ptr addrspace(1) %optr2, align 2
  store half %exp1, ptr addrspace(1) %optr3, align 2
  ret void
}

declare half @llvm.amdgcn.exp2.f16(half)
declare float @llvm.amdgcn.exp2.f32(float)
declare <8 x float> @llvm.amdgcn.wmma.scale.f32.16x16x128.f8f6f4.v8f32.v16i32.v16i32(i32 immarg, <16 x i32>, i32 immarg, <16 x i32>, i16 immarg, <8 x float>, i32 immarg, i32 immarg, i32, i32 immarg, i32 immarg, i32, i1 immarg, i1 immarg)
