// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// REQUIRES: x86-registered-target
// RUN: %clang_cc1 -flax-vector-conversions=none -ffreestanding %s -triple=x86_64-unknown-linux-gnu -target-feature +avx512f -target-feature +avx512vl -emit-llvm -o - -Wall -Werror | FileCheck --check-prefix=COMMON --check-prefix=COMMONIR --check-prefix=UNCONSTRAINED %s
// RUN: %clang_cc1 -flax-vector-conversions=none -fms-extensions -fms-compatibility -ffreestanding %s -triple=x86_64-windows-msvc -target-feature +avx512f -target-feature +avx512vl -emit-llvm -o - -Wall -Werror | FileCheck --check-prefix=COMMON --check-prefix=COMMONIR --check-prefix=UNCONSTRAINED %s
// RUN: %clang_cc1 -flax-vector-conversions=none -ffreestanding %s -triple=x86_64-unknown-linux-gnu -target-feature +avx512f -target-feature +avx512vl -ffp-exception-behavior=strict -emit-llvm -o - -Wall -Werror | FileCheck --check-prefix=COMMON --check-prefix=COMMONIR --check-prefix=CONSTRAINED %s
// RUN: %clang_cc1 -flax-vector-conversions=none -fms-compatibility -ffreestanding %s -triple=x86_64-unknown-linux-gnu -target-feature +avx512f -target-feature +avx512vl -ffp-exception-behavior=strict -emit-llvm -o - -Wall -Werror | FileCheck --check-prefix=COMMON --check-prefix=COMMONIR --check-prefix=CONSTRAINED %s

#include <immintrin.h>

// CONSTRAINED-LABEL: define dso_local <4 x float> @test_mm_mask_cvtph_ps(
// CONSTRAINED-SAME: <4 x float> noundef [[__W:%.*]], i8 noundef zeroext [[__U:%.*]], <2 x i64> noundef [[__A:%.*]]) #[[ATTR0:[0-9]+]] {
// CONSTRAINED-NEXT:  [[ENTRY:.*:]]
// CONSTRAINED-NEXT:    [[__W_ADDR_I:%.*]] = alloca <4 x float>, align 16
// CONSTRAINED-NEXT:    [[__U_ADDR_I:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR_I:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    [[__W_ADDR:%.*]] = alloca <4 x float>, align 16
// CONSTRAINED-NEXT:    [[__U_ADDR:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    store <4 x float> [[__W]], ptr [[__W_ADDR]], align 16
// CONSTRAINED-NEXT:    store i8 [[__U]], ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    store <2 x i64> [[__A]], ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    [[TMP0:%.*]] = load <4 x float>, ptr [[__W_ADDR]], align 16
// CONSTRAINED-NEXT:    [[TMP1:%.*]] = load i8, ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    [[TMP2:%.*]] = load <2 x i64>, ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    store <4 x float> [[TMP0]], ptr [[__W_ADDR_I]], align 16
// CONSTRAINED-NEXT:    store i8 [[TMP1]], ptr [[__U_ADDR_I]], align 1
// CONSTRAINED-NEXT:    store <2 x i64> [[TMP2]], ptr [[__A_ADDR_I]], align 16
// CONSTRAINED-NEXT:    [[TMP3:%.*]] = load <2 x i64>, ptr [[__A_ADDR_I]], align 16
// CONSTRAINED-NEXT:    [[TMP4:%.*]] = bitcast <2 x i64> [[TMP3]] to <8 x i16>
// CONSTRAINED-NEXT:    [[TMP5:%.*]] = load <4 x float>, ptr [[__W_ADDR_I]], align 16
// CONSTRAINED-NEXT:    [[TMP6:%.*]] = load i8, ptr [[__U_ADDR_I]], align 1
// CONSTRAINED-NEXT:    [[TMP7:%.*]] = shufflevector <8 x i16> [[TMP4]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CONSTRAINED-NEXT:    [[TMP8:%.*]] = bitcast <4 x i16> [[TMP7]] to <4 x half>
// CONSTRAINED-NEXT:    [[CVTPH2PS_I:%.*]] = call <4 x float> @llvm.fpext.v4f32.v4f16(<4 x half> [[TMP8]]) #[[ATTR4:[0-9]+]] [ "fp.control"(metadata !"rte") ]
// CONSTRAINED-NEXT:    [[TMP9:%.*]] = bitcast i8 [[TMP6]] to <8 x i1>
// CONSTRAINED-NEXT:    [[EXTRACT_I:%.*]] = shufflevector <8 x i1> [[TMP9]], <8 x i1> [[TMP9]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CONSTRAINED-NEXT:    [[TMP10:%.*]] = select <4 x i1> [[EXTRACT_I]], <4 x float> [[CVTPH2PS_I]], <4 x float> [[TMP5]]
// CONSTRAINED-NEXT:    ret <4 x float> [[TMP10]]
//
__m128 test_mm_mask_cvtph_ps(__m128 __W, __mmask8 __U, __m128i __A) {
  return _mm_mask_cvtph_ps(__W, __U, __A);
}

// CONSTRAINED-LABEL: define dso_local <4 x float> @test_mm_maskz_cvtph_ps(
// CONSTRAINED-SAME: i8 noundef zeroext [[__U:%.*]], <2 x i64> noundef [[__A:%.*]]) #[[ATTR0]] {
// CONSTRAINED-NEXT:  [[ENTRY:.*:]]
// CONSTRAINED-NEXT:    [[DOTCOMPOUNDLITERAL_I:%.*]] = alloca <4 x float>, align 16
// CONSTRAINED-NEXT:    [[__U_ADDR_I:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR_I:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    [[__U_ADDR:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    store i8 [[__U]], ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    store <2 x i64> [[__A]], ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    [[TMP0:%.*]] = load i8, ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    [[TMP1:%.*]] = load <2 x i64>, ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    store i8 [[TMP0]], ptr [[__U_ADDR_I]], align 1
// CONSTRAINED-NEXT:    store <2 x i64> [[TMP1]], ptr [[__A_ADDR_I]], align 16
// CONSTRAINED-NEXT:    [[TMP2:%.*]] = load <2 x i64>, ptr [[__A_ADDR_I]], align 16
// CONSTRAINED-NEXT:    [[TMP3:%.*]] = bitcast <2 x i64> [[TMP2]] to <8 x i16>
// CONSTRAINED-NEXT:    store <4 x float> zeroinitializer, ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CONSTRAINED-NEXT:    [[TMP4:%.*]] = load <4 x float>, ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CONSTRAINED-NEXT:    [[TMP5:%.*]] = load i8, ptr [[__U_ADDR_I]], align 1
// CONSTRAINED-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i16> [[TMP3]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CONSTRAINED-NEXT:    [[TMP7:%.*]] = bitcast <4 x i16> [[TMP6]] to <4 x half>
// CONSTRAINED-NEXT:    [[CVTPH2PS_I:%.*]] = call <4 x float> @llvm.fpext.v4f32.v4f16(<4 x half> [[TMP7]]) #[[ATTR4]] [ "fp.control"(metadata !"rte") ]
// CONSTRAINED-NEXT:    [[TMP8:%.*]] = bitcast i8 [[TMP5]] to <8 x i1>
// CONSTRAINED-NEXT:    [[EXTRACT_I:%.*]] = shufflevector <8 x i1> [[TMP8]], <8 x i1> [[TMP8]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CONSTRAINED-NEXT:    [[TMP9:%.*]] = select <4 x i1> [[EXTRACT_I]], <4 x float> [[CVTPH2PS_I]], <4 x float> [[TMP4]]
// CONSTRAINED-NEXT:    ret <4 x float> [[TMP9]]
//
__m128 test_mm_maskz_cvtph_ps(__mmask8 __U, __m128i __A) {
  return _mm_maskz_cvtph_ps(__U, __A);
}

// CONSTRAINED-LABEL: define dso_local <8 x float> @test_mm256_mask_cvtph_ps(
// CONSTRAINED-SAME: <8 x float> noundef [[__W:%.*]], i8 noundef zeroext [[__U:%.*]], <2 x i64> noundef [[__A:%.*]]) #[[ATTR1:[0-9]+]] {
// CONSTRAINED-NEXT:  [[ENTRY:.*:]]
// CONSTRAINED-NEXT:    [[__W_ADDR_I:%.*]] = alloca <8 x float>, align 32
// CONSTRAINED-NEXT:    [[__U_ADDR_I:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR_I:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    [[__W_ADDR:%.*]] = alloca <8 x float>, align 32
// CONSTRAINED-NEXT:    [[__U_ADDR:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    store <8 x float> [[__W]], ptr [[__W_ADDR]], align 32
// CONSTRAINED-NEXT:    store i8 [[__U]], ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    store <2 x i64> [[__A]], ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    [[TMP0:%.*]] = load <8 x float>, ptr [[__W_ADDR]], align 32
// CONSTRAINED-NEXT:    [[TMP1:%.*]] = load i8, ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    [[TMP2:%.*]] = load <2 x i64>, ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    store <8 x float> [[TMP0]], ptr [[__W_ADDR_I]], align 32
// CONSTRAINED-NEXT:    store i8 [[TMP1]], ptr [[__U_ADDR_I]], align 1
// CONSTRAINED-NEXT:    store <2 x i64> [[TMP2]], ptr [[__A_ADDR_I]], align 16
// CONSTRAINED-NEXT:    [[TMP3:%.*]] = load <2 x i64>, ptr [[__A_ADDR_I]], align 16
// CONSTRAINED-NEXT:    [[TMP4:%.*]] = bitcast <2 x i64> [[TMP3]] to <8 x i16>
// CONSTRAINED-NEXT:    [[TMP5:%.*]] = load <8 x float>, ptr [[__W_ADDR_I]], align 32
// CONSTRAINED-NEXT:    [[TMP6:%.*]] = load i8, ptr [[__U_ADDR_I]], align 1
// CONSTRAINED-NEXT:    [[TMP7:%.*]] = bitcast <8 x i16> [[TMP4]] to <8 x half>
// CONSTRAINED-NEXT:    [[CVTPH2PS_I:%.*]] = call <8 x float> @llvm.fpext.v8f32.v8f16(<8 x half> [[TMP7]]) #[[ATTR4]] [ "fp.control"(metadata !"rte") ]
// CONSTRAINED-NEXT:    [[TMP8:%.*]] = bitcast i8 [[TMP6]] to <8 x i1>
// CONSTRAINED-NEXT:    [[TMP9:%.*]] = select <8 x i1> [[TMP8]], <8 x float> [[CVTPH2PS_I]], <8 x float> [[TMP5]]
// CONSTRAINED-NEXT:    ret <8 x float> [[TMP9]]
//
__m256 test_mm256_mask_cvtph_ps(__m256 __W, __mmask8 __U, __m128i __A) {
  return _mm256_mask_cvtph_ps(__W, __U, __A);
}

// CONSTRAINED-LABEL: define dso_local <8 x float> @test_mm256_maskz_cvtph_ps(
// CONSTRAINED-SAME: i8 noundef zeroext [[__U:%.*]], <2 x i64> noundef [[__A:%.*]]) #[[ATTR1]] {
// CONSTRAINED-NEXT:  [[ENTRY:.*:]]
// CONSTRAINED-NEXT:    [[DOTCOMPOUNDLITERAL_I:%.*]] = alloca <8 x float>, align 32
// CONSTRAINED-NEXT:    [[__U_ADDR_I:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR_I:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    [[__U_ADDR:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    store i8 [[__U]], ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    store <2 x i64> [[__A]], ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    [[TMP0:%.*]] = load i8, ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    [[TMP1:%.*]] = load <2 x i64>, ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    store i8 [[TMP0]], ptr [[__U_ADDR_I]], align 1
// CONSTRAINED-NEXT:    store <2 x i64> [[TMP1]], ptr [[__A_ADDR_I]], align 16
// CONSTRAINED-NEXT:    [[TMP2:%.*]] = load <2 x i64>, ptr [[__A_ADDR_I]], align 16
// CONSTRAINED-NEXT:    [[TMP3:%.*]] = bitcast <2 x i64> [[TMP2]] to <8 x i16>
// CONSTRAINED-NEXT:    store <8 x float> zeroinitializer, ptr [[DOTCOMPOUNDLITERAL_I]], align 32
// CONSTRAINED-NEXT:    [[TMP4:%.*]] = load <8 x float>, ptr [[DOTCOMPOUNDLITERAL_I]], align 32
// CONSTRAINED-NEXT:    [[TMP5:%.*]] = load i8, ptr [[__U_ADDR_I]], align 1
// CONSTRAINED-NEXT:    [[TMP6:%.*]] = bitcast <8 x i16> [[TMP3]] to <8 x half>
// CONSTRAINED-NEXT:    [[CVTPH2PS_I:%.*]] = call <8 x float> @llvm.fpext.v8f32.v8f16(<8 x half> [[TMP6]]) #[[ATTR4]] [ "fp.control"(metadata !"rte") ]
// CONSTRAINED-NEXT:    [[TMP7:%.*]] = bitcast i8 [[TMP5]] to <8 x i1>
// CONSTRAINED-NEXT:    [[TMP8:%.*]] = select <8 x i1> [[TMP7]], <8 x float> [[CVTPH2PS_I]], <8 x float> [[TMP4]]
// CONSTRAINED-NEXT:    ret <8 x float> [[TMP8]]
//
__m256 test_mm256_maskz_cvtph_ps(__mmask8 __U, __m128i __A) {
  return _mm256_maskz_cvtph_ps(__U, __A);
}

// CONSTRAINED-LABEL: define dso_local <2 x i64> @test_mm_mask_cvtps_ph(
// CONSTRAINED-SAME: <2 x i64> noundef [[__W:%.*]], i8 noundef zeroext [[__U:%.*]], <4 x float> noundef [[__A:%.*]]) #[[ATTR0]] {
// CONSTRAINED-NEXT:  [[ENTRY:.*:]]
// CONSTRAINED-NEXT:    [[__W_ADDR:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    [[__U_ADDR:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR:%.*]] = alloca <4 x float>, align 16
// CONSTRAINED-NEXT:    store <2 x i64> [[__W]], ptr [[__W_ADDR]], align 16
// CONSTRAINED-NEXT:    store i8 [[__U]], ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    store <4 x float> [[__A]], ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    [[TMP0:%.*]] = load <4 x float>, ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    [[TMP1:%.*]] = load <2 x i64>, ptr [[__W_ADDR]], align 16
// CONSTRAINED-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP1]] to <8 x i16>
// CONSTRAINED-NEXT:    [[TMP3:%.*]] = load i8, ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    [[TMP4:%.*]] = call <8 x i16> @llvm.x86.avx512.mask.vcvtps2ph.128(<4 x float> [[TMP0]], i32 11, <8 x i16> [[TMP2]], i8 [[TMP3]]) #[[ATTR5:[0-9]+]]
// CONSTRAINED-NEXT:    [[TMP5:%.*]] = bitcast <8 x i16> [[TMP4]] to <2 x i64>
// CONSTRAINED-NEXT:    ret <2 x i64> [[TMP5]]
//
__m128i test_mm_mask_cvtps_ph(__m128i __W, __mmask8 __U, __m128 __A) {
  return _mm_mask_cvtps_ph(__W, __U, __A, _MM_FROUND_TO_ZERO | _MM_FROUND_NO_EXC);
}

// CONSTRAINED-LABEL: define dso_local <2 x i64> @test_mm_maskz_cvtps_ph(
// CONSTRAINED-SAME: i8 noundef zeroext [[__U:%.*]], <4 x float> noundef [[__A:%.*]]) #[[ATTR0]] {
// CONSTRAINED-NEXT:  [[ENTRY:.*:]]
// CONSTRAINED-NEXT:    [[DOTCOMPOUNDLITERAL_I:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    [[__U_ADDR:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR:%.*]] = alloca <4 x float>, align 16
// CONSTRAINED-NEXT:    store i8 [[__U]], ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    store <4 x float> [[__A]], ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    [[TMP0:%.*]] = load <4 x float>, ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    store <2 x i64> zeroinitializer, ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CONSTRAINED-NEXT:    [[TMP1:%.*]] = load <2 x i64>, ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CONSTRAINED-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP1]] to <8 x i16>
// CONSTRAINED-NEXT:    [[TMP3:%.*]] = load i8, ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    [[TMP4:%.*]] = call <8 x i16> @llvm.x86.avx512.mask.vcvtps2ph.128(<4 x float> [[TMP0]], i32 11, <8 x i16> [[TMP2]], i8 [[TMP3]]) #[[ATTR5]]
// CONSTRAINED-NEXT:    [[TMP5:%.*]] = bitcast <8 x i16> [[TMP4]] to <2 x i64>
// CONSTRAINED-NEXT:    ret <2 x i64> [[TMP5]]
//
__m128i test_mm_maskz_cvtps_ph(__mmask8 __U, __m128 __A) {
  return _mm_maskz_cvtps_ph(__U, __A, _MM_FROUND_TO_ZERO | _MM_FROUND_NO_EXC);
}

// CONSTRAINED-LABEL: define dso_local <2 x i64> @test_mm256_mask_cvtps_ph(
// CONSTRAINED-SAME: <2 x i64> noundef [[__W:%.*]], i8 noundef zeroext [[__U:%.*]], <8 x float> noundef [[__A:%.*]]) #[[ATTR1]] {
// CONSTRAINED-NEXT:  [[ENTRY:.*:]]
// CONSTRAINED-NEXT:    [[__W_ADDR:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    [[__U_ADDR:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR:%.*]] = alloca <8 x float>, align 32
// CONSTRAINED-NEXT:    store <2 x i64> [[__W]], ptr [[__W_ADDR]], align 16
// CONSTRAINED-NEXT:    store i8 [[__U]], ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    store <8 x float> [[__A]], ptr [[__A_ADDR]], align 32
// CONSTRAINED-NEXT:    [[TMP0:%.*]] = load <8 x float>, ptr [[__A_ADDR]], align 32
// CONSTRAINED-NEXT:    [[TMP1:%.*]] = load <2 x i64>, ptr [[__W_ADDR]], align 16
// CONSTRAINED-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP1]] to <8 x i16>
// CONSTRAINED-NEXT:    [[TMP3:%.*]] = load i8, ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    [[TMP4:%.*]] = call <8 x i16> @llvm.x86.avx512.mask.vcvtps2ph.256(<8 x float> [[TMP0]], i32 11, <8 x i16> [[TMP2]], i8 [[TMP3]]) #[[ATTR5]]
// CONSTRAINED-NEXT:    [[TMP5:%.*]] = bitcast <8 x i16> [[TMP4]] to <2 x i64>
// CONSTRAINED-NEXT:    ret <2 x i64> [[TMP5]]
//
__m128i test_mm256_mask_cvtps_ph(__m128i __W, __mmask8 __U, __m256 __A) {
  return _mm256_mask_cvtps_ph(__W, __U, __A, _MM_FROUND_TO_ZERO | _MM_FROUND_NO_EXC);
}

// CONSTRAINED-LABEL: define dso_local <2 x i64> @test_mm256_maskz_cvtps_ph(
// CONSTRAINED-SAME: i8 noundef zeroext [[__U:%.*]], <8 x float> noundef [[__A:%.*]]) #[[ATTR1]] {
// CONSTRAINED-NEXT:  [[ENTRY:.*:]]
// CONSTRAINED-NEXT:    [[DOTCOMPOUNDLITERAL_I:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    [[__U_ADDR:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR:%.*]] = alloca <8 x float>, align 32
// CONSTRAINED-NEXT:    store i8 [[__U]], ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    store <8 x float> [[__A]], ptr [[__A_ADDR]], align 32
// CONSTRAINED-NEXT:    [[TMP0:%.*]] = load <8 x float>, ptr [[__A_ADDR]], align 32
// CONSTRAINED-NEXT:    store <2 x i64> zeroinitializer, ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CONSTRAINED-NEXT:    [[TMP1:%.*]] = load <2 x i64>, ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CONSTRAINED-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP1]] to <8 x i16>
// CONSTRAINED-NEXT:    [[TMP3:%.*]] = load i8, ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    [[TMP4:%.*]] = call <8 x i16> @llvm.x86.avx512.mask.vcvtps2ph.256(<8 x float> [[TMP0]], i32 11, <8 x i16> [[TMP2]], i8 [[TMP3]]) #[[ATTR5]]
// CONSTRAINED-NEXT:    [[TMP5:%.*]] = bitcast <8 x i16> [[TMP4]] to <2 x i64>
// CONSTRAINED-NEXT:    ret <2 x i64> [[TMP5]]
//
__m128i test_mm256_maskz_cvtps_ph(__mmask8 __U, __m256 __A) {
  return _mm256_maskz_cvtps_ph(__U, __A, _MM_FROUND_TO_ZERO | _MM_FROUND_NO_EXC);
}

// CONSTRAINED-LABEL: define dso_local <2 x i64> @test_mm_mask_cvt_roundps_ph(
// CONSTRAINED-SAME: <2 x i64> noundef [[__W:%.*]], i8 noundef zeroext [[__U:%.*]], <4 x float> noundef [[__A:%.*]]) #[[ATTR0]] {
// CONSTRAINED-NEXT:  [[ENTRY:.*:]]
// CONSTRAINED-NEXT:    [[__W_ADDR:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    [[__U_ADDR:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR:%.*]] = alloca <4 x float>, align 16
// CONSTRAINED-NEXT:    store <2 x i64> [[__W]], ptr [[__W_ADDR]], align 16
// CONSTRAINED-NEXT:    store i8 [[__U]], ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    store <4 x float> [[__A]], ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    [[TMP0:%.*]] = load <4 x float>, ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    [[TMP1:%.*]] = load <2 x i64>, ptr [[__W_ADDR]], align 16
// CONSTRAINED-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP1]] to <8 x i16>
// CONSTRAINED-NEXT:    [[TMP3:%.*]] = load i8, ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    [[TMP4:%.*]] = call <8 x i16> @llvm.x86.avx512.mask.vcvtps2ph.128(<4 x float> [[TMP0]], i32 3, <8 x i16> [[TMP2]], i8 [[TMP3]]) #[[ATTR5]]
// CONSTRAINED-NEXT:    [[TMP5:%.*]] = bitcast <8 x i16> [[TMP4]] to <2 x i64>
// CONSTRAINED-NEXT:    ret <2 x i64> [[TMP5]]
//
__m128i test_mm_mask_cvt_roundps_ph(__m128i __W, __mmask8 __U, __m128 __A) {
  return _mm_mask_cvt_roundps_ph(__W, __U, __A, _MM_FROUND_TO_ZERO);
}

// CONSTRAINED-LABEL: define dso_local <2 x i64> @test_mm_maskz_cvt_roundps_ph(
// CONSTRAINED-SAME: i8 noundef zeroext [[__U:%.*]], <4 x float> noundef [[__A:%.*]]) #[[ATTR0]] {
// CONSTRAINED-NEXT:  [[ENTRY:.*:]]
// CONSTRAINED-NEXT:    [[DOTCOMPOUNDLITERAL_I:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    [[__U_ADDR:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR:%.*]] = alloca <4 x float>, align 16
// CONSTRAINED-NEXT:    store i8 [[__U]], ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    store <4 x float> [[__A]], ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    [[TMP0:%.*]] = load <4 x float>, ptr [[__A_ADDR]], align 16
// CONSTRAINED-NEXT:    store <2 x i64> zeroinitializer, ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CONSTRAINED-NEXT:    [[TMP1:%.*]] = load <2 x i64>, ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CONSTRAINED-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP1]] to <8 x i16>
// CONSTRAINED-NEXT:    [[TMP3:%.*]] = load i8, ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    [[TMP4:%.*]] = call <8 x i16> @llvm.x86.avx512.mask.vcvtps2ph.128(<4 x float> [[TMP0]], i32 3, <8 x i16> [[TMP2]], i8 [[TMP3]]) #[[ATTR5]]
// CONSTRAINED-NEXT:    [[TMP5:%.*]] = bitcast <8 x i16> [[TMP4]] to <2 x i64>
// CONSTRAINED-NEXT:    ret <2 x i64> [[TMP5]]
//
__m128i test_mm_maskz_cvt_roundps_ph(__mmask8 __U, __m128 __A) {
  return _mm_maskz_cvt_roundps_ph(__U, __A, _MM_FROUND_TO_ZERO);
}

// CONSTRAINED-LABEL: define dso_local <2 x i64> @test_mm256_mask_cvt_roundps_ph(
// CONSTRAINED-SAME: <2 x i64> noundef [[__W:%.*]], i8 noundef zeroext [[__U:%.*]], <8 x float> noundef [[__A:%.*]]) #[[ATTR1]] {
// CONSTRAINED-NEXT:  [[ENTRY:.*:]]
// CONSTRAINED-NEXT:    [[__W_ADDR:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    [[__U_ADDR:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR:%.*]] = alloca <8 x float>, align 32
// CONSTRAINED-NEXT:    store <2 x i64> [[__W]], ptr [[__W_ADDR]], align 16
// CONSTRAINED-NEXT:    store i8 [[__U]], ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    store <8 x float> [[__A]], ptr [[__A_ADDR]], align 32
// CONSTRAINED-NEXT:    [[TMP0:%.*]] = load <8 x float>, ptr [[__A_ADDR]], align 32
// CONSTRAINED-NEXT:    [[TMP1:%.*]] = load <2 x i64>, ptr [[__W_ADDR]], align 16
// CONSTRAINED-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP1]] to <8 x i16>
// CONSTRAINED-NEXT:    [[TMP3:%.*]] = load i8, ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    [[TMP4:%.*]] = call <8 x i16> @llvm.x86.avx512.mask.vcvtps2ph.256(<8 x float> [[TMP0]], i32 3, <8 x i16> [[TMP2]], i8 [[TMP3]]) #[[ATTR5]]
// CONSTRAINED-NEXT:    [[TMP5:%.*]] = bitcast <8 x i16> [[TMP4]] to <2 x i64>
// CONSTRAINED-NEXT:    ret <2 x i64> [[TMP5]]
//
__m128i test_mm256_mask_cvt_roundps_ph(__m128i __W, __mmask8 __U, __m256 __A) {
  return _mm256_mask_cvt_roundps_ph(__W, __U, __A, _MM_FROUND_TO_ZERO);
}

// CONSTRAINED-LABEL: define dso_local <2 x i64> @test_mm256_maskz_cvt_roundps_ph(
// CONSTRAINED-SAME: i8 noundef zeroext [[__U:%.*]], <8 x float> noundef [[__A:%.*]]) #[[ATTR1]] {
// CONSTRAINED-NEXT:  [[ENTRY:.*:]]
// CONSTRAINED-NEXT:    [[DOTCOMPOUNDLITERAL_I:%.*]] = alloca <2 x i64>, align 16
// CONSTRAINED-NEXT:    [[__U_ADDR:%.*]] = alloca i8, align 1
// CONSTRAINED-NEXT:    [[__A_ADDR:%.*]] = alloca <8 x float>, align 32
// CONSTRAINED-NEXT:    store i8 [[__U]], ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    store <8 x float> [[__A]], ptr [[__A_ADDR]], align 32
// CONSTRAINED-NEXT:    [[TMP0:%.*]] = load <8 x float>, ptr [[__A_ADDR]], align 32
// CONSTRAINED-NEXT:    store <2 x i64> zeroinitializer, ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CONSTRAINED-NEXT:    [[TMP1:%.*]] = load <2 x i64>, ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CONSTRAINED-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP1]] to <8 x i16>
// CONSTRAINED-NEXT:    [[TMP3:%.*]] = load i8, ptr [[__U_ADDR]], align 1
// CONSTRAINED-NEXT:    [[TMP4:%.*]] = call <8 x i16> @llvm.x86.avx512.mask.vcvtps2ph.256(<8 x float> [[TMP0]], i32 3, <8 x i16> [[TMP2]], i8 [[TMP3]]) #[[ATTR5]]
// CONSTRAINED-NEXT:    [[TMP5:%.*]] = bitcast <8 x i16> [[TMP4]] to <2 x i64>
// CONSTRAINED-NEXT:    ret <2 x i64> [[TMP5]]
//
__m128i test_mm256_maskz_cvt_roundps_ph(__mmask8 __U, __m256 __A) {
  return _mm256_maskz_cvt_roundps_ph(__U, __A, _MM_FROUND_TO_ZERO);
}
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// COMMON: {{.*}}
// COMMONIR: {{.*}}
// UNCONSTRAINED: {{.*}}
