; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --check-globals --include-generated-funcs
; RUN: opt -passes='tysan' -tysan-outline-instrumentation=false -S %s | FileCheck %s --check-prefix=CHECK-INLINE
; RUN: opt -passes='tysan' -S %s | FileCheck %s --check-prefix=CHECK-OUTLINE

!llvm.tysan.globals = !{!0}

!0 = distinct !{ptr null, !1}
!1 = !{!"any pointer", !2, i64 0}
!2 = !{!"omnipotent char", !3, i64 0}
!3 = !{!"Simple C/C++ TBAA"}
; CHECK: @llvm.used = appending global [1 x ptr] [ptr @tysan.module_ctor], section "llvm.metadata"
; CHECK: @__tysan_shadow_memory_address = external global i64
; CHECK: @__tysan_app_memory_mask = external global i64
; CHECK: @llvm.global_ctors = appending global [1 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 0, ptr @tysan.module_ctor, ptr null }]
; CHECK-LABEL: define {{[^@]+}}@tysan.module_ctor
; CHECK-SAME: () #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    call void @__tysan_init()
; CHECK-NEXT:    call void @__tysan_set_globals_types()
; CHECK-NEXT:    ret void
; CHECK-LABEL: define {{[^@]+}}@__tysan_set_globals_types() {
; CHECK-NEXT:    [[APP_MEM_MASK:%.*]] = load i64, ptr @__tysan_app_memory_mask, align 4
; CHECK-NEXT:    [[SHADOW_BASE:%.*]] = load i64, ptr @__tysan_shadow_memory_address, align 4
; CHECK-NEXT:    ret void
; CHECK: attributes #[[ATTR0]] = { nounwind }
; CHECK: [[META0:![0-9]+]] = distinct !{ptr null, [[META1:![0-9]+]]}
; CHECK: [[META1]] = !{!"any pointer", [[META2:![0-9]+]], i64 0}
; CHECK: [[META2]] = !{!"omnipotent char", [[META3:![0-9]+]], i64 0}
; CHECK: [[META3]] = !{!"Simple C/C++ TBAA"}
;.
; CHECK-INLINE: @llvm.used = appending global [1 x ptr] [ptr @tysan.module_ctor], section "llvm.metadata"
; CHECK-INLINE: @__tysan_shadow_memory_address = external global i64
; CHECK-INLINE: @__tysan_app_memory_mask = external global i64
; CHECK-INLINE: @llvm.global_ctors = appending global [1 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 0, ptr @tysan.module_ctor, ptr null }]
;.
; CHECK-OUTLINE: @llvm.used = appending global [1 x ptr] [ptr @tysan.module_ctor], section "llvm.metadata"
; CHECK-OUTLINE: @__tysan_shadow_memory_address = external global i64
; CHECK-OUTLINE: @__tysan_app_memory_mask = external global i64
; CHECK-OUTLINE: @llvm.global_ctors = appending global [1 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 0, ptr @tysan.module_ctor, ptr null }]
;.
; CHECK-INLINE-LABEL: define {{[^@]+}}@tysan.module_ctor
; CHECK-INLINE-SAME: () #[[ATTR0:[0-9]+]] {
; CHECK-INLINE-NEXT:    call void @__tysan_init()
; CHECK-INLINE-NEXT:    call void @__tysan_set_globals_types()
; CHECK-INLINE-NEXT:    ret void
;
;
; CHECK-INLINE-LABEL: define {{[^@]+}}@__tysan_set_globals_types() {
; CHECK-INLINE-NEXT:    [[APP_MEM_MASK:%.*]] = load i64, ptr @__tysan_app_memory_mask, align 4
; CHECK-INLINE-NEXT:    [[SHADOW_BASE:%.*]] = load i64, ptr @__tysan_shadow_memory_address, align 4
; CHECK-INLINE-NEXT:    ret void
;
;
; CHECK-OUTLINE-LABEL: define {{[^@]+}}@tysan.module_ctor
; CHECK-OUTLINE-SAME: () #[[ATTR0:[0-9]+]] {
; CHECK-OUTLINE-NEXT:    call void @__tysan_init()
; CHECK-OUTLINE-NEXT:    call void @__tysan_set_globals_types()
; CHECK-OUTLINE-NEXT:    ret void
;
;
; CHECK-OUTLINE-LABEL: define {{[^@]+}}@__tysan_set_globals_types() {
; CHECK-OUTLINE-NEXT:    [[APP_MEM_MASK:%.*]] = load i64, ptr @__tysan_app_memory_mask, align 4
; CHECK-OUTLINE-NEXT:    [[SHADOW_BASE:%.*]] = load i64, ptr @__tysan_shadow_memory_address, align 4
; CHECK-OUTLINE-NEXT:    ret void
;
;.
; CHECK-INLINE: attributes #[[ATTR0]] = { nounwind }
;.
; CHECK-OUTLINE: attributes #[[ATTR0]] = { nounwind }
;.
; CHECK-INLINE: [[META0:![0-9]+]] = distinct !{ptr null, [[META1:![0-9]+]]}
; CHECK-INLINE: [[META1]] = !{!"any pointer", [[META2:![0-9]+]], i64 0}
; CHECK-INLINE: [[META2]] = !{!"omnipotent char", [[META3:![0-9]+]], i64 0}
; CHECK-INLINE: [[META3]] = !{!"Simple C/C++ TBAA"}
;.
; CHECK-OUTLINE: [[META0:![0-9]+]] = distinct !{ptr null, [[META1:![0-9]+]]}
; CHECK-OUTLINE: [[META1]] = !{!"any pointer", [[META2:![0-9]+]], i64 0}
; CHECK-OUTLINE: [[META2]] = !{!"omnipotent char", [[META3:![0-9]+]], i64 0}
; CHECK-OUTLINE: [[META3]] = !{!"Simple C/C++ TBAA"}
;.
