; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 6
; Test basic type sanitizer instrumentation.
;
; RUN: opt -passes='tysan' -tysan-outline-instrumentation=false -S %s | FileCheck %s --check-prefix=CHECK-INLINE
; RUN: opt -passes='tysan' -S %s | FileCheck %s --check-prefix=CHECK-OUTLINE

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

; CHECK: @llvm.used = appending global [1 x ptr] [ptr @tysan.module_ctor], section "llvm.metadata"
; CHECK: @llvm.global_ctors = appending global [1 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 0, ptr @tysan.module_ctor, ptr null }]
;.
; CHECK-INLINE: @llvm.used = appending global [1 x ptr] [ptr @tysan.module_ctor], section "llvm.metadata"
; CHECK-INLINE: @llvm.global_ctors = appending global [1 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 0, ptr @tysan.module_ctor, ptr null }]
;.
; CHECK-OUTLINE: @llvm.used = appending global [1 x ptr] [ptr @tysan.module_ctor], section "llvm.metadata"
; CHECK-OUTLINE: @llvm.global_ctors = appending global [1 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 0, ptr @tysan.module_ctor, ptr null }]
;.
define i32 @test_load(ptr %a) sanitize_type {
; CHECK-LABEL: define i32 @test_load(
; CHECK-SAME: ptr [[A:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A]], align 4, !tbaa [[INT_TBAA0:![0-9]+]], !nosanitize [[META4:![0-9]+]]
; CHECK-NEXT:    ret i32 [[TMP1]]
;
; CHECK-INLINE-LABEL: define i32 @test_load(
; CHECK-INLINE-SAME: ptr [[A:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-INLINE-NEXT:  [[ENTRY:.*:]]
; CHECK-INLINE-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A]], align 4, !tbaa [[INT_TBAA0:![0-9]+]], !nosanitize [[META4:![0-9]+]]
; CHECK-INLINE-NEXT:    ret i32 [[TMP1]]
;
; CHECK-OUTLINE-LABEL: define i32 @test_load(
; CHECK-OUTLINE-SAME: ptr [[A:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-OUTLINE-NEXT:  [[ENTRY:.*:]]
; CHECK-OUTLINE-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A]], align 4, !tbaa [[INT_TBAA0:![0-9]+]], !nosanitize [[META4:![0-9]+]]
; CHECK-OUTLINE-NEXT:    ret i32 [[TMP1]]
;
entry:
  %tmp1 = load i32, ptr %a, align 4, !tbaa !3, !nosanitize !{}
  ret i32 %tmp1
}

!0 = !{!"Simple C++ TBAA"}
!1 = !{!"omnipotent char", !0, i64 0}
!2 = !{!"int", !1, i64 0}
!3 = !{!2, !2, i64 0}
!4 = !{!"_ZTS1x", !2, i64 0, !2, i64 4}
!5 = !{!"_ZTS1v", !2, i64 8, !2, i64 12, !4, i64 16}
!6 = !{!5, !2, i64 12}
; CHECK: attributes #[[ATTR0]] = { sanitize_type }
; CHECK: attributes #[[ATTR1:[0-9]+]] = { nounwind }
; CHECK: [[INT_TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; CHECK: [[META1]] = !{!"int", [[META2:![0-9]+]], i64 0}
; CHECK: [[META2]] = !{!"omnipotent char", [[META3:![0-9]+]], i64 0}
; CHECK: [[META3]] = !{!"Simple C++ TBAA"}
; CHECK: [[META4]] = !{}
;.
; CHECK-INLINE: attributes #[[ATTR0]] = { sanitize_type }
; CHECK-INLINE: attributes #[[ATTR1:[0-9]+]] = { nounwind }
;.
; CHECK-OUTLINE: attributes #[[ATTR0]] = { sanitize_type }
; CHECK-OUTLINE: attributes #[[ATTR1:[0-9]+]] = { nounwind }
;.
; CHECK-INLINE: [[INT_TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; CHECK-INLINE: [[META1]] = !{!"int", [[META2:![0-9]+]], i64 0}
; CHECK-INLINE: [[META2]] = !{!"omnipotent char", [[META3:![0-9]+]], i64 0}
; CHECK-INLINE: [[META3]] = !{!"Simple C++ TBAA"}
; CHECK-INLINE: [[META4]] = !{}
;.
; CHECK-OUTLINE: [[INT_TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; CHECK-OUTLINE: [[META1]] = !{!"int", [[META2:![0-9]+]], i64 0}
; CHECK-OUTLINE: [[META2]] = !{!"omnipotent char", [[META3:![0-9]+]], i64 0}
; CHECK-OUTLINE: [[META3]] = !{!"Simple C++ TBAA"}
; CHECK-OUTLINE: [[META4]] = !{}
;.
