; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt --bpf-check-and-opt-ir -S -mtriple=bpf-pc-linux < %s | FileCheck %s

define void @test(ptr addrspace(1) %p) {
; CHECK-LABEL: define void @test(
; CHECK-SAME:    ptr addrspace(1) [[P:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[P1:%.*]] = addrspacecast ptr addrspace(1) [[P]] to ptr
; CHECK-NEXT:    [[A2:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 8
; CHECK-NEXT:    [[B3:%.*]] = getelementptr inbounds i8, ptr [[A2]], i64 16
; CHECK-NEXT:    [[C4:%.*]] = getelementptr inbounds i8, ptr [[B3]], i64 24
; CHECK-NEXT:    [[D5:%.*]] = getelementptr inbounds i8, ptr [[C4]], i64 32
; CHECK-NEXT:    store i64 11, ptr [[C4]], align 8
; CHECK-NEXT:    store i64 22, ptr [[D5]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %a = getelementptr inbounds i8, ptr addrspace(1) %p, i64 8
  %b = getelementptr inbounds i8, ptr addrspace(1) %a, i64 16
  %c = getelementptr inbounds i8, ptr addrspace(1) %b, i64 24
  %d = getelementptr inbounds i8, ptr addrspace(1) %c, i64 32
  store i64 11, ptr addrspace(1) %c, align 8
  store i64 22, ptr addrspace(1) %d, align 8
  ret void
}
