; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; This is the BPF counterpart to the generic `half.ll` test as BPF has compilation errors on some
; operations.
; RUN: llc %s -o - -mtriple=bpfel | FileCheck %s

define half @from_bits(i16 %bits) nounwind {
; CHECK-LABEL: from_bits:
; CHECK:       # %bb.0:
; CHECK-NEXT:    w0 = w1
; CHECK-NEXT:    exit
  %f = bitcast i16 %bits to half
  ret half %f
}

define i16 @to_bits(half %f) nounwind {
; CHECK-LABEL: to_bits:
; CHECK:       # %bb.0:
; CHECK-NEXT:    w0 = w1
; CHECK-NEXT:    exit
  %bits = bitcast half %f to i16
  ret i16 %bits
}

define half @check_freeze(half %f) nounwind {
; CHECK-LABEL: check_freeze:
; CHECK:       # %bb.0:
; CHECK-NEXT:    w0 = w1
; CHECK-NEXT:    exit
  %t0 = freeze half %f
  ret half %t0
}
