; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=bpfel -mcpu=v5 < %s | FileCheck %s

define void @bar() {
; CHECK-LABEL: bar:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    call quux
; CHECK-NEXT:    *(u64 *)(r11 - 8) = r0
; CHECK-NEXT:    call quux
; CHECK-NEXT:    *(u64 *)(r11 - 16) = r0
; CHECK-NEXT:    call quux
; CHECK-NEXT:    *(u64 *)(r11 - 24) = r0
; CHECK-NEXT:    call quux
; CHECK-NEXT:    *(u64 *)(r11 - 32) = r0
; CHECK-NEXT:    call quux
; CHECK-NEXT:    *(u64 *)(r11 - 40) = r0
; CHECK-NEXT:    call quux
; CHECK-NEXT:    *(u64 *)(r11 - 48) = r0
; CHECK-NEXT:    call quux
; CHECK-NEXT:    r8 = r0
; CHECK-NEXT:    call quux
; CHECK-NEXT:    r9 = r0
; CHECK-NEXT:    call quux
; CHECK-NEXT:    r6 = r0
; CHECK-NEXT:    call quux
; CHECK-NEXT:    r7 = r0
; CHECK-NEXT:    r1 = *(u64 *)(r11 - 8)
; CHECK-NEXT:    r2 = *(u64 *)(r11 - 16)
; CHECK-NEXT:    r3 = *(u64 *)(r11 - 24)
; CHECK-NEXT:    r4 = *(u64 *)(r11 - 32)
; CHECK-NEXT:    r5 = *(u64 *)(r11 - 40)
; CHECK-NEXT:    call buz
; CHECK-NEXT:    r1 = *(u64 *)(r11 - 48)
; CHECK-NEXT:    r2 = r8
; CHECK-NEXT:    r3 = r9
; CHECK-NEXT:    r4 = r6
; CHECK-NEXT:    r5 = r7
; CHECK-NEXT:    call buz
; CHECK-NEXT:    r1 = r10
; CHECK-NEXT:    r1 += -8
; CHECK-NEXT:    call foo
; CHECK-NEXT:    r1 = r10
; CHECK-NEXT:    r1 += -16
; CHECK-NEXT:    call foo
; CHECK-NEXT:    exit
entry:
  %x = alloca i64, align 8
  %y = alloca i64, align 8
  ; Apply some register pressure by accumulating a set of values
  ; exceeding number of callee saved registers.
  %a = tail call i64 @quux()
  %b = tail call i64 @quux()
  %c = tail call i64 @quux()
  %d = tail call i64 @quux()
  %e = tail call i64 @quux()
  %f = tail call i64 @quux()
  %g = tail call i64 @quux()
  %h = tail call i64 @quux()
  %i = tail call i64 @quux()
  %j = tail call i64 @quux()
  ; Use each accumulated value in a call.
  tail call void @buz(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e)
  tail call void @buz(i64 %f, i64 %g, i64 %h, i64 %i, i64 %j)
  ; Use two stack allocated objects, to check that r10 offsets
  ; allocated for these objects are independent of r11 offsets
  ; allocated for stack spills.
  call void @foo(ptr %x)
  call void @foo(ptr %y)
  ret void
}

declare i64 @quux()
declare void @buz(i64, i64, i64, i64, i64)
declare void @foo(ptr)
