; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=bpf < %s | FileCheck %s

%struct.S = type { i32, i32, i32 }

@s = common global %struct.S zeroinitializer, align 4

; Function Attrs: nounwind readonly uwtable
define { i64, i32 } @bar(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) #0 {
; CHECK-LABEL: bar:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    r1 = s ll
; CHECK-NEXT:    w2 = *(u32 *)(r1 + 0)
; CHECK-NEXT:    w0 = *(u32 *)(r1 + 4)
; CHECK-NEXT:    r0 <<= 32
; CHECK-NEXT:    r0 |= r2
; CHECK-NEXT:    w2 = *(u32 *)(r1 + 8)
; CHECK-NEXT:    exit
entry:
  %retval.sroa.0.0.copyload = load i64, ptr @s, align 4
  %retval.sroa.2.0.copyload = load i32, ptr getelementptr inbounds (%struct.S, ptr @s, i64 0, i32 2), align 4
  %.fca.0.insert = insertvalue { i64, i32 } undef, i64 %retval.sroa.0.0.copyload, 0
  %.fca.1.insert = insertvalue { i64, i32 } %.fca.0.insert, i32 %retval.sroa.2.0.copyload, 1
  ret { i64, i32 } %.fca.1.insert
}

%struct.B = type { [100 x i64] }

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local void @baz(ptr noalias nocapture sret(%struct.B) align 8 %agg.result) local_unnamed_addr #0 {
; CHECK-LABEL: baz:
; CHECK:       .Lbaz$local:
; CHECK-NEXT:    .type .Lbaz$local,@function
; CHECK-NEXT:    .cfi_startproc
; CHECK-NEXT:  # %bb.0: # %entry
; CHECK-NEXT:    exit
entry:
  ret void
}
