# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "compile_commands",
    srcs = ["refresh.py"],
    main = "refresh.py",
    data = ["@wolfd_bazel_compile_commands//:generate_compile_commands"],
    deps = ["@rules_python//python/runfiles"],
)

