# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv32 -mattr=+d -run-pass=legalizer %s -o - \
# RUN: | FileCheck %s
# RUN: llc -mtriple=riscv64 -mattr=+d -run-pass=legalizer %s -o - \
# RUN: | FileCheck %s

---
name:            ceil_f32
body:             |
  bb.1:
    liveins: $f10_f

    ; CHECK-LABEL: name: ceil_f32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $f10_f = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoCALL target-flags(riscv-call) &ceilf, csr_ilp32d_lp64d, implicit-def $x1, implicit $f10_f, implicit-def $f10_f
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: $f10_f = COPY [[COPY1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = G_FCEIL %0
    $f10_f = COPY %1(s32)
    PseudoRET implicit $f10_f

...
---
name:            floor_f32
body:             |
  bb.1:
    liveins: $f10_f

    ; CHECK-LABEL: name: floor_f32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $f10_f = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoCALL target-flags(riscv-call) &floorf, csr_ilp32d_lp64d, implicit-def $x1, implicit $f10_f, implicit-def $f10_f
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: $f10_f = COPY [[COPY1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = G_FFLOOR %0
    $f10_f = COPY %1(s32)
    PseudoRET implicit $f10_f

...
---
name:            trunc_f32
body:             |
  bb.1:
    liveins: $f10_f

    ; CHECK-LABEL: name: trunc_f32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $f10_f = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoCALL target-flags(riscv-call) &truncf, csr_ilp32d_lp64d, implicit-def $x1, implicit $f10_f, implicit-def $f10_f
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: $f10_f = COPY [[COPY1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = G_INTRINSIC_TRUNC %0
    $f10_f = COPY %1(s32)
    PseudoRET implicit $f10_f

...
---
name:            rint_f32
body:             |
  bb.1:
    liveins: $f10_f

    ; CHECK-LABEL: name: rint_f32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $f10_f = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoCALL target-flags(riscv-call) &rintf, csr_ilp32d_lp64d, implicit-def $x1, implicit $f10_f, implicit-def $f10_f
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: $f10_f = COPY [[COPY1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = G_FRINT %0
    $f10_f = COPY %1(s32)
    PseudoRET implicit $f10_f

...
---
name:            nearbyint_f32
body:             |
  bb.1:
    liveins: $f10_f

    ; CHECK-LABEL: name: nearbyint_f32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $f10_f = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoCALL target-flags(riscv-call) &nearbyintf, csr_ilp32d_lp64d, implicit-def $x1, implicit $f10_f, implicit-def $f10_f
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: $f10_f = COPY [[COPY1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = G_FNEARBYINT %0
    $f10_f = COPY %1(s32)
    PseudoRET implicit $f10_f

...
---
name:            round_f32
body:             |
  bb.1:
    liveins: $f10_f

    ; CHECK-LABEL: name: round_f32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $f10_f = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoCALL target-flags(riscv-call) &roundf, csr_ilp32d_lp64d, implicit-def $x1, implicit $f10_f, implicit-def $f10_f
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: $f10_f = COPY [[COPY1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = G_INTRINSIC_ROUND %0
    $f10_f = COPY %1(s32)
    PseudoRET implicit $f10_f

...
---
name:            roundeven_f32
body:             |
  bb.1:
    liveins: $f10_f

    ; CHECK-LABEL: name: roundeven_f32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $f10_f = COPY [[COPY]](s32)
    ; CHECK-NEXT: PseudoCALL target-flags(riscv-call) &roundevenf, csr_ilp32d_lp64d, implicit-def $x1, implicit $f10_f, implicit-def $f10_f
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: $f10_f = COPY [[COPY1]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = G_INTRINSIC_ROUNDEVEN %0
    $f10_f = COPY %1(s32)
    PseudoRET implicit $f10_f

...
---
name:            ceil_f64
body:             |
  bb.1:
    liveins: $f10_d

    ; CHECK-LABEL: name: ceil_f64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $f10_d = COPY [[COPY]](s64)
    ; CHECK-NEXT: PseudoCALL target-flags(riscv-call) &ceil, csr_ilp32d_lp64d, implicit-def $x1, implicit $f10_d, implicit-def $f10_d
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: $f10_d = COPY [[COPY1]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = G_FCEIL %0
    $f10_d = COPY %1(s64)
    PseudoRET implicit $f10_d

...
---
name:            floor_f64
body:             |
  bb.1:
    liveins: $f10_d

    ; CHECK-LABEL: name: floor_f64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $f10_d = COPY [[COPY]](s64)
    ; CHECK-NEXT: PseudoCALL target-flags(riscv-call) &floor, csr_ilp32d_lp64d, implicit-def $x1, implicit $f10_d, implicit-def $f10_d
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: $f10_d = COPY [[COPY1]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = G_FFLOOR %0
    $f10_d = COPY %1(s64)
    PseudoRET implicit $f10_d

...
---
name:            trunc_f64
body:             |
  bb.1:
    liveins: $f10_d

    ; CHECK-LABEL: name: trunc_f64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $f10_d = COPY [[COPY]](s64)
    ; CHECK-NEXT: PseudoCALL target-flags(riscv-call) &trunc, csr_ilp32d_lp64d, implicit-def $x1, implicit $f10_d, implicit-def $f10_d
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: $f10_d = COPY [[COPY1]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = G_INTRINSIC_TRUNC %0
    $f10_d = COPY %1(s64)
    PseudoRET implicit $f10_d

...
---
name:            rint_f64
body:             |
  bb.1:
    liveins: $f10_d

    ; CHECK-LABEL: name: rint_f64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $f10_d = COPY [[COPY]](s64)
    ; CHECK-NEXT: PseudoCALL target-flags(riscv-call) &rint, csr_ilp32d_lp64d, implicit-def $x1, implicit $f10_d, implicit-def $f10_d
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: $f10_d = COPY [[COPY1]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = G_FRINT %0
    $f10_d = COPY %1(s64)
    PseudoRET implicit $f10_d

...
---
name:            nearbyint_f64
body:             |
  bb.1:
    liveins: $f10_d

    ; CHECK-LABEL: name: nearbyint_f64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $f10_d = COPY [[COPY]](s64)
    ; CHECK-NEXT: PseudoCALL target-flags(riscv-call) &nearbyint, csr_ilp32d_lp64d, implicit-def $x1, implicit $f10_d, implicit-def $f10_d
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: $f10_d = COPY [[COPY1]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = G_FNEARBYINT %0
    $f10_d = COPY %1(s64)
    PseudoRET implicit $f10_d

...
---
name:            round_f64
body:             |
  bb.1:
    liveins: $f10_d

    ; CHECK-LABEL: name: round_f64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $f10_d = COPY [[COPY]](s64)
    ; CHECK-NEXT: PseudoCALL target-flags(riscv-call) &round, csr_ilp32d_lp64d, implicit-def $x1, implicit $f10_d, implicit-def $f10_d
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: $f10_d = COPY [[COPY1]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = G_INTRINSIC_ROUND %0
    $f10_d = COPY %1(s64)
    PseudoRET implicit $f10_d

...
---
name:            roundeven_f64
body:             |
  bb.1:
    liveins: $f10_d

    ; CHECK-LABEL: name: roundeven_f64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: $f10_d = COPY [[COPY]](s64)
    ; CHECK-NEXT: PseudoCALL target-flags(riscv-call) &roundeven, csr_ilp32d_lp64d, implicit-def $x1, implicit $f10_d, implicit-def $f10_d
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: $f10_d = COPY [[COPY1]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = G_INTRINSIC_ROUNDEVEN %0
    $f10_d = COPY %1(s64)
    PseudoRET implicit $f10_d

...
