# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv32 -mattr=+d -run-pass=legalizer %s -o - \
# RUN: | FileCheck %s
# RUN: llc -mtriple=riscv64 -mattr=+d -run-pass=legalizer %s -o - \
# RUN: | FileCheck %s

---
name:            fadd_f32
body:             |
  bb.0:
    liveins: $f10_f, $f11_f

    ; CHECK-LABEL: name: fadd_f32
    ; CHECK: liveins: $f10_f, $f11_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f11_f
    ; CHECK-NEXT: [[FADD:%[0-9]+]]:_(s32) = G_FADD [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_f = COPY [[FADD]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = COPY $f11_f
    %2:_(s32) = G_FADD %0, %1
    $f10_f = COPY %2(s32)
    PseudoRET implicit $f10_f

...
---
name:            fsub_f32
body:             |
  bb.0:
    liveins: $f10_f, $f11_f

    ; CHECK-LABEL: name: fsub_f32
    ; CHECK: liveins: $f10_f, $f11_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f11_f
    ; CHECK-NEXT: [[FSUB:%[0-9]+]]:_(s32) = G_FSUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_f = COPY [[FSUB]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = COPY $f11_f
    %2:_(s32) = G_FSUB %0, %1
    $f10_f = COPY %2(s32)
    PseudoRET implicit $f10_f

...
---
name:            fmul_f32
body:             |
  bb.0:
    liveins: $f10_f, $f11_f

    ; CHECK-LABEL: name: fmul_f32
    ; CHECK: liveins: $f10_f, $f11_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f11_f
    ; CHECK-NEXT: [[FMUL:%[0-9]+]]:_(s32) = G_FMUL [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_f = COPY [[FMUL]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = COPY $f11_f
    %2:_(s32) = G_FMUL %0, %1
    $f10_f = COPY %2(s32)
    PseudoRET implicit $f10_f

...
---
name:            fdiv_f32
body:             |
  bb.0:
    liveins: $f10_f, $f11_f

    ; CHECK-LABEL: name: fdiv_f32
    ; CHECK: liveins: $f10_f, $f11_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f11_f
    ; CHECK-NEXT: [[FDIV:%[0-9]+]]:_(s32) = G_FDIV [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_f = COPY [[FDIV]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = COPY $f11_f
    %2:_(s32) = G_FDIV %0, %1
    $f10_f = COPY %2(s32)
    PseudoRET implicit $f10_f

...
---
name:            fma_f32
body:             |
  bb.0:
    liveins: $f10_f, $f11_f, $f12_f

    ; CHECK-LABEL: name: fma_f32
    ; CHECK: liveins: $f10_f, $f11_f, $f12_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f11_f
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $f12_f
    ; CHECK-NEXT: [[FMA:%[0-9]+]]:_(s32) = G_FMA [[COPY]], [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: $f10_f = COPY [[FMA]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = COPY $f11_f
    %2:_(s32) = COPY $f12_f
    %3:_(s32) = G_FMA %0, %1, %2
    $f10_f = COPY %3(s32)
    PseudoRET implicit $f10_f

...
---
name:            fneg_f32
body:             |
  bb.0:
    liveins: $f10_f

    ; CHECK-LABEL: name: fneg_f32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: [[FNEG:%[0-9]+]]:_(s32) = G_FNEG [[COPY]]
    ; CHECK-NEXT: $f10_f = COPY [[FNEG]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = G_FNEG %0
    $f10_f = COPY %1(s32)
    PseudoRET implicit $f10_f

...
---
name:            fabs_f32
body:             |
  bb.0:
    liveins: $f10_f

    ; CHECK-LABEL: name: fabs_f32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: [[FABS:%[0-9]+]]:_(s32) = G_FABS [[COPY]]
    ; CHECK-NEXT: $f10_f = COPY [[FABS]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = G_FABS %0
    $f10_f = COPY %1(s32)
    PseudoRET implicit $f10_f

...
---
name:            fsqrt_f32
body:             |
  bb.0:
    liveins: $f10_f

    ; CHECK-LABEL: name: fsqrt_f32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: [[FSQRT:%[0-9]+]]:_(s32) = G_FSQRT [[COPY]]
    ; CHECK-NEXT: $f10_f = COPY [[FSQRT]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = G_FSQRT %0
    $f10_f = COPY %1(s32)
    PseudoRET implicit $f10_f

...
---
name:            fmaxnum_f32
body:             |
  bb.0:
    liveins: $f10_f, $f11_f

    ; CHECK-LABEL: name: fmaxnum_f32
    ; CHECK: liveins: $f10_f, $f11_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f11_f
    ; CHECK-NEXT: [[FMAXNUM:%[0-9]+]]:_(s32) = G_FMAXNUM [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_f = COPY [[FMAXNUM]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = COPY $f11_f
    %2:_(s32) = G_FMAXNUM %0, %1
    $f10_f = COPY %2(s32)
    PseudoRET implicit $f10_f

...
---
name:            fminnum_f32
body:             |
  bb.0:
    liveins: $f10_f, $f11_f

    ; CHECK-LABEL: name: fminnum_f32
    ; CHECK: liveins: $f10_f, $f11_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f11_f
    ; CHECK-NEXT: [[FMINNUM:%[0-9]+]]:_(s32) = G_FMINNUM [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_f = COPY [[FMINNUM]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = COPY $f11_f
    %2:_(s32) = G_FMINNUM %0, %1
    $f10_f = COPY %2(s32)
    PseudoRET implicit $f10_f

...
---
name:            fmaximumnum_f32
body:             |
  bb.0:
    liveins: $f10_f, $f11_f

    ; CHECK-LABEL: name: fmaximumnum_f32
    ; CHECK: liveins: $f10_f, $f11_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f11_f
    ; CHECK-NEXT: [[FMAXIMUMNUM:%[0-9]+]]:_(s32) = G_FMAXIMUMNUM [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_f = COPY [[FMAXIMUMNUM]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = COPY $f11_f
    %2:_(s32) = G_FMAXIMUMNUM %0, %1
    $f10_f = COPY %2(s32)
    PseudoRET implicit $f10_f

...
---
name:            fminimumnum_f32
body:             |
  bb.0:
    liveins: $f10_f, $f11_f

    ; CHECK-LABEL: name: fminimumnum_f32
    ; CHECK: liveins: $f10_f, $f11_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f11_f
    ; CHECK-NEXT: [[FMINIMUMNUM:%[0-9]+]]:_(s32) = G_FMINIMUMNUM [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_f = COPY [[FMINIMUMNUM]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = COPY $f11_f
    %2:_(s32) = G_FMINIMUMNUM %0, %1
    $f10_f = COPY %2(s32)
    PseudoRET implicit $f10_f

...
---
name:            fcopysign_f32_f32
body:             |
  bb.0:
    liveins: $f10_f, $f11_f

    ; CHECK-LABEL: name: fcopysign_f32_f32
    ; CHECK: liveins: $f10_f, $f11_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f11_f
    ; CHECK-NEXT: [[FCOPYSIGN:%[0-9]+]]:_(s32) = G_FCOPYSIGN [[COPY]], [[COPY1]](s32)
    ; CHECK-NEXT: $f10_f = COPY [[FCOPYSIGN]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = COPY $f11_f
    %2:_(s32) = G_FCOPYSIGN %0, %1
    $f10_f = COPY %2(s32)
    PseudoRET implicit $f10_f

...
---
name:            fcopysign_f32_f64
body:             |
  bb.0:
    liveins: $f10_f, $f11_d

    ; CHECK-LABEL: name: fcopysign_f32_f64
    ; CHECK: liveins: $f10_f, $f11_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f11_d
    ; CHECK-NEXT: [[FCOPYSIGN:%[0-9]+]]:_(s32) = G_FCOPYSIGN [[COPY]], [[COPY1]](s64)
    ; CHECK-NEXT: $f10_f = COPY [[FCOPYSIGN]](s32)
    ; CHECK-NEXT: PseudoRET implicit $f10_f
    %0:_(s32) = COPY $f10_f
    %1:_(s64) = COPY $f11_d
    %2:_(s32) = G_FCOPYSIGN %0, %1
    $f10_f = COPY %2(s32)
    PseudoRET implicit $f10_f

...
---
name:            fadd_f64
body:             |
  bb.0:
    liveins: $f10_d, $f11_d

    ; CHECK-LABEL: name: fadd_f64
    ; CHECK: liveins: $f10_d, $f11_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f11_d
    ; CHECK-NEXT: [[FADD:%[0-9]+]]:_(s64) = G_FADD [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_d = COPY [[FADD]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = COPY $f11_d
    %2:_(s64) = G_FADD %0, %1
    $f10_d = COPY %2(s64)
    PseudoRET implicit $f10_d

...
---
name:            fsub_f64
body:             |
  bb.0:
    liveins: $f10_d, $f11_d

    ; CHECK-LABEL: name: fsub_f64
    ; CHECK: liveins: $f10_d, $f11_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f11_d
    ; CHECK-NEXT: [[FSUB:%[0-9]+]]:_(s64) = G_FSUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_d = COPY [[FSUB]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = COPY $f11_d
    %2:_(s64) = G_FSUB %0, %1
    $f10_d = COPY %2(s64)
    PseudoRET implicit $f10_d

...
---
name:            fmul_f64
body:             |
  bb.0:
    liveins: $f10_d, $f11_d

    ; CHECK-LABEL: name: fmul_f64
    ; CHECK: liveins: $f10_d, $f11_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f11_d
    ; CHECK-NEXT: [[FMUL:%[0-9]+]]:_(s64) = G_FMUL [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_d = COPY [[FMUL]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = COPY $f11_d
    %2:_(s64) = G_FMUL %0, %1
    $f10_d = COPY %2(s64)
    PseudoRET implicit $f10_d

...
---
name:            fdiv_f64
body:             |
  bb.0:
    liveins: $f10_d, $f11_d

    ; CHECK-LABEL: name: fdiv_f64
    ; CHECK: liveins: $f10_d, $f11_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f11_d
    ; CHECK-NEXT: [[FDIV:%[0-9]+]]:_(s64) = G_FDIV [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_d = COPY [[FDIV]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = COPY $f11_d
    %2:_(s64) = G_FDIV %0, %1
    $f10_d = COPY %2(s64)
    PseudoRET implicit $f10_d

...
---
name:            fma_f64
body:             |
  bb.0:
    liveins: $f10_d, $f11_d, $f12_d

    ; CHECK-LABEL: name: fma_f64
    ; CHECK: liveins: $f10_d, $f11_d, $f12_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f11_d
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s64) = COPY $f12_d
    ; CHECK-NEXT: [[FMA:%[0-9]+]]:_(s64) = G_FMA [[COPY]], [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: $f10_d = COPY [[FMA]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = COPY $f11_d
    %2:_(s64) = COPY $f12_d
    %3:_(s64) = G_FMA %0, %1, %2
    $f10_d = COPY %3(s64)
    PseudoRET implicit $f10_d

...
---
name:            fneg_f64
body:             |
  bb.0:
    liveins: $f10_d

    ; CHECK-LABEL: name: fneg_f64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: [[FNEG:%[0-9]+]]:_(s64) = G_FNEG [[COPY]]
    ; CHECK-NEXT: $f10_d = COPY [[FNEG]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = G_FNEG %0
    $f10_d = COPY %1(s64)
    PseudoRET implicit $f10_d

...
---
name:            fabs_f64
body:             |
  bb.0:
    liveins: $f10_d

    ; CHECK-LABEL: name: fabs_f64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: [[FABS:%[0-9]+]]:_(s64) = G_FABS [[COPY]]
    ; CHECK-NEXT: $f10_d = COPY [[FABS]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = G_FABS %0
    $f10_d = COPY %1(s64)
    PseudoRET implicit $f10_d

...
---
name:            fsqrt_f64
body:             |
  bb.0:
    liveins: $f10_d

    ; CHECK-LABEL: name: fsqrt_f64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: [[FSQRT:%[0-9]+]]:_(s64) = G_FSQRT [[COPY]]
    ; CHECK-NEXT: $f10_d = COPY [[FSQRT]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = G_FSQRT %0
    $f10_d = COPY %1(s64)
    PseudoRET implicit $f10_d

...
---
name:            fmaxnum_f64
body:             |
  bb.0:
    liveins: $f10_d, $f11_d

    ; CHECK-LABEL: name: fmaxnum_f64
    ; CHECK: liveins: $f10_d, $f11_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f11_d
    ; CHECK-NEXT: [[FMAXNUM:%[0-9]+]]:_(s64) = G_FMAXNUM [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_d = COPY [[FMAXNUM]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = COPY $f11_d
    %2:_(s64) = G_FMAXNUM %0, %1
    $f10_d = COPY %2(s64)
    PseudoRET implicit $f10_d

...
---
name:            fminnum_f64
body:             |
  bb.0:
    liveins: $f10_d, $f11_d

    ; CHECK-LABEL: name: fminnum_f64
    ; CHECK: liveins: $f10_d, $f11_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f11_d
    ; CHECK-NEXT: [[FMINNUM:%[0-9]+]]:_(s64) = G_FMINNUM [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_d = COPY [[FMINNUM]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = COPY $f11_d
    %2:_(s64) = G_FMINNUM %0, %1
    $f10_d = COPY %2(s64)
    PseudoRET implicit $f10_d

...
---
name:            fmaximumnum_f64
body:             |
  bb.0:
    liveins: $f10_d, $f11_d

    ; CHECK-LABEL: name: fmaximumnum_f64
    ; CHECK: liveins: $f10_d, $f11_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f11_d
    ; CHECK-NEXT: [[FMAXIMUMNUM:%[0-9]+]]:_(s64) = G_FMAXIMUMNUM [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_d = COPY [[FMAXIMUMNUM]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = COPY $f11_d
    %2:_(s64) = G_FMAXIMUMNUM %0, %1
    $f10_d = COPY %2(s64)
    PseudoRET implicit $f10_d

...
---
name:            fminimumnum_f64
body:             |
  bb.0:
    liveins: $f10_d, $f11_d

    ; CHECK-LABEL: name: fminimumnum_f64
    ; CHECK: liveins: $f10_d, $f11_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f11_d
    ; CHECK-NEXT: [[FMINIMUMNUM:%[0-9]+]]:_(s64) = G_FMINIMUMNUM [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $f10_d = COPY [[FMINIMUMNUM]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = COPY $f11_d
    %2:_(s64) = G_FMINIMUMNUM %0, %1
    $f10_d = COPY %2(s64)
    PseudoRET implicit $f10_d

...
---
name:            fcopysign_f64_f64
body:             |
  bb.0:
    liveins: $f10_d, $f11_d

    ; CHECK-LABEL: name: fcopysign_f64_f64
    ; CHECK: liveins: $f10_d, $f11_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $f11_d
    ; CHECK-NEXT: [[FCOPYSIGN:%[0-9]+]]:_(s64) = G_FCOPYSIGN [[COPY]], [[COPY1]](s64)
    ; CHECK-NEXT: $f10_d = COPY [[FCOPYSIGN]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = COPY $f11_d
    %2:_(s64) = G_FCOPYSIGN %0, %1
    $f10_d = COPY %2(s64)
    PseudoRET implicit $f10_d

...
---
name:            fcopysign_f64_f32
body:             |
  bb.0:
    liveins: $f10_d, $f11_f

    ; CHECK-LABEL: name: fcopysign_f64_f32
    ; CHECK: liveins: $f10_d, $f11_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $f11_f
    ; CHECK-NEXT: [[FCOPYSIGN:%[0-9]+]]:_(s64) = G_FCOPYSIGN [[COPY]], [[COPY1]](s32)
    ; CHECK-NEXT: $f10_d = COPY [[FCOPYSIGN]](s64)
    ; CHECK-NEXT: PseudoRET implicit $f10_d
    %0:_(s64) = COPY $f10_d
    %1:_(s32) = COPY $f11_f
    %2:_(s64) = G_FCOPYSIGN %0, %1
    $f10_d = COPY %2(s64)
    PseudoRET implicit $f10_d

...
