# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv32 -mattr=+zfh -run-pass=legalizer %s -o - \
# RUN: | FileCheck %s

---
name:            fcmp_oeq_f16
body:             |
  bb.1:
    liveins: $f10_h, $f11_h

    ; CHECK-LABEL: name: fcmp_oeq_f16
    ; CHECK: liveins: $f10_h, $f11_h
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s16) = COPY $f11_h
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:_(s32) = G_FCMP floatpred(oeq), [[COPY]](s16), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = COPY $f11_h
    %2:_(s1) = G_FCMP floatpred(oeq), %0(s16), %1
    %3:_(s32) = G_ANYEXT %2(s1)
    $x10 = COPY %3(s32)
    PseudoRET implicit $x10

...
---
name:            fcmp_ogt_f16
body:             |
  bb.1:
    liveins: $f10_h, $f11_h

    ; CHECK-LABEL: name: fcmp_ogt_f16
    ; CHECK: liveins: $f10_h, $f11_h
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s16) = COPY $f11_h
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:_(s32) = G_FCMP floatpred(ogt), [[COPY]](s16), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = COPY $f11_h
    %2:_(s1) = G_FCMP floatpred(ogt), %0(s16), %1
    %3:_(s32) = G_ANYEXT %2(s1)
    $x10 = COPY %3(s32)
    PseudoRET implicit $x10

...
---
name:            fcmp_oge_f16
body:             |
  bb.1:
    liveins: $f10_h, $f11_h

    ; CHECK-LABEL: name: fcmp_oge_f16
    ; CHECK: liveins: $f10_h, $f11_h
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s16) = COPY $f11_h
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:_(s32) = G_FCMP floatpred(oge), [[COPY]](s16), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = COPY $f11_h
    %2:_(s1) = G_FCMP floatpred(oge), %0(s16), %1
    %3:_(s32) = G_ANYEXT %2(s1)
    $x10 = COPY %3(s32)
    PseudoRET implicit $x10

...
---
name:            fcmp_olt_f16
body:             |
  bb.1:
    liveins: $f10_h, $f11_h

    ; CHECK-LABEL: name: fcmp_olt_f16
    ; CHECK: liveins: $f10_h, $f11_h
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s16) = COPY $f11_h
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:_(s32) = G_FCMP floatpred(olt), [[COPY]](s16), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = COPY $f11_h
    %2:_(s1) = G_FCMP floatpred(olt), %0(s16), %1
    %3:_(s32) = G_ANYEXT %2(s1)
    $x10 = COPY %3(s32)
    PseudoRET implicit $x10

...
---
name:            fcmp_ole_f16
body:             |
  bb.1:
    liveins: $f10_h, $f11_h

    ; CHECK-LABEL: name: fcmp_ole_f16
    ; CHECK: liveins: $f10_h, $f11_h
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s16) = COPY $f11_h
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:_(s32) = G_FCMP floatpred(ole), [[COPY]](s16), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = COPY $f11_h
    %2:_(s1) = G_FCMP floatpred(ole), %0(s16), %1
    %3:_(s32) = G_ANYEXT %2(s1)
    $x10 = COPY %3(s32)
    PseudoRET implicit $x10

...
---
name:            fcmp_one_f16
body:             |
  bb.1:
    liveins: $f10_h, $f11_h

    ; CHECK-LABEL: name: fcmp_one_f16
    ; CHECK: liveins: $f10_h, $f11_h
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s16) = COPY $f11_h
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:_(s32) = G_FCMP floatpred(one), [[COPY]](s16), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = COPY $f11_h
    %2:_(s1) = G_FCMP floatpred(one), %0(s16), %1
    %3:_(s32) = G_ANYEXT %2(s1)
    $x10 = COPY %3(s32)
    PseudoRET implicit $x10

...
---
name:            fcmp_ord_f16
body:             |
  bb.1:
    liveins: $f10_h, $f11_h

    ; CHECK-LABEL: name: fcmp_ord_f16
    ; CHECK: liveins: $f10_h, $f11_h
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s16) = COPY $f11_h
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:_(s32) = G_FCMP floatpred(ord), [[COPY]](s16), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = COPY $f11_h
    %2:_(s1) = G_FCMP floatpred(ord), %0(s16), %1
    %3:_(s32) = G_ANYEXT %2(s1)
    $x10 = COPY %3(s32)
    PseudoRET implicit $x10

...
---
name:            fcmp_ueq_f16
body:             |
  bb.1:
    liveins: $f10_h, $f11_h

    ; CHECK-LABEL: name: fcmp_ueq_f16
    ; CHECK: liveins: $f10_h, $f11_h
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s16) = COPY $f11_h
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:_(s32) = G_FCMP floatpred(ueq), [[COPY]](s16), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = COPY $f11_h
    %2:_(s1) = G_FCMP floatpred(ueq), %0(s16), %1
    %3:_(s32) = G_ANYEXT %2(s1)
    $x10 = COPY %3(s32)
    PseudoRET implicit $x10

...
---
name:            fcmp_ugt_f16
body:             |
  bb.1:
    liveins: $f10_h, $f11_h

    ; CHECK-LABEL: name: fcmp_ugt_f16
    ; CHECK: liveins: $f10_h, $f11_h
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s16) = COPY $f11_h
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:_(s32) = G_FCMP floatpred(ugt), [[COPY]](s16), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = COPY $f11_h
    %2:_(s1) = G_FCMP floatpred(ugt), %0(s16), %1
    %3:_(s32) = G_ANYEXT %2(s1)
    $x10 = COPY %3(s32)
    PseudoRET implicit $x10

...
---
name:            fcmp_uge_f16
body:             |
  bb.1:
    liveins: $f10_h, $f11_h

    ; CHECK-LABEL: name: fcmp_uge_f16
    ; CHECK: liveins: $f10_h, $f11_h
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s16) = COPY $f11_h
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:_(s32) = G_FCMP floatpred(uge), [[COPY]](s16), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = COPY $f11_h
    %2:_(s1) = G_FCMP floatpred(uge), %0(s16), %1
    %3:_(s32) = G_ANYEXT %2(s1)
    $x10 = COPY %3(s32)
    PseudoRET implicit $x10

...
---
name:            fcmp_ult_f16
body:             |
  bb.1:
    liveins: $f10_h, $f11_h

    ; CHECK-LABEL: name: fcmp_ult_f16
    ; CHECK: liveins: $f10_h, $f11_h
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s16) = COPY $f11_h
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:_(s32) = G_FCMP floatpred(ult), [[COPY]](s16), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = COPY $f11_h
    %2:_(s1) = G_FCMP floatpred(ult), %0(s16), %1
    %3:_(s32) = G_ANYEXT %2(s1)
    $x10 = COPY %3(s32)
    PseudoRET implicit $x10

...
---
name:            fcmp_ule_f16
body:             |
  bb.1:
    liveins: $f10_h, $f11_h

    ; CHECK-LABEL: name: fcmp_ule_f16
    ; CHECK: liveins: $f10_h, $f11_h
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s16) = COPY $f11_h
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:_(s32) = G_FCMP floatpred(ule), [[COPY]](s16), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = COPY $f11_h
    %2:_(s1) = G_FCMP floatpred(ule), %0(s16), %1
    %3:_(s32) = G_ANYEXT %2(s1)
    $x10 = COPY %3(s32)
    PseudoRET implicit $x10

...
---
name:            fcmp_une_f16
body:             |
  bb.1:
    liveins: $f10_h, $f11_h

    ; CHECK-LABEL: name: fcmp_une_f16
    ; CHECK: liveins: $f10_h, $f11_h
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s16) = COPY $f11_h
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:_(s32) = G_FCMP floatpred(une), [[COPY]](s16), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = COPY $f11_h
    %2:_(s1) = G_FCMP floatpred(une), %0(s16), %1
    %3:_(s32) = G_ANYEXT %2(s1)
    $x10 = COPY %3(s32)
    PseudoRET implicit $x10

...
---
name:            fcmp_uno_f16
body:             |
  bb.1:
    liveins: $f10_h, $f11_h

    ; CHECK-LABEL: name: fcmp_uno_f16
    ; CHECK: liveins: $f10_h, $f11_h
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s16) = COPY $f11_h
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:_(s32) = G_FCMP floatpred(uno), [[COPY]](s16), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = COPY $f11_h
    %2:_(s1) = G_FCMP floatpred(uno), %0(s16), %1
    %3:_(s32) = G_ANYEXT %2(s1)
    $x10 = COPY %3(s32)
    PseudoRET implicit $x10

...
