# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 3
# RUN: llc -mtriple=riscv32 -mattr=+d -run-pass=legalizer %s -o - \
# RUN: | FileCheck %s

---
name:            is_fpclass_f32
body:             |
  bb.1:
    liveins: $f10_f

    ; CHECK-LABEL: name: is_fpclass_f32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $f10_f
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 152
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[FCLASS:%[0-9]+]]:_(s32) = G_FCLASS [[COPY]](s32)
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[FCLASS]], [[C]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(ne), [[AND]](s32), [[C1]]
    ; CHECK-NEXT: $x10 = COPY [[ICMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s32) = COPY $f10_f
    %1:_(s1) = G_IS_FPCLASS %0(s32), 608
    %2:_(s32) = G_ANYEXT %1(s1)
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            is_fpclass_f64
body:             |
  bb.1:
    liveins: $f10_d

    ; CHECK-LABEL: name: is_fpclass_f64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $f10_d
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 152
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[FCLASS:%[0-9]+]]:_(s32) = G_FCLASS [[COPY]](s64)
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[FCLASS]], [[C]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(ne), [[AND]](s32), [[C1]]
    ; CHECK-NEXT: $x10 = COPY [[ICMP]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $f10_d
    %1:_(s1) = G_IS_FPCLASS %0(s64), 608
    %2:_(s32) = G_ANYEXT %1(s1)
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            is_fpclass_f128
body:             |
  bb.1:
    ; CHECK-LABEL: name: is_fpclass_f128
    ; CHECK: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 2147483647
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 2147418112
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[DEF]], [[C]]
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[DEF]], [[C]]
    ; CHECK-NEXT: [[AND2:%[0-9]+]]:_(s32) = G_AND [[DEF]], [[C]]
    ; CHECK-NEXT: [[AND3:%[0-9]+]]:_(s32) = G_AND [[DEF]], [[C1]]
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[AND]], [[C2]]
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[AND1]], [[C2]]
    ; CHECK-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[AND2]], [[C2]]
    ; CHECK-NEXT: [[XOR3:%[0-9]+]]:_(s32) = G_XOR [[AND3]], [[C2]]
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[XOR]], [[XOR1]]
    ; CHECK-NEXT: [[OR1:%[0-9]+]]:_(s32) = G_OR [[OR]], [[XOR2]]
    ; CHECK-NEXT: [[OR2:%[0-9]+]]:_(s32) = G_OR [[OR1]], [[XOR3]]
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[OR2]](s32), [[C2]]
    ; CHECK-NEXT: [[OR3:%[0-9]+]]:_(s32) = G_OR [[C4]], [[ICMP]]
    ; CHECK-NEXT: [[XOR4:%[0-9]+]]:_(s32) = G_XOR [[DEF]], [[C2]]
    ; CHECK-NEXT: [[XOR5:%[0-9]+]]:_(s32) = G_XOR [[DEF]], [[C2]]
    ; CHECK-NEXT: [[XOR6:%[0-9]+]]:_(s32) = G_XOR [[DEF]], [[C2]]
    ; CHECK-NEXT: [[XOR7:%[0-9]+]]:_(s32) = G_XOR [[DEF]], [[C3]]
    ; CHECK-NEXT: [[OR4:%[0-9]+]]:_(s32) = G_OR [[XOR4]], [[XOR5]]
    ; CHECK-NEXT: [[OR5:%[0-9]+]]:_(s32) = G_OR [[OR4]], [[XOR6]]
    ; CHECK-NEXT: [[OR6:%[0-9]+]]:_(s32) = G_OR [[OR5]], [[XOR7]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[OR6]](s32), [[C2]]
    ; CHECK-NEXT: [[OR7:%[0-9]+]]:_(s32) = G_OR [[OR3]], [[ICMP1]]
    ; CHECK-NEXT: $x10 = COPY [[OR7]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s128) = G_IMPLICIT_DEF
    %1:_(s1) = G_IS_FPCLASS %0(s128), 608
    %2:_(s32) = G_ANYEXT %1(s1)
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
