! RUN: %flang_fc1 -fdebug-dump-symbols %s 2>&1 | FileCheck --dump-input-context=500 %s
!CHECK: Global scope: size=0 alignment=1 sourceRange=0 bytes
!CHECK: IntrinsicModules scope: size=0 alignment=1 sourceRange=0 bytes
!CHECK: Module scope: __fortran_builtins
!CHECK: Module scope: __cuda_builtins size=0 alignment=1
!CHECK: Module scope: __fortran_type_info
!CHECK: Module scope: m size=0 alignment=1
!CHECK: Subprogram scope: devsubr size=0 alignment=1
module m
  implicit none
 contains
  attributes(device) subroutine devsubr()
  !CHECK: blockdim: Use from blockdim in cudadevice
  !CHECK: blockidx: Use from blockidx in cudadevice
  !CHECK: griddim: Use from griddim in cudadevice
  !CHECK: threadidx: Use from threadidx in cudadevice
  !CHECK: warpsize: Use from warpsize in cudadevice
  end subroutine
end module
