; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=pre-isel-intrinsic-lowering -mtriple=riscv32 -S < %s | FileCheck %s --check-prefix=RV32
; RUN: opt -passes=pre-isel-intrinsic-lowering -mtriple=riscv64 -S < %s | FileCheck %s --check-prefix=RV64

define <vscale x 4 x float> @scalable_vec_atan2(<vscale x 4 x float> %a, <vscale x 4 x float> %b) {
; RV32-LABEL: define <vscale x 4 x float> @scalable_vec_atan2(
; RV32-SAME: <vscale x 4 x float> [[A:%.*]], <vscale x 4 x float> [[B:%.*]]) {
; RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.vscale.i32()
; RV32-NEXT:    [[TMP2:%.*]] = mul nuw i32 [[TMP1]], 4
; RV32-NEXT:    br label %[[BB3:.*]]
; RV32:       [[BB3]]:
; RV32-NEXT:    [[TMP4:%.*]] = phi i32 [ 0, [[TMP0:%.*]] ], [ [[TMP10:%.*]], %[[BB3]] ]
; RV32-NEXT:    [[TMP5:%.*]] = phi <vscale x 4 x float> [ [[A]], [[TMP0]] ], [ [[TMP9:%.*]], %[[BB3]] ]
; RV32-NEXT:    [[TMP6:%.*]] = extractelement <vscale x 4 x float> [[TMP5]], i32 [[TMP4]]
; RV32-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 4 x float> [[B]], i32 [[TMP4]]
; RV32-NEXT:    [[TMP8:%.*]] = call float @llvm.atan2.f32(float [[TMP6]], float [[TMP7]])
; RV32-NEXT:    [[TMP9]] = insertelement <vscale x 4 x float> [[TMP5]], float [[TMP8]], i32 [[TMP4]]
; RV32-NEXT:    [[TMP10]] = add i32 [[TMP4]], 1
; RV32-NEXT:    [[TMP11:%.*]] = icmp eq i32 [[TMP10]], [[TMP2]]
; RV32-NEXT:    br i1 [[TMP11]], label %[[BB12:.*]], label %[[BB3]]
; RV32:       [[BB12]]:
; RV32-NEXT:    ret <vscale x 4 x float> [[TMP9]]
;
; RV64-LABEL: define <vscale x 4 x float> @scalable_vec_atan2(
; RV64-SAME: <vscale x 4 x float> [[A:%.*]], <vscale x 4 x float> [[B:%.*]]) {
; RV64-NEXT:    [[TMP1:%.*]] = call i64 @llvm.vscale.i64()
; RV64-NEXT:    [[TMP2:%.*]] = mul nuw i64 [[TMP1]], 4
; RV64-NEXT:    br label %[[BB3:.*]]
; RV64:       [[BB3]]:
; RV64-NEXT:    [[TMP4:%.*]] = phi i64 [ 0, [[TMP0:%.*]] ], [ [[TMP10:%.*]], %[[BB3]] ]
; RV64-NEXT:    [[TMP5:%.*]] = phi <vscale x 4 x float> [ [[A]], [[TMP0]] ], [ [[TMP9:%.*]], %[[BB3]] ]
; RV64-NEXT:    [[TMP6:%.*]] = extractelement <vscale x 4 x float> [[TMP5]], i64 [[TMP4]]
; RV64-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 4 x float> [[B]], i64 [[TMP4]]
; RV64-NEXT:    [[TMP8:%.*]] = call float @llvm.atan2.f32(float [[TMP6]], float [[TMP7]])
; RV64-NEXT:    [[TMP9]] = insertelement <vscale x 4 x float> [[TMP5]], float [[TMP8]], i64 [[TMP4]]
; RV64-NEXT:    [[TMP10]] = add i64 [[TMP4]], 1
; RV64-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[TMP10]], [[TMP2]]
; RV64-NEXT:    br i1 [[TMP11]], label %[[BB12:.*]], label %[[BB3]]
; RV64:       [[BB12]]:
; RV64-NEXT:    ret <vscale x 4 x float> [[TMP9]]
;
  %output = call <vscale x 4 x float> @llvm.atan2.nxv4f32(<vscale x 4 x float> %a, <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %output
}

define <vscale x 4 x float> @scalable_vec_pow(<vscale x 4 x float> %a, <vscale x 4 x float> %b) {
; RV32-LABEL: define <vscale x 4 x float> @scalable_vec_pow(
; RV32-SAME: <vscale x 4 x float> [[A:%.*]], <vscale x 4 x float> [[B:%.*]]) {
; RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.vscale.i32()
; RV32-NEXT:    [[TMP2:%.*]] = mul nuw i32 [[TMP1]], 4
; RV32-NEXT:    br label %[[BB3:.*]]
; RV32:       [[BB3]]:
; RV32-NEXT:    [[TMP4:%.*]] = phi i32 [ 0, [[TMP0:%.*]] ], [ [[TMP10:%.*]], %[[BB3]] ]
; RV32-NEXT:    [[TMP5:%.*]] = phi <vscale x 4 x float> [ [[A]], [[TMP0]] ], [ [[TMP9:%.*]], %[[BB3]] ]
; RV32-NEXT:    [[TMP6:%.*]] = extractelement <vscale x 4 x float> [[TMP5]], i32 [[TMP4]]
; RV32-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 4 x float> [[B]], i32 [[TMP4]]
; RV32-NEXT:    [[TMP8:%.*]] = call float @llvm.pow.f32(float [[TMP6]], float [[TMP7]])
; RV32-NEXT:    [[TMP9]] = insertelement <vscale x 4 x float> [[TMP5]], float [[TMP8]], i32 [[TMP4]]
; RV32-NEXT:    [[TMP10]] = add i32 [[TMP4]], 1
; RV32-NEXT:    [[TMP11:%.*]] = icmp eq i32 [[TMP10]], [[TMP2]]
; RV32-NEXT:    br i1 [[TMP11]], label %[[BB12:.*]], label %[[BB3]]
; RV32:       [[BB12]]:
; RV32-NEXT:    ret <vscale x 4 x float> [[TMP9]]
;
; RV64-LABEL: define <vscale x 4 x float> @scalable_vec_pow(
; RV64-SAME: <vscale x 4 x float> [[A:%.*]], <vscale x 4 x float> [[B:%.*]]) {
; RV64-NEXT:    [[TMP1:%.*]] = call i64 @llvm.vscale.i64()
; RV64-NEXT:    [[TMP2:%.*]] = mul nuw i64 [[TMP1]], 4
; RV64-NEXT:    br label %[[BB3:.*]]
; RV64:       [[BB3]]:
; RV64-NEXT:    [[TMP4:%.*]] = phi i64 [ 0, [[TMP0:%.*]] ], [ [[TMP10:%.*]], %[[BB3]] ]
; RV64-NEXT:    [[TMP5:%.*]] = phi <vscale x 4 x float> [ [[A]], [[TMP0]] ], [ [[TMP9:%.*]], %[[BB3]] ]
; RV64-NEXT:    [[TMP6:%.*]] = extractelement <vscale x 4 x float> [[TMP5]], i64 [[TMP4]]
; RV64-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 4 x float> [[B]], i64 [[TMP4]]
; RV64-NEXT:    [[TMP8:%.*]] = call float @llvm.pow.f32(float [[TMP6]], float [[TMP7]])
; RV64-NEXT:    [[TMP9]] = insertelement <vscale x 4 x float> [[TMP5]], float [[TMP8]], i64 [[TMP4]]
; RV64-NEXT:    [[TMP10]] = add i64 [[TMP4]], 1
; RV64-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[TMP10]], [[TMP2]]
; RV64-NEXT:    br i1 [[TMP11]], label %[[BB12:.*]], label %[[BB3]]
; RV64:       [[BB12]]:
; RV64-NEXT:    ret <vscale x 4 x float> [[TMP9]]
;
  %output = call <vscale x 4 x float> @llvm.pow.nxv4f32(<vscale x 4 x float> %a, <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %output
}

define <vscale x 4 x float> @scalable_vec_ldexp(<vscale x 4 x float> %a, <vscale x 4 x i32> %b) {
; RV32-LABEL: define <vscale x 4 x float> @scalable_vec_ldexp(
; RV32-SAME: <vscale x 4 x float> [[A:%.*]], <vscale x 4 x i32> [[B:%.*]]) {
; RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.vscale.i32()
; RV32-NEXT:    [[TMP2:%.*]] = mul nuw i32 [[TMP1]], 4
; RV32-NEXT:    br label %[[BB3:.*]]
; RV32:       [[BB3]]:
; RV32-NEXT:    [[TMP4:%.*]] = phi i32 [ 0, [[TMP0:%.*]] ], [ [[TMP10:%.*]], %[[BB3]] ]
; RV32-NEXT:    [[TMP5:%.*]] = phi <vscale x 4 x float> [ [[A]], [[TMP0]] ], [ [[TMP9:%.*]], %[[BB3]] ]
; RV32-NEXT:    [[TMP6:%.*]] = extractelement <vscale x 4 x float> [[TMP5]], i32 [[TMP4]]
; RV32-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 4 x i32> [[B]], i32 [[TMP4]]
; RV32-NEXT:    [[TMP8:%.*]] = call float @llvm.ldexp.f32.i32(float [[TMP6]], i32 [[TMP7]])
; RV32-NEXT:    [[TMP9]] = insertelement <vscale x 4 x float> [[TMP5]], float [[TMP8]], i32 [[TMP4]]
; RV32-NEXT:    [[TMP10]] = add i32 [[TMP4]], 1
; RV32-NEXT:    [[TMP11:%.*]] = icmp eq i32 [[TMP10]], [[TMP2]]
; RV32-NEXT:    br i1 [[TMP11]], label %[[BB12:.*]], label %[[BB3]]
; RV32:       [[BB12]]:
; RV32-NEXT:    ret <vscale x 4 x float> [[TMP9]]
;
; RV64-LABEL: define <vscale x 4 x float> @scalable_vec_ldexp(
; RV64-SAME: <vscale x 4 x float> [[A:%.*]], <vscale x 4 x i32> [[B:%.*]]) {
; RV64-NEXT:    [[TMP1:%.*]] = call i64 @llvm.vscale.i64()
; RV64-NEXT:    [[TMP2:%.*]] = mul nuw i64 [[TMP1]], 4
; RV64-NEXT:    br label %[[BB3:.*]]
; RV64:       [[BB3]]:
; RV64-NEXT:    [[TMP4:%.*]] = phi i64 [ 0, [[TMP0:%.*]] ], [ [[TMP10:%.*]], %[[BB3]] ]
; RV64-NEXT:    [[TMP5:%.*]] = phi <vscale x 4 x float> [ [[A]], [[TMP0]] ], [ [[TMP9:%.*]], %[[BB3]] ]
; RV64-NEXT:    [[TMP6:%.*]] = extractelement <vscale x 4 x float> [[TMP5]], i64 [[TMP4]]
; RV64-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 4 x i32> [[B]], i64 [[TMP4]]
; RV64-NEXT:    [[TMP8:%.*]] = call float @llvm.ldexp.f32.i32(float [[TMP6]], i32 [[TMP7]])
; RV64-NEXT:    [[TMP9]] = insertelement <vscale x 4 x float> [[TMP5]], float [[TMP8]], i64 [[TMP4]]
; RV64-NEXT:    [[TMP10]] = add i64 [[TMP4]], 1
; RV64-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[TMP10]], [[TMP2]]
; RV64-NEXT:    br i1 [[TMP11]], label %[[BB12:.*]], label %[[BB3]]
; RV64:       [[BB12]]:
; RV64-NEXT:    ret <vscale x 4 x float> [[TMP9]]
;
  %output = call <vscale x 4 x float> @llvm.ldexp.nxv4f32.nxv4i32(<vscale x 4 x float> %a, <vscale x 4 x i32> %b)
  ret <vscale x 4 x float> %output
}

define <vscale x 4 x float> @scalable_vec_powi(<vscale x 4 x float> %a, <vscale x 4 x i32> %b) {
; RV32-LABEL: define <vscale x 4 x float> @scalable_vec_powi(
; RV32-SAME: <vscale x 4 x float> [[A:%.*]], <vscale x 4 x i32> [[B:%.*]]) {
; RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.vscale.i32()
; RV32-NEXT:    [[TMP2:%.*]] = mul nuw i32 [[TMP1]], 4
; RV32-NEXT:    br label %[[BB3:.*]]
; RV32:       [[BB3]]:
; RV32-NEXT:    [[TMP4:%.*]] = phi i32 [ 0, [[TMP0:%.*]] ], [ [[TMP10:%.*]], %[[BB3]] ]
; RV32-NEXT:    [[TMP5:%.*]] = phi <vscale x 4 x float> [ [[A]], [[TMP0]] ], [ [[TMP9:%.*]], %[[BB3]] ]
; RV32-NEXT:    [[TMP6:%.*]] = extractelement <vscale x 4 x float> [[TMP5]], i32 [[TMP4]]
; RV32-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 4 x i32> [[B]], i32 [[TMP4]]
; RV32-NEXT:    [[TMP8:%.*]] = call float @llvm.powi.f32.i32(float [[TMP6]], i32 [[TMP7]])
; RV32-NEXT:    [[TMP9]] = insertelement <vscale x 4 x float> [[TMP5]], float [[TMP8]], i32 [[TMP4]]
; RV32-NEXT:    [[TMP10]] = add i32 [[TMP4]], 1
; RV32-NEXT:    [[TMP11:%.*]] = icmp eq i32 [[TMP10]], [[TMP2]]
; RV32-NEXT:    br i1 [[TMP11]], label %[[BB12:.*]], label %[[BB3]]
; RV32:       [[BB12]]:
; RV32-NEXT:    ret <vscale x 4 x float> [[TMP9]]
;
; RV64-LABEL: define <vscale x 4 x float> @scalable_vec_powi(
; RV64-SAME: <vscale x 4 x float> [[A:%.*]], <vscale x 4 x i32> [[B:%.*]]) {
; RV64-NEXT:    [[TMP1:%.*]] = call i64 @llvm.vscale.i64()
; RV64-NEXT:    [[TMP2:%.*]] = mul nuw i64 [[TMP1]], 4
; RV64-NEXT:    br label %[[BB3:.*]]
; RV64:       [[BB3]]:
; RV64-NEXT:    [[TMP4:%.*]] = phi i64 [ 0, [[TMP0:%.*]] ], [ [[TMP10:%.*]], %[[BB3]] ]
; RV64-NEXT:    [[TMP5:%.*]] = phi <vscale x 4 x float> [ [[A]], [[TMP0]] ], [ [[TMP9:%.*]], %[[BB3]] ]
; RV64-NEXT:    [[TMP6:%.*]] = extractelement <vscale x 4 x float> [[TMP5]], i64 [[TMP4]]
; RV64-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 4 x i32> [[B]], i64 [[TMP4]]
; RV64-NEXT:    [[TMP8:%.*]] = call float @llvm.powi.f32.i32(float [[TMP6]], i32 [[TMP7]])
; RV64-NEXT:    [[TMP9]] = insertelement <vscale x 4 x float> [[TMP5]], float [[TMP8]], i64 [[TMP4]]
; RV64-NEXT:    [[TMP10]] = add i64 [[TMP4]], 1
; RV64-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[TMP10]], [[TMP2]]
; RV64-NEXT:    br i1 [[TMP11]], label %[[BB12:.*]], label %[[BB3]]
; RV64:       [[BB12]]:
; RV64-NEXT:    ret <vscale x 4 x float> [[TMP9]]
;
  %output = call <vscale x 4 x float> @llvm.powi.nxv4f32.nxv4i32(<vscale x 4 x float> %a, <vscale x 4 x i32> %b)
  ret <vscale x 4 x float> %output
}
