; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=attributor -attributor-manifest-internal < %s | FileCheck %s

define half @ret_log_f16(half %arg) #1 {
; CHECK-LABEL: define nofpclass(nzero sub) half @ret_log_f16(
; CHECK-SAME: half [[ARG:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nzero sub) half @llvm.amdgcn.log.f16(half [[ARG]]) #[[ATTR6:[0-9]+]]
; CHECK-NEXT:    ret half [[CALL]]
;
  %call = call half @llvm.amdgcn.log.f16(half %arg)
  ret half %call
}

define float @ret_log_f32(float %arg) #1 {
; CHECK-LABEL: define nofpclass(nzero sub) float @ret_log_f32(
; CHECK-SAME: float [[ARG:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nzero sub) float @llvm.amdgcn.log.f32(float [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_noinf(float nofpclass(inf) %arg) #1 {
; CHECK-LABEL: define nofpclass(pinf nzero sub) float @ret_log_noinf(
; CHECK-SAME: float nofpclass(inf) [[ARG:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(pinf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(inf) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_noneg(float nofpclass(ninf nsub nnorm) %arg) #1 {
; CHECK-LABEL: define nofpclass(nzero sub) float @ret_log_noneg(
; CHECK-SAME: float nofpclass(ninf nsub nnorm) [[ARG:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(ninf nsub nnorm) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_noneg_nonan(float nofpclass(nan ninf nsub nnorm) %arg) #1 {
; CHECK-LABEL: define nofpclass(nan nzero sub) float @ret_log_noneg_nonan(
; CHECK-SAME: float nofpclass(nan ninf nsub nnorm) [[ARG:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nan nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(nan ninf nsub nnorm) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_noinf_noneg(float nofpclass(inf nsub nnorm) %arg) #1 {
; CHECK-LABEL: define nofpclass(pinf nzero sub) float @ret_log_noinf_noneg(
; CHECK-SAME: float nofpclass(inf nsub nnorm) [[ARG:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(pinf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(inf nsub nnorm) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_noinf_noneg_nonan(float nofpclass(nan inf nsub nnorm) %arg) #1 {
; CHECK-LABEL: define nofpclass(nan pinf nzero sub) float @ret_log_noinf_noneg_nonan(
; CHECK-SAME: float nofpclass(nan inf nsub nnorm) [[ARG:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nan pinf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(nan inf nsub nnorm) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_nopinf(float nofpclass(pinf) %arg) #1 {
; CHECK-LABEL: define nofpclass(pinf nzero sub) float @ret_log_nopinf(
; CHECK-SAME: float nofpclass(pinf) [[ARG:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(pinf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(pinf) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_noninf(float nofpclass(ninf) %arg) #1 {
; CHECK-LABEL: define nofpclass(nzero sub) float @ret_log_noninf(
; CHECK-SAME: float nofpclass(ninf) [[ARG:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(ninf) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_nonan(float nofpclass(nan) %arg) #1 {
; CHECK-LABEL: define nofpclass(nzero sub) float @ret_log_nonan(
; CHECK-SAME: float nofpclass(nan) [[ARG:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(nan) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_nonan_noinf(float nofpclass(nan inf) %arg) #1 {
; CHECK-LABEL: define nofpclass(pinf nzero sub) float @ret_log_nonan_noinf(
; CHECK-SAME: float nofpclass(nan inf) [[ARG:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(pinf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(nan inf) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_nonan_noinf_nozero(float nofpclass(nan inf zero) %arg) #1 {
; CHECK-LABEL: define nofpclass(inf nzero sub) float @ret_log_nonan_noinf_nozero(
; CHECK-SAME: float nofpclass(nan inf zero) [[ARG:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(nan inf zero) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_noinf_nozero(float nofpclass(inf zero) %arg) #1 {
; CHECK-LABEL: define nofpclass(inf nzero sub) float @ret_log_noinf_nozero(
; CHECK-SAME: float nofpclass(inf zero) [[ARG:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(inf zero) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_noinf_nonegzero(float nofpclass(inf nzero) %arg) #1 {
; CHECK-LABEL: define nofpclass(pinf nzero sub) float @ret_log_noinf_nonegzero(
; CHECK-SAME: float nofpclass(inf nzero) [[ARG:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(pinf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(inf nzero) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_positive_source(i32 %arg) #1 {
; CHECK-LABEL: define nofpclass(nan pinf nzero sub) float @ret_log_positive_source(
; CHECK-SAME: i32 [[ARG:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[UITOFP:%.*]] = uitofp i32 [[ARG]] to float
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nan pinf nzero sub) float @llvm.amdgcn.log.f32(float [[UITOFP]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %uitofp = uitofp i32 %arg to float
  %call = call float @llvm.amdgcn.log.f32(float %uitofp)
  ret float %call
}

define float @ret_log_unknown_sign(float nofpclass(nan) %arg, float nofpclass(nan) %arg1) #1 {
; CHECK-LABEL: define nofpclass(nzero sub) float @ret_log_unknown_sign(
; CHECK-SAME: float nofpclass(nan) [[ARG:%.*]], float nofpclass(nan) [[ARG1:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[UNKNOWN_SIGN_NOT_NAN:%.*]] = fmul nnan float [[ARG]], [[ARG1]]
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nzero sub) float @llvm.amdgcn.log.f32(float [[UNKNOWN_SIGN_NOT_NAN]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %unknown.sign.not.nan = fmul nnan float %arg, %arg1
  %call = call float @llvm.amdgcn.log.f32(float %unknown.sign.not.nan)
  ret float %call
}

define float @ret_log_daz_noinf_nozero(float nofpclass(inf zero) %arg) #2 {
; CHECK-LABEL: define nofpclass(pinf nzero sub) float @ret_log_daz_noinf_nozero(
; CHECK-SAME: float nofpclass(inf zero) [[ARG:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(pinf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(inf zero) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define <2 x float> @ret_log_daz_noinf_nozero_v2f32(<2 x float> nofpclass(inf zero) %arg) #2 {
; CHECK-LABEL: define nofpclass(pinf nzero sub) <2 x float> @ret_log_daz_noinf_nozero_v2f32(
; CHECK-SAME: <2 x float> nofpclass(inf zero) [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(pinf nzero sub) <2 x float> @llvm.log.v2f32(<2 x float> nofpclass(inf zero) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret <2 x float> [[CALL]]
;
  %call = call <2 x float> @llvm.log.v2f32(<2 x float> %arg)
  ret <2 x float> %call
}

define float @ret_log_daz_noinf_nonegzero(float nofpclass(inf nzero) %arg) #2 {
; CHECK-LABEL: define nofpclass(pinf nzero sub) float @ret_log_daz_noinf_nonegzero(
; CHECK-SAME: float nofpclass(inf nzero) [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(pinf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(inf nzero) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_dynamic_noinf_nozero(float nofpclass(inf zero) %arg) #3 {
; CHECK-LABEL: define nofpclass(pinf nzero sub) float @ret_log_dynamic_noinf_nozero(
; CHECK-SAME: float nofpclass(inf zero) [[ARG:%.*]]) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(pinf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(inf zero) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_dynamic_noinf_nonegzero(float nofpclass(inf nzero) %arg) #3 {
; CHECK-LABEL: define nofpclass(pinf nzero sub) float @ret_log_dynamic_noinf_nonegzero(
; CHECK-SAME: float nofpclass(inf nzero) [[ARG:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(pinf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(inf nzero) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_ftz_noinf_nonegzero(float nofpclass(inf nzero) %arg) #4 {
; CHECK-LABEL: define nofpclass(pinf nzero sub) float @ret_log_ftz_noinf_nonegzero(
; CHECK-SAME: float nofpclass(inf nzero) [[ARG:%.*]]) #[[ATTR3:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(pinf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(inf nzero) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_ftz_dynamic_noinf_nonegzero(float nofpclass(inf nzero) %arg) #5 {
; CHECK-LABEL: define nofpclass(pinf nzero sub) float @ret_log_ftz_dynamic_noinf_nonegzero(
; CHECK-SAME: float nofpclass(inf nzero) [[ARG:%.*]]) #[[ATTR4:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(pinf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(inf nzero) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_dynamic_noinf_nozero_nosub(float nofpclass(inf zero sub) %arg) #3 {
; CHECK-LABEL: define nofpclass(inf nzero sub) float @ret_log_dynamic_noinf_nozero_nosub(
; CHECK-SAME: float nofpclass(inf zero sub) [[ARG:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(inf zero sub) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_dynamic_noinf_nopzero_nopsub(float nofpclass(inf pzero psub) %arg) #3 {
; CHECK-LABEL: define nofpclass(pinf nzero sub) float @ret_log_dynamic_noinf_nopzero_nopsub(
; CHECK-SAME: float nofpclass(inf pzero psub) [[ARG:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(pinf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(inf pzero psub) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

define float @ret_log_dynamic_noinf_nonzero_nonsub(float nofpclass(inf nzero nsub) %arg) #3 {
; CHECK-LABEL: define nofpclass(pinf nzero sub) float @ret_log_dynamic_noinf_nonzero_nonsub(
; CHECK-SAME: float nofpclass(inf nzero nsub) [[ARG:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(pinf nzero sub) float @llvm.amdgcn.log.f32(float nofpclass(inf nzero nsub) [[ARG]]) #[[ATTR6]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.amdgcn.log.f32(float %arg)
  ret float %call
}

declare half @llvm.amdgcn.log.f16(half) #0
declare float @llvm.amdgcn.log.f32(float) #0

attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #1 = { denormal_fpenv(ieee) }
attributes #2 = { denormal_fpenv(ieee|preservesign) }
attributes #3 = { denormal_fpenv(ieee|dynamic) }
attributes #4 = { denormal_fpenv(preservesign|ieee) }
attributes #5 = { denormal_fpenv(dynamic|ieee) }
