# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -o - %s -mtriple=x86_64-- -run-pass=branch-folder | FileCheck %s

---
name:            test_drop_undef_when_hoisting
liveins:
  - { reg: '$xmm0', virtual-reg: '' }
  - { reg: '$edi', virtual-reg: '' }
constants:
  - id:              0
    value:           '<16 x i8> <i8 1, i8 1, i8 1, i8 1, i8 undef, i8 undef, i8 undef, i8 undef, i8 undef, i8 undef, i8 undef, i8 undef, i8 undef, i8 undef, i8 undef, i8 undef>'
  - id:              1
    value:           '<8 x i16> splat (i16 255)'
body:             |
  ; CHECK-LABEL: name: test_drop_undef_when_hoisting
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $edi, $xmm0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $xmm1 = MOVAPSrm $rip, 1, $noreg, %const.0, $noreg :: (load (s128) from constant-pool)
  ; CHECK-NEXT:   renamable $xmm1 = PCMPGTBrr killed renamable $xmm1, killed renamable $xmm0
  ; CHECK-NEXT:   renamable $xmm0 = V_SET0
  ; CHECK-NEXT:   renamable $xmm2 = MOVAPSrm $rip, 1, $noreg, %const.1, $noreg :: (load (s128) from constant-pool)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $edi, $xmm0, $xmm1, $xmm2
  ; CHECK-NEXT: {{  $}}
  ; FIXME: This is a miscompilation issue, should intersect flags when hoisting common code.
  ; CHECK-NEXT:   renamable $xmm1 = PUNPCKLBWrr killed renamable $xmm1, undef renamable $xmm0
  ; CHECK-NEXT:   TEST8ri renamable $dil, 1, implicit-def $eflags
  ; CHECK-NEXT:   JCC_1 %bb.3, 5, implicit killed $eflags
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT:   liveins: $edi, $xmm0, $xmm1, $xmm2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $xmm1 = PSHUFLWri killed renamable $xmm1, 1
  ; CHECK-NEXT:   renamable $xmm1 = PACKUSWBrr killed renamable $xmm1, undef renamable $xmm0
  ; CHECK-NEXT:   JMP_1 %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT:   liveins: $edi, $xmm0, $xmm1, $xmm2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $xmm1 = PMULLWrr killed renamable $xmm1, renamable $xmm1
  ; CHECK-NEXT:   renamable $xmm1 = PANDrr killed renamable $xmm1, renamable $xmm2
  ; CHECK-NEXT:   renamable $xmm1 = PACKUSWBrr killed renamable $xmm1, renamable $xmm1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x04000000), %bb.1(0x7c000000)
  ; CHECK-NEXT:   liveins: $edi, $xmm0, $xmm1, $xmm2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   TEST8ri renamable $dil, 1, implicit-def $eflags
  ; CHECK-NEXT:   JCC_1 %bb.1, 4, implicit $eflags
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   RET 0
  bb.0.entry:
    successors: %bb.1(0x80000000)
    liveins: $edi, $xmm0

    renamable $xmm1 = MOVAPSrm $rip, 1, $noreg, %const.0, $noreg :: (load (s128) from constant-pool)
    renamable $xmm1 = PCMPGTBrr killed renamable $xmm1, killed renamable $xmm0
    renamable $xmm0 = V_SET0
    renamable $xmm2 = MOVAPSrm $rip, 1, $noreg, %const.1, $noreg :: (load (s128) from constant-pool)

  bb.1:
    successors: %bb.3(0x40000000), %bb.2(0x40000000)
    liveins: $edi, $xmm0, $xmm1, $xmm2

    TEST8ri renamable $dil, 1, implicit-def $eflags
    JCC_1 %bb.3, 5, implicit killed $eflags

  bb.2:
    successors: %bb.4(0x80000000)
    liveins: $edi, $xmm0, $xmm1, $xmm2

    renamable $xmm1 = PUNPCKLBWrr killed renamable $xmm1, renamable $xmm0
    renamable $xmm1 = PSHUFLWri killed renamable $xmm1, 1
    renamable $xmm1 = PACKUSWBrr killed renamable $xmm1, undef renamable $xmm0
    JMP_1 %bb.4

  bb.3:
    successors: %bb.4(0x80000000)
    liveins: $edi, $xmm0, $xmm1, $xmm2

    renamable $xmm1 = PUNPCKLBWrr killed renamable $xmm1, undef renamable $xmm0
    renamable $xmm1 = PMULLWrr killed renamable $xmm1, renamable $xmm1
    renamable $xmm1 = PANDrr killed renamable $xmm1, renamable $xmm2
    renamable $xmm1 = PACKUSWBrr killed renamable $xmm1, renamable $xmm1

  bb.4:
    successors: %bb.5(0x04000000), %bb.1(0x7c000000)
    liveins: $edi, $xmm0, $xmm1, $xmm2

    TEST8ri renamable $dil, 1, implicit-def $eflags
    JCC_1 %bb.1, 4, implicit killed $eflags
    JMP_1 %bb.5

  bb.5:
    RET 0
...
