; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='sroa,memcpyopt,dse,instcombine,sroa<canonicalize-struct-to-vector>' -S %s | FileCheck %s --check-prefix=DELAYED
; RUN: opt -passes='sroa<canonicalize-struct-to-vector>,memcpyopt,dse,instcombine,sroa<canonicalize-struct-to-vector>' -S %s | FileCheck %s --check-prefix=EARLY

%pair = type { i64, i64 }
%quad = type { i64, i64, i64, i64 }

declare void @llvm.memcpy.p0.p0.i64(ptr noalias writeonly captures(none), ptr noalias readonly captures(none), i64, i1 immarg)
declare void @llvm.memset.p0.i64(ptr writeonly captures(none), i8, i64, i1 immarg)

; This test case has the following pattern:
;
;   memcpy tmp, obj, 16
;   memset obj + 16, 0, 16
;   
;  ----- SWAP(other, tmp) -----
;
;   memcpy swap.tmp, tmp, 16
;   memcpy tmp, other, 16
;   memcpy other, swap.tmp, 16
;
; It swaps the first 16-bytes of other and tmp, but the first 16-bytes of tmp are actually the same as the first 16-bytes
; of obj. This comes from real code from DuckDB, where the swap function is inlined. If struct-to-vector canonicalization runs before
; memcpyopt, then swap.tmp gets promoted to an SSA value and we are stuck with saving tmp to swap.tmp.
; But if we delay canonicalization until after memcpyopt,
; then memcpyopt realizes that tmp and obj share the same first 16-bytes, and so we don't need to save tmp to swap.tmp. So it can rewrite to:
;
;   memset obj + 16, 0, 16
;   memcpy tmp, other, 16
;   memcpy other, obj, 16
;
; This is a win because it avoids the extra step of saving tmp to swap.tmp.
define void @move_then_swap(ptr %dst, ptr %src, ptr %other) {
; DELAYED-LABEL: define void @move_then_swap(
; DELAYED-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]], ptr [[OTHER:%.*]]) {
; DELAYED-NEXT:  [[ENTRY:.*:]]
; DELAYED-NEXT:    [[TMP_SROA_0_0_COPYLOAD:%.*]] = load <2 x i64>, ptr [[OTHER]], align 8
; DELAYED-NEXT:    call void @llvm.memmove.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) [[OTHER]], ptr noundef nonnull align 8 dereferenceable(16) [[SRC]], i64 16, i1 false)
; DELAYED-NEXT:    store <2 x i64> [[TMP_SROA_0_0_COPYLOAD]], ptr [[DST]], align 8
; DELAYED-NEXT:    ret void
;
; EARLY-LABEL: define void @move_then_swap(
; EARLY-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]], ptr [[OTHER:%.*]]) {
; EARLY-NEXT:  [[ENTRY:.*:]]
; EARLY-NEXT:    [[OBJ_SROA_0_0_COPYLOAD:%.*]] = load <4 x i64>, ptr [[SRC]], align 8
; EARLY-NEXT:    [[OBJ_SROA_0_0_VEC_EXTRACT:%.*]] = shufflevector <4 x i64> [[OBJ_SROA_0_0_COPYLOAD]], <4 x i64> poison, <2 x i32> <i32 0, i32 1>
; EARLY-NEXT:    [[TMP_SROA_0_0_COPYLOAD:%.*]] = load <2 x i64>, ptr [[OTHER]], align 8
; EARLY-NEXT:    store <2 x i64> [[OBJ_SROA_0_0_VEC_EXTRACT]], ptr [[OTHER]], align 8
; EARLY-NEXT:    store <2 x i64> [[TMP_SROA_0_0_COPYLOAD]], ptr [[DST]], align 8
; EARLY-NEXT:    ret void
;
entry:
  %tmp = alloca %pair, align 8
  %obj = alloca %quad, align 8
  %swap.tmp = alloca %pair, align 8
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %obj, ptr align 8 %src, i64 32, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %tmp, ptr align 8 %obj, i64 16, i1 false)
  %obj.tail = getelementptr inbounds i8, ptr %obj, i64 16
  call void @llvm.memset.p0.i64(ptr align 8 %obj.tail, i8 0, i64 16, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %swap.tmp, ptr align 8 %tmp, i64 16, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %tmp, ptr align 8 %other, i64 16, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %other, ptr align 8 %swap.tmp, i64 16, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %dst, ptr align 8 %tmp, i64 16, i1 false)
  ret void
}
