; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes='sroa' -S | FileCheck %s

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare ptr @llvm.structured.gep.p0(ptr, ...)

%struct.S = type { i32, float }

define float @test_struct() {
; CHECK-LABEL: @test_struct(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ALLOCA:%.*]] = alloca [[STRUCT_S:%.*]], align 4
; CHECK-NEXT:    [[GEP0:%.*]] = call ptr (ptr, ...) @llvm.structured.gep.p0(ptr elementtype([[STRUCT_S]]) [[ALLOCA]], i32 0)
; CHECK-NEXT:    store i32 1, ptr [[GEP0]], align 4
; CHECK-NEXT:    [[GEP1:%.*]] = call ptr (ptr, ...) @llvm.structured.gep.p0(ptr elementtype([[STRUCT_S]]) [[ALLOCA]], i32 1)
; CHECK-NEXT:    store float 2.000000e+00, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[VAL:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    ret float [[VAL]]
;
entry:
  %alloca = alloca %struct.S, align 4
  %gep0 = call ptr (ptr, ...) @llvm.structured.gep.p0(ptr elementtype(%struct.S) %alloca, i32 0)
  store i32 1, ptr %gep0, align 4
  %gep1 = call ptr (ptr, ...) @llvm.structured.gep.p0(ptr elementtype(%struct.S) %alloca, i32 1)
  store float 2.0, ptr %gep1, align 4
  %val = load float, ptr %gep1, align 4
  ret float %val
}

define i16 @test_array() {
; CHECK-LABEL: @test_array(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[A:%.*]] = alloca [4 x i8], align 1
; CHECK-NEXT:    store float 0.000000e+00, ptr [[A]], align 4
; CHECK-NEXT:    [[PTR:%.*]] = call ptr (ptr, ...) @llvm.structured.gep.p0(ptr elementtype([4 x i8]) [[A]], i32 2)
; CHECK-NEXT:    [[A_SROA_0_2_EXTRACT_TRUNC:%.*]] = load i16, ptr [[PTR]], align 2
; CHECK-NEXT:    ret i16 [[A_SROA_0_2_EXTRACT_TRUNC]]
;
entry:
  %a = alloca [4 x i8], align 1
  store float 0.0, ptr %a, align 4
  %ptr = call ptr (ptr, ...) @llvm.structured.gep.p0(ptr elementtype([4 x i8]) %a, i32 2)
  %val = load i16, ptr %ptr, align 2
  ret i16 %val
}

define i32 @test_nested_struct() {
; CHECK-LABEL: @test_nested_struct(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X:%.*]] = alloca { i32, { float, i32 } }, align 4
; CHECK-NEXT:    [[Y:%.*]] = call ptr (ptr, ...) @llvm.structured.gep.p0(ptr elementtype({ i32, { float, i32 } }) [[X]], i32 1, i32 1)
; CHECK-NEXT:    store i32 0, ptr [[Y]], align 4
; CHECK-NEXT:    [[Z:%.*]] = load i32, ptr [[Y]], align 4
; CHECK-NEXT:    ret i32 [[Z]]
;
entry:
  %X = alloca { i32, { float, i32 } }, align 4
  %Y = call ptr (ptr, ...) @llvm.structured.gep.p0(ptr elementtype({ i32, { float, i32 } }) %X, i32 1, i32 1)
  store i32 0, ptr %Y, align 4
  %Z = load i32, ptr %Y, align 4
  ret i32 %Z
}

%large.struct = type { [5 x i32] }

define i32 @test_large_struct_copy_gep(ptr %input) {
; CHECK-LABEL: @test_large_struct_copy_gep(
; CHECK-NEXT:    [[A:%.*]] = load [[LARGE_STRUCT:%.*]], ptr [[INPUT:%.*]], align 1
; CHECK-NEXT:    [[A_FCA_0_0_EXTRACT:%.*]] = extractvalue [[LARGE_STRUCT]] [[A]], 0, 0
; CHECK-NEXT:    [[A_FCA_0_1_EXTRACT:%.*]] = extractvalue [[LARGE_STRUCT]] [[A]], 0, 1
; CHECK-NEXT:    [[A_FCA_0_2_EXTRACT:%.*]] = extractvalue [[LARGE_STRUCT]] [[A]], 0, 2
; CHECK-NEXT:    [[A_FCA_0_3_EXTRACT:%.*]] = extractvalue [[LARGE_STRUCT]] [[A]], 0, 3
; CHECK-NEXT:    [[A_FCA_0_4_EXTRACT:%.*]] = extractvalue [[LARGE_STRUCT]] [[A]], 0, 4
; CHECK-NEXT:    ret i32 [[A_FCA_0_3_EXTRACT]]
;
  %tmp = alloca %large.struct, align 1
  %a = load %large.struct, ptr %input, align 1
  store %large.struct %a, ptr %tmp

  %ptr = getelementptr %large.struct, ptr %tmp, i32 0, i32 0, i32 3
  %b = load i32, ptr %ptr
  ret i32 %b
}

define i32 @test_large_struct_copy_sgep(ptr %input) {
; CHECK-LABEL: @test_large_struct_copy_sgep(
; CHECK-NEXT:    [[TMP:%.*]] = alloca [[LARGE_STRUCT:%.*]], align 1
; CHECK-NEXT:    [[A:%.*]] = load [[LARGE_STRUCT]], ptr [[INPUT:%.*]], align 1
; CHECK-NEXT:    [[A_FCA_0_0_EXTRACT:%.*]] = extractvalue [[LARGE_STRUCT]] [[A]], 0, 0
; CHECK-NEXT:    [[A_FCA_0_0_GEP:%.*]] = getelementptr inbounds [[LARGE_STRUCT]], ptr [[TMP]], i32 0, i32 0, i32 0
; CHECK-NEXT:    store i32 [[A_FCA_0_0_EXTRACT]], ptr [[A_FCA_0_0_GEP]], align 4
; CHECK-NEXT:    [[A_FCA_0_1_EXTRACT:%.*]] = extractvalue [[LARGE_STRUCT]] [[A]], 0, 1
; CHECK-NEXT:    [[A_FCA_0_1_GEP:%.*]] = getelementptr inbounds [[LARGE_STRUCT]], ptr [[TMP]], i32 0, i32 0, i32 1
; CHECK-NEXT:    store i32 [[A_FCA_0_1_EXTRACT]], ptr [[A_FCA_0_1_GEP]], align 4
; CHECK-NEXT:    [[A_FCA_0_2_EXTRACT:%.*]] = extractvalue [[LARGE_STRUCT]] [[A]], 0, 2
; CHECK-NEXT:    [[A_FCA_0_2_GEP:%.*]] = getelementptr inbounds [[LARGE_STRUCT]], ptr [[TMP]], i32 0, i32 0, i32 2
; CHECK-NEXT:    store i32 [[A_FCA_0_2_EXTRACT]], ptr [[A_FCA_0_2_GEP]], align 4
; CHECK-NEXT:    [[A_FCA_0_3_EXTRACT:%.*]] = extractvalue [[LARGE_STRUCT]] [[A]], 0, 3
; CHECK-NEXT:    [[A_FCA_0_3_GEP:%.*]] = getelementptr inbounds [[LARGE_STRUCT]], ptr [[TMP]], i32 0, i32 0, i32 3
; CHECK-NEXT:    store i32 [[A_FCA_0_3_EXTRACT]], ptr [[A_FCA_0_3_GEP]], align 4
; CHECK-NEXT:    [[A_FCA_0_4_EXTRACT:%.*]] = extractvalue [[LARGE_STRUCT]] [[A]], 0, 4
; CHECK-NEXT:    [[A_FCA_0_4_GEP:%.*]] = getelementptr inbounds [[LARGE_STRUCT]], ptr [[TMP]], i32 0, i32 0, i32 4
; CHECK-NEXT:    store i32 [[A_FCA_0_4_EXTRACT]], ptr [[A_FCA_0_4_GEP]], align 4
; CHECK-NEXT:    [[PTR:%.*]] = call ptr (ptr, ...) @llvm.structured.gep.p0(ptr elementtype([[LARGE_STRUCT]]) [[TMP]], i32 0, i32 3)
; CHECK-NEXT:    [[B:%.*]] = load i32, ptr [[PTR]], align 4
; CHECK-NEXT:    ret i32 [[B]]
;
  %tmp = alloca %large.struct, align 1
  %a = load %large.struct, ptr %input, align 1
  store %large.struct %a, ptr %tmp

  %ptr = call ptr (ptr, ...) @llvm.structured.gep.p0(ptr elementtype(%large.struct) %tmp, i32 0, i32 3)
  %b = load i32, ptr %ptr
  ret i32 %b
}
