; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='memcpyopt,sroa<aggregate-to-vector>' -S %s | FileCheck %s --check-prefixes=GOOD
; RUN: opt -passes='sroa<aggregate-to-vector>,memcpyopt' -S %s | FileCheck %s --check-prefixes=BAD

%class.aiMatrix4x4t = type { float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float }

declare void @llvm.memcpy.p0.p0.i64(ptr noalias writeonly captures(none), ptr noalias readonly captures(none), i64, i1 immarg)

; This test case shows an example where we have:
;
; 1. memcpy %dst, %src
; 2. memcpy null, %dst
;
; but %src is only partially initialized. Note that null is just a placeholder for any pointer to simplify the test case.
; If SROA is too agressive and canonicalizes %src to a vector partition and promotes it to an SSA value, then you end up with a 16-byte store
; whose first lane is 0 and whose other three lanes carry no defined value. That is a wider store than necessary because the
; uninitialized memory becomes a placeholder value. If you instead delay struct to vector canonicalization and allow memcpyopt
; to run, you'll get a 4-byte store of 0.
define ptr @store_only_fp_tail() {
; GOOD-LABEL: define ptr @store_only_fp_tail() {
; GOOD-NEXT:    store float 0.000000e+00, ptr null, align 1
; GOOD-NEXT:    store <3 x float> undef, ptr getelementptr inbounds (i8, ptr null, i64 4), align 1
; GOOD-NEXT:    store float 0.000000e+00, ptr getelementptr inbounds (i8, ptr null, i64 16), align 1
; GOOD-NEXT:    store <11 x float> undef, ptr getelementptr inbounds (i8, ptr null, i64 20), align 1
; GOOD-NEXT:    ret ptr null
;
; BAD-LABEL: define ptr @store_only_fp_tail() {
; BAD-NEXT:    [[DST_SROA_0_0_VEC_INSERT:%.*]] = insertelement <4 x float> undef, float 0.000000e+00, i32 0
; BAD-NEXT:    store <4 x float> [[DST_SROA_0_0_VEC_INSERT]], ptr null, align 1
; BAD-NEXT:    store float 0.000000e+00, ptr getelementptr inbounds (i8, ptr null, i64 16), align 1
; BAD-NEXT:    store <11 x float> undef, ptr getelementptr inbounds (i8, ptr null, i64 20), align 1
; BAD-NEXT:    ret ptr null
;
  %dst = alloca %class.aiMatrix4x4t, align 4
  %src = alloca %class.aiMatrix4x4t, align 4
  %src.tail = getelementptr i8, ptr %src, i64 16
  store float 0.000000e+00, ptr %src.tail, align 4
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 64, i1 false)
  store float 0.000000e+00, ptr %dst, align 4
  call void @llvm.memcpy.p0.p0.i64(ptr null, ptr %dst, i64 64, i1 false)
  ret ptr null
}
