; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O3 -mtriple=aarch64-unknown-unknown -mattr=+bf16 | FileCheck %s --check-prefixes=SCALAR,SCALAR-SD
; RUN: llc < %s -O3 -global-isel -global-isel-abort=1 -mtriple=aarch64-unknown-unknown -mattr=+bf16 | FileCheck %s --check-prefixes=SCALAR,SCALAR-GIS

define bfloat @scalar_fptrunc_float(float %a) {
; SCALAR-LABEL: scalar_fptrunc_float:
; SCALAR:       // %bb.0: // %entry
; SCALAR-NEXT:    bfcvt h0, s0
; SCALAR-NEXT:    ret
entry:
  %res = fptrunc float %a to bfloat
  ret bfloat %res
}

define float @scalar_fpext(bfloat %a) {
; SCALAR-LABEL: scalar_fpext:
; SCALAR:       // %bb.0: // %entry
; SCALAR-NEXT:    // kill: def $h0 killed $h0 def $d0
; SCALAR-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-NEXT:    // kill: def $s0 killed $s0 killed $q0
; SCALAR-NEXT:    ret
entry:
  %res = fpext bfloat %a to float
  ret float %res
}

define double @scalar_fpext_double(bfloat %a) {
; SCALAR-LABEL: scalar_fpext_double:
; SCALAR:       // %bb.0: // %entry
; SCALAR-NEXT:    // kill: def $h0 killed $h0 def $d0
; SCALAR-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-NEXT:    fcvt d0, s0
; SCALAR-NEXT:    ret
entry:
  %res = fpext bfloat %a to double
  ret double %res
}

define <2 x bfloat> @v2bf16_fptrunc_float(<2 x float> %a) {
; SCALAR-LABEL: v2bf16_fptrunc_float:
; SCALAR:       // %bb.0: // %entry
; SCALAR-NEXT:    // kill: def $d0 killed $d0 def $q0
; SCALAR-NEXT:    bfcvtn v0.4h, v0.4s
; SCALAR-NEXT:    ret
entry:
  %res = fptrunc <2 x float> %a to <2 x bfloat>
  ret <2 x bfloat> %res
}

define <3 x bfloat> @v3bf16_fptrunc_float(<3 x float> %a) {
; SCALAR-LABEL: v3bf16_fptrunc_float:
; SCALAR:       // %bb.0: // %entry
; SCALAR-NEXT:    bfcvtn v0.4h, v0.4s
; SCALAR-NEXT:    ret
entry:
  %res = fptrunc <3 x float> %a to <3 x bfloat>
  ret <3 x bfloat> %res
}

define <4 x bfloat> @v4bf16_fptrunc_float(<4 x float> %a) {
; SCALAR-LABEL: v4bf16_fptrunc_float:
; SCALAR:       // %bb.0: // %entry
; SCALAR-NEXT:    bfcvtn v0.4h, v0.4s
; SCALAR-NEXT:    ret
entry:
  %res = fptrunc <4 x float> %a to <4 x bfloat>
  ret <4 x bfloat> %res
}

define <4 x bfloat> @v4bf16_fptrunc_double(<4 x double> %a) {
; SCALAR-SD-LABEL: v4bf16_fptrunc_double:
; SCALAR-SD:       // %bb.0: // %entry
; SCALAR-SD-NEXT:    fcvtxn v0.2s, v0.2d
; SCALAR-SD-NEXT:    fcvtxn2 v0.4s, v1.2d
; SCALAR-SD-NEXT:    bfcvtn v0.4h, v0.4s
; SCALAR-SD-NEXT:    ret
;
; SCALAR-GIS-LABEL: v4bf16_fptrunc_double:
; SCALAR-GIS:       // %bb.0: // %entry
; SCALAR-GIS-NEXT:    fcvtxn v0.2s, v0.2d
; SCALAR-GIS-NEXT:    fcvtxn2 v0.4s, v1.2d
; SCALAR-GIS-NEXT:    bfcvtn v0.4h, v0.4s
; SCALAR-GIS-NEXT:    ret
entry:
  %res = fptrunc <4 x double> %a to <4 x bfloat>
  ret <4 x bfloat> %res
}

define <2 x float> @v2bf16_fpext_float(<2 x bfloat> %a) {
; SCALAR-LABEL: v2bf16_fpext_float:
; SCALAR:       // %bb.0: // %entry
; SCALAR-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-NEXT:    // kill: def $d0 killed $d0 killed $q0
; SCALAR-NEXT:    ret
entry:
  %res = fpext <2 x bfloat> %a to <2 x float>
  ret <2 x float> %res
}

define <4 x float> @v4bf16_fpext_float(<4 x bfloat> %a) {
; SCALAR-LABEL: v4bf16_fpext_float:
; SCALAR:       // %bb.0: // %entry
; SCALAR-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-NEXT:    ret
entry:
  %res = fpext <4 x bfloat> %a to <4 x float>
  ret <4 x float> %res
}

define <4 x double> @v4bf16_fpext_double(<4 x bfloat> %a) {
; SCALAR-SD-LABEL: v4bf16_fpext_double:
; SCALAR-SD:       // %bb.0: // %entry
; SCALAR-SD-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-SD-NEXT:    fcvtl2 v1.2d, v0.4s
; SCALAR-SD-NEXT:    fcvtl v0.2d, v0.2s
; SCALAR-SD-NEXT:    ret
;
; SCALAR-GIS-LABEL: v4bf16_fpext_double:
; SCALAR-GIS:       // %bb.0: // %entry
; SCALAR-GIS-NEXT:    shll v1.4s, v0.4h, #16
; SCALAR-GIS-NEXT:    fcvtl v0.2d, v1.2s
; SCALAR-GIS-NEXT:    fcvtl2 v1.2d, v1.4s
; SCALAR-GIS-NEXT:    ret
entry:
  %res = fpext <4 x bfloat> %a to <4 x double>
  ret <4 x double> %res
}
