; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O3 -mtriple=aarch64-unknown-unknown -mattr=+bf16 | FileCheck %s --check-prefixes=SCALAR,SCALAR-SD
; RUN: llc < %s -O3 -global-isel -global-isel-abort=1 -mtriple=aarch64-unknown-unknown -mattr=+bf16 | FileCheck %s --check-prefixes=SCALAR,SCALAR-GIS

define bfloat @scalar_fadd(bfloat %a, bfloat %b) {
; SCALAR-SD-LABEL: scalar_fadd:
; SCALAR-SD:       // %bb.0: // %entry
; SCALAR-SD-NEXT:    // kill: def $h1 killed $h1 def $d1
; SCALAR-SD-NEXT:    // kill: def $h0 killed $h0 def $d0
; SCALAR-SD-NEXT:    shll v1.4s, v1.4h, #16
; SCALAR-SD-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-SD-NEXT:    fadd s0, s0, s1
; SCALAR-SD-NEXT:    bfcvt h0, s0
; SCALAR-SD-NEXT:    ret
;
; SCALAR-GIS-LABEL: scalar_fadd:
; SCALAR-GIS:       // %bb.0: // %entry
; SCALAR-GIS-NEXT:    // kill: def $h0 killed $h0 def $d0
; SCALAR-GIS-NEXT:    // kill: def $h1 killed $h1 def $d1
; SCALAR-GIS-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-GIS-NEXT:    shll v1.4s, v1.4h, #16
; SCALAR-GIS-NEXT:    fadd s0, s0, s1
; SCALAR-GIS-NEXT:    bfcvt h0, s0
; SCALAR-GIS-NEXT:    ret
entry:
  %res = fadd bfloat %a, %b
  ret bfloat %res
}

define <2 x bfloat> @v2bf16_fadd(<2 x bfloat> %a, <2 x bfloat> %b) {
; SCALAR-SD-LABEL: v2bf16_fadd:
; SCALAR-SD:       // %bb.0: // %entry
; SCALAR-SD-NEXT:    shll v1.4s, v1.4h, #16
; SCALAR-SD-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-SD-NEXT:    fadd v0.4s, v0.4s, v1.4s
; SCALAR-SD-NEXT:    bfcvtn v0.4h, v0.4s
; SCALAR-SD-NEXT:    ret
;
; SCALAR-GIS-LABEL: v2bf16_fadd:
; SCALAR-GIS:       // %bb.0: // %entry
; SCALAR-GIS-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-GIS-NEXT:    shll v1.4s, v1.4h, #16
; SCALAR-GIS-NEXT:    fadd v0.2s, v0.2s, v1.2s
; SCALAR-GIS-NEXT:    bfcvtn v0.4h, v0.4s
; SCALAR-GIS-NEXT:    ret
entry:
  %res = fadd <2 x bfloat> %a, %b
  ret <2 x bfloat> %res
}


define <4 x bfloat> @v4bf16_fadd(<4 x bfloat> %a, <4 x bfloat> %b) {
; SCALAR-SD-LABEL: v4bf16_fadd:
; SCALAR-SD:       // %bb.0: // %entry
; SCALAR-SD-NEXT:    shll v1.4s, v1.4h, #16
; SCALAR-SD-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-SD-NEXT:    fadd v0.4s, v0.4s, v1.4s
; SCALAR-SD-NEXT:    bfcvtn v0.4h, v0.4s
; SCALAR-SD-NEXT:    ret
;
; SCALAR-GIS-LABEL: v4bf16_fadd:
; SCALAR-GIS:       // %bb.0: // %entry
; SCALAR-GIS-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-GIS-NEXT:    shll v1.4s, v1.4h, #16
; SCALAR-GIS-NEXT:    fadd v0.4s, v0.4s, v1.4s
; SCALAR-GIS-NEXT:    bfcvtn v0.4h, v0.4s
; SCALAR-GIS-NEXT:    ret
entry:
  %res = fadd <4 x bfloat> %a, %b
  ret <4 x bfloat> %res
}

define bfloat @scalar_fsub(bfloat %a, bfloat %b) {
; SCALAR-SD-LABEL: scalar_fsub:
; SCALAR-SD:       // %bb.0: // %entry
; SCALAR-SD-NEXT:    // kill: def $h1 killed $h1 def $d1
; SCALAR-SD-NEXT:    // kill: def $h0 killed $h0 def $d0
; SCALAR-SD-NEXT:    shll v1.4s, v1.4h, #16
; SCALAR-SD-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-SD-NEXT:    fsub s0, s0, s1
; SCALAR-SD-NEXT:    bfcvt h0, s0
; SCALAR-SD-NEXT:    ret
;
; SCALAR-GIS-LABEL: scalar_fsub:
; SCALAR-GIS:       // %bb.0: // %entry
; SCALAR-GIS-NEXT:    // kill: def $h0 killed $h0 def $d0
; SCALAR-GIS-NEXT:    // kill: def $h1 killed $h1 def $d1
; SCALAR-GIS-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-GIS-NEXT:    shll v1.4s, v1.4h, #16
; SCALAR-GIS-NEXT:    fsub s0, s0, s1
; SCALAR-GIS-NEXT:    bfcvt h0, s0
; SCALAR-GIS-NEXT:    ret
entry:
  %res = fsub bfloat %a, %b
  ret bfloat %res
}

define bfloat @scalar_fmul(bfloat %a, bfloat %b) {
; SCALAR-SD-LABEL: scalar_fmul:
; SCALAR-SD:       // %bb.0: // %entry
; SCALAR-SD-NEXT:    // kill: def $h1 killed $h1 def $d1
; SCALAR-SD-NEXT:    // kill: def $h0 killed $h0 def $d0
; SCALAR-SD-NEXT:    shll v1.4s, v1.4h, #16
; SCALAR-SD-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-SD-NEXT:    fmul s0, s0, s1
; SCALAR-SD-NEXT:    bfcvt h0, s0
; SCALAR-SD-NEXT:    ret
;
; SCALAR-GIS-LABEL: scalar_fmul:
; SCALAR-GIS:       // %bb.0: // %entry
; SCALAR-GIS-NEXT:    // kill: def $h0 killed $h0 def $d0
; SCALAR-GIS-NEXT:    // kill: def $h1 killed $h1 def $d1
; SCALAR-GIS-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-GIS-NEXT:    shll v1.4s, v1.4h, #16
; SCALAR-GIS-NEXT:    fmul s0, s0, s1
; SCALAR-GIS-NEXT:    bfcvt h0, s0
; SCALAR-GIS-NEXT:    ret
entry:
  %res = fmul bfloat %a, %b
  ret bfloat %res
}

define bfloat @scalar_fdiv(bfloat %a, bfloat %b) {
; SCALAR-SD-LABEL: scalar_fdiv:
; SCALAR-SD:       // %bb.0: // %entry
; SCALAR-SD-NEXT:    // kill: def $h1 killed $h1 def $d1
; SCALAR-SD-NEXT:    // kill: def $h0 killed $h0 def $d0
; SCALAR-SD-NEXT:    shll v1.4s, v1.4h, #16
; SCALAR-SD-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-SD-NEXT:    fdiv s0, s0, s1
; SCALAR-SD-NEXT:    bfcvt h0, s0
; SCALAR-SD-NEXT:    ret
;
; SCALAR-GIS-LABEL: scalar_fdiv:
; SCALAR-GIS:       // %bb.0: // %entry
; SCALAR-GIS-NEXT:    // kill: def $h0 killed $h0 def $d0
; SCALAR-GIS-NEXT:    // kill: def $h1 killed $h1 def $d1
; SCALAR-GIS-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-GIS-NEXT:    shll v1.4s, v1.4h, #16
; SCALAR-GIS-NEXT:    fdiv s0, s0, s1
; SCALAR-GIS-NEXT:    bfcvt h0, s0
; SCALAR-GIS-NEXT:    ret
entry:
  %res = fdiv bfloat %a, %b
  ret bfloat %res
}

define i1 @scalar_fcmp(bfloat %a, bfloat %b) {
; SCALAR-SD-LABEL: scalar_fcmp:
; SCALAR-SD:       // %bb.0: // %entry
; SCALAR-SD-NEXT:    // kill: def $h1 killed $h1 def $d1
; SCALAR-SD-NEXT:    // kill: def $h0 killed $h0 def $d0
; SCALAR-SD-NEXT:    shll v1.4s, v1.4h, #16
; SCALAR-SD-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-SD-NEXT:    fcmp s0, s1
; SCALAR-SD-NEXT:    cset w0, gt
; SCALAR-SD-NEXT:    ret
;
; SCALAR-GIS-LABEL: scalar_fcmp:
; SCALAR-GIS:       // %bb.0: // %entry
; SCALAR-GIS-NEXT:    // kill: def $h0 killed $h0 def $d0
; SCALAR-GIS-NEXT:    // kill: def $h1 killed $h1 def $d1
; SCALAR-GIS-NEXT:    shll v0.4s, v0.4h, #16
; SCALAR-GIS-NEXT:    shll v1.4s, v1.4h, #16
; SCALAR-GIS-NEXT:    fcmp s0, s1
; SCALAR-GIS-NEXT:    cset w0, gt
; SCALAR-GIS-NEXT:    ret
entry:
  %cmp = fcmp ogt bfloat %a, %b
  ret i1 %cmp
}

define bfloat @scalar_sitofp(i32 %a) {
; SCALAR-SD-LABEL: scalar_sitofp:
; SCALAR-SD:       // %bb.0: // %entry
; SCALAR-SD-NEXT:    scvtf d0, w0
; SCALAR-SD-NEXT:    fcvtxn s0, d0
; SCALAR-SD-NEXT:    bfcvt h0, s0
; SCALAR-SD-NEXT:    ret
;
; SCALAR-GIS-LABEL: scalar_sitofp:
; SCALAR-GIS:       // %bb.0: // %entry
; SCALAR-GIS-NEXT:    scvtf s0, w0
; SCALAR-GIS-NEXT:    bfcvt h0, s0
; SCALAR-GIS-NEXT:    ret
entry:
  %res = sitofp i32 %a to bfloat
  ret bfloat %res
}

define <4 x bfloat> @v4i32_sitofp(<4 x i32> %a) {
; SCALAR-LABEL: v4i32_sitofp:
; SCALAR:       // %bb.0: // %entry
; SCALAR-NEXT:    scvtf v0.4s, v0.4s
; SCALAR-NEXT:    bfcvtn v0.4h, v0.4s
; SCALAR-NEXT:    ret
entry:
  %res = sitofp <4 x i32> %a to <4 x bfloat>
  ret <4 x bfloat> %res
}
