# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=aarch64 -run-pass=aarch64-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

# Negative: ctlz(0) is defined as bitwidth and must not become poison.
---
name:            ctlz_constant_zero_no_combine
body:             |
  bb.0:
    ; CHECK-LABEL: name: ctlz_constant_zero_no_combine
    ; CHECK: %r:_(s32) = G_CONSTANT i32 32
    ; CHECK-NEXT: $w0 = COPY %r(s32)
    %z:_(s32) = G_CONSTANT i32 0
    %r:_(s32) = G_CTLZ %z
    $w0 = COPY %r(s32)
...
---
name:            ctlz_unknown_no_combine
body:             |
  bb.0:
    liveins: $w0
    ; CHECK-LABEL: name: ctlz_unknown_no_combine
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %r:_(s32) = G_CTLZ %x(s32)
    ; CHECK-NEXT: $w0 = COPY %r(s32)
    %x:_(s32) = COPY $w0
    %r:_(s32) = G_CTLZ %x
    $w0 = COPY %r(s32)
...
---
name:            ctlz_or_with_one
body:             |
  bb.0:
    liveins: $w0
    ; CHECK-LABEL: name: ctlz_or_with_one
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %one:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: %or:_(s32) = G_OR %x, %one
    ; CHECK-NEXT: %r:_(s32) = G_CTLZ_ZERO_POISON %or(s32)
    ; CHECK-NEXT: $w0 = COPY %r(s32)
    %x:_(s32) = COPY $w0
    %one:_(s32) = G_CONSTANT i32 1
    %or:_(s32) = G_OR %x, %one
    %r:_(s32) = G_CTLZ %or
    $w0 = COPY %r(s32)
...
---
name:            cttz_shl_one_nuw
body:             |
  bb.0:
    liveins: $w0
    ; CHECK-LABEL: name: cttz_shl_one_nuw
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %one:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: %shl:_(s32) = nuw G_SHL %one, %x(s32)
    ; CHECK-NEXT: %r:_(s32) = G_CTTZ_ZERO_POISON %shl(s32)
    ; CHECK-NEXT: $w0 = COPY %r(s32)
    %x:_(s32) = COPY $w0
    %one:_(s32) = G_CONSTANT i32 1
    %shl:_(s32) = nuw G_SHL %one, %x
    %r:_(s32) = G_CTTZ %shl
    $w0 = COPY %r(s32)
...
---
name:            cttz_select_both_nonzero
body:             |
  bb.0:
    liveins: $w0, $w1, $w2
    ; CHECK-LABEL: name: cttz_select_both_nonzero
    ; CHECK: liveins: $w0, $w1, $w2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %y:_(s32) = COPY $w1
    ; CHECK-NEXT: %c:_(s32) = COPY $w2
    ; CHECK-NEXT: %cond:_(s1) = G_TRUNC %c(s32)
    ; CHECK-NEXT: %one:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: %xo:_(s32) = G_OR %x, %one
    ; CHECK-NEXT: %yo:_(s32) = G_OR %y, %one
    ; CHECK-NEXT: %sel:_(s32) = G_SELECT %cond(s1), %xo, %yo
    ; CHECK-NEXT: %r:_(s32) = G_CTTZ_ZERO_POISON %sel(s32)
    ; CHECK-NEXT: $w0 = COPY %r(s32)
    %x:_(s32) = COPY $w0
    %y:_(s32) = COPY $w1
    %c:_(s32) = COPY $w2
    %cond:_(s1) = G_TRUNC %c
    %one:_(s32) = G_CONSTANT i32 1
    %xo:_(s32) = G_OR %x, %one
    %yo:_(s32) = G_OR %y, %one
    %sel:_(s32) = G_SELECT %cond(s1), %xo, %yo
    %r:_(s32) = G_CTTZ %sel
    $w0 = COPY %r(s32)
...
