# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple aarch64 -run-pass=aarch64-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple aarch64 -passes='require<libcall-lowering-info>,function(machine-function(aarch64-prelegalizer-combiner))' %s -o - | FileCheck %s

---
name:            sitofp
liveins:
  - { reg: '$d0' }
body:             |
  bb.1.entry:
    liveins: $d0

    ; CHECK-LABEL: name: sitofp
    ; CHECK: liveins: $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %res:_(s64) = G_FCONSTANT double 0.000000e+00
    ; CHECK-NEXT: $d0 = COPY %res(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $d0
    %a:_(s64) = G_CONSTANT i64 0
    %res:_(s64) = G_SITOFP %a
    $d0 = COPY %res(s64)
    RET_ReallyLR implicit $d0

...
---
name:            uitofp
liveins:
  - { reg: '$d0' }
body:             |
  bb.1.entry:
    liveins: $d0

    ; CHECK-LABEL: name: uitofp
    ; CHECK: liveins: $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %res:_(s64) = G_FCONSTANT double 0.000000e+00
    ; CHECK-NEXT: $d0 = COPY %res(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $d0
    %a:_(s64) = G_CONSTANT i64 0
    %res:_(s64) = G_UITOFP %a
    $d0 = COPY %res(s64)
    RET_ReallyLR implicit $d0

...
