# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple aarch64 -run-pass=aarch64-prelegalizer-combiner %s -o - | FileCheck %s

# Basic positive K: (sub 5, (mul X, 7)) -> (add 5, (mul X, -7))
---
name:   sub_of_mul_const_pos_k
body:             |
  bb.0:
    liveins: $w0
    ; CHECK-LABEL: name: sub_of_mul_const_pos_k
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %c:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -7
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL %x, [[C]]
    ; CHECK-NEXT: %sub:_(s32) = G_ADD [[MUL]], %c
    ; CHECK-NEXT: $w0 = COPY %sub(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x:_(s32) = COPY $w0
    %k:_(s32) = G_CONSTANT i32 7
    %c:_(s32) = G_CONSTANT i32 5
    %mul:_(s32) = G_MUL %x, %k
    %sub:_(s32) = G_SUB %c, %mul
    $w0 = COPY %sub(s32)
    RET_ReallyLR implicit $w0
...

# Negative K: (sub 5, (mul X, -7)) -> (add 5, (mul X, 7))
---
name:   sub_of_mul_const_neg_k
body:             |
  bb.0:
    liveins: $w0
    ; CHECK-LABEL: name: sub_of_mul_const_neg_k
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %c:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL %x, [[C]]
    ; CHECK-NEXT: %sub:_(s32) = G_ADD [[MUL]], %c
    ; CHECK-NEXT: $w0 = COPY %sub(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x:_(s32) = COPY $w0
    %k:_(s32) = G_CONSTANT i32 -7
    %c:_(s32) = G_CONSTANT i32 5
    %mul:_(s32) = G_MUL %x, %k
    %sub:_(s32) = G_SUB %c, %mul
    $w0 = COPY %sub(s32)
    RET_ReallyLR implicit $w0
...

# C=0 collapses via combine_add_with_zero: (sub 0, (mul X, 7)) -> (mul X, -7)
---
name:   sub_of_mul_const_zero_c
body:             |
  bb.0:
    liveins: $w0
    ; CHECK-LABEL: name: sub_of_mul_const_zero_c
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -7
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL %x, [[C]]
    ; CHECK-NEXT: $w0 = COPY [[MUL]](s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x:_(s32) = COPY $w0
    %k:_(s32) = G_CONSTANT i32 7
    %c:_(s32) = G_CONSTANT i32 0
    %mul:_(s32) = G_MUL %x, %k
    %sub:_(s32) = G_SUB %c, %mul
    $w0 = COPY %sub(s32)
    RET_ReallyLR implicit $w0
...

# INT_MIN K: never reaches our matcher because mul_to_shl rewrites
# `mul X, 2^31` to `shl X, 31` first. Kept as a regression guard so we notice
# if pipeline ordering ever changes; the rewrite would still be semantically
# valid (-INT_MIN == INT_MIN under two's complement, so mul X, K == mul X, -K
# and the sub -> add flip is the actual win).
---
name:   sub_of_mul_const_int_min_handled_by_mul_to_shl
body:             |
  bb.0:
    liveins: $w0
    ; CHECK-LABEL: name: sub_of_mul_const_int_min_handled_by_mul_to_shl
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %c:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: %mul:_(s32) = G_SHL %x, [[C]](s32)
    ; CHECK-NEXT: %sub:_(s32) = G_SUB %c, %mul
    ; CHECK-NEXT: $w0 = COPY %sub(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x:_(s32) = COPY $w0
    %k:_(s32) = G_CONSTANT i32 -2147483648
    %c:_(s32) = G_CONSTANT i32 5
    %mul:_(s32) = G_MUL %x, %k
    %sub:_(s32) = G_SUB %c, %mul
    $w0 = COPY %sub(s32)
    RET_ReallyLR implicit $w0
...

# K is not a constant: bail
---
name:   sub_of_mul_const_non_const_bail
body:             |
  bb.0:
    liveins: $w0, $w1
    ; CHECK-LABEL: name: sub_of_mul_const_non_const_bail
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %y:_(s32) = COPY $w1
    ; CHECK-NEXT: %c:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: %mul:_(s32) = G_MUL %x, %y
    ; CHECK-NEXT: %sub:_(s32) = G_SUB %c, %mul
    ; CHECK-NEXT: $w0 = COPY %sub(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x:_(s32) = COPY $w0
    %y:_(s32) = COPY $w1
    %c:_(s32) = G_CONSTANT i32 5
    %mul:_(s32) = G_MUL %x, %y
    %sub:_(s32) = G_SUB %c, %mul
    $w0 = COPY %sub(s32)
    RET_ReallyLR implicit $w0
...

# Mul has two non-DBG users: bail (would either duplicate or regress).
---
name:   sub_of_mul_const_multi_use_bail
body:             |
  bb.0:
    liveins: $w0
    ; CHECK-LABEL: name: sub_of_mul_const_multi_use_bail
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %k:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: %c:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: %mul:_(s32) = G_MUL %x, %k
    ; CHECK-NEXT: %sub:_(s32) = G_SUB %c, %mul
    ; CHECK-NEXT: %use2:_(s32) = G_ADD %mul, %x
    ; CHECK-NEXT: $w0 = COPY %sub(s32)
    ; CHECK-NEXT: $w1 = COPY %use2(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0, implicit $w1
    %x:_(s32) = COPY $w0
    %k:_(s32) = G_CONSTANT i32 7
    %c:_(s32) = G_CONSTANT i32 5
    %mul:_(s32) = G_MUL %x, %k
    %sub:_(s32) = G_SUB %c, %mul
    %use2:_(s32) = G_ADD %mul, %x
    $w0 = COPY %sub(s32)
    $w1 = COPY %use2(s32)
    RET_ReallyLR implicit $w0, implicit $w1
...

# i64 width works (no LLT::scalar(32) restriction).
---
name:   sub_of_mul_const_i64
body:             |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: sub_of_mul_const_i64
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s64) = COPY $x0
    ; CHECK-NEXT: %c:_(s64) = G_CONSTANT i64 5
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 -7
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s64) = G_MUL %x, [[C]]
    ; CHECK-NEXT: %sub:_(s64) = G_ADD [[MUL]], %c
    ; CHECK-NEXT: $x0 = COPY %sub(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $x0
    %x:_(s64) = COPY $x0
    %k:_(s64) = G_CONSTANT i64 7
    %c:_(s64) = G_CONSTANT i64 5
    %mul:_(s64) = G_MUL %x, %k
    %sub:_(s64) = G_SUB %c, %mul
    $x0 = COPY %sub(s64)
    RET_ReallyLR implicit $x0
...

# Vector splat: bail in the first cut (matcher requires scalar).
---
name:   sub_of_mul_const_vector_bail
body:             |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: sub_of_mul_const_vector_bail
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(<4 x s32>) = COPY $q0
    ; CHECK-NEXT: %k_elt:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: %c_elt:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: %k:_(<4 x s32>) = G_BUILD_VECTOR %k_elt(s32), %k_elt(s32), %k_elt(s32), %k_elt(s32)
    ; CHECK-NEXT: %c:_(<4 x s32>) = G_BUILD_VECTOR %c_elt(s32), %c_elt(s32), %c_elt(s32), %c_elt(s32)
    ; CHECK-NEXT: %mul:_(<4 x s32>) = G_MUL %x, %k
    ; CHECK-NEXT: %sub:_(<4 x s32>) = G_SUB %c, %mul
    ; CHECK-NEXT: $q0 = COPY %sub(<4 x s32>)
    ; CHECK-NEXT: RET_ReallyLR implicit $q0
    %x:_(<4 x s32>) = COPY $q0
    %k_elt:_(s32) = G_CONSTANT i32 7
    %c_elt:_(s32) = G_CONSTANT i32 5
    %k:_(<4 x s32>) = G_BUILD_VECTOR %k_elt, %k_elt, %k_elt, %k_elt
    %c:_(<4 x s32>) = G_BUILD_VECTOR %c_elt, %c_elt, %c_elt, %c_elt
    %mul:_(<4 x s32>) = G_MUL %x, %k
    %sub:_(<4 x s32>) = G_SUB %c, %mul
    $q0 = COPY %sub(<4 x s32>)
    RET_ReallyLR implicit $q0
...
