# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -o - -mtriple aarch64-- -run-pass=aarch64-prelegalizer-combiner %s | FileCheck %s
# RUN: llc -o - -mtriple aarch64-- -passes='require<libcall-lowering-info>,function(machine-function(aarch64-prelegalizer-combiner))' %s | FileCheck %s
---
name: test_combine_neg_and_one_to_sext_inreg_s32
body: |
  bb.1:
  liveins: $w0
    ; CHECK-LABEL: name: test_combine_neg_and_one_to_sext_inreg_s32
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %res:_(s32) = G_SEXT_INREG %x, 1
    ; CHECK-NEXT: $w0 = COPY %res(s32)
    %x:_(s32) = COPY $w0
    %one:_(s32) = G_CONSTANT i32 1
    %zero:_(s32) = G_CONSTANT i32 0
    %and:_(s32) = G_AND %x:_, %one:_
    %res:_(s32) = G_SUB %zero:_, %and:_
    $w0 = COPY %res:_(s32)
...
---
name: test_combine_neg_and_one_to_sext_inreg_s64
body: |
  bb.1:
  liveins: $x0
    ; CHECK-LABEL: name: test_combine_neg_and_one_to_sext_inreg_s64
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s64) = COPY $x0
    ; CHECK-NEXT: %res:_(s64) = G_SEXT_INREG %x, 1
    ; CHECK-NEXT: $x0 = COPY %res(s64)
    %x:_(s64) = COPY $x0
    %one:_(s64) = G_CONSTANT i64 1
    %zero:_(s64) = G_CONSTANT i64 0
    %and:_(s64) = G_AND %x:_, %one:_
    %res:_(s64) = G_SUB %zero:_, %and:_
    $x0 = COPY %res:_(s64)
...
---
name: test_combine_neg_and_one_to_sext_inreg_multiuse_should_not_transform
body: |
  bb.1:
  liveins: $x0
    ; CHECK-LABEL: name: test_combine_neg_and_one_to_sext_inreg_multiuse_should_not_transform
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s64) = COPY $x0
    ; CHECK-NEXT: %one:_(s64) = G_CONSTANT i64 1
    ; CHECK-NEXT: %zero:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: %and:_(s64) = G_AND %x, %one
    ; CHECK-NEXT: %res:_(s64) = G_SUB %zero, %and
    ; CHECK-NEXT: $x0 = COPY %res(s64)
    ; CHECK-NEXT: $x1 = COPY %and(s64)
    %x:_(s64) = COPY $x0
    %one:_(s64) = G_CONSTANT i64 1
    %zero:_(s64) = G_CONSTANT i64 0
    %and:_(s64) = G_AND %x:_, %one:_
    %res:_(s64) = G_SUB %zero:_, %and:_
    $x0 = COPY %res:_(s64)
    $x1 = COPY %and:_(s64)
...
---
name: test_combine_neg_and_one_to_sext_inreg_v2i32
body: |
  bb.1:
  liveins: $d0
    ; CHECK-LABEL: name: test_combine_neg_and_one_to_sext_inreg_v2i32
    ; CHECK: liveins: $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(<2 x s32>) = COPY $d0
    ; CHECK-NEXT: %res:_(<2 x s32>) = G_SEXT_INREG %x, 1
    ; CHECK-NEXT: $d0 = COPY %res(<2 x s32>)
    %x:_(<2 x s32>) = COPY $d0
    %one:_(s32) = G_CONSTANT i32 1
    %ones:_(<2 x s32>) = G_BUILD_VECTOR %one, %one
    %zero:_(s32) = G_CONSTANT i32 0
    %zeros:_(<2 x s32>) = G_BUILD_VECTOR %zero, %zero
    %and:_(<2 x s32>) = G_AND %x:_, %ones:_
    %res:_(<2 x s32>) = G_SUB %zeros:_, %and:_
    $d0 = COPY %res:_(<2 x s32>)
...
