# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -o - -mtriple=aarch64-unknown-unknown -run-pass=aarch64-prelegalizer-combiner -verify-machineinstrs  %s | FileCheck %s
# RUN: llc -o - -mtriple=aarch64-unknown-unknown -passes='require<libcall-lowering-info>,function(machine-function(aarch64-prelegalizer-combiner))' %s | FileCheck %s

---
name: fpowi_s64_zero
body: |
    bb.0:
      liveins: $d0, $w0

    ; CHECK-LABEL: name: fpowi_s64_zero
    ; CHECK: liveins: $d0, $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.000000e+00
    ; CHECK-NEXT: $d0 = COPY [[C]](s64)
      %0:_(s64) = COPY $d0
      %1:_(s32) = COPY $w0
      %2:_(s32) = G_CONSTANT i32 0
      %3:_(s64) = nnan ninf nsz arcp contract afn reassoc G_FPOWI %0, %2(s32)
      $d0 = COPY %3(s64)
...

---
name: fpowi_s32_zero
body: |
    bb.0:
      liveins: $d0, $w0

    ; CHECK-LABEL: name: fpowi_s32_zero
    ; CHECK: liveins: $d0, $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float 1.000000e+00
    ; CHECK-NEXT: $s0 = COPY [[C]](s32)
      %0:_(s32) = COPY $s0
      %1:_(s32) = COPY $w0
      %2:_(s32) = G_CONSTANT i32 0
      %3:_(s32) = nnan ninf nsz arcp contract afn reassoc G_FPOWI %0, %2(s32)
      $s0 = COPY %3(s32)
...

---
name: fpowi_positive
body: |
    bb.0:
      liveins: $d0, $w0

    ; CHECK-LABEL: name: fpowi_positive
    ; CHECK: liveins: $d0, $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $d0
    ; CHECK-NEXT: [[FMUL:%[0-9]+]]:_(s64) = G_FMUL [[COPY]], [[COPY]]
    ; CHECK-NEXT: [[FMUL1:%[0-9]+]]:_(s64) = G_FMUL [[FMUL]], [[FMUL]]
    ; CHECK-NEXT: [[FMUL2:%[0-9]+]]:_(s64) = G_FMUL [[COPY]], [[FMUL1]]
    ; CHECK-NEXT: $d0 = COPY [[FMUL2]](s64)
      %0:_(s64) = COPY $d0
      %1:_(s32) = COPY $w0
      %2:_(s32) = G_CONSTANT i32 5
      %3:_(s64) = nnan ninf nsz arcp contract afn reassoc G_FPOWI %0, %2(s32)
      $d0 = COPY %3(s64)
...

---
name: fpowi_s64_negative
body: |
    bb.0:
      liveins: $d0, $w0

    ; CHECK-LABEL: name: fpowi_s64_negative
    ; CHECK: liveins: $d0, $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $d0
    ; CHECK-NEXT: [[FMUL:%[0-9]+]]:_(s64) = G_FMUL [[COPY]], [[COPY]]
    ; CHECK-NEXT: [[FMUL1:%[0-9]+]]:_(s64) = G_FMUL [[FMUL]], [[FMUL]]
    ; CHECK-NEXT: [[FMUL2:%[0-9]+]]:_(s64) = G_FMUL [[COPY]], [[FMUL1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.000000e+00
    ; CHECK-NEXT: [[FDIV:%[0-9]+]]:_(s64) = nnan ninf nsz arcp contract afn reassoc G_FDIV [[C]], [[FMUL2]]
    ; CHECK-NEXT: $d0 = COPY [[FDIV]](s64)
      %0:_(s64) = COPY $d0
      %1:_(s32) = COPY $w0
      %2:_(s32) = G_CONSTANT i32 -5
      %3:_(s64) = nnan ninf nsz arcp contract afn reassoc G_FPOWI %0, %2(s32)
      $d0 = COPY %3(s64)
...

---
name: fpowi_s32_negative
body: |
    bb.0:
      liveins: $d0, $w0

    ; CHECK-LABEL: name: fpowi_s32_negative
    ; CHECK: liveins: $d0, $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $s0
    ; CHECK-NEXT: [[FMUL:%[0-9]+]]:_(s32) = G_FMUL [[COPY]], [[COPY]]
    ; CHECK-NEXT: [[FMUL1:%[0-9]+]]:_(s32) = G_FMUL [[FMUL]], [[FMUL]]
    ; CHECK-NEXT: [[FMUL2:%[0-9]+]]:_(s32) = G_FMUL [[COPY]], [[FMUL1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float 1.000000e+00
    ; CHECK-NEXT: [[FDIV:%[0-9]+]]:_(s32) = nnan ninf nsz arcp contract afn reassoc G_FDIV [[C]], [[FMUL2]]
    ; CHECK-NEXT: $s0 = COPY [[FDIV]](s32)
      %0:_(s32) = COPY $s0
      %1:_(s32) = COPY $w0
      %2:_(s32) = G_CONSTANT i32 -5
      %3:_(s32) = nnan ninf nsz arcp contract afn reassoc G_FPOWI %0, %2(s32)
      $s0 = COPY %3(s32)
...

---
name: fpowi_libcall
body: |
    bb.0:
      liveins: $d0, $w0

    ; CHECK-LABEL: name: fpowi_libcall
    ; CHECK: liveins: $d0, $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $d0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: [[FPOWI:%[0-9]+]]:_(s64) = nnan ninf nsz arcp contract afn reassoc G_FPOWI [[COPY]], [[COPY1]](s32)
    ; CHECK-NEXT: $d0 = COPY [[FPOWI]](s64)
      %0:_(s64) = COPY $d0
      %1:_(s32) = COPY $w0
      %2:_(s64) = nnan ninf nsz arcp contract afn reassoc G_FPOWI %0, %1(s32)
      $d0 = COPY %2(s64)
...
