# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -run-pass=aarch64-prelegalizer-combiner -verify-machineinstrs -mtriple aarch64-unknown-unknown %s -o - | FileCheck %s
# RUN: llc -passes='require<libcall-lowering-info>,function(machine-function(aarch64-prelegalizer-combiner))' -mtriple aarch64-unknown-unknown %s -o - | FileCheck %s
# RUN: llc -debugify-and-strip-all-safe -run-pass=aarch64-prelegalizer-combiner -verify-machineinstrs -mtriple aarch64-unknown-unknown %s -o - | FileCheck %s
# RUN: llc -debugify-and-strip-all-safe -passes='require<libcall-lowering-info>,function(machine-function(aarch64-prelegalizer-combiner))' -mtriple aarch64-unknown-unknown %s -o - | FileCheck %s

---
name:            test_combine_fabs_fabs
body:             |
  bb.1:
  liveins: $w0
    ; CHECK-LABEL: name: test_combine_fabs_fabs
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: [[FABS:%[0-9]+]]:_(s32) = G_FABS [[COPY]]
    ; CHECK-NEXT: $w0 = COPY [[FABS]](s32)
    %0:_(s32) = COPY $w0
    %1:_(s32) = G_FABS %0(s32)
    %2:_(s32) = G_FABS %1(s32)
    $w0 = COPY %2(s32)
...
---
name:            test_combine_fabs_fabs_vec
body:             |
  bb.1:
  liveins: $x0
    ; CHECK-LABEL: name: test_combine_fabs_fabs_vec
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x s32>) = COPY $x0
    ; CHECK-NEXT: [[FABS:%[0-9]+]]:_(<2 x s32>) = G_FABS [[COPY]]
    ; CHECK-NEXT: $x0 = COPY [[FABS]](<2 x s32>)
    %0:_(<2 x s32>) = COPY $x0
    %1:_(<2 x s32>) = G_FABS %0(<2 x s32>)
    %2:_(<2 x s32>) = G_FABS %1(<2 x s32>)
    $x0 = COPY %2(<2 x s32>)
...
---
name:            test_combine_half_fabs_neg_constant
body:             |
  bb.1:
    ; CHECK-LABEL: name: test_combine_half_fabs_neg_constant
    ; CHECK: [[C:%[0-9]+]]:_(s16) = G_FCONSTANT half 0xH4580
    ; CHECK-NEXT: $h0 = COPY [[C]](s16)
    %0:_(s16) = G_FCONSTANT half 0xHC580
    %1:_(s16) = G_FABS %0
    $h0 = COPY %1(s16)
...
---
name:            test_combine_half_fabs_pos_constant
body:             |
  bb.1:
    ; CHECK-LABEL: name: test_combine_half_fabs_pos_constant
    ; CHECK: [[C:%[0-9]+]]:_(s16) = G_FCONSTANT half 0xH4580
    ; CHECK-NEXT: $h0 = COPY [[C]](s16)
    %0:_(s16) = G_FCONSTANT half 0xH4580
    %1:_(s16) = G_FABS %0
    $h0 = COPY %1(s16)
...
---
name:            test_combine_float_fabs_neg_constant
body:             |
  bb.1:
    liveins: $w0
    ; CHECK-LABEL: name: test_combine_float_fabs_neg_constant
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float 5.500000e+00
    ; CHECK-NEXT: $w0 = COPY [[C]](s32)
    %0:_(s32) = G_FCONSTANT float -5.500000e+00
    %1:_(s32) = G_FABS %0
    $w0 = COPY %1(s32)
...
---
name:            test_combine_float_fabs_pos_constant
body:             |
  bb.1:
    liveins: $w0
    ; CHECK-LABEL: name: test_combine_float_fabs_pos_constant
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float 5.500000e+00
    ; CHECK-NEXT: $w0 = COPY [[C]](s32)
    %0:_(s32) = G_FCONSTANT float -5.500000e+00
    %1:_(s32) = G_FABS %0
    $w0 = COPY %1(s32)
...
---
name:            test_combine_double_fabs_neg_constant
body:             |
  bb.1:
    liveins: $x0
    ; CHECK-LABEL: name: test_combine_double_fabs_neg_constant
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 4.200000e+00
    ; CHECK-NEXT: $x0 = COPY [[C]](s64)
    %0:_(s64) = G_FCONSTANT double -4.200000e+00
    %1:_(s64) = G_FABS %0
    $x0 = COPY %1(s64)
...
---
name:            test_combine_double_fabs_pos_constant
body:             |
  bb.1:
    liveins: $x0
    ; CHECK-LABEL: name: test_combine_double_fabs_pos_constant
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 4.200000e+00
    ; CHECK-NEXT: $x0 = COPY [[C]](s64)
    %0:_(s64) = G_FCONSTANT double 4.200000e+00
    %1:_(s64) = G_FABS %0
    $x0 = COPY %0(s64)
...
