# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple aarch64 -run-pass=aarch64-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple aarch64 -passes='require<libcall-lowering-info>,function(machine-function(aarch64-prelegalizer-combiner))' %s -o - | FileCheck %s

---
name:            fma
liveins:
  - { reg: '$d0' }
body:             |
  bb.1.entry:
    liveins: $d0

    ; CHECK-LABEL: name: fma
    ; CHECK: liveins: $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %res:_(s64) = G_FCONSTANT double 8.100000e+01
    ; CHECK-NEXT: $d0 = COPY %res(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $d0
    %a:_(s64) = G_FCONSTANT double 40.0
    %b:_(s64) = G_FCONSTANT double 2.0
    %c:_(s64) = G_FCONSTANT double 1.0
    %res:_(s64) = G_FMA %a, %b, %c
    $d0 = COPY %res(s64)
    RET_ReallyLR implicit $d0

...

---
name:            fmad
liveins:
  - { reg: '$d0' }
body:             |
  bb.1.entry:
    liveins: $d0

    ; CHECK-LABEL: name: fmad
    ; CHECK: liveins: $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %res:_(s64) = G_FCONSTANT double 8.100000e+01
    ; CHECK-NEXT: $d0 = COPY %res(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $d0
    %a:_(s64) = G_FCONSTANT double 40.0
    %b:_(s64) = G_FCONSTANT double 2.0
    %c:_(s64) = G_FCONSTANT double 1.0
    %res:_(s64) = G_FMAD %a, %b, %c
    $d0 = COPY %res(s64)
    RET_ReallyLR implicit $d0

...
