; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -global-isel=0 -mtriple=aarch64 < %s | FileCheck %s --check-prefixes=CHECK,CHECK-SD
; RUN: llc -global-isel -mtriple=aarch64 < %s | FileCheck %s --check-prefixes=CHECK,CHECK-GI

declare i64 @llvm.smax.i64(i64, i64)
declare i64 @llvm.umax.i64(i64, i64)
declare <4 x i32> @llvm.smax.v4i32(<4 x i32>, <4 x i32>)
declare <4 x i32> @llvm.umax.v4i32(<4 x i32>, <4 x i32>)

; 0 - smax(a, 0 - a)  ->  smin(a, 0 - a)   (i.e. -abs(a))
define i64 @ASubSMax(i64 %a) {
; CHECK-SD-LABEL: ASubSMax:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    neg x8, x0
; CHECK-SD-NEXT:    cmp x0, x8
; CHECK-SD-NEXT:    cneg x0, x0, gt
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: ASubSMax:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    neg x8, x0
; CHECK-GI-NEXT:    cmp x0, x8
; CHECK-GI-NEXT:    cneg x0, x0, ge
; CHECK-GI-NEXT:    ret
  %sub1 = sub i64 0, %a
  %max = call i64 @llvm.smax.i64(i64 %a, i64 %sub1)
  %sub2 = sub i64 0, %max
  ret i64 %sub2
}

; Extra use of %max blocks the combine.
define i64 @ASubSMaxOneUse(i64 %a) {
; CHECK-LABEL: ASubSMaxOneUse:
; CHECK:       // %bb.0:
; CHECK-NEXT:    neg x8, x0
; CHECK-NEXT:    cmp x0, x8
; CHECK-NEXT:    cneg x8, x0, le
; CHECK-NEXT:    mneg x0, x8, x8
; CHECK-NEXT:    ret
  %sub1 = sub i64 0, %a
  %max = call i64 @llvm.smax.i64(i64 %a, i64 %sub1)
  %sub2 = sub i64 0, %max
  %mul = mul i64 %max, %sub2
  ret i64 %mul
}

; 0 - smax(a, 0 - a)  ->  smin(a, 0 - a)   (i.e. -abs(a))
define <4 x i32> @ASubSMaxVec(<4 x i32> %a) {
; CHECK-LABEL: ASubSMaxVec:
; CHECK:       // %bb.0:
; CHECK-NEXT:    neg v1.4s, v0.4s
; CHECK-NEXT:    smin v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
  %sub1 = sub <4 x i32> zeroinitializer, %a
  %max = call <4 x i32> @llvm.smax.v4i32(<4 x i32> %a, <4 x i32> %sub1)
  %sub2 = sub <4 x i32> zeroinitializer, %max
  ret <4 x i32> %sub2
}

; 0 - umax(a, 0 - a)  ->  umin(a, 0 - a)
define i64 @ASubUMax(i64 %a) {
; CHECK-SD-LABEL: ASubUMax:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    neg x8, x0
; CHECK-SD-NEXT:    cmp x0, x8
; CHECK-SD-NEXT:    cneg x0, x0, hi
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: ASubUMax:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    neg x8, x0
; CHECK-GI-NEXT:    cmp x0, x8
; CHECK-GI-NEXT:    cneg x0, x0, hs
; CHECK-GI-NEXT:    ret
  %sub1 = sub i64 0, %a
  %max = call i64 @llvm.umax.i64(i64 %a, i64 %sub1)
  %sub2 = sub i64 0, %max
  ret i64 %sub2
}

; 0 - umax(a, 0 - a)  ->  umin(a, 0 - a)
define <4 x i32> @ASubUMaxVec(<4 x i32> %a) {
; CHECK-LABEL: ASubUMaxVec:
; CHECK:       // %bb.0:
; CHECK-NEXT:    neg v1.4s, v0.4s
; CHECK-NEXT:    umin v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
  %sub1 = sub <4 x i32> zeroinitializer, %a
  %max = call <4 x i32> @llvm.umax.v4i32(<4 x i32> %a, <4 x i32> %sub1)
  %sub2 = sub <4 x i32> zeroinitializer, %max
  ret <4 x i32> %sub2
}
