# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -run-pass=aarch64-prelegalizer-combiner -verify-machineinstrs -mtriple aarch64-unknown-unknown %s -o - | FileCheck %s
# RUN: llc -passes='require<libcall-lowering-info>,function(machine-function(aarch64-prelegalizer-combiner))' -mtriple aarch64-unknown-unknown %s -o - | FileCheck %s

---
name:            test_combine_nan_rhs_fminnum_half
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_rhs_fminnum_half
    ; CHECK: [[COPY:%[0-9]+]]:_(s16) = COPY $h0
    ; CHECK-NEXT: $h0 = COPY [[COPY]](s16)
    %0:_(s16) = COPY $h0
    %1:_(s16) = G_FCONSTANT half 0xH7C01
    %2:_(s16) = G_FMINNUM %0, %1
    $h0 = COPY %2
...
---
name:            test_combine_nan_rhs_fminnum_float
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_rhs_fminnum_float
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: $w0 = COPY [[COPY]](s32)
    %0:_(s32) = COPY $w0
    %1:_(s32) = G_FCONSTANT float 0x7FF8000000000000
    %2:_(s32) = G_FMINNUM %0, %1
    $w0 = COPY %2
...
---
name:            test_combine_nan_rhs_fminnum_double
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_rhs_fminnum_double
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $x0
    ; CHECK-NEXT: $x0 = COPY [[COPY]](s64)
    %0:_(s64) = COPY $x0
    %1:_(s64) = G_FCONSTANT double 0x7FF8000000000000
    %2:_(s64) = G_FMINNUM %0, %1
    $x0 = COPY %2
...
---
name:            test_combine_nan_lhs_fminnum_half
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_lhs_fminnum_half
    ; CHECK: [[COPY:%[0-9]+]]:_(s16) = COPY $h0
    ; CHECK-NEXT: $h0 = COPY [[COPY]](s16)
    %0:_(s16) = COPY $h0
    %1:_(s16) = G_FCONSTANT half 0xH7C01
    %2:_(s16) = G_FMINNUM %1, %0
    $h0 = COPY %2
...
---
name:            test_combine_nan_lhs_fminnum_float
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_lhs_fminnum_float
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: $w0 = COPY [[COPY]](s32)
    %0:_(s32) = COPY $w0
    %1:_(s32) = G_FCONSTANT float 0x7FF8000000000000
    %2:_(s32) = G_FMINNUM %1, %0
    $w0 = COPY %2
...
---
name:            test_combine_nan_lhs_fminnum_double
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_lhs_fminnum_double
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $x0
    ; CHECK-NEXT: $x0 = COPY [[COPY]](s64)
    %0:_(s64) = COPY $x0
    %1:_(s64) = G_FCONSTANT double 0x7FF8000000000000
    %2:_(s64) = G_FMINNUM %1, %0
    $x0 = COPY %2
...
---
name:            test_combine_nan_rhs_fmaxnum_half
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_rhs_fmaxnum_half
    ; CHECK: [[COPY:%[0-9]+]]:_(s16) = COPY $h0
    ; CHECK-NEXT: $h0 = COPY [[COPY]](s16)
    %0:_(s16) = COPY $h0
    %1:_(s16) = G_FCONSTANT half 0xH7C01
    %2:_(s16) = G_FMAXNUM %0, %1
    $h0 = COPY %2
...
---
name:            test_combine_nan_rhs_fmaxnum_float
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_rhs_fmaxnum_float
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: $w0 = COPY [[COPY]](s32)
    %0:_(s32) = COPY $w0
    %1:_(s32) = G_FCONSTANT float 0x7FF8000000000000
    %2:_(s32) = G_FMAXNUM %0, %1
    $w0 = COPY %2
...
---
name:            test_combine_nan_rhs_fmaxnum_double
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_rhs_fmaxnum_double
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $x0
    ; CHECK-NEXT: $x0 = COPY [[COPY]](s64)
    %0:_(s64) = COPY $x0
    %1:_(s64) = G_FCONSTANT double 0x7FF8000000000000
    %2:_(s64) = G_FMAXNUM %0, %1
    $x0 = COPY %2
...
---
name:            test_combine_nan_lhs_fmaxnum_half
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_lhs_fmaxnum_half
    ; CHECK: [[COPY:%[0-9]+]]:_(s16) = COPY $h0
    ; CHECK-NEXT: $h0 = COPY [[COPY]](s16)
    %0:_(s16) = COPY $h0
    %1:_(s16) = G_FCONSTANT half 0xH7C01
    %2:_(s16) = G_FMAXNUM %1, %0
    $h0 = COPY %2
...
---
name:            test_combine_nan_lhs_fmaxnum_float
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_lhs_fmaxnum_float
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: $w0 = COPY [[COPY]](s32)
    %0:_(s32) = COPY $w0
    %1:_(s32) = G_FCONSTANT float 0x7FF8000000000000
    %2:_(s32) = G_FMAXNUM %1, %0
    $w0 = COPY %2
...
---
name:            test_combine_nan_lhs_fmaxnum_double
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_lhs_fmaxnum_double
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $x0
    ; CHECK-NEXT: $x0 = COPY [[COPY]](s64)
    %0:_(s64) = COPY $x0
    %1:_(s64) = G_FCONSTANT double 0x7FF8000000000000
    %2:_(s64) = G_FMAXNUM %1, %0
    $x0 = COPY %2
...
