# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -run-pass=aarch64-prelegalizer-combiner -verify-machineinstrs -mtriple aarch64-unknown-unknown %s -o - | FileCheck %s

---
name:            zext_const
body:             |
  bb.0:
    liveins: $w0, $w1
    ; CHECK-LABEL: name: zext_const
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 5
    ; CHECK-NEXT: $x0 = COPY [[C]](s64)
    %2:_(s32) = G_CONSTANT i32 5
    %3:_(s64) = G_ZEXT %2
    $x0 = COPY %3
...
---
name:            sext_const
body:             |
  bb.0:
    liveins: $q0, $q1
    ; CHECK-LABEL: name: sext_const
    ; CHECK: liveins: $q0, $q1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 -5
    ; CHECK-NEXT: $x0 = COPY [[C]](s64)
    %2:_(s32) = G_CONSTANT i32 -5
    %3:_(s64) = G_SEXT %2
    $x0 = COPY %3
...
---
name:            trunc_const
body:             |
  bb.0:
    liveins: $q0, $q1
    ; CHECK-LABEL: name: trunc_const
    ; CHECK: liveins: $q0, $q1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 705032704
    ; CHECK-NEXT: $w0 = COPY [[C]](s32)
    %2:_(s64) = G_CONSTANT i64 5000000000
    %3:_(s32) = G_TRUNC %2
    $w0 = COPY %3
...
---
name:            trunc_const_bv
body:             |
  bb.0:
    liveins: $q0, $q1
    ; CHECK-LABEL: name: trunc_const_bv
    ; CHECK: liveins: $q0, $q1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 5000000000
    ; CHECK-NEXT: %bv:_(<2 x s64>) = G_BUILD_VECTOR [[C]](s64), [[C]](s64)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(<2 x s32>) = G_TRUNC %bv(<2 x s64>)
    ; CHECK-NEXT: $x0 = COPY [[TRUNC]](<2 x s32>)
    %2:_(s64) = G_CONSTANT i64 5000000000
    %bv:_(<2 x s64>) = G_BUILD_VECTOR %2, %2
    %3:_(<2 x s32>) = G_TRUNC %bv
    $x0 = COPY %3
...
---
name:            anyext_const
body:             |
  bb.0:
    liveins: $q0, $q1
    ; CHECK-LABEL: name: anyext_const
    ; CHECK: liveins: $q0, $q1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 500
    ; CHECK-NEXT: $x0 = COPY [[C]](s64)
    %2:_(s32) = G_CONSTANT i32 500
    %3:_(s64) = G_ANYEXT %2
    $x0 = COPY %3
...
---
name:            mul_abs_const
body:             |
  bb.0:
    liveins: $q0, $q1
    ; CHECK-LABEL: name: mul_abs_const
    ; CHECK: liveins: $q0, $q1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: $x0 = COPY [[C]](s64)
    %x:_(s32) = COPY $w0
    %zero:_(s32) = G_CONSTANT i32 0
    %mul:_(s32) = G_MUL %x, %zero
    %3:_(s64) = G_ANYEXT %mul
    %abs:_(s64) = G_ABS %3
    $x0 = COPY %3
