# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -o - -mtriple=aarch64-unknown-unknown -run-pass=aarch64-prelegalizer-combiner %s | FileCheck %s

---
name:            ne_i1_to_xor
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1

    ; CHECK-LABEL: name: ne_i1_to_xor
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x32:_(s32) = COPY $w0
    ; CHECK-NEXT: %y32:_(s32) = COPY $w1
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR %x32, %y32
    ; CHECK-NEXT: %cmp:_(s1) = G_TRUNC [[XOR]](s32)
    ; CHECK-NEXT: %ext:_(s32) = G_ZEXT %cmp(s1)
    ; CHECK-NEXT: $w0 = COPY %ext(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x32:_(s32) = COPY $w0
    %y32:_(s32) = COPY $w1
    %x:_(s1) = G_TRUNC %x32(s32)
    %y:_(s1) = G_TRUNC %y32(s32)
    %cmp:_(s1) = G_ICMP intpred(ne), %x(s1), %y
    %ext:_(s32) = G_ZEXT %cmp(s1)
    $w0 = COPY %ext(s32)
    RET_ReallyLR implicit $w0

...
---
name:            eq_i1_to_xnor
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1

    ; CHECK-LABEL: name: eq_i1_to_xnor
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x32:_(s32) = COPY $w0
    ; CHECK-NEXT: %y32:_(s32) = COPY $w1
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s1) = G_CONSTANT i1 true
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR %x32, %y32
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[XOR]](s32)
    ; CHECK-NEXT: %cmp:_(s1) = G_XOR [[TRUNC]], [[C]]
    ; CHECK-NEXT: %ext:_(s32) = G_ZEXT %cmp(s1)
    ; CHECK-NEXT: $w0 = COPY %ext(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x32:_(s32) = COPY $w0
    %y32:_(s32) = COPY $w1
    %x:_(s1) = G_TRUNC %x32(s32)
    %y:_(s1) = G_TRUNC %y32(s32)
    %cmp:_(s1) = G_ICMP intpred(eq), %x(s1), %y
    %ext:_(s32) = G_ZEXT %cmp(s1)
    $w0 = COPY %ext(s32)
    RET_ReallyLR implicit $w0

...
---
name:            ult_i1_to_andn_lhs
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1

    ; CHECK-LABEL: name: ult_i1_to_andn_lhs
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x32:_(s32) = COPY $w0
    ; CHECK-NEXT: %y32:_(s32) = COPY $w1
    ; CHECK-NEXT: %x:_(s1) = G_TRUNC %x32(s32)
    ; CHECK-NEXT: %y:_(s1) = G_TRUNC %y32(s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s1) = G_CONSTANT i1 true
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s1) = G_XOR %x, [[C]]
    ; CHECK-NEXT: %cmp:_(s1) = G_AND [[XOR]], %y
    ; CHECK-NEXT: %ext:_(s32) = G_ZEXT %cmp(s1)
    ; CHECK-NEXT: $w0 = COPY %ext(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x32:_(s32) = COPY $w0
    %y32:_(s32) = COPY $w1
    %x:_(s1) = G_TRUNC %x32(s32)
    %y:_(s1) = G_TRUNC %y32(s32)
    %cmp:_(s1) = G_ICMP intpred(ult), %x(s1), %y
    %ext:_(s32) = G_ZEXT %cmp(s1)
    $w0 = COPY %ext(s32)
    RET_ReallyLR implicit $w0

...
---
name:            sgt_i1_to_andn_lhs
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1

    ; CHECK-LABEL: name: sgt_i1_to_andn_lhs
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x32:_(s32) = COPY $w0
    ; CHECK-NEXT: %y32:_(s32) = COPY $w1
    ; CHECK-NEXT: %x:_(s1) = G_TRUNC %x32(s32)
    ; CHECK-NEXT: %y:_(s1) = G_TRUNC %y32(s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s1) = G_CONSTANT i1 true
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s1) = G_XOR %x, [[C]]
    ; CHECK-NEXT: %cmp:_(s1) = G_AND [[XOR]], %y
    ; CHECK-NEXT: %ext:_(s32) = G_ZEXT %cmp(s1)
    ; CHECK-NEXT: $w0 = COPY %ext(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x32:_(s32) = COPY $w0
    %y32:_(s32) = COPY $w1
    %x:_(s1) = G_TRUNC %x32(s32)
    %y:_(s1) = G_TRUNC %y32(s32)
    %cmp:_(s1) = G_ICMP intpred(sgt), %x(s1), %y
    %ext:_(s32) = G_ZEXT %cmp(s1)
    $w0 = COPY %ext(s32)
    RET_ReallyLR implicit $w0

...
---
name:            ugt_i1_to_andn_rhs
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1

    ; CHECK-LABEL: name: ugt_i1_to_andn_rhs
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x32:_(s32) = COPY $w0
    ; CHECK-NEXT: %y32:_(s32) = COPY $w1
    ; CHECK-NEXT: %x:_(s1) = G_TRUNC %x32(s32)
    ; CHECK-NEXT: %y:_(s1) = G_TRUNC %y32(s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s1) = G_CONSTANT i1 true
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s1) = G_XOR %y, [[C]]
    ; CHECK-NEXT: %cmp:_(s1) = G_AND %x, [[XOR]]
    ; CHECK-NEXT: %ext:_(s32) = G_ZEXT %cmp(s1)
    ; CHECK-NEXT: $w0 = COPY %ext(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x32:_(s32) = COPY $w0
    %y32:_(s32) = COPY $w1
    %x:_(s1) = G_TRUNC %x32(s32)
    %y:_(s1) = G_TRUNC %y32(s32)
    %cmp:_(s1) = G_ICMP intpred(ugt), %x(s1), %y
    %ext:_(s32) = G_ZEXT %cmp(s1)
    $w0 = COPY %ext(s32)
    RET_ReallyLR implicit $w0

...
---
name:            slt_i1_to_andn_rhs
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1

    ; CHECK-LABEL: name: slt_i1_to_andn_rhs
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x32:_(s32) = COPY $w0
    ; CHECK-NEXT: %y32:_(s32) = COPY $w1
    ; CHECK-NEXT: %x:_(s1) = G_TRUNC %x32(s32)
    ; CHECK-NEXT: %y:_(s1) = G_TRUNC %y32(s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s1) = G_CONSTANT i1 true
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s1) = G_XOR %y, [[C]]
    ; CHECK-NEXT: %cmp:_(s1) = G_AND %x, [[XOR]]
    ; CHECK-NEXT: %ext:_(s32) = G_ZEXT %cmp(s1)
    ; CHECK-NEXT: $w0 = COPY %ext(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x32:_(s32) = COPY $w0
    %y32:_(s32) = COPY $w1
    %x:_(s1) = G_TRUNC %x32(s32)
    %y:_(s1) = G_TRUNC %y32(s32)
    %cmp:_(s1) = G_ICMP intpred(slt), %x(s1), %y
    %ext:_(s32) = G_ZEXT %cmp(s1)
    $w0 = COPY %ext(s32)
    RET_ReallyLR implicit $w0

...
---
name:            ule_i1_to_orn_lhs
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1

    ; CHECK-LABEL: name: ule_i1_to_orn_lhs
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x32:_(s32) = COPY $w0
    ; CHECK-NEXT: %y32:_(s32) = COPY $w1
    ; CHECK-NEXT: %x:_(s1) = G_TRUNC %x32(s32)
    ; CHECK-NEXT: %y:_(s1) = G_TRUNC %y32(s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s1) = G_CONSTANT i1 true
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s1) = G_XOR %x, [[C]]
    ; CHECK-NEXT: %cmp:_(s1) = G_OR [[XOR]], %y
    ; CHECK-NEXT: %ext:_(s32) = G_ZEXT %cmp(s1)
    ; CHECK-NEXT: $w0 = COPY %ext(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x32:_(s32) = COPY $w0
    %y32:_(s32) = COPY $w1
    %x:_(s1) = G_TRUNC %x32(s32)
    %y:_(s1) = G_TRUNC %y32(s32)
    %cmp:_(s1) = G_ICMP intpred(ule), %x(s1), %y
    %ext:_(s32) = G_ZEXT %cmp(s1)
    $w0 = COPY %ext(s32)
    RET_ReallyLR implicit $w0

...
---
name:            sge_i1_to_orn_lhs
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1

    ; CHECK-LABEL: name: sge_i1_to_orn_lhs
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x32:_(s32) = COPY $w0
    ; CHECK-NEXT: %y32:_(s32) = COPY $w1
    ; CHECK-NEXT: %x:_(s1) = G_TRUNC %x32(s32)
    ; CHECK-NEXT: %y:_(s1) = G_TRUNC %y32(s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s1) = G_CONSTANT i1 true
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s1) = G_XOR %x, [[C]]
    ; CHECK-NEXT: %cmp:_(s1) = G_OR [[XOR]], %y
    ; CHECK-NEXT: %ext:_(s32) = G_ZEXT %cmp(s1)
    ; CHECK-NEXT: $w0 = COPY %ext(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x32:_(s32) = COPY $w0
    %y32:_(s32) = COPY $w1
    %x:_(s1) = G_TRUNC %x32(s32)
    %y:_(s1) = G_TRUNC %y32(s32)
    %cmp:_(s1) = G_ICMP intpred(sge), %x(s1), %y
    %ext:_(s32) = G_ZEXT %cmp(s1)
    $w0 = COPY %ext(s32)
    RET_ReallyLR implicit $w0

...
---
name:            uge_i1_to_orn_rhs
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1

    ; CHECK-LABEL: name: uge_i1_to_orn_rhs
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x32:_(s32) = COPY $w0
    ; CHECK-NEXT: %y32:_(s32) = COPY $w1
    ; CHECK-NEXT: %x:_(s1) = G_TRUNC %x32(s32)
    ; CHECK-NEXT: %y:_(s1) = G_TRUNC %y32(s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s1) = G_CONSTANT i1 true
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s1) = G_XOR %y, [[C]]
    ; CHECK-NEXT: %cmp:_(s1) = G_OR %x, [[XOR]]
    ; CHECK-NEXT: %ext:_(s32) = G_ZEXT %cmp(s1)
    ; CHECK-NEXT: $w0 = COPY %ext(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x32:_(s32) = COPY $w0
    %y32:_(s32) = COPY $w1
    %x:_(s1) = G_TRUNC %x32(s32)
    %y:_(s1) = G_TRUNC %y32(s32)
    %cmp:_(s1) = G_ICMP intpred(uge), %x(s1), %y
    %ext:_(s32) = G_ZEXT %cmp(s1)
    $w0 = COPY %ext(s32)
    RET_ReallyLR implicit $w0

...
---
name:            sle_i1_to_orn_rhs
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1

    ; CHECK-LABEL: name: sle_i1_to_orn_rhs
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x32:_(s32) = COPY $w0
    ; CHECK-NEXT: %y32:_(s32) = COPY $w1
    ; CHECK-NEXT: %x:_(s1) = G_TRUNC %x32(s32)
    ; CHECK-NEXT: %y:_(s1) = G_TRUNC %y32(s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s1) = G_CONSTANT i1 true
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s1) = G_XOR %y, [[C]]
    ; CHECK-NEXT: %cmp:_(s1) = G_OR %x, [[XOR]]
    ; CHECK-NEXT: %ext:_(s32) = G_ZEXT %cmp(s1)
    ; CHECK-NEXT: $w0 = COPY %ext(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x32:_(s32) = COPY $w0
    %y32:_(s32) = COPY $w1
    %x:_(s1) = G_TRUNC %x32(s32)
    %y:_(s1) = G_TRUNC %y32(s32)
    %cmp:_(s1) = G_ICMP intpred(sle), %x(s1), %y
    %ext:_(s32) = G_ZEXT %cmp(s1)
    $w0 = COPY %ext(s32)
    RET_ReallyLR implicit $w0

...
---
# Negative: ne on s32 operands doesn't match because the rule is i1-only.
name:            ne_s32_no_combine
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1

    ; CHECK-LABEL: name: ne_s32_no_combine
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %y:_(s32) = COPY $w1
    ; CHECK-NEXT: %cmp:_(s1) = G_ICMP intpred(ne), %x(s32), %y
    ; CHECK-NEXT: %ext:_(s32) = G_ZEXT %cmp(s1)
    ; CHECK-NEXT: $w0 = COPY %ext(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x:_(s32) = COPY $w0
    %y:_(s32) = COPY $w1
    %cmp:_(s1) = G_ICMP intpred(ne), %x(s32), %y
    %ext:_(s32) = G_ZEXT %cmp(s1)
    $w0 = COPY %ext(s32)
    RET_ReallyLR implicit $w0

...
---
# Negative: eq on s32 operands doesn't match either.
name:            eq_s32_no_combine
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1

    ; CHECK-LABEL: name: eq_s32_no_combine
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %y:_(s32) = COPY $w1
    ; CHECK-NEXT: %cmp:_(s1) = G_ICMP intpred(eq), %x(s32), %y
    ; CHECK-NEXT: %ext:_(s32) = G_ZEXT %cmp(s1)
    ; CHECK-NEXT: $w0 = COPY %ext(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x:_(s32) = COPY $w0
    %y:_(s32) = COPY $w1
    %cmp:_(s1) = G_ICMP intpred(eq), %x(s32), %y
    %ext:_(s32) = G_ZEXT %cmp(s1)
    $w0 = COPY %ext(s32)
    RET_ReallyLR implicit $w0

...
