# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=aarch64-unknown-unknown -run-pass=aarch64-prelegalizer-combiner -verify-machineinstrs -o - %s | FileCheck %s
# RUN: llc -mtriple=aarch64-unknown-unknown -passes='require<libcall-lowering-info>,function(machine-function(aarch64-prelegalizer-combiner))' -o - %s | FileCheck %s

# Test unary_op(undef) -> 0 combines

...
---
name:            abs_scalar
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0
    ; CHECK-LABEL: name: abs_scalar
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %abs:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: $w0 = COPY %abs(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %undef:_(s32) = G_IMPLICIT_DEF
    %abs:_(s32) = G_ABS %undef
    $w0 = COPY %abs(s32)
    RET_ReallyLR implicit $w0
...
---
name:            abs_vector
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $d0
    ; CHECK-LABEL: name: abs_vector
    ; CHECK: liveins: $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: %abs:_(<2 x s32>) = G_BUILD_VECTOR [[C]](s32), [[C]](s32)
    ; CHECK-NEXT: $d0 = COPY %abs(<2 x s32>)
    ; CHECK-NEXT: RET_ReallyLR implicit $d0
    %undef:_(<2 x s32>) = G_IMPLICIT_DEF
    %abs:_(<2 x s32>) = G_ABS %undef
    $d0 = COPY %abs(<2 x s32>)
    RET_ReallyLR implicit $d0
...
