# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -run-pass=aarch64-prelegalizer-combiner -mtriple aarch64-unknown-unknown -mattr=+dotprod %s -o - | FileCheck %s

---
name:            vecreduce_intrinsic
body:             |
  bb.0:
    liveins: $q0, $q1, $q2, $q3, $q4
    ; CHECK-LABEL: name: vecreduce_intrinsic
    ; CHECK: liveins: $q0, $q1, $q2, $q3, $q4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s32>) = COPY $q0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(<4 x s32>) = COPY $q1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(<4 x s32>) = COPY $q2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(<4 x s32>) = COPY $q3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(<4 x s32>) = COPY $q4
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<16 x s32>) = G_CONCAT_VECTORS [[COPY1]](<4 x s32>), [[COPY2]](<4 x s32>), [[COPY3]](<4 x s32>), [[COPY4]](<4 x s32>)
    ; CHECK-NEXT: [[INT:%[0-9]+]]:_(<4 x s32>) = G_INTRINSIC intrinsic(@llvm.vector.partial.reduce.add), [[COPY]](<4 x s32>), [[CONCAT_VECTORS]](<16 x s32>)
    ; CHECK-NEXT: [[VECREDUCE_ADD:%[0-9]+]]:_(s32) = G_VECREDUCE_ADD [[INT]](<4 x s32>)
    ; CHECK-NEXT: $w0 = COPY [[VECREDUCE_ADD]](s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:_(<4 x s32>) = COPY $q0
    %2:_(<4 x s32>) = COPY $q1
    %3:_(<4 x s32>) = COPY $q2
    %4:_(<4 x s32>) = COPY $q3
    %5:_(<4 x s32>) = COPY $q4
    %1:_(<16 x s32>) = G_CONCAT_VECTORS %2:_(<4 x s32>), %3:_(<4 x s32>), %4:_(<4 x s32>), %5:_(<4 x s32>)
    %6:_(<4 x s32>) = G_INTRINSIC intrinsic(@llvm.vector.partial.reduce.add), %0:_(<4 x s32>), %1:_(<16 x s32>)
    %7:_(s32) = G_VECREDUCE_ADD %6:_(<4 x s32>)
    $w0 = COPY %7:_(s32)
    RET_ReallyLR implicit $w0

...

---
name:            NotAPlusNegOne_vec
alignment:       4
frameInfo:
  maxAlignment:    1
machineFunctionInfo: {}
body:             |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: NotAPlusNegOne_vec
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(<4 x s16>) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<4 x s16>) = G_BUILD_VECTOR [[C]](s16), [[C]](s16), [[C]](s16), [[C]](s16)
    ; CHECK-NEXT: %xor:_(<4 x s16>) = G_SUB [[BUILD_VECTOR]], %x
    ; CHECK-NEXT: $x0 = COPY %xor(<4 x s16>)
    %x:_(<4 x s16>) = COPY $x0
    %neg_one:_(s16) = G_CONSTANT i16 -1
    %neg_one_vec:_(<4 x s16>) = G_BUILD_VECTOR %neg_one(s16), %neg_one(s16), %neg_one(s16), %neg_one(s16)
    %add:_(<4 x s16>) = G_ADD %x, %neg_one_vec
    %xor:_(<4 x s16>) = G_XOR %add, %neg_one_vec
    $x0 = COPY %xor
...

