# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -run-pass=aarch64-prelegalizer-combiner -verify-machineinstrs -mtriple aarch64-unknown-unknown %s -o - | FileCheck %s
# RUN: llc -debugify-and-strip-all-safe -run-pass=aarch64-prelegalizer-combiner -verify-machineinstrs -mtriple aarch64-unknown-unknown %s -o - | FileCheck %s

---
name:            agc.test_combine_ptradd_constants_intres
body:             |
  bb.1:
    liveins: $x0
    ; CHECK-LABEL: name: agc.test_combine_ptradd_constants_intres
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(p64) = G_CONSTANT i64 44
    ; CHECK-NEXT: [[PTRTOINT:%[0-9]+]]:_(s64) = G_PTRTOINT [[C]](p64)
    ; CHECK-NEXT: $x0 = COPY [[PTRTOINT]](s64)
    %1:_(s64) = G_CONSTANT i64 42
    %2:_(s32) = G_CONSTANT i32 2
    %3:_(p64) = G_INTTOPTR %2
    %4:_(p64) = G_PTR_ADD %3, %1
    %5:_(s64) = G_PTRTOINT %4
    $x0 = COPY %5(s64)
...
---
name:            agc.test_combine_ptradd_constants_ptrres
body:             |
  bb.1:
    liveins: $x0
    ; CHECK-LABEL: name: agc.test_combine_ptradd_constants_ptrres
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(p64) = G_CONSTANT i64 44
    ; CHECK-NEXT: $x0 = COPY [[C]](p64)
    %1:_(s64) = G_CONSTANT i64 42
    %2:_(s32) = G_CONSTANT i32 2
    %3:_(p64) = G_INTTOPTR %2
    %4:_(p64) = G_PTR_ADD %3, %1
    $x0 = COPY %4(p64)
...
---
name:            agc.test_not_combine_variable_ptradd
body:             |
  bb.1:
    liveins: $x0, $x1
    ; Ensure non-constant G_PTR_ADDs are not folded.
    ; CHECK-LABEL: name: agc.test_not_combine_variable_ptradd
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 42
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p64) = COPY $x1
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p64) = G_PTR_ADD [[COPY]], [[C]](s64)
    ; CHECK-NEXT: [[PTRTOINT:%[0-9]+]]:_(s64) = G_PTRTOINT [[PTR_ADD]](p64)
    ; CHECK-NEXT: $x0 = COPY [[PTRTOINT]](s64)
    %1:_(s64) = G_CONSTANT i64 42
    %2:_(p64) = COPY $x1
    %3:_(p64) = G_PTR_ADD %2, %1
    %4:_(s64) = G_PTRTOINT %3
    $x0 = COPY %4(s64)
...
---
name:            test_combine_zero_extend
body:             |
  bb.1:
  liveins: $x0

    ; CHECK-LABEL: name: test_combine_zero_extend
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(p0) = G_CONSTANT i64 4291891236
    ; CHECK-NEXT: $x0 = COPY [[C]](p0)
    %0:_(s32) = G_CONSTANT i32 -3076096
    %1:_(p0) = G_INTTOPTR %0:_(s32)
    %2:_(s64) = G_CONSTANT i64 36
    %3:_(p0) = G_PTR_ADD %1:_, %2:_(s64)
    $x0 = COPY %3
...
