# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple aarch64 -run-pass=aarch64-postlegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s
---
name:            test_combine_sext_trunc_of_sextload
legalized:       true
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x0
    ; CHECK-LABEL: name: test_combine_sext_trunc_of_sextload
    ; CHECK: liveins: $x0
    ; CHECK: [[COPY:%[0-9]+]]:_(p0) = COPY $x0
    ; CHECK: [[SEXTLOAD:%[0-9]+]]:_(s64) = G_SEXTLOAD [[COPY]](p0) :: (load 2)
    ; CHECK: [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[SEXTLOAD]](s64)
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[TRUNC]](s32)
    ; CHECK: $w0 = COPY [[COPY1]](s32)
    %0:_(p0) = COPY $x0
    %1:_(s64) = G_SEXTLOAD %0:_(p0) :: (load 2)
    %2:_(s32) = G_TRUNC %1:_(s64)
    %3:_(s32) = G_SEXT_INREG %2:_(s32), 16
    $w0 = COPY %3(s32)
...
---
name:            test_combine_sext_of_sextload
legalized:       true
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x0
    ; CHECK-LABEL: name: test_combine_sext_of_sextload
    ; CHECK: liveins: $x0
    ; CHECK: [[COPY:%[0-9]+]]:_(p0) = COPY $x0
    ; CHECK: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[COPY]](p0) :: (load 2)
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[SEXTLOAD]](s32)
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: $w0 = COPY [[COPY2]](s32)
    %0:_(p0) = COPY $x0
    %1:_(s32) = G_SEXTLOAD %0:_(p0) :: (load 2)
    %2:_(s32) = COPY %1:_(s32)
    %3:_(s32) = G_SEXT_INREG %2:_(s32), 16
    $w0 = COPY %3(s32)
...
---
name:            test_combine_sext_of_sextload_not_matching
legalized:       true
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x0
    ; Here we're trying to extend from a larger width than was extended in the load.
    ; CHECK-LABEL: name: test_combine_sext_of_sextload_not_matching
    ; CHECK: liveins: $x0
    ; CHECK: [[COPY:%[0-9]+]]:_(p0) = COPY $x0
    ; CHECK: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[COPY]](p0) :: (load 2)
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[SEXTLOAD]](s32)
    ; CHECK: $w0 = COPY [[COPY1]](s32)
    %0:_(p0) = COPY $x0
    %1:_(s32) = G_SEXTLOAD %0:_(p0) :: (load 2)
    %2:_(s32) = G_SEXT_INREG %1:_(s32), 24
    $w0 = COPY %2(s32)
...
---
name:            test_combine_sext_of_sextload_not_enough_src_signbits
legalized:       true
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x0
    ; Here we're trying to extend from a smaller width than was extended in the load.
    ; Don't perform the combine.
    ; CHECK-LABEL: name: test_combine_sext_of_sextload_not_enough_src_signbits
    ; CHECK: liveins: $x0
    ; CHECK: [[COPY:%[0-9]+]]:_(p0) = COPY $x0
    ; CHECK: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[COPY]](p0) :: (load 2)
    ; CHECK: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[SEXTLOAD]], 8
    ; CHECK: $w0 = COPY [[SEXT_INREG]](s32)
    %0:_(p0) = COPY $x0
    %1:_(s32) = G_SEXTLOAD %0:_(p0) :: (load 2)
    %2:_(s32) = G_SEXT_INREG %1:_(s32), 8
    $w0 = COPY %2(s32)
...
