# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple aarch64 -run-pass=aarch64-prelegalizer-combiner %s -o - | FileCheck %s

---
name:   ASubSMax
body:             |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: ASubSMax
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %a:_(s64) = COPY $x0
    ; CHECK-NEXT: %zero:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s64) = G_SUB %zero, %a
    ; CHECK-NEXT: %sub2:_(s64) = G_SMIN %a, [[SUB]]
    ; CHECK-NEXT: $x0 = COPY %sub2(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $x0
    %a:_(s64) = COPY $x0
    %zero:_(s64) = G_CONSTANT i64 0
    %sub1:_(s64) = G_SUB %zero, %a
    %max:_(s64) = G_SMAX %a, %sub1
    %sub2:_(s64) = G_SUB %zero, %max
    $x0 = COPY %sub2
    RET_ReallyLR implicit $x0

...
---
name:   ASubSMaxOneUse
body:             |
  bb.0:
    liveins: $x0


    ; CHECK-LABEL: name: ASubSMaxOneUse
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %a:_(s64) = COPY $x0
    ; CHECK-NEXT: %zero:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: %sub1:_(s64) = G_SUB %zero, %a
    ; CHECK-NEXT: %max:_(s64) = G_SMAX %a, %sub1
    ; CHECK-NEXT: %sub2:_(s64) = G_SUB %zero, %max
    ; CHECK-NEXT: %mul:_(s64) = G_MUL %max, %sub2
    ; CHECK-NEXT: $x0 = COPY %mul(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $x0
    %a:_(s64) = COPY $x0
    %zero:_(s64) = G_CONSTANT i64 0
    %sub1:_(s64) = G_SUB %zero, %a
    %max:_(s64) = G_SMAX %a, %sub1
    %sub2:_(s64) = G_SUB %zero, %max
    %mul:_(s64) = G_MUL %max, %sub2
    $x0 = COPY %mul
    RET_ReallyLR implicit $x0

...
---
name:   ASubUMax
body:             |
  bb.0:
    liveins: $x0


    ; CHECK-LABEL: name: ASubUMax
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %a:_(s64) = COPY $x0
    ; CHECK-NEXT: %zero:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s64) = G_SUB %zero, %a
    ; CHECK-NEXT: %sub2:_(s64) = G_UMIN %a, [[SUB]]
    ; CHECK-NEXT: $x0 = COPY %sub2(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $x0
    %a:_(s64) = COPY $x0
    %zero:_(s64) = G_CONSTANT i64 0
    %sub1:_(s64) = G_SUB %zero, %a
    %max:_(s64) = G_UMAX %a, %sub1
    %sub2:_(s64) = G_SUB %zero, %max
    $x0 = COPY %sub2
    RET_ReallyLR implicit $x0

...
---
name:   ASubUMaxOneUse
body:             |
  bb.0:
    liveins: $x0


    ; CHECK-LABEL: name: ASubUMaxOneUse
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %a:_(s64) = COPY $x0
    ; CHECK-NEXT: %zero:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: %sub1:_(s64) = G_SUB %zero, %a
    ; CHECK-NEXT: %max:_(s64) = G_UMAX %a, %sub1
    ; CHECK-NEXT: %sub2:_(s64) = G_SUB %zero, %max
    ; CHECK-NEXT: %mul:_(s64) = G_MUL %max, %sub2
    ; CHECK-NEXT: $x0 = COPY %mul(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $x0
    %a:_(s64) = COPY $x0
    %zero:_(s64) = G_CONSTANT i64 0
    %sub1:_(s64) = G_SUB %zero, %a
    %max:_(s64) = G_UMAX %a, %sub1
    %sub2:_(s64) = G_SUB %zero, %max
    %mul:_(s64) = G_MUL %max, %sub2
    $x0 = COPY %mul
    RET_ReallyLR implicit $x0
