# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=aarch64 -run-pass=aarch64-postlegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name:            test_use_vector_truncate_reversed_order
tracksRegLiveness: true
legalized:        true
body:             |
  bb.0:
    liveins: $d0

    ; CHECK-LABEL: name: test_use_vector_truncate_reversed_order
    ; CHECK: liveins: $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s16>) = COPY $d0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s16), [[UV1:%[0-9]+]]:_(s16), [[UV2:%[0-9]+]]:_(s16), [[UV3:%[0-9]+]]:_(s16) = G_UNMERGE_VALUES [[COPY]](<4 x s16>)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[UV]](s16)
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(s8) = G_TRUNC [[UV1]](s16)
    ; CHECK-NEXT: [[TRUNC2:%[0-9]+]]:_(s8) = G_TRUNC [[UV2]](s16)
    ; CHECK-NEXT: [[TRUNC3:%[0-9]+]]:_(s8) = G_TRUNC [[UV3]](s16)
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<4 x s8>) = G_BUILD_VECTOR [[TRUNC3]](s8), [[TRUNC2]](s8), [[TRUNC1]](s8), [[TRUNC]](s8)
    ; CHECK-NEXT: $w0 = COPY [[BUILD_VECTOR]](<4 x s8>)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:_(<4 x s16>) = COPY $d0
    %1:_(s16), %2:_(s16), %3:_(s16), %4:_(s16) = G_UNMERGE_VALUES %0(<4 x s16>)
    %5:_(s8) = G_TRUNC %1(s16)
    %6:_(s8) = G_TRUNC %2(s16)
    %7:_(s8) = G_TRUNC %3(s16)
    %8:_(s8) = G_TRUNC %4(s16)
    ; Reversed operand order
    %9:_(<4 x s8>) = G_BUILD_VECTOR %8(s8), %7(s8), %6(s8), %5(s8)
    $w0 = COPY %9(<4 x s8>)
    RET_ReallyLR implicit $w0

...
---
name:            test_use_vector_truncate_normal_order
tracksRegLiveness: true
legalized:        true
body:             |
  bb.0:
    liveins: $d0

    ; CHECK-LABEL: name: test_use_vector_truncate_normal_order
    ; CHECK: liveins: $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s16>) = COPY $d0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s16), [[UV1:%[0-9]+]]:_(s16), [[UV2:%[0-9]+]]:_(s16), [[UV3:%[0-9]+]]:_(s16) = G_UNMERGE_VALUES [[COPY]](<4 x s16>)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[UV]](s16)
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(s8) = G_TRUNC [[UV1]](s16)
    ; CHECK-NEXT: [[TRUNC2:%[0-9]+]]:_(s8) = G_TRUNC [[UV2]](s16)
    ; CHECK-NEXT: [[TRUNC3:%[0-9]+]]:_(s8) = G_TRUNC [[UV3]](s16)
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<4 x s8>) = G_BUILD_VECTOR [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC3]](s8)
    ; CHECK-NEXT: $w0 = COPY [[BUILD_VECTOR]](<4 x s8>)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:_(<4 x s16>) = COPY $d0
    %1:_(s16), %2:_(s16), %3:_(s16), %4:_(s16) = G_UNMERGE_VALUES %0(<4 x s16>)
    %5:_(s8) = G_TRUNC %1(s16)
    %6:_(s8) = G_TRUNC %2(s16)
    %7:_(s8) = G_TRUNC %3(s16)
    %8:_(s8) = G_TRUNC %4(s16)
    ; Normal operand order
    %9:_(<4 x s8>) = G_BUILD_VECTOR %5(s8), %6(s8), %7(s8), %8(s8)
    $w0 = COPY %9(<4 x s8>)
    RET_ReallyLR implicit $w0
...
---
name:            test_use_vector_truncate_double_v4i32
tracksRegLiveness: true
legalized:        true
body:             |
  bb.0:
    liveins: $q0

    ; CHECK-LABEL: name: test_use_vector_truncate_double_v4i32
    ; CHECK: liveins: $q0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s32>) = COPY $q0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32), [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](<4 x s32>)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[UV]](s32)
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(s8) = G_TRUNC [[UV1]](s32)
    ; CHECK-NEXT: [[TRUNC2:%[0-9]+]]:_(s8) = G_TRUNC [[UV2]](s32)
    ; CHECK-NEXT: [[TRUNC3:%[0-9]+]]:_(s8) = G_TRUNC [[UV3]](s32)
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<4 x s8>) = G_BUILD_VECTOR [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC3]](s8)
    ; CHECK-NEXT: $s0 = COPY [[BUILD_VECTOR]](<4 x s8>)
    ; CHECK-NEXT: RET_ReallyLR implicit $s0
    %0:_(<4 x s32>) = COPY $q0
    %1:_(s32), %2:_(s32), %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %0(<4 x s32>)
    %5:_(s8) = G_TRUNC %1(s32)
    %6:_(s8) = G_TRUNC %2(s32)
    %7:_(s8) = G_TRUNC %3(s32)
    %8:_(s8) = G_TRUNC %4(s32)
    %9:_(<4 x s8>) = G_BUILD_VECTOR %5(s8), %6(s8), %7(s8), %8(s8)
    $s0 = COPY %9(<4 x s8>)
    RET_ReallyLR implicit $s0
...
---
name:            test_use_vector_truncate_double_v2i64
tracksRegLiveness: true
legalized:        true
body:             |
  bb.0:
    liveins: $q0

    ; CHECK-LABEL: name: test_use_vector_truncate_double_v2i64
    ; CHECK: liveins: $q0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x i64>) = COPY $q0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(i64), [[UV1:%[0-9]+]]:_(i64) = G_UNMERGE_VALUES [[COPY]](<2 x i64>)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[UV]](i64)
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[UV1]](i64)
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
    ; CHECK-NEXT: $s0 = COPY [[BUILD_VECTOR]](<2 x s16>)
    ; CHECK-NEXT: RET_ReallyLR implicit $s0
    %0:_(<2 x i64>) = COPY $q0
    %1:_(i64), %2:_(i64) = G_UNMERGE_VALUES %0(<2 x i64>)
    %3:_(s16) = G_TRUNC %1(i64)
    %4:_(s16) = G_TRUNC %2(i64)
    %9:_(<2 x s16>) = G_BUILD_VECTOR %3(s16), %4(s16)
    $s0 = COPY %9(<2 x s16>)
    RET_ReallyLR implicit $s0
...
---
name:            test_use_vector_truncate_double_v4i32_undef
tracksRegLiveness: true
legalized:        true
body:             |
  bb.0:
    liveins: $q0

    ; CHECK-LABEL: name: test_use_vector_truncate_double_v4i32_undef
    ; CHECK: liveins: $q0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x s32>) = COPY $q0
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(<4 x s16>) = G_TRUNC [[COPY]](<4 x s32>)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<4 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x s16>) = G_CONCAT_VECTORS [[TRUNC]](<4 x s16>), [[DEF]](<4 x s16>)
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(<8 x s8>) = G_TRUNC [[CONCAT_VECTORS]](<8 x s16>)
    ; CHECK-NEXT: $d0 = COPY [[TRUNC1]](<8 x s8>)
    ; CHECK-NEXT: RET_ReallyLR implicit $s0
    %0:_(<4 x s32>) = COPY $q0
    %1:_(s32), %2:_(s32), %3:_(s32), %4:_(s32) = G_UNMERGE_VALUES %0(<4 x s32>)
    %5:_(s8) = G_TRUNC %1(s32)
    %6:_(s8) = G_TRUNC %2(s32)
    %7:_(s8) = G_TRUNC %3(s32)
    %8:_(s8) = G_TRUNC %4(s32)
    %9:_(s8) = G_IMPLICIT_DEF
    %10:_(<8 x s8>) = G_BUILD_VECTOR %5(s8), %6(s8), %7(s8), %8(s8), %9(s8), %9(s8), %9(s8), %9(s8)
    $d0 = COPY %10(<8 x s8>)
    RET_ReallyLR implicit $s0
...
---
name:            test_use_vector_truncate_double_v2i64_undef
tracksRegLiveness: true
legalized:        true
body:             |
  bb.0:
    liveins: $q0

    ; CHECK-LABEL: name: test_use_vector_truncate_double_v2i64_undef
    ; CHECK: liveins: $q0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x i64>) = COPY $q0
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(<2 x i32>) = G_TRUNC [[COPY]](<2 x i64>)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<2 x i32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<4 x i32>) = G_CONCAT_VECTORS [[TRUNC]](<2 x i32>), [[DEF]](<2 x i32>)
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(<4 x s16>) = G_TRUNC [[CONCAT_VECTORS]](<4 x i32>)
    ; CHECK-NEXT: $d0 = COPY [[TRUNC1]](<4 x s16>)
    ; CHECK-NEXT: RET_ReallyLR implicit $s0
    %0:_(<2 x i64>) = COPY $q0
    %1:_(i64), %2:_(i64) = G_UNMERGE_VALUES %0(<2 x i64>)
    %3:_(s16) = G_TRUNC %1(i64)
    %4:_(s16) = G_TRUNC %2(i64)
    %5:_(s16) = G_IMPLICIT_DEF
    %6:_(<4 x s16>) = G_BUILD_VECTOR %3(s16), %4(s16), %5(s16), %5(s16)
    $d0 = COPY %6(<4 x s16>)
    RET_ReallyLR implicit $s0
...
---
name:            test_use_vector_truncate_triple_v2i64_undef
tracksRegLiveness: true
legalized:        true
body:             |
  bb.0:
    liveins: $q0

    ; CHECK-LABEL: name: test_use_vector_truncate_triple_v2i64_undef
    ; CHECK: liveins: $q0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x i64>) = COPY $q0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(i64), [[UV1:%[0-9]+]]:_(i64) = G_UNMERGE_VALUES [[COPY]](<2 x i64>)
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[UV]](i64)
    ; CHECK-NEXT: [[TRUNC1:%[0-9]+]]:_(s8) = G_TRUNC [[UV1]](i64)
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s8) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s8>) = G_BUILD_VECTOR [[TRUNC]](s8), [[TRUNC1]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8), [[DEF]](s8)
    ; CHECK-NEXT: $d0 = COPY [[BUILD_VECTOR]](<8 x s8>)
    ; CHECK-NEXT: RET_ReallyLR implicit $s0
    %0:_(<2 x i64>) = COPY $q0
    %1:_(i64), %2:_(i64) = G_UNMERGE_VALUES %0(<2 x i64>)
    %3:_(s8) = G_TRUNC %1(i64)
    %4:_(s8) = G_TRUNC %2(i64)
    %5:_(s8) = G_IMPLICIT_DEF
    %6:_(<8 x s8>) = G_BUILD_VECTOR %3(s8), %4(s8), %5(s8), %5(s8), %5(s8), %5(s8), %5(s8), %5(s8)
    $d0 = COPY %6(<8 x s8>)
    RET_ReallyLR implicit $s0
...
