# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -run-pass=aarch64-prelegalizer-combiner -verify-machineinstrs -mtriple aarch64-unknown-unknown %s -o - | FileCheck %s
# RUN: llc -passes='require<libcall-lowering-info>,function(machine-function(aarch64-prelegalizer-combiner))' -mtriple aarch64-unknown-unknown %s -o - | FileCheck %s
# RUN: llc -debugify-and-strip-all-safe -run-pass=aarch64-prelegalizer-combiner -verify-machineinstrs -mtriple aarch64-unknown-unknown %s -o - | FileCheck %s
# RUN: llc -debugify-and-strip-all-safe -passes='require<libcall-lowering-info>,function(machine-function(aarch64-prelegalizer-combiner))' -mtriple aarch64-unknown-unknown %s -o - | FileCheck %s
---
name:            test_combine_inttoptr_same_addressspace
body:             |
  bb.1:
  liveins: $x0, $x1

    ; CHECK-LABEL: name: test_combine_inttoptr_same_addressspace
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p64) = COPY $x0
    ; CHECK-NEXT: $x1 = COPY [[COPY]](p64)
    %0:_(p64) = COPY $x0
    %1:_(s64) = G_PTRTOINT %0
    %2:_(p64) = G_INTTOPTR %1
    $x1 = COPY %2
...
---
name:            test_combine_inttoptr_diff_addressspace
body:             |
  bb.1:
  liveins: $x0, $x1

    ; CHECK-LABEL: name: test_combine_inttoptr_diff_addressspace
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $x0
    ; CHECK-NEXT: [[PTRTOINT:%[0-9]+]]:_(s64) = G_PTRTOINT [[COPY]](p0)
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p64) = G_INTTOPTR [[PTRTOINT]](s64)
    ; CHECK-NEXT: $x1 = COPY [[INTTOPTR]](p64)
    %0:_(p0) = COPY $x0
    %1:_(s64) = G_PTRTOINT %0
    %2:_(p64) = G_INTTOPTR %1
    $x1 = COPY %2
...
