# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -run-pass=aarch64-prelegalizer-combiner -mtriple=aarch64-unknown-unknown %s -o - | FileCheck %s

---
name:            or_and_xor_to_or
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1
    ; CHECK-LABEL: name: or_and_xor_to_or
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %y:_(s32) = COPY $w1
    ; CHECK-NEXT: %or:_(s32) = G_OR %x, %y
    ; CHECK-NEXT: $w0 = COPY %or(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x:_(s32) = COPY $w0
    %y:_(s32) = COPY $w1
    %negone:_(s32) = G_CONSTANT i32 -1
    %not:_(s32) = G_XOR %y, %negone
    %and:_(s32) = G_AND %x, %not
    %or:_(s32) = G_OR %and, %y
    $w0 = COPY %or(s32)
    RET_ReallyLR implicit $w0
...
---
name:            or_and_xor_to_or_vector
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $q0, $q1
    ; CHECK-LABEL: name: or_and_xor_to_or_vector
    ; CHECK: liveins: $q0, $q1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(<4 x s32>) = COPY $q0
    ; CHECK-NEXT: %y:_(<4 x s32>) = COPY $q1
    ; CHECK-NEXT: %or:_(<4 x s32>) = G_OR %x, %y
    ; CHECK-NEXT: $q0 = COPY %or(<4 x s32>)
    ; CHECK-NEXT: RET_ReallyLR implicit $q0
    %x:_(<4 x s32>) = COPY $q0
    %y:_(<4 x s32>) = COPY $q1
    %negone:_(s32) = G_CONSTANT i32 -1
    %splat:_(<4 x s32>) = G_BUILD_VECTOR %negone, %negone, %negone, %negone
    %not:_(<4 x s32>) = G_XOR %y, %splat
    %and:_(<4 x s32>) = G_AND %x, %not
    %or:_(<4 x s32>) = G_OR %and, %y
    $q0 = COPY %or(<4 x s32>)
    RET_ReallyLR implicit $q0
...

---
name:            or_and_xor_to_xor_or
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1
    ; CHECK-LABEL: name: or_and_xor_to_xor_or
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %y:_(s32) = COPY $w1
    ; CHECK-NEXT: %negone:_(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR %y, %negone
    ; CHECK-NEXT: %or:_(s32) = G_OR %x, [[XOR]]
    ; CHECK-NEXT: $w0 = COPY %or(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x:_(s32) = COPY $w0
    %y:_(s32) = COPY $w1
    %negone:_(s32) = G_CONSTANT i32 -1
    %and:_(s32) = G_AND %x, %y
    %not:_(s32) = G_XOR %y, %negone
    %or:_(s32) = G_OR %and, %not
    $w0 = COPY %or(s32)
    RET_ReallyLR implicit $w0
...
---
name:            or_and_xor_to_xor_or_vector
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $q0, $q1
    ; CHECK-LABEL: name: or_and_xor_to_xor_or_vector
    ; CHECK: liveins: $q0, $q1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(<4 x s32>) = COPY $q0
    ; CHECK-NEXT: %y:_(<4 x s32>) = COPY $q1
    ; CHECK-NEXT: %negone:_(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: %splat:_(<4 x s32>) = G_BUILD_VECTOR %negone(s32), %negone(s32), %negone(s32), %negone(s32)
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(<4 x s32>) = G_XOR %y, %splat
    ; CHECK-NEXT: %or:_(<4 x s32>) = G_OR %x, [[XOR]]
    ; CHECK-NEXT: $q0 = COPY %or(<4 x s32>)
    ; CHECK-NEXT: RET_ReallyLR implicit $q0
    %x:_(<4 x s32>) = COPY $q0
    %y:_(<4 x s32>) = COPY $q1
    %negone:_(s32) = G_CONSTANT i32 -1
    %splat:_(<4 x s32>) = G_BUILD_VECTOR %negone, %negone, %negone, %negone
    %and:_(<4 x s32>) = G_AND %x, %y
    %not:_(<4 x s32>) = G_XOR %y, %splat
    %or:_(<4 x s32>) = G_OR %and, %not
    $q0 = COPY %or(<4 x s32>)
    RET_ReallyLR implicit $q0
...

---
name:            and_xor_or_to_and
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1
    ; CHECK-LABEL: name: and_xor_or_to_and
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %y:_(s32) = COPY $w1
    ; CHECK-NEXT: %and:_(s32) = G_AND %x, %y
    ; CHECK-NEXT: $w0 = COPY %and(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x:_(s32) = COPY $w0
    %y:_(s32) = COPY $w1
    %negone:_(s32) = G_CONSTANT i32 -1
    %not:_(s32) = G_XOR %y, %negone
    %or:_(s32) = G_OR %x, %not
    %and:_(s32) = G_AND %or, %y
    $w0 = COPY %and(s32)
    RET_ReallyLR implicit $w0
...

---
name:            and_xor_or_to_and_vector
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $q0, $q1
    ; CHECK-LABEL: name: and_xor_or_to_and_vector
    ; CHECK: liveins: $q0, $q1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(<4 x s32>) = COPY $q0
    ; CHECK-NEXT: %y:_(<4 x s32>) = COPY $q1
    ; CHECK-NEXT: %and:_(<4 x s32>) = G_AND %x, %y
    ; CHECK-NEXT: $q0 = COPY %and(<4 x s32>)
    ; CHECK-NEXT: RET_ReallyLR implicit $q0
    %x:_(<4 x s32>) = COPY $q0
    %y:_(<4 x s32>) = COPY $q1
    %negone:_(s32) = G_CONSTANT i32 -1
    %splat:_(<4 x s32>) = G_BUILD_VECTOR %negone, %negone, %negone, %negone
    %not:_(<4 x s32>) = G_XOR %y, %splat
    %or:_(<4 x s32>) = G_OR %x, %not
    %and:_(<4 x s32>) = G_AND %or, %y
    $q0 = COPY %and(<4 x s32>)
    RET_ReallyLR implicit $q0
...

---
name:            and_xor_or_to_xor_and
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0, $w1
    ; CHECK-LABEL: name: and_xor_or_to_xor_and
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $w0
    ; CHECK-NEXT: %y:_(s32) = COPY $w1
    ; CHECK-NEXT: %negone:_(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR %y, %negone
    ; CHECK-NEXT: %and:_(s32) = G_AND %x, [[XOR]]
    ; CHECK-NEXT: $w0 = COPY %and(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %x:_(s32) = COPY $w0
    %y:_(s32) = COPY $w1
    %negone:_(s32) = G_CONSTANT i32 -1
    %not:_(s32) = G_XOR %y, %negone
    %or:_(s32) = G_OR %x, %y
    %and:_(s32) = G_AND %or, %not
    $w0 = COPY %and(s32)
    RET_ReallyLR implicit $w0
...

---
name:            and_xor_or_to_xor_and_vector
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $q0, $q1
    ; CHECK-LABEL: name: and_xor_or_to_xor_and_vector
    ; CHECK: liveins: $q0, $q1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(<4 x s32>) = COPY $q0
    ; CHECK-NEXT: %y:_(<4 x s32>) = COPY $q1
    ; CHECK-NEXT: %negone:_(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: %splat:_(<4 x s32>) = G_BUILD_VECTOR %negone(s32), %negone(s32), %negone(s32), %negone(s32)
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:_(<4 x s32>) = G_XOR %y, %splat
    ; CHECK-NEXT: %and:_(<4 x s32>) = G_AND %x, [[XOR]]
    ; CHECK-NEXT: $q0 = COPY %and(<4 x s32>)
    ; CHECK-NEXT: RET_ReallyLR implicit $q0
    %x:_(<4 x s32>) = COPY $q0
    %y:_(<4 x s32>) = COPY $q1
    %negone:_(s32) = G_CONSTANT i32 -1
    %splat:_(<4 x s32>) = G_BUILD_VECTOR %negone, %negone, %negone, %negone
    %not:_(<4 x s32>) = G_XOR %y, %splat
    %or:_(<4 x s32>) = G_OR %x, %y
    %and:_(<4 x s32>) = G_AND %or, %not
    $q0 = COPY %and(<4 x s32>)
    RET_ReallyLR implicit $q0
...
