; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -global-isel=0 -mtriple=aarch64 < %s | FileCheck %s --check-prefixes=CHECK,CHECK-SD
; RUN: llc -global-isel=1 -mtriple=aarch64 < %s | FileCheck %s --check-prefixes=CHECK,CHECK-GI

define i32 @or_and_xor_to_or(i32 %x, i32 %y) {
; CHECK-LABEL: or_and_xor_to_or:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    orr w0, w0, w1
; CHECK-NEXT:    ret
entry:
; fold (or (and X, (xor Y, -1)), Y) -> (or X, Y)
  %not = xor i32 %y, -1
  %and = and i32 %x, %not
  %or = or i32 %and, %y
  ret i32 %or
}

define i64 @or_and_xor_to_or_i64(i64 %x, i64 %y) {
; CHECK-LABEL: or_and_xor_to_or_i64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    orr x0, x0, x1
; CHECK-NEXT:    ret
entry:
; fold (or (and X, (xor Y, -1)), Y) -> (or X, Y)
  %not = xor i64 %y, -1
  %and = and i64 %x, %not
  %or = or i64 %and, %y
  ret i64 %or
}

define <4 x i32> @or_and_xor_to_or_vector(<4 x i32> %x, <4 x i32> %y) {
; CHECK-LABEL: or_and_xor_to_or_vector:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    orr v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    ret
entry:
; fold (or (and X, (xor Y, -1)), Y) -> (or X, Y)
  %not = xor <4 x i32> %y, <i32 -1, i32 -1, i32 -1, i32 -1>
  %and = and <4 x i32> %x, %not
  %or = or <4 x i32> %and, %y
  ret <4 x i32> %or
}

define i32 @or_and_xor_to_xor_or(i32 %x, i32 %y) {
; CHECK-SD-LABEL: or_and_xor_to_xor_or:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    and w8, w0, w1
; CHECK-SD-NEXT:    orn w0, w8, w1
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: or_and_xor_to_xor_or:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    orn w0, w0, w1
; CHECK-GI-NEXT:    ret
entry:
; (X&Y)|~Y --> X|~Y
  %not = xor i32 %y, -1
  %and = and i32 %x, %y
  %or = or i32 %and, %not
  ret i32 %or
}

define i64 @or_and_xor_to_xor_or_i64(i64 %x, i64 %y) {
; CHECK-SD-LABEL: or_and_xor_to_xor_or_i64:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    and x8, x0, x1
; CHECK-SD-NEXT:    orn x0, x8, x1
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: or_and_xor_to_xor_or_i64:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    orn x0, x0, x1
; CHECK-GI-NEXT:    ret
entry:
; (X&Y)|~Y --> X|~Y
  %not = xor i64 %y, -1
  %and = and i64 %x, %y
  %or = or i64 %and, %not
  ret i64 %or
}

define <4 x i32> @or_and_xor_to_xor_or_vector(<4 x i32> %x, <4 x i32> %y) {
; CHECK-SD-LABEL: or_and_xor_to_xor_or_vector:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-SD-NEXT:    orn v0.16b, v0.16b, v1.16b
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: or_and_xor_to_xor_or_vector:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    orn v0.16b, v0.16b, v1.16b
; CHECK-GI-NEXT:    ret
entry:
; (X&Y)|~Y --> X|~Y
  %not = xor <4 x i32> %y, <i32 -1, i32 -1, i32 -1, i32 -1>
  %and = and <4 x i32> %x, %y
  %or = or <4 x i32> %and, %not
  ret <4 x i32> %or
}

define i32 @and_or_xor_to_and(i32 %x, i32 %y) {
; CHECK-SD-LABEL: and_or_xor_to_and:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    orn w8, w0, w1
; CHECK-SD-NEXT:    and w0, w8, w1
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: and_or_xor_to_and:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    and w0, w0, w1
; CHECK-GI-NEXT:    ret
entry:
; (X|~Y)&Y --> X&Y
  %not = xor i32 %y, -1
  %or = or i32 %x, %not
  %and = and i32 %or, %y
  ret i32 %and
}

define i64 @and_or_xor_to_and_i64(i64 %x, i64 %y) {
; CHECK-SD-LABEL: and_or_xor_to_and_i64:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    orn x8, x0, x1
; CHECK-SD-NEXT:    and x0, x8, x1
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: and_or_xor_to_and_i64:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    and x0, x0, x1
; CHECK-GI-NEXT:    ret
entry:
; (X|~Y)&Y --> X&Y
  %not = xor i64 %y, -1
  %or = or i64 %x, %not
  %and = and i64 %or, %y
  ret i64 %and
}

define <4 x i32> @and_or_xor_to_and_vector(<4 x i32> %x, <4 x i32> %y) {
; CHECK-SD-LABEL: and_or_xor_to_and_vector:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    orn v0.16b, v0.16b, v1.16b
; CHECK-SD-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: and_or_xor_to_and_vector:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-GI-NEXT:    ret
entry:
; (X|~Y)&Y --> X&Y
  %not = xor <4 x i32> %y, <i32 -1, i32 -1, i32 -1, i32 -1>
  %or = or <4 x i32> %x, %not
  %and = and <4 x i32> %or, %y
  ret <4 x i32> %and
}

define i32 @and_or_xor_to_xor_and(i32 %x, i32 %y) {
; CHECK-SD-LABEL: and_or_xor_to_xor_and:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    orr w8, w0, w1
; CHECK-SD-NEXT:    bic w0, w8, w1
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: and_or_xor_to_xor_and:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    bic w0, w0, w1
; CHECK-GI-NEXT:    ret
entry:
; (X|Y)&~Y --> X&~Y
  %not = xor i32 %y, -1
  %or = or i32 %x, %y
  %and = and i32 %or, %not
  ret i32 %and
}

define i64 @and_or_xor_to_xor_and_i64(i64 %x, i64 %y) {
; CHECK-SD-LABEL: and_or_xor_to_xor_and_i64:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    orr x8, x0, x1
; CHECK-SD-NEXT:    bic x0, x8, x1
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: and_or_xor_to_xor_and_i64:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    bic x0, x0, x1
; CHECK-GI-NEXT:    ret
entry:
; (X|Y)&~Y --> X&~Y
  %not = xor i64 %y, -1
  %or = or i64 %x, %y
  %and = and i64 %or, %not
  ret i64 %and
}

define <4 x i32> @and_or_xor_to_xor_and_vector(<4 x i32> %x, <4 x i32> %y) {
; CHECK-SD-LABEL: and_or_xor_to_xor_and_vector:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    orr v0.16b, v0.16b, v1.16b
; CHECK-SD-NEXT:    bic v0.16b, v0.16b, v1.16b
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: and_or_xor_to_xor_and_vector:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    bic v0.16b, v0.16b, v1.16b
; CHECK-GI-NEXT:    ret
entry:
; (X|Y)&~Y --> X&~Y
  %not = xor <4 x i32> %y, <i32 -1, i32 -1, i32 -1, i32 -1>
  %or = or <4 x i32> %x, %y
  %and = and <4 x i32> %or, %not
  ret <4 x i32> %and
}
