# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=aarch64 -run-pass=aarch64-postlegalizer-combiner -aarch64postlegalizercombiner-only-enable-rule=simplify_demanded_bits -verify-machineinstrs %s -o - | FileCheck %s --check-prefixes=CHECK,RULE
# RUN: llc -mtriple=aarch64 -run-pass=aarch64-postlegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s --check-prefixes=CHECK,FULL
---
name:            drop_redundant_outer_mask
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0
    ; CHECK-LABEL: name: drop_redundant_outer_mask
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: %lowmask:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: %and2:_(s32) = G_AND [[COPY]], %lowmask
    ; CHECK-NEXT: $w0 = COPY %and2(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:_(s32) = COPY $w0
    %mask:_(s32) = G_CONSTANT i32 255
    %and:_(s32) = G_AND %0, %mask
    %lowmask:_(s32) = G_CONSTANT i32 15
    %and2:_(s32) = G_AND %and, %lowmask
    $w0 = COPY %and2(s32)
    RET_ReallyLR implicit $w0
...
---
name:            keep_and_multiuse_high_bits
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0
    ; RULE-LABEL: name: keep_and_multiuse_high_bits
    ; RULE: liveins: $x0
    ; RULE-NEXT: {{  $}}
    ; RULE-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $x0
    ; RULE-NEXT: %c:_(s64) = G_CONSTANT i64 4294967295
    ; RULE-NEXT: %and:_(s64) = G_AND [[COPY]], %c
    ; RULE-NEXT: %lo:_(s32) = G_TRUNC %and(s64)
    ; RULE-NEXT: %amt:_(s64) = G_CONSTANT i64 40
    ; RULE-NEXT: %hi:_(s64) = G_LSHR %c, %amt(s64)
    ; RULE-NEXT: $w0 = COPY %lo(s32)
    ; RULE-NEXT: $x1 = COPY %hi(s64)
    ; RULE-NEXT: RET_ReallyLR implicit $w0, implicit $x1
    ;
    ; FULL-LABEL: name: keep_and_multiuse_high_bits
    ; FULL: liveins: $x0
    ; FULL-NEXT: {{  $}}
    ; FULL-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $x0
    ; FULL-NEXT: %c:_(s64) = G_CONSTANT i64 4294967295
    ; FULL-NEXT: %and:_(s64) = G_AND [[COPY]], %c
    ; FULL-NEXT: %lo:_(s32) = G_TRUNC %and(s64)
    ; FULL-NEXT: %hi:_(s64) = G_CONSTANT i64 0
    ; FULL-NEXT: $w0 = COPY %lo(s32)
    ; FULL-NEXT: $x1 = COPY %hi(s64)
    ; FULL-NEXT: RET_ReallyLR implicit $w0, implicit $x1
    %0:_(s64) = COPY $x0
    %c:_(s64) = G_CONSTANT i64 4294967295
    %and:_(s64) = G_AND %0, %c
    %lo:_(s32) = G_TRUNC %and(s64)
    %amt:_(s64) = G_CONSTANT i64 40
    %hi:_(s64) = G_LSHR %and, %amt(s64)
    $w0 = COPY %lo(s32)
    $x1 = COPY %hi(s64)
    RET_ReallyLR implicit $w0, implicit $x1
...
---
# (or X, C) feeding a use that only demands bits where C is zero: the constant
# or-bits are entirely undemanded, so the disjoint G_OR is dropped and the use
# reads X directly.
name:            drop_disjoint_or_high_const
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0
    ; CHECK-LABEL: name: drop_disjoint_or_high_const
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: %lowmask:_(s32) = G_CONSTANT i32 255
    ; CHECK-NEXT: %and:_(s32) = G_AND [[COPY]], %lowmask
    ; CHECK-NEXT: $w0 = COPY %and(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:_(s32) = COPY $w0
    %hc:_(s32) = G_CONSTANT i32 65280
    %or:_(s32) = G_OR %0, %hc
    %lowmask:_(s32) = G_CONSTANT i32 255
    %and:_(s32) = G_AND %or, %lowmask
    $w0 = COPY %and(s32)
    RET_ReallyLR implicit $w0
...
---
# Negative: the demanded window overlaps the OR constant's set bits, so the OR
# is observable and must be kept.
name:            keep_or_demanded_const
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0
    ; CHECK-LABEL: name: keep_or_demanded_const
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: %hc:_(s32) = G_CONSTANT i32 255
    ; CHECK-NEXT: %or:_(s32) = G_OR [[COPY]], %hc
    ; CHECK-NEXT: %lowmask:_(s32) = G_CONSTANT i32 4095
    ; CHECK-NEXT: %and:_(s32) = G_AND %or, %lowmask
    ; CHECK-NEXT: $w0 = COPY %and(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:_(s32) = COPY $w0
    %hc:_(s32) = G_CONSTANT i32 255
    %or:_(s32) = G_OR %0, %hc
    %lowmask:_(s32) = G_CONSTANT i32 4095
    %and:_(s32) = G_AND %or, %lowmask
    $w0 = COPY %and(s32)
    RET_ReallyLR implicit $w0
...
---
# A shift root transfers its demand through the constant amount: shl-by-4
# observes only source bits [0,28), exactly the bits the mask keeps, so the
# single-use inner G_AND is redundant and must be erased.
name:            shl_root_drops_inner_mask
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0
    ; CHECK-LABEL: name: shl_root_drops_inner_mask
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: %amt:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: %shl:_(s32) = G_SHL [[COPY]], %amt(s32)
    ; CHECK-NEXT: $w0 = COPY %shl(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:_(s32) = COPY $w0
    %mask:_(s32) = G_CONSTANT i32 268435455
    %and:_(s32) = G_AND %0, %mask
    %amt:_(s32) = G_CONSTANT i32 4
    %shl:_(s32) = G_SHL %and, %amt
    $w0 = COPY %shl(s32)
    RET_ReallyLR implicit $w0
...
---
# AND root with demand propagated through shl-by-4: outer mask demands [0,12),
# which translates to src demand [0,8). Inner mask 255 covers [0,8), so the
# inner G_AND is redundant and gets dropped.
name:            and_root_sees_through_shl
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0
    ; RULE-LABEL: name: and_root_sees_through_shl
    ; RULE: liveins: $w0
    ; RULE-NEXT: {{  $}}
    ; RULE-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; RULE-NEXT: %amt:_(s32) = G_CONSTANT i32 4
    ; RULE-NEXT: %shl:_(s32) = G_SHL [[COPY]], %amt(s32)
    ; RULE-NEXT: %lowmask:_(s32) = G_CONSTANT i32 4095
    ; RULE-NEXT: %and2:_(s32) = G_AND %shl, %lowmask
    ; RULE-NEXT: $w0 = COPY %and2(s32)
    ; RULE-NEXT: RET_ReallyLR implicit $w0
    ;
    ; FULL-LABEL: name: and_root_sees_through_shl
    ; FULL: liveins: $w0
    ; FULL-NEXT: {{  $}}
    ; FULL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; FULL-NEXT: %mask:_(s32) = G_CONSTANT i32 255
    ; FULL-NEXT: %and:_(s32) = G_AND [[COPY]], %mask
    ; FULL-NEXT: %amt:_(s32) = G_CONSTANT i32 4
    ; FULL-NEXT: %shl:_(s32) = G_SHL %and, %amt(s32)
    ; FULL-NEXT: $w0 = COPY %shl(s32)
    ; FULL-NEXT: RET_ReallyLR implicit $w0
    %0:_(s32) = COPY $w0
    %mask:_(s32) = G_CONSTANT i32 255
    %and:_(s32) = G_AND %0, %mask
    %amt:_(s32) = G_CONSTANT i32 4
    %shl:_(s32) = G_SHL %and, %amt
    %lowmask:_(s32) = G_CONSTANT i32 4095
    %and2:_(s32) = G_AND %shl, %lowmask
    $w0 = COPY %and2(s32)
    RET_ReallyLR implicit $w0
...
---
# G_ASHR-by-8 under an AND that only demands bits [0,16). The sign-fill region
# [24,32) is undemanded, so the arithmetic shift converts to a logical shift.
name:            ashr_to_lshr_low_demand
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0
    ; RULE-LABEL: name: ashr_to_lshr_low_demand
    ; RULE: liveins: $w0
    ; RULE-NEXT: {{  $}}
    ; RULE-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; RULE-NEXT: %amt:_(s32) = G_CONSTANT i32 8
    ; RULE-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[COPY]], %amt(s32)
    ; RULE-NEXT: %lowmask:_(s32) = G_CONSTANT i32 65535
    ; RULE-NEXT: %and:_(s32) = G_AND [[LSHR]], %lowmask
    ; RULE-NEXT: $w0 = COPY %and(s32)
    ; RULE-NEXT: RET_ReallyLR implicit $w0
    ;
    ; FULL-LABEL: name: ashr_to_lshr_low_demand
    ; FULL: liveins: $w0
    ; FULL-NEXT: {{  $}}
    ; FULL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; FULL-NEXT: %amt:_(s32) = G_CONSTANT i32 8
    ; FULL-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; FULL-NEXT: %and:_(s32) = G_UBFX [[COPY]], %amt(s32), [[C]]
    ; FULL-NEXT: $w0 = COPY %and(s32)
    ; FULL-NEXT: RET_ReallyLR implicit $w0
    %0:_(s32) = COPY $w0
    %amt:_(s32) = G_CONSTANT i32 8
    %ashr:_(s32) = G_ASHR %0, %amt
    %lowmask:_(s32) = G_CONSTANT i32 65535
    %and:_(s32) = G_AND %ashr, %lowmask
    $w0 = COPY %and(s32)
    RET_ReallyLR implicit $w0
...
---
# G_ASHR is the root (all bits demanded). The sign-fill region is demanded, so
# ASHR must survive. Guards against unsound unconditional conversion.
name:            keep_ashr_sign_demanded
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0
    ; CHECK-LABEL: name: keep_ashr_sign_demanded
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; CHECK-NEXT: %amt:_(s32) = G_CONSTANT i32 8
    ; CHECK-NEXT: %ashr:_(s32) = G_ASHR [[COPY]], %amt(s32)
    ; CHECK-NEXT: $w0 = COPY %ashr(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:_(s32) = COPY $w0
    %amt:_(s32) = G_CONSTANT i32 8
    %ashr:_(s32) = G_ASHR %0, %amt
    $w0 = COPY %ashr(s32)
    RET_ReallyLR implicit $w0
...
---
# %and is multi-use (feeds both the G_SHL and the G_ADD). The combiner walks
# from %and2 through the single-use %shl, then reaches %and with partial
# demand. Node-local const-elim on %and is allowed (reroutes only the shl's
# operand), but the G_ADD still observes the masked value so %and must remain.
name:            multiuse_shift_inner_mask_survives
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0
    ; RULE-LABEL: name: multiuse_shift_inner_mask_survives
    ; RULE: liveins: $w0
    ; RULE-NEXT: {{  $}}
    ; RULE-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; RULE-NEXT: %mask:_(s32) = G_CONSTANT i32 255
    ; RULE-NEXT: %and:_(s32) = G_AND [[COPY]], %mask
    ; RULE-NEXT: %amt:_(s32) = G_CONSTANT i32 4
    ; RULE-NEXT: %shl:_(s32) = G_SHL [[COPY]], %amt(s32)
    ; RULE-NEXT: %lowmask:_(s32) = G_CONSTANT i32 4095
    ; RULE-NEXT: %and2:_(s32) = G_AND %shl, %lowmask
    ; RULE-NEXT: %other:_(s32) = G_ADD %and, %and
    ; RULE-NEXT: $w0 = COPY %and2(s32)
    ; RULE-NEXT: $w1 = COPY %other(s32)
    ; RULE-NEXT: RET_ReallyLR implicit $w0, implicit $w1
    ;
    ; FULL-LABEL: name: multiuse_shift_inner_mask_survives
    ; FULL: liveins: $w0
    ; FULL-NEXT: {{  $}}
    ; FULL-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $w0
    ; FULL-NEXT: %mask:_(s32) = G_CONSTANT i32 255
    ; FULL-NEXT: %and:_(s32) = G_AND [[COPY]], %mask
    ; FULL-NEXT: %amt:_(s32) = G_CONSTANT i32 4
    ; FULL-NEXT: %shl:_(s32) = G_SHL %and, %amt(s32)
    ; FULL-NEXT: %other:_(s32) = G_ADD %and, %and
    ; FULL-NEXT: $w0 = COPY %shl(s32)
    ; FULL-NEXT: $w1 = COPY %other(s32)
    ; FULL-NEXT: RET_ReallyLR implicit $w0, implicit $w1
    %0:_(s32) = COPY $w0
    %mask:_(s32) = G_CONSTANT i32 255
    %and:_(s32) = G_AND %0, %mask
    %amt:_(s32) = G_CONSTANT i32 4
    %shl:_(s32) = G_SHL %and, %amt
    %lowmask:_(s32) = G_CONSTANT i32 4095
    %and2:_(s32) = G_AND %shl, %lowmask
    %other:_(s32) = G_ADD %and, %and
    $w0 = COPY %and2(s32)
    $w1 = COPY %other(s32)
    RET_ReallyLR implicit $w0, implicit $w1
...
---
# 0x00FF00FFFFFFFFFF = 71777218572845055. Bits set: [0,40) and [48,56).
# G_LSHR-by-40 demands src bits [40,64). Within that window, C has bits [48,56)
# set and [40,48)u[56,64) clear, so neither "demand isSubsetOf C" nor
# "demand isSubsetOf ~C" holds. Additionally %and is multi-use (TRUNC + LSHR),
# so partial-demand recursion is blocked. Nothing changes in the rule-isolated
# run: strict negative gate for the multi-use guard.
name:            keep_and_multiuse_straddling_mask
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: keep_and_multiuse_straddling_mask
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $x0
    ; CHECK-NEXT: %ptr:_(p0) = COPY $x1
    ; CHECK-NEXT: %c:_(s64) = G_CONSTANT i64 71777218572845055
    ; CHECK-NEXT: %and:_(s64) = G_AND [[COPY]], %c
    ; CHECK-NEXT: %lo:_(s32) = G_TRUNC %and(s64)
    ; CHECK-NEXT: %amt:_(s64) = G_CONSTANT i64 40
    ; CHECK-NEXT: %hi:_(s64) = G_LSHR %and, %amt(s64)
    ; CHECK-NEXT: $w0 = COPY %lo(s32)
    ; CHECK-NEXT: $x1 = COPY %hi(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0, implicit $x1
    %0:_(s64) = COPY $x0
    %ptr:_(p0) = COPY $x1
    %c:_(s64) = G_CONSTANT i64 71777218572845055
    %and:_(s64) = G_AND %0, %c
    %lo:_(s32) = G_TRUNC %and(s64)
    %amt:_(s64) = G_CONSTANT i64 40
    %hi:_(s64) = G_LSHR %and, %amt(s64)
    $w0 = COPY %lo(s32)
    $x1 = COPY %hi(s64)
    RET_ReallyLR implicit $w0, implicit $x1
...
