# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -run-pass=aarch64-prelegalizer-combiner -verify-machineinstrs -mtriple aarch64-unknown-unknown %s -o - | FileCheck %s

---
name:            test_combine_nan_rhs_fminimum_half
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_rhs_fminimum_half
    ; CHECK: [[C:%[0-9]+]]:_(s16) = G_FCONSTANT half +snan(0x1)
    ; CHECK-NEXT: $h0 = COPY [[C]](s16)
    %0:_(s16) = COPY $h0
    %1:_(s16) = G_FCONSTANT half 0xH7C01
    %2:_(s16) = G_FMINIMUM %0, %1
    $h0 = COPY %2
...
---
name:            test_combine_nan_rhs_fminimum_float
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_rhs_fminimum_float
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float +qnan
    ; CHECK-NEXT: $w0 = COPY [[C]](s32)
    %0:_(s32) = COPY $w0
    %1:_(s32) = G_FCONSTANT float 0x7FF8000000000000
    %2:_(s32) = G_FMINIMUM %0, %1
    $w0 = COPY %2
...
---
name:            test_combine_nan_rhs_fminimum_double
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_rhs_fminimum_double
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double +qnan
    ; CHECK-NEXT: $x0 = COPY [[C]](s64)
    %0:_(s64) = COPY $x0
    %1:_(s64) = G_FCONSTANT double 0x7FF8000000000000
    %2:_(s64) = G_FMINIMUM %0, %1
    $x0 = COPY %2
...
---
name:            test_combine_nan_lhs_fminimum_half
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_lhs_fminimum_half
    ; CHECK: [[C:%[0-9]+]]:_(s16) = G_FCONSTANT half +snan(0x1)
    ; CHECK-NEXT: $h0 = COPY [[C]](s16)
    %0:_(s16) = COPY $h0
    %1:_(s16) = G_FCONSTANT half 0xH7C01
    %2:_(s16) = G_FMINIMUM %1, %0
    $h0 = COPY %2
...
---
name:            test_combine_nan_lhs_fminimum_float
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_lhs_fminimum_float
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float +qnan
    ; CHECK-NEXT: $w0 = COPY [[C]](s32)
    %0:_(s32) = COPY $w0
    %1:_(s32) = G_FCONSTANT float 0x7FF8000000000000
    %2:_(s32) = G_FMINIMUM %1, %0
    $w0 = COPY %2
...
---
name:            test_combine_nan_lhs_fminimum_double
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_lhs_fminimum_double
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double +qnan
    ; CHECK-NEXT: $x0 = COPY [[C]](s64)
    %0:_(s64) = COPY $x0
    %1:_(s64) = G_FCONSTANT double 0x7FF8000000000000
    %2:_(s64) = G_FMINIMUM %1, %0
    $x0 = COPY %2
...
---
name:            test_combine_nan_rhs_fmaximum_half
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_rhs_fmaximum_half
    ; CHECK: [[C:%[0-9]+]]:_(s16) = G_FCONSTANT half +snan(0x1)
    ; CHECK-NEXT: $h0 = COPY [[C]](s16)
    %0:_(s16) = COPY $h0
    %1:_(s16) = G_FCONSTANT half 0xH7C01
    %2:_(s16) = G_FMAXIMUM %0, %1
    $h0 = COPY %2
...
---
name:            test_combine_nan_rhs_fmaximum_float
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_rhs_fmaximum_float
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float +qnan
    ; CHECK-NEXT: $w0 = COPY [[C]](s32)
    %0:_(s32) = COPY $w0
    %1:_(s32) = G_FCONSTANT float 0x7FF8000000000000
    %2:_(s32) = G_FMAXIMUM %0, %1
    $w0 = COPY %2
...
---
name:            test_combine_nan_rhs_fmaximum_double
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_rhs_fmaximum_double
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double +qnan
    ; CHECK-NEXT: $x0 = COPY [[C]](s64)
    %0:_(s64) = COPY $x0
    %1:_(s64) = G_FCONSTANT double 0x7FF8000000000000
    %2:_(s64) = G_FMAXIMUM %0, %1
    $x0 = COPY %2
...
---
name:            test_combine_nan_lhs_fmaximum_half
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_lhs_fmaximum_half
    ; CHECK: [[C:%[0-9]+]]:_(s16) = G_FCONSTANT half +snan(0x1)
    ; CHECK-NEXT: $h0 = COPY [[C]](s16)
    %0:_(s16) = COPY $h0
    %1:_(s16) = G_FCONSTANT half 0xH7C01
    %2:_(s16) = G_FMAXIMUM %1, %0
    $h0 = COPY %2
...
---
name:            test_combine_nan_lhs_fmaximum_float
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_lhs_fmaximum_float
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_FCONSTANT float +qnan
    ; CHECK-NEXT: $w0 = COPY [[C]](s32)
    %0:_(s32) = COPY $w0
    %1:_(s32) = G_FCONSTANT float 0x7FF8000000000000
    %2:_(s32) = G_FMAXIMUM %1, %0
    $w0 = COPY %2
...
---
name:            test_combine_nan_lhs_fmaximum_double
body:             |
  bb.1:
  liveins:
    ; CHECK-LABEL: name: test_combine_nan_lhs_fmaximum_double
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double +qnan
    ; CHECK-NEXT: $x0 = COPY [[C]](s64)
    %0:_(s64) = COPY $x0
    %1:_(s64) = G_FCONSTANT double 0x7FF8000000000000
    %2:_(s64) = G_FMAXIMUM %1, %0
    $x0 = COPY %2
...
