; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=aarch64-unknown-unknown | FileCheck %s --check-prefixes=CHECK,CHECK-NO-FULLFP16,CHECK-SD-NO-FULLFP16
; RUN: llc < %s -mtriple=aarch64-unknown-unknown -global-isel | FileCheck %s --check-prefixes=CHECK,CHECK-NO-FULLFP16,CHECK-GI-NO-FULLFP16

; RUN: llc < %s -mtriple=aarch64-unknown-unknown -mattr=+fullfp16 | FileCheck %s --check-prefixes=CHECK,CHECK-FP16,CHECK-SD-FP16
; RUN: llc < %s -mtriple=aarch64-unknown-unknown -global-isel -mattr=+fullfp16 | FileCheck %s --check-prefixes=CHECK,CHECK-FP16,CHECK-GI-FP16

define <8 x i16> @test(<8 x half> %a) {
; CHECK-SD-NO-FULLFP16-LABEL: test:
; CHECK-SD-NO-FULLFP16:       // %bb.0: // %entry
; CHECK-SD-NO-FULLFP16-NEXT:    movi v1.8h, #126, lsl #8
; CHECK-SD-NO-FULLFP16-NEXT:    fcvtl v2.4s, v0.4h
; CHECK-SD-NO-FULLFP16-NEXT:    fcvtl2 v0.4s, v0.8h
; CHECK-SD-NO-FULLFP16-NEXT:    fcvtl v3.4s, v1.4h
; CHECK-SD-NO-FULLFP16-NEXT:    fcvtl2 v1.4s, v1.8h
; CHECK-SD-NO-FULLFP16-NEXT:    fmul v2.4s, v2.4s, v3.4s
; CHECK-SD-NO-FULLFP16-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-SD-NO-FULLFP16-NEXT:    fcvtn v1.4h, v2.4s
; CHECK-SD-NO-FULLFP16-NEXT:    fcvtn2 v1.8h, v0.4s
; CHECK-SD-NO-FULLFP16-NEXT:    fcvtl2 v0.4s, v1.8h
; CHECK-SD-NO-FULLFP16-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-SD-NO-FULLFP16-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-SD-NO-FULLFP16-NEXT:    fcvtzs v1.4s, v1.4s
; CHECK-SD-NO-FULLFP16-NEXT:    uzp1 v0.8h, v1.8h, v0.8h
; CHECK-SD-NO-FULLFP16-NEXT:    ret
;
; CHECK-GI-NO-FULLFP16-LABEL: test:
; CHECK-GI-NO-FULLFP16:       // %bb.0: // %entry
; CHECK-GI-NO-FULLFP16-NEXT:    movi v1.4h, #126, lsl #8
; CHECK-GI-NO-FULLFP16-NEXT:    fcvtl v2.4s, v0.4h
; CHECK-GI-NO-FULLFP16-NEXT:    fcvtl2 v0.4s, v0.8h
; CHECK-GI-NO-FULLFP16-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-GI-NO-FULLFP16-NEXT:    fmul v2.4s, v2.4s, v1.4s
; CHECK-GI-NO-FULLFP16-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-GI-NO-FULLFP16-NEXT:    fcvtn v1.4h, v2.4s
; CHECK-GI-NO-FULLFP16-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-GI-NO-FULLFP16-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-GI-NO-FULLFP16-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-GI-NO-FULLFP16-NEXT:    fcvtzs v1.4s, v1.4s
; CHECK-GI-NO-FULLFP16-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-GI-NO-FULLFP16-NEXT:    uzp1 v0.8h, v1.8h, v0.8h
; CHECK-GI-NO-FULLFP16-NEXT:    ret
;
; CHECK-FP16-LABEL: test:
; CHECK-FP16:       // %bb.0: // %entry
; CHECK-FP16-NEXT:    movi v1.8h, #126, lsl #8
; CHECK-FP16-NEXT:    fmul v0.8h, v0.8h, v1.8h
; CHECK-FP16-NEXT:    fcvtzs v0.8h, v0.8h
; CHECK-FP16-NEXT:    ret
entry:
  %fmul = fmul <8 x half> %a, splat (half 0xH7E00)
  %fptosi = fptosi <8 x half> %fmul to <8 x i16>
  ret <8 x i16> %fptosi
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
; CHECK-GI-FP16: {{.*}}
; CHECK-NO-FULLFP16: {{.*}}
; CHECK-SD-FP16: {{.*}}
