# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=arm64-apple-macosx -run-pass=aarch64-postlegalizer-combiner %s -o - | FileCheck %s
---
name:            freeze_push_illegal
legalized:       true
body:             |
  bb.0.entry:
    liveins: $x0
    ; CHECK-LABEL: name: freeze_push_illegal
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $x0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(<vscale x 4 x s32>) = G_LOAD [[COPY]](p0) :: (load (<vscale x 4 x s32>))
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[EVEC:%[0-9]+]]:_(s32) = G_EXTRACT_VECTOR_ELT [[LOAD]](<vscale x 4 x s32>), [[C]](s64)
    ; CHECK-NEXT: [[FREEZE:%[0-9]+]]:_(s32) = G_FREEZE [[EVEC]]
    ; CHECK-NEXT: $w0 = COPY [[FREEZE]](s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:_(p0) = COPY $x0
    %1:_(<vscale x 4 x s32>) = G_LOAD %0(p0) :: (load (<vscale x 4 x s32>))
    %2:_(s64) = G_CONSTANT i64 0
    %3:_(s32) = G_EXTRACT_VECTOR_ELT %1, %2
    %4:_(s32) = G_FREEZE %3
    $w0 = COPY %4(s32)
    RET_ReallyLR implicit $w0
...
