; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=arm64-apple-macosx -global-isel < %s | FileCheck %s

define i32 @_0(ptr %0) {
; CHECK-LABEL: _0:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    ldr q0, [x0]
; CHECK-NEXT:    fmov x0, d0
; CHECK-NEXT:    ; kill: def $w0 killed $w0 killed $x0
; CHECK-NEXT:    ret
entry:
  %1 = load i128, ptr %0, align 16
  %2 = freeze i128 %1
  %3 = trunc i128 %2 to i32
  ret i32 %3
}

define i32 @_1(ptr %0) {
; CHECK-LABEL: _1:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    ldr q0, [x0]
; CHECK-NEXT:    fmov x0, d0
; CHECK-NEXT:    ; kill: def $w0 killed $w0 killed $x0
; CHECK-NEXT:    ret
entry:
  %1 = load i128, ptr %0, align 16
  %2 = trunc i128 %1 to i32
  %3 = freeze i32 %2
  ret i32 %3
}
