# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=aarch64-unknown-linux-gnu -run-pass=instruction-select %s -o - | FileCheck %s

---
name:            pre_indexed_halfword
alignment:       4
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0, $w1
    ; CHECK-LABEL: name: pre_indexed_halfword
    ; CHECK: liveins: $x0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:gpr64sp = COPY $x0
    ; CHECK-NEXT: %val32:gpr32 = COPY $w1
    ; CHECK-NEXT: early-clobber %wb:gpr64sp = STRHHpre %val32, %ptr, 2 :: (store (s16))
    ; CHECK-NEXT: $x0 = COPY %wb
    ; CHECK-NEXT: RET_ReallyLR
    %ptr:gpr(p0) = COPY $x0
    %val32:gpr(s32) = COPY $w1
    %off:gpr(s64) = G_CONSTANT i64 2
    %wb:gpr(p0) = G_INDEXED_STORE %val32(s32), %ptr, %off, 1 :: (store (s16))
    $x0 = COPY %wb
    RET_ReallyLR

...
---
name:            post_indexed_halfword
alignment:       4
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0, $w1
    ; CHECK-LABEL: name: post_indexed_halfword
    ; CHECK: liveins: $x0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:gpr64sp = COPY $x0
    ; CHECK-NEXT: %val32:gpr32 = COPY $w1
    ; CHECK-NEXT: early-clobber %wb:gpr64sp = STRHHpost %val32, %ptr, 2 :: (store (s16))
    ; CHECK-NEXT: $x0 = COPY %wb
    ; CHECK-NEXT: RET_ReallyLR
    %ptr:gpr(p0) = COPY $x0
    %val32:gpr(s32) = COPY $w1
    %off:gpr(s64) = G_CONSTANT i64 2
    %wb:gpr(p0) = G_INDEXED_STORE %val32(s32), %ptr, %off, 0 :: (store (s16))
    $x0 = COPY %wb
    RET_ReallyLR

...
