# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=aarch64 -run-pass=aarch64-prelegalizer-combiner -O0 -verify-machineinstrs %s -o - | FileCheck %s
--- |
  target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
  target triple = "arm64-apple-darwin"

  declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg) #0

  define void @test_small_memset(ptr nocapture %dst) {
  entry:
    tail call void @llvm.memset.p0.i64(ptr align 4 %dst, i8 12, i64 32, i1 false)
    ret void
  }

  define void @test_large_memset(ptr nocapture %dst) {
  entry:
    tail call void @llvm.memset.p0.i64(ptr align 4 %dst, i8 12, i64 36, i1 false)
    ret void
  }

  attributes #0 = { argmemonly nounwind }

...
---
name:            test_small_memset
alignment:       4
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: test_small_memset
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 868082074056920076
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x i64>) = G_BUILD_VECTOR [[C]](i64), [[C]](i64)
    ; CHECK-NEXT: G_STORE [[BUILD_VECTOR]](<2 x i64>), [[COPY]](p0) :: (store (<2 x i64>) into %ir.dst, align 4)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 16
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = nuw inbounds G_PTR_ADD [[COPY]], [[C1]](s64)
    ; CHECK-NEXT: G_STORE [[BUILD_VECTOR]](<2 x i64>), [[PTR_ADD]](p0) :: (store (<2 x i64>) into %ir.dst + 16, align 4)
    ; CHECK-NEXT: RET_ReallyLR
    %0:_(p0) = COPY $x0
    %1:_(i8) = G_CONSTANT i8 12
    %2:_(i64) = G_CONSTANT i64 32
    G_MEMSET %0(p0), %1(i8), %2(i64), 1 :: (store (s8) into %ir.dst, align 4)
    RET_ReallyLR

...
---
name:            test_large_memset
alignment:       4
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: test_large_memset
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(i8) = G_CONSTANT i8 12
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(i64) = G_CONSTANT i64 36
    ; CHECK-NEXT: G_MEMSET [[COPY]](p0), [[C]](i8), [[C1]](i64), 1 :: (store (s8) into %ir.dst, align 4)
    ; CHECK-NEXT: RET_ReallyLR
    %0:_(p0) = COPY $x0
    %1:_(i8) = G_CONSTANT i8 12
    %2:_(i64) = G_CONSTANT i64 36
    G_MEMSET %0(p0), %1(i8), %2(i64), 1 :: (store (s8) into %ir.dst, align 4)
    RET_ReallyLR

...
