; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64 %s -o - | FileCheck --check-prefix=CHECK --check-prefix=CHECK-SD %s
; RUN: llc -mtriple=aarch64 -global-isel -global-isel-abort=2 %s -o - 2>&1 | FileCheck --check-prefix=CHECK --check-prefix=CHECK-GI %s

; CHECK-GI:         warning: Instruction selection used fallback path for insert_v8i32_v4i32_high
; CHECK-GI-NEXT:    warning: Instruction selection used fallback path for insert_v8i32_v4i32_low

define <4 x i32> @insert_v4i32_v2i32_high(<4 x i32> %a, <2 x i32> %b) {
; CHECK-LABEL: insert_v4i32_v2i32_high:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov d2, v0.d[1]
; CHECK-NEXT:    fmov d0, d1
; CHECK-NEXT:    mov v0.d[1], v2.d[0]
; CHECK-NEXT:    ret
entry:
  %vector = call <4 x i32> @llvm.vector.insert.v4i32.v2i32(<4 x i32> %a, <2 x i32> %b, i64 0)
  ret <4 x i32> %vector
}

define <4 x i32> @insert_v4i32_v2i32_low(<4 x i32> %a, <2 x i32> %b) {
; CHECK-LABEL: insert_v4i32_v2i32_low:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-NEXT:    ret
entry:
  %vector = call <4 x i32> @llvm.vector.insert.v4i32.v2i32(<4 x i32> %a, <2 x i32> %b, i64 2)
  ret <4 x i32> %vector
}

define <8 x i32> @insert_v8i32_v4i32_high(<8 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: insert_v8i32_v4i32_high:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov v0.16b, v2.16b
; CHECK-NEXT:    ret
entry:
  %vector = call <8 x i32> @llvm.vector.insert.v8i32.v4i32(<8 x i32> %a, <4 x i32> %b, i64 0)
  ret <8 x i32> %vector
}

define <8 x i32> @insert_v8i32_v4i32_low(<8 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: insert_v8i32_v4i32_low:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov v1.16b, v2.16b
; CHECK-NEXT:    ret
entry:
  %vector = call <8 x i32> @llvm.vector.insert.v8i32.v4i32(<8 x i32> %a, <4 x i32> %b, i64 4)
  ret <8 x i32> %vector
}

define <8 x i32> @insert_v8i32_v2i32_high(<8 x i32> %a, <2 x i32> %b) {
; CHECK-SD-LABEL: insert_v8i32_v2i32_high:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    mov d3, v0.d[1]
; CHECK-SD-NEXT:    fmov d0, d2
; CHECK-SD-NEXT:    mov v0.d[1], v3.d[0]
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: insert_v8i32_v2i32_high:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    // kill: def $d2 killed $d2 def $q2
; CHECK-GI-NEXT:    mov v0.s[1], v2.s[1]
; CHECK-GI-NEXT:    ret
entry:
  %vector = call <8 x i32> @llvm.vector.insert.v4i32.v2i32(<8 x i32> %a, <2 x i32> %b, i64 0)
  ret <8 x i32> %vector
}

define <8 x i32> @insert_v8i32_v2i32_low(<8 x i32> %a, <2 x i32> %b) {
; CHECK-SD-LABEL: insert_v8i32_v2i32_low:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    // kill: def $d2 killed $d2 def $q2
; CHECK-SD-NEXT:    mov v1.d[1], v2.d[0]
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: insert_v8i32_v2i32_low:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    // kill: def $d2 killed $d2 def $q2
; CHECK-GI-NEXT:    mov v1.s[3], v2.s[1]
; CHECK-GI-NEXT:    ret
entry:
  %vector = call <8 x i32> @llvm.vector.insert.v4i32.v2i32(<8 x i32> %a, <2 x i32> %b, i64 6)
  ret <8 x i32> %vector
}

define <8 x i16> @insert_v8i16_v4i16_high(<8 x i16> %a, <4 x i16> %b) {
; CHECK-LABEL: insert_v8i16_v4i16_high:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov d2, v0.d[1]
; CHECK-NEXT:    fmov d0, d1
; CHECK-NEXT:    mov v0.d[1], v2.d[0]
; CHECK-NEXT:    ret
entry:
  %vector = call <8 x i16> @llvm.vector.insert.v8i16.v4i16(<8 x i16> %a, <4 x i16> %b, i64 0)
  ret <8 x i16> %vector
}

define <8 x i16> @insert_v8i16_v4i16_low(<8 x i16> %a, <4 x i16> %b) {
; CHECK-LABEL: insert_v8i16_v4i16_low:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-NEXT:    ret
entry:
  %vector = call <8 x i16> @llvm.vector.insert.v8i16.v4i16(<8 x i16> %a, <4 x i16> %b, i64 4)
  ret <8 x i16> %vector
}

define <8 x i16> @insert_v8i16_v2i16_high(<8 x i16> %a, <2 x i16> %b) {
; CHECK-SD-LABEL: insert_v8i16_v2i16_high:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    zip2 v2.4h, v0.4h, v0.4h
; CHECK-SD-NEXT:    mov d3, v0.d[1]
; CHECK-SD-NEXT:    uzp1 v0.4h, v1.4h, v2.4h
; CHECK-SD-NEXT:    mov v0.d[1], v3.d[0]
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: insert_v8i16_v2i16_high:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    mov w8, v1.s[1]
; CHECK-GI-NEXT:    mov v1.h[1], w8
; CHECK-GI-NEXT:    mov v0.h[1], v1.h[1]
; CHECK-GI-NEXT:    ret
entry:
  %vector = call <8 x i16> @llvm.vector.insert.v4i32.v2i32(<8 x i16> %a, <2 x i16> %b, i64 0)
  ret <8 x i16> %vector
}

define <8 x i16> @insert_v8i16_v2i16_low(<8 x i16> %a, <2 x i16> %b) {
; CHECK-SD-LABEL: insert_v8i16_v2i16_low:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    mov d2, v0.d[1]
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    zip1 v2.4h, v2.4h, v2.4h
; CHECK-SD-NEXT:    mov v2.d[1], v1.d[0]
; CHECK-SD-NEXT:    xtn2 v0.8h, v2.4s
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: insert_v8i16_v2i16_low:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    mov w8, v1.s[1]
; CHECK-GI-NEXT:    mov v1.h[1], w8
; CHECK-GI-NEXT:    mov v0.h[7], v1.h[1]
; CHECK-GI-NEXT:    ret
entry:
  %vector = call <8 x i16> @llvm.vector.insert.v4i32.v2i32(<8 x i16> %a, <2 x i16> %b, i64 6)
  ret <8 x i16> %vector
}
