; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -mtriple=aarch64-- -mcpu=falkor -mattr=+lse -O0 -aarch64-enable-atomic-cfg-tidy=0 -stop-after=irtranslator -global-isel -verify-machineinstrs %s -o - | FileCheck %s

define i16 @convert_to_fp16(float %src) {
  ; CHECK-LABEL: name: convert_to_fp16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $s0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(f32) = COPY $s0
  ; CHECK-NEXT:   [[FPTRUNC:%[0-9]+]]:_(f16) = G_FPTRUNC [[COPY]](f32)
  ; CHECK-NEXT:   [[BITCAST:%[0-9]+]]:_(i16) = G_BITCAST [[FPTRUNC]](f16)
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(i32) = G_ANYEXT [[BITCAST]](i16)
  ; CHECK-NEXT:   $w0 = COPY [[ANYEXT]](i32)
  ; CHECK-NEXT:   RET_ReallyLR implicit $w0
  %cvt = call i16 @llvm.convert.to.fp16.f32(float %src)
  ret i16 %cvt
}

define float @convert_from_fp16(i16 %src) {
  ; CHECK-LABEL: name: convert_from_fp16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $w0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $w0
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i16) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[BITCAST:%[0-9]+]]:_(f16) = G_BITCAST [[TRUNC]](i16)
  ; CHECK-NEXT:   [[FPEXT:%[0-9]+]]:_(f32) = G_FPEXT [[BITCAST]](f16)
  ; CHECK-NEXT:   $s0 = COPY [[FPEXT]](f32)
  ; CHECK-NEXT:   RET_ReallyLR implicit $s0
  %cvt = call float @llvm.convert.from.fp16.f32(i16 %src)
  ret float %cvt
}

declare i16 @llvm.convert.to.fp16.f32(float) nounwind readnone
declare float @llvm.convert.from.fp16.f32(i16) nounwind readnone
