; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -O0 -global-isel -mtriple aarch64 -stop-after=irtranslator -verify-machineinstrs %s -o - -use-constant-int-for-fixed-length-splat=false | FileCheck %s --check-prefix=CHECK
; RUN: llc -O0 -global-isel -mtriple aarch64 -stop-after=irtranslator -verify-machineinstrs %s -o - -use-constant-int-for-fixed-length-splat | FileCheck %s --check-prefix=CHECK-CI

; Make sure we treat <1 x N> getelementptrs like scalar getelementptrs.

; We should not create a splat vector for the non-vector index on this
; getelementptr. The entire getelementptr should be translated to a scalar
; G_PTR_ADD.
define <1 x ptr> @one_elt_vector_ptr_add_non_vector_idx(<1 x ptr> %vec) {
  ; CHECK-LABEL: name: one_elt_vector_ptr_add_non_vector_idx
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $d0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $d0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY [[C]](s32)
  ; CHECK-NEXT:   [[SEXT:%[0-9]+]]:_(s64) = G_SEXT [[COPY1]](s32)
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[SEXT]](s64)
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(p0) = COPY [[PTR_ADD]](p0)
  ; CHECK-NEXT:   $d0 = COPY [[COPY2]](p0)
  ; CHECK-NEXT:   RET_ReallyLR implicit $d0
  ;
  ; CHECK-CI-LABEL: name: one_elt_vector_ptr_add_non_vector_idx
  ; CHECK-CI: bb.1 (%ir-block.0):
  ; CHECK-CI-NEXT:   liveins: $d0
  ; CHECK-CI-NEXT: {{  $}}
  ; CHECK-CI-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $d0
  ; CHECK-CI-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
  ; CHECK-CI-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s64)
  ; CHECK-CI-NEXT:   $d0 = COPY [[PTR_ADD]](p0)
  ; CHECK-CI-NEXT:   RET_ReallyLR implicit $d0
  %ptr_add = getelementptr i8, <1 x ptr> %vec, <1 x i32> <i32 1>
  ret <1 x ptr> %ptr_add
}

; We should not create a splat vector for the non-vector pointer on this
; getelementptr. The entire getelementptr should be translated to a scalar
; G_PTR_ADD.
define <1 x ptr> @one_elt_vector_ptr_add_non_vector_ptr(ptr %vec) {
  ; CHECK-LABEL: name: one_elt_vector_ptr_add_non_vector_ptr
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $x0
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY [[C]](s32)
  ; CHECK-NEXT:   [[SEXT:%[0-9]+]]:_(s64) = G_SEXT [[COPY1]](s32)
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[SEXT]](s64)
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(p0) = COPY [[PTR_ADD]](p0)
  ; CHECK-NEXT:   $d0 = COPY [[COPY2]](p0)
  ; CHECK-NEXT:   RET_ReallyLR implicit $d0
  ;
  ; CHECK-CI-LABEL: name: one_elt_vector_ptr_add_non_vector_ptr
  ; CHECK-CI: bb.1 (%ir-block.0):
  ; CHECK-CI-NEXT:   liveins: $x0
  ; CHECK-CI-NEXT: {{  $}}
  ; CHECK-CI-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $x0
  ; CHECK-CI-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
  ; CHECK-CI-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C]](s64)
  ; CHECK-CI-NEXT:   $d0 = COPY [[PTR_ADD]](p0)
  ; CHECK-CI-NEXT:   RET_ReallyLR implicit $d0
  %ptr_add = getelementptr i8, ptr %vec, <1 x i32> <i32 1>
  ret <1 x ptr> %ptr_add
}
