; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
; RUN: llc -O0 -mtriple=aarch64-- --global-isel --verify-machineinstrs --stop-after=irtranslator %s -o - | FileCheck %s

define void @vector_interleave2_v4i32(<2 x i32> %a, <2 x i32> %b) {
  ; CHECK-LABEL: name: vector_interleave2_v4i32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $d0, $d1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<2 x i32>) = COPY $d0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<2 x i32>) = COPY $d1
  ; CHECK-NEXT:   [[SHUF:%[0-9]+]]:_(<4 x i32>) = G_SHUFFLE_VECTOR [[COPY]](<2 x i32>), [[COPY1]], shufflemask(0, 2, 1, 3)
  ; CHECK-NEXT:   RET_ReallyLR
    %res = call <4 x i32> @llvm.vector.interleave2.v4i32(<2 x i32> %a, <2 x i32> %b)
    ret void
}

define void @vector_interleave2_v8f32(<4 x float> %a, <4 x float> %b) {
  ; CHECK-LABEL: name: vector_interleave2_v8f32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $q0, $q1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<4 x i32>) = COPY $q0
  ; CHECK-NEXT:   [[BITCAST:%[0-9]+]]:_(<4 x f32>) = G_BITCAST [[COPY]](<4 x i32>)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<4 x i32>) = COPY $q1
  ; CHECK-NEXT:   [[BITCAST1:%[0-9]+]]:_(<4 x f32>) = G_BITCAST [[COPY1]](<4 x i32>)
  ; CHECK-NEXT:   [[SHUF:%[0-9]+]]:_(<8 x f32>) = G_SHUFFLE_VECTOR [[BITCAST]](<4 x f32>), [[BITCAST1]], shufflemask(0, 4, 1, 5, 2, 6, 3, 7)
  ; CHECK-NEXT:   RET_ReallyLR
    %res = call <8 x float> @llvm.vector.interleave2.v8f32(<4 x float> %a, <4 x float> %b)
    ret void
}
