; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -mtriple=aarch64-linux-gnu -O0 -stop-after=irtranslator -global-isel -verify-machineinstrs %s -o - 2>&1 | FileCheck %s

declare void @use_s128(i128 %a, i128 %b)

define i32 @call_use_s128(i32 %p1, i128 %p2, i32 %p3, i32 %p4, i32 %p5, i128 %p6, i32 %p7) {
  ; Check partially passing a split type on the stack (s128 -> 2 x s64)
  ; CHECK-LABEL: name: call_use_s128
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $w0, $w4, $w5, $w6, $x2, $x3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $w0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i64) = COPY $x2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(i64) = COPY $x3
  ; CHECK-NEXT:   [[MV:%[0-9]+]]:_(i128) = G_MERGE_VALUES [[COPY1]](i64), [[COPY2]](i64)
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY $w4
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(i32) = COPY $w5
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(i32) = COPY $w6
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(i64) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load (i64) from %fixed-stack.2, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(i64) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load (i64) from %fixed-stack.1)
  ; CHECK-NEXT:   [[MV1:%[0-9]+]]:_(i128) = G_MERGE_VALUES [[LOAD]](i64), [[LOAD1]](i64)
  ; CHECK-NEXT:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD2:%[0-9]+]]:_(i32) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load (i32) from %fixed-stack.0, align 16)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(i64), [[UV1:%[0-9]+]]:_(i64) = G_UNMERGE_VALUES [[MV]](i128)
  ; CHECK-NEXT:   [[UV2:%[0-9]+]]:_(i64), [[UV3:%[0-9]+]]:_(i64) = G_UNMERGE_VALUES [[MV1]](i128)
  ; CHECK-NEXT:   $x0 = COPY [[UV]](i64)
  ; CHECK-NEXT:   $x1 = COPY [[UV1]](i64)
  ; CHECK-NEXT:   $x2 = COPY [[UV2]](i64)
  ; CHECK-NEXT:   $x3 = COPY [[UV3]](i64)
  ; CHECK-NEXT:   BL @use_s128, csr_aarch64_aapcs, implicit-def $lr, implicit $sp, implicit $x0, implicit $x1, implicit $x2, implicit $x3
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $w0 = COPY [[C]](i32)
  ; CHECK-NEXT:   RET_ReallyLR implicit $w0
entry:
  call void @use_s128(i128 %p2, i128 %p6)
  ret i32 0
}
