; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple aarch64 -global-isel -o - %s | FileCheck %s

define <4 x double> @knownfpclass_shuffle(<16 x double> %a) {
; CHECK-LABEL: knownfpclass_shuffle:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov d0, v1.d[1]
; CHECK-NEXT:    mov d1, v5.d[1]
; CHECK-NEXT:    movi v2.2d, #0000000000000000
; CHECK-NEXT:    mov v0.d[1], v3.d[1]
; CHECK-NEXT:    mov v1.d[1], v7.d[1]
; CHECK-NEXT:    fmov v3.2d, #1.00000000
; CHECK-NEXT:    fcmlt v0.2d, v0.2d, #0.0
; CHECK-NEXT:    fcmlt v1.2d, v1.2d, #0.0
; CHECK-NEXT:    bsl v0.16b, v2.16b, v3.16b
; CHECK-NEXT:    bsl v1.16b, v2.16b, v3.16b
; CHECK-NEXT:    ret
entry:
  %0 = shufflevector <16 x double> %a, <16 x double> zeroinitializer, <4 x i32> <i32 3, i32 7, i32 11, i32 15>
  %1 = fcmp olt <4 x double> %0, zeroinitializer
  %2 = select <4 x i1> %1, <4 x double> zeroinitializer, <4 x double> splat (double 1.000000e+00)
  ret <4 x double> %2
}
