# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=aarch64 -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s

...
---
name:            s64_s32_legal
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $s0
    ; CHECK-LABEL: name: s64_s32_legal
    ; CHECK: liveins: $s0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %copy:_(s32) = COPY $s0
    ; CHECK-NEXT: %lround:_(s64) = G_LROUND %copy(s32)
    ; CHECK-NEXT: %trunc:_(s32) = G_TRUNC %lround(s64)
    ; CHECK-NEXT: $w0 = COPY %trunc(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %copy:_(s32) = COPY $s0
    %lround:_(s64) = G_LROUND %copy(s32)
    %trunc:_(s32) = G_TRUNC %lround
    $w0 = COPY %trunc(s32)
    RET_ReallyLR implicit $w0
...
---
name:            s64_s64_legal
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $d0
    ; CHECK-LABEL: name: s64_s64_legal
    ; CHECK: liveins: $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %copy:_(s64) = COPY $d0
    ; CHECK-NEXT: %lround:_(s64) = G_LROUND %copy(s64)
    ; CHECK-NEXT: $x0 = COPY %lround(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $x0
    %copy:_(s64) = COPY $d0
    %lround:_(s64) = G_LROUND %copy(s64)
    $x0 = COPY %lround
    RET_ReallyLR implicit $x0
