# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 2
# RUN: llc -mtriple=arm64-unknown-unknown -global-isel -O0 -mattr=-fullfp16 -run-pass=legalizer %s -o - | FileCheck %s

--- |
  define <8 x half> @test_v8f16.sqrt(<8 x half> %a) {
    ret <8 x half> %a
  }

  define <4 x half> @test_v4f16.sqrt(<4 x half> %a) {
    ret <4 x half> %a
  }

...
---
name:            test_v8f16.sqrt
alignment:       4
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body:             |
  bb.1 (%ir-block.0):
    liveins: $q0
    ; CHECK-LABEL: name: test_v8f16.sqrt
    ; CHECK: liveins: $q0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x f16>) = COPY $q0
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<4 x f16>), [[UV1:%[0-9]+]]:_(<4 x f16>) = G_UNMERGE_VALUES [[COPY]](<8 x f16>)
    ; CHECK-NEXT: [[FPEXT:%[0-9]+]]:_(<4 x f32>) = G_FPEXT [[UV]](<4 x f16>)
    ; CHECK-NEXT: [[FPEXT1:%[0-9]+]]:_(<4 x f32>) = G_FPEXT [[UV1]](<4 x f16>)
    ; CHECK-NEXT: [[FSQRT:%[0-9]+]]:_(<4 x f32>) = G_FSQRT [[FPEXT]]
    ; CHECK-NEXT: [[FSQRT1:%[0-9]+]]:_(<4 x f32>) = G_FSQRT [[FPEXT1]]
    ; CHECK-NEXT: [[FPTRUNC:%[0-9]+]]:_(<4 x f16>) = G_FPTRUNC [[FSQRT]](<4 x f32>)
    ; CHECK-NEXT: [[FPTRUNC1:%[0-9]+]]:_(<4 x f16>) = G_FPTRUNC [[FSQRT1]](<4 x f32>)
    ; CHECK-NEXT: [[CONCAT_VECTORS:%[0-9]+]]:_(<8 x f16>) = G_CONCAT_VECTORS [[FPTRUNC]](<4 x f16>), [[FPTRUNC1]](<4 x f16>)
    ; CHECK-NEXT: $q0 = COPY [[CONCAT_VECTORS]](<8 x f16>)
    ; CHECK-NEXT: RET_ReallyLR implicit $q0
    %0:_(<8 x f16>) = COPY $q0
    %1:_(<8 x f16>) = G_FSQRT %0
    $q0 = COPY %1(<8 x f16>)
    RET_ReallyLR implicit $q0

...
---
name:            test_v4f16.sqrt
alignment:       4
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body:             |
  bb.1 (%ir-block.0):
    liveins: $d0
    ; CHECK-LABEL: name: test_v4f16.sqrt
    ; CHECK: liveins: $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<4 x f16>) = COPY $d0
    ; CHECK-NEXT: [[FPEXT:%[0-9]+]]:_(<4 x f32>) = G_FPEXT [[COPY]](<4 x f16>)
    ; CHECK-NEXT: [[FSQRT:%[0-9]+]]:_(<4 x f32>) = G_FSQRT [[FPEXT]]
    ; CHECK-NEXT: [[FPTRUNC:%[0-9]+]]:_(<4 x f16>) = G_FPTRUNC [[FSQRT]](<4 x f32>)
    ; CHECK-NEXT: $d0 = COPY [[FPTRUNC]](<4 x f16>)
    ; CHECK-NEXT: RET_ReallyLR implicit $d0
    %0:_(<4 x f16>) = COPY $d0
    %1:_(<4 x f16>) = G_FSQRT %0
    $d0 = COPY %1(<4 x f16>)
    RET_ReallyLR implicit $d0

...
