; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-linux -global-isel -verify-machineinstrs %s -o - | FileCheck %s

define <4 x i4> @failing(<4 x i4> %0) {
; CHECK-LABEL: failing:
; CHECK:       // %bb.0:
; CHECK-NEXT:    movi v1.4s, #15
; CHECK-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    movi v1.4s, #112
; CHECK-NEXT:    clz v0.4s, v0.4s
; CHECK-NEXT:    sub v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    xtn v0.4h, v0.4s
; CHECK-NEXT:    ret
  %2 = call <4 x i4> @llvm.ctlz.v4i4(<4 x i4> %0, i1 false)
  ret <4 x i4> %2
}
declare <4 x i4> @llvm.ctlz.v4i4(<4 x i4>, i1)
