# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple aarch64 -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s
...
---
name:            s32
body: |
  bb.0.entry:
    liveins: $w0
    ; CHECK-LABEL: name: s32
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %copy:_(s32) = COPY $w0
    ; CHECK-NEXT: %lsb:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: %width:_(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: %sbfx:_(s32) = G_SBFX %copy, %lsb(s32), %width
    ; CHECK-NEXT: $w0 = COPY %sbfx(s32)
    %copy:_(s32) = COPY $w0
    %lsb:_(s32) = G_CONSTANT i32 1
    %width:_(s32) = G_CONSTANT i32 2
    %sbfx:_(s32) = G_SBFX %copy(s32), %lsb, %width
    $w0 = COPY %sbfx(s32)
...
---
name:            s64
body: |
  bb.0.entry:
    liveins: $x0
    ; CHECK-LABEL: name: s64
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %copy:_(s64) = COPY $x0
    ; CHECK-NEXT: %lsb:_(s64) = G_CONSTANT i64 1
    ; CHECK-NEXT: %width:_(s64) = G_CONSTANT i64 2
    ; CHECK-NEXT: %sbfx:_(s64) = G_SBFX %copy, %lsb(s64), %width
    ; CHECK-NEXT: $x0 = COPY %sbfx(s64)
    %copy:_(s64) = COPY $x0
    %lsb:_(s64) = G_CONSTANT i64 1
    %width:_(s64) = G_CONSTANT i64 2
    %sbfx:_(s64) = G_SBFX %copy(s64), %lsb, %width
    $x0 = COPY %sbfx(s64)
...
