# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc %s -verify-machineinstrs -O0 -run-pass=legalizer -mtriple aarch64-unknown-unknown -o - | FileCheck %s
...
---
name:            trunc_usat_u_i32_to_i8
alignment:       4
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0

    ; CHECK-LABEL: name: trunc_usat_u_i32_to_i8
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(i32) = COPY $w0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 255
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(i32) = G_ICMP intpred(ult), [[C]](i32), [[COPY]]
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(i32) = G_SELECT [[ICMP]](i32), [[C]], [[COPY]]
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(i32) = G_AND [[SELECT]], [[C]]
    ; CHECK-NEXT: $w0 = COPY [[AND]](i32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:_(i32) = COPY $w0
    %4:_(i8) = G_TRUNC_USAT_U %0(i32)
    %5:_(i32) = G_ZEXT %4(i8)
    $w0 = COPY %5(i32)
    RET_ReallyLR implicit $w0
...
---
name:            trunc_usat_u_i32_to_i16
alignment:       4
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $w0

    ; CHECK-LABEL: name: trunc_usat_u_i32_to_i16
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(i32) = COPY $w0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 65535
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(i32) = G_ICMP intpred(ult), [[C]](i32), [[COPY]]
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(i32) = G_SELECT [[ICMP]](i32), [[C]], [[COPY]]
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(i32) = G_AND [[SELECT]], [[C]]
    ; CHECK-NEXT: $w0 = COPY [[AND]](i32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:_(i32) = COPY $w0
    %4:_(i16) = G_TRUNC_USAT_U %0(i32)
    %5:_(i32) = G_ZEXT %4(i16)
    $w0 = COPY %5(i32)
    RET_ReallyLR implicit $w0
...
---
name:            trunc_usat_u_i64_to_i32
alignment:       4
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: trunc_usat_u_i64_to_i32
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(i64) = COPY $x0
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 4294967295
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:_(i32) = G_ICMP intpred(ult), [[C]](i64), [[COPY]]
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:_(i64) = G_SELECT [[ICMP]](i32), [[C]], [[COPY]]
    ; CHECK-NEXT: [[TRUNC:%[0-9]+]]:_(i32) = G_TRUNC [[SELECT]](i64)
    ; CHECK-NEXT: $w0 = COPY [[TRUNC]](i32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:_(i64) = COPY $x0
    %4:_(i32) = G_TRUNC_USAT_U %0(i64)
    $w0 = COPY %4(i32)
    RET_ReallyLR implicit $w0
...
