# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=aarch64 -run-pass=legalizer -O0 %s -o - | FileCheck %s
---
name:            test_implicit_def
body: |
  bb.0.entry:
    liveins:

    ; CHECK-LABEL: name: test_implicit_def
    ; CHECK: [[DEF:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $x0 = COPY [[DEF]](s64)
    %0:_(s128) = G_IMPLICIT_DEF
    %1:_(s64) = G_TRUNC %0(s128)
    $x0 = COPY %1(s64)
...

---
name: test_implicit_def_s3
body: |
  bb.0:
    liveins:

    ; CHECK-LABEL: name: test_implicit_def_s3
    ; CHECK: [[DEF:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s64) = G_SEXT_INREG [[DEF]], 3
    ; CHECK-NEXT: $x0 = COPY [[SEXT_INREG]](s64)
    %0:_(s3) = G_IMPLICIT_DEF
    %1:_(s64) = G_SEXT %0
    $x0 = COPY %1(s64)
...

# FIXME: s2 not correctly handled

---
name: test_implicit_def_v4s32
body: |
  bb.0:

    ; CHECK-LABEL: name: test_implicit_def_v4s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(<2 x s32>), [[UV1:%[0-9]+]]:_(<2 x s32>) = G_UNMERGE_VALUES [[DEF]](<4 x s32>)
    ; CHECK-NEXT: $x0 = COPY [[UV]](<2 x s32>)
    ; CHECK-NEXT: $x1 = COPY [[UV1]](<2 x s32>)
    %0:_(<4 x s32>) = G_IMPLICIT_DEF
    %1:_(<2 x s32> ), %2:_(<2 x s32>) = G_UNMERGE_VALUES %0
    $x0 = COPY %1
    $x1 = COPY %2
...

---
name: test_implicit_def_v4s64
body: |
  bb.0:

    ; CHECK-LABEL: name: test_implicit_def_v4s64
    ; CHECK: [[DEF:%[0-9]+]]:_(<2 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $q0 = COPY [[DEF]](<2 x s64>)
    ; CHECK-NEXT: $q1 = COPY [[DEF]](<2 x s64>)
    %0:_(<4 x s64>) = G_IMPLICIT_DEF
    %1:_(<2 x s64> ), %2:_(<2 x s64>) = G_UNMERGE_VALUES %0
    $q0 = COPY %1
    $q1 = COPY %2
...
---
name: test_implicit_def_v2s32
body: |
  bb.0:

    ; CHECK-LABEL: name: test_implicit_def_v2s32
    ; CHECK: [[DEF:%[0-9]+]]:_(<2 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[DEF]](<2 x s32>)
    ; CHECK-NEXT: $w0 = COPY [[UV]](s32)
    ; CHECK-NEXT: $w1 = COPY [[UV1]](s32)
    %0:_(<2 x s32>) = G_IMPLICIT_DEF
    %1:_(s32), %2:_(s32) = G_UNMERGE_VALUES %0
    $w0 = COPY %1
    $w1 = COPY %2
...
---
name: test_implicit_def_v16s8
body: |
  bb.0:

    ; CHECK-LABEL: name: test_implicit_def_v16s8
    ; CHECK: [[DEF:%[0-9]+]]:_(<16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $q0 = COPY [[DEF]](<16 x s8>)
    %0:_(<16 x s8>) = G_IMPLICIT_DEF
    $q0 = COPY %0
...
---
name: test_implicit_def_v8s16
body: |
  bb.0:

    ; CHECK-LABEL: name: test_implicit_def_v8s16
    ; CHECK: [[DEF:%[0-9]+]]:_(<8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $q0 = COPY [[DEF]](<8 x s16>)
    %0:_(<8 x s16>) = G_IMPLICIT_DEF
    $q0 = COPY %0
...
---
name: test_implicit_def_s88
body: |
  bb.0:
    liveins:
    ; CHECK-LABEL: name: test_implicit_def_s88
    ; CHECK: [[DEF:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK-NEXT: $x0 = COPY [[DEF]](s64)
    %undef:_(s88) = G_IMPLICIT_DEF
    %trunc:_(s64) = G_TRUNC %undef
    $x0 = COPY %trunc(s64)
