# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -debugify-and-strip-all-safe=0 -run-pass=mir-debugify -verify-machineinstrs %s -o - | FileCheck %s

# RUN: llc -debugify-and-strip-all-safe=0 -passes=mir-debugify -verify-machineinstrs %s -o - | FileCheck %s
--- |
  target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
  target triple = "aarch64-unknown-unknown"

  define i32 @legalize_phi(i32 %argc) {
  entry:
    ret i32 0
  }

...
---
name:            legalize_phi
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
tracksRegLiveness: true
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
liveins:
body:             |
  ; CHECK-LABEL: name: legalize_phi
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $w0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $w0,  debug-location !11
  ; CHECK-NEXT:   DBG_VALUE [[COPY]](s32), $noreg, !9, !DIExpression(),  debug-location !11
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0,  debug-location !DILocation(line: 2, column: 1, scope: !5)
  ; CHECK-NEXT:   DBG_VALUE [[C]](s32), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 2, column: 1, scope: !5)
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1,  debug-location !DILocation(line: 3, column: 1, scope: !5)
  ; CHECK-NEXT:   DBG_VALUE [[C1]](s32), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 3, column: 1, scope: !5)
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2,  debug-location !DILocation(line: 4, column: 1, scope: !5)
  ; CHECK-NEXT:   DBG_VALUE [[C2]](s32), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 4, column: 1, scope: !5)
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(ugt), [[COPY]](s32), [[C]],  debug-location !DILocation(line: 5, column: 1, scope: !5)
  ; CHECK-NEXT:   DBG_VALUE [[ICMP]](s1), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 5, column: 1, scope: !5)
  ; CHECK-NEXT:   G_BRCOND [[ICMP]](s1), %bb.1,  debug-location !DILocation(line: 6, column: 1, scope: !5)
  ; CHECK-NEXT:   G_BR %bb.2,  debug-location !DILocation(line: 7, column: 1, scope: !5)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY]], [[C1]],  debug-location !DILocation(line: 8, column: 1, scope: !5)
  ; CHECK-NEXT:   DBG_VALUE [[ADD]](s32), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 8, column: 1, scope: !5)
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[ADD]](s32),  debug-location !DILocation(line: 9, column: 1, scope: !5)
  ; CHECK-NEXT:   DBG_VALUE [[TRUNC]](s1), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 9, column: 1, scope: !5)
  ; CHECK-NEXT:   G_BR %bb.3,  debug-location !DILocation(line: 10, column: 1, scope: !5)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[COPY]], [[C2]],  debug-location !DILocation(line: 11, column: 1, scope: !5)
  ; CHECK-NEXT:   DBG_VALUE [[ADD1]](s32), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 11, column: 1, scope: !5)
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(s1) = G_TRUNC [[ADD1]](s32),  debug-location !DILocation(line: 12, column: 1, scope: !5)
  ; CHECK-NEXT:   DBG_VALUE [[TRUNC1]](s1), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 12, column: 1, scope: !5)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(s1) = G_PHI [[TRUNC]](s1), %bb.1, [[TRUNC1]](s1), %bb.2,  debug-location !DILocation(line: 13, column: 1, scope: !5)
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:_(s1) = G_PHI [[TRUNC]](s1), %bb.1, [[TRUNC1]](s1), %bb.2,  debug-location !DILocation(line: 14, column: 1, scope: !5)
  ; CHECK-NEXT:   DBG_VALUE [[PHI]](s1), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 13, column: 1, scope: !5)
  ; CHECK-NEXT:   DBG_VALUE [[PHI1]](s1), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 14, column: 1, scope: !5)
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[PHI]](s1),  debug-location !DILocation(line: 15, column: 1, scope: !5)
  ; CHECK-NEXT:   DBG_VALUE [[ZEXT]](s32), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 15, column: 1, scope: !5)
  ; CHECK-NEXT:   $w0 = COPY [[ZEXT]](s32),  debug-location !DILocation(line: 16, column: 1, scope: !5)
  ; CHECK-NEXT:   DBG_VALUE $w0, $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 16, column: 1, scope: !5)
  ; CHECK-NEXT:   RET_ReallyLR implicit $w0,  debug-location !DILocation(line: 17, column: 1, scope: !5)
  bb.0:
    successors: %bb.1(0x40000000), %bb.2(0x40000000)
    liveins: $w0

    %0(s32) = COPY $w0
    %1(s32) = G_CONSTANT i32 0
    %3(s32) = G_CONSTANT i32 1
    %6(s32) = G_CONSTANT i32 2
    %2(s1) = G_ICMP intpred(ugt), %0(s32), %1
    G_BRCOND %2(s1), %bb.1
    G_BR %bb.2

  bb.1:
    successors: %bb.3(0x80000000)

    %4(s32) = G_ADD %0, %3
    %5(s1) = G_TRUNC %4(s32)
    G_BR %bb.3

  bb.2:
    successors: %bb.3(0x80000000)

    %7(s32) = G_ADD %0, %6
    %8(s1) = G_TRUNC %7(s32)

  bb.3:
    %9(s1) = G_PHI %5(s1), %bb.1, %8(s1), %bb.2
    %11:_(s1) = G_PHI %5(s1), %bb.1, %8(s1), %bb.2
    %10(s32) = G_ZEXT %9(s1)
    $w0 = COPY %10(s32)
    RET_ReallyLR implicit $w0

...
