# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -run-pass=aarch64-postlegalizer-combiner -verify-machineinstrs -mtriple aarch64-unknown-unknown %s -o - | FileCheck %s
---
# select (c, x, x) -> x
name:            test_combine_select_same_res
legalized:       true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_combine_select_same_res
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $x0
    ; CHECK-NEXT: $x0 = COPY [[COPY]](s64)
    %0:_(s64) = COPY $x0
    %1:_(s1) = G_TRUNC %0
    %2:_(s64) = G_SELECT %1, %0, %0
    $x0 = COPY %2(s64)
...
---
# select (undef, x, y) -> y
name:            test_combine_select_undef_res0_res1
legalized:       true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_combine_select_undef_res0_res1
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $x1
    ; CHECK-NEXT: $x0 = COPY [[COPY]](s64)
    %0:_(s64) = COPY $x0
    %1:_(s64) = COPY $x1
    %2:_(s1) = G_IMPLICIT_DEF
    %3:_(s64) = G_SELECT %2, %0, %1
    $x0 = COPY %3(s64)
...
---
# select (false, x, y) -> y
name:            test_combine_select_false_res0_res1
legalized:       true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_combine_select_false_res0_res1
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $x1
    ; CHECK-NEXT: $x0 = COPY [[COPY]](s64)
    %0:_(s64) = COPY $x0
    %1:_(s64) = COPY $x1
    %2:_(s1) = G_CONSTANT i1 false
    %3:_(s64) = G_SELECT %2, %0, %1
    $x0 = COPY %3(s64)
...
---
# select (true, x, y) -> x
name:            test_combine_select_true_res0_res1
legalized:       true
body:             |
  bb.1:
    liveins: $x0, $x1
    ; CHECK-LABEL: name: test_combine_select_true_res0_res1
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $x0
    ; CHECK-NEXT: $x0 = COPY [[COPY]](s64)
    %0:_(s64) = COPY $x0
    %1:_(s64) = COPY $x1
    %2:_(s1) = G_CONSTANT i1 true
    %3:_(s64) = G_SELECT %2, %0, %1
    $x0 = COPY %3(s64)
...
