# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple aarch64 -run-pass=aarch64-postlegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name:            merge_unmerge
alignment:       4
legalized:       true
liveins:
  - { reg: '$w0' }
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: merge_unmerge
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $x0
    ; CHECK-NEXT: $x0 = COPY [[COPY]](s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $x0
    %0:_(s64) = COPY $x0
    %a:_(s32), %b:_(s32) = G_UNMERGE_VALUES %0
    %merge:_(s64) = G_MERGE_VALUES %a, %b
    $x0 = COPY %merge(s64)
    RET_ReallyLR implicit $x0

...
---
name:            merge_unmerge_mismatched_order
alignment:       4
legalized:       true
liveins:
  - { reg: '$w0' }
body:             |
  bb.1.entry:
    liveins: $x0

    ; CHECK-LABEL: name: merge_unmerge_mismatched_order
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $x0
    ; CHECK-NEXT: %b:_(s32), %a:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK-NEXT: %merge:_(s64) = G_MERGE_VALUES %a(s32), %b(s32)
    ; CHECK-NEXT: $x0 = COPY %merge(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $x0
    %0:_(s64) = COPY $x0
    %b:_(s32), %a:_(s32) = G_UNMERGE_VALUES %0
    %merge:_(s64) = G_MERGE_VALUES %a, %b
    $x0 = COPY %merge(s64)
    RET_ReallyLR implicit $x0

...
---
name:            merge_unmerge_mismatched_num_defs
alignment:       4
legalized:       true
liveins:
  - { reg: '$w0' }
body:             |
  bb.1.entry:
    liveins: $q0

    ; CHECK-LABEL: name: merge_unmerge_mismatched_num_defs
    ; CHECK: liveins: $q0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s128) = COPY $q0
    ; CHECK-NEXT: %a:_(s32), %b:_(s32), %c:_(s32), %d:_(s32) = G_UNMERGE_VALUES [[COPY]](s128)
    ; CHECK-NEXT: %merge:_(s64) = G_MERGE_VALUES %a(s32), %b(s32)
    ; CHECK-NEXT: $x0 = COPY %merge(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $x0
    %0:_(s128) = COPY $q0
    %a:_(s32), %b:_(s32), %c:_(s32), %d:_(s32) = G_UNMERGE_VALUES %0
    %merge:_(s64) = G_MERGE_VALUES %a, %b
    $x0 = COPY %merge(s64)
    RET_ReallyLR implicit $x0

...
---
name:            merge_to_zext
alignment:       4
legalized:       true
liveins:
  - { reg: '$w0' }
body:             |
  bb.1.entry:
    liveins: $w0

    ; CHECK-LABEL: name: merge_to_zext
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %v:_(s32) = COPY $w0
    ; CHECK-NEXT: %merge:_(s64) = G_ZEXT %v(s32)
    ; CHECK-NEXT: $x0 = COPY %merge(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $x0
    %v:_(s32) = COPY $w0
    %zero:_(s32) = G_CONSTANT i32 0
    %merge:_(s64) = G_MERGE_VALUES %v, %zero
    $x0 = COPY %merge(s64)
    RET_ReallyLR implicit $x0

...
