; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -global-isel -stop-after=legalizer -o - %s | FileCheck %s
target triple = "aarch64"

; Check we don't crash here or try to generate an ill-formed `G_UMAX` of
; pointer vectors.

define <4 x ptr> @pr168872(<4 x ptr> %ptrs) {
  ; CHECK-LABEL: name: pr168872
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   liveins: $q0, $q1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(<2 x i64>) = COPY $q0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(<2 x i64>) = COPY $q1
  ; CHECK-NEXT:   [[BITCAST:%[0-9]+]]:_(<2 x p0>) = G_BITCAST [[COPY]](<2 x i64>)
  ; CHECK-NEXT:   [[BITCAST1:%[0-9]+]]:_(<2 x p0>) = G_BITCAST [[COPY1]](<2 x i64>)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i64 0
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<2 x p0>) = G_BUILD_VECTOR [[C]](p0), [[C]](p0)
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(<2 x i64>) = G_ICMP intpred(ugt), [[BITCAST]](<2 x p0>), [[BUILD_VECTOR]]
  ; CHECK-NEXT:   [[ICMP1:%[0-9]+]]:_(<2 x i64>) = G_ICMP intpred(ugt), [[BITCAST1]](<2 x p0>), [[BUILD_VECTOR]]
  ; CHECK-NEXT:   [[BITCAST2:%[0-9]+]]:_(<2 x i64>) = G_BITCAST [[BITCAST]](<2 x p0>)
  ; CHECK-NEXT:   [[BITCAST3:%[0-9]+]]:_(<2 x i64>) = G_BITCAST [[BUILD_VECTOR]](<2 x p0>)
  ; CHECK-NEXT:   [[SELECT:%[0-9]+]]:_(<2 x i64>) = G_SELECT [[ICMP]](<2 x i64>), [[BITCAST2]], [[BITCAST3]]
  ; CHECK-NEXT:   [[BITCAST4:%[0-9]+]]:_(<2 x p0>) = G_BITCAST [[SELECT]](<2 x i64>)
  ; CHECK-NEXT:   [[BITCAST5:%[0-9]+]]:_(<2 x i64>) = G_BITCAST [[BITCAST1]](<2 x p0>)
  ; CHECK-NEXT:   [[BITCAST6:%[0-9]+]]:_(<2 x i64>) = G_BITCAST [[BUILD_VECTOR]](<2 x p0>)
  ; CHECK-NEXT:   [[SELECT1:%[0-9]+]]:_(<2 x i64>) = G_SELECT [[ICMP1]](<2 x i64>), [[BITCAST5]], [[BITCAST6]]
  ; CHECK-NEXT:   [[BITCAST7:%[0-9]+]]:_(<2 x p0>) = G_BITCAST [[SELECT1]](<2 x i64>)
  ; CHECK-NEXT:   [[BITCAST8:%[0-9]+]]:_(<2 x i64>) = G_BITCAST [[BITCAST4]](<2 x p0>)
  ; CHECK-NEXT:   [[BITCAST9:%[0-9]+]]:_(<2 x i64>) = G_BITCAST [[BITCAST7]](<2 x p0>)
  ; CHECK-NEXT:   $q0 = COPY [[BITCAST8]](<2 x i64>)
  ; CHECK-NEXT:   $q1 = COPY [[BITCAST9]](<2 x i64>)
  ; CHECK-NEXT:   RET_ReallyLR implicit $q0, implicit $q1
entry:
  %cmp = icmp ugt <4 x ptr> %ptrs, zeroinitializer
  %ptrs.select = select <4 x i1> %cmp, <4 x ptr> %ptrs, <4 x ptr> zeroinitializer
  ret <4 x ptr> %ptrs.select
}
