# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=aarch64 -run-pass=regbankselect -verify-machineinstrs %s -o - | FileCheck %s

...
---
name:            fp_inputs
legalized:       true
body:             |
  bb.0:
    liveins: $s0, $s1

    ; CHECK-LABEL: name: fp_inputs
    ; CHECK: liveins: $s0, $s1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %lhs:fpr(s32) = COPY $s0
    ; CHECK-NEXT: %rhs:fpr(s32) = COPY $s1
    ; CHECK-NEXT: %maxnum:fpr(s32) = G_FMAXNUM %lhs, %rhs
    ; CHECK-NEXT: $s0 = COPY %maxnum(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $s0
    %lhs:_(s32) = COPY $s0
    %rhs:_(s32) = COPY $s1
    %maxnum:_(s32) = G_FMAXNUM %lhs, %rhs
    $s0 = COPY %maxnum(s32)
    RET_ReallyLR implicit $s0

...
---
name:            gp_inputs
legalized:       true
body:             |
  bb.0:
    liveins: $w0, $w1

    ; CHECK-LABEL: name: gp_inputs
    ; CHECK: liveins: $w0, $w1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %lhs:gpr(s32) = COPY $w0
    ; CHECK-NEXT: %rhs:gpr(s32) = COPY $w1
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fpr(s32) = COPY %lhs(s32)
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:fpr(s32) = COPY %rhs(s32)
    ; CHECK-NEXT: %maxnum:fpr(s32) = G_FMAXNUM [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $s0 = COPY %maxnum(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $s0
    %lhs:_(s32) = COPY $w0
    %rhs:_(s32) = COPY $w1
    %maxnum:_(s32) = G_FMAXNUM %lhs, %rhs
    $s0 = COPY %maxnum(s32)
    RET_ReallyLR implicit $s0

...
---
name:            gp_use
legalized:       true
body:             |
  bb.0:
    liveins: $s0, $s1

    ; CHECK-LABEL: name: gp_use
    ; CHECK: liveins: $s0, $s1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %lhs:fpr(s32) = COPY $s0
    ; CHECK-NEXT: %rhs:fpr(s32) = COPY $s1
    ; CHECK-NEXT: %maxnum:fpr(s32) = G_FMAXNUM %lhs, %rhs
    ; CHECK-NEXT: $w0 = COPY %maxnum(s32)
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %lhs:_(s32) = COPY $s0
    %rhs:_(s32) = COPY $s1
    %maxnum:_(s32) = G_FMAXNUM %lhs, %rhs
    $w0 = COPY %maxnum(s32)
    RET_ReallyLR implicit $w0
