# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=aarch64 -run-pass=regbankselect -verify-machineinstrs %s -o - | FileCheck %s

...
---
name:            no_cross_bank_copies_needed
legalized:       true
regBankSelected: false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $d0
    ; CHECK-LABEL: name: no_cross_bank_copies_needed
    ; CHECK: liveins: $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %fpr:fpr(s64) = COPY $d0
    ; CHECK-NEXT: %llround:fpr(s64) = G_LLROUND %fpr(s64)
    ; CHECK-NEXT: $d0 = COPY %llround(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $s0
    %fpr:_(s64) = COPY $d0
    %llround:_(s64) = G_LLROUND %fpr
    $d0 = COPY %llround:_(s64)
    RET_ReallyLR implicit $s0
...
---
name:            source_needs_copy
legalized:       true
regBankSelected: false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: source_needs_copy
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %gpr:gpr(s64) = COPY $x0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fpr(i64) = COPY %gpr(s64)
    ; CHECK-NEXT: %llround:fpr(s64) = G_LLROUND [[COPY]](i64)
    ; CHECK-NEXT: $d0 = COPY %llround(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $s0
    %gpr:_(s64) = COPY $x0
    %llround:_(s64) = G_LLROUND %gpr
    $d0 = COPY %llround:_(s64)
    RET_ReallyLR implicit $s0
...
---
name:            load_gets_fpr
legalized:       true
regBankSelected: false
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: load_gets_fpr
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %ptr:gpr(p0) = COPY $x0
    ; CHECK-NEXT: %load:fpr(s32) = G_LOAD %ptr(p0) :: (load (s32))
    ; CHECK-NEXT: %llround:gpr(s64) = G_LLROUND %load(s32)
    ; CHECK-NEXT: $d0 = COPY %llround(s64)
    ; CHECK-NEXT: RET_ReallyLR implicit $s0
    %ptr:_(p0) = COPY $x0
    %load:_(s32) = G_LOAD %ptr(p0) :: (load (s32))
    %llround:_(s64) = G_LLROUND %load
    $d0 = COPY %llround:_(s64)
    RET_ReallyLR implicit $s0

...
