# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=aarch64 -run-pass=instruction-select -verify-machineinstrs -global-isel-abort=1 %s -o - | FileCheck %s
---
name:            add_B
alignment:       4
legalized:       true
regBankSelected: true
tracksRegLiveness: true
liveins:
  - { reg: '$x0' }
body:             |
  bb.1:
    liveins: $x0

    ; CHECK-LABEL: name: add_B
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr64sp = COPY $x0
    ; CHECK-NEXT: [[LDRQui:%[0-9]+]]:fpr128 = LDRQui [[COPY]], 0 :: (load (<16 x s8>))
    ; CHECK-NEXT: [[ADDVv16i8v:%[0-9]+]]:fpr8 = ADDVv16i8v [[LDRQui]]
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:fpr32 = IMPLICIT_DEF
    ; CHECK-NEXT: [[INSERT_SUBREG:%[0-9]+]]:fpr32 = INSERT_SUBREG [[DEF]], [[ADDVv16i8v]], %subreg.bsub
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr32all = COPY [[INSERT_SUBREG]]
    ; CHECK-NEXT: $w0 = COPY [[COPY1]]
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:gpr(p0) = COPY $x0
    %1:fpr(<16 x i8>) = G_LOAD %0(p0) :: (load (<16 x s8>))
    %2:fpr(i8) = G_VECREDUCE_ADD %1(<16 x i8>)
    %4:gpr(i8) = COPY %2(i8)
    %3:gpr(i32) = G_ANYEXT %4(i8)
    $w0 = COPY %3(i32)
    RET_ReallyLR implicit $w0

...
---
name:            add_H
alignment:       4
legalized:       true
regBankSelected: true
tracksRegLiveness: true
liveins:
  - { reg: '$x0' }
body:             |
  bb.1:
    liveins: $x0

    ; CHECK-LABEL: name: add_H
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr64sp = COPY $x0
    ; CHECK-NEXT: [[LDRQui:%[0-9]+]]:fpr128 = LDRQui [[COPY]], 0 :: (load (<8 x s16>))
    ; CHECK-NEXT: [[ADDVv8i16v:%[0-9]+]]:fpr16 = ADDVv8i16v [[LDRQui]]
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:fpr32 = IMPLICIT_DEF
    ; CHECK-NEXT: [[INSERT_SUBREG:%[0-9]+]]:fpr32 = INSERT_SUBREG [[DEF]], [[ADDVv8i16v]], %subreg.hsub
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr32all = COPY [[INSERT_SUBREG]]
    ; CHECK-NEXT: $w0 = COPY [[COPY1]]
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:gpr(p0) = COPY $x0
    %1:fpr(<8 x i16>) = G_LOAD %0(p0) :: (load (<8 x s16>))
    %2:fpr(i16) = G_VECREDUCE_ADD %1(<8 x i16>)
    %4:gpr(i16) = COPY %2(i16)
    %3:gpr(i32) = G_ANYEXT %4(i16)
    $w0 = COPY %3(i32)
    RET_ReallyLR implicit $w0

...
---
name:            add_S
alignment:       4
legalized:       true
regBankSelected: true
tracksRegLiveness: true
liveins:
  - { reg: '$x0' }
body:             |
  bb.1:
    liveins: $x0

    ; CHECK-LABEL: name: add_S
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr64sp = COPY $x0
    ; CHECK-NEXT: [[LDRQui:%[0-9]+]]:fpr128 = LDRQui [[COPY]], 0 :: (load (<4 x s32>))
    ; CHECK-NEXT: [[ADDVv4i32v:%[0-9]+]]:fpr32 = ADDVv4i32v [[LDRQui]]
    ; CHECK-NEXT: $w0 = COPY [[ADDVv4i32v]]
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:gpr(p0) = COPY $x0
    %1:fpr(<4 x i32>) = G_LOAD %0(p0) :: (load (<4 x s32>))
    %2:fpr(i32) = G_VECREDUCE_ADD %1(<4 x i32>)
    $w0 = COPY %2(i32)
    RET_ReallyLR implicit $w0

...
---
name:            add_S_v2i32
alignment:       4
legalized:       true
regBankSelected: true
tracksRegLiveness: true
liveins:
  - { reg: '$x0' }
body:             |
  bb.1:
    liveins: $x0

    ; CHECK-LABEL: name: add_S_v2i32
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr64sp = COPY $x0
    ; CHECK-NEXT: [[LDRDui:%[0-9]+]]:fpr64 = LDRDui [[COPY]], 0 :: (load (<2 x s32>))
    ; CHECK-NEXT: [[ADDPv2i32_:%[0-9]+]]:fpr64 = ADDPv2i32 [[LDRDui]], [[LDRDui]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:fpr32 = COPY [[ADDPv2i32_]].ssub
    ; CHECK-NEXT: $w0 = COPY [[COPY1]]
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %0:gpr(p0) = COPY $x0
    %1:fpr(<2 x i32>) = G_LOAD %0(p0) :: (load (<2 x s32>))
    %2:fpr(i32) = G_VECREDUCE_ADD %1(<2 x i32>)
    $w0 = COPY %2(i32)
    RET_ReallyLR implicit $w0

...
---
name:            add_D
alignment:       4
legalized:       true
regBankSelected: true
tracksRegLiveness: true
liveins:
  - { reg: '$x0' }
body:             |
  bb.1:
    liveins: $x0

    ; CHECK-LABEL: name: add_D
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr64sp = COPY $x0
    ; CHECK-NEXT: [[LDRQui:%[0-9]+]]:fpr128 = LDRQui [[COPY]], 0 :: (load (<2 x s64>))
    ; CHECK-NEXT: [[ADDPv2i64p:%[0-9]+]]:fpr64 = ADDPv2i64p [[LDRQui]]
    ; CHECK-NEXT: $x0 = COPY [[ADDPv2i64p]]
    ; CHECK-NEXT: RET_ReallyLR implicit $x0
    %0:gpr(p0) = COPY $x0
    %1:fpr(<2 x i64>) = G_LOAD %0(p0) :: (load (<2 x s64>))
    %2:fpr(i64) = G_VECREDUCE_ADD %1(<2 x i64>)
    $x0 = COPY %2(i64)
    RET_ReallyLR implicit $x0

...
