# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -verify-machineinstrs -mtriple aarch64-unknown-unknown -run-pass=instruction-select %s -o - | FileCheck %s
---
name:            f64_faddp
alignment:       4
legalized:       true
regBankSelected: true
tracksRegLiveness: true
liveins:
  - { reg: '$q0' }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $q0

    ; CHECK-LABEL: name: f64_faddp
    ; CHECK: liveins: $q0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fpr128 = COPY $q0
    ; CHECK-NEXT: [[FADDPv2i64p:%[0-9]+]]:fpr64 = nofpexcept FADDPv2i64p [[COPY]], implicit $fpcr
    ; CHECK-NEXT: $d0 = COPY [[FADDPv2i64p]]
    ; CHECK-NEXT: RET_ReallyLR implicit $d0
    %0:fpr(<2 x f64>) = COPY $q0
    %6:gpr(i64) = G_CONSTANT i64 0
    %7:fpr(f64) = G_EXTRACT_VECTOR_ELT %0(<2 x f64>), %6(i64)
    %8:gpr(i64) = G_CONSTANT i64 1
    %9:fpr(f64) = G_EXTRACT_VECTOR_ELT %0(<2 x f64>), %8(i64)
    %4:fpr(f64) = G_FADD %7, %9
    $d0 = COPY %4(f64)
    RET_ReallyLR implicit $d0

...
---
name:            f32_faddp
alignment:       4
legalized:       true
regBankSelected: true
tracksRegLiveness: true
liveins:
  - { reg: '$d0' }
frameInfo:
  maxAlignment:    1
body:             |
  bb.1:
    liveins: $d0

    ; CHECK-LABEL: name: f32_faddp
    ; CHECK: liveins: $d0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fpr64 = COPY $d0
    ; CHECK-NEXT: [[FADDPv2i32p:%[0-9]+]]:fpr32 = nofpexcept FADDPv2i32p [[COPY]], implicit $fpcr
    ; CHECK-NEXT: $s0 = COPY [[FADDPv2i32p]]
    ; CHECK-NEXT: RET_ReallyLR implicit $s0
    %0:fpr(<2 x f32>) = COPY $d0
    %6:gpr(i64) = G_CONSTANT i64 0
    %7:fpr(f32) = G_EXTRACT_VECTOR_ELT %0(<2 x f32>), %6(i64)
    %8:gpr(i64) = G_CONSTANT i64 1
    %9:fpr(f32) = G_EXTRACT_VECTOR_ELT %0(<2 x f32>), %8(i64)
    %4:fpr(f32) = G_FADD %7, %9
    $s0 = COPY %4(f32)
    RET_ReallyLR implicit $s0

...
