# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=aarch64-unknown-unknown -mattr=+fullfp16 -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s

---
name:            positive_zero
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: positive_zero
    ; CHECK: [[FMOVH0_:%[0-9]+]]:fpr16 = FMOVH0
    ; CHECK-NEXT: $h0 = COPY [[FMOVH0_]]
    ; CHECK-NEXT: RET_ReallyLR implicit $h0
    %0:fpr(s16) = G_FCONSTANT half 0.0
    $h0 = COPY %0(s16)
    RET_ReallyLR implicit $h0
...
---
name:            one
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: one
    ; CHECK: [[FMOVHi:%[0-9]+]]:fpr16 = FMOVHi 112
    ; CHECK-NEXT: $h0 = COPY [[FMOVHi]]
    ; CHECK-NEXT: RET_ReallyLR implicit $h0
    %0:fpr(s16) = G_FCONSTANT half 1.0
    $h0 = COPY %0(s16)
    RET_ReallyLR implicit $h0
...
---
name:            constant_pool_load
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: constant_pool_load
    ; CHECK: [[MOVIv4i16_:%[0-9]+]]:fpr64 = MOVIv4i16 11, 0
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fpr16 = COPY [[MOVIv4i16_]].hsub
    ; CHECK-NEXT: $h0 = COPY [[COPY]]
    ; CHECK-NEXT: RET_ReallyLR implicit $h0
    %0:fpr(s16) = G_FCONSTANT half 0xH000B
    $h0 = COPY %0(s16)
    RET_ReallyLR implicit $h0
