; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -global-isel -mtriple aarch64 -verify-machineinstrs %s -o - | FileCheck %s

define i32 @smulfix_i32_scale_0(i32 %1, i32 %2) {
; CHECK-LABEL: smulfix_i32_scale_0:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mul w0, w0, w1
; CHECK-NEXT:    ret
  %m = call i32 @llvm.smul.fix.i32(i32 %1, i32 %2, i32 0)
  ret i32 %m
}

define i32 @smulfix_i32(i32 %1, i32 %2) {
; CHECK-LABEL: smulfix_i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    smull x8, w0, w1
; CHECK-NEXT:    asr x0, x8, #15
; CHECK-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-NEXT:    ret
  %m = call i32 @llvm.smul.fix.i32(i32 %1, i32 %2, i32 15)
  ret i32 %m
}

define i64 @smulfix_i64(i64 %1, i64 %2) {
; CHECK-LABEL: smulfix_i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    asr x8, x1, #63
; CHECK-NEXT:    asr x9, x0, #63
; CHECK-NEXT:    umulh x10, x0, x1
; CHECK-NEXT:    mul x8, x0, x8
; CHECK-NEXT:    madd x8, x9, x1, x8
; CHECK-NEXT:    mul x9, x0, x1
; CHECK-NEXT:    add x8, x8, x10
; CHECK-NEXT:    extr x0, x8, x9, #15
; CHECK-NEXT:    ret
  %m = call i64 @llvm.smul.fix.i64(i64 %1, i64 %2, i32 15)
  ret i64 %m
}

define <4 x i32> @smulfix_4xi32(<4 x i32> %1, <4 x i32> %2) {
; CHECK-LABEL: smulfix_4xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    smull v2.2d, v0.2s, v1.2s
; CHECK-NEXT:    smull2 v1.2d, v0.4s, v1.4s
; CHECK-NEXT:    shrn v0.2s, v2.2d, #2
; CHECK-NEXT:    shrn2 v0.4s, v1.2d, #2
; CHECK-NEXT:    ret
  %m = call <4 x i32> @llvm.smul.fix.v4i32(<4 x i32> %1, <4 x i32> %2, i32 2)
  ret <4 x i32> %m
}

define <4 x i32> @smulfix_4xi32_15(<4 x i32> %1, <4 x i32> %2) {
; CHECK-LABEL: smulfix_4xi32_15:
; CHECK:       // %bb.0:
; CHECK-NEXT:    smull v2.2d, v0.2s, v1.2s
; CHECK-NEXT:    smull2 v1.2d, v0.4s, v1.4s
; CHECK-NEXT:    shrn v0.2s, v2.2d, #15
; CHECK-NEXT:    shrn2 v0.4s, v1.2d, #15
; CHECK-NEXT:    ret
  %m = call <4 x i32> @llvm.smul.fix.v4i32(<4 x i32> %1, <4 x i32> %2, i32 15)
  ret <4 x i32> %m
}

define <4 x i32> @smulfix_4xi32_31(<4 x i32> %1, <4 x i32> %2) {
; CHECK-LABEL: smulfix_4xi32_31:
; CHECK:       // %bb.0:
; CHECK-NEXT:    smull v2.2d, v0.2s, v1.2s
; CHECK-NEXT:    smull2 v1.2d, v0.4s, v1.4s
; CHECK-NEXT:    shrn v0.2s, v2.2d, #31
; CHECK-NEXT:    shrn2 v0.4s, v1.2d, #31
; CHECK-NEXT:    ret
  %m = call <4 x i32> @llvm.smul.fix.v4i32(<4 x i32> %1, <4 x i32> %2, i32 31)
  ret <4 x i32> %m
}
