; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; Check that -store-merging=false disables GlobalISel store merging.
; RUN: llc -mtriple=aarch64-apple-ios -global-isel -global-isel-abort=1 < %s | FileCheck %s --check-prefix=MERGE
; RUN: llc -mtriple=aarch64-apple-ios -global-isel -global-isel-abort=1 -store-merging=false < %s | FileCheck %s --check-prefix=NOMERGE

define void @test_2xs16(ptr %ptr) {
; MERGE-LABEL: test_2xs16:
; MERGE:       ; %bb.0:
; MERGE-NEXT:    mov w8, #4 ; =0x4
; MERGE-NEXT:    movk w8, #5, lsl #16
; MERGE-NEXT:    str w8, [x0]
; MERGE-NEXT:    ret
;
; NOMERGE-LABEL: test_2xs16:
; NOMERGE:       ; %bb.0:
; NOMERGE-NEXT:    mov w8, #4 ; =0x4
; NOMERGE-NEXT:    mov w9, #5 ; =0x5
; NOMERGE-NEXT:    strh w8, [x0]
; NOMERGE-NEXT:    strh w9, [x0, #2]
; NOMERGE-NEXT:    ret
  store i16 4, ptr %ptr
  %addr2 = getelementptr i16, ptr %ptr, i64 1
  store i16 5, ptr %addr2
  ret void
}
