# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=aarch64-apple-ios -global-isel -global-isel-abort=1 -run-pass=loadstore-opt %s -o - | FileCheck %s

--- |
  source_filename = "store-merging-debug.mir"
  target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
  target triple = "aarch64-apple-ios"

  define void @test_simple_4xs16() !dbg !5 {
  entry:
    call void @llvm.dbg.value(metadata i32 0, metadata !9, metadata !DIExpression()), !dbg !11
    unreachable, !dbg !11
  }

  ; Function Attrs: nocallback nofree nosync nounwind readnone speculatable willreturn
  declare void @llvm.dbg.value(metadata, metadata, metadata) #0

  attributes #0 = { nocallback nofree nosync nounwind readnone speculatable willreturn }

  !llvm.dbg.cu = !{!0}
  !llvm.mir.debugify = !{!2, !3}
  !llvm.debugify = !{!3, !3}
  !llvm.module.flags = !{!4}

  !0 = distinct !DICompileUnit(language: DW_LANG_C, file: !1, producer: "debugify", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
  !1 = !DIFile(filename: "store-merging-debug.mir", directory: "/")
  !2 = !{i32 16}
  !3 = !{i32 1}
  !4 = !{i32 2, !"Debug Info Version", i32 3}
  !5 = distinct !DISubprogram(name: "test_simple_4xs16", linkageName: "test_simple_4xs16", scope: null, file: !1, line: 1, type: !6, scopeLine: 1, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !8)
  !6 = !DISubroutineType(types: !7)
  !7 = !{}
  !8 = !{!9}
  !9 = !DILocalVariable(name: "1", scope: !5, file: !1, line: 1, type: !10)
  !10 = !DIBasicType(name: "ty32", size: 32, encoding: DW_ATE_unsigned)
  !11 = !DILocation(line: 1, column: 1, scope: !5)

...
---
name:            test_simple_4xs16
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
liveins:
  - { reg: '$x0', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 0
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       []
  restorePoint:    []
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0:
    liveins: $x0

    ; CHECK-LABEL: name: test_simple_4xs16
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $x0,  debug-location !11
    ; CHECK-NEXT: DBG_VALUE [[COPY]](p0), $noreg, !9, !DIExpression(),  debug-location !11
    ; CHECK-NEXT: DBG_VALUE %1:_(s16), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 2, column: 1, scope: !5)
    ; CHECK-NEXT: DBG_VALUE %4:_(s16), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 3, column: 1, scope: !5)
    ; CHECK-NEXT: DBG_VALUE %7:_(s16), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 4, column: 1, scope: !5)
    ; CHECK-NEXT: DBG_VALUE %10:_(s16), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 5, column: 1, scope: !5)
    ; CHECK-NEXT: DBG_VALUE 0, $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 6, column: 1, scope: !5)
    ; CHECK-NEXT: DBG_VALUE %2:_(s64), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 7, column: 1, scope: !5)
    ; CHECK-NEXT: DBG_VALUE %3:_(p0), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 8, column: 1, scope: !5)
    ; CHECK-NEXT: DBG_VALUE 1, $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 9, column: 1, scope: !5)
    ; CHECK-NEXT: DBG_VALUE %5:_(s64), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 10, column: 1, scope: !5)
    ; CHECK-NEXT: DBG_VALUE %6:_(p0), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 11, column: 1, scope: !5)
    ; CHECK-NEXT: DBG_VALUE 2, $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 12, column: 1, scope: !5)
    ; CHECK-NEXT: DBG_VALUE %8:_(s64), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 13, column: 1, scope: !5)
    ; CHECK-NEXT: DBG_VALUE %9:_(p0), $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 14, column: 1, scope: !5)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 3940688328982532
    ; CHECK-NEXT: G_STORE [[C]](s64), [[COPY]](p0),  debug-location !DILocation(line: 9, scope: !5) :: (store (s64), align 2)
    ; CHECK-NEXT: DBG_VALUE 3, $noreg, !9, !DIExpression(),  debug-location !DILocation(line: 15, column: 1, scope: !5)
    ; CHECK-NEXT: RET_ReallyLR debug-location !DILocation(line: 16, column: 1, scope: !5)
    %0:_(p0) = COPY $x0, debug-location !11
    DBG_VALUE %0(p0), $noreg, !9, !DIExpression(), debug-location !11
    %1:_(s16) = G_CONSTANT i16 4, debug-location !DILocation(line: 2, column: 1, scope: !5)
    DBG_VALUE %1(s16), $noreg, !9, !DIExpression(), debug-location !DILocation(line: 2, column: 1, scope: !5)
    %4:_(s16) = G_CONSTANT i16 5, debug-location !DILocation(line: 3, column: 1, scope: !5)
    DBG_VALUE %4(s16), $noreg, !9, !DIExpression(), debug-location !DILocation(line: 3, column: 1, scope: !5)
    %7:_(s16) = G_CONSTANT i16 9, debug-location !DILocation(line: 4, column: 1, scope: !5)
    DBG_VALUE %7(s16), $noreg, !9, !DIExpression(), debug-location !DILocation(line: 4, column: 1, scope: !5)
    %10:_(s16) = G_CONSTANT i16 14, debug-location !DILocation(line: 5, column: 1, scope: !5)
    DBG_VALUE %10(s16), $noreg, !9, !DIExpression(), debug-location !DILocation(line: 5, column: 1, scope: !5)
    G_STORE %1(s16), %0(p0), debug-location !DILocation(line: 9, column: 1, scope: !5) :: (store (s16))
    DBG_VALUE 0, $noreg, !9, !DIExpression(), debug-location !DILocation(line: 6, column: 1, scope: !5)
    %2:_(s64) = G_CONSTANT i64 2, debug-location !DILocation(line: 7, column: 1, scope: !5)
    DBG_VALUE %2(s64), $noreg, !9, !DIExpression(), debug-location !DILocation(line: 7, column: 1, scope: !5)
    %3:_(p0) = G_PTR_ADD %0, %2(s64), debug-location !DILocation(line: 8, column: 1, scope: !5)
    DBG_VALUE %3(p0), $noreg, !9, !DIExpression(), debug-location !DILocation(line: 8, column: 1, scope: !5)
    G_STORE %4(s16), %3(p0), debug-location !DILocation(line: 9, column: 1, scope: !5) :: (store (s16))
    DBG_VALUE 1, $noreg, !9, !DIExpression(), debug-location !DILocation(line: 9, column: 1, scope: !5)
    %5:_(s64) = G_CONSTANT i64 4, debug-location !DILocation(line: 10, column: 1, scope: !5)
    DBG_VALUE %5(s64), $noreg, !9, !DIExpression(), debug-location !DILocation(line: 10, column: 1, scope: !5)
    %6:_(p0) = G_PTR_ADD %0, %5(s64), debug-location !DILocation(line: 11, column: 1, scope: !5)
    DBG_VALUE %6(p0), $noreg, !9, !DIExpression(), debug-location !DILocation(line: 11, column: 1, scope: !5)
    G_STORE %7(s16), %6(p0), debug-location !DILocation(line: 9, column: 4, scope: !5) :: (store (s16))
    DBG_VALUE 2, $noreg, !9, !DIExpression(), debug-location !DILocation(line: 12, column: 1, scope: !5)
    %8:_(s64) = G_CONSTANT i64 6, debug-location !DILocation(line: 13, column: 1, scope: !5)
    DBG_VALUE %8(s64), $noreg, !9, !DIExpression(), debug-location !DILocation(line: 13, column: 1, scope: !5)
    %9:_(p0) = G_PTR_ADD %0, %8(s64), debug-location !DILocation(line: 14, column: 1, scope: !5)
    DBG_VALUE %9(p0), $noreg, !9, !DIExpression(), debug-location !DILocation(line: 14, column: 1, scope: !5)
    G_STORE %10(s16), %9(p0), debug-location !DILocation(line: 9, column: 4, scope: !5) :: (store (s16))
    DBG_VALUE 3, $noreg, !9, !DIExpression(), debug-location !DILocation(line: 15, column: 1, scope: !5)
    RET_ReallyLR debug-location !DILocation(line: 16, column: 1, scope: !5)

...
