# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=aarch64-unknown-linux -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s -check-prefixes=CHECK

--- |
  target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
  target triple = "aarch64-unknown-linux"

  %struct.__va_list = type { ptr, ptr, ptr, i32, i32 }

  define i32 @va_start(ptr %a, ...) {
  entry:
    %ap = alloca %struct.__va_list, align 8
    call void @llvm.lifetime.start.p0(ptr %ap)
    call void @llvm.va_start.p0(ptr %ap)
    %vr_offs_p = getelementptr inbounds i8, ptr %ap, i64 28
    %vr_offs = load i32, ptr %vr_offs_p, align 4
    ret i32 %vr_offs
  }
...
---
name:            va_start
alignment:       16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
fixedStack:
  - { id: 0, size: 4, alignment: 16 }
stack:
  - { id: 0, size: 56, alignment: 8 }
  - { id: 1, size: 128, alignment: 16 }
  - { id: 2, name: ap, size: 32, alignment: 8 }
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: va_start
    ; CHECK: LIFETIME_START %stack.2.ap
    ; CHECK-NEXT: [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri %stack.2.ap, 0, 0
    ; CHECK-NEXT: [[ADDXri1:%[0-9]+]]:gpr64common = ADDXri %stack.0, 0, 0
    ; CHECK-NEXT: STRXui [[ADDXri1]], [[ADDXri]], 0 :: (store (s64) into %ir.ap)
    ; CHECK-NEXT: [[ADDXri2:%[0-9]+]]:gpr64common = ADDXri %stack.0, 0, 0
    ; CHECK-NEXT: STRXui [[ADDXri2]], [[ADDXri]], 1 :: (store (s64) into %ir.ap + 8)
    ; CHECK-NEXT: [[ADDXri3:%[0-9]+]]:gpr64common = ADDXri %stack.0, 0, 0
    ; CHECK-NEXT: STRXui [[ADDXri3]], [[ADDXri]], 2 :: (store (s64) into %ir.ap + 16)
    ; CHECK-NEXT: [[MOVi32imm:%[0-9]+]]:gpr32 = MOVi32imm 0
    ; CHECK-NEXT: STRWui [[MOVi32imm]], [[ADDXri]], 6 :: (store (s32) into %ir.ap + 24, align 8)
    ; CHECK-NEXT: [[MOVi32imm1:%[0-9]+]]:gpr32 = MOVi32imm 0
    ; CHECK-NEXT: STRWui [[MOVi32imm1]], [[ADDXri]], 7 :: (store (s32) into %ir.ap + 28, basealign 8)
    ; CHECK-NEXT: [[LDRWui:%[0-9]+]]:gpr32 = LDRWui %stack.2.ap, 7 :: (dereferenceable load (s32) from %ir.vr_offs_p)
    ; CHECK-NEXT: $w0 = COPY [[LDRWui]]
    LIFETIME_START %stack.2.ap
    %0:gpr(p0) = G_FRAME_INDEX %stack.2.ap
    G_VASTART %0(p0) :: (store (s256) into %ir.ap, align 8)
    %1:gpr(s64) = G_CONSTANT i64 28
    %2:gpr(p0) = G_PTR_ADD %0, %1(s64)
    %3:gpr(s32) = G_LOAD %2(p0) :: (dereferenceable load (s32) from %ir.vr_offs_p)
    $w0 = COPY %3(s32)
...
