; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -mtriple=powerpc-unknown-aix -mcpu=pwr10 -passes=slp-vectorizer < %s | FileCheck %s

define range(i64 0, 8) i64 @extract_bits1(i64 noundef %a) local_unnamed_addr {
; CHECK-LABEL: @extract_bits1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x i64> poison, i64 [[A:%.*]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i64> [[TMP0]], <2 x i64> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = lshr <2 x i64> [[TMP1]], <i64 2, i64 5>
; CHECK-NEXT:    [[TMP3:%.*]] = and <2 x i64> [[TMP2]], <i64 1, i64 6>
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <2 x i64> [[TMP3]], i32 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x i64> [[TMP3]], i32 1
; CHECK-NEXT:    [[OR:%.*]] = or disjoint i64 [[TMP4]], [[TMP5]]
; CHECK-NEXT:    ret i64 [[OR]]
;
entry:
  %shr = lshr i64 %a, 2
  %and = and i64 %shr, 1
  %shr1 = lshr i64 %a, 5
  %and2 = and i64 %shr1, 6
  %or = or disjoint i64 %and, %and2
  ret i64 %or
}
