; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=normalize < %s | FileCheck %s

define i32 @foo(i32 %a0) {
; CHECK-LABEL: define i32 @foo(
; CHECK-SAME: i32 [[A0:%.*]]) {
; CHECK-NEXT:  [[BB17254:.*:]]
; CHECK-NEXT:    %"vl12603([[A0]], 2)" = add i32 [[A0]], 2
; CHECK-NEXT:    ret i32 %"vl12603([[A0]], 2)"
;
entry:
  %a = add i32 %a0, 2
  ret i32 %a
}

define i32 @bar(i32 %a0) {
; CHECK-LABEL: define i32 @bar(
; CHECK-SAME: i32 [[A0:%.*]]) {
; CHECK-NEXT:  [[BB17254:.*:]]
; CHECK-NEXT:    %"vl76167([[A0]], 2)" = add i32 [[A0]], 2
; CHECK-NEXT:    %"op10412(vl76167)" = add i32 6, %"vl76167([[A0]], 2)"
; CHECK-NEXT:    %"op10412(op10412)" = add i32 8, %"op10412(vl76167)"
; CHECK-NEXT:    ret i32 %"op10412(op10412)"
;
entry:
  %a = add i32 %a0, 2
  %b = add i32 %a, 6
  %c = add i32 %b, 8
  ret i32 %c
}
