; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=m68k-pc-linux -relocation-model=pic -verify-machineinstrs | FileCheck %s

;
; Pass first two arguments in registers %d0 and %d1

define void @foo_inreg(i32* nocapture inreg %out, i32 inreg %in) nounwind {
; CHECK-LABEL: foo_inreg:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    move.l %d0, %a0
; CHECK-NEXT:    move.l %d1, (%a0)
; CHECK-NEXT:    rts
entry:
  store i32 %in, i32* %out, align 4
  ret void
}

define void @bar_inreg(i32* nocapture inreg %pOut, i32* nocapture inreg %pIn) nounwind {
; CHECK-LABEL: bar_inreg:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    move.l %d1, %a0
; CHECK-NEXT:    move.l %d0, %a1
; CHECK-NEXT:    move.l (%a0), (%a1)
; CHECK-NEXT:    rts
entry:
  %0 = load i32, i32* %pIn, align 4
  store i32 %0, i32* %pOut, align 4
  ret void
}
