// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple aarch64-none-linux-gnu -target-feature +neon \
// RUN:   -emit-llvm -o - %s \
// RUN: | FileCheck %s --check-prefix=LLVM
#include<arm_neon.h>


// LLVM-LABEL: define dso_local i64 @test_vqshlud_n_s64(
// LLVM-SAME: i64 noundef [[A:%.*]]) #[[ATTR0:[0-9]+]] {
// LLVM-NEXT:  [[ENTRY:.*:]]
// LLVM-NEXT:    [[A_ADDR:%.*]] = alloca i64, align 8
// LLVM-NEXT:    [[__RET:%.*]] = alloca i64, align 8
// LLVM-NEXT:    [[__S0:%.*]] = alloca i64, align 8
// LLVM-NEXT:    [[REF_TMP:%.*]] = alloca i64, align 8
// LLVM-NEXT:    [[TMP:%.*]] = alloca i64, align 8
// LLVM-NEXT:    store i64 [[A]], ptr [[A_ADDR]], align 8
// LLVM-NEXT:    [[TMP0:%.*]] = load i64, ptr [[A_ADDR]], align 8
// LLVM-NEXT:    store i64 [[TMP0]], ptr [[__S0]], align 8
// LLVM-NEXT:    [[TMP1:%.*]] = load i64, ptr [[__S0]], align 8
// LLVM-NEXT:    [[VQSHLU_N:%.*]] = call i64 @llvm.aarch64.neon.sqshlu.i64(i64 [[TMP1]], i64 1)
// LLVM-NEXT:    store i64 [[VQSHLU_N]], ptr [[REF_TMP]], align 8
// LLVM-NEXT:    [[TMP2:%.*]] = load i64, ptr [[REF_TMP]], align 8
// LLVM-NEXT:    store i64 [[TMP2]], ptr [[__RET]], align 8
// LLVM-NEXT:    [[TMP3:%.*]] = load i64, ptr [[__RET]], align 8
// LLVM-NEXT:    store i64 [[TMP3]], ptr [[TMP]], align 8
// LLVM-NEXT:    [[TMP4:%.*]] = load i64, ptr [[TMP]], align 8
// LLVM-NEXT:    ret i64 [[TMP4]]
//
int64_t test_vqshlud_n_s64(int64_t a) {
  return vqshlud_n_s64(a, 1);
}

// LLVM-LABEL: define dso_local i64 @test_vqshld_n_s64(
// LLVM-SAME: i64 noundef [[A:%.*]]) #[[ATTR0]] {
// LLVM-NEXT:  [[ENTRY:.*:]]
// LLVM-NEXT:    [[A_ADDR:%.*]] = alloca i64, align 8
// LLVM-NEXT:    [[__RET:%.*]] = alloca i64, align 8
// LLVM-NEXT:    [[__S0:%.*]] = alloca i64, align 8
// LLVM-NEXT:    [[REF_TMP:%.*]] = alloca i64, align 8
// LLVM-NEXT:    [[TMP:%.*]] = alloca i64, align 8
// LLVM-NEXT:    store i64 [[A]], ptr [[A_ADDR]], align 8
// LLVM-NEXT:    [[TMP0:%.*]] = load i64, ptr [[A_ADDR]], align 8
// LLVM-NEXT:    store i64 [[TMP0]], ptr [[__S0]], align 8
// LLVM-NEXT:    [[TMP1:%.*]] = load i64, ptr [[__S0]], align 8
// LLVM-NEXT:    [[VQSHL_N:%.*]] = call i64 @llvm.aarch64.neon.sqshl.i64(i64 [[TMP1]], i64 1)
// LLVM-NEXT:    store i64 [[VQSHL_N]], ptr [[REF_TMP]], align 8
// LLVM-NEXT:    [[TMP2:%.*]] = load i64, ptr [[REF_TMP]], align 8
// LLVM-NEXT:    store i64 [[TMP2]], ptr [[__RET]], align 8
// LLVM-NEXT:    [[TMP3:%.*]] = load i64, ptr [[__RET]], align 8
// LLVM-NEXT:    store i64 [[TMP3]], ptr [[TMP]], align 8
// LLVM-NEXT:    [[TMP4:%.*]] = load i64, ptr [[TMP]], align 8
// LLVM-NEXT:    ret i64 [[TMP4]]
//
int64_t test_vqshld_n_s64(int64_t a) {
  return vqshld_n_s64(a, 1);
}

// LLVM-LABEL: define dso_local i64 @test_vqshld_n_u64(
// LLVM-SAME: i64 noundef [[A:%.*]]) #[[ATTR0]] {
// LLVM-NEXT:  [[ENTRY:.*:]]
// LLVM-NEXT:    [[A_ADDR:%.*]] = alloca i64, align 8
// LLVM-NEXT:    [[__RET:%.*]] = alloca i64, align 8
// LLVM-NEXT:    [[__S0:%.*]] = alloca i64, align 8
// LLVM-NEXT:    [[REF_TMP:%.*]] = alloca i64, align 8
// LLVM-NEXT:    [[TMP:%.*]] = alloca i64, align 8
// LLVM-NEXT:    store i64 [[A]], ptr [[A_ADDR]], align 8
// LLVM-NEXT:    [[TMP0:%.*]] = load i64, ptr [[A_ADDR]], align 8
// LLVM-NEXT:    store i64 [[TMP0]], ptr [[__S0]], align 8
// LLVM-NEXT:    [[TMP1:%.*]] = load i64, ptr [[__S0]], align 8
// LLVM-NEXT:    [[VQSHL_N:%.*]] = call i64 @llvm.aarch64.neon.uqshl.i64(i64 [[TMP1]], i64 1)
// LLVM-NEXT:    store i64 [[VQSHL_N]], ptr [[REF_TMP]], align 8
// LLVM-NEXT:    [[TMP2:%.*]] = load i64, ptr [[REF_TMP]], align 8
// LLVM-NEXT:    store i64 [[TMP2]], ptr [[__RET]], align 8
// LLVM-NEXT:    [[TMP3:%.*]] = load i64, ptr [[__RET]], align 8
// LLVM-NEXT:    store i64 [[TMP3]], ptr [[TMP]], align 8
// LLVM-NEXT:    [[TMP4:%.*]] = load i64, ptr [[TMP]], align 8
// LLVM-NEXT:    ret i64 [[TMP4]]
//
uint64_t test_vqshld_n_u64(uint64_t a) {
  return vqshld_n_u64(a, 1);
}
