; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -slp-threshold=-100 -mtriple=aarch64-unknown-linux-gnu < %s | FileCheck %s

define ptr @test(ptr %d, i64 %v) {
; CHECK-LABEL: define ptr @test(
; CHECK-SAME: ptr [[D:%.*]], i64 [[V:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[D]], align 1
; CHECK-NEXT:    [[CMP4_2:%.*]] = icmp eq i8 [[TMP0]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = xor i64 0, [[V]]
; CHECK-NEXT:    [[TMP7:%.*]] = select i1 [[CMP4_2]], i64 0, i64 4
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <3 x i64> <i64 poison, i64 poison, i64 1>, i64 [[TMP7]], i32 0
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <3 x i64> [[TMP3]], i64 [[TMP2]], i32 1
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <3 x i64> <i64 1, i64 3, i64 poison>, i64 [[V]], i32 2
; CHECK-NEXT:    [[TMP6:%.*]] = udiv <3 x i64> [[TMP4]], [[TMP5]]
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <3 x i64> [[TMP6]], <3 x i64> poison, <6 x i32> <i32 0, i32 1, i32 0, i32 1, i32 2, i32 2>
; CHECK-NEXT:    [[TMP9:%.*]] = mul <6 x i64> [[TMP8]], <i64 2, i64 6, i64 4, i64 3, i64 5, i64 4>
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <6 x i64> [[TMP9]], i32 0
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[D]], i64 [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = extractelement <6 x i64> [[TMP9]], i32 1
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[D]], i64 [[TMP12]]
; CHECK-NEXT:    [[TMP14:%.*]] = extractelement <6 x i64> [[TMP9]], i32 2
; CHECK-NEXT:    [[SCEVGEP42:%.*]] = getelementptr i8, ptr [[D]], i64 [[TMP14]]
; CHECK-NEXT:    [[TMP15:%.*]] = extractelement <6 x i64> [[TMP9]], i32 3
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr [[D]], i64 [[TMP15]]
; CHECK-NEXT:    [[TMP17:%.*]] = extractelement <6 x i64> [[TMP9]], i32 4
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr i8, ptr [[D]], i64 [[TMP17]]
; CHECK-NEXT:    [[TMP19:%.*]] = extractelement <6 x i64> [[TMP9]], i32 5
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr i8, ptr [[D]], i64 [[TMP19]]
; CHECK-NEXT:    ret ptr [[TMP20]]
;
entry:
  %0 = load i8, ptr %d, align 1
  %cmp4.2 = icmp eq i8 %0, 0
  %1 = select i1 %cmp4.2, i64 0, i64 4
  %2 = shl i64 %1, 1
  %3 = getelementptr i8, ptr %d, i64 %2
  %4 = xor i64 0, %v
  %5 = udiv i64 %4, 3
  %6 = mul i64 %5, 6
  %7 = getelementptr i8, ptr %d, i64 %6
  %8 = shl i64 %1, 2
  %scevgep42 = getelementptr i8, ptr %d, i64 %8
  %9 = mul i64 %5, 3
  %10 = getelementptr i8, ptr %d, i64 %9
  %11 = udiv i64 1, %v
  %12 = mul i64 %11, 5
  %13 = getelementptr i8, ptr %d, i64 %12
  %14 = mul i64 %11, 4
  %15 = getelementptr i8, ptr %d, i64 %14
  ret ptr %15
}
