; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=slp-vectorizer -mtriple=aarch64-unknown-linux-gnu -S | FileCheck %s

define void @single_use_v4(ptr %src0, ptr %src1, ptr %dst) {
; CHECK-LABEL: @single_use_v4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load <4 x float>, ptr [[SRC0:%.*]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x float>, ptr [[SRC1:%.*]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = fmul fast <4 x float> [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = fadd fast <4 x float> [[TMP2]], splat (float 1.000000e+00)
; CHECK-NEXT:    store <4 x float> [[TMP3]], ptr [[DST:%.*]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %s0.0 = load float, ptr %src0, align 4
  %gep.s0.1 = getelementptr inbounds float, ptr %src0, i64 1
  %s0.1 = load float, ptr %gep.s0.1, align 4
  %gep.s0.2 = getelementptr inbounds float, ptr %src0, i64 2
  %s0.2 = load float, ptr %gep.s0.2, align 4
  %gep.s0.3 = getelementptr inbounds float, ptr %src0, i64 3
  %s0.3 = load float, ptr %gep.s0.3, align 4
  %s1.0 = load float, ptr %src1, align 4
  %gep.s1.1 = getelementptr inbounds float, ptr %src1, i64 1
  %s1.1 = load float, ptr %gep.s1.1, align 4
  %gep.s1.2 = getelementptr inbounds float, ptr %src1, i64 2
  %s1.2 = load float, ptr %gep.s1.2, align 4
  %gep.s1.3 = getelementptr inbounds float, ptr %src1, i64 3
  %s1.3 = load float, ptr %gep.s1.3, align 4
  %mul.0 = fmul fast float %s0.0, %s1.0
  %mul.1 = fmul fast float %s0.1, %s1.1
  %mul.2 = fmul fast float %s0.2, %s1.2
  %mul.3 = fmul fast float %s0.3, %s1.3
  %add.0 = fadd fast float %mul.0, 1.0
  %add.1 = fadd fast float %mul.1, 1.0
  %add.2 = fadd fast float %mul.2, 1.0
  %add.3 = fadd fast float %mul.3, 1.0
  store float %add.0, ptr %dst, align 4
  %gep.d.1 = getelementptr inbounds float, ptr %dst, i64 1
  store float %add.1, ptr %gep.d.1, align 4
  %gep.d.2 = getelementptr inbounds float, ptr %dst, i64 2
  store float %add.2, ptr %gep.d.2, align 4
  %gep.d.3 = getelementptr inbounds float, ptr %dst, i64 3
  store float %add.3, ptr %gep.d.3, align 4
  ret void
}

define void @mixed_use_v4(ptr %src0, ptr %src1, ptr %dst, ptr %extra) {
; CHECK-LABEL: @mixed_use_v4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load <4 x float>, ptr [[SRC0:%.*]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x float>, ptr [[SRC1:%.*]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = fmul fast <4 x float> [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = fadd fast <4 x float> [[TMP2]], splat (float 1.000000e+00)
; CHECK-NEXT:    store <4 x float> [[TMP3]], ptr [[DST:%.*]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x float> [[TMP2]], i32 0
; CHECK-NEXT:    store float [[TMP4]], ptr [[EXTRA:%.*]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %s0.0 = load float, ptr %src0, align 4
  %gep.s0.1 = getelementptr inbounds float, ptr %src0, i64 1
  %s0.1 = load float, ptr %gep.s0.1, align 4
  %gep.s0.2 = getelementptr inbounds float, ptr %src0, i64 2
  %s0.2 = load float, ptr %gep.s0.2, align 4
  %gep.s0.3 = getelementptr inbounds float, ptr %src0, i64 3
  %s0.3 = load float, ptr %gep.s0.3, align 4
  %s1.0 = load float, ptr %src1, align 4
  %gep.s1.1 = getelementptr inbounds float, ptr %src1, i64 1
  %s1.1 = load float, ptr %gep.s1.1, align 4
  %gep.s1.2 = getelementptr inbounds float, ptr %src1, i64 2
  %s1.2 = load float, ptr %gep.s1.2, align 4
  %gep.s1.3 = getelementptr inbounds float, ptr %src1, i64 3
  %s1.3 = load float, ptr %gep.s1.3, align 4
  %mul.0 = fmul fast float %s0.0, %s1.0
  %mul.1 = fmul fast float %s0.1, %s1.1
  %mul.2 = fmul fast float %s0.2, %s1.2
  %mul.3 = fmul fast float %s0.3, %s1.3
  %add.0 = fadd fast float %mul.0, 1.0
  %add.1 = fadd fast float %mul.1, 1.0
  %add.2 = fadd fast float %mul.2, 1.0
  %add.3 = fadd fast float %mul.3, 1.0
  store float %add.0, ptr %dst, align 4
  %gep.d.1 = getelementptr inbounds float, ptr %dst, i64 1
  store float %add.1, ptr %gep.d.1, align 4
  %gep.d.2 = getelementptr inbounds float, ptr %dst, i64 2
  store float %add.2, ptr %gep.d.2, align 4
  %gep.d.3 = getelementptr inbounds float, ptr %dst, i64 3
  store float %add.3, ptr %gep.d.3, align 4
  ; mul.0 has an extra use, preventing FMulAdd
  store float %mul.0, ptr %extra, align 4
  ret void
}

; 4-wide: all fmuls have multiple uses.
; FMulAdd should NOT be applied.
define void @all_multi_use_v4(ptr %src0, ptr %src1, ptr %dst, ptr %extra) {
; CHECK-LABEL: @all_multi_use_v4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load <4 x float>, ptr [[SRC0:%.*]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x float>, ptr [[SRC1:%.*]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = fmul fast <4 x float> [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = fadd fast <4 x float> [[TMP2]], splat (float 1.000000e+00)
; CHECK-NEXT:    store <4 x float> [[TMP3]], ptr [[DST:%.*]], align 4
; CHECK-NEXT:    store <4 x float> [[TMP2]], ptr [[EXTRA:%.*]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %s0.0 = load float, ptr %src0, align 4
  %gep.s0.1 = getelementptr inbounds float, ptr %src0, i64 1
  %s0.1 = load float, ptr %gep.s0.1, align 4
  %gep.s0.2 = getelementptr inbounds float, ptr %src0, i64 2
  %s0.2 = load float, ptr %gep.s0.2, align 4
  %gep.s0.3 = getelementptr inbounds float, ptr %src0, i64 3
  %s0.3 = load float, ptr %gep.s0.3, align 4
  %s1.0 = load float, ptr %src1, align 4
  %gep.s1.1 = getelementptr inbounds float, ptr %src1, i64 1
  %s1.1 = load float, ptr %gep.s1.1, align 4
  %gep.s1.2 = getelementptr inbounds float, ptr %src1, i64 2
  %s1.2 = load float, ptr %gep.s1.2, align 4
  %gep.s1.3 = getelementptr inbounds float, ptr %src1, i64 3
  %s1.3 = load float, ptr %gep.s1.3, align 4
  %mul.0 = fmul fast float %s0.0, %s1.0
  %mul.1 = fmul fast float %s0.1, %s1.1
  %mul.2 = fmul fast float %s0.2, %s1.2
  %mul.3 = fmul fast float %s0.3, %s1.3
  %add.0 = fadd fast float %mul.0, 1.0
  %add.1 = fadd fast float %mul.1, 1.0
  %add.2 = fadd fast float %mul.2, 1.0
  %add.3 = fadd fast float %mul.3, 1.0
  store float %add.0, ptr %dst, align 4
  %gep.d.1 = getelementptr inbounds float, ptr %dst, i64 1
  store float %add.1, ptr %gep.d.1, align 4
  %gep.d.2 = getelementptr inbounds float, ptr %dst, i64 2
  store float %add.2, ptr %gep.d.2, align 4
  %gep.d.3 = getelementptr inbounds float, ptr %dst, i64 3
  store float %add.3, ptr %gep.d.3, align 4
  store float %mul.0, ptr %extra, align 4
  %gep.e.1 = getelementptr inbounds float, ptr %extra, i64 1
  store float %mul.1, ptr %gep.e.1, align 4
  %gep.e.2 = getelementptr inbounds float, ptr %extra, i64 2
  store float %mul.2, ptr %gep.e.2, align 4
  %gep.e.3 = getelementptr inbounds float, ptr %extra, i64 3
  store float %mul.3, ptr %gep.e.3, align 4
  ret void
}
