; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=slp-vectorizer -mtriple=aarch64-unknown-linux-gnu -mcpu=neoverse-512tvb < %s | FileCheck %s

define void @gather_load_fp128(ptr %arg) #0 {
; CHECK-LABEL: @gather_load_fp128(
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[ARG:%.*]], i64 16
; CHECK-NEXT:    [[LOAD0:%.*]] = load fp128, ptr [[ARG]], align 1
; CHECK-NEXT:    [[LOAD1:%.*]] = load fp128, ptr [[GEP]], align 1
; CHECK-NEXT:    [[LOAD2:%.*]] = load fp128, ptr null, align 1
; CHECK-NEXT:    [[LOAD3:%.*]] = load fp128, ptr null, align 1
; CHECK-NEXT:    [[FCMP0:%.*]] = fcmp oeq fp128 [[LOAD0]], 0xL00000000000000000000000000000000
; CHECK-NEXT:    [[FCMP1:%.*]] = fcmp oeq fp128 [[LOAD1]], 0xL00000000000000000000000000000000
; CHECK-NEXT:    [[FCMP2:%.*]] = fcmp oeq fp128 [[LOAD2]], 0xL00000000000000000000000000000000
; CHECK-NEXT:    [[FCMP3:%.*]] = fcmp oeq fp128 [[LOAD3]], 0xL00000000000000000000000000000000
; CHECK-NEXT:    ret void
;
  %gep = getelementptr i8, ptr %arg, i64 16
  %load0 = load fp128, ptr %arg, align 1
  %load1 = load fp128, ptr %gep, align 1
  %load2 = load fp128, ptr null, align 1
  %load3 = load fp128, ptr null, align 1
  %fcmp0 = fcmp oeq fp128 %load0, 0xL0
  %fcmp1 = fcmp oeq fp128 %load1, 0xL0
  %fcmp2 = fcmp oeq fp128 %load2, 0xL0
  %fcmp3 = fcmp oeq fp128 %load3, 0xL0
  ret void
}

define void @gather_load_i128(ptr %arg) #0 {
; CHECK-LABEL: @gather_load_i128(
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[ARG:%.*]], i64 16
; CHECK-NEXT:    [[LOAD0:%.*]] = load i128, ptr [[ARG]], align 1
; CHECK-NEXT:    [[LOAD1:%.*]] = load i128, ptr [[GEP]], align 1
; CHECK-NEXT:    [[LOAD2:%.*]] = load i128, ptr null, align 1
; CHECK-NEXT:    [[LOAD3:%.*]] = load i128, ptr null, align 1
; CHECK-NEXT:    [[CMP0:%.*]] = icmp eq i128 [[LOAD0]], 0
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i128 [[LOAD1]], 0
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i128 [[LOAD2]], 0
; CHECK-NEXT:    [[CMP3:%.*]] = icmp eq i128 [[LOAD3]], 0
; CHECK-NEXT:    ret void
;
  %gep = getelementptr i8, ptr %arg, i64 16
  %load0 = load i128, ptr %arg, align 1
  %load1 = load i128, ptr %gep, align 1
  %load2 = load i128, ptr null, align 1
  %load3 = load i128, ptr null, align 1
  %cmp0 = icmp eq i128 %load0, 0
  %cmp1 = icmp eq i128 %load1, 0
  %cmp2 = icmp eq i128 %load2, 0
  %cmp3 = icmp eq i128 %load3, 0
  ret void
}

attributes #0 = { vscale_range(2,2) }
