; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=arm64-apple-macosx15.0.0 < %s | FileCheck %s

define i1 @test(ptr %arg, ptr %arg1, i64 %arg2, ptr %arg3) {
; CHECK-LABEL: define i1 @test(
; CHECK-SAME: ptr [[ARG:%.*]], ptr [[ARG1:%.*]], i64 [[ARG2:%.*]], ptr [[ARG3:%.*]]) {
; CHECK-NEXT:  [[BB:.*:]]
; CHECK-NEXT:    [[GETELEMENTPTR:%.*]] = getelementptr i8, ptr [[ARG1]], i64 [[ARG2]]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x ptr> <ptr poison, ptr null>, ptr [[ARG1]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, <2 x ptr> [[TMP0]], <2 x i64> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <8 x ptr> <ptr poison, ptr null, ptr poison, ptr poison, ptr poison, ptr poison, ptr poison, ptr poison>, ptr [[ARG3]], i32 0
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x ptr> [[TMP2]], <8 x ptr> poison, <8 x i32> <i32 0, i32 0, i32 0, i32 0, i32 1, i32 0, i32 0, i32 0>
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, <8 x ptr> [[TMP3]], <8 x i64> <i64 -440, i64 -440, i64 -440, i64 -440, i64 -32, i64 -440, i64 -440, i64 -440>
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x ptr> <ptr null, ptr poison>, ptr [[ARG3]], i32 1
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, <2 x ptr> [[TMP5]], <2 x i64> <i64 -32, i64 -432>
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <2 x ptr> [[TMP6]], <2 x ptr> poison, <4 x i32> <i32 0, i32 1, i32 1, i32 1>
; CHECK-NEXT:    [[GETELEMENTPTR7:%.*]] = getelementptr i8, ptr [[ARG1]], i64 0
; CHECK-NEXT:    [[GETELEMENTPTR8:%.*]] = getelementptr i8, ptr [[ARG3]], i64 -432
; CHECK-NEXT:    [[ICMP:%.*]] = icmp ult ptr null, [[GETELEMENTPTR8]]
; CHECK-NEXT:    [[AND:%.*]] = and i1 false, [[ICMP]]
; CHECK-NEXT:    [[ICMP9:%.*]] = icmp ult ptr [[GETELEMENTPTR7]], null
; CHECK-NEXT:    [[AND10:%.*]] = and i1 [[ICMP9]], false
; CHECK-NEXT:    [[ICMP17:%.*]] = icmp ult ptr null, null
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x ptr> [[TMP1]], <2 x ptr> poison, <8 x i32> <i32 0, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x ptr> <ptr poison, ptr poison, ptr null, ptr null, ptr null, ptr null, ptr null, ptr null>, <8 x ptr> [[TMP8]], <8 x i32> <i32 8, i32 9, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x ptr> [[TMP7]], <4 x ptr> poison, <8 x i32> <i32 poison, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <2 x ptr> [[TMP6]], <2 x ptr> poison, <8 x i32> <i32 0, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <8 x ptr> <ptr null, ptr poison, ptr poison, ptr poison, ptr poison, ptr poison, ptr poison, ptr poison>, <8 x ptr> [[TMP11]], <8 x i32> <i32 0, i32 9, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <8 x ptr> [[TMP12]], <8 x ptr> poison, <8 x i32> <i32 0, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1>
; CHECK-NEXT:    [[TMP14:%.*]] = icmp ult <8 x ptr> [[TMP9]], [[TMP13]]
; CHECK-NEXT:    [[TMP15:%.*]] = insertelement <8 x i1> <i1 false, i1 false, i1 poison, i1 false, i1 false, i1 false, i1 false, i1 false>, i1 [[ICMP17]], i32 2
; CHECK-NEXT:    [[TMP16:%.*]] = and <8 x i1> [[TMP14]], [[TMP15]]
; CHECK-NEXT:    [[ICMP36:%.*]] = icmp ult ptr null, [[GETELEMENTPTR8]]
; CHECK-NEXT:    [[AND37:%.*]] = and i1 false, [[ICMP36]]
; CHECK-NEXT:    [[TMP17:%.*]] = insertelement <4 x ptr> <ptr poison, ptr poison, ptr null, ptr null>, ptr [[ARG]], i32 1
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <2 x ptr> [[TMP1]], <2 x ptr> poison, <4 x i32> <i32 0, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <4 x ptr> [[TMP17]], <4 x ptr> [[TMP18]], <4 x i32> <i32 4, i32 1, i32 2, i32 3>
; CHECK-NEXT:    [[TMP20:%.*]] = icmp ult <4 x ptr> [[TMP19]], [[TMP7]]
; CHECK-NEXT:    [[TMP21:%.*]] = and <4 x i1> zeroinitializer, [[TMP20]]
; CHECK-NEXT:    [[ICMP58:%.*]] = icmp ult ptr [[GETELEMENTPTR]], null
; CHECK-NEXT:    [[TMP22:%.*]] = insertelement <2 x ptr> <ptr poison, ptr null>, ptr [[GETELEMENTPTR]], i32 0
; CHECK-NEXT:    [[TMP23:%.*]] = icmp ult <2 x ptr> [[TMP22]], splat (ptr null)
; CHECK-NEXT:    [[TMP24:%.*]] = insertelement <8 x ptr> <ptr null, ptr null, ptr null, ptr null, ptr poison, ptr poison, ptr null, ptr null>, ptr [[ARG]], i32 4
; CHECK-NEXT:    [[TMP25:%.*]] = insertelement <8 x ptr> [[TMP24]], ptr [[ARG1]], i32 5
; CHECK-NEXT:    [[TMP26:%.*]] = icmp ult <8 x ptr> [[TMP25]], [[TMP4]]
; CHECK-NEXT:    [[TMP27:%.*]] = insertelement <8 x i1> <i1 false, i1 poison, i1 poison, i1 poison, i1 poison, i1 poison, i1 false, i1 false>, i1 [[ICMP58]], i32 1
; CHECK-NEXT:    [[TMP28:%.*]] = shufflevector <2 x i1> [[TMP23]], <2 x i1> poison, <8 x i32> <i32 0, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP29:%.*]] = shufflevector <8 x i1> [[TMP27]], <8 x i1> [[TMP28]], <8 x i32> <i32 0, i32 1, i32 8, i32 9, i32 poison, i32 poison, i32 6, i32 7>
; CHECK-NEXT:    [[TMP30:%.*]] = shufflevector <8 x i1> [[TMP29]], <8 x i1> <i1 false, i1 false, i1 undef, i1 undef, i1 undef, i1 undef, i1 undef, i1 undef>, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 6, i32 7>
; CHECK-NEXT:    [[TMP31:%.*]] = and <8 x i1> [[TMP30]], [[TMP26]]
; CHECK-NEXT:    [[TMP32:%.*]] = extractelement <8 x ptr> [[TMP4]], i32 0
; CHECK-NEXT:    [[ICMP84:%.*]] = icmp ult ptr null, [[TMP32]]
; CHECK-NEXT:    [[AND85:%.*]] = and i1 false, [[ICMP84]]
; CHECK-NEXT:    [[TMP33:%.*]] = call i1 @llvm.vector.reduce.or.v8i1(<8 x i1> [[TMP31]])
; CHECK-NEXT:    [[TMP34:%.*]] = shufflevector <8 x i1> [[TMP16]], <8 x i1> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    [[RDX_OP:%.*]] = or <4 x i1> [[TMP34]], [[TMP21]]
; CHECK-NEXT:    [[TMP35:%.*]] = shufflevector <4 x i1> [[RDX_OP]], <4 x i1> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP36:%.*]] = shufflevector <8 x i1> [[TMP16]], <8 x i1> [[TMP35]], <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP37:%.*]] = call i1 @llvm.vector.reduce.or.v8i1(<8 x i1> [[TMP36]])
; CHECK-NEXT:    [[OP_RDX16:%.*]] = or i1 [[TMP37]], [[AND]]
; CHECK-NEXT:    [[OP_RDX17:%.*]] = or i1 [[AND10]], [[AND37]]
; CHECK-NEXT:    [[OP_RDX18:%.*]] = or i1 [[AND85]], [[TMP33]]
; CHECK-NEXT:    [[OP_RDX19:%.*]] = or i1 [[OP_RDX16]], [[OP_RDX17]]
; CHECK-NEXT:    [[OP_RDX20:%.*]] = or i1 [[OP_RDX19]], [[OP_RDX18]]
; CHECK-NEXT:    ret i1 [[OP_RDX20]]
;
bb:
  %getelementptr = getelementptr i8, ptr %arg1, i64 %arg2
  %getelementptr4 = getelementptr i8, ptr null, i64 0
  %getelementptr5 = getelementptr i8, ptr null, i64 -32
  %getelementptr6 = getelementptr i8, ptr %arg3, i64 -440
  %getelementptr7 = getelementptr i8, ptr %arg1, i64 0
  %getelementptr8 = getelementptr i8, ptr %arg3, i64 -432
  %icmp = icmp ult ptr null, %getelementptr8
  %and = and i1 false, %icmp
  %icmp9 = icmp ult ptr %getelementptr7, null
  %and10 = and i1 %icmp9, false
  %or = or i1 %and, %and10
  %icmp11 = icmp ult ptr %getelementptr7, null
  %and12 = and i1 %icmp11, false
  %or13 = or i1 %or, %and12
  %icmp14 = icmp ult ptr %getelementptr4, %getelementptr8
  %and15 = and i1 false, %icmp14
  %or16 = or i1 %or13, %and15
  %icmp17 = icmp ult ptr null, null
  %icmp18 = icmp ult ptr null, %getelementptr8
  %and19 = and i1 %icmp17, %icmp18
  %or20 = or i1 %or16, %and19
  %icmp21 = icmp ult ptr null, %getelementptr8
  %and22 = and i1 false, %icmp21
  %or23 = or i1 %or20, %and22
  %icmp24 = icmp ult ptr null, %getelementptr8
  %and25 = and i1 false, %icmp24
  %or26 = or i1 %or23, %and25
  %icmp27 = icmp ult ptr null, %getelementptr8
  %and28 = and i1 false, %icmp27
  %or29 = or i1 %or26, %and28
  %icmp30 = icmp ult ptr null, %getelementptr8
  %and31 = and i1 false, %icmp30
  %or32 = or i1 %or29, %and31
  %icmp33 = icmp ult ptr null, %getelementptr8
  %and34 = and i1 false, %icmp33
  %or35 = or i1 %or32, %and34
  %icmp36 = icmp ult ptr null, %getelementptr8
  %and37 = and i1 false, %icmp36
  %or38 = or i1 %or35, %and37
  %icmp39 = icmp ult ptr %getelementptr7, %getelementptr5
  %icmp40 = icmp ult ptr null, null
  %and41 = and i1 %icmp39, %icmp40
  %or42 = or i1 %or38, %and41
  %icmp43 = icmp ult ptr null, null
  %icmp44 = icmp ult ptr %arg, %getelementptr8
  %and45 = and i1 %icmp43, %icmp44
  %or46 = or i1 %or42, %and45
  %icmp47 = icmp ult ptr null, null
  %icmp48 = icmp ult ptr null, %getelementptr8
  %and49 = and i1 %icmp47, %icmp48
  %or50 = or i1 %or46, %and49
  %icmp51 = icmp ult ptr null, null
  %icmp52 = icmp ult ptr null, %getelementptr8
  %and53 = and i1 %icmp51, %icmp52
  %or54 = or i1 %or50, %and53
  %icmp55 = icmp ult ptr null, %getelementptr6
  %and56 = and i1 false, %icmp55
  %or57 = or i1 %or54, %and56
  %icmp58 = icmp ult ptr %getelementptr, null
  %icmp59 = icmp ult ptr null, %getelementptr6
  %and60 = and i1 %icmp58, %icmp59
  %or61 = or i1 %or57, %and60
  %icmp62 = icmp ult ptr %getelementptr, null
  %icmp63 = icmp ult ptr null, %getelementptr6
  %and64 = and i1 %icmp62, %icmp63
  %or65 = or i1 %or61, %and64
  %icmp66 = icmp ult ptr null, null
  %icmp67 = icmp ult ptr null, %getelementptr6
  %and68 = and i1 %icmp66, %icmp67
  %or69 = or i1 %or65, %and68
  %icmp70 = icmp ult ptr %arg, %getelementptr5
  %icmp71 = icmp ult ptr null, null
  %and72 = and i1 %icmp70, %icmp71
  %or73 = or i1 %or69, %and72
  %icmp74 = icmp ult ptr null, null
  %icmp75 = icmp ult ptr %arg1, %getelementptr6
  %and76 = and i1 %icmp74, %icmp75
  %or77 = or i1 %or73, %and76
  %icmp78 = icmp ult ptr null, %getelementptr6
  %and79 = and i1 false, %icmp78
  %or80 = or i1 %or77, %and79
  %icmp81 = icmp ult ptr null, %getelementptr6
  %and82 = and i1 false, %icmp81
  %or83 = or i1 %or80, %and82
  %icmp84 = icmp ult ptr null, %getelementptr6
  %and85 = and i1 false, %icmp84
  %or86 = or i1 %or83, %and85
  ret i1 %or86
}
