; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=arm64-apple-macosx15.0.0 < %s | FileCheck %s

define i1 @test(ptr %arg, ptr %arg1, i1 %arg2, i1 %arg3, i1 %arg4) {
; CHECK-LABEL: define i1 @test(
; CHECK-SAME: ptr [[ARG:%.*]], ptr [[ARG1:%.*]], i1 [[ARG2:%.*]], i1 [[ARG3:%.*]], i1 [[ARG4:%.*]]) {
; CHECK-NEXT:  [[BB:.*:]]
; CHECK-NEXT:    [[GETELEMENTPTR:%.*]] = getelementptr i8, ptr [[ARG1]], i64 3684
; CHECK-NEXT:    [[GETELEMENTPTR5:%.*]] = getelementptr i8, ptr [[ARG]], i64 21
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <8 x ptr> poison, ptr [[ARG1]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x ptr> [[TMP0]], <8 x ptr> poison, <8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, <8 x ptr> [[TMP1]], <8 x i64> <i64 8484, i64 8484, i64 8484, i64 5284, i64 8484, i64 8484, i64 8484, i64 8484>
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <8 x ptr> [[TMP2]], i32 0
; CHECK-NEXT:    [[ICMP:%.*]] = icmp ult ptr [[TMP3]], null
; CHECK-NEXT:    [[ICMP7:%.*]] = icmp ult ptr null, null
; CHECK-NEXT:    [[AND:%.*]] = and i1 false, [[ICMP7]]
; CHECK-NEXT:    [[ICMP11:%.*]] = icmp ult ptr null, null
; CHECK-NEXT:    [[AND12:%.*]] = and i1 false, [[ICMP11]]
; CHECK-NEXT:    [[ICMP14:%.*]] = icmp ult ptr null, null
; CHECK-NEXT:    [[AND15:%.*]] = and i1 false, [[ICMP14]]
; CHECK-NEXT:    [[TMP4:%.*]] = icmp ult <8 x ptr> [[TMP2]], splat (ptr null)
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <8 x i1> <i1 false, i1 poison, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false>, i1 [[ARG2]], i32 1
; CHECK-NEXT:    [[TMP6:%.*]] = and <8 x i1> [[TMP4]], [[TMP5]]
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <8 x ptr> [[TMP2]], i32 3
; CHECK-NEXT:    [[ICMP46:%.*]] = icmp ult ptr [[TMP7]], null
; CHECK-NEXT:    [[AND47:%.*]] = and i1 false, [[ICMP46]]
; CHECK-NEXT:    [[ICMP49:%.*]] = icmp ult ptr [[ARG]], null
; CHECK-NEXT:    [[AND50:%.*]] = and i1 [[ICMP49]], false
; CHECK-NEXT:    [[ICMP52:%.*]] = icmp ult ptr [[ARG1]], null
; CHECK-NEXT:    [[AND53:%.*]] = and i1 [[ICMP52]], false
; CHECK-NEXT:    [[ICMP55:%.*]] = icmp ult ptr [[ARG]], null
; CHECK-NEXT:    [[AND56:%.*]] = and i1 false, [[ICMP55]]
; CHECK-NEXT:    [[ICMP58:%.*]] = icmp ult ptr [[ARG]], null
; CHECK-NEXT:    [[AND59:%.*]] = and i1 false, [[ICMP58]]
; CHECK-NEXT:    [[ICMP62:%.*]] = icmp ult ptr [[GETELEMENTPTR5]], null
; CHECK-NEXT:    [[AND63:%.*]] = and i1 [[ARG2]], [[ICMP62]]
; CHECK-NEXT:    [[ICMP65:%.*]] = icmp ult ptr [[GETELEMENTPTR]], null
; CHECK-NEXT:    [[AND66:%.*]] = and i1 [[ICMP65]], false
; CHECK-NEXT:    [[TMP8:%.*]] = call i1 @llvm.vector.reduce.or.v8i1(<8 x i1> [[TMP6]])
; CHECK-NEXT:    [[OP_RDX24:%.*]] = or i1 [[TMP8]], [[AND]]
; CHECK-NEXT:    [[OP_RDX25:%.*]] = or i1 false, [[AND12]]
; CHECK-NEXT:    [[OP_RDX26:%.*]] = or i1 [[AND15]], false
; CHECK-NEXT:    [[OP_RDX27:%.*]] = or i1 false, [[AND47]]
; CHECK-NEXT:    [[OP_RDX28:%.*]] = or i1 [[AND50]], [[AND53]]
; CHECK-NEXT:    [[OP_RDX29:%.*]] = or i1 [[AND56]], [[AND59]]
; CHECK-NEXT:    [[OP_RDX30:%.*]] = or i1 [[AND63]], [[AND66]]
; CHECK-NEXT:    [[OP_RDX31:%.*]] = or i1 [[ARG3]], [[ARG2]]
; CHECK-NEXT:    [[OP_RDX32:%.*]] = or i1 [[ARG4]], false
; CHECK-NEXT:    [[OP_RDX33:%.*]] = or i1 [[OP_RDX24]], [[OP_RDX25]]
; CHECK-NEXT:    [[OP_RDX34:%.*]] = or i1 [[OP_RDX26]], [[OP_RDX27]]
; CHECK-NEXT:    [[OP_RDX35:%.*]] = or i1 [[OP_RDX28]], [[OP_RDX29]]
; CHECK-NEXT:    [[OP_RDX36:%.*]] = or i1 [[OP_RDX30]], [[OP_RDX31]]
; CHECK-NEXT:    [[OP_RDX37:%.*]] = or i1 [[OP_RDX33]], [[OP_RDX34]]
; CHECK-NEXT:    [[OP_RDX38:%.*]] = or i1 [[OP_RDX35]], [[OP_RDX36]]
; CHECK-NEXT:    [[OP_RDX39:%.*]] = or i1 [[OP_RDX37]], [[OP_RDX38]]
; CHECK-NEXT:    [[OP_RDX40:%.*]] = or i1 [[OP_RDX39]], [[OP_RDX32]]
; CHECK-NEXT:    ret i1 [[OP_RDX40]]
;
bb:
  %getelementptr = getelementptr i8, ptr %arg1, i64 3684
  %getelementptr5 = getelementptr i8, ptr %arg, i64 21
  %getelementptr6 = getelementptr i8, ptr %arg1, i64 8484
  %icmp = icmp ult ptr %getelementptr6, null
  %icmp7 = icmp ult ptr null, null
  %and = and i1 false, %icmp7
  %or = or i1 false, %and
  %and8 = and i1 false, false
  %or9 = or i1 %or, %and8
  %or10 = or i1 %or9, false
  %icmp11 = icmp ult ptr null, null
  %and12 = and i1 false, %icmp11
  %or13 = or i1 %or10, %and12
  %icmp14 = icmp ult ptr null, null
  %and15 = and i1 false, %icmp14
  %or16 = or i1 %or13, %and15
  %and17 = and i1 false, false
  %icmp19 = icmp ult ptr %getelementptr6, null
  %getelementptr22 = getelementptr i8, ptr %arg1, i64 5284
  %or18 = or i1 %or16, %and17
  %and20 = and i1 %icmp19, false
  %or23 = or i1 %or18, %and20
  %icmp21 = icmp ult ptr %getelementptr6, null
  %and24 = and i1 %icmp21, %arg2
  %or25 = or i1 %or23, %and24
  %icmp26 = icmp ult ptr %getelementptr6, null
  %and27 = and i1 %icmp26, false
  %or28 = or i1 %or25, %and27
  %icmp29 = icmp ult ptr %getelementptr22, null
  %and30 = and i1 false, %icmp29
  %or31 = or i1 %or28, %and30
  %icmp32 = icmp ult ptr %getelementptr6, null
  %and33 = and i1 %icmp32, false
  %or34 = or i1 %or31, %and33
  %icmp35 = icmp ult ptr %getelementptr6, null
  %and36 = and i1 %icmp35, false
  %or37 = or i1 %or34, %and36
  %icmp38 = icmp ult ptr %getelementptr6, null
  %and39 = and i1 %icmp38, false
  %or40 = or i1 %or37, %and39
  %icmp41 = icmp ult ptr %getelementptr6, null
  %and42 = and i1 %icmp41, false
  %or43 = or i1 %or40, %and42
  %and44 = and i1 false, false
  %or45 = or i1 %or43, %and44
  %icmp46 = icmp ult ptr %getelementptr22, null
  %and47 = and i1 false, %icmp46
  %or48 = or i1 %or45, %and47
  %icmp49 = icmp ult ptr %arg, null
  %and50 = and i1 %icmp49, false
  %or51 = or i1 %or48, %and50
  %icmp52 = icmp ult ptr %arg1, null
  %and53 = and i1 %icmp52, false
  %or54 = or i1 %or51, %and53
  %icmp55 = icmp ult ptr %arg, null
  %and56 = and i1 false, %icmp55
  %or57 = or i1 %or54, %and56
  %icmp58 = icmp ult ptr %arg, null
  %and59 = and i1 false, %icmp58
  %or60 = or i1 %or57, %and59
  %or61 = or i1 %or60, %arg3
  %icmp62 = icmp ult ptr %getelementptr5, null
  %and63 = and i1 %arg2, %icmp62
  %or64 = or i1 %or61, %and63
  %icmp65 = icmp ult ptr %getelementptr, null
  %and66 = and i1 %icmp65, false
  %or67 = or i1 %or64, %and66
  %or68 = or i1 %or67, %arg2
  %or69 = or i1 %or68, %arg4
  ret i1 %or69
}
