; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=aarch64-unknown-linux-gnu < %s | FileCheck %s

define double @test(ptr %0, double %1) {
; CHECK-LABEL: define double @test(
; CHECK-SAME: ptr [[TMP0:%.*]], double [[TMP1:%.*]]) {
; CHECK-NEXT:  [[_LR_PH:.*:]]
; CHECK-NEXT:    [[TMP2:%.*]] = load double, ptr null, align 8
; CHECK-NEXT:    [[TMP3:%.*]] = fsub double 0.000000e+00, [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = fmul double [[TMP3]], 0.000000e+00
; CHECK-NEXT:    store double [[TMP4]], ptr null, align 8
; CHECK-NEXT:    [[TMP5:%.*]] = fmul double 0.000000e+00, 0.000000e+00
; CHECK-NEXT:    [[TMP6:%.*]] = fmul double [[TMP3]], 0.000000e+00
; CHECK-NEXT:    [[TMP7:%.*]] = fmul double [[TMP6]], [[TMP1]]
; CHECK-NEXT:    store double [[TMP7]], ptr null, align 8
; CHECK-NEXT:    [[TMP8:%.*]] = fadd double [[TMP1]], 0.000000e+00
; CHECK-NEXT:    [[TMP9:%.*]] = fmul double [[TMP8]], 0.000000e+00
; CHECK-NEXT:    store double [[TMP9]], ptr null, align 8
; CHECK-NEXT:    [[TMP10:%.*]] = fmul double [[TMP6]], 0.000000e+00
; CHECK-NEXT:    [[TMP11:%.*]] = fadd double 0.000000e+00, 0.000000e+00
; CHECK-NEXT:    [[TMP12:%.*]] = fmul double [[TMP11]], [[TMP1]]
; CHECK-NEXT:    store double [[TMP12]], ptr null, align 8
; CHECK-NEXT:    [[TMP13:%.*]] = fmul double [[TMP11]], 0.000000e+00
; CHECK-NEXT:    br label %[[SCALAR_PH:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[TMP14:%.*]] = fmul double 0.000000e+00, [[TMP4]]
; CHECK-NEXT:    [[TMP15:%.*]] = fmul double [[TMP7]], 0.000000e+00
; CHECK-NEXT:    [[TMP16:%.*]] = fadd double [[TMP15]], [[TMP4]]
; CHECK-NEXT:    [[TMP17:%.*]] = fmul double [[TMP10]], 0.000000e+00
; CHECK-NEXT:    [[TMP18:%.*]] = fadd double [[TMP16]], [[TMP17]]
; CHECK-NEXT:    [[TMP19:%.*]] = fmul double [[TMP12]], 0.000000e+00
; CHECK-NEXT:    [[TMP20:%.*]] = fadd double [[TMP19]], 0.000000e+00
; CHECK-NEXT:    [[TMP21:%.*]] = fmul double [[TMP13]], 0.000000e+00
; CHECK-NEXT:    [[TMP22:%.*]] = fadd double [[TMP20]], [[TMP21]]
; CHECK-NEXT:    [[TMP23:%.*]] = fadd double [[TMP22]], 0.000000e+00
; CHECK-NEXT:    [[TMP24:%.*]] = fmul double [[TMP23]], 0.000000e+00
; CHECK-NEXT:    [[TMP25:%.*]] = fadd double [[TMP18]], 0.000000e+00
; CHECK-NEXT:    [[TMP26:%.*]] = fmul double [[TMP25]], 0.000000e+00
; CHECK-NEXT:    [[TMP27:%.*]] = fsub double [[TMP24]], [[TMP26]]
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr i8, ptr [[TMP0]], i64 24
; CHECK-NEXT:    store double [[TMP27]], ptr [[TMP28]], align 8
; CHECK-NEXT:    [[TMP29:%.*]] = fmul double [[TMP5]], 0.000000e+00
; CHECK-NEXT:    [[TMP30:%.*]] = fadd double [[TMP29]], 0.000000e+00
; CHECK-NEXT:    [[TMP31:%.*]] = fmul double [[TMP9]], 0.000000e+00
; CHECK-NEXT:    [[TMP32:%.*]] = fadd double [[TMP30]], [[TMP31]]
; CHECK-NEXT:    [[TMP33:%.*]] = fadd double [[TMP32]], 0.000000e+00
; CHECK-NEXT:    [[TMP34:%.*]] = fsub double [[TMP25]], [[TMP33]]
; CHECK-NEXT:    [[TMP35:%.*]] = getelementptr i8, ptr [[TMP0]], i64 32
; CHECK-NEXT:    store double [[TMP34]], ptr [[TMP35]], align 8
; CHECK-NEXT:    [[TMP36:%.*]] = fmul double [[TMP33]], 0.000000e+00
; CHECK-NEXT:    [[TMP37:%.*]] = fsub double [[TMP36]], [[TMP23]]
; CHECK-NEXT:    [[TMP38:%.*]] = getelementptr i8, ptr [[TMP0]], i64 40
; CHECK-NEXT:    store double [[TMP37]], ptr [[TMP38]], align 8
; CHECK-NEXT:    [[TMP39:%.*]] = fmul double [[TMP7]], 0.000000e+00
; CHECK-NEXT:    [[TMP40:%.*]] = fadd double [[TMP39]], [[TMP1]]
; CHECK-NEXT:    [[TMP41:%.*]] = fadd double [[TMP40]], [[TMP10]]
; CHECK-NEXT:    [[TMP42:%.*]] = fadd double [[TMP41]], 0.000000e+00
; CHECK-NEXT:    [[TMP43:%.*]] = fadd double [[TMP14]], 0.000000e+00
; CHECK-NEXT:    [[TMP44:%.*]] = fmul double [[TMP43]], 0.000000e+00
; CHECK-NEXT:    [[TMP45:%.*]] = fsub double [[TMP42]], [[TMP44]]
; CHECK-NEXT:    [[TMP46:%.*]] = getelementptr i8, ptr [[TMP0]], i64 48
; CHECK-NEXT:    store double [[TMP45]], ptr [[TMP46]], align 8
; CHECK-NEXT:    ret double 0.000000e+00
;
.lr.ph:
  %2 = load double, ptr null, align 8
  %3 = fsub double 0.000000e+00, %2
  %4 = fmul double %3, 0.000000e+00
  store double %4, ptr null, align 8
  %5 = fmul double 0.000000e+00, 0.000000e+00
  %6 = fmul double %3, 0.000000e+00
  %7 = fmul double %6, %1
  store double %7, ptr null, align 8
  %8 = fadd double %1, 0.000000e+00
  %9 = fmul double %8, 0.000000e+00
  store double %9, ptr null, align 8
  %10 = fmul double %6, 0.000000e+00
  %11 = fadd double 0.000000e+00, 0.000000e+00
  %12 = fmul double %11, %1
  store double %12, ptr null, align 8
  %13 = fmul double %11, 0.000000e+00
  br label %scalar.ph

scalar.ph:
  %14 = fmul double 0.000000e+00, %4
  %15 = fmul double %7, 0.000000e+00
  %16 = fadd double %15, %4
  %17 = fmul double %10, 0.000000e+00
  %18 = fadd double %16, %17
  %19 = fmul double %12, 0.000000e+00
  %20 = fadd double %19, 0.000000e+00
  %21 = fmul double %13, 0.000000e+00
  %22 = fadd double %20, %21
  %23 = fadd double %22, 0.000000e+00
  %24 = fmul double %23, 0.000000e+00
  %25 = fadd double %18, 0.000000e+00
  %26 = fmul double %25, 0.000000e+00
  %27 = fsub double %24, %26
  %28 = getelementptr i8, ptr %0, i64 24
  store double %27, ptr %28, align 8
  %29 = fmul double %5, 0.000000e+00
  %30 = fadd double %29, 0.000000e+00
  %31 = fmul double %9, 0.000000e+00
  %32 = fadd double %30, %31
  %33 = fadd double %32, 0.000000e+00
  %34 = fsub double %25, %33
  %35 = getelementptr i8, ptr %0, i64 32
  store double %34, ptr %35, align 8
  %36 = fmul double %33, 0.000000e+00
  %37 = fsub double %36, %23
  %38 = getelementptr i8, ptr %0, i64 40
  store double %37, ptr %38, align 8
  %39 = fmul double %7, 0.000000e+00
  %40 = fadd double %39, %1
  %41 = fadd double %40, %10
  %42 = fadd double %41, 0.000000e+00
  %43 = fadd double %14, 0.000000e+00
  %44 = fmul double %43, 0.000000e+00
  %45 = fsub double %42, %44
  %46 = getelementptr i8, ptr %0, i64 48
  store double %45, ptr %46, align 8
  ret double 0.000000e+00
}
