; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -slp-revec -mtriple=aarch64-unknown-linux-gnu < %s | FileCheck %s

define <16 x i64> @test() {
; CHECK-LABEL: define <16 x i64> @test() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = zext <16 x i8> splat (i8 1) to <16 x i64>
; CHECK-NEXT:    [[TMP1:%.*]] = sub <16 x i64> zeroinitializer, [[TMP0]]
; CHECK-NEXT:    [[TMP2:%.*]] = zext <16 x i8> zeroinitializer to <16 x i64>
; CHECK-NEXT:    [[TMP3:%.*]] = sub <16 x i64> zeroinitializer, [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = call <16 x i64> @llvm.smin.v16i64(<16 x i64> [[TMP1]], <16 x i64> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = zext <16 x i8> zeroinitializer to <16 x i64>
; CHECK-NEXT:    [[TMP6:%.*]] = sub <16 x i64> zeroinitializer, [[TMP5]]
; CHECK-NEXT:    [[TMP7:%.*]] = call <16 x i64> @llvm.smin.v16i64(<16 x i64> [[TMP4]], <16 x i64> [[TMP6]])
; CHECK-NEXT:    [[TMP8:%.*]] = zext <16 x i8> zeroinitializer to <16 x i64>
; CHECK-NEXT:    [[TMP9:%.*]] = sub <16 x i64> zeroinitializer, [[TMP8]]
; CHECK-NEXT:    [[TMP10:%.*]] = call <16 x i64> @llvm.smin.v16i64(<16 x i64> [[TMP7]], <16 x i64> [[TMP9]])
; CHECK-NEXT:    [[TMP11:%.*]] = sub <16 x i64> zeroinitializer, zeroinitializer
; CHECK-NEXT:    [[TMP12:%.*]] = call <16 x i64> @llvm.smin.v16i64(<16 x i64> [[TMP10]], <16 x i64> [[TMP11]])
; CHECK-NEXT:    [[TMP13:%.*]] = sub <16 x i64> zeroinitializer, zeroinitializer
; CHECK-NEXT:    [[TMP14:%.*]] = call <16 x i64> @llvm.smin.v16i64(<16 x i64> [[TMP12]], <16 x i64> [[TMP13]])
; CHECK-NEXT:    [[TMP15:%.*]] = sub <16 x i64> zeroinitializer, zeroinitializer
; CHECK-NEXT:    [[TMP16:%.*]] = call <16 x i64> @llvm.smin.v16i64(<16 x i64> [[TMP14]], <16 x i64> [[TMP15]])
; CHECK-NEXT:    [[TMP17:%.*]] = sub <16 x i64> zeroinitializer, zeroinitializer
; CHECK-NEXT:    [[TMP48:%.*]] = call <16 x i64> @llvm.smin.v16i64(<16 x i64> [[TMP16]], <16 x i64> [[TMP17]])
; CHECK-NEXT:    ret <16 x i64> [[TMP48]]
;
entry:
  %0 = zext <16 x i8> splat (i8 1) to <16 x i64>
  %1 = sub <16 x i64> zeroinitializer, %0
  %2 = zext <16 x i8> zeroinitializer to <16 x i64>
  %3 = sub <16 x i64> zeroinitializer, %2
  %4 = call <16 x i64> @llvm.smin.v16i64(<16 x i64> %1, <16 x i64> %3)
  %5 = zext <16 x i8> zeroinitializer to <16 x i64>
  %6 = sub <16 x i64> zeroinitializer, %5
  %7 = call <16 x i64> @llvm.smin.v16i64(<16 x i64> %4, <16 x i64> %6)
  %8 = zext <16 x i8> zeroinitializer to <16 x i64>
  %9 = sub <16 x i64> zeroinitializer, %8
  %10 = call <16 x i64> @llvm.smin.v16i64(<16 x i64> %7, <16 x i64> %9)
  %11 = sub <16 x i64> zeroinitializer, zeroinitializer
  %12 = call <16 x i64> @llvm.smin.v16i64(<16 x i64> %10, <16 x i64> %11)
  %13 = sub <16 x i64> zeroinitializer, zeroinitializer
  %14 = call <16 x i64> @llvm.smin.v16i64(<16 x i64> %12, <16 x i64> %13)
  %15 = sub <16 x i64> zeroinitializer, zeroinitializer
  %16 = call <16 x i64> @llvm.smin.v16i64(<16 x i64> %14, <16 x i64> %15)
  %17 = sub <16 x i64> zeroinitializer, zeroinitializer
  %18 = call <16 x i64> @llvm.smin.v16i64(<16 x i64> %16, <16 x i64> %17)
  ret <16 x i64> %18
}

declare <16 x i64> @llvm.smin.v16i64(<16 x i64>, <16 x i64>)

