; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=arm64-apple-macosx15.0.0 < %s | FileCheck %s

define void @test(i1 %c, ptr %ptr0, ptr %ptr1, float %a, float %b) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i1 [[C:%.*]], ptr [[PTR0:%.*]], ptr [[PTR1:%.*]], float [[A:%.*]], float [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br i1 [[C]], label %[[EXIT:.*]], label %[[COMPUTE:.*]]
; CHECK:       [[COMPUTE]]:
; CHECK-NEXT:    [[FLAG:%.*]] = load i8, ptr [[PTR0]], align 1
; CHECK-NEXT:    [[T0:%.*]] = fmul float [[A]], 3.000000e+00
; CHECK-NEXT:    [[T1:%.*]] = fmul float [[T0]], 3.000000e+00
; CHECK-NEXT:    [[T2:%.*]] = fadd float [[A]], 2.000000e+00
; CHECK-NEXT:    [[T3:%.*]] = fmul float [[T2]], [[B]]
; CHECK-NEXT:    [[W:%.*]] = load float, ptr [[PTR0]], align 4
; CHECK-NEXT:    [[T4:%.*]] = fmul float [[W]], 3.000000e+00
; CHECK-NEXT:    [[T5:%.*]] = fadd float [[T4]], 2.000000e+00
; CHECK-NEXT:    [[T6:%.*]] = fmul float [[T5]], [[A]]
; CHECK-NEXT:    [[SUM0:%.*]] = fadd float [[T6]], 1.000000e+00
; CHECK-NEXT:    [[T7:%.*]] = fmul float [[W]], 3.000000e+00
; CHECK-NEXT:    [[T8:%.*]] = fmul float [[T7]], 3.000000e+00
; CHECK-NEXT:    [[T9:%.*]] = fadd float [[T8]], 2.000000e+00
; CHECK-NEXT:    [[COND0:%.*]] = icmp eq i8 [[FLAG]], 0
; CHECK-NEXT:    [[T10:%.*]] = fadd float [[T3]], 2.000000e+00
; CHECK-NEXT:    [[SEL0:%.*]] = select i1 [[COND0]], float 0.000000e+00, float [[T10]]
; CHECK-NEXT:    [[RES0:%.*]] = fadd float [[SUM0]], [[SEL0]]
; CHECK-NEXT:    [[COND1:%.*]] = icmp eq i8 [[FLAG]], 0
; CHECK-NEXT:    [[T11:%.*]] = fadd float [[T1]], 2.000000e+00
; CHECK-NEXT:    [[SEL1:%.*]] = select i1 [[COND1]], float 0.000000e+00, float [[T11]]
; CHECK-NEXT:    [[RES1:%.*]] = fadd float [[T9]], [[SEL1]]
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[TMP23:%.*]] = phi float [ 0.000000e+00, %[[ENTRY]] ], [ [[RES0]], %[[COMPUTE]] ]
; CHECK-NEXT:    [[TMP24:%.*]] = phi float [ 0.000000e+00, %[[ENTRY]] ], [ [[RES1]], %[[COMPUTE]] ]
; CHECK-NEXT:    store float [[TMP23]], ptr [[PTR0]], align 4
; CHECK-NEXT:    store float [[TMP24]], ptr [[PTR1]], align 4
; CHECK-NEXT:    ret void
;
entry:
  br i1 %c, label %exit, label %compute

compute:
  %flag = load i8, ptr %ptr0, align 1
  %t0 = fmul float %a, 3.000000e+00
  %t1 = fmul float %t0, 3.000000e+00
  %t2 = fadd float %a, 2.000000e+00
  %t3 = fmul float %t2, %b
  %w = load float, ptr %ptr0, align 4
  %t4 = fmul float %w, 3.000000e+00
  %t5 = fadd float %t4, 2.000000e+00
  %t6 = fmul float %t5, %a
  %sum0 = fadd float %t6, 1.000000e+00
  %t7 = fmul float %w, 3.000000e+00
  %t8 = fmul float %t7, 3.000000e+00
  %t9 = fadd float %t8, 2.000000e+00
  %cond0 = icmp eq i8 %flag, 0
  %t10 = fadd float %t3, 2.000000e+00
  %sel0 = select i1 %cond0, float 0.000000e+00, float %t10
  %res0 = fadd float %sum0, %sel0
  %cond1 = icmp eq i8 %flag, 0
  %t11 = fadd float %t1, 2.000000e+00
  %sel1 = select i1 %cond1, float 0.000000e+00, float %t11
  %res1 = fadd float %t9, %sel1
  br label %exit

exit:
  %r0 = phi float [ 0.000000e+00, %entry ], [ %res0, %compute ]
  %r1 = phi float [ 0.000000e+00, %entry ], [ %res1, %compute ]
  store float %r0, ptr %ptr0, align 4
  store float %r1, ptr %ptr1, align 4
  ret void

}
