; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; Test 16-bit atomic loads. Expect libcall without natural alignment.
;
; RUN: llc < %s -mtriple=s390x-linux-gnu | FileCheck %s

define i16 @f1(ptr %src) {
; CHECK-LABEL: f1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lh %r2, 0(%r2)
; CHECK-NEXT:    br %r14
  %val = load atomic i16, ptr %src seq_cst, align 2
  ret i16 %val
}

define i16 @f2(ptr %src) {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -168
; CHECK-NEXT:    .cfi_def_cfa_offset 328
; CHECK-NEXT:    lgr %r3, %r2
; CHECK-NEXT:    la %r4, 166(%r15)
; CHECK-NEXT:    lghi %r2, 2
; CHECK-NEXT:    lhi %r5, 5
; CHECK-NEXT:    brasl %r14, __atomic_load@PLT
; CHECK-NEXT:    lh %r2, 166(%r15)
; CHECK-NEXT:    lmg %r14, %r15, 280(%r15)
; CHECK-NEXT:    br %r14
  %val = load atomic i16, ptr %src seq_cst, align 1
  ret i16 %val
}
