; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; Test float atomic loads. Expect libcall without natural alignment.
;
; RUN: llc < %s -mtriple=s390x-linux-gnu | FileCheck %s
; RUN: llc < %s -mtriple=s390x-linux-gnu -mcpu=z14 | FileCheck %s --check-prefix=Z14

define void @f1(ptr %src, float %val) {
; CHECK-LABEL: f1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $f0s killed $f0s def $f0d
; CHECK-NEXT:    lgdr %r0, %f0
; CHECK-NEXT:    srlg %r0, %r0, 32
; CHECK-NEXT:    st %r0, 0(%r2)
; CHECK-NEXT:    bcr 15, %r0
; CHECK-NEXT:    br %r14
;
; Z14-LABEL: f1:
; Z14:       # %bb.0:
; Z14-NEXT:    ste %f0, 0(%r2)
; Z14-NEXT:    bcr 14, %r0
; Z14-NEXT:    br %r14
  store atomic float %val, ptr %src seq_cst, align 4
  ret void
}

define void @f2(ptr %src, float %val) {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -168
; CHECK-NEXT:    .cfi_def_cfa_offset 328
; CHECK-NEXT:    lgr %r3, %r2
; CHECK-NEXT:    ste %f0, 164(%r15)
; CHECK-NEXT:    la %r4, 164(%r15)
; CHECK-NEXT:    lghi %r2, 4
; CHECK-NEXT:    lhi %r5, 5
; CHECK-NEXT:    brasl %r14, __atomic_store@PLT
; CHECK-NEXT:    lmg %r14, %r15, 280(%r15)
; CHECK-NEXT:    br %r14
;
; Z14-LABEL: f2:
; Z14:       # %bb.0:
; Z14-NEXT:    stmg %r14, %r15, 112(%r15)
; Z14-NEXT:    .cfi_offset %r14, -48
; Z14-NEXT:    .cfi_offset %r15, -40
; Z14-NEXT:    aghi %r15, -168
; Z14-NEXT:    .cfi_def_cfa_offset 328
; Z14-NEXT:    lgr %r3, %r2
; Z14-NEXT:    la %r4, 164(%r15)
; Z14-NEXT:    lghi %r2, 4
; Z14-NEXT:    lhi %r5, 5
; Z14-NEXT:    ste %f0, 164(%r15)
; Z14-NEXT:    brasl %r14, __atomic_store@PLT
; Z14-NEXT:    lmg %r14, %r15, 280(%r15)
; Z14-NEXT:    br %r14
  store atomic float %val, ptr %src seq_cst, align 2
  ret void
}
