# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# RUN: llc -mtriple=s390x-ibm-linux -mcpu=z13 -run-pass=postrapseudos -o - %s | FileCheck %s

---
name:            copy_fp64_to_gr64__r1d_to_f3d
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r1d
    ; CHECK-LABEL: name: copy_fp64_to_gr64__r1d_to_f3d
    ; CHECK: liveins: $r1d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $f3d = LDGR $r1d
    ; CHECK-NEXT: Return implicit $f3d
    $f3d = COPY $r1d
    Return implicit $f3d
...

---
name:            copy_fp64_to_gr64__r1d_to_f3d_undef
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r1d
    ; CHECK-LABEL: name: copy_fp64_to_gr64__r1d_to_f3d_undef
    ; CHECK: liveins: $r1d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $f3d = KILL undef $r1d
    ; CHECK-NEXT: Return implicit $f3d
    $f3d = COPY undef $r1d
    Return implicit $f3d
...

---
name:            copy_fp64_to_gr64__r1d_to_f3d_killed
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r1d
    ; CHECK-LABEL: name: copy_fp64_to_gr64__r1d_to_f3d_killed
    ; CHECK: liveins: $r1d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $f3d = LDGR killed $r1d
    ; CHECK-NEXT: Return implicit $f3d
    $f3d = COPY killed $r1d
    Return implicit $f3d
...

