# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# RUN: llc -mtriple=s390x-ibm-linux -mcpu=z13 -run-pass=postrapseudos -verify-machineinstrs -o - %s | FileCheck %s

---
name:            copy_gr128_to_fp128__r0q_to_f0q
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0q
    ; CHECK-LABEL: name: copy_gr128_to_fp128__r0q_to_f0q
    ; CHECK: liveins: $r0q
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $f0d = LDGR $r0d, implicit-def $f0q
    ; CHECK-NEXT: $f2d = LDGR $r1d
    ; CHECK-NEXT: Return implicit $f0q
    $f0q = COPY $r0q
    Return implicit $f0q
...

---
name:            copy_gr128_to_fp128__r0q_to_f0q_killed
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0q
    ; CHECK-LABEL: name: copy_gr128_to_fp128__r0q_to_f0q_killed
    ; CHECK: liveins: $r0q
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $f0d = LDGR $r0d, implicit-def $f0q
    ; CHECK-NEXT: $f2d = LDGR killed $r1d
    ; CHECK-NEXT: Return implicit $f0q
    $f0q = COPY killed $r0q
    Return implicit $f0q
...

---
name:            copy_gr128_to_fp128__r0q_to_f0q_undef
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0q
    ; CHECK-LABEL: name: copy_gr128_to_fp128__r0q_to_f0q_undef
    ; CHECK: liveins: $r0q
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $f0q = KILL undef $r0q
    ; CHECK-NEXT: Return implicit $f0q
    $f0q = COPY undef $r0q
    Return implicit $f0q
...
