# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# RUN: llc -mtriple=s390x-ibm-linux -mcpu=z13 -run-pass=postrapseudos -o - %s | FileCheck %s
# RUN: llc -mtriple=s390x-ibm-linux -mcpu=z13 -passes=post-ra-pseudos -o - %s | FileCheck %s
---
name:            copy_fp64_to_gr64__f3d_to_r1d
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $f3d
    ; CHECK-LABEL: name: copy_fp64_to_gr64__f3d_to_r1d
    ; CHECK: liveins: $f3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r1d = LGDR $f3d
    ; CHECK-NEXT: Return implicit $r1d
    $r1d = COPY $f3d
    Return implicit $r1d
...

---
name:            copy_fp64_to_gr64__f3d_to_r1d_undef
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $f3d
    ; CHECK-LABEL: name: copy_fp64_to_gr64__f3d_to_r1d_undef
    ; CHECK: liveins: $f3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r1d = KILL undef $f3d
    ; CHECK-NEXT: Return implicit $r1d
    $r1d = COPY undef $f3d
    Return implicit $r1d
...

---
name:            copy_fp64_to_gr64__f3d_to_r1d_killed
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $f3d
    ; CHECK-LABEL: name: copy_fp64_to_gr64__f3d_to_r1d_killed
    ; CHECK: liveins: $f3d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r1d = LGDR killed $f3d
    ; CHECK-NEXT: Return implicit $r1d
    $r1d = COPY killed $f3d
    Return implicit $r1d
...

