# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# RUN: llc -mtriple=s390x-ibm-linux -mcpu=z13 -run-pass=postrapseudos -o - %s | FileCheck %s

---
name:            copy_vr128_to_gr128__v0_to_r0q
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $v0
    ; CHECK-LABEL: name: copy_vr128_to_gr128__v0_to_r0q
    ; CHECK: liveins: $v0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r0d = VLGVG $v0, $noreg, 0, implicit-def $r0q
    ; CHECK-NEXT: $r1d = VLGVG $v0, $noreg, 1
    ; CHECK-NEXT: Return implicit $r0q
    $r0q = COPY $v0
    Return implicit $r0q
...

---
name:            copy_vr128_to_gr128__v0_to_r0q_killed
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $v0
    ; CHECK-LABEL: name: copy_vr128_to_gr128__v0_to_r0q_killed
    ; CHECK: liveins: $v0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $r0d = VLGVG $v0, $noreg, 0, implicit-def $r0q
    ; CHECK-NEXT: $r1d = VLGVG killed $v0, $noreg, 1
    ; CHECK-NEXT: Return implicit $r0q
    $r0q = COPY killed $v0
    Return implicit $r0q
...

---
name:            copy_vr128_to_gr128__v0_to_r0q_undef
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: copy_vr128_to_gr128__v0_to_r0q_undef
    ; CHECK: $r0q = KILL undef $v0
    ; CHECK-NEXT: Return implicit $r0q
    $r0q = COPY undef $v0
    Return implicit $r0q
...

---
name:            copy_vr128_to_gr128__v0_to_r0q_undef_use_subreg0
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: copy_vr128_to_gr128__v0_to_r0q_undef_use_subreg0
    ; CHECK: $r0q = KILL undef $v0
    ; CHECK-NEXT: Return implicit $r0d
    $r0q = COPY undef $v0
    Return implicit $r0d
...

---
name:            copy_vr128_to_gr128__v0_to_r0q_undef_use_subreg1
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: copy_vr128_to_gr128__v0_to_r0q_undef_use_subreg1
    ; CHECK: $r0q = KILL undef $v0
    ; CHECK-NEXT: Return implicit $r1d
    $r0q = COPY undef $v0
    Return implicit $r1d
...
