; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; Test Flag Output Operands with 14 combinations of CCMASK and optimizations
; for XOR for three different functions, including two test cases from heiko.
; This test checks NOT EQUAL (!=), e.g.  CC != 0 ^ CC != 1 ^ CC != 2.

; RUN: llc < %s -verify-machineinstrs -mtriple=s390x-linux-gnu -O2 | FileCheck %s
; Test CC != 0 ^ CC != 1.
define signext range(i32 0, 43) i32 @foo_01(i32 noundef signext %x) {
; CHECK-LABEL: foo_01:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    ahi %r2, 42
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 42
; CHECK-NEXT:    bler %r14
; CHECK-NEXT:  .LBB0_1: # %entry
; CHECK-NEXT:    lghi %r2, 0
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call { i32, i32 } asm "ahi $0,42\0A", "=d,={@cc},0"(i32 %x) #2
  %asmresult1 = extractvalue { i32, i32 } %0, 1
  %1 = icmp ult i32 %asmresult1, 4
  tail call void @llvm.assume(i1 %1)
  %xor5 = icmp samesign ult i32 %asmresult1, 2
  %cond = select i1 %xor5, i32 42, i32 0
  ret i32 %cond
}

declare void @llvm.assume(i1 noundef) #1

; Test CC != 0 ^ CC != 2.
define signext range(i32 0, 43) i32 @foo_02(i32 noundef signext %x) {
; CHECK-LABEL: foo_02:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    ahi %r2, 42
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 42
; CHECK-NEXT:    bher %r14
; CHECK-NEXT:  .LBB1_1: # %entry
; CHECK-NEXT:    lghi %r2, 0
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call { i32, i32 } asm "ahi $0,42\0A", "=d,={@cc},0"(i32 %x) #2
  %asmresult1 = extractvalue { i32, i32 } %0, 1
  %1 = icmp ult i32 %asmresult1, 4
  tail call void @llvm.assume(i1 %1)
  %cmp = icmp ne i32 %asmresult1, 0
  %cmp2 = icmp ne i32 %asmresult1, 2
  %xor5 = xor i1 %cmp, %cmp2
  %cond = select i1 %xor5, i32 42, i32 0
  ret i32 %cond
}

; Test CC != 0 ^ CC != 3.
define signext range(i32 0, 43) i32 @foo_03(i32 noundef signext %x) {
; CHECK-LABEL: foo_03:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    ahi %r2, 42
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 42
; CHECK-NEXT:    bnlhr %r14
; CHECK-NEXT:  .LBB2_1: # %entry
; CHECK-NEXT:    lghi %r2, 0
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call { i32, i32 } asm "ahi $0,42\0A", "=d,={@cc},0"(i32 %x) #2
  %asmresult1 = extractvalue { i32, i32 } %0, 1
  %1 = icmp ult i32 %asmresult1, 4
  tail call void @llvm.assume(i1 %1)
  %cmp = icmp ne i32 %asmresult1, 0
  %cmp2 = icmp ne i32 %asmresult1, 3
  %xor5 = xor i1 %cmp, %cmp2
  %cond = select i1 %xor5, i32 42, i32 0
  ret i32 %cond
}

; Test CC != 1 ^ CC != 2.
define signext range(i32 0, 43) i32 @foo_12(i32 noundef signext %x) {
; CHECK-LABEL: foo_12:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    ahi %r2, 42
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 42
; CHECK-NEXT:    blhr %r14
; CHECK-NEXT:  .LBB3_1: # %entry
; CHECK-NEXT:    lghi %r2, 0
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call { i32, i32 } asm "ahi $0,42\0A", "=d,={@cc},0"(i32 %x) #2
  %asmresult1 = extractvalue { i32, i32 } %0, 1
  %1 = icmp ult i32 %asmresult1, 4
  tail call void @llvm.assume(i1 %1)
  %2 = add nsw i32 %asmresult1, -1
  %xor5 = icmp ult i32 %2, 2
  %cond = select i1 %xor5, i32 42, i32 0
  ret i32 %cond
}

; Test CC != 1 ^ CC != 3.
define signext range(i32 0, 43) i32 @foo_13(i32 noundef signext %x) {
; CHECK-LABEL: foo_13:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    ahi %r2, 42
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 42
; CHECK-NEXT:    bnher %r14
; CHECK-NEXT:  .LBB4_1: # %entry
; CHECK-NEXT:    lghi %r2, 0
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call { i32, i32 } asm "ahi $0,42\0A", "=d,={@cc},0"(i32 %x) #2
  %asmresult1 = extractvalue { i32, i32 } %0, 1
  %1 = icmp ult i32 %asmresult1, 4
  tail call void @llvm.assume(i1 %1)
  %cmp = icmp ne i32 %asmresult1, 1
  %cmp2 = icmp ne i32 %asmresult1, 3
  %xor5 = xor i1 %cmp, %cmp2
  %cond = select i1 %xor5, i32 42, i32 0
  ret i32 %cond
}

; Test CC != 2 ^ CC != 3.
define signext range(i32 0, 43) i32 @foo_23(i32 noundef signext %x) {
; CHECK-LABEL: foo_23:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    ahi %r2, 42
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 42
; CHECK-NEXT:    bnler %r14
; CHECK-NEXT:  .LBB5_1: # %entry
; CHECK-NEXT:    lghi %r2, 0
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call { i32, i32 } asm "ahi $0,42\0A", "=d,={@cc},0"(i32 %x) #2
  %asmresult1 = extractvalue { i32, i32 } %0, 1
  %1 = icmp ult i32 %asmresult1, 4
  tail call void @llvm.assume(i1 %1)
  %xor5 = icmp samesign ugt i32 %asmresult1, 1
  %cond = select i1 %xor5, i32 42, i32 0
  ret i32 %cond
}

; Test CC != 0 ^ CC != 1 ^ CC != 2.
define signext range(i32 0, 43) i32 @foo_012(i32 noundef signext %x) {
; CHECK-LABEL: foo_012:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    ahi %r2, 42
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 42
; CHECK-NEXT:    bor %r14
; CHECK-NEXT:  .LBB6_1: # %entry
; CHECK-NEXT:    lghi %r2, 0
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call { i32, i32 } asm "ahi $0,42\0A", "=d,={@cc},0"(i32 %x) #2
  %asmresult1 = extractvalue { i32, i32 } %0, 1
  %1 = icmp ult i32 %asmresult1, 4
  tail call void @llvm.assume(i1 %1)
  %xor610 = icmp eq i32 %asmresult1, 3
  %cond = select i1 %xor610, i32 42, i32 0
  ret i32 %cond
}

; Test CC != 0 ^ CC != 1 ^ CC != 3.
define signext range(i32 0, 43) i32 @foo_013(i32 noundef signext %x) {
; CHECK-LABEL: foo_013:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    ahi %r2, 42
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 42
; CHECK-NEXT:    bhr %r14
; CHECK-NEXT:  .LBB7_1: # %entry
; CHECK-NEXT:    lghi %r2, 0
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call { i32, i32 } asm "ahi $0,42\0A", "=d,={@cc},0"(i32 %x) #2
  %asmresult1 = extractvalue { i32, i32 } %0, 1
  %1 = icmp ult i32 %asmresult1, 4
  tail call void @llvm.assume(i1 %1)
  %xor9 = icmp samesign ugt i32 %asmresult1, 1
  %cmp4 = icmp ne i32 %asmresult1, 3
  %xor610 = and i1 %xor9, %cmp4
  %cond = select i1 %xor610, i32 42, i32 0
  ret i32 %cond
}

; Test CC != 0 ^ CC != 2 ^ CC != 3.
define signext range(i32 0, 43) i32 @foo_023(i32 noundef signext %x) {
; CHECK-LABEL: foo_023:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    ahi %r2, 42
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 42
; CHECK-NEXT:    blr %r14
; CHECK-NEXT:  .LBB8_1: # %entry
; CHECK-NEXT:    lghi %r2, 0
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call { i32, i32 } asm "ahi $0,42\0A", "=d,={@cc},0"(i32 %x) #2
  %asmresult1 = extractvalue { i32, i32 } %0, 1
  %1 = icmp ult i32 %asmresult1, 4
  tail call void @llvm.assume(i1 %1)
  %cmp = icmp ne i32 %asmresult1, 0
  %cmp2 = icmp ne i32 %asmresult1, 2
  %xor9 = xor i1 %cmp, %cmp2
  %cmp4 = icmp ne i32 %asmresult1, 3
  %xor610 = xor i1 %cmp4, %xor9
  %cond = select i1 %xor610, i32 42, i32 0
  ret i32 %cond
}

; Test CC != 1 ^ CC != 2 ^ CC != 3.
define signext range(i32 0, 43) i32 @foo_123(i32 noundef signext %x) {
; CHECK-LABEL: foo_123:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    ahi %r2, 42
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 42
; CHECK-NEXT:    ber %r14
; CHECK-NEXT:  .LBB9_1: # %entry
; CHECK-NEXT:    lghi %r2, 0
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call { i32, i32 } asm "ahi $0,42\0A", "=d,={@cc},0"(i32 %x) #2
  %asmresult1 = extractvalue { i32, i32 } %0, 1
  %1 = icmp ult i32 %asmresult1, 4
  tail call void @llvm.assume(i1 %1)
  %xor610 = icmp eq i32 %asmresult1, 0
  %cond = select i1 %xor610, i32 42, i32 0
  ret i32 %cond
}


@a = global i32 0, align 4

; Test CC != 0 ^ CC != 1.
define range(i64 5, 9) i64 @fu_01() {
; CHECK-LABEL: fu_01:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 8
; CHECK-NEXT:    bnler %r14
; CHECK-NEXT:  .LBB10_1: # %entry
; CHECK-NEXT:    lghi %r2, 5
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #2
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %xor4.i = icmp samesign ugt i32 %0, 1
  %. = select i1 %xor4.i, i64 8, i64 5
  ret i64 %.
}

; Test CC != 0 ^ CC != 2.
define range(i64 5, 9) i64 @fu_02() {
; CHECK-LABEL: fu_02:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 5
; CHECK-NEXT:    bher %r14
; CHECK-NEXT:  .LBB11_1: # %entry
; CHECK-NEXT:    lghi %r2, 8
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #2
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %2 = and i32 %0, 1
  %tobool.not.not = icmp eq i32 %2, 0
  %. = select i1 %tobool.not.not, i64 5, i64 8
  ret i64 %.
}

; Test CC != 0 ^ CC != 3.
define range(i64 5, 9) i64 @fu_03() {
; CHECK-LABEL: fu_03:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 8
; CHECK-NEXT:    blhr %r14
; CHECK-NEXT:  .LBB12_1: # %entry
; CHECK-NEXT:    lghi %r2, 5
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #2
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %cmp.i = icmp ne i32 %0, 0
  %2 = icmp ne i32 %0, 3
  %tobool.not = and i1 %cmp.i, %2
  %. = select i1 %tobool.not, i64 8, i64 5
  ret i64 %.
}

; Test CC != 1 ^ CC != 2.
define range(i64 5, 9) i64 @fu_12() {
; CHECK-LABEL: fu_12:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 8
; CHECK-NEXT:    bnlhr %r14
; CHECK-NEXT:  .LBB13_1: # %entry
; CHECK-NEXT:    lghi %r2, 5
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #2
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %2 = add nsw i32 %0, -3
  %xor4.i = icmp ult i32 %2, -2
  %. = select i1 %xor4.i, i64 8, i64 5
  ret i64 %.
}

; Test CC != 1 ^ CC != 3.
define range(i64 5, 9) i64 @fu_13() {
; CHECK-LABEL: fu_13:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 8
; CHECK-NEXT:    bher %r14
; CHECK-NEXT:  .LBB14_1: # %entry
; CHECK-NEXT:    lghi %r2, 5
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #2
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %2 = and i32 %0, 1
  %tobool.not.not.not = icmp eq i32 %2, 0
  %. = select i1 %tobool.not.not.not, i64 8, i64 5
  ret i64 %.
}

; Test CC != 2 ^ CC != 3.
define range(i64 5, 9) i64 @fu_23() {
; CHECK-LABEL: fu_23:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 8
; CHECK-NEXT:    bler %r14
; CHECK-NEXT:  .LBB15_1: # %entry
; CHECK-NEXT:    lghi %r2, 5
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #2
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %xor4.i = icmp samesign ult i32 %0, 2
  %. = select i1 %xor4.i, i64 8, i64 5
  ret i64 %.
}

; Test CC != 0 ^ CC != 1 ^ CC != 2.
define range(i64 5, 9) i64 @fu_012() {
; CHECK-LABEL: fu_012:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 5
; CHECK-NEXT:    bor %r14
; CHECK-NEXT:  .LBB16_1: # %entry
; CHECK-NEXT:    lghi %r2, 8
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #2
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %xor59.i.not = icmp eq i32 %0, 3
  %. = select i1 %xor59.i.not, i64 5, i64 8
  ret i64 %.
}

; Test CC != 0 ^ CC != 1 ^ CC != 3.
define range(i64 5, 9) i64 @fu_013() {
; CHECK-LABEL: fu_013:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 8
; CHECK-NEXT:    bnhr %r14
; CHECK-NEXT:  .LBB17_1: # %entry
; CHECK-NEXT:    lghi %r2, 5
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #2
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %xor8.i = icmp samesign ult i32 %0, 2
  %cmp3.i = icmp eq i32 %0, 3
  %xor59.i.not = or i1 %xor8.i, %cmp3.i
  %. = select i1 %xor59.i.not, i64 8, i64 5
  ret i64 %.
}

; Test CC != 0 ^ CC != 2 ^ CC != 3.
define range(i64 5, 9) i64 @fu_023() {
; CHECK-LABEL: fu_023:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 8
; CHECK-NEXT:    bnlr %r14
; CHECK-NEXT:  .LBB18_1: # %entry
; CHECK-NEXT:    lghi %r2, 5
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #2
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %cmp.i = icmp ne i32 %0, 0
  %cmp1.i = icmp ne i32 %0, 2
  %xor8.i = xor i1 %cmp.i, %cmp1.i
  %2 = icmp eq i32 %0, 3
  %tobool.not = xor i1 %2, %xor8.i
  %. = select i1 %tobool.not, i64 8, i64 5
  ret i64 %.
}

; Test CC != 1 ^ CC != 2 ^ CC != 3.
define range(i64 5, 9) i64 @fu_123() {
; CHECK-LABEL: fu_123:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    lghi %r2, 5
; CHECK-NEXT:    ber %r14
; CHECK-NEXT:  .LBB19_1: # %entry
; CHECK-NEXT:    lghi %r2, 8
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #2
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %xor59.i.not = icmp eq i32 %0, 0
  %. = select i1 %xor59.i.not, i64 5, i64 8
  ret i64 %.
}

; Test CC != 0 ^ CC != 1.
define void @bar_01() {
; CHECK-LABEL: bar_01:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    jgle dummy@PLT
; CHECK-NEXT:  .LBB20_1: # %if.end
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #3
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %xor4.i = icmp samesign ugt i32 %0, 1
  br i1 %xor4.i, label %if.end, label %if.then

if.then:                                          ; preds = %entry
  tail call void @dummy() #3
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

declare void @dummy() local_unnamed_addr #1

; Test CC != 0 ^ CC != 2.
define void @bar_02() {
; CHECK-LABEL: bar_02:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    jghe dummy@PLT
; CHECK-NEXT:  .LBB21_1: # %if.end
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #3
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %2 = and i32 %0, 1
  %tobool.not.not = icmp eq i32 %2, 0
  br i1 %tobool.not.not, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  tail call void @dummy() #3
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

; Test CC != 0 ^ CC != 3.
; TODO: DAGCombiner is not able to optimize srl/ipm/cc sequence because of
; switch table created by simplifyBranchOnICmpChain.
define void @bar_03() {
; CHECK-LABEL: bar_03:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    ipm %r0
; CHECK-NEXT:    jgo dummy@PLT
; CHECK-NEXT:  .LBB22_1: # %entry
; CHECK-NEXT:    srl %r0, 28
; CHECK-NEXT:    ciblh %r0, 0, 0(%r14)
; CHECK-NEXT:  .LBB22_2: # %if.then
; CHECK-NEXT:    jg dummy@PLT
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #3
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  switch i32 %0, label %if.end [
    i32 3, label %if.then
    i32 0, label %if.then
  ]

if.then:                                          ; preds = %entry, %entry
  tail call void @dummy() #3
  br label %if.end

if.end:                                           ; preds = %entry, %if.then
  ret void
}

; Test CC != 1 ^ CC != 2.
define void @bar_12() {
; CHECK-LABEL: bar_12:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    jglh dummy@PLT
; CHECK-NEXT:  .LBB23_1: # %if.end
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #3
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %2 = add nsw i32 %0, -3
  %xor4.i = icmp ult i32 %2, -2
  br i1 %xor4.i, label %if.end, label %if.then

if.then:                                          ; preds = %entry
  tail call void @dummy() #3
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

; Test CC != 1 ^ CC != 3.
define void @bar_13() {
; CHECK-LABEL: bar_13:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    jgnhe dummy@PLT
; CHECK-NEXT:  .LBB24_1: # %if.end
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #3
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %2 = and i32 %0, 1
  %tobool.not.not.not = icmp eq i32 %2, 0
  br i1 %tobool.not.not.not, label %if.end, label %if.then

if.then:                                          ; preds = %entry
  tail call void @dummy() #3
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

; Test CC != 2 ^ CC != 3.
define void @bar_23() {
; CHECK-LABEL: bar_23:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    jgnle dummy@PLT
; CHECK-NEXT:  .LBB25_1: # %if.end
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #3
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %xor4.i = icmp samesign ult i32 %0, 2
  br i1 %xor4.i, label %if.end, label %if.then

if.then:                                          ; preds = %entry
  tail call void @dummy() #3
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

; Test CC != 0 ^ CC != 1 ^ CC != 2.
define void @bar_012() {
; CHECK-LABEL: bar_012:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    jgo dummy@PLT
; CHECK-NEXT:  .LBB26_1: # %if.end
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #3
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %xor59.i.not = icmp eq i32 %0, 3
  br i1 %xor59.i.not, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  tail call void @dummy() #3
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

; Test CC != 0 ^ CC != 1 ^ CC != 3.
define void @bar_013() {
; CHECK-LABEL: bar_013:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    jgh dummy@PLT
; CHECK-NEXT:  .LBB27_1: # %if.end
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #3
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %switch = icmp eq i32 %0, 2
  br i1 %switch, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  tail call void @dummy() #3
  br label %if.end

if.end:                                           ; preds = %entry, %if.then
  ret void
}

; Test CC != 0 ^ CC != 2 ^ CC != 3.
define void @bar_023() {
; CHECK-LABEL: bar_023:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    jgl dummy@PLT
; CHECK-NEXT:  .LBB28_1: # %if.end
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #3
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %cmp.i = icmp ne i32 %0, 0
  %cmp1.i = icmp ne i32 %0, 2
  %xor8.i = xor i1 %cmp.i, %cmp1.i
  %2 = icmp eq i32 %0, 3
  %tobool.not = xor i1 %2, %xor8.i
  br i1 %tobool.not, label %if.end, label %if.then

if.then:                                          ; preds = %entry
  tail call void @dummy() #3
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

; Test CC != 1 ^ CC != 2 ^ CC != 3.
define void @bar_123() {
; CHECK-LABEL: bar_123:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lgrl %r1, a@GOT
; CHECK-NEXT:    #APP
; CHECK-NEXT:    alsi 0(%r1), -1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    jge dummy@PLT
; CHECK-NEXT:  .LBB29_1: # %if.end
; CHECK-NEXT:    br %r14
entry:
  %0 = tail call i32 asm sideeffect "       alsi    $1,-1\0A", "={@cc},=*QS,*QS,~{memory}"(ptr nonnull elementtype(i32) @a, ptr nonnull elementtype(i32) @a) #3
  %1 = icmp ult i32 %0, 4
  tail call void @llvm.assume(i1 %1)
  %xor59.i.not = icmp eq i32 %0, 0
  br i1 %xor59.i.not, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  tail call void @dummy() #3
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}


