; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Test strict conversions of unsigned i64s to floating-point values (z10 only).
;
; RUN: llc < %s -mtriple=s390x-linux-gnu -mcpu=z10 | FileCheck %s

declare half @llvm.experimental.constrained.uitofp.f16.i64(i64, metadata, metadata)
declare float @llvm.experimental.constrained.uitofp.f32.i64(i64, metadata, metadata)
declare double @llvm.experimental.constrained.uitofp.f64.i64(i64, metadata, metadata)
declare fp128 @llvm.experimental.constrained.uitofp.f128.i64(i64, metadata, metadata)

; Test i64->f16. For z10, this results in just a single a libcall.
define half @f0(i64 %i) #0 {
; CHECK-LABEL: f0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    cgijhe %r2, 0, .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    risbg %r0, %r2, 63, 191, 0
; CHECK-NEXT:    rosbg %r0, %r2, 1, 63, 63
; CHECK-NEXT:    cegbr %f0, %r0
; CHECK-NEXT:    aebr %f0, %f0
; CHECK-NEXT:    j .LBB0_3
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    cegbr %f0, %r2
; CHECK-NEXT:  .LBB0_3:
; CHECK-NEXT:    brasl %r14, __truncsfhf2@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  %conv = call half @llvm.experimental.constrained.uitofp.f16.i64(i64 %i,
                                               metadata !"round.dynamic",
                                               metadata !"fpexcept.strict") #0
  ret half %conv
}

; Test i64->f32.  There's no native support for unsigned i64-to-fp conversions,
; but we should be able to implement them using signed i64-to-fp conversions.
define float @f1(i64 %i) #0 {
; CHECK-LABEL: f1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cgijhe %r2, 0, .LBB1_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    risbg %r0, %r2, 63, 191, 0
; CHECK-NEXT:    rosbg %r0, %r2, 1, 63, 63
; CHECK-NEXT:    cegbr %f0, %r0
; CHECK-NEXT:    aebr %f0, %f0
; CHECK-NEXT:    br %r14
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    cegbr %f0, %r2
; CHECK-NEXT:    br %r14
  %conv = call float @llvm.experimental.constrained.uitofp.f32.i64(i64 %i,
                                               metadata !"round.dynamic",
                                               metadata !"fpexcept.strict") #0
  ret float %conv
}

; Test i64->f64.
define double @f2(i64 %i) #0 {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srlg %r0, %r2, 32
; CHECK-NEXT:    oihh %r0, 17712
; CHECK-NEXT:    ldgr %f1, %r0
; CHECK-NEXT:    larl %r1, .LCPI2_0
; CHECK-NEXT:    sdb %f1, 0(%r1)
; CHECK-NEXT:    iihf %r2, 1127219200
; CHECK-NEXT:    ldgr %f0, %r2
; CHECK-NEXT:    adbr %f0, %f1
; CHECK-NEXT:    br %r14
  %conv = call double @llvm.experimental.constrained.uitofp.f64.i64(i64 %i,
                                               metadata !"round.dynamic",
                                               metadata !"fpexcept.strict") #0
  ret double %conv
}

; Test i64->f128.
define void @f3(i64 %i, ptr %dst) #0 {
; CHECK-LABEL: f3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lghi %r1, 4
; CHECK-NEXT:    cgijl %r2, 0, .LBB3_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    lghi %r1, 0
; CHECK-NEXT:  .LBB3_2:
; CHECK-NEXT:    larl %r4, .LCPI3_0
; CHECK-NEXT:    lxeb %f0, 0(%r1,%r4)
; CHECK-NEXT:    cxgbr %f1, %r2
; CHECK-NEXT:    axbr %f1, %f0
; CHECK-NEXT:    std %f1, 0(%r3)
; CHECK-NEXT:    std %f3, 8(%r3)
; CHECK-NEXT:    br %r14
  %conv = call fp128 @llvm.experimental.constrained.uitofp.f128.i64(i64 %i,
                                               metadata !"round.dynamic",
                                               metadata !"fpexcept.strict") #0
  store fp128 %conv, ptr %dst
  ret void
}

attributes #0 = { strictfp }
