; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=s390x-linux-gnu -mcpu=z10 \
; RUN:   | FileCheck -check-prefix=CHECK -check-prefix=CHECK-SCALAR %s
; RUN: llc < %s -mtriple=s390x-linux-gnu -mcpu=z14 \
; RUN:   | FileCheck -check-prefix=CHECK -check-prefix=CHECK-VECTOR %s

declare half @llvm.experimental.constrained.fma.f16(half, half, half, metadata, metadata)
declare float @llvm.experimental.constrained.fma.f32(float, float, float, metadata, metadata)

define half @f0(half %f1, half %f2, half %acc) #0 {
; CHECK-SCALAR-LABEL: f0:
; CHECK-SCALAR:       # %bb.0:
; CHECK-SCALAR-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-SCALAR-NEXT:    .cfi_offset %r14, -48
; CHECK-SCALAR-NEXT:    .cfi_offset %r15, -40
; CHECK-SCALAR-NEXT:    aghi %r15, -184
; CHECK-SCALAR-NEXT:    .cfi_def_cfa_offset 344
; CHECK-SCALAR-NEXT:    std %f8, 176(%r15) # 8-byte Spill
; CHECK-SCALAR-NEXT:    std %f9, 168(%r15) # 8-byte Spill
; CHECK-SCALAR-NEXT:    std %f10, 160(%r15) # 8-byte Spill
; CHECK-SCALAR-NEXT:    .cfi_offset %f8, -168
; CHECK-SCALAR-NEXT:    .cfi_offset %f9, -176
; CHECK-SCALAR-NEXT:    .cfi_offset %f10, -184
; CHECK-SCALAR-NEXT:    ler %f8, %f4
; CHECK-SCALAR-NEXT:    ler %f9, %f0
; CHECK-SCALAR-NEXT:    ler %f0, %f2
; CHECK-SCALAR-NEXT:    brasl %r14, __extendhfdf2@PLT
; CHECK-SCALAR-NEXT:    ldr %f10, %f0
; CHECK-SCALAR-NEXT:    ler %f0, %f9
; CHECK-SCALAR-NEXT:    brasl %r14, __extendhfdf2@PLT
; CHECK-SCALAR-NEXT:    ldr %f9, %f0
; CHECK-SCALAR-NEXT:    ler %f0, %f8
; CHECK-SCALAR-NEXT:    brasl %r14, __extendhfdf2@PLT
; CHECK-SCALAR-NEXT:    madbr %f0, %f9, %f10
; CHECK-SCALAR-NEXT:    brasl %r14, __truncdfhf2@PLT
; CHECK-SCALAR-NEXT:    ld %f8, 176(%r15) # 8-byte Reload
; CHECK-SCALAR-NEXT:    ld %f9, 168(%r15) # 8-byte Reload
; CHECK-SCALAR-NEXT:    ld %f10, 160(%r15) # 8-byte Reload
; CHECK-SCALAR-NEXT:    lmg %r14, %r15, 296(%r15)
; CHECK-SCALAR-NEXT:    br %r14
;
; CHECK-VECTOR-LABEL: f0:
; CHECK-VECTOR:       # %bb.0:
; CHECK-VECTOR-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-VECTOR-NEXT:    .cfi_offset %r14, -48
; CHECK-VECTOR-NEXT:    .cfi_offset %r15, -40
; CHECK-VECTOR-NEXT:    aghi %r15, -184
; CHECK-VECTOR-NEXT:    .cfi_def_cfa_offset 344
; CHECK-VECTOR-NEXT:    std %f8, 176(%r15) # 8-byte Spill
; CHECK-VECTOR-NEXT:    std %f9, 168(%r15) # 8-byte Spill
; CHECK-VECTOR-NEXT:    std %f10, 160(%r15) # 8-byte Spill
; CHECK-VECTOR-NEXT:    .cfi_offset %f8, -168
; CHECK-VECTOR-NEXT:    .cfi_offset %f9, -176
; CHECK-VECTOR-NEXT:    .cfi_offset %f10, -184
; CHECK-VECTOR-NEXT:    ldr %f9, %f0
; CHECK-VECTOR-NEXT:    ldr %f0, %f4
; CHECK-VECTOR-NEXT:    ldr %f8, %f2
; CHECK-VECTOR-NEXT:    brasl %r14, __extendhfdf2@PLT
; CHECK-VECTOR-NEXT:    ldr %f10, %f0
; CHECK-VECTOR-NEXT:    ldr %f0, %f8
; CHECK-VECTOR-NEXT:    brasl %r14, __extendhfdf2@PLT
; CHECK-VECTOR-NEXT:    ldr %f8, %f0
; CHECK-VECTOR-NEXT:    ldr %f0, %f9
; CHECK-VECTOR-NEXT:    brasl %r14, __extendhfdf2@PLT
; CHECK-VECTOR-NEXT:    wfmadb %f0, %f0, %f8, %f10
; CHECK-VECTOR-NEXT:    brasl %r14, __truncdfhf2@PLT
; CHECK-VECTOR-NEXT:    ld %f8, 176(%r15) # 8-byte Reload
; CHECK-VECTOR-NEXT:    ld %f9, 168(%r15) # 8-byte Reload
; CHECK-VECTOR-NEXT:    ld %f10, 160(%r15) # 8-byte Reload
; CHECK-VECTOR-NEXT:    lmg %r14, %r15, 296(%r15)
; CHECK-VECTOR-NEXT:    br %r14
  %res = call half @llvm.experimental.constrained.fma.f16 (
                        half %f1, half %f2, half %acc,
                        metadata !"round.dynamic",
                        metadata !"fpexcept.strict") #0
  ret half %res
}

define float @f1(float %f1, float %f2, float %acc) #0 {
; CHECK-SCALAR-LABEL: f1:
; CHECK-SCALAR:       # %bb.0:
; CHECK-SCALAR-NEXT:    maebr %f4, %f0, %f2
; CHECK-SCALAR-NEXT:    ler %f0, %f4
; CHECK-SCALAR-NEXT:    br %r14
;
; CHECK-VECTOR-LABEL: f1:
; CHECK-VECTOR:       # %bb.0:
; CHECK-VECTOR-NEXT:    wfmasb %f0, %f0, %f2, %f4
; CHECK-VECTOR-NEXT:    br %r14
  %res = call float @llvm.experimental.constrained.fma.f32 (
                        float %f1, float %f2, float %acc,
                        metadata !"round.dynamic",
                        metadata !"fpexcept.strict") #0
  ret float %res
}

define float @f2(float %f1, ptr %ptr, float %acc) #0 {
; CHECK-SCALAR-LABEL: f2:
; CHECK-SCALAR:       # %bb.0:
; CHECK-SCALAR-NEXT:    maeb %f2, %f0, 0(%r2)
; CHECK-SCALAR-NEXT:    ler %f0, %f2
; CHECK-SCALAR-NEXT:    br %r14
;
; CHECK-VECTOR-LABEL: f2:
; CHECK-VECTOR:       # %bb.0:
; CHECK-VECTOR-NEXT:    maeb %f2, %f0, 0(%r2)
; CHECK-VECTOR-NEXT:    ldr %f0, %f2
; CHECK-VECTOR-NEXT:    br %r14
  %f2 = load float, ptr %ptr
  %res = call float @llvm.experimental.constrained.fma.f32 (
                        float %f1, float %f2, float %acc,
                        metadata !"round.dynamic",
                        metadata !"fpexcept.strict") #0
  ret float %res
}

define float @f3(float %f1, ptr %base, float %acc) #0 {
; CHECK-SCALAR-LABEL: f3:
; CHECK-SCALAR:       # %bb.0:
; CHECK-SCALAR-NEXT:    maeb %f2, %f0, 4092(%r2)
; CHECK-SCALAR-NEXT:    ler %f0, %f2
; CHECK-SCALAR-NEXT:    br %r14
;
; CHECK-VECTOR-LABEL: f3:
; CHECK-VECTOR:       # %bb.0:
; CHECK-VECTOR-NEXT:    maeb %f2, %f0, 4092(%r2)
; CHECK-VECTOR-NEXT:    ldr %f0, %f2
; CHECK-VECTOR-NEXT:    br %r14
  %ptr = getelementptr float, ptr %base, i64 1023
  %f2 = load float, ptr %ptr
  %res = call float @llvm.experimental.constrained.fma.f32 (
                        float %f1, float %f2, float %acc,
                        metadata !"round.dynamic",
                        metadata !"fpexcept.strict") #0
  ret float %res
}

define float @f4(float %f1, ptr %base, float %acc) #0 {
; The important thing here is that we don't generate an out-of-range
; displacement.  Other sequences besides this one would be OK.
;
; CHECK-SCALAR-LABEL: f4:
; CHECK-SCALAR:       # %bb.0:
; CHECK-SCALAR-NEXT:    aghi %r2, 4096
; CHECK-SCALAR-NEXT:    maeb %f2, %f0, 0(%r2)
; CHECK-SCALAR-NEXT:    ler %f0, %f2
; CHECK-SCALAR-NEXT:    br %r14
;
; CHECK-VECTOR-LABEL: f4:
; CHECK-VECTOR:       # %bb.0:
; CHECK-VECTOR-NEXT:    aghi %r2, 4096
; CHECK-VECTOR-NEXT:    maeb %f2, %f0, 0(%r2)
; CHECK-VECTOR-NEXT:    ldr %f0, %f2
; CHECK-VECTOR-NEXT:    br %r14
  %ptr = getelementptr float, ptr %base, i64 1024
  %f2 = load float, ptr %ptr
  %res = call float @llvm.experimental.constrained.fma.f32 (
                        float %f1, float %f2, float %acc,
                        metadata !"round.dynamic",
                        metadata !"fpexcept.strict") #0
  ret float %res
}

define float @f5(float %f1, ptr %base, float %acc) #0 {
; Here too the important thing is that we don't generate an out-of-range
; displacement.  Other sequences besides this one would be OK.
;
; CHECK-SCALAR-LABEL: f5:
; CHECK-SCALAR:       # %bb.0:
; CHECK-SCALAR-NEXT:    aghi %r2, -4
; CHECK-SCALAR-NEXT:    maeb %f2, %f0, 0(%r2)
; CHECK-SCALAR-NEXT:    ler %f0, %f2
; CHECK-SCALAR-NEXT:    br %r14
;
; CHECK-VECTOR-LABEL: f5:
; CHECK-VECTOR:       # %bb.0:
; CHECK-VECTOR-NEXT:    aghi %r2, -4
; CHECK-VECTOR-NEXT:    maeb %f2, %f0, 0(%r2)
; CHECK-VECTOR-NEXT:    ldr %f0, %f2
; CHECK-VECTOR-NEXT:    br %r14
  %ptr = getelementptr float, ptr %base, i64 -1
  %f2 = load float, ptr %ptr
  %res = call float @llvm.experimental.constrained.fma.f32 (
                        float %f1, float %f2, float %acc,
                        metadata !"round.dynamic",
                        metadata !"fpexcept.strict") #0
  ret float %res
}

define float @f6(float %f1, ptr %base, i64 %index, float %acc) #0 {
; CHECK-SCALAR-LABEL: f6:
; CHECK-SCALAR:       # %bb.0:
; CHECK-SCALAR-NEXT:    sllg %r1, %r3, 2
; CHECK-SCALAR-NEXT:    maeb %f2, %f0, 0(%r1,%r2)
; CHECK-SCALAR-NEXT:    ler %f0, %f2
; CHECK-SCALAR-NEXT:    br %r14
;
; CHECK-VECTOR-LABEL: f6:
; CHECK-VECTOR:       # %bb.0:
; CHECK-VECTOR-NEXT:    sllg %r1, %r3, 2
; CHECK-VECTOR-NEXT:    maeb %f2, %f0, 0(%r1,%r2)
; CHECK-VECTOR-NEXT:    ldr %f0, %f2
; CHECK-VECTOR-NEXT:    br %r14
  %ptr = getelementptr float, ptr %base, i64 %index
  %f2 = load float, ptr %ptr
  %res = call float @llvm.experimental.constrained.fma.f32 (
                        float %f1, float %f2, float %acc,
                        metadata !"round.dynamic",
                        metadata !"fpexcept.strict") #0
  ret float %res
}

define float @f7(float %f1, ptr %base, i64 %index, float %acc) #0 {
; CHECK-SCALAR-LABEL: f7:
; CHECK-SCALAR:       # %bb.0:
; CHECK-SCALAR-NEXT:    sllg %r1, %r3, 2
; CHECK-SCALAR-NEXT:    maeb %f2, %f0, 4092(%r2,%r1)
; CHECK-SCALAR-NEXT:    ler %f0, %f2
; CHECK-SCALAR-NEXT:    br %r14
;
; CHECK-VECTOR-LABEL: f7:
; CHECK-VECTOR:       # %bb.0:
; CHECK-VECTOR-NEXT:    sllg %r1, %r3, 2
; CHECK-VECTOR-NEXT:    maeb %f2, %f0, 4092(%r2,%r1)
; CHECK-VECTOR-NEXT:    ldr %f0, %f2
; CHECK-VECTOR-NEXT:    br %r14
  %index2 = add i64 %index, 1023
  %ptr = getelementptr float, ptr %base, i64 %index2
  %f2 = load float, ptr %ptr
  %res = call float @llvm.experimental.constrained.fma.f32 (
                        float %f1, float %f2, float %acc,
                        metadata !"round.dynamic",
                        metadata !"fpexcept.strict") #0
  ret float %res
}

define float @f8(float %f1, ptr %base, i64 %index, float %acc) #0 {
; CHECK-SCALAR-LABEL: f8:
; CHECK-SCALAR:       # %bb.0:
; CHECK-SCALAR-NEXT:    sllg %r1, %r3, 2
; CHECK-SCALAR-NEXT:    lay %r1, 4096(%r2,%r1)
; CHECK-SCALAR-NEXT:    maeb %f2, %f0, 0(%r1)
; CHECK-SCALAR-NEXT:    ler %f0, %f2
; CHECK-SCALAR-NEXT:    br %r14
;
; CHECK-VECTOR-LABEL: f8:
; CHECK-VECTOR:       # %bb.0:
; CHECK-VECTOR-NEXT:    sllg %r1, %r3, 2
; CHECK-VECTOR-NEXT:    lay %r1, 4096(%r2,%r1)
; CHECK-VECTOR-NEXT:    maeb %f2, %f0, 0(%r1)
; CHECK-VECTOR-NEXT:    ldr %f0, %f2
; CHECK-VECTOR-NEXT:    br %r14
  %index2 = add i64 %index, 1024
  %ptr = getelementptr float, ptr %base, i64 %index2
  %f2 = load float, ptr %ptr
  %res = call float @llvm.experimental.constrained.fma.f32 (
                        float %f1, float %f2, float %acc,
                        metadata !"round.dynamic",
                        metadata !"fpexcept.strict") #0
  ret float %res
}

attributes #0 = { strictfp }
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
