; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=s390x-unknown-linux | FileCheck %s

; SystemZ (s390x) lowers i128 div/rem pairs through fused libcalls.

define void @sdivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; CHECK-LABEL: sdivrem_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r6, %r15, 48(%r15)
; CHECK-NEXT:    .cfi_offset %r6, -112
; CHECK-NEXT:    .cfi_offset %r7, -104
; CHECK-NEXT:    .cfi_offset %r8, -96
; CHECK-NEXT:    .cfi_offset %r9, -88
; CHECK-NEXT:    .cfi_offset %r10, -80
; CHECK-NEXT:    .cfi_offset %r11, -72
; CHECK-NEXT:    .cfi_offset %r12, -64
; CHECK-NEXT:    .cfi_offset %r13, -56
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -256
; CHECK-NEXT:    .cfi_def_cfa_offset 416
; CHECK-NEXT:    lgr %r13, %r3
; CHECK-NEXT:    lgr %r12, %r2
; CHECK-NEXT:    lg %r11, 8(%r5)
; CHECK-NEXT:    lg %r10, 0(%r5)
; CHECK-NEXT:    lg %r9, 8(%r4)
; CHECK-NEXT:    lg %r8, 0(%r4)
; CHECK-NEXT:    stg %r11, 168(%r15)
; CHECK-NEXT:    stg %r10, 160(%r15)
; CHECK-NEXT:    stg %r9, 184(%r15)
; CHECK-NEXT:    la %r2, 192(%r15)
; CHECK-NEXT:    la %r3, 176(%r15)
; CHECK-NEXT:    la %r4, 160(%r15)
; CHECK-NEXT:    stg %r8, 176(%r15)
; CHECK-NEXT:    brasl %r14, __divti3@PLT
; CHECK-NEXT:    lg %r7, 192(%r15)
; CHECK-NEXT:    lg %r6, 200(%r15)
; CHECK-NEXT:    stg %r11, 216(%r15)
; CHECK-NEXT:    stg %r10, 208(%r15)
; CHECK-NEXT:    stg %r9, 232(%r15)
; CHECK-NEXT:    la %r2, 240(%r15)
; CHECK-NEXT:    la %r3, 224(%r15)
; CHECK-NEXT:    la %r4, 208(%r15)
; CHECK-NEXT:    stg %r8, 224(%r15)
; CHECK-NEXT:    brasl %r14, __modti3@PLT
; CHECK-NEXT:    lg %r0, 248(%r15)
; CHECK-NEXT:    lg %r1, 240(%r15)
; CHECK-NEXT:    stg %r6, 8(%r12)
; CHECK-NEXT:    stg %r7, 0(%r12)
; CHECK-NEXT:    stg %r0, 8(%r13)
; CHECK-NEXT:    stg %r1, 0(%r13)
; CHECK-NEXT:    lmg %r6, %r15, 304(%r15)
; CHECK-NEXT:    br %r14
  %q = sdiv i128 %n, %d
  %r = srem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}

define void @udivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; CHECK-LABEL: udivrem_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r6, %r15, 48(%r15)
; CHECK-NEXT:    .cfi_offset %r6, -112
; CHECK-NEXT:    .cfi_offset %r7, -104
; CHECK-NEXT:    .cfi_offset %r8, -96
; CHECK-NEXT:    .cfi_offset %r9, -88
; CHECK-NEXT:    .cfi_offset %r10, -80
; CHECK-NEXT:    .cfi_offset %r11, -72
; CHECK-NEXT:    .cfi_offset %r12, -64
; CHECK-NEXT:    .cfi_offset %r13, -56
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -256
; CHECK-NEXT:    .cfi_def_cfa_offset 416
; CHECK-NEXT:    lgr %r13, %r3
; CHECK-NEXT:    lgr %r12, %r2
; CHECK-NEXT:    lg %r11, 8(%r5)
; CHECK-NEXT:    lg %r10, 0(%r5)
; CHECK-NEXT:    lg %r9, 8(%r4)
; CHECK-NEXT:    lg %r8, 0(%r4)
; CHECK-NEXT:    stg %r11, 168(%r15)
; CHECK-NEXT:    stg %r10, 160(%r15)
; CHECK-NEXT:    stg %r9, 184(%r15)
; CHECK-NEXT:    la %r2, 192(%r15)
; CHECK-NEXT:    la %r3, 176(%r15)
; CHECK-NEXT:    la %r4, 160(%r15)
; CHECK-NEXT:    stg %r8, 176(%r15)
; CHECK-NEXT:    brasl %r14, __udivti3@PLT
; CHECK-NEXT:    lg %r7, 192(%r15)
; CHECK-NEXT:    lg %r6, 200(%r15)
; CHECK-NEXT:    stg %r11, 216(%r15)
; CHECK-NEXT:    stg %r10, 208(%r15)
; CHECK-NEXT:    stg %r9, 232(%r15)
; CHECK-NEXT:    la %r2, 240(%r15)
; CHECK-NEXT:    la %r3, 224(%r15)
; CHECK-NEXT:    la %r4, 208(%r15)
; CHECK-NEXT:    stg %r8, 224(%r15)
; CHECK-NEXT:    brasl %r14, __umodti3@PLT
; CHECK-NEXT:    lg %r0, 248(%r15)
; CHECK-NEXT:    lg %r1, 240(%r15)
; CHECK-NEXT:    stg %r6, 8(%r12)
; CHECK-NEXT:    stg %r7, 0(%r12)
; CHECK-NEXT:    stg %r0, 8(%r13)
; CHECK-NEXT:    stg %r1, 0(%r13)
; CHECK-NEXT:    lmg %r6, %r15, 304(%r15)
; CHECK-NEXT:    br %r14
  %q = udiv i128 %n, %d
  %r = urem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}
