; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; Test 128-bit multiplication on z13
;
; RUN: llc < %s -mtriple=s390x-linux-gnu -mcpu=z13 | FileCheck %s

; Multiplication.
define i128 @f1(i128 %a, i128 %b) {
; CHECK-LABEL: f1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r12, %r15, 96(%r15)
; CHECK-NEXT:    .cfi_offset %r12, -64
; CHECK-NEXT:    .cfi_offset %r13, -56
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    lg %r13, 8(%r3)
; CHECK-NEXT:    lg %r0, 8(%r4)
; CHECK-NEXT:    lgr %r1, %r13
; CHECK-NEXT:    mlgr %r12, %r0
; CHECK-NEXT:    msg %r1, 0(%r4)
; CHECK-NEXT:    msg %r0, 0(%r3)
; CHECK-NEXT:    agr %r1, %r12
; CHECK-NEXT:    agr %r0, %r1
; CHECK-NEXT:    stg %r13, 8(%r2)
; CHECK-NEXT:    stg %r0, 0(%r2)
; CHECK-NEXT:    lmg %r12, %r15, 96(%r15)
; CHECK-NEXT:    br %r14
  %res = mul i128 %a, %b
  ret i128 %res
}
