# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=s390x-linux-gnu -sink-insts-to-avoid-spills -verify-machineinstrs -run-pass=machine-sink -o - %s | FileCheck %s

# Test kill flags are cleared after sinking operations into cycle during MachineLICM.

---
name:            c
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: c
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gr64bit = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr64bit = COPY [[DEF]]
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gr64bit = COPY [[COPY]]
  ; CHECK-NEXT:   INLINEASM &"", 1 /* sideeffect attdialect */, implicit [[COPY1]], implicit [[DEF]]
  ; CHECK-NEXT:   J %bb.1
  bb.0:
    successors: %bb.1(0x80000000)

    %7:gr64bit = IMPLICIT_DEF
    %8:gr64bit = COPY %7
    %9:gr64bit = COPY killed %8

  bb.1:
    successors: %bb.1(0x80000000)

    INLINEASM &"", 1 , implicit %9, implicit %7
    J %bb.1

...
