; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=s390x < %s | FileCheck %s -check-prefix S390X

define void @memop_soft_float() "use-soft-float"="true" {
; S390X-LABEL: memop_soft_float:
; S390X:       # %bb.0:
; S390X-NEXT:    stmg %r14, %r15, 112(%r15)
; S390X-NEXT:    .cfi_offset %r14, -48
; S390X-NEXT:    .cfi_offset %r15, -40
; S390X-NEXT:    aghi %r15, -160
; S390X-NEXT:    .cfi_def_cfa_offset 320
; S390X-NEXT:    lghi %r2, 0
; S390X-NEXT:    lghi %r3, 0
; S390X-NEXT:    lghi %r4, 32
; S390X-NEXT:    brasl %r14, memcpy@PLT
; S390X-NEXT:    lghi %r2, 0
; S390X-NEXT:    lhi %r3, 0
; S390X-NEXT:    lghi %r4, 32
; S390X-NEXT:    brasl %r14, memset@PLT
; S390X-NEXT:    lmg %r14, %r15, 272(%r15)
; S390X-NEXT:    br %r14
    call void @llvm.memcpy.p0.p0.i32(ptr null, ptr null, i32 32, i1 true)
    call void @llvm.memset.p0.i32(ptr null, i8 0, i32 32, i1 true)
    ret void
}

define void @memop_noimplicitfloat() noimplicitfloat {
; S390X-LABEL: memop_noimplicitfloat:
; S390X:       # %bb.0:
; S390X-NEXT:    stmg %r14, %r15, 112(%r15)
; S390X-NEXT:    .cfi_offset %r14, -48
; S390X-NEXT:    .cfi_offset %r15, -40
; S390X-NEXT:    aghi %r15, -160
; S390X-NEXT:    .cfi_def_cfa_offset 320
; S390X-NEXT:    lghi %r2, 0
; S390X-NEXT:    lghi %r3, 0
; S390X-NEXT:    lghi %r4, 32
; S390X-NEXT:    brasl %r14, memcpy@PLT
; S390X-NEXT:    lghi %r2, 0
; S390X-NEXT:    lhi %r3, 0
; S390X-NEXT:    lghi %r4, 32
; S390X-NEXT:    brasl %r14, memset@PLT
; S390X-NEXT:    lmg %r14, %r15, 272(%r15)
; S390X-NEXT:    br %r14
    call void @llvm.memcpy.p0.p0.i32(ptr null, ptr null, i32 32, i1 true)
    call void @llvm.memset.p0.i32(ptr null, i8 0, i32 32, i1 true)
    ret void
}

declare void @llvm.memcpy.p0.p0.i32(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i32, i1 immarg) nocallback nofree nounwind willreturn memory(argmem: readwrite)
declare void @llvm.memset.p0.i32(ptr nocapture writeonly, i8, i32, i1 immarg) nocallback nofree nounwind willreturn memory(argmem: write)
