# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc %s -mtriple=s390x-ibm-linux -mcpu=z15 -run-pass=prologepilog -o - | FileCheck %s
---
name:            repro
tracksRegLiveness: true
stack:
  - { id: 0, offset: 0, size: 16384, callee-saved-restored: true }
body:             |
  bb.0 :
    liveins: $r2d, $r3d

    ; CHECK-LABEL: name: repro
    ; CHECK: liveins: $r2d, $r3d, $r6d, $r15d, $r7d, $r8d, $r9d, $r10d, $r11d, $r12d, $r13d, $r14d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: STMG killed $r6d, killed $r15d, $r15d, 48, implicit killed $r7d, implicit killed $r8d, implicit killed $r9d, implicit killed $r10d, implicit killed $r11d, implicit killed $r12d, implicit killed $r13d, implicit killed $r14d
    ; CHECK-NEXT: CFI_INSTRUCTION offset $r6d, -112
    ; CHECK-NEXT: CFI_INSTRUCTION offset $r7d, -104
    ; CHECK-NEXT: CFI_INSTRUCTION offset $r8d, -96
    ; CHECK-NEXT: CFI_INSTRUCTION offset $r9d, -88
    ; CHECK-NEXT: CFI_INSTRUCTION offset $r10d, -80
    ; CHECK-NEXT: CFI_INSTRUCTION offset $r11d, -72
    ; CHECK-NEXT: CFI_INSTRUCTION offset $r12d, -64
    ; CHECK-NEXT: CFI_INSTRUCTION offset $r13d, -56
    ; CHECK-NEXT: CFI_INSTRUCTION offset $r14d, -48
    ; CHECK-NEXT: CFI_INSTRUCTION offset $r15d, -40
    ; CHECK-NEXT: $r15d = AGHI $r15d, -16560, implicit-def dead $cc
    ; CHECK-NEXT: CFI_INSTRUCTION def_cfa_offset 16720
    ; CHECK-NEXT: renamable $r0d = COPY $r3d
    ; CHECK-NEXT: STG killed $r2d, $r15d, 168, $noreg :: (store (s64) into %stack.1)
    ; CHECK-NEXT: $r2d = LAY $r15d, 4096, $noreg
    ; CHECK-NEXT: INLINEASM &"  lg $0, $1\0A\09", sideeffect mayload maystore attdialect, regdef-ec:GR64Bit, def early-clobber renamable $r1d, mem:m, killed $r2d, 1080, $noreg, clobber, implicit-def dead early-clobber $r3d, clobber, implicit-def dead early-clobber $r4d, clobber, implicit-def dead early-clobber $r5d, clobber, implicit-def dead early-clobber $r6d, clobber, implicit-def dead early-clobber $r7d, clobber, implicit-def dead early-clobber $r8d, clobber, implicit-def dead early-clobber $r9d, clobber, implicit-def dead early-clobber $r10d, clobber, implicit-def dead early-clobber $r11d, clobber, implicit-def dead early-clobber $r12d, clobber, implicit-def dead early-clobber $r13d, clobber, implicit-def dead early-clobber $r14d, clobber, implicit-def dead early-clobber $cc
    ; CHECK-NEXT: $r2d = LG $r15d, 168, $noreg :: (load (s64) from %stack.1)
    ; CHECK-NEXT: renamable $r2d = AGR killed renamable $r2d, killed renamable $r0d, implicit-def dead $cc
    ; CHECK-NEXT: renamable $r2d = AGR killed renamable $r2d, killed renamable $r1d, implicit-def dead $cc
    ; CHECK-NEXT: $r6d, $r15d = LMG $r15d, 16608, implicit-def $r7d, implicit-def $r8d, implicit-def $r9d, implicit-def $r10d, implicit-def $r11d, implicit-def $r12d, implicit-def $r13d, implicit-def $r14d
    ; CHECK-NEXT: Return implicit $r2d
    renamable $r0d = COPY $r3d
    INLINEASM &"  lg $0, $1\0A\09", 25 /* sideeffect mayload maystore attdialect */, 1179659 /* regdef-ec:GR64Bit */, def early-clobber renamable $r1d, 262174 /* mem:m */, %stack.0, 5000, $noreg, 12 /* clobber */, implicit-def dead early-clobber $r3d, 12 /* clobber */, implicit-def dead early-clobber $r4d, 12 /* clobber */, implicit-def dead early-clobber $r5d, 12 /* clobber */, implicit-def dead early-clobber $r6d, 12 /* clobber */, implicit-def dead early-clobber $r7d, 12 /* clobber */, implicit-def dead early-clobber $r8d, 12 /* clobber */, implicit-def dead early-clobber $r9d, 12 /* clobber */, implicit-def dead early-clobber $r10d, 12 /* clobber */, implicit-def dead early-clobber $r11d, 12 /* clobber */, implicit-def dead early-clobber $r12d, 12 /* clobber */, implicit-def dead early-clobber $r13d, 12 /* clobber */, implicit-def dead early-clobber $r14d, 12 /* clobber */, implicit-def dead early-clobber $cc
    renamable $r2d = AGR killed renamable $r2d, killed renamable $r0d, implicit-def dead $cc
    renamable $r2d = AGR killed renamable $r2d, killed renamable $r1d, implicit-def dead $cc
    Return implicit $r2d
...
