; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=s390x-linux-gnu -mcpu=z16 | FileCheck %s
;
; Test fp16-vector stack arguments.

define void @bar(<8 x half>, <8 x half>, <8 x half>, <8 x half>,
; CHECK-LABEL: bar:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl %v0, 176(%r15), 3
; CHECK-NEXT:    lg %r0, 168(%r15)
; CHECK-NEXT:    vlrepg %v1, 160(%r15)
; CHECK-NEXT:    vsteh %v1, 0(%r2), 0
; CHECK-NEXT:    stg %r0, 0(%r3)
; CHECK-NEXT:    vst %v0, 0(%r4), 3
; CHECK-NEXT:    br %r14
                 <8 x half>, <8 x half>, <8 x half>, <8 x half>,
                 <1 x half> %A, <4 x half> %B, <8 x half> %C,
                 ptr %Dst0, ptr %Dst1, ptr %Dst2) {
  store <1 x half> %A, ptr %Dst0
  store <4 x half> %B, ptr %Dst1
  store <8 x half> %C, ptr %Dst2
  ret void
}

define void @foo(<1 x half> %A, <4 x half> %B, <8 x half> %C) {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -192
; CHECK-NEXT:    .cfi_def_cfa_offset 352
; CHECK-NEXT:    vst %v28, 176(%r15), 3
; CHECK-NEXT:    vmrhg %v0, %v24, %v26
; CHECK-NEXT:    vgbm %v24, 0
; CHECK-NEXT:    vgbm %v26, 0
; CHECK-NEXT:    vgbm %v28, 0
; CHECK-NEXT:    vgbm %v30, 0
; CHECK-NEXT:    vgbm %v25, 0
; CHECK-NEXT:    vgbm %v27, 0
; CHECK-NEXT:    vgbm %v29, 0
; CHECK-NEXT:    vgbm %v31, 0
; CHECK-NEXT:    vst %v0, 160(%r15), 3
; CHECK-NEXT:    brasl %r14, bar@PLT
; CHECK-NEXT:    lmg %r14, %r15, 304(%r15)
; CHECK-NEXT:    br %r14
  call void @bar(<8 x half> zeroinitializer, <8 x half> zeroinitializer,
                 <8 x half> zeroinitializer, <8 x half> zeroinitializer,
                 <8 x half> zeroinitializer, <8 x half> zeroinitializer,
                 <8 x half> zeroinitializer, <8 x half> zeroinitializer,
                 <1 x half> %A, <4 x half> %B, <8 x half> %C)
  ret void
}
