; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S  -passes='separate-const-offset-from-gep<lower-gep>' %s | FileCheck %s

define ptr @xor-const-test(i32 %0) {
; CHECK-LABEL: define ptr @xor-const-test(
; CHECK-SAME: i32 [[TMP0:%.*]]) {
; CHECK-NEXT:    [[BASE:%.*]] = alloca [4 x i32], align 16
; CHECK-NEXT:    [[XOR1:%.*]] = xor i64 0, 0
; CHECK-NEXT:    [[TMP3:%.*]] = shl i64 [[XOR1]], 2
; CHECK-NEXT:    [[UGLYGEP:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[TMP3]]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[UGLYGEP]], i64 12
; CHECK-NEXT:    ret ptr [[TMP2]]
;
  %base = alloca [4 x i32], align 16
  %xor = xor i64 0, 3
  %gep = getelementptr [4 x i32], ptr %base, i64 0, i64 %xor
  ret ptr %gep
}

define ptr @xor-const-test2(i32 %0) {
; CHECK-LABEL: define ptr @xor-const-test2(
; CHECK-SAME: i32 [[TMP0:%.*]]) {
; CHECK-NEXT:    [[BASE:%.*]] = alloca [4 x i32], align 16
; CHECK-NEXT:    [[XOR1:%.*]] = xor i64 2, 2
; CHECK-NEXT:    [[TMP2:%.*]] = shl i64 [[XOR1]], 2
; CHECK-NEXT:    [[UGLYGEP:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[TMP2]]
; CHECK-NEXT:    [[UGLYGEP2:%.*]] = getelementptr i8, ptr [[UGLYGEP]], i64 4
; CHECK-NEXT:    ret ptr [[UGLYGEP2]]
;
  %base = alloca [4 x i32], align 16
  %xor = xor i64 2, 3
  %gep = getelementptr [4 x i32], ptr %base, i64 0, i64 %xor
  ret ptr %gep
}
