; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S  -passes='separate-const-offset-from-gep<lower-gep>' %s | FileCheck %s

define ptr @xor_decompose_constant_base_op(i32 %a) {
; CHECK-LABEL: define ptr @xor_decompose_constant_base_op(
; CHECK-SAME: i32 [[A:%.*]]) {
; CHECK-NEXT:    [[BASE:%.*]] = alloca [4 x i32], align 16
; CHECK-NEXT:    [[UGLYGEP:%.*]] = getelementptr i8, ptr [[BASE]], i64 12
; CHECK-NEXT:    ret ptr [[UGLYGEP]]
;
  %base = alloca [4 x i32], align 16
  %xor = xor i64 0, 3
  %gep = getelementptr [4 x i32], ptr %base, i64 0, i64 %xor
  ret ptr %gep
}

define ptr @xor_decompose_constant_base_op_2(i32 %a) {
; CHECK-LABEL: define ptr @xor_decompose_constant_base_op_2(
; CHECK-SAME: i32 [[A:%.*]]) {
; CHECK-NEXT:    [[BASE:%.*]] = alloca [4 x i32], align 16
; CHECK-NEXT:    [[XOR1:%.*]] = xor i64 2, 2
; CHECK-NEXT:    [[TMP1:%.*]] = shl i64 [[XOR1]], 2
; CHECK-NEXT:    [[UGLYGEP:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[TMP1]]
; CHECK-NEXT:    [[UGLYGEP2:%.*]] = getelementptr i8, ptr [[UGLYGEP]], i64 4
; CHECK-NEXT:    ret ptr [[UGLYGEP2]]
;
  %base = alloca [4 x i32], align 16
  %xor = xor i64 2, 3
  %gep = getelementptr [4 x i32], ptr %base, i64 0, i64 %xor
  ret ptr %gep
}

define ptr @xor_decompose_constant_sign_bit(ptr %p, i32 %a) {
; CHECK-LABEL: define ptr @xor_decompose_constant_sign_bit(
; CHECK-SAME: ptr [[P:%.*]], i32 [[A:%.*]]) {
; CHECK-NEXT:    [[XOR:%.*]] = xor i32 [[A]], -1
; CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[XOR]] to i64
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds i32, ptr [[P]], i64 [[IDXPROM]]
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %xor = xor i32 %a, -1
  %gep = getelementptr inbounds i32, ptr %p, i32 %xor
  ret ptr %gep
}

define ptr @xor_decompose_casts_chain(i64 %x, ptr %p) {
; CHECK-LABEL: define ptr @xor_decompose_casts_chain(
; CHECK-SAME: i64 [[X:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:    [[Y:%.*]] = and i64 [[X]], 8589934592
; CHECK-NEXT:    [[XOR:%.*]] = xor i64 [[Y]], 12884901888
; CHECK-NEXT:    [[TRUNC:%.*]] = trunc i64 [[XOR]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[TRUNC]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = shl i64 [[TMP1]], 2
; CHECK-NEXT:    [[UGLYGEP:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP2]]
; CHECK-NEXT:    [[UGLYGEP2:%.*]] = getelementptr i8, ptr [[UGLYGEP]], i64 28
; CHECK-NEXT:    ret ptr [[UGLYGEP2]]
;
  %y = and i64 %x, 8589934592           ; bit 33 unknown, all others zero
  %xor = xor i64 %y, 12884901888        ; xor w/ 0x300000000: bit 32 (disjoint) | bit 33 (non-disjoint).
  %trunc = trunc i64 %xor to i32        ; Push 0.
  %expr = add nuw i32 %trunc, 7
  %idx = zext i32 %expr to i64
  %gep = getelementptr i32, ptr %p, i64 %idx
  ret ptr %gep
}

define ptr @xor_decompose_casts_chain_2(i32 %x, i32 %y, ptr %p) {
; CHECK-LABEL: define ptr @xor_decompose_casts_chain_2(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:    [[MASK:%.*]] = and i32 [[X]], 31
; CHECK-NEXT:    [[TMP1:%.*]] = sext i32 [[MASK]] to i64
; CHECK-NEXT:    [[XOR1:%.*]] = xor i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = shl i64 [[XOR1]], 2
; CHECK-NEXT:    [[UGLYGEP:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP2]]
; CHECK-NEXT:    [[UGLYGEP2:%.*]] = getelementptr i8, ptr [[UGLYGEP]], i64 128
; CHECK-NEXT:    ret ptr [[UGLYGEP2]]
;
  %mask = and i32 %x, 31
  %xor = xor i32 %mask, 33
  %idx = sext i32 %xor to i64
  %gep = getelementptr i32, ptr %p, i64 %idx
  ret ptr %gep
}

define <4 x ptr> @xor_decompose_gep_vector(<4 x ptr> %p, i32 %x) {
; CHECK-LABEL: define <4 x ptr> @xor_decompose_gep_vector(
; CHECK-SAME: <4 x ptr> [[P:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:    [[XOR:%.*]] = xor i32 [[X]], 33
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i32, <4 x ptr> [[P]], i32 [[XOR]]
; CHECK-NEXT:    ret <4 x ptr> [[GEP]]
;
  %xor = xor i32 %x, 33
  %gep = getelementptr i32, <4 x ptr> %p, i32 %xor
  ret <4 x ptr> %gep
}
