static_library("Register") {
  output_name = "lldbRegister"
  configs += [ "//llvm/utils/gn/build:lldb_code" ]
  deps = [
    "//lldb/source/Utility",
    "//llvm/lib/Support",
    "//llvm/lib/TargetParser",
  ]

  # Uses source-relative includes for own headers.
  include_dirs = [ "//lldb/source" ]
  sources = [
    "RegisterInfoFreeBSD_i386.cpp",
    "RegisterInfoFreeBSD_powerpc.cpp",
    "RegisterInfoFreeBSD_x86_64.cpp",
    "RegisterInfoLinux_i386.cpp",
    "RegisterInfoLinux_s390x.cpp",
    "RegisterInfoLinux_x86_64.cpp",
    "RegisterInfoNetBSD_i386.cpp",
    "RegisterInfoNetBSD_x86_64.cpp",
    "RegisterInfoOpenBSD_i386.cpp",
    "RegisterInfoOpenBSD_x86_64.cpp",
    "RegisterInfoWindows_i386.cpp",
    "RegisterInfoWindows_x86_64.cpp",
    "RegisterContext_x86.cpp",
    "RegisterInfoPOSIXDynamic_riscv32.cpp",
    "RegisterInfoPOSIX_arm.cpp",
    "RegisterInfoPOSIX_arm64.cpp",
    "RegisterInfoPOSIX_loongarch64.cpp",
    "RegisterInfoPOSIX_ppc64.cpp",
    "RegisterInfoPOSIX_ppc64le.cpp",
    "RegisterInfoPOSIX_riscv32.cpp",
    "RegisterInfoPOSIX_riscv64.cpp",
    "RegisterInfos_x86_64_with_base_shared.cpp",
    "RegisterTypeDetector_arm64.cpp",
  ]
}

static_library("Utility") {
  output_name = "lldbPluginProcessUtility"
  configs += [ "//llvm/utils/gn/build:lldb_code" ]
  deps = [
    ":Register",
    #"//lldb/source/Breakpoint", # 3-hop dependency cycle.
    "//lldb/source/Core",
    "//lldb/source/DataFormatters",
    "//lldb/source/Expression",
    "//lldb/source/Host",
    "//lldb/source/Symbol",

    #"//lldb/source/Target", # Dependency cycle.
    "//lldb/source/Utility",
    "//lldb/source/ValueObject",
    "//llvm/lib/Support",
    "//llvm/lib/TargetParser",
  ]

  # Uses source-relative includes for own headers.
  include_dirs = [ "//lldb/source" ]
  sources = [
    "AuxVector.cpp",
    "FreeBSDSignals.cpp",
    "GDBRemoteSignals.cpp",
    "HistoryThread.cpp",
    "HistoryUnwind.cpp",
    "InferiorCallPOSIX.cpp",
    "LinuxProcMaps.cpp",
    "LinuxSignals.cpp",
    "MemoryTagManagerAArch64MTE.cpp",
    "NativeProcessSoftwareSingleStep.cpp",
    "NativeRegisterContextDBReg.cpp",
    "NativeRegisterContextDBReg_arm.cpp",
    "NativeRegisterContextDBReg_arm64.cpp",
    "NativeRegisterContextDBReg_loongarch.cpp",
    "NativeRegisterContextDBReg_x86.cpp",
    "NativeRegisterContextRegisterInfo.cpp",
    "NetBSDSignals.cpp",
    "OpenBSDSignals.cpp",
    "RegisterContextDarwin_arm.cpp",
    "RegisterContextDarwin_arm64.cpp",
    "RegisterContextDarwin_riscv32.cpp",
    "RegisterContextDarwin_x86_64.cpp",
    "RegisterContextDummy.cpp",
    "RegisterContextHistory.cpp",
    "RegisterContextMach_arm.cpp",
    "RegisterContextMach_x86_64.cpp",
    "RegisterContextMemory.cpp",
    "RegisterContextPOSIX_arm.cpp",
    "RegisterContextPOSIX_arm64.cpp",
    "RegisterContextPOSIX_loongarch64.cpp",
    "RegisterContextPOSIX_powerpc.cpp",
    "RegisterContextPOSIX_ppc64le.cpp",
    "RegisterContextPOSIX_riscv32.cpp",
    "RegisterContextPOSIX_riscv64.cpp",
    "RegisterContextPOSIX_s390x.cpp",
    "RegisterContextPOSIX_x86.cpp",
    "RegisterContextThreadMemory.cpp",
    "StopInfoMachException.cpp",
    "ThreadMemory.cpp",
  ]
}
