; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s  -mtriple=arm-linux-gnueabi | FileCheck %s --check-prefix=NOREGALLOC
; RUN: llc < %s  -mtriple=arm-linux-gnueabi -regalloc=basic | FileCheck %s --check-prefix=REGALLOC

@.str = private constant [1 x i8] zeroinitializer, align 1

define void @g() {
; NOREGALLOC-LABEL: g:
; NOREGALLOC:       @ %bb.0: @ %entry
; NOREGALLOC-NEXT:    .save {r11, lr}
; NOREGALLOC-NEXT:    push {r11, lr}
; NOREGALLOC-NEXT:    .pad #16
; NOREGALLOC-NEXT:    sub sp, sp, #16
; NOREGALLOC-NEXT:    mov r0, #1048576
; NOREGALLOC-NEXT:    mov r1, #0
; NOREGALLOC-NEXT:    orr r0, r0, #1073741824
; NOREGALLOC-NEXT:    str r0, [sp, #12]
; NOREGALLOC-NEXT:    mov r0, #3
; NOREGALLOC-NEXT:    str r1, [sp, #8]
; NOREGALLOC-NEXT:    str r0, [sp]
; NOREGALLOC-NEXT:    mov r1, #1
; NOREGALLOC-NEXT:    ldr r0, .LCPI0_0
; NOREGALLOC-NEXT:    mov r2, #0
; NOREGALLOC-NEXT:    mov r3, #1073741824
; NOREGALLOC-NEXT:    bl f
; NOREGALLOC-NEXT:    add sp, sp, #16
; NOREGALLOC-NEXT:    pop {r11, lr}
; NOREGALLOC-NEXT:    mov pc, lr
; NOREGALLOC-NEXT:    .p2align 2
; NOREGALLOC-NEXT:  @ %bb.1:
; NOREGALLOC-NEXT:  .LCPI0_0:
; NOREGALLOC-NEXT:    .long .L.str
;
; REGALLOC-LABEL: g:
; REGALLOC:       @ %bb.0: @ %entry
; REGALLOC-NEXT:    .save {r11, lr}
; REGALLOC-NEXT:    push {r11, lr}
; REGALLOC-NEXT:    .pad #16
; REGALLOC-NEXT:    sub sp, sp, #16
; REGALLOC-NEXT:    mov r1, #1048576
; REGALLOC-NEXT:    mov r0, #0
; REGALLOC-NEXT:    orr r1, r1, #1073741824
; REGALLOC-NEXT:    str r0, [sp, #8]
; REGALLOC-NEXT:    mov r0, #3
; REGALLOC-NEXT:    str r1, [sp, #12]
; REGALLOC-NEXT:    str r0, [sp]
; REGALLOC-NEXT:    mov r1, #1
; REGALLOC-NEXT:    ldr r0, .LCPI0_0
; REGALLOC-NEXT:    mov r2, #0
; REGALLOC-NEXT:    mov r3, #1073741824
; REGALLOC-NEXT:    bl f
; REGALLOC-NEXT:    add sp, sp, #16
; REGALLOC-NEXT:    pop {r11, lr}
; REGALLOC-NEXT:    mov pc, lr
; REGALLOC-NEXT:    .p2align 2
; REGALLOC-NEXT:  @ %bb.1:
; REGALLOC-NEXT:  .LCPI0_0:
; REGALLOC-NEXT:    .long .L.str
entry:
;CHECK: [sp, #8]
        tail call  void (ptr, ...) @f(ptr @.str, i32 1, double 2.000000e+00, i32 3, double 4.000000e+00)
        ret void
}

declare void @f(ptr, ...)
