; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=arm-eabi -mattr=+v4t %s -o - | FileCheck %s  --check-prefixes=CHECK,CHECK-ARM
; RUN: llc -mtriple=thumbv6m-none-eabi %s -o - | FileCheck %s --check-prefixes=CHECK,CHECK-THUMB

;
; trunc(abs(sub(zext(a),zext(b)))) -> abdu(a,b)
;

define i8 @abd_ext_i8(i8 %a, i8 %b) nounwind {
; CHECK-ARM-LABEL: abd_ext_i8:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    and r1, r1, #255
; CHECK-ARM-NEXT:    and r0, r0, #255
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsbmi r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_ext_i8:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    uxtb r1, r1
; CHECK-THUMB-NEXT:    uxtb r0, r0
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    asrs r1, r0, #31
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %aext = zext i8 %a to i64
  %bext = zext i8 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 false)
  %trunc = trunc i64 %abs to i8
  ret i8 %trunc
}

define i8 @abd_ext_i8_i16(i8 %a, i16 %b) nounwind {
; CHECK-ARM-LABEL: abd_ext_i8_i16:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    mov r2, #255
; CHECK-ARM-NEXT:    and r0, r0, #255
; CHECK-ARM-NEXT:    orr r2, r2, #65280
; CHECK-ARM-NEXT:    and r1, r1, r2
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsbmi r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_ext_i8_i16:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    uxth r1, r1
; CHECK-THUMB-NEXT:    uxtb r0, r0
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    asrs r1, r0, #31
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %aext = zext i8 %a to i64
  %bext = zext i16 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 false)
  %trunc = trunc i64 %abs to i8
  ret i8 %trunc
}

define i8 @abd_ext_i8_undef(i8 %a, i8 %b) nounwind {
; CHECK-ARM-LABEL: abd_ext_i8_undef:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    and r1, r1, #255
; CHECK-ARM-NEXT:    and r0, r0, #255
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsbmi r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_ext_i8_undef:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    uxtb r1, r1
; CHECK-THUMB-NEXT:    uxtb r0, r0
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    asrs r1, r0, #31
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %aext = zext i8 %a to i64
  %bext = zext i8 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 true)
  %trunc = trunc i64 %abs to i8
  ret i8 %trunc
}

define i16 @abd_ext_i16(i16 %a, i16 %b) nounwind {
; CHECK-ARM-LABEL: abd_ext_i16:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    mov r2, #255
; CHECK-ARM-NEXT:    orr r2, r2, #65280
; CHECK-ARM-NEXT:    and r1, r1, r2
; CHECK-ARM-NEXT:    and r0, r0, r2
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsbmi r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_ext_i16:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    uxth r1, r1
; CHECK-THUMB-NEXT:    uxth r0, r0
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    asrs r1, r0, #31
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %aext = zext i16 %a to i64
  %bext = zext i16 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 false)
  %trunc = trunc i64 %abs to i16
  ret i16 %trunc
}

define i16 @abd_ext_i16_i32(i16 %a, i32 %b) nounwind {
; CHECK-ARM-LABEL: abd_ext_i16_i32:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    mov r2, #255
; CHECK-ARM-NEXT:    orr r2, r2, #65280
; CHECK-ARM-NEXT:    and r0, r0, r2
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsblo r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_ext_i16_i32:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    uxth r0, r0
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    sbcs r1, r1
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %aext = zext i16 %a to i64
  %bext = zext i32 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 false)
  %trunc = trunc i64 %abs to i16
  ret i16 %trunc
}

define i16 @abd_ext_i16_undef(i16 %a, i16 %b) nounwind {
; CHECK-ARM-LABEL: abd_ext_i16_undef:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    mov r2, #255
; CHECK-ARM-NEXT:    orr r2, r2, #65280
; CHECK-ARM-NEXT:    and r1, r1, r2
; CHECK-ARM-NEXT:    and r0, r0, r2
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsbmi r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_ext_i16_undef:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    uxth r1, r1
; CHECK-THUMB-NEXT:    uxth r0, r0
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    asrs r1, r0, #31
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %aext = zext i16 %a to i64
  %bext = zext i16 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 true)
  %trunc = trunc i64 %abs to i16
  ret i16 %trunc
}

define i32 @abd_ext_i32(i32 %a, i32 %b) nounwind {
; CHECK-ARM-LABEL: abd_ext_i32:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsblo r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_ext_i32:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    sbcs r1, r1
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %aext = zext i32 %a to i64
  %bext = zext i32 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 false)
  %trunc = trunc i64 %abs to i32
  ret i32 %trunc
}

define i32 @abd_ext_i32_i16(i32 %a, i16 %b) nounwind {
; CHECK-ARM-LABEL: abd_ext_i32_i16:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    mov r2, #255
; CHECK-ARM-NEXT:    orr r2, r2, #65280
; CHECK-ARM-NEXT:    and r1, r1, r2
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsblo r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_ext_i32_i16:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    uxth r1, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    sbcs r1, r1
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %aext = zext i32 %a to i64
  %bext = zext i16 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 false)
  %trunc = trunc i64 %abs to i32
  ret i32 %trunc
}

define i32 @abd_ext_i32_undef(i32 %a, i32 %b) nounwind {
; CHECK-ARM-LABEL: abd_ext_i32_undef:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsblo r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_ext_i32_undef:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    sbcs r1, r1
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %aext = zext i32 %a to i64
  %bext = zext i32 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 true)
  %trunc = trunc i64 %abs to i32
  ret i32 %trunc
}

define i64 @abd_ext_i64(i64 %a, i64 %b) nounwind {
; CHECK-ARM-LABEL: abd_ext_i64:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    subs r0, r0, r2
; CHECK-ARM-NEXT:    mov r12, #0
; CHECK-ARM-NEXT:    sbcs r1, r1, r3
; CHECK-ARM-NEXT:    adc r2, r12, #0
; CHECK-ARM-NEXT:    eor r2, r2, #1
; CHECK-ARM-NEXT:    rsb r2, r2, #0
; CHECK-ARM-NEXT:    eor r0, r0, r2
; CHECK-ARM-NEXT:    eor r1, r1, r2
; CHECK-ARM-NEXT:    subs r0, r0, r2
; CHECK-ARM-NEXT:    sbc r1, r1, r2
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_ext_i64:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    .save {r4, lr}
; CHECK-THUMB-NEXT:    push {r4, lr}
; CHECK-THUMB-NEXT:    movs r4, #0
; CHECK-THUMB-NEXT:    subs r0, r0, r2
; CHECK-THUMB-NEXT:    sbcs r1, r3
; CHECK-THUMB-NEXT:    adcs r4, r4
; CHECK-THUMB-NEXT:    movs r2, #1
; CHECK-THUMB-NEXT:    eors r2, r4
; CHECK-THUMB-NEXT:    rsbs r2, r2, #0
; CHECK-THUMB-NEXT:    eors r1, r2
; CHECK-THUMB-NEXT:    eors r0, r2
; CHECK-THUMB-NEXT:    subs r0, r0, r2
; CHECK-THUMB-NEXT:    sbcs r1, r2
; CHECK-THUMB-NEXT:    pop {r4, pc}
  %aext = zext i64 %a to i128
  %bext = zext i64 %b to i128
  %sub = sub i128 %aext, %bext
  %abs = call i128 @llvm.abs.i128(i128 %sub, i1 false)
  %trunc = trunc i128 %abs to i64
  ret i64 %trunc
}

define i64 @abd_ext_i64_undef(i64 %a, i64 %b) nounwind {
; CHECK-ARM-LABEL: abd_ext_i64_undef:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    subs r0, r0, r2
; CHECK-ARM-NEXT:    mov r12, #0
; CHECK-ARM-NEXT:    sbcs r1, r1, r3
; CHECK-ARM-NEXT:    adc r2, r12, #0
; CHECK-ARM-NEXT:    eor r2, r2, #1
; CHECK-ARM-NEXT:    rsb r2, r2, #0
; CHECK-ARM-NEXT:    eor r0, r0, r2
; CHECK-ARM-NEXT:    eor r1, r1, r2
; CHECK-ARM-NEXT:    subs r0, r0, r2
; CHECK-ARM-NEXT:    sbc r1, r1, r2
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_ext_i64_undef:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    .save {r4, lr}
; CHECK-THUMB-NEXT:    push {r4, lr}
; CHECK-THUMB-NEXT:    movs r4, #0
; CHECK-THUMB-NEXT:    subs r0, r0, r2
; CHECK-THUMB-NEXT:    sbcs r1, r3
; CHECK-THUMB-NEXT:    adcs r4, r4
; CHECK-THUMB-NEXT:    movs r2, #1
; CHECK-THUMB-NEXT:    eors r2, r4
; CHECK-THUMB-NEXT:    rsbs r2, r2, #0
; CHECK-THUMB-NEXT:    eors r1, r2
; CHECK-THUMB-NEXT:    eors r0, r2
; CHECK-THUMB-NEXT:    subs r0, r0, r2
; CHECK-THUMB-NEXT:    sbcs r1, r2
; CHECK-THUMB-NEXT:    pop {r4, pc}
  %aext = zext i64 %a to i128
  %bext = zext i64 %b to i128
  %sub = sub i128 %aext, %bext
  %abs = call i128 @llvm.abs.i128(i128 %sub, i1 true)
  %trunc = trunc i128 %abs to i64
  ret i64 %trunc
}

define i128 @abd_ext_i128(i128 %a, i128 %b) nounwind {
; CHECK-ARM-LABEL: abd_ext_i128:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    .save {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    push {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    ldr r5, [sp, #16]
; CHECK-ARM-NEXT:    mov r6, #0
; CHECK-ARM-NEXT:    ldr r4, [sp, #20]
; CHECK-ARM-NEXT:    subs r0, r0, r5
; CHECK-ARM-NEXT:    ldr lr, [sp, #24]
; CHECK-ARM-NEXT:    sbcs r1, r1, r4
; CHECK-ARM-NEXT:    ldr r12, [sp, #28]
; CHECK-ARM-NEXT:    sbcs r2, r2, lr
; CHECK-ARM-NEXT:    sbcs r3, r3, r12
; CHECK-ARM-NEXT:    adc r6, r6, #0
; CHECK-ARM-NEXT:    eor r6, r6, #1
; CHECK-ARM-NEXT:    rsb r6, r6, #0
; CHECK-ARM-NEXT:    eor r0, r0, r6
; CHECK-ARM-NEXT:    eor r1, r1, r6
; CHECK-ARM-NEXT:    subs r0, r0, r6
; CHECK-ARM-NEXT:    eor r2, r2, r6
; CHECK-ARM-NEXT:    sbcs r1, r1, r6
; CHECK-ARM-NEXT:    eor r3, r3, r6
; CHECK-ARM-NEXT:    sbcs r2, r2, r6
; CHECK-ARM-NEXT:    sbc r3, r3, r6
; CHECK-ARM-NEXT:    pop {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_ext_i128:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    .save {r4, r5, r6, r7, lr}
; CHECK-THUMB-NEXT:    push {r4, r5, r6, r7, lr}
; CHECK-THUMB-NEXT:    .pad #4
; CHECK-THUMB-NEXT:    sub sp, #4
; CHECK-THUMB-NEXT:    mov r4, r0
; CHECK-THUMB-NEXT:    ldr r0, [sp, #36]
; CHECK-THUMB-NEXT:    str r0, [sp] @ 4-byte Spill
; CHECK-THUMB-NEXT:    ldr r5, [sp, #32]
; CHECK-THUMB-NEXT:    ldr r6, [sp, #28]
; CHECK-THUMB-NEXT:    ldr r7, [sp, #24]
; CHECK-THUMB-NEXT:    movs r0, #0
; CHECK-THUMB-NEXT:    subs r4, r4, r7
; CHECK-THUMB-NEXT:    sbcs r1, r6
; CHECK-THUMB-NEXT:    sbcs r2, r5
; CHECK-THUMB-NEXT:    ldr r5, [sp] @ 4-byte Reload
; CHECK-THUMB-NEXT:    sbcs r3, r5
; CHECK-THUMB-NEXT:    adcs r0, r0
; CHECK-THUMB-NEXT:    movs r5, #1
; CHECK-THUMB-NEXT:    eors r5, r0
; CHECK-THUMB-NEXT:    rsbs r5, r5, #0
; CHECK-THUMB-NEXT:    eors r3, r5
; CHECK-THUMB-NEXT:    eors r2, r5
; CHECK-THUMB-NEXT:    eors r1, r5
; CHECK-THUMB-NEXT:    eors r4, r5
; CHECK-THUMB-NEXT:    subs r0, r4, r5
; CHECK-THUMB-NEXT:    sbcs r1, r5
; CHECK-THUMB-NEXT:    sbcs r2, r5
; CHECK-THUMB-NEXT:    sbcs r3, r5
; CHECK-THUMB-NEXT:    add sp, #4
; CHECK-THUMB-NEXT:    pop {r4, r5, r6, r7, pc}
  %aext = zext i128 %a to i256
  %bext = zext i128 %b to i256
  %sub = sub i256 %aext, %bext
  %abs = call i256 @llvm.abs.i256(i256 %sub, i1 false)
  %trunc = trunc i256 %abs to i128
  ret i128 %trunc
}

define i128 @abd_ext_i128_undef(i128 %a, i128 %b) nounwind {
; CHECK-ARM-LABEL: abd_ext_i128_undef:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    .save {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    push {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    ldr r5, [sp, #16]
; CHECK-ARM-NEXT:    mov r6, #0
; CHECK-ARM-NEXT:    ldr r4, [sp, #20]
; CHECK-ARM-NEXT:    subs r0, r0, r5
; CHECK-ARM-NEXT:    ldr lr, [sp, #24]
; CHECK-ARM-NEXT:    sbcs r1, r1, r4
; CHECK-ARM-NEXT:    ldr r12, [sp, #28]
; CHECK-ARM-NEXT:    sbcs r2, r2, lr
; CHECK-ARM-NEXT:    sbcs r3, r3, r12
; CHECK-ARM-NEXT:    adc r6, r6, #0
; CHECK-ARM-NEXT:    eor r6, r6, #1
; CHECK-ARM-NEXT:    rsb r6, r6, #0
; CHECK-ARM-NEXT:    eor r0, r0, r6
; CHECK-ARM-NEXT:    eor r1, r1, r6
; CHECK-ARM-NEXT:    subs r0, r0, r6
; CHECK-ARM-NEXT:    eor r2, r2, r6
; CHECK-ARM-NEXT:    sbcs r1, r1, r6
; CHECK-ARM-NEXT:    eor r3, r3, r6
; CHECK-ARM-NEXT:    sbcs r2, r2, r6
; CHECK-ARM-NEXT:    sbc r3, r3, r6
; CHECK-ARM-NEXT:    pop {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_ext_i128_undef:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    .save {r4, r5, r6, r7, lr}
; CHECK-THUMB-NEXT:    push {r4, r5, r6, r7, lr}
; CHECK-THUMB-NEXT:    .pad #4
; CHECK-THUMB-NEXT:    sub sp, #4
; CHECK-THUMB-NEXT:    mov r4, r0
; CHECK-THUMB-NEXT:    ldr r0, [sp, #36]
; CHECK-THUMB-NEXT:    str r0, [sp] @ 4-byte Spill
; CHECK-THUMB-NEXT:    ldr r5, [sp, #32]
; CHECK-THUMB-NEXT:    ldr r6, [sp, #28]
; CHECK-THUMB-NEXT:    ldr r7, [sp, #24]
; CHECK-THUMB-NEXT:    movs r0, #0
; CHECK-THUMB-NEXT:    subs r4, r4, r7
; CHECK-THUMB-NEXT:    sbcs r1, r6
; CHECK-THUMB-NEXT:    sbcs r2, r5
; CHECK-THUMB-NEXT:    ldr r5, [sp] @ 4-byte Reload
; CHECK-THUMB-NEXT:    sbcs r3, r5
; CHECK-THUMB-NEXT:    adcs r0, r0
; CHECK-THUMB-NEXT:    movs r5, #1
; CHECK-THUMB-NEXT:    eors r5, r0
; CHECK-THUMB-NEXT:    rsbs r5, r5, #0
; CHECK-THUMB-NEXT:    eors r3, r5
; CHECK-THUMB-NEXT:    eors r2, r5
; CHECK-THUMB-NEXT:    eors r1, r5
; CHECK-THUMB-NEXT:    eors r4, r5
; CHECK-THUMB-NEXT:    subs r0, r4, r5
; CHECK-THUMB-NEXT:    sbcs r1, r5
; CHECK-THUMB-NEXT:    sbcs r2, r5
; CHECK-THUMB-NEXT:    sbcs r3, r5
; CHECK-THUMB-NEXT:    add sp, #4
; CHECK-THUMB-NEXT:    pop {r4, r5, r6, r7, pc}
  %aext = zext i128 %a to i256
  %bext = zext i128 %b to i256
  %sub = sub i256 %aext, %bext
  %abs = call i256 @llvm.abs.i256(i256 %sub, i1 true)
  %trunc = trunc i256 %abs to i128
  ret i128 %trunc
}

;
; sub(umax(a,b),umin(a,b)) -> abdu(a,b)
;

define i8 @abd_minmax_i8(i8 %a, i8 %b) nounwind {
; CHECK-ARM-LABEL: abd_minmax_i8:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    and r1, r1, #255
; CHECK-ARM-NEXT:    and r0, r0, #255
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsbmi r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_minmax_i8:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    uxtb r1, r1
; CHECK-THUMB-NEXT:    uxtb r0, r0
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    asrs r1, r0, #31
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %min = call i8 @llvm.umin.i8(i8 %a, i8 %b)
  %max = call i8 @llvm.umax.i8(i8 %a, i8 %b)
  %sub = sub i8 %max, %min
  ret i8 %sub
}

define i16 @abd_minmax_i16(i16 %a, i16 %b) nounwind {
; CHECK-ARM-LABEL: abd_minmax_i16:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    mov r2, #255
; CHECK-ARM-NEXT:    orr r2, r2, #65280
; CHECK-ARM-NEXT:    and r1, r1, r2
; CHECK-ARM-NEXT:    and r0, r0, r2
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsbmi r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_minmax_i16:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    uxth r1, r1
; CHECK-THUMB-NEXT:    uxth r0, r0
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    asrs r1, r0, #31
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %min = call i16 @llvm.umin.i16(i16 %a, i16 %b)
  %max = call i16 @llvm.umax.i16(i16 %a, i16 %b)
  %sub = sub i16 %max, %min
  ret i16 %sub
}

define i32 @abd_minmax_i32(i32 %a, i32 %b) nounwind {
; CHECK-ARM-LABEL: abd_minmax_i32:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsblo r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_minmax_i32:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    sbcs r1, r1
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %min = call i32 @llvm.umin.i32(i32 %a, i32 %b)
  %max = call i32 @llvm.umax.i32(i32 %a, i32 %b)
  %sub = sub i32 %max, %min
  ret i32 %sub
}

define i64 @abd_minmax_i64(i64 %a, i64 %b) nounwind {
; CHECK-ARM-LABEL: abd_minmax_i64:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    subs r0, r0, r2
; CHECK-ARM-NEXT:    mov r12, #0
; CHECK-ARM-NEXT:    sbcs r1, r1, r3
; CHECK-ARM-NEXT:    adc r2, r12, #0
; CHECK-ARM-NEXT:    eor r2, r2, #1
; CHECK-ARM-NEXT:    rsb r2, r2, #0
; CHECK-ARM-NEXT:    eor r0, r0, r2
; CHECK-ARM-NEXT:    eor r1, r1, r2
; CHECK-ARM-NEXT:    subs r0, r0, r2
; CHECK-ARM-NEXT:    sbc r1, r1, r2
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_minmax_i64:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    .save {r4, lr}
; CHECK-THUMB-NEXT:    push {r4, lr}
; CHECK-THUMB-NEXT:    movs r4, #0
; CHECK-THUMB-NEXT:    subs r0, r0, r2
; CHECK-THUMB-NEXT:    sbcs r1, r3
; CHECK-THUMB-NEXT:    adcs r4, r4
; CHECK-THUMB-NEXT:    movs r2, #1
; CHECK-THUMB-NEXT:    eors r2, r4
; CHECK-THUMB-NEXT:    rsbs r2, r2, #0
; CHECK-THUMB-NEXT:    eors r1, r2
; CHECK-THUMB-NEXT:    eors r0, r2
; CHECK-THUMB-NEXT:    subs r0, r0, r2
; CHECK-THUMB-NEXT:    sbcs r1, r2
; CHECK-THUMB-NEXT:    pop {r4, pc}
  %min = call i64 @llvm.umin.i64(i64 %a, i64 %b)
  %max = call i64 @llvm.umax.i64(i64 %a, i64 %b)
  %sub = sub i64 %max, %min
  ret i64 %sub
}

define i128 @abd_minmax_i128(i128 %a, i128 %b) nounwind {
; CHECK-ARM-LABEL: abd_minmax_i128:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    .save {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    push {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    ldr r5, [sp, #16]
; CHECK-ARM-NEXT:    mov r6, #0
; CHECK-ARM-NEXT:    ldr r4, [sp, #20]
; CHECK-ARM-NEXT:    subs r0, r0, r5
; CHECK-ARM-NEXT:    ldr lr, [sp, #24]
; CHECK-ARM-NEXT:    sbcs r1, r1, r4
; CHECK-ARM-NEXT:    ldr r12, [sp, #28]
; CHECK-ARM-NEXT:    sbcs r2, r2, lr
; CHECK-ARM-NEXT:    sbcs r3, r3, r12
; CHECK-ARM-NEXT:    adc r6, r6, #0
; CHECK-ARM-NEXT:    eor r6, r6, #1
; CHECK-ARM-NEXT:    rsb r6, r6, #0
; CHECK-ARM-NEXT:    eor r0, r0, r6
; CHECK-ARM-NEXT:    eor r1, r1, r6
; CHECK-ARM-NEXT:    subs r0, r0, r6
; CHECK-ARM-NEXT:    eor r2, r2, r6
; CHECK-ARM-NEXT:    sbcs r1, r1, r6
; CHECK-ARM-NEXT:    eor r3, r3, r6
; CHECK-ARM-NEXT:    sbcs r2, r2, r6
; CHECK-ARM-NEXT:    sbc r3, r3, r6
; CHECK-ARM-NEXT:    pop {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_minmax_i128:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    .save {r4, r5, r6, r7, lr}
; CHECK-THUMB-NEXT:    push {r4, r5, r6, r7, lr}
; CHECK-THUMB-NEXT:    .pad #4
; CHECK-THUMB-NEXT:    sub sp, #4
; CHECK-THUMB-NEXT:    mov r4, r0
; CHECK-THUMB-NEXT:    ldr r0, [sp, #36]
; CHECK-THUMB-NEXT:    str r0, [sp] @ 4-byte Spill
; CHECK-THUMB-NEXT:    ldr r5, [sp, #32]
; CHECK-THUMB-NEXT:    ldr r6, [sp, #28]
; CHECK-THUMB-NEXT:    ldr r7, [sp, #24]
; CHECK-THUMB-NEXT:    movs r0, #0
; CHECK-THUMB-NEXT:    subs r4, r4, r7
; CHECK-THUMB-NEXT:    sbcs r1, r6
; CHECK-THUMB-NEXT:    sbcs r2, r5
; CHECK-THUMB-NEXT:    ldr r5, [sp] @ 4-byte Reload
; CHECK-THUMB-NEXT:    sbcs r3, r5
; CHECK-THUMB-NEXT:    adcs r0, r0
; CHECK-THUMB-NEXT:    movs r5, #1
; CHECK-THUMB-NEXT:    eors r5, r0
; CHECK-THUMB-NEXT:    rsbs r5, r5, #0
; CHECK-THUMB-NEXT:    eors r3, r5
; CHECK-THUMB-NEXT:    eors r2, r5
; CHECK-THUMB-NEXT:    eors r1, r5
; CHECK-THUMB-NEXT:    eors r4, r5
; CHECK-THUMB-NEXT:    subs r0, r4, r5
; CHECK-THUMB-NEXT:    sbcs r1, r5
; CHECK-THUMB-NEXT:    sbcs r2, r5
; CHECK-THUMB-NEXT:    sbcs r3, r5
; CHECK-THUMB-NEXT:    add sp, #4
; CHECK-THUMB-NEXT:    pop {r4, r5, r6, r7, pc}
  %min = call i128 @llvm.umin.i128(i128 %a, i128 %b)
  %max = call i128 @llvm.umax.i128(i128 %a, i128 %b)
  %sub = sub i128 %max, %min
  ret i128 %sub
}

;
; select(icmp(a,b),sub(a,b),sub(b,a)) -> abdu(a,b)
;

define i8 @abd_cmp_i8(i8 %a, i8 %b) nounwind {
; CHECK-ARM-LABEL: abd_cmp_i8:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    and r1, r1, #255
; CHECK-ARM-NEXT:    and r0, r0, #255
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsbmi r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_cmp_i8:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    uxtb r1, r1
; CHECK-THUMB-NEXT:    uxtb r0, r0
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    asrs r1, r0, #31
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %cmp = icmp ugt i8 %a, %b
  %ab = sub i8 %a, %b
  %ba = sub i8 %b, %a
  %sel = select i1 %cmp, i8 %ab, i8 %ba
  ret i8 %sel
}

define i16 @abd_cmp_i16(i16 %a, i16 %b) nounwind {
; CHECK-ARM-LABEL: abd_cmp_i16:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    mov r2, #255
; CHECK-ARM-NEXT:    orr r2, r2, #65280
; CHECK-ARM-NEXT:    and r1, r1, r2
; CHECK-ARM-NEXT:    and r0, r0, r2
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsbmi r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_cmp_i16:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    uxth r1, r1
; CHECK-THUMB-NEXT:    uxth r0, r0
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    asrs r1, r0, #31
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %cmp = icmp uge i16 %a, %b
  %ab = sub i16 %a, %b
  %ba = sub i16 %b, %a
  %sel = select i1 %cmp, i16 %ab, i16 %ba
  ret i16 %sel
}

define i32 @abd_cmp_i32(i32 %a, i32 %b) nounwind {
; CHECK-ARM-LABEL: abd_cmp_i32:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsblo r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_cmp_i32:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    sbcs r1, r1
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %cmp = icmp ult i32 %a, %b
  %ab = sub i32 %a, %b
  %ba = sub i32 %b, %a
  %sel = select i1 %cmp, i32 %ba, i32 %ab
  ret i32 %sel
}

define i64 @abd_cmp_i64(i64 %a, i64 %b) nounwind {
; CHECK-ARM-LABEL: abd_cmp_i64:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    subs r0, r0, r2
; CHECK-ARM-NEXT:    mov r12, #0
; CHECK-ARM-NEXT:    sbcs r1, r1, r3
; CHECK-ARM-NEXT:    adc r2, r12, #0
; CHECK-ARM-NEXT:    eor r2, r2, #1
; CHECK-ARM-NEXT:    rsb r2, r2, #0
; CHECK-ARM-NEXT:    eor r0, r0, r2
; CHECK-ARM-NEXT:    eor r1, r1, r2
; CHECK-ARM-NEXT:    subs r0, r0, r2
; CHECK-ARM-NEXT:    sbc r1, r1, r2
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_cmp_i64:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    .save {r4, lr}
; CHECK-THUMB-NEXT:    push {r4, lr}
; CHECK-THUMB-NEXT:    movs r4, #0
; CHECK-THUMB-NEXT:    subs r0, r0, r2
; CHECK-THUMB-NEXT:    sbcs r1, r3
; CHECK-THUMB-NEXT:    adcs r4, r4
; CHECK-THUMB-NEXT:    movs r2, #1
; CHECK-THUMB-NEXT:    eors r2, r4
; CHECK-THUMB-NEXT:    rsbs r2, r2, #0
; CHECK-THUMB-NEXT:    eors r1, r2
; CHECK-THUMB-NEXT:    eors r0, r2
; CHECK-THUMB-NEXT:    subs r0, r0, r2
; CHECK-THUMB-NEXT:    sbcs r1, r2
; CHECK-THUMB-NEXT:    pop {r4, pc}
  %cmp = icmp uge i64 %a, %b
  %ab = sub i64 %a, %b
  %ba = sub i64 %b, %a
  %sel = select i1 %cmp, i64 %ab, i64 %ba
  ret i64 %sel
}

define i128 @abd_cmp_i128(i128 %a, i128 %b) nounwind {
; CHECK-ARM-LABEL: abd_cmp_i128:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    .save {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    push {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    ldr r5, [sp, #16]
; CHECK-ARM-NEXT:    mov r6, #0
; CHECK-ARM-NEXT:    ldr r4, [sp, #20]
; CHECK-ARM-NEXT:    subs r0, r0, r5
; CHECK-ARM-NEXT:    ldr lr, [sp, #24]
; CHECK-ARM-NEXT:    sbcs r1, r1, r4
; CHECK-ARM-NEXT:    ldr r12, [sp, #28]
; CHECK-ARM-NEXT:    sbcs r2, r2, lr
; CHECK-ARM-NEXT:    sbcs r3, r3, r12
; CHECK-ARM-NEXT:    adc r6, r6, #0
; CHECK-ARM-NEXT:    eor r6, r6, #1
; CHECK-ARM-NEXT:    rsb r6, r6, #0
; CHECK-ARM-NEXT:    eor r0, r0, r6
; CHECK-ARM-NEXT:    eor r1, r1, r6
; CHECK-ARM-NEXT:    subs r0, r0, r6
; CHECK-ARM-NEXT:    eor r2, r2, r6
; CHECK-ARM-NEXT:    sbcs r1, r1, r6
; CHECK-ARM-NEXT:    eor r3, r3, r6
; CHECK-ARM-NEXT:    sbcs r2, r2, r6
; CHECK-ARM-NEXT:    sbc r3, r3, r6
; CHECK-ARM-NEXT:    pop {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_cmp_i128:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    .save {r4, r5, r6, r7, lr}
; CHECK-THUMB-NEXT:    push {r4, r5, r6, r7, lr}
; CHECK-THUMB-NEXT:    .pad #4
; CHECK-THUMB-NEXT:    sub sp, #4
; CHECK-THUMB-NEXT:    mov r4, r0
; CHECK-THUMB-NEXT:    ldr r0, [sp, #36]
; CHECK-THUMB-NEXT:    str r0, [sp] @ 4-byte Spill
; CHECK-THUMB-NEXT:    ldr r5, [sp, #32]
; CHECK-THUMB-NEXT:    ldr r6, [sp, #28]
; CHECK-THUMB-NEXT:    ldr r7, [sp, #24]
; CHECK-THUMB-NEXT:    movs r0, #0
; CHECK-THUMB-NEXT:    subs r4, r4, r7
; CHECK-THUMB-NEXT:    sbcs r1, r6
; CHECK-THUMB-NEXT:    sbcs r2, r5
; CHECK-THUMB-NEXT:    ldr r5, [sp] @ 4-byte Reload
; CHECK-THUMB-NEXT:    sbcs r3, r5
; CHECK-THUMB-NEXT:    adcs r0, r0
; CHECK-THUMB-NEXT:    movs r5, #1
; CHECK-THUMB-NEXT:    eors r5, r0
; CHECK-THUMB-NEXT:    rsbs r5, r5, #0
; CHECK-THUMB-NEXT:    eors r3, r5
; CHECK-THUMB-NEXT:    eors r2, r5
; CHECK-THUMB-NEXT:    eors r1, r5
; CHECK-THUMB-NEXT:    eors r4, r5
; CHECK-THUMB-NEXT:    subs r0, r4, r5
; CHECK-THUMB-NEXT:    sbcs r1, r5
; CHECK-THUMB-NEXT:    sbcs r2, r5
; CHECK-THUMB-NEXT:    sbcs r3, r5
; CHECK-THUMB-NEXT:    add sp, #4
; CHECK-THUMB-NEXT:    pop {r4, r5, r6, r7, pc}
  %cmp = icmp uge i128 %a, %b
  %ab = sub i128 %a, %b
  %ba = sub i128 %b, %a
  %sel = select i1 %cmp, i128 %ab, i128 %ba
  ret i128 %sel
}

;
; negative tests
;

define i64 @vector_legalized(i16 %a, i16 %b) {
; CHECK-ARM-LABEL: vector_legalized:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    mov r2, #255
; CHECK-ARM-NEXT:    orr r2, r2, #65280
; CHECK-ARM-NEXT:    and r1, r1, r2
; CHECK-ARM-NEXT:    and r0, r0, r2
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    mov r1, #0
; CHECK-ARM-NEXT:    rsbmi r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: vector_legalized:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    uxth r1, r1
; CHECK-THUMB-NEXT:    uxth r0, r0
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    asrs r1, r0, #31
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    movs r1, #0
; CHECK-THUMB-NEXT:    bx lr
  %ea = zext i16 %a to i32
  %eb = zext i16 %b to i32
  %s = sub i32 %ea, %eb
  %ab = call i32 @llvm.abs.i32(i32 %s, i1 false)
  %e = zext i32 %ab to i64
  %red = call i64 @llvm.vector.reduce.add.v32i64(<32 x i64> zeroinitializer)
  %z = add i64 %red, %e
  ret i64 %z
}

;
; sub(select(icmp(a,b),a,b),select(icmp(a,b),b,a)) -> abdu(a,b)
;

define i8 @abd_select_i8(i8 %a, i8 %b) nounwind {
; CHECK-ARM-LABEL: abd_select_i8:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    and r1, r1, #255
; CHECK-ARM-NEXT:    and r0, r0, #255
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsbmi r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_select_i8:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    uxtb r1, r1
; CHECK-THUMB-NEXT:    uxtb r0, r0
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    asrs r1, r0, #31
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %cmp = icmp ult i8 %a, %b
  %ab = select i1 %cmp, i8 %a, i8 %b
  %ba = select i1 %cmp, i8 %b, i8 %a
  %sub = sub i8 %ba, %ab
  ret i8 %sub
}

define i16 @abd_select_i16(i16 %a, i16 %b) nounwind {
; CHECK-ARM-LABEL: abd_select_i16:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    mov r2, #255
; CHECK-ARM-NEXT:    orr r2, r2, #65280
; CHECK-ARM-NEXT:    and r1, r1, r2
; CHECK-ARM-NEXT:    and r0, r0, r2
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsbmi r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_select_i16:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    uxth r1, r1
; CHECK-THUMB-NEXT:    uxth r0, r0
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    asrs r1, r0, #31
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %cmp = icmp ule i16 %a, %b
  %ab = select i1 %cmp, i16 %a, i16 %b
  %ba = select i1 %cmp, i16 %b, i16 %a
  %sub = sub i16 %ba, %ab
  ret i16 %sub
}

define i32 @abd_select_i32(i32 %a, i32 %b) nounwind {
; CHECK-ARM-LABEL: abd_select_i32:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    subs r0, r0, r1
; CHECK-ARM-NEXT:    rsblo r0, r0, #0
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_select_i32:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    sbcs r1, r1
; CHECK-THUMB-NEXT:    eors r0, r1
; CHECK-THUMB-NEXT:    subs r0, r0, r1
; CHECK-THUMB-NEXT:    bx lr
  %cmp = icmp ugt i32 %a, %b
  %ab = select i1 %cmp, i32 %a, i32 %b
  %ba = select i1 %cmp, i32 %b, i32 %a
  %sub = sub i32 %ab, %ba
  ret i32 %sub
}

define i64 @abd_select_i64(i64 %a, i64 %b) nounwind {
; CHECK-ARM-LABEL: abd_select_i64:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    subs r0, r0, r2
; CHECK-ARM-NEXT:    mov r12, #0
; CHECK-ARM-NEXT:    sbcs r1, r1, r3
; CHECK-ARM-NEXT:    adc r2, r12, #0
; CHECK-ARM-NEXT:    eor r2, r2, #1
; CHECK-ARM-NEXT:    rsb r2, r2, #0
; CHECK-ARM-NEXT:    eor r0, r0, r2
; CHECK-ARM-NEXT:    eor r1, r1, r2
; CHECK-ARM-NEXT:    subs r0, r0, r2
; CHECK-ARM-NEXT:    sbc r1, r1, r2
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_select_i64:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    .save {r4, lr}
; CHECK-THUMB-NEXT:    push {r4, lr}
; CHECK-THUMB-NEXT:    movs r4, #0
; CHECK-THUMB-NEXT:    subs r0, r0, r2
; CHECK-THUMB-NEXT:    sbcs r1, r3
; CHECK-THUMB-NEXT:    adcs r4, r4
; CHECK-THUMB-NEXT:    movs r2, #1
; CHECK-THUMB-NEXT:    eors r2, r4
; CHECK-THUMB-NEXT:    rsbs r2, r2, #0
; CHECK-THUMB-NEXT:    eors r1, r2
; CHECK-THUMB-NEXT:    eors r0, r2
; CHECK-THUMB-NEXT:    subs r0, r0, r2
; CHECK-THUMB-NEXT:    sbcs r1, r2
; CHECK-THUMB-NEXT:    pop {r4, pc}
  %cmp = icmp uge i64 %a, %b
  %ab = select i1 %cmp, i64 %a, i64 %b
  %ba = select i1 %cmp, i64 %b, i64 %a
  %sub = sub i64 %ab, %ba
  ret i64 %sub
}

define i128 @abd_select_i128(i128 %a, i128 %b) nounwind {
; CHECK-ARM-LABEL: abd_select_i128:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    .save {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    push {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    ldr r5, [sp, #16]
; CHECK-ARM-NEXT:    mov r6, #0
; CHECK-ARM-NEXT:    ldr r4, [sp, #20]
; CHECK-ARM-NEXT:    subs r0, r0, r5
; CHECK-ARM-NEXT:    ldr lr, [sp, #24]
; CHECK-ARM-NEXT:    sbcs r1, r1, r4
; CHECK-ARM-NEXT:    ldr r12, [sp, #28]
; CHECK-ARM-NEXT:    sbcs r2, r2, lr
; CHECK-ARM-NEXT:    sbcs r3, r3, r12
; CHECK-ARM-NEXT:    adc r6, r6, #0
; CHECK-ARM-NEXT:    eor r6, r6, #1
; CHECK-ARM-NEXT:    rsb r6, r6, #0
; CHECK-ARM-NEXT:    eor r0, r0, r6
; CHECK-ARM-NEXT:    eor r1, r1, r6
; CHECK-ARM-NEXT:    subs r0, r0, r6
; CHECK-ARM-NEXT:    eor r2, r2, r6
; CHECK-ARM-NEXT:    sbcs r1, r1, r6
; CHECK-ARM-NEXT:    eor r3, r3, r6
; CHECK-ARM-NEXT:    sbcs r2, r2, r6
; CHECK-ARM-NEXT:    sbc r3, r3, r6
; CHECK-ARM-NEXT:    pop {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB-LABEL: abd_select_i128:
; CHECK-THUMB:       @ %bb.0:
; CHECK-THUMB-NEXT:    .save {r4, r5, r6, r7, lr}
; CHECK-THUMB-NEXT:    push {r4, r5, r6, r7, lr}
; CHECK-THUMB-NEXT:    .pad #4
; CHECK-THUMB-NEXT:    sub sp, #4
; CHECK-THUMB-NEXT:    mov r4, r0
; CHECK-THUMB-NEXT:    ldr r0, [sp, #36]
; CHECK-THUMB-NEXT:    str r0, [sp] @ 4-byte Spill
; CHECK-THUMB-NEXT:    ldr r5, [sp, #32]
; CHECK-THUMB-NEXT:    ldr r6, [sp, #28]
; CHECK-THUMB-NEXT:    ldr r7, [sp, #24]
; CHECK-THUMB-NEXT:    movs r0, #0
; CHECK-THUMB-NEXT:    subs r4, r4, r7
; CHECK-THUMB-NEXT:    sbcs r1, r6
; CHECK-THUMB-NEXT:    sbcs r2, r5
; CHECK-THUMB-NEXT:    ldr r5, [sp] @ 4-byte Reload
; CHECK-THUMB-NEXT:    sbcs r3, r5
; CHECK-THUMB-NEXT:    adcs r0, r0
; CHECK-THUMB-NEXT:    movs r5, #1
; CHECK-THUMB-NEXT:    eors r5, r0
; CHECK-THUMB-NEXT:    rsbs r5, r5, #0
; CHECK-THUMB-NEXT:    eors r3, r5
; CHECK-THUMB-NEXT:    eors r2, r5
; CHECK-THUMB-NEXT:    eors r1, r5
; CHECK-THUMB-NEXT:    eors r4, r5
; CHECK-THUMB-NEXT:    subs r0, r4, r5
; CHECK-THUMB-NEXT:    sbcs r1, r5
; CHECK-THUMB-NEXT:    sbcs r2, r5
; CHECK-THUMB-NEXT:    sbcs r3, r5
; CHECK-THUMB-NEXT:    add sp, #4
; CHECK-THUMB-NEXT:    pop {r4, r5, r6, r7, pc}
  %cmp = icmp ult i128 %a, %b
  %ab = select i1 %cmp, i128 %a, i128 %b
  %ba = select i1 %cmp, i128 %b, i128 %a
  %sub = sub i128 %ba, %ab
  ret i128 %sub
}

declare i8 @llvm.abs.i8(i8, i1)
declare i16 @llvm.abs.i16(i16, i1)
declare i32 @llvm.abs.i32(i32, i1)
declare i64 @llvm.abs.i64(i64, i1)
declare i128 @llvm.abs.i128(i128, i1)

declare i8 @llvm.umax.i8(i8, i8)
declare i16 @llvm.umax.i16(i16, i16)
declare i32 @llvm.umax.i32(i32, i32)
declare i64 @llvm.umax.i64(i64, i64)

declare i8 @llvm.umin.i8(i8, i8)
declare i16 @llvm.umin.i16(i16, i16)
declare i32 @llvm.umin.i32(i32, i32)
declare i64 @llvm.umin.i64(i64, i64)
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
