; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc < %s -frame-pointer=all -mtriple=thumbv7-unknown-linux-gnueabihf | FileCheck %s

; Test generated from C code:
; #include <stdarg.h>
; ptr foo() {
;   return _AddressOfReturnAddress();
; }
; int bar(int x(va_list, ptr), ...) {
;   va_list y;
;   va_start(y, x);
;   return x(y, _AddressOfReturnAddress()) + 1;
; }

declare void @llvm.va_start(ptr)
declare ptr @llvm.addressofreturnaddress()

define dso_local ptr @foo() {
; CHECK-LABEL: foo:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    .save {r7, lr}
; CHECK-NEXT:    push {r7, lr}
; CHECK-NEXT:    .setfp r7, sp
; CHECK-NEXT:    mov r7, sp
; CHECK-NEXT:    adds r0, r7, #4
; CHECK-NEXT:    pop {r7, pc}
entry:
  %0 = call ptr @llvm.addressofreturnaddress()
  ret ptr %0
}

define dso_local i32 @bar(ptr %x, ...) {
; CHECK-LABEL: bar:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    .pad #12
; CHECK-NEXT:    sub sp, #12
; CHECK-NEXT:    .save {r7, lr}
; CHECK-NEXT:    push {r7, lr}
; CHECK-NEXT:    .setfp r7, sp
; CHECK-NEXT:    mov r7, sp
; CHECK-NEXT:    .pad #12
; CHECK-NEXT:    sub sp, #12
; CHECK-NEXT:    add.w lr, r7, #8
; CHECK-NEXT:    mov r12, r0
; CHECK-NEXT:    add.w r0, r7, #8
; CHECK-NEXT:    str r0, [sp]
; CHECK-NEXT:    stm.w lr, {r1, r2, r3}
; CHECK-NEXT:    adds r1, r7, #4
; CHECK-NEXT:    str.w r12, [sp, #8]
; CHECK-NEXT:    blx r12
; CHECK-NEXT:    adds r0, #1
; CHECK-NEXT:    add sp, #12
; CHECK-NEXT:    pop.w {r7, lr}
; CHECK-NEXT:    add sp, #12
; CHECK-NEXT:    bx lr
entry:
  %x.addr = alloca ptr, align 8
  %y = alloca ptr, align 8
  store ptr %x, ptr %x.addr, align 8
  call void @llvm.va_start(ptr %y)
  %0 = load ptr, ptr %x.addr, align 8
  %1 = call ptr @llvm.addressofreturnaddress()
  %2 = load ptr, ptr %y, align 8
  %call = call i32 %0(ptr %2, ptr %1)
  %add = add nsw i32 %call, 1
  ret i32 %add
}
