; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=thumbv7em-arm-none-eabi %s -o - | FileCheck %s

define arm_aapcs_vfpcc void @test(ptr %v50) {
; CHECK-LABEL: test:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r1, #65534
; CHECK-NEXT:    strh.w r1, [r0, #510]
; CHECK-NEXT:    movw r1, #64506
; CHECK-NEXT:    movt r1, #65020
; CHECK-NEXT:    str.w r1, [r0, #506]
; CHECK-NEXT:    movw r1, #63478
; CHECK-NEXT:    movt r1, #63992
; CHECK-NEXT:    str.w r1, [r0, #502]
; CHECK-NEXT:    movw r1, #62450
; CHECK-NEXT:    movt r1, #62964
; CHECK-NEXT:    str.w r1, [r0, #498]
; CHECK-NEXT:    movw r1, #61422
; CHECK-NEXT:    movt r1, #61936
; CHECK-NEXT:    str.w r1, [r0, #494]
; CHECK-NEXT:    movw r1, #60394
; CHECK-NEXT:    movt r1, #60908
; CHECK-NEXT:    str.w r1, [r0, #490]
; CHECK-NEXT:    movw r1, #59366
; CHECK-NEXT:    movt r1, #59880
; CHECK-NEXT:    str.w r1, [r0, #486]
; CHECK-NEXT:    movw r1, #58338
; CHECK-NEXT:    movt r1, #58852
; CHECK-NEXT:    str.w r1, [r0, #482]
; CHECK-NEXT:    movw r1, #57310
; CHECK-NEXT:    movt r1, #57824
; CHECK-NEXT:    str.w r1, [r0, #478]
; CHECK-NEXT:    movw r1, #56282
; CHECK-NEXT:    movt r1, #56796
; CHECK-NEXT:    str.w r1, [r0, #474]
; CHECK-NEXT:    movw r1, #55254
; CHECK-NEXT:    movt r1, #55768
; CHECK-NEXT:    str.w r1, [r0, #470]
; CHECK-NEXT:    movw r1, #54226
; CHECK-NEXT:    movt r1, #54740
; CHECK-NEXT:    str.w r1, [r0, #466]
; CHECK-NEXT:    movw r1, #53198
; CHECK-NEXT:    movt r1, #53712
; CHECK-NEXT:    str.w r1, [r0, #462]
; CHECK-NEXT:    movw r1, #52170
; CHECK-NEXT:    movt r1, #52684
; CHECK-NEXT:    str.w r1, [r0, #458]
; CHECK-NEXT:    movw r1, #51142
; CHECK-NEXT:    movt r1, #51656
; CHECK-NEXT:    str.w r1, [r0, #454]
; CHECK-NEXT:    movw r1, #50114
; CHECK-NEXT:    movt r1, #50628
; CHECK-NEXT:    str.w r1, [r0, #450]
; CHECK-NEXT:    movw r1, #49086
; CHECK-NEXT:    movt r1, #49600
; CHECK-NEXT:    str.w r1, [r0, #446]
; CHECK-NEXT:    movw r1, #48058
; CHECK-NEXT:    movt r1, #48572
; CHECK-NEXT:    str.w r1, [r0, #442]
; CHECK-NEXT:    movw r1, #47030
; CHECK-NEXT:    movt r1, #47544
; CHECK-NEXT:    str.w r1, [r0, #438]
; CHECK-NEXT:    movw r1, #46002
; CHECK-NEXT:    movt r1, #46516
; CHECK-NEXT:    str.w r1, [r0, #434]
; CHECK-NEXT:    movw r1, #44974
; CHECK-NEXT:    movt r1, #45488
; CHECK-NEXT:    str.w r1, [r0, #430]
; CHECK-NEXT:    movw r1, #43946
; CHECK-NEXT:    movt r1, #44460
; CHECK-NEXT:    str.w r1, [r0, #426]
; CHECK-NEXT:    movw r1, #42918
; CHECK-NEXT:    movt r1, #43432
; CHECK-NEXT:    str.w r1, [r0, #422]
; CHECK-NEXT:    movw r1, #41890
; CHECK-NEXT:    movt r1, #42404
; CHECK-NEXT:    str.w r1, [r0, #418]
; CHECK-NEXT:    movw r1, #40862
; CHECK-NEXT:    movt r1, #41376
; CHECK-NEXT:    str.w r1, [r0, #414]
; CHECK-NEXT:    movw r1, #39834
; CHECK-NEXT:    movt r1, #40348
; CHECK-NEXT:    str.w r1, [r0, #410]
; CHECK-NEXT:    movw r1, #38806
; CHECK-NEXT:    movt r1, #39320
; CHECK-NEXT:    str.w r1, [r0, #406]
; CHECK-NEXT:    movw r1, #37778
; CHECK-NEXT:    movt r1, #38292
; CHECK-NEXT:    str.w r1, [r0, #402]
; CHECK-NEXT:    movw r1, #36750
; CHECK-NEXT:    movt r1, #37264
; CHECK-NEXT:    str.w r1, [r0, #398]
; CHECK-NEXT:    movw r1, #35722
; CHECK-NEXT:    movt r1, #36236
; CHECK-NEXT:    str.w r1, [r0, #394]
; CHECK-NEXT:    bx lr
  %v190 = getelementptr inbounds i8, ptr %v50, i32 394
  store i8 -118, ptr %v190, align 1
  %v191 = getelementptr inbounds i8, ptr %v50, i32 395
  store i8 -117, ptr %v191, align 1
  %v192 = getelementptr inbounds i8, ptr %v50, i32 396
  store i8 -116, ptr %v192, align 1
  %v193 = getelementptr inbounds i8, ptr %v50, i32 397
  store i8 -115, ptr %v193, align 1
  %v194 = getelementptr inbounds i8, ptr %v50, i32 398
  store i8 -114, ptr %v194, align 1
  %v195 = getelementptr inbounds i8, ptr %v50, i32 399
  store i8 -113, ptr %v195, align 1
  %v196 = getelementptr inbounds i8, ptr %v50, i32 400
  store i8 -112, ptr %v196, align 1
  %v197 = getelementptr inbounds i8, ptr %v50, i32 401
  store i8 -111, ptr %v197, align 1
  %v198 = getelementptr inbounds i8, ptr %v50, i32 402
  store i8 -110, ptr %v198, align 1
  %v199 = getelementptr inbounds i8, ptr %v50, i32 403
  store i8 -109, ptr %v199, align 1
  %v200 = getelementptr inbounds i8, ptr %v50, i32 404
  store i8 -108, ptr %v200, align 1
  %v201 = getelementptr inbounds i8, ptr %v50, i32 405
  store i8 -107, ptr %v201, align 1
  %v202 = getelementptr inbounds i8, ptr %v50, i32 406
  store i8 -106, ptr %v202, align 1
  %v203 = getelementptr inbounds i8, ptr %v50, i32 407
  store i8 -105, ptr %v203, align 1
  %v204 = getelementptr inbounds i8, ptr %v50, i32 408
  store i8 -104, ptr %v204, align 1
  %v205 = getelementptr inbounds i8, ptr %v50, i32 409
  store i8 -103, ptr %v205, align 1
  %v206 = getelementptr inbounds i8, ptr %v50, i32 410
  store i8 -102, ptr %v206, align 1
  %v207 = getelementptr inbounds i8, ptr %v50, i32 411
  store i8 -101, ptr %v207, align 1
  %v208 = getelementptr inbounds i8, ptr %v50, i32 412
  store i8 -100, ptr %v208, align 1
  %v209 = getelementptr inbounds i8, ptr %v50, i32 413
  store i8 -99, ptr %v209, align 1
  %v210 = getelementptr inbounds i8, ptr %v50, i32 414
  store i8 -98, ptr %v210, align 1
  %v211 = getelementptr inbounds i8, ptr %v50, i32 415
  store i8 -97, ptr %v211, align 1
  %v212 = getelementptr inbounds i8, ptr %v50, i32 416
  store i8 -96, ptr %v212, align 1
  %v213 = getelementptr inbounds i8, ptr %v50, i32 417
  store i8 -95, ptr %v213, align 1
  %v214 = getelementptr inbounds i8, ptr %v50, i32 418
  store i8 -94, ptr %v214, align 1
  %v215 = getelementptr inbounds i8, ptr %v50, i32 419
  store i8 -93, ptr %v215, align 1
  %v216 = getelementptr inbounds i8, ptr %v50, i32 420
  store i8 -92, ptr %v216, align 1
  %v217 = getelementptr inbounds i8, ptr %v50, i32 421
  store i8 -91, ptr %v217, align 1
  %v218 = getelementptr inbounds i8, ptr %v50, i32 422
  store i8 -90, ptr %v218, align 1
  %v219 = getelementptr inbounds i8, ptr %v50, i32 423
  store i8 -89, ptr %v219, align 1
  %v220 = getelementptr inbounds i8, ptr %v50, i32 424
  store i8 -88, ptr %v220, align 1
  %v221 = getelementptr inbounds i8, ptr %v50, i32 425
  store i8 -87, ptr %v221, align 1
  %v222 = getelementptr inbounds i8, ptr %v50, i32 426
  store i8 -86, ptr %v222, align 1
  %v223 = getelementptr inbounds i8, ptr %v50, i32 427
  store i8 -85, ptr %v223, align 1
  %v224 = getelementptr inbounds i8, ptr %v50, i32 428
  store i8 -84, ptr %v224, align 1
  %v225 = getelementptr inbounds i8, ptr %v50, i32 429
  store i8 -83, ptr %v225, align 1
  %v226 = getelementptr inbounds i8, ptr %v50, i32 430
  store i8 -82, ptr %v226, align 1
  %v227 = getelementptr inbounds i8, ptr %v50, i32 431
  store i8 -81, ptr %v227, align 1
  %v228 = getelementptr inbounds i8, ptr %v50, i32 432
  store i8 -80, ptr %v228, align 1
  %v229 = getelementptr inbounds i8, ptr %v50, i32 433
  store i8 -79, ptr %v229, align 1
  %v230 = getelementptr inbounds i8, ptr %v50, i32 434
  store i8 -78, ptr %v230, align 1
  %v231 = getelementptr inbounds i8, ptr %v50, i32 435
  store i8 -77, ptr %v231, align 1
  %v232 = getelementptr inbounds i8, ptr %v50, i32 436
  store i8 -76, ptr %v232, align 1
  %v233 = getelementptr inbounds i8, ptr %v50, i32 437
  store i8 -75, ptr %v233, align 1
  %v234 = getelementptr inbounds i8, ptr %v50, i32 438
  store i8 -74, ptr %v234, align 1
  %v235 = getelementptr inbounds i8, ptr %v50, i32 439
  store i8 -73, ptr %v235, align 1
  %v236 = getelementptr inbounds i8, ptr %v50, i32 440
  store i8 -72, ptr %v236, align 1
  %v237 = getelementptr inbounds i8, ptr %v50, i32 441
  store i8 -71, ptr %v237, align 1
  %v238 = getelementptr inbounds i8, ptr %v50, i32 442
  store i8 -70, ptr %v238, align 1
  %v239 = getelementptr inbounds i8, ptr %v50, i32 443
  store i8 -69, ptr %v239, align 1
  %v240 = getelementptr inbounds i8, ptr %v50, i32 444
  store i8 -68, ptr %v240, align 1
  %v241 = getelementptr inbounds i8, ptr %v50, i32 445
  store i8 -67, ptr %v241, align 1
  %v242 = getelementptr inbounds i8, ptr %v50, i32 446
  store i8 -66, ptr %v242, align 1
  %v243 = getelementptr inbounds i8, ptr %v50, i32 447
  store i8 -65, ptr %v243, align 1
  %v244 = getelementptr inbounds i8, ptr %v50, i32 448
  store i8 -64, ptr %v244, align 1
  %v245 = getelementptr inbounds i8, ptr %v50, i32 449
  store i8 -63, ptr %v245, align 1
  %v246 = getelementptr inbounds i8, ptr %v50, i32 450
  store i8 -62, ptr %v246, align 1
  %v247 = getelementptr inbounds i8, ptr %v50, i32 451
  store i8 -61, ptr %v247, align 1
  %v248 = getelementptr inbounds i8, ptr %v50, i32 452
  store i8 -60, ptr %v248, align 1
  %v249 = getelementptr inbounds i8, ptr %v50, i32 453
  store i8 -59, ptr %v249, align 1
  %v250 = getelementptr inbounds i8, ptr %v50, i32 454
  store i8 -58, ptr %v250, align 1
  %v251 = getelementptr inbounds i8, ptr %v50, i32 455
  store i8 -57, ptr %v251, align 1
  %v252 = getelementptr inbounds i8, ptr %v50, i32 456
  store i8 -56, ptr %v252, align 1
  %v253 = getelementptr inbounds i8, ptr %v50, i32 457
  store i8 -55, ptr %v253, align 1
  %v254 = getelementptr inbounds i8, ptr %v50, i32 458
  store i8 -54, ptr %v254, align 1
  %v255 = getelementptr inbounds i8, ptr %v50, i32 459
  store i8 -53, ptr %v255, align 1
  %v256 = getelementptr inbounds i8, ptr %v50, i32 460
  store i8 -52, ptr %v256, align 1
  %v257 = getelementptr inbounds i8, ptr %v50, i32 461
  store i8 -51, ptr %v257, align 1
  %v258 = getelementptr inbounds i8, ptr %v50, i32 462
  store i8 -50, ptr %v258, align 1
  %v259 = getelementptr inbounds i8, ptr %v50, i32 463
  store i8 -49, ptr %v259, align 1
  %v260 = getelementptr inbounds i8, ptr %v50, i32 464
  store i8 -48, ptr %v260, align 1
  %v261 = getelementptr inbounds i8, ptr %v50, i32 465
  store i8 -47, ptr %v261, align 1
  %v262 = getelementptr inbounds i8, ptr %v50, i32 466
  store i8 -46, ptr %v262, align 1
  %v263 = getelementptr inbounds i8, ptr %v50, i32 467
  store i8 -45, ptr %v263, align 1
  %v264 = getelementptr inbounds i8, ptr %v50, i32 468
  store i8 -44, ptr %v264, align 1
  %v265 = getelementptr inbounds i8, ptr %v50, i32 469
  store i8 -43, ptr %v265, align 1
  %v266 = getelementptr inbounds i8, ptr %v50, i32 470
  store i8 -42, ptr %v266, align 1
  %v267 = getelementptr inbounds i8, ptr %v50, i32 471
  store i8 -41, ptr %v267, align 1
  %v268 = getelementptr inbounds i8, ptr %v50, i32 472
  store i8 -40, ptr %v268, align 1
  %v269 = getelementptr inbounds i8, ptr %v50, i32 473
  store i8 -39, ptr %v269, align 1
  %v270 = getelementptr inbounds i8, ptr %v50, i32 474
  store i8 -38, ptr %v270, align 1
  %v271 = getelementptr inbounds i8, ptr %v50, i32 475
  store i8 -37, ptr %v271, align 1
  %v272 = getelementptr inbounds i8, ptr %v50, i32 476
  store i8 -36, ptr %v272, align 1
  %v273 = getelementptr inbounds i8, ptr %v50, i32 477
  store i8 -35, ptr %v273, align 1
  %v274 = getelementptr inbounds i8, ptr %v50, i32 478
  store i8 -34, ptr %v274, align 1
  %v275 = getelementptr inbounds i8, ptr %v50, i32 479
  store i8 -33, ptr %v275, align 1
  %v276 = getelementptr inbounds i8, ptr %v50, i32 480
  store i8 -32, ptr %v276, align 1
  %v277 = getelementptr inbounds i8, ptr %v50, i32 481
  store i8 -31, ptr %v277, align 1
  %v278 = getelementptr inbounds i8, ptr %v50, i32 482
  store i8 -30, ptr %v278, align 1
  %v279 = getelementptr inbounds i8, ptr %v50, i32 483
  store i8 -29, ptr %v279, align 1
  %v280 = getelementptr inbounds i8, ptr %v50, i32 484
  store i8 -28, ptr %v280, align 1
  %v281 = getelementptr inbounds i8, ptr %v50, i32 485
  store i8 -27, ptr %v281, align 1
  %v282 = getelementptr inbounds i8, ptr %v50, i32 486
  store i8 -26, ptr %v282, align 1
  %v283 = getelementptr inbounds i8, ptr %v50, i32 487
  store i8 -25, ptr %v283, align 1
  %v284 = getelementptr inbounds i8, ptr %v50, i32 488
  store i8 -24, ptr %v284, align 1
  %v285 = getelementptr inbounds i8, ptr %v50, i32 489
  store i8 -23, ptr %v285, align 1
  %v286 = getelementptr inbounds i8, ptr %v50, i32 490
  store i8 -22, ptr %v286, align 1
  %v287 = getelementptr inbounds i8, ptr %v50, i32 491
  store i8 -21, ptr %v287, align 1
  %v288 = getelementptr inbounds i8, ptr %v50, i32 492
  store i8 -20, ptr %v288, align 1
  %v289 = getelementptr inbounds i8, ptr %v50, i32 493
  store i8 -19, ptr %v289, align 1
  %v290 = getelementptr inbounds i8, ptr %v50, i32 494
  store i8 -18, ptr %v290, align 1
  %v291 = getelementptr inbounds i8, ptr %v50, i32 495
  store i8 -17, ptr %v291, align 1
  %v292 = getelementptr inbounds i8, ptr %v50, i32 496
  store i8 -16, ptr %v292, align 1
  %v293 = getelementptr inbounds i8, ptr %v50, i32 497
  store i8 -15, ptr %v293, align 1
  %v294 = getelementptr inbounds i8, ptr %v50, i32 498
  store i8 -14, ptr %v294, align 1
  %v295 = getelementptr inbounds i8, ptr %v50, i32 499
  store i8 -13, ptr %v295, align 1
  %v296 = getelementptr inbounds i8, ptr %v50, i32 500
  store i8 -12, ptr %v296, align 1
  %v297 = getelementptr inbounds i8, ptr %v50, i32 501
  store i8 -11, ptr %v297, align 1
  %v298 = getelementptr inbounds i8, ptr %v50, i32 502
  store i8 -10, ptr %v298, align 1
  %v299 = getelementptr inbounds i8, ptr %v50, i32 503
  store i8 -9, ptr %v299, align 1
  %v300 = getelementptr inbounds i8, ptr %v50, i32 504
  store i8 -8, ptr %v300, align 1
  %v301 = getelementptr inbounds i8, ptr %v50, i32 505
  store i8 -7, ptr %v301, align 1
  %v302 = getelementptr inbounds i8, ptr %v50, i32 506
  store i8 -6, ptr %v302, align 1
  %v303 = getelementptr inbounds i8, ptr %v50, i32 507
  store i8 -5, ptr %v303, align 1
  %v304 = getelementptr inbounds i8, ptr %v50, i32 508
  store i8 -4, ptr %v304, align 1
  %v305 = getelementptr inbounds i8, ptr %v50, i32 509
  store i8 -3, ptr %v305, align 1
  %v306 = getelementptr inbounds i8, ptr %v50, i32 510
  store i8 -2, ptr %v306, align 1
  %v307 = getelementptr inbounds i8, ptr %v50, i32 511
  store i8 -1, ptr %v307, align 1
  ret void
  }

