; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=arm-eabi -mcpu=cortex-a9 %s -o - | FileCheck %s

define i32 @max(i8 %ctx, ptr %ptr, i32 %val)
; CHECK-LABEL: max:
; CHECK:       @ %bb.0:
; CHECK-NEXT:  .LBB0_1: @ %atomicrmw.start
; CHECK-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldrex r0, [r1]
; CHECK-NEXT:    mov r3, r2
; CHECK-NEXT:    cmp r0, r2
; CHECK-NEXT:    movhi r3, r0
; CHECK-NEXT:    strex r12, r3, [r1]
; CHECK-NEXT:    cmp r12, #0
; CHECK-NEXT:    bne .LBB0_1
; CHECK-NEXT:  @ %bb.2: @ %atomicrmw.end
; CHECK-NEXT:    bx lr
{
  %old = atomicrmw umax ptr %ptr, i32 %val monotonic
  ret i32 %old
}

define i32 @min(i8 %ctx, ptr %ptr, i32 %val)
; CHECK-LABEL: min:
; CHECK:       @ %bb.0:
; CHECK-NEXT:  .LBB1_1: @ %atomicrmw.start
; CHECK-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldrex r0, [r1]
; CHECK-NEXT:    mov r3, r2
; CHECK-NEXT:    cmp r0, r2
; CHECK-NEXT:    movlo r3, r0
; CHECK-NEXT:    strex r12, r3, [r1]
; CHECK-NEXT:    cmp r12, #0
; CHECK-NEXT:    bne .LBB1_1
; CHECK-NEXT:  @ %bb.2: @ %atomicrmw.end
; CHECK-NEXT:    bx lr
{
  %old = atomicrmw umin ptr %ptr, i32 %val monotonic
  ret i32 %old
}
