; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple armv8a-none-eabihf -mattr=-bf16 | FileCheck %s --check-prefixes=CHECK,CHECK-CVT
; RUN: llc < %s -mtriple armv8a-none-eabihf -mattr=+bf16 | FileCheck %s --check-prefixes=CHECK,CHECK-BF16

;define bfloat @test_fadd(bfloat %a, bfloat %b) #0 {
;  %r = fadd bfloat %a, %b
;  ret bfloat %r
;}

;define bfloat @test_fadd_fast(bfloat %a, bfloat %b) #0 {
;  %r = fadd fast bfloat %a, %b
;  ret bfloat %r
;}

;define bfloat @test_fsub(bfloat %a, bfloat %b) #0 {
;  %r = fsub bfloat %a, %b
;  ret bfloat %r
;}

;define bfloat @test_fmul(bfloat %a, bfloat %b) #0 {
;  %r = fmul bfloat %a, %b
;  ret bfloat %r
;}

;define bfloat @test_fmadd(bfloat %a, bfloat %b, bfloat %c) #0 {
;  %mul = fmul fast bfloat %a, %b
;  %r = fadd fast bfloat %mul, %c
;  ret bfloat %r
;}

;define bfloat @test_fdiv(bfloat %a, bfloat %b) #0 {
;  %r = fdiv bfloat %a, %b
;  ret bfloat %r
;}

;define bfloat @test_frem(bfloat %a, bfloat %b) #0 {
;  %r = frem bfloat %a, %b
;  ret bfloat %r
;}

define bfloat @test_load(ptr %a) #0 {
; CHECK-LABEL: test_load:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    ldrh r0, [r0]
; CHECK-NEXT:    vmov s0, r0
; CHECK-NEXT:    bx lr
  %r = load bfloat, ptr %a
  ret bfloat %r
}

define void @test_store(bfloat %a, ptr %b) #0 {
; CHECK-LABEL: test_store:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vmov r1, s0
; CHECK-NEXT:    strh r1, [r0]
; CHECK-NEXT:    bx lr
  store bfloat %a, ptr %b
  ret void
}

declare bfloat @test_callee(bfloat %a, bfloat %b) #0

define bfloat @test_call(bfloat %a, bfloat %b) #0 {
; CHECK-CVT-LABEL: test_call:
; CHECK-CVT:       @ %bb.0:
; CHECK-CVT-NEXT:    .save {r11, lr}
; CHECK-CVT-NEXT:    push {r11, lr}
; CHECK-CVT-NEXT:    bl test_callee
; CHECK-CVT-NEXT:    pop {r11, pc}
;
; CHECK-BF16-LABEL: test_call:
; CHECK-BF16:       @ %bb.0:
; CHECK-BF16-NEXT:    .save {r11, lr}
; CHECK-BF16-NEXT:    push {r11, lr}
; CHECK-BF16-NEXT:    .pad #8
; CHECK-BF16-NEXT:    sub sp, sp, #8
; CHECK-BF16-NEXT:    vmov r0, s1
; CHECK-BF16-NEXT:    vmov r1, s0
; CHECK-BF16-NEXT:    uxth r0, r0
; CHECK-BF16-NEXT:    uxth r1, r1
; CHECK-BF16-NEXT:    vmov s1, r0
; CHECK-BF16-NEXT:    vmov s0, r1
; CHECK-BF16-NEXT:    bl test_callee
; CHECK-BF16-NEXT:    vmov r0, s0
; CHECK-BF16-NEXT:    strh r0, [sp, #6]
; CHECK-BF16-NEXT:    ldrh r0, [sp, #6]
; CHECK-BF16-NEXT:    vmov s0, r0
; CHECK-BF16-NEXT:    add sp, sp, #8
; CHECK-BF16-NEXT:    pop {r11, pc}
  %r = call bfloat @test_callee(bfloat %a, bfloat %b)
  ret bfloat %r
}

define bfloat @test_call_flipped(bfloat %a, bfloat %b) #0 {
; CHECK-CVT-LABEL: test_call_flipped:
; CHECK-CVT:       @ %bb.0:
; CHECK-CVT-NEXT:    .save {r11, lr}
; CHECK-CVT-NEXT:    push {r11, lr}
; CHECK-CVT-NEXT:    vmov.f32 s2, s0
; CHECK-CVT-NEXT:    vmov.f32 s0, s1
; CHECK-CVT-NEXT:    vmov.f32 s1, s2
; CHECK-CVT-NEXT:    bl test_callee
; CHECK-CVT-NEXT:    pop {r11, pc}
;
; CHECK-BF16-LABEL: test_call_flipped:
; CHECK-BF16:       @ %bb.0:
; CHECK-BF16-NEXT:    .save {r11, lr}
; CHECK-BF16-NEXT:    push {r11, lr}
; CHECK-BF16-NEXT:    .pad #8
; CHECK-BF16-NEXT:    sub sp, sp, #8
; CHECK-BF16-NEXT:    vmov r0, s0
; CHECK-BF16-NEXT:    vmov r1, s1
; CHECK-BF16-NEXT:    uxth r0, r0
; CHECK-BF16-NEXT:    uxth r1, r1
; CHECK-BF16-NEXT:    vmov s1, r0
; CHECK-BF16-NEXT:    vmov s0, r1
; CHECK-BF16-NEXT:    bl test_callee
; CHECK-BF16-NEXT:    vmov r0, s0
; CHECK-BF16-NEXT:    strh r0, [sp, #6]
; CHECK-BF16-NEXT:    ldrh r0, [sp, #6]
; CHECK-BF16-NEXT:    vmov s0, r0
; CHECK-BF16-NEXT:    add sp, sp, #8
; CHECK-BF16-NEXT:    pop {r11, pc}
  %r = call bfloat @test_callee(bfloat %b, bfloat %a)
  ret bfloat %r
}

define bfloat @test_tailcall_flipped(bfloat %a, bfloat %b) #0 {
; CHECK-CVT-LABEL: test_tailcall_flipped:
; CHECK-CVT:       @ %bb.0:
; CHECK-CVT-NEXT:    vmov.f32 s2, s0
; CHECK-CVT-NEXT:    vmov.f32 s0, s1
; CHECK-CVT-NEXT:    vmov.f32 s1, s2
; CHECK-CVT-NEXT:    b test_callee
;
; CHECK-BF16-LABEL: test_tailcall_flipped:
; CHECK-BF16:       @ %bb.0:
; CHECK-BF16-NEXT:    vmov r0, s1
; CHECK-BF16-NEXT:    vmov r1, s0
; CHECK-BF16-NEXT:    uxth r0, r0
; CHECK-BF16-NEXT:    vmov s0, r0
; CHECK-BF16-NEXT:    uxth r0, r1
; CHECK-BF16-NEXT:    vmov s1, r0
; CHECK-BF16-NEXT:    b test_callee
  %r = tail call bfloat @test_callee(bfloat %b, bfloat %a)
  ret bfloat %r
}

;define bfloat @test_select(bfloat %a, bfloat %b, i1 zeroext %c) #0 {
;  %r = select i1 %c, bfloat %a, bfloat %b
;  ret bfloat %r
;}

;define bfloat @test_select_cc(bfloat %a, bfloat %b, bfloat %c, bfloat %d) #0 {
;  %cc = fcmp une bfloat %c, %d
;  %r = select i1 %cc, bfloat %a, bfloat %b
;  ret bfloat %r
;}

;define float @test_select_cc_f32_f16(float %a, float %b, bfloat %c, bfloat %d) #0 {
;  %cc = fcmp une bfloat %c, %d
;  %r = select i1 %cc, float %a, float %b
;  ret float %r
;}

;define bfloat @test_select_cc_f16_f32(bfloat %a, bfloat %b, float %c, float %d) #0 {
;  %cc = fcmp une float %c, %d
;  %r = select i1 %cc, bfloat %a, bfloat %b
;  ret bfloat %r
;}

;define i1 @test_fcmp_une(bfloat %a, bfloat %b) #0 {
;  %r = fcmp une bfloat %a, %b
;  ret i1 %r
;}

;define i1 @test_fcmp_ueq(bfloat %a, bfloat %b) #0 {
;  %r = fcmp ueq bfloat %a, %b
;  ret i1 %r
;}

;define i1 @test_fcmp_ugt(bfloat %a, bfloat %b) #0 {
;  %r = fcmp ugt bfloat %a, %b
;  ret i1 %r
;}

;define i1 @test_fcmp_uge(bfloat %a, bfloat %b) #0 {
;  %r = fcmp uge bfloat %a, %b
;  ret i1 %r
;}

;define i1 @test_fcmp_ult(bfloat %a, bfloat %b) #0 {
;  %r = fcmp ult bfloat %a, %b
;  ret i1 %r
;}

;define i1 @test_fcmp_ule(bfloat %a, bfloat %b) #0 {
;  %r = fcmp ule bfloat %a, %b
;  ret i1 %r
;}

;define i1 @test_fcmp_uno(bfloat %a, bfloat %b) #0 {
;  %r = fcmp uno bfloat %a, %b
;  ret i1 %r
;}

;define i1 @test_fcmp_one(bfloat %a, bfloat %b) #0 {
;  %r = fcmp one bfloat %a, %b
;  ret i1 %r
;}

;define i1 @test_fcmp_oeq(bfloat %a, bfloat %b) #0 {
;  %r = fcmp oeq bfloat %a, %b
;  ret i1 %r
;}

;define i1 @test_fcmp_ogt(bfloat %a, bfloat %b) #0 {
;  %r = fcmp ogt bfloat %a, %b
;  ret i1 %r
;}

;define i1 @test_fcmp_oge(bfloat %a, bfloat %b) #0 {
;  %r = fcmp oge bfloat %a, %b
;  ret i1 %r
;}

;define i1 @test_fcmp_olt(bfloat %a, bfloat %b) #0 {
;  %r = fcmp olt bfloat %a, %b
;  ret i1 %r
;}

;define i1 @test_fcmp_ole(bfloat %a, bfloat %b) #0 {
;  %r = fcmp ole bfloat %a, %b
;  ret i1 %r
;}

;define i1 @test_fcmp_ord(bfloat %a, bfloat %b) #0 {
;  %r = fcmp ord bfloat %a, %b
;  ret i1 %r
;}

;define void @test_fccmp(bfloat %in, ptr %out) {
;  %cmp1 = fcmp ogt bfloat %in, 0xR4800
;  %cmp2 = fcmp olt bfloat %in, 0xR4500
;  %cond = and i1 %cmp1, %cmp2
;  %result = select i1 %cond, bfloat %in, bfloat 0xR4500
;  store bfloat %result, ptr %out
;  ret void
;}

;define void @test_br_cc(bfloat %a, bfloat %b, ptr %p1, ptr %p2) #0 {
;  %c = fcmp uge bfloat %a, %b
;  br i1 %c, label %then, label %else
;then:
;  store i32 0, ptr %p1
;  ret void
;else:
;  store i32 0, ptr %p2
;  ret void
;}

define bfloat @test_phi(ptr %p1) #0 {
; CHECK-LABEL: test_phi:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    .save {r4, lr}
; CHECK-NEXT:    push {r4, lr}
; CHECK-NEXT:    .vsave {d8, d9}
; CHECK-NEXT:    vpush {d8, d9}
; CHECK-NEXT:    mov r4, r0
; CHECK-NEXT:    ldrh r0, [r0]
; CHECK-NEXT:    vmov s18, r0
; CHECK-NEXT:  .LBB5_1: @ %loop
; CHECK-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldrh r0, [r4]
; CHECK-NEXT:    vmov.f32 s16, s18
; CHECK-NEXT:    vmov s18, r0
; CHECK-NEXT:    mov r0, r4
; CHECK-NEXT:    bl test_dummy
; CHECK-NEXT:    tst r0, #1
; CHECK-NEXT:    bne .LBB5_1
; CHECK-NEXT:  @ %bb.2: @ %return
; CHECK-NEXT:    vmov.f32 s0, s16
; CHECK-NEXT:    vpop {d8, d9}
; CHECK-NEXT:    pop {r4, pc}
entry:
  %a = load bfloat, ptr %p1
  br label %loop
loop:
  %r = phi bfloat [%a, %entry], [%b, %loop]
  %b = load bfloat, ptr %p1
  %c = call i1 @test_dummy(ptr %p1)
  br i1 %c, label %loop, label %return
return:
  ret bfloat %r
}

declare i1 @test_dummy(ptr %p1) #0

;define i32 @test_fptosi_i32(bfloat %a) #0 {
;  %r = fptosi bfloat %a to i32
;  ret i32 %r
;}

;define i64 @test_fptosi_i64(bfloat %a) #0 {
;  %r = fptosi bfloat %a to i64
;  ret i64 %r
;}

;define i32 @test_fptoui_i32(bfloat %a) #0 {
;  %r = fptoui bfloat %a to i32
;  ret i32 %r
;}

;define i64 @test_fptoui_i64(bfloat %a) #0 {
;  %r = fptoui bfloat %a to i64
;  ret i64 %r
;}

;define bfloat @test_uitofp_i32(i32 %a) #0 {
;  %r = uitofp i32 %a to bfloat
;  ret bfloat %r
;}

;define bfloat @test_uitofp_i64(i64 %a) #0 {
;  %r = uitofp i64 %a to bfloat
;  ret bfloat %r
;}

;define bfloat @test_sitofp_i32(i32 %a) #0 {
;  %r = sitofp i32 %a to bfloat
;  ret bfloat %r
;}

;define bfloat @test_sitofp_i64(i64 %a) #0 {
;  %r = sitofp i64 %a to bfloat
;  ret bfloat %r
;}

;define bfloat @test_uitofp_i32_fadd(i32 %a, bfloat %b) #0 {
;  %c = uitofp i32 %a to bfloat
;  %r = fadd bfloat %b, %c
;  ret bfloat %r
;}

;define bfloat @test_sitofp_i32_fadd(i32 %a, bfloat %b) #0 {
;  %c = sitofp i32 %a to bfloat
;  %r = fadd bfloat %b, %c
;  ret bfloat %r
;}

;define bfloat @test_fptrunc_float(float %a) #0 {
;  %r = fptrunc float %a to bfloat
;  ret bfloat %r
;}

;define bfloat @test_fptrunc_double(double %a) #0 {
;  %r = fptrunc double %a to bfloat
;  ret bfloat %r
;}

;define bfloat @test_fptrunc_float_fast(float %a) #0 {
;  %r = fptrunc fast float %a to bfloat
;  ret bfloat %r
;}

;define bfloat @test_fptrunc_double_fast(double %a) #0 {
;  %r = fptrunc fast double %a to bfloat
;  ret bfloat %r
;}

;define float @test_fpext_float(bfloat %a) #0 {
;  %r = fpext bfloat %a to float
;  ret float %r
;}

;define double @test_fpext_double(bfloat %a) #0 {
;  %r = fpext bfloat %a to double
;  ret double %r
;}

;define float @test_fpext_float_fast(bfloat %a) #0 {
;  %r = fpext fast bfloat %a to float
;  ret float %r
;}

;define double @test_fpext_double_fast(bfloat %a) #0 {
;  %r = fpext fast bfloat %a to double
;  ret double %r
;}

define i16 @test_bitcast_bfloattoi16(bfloat %a) #0 {
; CHECK-LABEL: test_bitcast_bfloattoi16:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vmov r0, s0
; CHECK-NEXT:    bx lr
  %r = bitcast bfloat %a to i16
  ret i16 %r
}

define bfloat @test_bitcast_i16tobfloat(i16 %a) #0 {
; CHECK-CVT-LABEL: test_bitcast_i16tobfloat:
; CHECK-CVT:       @ %bb.0:
; CHECK-CVT-NEXT:    vmov s0, r0
; CHECK-CVT-NEXT:    bx lr
;
; CHECK-BF16-LABEL: test_bitcast_i16tobfloat:
; CHECK-BF16:       @ %bb.0:
; CHECK-BF16-NEXT:    .pad #4
; CHECK-BF16-NEXT:    sub sp, sp, #4
; CHECK-BF16-NEXT:    strh r0, [sp, #2]
; CHECK-BF16-NEXT:    ldrh r0, [sp, #2]
; CHECK-BF16-NEXT:    vmov s0, r0
; CHECK-BF16-NEXT:    add sp, sp, #4
; CHECK-BF16-NEXT:    bx lr
  %r = bitcast i16 %a to bfloat
  ret bfloat %r
}

define half @test_bitcast_bfloattof16(bfloat %a) #0 {
; CHECK-LABEL: test_bitcast_bfloattof16:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    bx lr
  %r = bitcast bfloat %a to half
  ret half %r
}

define bfloat @test_bitcast_f16tobfloat(half %a) #0 {
; CHECK-CVT-LABEL: test_bitcast_f16tobfloat:
; CHECK-CVT:       @ %bb.0:
; CHECK-CVT-NEXT:    bx lr
;
; CHECK-BF16-LABEL: test_bitcast_f16tobfloat:
; CHECK-BF16:       @ %bb.0:
; CHECK-BF16-NEXT:    .pad #4
; CHECK-BF16-NEXT:    sub sp, sp, #4
; CHECK-BF16-NEXT:    vmov r0, s0
; CHECK-BF16-NEXT:    strh r0, [sp, #2]
; CHECK-BF16-NEXT:    ldrh r0, [sp, #2]
; CHECK-BF16-NEXT:    vmov s0, r0
; CHECK-BF16-NEXT:    add sp, sp, #4
; CHECK-BF16-NEXT:    bx lr
  %r = bitcast half %a to bfloat
  ret bfloat %r
}

;define bfloat @test_sqrt(bfloat %a) #0 {
;  %r = call bfloat @llvm.sqrt.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_powi(bfloat %a, i32 %b) #0 {
;  %r = call bfloat @llvm.powi.bf16.i32(bfloat %a, i32 %b)
;  ret bfloat %r
;}

;define bfloat @test_sin(bfloat %a) #0 {
;  %r = call bfloat @llvm.sin.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_cos(bfloat %a) #0 {
;  %r = call bfloat @llvm.cos.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_tan(bfloat %a) #0 {
;  %r = call bfloat @llvm.tan.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_acos(bfloat %a) #0 {
;  %r = call bfloat @llvm.acos.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_asin(bfloat %a) #0 {
;  %r = call bfloat @llvm.asin.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_atan(bfloat %a) #0 {
;  %r = call bfloat @llvm.atan.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_atan2(bfloat %a, bfloat %b) #0 {
;  %r = call bfloat @llvm.atan2.bf16(bfloat %a, bfloat %b)
;  ret bfloat %r
;}

;define bfloat @test_cosh(bfloat %a) #0 {
;  %r = call bfloat @llvm.cosh.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_sinh(bfloat %a) #0 {
;  %r = call bfloat @llvm.sinh.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_tanh(bfloat %a) #0 {
;  %r = call bfloat @llvm.tanh.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_pow(bfloat %a, bfloat %b) #0 {
;  %r = call bfloat @llvm.pow.bf16(bfloat %a, bfloat %b)
;  ret bfloat %r
;}

;define bfloat @test_exp(bfloat %a) #0 {
;  %r = call bfloat @llvm.exp.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_exp2(bfloat %a) #0 {
;  %r = call bfloat @llvm.exp2.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_log(bfloat %a) #0 {
;  %r = call bfloat @llvm.log.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_log10(bfloat %a) #0 {
;  %r = call bfloat @llvm.log10.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_log2(bfloat %a) #0 {
;  %r = call bfloat @llvm.log2.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_fma(bfloat %a, bfloat %b, bfloat %c) #0 {
;  %r = call bfloat @llvm.fma.bf16(bfloat %a, bfloat %b, bfloat %c)
;  ret bfloat %r
;}

;define bfloat @test_fabs(bfloat %a) #0 {
;  %r = call bfloat @llvm.fabs.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_fneg(bfloat %a) #0 {
;  %r = fneg bfloat %a
;  ret bfloat %r
;}

;define bfloat @test_minnum(bfloat %a, bfloat %b) #0 {
;  %r = call bfloat @llvm.minnum.bf16(bfloat %a, bfloat %b)
;  ret bfloat %r
;}

;define bfloat @test_maxnum(bfloat %a, bfloat %b) #0 {
;  %r = call bfloat @llvm.maxnum.bf16(bfloat %a, bfloat %b)
;  ret bfloat %r
;}

define bfloat @test_copysign(bfloat %a, bfloat %b) #0 {
; CHECK-CVT-LABEL: test_copysign:
; CHECK-CVT:       @ %bb.0:
; CHECK-CVT-NEXT:    vmov r0, s1
; CHECK-CVT-NEXT:    vmov r1, s0
; CHECK-CVT-NEXT:    lsr r0, r0, #15
; CHECK-CVT-NEXT:    bfi r1, r0, #15, #17
; CHECK-CVT-NEXT:    vmov s0, r1
; CHECK-CVT-NEXT:    bx lr
;
; CHECK-BF16-LABEL: test_copysign:
; CHECK-BF16:       @ %bb.0:
; CHECK-BF16-NEXT:    .pad #12
; CHECK-BF16-NEXT:    sub sp, sp, #12
; CHECK-BF16-NEXT:    vmov r0, s0
; CHECK-BF16-NEXT:    vmov r1, s1
; CHECK-BF16-NEXT:    strh r0, [sp, #10]
; CHECK-BF16-NEXT:    ldrh r0, [sp, #10]
; CHECK-BF16-NEXT:    strh r1, [sp, #8]
; CHECK-BF16-NEXT:    ldrh r1, [sp, #8]
; CHECK-BF16-NEXT:    strh r1, [sp, #4]
; CHECK-BF16-NEXT:    ldrb r1, [sp, #5]
; CHECK-BF16-NEXT:    strh r0, [sp]
; CHECK-BF16-NEXT:    ldrb r0, [sp, #1]
; CHECK-BF16-NEXT:    and r1, r1, #128
; CHECK-BF16-NEXT:    and r0, r0, #127
; CHECK-BF16-NEXT:    orr r0, r0, r1
; CHECK-BF16-NEXT:    strb r0, [sp, #1]
; CHECK-BF16-NEXT:    ldrh r0, [sp]
; CHECK-BF16-NEXT:    vmov s0, r0
; CHECK-BF16-NEXT:    add sp, sp, #12
; CHECK-BF16-NEXT:    bx lr
  %r = call bfloat @llvm.copysign.bf16(bfloat %a, bfloat %b)
  ret bfloat %r
}

define bfloat @test_copysign_f32(bfloat %a, float %b) #0 {
; CHECK-CVT-LABEL: test_copysign_f32:
; CHECK-CVT:       @ %bb.0:
; CHECK-CVT-NEXT:    vmov r0, s0
; CHECK-CVT-NEXT:    vmov r1, s1
; CHECK-CVT-NEXT:    and r1, r1, #-2147483648
; CHECK-CVT-NEXT:    bfc r0, #15, #17
; CHECK-CVT-NEXT:    orr r0, r0, r1, lsr #16
; CHECK-CVT-NEXT:    vmov s0, r0
; CHECK-CVT-NEXT:    bx lr
;
; CHECK-BF16-LABEL: test_copysign_f32:
; CHECK-BF16:       @ %bb.0:
; CHECK-BF16-NEXT:    .pad #8
; CHECK-BF16-NEXT:    sub sp, sp, #8
; CHECK-BF16-NEXT:    vmov r0, s0
; CHECK-BF16-NEXT:    vmov r1, s1
; CHECK-BF16-NEXT:    strh r0, [sp, #6]
; CHECK-BF16-NEXT:    ldrh r0, [sp, #6]
; CHECK-BF16-NEXT:    strh r0, [sp]
; CHECK-BF16-NEXT:    and r1, r1, #-2147483648
; CHECK-BF16-NEXT:    ldrb r0, [sp, #1]
; CHECK-BF16-NEXT:    and r0, r0, #127
; CHECK-BF16-NEXT:    orr r0, r0, r1, lsr #24
; CHECK-BF16-NEXT:    strb r0, [sp, #1]
; CHECK-BF16-NEXT:    ldrh r0, [sp]
; CHECK-BF16-NEXT:    vmov s0, r0
; CHECK-BF16-NEXT:    add sp, sp, #8
; CHECK-BF16-NEXT:    bx lr
  %tb = fptrunc float %b to bfloat
  %r = call bfloat @llvm.copysign.bf16(bfloat %a, bfloat %tb)
  ret bfloat %r
}

define bfloat @test_copysign_f64(bfloat %a, double %b) #0 {
; CHECK-CVT-LABEL: test_copysign_f64:
; CHECK-CVT:       @ %bb.0:
; CHECK-CVT-NEXT:    vmov r0, s0
; CHECK-CVT-NEXT:    vmov r1, r2, d1
; CHECK-CVT-NEXT:    and r1, r2, #-2147483648
; CHECK-CVT-NEXT:    bfc r0, #15, #17
; CHECK-CVT-NEXT:    orr r0, r0, r1, lsr #16
; CHECK-CVT-NEXT:    vmov s0, r0
; CHECK-CVT-NEXT:    bx lr
;
; CHECK-BF16-LABEL: test_copysign_f64:
; CHECK-BF16:       @ %bb.0:
; CHECK-BF16-NEXT:    .pad #24
; CHECK-BF16-NEXT:    sub sp, sp, #24
; CHECK-BF16-NEXT:    vmov r0, s0
; CHECK-BF16-NEXT:    strh r0, [sp, #22]
; CHECK-BF16-NEXT:    ldrh r0, [sp, #22]
; CHECK-BF16-NEXT:    vstr d1, [sp, #8]
; CHECK-BF16-NEXT:    ldrb r1, [sp, #15]
; CHECK-BF16-NEXT:    strh r0, [sp, #4]
; CHECK-BF16-NEXT:    ldrb r0, [sp, #5]
; CHECK-BF16-NEXT:    and r1, r1, #128
; CHECK-BF16-NEXT:    and r0, r0, #127
; CHECK-BF16-NEXT:    orr r0, r0, r1
; CHECK-BF16-NEXT:    strb r0, [sp, #5]
; CHECK-BF16-NEXT:    ldrh r0, [sp, #4]
; CHECK-BF16-NEXT:    vmov s0, r0
; CHECK-BF16-NEXT:    add sp, sp, #24
; CHECK-BF16-NEXT:    bx lr
  %tb = fptrunc double %b to bfloat
  %r = call bfloat @llvm.copysign.bf16(bfloat %a, bfloat %tb)
  ret bfloat %r
}

; away the (fpext (fp_round <result>)) here.

;define float @test_copysign_extended(bfloat %a, bfloat %b) #0 {
;  %r = call bfloat @llvm.copysign.bf16(bfloat %a, bfloat %b)
;  %xr = fpext bfloat %r to float
;  ret float %xr
;}

;define bfloat @test_floor(bfloat %a) #0 {
;  %r = call bfloat @llvm.floor.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_ceil(bfloat %a) #0 {
;  %r = call bfloat @llvm.ceil.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_trunc(bfloat %a) #0 {
;  %r = call bfloat @llvm.trunc.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_rint(bfloat %a) #0 {
;  %r = call bfloat @llvm.rint.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_nearbyint(bfloat %a) #0 {
;  %r = call bfloat @llvm.nearbyint.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_round(bfloat %a) #0 {
;  %r = call bfloat @llvm.round.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_roundeven(bfloat %a) #0 {
;  %r = call bfloat @llvm.roundeven.bf16(bfloat %a)
;  ret bfloat %r
;}

;define bfloat @test_fmuladd(bfloat %a, bfloat %b, bfloat %c) #0 {
;  %r = call bfloat @llvm.fmuladd.bf16(bfloat %a, bfloat %b, bfloat %c)
;  ret bfloat %r
;}

attributes #0 = { nounwind }
