; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=thumbv7m-linux-gnueabi              | FileCheck %s --check-prefixes=ANY,SOFTFLOAT
; RUN: llc < %s -mtriple=thumbv8-linux-gnueabihf -mattr=neon | FileCheck %s --check-prefixes=ANY,HARDFLOAT

define float @cbrt_f32_fmf(float %x) nounwind {
; SOFTFLOAT-LABEL: cbrt_f32_fmf:
; SOFTFLOAT:       @ %bb.0:
; SOFTFLOAT-NEXT:    .save {r7, lr}
; SOFTFLOAT-NEXT:    push {r7, lr}
; SOFTFLOAT-NEXT:    bl cbrtf
; SOFTFLOAT-NEXT:    pop {r7, pc}
;
; HARDFLOAT-LABEL: cbrt_f32_fmf:
; HARDFLOAT:       @ %bb.0:
; HARDFLOAT-NEXT:    b cbrtf
  %r = call nsz ninf afn float @llvm.cbrt.f32(float %x)
  ret float %r
}

define double @cbrt_f64_fmf(double %x) nounwind {
; SOFTFLOAT-LABEL: cbrt_f64_fmf:
; SOFTFLOAT:       @ %bb.0:
; SOFTFLOAT-NEXT:    .save {r7, lr}
; SOFTFLOAT-NEXT:    push {r7, lr}
; SOFTFLOAT-NEXT:    bl cbrt
; SOFTFLOAT-NEXT:    pop {r7, pc}
;
; HARDFLOAT-LABEL: cbrt_f64_fmf:
; HARDFLOAT:       @ %bb.0:
; HARDFLOAT-NEXT:    b cbrt
  %r = call nsz ninf afn double @llvm.cbrt.f64(double %x)
  ret double %r
}

define <4 x float> @cbrt_v4f32_fmf(<4 x float> %x) nounwind {
; SOFTFLOAT-LABEL: cbrt_v4f32_fmf:
; SOFTFLOAT:       @ %bb.0:
; SOFTFLOAT-NEXT:    .save {r4, r5, r6, r7, lr}
; SOFTFLOAT-NEXT:    push {r4, r5, r6, r7, lr}
; SOFTFLOAT-NEXT:    .pad #4
; SOFTFLOAT-NEXT:    sub sp, #4
; SOFTFLOAT-NEXT:    mov r4, r3
; SOFTFLOAT-NEXT:    mov r5, r2
; SOFTFLOAT-NEXT:    mov r6, r1
; SOFTFLOAT-NEXT:    bl cbrtf
; SOFTFLOAT-NEXT:    mov r7, r0
; SOFTFLOAT-NEXT:    mov r0, r6
; SOFTFLOAT-NEXT:    bl cbrtf
; SOFTFLOAT-NEXT:    mov r6, r0
; SOFTFLOAT-NEXT:    mov r0, r5
; SOFTFLOAT-NEXT:    bl cbrtf
; SOFTFLOAT-NEXT:    mov r5, r0
; SOFTFLOAT-NEXT:    mov r0, r4
; SOFTFLOAT-NEXT:    bl cbrtf
; SOFTFLOAT-NEXT:    mov r3, r0
; SOFTFLOAT-NEXT:    mov r0, r7
; SOFTFLOAT-NEXT:    mov r1, r6
; SOFTFLOAT-NEXT:    mov r2, r5
; SOFTFLOAT-NEXT:    add sp, #4
; SOFTFLOAT-NEXT:    pop {r4, r5, r6, r7, pc}
;
; HARDFLOAT-LABEL: cbrt_v4f32_fmf:
; HARDFLOAT:       @ %bb.0:
; HARDFLOAT-NEXT:    .save {r7, lr}
; HARDFLOAT-NEXT:    push {r7, lr}
; HARDFLOAT-NEXT:    .vsave {d8, d9, d10, d11}
; HARDFLOAT-NEXT:    vpush {d8, d9, d10, d11}
; HARDFLOAT-NEXT:    vorr q5, q0, q0
; HARDFLOAT-NEXT:    vmov.f32 s0, s23
; HARDFLOAT-NEXT:    bl cbrtf
; HARDFLOAT-NEXT:    vmov.f32 s19, s0
; HARDFLOAT-NEXT:    vmov.f32 s0, s22
; HARDFLOAT-NEXT:    bl cbrtf
; HARDFLOAT-NEXT:    vmov.f32 s18, s0
; HARDFLOAT-NEXT:    vmov.f32 s0, s21
; HARDFLOAT-NEXT:    bl cbrtf
; HARDFLOAT-NEXT:    vmov.f32 s17, s0
; HARDFLOAT-NEXT:    vmov.f32 s0, s20
; HARDFLOAT-NEXT:    bl cbrtf
; HARDFLOAT-NEXT:    vmov.f32 s16, s0
; HARDFLOAT-NEXT:    vorr q0, q4, q4
; HARDFLOAT-NEXT:    vpop {d8, d9, d10, d11}
; HARDFLOAT-NEXT:    pop {r7, pc}
  %r = call fast <4 x float> @llvm.cbrt.v4f32(<4 x float> %x)
  ret <4 x float> %r
}

define <2 x double> @cbrt_v2f64_fmf(<2 x double> %x) nounwind {
; SOFTFLOAT-LABEL: cbrt_v2f64_fmf:
; SOFTFLOAT:       @ %bb.0:
; SOFTFLOAT-NEXT:    .save {r4, r5, r6, r7, lr}
; SOFTFLOAT-NEXT:    push {r4, r5, r6, r7, lr}
; SOFTFLOAT-NEXT:    .pad #4
; SOFTFLOAT-NEXT:    sub sp, #4
; SOFTFLOAT-NEXT:    mov r4, r3
; SOFTFLOAT-NEXT:    mov r5, r2
; SOFTFLOAT-NEXT:    bl cbrt
; SOFTFLOAT-NEXT:    mov r6, r0
; SOFTFLOAT-NEXT:    mov r7, r1
; SOFTFLOAT-NEXT:    mov r0, r5
; SOFTFLOAT-NEXT:    mov r1, r4
; SOFTFLOAT-NEXT:    bl cbrt
; SOFTFLOAT-NEXT:    mov r2, r0
; SOFTFLOAT-NEXT:    mov r3, r1
; SOFTFLOAT-NEXT:    mov r0, r6
; SOFTFLOAT-NEXT:    mov r1, r7
; SOFTFLOAT-NEXT:    add sp, #4
; SOFTFLOAT-NEXT:    pop {r4, r5, r6, r7, pc}
;
; HARDFLOAT-LABEL: cbrt_v2f64_fmf:
; HARDFLOAT:       @ %bb.0:
; HARDFLOAT-NEXT:    .save {r7, lr}
; HARDFLOAT-NEXT:    push {r7, lr}
; HARDFLOAT-NEXT:    .vsave {d8, d9, d10, d11}
; HARDFLOAT-NEXT:    vpush {d8, d9, d10, d11}
; HARDFLOAT-NEXT:    vorr q4, q0, q0
; HARDFLOAT-NEXT:    vorr d0, d9, d9
; HARDFLOAT-NEXT:    bl cbrt
; HARDFLOAT-NEXT:    vorr d11, d0, d0
; HARDFLOAT-NEXT:    vorr d0, d8, d8
; HARDFLOAT-NEXT:    bl cbrt
; HARDFLOAT-NEXT:    vorr d10, d0, d0
; HARDFLOAT-NEXT:    vorr q0, q5, q5
; HARDFLOAT-NEXT:    vpop {d8, d9, d10, d11}
; HARDFLOAT-NEXT:    pop {r7, pc}
  %r = call fast <2 x double> @llvm.cbrt.v2f64(<2 x double> %x)
  ret <2 x double> %r
}

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; ANY: {{.*}}
