; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O3 -mtriple=armv7-linux-gnueabihf | FileCheck %s --check-prefix=ARM
; RUN: llc < %s -O3 -mtriple=thumbv7-linux-gnueabihf | FileCheck %s --check-prefix=THUMBV7
; RUN: llc < %s -O3 -mtriple=thumbv5-none-eabi | FileCheck %s --check-prefix=THUMBV5

define i16 @test_1cmp_signed_1(ptr %ptr1) {
; ARM-LABEL: test_1cmp_signed_1:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    ldrh r0, [r0]
; ARM-NEXT:    movw r1, #65535
; ARM-NEXT:    sub r0, r0, r1
; ARM-NEXT:    clz r0, r0
; ARM-NEXT:    lsr r0, r0, #5
; ARM-NEXT:    bx lr
;
; THUMBV7-LABEL: test_1cmp_signed_1:
; THUMBV7:       @ %bb.0: @ %entry
; THUMBV7-NEXT:    ldrh r0, [r0]
; THUMBV7-NEXT:    movw r1, #65535
; THUMBV7-NEXT:    subs r0, r0, r1
; THUMBV7-NEXT:    clz r0, r0
; THUMBV7-NEXT:    lsrs r0, r0, #5
; THUMBV7-NEXT:    bx lr
;
; THUMBV5-LABEL: test_1cmp_signed_1:
; THUMBV5:       @ %bb.0: @ %entry
; THUMBV5-NEXT:    ldrh r0, [r0]
; THUMBV5-NEXT:    ldr r1, .LCPI0_0
; THUMBV5-NEXT:    cmp r0, r1
; THUMBV5-NEXT:    beq .LBB0_2
; THUMBV5-NEXT:  @ %bb.1: @ %if.then
; THUMBV5-NEXT:    movs r0, #0
; THUMBV5-NEXT:    bx lr
; THUMBV5-NEXT:  .LBB0_2: @ %if
; THUMBV5-NEXT:    movs r0, #1
; THUMBV5-NEXT:    bx lr
; THUMBV5-NEXT:    .p2align 2
; THUMBV5-NEXT:  @ %bb.3:
; THUMBV5-NEXT:  .LCPI0_0:
; THUMBV5-NEXT:    .long 65535 @ 0xffff
entry:
  %val = load i16, ptr %ptr1, align 2
  %cmp = icmp eq i16 %val, -1
  br i1 %cmp, label %if, label %if.then
if:
  ret i16 1
if.then:
  ret i16 0
}

define i16 @test_1cmp_signed_2(ptr %ptr1) {
; ARM-LABEL: test_1cmp_signed_2:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    ldrsh r1, [r0]
; ARM-NEXT:    mov r0, #0
; ARM-NEXT:    cmn r1, #2
; ARM-NEXT:    movwgt r0, #1
; ARM-NEXT:    bx lr
;
; THUMBV7-LABEL: test_1cmp_signed_2:
; THUMBV7:       @ %bb.0: @ %entry
; THUMBV7-NEXT:    ldrsh.w r1, [r0]
; THUMBV7-NEXT:    movs r0, #0
; THUMBV7-NEXT:    cmn.w r1, #2
; THUMBV7-NEXT:    it gt
; THUMBV7-NEXT:    movgt r0, #1
; THUMBV7-NEXT:    bx lr
;
; THUMBV5-LABEL: test_1cmp_signed_2:
; THUMBV5:       @ %bb.0: @ %entry
; THUMBV5-NEXT:    movs r1, #0
; THUMBV5-NEXT:    mvns r1, r1
; THUMBV5-NEXT:    ldrh r0, [r0]
; THUMBV5-NEXT:    lsls r0, r0, #16
; THUMBV5-NEXT:    asrs r0, r0, #16
; THUMBV5-NEXT:    cmp r0, r1
; THUMBV5-NEXT:    blt .LBB1_2
; THUMBV5-NEXT:  @ %bb.1: @ %if
; THUMBV5-NEXT:    movs r0, #1
; THUMBV5-NEXT:    bx lr
; THUMBV5-NEXT:  .LBB1_2: @ %if.then
; THUMBV5-NEXT:    movs r0, #0
; THUMBV5-NEXT:    bx lr
entry:
  %val = load i16, ptr %ptr1, align 2
  %cmp = icmp sge i16 %val, -1
  br i1 %cmp, label %if, label %if.then
if:
  ret i16 1
if.then:
  ret i16 0
}

define i16 @test_1cmp_unsigned_1(ptr %ptr1) {
; ARM-LABEL: test_1cmp_unsigned_1:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    ldrh r0, [r0]
; ARM-NEXT:    movw r1, #65535
; ARM-NEXT:    sub r0, r0, r1
; ARM-NEXT:    clz r0, r0
; ARM-NEXT:    lsr r0, r0, #5
; ARM-NEXT:    bx lr
;
; THUMBV7-LABEL: test_1cmp_unsigned_1:
; THUMBV7:       @ %bb.0: @ %entry
; THUMBV7-NEXT:    ldrh r0, [r0]
; THUMBV7-NEXT:    movw r1, #65535
; THUMBV7-NEXT:    subs r0, r0, r1
; THUMBV7-NEXT:    clz r0, r0
; THUMBV7-NEXT:    lsrs r0, r0, #5
; THUMBV7-NEXT:    bx lr
;
; THUMBV5-LABEL: test_1cmp_unsigned_1:
; THUMBV5:       @ %bb.0: @ %entry
; THUMBV5-NEXT:    ldrh r0, [r0]
; THUMBV5-NEXT:    ldr r1, .LCPI2_0
; THUMBV5-NEXT:    cmp r0, r1
; THUMBV5-NEXT:    bne .LBB2_2
; THUMBV5-NEXT:  @ %bb.1: @ %if
; THUMBV5-NEXT:    movs r0, #1
; THUMBV5-NEXT:    bx lr
; THUMBV5-NEXT:  .LBB2_2: @ %if.then
; THUMBV5-NEXT:    movs r0, #0
; THUMBV5-NEXT:    bx lr
; THUMBV5-NEXT:    .p2align 2
; THUMBV5-NEXT:  @ %bb.3:
; THUMBV5-NEXT:  .LCPI2_0:
; THUMBV5-NEXT:    .long 65535 @ 0xffff
entry:
  %val = load i16, ptr %ptr1, align 2
  %cmp = icmp uge i16 %val, -1
  br i1 %cmp, label %if, label %if.then
if:
  ret i16 1
if.then:
  ret i16 0
}
