; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=armv7-- < %s | FileCheck %s

define void @copy_undef_propogate(i32 %in, ptr %out) {
; CHECK-LABEL: copy_undef_propogate:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    vmov.32 d17[0], r0
; CHECK-NEXT:    @ implicit-def: $r0
; CHECK-NEXT:  .LBB0_1: @ %for.cond
; CHECK-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vmov.32 d16[0], r0
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    vmov.32 d16[1], r0
; CHECK-NEXT:    add r0, r0, #1
; CHECK-NEXT:    vst1.32 {d16, d17}, [r2:128]!
; CHECK-NEXT:    vst1.64 {d16, d17}, [r2:128]
; CHECK-NEXT:    b .LBB0_1
entry:
  %1 = insertelement <8 x i32> <i32 undef, i32 undef, i32 undef, i32 undef, i32 poison, i32 poison, i32 poison, i32 undef>, i32 %in, i64 6
  br label %for.cond

for.cond:
  %i.0 = phi i32 [ undef, %entry ], [ %inc, %for.cond ]
  %2 = insertelement <8 x i32> %1, i32 %i.0, i64 4
  %3 = insertelement <8 x i32> %2, i32 %i.0, i64 5
  store <8 x i32> %3, ptr %out
  %inc = add nsw i32 %i.0, 1
  br label %for.cond
}

