; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=armv7-none-eabi -verify-machineinstrs | FileCheck --check-prefixes=CT %s
; RUN: llc < %s -mtriple=armv6 -verify-machineinstrs | FileCheck --check-prefix=DEFAULT %s
; RUN: llc < %s -mtriple=thumbv6m-none-eabi -verify-machineinstrs | FileCheck --check-prefix=THUMB1 %s
; RUN: llc < %s -mtriple=thumbv7m-none-eabi -verify-machineinstrs | FileCheck --check-prefix=THUMB2 %s
; RUN: llc < %s -mtriple=thumbv7-linux-gnueabihf -mcpu=cortex-a9 -verify-machineinstrs | FileCheck --check-prefix=CORTEXA9 %s
; RUN: llc < %s -mtriple=armv7-linux-gnueabihf -mcpu=cortex-a9 -verify-machineinstrs | FileCheck --check-prefix=CORTEX-NOTHUMB %s

define i1 @ct_i1(i1 %cond, i1 %a, i1 %b) {
; CT-LABEL: ct_i1:
; CT:       @ %bb.0: @ %entry
; CT-NEXT:    and r3, r0, #1
; CT-NEXT:    BUNDLE
; CT-NEXT:    bx lr
;
; DEFAULT-LABEL: ct_i1:
; DEFAULT:       @ %bb.0: @ %entry
; DEFAULT-NEXT:    and r3, r0, #1
; DEFAULT-NEXT:    BUNDLE
; DEFAULT-NEXT:    bx lr
;
; THUMB1-LABEL: ct_i1:
; THUMB1:       @ %bb.0: @ %entry
; THUMB1-NEXT:    .save {r4, lr}
; THUMB1-NEXT:    push {r4, lr}
; THUMB1-NEXT:    movs r3, #1
; THUMB1-NEXT:    ands r3, r0
; THUMB1-NEXT:    BUNDLE
; THUMB1-NEXT:    pop {r4, pc}
;
; THUMB2-LABEL: ct_i1:
; THUMB2:       @ %bb.0: @ %entry
; THUMB2-NEXT:    and r3, r0, #1
; THUMB2-NEXT:    rsb.w r12, r3, #0
; THUMB2-NEXT:    and.w r0, r1, r12
; THUMB2-NEXT:    bic.w r12, r2, r12
; THUMB2-NEXT:    orr.w r0, r0, r12
; THUMB2-NEXT:    bx lr
;
; CORTEXA9-LABEL: ct_i1:
; CORTEXA9:       @ %bb.0: @ %entry
; CORTEXA9-NEXT:    and r3, r0, #1
; CORTEXA9-NEXT:    rsb.w r12, r3, #0
; CORTEXA9-NEXT:    and.w r0, r1, r12
; CORTEXA9-NEXT:    bic.w r12, r2, r12
; CORTEXA9-NEXT:    orr.w r0, r0, r12
; CORTEXA9-NEXT:    bx lr
;
; CORTEX-NOTHUMB-LABEL: ct_i1:
; CORTEX-NOTHUMB:       @ %bb.0: @ %entry
; CORTEX-NOTHUMB-NEXT:    and r3, r0, #1
; CORTEX-NOTHUMB-NEXT:    BUNDLE
; CORTEX-NOTHUMB-NEXT:    bx lr
entry:
  %sel = call i1 @llvm.ct.select.i1(i1 %cond, i1 %a, i1 %b)
  ret i1 %sel
}

define i8 @ct_int8(i1 %cond, i8 %a, i8 %b) {
; CT-LABEL: ct_int8:
; CT:       @ %bb.0: @ %entry
; CT-NEXT:    and r3, r0, #1
; CT-NEXT:    BUNDLE
; CT-NEXT:    bx lr
;
; DEFAULT-LABEL: ct_int8:
; DEFAULT:       @ %bb.0: @ %entry
; DEFAULT-NEXT:    and r3, r0, #1
; DEFAULT-NEXT:    BUNDLE
; DEFAULT-NEXT:    bx lr
;
; THUMB1-LABEL: ct_int8:
; THUMB1:       @ %bb.0: @ %entry
; THUMB1-NEXT:    .save {r4, lr}
; THUMB1-NEXT:    push {r4, lr}
; THUMB1-NEXT:    movs r3, #1
; THUMB1-NEXT:    ands r3, r0
; THUMB1-NEXT:    BUNDLE
; THUMB1-NEXT:    pop {r4, pc}
;
; THUMB2-LABEL: ct_int8:
; THUMB2:       @ %bb.0: @ %entry
; THUMB2-NEXT:    and r3, r0, #1
; THUMB2-NEXT:    rsb.w r12, r3, #0
; THUMB2-NEXT:    and.w r0, r1, r12
; THUMB2-NEXT:    bic.w r12, r2, r12
; THUMB2-NEXT:    orr.w r0, r0, r12
; THUMB2-NEXT:    bx lr
;
; CORTEXA9-LABEL: ct_int8:
; CORTEXA9:       @ %bb.0: @ %entry
; CORTEXA9-NEXT:    and r3, r0, #1
; CORTEXA9-NEXT:    rsb.w r12, r3, #0
; CORTEXA9-NEXT:    and.w r0, r1, r12
; CORTEXA9-NEXT:    bic.w r12, r2, r12
; CORTEXA9-NEXT:    orr.w r0, r0, r12
; CORTEXA9-NEXT:    bx lr
;
; CORTEX-NOTHUMB-LABEL: ct_int8:
; CORTEX-NOTHUMB:       @ %bb.0: @ %entry
; CORTEX-NOTHUMB-NEXT:    and r3, r0, #1
; CORTEX-NOTHUMB-NEXT:    BUNDLE
; CORTEX-NOTHUMB-NEXT:    bx lr
entry:
  %sel = call i8 @llvm.ct.select.i8(i1 %cond, i8 %a, i8 %b)
  ret i8 %sel
}

define i16 @ct_int16(i1 %cond, i16 %a, i16 %b) {
; CT-LABEL: ct_int16:
; CT:       @ %bb.0: @ %entry
; CT-NEXT:    and r3, r0, #1
; CT-NEXT:    BUNDLE
; CT-NEXT:    bx lr
;
; DEFAULT-LABEL: ct_int16:
; DEFAULT:       @ %bb.0: @ %entry
; DEFAULT-NEXT:    and r3, r0, #1
; DEFAULT-NEXT:    BUNDLE
; DEFAULT-NEXT:    bx lr
;
; THUMB1-LABEL: ct_int16:
; THUMB1:       @ %bb.0: @ %entry
; THUMB1-NEXT:    .save {r4, lr}
; THUMB1-NEXT:    push {r4, lr}
; THUMB1-NEXT:    movs r3, #1
; THUMB1-NEXT:    ands r3, r0
; THUMB1-NEXT:    BUNDLE
; THUMB1-NEXT:    pop {r4, pc}
;
; THUMB2-LABEL: ct_int16:
; THUMB2:       @ %bb.0: @ %entry
; THUMB2-NEXT:    and r3, r0, #1
; THUMB2-NEXT:    rsb.w r12, r3, #0
; THUMB2-NEXT:    and.w r0, r1, r12
; THUMB2-NEXT:    bic.w r12, r2, r12
; THUMB2-NEXT:    orr.w r0, r0, r12
; THUMB2-NEXT:    bx lr
;
; CORTEXA9-LABEL: ct_int16:
; CORTEXA9:       @ %bb.0: @ %entry
; CORTEXA9-NEXT:    and r3, r0, #1
; CORTEXA9-NEXT:    rsb.w r12, r3, #0
; CORTEXA9-NEXT:    and.w r0, r1, r12
; CORTEXA9-NEXT:    bic.w r12, r2, r12
; CORTEXA9-NEXT:    orr.w r0, r0, r12
; CORTEXA9-NEXT:    bx lr
;
; CORTEX-NOTHUMB-LABEL: ct_int16:
; CORTEX-NOTHUMB:       @ %bb.0: @ %entry
; CORTEX-NOTHUMB-NEXT:    and r3, r0, #1
; CORTEX-NOTHUMB-NEXT:    BUNDLE
; CORTEX-NOTHUMB-NEXT:    bx lr
entry:
  %sel = call i16 @llvm.ct.select.i16(i1 %cond, i16 %a, i16 %b)
  ret i16 %sel
}

define i32 @ct_int32(i1 %cond, i32 %a, i32 %b) {
; CT-LABEL: ct_int32:
; CT:       @ %bb.0: @ %entry
; CT-NEXT:    and r3, r0, #1
; CT-NEXT:    BUNDLE
; CT-NEXT:    bx lr
;
; DEFAULT-LABEL: ct_int32:
; DEFAULT:       @ %bb.0: @ %entry
; DEFAULT-NEXT:    and r3, r0, #1
; DEFAULT-NEXT:    BUNDLE
; DEFAULT-NEXT:    bx lr
;
; THUMB1-LABEL: ct_int32:
; THUMB1:       @ %bb.0: @ %entry
; THUMB1-NEXT:    .save {r4, lr}
; THUMB1-NEXT:    push {r4, lr}
; THUMB1-NEXT:    movs r3, #1
; THUMB1-NEXT:    ands r3, r0
; THUMB1-NEXT:    BUNDLE
; THUMB1-NEXT:    pop {r4, pc}
;
; THUMB2-LABEL: ct_int32:
; THUMB2:       @ %bb.0: @ %entry
; THUMB2-NEXT:    and r3, r0, #1
; THUMB2-NEXT:    rsb.w r12, r3, #0
; THUMB2-NEXT:    and.w r0, r1, r12
; THUMB2-NEXT:    bic.w r12, r2, r12
; THUMB2-NEXT:    orr.w r0, r0, r12
; THUMB2-NEXT:    bx lr
;
; CORTEXA9-LABEL: ct_int32:
; CORTEXA9:       @ %bb.0: @ %entry
; CORTEXA9-NEXT:    and r3, r0, #1
; CORTEXA9-NEXT:    rsb.w r12, r3, #0
; CORTEXA9-NEXT:    and.w r0, r1, r12
; CORTEXA9-NEXT:    bic.w r12, r2, r12
; CORTEXA9-NEXT:    orr.w r0, r0, r12
; CORTEXA9-NEXT:    bx lr
;
; CORTEX-NOTHUMB-LABEL: ct_int32:
; CORTEX-NOTHUMB:       @ %bb.0: @ %entry
; CORTEX-NOTHUMB-NEXT:    and r3, r0, #1
; CORTEX-NOTHUMB-NEXT:    BUNDLE
; CORTEX-NOTHUMB-NEXT:    bx lr
entry:
  %sel = call i32 @llvm.ct.select.i32(i1 %cond, i32 %a, i32 %b)
  ret i32 %sel
}

define i64 @ct_int64(i1 %cond, i64 %a, i64 %b) {
; CT-LABEL: ct_int64:
; CT:       @ %bb.0: @ %entry
; CT-NEXT:    .save {r4, lr}
; CT-NEXT:    push {r4, lr}
; CT-NEXT:    ldr r1, [sp, #8]
; CT-NEXT:    and lr, r0, #1
; CT-NEXT:    ldr r12, [sp, #12]
; CT-NEXT:    BUNDLE
; CT-NEXT:    BUNDLE
; CT-NEXT:    pop {r4, pc}
;
; DEFAULT-LABEL: ct_int64:
; DEFAULT:       @ %bb.0: @ %entry
; DEFAULT-NEXT:    push {r11, lr}
; DEFAULT-NEXT:    and r12, r0, #1
; DEFAULT-NEXT:    ldr r1, [sp, #8]
; DEFAULT-NEXT:    BUNDLE
; DEFAULT-NEXT:    ldr r2, [sp, #12]
; DEFAULT-NEXT:    BUNDLE
; DEFAULT-NEXT:    pop {r11, pc}
;
; THUMB1-LABEL: ct_int64:
; THUMB1:       @ %bb.0: @ %entry
; THUMB1-NEXT:    .save {r4, r5, r7, lr}
; THUMB1-NEXT:    push {r4, r5, r7, lr}
; THUMB1-NEXT:    movs r4, #1
; THUMB1-NEXT:    ands r4, r0
; THUMB1-NEXT:    ldr r1, [sp, #16]
; THUMB1-NEXT:    BUNDLE
; THUMB1-NEXT:    ldr r2, [sp, #20]
; THUMB1-NEXT:    BUNDLE
; THUMB1-NEXT:    pop {r4, r5, r7, pc}
;
; THUMB2-LABEL: ct_int64:
; THUMB2:       @ %bb.0: @ %entry
; THUMB2-NEXT:    .save {r7, lr}
; THUMB2-NEXT:    push {r7, lr}
; THUMB2-NEXT:    and r12, r0, #1
; THUMB2-NEXT:    ldr r1, [sp, #8]
; THUMB2-NEXT:    rsb.w lr, r12, #0
; THUMB2-NEXT:    and.w r0, r2, lr
; THUMB2-NEXT:    bic.w lr, r1, lr
; THUMB2-NEXT:    orr.w r0, r0, lr
; THUMB2-NEXT:    ldr r2, [sp, #12]
; THUMB2-NEXT:    rsb.w lr, r12, #0
; THUMB2-NEXT:    and.w r1, r3, lr
; THUMB2-NEXT:    bic.w lr, r2, lr
; THUMB2-NEXT:    orr.w r1, r1, lr
; THUMB2-NEXT:    pop {r7, pc}
;
; CORTEXA9-LABEL: ct_int64:
; CORTEXA9:       @ %bb.0: @ %entry
; CORTEXA9-NEXT:    .save {r4, lr}
; CORTEXA9-NEXT:    push {r4, lr}
; CORTEXA9-NEXT:    ldrd r1, r12, [sp, #8]
; CORTEXA9-NEXT:    and lr, r0, #1
; CORTEXA9-NEXT:    rsb.w r4, lr, #0
; CORTEXA9-NEXT:    and.w r0, r2, r4
; CORTEXA9-NEXT:    bic.w r4, r1, r4
; CORTEXA9-NEXT:    orrs r0, r4
; CORTEXA9-NEXT:    rsb.w r2, lr, #0
; CORTEXA9-NEXT:    and.w r1, r3, r2
; CORTEXA9-NEXT:    bic.w r2, r12, r2
; CORTEXA9-NEXT:    orr.w r1, r1, r2
; CORTEXA9-NEXT:    pop {r4, pc}
;
; CORTEX-NOTHUMB-LABEL: ct_int64:
; CORTEX-NOTHUMB:       @ %bb.0: @ %entry
; CORTEX-NOTHUMB-NEXT:    .save {r4, lr}
; CORTEX-NOTHUMB-NEXT:    push {r4, lr}
; CORTEX-NOTHUMB-NEXT:    ldr r12, [sp, #12]
; CORTEX-NOTHUMB-NEXT:    and lr, r0, #1
; CORTEX-NOTHUMB-NEXT:    ldr r1, [sp, #8]
; CORTEX-NOTHUMB-NEXT:    BUNDLE
; CORTEX-NOTHUMB-NEXT:    BUNDLE
; CORTEX-NOTHUMB-NEXT:    pop {r4, pc}
entry:
  %sel = call i64 @llvm.ct.select.i64(i1 %cond, i64 %a, i64 %b)
  ret i64 %sel
}

define float @ct_float(i1 %cond, float %a, float %b) {
; CT-LABEL: ct_float:
; CT:       @ %bb.0: @ %entry
; CT-NEXT:    and r0, r0, #1
; CT-NEXT:    vmov s0, r2
; CT-NEXT:    vmov s2, r1
; CT-NEXT:    BUNDLE
; CT-NEXT:    vmov r0, s4
; CT-NEXT:    bx lr
;
; DEFAULT-LABEL: ct_float:
; DEFAULT:       @ %bb.0: @ %entry
; DEFAULT-NEXT:    and r3, r0, #1
; DEFAULT-NEXT:    BUNDLE
; DEFAULT-NEXT:    bx lr
;
; THUMB1-LABEL: ct_float:
; THUMB1:       @ %bb.0: @ %entry
; THUMB1-NEXT:    .save {r4, lr}
; THUMB1-NEXT:    push {r4, lr}
; THUMB1-NEXT:    movs r3, #1
; THUMB1-NEXT:    ands r3, r0
; THUMB1-NEXT:    BUNDLE
; THUMB1-NEXT:    pop {r4, pc}
;
; THUMB2-LABEL: ct_float:
; THUMB2:       @ %bb.0: @ %entry
; THUMB2-NEXT:    and r3, r0, #1
; THUMB2-NEXT:    rsb.w r12, r3, #0
; THUMB2-NEXT:    and.w r0, r1, r12
; THUMB2-NEXT:    bic.w r12, r2, r12
; THUMB2-NEXT:    orr.w r0, r0, r12
; THUMB2-NEXT:    bx lr
;
; CORTEXA9-LABEL: ct_float:
; CORTEXA9:       @ %bb.0: @ %entry
; CORTEXA9-NEXT:    and r0, r0, #1
; CORTEXA9-NEXT:    vmov r2, s0
; CORTEXA9-NEXT:    vmov r3, s1
; CORTEXA9-NEXT:    rsbs r1, r0, #0
; CORTEXA9-NEXT:    ands r2, r1
; CORTEXA9-NEXT:    bic.w r1, r3, r1
; CORTEXA9-NEXT:    orrs r2, r1
; CORTEXA9-NEXT:    vmov s2, r2
; CORTEXA9-NEXT:    vmov.f32 s0, s2
; CORTEXA9-NEXT:    bx lr
;
; CORTEX-NOTHUMB-LABEL: ct_float:
; CORTEX-NOTHUMB:       @ %bb.0: @ %entry
; CORTEX-NOTHUMB-NEXT:    and r0, r0, #1
; CORTEX-NOTHUMB-NEXT:    BUNDLE
; CORTEX-NOTHUMB-NEXT:    vmov.f32 s0, s2
; CORTEX-NOTHUMB-NEXT:    bx lr
entry:
  %sel = call float @llvm.ct.select.f32(i1 %cond, float %a, float %b)
  ret float %sel
}

define double @ct_f64(i1 %cond, double %a, double %b) {
; CT-LABEL: ct_f64:
; CT:       @ %bb.0: @ %entry
; CT-NEXT:    vldr d16, [sp]
; CT-NEXT:    vmov d17, r2, r3
; CT-NEXT:    and r0, r0, #1
; CT-NEXT:    BUNDLE
; CT-NEXT:    vmov r0, r1, d18
; CT-NEXT:    bx lr
;
; DEFAULT-LABEL: ct_f64:
; DEFAULT:       @ %bb.0: @ %entry
; DEFAULT-NEXT:    push {r11, lr}
; DEFAULT-NEXT:    and r12, r0, #1
; DEFAULT-NEXT:    ldr r1, [sp, #8]
; DEFAULT-NEXT:    BUNDLE
; DEFAULT-NEXT:    ldr r2, [sp, #12]
; DEFAULT-NEXT:    BUNDLE
; DEFAULT-NEXT:    pop {r11, pc}
;
; THUMB1-LABEL: ct_f64:
; THUMB1:       @ %bb.0: @ %entry
; THUMB1-NEXT:    .save {r4, r5, r7, lr}
; THUMB1-NEXT:    push {r4, r5, r7, lr}
; THUMB1-NEXT:    movs r4, #1
; THUMB1-NEXT:    ands r4, r0
; THUMB1-NEXT:    ldr r1, [sp, #16]
; THUMB1-NEXT:    BUNDLE
; THUMB1-NEXT:    ldr r2, [sp, #20]
; THUMB1-NEXT:    BUNDLE
; THUMB1-NEXT:    pop {r4, r5, r7, pc}
;
; THUMB2-LABEL: ct_f64:
; THUMB2:       @ %bb.0: @ %entry
; THUMB2-NEXT:    .save {r7, lr}
; THUMB2-NEXT:    push {r7, lr}
; THUMB2-NEXT:    and r12, r0, #1
; THUMB2-NEXT:    ldr r1, [sp, #8]
; THUMB2-NEXT:    rsb.w lr, r12, #0
; THUMB2-NEXT:    and.w r0, r2, lr
; THUMB2-NEXT:    bic.w lr, r1, lr
; THUMB2-NEXT:    orr.w r0, r0, lr
; THUMB2-NEXT:    ldr r2, [sp, #12]
; THUMB2-NEXT:    rsb.w lr, r12, #0
; THUMB2-NEXT:    and.w r1, r3, lr
; THUMB2-NEXT:    bic.w lr, r2, lr
; THUMB2-NEXT:    orr.w r1, r1, lr
; THUMB2-NEXT:    pop {r7, pc}
;
; CORTEXA9-LABEL: ct_f64:
; CORTEXA9:       @ %bb.0: @ %entry
; CORTEXA9-NEXT:    and r0, r0, #1
; CORTEXA9-NEXT:    rsbs r1, r0, #0
; CORTEXA9-NEXT:    vdup.32 d17, r1
; CORTEXA9-NEXT:    vand d16, d0, d17
; CORTEXA9-NEXT:    vbic d17, d1, d17
; CORTEXA9-NEXT:    vorr d16, d16, d17
; CORTEXA9-NEXT:    vmov.f64 d0, d16
; CORTEXA9-NEXT:    bx lr
;
; CORTEX-NOTHUMB-LABEL: ct_f64:
; CORTEX-NOTHUMB:       @ %bb.0: @ %entry
; CORTEX-NOTHUMB-NEXT:    and r0, r0, #1
; CORTEX-NOTHUMB-NEXT:    BUNDLE
; CORTEX-NOTHUMB-NEXT:    vmov.f64 d0, d16
; CORTEX-NOTHUMB-NEXT:    bx lr
entry:
  %sel = call double @llvm.ct.select.f64(i1 %cond, double %a, double %b)
  ret double %sel
}
