; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=armv6-none-eabi < %s | FileCheck %s

define i32 @zext_u8_from_shift8(i32 %0) {
; CHECK-LABEL: zext_u8_from_shift8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    uxtb r0, r0, ror #8
; CHECK-NEXT:    bx lr
  %2 = lshr i32 %0, 8
  %3 = and i32 %2, 255
  ret i32 %3
}

define i32 @zext_u8_from_shift16(i32 %0) {
; CHECK-LABEL: zext_u8_from_shift16:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    uxtb r0, r0, ror #16
; CHECK-NEXT:    bx lr
  %2 = lshr i32 %0, 16
  %3 = and i32 %2, 255
  ret i32 %3
}

define i32 @sext_i8_from_bits8(i32 %0) {
; CHECK-LABEL: sext_i8_from_bits8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    sxtb r0, r0, ror #8
; CHECK-NEXT:    bx lr
  %2 = shl i32 %0, 16
  %3 = ashr i32 %2, 24
  ret i32 %3
}

define i32 @sext_i8_from_bits16(i32 %0) {
; CHECK-LABEL: sext_i8_from_bits16:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    sxtb r0, r0, ror #16
; CHECK-NEXT:    bx lr
  %2 = shl i32 %0, 8
  %3 = ashr i32 %2, 24
  ret i32 %3
}

define i32 @zext_u16_from_shift8(i32 %0) {
; CHECK-LABEL: zext_u16_from_shift8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    uxth r0, r0, ror #8
; CHECK-NEXT:    bx lr
  %2 = lshr i32 %0, 8
  %3 = and i32 %2, 65535
  ret i32 %3
}

define i32 @sext_i16_from_shift8(i32 %0) {
; CHECK-LABEL: sext_i16_from_shift8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    sxth r0, r0, ror #8
; CHECK-NEXT:    bx lr
  %2 = shl i32 %0, 8
  %3 = ashr i32 %2, 16
  ret i32 %3
}
