; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=armv7-none-eabihf -mattr=+vfp3 < %s | FileCheck %s

; With ARM's combineRepeatedFPDivisors() threshold set to 3:
; - 2 matching fdiv arcp uses should stay as divisions.
; - 3 matching fdiv arcp uses should become 1 reciprocal + 3 multiplies.

define void @two_fdiv_float(float %d, float %a, float %b) {
; CHECK-LABEL: two_fdiv_float:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vdiv.f32 s4, s1, s0
; CHECK-NEXT:    vdiv.f32 s1, s2, s0
; CHECK-NEXT:    vmov.f32 s0, s4
; CHECK-NEXT:    b use2
  %div0 = fdiv arcp float %a, %d
  %div1 = fdiv arcp float %b, %d
  tail call void @use2(float %div0, float %div1)
  ret void
}

define void @three_fdiv_float(float %d, float %a, float %b, float %c) {
; CHECK-LABEL: three_fdiv_float:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vdiv.f32 s4, s1, s0
; CHECK-NEXT:    vdiv.f32 s1, s2, s0
; CHECK-NEXT:    vdiv.f32 s2, s3, s0
; CHECK-NEXT:    vmov.f32 s0, s4
; CHECK-NEXT:    b use3
  %div0 = fdiv arcp float %a, %d
  %div1 = fdiv arcp float %b, %d
  %div2 = fdiv arcp float %c, %d
  tail call void @use3(float %div0, float %div1, float %div2)
  ret void
}

declare void @use2(float, float)
declare void @use3(float, float, float)
