; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple arm-eabi -mattr=+v5t | FileCheck %s --check-prefix=CHECK-5
; RUN: llc < %s -mtriple arm-eabi -mattr=+v6t2 | FileCheck %s
; RUN: llc < %s -mtriple arm-eabi -mattr=+v6t2 -mattr=+neon | FileCheck %s
; RUN: llc < %s -mtriple thumbv6m-none-eabi | FileCheck %s --check-prefix=CHECK-6M
; RUN: llc < %s -mtriple thumbv8m.base-none-eabi | FileCheck %s --check-prefix=CHECK-8MBASE

;; Check the transformation
;; CMOV(0, cttz, cc) -> AND (cttz, numbits-1)
;; for cttz in the case of i32

;; Cases for which the optimzation takes place
define i32 @cttzi32(i32 %x) {
; CHECK-5-LABEL: cttzi32:
; CHECK-5:       @ %bb.0: @ %entry
; CHECK-5-NEXT:    sub r1, r0, #1
; CHECK-5-NEXT:    cmp r0, #0
; CHECK-5-NEXT:    bic r1, r1, r0
; CHECK-5-NEXT:    clz r1, r1
; CHECK-5-NEXT:    rsbne r0, r1, #32
; CHECK-5-NEXT:    bx lr
;
; CHECK-LABEL: cttzi32:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    rbit r1, r0
; CHECK-NEXT:    cmp r0, #0
; CHECK-NEXT:    clzne r0, r1
; CHECK-NEXT:    bx lr
;
; CHECK-6M-LABEL: cttzi32:
; CHECK-6M:       @ %bb.0: @ %entry
; CHECK-6M-NEXT:    rsbs r1, r0, #0
; CHECK-6M-NEXT:    ands r1, r0
; CHECK-6M-NEXT:    ldr r2, .LCPI0_0
; CHECK-6M-NEXT:    muls r2, r1, r2
; CHECK-6M-NEXT:    lsrs r2, r2, #27
; CHECK-6M-NEXT:    movs r1, #32
; CHECK-6M-NEXT:    cmp r0, #0
; CHECK-6M-NEXT:    bne .LBB0_3
; CHECK-6M-NEXT:  @ %bb.1: @ %entry
; CHECK-6M-NEXT:    beq .LBB0_4
; CHECK-6M-NEXT:  .LBB0_2: @ %entry
; CHECK-6M-NEXT:    mov r0, r1
; CHECK-6M-NEXT:    bx lr
; CHECK-6M-NEXT:  .LBB0_3: @ %entry
; CHECK-6M-NEXT:    adr r1, .LCPI0_1
; CHECK-6M-NEXT:    ldrb r1, [r1, r2]
; CHECK-6M-NEXT:    bne .LBB0_2
; CHECK-6M-NEXT:  .LBB0_4: @ %entry
; CHECK-6M-NEXT:    mov r1, r0
; CHECK-6M-NEXT:    mov r0, r1
; CHECK-6M-NEXT:    bx lr
; CHECK-6M-NEXT:    .p2align 2
; CHECK-6M-NEXT:  @ %bb.5:
; CHECK-6M-NEXT:  .LCPI0_0:
; CHECK-6M-NEXT:    .long 125613361 @ 0x77cb531
; CHECK-6M-NEXT:  .LCPI0_1:
; CHECK-6M-NEXT:    .ascii "\000\001\034\002\035\016\030\003\036\026\024\017\031\021\004\b\037\033\r\027\025\023\020\007\032\f\022\006\013\005\n\t"
;
; CHECK-8MBASE-LABEL: cttzi32:
; CHECK-8MBASE:       @ %bb.0: @ %entry
; CHECK-8MBASE-NEXT:    rsbs r1, r0, #0
; CHECK-8MBASE-NEXT:    ands r1, r0
; CHECK-8MBASE-NEXT:    movw r2, #46385
; CHECK-8MBASE-NEXT:    movt r2, #1916
; CHECK-8MBASE-NEXT:    muls r2, r1, r2
; CHECK-8MBASE-NEXT:    lsrs r2, r2, #27
; CHECK-8MBASE-NEXT:    movs r1, #32
; CHECK-8MBASE-NEXT:    cmp r0, #0
; CHECK-8MBASE-NEXT:    bne .LBB0_3
; CHECK-8MBASE-NEXT:  @ %bb.1: @ %entry
; CHECK-8MBASE-NEXT:    beq .LBB0_4
; CHECK-8MBASE-NEXT:  .LBB0_2: @ %entry
; CHECK-8MBASE-NEXT:    mov r0, r1
; CHECK-8MBASE-NEXT:    bx lr
; CHECK-8MBASE-NEXT:  .LBB0_3: @ %entry
; CHECK-8MBASE-NEXT:    adr r1, .LCPI0_0
; CHECK-8MBASE-NEXT:    ldrb r1, [r1, r2]
; CHECK-8MBASE-NEXT:    bne .LBB0_2
; CHECK-8MBASE-NEXT:  .LBB0_4: @ %entry
; CHECK-8MBASE-NEXT:    mov r1, r0
; CHECK-8MBASE-NEXT:    mov r0, r1
; CHECK-8MBASE-NEXT:    bx lr
; CHECK-8MBASE-NEXT:    .p2align 2
; CHECK-8MBASE-NEXT:  @ %bb.5:
; CHECK-8MBASE-NEXT:  .LCPI0_0:
; CHECK-8MBASE-NEXT:    .ascii "\000\001\034\002\035\016\030\003\036\026\024\017\031\021\004\b\037\033\r\027\025\023\020\007\032\f\022\006\013\005\n\t"
entry:
  %0 = call i32 @llvm.cttz.i32(i32 %x, i1 true)
  %1 = icmp eq i32 %x, 0
  %2 = select i1 %1, i32 0, i32 %0
  ret i32 %2
}

define i32 @cttzi32ne(i32 %x) {
; CHECK-5-LABEL: cttzi32ne:
; CHECK-5:       @ %bb.0: @ %entry
; CHECK-5-NEXT:    sub r1, r0, #1
; CHECK-5-NEXT:    cmp r0, #0
; CHECK-5-NEXT:    bic r1, r1, r0
; CHECK-5-NEXT:    clz r1, r1
; CHECK-5-NEXT:    rsbne r0, r1, #32
; CHECK-5-NEXT:    bx lr
;
; CHECK-LABEL: cttzi32ne:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    rbit r1, r0
; CHECK-NEXT:    cmp r0, #0
; CHECK-NEXT:    clzne r0, r1
; CHECK-NEXT:    bx lr
;
; CHECK-6M-LABEL: cttzi32ne:
; CHECK-6M:       @ %bb.0: @ %entry
; CHECK-6M-NEXT:    rsbs r1, r0, #0
; CHECK-6M-NEXT:    ands r1, r0
; CHECK-6M-NEXT:    ldr r2, .LCPI1_0
; CHECK-6M-NEXT:    muls r2, r1, r2
; CHECK-6M-NEXT:    lsrs r2, r2, #27
; CHECK-6M-NEXT:    movs r1, #32
; CHECK-6M-NEXT:    cmp r0, #0
; CHECK-6M-NEXT:    bne .LBB1_3
; CHECK-6M-NEXT:  @ %bb.1: @ %entry
; CHECK-6M-NEXT:    beq .LBB1_4
; CHECK-6M-NEXT:  .LBB1_2: @ %entry
; CHECK-6M-NEXT:    mov r0, r1
; CHECK-6M-NEXT:    bx lr
; CHECK-6M-NEXT:  .LBB1_3: @ %entry
; CHECK-6M-NEXT:    adr r1, .LCPI1_1
; CHECK-6M-NEXT:    ldrb r1, [r1, r2]
; CHECK-6M-NEXT:    bne .LBB1_2
; CHECK-6M-NEXT:  .LBB1_4: @ %entry
; CHECK-6M-NEXT:    mov r1, r0
; CHECK-6M-NEXT:    mov r0, r1
; CHECK-6M-NEXT:    bx lr
; CHECK-6M-NEXT:    .p2align 2
; CHECK-6M-NEXT:  @ %bb.5:
; CHECK-6M-NEXT:  .LCPI1_0:
; CHECK-6M-NEXT:    .long 125613361 @ 0x77cb531
; CHECK-6M-NEXT:  .LCPI1_1:
; CHECK-6M-NEXT:    .ascii "\000\001\034\002\035\016\030\003\036\026\024\017\031\021\004\b\037\033\r\027\025\023\020\007\032\f\022\006\013\005\n\t"
;
; CHECK-8MBASE-LABEL: cttzi32ne:
; CHECK-8MBASE:       @ %bb.0: @ %entry
; CHECK-8MBASE-NEXT:    rsbs r1, r0, #0
; CHECK-8MBASE-NEXT:    ands r1, r0
; CHECK-8MBASE-NEXT:    movw r2, #46385
; CHECK-8MBASE-NEXT:    movt r2, #1916
; CHECK-8MBASE-NEXT:    muls r2, r1, r2
; CHECK-8MBASE-NEXT:    lsrs r2, r2, #27
; CHECK-8MBASE-NEXT:    movs r1, #32
; CHECK-8MBASE-NEXT:    cmp r0, #0
; CHECK-8MBASE-NEXT:    bne .LBB1_3
; CHECK-8MBASE-NEXT:  @ %bb.1: @ %entry
; CHECK-8MBASE-NEXT:    beq .LBB1_4
; CHECK-8MBASE-NEXT:  .LBB1_2: @ %entry
; CHECK-8MBASE-NEXT:    mov r0, r1
; CHECK-8MBASE-NEXT:    bx lr
; CHECK-8MBASE-NEXT:  .LBB1_3: @ %entry
; CHECK-8MBASE-NEXT:    adr r1, .LCPI1_0
; CHECK-8MBASE-NEXT:    ldrb r1, [r1, r2]
; CHECK-8MBASE-NEXT:    bne .LBB1_2
; CHECK-8MBASE-NEXT:  .LBB1_4: @ %entry
; CHECK-8MBASE-NEXT:    mov r1, r0
; CHECK-8MBASE-NEXT:    mov r0, r1
; CHECK-8MBASE-NEXT:    bx lr
; CHECK-8MBASE-NEXT:    .p2align 2
; CHECK-8MBASE-NEXT:  @ %bb.5:
; CHECK-8MBASE-NEXT:  .LCPI1_0:
; CHECK-8MBASE-NEXT:    .ascii "\000\001\034\002\035\016\030\003\036\026\024\017\031\021\004\b\037\033\r\027\025\023\020\007\032\f\022\006\013\005\n\t"
entry:
  %0 = call i32 @llvm.cttz.i32(i32 %x, i1 true)
  %1 = icmp ne i32 %x, 0
  %2 = select i1 %1, i32 %0, i32 0
  ret i32 %2
}

;; Cases for which the optimization does not take place
define i32 @cttzne(i32 %x) {
; CHECK-5-LABEL: cttzne:
; CHECK-5:       @ %bb.0: @ %entry
; CHECK-5-NEXT:    sub r1, r0, #1
; CHECK-5-NEXT:    cmp r0, #0
; CHECK-5-NEXT:    bic r1, r1, r0
; CHECK-5-NEXT:    clz r1, r1
; CHECK-5-NEXT:    rsb r1, r1, #32
; CHECK-5-NEXT:    movne r1, #0
; CHECK-5-NEXT:    mov r0, r1
; CHECK-5-NEXT:    bx lr
;
; CHECK-LABEL: cttzne:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    rbit r1, r0
; CHECK-NEXT:    cmp r0, #0
; CHECK-NEXT:    clz r1, r1
; CHECK-NEXT:    movwne r1, #0
; CHECK-NEXT:    mov r0, r1
; CHECK-NEXT:    bx lr
;
; CHECK-6M-LABEL: cttzne:
; CHECK-6M:       @ %bb.0: @ %entry
; CHECK-6M-NEXT:    mov r1, r0
; CHECK-6M-NEXT:    rsbs r0, r0, #0
; CHECK-6M-NEXT:    ands r0, r1
; CHECK-6M-NEXT:    ldr r2, .LCPI2_0
; CHECK-6M-NEXT:    muls r2, r0, r2
; CHECK-6M-NEXT:    lsrs r3, r2, #27
; CHECK-6M-NEXT:    movs r0, #0
; CHECK-6M-NEXT:    movs r2, #32
; CHECK-6M-NEXT:    cmp r1, #0
; CHECK-6M-NEXT:    bne .LBB2_3
; CHECK-6M-NEXT:  @ %bb.1: @ %entry
; CHECK-6M-NEXT:    beq .LBB2_4
; CHECK-6M-NEXT:  .LBB2_2: @ %entry
; CHECK-6M-NEXT:    bx lr
; CHECK-6M-NEXT:  .LBB2_3: @ %entry
; CHECK-6M-NEXT:    adr r1, .LCPI2_1
; CHECK-6M-NEXT:    ldrb r2, [r1, r3]
; CHECK-6M-NEXT:    bne .LBB2_2
; CHECK-6M-NEXT:  .LBB2_4: @ %entry
; CHECK-6M-NEXT:    mov r0, r2
; CHECK-6M-NEXT:    bx lr
; CHECK-6M-NEXT:    .p2align 2
; CHECK-6M-NEXT:  @ %bb.5:
; CHECK-6M-NEXT:  .LCPI2_0:
; CHECK-6M-NEXT:    .long 125613361 @ 0x77cb531
; CHECK-6M-NEXT:  .LCPI2_1:
; CHECK-6M-NEXT:    .ascii "\000\001\034\002\035\016\030\003\036\026\024\017\031\021\004\b\037\033\r\027\025\023\020\007\032\f\022\006\013\005\n\t"
;
; CHECK-8MBASE-LABEL: cttzne:
; CHECK-8MBASE:       @ %bb.0: @ %entry
; CHECK-8MBASE-NEXT:    mov r1, r0
; CHECK-8MBASE-NEXT:    rsbs r0, r0, #0
; CHECK-8MBASE-NEXT:    ands r0, r1
; CHECK-8MBASE-NEXT:    movw r2, #46385
; CHECK-8MBASE-NEXT:    movt r2, #1916
; CHECK-8MBASE-NEXT:    muls r2, r0, r2
; CHECK-8MBASE-NEXT:    lsrs r3, r2, #27
; CHECK-8MBASE-NEXT:    movs r0, #0
; CHECK-8MBASE-NEXT:    movs r2, #32
; CHECK-8MBASE-NEXT:    cmp r1, #0
; CHECK-8MBASE-NEXT:    bne .LBB2_3
; CHECK-8MBASE-NEXT:  @ %bb.1: @ %entry
; CHECK-8MBASE-NEXT:    beq .LBB2_4
; CHECK-8MBASE-NEXT:  .LBB2_2: @ %entry
; CHECK-8MBASE-NEXT:    bx lr
; CHECK-8MBASE-NEXT:  .LBB2_3: @ %entry
; CHECK-8MBASE-NEXT:    adr r1, .LCPI2_0
; CHECK-8MBASE-NEXT:    ldrb r2, [r1, r3]
; CHECK-8MBASE-NEXT:    bne .LBB2_2
; CHECK-8MBASE-NEXT:  .LBB2_4: @ %entry
; CHECK-8MBASE-NEXT:    mov r0, r2
; CHECK-8MBASE-NEXT:    bx lr
; CHECK-8MBASE-NEXT:    .p2align 2
; CHECK-8MBASE-NEXT:  @ %bb.5:
; CHECK-8MBASE-NEXT:  .LCPI2_0:
; CHECK-8MBASE-NEXT:    .ascii "\000\001\034\002\035\016\030\003\036\026\024\017\031\021\004\b\037\033\r\027\025\023\020\007\032\f\022\006\013\005\n\t"
entry:
  %0 = call i32 @llvm.cttz.i32(i32 %x, i1 true)
  %1 = icmp ne i32 %x, 0
  %2 = select i1 %1, i32 0, i32 %0
  ret i32 %2
}

define i32 @cttzxnot0(i32 %x) {
; CHECK-5-LABEL: cttzxnot0:
; CHECK-5:       @ %bb.0: @ %entry
; CHECK-5-NEXT:    sub r1, r0, #1
; CHECK-5-NEXT:    bic r1, r1, r0
; CHECK-5-NEXT:    subs r0, r0, #10
; CHECK-5-NEXT:    clz r1, r1
; CHECK-5-NEXT:    rsbne r0, r1, #32
; CHECK-5-NEXT:    bx lr
;
; CHECK-LABEL: cttzxnot0:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    rbit r1, r0
; CHECK-NEXT:    subs r0, r0, #10
; CHECK-NEXT:    clzne r0, r1
; CHECK-NEXT:    bx lr
;
; CHECK-6M-LABEL: cttzxnot0:
; CHECK-6M:       @ %bb.0: @ %entry
; CHECK-6M-NEXT:    cmp r0, #0
; CHECK-6M-NEXT:    beq .LBB3_2
; CHECK-6M-NEXT:  @ %bb.1: @ %entry
; CHECK-6M-NEXT:    rsbs r1, r0, #0
; CHECK-6M-NEXT:    ands r1, r0
; CHECK-6M-NEXT:    ldr r2, .LCPI3_0
; CHECK-6M-NEXT:    muls r2, r1, r2
; CHECK-6M-NEXT:    lsrs r1, r2, #27
; CHECK-6M-NEXT:    adr r2, .LCPI3_1
; CHECK-6M-NEXT:    ldrb r1, [r2, r1]
; CHECK-6M-NEXT:    cmp r0, #10
; CHECK-6M-NEXT:    beq .LBB3_3
; CHECK-6M-NEXT:    b .LBB3_4
; CHECK-6M-NEXT:  .LBB3_2:
; CHECK-6M-NEXT:    movs r1, #32
; CHECK-6M-NEXT:    cmp r0, #10
; CHECK-6M-NEXT:    bne .LBB3_4
; CHECK-6M-NEXT:  .LBB3_3:
; CHECK-6M-NEXT:    movs r1, #0
; CHECK-6M-NEXT:  .LBB3_4: @ %entry
; CHECK-6M-NEXT:    mov r0, r1
; CHECK-6M-NEXT:    bx lr
; CHECK-6M-NEXT:    .p2align 2
; CHECK-6M-NEXT:  @ %bb.5:
; CHECK-6M-NEXT:  .LCPI3_0:
; CHECK-6M-NEXT:    .long 125613361 @ 0x77cb531
; CHECK-6M-NEXT:  .LCPI3_1:
; CHECK-6M-NEXT:    .ascii "\000\001\034\002\035\016\030\003\036\026\024\017\031\021\004\b\037\033\r\027\025\023\020\007\032\f\022\006\013\005\n\t"
;
; CHECK-8MBASE-LABEL: cttzxnot0:
; CHECK-8MBASE:       @ %bb.0: @ %entry
; CHECK-8MBASE-NEXT:    cbz r0, .LBB3_2
; CHECK-8MBASE-NEXT:  @ %bb.1: @ %entry
; CHECK-8MBASE-NEXT:    rsbs r1, r0, #0
; CHECK-8MBASE-NEXT:    ands r1, r0
; CHECK-8MBASE-NEXT:    movw r2, #46385
; CHECK-8MBASE-NEXT:    movt r2, #1916
; CHECK-8MBASE-NEXT:    muls r2, r1, r2
; CHECK-8MBASE-NEXT:    lsrs r1, r2, #27
; CHECK-8MBASE-NEXT:    adr r2, .LCPI3_0
; CHECK-8MBASE-NEXT:    ldrb r1, [r2, r1]
; CHECK-8MBASE-NEXT:    cmp r0, #10
; CHECK-8MBASE-NEXT:    beq .LBB3_3
; CHECK-8MBASE-NEXT:    b .LBB3_4
; CHECK-8MBASE-NEXT:  .LBB3_2:
; CHECK-8MBASE-NEXT:    movs r1, #32
; CHECK-8MBASE-NEXT:    cmp r0, #10
; CHECK-8MBASE-NEXT:    bne .LBB3_4
; CHECK-8MBASE-NEXT:  .LBB3_3:
; CHECK-8MBASE-NEXT:    movs r1, #0
; CHECK-8MBASE-NEXT:  .LBB3_4: @ %entry
; CHECK-8MBASE-NEXT:    mov r0, r1
; CHECK-8MBASE-NEXT:    bx lr
; CHECK-8MBASE-NEXT:    .p2align 2
; CHECK-8MBASE-NEXT:  @ %bb.5:
; CHECK-8MBASE-NEXT:  .LCPI3_0:
; CHECK-8MBASE-NEXT:    .ascii "\000\001\034\002\035\016\030\003\036\026\024\017\031\021\004\b\037\033\r\027\025\023\020\007\032\f\022\006\013\005\n\t"
entry:
  %0 = call i32 @llvm.cttz.i32(i32 %x, i1 true)
  %1 = icmp eq i32 %x, 10
  %2 = select i1 %1, i32 0, i32 %0
  ret i32 %2
}

define i32 @cttzlhsnot0(i32 %x) {
; CHECK-5-LABEL: cttzlhsnot0:
; CHECK-5:       @ %bb.0: @ %entry
; CHECK-5-NEXT:    sub r1, r0, #1
; CHECK-5-NEXT:    cmp r0, #0
; CHECK-5-NEXT:    bic r1, r1, r0
; CHECK-5-NEXT:    clz r1, r1
; CHECK-5-NEXT:    rsb r1, r1, #32
; CHECK-5-NEXT:    moveq r1, #10
; CHECK-5-NEXT:    mov r0, r1
; CHECK-5-NEXT:    bx lr
;
; CHECK-LABEL: cttzlhsnot0:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    rbit r1, r0
; CHECK-NEXT:    cmp r0, #0
; CHECK-NEXT:    clz r1, r1
; CHECK-NEXT:    movweq r1, #10
; CHECK-NEXT:    mov r0, r1
; CHECK-NEXT:    bx lr
;
; CHECK-6M-LABEL: cttzlhsnot0:
; CHECK-6M:       @ %bb.0: @ %entry
; CHECK-6M-NEXT:    mov r1, r0
; CHECK-6M-NEXT:    rsbs r0, r0, #0
; CHECK-6M-NEXT:    ands r0, r1
; CHECK-6M-NEXT:    ldr r2, .LCPI4_0
; CHECK-6M-NEXT:    muls r2, r0, r2
; CHECK-6M-NEXT:    lsrs r3, r2, #27
; CHECK-6M-NEXT:    movs r0, #10
; CHECK-6M-NEXT:    movs r2, #32
; CHECK-6M-NEXT:    cmp r1, #0
; CHECK-6M-NEXT:    bne .LBB4_3
; CHECK-6M-NEXT:  @ %bb.1: @ %entry
; CHECK-6M-NEXT:    bne .LBB4_4
; CHECK-6M-NEXT:  .LBB4_2: @ %entry
; CHECK-6M-NEXT:    bx lr
; CHECK-6M-NEXT:  .LBB4_3: @ %entry
; CHECK-6M-NEXT:    adr r1, .LCPI4_1
; CHECK-6M-NEXT:    ldrb r2, [r1, r3]
; CHECK-6M-NEXT:    beq .LBB4_2
; CHECK-6M-NEXT:  .LBB4_4: @ %entry
; CHECK-6M-NEXT:    mov r0, r2
; CHECK-6M-NEXT:    bx lr
; CHECK-6M-NEXT:    .p2align 2
; CHECK-6M-NEXT:  @ %bb.5:
; CHECK-6M-NEXT:  .LCPI4_0:
; CHECK-6M-NEXT:    .long 125613361 @ 0x77cb531
; CHECK-6M-NEXT:  .LCPI4_1:
; CHECK-6M-NEXT:    .ascii "\000\001\034\002\035\016\030\003\036\026\024\017\031\021\004\b\037\033\r\027\025\023\020\007\032\f\022\006\013\005\n\t"
;
; CHECK-8MBASE-LABEL: cttzlhsnot0:
; CHECK-8MBASE:       @ %bb.0: @ %entry
; CHECK-8MBASE-NEXT:    mov r1, r0
; CHECK-8MBASE-NEXT:    rsbs r0, r0, #0
; CHECK-8MBASE-NEXT:    ands r0, r1
; CHECK-8MBASE-NEXT:    movw r2, #46385
; CHECK-8MBASE-NEXT:    movt r2, #1916
; CHECK-8MBASE-NEXT:    muls r2, r0, r2
; CHECK-8MBASE-NEXT:    lsrs r3, r2, #27
; CHECK-8MBASE-NEXT:    movs r0, #10
; CHECK-8MBASE-NEXT:    movs r2, #32
; CHECK-8MBASE-NEXT:    cmp r1, #0
; CHECK-8MBASE-NEXT:    bne .LBB4_3
; CHECK-8MBASE-NEXT:  @ %bb.1: @ %entry
; CHECK-8MBASE-NEXT:    bne .LBB4_4
; CHECK-8MBASE-NEXT:  .LBB4_2: @ %entry
; CHECK-8MBASE-NEXT:    bx lr
; CHECK-8MBASE-NEXT:  .LBB4_3: @ %entry
; CHECK-8MBASE-NEXT:    adr r1, .LCPI4_0
; CHECK-8MBASE-NEXT:    ldrb r2, [r1, r3]
; CHECK-8MBASE-NEXT:    beq .LBB4_2
; CHECK-8MBASE-NEXT:  .LBB4_4: @ %entry
; CHECK-8MBASE-NEXT:    mov r0, r2
; CHECK-8MBASE-NEXT:    bx lr
; CHECK-8MBASE-NEXT:    .p2align 2
; CHECK-8MBASE-NEXT:  @ %bb.5:
; CHECK-8MBASE-NEXT:  .LCPI4_0:
; CHECK-8MBASE-NEXT:    .ascii "\000\001\034\002\035\016\030\003\036\026\024\017\031\021\004\b\037\033\r\027\025\023\020\007\032\f\022\006\013\005\n\t"
entry:
  %0 = call i32 @llvm.cttz.i32(i32 %x, i1 true)
  %1 = icmp eq i32 %x, 0
  %2 = select i1 %1, i32 10, i32 %0
  ret i32 %2
}

define i32 @notcttz(i32 %x) {
; CHECK-5-LABEL: notcttz:
; CHECK-5:       @ %bb.0: @ %entry
; CHECK-5-NEXT:    cmp r0, #0
; CHECK-5-NEXT:    clzne r0, r0
; CHECK-5-NEXT:    bx lr
;
; CHECK-LABEL: notcttz:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    cmp r0, #0
; CHECK-NEXT:    clzne r0, r0
; CHECK-NEXT:    bx lr
;
; CHECK-6M-LABEL: notcttz:
; CHECK-6M:       @ %bb.0: @ %entry
; CHECK-6M-NEXT:    .save {r4, lr}
; CHECK-6M-NEXT:    push {r4, lr}
; CHECK-6M-NEXT:    mov r4, r0
; CHECK-6M-NEXT:    bl __clzsi2
; CHECK-6M-NEXT:    cmp r4, #0
; CHECK-6M-NEXT:    bne .LBB5_2
; CHECK-6M-NEXT:  @ %bb.1: @ %entry
; CHECK-6M-NEXT:    mov r0, r4
; CHECK-6M-NEXT:  .LBB5_2: @ %entry
; CHECK-6M-NEXT:    pop {r4, pc}
;
; CHECK-8MBASE-LABEL: notcttz:
; CHECK-8MBASE:       @ %bb.0: @ %entry
; CHECK-8MBASE-NEXT:    .save {r4, lr}
; CHECK-8MBASE-NEXT:    push {r4, lr}
; CHECK-8MBASE-NEXT:    mov r4, r0
; CHECK-8MBASE-NEXT:    bl __clzsi2
; CHECK-8MBASE-NEXT:    cbnz r4, .LBB5_2
; CHECK-8MBASE-NEXT:  @ %bb.1: @ %entry
; CHECK-8MBASE-NEXT:    mov r0, r4
; CHECK-8MBASE-NEXT:  .LBB5_2: @ %entry
; CHECK-8MBASE-NEXT:    pop {r4, pc}
entry:
  %0 = call i32 @llvm.ctlz.i32(i32 %x, i1 true)
  %1 = icmp eq i32 %x, 0
  %2 = select i1 %1, i32 0, i32 %0
  ret i32 %2
}

define i32 @cttzlhsnotx(i32 %x, i32 %y) {
; CHECK-5-LABEL: cttzlhsnotx:
; CHECK-5:       @ %bb.0: @ %entry
; CHECK-5-NEXT:    sub r2, r0, #1
; CHECK-5-NEXT:    cmp r1, #0
; CHECK-5-NEXT:    bic r0, r2, r0
; CHECK-5-NEXT:    clz r0, r0
; CHECK-5-NEXT:    rsbne r1, r0, #32
; CHECK-5-NEXT:    mov r0, r1
; CHECK-5-NEXT:    bx lr
;
; CHECK-LABEL: cttzlhsnotx:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    rbit r0, r0
; CHECK-NEXT:    cmp r1, #0
; CHECK-NEXT:    clzne r1, r0
; CHECK-NEXT:    mov r0, r1
; CHECK-NEXT:    bx lr
;
; CHECK-6M-LABEL: cttzlhsnotx:
; CHECK-6M:       @ %bb.0: @ %entry
; CHECK-6M-NEXT:    cmp r0, #0
; CHECK-6M-NEXT:    beq .LBB6_2
; CHECK-6M-NEXT:  @ %bb.1: @ %entry
; CHECK-6M-NEXT:    rsbs r2, r0, #0
; CHECK-6M-NEXT:    ands r2, r0
; CHECK-6M-NEXT:    ldr r0, .LCPI6_0
; CHECK-6M-NEXT:    muls r0, r2, r0
; CHECK-6M-NEXT:    lsrs r0, r0, #27
; CHECK-6M-NEXT:    adr r2, .LCPI6_1
; CHECK-6M-NEXT:    ldrb r0, [r2, r0]
; CHECK-6M-NEXT:    cmp r1, #0
; CHECK-6M-NEXT:    beq .LBB6_3
; CHECK-6M-NEXT:    b .LBB6_4
; CHECK-6M-NEXT:  .LBB6_2:
; CHECK-6M-NEXT:    movs r0, #32
; CHECK-6M-NEXT:    cmp r1, #0
; CHECK-6M-NEXT:    bne .LBB6_4
; CHECK-6M-NEXT:  .LBB6_3: @ %entry
; CHECK-6M-NEXT:    mov r0, r1
; CHECK-6M-NEXT:  .LBB6_4: @ %entry
; CHECK-6M-NEXT:    bx lr
; CHECK-6M-NEXT:    .p2align 2
; CHECK-6M-NEXT:  @ %bb.5:
; CHECK-6M-NEXT:  .LCPI6_0:
; CHECK-6M-NEXT:    .long 125613361 @ 0x77cb531
; CHECK-6M-NEXT:  .LCPI6_1:
; CHECK-6M-NEXT:    .ascii "\000\001\034\002\035\016\030\003\036\026\024\017\031\021\004\b\037\033\r\027\025\023\020\007\032\f\022\006\013\005\n\t"
;
; CHECK-8MBASE-LABEL: cttzlhsnotx:
; CHECK-8MBASE:       @ %bb.0: @ %entry
; CHECK-8MBASE-NEXT:    cbz r0, .LBB6_2
; CHECK-8MBASE-NEXT:  @ %bb.1: @ %entry
; CHECK-8MBASE-NEXT:    rsbs r2, r0, #0
; CHECK-8MBASE-NEXT:    ands r2, r0
; CHECK-8MBASE-NEXT:    movw r0, #46385
; CHECK-8MBASE-NEXT:    movt r0, #1916
; CHECK-8MBASE-NEXT:    muls r0, r2, r0
; CHECK-8MBASE-NEXT:    lsrs r0, r0, #27
; CHECK-8MBASE-NEXT:    adr r2, .LCPI6_0
; CHECK-8MBASE-NEXT:    ldrb r0, [r2, r0]
; CHECK-8MBASE-NEXT:    cbz r1, .LBB6_3
; CHECK-8MBASE-NEXT:    b .LBB6_4
; CHECK-8MBASE-NEXT:  .LBB6_2:
; CHECK-8MBASE-NEXT:    movs r0, #32
; CHECK-8MBASE-NEXT:    cbnz r1, .LBB6_4
; CHECK-8MBASE-NEXT:  .LBB6_3: @ %entry
; CHECK-8MBASE-NEXT:    mov r0, r1
; CHECK-8MBASE-NEXT:  .LBB6_4: @ %entry
; CHECK-8MBASE-NEXT:    bx lr
; CHECK-8MBASE-NEXT:    .p2align 2
; CHECK-8MBASE-NEXT:  @ %bb.5:
; CHECK-8MBASE-NEXT:  .LCPI6_0:
; CHECK-8MBASE-NEXT:    .ascii "\000\001\034\002\035\016\030\003\036\026\024\017\031\021\004\b\037\033\r\027\025\023\020\007\032\f\022\006\013\005\n\t"
entry:
  %0 = call i32 @llvm.cttz.i32(i32 %x, i1 true)
  %1 = icmp eq i32 %y, 0
  %2 = select i1 %1, i32 0, i32 %0
  ret i32 %2
}

declare i32 @llvm.cttz.i32(i32, i1)

declare i32 @llvm.ctlz.i32(i32, i1)
