; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=armv6-linux-gnueabihf | FileCheck %s --check-prefix=ARMV6
; RUN: llc < %s -mtriple=armv7-linux-gnueabi   | FileCheck %s --check-prefix=ARMV7
; RUN: llc < %s -mtriple=armv7-none-eabi       | FileCheck %s --check-prefix=ARMV7

; These 32-bit ARM triples inline-expand i128 div/rem. Keep the checks minimal:
; verify that no libcalls are emitted and that the function reaches its
; epilogue.

define void @sdivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; ARMV6-LABEL: sdivrem_i128:
; ARMV6:       @ %bb.0: @ %_udiv-special-cases_udiv-special-cases
; ARMV6-NEXT:    .save {r4, r5, r6, r7, r8, r9, r10, r11, lr}
; ARMV6-NEXT:    push {r4, r5, r6, r7, r8, r9, r10, r11, lr}
; ARMV6-NEXT:    .pad #252
; ARMV6-NEXT:    sub sp, sp, #252
; ARMV6-NEXT:    ldr r10, [sp, #292]
; ARMV6-NEXT:    str r1, [sp, #44] @ 4-byte Spill
; ARMV6-NEXT:    str r0, [sp, #40] @ 4-byte Spill
; ARMV6-NEXT:    ldr r0, [sp, #288]
; ARMV6-NEXT:    eor r1, r3, r10, asr #31
; ARMV6-NEXT:    eor r3, r2, r10, asr #31
; ARMV6-NEXT:    eor r2, r10, r10, asr #31
; ARMV6-NEXT:    subs r8, r3, r10, asr #31
; ARMV6-NEXT:    eor r0, r0, r10, asr #31
; ARMV6-NEXT:    sbcs r9, r1, r10, asr #31
; ARMV6-NEXT:    str r0, [sp, #36] @ 4-byte Spill
; ARMV6-NEXT:    sbcs lr, r0, r10, asr #31
; ARMV6-NEXT:    str r1, [sp, #32] @ 4-byte Spill
; ARMV6-NEXT:    sbc r11, r2, r10, asr #31
; ARMV6-NEXT:    clz r0, lr
; ARMV6-NEXT:    clz r1, r8
; ARMV6-NEXT:    add r0, r0, #32
; ARMV6-NEXT:    cmp r11, #0
; ARMV6-NEXT:    add r1, r1, #32
; ARMV6-NEXT:    clzne r0, r11
; ARMV6-NEXT:    cmp r9, #0
; ARMV6-NEXT:    str r2, [sp, #28] @ 4-byte Spill
; ARMV6-NEXT:    clzne r1, r9
; ARMV6-NEXT:    orrs r2, lr, r11
; ARMV6-NEXT:    ldr r6, [sp, #308]
; ARMV6-NEXT:    addeq r0, r1, #64
; ARMV6-NEXT:    ldr r1, [sp, #304]
; ARMV6-NEXT:    str r3, [sp, #24] @ 4-byte Spill
; ARMV6-NEXT:    eor r2, r1, r6, asr #31
; ARMV6-NEXT:    ldr r1, [sp, #300]
; ARMV6-NEXT:    str r2, [sp, #20] @ 4-byte Spill
; ARMV6-NEXT:    eor r3, r1, r6, asr #31
; ARMV6-NEXT:    ldr r1, [sp, #296]
; ARMV6-NEXT:    str r3, [sp, #52] @ 4-byte Spill
; ARMV6-NEXT:    eor r7, r1, r6, asr #31
; ARMV6-NEXT:    str r7, [sp, #48] @ 4-byte Spill
; ARMV6-NEXT:    subs r7, r7, r6, asr #31
; ARMV6-NEXT:    eor r1, r6, r6, asr #31
; ARMV6-NEXT:    sbcs r5, r3, r6, asr #31
; ARMV6-NEXT:    str r1, [sp, #16] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r4, r2, r6, asr #31
; ARMV6-NEXT:    clz r2, r7
; ARMV6-NEXT:    sbc r12, r1, r6, asr #31
; ARMV6-NEXT:    clz r1, r4
; ARMV6-NEXT:    add r1, r1, #32
; ARMV6-NEXT:    cmp r12, #0
; ARMV6-NEXT:    clzne r1, r12
; ARMV6-NEXT:    add r2, r2, #32
; ARMV6-NEXT:    cmp r5, #0
; ARMV6-NEXT:    str r5, [sp, #80] @ 4-byte Spill
; ARMV6-NEXT:    clzne r2, r5
; ARMV6-NEXT:    orrs r3, r4, r12
; ARMV6-NEXT:    addeq r1, r2, #64
; ARMV6-NEXT:    mov r2, #0
; ARMV6-NEXT:    subs r0, r1, r0
; ARMV6-NEXT:    str r0, [sp, #104] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r1, r2, #0
; ARMV6-NEXT:    str r1, [sp, #100] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r3, r2, #0
; ARMV6-NEXT:    str r3, [sp, #112] @ 4-byte Spill
; ARMV6-NEXT:    sbc r2, r2, #0
; ARMV6-NEXT:    rsbs r0, r0, #127
; ARMV6-NEXT:    rscs r0, r1, #0
; ARMV6-NEXT:    str r2, [sp, #108] @ 4-byte Spill
; ARMV6-NEXT:    rscs r0, r3, #0
; ARMV6-NEXT:    orr r1, r9, r11
; ARMV6-NEXT:    rscs r0, r2, #0
; ARMV6-NEXT:    orr r2, r8, lr
; ARMV6-NEXT:    orr r1, r2, r1
; ARMV6-NEXT:    orr r2, r5, r12
; ARMV6-NEXT:    orr r3, r7, r4
; ARMV6-NEXT:    clz r1, r1
; ARMV6-NEXT:    orr r2, r3, r2
; ARMV6-NEXT:    mov r0, #0
; ARMV6-NEXT:    clz r2, r2
; ARMV6-NEXT:    lsr r1, r1, #5
; ARMV6-NEXT:    movlo r0, #1
; ARMV6-NEXT:    str r4, [sp, #76] @ 4-byte Spill
; ARMV6-NEXT:    lsr r2, r2, #5
; ARMV6-NEXT:    orr r1, r2, r1
; ARMV6-NEXT:    orrs r0, r1, r0
; ARMV6-NEXT:    mov r3, r11
; ARMV6-NEXT:    mov r4, lr
; ARMV6-NEXT:    mov r5, r9
; ARMV6-NEXT:    mov r1, r8
; ARMV6-NEXT:    movne r3, #0
; ARMV6-NEXT:    movne r4, #0
; ARMV6-NEXT:    movne r5, #0
; ARMV6-NEXT:    movne r8, #0
; ARMV6-NEXT:    str r7, [sp, #84] @ 4-byte Spill
; ARMV6-NEXT:    asr r7, r6, #31
; ARMV6-NEXT:    eor r0, r7, r10, asr #31
; ARMV6-NEXT:    str r12, [sp, #72] @ 4-byte Spill
; ARMV6-NEXT:    str r0, [sp, #12] @ 4-byte Spill
; ARMV6-NEXT:    bne .LBB0_6
; ARMV6-NEXT:  @ %bb.1: @ %_udiv-special-cases_udiv-special-cases
; ARMV6-NEXT:    ldr r0, [sp, #104] @ 4-byte Reload
; ARMV6-NEXT:    ldr r10, [sp, #100] @ 4-byte Reload
; ARMV6-NEXT:    eor r7, r0, #127
; ARMV6-NEXT:    ldr r0, [sp, #112] @ 4-byte Reload
; ARMV6-NEXT:    orr r7, r7, r0
; ARMV6-NEXT:    ldr r0, [sp, #108] @ 4-byte Reload
; ARMV6-NEXT:    orr r6, r10, r0
; ARMV6-NEXT:    ldr r0, [sp, #52] @ 4-byte Reload
; ARMV6-NEXT:    orrs r7, r7, r6
; ARMV6-NEXT:    ldr r6, [sp, #48] @ 4-byte Reload
; ARMV6-NEXT:    beq .LBB0_7
; ARMV6-NEXT:  @ %bb.2: @ %udiv-bb15
; ARMV6-NEXT:    mov r5, #0
; ARMV6-NEXT:    mov r2, r9
; ARMV6-NEXT:    str r1, [sp, #232]
; ARMV6-NEXT:    add r3, sp, #216
; ARMV6-NEXT:    str r5, [sp, #228]
; ARMV6-NEXT:    mov r9, r1
; ARMV6-NEXT:    str r5, [sp, #224]
; ARMV6-NEXT:    mov r1, #12
; ARMV6-NEXT:    str r5, [sp, #220]
; ARMV6-NEXT:    mov r8, r2
; ARMV6-NEXT:    str r5, [sp, #216]
; ARMV6-NEXT:    add r3, r3, #16
; ARMV6-NEXT:    str r2, [sp, #236]
; ARMV6-NEXT:    str lr, [sp, #240]
; ARMV6-NEXT:    str r11, [sp, #244]
; ARMV6-NEXT:    ldr r4, [sp, #104] @ 4-byte Reload
; ARMV6-NEXT:    rsb r0, r4, #127
; ARMV6-NEXT:    and r2, r1, r0, lsr #3
; ARMV6-NEXT:    and r0, r0, #31
; ARMV6-NEXT:    eor r12, r0, #31
; ARMV6-NEXT:    ldr r2, [r3, -r2]!
; ARMV6-NEXT:    ldr r6, [r3, #8]
; ARMV6-NEXT:    ldr r7, [r3, #4]
; ARMV6-NEXT:    ldr r3, [r3, #12]
; ARMV6-NEXT:    lsr r1, r6, #1
; ARMV6-NEXT:    lsl r3, r3, r0
; ARMV6-NEXT:    orr r1, r3, r1, lsr r12
; ARMV6-NEXT:    str r1, [sp, #116] @ 4-byte Spill
; ARMV6-NEXT:    lsl r1, r6, r0
; ARMV6-NEXT:    lsrs r3, r7, #1
; ARMV6-NEXT:    lsr r6, r2, #1
; ARMV6-NEXT:    orr r1, r1, r3, lsr r12
; ARMV6-NEXT:    str r1, [sp, #92] @ 4-byte Spill
; ARMV6-NEXT:    lsl r1, r7, r0
; ARMV6-NEXT:    lsl r0, r2, r0
; ARMV6-NEXT:    adds r7, r4, #1
; ARMV6-NEXT:    str r0, [sp, #96] @ 4-byte Spill
; ARMV6-NEXT:    adcs r0, r10, #0
; ARMV6-NEXT:    str r0, [sp, #100] @ 4-byte Spill
; ARMV6-NEXT:    ldr r0, [sp, #112] @ 4-byte Reload
; ARMV6-NEXT:    orr r1, r1, r6, lsr r12
; ARMV6-NEXT:    str r1, [sp, #88] @ 4-byte Spill
; ARMV6-NEXT:    adcs r12, r0, #0
; ARMV6-NEXT:    ldr r0, [sp, #108] @ 4-byte Reload
; ARMV6-NEXT:    adcs r0, r0, #0
; ARMV6-NEXT:    str r0, [sp, #104] @ 4-byte Spill
; ARMV6-NEXT:    adcs r0, r5, #0
; ARMV6-NEXT:    bne .LBB0_14
; ARMV6-NEXT:  @ %bb.3: @ %udiv-preheader4
; ARMV6-NEXT:    str r9, [sp, #184]
; ARMV6-NEXT:    mov r0, #12
; ARMV6-NEXT:    and r1, r0, r7, lsr #3
; ARMV6-NEXT:    add r9, sp, #184
; ARMV6-NEXT:    add r0, r9, r1
; ARMV6-NEXT:    str r5, [sp, #212]
; ARMV6-NEXT:    str r5, [sp, #208]
; ARMV6-NEXT:    and r4, r7, #31
; ARMV6-NEXT:    str r11, [sp, #196]
; ARMV6-NEXT:    eor r11, r4, #31
; ARMV6-NEXT:    str r5, [sp, #204]
; ARMV6-NEXT:    mov r6, #0
; ARMV6-NEXT:    str r5, [sp, #200]
; ARMV6-NEXT:    str r8, [sp, #188]
; ARMV6-NEXT:    str lr, [sp, #192]
; ARMV6-NEXT:    ldr r5, [r0, #4]
; ARMV6-NEXT:    ldr r2, [r0, #8]
; ARMV6-NEXT:    ldr r3, [r0, #12]
; ARMV6-NEXT:    str r7, [sp, #112] @ 4-byte Spill
; ARMV6-NEXT:    ldr r1, [r9, r1]
; ARMV6-NEXT:    lsr r0, r2, r4
; ARMV6-NEXT:    lsl r7, r3, #1
; ARMV6-NEXT:    orr r0, r0, r7, lsl r11
; ARMV6-NEXT:    lsr r7, r5, r4
; ARMV6-NEXT:    lsl r5, r5, #1
; ARMV6-NEXT:    lsl r2, r2, #1
; ARMV6-NEXT:    lsr r1, r1, r4
; ARMV6-NEXT:    orr r8, r1, r5, lsl r11
; ARMV6-NEXT:    ldr r1, [sp, #84] @ 4-byte Reload
; ARMV6-NEXT:    orr r2, r7, r2, lsl r11
; ARMV6-NEXT:    ldr r11, [sp, #116] @ 4-byte Reload
; ARMV6-NEXT:    subs r1, r1, #1
; ARMV6-NEXT:    str r1, [sp, #68] @ 4-byte Spill
; ARMV6-NEXT:    ldr r1, [sp, #80] @ 4-byte Reload
; ARMV6-NEXT:    ldr lr, [sp, #100] @ 4-byte Reload
; ARMV6-NEXT:    sbcs r1, r1, #0
; ARMV6-NEXT:    str r1, [sp, #64] @ 4-byte Spill
; ARMV6-NEXT:    ldr r1, [sp, #76] @ 4-byte Reload
; ARMV6-NEXT:    ldr r7, [sp, #96] @ 4-byte Reload
; ARMV6-NEXT:    sbcs r1, r1, #0
; ARMV6-NEXT:    str r1, [sp, #60] @ 4-byte Spill
; ARMV6-NEXT:    ldr r1, [sp, #72] @ 4-byte Reload
; ARMV6-NEXT:    ldr r10, [sp, #92] @ 4-byte Reload
; ARMV6-NEXT:    sbc r1, r1, #0
; ARMV6-NEXT:    str r1, [sp, #56] @ 4-byte Spill
; ARMV6-NEXT:    lsr r1, r3, r4
; ARMV6-NEXT:    ldr r4, [sp, #104] @ 4-byte Reload
; ARMV6-NEXT:    ldr r9, [sp, #88] @ 4-byte Reload
; ARMV6-NEXT:    str r1, [sp, #108] @ 4-byte Spill
; ARMV6-NEXT:    mov r1, #0
; ARMV6-NEXT:  .LBB0_4: @ %udiv-do-while3
; ARMV6-NEXT:    @ =>This Inner Loop Header: Depth=1
; ARMV6-NEXT:    mov r5, r1
; ARMV6-NEXT:    ldr r1, [sp, #108] @ 4-byte Reload
; ARMV6-NEXT:    add r3, sp, #92
; ARMV6-NEXT:    str r11, [sp, #116] @ 4-byte Spill
; ARMV6-NEXT:    stm r3, {r6, r7, r9, r10} @ 16-byte Folded Spill
; ARMV6-NEXT:    lsl r7, r8, #1
; ARMV6-NEXT:    lsl r1, r1, #1
; ARMV6-NEXT:    ldr r3, [sp, #68] @ 4-byte Reload
; ARMV6-NEXT:    orr r7, r7, r11, lsr #31
; ARMV6-NEXT:    orr r1, r1, r0, lsr #31
; ARMV6-NEXT:    lsl r0, r0, #1
; ARMV6-NEXT:    subs r3, r3, r7
; ARMV6-NEXT:    orr r0, r0, r2, lsr #31
; ARMV6-NEXT:    lsl r2, r2, #1
; ARMV6-NEXT:    ldr r3, [sp, #64] @ 4-byte Reload
; ARMV6-NEXT:    orr r2, r2, r8, lsr #31
; ARMV6-NEXT:    ldr r6, [sp, #72] @ 4-byte Reload
; ARMV6-NEXT:    sbcs r3, r3, r2
; ARMV6-NEXT:    ldr r3, [sp, #60] @ 4-byte Reload
; ARMV6-NEXT:    sbcs r3, r3, r0
; ARMV6-NEXT:    ldr r3, [sp, #56] @ 4-byte Reload
; ARMV6-NEXT:    sbc r3, r3, r1
; ARMV6-NEXT:    and r10, r6, r3, asr #31
; ARMV6-NEXT:    ldr r6, [sp, #76] @ 4-byte Reload
; ARMV6-NEXT:    and r8, r6, r3, asr #31
; ARMV6-NEXT:    ldr r6, [sp, #80] @ 4-byte Reload
; ARMV6-NEXT:    and r9, r6, r3, asr #31
; ARMV6-NEXT:    ldr r6, [sp, #84] @ 4-byte Reload
; ARMV6-NEXT:    and r11, r6, r3, asr #31
; ARMV6-NEXT:    subs r6, r7, r11
; ARMV6-NEXT:    str r6, [sp, #88] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r2, r2, r9
; ARMV6-NEXT:    sbcs r11, r0, r8
; ARMV6-NEXT:    ldr r8, [sp, #88] @ 4-byte Reload
; ARMV6-NEXT:    sbc r0, r1, r10
; ARMV6-NEXT:    mov r1, #1
; ARMV6-NEXT:    and r6, r1, r3, asr #31
; ARMV6-NEXT:    ldr r1, [sp, #112] @ 4-byte Reload
; ARMV6-NEXT:    str r0, [sp, #108] @ 4-byte Spill
; ARMV6-NEXT:    subs r1, r1, #1
; ARMV6-NEXT:    str r1, [sp, #112] @ 4-byte Spill
; ARMV6-NEXT:    sbcs lr, lr, #0
; ARMV6-NEXT:    ldr r0, [sp, #96] @ 4-byte Reload
; ARMV6-NEXT:    sbcs r12, r12, #0
; ARMV6-NEXT:    sbc r4, r4, #0
; ARMV6-NEXT:    orr r1, r1, r12
; ARMV6-NEXT:    orr r3, lr, r4
; ARMV6-NEXT:    orrs r1, r1, r3
; ARMV6-NEXT:    ldr r3, [sp, #100] @ 4-byte Reload
; ARMV6-NEXT:    ldr r1, [sp, #92] @ 4-byte Reload
; ARMV6-NEXT:    orr r7, r1, r0, lsl #1
; ARMV6-NEXT:    lsl r1, r3, #1
; ARMV6-NEXT:    orr r1, r1, r0, lsr #31
; ARMV6-NEXT:    ldr r0, [sp, #104] @ 4-byte Reload
; ARMV6-NEXT:    orr r9, r5, r1
; ARMV6-NEXT:    lsl r1, r0, #1
; ARMV6-NEXT:    orr r1, r1, r3, lsr #31
; ARMV6-NEXT:    orr r10, r5, r1
; ARMV6-NEXT:    ldr r1, [sp, #116] @ 4-byte Reload
; ARMV6-NEXT:    lsl r1, r1, #1
; ARMV6-NEXT:    orr r1, r1, r0, lsr #31
; ARMV6-NEXT:    mov r0, r11
; ARMV6-NEXT:    orr r11, r5, r1
; ARMV6-NEXT:    mov r1, #0
; ARMV6-NEXT:    bne .LBB0_4
; ARMV6-NEXT:  .LBB0_5: @ %udiv-loop-exit2
; ARMV6-NEXT:    lsl r1, r9, #1
; ARMV6-NEXT:    orr r5, r1, r7, lsr #31
; ARMV6-NEXT:    lsl r1, r10, #1
; ARMV6-NEXT:    orr r4, r1, r9, lsr #31
; ARMV6-NEXT:    lsl r1, r11, #1
; ARMV6-NEXT:    orr r8, r6, r7, lsl #1
; ARMV6-NEXT:    orr r3, r1, r10, lsr #31
; ARMV6-NEXT:  .LBB0_6:
; ARMV6-NEXT:    ldr r0, [sp, #52] @ 4-byte Reload
; ARMV6-NEXT:    ldr r6, [sp, #48] @ 4-byte Reload
; ARMV6-NEXT:  .LBB0_7: @ %udiv-end1
; ARMV6-NEXT:    ldr r2, [sp, #292]
; ARMV6-NEXT:    ldr r1, [sp, #24] @ 4-byte Reload
; ARMV6-NEXT:    str r5, [sp, #76] @ 4-byte Spill
; ARMV6-NEXT:    subs r10, r1, r2, asr #31
; ARMV6-NEXT:    ldr r1, [sp, #32] @ 4-byte Reload
; ARMV6-NEXT:    str r3, [sp, #96] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r11, r1, r2, asr #31
; ARMV6-NEXT:    ldr r1, [sp, #36] @ 4-byte Reload
; ARMV6-NEXT:    str r8, [sp, #116] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r5, r1, r2, asr #31
; ARMV6-NEXT:    ldr r1, [sp, #28] @ 4-byte Reload
; ARMV6-NEXT:    str r4, [sp, #100] @ 4-byte Spill
; ARMV6-NEXT:    sbc r1, r1, r2, asr #31
; ARMV6-NEXT:    clz r2, r5
; ARMV6-NEXT:    add r7, r2, #32
; ARMV6-NEXT:    clz r2, r10
; ARMV6-NEXT:    cmp r1, #0
; ARMV6-NEXT:    add r2, r2, #32
; ARMV6-NEXT:    clzne r7, r1
; ARMV6-NEXT:    cmp r11, #0
; ARMV6-NEXT:    clzne r2, r11
; ARMV6-NEXT:    orrs r3, r5, r1
; ARMV6-NEXT:    addeq r7, r2, #64
; ARMV6-NEXT:    ldr r2, [sp, #308]
; ARMV6-NEXT:    ldr r3, [sp, #20] @ 4-byte Reload
; ARMV6-NEXT:    str r11, [sp, #60] @ 4-byte Spill
; ARMV6-NEXT:    subs lr, r6, r2, asr #31
; ARMV6-NEXT:    str r5, [sp, #52] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r9, r0, r2, asr #31
; ARMV6-NEXT:    ldr r0, [sp, #16] @ 4-byte Reload
; ARMV6-NEXT:    sbcs r8, r3, r2, asr #31
; ARMV6-NEXT:    clz r3, lr
; ARMV6-NEXT:    sbc r0, r0, r2, asr #31
; ARMV6-NEXT:    clz r2, r8
; ARMV6-NEXT:    add r2, r2, #32
; ARMV6-NEXT:    cmp r0, #0
; ARMV6-NEXT:    clzne r2, r0
; ARMV6-NEXT:    add r3, r3, #32
; ARMV6-NEXT:    cmp r9, #0
; ARMV6-NEXT:    str r0, [sp, #80] @ 4-byte Spill
; ARMV6-NEXT:    clzne r3, r9
; ARMV6-NEXT:    orrs r6, r8, r0
; ARMV6-NEXT:    addeq r2, r3, #64
; ARMV6-NEXT:    mov r6, #0
; ARMV6-NEXT:    subs r2, r2, r7
; ARMV6-NEXT:    str r9, [sp, #88] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r4, r6, #0
; ARMV6-NEXT:    str r4, [sp, #108] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r7, r6, #0
; ARMV6-NEXT:    mov r12, r2
; ARMV6-NEXT:    sbc r3, r6, #0
; ARMV6-NEXT:    rsbs r2, r2, #127
; ARMV6-NEXT:    rscs r2, r4, #0
; ARMV6-NEXT:    str r3, [sp, #112] @ 4-byte Spill
; ARMV6-NEXT:    rscs r2, r7, #0
; ARMV6-NEXT:    orr r4, lr, r8
; ARMV6-NEXT:    rscs r2, r3, #0
; ARMV6-NEXT:    orr r3, r10, r5
; ARMV6-NEXT:    orr r2, r11, r1
; ARMV6-NEXT:    str r7, [sp, #104] @ 4-byte Spill
; ARMV6-NEXT:    orr r2, r3, r2
; ARMV6-NEXT:    orr r3, r9, r0
; ARMV6-NEXT:    orr r3, r4, r3
; ARMV6-NEXT:    clz r2, r2
; ARMV6-NEXT:    clz r3, r3
; ARMV6-NEXT:    ldr r7, [sp, #12] @ 4-byte Reload
; ARMV6-NEXT:    ldr r4, [sp, #116] @ 4-byte Reload
; ARMV6-NEXT:    lsr r2, r2, #5
; ARMV6-NEXT:    lsr r3, r3, #5
; ARMV6-NEXT:    ldr r0, [sp, #96] @ 4-byte Reload
; ARMV6-NEXT:    orr r2, r3, r2
; ARMV6-NEXT:    ldr r3, [sp, #76] @ 4-byte Reload
; ARMV6-NEXT:    movlo r6, #1
; ARMV6-NEXT:    eor r4, r4, r7
; ARMV6-NEXT:    orr r2, r2, r6
; ARMV6-NEXT:    eor r6, r0, r7
; ARMV6-NEXT:    ldr r0, [sp, #100] @ 4-byte Reload
; ARMV6-NEXT:    subs r4, r4, r7
; ARMV6-NEXT:    eor r3, r3, r7
; ARMV6-NEXT:    mov r9, r10
; ARMV6-NEXT:    sbcs r3, r3, r7
; ARMV6-NEXT:    eor r0, r0, r7
; ARMV6-NEXT:    sbcs r0, r0, r7
; ARMV6-NEXT:    str r0, [sp, #28] @ 4-byte Spill
; ARMV6-NEXT:    sbc r0, r6, r7
; ARMV6-NEXT:    str r0, [sp, #24] @ 4-byte Spill
; ARMV6-NEXT:    ldr r0, [sp, #292]
; ARMV6-NEXT:    cmp r2, #0
; ARMV6-NEXT:    str r4, [sp, #36] @ 4-byte Spill
; ARMV6-NEXT:    mov r4, r11
; ARMV6-NEXT:    mov r10, r1
; ARMV6-NEXT:    mov r11, r5
; ARMV6-NEXT:    mov r6, r9
; ARMV6-NEXT:    str r3, [sp, #32] @ 4-byte Spill
; ARMV6-NEXT:    mov r3, r4
; ARMV6-NEXT:    asr r0, r0, #31
; ARMV6-NEXT:    movne r10, #0
; ARMV6-NEXT:    movne r11, #0
; ARMV6-NEXT:    movne r3, #0
; ARMV6-NEXT:    movne r6, #0
; ARMV6-NEXT:    str r1, [sp, #56] @ 4-byte Spill
; ARMV6-NEXT:    str r8, [sp, #84] @ 4-byte Spill
; ARMV6-NEXT:    str r0, [sp, #48] @ 4-byte Spill
; ARMV6-NEXT:    str lr, [sp, #92] @ 4-byte Spill
; ARMV6-NEXT:    bne .LBB0_13
; ARMV6-NEXT:  @ %bb.8: @ %udiv-end1
; ARMV6-NEXT:    ldr r0, [sp, #104] @ 4-byte Reload
; ARMV6-NEXT:    eor r1, r12, #127
; ARMV6-NEXT:    ldr r2, [sp, #108] @ 4-byte Reload
; ARMV6-NEXT:    orr r1, r1, r0
; ARMV6-NEXT:    ldr r0, [sp, #112] @ 4-byte Reload
; ARMV6-NEXT:    orr r5, r2, r0
; ARMV6-NEXT:    orrs r1, r1, r5
; ARMV6-NEXT:    beq .LBB0_13
; ARMV6-NEXT:  @ %bb.9: @ %udiv-bb1
; ARMV6-NEXT:    mov r10, #0
; ARMV6-NEXT:    str r9, [sp, #168]
; ARMV6-NEXT:    str r10, [sp, #164]
; ARMV6-NEXT:    add r3, sp, #152
; ARMV6-NEXT:    str r10, [sp, #160]
; ARMV6-NEXT:    mov r1, #12
; ARMV6-NEXT:    str r10, [sp, #156]
; ARMV6-NEXT:    add r3, r3, #16
; ARMV6-NEXT:    str r10, [sp, #152]
; ARMV6-NEXT:    ldr r0, [sp, #60] @ 4-byte Reload
; ARMV6-NEXT:    str r0, [sp, #172]
; ARMV6-NEXT:    ldr r8, [sp, #52] @ 4-byte Reload
; ARMV6-NEXT:    str r8, [sp, #176]
; ARMV6-NEXT:    ldr r0, [sp, #56] @ 4-byte Reload
; ARMV6-NEXT:    str r0, [sp, #180]
; ARMV6-NEXT:    rsb r0, r12, #127
; ARMV6-NEXT:    and r1, r1, r0, lsr #3
; ARMV6-NEXT:    and r0, r0, #31
; ARMV6-NEXT:    eor r2, r0, #31
; ARMV6-NEXT:    ldr r6, [r3, -r1]!
; ARMV6-NEXT:    ldmib r3, {r1, r5}
; ARMV6-NEXT:    lsr r4, r5, #1
; ARMV6-NEXT:    lsl r7, r6, r0
; ARMV6-NEXT:    ldr r3, [r3, #12]
; ARMV6-NEXT:    str r9, [sp, #8] @ 4-byte Spill
; ARMV6-NEXT:    lsl r3, r3, r0
; ARMV6-NEXT:    orr r3, r3, r4, lsr r2
; ARMV6-NEXT:    str r3, [sp, #116] @ 4-byte Spill
; ARMV6-NEXT:    lsl r3, r5, r0
; ARMV6-NEXT:    lsrs r5, r1, #1
; ARMV6-NEXT:    orr r4, r3, r5, lsr r2
; ARMV6-NEXT:    lsl r1, r1, r0
; ARMV6-NEXT:    lsr r3, r6, #1
; ARMV6-NEXT:    adds r0, r12, #1
; ARMV6-NEXT:    orr r11, r1, r3, lsr r2
; ARMV6-NEXT:    ldr r1, [sp, #108] @ 4-byte Reload
; ARMV6-NEXT:    adcs r1, r1, #0
; ARMV6-NEXT:    str r1, [sp, #100] @ 4-byte Spill
; ARMV6-NEXT:    ldr r1, [sp, #104] @ 4-byte Reload
; ARMV6-NEXT:    adcs lr, r1, #0
; ARMV6-NEXT:    ldr r1, [sp, #112] @ 4-byte Reload
; ARMV6-NEXT:    adcs r1, r1, #0
; ARMV6-NEXT:    str r1, [sp, #108] @ 4-byte Spill
; ARMV6-NEXT:    adcs r2, r10, #0
; ARMV6-NEXT:    bne .LBB0_15
; ARMV6-NEXT:  @ %bb.10: @ %udiv-preheader
; ARMV6-NEXT:    str r9, [sp, #120]
; ARMV6-NEXT:    add r9, sp, #120
; ARMV6-NEXT:    str r10, [sp, #148]
; ARMV6-NEXT:    str r10, [sp, #144]
; ARMV6-NEXT:    str r10, [sp, #140]
; ARMV6-NEXT:    str r10, [sp, #136]
; ARMV6-NEXT:    ldr r1, [sp, #60] @ 4-byte Reload
; ARMV6-NEXT:    str r8, [sp, #128]
; ARMV6-NEXT:    and r8, r0, #31
; ARMV6-NEXT:    str r1, [sp, #124]
; ARMV6-NEXT:    ldr r1, [sp, #56] @ 4-byte Reload
; ARMV6-NEXT:    str r1, [sp, #132]
; ARMV6-NEXT:    mov r1, #12
; ARMV6-NEXT:    and r2, r1, r0, lsr #3
; ARMV6-NEXT:    add r5, r9, r2
; ARMV6-NEXT:    ldmib r5, {r1, r3, r10}
; ARMV6-NEXT:    lsr r5, r3, r8
; ARMV6-NEXT:    lsl r6, r10, #1
; ARMV6-NEXT:    str r0, [sp, #112] @ 4-byte Spill
; ARMV6-NEXT:    eor r0, r8, #31
; ARMV6-NEXT:    ldr r2, [r9, r2]
; ARMV6-NEXT:    lsl r3, r3, #1
; ARMV6-NEXT:    orr r6, r5, r6, lsl r0
; ARMV6-NEXT:    lsr r5, r1, r8
; ARMV6-NEXT:    orr r12, r5, r3, lsl r0
; ARMV6-NEXT:    lsl r3, r1, #1
; ARMV6-NEXT:    lsr r10, r10, r8
; ARMV6-NEXT:    lsr r2, r2, r8
; ARMV6-NEXT:    orr r5, r2, r3, lsl r0
; ARMV6-NEXT:    ldr r0, [sp, #92] @ 4-byte Reload
; ARMV6-NEXT:    mov r9, #0
; ARMV6-NEXT:    ldr r2, [sp, #80] @ 4-byte Reload
; ARMV6-NEXT:    subs r0, r0, #1
; ARMV6-NEXT:    str r0, [sp, #76] @ 4-byte Spill
; ARMV6-NEXT:    ldr r0, [sp, #88] @ 4-byte Reload
; ARMV6-NEXT:    ldr r1, [sp, #116] @ 4-byte Reload
; ARMV6-NEXT:    sbcs r0, r0, #0
; ARMV6-NEXT:    str r0, [sp, #72] @ 4-byte Spill
; ARMV6-NEXT:    ldr r0, [sp, #84] @ 4-byte Reload
; ARMV6-NEXT:    ldr r8, [sp, #100] @ 4-byte Reload
; ARMV6-NEXT:    sbcs r0, r0, #0
; ARMV6-NEXT:    str r0, [sp, #68] @ 4-byte Spill
; ARMV6-NEXT:    sbc r0, r2, #0
; ARMV6-NEXT:    str r0, [sp, #64] @ 4-byte Spill
; ARMV6-NEXT:    ldr r0, [sp, #108] @ 4-byte Reload
; ARMV6-NEXT:    mov r2, #0
; ARMV6-NEXT:  .LBB0_11: @ %udiv-do-while
; ARMV6-NEXT:    @ =>This Inner Loop Header: Depth=1
; ARMV6-NEXT:    add r3, sp, #96
; ARMV6-NEXT:    str r4, [sp, #108] @ 4-byte Spill
; ARMV6-NEXT:    stm r3, {r2, r7, r11} @ 12-byte Folded Spill
; ARMV6-NEXT:    lsl r2, r10, #1
; ARMV6-NEXT:    lsl r3, r6, #1
; ARMV6-NEXT:    orr r2, r2, r6, lsr #31
; ARMV6-NEXT:    lsl r6, r12, #1
; ARMV6-NEXT:    orr r6, r6, r5, lsr #31
; ARMV6-NEXT:    lsl r5, r5, #1
; ARMV6-NEXT:    ldr r4, [sp, #76] @ 4-byte Reload
; ARMV6-NEXT:    orr r5, r5, r1, lsr #31
; ARMV6-NEXT:    orr r3, r3, r12, lsr #31
; ARMV6-NEXT:    ldr r7, [sp, #64] @ 4-byte Reload
; ARMV6-NEXT:    subs r4, r4, r5
; ARMV6-NEXT:    str r1, [sp, #116] @ 4-byte Spill
; ARMV6-NEXT:    ldr r4, [sp, #72] @ 4-byte Reload
; ARMV6-NEXT:    ldr r1, [sp, #84] @ 4-byte Reload
; ARMV6-NEXT:    sbcs r4, r4, r6
; ARMV6-NEXT:    ldr r4, [sp, #68] @ 4-byte Reload
; ARMV6-NEXT:    sbcs r4, r4, r3
; ARMV6-NEXT:    sbc r4, r7, r2
; ARMV6-NEXT:    ldr r7, [sp, #80] @ 4-byte Reload
; ARMV6-NEXT:    and r10, r7, r4, asr #31
; ARMV6-NEXT:    and r7, r1, r4, asr #31
; ARMV6-NEXT:    ldr r1, [sp, #88] @ 4-byte Reload
; ARMV6-NEXT:    and r11, r1, r4, asr #31
; ARMV6-NEXT:    ldr r1, [sp, #92] @ 4-byte Reload
; ARMV6-NEXT:    and r12, r1, r4, asr #31
; ARMV6-NEXT:    mov r1, #1
; ARMV6-NEXT:    subs r5, r5, r12
; ARMV6-NEXT:    sbcs r12, r6, r11
; ARMV6-NEXT:    sbcs r6, r3, r7
; ARMV6-NEXT:    sbc r10, r2, r10
; ARMV6-NEXT:    and r2, r1, r4, asr #31
; ARMV6-NEXT:    ldr r1, [sp, #112] @ 4-byte Reload
; ARMV6-NEXT:    subs r1, r1, #1
; ARMV6-NEXT:    str r1, [sp, #112] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r8, r8, #0
; ARMV6-NEXT:    sbcs lr, lr, #0
; ARMV6-NEXT:    sbc r0, r0, #0
; ARMV6-NEXT:    orr r4, r1, lr
; ARMV6-NEXT:    orr r3, r8, r0
; ARMV6-NEXT:    ldr r1, [sp, #100] @ 4-byte Reload
; ARMV6-NEXT:    orrs r3, r4, r3
; ARMV6-NEXT:    ldr r3, [sp, #96] @ 4-byte Reload
; ARMV6-NEXT:    orr r7, r3, r1, lsl #1
; ARMV6-NEXT:    ldr r3, [sp, #104] @ 4-byte Reload
; ARMV6-NEXT:    lsl r4, r3, #1
; ARMV6-NEXT:    orr r1, r4, r1, lsr #31
; ARMV6-NEXT:    orr r11, r9, r1
; ARMV6-NEXT:    ldr r1, [sp, #108] @ 4-byte Reload
; ARMV6-NEXT:    lsl r4, r1, #1
; ARMV6-NEXT:    orr r4, r4, r3, lsr #31
; ARMV6-NEXT:    ldr r3, [sp, #116] @ 4-byte Reload
; ARMV6-NEXT:    orr r4, r9, r4
; ARMV6-NEXT:    lsl r3, r3, #1
; ARMV6-NEXT:    orr r3, r3, r1, lsr #31
; ARMV6-NEXT:    orr r1, r9, r3
; ARMV6-NEXT:    mov r9, #0
; ARMV6-NEXT:    bne .LBB0_11
; ARMV6-NEXT:  .LBB0_12: @ %udiv-loop-exit
; ARMV6-NEXT:    lsl r0, r11, #1
; ARMV6-NEXT:    orr r3, r0, r7, lsr #31
; ARMV6-NEXT:    lsl r0, r4, #1
; ARMV6-NEXT:    ldr r9, [sp, #8] @ 4-byte Reload
; ARMV6-NEXT:    orr r11, r0, r11, lsr #31
; ARMV6-NEXT:    lsl r0, r1, #1
; ARMV6-NEXT:    orr r6, r2, r7, lsl #1
; ARMV6-NEXT:    orr r10, r0, r4, lsr #31
; ARMV6-NEXT:  .LBB0_13: @ %udiv-end
; ARMV6-NEXT:    ldr r1, [sp, #40] @ 4-byte Reload
; ARMV6-NEXT:    mov r4, #0
; ARMV6-NEXT:    ldr r0, [sp, #36] @ 4-byte Reload
; ARMV6-NEXT:    mov r12, #0
; ARMV6-NEXT:    ldr r2, [sp, #88] @ 4-byte Reload
; ARMV6-NEXT:    str r0, [r1]
; ARMV6-NEXT:    ldr r0, [sp, #32] @ 4-byte Reload
; ARMV6-NEXT:    str r0, [r1, #4]
; ARMV6-NEXT:    ldr r0, [sp, #28] @ 4-byte Reload
; ARMV6-NEXT:    str r0, [r1, #8]
; ARMV6-NEXT:    ldr r0, [sp, #24] @ 4-byte Reload
; ARMV6-NEXT:    str r0, [r1, #12]
; ARMV6-NEXT:    ldr r0, [sp, #92] @ 4-byte Reload
; ARMV6-NEXT:    ldr lr, [sp, #80] @ 4-byte Reload
; ARMV6-NEXT:    umull r1, r7, r0, r6
; ARMV6-NEXT:    umlal r7, r4, r2, r6
; ARMV6-NEXT:    str r1, [sp, #116] @ 4-byte Spill
; ARMV6-NEXT:    umull r5, r1, r0, r3
; ARMV6-NEXT:    adds r8, r5, r7
; ARMV6-NEXT:    adcs r1, r4, r1
; ARMV6-NEXT:    ldr r4, [sp, #84] @ 4-byte Reload
; ARMV6-NEXT:    adc r7, r12, #0
; ARMV6-NEXT:    umlal r1, r7, r2, r3
; ARMV6-NEXT:    umull r12, r5, r6, r4
; ARMV6-NEXT:    mla r6, r6, lr, r5
; ARMV6-NEXT:    mla r3, r3, r4, r6
; ARMV6-NEXT:    umull r6, r5, r11, r0
; ARMV6-NEXT:    mla r2, r11, r2, r5
; ARMV6-NEXT:    mla r0, r10, r0, r2
; ARMV6-NEXT:    adds r2, r6, r12
; ARMV6-NEXT:    adc r0, r0, r3
; ARMV6-NEXT:    adds r1, r1, r2
; ARMV6-NEXT:    ldr r2, [sp, #116] @ 4-byte Reload
; ARMV6-NEXT:    adc r0, r7, r0
; ARMV6-NEXT:    ldr r3, [sp, #60] @ 4-byte Reload
; ARMV6-NEXT:    subs r2, r9, r2
; ARMV6-NEXT:    ldr r7, [sp, #52] @ 4-byte Reload
; ARMV6-NEXT:    sbcs r3, r3, r8
; ARMV6-NEXT:    sbcs r1, r7, r1
; ARMV6-NEXT:    ldr r7, [sp, #56] @ 4-byte Reload
; ARMV6-NEXT:    sbc r0, r7, r0
; ARMV6-NEXT:    ldr r7, [sp, #48] @ 4-byte Reload
; ARMV6-NEXT:    eor r2, r2, r7
; ARMV6-NEXT:    eor r3, r3, r7
; ARMV6-NEXT:    subs r2, r2, r7
; ARMV6-NEXT:    eor r1, r1, r7
; ARMV6-NEXT:    sbcs r3, r3, r7
; ARMV6-NEXT:    eor r0, r0, r7
; ARMV6-NEXT:    sbcs r1, r1, r7
; ARMV6-NEXT:    sbc r0, r0, r7
; ARMV6-NEXT:    ldr r7, [sp, #44] @ 4-byte Reload
; ARMV6-NEXT:    stm r7, {r2, r3}
; ARMV6-NEXT:    str r1, [r7, #8]
; ARMV6-NEXT:    str r0, [r7, #12]
; ARMV6-NEXT:    add sp, sp, #252
; ARMV6-NEXT:    pop {r4, r5, r6, r7, r8, r9, r10, r11, pc}
; ARMV6-NEXT:  .LBB0_14:
; ARMV6-NEXT:    ldr r11, [sp, #116] @ 4-byte Reload
; ARMV6-NEXT:    mov r6, #0
; ARMV6-NEXT:    ldr r7, [sp, #96] @ 4-byte Reload
; ARMV6-NEXT:    ldr r10, [sp, #92] @ 4-byte Reload
; ARMV6-NEXT:    ldr r9, [sp, #88] @ 4-byte Reload
; ARMV6-NEXT:    b .LBB0_5
; ARMV6-NEXT:  .LBB0_15:
; ARMV6-NEXT:    ldr r1, [sp, #116] @ 4-byte Reload
; ARMV6-NEXT:    mov r2, #0
; ARMV6-NEXT:    b .LBB0_12
;
; ARMV7-LABEL: sdivrem_i128:
; ARMV7:       @ %bb.0: @ %_udiv-special-cases_udiv-special-cases
; ARMV7-NEXT:    .save {r4, r5, r6, r7, r8, r9, r10, r11, lr}
; ARMV7-NEXT:    push {r4, r5, r6, r7, r8, r9, r10, r11, lr}
; ARMV7-NEXT:    .pad #244
; ARMV7-NEXT:    sub sp, sp, #244
; ARMV7-NEXT:    ldr r10, [sp, #284]
; ARMV7-NEXT:    str r0, [sp, #28] @ 4-byte Spill
; ARMV7-NEXT:    ldr r0, [sp, #280]
; ARMV7-NEXT:    eor r2, r2, r10, asr #31
; ARMV7-NEXT:    str r1, [sp, #32] @ 4-byte Spill
; ARMV7-NEXT:    eor r1, r3, r10, asr #31
; ARMV7-NEXT:    str r2, [sp, #44] @ 4-byte Spill
; ARMV7-NEXT:    subs r2, r2, r10, asr #31
; ARMV7-NEXT:    eor r0, r0, r10, asr #31
; ARMV7-NEXT:    sbcs r11, r1, r10, asr #31
; ARMV7-NEXT:    str r1, [sp, #36] @ 4-byte Spill
; ARMV7-NEXT:    eor r1, r10, r10, asr #31
; ARMV7-NEXT:    sbcs r9, r0, r10, asr #31
; ARMV7-NEXT:    sbc r12, r1, r10, asr #31
; ARMV7-NEXT:    str r0, [sp, #40] @ 4-byte Spill
; ARMV7-NEXT:    clz r0, r9
; ARMV7-NEXT:    str r1, [sp, #24] @ 4-byte Spill
; ARMV7-NEXT:    clz r1, r2
; ARMV7-NEXT:    add r0, r0, #32
; ARMV7-NEXT:    cmp r12, #0
; ARMV7-NEXT:    add r1, r1, #32
; ARMV7-NEXT:    clzne r0, r12
; ARMV7-NEXT:    cmp r11, #0
; ARMV7-NEXT:    ldr r6, [sp, #300]
; ARMV7-NEXT:    clzne r1, r11
; ARMV7-NEXT:    ldr r3, [sp, #288]
; ARMV7-NEXT:    str r2, [sp, #88] @ 4-byte Spill
; ARMV7-NEXT:    orrs r2, r9, r12
; ARMV7-NEXT:    ldr r2, [sp, #292]
; ARMV7-NEXT:    addeq r0, r1, #64
; ARMV7-NEXT:    ldr r1, [sp, #296]
; ARMV7-NEXT:    eor r3, r3, r6, asr #31
; ARMV7-NEXT:    eor r2, r2, r6, asr #31
; ARMV7-NEXT:    subs lr, r3, r6, asr #31
; ARMV7-NEXT:    eor r1, r1, r6, asr #31
; ARMV7-NEXT:    sbcs r4, r2, r6, asr #31
; ARMV7-NEXT:    str r2, [sp, #12] @ 4-byte Spill
; ARMV7-NEXT:    eor r2, r6, r6, asr #31
; ARMV7-NEXT:    sbcs r5, r1, r6, asr #31
; ARMV7-NEXT:    str r1, [sp, #48] @ 4-byte Spill
; ARMV7-NEXT:    sbc r7, r2, r6, asr #31
; ARMV7-NEXT:    clz r1, r5
; ARMV7-NEXT:    str r2, [sp, #8] @ 4-byte Spill
; ARMV7-NEXT:    clz r2, lr
; ARMV7-NEXT:    add r1, r1, #32
; ARMV7-NEXT:    cmp r7, #0
; ARMV7-NEXT:    clzne r1, r7
; ARMV7-NEXT:    add r2, r2, #32
; ARMV7-NEXT:    cmp r4, #0
; ARMV7-NEXT:    str r3, [sp, #16] @ 4-byte Spill
; ARMV7-NEXT:    clzne r2, r4
; ARMV7-NEXT:    orrs r3, r5, r7
; ARMV7-NEXT:    addeq r1, r2, #64
; ARMV7-NEXT:    str r7, [sp, #68] @ 4-byte Spill
; ARMV7-NEXT:    subs r8, r1, r0
; ARMV7-NEXT:    mov r0, #0
; ARMV7-NEXT:    sbcs r1, r0, #0
; ARMV7-NEXT:    str r1, [sp, #100] @ 4-byte Spill
; ARMV7-NEXT:    sbcs r2, r0, #0
; ARMV7-NEXT:    str r2, [sp, #96] @ 4-byte Spill
; ARMV7-NEXT:    sbc r3, r0, #0
; ARMV7-NEXT:    rsbs r0, r8, #127
; ARMV7-NEXT:    rscs r0, r1, #0
; ARMV7-NEXT:    orr r1, r4, r7
; ARMV7-NEXT:    ldr r7, [sp, #88] @ 4-byte Reload
; ARMV7-NEXT:    rscs r0, r2, #0
; ARMV7-NEXT:    orr r2, lr, r5
; ARMV7-NEXT:    rscs r0, r3, #0
; ARMV7-NEXT:    orr r1, r2, r1
; ARMV7-NEXT:    str r3, [sp, #92] @ 4-byte Spill
; ARMV7-NEXT:    orr r2, r11, r12
; ARMV7-NEXT:    orr r3, r7, r9
; ARMV7-NEXT:    orr r2, r3, r2
; ARMV7-NEXT:    clz r1, r1
; ARMV7-NEXT:    clz r2, r2
; ARMV7-NEXT:    mov r0, #0
; ARMV7-NEXT:    lsr r1, r1, #5
; ARMV7-NEXT:    movwlo r0, #1
; ARMV7-NEXT:    lsr r2, r2, #5
; ARMV7-NEXT:    orr r1, r1, r2
; ARMV7-NEXT:    orrs r0, r1, r0
; ARMV7-NEXT:    mov r3, r9
; ARMV7-NEXT:    asr r0, r6, #31
; ARMV7-NEXT:    mov r6, r7
; ARMV7-NEXT:    eor r0, r0, r10, asr #31
; ARMV7-NEXT:    mov r1, r12
; ARMV7-NEXT:    str r0, [sp, #20] @ 4-byte Spill
; ARMV7-NEXT:    mov r0, r11
; ARMV7-NEXT:    movwne r0, #0
; ARMV7-NEXT:    movwne r6, #0
; ARMV7-NEXT:    movwne r3, #0
; ARMV7-NEXT:    movwne r1, #0
; ARMV7-NEXT:    str r0, [sp, #108] @ 4-byte Spill
; ARMV7-NEXT:    bne .LBB0_15
; ARMV7-NEXT:  @ %bb.1: @ %_udiv-special-cases_udiv-special-cases
; ARMV7-NEXT:    mov r10, r7
; ARMV7-NEXT:    ldr r7, [sp, #96] @ 4-byte Reload
; ARMV7-NEXT:    eor r0, r8, #127
; ARMV7-NEXT:    mov r2, r11
; ARMV7-NEXT:    str r5, [sp, #72] @ 4-byte Spill
; ARMV7-NEXT:    orr r0, r0, r7
; ARMV7-NEXT:    ldr r7, [sp, #100] @ 4-byte Reload
; ARMV7-NEXT:    ldr r5, [sp, #92] @ 4-byte Reload
; ARMV7-NEXT:    ldr r11, [sp, #48] @ 4-byte Reload
; ARMV7-NEXT:    orr r7, r7, r5
; ARMV7-NEXT:    str r4, [sp, #76] @ 4-byte Spill
; ARMV7-NEXT:    orrs r0, r0, r7
; ARMV7-NEXT:    str lr, [sp, #80] @ 4-byte Spill
; ARMV7-NEXT:    beq .LBB0_6
; ARMV7-NEXT:  @ %bb.2: @ %udiv-bb15
; ARMV7-NEXT:    mov r0, #0
; ARMV7-NEXT:    mov r1, #12
; ARMV7-NEXT:    str r0, [sp, #220]
; ARMV7-NEXT:    mov r11, r2
; ARMV7-NEXT:    str r0, [sp, #216]
; ARMV7-NEXT:    str r0, [sp, #212]
; ARMV7-NEXT:    str r0, [sp, #208]
; ARMV7-NEXT:    add r0, sp, #228
; ARMV7-NEXT:    stm r0, {r2, r9, r12}
; ARMV7-NEXT:    rsb r0, r8, #127
; ARMV7-NEXT:    add r2, sp, #208
; ARMV7-NEXT:    and r1, r1, r0, lsr #3
; ARMV7-NEXT:    add r2, r2, #16
; ARMV7-NEXT:    str r10, [sp, #224]
; ARMV7-NEXT:    and r6, r0, #31
; ARMV7-NEXT:    ldr r1, [r2, -r1]!
; ARMV7-NEXT:    eor r4, r6, #31
; ARMV7-NEXT:    str r9, [sp, #64] @ 4-byte Spill
; ARMV7-NEXT:    ldmib r2, {r3, r7}
; ARMV7-NEXT:    lsr r5, r1, #1
; ARMV7-NEXT:    ldr r2, [r2, #12]
; ARMV7-NEXT:    lsl r0, r3, r6
; ARMV7-NEXT:    orr r9, r0, r5, lsr r4
; ARMV7-NEXT:    lsr r5, r7, #1
; ARMV7-NEXT:    lsrs r3, r3, #1
; ARMV7-NEXT:    lsl r2, r2, r6
; ARMV7-NEXT:    orr r0, r2, r5, lsr r4
; ARMV7-NEXT:    str r0, [sp, #108] @ 4-byte Spill
; ARMV7-NEXT:    lsl r2, r7, r6
; ARMV7-NEXT:    ldr r0, [sp, #100] @ 4-byte Reload
; ARMV7-NEXT:    orr lr, r2, r3, lsr r4
; ARMV7-NEXT:    adds r4, r8, #1
; ARMV7-NEXT:    lsl r2, r1, r6
; ARMV7-NEXT:    adcs r8, r0, #0
; ARMV7-NEXT:    ldr r0, [sp, #96] @ 4-byte Reload
; ARMV7-NEXT:    mov r3, #0
; ARMV7-NEXT:    adcs r0, r0, #0
; ARMV7-NEXT:    str r0, [sp, #84] @ 4-byte Spill
; ARMV7-NEXT:    ldr r0, [sp, #92] @ 4-byte Reload
; ARMV7-NEXT:    adcs r0, r0, #0
; ARMV7-NEXT:    str r0, [sp, #96] @ 4-byte Spill
; ARMV7-NEXT:    mov r0, #0
; ARMV7-NEXT:    adcs r1, r3, #0
; ARMV7-NEXT:    str r0, [sp, #104] @ 4-byte Spill
; ARMV7-NEXT:    bne .LBB0_13
; ARMV7-NEXT:  @ %bb.3: @ %udiv-preheader4
; ARMV7-NEXT:    mov r1, #0
; ARMV7-NEXT:    str r10, [sp, #176]
; ARMV7-NEXT:    str r1, [sp, #204]
; ARMV7-NEXT:    add r10, sp, #176
; ARMV7-NEXT:    str r1, [sp, #200]
; ARMV7-NEXT:    str r1, [sp, #196]
; ARMV7-NEXT:    str r1, [sp, #192]
; ARMV7-NEXT:    ubfx r1, r4, #5, #2
; ARMV7-NEXT:    str r11, [sp, #180]
; ARMV7-NEXT:    ldr r0, [sp, #64] @ 4-byte Reload
; ARMV7-NEXT:    add r3, r10, r1, lsl #2
; ARMV7-NEXT:    str r0, [sp, #184]
; ARMV7-NEXT:    and r0, r4, #31
; ARMV7-NEXT:    str r12, [sp, #188]
; ARMV7-NEXT:    ldmib r3, {r5, r6, r12}
; ARMV7-NEXT:    lsr r3, r6, r0
; ARMV7-NEXT:    lsl r7, r12, #1
; ARMV7-NEXT:    str r4, [sp, #100] @ 4-byte Spill
; ARMV7-NEXT:    eor r4, r0, #31
; ARMV7-NEXT:    ldr r1, [r10, r1, lsl #2]
; ARMV7-NEXT:    lsl r6, r6, #1
; ARMV7-NEXT:    orr r3, r3, r7, lsl r4
; ARMV7-NEXT:    lsr r7, r5, r0
; ARMV7-NEXT:    lsl r5, r5, #1
; ARMV7-NEXT:    orr r6, r7, r6, lsl r4
; ARMV7-NEXT:    lsr r12, r12, r0
; ARMV7-NEXT:    lsr r1, r1, r0
; ARMV7-NEXT:    orr r7, r1, r5, lsl r4
; ARMV7-NEXT:    ldr r1, [sp, #80] @ 4-byte Reload
; ARMV7-NEXT:    mov r10, #0
; ARMV7-NEXT:    ldr r0, [sp, #108] @ 4-byte Reload
; ARMV7-NEXT:    subs r1, r1, #1
; ARMV7-NEXT:    str r1, [sp, #64] @ 4-byte Spill
; ARMV7-NEXT:    ldr r1, [sp, #76] @ 4-byte Reload
; ARMV7-NEXT:    ldr r11, [sp, #84] @ 4-byte Reload
; ARMV7-NEXT:    sbcs r1, r1, #0
; ARMV7-NEXT:    str r1, [sp, #60] @ 4-byte Spill
; ARMV7-NEXT:    ldr r1, [sp, #72] @ 4-byte Reload
; ARMV7-NEXT:    sbcs r1, r1, #0
; ARMV7-NEXT:    str r1, [sp, #56] @ 4-byte Spill
; ARMV7-NEXT:    ldr r1, [sp, #68] @ 4-byte Reload
; ARMV7-NEXT:    sbc r1, r1, #0
; ARMV7-NEXT:    str r1, [sp, #52] @ 4-byte Spill
; ARMV7-NEXT:    ldr r1, [sp, #96] @ 4-byte Reload
; ARMV7-NEXT:  .LBB0_4: @ %udiv-do-while3
; ARMV7-NEXT:    @ =>This Inner Loop Header: Depth=1
; ARMV7-NEXT:    lsl r5, r12, #1
; ARMV7-NEXT:    add r4, sp, #88
; ARMV7-NEXT:    orr r5, r5, r3, lsr #31
; ARMV7-NEXT:    lsl r3, r3, #1
; ARMV7-NEXT:    stm r4, {r2, r9, lr} @ 12-byte Folded Spill
; ARMV7-NEXT:    orr r3, r3, r6, lsr #31
; ARMV7-NEXT:    lsl r6, r6, #1
; ARMV7-NEXT:    ldr r2, [sp, #104] @ 4-byte Reload
; ARMV7-NEXT:    orr r6, r6, r7, lsr #31
; ARMV7-NEXT:    lsl r7, r7, #1
; ARMV7-NEXT:    str r2, [sp, #84] @ 4-byte Spill
; ARMV7-NEXT:    ldr r2, [sp, #64] @ 4-byte Reload
; ARMV7-NEXT:    orr r7, r7, r0, lsr #31
; ARMV7-NEXT:    str r0, [sp, #108] @ 4-byte Spill
; ARMV7-NEXT:    subs r2, r2, r7
; ARMV7-NEXT:    ldr r0, [sp, #72] @ 4-byte Reload
; ARMV7-NEXT:    ldr r2, [sp, #60] @ 4-byte Reload
; ARMV7-NEXT:    ldr r4, [sp, #68] @ 4-byte Reload
; ARMV7-NEXT:    sbcs r2, r2, r6
; ARMV7-NEXT:    ldr r2, [sp, #56] @ 4-byte Reload
; ARMV7-NEXT:    sbcs r2, r2, r3
; ARMV7-NEXT:    ldr r2, [sp, #52] @ 4-byte Reload
; ARMV7-NEXT:    sbc r2, r2, r5
; ARMV7-NEXT:    and r9, r0, r2, asr #31
; ARMV7-NEXT:    ldr r0, [sp, #76] @ 4-byte Reload
; ARMV7-NEXT:    and r4, r4, r2, asr #31
; ARMV7-NEXT:    and lr, r0, r2, asr #31
; ARMV7-NEXT:    ldr r0, [sp, #80] @ 4-byte Reload
; ARMV7-NEXT:    and r12, r0, r2, asr #31
; ARMV7-NEXT:    mov r0, #1
; ARMV7-NEXT:    subs r7, r7, r12
; ARMV7-NEXT:    and r0, r0, r2, asr #31
; ARMV7-NEXT:    sbcs r6, r6, lr
; ARMV7-NEXT:    str r0, [sp, #104] @ 4-byte Spill
; ARMV7-NEXT:    ldr r0, [sp, #100] @ 4-byte Reload
; ARMV7-NEXT:    sbcs r3, r3, r9
; ARMV7-NEXT:    sbc r12, r5, r4
; ARMV7-NEXT:    ldr r4, [sp, #92] @ 4-byte Reload
; ARMV7-NEXT:    subs r0, r0, #1
; ARMV7-NEXT:    str r0, [sp, #100] @ 4-byte Spill
; ARMV7-NEXT:    sbcs r8, r8, #0
; ARMV7-NEXT:    sbcs r11, r11, #0
; ARMV7-NEXT:    sbc r1, r1, #0
; ARMV7-NEXT:    orr r5, r0, r11
; ARMV7-NEXT:    orr r2, r8, r1
; ARMV7-NEXT:    ldr r0, [sp, #88] @ 4-byte Reload
; ARMV7-NEXT:    orrs r2, r5, r2
; ARMV7-NEXT:    lsl r5, r4, #1
; ARMV7-NEXT:    ldr r2, [sp, #84] @ 4-byte Reload
; ARMV7-NEXT:    orr r2, r2, r0, lsl #1
; ARMV7-NEXT:    orr r0, r5, r0, lsr #31
; ARMV7-NEXT:    orr r9, r10, r0
; ARMV7-NEXT:    ldr r0, [sp, #96] @ 4-byte Reload
; ARMV7-NEXT:    lsl r5, r0, #1
; ARMV7-NEXT:    orr r5, r5, r4, lsr #31
; ARMV7-NEXT:    ldr r4, [sp, #108] @ 4-byte Reload
; ARMV7-NEXT:    orr lr, r10, r5
; ARMV7-NEXT:    lsl r5, r4, #1
; ARMV7-NEXT:    orr r5, r5, r0, lsr #31
; ARMV7-NEXT:    orr r0, r10, r5
; ARMV7-NEXT:    mov r10, #0
; ARMV7-NEXT:    bne .LBB0_4
; ARMV7-NEXT:  .LBB0_5: @ %udiv-loop-exit2
; ARMV7-NEXT:    ldr r1, [sp, #104] @ 4-byte Reload
; ARMV7-NEXT:    lsl r0, r0, #1
; ARMV7-NEXT:    ldr r11, [sp, #48] @ 4-byte Reload
; ARMV7-NEXT:    orr r6, r1, r2, lsl #1
; ARMV7-NEXT:    lsl r1, r9, #1
; ARMV7-NEXT:    orr r1, r1, r2, lsr #31
; ARMV7-NEXT:    str r1, [sp, #108] @ 4-byte Spill
; ARMV7-NEXT:    lsl r2, lr, #1
; ARMV7-NEXT:    orr r3, r2, r9, lsr #31
; ARMV7-NEXT:    orr r1, r0, lr, lsr #31
; ARMV7-NEXT:  .LBB0_6: @ %udiv-end1
; ARMV7-NEXT:    ldr r2, [sp, #284]
; ARMV7-NEXT:    ldr r0, [sp, #44] @ 4-byte Reload
; ARMV7-NEXT:    ldr r7, [sp, #24] @ 4-byte Reload
; ARMV7-NEXT:    subs r8, r0, r2, asr #31
; ARMV7-NEXT:    ldr r0, [sp, #36] @ 4-byte Reload
; ARMV7-NEXT:    ldr r4, [sp, #300]
; ARMV7-NEXT:    sbcs r10, r0, r2, asr #31
; ARMV7-NEXT:    ldr r0, [sp, #40] @ 4-byte Reload
; ARMV7-NEXT:    str r3, [sp, #96] @ 4-byte Spill
; ARMV7-NEXT:    sbcs lr, r0, r2, asr #31
; ARMV7-NEXT:    ldr r3, [sp, #16] @ 4-byte Reload
; ARMV7-NEXT:    sbc r9, r7, r2, asr #31
; ARMV7-NEXT:    clz r0, lr
; ARMV7-NEXT:    clz r7, r8
; ARMV7-NEXT:    add r0, r0, #32
; ARMV7-NEXT:    cmp r9, #0
; ARMV7-NEXT:    add r7, r7, #32
; ARMV7-NEXT:    clzne r0, r9
; ARMV7-NEXT:    cmp r10, #0
; ARMV7-NEXT:    clzne r7, r10
; ARMV7-NEXT:    orrs r5, lr, r9
; ARMV7-NEXT:    addeq r0, r7, #64
; ARMV7-NEXT:    subs r12, r3, r4, asr #31
; ARMV7-NEXT:    ldr r3, [sp, #12] @ 4-byte Reload
; ARMV7-NEXT:    clz r5, r12
; ARMV7-NEXT:    str r6, [sp, #92] @ 4-byte Spill
; ARMV7-NEXT:    add r5, r5, #32
; ARMV7-NEXT:    sbcs r6, r3, r4, asr #31
; ARMV7-NEXT:    ldr r3, [sp, #8] @ 4-byte Reload
; ARMV7-NEXT:    sbcs r2, r11, r4, asr #31
; ARMV7-NEXT:    str r1, [sp, #88] @ 4-byte Spill
; ARMV7-NEXT:    sbc r3, r3, r4, asr #31
; ARMV7-NEXT:    clz r7, r2
; ARMV7-NEXT:    add r7, r7, #32
; ARMV7-NEXT:    cmp r3, #0
; ARMV7-NEXT:    clzne r7, r3
; ARMV7-NEXT:    cmp r6, #0
; ARMV7-NEXT:    clzne r5, r6
; ARMV7-NEXT:    orrs r4, r2, r3
; ARMV7-NEXT:    addeq r7, r5, #64
; ARMV7-NEXT:    str r6, [sp, #72] @ 4-byte Spill
; ARMV7-NEXT:    subs r11, r7, r0
; ARMV7-NEXT:    mov r7, #0
; ARMV7-NEXT:    sbcs r4, r7, #0
; ARMV7-NEXT:    str r4, [sp, #84] @ 4-byte Spill
; ARMV7-NEXT:    sbcs r5, r7, #0
; ARMV7-NEXT:    str r5, [sp, #104] @ 4-byte Spill
; ARMV7-NEXT:    sbc r1, r7, #0
; ARMV7-NEXT:    rsbs r0, r11, #127
; ARMV7-NEXT:    rscs r0, r4, #0
; ARMV7-NEXT:    orr r4, r8, lr
; ARMV7-NEXT:    rscs r0, r5, #0
; ARMV7-NEXT:    orr r5, r12, r2
; ARMV7-NEXT:    rscs r0, r1, #0
; ARMV7-NEXT:    str r1, [sp, #100] @ 4-byte Spill
; ARMV7-NEXT:    orr r0, r6, r3
; ARMV7-NEXT:    ldr r6, [sp, #20] @ 4-byte Reload
; ARMV7-NEXT:    orr r0, r5, r0
; ARMV7-NEXT:    orr r5, r10, r9
; ARMV7-NEXT:    clz r0, r0
; ARMV7-NEXT:    orr r4, r4, r5
; ARMV7-NEXT:    clz r4, r4
; ARMV7-NEXT:    ldr r1, [sp, #88] @ 4-byte Reload
; ARMV7-NEXT:    lsr r0, r0, #5
; ARMV7-NEXT:    movwlo r7, #1
; ARMV7-NEXT:    lsr r4, r4, #5
; ARMV7-NEXT:    orr r0, r0, r4
; ARMV7-NEXT:    orr r0, r0, r7
; ARMV7-NEXT:    eor r7, r1, r6
; ARMV7-NEXT:    ldr r1, [sp, #96] @ 4-byte Reload
; ARMV7-NEXT:    str r3, [sp, #64] @ 4-byte Spill
; ARMV7-NEXT:    ldr r3, [sp, #92] @ 4-byte Reload
; ARMV7-NEXT:    str r2, [sp, #68] @ 4-byte Spill
; ARMV7-NEXT:    eor r2, r1, r6
; ARMV7-NEXT:    ldr r1, [sp, #108] @ 4-byte Reload
; ARMV7-NEXT:    eor r4, r3, r6
; ARMV7-NEXT:    subs r3, r4, r6
; ARMV7-NEXT:    str r9, [sp, #36] @ 4-byte Spill
; ARMV7-NEXT:    eor r1, r1, r6
; ARMV7-NEXT:    str lr, [sp, #40] @ 4-byte Spill
; ARMV7-NEXT:    sbcs r1, r1, r6
; ARMV7-NEXT:    str r1, [sp, #12] @ 4-byte Spill
; ARMV7-NEXT:    sbcs r1, r2, r6
; ARMV7-NEXT:    str r1, [sp, #8] @ 4-byte Spill
; ARMV7-NEXT:    sbc r1, r7, r6
; ARMV7-NEXT:    str r1, [sp, #20] @ 4-byte Spill
; ARMV7-NEXT:    ldr r1, [sp, #284]
; ARMV7-NEXT:    cmp r0, #0
; ARMV7-NEXT:    mov r6, r8
; ARMV7-NEXT:    mov r2, r10
; ARMV7-NEXT:    movwne r6, #0
; ARMV7-NEXT:    movwne r2, #0
; ARMV7-NEXT:    asr r1, r1, #31
; ARMV7-NEXT:    movwne lr, #0
; ARMV7-NEXT:    movwne r9, #0
; ARMV7-NEXT:    str r3, [sp, #16] @ 4-byte Spill
; ARMV7-NEXT:    str r1, [sp, #24] @ 4-byte Spill
; ARMV7-NEXT:    str r8, [sp, #44] @ 4-byte Spill
; ARMV7-NEXT:    bne .LBB0_12
; ARMV7-NEXT:  @ %bb.7: @ %udiv-end1
; ARMV7-NEXT:    ldr r3, [sp, #104] @ 4-byte Reload
; ARMV7-NEXT:    eor r0, r11, #127
; ARMV7-NEXT:    mov r1, r8
; ARMV7-NEXT:    ldr r8, [sp, #84] @ 4-byte Reload
; ARMV7-NEXT:    orr r0, r0, r3
; ARMV7-NEXT:    ldr r3, [sp, #100] @ 4-byte Reload
; ARMV7-NEXT:    orr r4, r8, r3
; ARMV7-NEXT:    orrs r0, r0, r4
; ARMV7-NEXT:    beq .LBB0_12
; ARMV7-NEXT:  @ %bb.8: @ %udiv-bb1
; ARMV7-NEXT:    mov r7, #0
; ARMV7-NEXT:    str r12, [sp, #76] @ 4-byte Spill
; ARMV7-NEXT:    str r1, [sp, #160]
; ARMV7-NEXT:    rsb r0, r11, #127
; ARMV7-NEXT:    str r7, [sp, #156]
; ARMV7-NEXT:    mov r1, #12
; ARMV7-NEXT:    str r7, [sp, #152]
; ARMV7-NEXT:    add r2, sp, #144
; ARMV7-NEXT:    str r7, [sp, #148]
; ARMV7-NEXT:    and r1, r1, r0, lsr #3
; ARMV7-NEXT:    str r7, [sp, #144]
; ARMV7-NEXT:    add r2, r2, #16
; ARMV7-NEXT:    str r10, [sp, #164]
; ARMV7-NEXT:    and r0, r0, #31
; ARMV7-NEXT:    ldr r9, [sp, #40] @ 4-byte Reload
; ARMV7-NEXT:    eor lr, r0, #31
; ARMV7-NEXT:    str r9, [sp, #168]
; ARMV7-NEXT:    ldr r12, [sp, #36] @ 4-byte Reload
; ARMV7-NEXT:    str r12, [sp, #172]
; ARMV7-NEXT:    ldr r1, [r2, -r1]!
; ARMV7-NEXT:    ldmib r2, {r3, r6}
; ARMV7-NEXT:    lsr r4, r1, #1
; ARMV7-NEXT:    ldr r2, [r2, #12]
; ARMV7-NEXT:    lsl r5, r3, r0
; ARMV7-NEXT:    orr r4, r5, r4, lsr lr
; ARMV7-NEXT:    str r4, [sp, #96] @ 4-byte Spill
; ARMV7-NEXT:    lsr r4, r6, #1
; ARMV7-NEXT:    lsl r2, r2, r0
; ARMV7-NEXT:    lsrs r3, r3, #1
; ARMV7-NEXT:    orr r2, r2, r4, lsr lr
; ARMV7-NEXT:    str r2, [sp, #108] @ 4-byte Spill
; ARMV7-NEXT:    lsl r2, r6, r0
; ARMV7-NEXT:    orr r2, r2, r3, lsr lr
; ARMV7-NEXT:    adds r3, r11, #1
; ARMV7-NEXT:    str r2, [sp, #92] @ 4-byte Spill
; ARMV7-NEXT:    mov r2, r10
; ARMV7-NEXT:    lsl r10, r1, r0
; ARMV7-NEXT:    ldr r0, [sp, #104] @ 4-byte Reload
; ARMV7-NEXT:    adcs r8, r8, #0
; ARMV7-NEXT:    str r2, [sp, #4] @ 4-byte Spill
; ARMV7-NEXT:    adcs lr, r0, #0
; ARMV7-NEXT:    ldr r0, [sp, #100] @ 4-byte Reload
; ARMV7-NEXT:    adcs r0, r0, #0
; ARMV7-NEXT:    str r0, [sp, #88] @ 4-byte Spill
; ARMV7-NEXT:    adcs r0, r7, #0
; ARMV7-NEXT:    ldr r0, [sp, #44] @ 4-byte Reload
; ARMV7-NEXT:    bne .LBB0_14
; ARMV7-NEXT:  @ %bb.9: @ %udiv-preheader
; ARMV7-NEXT:    add r1, sp, #112
; ARMV7-NEXT:    str r7, [sp, #140]
; ARMV7-NEXT:    stm r1, {r0, r2, r9, r12}
; ARMV7-NEXT:    ubfx r0, r3, #5, #2
; ARMV7-NEXT:    add r12, sp, #112
; ARMV7-NEXT:    add r2, r12, r0, lsl #2
; ARMV7-NEXT:    str r7, [sp, #136]
; ARMV7-NEXT:    str r7, [sp, #132]
; ARMV7-NEXT:    str r7, [sp, #128]
; ARMV7-NEXT:    ldr r9, [r2, #12]
; ARMV7-NEXT:    ldr r1, [r2, #8]
; ARMV7-NEXT:    ldr r7, [r2, #4]
; ARMV7-NEXT:    and r2, r3, #31
; ARMV7-NEXT:    eor r4, r2, #31
; ARMV7-NEXT:    str r3, [sp, #104] @ 4-byte Spill
; ARMV7-NEXT:    lsr r3, r1, r2
; ARMV7-NEXT:    lsl r6, r9, #1
; ARMV7-NEXT:    lsl r1, r1, #1
; ARMV7-NEXT:    orr r6, r3, r6, lsl r4
; ARMV7-NEXT:    lsr r3, r7, r2
; ARMV7-NEXT:    orr r1, r3, r1, lsl r4
; ARMV7-NEXT:    str r1, [sp, #100] @ 4-byte Spill
; ARMV7-NEXT:    lsl r1, r7, #1
; ARMV7-NEXT:    ldr r0, [r12, r0, lsl #2]
; ARMV7-NEXT:    lsr r11, r9, r2
; ARMV7-NEXT:    ldr r3, [sp, #64] @ 4-byte Reload
; ARMV7-NEXT:    ldr r7, [sp, #88] @ 4-byte Reload
; ARMV7-NEXT:    ldr r5, [sp, #92] @ 4-byte Reload
; ARMV7-NEXT:    lsr r0, r0, r2
; ARMV7-NEXT:    mov r2, #0
; ARMV7-NEXT:    orr r0, r0, r1, lsl r4
; ARMV7-NEXT:    ldr r1, [sp, #76] @ 4-byte Reload
; ARMV7-NEXT:    ldr r4, [sp, #96] @ 4-byte Reload
; ARMV7-NEXT:    subs r1, r1, #1
; ARMV7-NEXT:    str r1, [sp, #60] @ 4-byte Spill
; ARMV7-NEXT:    ldr r1, [sp, #72] @ 4-byte Reload
; ARMV7-NEXT:    sbcs r1, r1, #0
; ARMV7-NEXT:    str r1, [sp, #56] @ 4-byte Spill
; ARMV7-NEXT:    ldr r1, [sp, #68] @ 4-byte Reload
; ARMV7-NEXT:    sbcs r1, r1, #0
; ARMV7-NEXT:    str r1, [sp, #52] @ 4-byte Spill
; ARMV7-NEXT:    sbc r1, r3, #0
; ARMV7-NEXT:    ldr r3, [sp, #108] @ 4-byte Reload
; ARMV7-NEXT:    str r1, [sp, #48] @ 4-byte Spill
; ARMV7-NEXT:    mov r1, #0
; ARMV7-NEXT:  .LBB0_10: @ %udiv-do-while
; ARMV7-NEXT:    @ =>This Inner Loop Header: Depth=1
; ARMV7-NEXT:    str r2, [sp, #80] @ 4-byte Spill
; ARMV7-NEXT:    lsl r2, r11, #1
; ARMV7-NEXT:    ldr r11, [sp, #100] @ 4-byte Reload
; ARMV7-NEXT:    orr r2, r2, r6, lsr #31
; ARMV7-NEXT:    str r4, [sp, #88] @ 4-byte Spill
; ARMV7-NEXT:    lsl r4, r6, #1
; ARMV7-NEXT:    str r5, [sp, #96] @ 4-byte Spill
; ARMV7-NEXT:    lsl r6, r11, #1
; ARMV7-NEXT:    ldr r5, [sp, #60] @ 4-byte Reload
; ARMV7-NEXT:    orr r6, r6, r0, lsr #31
; ARMV7-NEXT:    lsl r0, r0, #1
; ARMV7-NEXT:    orr r0, r0, r3, lsr #31
; ARMV7-NEXT:    orr r4, r4, r11, lsr #31
; ARMV7-NEXT:    subs r5, r5, r0
; ARMV7-NEXT:    str r3, [sp, #108] @ 4-byte Spill
; ARMV7-NEXT:    ldr r5, [sp, #56] @ 4-byte Reload
; ARMV7-NEXT:    ldr r3, [sp, #68] @ 4-byte Reload
; ARMV7-NEXT:    sbcs r5, r5, r6
; ARMV7-NEXT:    str r1, [sp, #92] @ 4-byte Spill
; ARMV7-NEXT:    ldr r5, [sp, #52] @ 4-byte Reload
; ARMV7-NEXT:    ldr r1, [sp, #64] @ 4-byte Reload
; ARMV7-NEXT:    sbcs r5, r5, r4
; ARMV7-NEXT:    str r10, [sp, #84] @ 4-byte Spill
; ARMV7-NEXT:    ldr r5, [sp, #48] @ 4-byte Reload
; ARMV7-NEXT:    sbc r5, r5, r2
; ARMV7-NEXT:    and r9, r3, r5, asr #31
; ARMV7-NEXT:    ldr r3, [sp, #72] @ 4-byte Reload
; ARMV7-NEXT:    and r10, r1, r5, asr #31
; ARMV7-NEXT:    and r11, r3, r5, asr #31
; ARMV7-NEXT:    ldr r3, [sp, #76] @ 4-byte Reload
; ARMV7-NEXT:    and r12, r3, r5, asr #31
; ARMV7-NEXT:    ldr r3, [sp, #104] @ 4-byte Reload
; ARMV7-NEXT:    subs r0, r0, r12
; ARMV7-NEXT:    sbcs r1, r6, r11
; ARMV7-NEXT:    str r1, [sp, #100] @ 4-byte Spill
; ARMV7-NEXT:    sbcs r6, r4, r9
; ARMV7-NEXT:    ldr r1, [sp, #84] @ 4-byte Reload
; ARMV7-NEXT:    sbc r11, r2, r10
; ARMV7-NEXT:    subs r3, r3, #1
; ARMV7-NEXT:    sbcs r8, r8, #0
; ARMV7-NEXT:    str r3, [sp, #104] @ 4-byte Spill
; ARMV7-NEXT:    sbcs lr, lr, #0
; ARMV7-NEXT:    mov r2, #1
; ARMV7-NEXT:    orr r4, r3, lr
; ARMV7-NEXT:    ldr r3, [sp, #80] @ 4-byte Reload
; ARMV7-NEXT:    sbc r7, r7, #0
; ARMV7-NEXT:    ldr r9, [sp, #88] @ 4-byte Reload
; ARMV7-NEXT:    and r2, r2, r5, asr #31
; ARMV7-NEXT:    orr r5, r8, r7
; ARMV7-NEXT:    orr r12, r3, r1, lsl #1
; ARMV7-NEXT:    ldr r3, [sp, #96] @ 4-byte Reload
; ARMV7-NEXT:    orrs r5, r4, r5
; ARMV7-NEXT:    ldr r10, [sp, #92] @ 4-byte Reload
; ARMV7-NEXT:    lsl r5, r9, #1
; ARMV7-NEXT:    orr r1, r5, r1, lsr #31
; ARMV7-NEXT:    orr r4, r10, r1
; ARMV7-NEXT:    lsl r1, r3, #1
; ARMV7-NEXT:    orr r1, r1, r9, lsr #31
; ARMV7-NEXT:    orr r5, r10, r1
; ARMV7-NEXT:    ldr r1, [sp, #108] @ 4-byte Reload
; ARMV7-NEXT:    lsl r1, r1, #1
; ARMV7-NEXT:    orr r1, r1, r3, lsr #31
; ARMV7-NEXT:    orr r3, r10, r1
; ARMV7-NEXT:    mov r10, r12
; ARMV7-NEXT:    mov r1, #0
; ARMV7-NEXT:    bne .LBB0_10
; ARMV7-NEXT:  .LBB0_11: @ %udiv-loop-exit
; ARMV7-NEXT:    lsl r1, r4, #1
; ARMV7-NEXT:    orr r6, r2, r10, lsl #1
; ARMV7-NEXT:    orr r2, r1, r10, lsr #31
; ARMV7-NEXT:    lsl r1, r5, #1
; ARMV7-NEXT:    ldr r10, [sp, #4] @ 4-byte Reload
; ARMV7-NEXT:    orr lr, r1, r4, lsr #31
; ARMV7-NEXT:    ldr r12, [sp, #76] @ 4-byte Reload
; ARMV7-NEXT:    lsl r1, r3, #1
; ARMV7-NEXT:    orr r9, r1, r5, lsr #31
; ARMV7-NEXT:  .LBB0_12: @ %udiv-end
; ARMV7-NEXT:    umull r0, r7, r12, r6
; ARMV7-NEXT:    ldr r5, [sp, #16] @ 4-byte Reload
; ARMV7-NEXT:    ldr r11, [sp, #72] @ 4-byte Reload
; ARMV7-NEXT:    mov r4, #0
; ARMV7-NEXT:    mov r1, r12
; ARMV7-NEXT:    ldr r3, [sp, #68] @ 4-byte Reload
; ARMV7-NEXT:    str r0, [sp, #108] @ 4-byte Spill
; ARMV7-NEXT:    umlal r7, r4, r11, r6
; ARMV7-NEXT:    ldr r0, [sp, #28] @ 4-byte Reload
; ARMV7-NEXT:    mov r12, #0
; ARMV7-NEXT:    str r5, [r0]
; ARMV7-NEXT:    ldr r5, [sp, #12] @ 4-byte Reload
; ARMV7-NEXT:    str r5, [r0, #4]
; ARMV7-NEXT:    ldr r5, [sp, #8] @ 4-byte Reload
; ARMV7-NEXT:    str r5, [r0, #8]
; ARMV7-NEXT:    ldr r5, [sp, #20] @ 4-byte Reload
; ARMV7-NEXT:    str r5, [r0, #12]
; ARMV7-NEXT:    umull r5, r0, r1, r2
; ARMV7-NEXT:    adds r8, r5, r7
; ARMV7-NEXT:    adcs r0, r4, r0
; ARMV7-NEXT:    ldr r4, [sp, #64] @ 4-byte Reload
; ARMV7-NEXT:    adc r7, r12, #0
; ARMV7-NEXT:    umull r12, r5, r6, r3
; ARMV7-NEXT:    mla r6, r6, r4, r5
; ARMV7-NEXT:    umlal r0, r7, r11, r2
; ARMV7-NEXT:    mla r2, r2, r3, r6
; ARMV7-NEXT:    umull r6, r5, lr, r1
; ARMV7-NEXT:    mla r3, lr, r11, r5
; ARMV7-NEXT:    mla r1, r9, r1, r3
; ARMV7-NEXT:    adds r3, r6, r12
; ARMV7-NEXT:    adc r1, r1, r2
; ARMV7-NEXT:    adds r0, r0, r3
; ARMV7-NEXT:    ldr r2, [sp, #108] @ 4-byte Reload
; ARMV7-NEXT:    adc r1, r7, r1
; ARMV7-NEXT:    ldr r3, [sp, #44] @ 4-byte Reload
; ARMV7-NEXT:    ldr r7, [sp, #40] @ 4-byte Reload
; ARMV7-NEXT:    subs r2, r3, r2
; ARMV7-NEXT:    sbcs r3, r10, r8
; ARMV7-NEXT:    sbcs r0, r7, r0
; ARMV7-NEXT:    ldr r7, [sp, #36] @ 4-byte Reload
; ARMV7-NEXT:    sbc r1, r7, r1
; ARMV7-NEXT:    ldr r7, [sp, #24] @ 4-byte Reload
; ARMV7-NEXT:    eor r2, r2, r7
; ARMV7-NEXT:    eor r3, r3, r7
; ARMV7-NEXT:    subs r2, r2, r7
; ARMV7-NEXT:    eor r0, r0, r7
; ARMV7-NEXT:    sbcs r3, r3, r7
; ARMV7-NEXT:    eor r1, r1, r7
; ARMV7-NEXT:    sbcs r0, r0, r7
; ARMV7-NEXT:    sbc r1, r1, r7
; ARMV7-NEXT:    ldr r7, [sp, #32] @ 4-byte Reload
; ARMV7-NEXT:    stm r7, {r2, r3}
; ARMV7-NEXT:    str r0, [r7, #8]
; ARMV7-NEXT:    str r1, [r7, #12]
; ARMV7-NEXT:    add sp, sp, #244
; ARMV7-NEXT:    pop {r4, r5, r6, r7, r8, r9, r10, r11, pc}
; ARMV7-NEXT:  .LBB0_13:
; ARMV7-NEXT:    ldr r0, [sp, #108] @ 4-byte Reload
; ARMV7-NEXT:    b .LBB0_5
; ARMV7-NEXT:  .LBB0_14:
; ARMV7-NEXT:    mov r2, #0
; ARMV7-NEXT:    ldr r3, [sp, #108] @ 4-byte Reload
; ARMV7-NEXT:    ldr r4, [sp, #96] @ 4-byte Reload
; ARMV7-NEXT:    ldr r5, [sp, #92] @ 4-byte Reload
; ARMV7-NEXT:    b .LBB0_11
; ARMV7-NEXT:  .LBB0_15:
; ARMV7-NEXT:    ldr r11, [sp, #48] @ 4-byte Reload
; ARMV7-NEXT:    b .LBB0_6
  %q = sdiv i128 %n, %d
  %r = srem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}

define void @udivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; ARMV6-LABEL: udivrem_i128:
; ARMV6:       @ %bb.0: @ %_udiv-special-cases_udiv-special-cases
; ARMV6-NEXT:    .save {r4, r5, r6, r7, r8, r9, r10, r11, lr}
; ARMV6-NEXT:    push {r4, r5, r6, r7, r8, r9, r10, r11, lr}
; ARMV6-NEXT:    .pad #228
; ARMV6-NEXT:    sub sp, sp, #228
; ARMV6-NEXT:    ldr r11, [sp, #264]
; ARMV6-NEXT:    mov r8, r2
; ARMV6-NEXT:    ldr r4, [sp, #268]
; ARMV6-NEXT:    clz r2, r3
; ARMV6-NEXT:    str r0, [sp, #28] @ 4-byte Spill
; ARMV6-NEXT:    clz r0, r11
; ARMV6-NEXT:    str r1, [sp, #32] @ 4-byte Spill
; ARMV6-NEXT:    clz r1, r8
; ARMV6-NEXT:    add r0, r0, #32
; ARMV6-NEXT:    cmp r4, #0
; ARMV6-NEXT:    clzne r0, r4
; ARMV6-NEXT:    add r1, r1, #32
; ARMV6-NEXT:    cmp r3, #0
; ARMV6-NEXT:    str r1, [sp, #8] @ 4-byte Spill
; ARMV6-NEXT:    str r2, [sp, #4] @ 4-byte Spill
; ARMV6-NEXT:    movne r1, r2
; ARMV6-NEXT:    orrs r2, r11, r4
; ARMV6-NEXT:    ldr lr, [sp, #280]
; ARMV6-NEXT:    ldr r2, [sp, #272]
; ARMV6-NEXT:    addeq r0, r1, #64
; ARMV6-NEXT:    ldr r7, [sp, #284]
; ARMV6-NEXT:    clz r1, lr
; ARMV6-NEXT:    ldr r12, [sp, #276]
; ARMV6-NEXT:    clz r2, r2
; ARMV6-NEXT:    add r1, r1, #32
; ARMV6-NEXT:    cmp r7, #0
; ARMV6-NEXT:    clzne r1, r7
; ARMV6-NEXT:    add r2, r2, #32
; ARMV6-NEXT:    cmp r12, #0
; ARMV6-NEXT:    mov r10, r3
; ARMV6-NEXT:    clzne r2, r12
; ARMV6-NEXT:    orrs r3, lr, r7
; ARMV6-NEXT:    addeq r1, r2, #64
; ARMV6-NEXT:    mov r2, #0
; ARMV6-NEXT:    subs r9, r1, r0
; ARMV6-NEXT:    ldr r3, [sp, #272]
; ARMV6-NEXT:    sbcs r6, r2, #0
; ARMV6-NEXT:    str r4, [sp, #48] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r5, r2, #0
; ARMV6-NEXT:    orr r3, r3, lr
; ARMV6-NEXT:    sbc r1, r2, #0
; ARMV6-NEXT:    rsbs r0, r9, #127
; ARMV6-NEXT:    rscs r0, r6, #0
; ARMV6-NEXT:    str r1, [sp, #84] @ 4-byte Spill
; ARMV6-NEXT:    rscs r0, r5, #0
; ARMV6-NEXT:    orr r2, r8, r11
; ARMV6-NEXT:    rscs r0, r1, #0
; ARMV6-NEXT:    orr r1, r10, r4
; ARMV6-NEXT:    orr r1, r2, r1
; ARMV6-NEXT:    orr r2, r12, r7
; ARMV6-NEXT:    orr r2, r3, r2
; ARMV6-NEXT:    clz r1, r1
; ARMV6-NEXT:    clz r2, r2
; ARMV6-NEXT:    mov r0, #0
; ARMV6-NEXT:    lsr r1, r1, #5
; ARMV6-NEXT:    movlo r0, #1
; ARMV6-NEXT:    lsr r2, r2, #5
; ARMV6-NEXT:    orr r1, r2, r1
; ARMV6-NEXT:    orrs r0, r1, r0
; ARMV6-NEXT:    mov r3, r10
; ARMV6-NEXT:    mov r7, r8
; ARMV6-NEXT:    str r11, [sp, #44] @ 4-byte Spill
; ARMV6-NEXT:    movne r4, #0
; ARMV6-NEXT:    movne r11, #0
; ARMV6-NEXT:    movne r3, #0
; ARMV6-NEXT:    movne r7, #0
; ARMV6-NEXT:    str r10, [sp, #40] @ 4-byte Spill
; ARMV6-NEXT:    str r8, [sp, #36] @ 4-byte Spill
; ARMV6-NEXT:    bne .LBB1_6
; ARMV6-NEXT:  @ %bb.1: @ %_udiv-special-cases_udiv-special-cases
; ARMV6-NEXT:    ldr r1, [sp, #84] @ 4-byte Reload
; ARMV6-NEXT:    eor r0, r9, #127
; ARMV6-NEXT:    orr r0, r0, r5
; ARMV6-NEXT:    str r5, [sp, #76] @ 4-byte Spill
; ARMV6-NEXT:    orr r1, r6, r1
; ARMV6-NEXT:    str r6, [sp, #80] @ 4-byte Spill
; ARMV6-NEXT:    orrs r0, r0, r1
; ARMV6-NEXT:    beq .LBB1_6
; ARMV6-NEXT:  @ %bb.2: @ %udiv-bb15
; ARMV6-NEXT:    mov r0, #0
; ARMV6-NEXT:    str r8, [sp, #208]
; ARMV6-NEXT:    str r0, [sp, #204]
; ARMV6-NEXT:    add r2, sp, #192
; ARMV6-NEXT:    str r0, [sp, #200]
; ARMV6-NEXT:    mov r11, #12
; ARMV6-NEXT:    str r0, [sp, #196]
; ARMV6-NEXT:    add r2, r2, #16
; ARMV6-NEXT:    str r0, [sp, #192]
; ARMV6-NEXT:    rsb r0, r9, #127
; ARMV6-NEXT:    str r10, [sp, #212]
; ARMV6-NEXT:    mov r6, r8
; ARMV6-NEXT:    ldr lr, [sp, #44] @ 4-byte Reload
; ARMV6-NEXT:    and r1, r11, r0, lsr #3
; ARMV6-NEXT:    str lr, [sp, #216]
; ARMV6-NEXT:    and r0, r0, #31
; ARMV6-NEXT:    ldr r12, [sp, #48] @ 4-byte Reload
; ARMV6-NEXT:    eor r5, r0, #31
; ARMV6-NEXT:    str r12, [sp, #220]
; ARMV6-NEXT:    ldr r1, [r2, -r1]!
; ARMV6-NEXT:    ldr r4, [r2, #8]
; ARMV6-NEXT:    ldr r7, [r2, #4]
; ARMV6-NEXT:    ldr r2, [r2, #12]
; ARMV6-NEXT:    lsr r3, r4, #1
; ARMV6-NEXT:    lsl r2, r2, r0
; ARMV6-NEXT:    orr r2, r2, r3, lsr r5
; ARMV6-NEXT:    str r2, [sp, #92] @ 4-byte Spill
; ARMV6-NEXT:    lsl r2, r4, r0
; ARMV6-NEXT:    lsrs r3, r7, #1
; ARMV6-NEXT:    orr r8, r2, r3, lsr r5
; ARMV6-NEXT:    lsl r2, r7, r0
; ARMV6-NEXT:    lsr r3, r1, #1
; ARMV6-NEXT:    lsl r4, r1, r0
; ARMV6-NEXT:    ldr r0, [sp, #80] @ 4-byte Reload
; ARMV6-NEXT:    orr r2, r2, r3, lsr r5
; ARMV6-NEXT:    adds r5, r9, #1
; ARMV6-NEXT:    str r2, [sp, #72] @ 4-byte Spill
; ARMV6-NEXT:    adcs r0, r0, #0
; ARMV6-NEXT:    str r0, [sp, #80] @ 4-byte Spill
; ARMV6-NEXT:    ldr r0, [sp, #76] @ 4-byte Reload
; ARMV6-NEXT:    mov r2, #0
; ARMV6-NEXT:    adcs r0, r0, #0
; ARMV6-NEXT:    str r0, [sp, #76] @ 4-byte Spill
; ARMV6-NEXT:    ldr r0, [sp, #84] @ 4-byte Reload
; ARMV6-NEXT:    adcs r7, r0, #0
; ARMV6-NEXT:    mov r0, #0
; ARMV6-NEXT:    str r0, [sp, #88] @ 4-byte Spill
; ARMV6-NEXT:    adcs r0, r2, #0
; ARMV6-NEXT:    bne .LBB1_13
; ARMV6-NEXT:  @ %bb.3: @ %udiv-preheader4
; ARMV6-NEXT:    mov r0, #0
; ARMV6-NEXT:    str r12, [sp, #172]
; ARMV6-NEXT:    str r0, [sp, #188]
; ARMV6-NEXT:    str r0, [sp, #184]
; ARMV6-NEXT:    str r0, [sp, #180]
; ARMV6-NEXT:    str r0, [sp, #176]
; ARMV6-NEXT:    add r0, sp, #160
; ARMV6-NEXT:    stm r0, {r6, r10, lr}
; ARMV6-NEXT:    and r0, r11, r5, lsr #3
; ARMV6-NEXT:    add r6, sp, #160
; ARMV6-NEXT:    add r2, r6, r0
; ARMV6-NEXT:    ldr r10, [sp, #80] @ 4-byte Reload
; ARMV6-NEXT:    ldr r11, [sp, #72] @ 4-byte Reload
; ARMV6-NEXT:    ldmib r2, {r1, r3, lr}
; ARMV6-NEXT:    lsl r2, lr, #1
; ARMV6-NEXT:    str r5, [sp, #84] @ 4-byte Spill
; ARMV6-NEXT:    and r5, r5, #31
; ARMV6-NEXT:    ldr r0, [r6, r0]
; ARMV6-NEXT:    eor r12, r5, #31
; ARMV6-NEXT:    lsr r9, r3, r5
; ARMV6-NEXT:    orr r9, r9, r2, lsl r12
; ARMV6-NEXT:    lsr r2, r1, r5
; ARMV6-NEXT:    lsl r1, r1, #1
; ARMV6-NEXT:    lsl r3, r3, #1
; ARMV6-NEXT:    lsr r0, r0, r5
; ARMV6-NEXT:    orr r1, r0, r1, lsl r12
; ARMV6-NEXT:    ldr r0, [sp, #272]
; ARMV6-NEXT:    orr r3, r2, r3, lsl r12
; ARMV6-NEXT:    ldr r6, [sp, #92] @ 4-byte Reload
; ARMV6-NEXT:    lsr lr, lr, r5
; ARMV6-NEXT:    subs r0, r0, #1
; ARMV6-NEXT:    str r0, [sp, #64] @ 4-byte Spill
; ARMV6-NEXT:    ldr r0, [sp, #276]
; ARMV6-NEXT:    mov r5, #0
; ARMV6-NEXT:    ldr r12, [sp, #76] @ 4-byte Reload
; ARMV6-NEXT:    sbcs r0, r0, #0
; ARMV6-NEXT:    str r0, [sp, #60] @ 4-byte Spill
; ARMV6-NEXT:    ldr r0, [sp, #280]
; ARMV6-NEXT:    sbcs r0, r0, #0
; ARMV6-NEXT:    str r0, [sp, #56] @ 4-byte Spill
; ARMV6-NEXT:    ldr r0, [sp, #284]
; ARMV6-NEXT:    sbc r0, r0, #0
; ARMV6-NEXT:    str r0, [sp, #52] @ 4-byte Spill
; ARMV6-NEXT:  .LBB1_4: @ %udiv-do-while3
; ARMV6-NEXT:    @ =>This Inner Loop Header: Depth=1
; ARMV6-NEXT:    ldr r2, [sp, #88] @ 4-byte Reload
; ARMV6-NEXT:    lsl r0, lr, #1
; ARMV6-NEXT:    str r2, [sp, #68] @ 4-byte Spill
; ARMV6-NEXT:    lsl r2, r9, #1
; ARMV6-NEXT:    orr r2, r2, r3, lsr #31
; ARMV6-NEXT:    lsl r3, r3, #1
; ARMV6-NEXT:    orr r3, r3, r1, lsr #31
; ARMV6-NEXT:    lsl r1, r1, #1
; ARMV6-NEXT:    str r6, [sp, #92] @ 4-byte Spill
; ARMV6-NEXT:    orr r1, r1, r6, lsr #31
; ARMV6-NEXT:    ldr r6, [sp, #64] @ 4-byte Reload
; ARMV6-NEXT:    orr r0, r0, r9, lsr #31
; ARMV6-NEXT:    str r4, [sp, #72] @ 4-byte Spill
; ARMV6-NEXT:    subs r4, r6, r1
; ARMV6-NEXT:    ldr r6, [sp, #60] @ 4-byte Reload
; ARMV6-NEXT:    str r11, [sp, #76] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r4, r6, r3
; ARMV6-NEXT:    ldr r6, [sp, #56] @ 4-byte Reload
; ARMV6-NEXT:    str r8, [sp, #80] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r4, r6, r2
; ARMV6-NEXT:    ldr r6, [sp, #52] @ 4-byte Reload
; ARMV6-NEXT:    sbc r4, r6, r0
; ARMV6-NEXT:    ldr r6, [sp, #284]
; ARMV6-NEXT:    and r11, r6, r4, asr #31
; ARMV6-NEXT:    ldr r6, [sp, #280]
; ARMV6-NEXT:    and lr, r6, r4, asr #31
; ARMV6-NEXT:    ldr r6, [sp, #276]
; ARMV6-NEXT:    and r8, r6, r4, asr #31
; ARMV6-NEXT:    ldr r6, [sp, #272]
; ARMV6-NEXT:    and r9, r6, r4, asr #31
; ARMV6-NEXT:    ldr r6, [sp, #72] @ 4-byte Reload
; ARMV6-NEXT:    subs r1, r1, r9
; ARMV6-NEXT:    sbcs r3, r3, r8
; ARMV6-NEXT:    sbcs r9, r2, lr
; ARMV6-NEXT:    sbc lr, r0, r11
; ARMV6-NEXT:    mov r0, #1
; ARMV6-NEXT:    and r0, r0, r4, asr #31
; ARMV6-NEXT:    str r0, [sp, #88] @ 4-byte Spill
; ARMV6-NEXT:    ldr r0, [sp, #84] @ 4-byte Reload
; ARMV6-NEXT:    subs r0, r0, #1
; ARMV6-NEXT:    str r0, [sp, #84] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r10, r10, #0
; ARMV6-NEXT:    sbcs r12, r12, #0
; ARMV6-NEXT:    sbc r7, r7, #0
; ARMV6-NEXT:    orr r0, r0, r12
; ARMV6-NEXT:    orr r4, r10, r7
; ARMV6-NEXT:    orrs r0, r0, r4
; ARMV6-NEXT:    ldr r4, [sp, #76] @ 4-byte Reload
; ARMV6-NEXT:    ldr r0, [sp, #68] @ 4-byte Reload
; ARMV6-NEXT:    orr r2, r0, r6, lsl #1
; ARMV6-NEXT:    lsl r0, r4, #1
; ARMV6-NEXT:    orr r0, r0, r6, lsr #31
; ARMV6-NEXT:    ldr r6, [sp, #80] @ 4-byte Reload
; ARMV6-NEXT:    orr r11, r5, r0
; ARMV6-NEXT:    lsl r0, r6, #1
; ARMV6-NEXT:    orr r0, r0, r4, lsr #31
; ARMV6-NEXT:    mov r4, r2
; ARMV6-NEXT:    orr r8, r5, r0
; ARMV6-NEXT:    ldr r0, [sp, #92] @ 4-byte Reload
; ARMV6-NEXT:    lsl r0, r0, #1
; ARMV6-NEXT:    orr r0, r0, r6, lsr #31
; ARMV6-NEXT:    orr r6, r5, r0
; ARMV6-NEXT:    mov r5, #0
; ARMV6-NEXT:    bne .LBB1_4
; ARMV6-NEXT:  .LBB1_5: @ %udiv-loop-exit2
; ARMV6-NEXT:    ldr r0, [sp, #88] @ 4-byte Reload
; ARMV6-NEXT:    lsl r3, r11, #1
; ARMV6-NEXT:    lsl r2, r8, #1
; ARMV6-NEXT:    orr r3, r3, r4, lsr #31
; ARMV6-NEXT:    orr r7, r0, r4, lsl #1
; ARMV6-NEXT:    lsl r0, r6, #1
; ARMV6-NEXT:    orr r4, r0, r8, lsr #31
; ARMV6-NEXT:    ldr r10, [sp, #40] @ 4-byte Reload
; ARMV6-NEXT:    ldr r8, [sp, #36] @ 4-byte Reload
; ARMV6-NEXT:    orr r11, r2, r11, lsr #31
; ARMV6-NEXT:  .LBB1_6: @ %udiv-end1
; ARMV6-NEXT:    ldr r6, [sp, #44] @ 4-byte Reload
; ARMV6-NEXT:    mov lr, #0
; ARMV6-NEXT:    str r7, [sp, #12] @ 4-byte Spill
; ARMV6-NEXT:    ldr r7, [sp, #48] @ 4-byte Reload
; ARMV6-NEXT:    clz r0, r6
; ARMV6-NEXT:    ldmib sp, {r1, r2} @ 8-byte Folded Reload
; ARMV6-NEXT:    add r0, r0, #32
; ARMV6-NEXT:    cmp r7, #0
; ARMV6-NEXT:    clzne r0, r7
; ARMV6-NEXT:    cmp r10, #0
; ARMV6-NEXT:    movne r2, r1
; ARMV6-NEXT:    orrs r1, r6, r7
; ARMV6-NEXT:    ldr r5, [sp, #280]
; ARMV6-NEXT:    addeq r0, r2, #64
; ARMV6-NEXT:    ldr r2, [sp, #272]
; ARMV6-NEXT:    str r4, [sp, #24] @ 4-byte Spill
; ARMV6-NEXT:    clz r1, r5
; ARMV6-NEXT:    ldr r4, [sp, #284]
; ARMV6-NEXT:    clz r2, r2
; ARMV6-NEXT:    ldr r12, [sp, #276]
; ARMV6-NEXT:    add r1, r1, #32
; ARMV6-NEXT:    cmp r4, #0
; ARMV6-NEXT:    add r2, r2, #32
; ARMV6-NEXT:    clzne r1, r4
; ARMV6-NEXT:    cmp r12, #0
; ARMV6-NEXT:    str r3, [sp, #16] @ 4-byte Spill
; ARMV6-NEXT:    clzne r2, r12
; ARMV6-NEXT:    orrs r3, r5, r4
; ARMV6-NEXT:    str r11, [sp, #20] @ 4-byte Spill
; ARMV6-NEXT:    addeq r1, r2, #64
; ARMV6-NEXT:    subs r9, r1, r0
; ARMV6-NEXT:    sbcs r2, lr, #0
; ARMV6-NEXT:    sbcs r1, lr, #0
; ARMV6-NEXT:    sbc r3, lr, #0
; ARMV6-NEXT:    rsbs r0, r9, #127
; ARMV6-NEXT:    rscs r0, r2, #0
; ARMV6-NEXT:    mov r11, r1
; ARMV6-NEXT:    rscs r0, r1, #0
; ARMV6-NEXT:    orr r1, r10, r7
; ARMV6-NEXT:    rscs r0, r3, #0
; ARMV6-NEXT:    str r3, [sp, #84] @ 4-byte Spill
; ARMV6-NEXT:    orr r0, r8, r6
; ARMV6-NEXT:    orr r3, r12, r4
; ARMV6-NEXT:    orr r0, r0, r1
; ARMV6-NEXT:    ldr r1, [sp, #272]
; ARMV6-NEXT:    clz r0, r0
; ARMV6-NEXT:    movlo lr, #1
; ARMV6-NEXT:    orr r1, r1, r5
; ARMV6-NEXT:    mov r4, r8
; ARMV6-NEXT:    orr r1, r1, r3
; ARMV6-NEXT:    lsr r0, r0, #5
; ARMV6-NEXT:    clz r1, r1
; ARMV6-NEXT:    mov r3, r10
; ARMV6-NEXT:    lsr r1, r1, #5
; ARMV6-NEXT:    orr r0, r1, r0
; ARMV6-NEXT:    orrs r0, r0, lr
; ARMV6-NEXT:    movne r7, #0
; ARMV6-NEXT:    movne r6, #0
; ARMV6-NEXT:    movne r3, #0
; ARMV6-NEXT:    movne r4, #0
; ARMV6-NEXT:    bne .LBB1_12
; ARMV6-NEXT:  @ %bb.7: @ %udiv-end1
; ARMV6-NEXT:    ldr r1, [sp, #84] @ 4-byte Reload
; ARMV6-NEXT:    eor r0, r9, #127
; ARMV6-NEXT:    orr r0, r0, r11
; ARMV6-NEXT:    orr r1, r2, r1
; ARMV6-NEXT:    orrs r0, r0, r1
; ARMV6-NEXT:    beq .LBB1_12
; ARMV6-NEXT:  @ %bb.8: @ %udiv-bb1
; ARMV6-NEXT:    rsb r1, r9, #127
; ARMV6-NEXT:    add r4, sp, #128
; ARMV6-NEXT:    ldr r0, [sp, #264]
; ARMV6-NEXT:    mov lr, r11
; ARMV6-NEXT:    mov r12, r2
; ARMV6-NEXT:    mov r2, #0
; ARMV6-NEXT:    str r0, [sp, #152]
; ARMV6-NEXT:    mov r0, #12
; ARMV6-NEXT:    ldr r11, [sp, #268]
; ARMV6-NEXT:    and r3, r0, r1, lsr #3
; ARMV6-NEXT:    add r4, r4, #16
; ARMV6-NEXT:    str r8, [sp, #144]
; ARMV6-NEXT:    str r2, [sp, #140]
; ARMV6-NEXT:    and r0, r1, #31
; ARMV6-NEXT:    str r2, [sp, #136]
; ARMV6-NEXT:    eor r6, r0, #31
; ARMV6-NEXT:    str r2, [sp, #132]
; ARMV6-NEXT:    str r2, [sp, #128]
; ARMV6-NEXT:    str r10, [sp, #148]
; ARMV6-NEXT:    str r11, [sp, #156]
; ARMV6-NEXT:    ldr r3, [r4, -r3]!
; ARMV6-NEXT:    ldr r7, [r4, #4]
; ARMV6-NEXT:    ldr r5, [r4, #8]
; ARMV6-NEXT:    ldr r4, [r4, #12]
; ARMV6-NEXT:    lsl r1, r4, r0
; ARMV6-NEXT:    lsr r4, r5, #1
; ARMV6-NEXT:    orr r1, r1, r4, lsr r6
; ARMV6-NEXT:    str r1, [sp, #92] @ 4-byte Spill
; ARMV6-NEXT:    lsl r1, r5, r0
; ARMV6-NEXT:    lsrs r4, r7, #1
; ARMV6-NEXT:    orr r1, r1, r4, lsr r6
; ARMV6-NEXT:    str r1, [sp, #88] @ 4-byte Spill
; ARMV6-NEXT:    lsl r1, r7, r0
; ARMV6-NEXT:    lsr r4, r3, #1
; ARMV6-NEXT:    orr r1, r1, r4, lsr r6
; ARMV6-NEXT:    adds r7, r9, #1
; ARMV6-NEXT:    adcs r6, r12, #0
; ARMV6-NEXT:    str r1, [sp, #80] @ 4-byte Spill
; ARMV6-NEXT:    lsl r1, r3, r0
; ARMV6-NEXT:    ldr r0, [sp, #84] @ 4-byte Reload
; ARMV6-NEXT:    adcs r9, lr, #0
; ARMV6-NEXT:    adcs r0, r0, #0
; ARMV6-NEXT:    str r0, [sp, #76] @ 4-byte Spill
; ARMV6-NEXT:    adcs r0, r2, #0
; ARMV6-NEXT:    bne .LBB1_14
; ARMV6-NEXT:  @ %bb.9: @ %udiv-preheader
; ARMV6-NEXT:    ldr r0, [sp, #264]
; ARMV6-NEXT:    add r5, sp, #96
; ARMV6-NEXT:    str r0, [sp, #104]
; ARMV6-NEXT:    mov r0, #12
; ARMV6-NEXT:    str r2, [sp, #124]
; ARMV6-NEXT:    str r2, [sp, #120]
; ARMV6-NEXT:    str r2, [sp, #116]
; ARMV6-NEXT:    str r2, [sp, #112]
; ARMV6-NEXT:    and r2, r0, r7, lsr #3
; ARMV6-NEXT:    add r0, r5, r2
; ARMV6-NEXT:    str r11, [sp, #108]
; ARMV6-NEXT:    str r8, [sp, #96]
; ARMV6-NEXT:    and r11, r7, #31
; ARMV6-NEXT:    str r10, [sp, #100]
; ARMV6-NEXT:    eor r12, r11, #31
; ARMV6-NEXT:    ldr r3, [r0, #8]
; ARMV6-NEXT:    ldr r8, [r0, #12]
; ARMV6-NEXT:    ldr r4, [r0, #4]
; ARMV6-NEXT:    str r7, [sp, #84] @ 4-byte Spill
; ARMV6-NEXT:    lsr r0, r3, r11
; ARMV6-NEXT:    lsl r7, r8, #1
; ARMV6-NEXT:    lsl r3, r3, #1
; ARMV6-NEXT:    orr lr, r0, r7, lsl r12
; ARMV6-NEXT:    lsr r0, r4, r11
; ARMV6-NEXT:    orr r10, r0, r3, lsl r12
; ARMV6-NEXT:    ldr r3, [r5, r2]
; ARMV6-NEXT:    lsl r4, r4, #1
; ARMV6-NEXT:    lsr r8, r8, r11
; ARMV6-NEXT:    ldr r5, [sp, #92] @ 4-byte Reload
; ARMV6-NEXT:    lsr r3, r3, r11
; ARMV6-NEXT:    orr r4, r3, r4, lsl r12
; ARMV6-NEXT:    ldr r3, [sp, #272]
; ARMV6-NEXT:    ldr r12, [sp, #76] @ 4-byte Reload
; ARMV6-NEXT:    subs r0, r3, #1
; ARMV6-NEXT:    ldr r3, [sp, #276]
; ARMV6-NEXT:    str r0, [sp, #64] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r0, r3, #0
; ARMV6-NEXT:    ldr r3, [sp, #280]
; ARMV6-NEXT:    str r0, [sp, #60] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r0, r3, #0
; ARMV6-NEXT:    ldr r3, [sp, #284]
; ARMV6-NEXT:    ldr r11, [sp, #80] @ 4-byte Reload
; ARMV6-NEXT:    str r0, [sp, #56] @ 4-byte Spill
; ARMV6-NEXT:    sbc r0, r3, #0
; ARMV6-NEXT:    str r0, [sp, #52] @ 4-byte Spill
; ARMV6-NEXT:    mov r3, #0
; ARMV6-NEXT:    mov r0, #0
; ARMV6-NEXT:  .LBB1_10: @ %udiv-do-while
; ARMV6-NEXT:    @ =>This Inner Loop Header: Depth=1
; ARMV6-NEXT:    add r7, sp, #72
; ARMV6-NEXT:    ldr r2, [sp, #88] @ 4-byte Reload
; ARMV6-NEXT:    stm r7, {r0, r1, r2} @ 12-byte Folded Spill
; ARMV6-NEXT:    lsl r0, r10, #1
; ARMV6-NEXT:    orr r0, r0, r4, lsr #31
; ARMV6-NEXT:    lsl r4, r4, #1
; ARMV6-NEXT:    ldr r1, [sp, #64] @ 4-byte Reload
; ARMV6-NEXT:    orr r4, r4, r5, lsr #31
; ARMV6-NEXT:    str r5, [sp, #92] @ 4-byte Spill
; ARMV6-NEXT:    subs r5, r1, r4
; ARMV6-NEXT:    ldr r1, [sp, #60] @ 4-byte Reload
; ARMV6-NEXT:    lsl r7, lr, #1
; ARMV6-NEXT:    mov r2, r3
; ARMV6-NEXT:    sbcs r5, r1, r0
; ARMV6-NEXT:    ldr r1, [sp, #56] @ 4-byte Reload
; ARMV6-NEXT:    orr r7, r7, r10, lsr #31
; ARMV6-NEXT:    lsl r3, r8, #1
; ARMV6-NEXT:    sbcs r5, r1, r7
; ARMV6-NEXT:    ldr r1, [sp, #52] @ 4-byte Reload
; ARMV6-NEXT:    orr r3, r3, lr, lsr #31
; ARMV6-NEXT:    str r11, [sp, #88] @ 4-byte Spill
; ARMV6-NEXT:    sbc r5, r1, r3
; ARMV6-NEXT:    ldr r1, [sp, #284]
; ARMV6-NEXT:    and r11, r1, r5, asr #31
; ARMV6-NEXT:    ldr r1, [sp, #280]
; ARMV6-NEXT:    and lr, r1, r5, asr #31
; ARMV6-NEXT:    ldr r1, [sp, #276]
; ARMV6-NEXT:    and r10, r1, r5, asr #31
; ARMV6-NEXT:    ldr r1, [sp, #272]
; ARMV6-NEXT:    and r8, r1, r5, asr #31
; ARMV6-NEXT:    subs r1, r4, r8
; ARMV6-NEXT:    str r1, [sp, #68] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r4, r0, r10
; ARMV6-NEXT:    mov r0, #1
; ARMV6-NEXT:    sbcs r10, r7, lr
; ARMV6-NEXT:    and r0, r0, r5, asr #31
; ARMV6-NEXT:    sbc r8, r3, r11
; ARMV6-NEXT:    ldr r3, [sp, #84] @ 4-byte Reload
; ARMV6-NEXT:    ldr r1, [sp, #76] @ 4-byte Reload
; ARMV6-NEXT:    subs r3, r3, #1
; ARMV6-NEXT:    str r3, [sp, #84] @ 4-byte Spill
; ARMV6-NEXT:    sbcs r6, r6, #0
; ARMV6-NEXT:    ldr lr, [sp, #88] @ 4-byte Reload
; ARMV6-NEXT:    sbcs r9, r9, #0
; ARMV6-NEXT:    sbc r12, r12, #0
; ARMV6-NEXT:    orr r3, r3, r9
; ARMV6-NEXT:    orr r5, r6, r12
; ARMV6-NEXT:    orrs r3, r3, r5
; ARMV6-NEXT:    ldr r5, [sp, #80] @ 4-byte Reload
; ARMV6-NEXT:    ldr r3, [sp, #72] @ 4-byte Reload
; ARMV6-NEXT:    orr r7, r3, r1, lsl #1
; ARMV6-NEXT:    lsl r3, lr, #1
; ARMV6-NEXT:    orr r1, r3, r1, lsr #31
; ARMV6-NEXT:    lsl r3, r5, #1
; ARMV6-NEXT:    orr r3, r3, lr, lsr #31
; ARMV6-NEXT:    orr r11, r2, r1
; ARMV6-NEXT:    orr r1, r2, r3
; ARMV6-NEXT:    str r1, [sp, #88] @ 4-byte Spill
; ARMV6-NEXT:    ldr r1, [sp, #92] @ 4-byte Reload
; ARMV6-NEXT:    mov lr, r10
; ARMV6-NEXT:    mov r10, r4
; ARMV6-NEXT:    ldr r4, [sp, #68] @ 4-byte Reload
; ARMV6-NEXT:    lsl r3, r1, #1
; ARMV6-NEXT:    mov r1, r7
; ARMV6-NEXT:    orr r3, r3, r5, lsr #31
; ARMV6-NEXT:    orr r5, r2, r3
; ARMV6-NEXT:    mov r3, #0
; ARMV6-NEXT:    bne .LBB1_10
; ARMV6-NEXT:  .LBB1_11: @ %udiv-loop-exit
; ARMV6-NEXT:    orr r4, r0, r1, lsl #1
; ARMV6-NEXT:    lsl r0, r11, #1
; ARMV6-NEXT:    orr r3, r0, r1, lsr #31
; ARMV6-NEXT:    ldr r1, [sp, #88] @ 4-byte Reload
; ARMV6-NEXT:    ldr r10, [sp, #40] @ 4-byte Reload
; ARMV6-NEXT:    ldr r8, [sp, #36] @ 4-byte Reload
; ARMV6-NEXT:    lsl r0, r1, #1
; ARMV6-NEXT:    orr r6, r0, r11, lsr #31
; ARMV6-NEXT:    lsl r0, r5, #1
; ARMV6-NEXT:    orr r7, r0, r1, lsr #31
; ARMV6-NEXT:  .LBB1_12: @ %udiv-end
; ARMV6-NEXT:    ldr r0, [sp, #28] @ 4-byte Reload
; ARMV6-NEXT:    mov lr, r7
; ARMV6-NEXT:    ldr r1, [sp, #12] @ 4-byte Reload
; ARMV6-NEXT:    mov r7, #0
; ARMV6-NEXT:    ldr r11, [sp, #272]
; ARMV6-NEXT:    mov r12, r6
; ARMV6-NEXT:    str r1, [r0]
; ARMV6-NEXT:    mov r2, #0
; ARMV6-NEXT:    ldr r1, [sp, #16] @ 4-byte Reload
; ARMV6-NEXT:    str r1, [r0, #4]
; ARMV6-NEXT:    umull r6, r5, r11, r3
; ARMV6-NEXT:    ldr r1, [sp, #20] @ 4-byte Reload
; ARMV6-NEXT:    str r1, [r0, #8]
; ARMV6-NEXT:    ldr r1, [sp, #24] @ 4-byte Reload
; ARMV6-NEXT:    str r1, [r0, #12]
; ARMV6-NEXT:    umull r0, r1, r11, r4
; ARMV6-NEXT:    ldr r9, [sp, #276]
; ARMV6-NEXT:    umlal r1, r7, r9, r4
; ARMV6-NEXT:    str r0, [sp, #92] @ 4-byte Spill
; ARMV6-NEXT:    adds r0, r6, r1
; ARMV6-NEXT:    ldr r1, [sp, #280]
; ARMV6-NEXT:    adcs r7, r7, r5
; ARMV6-NEXT:    str r0, [sp, #88] @ 4-byte Spill
; ARMV6-NEXT:    ldr r0, [sp, #284]
; ARMV6-NEXT:    adc r2, r2, #0
; ARMV6-NEXT:    umull r6, r5, r4, r1
; ARMV6-NEXT:    mla r5, r4, r0, r5
; ARMV6-NEXT:    ldr r0, [sp, #92] @ 4-byte Reload
; ARMV6-NEXT:    umlal r7, r2, r9, r3
; ARMV6-NEXT:    mla r3, r3, r1, r5
; ARMV6-NEXT:    ldr r1, [sp, #88] @ 4-byte Reload
; ARMV6-NEXT:    umull r5, r4, r12, r11
; ARMV6-NEXT:    mla r4, r12, r9, r4
; ARMV6-NEXT:    adds r6, r5, r6
; ARMV6-NEXT:    mla r4, lr, r11, r4
; ARMV6-NEXT:    adc r3, r4, r3
; ARMV6-NEXT:    adds r7, r7, r6
; ARMV6-NEXT:    adc r2, r2, r3
; ARMV6-NEXT:    subs r0, r8, r0
; ARMV6-NEXT:    ldr r3, [sp, #264]
; ARMV6-NEXT:    sbcs r1, r10, r1
; ARMV6-NEXT:    sbcs r3, r3, r7
; ARMV6-NEXT:    ldr r7, [sp, #268]
; ARMV6-NEXT:    sbc r2, r7, r2
; ARMV6-NEXT:    ldr r7, [sp, #32] @ 4-byte Reload
; ARMV6-NEXT:    stm r7, {r0, r1, r3}
; ARMV6-NEXT:    str r2, [r7, #12]
; ARMV6-NEXT:    add sp, sp, #228
; ARMV6-NEXT:    pop {r4, r5, r6, r7, r8, r9, r10, r11, pc}
; ARMV6-NEXT:  .LBB1_13:
; ARMV6-NEXT:    ldr r6, [sp, #92] @ 4-byte Reload
; ARMV6-NEXT:    ldr r11, [sp, #72] @ 4-byte Reload
; ARMV6-NEXT:    b .LBB1_5
; ARMV6-NEXT:  .LBB1_14:
; ARMV6-NEXT:    ldr r5, [sp, #92] @ 4-byte Reload
; ARMV6-NEXT:    mov r0, #0
; ARMV6-NEXT:    ldr r11, [sp, #80] @ 4-byte Reload
; ARMV6-NEXT:    b .LBB1_11
;
; ARMV7-LABEL: udivrem_i128:
; ARMV7:       @ %bb.0: @ %_udiv-special-cases_udiv-special-cases
; ARMV7-NEXT:    .save {r4, r5, r6, r7, r8, r9, r10, r11, lr}
; ARMV7-NEXT:    push {r4, r5, r6, r7, r8, r9, r10, r11, lr}
; ARMV7-NEXT:    .pad #228
; ARMV7-NEXT:    sub sp, sp, #228
; ARMV7-NEXT:    ldr r4, [sp, #264]
; ARMV7-NEXT:    mov r11, r3
; ARMV7-NEXT:    ldr r5, [sp, #268]
; ARMV7-NEXT:    clz r3, r3
; ARMV7-NEXT:    str r0, [sp, #24] @ 4-byte Spill
; ARMV7-NEXT:    clz r0, r4
; ARMV7-NEXT:    str r1, [sp, #28] @ 4-byte Spill
; ARMV7-NEXT:    clz r1, r2
; ARMV7-NEXT:    add r0, r0, #32
; ARMV7-NEXT:    cmp r5, #0
; ARMV7-NEXT:    clzne r0, r5
; ARMV7-NEXT:    add r1, r1, #32
; ARMV7-NEXT:    ldr r10, [sp, #280]
; ARMV7-NEXT:    cmp r11, #0
; ARMV7-NEXT:    str r1, [sp, #8] @ 4-byte Spill
; ARMV7-NEXT:    movne r1, r3
; ARMV7-NEXT:    str r3, [sp, #4] @ 4-byte Spill
; ARMV7-NEXT:    orrs r3, r4, r5
; ARMV7-NEXT:    ldr r12, [sp, #272]
; ARMV7-NEXT:    addeq r0, r1, #64
; ARMV7-NEXT:    ldr r6, [sp, #284]
; ARMV7-NEXT:    clz r1, r10
; ARMV7-NEXT:    ldr lr, [sp, #276]
; ARMV7-NEXT:    clz r3, r12
; ARMV7-NEXT:    add r1, r1, #32
; ARMV7-NEXT:    cmp r6, #0
; ARMV7-NEXT:    clzne r1, r6
; ARMV7-NEXT:    add r7, r3, #32
; ARMV7-NEXT:    cmp lr, #0
; ARMV7-NEXT:    str r4, [sp, #44] @ 4-byte Spill
; ARMV7-NEXT:    clzne r7, lr
; ARMV7-NEXT:    orrs r3, r10, r6
; ARMV7-NEXT:    addeq r1, r7, #64
; ARMV7-NEXT:    orr r7, r2, r4
; ARMV7-NEXT:    subs r9, r1, r0
; ARMV7-NEXT:    mov r0, #0
; ARMV7-NEXT:    sbcs r3, r0, #0
; ARMV7-NEXT:    str r3, [sp, #80] @ 4-byte Spill
; ARMV7-NEXT:    sbcs r8, r0, #0
; ARMV7-NEXT:    str r5, [sp, #40] @ 4-byte Spill
; ARMV7-NEXT:    sbc r1, r0, #0
; ARMV7-NEXT:    rsbs r0, r9, #127
; ARMV7-NEXT:    rscs r0, r3, #0
; ARMV7-NEXT:    str r1, [sp, #84] @ 4-byte Spill
; ARMV7-NEXT:    rscs r0, r8, #0
; ARMV7-NEXT:    orr r3, r12, r10
; ARMV7-NEXT:    rscs r0, r1, #0
; ARMV7-NEXT:    orr r1, lr, r6
; ARMV7-NEXT:    orr r1, r3, r1
; ARMV7-NEXT:    orr r3, r11, r5
; ARMV7-NEXT:    orr r3, r7, r3
; ARMV7-NEXT:    clz r1, r1
; ARMV7-NEXT:    clz r3, r3
; ARMV7-NEXT:    mov r0, #0
; ARMV7-NEXT:    lsr r1, r1, #5
; ARMV7-NEXT:    movwlo r0, #1
; ARMV7-NEXT:    lsr r3, r3, #5
; ARMV7-NEXT:    orr r1, r1, r3
; ARMV7-NEXT:    orrs r0, r1, r0
; ARMV7-NEXT:    mov r6, r11
; ARMV7-NEXT:    mov r7, r2
; ARMV7-NEXT:    movwne r5, #0
; ARMV7-NEXT:    movwne r4, #0
; ARMV7-NEXT:    movwne r6, #0
; ARMV7-NEXT:    movwne r7, #0
; ARMV7-NEXT:    str r2, [sp, #36] @ 4-byte Spill
; ARMV7-NEXT:    str r11, [sp, #32] @ 4-byte Spill
; ARMV7-NEXT:    bne .LBB1_6
; ARMV7-NEXT:  @ %bb.1: @ %_udiv-special-cases_udiv-special-cases
; ARMV7-NEXT:    ldr r1, [sp, #84] @ 4-byte Reload
; ARMV7-NEXT:    eor r0, r9, #127
; ARMV7-NEXT:    ldr r2, [sp, #80] @ 4-byte Reload
; ARMV7-NEXT:    orr r0, r0, r8
; ARMV7-NEXT:    str r8, [sp, #76] @ 4-byte Spill
; ARMV7-NEXT:    orr r2, r2, r1
; ARMV7-NEXT:    orrs r0, r0, r2
; ARMV7-NEXT:    beq .LBB1_6
; ARMV7-NEXT:  @ %bb.2: @ %udiv-bb15
; ARMV7-NEXT:    ldr r8, [sp, #36] @ 4-byte Reload
; ARMV7-NEXT:    mov r0, #0
; ARMV7-NEXT:    str r8, [sp, #208]
; ARMV7-NEXT:    add r3, sp, #192
; ARMV7-NEXT:    str r0, [sp, #204]
; ARMV7-NEXT:    mov r2, #12
; ARMV7-NEXT:    str r0, [sp, #200]
; ARMV7-NEXT:    add r3, r3, #16
; ARMV7-NEXT:    str r0, [sp, #196]
; ARMV7-NEXT:    str r0, [sp, #192]
; ARMV7-NEXT:    rsb r0, r9, #127
; ARMV7-NEXT:    str r11, [sp, #212]
; ARMV7-NEXT:    ldr r12, [sp, #44] @ 4-byte Reload
; ARMV7-NEXT:    and r2, r2, r0, lsr #3
; ARMV7-NEXT:    str r12, [sp, #216]
; ARMV7-NEXT:    and r0, r0, #31
; ARMV7-NEXT:    ldr r10, [sp, #40] @ 4-byte Reload
; ARMV7-NEXT:    eor r1, r0, #31
; ARMV7-NEXT:    str r10, [sp, #220]
; ARMV7-NEXT:    ldr r7, [r3, -r2]!
; ARMV7-NEXT:    ldmib r3, {r2, r4}
; ARMV7-NEXT:    lsr r6, r7, #1
; ARMV7-NEXT:    ldr r3, [r3, #12]
; ARMV7-NEXT:    lsl r5, r2, r0
; ARMV7-NEXT:    lsrs r2, r2, #1
; ARMV7-NEXT:    orr r5, r5, r6, lsr r1
; ARMV7-NEXT:    str r5, [sp, #72] @ 4-byte Spill
; ARMV7-NEXT:    lsl r3, r3, r0
; ARMV7-NEXT:    lsr r5, r4, #1
; ARMV7-NEXT:    orr r3, r3, r5, lsr r1
; ARMV7-NEXT:    str r3, [sp, #92] @ 4-byte Spill
; ARMV7-NEXT:    lsl r3, r4, r0
; ARMV7-NEXT:    lsl r0, r7, r0
; ARMV7-NEXT:    str r0, [sp, #68] @ 4-byte Spill
; ARMV7-NEXT:    adds r5, r9, #1
; ARMV7-NEXT:    ldr r0, [sp, #80] @ 4-byte Reload
; ARMV7-NEXT:    orr r1, r3, r2, lsr r1
; ARMV7-NEXT:    str r1, [sp, #64] @ 4-byte Spill
; ARMV7-NEXT:    mov r3, #0
; ARMV7-NEXT:    adcs r0, r0, #0
; ARMV7-NEXT:    str r0, [sp, #20] @ 4-byte Spill
; ARMV7-NEXT:    ldr r0, [sp, #76] @ 4-byte Reload
; ARMV7-NEXT:    adcs r6, r0, #0
; ARMV7-NEXT:    ldr r0, [sp, #84] @ 4-byte Reload
; ARMV7-NEXT:    adcs r0, r0, #0
; ARMV7-NEXT:    str r0, [sp, #76] @ 4-byte Spill
; ARMV7-NEXT:    mov r0, #0
; ARMV7-NEXT:    str r0, [sp, #88] @ 4-byte Spill
; ARMV7-NEXT:    adcs r0, r3, #0
; ARMV7-NEXT:    bne .LBB1_13
; ARMV7-NEXT:  @ %bb.3: @ %udiv-preheader4
; ARMV7-NEXT:    mov r0, #0
; ARMV7-NEXT:    ubfx r1, r5, #5, #2
; ARMV7-NEXT:    str r0, [sp, #188]
; ARMV7-NEXT:    and r9, r5, #31
; ARMV7-NEXT:    str r0, [sp, #184]
; ARMV7-NEXT:    eor r3, r9, #31
; ARMV7-NEXT:    str r0, [sp, #180]
; ARMV7-NEXT:    str r0, [sp, #176]
; ARMV7-NEXT:    add r0, sp, #160
; ARMV7-NEXT:    stm r0, {r8, r11, r12}
; ARMV7-NEXT:    add r12, sp, #160
; ARMV7-NEXT:    add r0, r12, r1, lsl #2
; ARMV7-NEXT:    str r10, [sp, #172]
; ARMV7-NEXT:    ldmib r0, {r4, r7, r8}
; ARMV7-NEXT:    lsr r10, r7, r9
; ARMV7-NEXT:    lsl r0, r8, #1
; ARMV7-NEXT:    lsl r7, r7, #1
; ARMV7-NEXT:    str r5, [sp, #84] @ 4-byte Spill
; ARMV7-NEXT:    orr lr, r10, r0, lsl r3
; ARMV7-NEXT:    lsr r10, r4, r9
; ARMV7-NEXT:    orr r0, r10, r7, lsl r3
; ARMV7-NEXT:    str r0, [sp, #80] @ 4-byte Spill
; ARMV7-NEXT:    ldr r1, [r12, r1, lsl #2]
; ARMV7-NEXT:    lsl r7, r4, #1
; ARMV7-NEXT:    ldr r12, [sp, #276]
; ARMV7-NEXT:    lsr r11, r8, r9
; ARMV7-NEXT:    ldr r10, [sp, #76] @ 4-byte Reload
; ARMV7-NEXT:    ldr r5, [sp, #68] @ 4-byte Reload
; ARMV7-NEXT:    mov r8, #0
; ARMV7-NEXT:    lsr r1, r1, r9
; ARMV7-NEXT:    ldr r9, [sp, #20] @ 4-byte Reload
; ARMV7-NEXT:    orr r1, r1, r7, lsl r3
; ARMV7-NEXT:    ldr r7, [sp, #272]
; ARMV7-NEXT:    ldr r2, [sp, #64] @ 4-byte Reload
; ARMV7-NEXT:    subs r3, r7, #1
; ARMV7-NEXT:    ldr r7, [sp, #280]
; ARMV7-NEXT:    str r3, [sp, #60] @ 4-byte Spill
; ARMV7-NEXT:    sbcs r3, r12, #0
; ARMV7-NEXT:    str r3, [sp, #56] @ 4-byte Spill
; ARMV7-NEXT:    sbcs r3, r7, #0
; ARMV7-NEXT:    ldr r7, [sp, #284]
; ARMV7-NEXT:    str r3, [sp, #52] @ 4-byte Spill
; ARMV7-NEXT:    sbc r3, r7, #0
; ARMV7-NEXT:    str r3, [sp, #48] @ 4-byte Spill
; ARMV7-NEXT:    ldr r12, [sp, #92] @ 4-byte Reload
; ARMV7-NEXT:    ldr r3, [sp, #72] @ 4-byte Reload
; ARMV7-NEXT:  .LBB1_4: @ %udiv-do-while3
; ARMV7-NEXT:    @ =>This Inner Loop Header: Depth=1
; ARMV7-NEXT:    str r3, [sp, #72] @ 4-byte Spill
; ARMV7-NEXT:    lsl r3, r11, #1
; ARMV7-NEXT:    ldr r11, [sp, #80] @ 4-byte Reload
; ARMV7-NEXT:    lsl r7, lr, #1
; ARMV7-NEXT:    ldr r0, [sp, #88] @ 4-byte Reload
; ARMV7-NEXT:    orr r3, r3, lr, lsr #31
; ARMV7-NEXT:    str r0, [sp, #64] @ 4-byte Spill
; ARMV7-NEXT:    lsl r0, r11, #1
; ARMV7-NEXT:    str r2, [sp, #76] @ 4-byte Spill
; ARMV7-NEXT:    orr r0, r0, r1, lsr #31
; ARMV7-NEXT:    lsl r1, r1, #1
; ARMV7-NEXT:    ldr r2, [sp, #60] @ 4-byte Reload
; ARMV7-NEXT:    orr r1, r1, r12, lsr #31
; ARMV7-NEXT:    orr r7, r7, r11, lsr #31
; ARMV7-NEXT:    str r5, [sp, #68] @ 4-byte Spill
; ARMV7-NEXT:    subs r4, r2, r1
; ARMV7-NEXT:    ldr r2, [sp, #56] @ 4-byte Reload
; ARMV7-NEXT:    str r12, [sp, #92] @ 4-byte Spill
; ARMV7-NEXT:    sbcs r4, r2, r0
; ARMV7-NEXT:    ldr r2, [sp, #52] @ 4-byte Reload
; ARMV7-NEXT:    sbcs r4, r2, r7
; ARMV7-NEXT:    ldr r2, [sp, #48] @ 4-byte Reload
; ARMV7-NEXT:    sbc r4, r2, r3
; ARMV7-NEXT:    ldr r2, [sp, #284]
; ARMV7-NEXT:    and r5, r2, r4, asr #31
; ARMV7-NEXT:    ldr r2, [sp, #280]
; ARMV7-NEXT:    and lr, r2, r4, asr #31
; ARMV7-NEXT:    ldr r2, [sp, #276]
; ARMV7-NEXT:    and r11, r2, r4, asr #31
; ARMV7-NEXT:    ldr r2, [sp, #272]
; ARMV7-NEXT:    and r12, r2, r4, asr #31
; ARMV7-NEXT:    mov r2, #1
; ARMV7-NEXT:    subs r1, r1, r12
; ARMV7-NEXT:    and r2, r2, r4, asr #31
; ARMV7-NEXT:    sbcs r0, r0, r11
; ARMV7-NEXT:    ldr r4, [sp, #84] @ 4-byte Reload
; ARMV7-NEXT:    sbcs lr, r7, lr
; ARMV7-NEXT:    str r2, [sp, #88] @ 4-byte Spill
; ARMV7-NEXT:    ldr r2, [sp, #68] @ 4-byte Reload
; ARMV7-NEXT:    sbc r11, r3, r5
; ARMV7-NEXT:    subs r4, r4, #1
; ARMV7-NEXT:    str r0, [sp, #80] @ 4-byte Spill
; ARMV7-NEXT:    ldr r0, [sp, #64] @ 4-byte Reload
; ARMV7-NEXT:    sbcs r9, r9, #0
; ARMV7-NEXT:    sbcs r6, r6, #0
; ARMV7-NEXT:    ldr r7, [sp, #76] @ 4-byte Reload
; ARMV7-NEXT:    orr r5, r0, r2, lsl #1
; ARMV7-NEXT:    ldr r0, [sp, #72] @ 4-byte Reload
; ARMV7-NEXT:    sbc r10, r10, #0
; ARMV7-NEXT:    str r4, [sp, #84] @ 4-byte Spill
; ARMV7-NEXT:    orr r3, r9, r10
; ARMV7-NEXT:    orr r4, r4, r6
; ARMV7-NEXT:    orrs r3, r4, r3
; ARMV7-NEXT:    lsl r4, r0, #1
; ARMV7-NEXT:    orr r2, r4, r2, lsr #31
; ARMV7-NEXT:    orr r3, r8, r2
; ARMV7-NEXT:    lsl r2, r7, #1
; ARMV7-NEXT:    orr r2, r2, r0, lsr #31
; ARMV7-NEXT:    ldr r0, [sp, #92] @ 4-byte Reload
; ARMV7-NEXT:    orr r2, r8, r2
; ARMV7-NEXT:    lsl r4, r0, #1
; ARMV7-NEXT:    orr r4, r4, r7, lsr #31
; ARMV7-NEXT:    orr r12, r8, r4
; ARMV7-NEXT:    mov r8, #0
; ARMV7-NEXT:    bne .LBB1_4
; ARMV7-NEXT:  .LBB1_5: @ %udiv-loop-exit2
; ARMV7-NEXT:    ldr r0, [sp, #88] @ 4-byte Reload
; ARMV7-NEXT:    lsl r1, r3, #1
; ARMV7-NEXT:    orr r6, r1, r5, lsr #31
; ARMV7-NEXT:    lsl r1, r2, #1
; ARMV7-NEXT:    ldr r11, [sp, #32] @ 4-byte Reload
; ARMV7-NEXT:    orr r4, r1, r3, lsr #31
; ARMV7-NEXT:    orr r7, r0, r5, lsl #1
; ARMV7-NEXT:    lsl r1, r12, #1
; ARMV7-NEXT:    orr r5, r1, r2, lsr #31
; ARMV7-NEXT:  .LBB1_6: @ %udiv-end1
; ARMV7-NEXT:    str r5, [sp, #48] @ 4-byte Spill
; ARMV7-NEXT:    ldr r5, [sp, #44] @ 4-byte Reload
; ARMV7-NEXT:    str r4, [sp, #20] @ 4-byte Spill
; ARMV7-NEXT:    ldr r4, [sp, #40] @ 4-byte Reload
; ARMV7-NEXT:    clz r0, r5
; ARMV7-NEXT:    ldmib sp, {r1, r2} @ 8-byte Folded Reload
; ARMV7-NEXT:    add r0, r0, #32
; ARMV7-NEXT:    cmp r4, #0
; ARMV7-NEXT:    clzne r0, r4
; ARMV7-NEXT:    cmp r11, #0
; ARMV7-NEXT:    ldr lr, [sp, #280]
; ARMV7-NEXT:    movne r2, r1
; ARMV7-NEXT:    orrs r1, r5, r4
; ARMV7-NEXT:    str r6, [sp, #16] @ 4-byte Spill
; ARMV7-NEXT:    ldr r6, [sp, #284]
; ARMV7-NEXT:    clz r1, lr
; ARMV7-NEXT:    ldr r12, [sp, #272]
; ARMV7-NEXT:    addeq r0, r2, #64
; ARMV7-NEXT:    str r7, [sp, #12] @ 4-byte Spill
; ARMV7-NEXT:    add r1, r1, #32
; ARMV7-NEXT:    ldr r7, [sp, #276]
; ARMV7-NEXT:    clz r2, r12
; ARMV7-NEXT:    cmp r6, #0
; ARMV7-NEXT:    add r2, r2, #32
; ARMV7-NEXT:    clzne r1, r6
; ARMV7-NEXT:    cmp r7, #0
; ARMV7-NEXT:    clzne r2, r7
; ARMV7-NEXT:    orrs r3, lr, r6
; ARMV7-NEXT:    addeq r1, r2, #64
; ARMV7-NEXT:    mov r2, #0
; ARMV7-NEXT:    subs r10, r1, r0
; ARMV7-NEXT:    orr r3, r11, r4
; ARMV7-NEXT:    sbcs r9, r2, #0
; ARMV7-NEXT:    sbcs r1, r2, #0
; ARMV7-NEXT:    str r1, [sp, #80] @ 4-byte Spill
; ARMV7-NEXT:    sbc r8, r2, #0
; ARMV7-NEXT:    rsbs r0, r10, #127
; ARMV7-NEXT:    rscs r0, r9, #0
; ARMV7-NEXT:    rscs r0, r1, #0
; ARMV7-NEXT:    orr r1, r7, r6
; ARMV7-NEXT:    rscs r0, r8, #0
; ARMV7-NEXT:    mov r7, r11
; ARMV7-NEXT:    orr r0, r12, lr
; ARMV7-NEXT:    ldr r12, [sp, #36] @ 4-byte Reload
; ARMV7-NEXT:    orr r0, r0, r1
; ARMV7-NEXT:    movwlo r2, #1
; ARMV7-NEXT:    orr r1, r12, r5
; ARMV7-NEXT:    clz r0, r0
; ARMV7-NEXT:    orr r1, r1, r3
; ARMV7-NEXT:    mov r3, r12
; ARMV7-NEXT:    clz r1, r1
; ARMV7-NEXT:    lsr r0, r0, #5
; ARMV7-NEXT:    lsr r1, r1, #5
; ARMV7-NEXT:    orr r0, r0, r1
; ARMV7-NEXT:    orrs r0, r0, r2
; ARMV7-NEXT:    movwne r5, #0
; ARMV7-NEXT:    movwne r4, #0
; ARMV7-NEXT:    movwne r3, #0
; ARMV7-NEXT:    movwne r7, #0
; ARMV7-NEXT:    str r5, [sp, #44] @ 4-byte Spill
; ARMV7-NEXT:    str r4, [sp, #40] @ 4-byte Spill
; ARMV7-NEXT:    bne .LBB1_15
; ARMV7-NEXT:  @ %bb.7: @ %udiv-end1
; ARMV7-NEXT:    ldr r1, [sp, #80] @ 4-byte Reload
; ARMV7-NEXT:    eor r0, r10, #127
; ARMV7-NEXT:    ldr lr, [sp, #264]
; ARMV7-NEXT:    orr r0, r0, r1
; ARMV7-NEXT:    orr r1, r9, r8
; ARMV7-NEXT:    orrs r0, r0, r1
; ARMV7-NEXT:    beq .LBB1_12
; ARMV7-NEXT:  @ %bb.8: @ %udiv-bb1
; ARMV7-NEXT:    mov r0, #0
; ARMV7-NEXT:    add r3, sp, #128
; ARMV7-NEXT:    str r0, [sp, #140]
; ARMV7-NEXT:    mov r1, #12
; ARMV7-NEXT:    str r0, [sp, #136]
; ARMV7-NEXT:    add r3, r3, #16
; ARMV7-NEXT:    str r0, [sp, #132]
; ARMV7-NEXT:    str r0, [sp, #128]
; ARMV7-NEXT:    ldr r0, [sp, #268]
; ARMV7-NEXT:    str r0, [sp, #156]
; ARMV7-NEXT:    rsb r0, r10, #127
; ARMV7-NEXT:    str r12, [sp, #144]
; ARMV7-NEXT:    and r1, r1, r0, lsr #3
; ARMV7-NEXT:    str r11, [sp, #148]
; ARMV7-NEXT:    str lr, [sp, #152]
; ARMV7-NEXT:    and r0, r0, #31
; ARMV7-NEXT:    ldr r1, [r3, -r1]!
; ARMV7-NEXT:    eor r2, r0, #31
; ARMV7-NEXT:    ldmib r3, {r5, r7}
; ARMV7-NEXT:    lsr r6, r1, #1
; ARMV7-NEXT:    ldr r3, [r3, #12]
; ARMV7-NEXT:    lsl r4, r5, r0
; ARMV7-NEXT:    orr r6, r4, r6, lsr r2
; ARMV7-NEXT:    lsr r4, r7, #1
; ARMV7-NEXT:    str r6, [sp, #84] @ 4-byte Spill
; ARMV7-NEXT:    lsl r3, r3, r0
; ARMV7-NEXT:    orr r3, r3, r4, lsr r2
; ARMV7-NEXT:    lsrs r4, r5, #1
; ARMV7-NEXT:    str r3, [sp, #92] @ 4-byte Spill
; ARMV7-NEXT:    lsl r3, r7, r0
; ARMV7-NEXT:    orr r5, r3, r4, lsr r2
; ARMV7-NEXT:    adds r4, r10, #1
; ARMV7-NEXT:    lsl r7, r1, r0
; ARMV7-NEXT:    adcs r0, r9, #0
; ARMV7-NEXT:    str r0, [sp, #72] @ 4-byte Spill
; ARMV7-NEXT:    mov r1, #0
; ARMV7-NEXT:    ldr r0, [sp, #80] @ 4-byte Reload
; ARMV7-NEXT:    adcs r2, r0, #0
; ARMV7-NEXT:    adcs r0, r8, #0
; ARMV7-NEXT:    str r0, [sp, #76] @ 4-byte Spill
; ARMV7-NEXT:    mov r0, #0
; ARMV7-NEXT:    str r0, [sp, #88] @ 4-byte Spill
; ARMV7-NEXT:    adcs r0, r1, #0
; ARMV7-NEXT:    bne .LBB1_14
; ARMV7-NEXT:  @ %bb.9: @ %udiv-preheader
; ARMV7-NEXT:    mov r0, #0
; ARMV7-NEXT:    add r6, sp, #96
; ARMV7-NEXT:    str r0, [sp, #124]
; ARMV7-NEXT:    and r10, r4, #31
; ARMV7-NEXT:    str r0, [sp, #120]
; ARMV7-NEXT:    str r0, [sp, #116]
; ARMV7-NEXT:    str r0, [sp, #112]
; ARMV7-NEXT:    ldr r0, [sp, #264]
; ARMV7-NEXT:    str r0, [sp, #104]
; ARMV7-NEXT:    ldr r0, [sp, #268]
; ARMV7-NEXT:    str r0, [sp, #108]
; ARMV7-NEXT:    ubfx r0, r4, #5, #2
; ARMV7-NEXT:    str r12, [sp, #96]
; ARMV7-NEXT:    add r3, r6, r0, lsl #2
; ARMV7-NEXT:    str r11, [sp, #100]
; ARMV7-NEXT:    ldr r1, [r3, #8]
; ARMV7-NEXT:    ldr r12, [r3, #4]
; ARMV7-NEXT:    ldr r9, [r3, #12]
; ARMV7-NEXT:    str r4, [sp, #80] @ 4-byte Spill
; ARMV7-NEXT:    eor r4, r10, #31
; ARMV7-NEXT:    ldr r0, [r6, r0, lsl #2]
; ARMV7-NEXT:    lsr r11, r1, r10
; ARMV7-NEXT:    lsl r3, r9, #1
; ARMV7-NEXT:    lsl r1, r1, #1
; ARMV7-NEXT:    orr lr, r11, r3, lsl r4
; ARMV7-NEXT:    lsr r11, r12, r10
; ARMV7-NEXT:    orr r3, r11, r1, lsl r4
; ARMV7-NEXT:    lsr r0, r0, r10
; ARMV7-NEXT:    lsl r1, r12, #1
; ARMV7-NEXT:    orr r8, r0, r1, lsl r4
; ARMV7-NEXT:    ldr r0, [sp, #272]
; ARMV7-NEXT:    lsr r1, r9, r10
; ARMV7-NEXT:    ldr r6, [sp, #92] @ 4-byte Reload
; ARMV7-NEXT:    subs r0, r0, #1
; ARMV7-NEXT:    str r0, [sp, #64] @ 4-byte Spill
; ARMV7-NEXT:    ldr r0, [sp, #276]
; ARMV7-NEXT:    mov r10, #0
; ARMV7-NEXT:    ldr r9, [sp, #72] @ 4-byte Reload
; ARMV7-NEXT:    sbcs r0, r0, #0
; ARMV7-NEXT:    str r0, [sp, #60] @ 4-byte Spill
; ARMV7-NEXT:    ldr r0, [sp, #280]
; ARMV7-NEXT:    ldr r11, [sp, #76] @ 4-byte Reload
; ARMV7-NEXT:    sbcs r0, r0, #0
; ARMV7-NEXT:    str r0, [sp, #56] @ 4-byte Spill
; ARMV7-NEXT:    ldr r0, [sp, #284]
; ARMV7-NEXT:    sbc r0, r0, #0
; ARMV7-NEXT:    str r0, [sp, #52] @ 4-byte Spill
; ARMV7-NEXT:  .LBB1_10: @ %udiv-do-while
; ARMV7-NEXT:    @ =>This Inner Loop Header: Depth=1
; ARMV7-NEXT:    ldr r4, [sp, #88] @ 4-byte Reload
; ARMV7-NEXT:    str r4, [sp, #68] @ 4-byte Spill
; ARMV7-NEXT:    lsl r4, r8, #1
; ARMV7-NEXT:    ldr r0, [sp, #64] @ 4-byte Reload
; ARMV7-NEXT:    orr r4, r4, r6, lsr #31
; ARMV7-NEXT:    str r5, [sp, #76] @ 4-byte Spill
; ARMV7-NEXT:    ldr r5, [sp, #84] @ 4-byte Reload
; ARMV7-NEXT:    str r7, [sp, #84] @ 4-byte Spill
; ARMV7-NEXT:    lsl r7, r1, #1
; ARMV7-NEXT:    lsl r1, lr, #1
; ARMV7-NEXT:    str r5, [sp, #72] @ 4-byte Spill
; ARMV7-NEXT:    orr r1, r1, r3, lsr #31
; ARMV7-NEXT:    lsl r3, r3, #1
; ARMV7-NEXT:    subs r5, r0, r4
; ARMV7-NEXT:    ldr r0, [sp, #60] @ 4-byte Reload
; ARMV7-NEXT:    orr r3, r3, r8, lsr #31
; ARMV7-NEXT:    orr r7, r7, lr, lsr #31
; ARMV7-NEXT:    sbcs r5, r0, r3
; ARMV7-NEXT:    ldr r0, [sp, #56] @ 4-byte Reload
; ARMV7-NEXT:    str r6, [sp, #92] @ 4-byte Spill
; ARMV7-NEXT:    sbcs r5, r0, r1
; ARMV7-NEXT:    ldr r0, [sp, #52] @ 4-byte Reload
; ARMV7-NEXT:    sbc r5, r0, r7
; ARMV7-NEXT:    ldr r0, [sp, #284]
; ARMV7-NEXT:    and r6, r0, r5, asr #31
; ARMV7-NEXT:    ldr r0, [sp, #280]
; ARMV7-NEXT:    and lr, r0, r5, asr #31
; ARMV7-NEXT:    ldr r0, [sp, #276]
; ARMV7-NEXT:    and r12, r0, r5, asr #31
; ARMV7-NEXT:    ldr r0, [sp, #272]
; ARMV7-NEXT:    and r8, r0, r5, asr #31
; ARMV7-NEXT:    mov r0, #1
; ARMV7-NEXT:    subs r8, r4, r8
; ARMV7-NEXT:    and r0, r0, r5, asr #31
; ARMV7-NEXT:    sbcs r3, r3, r12
; ARMV7-NEXT:    ldr r5, [sp, #80] @ 4-byte Reload
; ARMV7-NEXT:    sbcs lr, r1, lr
; ARMV7-NEXT:    str r0, [sp, #88] @ 4-byte Spill
; ARMV7-NEXT:    sbc r12, r7, r6
; ARMV7-NEXT:    subs r5, r5, #1
; ARMV7-NEXT:    sbcs r9, r9, #0
; ARMV7-NEXT:    ldr r0, [sp, #84] @ 4-byte Reload
; ARMV7-NEXT:    sbcs r2, r2, #0
; ARMV7-NEXT:    ldr r4, [sp, #72] @ 4-byte Reload
; ARMV7-NEXT:    sbc r11, r11, #0
; ARMV7-NEXT:    str r5, [sp, #80] @ 4-byte Spill
; ARMV7-NEXT:    orr r7, r9, r11
; ARMV7-NEXT:    orr r5, r5, r2
; ARMV7-NEXT:    ldr r1, [sp, #68] @ 4-byte Reload
; ARMV7-NEXT:    orrs r7, r5, r7
; ARMV7-NEXT:    lsl r5, r4, #1
; ARMV7-NEXT:    ldr r6, [sp, #76] @ 4-byte Reload
; ARMV7-NEXT:    orr r7, r1, r0, lsl #1
; ARMV7-NEXT:    orr r0, r5, r0, lsr #31
; ARMV7-NEXT:    orr r0, r10, r0
; ARMV7-NEXT:    str r0, [sp, #84] @ 4-byte Spill
; ARMV7-NEXT:    ldr r0, [sp, #92] @ 4-byte Reload
; ARMV7-NEXT:    lsl r5, r6, #1
; ARMV7-NEXT:    orr r5, r5, r4, lsr #31
; ARMV7-NEXT:    mov r1, r12
; ARMV7-NEXT:    orr r5, r10, r5
; ARMV7-NEXT:    lsl r0, r0, #1
; ARMV7-NEXT:    orr r0, r0, r6, lsr #31
; ARMV7-NEXT:    orr r6, r10, r0
; ARMV7-NEXT:    mov r10, #0
; ARMV7-NEXT:    bne .LBB1_10
; ARMV7-NEXT:  .LBB1_11: @ %udiv-loop-exit
; ARMV7-NEXT:    ldr r0, [sp, #88] @ 4-byte Reload
; ARMV7-NEXT:    ldr r11, [sp, #32] @ 4-byte Reload
; ARMV7-NEXT:    orr r3, r0, r7, lsl #1
; ARMV7-NEXT:    ldr r0, [sp, #84] @ 4-byte Reload
; ARMV7-NEXT:    ldr r12, [sp, #36] @ 4-byte Reload
; ARMV7-NEXT:    ldr lr, [sp, #264]
; ARMV7-NEXT:    lsl r1, r0, #1
; ARMV7-NEXT:    orr r7, r1, r7, lsr #31
; ARMV7-NEXT:    lsl r1, r5, #1
; ARMV7-NEXT:    orr r0, r1, r0, lsr #31
; ARMV7-NEXT:    str r0, [sp, #44] @ 4-byte Spill
; ARMV7-NEXT:    lsl r0, r6, #1
; ARMV7-NEXT:    orr r0, r0, r5, lsr #31
; ARMV7-NEXT:    str r0, [sp, #40] @ 4-byte Spill
; ARMV7-NEXT:  .LBB1_12: @ %udiv-end
; ARMV7-NEXT:    ldr r10, [sp, #272]
; ARMV7-NEXT:    mov r6, #0
; ARMV7-NEXT:    ldr r4, [sp, #12] @ 4-byte Reload
; ARMV7-NEXT:    mov r2, #0
; ARMV7-NEXT:    ldr r8, [sp, #276]
; ARMV7-NEXT:    umull r0, r1, r10, r3
; ARMV7-NEXT:    umlal r1, r6, r8, r3
; ARMV7-NEXT:    str r0, [sp, #92] @ 4-byte Spill
; ARMV7-NEXT:    ldr r0, [sp, #24] @ 4-byte Reload
; ARMV7-NEXT:    str r4, [r0]
; ARMV7-NEXT:    ldr r4, [sp, #16] @ 4-byte Reload
; ARMV7-NEXT:    str r4, [r0, #4]
; ARMV7-NEXT:    ldr r4, [sp, #20] @ 4-byte Reload
; ARMV7-NEXT:    str r4, [r0, #8]
; ARMV7-NEXT:    ldr r4, [sp, #48] @ 4-byte Reload
; ARMV7-NEXT:    str r4, [r0, #12]
; ARMV7-NEXT:    umull r5, r4, r10, r7
; ARMV7-NEXT:    ldr r0, [sp, #280]
; ARMV7-NEXT:    adds r9, r5, r1
; ARMV7-NEXT:    ldr r1, [sp, #284]
; ARMV7-NEXT:    adcs r6, r6, r4
; ARMV7-NEXT:    umull r5, r4, r3, r0
; ARMV7-NEXT:    adc r2, r2, #0
; ARMV7-NEXT:    mla r3, r3, r1, r4
; ARMV7-NEXT:    umlal r6, r2, r8, r7
; ARMV7-NEXT:    mla r3, r7, r0, r3
; ARMV7-NEXT:    ldr r0, [sp, #44] @ 4-byte Reload
; ARMV7-NEXT:    umull r7, r4, r0, r10
; ARMV7-NEXT:    mla r4, r0, r8, r4
; ARMV7-NEXT:    ldr r0, [sp, #40] @ 4-byte Reload
; ARMV7-NEXT:    adds r7, r7, r5
; ARMV7-NEXT:    mla r4, r0, r10, r4
; ARMV7-NEXT:    ldr r0, [sp, #92] @ 4-byte Reload
; ARMV7-NEXT:    adc r3, r4, r3
; ARMV7-NEXT:    adds r7, r6, r7
; ARMV7-NEXT:    adc r2, r2, r3
; ARMV7-NEXT:    subs r0, r12, r0
; ARMV7-NEXT:    sbcs r1, r11, r9
; ARMV7-NEXT:    sbcs r3, lr, r7
; ARMV7-NEXT:    ldr r7, [sp, #268]
; ARMV7-NEXT:    sbc r2, r7, r2
; ARMV7-NEXT:    ldr r7, [sp, #28] @ 4-byte Reload
; ARMV7-NEXT:    stm r7, {r0, r1, r3}
; ARMV7-NEXT:    str r2, [r7, #12]
; ARMV7-NEXT:    add sp, sp, #228
; ARMV7-NEXT:    pop {r4, r5, r6, r7, r8, r9, r10, r11, pc}
; ARMV7-NEXT:  .LBB1_13:
; ARMV7-NEXT:    ldr r12, [sp, #92] @ 4-byte Reload
; ARMV7-NEXT:    ldr r3, [sp, #72] @ 4-byte Reload
; ARMV7-NEXT:    ldr r5, [sp, #68] @ 4-byte Reload
; ARMV7-NEXT:    ldr r2, [sp, #64] @ 4-byte Reload
; ARMV7-NEXT:    b .LBB1_5
; ARMV7-NEXT:  .LBB1_14:
; ARMV7-NEXT:    ldr r6, [sp, #92] @ 4-byte Reload
; ARMV7-NEXT:    b .LBB1_11
; ARMV7-NEXT:  .LBB1_15:
; ARMV7-NEXT:    ldr lr, [sp, #264]
; ARMV7-NEXT:    b .LBB1_12
  %q = udiv i128 %n, %d
  %r = urem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}
