# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=thumbv7-apple-ios -run-pass=if-converter %s -o - | FileCheck %s

# Forked-diamond testcase with unanalyzable instructions in both the True and
# False BBs following the forked diamond.

---
name:            foo
body:             |
  ; CHECK-LABEL: name: foo
  ; CHECK: bb.0:
  ; CHECK:   successors: %bb.2(0x20000000), %bb.1(0x60000000)
  ; CHECK:   $sp = tADDspi $sp, 2, 1 /* CC::ne */, $cpsr
  ; CHECK:   $sp = tADDspi $sp, 1, 0 /* CC::eq */, $cpsr, implicit $sp
  ; CHECK:   t2Bcc %bb.2, 1 /* CC::ne */, $cpsr
  ; CHECK: bb.1:
  ; CHECK:   $sp = tADDspi $sp, 4, 14 /* CC::al */, $noreg
  ; CHECK:   tBX_RET 14 /* CC::al */, $noreg
  ; CHECK: bb.2:
  ; CHECK:   $sp = tADDspi $sp, 3, 14 /* CC::al */, $noreg
  ; CHECK:   tBX_RET 14 /* CC::al */, $noreg
  bb.0:
    tBcc %bb.2, 1, $cpsr

  bb.1:
  successors: %bb.3(0x20000000), %bb.4(0x60000000)
    $sp = tADDspi $sp, 1, 14, _
    tBcc %bb.3, 1, $cpsr
    tB %bb.4, 14, $noreg

  bb.2:
  successors: %bb.3(0x20000000), %bb.4(0x60000000)
    $sp = tADDspi $sp, 2, 14, _
    tBcc %bb.3, 1, $cpsr
    tB %bb.4, 14, $noreg

  bb.3:
  successors:
    $sp = tADDspi $sp, 3, 14, _
    tBX_RET 14, _

  bb.4:
  successors:
    $sp = tADDspi $sp, 4, 14, _
    tBX_RET 14, _
...
