; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=armv5t-unknown-linux-gnueabi < %s | FileCheck %s

; https://bugs.llvm.org/show_bug.cgi?id=38149

; We are truncating from wider width, and then sign-extending
; back to the original width. Then we inequality-comparing orig and src.
; If they don't match, then we had signed truncation during truncation.

; This can be expressed in a several ways in IR:
;   trunc + sext + icmp ne <- not canonical
;   shl   + ashr + icmp ne
;   add          + icmp ult/ule
;   add          + icmp uge/ugt
; However only the simplest form (with two shifts) gets lowered best.

; ---------------------------------------------------------------------------- ;
; shl + ashr + icmp ne
; ---------------------------------------------------------------------------- ;

define i1 @shifts_necmp_i16_i8(i16 %x) nounwind {
; CHECK-LABEL: shifts_necmp_i16_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r1, #255
; CHECK-NEXT:    orr r1, r1, #65280
; CHECK-NEXT:    and r2, r0, r1
; CHECK-NEXT:    lsl r0, r0, #24
; CHECK-NEXT:    and r0, r1, r0, asr #24
; CHECK-NEXT:    subs r0, r0, r2
; CHECK-NEXT:    movne r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = shl i16 %x, 8 ; 16-8
  %tmp1 = ashr exact i16 %tmp0, 8 ; 16-8
  %tmp2 = icmp ne i16 %tmp1, %x
  ret i1 %tmp2
}

define i1 @shifts_necmp_i32_i16(i32 %x) nounwind {
; CHECK-LABEL: shifts_necmp_i32_i16:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    lsl r1, r0, #16
; CHECK-NEXT:    subs r0, r0, r1, asr #16
; CHECK-NEXT:    movne r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = shl i32 %x, 16 ; 32-16
  %tmp1 = ashr exact i32 %tmp0, 16 ; 32-16
  %tmp2 = icmp ne i32 %tmp1, %x
  ret i1 %tmp2
}

define i1 @shifts_necmp_i32_i8(i32 %x) nounwind {
; CHECK-LABEL: shifts_necmp_i32_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    lsl r1, r0, #24
; CHECK-NEXT:    subs r0, r0, r1, asr #24
; CHECK-NEXT:    movne r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = shl i32 %x, 24 ; 32-8
  %tmp1 = ashr exact i32 %tmp0, 24 ; 32-8
  %tmp2 = icmp ne i32 %tmp1, %x
  ret i1 %tmp2
}

; ---------------------------------------------------------------------------- ;
; add + icmp ult
; ---------------------------------------------------------------------------- ;

define i1 @add_ultcmp_i16_i8(i16 %x) nounwind {
; CHECK-LABEL: add_ultcmp_i16_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r1, #255
; CHECK-NEXT:    orr r1, r1, #65280
; CHECK-NEXT:    and r0, r0, r1
; CHECK-NEXT:    sub r1, r0, #128
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #65280
; CHECK-NEXT:    movlo r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, -128 ; ~0U << (8-1)
  %tmp1 = icmp ult i16 %tmp0, -256 ; ~0U << 8
  ret i1 %tmp1
}

define i1 @add_ultcmp_i32_i16(i32 %x) nounwind {
; CHECK-LABEL: add_ultcmp_i32_i16:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    sub r1, r0, #32768
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmn r1, #65536
; CHECK-NEXT:    movlo r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i32 %x, -32768 ; ~0U << (16-1)
  %tmp1 = icmp ult i32 %tmp0, -65536 ; ~0U << 16
  ret i1 %tmp1
}

define i1 @add_ultcmp_i32_i8(i32 %x) nounwind {
; CHECK-LABEL: add_ultcmp_i32_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    sub r1, r0, #128
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmn r1, #256
; CHECK-NEXT:    movlo r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i32 %x, -128 ; ~0U << (8-1)
  %tmp1 = icmp ult i32 %tmp0, -256 ; ~0U << 8
  ret i1 %tmp1
}

; Slightly more canonical variant
define i1 @add_ulecmp_i16_i8(i16 %x) nounwind {
; CHECK-LABEL: add_ulecmp_i16_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r1, #255
; CHECK-NEXT:    orr r1, r1, #65280
; CHECK-NEXT:    and r0, r0, r1
; CHECK-NEXT:    sub r1, r0, #128
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #65280
; CHECK-NEXT:    movlo r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, -128 ; ~0U << (8-1)
  %tmp1 = icmp ule i16 %tmp0, -257 ; ~0U << 8 - 1
  ret i1 %tmp1
}

; ---------------------------------------------------------------------------- ;
; add + icmp uge
; ---------------------------------------------------------------------------- ;

define i1 @add_ugecmp_i16_i8(i16 %x) nounwind {
; CHECK-LABEL: add_ugecmp_i16_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r1, #255
; CHECK-NEXT:    add r0, r0, #128
; CHECK-NEXT:    orr r1, r1, #65280
; CHECK-NEXT:    and r1, r0, r1
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #255
; CHECK-NEXT:    movhi r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp uge i16 %tmp0, 256 ; 1U << 8
  ret i1 %tmp1
}

define i1 @add_ugecmp_i32_i16(i32 %x) nounwind {
; CHECK-LABEL: add_ugecmp_i32_i16:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    add r0, r0, #32768
; CHECK-NEXT:    lsrs r0, r0, #16
; CHECK-NEXT:    movne r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i32 %x, 32768 ; 1U << (16-1)
  %tmp1 = icmp uge i32 %tmp0, 65536 ; 1U << 16
  ret i1 %tmp1
}

define i1 @add_ugecmp_i32_i8(i32 %x) nounwind {
; CHECK-LABEL: add_ugecmp_i32_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    add r1, r0, #128
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #255
; CHECK-NEXT:    movhi r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i32 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp uge i32 %tmp0, 256 ; 1U << 8
  ret i1 %tmp1
}

; Slightly more canonical variant
define i1 @add_ugtcmp_i16_i8(i16 %x) nounwind {
; CHECK-LABEL: add_ugtcmp_i16_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r1, #255
; CHECK-NEXT:    add r0, r0, #128
; CHECK-NEXT:    orr r1, r1, #65280
; CHECK-NEXT:    and r1, r0, r1
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #255
; CHECK-NEXT:    movhi r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp ugt i16 %tmp0, 255 ; (1U << 8) - 1
  ret i1 %tmp1
}

; Negative tests
; ---------------------------------------------------------------------------- ;

; Adding not a constant
define i1 @add_ugecmp_bad_i16_i8_add(i16 %x, i16 %y) nounwind {
; CHECK-LABEL: add_ugecmp_bad_i16_i8_add:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    add r0, r0, r1
; CHECK-NEXT:    mov r1, #255
; CHECK-NEXT:    orr r1, r1, #65280
; CHECK-NEXT:    and r1, r0, r1
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #255
; CHECK-NEXT:    movhi r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, %y
  %tmp1 = icmp uge i16 %tmp0, 256 ; 1U << 8
  ret i1 %tmp1
}

; Comparing not with a constant
define i1 @add_ugecmp_bad_i16_i8_cmp(i16 %x, i16 %y) nounwind {
; CHECK-LABEL: add_ugecmp_bad_i16_i8_cmp:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r2, #255
; CHECK-NEXT:    add r0, r0, #128
; CHECK-NEXT:    orr r2, r2, #65280
; CHECK-NEXT:    and r1, r1, r2
; CHECK-NEXT:    and r2, r0, r2
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r2, r1
; CHECK-NEXT:    movhs r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp uge i16 %tmp0, %y
  ret i1 %tmp1
}

; Second constant is not larger than the first one
define i1 @add_ugecmp_bad_i8_i16(i16 %x) nounwind {
; CHECK-LABEL: add_ugecmp_bad_i8_i16:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r1, #255
; CHECK-NEXT:    add r0, r0, #128
; CHECK-NEXT:    orr r1, r1, #65280
; CHECK-NEXT:    and r1, r0, r1
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #127
; CHECK-NEXT:    movhi r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp uge i16 %tmp0, 128 ; 1U << (8-1)
  ret i1 %tmp1
}

; First constant is not power of two
define i1 @add_ugecmp_bad_i16_i8_c0notpoweroftwo(i16 %x) nounwind {
; CHECK-LABEL: add_ugecmp_bad_i16_i8_c0notpoweroftwo:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r1, #255
; CHECK-NEXT:    add r0, r0, #192
; CHECK-NEXT:    orr r1, r1, #65280
; CHECK-NEXT:    and r1, r0, r1
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #255
; CHECK-NEXT:    movhi r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 192 ; (1U << (8-1)) + (1U << (8-1-1))
  %tmp1 = icmp uge i16 %tmp0, 256 ; 1U << 8
  ret i1 %tmp1
}

; Second constant is not power of two
define i1 @add_ugecmp_bad_i16_i8_c1notpoweroftwo(i16 %x) nounwind {
; CHECK-LABEL: add_ugecmp_bad_i16_i8_c1notpoweroftwo:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    add r0, r0, #128
; CHECK-NEXT:    and r0, r0, #65280
; CHECK-NEXT:    lsr r1, r0, #8
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #2
; CHECK-NEXT:    movhi r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp uge i16 %tmp0, 768 ; (1U << 8)) + (1U << (8+1))
  ret i1 %tmp1
}

; Magic check fails, 64 << 1 != 256
define i1 @add_ugecmp_bad_i16_i8_magic(i16 %x) nounwind {
; CHECK-LABEL: add_ugecmp_bad_i16_i8_magic:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r1, #255
; CHECK-NEXT:    add r0, r0, #64
; CHECK-NEXT:    orr r1, r1, #65280
; CHECK-NEXT:    and r1, r0, r1
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #255
; CHECK-NEXT:    movhi r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 64 ; 1U << (8-1-1)
  %tmp1 = icmp uge i16 %tmp0, 256 ; 1U << 8
  ret i1 %tmp1
}

; Bad 'destination type'
define i1 @add_ugecmp_bad_i16_i4(i16 %x) nounwind {
; CHECK-LABEL: add_ugecmp_bad_i16_i4:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r1, #255
; CHECK-NEXT:    add r0, r0, #8
; CHECK-NEXT:    orr r1, r1, #65280
; CHECK-NEXT:    and r1, r0, r1
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #15
; CHECK-NEXT:    movhi r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 8 ; 1U << (4-1)
  %tmp1 = icmp uge i16 %tmp0, 16 ; 1U << 4
  ret i1 %tmp1
}

; Bad storage type
define i1 @add_ugecmp_bad_i24_i8(i24 %x) nounwind {
; CHECK-LABEL: add_ugecmp_bad_i24_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    add r0, r0, #128
; CHECK-NEXT:    bic r1, r0, #-16777216
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #255
; CHECK-NEXT:    movhi r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i24 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp uge i24 %tmp0, 256 ; 1U << 8
  ret i1 %tmp1
}

; Slightly more canonical variant
define i1 @add_ugtcmp_bad_i16_i8(i16 %x) nounwind {
; CHECK-LABEL: add_ugtcmp_bad_i16_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp ugt i16 %tmp0, -1 ; when we +1 it, it will wrap to 0
  ret i1 %tmp1
}
