# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=thumbv6m--eabi -verify-machineinstrs -run-pass=arm-ldst-opt %s -o - | FileCheck %s

# Check that tSUBi8 is NOT generated if the base register isn't live-in
# to any successor block. Before the PR21029 workaround was removed, the
# base register was reset unconditionally at the end of the block.

# CHECK-LABEL: bb.0:
# CHECK: $r4 = tLDMIA_UPD $r4, 14 /* CC::al */, $noreg, def $r0, def $r1
# CHECK-NOT: tSUBi8 $r4

# CHECK-LABEL: bb.1:
# CHECK: $r4 = tLDMIA_UPD $r4, 14 /* CC::al */, $noreg, def $r0, def $r1
# CHECK: $r4, dead $cpsr = tSUBi8 $r4, 8, 14 /* CC::al */, $noreg

---
name:            foo
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: foo
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $r4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r4 = tLDMIA_UPD $r4, 14 /* CC::al */, $noreg, def $r0, def $r1 :: (load (s32))
  ; CHECK-NEXT:   $r4, dead $cpsr = tSUBi8 $r4, 8, 14 /* CC::al */, $noreg
  ; CHECK-NEXT:   tB %bb.2, 14 /* CC::al */, $noreg
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $r4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r4 = tLDMIA_UPD $r4, 14 /* CC::al */, $noreg, def $r0, def $r1 :: (load (s32))
  ; CHECK-NEXT:   $r4, dead $cpsr = tSUBi8 $r4, 8, 14 /* CC::al */, $noreg
  ; CHECK-NEXT:   tB %bb.3, 14 /* CC::al */, $noreg
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $r0, $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   tTRAP
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   liveins: $r0, $r1, $r4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   tTRAP
  bb.0:
    liveins: $r4
    renamable $r0 = tLDRi renamable $r4, 0, 14, $noreg :: (load (s32))
    renamable $r1 = tLDRi renamable $r4, 1, 14, $noreg :: (load (s32))
    tB %bb.2, 14, $noreg

  bb.1:
    liveins: $r4
    renamable $r0 = tLDRi renamable $r4, 0, 14, $noreg :: (load (s32))
    renamable $r1 = tLDRi renamable $r4, 1, 14, $noreg :: (load (s32))
    tB %bb.3, 14, $noreg

  bb.2:
    liveins: $r0, $r1
    tTRAP

  bb.3:
    liveins: $r0, $r1, $r4
    tTRAP


...
