; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=armv7-unknown-linux-gnueabi -relocation-model pic -mattr=+long-calls -o - %s \
; RUN:    | FileCheck %s

@msg = private unnamed_addr constant [12 x i8] c"hello world\00", align 1

declare i32 @puts(ptr)

define void @test() {
; CHECK-LABEL: test:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    .save {r11, lr}
; CHECK-NEXT:    push {r11, lr}
; CHECK-NEXT:    ldr r0, .LCPI0_0
; CHECK-NEXT:    ldr r1, .LCPI0_1
; CHECK-NEXT:  .LPC0_0:
; CHECK-NEXT:    add r0, pc, r0
; CHECK-NEXT:  .LPC0_1:
; CHECK-NEXT:    ldr r1, [pc, r1]
; CHECK-NEXT:    blx r1
; CHECK-NEXT:    pop {r11, pc}
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  @ %bb.1:
; CHECK-NEXT:  .LCPI0_0:
; CHECK-NEXT:    .long .Lmsg-(.LPC0_0+8)
; CHECK-NEXT:  .LCPI0_1:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .long puts(GOT_PREL)-(.LPC0_1+8-.Ltmp0)
entry:
  %call = call i32 @puts(ptr @msg)
  ret void
}
