; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=thumbv8.1m.main-unknown-unknown < %s | FileCheck %s

; Make sure this does not assert during machine outlining.

declare void @a(...)

define void @b(i32 %a, i32 %b, i32 %c, ptr %d, ptr %e) minsize {
; CHECK-LABEL: b:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    mov r1, r0
; CHECK-NEXT:    ldr r3, [sp]
; CHECK-NEXT:    movs r0, #2
; CHECK-NEXT:    b a
  tail call void @a(i32 2, i32 %a, i32 %b, ptr %e)
  ret void
}

define void @c(i32 %a, i32 %b, i32 %c, ptr %d, ptr %e) minsize {
; CHECK-LABEL: c:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r2, r1
; CHECK-NEXT:    mov r1, r0
; CHECK-NEXT:    ldr r3, [sp]
; CHECK-NEXT:    movs r0, #4
; CHECK-NEXT:    b a
  tail call void @a(i32 4, i32 %a, i32 %b, ptr %e)
  ret void
}
