; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=thumbv7-apple-ios -mcpu=cortex-a8 -pre-RA-sched=source -disable-post-ra | FileCheck %s -check-prefix=CHECK-7A
; RUN: llc < %s -mtriple=thumbv6m -pre-RA-sched=source -disable-post-ra -mattr=+strict-align | FileCheck %s -check-prefix=CHECK-6M

define void @t1(ptr nocapture %c) nounwind optsize {
; CHECK-7A-LABEL: t1:
; CHECK-7A:       @ %bb.0: @ %entry
; CHECK-7A-NEXT:    movs r1, #0
; CHECK-7A-NEXT:    strd r1, r1, [r0]
; CHECK-7A-NEXT:    str r1, [r0, #8]
; CHECK-7A-NEXT:    bx lr
;
; CHECK-6M-LABEL: t1:
; CHECK-6M:       @ %bb.0: @ %entry
; CHECK-6M-NEXT:    movs r1, #0
; CHECK-6M-NEXT:    str r1, [r0]
; CHECK-6M-NEXT:    str r1, [r0, #4]
; CHECK-6M-NEXT:    str r1, [r0, #8]
; CHECK-6M-NEXT:    bx lr
entry:
  call void @llvm.memset.p0.i64(ptr align 8 %c, i8 0, i64 12, i1 false)
  ret void
}

define void @t2() nounwind ssp {
; CHECK-7A-LABEL: t2:
; CHECK-7A:       @ %bb.0: @ %entry
; CHECK-7A-NEXT:    push {r4, r7, lr}
; CHECK-7A-NEXT:    add r7, sp, #4
; CHECK-7A-NEXT:    sub sp, #36
; CHECK-7A-NEXT:    mov r4, sp
; CHECK-7A-NEXT:    bfc r4, #0, #3
; CHECK-7A-NEXT:    mov sp, r4
; CHECK-7A-NEXT:    movw r0, :lower16:(L___stack_chk_guard$non_lazy_ptr-(LPC1_0+4))
; CHECK-7A-NEXT:    movt r0, :upper16:(L___stack_chk_guard$non_lazy_ptr-(LPC1_0+4))
; CHECK-7A-NEXT:  LPC1_0:
; CHECK-7A-NEXT:    add r0, pc
; CHECK-7A-NEXT:    ldr r0, [r0]
; CHECK-7A-NEXT:    ldr r0, [r0]
; CHECK-7A-NEXT:    str r0, [sp, #32]
; CHECK-7A-NEXT:    vmov.i32 q8, #0x0
; CHECK-7A-NEXT:    movs r1, #10
; CHECK-7A-NEXT:    mov r0, sp
; CHECK-7A-NEXT:    mov r2, r0
; CHECK-7A-NEXT:    vst1.64 {d16, d17}, [r2], r1
; CHECK-7A-NEXT:    vst1.16 {d16, d17}, [r2]
; CHECK-7A-NEXT:    bl _something
; CHECK-7A-NEXT:    ldr r0, [sp, #32]
; CHECK-7A-NEXT:    movw r1, :lower16:(L___stack_chk_guard$non_lazy_ptr-(LPC1_1+4))
; CHECK-7A-NEXT:    movt r1, :upper16:(L___stack_chk_guard$non_lazy_ptr-(LPC1_1+4))
; CHECK-7A-NEXT:  LPC1_1:
; CHECK-7A-NEXT:    add r1, pc
; CHECK-7A-NEXT:    ldr r1, [r1]
; CHECK-7A-NEXT:    ldr r1, [r1]
; CHECK-7A-NEXT:    cmp r1, r0
; CHECK-7A-NEXT:    ittt eq
; CHECK-7A-NEXT:    subeq r4, r7, #4
; CHECK-7A-NEXT:    moveq sp, r4
; CHECK-7A-NEXT:    popeq {r4, r7, pc}
; CHECK-7A-NEXT:  LBB1_1: @ %entry
; CHECK-7A-NEXT:    bl ___stack_chk_fail
;
; CHECK-6M-LABEL: t2:
; CHECK-6M:       @ %bb.0: @ %entry
; CHECK-6M-NEXT:    push {r7, lr}
; CHECK-6M-NEXT:    sub sp, #32
; CHECK-6M-NEXT:    ldr r0, .LCPI1_0
; CHECK-6M-NEXT:    ldr r0, [r0]
; CHECK-6M-NEXT:    str r0, [sp, #28]
; CHECK-6M-NEXT:    mov r0, sp
; CHECK-6M-NEXT:    movs r1, #0
; CHECK-6M-NEXT:    strh r1, [r0, #24]
; CHECK-6M-NEXT:    str r1, [sp]
; CHECK-6M-NEXT:    str r1, [sp, #4]
; CHECK-6M-NEXT:    str r1, [sp, #8]
; CHECK-6M-NEXT:    str r1, [sp, #12]
; CHECK-6M-NEXT:    str r1, [sp, #16]
; CHECK-6M-NEXT:    str r1, [sp, #20]
; CHECK-6M-NEXT:    bl something
; CHECK-6M-NEXT:    ldr r0, [sp, #28]
; CHECK-6M-NEXT:    ldr r1, .LCPI1_0
; CHECK-6M-NEXT:    ldr r1, [r1]
; CHECK-6M-NEXT:    cmp r1, r0
; CHECK-6M-NEXT:    bne .LBB1_2
; CHECK-6M-NEXT:  @ %bb.1: @ %entry
; CHECK-6M-NEXT:    add sp, #32
; CHECK-6M-NEXT:    pop {r7, pc}
; CHECK-6M-NEXT:  .LBB1_2: @ %entry
; CHECK-6M-NEXT:    bl __stack_chk_fail
; CHECK-6M-NEXT:    .p2align 2
; CHECK-6M-NEXT:  @ %bb.3:
; CHECK-6M-NEXT:  .LCPI1_0:
; CHECK-6M-NEXT:    .long __stack_chk_guard
entry:
  %buf = alloca [26 x i8], align 1
  call void @llvm.memset.p0.i32(ptr %buf, i8 0, i32 26, i1 false)
  call void @something(ptr %buf) nounwind
  ret void
}

define void @t3(ptr %p) {
; CHECK-7A-LABEL: t3:
; CHECK-7A:       @ %bb.0: @ %entry
; CHECK-7A-NEXT:    push {r4, r5, lr}
; CHECK-7A-NEXT:    mov r4, r0
; CHECK-7A-NEXT:    movs r5, #0
; CHECK-7A-NEXT:  LBB2_1: @ %for.body
; CHECK-7A-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-7A-NEXT:    uxtb r0, r5
; CHECK-7A-NEXT:    orr.w r0, r0, r0, lsl #8
; CHECK-7A-NEXT:    orr.w r0, r0, r0, lsl #16
; CHECK-7A-NEXT:    str r0, [r4]
; CHECK-7A-NEXT:    mov r0, r4
; CHECK-7A-NEXT:    bl _something
; CHECK-7A-NEXT:    adds r5, #1
; CHECK-7A-NEXT:    cmp r5, #255
; CHECK-7A-NEXT:    bne LBB2_1
; CHECK-7A-NEXT:  @ %bb.2: @ %for.end
; CHECK-7A-NEXT:    pop {r4, r5, pc}
;
; CHECK-6M-LABEL: t3:
; CHECK-6M:       @ %bb.0: @ %entry
; CHECK-6M-NEXT:    push {r4, r5, r7, lr}
; CHECK-6M-NEXT:    mov r4, r0
; CHECK-6M-NEXT:    movs r5, #0
; CHECK-6M-NEXT:  .LBB2_1: @ %for.body
; CHECK-6M-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-6M-NEXT:    strb r5, [r4, #3]
; CHECK-6M-NEXT:    strb r5, [r4, #2]
; CHECK-6M-NEXT:    strb r5, [r4, #1]
; CHECK-6M-NEXT:    strb r5, [r4]
; CHECK-6M-NEXT:    mov r0, r4
; CHECK-6M-NEXT:    bl something
; CHECK-6M-NEXT:    adds r5, r5, #1
; CHECK-6M-NEXT:    cmp r5, #255
; CHECK-6M-NEXT:    bne .LBB2_1
; CHECK-6M-NEXT:  @ %bb.2: @ %for.end
; CHECK-6M-NEXT:    pop {r4, r5, r7, pc}
entry:
  br label %for.body

for.body:
  %i = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %0 = trunc i32 %i to i8
  call void @llvm.memset.p0.i32(ptr %p, i8 %0, i32 4, i1 false)
  call void @something(ptr %p)
  %inc = add nuw nsw i32 %i, 1
  %exitcond = icmp eq i32 %inc, 255
  br i1 %exitcond, label %for.end, label %for.body

for.end:
  ret void
}

define void @t4(ptr %p) {
; CHECK-7A-LABEL: t4:
; CHECK-7A:       @ %bb.0: @ %entry
; CHECK-7A-NEXT:    push {r4, r5, lr}
; CHECK-7A-NEXT:    mov r4, r0
; CHECK-7A-NEXT:    movs r5, #0
; CHECK-7A-NEXT:  LBB3_1: @ %for.body
; CHECK-7A-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-7A-NEXT:    uxtb r0, r5
; CHECK-7A-NEXT:    orr.w r0, r0, r0, lsl #8
; CHECK-7A-NEXT:    orr.w r0, r0, r0, lsl #16
; CHECK-7A-NEXT:    str r0, [r4]
; CHECK-7A-NEXT:    mov r0, r4
; CHECK-7A-NEXT:    bl _something
; CHECK-7A-NEXT:    adds r5, #1
; CHECK-7A-NEXT:    cmp r5, #255
; CHECK-7A-NEXT:    bne LBB3_1
; CHECK-7A-NEXT:  @ %bb.2: @ %for.end
; CHECK-7A-NEXT:    pop {r4, r5, pc}
;
; CHECK-6M-LABEL: t4:
; CHECK-6M:       @ %bb.0: @ %entry
; CHECK-6M-NEXT:    push {r4, r5, r7, lr}
; CHECK-6M-NEXT:    mov r4, r0
; CHECK-6M-NEXT:    movs r5, #0
; CHECK-6M-NEXT:  .LBB3_1: @ %for.body
; CHECK-6M-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-6M-NEXT:    uxtb r0, r5
; CHECK-6M-NEXT:    movs r1, #255
; CHECK-6M-NEXT:    adds r1, #2
; CHECK-6M-NEXT:    muls r1, r0, r1
; CHECK-6M-NEXT:    strh r1, [r4, #2]
; CHECK-6M-NEXT:    strh r1, [r4]
; CHECK-6M-NEXT:    mov r0, r4
; CHECK-6M-NEXT:    bl something
; CHECK-6M-NEXT:    adds r5, r5, #1
; CHECK-6M-NEXT:    cmp r5, #255
; CHECK-6M-NEXT:    bne .LBB3_1
; CHECK-6M-NEXT:  @ %bb.2: @ %for.end
; CHECK-6M-NEXT:    pop {r4, r5, r7, pc}
entry:
  br label %for.body

for.body:
  %i = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %0 = trunc i32 %i to i8
  call void @llvm.memset.p0.i32(ptr align 2 %p, i8 %0, i32 4, i1 false)
  call void @something(ptr %p)
  %inc = add nuw nsw i32 %i, 1
  %exitcond = icmp eq i32 %inc, 255
  br i1 %exitcond, label %for.end, label %for.body

for.end:
  ret void
}

declare void @something(ptr) nounwind
declare void @llvm.memset.p0.i32(ptr nocapture, i8, i32, i1) nounwind
declare void @llvm.memset.p0.i64(ptr nocapture, i8, i64, i1) nounwind
