; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc %s -o - -mtriple=armv8-unknown -mattr=-fuse-literals,+use-misched | FileCheck %s --check-prefix=CHECK --check-prefix=CHECKDONT
; RUN: llc %s -o - -mtriple=armv8-unknown -mattr=+fuse-literals,+use-misched | FileCheck %s --check-prefix=CHECK --check-prefix=CHECKFUSE

@g = common global ptr zeroinitializer

define ptr @litp(i32 %a, i32 %b) {
; CHECKDONT-LABEL: litp:
; CHECKDONT:       @ %bb.0: @ %entry
; CHECKDONT-NEXT:    add r1, r1, r0
; CHECKDONT-NEXT:    movw r2, :lower16:litp
; CHECKDONT-NEXT:    movw r0, :lower16:g
; CHECKDONT-NEXT:    movt r2, :upper16:litp
; CHECKDONT-NEXT:    movt r0, :upper16:g
; CHECKDONT-NEXT:    add r2, r2, r1, lsl #2
; CHECKDONT-NEXT:    str r2, [r0], r1, lsl #2
; CHECKDONT-NEXT:    bx lr
;
; CHECKFUSE-LABEL: litp:
; CHECKFUSE:       @ %bb.0: @ %entry
; CHECKFUSE-NEXT:    add r1, r1, r0
; CHECKFUSE-NEXT:    movw r2, :lower16:litp
; CHECKFUSE-NEXT:    movt r2, :upper16:litp
; CHECKFUSE-NEXT:    movw r0, :lower16:g
; CHECKFUSE-NEXT:    movt r0, :upper16:g
; CHECKFUSE-NEXT:    add r2, r2, r1, lsl #2
; CHECKFUSE-NEXT:    str r2, [r0], r1, lsl #2
; CHECKFUSE-NEXT:    bx lr
entry:
  %add = add nsw i32 %b, %a
  %ptr = getelementptr i32, ptr @litp, i32 %add
  %res = getelementptr i32, ptr @g, i32 %add
  store ptr %ptr, ptr @g, align 4
  ret ptr %res

}

define i32 @liti(i32 %a, i32 %b) {
; CHECKDONT-LABEL: liti:
; CHECKDONT:       @ %bb.0: @ %entry
; CHECKDONT-NEXT:    movw r2, :lower16:g
; CHECKDONT-NEXT:    movw r12, #48879
; CHECKDONT-NEXT:    movw r3, #309
; CHECKDONT-NEXT:    add r1, r1, r0
; CHECKDONT-NEXT:    movt r2, :upper16:g
; CHECKDONT-NEXT:    movt r12, #61536
; CHECKDONT-NEXT:    movt r3, #1848
; CHECKDONT-NEXT:    add r0, r1, r3
; CHECKDONT-NEXT:    add r1, r1, r12
; CHECKDONT-NEXT:    str r1, [r2]
; CHECKDONT-NEXT:    bx lr
;
; CHECKFUSE-LABEL: liti:
; CHECKFUSE:       @ %bb.0: @ %entry
; CHECKFUSE-NEXT:    add r1, r1, r0
; CHECKFUSE-NEXT:    movw r2, :lower16:g
; CHECKFUSE-NEXT:    movt r2, :upper16:g
; CHECKFUSE-NEXT:    movw r12, #48879
; CHECKFUSE-NEXT:    movt r12, #61536
; CHECKFUSE-NEXT:    movw r3, #309
; CHECKFUSE-NEXT:    movt r3, #1848
; CHECKFUSE-NEXT:    add r0, r1, r3
; CHECKFUSE-NEXT:    add r1, r1, r12
; CHECKFUSE-NEXT:    str r1, [r2]
; CHECKFUSE-NEXT:    bx lr
entry:
  %adda = add i32 %a, -262095121
  %add1 = add i32 %adda, %b
  %addb = add i32 %b, 121110837
  %add2 = add i32 %addb, %a
  store i32 %add1, ptr @g, align 4
  ret i32 %add2

}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
