; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -o - %s | FileCheck %s
target triple = "arm-unknown-unknown"

; select with and i1/or i1 condition should be implemented as a series of 2
; cmovs, not by producing two conditions and using and on them.

define i32 @select_and(i32 %a0, i32 %a1, i32 %a2, i32 %a3, i32 %a4, i32 %a5) {
; CHECK-LABEL: select_and:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    push {r11, lr}
; CHECK-NEXT:    add lr, sp, #12
; CHECK-NEXT:    add r12, sp, #8
; CHECK-NEXT:    cmp r2, r3
; CHECK-NEXT:    movhs r12, lr
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    movhs r12, lr
; CHECK-NEXT:    ldr r0, [r12]
; CHECK-NEXT:    pop {r11, lr}
; CHECK-NEXT:    mov pc, lr
  %cmp0 = icmp ult i32 %a0, %a1
  %cmp1 = icmp ult i32 %a2, %a3
  %and = and i1 %cmp0, %cmp1
  %res = select i1 %and, i32 %a4, i32 %a5
  ret i32 %res
}

define i32 @select_or(i32 %a0, i32 %a1, i32 %a2, i32 %a3, i32 %a4, i32 %a5) {
; select with and i1 condition should be implemented as a series of 2 cmovs, not
; by producing two conditions and using and on them.
; CHECK-LABEL: select_or:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    push {r11, lr}
; CHECK-NEXT:    add r12, sp, #8
; CHECK-NEXT:    add lr, sp, #12
; CHECK-NEXT:    cmp r2, r3
; CHECK-NEXT:    movlo lr, r12
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    movlo lr, r12
; CHECK-NEXT:    ldr r0, [lr]
; CHECK-NEXT:    pop {r11, lr}
; CHECK-NEXT:    mov pc, lr
  %cmp0 = icmp ult i32 %a0, %a1
  %cmp1 = icmp ult i32 %a2, %a3
  %and = or i1 %cmp0, %cmp1
  %res = select i1 %and, i32 %a4, i32 %a5
  ret i32 %res
}

; If one of the conditions is materialized as a 0/1 value anyway, then the
; sequence of 2 cmovs should not be used.

@var32 = global i32 0
define i32 @select_noopt(i32 %a0, i32 %a1, i32 %a2, i32 %a3, i32 %a4) {
; CHECK-LABEL: select_noopt:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r12, #0
; CHECK-NEXT:    cmp r1, r2
; CHECK-NEXT:    movlo r12, #1
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    ldr r0, .LCPI2_0
; CHECK-NEXT:    movlo r12, #1
; CHECK-NEXT:    cmp r12, #0
; CHECK-NEXT:    str r12, [r0]
; CHECK-NEXT:    ldr r0, [sp]
; CHECK-NEXT:    movne r0, r3
; CHECK-NEXT:    mov pc, lr
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  @ %bb.1:
; CHECK-NEXT:  .LCPI2_0:
; CHECK-NEXT:    .long var32
  %cmp0 = icmp ult i32 %a0, %a1
  %cmp1 = icmp ult i32 %a1, %a2
  %or = or i1 %cmp0, %cmp1
  %zero_one = zext i1 %or to i32
  store volatile i32 %zero_one, ptr @var32
  %res = select i1 %or, i32 %a3, i32 %a4
  ret i32 %res
}
