; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=arm-eabi -mattr=+neon %s -o - | FileCheck %s

; Test ARM NEON vector CLS (Count Leading Sign bits) operations
; The intrinsics are lowered to ISD::CTLS and selected to VCLS instructions

define <8 x i8> @test_cls_v8i8(<8 x i8> %a) nounwind {
; CHECK-LABEL: test_cls_v8i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vmov d16, r0, r1
; CHECK-NEXT:    vcls.s8 d16, d16
; CHECK-NEXT:    vmov r0, r1, d16
; CHECK-NEXT:    mov pc, lr
  %result = call <8 x i8> @llvm.arm.neon.vcls.v8i8(<8 x i8> %a)
  ret <8 x i8> %result
}

define <16 x i8> @test_cls_v16i8(<16 x i8> %a) nounwind {
; CHECK-LABEL: test_cls_v16i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vmov d17, r2, r3
; CHECK-NEXT:    vmov d16, r0, r1
; CHECK-NEXT:    vcls.s8 q8, q8
; CHECK-NEXT:    vmov r0, r1, d16
; CHECK-NEXT:    vmov r2, r3, d17
; CHECK-NEXT:    mov pc, lr
  %result = call <16 x i8> @llvm.arm.neon.vcls.v16i8(<16 x i8> %a)
  ret <16 x i8> %result
}

define <4 x i16> @test_cls_v4i16(<4 x i16> %a) nounwind {
; CHECK-LABEL: test_cls_v4i16:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vmov d16, r0, r1
; CHECK-NEXT:    vcls.s16 d16, d16
; CHECK-NEXT:    vmov r0, r1, d16
; CHECK-NEXT:    mov pc, lr
  %result = call <4 x i16> @llvm.arm.neon.vcls.v4i16(<4 x i16> %a)
  ret <4 x i16> %result
}

define <8 x i16> @test_cls_v8i16(<8 x i16> %a) nounwind {
; CHECK-LABEL: test_cls_v8i16:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vmov d17, r2, r3
; CHECK-NEXT:    vmov d16, r0, r1
; CHECK-NEXT:    vcls.s16 q8, q8
; CHECK-NEXT:    vmov r0, r1, d16
; CHECK-NEXT:    vmov r2, r3, d17
; CHECK-NEXT:    mov pc, lr
  %result = call <8 x i16> @llvm.arm.neon.vcls.v8i16(<8 x i16> %a)
  ret <8 x i16> %result
}

define <2 x i32> @test_cls_v2i32(<2 x i32> %a) nounwind {
; CHECK-LABEL: test_cls_v2i32:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vmov d16, r0, r1
; CHECK-NEXT:    vcls.s32 d16, d16
; CHECK-NEXT:    vmov r0, r1, d16
; CHECK-NEXT:    mov pc, lr
  %result = call <2 x i32> @llvm.arm.neon.vcls.v2i32(<2 x i32> %a)
  ret <2 x i32> %result
}

define <4 x i32> @test_cls_v4i32(<4 x i32> %a) nounwind {
; CHECK-LABEL: test_cls_v4i32:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vmov d17, r2, r3
; CHECK-NEXT:    vmov d16, r0, r1
; CHECK-NEXT:    vcls.s32 q8, q8
; CHECK-NEXT:    vmov r0, r1, d16
; CHECK-NEXT:    vmov r2, r3, d17
; CHECK-NEXT:    mov pc, lr
  %result = call <4 x i32> @llvm.arm.neon.vcls.v4i32(<4 x i32> %a)
  ret <4 x i32> %result
}

declare <8 x i8> @llvm.arm.neon.vcls.v8i8(<8 x i8>) nounwind readnone
declare <16 x i8> @llvm.arm.neon.vcls.v16i8(<16 x i8>) nounwind readnone
declare <4 x i16> @llvm.arm.neon.vcls.v4i16(<4 x i16>) nounwind readnone
declare <8 x i16> @llvm.arm.neon.vcls.v8i16(<8 x i16>) nounwind readnone
declare <2 x i32> @llvm.arm.neon.vcls.v2i32(<2 x i32>) nounwind readnone
declare <4 x i32> @llvm.arm.neon.vcls.v4i32(<4 x i32>) nounwind readnone
