# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=thumbv8m.main-none-eabi -run-pass=peephole-opt -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple=thumbv8m.main-none-eabi -passes=peephole-opt -verify-machineinstrs %s -o - | FileCheck %s

# Hand-written MIR for ARMBaseInstrInfo::optimizeCompareInstr / isOptimizeCompareCandidate:
# folded compare-with-zero after t2ADCrs (Thumb2 shifted-register ADC).

--- |
  target datalayout = "e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64"
  target triple = "thumbv8m.main-none-eabi"

  define void @thumb2_t2adcrs_cmp_fold() { ret void }
...
---
name:            thumb2_t2adcrs_cmp_fold
alignment:       2
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: thumb2_t2adcrs_cmp_fold
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $r0, $r1, $cpsr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:rgpr = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:rgpr = COPY $r1
  ; CHECK-NEXT:   [[t2ADCrs:%[0-9]+]]:rgpr = t2ADCrs [[COPY]], [[COPY1]], 19, 14 /* CC::al */, $noreg, def $cpsr, implicit $cpsr, implicit-def $cpsr
  ; CHECK-NEXT:   t2Bcc %bb.1, 0 /* CC::eq */, $cpsr
  ; CHECK-NEXT:   t2B %bb.2, 14 /* CC::al */, $noreg
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[t2MOVi:%[0-9]+]]:rgpr = t2MOVi 1, 14 /* CC::al */, $noreg, $noreg
  ; CHECK-NEXT:   $r0 = COPY [[t2MOVi]]
  ; CHECK-NEXT:   tBX_RET 14 /* CC::al */, $noreg, implicit $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   [[t2MOVi1:%[0-9]+]]:rgpr = t2MOVi 0, 14 /* CC::al */, $noreg, $noreg
  ; CHECK-NEXT:   $r0 = COPY [[t2MOVi1]]
  ; CHECK-NEXT:   tBX_RET 14 /* CC::al */, $noreg, implicit $r0
  bb.0:
    liveins: $r0, $r1, $cpsr
    successors: %bb.1(0x40000000), %bb.2(0x40000000)

    %0:rgpr = COPY $r0
    %1:rgpr = COPY $r1
    %2:rgpr = t2ADCrs %0, %1, 19, 14, $noreg, $noreg, implicit $cpsr, implicit-def $cpsr
    t2CMPri %2, 0, 14, $noreg, implicit-def $cpsr
    t2Bcc %bb.1, 0, $cpsr
    t2B %bb.2, 14, $noreg

  bb.1:
    successors: %bb.2(0x80000000)
    %3:rgpr = t2MOVi 1, 14, $noreg, $noreg
    $r0 = COPY %3
    tBX_RET 14, $noreg, implicit $r0

  bb.2:
    %4:rgpr = t2MOVi 0, 14, $noreg, $noreg
    $r0 = COPY %4
    tBX_RET 14, $noreg, implicit $r0

...
