# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=armv7-none-eabi -run-pass=peephole-opt -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple=armv7-none-eabi -passes=peephole-opt -verify-machineinstrs %s -o - | FileCheck %s

# Hand-written MIR for ARMBaseInstrInfo::optimizeCompareInstr / isOptimizeCompareCandidate:
# folded compare-with-zero after ADCrsi / ADCrsr (optional CPSR slot toggled on the ADC).

--- |
  target datalayout = "e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64"
  target triple = "armv7-none-eabi"

  define void @arm_adcrsi_cmp_fold() { ret void }
  define void @arm_adcrsr_cmp_fold() { ret void }
...
---
name:            arm_adcrsi_cmp_fold
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: arm_adcrsi_cmp_fold
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $r0, $r1, $cpsr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $r1
  ; CHECK-NEXT:   [[ADCrsi:%[0-9]+]]:gpr = ADCrsi [[COPY]], [[COPY1]], 234, 14 /* CC::al */, $noreg, $noreg, implicit $cpsr, implicit-def $cpsr
  ; CHECK-NEXT:   CMPri [[ADCrsi]], 0, 14 /* CC::al */, $noreg, implicit-def $cpsr
  ; CHECK-NEXT:   Bcc %bb.1, 0 /* CC::eq */, $cpsr
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVi:%[0-9]+]]:gpr = MOVi 1, 14 /* CC::al */, $noreg, $noreg
  ; CHECK-NEXT:   $r0 = COPY [[MOVi]]
  ; CHECK-NEXT:   BX_RET 14 /* CC::al */, $noreg, implicit $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   [[MOVi1:%[0-9]+]]:gpr = MOVi 0, 14 /* CC::al */, $noreg, $noreg
  ; CHECK-NEXT:   $r0 = COPY [[MOVi1]]
  ; CHECK-NEXT:   BX_RET 14 /* CC::al */, $noreg, implicit $r0
  bb.0:
    liveins: $r0, $r1, $cpsr
    successors: %bb.1(0x40000000), %bb.2(0x40000000)

    %0:gpr = COPY $r0
    %1:gpr = COPY $r1
    %2:gpr = ADCrsi %0, %1, 234, 14, $noreg, $noreg, implicit $cpsr, implicit-def $cpsr
    CMPri %2, 0, 14, $noreg, implicit-def $cpsr
    Bcc %bb.1, 0, $cpsr
    B %bb.2

  bb.1:
    successors: %bb.2(0x80000000)
    %3:gpr = MOVi 1, 14, $noreg, $noreg
    $r0 = COPY %3
    BX_RET 14, $noreg, implicit $r0

  bb.2:
    %4:gpr = MOVi 0, 14, $noreg, $noreg
    $r0 = COPY %4
    BX_RET 14, $noreg, implicit $r0

...
---
name:            arm_adcrsr_cmp_fold
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: arm_adcrsr_cmp_fold
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $r0, $r1, $r2, $cpsr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gprnopc = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gprnopc = COPY $r1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gprnopc = COPY $r2
  ; CHECK-NEXT:   [[ADCrsr:%[0-9]+]]:gprnopc = ADCrsr [[COPY]], [[COPY1]], [[COPY2]], 2, 14 /* CC::al */, $noreg, $noreg, implicit $cpsr, implicit-def $cpsr
  ; CHECK-NEXT:   CMPri [[ADCrsr]], 0, 14 /* CC::al */, $noreg, implicit-def $cpsr
  ; CHECK-NEXT:   Bcc %bb.1, 0 /* CC::eq */, $cpsr
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVi:%[0-9]+]]:gpr = MOVi 1, 14 /* CC::al */, $noreg, $noreg
  ; CHECK-NEXT:   $r0 = COPY [[MOVi]]
  ; CHECK-NEXT:   BX_RET 14 /* CC::al */, $noreg, implicit $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   [[MOVi1:%[0-9]+]]:gpr = MOVi 0, 14 /* CC::al */, $noreg, $noreg
  ; CHECK-NEXT:   $r0 = COPY [[MOVi1]]
  ; CHECK-NEXT:   BX_RET 14 /* CC::al */, $noreg, implicit $r0
  bb.0:
    liveins: $r0, $r1, $r2, $cpsr
    successors: %bb.1(0x40000000), %bb.2(0x40000000)

    %0:gprnopc = COPY $r0
    %1:gprnopc = COPY $r1
    %2:gprnopc = COPY $r2
    %3:gprnopc = ADCrsr %0, %1, %2, 2, 14, $noreg, $noreg, implicit $cpsr, implicit-def $cpsr
    CMPri %3, 0, 14, $noreg, implicit-def $cpsr
    Bcc %bb.1, 0, $cpsr
    B %bb.2

  bb.1:
    successors: %bb.2(0x80000000)
    %4:gpr = MOVi 1, 14, $noreg, $noreg
    $r0 = COPY %4
    BX_RET 14, $noreg, implicit $r0

  bb.2:
    %5:gpr = MOVi 0, 14, $noreg, $noreg
    $r0 = COPY %5
    BX_RET 14, $noreg, implicit $r0

...
