# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=armv7-apple-ios -run-pass=postra-machine-sink -o - %s | FileCheck %s

---
name:            test_undef_use_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_undef_use_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r0 = MOVi 1, 14 /* CC::al */, $noreg, $noreg
  ; CHECK-NEXT:   renamable $r1 = COPY killed renamable $r0, implicit undef $r2
  ; CHECK-NEXT:   $r2 = MOVi 0, 14 /* CC::al */, $noreg, $noreg
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BX_RET 14 /* CC::al */, $noreg, implicit $r1
  bb.0:
    successors: %bb.1

    renamable $r0 = MOVi 1, 14, $noreg, $noreg
    renamable $r1 = COPY killed renamable $r0, implicit undef $r2
    $r2 = MOVi 0, 14, $noreg, $noreg

  bb.1:
    liveins: $r1
    BX_RET 14, $noreg, implicit $r1
...
---
name:            test_internal_read_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_internal_read_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r0 = MOVi 1, 14 /* CC::al */, $noreg, $noreg
  ; CHECK-NEXT:   renamable $r1 = COPY killed renamable $r0, implicit-def $r2, implicit internal $r2
  ; CHECK-NEXT:   $r3 = MOVi 0, 14 /* CC::al */, $noreg, $noreg
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $r1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BX_RET 14 /* CC::al */, $noreg, implicit $r1
  bb.0:
    successors: %bb.1

    renamable $r0 = MOVi 1, 14, $noreg, $noreg
    renamable $r1 = COPY killed renamable $r0, implicit-def $r2, implicit internal $r2
    $r3 = MOVi 0, 14, $noreg, $noreg

  bb.1:
    liveins: $r1
    BX_RET 14, $noreg, implicit $r1
...
