# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=arm-apple-ios -enable-subreg-liveness -verify-machineinstrs -start-before=register-coalescer -stop-after=register-coalescer %s -o - | FileCheck %s

# Coalescing can erase an undef PHI input from a subrange while preserving the
# value in a different lane. The coalescer must materialize an IMPLICIT_DEF for
# the missing lane in the predecessor where the PHI input is undef.

---
name: test
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: test
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $d0, $d2, $d4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   undef [[COPY:%[0-9]+]].dsub_0:qpr = COPY $d0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]].dsub_1:qpr = COPY $d2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:dpr = COPY $d4
  ; CHECK-NEXT:   tB %bb.1, 14 /* CC::al */, $noreg
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gprnopc = IMPLICIT_DEF
  ; CHECK-NEXT:   t2CMPri [[DEF]], 0, 14 /* CC::al */, $noreg, implicit-def $cpsr
  ; CHECK-NEXT:   t2Bcc %bb.3, 0 /* CC::eq */, killed $cpsr
  ; CHECK-NEXT:   tB %bb.2, 14 /* CC::al */, $noreg
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   tB %bb.5, 14 /* CC::al */, $noreg
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.6(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   KILL implicit [[COPY]].dsub_0
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:gprnopc = IMPLICIT_DEF
  ; CHECK-NEXT:   t2CMPri [[DEF1]], 0, 14 /* CC::al */, $noreg, implicit-def $cpsr
  ; CHECK-NEXT:   Bcc %bb.4, 1 /* CC::ne */, killed $cpsr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   undef [[COPY:%[0-9]+]].dsub_1:qpr = IMPLICIT_DEF
  ; CHECK-NEXT:   B %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   undef [[COPY:%[0-9]+]].dsub_1:qpr = COPY [[COPY1]]
  ; CHECK-NEXT:   tB %bb.5, 14 /* CC::al */, $noreg
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   tBX_RET 14 /* CC::al */, $noreg, implicit [[COPY]].dsub_1
  bb.0:
    successors: %bb.1
    liveins: $d0, $d2, $d4

    %0:dpr = COPY $d0
    %7:dpr = COPY $d2
    %8:dpr = COPY $d4
    undef %1.dsub_0:qpr = COPY %0
    tB %bb.1, 14, $noreg

  bb.1:
    successors: %bb.2, %bb.3

    %5:gprnopc = IMPLICIT_DEF
    t2CMPri %5, 0, 14, $noreg, implicit-def $cpsr
    t2Bcc %bb.3, 0, killed $cpsr
    tB %bb.2, 14, $noreg

  bb.2:
    successors: %bb.5

    %1.dsub_1:qpr = COPY %7
    %2:dpr = COPY %1.dsub_1
    tB %bb.5, 14, $noreg

  bb.3:
    successors: %bb.5, %bb.4

    %2:dpr = IMPLICIT_DEF
    KILL implicit %1.dsub_0
    %6:gprnopc = IMPLICIT_DEF
    t2CMPri %6, 0, 14, $noreg, implicit-def $cpsr
    t2Bcc %bb.5, 0, killed $cpsr
    tB %bb.4, 14, $noreg

  bb.4:
    successors: %bb.5

    %3:dpr = COPY %8
    %2:dpr = COPY %3
    tB %bb.5, 14, $noreg

  bb.5:
    %4:dpr = COPY %2
    tBX_RET 14, $noreg, implicit %4

...
