; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=armv7-none-linux-gnu | FileCheck --check-prefix=CHECK-ARM %s
; RUN: llc < %s -mtriple=thumbv7-none-linux-gnu | FileCheck --check-prefix=CHECK-THUMB2 %s

define i32 @test_basic_i32(i32 %a, i32 %b, i32 %x, i32 %y) {
; CHECK-ARM-LABEL: test_basic_i32:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    sub r2, r2, r3
; CHECK-ARM-NEXT:    cmp r0, r1
; CHECK-ARM-NEXT:    sublo r2, r2, #1
; CHECK-ARM-NEXT:    mov r0, r2
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB2-LABEL: test_basic_i32:
; CHECK-THUMB2:       @ %bb.0:
; CHECK-THUMB2-NEXT:    subs r2, r2, r3
; CHECK-THUMB2-NEXT:    cmp r0, r1
; CHECK-THUMB2-NEXT:    it lo
; CHECK-THUMB2-NEXT:    sublo r2, #1
; CHECK-THUMB2-NEXT:    mov r0, r2
; CHECK-THUMB2-NEXT:    bx lr
  %cc = icmp ult i32 %a, %b
  %carry = zext i1 %cc to i32
  %sub = sub i32 %x, %y
  %res = sub i32 %sub, %carry
  ret i32 %res
}

define i32 @test_only_borrow(i32 %a, i32 %b, i32 %x) {
; CHECK-ARM-LABEL: test_only_borrow:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    cmp r0, r1
; CHECK-ARM-NEXT:    sublo r2, r2, #1
; CHECK-ARM-NEXT:    mov r0, r2
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB2-LABEL: test_only_borrow:
; CHECK-THUMB2:       @ %bb.0:
; CHECK-THUMB2-NEXT:    cmp r0, r1
; CHECK-THUMB2-NEXT:    it lo
; CHECK-THUMB2-NEXT:    sublo r2, #1
; CHECK-THUMB2-NEXT:    mov r0, r2
; CHECK-THUMB2-NEXT:    bx lr
  %cc = icmp ult i32 %a, %b
  %carry = zext i1 %cc to i32
  %res = sub i32 %x, %carry
  ret i32 %res
}

define i32 @test_sext_add(i32 %a, i32 %b, i32 %x, i32 %y) {
; CHECK-ARM-LABEL: test_sext_add:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    sub r2, r2, r3
; CHECK-ARM-NEXT:    cmp r0, r1
; CHECK-ARM-NEXT:    sublo r2, r2, #1
; CHECK-ARM-NEXT:    mov r0, r2
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB2-LABEL: test_sext_add:
; CHECK-THUMB2:       @ %bb.0:
; CHECK-THUMB2-NEXT:    subs r2, r2, r3
; CHECK-THUMB2-NEXT:    cmp r0, r1
; CHECK-THUMB2-NEXT:    it lo
; CHECK-THUMB2-NEXT:    sublo r2, #1
; CHECK-THUMB2-NEXT:    mov r0, r2
; CHECK-THUMB2-NEXT:    bx lr
  %cc = icmp ult i32 %a, %b
  %carry = sext i1 %cc to i32
  %sub = sub i32 %x, %y
  %res = add i32 %sub, %carry
  ret i32 %res
}

; FIXME: This case could be supported with reversed operands to the CMP.
define i32 @test_ugt(i32 %a, i32 %b, i32 %x, i32 %y) {
; CHECK-ARM-LABEL: test_ugt:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    sub r2, r2, r3
; CHECK-ARM-NEXT:    cmp r0, r1
; CHECK-ARM-NEXT:    subhi r2, r2, #1
; CHECK-ARM-NEXT:    mov r0, r2
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB2-LABEL: test_ugt:
; CHECK-THUMB2:       @ %bb.0:
; CHECK-THUMB2-NEXT:    subs r2, r2, r3
; CHECK-THUMB2-NEXT:    cmp r0, r1
; CHECK-THUMB2-NEXT:    it hi
; CHECK-THUMB2-NEXT:    subhi r2, #1
; CHECK-THUMB2-NEXT:    mov r0, r2
; CHECK-THUMB2-NEXT:    bx lr
  %cc = icmp ugt i32 %a, %b
  %carry = zext i1 %cc to i32
  %sub = sub i32 %x, %y
  %res = sub i32 %sub, %carry
  ret i32 %res
}

define i32 @test_unsupported_cc_slt(i32 %a, i32 %b, i32 %x, i32 %y) {
; CHECK-ARM-LABEL: test_unsupported_cc_slt:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    sub r2, r2, r3
; CHECK-ARM-NEXT:    cmp r0, r1
; CHECK-ARM-NEXT:    sublt r2, r2, #1
; CHECK-ARM-NEXT:    mov r0, r2
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB2-LABEL: test_unsupported_cc_slt:
; CHECK-THUMB2:       @ %bb.0:
; CHECK-THUMB2-NEXT:    subs r2, r2, r3
; CHECK-THUMB2-NEXT:    cmp r0, r1
; CHECK-THUMB2-NEXT:    it lt
; CHECK-THUMB2-NEXT:    sublt r2, #1
; CHECK-THUMB2-NEXT:    mov r0, r2
; CHECK-THUMB2-NEXT:    bx lr
  %cc = icmp slt i32 %a, %b
  %carry = zext i1 %cc to i32
  %sub = sub i32 %x, %y
  %res = sub i32 %sub, %carry
  ret i32 %res
}

define i32 @test_unsupported_cc_sgt(i32 %a, i32 %b, i32 %x, i32 %y) {
; CHECK-ARM-LABEL: test_unsupported_cc_sgt:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    sub r2, r2, r3
; CHECK-ARM-NEXT:    cmp r0, r1
; CHECK-ARM-NEXT:    subgt r2, r2, #1
; CHECK-ARM-NEXT:    mov r0, r2
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB2-LABEL: test_unsupported_cc_sgt:
; CHECK-THUMB2:       @ %bb.0:
; CHECK-THUMB2-NEXT:    subs r2, r2, r3
; CHECK-THUMB2-NEXT:    cmp r0, r1
; CHECK-THUMB2-NEXT:    it gt
; CHECK-THUMB2-NEXT:    subgt r2, #1
; CHECK-THUMB2-NEXT:    mov r0, r2
; CHECK-THUMB2-NEXT:    bx lr
  %cc = icmp sgt i32 %a, %b
  %carry = zext i1 %cc to i32
  %sub = sub i32 %x, %y
  %res = sub i32 %sub, %carry
  ret i32 %res
}

define i32 @test_multiple_setcc_uses(i32 %a, i32 %b, i32 %x) {
; CHECK-ARM-LABEL: test_multiple_setcc_uses:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    push {r4, lr}
; CHECK-ARM-NEXT:    cmp r0, r1
; CHECK-ARM-NEXT:    mov r0, #0
; CHECK-ARM-NEXT:    mov r4, r2
; CHECK-ARM-NEXT:    movwlo r0, #1
; CHECK-ARM-NEXT:    sublo r4, r4, #1
; CHECK-ARM-NEXT:    bl use
; CHECK-ARM-NEXT:    mov r0, r4
; CHECK-ARM-NEXT:    pop {r4, pc}
;
; CHECK-THUMB2-LABEL: test_multiple_setcc_uses:
; CHECK-THUMB2:       @ %bb.0:
; CHECK-THUMB2-NEXT:    push {r4, lr}
; CHECK-THUMB2-NEXT:    cmp r0, r1
; CHECK-THUMB2-NEXT:    mov r4, r2
; CHECK-THUMB2-NEXT:    mov.w r0, #0
; CHECK-THUMB2-NEXT:    it lo
; CHECK-THUMB2-NEXT:    sublo r4, #1
; CHECK-THUMB2-NEXT:    it lo
; CHECK-THUMB2-NEXT:    movlo r0, #1
; CHECK-THUMB2-NEXT:    bl use
; CHECK-THUMB2-NEXT:    mov r0, r4
; CHECK-THUMB2-NEXT:    pop {r4, pc}
  %cc = icmp ult i32 %a, %b
  %carry = zext i1 %cc to i32
  %res = sub i32 %x, %carry
  tail call void @use(i1 %cc)
  ret i32 %res
}

define i32 @test_multiple_carry_uses(i32 %a, i32 %b, i32 %x) {
; CHECK-ARM-LABEL: test_multiple_carry_uses:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    push {r4, r5, r11, lr}
; CHECK-ARM-NEXT:    mov r5, #0
; CHECK-ARM-NEXT:    cmp r0, r1
; CHECK-ARM-NEXT:    movwlo r5, #1
; CHECK-ARM-NEXT:    mov r4, r2
; CHECK-ARM-NEXT:    mov r0, r5
; CHECK-ARM-NEXT:    bl use
; CHECK-ARM-NEXT:    sub r0, r4, r5
; CHECK-ARM-NEXT:    pop {r4, r5, r11, pc}
;
; CHECK-THUMB2-LABEL: test_multiple_carry_uses:
; CHECK-THUMB2:       @ %bb.0:
; CHECK-THUMB2-NEXT:    push {r4, r5, r7, lr}
; CHECK-THUMB2-NEXT:    movs r5, #0
; CHECK-THUMB2-NEXT:    cmp r0, r1
; CHECK-THUMB2-NEXT:    it lo
; CHECK-THUMB2-NEXT:    movlo r5, #1
; CHECK-THUMB2-NEXT:    mov r0, r5
; CHECK-THUMB2-NEXT:    mov r4, r2
; CHECK-THUMB2-NEXT:    bl use
; CHECK-THUMB2-NEXT:    subs r0, r4, r5
; CHECK-THUMB2-NEXT:    pop {r4, r5, r7, pc}
  %cc = icmp ult i32 %a, %b
  %carry = zext i1 %cc to i32
  %res = sub i32 %x, %carry
  tail call void @use(i32 %carry)
  ret i32 %res
}

define i32 @test_multiple_sub_uses(i32 %a, i32 %b, i32 %x, i32 %y) {
; CHECK-ARM-LABEL: test_multiple_sub_uses:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    push {r4, r5, r6, lr}
; CHECK-ARM-NEXT:    sub r6, r2, r3
; CHECK-ARM-NEXT:    mov r5, r0
; CHECK-ARM-NEXT:    mov r4, r1
; CHECK-ARM-NEXT:    mov r0, r6
; CHECK-ARM-NEXT:    bl use
; CHECK-ARM-NEXT:    cmp r5, r4
; CHECK-ARM-NEXT:    sublo r6, r6, #1
; CHECK-ARM-NEXT:    mov r0, r6
; CHECK-ARM-NEXT:    pop {r4, r5, r6, pc}
;
; CHECK-THUMB2-LABEL: test_multiple_sub_uses:
; CHECK-THUMB2:       @ %bb.0:
; CHECK-THUMB2-NEXT:    push {r4, r5, r6, lr}
; CHECK-THUMB2-NEXT:    subs r6, r2, r3
; CHECK-THUMB2-NEXT:    mov r5, r0
; CHECK-THUMB2-NEXT:    mov r4, r1
; CHECK-THUMB2-NEXT:    mov r0, r6
; CHECK-THUMB2-NEXT:    bl use
; CHECK-THUMB2-NEXT:    cmp r5, r4
; CHECK-THUMB2-NEXT:    it lo
; CHECK-THUMB2-NEXT:    sublo r6, #1
; CHECK-THUMB2-NEXT:    mov r0, r6
; CHECK-THUMB2-NEXT:    pop {r4, r5, r6, pc}
  %cc = icmp ult i32 %a, %b
  %carry = zext i1 %cc to i32
  %sub = sub i32 %x, %y
  %res = sub i32 %sub, %carry
  tail call void @use(i32 %sub)
  ret i32 %res
}

define i8 @test_i8(i8 %a, i8 %b, i8 %x, i8 %y) {
; CHECK-ARM-LABEL: test_i8:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    sub r2, r2, r3
; CHECK-ARM-NEXT:    uxtb r1, r1
; CHECK-ARM-NEXT:    uxtb r0, r0
; CHECK-ARM-NEXT:    cmp r0, r1
; CHECK-ARM-NEXT:    sublo r2, r2, #1
; CHECK-ARM-NEXT:    mov r0, r2
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB2-LABEL: test_i8:
; CHECK-THUMB2:       @ %bb.0:
; CHECK-THUMB2-NEXT:    subs r2, r2, r3
; CHECK-THUMB2-NEXT:    uxtb r0, r0
; CHECK-THUMB2-NEXT:    uxtb r1, r1
; CHECK-THUMB2-NEXT:    cmp r0, r1
; CHECK-THUMB2-NEXT:    it lo
; CHECK-THUMB2-NEXT:    sublo r2, #1
; CHECK-THUMB2-NEXT:    mov r0, r2
; CHECK-THUMB2-NEXT:    bx lr
  %cc = icmp ult i8 %a, %b
  %carry = zext i1 %cc to i8
  %sub = sub i8 %x, %y
  %res = sub i8 %sub, %carry
  ret i8 %res
}

define i16 @test_i16(i16 %a, i16 %b, i16 %x, i16 %y) {
; CHECK-ARM-LABEL: test_i16:
; CHECK-ARM:       @ %bb.0:
; CHECK-ARM-NEXT:    sub r2, r2, r3
; CHECK-ARM-NEXT:    uxth r1, r1
; CHECK-ARM-NEXT:    uxth r0, r0
; CHECK-ARM-NEXT:    cmp r0, r1
; CHECK-ARM-NEXT:    sublo r2, r2, #1
; CHECK-ARM-NEXT:    mov r0, r2
; CHECK-ARM-NEXT:    bx lr
;
; CHECK-THUMB2-LABEL: test_i16:
; CHECK-THUMB2:       @ %bb.0:
; CHECK-THUMB2-NEXT:    subs r2, r2, r3
; CHECK-THUMB2-NEXT:    uxth r0, r0
; CHECK-THUMB2-NEXT:    uxth r1, r1
; CHECK-THUMB2-NEXT:    cmp r0, r1
; CHECK-THUMB2-NEXT:    it lo
; CHECK-THUMB2-NEXT:    sublo r2, #1
; CHECK-THUMB2-NEXT:    mov r0, r2
; CHECK-THUMB2-NEXT:    bx lr
  %cc = icmp ult i16 %a, %b
  %carry = zext i1 %cc to i16
  %sub = sub i16 %x, %y
  %res = sub i16 %sub, %carry
  ret i16 %res
}

declare void @use()
