; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=armv7-unknown-linux-musleabihf -mattr=-neon %s -o - | FileCheck %s

declare fastcc noundef range(i16 0, 256) <4 x i16> @other()

define void @test(ptr %0) #0 {
; CHECK-LABEL: test:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    .save {r4, lr}
; CHECK-NEXT:    push {r4, lr}
; CHECK-NEXT:    mov r4, r0
; CHECK-NEXT:    bl other
; CHECK-NEXT:    uxth r3, r3
; CHECK-NEXT:    uxth r2, r2
; CHECK-NEXT:    uxth r1, r1
; CHECK-NEXT:    uxth r0, r0
; CHECK-NEXT:    strb r3, [r4, #3]
; CHECK-NEXT:    strb r2, [r4, #2]
; CHECK-NEXT:    strb r1, [r4, #1]
; CHECK-NEXT:    strb r0, [r4]
; CHECK-NEXT:    pop {r4, pc}
entry:
  %call = call fastcc <4 x i16> @other()
  %t = trunc <4 x i16> %call to <4 x i8>
  store <4 x i8> %t, ptr %0, align 1
  ret void
}

define <4 x i16> @test2() #0 {
; CHECK-LABEL: test2:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    .save {r11, lr}
; CHECK-NEXT:    push {r11, lr}
; CHECK-NEXT:    bl other
; CHECK-NEXT:    movw r1, #65408
; CHECK-NEXT:    and r0, r0, r1
; CHECK-NEXT:    and r2, r2, r1
; CHECK-NEXT:    mov r1, #0
; CHECK-NEXT:    mov r3, #0
; CHECK-NEXT:    pop {r11, pc}
entry:
  %call = call fastcc <4 x i16> @other()
  %a = and <4 x i16> %call, <i16 u0x80, i16 u0x100, i16 u0x80, i16 u0x100>
  ret <4 x i16> %a
}

