; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=armv7a-eabi < %s -o - | FileCheck %s --check-prefix=ARM
; RUN: llc -mtriple=thumbv6m-none-eabi < %s -o - | FileCheck %s --check-prefix=THUMB1
; RUN: llc -mtriple=thumbv7m-none-eabi < %s -o - | FileCheck %s --check-prefix=THUMB2

define i32 @test1(i32 %x) {
; ARM-LABEL: test1:
; ARM:       @ %bb.0:
; ARM-NEXT:    asr r1, r0, #31
; ARM-NEXT:    add r0, r0, r1, lsr #29
; ARM-NEXT:    asr r0, r0, #3
; ARM-NEXT:    bx lr
;
; THUMB1-LABEL: test1:
; THUMB1:       @ %bb.0:
; THUMB1-NEXT:    asrs r1, r0, #31
; THUMB1-NEXT:    lsrs r1, r1, #29
; THUMB1-NEXT:    adds r0, r0, r1
; THUMB1-NEXT:    asrs r0, r0, #3
; THUMB1-NEXT:    bx lr
;
; THUMB2-LABEL: test1:
; THUMB2:       @ %bb.0:
; THUMB2-NEXT:    asrs r1, r0, #31
; THUMB2-NEXT:    add.w r0, r0, r1, lsr #29
; THUMB2-NEXT:    asrs r0, r0, #3
; THUMB2-NEXT:    bx lr
  %div = sdiv i32 %x, 8
  ret i32 %div
}

define i32 @test2(i32 %x) {
; ARM-LABEL: test2:
; ARM:       @ %bb.0:
; ARM-NEXT:    asr r1, r0, #31
; ARM-NEXT:    add r0, r0, r1, lsr #29
; ARM-NEXT:    mov r1, #0
; ARM-NEXT:    sub r0, r1, r0, asr #3
; ARM-NEXT:    bx lr
;
; THUMB1-LABEL: test2:
; THUMB1:       @ %bb.0:
; THUMB1-NEXT:    asrs r1, r0, #31
; THUMB1-NEXT:    lsrs r1, r1, #29
; THUMB1-NEXT:    adds r0, r0, r1
; THUMB1-NEXT:    asrs r0, r0, #3
; THUMB1-NEXT:    rsbs r0, r0, #0
; THUMB1-NEXT:    bx lr
;
; THUMB2-LABEL: test2:
; THUMB2:       @ %bb.0:
; THUMB2-NEXT:    asrs r1, r0, #31
; THUMB2-NEXT:    add.w r0, r0, r1, lsr #29
; THUMB2-NEXT:    movs r1, #0
; THUMB2-NEXT:    sub.w r0, r1, r0, asr #3
; THUMB2-NEXT:    bx lr
  %div = sdiv i32 %x, -8
  ret i32 %div
}

define i32 @test3(i32 %x) {
; ARM-LABEL: test3:
; ARM:       @ %bb.0:
; ARM-NEXT:    asr r1, r0, #31
; ARM-NEXT:    add r0, r0, r1, lsr #27
; ARM-NEXT:    asr r0, r0, #5
; ARM-NEXT:    bx lr
;
; THUMB1-LABEL: test3:
; THUMB1:       @ %bb.0:
; THUMB1-NEXT:    asrs r1, r0, #31
; THUMB1-NEXT:    lsrs r1, r1, #27
; THUMB1-NEXT:    adds r0, r0, r1
; THUMB1-NEXT:    asrs r0, r0, #5
; THUMB1-NEXT:    bx lr
;
; THUMB2-LABEL: test3:
; THUMB2:       @ %bb.0:
; THUMB2-NEXT:    asrs r1, r0, #31
; THUMB2-NEXT:    add.w r0, r0, r1, lsr #27
; THUMB2-NEXT:    asrs r0, r0, #5
; THUMB2-NEXT:    bx lr
  %div = sdiv i32 %x, 32
  ret i32 %div
}

define i32 @test8(i32 %x) {
; ARM-LABEL: test8:
; ARM:       @ %bb.0:
; ARM-NEXT:    add r0, r0, r0, lsr #31
; ARM-NEXT:    asr r0, r0, #1
; ARM-NEXT:    bx lr
;
; THUMB1-LABEL: test8:
; THUMB1:       @ %bb.0:
; THUMB1-NEXT:    lsrs r1, r0, #31
; THUMB1-NEXT:    adds r0, r0, r1
; THUMB1-NEXT:    asrs r0, r0, #1
; THUMB1-NEXT:    bx lr
;
; THUMB2-LABEL: test8:
; THUMB2:       @ %bb.0:
; THUMB2-NEXT:    add.w r0, r0, r0, lsr #31
; THUMB2-NEXT:    asrs r0, r0, #1
; THUMB2-NEXT:    bx lr
  %div = sdiv i32 %x, 2
  ret i32 %div
}

define i32 @sdiv_int(i32 %begin, i32 %first) {
; ARM-LABEL: sdiv_int:
; ARM:       @ %bb.0:
; ARM-NEXT:    sub r1, r0, r1
; ARM-NEXT:    add r1, r1, #1
; ARM-NEXT:    add r1, r1, r1, lsr #31
; ARM-NEXT:    sub r0, r0, r1, asr #1
; ARM-NEXT:    bx lr
;
; THUMB1-LABEL: sdiv_int:
; THUMB1:       @ %bb.0:
; THUMB1-NEXT:    subs r1, r0, r1
; THUMB1-NEXT:    adds r1, r1, #1
; THUMB1-NEXT:    lsrs r2, r1, #31
; THUMB1-NEXT:    adds r1, r1, r2
; THUMB1-NEXT:    asrs r1, r1, #1
; THUMB1-NEXT:    subs r0, r0, r1
; THUMB1-NEXT:    bx lr
;
; THUMB2-LABEL: sdiv_int:
; THUMB2:       @ %bb.0:
; THUMB2-NEXT:    subs r1, r0, r1
; THUMB2-NEXT:    adds r1, #1
; THUMB2-NEXT:    add.w r1, r1, r1, lsr #31
; THUMB2-NEXT:    sub.w r0, r0, r1, asr #1
; THUMB2-NEXT:    bx lr
  %sub = add i32 %begin, 1
  %add = sub i32 %sub, %first
  %div.neg = sdiv i32 %add, -2
  %sub1 = add i32 %div.neg, %begin
  ret i32 %sub1
}
