; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=armv7-unknown-linux-gnueabi < %s | FileCheck %s --check-prefixes=CHECK

; https://bugs.llvm.org/show_bug.cgi?id=38149

; We are truncating from wider width, and then sign-extending
; back to the original width. Then we equality-comparing orig and src.
; If they don't match, then we had signed truncation during truncation.

; This can be expressed in a several ways in IR:
;   trunc + sext + icmp eq <- not canonical
;   shl   + ashr + icmp eq
;   add          + icmp uge/ugt
;   add          + icmp ult/ule
; However only the simplest form (with two shifts) gets lowered best.

; ---------------------------------------------------------------------------- ;
; shl + ashr + icmp eq
; ---------------------------------------------------------------------------- ;

define i1 @shifts_eqcmp_i16_i8(i16 %x) nounwind {
; CHECK-SD-LABEL: shifts_eqcmp_i16_i8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    sxtb w8, w0
; CHECK-SD-NEXT:    and w8, w8, #0xffff
; CHECK-SD-NEXT:    cmp w8, w0, uxth
; CHECK-SD-NEXT:    cset w0, eq
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: shifts_eqcmp_i16_i8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    lsl w8, w0, #8
; CHECK-GI-NEXT:    sbfx w8, w8, #8, #8
; CHECK-GI-NEXT:    and w8, w8, #0xffff
; CHECK-GI-NEXT:    cmp w8, w0, uxth
; CHECK-GI-NEXT:    cset w0, eq
; CHECK-GI-NEXT:    ret
; CHECK-LABEL: shifts_eqcmp_i16_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    sxtb r1, r0
; CHECK-NEXT:    uxth r0, r0
; CHECK-NEXT:    uxth r1, r1
; CHECK-NEXT:    sub r0, r1, r0
; CHECK-NEXT:    clz r0, r0
; CHECK-NEXT:    lsr r0, r0, #5
; CHECK-NEXT:    bx lr
  %tmp0 = shl i16 %x, 8 ; 16-8
  %tmp1 = ashr exact i16 %tmp0, 8 ; 16-8
  %tmp2 = icmp eq i16 %tmp1, %x
  ret i1 %tmp2
}

define i1 @shifts_eqcmp_i32_i16(i32 %x) nounwind {
; CHECK-LABEL: shifts_eqcmp_i32_i16:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    sxth r1, r0
; CHECK-NEXT:    sub r0, r1, r0
; CHECK-NEXT:    clz r0, r0
; CHECK-NEXT:    lsr r0, r0, #5
; CHECK-NEXT:    bx lr
  %tmp0 = shl i32 %x, 16 ; 32-16
  %tmp1 = ashr exact i32 %tmp0, 16 ; 32-16
  %tmp2 = icmp eq i32 %tmp1, %x
  ret i1 %tmp2
}

define i1 @shifts_eqcmp_i32_i8(i32 %x) nounwind {
; CHECK-LABEL: shifts_eqcmp_i32_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    sxtb r1, r0
; CHECK-NEXT:    sub r0, r1, r0
; CHECK-NEXT:    clz r0, r0
; CHECK-NEXT:    lsr r0, r0, #5
; CHECK-NEXT:    bx lr
  %tmp0 = shl i32 %x, 24 ; 32-8
  %tmp1 = ashr exact i32 %tmp0, 24 ; 32-8
  %tmp2 = icmp eq i32 %tmp1, %x
  ret i1 %tmp2
}

; ---------------------------------------------------------------------------- ;
; add + icmp uge
; ---------------------------------------------------------------------------- ;

define i1 @add_ugecmp_i16_i8(i16 %x) nounwind {
; CHECK-SD-LABEL: add_ugecmp_i16_i8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    and w8, w0, #0xffff
; CHECK-SD-NEXT:    sub w8, w8, #128
; CHECK-SD-NEXT:    lsr w8, w8, #8
; CHECK-SD-NEXT:    cmp w8, #254
; CHECK-SD-NEXT:    cset w0, hi
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: add_ugecmp_i16_i8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    mov w8, #-128 // =0xffffff80
; CHECK-GI-NEXT:    mov w9, #65280 // =0xff00
; CHECK-GI-NEXT:    add w8, w8, w0, uxth
; CHECK-GI-NEXT:    cmp w8, w9
; CHECK-GI-NEXT:    cset w0, hs
; CHECK-GI-NEXT:    ret
; CHECK-LABEL: add_ugecmp_i16_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mvn r1, #127
; CHECK-NEXT:    uxtah r0, r1, r0
; CHECK-NEXT:    lsr r1, r0, #8
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #254
; CHECK-NEXT:    movwhi r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, -128 ; ~0U << (8-1)
  %tmp1 = icmp uge i16 %tmp0, -256 ; ~0U << 8
  ret i1 %tmp1
}

define i1 @add_ugecmp_i32_i16_i8(i16 %xx) nounwind {
; CHECK-SD-LABEL: add_ugecmp_i32_i16_i8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    and w8, w0, #0xffff
; CHECK-SD-NEXT:    cmp w8, w8, sxtb
; CHECK-SD-NEXT:    cset w0, eq
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: add_ugecmp_i32_i16_i8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    mov w8, #-128 // =0xffffff80
; CHECK-GI-NEXT:    add w8, w8, w0, uxth
; CHECK-GI-NEXT:    cmn w8, #256
; CHECK-GI-NEXT:    cset w0, hs
; CHECK-GI-NEXT:    ret
; CHECK-LABEL: add_ugecmp_i32_i16_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    uxth r0, r0
; CHECK-NEXT:    sxtb r1, r0
; CHECK-NEXT:    sub r0, r1, r0
; CHECK-NEXT:    clz r0, r0
; CHECK-NEXT:    lsr r0, r0, #5
; CHECK-NEXT:    bx lr
  %x = zext i16 %xx to i32
  %tmp0 = add i32 %x, -128 ; ~0U << (8-1)
  %tmp1 = icmp uge i32 %tmp0, -256 ; ~0U << 8
  ret i1 %tmp1
}

define i1 @add_ugecmp_i32_i16(i32 %x) nounwind {
; CHECK-SD-LABEL: add_ugecmp_i32_i16:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    cmp w0, w0, sxth
; CHECK-SD-NEXT:    cset w0, eq
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: add_ugecmp_i32_i16:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    sub w8, w0, #8, lsl #12 // =32768
; CHECK-GI-NEXT:    cmn w8, #16, lsl #12 // =65536
; CHECK-GI-NEXT:    cset w0, hs
; CHECK-GI-NEXT:    ret
; CHECK-LABEL: add_ugecmp_i32_i16:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    sxth r1, r0
; CHECK-NEXT:    sub r0, r1, r0
; CHECK-NEXT:    clz r0, r0
; CHECK-NEXT:    lsr r0, r0, #5
; CHECK-NEXT:    bx lr
  %tmp0 = add i32 %x, -32768 ; ~0U << (16-1)
  %tmp1 = icmp uge i32 %tmp0, -65536 ; ~0U << 16
  ret i1 %tmp1
}

define i1 @add_ugecmp_i32_i8(i32 %x) nounwind {
; CHECK-SD-LABEL: add_ugecmp_i32_i8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    cmp w0, w0, sxtb
; CHECK-SD-NEXT:    cset w0, eq
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: add_ugecmp_i32_i8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    sub w8, w0, #128
; CHECK-GI-NEXT:    cmn w8, #256
; CHECK-GI-NEXT:    cset w0, hs
; CHECK-GI-NEXT:    ret
; CHECK-LABEL: add_ugecmp_i32_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    sxtb r1, r0
; CHECK-NEXT:    sub r0, r1, r0
; CHECK-NEXT:    clz r0, r0
; CHECK-NEXT:    lsr r0, r0, #5
; CHECK-NEXT:    bx lr
  %tmp0 = add i32 %x, -128 ; ~0U << (8-1)
  %tmp1 = icmp uge i32 %tmp0, -256 ; ~0U << 8
  ret i1 %tmp1
}

; Slightly more canonical variant
define i1 @add_ugtcmp_i16_i8(i16 %x) nounwind {
; CHECK-SD-LABEL: add_ugtcmp_i16_i8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    and w8, w0, #0xffff
; CHECK-SD-NEXT:    sub w8, w8, #128
; CHECK-SD-NEXT:    lsr w8, w8, #8
; CHECK-SD-NEXT:    cmp w8, #254
; CHECK-SD-NEXT:    cset w0, hi
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: add_ugtcmp_i16_i8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    mov w8, #-128 // =0xffffff80
; CHECK-GI-NEXT:    mov w9, #65279 // =0xfeff
; CHECK-GI-NEXT:    add w8, w8, w0, uxth
; CHECK-GI-NEXT:    cmp w8, w9
; CHECK-GI-NEXT:    cset w0, hi
; CHECK-GI-NEXT:    ret
; CHECK-LABEL: add_ugtcmp_i16_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mvn r1, #127
; CHECK-NEXT:    uxtah r0, r1, r0
; CHECK-NEXT:    lsr r1, r0, #8
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #254
; CHECK-NEXT:    movwhi r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, -128 ; ~0U << (8-1)
  %tmp1 = icmp ugt i16 %tmp0, -257 ; ~0U << 8 - 1
  ret i1 %tmp1
}

; ---------------------------------------------------------------------------- ;
; add + icmp ult
; ---------------------------------------------------------------------------- ;

define i1 @add_ultcmp_i16_i8(i16 %x) nounwind {
; CHECK-SD-LABEL: add_ultcmp_i16_i8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    sxtb w8, w0
; CHECK-SD-NEXT:    and w8, w8, #0xffff
; CHECK-SD-NEXT:    cmp w8, w0, uxth
; CHECK-SD-NEXT:    cset w0, eq
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: add_ultcmp_i16_i8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    add w8, w0, #128
; CHECK-GI-NEXT:    and w8, w8, #0xffff
; CHECK-GI-NEXT:    cmp w8, #256
; CHECK-GI-NEXT:    cset w0, lo
; CHECK-GI-NEXT:    ret
; CHECK-LABEL: add_ultcmp_i16_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    sxtb r1, r0
; CHECK-NEXT:    uxth r0, r0
; CHECK-NEXT:    uxth r1, r1
; CHECK-NEXT:    sub r0, r1, r0
; CHECK-NEXT:    clz r0, r0
; CHECK-NEXT:    lsr r0, r0, #5
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp ult i16 %tmp0, 256 ; 1U << 8
  ret i1 %tmp1
}

define i1 @add_ultcmp_i32_i16(i32 %x) nounwind {
; CHECK-SD-LABEL: add_ultcmp_i32_i16:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    cmp w0, w0, sxth
; CHECK-SD-NEXT:    cset w0, eq
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: add_ultcmp_i32_i16:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    add w8, w0, #8, lsl #12 // =32768
; CHECK-GI-NEXT:    cmp w8, #16, lsl #12 // =65536
; CHECK-GI-NEXT:    cset w0, lo
; CHECK-GI-NEXT:    ret
; CHECK-LABEL: add_ultcmp_i32_i16:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    sxth r1, r0
; CHECK-NEXT:    sub r0, r1, r0
; CHECK-NEXT:    clz r0, r0
; CHECK-NEXT:    lsr r0, r0, #5
; CHECK-NEXT:    bx lr
  %tmp0 = add i32 %x, 32768 ; 1U << (16-1)
  %tmp1 = icmp ult i32 %tmp0, 65536 ; 1U << 16
  ret i1 %tmp1
}

define i1 @add_ultcmp_i32_i8(i32 %x) nounwind {
; CHECK-SD-LABEL: add_ultcmp_i32_i8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    cmp w0, w0, sxtb
; CHECK-SD-NEXT:    cset w0, eq
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: add_ultcmp_i32_i8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    add w8, w0, #128
; CHECK-GI-NEXT:    cmp w8, #256
; CHECK-GI-NEXT:    cset w0, lo
; CHECK-GI-NEXT:    ret
; CHECK-LABEL: add_ultcmp_i32_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    sxtb r1, r0
; CHECK-NEXT:    sub r0, r1, r0
; CHECK-NEXT:    clz r0, r0
; CHECK-NEXT:    lsr r0, r0, #5
; CHECK-NEXT:    bx lr
  %tmp0 = add i32 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp ult i32 %tmp0, 256 ; 1U << 8
  ret i1 %tmp1
}

; Slightly more canonical variant
define i1 @add_ulecmp_i16_i8(i16 %x) nounwind {
; CHECK-LABEL: add_ulecmp_i16_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    sxtb r1, r0
; CHECK-NEXT:    uxth r0, r0
; CHECK-NEXT:    uxth r1, r1
; CHECK-NEXT:    sub r0, r1, r0
; CHECK-NEXT:    clz r0, r0
; CHECK-NEXT:    lsr r0, r0, #5
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp ule i16 %tmp0, 255 ; (1U << 8) - 1
  ret i1 %tmp1
}

; Negative tests
; ---------------------------------------------------------------------------- ;

; Adding not a constant
define i1 @add_ultcmp_bad_i16_i8_add(i16 %x, i16 %y) nounwind {
; CHECK-SD-LABEL: add_ultcmp_bad_i16_i8_add:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    add w8, w0, w1
; CHECK-SD-NEXT:    tst w8, #0xff00
; CHECK-SD-NEXT:    cset w0, eq
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: add_ultcmp_bad_i16_i8_add:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    add w8, w0, w1
; CHECK-GI-NEXT:    and w8, w8, #0xffff
; CHECK-GI-NEXT:    cmp w8, #256
; CHECK-GI-NEXT:    cset w0, lo
; CHECK-GI-NEXT:    ret
; CHECK-LABEL: add_ultcmp_bad_i16_i8_add:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    add r0, r0, r1
; CHECK-NEXT:    uxth r1, r0
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #256
; CHECK-NEXT:    movwlo r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, %y
  %tmp1 = icmp ult i16 %tmp0, 256 ; 1U << 8
  ret i1 %tmp1
}

; Comparing not with a constant
define i1 @add_ultcmp_bad_i16_i8_cmp(i16 %x, i16 %y) nounwind {
; CHECK-LABEL: add_ultcmp_bad_i16_i8_cmp:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    add r0, r0, #128
; CHECK-NEXT:    uxth r1, r1
; CHECK-NEXT:    uxth r2, r0
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r2, r1
; CHECK-NEXT:    movwlo r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp ult i16 %tmp0, %y
  ret i1 %tmp1
}

; Second constant is not larger than the first one
define i1 @add_ultcmp_bad_i8_i16(i16 %x) nounwind {
; CHECK-SD-LABEL: add_ultcmp_bad_i8_i16:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    and w8, w0, #0xffff
; CHECK-SD-NEXT:    add w8, w8, #128
; CHECK-SD-NEXT:    lsr w0, w8, #16
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: add_ultcmp_bad_i8_i16:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    and w8, w0, #0xffff
; CHECK-GI-NEXT:    add w8, w8, #128
; CHECK-GI-NEXT:    cmp w8, w8, uxth
; CHECK-GI-NEXT:    cset w0, ne
; CHECK-GI-NEXT:    ret
; CHECK-LABEL: add_ultcmp_bad_i8_i16:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r1, #128
; CHECK-NEXT:    uxtah r0, r1, r0
; CHECK-NEXT:    lsr r0, r0, #16
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp ult i16 %tmp0, 128 ; 1U << (8-1)
  ret i1 %tmp1
}

; First constant is not power of two
define i1 @add_ultcmp_bad_i16_i8_c0notpoweroftwo(i16 %x) nounwind {
; CHECK-SD-LABEL: add_ultcmp_bad_i16_i8_c0notpoweroftwo:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    add w8, w0, #192
; CHECK-SD-NEXT:    tst w8, #0xff00
; CHECK-SD-NEXT:    cset w0, eq
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: add_ultcmp_bad_i16_i8_c0notpoweroftwo:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    add w8, w0, #192
; CHECK-GI-NEXT:    and w8, w8, #0xffff
; CHECK-GI-NEXT:    cmp w8, #256
; CHECK-GI-NEXT:    cset w0, lo
; CHECK-GI-NEXT:    ret
; CHECK-LABEL: add_ultcmp_bad_i16_i8_c0notpoweroftwo:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    add r0, r0, #192
; CHECK-NEXT:    uxth r1, r0
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #256
; CHECK-NEXT:    movwlo r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 192 ; (1U << (8-1)) + (1U << (8-1-1))
  %tmp1 = icmp ult i16 %tmp0, 256 ; 1U << 8
  ret i1 %tmp1
}

; Second constant is not power of two
define i1 @add_ultcmp_bad_i16_i8_c1notpoweroftwo(i16 %x) nounwind {
; CHECK-LABEL: add_ultcmp_bad_i16_i8_c1notpoweroftwo:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    add r0, r0, #128
; CHECK-NEXT:    uxth r1, r0
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #768
; CHECK-NEXT:    movwlo r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp ult i16 %tmp0, 768 ; (1U << 8)) + (1U << (8+1))
  ret i1 %tmp1
}

; Magic check fails, 64 << 1 != 256
define i1 @add_ultcmp_bad_i16_i8_magic(i16 %x) nounwind {
; CHECK-SD-LABEL: add_ultcmp_bad_i16_i8_magic:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    add w8, w0, #64
; CHECK-SD-NEXT:    tst w8, #0xff00
; CHECK-SD-NEXT:    cset w0, eq
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: add_ultcmp_bad_i16_i8_magic:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    add w8, w0, #64
; CHECK-GI-NEXT:    and w8, w8, #0xffff
; CHECK-GI-NEXT:    cmp w8, #256
; CHECK-GI-NEXT:    cset w0, lo
; CHECK-GI-NEXT:    ret
; CHECK-LABEL: add_ultcmp_bad_i16_i8_magic:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    add r0, r0, #64
; CHECK-NEXT:    uxth r1, r0
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #256
; CHECK-NEXT:    movwlo r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 64 ; 1U << (8-1-1)
  %tmp1 = icmp ult i16 %tmp0, 256 ; 1U << 8
  ret i1 %tmp1
}

; Bad 'destination type'
define i1 @add_ultcmp_bad_i16_i4(i16 %x) nounwind {
; CHECK-SD-LABEL: add_ultcmp_bad_i16_i4:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    add w8, w0, #8
; CHECK-SD-NEXT:    tst w8, #0xfff0
; CHECK-SD-NEXT:    cset w0, eq
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: add_ultcmp_bad_i16_i4:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    add w8, w0, #8
; CHECK-GI-NEXT:    and w8, w8, #0xffff
; CHECK-GI-NEXT:    cmp w8, #16
; CHECK-GI-NEXT:    cset w0, lo
; CHECK-GI-NEXT:    ret
; CHECK-LABEL: add_ultcmp_bad_i16_i4:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    add r0, r0, #8
; CHECK-NEXT:    uxth r1, r0
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #16
; CHECK-NEXT:    movwlo r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 8 ; 1U << (4-1)
  %tmp1 = icmp ult i16 %tmp0, 16 ; 1U << 4
  ret i1 %tmp1
}

; Bad storage type
define i1 @add_ultcmp_bad_i24_i8(i24 %x) nounwind {
; CHECK-SD-LABEL: add_ultcmp_bad_i24_i8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    add w8, w0, #128
; CHECK-SD-NEXT:    tst w8, #0xffff00
; CHECK-SD-NEXT:    cset w0, eq
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: add_ultcmp_bad_i24_i8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    add w8, w0, #128
; CHECK-GI-NEXT:    and w8, w8, #0xffffff
; CHECK-GI-NEXT:    cmp w8, #256
; CHECK-GI-NEXT:    cset w0, lo
; CHECK-GI-NEXT:    ret
; CHECK-LABEL: add_ultcmp_bad_i24_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    add r0, r0, #128
; CHECK-NEXT:    bic r1, r0, #-16777216
; CHECK-NEXT:    mov r0, #0
; CHECK-NEXT:    cmp r1, #256
; CHECK-NEXT:    movwlo r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i24 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp ult i24 %tmp0, 256 ; 1U << 8
  ret i1 %tmp1
}

define i1 @add_ulecmp_bad_i16_i8(i16 %x) nounwind {
; CHECK-LABEL: add_ulecmp_bad_i16_i8:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    mov r0, #1
; CHECK-NEXT:    bx lr
  %tmp0 = add i16 %x, 128 ; 1U << (8-1)
  %tmp1 = icmp ule i16 %tmp0, -1 ; when we +1 it, it will wrap to 0
  ret i1 %tmp1
}
