; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=armv7a-eabi < %s -o - | FileCheck %s --check-prefix=ARM
; RUN: llc -mtriple=thumbv6m-none-eabi < %s -o - | FileCheck %s --check-prefix=THUMB1
; RUN: llc -mtriple=thumbv7m-none-eabi < %s -o - | FileCheck %s --check-prefix=THUMB2

define i16 @fold_srem_1_i16(i16 %x) {
; ARM-LABEL: fold_srem_1_i16:
; ARM:       @ %bb.0:
; ARM-NEXT:    mov r0, #0
; ARM-NEXT:    bx lr
;
; THUMB1-LABEL: fold_srem_1_i16:
; THUMB1:       @ %bb.0:
; THUMB1-NEXT:    movs r0, #0
; THUMB1-NEXT:    bx lr
;
; THUMB2-LABEL: fold_srem_1_i16:
; THUMB2:       @ %bb.0:
; THUMB2-NEXT:    movs r0, #0
; THUMB2-NEXT:    bx lr
  %1 = srem i16 %x, 1
  ret i16 %1
}

define i32 @fold_srem_1_i32(i32 %x) {
; ARM-LABEL: fold_srem_1_i32:
; ARM:       @ %bb.0:
; ARM-NEXT:    mov r0, #0
; ARM-NEXT:    bx lr
;
; THUMB1-LABEL: fold_srem_1_i32:
; THUMB1:       @ %bb.0:
; THUMB1-NEXT:    movs r0, #0
; THUMB1-NEXT:    bx lr
;
; THUMB2-LABEL: fold_srem_1_i32:
; THUMB2:       @ %bb.0:
; THUMB2-NEXT:    movs r0, #0
; THUMB2-NEXT:    bx lr
  %1 = srem i32 %x, 1
  ret i32 %1
}

define i16 @fold_srem_2_i16(i16 %x) {
; ARM-LABEL: fold_srem_2_i16:
; ARM:       @ %bb.0:
; ARM-NEXT:    uxth r1, r0
; ARM-NEXT:    add r1, r0, r1, lsr #15
; ARM-NEXT:    bic r1, r1, #1
; ARM-NEXT:    sub r0, r0, r1
; ARM-NEXT:    bx lr
;
; THUMB1-LABEL: fold_srem_2_i16:
; THUMB1:       @ %bb.0:
; THUMB1-NEXT:    uxth r1, r0
; THUMB1-NEXT:    lsrs r1, r1, #15
; THUMB1-NEXT:    adds r1, r0, r1
; THUMB1-NEXT:    movs r2, #1
; THUMB1-NEXT:    bics r1, r2
; THUMB1-NEXT:    subs r0, r0, r1
; THUMB1-NEXT:    bx lr
;
; THUMB2-LABEL: fold_srem_2_i16:
; THUMB2:       @ %bb.0:
; THUMB2-NEXT:    uxth r1, r0
; THUMB2-NEXT:    add.w r1, r0, r1, lsr #15
; THUMB2-NEXT:    bic r1, r1, #1
; THUMB2-NEXT:    subs r0, r0, r1
; THUMB2-NEXT:    bx lr
  %1 = srem i16 %x, 2
  ret i16 %1
}

define i32 @fold_srem_2_i32(i32 %x) {
; ARM-LABEL: fold_srem_2_i32:
; ARM:       @ %bb.0:
; ARM-NEXT:    add r1, r0, r0, lsr #31
; ARM-NEXT:    bic r1, r1, #1
; ARM-NEXT:    sub r0, r0, r1
; ARM-NEXT:    bx lr
;
; THUMB1-LABEL: fold_srem_2_i32:
; THUMB1:       @ %bb.0:
; THUMB1-NEXT:    lsrs r1, r0, #31
; THUMB1-NEXT:    adds r1, r0, r1
; THUMB1-NEXT:    movs r2, #1
; THUMB1-NEXT:    bics r1, r2
; THUMB1-NEXT:    subs r0, r0, r1
; THUMB1-NEXT:    bx lr
;
; THUMB2-LABEL: fold_srem_2_i32:
; THUMB2:       @ %bb.0:
; THUMB2-NEXT:    add.w r1, r0, r0, lsr #31
; THUMB2-NEXT:    bic r1, r1, #1
; THUMB2-NEXT:    subs r0, r0, r1
; THUMB2-NEXT:    bx lr
  %1 = srem i32 %x, 2
  ret i32 %1
}

define i16 @fold_srem_pow2_i16(i16 %x) {
; ARM-LABEL: fold_srem_pow2_i16:
; ARM:       @ %bb.0:
; ARM-NEXT:    sxth r1, r0
; ARM-NEXT:    ubfx r1, r1, #25, #6
; ARM-NEXT:    add r1, r0, r1
; ARM-NEXT:    bic r1, r1, #63
; ARM-NEXT:    sub r0, r0, r1
; ARM-NEXT:    bx lr
;
; THUMB1-LABEL: fold_srem_pow2_i16:
; THUMB1:       @ %bb.0:
; THUMB1-NEXT:    sxth r1, r0
; THUMB1-NEXT:    lsrs r1, r1, #26
; THUMB1-NEXT:    adds r1, r0, r1
; THUMB1-NEXT:    movs r2, #63
; THUMB1-NEXT:    bics r1, r2
; THUMB1-NEXT:    subs r0, r0, r1
; THUMB1-NEXT:    bx lr
;
; THUMB2-LABEL: fold_srem_pow2_i16:
; THUMB2:       @ %bb.0:
; THUMB2-NEXT:    sxth r1, r0
; THUMB2-NEXT:    ubfx r1, r1, #25, #6
; THUMB2-NEXT:    add r1, r0
; THUMB2-NEXT:    bic r1, r1, #63
; THUMB2-NEXT:    subs r0, r0, r1
; THUMB2-NEXT:    bx lr
  %1 = srem i16 %x, 64
  ret i16 %1
}

define i32 @fold_srem_pow2_i32(i32 %x) {
; ARM-LABEL: fold_srem_pow2_i32:
; ARM:       @ %bb.0:
; ARM-NEXT:    asr r1, r0, #31
; ARM-NEXT:    add r1, r0, r1, lsr #26
; ARM-NEXT:    bic r1, r1, #63
; ARM-NEXT:    sub r0, r0, r1
; ARM-NEXT:    bx lr
;
; THUMB1-LABEL: fold_srem_pow2_i32:
; THUMB1:       @ %bb.0:
; THUMB1-NEXT:    asrs r1, r0, #31
; THUMB1-NEXT:    lsrs r1, r1, #26
; THUMB1-NEXT:    adds r1, r0, r1
; THUMB1-NEXT:    movs r2, #63
; THUMB1-NEXT:    bics r1, r2
; THUMB1-NEXT:    subs r0, r0, r1
; THUMB1-NEXT:    bx lr
;
; THUMB2-LABEL: fold_srem_pow2_i32:
; THUMB2:       @ %bb.0:
; THUMB2-NEXT:    asrs r1, r0, #31
; THUMB2-NEXT:    add.w r1, r0, r1, lsr #26
; THUMB2-NEXT:    bic r1, r1, #63
; THUMB2-NEXT:    subs r0, r0, r1
; THUMB2-NEXT:    bx lr
  %1 = srem i32 %x, 64
  ret i32 %1
}

define i16 @fold_srem_smax_i16(i16 %x) {
; ARM-LABEL: fold_srem_smax_i16:
; ARM:       @ %bb.0:
; ARM-NEXT:    sxth r1, r0
; ARM-NEXT:    ubfx r1, r1, #16, #15
; ARM-NEXT:    add r1, r0, r1
; ARM-NEXT:    bfc r1, #0, #15
; ARM-NEXT:    add r0, r0, r1
; ARM-NEXT:    bx lr
;
; THUMB1-LABEL: fold_srem_smax_i16:
; THUMB1:       @ %bb.0:
; THUMB1-NEXT:    sxth r1, r0
; THUMB1-NEXT:    lsrs r1, r1, #17
; THUMB1-NEXT:    adds r1, r0, r1
; THUMB1-NEXT:    uxth r1, r1
; THUMB1-NEXT:    lsrs r1, r1, #15
; THUMB1-NEXT:    lsls r1, r1, #15
; THUMB1-NEXT:    adds r0, r0, r1
; THUMB1-NEXT:    bx lr
;
; THUMB2-LABEL: fold_srem_smax_i16:
; THUMB2:       @ %bb.0:
; THUMB2-NEXT:    sxth r1, r0
; THUMB2-NEXT:    movw r2, #32767
; THUMB2-NEXT:    ubfx r1, r1, #16, #15
; THUMB2-NEXT:    add r1, r0
; THUMB2-NEXT:    bics r1, r2
; THUMB2-NEXT:    add r0, r1
; THUMB2-NEXT:    bx lr
  %1 = srem i16 %x, 32768
  ret i16 %1
}

define i32 @fold_srem_smax_i32(i32 %x) {
; ARM-LABEL: fold_srem_smax_i32:
; ARM:       @ %bb.0:
; ARM-NEXT:    asr r1, r0, #31
; ARM-NEXT:    add r1, r0, r1, lsr #1
; ARM-NEXT:    and r1, r1, #-2147483648
; ARM-NEXT:    add r0, r0, r1
; ARM-NEXT:    bx lr
;
; THUMB1-LABEL: fold_srem_smax_i32:
; THUMB1:       @ %bb.0:
; THUMB1-NEXT:    asrs r1, r0, #31
; THUMB1-NEXT:    lsrs r1, r1, #1
; THUMB1-NEXT:    adds r1, r0, r1
; THUMB1-NEXT:    lsrs r1, r1, #31
; THUMB1-NEXT:    lsls r1, r1, #31
; THUMB1-NEXT:    adds r0, r0, r1
; THUMB1-NEXT:    bx lr
;
; THUMB2-LABEL: fold_srem_smax_i32:
; THUMB2:       @ %bb.0:
; THUMB2-NEXT:    asrs r1, r0, #31
; THUMB2-NEXT:    add.w r1, r0, r1, lsr #1
; THUMB2-NEXT:    and r1, r1, #-2147483648
; THUMB2-NEXT:    add r0, r1
; THUMB2-NEXT:    bx lr
  %1 = srem i32 %x, 2147483648
  ret i32 %1
}
