; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=thumb-- -mcpu=cortex-a8 -relocation-model=static %s -o - | FileCheck -check-prefix=NO-OPTION %s
; RUN: llc -mtriple=thumb-- -mcpu=cortex-a8 -relocation-model=static %s -o - -mattr=+long-calls | FileCheck -check-prefix=LONGCALL %s
; RUN: llc -mtriple=thumb-- -mcpu=cortex-a8 -relocation-model=static %s -o - -mattr=-long-calls | FileCheck -check-prefix=NO-LONGCALL %s
; RUN: llc -mtriple=thumb-- -mcpu=cortex-a8 -relocation-model=static %s -o - -O0 | FileCheck -check-prefix=NO-OPTION %s
; RUN: llc -mtriple=thumb-- -mcpu=cortex-a8 -relocation-model=static %s -o - -O0 -mattr=+long-calls | FileCheck -check-prefix=LONGCALL %s
; RUN: llc -mtriple=thumb-- -mcpu=cortex-a8 -relocation-model=static %s -o - -O0 -mattr=-long-calls | FileCheck -check-prefix=NO-LONGCALL %s
; RUN: llc -mtriple=arm-linux-gnueabi -mcpu=cortex-a8 -relocation-model=static %s -o - -mattr=+long-calls,+execute-only | FileCheck -check-prefix=XO-LONGCALL %s
; RUN: llc -mtriple=arm-linux-gnueabi -mcpu=cortex-a8 -relocation-model=pic %s -o - -mattr=+long-calls | FileCheck -check-prefix=PIC-LONGCALL %s

define i32 @caller0() #0 {
; NO-OPTION-LABEL: caller0:
; NO-OPTION:       @ %bb.0: @ %entry
; NO-OPTION-NEXT:    push {r7, lr}
; NO-OPTION-NEXT:    ldr r0, .LCPI0_0
; NO-OPTION-NEXT:    blx r0
; NO-OPTION-NEXT:    movs r0, #0
; NO-OPTION-NEXT:    pop {r7, pc}
; NO-OPTION-NEXT:    .p2align 2
; NO-OPTION-NEXT:  @ %bb.1:
; NO-OPTION-NEXT:  .LCPI0_0:
; NO-OPTION-NEXT:    .long callee0
;
; LONGCALL-LABEL: caller0:
; LONGCALL:       @ %bb.0: @ %entry
; LONGCALL-NEXT:    push {r7, lr}
; LONGCALL-NEXT:    ldr r0, .LCPI0_0
; LONGCALL-NEXT:    blx r0
; LONGCALL-NEXT:    movs r0, #0
; LONGCALL-NEXT:    pop {r7, pc}
; LONGCALL-NEXT:    .p2align 2
; LONGCALL-NEXT:  @ %bb.1:
; LONGCALL-NEXT:  .LCPI0_0:
; LONGCALL-NEXT:    .long callee0
;
; NO-LONGCALL-LABEL: caller0:
; NO-LONGCALL:       @ %bb.0: @ %entry
; NO-LONGCALL-NEXT:    push {r7, lr}
; NO-LONGCALL-NEXT:    bl callee0
; NO-LONGCALL-NEXT:    movs r0, #0
; NO-LONGCALL-NEXT:    pop {r7, pc}
;
; XO-LONGCALL-LABEL: caller0:
; XO-LONGCALL:       @ %bb.0: @ %entry
; XO-LONGCALL-NEXT:    .save {r11, lr}
; XO-LONGCALL-NEXT:    push {r11, lr}
; XO-LONGCALL-NEXT:    movw r0, :lower16:callee0
; XO-LONGCALL-NEXT:    movt r0, :upper16:callee0
; XO-LONGCALL-NEXT:    blx r0
; XO-LONGCALL-NEXT:    mov r0, #0
; XO-LONGCALL-NEXT:    pop {r11, pc}
;
; PIC-LONGCALL-LABEL: caller0:
; PIC-LONGCALL:       @ %bb.0: @ %entry
; PIC-LONGCALL-NEXT:    .save {r11, lr}
; PIC-LONGCALL-NEXT:    push {r11, lr}
; PIC-LONGCALL-NEXT:    ldr r0, .LCPI0_0
; PIC-LONGCALL-NEXT:  .LPC0_0:
; PIC-LONGCALL-NEXT:    ldr r0, [pc, r0]
; PIC-LONGCALL-NEXT:    blx r0
; PIC-LONGCALL-NEXT:    mov r0, #0
; PIC-LONGCALL-NEXT:    pop {r11, pc}
; PIC-LONGCALL-NEXT:    .p2align 2
; PIC-LONGCALL-NEXT:  @ %bb.1:
; PIC-LONGCALL-NEXT:  .LCPI0_0:
; PIC-LONGCALL-NEXT:  .Ltmp0:
; PIC-LONGCALL-NEXT:    .long callee0(GOT_PREL)-(.LPC0_0+8-.Ltmp0)
entry:
  tail call void @callee0()
  ret i32 0
}

define i32 @caller1() {
; NO-OPTION-LABEL: caller1:
; NO-OPTION:       @ %bb.0: @ %entry
; NO-OPTION-NEXT:    push {r7, lr}
; NO-OPTION-NEXT:    bl callee0
; NO-OPTION-NEXT:    movs r0, #0
; NO-OPTION-NEXT:    pop {r7, pc}
;
; LONGCALL-LABEL: caller1:
; LONGCALL:       @ %bb.0: @ %entry
; LONGCALL-NEXT:    push {r7, lr}
; LONGCALL-NEXT:    ldr r0, .LCPI1_0
; LONGCALL-NEXT:    blx r0
; LONGCALL-NEXT:    movs r0, #0
; LONGCALL-NEXT:    pop {r7, pc}
; LONGCALL-NEXT:    .p2align 2
; LONGCALL-NEXT:  @ %bb.1:
; LONGCALL-NEXT:  .LCPI1_0:
; LONGCALL-NEXT:    .long callee0
;
; NO-LONGCALL-LABEL: caller1:
; NO-LONGCALL:       @ %bb.0: @ %entry
; NO-LONGCALL-NEXT:    push {r7, lr}
; NO-LONGCALL-NEXT:    bl callee0
; NO-LONGCALL-NEXT:    movs r0, #0
; NO-LONGCALL-NEXT:    pop {r7, pc}
;
; XO-LONGCALL-LABEL: caller1:
; XO-LONGCALL:       @ %bb.0: @ %entry
; XO-LONGCALL-NEXT:    .save {r11, lr}
; XO-LONGCALL-NEXT:    push {r11, lr}
; XO-LONGCALL-NEXT:    movw r0, :lower16:callee0
; XO-LONGCALL-NEXT:    movt r0, :upper16:callee0
; XO-LONGCALL-NEXT:    blx r0
; XO-LONGCALL-NEXT:    mov r0, #0
; XO-LONGCALL-NEXT:    pop {r11, pc}
;
; PIC-LONGCALL-LABEL: caller1:
; PIC-LONGCALL:       @ %bb.0: @ %entry
; PIC-LONGCALL-NEXT:    .save {r11, lr}
; PIC-LONGCALL-NEXT:    push {r11, lr}
; PIC-LONGCALL-NEXT:    ldr r0, .LCPI1_0
; PIC-LONGCALL-NEXT:  .LPC1_0:
; PIC-LONGCALL-NEXT:    ldr r0, [pc, r0]
; PIC-LONGCALL-NEXT:    blx r0
; PIC-LONGCALL-NEXT:    mov r0, #0
; PIC-LONGCALL-NEXT:    pop {r11, pc}
; PIC-LONGCALL-NEXT:    .p2align 2
; PIC-LONGCALL-NEXT:  @ %bb.1:
; PIC-LONGCALL-NEXT:  .LCPI1_0:
; PIC-LONGCALL-NEXT:  .Ltmp1:
; PIC-LONGCALL-NEXT:    .long callee0(GOT_PREL)-(.LPC1_0+8-.Ltmp1)
entry:
  tail call void @callee0()
  ret i32 0
}

declare void @callee0()

attributes #0 = { "target-features"="+long-calls" }

define dso_local void @global_func() {
; NO-OPTION-LABEL: global_func:
; NO-OPTION:       @ %bb.0: @ %entry
; NO-OPTION-NEXT:    bx lr
;
; LONGCALL-LABEL: global_func:
; LONGCALL:       @ %bb.0: @ %entry
; LONGCALL-NEXT:    bx lr
;
; NO-LONGCALL-LABEL: global_func:
; NO-LONGCALL:       @ %bb.0: @ %entry
; NO-LONGCALL-NEXT:    bx lr
;
; XO-LONGCALL-LABEL: global_func:
; XO-LONGCALL:       @ %bb.0: @ %entry
; XO-LONGCALL-NEXT:    bx lr
entry:
  ret void
}

define void @test_global() {
; NO-OPTION-LABEL: test_global:
; NO-OPTION:       @ %bb.0: @ %entry
; NO-OPTION-NEXT:    push {r7, lr}
; NO-OPTION-NEXT:    bl global_func
; NO-OPTION-NEXT:    pop {r7, pc}
;
; LONGCALL-LABEL: test_global:
; LONGCALL:       @ %bb.0: @ %entry
; LONGCALL-NEXT:    push {r7, lr}
; LONGCALL-NEXT:    ldr r0, .LCPI3_0
; LONGCALL-NEXT:    blx r0
; LONGCALL-NEXT:    pop {r7, pc}
; LONGCALL-NEXT:    .p2align 2
; LONGCALL-NEXT:  @ %bb.1:
; LONGCALL-NEXT:  .LCPI3_0:
; LONGCALL-NEXT:    .long global_func
;
; NO-LONGCALL-LABEL: test_global:
; NO-LONGCALL:       @ %bb.0: @ %entry
; NO-LONGCALL-NEXT:    push {r7, lr}
; NO-LONGCALL-NEXT:    bl global_func
; NO-LONGCALL-NEXT:    pop {r7, pc}
;
; XO-LONGCALL-LABEL: test_global:
; XO-LONGCALL:       @ %bb.0: @ %entry
; XO-LONGCALL-NEXT:    .save {r11, lr}
; XO-LONGCALL-NEXT:    push {r11, lr}
; XO-LONGCALL-NEXT:    movw r0, :lower16:global_func
; XO-LONGCALL-NEXT:    movt r0, :upper16:global_func
; XO-LONGCALL-NEXT:    blx r0
; XO-LONGCALL-NEXT:    pop {r11, pc}
;
; PIC-LONGCALL-LABEL: test_global:
; PIC-LONGCALL:       @ %bb.0: @ %entry
; PIC-LONGCALL-NEXT:    .save {r11, lr}
; PIC-LONGCALL-NEXT:    push {r11, lr}
; PIC-LONGCALL-NEXT:    ldr r0, .LCPI3_0
; PIC-LONGCALL-NEXT:  .LPC3_0:
; PIC-LONGCALL-NEXT:    add r0, pc, r0
; PIC-LONGCALL-NEXT:    blx r0
; PIC-LONGCALL-NEXT:    pop {r11, pc}
; PIC-LONGCALL-NEXT:    .p2align 2
; PIC-LONGCALL-NEXT:  @ %bb.1:
; PIC-LONGCALL-NEXT:  .LCPI3_0:
; PIC-LONGCALL-NEXT:    .long .Lglobal_func$local-(.LPC3_0+8)
entry:
  call void @global_func()
  ret void
}

declare void @llvm.memset.p0.i32(ptr nocapture writeonly, i8, i32, i1 immarg)

define void @test_memset(ptr %dst, i8 %val, i32 %len) {
; NO-OPTION-LABEL: test_memset:
; NO-OPTION:       @ %bb.0: @ %entry
; NO-OPTION-NEXT:    push {r7, lr}
; NO-OPTION-NEXT:    bl memset
; NO-OPTION-NEXT:    pop {r7, pc}
;
; LONGCALL-LABEL: test_memset:
; LONGCALL:       @ %bb.0: @ %entry
; LONGCALL-NEXT:    push {r7, lr}
; LONGCALL-NEXT:    ldr r3, .LCPI4_0
; LONGCALL-NEXT:    blx r3
; LONGCALL-NEXT:    pop {r7, pc}
; LONGCALL-NEXT:    .p2align 2
; LONGCALL-NEXT:  @ %bb.1:
; LONGCALL-NEXT:  .LCPI4_0:
; LONGCALL-NEXT:    .long memset
;
; NO-LONGCALL-LABEL: test_memset:
; NO-LONGCALL:       @ %bb.0: @ %entry
; NO-LONGCALL-NEXT:    push {r7, lr}
; NO-LONGCALL-NEXT:    bl memset
; NO-LONGCALL-NEXT:    pop {r7, pc}
;
; XO-LONGCALL-LABEL: test_memset:
; XO-LONGCALL:       @ %bb.0: @ %entry
; XO-LONGCALL-NEXT:    .save {r11, lr}
; XO-LONGCALL-NEXT:    push {r11, lr}
; XO-LONGCALL-NEXT:    movw r3, :lower16:memset
; XO-LONGCALL-NEXT:    movt r3, :upper16:memset
; XO-LONGCALL-NEXT:    blx r3
; XO-LONGCALL-NEXT:    pop {r11, pc}
;
; PIC-LONGCALL-LABEL: test_memset:
; PIC-LONGCALL:       @ %bb.0: @ %entry
; PIC-LONGCALL-NEXT:    .save {r11, lr}
; PIC-LONGCALL-NEXT:    push {r11, lr}
; PIC-LONGCALL-NEXT:    ldr r3, .LCPI4_0
; PIC-LONGCALL-NEXT:  .LPC4_0:
; PIC-LONGCALL-NEXT:    ldr r3, [pc, r3]
; PIC-LONGCALL-NEXT:    blx r3
; PIC-LONGCALL-NEXT:    pop {r11, pc}
; PIC-LONGCALL-NEXT:    .p2align 2
; PIC-LONGCALL-NEXT:  @ %bb.1:
; PIC-LONGCALL-NEXT:  .LCPI4_0:
; PIC-LONGCALL-NEXT:    .long memset(GOT_PREL)
entry:
  call void @llvm.memset.p0.i32(ptr %dst, i8 %val, i32 %len, i1 false)
  ret void
}
