# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -run-pass=prologepilog %s -o - | FileCheck %s

--- |
  target triple = "thumbv5e-none-darwin"

  @.str = external constant [26 x i8]

  define ptr @f_pcrel() {
  entry:
    ret ptr @.str
  }
  define ptr @f_abs() {
  entry:
    ret ptr @.str
  }
...
---
name:            f_pcrel
alignment:       2
tracksRegLiveness: true
noPhis:          true
isSSA:           false
noVRegs:         true
hasFakeUses:     false
tracksDebugUserValues: true
frameInfo:
  maxAlignment:    1
  maxCallFrameSize: 0
machineFunctionInfo:
  isLRSpilled:     false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: f_pcrel
    ; CHECK: liveins: $lr
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup tPUSH 14 /* CC::al */, $noreg, killed $lr, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 4
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION offset $lr, -4
    ; CHECK-NEXT: dead $r0 = SPACE 2036, undef $r0
    ; CHECK-NEXT: renamable $r0 = tLDRLIT_ga_pcrel target-flags(arm-nonlazy) @.str
    ; CHECK-NEXT: renamable $r0 = tLDRi killed renamable $r0, 0, 14 /* CC::al */, $noreg :: (load (s32) from got)
    ; CHECK-NEXT: frame-destroy tPOP_RET 14 /* CC::al */, $noreg, def $pc, implicit-def $sp, implicit $sp, implicit $r0
    dead $r0 = SPACE 2036, undef $r0
    renamable $r0 = tLDRLIT_ga_pcrel target-flags(arm-nonlazy) @.str
    renamable $r0 = tLDRi killed renamable $r0, 0, 14 /* CC::al */, $noreg :: (load (s32) from got)
    tBX_RET 14 /* CC::al */, $noreg, implicit $r0
...
---
name:            f_abs
alignment:       2
tracksRegLiveness: true
noPhis:          true
isSSA:           false
noVRegs:         true
hasFakeUses:     false
tracksDebugUserValues: true
frameInfo:
  maxAlignment:    1
  maxCallFrameSize: 0
machineFunctionInfo:
  isLRSpilled:     false
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: f_abs
    ; CHECK: liveins: $lr
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup tPUSH 14 /* CC::al */, $noreg, killed $lr, implicit-def $sp, implicit $sp
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 4
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION offset $lr, -4
    ; CHECK-NEXT: dead $r0 = SPACE 2040, undef $r0
    ; CHECK-NEXT: renamable $r0 = tLDRLIT_ga_abs target-flags(arm-nonlazy) @.str
    ; CHECK-NEXT: frame-destroy tPOP_RET 14 /* CC::al */, $noreg, def $pc, implicit-def $sp, implicit $sp, implicit $r0
    dead $r0 = SPACE 2040, undef $r0
    renamable $r0 = tLDRLIT_ga_abs target-flags(arm-nonlazy) @.str
    tBX_RET 14 /* CC::al */, $noreg, implicit $r0
...
