; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=arm-eabi < %s | FileCheck %s

; Make sure postinc addressing mode is not used for volatile accesses,
; see https://github.com/llvm/llvm-project/issues/173014.

define void @volatile_store(ptr %start, ptr %end) {
; CHECK-LABEL: volatile_store:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    mov r2, #42
; CHECK-NEXT:  .LBB0_1: @ %loop
; CHECK-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    str r2, [r0], #4
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    bne .LBB0_1
; CHECK-NEXT:  @ %bb.2: @ %bb2
; CHECK-NEXT:    mov pc, lr
entry:
  br label %loop

loop:
  %iv = phi ptr [ %iv.next, %loop ], [ %start, %entry ]
  %iv.next = getelementptr inbounds nuw i8, ptr %iv, i64 4
  store volatile i32 42, ptr %iv, align 4
  %cmp = icmp eq ptr %iv.next, %end
  br i1 %cmp, label %bb2, label %loop

bb2:
  ret void
}

define void @volatile_load(ptr %start, ptr %end) {
; CHECK-LABEL: volatile_load:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:  .LBB1_1: @ %loop
; CHECK-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldr r2, [r0], #4
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    bne .LBB1_1
; CHECK-NEXT:  @ %bb.2: @ %bb2
; CHECK-NEXT:    mov pc, lr
entry:
  br label %loop

loop:
  %iv = phi ptr [ %iv.next, %loop ], [ %start, %entry ]
  %iv.next = getelementptr inbounds nuw i8, ptr %iv, i64 4
  load volatile i32, ptr %iv, align 4
  %cmp = icmp eq ptr %iv.next, %end
  br i1 %cmp, label %bb2, label %loop

bb2:
  ret void
}
