; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=arm-eabi < %s | FileCheck %s --check-prefixes=CHECK,SDAG
; RUN: llc -mtriple=arm-eabi -global-isel < %s | FileCheck %s --check-prefixes=CHECK,GISEL

; Make sure postinc/preinc addressing mode is not used for volatile accesses,
; see https://github.com/llvm/llvm-project/issues/173014.

define ptr @volatile_store_postinc(ptr %p) {
; SDAG-LABEL: volatile_store_postinc:
; SDAG:       @ %bb.0:
; SDAG-NEXT:    mov r1, #0
; SDAG-NEXT:    str r1, [r0]
; SDAG-NEXT:    add r0, r0, #4
; SDAG-NEXT:    mov pc, lr
;
; GISEL-LABEL: volatile_store_postinc:
; GISEL:       @ %bb.0:
; GISEL-NEXT:    mov r1, #0
; GISEL-NEXT:    str r1, [r0]
; GISEL-NEXT:    mov r1, #4
; GISEL-NEXT:    add r0, r0, r1
; GISEL-NEXT:    mov pc, lr
  store volatile i32 0, ptr %p
  %gep = getelementptr i8, ptr %p, i64 4
  ret ptr %gep
}

define ptr @volatile_load_postinc(ptr %p) {
; SDAG-LABEL: volatile_load_postinc:
; SDAG:       @ %bb.0:
; SDAG-NEXT:    ldr r1, [r0]
; SDAG-NEXT:    add r0, r0, #4
; SDAG-NEXT:    mov pc, lr
;
; GISEL-LABEL: volatile_load_postinc:
; GISEL:       @ %bb.0:
; GISEL-NEXT:    ldr r1, [r0]
; GISEL-NEXT:    mov r1, #4
; GISEL-NEXT:    add r0, r0, r1
; GISEL-NEXT:    mov pc, lr
  load volatile i32, ptr %p
  %gep = getelementptr i8, ptr %p, i64 4
  ret ptr %gep
}

define ptr @volatile_store_preinc(ptr %p) {
; SDAG-LABEL: volatile_store_preinc:
; SDAG:       @ %bb.0:
; SDAG-NEXT:    mov r1, #0
; SDAG-NEXT:    str r1, [r0, #4]!
; SDAG-NEXT:    mov pc, lr
;
; GISEL-LABEL: volatile_store_preinc:
; GISEL:       @ %bb.0:
; GISEL-NEXT:    mov r2, #4
; GISEL-NEXT:    add r0, r0, r2
; GISEL-NEXT:    mov r1, #0
; GISEL-NEXT:    str r1, [r0]
; GISEL-NEXT:    mov pc, lr
  %gep = getelementptr i8, ptr %p, i64 4
  store volatile i32 0, ptr %gep
  ret ptr %gep
}

define ptr @volatile_load_preinc(ptr %p) {
; SDAG-LABEL: volatile_load_preinc:
; SDAG:       @ %bb.0:
; SDAG-NEXT:    ldr r1, [r0, #4]!
; SDAG-NEXT:    mov pc, lr
;
; GISEL-LABEL: volatile_load_preinc:
; GISEL:       @ %bb.0:
; GISEL-NEXT:    mov r1, #4
; GISEL-NEXT:    add r0, r0, r1
; GISEL-NEXT:    ldr r1, [r0]
; GISEL-NEXT:    mov pc, lr
  %gep = getelementptr i8, ptr %p, i64 4
  load volatile i32, ptr %gep
  ret ptr %gep
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
