; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=armv8-linux-gnueabihf -mattr=+fp-armv8 -float-abi=hard | FileCheck %s
@varfloat = global float 0.0
@vardouble = global double 0.0
define void @test_vsel32sgt(i32 %lhs32, i32 %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32sgt:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r2, :lower16:varfloat
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    movt r2, :upper16:varfloat
; CHECK-NEXT:    vselgt.f32 s0, s0, s1
; CHECK-NEXT:    vstr s0, [r2]
; CHECK-NEXT:    bx lr
  %tst1 = icmp sgt i32 %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64sgt(i32 %lhs32, i32 %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64sgt:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r2, :lower16:vardouble
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    movt r2, :upper16:vardouble
; CHECK-NEXT:    vselgt.f64 d16, d0, d1
; CHECK-NEXT:    vstr d16, [r2]
; CHECK-NEXT:    bx lr
  %tst1 = icmp sgt i32 %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32sge(i32 %lhs32, i32 %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32sge:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r2, :lower16:varfloat
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    movt r2, :upper16:varfloat
; CHECK-NEXT:    vselge.f32 s0, s0, s1
; CHECK-NEXT:    vstr s0, [r2]
; CHECK-NEXT:    bx lr
  %tst1 = icmp sge i32 %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64sge(i32 %lhs32, i32 %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64sge:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r2, :lower16:vardouble
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    movt r2, :upper16:vardouble
; CHECK-NEXT:    vselge.f64 d16, d0, d1
; CHECK-NEXT:    vstr d16, [r2]
; CHECK-NEXT:    bx lr
  %tst1 = icmp sge i32 %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32eq(i32 %lhs32, i32 %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32eq:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r2, :lower16:varfloat
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    movt r2, :upper16:varfloat
; CHECK-NEXT:    vseleq.f32 s0, s0, s1
; CHECK-NEXT:    vstr s0, [r2]
; CHECK-NEXT:    bx lr
  %tst1 = icmp eq i32 %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64eq(i32 %lhs32, i32 %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64eq:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r2, :lower16:vardouble
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    movt r2, :upper16:vardouble
; CHECK-NEXT:    vseleq.f64 d16, d0, d1
; CHECK-NEXT:    vstr d16, [r2]
; CHECK-NEXT:    bx lr
  %tst1 = icmp eq i32 %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32slt(i32 %lhs32, i32 %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32slt:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r2, :lower16:varfloat
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    movt r2, :upper16:varfloat
; CHECK-NEXT:    vselge.f32 s0, s1, s0
; CHECK-NEXT:    vstr s0, [r2]
; CHECK-NEXT:    bx lr
  %tst1 = icmp slt i32 %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64slt(i32 %lhs32, i32 %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64slt:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r2, :lower16:vardouble
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    movt r2, :upper16:vardouble
; CHECK-NEXT:    vselge.f64 d16, d1, d0
; CHECK-NEXT:    vstr d16, [r2]
; CHECK-NEXT:    bx lr
  %tst1 = icmp slt i32 %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32sle(i32 %lhs32, i32 %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32sle:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r2, :lower16:varfloat
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    movt r2, :upper16:varfloat
; CHECK-NEXT:    vselgt.f32 s0, s1, s0
; CHECK-NEXT:    vstr s0, [r2]
; CHECK-NEXT:    bx lr
  %tst1 = icmp sle i32 %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64sle(i32 %lhs32, i32 %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64sle:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r2, :lower16:vardouble
; CHECK-NEXT:    cmp r0, r1
; CHECK-NEXT:    movt r2, :upper16:vardouble
; CHECK-NEXT:    vselgt.f64 d16, d1, d0
; CHECK-NEXT:    vstr d16, [r2]
; CHECK-NEXT:    bx lr
  %tst1 = icmp sle i32 %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32ogt(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32ogt:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselgt.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp ogt float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64ogt(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64ogt:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselgt.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp ogt float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32oge(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32oge:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselge.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp oge float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64oge(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64oge:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselge.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp oge float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32oeq(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32oeq:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vseleq.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp oeq float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64oeq(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64oeq:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vseleq.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp oeq float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32ugt(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32ugt:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselge.f32 s0, s3, s2
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp ugt float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64ugt(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64ugt:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselge.f64 d16, d2, d1
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp ugt float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32uge(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32uge:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselgt.f32 s0, s3, s2
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp uge float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64uge(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64uge:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselgt.f64 d16, d2, d1
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp uge float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32olt(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32olt:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselgt.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp olt float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64olt(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64olt:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselgt.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp olt float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32ult(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32ult:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselge.f32 s0, s3, s2
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp ult float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64ult(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64ult:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselge.f64 d16, d2, d1
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp ult float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32ole(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32ole:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselge.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp ole float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64ole(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64ole:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselge.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp ole float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32ule(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32ule:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselgt.f32 s0, s3, s2
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp ule float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64ule(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64ule:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselgt.f64 d16, d2, d1
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp ule float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32ord(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32ord:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselvs.f32 s0, s3, s2
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp ord float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64ord(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64ord:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselvs.f64 d16, d2, d1
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp ord float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32une(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32une:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vseleq.f32 s0, s3, s2
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp une float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64une(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64une:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vseleq.f64 d16, d2, d1
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp une float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32uno(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32uno:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselvs.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp uno float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64uno(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64uno:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselvs.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp uno float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}

define void @test_vsel32ogt_nnan(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32ogt_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselgt.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan ogt float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64ogt_nnan(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64ogt_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselgt.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan ogt float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32oge_nnan(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32oge_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselge.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan oge float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64oge_nnan(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64oge_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselge.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan oge float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32oeq_nnan(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32oeq_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vseleq.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan oeq float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64oeq_nnan(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64oeq_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vseleq.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan oeq float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32ugt_nnan(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32ugt_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselgt.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan ugt float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64ugt_nnan(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64ugt_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselgt.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan ugt float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32uge_nnan(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32uge_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselge.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan uge float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64uge_nnan(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64uge_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselge.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan uge float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32olt_nnan(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32olt_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselgt.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan olt float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64olt_nnan(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64olt_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselgt.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan olt float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32ult_nnan(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32ult_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselgt.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan ult float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64ult_nnan(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64ult_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselgt.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan ult float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32ole_nnan(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32ole_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselge.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan ole float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64ole_nnan(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64ole_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselge.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan ole float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32ule_nnan(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32ule_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselge.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan ule float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64ule_nnan(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64ule_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s1, s0
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselge.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan ule float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32ord_nnan(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32ord_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselvs.f32 s0, s3, s2
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan ord float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64ord_nnan(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64ord_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselvs.f64 d16, d2, d1
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan ord float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32une_nnan(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32une_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vseleq.f32 s0, s3, s2
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan une float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64une_nnan(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64une_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vseleq.f64 d16, d2, d1
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan une float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
define void @test_vsel32uno_nnan(float %lhs32, float %rhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel32uno_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:varfloat
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:varfloat
; CHECK-NEXT:    vselvs.f32 s0, s2, s3
; CHECK-NEXT:    vstr s0, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan uno float %lhs32, %rhs32
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}
define void @test_vsel64uno_nnan(float %lhs32, float %rhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel64uno_nnan:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vcmp.f32 s0, s1
; CHECK-NEXT:    movw r0, :lower16:vardouble
; CHECK-NEXT:    vmrs APSR_nzcv, fpscr
; CHECK-NEXT:    movt r0, :upper16:vardouble
; CHECK-NEXT:    vselvs.f64 d16, d1, d2
; CHECK-NEXT:    vstr d16, [r0]
; CHECK-NEXT:    bx lr
  %tst1 = fcmp nnan uno float %lhs32, %rhs32
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}

define void @test_vsel_ltzero(i32 %lhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel_ltzero:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r1, :lower16:varfloat
; CHECK-NEXT:    cmp r0, #0
; CHECK-NEXT:    movt r1, :upper16:varfloat
; CHECK-NEXT:    vselge.f32 s0, s1, s0
; CHECK-NEXT:    vstr s0, [r1]
; CHECK-NEXT:    bx lr
  %tst1 = icmp slt i32 %lhs32, 0
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}

define void @test_vsel_lezero(i32 %lhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel_lezero:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r1, :lower16:varfloat
; CHECK-NEXT:    cmp r0, #1
; CHECK-NEXT:    movt r1, :upper16:varfloat
; CHECK-NEXT:    vselge.f32 s0, s1, s0
; CHECK-NEXT:    vstr s0, [r1]
; CHECK-NEXT:    bx lr
  %tst1 = icmp sle i32 %lhs32, 0
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}

define void @test_vsel_gtzero(i32 %lhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel_gtzero:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r1, :lower16:varfloat
; CHECK-NEXT:    cmp r0, #0
; CHECK-NEXT:    movt r1, :upper16:varfloat
; CHECK-NEXT:    vselgt.f32 s0, s0, s1
; CHECK-NEXT:    vstr s0, [r1]
; CHECK-NEXT:    bx lr
  %tst1 = icmp sgt i32 %lhs32, 0
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}

define void @test_vsel_gezero(i32 %lhs32, float %a, float %b) {
; CHECK-LABEL: test_vsel_gezero:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r1, :lower16:varfloat
; CHECK-NEXT:    cmp r0, #0
; CHECK-NEXT:    movt r1, :upper16:varfloat
; CHECK-NEXT:    vselge.f32 s0, s0, s1
; CHECK-NEXT:    vstr s0, [r1]
; CHECK-NEXT:    bx lr
  %tst1 = icmp sge i32 %lhs32, 0
  %val1 = select i1 %tst1, float %a, float %b
  store float %val1, ptr @varfloat
  ret void
}

define void @test_vsel_ltzero64(i32 %lhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel_ltzero64:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r1, :lower16:vardouble
; CHECK-NEXT:    cmp r0, #0
; CHECK-NEXT:    movt r1, :upper16:vardouble
; CHECK-NEXT:    vselge.f64 d16, d1, d0
; CHECK-NEXT:    vstr d16, [r1]
; CHECK-NEXT:    bx lr
  %tst1 = icmp slt i32 %lhs32, 0
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}

define void @test_vsel_lezero64(i32 %lhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel_lezero64:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r1, :lower16:vardouble
; CHECK-NEXT:    cmp r0, #1
; CHECK-NEXT:    movt r1, :upper16:vardouble
; CHECK-NEXT:    vselge.f64 d16, d1, d0
; CHECK-NEXT:    vstr d16, [r1]
; CHECK-NEXT:    bx lr
  %tst1 = icmp sle i32 %lhs32, 0
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}

define void @test_vsel_gtzero64(i32 %lhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel_gtzero64:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r1, :lower16:vardouble
; CHECK-NEXT:    cmp r0, #0
; CHECK-NEXT:    movt r1, :upper16:vardouble
; CHECK-NEXT:    vselgt.f64 d16, d0, d1
; CHECK-NEXT:    vstr d16, [r1]
; CHECK-NEXT:    bx lr
  %tst1 = icmp sgt i32 %lhs32, 0
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}

define void @test_vsel_gezero64(i32 %lhs32, double %a, double %b) {
; CHECK-LABEL: test_vsel_gezero64:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movw r1, :lower16:vardouble
; CHECK-NEXT:    cmp r0, #0
; CHECK-NEXT:    movt r1, :upper16:vardouble
; CHECK-NEXT:    vselge.f64 d16, d0, d1
; CHECK-NEXT:    vstr d16, [r1]
; CHECK-NEXT:    bx lr
  %tst1 = icmp sge i32 %lhs32, 0
  %val1 = select i1 %tst1, double %a, double %b
  store double %val1, ptr @vardouble
  ret void
}
