; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -gvn-enable-min-finding-select-pattern -passes=gvn -S < %s | FileCheck %s

declare void @external_function(ptr)

; Negative test: Select not in a loop.
define void @test_not_in_loop(ptr %arr) {
; CHECK-LABEL: define void @test_not_in_loop(
; CHECK-SAME: ptr [[ARR:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[ARR]], align 4
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i64 1
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], [[LOAD2]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float [[LOAD2]]
; CHECK-NEXT:    ret void
;
entry:
  %gep1 = getelementptr float, ptr %arr, i32 0
  %load1 = load float, ptr %gep1
  %sext = sext i32 1 to i64
  %gep2 = getelementptr float, ptr %arr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  ret void
}

; Negative test: Loop without preheader (multiple entry points).
define void @test_no_preheader(ptr %arr, i32 %n, i1 %cond) {
; CHECK-LABEL: define void @test_no_preheader(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP:.*]], label %[[OTHER_ENTRY:.*]]
; CHECK:       [[OTHER_ENTRY]]:
; CHECK-NEXT:    br label %[[LOOP]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ 0, %[[OTHER_ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[SEXT:%.*]] = sext i32 [[I]] to i64
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i64 [[SEXT]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br i1 %cond, label %loop, label %other_entry

other_entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ 0, %other_entry ], [ %i.next, %loop ]
  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %sext = sext i32 %i to i64
  %gep2 = getelementptr float, ptr %arr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: Condition is not a CmpInst.
define void @test_condition_not_cmp(ptr %arr, i32 %n, i1 %bool) {
; CHECK-LABEL: define void @test_condition_not_cmp(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]], i1 [[BOOL:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[SEXT:%.*]] = sext i32 [[I]] to i64
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i64 [[SEXT]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %sext = sext i32 %i to i64
  %gep2 = getelementptr float, ptr %arr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %sel = select i1 %bool, float %load1, float %load2
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: Not both operands are loads (constant RHS).
define void @test_not_both_loads(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_not_both_loads(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], 0.000000e+00
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float 0.000000e+00
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %cmp = fcmp olt float %load1, 0.0
  %sel = select i1 %cmp, float %load1, float 0.0
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: Load doesn't match GEP(GEP(...))nested pattern.
define void @test_wrong_gep_pattern(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_wrong_gep_pattern(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  ; Simple GEP, not nested GEP(GEP(...))
  %gep2 = getelementptr float, ptr %arr, i32 %i
  %load2 = load float, ptr %gep2
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: ZExt instead of SExt.
define void @test_no_sext(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_no_sext(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[ZEXT:%.*]] = zext i32 [[I]] to i64
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i64 [[ZEXT]]
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], [[LOAD2]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float [[LOAD2]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %zext = zext i32 %i to i64
  %gep2 = getelementptr float, ptr %arr, i64 %zext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: SExt with wrong types (i16->i32 instead of i32->i64).
define void @test_wrong_sext_types(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_wrong_sext_types(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[I16:%.*]] = trunc i32 [[I]] to i16
; CHECK-NEXT:    [[SEXT:%.*]] = sext i16 [[I16]] to i32
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i32 [[SEXT]]
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], [[LOAD2]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float [[LOAD2]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %i16 = trunc i32 %i to i16
  %sext = sext i16 %i16 to i32
  %gep2 = getelementptr float, ptr %arr, i32 %sext
  %gep3 = getelementptr i8, ptr %gep2, i32 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: IndexVal is a constant, not a PHI node.
define void @test_index_is_constant(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_index_is_constant(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[GEP2_PHI_TRANS_INSERT:%.*]] = getelementptr float, ptr [[ARR]], i64 5
; CHECK-NEXT:    [[LOAD2_PRE:%.*]] = load float, ptr [[GEP2_PHI_TRANS_INSERT]], align 4
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], [[LOAD2_PRE]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float [[LOAD2_PRE]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]

  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  ; IndexVal is a constant (5), not a PHI node!
  %sext = sext i32 5 to i64
  %gep2 = getelementptr float, ptr %arr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: Initial min index value is not 1.
define void @test_initial_index_not_one(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_initial_index_not_one(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MIN_IDX:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[MIN_IDX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[SEXT:%.*]] = sext i32 [[MIN_IDX]] to i64
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i64 [[SEXT]]
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], [[LOAD2]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float [[LOAD2]]
; CHECK-NEXT:    [[MIN_IDX_NEXT]] = select i1 [[CMP]], i32 [[I]], i32 [[MIN_IDX]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  ; Initial value is 0, not 1!
  %min.idx = phi i32 [ 0, %entry ], [ %min.idx.next, %loop ]

  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %sext = sext i32 %min.idx to i64
  %gep2 = getelementptr float, ptr %arr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %min.idx.next = select i1 %cmp, i32 %i, i32 %min.idx
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: Pattern recognized but hoisting not safe due to aliasing store in loop.
define void @test_aliasing_store_in_loop(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_aliasing_store_in_loop(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MIN_IDX:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[MIN_IDX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[STORE_GEP:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    store float 0.000000e+00, ptr [[STORE_GEP]], align 4
; CHECK-NEXT:    [[SEXT:%.*]] = sext i32 [[MIN_IDX]] to i64
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i64 [[SEXT]]
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float 0.000000e+00, [[LOAD2]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float 0.000000e+00, float [[LOAD2]]
; CHECK-NEXT:    [[MIN_IDX_NEXT]] = select i1 [[CMP]], i32 [[I]], i32 [[MIN_IDX]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %min.idx = phi i32 [ 1, %entry ], [ %min.idx.next, %loop ]

  ; This store aliases with the loads, preventing hoisting.
  %store.gep = getelementptr float, ptr %arr, i32 %i
  store float 0.0, ptr %store.gep

  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %sext = sext i32 %min.idx to i64
  %gep2 = getelementptr float, ptr %arr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %min.idx.next = select i1 %cmp, i32 %i, i32 %min.idx
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: Pattern recognized but BasePtr is not loop invariant.
define void @test_non_invariant_base_ptr(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_non_invariant_base_ptr(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MIN_IDX:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[MIN_IDX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[BASE_PTR:%.*]] = phi ptr [ [[ARR]], %[[ENTRY]] ], [ [[BASE_PTR_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[BASE_PTR]], i32 [[I]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[SEXT:%.*]] = sext i32 [[MIN_IDX]] to i64
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[BASE_PTR]], i64 [[SEXT]]
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], [[LOAD2]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float [[LOAD2]]
; CHECK-NEXT:    [[MIN_IDX_NEXT]] = select i1 [[CMP]], i32 [[I]], i32 [[MIN_IDX]]
; CHECK-NEXT:    [[BASE_PTR_NEXT]] = getelementptr float, ptr [[BASE_PTR]], i32 1
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %min.idx = phi i32 [ 1, %entry ], [ %min.idx.next, %loop ]
  ; Base pointer changes each iteration - not loop invariant!
  %base.ptr = phi ptr [ %arr, %entry ], [ %base.ptr.next, %loop ]

  %gep1 = getelementptr float, ptr %base.ptr, i32 %i
  %load1 = load float, ptr %gep1
  %sext = sext i32 %min.idx to i64
  %gep2 = getelementptr float, ptr %base.ptr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %min.idx.next = select i1 %cmp, i32 %i, i32 %min.idx
  %base.ptr.next = getelementptr float, ptr %base.ptr, i32 1
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: Pattern recognized but may-alias call in loop.
define void @test_may_alias_call_in_loop(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_may_alias_call_in_loop(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MIN_IDX:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[MIN_IDX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    call void @external_function(ptr [[ARR]])
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[SEXT:%.*]] = sext i32 [[MIN_IDX]] to i64
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i64 [[SEXT]]
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], [[LOAD2]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float [[LOAD2]]
; CHECK-NEXT:    [[MIN_IDX_NEXT]] = select i1 [[CMP]], i32 [[I]], i32 [[MIN_IDX]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %min.idx = phi i32 [ 1, %entry ], [ %min.idx.next, %loop ]

  ; External function may modify memory.
  call void @external_function(ptr %arr)

  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %sext = sext i32 %min.idx to i64
  %gep2 = getelementptr float, ptr %arr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %min.idx.next = select i1 %cmp, i32 %i, i32 %min.idx
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: byte offsets on the two load addresses do not satisfy
; bytes_offset(val.first.gep) - bytes_offset(val.min.gep)
;   == sizeof(LoadType) * step_of_iv_next
; Here val.first has no i8-offset (C1 = 0), val.min has -4 (C2 = -4),
; sizeof(float) = 4, and step = -1, so the required equality
; (C1 - C2 == sizeof(T) * step) becomes 4 == -4 -- false. Transforming
; would propagate this iter's val.first as next iter's known_min, but
; next iter's val.min reads a different address. Recognizer must bail.
define i32 @test_gvn_min_pattern_offset_mismatch(ptr %base) {
; CHECK-LABEL: define i32 @test_gvn_min_pattern_offset_mismatch(
; CHECK-SAME: ptr [[BASE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 3, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[CTR:%.*]] = phi i64 [ 3, %[[ENTRY]] ], [ [[CTR_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MIN_IDX:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[MIN_IDX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], -1
; CHECK-NEXT:    [[PTR_IV:%.*]] = getelementptr float, ptr [[BASE]], i64 [[IV]]
; CHECK-NEXT:    [[VAL_FIRST:%.*]] = load float, ptr [[PTR_IV]], align 4
; CHECK-NEXT:    [[MIN_IDX_EXT:%.*]] = sext i32 [[MIN_IDX]] to i64
; CHECK-NEXT:    [[GEP_TYPED:%.*]] = getelementptr float, ptr [[BASE]], i64 [[MIN_IDX_EXT]]
; CHECK-NEXT:    [[GEP_OFFSET:%.*]] = getelementptr i8, ptr [[GEP_TYPED]], i64 -4
; CHECK-NEXT:    [[VAL_MIN:%.*]] = load float, ptr [[GEP_OFFSET]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[VAL_FIRST]], [[VAL_MIN]]
; CHECK-NEXT:    [[NEW_IDX:%.*]] = trunc nsw i64 [[IV_NEXT]] to i32
; CHECK-NEXT:    [[MIN_IDX_NEXT]] = select i1 [[CMP]], i32 [[NEW_IDX]], i32 [[MIN_IDX]]
; CHECK-NEXT:    [[CTR_NEXT]] = add nsw i64 [[CTR]], -1
; CHECK-NEXT:    [[COND:%.*]] = icmp samesign ugt i64 [[CTR]], 1
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 [[MIN_IDX_NEXT]]
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 3, %entry ], [ %iv.next, %loop ]
  %ctr = phi i64 [ 3, %entry ], [ %ctr.next, %loop ]
  %min.idx = phi i32 [ 1, %entry ], [ %min.idx.next, %loop ]
  %iv.next = add nsw i64 %iv, -1
  %ptr.iv = getelementptr float, ptr %base, i64 %iv
  %val.first = load float, ptr %ptr.iv, align 4
  %min.idx.ext = sext i32 %min.idx to i64
  %gep.typed = getelementptr float, ptr %base, i64 %min.idx.ext
  %gep.offset = getelementptr i8, ptr %gep.typed, i64 -4
  %val.min = load float, ptr %gep.offset, align 4
  %cmp = fcmp olt float %val.first, %val.min
  %new.idx = trunc nsw i64 %iv.next to i32
  %min.idx.next = select i1 %cmp, i32 %new.idx, i32 %min.idx
  %ctr.next = add nsw i64 %ctr, -1
  %cond = icmp samesign ugt i64 %ctr, 1
  br i1 %cond, label %loop, label %exit

exit:
  ret i32 %min.idx.next
}

; Negative test: select is in an inner block, not header-is-latch. Transform
; must not fire.
define void @test_select_block_not_header_is_latch(ptr %arr, i32 %initial_min_idx, i1 %go) {
; CHECK-LABEL: define void @test_select_block_not_header_is_latch(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[INITIAL_MIN_IDX:%.*]], i1 [[GO:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[INDVARS_IV_I:%.*]] = phi i64 [ 1, %[[ENTRY]] ], [ [[INDVARS_IV_NEXT_I:%.*]], %[[BODY:.*]] ]
; CHECK-NEXT:    [[LOOP_COUNTER:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[LOOP_COUNTER_NEXT:%.*]], %[[BODY]] ]
; CHECK-NEXT:    [[MIN_IDX:%.*]] = phi i32 [ [[INITIAL_MIN_IDX]], %[[ENTRY]] ], [ [[MIN_IDX_NEXT:%.*]], %[[BODY]] ]
; CHECK-NEXT:    br i1 [[GO]], label %[[BODY]], label %[[EXIT:.*]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVARS_IV_NEXT_I]] = add nsw i64 [[INDVARS_IV_I]], -1
; CHECK-NEXT:    [[PTR_I32_IV:%.*]] = getelementptr i32, ptr [[ARR]], i64 [[INDVARS_IV_I]]
; CHECK-NEXT:    [[PTR_FIRST_LOAD:%.*]] = getelementptr i8, ptr [[PTR_I32_IV]], i64 -8
; CHECK-NEXT:    [[VAL_FIRST:%.*]] = load i32, ptr [[PTR_FIRST_LOAD]], align 4
; CHECK-NEXT:    [[MIN_IDX_EXT:%.*]] = sext i32 [[MIN_IDX]] to i64
; CHECK-NEXT:    [[PTR_I32_MIN:%.*]] = getelementptr i32, ptr [[ARR]], i64 [[MIN_IDX_EXT]]
; CHECK-NEXT:    [[PTR_SECOND_LOAD:%.*]] = getelementptr i8, ptr [[PTR_I32_MIN]], i64 -4
; CHECK-NEXT:    [[VAL_CURRENT_MIN:%.*]] = load i32, ptr [[PTR_SECOND_LOAD]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[VAL_FIRST]], [[VAL_CURRENT_MIN]]
; CHECK-NEXT:    [[NEXT_IDX_TRUNC:%.*]] = trunc nsw i64 [[INDVARS_IV_NEXT_I]] to i32
; CHECK-NEXT:    [[MIN_IDX_NEXT]] = select i1 [[CMP]], i32 [[NEXT_IDX_TRUNC]], i32 [[MIN_IDX]]
; CHECK-NEXT:    [[LOOP_COUNTER_NEXT]] = add nsw i64 [[LOOP_COUNTER]], -1
; CHECK-NEXT:    [[LOOP_CONTINUE:%.*]] = icmp samesign ugt i64 [[LOOP_COUNTER]], 1
; CHECK-NEXT:    br i1 [[LOOP_CONTINUE]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %indvars.iv.i = phi i64 [ 1, %entry ], [ %indvars.iv.next.i, %latch ]
  %loop.counter = phi i64 [ 0, %entry ], [ %loop.counter.next, %latch ]
  %min.idx = phi i32 [ %initial_min_idx, %entry ], [ %min.idx.next, %latch ]
  br i1 %go, label %body, label %exit

body:
  %indvars.iv.next.i = add nsw i64 %indvars.iv.i, -1
  %ptr.i32.iv = getelementptr i32, ptr %arr, i64 %indvars.iv.i
  %ptr.first.load = getelementptr i8, ptr %ptr.i32.iv, i64 -8
  %val.first = load i32, ptr %ptr.first.load, align 4
  %min.idx.ext = sext i32 %min.idx to i64
  %ptr.i32.min = getelementptr i32, ptr %arr, i64 %min.idx.ext
  %ptr.second.load = getelementptr i8, ptr %ptr.i32.min, i64 -4
  %val.current.min = load i32, ptr %ptr.second.load, align 4
  %cmp = icmp slt i32 %val.first, %val.current.min
  %next.idx.trunc = trunc nsw i64 %indvars.iv.next.i to i32
  %min.idx.next = select i1 %cmp, i32 %next.idx.trunc, i32 %min.idx
  br label %latch

latch:
  %loop.counter.next = add nsw i64 %loop.counter, -1
  %loop.continue = icmp samesign ugt i64 %loop.counter, 1
  br i1 %loop.continue, label %header, label %exit

exit:
  ret void
}

; Negative test: hoistable load has an extra use in the loop.
define { i32, float } @test_hoistable_load_has_extra_use(ptr %arr) {
; CHECK-LABEL: define { i32, float } @test_hoistable_load_has_extra_use(
; CHECK-SAME: ptr [[ARR:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 5, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[CTR:%.*]] = phi i64 [ 4, %[[ENTRY]] ], [ [[CTR_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MIN_IDX:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[MIN_IDX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[SUM:%.*]] = phi float [ 0.000000e+00, %[[ENTRY]] ], [ [[SUM_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], -1
; CHECK-NEXT:    [[PTR_IV:%.*]] = getelementptr float, ptr [[ARR]], i64 [[IV]]
; CHECK-NEXT:    [[PTR_FIRST:%.*]] = getelementptr i8, ptr [[PTR_IV]], i64 -8
; CHECK-NEXT:    [[VAL_FIRST:%.*]] = load float, ptr [[PTR_FIRST]], align 4
; CHECK-NEXT:    [[MIN_IDX_EXT:%.*]] = sext i32 [[MIN_IDX]] to i64
; CHECK-NEXT:    [[GEP_TYPED:%.*]] = getelementptr float, ptr [[ARR]], i64 [[MIN_IDX_EXT]]
; CHECK-NEXT:    [[GEP_OFFSET:%.*]] = getelementptr i8, ptr [[GEP_TYPED]], i64 -4
; CHECK-NEXT:    [[VAL_MIN:%.*]] = load float, ptr [[GEP_OFFSET]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[VAL_FIRST]], [[VAL_MIN]]
; CHECK-NEXT:    [[NEW_IDX:%.*]] = trunc nsw i64 [[IV_NEXT]] to i32
; CHECK-NEXT:    [[MIN_IDX_NEXT]] = select i1 [[CMP]], i32 [[NEW_IDX]], i32 [[MIN_IDX]]
; CHECK-NEXT:    [[SUM_NEXT]] = fadd float [[SUM]], [[VAL_MIN]]
; CHECK-NEXT:    [[CTR_NEXT]] = add nsw i64 [[CTR]], -1
; CHECK-NEXT:    [[COND:%.*]] = icmp samesign ugt i64 [[CTR]], 1
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[R0:%.*]] = insertvalue { i32, float } poison, i32 [[MIN_IDX_NEXT]], 0
; CHECK-NEXT:    [[R1:%.*]] = insertvalue { i32, float } [[R0]], float [[SUM_NEXT]], 1
; CHECK-NEXT:    ret { i32, float } [[R1]]
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 5, %entry ], [ %iv.next, %loop ]
  %ctr = phi i64 [ 4, %entry ], [ %ctr.next, %loop ]
  %min.idx = phi i32 [ 1, %entry ], [ %min.idx.next, %loop ]
  %sum = phi float [ 0.0, %entry ], [ %sum.next, %loop ]
  %iv.next = add nsw i64 %iv, -1
  %ptr.iv = getelementptr float, ptr %arr, i64 %iv
  %ptr.first = getelementptr i8, ptr %ptr.iv, i64 -8
  %val.first = load float, ptr %ptr.first, align 4
  %min.idx.ext = sext i32 %min.idx to i64
  %gep.typed = getelementptr float, ptr %arr, i64 %min.idx.ext
  %gep.offset = getelementptr i8, ptr %gep.typed, i64 -4
  %val.min = load float, ptr %gep.offset, align 4
  %cmp = fcmp olt float %val.first, %val.min
  %new.idx = trunc nsw i64 %iv.next to i32
  %min.idx.next = select i1 %cmp, i32 %new.idx, i32 %min.idx
  %sum.next = fadd float %sum, %val.min
  %ctr.next = add nsw i64 %ctr, -1
  %cond = icmp samesign ugt i64 %ctr, 1
  br i1 %cond, label %loop, label %exit

exit:
  %r0 = insertvalue { i32, float } poison, i32 %min.idx.next, 0
  %r1 = insertvalue { i32, float } %r0, float %sum.next, 1
  ret { i32, float } %r1
}

; Negative test: IndexValPhi's loop back-edge is not the Select.
define void @test_indexvalphi_backedge_not_select(ptr %arr, ptr %sink) {
; CHECK-LABEL: define void @test_indexvalphi_backedge_not_select(
; CHECK-SAME: ptr [[ARR:%.*]], ptr [[SINK:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 5, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[CTR:%.*]] = phi i64 [ 4, %[[ENTRY]] ], [ [[CTR_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], -1
; CHECK-NEXT:    [[PTR_IV:%.*]] = getelementptr float, ptr [[ARR]], i64 [[IV]]
; CHECK-NEXT:    [[PTR_FIRST:%.*]] = getelementptr i8, ptr [[PTR_IV]], i64 -8
; CHECK-NEXT:    [[VAL_FIRST:%.*]] = load float, ptr [[PTR_FIRST]], align 4
; CHECK-NEXT:    [[GEP_TYPED:%.*]] = getelementptr float, ptr [[ARR]], i64 1
; CHECK-NEXT:    [[GEP_OFFSET:%.*]] = getelementptr i8, ptr [[GEP_TYPED]], i64 -4
; CHECK-NEXT:    [[VAL_MIN:%.*]] = load float, ptr [[GEP_OFFSET]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[VAL_FIRST]], [[VAL_MIN]]
; CHECK-NEXT:    [[NEW_IDX:%.*]] = trunc nsw i64 [[IV_NEXT]] to i32
; CHECK-NEXT:    [[MIN_IDX_NEXT:%.*]] = select i1 [[CMP]], i32 [[NEW_IDX]], i32 1
; CHECK-NEXT:    [[SINK_IV:%.*]] = getelementptr i32, ptr [[SINK]], i64 [[CTR]]
; CHECK-NEXT:    store i32 [[MIN_IDX_NEXT]], ptr [[SINK_IV]], align 4
; CHECK-NEXT:    [[CTR_NEXT]] = add nsw i64 [[CTR]], -1
; CHECK-NEXT:    [[COND:%.*]] = icmp samesign ugt i64 [[CTR]], 1
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 5, %entry ], [ %iv.next, %loop ]
  %ctr = phi i64 [ 4, %entry ], [ %ctr.next, %loop ]
  %min.idx = phi i32 [ 1, %entry ], [ %min.idx.alt, %loop ]
  %iv.next = add nsw i64 %iv, -1
  %ptr.iv = getelementptr float, ptr %arr, i64 %iv
  %ptr.first = getelementptr i8, ptr %ptr.iv, i64 -8
  %val.first = load float, ptr %ptr.first, align 4
  %min.idx.ext = sext i32 %min.idx to i64
  %gep.typed = getelementptr float, ptr %arr, i64 %min.idx.ext
  %gep.offset = getelementptr i8, ptr %gep.typed, i64 -4
  %val.min = load float, ptr %gep.offset, align 4
  %cmp = fcmp olt float %val.first, %val.min
  %new.idx = trunc nsw i64 %iv.next to i32
  %min.idx.next = select i1 %cmp, i32 %new.idx, i32 %min.idx
  %min.idx.alt = add nsw i32 %min.idx, 0
  %sink.iv = getelementptr i32, ptr %sink, i64 %ctr
  store i32 %min.idx.next, ptr %sink.iv, align 4
  %ctr.next = add nsw i64 %ctr, -1
  %cond = icmp samesign ugt i64 %ctr, 1
  br i1 %cond, label %loop, label %exit

exit:
  ret void
}

; Negative test: Base pointer is loop-variant; hoisting GEP into the
; preheader would use a value not dominating the preheader.
define i32 @test_base_not_loop_invariant(ptr %arr) {
; CHECK-LABEL: define i32 @test_base_not_loop_invariant(
; CHECK-SAME: ptr [[ARR:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 3, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[CTR:%.*]] = phi i64 [ 3, %[[ENTRY]] ], [ [[CTR_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MIN_IDX:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[MIN_IDX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[BASE_PTR:%.*]] = phi ptr [ [[ARR]], %[[ENTRY]] ], [ [[BASE_PTR_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], -1
; CHECK-NEXT:    [[PTR_IV:%.*]] = getelementptr float, ptr [[BASE_PTR]], i64 [[IV]]
; CHECK-NEXT:    [[PTR_FIRST:%.*]] = getelementptr i8, ptr [[PTR_IV]], i64 -8
; CHECK-NEXT:    [[VAL_FIRST:%.*]] = load float, ptr [[PTR_FIRST]], align 4
; CHECK-NEXT:    [[MIN_IDX_EXT:%.*]] = sext i32 [[MIN_IDX]] to i64
; CHECK-NEXT:    [[GEP_TYPED:%.*]] = getelementptr float, ptr [[BASE_PTR]], i64 [[MIN_IDX_EXT]]
; CHECK-NEXT:    [[GEP_OFFSET:%.*]] = getelementptr i8, ptr [[GEP_TYPED]], i64 -4
; CHECK-NEXT:    [[VAL_MIN:%.*]] = load float, ptr [[GEP_OFFSET]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[VAL_FIRST]], [[VAL_MIN]]
; CHECK-NEXT:    [[NEW_IDX:%.*]] = trunc nsw i64 [[IV_NEXT]] to i32
; CHECK-NEXT:    [[MIN_IDX_NEXT]] = select i1 [[CMP]], i32 [[NEW_IDX]], i32 [[MIN_IDX]]
; CHECK-NEXT:    [[BASE_PTR_NEXT]] = getelementptr float, ptr [[BASE_PTR]], i64 4
; CHECK-NEXT:    [[CTR_NEXT]] = add nsw i64 [[CTR]], -1
; CHECK-NEXT:    [[COND:%.*]] = icmp samesign ugt i64 [[CTR]], 1
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 [[MIN_IDX_NEXT]]
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 3, %entry ], [ %iv.next, %loop ]
  %ctr = phi i64 [ 3, %entry ], [ %ctr.next, %loop ]
  %min.idx = phi i32 [ 1, %entry ], [ %min.idx.next, %loop ]
  %base.ptr = phi ptr [ %arr, %entry ], [ %base.ptr.next, %loop ]
  %iv.next = add nsw i64 %iv, -1
  %ptr.iv = getelementptr float, ptr %base.ptr, i64 %iv
  %ptr.first = getelementptr i8, ptr %ptr.iv, i64 -8
  %val.first = load float, ptr %ptr.first, align 4
  %min.idx.ext = sext i32 %min.idx to i64
  %gep.typed = getelementptr float, ptr %base.ptr, i64 %min.idx.ext
  %gep.offset = getelementptr i8, ptr %gep.typed, i64 -4
  %val.min = load float, ptr %gep.offset, align 4
  %cmp = fcmp olt float %val.first, %val.min
  %new.idx = trunc nsw i64 %iv.next to i32
  %min.idx.next = select i1 %cmp, i32 %new.idx, i32 %min.idx
  %base.ptr.next = getelementptr float, ptr %base.ptr, i64 4
  %ctr.next = add nsw i64 %ctr, -1
  %cond = icmp samesign ugt i64 %ctr, 1
  br i1 %cond, label %loop, label %exit

exit:
  ret i32 %min.idx.next
}

; Negative test: IndexValPhi is defined in an outer-loop block, not the
; inner loop containing the select; the preheader-lookup would assert.
define i32 @test_indexvalphi_in_outer_loop(ptr %a) {
; CHECK-LABEL: define i32 @test_indexvalphi_in_outer_loop(
; CHECK-SAME: ptr [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[IDX_OUTER:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[IDX_NEXT:%.*]], %[[LOOP:.*]] ]
; CHECK-NEXT:    [[IDX_EXT_PHI_TRANS_INSERT:%.*]] = sext i32 [[IDX_OUTER]] to i64
; CHECK-NEXT:    [[RHS_GEP1_PHI_TRANS_INSERT:%.*]] = getelementptr i32, ptr [[A]], i64 [[IDX_EXT_PHI_TRANS_INSERT]]
; CHECK-NEXT:    [[RHS_GEP2_PHI_TRANS_INSERT:%.*]] = getelementptr i8, ptr [[RHS_GEP1_PHI_TRANS_INSERT]], i64 -4
; CHECK-NEXT:    [[RHS_PRE:%.*]] = load i32, ptr [[RHS_GEP2_PHI_TRANS_INSERT]], align 4
; CHECK-NEXT:    br label %[[LOOP]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 1, %[[OUTER]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[CNT:%.*]] = phi i32 [ 0, %[[OUTER]] ], [ [[CNT_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[LHS_GEP:%.*]] = getelementptr i32, ptr [[A]], i64 [[IV]]
; CHECK-NEXT:    [[LHS:%.*]] = load i32, ptr [[LHS_GEP]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[LHS]], [[RHS_PRE]]
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 1
; CHECK-NEXT:    [[NEWIDX:%.*]] = trunc i64 [[IV_NEXT]] to i32
; CHECK-NEXT:    [[IDX_NEXT]] = select i1 [[CMP]], i32 [[NEWIDX]], i32 [[IDX_OUTER]]
; CHECK-NEXT:    [[CNT_NEXT]] = add i32 [[CNT]], 1
; CHECK-NEXT:    [[CONT:%.*]] = icmp ult i32 [[CNT]], 1
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[OUTER]]
;
entry:
  br label %outer
outer:
  %idx.outer = phi i32 [ 1, %entry ], [ %idx.next, %loop ]
  br label %loop
loop:
  %iv = phi i64 [ 1, %outer ], [ %iv.next, %loop ]
  %cnt = phi i32 [ 0, %outer ], [ %cnt.next, %loop ]
  %lhs.gep = getelementptr i32, ptr %a, i64 %iv
  %lhs = load i32, ptr %lhs.gep, align 4
  %idx.ext = sext i32 %idx.outer to i64
  %rhs.gep1 = getelementptr i32, ptr %a, i64 %idx.ext
  %rhs.gep2 = getelementptr i8, ptr %rhs.gep1, i64 -4
  %rhs = load i32, ptr %rhs.gep2, align 4
  %cmp = icmp slt i32 %lhs, %rhs
  %iv.next = add i64 %iv, 1
  %newidx = trunc i64 %iv.next to i32
  %idx.next = select i1 %cmp, i32 %newidx, i32 %idx.outer
  %cnt.next = add i32 %cnt, 1
  %cont = icmp ult i32 %cnt, 1
  br i1 %cont, label %loop, label %outer
}

; Negative test: a post-load store in the loop body aliases the
; hoistable load's location on the next iteration. Memoizing the
; value across iterations would observe a stale value.
define i32 @test_backedge_store_clobbers_hoistable_load(ptr %arr) {
; CHECK-LABEL: define i32 @test_backedge_store_clobbers_hoistable_load(
; CHECK-SAME: ptr [[ARR:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 1, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[CNT:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[CNT_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MIN_IDX:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[MIN_IDX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[PTR_CUR:%.*]] = getelementptr i32, ptr [[ARR]], i64 [[IV]]
; CHECK-NEXT:    [[VAL_FIRST:%.*]] = load i32, ptr [[PTR_CUR]], align 4
; CHECK-NEXT:    [[MIN_EXT:%.*]] = sext i32 [[MIN_IDX]] to i64
; CHECK-NEXT:    [[PTR_MIN_BASE:%.*]] = getelementptr i32, ptr [[ARR]], i64 [[MIN_EXT]]
; CHECK-NEXT:    [[PTR_SECOND:%.*]] = getelementptr i8, ptr [[PTR_MIN_BASE]], i64 -4
; CHECK-NEXT:    [[VAL_CURRENT_MIN:%.*]] = load i32, ptr [[PTR_SECOND]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[VAL_FIRST]], [[VAL_CURRENT_MIN]]
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 1
; CHECK-NEXT:    [[NEXT_IDX_TRUNC:%.*]] = trunc i64 [[IV_NEXT]] to i32
; CHECK-NEXT:    [[MIN_IDX_NEXT]] = select i1 [[CMP]], i32 [[NEXT_IDX_TRUNC]], i32 [[MIN_IDX]]
; CHECK-NEXT:    store i32 0, ptr [[PTR_CUR]], align 4
; CHECK-NEXT:    [[CNT_NEXT]] = add i64 [[CNT]], 1
; CHECK-NEXT:    [[CONT:%.*]] = icmp ult i64 [[CNT_NEXT]], 2
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 [[MIN_IDX_NEXT]]
;
entry:
  br label %loop
loop:
  %iv = phi i64 [ 1, %entry ], [ %iv.next, %loop ]
  %cnt = phi i64 [ 0, %entry ], [ %cnt.next, %loop ]
  %min.idx = phi i32 [ 1, %entry ], [ %min.idx.next, %loop ]
  %ptr.cur = getelementptr i32, ptr %arr, i64 %iv
  %val.first = load i32, ptr %ptr.cur, align 4
  %min.ext = sext i32 %min.idx to i64
  %ptr.min.base = getelementptr i32, ptr %arr, i64 %min.ext
  %ptr.second = getelementptr i8, ptr %ptr.min.base, i64 -4
  %val.current.min = load i32, ptr %ptr.second, align 4
  %cmp = icmp slt i32 %val.first, %val.current.min
  %iv.next = add i64 %iv, 1
  %next.idx.trunc = trunc i64 %iv.next to i32
  %min.idx.next = select i1 %cmp, i32 %next.idx.trunc, i32 %min.idx
  store i32 0, ptr %ptr.cur, align 4
  %cnt.next = add i64 %cnt, 1
  %cont = icmp ult i64 %cnt.next, 2
  br i1 %cont, label %loop, label %exit
exit:
  ret i32 %min.idx.next
}

; Negative test: hoistable load is unordered-atomic. Memoizing across
; iterations would drop the per-iteration atomic semantics.
define i32 @test_atomic_hoistable_load(ptr %a) {
; CHECK-LABEL: define i32 @test_atomic_hoistable_load(
; CHECK-SAME: ptr [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 3, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[CTR:%.*]] = phi i64 [ 3, %[[ENTRY]] ], [ [[CTR_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[IDX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], -1
; CHECK-NEXT:    [[LHS_GEP:%.*]] = getelementptr i32, ptr [[A]], i64 [[IV]]
; CHECK-NEXT:    [[LHS:%.*]] = load i32, ptr [[LHS_GEP]], align 4
; CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[IDX]] to i64
; CHECK-NEXT:    [[RHS_GEP1:%.*]] = getelementptr i32, ptr [[A]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[RHS_GEP2:%.*]] = getelementptr i8, ptr [[RHS_GEP1]], i64 -4
; CHECK-NEXT:    [[RHS:%.*]] = load atomic i32, ptr [[RHS_GEP2]] unordered, align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[LHS]], [[RHS]]
; CHECK-NEXT:    [[NEWIDX:%.*]] = trunc nsw i64 [[IV_NEXT]] to i32
; CHECK-NEXT:    [[IDX_NEXT]] = select i1 [[CMP]], i32 [[NEWIDX]], i32 [[IDX]]
; CHECK-NEXT:    [[CTR_NEXT]] = add nsw i64 [[CTR]], -1
; CHECK-NEXT:    [[CONT:%.*]] = icmp samesign ugt i64 [[CTR]], 1
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 [[IDX_NEXT]]
;
entry:
  br label %loop
loop:
  %iv = phi i64 [ 3, %entry ], [ %iv.next, %loop ]
  %ctr = phi i64 [ 3, %entry ], [ %ctr.next, %loop ]
  %idx = phi i32 [ 1, %entry ], [ %idx.next, %loop ]
  %iv.next = add nsw i64 %iv, -1
  %lhs.gep = getelementptr i32, ptr %a, i64 %iv
  %lhs = load i32, ptr %lhs.gep, align 4
  %idx.ext = sext i32 %idx to i64
  %rhs.gep1 = getelementptr i32, ptr %a, i64 %idx.ext
  %rhs.gep2 = getelementptr i8, ptr %rhs.gep1, i64 -4
  %rhs = load atomic i32, ptr %rhs.gep2 unordered, align 4
  %cmp = icmp slt i32 %lhs, %rhs
  %newidx = trunc nsw i64 %iv.next to i32
  %idx.next = select i1 %cmp, i32 %newidx, i32 %idx
  %ctr.next = add nsw i64 %ctr, -1
  %cont = icmp samesign ugt i64 %ctr, 1
  br i1 %cont, label %loop, label %exit
exit:
  ret i32 %idx.next
}

; Negative test: select's new-index sits on the false arm. The transform
; plants `select Cmp, LHS, KnownMin`, so this polarity is unsupported.
define i32 @test_new_index_on_false_arm(ptr %a) {
; CHECK-LABEL: define i32 @test_new_index_on_false_arm(
; CHECK-SAME: ptr [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 1, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[CNT:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[CNT_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[IDX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[LHS_GEP:%.*]] = getelementptr i32, ptr [[A]], i64 [[IV]]
; CHECK-NEXT:    [[LHS:%.*]] = load i32, ptr [[LHS_GEP]], align 4
; CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[IDX]] to i64
; CHECK-NEXT:    [[RHS_GEP1:%.*]] = getelementptr i32, ptr [[A]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[RHS_GEP2:%.*]] = getelementptr i8, ptr [[RHS_GEP1]], i64 -4
; CHECK-NEXT:    [[RHS:%.*]] = load i32, ptr [[RHS_GEP2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[LHS]], [[RHS]]
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 1
; CHECK-NEXT:    [[NEWIDX:%.*]] = trunc i64 [[IV_NEXT]] to i32
; CHECK-NEXT:    [[IDX_NEXT]] = select i1 [[CMP]], i32 [[IDX]], i32 [[NEWIDX]]
; CHECK-NEXT:    [[CNT_NEXT]] = add i32 [[CNT]], 1
; CHECK-NEXT:    [[CONT:%.*]] = icmp ult i32 [[CNT]], 1
; CHECK-NEXT:    br i1 [[CONT]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 [[IDX_NEXT]]
;
entry:
  br label %loop
loop:
  %iv = phi i64 [ 1, %entry ], [ %iv.next, %loop ]
  %cnt = phi i32 [ 0, %entry ], [ %cnt.next, %loop ]
  %idx = phi i32 [ 1, %entry ], [ %idx.next, %loop ]
  %lhs.gep = getelementptr i32, ptr %a, i64 %iv
  %lhs = load i32, ptr %lhs.gep, align 4
  %idx.ext = sext i32 %idx to i64
  %rhs.gep1 = getelementptr i32, ptr %a, i64 %idx.ext
  %rhs.gep2 = getelementptr i8, ptr %rhs.gep1, i64 -4
  %rhs = load i32, ptr %rhs.gep2, align 4
  %cmp = icmp slt i32 %lhs, %rhs
  %iv.next = add i64 %iv, 1
  %newidx = trunc i64 %iv.next to i32
  %idx.next = select i1 %cmp, i32 %idx, i32 %newidx
  %cnt.next = add i32 %cnt, 1
  %cont = icmp ult i32 %cnt, 1
  br i1 %cont, label %loop, label %exit
exit:
  ret i32 %idx.next
}
