; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=gvn -enable-load-pre -S | FileCheck %s --check-prefixes=CHECK,MDEP
; RUN: opt < %s -passes='gvn<memoryssa>' -enable-load-pre -S | FileCheck %s --check-prefixes=CHECK,MSSA

; Ensure AA metadata are combined properly while hoisting the load.

@g_bool = global i8 0, align 1
@g_long = global i64 0, align 8

define void @test_combine_metadata(i1 %c, i64 %arg) {
; MDEP-LABEL: define void @test_combine_metadata(
; MDEP-SAME: i1 [[C:%.*]], i64 [[ARG:%.*]]) {
; MDEP-NEXT:  [[ENTRY:.*]]:
; MDEP-NEXT:    [[C3:%.*]] = alloca i8, align 1
; MDEP-NEXT:    br label %[[LOOP:.*]]
; MDEP:       [[LOOP]]:
; MDEP-NEXT:    [[PHI:%.*]] = phi ptr [ @g_long, %[[IF_THEN:.*]] ], [ [[C3]], %[[ENTRY]] ]
; MDEP-NEXT:    store i64 [[ARG]], ptr @g_long, align 8, !tbaa [[LONG_TBAA0:![0-9]+]]
; MDEP-NEXT:    [[TR:%.*]] = trunc i64 [[ARG]] to i8
; MDEP-NEXT:    store i8 [[TR]], ptr [[C3]], align 1, !tbaa [[_BOOL_TBAA4:![0-9]+]]
; MDEP-NEXT:    [[V1_PRE:%.*]] = load i8, ptr [[PHI]], align 1, !tbaa [[CHAR_TBAA6:![0-9]+]]
; MDEP-NEXT:    br i1 [[C]], label %[[IF_THEN]], label %[[IF_ELSE:.*]]
; MDEP:       [[IF_ELSE]]:
; MDEP-NEXT:    store i8 [[V1_PRE]], ptr @g_bool, align 8, !tbaa [[LONG_TBAA0]]
; MDEP-NEXT:    br label %[[IF_THEN]]
; MDEP:       [[IF_THEN]]:
; MDEP-NEXT:    store i8 [[V1_PRE]], ptr @g_bool, align 1
; MDEP-NEXT:    br label %[[LOOP]]
;
; MSSA-LABEL: define void @test_combine_metadata(
; MSSA-SAME: i1 [[C:%.*]], i64 [[ARG:%.*]]) {
; MSSA-NEXT:  [[ENTRY:.*]]:
; MSSA-NEXT:    [[C3:%.*]] = alloca i8, align 1
; MSSA-NEXT:    br label %[[LOOP:.*]]
; MSSA:       [[LOOP]]:
; MSSA-NEXT:    [[PHI:%.*]] = phi ptr [ @g_long, %[[IF_THEN:.*]] ], [ [[C3]], %[[ENTRY]] ]
; MSSA-NEXT:    store i64 [[ARG]], ptr @g_long, align 8, !tbaa [[LONG_TBAA0:![0-9]+]]
; MSSA-NEXT:    [[TR:%.*]] = trunc i64 [[ARG]] to i8
; MSSA-NEXT:    store i8 [[TR]], ptr [[C3]], align 1, !tbaa [[_BOOL_TBAA4:![0-9]+]]
; MSSA-NEXT:    br i1 [[C]], label %[[IF_THEN]], label %[[IF_ELSE:.*]]
; MSSA:       [[IF_ELSE]]:
; MSSA-NEXT:    [[V2:%.*]] = load i8, ptr [[PHI]], align 1, !tbaa [[CHAR_TBAA6:![0-9]+]]
; MSSA-NEXT:    store i8 [[V2]], ptr @g_bool, align 8, !tbaa [[LONG_TBAA0]]
; MSSA-NEXT:    br label %[[IF_THEN]]
; MSSA:       [[IF_THEN]]:
; MSSA-NEXT:    [[V1:%.*]] = load i8, ptr [[PHI]], align 1, !tbaa [[_BOOL_TBAA4]]
; MSSA-NEXT:    store i8 [[V1]], ptr @g_bool, align 1
; MSSA-NEXT:    br label %[[LOOP]]
;
entry:
  %val = alloca i8, align 1
  br label %loop

loop:
  %phi = phi ptr [ @g_long, %if.then ], [ %val, %entry ]
  store i64 %arg, ptr @g_long, align 8, !tbaa !3
  %trunc = trunc i64 %arg to i8
  store i8 %trunc, ptr %val, align 1, !tbaa !5
  br i1 %c, label %if.then, label %if.else

if.else:
  %v2 = load i8, ptr %phi, align 1, !tbaa !7
  store i8 %v2, ptr @g_bool, align 8, !tbaa !3
  br label %if.then

if.then:
  %v1 = load i8, ptr %phi, align 1, !tbaa !5
  store i8 %v1, ptr @g_bool, align 1
  br label %loop
}

!0 = !{!"Simple C/C++ TBAA"}
!1 = !{!"omnipotent char", !0, i64 0}
!2 = !{!"long", !1, i64 0}
!3 = !{!2, !2, i64 0}
!4 = !{!"_Bool", !1, i64 0}
!5 = !{!4, !4, i64 0}
!7 = !{!1, !1, i64 0}
;.
; MDEP: [[LONG_TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; MDEP: [[META1]] = !{!"long", [[META2:![0-9]+]], i64 0}
; MDEP: [[META2]] = !{!"omnipotent char", [[META3:![0-9]+]], i64 0}
; MDEP: [[META3]] = !{!"Simple C/C++ TBAA"}
; MDEP: [[_BOOL_TBAA4]] = !{[[META5:![0-9]+]], [[META5]], i64 0}
; MDEP: [[META5]] = !{!"_Bool", [[META2]], i64 0}
; MDEP: [[CHAR_TBAA6]] = !{[[META2]], [[META2]], i64 0}
;.
; MSSA: [[LONG_TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; MSSA: [[META1]] = !{!"long", [[META2:![0-9]+]], i64 0}
; MSSA: [[META2]] = !{!"omnipotent char", [[META3:![0-9]+]], i64 0}
; MSSA: [[META3]] = !{!"Simple C/C++ TBAA"}
; MSSA: [[_BOOL_TBAA4]] = !{[[META5:![0-9]+]], [[META5]], i64 0}
; MSSA: [[META5]] = !{!"_Bool", [[META2]], i64 0}
; MSSA: [[CHAR_TBAA6]] = !{[[META2]], [[META2]], i64 0}
;.
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
