; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S < %s -passes='loop-unroll,load-store-vectorizer' -unroll-count=128 --capture-tracking-max-uses-to-explore=1024 | FileCheck %s

; Without using batching alias analysis, this test takes 6 seconds to compile. With, less than a second.
; This is because the mechanism that proves NoAlias in this case is very expensive (CaptureTracking.cpp),
; and caching the result leads to 2 calls to that mechanism instead of ~300,000 (run with -stats to see the difference)

; This test only demonstrates the compile time issue if capture-tracking-max-uses-to-explore is set to at least 1024,
; because with the default value of 100, the CaptureTracking analysis is not run, NoAlias is not proven, and the vectorizer gives up early.

@global_mem = external global i8, align 4

define void @compile-time-test() {
; CHECK-LABEL: define void @compile-time-test() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[GLOBAL_BASE_LOADS:%.*]] = getelementptr i8, ptr inttoptr (i32 ptrtoint (ptr @global_mem to i32) to ptr), i64 0
; CHECK-NEXT:    [[LOCAL_BASE_STORES:%.*]] = alloca <512 x i8>, align 4
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load <4 x i8>, ptr [[GLOBAL_BASE_LOADS]], align 4
; CHECK-NEXT:    [[LOAD_01:%.*]] = extractelement <4 x i8> [[TMP0]], i32 0
; CHECK-NEXT:    [[LOAD_12:%.*]] = extractelement <4 x i8> [[TMP0]], i32 1
; CHECK-NEXT:    [[LOAD_23:%.*]] = extractelement <4 x i8> [[TMP0]], i32 2
; CHECK-NEXT:    [[LOAD_34:%.*]] = extractelement <4 x i8> [[TMP0]], i32 3
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_01]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <4 x i8> [[TMP1]], i8 [[LOAD_12]], i32 1
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <4 x i8> [[TMP2]], i8 [[LOAD_23]], i32 2
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <4 x i8> [[TMP3]], i8 [[LOAD_34]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP4]], ptr [[LOCAL_BASE_STORES]], align 4
; CHECK-NEXT:    [[PTR_0_1:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 4
; CHECK-NEXT:    [[TMP5:%.*]] = load <4 x i8>, ptr [[PTR_0_1]], align 4
; CHECK-NEXT:    [[LOAD_0_128:%.*]] = extractelement <4 x i8> [[TMP5]], i32 0
; CHECK-NEXT:    [[LOAD_1_129:%.*]] = extractelement <4 x i8> [[TMP5]], i32 1
; CHECK-NEXT:    [[LOAD_2_130:%.*]] = extractelement <4 x i8> [[TMP5]], i32 2
; CHECK-NEXT:    [[LOAD_3_131:%.*]] = extractelement <4 x i8> [[TMP5]], i32 3
; CHECK-NEXT:    [[PTR2_0_1:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 4
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_128]], i32 0
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <4 x i8> [[TMP6]], i8 [[LOAD_1_129]], i32 1
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x i8> [[TMP7]], i8 [[LOAD_2_130]], i32 2
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <4 x i8> [[TMP8]], i8 [[LOAD_3_131]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP9]], ptr [[PTR2_0_1]], align 4
; CHECK-NEXT:    [[PTR_0_2:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 8
; CHECK-NEXT:    [[TMP10:%.*]] = load <4 x i8>, ptr [[PTR_0_2]], align 4
; CHECK-NEXT:    [[LOAD_0_232:%.*]] = extractelement <4 x i8> [[TMP10]], i32 0
; CHECK-NEXT:    [[LOAD_1_233:%.*]] = extractelement <4 x i8> [[TMP10]], i32 1
; CHECK-NEXT:    [[LOAD_2_234:%.*]] = extractelement <4 x i8> [[TMP10]], i32 2
; CHECK-NEXT:    [[LOAD_3_235:%.*]] = extractelement <4 x i8> [[TMP10]], i32 3
; CHECK-NEXT:    [[PTR2_0_2:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 8
; CHECK-NEXT:    [[TMP11:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_232]], i32 0
; CHECK-NEXT:    [[TMP12:%.*]] = insertelement <4 x i8> [[TMP11]], i8 [[LOAD_1_233]], i32 1
; CHECK-NEXT:    [[TMP13:%.*]] = insertelement <4 x i8> [[TMP12]], i8 [[LOAD_2_234]], i32 2
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <4 x i8> [[TMP13]], i8 [[LOAD_3_235]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP14]], ptr [[PTR2_0_2]], align 4
; CHECK-NEXT:    [[PTR_0_3:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 12
; CHECK-NEXT:    [[TMP15:%.*]] = load <4 x i8>, ptr [[PTR_0_3]], align 4
; CHECK-NEXT:    [[LOAD_0_336:%.*]] = extractelement <4 x i8> [[TMP15]], i32 0
; CHECK-NEXT:    [[LOAD_1_337:%.*]] = extractelement <4 x i8> [[TMP15]], i32 1
; CHECK-NEXT:    [[LOAD_2_338:%.*]] = extractelement <4 x i8> [[TMP15]], i32 2
; CHECK-NEXT:    [[LOAD_3_339:%.*]] = extractelement <4 x i8> [[TMP15]], i32 3
; CHECK-NEXT:    [[PTR2_0_3:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 12
; CHECK-NEXT:    [[TMP16:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_336]], i32 0
; CHECK-NEXT:    [[TMP17:%.*]] = insertelement <4 x i8> [[TMP16]], i8 [[LOAD_1_337]], i32 1
; CHECK-NEXT:    [[TMP18:%.*]] = insertelement <4 x i8> [[TMP17]], i8 [[LOAD_2_338]], i32 2
; CHECK-NEXT:    [[TMP19:%.*]] = insertelement <4 x i8> [[TMP18]], i8 [[LOAD_3_339]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP19]], ptr [[PTR2_0_3]], align 4
; CHECK-NEXT:    [[PTR_0_4:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 16
; CHECK-NEXT:    [[TMP20:%.*]] = load <4 x i8>, ptr [[PTR_0_4]], align 4
; CHECK-NEXT:    [[LOAD_0_440:%.*]] = extractelement <4 x i8> [[TMP20]], i32 0
; CHECK-NEXT:    [[LOAD_1_441:%.*]] = extractelement <4 x i8> [[TMP20]], i32 1
; CHECK-NEXT:    [[LOAD_2_442:%.*]] = extractelement <4 x i8> [[TMP20]], i32 2
; CHECK-NEXT:    [[LOAD_3_443:%.*]] = extractelement <4 x i8> [[TMP20]], i32 3
; CHECK-NEXT:    [[PTR2_0_4:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 16
; CHECK-NEXT:    [[TMP21:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_440]], i32 0
; CHECK-NEXT:    [[TMP22:%.*]] = insertelement <4 x i8> [[TMP21]], i8 [[LOAD_1_441]], i32 1
; CHECK-NEXT:    [[TMP23:%.*]] = insertelement <4 x i8> [[TMP22]], i8 [[LOAD_2_442]], i32 2
; CHECK-NEXT:    [[TMP24:%.*]] = insertelement <4 x i8> [[TMP23]], i8 [[LOAD_3_443]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP24]], ptr [[PTR2_0_4]], align 4
; CHECK-NEXT:    [[PTR_0_5:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 20
; CHECK-NEXT:    [[TMP25:%.*]] = load <4 x i8>, ptr [[PTR_0_5]], align 4
; CHECK-NEXT:    [[LOAD_0_544:%.*]] = extractelement <4 x i8> [[TMP25]], i32 0
; CHECK-NEXT:    [[LOAD_1_545:%.*]] = extractelement <4 x i8> [[TMP25]], i32 1
; CHECK-NEXT:    [[LOAD_2_546:%.*]] = extractelement <4 x i8> [[TMP25]], i32 2
; CHECK-NEXT:    [[LOAD_3_547:%.*]] = extractelement <4 x i8> [[TMP25]], i32 3
; CHECK-NEXT:    [[PTR2_0_5:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 20
; CHECK-NEXT:    [[TMP26:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_544]], i32 0
; CHECK-NEXT:    [[TMP27:%.*]] = insertelement <4 x i8> [[TMP26]], i8 [[LOAD_1_545]], i32 1
; CHECK-NEXT:    [[TMP28:%.*]] = insertelement <4 x i8> [[TMP27]], i8 [[LOAD_2_546]], i32 2
; CHECK-NEXT:    [[TMP29:%.*]] = insertelement <4 x i8> [[TMP28]], i8 [[LOAD_3_547]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP29]], ptr [[PTR2_0_5]], align 4
; CHECK-NEXT:    [[PTR_0_6:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 24
; CHECK-NEXT:    [[TMP30:%.*]] = load <4 x i8>, ptr [[PTR_0_6]], align 4
; CHECK-NEXT:    [[LOAD_0_648:%.*]] = extractelement <4 x i8> [[TMP30]], i32 0
; CHECK-NEXT:    [[LOAD_1_649:%.*]] = extractelement <4 x i8> [[TMP30]], i32 1
; CHECK-NEXT:    [[LOAD_2_650:%.*]] = extractelement <4 x i8> [[TMP30]], i32 2
; CHECK-NEXT:    [[LOAD_3_651:%.*]] = extractelement <4 x i8> [[TMP30]], i32 3
; CHECK-NEXT:    [[PTR2_0_6:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 24
; CHECK-NEXT:    [[TMP31:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_648]], i32 0
; CHECK-NEXT:    [[TMP32:%.*]] = insertelement <4 x i8> [[TMP31]], i8 [[LOAD_1_649]], i32 1
; CHECK-NEXT:    [[TMP33:%.*]] = insertelement <4 x i8> [[TMP32]], i8 [[LOAD_2_650]], i32 2
; CHECK-NEXT:    [[TMP34:%.*]] = insertelement <4 x i8> [[TMP33]], i8 [[LOAD_3_651]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP34]], ptr [[PTR2_0_6]], align 4
; CHECK-NEXT:    [[PTR_0_7:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 28
; CHECK-NEXT:    [[TMP35:%.*]] = load <4 x i8>, ptr [[PTR_0_7]], align 4
; CHECK-NEXT:    [[LOAD_0_752:%.*]] = extractelement <4 x i8> [[TMP35]], i32 0
; CHECK-NEXT:    [[LOAD_1_753:%.*]] = extractelement <4 x i8> [[TMP35]], i32 1
; CHECK-NEXT:    [[LOAD_2_754:%.*]] = extractelement <4 x i8> [[TMP35]], i32 2
; CHECK-NEXT:    [[LOAD_3_755:%.*]] = extractelement <4 x i8> [[TMP35]], i32 3
; CHECK-NEXT:    [[PTR2_0_7:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 28
; CHECK-NEXT:    [[TMP36:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_752]], i32 0
; CHECK-NEXT:    [[TMP37:%.*]] = insertelement <4 x i8> [[TMP36]], i8 [[LOAD_1_753]], i32 1
; CHECK-NEXT:    [[TMP38:%.*]] = insertelement <4 x i8> [[TMP37]], i8 [[LOAD_2_754]], i32 2
; CHECK-NEXT:    [[TMP39:%.*]] = insertelement <4 x i8> [[TMP38]], i8 [[LOAD_3_755]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP39]], ptr [[PTR2_0_7]], align 4
; CHECK-NEXT:    [[PTR_0_8:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 32
; CHECK-NEXT:    [[TMP40:%.*]] = load <4 x i8>, ptr [[PTR_0_8]], align 4
; CHECK-NEXT:    [[LOAD_0_856:%.*]] = extractelement <4 x i8> [[TMP40]], i32 0
; CHECK-NEXT:    [[LOAD_1_857:%.*]] = extractelement <4 x i8> [[TMP40]], i32 1
; CHECK-NEXT:    [[LOAD_2_858:%.*]] = extractelement <4 x i8> [[TMP40]], i32 2
; CHECK-NEXT:    [[LOAD_3_859:%.*]] = extractelement <4 x i8> [[TMP40]], i32 3
; CHECK-NEXT:    [[PTR2_0_8:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 32
; CHECK-NEXT:    [[TMP41:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_856]], i32 0
; CHECK-NEXT:    [[TMP42:%.*]] = insertelement <4 x i8> [[TMP41]], i8 [[LOAD_1_857]], i32 1
; CHECK-NEXT:    [[TMP43:%.*]] = insertelement <4 x i8> [[TMP42]], i8 [[LOAD_2_858]], i32 2
; CHECK-NEXT:    [[TMP44:%.*]] = insertelement <4 x i8> [[TMP43]], i8 [[LOAD_3_859]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP44]], ptr [[PTR2_0_8]], align 4
; CHECK-NEXT:    [[PTR_0_9:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 36
; CHECK-NEXT:    [[TMP45:%.*]] = load <4 x i8>, ptr [[PTR_0_9]], align 4
; CHECK-NEXT:    [[LOAD_0_960:%.*]] = extractelement <4 x i8> [[TMP45]], i32 0
; CHECK-NEXT:    [[LOAD_1_961:%.*]] = extractelement <4 x i8> [[TMP45]], i32 1
; CHECK-NEXT:    [[LOAD_2_962:%.*]] = extractelement <4 x i8> [[TMP45]], i32 2
; CHECK-NEXT:    [[LOAD_3_963:%.*]] = extractelement <4 x i8> [[TMP45]], i32 3
; CHECK-NEXT:    [[PTR2_0_9:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 36
; CHECK-NEXT:    [[TMP46:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_960]], i32 0
; CHECK-NEXT:    [[TMP47:%.*]] = insertelement <4 x i8> [[TMP46]], i8 [[LOAD_1_961]], i32 1
; CHECK-NEXT:    [[TMP48:%.*]] = insertelement <4 x i8> [[TMP47]], i8 [[LOAD_2_962]], i32 2
; CHECK-NEXT:    [[TMP49:%.*]] = insertelement <4 x i8> [[TMP48]], i8 [[LOAD_3_963]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP49]], ptr [[PTR2_0_9]], align 4
; CHECK-NEXT:    [[PTR_0_10:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 40
; CHECK-NEXT:    [[TMP50:%.*]] = load <4 x i8>, ptr [[PTR_0_10]], align 4
; CHECK-NEXT:    [[LOAD_0_1064:%.*]] = extractelement <4 x i8> [[TMP50]], i32 0
; CHECK-NEXT:    [[LOAD_1_1065:%.*]] = extractelement <4 x i8> [[TMP50]], i32 1
; CHECK-NEXT:    [[LOAD_2_1066:%.*]] = extractelement <4 x i8> [[TMP50]], i32 2
; CHECK-NEXT:    [[LOAD_3_1067:%.*]] = extractelement <4 x i8> [[TMP50]], i32 3
; CHECK-NEXT:    [[PTR2_0_10:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 40
; CHECK-NEXT:    [[TMP51:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_1064]], i32 0
; CHECK-NEXT:    [[TMP52:%.*]] = insertelement <4 x i8> [[TMP51]], i8 [[LOAD_1_1065]], i32 1
; CHECK-NEXT:    [[TMP53:%.*]] = insertelement <4 x i8> [[TMP52]], i8 [[LOAD_2_1066]], i32 2
; CHECK-NEXT:    [[TMP54:%.*]] = insertelement <4 x i8> [[TMP53]], i8 [[LOAD_3_1067]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP54]], ptr [[PTR2_0_10]], align 4
; CHECK-NEXT:    [[PTR_0_11:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 44
; CHECK-NEXT:    [[TMP55:%.*]] = load <4 x i8>, ptr [[PTR_0_11]], align 4
; CHECK-NEXT:    [[LOAD_0_1168:%.*]] = extractelement <4 x i8> [[TMP55]], i32 0
; CHECK-NEXT:    [[LOAD_1_1169:%.*]] = extractelement <4 x i8> [[TMP55]], i32 1
; CHECK-NEXT:    [[LOAD_2_1170:%.*]] = extractelement <4 x i8> [[TMP55]], i32 2
; CHECK-NEXT:    [[LOAD_3_1171:%.*]] = extractelement <4 x i8> [[TMP55]], i32 3
; CHECK-NEXT:    [[PTR2_0_11:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 44
; CHECK-NEXT:    [[TMP56:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_1168]], i32 0
; CHECK-NEXT:    [[TMP57:%.*]] = insertelement <4 x i8> [[TMP56]], i8 [[LOAD_1_1169]], i32 1
; CHECK-NEXT:    [[TMP58:%.*]] = insertelement <4 x i8> [[TMP57]], i8 [[LOAD_2_1170]], i32 2
; CHECK-NEXT:    [[TMP59:%.*]] = insertelement <4 x i8> [[TMP58]], i8 [[LOAD_3_1171]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP59]], ptr [[PTR2_0_11]], align 4
; CHECK-NEXT:    [[PTR_0_12:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 48
; CHECK-NEXT:    [[TMP60:%.*]] = load <4 x i8>, ptr [[PTR_0_12]], align 4
; CHECK-NEXT:    [[LOAD_0_1272:%.*]] = extractelement <4 x i8> [[TMP60]], i32 0
; CHECK-NEXT:    [[LOAD_1_1273:%.*]] = extractelement <4 x i8> [[TMP60]], i32 1
; CHECK-NEXT:    [[LOAD_2_1274:%.*]] = extractelement <4 x i8> [[TMP60]], i32 2
; CHECK-NEXT:    [[LOAD_3_1275:%.*]] = extractelement <4 x i8> [[TMP60]], i32 3
; CHECK-NEXT:    [[PTR2_0_12:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 48
; CHECK-NEXT:    [[TMP61:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_1272]], i32 0
; CHECK-NEXT:    [[TMP62:%.*]] = insertelement <4 x i8> [[TMP61]], i8 [[LOAD_1_1273]], i32 1
; CHECK-NEXT:    [[TMP63:%.*]] = insertelement <4 x i8> [[TMP62]], i8 [[LOAD_2_1274]], i32 2
; CHECK-NEXT:    [[TMP64:%.*]] = insertelement <4 x i8> [[TMP63]], i8 [[LOAD_3_1275]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP64]], ptr [[PTR2_0_12]], align 4
; CHECK-NEXT:    [[PTR_0_13:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 52
; CHECK-NEXT:    [[TMP65:%.*]] = load <4 x i8>, ptr [[PTR_0_13]], align 4
; CHECK-NEXT:    [[LOAD_0_1376:%.*]] = extractelement <4 x i8> [[TMP65]], i32 0
; CHECK-NEXT:    [[LOAD_1_1377:%.*]] = extractelement <4 x i8> [[TMP65]], i32 1
; CHECK-NEXT:    [[LOAD_2_1378:%.*]] = extractelement <4 x i8> [[TMP65]], i32 2
; CHECK-NEXT:    [[LOAD_3_1379:%.*]] = extractelement <4 x i8> [[TMP65]], i32 3
; CHECK-NEXT:    [[PTR2_0_13:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 52
; CHECK-NEXT:    [[TMP66:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_1376]], i32 0
; CHECK-NEXT:    [[TMP67:%.*]] = insertelement <4 x i8> [[TMP66]], i8 [[LOAD_1_1377]], i32 1
; CHECK-NEXT:    [[TMP68:%.*]] = insertelement <4 x i8> [[TMP67]], i8 [[LOAD_2_1378]], i32 2
; CHECK-NEXT:    [[TMP69:%.*]] = insertelement <4 x i8> [[TMP68]], i8 [[LOAD_3_1379]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP69]], ptr [[PTR2_0_13]], align 4
; CHECK-NEXT:    [[PTR_0_14:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 56
; CHECK-NEXT:    [[TMP70:%.*]] = load <4 x i8>, ptr [[PTR_0_14]], align 4
; CHECK-NEXT:    [[LOAD_0_1480:%.*]] = extractelement <4 x i8> [[TMP70]], i32 0
; CHECK-NEXT:    [[LOAD_1_1481:%.*]] = extractelement <4 x i8> [[TMP70]], i32 1
; CHECK-NEXT:    [[LOAD_2_1482:%.*]] = extractelement <4 x i8> [[TMP70]], i32 2
; CHECK-NEXT:    [[LOAD_3_1483:%.*]] = extractelement <4 x i8> [[TMP70]], i32 3
; CHECK-NEXT:    [[PTR2_0_14:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 56
; CHECK-NEXT:    [[TMP71:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_1480]], i32 0
; CHECK-NEXT:    [[TMP72:%.*]] = insertelement <4 x i8> [[TMP71]], i8 [[LOAD_1_1481]], i32 1
; CHECK-NEXT:    [[TMP73:%.*]] = insertelement <4 x i8> [[TMP72]], i8 [[LOAD_2_1482]], i32 2
; CHECK-NEXT:    [[TMP74:%.*]] = insertelement <4 x i8> [[TMP73]], i8 [[LOAD_3_1483]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP74]], ptr [[PTR2_0_14]], align 4
; CHECK-NEXT:    [[PTR_0_15:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 60
; CHECK-NEXT:    [[TMP75:%.*]] = load <4 x i8>, ptr [[PTR_0_15]], align 4
; CHECK-NEXT:    [[LOAD_0_1584:%.*]] = extractelement <4 x i8> [[TMP75]], i32 0
; CHECK-NEXT:    [[LOAD_1_1585:%.*]] = extractelement <4 x i8> [[TMP75]], i32 1
; CHECK-NEXT:    [[LOAD_2_1586:%.*]] = extractelement <4 x i8> [[TMP75]], i32 2
; CHECK-NEXT:    [[LOAD_3_1587:%.*]] = extractelement <4 x i8> [[TMP75]], i32 3
; CHECK-NEXT:    [[PTR2_0_15:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 60
; CHECK-NEXT:    [[TMP76:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_1584]], i32 0
; CHECK-NEXT:    [[TMP77:%.*]] = insertelement <4 x i8> [[TMP76]], i8 [[LOAD_1_1585]], i32 1
; CHECK-NEXT:    [[TMP78:%.*]] = insertelement <4 x i8> [[TMP77]], i8 [[LOAD_2_1586]], i32 2
; CHECK-NEXT:    [[TMP79:%.*]] = insertelement <4 x i8> [[TMP78]], i8 [[LOAD_3_1587]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP79]], ptr [[PTR2_0_15]], align 4
; CHECK-NEXT:    [[PTR_0_16:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 64
; CHECK-NEXT:    [[TMP80:%.*]] = load <4 x i8>, ptr [[PTR_0_16]], align 4
; CHECK-NEXT:    [[LOAD_0_1688:%.*]] = extractelement <4 x i8> [[TMP80]], i32 0
; CHECK-NEXT:    [[LOAD_1_1689:%.*]] = extractelement <4 x i8> [[TMP80]], i32 1
; CHECK-NEXT:    [[LOAD_2_1690:%.*]] = extractelement <4 x i8> [[TMP80]], i32 2
; CHECK-NEXT:    [[LOAD_3_1691:%.*]] = extractelement <4 x i8> [[TMP80]], i32 3
; CHECK-NEXT:    [[PTR2_0_16:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 64
; CHECK-NEXT:    [[TMP81:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_1688]], i32 0
; CHECK-NEXT:    [[TMP82:%.*]] = insertelement <4 x i8> [[TMP81]], i8 [[LOAD_1_1689]], i32 1
; CHECK-NEXT:    [[TMP83:%.*]] = insertelement <4 x i8> [[TMP82]], i8 [[LOAD_2_1690]], i32 2
; CHECK-NEXT:    [[TMP84:%.*]] = insertelement <4 x i8> [[TMP83]], i8 [[LOAD_3_1691]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP84]], ptr [[PTR2_0_16]], align 4
; CHECK-NEXT:    [[PTR_0_17:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 68
; CHECK-NEXT:    [[TMP85:%.*]] = load <4 x i8>, ptr [[PTR_0_17]], align 4
; CHECK-NEXT:    [[LOAD_0_1792:%.*]] = extractelement <4 x i8> [[TMP85]], i32 0
; CHECK-NEXT:    [[LOAD_1_1793:%.*]] = extractelement <4 x i8> [[TMP85]], i32 1
; CHECK-NEXT:    [[LOAD_2_1794:%.*]] = extractelement <4 x i8> [[TMP85]], i32 2
; CHECK-NEXT:    [[LOAD_3_1795:%.*]] = extractelement <4 x i8> [[TMP85]], i32 3
; CHECK-NEXT:    [[PTR2_0_17:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 68
; CHECK-NEXT:    [[TMP86:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_1792]], i32 0
; CHECK-NEXT:    [[TMP87:%.*]] = insertelement <4 x i8> [[TMP86]], i8 [[LOAD_1_1793]], i32 1
; CHECK-NEXT:    [[TMP88:%.*]] = insertelement <4 x i8> [[TMP87]], i8 [[LOAD_2_1794]], i32 2
; CHECK-NEXT:    [[TMP89:%.*]] = insertelement <4 x i8> [[TMP88]], i8 [[LOAD_3_1795]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP89]], ptr [[PTR2_0_17]], align 4
; CHECK-NEXT:    [[PTR_0_18:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 72
; CHECK-NEXT:    [[TMP90:%.*]] = load <4 x i8>, ptr [[PTR_0_18]], align 4
; CHECK-NEXT:    [[LOAD_0_1896:%.*]] = extractelement <4 x i8> [[TMP90]], i32 0
; CHECK-NEXT:    [[LOAD_1_1897:%.*]] = extractelement <4 x i8> [[TMP90]], i32 1
; CHECK-NEXT:    [[LOAD_2_1898:%.*]] = extractelement <4 x i8> [[TMP90]], i32 2
; CHECK-NEXT:    [[LOAD_3_1899:%.*]] = extractelement <4 x i8> [[TMP90]], i32 3
; CHECK-NEXT:    [[PTR2_0_18:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 72
; CHECK-NEXT:    [[TMP91:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_1896]], i32 0
; CHECK-NEXT:    [[TMP92:%.*]] = insertelement <4 x i8> [[TMP91]], i8 [[LOAD_1_1897]], i32 1
; CHECK-NEXT:    [[TMP93:%.*]] = insertelement <4 x i8> [[TMP92]], i8 [[LOAD_2_1898]], i32 2
; CHECK-NEXT:    [[TMP94:%.*]] = insertelement <4 x i8> [[TMP93]], i8 [[LOAD_3_1899]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP94]], ptr [[PTR2_0_18]], align 4
; CHECK-NEXT:    [[PTR_0_19:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 76
; CHECK-NEXT:    [[TMP95:%.*]] = load <4 x i8>, ptr [[PTR_0_19]], align 4
; CHECK-NEXT:    [[LOAD_0_19100:%.*]] = extractelement <4 x i8> [[TMP95]], i32 0
; CHECK-NEXT:    [[LOAD_1_19101:%.*]] = extractelement <4 x i8> [[TMP95]], i32 1
; CHECK-NEXT:    [[LOAD_2_19102:%.*]] = extractelement <4 x i8> [[TMP95]], i32 2
; CHECK-NEXT:    [[LOAD_3_19103:%.*]] = extractelement <4 x i8> [[TMP95]], i32 3
; CHECK-NEXT:    [[PTR2_0_19:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 76
; CHECK-NEXT:    [[TMP96:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_19100]], i32 0
; CHECK-NEXT:    [[TMP97:%.*]] = insertelement <4 x i8> [[TMP96]], i8 [[LOAD_1_19101]], i32 1
; CHECK-NEXT:    [[TMP98:%.*]] = insertelement <4 x i8> [[TMP97]], i8 [[LOAD_2_19102]], i32 2
; CHECK-NEXT:    [[TMP99:%.*]] = insertelement <4 x i8> [[TMP98]], i8 [[LOAD_3_19103]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP99]], ptr [[PTR2_0_19]], align 4
; CHECK-NEXT:    [[PTR_0_20:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 80
; CHECK-NEXT:    [[TMP100:%.*]] = load <4 x i8>, ptr [[PTR_0_20]], align 4
; CHECK-NEXT:    [[LOAD_0_20104:%.*]] = extractelement <4 x i8> [[TMP100]], i32 0
; CHECK-NEXT:    [[LOAD_1_20105:%.*]] = extractelement <4 x i8> [[TMP100]], i32 1
; CHECK-NEXT:    [[LOAD_2_20106:%.*]] = extractelement <4 x i8> [[TMP100]], i32 2
; CHECK-NEXT:    [[LOAD_3_20107:%.*]] = extractelement <4 x i8> [[TMP100]], i32 3
; CHECK-NEXT:    [[PTR2_0_20:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 80
; CHECK-NEXT:    [[TMP101:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_20104]], i32 0
; CHECK-NEXT:    [[TMP102:%.*]] = insertelement <4 x i8> [[TMP101]], i8 [[LOAD_1_20105]], i32 1
; CHECK-NEXT:    [[TMP103:%.*]] = insertelement <4 x i8> [[TMP102]], i8 [[LOAD_2_20106]], i32 2
; CHECK-NEXT:    [[TMP104:%.*]] = insertelement <4 x i8> [[TMP103]], i8 [[LOAD_3_20107]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP104]], ptr [[PTR2_0_20]], align 4
; CHECK-NEXT:    [[PTR_0_21:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 84
; CHECK-NEXT:    [[TMP105:%.*]] = load <4 x i8>, ptr [[PTR_0_21]], align 4
; CHECK-NEXT:    [[LOAD_0_21108:%.*]] = extractelement <4 x i8> [[TMP105]], i32 0
; CHECK-NEXT:    [[LOAD_1_21109:%.*]] = extractelement <4 x i8> [[TMP105]], i32 1
; CHECK-NEXT:    [[LOAD_2_21110:%.*]] = extractelement <4 x i8> [[TMP105]], i32 2
; CHECK-NEXT:    [[LOAD_3_21111:%.*]] = extractelement <4 x i8> [[TMP105]], i32 3
; CHECK-NEXT:    [[PTR2_0_21:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 84
; CHECK-NEXT:    [[TMP106:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_21108]], i32 0
; CHECK-NEXT:    [[TMP107:%.*]] = insertelement <4 x i8> [[TMP106]], i8 [[LOAD_1_21109]], i32 1
; CHECK-NEXT:    [[TMP108:%.*]] = insertelement <4 x i8> [[TMP107]], i8 [[LOAD_2_21110]], i32 2
; CHECK-NEXT:    [[TMP109:%.*]] = insertelement <4 x i8> [[TMP108]], i8 [[LOAD_3_21111]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP109]], ptr [[PTR2_0_21]], align 4
; CHECK-NEXT:    [[PTR_0_22:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 88
; CHECK-NEXT:    [[TMP110:%.*]] = load <4 x i8>, ptr [[PTR_0_22]], align 4
; CHECK-NEXT:    [[LOAD_0_22112:%.*]] = extractelement <4 x i8> [[TMP110]], i32 0
; CHECK-NEXT:    [[LOAD_1_22113:%.*]] = extractelement <4 x i8> [[TMP110]], i32 1
; CHECK-NEXT:    [[LOAD_2_22114:%.*]] = extractelement <4 x i8> [[TMP110]], i32 2
; CHECK-NEXT:    [[LOAD_3_22115:%.*]] = extractelement <4 x i8> [[TMP110]], i32 3
; CHECK-NEXT:    [[PTR2_0_22:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 88
; CHECK-NEXT:    [[TMP111:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_22112]], i32 0
; CHECK-NEXT:    [[TMP112:%.*]] = insertelement <4 x i8> [[TMP111]], i8 [[LOAD_1_22113]], i32 1
; CHECK-NEXT:    [[TMP113:%.*]] = insertelement <4 x i8> [[TMP112]], i8 [[LOAD_2_22114]], i32 2
; CHECK-NEXT:    [[TMP114:%.*]] = insertelement <4 x i8> [[TMP113]], i8 [[LOAD_3_22115]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP114]], ptr [[PTR2_0_22]], align 4
; CHECK-NEXT:    [[PTR_0_23:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 92
; CHECK-NEXT:    [[TMP115:%.*]] = load <4 x i8>, ptr [[PTR_0_23]], align 4
; CHECK-NEXT:    [[LOAD_0_23116:%.*]] = extractelement <4 x i8> [[TMP115]], i32 0
; CHECK-NEXT:    [[LOAD_1_23117:%.*]] = extractelement <4 x i8> [[TMP115]], i32 1
; CHECK-NEXT:    [[LOAD_2_23118:%.*]] = extractelement <4 x i8> [[TMP115]], i32 2
; CHECK-NEXT:    [[LOAD_3_23119:%.*]] = extractelement <4 x i8> [[TMP115]], i32 3
; CHECK-NEXT:    [[PTR2_0_23:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 92
; CHECK-NEXT:    [[TMP116:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_23116]], i32 0
; CHECK-NEXT:    [[TMP117:%.*]] = insertelement <4 x i8> [[TMP116]], i8 [[LOAD_1_23117]], i32 1
; CHECK-NEXT:    [[TMP118:%.*]] = insertelement <4 x i8> [[TMP117]], i8 [[LOAD_2_23118]], i32 2
; CHECK-NEXT:    [[TMP119:%.*]] = insertelement <4 x i8> [[TMP118]], i8 [[LOAD_3_23119]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP119]], ptr [[PTR2_0_23]], align 4
; CHECK-NEXT:    [[PTR_0_24:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 96
; CHECK-NEXT:    [[TMP120:%.*]] = load <4 x i8>, ptr [[PTR_0_24]], align 4
; CHECK-NEXT:    [[LOAD_0_24120:%.*]] = extractelement <4 x i8> [[TMP120]], i32 0
; CHECK-NEXT:    [[LOAD_1_24121:%.*]] = extractelement <4 x i8> [[TMP120]], i32 1
; CHECK-NEXT:    [[LOAD_2_24122:%.*]] = extractelement <4 x i8> [[TMP120]], i32 2
; CHECK-NEXT:    [[LOAD_3_24123:%.*]] = extractelement <4 x i8> [[TMP120]], i32 3
; CHECK-NEXT:    [[PTR2_0_24:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 96
; CHECK-NEXT:    [[TMP121:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_24120]], i32 0
; CHECK-NEXT:    [[TMP122:%.*]] = insertelement <4 x i8> [[TMP121]], i8 [[LOAD_1_24121]], i32 1
; CHECK-NEXT:    [[TMP123:%.*]] = insertelement <4 x i8> [[TMP122]], i8 [[LOAD_2_24122]], i32 2
; CHECK-NEXT:    [[TMP124:%.*]] = insertelement <4 x i8> [[TMP123]], i8 [[LOAD_3_24123]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP124]], ptr [[PTR2_0_24]], align 4
; CHECK-NEXT:    [[PTR_0_25:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 100
; CHECK-NEXT:    [[TMP125:%.*]] = load <4 x i8>, ptr [[PTR_0_25]], align 4
; CHECK-NEXT:    [[LOAD_0_25124:%.*]] = extractelement <4 x i8> [[TMP125]], i32 0
; CHECK-NEXT:    [[LOAD_1_25125:%.*]] = extractelement <4 x i8> [[TMP125]], i32 1
; CHECK-NEXT:    [[LOAD_2_25126:%.*]] = extractelement <4 x i8> [[TMP125]], i32 2
; CHECK-NEXT:    [[LOAD_3_25127:%.*]] = extractelement <4 x i8> [[TMP125]], i32 3
; CHECK-NEXT:    [[PTR2_0_25:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 100
; CHECK-NEXT:    [[TMP126:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_25124]], i32 0
; CHECK-NEXT:    [[TMP127:%.*]] = insertelement <4 x i8> [[TMP126]], i8 [[LOAD_1_25125]], i32 1
; CHECK-NEXT:    [[TMP128:%.*]] = insertelement <4 x i8> [[TMP127]], i8 [[LOAD_2_25126]], i32 2
; CHECK-NEXT:    [[TMP129:%.*]] = insertelement <4 x i8> [[TMP128]], i8 [[LOAD_3_25127]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP129]], ptr [[PTR2_0_25]], align 4
; CHECK-NEXT:    [[PTR_0_26:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 104
; CHECK-NEXT:    [[TMP130:%.*]] = load <4 x i8>, ptr [[PTR_0_26]], align 4
; CHECK-NEXT:    [[LOAD_0_26128:%.*]] = extractelement <4 x i8> [[TMP130]], i32 0
; CHECK-NEXT:    [[LOAD_1_26129:%.*]] = extractelement <4 x i8> [[TMP130]], i32 1
; CHECK-NEXT:    [[LOAD_2_26130:%.*]] = extractelement <4 x i8> [[TMP130]], i32 2
; CHECK-NEXT:    [[LOAD_3_26131:%.*]] = extractelement <4 x i8> [[TMP130]], i32 3
; CHECK-NEXT:    [[PTR2_0_26:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 104
; CHECK-NEXT:    [[TMP131:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_26128]], i32 0
; CHECK-NEXT:    [[TMP132:%.*]] = insertelement <4 x i8> [[TMP131]], i8 [[LOAD_1_26129]], i32 1
; CHECK-NEXT:    [[TMP133:%.*]] = insertelement <4 x i8> [[TMP132]], i8 [[LOAD_2_26130]], i32 2
; CHECK-NEXT:    [[TMP134:%.*]] = insertelement <4 x i8> [[TMP133]], i8 [[LOAD_3_26131]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP134]], ptr [[PTR2_0_26]], align 4
; CHECK-NEXT:    [[PTR_0_27:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 108
; CHECK-NEXT:    [[TMP135:%.*]] = load <4 x i8>, ptr [[PTR_0_27]], align 4
; CHECK-NEXT:    [[LOAD_0_27132:%.*]] = extractelement <4 x i8> [[TMP135]], i32 0
; CHECK-NEXT:    [[LOAD_1_27133:%.*]] = extractelement <4 x i8> [[TMP135]], i32 1
; CHECK-NEXT:    [[LOAD_2_27134:%.*]] = extractelement <4 x i8> [[TMP135]], i32 2
; CHECK-NEXT:    [[LOAD_3_27135:%.*]] = extractelement <4 x i8> [[TMP135]], i32 3
; CHECK-NEXT:    [[PTR2_0_27:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 108
; CHECK-NEXT:    [[TMP136:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_27132]], i32 0
; CHECK-NEXT:    [[TMP137:%.*]] = insertelement <4 x i8> [[TMP136]], i8 [[LOAD_1_27133]], i32 1
; CHECK-NEXT:    [[TMP138:%.*]] = insertelement <4 x i8> [[TMP137]], i8 [[LOAD_2_27134]], i32 2
; CHECK-NEXT:    [[TMP139:%.*]] = insertelement <4 x i8> [[TMP138]], i8 [[LOAD_3_27135]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP139]], ptr [[PTR2_0_27]], align 4
; CHECK-NEXT:    [[PTR_0_28:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 112
; CHECK-NEXT:    [[TMP140:%.*]] = load <4 x i8>, ptr [[PTR_0_28]], align 4
; CHECK-NEXT:    [[LOAD_0_28136:%.*]] = extractelement <4 x i8> [[TMP140]], i32 0
; CHECK-NEXT:    [[LOAD_1_28137:%.*]] = extractelement <4 x i8> [[TMP140]], i32 1
; CHECK-NEXT:    [[LOAD_2_28138:%.*]] = extractelement <4 x i8> [[TMP140]], i32 2
; CHECK-NEXT:    [[LOAD_3_28139:%.*]] = extractelement <4 x i8> [[TMP140]], i32 3
; CHECK-NEXT:    [[PTR2_0_28:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 112
; CHECK-NEXT:    [[TMP141:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_28136]], i32 0
; CHECK-NEXT:    [[TMP142:%.*]] = insertelement <4 x i8> [[TMP141]], i8 [[LOAD_1_28137]], i32 1
; CHECK-NEXT:    [[TMP143:%.*]] = insertelement <4 x i8> [[TMP142]], i8 [[LOAD_2_28138]], i32 2
; CHECK-NEXT:    [[TMP144:%.*]] = insertelement <4 x i8> [[TMP143]], i8 [[LOAD_3_28139]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP144]], ptr [[PTR2_0_28]], align 4
; CHECK-NEXT:    [[PTR_0_29:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 116
; CHECK-NEXT:    [[TMP145:%.*]] = load <4 x i8>, ptr [[PTR_0_29]], align 4
; CHECK-NEXT:    [[LOAD_0_29140:%.*]] = extractelement <4 x i8> [[TMP145]], i32 0
; CHECK-NEXT:    [[LOAD_1_29141:%.*]] = extractelement <4 x i8> [[TMP145]], i32 1
; CHECK-NEXT:    [[LOAD_2_29142:%.*]] = extractelement <4 x i8> [[TMP145]], i32 2
; CHECK-NEXT:    [[LOAD_3_29143:%.*]] = extractelement <4 x i8> [[TMP145]], i32 3
; CHECK-NEXT:    [[PTR2_0_29:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 116
; CHECK-NEXT:    [[TMP146:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_29140]], i32 0
; CHECK-NEXT:    [[TMP147:%.*]] = insertelement <4 x i8> [[TMP146]], i8 [[LOAD_1_29141]], i32 1
; CHECK-NEXT:    [[TMP148:%.*]] = insertelement <4 x i8> [[TMP147]], i8 [[LOAD_2_29142]], i32 2
; CHECK-NEXT:    [[TMP149:%.*]] = insertelement <4 x i8> [[TMP148]], i8 [[LOAD_3_29143]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP149]], ptr [[PTR2_0_29]], align 4
; CHECK-NEXT:    [[PTR_0_30:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 120
; CHECK-NEXT:    [[TMP150:%.*]] = load <4 x i8>, ptr [[PTR_0_30]], align 4
; CHECK-NEXT:    [[LOAD_0_30144:%.*]] = extractelement <4 x i8> [[TMP150]], i32 0
; CHECK-NEXT:    [[LOAD_1_30145:%.*]] = extractelement <4 x i8> [[TMP150]], i32 1
; CHECK-NEXT:    [[LOAD_2_30146:%.*]] = extractelement <4 x i8> [[TMP150]], i32 2
; CHECK-NEXT:    [[LOAD_3_30147:%.*]] = extractelement <4 x i8> [[TMP150]], i32 3
; CHECK-NEXT:    [[PTR2_0_30:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 120
; CHECK-NEXT:    [[TMP151:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_30144]], i32 0
; CHECK-NEXT:    [[TMP152:%.*]] = insertelement <4 x i8> [[TMP151]], i8 [[LOAD_1_30145]], i32 1
; CHECK-NEXT:    [[TMP153:%.*]] = insertelement <4 x i8> [[TMP152]], i8 [[LOAD_2_30146]], i32 2
; CHECK-NEXT:    [[TMP154:%.*]] = insertelement <4 x i8> [[TMP153]], i8 [[LOAD_3_30147]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP154]], ptr [[PTR2_0_30]], align 4
; CHECK-NEXT:    [[PTR_0_31:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 124
; CHECK-NEXT:    [[TMP155:%.*]] = load <4 x i8>, ptr [[PTR_0_31]], align 4
; CHECK-NEXT:    [[LOAD_0_31148:%.*]] = extractelement <4 x i8> [[TMP155]], i32 0
; CHECK-NEXT:    [[LOAD_1_31149:%.*]] = extractelement <4 x i8> [[TMP155]], i32 1
; CHECK-NEXT:    [[LOAD_2_31150:%.*]] = extractelement <4 x i8> [[TMP155]], i32 2
; CHECK-NEXT:    [[LOAD_3_31151:%.*]] = extractelement <4 x i8> [[TMP155]], i32 3
; CHECK-NEXT:    [[PTR2_0_31:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 124
; CHECK-NEXT:    [[TMP156:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_31148]], i32 0
; CHECK-NEXT:    [[TMP157:%.*]] = insertelement <4 x i8> [[TMP156]], i8 [[LOAD_1_31149]], i32 1
; CHECK-NEXT:    [[TMP158:%.*]] = insertelement <4 x i8> [[TMP157]], i8 [[LOAD_2_31150]], i32 2
; CHECK-NEXT:    [[TMP159:%.*]] = insertelement <4 x i8> [[TMP158]], i8 [[LOAD_3_31151]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP159]], ptr [[PTR2_0_31]], align 4
; CHECK-NEXT:    [[PTR_0_32:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 128
; CHECK-NEXT:    [[TMP160:%.*]] = load <4 x i8>, ptr [[PTR_0_32]], align 4
; CHECK-NEXT:    [[LOAD_0_32152:%.*]] = extractelement <4 x i8> [[TMP160]], i32 0
; CHECK-NEXT:    [[LOAD_1_32153:%.*]] = extractelement <4 x i8> [[TMP160]], i32 1
; CHECK-NEXT:    [[LOAD_2_32154:%.*]] = extractelement <4 x i8> [[TMP160]], i32 2
; CHECK-NEXT:    [[LOAD_3_32155:%.*]] = extractelement <4 x i8> [[TMP160]], i32 3
; CHECK-NEXT:    [[PTR2_0_32:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 128
; CHECK-NEXT:    [[TMP161:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_32152]], i32 0
; CHECK-NEXT:    [[TMP162:%.*]] = insertelement <4 x i8> [[TMP161]], i8 [[LOAD_1_32153]], i32 1
; CHECK-NEXT:    [[TMP163:%.*]] = insertelement <4 x i8> [[TMP162]], i8 [[LOAD_2_32154]], i32 2
; CHECK-NEXT:    [[TMP164:%.*]] = insertelement <4 x i8> [[TMP163]], i8 [[LOAD_3_32155]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP164]], ptr [[PTR2_0_32]], align 4
; CHECK-NEXT:    [[PTR_0_33:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 132
; CHECK-NEXT:    [[TMP165:%.*]] = load <4 x i8>, ptr [[PTR_0_33]], align 4
; CHECK-NEXT:    [[LOAD_0_33156:%.*]] = extractelement <4 x i8> [[TMP165]], i32 0
; CHECK-NEXT:    [[LOAD_1_33157:%.*]] = extractelement <4 x i8> [[TMP165]], i32 1
; CHECK-NEXT:    [[LOAD_2_33158:%.*]] = extractelement <4 x i8> [[TMP165]], i32 2
; CHECK-NEXT:    [[LOAD_3_33159:%.*]] = extractelement <4 x i8> [[TMP165]], i32 3
; CHECK-NEXT:    [[PTR2_0_33:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 132
; CHECK-NEXT:    [[TMP166:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_33156]], i32 0
; CHECK-NEXT:    [[TMP167:%.*]] = insertelement <4 x i8> [[TMP166]], i8 [[LOAD_1_33157]], i32 1
; CHECK-NEXT:    [[TMP168:%.*]] = insertelement <4 x i8> [[TMP167]], i8 [[LOAD_2_33158]], i32 2
; CHECK-NEXT:    [[TMP169:%.*]] = insertelement <4 x i8> [[TMP168]], i8 [[LOAD_3_33159]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP169]], ptr [[PTR2_0_33]], align 4
; CHECK-NEXT:    [[PTR_0_34:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 136
; CHECK-NEXT:    [[TMP170:%.*]] = load <4 x i8>, ptr [[PTR_0_34]], align 4
; CHECK-NEXT:    [[LOAD_0_34160:%.*]] = extractelement <4 x i8> [[TMP170]], i32 0
; CHECK-NEXT:    [[LOAD_1_34161:%.*]] = extractelement <4 x i8> [[TMP170]], i32 1
; CHECK-NEXT:    [[LOAD_2_34162:%.*]] = extractelement <4 x i8> [[TMP170]], i32 2
; CHECK-NEXT:    [[LOAD_3_34163:%.*]] = extractelement <4 x i8> [[TMP170]], i32 3
; CHECK-NEXT:    [[PTR2_0_34:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 136
; CHECK-NEXT:    [[TMP171:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_34160]], i32 0
; CHECK-NEXT:    [[TMP172:%.*]] = insertelement <4 x i8> [[TMP171]], i8 [[LOAD_1_34161]], i32 1
; CHECK-NEXT:    [[TMP173:%.*]] = insertelement <4 x i8> [[TMP172]], i8 [[LOAD_2_34162]], i32 2
; CHECK-NEXT:    [[TMP174:%.*]] = insertelement <4 x i8> [[TMP173]], i8 [[LOAD_3_34163]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP174]], ptr [[PTR2_0_34]], align 4
; CHECK-NEXT:    [[PTR_0_35:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 140
; CHECK-NEXT:    [[TMP175:%.*]] = load <4 x i8>, ptr [[PTR_0_35]], align 4
; CHECK-NEXT:    [[LOAD_0_35164:%.*]] = extractelement <4 x i8> [[TMP175]], i32 0
; CHECK-NEXT:    [[LOAD_1_35165:%.*]] = extractelement <4 x i8> [[TMP175]], i32 1
; CHECK-NEXT:    [[LOAD_2_35166:%.*]] = extractelement <4 x i8> [[TMP175]], i32 2
; CHECK-NEXT:    [[LOAD_3_35167:%.*]] = extractelement <4 x i8> [[TMP175]], i32 3
; CHECK-NEXT:    [[PTR2_0_35:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 140
; CHECK-NEXT:    [[TMP176:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_35164]], i32 0
; CHECK-NEXT:    [[TMP177:%.*]] = insertelement <4 x i8> [[TMP176]], i8 [[LOAD_1_35165]], i32 1
; CHECK-NEXT:    [[TMP178:%.*]] = insertelement <4 x i8> [[TMP177]], i8 [[LOAD_2_35166]], i32 2
; CHECK-NEXT:    [[TMP179:%.*]] = insertelement <4 x i8> [[TMP178]], i8 [[LOAD_3_35167]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP179]], ptr [[PTR2_0_35]], align 4
; CHECK-NEXT:    [[PTR_0_36:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 144
; CHECK-NEXT:    [[TMP180:%.*]] = load <4 x i8>, ptr [[PTR_0_36]], align 4
; CHECK-NEXT:    [[LOAD_0_36168:%.*]] = extractelement <4 x i8> [[TMP180]], i32 0
; CHECK-NEXT:    [[LOAD_1_36169:%.*]] = extractelement <4 x i8> [[TMP180]], i32 1
; CHECK-NEXT:    [[LOAD_2_36170:%.*]] = extractelement <4 x i8> [[TMP180]], i32 2
; CHECK-NEXT:    [[LOAD_3_36171:%.*]] = extractelement <4 x i8> [[TMP180]], i32 3
; CHECK-NEXT:    [[PTR2_0_36:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 144
; CHECK-NEXT:    [[TMP181:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_36168]], i32 0
; CHECK-NEXT:    [[TMP182:%.*]] = insertelement <4 x i8> [[TMP181]], i8 [[LOAD_1_36169]], i32 1
; CHECK-NEXT:    [[TMP183:%.*]] = insertelement <4 x i8> [[TMP182]], i8 [[LOAD_2_36170]], i32 2
; CHECK-NEXT:    [[TMP184:%.*]] = insertelement <4 x i8> [[TMP183]], i8 [[LOAD_3_36171]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP184]], ptr [[PTR2_0_36]], align 4
; CHECK-NEXT:    [[PTR_0_37:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 148
; CHECK-NEXT:    [[TMP185:%.*]] = load <4 x i8>, ptr [[PTR_0_37]], align 4
; CHECK-NEXT:    [[LOAD_0_37172:%.*]] = extractelement <4 x i8> [[TMP185]], i32 0
; CHECK-NEXT:    [[LOAD_1_37173:%.*]] = extractelement <4 x i8> [[TMP185]], i32 1
; CHECK-NEXT:    [[LOAD_2_37174:%.*]] = extractelement <4 x i8> [[TMP185]], i32 2
; CHECK-NEXT:    [[LOAD_3_37175:%.*]] = extractelement <4 x i8> [[TMP185]], i32 3
; CHECK-NEXT:    [[PTR2_0_37:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 148
; CHECK-NEXT:    [[TMP186:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_37172]], i32 0
; CHECK-NEXT:    [[TMP187:%.*]] = insertelement <4 x i8> [[TMP186]], i8 [[LOAD_1_37173]], i32 1
; CHECK-NEXT:    [[TMP188:%.*]] = insertelement <4 x i8> [[TMP187]], i8 [[LOAD_2_37174]], i32 2
; CHECK-NEXT:    [[TMP189:%.*]] = insertelement <4 x i8> [[TMP188]], i8 [[LOAD_3_37175]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP189]], ptr [[PTR2_0_37]], align 4
; CHECK-NEXT:    [[PTR_0_38:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 152
; CHECK-NEXT:    [[TMP190:%.*]] = load <4 x i8>, ptr [[PTR_0_38]], align 4
; CHECK-NEXT:    [[LOAD_0_38176:%.*]] = extractelement <4 x i8> [[TMP190]], i32 0
; CHECK-NEXT:    [[LOAD_1_38177:%.*]] = extractelement <4 x i8> [[TMP190]], i32 1
; CHECK-NEXT:    [[LOAD_2_38178:%.*]] = extractelement <4 x i8> [[TMP190]], i32 2
; CHECK-NEXT:    [[LOAD_3_38179:%.*]] = extractelement <4 x i8> [[TMP190]], i32 3
; CHECK-NEXT:    [[PTR2_0_38:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 152
; CHECK-NEXT:    [[TMP191:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_38176]], i32 0
; CHECK-NEXT:    [[TMP192:%.*]] = insertelement <4 x i8> [[TMP191]], i8 [[LOAD_1_38177]], i32 1
; CHECK-NEXT:    [[TMP193:%.*]] = insertelement <4 x i8> [[TMP192]], i8 [[LOAD_2_38178]], i32 2
; CHECK-NEXT:    [[TMP194:%.*]] = insertelement <4 x i8> [[TMP193]], i8 [[LOAD_3_38179]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP194]], ptr [[PTR2_0_38]], align 4
; CHECK-NEXT:    [[PTR_0_39:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 156
; CHECK-NEXT:    [[TMP195:%.*]] = load <4 x i8>, ptr [[PTR_0_39]], align 4
; CHECK-NEXT:    [[LOAD_0_39180:%.*]] = extractelement <4 x i8> [[TMP195]], i32 0
; CHECK-NEXT:    [[LOAD_1_39181:%.*]] = extractelement <4 x i8> [[TMP195]], i32 1
; CHECK-NEXT:    [[LOAD_2_39182:%.*]] = extractelement <4 x i8> [[TMP195]], i32 2
; CHECK-NEXT:    [[LOAD_3_39183:%.*]] = extractelement <4 x i8> [[TMP195]], i32 3
; CHECK-NEXT:    [[PTR2_0_39:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 156
; CHECK-NEXT:    [[TMP196:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_39180]], i32 0
; CHECK-NEXT:    [[TMP197:%.*]] = insertelement <4 x i8> [[TMP196]], i8 [[LOAD_1_39181]], i32 1
; CHECK-NEXT:    [[TMP198:%.*]] = insertelement <4 x i8> [[TMP197]], i8 [[LOAD_2_39182]], i32 2
; CHECK-NEXT:    [[TMP199:%.*]] = insertelement <4 x i8> [[TMP198]], i8 [[LOAD_3_39183]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP199]], ptr [[PTR2_0_39]], align 4
; CHECK-NEXT:    [[PTR_0_40:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 160
; CHECK-NEXT:    [[TMP200:%.*]] = load <4 x i8>, ptr [[PTR_0_40]], align 4
; CHECK-NEXT:    [[LOAD_0_40184:%.*]] = extractelement <4 x i8> [[TMP200]], i32 0
; CHECK-NEXT:    [[LOAD_1_40185:%.*]] = extractelement <4 x i8> [[TMP200]], i32 1
; CHECK-NEXT:    [[LOAD_2_40186:%.*]] = extractelement <4 x i8> [[TMP200]], i32 2
; CHECK-NEXT:    [[LOAD_3_40187:%.*]] = extractelement <4 x i8> [[TMP200]], i32 3
; CHECK-NEXT:    [[PTR2_0_40:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 160
; CHECK-NEXT:    [[TMP201:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_40184]], i32 0
; CHECK-NEXT:    [[TMP202:%.*]] = insertelement <4 x i8> [[TMP201]], i8 [[LOAD_1_40185]], i32 1
; CHECK-NEXT:    [[TMP203:%.*]] = insertelement <4 x i8> [[TMP202]], i8 [[LOAD_2_40186]], i32 2
; CHECK-NEXT:    [[TMP204:%.*]] = insertelement <4 x i8> [[TMP203]], i8 [[LOAD_3_40187]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP204]], ptr [[PTR2_0_40]], align 4
; CHECK-NEXT:    [[PTR_0_41:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 164
; CHECK-NEXT:    [[TMP205:%.*]] = load <4 x i8>, ptr [[PTR_0_41]], align 4
; CHECK-NEXT:    [[LOAD_0_41188:%.*]] = extractelement <4 x i8> [[TMP205]], i32 0
; CHECK-NEXT:    [[LOAD_1_41189:%.*]] = extractelement <4 x i8> [[TMP205]], i32 1
; CHECK-NEXT:    [[LOAD_2_41190:%.*]] = extractelement <4 x i8> [[TMP205]], i32 2
; CHECK-NEXT:    [[LOAD_3_41191:%.*]] = extractelement <4 x i8> [[TMP205]], i32 3
; CHECK-NEXT:    [[PTR2_0_41:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 164
; CHECK-NEXT:    [[TMP206:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_41188]], i32 0
; CHECK-NEXT:    [[TMP207:%.*]] = insertelement <4 x i8> [[TMP206]], i8 [[LOAD_1_41189]], i32 1
; CHECK-NEXT:    [[TMP208:%.*]] = insertelement <4 x i8> [[TMP207]], i8 [[LOAD_2_41190]], i32 2
; CHECK-NEXT:    [[TMP209:%.*]] = insertelement <4 x i8> [[TMP208]], i8 [[LOAD_3_41191]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP209]], ptr [[PTR2_0_41]], align 4
; CHECK-NEXT:    [[PTR_0_42:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 168
; CHECK-NEXT:    [[TMP210:%.*]] = load <4 x i8>, ptr [[PTR_0_42]], align 4
; CHECK-NEXT:    [[LOAD_0_42192:%.*]] = extractelement <4 x i8> [[TMP210]], i32 0
; CHECK-NEXT:    [[LOAD_1_42193:%.*]] = extractelement <4 x i8> [[TMP210]], i32 1
; CHECK-NEXT:    [[LOAD_2_42194:%.*]] = extractelement <4 x i8> [[TMP210]], i32 2
; CHECK-NEXT:    [[LOAD_3_42195:%.*]] = extractelement <4 x i8> [[TMP210]], i32 3
; CHECK-NEXT:    [[PTR2_0_42:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 168
; CHECK-NEXT:    [[TMP211:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_42192]], i32 0
; CHECK-NEXT:    [[TMP212:%.*]] = insertelement <4 x i8> [[TMP211]], i8 [[LOAD_1_42193]], i32 1
; CHECK-NEXT:    [[TMP213:%.*]] = insertelement <4 x i8> [[TMP212]], i8 [[LOAD_2_42194]], i32 2
; CHECK-NEXT:    [[TMP214:%.*]] = insertelement <4 x i8> [[TMP213]], i8 [[LOAD_3_42195]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP214]], ptr [[PTR2_0_42]], align 4
; CHECK-NEXT:    [[PTR_0_43:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 172
; CHECK-NEXT:    [[TMP215:%.*]] = load <4 x i8>, ptr [[PTR_0_43]], align 4
; CHECK-NEXT:    [[LOAD_0_43196:%.*]] = extractelement <4 x i8> [[TMP215]], i32 0
; CHECK-NEXT:    [[LOAD_1_43197:%.*]] = extractelement <4 x i8> [[TMP215]], i32 1
; CHECK-NEXT:    [[LOAD_2_43198:%.*]] = extractelement <4 x i8> [[TMP215]], i32 2
; CHECK-NEXT:    [[LOAD_3_43199:%.*]] = extractelement <4 x i8> [[TMP215]], i32 3
; CHECK-NEXT:    [[PTR2_0_43:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 172
; CHECK-NEXT:    [[TMP216:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_43196]], i32 0
; CHECK-NEXT:    [[TMP217:%.*]] = insertelement <4 x i8> [[TMP216]], i8 [[LOAD_1_43197]], i32 1
; CHECK-NEXT:    [[TMP218:%.*]] = insertelement <4 x i8> [[TMP217]], i8 [[LOAD_2_43198]], i32 2
; CHECK-NEXT:    [[TMP219:%.*]] = insertelement <4 x i8> [[TMP218]], i8 [[LOAD_3_43199]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP219]], ptr [[PTR2_0_43]], align 4
; CHECK-NEXT:    [[PTR_0_44:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 176
; CHECK-NEXT:    [[TMP220:%.*]] = load <4 x i8>, ptr [[PTR_0_44]], align 4
; CHECK-NEXT:    [[LOAD_0_44200:%.*]] = extractelement <4 x i8> [[TMP220]], i32 0
; CHECK-NEXT:    [[LOAD_1_44201:%.*]] = extractelement <4 x i8> [[TMP220]], i32 1
; CHECK-NEXT:    [[LOAD_2_44202:%.*]] = extractelement <4 x i8> [[TMP220]], i32 2
; CHECK-NEXT:    [[LOAD_3_44203:%.*]] = extractelement <4 x i8> [[TMP220]], i32 3
; CHECK-NEXT:    [[PTR2_0_44:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 176
; CHECK-NEXT:    [[TMP221:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_44200]], i32 0
; CHECK-NEXT:    [[TMP222:%.*]] = insertelement <4 x i8> [[TMP221]], i8 [[LOAD_1_44201]], i32 1
; CHECK-NEXT:    [[TMP223:%.*]] = insertelement <4 x i8> [[TMP222]], i8 [[LOAD_2_44202]], i32 2
; CHECK-NEXT:    [[TMP224:%.*]] = insertelement <4 x i8> [[TMP223]], i8 [[LOAD_3_44203]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP224]], ptr [[PTR2_0_44]], align 4
; CHECK-NEXT:    [[PTR_0_45:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 180
; CHECK-NEXT:    [[TMP225:%.*]] = load <4 x i8>, ptr [[PTR_0_45]], align 4
; CHECK-NEXT:    [[LOAD_0_45204:%.*]] = extractelement <4 x i8> [[TMP225]], i32 0
; CHECK-NEXT:    [[LOAD_1_45205:%.*]] = extractelement <4 x i8> [[TMP225]], i32 1
; CHECK-NEXT:    [[LOAD_2_45206:%.*]] = extractelement <4 x i8> [[TMP225]], i32 2
; CHECK-NEXT:    [[LOAD_3_45207:%.*]] = extractelement <4 x i8> [[TMP225]], i32 3
; CHECK-NEXT:    [[PTR2_0_45:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 180
; CHECK-NEXT:    [[TMP226:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_45204]], i32 0
; CHECK-NEXT:    [[TMP227:%.*]] = insertelement <4 x i8> [[TMP226]], i8 [[LOAD_1_45205]], i32 1
; CHECK-NEXT:    [[TMP228:%.*]] = insertelement <4 x i8> [[TMP227]], i8 [[LOAD_2_45206]], i32 2
; CHECK-NEXT:    [[TMP229:%.*]] = insertelement <4 x i8> [[TMP228]], i8 [[LOAD_3_45207]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP229]], ptr [[PTR2_0_45]], align 4
; CHECK-NEXT:    [[PTR_0_46:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 184
; CHECK-NEXT:    [[TMP230:%.*]] = load <4 x i8>, ptr [[PTR_0_46]], align 4
; CHECK-NEXT:    [[LOAD_0_46208:%.*]] = extractelement <4 x i8> [[TMP230]], i32 0
; CHECK-NEXT:    [[LOAD_1_46209:%.*]] = extractelement <4 x i8> [[TMP230]], i32 1
; CHECK-NEXT:    [[LOAD_2_46210:%.*]] = extractelement <4 x i8> [[TMP230]], i32 2
; CHECK-NEXT:    [[LOAD_3_46211:%.*]] = extractelement <4 x i8> [[TMP230]], i32 3
; CHECK-NEXT:    [[PTR2_0_46:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 184
; CHECK-NEXT:    [[TMP231:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_46208]], i32 0
; CHECK-NEXT:    [[TMP232:%.*]] = insertelement <4 x i8> [[TMP231]], i8 [[LOAD_1_46209]], i32 1
; CHECK-NEXT:    [[TMP233:%.*]] = insertelement <4 x i8> [[TMP232]], i8 [[LOAD_2_46210]], i32 2
; CHECK-NEXT:    [[TMP234:%.*]] = insertelement <4 x i8> [[TMP233]], i8 [[LOAD_3_46211]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP234]], ptr [[PTR2_0_46]], align 4
; CHECK-NEXT:    [[PTR_0_47:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 188
; CHECK-NEXT:    [[TMP235:%.*]] = load <4 x i8>, ptr [[PTR_0_47]], align 4
; CHECK-NEXT:    [[LOAD_0_47212:%.*]] = extractelement <4 x i8> [[TMP235]], i32 0
; CHECK-NEXT:    [[LOAD_1_47213:%.*]] = extractelement <4 x i8> [[TMP235]], i32 1
; CHECK-NEXT:    [[LOAD_2_47214:%.*]] = extractelement <4 x i8> [[TMP235]], i32 2
; CHECK-NEXT:    [[LOAD_3_47215:%.*]] = extractelement <4 x i8> [[TMP235]], i32 3
; CHECK-NEXT:    [[PTR2_0_47:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 188
; CHECK-NEXT:    [[TMP236:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_47212]], i32 0
; CHECK-NEXT:    [[TMP237:%.*]] = insertelement <4 x i8> [[TMP236]], i8 [[LOAD_1_47213]], i32 1
; CHECK-NEXT:    [[TMP238:%.*]] = insertelement <4 x i8> [[TMP237]], i8 [[LOAD_2_47214]], i32 2
; CHECK-NEXT:    [[TMP239:%.*]] = insertelement <4 x i8> [[TMP238]], i8 [[LOAD_3_47215]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP239]], ptr [[PTR2_0_47]], align 4
; CHECK-NEXT:    [[PTR_0_48:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 192
; CHECK-NEXT:    [[TMP240:%.*]] = load <4 x i8>, ptr [[PTR_0_48]], align 4
; CHECK-NEXT:    [[LOAD_0_48216:%.*]] = extractelement <4 x i8> [[TMP240]], i32 0
; CHECK-NEXT:    [[LOAD_1_48217:%.*]] = extractelement <4 x i8> [[TMP240]], i32 1
; CHECK-NEXT:    [[LOAD_2_48218:%.*]] = extractelement <4 x i8> [[TMP240]], i32 2
; CHECK-NEXT:    [[LOAD_3_48219:%.*]] = extractelement <4 x i8> [[TMP240]], i32 3
; CHECK-NEXT:    [[PTR2_0_48:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 192
; CHECK-NEXT:    [[TMP241:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_48216]], i32 0
; CHECK-NEXT:    [[TMP242:%.*]] = insertelement <4 x i8> [[TMP241]], i8 [[LOAD_1_48217]], i32 1
; CHECK-NEXT:    [[TMP243:%.*]] = insertelement <4 x i8> [[TMP242]], i8 [[LOAD_2_48218]], i32 2
; CHECK-NEXT:    [[TMP244:%.*]] = insertelement <4 x i8> [[TMP243]], i8 [[LOAD_3_48219]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP244]], ptr [[PTR2_0_48]], align 4
; CHECK-NEXT:    [[PTR_0_49:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 196
; CHECK-NEXT:    [[TMP245:%.*]] = load <4 x i8>, ptr [[PTR_0_49]], align 4
; CHECK-NEXT:    [[LOAD_0_49220:%.*]] = extractelement <4 x i8> [[TMP245]], i32 0
; CHECK-NEXT:    [[LOAD_1_49221:%.*]] = extractelement <4 x i8> [[TMP245]], i32 1
; CHECK-NEXT:    [[LOAD_2_49222:%.*]] = extractelement <4 x i8> [[TMP245]], i32 2
; CHECK-NEXT:    [[LOAD_3_49223:%.*]] = extractelement <4 x i8> [[TMP245]], i32 3
; CHECK-NEXT:    [[PTR2_0_49:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 196
; CHECK-NEXT:    [[TMP246:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_49220]], i32 0
; CHECK-NEXT:    [[TMP247:%.*]] = insertelement <4 x i8> [[TMP246]], i8 [[LOAD_1_49221]], i32 1
; CHECK-NEXT:    [[TMP248:%.*]] = insertelement <4 x i8> [[TMP247]], i8 [[LOAD_2_49222]], i32 2
; CHECK-NEXT:    [[TMP249:%.*]] = insertelement <4 x i8> [[TMP248]], i8 [[LOAD_3_49223]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP249]], ptr [[PTR2_0_49]], align 4
; CHECK-NEXT:    [[PTR_0_50:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 200
; CHECK-NEXT:    [[TMP250:%.*]] = load <4 x i8>, ptr [[PTR_0_50]], align 4
; CHECK-NEXT:    [[LOAD_0_50224:%.*]] = extractelement <4 x i8> [[TMP250]], i32 0
; CHECK-NEXT:    [[LOAD_1_50225:%.*]] = extractelement <4 x i8> [[TMP250]], i32 1
; CHECK-NEXT:    [[LOAD_2_50226:%.*]] = extractelement <4 x i8> [[TMP250]], i32 2
; CHECK-NEXT:    [[LOAD_3_50227:%.*]] = extractelement <4 x i8> [[TMP250]], i32 3
; CHECK-NEXT:    [[PTR2_0_50:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 200
; CHECK-NEXT:    [[TMP251:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_50224]], i32 0
; CHECK-NEXT:    [[TMP252:%.*]] = insertelement <4 x i8> [[TMP251]], i8 [[LOAD_1_50225]], i32 1
; CHECK-NEXT:    [[TMP253:%.*]] = insertelement <4 x i8> [[TMP252]], i8 [[LOAD_2_50226]], i32 2
; CHECK-NEXT:    [[TMP254:%.*]] = insertelement <4 x i8> [[TMP253]], i8 [[LOAD_3_50227]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP254]], ptr [[PTR2_0_50]], align 4
; CHECK-NEXT:    [[PTR_0_51:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 204
; CHECK-NEXT:    [[TMP255:%.*]] = load <4 x i8>, ptr [[PTR_0_51]], align 4
; CHECK-NEXT:    [[LOAD_0_51228:%.*]] = extractelement <4 x i8> [[TMP255]], i32 0
; CHECK-NEXT:    [[LOAD_1_51229:%.*]] = extractelement <4 x i8> [[TMP255]], i32 1
; CHECK-NEXT:    [[LOAD_2_51230:%.*]] = extractelement <4 x i8> [[TMP255]], i32 2
; CHECK-NEXT:    [[LOAD_3_51231:%.*]] = extractelement <4 x i8> [[TMP255]], i32 3
; CHECK-NEXT:    [[PTR2_0_51:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 204
; CHECK-NEXT:    [[TMP256:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_51228]], i32 0
; CHECK-NEXT:    [[TMP257:%.*]] = insertelement <4 x i8> [[TMP256]], i8 [[LOAD_1_51229]], i32 1
; CHECK-NEXT:    [[TMP258:%.*]] = insertelement <4 x i8> [[TMP257]], i8 [[LOAD_2_51230]], i32 2
; CHECK-NEXT:    [[TMP259:%.*]] = insertelement <4 x i8> [[TMP258]], i8 [[LOAD_3_51231]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP259]], ptr [[PTR2_0_51]], align 4
; CHECK-NEXT:    [[PTR_0_52:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 208
; CHECK-NEXT:    [[TMP260:%.*]] = load <4 x i8>, ptr [[PTR_0_52]], align 4
; CHECK-NEXT:    [[LOAD_0_52232:%.*]] = extractelement <4 x i8> [[TMP260]], i32 0
; CHECK-NEXT:    [[LOAD_1_52233:%.*]] = extractelement <4 x i8> [[TMP260]], i32 1
; CHECK-NEXT:    [[LOAD_2_52234:%.*]] = extractelement <4 x i8> [[TMP260]], i32 2
; CHECK-NEXT:    [[LOAD_3_52235:%.*]] = extractelement <4 x i8> [[TMP260]], i32 3
; CHECK-NEXT:    [[PTR2_0_52:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 208
; CHECK-NEXT:    [[TMP261:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_52232]], i32 0
; CHECK-NEXT:    [[TMP262:%.*]] = insertelement <4 x i8> [[TMP261]], i8 [[LOAD_1_52233]], i32 1
; CHECK-NEXT:    [[TMP263:%.*]] = insertelement <4 x i8> [[TMP262]], i8 [[LOAD_2_52234]], i32 2
; CHECK-NEXT:    [[TMP264:%.*]] = insertelement <4 x i8> [[TMP263]], i8 [[LOAD_3_52235]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP264]], ptr [[PTR2_0_52]], align 4
; CHECK-NEXT:    [[PTR_0_53:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 212
; CHECK-NEXT:    [[TMP265:%.*]] = load <4 x i8>, ptr [[PTR_0_53]], align 4
; CHECK-NEXT:    [[LOAD_0_53236:%.*]] = extractelement <4 x i8> [[TMP265]], i32 0
; CHECK-NEXT:    [[LOAD_1_53237:%.*]] = extractelement <4 x i8> [[TMP265]], i32 1
; CHECK-NEXT:    [[LOAD_2_53238:%.*]] = extractelement <4 x i8> [[TMP265]], i32 2
; CHECK-NEXT:    [[LOAD_3_53239:%.*]] = extractelement <4 x i8> [[TMP265]], i32 3
; CHECK-NEXT:    [[PTR2_0_53:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 212
; CHECK-NEXT:    [[TMP266:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_53236]], i32 0
; CHECK-NEXT:    [[TMP267:%.*]] = insertelement <4 x i8> [[TMP266]], i8 [[LOAD_1_53237]], i32 1
; CHECK-NEXT:    [[TMP268:%.*]] = insertelement <4 x i8> [[TMP267]], i8 [[LOAD_2_53238]], i32 2
; CHECK-NEXT:    [[TMP269:%.*]] = insertelement <4 x i8> [[TMP268]], i8 [[LOAD_3_53239]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP269]], ptr [[PTR2_0_53]], align 4
; CHECK-NEXT:    [[PTR_0_54:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 216
; CHECK-NEXT:    [[TMP270:%.*]] = load <4 x i8>, ptr [[PTR_0_54]], align 4
; CHECK-NEXT:    [[LOAD_0_54240:%.*]] = extractelement <4 x i8> [[TMP270]], i32 0
; CHECK-NEXT:    [[LOAD_1_54241:%.*]] = extractelement <4 x i8> [[TMP270]], i32 1
; CHECK-NEXT:    [[LOAD_2_54242:%.*]] = extractelement <4 x i8> [[TMP270]], i32 2
; CHECK-NEXT:    [[LOAD_3_54243:%.*]] = extractelement <4 x i8> [[TMP270]], i32 3
; CHECK-NEXT:    [[PTR2_0_54:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 216
; CHECK-NEXT:    [[TMP271:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_54240]], i32 0
; CHECK-NEXT:    [[TMP272:%.*]] = insertelement <4 x i8> [[TMP271]], i8 [[LOAD_1_54241]], i32 1
; CHECK-NEXT:    [[TMP273:%.*]] = insertelement <4 x i8> [[TMP272]], i8 [[LOAD_2_54242]], i32 2
; CHECK-NEXT:    [[TMP274:%.*]] = insertelement <4 x i8> [[TMP273]], i8 [[LOAD_3_54243]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP274]], ptr [[PTR2_0_54]], align 4
; CHECK-NEXT:    [[PTR_0_55:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 220
; CHECK-NEXT:    [[TMP275:%.*]] = load <4 x i8>, ptr [[PTR_0_55]], align 4
; CHECK-NEXT:    [[LOAD_0_55244:%.*]] = extractelement <4 x i8> [[TMP275]], i32 0
; CHECK-NEXT:    [[LOAD_1_55245:%.*]] = extractelement <4 x i8> [[TMP275]], i32 1
; CHECK-NEXT:    [[LOAD_2_55246:%.*]] = extractelement <4 x i8> [[TMP275]], i32 2
; CHECK-NEXT:    [[LOAD_3_55247:%.*]] = extractelement <4 x i8> [[TMP275]], i32 3
; CHECK-NEXT:    [[PTR2_0_55:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 220
; CHECK-NEXT:    [[TMP276:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_55244]], i32 0
; CHECK-NEXT:    [[TMP277:%.*]] = insertelement <4 x i8> [[TMP276]], i8 [[LOAD_1_55245]], i32 1
; CHECK-NEXT:    [[TMP278:%.*]] = insertelement <4 x i8> [[TMP277]], i8 [[LOAD_2_55246]], i32 2
; CHECK-NEXT:    [[TMP279:%.*]] = insertelement <4 x i8> [[TMP278]], i8 [[LOAD_3_55247]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP279]], ptr [[PTR2_0_55]], align 4
; CHECK-NEXT:    [[PTR_0_56:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 224
; CHECK-NEXT:    [[TMP280:%.*]] = load <4 x i8>, ptr [[PTR_0_56]], align 4
; CHECK-NEXT:    [[LOAD_0_56248:%.*]] = extractelement <4 x i8> [[TMP280]], i32 0
; CHECK-NEXT:    [[LOAD_1_56249:%.*]] = extractelement <4 x i8> [[TMP280]], i32 1
; CHECK-NEXT:    [[LOAD_2_56250:%.*]] = extractelement <4 x i8> [[TMP280]], i32 2
; CHECK-NEXT:    [[LOAD_3_56251:%.*]] = extractelement <4 x i8> [[TMP280]], i32 3
; CHECK-NEXT:    [[PTR2_0_56:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 224
; CHECK-NEXT:    [[TMP281:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_56248]], i32 0
; CHECK-NEXT:    [[TMP282:%.*]] = insertelement <4 x i8> [[TMP281]], i8 [[LOAD_1_56249]], i32 1
; CHECK-NEXT:    [[TMP283:%.*]] = insertelement <4 x i8> [[TMP282]], i8 [[LOAD_2_56250]], i32 2
; CHECK-NEXT:    [[TMP284:%.*]] = insertelement <4 x i8> [[TMP283]], i8 [[LOAD_3_56251]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP284]], ptr [[PTR2_0_56]], align 4
; CHECK-NEXT:    [[PTR_0_57:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 228
; CHECK-NEXT:    [[TMP285:%.*]] = load <4 x i8>, ptr [[PTR_0_57]], align 4
; CHECK-NEXT:    [[LOAD_0_57252:%.*]] = extractelement <4 x i8> [[TMP285]], i32 0
; CHECK-NEXT:    [[LOAD_1_57253:%.*]] = extractelement <4 x i8> [[TMP285]], i32 1
; CHECK-NEXT:    [[LOAD_2_57254:%.*]] = extractelement <4 x i8> [[TMP285]], i32 2
; CHECK-NEXT:    [[LOAD_3_57255:%.*]] = extractelement <4 x i8> [[TMP285]], i32 3
; CHECK-NEXT:    [[PTR2_0_57:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 228
; CHECK-NEXT:    [[TMP286:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_57252]], i32 0
; CHECK-NEXT:    [[TMP287:%.*]] = insertelement <4 x i8> [[TMP286]], i8 [[LOAD_1_57253]], i32 1
; CHECK-NEXT:    [[TMP288:%.*]] = insertelement <4 x i8> [[TMP287]], i8 [[LOAD_2_57254]], i32 2
; CHECK-NEXT:    [[TMP289:%.*]] = insertelement <4 x i8> [[TMP288]], i8 [[LOAD_3_57255]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP289]], ptr [[PTR2_0_57]], align 4
; CHECK-NEXT:    [[PTR_0_58:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 232
; CHECK-NEXT:    [[TMP290:%.*]] = load <4 x i8>, ptr [[PTR_0_58]], align 4
; CHECK-NEXT:    [[LOAD_0_58256:%.*]] = extractelement <4 x i8> [[TMP290]], i32 0
; CHECK-NEXT:    [[LOAD_1_58257:%.*]] = extractelement <4 x i8> [[TMP290]], i32 1
; CHECK-NEXT:    [[LOAD_2_58258:%.*]] = extractelement <4 x i8> [[TMP290]], i32 2
; CHECK-NEXT:    [[LOAD_3_58259:%.*]] = extractelement <4 x i8> [[TMP290]], i32 3
; CHECK-NEXT:    [[PTR2_0_58:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 232
; CHECK-NEXT:    [[TMP291:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_58256]], i32 0
; CHECK-NEXT:    [[TMP292:%.*]] = insertelement <4 x i8> [[TMP291]], i8 [[LOAD_1_58257]], i32 1
; CHECK-NEXT:    [[TMP293:%.*]] = insertelement <4 x i8> [[TMP292]], i8 [[LOAD_2_58258]], i32 2
; CHECK-NEXT:    [[TMP294:%.*]] = insertelement <4 x i8> [[TMP293]], i8 [[LOAD_3_58259]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP294]], ptr [[PTR2_0_58]], align 4
; CHECK-NEXT:    [[PTR_0_59:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 236
; CHECK-NEXT:    [[TMP295:%.*]] = load <4 x i8>, ptr [[PTR_0_59]], align 4
; CHECK-NEXT:    [[LOAD_0_59260:%.*]] = extractelement <4 x i8> [[TMP295]], i32 0
; CHECK-NEXT:    [[LOAD_1_59261:%.*]] = extractelement <4 x i8> [[TMP295]], i32 1
; CHECK-NEXT:    [[LOAD_2_59262:%.*]] = extractelement <4 x i8> [[TMP295]], i32 2
; CHECK-NEXT:    [[LOAD_3_59263:%.*]] = extractelement <4 x i8> [[TMP295]], i32 3
; CHECK-NEXT:    [[PTR2_0_59:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 236
; CHECK-NEXT:    [[TMP296:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_59260]], i32 0
; CHECK-NEXT:    [[TMP297:%.*]] = insertelement <4 x i8> [[TMP296]], i8 [[LOAD_1_59261]], i32 1
; CHECK-NEXT:    [[TMP298:%.*]] = insertelement <4 x i8> [[TMP297]], i8 [[LOAD_2_59262]], i32 2
; CHECK-NEXT:    [[TMP299:%.*]] = insertelement <4 x i8> [[TMP298]], i8 [[LOAD_3_59263]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP299]], ptr [[PTR2_0_59]], align 4
; CHECK-NEXT:    [[PTR_0_60:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 240
; CHECK-NEXT:    [[TMP300:%.*]] = load <4 x i8>, ptr [[PTR_0_60]], align 4
; CHECK-NEXT:    [[LOAD_0_60264:%.*]] = extractelement <4 x i8> [[TMP300]], i32 0
; CHECK-NEXT:    [[LOAD_1_60265:%.*]] = extractelement <4 x i8> [[TMP300]], i32 1
; CHECK-NEXT:    [[LOAD_2_60266:%.*]] = extractelement <4 x i8> [[TMP300]], i32 2
; CHECK-NEXT:    [[LOAD_3_60267:%.*]] = extractelement <4 x i8> [[TMP300]], i32 3
; CHECK-NEXT:    [[PTR2_0_60:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 240
; CHECK-NEXT:    [[TMP301:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_60264]], i32 0
; CHECK-NEXT:    [[TMP302:%.*]] = insertelement <4 x i8> [[TMP301]], i8 [[LOAD_1_60265]], i32 1
; CHECK-NEXT:    [[TMP303:%.*]] = insertelement <4 x i8> [[TMP302]], i8 [[LOAD_2_60266]], i32 2
; CHECK-NEXT:    [[TMP304:%.*]] = insertelement <4 x i8> [[TMP303]], i8 [[LOAD_3_60267]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP304]], ptr [[PTR2_0_60]], align 4
; CHECK-NEXT:    [[PTR_0_61:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 244
; CHECK-NEXT:    [[TMP305:%.*]] = load <4 x i8>, ptr [[PTR_0_61]], align 4
; CHECK-NEXT:    [[LOAD_0_61268:%.*]] = extractelement <4 x i8> [[TMP305]], i32 0
; CHECK-NEXT:    [[LOAD_1_61269:%.*]] = extractelement <4 x i8> [[TMP305]], i32 1
; CHECK-NEXT:    [[LOAD_2_61270:%.*]] = extractelement <4 x i8> [[TMP305]], i32 2
; CHECK-NEXT:    [[LOAD_3_61271:%.*]] = extractelement <4 x i8> [[TMP305]], i32 3
; CHECK-NEXT:    [[PTR2_0_61:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 244
; CHECK-NEXT:    [[TMP306:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_61268]], i32 0
; CHECK-NEXT:    [[TMP307:%.*]] = insertelement <4 x i8> [[TMP306]], i8 [[LOAD_1_61269]], i32 1
; CHECK-NEXT:    [[TMP308:%.*]] = insertelement <4 x i8> [[TMP307]], i8 [[LOAD_2_61270]], i32 2
; CHECK-NEXT:    [[TMP309:%.*]] = insertelement <4 x i8> [[TMP308]], i8 [[LOAD_3_61271]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP309]], ptr [[PTR2_0_61]], align 4
; CHECK-NEXT:    [[PTR_0_62:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 248
; CHECK-NEXT:    [[TMP310:%.*]] = load <4 x i8>, ptr [[PTR_0_62]], align 4
; CHECK-NEXT:    [[LOAD_0_62272:%.*]] = extractelement <4 x i8> [[TMP310]], i32 0
; CHECK-NEXT:    [[LOAD_1_62273:%.*]] = extractelement <4 x i8> [[TMP310]], i32 1
; CHECK-NEXT:    [[LOAD_2_62274:%.*]] = extractelement <4 x i8> [[TMP310]], i32 2
; CHECK-NEXT:    [[LOAD_3_62275:%.*]] = extractelement <4 x i8> [[TMP310]], i32 3
; CHECK-NEXT:    [[PTR2_0_62:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 248
; CHECK-NEXT:    [[TMP311:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_62272]], i32 0
; CHECK-NEXT:    [[TMP312:%.*]] = insertelement <4 x i8> [[TMP311]], i8 [[LOAD_1_62273]], i32 1
; CHECK-NEXT:    [[TMP313:%.*]] = insertelement <4 x i8> [[TMP312]], i8 [[LOAD_2_62274]], i32 2
; CHECK-NEXT:    [[TMP314:%.*]] = insertelement <4 x i8> [[TMP313]], i8 [[LOAD_3_62275]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP314]], ptr [[PTR2_0_62]], align 4
; CHECK-NEXT:    [[PTR_0_63:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 252
; CHECK-NEXT:    [[TMP315:%.*]] = load <4 x i8>, ptr [[PTR_0_63]], align 4
; CHECK-NEXT:    [[LOAD_0_63276:%.*]] = extractelement <4 x i8> [[TMP315]], i32 0
; CHECK-NEXT:    [[LOAD_1_63277:%.*]] = extractelement <4 x i8> [[TMP315]], i32 1
; CHECK-NEXT:    [[LOAD_2_63278:%.*]] = extractelement <4 x i8> [[TMP315]], i32 2
; CHECK-NEXT:    [[LOAD_3_63279:%.*]] = extractelement <4 x i8> [[TMP315]], i32 3
; CHECK-NEXT:    [[PTR2_0_63:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 252
; CHECK-NEXT:    [[TMP316:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_63276]], i32 0
; CHECK-NEXT:    [[TMP317:%.*]] = insertelement <4 x i8> [[TMP316]], i8 [[LOAD_1_63277]], i32 1
; CHECK-NEXT:    [[TMP318:%.*]] = insertelement <4 x i8> [[TMP317]], i8 [[LOAD_2_63278]], i32 2
; CHECK-NEXT:    [[TMP319:%.*]] = insertelement <4 x i8> [[TMP318]], i8 [[LOAD_3_63279]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP319]], ptr [[PTR2_0_63]], align 4
; CHECK-NEXT:    [[PTR_0_64:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 256
; CHECK-NEXT:    [[TMP320:%.*]] = load <4 x i8>, ptr [[PTR_0_64]], align 4
; CHECK-NEXT:    [[LOAD_0_64280:%.*]] = extractelement <4 x i8> [[TMP320]], i32 0
; CHECK-NEXT:    [[LOAD_1_64281:%.*]] = extractelement <4 x i8> [[TMP320]], i32 1
; CHECK-NEXT:    [[LOAD_2_64282:%.*]] = extractelement <4 x i8> [[TMP320]], i32 2
; CHECK-NEXT:    [[LOAD_3_64283:%.*]] = extractelement <4 x i8> [[TMP320]], i32 3
; CHECK-NEXT:    [[PTR2_0_64:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 256
; CHECK-NEXT:    [[TMP321:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_64280]], i32 0
; CHECK-NEXT:    [[TMP322:%.*]] = insertelement <4 x i8> [[TMP321]], i8 [[LOAD_1_64281]], i32 1
; CHECK-NEXT:    [[TMP323:%.*]] = insertelement <4 x i8> [[TMP322]], i8 [[LOAD_2_64282]], i32 2
; CHECK-NEXT:    [[TMP324:%.*]] = insertelement <4 x i8> [[TMP323]], i8 [[LOAD_3_64283]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP324]], ptr [[PTR2_0_64]], align 4
; CHECK-NEXT:    [[PTR_0_65:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 260
; CHECK-NEXT:    [[TMP325:%.*]] = load <4 x i8>, ptr [[PTR_0_65]], align 4
; CHECK-NEXT:    [[LOAD_0_65284:%.*]] = extractelement <4 x i8> [[TMP325]], i32 0
; CHECK-NEXT:    [[LOAD_1_65285:%.*]] = extractelement <4 x i8> [[TMP325]], i32 1
; CHECK-NEXT:    [[LOAD_2_65286:%.*]] = extractelement <4 x i8> [[TMP325]], i32 2
; CHECK-NEXT:    [[LOAD_3_65287:%.*]] = extractelement <4 x i8> [[TMP325]], i32 3
; CHECK-NEXT:    [[PTR2_0_65:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 260
; CHECK-NEXT:    [[TMP326:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_65284]], i32 0
; CHECK-NEXT:    [[TMP327:%.*]] = insertelement <4 x i8> [[TMP326]], i8 [[LOAD_1_65285]], i32 1
; CHECK-NEXT:    [[TMP328:%.*]] = insertelement <4 x i8> [[TMP327]], i8 [[LOAD_2_65286]], i32 2
; CHECK-NEXT:    [[TMP329:%.*]] = insertelement <4 x i8> [[TMP328]], i8 [[LOAD_3_65287]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP329]], ptr [[PTR2_0_65]], align 4
; CHECK-NEXT:    [[PTR_0_66:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 264
; CHECK-NEXT:    [[TMP330:%.*]] = load <4 x i8>, ptr [[PTR_0_66]], align 4
; CHECK-NEXT:    [[LOAD_0_66288:%.*]] = extractelement <4 x i8> [[TMP330]], i32 0
; CHECK-NEXT:    [[LOAD_1_66289:%.*]] = extractelement <4 x i8> [[TMP330]], i32 1
; CHECK-NEXT:    [[LOAD_2_66290:%.*]] = extractelement <4 x i8> [[TMP330]], i32 2
; CHECK-NEXT:    [[LOAD_3_66291:%.*]] = extractelement <4 x i8> [[TMP330]], i32 3
; CHECK-NEXT:    [[PTR2_0_66:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 264
; CHECK-NEXT:    [[TMP331:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_66288]], i32 0
; CHECK-NEXT:    [[TMP332:%.*]] = insertelement <4 x i8> [[TMP331]], i8 [[LOAD_1_66289]], i32 1
; CHECK-NEXT:    [[TMP333:%.*]] = insertelement <4 x i8> [[TMP332]], i8 [[LOAD_2_66290]], i32 2
; CHECK-NEXT:    [[TMP334:%.*]] = insertelement <4 x i8> [[TMP333]], i8 [[LOAD_3_66291]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP334]], ptr [[PTR2_0_66]], align 4
; CHECK-NEXT:    [[PTR_0_67:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 268
; CHECK-NEXT:    [[TMP335:%.*]] = load <4 x i8>, ptr [[PTR_0_67]], align 4
; CHECK-NEXT:    [[LOAD_0_67292:%.*]] = extractelement <4 x i8> [[TMP335]], i32 0
; CHECK-NEXT:    [[LOAD_1_67293:%.*]] = extractelement <4 x i8> [[TMP335]], i32 1
; CHECK-NEXT:    [[LOAD_2_67294:%.*]] = extractelement <4 x i8> [[TMP335]], i32 2
; CHECK-NEXT:    [[LOAD_3_67295:%.*]] = extractelement <4 x i8> [[TMP335]], i32 3
; CHECK-NEXT:    [[PTR2_0_67:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 268
; CHECK-NEXT:    [[TMP336:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_67292]], i32 0
; CHECK-NEXT:    [[TMP337:%.*]] = insertelement <4 x i8> [[TMP336]], i8 [[LOAD_1_67293]], i32 1
; CHECK-NEXT:    [[TMP338:%.*]] = insertelement <4 x i8> [[TMP337]], i8 [[LOAD_2_67294]], i32 2
; CHECK-NEXT:    [[TMP339:%.*]] = insertelement <4 x i8> [[TMP338]], i8 [[LOAD_3_67295]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP339]], ptr [[PTR2_0_67]], align 4
; CHECK-NEXT:    [[PTR_0_68:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 272
; CHECK-NEXT:    [[TMP340:%.*]] = load <4 x i8>, ptr [[PTR_0_68]], align 4
; CHECK-NEXT:    [[LOAD_0_68296:%.*]] = extractelement <4 x i8> [[TMP340]], i32 0
; CHECK-NEXT:    [[LOAD_1_68297:%.*]] = extractelement <4 x i8> [[TMP340]], i32 1
; CHECK-NEXT:    [[LOAD_2_68298:%.*]] = extractelement <4 x i8> [[TMP340]], i32 2
; CHECK-NEXT:    [[LOAD_3_68299:%.*]] = extractelement <4 x i8> [[TMP340]], i32 3
; CHECK-NEXT:    [[PTR2_0_68:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 272
; CHECK-NEXT:    [[TMP341:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_68296]], i32 0
; CHECK-NEXT:    [[TMP342:%.*]] = insertelement <4 x i8> [[TMP341]], i8 [[LOAD_1_68297]], i32 1
; CHECK-NEXT:    [[TMP343:%.*]] = insertelement <4 x i8> [[TMP342]], i8 [[LOAD_2_68298]], i32 2
; CHECK-NEXT:    [[TMP344:%.*]] = insertelement <4 x i8> [[TMP343]], i8 [[LOAD_3_68299]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP344]], ptr [[PTR2_0_68]], align 4
; CHECK-NEXT:    [[PTR_0_69:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 276
; CHECK-NEXT:    [[TMP345:%.*]] = load <4 x i8>, ptr [[PTR_0_69]], align 4
; CHECK-NEXT:    [[LOAD_0_69300:%.*]] = extractelement <4 x i8> [[TMP345]], i32 0
; CHECK-NEXT:    [[LOAD_1_69301:%.*]] = extractelement <4 x i8> [[TMP345]], i32 1
; CHECK-NEXT:    [[LOAD_2_69302:%.*]] = extractelement <4 x i8> [[TMP345]], i32 2
; CHECK-NEXT:    [[LOAD_3_69303:%.*]] = extractelement <4 x i8> [[TMP345]], i32 3
; CHECK-NEXT:    [[PTR2_0_69:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 276
; CHECK-NEXT:    [[TMP346:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_69300]], i32 0
; CHECK-NEXT:    [[TMP347:%.*]] = insertelement <4 x i8> [[TMP346]], i8 [[LOAD_1_69301]], i32 1
; CHECK-NEXT:    [[TMP348:%.*]] = insertelement <4 x i8> [[TMP347]], i8 [[LOAD_2_69302]], i32 2
; CHECK-NEXT:    [[TMP349:%.*]] = insertelement <4 x i8> [[TMP348]], i8 [[LOAD_3_69303]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP349]], ptr [[PTR2_0_69]], align 4
; CHECK-NEXT:    [[PTR_0_70:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 280
; CHECK-NEXT:    [[TMP350:%.*]] = load <4 x i8>, ptr [[PTR_0_70]], align 4
; CHECK-NEXT:    [[LOAD_0_70304:%.*]] = extractelement <4 x i8> [[TMP350]], i32 0
; CHECK-NEXT:    [[LOAD_1_70305:%.*]] = extractelement <4 x i8> [[TMP350]], i32 1
; CHECK-NEXT:    [[LOAD_2_70306:%.*]] = extractelement <4 x i8> [[TMP350]], i32 2
; CHECK-NEXT:    [[LOAD_3_70307:%.*]] = extractelement <4 x i8> [[TMP350]], i32 3
; CHECK-NEXT:    [[PTR2_0_70:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 280
; CHECK-NEXT:    [[TMP351:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_70304]], i32 0
; CHECK-NEXT:    [[TMP352:%.*]] = insertelement <4 x i8> [[TMP351]], i8 [[LOAD_1_70305]], i32 1
; CHECK-NEXT:    [[TMP353:%.*]] = insertelement <4 x i8> [[TMP352]], i8 [[LOAD_2_70306]], i32 2
; CHECK-NEXT:    [[TMP354:%.*]] = insertelement <4 x i8> [[TMP353]], i8 [[LOAD_3_70307]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP354]], ptr [[PTR2_0_70]], align 4
; CHECK-NEXT:    [[PTR_0_71:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 284
; CHECK-NEXT:    [[TMP355:%.*]] = load <4 x i8>, ptr [[PTR_0_71]], align 4
; CHECK-NEXT:    [[LOAD_0_71308:%.*]] = extractelement <4 x i8> [[TMP355]], i32 0
; CHECK-NEXT:    [[LOAD_1_71309:%.*]] = extractelement <4 x i8> [[TMP355]], i32 1
; CHECK-NEXT:    [[LOAD_2_71310:%.*]] = extractelement <4 x i8> [[TMP355]], i32 2
; CHECK-NEXT:    [[LOAD_3_71311:%.*]] = extractelement <4 x i8> [[TMP355]], i32 3
; CHECK-NEXT:    [[PTR2_0_71:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 284
; CHECK-NEXT:    [[TMP356:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_71308]], i32 0
; CHECK-NEXT:    [[TMP357:%.*]] = insertelement <4 x i8> [[TMP356]], i8 [[LOAD_1_71309]], i32 1
; CHECK-NEXT:    [[TMP358:%.*]] = insertelement <4 x i8> [[TMP357]], i8 [[LOAD_2_71310]], i32 2
; CHECK-NEXT:    [[TMP359:%.*]] = insertelement <4 x i8> [[TMP358]], i8 [[LOAD_3_71311]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP359]], ptr [[PTR2_0_71]], align 4
; CHECK-NEXT:    [[PTR_0_72:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 288
; CHECK-NEXT:    [[TMP360:%.*]] = load <4 x i8>, ptr [[PTR_0_72]], align 4
; CHECK-NEXT:    [[LOAD_0_72312:%.*]] = extractelement <4 x i8> [[TMP360]], i32 0
; CHECK-NEXT:    [[LOAD_1_72313:%.*]] = extractelement <4 x i8> [[TMP360]], i32 1
; CHECK-NEXT:    [[LOAD_2_72314:%.*]] = extractelement <4 x i8> [[TMP360]], i32 2
; CHECK-NEXT:    [[LOAD_3_72315:%.*]] = extractelement <4 x i8> [[TMP360]], i32 3
; CHECK-NEXT:    [[PTR2_0_72:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 288
; CHECK-NEXT:    [[TMP361:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_72312]], i32 0
; CHECK-NEXT:    [[TMP362:%.*]] = insertelement <4 x i8> [[TMP361]], i8 [[LOAD_1_72313]], i32 1
; CHECK-NEXT:    [[TMP363:%.*]] = insertelement <4 x i8> [[TMP362]], i8 [[LOAD_2_72314]], i32 2
; CHECK-NEXT:    [[TMP364:%.*]] = insertelement <4 x i8> [[TMP363]], i8 [[LOAD_3_72315]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP364]], ptr [[PTR2_0_72]], align 4
; CHECK-NEXT:    [[PTR_0_73:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 292
; CHECK-NEXT:    [[TMP365:%.*]] = load <4 x i8>, ptr [[PTR_0_73]], align 4
; CHECK-NEXT:    [[LOAD_0_73316:%.*]] = extractelement <4 x i8> [[TMP365]], i32 0
; CHECK-NEXT:    [[LOAD_1_73317:%.*]] = extractelement <4 x i8> [[TMP365]], i32 1
; CHECK-NEXT:    [[LOAD_2_73318:%.*]] = extractelement <4 x i8> [[TMP365]], i32 2
; CHECK-NEXT:    [[LOAD_3_73319:%.*]] = extractelement <4 x i8> [[TMP365]], i32 3
; CHECK-NEXT:    [[PTR2_0_73:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 292
; CHECK-NEXT:    [[TMP366:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_73316]], i32 0
; CHECK-NEXT:    [[TMP367:%.*]] = insertelement <4 x i8> [[TMP366]], i8 [[LOAD_1_73317]], i32 1
; CHECK-NEXT:    [[TMP368:%.*]] = insertelement <4 x i8> [[TMP367]], i8 [[LOAD_2_73318]], i32 2
; CHECK-NEXT:    [[TMP369:%.*]] = insertelement <4 x i8> [[TMP368]], i8 [[LOAD_3_73319]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP369]], ptr [[PTR2_0_73]], align 4
; CHECK-NEXT:    [[PTR_0_74:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 296
; CHECK-NEXT:    [[TMP370:%.*]] = load <4 x i8>, ptr [[PTR_0_74]], align 4
; CHECK-NEXT:    [[LOAD_0_74320:%.*]] = extractelement <4 x i8> [[TMP370]], i32 0
; CHECK-NEXT:    [[LOAD_1_74321:%.*]] = extractelement <4 x i8> [[TMP370]], i32 1
; CHECK-NEXT:    [[LOAD_2_74322:%.*]] = extractelement <4 x i8> [[TMP370]], i32 2
; CHECK-NEXT:    [[LOAD_3_74323:%.*]] = extractelement <4 x i8> [[TMP370]], i32 3
; CHECK-NEXT:    [[PTR2_0_74:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 296
; CHECK-NEXT:    [[TMP371:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_74320]], i32 0
; CHECK-NEXT:    [[TMP372:%.*]] = insertelement <4 x i8> [[TMP371]], i8 [[LOAD_1_74321]], i32 1
; CHECK-NEXT:    [[TMP373:%.*]] = insertelement <4 x i8> [[TMP372]], i8 [[LOAD_2_74322]], i32 2
; CHECK-NEXT:    [[TMP374:%.*]] = insertelement <4 x i8> [[TMP373]], i8 [[LOAD_3_74323]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP374]], ptr [[PTR2_0_74]], align 4
; CHECK-NEXT:    [[PTR_0_75:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 300
; CHECK-NEXT:    [[TMP375:%.*]] = load <4 x i8>, ptr [[PTR_0_75]], align 4
; CHECK-NEXT:    [[LOAD_0_75324:%.*]] = extractelement <4 x i8> [[TMP375]], i32 0
; CHECK-NEXT:    [[LOAD_1_75325:%.*]] = extractelement <4 x i8> [[TMP375]], i32 1
; CHECK-NEXT:    [[LOAD_2_75326:%.*]] = extractelement <4 x i8> [[TMP375]], i32 2
; CHECK-NEXT:    [[LOAD_3_75327:%.*]] = extractelement <4 x i8> [[TMP375]], i32 3
; CHECK-NEXT:    [[PTR2_0_75:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 300
; CHECK-NEXT:    [[TMP376:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_75324]], i32 0
; CHECK-NEXT:    [[TMP377:%.*]] = insertelement <4 x i8> [[TMP376]], i8 [[LOAD_1_75325]], i32 1
; CHECK-NEXT:    [[TMP378:%.*]] = insertelement <4 x i8> [[TMP377]], i8 [[LOAD_2_75326]], i32 2
; CHECK-NEXT:    [[TMP379:%.*]] = insertelement <4 x i8> [[TMP378]], i8 [[LOAD_3_75327]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP379]], ptr [[PTR2_0_75]], align 4
; CHECK-NEXT:    [[PTR_0_76:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 304
; CHECK-NEXT:    [[TMP380:%.*]] = load <4 x i8>, ptr [[PTR_0_76]], align 4
; CHECK-NEXT:    [[LOAD_0_76328:%.*]] = extractelement <4 x i8> [[TMP380]], i32 0
; CHECK-NEXT:    [[LOAD_1_76329:%.*]] = extractelement <4 x i8> [[TMP380]], i32 1
; CHECK-NEXT:    [[LOAD_2_76330:%.*]] = extractelement <4 x i8> [[TMP380]], i32 2
; CHECK-NEXT:    [[LOAD_3_76331:%.*]] = extractelement <4 x i8> [[TMP380]], i32 3
; CHECK-NEXT:    [[PTR2_0_76:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 304
; CHECK-NEXT:    [[TMP381:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_76328]], i32 0
; CHECK-NEXT:    [[TMP382:%.*]] = insertelement <4 x i8> [[TMP381]], i8 [[LOAD_1_76329]], i32 1
; CHECK-NEXT:    [[TMP383:%.*]] = insertelement <4 x i8> [[TMP382]], i8 [[LOAD_2_76330]], i32 2
; CHECK-NEXT:    [[TMP384:%.*]] = insertelement <4 x i8> [[TMP383]], i8 [[LOAD_3_76331]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP384]], ptr [[PTR2_0_76]], align 4
; CHECK-NEXT:    [[PTR_0_77:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 308
; CHECK-NEXT:    [[TMP385:%.*]] = load <4 x i8>, ptr [[PTR_0_77]], align 4
; CHECK-NEXT:    [[LOAD_0_77332:%.*]] = extractelement <4 x i8> [[TMP385]], i32 0
; CHECK-NEXT:    [[LOAD_1_77333:%.*]] = extractelement <4 x i8> [[TMP385]], i32 1
; CHECK-NEXT:    [[LOAD_2_77334:%.*]] = extractelement <4 x i8> [[TMP385]], i32 2
; CHECK-NEXT:    [[LOAD_3_77335:%.*]] = extractelement <4 x i8> [[TMP385]], i32 3
; CHECK-NEXT:    [[PTR2_0_77:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 308
; CHECK-NEXT:    [[TMP386:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_77332]], i32 0
; CHECK-NEXT:    [[TMP387:%.*]] = insertelement <4 x i8> [[TMP386]], i8 [[LOAD_1_77333]], i32 1
; CHECK-NEXT:    [[TMP388:%.*]] = insertelement <4 x i8> [[TMP387]], i8 [[LOAD_2_77334]], i32 2
; CHECK-NEXT:    [[TMP389:%.*]] = insertelement <4 x i8> [[TMP388]], i8 [[LOAD_3_77335]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP389]], ptr [[PTR2_0_77]], align 4
; CHECK-NEXT:    [[PTR_0_78:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 312
; CHECK-NEXT:    [[TMP390:%.*]] = load <4 x i8>, ptr [[PTR_0_78]], align 4
; CHECK-NEXT:    [[LOAD_0_78336:%.*]] = extractelement <4 x i8> [[TMP390]], i32 0
; CHECK-NEXT:    [[LOAD_1_78337:%.*]] = extractelement <4 x i8> [[TMP390]], i32 1
; CHECK-NEXT:    [[LOAD_2_78338:%.*]] = extractelement <4 x i8> [[TMP390]], i32 2
; CHECK-NEXT:    [[LOAD_3_78339:%.*]] = extractelement <4 x i8> [[TMP390]], i32 3
; CHECK-NEXT:    [[PTR2_0_78:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 312
; CHECK-NEXT:    [[TMP391:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_78336]], i32 0
; CHECK-NEXT:    [[TMP392:%.*]] = insertelement <4 x i8> [[TMP391]], i8 [[LOAD_1_78337]], i32 1
; CHECK-NEXT:    [[TMP393:%.*]] = insertelement <4 x i8> [[TMP392]], i8 [[LOAD_2_78338]], i32 2
; CHECK-NEXT:    [[TMP394:%.*]] = insertelement <4 x i8> [[TMP393]], i8 [[LOAD_3_78339]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP394]], ptr [[PTR2_0_78]], align 4
; CHECK-NEXT:    [[PTR_0_79:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 316
; CHECK-NEXT:    [[TMP395:%.*]] = load <4 x i8>, ptr [[PTR_0_79]], align 4
; CHECK-NEXT:    [[LOAD_0_79340:%.*]] = extractelement <4 x i8> [[TMP395]], i32 0
; CHECK-NEXT:    [[LOAD_1_79341:%.*]] = extractelement <4 x i8> [[TMP395]], i32 1
; CHECK-NEXT:    [[LOAD_2_79342:%.*]] = extractelement <4 x i8> [[TMP395]], i32 2
; CHECK-NEXT:    [[LOAD_3_79343:%.*]] = extractelement <4 x i8> [[TMP395]], i32 3
; CHECK-NEXT:    [[PTR2_0_79:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 316
; CHECK-NEXT:    [[TMP396:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_79340]], i32 0
; CHECK-NEXT:    [[TMP397:%.*]] = insertelement <4 x i8> [[TMP396]], i8 [[LOAD_1_79341]], i32 1
; CHECK-NEXT:    [[TMP398:%.*]] = insertelement <4 x i8> [[TMP397]], i8 [[LOAD_2_79342]], i32 2
; CHECK-NEXT:    [[TMP399:%.*]] = insertelement <4 x i8> [[TMP398]], i8 [[LOAD_3_79343]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP399]], ptr [[PTR2_0_79]], align 4
; CHECK-NEXT:    [[PTR_0_80:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 320
; CHECK-NEXT:    [[TMP400:%.*]] = load <4 x i8>, ptr [[PTR_0_80]], align 4
; CHECK-NEXT:    [[LOAD_0_80344:%.*]] = extractelement <4 x i8> [[TMP400]], i32 0
; CHECK-NEXT:    [[LOAD_1_80345:%.*]] = extractelement <4 x i8> [[TMP400]], i32 1
; CHECK-NEXT:    [[LOAD_2_80346:%.*]] = extractelement <4 x i8> [[TMP400]], i32 2
; CHECK-NEXT:    [[LOAD_3_80347:%.*]] = extractelement <4 x i8> [[TMP400]], i32 3
; CHECK-NEXT:    [[PTR2_0_80:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 320
; CHECK-NEXT:    [[TMP401:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_80344]], i32 0
; CHECK-NEXT:    [[TMP402:%.*]] = insertelement <4 x i8> [[TMP401]], i8 [[LOAD_1_80345]], i32 1
; CHECK-NEXT:    [[TMP403:%.*]] = insertelement <4 x i8> [[TMP402]], i8 [[LOAD_2_80346]], i32 2
; CHECK-NEXT:    [[TMP404:%.*]] = insertelement <4 x i8> [[TMP403]], i8 [[LOAD_3_80347]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP404]], ptr [[PTR2_0_80]], align 4
; CHECK-NEXT:    [[PTR_0_81:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 324
; CHECK-NEXT:    [[TMP405:%.*]] = load <4 x i8>, ptr [[PTR_0_81]], align 4
; CHECK-NEXT:    [[LOAD_0_81348:%.*]] = extractelement <4 x i8> [[TMP405]], i32 0
; CHECK-NEXT:    [[LOAD_1_81349:%.*]] = extractelement <4 x i8> [[TMP405]], i32 1
; CHECK-NEXT:    [[LOAD_2_81350:%.*]] = extractelement <4 x i8> [[TMP405]], i32 2
; CHECK-NEXT:    [[LOAD_3_81351:%.*]] = extractelement <4 x i8> [[TMP405]], i32 3
; CHECK-NEXT:    [[PTR2_0_81:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 324
; CHECK-NEXT:    [[TMP406:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_81348]], i32 0
; CHECK-NEXT:    [[TMP407:%.*]] = insertelement <4 x i8> [[TMP406]], i8 [[LOAD_1_81349]], i32 1
; CHECK-NEXT:    [[TMP408:%.*]] = insertelement <4 x i8> [[TMP407]], i8 [[LOAD_2_81350]], i32 2
; CHECK-NEXT:    [[TMP409:%.*]] = insertelement <4 x i8> [[TMP408]], i8 [[LOAD_3_81351]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP409]], ptr [[PTR2_0_81]], align 4
; CHECK-NEXT:    [[PTR_0_82:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 328
; CHECK-NEXT:    [[TMP410:%.*]] = load <4 x i8>, ptr [[PTR_0_82]], align 4
; CHECK-NEXT:    [[LOAD_0_82352:%.*]] = extractelement <4 x i8> [[TMP410]], i32 0
; CHECK-NEXT:    [[LOAD_1_82353:%.*]] = extractelement <4 x i8> [[TMP410]], i32 1
; CHECK-NEXT:    [[LOAD_2_82354:%.*]] = extractelement <4 x i8> [[TMP410]], i32 2
; CHECK-NEXT:    [[LOAD_3_82355:%.*]] = extractelement <4 x i8> [[TMP410]], i32 3
; CHECK-NEXT:    [[PTR2_0_82:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 328
; CHECK-NEXT:    [[TMP411:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_82352]], i32 0
; CHECK-NEXT:    [[TMP412:%.*]] = insertelement <4 x i8> [[TMP411]], i8 [[LOAD_1_82353]], i32 1
; CHECK-NEXT:    [[TMP413:%.*]] = insertelement <4 x i8> [[TMP412]], i8 [[LOAD_2_82354]], i32 2
; CHECK-NEXT:    [[TMP414:%.*]] = insertelement <4 x i8> [[TMP413]], i8 [[LOAD_3_82355]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP414]], ptr [[PTR2_0_82]], align 4
; CHECK-NEXT:    [[PTR_0_83:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 332
; CHECK-NEXT:    [[TMP415:%.*]] = load <4 x i8>, ptr [[PTR_0_83]], align 4
; CHECK-NEXT:    [[LOAD_0_83356:%.*]] = extractelement <4 x i8> [[TMP415]], i32 0
; CHECK-NEXT:    [[LOAD_1_83357:%.*]] = extractelement <4 x i8> [[TMP415]], i32 1
; CHECK-NEXT:    [[LOAD_2_83358:%.*]] = extractelement <4 x i8> [[TMP415]], i32 2
; CHECK-NEXT:    [[LOAD_3_83359:%.*]] = extractelement <4 x i8> [[TMP415]], i32 3
; CHECK-NEXT:    [[PTR2_0_83:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 332
; CHECK-NEXT:    [[TMP416:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_83356]], i32 0
; CHECK-NEXT:    [[TMP417:%.*]] = insertelement <4 x i8> [[TMP416]], i8 [[LOAD_1_83357]], i32 1
; CHECK-NEXT:    [[TMP418:%.*]] = insertelement <4 x i8> [[TMP417]], i8 [[LOAD_2_83358]], i32 2
; CHECK-NEXT:    [[TMP419:%.*]] = insertelement <4 x i8> [[TMP418]], i8 [[LOAD_3_83359]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP419]], ptr [[PTR2_0_83]], align 4
; CHECK-NEXT:    [[PTR_0_84:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 336
; CHECK-NEXT:    [[TMP420:%.*]] = load <4 x i8>, ptr [[PTR_0_84]], align 4
; CHECK-NEXT:    [[LOAD_0_84360:%.*]] = extractelement <4 x i8> [[TMP420]], i32 0
; CHECK-NEXT:    [[LOAD_1_84361:%.*]] = extractelement <4 x i8> [[TMP420]], i32 1
; CHECK-NEXT:    [[LOAD_2_84362:%.*]] = extractelement <4 x i8> [[TMP420]], i32 2
; CHECK-NEXT:    [[LOAD_3_84363:%.*]] = extractelement <4 x i8> [[TMP420]], i32 3
; CHECK-NEXT:    [[PTR2_0_84:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 336
; CHECK-NEXT:    [[TMP421:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_84360]], i32 0
; CHECK-NEXT:    [[TMP422:%.*]] = insertelement <4 x i8> [[TMP421]], i8 [[LOAD_1_84361]], i32 1
; CHECK-NEXT:    [[TMP423:%.*]] = insertelement <4 x i8> [[TMP422]], i8 [[LOAD_2_84362]], i32 2
; CHECK-NEXT:    [[TMP424:%.*]] = insertelement <4 x i8> [[TMP423]], i8 [[LOAD_3_84363]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP424]], ptr [[PTR2_0_84]], align 4
; CHECK-NEXT:    [[PTR_0_85:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 340
; CHECK-NEXT:    [[TMP425:%.*]] = load <4 x i8>, ptr [[PTR_0_85]], align 4
; CHECK-NEXT:    [[LOAD_0_85364:%.*]] = extractelement <4 x i8> [[TMP425]], i32 0
; CHECK-NEXT:    [[LOAD_1_85365:%.*]] = extractelement <4 x i8> [[TMP425]], i32 1
; CHECK-NEXT:    [[LOAD_2_85366:%.*]] = extractelement <4 x i8> [[TMP425]], i32 2
; CHECK-NEXT:    [[LOAD_3_85367:%.*]] = extractelement <4 x i8> [[TMP425]], i32 3
; CHECK-NEXT:    [[PTR2_0_85:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 340
; CHECK-NEXT:    [[TMP426:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_85364]], i32 0
; CHECK-NEXT:    [[TMP427:%.*]] = insertelement <4 x i8> [[TMP426]], i8 [[LOAD_1_85365]], i32 1
; CHECK-NEXT:    [[TMP428:%.*]] = insertelement <4 x i8> [[TMP427]], i8 [[LOAD_2_85366]], i32 2
; CHECK-NEXT:    [[TMP429:%.*]] = insertelement <4 x i8> [[TMP428]], i8 [[LOAD_3_85367]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP429]], ptr [[PTR2_0_85]], align 4
; CHECK-NEXT:    [[PTR_0_86:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 344
; CHECK-NEXT:    [[TMP430:%.*]] = load <4 x i8>, ptr [[PTR_0_86]], align 4
; CHECK-NEXT:    [[LOAD_0_86368:%.*]] = extractelement <4 x i8> [[TMP430]], i32 0
; CHECK-NEXT:    [[LOAD_1_86369:%.*]] = extractelement <4 x i8> [[TMP430]], i32 1
; CHECK-NEXT:    [[LOAD_2_86370:%.*]] = extractelement <4 x i8> [[TMP430]], i32 2
; CHECK-NEXT:    [[LOAD_3_86371:%.*]] = extractelement <4 x i8> [[TMP430]], i32 3
; CHECK-NEXT:    [[PTR2_0_86:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 344
; CHECK-NEXT:    [[TMP431:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_86368]], i32 0
; CHECK-NEXT:    [[TMP432:%.*]] = insertelement <4 x i8> [[TMP431]], i8 [[LOAD_1_86369]], i32 1
; CHECK-NEXT:    [[TMP433:%.*]] = insertelement <4 x i8> [[TMP432]], i8 [[LOAD_2_86370]], i32 2
; CHECK-NEXT:    [[TMP434:%.*]] = insertelement <4 x i8> [[TMP433]], i8 [[LOAD_3_86371]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP434]], ptr [[PTR2_0_86]], align 4
; CHECK-NEXT:    [[PTR_0_87:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 348
; CHECK-NEXT:    [[TMP435:%.*]] = load <4 x i8>, ptr [[PTR_0_87]], align 4
; CHECK-NEXT:    [[LOAD_0_87372:%.*]] = extractelement <4 x i8> [[TMP435]], i32 0
; CHECK-NEXT:    [[LOAD_1_87373:%.*]] = extractelement <4 x i8> [[TMP435]], i32 1
; CHECK-NEXT:    [[LOAD_2_87374:%.*]] = extractelement <4 x i8> [[TMP435]], i32 2
; CHECK-NEXT:    [[LOAD_3_87375:%.*]] = extractelement <4 x i8> [[TMP435]], i32 3
; CHECK-NEXT:    [[PTR2_0_87:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 348
; CHECK-NEXT:    [[TMP436:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_87372]], i32 0
; CHECK-NEXT:    [[TMP437:%.*]] = insertelement <4 x i8> [[TMP436]], i8 [[LOAD_1_87373]], i32 1
; CHECK-NEXT:    [[TMP438:%.*]] = insertelement <4 x i8> [[TMP437]], i8 [[LOAD_2_87374]], i32 2
; CHECK-NEXT:    [[TMP439:%.*]] = insertelement <4 x i8> [[TMP438]], i8 [[LOAD_3_87375]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP439]], ptr [[PTR2_0_87]], align 4
; CHECK-NEXT:    [[PTR_0_88:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 352
; CHECK-NEXT:    [[TMP440:%.*]] = load <4 x i8>, ptr [[PTR_0_88]], align 4
; CHECK-NEXT:    [[LOAD_0_88376:%.*]] = extractelement <4 x i8> [[TMP440]], i32 0
; CHECK-NEXT:    [[LOAD_1_88377:%.*]] = extractelement <4 x i8> [[TMP440]], i32 1
; CHECK-NEXT:    [[LOAD_2_88378:%.*]] = extractelement <4 x i8> [[TMP440]], i32 2
; CHECK-NEXT:    [[LOAD_3_88379:%.*]] = extractelement <4 x i8> [[TMP440]], i32 3
; CHECK-NEXT:    [[PTR2_0_88:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 352
; CHECK-NEXT:    [[TMP441:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_88376]], i32 0
; CHECK-NEXT:    [[TMP442:%.*]] = insertelement <4 x i8> [[TMP441]], i8 [[LOAD_1_88377]], i32 1
; CHECK-NEXT:    [[TMP443:%.*]] = insertelement <4 x i8> [[TMP442]], i8 [[LOAD_2_88378]], i32 2
; CHECK-NEXT:    [[TMP444:%.*]] = insertelement <4 x i8> [[TMP443]], i8 [[LOAD_3_88379]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP444]], ptr [[PTR2_0_88]], align 4
; CHECK-NEXT:    [[PTR_0_89:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 356
; CHECK-NEXT:    [[TMP445:%.*]] = load <4 x i8>, ptr [[PTR_0_89]], align 4
; CHECK-NEXT:    [[LOAD_0_89380:%.*]] = extractelement <4 x i8> [[TMP445]], i32 0
; CHECK-NEXT:    [[LOAD_1_89381:%.*]] = extractelement <4 x i8> [[TMP445]], i32 1
; CHECK-NEXT:    [[LOAD_2_89382:%.*]] = extractelement <4 x i8> [[TMP445]], i32 2
; CHECK-NEXT:    [[LOAD_3_89383:%.*]] = extractelement <4 x i8> [[TMP445]], i32 3
; CHECK-NEXT:    [[PTR2_0_89:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 356
; CHECK-NEXT:    [[TMP446:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_89380]], i32 0
; CHECK-NEXT:    [[TMP447:%.*]] = insertelement <4 x i8> [[TMP446]], i8 [[LOAD_1_89381]], i32 1
; CHECK-NEXT:    [[TMP448:%.*]] = insertelement <4 x i8> [[TMP447]], i8 [[LOAD_2_89382]], i32 2
; CHECK-NEXT:    [[TMP449:%.*]] = insertelement <4 x i8> [[TMP448]], i8 [[LOAD_3_89383]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP449]], ptr [[PTR2_0_89]], align 4
; CHECK-NEXT:    [[PTR_0_90:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 360
; CHECK-NEXT:    [[TMP450:%.*]] = load <4 x i8>, ptr [[PTR_0_90]], align 4
; CHECK-NEXT:    [[LOAD_0_90384:%.*]] = extractelement <4 x i8> [[TMP450]], i32 0
; CHECK-NEXT:    [[LOAD_1_90385:%.*]] = extractelement <4 x i8> [[TMP450]], i32 1
; CHECK-NEXT:    [[LOAD_2_90386:%.*]] = extractelement <4 x i8> [[TMP450]], i32 2
; CHECK-NEXT:    [[LOAD_3_90387:%.*]] = extractelement <4 x i8> [[TMP450]], i32 3
; CHECK-NEXT:    [[PTR2_0_90:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 360
; CHECK-NEXT:    [[TMP451:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_90384]], i32 0
; CHECK-NEXT:    [[TMP452:%.*]] = insertelement <4 x i8> [[TMP451]], i8 [[LOAD_1_90385]], i32 1
; CHECK-NEXT:    [[TMP453:%.*]] = insertelement <4 x i8> [[TMP452]], i8 [[LOAD_2_90386]], i32 2
; CHECK-NEXT:    [[TMP454:%.*]] = insertelement <4 x i8> [[TMP453]], i8 [[LOAD_3_90387]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP454]], ptr [[PTR2_0_90]], align 4
; CHECK-NEXT:    [[PTR_0_91:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 364
; CHECK-NEXT:    [[TMP455:%.*]] = load <4 x i8>, ptr [[PTR_0_91]], align 4
; CHECK-NEXT:    [[LOAD_0_91388:%.*]] = extractelement <4 x i8> [[TMP455]], i32 0
; CHECK-NEXT:    [[LOAD_1_91389:%.*]] = extractelement <4 x i8> [[TMP455]], i32 1
; CHECK-NEXT:    [[LOAD_2_91390:%.*]] = extractelement <4 x i8> [[TMP455]], i32 2
; CHECK-NEXT:    [[LOAD_3_91391:%.*]] = extractelement <4 x i8> [[TMP455]], i32 3
; CHECK-NEXT:    [[PTR2_0_91:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 364
; CHECK-NEXT:    [[TMP456:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_91388]], i32 0
; CHECK-NEXT:    [[TMP457:%.*]] = insertelement <4 x i8> [[TMP456]], i8 [[LOAD_1_91389]], i32 1
; CHECK-NEXT:    [[TMP458:%.*]] = insertelement <4 x i8> [[TMP457]], i8 [[LOAD_2_91390]], i32 2
; CHECK-NEXT:    [[TMP459:%.*]] = insertelement <4 x i8> [[TMP458]], i8 [[LOAD_3_91391]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP459]], ptr [[PTR2_0_91]], align 4
; CHECK-NEXT:    [[PTR_0_92:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 368
; CHECK-NEXT:    [[TMP460:%.*]] = load <4 x i8>, ptr [[PTR_0_92]], align 4
; CHECK-NEXT:    [[LOAD_0_92392:%.*]] = extractelement <4 x i8> [[TMP460]], i32 0
; CHECK-NEXT:    [[LOAD_1_92393:%.*]] = extractelement <4 x i8> [[TMP460]], i32 1
; CHECK-NEXT:    [[LOAD_2_92394:%.*]] = extractelement <4 x i8> [[TMP460]], i32 2
; CHECK-NEXT:    [[LOAD_3_92395:%.*]] = extractelement <4 x i8> [[TMP460]], i32 3
; CHECK-NEXT:    [[PTR2_0_92:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 368
; CHECK-NEXT:    [[TMP461:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_92392]], i32 0
; CHECK-NEXT:    [[TMP462:%.*]] = insertelement <4 x i8> [[TMP461]], i8 [[LOAD_1_92393]], i32 1
; CHECK-NEXT:    [[TMP463:%.*]] = insertelement <4 x i8> [[TMP462]], i8 [[LOAD_2_92394]], i32 2
; CHECK-NEXT:    [[TMP464:%.*]] = insertelement <4 x i8> [[TMP463]], i8 [[LOAD_3_92395]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP464]], ptr [[PTR2_0_92]], align 4
; CHECK-NEXT:    [[PTR_0_93:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 372
; CHECK-NEXT:    [[TMP465:%.*]] = load <4 x i8>, ptr [[PTR_0_93]], align 4
; CHECK-NEXT:    [[LOAD_0_93396:%.*]] = extractelement <4 x i8> [[TMP465]], i32 0
; CHECK-NEXT:    [[LOAD_1_93397:%.*]] = extractelement <4 x i8> [[TMP465]], i32 1
; CHECK-NEXT:    [[LOAD_2_93398:%.*]] = extractelement <4 x i8> [[TMP465]], i32 2
; CHECK-NEXT:    [[LOAD_3_93399:%.*]] = extractelement <4 x i8> [[TMP465]], i32 3
; CHECK-NEXT:    [[PTR2_0_93:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 372
; CHECK-NEXT:    [[TMP466:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_93396]], i32 0
; CHECK-NEXT:    [[TMP467:%.*]] = insertelement <4 x i8> [[TMP466]], i8 [[LOAD_1_93397]], i32 1
; CHECK-NEXT:    [[TMP468:%.*]] = insertelement <4 x i8> [[TMP467]], i8 [[LOAD_2_93398]], i32 2
; CHECK-NEXT:    [[TMP469:%.*]] = insertelement <4 x i8> [[TMP468]], i8 [[LOAD_3_93399]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP469]], ptr [[PTR2_0_93]], align 4
; CHECK-NEXT:    [[PTR_0_94:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 376
; CHECK-NEXT:    [[TMP470:%.*]] = load <4 x i8>, ptr [[PTR_0_94]], align 4
; CHECK-NEXT:    [[LOAD_0_94400:%.*]] = extractelement <4 x i8> [[TMP470]], i32 0
; CHECK-NEXT:    [[LOAD_1_94401:%.*]] = extractelement <4 x i8> [[TMP470]], i32 1
; CHECK-NEXT:    [[LOAD_2_94402:%.*]] = extractelement <4 x i8> [[TMP470]], i32 2
; CHECK-NEXT:    [[LOAD_3_94403:%.*]] = extractelement <4 x i8> [[TMP470]], i32 3
; CHECK-NEXT:    [[PTR2_0_94:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 376
; CHECK-NEXT:    [[TMP471:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_94400]], i32 0
; CHECK-NEXT:    [[TMP472:%.*]] = insertelement <4 x i8> [[TMP471]], i8 [[LOAD_1_94401]], i32 1
; CHECK-NEXT:    [[TMP473:%.*]] = insertelement <4 x i8> [[TMP472]], i8 [[LOAD_2_94402]], i32 2
; CHECK-NEXT:    [[TMP474:%.*]] = insertelement <4 x i8> [[TMP473]], i8 [[LOAD_3_94403]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP474]], ptr [[PTR2_0_94]], align 4
; CHECK-NEXT:    [[PTR_0_95:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 380
; CHECK-NEXT:    [[TMP475:%.*]] = load <4 x i8>, ptr [[PTR_0_95]], align 4
; CHECK-NEXT:    [[LOAD_0_95404:%.*]] = extractelement <4 x i8> [[TMP475]], i32 0
; CHECK-NEXT:    [[LOAD_1_95405:%.*]] = extractelement <4 x i8> [[TMP475]], i32 1
; CHECK-NEXT:    [[LOAD_2_95406:%.*]] = extractelement <4 x i8> [[TMP475]], i32 2
; CHECK-NEXT:    [[LOAD_3_95407:%.*]] = extractelement <4 x i8> [[TMP475]], i32 3
; CHECK-NEXT:    [[PTR2_0_95:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 380
; CHECK-NEXT:    [[TMP476:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_95404]], i32 0
; CHECK-NEXT:    [[TMP477:%.*]] = insertelement <4 x i8> [[TMP476]], i8 [[LOAD_1_95405]], i32 1
; CHECK-NEXT:    [[TMP478:%.*]] = insertelement <4 x i8> [[TMP477]], i8 [[LOAD_2_95406]], i32 2
; CHECK-NEXT:    [[TMP479:%.*]] = insertelement <4 x i8> [[TMP478]], i8 [[LOAD_3_95407]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP479]], ptr [[PTR2_0_95]], align 4
; CHECK-NEXT:    [[PTR_0_96:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 384
; CHECK-NEXT:    [[TMP480:%.*]] = load <4 x i8>, ptr [[PTR_0_96]], align 4
; CHECK-NEXT:    [[LOAD_0_96408:%.*]] = extractelement <4 x i8> [[TMP480]], i32 0
; CHECK-NEXT:    [[LOAD_1_96409:%.*]] = extractelement <4 x i8> [[TMP480]], i32 1
; CHECK-NEXT:    [[LOAD_2_96410:%.*]] = extractelement <4 x i8> [[TMP480]], i32 2
; CHECK-NEXT:    [[LOAD_3_96411:%.*]] = extractelement <4 x i8> [[TMP480]], i32 3
; CHECK-NEXT:    [[PTR2_0_96:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 384
; CHECK-NEXT:    [[TMP481:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_96408]], i32 0
; CHECK-NEXT:    [[TMP482:%.*]] = insertelement <4 x i8> [[TMP481]], i8 [[LOAD_1_96409]], i32 1
; CHECK-NEXT:    [[TMP483:%.*]] = insertelement <4 x i8> [[TMP482]], i8 [[LOAD_2_96410]], i32 2
; CHECK-NEXT:    [[TMP484:%.*]] = insertelement <4 x i8> [[TMP483]], i8 [[LOAD_3_96411]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP484]], ptr [[PTR2_0_96]], align 4
; CHECK-NEXT:    [[PTR_0_97:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 388
; CHECK-NEXT:    [[TMP485:%.*]] = load <4 x i8>, ptr [[PTR_0_97]], align 4
; CHECK-NEXT:    [[LOAD_0_97412:%.*]] = extractelement <4 x i8> [[TMP485]], i32 0
; CHECK-NEXT:    [[LOAD_1_97413:%.*]] = extractelement <4 x i8> [[TMP485]], i32 1
; CHECK-NEXT:    [[LOAD_2_97414:%.*]] = extractelement <4 x i8> [[TMP485]], i32 2
; CHECK-NEXT:    [[LOAD_3_97415:%.*]] = extractelement <4 x i8> [[TMP485]], i32 3
; CHECK-NEXT:    [[PTR2_0_97:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 388
; CHECK-NEXT:    [[TMP486:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_97412]], i32 0
; CHECK-NEXT:    [[TMP487:%.*]] = insertelement <4 x i8> [[TMP486]], i8 [[LOAD_1_97413]], i32 1
; CHECK-NEXT:    [[TMP488:%.*]] = insertelement <4 x i8> [[TMP487]], i8 [[LOAD_2_97414]], i32 2
; CHECK-NEXT:    [[TMP489:%.*]] = insertelement <4 x i8> [[TMP488]], i8 [[LOAD_3_97415]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP489]], ptr [[PTR2_0_97]], align 4
; CHECK-NEXT:    [[PTR_0_98:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 392
; CHECK-NEXT:    [[TMP490:%.*]] = load <4 x i8>, ptr [[PTR_0_98]], align 4
; CHECK-NEXT:    [[LOAD_0_98416:%.*]] = extractelement <4 x i8> [[TMP490]], i32 0
; CHECK-NEXT:    [[LOAD_1_98417:%.*]] = extractelement <4 x i8> [[TMP490]], i32 1
; CHECK-NEXT:    [[LOAD_2_98418:%.*]] = extractelement <4 x i8> [[TMP490]], i32 2
; CHECK-NEXT:    [[LOAD_3_98419:%.*]] = extractelement <4 x i8> [[TMP490]], i32 3
; CHECK-NEXT:    [[PTR2_0_98:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 392
; CHECK-NEXT:    [[TMP491:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_98416]], i32 0
; CHECK-NEXT:    [[TMP492:%.*]] = insertelement <4 x i8> [[TMP491]], i8 [[LOAD_1_98417]], i32 1
; CHECK-NEXT:    [[TMP493:%.*]] = insertelement <4 x i8> [[TMP492]], i8 [[LOAD_2_98418]], i32 2
; CHECK-NEXT:    [[TMP494:%.*]] = insertelement <4 x i8> [[TMP493]], i8 [[LOAD_3_98419]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP494]], ptr [[PTR2_0_98]], align 4
; CHECK-NEXT:    [[PTR_0_99:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 396
; CHECK-NEXT:    [[TMP495:%.*]] = load <4 x i8>, ptr [[PTR_0_99]], align 4
; CHECK-NEXT:    [[LOAD_0_99420:%.*]] = extractelement <4 x i8> [[TMP495]], i32 0
; CHECK-NEXT:    [[LOAD_1_99421:%.*]] = extractelement <4 x i8> [[TMP495]], i32 1
; CHECK-NEXT:    [[LOAD_2_99422:%.*]] = extractelement <4 x i8> [[TMP495]], i32 2
; CHECK-NEXT:    [[LOAD_3_99423:%.*]] = extractelement <4 x i8> [[TMP495]], i32 3
; CHECK-NEXT:    [[PTR2_0_99:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 396
; CHECK-NEXT:    [[TMP496:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_99420]], i32 0
; CHECK-NEXT:    [[TMP497:%.*]] = insertelement <4 x i8> [[TMP496]], i8 [[LOAD_1_99421]], i32 1
; CHECK-NEXT:    [[TMP498:%.*]] = insertelement <4 x i8> [[TMP497]], i8 [[LOAD_2_99422]], i32 2
; CHECK-NEXT:    [[TMP499:%.*]] = insertelement <4 x i8> [[TMP498]], i8 [[LOAD_3_99423]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP499]], ptr [[PTR2_0_99]], align 4
; CHECK-NEXT:    [[PTR_0_100:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 400
; CHECK-NEXT:    [[TMP500:%.*]] = load <4 x i8>, ptr [[PTR_0_100]], align 4
; CHECK-NEXT:    [[LOAD_0_100424:%.*]] = extractelement <4 x i8> [[TMP500]], i32 0
; CHECK-NEXT:    [[LOAD_1_100425:%.*]] = extractelement <4 x i8> [[TMP500]], i32 1
; CHECK-NEXT:    [[LOAD_2_100426:%.*]] = extractelement <4 x i8> [[TMP500]], i32 2
; CHECK-NEXT:    [[LOAD_3_100427:%.*]] = extractelement <4 x i8> [[TMP500]], i32 3
; CHECK-NEXT:    [[PTR2_0_100:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 400
; CHECK-NEXT:    [[TMP501:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_100424]], i32 0
; CHECK-NEXT:    [[TMP502:%.*]] = insertelement <4 x i8> [[TMP501]], i8 [[LOAD_1_100425]], i32 1
; CHECK-NEXT:    [[TMP503:%.*]] = insertelement <4 x i8> [[TMP502]], i8 [[LOAD_2_100426]], i32 2
; CHECK-NEXT:    [[TMP504:%.*]] = insertelement <4 x i8> [[TMP503]], i8 [[LOAD_3_100427]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP504]], ptr [[PTR2_0_100]], align 4
; CHECK-NEXT:    [[PTR_0_101:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 404
; CHECK-NEXT:    [[TMP505:%.*]] = load <4 x i8>, ptr [[PTR_0_101]], align 4
; CHECK-NEXT:    [[LOAD_0_101428:%.*]] = extractelement <4 x i8> [[TMP505]], i32 0
; CHECK-NEXT:    [[LOAD_1_101429:%.*]] = extractelement <4 x i8> [[TMP505]], i32 1
; CHECK-NEXT:    [[LOAD_2_101430:%.*]] = extractelement <4 x i8> [[TMP505]], i32 2
; CHECK-NEXT:    [[LOAD_3_101431:%.*]] = extractelement <4 x i8> [[TMP505]], i32 3
; CHECK-NEXT:    [[PTR2_0_101:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 404
; CHECK-NEXT:    [[TMP506:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_101428]], i32 0
; CHECK-NEXT:    [[TMP507:%.*]] = insertelement <4 x i8> [[TMP506]], i8 [[LOAD_1_101429]], i32 1
; CHECK-NEXT:    [[TMP508:%.*]] = insertelement <4 x i8> [[TMP507]], i8 [[LOAD_2_101430]], i32 2
; CHECK-NEXT:    [[TMP509:%.*]] = insertelement <4 x i8> [[TMP508]], i8 [[LOAD_3_101431]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP509]], ptr [[PTR2_0_101]], align 4
; CHECK-NEXT:    [[PTR_0_102:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 408
; CHECK-NEXT:    [[TMP510:%.*]] = load <4 x i8>, ptr [[PTR_0_102]], align 4
; CHECK-NEXT:    [[LOAD_0_102432:%.*]] = extractelement <4 x i8> [[TMP510]], i32 0
; CHECK-NEXT:    [[LOAD_1_102433:%.*]] = extractelement <4 x i8> [[TMP510]], i32 1
; CHECK-NEXT:    [[LOAD_2_102434:%.*]] = extractelement <4 x i8> [[TMP510]], i32 2
; CHECK-NEXT:    [[LOAD_3_102435:%.*]] = extractelement <4 x i8> [[TMP510]], i32 3
; CHECK-NEXT:    [[PTR2_0_102:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 408
; CHECK-NEXT:    [[TMP511:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_102432]], i32 0
; CHECK-NEXT:    [[TMP512:%.*]] = insertelement <4 x i8> [[TMP511]], i8 [[LOAD_1_102433]], i32 1
; CHECK-NEXT:    [[TMP513:%.*]] = insertelement <4 x i8> [[TMP512]], i8 [[LOAD_2_102434]], i32 2
; CHECK-NEXT:    [[TMP514:%.*]] = insertelement <4 x i8> [[TMP513]], i8 [[LOAD_3_102435]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP514]], ptr [[PTR2_0_102]], align 4
; CHECK-NEXT:    [[PTR_0_103:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 412
; CHECK-NEXT:    [[TMP515:%.*]] = load <4 x i8>, ptr [[PTR_0_103]], align 4
; CHECK-NEXT:    [[LOAD_0_103436:%.*]] = extractelement <4 x i8> [[TMP515]], i32 0
; CHECK-NEXT:    [[LOAD_1_103437:%.*]] = extractelement <4 x i8> [[TMP515]], i32 1
; CHECK-NEXT:    [[LOAD_2_103438:%.*]] = extractelement <4 x i8> [[TMP515]], i32 2
; CHECK-NEXT:    [[LOAD_3_103439:%.*]] = extractelement <4 x i8> [[TMP515]], i32 3
; CHECK-NEXT:    [[PTR2_0_103:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 412
; CHECK-NEXT:    [[TMP516:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_103436]], i32 0
; CHECK-NEXT:    [[TMP517:%.*]] = insertelement <4 x i8> [[TMP516]], i8 [[LOAD_1_103437]], i32 1
; CHECK-NEXT:    [[TMP518:%.*]] = insertelement <4 x i8> [[TMP517]], i8 [[LOAD_2_103438]], i32 2
; CHECK-NEXT:    [[TMP519:%.*]] = insertelement <4 x i8> [[TMP518]], i8 [[LOAD_3_103439]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP519]], ptr [[PTR2_0_103]], align 4
; CHECK-NEXT:    [[PTR_0_104:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 416
; CHECK-NEXT:    [[TMP520:%.*]] = load <4 x i8>, ptr [[PTR_0_104]], align 4
; CHECK-NEXT:    [[LOAD_0_104440:%.*]] = extractelement <4 x i8> [[TMP520]], i32 0
; CHECK-NEXT:    [[LOAD_1_104441:%.*]] = extractelement <4 x i8> [[TMP520]], i32 1
; CHECK-NEXT:    [[LOAD_2_104442:%.*]] = extractelement <4 x i8> [[TMP520]], i32 2
; CHECK-NEXT:    [[LOAD_3_104443:%.*]] = extractelement <4 x i8> [[TMP520]], i32 3
; CHECK-NEXT:    [[PTR2_0_104:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 416
; CHECK-NEXT:    [[TMP521:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_104440]], i32 0
; CHECK-NEXT:    [[TMP522:%.*]] = insertelement <4 x i8> [[TMP521]], i8 [[LOAD_1_104441]], i32 1
; CHECK-NEXT:    [[TMP523:%.*]] = insertelement <4 x i8> [[TMP522]], i8 [[LOAD_2_104442]], i32 2
; CHECK-NEXT:    [[TMP524:%.*]] = insertelement <4 x i8> [[TMP523]], i8 [[LOAD_3_104443]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP524]], ptr [[PTR2_0_104]], align 4
; CHECK-NEXT:    [[PTR_0_105:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 420
; CHECK-NEXT:    [[TMP525:%.*]] = load <4 x i8>, ptr [[PTR_0_105]], align 4
; CHECK-NEXT:    [[LOAD_0_105444:%.*]] = extractelement <4 x i8> [[TMP525]], i32 0
; CHECK-NEXT:    [[LOAD_1_105445:%.*]] = extractelement <4 x i8> [[TMP525]], i32 1
; CHECK-NEXT:    [[LOAD_2_105446:%.*]] = extractelement <4 x i8> [[TMP525]], i32 2
; CHECK-NEXT:    [[LOAD_3_105447:%.*]] = extractelement <4 x i8> [[TMP525]], i32 3
; CHECK-NEXT:    [[PTR2_0_105:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 420
; CHECK-NEXT:    [[TMP526:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_105444]], i32 0
; CHECK-NEXT:    [[TMP527:%.*]] = insertelement <4 x i8> [[TMP526]], i8 [[LOAD_1_105445]], i32 1
; CHECK-NEXT:    [[TMP528:%.*]] = insertelement <4 x i8> [[TMP527]], i8 [[LOAD_2_105446]], i32 2
; CHECK-NEXT:    [[TMP529:%.*]] = insertelement <4 x i8> [[TMP528]], i8 [[LOAD_3_105447]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP529]], ptr [[PTR2_0_105]], align 4
; CHECK-NEXT:    [[PTR_0_106:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 424
; CHECK-NEXT:    [[TMP530:%.*]] = load <4 x i8>, ptr [[PTR_0_106]], align 4
; CHECK-NEXT:    [[LOAD_0_106448:%.*]] = extractelement <4 x i8> [[TMP530]], i32 0
; CHECK-NEXT:    [[LOAD_1_106449:%.*]] = extractelement <4 x i8> [[TMP530]], i32 1
; CHECK-NEXT:    [[LOAD_2_106450:%.*]] = extractelement <4 x i8> [[TMP530]], i32 2
; CHECK-NEXT:    [[LOAD_3_106451:%.*]] = extractelement <4 x i8> [[TMP530]], i32 3
; CHECK-NEXT:    [[PTR2_0_106:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 424
; CHECK-NEXT:    [[TMP531:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_106448]], i32 0
; CHECK-NEXT:    [[TMP532:%.*]] = insertelement <4 x i8> [[TMP531]], i8 [[LOAD_1_106449]], i32 1
; CHECK-NEXT:    [[TMP533:%.*]] = insertelement <4 x i8> [[TMP532]], i8 [[LOAD_2_106450]], i32 2
; CHECK-NEXT:    [[TMP534:%.*]] = insertelement <4 x i8> [[TMP533]], i8 [[LOAD_3_106451]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP534]], ptr [[PTR2_0_106]], align 4
; CHECK-NEXT:    [[PTR_0_107:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 428
; CHECK-NEXT:    [[TMP535:%.*]] = load <4 x i8>, ptr [[PTR_0_107]], align 4
; CHECK-NEXT:    [[LOAD_0_107452:%.*]] = extractelement <4 x i8> [[TMP535]], i32 0
; CHECK-NEXT:    [[LOAD_1_107453:%.*]] = extractelement <4 x i8> [[TMP535]], i32 1
; CHECK-NEXT:    [[LOAD_2_107454:%.*]] = extractelement <4 x i8> [[TMP535]], i32 2
; CHECK-NEXT:    [[LOAD_3_107455:%.*]] = extractelement <4 x i8> [[TMP535]], i32 3
; CHECK-NEXT:    [[PTR2_0_107:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 428
; CHECK-NEXT:    [[TMP536:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_107452]], i32 0
; CHECK-NEXT:    [[TMP537:%.*]] = insertelement <4 x i8> [[TMP536]], i8 [[LOAD_1_107453]], i32 1
; CHECK-NEXT:    [[TMP538:%.*]] = insertelement <4 x i8> [[TMP537]], i8 [[LOAD_2_107454]], i32 2
; CHECK-NEXT:    [[TMP539:%.*]] = insertelement <4 x i8> [[TMP538]], i8 [[LOAD_3_107455]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP539]], ptr [[PTR2_0_107]], align 4
; CHECK-NEXT:    [[PTR_0_108:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 432
; CHECK-NEXT:    [[TMP540:%.*]] = load <4 x i8>, ptr [[PTR_0_108]], align 4
; CHECK-NEXT:    [[LOAD_0_108456:%.*]] = extractelement <4 x i8> [[TMP540]], i32 0
; CHECK-NEXT:    [[LOAD_1_108457:%.*]] = extractelement <4 x i8> [[TMP540]], i32 1
; CHECK-NEXT:    [[LOAD_2_108458:%.*]] = extractelement <4 x i8> [[TMP540]], i32 2
; CHECK-NEXT:    [[LOAD_3_108459:%.*]] = extractelement <4 x i8> [[TMP540]], i32 3
; CHECK-NEXT:    [[PTR2_0_108:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 432
; CHECK-NEXT:    [[TMP541:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_108456]], i32 0
; CHECK-NEXT:    [[TMP542:%.*]] = insertelement <4 x i8> [[TMP541]], i8 [[LOAD_1_108457]], i32 1
; CHECK-NEXT:    [[TMP543:%.*]] = insertelement <4 x i8> [[TMP542]], i8 [[LOAD_2_108458]], i32 2
; CHECK-NEXT:    [[TMP544:%.*]] = insertelement <4 x i8> [[TMP543]], i8 [[LOAD_3_108459]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP544]], ptr [[PTR2_0_108]], align 4
; CHECK-NEXT:    [[PTR_0_109:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 436
; CHECK-NEXT:    [[TMP545:%.*]] = load <4 x i8>, ptr [[PTR_0_109]], align 4
; CHECK-NEXT:    [[LOAD_0_109460:%.*]] = extractelement <4 x i8> [[TMP545]], i32 0
; CHECK-NEXT:    [[LOAD_1_109461:%.*]] = extractelement <4 x i8> [[TMP545]], i32 1
; CHECK-NEXT:    [[LOAD_2_109462:%.*]] = extractelement <4 x i8> [[TMP545]], i32 2
; CHECK-NEXT:    [[LOAD_3_109463:%.*]] = extractelement <4 x i8> [[TMP545]], i32 3
; CHECK-NEXT:    [[PTR2_0_109:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 436
; CHECK-NEXT:    [[TMP546:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_109460]], i32 0
; CHECK-NEXT:    [[TMP547:%.*]] = insertelement <4 x i8> [[TMP546]], i8 [[LOAD_1_109461]], i32 1
; CHECK-NEXT:    [[TMP548:%.*]] = insertelement <4 x i8> [[TMP547]], i8 [[LOAD_2_109462]], i32 2
; CHECK-NEXT:    [[TMP549:%.*]] = insertelement <4 x i8> [[TMP548]], i8 [[LOAD_3_109463]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP549]], ptr [[PTR2_0_109]], align 4
; CHECK-NEXT:    [[PTR_0_110:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 440
; CHECK-NEXT:    [[TMP550:%.*]] = load <4 x i8>, ptr [[PTR_0_110]], align 4
; CHECK-NEXT:    [[LOAD_0_110464:%.*]] = extractelement <4 x i8> [[TMP550]], i32 0
; CHECK-NEXT:    [[LOAD_1_110465:%.*]] = extractelement <4 x i8> [[TMP550]], i32 1
; CHECK-NEXT:    [[LOAD_2_110466:%.*]] = extractelement <4 x i8> [[TMP550]], i32 2
; CHECK-NEXT:    [[LOAD_3_110467:%.*]] = extractelement <4 x i8> [[TMP550]], i32 3
; CHECK-NEXT:    [[PTR2_0_110:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 440
; CHECK-NEXT:    [[TMP551:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_110464]], i32 0
; CHECK-NEXT:    [[TMP552:%.*]] = insertelement <4 x i8> [[TMP551]], i8 [[LOAD_1_110465]], i32 1
; CHECK-NEXT:    [[TMP553:%.*]] = insertelement <4 x i8> [[TMP552]], i8 [[LOAD_2_110466]], i32 2
; CHECK-NEXT:    [[TMP554:%.*]] = insertelement <4 x i8> [[TMP553]], i8 [[LOAD_3_110467]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP554]], ptr [[PTR2_0_110]], align 4
; CHECK-NEXT:    [[PTR_0_111:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 444
; CHECK-NEXT:    [[TMP555:%.*]] = load <4 x i8>, ptr [[PTR_0_111]], align 4
; CHECK-NEXT:    [[LOAD_0_111468:%.*]] = extractelement <4 x i8> [[TMP555]], i32 0
; CHECK-NEXT:    [[LOAD_1_111469:%.*]] = extractelement <4 x i8> [[TMP555]], i32 1
; CHECK-NEXT:    [[LOAD_2_111470:%.*]] = extractelement <4 x i8> [[TMP555]], i32 2
; CHECK-NEXT:    [[LOAD_3_111471:%.*]] = extractelement <4 x i8> [[TMP555]], i32 3
; CHECK-NEXT:    [[PTR2_0_111:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 444
; CHECK-NEXT:    [[TMP556:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_111468]], i32 0
; CHECK-NEXT:    [[TMP557:%.*]] = insertelement <4 x i8> [[TMP556]], i8 [[LOAD_1_111469]], i32 1
; CHECK-NEXT:    [[TMP558:%.*]] = insertelement <4 x i8> [[TMP557]], i8 [[LOAD_2_111470]], i32 2
; CHECK-NEXT:    [[TMP559:%.*]] = insertelement <4 x i8> [[TMP558]], i8 [[LOAD_3_111471]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP559]], ptr [[PTR2_0_111]], align 4
; CHECK-NEXT:    [[PTR_0_112:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 448
; CHECK-NEXT:    [[TMP560:%.*]] = load <4 x i8>, ptr [[PTR_0_112]], align 4
; CHECK-NEXT:    [[LOAD_0_112472:%.*]] = extractelement <4 x i8> [[TMP560]], i32 0
; CHECK-NEXT:    [[LOAD_1_112473:%.*]] = extractelement <4 x i8> [[TMP560]], i32 1
; CHECK-NEXT:    [[LOAD_2_112474:%.*]] = extractelement <4 x i8> [[TMP560]], i32 2
; CHECK-NEXT:    [[LOAD_3_112475:%.*]] = extractelement <4 x i8> [[TMP560]], i32 3
; CHECK-NEXT:    [[PTR2_0_112:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 448
; CHECK-NEXT:    [[TMP561:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_112472]], i32 0
; CHECK-NEXT:    [[TMP562:%.*]] = insertelement <4 x i8> [[TMP561]], i8 [[LOAD_1_112473]], i32 1
; CHECK-NEXT:    [[TMP563:%.*]] = insertelement <4 x i8> [[TMP562]], i8 [[LOAD_2_112474]], i32 2
; CHECK-NEXT:    [[TMP564:%.*]] = insertelement <4 x i8> [[TMP563]], i8 [[LOAD_3_112475]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP564]], ptr [[PTR2_0_112]], align 4
; CHECK-NEXT:    [[PTR_0_113:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 452
; CHECK-NEXT:    [[TMP565:%.*]] = load <4 x i8>, ptr [[PTR_0_113]], align 4
; CHECK-NEXT:    [[LOAD_0_113476:%.*]] = extractelement <4 x i8> [[TMP565]], i32 0
; CHECK-NEXT:    [[LOAD_1_113477:%.*]] = extractelement <4 x i8> [[TMP565]], i32 1
; CHECK-NEXT:    [[LOAD_2_113478:%.*]] = extractelement <4 x i8> [[TMP565]], i32 2
; CHECK-NEXT:    [[LOAD_3_113479:%.*]] = extractelement <4 x i8> [[TMP565]], i32 3
; CHECK-NEXT:    [[PTR2_0_113:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 452
; CHECK-NEXT:    [[TMP566:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_113476]], i32 0
; CHECK-NEXT:    [[TMP567:%.*]] = insertelement <4 x i8> [[TMP566]], i8 [[LOAD_1_113477]], i32 1
; CHECK-NEXT:    [[TMP568:%.*]] = insertelement <4 x i8> [[TMP567]], i8 [[LOAD_2_113478]], i32 2
; CHECK-NEXT:    [[TMP569:%.*]] = insertelement <4 x i8> [[TMP568]], i8 [[LOAD_3_113479]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP569]], ptr [[PTR2_0_113]], align 4
; CHECK-NEXT:    [[PTR_0_114:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 456
; CHECK-NEXT:    [[TMP570:%.*]] = load <4 x i8>, ptr [[PTR_0_114]], align 4
; CHECK-NEXT:    [[LOAD_0_114480:%.*]] = extractelement <4 x i8> [[TMP570]], i32 0
; CHECK-NEXT:    [[LOAD_1_114481:%.*]] = extractelement <4 x i8> [[TMP570]], i32 1
; CHECK-NEXT:    [[LOAD_2_114482:%.*]] = extractelement <4 x i8> [[TMP570]], i32 2
; CHECK-NEXT:    [[LOAD_3_114483:%.*]] = extractelement <4 x i8> [[TMP570]], i32 3
; CHECK-NEXT:    [[PTR2_0_114:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 456
; CHECK-NEXT:    [[TMP571:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_114480]], i32 0
; CHECK-NEXT:    [[TMP572:%.*]] = insertelement <4 x i8> [[TMP571]], i8 [[LOAD_1_114481]], i32 1
; CHECK-NEXT:    [[TMP573:%.*]] = insertelement <4 x i8> [[TMP572]], i8 [[LOAD_2_114482]], i32 2
; CHECK-NEXT:    [[TMP574:%.*]] = insertelement <4 x i8> [[TMP573]], i8 [[LOAD_3_114483]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP574]], ptr [[PTR2_0_114]], align 4
; CHECK-NEXT:    [[PTR_0_115:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 460
; CHECK-NEXT:    [[TMP575:%.*]] = load <4 x i8>, ptr [[PTR_0_115]], align 4
; CHECK-NEXT:    [[LOAD_0_115484:%.*]] = extractelement <4 x i8> [[TMP575]], i32 0
; CHECK-NEXT:    [[LOAD_1_115485:%.*]] = extractelement <4 x i8> [[TMP575]], i32 1
; CHECK-NEXT:    [[LOAD_2_115486:%.*]] = extractelement <4 x i8> [[TMP575]], i32 2
; CHECK-NEXT:    [[LOAD_3_115487:%.*]] = extractelement <4 x i8> [[TMP575]], i32 3
; CHECK-NEXT:    [[PTR2_0_115:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 460
; CHECK-NEXT:    [[TMP576:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_115484]], i32 0
; CHECK-NEXT:    [[TMP577:%.*]] = insertelement <4 x i8> [[TMP576]], i8 [[LOAD_1_115485]], i32 1
; CHECK-NEXT:    [[TMP578:%.*]] = insertelement <4 x i8> [[TMP577]], i8 [[LOAD_2_115486]], i32 2
; CHECK-NEXT:    [[TMP579:%.*]] = insertelement <4 x i8> [[TMP578]], i8 [[LOAD_3_115487]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP579]], ptr [[PTR2_0_115]], align 4
; CHECK-NEXT:    [[PTR_0_116:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 464
; CHECK-NEXT:    [[TMP580:%.*]] = load <4 x i8>, ptr [[PTR_0_116]], align 4
; CHECK-NEXT:    [[LOAD_0_116488:%.*]] = extractelement <4 x i8> [[TMP580]], i32 0
; CHECK-NEXT:    [[LOAD_1_116489:%.*]] = extractelement <4 x i8> [[TMP580]], i32 1
; CHECK-NEXT:    [[LOAD_2_116490:%.*]] = extractelement <4 x i8> [[TMP580]], i32 2
; CHECK-NEXT:    [[LOAD_3_116491:%.*]] = extractelement <4 x i8> [[TMP580]], i32 3
; CHECK-NEXT:    [[PTR2_0_116:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 464
; CHECK-NEXT:    [[TMP581:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_116488]], i32 0
; CHECK-NEXT:    [[TMP582:%.*]] = insertelement <4 x i8> [[TMP581]], i8 [[LOAD_1_116489]], i32 1
; CHECK-NEXT:    [[TMP583:%.*]] = insertelement <4 x i8> [[TMP582]], i8 [[LOAD_2_116490]], i32 2
; CHECK-NEXT:    [[TMP584:%.*]] = insertelement <4 x i8> [[TMP583]], i8 [[LOAD_3_116491]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP584]], ptr [[PTR2_0_116]], align 4
; CHECK-NEXT:    [[PTR_0_117:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 468
; CHECK-NEXT:    [[TMP585:%.*]] = load <4 x i8>, ptr [[PTR_0_117]], align 4
; CHECK-NEXT:    [[LOAD_0_117492:%.*]] = extractelement <4 x i8> [[TMP585]], i32 0
; CHECK-NEXT:    [[LOAD_1_117493:%.*]] = extractelement <4 x i8> [[TMP585]], i32 1
; CHECK-NEXT:    [[LOAD_2_117494:%.*]] = extractelement <4 x i8> [[TMP585]], i32 2
; CHECK-NEXT:    [[LOAD_3_117495:%.*]] = extractelement <4 x i8> [[TMP585]], i32 3
; CHECK-NEXT:    [[PTR2_0_117:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 468
; CHECK-NEXT:    [[TMP586:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_117492]], i32 0
; CHECK-NEXT:    [[TMP587:%.*]] = insertelement <4 x i8> [[TMP586]], i8 [[LOAD_1_117493]], i32 1
; CHECK-NEXT:    [[TMP588:%.*]] = insertelement <4 x i8> [[TMP587]], i8 [[LOAD_2_117494]], i32 2
; CHECK-NEXT:    [[TMP589:%.*]] = insertelement <4 x i8> [[TMP588]], i8 [[LOAD_3_117495]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP589]], ptr [[PTR2_0_117]], align 4
; CHECK-NEXT:    [[PTR_0_118:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 472
; CHECK-NEXT:    [[TMP590:%.*]] = load <4 x i8>, ptr [[PTR_0_118]], align 4
; CHECK-NEXT:    [[LOAD_0_118496:%.*]] = extractelement <4 x i8> [[TMP590]], i32 0
; CHECK-NEXT:    [[LOAD_1_118497:%.*]] = extractelement <4 x i8> [[TMP590]], i32 1
; CHECK-NEXT:    [[LOAD_2_118498:%.*]] = extractelement <4 x i8> [[TMP590]], i32 2
; CHECK-NEXT:    [[LOAD_3_118499:%.*]] = extractelement <4 x i8> [[TMP590]], i32 3
; CHECK-NEXT:    [[PTR2_0_118:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 472
; CHECK-NEXT:    [[TMP591:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_118496]], i32 0
; CHECK-NEXT:    [[TMP592:%.*]] = insertelement <4 x i8> [[TMP591]], i8 [[LOAD_1_118497]], i32 1
; CHECK-NEXT:    [[TMP593:%.*]] = insertelement <4 x i8> [[TMP592]], i8 [[LOAD_2_118498]], i32 2
; CHECK-NEXT:    [[TMP594:%.*]] = insertelement <4 x i8> [[TMP593]], i8 [[LOAD_3_118499]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP594]], ptr [[PTR2_0_118]], align 4
; CHECK-NEXT:    [[PTR_0_119:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 476
; CHECK-NEXT:    [[TMP595:%.*]] = load <4 x i8>, ptr [[PTR_0_119]], align 4
; CHECK-NEXT:    [[LOAD_0_119500:%.*]] = extractelement <4 x i8> [[TMP595]], i32 0
; CHECK-NEXT:    [[LOAD_1_119501:%.*]] = extractelement <4 x i8> [[TMP595]], i32 1
; CHECK-NEXT:    [[LOAD_2_119502:%.*]] = extractelement <4 x i8> [[TMP595]], i32 2
; CHECK-NEXT:    [[LOAD_3_119503:%.*]] = extractelement <4 x i8> [[TMP595]], i32 3
; CHECK-NEXT:    [[PTR2_0_119:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 476
; CHECK-NEXT:    [[TMP596:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_119500]], i32 0
; CHECK-NEXT:    [[TMP597:%.*]] = insertelement <4 x i8> [[TMP596]], i8 [[LOAD_1_119501]], i32 1
; CHECK-NEXT:    [[TMP598:%.*]] = insertelement <4 x i8> [[TMP597]], i8 [[LOAD_2_119502]], i32 2
; CHECK-NEXT:    [[TMP599:%.*]] = insertelement <4 x i8> [[TMP598]], i8 [[LOAD_3_119503]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP599]], ptr [[PTR2_0_119]], align 4
; CHECK-NEXT:    [[PTR_0_120:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 480
; CHECK-NEXT:    [[TMP600:%.*]] = load <4 x i8>, ptr [[PTR_0_120]], align 4
; CHECK-NEXT:    [[LOAD_0_120504:%.*]] = extractelement <4 x i8> [[TMP600]], i32 0
; CHECK-NEXT:    [[LOAD_1_120505:%.*]] = extractelement <4 x i8> [[TMP600]], i32 1
; CHECK-NEXT:    [[LOAD_2_120506:%.*]] = extractelement <4 x i8> [[TMP600]], i32 2
; CHECK-NEXT:    [[LOAD_3_120507:%.*]] = extractelement <4 x i8> [[TMP600]], i32 3
; CHECK-NEXT:    [[PTR2_0_120:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 480
; CHECK-NEXT:    [[TMP601:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_120504]], i32 0
; CHECK-NEXT:    [[TMP602:%.*]] = insertelement <4 x i8> [[TMP601]], i8 [[LOAD_1_120505]], i32 1
; CHECK-NEXT:    [[TMP603:%.*]] = insertelement <4 x i8> [[TMP602]], i8 [[LOAD_2_120506]], i32 2
; CHECK-NEXT:    [[TMP604:%.*]] = insertelement <4 x i8> [[TMP603]], i8 [[LOAD_3_120507]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP604]], ptr [[PTR2_0_120]], align 4
; CHECK-NEXT:    [[PTR_0_121:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 484
; CHECK-NEXT:    [[TMP605:%.*]] = load <4 x i8>, ptr [[PTR_0_121]], align 4
; CHECK-NEXT:    [[LOAD_0_121508:%.*]] = extractelement <4 x i8> [[TMP605]], i32 0
; CHECK-NEXT:    [[LOAD_1_121509:%.*]] = extractelement <4 x i8> [[TMP605]], i32 1
; CHECK-NEXT:    [[LOAD_2_121510:%.*]] = extractelement <4 x i8> [[TMP605]], i32 2
; CHECK-NEXT:    [[LOAD_3_121511:%.*]] = extractelement <4 x i8> [[TMP605]], i32 3
; CHECK-NEXT:    [[PTR2_0_121:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 484
; CHECK-NEXT:    [[TMP606:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_121508]], i32 0
; CHECK-NEXT:    [[TMP607:%.*]] = insertelement <4 x i8> [[TMP606]], i8 [[LOAD_1_121509]], i32 1
; CHECK-NEXT:    [[TMP608:%.*]] = insertelement <4 x i8> [[TMP607]], i8 [[LOAD_2_121510]], i32 2
; CHECK-NEXT:    [[TMP609:%.*]] = insertelement <4 x i8> [[TMP608]], i8 [[LOAD_3_121511]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP609]], ptr [[PTR2_0_121]], align 4
; CHECK-NEXT:    [[PTR_0_122:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 488
; CHECK-NEXT:    [[TMP610:%.*]] = load <4 x i8>, ptr [[PTR_0_122]], align 4
; CHECK-NEXT:    [[LOAD_0_122512:%.*]] = extractelement <4 x i8> [[TMP610]], i32 0
; CHECK-NEXT:    [[LOAD_1_122513:%.*]] = extractelement <4 x i8> [[TMP610]], i32 1
; CHECK-NEXT:    [[LOAD_2_122514:%.*]] = extractelement <4 x i8> [[TMP610]], i32 2
; CHECK-NEXT:    [[LOAD_3_122515:%.*]] = extractelement <4 x i8> [[TMP610]], i32 3
; CHECK-NEXT:    [[PTR2_0_122:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 488
; CHECK-NEXT:    [[TMP611:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_122512]], i32 0
; CHECK-NEXT:    [[TMP612:%.*]] = insertelement <4 x i8> [[TMP611]], i8 [[LOAD_1_122513]], i32 1
; CHECK-NEXT:    [[TMP613:%.*]] = insertelement <4 x i8> [[TMP612]], i8 [[LOAD_2_122514]], i32 2
; CHECK-NEXT:    [[TMP614:%.*]] = insertelement <4 x i8> [[TMP613]], i8 [[LOAD_3_122515]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP614]], ptr [[PTR2_0_122]], align 4
; CHECK-NEXT:    [[PTR_0_123:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 492
; CHECK-NEXT:    [[TMP615:%.*]] = load <4 x i8>, ptr [[PTR_0_123]], align 4
; CHECK-NEXT:    [[LOAD_0_123516:%.*]] = extractelement <4 x i8> [[TMP615]], i32 0
; CHECK-NEXT:    [[LOAD_1_123517:%.*]] = extractelement <4 x i8> [[TMP615]], i32 1
; CHECK-NEXT:    [[LOAD_2_123518:%.*]] = extractelement <4 x i8> [[TMP615]], i32 2
; CHECK-NEXT:    [[LOAD_3_123519:%.*]] = extractelement <4 x i8> [[TMP615]], i32 3
; CHECK-NEXT:    [[PTR2_0_123:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 492
; CHECK-NEXT:    [[TMP616:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_123516]], i32 0
; CHECK-NEXT:    [[TMP617:%.*]] = insertelement <4 x i8> [[TMP616]], i8 [[LOAD_1_123517]], i32 1
; CHECK-NEXT:    [[TMP618:%.*]] = insertelement <4 x i8> [[TMP617]], i8 [[LOAD_2_123518]], i32 2
; CHECK-NEXT:    [[TMP619:%.*]] = insertelement <4 x i8> [[TMP618]], i8 [[LOAD_3_123519]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP619]], ptr [[PTR2_0_123]], align 4
; CHECK-NEXT:    [[PTR_0_124:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 496
; CHECK-NEXT:    [[TMP620:%.*]] = load <4 x i8>, ptr [[PTR_0_124]], align 4
; CHECK-NEXT:    [[LOAD_0_124520:%.*]] = extractelement <4 x i8> [[TMP620]], i32 0
; CHECK-NEXT:    [[LOAD_1_124521:%.*]] = extractelement <4 x i8> [[TMP620]], i32 1
; CHECK-NEXT:    [[LOAD_2_124522:%.*]] = extractelement <4 x i8> [[TMP620]], i32 2
; CHECK-NEXT:    [[LOAD_3_124523:%.*]] = extractelement <4 x i8> [[TMP620]], i32 3
; CHECK-NEXT:    [[PTR2_0_124:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 496
; CHECK-NEXT:    [[TMP621:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_124520]], i32 0
; CHECK-NEXT:    [[TMP622:%.*]] = insertelement <4 x i8> [[TMP621]], i8 [[LOAD_1_124521]], i32 1
; CHECK-NEXT:    [[TMP623:%.*]] = insertelement <4 x i8> [[TMP622]], i8 [[LOAD_2_124522]], i32 2
; CHECK-NEXT:    [[TMP624:%.*]] = insertelement <4 x i8> [[TMP623]], i8 [[LOAD_3_124523]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP624]], ptr [[PTR2_0_124]], align 4
; CHECK-NEXT:    [[PTR_0_125:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 500
; CHECK-NEXT:    [[TMP625:%.*]] = load <4 x i8>, ptr [[PTR_0_125]], align 4
; CHECK-NEXT:    [[LOAD_0_125524:%.*]] = extractelement <4 x i8> [[TMP625]], i32 0
; CHECK-NEXT:    [[LOAD_1_125525:%.*]] = extractelement <4 x i8> [[TMP625]], i32 1
; CHECK-NEXT:    [[LOAD_2_125526:%.*]] = extractelement <4 x i8> [[TMP625]], i32 2
; CHECK-NEXT:    [[LOAD_3_125527:%.*]] = extractelement <4 x i8> [[TMP625]], i32 3
; CHECK-NEXT:    [[PTR2_0_125:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 500
; CHECK-NEXT:    [[TMP626:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_125524]], i32 0
; CHECK-NEXT:    [[TMP627:%.*]] = insertelement <4 x i8> [[TMP626]], i8 [[LOAD_1_125525]], i32 1
; CHECK-NEXT:    [[TMP628:%.*]] = insertelement <4 x i8> [[TMP627]], i8 [[LOAD_2_125526]], i32 2
; CHECK-NEXT:    [[TMP629:%.*]] = insertelement <4 x i8> [[TMP628]], i8 [[LOAD_3_125527]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP629]], ptr [[PTR2_0_125]], align 4
; CHECK-NEXT:    [[PTR_0_126:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 504
; CHECK-NEXT:    [[TMP630:%.*]] = load <4 x i8>, ptr [[PTR_0_126]], align 4
; CHECK-NEXT:    [[LOAD_0_126528:%.*]] = extractelement <4 x i8> [[TMP630]], i32 0
; CHECK-NEXT:    [[LOAD_1_126529:%.*]] = extractelement <4 x i8> [[TMP630]], i32 1
; CHECK-NEXT:    [[LOAD_2_126530:%.*]] = extractelement <4 x i8> [[TMP630]], i32 2
; CHECK-NEXT:    [[LOAD_3_126531:%.*]] = extractelement <4 x i8> [[TMP630]], i32 3
; CHECK-NEXT:    [[PTR2_0_126:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 504
; CHECK-NEXT:    [[TMP631:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_126528]], i32 0
; CHECK-NEXT:    [[TMP632:%.*]] = insertelement <4 x i8> [[TMP631]], i8 [[LOAD_1_126529]], i32 1
; CHECK-NEXT:    [[TMP633:%.*]] = insertelement <4 x i8> [[TMP632]], i8 [[LOAD_2_126530]], i32 2
; CHECK-NEXT:    [[TMP634:%.*]] = insertelement <4 x i8> [[TMP633]], i8 [[LOAD_3_126531]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP634]], ptr [[PTR2_0_126]], align 4
; CHECK-NEXT:    [[PTR_0_127:%.*]] = getelementptr i8, ptr [[GLOBAL_BASE_LOADS]], i64 508
; CHECK-NEXT:    [[TMP635:%.*]] = load <4 x i8>, ptr [[PTR_0_127]], align 4
; CHECK-NEXT:    [[LOAD_0_127532:%.*]] = extractelement <4 x i8> [[TMP635]], i32 0
; CHECK-NEXT:    [[LOAD_1_127533:%.*]] = extractelement <4 x i8> [[TMP635]], i32 1
; CHECK-NEXT:    [[LOAD_2_127534:%.*]] = extractelement <4 x i8> [[TMP635]], i32 2
; CHECK-NEXT:    [[LOAD_3_127535:%.*]] = extractelement <4 x i8> [[TMP635]], i32 3
; CHECK-NEXT:    [[PTR2_0_127:%.*]] = getelementptr i8, ptr [[LOCAL_BASE_STORES]], i64 508
; CHECK-NEXT:    [[TMP636:%.*]] = insertelement <4 x i8> poison, i8 [[LOAD_0_127532]], i32 0
; CHECK-NEXT:    [[TMP637:%.*]] = insertelement <4 x i8> [[TMP636]], i8 [[LOAD_1_127533]], i32 1
; CHECK-NEXT:    [[TMP638:%.*]] = insertelement <4 x i8> [[TMP637]], i8 [[LOAD_2_127534]], i32 2
; CHECK-NEXT:    [[TMP639:%.*]] = insertelement <4 x i8> [[TMP638]], i8 [[LOAD_3_127535]], i32 3
; CHECK-NEXT:    store <4 x i8> [[TMP639]], ptr [[PTR2_0_127]], align 4
; CHECK-NEXT:    ret void
;
entry:
  ; Create base pointer to a global variable with the inefficient pattern that Alias Analysis cannot easily traverse through.
  %global_base_loads = getelementptr i8, ptr inttoptr (i32 ptrtoint (ptr @global_mem to i32) to ptr), i64 0

  ; Create another pointer for the stores.
  %local_base_stores = alloca <512 x i8>, align 4

  ; 512 interwoven loads and stores in a loop that gets unrolled
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i_next, %loop ]

  %ptr_0 = getelementptr i8, ptr %global_base_loads, i64 %i
  %load_0 = load i8, ptr %ptr_0, align 4
  %ptr2_0 = getelementptr i8, ptr %local_base_stores, i64 %i
  store i8 %load_0, ptr %ptr2_0, align 4

  %i_1 = add i64 %i, 1

  %ptr_1 = getelementptr i8, ptr %global_base_loads, i64 %i_1
  %load_1 = load i8, ptr %ptr_1, align 1
  %ptr2_1 = getelementptr i8, ptr %local_base_stores, i64 %i_1
  store i8 %load_1, ptr %ptr2_1, align 1

  %i_2 = add i64 %i, 2

  %ptr_2 = getelementptr i8, ptr %global_base_loads, i64 %i_2
  %load_2 = load i8, ptr %ptr_2, align 2
  %ptr2_2 = getelementptr i8, ptr %local_base_stores, i64 %i_2
  store i8 %load_2, ptr %ptr2_2, align 2

  %i_3 = add i64 %i, 3

  %ptr_3 = getelementptr i8, ptr %global_base_loads, i64 %i_3
  %load_3 = load i8, ptr %ptr_3, align 1
  %ptr2_3 = getelementptr i8, ptr %local_base_stores, i64 %i_3
  store i8 %load_3, ptr %ptr2_3, align 1

  %i_next = add i64 %i, 4
  %cmp = icmp ult i64 %i_next, 512
  br i1 %cmp, label %loop, label %done

done:
  ret void
}
