; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S < %s -passes=load-store-vectorizer | FileCheck %s
; RUN: opt -S < %s -passes='function(load-store-vectorizer)' | FileCheck %s

target datalayout = "e-p270:32:32"

; Reorder succeeds.
define i32 @reorder_success(ptr noundef dereferenceable(8) align 8 %a) {
; CHECK-LABEL: define i32 @reorder_success(
; CHECK-SAME: ptr noundef align 8 dereferenceable(8) [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr i32, ptr [[A]], i64 0
; CHECK-NEXT:    [[VEC:%.*]] = load <2 x i32>, ptr [[PTR0]], align 8
; CHECK-NEXT:    [[LOAD01:%.*]] = extractelement <2 x i32> [[VEC]], i32 0
; CHECK-NEXT:    [[LOAD12:%.*]] = extractelement <2 x i32> [[VEC]], i32 1
; CHECK-NEXT:    [[LOAD1_FR:%.*]] = freeze i32 [[LOAD12]]
; CHECK-NEXT:    [[LOAD0_FR:%.*]] = freeze i32 [[LOAD01]]
; CHECK-NEXT:    [[R:%.*]] = add i32 [[LOAD0_FR]], [[LOAD1_FR]]
; CHECK-NEXT:    ret i32 [[R]]
;
entry:
  %ptr1 = getelementptr i32, ptr %a, i64 1
  %load1 = load i32, ptr %ptr1, align 4
  %load1.fr = freeze i32 %load1
  %ptr0 = getelementptr i32, ptr %a, i64 0
  %load0 = load i32, ptr %ptr0, align 8
  %load0.fr = freeze i32 %load0
  %r = add i32 %load0.fr, %load1.fr
  ret i32 %r
}

; Dominating operand.
define i32 @reorder_cross_bb_operand(ptr noundef dereferenceable(8) align 8 %a) {
; CHECK-LABEL: define i32 @reorder_cross_bb_operand(
; CHECK-SAME: ptr noundef align 8 dereferenceable(8) [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[BASE:%.*]] = getelementptr i32, ptr [[A]], i64 0
; CHECK-NEXT:    br label %[[BB:.*]]
; CHECK:       [[BB]]:
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr i32, ptr [[BASE]], i64 0
; CHECK-NEXT:    [[VEC:%.*]] = load <2 x i32>, ptr [[PTR0]], align 8
; CHECK-NEXT:    [[LOAD01:%.*]] = extractelement <2 x i32> [[VEC]], i32 0
; CHECK-NEXT:    [[LOAD12:%.*]] = extractelement <2 x i32> [[VEC]], i32 1
; CHECK-NEXT:    [[LOAD1_FR:%.*]] = freeze i32 [[LOAD12]]
; CHECK-NEXT:    [[LOAD0_FR:%.*]] = freeze i32 [[LOAD01]]
; CHECK-NEXT:    [[R:%.*]] = add i32 [[LOAD0_FR]], [[LOAD1_FR]]
; CHECK-NEXT:    ret i32 [[R]]
;
entry:
  %base = getelementptr i32, ptr %a, i64 0
  br label %bb
bb:
  %ptr1 = getelementptr i32, ptr %base, i64 1
  %load1 = load i32, ptr %ptr1, align 4
  %load1.fr = freeze i32 %load1
  %ptr0 = getelementptr i32, ptr %base, i64 0
  %load0 = load i32, ptr %ptr0, align 8
  %load0.fr = freeze i32 %load0
  %r = add i32 %load0.fr, %load1.fr
  ret i32 %r
}

; Speculatable call.
define i32 @reorder_speculatable_call(
; CHECK-LABEL: define i32 @reorder_speculatable_call(
; CHECK-SAME: ptr noundef align 8 dereferenceable(8) [[A:%.*]], i64 noundef [[SEED:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[IDX_RAW:%.*]] = call i64 @spec_i64(i64 [[SEED]])
; CHECK-NEXT:    [[IDX_RAW_FR:%.*]] = freeze i64 [[IDX_RAW]]
; CHECK-NEXT:    [[IDX:%.*]] = urem i64 [[IDX_RAW_FR]], 1
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr i32, ptr [[A]], i64 [[IDX]]
; CHECK-NEXT:    [[VEC:%.*]] = load <2 x i32>, ptr [[PTR0]], align 8
; CHECK-NEXT:    [[LOAD01:%.*]] = extractelement <2 x i32> [[VEC]], i32 0
; CHECK-NEXT:    [[LOAD12:%.*]] = extractelement <2 x i32> [[VEC]], i32 1
; CHECK-NEXT:    [[LOAD1_FR:%.*]] = freeze i32 [[LOAD12]]
; CHECK-NEXT:    [[LOAD0_FR:%.*]] = freeze i32 [[LOAD01]]
; CHECK-NEXT:    [[R:%.*]] = add i32 [[LOAD0_FR]], [[LOAD1_FR]]
; CHECK-NEXT:    ret i32 [[R]]
;
  ptr noundef dereferenceable(8) align 8 %a, i64 noundef %seed) {
entry:
  %ptr1 = getelementptr i32, ptr %a, i64 1
  %load1 = load i32, ptr %ptr1, align 4
  %load1.fr = freeze i32 %load1
  %idx.raw = call i64 @spec_i64(i64 %seed)
  %idx.raw.fr = freeze i64 %idx.raw
  %idx = urem i64 %idx.raw.fr, 1
  %ptr0 = getelementptr i32, ptr %a, i64 %idx
  %load0 = load i32, ptr %ptr0, align 8
  %load0.fr = freeze i32 %load0
  %r = add i32 %load0.fr, %load1.fr
  ret i32 %r
}

; Load fallback.
define i32 @load_dependency_fallback(
; CHECK-LABEL: define i32 @load_dependency_fallback(
; CHECK-SAME: ptr noundef align 8 dereferenceable(8) [[A:%.*]], ptr noundef align 8 dereferenceable(8) [[PP:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr [[A]], i64 1
; CHECK-NEXT:    [[BASE:%.*]] = getelementptr i8, ptr [[PTR1]], i64 -4
; CHECK-NEXT:    [[VEC:%.*]] = load <2 x i32>, ptr [[BASE]], align 8
; CHECK-NEXT:    [[LOAD01:%.*]] = extractelement <2 x i32> [[VEC]], i32 0
; CHECK-NEXT:    [[LOAD12:%.*]] = extractelement <2 x i32> [[VEC]], i32 1
; CHECK-NEXT:    [[LOAD1_FR:%.*]] = freeze i32 [[LOAD12]]
; CHECK-NEXT:    [[LOADED:%.*]] = load i64, ptr [[PP]], align 8
; CHECK-NEXT:    [[LOADED_FR:%.*]] = freeze i64 [[LOADED]]
; CHECK-NEXT:    [[LOAD0_FR:%.*]] = freeze i32 [[LOAD01]]
; CHECK-NEXT:    [[LOADED_T:%.*]] = trunc i64 [[LOADED_FR]] to i32
; CHECK-NEXT:    [[T:%.*]] = add i32 [[LOAD0_FR]], [[LOAD1_FR]]
; CHECK-NEXT:    [[R:%.*]] = add i32 [[T]], [[LOADED_T]]
; CHECK-NEXT:    ret i32 [[R]]
;
  ptr noundef dereferenceable(8) align 8 %a,
  ptr noundef dereferenceable(8) align 8 %pp) {
entry:
  %ptr1 = getelementptr i32, ptr %a, i64 1
  %load1 = load i32, ptr %ptr1, align 4
  %load1.fr = freeze i32 %load1
  %loaded = load i64, ptr %pp, align 8
  %loaded.fr = freeze i64 %loaded
  %idx = sub i64 %loaded.fr, %loaded.fr
  %ptr0 = getelementptr i32, ptr %a, i64 %idx
  %load0 = load i32, ptr %ptr0, align 8
  %load0.fr = freeze i32 %load0
  %loaded.t = trunc i64 %loaded.fr to i32
  %t = add i32 %load0.fr, %load1.fr
  %r = add i32 %t, %loaded.t
  ret i32 %r
}

; Offset fallback.
define i32 @offset_fallback(ptr noundef dereferenceable(16) align 16 %a) {
; CHECK-LABEL: define i32 @offset_fallback(
; CHECK-SAME: ptr noundef align 16 dereferenceable(16) [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[PTR3:%.*]] = getelementptr i32, ptr [[A]], i64 3
; CHECK-NEXT:    [[BASE:%.*]] = getelementptr i8, ptr [[PTR3]], i64 -12
; CHECK-NEXT:    [[VEC:%.*]] = load <4 x i32>, ptr [[BASE]], align 16
; CHECK-NEXT:    [[LOAD01:%.*]] = extractelement <4 x i32> [[VEC]], i32 0
; CHECK-NEXT:    [[LOAD12:%.*]] = extractelement <4 x i32> [[VEC]], i32 1
; CHECK-NEXT:    [[LOAD23:%.*]] = extractelement <4 x i32> [[VEC]], i32 2
; CHECK-NEXT:    [[LOAD34:%.*]] = extractelement <4 x i32> [[VEC]], i32 3
; CHECK-NEXT:    [[LOAD3_FR:%.*]] = freeze i32 [[LOAD34]]
; CHECK-NEXT:    [[LOAD0_FR:%.*]] = freeze i32 [[LOAD01]]
; CHECK-NEXT:    [[LOAD1_FR:%.*]] = freeze i32 [[LOAD12]]
; CHECK-NEXT:    [[LOAD2_FR:%.*]] = freeze i32 [[LOAD23]]
; CHECK-NEXT:    [[T0:%.*]] = add i32 [[LOAD0_FR]], [[LOAD1_FR]]
; CHECK-NEXT:    [[T1:%.*]] = add i32 [[T0]], [[LOAD2_FR]]
; CHECK-NEXT:    [[R:%.*]] = add i32 [[T1]], [[LOAD3_FR]]
; CHECK-NEXT:    ret i32 [[R]]
;
entry:
  %ptr3 = getelementptr i32, ptr %a, i64 3
  %load3 = load i32, ptr %ptr3, align 4
  %load3.fr = freeze i32 %load3
  %load3z = zext i32 %load3.fr to i64
  %rem = urem i64 %load3z, 1
  %ptr0 = getelementptr i32, ptr %a, i64 %rem
  %load0 = load i32, ptr %ptr0, align 16
  %load0.fr = freeze i32 %load0
  %ptr1 = getelementptr i32, ptr %a, i64 1
  %load1 = load i32, ptr %ptr1, align 4
  %load1.fr = freeze i32 %load1
  %ptr2 = getelementptr i32, ptr %a, i64 2
  %load2 = load i32, ptr %ptr2, align 8
  %load2.fr = freeze i32 %load2
  %t0 = add i32 %load0.fr, %load1.fr
  %t1 = add i32 %t0, %load2.fr
  %r = add i32 %t1, %load3.fr
  ret i32 %r
}

; Address-space index.
define i32 @addrspace_index(
; CHECK-LABEL: define i32 @addrspace_index(
; CHECK-SAME: ptr addrspace(270) noundef align 8 dereferenceable(8) [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr addrspace(270) [[A]], i32 1
; CHECK-NEXT:    [[BASE:%.*]] = getelementptr i8, ptr addrspace(270) [[PTR1]], i32 -4
; CHECK-NEXT:    [[VEC:%.*]] = load <2 x i32>, ptr addrspace(270) [[BASE]], align 8
; CHECK-NEXT:    [[LOAD01:%.*]] = extractelement <2 x i32> [[VEC]], i32 0
; CHECK-NEXT:    [[LOAD12:%.*]] = extractelement <2 x i32> [[VEC]], i32 1
; CHECK-NEXT:    [[LOAD1_FR:%.*]] = freeze i32 [[LOAD12]]
; CHECK-NEXT:    [[LOAD0_FR:%.*]] = freeze i32 [[LOAD01]]
; CHECK-NEXT:    [[R:%.*]] = add i32 [[LOAD0_FR]], [[LOAD1_FR]]
; CHECK-NEXT:    ret i32 [[R]]
;
  ptr addrspace(270) noundef dereferenceable(8) align 8 %a) {
entry:
  %ptr1 = getelementptr i32, ptr addrspace(270) %a, i32 1
  %load1 = load i32, ptr addrspace(270) %ptr1, align 4
  %load1.fr = freeze i32 %load1
  %rem = urem i32 %load1.fr, 1
  %ptr0 = getelementptr i32, ptr addrspace(270) %a, i32 %rem
  %load0 = load i32, ptr addrspace(270) %ptr0, align 8
  %load0.fr = freeze i32 %load0
  %r = add i32 %load0.fr, %load1.fr
  ret i32 %r
}

; PHI boundary.
define i32 @phi_boundary(ptr noundef dereferenceable(8) align 8 %a,
; CHECK-LABEL: define i32 @phi_boundary(
; CHECK-SAME: ptr noundef align 8 dereferenceable(8) [[A:%.*]], ptr noundef align 8 dereferenceable(8) [[B:%.*]], i1 noundef [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C]], label %[[T:.*]], label %[[F:.*]]
; CHECK:       [[T]]:
; CHECK-NEXT:    br label %[[M:.*]]
; CHECK:       [[F]]:
; CHECK-NEXT:    br label %[[M]]
; CHECK:       [[M]]:
; CHECK-NEXT:    [[P:%.*]] = phi ptr [ [[A]], %[[T]] ], [ [[B]], %[[F]] ]
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr i32, ptr [[P]], i64 0
; CHECK-NEXT:    [[VEC:%.*]] = load <2 x i32>, ptr [[PTR0]], align 8
; CHECK-NEXT:    [[LOAD01:%.*]] = extractelement <2 x i32> [[VEC]], i32 0
; CHECK-NEXT:    [[LOAD12:%.*]] = extractelement <2 x i32> [[VEC]], i32 1
; CHECK-NEXT:    [[LOAD1_FR:%.*]] = freeze i32 [[LOAD12]]
; CHECK-NEXT:    [[LOAD0_FR:%.*]] = freeze i32 [[LOAD01]]
; CHECK-NEXT:    [[R:%.*]] = add i32 [[LOAD0_FR]], [[LOAD1_FR]]
; CHECK-NEXT:    ret i32 [[R]]
;
  ptr noundef dereferenceable(8) align 8 %b,
  i1 noundef %c) {
entry:
  br i1 %c, label %t, label %f
t:
  br label %m
f:
  br label %m
m:
  %p = phi ptr [ %a, %t ], [ %b, %f ]
  %ptr1 = getelementptr i32, ptr %p, i64 1
  %load1 = load i32, ptr %ptr1, align 4
  %load1.fr = freeze i32 %load1
  %ptr0 = getelementptr i32, ptr %p, i64 0
  %load0 = load i32, ptr %ptr0, align 8
  %load0.fr = freeze i32 %load0
  %r = add i32 %load0.fr, %load1.fr
  ret i32 %r
}

; Function Attrs: nounwind speculatable willreturn memory(none)
declare i64 @spec_i64(i64) #0

attributes #0 = { nounwind speculatable willreturn memory(none) }
