; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=slp-vectorizer -slp-threshold=-1000 -mtriple=x86_64-unknown-linux-gnu -S < %s | FileCheck %s

; add nsw X, INT_MIN is converted to sub X, INT_MIN. Negating INT_MIN
; overflows, so the converted lane is no longer nsw and the vector op must
; not be nsw.
define void @add_intmin_converted_to_sub(ptr %p, i32 %x, i32 %y) {
; CHECK-LABEL: @add_intmin_converted_to_sub(
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <2 x i32> poison, i32 [[X:%.*]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <2 x i32> [[TMP1]], i32 [[Y:%.*]], i32 1
; CHECK-NEXT:    [[TMP3:%.*]] = sub nsw <2 x i32> [[TMP2]], <i32 -2147483648, i32 7>
; CHECK-NEXT:    store <2 x i32> [[TMP3]], ptr [[P:%.*]], align 4
; CHECK-NEXT:    ret void
;
  %a = add nsw i32 %x, -2147483648
  %b = sub nsw i32 %y, 7
  store i32 %a, ptr %p, align 4
  %p1 = getelementptr inbounds i32, ptr %p, i64 1
  store i32 %b, ptr %p1, align 4
  ret void
}

; sub nsw X, INT_MIN is converted to add X, INT_MIN. Same reasoning, nsw must
; be dropped.
define void @sub_intmin_converted_to_add(ptr %p, i32 %x, i32 %y) {
; CHECK-LABEL: @sub_intmin_converted_to_add(
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <2 x i32> poison, i32 [[X:%.*]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <2 x i32> [[TMP1]], i32 [[Y:%.*]], i32 1
; CHECK-NEXT:    [[TMP3:%.*]] = add nsw <2 x i32> [[TMP2]], <i32 -2147483648, i32 7>
; CHECK-NEXT:    store <2 x i32> [[TMP3]], ptr [[P:%.*]], align 4
; CHECK-NEXT:    ret void
;
  %a = sub nsw i32 %x, -2147483648
  %b = add nsw i32 %y, 7
  store i32 %a, ptr %p, align 4
  %p1 = getelementptr inbounds i32, ptr %p, i64 1
  store i32 %b, ptr %p1, align 4
  ret void
}

; The negated constant is not INT_MIN, so the conversion preserves nsw.
define void @keep_nsw_non_intmin(ptr %p, i32 %x, i32 %y) {
; CHECK-LABEL: @keep_nsw_non_intmin(
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <2 x i32> poison, i32 [[X:%.*]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <2 x i32> [[TMP1]], i32 [[Y:%.*]], i32 1
; CHECK-NEXT:    [[TMP3:%.*]] = sub nsw <2 x i32> [[TMP2]], <i32 -5, i32 7>
; CHECK-NEXT:    store <2 x i32> [[TMP3]], ptr [[P:%.*]], align 4
; CHECK-NEXT:    ret void
;
  %a = add nsw i32 %x, 5
  %b = sub nsw i32 %y, 7
  store i32 %a, ptr %p, align 4
  %p1 = getelementptr inbounds i32, ptr %p, i64 1
  store i32 %b, ptr %p1, align 4
  ret void
}

; The INT_MIN lane keeps its own opcode (no conversion), so nsw stays valid.
define void @keep_nsw_same_opcode(ptr %p, i32 %x, i32 %y) {
; CHECK-LABEL: @keep_nsw_same_opcode(
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <2 x i32> poison, i32 [[X:%.*]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <2 x i32> [[TMP1]], i32 [[Y:%.*]], i32 1
; CHECK-NEXT:    [[TMP3:%.*]] = add nsw <2 x i32> [[TMP2]], <i32 -2147483648, i32 7>
; CHECK-NEXT:    store <2 x i32> [[TMP3]], ptr [[P:%.*]], align 4
; CHECK-NEXT:    ret void
;
  %a = add nsw i32 %x, -2147483648
  %b = add nsw i32 %y, 7
  store i32 %a, ptr %p, align 4
  %p1 = getelementptr inbounds i32, ptr %p, i64 1
  store i32 %b, ptr %p1, align 4
  ret void
}
