; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=x86_64-unknown -passes=slp-vectorizer -S | FileCheck %s --check-prefixes=CHECK,SSE
; RUN: opt < %s -mtriple=x86_64-unknown -mcpu=slm -passes=slp-vectorizer -S | FileCheck %s --check-prefixes=CHECK,SLM
; RUN: opt < %s -mtriple=x86_64-unknown -mcpu=corei7-avx -passes=slp-vectorizer -S | FileCheck %s --check-prefixes=CHECK,AVX
; RUN: opt < %s -mtriple=x86_64-unknown -mcpu=core-avx2 -passes=slp-vectorizer -S | FileCheck %s --check-prefixes=CHECK,AVX2
; RUN: opt < %s -mtriple=x86_64-unknown -mcpu=knl -passes=slp-vectorizer -S | FileCheck %s --check-prefixes=CHECK,KNL
; RUN: opt < %s -mtriple=x86_64-unknown -mcpu=skx -mattr=-prefer-256-bit -passes=slp-vectorizer -S | FileCheck %s --check-prefixes=CHECK,AVX512
; RUN: opt < %s -mtriple=x86_64-unknown -mcpu=skx -mattr=+prefer-256-bit -passes=slp-vectorizer -S | FileCheck %s --check-prefixes=CHECK,AVX512_256

@a64 = common global [8 x i64] zeroinitializer, align 64
@b64 = common global [8 x i64] zeroinitializer, align 64
@c64 = common global [8 x i64] zeroinitializer, align 64
@a32 = common global [16 x i32] zeroinitializer, align 64
@b32 = common global [16 x i32] zeroinitializer, align 64
@c32 = common global [16 x i32] zeroinitializer, align 64
@a16 = common global [32 x i16] zeroinitializer, align 64
@b16 = common global [32 x i16] zeroinitializer, align 64
@c16 = common global [32 x i16] zeroinitializer, align 64
@a8  = common global [64 x i8] zeroinitializer, align 64
@b8  = common global [64 x i8] zeroinitializer, align 64
@c8  = common global [64 x i8] zeroinitializer, align 64

declare {i64, i1} @llvm.smul.with.overflow.i64(i64, i64)
declare {i32, i1} @llvm.smul.with.overflow.i32(i32, i32)
declare {i16, i1} @llvm.smul.with.overflow.i16(i16, i16)
declare {i8 , i1} @llvm.smul.with.overflow.i8 (i8 , i8 )

define void @mul_v8i64() {
; CHECK-LABEL: @mul_v8i64(
; CHECK-NEXT:    [[A0:%.*]] = load i64, ptr @a64, align 8
; CHECK-NEXT:    [[A1:%.*]] = load i64, ptr getelementptr inbounds ([8 x i64], ptr @a64, i32 0, i64 1), align 8
; CHECK-NEXT:    [[A2:%.*]] = load i64, ptr getelementptr inbounds ([8 x i64], ptr @a64, i32 0, i64 2), align 8
; CHECK-NEXT:    [[A3:%.*]] = load i64, ptr getelementptr inbounds ([8 x i64], ptr @a64, i32 0, i64 3), align 8
; CHECK-NEXT:    [[A4:%.*]] = load i64, ptr getelementptr inbounds ([8 x i64], ptr @a64, i32 0, i64 4), align 8
; CHECK-NEXT:    [[A5:%.*]] = load i64, ptr getelementptr inbounds ([8 x i64], ptr @a64, i32 0, i64 5), align 8
; CHECK-NEXT:    [[A6:%.*]] = load i64, ptr getelementptr inbounds ([8 x i64], ptr @a64, i32 0, i64 6), align 8
; CHECK-NEXT:    [[A7:%.*]] = load i64, ptr getelementptr inbounds ([8 x i64], ptr @a64, i32 0, i64 7), align 8
; CHECK-NEXT:    [[B0:%.*]] = load i64, ptr @b64, align 8
; CHECK-NEXT:    [[B1:%.*]] = load i64, ptr getelementptr inbounds ([8 x i64], ptr @b64, i32 0, i64 1), align 8
; CHECK-NEXT:    [[B2:%.*]] = load i64, ptr getelementptr inbounds ([8 x i64], ptr @b64, i32 0, i64 2), align 8
; CHECK-NEXT:    [[B3:%.*]] = load i64, ptr getelementptr inbounds ([8 x i64], ptr @b64, i32 0, i64 3), align 8
; CHECK-NEXT:    [[B4:%.*]] = load i64, ptr getelementptr inbounds ([8 x i64], ptr @b64, i32 0, i64 4), align 8
; CHECK-NEXT:    [[B5:%.*]] = load i64, ptr getelementptr inbounds ([8 x i64], ptr @b64, i32 0, i64 5), align 8
; CHECK-NEXT:    [[B6:%.*]] = load i64, ptr getelementptr inbounds ([8 x i64], ptr @b64, i32 0, i64 6), align 8
; CHECK-NEXT:    [[B7:%.*]] = load i64, ptr getelementptr inbounds ([8 x i64], ptr @b64, i32 0, i64 7), align 8
; CHECK-NEXT:    [[C0:%.*]] = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 [[A0]], i64 [[B0]])
; CHECK-NEXT:    [[C1:%.*]] = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 [[A1]], i64 [[B1]])
; CHECK-NEXT:    [[C2:%.*]] = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 [[A2]], i64 [[B2]])
; CHECK-NEXT:    [[C3:%.*]] = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 [[A3]], i64 [[B3]])
; CHECK-NEXT:    [[C4:%.*]] = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 [[A4]], i64 [[B4]])
; CHECK-NEXT:    [[C5:%.*]] = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 [[A5]], i64 [[B5]])
; CHECK-NEXT:    [[C6:%.*]] = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 [[A6]], i64 [[B6]])
; CHECK-NEXT:    [[C7:%.*]] = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 [[A7]], i64 [[B7]])
; CHECK-NEXT:    [[R0:%.*]] = extractvalue { i64, i1 } [[C0]], 0
; CHECK-NEXT:    [[R1:%.*]] = extractvalue { i64, i1 } [[C1]], 0
; CHECK-NEXT:    [[R2:%.*]] = extractvalue { i64, i1 } [[C2]], 0
; CHECK-NEXT:    [[R3:%.*]] = extractvalue { i64, i1 } [[C3]], 0
; CHECK-NEXT:    [[R4:%.*]] = extractvalue { i64, i1 } [[C4]], 0
; CHECK-NEXT:    [[R5:%.*]] = extractvalue { i64, i1 } [[C5]], 0
; CHECK-NEXT:    [[R6:%.*]] = extractvalue { i64, i1 } [[C6]], 0
; CHECK-NEXT:    [[R7:%.*]] = extractvalue { i64, i1 } [[C7]], 0
; CHECK-NEXT:    store i64 [[R0]], ptr @c64, align 8
; CHECK-NEXT:    store i64 [[R1]], ptr getelementptr inbounds ([8 x i64], ptr @c64, i32 0, i64 1), align 8
; CHECK-NEXT:    store i64 [[R2]], ptr getelementptr inbounds ([8 x i64], ptr @c64, i32 0, i64 2), align 8
; CHECK-NEXT:    store i64 [[R3]], ptr getelementptr inbounds ([8 x i64], ptr @c64, i32 0, i64 3), align 8
; CHECK-NEXT:    store i64 [[R4]], ptr getelementptr inbounds ([8 x i64], ptr @c64, i32 0, i64 4), align 8
; CHECK-NEXT:    store i64 [[R5]], ptr getelementptr inbounds ([8 x i64], ptr @c64, i32 0, i64 5), align 8
; CHECK-NEXT:    store i64 [[R6]], ptr getelementptr inbounds ([8 x i64], ptr @c64, i32 0, i64 6), align 8
; CHECK-NEXT:    store i64 [[R7]], ptr getelementptr inbounds ([8 x i64], ptr @c64, i32 0, i64 7), align 8
; CHECK-NEXT:    ret void
;
  %a0 = load i64, ptr @a64, align 8
  %a1 = load i64, ptr getelementptr inbounds ([8 x i64], ptr @a64, i32 0, i64 1), align 8
  %a2 = load i64, ptr getelementptr inbounds ([8 x i64], ptr @a64, i32 0, i64 2), align 8
  %a3 = load i64, ptr getelementptr inbounds ([8 x i64], ptr @a64, i32 0, i64 3), align 8
  %a4 = load i64, ptr getelementptr inbounds ([8 x i64], ptr @a64, i32 0, i64 4), align 8
  %a5 = load i64, ptr getelementptr inbounds ([8 x i64], ptr @a64, i32 0, i64 5), align 8
  %a6 = load i64, ptr getelementptr inbounds ([8 x i64], ptr @a64, i32 0, i64 6), align 8
  %a7 = load i64, ptr getelementptr inbounds ([8 x i64], ptr @a64, i32 0, i64 7), align 8
  %b0 = load i64, ptr @b64, align 8
  %b1 = load i64, ptr getelementptr inbounds ([8 x i64], ptr @b64, i32 0, i64 1), align 8
  %b2 = load i64, ptr getelementptr inbounds ([8 x i64], ptr @b64, i32 0, i64 2), align 8
  %b3 = load i64, ptr getelementptr inbounds ([8 x i64], ptr @b64, i32 0, i64 3), align 8
  %b4 = load i64, ptr getelementptr inbounds ([8 x i64], ptr @b64, i32 0, i64 4), align 8
  %b5 = load i64, ptr getelementptr inbounds ([8 x i64], ptr @b64, i32 0, i64 5), align 8
  %b6 = load i64, ptr getelementptr inbounds ([8 x i64], ptr @b64, i32 0, i64 6), align 8
  %b7 = load i64, ptr getelementptr inbounds ([8 x i64], ptr @b64, i32 0, i64 7), align 8
  %c0 = call {i64, i1} @llvm.smul.with.overflow.i64(i64 %a0, i64 %b0)
  %c1 = call {i64, i1} @llvm.smul.with.overflow.i64(i64 %a1, i64 %b1)
  %c2 = call {i64, i1} @llvm.smul.with.overflow.i64(i64 %a2, i64 %b2)
  %c3 = call {i64, i1} @llvm.smul.with.overflow.i64(i64 %a3, i64 %b3)
  %c4 = call {i64, i1} @llvm.smul.with.overflow.i64(i64 %a4, i64 %b4)
  %c5 = call {i64, i1} @llvm.smul.with.overflow.i64(i64 %a5, i64 %b5)
  %c6 = call {i64, i1} @llvm.smul.with.overflow.i64(i64 %a6, i64 %b6)
  %c7 = call {i64, i1} @llvm.smul.with.overflow.i64(i64 %a7, i64 %b7)
  %r0 = extractvalue {i64, i1} %c0, 0
  %r1 = extractvalue {i64, i1} %c1, 0
  %r2 = extractvalue {i64, i1} %c2, 0
  %r3 = extractvalue {i64, i1} %c3, 0
  %r4 = extractvalue {i64, i1} %c4, 0
  %r5 = extractvalue {i64, i1} %c5, 0
  %r6 = extractvalue {i64, i1} %c6, 0
  %r7 = extractvalue {i64, i1} %c7, 0
  store i64 %r0, ptr @c64, align 8
  store i64 %r1, ptr getelementptr inbounds ([8 x i64], ptr @c64, i32 0, i64 1), align 8
  store i64 %r2, ptr getelementptr inbounds ([8 x i64], ptr @c64, i32 0, i64 2), align 8
  store i64 %r3, ptr getelementptr inbounds ([8 x i64], ptr @c64, i32 0, i64 3), align 8
  store i64 %r4, ptr getelementptr inbounds ([8 x i64], ptr @c64, i32 0, i64 4), align 8
  store i64 %r5, ptr getelementptr inbounds ([8 x i64], ptr @c64, i32 0, i64 5), align 8
  store i64 %r6, ptr getelementptr inbounds ([8 x i64], ptr @c64, i32 0, i64 6), align 8
  store i64 %r7, ptr getelementptr inbounds ([8 x i64], ptr @c64, i32 0, i64 7), align 8
  ret void
}

define void @mul_v16i32() {
; SSE-LABEL: @mul_v16i32(
; SSE-NEXT:    [[A0:%.*]] = load i32, ptr @a32, align 4
; SSE-NEXT:    [[A1:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 1), align 4
; SSE-NEXT:    [[A2:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 2), align 4
; SSE-NEXT:    [[A3:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 3), align 4
; SSE-NEXT:    [[A4:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 4), align 4
; SSE-NEXT:    [[A5:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 5), align 4
; SSE-NEXT:    [[A6:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 6), align 4
; SSE-NEXT:    [[A7:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 7), align 4
; SSE-NEXT:    [[A8:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 8), align 4
; SSE-NEXT:    [[A9:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 9), align 4
; SSE-NEXT:    [[A10:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 10), align 4
; SSE-NEXT:    [[A11:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 11), align 4
; SSE-NEXT:    [[A12:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 12), align 4
; SSE-NEXT:    [[A13:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 13), align 4
; SSE-NEXT:    [[A14:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 14), align 4
; SSE-NEXT:    [[A15:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 15), align 4
; SSE-NEXT:    [[B0:%.*]] = load i32, ptr @b32, align 4
; SSE-NEXT:    [[B1:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 1), align 4
; SSE-NEXT:    [[B2:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 2), align 4
; SSE-NEXT:    [[B3:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 3), align 4
; SSE-NEXT:    [[B4:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 4), align 4
; SSE-NEXT:    [[B5:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 5), align 4
; SSE-NEXT:    [[B6:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 6), align 4
; SSE-NEXT:    [[B7:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 7), align 4
; SSE-NEXT:    [[B8:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 8), align 4
; SSE-NEXT:    [[B9:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 9), align 4
; SSE-NEXT:    [[B10:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 10), align 4
; SSE-NEXT:    [[B11:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 11), align 4
; SSE-NEXT:    [[B12:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 12), align 4
; SSE-NEXT:    [[B13:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 13), align 4
; SSE-NEXT:    [[B14:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 14), align 4
; SSE-NEXT:    [[B15:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 15), align 4
; SSE-NEXT:    [[C0:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A0]], i32 [[B0]])
; SSE-NEXT:    [[C1:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A1]], i32 [[B1]])
; SSE-NEXT:    [[C2:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A2]], i32 [[B2]])
; SSE-NEXT:    [[C3:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A3]], i32 [[B3]])
; SSE-NEXT:    [[C4:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A4]], i32 [[B4]])
; SSE-NEXT:    [[C5:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A5]], i32 [[B5]])
; SSE-NEXT:    [[C6:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A6]], i32 [[B6]])
; SSE-NEXT:    [[C7:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A7]], i32 [[B7]])
; SSE-NEXT:    [[C8:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A8]], i32 [[B8]])
; SSE-NEXT:    [[C9:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A9]], i32 [[B9]])
; SSE-NEXT:    [[C10:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A10]], i32 [[B10]])
; SSE-NEXT:    [[C11:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A11]], i32 [[B11]])
; SSE-NEXT:    [[C12:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A12]], i32 [[B12]])
; SSE-NEXT:    [[C13:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A13]], i32 [[B13]])
; SSE-NEXT:    [[C14:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A14]], i32 [[B14]])
; SSE-NEXT:    [[C15:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A15]], i32 [[B15]])
; SSE-NEXT:    [[R0:%.*]] = extractvalue { i32, i1 } [[C0]], 0
; SSE-NEXT:    [[R1:%.*]] = extractvalue { i32, i1 } [[C1]], 0
; SSE-NEXT:    [[R2:%.*]] = extractvalue { i32, i1 } [[C2]], 0
; SSE-NEXT:    [[R3:%.*]] = extractvalue { i32, i1 } [[C3]], 0
; SSE-NEXT:    [[R4:%.*]] = extractvalue { i32, i1 } [[C4]], 0
; SSE-NEXT:    [[R5:%.*]] = extractvalue { i32, i1 } [[C5]], 0
; SSE-NEXT:    [[R6:%.*]] = extractvalue { i32, i1 } [[C6]], 0
; SSE-NEXT:    [[R7:%.*]] = extractvalue { i32, i1 } [[C7]], 0
; SSE-NEXT:    [[R8:%.*]] = extractvalue { i32, i1 } [[C8]], 0
; SSE-NEXT:    [[R9:%.*]] = extractvalue { i32, i1 } [[C9]], 0
; SSE-NEXT:    [[R10:%.*]] = extractvalue { i32, i1 } [[C10]], 0
; SSE-NEXT:    [[R11:%.*]] = extractvalue { i32, i1 } [[C11]], 0
; SSE-NEXT:    [[R12:%.*]] = extractvalue { i32, i1 } [[C12]], 0
; SSE-NEXT:    [[R13:%.*]] = extractvalue { i32, i1 } [[C13]], 0
; SSE-NEXT:    [[R14:%.*]] = extractvalue { i32, i1 } [[C14]], 0
; SSE-NEXT:    [[R15:%.*]] = extractvalue { i32, i1 } [[C15]], 0
; SSE-NEXT:    store i32 [[R0]], ptr @c32, align 4
; SSE-NEXT:    store i32 [[R1]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 1), align 4
; SSE-NEXT:    store i32 [[R2]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 2), align 4
; SSE-NEXT:    store i32 [[R3]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 3), align 4
; SSE-NEXT:    store i32 [[R4]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 4), align 4
; SSE-NEXT:    store i32 [[R5]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 5), align 4
; SSE-NEXT:    store i32 [[R6]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 6), align 4
; SSE-NEXT:    store i32 [[R7]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 7), align 4
; SSE-NEXT:    store i32 [[R8]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 8), align 4
; SSE-NEXT:    store i32 [[R9]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 9), align 4
; SSE-NEXT:    store i32 [[R10]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 10), align 4
; SSE-NEXT:    store i32 [[R11]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 11), align 4
; SSE-NEXT:    store i32 [[R12]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 12), align 4
; SSE-NEXT:    store i32 [[R13]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 13), align 4
; SSE-NEXT:    store i32 [[R14]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 14), align 4
; SSE-NEXT:    store i32 [[R15]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 15), align 4
; SSE-NEXT:    ret void
;
; SLM-LABEL: @mul_v16i32(
; SLM-NEXT:    [[A0:%.*]] = load i32, ptr @a32, align 4
; SLM-NEXT:    [[A1:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 1), align 4
; SLM-NEXT:    [[A2:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 2), align 4
; SLM-NEXT:    [[A3:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 3), align 4
; SLM-NEXT:    [[A4:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 4), align 4
; SLM-NEXT:    [[A5:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 5), align 4
; SLM-NEXT:    [[A6:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 6), align 4
; SLM-NEXT:    [[A7:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 7), align 4
; SLM-NEXT:    [[A8:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 8), align 4
; SLM-NEXT:    [[A9:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 9), align 4
; SLM-NEXT:    [[A10:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 10), align 4
; SLM-NEXT:    [[A11:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 11), align 4
; SLM-NEXT:    [[A12:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 12), align 4
; SLM-NEXT:    [[A13:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 13), align 4
; SLM-NEXT:    [[A14:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 14), align 4
; SLM-NEXT:    [[A15:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 15), align 4
; SLM-NEXT:    [[B0:%.*]] = load i32, ptr @b32, align 4
; SLM-NEXT:    [[B1:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 1), align 4
; SLM-NEXT:    [[B2:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 2), align 4
; SLM-NEXT:    [[B3:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 3), align 4
; SLM-NEXT:    [[B4:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 4), align 4
; SLM-NEXT:    [[B5:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 5), align 4
; SLM-NEXT:    [[B6:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 6), align 4
; SLM-NEXT:    [[B7:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 7), align 4
; SLM-NEXT:    [[B8:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 8), align 4
; SLM-NEXT:    [[B9:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 9), align 4
; SLM-NEXT:    [[B10:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 10), align 4
; SLM-NEXT:    [[B11:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 11), align 4
; SLM-NEXT:    [[B12:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 12), align 4
; SLM-NEXT:    [[B13:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 13), align 4
; SLM-NEXT:    [[B14:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 14), align 4
; SLM-NEXT:    [[B15:%.*]] = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 15), align 4
; SLM-NEXT:    [[C0:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A0]], i32 [[B0]])
; SLM-NEXT:    [[C1:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A1]], i32 [[B1]])
; SLM-NEXT:    [[C2:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A2]], i32 [[B2]])
; SLM-NEXT:    [[C3:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A3]], i32 [[B3]])
; SLM-NEXT:    [[C4:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A4]], i32 [[B4]])
; SLM-NEXT:    [[C5:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A5]], i32 [[B5]])
; SLM-NEXT:    [[C6:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A6]], i32 [[B6]])
; SLM-NEXT:    [[C7:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A7]], i32 [[B7]])
; SLM-NEXT:    [[C8:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A8]], i32 [[B8]])
; SLM-NEXT:    [[C9:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A9]], i32 [[B9]])
; SLM-NEXT:    [[C10:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A10]], i32 [[B10]])
; SLM-NEXT:    [[C11:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A11]], i32 [[B11]])
; SLM-NEXT:    [[C12:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A12]], i32 [[B12]])
; SLM-NEXT:    [[C13:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A13]], i32 [[B13]])
; SLM-NEXT:    [[C14:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A14]], i32 [[B14]])
; SLM-NEXT:    [[C15:%.*]] = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 [[A15]], i32 [[B15]])
; SLM-NEXT:    [[R0:%.*]] = extractvalue { i32, i1 } [[C0]], 0
; SLM-NEXT:    [[R1:%.*]] = extractvalue { i32, i1 } [[C1]], 0
; SLM-NEXT:    [[R2:%.*]] = extractvalue { i32, i1 } [[C2]], 0
; SLM-NEXT:    [[R3:%.*]] = extractvalue { i32, i1 } [[C3]], 0
; SLM-NEXT:    [[R4:%.*]] = extractvalue { i32, i1 } [[C4]], 0
; SLM-NEXT:    [[R5:%.*]] = extractvalue { i32, i1 } [[C5]], 0
; SLM-NEXT:    [[R6:%.*]] = extractvalue { i32, i1 } [[C6]], 0
; SLM-NEXT:    [[R7:%.*]] = extractvalue { i32, i1 } [[C7]], 0
; SLM-NEXT:    [[R8:%.*]] = extractvalue { i32, i1 } [[C8]], 0
; SLM-NEXT:    [[R9:%.*]] = extractvalue { i32, i1 } [[C9]], 0
; SLM-NEXT:    [[R10:%.*]] = extractvalue { i32, i1 } [[C10]], 0
; SLM-NEXT:    [[R11:%.*]] = extractvalue { i32, i1 } [[C11]], 0
; SLM-NEXT:    [[R12:%.*]] = extractvalue { i32, i1 } [[C12]], 0
; SLM-NEXT:    [[R13:%.*]] = extractvalue { i32, i1 } [[C13]], 0
; SLM-NEXT:    [[R14:%.*]] = extractvalue { i32, i1 } [[C14]], 0
; SLM-NEXT:    [[R15:%.*]] = extractvalue { i32, i1 } [[C15]], 0
; SLM-NEXT:    store i32 [[R0]], ptr @c32, align 4
; SLM-NEXT:    store i32 [[R1]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 1), align 4
; SLM-NEXT:    store i32 [[R2]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 2), align 4
; SLM-NEXT:    store i32 [[R3]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 3), align 4
; SLM-NEXT:    store i32 [[R4]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 4), align 4
; SLM-NEXT:    store i32 [[R5]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 5), align 4
; SLM-NEXT:    store i32 [[R6]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 6), align 4
; SLM-NEXT:    store i32 [[R7]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 7), align 4
; SLM-NEXT:    store i32 [[R8]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 8), align 4
; SLM-NEXT:    store i32 [[R9]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 9), align 4
; SLM-NEXT:    store i32 [[R10]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 10), align 4
; SLM-NEXT:    store i32 [[R11]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 11), align 4
; SLM-NEXT:    store i32 [[R12]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 12), align 4
; SLM-NEXT:    store i32 [[R13]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 13), align 4
; SLM-NEXT:    store i32 [[R14]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 14), align 4
; SLM-NEXT:    store i32 [[R15]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 15), align 4
; SLM-NEXT:    ret void
;
; AVX-LABEL: @mul_v16i32(
; AVX-NEXT:    [[TMP1:%.*]] = load <16 x i32>, ptr @a32, align 4
; AVX-NEXT:    [[TMP2:%.*]] = load <16 x i32>, ptr @b32, align 4
; AVX-NEXT:    [[TMP3:%.*]] = call { <16 x i32>, <16 x i1> } @llvm.smul.with.overflow.v16i32(<16 x i32> [[TMP1]], <16 x i32> [[TMP2]])
; AVX-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP5:%.*]] = extractelement <16 x i32> [[TMP4]], i32 0
; AVX-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP7:%.*]] = extractelement <16 x i32> [[TMP6]], i32 1
; AVX-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP9:%.*]] = extractelement <16 x i32> [[TMP8]], i32 2
; AVX-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP11:%.*]] = extractelement <16 x i32> [[TMP10]], i32 3
; AVX-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP13:%.*]] = extractelement <16 x i32> [[TMP12]], i32 4
; AVX-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP15:%.*]] = extractelement <16 x i32> [[TMP14]], i32 5
; AVX-NEXT:    [[TMP16:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP17:%.*]] = extractelement <16 x i32> [[TMP16]], i32 6
; AVX-NEXT:    [[TMP18:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP19:%.*]] = extractelement <16 x i32> [[TMP18]], i32 7
; AVX-NEXT:    [[TMP20:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP21:%.*]] = extractelement <16 x i32> [[TMP20]], i32 8
; AVX-NEXT:    [[TMP22:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP23:%.*]] = extractelement <16 x i32> [[TMP22]], i32 9
; AVX-NEXT:    [[TMP24:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP25:%.*]] = extractelement <16 x i32> [[TMP24]], i32 10
; AVX-NEXT:    [[TMP26:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP27:%.*]] = extractelement <16 x i32> [[TMP26]], i32 11
; AVX-NEXT:    [[TMP28:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP29:%.*]] = extractelement <16 x i32> [[TMP28]], i32 12
; AVX-NEXT:    [[TMP30:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP31:%.*]] = extractelement <16 x i32> [[TMP30]], i32 13
; AVX-NEXT:    [[TMP32:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP33:%.*]] = extractelement <16 x i32> [[TMP32]], i32 14
; AVX-NEXT:    [[TMP34:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX-NEXT:    [[TMP35:%.*]] = extractelement <16 x i32> [[TMP34]], i32 15
; AVX-NEXT:    store i32 [[TMP5]], ptr @c32, align 4
; AVX-NEXT:    store i32 [[TMP7]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 1), align 4
; AVX-NEXT:    store i32 [[TMP9]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 2), align 4
; AVX-NEXT:    store i32 [[TMP11]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 3), align 4
; AVX-NEXT:    store i32 [[TMP13]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 4), align 4
; AVX-NEXT:    store i32 [[TMP15]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 5), align 4
; AVX-NEXT:    store i32 [[TMP17]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 6), align 4
; AVX-NEXT:    store i32 [[TMP19]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 7), align 4
; AVX-NEXT:    store i32 [[TMP21]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 8), align 4
; AVX-NEXT:    store i32 [[TMP23]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 9), align 4
; AVX-NEXT:    store i32 [[TMP25]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 10), align 4
; AVX-NEXT:    store i32 [[TMP27]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 11), align 4
; AVX-NEXT:    store i32 [[TMP29]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 12), align 4
; AVX-NEXT:    store i32 [[TMP31]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 13), align 4
; AVX-NEXT:    store i32 [[TMP33]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 14), align 4
; AVX-NEXT:    store i32 [[TMP35]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 15), align 4
; AVX-NEXT:    ret void
;
; AVX2-LABEL: @mul_v16i32(
; AVX2-NEXT:    [[TMP1:%.*]] = load <16 x i32>, ptr @a32, align 4
; AVX2-NEXT:    [[TMP2:%.*]] = load <16 x i32>, ptr @b32, align 4
; AVX2-NEXT:    [[TMP3:%.*]] = call { <16 x i32>, <16 x i1> } @llvm.smul.with.overflow.v16i32(<16 x i32> [[TMP1]], <16 x i32> [[TMP2]])
; AVX2-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP5:%.*]] = extractelement <16 x i32> [[TMP4]], i32 0
; AVX2-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP7:%.*]] = extractelement <16 x i32> [[TMP6]], i32 1
; AVX2-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP9:%.*]] = extractelement <16 x i32> [[TMP8]], i32 2
; AVX2-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP11:%.*]] = extractelement <16 x i32> [[TMP10]], i32 3
; AVX2-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP13:%.*]] = extractelement <16 x i32> [[TMP12]], i32 4
; AVX2-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP15:%.*]] = extractelement <16 x i32> [[TMP14]], i32 5
; AVX2-NEXT:    [[TMP16:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP17:%.*]] = extractelement <16 x i32> [[TMP16]], i32 6
; AVX2-NEXT:    [[TMP18:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP19:%.*]] = extractelement <16 x i32> [[TMP18]], i32 7
; AVX2-NEXT:    [[TMP20:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP21:%.*]] = extractelement <16 x i32> [[TMP20]], i32 8
; AVX2-NEXT:    [[TMP22:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP23:%.*]] = extractelement <16 x i32> [[TMP22]], i32 9
; AVX2-NEXT:    [[TMP24:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP25:%.*]] = extractelement <16 x i32> [[TMP24]], i32 10
; AVX2-NEXT:    [[TMP26:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP27:%.*]] = extractelement <16 x i32> [[TMP26]], i32 11
; AVX2-NEXT:    [[TMP28:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP29:%.*]] = extractelement <16 x i32> [[TMP28]], i32 12
; AVX2-NEXT:    [[TMP30:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP31:%.*]] = extractelement <16 x i32> [[TMP30]], i32 13
; AVX2-NEXT:    [[TMP32:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP33:%.*]] = extractelement <16 x i32> [[TMP32]], i32 14
; AVX2-NEXT:    [[TMP34:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX2-NEXT:    [[TMP35:%.*]] = extractelement <16 x i32> [[TMP34]], i32 15
; AVX2-NEXT:    store i32 [[TMP5]], ptr @c32, align 4
; AVX2-NEXT:    store i32 [[TMP7]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 1), align 4
; AVX2-NEXT:    store i32 [[TMP9]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 2), align 4
; AVX2-NEXT:    store i32 [[TMP11]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 3), align 4
; AVX2-NEXT:    store i32 [[TMP13]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 4), align 4
; AVX2-NEXT:    store i32 [[TMP15]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 5), align 4
; AVX2-NEXT:    store i32 [[TMP17]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 6), align 4
; AVX2-NEXT:    store i32 [[TMP19]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 7), align 4
; AVX2-NEXT:    store i32 [[TMP21]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 8), align 4
; AVX2-NEXT:    store i32 [[TMP23]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 9), align 4
; AVX2-NEXT:    store i32 [[TMP25]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 10), align 4
; AVX2-NEXT:    store i32 [[TMP27]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 11), align 4
; AVX2-NEXT:    store i32 [[TMP29]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 12), align 4
; AVX2-NEXT:    store i32 [[TMP31]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 13), align 4
; AVX2-NEXT:    store i32 [[TMP33]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 14), align 4
; AVX2-NEXT:    store i32 [[TMP35]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 15), align 4
; AVX2-NEXT:    ret void
;
; KNL-LABEL: @mul_v16i32(
; KNL-NEXT:    [[TMP1:%.*]] = load <16 x i32>, ptr @a32, align 4
; KNL-NEXT:    [[TMP2:%.*]] = load <16 x i32>, ptr @b32, align 4
; KNL-NEXT:    [[TMP3:%.*]] = call { <16 x i32>, <16 x i1> } @llvm.smul.with.overflow.v16i32(<16 x i32> [[TMP1]], <16 x i32> [[TMP2]])
; KNL-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP5:%.*]] = extractelement <16 x i32> [[TMP4]], i32 0
; KNL-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP7:%.*]] = extractelement <16 x i32> [[TMP6]], i32 1
; KNL-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP9:%.*]] = extractelement <16 x i32> [[TMP8]], i32 2
; KNL-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP11:%.*]] = extractelement <16 x i32> [[TMP10]], i32 3
; KNL-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP13:%.*]] = extractelement <16 x i32> [[TMP12]], i32 4
; KNL-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP15:%.*]] = extractelement <16 x i32> [[TMP14]], i32 5
; KNL-NEXT:    [[TMP16:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP17:%.*]] = extractelement <16 x i32> [[TMP16]], i32 6
; KNL-NEXT:    [[TMP18:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP19:%.*]] = extractelement <16 x i32> [[TMP18]], i32 7
; KNL-NEXT:    [[TMP20:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP21:%.*]] = extractelement <16 x i32> [[TMP20]], i32 8
; KNL-NEXT:    [[TMP22:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP23:%.*]] = extractelement <16 x i32> [[TMP22]], i32 9
; KNL-NEXT:    [[TMP24:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP25:%.*]] = extractelement <16 x i32> [[TMP24]], i32 10
; KNL-NEXT:    [[TMP26:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP27:%.*]] = extractelement <16 x i32> [[TMP26]], i32 11
; KNL-NEXT:    [[TMP28:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP29:%.*]] = extractelement <16 x i32> [[TMP28]], i32 12
; KNL-NEXT:    [[TMP30:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP31:%.*]] = extractelement <16 x i32> [[TMP30]], i32 13
; KNL-NEXT:    [[TMP32:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP33:%.*]] = extractelement <16 x i32> [[TMP32]], i32 14
; KNL-NEXT:    [[TMP34:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; KNL-NEXT:    [[TMP35:%.*]] = extractelement <16 x i32> [[TMP34]], i32 15
; KNL-NEXT:    store i32 [[TMP5]], ptr @c32, align 4
; KNL-NEXT:    store i32 [[TMP7]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 1), align 4
; KNL-NEXT:    store i32 [[TMP9]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 2), align 4
; KNL-NEXT:    store i32 [[TMP11]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 3), align 4
; KNL-NEXT:    store i32 [[TMP13]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 4), align 4
; KNL-NEXT:    store i32 [[TMP15]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 5), align 4
; KNL-NEXT:    store i32 [[TMP17]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 6), align 4
; KNL-NEXT:    store i32 [[TMP19]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 7), align 4
; KNL-NEXT:    store i32 [[TMP21]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 8), align 4
; KNL-NEXT:    store i32 [[TMP23]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 9), align 4
; KNL-NEXT:    store i32 [[TMP25]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 10), align 4
; KNL-NEXT:    store i32 [[TMP27]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 11), align 4
; KNL-NEXT:    store i32 [[TMP29]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 12), align 4
; KNL-NEXT:    store i32 [[TMP31]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 13), align 4
; KNL-NEXT:    store i32 [[TMP33]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 14), align 4
; KNL-NEXT:    store i32 [[TMP35]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 15), align 4
; KNL-NEXT:    ret void
;
; AVX512-LABEL: @mul_v16i32(
; AVX512-NEXT:    [[TMP1:%.*]] = load <16 x i32>, ptr @a32, align 4
; AVX512-NEXT:    [[TMP2:%.*]] = load <16 x i32>, ptr @b32, align 4
; AVX512-NEXT:    [[TMP3:%.*]] = call { <16 x i32>, <16 x i1> } @llvm.smul.with.overflow.v16i32(<16 x i32> [[TMP1]], <16 x i32> [[TMP2]])
; AVX512-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP5:%.*]] = extractelement <16 x i32> [[TMP4]], i32 0
; AVX512-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP7:%.*]] = extractelement <16 x i32> [[TMP6]], i32 1
; AVX512-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP9:%.*]] = extractelement <16 x i32> [[TMP8]], i32 2
; AVX512-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP11:%.*]] = extractelement <16 x i32> [[TMP10]], i32 3
; AVX512-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP13:%.*]] = extractelement <16 x i32> [[TMP12]], i32 4
; AVX512-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP15:%.*]] = extractelement <16 x i32> [[TMP14]], i32 5
; AVX512-NEXT:    [[TMP16:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP17:%.*]] = extractelement <16 x i32> [[TMP16]], i32 6
; AVX512-NEXT:    [[TMP18:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP19:%.*]] = extractelement <16 x i32> [[TMP18]], i32 7
; AVX512-NEXT:    [[TMP20:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP21:%.*]] = extractelement <16 x i32> [[TMP20]], i32 8
; AVX512-NEXT:    [[TMP22:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP23:%.*]] = extractelement <16 x i32> [[TMP22]], i32 9
; AVX512-NEXT:    [[TMP24:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP25:%.*]] = extractelement <16 x i32> [[TMP24]], i32 10
; AVX512-NEXT:    [[TMP26:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP27:%.*]] = extractelement <16 x i32> [[TMP26]], i32 11
; AVX512-NEXT:    [[TMP28:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP29:%.*]] = extractelement <16 x i32> [[TMP28]], i32 12
; AVX512-NEXT:    [[TMP30:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP31:%.*]] = extractelement <16 x i32> [[TMP30]], i32 13
; AVX512-NEXT:    [[TMP32:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP33:%.*]] = extractelement <16 x i32> [[TMP32]], i32 14
; AVX512-NEXT:    [[TMP34:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512-NEXT:    [[TMP35:%.*]] = extractelement <16 x i32> [[TMP34]], i32 15
; AVX512-NEXT:    store i32 [[TMP5]], ptr @c32, align 4
; AVX512-NEXT:    store i32 [[TMP7]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 1), align 4
; AVX512-NEXT:    store i32 [[TMP9]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 2), align 4
; AVX512-NEXT:    store i32 [[TMP11]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 3), align 4
; AVX512-NEXT:    store i32 [[TMP13]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 4), align 4
; AVX512-NEXT:    store i32 [[TMP15]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 5), align 4
; AVX512-NEXT:    store i32 [[TMP17]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 6), align 4
; AVX512-NEXT:    store i32 [[TMP19]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 7), align 4
; AVX512-NEXT:    store i32 [[TMP21]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 8), align 4
; AVX512-NEXT:    store i32 [[TMP23]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 9), align 4
; AVX512-NEXT:    store i32 [[TMP25]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 10), align 4
; AVX512-NEXT:    store i32 [[TMP27]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 11), align 4
; AVX512-NEXT:    store i32 [[TMP29]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 12), align 4
; AVX512-NEXT:    store i32 [[TMP31]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 13), align 4
; AVX512-NEXT:    store i32 [[TMP33]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 14), align 4
; AVX512-NEXT:    store i32 [[TMP35]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 15), align 4
; AVX512-NEXT:    ret void
;
; AVX512_256-LABEL: @mul_v16i32(
; AVX512_256-NEXT:    [[TMP1:%.*]] = load <16 x i32>, ptr @a32, align 4
; AVX512_256-NEXT:    [[TMP2:%.*]] = load <16 x i32>, ptr @b32, align 4
; AVX512_256-NEXT:    [[TMP3:%.*]] = call { <16 x i32>, <16 x i1> } @llvm.smul.with.overflow.v16i32(<16 x i32> [[TMP1]], <16 x i32> [[TMP2]])
; AVX512_256-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP5:%.*]] = extractelement <16 x i32> [[TMP4]], i32 0
; AVX512_256-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP7:%.*]] = extractelement <16 x i32> [[TMP6]], i32 1
; AVX512_256-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP9:%.*]] = extractelement <16 x i32> [[TMP8]], i32 2
; AVX512_256-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP11:%.*]] = extractelement <16 x i32> [[TMP10]], i32 3
; AVX512_256-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP13:%.*]] = extractelement <16 x i32> [[TMP12]], i32 4
; AVX512_256-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP15:%.*]] = extractelement <16 x i32> [[TMP14]], i32 5
; AVX512_256-NEXT:    [[TMP16:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP17:%.*]] = extractelement <16 x i32> [[TMP16]], i32 6
; AVX512_256-NEXT:    [[TMP18:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP19:%.*]] = extractelement <16 x i32> [[TMP18]], i32 7
; AVX512_256-NEXT:    [[TMP20:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP21:%.*]] = extractelement <16 x i32> [[TMP20]], i32 8
; AVX512_256-NEXT:    [[TMP22:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP23:%.*]] = extractelement <16 x i32> [[TMP22]], i32 9
; AVX512_256-NEXT:    [[TMP24:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP25:%.*]] = extractelement <16 x i32> [[TMP24]], i32 10
; AVX512_256-NEXT:    [[TMP26:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP27:%.*]] = extractelement <16 x i32> [[TMP26]], i32 11
; AVX512_256-NEXT:    [[TMP28:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP29:%.*]] = extractelement <16 x i32> [[TMP28]], i32 12
; AVX512_256-NEXT:    [[TMP30:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP31:%.*]] = extractelement <16 x i32> [[TMP30]], i32 13
; AVX512_256-NEXT:    [[TMP32:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP33:%.*]] = extractelement <16 x i32> [[TMP32]], i32 14
; AVX512_256-NEXT:    [[TMP34:%.*]] = extractvalue { <16 x i32>, <16 x i1> } [[TMP3]], 0
; AVX512_256-NEXT:    [[TMP35:%.*]] = extractelement <16 x i32> [[TMP34]], i32 15
; AVX512_256-NEXT:    store i32 [[TMP5]], ptr @c32, align 4
; AVX512_256-NEXT:    store i32 [[TMP7]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 1), align 4
; AVX512_256-NEXT:    store i32 [[TMP9]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 2), align 4
; AVX512_256-NEXT:    store i32 [[TMP11]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 3), align 4
; AVX512_256-NEXT:    store i32 [[TMP13]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 4), align 4
; AVX512_256-NEXT:    store i32 [[TMP15]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 5), align 4
; AVX512_256-NEXT:    store i32 [[TMP17]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 6), align 4
; AVX512_256-NEXT:    store i32 [[TMP19]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 7), align 4
; AVX512_256-NEXT:    store i32 [[TMP21]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 8), align 4
; AVX512_256-NEXT:    store i32 [[TMP23]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 9), align 4
; AVX512_256-NEXT:    store i32 [[TMP25]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 10), align 4
; AVX512_256-NEXT:    store i32 [[TMP27]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 11), align 4
; AVX512_256-NEXT:    store i32 [[TMP29]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 12), align 4
; AVX512_256-NEXT:    store i32 [[TMP31]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 13), align 4
; AVX512_256-NEXT:    store i32 [[TMP33]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 14), align 4
; AVX512_256-NEXT:    store i32 [[TMP35]], ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 15), align 4
; AVX512_256-NEXT:    ret void
;
  %a0  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 0 ), align 4
  %a1  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 1 ), align 4
  %a2  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 2 ), align 4
  %a3  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 3 ), align 4
  %a4  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 4 ), align 4
  %a5  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 5 ), align 4
  %a6  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 6 ), align 4
  %a7  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 7 ), align 4
  %a8  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 8 ), align 4
  %a9  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 9 ), align 4
  %a10 = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 10), align 4
  %a11 = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 11), align 4
  %a12 = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 12), align 4
  %a13 = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 13), align 4
  %a14 = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 14), align 4
  %a15 = load i32, ptr getelementptr inbounds ([16 x i32], ptr @a32, i32 0, i64 15), align 4
  %b0  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 0 ), align 4
  %b1  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 1 ), align 4
  %b2  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 2 ), align 4
  %b3  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 3 ), align 4
  %b4  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 4 ), align 4
  %b5  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 5 ), align 4
  %b6  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 6 ), align 4
  %b7  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 7 ), align 4
  %b8  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 8 ), align 4
  %b9  = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 9 ), align 4
  %b10 = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 10), align 4
  %b11 = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 11), align 4
  %b12 = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 12), align 4
  %b13 = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 13), align 4
  %b14 = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 14), align 4
  %b15 = load i32, ptr getelementptr inbounds ([16 x i32], ptr @b32, i32 0, i64 15), align 4
  %c0  = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a0 , i32 %b0 )
  %c1  = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a1 , i32 %b1 )
  %c2  = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a2 , i32 %b2 )
  %c3  = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a3 , i32 %b3 )
  %c4  = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a4 , i32 %b4 )
  %c5  = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a5 , i32 %b5 )
  %c6  = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a6 , i32 %b6 )
  %c7  = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a7 , i32 %b7 )
  %c8  = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a8 , i32 %b8 )
  %c9  = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a9 , i32 %b9 )
  %c10 = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a10, i32 %b10)
  %c11 = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a11, i32 %b11)
  %c12 = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a12, i32 %b12)
  %c13 = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a13, i32 %b13)
  %c14 = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a14, i32 %b14)
  %c15 = call {i32, i1} @llvm.smul.with.overflow.i32(i32 %a15, i32 %b15)
  %r0  = extractvalue {i32, i1} %c0 , 0
  %r1  = extractvalue {i32, i1} %c1 , 0
  %r2  = extractvalue {i32, i1} %c2 , 0
  %r3  = extractvalue {i32, i1} %c3 , 0
  %r4  = extractvalue {i32, i1} %c4 , 0
  %r5  = extractvalue {i32, i1} %c5 , 0
  %r6  = extractvalue {i32, i1} %c6 , 0
  %r7  = extractvalue {i32, i1} %c7 , 0
  %r8  = extractvalue {i32, i1} %c8 , 0
  %r9  = extractvalue {i32, i1} %c9 , 0
  %r10 = extractvalue {i32, i1} %c10, 0
  %r11 = extractvalue {i32, i1} %c11, 0
  %r12 = extractvalue {i32, i1} %c12, 0
  %r13 = extractvalue {i32, i1} %c13, 0
  %r14 = extractvalue {i32, i1} %c14, 0
  %r15 = extractvalue {i32, i1} %c15, 0
  store i32 %r0 , ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 0 ), align 4
  store i32 %r1 , ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 1 ), align 4
  store i32 %r2 , ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 2 ), align 4
  store i32 %r3 , ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 3 ), align 4
  store i32 %r4 , ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 4 ), align 4
  store i32 %r5 , ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 5 ), align 4
  store i32 %r6 , ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 6 ), align 4
  store i32 %r7 , ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 7 ), align 4
  store i32 %r8 , ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 8 ), align 4
  store i32 %r9 , ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 9 ), align 4
  store i32 %r10, ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 10), align 4
  store i32 %r11, ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 11), align 4
  store i32 %r12, ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 12), align 4
  store i32 %r13, ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 13), align 4
  store i32 %r14, ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 14), align 4
  store i32 %r15, ptr getelementptr inbounds ([16 x i32], ptr @c32, i32 0, i64 15), align 4
  ret void
}

define void @mul_v32i16() {
; CHECK-LABEL: @mul_v32i16(
; CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i16>, ptr @a16, align 2
; CHECK-NEXT:    [[TMP2:%.*]] = load <32 x i16>, ptr @b16, align 2
; CHECK-NEXT:    [[TMP3:%.*]] = call { <32 x i16>, <32 x i1> } @llvm.smul.with.overflow.v32i16(<32 x i16> [[TMP1]], <32 x i16> [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R0:%.*]] = extractelement <32 x i16> [[TMP4]], i32 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R1:%.*]] = extractelement <32 x i16> [[TMP6]], i32 1
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R2:%.*]] = extractelement <32 x i16> [[TMP8]], i32 2
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R3:%.*]] = extractelement <32 x i16> [[TMP10]], i32 3
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R4:%.*]] = extractelement <32 x i16> [[TMP12]], i32 4
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R5:%.*]] = extractelement <32 x i16> [[TMP14]], i32 5
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R6:%.*]] = extractelement <32 x i16> [[TMP16]], i32 6
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R7:%.*]] = extractelement <32 x i16> [[TMP18]], i32 7
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R8:%.*]] = extractelement <32 x i16> [[TMP20]], i32 8
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R9:%.*]] = extractelement <32 x i16> [[TMP22]], i32 9
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R10:%.*]] = extractelement <32 x i16> [[TMP24]], i32 10
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R11:%.*]] = extractelement <32 x i16> [[TMP26]], i32 11
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R12:%.*]] = extractelement <32 x i16> [[TMP28]], i32 12
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R13:%.*]] = extractelement <32 x i16> [[TMP30]], i32 13
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R14:%.*]] = extractelement <32 x i16> [[TMP32]], i32 14
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R15:%.*]] = extractelement <32 x i16> [[TMP34]], i32 15
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R16:%.*]] = extractelement <32 x i16> [[TMP36]], i32 16
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R17:%.*]] = extractelement <32 x i16> [[TMP38]], i32 17
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R18:%.*]] = extractelement <32 x i16> [[TMP40]], i32 18
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R19:%.*]] = extractelement <32 x i16> [[TMP42]], i32 19
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R20:%.*]] = extractelement <32 x i16> [[TMP44]], i32 20
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R21:%.*]] = extractelement <32 x i16> [[TMP46]], i32 21
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R22:%.*]] = extractelement <32 x i16> [[TMP48]], i32 22
; CHECK-NEXT:    [[TMP50:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R23:%.*]] = extractelement <32 x i16> [[TMP50]], i32 23
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R24:%.*]] = extractelement <32 x i16> [[TMP52]], i32 24
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R25:%.*]] = extractelement <32 x i16> [[TMP54]], i32 25
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R26:%.*]] = extractelement <32 x i16> [[TMP56]], i32 26
; CHECK-NEXT:    [[TMP58:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R27:%.*]] = extractelement <32 x i16> [[TMP58]], i32 27
; CHECK-NEXT:    [[TMP60:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R28:%.*]] = extractelement <32 x i16> [[TMP60]], i32 28
; CHECK-NEXT:    [[TMP62:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R29:%.*]] = extractelement <32 x i16> [[TMP62]], i32 29
; CHECK-NEXT:    [[TMP64:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R30:%.*]] = extractelement <32 x i16> [[TMP64]], i32 30
; CHECK-NEXT:    [[TMP66:%.*]] = extractvalue { <32 x i16>, <32 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R31:%.*]] = extractelement <32 x i16> [[TMP66]], i32 31
; CHECK-NEXT:    store i16 [[R0]], ptr @c16, align 2
; CHECK-NEXT:    store i16 [[R1]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 1), align 2
; CHECK-NEXT:    store i16 [[R2]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 2), align 2
; CHECK-NEXT:    store i16 [[R3]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 3), align 2
; CHECK-NEXT:    store i16 [[R4]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 4), align 2
; CHECK-NEXT:    store i16 [[R5]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 5), align 2
; CHECK-NEXT:    store i16 [[R6]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 6), align 2
; CHECK-NEXT:    store i16 [[R7]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 7), align 2
; CHECK-NEXT:    store i16 [[R8]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 8), align 2
; CHECK-NEXT:    store i16 [[R9]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 9), align 2
; CHECK-NEXT:    store i16 [[R10]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 10), align 2
; CHECK-NEXT:    store i16 [[R11]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 11), align 2
; CHECK-NEXT:    store i16 [[R12]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 12), align 2
; CHECK-NEXT:    store i16 [[R13]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 13), align 2
; CHECK-NEXT:    store i16 [[R14]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 14), align 2
; CHECK-NEXT:    store i16 [[R15]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 15), align 2
; CHECK-NEXT:    store i16 [[R16]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 16), align 2
; CHECK-NEXT:    store i16 [[R17]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 17), align 2
; CHECK-NEXT:    store i16 [[R18]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 18), align 2
; CHECK-NEXT:    store i16 [[R19]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 19), align 2
; CHECK-NEXT:    store i16 [[R20]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 20), align 2
; CHECK-NEXT:    store i16 [[R21]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 21), align 2
; CHECK-NEXT:    store i16 [[R22]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 22), align 2
; CHECK-NEXT:    store i16 [[R23]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 23), align 2
; CHECK-NEXT:    store i16 [[R24]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 24), align 2
; CHECK-NEXT:    store i16 [[R25]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 25), align 2
; CHECK-NEXT:    store i16 [[R26]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 26), align 2
; CHECK-NEXT:    store i16 [[R27]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 27), align 2
; CHECK-NEXT:    store i16 [[R28]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 28), align 2
; CHECK-NEXT:    store i16 [[R29]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 29), align 2
; CHECK-NEXT:    store i16 [[R30]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 30), align 2
; CHECK-NEXT:    store i16 [[R31]], ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 31), align 2
; CHECK-NEXT:    ret void
;
  %a0  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 0 ), align 2
  %a1  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 1 ), align 2
  %a2  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 2 ), align 2
  %a3  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 3 ), align 2
  %a4  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 4 ), align 2
  %a5  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 5 ), align 2
  %a6  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 6 ), align 2
  %a7  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 7 ), align 2
  %a8  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 8 ), align 2
  %a9  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 9 ), align 2
  %a10 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 10), align 2
  %a11 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 11), align 2
  %a12 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 12), align 2
  %a13 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 13), align 2
  %a14 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 14), align 2
  %a15 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 15), align 2
  %a16 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 16), align 2
  %a17 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 17), align 2
  %a18 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 18), align 2
  %a19 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 19), align 2
  %a20 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 20), align 2
  %a21 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 21), align 2
  %a22 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 22), align 2
  %a23 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 23), align 2
  %a24 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 24), align 2
  %a25 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 25), align 2
  %a26 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 26), align 2
  %a27 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 27), align 2
  %a28 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 28), align 2
  %a29 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 29), align 2
  %a30 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 30), align 2
  %a31 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @a16, i32 0, i64 31), align 2
  %b0  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 0 ), align 2
  %b1  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 1 ), align 2
  %b2  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 2 ), align 2
  %b3  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 3 ), align 2
  %b4  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 4 ), align 2
  %b5  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 5 ), align 2
  %b6  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 6 ), align 2
  %b7  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 7 ), align 2
  %b8  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 8 ), align 2
  %b9  = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 9 ), align 2
  %b10 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 10), align 2
  %b11 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 11), align 2
  %b12 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 12), align 2
  %b13 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 13), align 2
  %b14 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 14), align 2
  %b15 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 15), align 2
  %b16 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 16), align 2
  %b17 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 17), align 2
  %b18 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 18), align 2
  %b19 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 19), align 2
  %b20 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 20), align 2
  %b21 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 21), align 2
  %b22 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 22), align 2
  %b23 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 23), align 2
  %b24 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 24), align 2
  %b25 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 25), align 2
  %b26 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 26), align 2
  %b27 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 27), align 2
  %b28 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 28), align 2
  %b29 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 29), align 2
  %b30 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 30), align 2
  %b31 = load i16, ptr getelementptr inbounds ([32 x i16], ptr @b16, i32 0, i64 31), align 2
  %c0  = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a0 , i16 %b0 )
  %c1  = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a1 , i16 %b1 )
  %c2  = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a2 , i16 %b2 )
  %c3  = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a3 , i16 %b3 )
  %c4  = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a4 , i16 %b4 )
  %c5  = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a5 , i16 %b5 )
  %c6  = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a6 , i16 %b6 )
  %c7  = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a7 , i16 %b7 )
  %c8  = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a8 , i16 %b8 )
  %c9  = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a9 , i16 %b9 )
  %c10 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a10, i16 %b10)
  %c11 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a11, i16 %b11)
  %c12 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a12, i16 %b12)
  %c13 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a13, i16 %b13)
  %c14 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a14, i16 %b14)
  %c15 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a15, i16 %b15)
  %c16 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a16, i16 %b16)
  %c17 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a17, i16 %b17)
  %c18 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a18, i16 %b18)
  %c19 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a19, i16 %b19)
  %c20 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a20, i16 %b20)
  %c21 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a21, i16 %b21)
  %c22 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a22, i16 %b22)
  %c23 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a23, i16 %b23)
  %c24 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a24, i16 %b24)
  %c25 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a25, i16 %b25)
  %c26 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a26, i16 %b26)
  %c27 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a27, i16 %b27)
  %c28 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a28, i16 %b28)
  %c29 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a29, i16 %b29)
  %c30 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a30, i16 %b30)
  %c31 = call {i16, i1} @llvm.smul.with.overflow.i16(i16 %a31, i16 %b31)
  %r0  = extractvalue {i16, i1} %c0 , 0
  %r1  = extractvalue {i16, i1} %c1 , 0
  %r2  = extractvalue {i16, i1} %c2 , 0
  %r3  = extractvalue {i16, i1} %c3 , 0
  %r4  = extractvalue {i16, i1} %c4 , 0
  %r5  = extractvalue {i16, i1} %c5 , 0
  %r6  = extractvalue {i16, i1} %c6 , 0
  %r7  = extractvalue {i16, i1} %c7 , 0
  %r8  = extractvalue {i16, i1} %c8 , 0
  %r9  = extractvalue {i16, i1} %c9 , 0
  %r10 = extractvalue {i16, i1} %c10, 0
  %r11 = extractvalue {i16, i1} %c11, 0
  %r12 = extractvalue {i16, i1} %c12, 0
  %r13 = extractvalue {i16, i1} %c13, 0
  %r14 = extractvalue {i16, i1} %c14, 0
  %r15 = extractvalue {i16, i1} %c15, 0
  %r16 = extractvalue {i16, i1} %c16, 0
  %r17 = extractvalue {i16, i1} %c17, 0
  %r18 = extractvalue {i16, i1} %c18, 0
  %r19 = extractvalue {i16, i1} %c19, 0
  %r20 = extractvalue {i16, i1} %c20, 0
  %r21 = extractvalue {i16, i1} %c21, 0
  %r22 = extractvalue {i16, i1} %c22, 0
  %r23 = extractvalue {i16, i1} %c23, 0
  %r24 = extractvalue {i16, i1} %c24, 0
  %r25 = extractvalue {i16, i1} %c25, 0
  %r26 = extractvalue {i16, i1} %c26, 0
  %r27 = extractvalue {i16, i1} %c27, 0
  %r28 = extractvalue {i16, i1} %c28, 0
  %r29 = extractvalue {i16, i1} %c29, 0
  %r30 = extractvalue {i16, i1} %c30, 0
  %r31 = extractvalue {i16, i1} %c31, 0
  store i16 %r0 , ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 0 ), align 2
  store i16 %r1 , ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 1 ), align 2
  store i16 %r2 , ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 2 ), align 2
  store i16 %r3 , ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 3 ), align 2
  store i16 %r4 , ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 4 ), align 2
  store i16 %r5 , ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 5 ), align 2
  store i16 %r6 , ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 6 ), align 2
  store i16 %r7 , ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 7 ), align 2
  store i16 %r8 , ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 8 ), align 2
  store i16 %r9 , ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 9 ), align 2
  store i16 %r10, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 10), align 2
  store i16 %r11, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 11), align 2
  store i16 %r12, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 12), align 2
  store i16 %r13, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 13), align 2
  store i16 %r14, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 14), align 2
  store i16 %r15, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 15), align 2
  store i16 %r16, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 16), align 2
  store i16 %r17, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 17), align 2
  store i16 %r18, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 18), align 2
  store i16 %r19, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 19), align 2
  store i16 %r20, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 20), align 2
  store i16 %r21, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 21), align 2
  store i16 %r22, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 22), align 2
  store i16 %r23, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 23), align 2
  store i16 %r24, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 24), align 2
  store i16 %r25, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 25), align 2
  store i16 %r26, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 26), align 2
  store i16 %r27, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 27), align 2
  store i16 %r28, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 28), align 2
  store i16 %r29, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 29), align 2
  store i16 %r30, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 30), align 2
  store i16 %r31, ptr getelementptr inbounds ([32 x i16], ptr @c16, i32 0, i64 31), align 2
  ret void
}

define void @mul_v64i8() {
; CHECK-LABEL: @mul_v64i8(
; CHECK-NEXT:    [[TMP1:%.*]] = load <64 x i8>, ptr @a8, align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load <64 x i8>, ptr @b8, align 1
; CHECK-NEXT:    [[TMP3:%.*]] = call { <64 x i8>, <64 x i1> } @llvm.smul.with.overflow.v64i8(<64 x i8> [[TMP1]], <64 x i8> [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R0:%.*]] = extractelement <64 x i8> [[TMP4]], i32 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R1:%.*]] = extractelement <64 x i8> [[TMP6]], i32 1
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R2:%.*]] = extractelement <64 x i8> [[TMP8]], i32 2
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R3:%.*]] = extractelement <64 x i8> [[TMP10]], i32 3
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R4:%.*]] = extractelement <64 x i8> [[TMP12]], i32 4
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R5:%.*]] = extractelement <64 x i8> [[TMP14]], i32 5
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R6:%.*]] = extractelement <64 x i8> [[TMP16]], i32 6
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R7:%.*]] = extractelement <64 x i8> [[TMP18]], i32 7
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R8:%.*]] = extractelement <64 x i8> [[TMP20]], i32 8
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R9:%.*]] = extractelement <64 x i8> [[TMP22]], i32 9
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R10:%.*]] = extractelement <64 x i8> [[TMP24]], i32 10
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R11:%.*]] = extractelement <64 x i8> [[TMP26]], i32 11
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R12:%.*]] = extractelement <64 x i8> [[TMP28]], i32 12
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R13:%.*]] = extractelement <64 x i8> [[TMP30]], i32 13
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R14:%.*]] = extractelement <64 x i8> [[TMP32]], i32 14
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R15:%.*]] = extractelement <64 x i8> [[TMP34]], i32 15
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R16:%.*]] = extractelement <64 x i8> [[TMP36]], i32 16
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R17:%.*]] = extractelement <64 x i8> [[TMP38]], i32 17
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R18:%.*]] = extractelement <64 x i8> [[TMP40]], i32 18
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R19:%.*]] = extractelement <64 x i8> [[TMP42]], i32 19
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R20:%.*]] = extractelement <64 x i8> [[TMP44]], i32 20
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R21:%.*]] = extractelement <64 x i8> [[TMP46]], i32 21
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R22:%.*]] = extractelement <64 x i8> [[TMP48]], i32 22
; CHECK-NEXT:    [[TMP50:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R23:%.*]] = extractelement <64 x i8> [[TMP50]], i32 23
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R24:%.*]] = extractelement <64 x i8> [[TMP52]], i32 24
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R25:%.*]] = extractelement <64 x i8> [[TMP54]], i32 25
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R26:%.*]] = extractelement <64 x i8> [[TMP56]], i32 26
; CHECK-NEXT:    [[TMP58:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R27:%.*]] = extractelement <64 x i8> [[TMP58]], i32 27
; CHECK-NEXT:    [[TMP60:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R28:%.*]] = extractelement <64 x i8> [[TMP60]], i32 28
; CHECK-NEXT:    [[TMP62:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R29:%.*]] = extractelement <64 x i8> [[TMP62]], i32 29
; CHECK-NEXT:    [[TMP64:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R30:%.*]] = extractelement <64 x i8> [[TMP64]], i32 30
; CHECK-NEXT:    [[TMP66:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R31:%.*]] = extractelement <64 x i8> [[TMP66]], i32 31
; CHECK-NEXT:    [[TMP68:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R32:%.*]] = extractelement <64 x i8> [[TMP68]], i32 32
; CHECK-NEXT:    [[TMP70:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R33:%.*]] = extractelement <64 x i8> [[TMP70]], i32 33
; CHECK-NEXT:    [[TMP72:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R34:%.*]] = extractelement <64 x i8> [[TMP72]], i32 34
; CHECK-NEXT:    [[TMP74:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R35:%.*]] = extractelement <64 x i8> [[TMP74]], i32 35
; CHECK-NEXT:    [[TMP76:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R36:%.*]] = extractelement <64 x i8> [[TMP76]], i32 36
; CHECK-NEXT:    [[TMP78:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R37:%.*]] = extractelement <64 x i8> [[TMP78]], i32 37
; CHECK-NEXT:    [[TMP80:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R38:%.*]] = extractelement <64 x i8> [[TMP80]], i32 38
; CHECK-NEXT:    [[TMP82:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R39:%.*]] = extractelement <64 x i8> [[TMP82]], i32 39
; CHECK-NEXT:    [[TMP84:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R40:%.*]] = extractelement <64 x i8> [[TMP84]], i32 40
; CHECK-NEXT:    [[TMP86:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R41:%.*]] = extractelement <64 x i8> [[TMP86]], i32 41
; CHECK-NEXT:    [[TMP88:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R42:%.*]] = extractelement <64 x i8> [[TMP88]], i32 42
; CHECK-NEXT:    [[TMP90:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R43:%.*]] = extractelement <64 x i8> [[TMP90]], i32 43
; CHECK-NEXT:    [[TMP92:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R44:%.*]] = extractelement <64 x i8> [[TMP92]], i32 44
; CHECK-NEXT:    [[TMP94:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R45:%.*]] = extractelement <64 x i8> [[TMP94]], i32 45
; CHECK-NEXT:    [[TMP96:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R46:%.*]] = extractelement <64 x i8> [[TMP96]], i32 46
; CHECK-NEXT:    [[TMP98:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R47:%.*]] = extractelement <64 x i8> [[TMP98]], i32 47
; CHECK-NEXT:    [[TMP100:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R48:%.*]] = extractelement <64 x i8> [[TMP100]], i32 48
; CHECK-NEXT:    [[TMP102:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R49:%.*]] = extractelement <64 x i8> [[TMP102]], i32 49
; CHECK-NEXT:    [[TMP104:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R50:%.*]] = extractelement <64 x i8> [[TMP104]], i32 50
; CHECK-NEXT:    [[TMP106:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R51:%.*]] = extractelement <64 x i8> [[TMP106]], i32 51
; CHECK-NEXT:    [[TMP108:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R52:%.*]] = extractelement <64 x i8> [[TMP108]], i32 52
; CHECK-NEXT:    [[TMP110:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R53:%.*]] = extractelement <64 x i8> [[TMP110]], i32 53
; CHECK-NEXT:    [[TMP112:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R54:%.*]] = extractelement <64 x i8> [[TMP112]], i32 54
; CHECK-NEXT:    [[TMP114:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R55:%.*]] = extractelement <64 x i8> [[TMP114]], i32 55
; CHECK-NEXT:    [[TMP116:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R56:%.*]] = extractelement <64 x i8> [[TMP116]], i32 56
; CHECK-NEXT:    [[TMP118:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R57:%.*]] = extractelement <64 x i8> [[TMP118]], i32 57
; CHECK-NEXT:    [[TMP120:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R58:%.*]] = extractelement <64 x i8> [[TMP120]], i32 58
; CHECK-NEXT:    [[TMP122:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R59:%.*]] = extractelement <64 x i8> [[TMP122]], i32 59
; CHECK-NEXT:    [[TMP124:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R60:%.*]] = extractelement <64 x i8> [[TMP124]], i32 60
; CHECK-NEXT:    [[TMP126:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R61:%.*]] = extractelement <64 x i8> [[TMP126]], i32 61
; CHECK-NEXT:    [[TMP128:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R62:%.*]] = extractelement <64 x i8> [[TMP128]], i32 62
; CHECK-NEXT:    [[TMP130:%.*]] = extractvalue { <64 x i8>, <64 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[R63:%.*]] = extractelement <64 x i8> [[TMP130]], i32 63
; CHECK-NEXT:    store i8 [[R0]], ptr @c8, align 1
; CHECK-NEXT:    store i8 [[R1]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 1), align 1
; CHECK-NEXT:    store i8 [[R2]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 2), align 1
; CHECK-NEXT:    store i8 [[R3]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 3), align 1
; CHECK-NEXT:    store i8 [[R4]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 4), align 1
; CHECK-NEXT:    store i8 [[R5]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 5), align 1
; CHECK-NEXT:    store i8 [[R6]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 6), align 1
; CHECK-NEXT:    store i8 [[R7]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 7), align 1
; CHECK-NEXT:    store i8 [[R8]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 8), align 1
; CHECK-NEXT:    store i8 [[R9]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 9), align 1
; CHECK-NEXT:    store i8 [[R10]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 10), align 1
; CHECK-NEXT:    store i8 [[R11]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 11), align 1
; CHECK-NEXT:    store i8 [[R12]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 12), align 1
; CHECK-NEXT:    store i8 [[R13]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 13), align 1
; CHECK-NEXT:    store i8 [[R14]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 14), align 1
; CHECK-NEXT:    store i8 [[R15]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 15), align 1
; CHECK-NEXT:    store i8 [[R16]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 16), align 1
; CHECK-NEXT:    store i8 [[R17]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 17), align 1
; CHECK-NEXT:    store i8 [[R18]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 18), align 1
; CHECK-NEXT:    store i8 [[R19]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 19), align 1
; CHECK-NEXT:    store i8 [[R20]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 20), align 1
; CHECK-NEXT:    store i8 [[R21]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 21), align 1
; CHECK-NEXT:    store i8 [[R22]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 22), align 1
; CHECK-NEXT:    store i8 [[R23]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 23), align 1
; CHECK-NEXT:    store i8 [[R24]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 24), align 1
; CHECK-NEXT:    store i8 [[R25]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 25), align 1
; CHECK-NEXT:    store i8 [[R26]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 26), align 1
; CHECK-NEXT:    store i8 [[R27]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 27), align 1
; CHECK-NEXT:    store i8 [[R28]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 28), align 1
; CHECK-NEXT:    store i8 [[R29]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 29), align 1
; CHECK-NEXT:    store i8 [[R30]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 30), align 1
; CHECK-NEXT:    store i8 [[R31]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 31), align 1
; CHECK-NEXT:    store i8 [[R32]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 32), align 1
; CHECK-NEXT:    store i8 [[R33]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 33), align 1
; CHECK-NEXT:    store i8 [[R34]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 34), align 1
; CHECK-NEXT:    store i8 [[R35]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 35), align 1
; CHECK-NEXT:    store i8 [[R36]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 36), align 1
; CHECK-NEXT:    store i8 [[R37]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 37), align 1
; CHECK-NEXT:    store i8 [[R38]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 38), align 1
; CHECK-NEXT:    store i8 [[R39]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 39), align 1
; CHECK-NEXT:    store i8 [[R40]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 40), align 1
; CHECK-NEXT:    store i8 [[R41]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 41), align 1
; CHECK-NEXT:    store i8 [[R42]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 42), align 1
; CHECK-NEXT:    store i8 [[R43]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 43), align 1
; CHECK-NEXT:    store i8 [[R44]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 44), align 1
; CHECK-NEXT:    store i8 [[R45]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 45), align 1
; CHECK-NEXT:    store i8 [[R46]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 46), align 1
; CHECK-NEXT:    store i8 [[R47]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 47), align 1
; CHECK-NEXT:    store i8 [[R48]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 48), align 1
; CHECK-NEXT:    store i8 [[R49]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 49), align 1
; CHECK-NEXT:    store i8 [[R50]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 50), align 1
; CHECK-NEXT:    store i8 [[R51]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 51), align 1
; CHECK-NEXT:    store i8 [[R52]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 52), align 1
; CHECK-NEXT:    store i8 [[R53]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 53), align 1
; CHECK-NEXT:    store i8 [[R54]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 54), align 1
; CHECK-NEXT:    store i8 [[R55]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 55), align 1
; CHECK-NEXT:    store i8 [[R56]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 56), align 1
; CHECK-NEXT:    store i8 [[R57]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 57), align 1
; CHECK-NEXT:    store i8 [[R58]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 58), align 1
; CHECK-NEXT:    store i8 [[R59]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 59), align 1
; CHECK-NEXT:    store i8 [[R60]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 60), align 1
; CHECK-NEXT:    store i8 [[R61]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 61), align 1
; CHECK-NEXT:    store i8 [[R62]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 62), align 1
; CHECK-NEXT:    store i8 [[R63]], ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 63), align 1
; CHECK-NEXT:    ret void
;
  %a0  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 0 ), align 1
  %a1  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 1 ), align 1
  %a2  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 2 ), align 1
  %a3  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 3 ), align 1
  %a4  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 4 ), align 1
  %a5  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 5 ), align 1
  %a6  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 6 ), align 1
  %a7  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 7 ), align 1
  %a8  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 8 ), align 1
  %a9  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 9 ), align 1
  %a10 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 10), align 1
  %a11 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 11), align 1
  %a12 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 12), align 1
  %a13 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 13), align 1
  %a14 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 14), align 1
  %a15 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 15), align 1
  %a16 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 16), align 1
  %a17 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 17), align 1
  %a18 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 18), align 1
  %a19 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 19), align 1
  %a20 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 20), align 1
  %a21 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 21), align 1
  %a22 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 22), align 1
  %a23 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 23), align 1
  %a24 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 24), align 1
  %a25 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 25), align 1
  %a26 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 26), align 1
  %a27 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 27), align 1
  %a28 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 28), align 1
  %a29 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 29), align 1
  %a30 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 30), align 1
  %a31 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 31), align 1
  %a32 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 32), align 1
  %a33 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 33), align 1
  %a34 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 34), align 1
  %a35 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 35), align 1
  %a36 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 36), align 1
  %a37 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 37), align 1
  %a38 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 38), align 1
  %a39 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 39), align 1
  %a40 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 40), align 1
  %a41 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 41), align 1
  %a42 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 42), align 1
  %a43 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 43), align 1
  %a44 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 44), align 1
  %a45 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 45), align 1
  %a46 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 46), align 1
  %a47 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 47), align 1
  %a48 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 48), align 1
  %a49 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 49), align 1
  %a50 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 50), align 1
  %a51 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 51), align 1
  %a52 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 52), align 1
  %a53 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 53), align 1
  %a54 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 54), align 1
  %a55 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 55), align 1
  %a56 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 56), align 1
  %a57 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 57), align 1
  %a58 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 58), align 1
  %a59 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 59), align 1
  %a60 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 60), align 1
  %a61 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 61), align 1
  %a62 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 62), align 1
  %a63 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @a8, i32 0, i64 63), align 1
  %b0  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 0 ), align 1
  %b1  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 1 ), align 1
  %b2  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 2 ), align 1
  %b3  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 3 ), align 1
  %b4  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 4 ), align 1
  %b5  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 5 ), align 1
  %b6  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 6 ), align 1
  %b7  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 7 ), align 1
  %b8  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 8 ), align 1
  %b9  = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 9 ), align 1
  %b10 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 10), align 1
  %b11 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 11), align 1
  %b12 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 12), align 1
  %b13 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 13), align 1
  %b14 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 14), align 1
  %b15 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 15), align 1
  %b16 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 16), align 1
  %b17 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 17), align 1
  %b18 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 18), align 1
  %b19 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 19), align 1
  %b20 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 20), align 1
  %b21 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 21), align 1
  %b22 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 22), align 1
  %b23 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 23), align 1
  %b24 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 24), align 1
  %b25 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 25), align 1
  %b26 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 26), align 1
  %b27 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 27), align 1
  %b28 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 28), align 1
  %b29 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 29), align 1
  %b30 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 30), align 1
  %b31 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 31), align 1
  %b32 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 32), align 1
  %b33 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 33), align 1
  %b34 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 34), align 1
  %b35 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 35), align 1
  %b36 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 36), align 1
  %b37 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 37), align 1
  %b38 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 38), align 1
  %b39 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 39), align 1
  %b40 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 40), align 1
  %b41 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 41), align 1
  %b42 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 42), align 1
  %b43 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 43), align 1
  %b44 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 44), align 1
  %b45 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 45), align 1
  %b46 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 46), align 1
  %b47 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 47), align 1
  %b48 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 48), align 1
  %b49 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 49), align 1
  %b50 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 50), align 1
  %b51 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 51), align 1
  %b52 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 52), align 1
  %b53 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 53), align 1
  %b54 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 54), align 1
  %b55 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 55), align 1
  %b56 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 56), align 1
  %b57 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 57), align 1
  %b58 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 58), align 1
  %b59 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 59), align 1
  %b60 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 60), align 1
  %b61 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 61), align 1
  %b62 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 62), align 1
  %b63 = load i8, ptr getelementptr inbounds ([64 x i8], ptr @b8, i32 0, i64 63), align 1
  %c0  = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a0 , i8 %b0 )
  %c1  = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a1 , i8 %b1 )
  %c2  = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a2 , i8 %b2 )
  %c3  = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a3 , i8 %b3 )
  %c4  = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a4 , i8 %b4 )
  %c5  = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a5 , i8 %b5 )
  %c6  = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a6 , i8 %b6 )
  %c7  = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a7 , i8 %b7 )
  %c8  = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a8 , i8 %b8 )
  %c9  = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a9 , i8 %b9 )
  %c10 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a10, i8 %b10)
  %c11 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a11, i8 %b11)
  %c12 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a12, i8 %b12)
  %c13 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a13, i8 %b13)
  %c14 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a14, i8 %b14)
  %c15 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a15, i8 %b15)
  %c16 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a16, i8 %b16)
  %c17 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a17, i8 %b17)
  %c18 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a18, i8 %b18)
  %c19 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a19, i8 %b19)
  %c20 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a20, i8 %b20)
  %c21 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a21, i8 %b21)
  %c22 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a22, i8 %b22)
  %c23 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a23, i8 %b23)
  %c24 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a24, i8 %b24)
  %c25 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a25, i8 %b25)
  %c26 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a26, i8 %b26)
  %c27 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a27, i8 %b27)
  %c28 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a28, i8 %b28)
  %c29 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a29, i8 %b29)
  %c30 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a30, i8 %b30)
  %c31 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a31, i8 %b31)
  %c32 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a32, i8 %b32)
  %c33 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a33, i8 %b33)
  %c34 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a34, i8 %b34)
  %c35 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a35, i8 %b35)
  %c36 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a36, i8 %b36)
  %c37 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a37, i8 %b37)
  %c38 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a38, i8 %b38)
  %c39 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a39, i8 %b39)
  %c40 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a40, i8 %b40)
  %c41 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a41, i8 %b41)
  %c42 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a42, i8 %b42)
  %c43 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a43, i8 %b43)
  %c44 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a44, i8 %b44)
  %c45 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a45, i8 %b45)
  %c46 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a46, i8 %b46)
  %c47 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a47, i8 %b47)
  %c48 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a48, i8 %b48)
  %c49 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a49, i8 %b49)
  %c50 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a50, i8 %b50)
  %c51 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a51, i8 %b51)
  %c52 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a52, i8 %b52)
  %c53 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a53, i8 %b53)
  %c54 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a54, i8 %b54)
  %c55 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a55, i8 %b55)
  %c56 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a56, i8 %b56)
  %c57 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a57, i8 %b57)
  %c58 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a58, i8 %b58)
  %c59 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a59, i8 %b59)
  %c60 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a60, i8 %b60)
  %c61 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a61, i8 %b61)
  %c62 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a62, i8 %b62)
  %c63 = call {i8, i1} @llvm.smul.with.overflow.i8(i8 %a63, i8 %b63)
  %r0  = extractvalue {i8, i1} %c0 , 0
  %r1  = extractvalue {i8, i1} %c1 , 0
  %r2  = extractvalue {i8, i1} %c2 , 0
  %r3  = extractvalue {i8, i1} %c3 , 0
  %r4  = extractvalue {i8, i1} %c4 , 0
  %r5  = extractvalue {i8, i1} %c5 , 0
  %r6  = extractvalue {i8, i1} %c6 , 0
  %r7  = extractvalue {i8, i1} %c7 , 0
  %r8  = extractvalue {i8, i1} %c8 , 0
  %r9  = extractvalue {i8, i1} %c9 , 0
  %r10 = extractvalue {i8, i1} %c10, 0
  %r11 = extractvalue {i8, i1} %c11, 0
  %r12 = extractvalue {i8, i1} %c12, 0
  %r13 = extractvalue {i8, i1} %c13, 0
  %r14 = extractvalue {i8, i1} %c14, 0
  %r15 = extractvalue {i8, i1} %c15, 0
  %r16 = extractvalue {i8, i1} %c16, 0
  %r17 = extractvalue {i8, i1} %c17, 0
  %r18 = extractvalue {i8, i1} %c18, 0
  %r19 = extractvalue {i8, i1} %c19, 0
  %r20 = extractvalue {i8, i1} %c20, 0
  %r21 = extractvalue {i8, i1} %c21, 0
  %r22 = extractvalue {i8, i1} %c22, 0
  %r23 = extractvalue {i8, i1} %c23, 0
  %r24 = extractvalue {i8, i1} %c24, 0
  %r25 = extractvalue {i8, i1} %c25, 0
  %r26 = extractvalue {i8, i1} %c26, 0
  %r27 = extractvalue {i8, i1} %c27, 0
  %r28 = extractvalue {i8, i1} %c28, 0
  %r29 = extractvalue {i8, i1} %c29, 0
  %r30 = extractvalue {i8, i1} %c30, 0
  %r31 = extractvalue {i8, i1} %c31, 0
  %r32 = extractvalue {i8, i1} %c32, 0
  %r33 = extractvalue {i8, i1} %c33, 0
  %r34 = extractvalue {i8, i1} %c34, 0
  %r35 = extractvalue {i8, i1} %c35, 0
  %r36 = extractvalue {i8, i1} %c36, 0
  %r37 = extractvalue {i8, i1} %c37, 0
  %r38 = extractvalue {i8, i1} %c38, 0
  %r39 = extractvalue {i8, i1} %c39, 0
  %r40 = extractvalue {i8, i1} %c40, 0
  %r41 = extractvalue {i8, i1} %c41, 0
  %r42 = extractvalue {i8, i1} %c42, 0
  %r43 = extractvalue {i8, i1} %c43, 0
  %r44 = extractvalue {i8, i1} %c44, 0
  %r45 = extractvalue {i8, i1} %c45, 0
  %r46 = extractvalue {i8, i1} %c46, 0
  %r47 = extractvalue {i8, i1} %c47, 0
  %r48 = extractvalue {i8, i1} %c48, 0
  %r49 = extractvalue {i8, i1} %c49, 0
  %r50 = extractvalue {i8, i1} %c50, 0
  %r51 = extractvalue {i8, i1} %c51, 0
  %r52 = extractvalue {i8, i1} %c52, 0
  %r53 = extractvalue {i8, i1} %c53, 0
  %r54 = extractvalue {i8, i1} %c54, 0
  %r55 = extractvalue {i8, i1} %c55, 0
  %r56 = extractvalue {i8, i1} %c56, 0
  %r57 = extractvalue {i8, i1} %c57, 0
  %r58 = extractvalue {i8, i1} %c58, 0
  %r59 = extractvalue {i8, i1} %c59, 0
  %r60 = extractvalue {i8, i1} %c60, 0
  %r61 = extractvalue {i8, i1} %c61, 0
  %r62 = extractvalue {i8, i1} %c62, 0
  %r63 = extractvalue {i8, i1} %c63, 0
  store i8 %r0 , ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 0 ), align 1
  store i8 %r1 , ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 1 ), align 1
  store i8 %r2 , ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 2 ), align 1
  store i8 %r3 , ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 3 ), align 1
  store i8 %r4 , ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 4 ), align 1
  store i8 %r5 , ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 5 ), align 1
  store i8 %r6 , ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 6 ), align 1
  store i8 %r7 , ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 7 ), align 1
  store i8 %r8 , ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 8 ), align 1
  store i8 %r9 , ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 9 ), align 1
  store i8 %r10, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 10), align 1
  store i8 %r11, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 11), align 1
  store i8 %r12, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 12), align 1
  store i8 %r13, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 13), align 1
  store i8 %r14, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 14), align 1
  store i8 %r15, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 15), align 1
  store i8 %r16, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 16), align 1
  store i8 %r17, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 17), align 1
  store i8 %r18, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 18), align 1
  store i8 %r19, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 19), align 1
  store i8 %r20, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 20), align 1
  store i8 %r21, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 21), align 1
  store i8 %r22, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 22), align 1
  store i8 %r23, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 23), align 1
  store i8 %r24, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 24), align 1
  store i8 %r25, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 25), align 1
  store i8 %r26, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 26), align 1
  store i8 %r27, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 27), align 1
  store i8 %r28, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 28), align 1
  store i8 %r29, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 29), align 1
  store i8 %r30, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 30), align 1
  store i8 %r31, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 31), align 1
  store i8 %r32, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 32), align 1
  store i8 %r33, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 33), align 1
  store i8 %r34, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 34), align 1
  store i8 %r35, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 35), align 1
  store i8 %r36, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 36), align 1
  store i8 %r37, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 37), align 1
  store i8 %r38, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 38), align 1
  store i8 %r39, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 39), align 1
  store i8 %r40, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 40), align 1
  store i8 %r41, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 41), align 1
  store i8 %r42, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 42), align 1
  store i8 %r43, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 43), align 1
  store i8 %r44, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 44), align 1
  store i8 %r45, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 45), align 1
  store i8 %r46, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 46), align 1
  store i8 %r47, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 47), align 1
  store i8 %r48, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 48), align 1
  store i8 %r49, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 49), align 1
  store i8 %r50, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 50), align 1
  store i8 %r51, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 51), align 1
  store i8 %r52, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 52), align 1
  store i8 %r53, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 53), align 1
  store i8 %r54, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 54), align 1
  store i8 %r55, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 55), align 1
  store i8 %r56, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 56), align 1
  store i8 %r57, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 57), align 1
  store i8 %r58, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 58), align 1
  store i8 %r59, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 59), align 1
  store i8 %r60, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 60), align 1
  store i8 %r61, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 61), align 1
  store i8 %r62, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 62), align 1
  store i8 %r63, ptr getelementptr inbounds ([64 x i8], ptr @c8, i32 0, i64 63), align 1
  ret void
}
