; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -slp-threshold=-99999 -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define void @test() {
; CHECK-LABEL: define void @test() {
; CHECK-NEXT:  [[BB:.*]]:
; CHECK-NEXT:    br i1 false, label %[[BB1:.*]], label %[[BB9:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[SHL4:%.*]] = shl i32 0, 0
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x i32> <i32 0, i32 poison, i32 poison, i32 poison>, i32 [[SHL4]], i32 1
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> <i32 0, i32 -1, i32 undef, i32 undef>, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>, <4 x i32> <i32 4, i32 5, i32 3, i32 2>
; CHECK-NEXT:    [[TMP3:%.*]] = add <4 x i32> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = ashr <4 x i32> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> [[TMP4]], <4 x i32> <i32 0, i32 5, i32 2, i32 3>
; CHECK-NEXT:    br label %[[BB6:.*]]
; CHECK:       [[BB6]]:
; CHECK-NEXT:    [[TMP6:%.*]] = phi <4 x i32> [ [[TMP5]], %[[BB1]] ]
; CHECK-NEXT:    br label %[[BB9]]
; CHECK:       [[BB9]]:
; CHECK-NEXT:    [[TMP7:%.*]] = phi <4 x i32> [ <i32 0, i32 0, i32 poison, i32 0>, %[[BB]] ], [ [[TMP6]], %[[BB6]] ]
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <4 x i32> [[TMP7]], i32 3
; CHECK-NEXT:    [[OR:%.*]] = or i32 [[TMP8]], 0
; CHECK-NEXT:    ret void
;
bb:
  br i1 false, label %bb1, label %bb9

bb1:
  %add = add i32 0, 0
  %shl = shl i32 %add, 0
  %sub = sub i32 0, 1
  %add2 = add i32 %sub, %shl
  %add3 = add i32 0, 0
  %shl4 = shl i32 %add3, 0
  %ashr = ashr i32 %shl4, 1
  %add5 = add i32 0, 0
  br label %bb6

bb6:
  %phi = phi i32 [ %add2, %bb1 ]
  %phi7 = phi i32 [ %ashr, %bb1 ]
  %phi8 = phi i32 [ %add5, %bb1 ]
  br label %bb9

bb9:
  %phi10 = phi i32 [ poison, %bb ], [ %phi, %bb6 ]
  %phi11 = phi i32 [ 0, %bb ], [ %phi7, %bb6 ]
  %phi12 = phi i32 [ 0, %bb ], [ %phi, %bb6 ]
  %phi13 = phi i32 [ 0, %bb ], [ %phi8, %bb6 ]
  %or = or i32 %phi12, 0
  ret void
}

