; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -slp-threshold=-99999 -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define void @test(i32 %arg) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i32 [[ARG:%.*]]) {
; CHECK-NEXT:  [[BB:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x i32> <i32 poison, i32 0>, i32 [[ARG]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = lshr <2 x i32> zeroinitializer, [[TMP0]]
; CHECK-NEXT:    [[TMP2:%.*]] = shl <2 x i32> zeroinitializer, [[TMP0]]
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP2]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP4:%.*]] = add <2 x i32> [[TMP3]], <i32 1, i32 0>
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <2 x i32> [[TMP3]], <2 x i32> [[TMP4]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP6:%.*]] = add <2 x i32> [[TMP5]], splat (i32 1)
; CHECK-NEXT:    [[TMP7:%.*]] = ashr <2 x i32> [[TMP5]], splat (i32 1)
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP6]], <2 x i32> [[TMP7]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    br label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    br i1 false, label %[[BB2:.*]], label %[[BB4:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[TMP9:%.*]] = phi <2 x i32> [ [[TMP8]], %[[BB1]] ], [ [[TMP14:%.*]], %[[BB4]] ]
; CHECK-NEXT:    ret void
; CHECK:       [[BB4]]:
; CHECK-NEXT:    [[TMP10:%.*]] = phi <2 x i32> [ [[TMP4]], %[[BB1]] ]
; CHECK-NEXT:    [[TMP11:%.*]] = lshr <2 x i32> [[TMP10]], zeroinitializer
; CHECK-NEXT:    [[TMP12:%.*]] = or <2 x i32> [[TMP10]], zeroinitializer
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <2 x i32> [[TMP11]], <2 x i32> [[TMP12]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP14]] = or <2 x i32> [[TMP13]], zeroinitializer
; CHECK-NEXT:    br label %[[BB2]]
;
bb:
  %lshr = lshr i32 0, %arg
  %add = add i32 %lshr, 1
  %shl = shl i32 0, 0
  %or = or i32 %shl, 0
  %ashr = ashr i32 %or, 1
  br label %bb1

bb1:
  br i1 false, label %bb2, label %bb4

bb2:
  %phi = phi i32 [ %add, %bb1 ], [ %or8, %bb4 ]
  %phi3 = phi i32 [ %ashr, %bb1 ], [ %ashr10, %bb4 ]
  ret void

bb4:
  %phi5 = phi i32 [ %add, %bb1 ]
  %phi6 = phi i32 [ %or, %bb1 ]
  %lshr7 = lshr i32 %phi5, 0
  %or8 = or i32 %lshr7, 0
  %or9 = or i32 %phi6, 0
  %ashr10 = ashr i32 %or9, 0
  br label %bb2
}
