; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu -slp-threshold=-1000 < %s | FileCheck %s

define i64 @test(ptr %buf) {
; CHECK-LABEL: define i64 @test(
; CHECK-SAME: ptr [[BUF:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[BUF]], align 1
; CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[TMP0]] to i64
; CHECK-NEXT:    [[MUL:%.*]] = mul i64 [[CONV]], 24
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds nuw i8, ptr [[BUF]], i64 1
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i8>, ptr [[ARRAYIDX1]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = zext <2 x i8> [[TMP1]] to <2 x i16>
; CHECK-NEXT:    [[TMP3:%.*]] = mul <2 x i16> [[TMP2]], <i16 16, i16 8>
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <2 x i16> [[TMP3]], i32 0
; CHECK-NEXT:    [[TMP5:%.*]] = zext i16 [[TMP4]] to i64
; CHECK-NEXT:    [[OR:%.*]] = or disjoint i64 [[TMP5]], [[MUL]]
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x i16> [[TMP3]], i32 1
; CHECK-NEXT:    [[TMP7:%.*]] = zext i16 [[TMP6]] to i64
; CHECK-NEXT:    [[OR7:%.*]] = or disjoint i64 [[OR]], [[TMP7]]
; CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds nuw i8, ptr [[BUF]], i64 3
; CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[ARRAYIDX8]], align 1
; CHECK-NEXT:    [[CONV9:%.*]] = zext i8 [[TMP8]] to i64
; CHECK-NEXT:    [[OR10:%.*]] = or disjoint i64 [[OR7]], [[CONV9]]
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[BUF]], i64 4
; CHECK-NEXT:    [[TMP9:%.*]] = load <2 x i8>, ptr [[ADD_PTR]], align 1
; CHECK-NEXT:    [[ARRAYIDX22:%.*]] = getelementptr inbounds nuw i8, ptr [[BUF]], i64 6
; CHECK-NEXT:    [[TMP10:%.*]] = load i8, ptr [[ARRAYIDX22]], align 1
; CHECK-NEXT:    [[CONV23:%.*]] = zext i8 [[TMP10]] to i64
; CHECK-NEXT:    [[TMP17:%.*]] = zext <2 x i8> [[TMP9]] to <2 x i64>
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <2 x i64> [[TMP17]], <2 x i64> poison, <4 x i32> <i32 1, i32 0, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP13:%.*]] = insertelement <4 x i64> [[TMP12]], i64 [[OR10]], i32 2
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <4 x i64> [[TMP13]], i64 [[CONV23]], i32 3
; CHECK-NEXT:    [[TMP15:%.*]] = mul <4 x i64> [[TMP14]], <i64 16, i64 24, i64 32, i64 8>
; CHECK-NEXT:    [[ARRAYIDX27:%.*]] = getelementptr inbounds nuw i8, ptr [[BUF]], i64 7
; CHECK-NEXT:    [[TMP16:%.*]] = load i8, ptr [[ARRAYIDX27]], align 1
; CHECK-NEXT:    [[CONV28:%.*]] = zext i8 [[TMP16]] to i64
; CHECK-NEXT:    [[TMP11:%.*]] = call i64 @llvm.vector.reduce.or.v4i64(<4 x i64> [[TMP15]])
; CHECK-NEXT:    [[OP_RDX:%.*]] = or disjoint i64 [[TMP11]], [[CONV28]]
; CHECK-NEXT:    ret i64 [[OP_RDX]]
;
entry:
  %0 = load i8, ptr %buf, align 1
  %conv = zext i8 %0 to i64
  %mul = mul i64 %conv, 24
  %arrayidx1 = getelementptr inbounds nuw i8, ptr %buf, i64 1
  %1 = load i8, ptr %arrayidx1, align 1
  %conv2 = zext i8 %1 to i64
  %mul3 = mul i64 %conv2, 16
  %or = or disjoint i64 %mul3, %mul
  %arrayidx4 = getelementptr inbounds nuw i8, ptr %buf, i64 2
  %2 = load i8, ptr %arrayidx4, align 1
  %conv5 = zext i8 %2 to i64
  %mul6 = mul i64 %conv5, 8
  %or7 = or disjoint i64 %or, %mul6
  %arrayidx8 = getelementptr inbounds nuw i8, ptr %buf, i64 3
  %3 = load i8, ptr %arrayidx8, align 1
  %conv9 = zext i8 %3 to i64
  %or10 = or disjoint i64 %or7, %conv9
  %mul12 = mul i64 %or10, 32
  %add.ptr = getelementptr inbounds nuw i8, ptr %buf, i64 4
  %4 = load i8, ptr %add.ptr, align 1
  %conv14 = zext i8 %4 to i64
  %mul15 = mul i64 %conv14, 24
  %arrayidx17 = getelementptr inbounds nuw i8, ptr %buf, i64 5
  %5 = load i8, ptr %arrayidx17, align 1
  %conv18 = zext i8 %5 to i64
  %mul19 = mul i64 %conv18, 16
  %or20 = or disjoint i64 %mul19, %mul15
  %arrayidx22 = getelementptr inbounds nuw i8, ptr %buf, i64 6
  %6 = load i8, ptr %arrayidx22, align 1
  %conv23 = zext i8 %6 to i64
  %mul24 = mul i64 %conv23, 8
  %arrayidx27 = getelementptr inbounds nuw i8, ptr %buf, i64 7
  %7 = load i8, ptr %arrayidx27, align 1
  %conv28 = zext i8 %7 to i64
  %or25 = or disjoint i64 %or20, %mul12
  %or29 = or disjoint i64 %or25, %mul24
  %add = or disjoint i64 %or29, %conv28
  ret i64 %add
}
