; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu -slp-threshold=-99999 < %s | FileCheck %s

define void @test(i32 %arg) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i32 [[ARG:%.*]]) {
; CHECK-NEXT:  [[BB:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x i32> <i32 0, i32 poison>, i32 [[ARG]], i32 1
; CHECK-NEXT:    br label %[[BB4:.*]]
; CHECK:       [[BB1:.*]]:
; CHECK-NEXT:    [[SUB2:%.*]] = sub i32 0, 0
; CHECK-NEXT:    [[OR:%.*]] = or i32 [[SUB2]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = sub <2 x i32> <i32 1, i32 0>, [[TMP0]]
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i32> <i32 0, i32 poison, i32 0, i32 0>, <4 x i32> [[TMP2]], <4 x i32> <i32 0, i32 5, i32 2, i32 3>
; CHECK-NEXT:    [[TMP4:%.*]] = add <4 x i32> zeroinitializer, [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> [[TMP4]], <4 x i32> <i32 0, i32 1, i32 6, i32 poison>
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[OR]], i32 3
; CHECK-NEXT:    br i1 false, label %[[BB8:.*]], label %[[BB4]]
; CHECK:       [[BB4]]:
; CHECK-NEXT:    [[TMP7:%.*]] = phi <4 x i32> [ zeroinitializer, %[[BB]] ], [ [[TMP4]], %[[BB1]] ]
; CHECK-NEXT:    [[TMP8:%.*]] = or <4 x i32> [[TMP7]], zeroinitializer
; CHECK-NEXT:    br i1 false, label %[[BB8]], label %[[BB1]]
; CHECK:       [[BB8]]:
; CHECK-NEXT:    [[TMP9:%.*]] = phi <4 x i32> [ [[TMP8]], %[[BB4]] ], [ [[TMP6]], %[[BB1]] ]
; CHECK-NEXT:    ret void
;
bb:
  br label %bb4

bb1:
  %sub = sub i32 0, %arg
  %sub2 = sub i32 0, 0
  %or = or i32 %sub2, 0
  %or3 = or i32 1, 0
  %add = add i32 0, 0
  br i1 false, label %bb8, label %bb4

bb4:
  %phi = phi i32 [ 0, %bb ], [ %add, %bb1 ]
  %phi5 = phi i32 [ 0, %bb ], [ %sub, %bb1 ]
  %phi6 = phi i32 [ 0, %bb ], [ 0, %bb1 ]
  %or7 = or i32 %phi6, 0
  br i1 false, label %bb8, label %bb1

bb8:
  %phi9 = phi i32 [ %phi5, %bb4 ], [ %sub, %bb1 ]
  %phi10 = phi i32 [ %phi, %bb4 ], [ %or, %bb1 ]
  %phi11 = phi i32 [ %or7, %bb4 ], [ %or3, %bb1 ]
  %phi12 = phi i32 [ %phi, %bb4 ], [ %add, %bb1 ]
  ret void
}

