; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux-gnu -slp-threshold=-9999 < %s | FileCheck %s

define void @test() {
; CHECK-LABEL: define void @test() {
; CHECK-NEXT:  [[BB:.*]]:
; CHECK-NEXT:    br label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi <4 x i32> [ <i32 poison, i32 poison, i32 0, i32 0>, %[[BB]] ], [ [[TMP6:%.*]], %[[BB14:.*]] ], [ <i32 poison, i32 poison, i32 0, i32 0>, %[[BB10:.*]] ]
; CHECK-NEXT:    br label %[[BB3:.*]]
; CHECK:       [[BB3]]:
; CHECK-NEXT:    [[TMP1:%.*]] = phi <2 x float> [ zeroinitializer, %[[BB1]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = phi <4 x i32> [ [[TMP0]], %[[BB1]] ]
; CHECK-NEXT:    br label %[[BB10]]
; CHECK:       [[BB10]]:
; CHECK-NEXT:    [[PHI11:%.*]] = phi i32 [ 0, %[[BB3]] ], [ [[PHI11]], %[[BB14]] ]
; CHECK-NEXT:    [[PHI12:%.*]] = phi float [ 0.000000e+00, %[[BB3]] ], [ 0.000000e+00, %[[BB14]] ]
; CHECK-NEXT:    [[PHI13:%.*]] = phi i32 [ 0, %[[BB3]] ], [ [[OR15:%.*]], %[[BB14]] ]
; CHECK-NEXT:    switch i32 0, label %[[BB14]] [
; CHECK-NEXT:      i32 0, label %[[BB1]]
; CHECK-NEXT:    ]
; CHECK:       [[BB14]]:
; CHECK-NEXT:    [[OR:%.*]] = or i32 [[PHI13]], [[PHI11]]
; CHECK-NEXT:    [[OR15]] = or i32 [[OR]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <4 x i32> poison, i32 [[PHI11]], i32 2
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP3]], i32 [[OR]], i32 3
; CHECK-NEXT:    [[TMP6]] = or <4 x i32> [[TMP5]], <i32 poison, i32 poison, i32 0, i32 0>
; CHECK-NEXT:    br i1 false, label %[[BB1]], label %[[BB10]]
;
bb:
  br label %bb1

bb1:
  %phi = phi i32 [ 0, %bb ], [ %or16, %bb14 ], [ 0, %bb10 ]
  %phi2 = phi i32 [ 0, %bb ], [ %or15, %bb14 ], [ 0, %bb10 ]
  br label %bb3

bb3:                                              ; preds = %bb1
  %phi4 = phi i32 [ poison, %bb1 ]
  %phi6 = phi i32 [ poison, %bb1 ]
  %phi7 = phi i32 [ %phi, %bb1 ]
  %phi9 = phi i32 [ %phi2, %bb1 ]
  %0 = phi <2 x float> [ zeroinitializer, %bb1 ]
  br label %bb10

bb10:
  %phi11 = phi i32 [ 0, %bb3 ], [ %phi11, %bb14 ]
  %phi12 = phi float [ 0.000000e+00, %bb3 ], [ 0.000000e+00, %bb14 ]
  %phi13 = phi i32 [ 0, %bb3 ], [ %or15, %bb14 ]
  switch i32 0, label %bb14 [
  i32 0, label %bb1
  ]

bb14:
  %or = or i32 %phi13, %phi11
  %or15 = or i32 %or, 0
  %or16 = or i32 %phi11, 0
  br i1 false, label %bb1, label %bb10
}
