; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -slp-threshold=-99999 -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define void @test(i32 %arg) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i32 [[ARG:%.*]]) {
; CHECK-NEXT:  [[BB:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x i32> <i32 0, i32 poison>, i32 [[ARG]], i32 1
; CHECK-NEXT:    [[TMP1:%.*]] = lshr <2 x i32> zeroinitializer, [[TMP0]]
; CHECK-NEXT:    [[TMP2:%.*]] = shl <2 x i32> zeroinitializer, [[TMP0]]
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP2]], <2 x i32> <i32 2, i32 1>
; CHECK-NEXT:    br label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[TMP4:%.*]] = phi <2 x i32> [ [[TMP16:%.*]], %[[BB8:.*]] ], [ zeroinitializer, %[[BB]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = phi <2 x i32> [ [[TMP13:%.*]], %[[BB8]] ], [ zeroinitializer, %[[BB]] ]
; CHECK-NEXT:    br i1 false, label %[[BB8]], label %[[BB4:.*]]
; CHECK:       [[BB4]]:
; CHECK-NEXT:    [[TMP6:%.*]] = lshr <2 x i32> [[TMP5]], zeroinitializer
; CHECK-NEXT:    [[TMP7:%.*]] = or <2 x i32> [[TMP5]], zeroinitializer
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP6]], <2 x i32> [[TMP7]], <2 x i32> <i32 2, i32 1>
; CHECK-NEXT:    [[TMP9:%.*]] = add <2 x i32> [[TMP8]], zeroinitializer
; CHECK-NEXT:    br label %[[BB5:.*]]
; CHECK:       [[BB5]]:
; CHECK-NEXT:    [[TMP10:%.*]] = phi <2 x i32> [ [[TMP9]], %[[BB4]] ]
; CHECK-NEXT:    br label %[[BB8]]
; CHECK:       [[BB8]]:
; CHECK-NEXT:    [[TMP11:%.*]] = phi <2 x i32> [ [[TMP4]], %[[BB1]] ], [ [[TMP10]], %[[BB5]] ]
; CHECK-NEXT:    [[TMP12:%.*]] = or <2 x i32> [[TMP3]], zeroinitializer
; CHECK-NEXT:    [[TMP13]] = or <2 x i32> [[TMP3]], <i32 0, i32 1>
; CHECK-NEXT:    [[TMP14:%.*]] = or <2 x i32> [[TMP12]], splat (i32 1)
; CHECK-NEXT:    [[TMP15:%.*]] = ashr <2 x i32> [[TMP12]], splat (i32 1)
; CHECK-NEXT:    [[TMP16]] = shufflevector <2 x i32> [[TMP14]], <2 x i32> [[TMP15]], <2 x i32> <i32 2, i32 1>
; CHECK-NEXT:    br label %[[BB1]]
;
bb:
  br label %bb1

bb1:                                              ; preds = %bb8, %bb
  %phi = phi i32 [ %ashr14, %bb8 ], [ 0, %bb ]
  %phi2 = phi i32 [ %or13, %bb8 ], [ 0, %bb ]
  %phi3 = phi i32 [ %or12, %bb8 ], [ 0, %bb ]
  br i1 false, label %bb8, label %bb4

bb4:                                              ; preds = %bb1
  %lshr = lshr i32 %phi3, 0
  %add = add i32 %lshr, 0
  %or = or i32 %phi2, 0
  %ashr = ashr i32 %or, 0
  br label %bb5

bb5:                                              ; preds = %bb4
  %phi6 = phi i32 [ %add, %bb4 ]
  %phi7 = phi i32 [ %ashr, %bb4 ]
  br label %bb8

bb8:                                              ; preds = %bb5, %bb1
  %phi9 = phi i32 [ %phi3, %bb1 ], [ %phi6, %bb5 ]
  %phi10 = phi i32 [ %phi, %bb1 ], [ %phi7, %bb5 ]
  %lshr11 = lshr i32 0, %arg
  %or12 = or i32 %lshr11, 1
  %shl = shl i32 0, 0
  %or13 = or i32 %shl, 0
  %ashr14 = ashr i32 %or13, 1
  br label %bb1
}
