; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux-gnu -mattr=+avx2 < %s | FileCheck %s

define void @test(i32 %a, ptr %out) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i32 [[A:%.*]], ptr [[OUT:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store i32 [[A]], ptr [[OUT]], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x i32> poison, i32 [[A]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = lshr <4 x i32> [[TMP1]], <i32 1, i32 2, i32 3, i32 4>
; CHECK-NEXT:    [[ARRAYIDX9_1:%.*]] = getelementptr inbounds nuw i8, ptr [[OUT]], i64 4
; CHECK-NEXT:    store <4 x i32> [[TMP2]], ptr [[ARRAYIDX9_1]], align 4
; CHECK-NEXT:    [[SHR_5:%.*]] = lshr i32 [[A]], 5
; CHECK-NEXT:    [[ARRAYIDX9_5:%.*]] = getelementptr inbounds nuw i8, ptr [[OUT]], i64 20
; CHECK-NEXT:    store i32 [[SHR_5]], ptr [[ARRAYIDX9_5]], align 4
; CHECK-NEXT:    [[SHR_6:%.*]] = lshr i32 [[A]], 6
; CHECK-NEXT:    [[ARRAYIDX9_6:%.*]] = getelementptr inbounds nuw i8, ptr [[OUT]], i64 24
; CHECK-NEXT:    store i32 [[SHR_6]], ptr [[ARRAYIDX9_6]], align 4
; CHECK-NEXT:    [[SHR_7:%.*]] = lshr i32 [[A]], 7
; CHECK-NEXT:    [[ARRAYIDX9_7:%.*]] = getelementptr inbounds nuw i8, ptr [[OUT]], i64 28
; CHECK-NEXT:    store i32 [[SHR_7]], ptr [[ARRAYIDX9_7]], align 4
; CHECK-NEXT:    ret void
;
entry:
  store i32 %a, ptr %out, align 4
  %shr.1 = lshr i32 %a, 1
  %arrayidx9.1 = getelementptr inbounds nuw i8, ptr %out, i64 4
  store i32 %shr.1, ptr %arrayidx9.1, align 4
  %shr.2 = lshr i32 %a, 2
  %arrayidx9.2 = getelementptr inbounds nuw i8, ptr %out, i64 8
  store i32 %shr.2, ptr %arrayidx9.2, align 4
  %shr.3 = lshr i32 %a, 3
  %arrayidx9.3 = getelementptr inbounds nuw i8, ptr %out, i64 12
  store i32 %shr.3, ptr %arrayidx9.3, align 4
  %shr.4 = lshr i32 %a, 4
  %arrayidx9.4 = getelementptr inbounds nuw i8, ptr %out, i64 16
  store i32 %shr.4, ptr %arrayidx9.4, align 4
  %shr.5 = lshr i32 %a, 5
  %arrayidx9.5 = getelementptr inbounds nuw i8, ptr %out, i64 20
  store i32 %shr.5, ptr %arrayidx9.5, align 4
  %shr.6 = lshr i32 %a, 6
  %arrayidx9.6 = getelementptr inbounds nuw i8, ptr %out, i64 24
  store i32 %shr.6, ptr %arrayidx9.6, align 4
  %shr.7 = lshr i32 %a, 7
  %arrayidx9.7 = getelementptr inbounds nuw i8, ptr %out, i64 28
  store i32 %shr.7, ptr %arrayidx9.7, align 4
  ret void
}

