; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu -slp-threshold=-99999 < %s | FileCheck %s

define void @test(i32 %arg) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i32 [[ARG:%.*]]) {
; CHECK-NEXT:  [[BB:.*:]]
; CHECK-NEXT:    br label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x i32> <i32 0, i32 0, i32 poison, i32 0>, i32 [[ARG]], i32 2
; CHECK-NEXT:    [[TMP1:%.*]] = sub <4 x i32> <i32 7, i32 7, i32 0, i32 7>, [[TMP0]]
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> <i32 0, i32 0, i32 poison, i32 0>, <4 x i32> <i32 4, i32 5, i32 2, i32 7>
; CHECK-NEXT:    [[TMP3:%.*]] = add <4 x i32> <i32 7, i32 0, i32 0, i32 0>, [[TMP4]]
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i32> [[TMP1]], i32 0
; CHECK-NEXT:    [[ICMP:%.*]] = icmp ult i32 [[TMP2]], 0
; CHECK-NEXT:    br i1 false, label %[[BB2:.*]], label %[[BB3:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    br label %[[BB3]]
; CHECK:       [[BB3]]:
; CHECK-NEXT:    [[TMP5:%.*]] = phi <4 x i32> [ [[TMP1]], %[[BB2]] ], [ [[TMP3]], %[[BB1]] ]
; CHECK-NEXT:    ret void
;
bb:
  br label %bb1

bb1:
  %sub = sub i32 0, %arg
  %add = add i32 7, 0
  %icmp = icmp ult i32 %add, 0
  br i1 false, label %bb2, label %bb3

bb2:
  br label %bb3

bb3:
  %phi = phi i32 [ 7, %bb2 ], [ 0, %bb1 ]
  %phi4 = phi i32 [ %sub, %bb2 ], [ %sub, %bb1 ]
  %phi5 = phi i32 [ %add, %bb2 ], [ %add, %bb1 ]
  %phi6 = phi i32 [ %add, %bb2 ], [ 0, %bb1 ]
  ret void
}
