; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu -slp-threshold=-100 < %s | FileCheck %s

define i8 @test(ptr %g_127, i32 %0, i16 %1) {
; CHECK-LABEL: define i8 @test(
; CHECK-SAME: ptr [[G_127:%.*]], i32 [[TMP0:%.*]], i16 [[TMP1:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_INC434_I:.*]]
; CHECK:       [[FOR_COND166_PREHEADER_I:.*]]:
; CHECK-NEXT:    br label %[[FOR_INC434_I]]
; CHECK:       [[FOR_INC434_I]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ 60, %[[FOR_COND166_PREHEADER_I]] ]
; CHECK-NEXT:    [[CONV8_I_I:%.*]] = zext nneg i32 [[TMP0]] to i64
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <3 x i64> poison, i64 [[CONV8_I_I]], i32 0
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <3 x i64> [[TMP3]], <3 x i64> poison, <3 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <3 x i64> poison, i64 [[TMP2]], i32 0
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <3 x i64> [[TMP5]], <3 x i64> poison, <3 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP7:%.*]] = udiv <3 x i64> [[TMP4]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = trunc <3 x i64> [[TMP7]] to <3 x i16>
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <3 x i16> [[TMP8]], <3 x i16> poison, <4 x i32> <i32 0, i32 1, i32 1, i32 2>
; CHECK-NEXT:    [[TMP10:%.*]] = call <4 x i16> @llvm.bswap.v4i16(<4 x i16> [[TMP9]])
; CHECK-NEXT:    [[TMP11:%.*]] = insertelement <2 x i64> poison, i64 [[CONV8_I_I]], i32 0
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <2 x i64> [[TMP11]], <2 x i64> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP13:%.*]] = insertelement <2 x i64> poison, i64 [[TMP2]], i32 0
; CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <2 x i64> [[TMP13]], <2 x i64> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP19:%.*]] = udiv <2 x i64> [[TMP12]], [[TMP14]]
; CHECK-NEXT:    [[TMP16:%.*]] = trunc <2 x i64> [[TMP19]] to <2 x i16>
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <2 x i16> [[TMP16]], <2 x i16> poison, <4 x i32> <i32 0, i32 0, i32 1, i32 1>
; CHECK-NEXT:    [[TMP18:%.*]] = call <4 x i16> @llvm.bswap.v4i16(<4 x i16> [[TMP17]])
; CHECK-NEXT:    [[RDX_OP:%.*]] = and <4 x i16> [[TMP10]], [[TMP18]]
; CHECK-NEXT:    [[TMP15:%.*]] = call i16 @llvm.vector.reduce.and.v4i16(<4 x i16> [[RDX_OP]])
; CHECK-NEXT:    [[OP_RDX:%.*]] = and i16 [[TMP15]], [[TMP1]]
; CHECK-NEXT:    [[AND14_I_2_I_5:%.*]] = zext i16 [[OP_RDX]] to i32
; CHECK-NEXT:    store i32 [[AND14_I_2_I_5]], ptr [[G_127]], align 4
; CHECK-NEXT:    ret i8 0
;
entry:
  br label %for.inc434.i

for.cond166.preheader.i:
  br label %for.inc434.i

for.inc434.i:
  %2 = phi i64 [ 0, %entry ], [ 60, %for.cond166.preheader.i ]
  %conv8.i.i = zext nneg i32 %0 to i64
  %div.i.i.1 = udiv i64 %conv8.i.i, %2
  %3 = trunc i64 %div.i.i.1 to i16
  %call12.i.2.i.1 = tail call i16 @llvm.bswap.i16(i16 %3)
  %and14.i.2.i.118 = and i16 %1, %call12.i.2.i.1
  %div.i.i.2 = udiv i64 %conv8.i.i, %2
  %4 = trunc i64 %div.i.i.2 to i16
  %call12.i.i.2 = tail call i16 @llvm.bswap.i16(i16 %4)
  %and14.i.i.219 = and i16 %and14.i.2.i.118, %call12.i.i.2
  %call12.i.2.i.2 = tail call i16 @llvm.bswap.i16(i16 %4)
  %and14.i.2.i.220 = and i16 %and14.i.i.219, %call12.i.2.i.2
  %div.i.i.3 = udiv i64 %conv8.i.i, %2
  %5 = trunc i64 %div.i.i.3 to i16
  %call12.i.2.i.3 = tail call i16 @llvm.bswap.i16(i16 %5)
  %and14.i.2.i.322 = and i16 %and14.i.2.i.220, %call12.i.2.i.3
  %div.i.i.4 = udiv i64 %conv8.i.i, %2
  %6 = trunc i64 %div.i.i.4 to i16
  %call12.i.i.4 = tail call i16 @llvm.bswap.i16(i16 %6)
  %and14.i.i.423 = and i16 %and14.i.2.i.322, %call12.i.i.4
  %call12.i.2.i.4 = tail call i16 @llvm.bswap.i16(i16 %6)
  %and14.i.2.i.424 = and i16 %and14.i.i.423, %call12.i.2.i.4
  %div.i.i.5 = udiv i64 %conv8.i.i, %2
  %7 = trunc i64 %div.i.i.5 to i16
  %call12.i.i.5 = tail call i16 @llvm.bswap.i16(i16 %7)
  %and14.i.i.525 = and i16 %and14.i.2.i.424, %call12.i.i.5
  %call12.i.2.i.5 = tail call i16 @llvm.bswap.i16(i16 %7)
  %and14.i.2.i.51 = and i16 %and14.i.i.525, %call12.i.2.i.5
  %and14.i.2.i.5 = zext i16 %and14.i.2.i.51 to i32
  store i32 %and14.i.2.i.5, ptr %g_127, align 4
  ret i8 0
}
