; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define i1 @test() {
; CHECK-LABEL: define i1 @test() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[E0:%.*]] = extractelement <4 x float> zeroinitializer, i64 0
; CHECK-NEXT:    [[E3:%.*]] = extractelement <4 x float> splat (float 3.000000e+00), i64 0
; CHECK-NEXT:    [[E4:%.*]] = extractelement <4 x float> splat (float 4.000000e+00), i64 0
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x float> <float 0.000000e+00, float 5.000000e+00, float undef, float undef>, float [[E4]], i32 2
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <4 x float> [[TMP0]], float [[E3]], i32 3
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <8 x float> <float undef, float undef, float undef, float undef, float 2.000000e+00, float 1.000000e+00, float 0.000000e+00, float undef>, float [[E0]], i32 7
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x float> [[TMP1]], <4 x float> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x float> [[TMP2]], <8 x float> [[TMP3]], <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP5:%.*]] = fpext <8 x float> [[TMP4]] to <8 x double>
; CHECK-NEXT:    [[TMP6:%.*]] = fmul <8 x double> zeroinitializer, [[TMP5]]
; CHECK-NEXT:    [[TMP7:%.*]] = select <8 x i1> zeroinitializer, <8 x double> [[TMP6]], <8 x double> zeroinitializer
; CHECK-NEXT:    [[TMP8:%.*]] = fcmp olt <8 x double> [[TMP7]], zeroinitializer
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <8 x i1> [[TMP8]], i32 0
; CHECK-NEXT:    ret i1 [[TMP9]]
;
entry:
  %e0 = extractelement <4 x float> splat (float 0.0), i64 0
  %c1 = fpext float %e0 to double
  %m1 = fmul double 0.0, %c1
  %s1 = select i1 false, double %m1, double 0.0
  %r1 = fcmp olt double %s1, 0.0

  %c2 = fpext float 0.0 to double
  %m2 = fmul double 0.0, %c2
  %s2 = select i1 false, double %m2, double 0.0
  %r2 = fcmp olt double %s2, 0.0

  %e1 = extractelement <4 x float> splat (float 1.0), i64 0
  %c3 = fpext float %e1 to double
  %m3 = fmul double 0.0, %c3
  %s3 = select i1 false, double %m3, double 0.0
  %r3 = fcmp olt double %s3, 0.0

  %e2 = extractelement <4 x float> splat (float 2.0), i64 0
  %c4 = fpext float %e2 to double
  %m4 = fmul double 0.0, %c4
  %s4 = select i1 false, double %m4, double 0.0
  %r4 = fcmp olt double %s4, 0.0

  %e3 = extractelement <4 x float> splat (float 3.0), i64 0
  %c5 = fpext float %e3 to double
  %m5 = fmul double 0.0, %c5
  %s5 = select i1 false, double %m5, double 0.0
  %r5 = fcmp olt double %s5, 0.0

  %e4 = extractelement <4 x float> splat (float 4.0), i64 0
  %c6 = fpext float %e4 to double
  %m6 = fmul double 0.0, %c6
  %s6 = select i1 false, double %m6, double 0.0
  %r6 = fcmp olt double %s6, 0.0

  %e5 = extractelement <4 x float> splat (float 5.0), i64 0
  %c7 = fpext float %e5 to double
  %m7 = fmul double 0.0, %c7
  %s7 = select i1 false, double %m7, double 0.0
  %r7 = fcmp olt double %s7, 0.0

  %m8 = fmul double 0.0, %c1
  %s8 = select i1 false, double %m8, double 0.0
  %r8 = fcmp olt double %s8, 0.0

  ret i1 %r8
}
