; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define i16 @test(i64 %0) {
; CHECK-LABEL: define i16 @test(
; CHECK-SAME: i64 [[TMP0:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <8 x i64> poison, i64 [[TMP0]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i64> [[TMP1]], <8 x i64> poison, <8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP3:%.*]] = icmp ne <8 x i64> [[TMP2]], zeroinitializer
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq <8 x i64> [[TMP2]], zeroinitializer
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x i1> [[TMP3]], <8 x i1> [[TMP4]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 15>
; CHECK-NEXT:    [[TMP9:%.*]] = select <8 x i1> [[TMP8]], <8 x i16> splat (i16 1), <8 x i16> <i16 0, i16 0, i16 0, i16 0, i16 0, i16 0, i16 0, i16 2>
; CHECK-NEXT:    [[TMP10:%.*]] = call i16 @llvm.vector.reduce.add.v8i16(<8 x i16> [[TMP9]])
; CHECK-NEXT:    ret i16 [[TMP10]]
;
entry:
  %cmp12.not.not = icmp eq i64 %0, 0
  %conv38 = select i1 %cmp12.not.not, i16 1, i16 2
  %cmp80 = icmp ne i64 %0, 0
  %cond82 = zext i1 %cmp80 to i16
  %conv89 = add i16 %conv38, %cond82
  %cmp96 = icmp ne i64 %0, 0
  %cond98 = zext i1 %cmp96 to i16
  %conv105 = add i16 %conv89, %cond98
  %cmp112 = icmp ne i64 %0, 0
  %cond114 = zext i1 %cmp112 to i16
  %conv121 = add i16 %conv105, %cond114
  %cmp128 = icmp ne i64 %0, 0
  %cond130 = zext i1 %cmp128 to i16
  %conv137 = add i16 %conv121, %cond130
  %cmp144 = icmp ne i64 %0, 0
  %cond146 = zext i1 %cmp144 to i16
  %conv153 = add i16 %conv137, %cond146
  %cmp160 = icmp ne i64 %0, 0
  %cond162 = zext i1 %cmp160 to i16
  %conv169 = add i16 %conv153, %cond162
  %cmp176 = icmp ne i64 %0, 0
  %cond178 = zext i1 %cmp176 to i16
  %conv185 = add i16 %conv169, %cond178
  ret i16 %conv185
}
