; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define i64 @test() {
; CHECK-LABEL: define i64 @test() {
; CHECK-NEXT:  [[BB:.*]]:
; CHECK-NEXT:    [[SHL:%.*]] = shl i32 0, 1
; CHECK-NEXT:    [[ADD1:%.*]] = add i32 0, 1
; CHECK-NEXT:    br label %[[BB2:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i32 [ [[SHL]], %[[BB]] ]
; CHECK-NEXT:    [[PHI3:%.*]] = phi i32 [ 0, %[[BB]] ]
; CHECK-NEXT:    [[PHI4:%.*]] = phi i32 [ 0, %[[BB]] ]
; CHECK-NEXT:    [[PHI5:%.*]] = phi i32 [ [[ADD1]], %[[BB]] ]
; CHECK-NEXT:    ret i64 0
;
bb:
  %shl = shl i32 0, 1
  %mul = mul i32 0, 0
  %add = add i32 0, 0
  %add1 = add i32 0, 1
  br label %bb2

bb2:
  %phi = phi i32 [ %shl, %bb ]
  %phi3 = phi i32 [ %add, %bb ]
  %phi4 = phi i32 [ %mul, %bb ]
  %phi5 = phi i32 [ %add1, %bb ]
  ret i64 0
}
