; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define void @test() {
; CHECK-LABEL: define void @test() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr null, align 1
; CHECK-NEXT:    [[ARRAYIDX13_8_I:%.*]] = getelementptr i8, ptr null, i64 16
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr null, align 1
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr null, align 1
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr null, align 1
; CHECK-NEXT:    [[TMP12:%.*]] = load i8, ptr null, align 1
; CHECK-NEXT:    [[TMP15:%.*]] = load i8, ptr null, align 1
; CHECK-NEXT:    [[TMP18:%.*]] = load i8, ptr null, align 1
; CHECK-NEXT:    [[TMP21:%.*]] = load i8, ptr null, align 1
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <16 x i8> poison, i8 [[TMP0]], i32 0
; CHECK-NEXT:    [[TMP20:%.*]] = insertelement <16 x i8> [[TMP8]], i8 [[TMP3]], i32 1
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <16 x i8> [[TMP20]], i8 [[TMP6]], i32 2
; CHECK-NEXT:    [[TMP11:%.*]] = insertelement <16 x i8> [[TMP10]], i8 [[TMP9]], i32 3
; CHECK-NEXT:    [[TMP22:%.*]] = insertelement <16 x i8> [[TMP11]], i8 [[TMP12]], i32 4
; CHECK-NEXT:    [[TMP13:%.*]] = insertelement <16 x i8> [[TMP22]], i8 [[TMP15]], i32 5
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <16 x i8> [[TMP13]], i8 [[TMP18]], i32 6
; CHECK-NEXT:    [[TMP23:%.*]] = insertelement <16 x i8> [[TMP14]], i8 [[TMP21]], i32 7
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <16 x i8> [[TMP23]], <16 x i8> poison, <16 x i32> <i32 0, i32 0, i32 1, i32 1, i32 2, i32 2, i32 3, i32 3, i32 4, i32 4, i32 5, i32 5, i32 6, i32 6, i32 7, i32 7>
; CHECK-NEXT:    [[TMP17:%.*]] = icmp ult <16 x i8> [[TMP16]], zeroinitializer
; CHECK-NEXT:    [[TMP24:%.*]] = and <16 x i8> [[TMP16]], <i8 -1, i8 0, i8 -1, i8 0, i8 -1, i8 0, i8 -1, i8 0, i8 -1, i8 0, i8 -1, i8 0, i8 -1, i8 0, i8 -1, i8 0>
; CHECK-NEXT:    [[TMP19:%.*]] = select <16 x i1> [[TMP17]], <16 x i8> zeroinitializer, <16 x i8> [[TMP24]]
; CHECK-NEXT:    store <16 x i8> [[TMP19]], ptr [[ARRAYIDX13_8_I]], align 1
; CHECK-NEXT:    ret void
;
entry:
  %0 = load i8, ptr null, align 1
  %cmp8.8.i = icmp ult i8 %0, 0
  %1 = lshr i8 %0, 0
  %narrow.8.i = select i1 %cmp8.8.i, i8 0, i8 %1
  %arrayidx13.8.i = getelementptr i8, ptr null, i64 16
  store i8 %narrow.8.i, ptr %arrayidx13.8.i, align 1
  %cmp15.8.i = icmp ult i8 %0, 0
  %2 = and i8 %0, 0
  %narrow31.8.i = select i1 %cmp15.8.i, i8 0, i8 %2
  %arrayidx25.8.i = getelementptr i8, ptr null, i64 17
  store i8 %narrow31.8.i, ptr %arrayidx25.8.i, align 1
  %3 = load i8, ptr null, align 1
  %cmp8.9.i = icmp ult i8 %3, 0
  %4 = lshr i8 %3, 0
  %narrow.9.i = select i1 %cmp8.9.i, i8 0, i8 %4
  %arrayidx13.9.i = getelementptr i8, ptr null, i64 18
  store i8 %narrow.9.i, ptr %arrayidx13.9.i, align 1
  %cmp15.9.i = icmp ult i8 %3, 0
  %5 = and i8 %3, 0
  %narrow31.9.i = select i1 %cmp15.9.i, i8 0, i8 %5
  %arrayidx25.9.i = getelementptr i8, ptr null, i64 19
  store i8 %narrow31.9.i, ptr %arrayidx25.9.i, align 1
  %6 = load i8, ptr null, align 1
  %cmp8.10.i = icmp ult i8 %6, 0
  %7 = lshr i8 %6, 0
  %narrow.10.i = select i1 %cmp8.10.i, i8 0, i8 %7
  %arrayidx13.10.i = getelementptr i8, ptr null, i64 20
  store i8 %narrow.10.i, ptr %arrayidx13.10.i, align 1
  %cmp15.10.i = icmp ult i8 %6, 0
  %8 = and i8 %6, 0
  %narrow31.10.i = select i1 %cmp15.10.i, i8 0, i8 %8
  %arrayidx25.10.i = getelementptr i8, ptr null, i64 21
  store i8 %narrow31.10.i, ptr %arrayidx25.10.i, align 1
  %9 = load i8, ptr null, align 1
  %cmp8.11.i = icmp ult i8 %9, 0
  %10 = lshr i8 %9, 0
  %narrow.11.i = select i1 %cmp8.11.i, i8 0, i8 %10
  %arrayidx13.11.i = getelementptr i8, ptr null, i64 22
  store i8 %narrow.11.i, ptr %arrayidx13.11.i, align 1
  %cmp15.11.i = icmp ult i8 %9, 0
  %11 = and i8 %9, 0
  %narrow31.11.i = select i1 %cmp15.11.i, i8 0, i8 %11
  %arrayidx25.11.i = getelementptr i8, ptr null, i64 23
  store i8 %narrow31.11.i, ptr %arrayidx25.11.i, align 1
  %12 = load i8, ptr null, align 1
  %cmp8.12.i = icmp ult i8 %12, 0
  %13 = lshr i8 %12, 0
  %narrow.12.i = select i1 %cmp8.12.i, i8 0, i8 %13
  %arrayidx13.12.i = getelementptr i8, ptr null, i64 24
  store i8 %narrow.12.i, ptr %arrayidx13.12.i, align 1
  %cmp15.12.i = icmp ult i8 %12, 0
  %14 = and i8 %12, 0
  %narrow31.12.i = select i1 %cmp15.12.i, i8 0, i8 %14
  %arrayidx25.12.i = getelementptr i8, ptr null, i64 25
  store i8 %narrow31.12.i, ptr %arrayidx25.12.i, align 1
  %15 = load i8, ptr null, align 1
  %cmp8.13.i = icmp ult i8 %15, 0
  %16 = lshr i8 %15, 0
  %narrow.13.i = select i1 %cmp8.13.i, i8 0, i8 %16
  %arrayidx13.13.i = getelementptr i8, ptr null, i64 26
  store i8 %narrow.13.i, ptr %arrayidx13.13.i, align 1
  %cmp15.13.i = icmp ult i8 %15, 0
  %17 = and i8 %15, 0
  %narrow31.13.i = select i1 %cmp15.13.i, i8 0, i8 %17
  %arrayidx25.13.i = getelementptr i8, ptr null, i64 27
  store i8 %narrow31.13.i, ptr %arrayidx25.13.i, align 1
  %18 = load i8, ptr null, align 1
  %cmp8.14.i = icmp ult i8 %18, 0
  %19 = lshr i8 %18, 0
  %narrow.14.i = select i1 %cmp8.14.i, i8 0, i8 %19
  %arrayidx13.14.i = getelementptr i8, ptr null, i64 28
  store i8 %narrow.14.i, ptr %arrayidx13.14.i, align 1
  %cmp15.14.i = icmp ult i8 %18, 0
  %20 = and i8 %18, 0
  %narrow31.14.i = select i1 %cmp15.14.i, i8 0, i8 %20
  %arrayidx25.14.i = getelementptr i8, ptr null, i64 29
  store i8 %narrow31.14.i, ptr %arrayidx25.14.i, align 1
  %21 = load i8, ptr null, align 1
  %cmp8.15.i = icmp ult i8 %21, 0
  %22 = lshr i8 %21, 0
  %narrow.15.i = select i1 %cmp8.15.i, i8 0, i8 %22
  %arrayidx13.15.i = getelementptr i8, ptr null, i64 30
  store i8 %narrow.15.i, ptr %arrayidx13.15.i, align 1
  %cmp15.15.i = icmp ult i8 %21, 0
  %23 = and i8 %21, 0
  %narrow31.15.i = select i1 %cmp15.15.i, i8 0, i8 %23
  %arrayidx25.15.i = getelementptr i8, ptr null, i64 31
  store i8 %narrow31.15.i, ptr %arrayidx25.15.i, align 1
  ret void
}
