; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=x86_64 -mcpu=skylake-avx512 -passes=slp-vectorizer -S < %s | FileCheck %s

define void @const_stride_2_i8(ptr %pl, ptr %ps) {
; CHECK-LABEL: define void @const_stride_2_i8(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[L:%.*]] = load <8 x i8>, ptr [[PL]], align 1
; CHECK-NEXT:    [[E0:%.*]] = extractelement <8 x i8> [[L]], i32 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <8 x i8> [[L]], i32 1
; CHECK-NEXT:    [[E2:%.*]] = extractelement <8 x i8> [[L]], i32 2
; CHECK-NEXT:    [[E3:%.*]] = extractelement <8 x i8> [[L]], i32 3
; CHECK-NEXT:    [[E4:%.*]] = extractelement <8 x i8> [[L]], i32 4
; CHECK-NEXT:    [[E5:%.*]] = extractelement <8 x i8> [[L]], i32 5
; CHECK-NEXT:    [[E6:%.*]] = extractelement <8 x i8> [[L]], i32 6
; CHECK-NEXT:    [[E7:%.*]] = extractelement <8 x i8> [[L]], i32 7
; CHECK-NEXT:    [[S0:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 0
; CHECK-NEXT:    [[S1:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 2
; CHECK-NEXT:    [[S2:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 4
; CHECK-NEXT:    [[S3:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 6
; CHECK-NEXT:    [[S4:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 8
; CHECK-NEXT:    [[S5:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 10
; CHECK-NEXT:    [[S6:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 12
; CHECK-NEXT:    [[S7:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 14
; CHECK-NEXT:    store i8 [[E0]], ptr [[S0]], align 1
; CHECK-NEXT:    store i8 [[E1]], ptr [[S1]], align 1
; CHECK-NEXT:    store i8 [[E2]], ptr [[S2]], align 1
; CHECK-NEXT:    store i8 [[E3]], ptr [[S3]], align 1
; CHECK-NEXT:    store i8 [[E4]], ptr [[S4]], align 1
; CHECK-NEXT:    store i8 [[E5]], ptr [[S5]], align 1
; CHECK-NEXT:    store i8 [[E6]], ptr [[S6]], align 1
; CHECK-NEXT:    store i8 [[E7]], ptr [[S7]], align 1
; CHECK-NEXT:    ret void
;
  %l = load <8 x i8>, ptr %pl, align 1
  %e0 = extractelement <8 x i8> %l, i32 0
  %e1 = extractelement <8 x i8> %l, i32 1
  %e2 = extractelement <8 x i8> %l, i32 2
  %e3 = extractelement <8 x i8> %l, i32 3
  %e4 = extractelement <8 x i8> %l, i32 4
  %e5 = extractelement <8 x i8> %l, i32 5
  %e6 = extractelement <8 x i8> %l, i32 6
  %e7 = extractelement <8 x i8> %l, i32 7
  %s0 = getelementptr inbounds i8, ptr %ps, i64 0
  %s1 = getelementptr inbounds i8, ptr %ps, i64 2
  %s2 = getelementptr inbounds i8, ptr %ps, i64 4
  %s3 = getelementptr inbounds i8, ptr %ps, i64 6
  %s4 = getelementptr inbounds i8, ptr %ps, i64 8
  %s5 = getelementptr inbounds i8, ptr %ps, i64 10
  %s6 = getelementptr inbounds i8, ptr %ps, i64 12
  %s7 = getelementptr inbounds i8, ptr %ps, i64 14
  store i8 %e0, ptr %s0
  store i8 %e1, ptr %s1
  store i8 %e2, ptr %s2
  store i8 %e3, ptr %s3
  store i8 %e4, ptr %s4
  store i8 %e5, ptr %s5
  store i8 %e6, ptr %s6
  store i8 %e7, ptr %s7
  ret void
}

define void @const_stride_2_i32(ptr %pl, ptr %ps) {
; CHECK-LABEL: define void @const_stride_2_i32(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[L:%.*]] = load <8 x i32>, ptr [[PL]], align 4
; CHECK-NEXT:    [[E0:%.*]] = extractelement <8 x i32> [[L]], i32 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <8 x i32> [[L]], i32 1
; CHECK-NEXT:    [[E2:%.*]] = extractelement <8 x i32> [[L]], i32 2
; CHECK-NEXT:    [[E3:%.*]] = extractelement <8 x i32> [[L]], i32 3
; CHECK-NEXT:    [[E4:%.*]] = extractelement <8 x i32> [[L]], i32 4
; CHECK-NEXT:    [[E5:%.*]] = extractelement <8 x i32> [[L]], i32 5
; CHECK-NEXT:    [[E6:%.*]] = extractelement <8 x i32> [[L]], i32 6
; CHECK-NEXT:    [[E7:%.*]] = extractelement <8 x i32> [[L]], i32 7
; CHECK-NEXT:    [[S0:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 0
; CHECK-NEXT:    [[S1:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 2
; CHECK-NEXT:    [[S2:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 4
; CHECK-NEXT:    [[S3:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 6
; CHECK-NEXT:    [[S4:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 8
; CHECK-NEXT:    [[S5:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 10
; CHECK-NEXT:    [[S6:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 12
; CHECK-NEXT:    [[S7:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 14
; CHECK-NEXT:    store i32 [[E0]], ptr [[S0]], align 4
; CHECK-NEXT:    store i32 [[E1]], ptr [[S1]], align 4
; CHECK-NEXT:    store i32 [[E2]], ptr [[S2]], align 4
; CHECK-NEXT:    store i32 [[E3]], ptr [[S3]], align 4
; CHECK-NEXT:    store i32 [[E4]], ptr [[S4]], align 4
; CHECK-NEXT:    store i32 [[E5]], ptr [[S5]], align 4
; CHECK-NEXT:    store i32 [[E6]], ptr [[S6]], align 4
; CHECK-NEXT:    store i32 [[E7]], ptr [[S7]], align 4
; CHECK-NEXT:    ret void
;
  %l = load <8 x i32>, ptr %pl, align 4
  %e0 = extractelement <8 x i32> %l, i32 0
  %e1 = extractelement <8 x i32> %l, i32 1
  %e2 = extractelement <8 x i32> %l, i32 2
  %e3 = extractelement <8 x i32> %l, i32 3
  %e4 = extractelement <8 x i32> %l, i32 4
  %e5 = extractelement <8 x i32> %l, i32 5
  %e6 = extractelement <8 x i32> %l, i32 6
  %e7 = extractelement <8 x i32> %l, i32 7
  %s0 = getelementptr inbounds i32, ptr %ps, i64 0
  %s1 = getelementptr inbounds i32, ptr %ps, i64 2
  %s2 = getelementptr inbounds i32, ptr %ps, i64 4
  %s3 = getelementptr inbounds i32, ptr %ps, i64 6
  %s4 = getelementptr inbounds i32, ptr %ps, i64 8
  %s5 = getelementptr inbounds i32, ptr %ps, i64 10
  %s6 = getelementptr inbounds i32, ptr %ps, i64 12
  %s7 = getelementptr inbounds i32, ptr %ps, i64 14
  store i32 %e0, ptr %s0
  store i32 %e1, ptr %s1
  store i32 %e2, ptr %s2
  store i32 %e3, ptr %s3
  store i32 %e4, ptr %s4
  store i32 %e5, ptr %s5
  store i32 %e6, ptr %s6
  store i32 %e7, ptr %s7
  ret void
}

define void @consecutive_present_no_masked(ptr %p, i32 %x1, i32 %x3) {
; CHECK-LABEL: define void @consecutive_present_no_masked(
; CHECK-SAME: ptr [[P:%.*]], i32 [[X1:%.*]], i32 [[X3:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[SRC0:%.*]] = getelementptr inbounds i32, ptr [[P]], i64 0
; CHECK-NEXT:    [[SRC2:%.*]] = getelementptr inbounds i32, ptr [[P]], i64 2
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr [[SRC0]], align 4
; CHECK-NEXT:    [[V2:%.*]] = load i32, ptr [[SRC2]], align 4
; CHECK-NEXT:    [[NEG0:%.*]] = sub nsw i32 0, [[V0]]
; CHECK-NEXT:    [[NEG2:%.*]] = sub nsw i32 0, [[V2]]
; CHECK-NEXT:    [[S0:%.*]] = getelementptr inbounds i32, ptr [[P]], i64 64
; CHECK-NEXT:    [[S1:%.*]] = getelementptr inbounds i32, ptr [[P]], i64 65
; CHECK-NEXT:    [[S2:%.*]] = getelementptr inbounds i32, ptr [[P]], i64 66
; CHECK-NEXT:    [[S3:%.*]] = getelementptr inbounds i32, ptr [[P]], i64 67
; CHECK-NEXT:    store i32 [[NEG0]], ptr [[S0]], align 4
; CHECK-NEXT:    store i32 [[X1]], ptr [[S1]], align 4
; CHECK-NEXT:    store i32 [[NEG2]], ptr [[S2]], align 4
; CHECK-NEXT:    store i32 [[X3]], ptr [[S3]], align 4
; CHECK-NEXT:    ret void
;
  %src0 = getelementptr inbounds i32, ptr %p, i64 0
  %src2 = getelementptr inbounds i32, ptr %p, i64 2
  %v0 = load i32, ptr %src0, align 4
  %v2 = load i32, ptr %src2, align 4
  %neg0 = sub nsw i32 0, %v0
  %neg2 = sub nsw i32 0, %v2
  %s0 = getelementptr inbounds i32, ptr %p, i64 64
  %s1 = getelementptr inbounds i32, ptr %p, i64 65
  %s2 = getelementptr inbounds i32, ptr %p, i64 66
  %s3 = getelementptr inbounds i32, ptr %p, i64 67
  store i32 %neg0, ptr %s0, align 4
  store i32 %x1, ptr %s1, align 4
  store i32 %neg2, ptr %s2, align 4
  store i32 %x3, ptr %s3, align 4
  ret void
}

define void @const_stride_2_i32_zext_value(ptr %pl, ptr %ps) {
; CHECK-LABEL: define void @const_stride_2_i32_zext_value(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[L:%.*]] = load <8 x i8>, ptr [[PL]], align 1
; CHECK-NEXT:    [[E0:%.*]] = extractelement <8 x i8> [[L]], i32 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <8 x i8> [[L]], i32 1
; CHECK-NEXT:    [[E2:%.*]] = extractelement <8 x i8> [[L]], i32 2
; CHECK-NEXT:    [[E3:%.*]] = extractelement <8 x i8> [[L]], i32 3
; CHECK-NEXT:    [[E4:%.*]] = extractelement <8 x i8> [[L]], i32 4
; CHECK-NEXT:    [[E5:%.*]] = extractelement <8 x i8> [[L]], i32 5
; CHECK-NEXT:    [[E6:%.*]] = extractelement <8 x i8> [[L]], i32 6
; CHECK-NEXT:    [[E7:%.*]] = extractelement <8 x i8> [[L]], i32 7
; CHECK-NEXT:    [[Z0:%.*]] = zext i8 [[E0]] to i32
; CHECK-NEXT:    [[Z1:%.*]] = zext i8 [[E1]] to i32
; CHECK-NEXT:    [[Z2:%.*]] = zext i8 [[E2]] to i32
; CHECK-NEXT:    [[Z3:%.*]] = zext i8 [[E3]] to i32
; CHECK-NEXT:    [[Z4:%.*]] = zext i8 [[E4]] to i32
; CHECK-NEXT:    [[Z5:%.*]] = zext i8 [[E5]] to i32
; CHECK-NEXT:    [[Z6:%.*]] = zext i8 [[E6]] to i32
; CHECK-NEXT:    [[Z7:%.*]] = zext i8 [[E7]] to i32
; CHECK-NEXT:    [[S0:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 0
; CHECK-NEXT:    [[S1:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 2
; CHECK-NEXT:    [[S2:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 4
; CHECK-NEXT:    [[S3:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 6
; CHECK-NEXT:    [[S4:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 8
; CHECK-NEXT:    [[S5:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 10
; CHECK-NEXT:    [[S6:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 12
; CHECK-NEXT:    [[S7:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 14
; CHECK-NEXT:    store i32 [[Z0]], ptr [[S0]], align 4
; CHECK-NEXT:    store i32 [[Z1]], ptr [[S1]], align 4
; CHECK-NEXT:    store i32 [[Z2]], ptr [[S2]], align 4
; CHECK-NEXT:    store i32 [[Z3]], ptr [[S3]], align 4
; CHECK-NEXT:    store i32 [[Z4]], ptr [[S4]], align 4
; CHECK-NEXT:    store i32 [[Z5]], ptr [[S5]], align 4
; CHECK-NEXT:    store i32 [[Z6]], ptr [[S6]], align 4
; CHECK-NEXT:    store i32 [[Z7]], ptr [[S7]], align 4
; CHECK-NEXT:    ret void
;
  %l = load <8 x i8>, ptr %pl, align 1
  %e0 = extractelement <8 x i8> %l, i32 0
  %e1 = extractelement <8 x i8> %l, i32 1
  %e2 = extractelement <8 x i8> %l, i32 2
  %e3 = extractelement <8 x i8> %l, i32 3
  %e4 = extractelement <8 x i8> %l, i32 4
  %e5 = extractelement <8 x i8> %l, i32 5
  %e6 = extractelement <8 x i8> %l, i32 6
  %e7 = extractelement <8 x i8> %l, i32 7
  %z0 = zext i8 %e0 to i32
  %z1 = zext i8 %e1 to i32
  %z2 = zext i8 %e2 to i32
  %z3 = zext i8 %e3 to i32
  %z4 = zext i8 %e4 to i32
  %z5 = zext i8 %e5 to i32
  %z6 = zext i8 %e6 to i32
  %z7 = zext i8 %e7 to i32
  %s0 = getelementptr inbounds i32, ptr %ps, i64 0
  %s1 = getelementptr inbounds i32, ptr %ps, i64 2
  %s2 = getelementptr inbounds i32, ptr %ps, i64 4
  %s3 = getelementptr inbounds i32, ptr %ps, i64 6
  %s4 = getelementptr inbounds i32, ptr %ps, i64 8
  %s5 = getelementptr inbounds i32, ptr %ps, i64 10
  %s6 = getelementptr inbounds i32, ptr %ps, i64 12
  %s7 = getelementptr inbounds i32, ptr %ps, i64 14
  store i32 %z0, ptr %s0
  store i32 %z1, ptr %s1
  store i32 %z2, ptr %s2
  store i32 %z3, ptr %s3
  store i32 %z4, ptr %s4
  store i32 %z5, ptr %s5
  store i32 %z6, ptr %s6
  store i32 %z7, ptr %s7
  ret void
}

define void @const_stride_2_i32_add_value(ptr %pl, ptr %ps) {
; CHECK-LABEL: define void @const_stride_2_i32_add_value(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[L:%.*]] = load <8 x i8>, ptr [[PL]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = zext <8 x i8> [[L]] to <8 x i16>
; CHECK-NEXT:    [[TMP2:%.*]] = add <8 x i16> [[TMP1]], splat (i16 5)
; CHECK-NEXT:    [[S0:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 0
; CHECK-NEXT:    [[S1:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 2
; CHECK-NEXT:    [[S2:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 4
; CHECK-NEXT:    [[S3:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 6
; CHECK-NEXT:    [[S4:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 8
; CHECK-NEXT:    [[S5:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 10
; CHECK-NEXT:    [[S6:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 12
; CHECK-NEXT:    [[S7:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 14
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <8 x i16> [[TMP2]], i32 0
; CHECK-NEXT:    [[TMP4:%.*]] = zext i16 [[TMP3]] to i32
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[S0]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <8 x i16> [[TMP2]], i32 1
; CHECK-NEXT:    [[TMP6:%.*]] = zext i16 [[TMP5]] to i32
; CHECK-NEXT:    store i32 [[TMP6]], ptr [[S1]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <8 x i16> [[TMP2]], i32 2
; CHECK-NEXT:    [[TMP8:%.*]] = zext i16 [[TMP7]] to i32
; CHECK-NEXT:    store i32 [[TMP8]], ptr [[S2]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <8 x i16> [[TMP2]], i32 3
; CHECK-NEXT:    [[TMP10:%.*]] = zext i16 [[TMP9]] to i32
; CHECK-NEXT:    store i32 [[TMP10]], ptr [[S3]], align 4
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <8 x i16> [[TMP2]], i32 4
; CHECK-NEXT:    [[TMP12:%.*]] = zext i16 [[TMP11]] to i32
; CHECK-NEXT:    store i32 [[TMP12]], ptr [[S4]], align 4
; CHECK-NEXT:    [[TMP13:%.*]] = extractelement <8 x i16> [[TMP2]], i32 5
; CHECK-NEXT:    [[TMP14:%.*]] = zext i16 [[TMP13]] to i32
; CHECK-NEXT:    store i32 [[TMP14]], ptr [[S5]], align 4
; CHECK-NEXT:    [[TMP15:%.*]] = extractelement <8 x i16> [[TMP2]], i32 6
; CHECK-NEXT:    [[TMP16:%.*]] = zext i16 [[TMP15]] to i32
; CHECK-NEXT:    store i32 [[TMP16]], ptr [[S6]], align 4
; CHECK-NEXT:    [[TMP17:%.*]] = extractelement <8 x i16> [[TMP2]], i32 7
; CHECK-NEXT:    [[TMP18:%.*]] = zext i16 [[TMP17]] to i32
; CHECK-NEXT:    store i32 [[TMP18]], ptr [[S7]], align 4
; CHECK-NEXT:    ret void
;
  %l = load <8 x i8>, ptr %pl, align 1
  %e0 = extractelement <8 x i8> %l, i32 0
  %e1 = extractelement <8 x i8> %l, i32 1
  %e2 = extractelement <8 x i8> %l, i32 2
  %e3 = extractelement <8 x i8> %l, i32 3
  %e4 = extractelement <8 x i8> %l, i32 4
  %e5 = extractelement <8 x i8> %l, i32 5
  %e6 = extractelement <8 x i8> %l, i32 6
  %e7 = extractelement <8 x i8> %l, i32 7
  %z0 = zext i8 %e0 to i32
  %z1 = zext i8 %e1 to i32
  %z2 = zext i8 %e2 to i32
  %z3 = zext i8 %e3 to i32
  %z4 = zext i8 %e4 to i32
  %z5 = zext i8 %e5 to i32
  %z6 = zext i8 %e6 to i32
  %z7 = zext i8 %e7 to i32
  %a0 = add i32 %z0, 5
  %a1 = add i32 %z1, 5
  %a2 = add i32 %z2, 5
  %a3 = add i32 %z3, 5
  %a4 = add i32 %z4, 5
  %a5 = add i32 %z5, 5
  %a6 = add i32 %z6, 5
  %a7 = add i32 %z7, 5
  %s0 = getelementptr inbounds i32, ptr %ps, i64 0
  %s1 = getelementptr inbounds i32, ptr %ps, i64 2
  %s2 = getelementptr inbounds i32, ptr %ps, i64 4
  %s3 = getelementptr inbounds i32, ptr %ps, i64 6
  %s4 = getelementptr inbounds i32, ptr %ps, i64 8
  %s5 = getelementptr inbounds i32, ptr %ps, i64 10
  %s6 = getelementptr inbounds i32, ptr %ps, i64 12
  %s7 = getelementptr inbounds i32, ptr %ps, i64 14
  store i32 %a0, ptr %s0
  store i32 %a1, ptr %s1
  store i32 %a2, ptr %s2
  store i32 %a3, ptr %s3
  store i32 %a4, ptr %s4
  store i32 %a5, ptr %s5
  store i32 %a6, ptr %s6
  store i32 %a7, ptr %s7
  ret void
}

define void @const_stride_2_i32_reverse_values(ptr %pl, ptr %ps) {
; CHECK-LABEL: define void @const_stride_2_i32_reverse_values(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[L:%.*]] = load <8 x i32>, ptr [[PL]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = add <8 x i32> [[L]], splat (i32 1)
; CHECK-NEXT:    [[S0:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 0
; CHECK-NEXT:    [[S1:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 2
; CHECK-NEXT:    [[S2:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 4
; CHECK-NEXT:    [[S3:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 6
; CHECK-NEXT:    [[S4:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 8
; CHECK-NEXT:    [[S5:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 10
; CHECK-NEXT:    [[S6:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 12
; CHECK-NEXT:    [[S7:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 14
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <8 x i32> [[TMP1]], i32 7
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[S0]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <8 x i32> [[TMP1]], i32 6
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[S1]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <8 x i32> [[TMP1]], i32 5
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[S2]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <8 x i32> [[TMP1]], i32 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[S3]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <8 x i32> [[TMP1]], i32 3
; CHECK-NEXT:    store i32 [[TMP6]], ptr [[S4]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <8 x i32> [[TMP1]], i32 2
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[S5]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <8 x i32> [[TMP1]], i32 1
; CHECK-NEXT:    store i32 [[TMP8]], ptr [[S6]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <8 x i32> [[TMP1]], i32 0
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[S7]], align 4
; CHECK-NEXT:    ret void
;
  %l = load <8 x i32>, ptr %pl, align 4
  %e0 = extractelement <8 x i32> %l, i32 7
  %e1 = extractelement <8 x i32> %l, i32 6
  %e2 = extractelement <8 x i32> %l, i32 5
  %e3 = extractelement <8 x i32> %l, i32 4
  %e4 = extractelement <8 x i32> %l, i32 3
  %e5 = extractelement <8 x i32> %l, i32 2
  %e6 = extractelement <8 x i32> %l, i32 1
  %e7 = extractelement <8 x i32> %l, i32 0
  %a0 = add i32 %e0, 1
  %a1 = add i32 %e1, 1
  %a2 = add i32 %e2, 1
  %a3 = add i32 %e3, 1
  %a4 = add i32 %e4, 1
  %a5 = add i32 %e5, 1
  %a6 = add i32 %e6, 1
  %a7 = add i32 %e7, 1
  %s0 = getelementptr inbounds i32, ptr %ps, i64 0
  %s1 = getelementptr inbounds i32, ptr %ps, i64 2
  %s2 = getelementptr inbounds i32, ptr %ps, i64 4
  %s3 = getelementptr inbounds i32, ptr %ps, i64 6
  %s4 = getelementptr inbounds i32, ptr %ps, i64 8
  %s5 = getelementptr inbounds i32, ptr %ps, i64 10
  %s6 = getelementptr inbounds i32, ptr %ps, i64 12
  %s7 = getelementptr inbounds i32, ptr %ps, i64 14
  store i32 %a0, ptr %s0
  store i32 %a1, ptr %s1
  store i32 %a2, ptr %s2
  store i32 %a3, ptr %s3
  store i32 %a4, ptr %s4
  store i32 %a5, ptr %s5
  store i32 %a6, ptr %s6
  store i32 %a7, ptr %s7
  ret void
}

define void @non_const_stride_i32(ptr %pl, ptr %ps) {
; CHECK-LABEL: define void @non_const_stride_i32(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[L:%.*]] = load <8 x i32>, ptr [[PL]], align 4
; CHECK-NEXT:    [[E0:%.*]] = extractelement <8 x i32> [[L]], i32 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <8 x i32> [[L]], i32 1
; CHECK-NEXT:    [[E2:%.*]] = extractelement <8 x i32> [[L]], i32 2
; CHECK-NEXT:    [[E3:%.*]] = extractelement <8 x i32> [[L]], i32 3
; CHECK-NEXT:    [[E4:%.*]] = extractelement <8 x i32> [[L]], i32 4
; CHECK-NEXT:    [[E5:%.*]] = extractelement <8 x i32> [[L]], i32 5
; CHECK-NEXT:    [[E6:%.*]] = extractelement <8 x i32> [[L]], i32 6
; CHECK-NEXT:    [[E7:%.*]] = extractelement <8 x i32> [[L]], i32 7
; CHECK-NEXT:    [[S0:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 0
; CHECK-NEXT:    [[S1:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 2
; CHECK-NEXT:    [[S2:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 4
; CHECK-NEXT:    [[S3:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 6
; CHECK-NEXT:    [[S4:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 8
; CHECK-NEXT:    [[S5:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 10
; CHECK-NEXT:    [[S6:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 12
; CHECK-NEXT:    [[S7:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 15
; CHECK-NEXT:    store i32 [[E0]], ptr [[S0]], align 4
; CHECK-NEXT:    store i32 [[E1]], ptr [[S1]], align 4
; CHECK-NEXT:    store i32 [[E2]], ptr [[S2]], align 4
; CHECK-NEXT:    store i32 [[E3]], ptr [[S3]], align 4
; CHECK-NEXT:    store i32 [[E4]], ptr [[S4]], align 4
; CHECK-NEXT:    store i32 [[E5]], ptr [[S5]], align 4
; CHECK-NEXT:    store i32 [[E6]], ptr [[S6]], align 4
; CHECK-NEXT:    store i32 [[E7]], ptr [[S7]], align 4
; CHECK-NEXT:    ret void
;
  %l = load <8 x i32>, ptr %pl, align 4
  %e0 = extractelement <8 x i32> %l, i32 0
  %e1 = extractelement <8 x i32> %l, i32 1
  %e2 = extractelement <8 x i32> %l, i32 2
  %e3 = extractelement <8 x i32> %l, i32 3
  %e4 = extractelement <8 x i32> %l, i32 4
  %e5 = extractelement <8 x i32> %l, i32 5
  %e6 = extractelement <8 x i32> %l, i32 6
  %e7 = extractelement <8 x i32> %l, i32 7
  %s0 = getelementptr inbounds i32, ptr %ps, i64 0
  %s1 = getelementptr inbounds i32, ptr %ps, i64 2
  %s2 = getelementptr inbounds i32, ptr %ps, i64 4
  %s3 = getelementptr inbounds i32, ptr %ps, i64 6
  %s4 = getelementptr inbounds i32, ptr %ps, i64 8
  %s5 = getelementptr inbounds i32, ptr %ps, i64 10
  %s6 = getelementptr inbounds i32, ptr %ps, i64 12
  %s7 = getelementptr inbounds i32, ptr %ps, i64 15
  store i32 %e0, ptr %s0
  store i32 %e1, ptr %s1
  store i32 %e2, ptr %s2
  store i32 %e3, ptr %s3
  store i32 %e4, ptr %s4
  store i32 %e5, ptr %s5
  store i32 %e6, ptr %s6
  store i32 %e7, ptr %s7
  ret void
}

define void @irregular_gaps_i8(ptr %pl, ptr %ps) {
; CHECK-LABEL: define void @irregular_gaps_i8(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[L:%.*]] = load <8 x i8>, ptr [[PL]], align 1
; CHECK-NEXT:    [[E0:%.*]] = extractelement <8 x i8> [[L]], i32 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <8 x i8> [[L]], i32 1
; CHECK-NEXT:    [[E2:%.*]] = extractelement <8 x i8> [[L]], i32 2
; CHECK-NEXT:    [[E3:%.*]] = extractelement <8 x i8> [[L]], i32 3
; CHECK-NEXT:    [[E4:%.*]] = extractelement <8 x i8> [[L]], i32 4
; CHECK-NEXT:    [[E5:%.*]] = extractelement <8 x i8> [[L]], i32 5
; CHECK-NEXT:    [[E6:%.*]] = extractelement <8 x i8> [[L]], i32 6
; CHECK-NEXT:    [[E7:%.*]] = extractelement <8 x i8> [[L]], i32 7
; CHECK-NEXT:    [[S0:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 0
; CHECK-NEXT:    [[S1:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 2
; CHECK-NEXT:    [[S2:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 5
; CHECK-NEXT:    [[S3:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 9
; CHECK-NEXT:    [[S4:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 11
; CHECK-NEXT:    [[S5:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 14
; CHECK-NEXT:    [[S6:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 18
; CHECK-NEXT:    [[S7:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 20
; CHECK-NEXT:    store i8 [[E0]], ptr [[S0]], align 1
; CHECK-NEXT:    store i8 [[E1]], ptr [[S1]], align 1
; CHECK-NEXT:    store i8 [[E2]], ptr [[S2]], align 1
; CHECK-NEXT:    store i8 [[E3]], ptr [[S3]], align 1
; CHECK-NEXT:    store i8 [[E4]], ptr [[S4]], align 1
; CHECK-NEXT:    store i8 [[E5]], ptr [[S5]], align 1
; CHECK-NEXT:    store i8 [[E6]], ptr [[S6]], align 1
; CHECK-NEXT:    store i8 [[E7]], ptr [[S7]], align 1
; CHECK-NEXT:    ret void
;
  %l = load <8 x i8>, ptr %pl, align 1
  %e0 = extractelement <8 x i8> %l, i32 0
  %e1 = extractelement <8 x i8> %l, i32 1
  %e2 = extractelement <8 x i8> %l, i32 2
  %e3 = extractelement <8 x i8> %l, i32 3
  %e4 = extractelement <8 x i8> %l, i32 4
  %e5 = extractelement <8 x i8> %l, i32 5
  %e6 = extractelement <8 x i8> %l, i32 6
  %e7 = extractelement <8 x i8> %l, i32 7
  %s0 = getelementptr inbounds i8, ptr %ps, i64 0
  %s1 = getelementptr inbounds i8, ptr %ps, i64 2
  %s2 = getelementptr inbounds i8, ptr %ps, i64 5
  %s3 = getelementptr inbounds i8, ptr %ps, i64 9
  %s4 = getelementptr inbounds i8, ptr %ps, i64 11
  %s5 = getelementptr inbounds i8, ptr %ps, i64 14
  %s6 = getelementptr inbounds i8, ptr %ps, i64 18
  %s7 = getelementptr inbounds i8, ptr %ps, i64 20
  store i8 %e0, ptr %s0
  store i8 %e1, ptr %s1
  store i8 %e2, ptr %s2
  store i8 %e3, ptr %s3
  store i8 %e4, ptr %s4
  store i8 %e5, ptr %s5
  store i8 %e6, ptr %s6
  store i8 %e7, ptr %s7
  ret void
}

define void @reordered_values_i32(ptr %pl, ptr %ps) {
; CHECK-LABEL: define void @reordered_values_i32(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[L:%.*]] = load <4 x i32>, ptr [[PL]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = add <4 x i32> [[L]], splat (i32 1)
; CHECK-NEXT:    [[S0:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 0
; CHECK-NEXT:    [[S1:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 2
; CHECK-NEXT:    [[S2:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 4
; CHECK-NEXT:    [[S3:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 6
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i32> [[TMP1]], i32 1
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[S0]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <4 x i32> [[TMP1]], i32 0
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[S1]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i32> [[TMP1]], i32 3
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[S2]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <4 x i32> [[TMP1]], i32 2
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[S3]], align 4
; CHECK-NEXT:    ret void
;
  %l = load <4 x i32>, ptr %pl, align 4
  %e0 = extractelement <4 x i32> %l, i32 1
  %e1 = extractelement <4 x i32> %l, i32 0
  %e2 = extractelement <4 x i32> %l, i32 3
  %e3 = extractelement <4 x i32> %l, i32 2
  %a0 = add i32 %e0, 1
  %a1 = add i32 %e1, 1
  %a2 = add i32 %e2, 1
  %a3 = add i32 %e3, 1
  %s0 = getelementptr inbounds i32, ptr %ps, i64 0
  %s1 = getelementptr inbounds i32, ptr %ps, i64 2
  %s2 = getelementptr inbounds i32, ptr %ps, i64 4
  %s3 = getelementptr inbounds i32, ptr %ps, i64 6
  store i32 %a0, ptr %s0
  store i32 %a1, ptr %s1
  store i32 %a2, ptr %s2
  store i32 %a3, ptr %s3
  ret void
}
