; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu -mcpu=icelake-server < %s | FileCheck %s

define void @test(ptr %0, i32 %.sroa.31.0.copyload4033) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[TMP0:%.*]], i32 [[DOTSROA_31_0_COPYLOAD4033:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[_PREHEADER1937_PREHEADER:.*:]]
; CHECK-NEXT:    br [[DOTPREHEADER1927_PREHEADER:label %.*]]
; CHECK:       [[_PREHEADER1927_PREHEADER:.*:]]
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <4 x i32> poison, i32 [[DOTSROA_31_0_COPYLOAD4033]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    br [[DOTPREHEADER1927:label %.*]]
; CHECK:       [[_LOOPEXIT1924:.*:]]
; CHECK-NEXT:    br i1 false, [[DOTPREHEADER1927]], [[DOTPREHEADER1927_PREHEADER]]
; CHECK:       [[_PREHEADER1927:.*:]]
; CHECK-NEXT:    br i1 false, [[DOTLR_PH2669_PREHEADER:label %.*]], [[DOTCRITEDGE1844_LOOPEXIT2813:label %.*]]
; CHECK:       [[_LR_PH2669_PREHEADER:.*:]]
; CHECK-NEXT:    br i1 false, [[DOTLOOPEXIT1924:label %.*]], [[DOT_CRIT_EDGE2670:label %.*]]
; CHECK:       [[__CRIT_EDGE2670:.*:]]
; CHECK-NEXT:    ret void
; CHECK:       [[_CRITEDGE1844_LOOPEXIT2813:.*:]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP0]], i64 -24
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[TMP0]], i64 -36
; CHECK-NEXT:    [[TMP5:%.*]] = load <2 x i32>, ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = call <7 x i32> @llvm.masked.load.v7i32.p0(ptr align 4 [[TMP3]], <7 x i1> <i1 true, i1 false, i1 false, i1 false, i1 false, i1 false, i1 true>, <7 x i32> poison)
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <7 x i32> [[TMP6]], <7 x i32> poison, <2 x i32> <i32 6, i32 0>
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP5]], <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i32> [[TMP7]], <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <2 x i32> [[TMP5]], <2 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    [[TMP11:%.*]] = or <4 x i32> [[TMP10]], [[TMP2]]
; CHECK-NEXT:    [[TMP12:%.*]] = or <4 x i32> [[TMP11]], splat (i32 1)
; CHECK-NEXT:    store <4 x i32> [[TMP12]], ptr [[TMP4]], align 4
; CHECK-NEXT:    br [[DOTLOOPEXIT1924]]
;
.preheader1937.preheader:
  br label %.preheader1927.preheader

.preheader1927.preheader:                         ; preds = %.loopexit1924, %.preheader1937.preheader
  br label %.preheader1927

.loopexit1924:                                    ; preds = %.critedge1844.loopexit2813, %.lr.ph2669.preheader
  br i1 false, label %.preheader1927, label %.preheader1927.preheader

.preheader1927:                                   ; preds = %.loopexit1924, %.preheader1927.preheader
  br i1 false, label %.lr.ph2669.preheader, label %.critedge1844.loopexit2813

.lr.ph2669.preheader:                             ; preds = %.preheader1927
  br i1 false, label %.loopexit1924, label %._crit_edge2670

._crit_edge2670:                                  ; preds = %.lr.ph2669.preheader
  ret void

.critedge1844.loopexit2813:                       ; preds = %.preheader1927
  %1 = getelementptr i8, ptr %0, i64 -24
  %2 = load i32, ptr %1, align 4
  %3 = or i32 %2, %.sroa.31.0.copyload4033
  %4 = or i32 %3, 1
  %5 = getelementptr i8, ptr %0, i64 -36
  store i32 %4, ptr %5, align 4
  %6 = getelementptr i8, ptr %0, i64 -20
  %7 = load i32, ptr %6, align 4
  %8 = or i32 %7, %.sroa.31.0.copyload4033
  %9 = or i32 %8, 1
  %.sroa.34125.0..sroa_idx = getelementptr i8, ptr %0, i64 -32
  store i32 %9, ptr %.sroa.34125.0..sroa_idx, align 4
  %10 = load i32, ptr %0, align 4
  %11 = or i32 %10, %.sroa.31.0.copyload4033
  %12 = or i32 %11, 1
  %.sroa.54126.0..sroa_idx = getelementptr i8, ptr %0, i64 -28
  store i32 %12, ptr %.sroa.54126.0..sroa_idx, align 4
  %13 = or i32 %2, %.sroa.31.0.copyload4033
  %14 = or i32 %13, 1
  store i32 %14, ptr %1, align 4
  br label %.loopexit1924
}
