; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux -mattr=+sse4.2 -slp-threshold=-2 < %s | FileCheck %s

define i32 @test(i32 %arg, i32 %arg1, i1 %arg4, i1 %arg5) {
; CHECK-LABEL: define i32 @test(
; CHECK-SAME: i32 [[ARG:%.*]], i32 [[ARG1:%.*]], i1 [[ARG4:%.*]], i1 [[ARG5:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[BB:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x i32> poison, i32 [[ARG]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <4 x i32> [[TMP0]], i32 [[ARG1]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> poison, <4 x i32> <i32 0, i32 1, i32 1, i32 0>
; CHECK-NEXT:    [[TMP3:%.*]] = sdiv <4 x i32> [[TMP2]], splat (i32 64)
; CHECK-NEXT:    [[TMP4:%.*]] = shl <4 x i32> [[TMP3]], <i32 1, i32 0, i32 0, i32 0>
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 0, i32 1>
; CHECK-NEXT:    [[TMP6:%.*]] = icmp ne <4 x i32> [[TMP4]], [[TMP5]]
; CHECK-NEXT:    [[TMP7:%.*]] = select <4 x i1> [[TMP6]], <4 x i32> <i32 1, i32 2, i32 4, i32 8>, <4 x i32> zeroinitializer
; CHECK-NEXT:    br i1 [[ARG4]], label %[[BB13:.*]], label %[[BB16:.*]]
; CHECK:       [[COMMON_RET:.*]]:
; CHECK-NEXT:    [[COMMON_RET_OP:%.*]] = phi i32 [ 0, %[[BB20:.*]] ], [ [[TMP10:%.*]], %[[BB17:.*]] ]
; CHECK-NEXT:    ret i32 [[COMMON_RET_OP]]
; CHECK:       [[BB13]]:
; CHECK-NEXT:    [[TMP8:%.*]] = call i32 @llvm.vector.reduce.or.v4i32(<4 x i32> [[TMP7]])
; CHECK-NEXT:    ret i32 [[TMP8]]
; CHECK:       [[BB16]]:
; CHECK-NEXT:    br i1 [[ARG5]], label %[[BB17]], label %[[BB20]]
; CHECK:       [[BB17]]:
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i32> [[TMP7]], <4 x i32> poison, <3 x i32> <i32 0, i32 1, i32 2>
; CHECK-NEXT:    [[TMP10]] = call i32 @llvm.vector.reduce.or.v3i32(<3 x i32> [[TMP9]])
; CHECK-NEXT:    br label %[[COMMON_RET]]
; CHECK:       [[BB20]]:
; CHECK-NEXT:    [[TMP12:%.*]] = extractelement <4 x i32> [[TMP7]], i32 3
; CHECK-NEXT:    store volatile i32 [[TMP12]], ptr null, align 4294967296
; CHECK-NEXT:    br label %[[COMMON_RET]]
;
bb:
  %sdiv = sdiv i32 %arg, 64
  %shl = shl i32 %sdiv, 1
  %icmp = icmp ne i32 %shl, %arg
  %zext = zext i1 %icmp to i32
  %sdiv6 = sdiv i32 %arg1, 64
  %icmp7 = icmp eq i32 %sdiv6, %arg
  %select = select i1 %icmp7, i32 0, i32 2
  %sdiv8 = sdiv i32 %arg1, 64
  %icmp9 = icmp eq i32 %sdiv8, %arg
  %select10 = select i1 %icmp9, i32 0, i32 4
  %icmp11 = icmp eq i32 %sdiv, %arg1
  %select12 = select i1 %icmp11, i32 0, i32 8
  br i1 %arg4, label %bb13, label %bb16

common.ret:
  %common.ret.op = phi i32 [ 0, %bb20 ], [ %or19, %bb17 ]
  ret i32 %common.ret.op

bb13:
  %or = or i32 %select, %zext
  %or14 = or i32 %or, %select10
  %or15 = or i32 %or14, %select12
  ret i32 %or15

bb16:
  br i1 %arg5, label %bb17, label %bb20

bb17:
  %or18 = or i32 %select, %zext
  %or19 = or i32 %or18, %select10
  br label %common.ret

bb20:
  store volatile i32 %select12, ptr null, align 4294967296
  br label %common.ret
}

define i32 @test_multi_cond_use(i32 %arg, i32 %arg1, i1 %arg4, i1 %arg5) {
; CHECK-LABEL: define i32 @test_multi_cond_use(
; CHECK-SAME: i32 [[ARG:%.*]], i32 [[ARG1:%.*]], i1 [[ARG4:%.*]], i1 [[ARG5:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[BB:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x i32> poison, i32 [[ARG]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <4 x i32> [[TMP0]], i32 [[ARG1]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> poison, <4 x i32> <i32 0, i32 1, i32 0, i32 1>
; CHECK-NEXT:    [[TMP3:%.*]] = sdiv <4 x i32> [[TMP2]], splat (i32 64)
; CHECK-NEXT:    [[TMP4:%.*]] = shl <4 x i32> [[TMP3]], <i32 0, i32 0, i32 1, i32 0>
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> poison, <4 x i32> <i32 1, i32 0, i32 0, i32 0>
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq <4 x i32> [[TMP4]], [[TMP5]]
; CHECK-NEXT:    [[TMP7:%.*]] = icmp ne <4 x i32> [[TMP4]], [[TMP5]]
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i1> [[TMP6]], <4 x i1> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 6, i32 3>
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <4 x i1> [[TMP10]], i32 2
; CHECK-NEXT:    [[EXT:%.*]] = zext i1 [[TMP8]] to i32
; CHECK-NEXT:    [[ICMP7:%.*]] = extractelement <4 x i1> [[TMP10]], i32 3
; CHECK-NEXT:    [[SELECT:%.*]] = select i1 [[ICMP7]], i32 0, i32 2
; CHECK-NEXT:    [[ICMP9:%.*]] = extractelement <4 x i1> [[TMP10]], i32 1
; CHECK-NEXT:    [[TMP12:%.*]] = select i1 [[ICMP9]], i32 0, i32 4
; CHECK-NEXT:    [[ICMP11:%.*]] = extractelement <4 x i1> [[TMP10]], i32 0
; CHECK-NEXT:    [[TMP13:%.*]] = select i1 [[ICMP11]], i32 0, i32 8
; CHECK-NEXT:    [[EXT1:%.*]] = zext i1 [[ICMP11]] to i32
; CHECK-NEXT:    br i1 [[ARG4]], label %[[BB13:.*]], label %[[BB16:.*]]
; CHECK:       [[COMMON_RET:.*]]:
; CHECK-NEXT:    [[COMMON_RET_OP:%.*]] = phi i32 [ [[EXT1]], %[[BB20:.*]] ], [ [[OR19:%.*]], %[[BB17:.*]] ]
; CHECK-NEXT:    ret i32 [[COMMON_RET_OP]]
; CHECK:       [[BB13]]:
; CHECK-NEXT:    [[OR:%.*]] = or i32 [[SELECT]], [[EXT]]
; CHECK-NEXT:    [[OR14:%.*]] = or i32 [[OR]], [[TMP12]]
; CHECK-NEXT:    [[TMP9:%.*]] = or i32 [[OR14]], [[TMP13]]
; CHECK-NEXT:    ret i32 [[TMP9]]
; CHECK:       [[BB16]]:
; CHECK-NEXT:    br i1 [[ARG5]], label %[[BB17]], label %[[BB20]]
; CHECK:       [[BB17]]:
; CHECK-NEXT:    [[OR18:%.*]] = or i32 [[SELECT]], [[EXT]]
; CHECK-NEXT:    [[OR19]] = or i32 [[OR18]], [[TMP12]]
; CHECK-NEXT:    br label %[[COMMON_RET]]
; CHECK:       [[BB20]]:
; CHECK-NEXT:    store volatile i32 [[TMP13]], ptr null, align 4294967296
; CHECK-NEXT:    br label %[[COMMON_RET]]
;
bb:
  %sdiv = sdiv i32 %arg, 64
  %shl = shl i32 %sdiv, 1
  %icmp = icmp ne i32 %shl, %arg
  %zext = zext i1 %icmp to i32
  %sdiv6 = sdiv i32 %arg1, 64
  %icmp7 = icmp eq i32 %sdiv6, %arg
  %select = select i1 %icmp7, i32 0, i32 2
  %sdiv8 = sdiv i32 %arg1, 64
  %icmp9 = icmp eq i32 %sdiv8, %arg
  %select10 = select i1 %icmp9, i32 0, i32 4
  %icmp11 = icmp eq i32 %sdiv, %arg1
  %select12 = select i1 %icmp11, i32 0, i32 8
  %ext = zext i1 %icmp11 to i32
  br i1 %arg4, label %bb13, label %bb16

common.ret:
  %common.ret.op = phi i32 [ %ext, %bb20 ], [ %or19, %bb17 ]
  ret i32 %common.ret.op

bb13:
  %or = or i32 %select, %zext
  %or14 = or i32 %or, %select10
  %or15 = or i32 %or14, %select12
  ret i32 %or15

bb16:
  br i1 %arg5, label %bb17, label %bb20

bb17:
  %or18 = or i32 %select, %zext
  %or19 = or i32 %or18, %select10
  br label %common.ret

bb20:
  store volatile i32 %select12, ptr null, align 4294967296
  br label %common.ret
}
