; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt --passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

@__profc_i = external global [24 x i64]

define void @test(i16 %0, i64 %.reass732) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i16 [[TMP0:%.*]], i64 [[DOTREASS732:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP1:%.*]] = sext i16 [[TMP0]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = and i64 [[TMP1]], 2147483647
; CHECK-NEXT:    [[REASS_ADD:%.*]] = shl i64 [[TMP2]], 1
; CHECK-NEXT:    [[INVARIANT_OP731:%.*]] = add i64 [[REASS_ADD]], 16
; CHECK-NEXT:    [[INVARIANT_OP741:%.*]] = shl i64 [[TMP2]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = shl i64 [[TMP2]], 1
; CHECK-NEXT:    br label %[[FOR_BODY4_LR_PH:.*]]
; CHECK:       [[FOR_BODY4_LR_PH]]:
; CHECK-NEXT:    [[DOTPROMOTED1212318221:%.*]] = phi i64 [ [[DOTREASS805:%.*]], %[[FOR_BODY4_LR_PH]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[DOTPROMOTED125241821:%.*]] = phi i64 [ [[DOTREASS774:%.*]], %[[FOR_BODY4_LR_PH]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[DOTREASS742:%.*]] = or i64 [[DOTPROMOTED1212318221]], [[INVARIANT_OP741]]
; CHECK-NEXT:    store i64 [[DOTREASS742]], ptr getelementptr inbounds nuw (i8, ptr @__profc_i, i64 72), align 8
; CHECK-NEXT:    [[DOTREASS7322:%.*]] = or i64 [[DOTPROMOTED125241821]], [[INVARIANT_OP731]]
; CHECK-NEXT:    store i64 [[DOTREASS7322]], ptr getelementptr inbounds nuw (i8, ptr @__profc_i, i64 80), align 8
; CHECK-NEXT:    [[DOTREASS753:%.*]] = add i64 [[DOTREASS732]], [[TMP3]]
; CHECK-NEXT:    [[DOTREASS774]] = or i64 [[DOTREASS753]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = shl i64 [[TMP2]], 1
; CHECK-NEXT:    [[DOTREASS805]] = or i64 [[TMP4]], 1
; CHECK-NEXT:    br label %[[FOR_BODY4_LR_PH]]
;
entry:
  %1 = sext i16 %0 to i64
  %2 = and i64 %1, 2147483647
  %reass.add = shl i64 %2, 1
  %invariant.op731 = add i64 %reass.add, 16
  %invariant.op741 = shl i64 %2, 1
  %3 = shl i64 %2, 1
  br label %for.body4.lr.ph

for.body4.lr.ph:
  %.promoted1212318221 = phi i64 [ %.reass805, %for.body4.lr.ph ], [ 0, %entry ]
  %.promoted125241821 = phi i64 [ %.reass774, %for.body4.lr.ph ], [ 0, %entry ]
  %.reass742 = or i64 %.promoted1212318221, %invariant.op741
  store i64 %.reass742, ptr getelementptr inbounds nuw (i8, ptr @__profc_i, i64 72), align 8
  %.reass7322 = or i64 %.promoted125241821, %invariant.op731
  store i64 %.reass7322, ptr getelementptr inbounds nuw (i8, ptr @__profc_i, i64 80), align 8
  %.reass753 = add i64 %.reass732, %3
  %.reass774 = or i64 %.reass753, 1
  %4 = shl i64 %2, 1
  %.reass805 = or i64 %4, 1
  br label %for.body4.lr.ph
}
