; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define i8 @test(ptr %c, i1 %cmp3, i8 %c.promoted) {
; CHECK-LABEL: define i8 @test(
; CHECK-SAME: ptr [[C:%.*]], i1 [[CMP3:%.*]], i8 [[C_PROMOTED:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[C]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <8 x i1> poison, i1 [[CMP3]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i1> [[TMP1]], <8 x i1> poison, <8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP3:%.*]] = select <8 x i1> [[TMP2]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP0]] to i8
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <8 x i8> poison, i8 [[TMP4]], i32 0
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> poison, <8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP7:%.*]] = or <8 x i8> [[TMP6]], [[TMP3]]
; CHECK-NEXT:    [[TMP8:%.*]] = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[TMP7]])
; CHECK-NEXT:    [[OP_RDX:%.*]] = or i8 [[TMP8]], [[C_PROMOTED]]
; CHECK-NEXT:    ret i8 [[OP_RDX]]
;
entry:
  %0 = load i32, ptr %c, align 4
  %conv4 = zext i1 %cmp3 to i32
  %or = or i32 %0, %conv4
  %1 = trunc i32 %or to i8
  %shl.1 = select i1 %cmp3, i32 2, i32 0
  %or.1 = or i32 %shl.1, %0
  %shl.2 = select i1 %cmp3, i32 4, i32 0
  %conv7 = or i8 %c.promoted, %1
  %2 = trunc i32 %or.1 to i8
  %conv7.1 = or i8 %conv7, %2
  %or.2 = or i32 %shl.2, %0
  %3 = trunc i32 %or.2 to i8
  %conv7.2 = or i8 %conv7.1, %3
  %shl.3 = select i1 %cmp3, i32 8, i32 0
  %or.3 = or i32 %shl.3, %0
  %4 = trunc i32 %or.3 to i8
  %shl.4 = select i1 %cmp3, i32 16, i32 0
  %or.4 = or i32 %shl.4, %0
  %shl.5 = select i1 %cmp3, i32 32, i32 0
  %shl.6 = select i1 %cmp3, i32 64, i32 0
  %shl.7 = select i1 %cmp3, i32 128, i32 0
  %conv7.3 = or i8 %conv7.2, %4
  %5 = trunc i32 %or.4 to i8
  %conv7.4 = or i8 %conv7.3, %5
  %or.5 = or i32 %shl.5, %0
  %6 = trunc i32 %or.5 to i8
  %conv7.5 = or i8 %conv7.4, %6
  %or.6 = or i32 %shl.6, %0
  %7 = trunc i32 %or.6 to i8
  %conv7.6 = or i8 %conv7.5, %7
  %or.7 = or i32 %shl.7, %0
  %8 = trunc i32 %or.7 to i8
  %conv7.7 = or i8 %conv7.6, %8
  ret i8 %conv7.7
}
