; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=slp-vectorizer -slp-threshold=-999 -S -mtriple=x86_64-unknown-linux -mcpu=corei7-avx | FileCheck %s

target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64-S128"

declare double @user_func(double)
declare double @another_user_func(double, double)

; Two consecutive non-vectorizable calls feeding stores to non-consecutive
; addresses. The fmul operand chain is only reachable through the calls, so
; without operand-chain seeding from non-vectorizable calls the loads/fmuls
; remain scalar.
define void @test_two_calls_with_vectorizable_operands(ptr %p, ptr %out0, ptr %out1) {
; CHECK-LABEL: define void @test_two_calls_with_vectorizable_operands(
; CHECK-SAME: ptr [[P:%.*]], ptr [[OUT0:%.*]], ptr [[OUT1:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[A0:%.*]] = load double, ptr [[P]], align 8
; CHECK-NEXT:    [[P1:%.*]] = getelementptr double, ptr [[P]], i64 1
; CHECK-NEXT:    [[A1:%.*]] = load double, ptr [[P1]], align 8
; CHECK-NEXT:    [[M0:%.*]] = fmul double [[A0]], 2.000000e+00
; CHECK-NEXT:    [[M1:%.*]] = fmul double [[A1]], 3.000000e+00
; CHECK-NEXT:    [[R0:%.*]] = call double @user_func(double [[M0]])
; CHECK-NEXT:    [[R1:%.*]] = call double @user_func(double [[M1]])
; CHECK-NEXT:    store double [[R0]], ptr [[OUT0]], align 8
; CHECK-NEXT:    store double [[R1]], ptr [[OUT1]], align 8
; CHECK-NEXT:    ret void
;
  %a0 = load double, ptr %p, align 8
  %p1 = getelementptr double, ptr %p, i64 1
  %a1 = load double, ptr %p1, align 8
  %m0 = fmul double %a0, 2.000000e+00
  %m1 = fmul double %a1, 3.000000e+00
  %r0 = call double @user_func(double %m0)
  %r1 = call double @user_func(double %m1)
  store double %r0, ptr %out0, align 8
  store double %r1, ptr %out1, align 8
  ret void
}

; Two non-vectorizable calls with paired operands across calls. Both arguments
; should be vectorized as <2 x double> bundles.
define void @test_two_calls_paired_operands(ptr %p, ptr %q, ptr %out0, ptr %out1) {
; CHECK-LABEL: define void @test_two_calls_paired_operands(
; CHECK-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], ptr [[OUT0:%.*]], ptr [[OUT1:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[A0:%.*]] = load double, ptr [[P]], align 8
; CHECK-NEXT:    [[P1:%.*]] = getelementptr double, ptr [[P]], i64 1
; CHECK-NEXT:    [[A1:%.*]] = load double, ptr [[P1]], align 8
; CHECK-NEXT:    [[B0:%.*]] = load double, ptr [[Q]], align 8
; CHECK-NEXT:    [[Q1:%.*]] = getelementptr double, ptr [[Q]], i64 1
; CHECK-NEXT:    [[B1:%.*]] = load double, ptr [[Q1]], align 8
; CHECK-NEXT:    [[M0:%.*]] = fmul double [[A0]], 2.000000e+00
; CHECK-NEXT:    [[M1:%.*]] = fmul double [[A1]], 3.000000e+00
; CHECK-NEXT:    [[N0:%.*]] = fadd double [[B0]], 4.000000e+00
; CHECK-NEXT:    [[N1:%.*]] = fadd double [[B1]], 5.000000e+00
; CHECK-NEXT:    [[R0:%.*]] = call double @another_user_func(double [[M0]], double [[N0]])
; CHECK-NEXT:    [[R1:%.*]] = call double @another_user_func(double [[M1]], double [[N1]])
; CHECK-NEXT:    store double [[R0]], ptr [[OUT0]], align 8
; CHECK-NEXT:    store double [[R1]], ptr [[OUT1]], align 8
; CHECK-NEXT:    ret void
;
  %a0 = load double, ptr %p, align 8
  %p1 = getelementptr double, ptr %p, i64 1
  %a1 = load double, ptr %p1, align 8
  %b0 = load double, ptr %q, align 8
  %q1 = getelementptr double, ptr %q, i64 1
  %b1 = load double, ptr %q1, align 8
  %m0 = fmul double %a0, 2.000000e+00
  %m1 = fmul double %a1, 3.000000e+00
  %n0 = fadd double %b0, 4.000000e+00
  %n1 = fadd double %b1, 5.000000e+00
  %r0 = call double @another_user_func(double %m0, double %n0)
  %r1 = call double @another_user_func(double %m1, double %n1)
  store double %r0, ptr %out0, align 8
  store double %r1, ptr %out1, align 8
  ret void
}

; Memory intrinsics must not be added to the post-process call list.
define void @test_skip_memcpy(ptr %dst, ptr %src) {
; CHECK-LABEL: define void @test_skip_memcpy(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr [[DST]], ptr [[SRC]], i64 16, i1 false)
; CHECK-NEXT:    ret void
;
  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %src, i64 16, i1 false)
  ret void
}

; Trivially vectorizable intrinsics are still handled by the regular path -
; this confirms the existing behavior is preserved.
define void @test_trivially_vectorizable_intrinsic(ptr %p, ptr %out) {
; CHECK-LABEL: define void @test_trivially_vectorizable_intrinsic(
; CHECK-SAME: ptr [[P:%.*]], ptr [[OUT:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x double>, ptr [[P]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = call <2 x double> @llvm.fabs.v2f64(<2 x double> [[TMP1]])
; CHECK-NEXT:    store <2 x double> [[TMP2]], ptr [[OUT]], align 8
; CHECK-NEXT:    ret void
;
  %a0 = load double, ptr %p, align 8
  %p1 = getelementptr double, ptr %p, i64 1
  %a1 = load double, ptr %p1, align 8
  %r0 = call double @llvm.fabs.f64(double %a0)
  %r1 = call double @llvm.fabs.f64(double %a1)
  store double %r0, ptr %out, align 8
  %out1 = getelementptr double, ptr %out, i64 1
  store double %r1, ptr %out1, align 8
  ret void
}

declare double @llvm.fabs.f64(double)
declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)
