; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu < %s -slp-threshold=-99999 | FileCheck %s

define void @test() {
; CHECK-LABEL: define void @test() {
; CHECK-NEXT:  [[BB:.*]]:
; CHECK-NEXT:    br i1 false, label %[[BB1:.*]], label %[[BB6:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[SHL4:%.*]] = shl i32 0, 0
; CHECK-NEXT:    [[ADD2:%.*]] = add i32 -1, 0
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i32> <i32 0, i32 poison>, i32 [[SHL4]], i32 1
; CHECK-NEXT:    [[TMP6:%.*]] = ashr <2 x i32> [[TMP5]], <i32 0, i32 1>
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <2 x i32> [[TMP6]], <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[ADD2]], i32 2
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 2>
; CHECK-NEXT:    br label %[[BB6]]
; CHECK:       [[BB6]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi <4 x i32> [ <i32 0, i32 0, i32 poison, i32 0>, %[[BB]] ], [ [[TMP4]], %[[BB1]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <4 x i32> [[TMP0]], i32 3
; CHECK-NEXT:    [[OR:%.*]] = or i32 [[TMP1]], 0
; CHECK-NEXT:    ret void
;
bb:
  br i1 false, label %bb1, label %bb6

bb1:
  %add = add i32 0, 0
  %shl = shl i32 %add, 0
  %sub = sub i32 0, 1
  %add2 = add i32 %sub, %shl
  %add3 = add i32 0, 0
  %shl4 = shl i32 %add3, 0
  %ashr = ashr i32 %shl4, 1
  %add5 = add i32 0, 0
  br label %bb6

bb6:
  %phi = phi i32 [ poison, %bb ], [ %add2, %bb1 ]
  %phi7 = phi i32 [ 0, %bb ], [ %ashr, %bb1 ]
  %phi8 = phi i32 [ 0, %bb ], [ %add2, %bb1 ]
  %phi9 = phi i32 [ 0, %bb ], [ %add5, %bb1 ]
  %or = or i32 %phi8, 0
  ret void
}
