; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-unknown -mcpu=znver2 < %s | FileCheck %s

define void @test() {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[BB1:.*]]
; CHECK:       [[IF_THEN_I_I:.*]]:
; CHECK-NEXT:    br label %[[BB3:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[TMP0:%.*]] = zext i1 false to i64
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <4 x i64> <i64 0, i64 0, i64 poison, i64 0>, i64 [[TMP0]], i32 2
; CHECK-NEXT:    [[TMP2:%.*]] = add <4 x i64> zeroinitializer, [[TMP1]]
; CHECK-NEXT:    br i1 false, label %[[BB3]], label %[[BB2:.*]]
; CHECK:       [[BB3]]:
; CHECK-NEXT:    [[TMP4:%.*]] = phi <4 x i64> [ [[TMP2]], %[[BB1]] ], [ poison, %[[IF_THEN_I_I]] ]
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[TMP7:%.*]] = phi <4 x i64> [ [[TMP4]], %[[BB3]] ], [ [[TMP2]], %[[BB1]] ]
; CHECK-NEXT:    store <4 x i64> [[TMP7]], ptr getelementptr inbounds nuw (i8, ptr null, i64 40), align 8
; CHECK-NEXT:    ret void
;
entry:
  br label %bb1

if.then.i.i:
  br label %3

bb1:
  %0 = zext i1 false to i64
  %1 = add i64 0, %0
  %2 = add i64 0, 0
  br i1 false, label %3, label %bb2

3:
  %pgocount51962 = phi i64 [ 0, %bb1 ], [ 0, %if.then.i.i ]
  %pgocount62360 = phi i64 [ 0, %bb1 ], [ 0, %if.then.i.i ]
  %pgocount83056 = phi i64 [ %1, %bb1 ], [ 0, %if.then.i.i ]
  %pgocount93354 = phi i64 [ %2, %bb1 ], [ 0, %if.then.i.i ]
  br label %bb2

bb2:
  %pgocount51961 = phi i64 [ %pgocount51962, %3 ], [ 0, %bb1 ]
  %pgocount62359 = phi i64 [ %pgocount62360, %3 ], [ 0, %bb1 ]
  %pgocount83055 = phi i64 [ %pgocount83056, %3 ], [ %1, %bb1 ]
  %pgocount93353 = phi i64 [ %pgocount93354, %3 ], [ %2, %bb1 ]
  store i64 %pgocount51961, ptr getelementptr inbounds nuw (i8, ptr null, i64 40), align 8
  store i64 %pgocount62359, ptr getelementptr inbounds nuw (i8, ptr null, i64 48), align 8
  store i64 %pgocount83055, ptr getelementptr inbounds nuw (i8, ptr null, i64 56), align 8
  store i64 %pgocount93353, ptr getelementptr inbounds nuw (i8, ptr null, i64 64), align 8
  ret void
}
