; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt --passes=slp-vectorizer -S -slp-threshold=-99999 -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define void @test() {
; CHECK-LABEL: define void @test() {
; CHECK-NEXT:  [[BB:.*:]]
; CHECK-NEXT:    br i1 false, label %[[BB1:.*]], label %[[BB2:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    br label %[[BB5:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 0, -51345
; CHECK-NEXT:    [[ADD3:%.*]] = add i32 0, 1
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x i32> <i32 0, i32 0, i32 poison, i32 1>, i32 [[MUL]], i32 2
; CHECK-NEXT:    [[TMP1:%.*]] = add <4 x i32> [[TMP0]], <i32 1, i32 1, i32 0, i32 0>
; CHECK-NEXT:    [[ZEXT:%.*]] = zext i32 [[ADD3]] to i64
; CHECK-NEXT:    br i1 false, label %[[BB5]], label %[[BB5]]
; CHECK:       [[BB5]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi <4 x i32> [ [[TMP1]], %[[BB2]] ], [ zeroinitializer, %[[BB1]] ], [ [[TMP1]], %[[BB2]] ]
; CHECK-NEXT:    ret void
;
bb:
  br i1 false, label %bb1, label %bb2

bb1:
  %add = add i32 0, 0
  br label %bb5

bb2:
  %add3 = add i32 0, 1
  %zext = zext i32 %add3 to i64
  %mul = mul i32 0, -51345
  %add4 = add i32 0, 1
  br i1 false, label %bb5, label %bb5

bb5:
  %phi = phi i32 [ 1, %bb2 ], [ 0, %bb1 ], [ 1, %bb2 ]
  %phi6 = phi i32 [ %add3, %bb2 ], [ 0, %bb1 ], [ %add3, %bb2 ]
  %phi7 = phi i32 [ %mul, %bb2 ], [ 0, %bb1 ], [ %mul, %bb2 ]
  %phi8 = phi i32 [ %add4, %bb2 ], [ %add, %bb1 ], [ %add4, %bb2 ]
  ret void
}

