; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define i1 @test() {
; CHECK-LABEL: define i1 @test() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[REM1876_UREM:%.*]] = xor i32 poison, 0
; CHECK-NEXT:    [[REM1876:%.*]] = select i1 false, i32 0, i32 [[REM1876_UREM]]
; CHECK-NEXT:    [[MUL2037:%.*]] = mul i32 [[REM1876]], 0
; CHECK-NEXT:    br label %[[IF_THEN2378:.*]]
; CHECK:       [[IF_THEN2378]]:
; CHECK-NEXT:    [[MUL1877:%.*]] = mul i32 [[REM1876]], 0
; CHECK-NEXT:    [[MUL1920:%.*]] = mul i32 poison, 0
; CHECK-NEXT:    [[REM1878:%.*]] = urem i32 [[MUL1877]], 0
; CHECK-NEXT:    [[REM1921:%.*]] = urem i32 [[MUL1920]], 0
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x i32> poison, i32 [[REM1921]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <2 x i32> [[TMP0]], i32 [[REM1878]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i32> <i32 poison, i32 poison, i32 0, i32 0>, <4 x i32> [[TMP2]], <4 x i32> <i32 4, i32 5, i32 2, i32 3>
; CHECK-NEXT:    [[TMP4:%.*]] = add <4 x i32> poison, [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = freeze <4 x i32> [[TMP4]]
; CHECK-NEXT:    [[TMP6:%.*]] = select <4 x i1> zeroinitializer, <4 x i32> [[TMP5]], <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP7:%.*]] = urem <4 x i32> [[TMP6]], splat (i32 46337)
; CHECK-NEXT:    [[TMP8:%.*]] = icmp ult <4 x i32> [[TMP7]], zeroinitializer
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x i1> [[TMP8]], i32 0
; CHECK-NEXT:    ret i1 [[TMP9]]
;
entry:
  %rem1857 = srem i32 0, 0
  %rem1859 = select i1 false, i32 0, i32 %rem1857
  %rem1865 = select i1 false, i32 0, i32 0
  %rem1917 = srem i32 0, 0
  %rem1919 = select i1 false, i32 0, i32 %rem1917
  %rem1876.urem = xor i32 poison, 0
  %rem1876 = select i1 false, i32 0, i32 %rem1876.urem
  %mul2037 = mul i32 %rem1876, 0
  br label %if.then2378

if.then2378:                                      ; preds = %entry
  %mul1950 = mul i32 %rem1859, 0
  %rem1951 = urem i32 %mul1950, 0
  %add1964 = or i32 %rem1951, 0
  %add1964.frozen = freeze i32 %add1964
  %rem1965 = select i1 false, i32 %add1964.frozen, i32 0
  %rem1974 = urem i32 %rem1965, 46337
  %rem1976.cmp = icmp ult i32 %rem1974, 0
  %mul2197 = mul i32 0, %rem1919
  %rem2198 = urem i32 %mul2197, 0
  %add2211.frozen = freeze i32 %rem2198
  %rem2212 = select i1 false, i32 %add2211.frozen, i32 0
  %rem2220 = urem i32 %rem2212, 46337
  %rem2222.cmp = icmp ult i32 %rem2220, 0
  %mul1866 = mul i32 0, %rem1865
  %mul1877 = mul i32 %rem1876, 0
  %rem1878 = urem i32 %mul1877, 0
  %rem1867 = urem i32 %mul1866, 0
  %add1879 = add i32 %rem1867, %rem1878
  %add1879.frozen = freeze i32 %add1879
  %rem1880 = select i1 false, i32 %add1879.frozen, i32 0
  %rem1888 = urem i32 %rem1880, 46337
  %rem1890.cmp = icmp ult i32 %rem1888, 0
  %mul1907 = mul i32 0, %rem1865
  %rem1908 = urem i32 %mul1907, 0
  %mul1920 = mul i32 %rem1919, 0
  %rem1921 = urem i32 %mul1920, 0
  %add1922 = add i32 %rem1908, %rem1921
  %add1922.frozen = freeze i32 %add1922
  %rem1923 = select i1 false, i32 %add1922.frozen, i32 0
  %rem1931 = urem i32 %rem1923, 46337
  %rem1933.cmp = icmp ult i32 %rem1931, 0
  ret i1 %rem1933.cmp
}

