; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=x86_64 < %s | FileCheck %s

define float @test() {
; CHECK-LABEL: define float @test() {
; CHECK-NEXT:  [[BB:.*:]]
; CHECK-NEXT:    [[LOAD:%.*]] = load float, ptr null, align 4
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x float> <float poison, float 0.000000e+00>, float [[LOAD]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = fadd <2 x float> zeroinitializer, [[TMP0]]
; CHECK-NEXT:    [[FMUL:%.*]] = fmul float 0.000000e+00, 0.000000e+00
; CHECK-NEXT:    [[FMUL3:%.*]] = fmul float 0.000000e+00, 0.000000e+00
; CHECK-NEXT:    [[FADD4:%.*]] = fadd float [[FMUL3]], 0.000000e+00
; CHECK-NEXT:    br i1 false, label %[[BB5:.*]], label %[[BB6:.*]]
; CHECK:       [[BB5]]:
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x float> [[TMP1]], i32 0
; CHECK-NEXT:    br label %[[BB8:.*]]
; CHECK:       [[BB6]]:
; CHECK-NEXT:    [[TMP3:%.*]] = fdiv <2 x float> [[TMP1]], zeroinitializer
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <2 x float> [[TMP3]], i32 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x float> [[TMP3]], i32 1
; CHECK-NEXT:    br label %[[BB8]]
; CHECK:       [[BB8]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi float [ 0.000000e+00, %[[BB5]] ], [ [[TMP5]], %[[BB6]] ]
; CHECK-NEXT:    [[PHI9:%.*]] = phi float [ [[FMUL]], %[[BB5]] ], [ 0.000000e+00, %[[BB6]] ]
; CHECK-NEXT:    [[PHI10:%.*]] = phi float [ [[FADD4]], %[[BB5]] ], [ [[LOAD]], %[[BB6]] ]
; CHECK-NEXT:    [[TMP10:%.*]] = phi float [ [[TMP2]], %[[BB5]] ], [ [[TMP4]], %[[BB6]] ]
; CHECK-NEXT:    ret float [[TMP10]]
;
bb:
  %fadd = fadd float 0.000000e+00, 0.000000e+00
  %load = load float, ptr null, align 4
  %fadd1 = fadd float %fadd, %load
  %fadd2 = fadd float 0.000000e+00, 0.000000e+00
  %fmul = fmul float 0.000000e+00, 0.000000e+00
  %fmul3 = fmul float 0.000000e+00, 0.000000e+00
  %fadd4 = fadd float %fmul3, 0.000000e+00
  br i1 false, label %bb5, label %bb6

bb5:
  br label %bb8

bb6:
  %fdiv = fdiv float %fadd1, 0.000000e+00
  %fdiv7 = fdiv float %fadd2, 0.000000e+00
  br label %bb8

bb8:
  %phi = phi float [ 0.000000e+00, %bb5 ], [ %fdiv7, %bb6 ]
  %phi9 = phi float [ %fmul, %bb5 ], [ 0.000000e+00, %bb6 ]
  %phi10 = phi float [ %fadd4, %bb5 ], [ %load, %bb6 ]
  %phi11 = phi float [ %fadd1, %bb5 ], [ %fdiv, %bb6 ]
  ret float %phi11
}
