; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -slp-threshold=-200 -mtriple=x86_64-unknown-linux -mcpu=core-avx2 -S < %s | FileCheck %s

define void @test(ptr %p0, ptr %p1, ptr %dst, i32 %a0, i32 %a1, i32 %a2, i32 %a3) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[P0:%.*]], ptr [[P1:%.*]], ptr [[DST:%.*]], i32 [[A0:%.*]], i32 [[A1:%.*]], i32 [[A2:%.*]], i32 [[A3:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[Q1:%.*]] = getelementptr i32, ptr [[P0]], i32 2
; CHECK-NEXT:    [[Q2:%.*]] = getelementptr i32, ptr [[P0]], i32 3
; CHECK-NEXT:    [[R1:%.*]] = getelementptr i32, ptr [[P1]], i32 2
; CHECK-NEXT:    [[R2:%.*]] = getelementptr i32, ptr [[P1]], i32 3
; CHECK-NEXT:    [[X2:%.*]] = load i32, ptr [[Q1]], align 4
; CHECK-NEXT:    [[X3:%.*]] = load i32, ptr [[Q2]], align 4
; CHECK-NEXT:    [[Y2:%.*]] = load i32, ptr [[R1]], align 4
; CHECK-NEXT:    [[Y3:%.*]] = load i32, ptr [[R2]], align 4
; CHECK-NEXT:    [[C2:%.*]] = sub i32 [[X2]], [[Y2]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x i32>, ptr [[P0]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i32>, ptr [[P1]], align 4
; CHECK-NEXT:    [[RES2:%.*]] = udiv i32 [[C2]], [[A2]]
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[RES2]], i32 2
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[X3]], i32 3
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP0]], <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i32> [[TMP7]], <4 x i32> [[TMP8]], <4 x i32> <i32 4, i32 5, i32 2, i32 3>
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <4 x i32> <i32 poison, i32 poison, i32 0, i32 poison>, i32 [[Y3]], i32 3
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <4 x i32> [[TMP6]], <4 x i32> [[TMP13]], <4 x i32> <i32 4, i32 5, i32 2, i32 3>
; CHECK-NEXT:    [[TMP15:%.*]] = sub <4 x i32> [[TMP9]], [[TMP14]]
; CHECK-NEXT:    [[TMP16:%.*]] = insertelement <4 x i32> <i32 poison, i32 poison, i32 0, i32 poison>, i32 [[A0]], i32 0
; CHECK-NEXT:    [[TMP11:%.*]] = insertelement <4 x i32> [[TMP16]], i32 [[A1]], i32 1
; CHECK-NEXT:    [[TMP12:%.*]] = insertelement <4 x i32> [[TMP11]], i32 [[A3]], i32 3
; CHECK-NEXT:    [[TMP10:%.*]] = add <4 x i32> [[TMP15]], [[TMP12]]
; CHECK-NEXT:    store <4 x i32> [[TMP10]], ptr [[DST]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %q0 = getelementptr i32, ptr %p0, i32 1
  %q1 = getelementptr i32, ptr %p0, i32 2
  %q2 = getelementptr i32, ptr %p0, i32 3
  %r0 = getelementptr i32, ptr %p1, i32 1
  %r1 = getelementptr i32, ptr %p1, i32 2
  %r2 = getelementptr i32, ptr %p1, i32 3
  %d1 = getelementptr i32, ptr %dst, i32 1
  %d2 = getelementptr i32, ptr %dst, i32 2
  %d3 = getelementptr i32, ptr %dst, i32 3

  %x0 = load i32, ptr %p0
  %x1 = load i32, ptr %q0
  %x2 = load i32, ptr %q1
  %x3 = load i32, ptr %q2
  %y0 = load i32, ptr %p1
  %y1 = load i32, ptr %r0
  %y2 = load i32, ptr %r1
  %y3 = load i32, ptr %r2

  %c0 = sub i32 %x0, %y0
  %c1 = sub i32 %x1, %y1
  %c2 = sub i32 %x2, %y2
  %c3 = sub i32 %x3, %y3

  ; All lanes: outer add except lane 2 (udiv = copyable).
  ; Lanes 0,3: (sub_result, arg).  Lane 1: (arg, sub_result) = reversed.
  %res0 = add i32 %c0, %a0
  %res1 = add i32 %a1, %c1
  %res2 = udiv i32 %c2, %a2
  %res3 = add i32 %c3, %a3

  store i32 %res0, ptr %dst
  store i32 %res1, ptr %d1
  store i32 %res2, ptr %d2
  store i32 %res3, ptr %d3
  ret void
}

define void @test_baseline(ptr %p0, ptr %p1, ptr %dst, i32 %a0, i32 %a1, i32 %a2, i32 %a3) {
; CHECK-LABEL: define void @test_baseline(
; CHECK-SAME: ptr [[P0:%.*]], ptr [[P1:%.*]], ptr [[DST:%.*]], i32 [[A0:%.*]], i32 [[A1:%.*]], i32 [[A2:%.*]], i32 [[A3:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[Q1:%.*]] = getelementptr i32, ptr [[P0]], i32 2
; CHECK-NEXT:    [[Q2:%.*]] = getelementptr i32, ptr [[P0]], i32 3
; CHECK-NEXT:    [[R1:%.*]] = getelementptr i32, ptr [[P1]], i32 2
; CHECK-NEXT:    [[R2:%.*]] = getelementptr i32, ptr [[P1]], i32 3
; CHECK-NEXT:    [[X2:%.*]] = load i32, ptr [[Q1]], align 4
; CHECK-NEXT:    [[X3:%.*]] = load i32, ptr [[Q2]], align 4
; CHECK-NEXT:    [[Y2:%.*]] = load i32, ptr [[R1]], align 4
; CHECK-NEXT:    [[Y3:%.*]] = load i32, ptr [[R2]], align 4
; CHECK-NEXT:    [[C2:%.*]] = sub i32 [[X2]], [[Y2]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x i32>, ptr [[P0]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i32>, ptr [[P1]], align 4
; CHECK-NEXT:    [[RES2:%.*]] = udiv i32 [[C2]], [[A2]]
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[RES2]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[X3]], i32 3
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i32> [[TMP0]], <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> [[TMP4]], <4 x i32> <i32 4, i32 5, i32 2, i32 3>
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <4 x i32> <i32 poison, i32 poison, i32 0, i32 poison>, i32 [[Y3]], i32 3
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i32> [[TMP6]], <4 x i32> [[TMP7]], <4 x i32> <i32 4, i32 5, i32 2, i32 3>
; CHECK-NEXT:    [[TMP9:%.*]] = sub <4 x i32> [[TMP5]], [[TMP8]]
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <4 x i32> <i32 poison, i32 poison, i32 0, i32 poison>, i32 [[A0]], i32 0
; CHECK-NEXT:    [[TMP11:%.*]] = insertelement <4 x i32> [[TMP10]], i32 [[A1]], i32 1
; CHECK-NEXT:    [[TMP12:%.*]] = insertelement <4 x i32> [[TMP11]], i32 [[A3]], i32 3
; CHECK-NEXT:    [[TMP13:%.*]] = add <4 x i32> [[TMP9]], [[TMP12]]
; CHECK-NEXT:    store <4 x i32> [[TMP13]], ptr [[DST]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %q0 = getelementptr i32, ptr %p0, i32 1
  %q1 = getelementptr i32, ptr %p0, i32 2
  %q2 = getelementptr i32, ptr %p0, i32 3
  %r0 = getelementptr i32, ptr %p1, i32 1
  %r1 = getelementptr i32, ptr %p1, i32 2
  %r2 = getelementptr i32, ptr %p1, i32 3
  %d1 = getelementptr i32, ptr %dst, i32 1
  %d2 = getelementptr i32, ptr %dst, i32 2
  %d3 = getelementptr i32, ptr %dst, i32 3

  %x0 = load i32, ptr %p0
  %x1 = load i32, ptr %q0
  %x2 = load i32, ptr %q1
  %x3 = load i32, ptr %q2
  %y0 = load i32, ptr %p1
  %y1 = load i32, ptr %r0
  %y2 = load i32, ptr %r1
  %y3 = load i32, ptr %r2

  %c0 = sub i32 %x0, %y0
  %c1 = sub i32 %x1, %y1
  %c2 = sub i32 %x2, %y2
  %c3 = sub i32 %x3, %y3

  ; ALL consistent: (sub_result, arg)
  %res0 = add i32 %c0, %a0
  %res1 = add i32 %c1, %a1
  %res2 = udiv i32 %c2, %a2
  %res3 = add i32 %c3, %a3

  store i32 %res0, ptr %dst
  store i32 %res1, ptr %d1
  store i32 %res2, ptr %d2
  store i32 %res3, ptr %d3
  ret void
}

