; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-apple-macosx12.0.0 < %s | FileCheck %s

define float @test1(<2 x float> %retval.i69.sroa.0.0.copyload.i.i) {
; CHECK-LABEL: define float @test1(
; CHECK-SAME: <2 x float> [[RETVAL_I69_SROA_0_0_COPYLOAD_I_I:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <2 x float> [[RETVAL_I69_SROA_0_0_COPYLOAD_I_I]], <2 x float> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP1:%.*]] = fadd <4 x float> [[TMP0]], zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x float> [[TMP1]], i32 0
; CHECK-NEXT:    [[TMP3:%.*]] = call float @llvm.vector.reduce.fadd.v4f32(float [[TMP2]], <4 x float> [[TMP1]])
; CHECK-NEXT:    ret float [[TMP3]]
;
entry:
  %a.i.sroa.5.8.vec.extract.i.i = extractelement <2 x float> %retval.i69.sroa.0.0.copyload.i.i, i64 0
  %a.i.sroa.0.0.vec.extract.i.i = extractelement <2 x float> %retval.i69.sroa.0.0.copyload.i.i, i64 0
  %add.i629.i.i = fadd float %a.i.sroa.0.0.vec.extract.i.i, 0.000000e+00
  %a.i616.sroa.0.4.vec.extract.i.i = extractelement <2 x float> %retval.i69.sroa.0.0.copyload.i.i, i64 0
  %add.i629.1.i.i = fadd float %a.i616.sroa.0.4.vec.extract.i.i, 0.000000e+00
  %add.i597.1.i.i = fadd float %add.i629.1.i.i, %add.i629.1.i.i
  %a.i616.sroa.8.12.vec.extract.i.i = extractelement <2 x float> %retval.i69.sroa.0.0.copyload.i.i, i64 0
  %add.i629.3.i.i = fadd float %a.i616.sroa.8.12.vec.extract.i.i, 0.000000e+00
  %add.i629.2.i.i = fadd float %a.i.sroa.5.8.vec.extract.i.i, 0.000000e+00
  %add.i195.1.i.i = fadd float %add.i629.i.i, %add.i597.1.i.i
  %add.i195.2.i.i = fadd float %add.i629.2.i.i, %add.i195.1.i.i
  %add.i195.3.i.i = fadd float %add.i629.3.i.i, %add.i195.2.i.i
  ret float %add.i195.3.i.i
}

define float @test2(<2 x float> %retval.i69.sroa.0.0.copyload.i.i) {
; CHECK-LABEL: define float @test2(
; CHECK-SAME: <2 x float> [[RETVAL_I69_SROA_0_0_COPYLOAD_I_I:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <2 x float> [[RETVAL_I69_SROA_0_0_COPYLOAD_I_I]], <2 x float> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP1:%.*]] = fadd <4 x float> [[TMP0]], <float -0.000000e+00, float 0.000000e+00, float 0.000000e+00, float -0.000000e+00>
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x float> [[TMP1]], <4 x float> <float 0.000000e+00, float poison, float poison, float 0.000000e+00>, <4 x i32> <i32 4, i32 1, i32 2, i32 7>
; CHECK-NEXT:    [[TMP3:%.*]] = fadd <4 x float> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x float> [[TMP3]], i32 0
; CHECK-NEXT:    [[OP_RDX:%.*]] = fadd float 1.000000e+00, [[TMP4]]
; CHECK-NEXT:    [[TMP5:%.*]] = call float @llvm.vector.reduce.fadd.v4f32(float [[OP_RDX]], <4 x float> [[TMP3]])
; CHECK-NEXT:    ret float [[TMP5]]
;
entry:
  %a.i.sroa.5.8.vec.extract.i.i = extractelement <2 x float> %retval.i69.sroa.0.0.copyload.i.i, i64 0
  %add.i629.2.i.i = fadd float %a.i.sroa.5.8.vec.extract.i.i, 0.000000e+00
  %a.i.sroa.0.0.vec.extract.i.i = extractelement <2 x float> %retval.i69.sroa.0.0.copyload.i.i, i64 0
  %add.i629.i.i = fadd float %a.i.sroa.0.0.vec.extract.i.i, 0.000000e+00
  %add.i597.i.i = fadd float %add.i629.i.i, %add.i629.i.i
  %a.i616.sroa.0.4.vec.extract.i.i = extractelement <2 x float> %retval.i69.sroa.0.0.copyload.i.i, i64 0
  %add.i629.1.i.i = fadd float %a.i616.sroa.0.4.vec.extract.i.i, 0.000000e+00
  %add.i725.1.i.i = fadd float %add.i629.1.i.i, 1.000000e+00
  %add.i597.1.i.i = fadd float %add.i629.1.i.i, %add.i725.1.i.i
  %a.i616.sroa.8.12.vec.extract.i.i = extractelement <2 x float> %retval.i69.sroa.0.0.copyload.i.i, i64 0
  %add.i629.3.i.i = fadd float %a.i616.sroa.8.12.vec.extract.i.i, 0.000000e+00
  %add.i597.2.i.i = fadd float %add.i629.2.i.i, %add.i629.2.i.i
  %add.i195.1.i.i = fadd float %add.i597.i.i, %add.i597.1.i.i
  %add.i195.2.i.i = fadd float %add.i597.2.i.i, %add.i195.1.i.i
  %add.i195.3.i.i = fadd float %add.i629.3.i.i, %add.i195.2.i.i
  ret float %add.i195.3.i.i
}
