; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt --passes=slp-vectorizer -S -mattr=+avx -mtriple=x86_64-unknown-linux-gnu < %s -slp-threshold=-10 | FileCheck %s


define void @test(ptr %arg3, double %load.2.i, double %load.i, double %fadd10.i.i) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[ARG3:%.*]], double [[LOAD_2_I:%.*]], double [[LOAD_I:%.*]], double [[FADD10_I_I:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[BB:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load <4 x double>, ptr [[ARG3]], align 8
; CHECK-NEXT:    [[GETELEMENTPTR_4_I:%.*]] = getelementptr i8, ptr [[ARG3]], i64 32
; CHECK-NEXT:    [[LOAD_4_I:%.*]] = load double, ptr [[GETELEMENTPTR_4_I]], align 8
; CHECK-NEXT:    [[GETELEMENTPTR_5_I:%.*]] = getelementptr i8, ptr [[ARG3]], i64 40
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x double>, ptr [[GETELEMENTPTR_5_I]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <2 x double> [[TMP1]], <2 x double> poison, <2 x i32> <i32 1, i32 0>
; CHECK-NEXT:    [[GETELEMENTPTR_7_I:%.*]] = getelementptr i8, ptr [[ARG3]], i64 56
; CHECK-NEXT:    [[LOAD_7_I:%.*]] = load double, ptr [[GETELEMENTPTR_7_I]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <2 x double> poison, double [[LOAD_4_I]], i32 0
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <2 x double> [[TMP3]], double [[LOAD_7_I]], i32 1
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x double> poison, double [[LOAD_I]], i32 0
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x double> poison, double [[LOAD_2_I]], i32 0
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <2 x double> [[TMP6]], double [[FADD10_I_I]], i32 1
; CHECK-NEXT:    br label %[[BB7:.*]]
; CHECK:       [[BB7]]:
; CHECK-NEXT:    [[TMP8:%.*]] = phi <2 x double> [ [[TMP4]], %[[BB]] ], [ [[TMP17:%.*]], %[[BB7]] ]
; CHECK-NEXT:    [[TMP9:%.*]] = phi <2 x double> [ [[TMP2]], %[[BB]] ], [ [[TMP15:%.*]], %[[BB7]] ]
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <2 x double> [[TMP8]], <2 x double> poison, <4 x i32> <i32 1, i32 poison, i32 poison, i32 0>
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <2 x double> [[TMP9]], <2 x double> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <4 x double> [[TMP10]], <4 x double> [[TMP11]], <4 x i32> <i32 0, i32 4, i32 5, i32 3>
; CHECK-NEXT:    [[TMP13:%.*]] = fmul <4 x double> [[TMP0]], [[TMP12]]
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <4 x double> [[TMP13]], <4 x double> poison, <4 x i32> <i32 3, i32 0, i32 2, i32 1>
; CHECK-NEXT:    [[TMP14:%.*]] = call double @llvm.vector.reduce.fadd.v4f64(double -0.000000e+00, <4 x double> [[TMP18]])
; CHECK-NEXT:    [[TMP15]] = fadd <2 x double> [[TMP7]], <double 0.000000e+00, double -0.000000e+00>
; CHECK-NEXT:    [[TMP16:%.*]] = insertelement <2 x double> [[TMP5]], double [[TMP14]], i32 1
; CHECK-NEXT:    [[TMP17]] = fadd <2 x double> [[TMP16]], zeroinitializer
; CHECK-NEXT:    br label %[[BB7]]
;
bb:
  %load.i1 = load double, ptr %arg3, align 8
  %getelementptr.1.i = getelementptr i8, ptr %arg3, i64 8
  %load.1.i = load double, ptr %getelementptr.1.i, align 8
  %getelementptr.2.i = getelementptr i8, ptr %arg3, i64 16
  %load.2.i2 = load double, ptr %getelementptr.2.i, align 8
  %getelementptr.3.i = getelementptr i8, ptr %arg3, i64 24
  %load.3.i = load double, ptr %getelementptr.3.i, align 8
  %getelementptr.4.i = getelementptr i8, ptr %arg3, i64 32
  %load.4.i = load double, ptr %getelementptr.4.i, align 8
  %getelementptr.5.i = getelementptr i8, ptr %arg3, i64 40
  %load.5.i = load double, ptr %getelementptr.5.i, align 8
  %getelementptr.6.i = getelementptr i8, ptr %arg3, i64 48
  %load.6.i = load double, ptr %getelementptr.6.i, align 8
  %getelementptr.7.i = getelementptr i8, ptr %arg3, i64 56
  %load.7.i = load double, ptr %getelementptr.7.i, align 8
  br label %bb7

bb7:
  %fadd.i3.i111 = phi double [ %load.4.i, %bb ], [ %fadd.i3.i, %bb7 ]
  %fadd19.i.i210 = phi double [ %load.7.i, %bb ], [ %fadd19.i.i, %bb7 ]
  %fadd10.i.i39 = phi double [ %load.5.i, %bb ], [ %fadd10.i.i, %bb7 ]
  %fadd16.i.i48 = phi double [ %load.6.i, %bb ], [ %fadd16.i.i, %bb7 ]
  %fmul.i.i = fmul double %load.3.i, %fadd.i3.i111
  %fmul18.i.i = fmul double %load.i1, %fadd19.i.i210
  %fadd.i.i = fadd double %fmul.i.i, %fmul18.i.i
  %fmul21.i.i = fmul double %load.2.i2, %fadd10.i.i39
  %fadd22.i.i = fadd double %fadd.i.i, %fmul21.i.i
  %fmul25.i.i = fmul double %load.1.i, %fadd16.i.i48
  %fadd26.i.i = fadd double %fadd22.i.i, %fmul25.i.i
  %fadd.i3.i = fadd double %load.i, 0.000000e+00
  %fadd16.i.i = fadd double %load.2.i, 0.000000e+00
  %fadd19.i.i = fadd double %fadd26.i.i, 0.000000e+00
  br label %bb7
}
