; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt --passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define double @test(double %0) {
; CHECK-LABEL: define double @test(
; CHECK-SAME: double [[TMP0:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <2 x double> <double 1.000000e+00, double poison>, double [[TMP0]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = fmul <2 x double> zeroinitializer, [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <2 x double> [[TMP2]], <2 x double> poison, <4 x i32> <i32 0, i32 1, i32 1, i32 1>
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x double> [[TMP3]], i32 1
; CHECK-NEXT:    [[TMP5:%.*]] = call reassoc double @llvm.vector.reduce.fadd.v4f64(double -0.000000e+00, <4 x double> [[TMP3]])
; CHECK-NEXT:    [[OP_RDX:%.*]] = fadd reassoc double [[TMP5]], [[TMP4]]
; CHECK-NEXT:    ret double [[OP_RDX]]
;
entry:
  %1 = fmul double %0, 0.000000e+00
  %2 = fadd reassoc double %1, 0.000000e+00
  %3 = fadd reassoc double %1, %2
  %4 = fadd reassoc double %1, %3
  %5 = fadd reassoc double %1, %4
  ret double %5
}
