; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define void @test(i32 %julianDay, i1 %cmp, i8 %0, i16 %1) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i32 [[JULIANDAY:%.*]], i1 [[CMP:%.*]], i8 [[TMP0:%.*]], i16 [[TMP1:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_THEN2:.*]], label %[[IF_END33:.*]]
; CHECK:       [[IF_THEN2]]:
; CHECK-NEXT:    [[CONV_I:%.*]] = sext i8 [[TMP0]] to i32
; CHECK-NEXT:    [[CONV_I2:%.*]] = sext i16 [[TMP1]] to i32
; CHECK-NEXT:    br label %[[IF_END33]]
; CHECK:       [[IF_END33]]:
; CHECK-NEXT:    [[MONTH_0:%.*]] = phi i32 [ [[CONV_I]], %[[IF_THEN2]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[DAYOFMONTH_0:%.*]] = phi i32 [ [[CONV_I]], %[[IF_THEN2]] ], [ [[JULIANDAY]], %[[ENTRY]] ]
; CHECK-NEXT:    [[DAYOFYEAR_0:%.*]] = phi i32 [ [[CONV_I2]], %[[IF_THEN2]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    store volatile i32 [[MONTH_0]], ptr null, align 4294967296
; CHECK-NEXT:    store volatile i32 [[DAYOFMONTH_0]], ptr null, align 4294967296
; CHECK-NEXT:    store volatile i32 [[DAYOFYEAR_0]], ptr null, align 4294967296
; CHECK-NEXT:    ret void
;
entry:
  br i1 %cmp, label %if.then2, label %if.end33

if.then2:
  %conv.i = sext i8 %0 to i32
  %conv.i2 = sext i16 %1 to i32
  br label %if.end33

if.end33:
  %month.0 = phi i32 [ %conv.i, %if.then2 ], [ 0, %entry ]
  %dayOfMonth.0 = phi i32 [ %conv.i, %if.then2 ], [ %julianDay, %entry ]
  %dayOfYear.0 = phi i32 [ %conv.i2, %if.then2 ], [ 0, %entry ]
  store volatile i32 %month.0, ptr null, align 4294967296
  store volatile i32 %dayOfMonth.0, ptr null, align 4294967296
  store volatile i32 %dayOfYear.0, ptr null, align 4294967296
  ret void
}
