; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -mtriple=x86_64-unknown-linux-gnu -mcpu=icelake-server -passes=slp-vectorizer -S | FileCheck %s

declare double @llvm.sqrt.f64(double)

define void @prim(double %x, double %y, double %z, double %w, ptr %p0, ptr %p1) {
; CHECK-LABEL: define void @prim(
; CHECK-SAME: double [[X:%.*]], double [[Y:%.*]], double [[Z:%.*]], double [[W:%.*]], ptr [[P0:%.*]], ptr [[P1:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[X1:%.*]] = fsub double [[X]], [[Z]]
; CHECK-NEXT:    [[Y1:%.*]] = fadd double [[Y]], [[W]]
; CHECK-NEXT:    [[TMP8:%.*]] = fdiv double [[X1]], [[Z]]
; CHECK-NEXT:    [[TMP9:%.*]] = fdiv double [[Y1]], [[W]]
; CHECK-NEXT:    [[X3:%.*]] = fsub double [[TMP8]], [[Z]]
; CHECK-NEXT:    [[Y3:%.*]] = fadd double [[TMP9]], [[W]]
; CHECK-NEXT:    store double [[X3]], ptr [[P0]], align 8
; CHECK-NEXT:    store double [[Y3]], ptr [[P1]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %x1 = fsub double %x, %z
  %y1 = fadd double %y, %w
  %x2 = fdiv double %x1, %z
  %y2 = fdiv double %y1, %w
  %x3 = fsub double %x2, %z
  %y3 = fadd double %y2, %w
  store double %x3, ptr %p0
  store double %y3, ptr %p1
  ret void
}

define void @prim_sqrt(double %x, double %y, double %z, double %w, ptr %p0, ptr %p1) {
; CHECK-LABEL: define void @prim_sqrt(
; CHECK-SAME: double [[X:%.*]], double [[Y:%.*]], double [[Z:%.*]], double [[W:%.*]], ptr [[P0:%.*]], ptr [[P1:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[X1:%.*]] = fsub double [[X]], [[Z]]
; CHECK-NEXT:    [[Y1:%.*]] = fadd double [[Y]], [[W]]
; CHECK-NEXT:    [[TMP8:%.*]] = call double @llvm.sqrt.f64(double [[X1]])
; CHECK-NEXT:    [[TMP9:%.*]] = call double @llvm.sqrt.f64(double [[Y1]])
; CHECK-NEXT:    [[X3:%.*]] = fsub double [[TMP8]], [[Z]]
; CHECK-NEXT:    [[Y3:%.*]] = fadd double [[TMP9]], [[W]]
; CHECK-NEXT:    store double [[X3]], ptr [[P0]], align 8
; CHECK-NEXT:    store double [[Y3]], ptr [[P1]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %x1 = fsub double %x, %z
  %y1 = fadd double %y, %w
  %x2 = call double @llvm.sqrt.f64(double %x1)
  %y2 = call double @llvm.sqrt.f64(double %y1)
  %x3 = fsub double %x2, %z
  %y3 = fadd double %y2, %w
  store double %x3, ptr %p0
  store double %y3, ptr %p1
  ret void
}

define void @prim_v4(double %x0, double %x1, double %x2, double %x3, double %d0, double %d1, double %d2, double %d3, ptr %p0, ptr %p1, ptr %p2, ptr %p3) {
; CHECK-LABEL: define void @prim_v4(
; CHECK-SAME: double [[X0:%.*]], double [[X1:%.*]], double [[X2:%.*]], double [[X3:%.*]], double [[D0:%.*]], double [[D1:%.*]], double [[D2:%.*]], double [[D3:%.*]], ptr [[P0:%.*]], ptr [[P1:%.*]], ptr [[P2:%.*]], ptr [[P3:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A0:%.*]] = fsub double [[X0]], [[D0]]
; CHECK-NEXT:    [[A1:%.*]] = fadd double [[X1]], [[D1]]
; CHECK-NEXT:    [[A2:%.*]] = fsub double [[X2]], [[D2]]
; CHECK-NEXT:    [[A3:%.*]] = fadd double [[X3]], [[D3]]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x double> poison, double [[A1]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <4 x double> [[TMP0]], double [[A3]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <4 x double> [[TMP1]], double [[A0]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <4 x double> [[TMP2]], double [[A2]], i32 3
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <4 x double> poison, double [[D1]], i32 0
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <4 x double> [[TMP4]], double [[D3]], i32 1
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <4 x double> [[TMP5]], double [[D0]], i32 2
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <4 x double> [[TMP6]], double [[D2]], i32 3
; CHECK-NEXT:    [[TMP8:%.*]] = fdiv <4 x double> [[TMP3]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = fadd <4 x double> [[TMP8]], [[TMP7]]
; CHECK-NEXT:    [[TMP10:%.*]] = fsub <4 x double> [[TMP8]], [[TMP7]]
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <4 x double> [[TMP9]], <4 x double> [[TMP10]], <4 x i32> <i32 0, i32 1, i32 6, i32 7>
; CHECK-NEXT:    [[TMP14:%.*]] = extractelement <4 x double> [[TMP11]], i32 2
; CHECK-NEXT:    store double [[TMP14]], ptr [[P0]], align 8
; CHECK-NEXT:    [[TMP15:%.*]] = extractelement <4 x double> [[TMP11]], i32 0
; CHECK-NEXT:    store double [[TMP15]], ptr [[P1]], align 8
; CHECK-NEXT:    [[TMP16:%.*]] = extractelement <4 x double> [[TMP11]], i32 3
; CHECK-NEXT:    store double [[TMP16]], ptr [[P2]], align 8
; CHECK-NEXT:    [[TMP17:%.*]] = extractelement <4 x double> [[TMP11]], i32 1
; CHECK-NEXT:    store double [[TMP17]], ptr [[P3]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %a0 = fsub double %x0, %d0
  %a1 = fadd double %x1, %d1
  %a2 = fsub double %x2, %d2
  %a3 = fadd double %x3, %d3
  %q0 = fdiv double %a0, %d0
  %q1 = fdiv double %a1, %d1
  %q2 = fdiv double %a2, %d2
  %q3 = fdiv double %a3, %d3
  %r0 = fsub double %q0, %d0
  %r1 = fadd double %q1, %d1
  %r2 = fsub double %q2, %d2
  %r3 = fadd double %q3, %d3
  store double %r0, ptr %p0
  store double %r1, ptr %p1
  store double %r2, ptr %p2
  store double %r3, ptr %p3
  ret void
}
