; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -slp-threshold=1 -mtriple=x86_64 < %s | FileCheck %s

@c = global ptr null
@e = global ptr null
@a = external global i16
@f = external global i16

define void @test(ptr %j, ptr %b) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[J:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[SCEVGEP5:%.*]] = getelementptr i8, ptr [[B]], i16 8
; CHECK-NEXT:    [[SCEVGEP6:%.*]] = getelementptr i8, ptr [[J]], i16 4
; CHECK-NEXT:    [[BOUND038:%.*]] = icmp ult ptr @a, getelementptr inbounds nuw (i8, ptr @f, i16 1)
; CHECK-NEXT:    [[BOUND139:%.*]] = icmp ult ptr @f, getelementptr inbounds nuw (i8, ptr @a, i16 1)
; CHECK-NEXT:    [[FOUND_CONFLICT40:%.*]] = and i1 [[BOUND038]], [[BOUND139]]
; CHECK-NEXT:    [[BOUND042:%.*]] = icmp ugt ptr [[SCEVGEP5]], @a
; CHECK-NEXT:    [[BOUND143:%.*]] = icmp ult ptr [[B]], getelementptr inbounds nuw (i8, ptr @a, i16 1)
; CHECK-NEXT:    [[FOUND_CONFLICT44:%.*]] = and i1 [[BOUND042]], [[BOUND143]]
; CHECK-NEXT:    [[BOUND046:%.*]] = icmp ugt ptr [[SCEVGEP6]], @a
; CHECK-NEXT:    [[BOUND147:%.*]] = icmp ult ptr [[J]], getelementptr inbounds nuw (i8, ptr @a, i16 1)
; CHECK-NEXT:    [[FOUND_CONFLICT48:%.*]] = and i1 [[BOUND046]], [[BOUND147]]
; CHECK-NEXT:    [[BOUND050:%.*]] = icmp ugt ptr [[SCEVGEP5]], @f
; CHECK-NEXT:    [[BOUND151:%.*]] = icmp ult ptr [[B]], getelementptr inbounds nuw (i8, ptr @f, i16 1)
; CHECK-NEXT:    [[FOUND_CONFLICT52:%.*]] = and i1 [[BOUND050]], [[BOUND151]]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x ptr> <ptr poison, ptr getelementptr inbounds nuw (i8, ptr @a, i64 1), ptr getelementptr inbounds nuw (i8, ptr @f, i64 1), ptr poison>, ptr [[SCEVGEP5]], i32 3
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <4 x ptr> <ptr poison, ptr @a, ptr @f, ptr poison>, ptr [[B]], i32 3
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr @c, align 1
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr @e, align 1
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[TMP2]], i16 1
; CHECK-NEXT:    [[SCEVGEP4:%.*]] = getelementptr i8, ptr [[TMP3]], i16 4
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <4 x ptr> poison, ptr [[TMP2]], i32 0
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x ptr> [[TMP4]], <4 x ptr> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <4 x ptr> [[TMP0]], ptr [[SCEVGEP4]], i32 0
; CHECK-NEXT:    [[TMP7:%.*]] = icmp ult <4 x ptr> [[TMP5]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x ptr> [[TMP1]], ptr [[TMP3]], i32 0
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <4 x ptr> poison, ptr [[SCEVGEP]], i32 0
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x ptr> [[TMP9]], <4 x ptr> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP11:%.*]] = icmp ult <4 x ptr> [[TMP8]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = and <4 x i1> [[TMP7]], [[TMP11]]
; CHECK-NEXT:    [[BOUND022:%.*]] = icmp ult ptr [[TMP3]], getelementptr inbounds nuw (i8, ptr @a, i16 1)
; CHECK-NEXT:    [[BOUND123:%.*]] = icmp ugt ptr [[SCEVGEP4]], @a
; CHECK-NEXT:    [[FOUND_CONFLICT24:%.*]] = and i1 [[BOUND022]], [[BOUND123]]
; CHECK-NEXT:    [[BOUND026:%.*]] = icmp ult ptr [[TMP3]], getelementptr inbounds nuw (i8, ptr @f, i16 1)
; CHECK-NEXT:    [[BOUND127:%.*]] = icmp ugt ptr [[SCEVGEP4]], @f
; CHECK-NEXT:    [[FOUND_CONFLICT28:%.*]] = and i1 [[BOUND026]], [[BOUND127]]
; CHECK-NEXT:    [[BOUND030:%.*]] = icmp ult ptr [[TMP3]], [[SCEVGEP5]]
; CHECK-NEXT:    [[BOUND131:%.*]] = icmp ult ptr [[B]], [[SCEVGEP4]]
; CHECK-NEXT:    [[FOUND_CONFLICT32:%.*]] = and i1 [[BOUND030]], [[BOUND131]]
; CHECK-NEXT:    [[TMP13:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP12]])
; CHECK-NEXT:    [[OP_RDX:%.*]] = or i1 [[TMP13]], [[FOUND_CONFLICT24]]
; CHECK-NEXT:    [[OP_RDX1:%.*]] = or i1 [[FOUND_CONFLICT28]], [[FOUND_CONFLICT32]]
; CHECK-NEXT:    [[OP_RDX2:%.*]] = or i1 [[FOUND_CONFLICT40]], [[FOUND_CONFLICT44]]
; CHECK-NEXT:    [[OP_RDX3:%.*]] = or i1 [[FOUND_CONFLICT48]], [[FOUND_CONFLICT52]]
; CHECK-NEXT:    [[OP_RDX4:%.*]] = or i1 [[OP_RDX]], [[OP_RDX1]]
; CHECK-NEXT:    [[OP_RDX5:%.*]] = or i1 [[OP_RDX2]], [[OP_RDX3]]
; CHECK-NEXT:    [[OP_RDX6:%.*]] = or i1 [[OP_RDX4]], [[OP_RDX5]]
; CHECK-NEXT:    br i1 [[OP_RDX6]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %scevgep5 = getelementptr i8, ptr %b, i16 8
  %scevgep6 = getelementptr i8, ptr %j, i16 4
  %bound038 = icmp ult ptr @a, getelementptr inbounds nuw (i8, ptr @f, i16 1)
  %bound139 = icmp ult ptr @f, getelementptr inbounds nuw (i8, ptr @a, i16 1)
  %found.conflict40 = and i1 %bound038, %bound139
  %bound042 = icmp ugt ptr %scevgep5, @a
  %bound143 = icmp ult ptr %b, getelementptr inbounds nuw (i8, ptr @a, i16 1)
  %found.conflict44 = and i1 %bound042, %bound143
  %invariant.op = or i1 %found.conflict40, %found.conflict44
  %bound046 = icmp ugt ptr %scevgep6, @a
  %bound147 = icmp ult ptr %j, getelementptr inbounds nuw (i8, ptr @a, i16 1)
  %found.conflict48 = and i1 %bound046, %bound147
  %invariant.op58 = or i1 %invariant.op, %found.conflict48
  %bound050 = icmp ugt ptr %scevgep5, @f
  %bound151 = icmp ult ptr %b, getelementptr inbounds nuw (i8, ptr @f, i16 1)
  %found.conflict52 = and i1 %bound050, %bound151
  %invariant.op60 = or i1 %invariant.op58, %found.conflict52
  br label %loop

loop:
  %0 = load ptr, ptr @c, align 1
  %1 = load ptr, ptr @e, align 1
  %scevgep = getelementptr i8, ptr %0, i16 1
  %scevgep4 = getelementptr i8, ptr %1, i16 4
  %bound0 = icmp ult ptr %0, %scevgep4
  %bound1 = icmp ult ptr %1, %scevgep
  %found.conflict = and i1 %bound0, %bound1
  %bound07 = icmp ult ptr %0, getelementptr inbounds nuw (i8, ptr @a, i16 1)
  %bound18 = icmp ugt ptr %scevgep, @a
  %found.conflict9 = and i1 %bound07, %bound18
  %conflict.rdx = or i1 %found.conflict, %found.conflict9
  %bound010 = icmp ult ptr %0, getelementptr inbounds nuw (i8, ptr @f, i16 1)
  %bound111 = icmp ugt ptr %scevgep, @f
  %found.conflict12 = and i1 %bound010, %bound111
  %conflict.rdx13 = or i1 %conflict.rdx, %found.conflict12
  %bound014 = icmp ult ptr %0, %scevgep5
  %bound115 = icmp ult ptr %b, %scevgep
  %found.conflict16 = and i1 %bound014, %bound115
  %conflict.rdx17 = or i1 %conflict.rdx13, %found.conflict16
  %bound022 = icmp ult ptr %1, getelementptr inbounds nuw (i8, ptr @a, i16 1)
  %bound123 = icmp ugt ptr %scevgep4, @a
  %found.conflict24 = and i1 %bound022, %bound123
  %conflict.rdx25 = or i1 %conflict.rdx17, %found.conflict24
  %bound026 = icmp ult ptr %1, getelementptr inbounds nuw (i8, ptr @f, i16 1)
  %bound127 = icmp ugt ptr %scevgep4, @f
  %found.conflict28 = and i1 %bound026, %bound127
  %conflict.rdx29 = or i1 %conflict.rdx25, %found.conflict28
  %bound030 = icmp ult ptr %1, %scevgep5
  %bound131 = icmp ult ptr %b, %scevgep4
  %found.conflict32 = and i1 %bound030, %bound131
  %conflict.rdx33 = or i1 %conflict.rdx29, %found.conflict32
  %conflict.rdx57.reass = or i1 %conflict.rdx33, %invariant.op60
  br i1 %conflict.rdx57.reass, label %loop, label %exit

exit:
  ret void
}
