; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define i80 @test(i8 %0, i80 %.sroa.0.7.insert.ext) {
; CHECK-LABEL: define i80 @test(
; CHECK-SAME: i8 [[TMP0:%.*]], i80 [[DOTSROA_0_7_INSERT_EXT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <4 x i8> poison, i8 [[TMP0]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i8> [[TMP1]], <4 x i8> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @llvm.bswap.i32(i32 [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = zext i32 [[TMP4]] to i128
; CHECK-NEXT:    [[TMP6:%.*]] = trunc i128 [[TMP5]] to i80
; CHECK-NEXT:    [[OP_RDX:%.*]] = or disjoint i80 [[TMP6]], [[DOTSROA_0_7_INSERT_EXT]]
; CHECK-NEXT:    ret i80 [[OP_RDX]]
;
entry:
  %.sroa.0.6.insert.ext = zext i8 %0 to i80
  %.sroa.0.3.insert.ext = zext i8 %0 to i80
  %.sroa.0.3.insert.shift = shl nuw nsw i80 %.sroa.0.3.insert.ext, 24
  %.sroa.0.2.insert.ext = zext i8 %0 to i80
  %.sroa.0.2.insert.shift = shl nuw nsw i80 %.sroa.0.2.insert.ext, 16
  %.sroa.0.1.insert.ext = zext i8 %0 to i80
  %.sroa.0.1.insert.shift = shl nuw nsw i80 %.sroa.0.1.insert.ext, 8
  %1 = or disjoint i80 %.sroa.0.7.insert.ext, %.sroa.0.6.insert.ext
  %.sroa.0.3.insert.insert = or disjoint i80 %.sroa.0.3.insert.shift, %.sroa.0.2.insert.shift
  %.sroa.0.8.insert.mask = or disjoint i80 %1, %.sroa.0.3.insert.insert
  %.sroa.0.4.insert.mask69 = or disjoint i80 %.sroa.0.1.insert.shift, %.sroa.0.8.insert.mask
  ret i80 %.sroa.0.4.insert.mask69
}
