; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define i16 @test(i32 %call5, i32 %add36) {
; CHECK-LABEL: define i16 @test(
; CHECK-SAME: i32 [[CALL5:%.*]], i32 [[ADD36:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <8 x i32> <i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 poison, i32 0, i32 poison>, i32 [[CALL5]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <8 x i32> [[TMP0]], i32 [[ADD36]], i32 5
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[TMP1]], <8 x i32> poison, <8 x i32> <i32 0, i32 0, i32 2, i32 3, i32 4, i32 5, i32 6, i32 0>
; CHECK-NEXT:    [[TMP3:%.*]] = icmp ne <8 x i32> <i32 1, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 1>, [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <8 x i1> [[TMP3]], i32 6
; CHECK-NEXT:    [[COND3:%.*]] = zext i1 [[TMP4]] to i16
; CHECK-NEXT:    [[TOBOOL48_NOT:%.*]] = icmp eq i32 0, 0
; CHECK-NEXT:    [[COND7:%.*]] = zext i1 [[TOBOOL48_NOT]] to i16
; CHECK-NEXT:    [[CMP21:%.*]] = icmp ne i32 0, 0
; CHECK-NEXT:    [[COND26:%.*]] = select i1 [[CMP21]], i16 0, i16 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <8 x i1> [[TMP3]], i32 5
; CHECK-NEXT:    [[COND42:%.*]] = select i1 [[TMP5]], i16 0, i16 0
; CHECK-NEXT:    [[TMP12:%.*]] = select <8 x i1> [[TMP3]], <8 x i16> <i16 1, i16 1, i16 1, i16 0, i16 0, i16 1, i16 0, i16 0>, <8 x i16> <i16 0, i16 0, i16 0, i16 1, i16 1, i16 0, i16 0, i16 0>
; CHECK-NEXT:    [[TMP13:%.*]] = call i16 @llvm.vector.reduce.add.v8i16(<8 x i16> [[TMP12]])
; CHECK-NEXT:    [[OP_RDX:%.*]] = add i16 [[TMP13]], [[COND3]]
; CHECK-NEXT:    [[OP_RDX1:%.*]] = add i16 [[COND7]], [[COND26]]
; CHECK-NEXT:    [[OP_RDX2:%.*]] = add i16 [[OP_RDX]], [[OP_RDX1]]
; CHECK-NEXT:    [[OP_RDX3:%.*]] = add i16 [[OP_RDX2]], [[COND42]]
; CHECK-NEXT:    ret i16 [[OP_RDX3]]
;
entry:
  %cmp = icmp ne i32 0, 0
  %cond1 = select i1 %cmp, i16 0, i16 0
  %cond3 = zext i1 %cmp to i16
  %add4 = add i16 %cond1, %cond3
  %tobool6.not = icmp eq i32 0, 0
  %cond7 = zext i1 %tobool6.not to i16
  %add8 = add i16 %add4, %cond7
  %cmp9 = icmp ne i32 %call5, 1
  %conv. = select i1 %cmp9, i16 0, i16 0
  %add11 = add i16 %add8, %conv.
  %cond14 = zext i1 %cmp9 to i16
  %add15 = add i16 %add11, %cond14
  %cmp17 = icmp ne i32 %call5, 0
  %cond19 = zext i1 %cmp17 to i16
  %add20 = add i16 %add15, %cond19
  %cmp21 = icmp ne i32 0, 0
  %cond26 = select i1 %cmp21, i16 0, i16 0
  %add27 = add i16 %add20, %cond26
  %cond30 = zext i1 %cmp21 to i16
  %add31 = add i16 %add27, %cond30
  %tobool32.not = icmp eq i32 0, 0
  %cond33 = zext i1 %tobool32.not to i16
  %add34 = add i16 %add31, %cond33
  %tobool48.not = icmp eq i32 0, 0
  %cond49 = zext i1 %tobool48.not to i16
  %add43 = add i16 %add34, %cond49
  %cmp37 = icmp ne i32 %add36, 0
  %cond42 = select i1 %cmp37, i16 0, i16 0
  %add47 = add i16 %add43, %cond42
  %cond46 = zext i1 %cmp37 to i16
  %add50 = add i16 %add47, %cond46
  ret i16 %add50
}
