; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -slp-threshold=-5 -mtriple=x86_64-unknown-linux-gnu -mcpu=icelake-server < %s | FileCheck %s

define double @test(double %0) {
; CHECK-LABEL: define double @test(
; CHECK-SAME: double [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <2 x double> <double poison, double 1.000000e+00>, double [[TMP0]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = fmul <2 x double> [[TMP1]], zeroinitializer
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <2 x double> [[TMP2]], <2 x double> poison, <8 x i32> <i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 1>
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <8 x double> [[TMP3]], i32 0
; CHECK-NEXT:    [[ADD35_I_31721:%.*]] = fadd double [[TMP4]], 0.000000e+00
; CHECK-NEXT:    [[ADD35_I_1_3:%.*]] = fadd double [[ADD35_I_31721]], [[TMP4]]
; CHECK-NEXT:    [[ADD35_I_2_2:%.*]] = fadd double [[ADD35_I_31721]], [[ADD35_I_1_3]]
; CHECK-NEXT:    [[ADD35_I_4_1:%.*]] = fadd double [[ADD35_I_2_2]], [[ADD35_I_2_2]]
; CHECK-NEXT:    [[ADD35_I_6_1:%.*]] = fadd double [[ADD35_I_4_1]], [[ADD35_I_31721]]
; CHECK-NEXT:    ret double [[ADD35_I_6_1]]
;
entry:
  %mul.i1377.4 = fmul double %0, 0.000000e+00
  %add35.i.31721 = fadd double %mul.i1377.4, 0.000000e+00
  %add35.i.1.3 = fadd double %add35.i.31721, %mul.i1377.4
  %add35.i.2.2 = fadd double %add35.i.31721, %add35.i.1.3
  %add35.i.4.1 = fadd double %add35.i.2.2, %add35.i.2.2
  %add35.i.6.1 = fadd double %add35.i.4.1, %add35.i.31721
  ret double %add35.i.6.1
}
