; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define i32 @test(i32 %v4) {
; CHECK-LABEL: define i32 @test(
; CHECK-SAME: i32 [[V4:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[REM23:%.*]] = select i1 false, i32 0, i32 0
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x i32> <i32 1, i32 poison>, i32 [[V4]], i32 1
; CHECK-NEXT:    [[TMP1:%.*]] = select <2 x i1> zeroinitializer, <2 x i32> [[TMP0]], <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> poison, <8 x i32> <i32 0, i32 1, i32 1, i32 0, i32 0, i32 1, i32 1, i32 1>
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> poison, <2 x i32> <i32 1, i32 poison>
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <2 x i32> [[TMP3]], i32 [[REM23]], i32 1
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <2 x i32> [[TMP4]], <2 x i32> poison, <4 x i32> <i32 0, i32 0, i32 1, i32 1>
; CHECK-NEXT:    [[TMP6:%.*]] = mul <4 x i32> [[TMP5]], zeroinitializer
; CHECK-NEXT:    [[TMP7:%.*]] = urem <4 x i32> [[TMP6]], splat (i32 46337)
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i32> [[TMP7]], <4 x i32> poison, <8 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i32> [[TMP7]], <4 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i32> [[TMP9]], <8 x i32> <i32 0, i32 0, i32 poison, i32 poison, i32 21110, i32 poison, i32 poison, i32 0>, <8 x i32> <i32 8, i32 9, i32 0, i32 1, i32 12, i32 2, i32 3, i32 15>
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <2 x i32> [[TMP4]], <2 x i32> poison, <8 x i32> <i32 0, i32 0, i32 0, i32 0, i32 1, i32 1, i32 0, i32 0>
; CHECK-NEXT:    [[TMP14:%.*]] = mul <8 x i32> [[TMP10]], [[TMP13]]
; CHECK-NEXT:    [[TMP15:%.*]] = trunc <8 x i32> [[TMP14]] to <8 x i16>
; CHECK-NEXT:    [[TMP16:%.*]] = urem <8 x i16> [[TMP15]], <i16 1, i16 1, i16 -19199, i16 -19199, i16 -19199, i16 1, i16 1, i16 1>
; CHECK-NEXT:    [[TMP17:%.*]] = mul <8 x i32> <i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 1>, [[TMP2]]
; CHECK-NEXT:    [[TMP18:%.*]] = urem <8 x i32> [[TMP17]], splat (i32 1)
; CHECK-NEXT:    [[TMP19:%.*]] = trunc <8 x i32> [[TMP18]] to <8 x i16>
; CHECK-NEXT:    [[TMP20:%.*]] = mul <8 x i16> [[TMP19]], zeroinitializer
; CHECK-NEXT:    [[TMP21:%.*]] = urem <8 x i16> [[TMP20]], <i16 1, i16 1, i16 1, i16 1, i16 -19199, i16 1, i16 1, i16 1>
; CHECK-NEXT:    [[TMP22:%.*]] = mul <8 x i16> [[TMP16]], <i16 0, i16 0, i16 0, i16 0, i16 1, i16 0, i16 0, i16 0>
; CHECK-NEXT:    [[TMP23:%.*]] = urem <8 x i16> [[TMP22]], <i16 1, i16 1, i16 1, i16 1, i16 -19199, i16 1, i16 1, i16 1>
; CHECK-NEXT:    [[TMP24:%.*]] = or <8 x i16> [[TMP21]], [[TMP23]]
; CHECK-NEXT:    [[TMP25:%.*]] = add <8 x i16> [[TMP21]], [[TMP23]]
; CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <8 x i16> [[TMP24]], <8 x i16> [[TMP25]], <8 x i32> <i32 0, i32 9, i32 2, i32 11, i32 4, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[TMP27:%.*]] = zext <8 x i16> [[TMP26]] to <8 x i32>
; CHECK-NEXT:    [[TMP28:%.*]] = freeze <8 x i32> [[TMP27]]
; CHECK-NEXT:    [[TMP29:%.*]] = select <8 x i1> <i1 false, i1 false, i1 false, i1 false, i1 true, i1 false, i1 false, i1 false>, <8 x i32> [[TMP28]], <8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP30:%.*]] = or <8 x i32> [[TMP29]], <i32 0, i32 0, i32 0, i32 0, i32 39609, i32 0, i32 0, i32 0>
; CHECK-NEXT:    [[TMP31:%.*]] = urem <8 x i32> [[TMP30]], splat (i32 46337)
; CHECK-NEXT:    [[TMP32:%.*]] = icmp ult <8 x i32> [[TMP31]], zeroinitializer
; CHECK-NEXT:    ret i32 0
;
entry:
  %rem28.cmp = icmp slt i32 0, 0
  %rem28 = select i1 %rem28.cmp, i32 %v4, i32 1
  %mul102 = mul i32 %rem28, 0
  %rem103 = urem i32 %mul102, 1
  %mul89 = mul i32 %rem28, 1
  %rem90 = urem i32 %mul89, 1
  %mul97 = mul i32 0, %rem90
  %rem98 = urem i32 %mul97, 1
  %mul110 = mul i32 0, %rem103
  %rem111 = urem i32 %mul110, 1
  %add112 = add i32 %rem98, %rem111
  %add112.frozen = freeze i32 %add112
  %rem113 = select i1 false, i32 %add112.frozen, i32 0
  %rem123 = urem i32 %rem113, 46337
  %rem125.cmp = icmp ult i32 %rem123, 0
  %rem23 = select i1 false, i32 0, i32 0
  %mul339 = mul i32 %rem23, 0
  %rem340 = urem i32 %mul339, 46337
  %mul344 = mul i32 %rem28, %rem340
  %rem345 = urem i32 %mul344, 1
  %mul354 = mul i32 %rem28, 0
  %rem355 = urem i32 %mul354, 1
  %mul362 = mul i32 0, %rem355
  %rem363 = urem i32 %mul362, 1
  %mul349 = mul i32 %rem345, 0
  %rem350 = urem i32 %mul349, 1
  %add364 = add i32 %rem363, %rem350
  %add364.frozen = freeze i32 %add364
  %rem365 = select i1 false, i32 %add364.frozen, i32 0
  %rem372 = urem i32 %rem365, 46337
  %rem374.cmp = icmp ult i32 %rem372, 0
  %mul378 = mul i32 %rem23, 0
  %rem379 = urem i32 %mul378, 46337
  %mul383 = mul i32 %rem379, %rem23
  %rem384 = urem i32 %mul383, 1
  %mul393 = mul i32 %rem28, 0
  %rem394 = urem i32 %mul393, 1
  %mul398 = mul i32 %rem394, 0
  %rem399 = urem i32 %mul398, 1
  %mul388 = mul i32 %rem384, 0
  %rem389 = urem i32 %mul388, 1
  %add400 = add i32 %rem399, %rem389
  %add400.frozen = freeze i32 %add400
  %rem401 = select i1 false, i32 %add400.frozen, i32 0
  %rem408 = urem i32 %rem401, 46337
  %rem410.cmp = icmp ult i32 %rem408, 0
  %rem3.cmp = icmp slt i32 0, 0
  %mul519 = mul i32 %rem23, 21110
  %rem520 = urem i32 %mul519, 46337
  %rem3 = select i1 %rem3.cmp, i32 1, i32 0
  %mul506 = mul i32 %rem3, 0
  %rem507 = urem i32 %mul506, 1
  %mul514 = mul i32 %rem507, 0
  %rem515 = urem i32 %mul514, 46337
  %mul527 = mul i32 1, %rem520
  %rem528 = urem i32 %mul527, 46337
  %add529 = or i32 %rem515, %rem528
  %add529.frozen = freeze i32 %add529
  %rem530 = select i1 true, i32 %add529.frozen, i32 0
  %add536 = or i32 %rem530, 39609
  %rem537 = urem i32 %add536, 46337
  %rem539.cmp = icmp ult i32 %rem537, 0
  %mul543 = mul i32 %rem28, 0
  %rem544 = urem i32 %mul543, 46337
  %mul548 = mul i32 %rem544, %rem28
  %rem549 = urem i32 %mul548, 46337
  %mul564 = mul i32 %rem3, 0
  %rem565 = urem i32 %mul564, 1
  %mul572 = mul i32 %rem565, 0
  %rem573 = urem i32 %mul572, 1
  %mul556 = mul i32 0, %rem549
  %rem557 = urem i32 %mul556, 1
  %add574 = add i32 %rem573, %rem557
  %add574.frozen = freeze i32 %add574
  %rem575 = select i1 false, i32 %add574.frozen, i32 0
  %rem582 = urem i32 %rem575, 46337
  %rem584.cmp = icmp ult i32 %rem582, 0
  %mul720 = mul i32 %rem28, 0
  %rem721 = urem i32 %mul720, 46337
  %mul725 = mul i32 %rem721, %rem28
  %rem726 = urem i32 %mul725, 46337
  %mul735 = mul i32 %rem28, 0
  %rem736 = urem i32 %mul735, 1
  %mul743 = mul i32 0, %rem736
  %rem744 = urem i32 %mul743, 1
  %mul730 = mul i32 %rem726, 0
  %rem731 = urem i32 %mul730, 1
  %add745 = or i32 %rem744, %rem731
  %add745.frozen = freeze i32 %add745
  %rem746 = select i1 false, i32 %add745.frozen, i32 0
  %rem753 = urem i32 %rem746, 46337
  %rem755.cmp = icmp ult i32 %rem753, 0
  %mul777 = mul i32 %rem28, 0
  %rem778 = urem i32 %mul777, 1
  %mul764 = mul i32 0, %rem28
  %rem765 = urem i32 %mul764, 1
  %mul772 = mul i32 0, %rem765
  %rem773 = urem i32 %mul772, 1
  %mul785 = mul i32 0, %rem778
  %rem786 = urem i32 %mul785, 1
  %add787 = add i32 %rem773, %rem786
  %add787.frozen = freeze i32 %add787
  %rem788 = select i1 false, i32 %add787.frozen, i32 0
  %rem795 = urem i32 %rem788, 46337
  %rem797.cmp = icmp ult i32 %rem795, 0
  %mul861 = mul i32 %rem28, 0
  %rem862 = urem i32 %mul861, 1
  %mul848 = mul i32 %rem3, 0
  %rem849 = urem i32 %mul848, 1
  %mul856 = mul i32 %rem849, 0
  %rem857 = urem i32 %mul856, 1
  %mul869 = mul i32 0, %rem862
  %rem870 = urem i32 %mul869, 1
  %add871 = or i32 %rem857, %rem870
  %add871.frozen = freeze i32 %add871
  %rem872 = select i1 false, i32 %add871.frozen, i32 0
  %rem882 = urem i32 %rem872, 46337
  %rem884.cmp = icmp ult i32 %rem882, 0
  ret i32 0
}
