; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt --passes=slp-vectorizer -S -slp-revec -slp-vectorize-non-power-of-2 -mtriple=x86_64-pc-windows-gnu -mcpu=alderlake < %s | FileCheck %s

define float @test(ptr %0, double %1, double %2, double %3) {
; CHECK-LABEL: define float @test(
; CHECK-SAME: ptr [[TMP0:%.*]], double [[TMP1:%.*]], double [[TMP2:%.*]], double [[TMP3:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP5:%.*]] = fmul double [[TMP1]], 0.000000e+00
; CHECK-NEXT:    [[TMP6:%.*]] = fmul double [[TMP1]], 0.000000e+00
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <3 x double> poison, double [[TMP3]], i32 0
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <3 x double> [[TMP7]], double [[TMP2]], i32 1
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <3 x double> [[TMP8]], double [[TMP1]], i32 2
; CHECK-NEXT:    [[TMP10:%.*]] = fmul <3 x double> [[TMP9]], zeroinitializer
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <3 x double> [[TMP9]], <3 x double> poison, <3 x i32> <i32 1, i32 0, i32 2>
; CHECK-NEXT:    [[TMP14:%.*]] = fmul <3 x double> [[TMP13]], zeroinitializer
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i8, ptr [[TMP0]], i64 1356
; CHECK-NEXT:    [[TMP18:%.*]] = fmul double [[TMP1]], 0.000000e+00
; CHECK-NEXT:    [[TMP17:%.*]] = insertelement <3 x double> <double -0.000000e+00, double poison, double -0.000000e+00>, double [[TMP6]], i32 1
; CHECK-NEXT:    [[TMP16:%.*]] = insertelement <3 x double> <double poison, double poison, double -0.000000e+00>, double [[TMP1]], i32 1
; CHECK-NEXT:    [[TMP19:%.*]] = insertelement <3 x double> [[TMP16]], double [[TMP18]], i32 0
; CHECK-NEXT:    [[TMP20:%.*]] = fadd <3 x double> [[TMP17]], [[TMP19]]
; CHECK-NEXT:    [[TMP21:%.*]] = insertelement <3 x double> <double 0.000000e+00, double poison, double 0.000000e+00>, double [[TMP5]], i32 1
; CHECK-NEXT:    [[TMP22:%.*]] = fadd <3 x double> [[TMP21]], [[TMP20]]
; CHECK-NEXT:    [[TMP23:%.*]] = fadd <3 x double> [[TMP14]], [[TMP22]]
; CHECK-NEXT:    [[TMP24:%.*]] = fadd <3 x double> [[TMP10]], [[TMP23]]
; CHECK-NEXT:    [[TMP25:%.*]] = fptrunc <3 x double> [[TMP24]] to <3 x float>
; CHECK-NEXT:    store <3 x float> [[TMP25]], ptr [[TMP15]], align 4
; CHECK-NEXT:    [[TMP26:%.*]] = extractelement <3 x float> [[TMP25]], i32 0
; CHECK-NEXT:    ret float [[TMP26]]
;
  %5 = fmul double %1, 0.000000e+00
  %6 = fmul double %1, 0.000000e+00
  %7 = fmul double %1, 0.000000e+00
  %8 = fadd double %7, %1
  %9 = fmul double %3, 0.000000e+00
  %10 = fmul double %2, 0.000000e+00
  %11 = fadd double %5, 0.000000e+00
  %12 = fadd double %10, %11
  %13 = fadd double %9, %12
  %14 = fptrunc double %13 to float
  %15 = getelementptr i8, ptr %0, i64 1356
  store float %14, ptr %15, align 4
  %16 = fmul double %2, 0.000000e+00
  %17 = fmul double %3, 0.000000e+00
  %18 = fadd double %6, %8
  %19 = fadd double %17, %18
  %20 = fadd double %16, %19
  %21 = fptrunc double %20 to float
  %22 = getelementptr i8, ptr %0, i64 1360
  store float %21, ptr %22, align 4
  %23 = fmul double %1, 0.000000e+00
  %24 = fmul double %1, 0.000000e+00
  %25 = fadd double %24, 0.000000e+00
  %26 = fadd double %23, %25
  %27 = fptrunc double %26 to float
  %28 = getelementptr i8, ptr %0, i64 1364
  store float %27, ptr %28, align 4
  ret float %14
}

