; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu -mcpu=x86-64-v3 -slp-revec -S < %s | FileCheck %s

define dso_local <2 x float> @fma_f32(ptr %A, float %B) {
; CHECK-LABEL: @fma_f32(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[REAL:%.*]] = load float, ptr [[A:%.*]], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 4
; CHECK-NEXT:    [[IMAG:%.*]] = load float, ptr [[TMP0]], align 4
; CHECK-NEXT:    [[MUL_R:%.*]] = fmul reassoc nsz contract float [[REAL]], 2.000000e+00
; CHECK-NEXT:    [[MUL_I:%.*]] = fmul reassoc nsz contract float [[IMAG]], 2.000000e+00
; CHECK-NEXT:    [[ADD_R:%.*]] = fadd reassoc nsz contract float [[MUL_R]], [[B:%.*]]
; CHECK-NEXT:    [[V0:%.*]] = insertelement <2 x float> poison, float [[ADD_R]], i64 0
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <2 x float> [[V0]], float [[MUL_I]], i64 1
; CHECK-NEXT:    ret <2 x float> [[TMP3]]
;
entry:
  %real = load float, ptr %A, align 4
  %0 = getelementptr inbounds nuw i8, ptr %A, i64 4
  %imag = load float, ptr %0, align 4
  %mul.r = fmul reassoc nsz contract float %real, 2.000000e+00
  %mul.i = fmul reassoc nsz contract float %imag, 2.000000e+00
  %add.r = fadd reassoc nsz contract float %mul.r, %B
  %v0 = insertelement <2 x float> poison, float %add.r, i64 0
  %v1 = insertelement <2 x float> %v0, float %mul.i, i64 1
  ret <2 x float> %v1
}
