; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define void @test(ptr %0, ptr %1, float %.sroa.3232.0.copyload) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[TMP0:%.*]], ptr [[TMP1:%.*]], float [[DOTSROA_3232_0_COPYLOAD:%.*]]) {
; CHECK-NEXT:  [[BB:.*:]]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[TMP1]], i64 12
; CHECK-NEXT:    [[TMP3:%.*]] = load <2 x float>, ptr [[TMP0]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = fmul <2 x float> [[TMP3]], <float 0.000000e+00, float 1.000000e+00>
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x float> [[TMP3]], <2 x float> <float 0.000000e+00, float poison>, <2 x i32> <i32 2, i32 1>
; CHECK-NEXT:    [[TMP5:%.*]] = fmul <2 x float> [[TMP3]], [[TMP4]]
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x float> [[TMP3]], float [[DOTSROA_3232_0_COPYLOAD]], i32 0
; CHECK-NEXT:    [[TMP8:%.*]] = fmul <2 x float> [[TMP6]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x float> [[TMP6]], <2 x float> <float poison, float 0.000000e+00>, <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP10:%.*]] = fmul <2 x float> [[TMP5]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <2 x float> [[TMP10]], <2 x float> poison, <2 x i32> <i32 1, i32 0>
; CHECK-NEXT:    [[TMP12:%.*]] = fmul <2 x float> [[TMP8]], zeroinitializer
; CHECK-NEXT:    [[TMP13:%.*]] = fmul <2 x float> [[TMP12]], zeroinitializer
; CHECK-NEXT:    [[TMP14:%.*]] = fmul <2 x float> [[TMP13]], zeroinitializer
; CHECK-NEXT:    [[TMP15:%.*]] = fadd <2 x float> [[TMP14]], [[TMP11]]
; CHECK-NEXT:    [[TMP16:%.*]] = fadd <2 x float> [[TMP15]], zeroinitializer
; CHECK-NEXT:    [[TMP17:%.*]] = fadd <2 x float> [[TMP16]], splat (float 1.000000e+00)
; CHECK-NEXT:    store <2 x float> [[TMP17]], ptr [[TMP2]], align 4
; CHECK-NEXT:    ret void
;
bb:
  %.sroa.3232.0.copyload2 = load float, ptr %0, align 4
  %2 = fmul float %.sroa.3232.0.copyload2, 0.000000e+00
  %3 = fmul float %.sroa.3232.0.copyload, %2
  %.sroa.2.0..sroa_idx = getelementptr i8, ptr %0, i64 4
  %.sroa.2.0.copyload1 = load float, ptr %.sroa.2.0..sroa_idx, align 4
  %4 = fmul float %3, 0.000000e+00
  %5 = fmul float %4, 0.000000e+00
  %6 = fmul float %5, 0.000000e+00
  %7 = fmul float %.sroa.2.0.copyload1, %.sroa.2.0.copyload1
  %8 = fmul float %7, 0.000000e+00
  %9 = fadd float %6, %8
  %10 = fadd float %9, 0.000000e+00
  %11 = fadd float %10, 1.000000e+00
  %12 = getelementptr i8, ptr %1, i64 12
  store float %11, ptr %12, align 4
  %13 = fmul float %8, 0.000000e+00
  %14 = fmul float %13, 0.000000e+00
  %15 = fadd float %14, %3
  %16 = fadd float %15, 0.000000e+00
  %17 = fadd float %16, 1.000000e+00
  %18 = getelementptr i8, ptr %1, i64 16
  store float %17, ptr %18, align 4
  ret void
}
