; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu -mcpu=icelake-server -slp-threshold=-5 < %s | FileCheck %s

@st = external global [4 x [4 x i32]]

define i32 @test(i32 %0, i32 %1) {
; CHECK-LABEL: define i32 @test(
; CHECK-SAME: i32 [[TMP0:%.*]], i32 [[TMP1:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <2 x i32> poison, i32 [[TMP0]], i32 0
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <2 x i32> [[TMP3]], i32 [[TMP1]], i32 1
; CHECK-NEXT:    [[TMP7:%.*]] = add <2 x i32> [[TMP3]], [[TMP4]]
; CHECK-NEXT:    [[DOTNEG_NEG:%.*]] = shl i32 [[TMP0]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = load <2 x i32>, ptr getelementptr inbounds nuw (i8, ptr @st, i64 8), align 8
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr getelementptr inbounds nuw (i8, ptr @st, i64 12), align 4
; CHECK-NEXT:    [[SUB120_3:%.*]] = or i32 [[TMP5]], [[DOTNEG_NEG]]
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP6]], <2 x i32> poison, <8 x i32> <i32 0, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> <i32 poison, i32 poison, i32 poison, i32 0, i32 poison, i32 poison, i32 0, i32 0>, <8 x i32> <i32 0, i32 1, i32 poison, i32 11, i32 poison, i32 poison, i32 14, i32 15>
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <8 x i32> [[TMP9]], i32 [[TMP0]], i32 2
; CHECK-NEXT:    [[TMP11:%.*]] = insertelement <8 x i32> [[TMP10]], i32 [[SUB120_3]], i32 5
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <8 x i32> [[TMP11]], <8 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 2, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <8 x i32> [[TMP11]], <8 x i32> poison, <5 x i32> <i32 2, i32 poison, i32 poison, i32 5, i32 poison>
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <5 x i32> [[TMP13]], i32 [[DOTNEG_NEG]], i32 1
; CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <2 x i32> [[TMP7]], <2 x i32> poison, <5 x i32> <i32 0, i32 poison, i32 1, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <5 x i32> [[TMP14]], <5 x i32> [[TMP15]], <5 x i32> <i32 0, i32 1, i32 5, i32 3, i32 7>
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <5 x i32> [[TMP16]], <5 x i32> poison, <8 x i32> <i32 0, i32 1, i32 0, i32 2, i32 0, i32 3, i32 4, i32 2>
; CHECK-NEXT:    [[TMP18:%.*]] = sub <8 x i32> [[TMP12]], [[TMP17]]
; CHECK-NEXT:    [[TMP19:%.*]] = add <8 x i32> [[TMP12]], [[TMP17]]
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <8 x i32> [[TMP18]], <8 x i32> [[TMP19]], <8 x i32> <i32 0, i32 9, i32 10, i32 3, i32 12, i32 13, i32 6, i32 7>
; CHECK-NEXT:    store <8 x i32> [[TMP20]], ptr getelementptr inbounds nuw (i8, ptr @st, i64 8), align 8
; CHECK-NEXT:    ret i32 0
;
entry:
  %add110 = add i32 %0, %1
  %sub124 = sub i32 0, %add110
  store i32 %sub124, ptr getelementptr inbounds nuw (i8, ptr @st, i64 32), align 16
  %shl127 = shl i32 %0, 1
  store i32 %shl127, ptr getelementptr inbounds nuw (i8, ptr @st, i64 16), align 16
  %shl.2 = shl i32 %0, 1
  %sub124.1 = sub i32 0, %shl.2
  store i32 %sub124.1, ptr getelementptr inbounds nuw (i8, ptr @st, i64 36), align 4
  %sub115.1 = sub i32 0, %shl.2
  store i32 %sub115.1, ptr getelementptr inbounds nuw (i8, ptr @st, i64 20), align 4
  %2 = load i32, ptr getelementptr inbounds nuw (i8, ptr @st, i64 8), align 8
  %add105.2 = sub i32 %2, %0
  store i32 %add105.2, ptr getelementptr inbounds nuw (i8, ptr @st, i64 8), align 8
  %shl127.2 = shl i32 %0, 1
  store i32 %shl127.2, ptr getelementptr inbounds nuw (i8, ptr @st, i64 24), align 8
  %.neg.neg = shl i32 %0, 1
  %3 = load i32, ptr getelementptr inbounds nuw (i8, ptr @st, i64 12), align 4
  %add105.3 = add i32 %.neg.neg, %3
  store i32 %add105.3, ptr getelementptr inbounds nuw (i8, ptr @st, i64 12), align 4
  %sub120.3 = or i32 %3, %.neg.neg
  %shl127.3 = shl i32 %sub120.3, 1
  store i32 %shl127.3, ptr getelementptr inbounds nuw (i8, ptr @st, i64 28), align 4
  ret i32 0
}

define i32 @test1(ptr %0, ptr %1, i32 %2) {
; CHECK-LABEL: define i32 @test1(
; CHECK-SAME: ptr [[TMP0:%.*]], ptr [[TMP1:%.*]], i32 [[TMP2:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP0]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x i32> poison, i32 [[TMP2]], i32 1
; CHECK-NEXT:    [[ADD53_1:%.*]] = add i32 [[TMP4]], [[TMP2]]
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <2 x i32> [[TMP6]], i32 [[TMP3]], i32 0
; CHECK-NEXT:    [[TMP8:%.*]] = add <2 x i32> [[TMP7]], splat (i32 1)
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i32> <i32 poison, i32 0>, i32 [[ADD53_1]], i32 0
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i32> [[TMP6]], <2 x i32> [[TMP8]], <2 x i32> <i32 2, i32 1>
; CHECK-NEXT:    [[TMP10:%.*]] = sub <2 x i32> [[TMP5]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x i32> [[TMP10]], i32 1
; CHECK-NEXT:    [[SHL_1:%.*]] = shl i32 [[TMP11]], 1
; CHECK-NEXT:    [[TMP12:%.*]] = insertelement <2 x i32> poison, i32 [[ADD53_1]], i32 0
; CHECK-NEXT:    [[TMP13:%.*]] = insertelement <2 x i32> [[TMP12]], i32 [[SHL_1]], i32 1
; CHECK-NEXT:    [[TMP14:%.*]] = or <2 x i32> [[TMP8]], [[TMP13]]
; CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <2 x i32> [[TMP7]], <2 x i32> <i32 1, i32 poison>, <2 x i32> <i32 2, i32 1>
; CHECK-NEXT:    [[TMP16:%.*]] = add <2 x i32> [[TMP14]], [[TMP15]]
; CHECK-NEXT:    [[TMP17:%.*]] = or <2 x i32> [[TMP14]], [[TMP15]]
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <2 x i32> [[TMP16]], <2 x i32> [[TMP17]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP19:%.*]] = extractelement <2 x i32> [[TMP10]], i32 0
; CHECK-NEXT:    store i32 [[TMP19]], ptr @st, align 8
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <2 x i32> [[TMP18]], <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <2 x i32> [[TMP10]], <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <4 x i32> [[TMP20]], <4 x i32> [[TMP21]], <4 x i32> <i32 0, i32 1, i32 4, i32 5>
; CHECK-NEXT:    [[TMP23:%.*]] = or <4 x i32> [[TMP22]], splat (i32 1)
; CHECK-NEXT:    store <4 x i32> [[TMP23]], ptr getelementptr inbounds nuw (i8, ptr @st, i64 16), align 16
; CHECK-NEXT:    ret i32 0
;
entry:
  %3 = load i32, ptr %0, align 8
  %4 = load i32, ptr %1, align 4
  %sub80.1 = sub i32 0, %2
  %add62.1 = add i32 %3, 1
  %add53.1 = add i32 %4, %2
  %add81.1 = or i32 %add62.1, %add53.1
  %sub115 = add i32 %add81.1, 1
  %add128 = or i32 %sub115, 1
  store i32 %add128, ptr getelementptr inbounds nuw (i8, ptr @st, i64 16), align 16
  %sub71.11 = add i32 %2, 1
  %shl.1 = shl i32 %sub80.1, 1
  %add89.1 = or i32 %sub71.11, %shl.1
  %sub115.1 = or i32 %add89.1, %2
  %add128.1 = or i32 %sub115.1, 1
  store i32 %add128.1, ptr getelementptr inbounds nuw (i8, ptr @st, i64 20), align 4
  %sub85.1 = sub i32 %add53.1, %add62.1
  store i32 %sub85.1, ptr @st, align 8
  %add128.2 = or i32 %sub85.1, 1
  store i32 %add128.2, ptr getelementptr inbounds nuw (i8, ptr @st, i64 24), align 8
  %sub94.1 = or i32 %sub80.1, 1
  store i32 %sub94.1, ptr getelementptr inbounds nuw (i8, ptr @st, i64 28), align 4
  ret i32 0
}

define i32 @test2(i32 %0) {
; CHECK-LABEL: define i32 @test2(
; CHECK-SAME: i32 [[TMP0:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <4 x i32> <i32 0, i32 poison, i32 poison, i32 poison>, i32 [[TMP0]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> poison, <4 x i32> <i32 0, i32 1, i32 1, i32 1>
; CHECK-NEXT:    [[TMP3:%.*]] = or <4 x i32> <i32 0, i32 1, i32 0, i32 1>, [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> poison, <4 x i32> <i32 1, i32 2, i32 2, i32 2>
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i32> [[TMP4]], <4 x i32> <i32 poison, i32 poison, i32 1, i32 1>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
; CHECK-NEXT:    [[TMP6:%.*]] = add <4 x i32> [[TMP4]], [[TMP5]]
; CHECK-NEXT:    [[TMP7:%.*]] = or <4 x i32> [[TMP4]], [[TMP5]]
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <4 x i32> [[TMP6]], <4 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 6, i32 3>
; CHECK-NEXT:    [[TMP11:%.*]] = shl i32 [[TMP0]], 1
; CHECK-NEXT:    store i32 [[TMP11]], ptr getelementptr inbounds nuw (i8, ptr @st, i64 20), align 4
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> <i32 0, i32 poison, i32 0, i32 poison>, <4 x i32> <i32 4, i32 1, i32 6, i32 2>
; CHECK-NEXT:    [[TMP15:%.*]] = add <4 x i32> [[TMP3]], [[TMP9]]
; CHECK-NEXT:    [[TMP18:%.*]] = sub <4 x i32> [[TMP15]], [[TMP17]]
; CHECK-NEXT:    [[TMP19:%.*]] = add <4 x i32> [[TMP15]], [[TMP17]]
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <4 x i32> [[TMP18]], <4 x i32> [[TMP19]], <4 x i32> <i32 0, i32 5, i32 6, i32 7>
; CHECK-NEXT:    store <4 x i32> [[TMP20]], ptr @st, align 4
; CHECK-NEXT:    ret i32 0
;
entry:
  %sub80.3 = or i32 %0, 1
  %add110.3 = add i32 %0, 1
  %add110.2 = or i32 %0, 1
  %shl.1 = shl i32 %0, 1
  store i32 %shl.1, ptr getelementptr inbounds nuw (i8, ptr @st, i64 20), align 4
  %add105.3 = add i32 %sub80.3, %0
  %shl.3 = shl i32 %sub80.3, 1
  %add121.3 = add i32 %add110.3, %add105.3
  %add121.2 = add i32 %add110.2, %0
  %add121.1 = add i32 %shl.1, %shl.3
  %sub120.1 = sub i32 0, %shl.3
  %1 = insertelement <4 x i32> poison, i32 %sub120.1, i32 0
  %2 = insertelement <4 x i32> %1, i32 %add121.1, i32 1
  %3 = insertelement <4 x i32> %2, i32 %add121.2, i32 2
  %4 = insertelement <4 x i32> %3, i32 %add121.3, i32 3
  store <4 x i32> %4, ptr @st, align 4
  ret i32 0
}

