; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define i32 @test(ptr %img, i32 %0) {
; CHECK-LABEL: define i32 @test(
; CHECK-SAME: ptr [[IMG:%.*]], i32 [[TMP0:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ADD65:%.*]] = add i32 [[TMP0]], 1
; CHECK-NEXT:    [[ADD47_1_1:%.*]] = or i32 [[TMP0]], 1
; CHECK-NEXT:    [[ADD65_1:%.*]] = add i32 [[ADD47_1_1]], 2
; CHECK-NEXT:    [[SUB146:%.*]] = sub i32 [[ADD65]], [[ADD65_1]]
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[IMG]], align 8
; CHECK-NEXT:    [[ARRAYIDX150:%.*]] = getelementptr i8, ptr [[TMP1]], i64 13120
; CHECK-NEXT:    store i32 [[SUB146]], ptr [[ARRAYIDX150]], align 8
; CHECK-NEXT:    [[MUL152:%.*]] = shl i32 [[ADD65]], 1
; CHECK-NEXT:    [[ADD154:%.*]] = or i32 [[MUL152]], [[ADD65_1]]
; CHECK-NEXT:    [[INVARIANT_GEP_16:%.*]] = getelementptr i8, ptr [[TMP1]], i64 13116
; CHECK-NEXT:    store i32 [[ADD154]], ptr [[INVARIANT_GEP_16]], align 4
; CHECK-NEXT:    ret i32 0
;
entry:
  %add65 = add i32 %0, 1
  %add47.1.1 = or i32 %0, 1
  %add65.1 = add i32 %add47.1.1, 2
  %sub146 = sub i32 %add65, %add65.1
  %1 = load ptr, ptr %img, align 8
  %arrayidx150 = getelementptr i8, ptr %1, i64 13120
  store i32 %sub146, ptr %arrayidx150, align 8
  %mul152 = shl i32 %add65, 1
  %add154 = or i32 %mul152, %add65.1
  %invariant.gep.16 = getelementptr i8, ptr %1, i64 13116
  store i32 %add154, ptr %invariant.gep.16, align 4
  ret i32 0
}
