; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu -mcpu=icelake-server < %s | FileCheck %s

define void @test(ptr %src, i8 %0, i32 %conv2) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[SRC:%.*]], i8 [[TMP0:%.*]], i32 [[CONV2:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CONV65:%.*]] = zext i8 [[TMP0]] to i32
; CHECK-NEXT:    [[ADD36:%.*]] = add i32 [[CONV65]], 1
; CHECK-NEXT:    [[ADD37:%.*]] = or i32 [[ADD36]], [[CONV2]]
; CHECK-NEXT:    [[CONV4:%.*]] = zext i8 [[TMP0]] to i32
; CHECK-NEXT:    [[ADD38:%.*]] = or i32 [[ADD37]], [[CONV4]]
; CHECK-NEXT:    [[SHR39:%.*]] = lshr i32 [[ADD38]], 1
; CHECK-NEXT:    [[CONV40:%.*]] = trunc i32 [[SHR39]] to i8
; CHECK-NEXT:    [[ARRAYIDX41:%.*]] = getelementptr i8, ptr [[SRC]], i64 1
; CHECK-NEXT:    store i8 [[CONV40]], ptr [[ARRAYIDX41]], align 1
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[CONV4]], 1
; CHECK-NEXT:    [[ADD45:%.*]] = or i32 [[ADD]], [[CONV2]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[SRC]], align 1
; CHECK-NEXT:    [[CONV8:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    [[ADD46:%.*]] = or i32 [[ADD45]], [[CONV8]]
; CHECK-NEXT:    [[SHR47:%.*]] = lshr i32 [[ADD46]], 1
; CHECK-NEXT:    [[CONV48:%.*]] = trunc i32 [[SHR47]] to i8
; CHECK-NEXT:    [[ARRAYIDX49:%.*]] = getelementptr i8, ptr [[SRC]], i64 2
; CHECK-NEXT:    store i8 [[CONV48]], ptr [[ARRAYIDX49]], align 1
; CHECK-NEXT:    [[MUL52:%.*]] = shl i32 [[CONV8]], 1
; CHECK-NEXT:    [[ADD54:%.*]] = or i32 [[MUL52]], 1
; CHECK-NEXT:    [[CONV10:%.*]] = zext i8 [[TMP0]] to i32
; CHECK-NEXT:    [[ADD55:%.*]] = add i32 [[ADD54]], [[CONV10]]
; CHECK-NEXT:    [[SHR56:%.*]] = lshr i32 [[ADD55]], 1
; CHECK-NEXT:    [[CONV57:%.*]] = trunc i32 [[SHR56]] to i8
; CHECK-NEXT:    [[ARRAYIDX58:%.*]] = getelementptr i8, ptr [[SRC]], i64 3
; CHECK-NEXT:    store i8 [[CONV57]], ptr [[ARRAYIDX58]], align 1
; CHECK-NEXT:    [[ADD63:%.*]] = add i32 [[CONV8]], 1
; CHECK-NEXT:    [[ADD64:%.*]] = or i32 [[ADD63]], [[CONV10]]
; CHECK-NEXT:    [[SHR66:%.*]] = lshr i32 [[ADD64]], 1
; CHECK-NEXT:    [[CONV67:%.*]] = trunc i32 [[SHR66]] to i8
; CHECK-NEXT:    [[ARRAYIDX68:%.*]] = getelementptr i8, ptr [[SRC]], i64 4
; CHECK-NEXT:    store i8 [[CONV67]], ptr [[ARRAYIDX68]], align 1
; CHECK-NEXT:    ret void
;
entry:
  %conv65 = zext i8 %0 to i32
  %add36 = add i32 %conv65, 1
  %add37 = or i32 %add36, %conv2
  %conv4 = zext i8 %0 to i32
  %add38 = or i32 %add37, %conv4
  %shr39 = lshr i32 %add38, 1
  %conv40 = trunc i32 %shr39 to i8
  %arrayidx41 = getelementptr i8, ptr %src, i64 1
  store i8 %conv40, ptr %arrayidx41, align 1
  %add = add i32 %conv4, 1
  %add45 = or i32 %add, %conv2
  %1 = load i8, ptr %src, align 1
  %conv8 = zext i8 %1 to i32
  %add46 = or i32 %add45, %conv8
  %shr47 = lshr i32 %add46, 1
  %conv48 = trunc i32 %shr47 to i8
  %arrayidx49 = getelementptr i8, ptr %src, i64 2
  store i8 %conv48, ptr %arrayidx49, align 1
  %mul52 = shl i32 %conv8, 1
  %add54 = or i32 %mul52, 1
  %conv10 = zext i8 %0 to i32
  %add55 = add i32 %add54, %conv10
  %shr56 = lshr i32 %add55, 1
  %conv57 = trunc i32 %shr56 to i8
  %arrayidx58 = getelementptr i8, ptr %src, i64 3
  store i8 %conv57, ptr %arrayidx58, align 1
  %add63 = add i32 %conv8, 1
  %add64 = or i32 %add63, %conv10
  %shr66 = lshr i32 %add64, 1
  %conv67 = trunc i32 %shr66 to i8
  %arrayidx68 = getelementptr i8, ptr %src, i64 4
  store i8 %conv67, ptr %arrayidx68, align 1
  ret void
}
