; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux < %s | FileCheck %s

define void @test(ptr %dest, ptr %p) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[DEST:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[INC0:%.*]] = getelementptr inbounds i16, ptr [[P]], i64 1
; CHECK-NEXT:    [[INC1:%.*]] = getelementptr inbounds i16, ptr [[P]], i64 2
; CHECK-NEXT:    [[E0:%.*]] = load i16, ptr [[P]], align 4
; CHECK-NEXT:    [[E1:%.*]] = load i16, ptr [[INC0]], align 2
; CHECK-NEXT:    [[A0:%.*]] = sub i16 [[E0]], 1
; CHECK-NEXT:    [[A1:%.*]] = shl i16 [[E1]], 1
; CHECK-NEXT:    [[INC4:%.*]] = getelementptr inbounds i16, ptr [[DEST]], i64 1
; CHECK-NEXT:    [[INC5:%.*]] = getelementptr inbounds i16, ptr [[DEST]], i64 2
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x i16>, ptr [[INC1]], align 2
; CHECK-NEXT:    [[TMP1:%.*]] = add <2 x i16> [[TMP0]], splat (i16 1)
; CHECK-NEXT:    store i16 [[A0]], ptr [[DEST]], align 4
; CHECK-NEXT:    store i16 [[A1]], ptr [[INC4]], align 2
; CHECK-NEXT:    store <2 x i16> [[TMP1]], ptr [[INC5]], align 2
; CHECK-NEXT:    ret void
;
entry:
  %inc0 = getelementptr inbounds i16, ptr %p, i64 1
  %inc1 = getelementptr inbounds i16, ptr %p, i64 2
  %inc2 = getelementptr inbounds i16, ptr %p, i64 3
  %e0 = load i16, ptr %p, align 4
  %e1 = load i16, ptr %inc0, align 2
  %e2 = load i16, ptr %inc1, align 2
  %e3 = load i16, ptr %inc2, align 2

  %a0 = sub i16 %e0, 1
  %a1 = shl i16 %e1, 1
  %a2 = add i16 %e2, 1
  %a3 = add i16 %e3, 1

  %inc4 = getelementptr inbounds i16, ptr %dest, i64 1
  %inc5 = getelementptr inbounds i16, ptr %dest, i64 2
  %inc6 = getelementptr inbounds i16, ptr %dest, i64 3

  store i16 %a0, ptr %dest, align 4
  store i16 %a1, ptr %inc4, align 2
  store i16 %a2, ptr %inc5, align 2
  store i16 %a3, ptr %inc6, align 2
  ret void
}
