; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt --passes=slp-vectorizer -S -slp-revec -mcpu=tigerlake -mtriple=x86_64-pc-windows-gnu < %s | FileCheck %s

define double @test(<8 x i32> %broadcast.splatinsert9, <8 x i16> %0) {
; CHECK-LABEL: define double @test(
; CHECK-SAME: <8 x i32> [[BROADCAST_SPLATINSERT9:%.*]], <8 x i16> [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[VECTOR_PH:.*:]]
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i32> [[BROADCAST_SPLATINSERT9]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP2:%.*]] = mul <16 x i32> [[TMP1]], [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i16> [[TMP0]], <8 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP4:%.*]] = sext <16 x i16> [[TMP3]] to <16 x i32>
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <16 x i32> [[TMP4]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[TMP6:%.*]] = mul <16 x i32> [[TMP1]], [[TMP1]]
; CHECK-NEXT:    [[TMP7:%.*]] = or <16 x i32> [[TMP2]], splat (i32 1)
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x i32> [[TMP5]], <8 x i32> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP9:%.*]] = mul <16 x i32> [[TMP8]], [[TMP4]]
; CHECK-NEXT:    [[TMP10:%.*]] = or <16 x i32> [[TMP7]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = or <16 x i32> [[TMP10]], [[TMP6]]
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <16 x i32> [[TMP11]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[TMP12]])
; CHECK-NEXT:    [[TMP14:%.*]] = sitofp i32 [[TMP13]] to double
; CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <16 x i32> [[TMP11]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP16:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[TMP15]])
; CHECK-NEXT:    [[TMP17:%.*]] = sitofp i32 [[TMP16]] to double
; CHECK-NEXT:    [[TMP18:%.*]] = fsub double [[TMP14]], [[TMP17]]
; CHECK-NEXT:    ret double [[TMP18]]
;
vector.ph:
  %1 = mul <8 x i32> %broadcast.splatinsert9, %broadcast.splatinsert9
  %2 = or <8 x i32> %1, splat (i32 1)
  %3 = sext <8 x i16> %0 to <8 x i32>
  %4 = sext <8 x i16> %0 to <8 x i32>
  %5 = mul <8 x i32> %3, %4
  %6 = or <8 x i32> %2, %5
  %7 = mul <8 x i32> %broadcast.splatinsert9, %broadcast.splatinsert9
  %8 = or <8 x i32> %6, %7
  %9 = mul <8 x i32> %broadcast.splatinsert9, %broadcast.splatinsert9
  %10 = or <8 x i32> %9, splat (i32 1)
  %11 = mul <8 x i32> %3, %3
  %12 = or <8 x i32> %10, %11
  %13 = mul <8 x i32> %broadcast.splatinsert9, %broadcast.splatinsert9
  %14 = or <8 x i32> %12, %13
  %15 = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> %14)
  %16 = sitofp i32 %15 to double
  %17 = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> %8)
  %18 = sitofp i32 %17 to double
  %19 = fsub double %16, %18
  ret double %19
}

declare i32 @llvm.vector.reduce.add.v8i32(<8 x i32>)

