; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define i32 @test(i32 %add.i64326, i32 %call119) {
; CHECK-LABEL: define i32 @test(
; CHECK-SAME: i32 [[ADD_I64326:%.*]], i32 [[CALL119:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CALL:%.*]] = tail call i32 (...) null()
; CHECK-NEXT:    [[CALL35:%.*]] = tail call i32 (...) null()
; CHECK-NEXT:    [[CALL91:%.*]] = tail call i32 (...) null()
; CHECK-NEXT:    [[ADD_R131:%.*]] = add i32 [[CALL119]], [[ADD_I64326]]
; CHECK-NEXT:    [[CALL1193:%.*]] = tail call i32 (...) null()
; CHECK-NEXT:    [[CALL211:%.*]] = tail call i32 (...) null()
; CHECK-NEXT:    [[CALL239:%.*]] = tail call i32 (...) null()
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <6 x i32> poison, i32 [[CALL]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <6 x i32> [[TMP0]], i32 [[CALL35]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <6 x i32> [[TMP1]], i32 [[CALL91]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <6 x i32> [[TMP2]], i32 [[CALL1193]], i32 3
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <6 x i32> [[TMP3]], i32 [[CALL211]], i32 4
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <6 x i32> [[TMP4]], i32 [[CALL239]], i32 5
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <6 x i32> [[TMP5]], <6 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <8 x i32> [[TMP6]], <8 x i32> <i32 0, i32 0, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 8, i32 9>
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x i32> <i32 poison, i32 0>, i32 [[ADD_I64326]], i32 0
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <2 x i32> <i32 poison, i32 0>, i32 [[CALL35]], i32 0
; CHECK-NEXT:    [[TMP10:%.*]] = add <2 x i32> [[TMP8]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <8 x i32> [[TMP7]], <8 x i32> poison, <16 x i32> <i32 0, i32 poison, i32 1, i32 poison, i32 poison, i32 2, i32 poison, i32 3, i32 poison, i32 4, i32 poison, i32 5, i32 6, i32 7, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP12:%.*]] = insertelement <16 x i32> [[TMP11]], i32 [[ADD_R131]], i32 14
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <16 x i32> [[TMP12]], <16 x i32> poison, <16 x i32> <i32 0, i32 0, i32 2, i32 poison, i32 poison, i32 5, i32 5, i32 7, i32 7, i32 9, i32 9, i32 11, i32 12, i32 13, i32 14, i32 14>
; CHECK-NEXT:    [[TMP14:%.*]] = and <16 x i32> [[TMP13]], <i32 0, i32 0, i32 0, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
; CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <2 x i32> [[TMP10]], <2 x i32> poison, <8 x i32> <i32 poison, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <2 x i32> [[TMP10]], <2 x i32> poison, <8 x i32> <i32 0, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <8 x i32> <i32 0, i32 1, i32 0, i32 0, i32 poison, i32 poison, i32 poison, i32 0>, <8 x i32> [[TMP16]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 9, i32 7>
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <8 x i32> [[TMP17]], <8 x i32> [[TMP16]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 6, i32 7>
; CHECK-NEXT:    [[TMP23:%.*]] = icmp ult <8 x i32> [[TMP18]], zeroinitializer
; CHECK-NEXT:    [[TMP24:%.*]] = icmp eq <16 x i32> [[TMP14]], <i32 0, i32 0, i32 0, i32 poison, i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
; CHECK-NEXT:    [[TMP25:%.*]] = shufflevector <16 x i1> [[TMP24]], <16 x i1> poison, <24 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <8 x i1> [[TMP23]], <8 x i1> poison, <24 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP27:%.*]] = shufflevector <24 x i1> [[TMP25]], <24 x i1> [[TMP26]], <24 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
; CHECK-NEXT:    [[TMP28:%.*]] = select <24 x i1> [[TMP27]], <24 x i32> zeroinitializer, <24 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP29:%.*]] = call i32 @llvm.vector.reduce.add.v24i32(<24 x i32> [[TMP28]])
; CHECK-NEXT:    ret i32 [[TMP29]]
;
entry:
  %add.r = add i32 0, 0
  %sext.mask = and i32 %add.r, 0
  %call = tail call i32 (...) null()
  %sext.mask323 = and i32 %call, 0
  %call35 = tail call i32 (...) null()
  %sext.mask324 = and i32 %call35, 0
  %add.r63 = add i32 0, 0
  %sext.mask325 = and i32 %add.r63, 0
  %coerce36.sroa.2.0.extract.shift327 = add i32 %add.i64326, %call35
  %call91 = tail call i32 (...) null()
  %sext329.mask = and i32 %call91, 0
  %0 = and i32 %call91, 0
  %add.r131 = add i32 %call119, %add.i64326
  %sext332.mask = and i32 %add.r131, 0
  %coerce52.sroa.2.0.extract.shift335 = add i32 0, 0
  %call1193 = tail call i32 (...) null()
  %sext336.mask = and i32 %call1193, 0
  %add.i132334 = and i32 %call1193, 0
  %call211 = tail call i32 (...) null()
  %sext339.mask = and i32 %call211, 0
  %1 = and i32 %call211, 0
  %call239 = tail call i32 (...) null()
  %sext342.mask = and i32 %call239, 0
  %add.i320 = and i32 %call, 0
  %tobool31.not = icmp eq i32 %add.i320, 0
  %add33 = select i1 %tobool31.not, i32 0, i32 0
  %tobool25.not = icmp eq i32 %sext.mask323, 0
  %add27 = select i1 %tobool25.not, i32 0, i32 0
  %add12 = add i32 %add33, %add27
  %tobool.not = icmp ult i32 0, 0
  %add11 = select i1 %tobool.not, i32 0, i32 0
  %add28 = add i32 %add12, %add11
  %tobool47.not = icmp ult i32 1, 0
  %add49 = select i1 %tobool47.not, i32 0, i32 0
  %add34 = add i32 %add28, %add49
  %cmp = icmp eq i32 %sext.mask, 0
  %add = select i1 %cmp, i32 0, i32 0
  %add44 = add i32 %add34, %add
  %tobool41.not = icmp eq i32 %sext.mask324, 0
  %add43 = select i1 %tobool41.not, i32 0, i32 0
  %add50 = add i32 %add44, %add43
  %tobool87.not = icmp ult i32 0, 0
  %add89 = select i1 %tobool87.not, i32 0, i32 0
  %add72 = add i32 %add50, %add89
  %add159 = select i1 %tobool87.not, i32 0, i32 0
  %add78 = add i32 %add72, %add159
  %add83 = select i1 poison, i32 0, i32 0
  %add84 = add i32 %add78, %add83
  %add152 = select i1 poison, i32 0, i32 0
  %add90 = add i32 %add84, %add152
  %tobool69.not = icmp eq i32 %sext.mask325, 0
  %add71 = select i1 %tobool69.not, i32 0, i32 0
  %add112 = add i32 %add90, %add71
  %tobool75.not = icmp ult i32 %coerce36.sroa.2.0.extract.shift327, 0
  %add77 = select i1 %tobool75.not, i32 0, i32 0
  %add118 = add i32 %add112, %add77
  %tobool109.not = icmp eq i32 %sext329.mask, 0
  %add111 = select i1 %tobool109.not, i32 0, i32 0
  %add140 = add i32 %add118, %add111
  %tobool115.not = icmp eq i32 %0, 0
  %add117 = select i1 %tobool115.not, i32 0, i32 0
  %add146 = add i32 %add140, %add117
  %tobool175.not = icmp eq i32 %sext336.mask, 0
  %add177 = select i1 %tobool175.not, i32 0, i32 0
  %add153 = add i32 %add146, %add177
  %tobool181.not = icmp eq i32 %add.i132334, 0
  %add183 = select i1 %tobool181.not, i32 0, i32 0
  %add160 = add i32 %add153, %add183
  %tobool137.not = icmp eq i32 %sext332.mask, 0
  %add139 = select i1 %tobool137.not, i32 0, i32 0
  %add178 = add i32 %add160, %add139
  %tobool143.not = icmp ult i32 %coerce52.sroa.2.0.extract.shift335, 0
  %add145 = select i1 %tobool143.not, i32 0, i32 0
  %add184 = add i32 %add178, %add145
  %add202 = select i1 %tobool137.not, i32 0, i32 0
  %add203 = add i32 %add184, %add202
  %add209 = select i1 %tobool143.not, i32 0, i32 0
  %add210 = add i32 %add203, %add209
  %tobool229.not = icmp eq i32 %sext339.mask, 0
  %add231 = select i1 %tobool229.not, i32 0, i32 0
  %add232 = add i32 %add210, %add231
  %tobool235.not = icmp eq i32 %1, 0
  %add237 = select i1 %tobool235.not, i32 0, i32 0
  %add238 = add i32 %add232, %add237
  %tobool251.not = icmp ult i32 0, 0
  %add253 = select i1 %tobool251.not, i32 0, i32 0
  %add248 = add i32 %add238, %add253
  %tobool245.not = icmp eq i32 %sext342.mask, 0
  %add247 = select i1 %tobool245.not, i32 0, i32 0
  %add254 = add i32 %add248, %add247
  ret i32 %add254
}
