; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64 < %s | FileCheck %s

define i1 @test() {
; CHECK-LABEL: define i1 @test() {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp slt i32 0, 0
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <2 x i1> <i1 poison, i1 false>, i1 [[TMP1]], i32 0
; CHECK-NEXT:    [[TMP3:%.*]] = select <2 x i1> [[TMP2]], <2 x i32> <i32 1, i32 0>, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i32> [[TMP3]], <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 1, i32 1>
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <2 x i32> [[TMP3]], <2 x i32> poison, <4 x i32> <i32 1, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <4 x i32> [[TMP5]], i32 0, i32 1
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <4 x i32> [[TMP6]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 0, i32 1>
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i32> [[TMP7]], <4 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i32> [[TMP8]], <8 x i32> <i32 0, i32 0, i32 0, i32 0, i32 undef, i32 undef, i32 undef, i32 undef>, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i32> [[TMP4]], <4 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <8 x i32> <i32 0, i32 0, i32 0, i32 0, i32 undef, i32 undef, i32 undef, i32 undef>, <8 x i32> [[TMP10]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
; CHECK-NEXT:    [[TMP12:%.*]] = mul <8 x i32> [[TMP9]], zeroinitializer
; CHECK-NEXT:    [[TMP13:%.*]] = urem <8 x i32> [[TMP12]], splat (i32 46337)
; CHECK-NEXT:    [[TMP14:%.*]] = mul <8 x i32> [[TMP13]], zeroinitializer
; CHECK-NEXT:    [[TMP15:%.*]] = urem <8 x i32> [[TMP14]], splat (i32 46337)
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <8 x i32> [[TMP15]], <8 x i32> poison, <8 x i32> <i32 0, i32 1, i32 4, i32 5, i32 6, i32 7, i32 2, i32 3>
; CHECK-NEXT:    [[TMP17:%.*]] = add <8 x i32> poison, [[TMP16]]
; CHECK-NEXT:    [[TMP18:%.*]] = or <8 x i32> poison, [[TMP16]]
; CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <8 x i32> [[TMP17]], <8 x i32> [[TMP18]], <8 x i32> <i32 0, i32 9, i32 10, i32 3, i32 12, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP20:%.*]] = freeze <8 x i32> [[TMP19]]
; CHECK-NEXT:    [[TMP21:%.*]] = select <8 x i1> zeroinitializer, <8 x i32> [[TMP20]], <8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP22:%.*]] = mul <8 x i32> [[TMP11]], zeroinitializer
; CHECK-NEXT:    [[TMP23:%.*]] = urem <8 x i32> [[TMP22]], splat (i32 46337)
; CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <8 x i32> [[TMP23]], <8 x i32> poison, <8 x i32> <i32 0, i32 4, i32 1, i32 2, i32 5, i32 3, i32 6, i32 7>
; CHECK-NEXT:    [[TMP25:%.*]] = add <8 x i32> [[TMP21]], [[TMP24]]
; CHECK-NEXT:    [[TMP26:%.*]] = or <8 x i32> [[TMP21]], [[TMP24]]
; CHECK-NEXT:    [[TMP27:%.*]] = shufflevector <8 x i32> [[TMP25]], <8 x i32> [[TMP26]], <8 x i32> <i32 0, i32 9, i32 2, i32 11, i32 4, i32 5, i32 14, i32 7>
; CHECK-NEXT:    [[TMP28:%.*]] = urem <8 x i32> [[TMP27]], splat (i32 46337)
; CHECK-NEXT:    [[TMP29:%.*]] = icmp ult <8 x i32> [[TMP28]], zeroinitializer
; CHECK-NEXT:    [[TMP30:%.*]] = extractelement <8 x i1> [[TMP29]], i32 0
; CHECK-NEXT:    ret i1 [[TMP30]]
;
  %1 = select i1 false, i32 0, i32 0
  %2 = select i1 false, i32 0, i32 0
  %3 = mul i32 %2, 0
  %4 = urem i32 %3, 46337
  %5 = mul i32 %1, 0
  %6 = urem i32 %5, 0
  %7 = mul i32 %6, 0
  %8 = urem i32 %7, 0
  %9 = mul i32 %8, 0
  %10 = urem i32 %9, 1
  %11 = mul i32 %4, 0
  %12 = urem i32 %11, 46337
  %13 = add i32 %10, %12
  %14 = freeze i32 %13
  %15 = select i1 false, i32 %14, i32 0
  %16 = mul i32 %1, 0
  %17 = urem i32 %16, 46337
  %18 = add i32 %15, %17
  %19 = urem i32 %18, 46337
  %20 = icmp ult i32 %19, 0
  %21 = mul i32 %1, 0
  %22 = urem i32 %21, 46337
  %23 = mul i32 %2, 0
  %24 = urem i32 %23, 0
  %25 = mul i32 %24, 0
  %26 = urem i32 %25, 0
  %27 = mul i32 %26, 0
  %28 = urem i32 %27, 0
  %29 = mul i32 %22, 0
  %30 = urem i32 %29, 46337
  %31 = add i32 %28, %30
  %32 = freeze i32 %31
  %33 = select i1 false, i32 %32, i32 0
  %34 = mul i32 %1, 0
  %35 = urem i32 %34, 46337
  %36 = or i32 %33, %35
  %37 = urem i32 %36, 46337
  %38 = icmp ult i32 %37, 0
  %39 = mul i32 %1, 0
  %40 = urem i32 %39, 0
  %41 = mul i32 %40, 0
  %42 = urem i32 %41, 0
  %43 = mul i32 %1, 0
  %44 = urem i32 %43, 0
  %45 = mul i32 0, %44
  %46 = urem i32 %45, 0
  %47 = mul i32 %1, 0
  %48 = mul i32 %1, 0
  %49 = urem i32 %48, 0
  %50 = mul i32 %49, 0
  %51 = urem i32 %50, 0
  %52 = mul i32 %2, 0
  %53 = urem i32 %52, 0
  %54 = mul i32 %53, 0
  %55 = urem i32 %54, 0
  %56 = icmp slt i32 0, 0
  %57 = mul i32 %1, 0
  %58 = mul i32 %1, 0
  %59 = urem i32 %58, 0
  %60 = mul i32 %59, 0
  %61 = urem i32 %57, 46337
  %62 = mul i32 %61, 0
  %63 = select i1 %56, i32 1, i32 0
  %64 = mul i32 %63, 0
  %65 = extractelement <4 x i32> zeroinitializer, i32 0
  %66 = mul i32 %65, 0
  %67 = urem i32 %66, 46337
  %68 = mul i32 %42, 0
  %69 = urem i32 %68, 1
  %70 = mul i32 %67, 0
  %71 = urem i32 %70, 46337
  %72 = add i32 %69, %71
  %73 = freeze i32 %72
  %74 = select i1 false, i32 %73, i32 0
  %75 = mul i32 %65, 0
  %76 = urem i32 %75, 46337
  %77 = add i32 %74, %76
  %78 = urem i32 %77, 46337
  %79 = icmp ult i32 %78, 0
  %80 = extractelement <4 x i32> zeroinitializer, i32 0
  %81 = mul i32 %80, 0
  %82 = urem i32 %81, 46337
  %83 = mul i32 %46, 0
  %84 = urem i32 %83, 0
  %85 = mul i32 %82, 0
  %86 = urem i32 %85, 46337
  %87 = or i32 %84, %86
  %88 = freeze i32 %87
  %89 = select i1 false, i32 %88, i32 0
  %90 = urem i32 %47, 46337
  %91 = add i32 %89, %90
  %92 = urem i32 %91, 46337
  %93 = icmp ult i32 %92, 0
  %94 = mul i32 %65, 0
  %95 = urem i32 %94, 46337
  %96 = mul i32 %51, 0
  %97 = urem i32 %96, 1
  %98 = mul i32 %95, 0
  %99 = urem i32 %98, 46337
  %100 = add i32 %97, %99
  %101 = freeze i32 %100
  %102 = select i1 false, i32 %101, i32 0
  %103 = mul i32 %65, 0
  %104 = urem i32 %103, 46337
  %105 = or i32 %102, %104
  %106 = urem i32 %105, 46337
  %107 = icmp ult i32 %106, 0
  %108 = mul i32 %80, 0
  %109 = urem i32 %108, 46337
  %110 = mul i32 %55, 0
  %111 = urem i32 %110, 0
  %112 = mul i32 %109, 0
  %113 = urem i32 %112, 46337
  %114 = or i32 %111, %113
  %115 = freeze i32 %114
  %116 = select i1 false, i32 %115, i32 0
  %117 = mul i32 %80, 0
  %118 = urem i32 %117, 46337
  %119 = add i32 %116, %118
  %120 = urem i32 %119, 46337
  %121 = icmp ult i32 %120, 0
  %122 = urem i32 %60, 0
  %123 = mul i32 %122, 0
  %124 = urem i32 %123, 1
  %125 = urem i32 %62, 46337
  %126 = or i32 %124, %125
  %127 = freeze i32 %126
  %128 = select i1 false, i32 %127, i32 0
  %129 = urem i32 %64, 46337
  %130 = or i32 %128, %129
  %131 = urem i32 %130, 46337
  %132 = icmp ult i32 %131, 0
  %133 = mul i32 %1, 0
  %134 = urem i32 %133, 46337
  %135 = mul i32 %1, 0
  %136 = urem i32 %135, 0
  %137 = mul i32 %136, 0
  %138 = urem i32 %137, 0
  %139 = mul i32 %138, 0
  %140 = urem i32 %139, 0
  %141 = mul i32 %134, 0
  %142 = urem i32 %141, 46337
  %143 = add i32 %140, %142
  %144 = extractelement <4 x i32> zeroinitializer, i32 0
  %145 = freeze i32 %143
  %146 = select i1 false, i32 %145, i32 0
  %147 = mul i32 %144, 0
  %148 = urem i32 %147, 46337
  %149 = add i32 %146, %148
  %150 = urem i32 %149, 46337
  %151 = icmp ult i32 %150, 0
  ret i1 %151
}
