; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-grtev4-linux-gnu < %s | FileCheck %s

define i32 @test(i128 %add134.i8203) {
; CHECK-LABEL: define i32 @test(
; CHECK-SAME: i128 [[ADD134_I8203:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[REASS_SUB6909:%.*]] = sub i64 0, 0
; CHECK-NEXT:    [[SUB9_I3318:%.*]] = or i64 [[REASS_SUB6909]], 0
; CHECK-NEXT:    br label %[[CONT90_I:.*]]
; CHECK:       [[CONT90_I]]:
; CHECK-NEXT:    [[T_I_SROA_488_1:%.*]] = phi i64 [ [[SUB9_I3318]], %[[ENTRY]] ]
; CHECK-NEXT:    [[T_I_SROA_457_1:%.*]] = phi i64 [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[T_I_SROA_426_1:%.*]] = phi i64 [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[CONV61_I8293:%.*]] = zext i64 [[T_I_SROA_426_1]] to i128
; CHECK-NEXT:    [[CONV66_I8295:%.*]] = zext i64 [[T_I_SROA_457_1]] to i128
; CHECK-NEXT:    [[MUL127_I8312:%.*]] = mul i128 0, [[CONV66_I8295]]
; CHECK-NEXT:    [[MUL132_I8313:%.*]] = mul i128 0, [[CONV61_I8293]]
; CHECK-NEXT:    [[ADD135_I8317:%.*]] = or i128 0, [[MUL132_I8313]]
; CHECK-NEXT:    [[TMP0:%.*]] = trunc i128 [[ADD135_I8317]] to i64
; CHECK-NEXT:    [[CONV137_I8321:%.*]] = and i64 [[TMP0]], 0
; CHECK-NEXT:    [[ADD153_I8337:%.*]] = or i128 0, [[MUL127_I8312]]
; CHECK-NEXT:    [[ADD155_I8339:%.*]] = or i128 [[ADD153_I8337]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i128 [[ADD155_I8339]] to i64
; CHECK-NEXT:    [[CONV76_I8298:%.*]] = zext i64 [[T_I_SROA_488_1]] to i128
; CHECK-NEXT:    [[MUL57_I8179:%.*]] = mul i128 0, [[CONV66_I8295]]
; CHECK-NEXT:    [[ADD135_I8204:%.*]] = or i128 [[ADD134_I8203]], [[MUL57_I8179]]
; CHECK-NEXT:    [[TMP2:%.*]] = trunc i128 [[ADD135_I8204]] to i64
; CHECK-NEXT:    [[CONV137_I8208:%.*]] = and i64 [[TMP2]], 0
; CHECK-NEXT:    [[ADD179_I8250:%.*]] = or i64 0, [[CONV137_I8208]]
; CHECK-NEXT:    [[MUL45_I8175:%.*]] = mul i128 0, [[CONV76_I8298]]
; CHECK-NEXT:    [[ADD153_I8224:%.*]] = or i128 0, [[MUL45_I8175]]
; CHECK-NEXT:    [[ADD155_I8226:%.*]] = or i128 [[ADD153_I8224]], 0
; CHECK-NEXT:    [[SHR168_I8352:%.*]] = lshr i128 0, 0
; CHECK-NEXT:    [[TMP3:%.*]] = trunc i128 [[SHR168_I8352]] to i64
; CHECK-NEXT:    [[CONV177_I8361:%.*]] = and i64 [[TMP3]], 0
; CHECK-NEXT:    [[ARRAYIDX192_I8375:%.*]] = getelementptr i8, ptr poison, i64 72
; CHECK-NEXT:    store i64 [[CONV177_I8361]], ptr [[ARRAYIDX192_I8375]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i128 0 to i64
; CHECK-NEXT:    [[CONV171_I8355:%.*]] = and i64 [[TMP4]], 0
; CHECK-NEXT:    [[ARRAYIDX191_I8374:%.*]] = getelementptr i8, ptr poison, i64 64
; CHECK-NEXT:    store i64 [[CONV171_I8355]], ptr [[ARRAYIDX191_I8374]], align 8
; CHECK-NEXT:    [[SHR180_I8364:%.*]] = lshr i64 [[CONV137_I8321]], 1
; CHECK-NEXT:    [[CONV159_I8343:%.*]] = and i64 [[TMP1]], 0
; CHECK-NEXT:    [[ADD182_I8366:%.*]] = or i64 [[SHR180_I8364]], [[CONV159_I8343]]
; CHECK-NEXT:    [[SHR183_I8367:%.*]] = lshr i64 [[ADD182_I8366]], 0
; CHECK-NEXT:    [[CONV165_I8349:%.*]] = and i64 0, 0
; CHECK-NEXT:    [[ADD187_I8371:%.*]] = or i64 [[SHR183_I8367]], [[CONV165_I8349]]
; CHECK-NEXT:    [[ARRAYIDX190_I8373:%.*]] = getelementptr i8, ptr poison, i64 56
; CHECK-NEXT:    store i64 [[ADD187_I8371]], ptr [[ARRAYIDX190_I8373]], align 8
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i128 0 to i64
; CHECK-NEXT:    [[CONV177_I8248:%.*]] = and i64 [[TMP5]], 0
; CHECK-NEXT:    [[ARRAYIDX192_I8262:%.*]] = getelementptr i8, ptr poison, i64 112
; CHECK-NEXT:    store i64 [[CONV177_I8248]], ptr [[ARRAYIDX192_I8262]], align 8
; CHECK-NEXT:    [[TMP6:%.*]] = trunc i128 [[ADD134_I8203]] to i64
; CHECK-NEXT:    [[CONV171_I8242:%.*]] = and i64 [[TMP6]], 0
; CHECK-NEXT:    [[ARRAYIDX191_I8261:%.*]] = getelementptr i8, ptr poison, i64 104
; CHECK-NEXT:    store i64 [[CONV171_I8242]], ptr [[ARRAYIDX191_I8261]], align 8
; CHECK-NEXT:    [[SHR180_I8251:%.*]] = lshr i64 [[ADD179_I8250]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = trunc i128 [[ADD155_I8226]] to i64
; CHECK-NEXT:    [[ADD182_I8253:%.*]] = or i64 [[SHR180_I8251]], [[TMP7]]
; CHECK-NEXT:    [[SHR183_I8254:%.*]] = lshr i64 [[ADD182_I8253]], 0
; CHECK-NEXT:    [[ADD187_I8258:%.*]] = or i64 [[SHR183_I8254]], 0
; CHECK-NEXT:    [[ARRAYIDX190_I8260:%.*]] = getelementptr i8, ptr poison, i64 96
; CHECK-NEXT:    store i64 [[ADD187_I8258]], ptr [[ARRAYIDX190_I8260]], align 8
; CHECK-NEXT:    [[AND185_I8256:%.*]] = and i64 [[ADD182_I8253]], 0
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr poison, i64 88
; CHECK-NEXT:    store i64 [[AND185_I8256]], ptr [[TMP8]], align 8
; CHECK-NEXT:    [[AND181_I8252:%.*]] = and i64 [[ADD179_I8250]], 0
; CHECK-NEXT:    [[Z_I519:%.*]] = getelementptr i8, ptr poison, i64 80
; CHECK-NEXT:    store i64 [[AND181_I8252]], ptr [[Z_I519]], align 8
; CHECK-NEXT:    ret i32 0
;
entry:
  %sub5.i3314 = add i64 0, 0
  %reass.sub6909 = sub i64 0, 0
  %sub9.i3318 = or i64 %reass.sub6909, 0
  br label %cont90.i

cont90.i:
  %t.i.sroa.488.1 = phi i64 [ %sub9.i3318, %entry ]
  %t.i.sroa.457.1 = phi i64 [ %sub5.i3314, %entry ]
  %t.i.sroa.426.1 = phi i64 [ 0, %entry ]
  %conv61.i8293 = zext i64 %t.i.sroa.426.1 to i128
  %conv66.i8295 = zext i64 %t.i.sroa.457.1 to i128
  %mul127.i8312 = mul i128 0, %conv66.i8295
  %mul132.i8313 = mul i128 0, %conv61.i8293
  %add135.i8317 = or i128 0, %mul132.i8313
  %0 = trunc i128 %add135.i8317 to i64
  %conv137.i8321 = and i64 %0, 0
  %add153.i8337 = or i128 0, %mul127.i8312
  %add155.i8339 = or i128 %add153.i8337, 0
  %1 = trunc i128 %add155.i8339 to i64
  %conv76.i8298 = zext i64 %t.i.sroa.488.1 to i128
  %mul57.i8179 = mul i128 0, %conv66.i8295
  %add135.i8204 = or i128 %add134.i8203, %mul57.i8179
  %2 = trunc i128 %add135.i8204 to i64
  %conv137.i8208 = and i64 %2, 0
  %add179.i8250 = or i64 0, %conv137.i8208
  %mul45.i8175 = mul i128 0, %conv76.i8298
  %add153.i8224 = or i128 0, %mul45.i8175
  %add155.i8226 = or i128 %add153.i8224, 0
  %shr168.i8352 = lshr i128 0, 0
  %3 = trunc i128 %shr168.i8352 to i64
  %conv177.i8361 = and i64 %3, 0
  %arrayidx192.i8375 = getelementptr i8, ptr poison, i64 72
  store i64 %conv177.i8361, ptr %arrayidx192.i8375, align 8
  %4 = trunc i128 0 to i64
  %conv171.i8355 = and i64 %4, 0
  %arrayidx191.i8374 = getelementptr i8, ptr poison, i64 64
  store i64 %conv171.i8355, ptr %arrayidx191.i8374, align 8
  %shr180.i8364 = lshr i64 %conv137.i8321, 1
  %conv159.i8343 = and i64 %1, 0
  %add182.i8366 = or i64 %shr180.i8364, %conv159.i8343
  %shr183.i8367 = lshr i64 %add182.i8366, 0
  %conv165.i8349 = and i64 0, 0
  %add187.i8371 = or i64 %shr183.i8367, %conv165.i8349
  %arrayidx190.i8373 = getelementptr i8, ptr poison, i64 56
  store i64 %add187.i8371, ptr %arrayidx190.i8373, align 8
  %5 = trunc i128 0 to i64
  %conv177.i8248 = and i64 %5, 0
  %arrayidx192.i8262 = getelementptr i8, ptr poison, i64 112
  store i64 %conv177.i8248, ptr %arrayidx192.i8262, align 8
  %6 = trunc i128 %add134.i8203 to i64
  %conv171.i8242 = and i64 %6, 0
  %arrayidx191.i8261 = getelementptr i8, ptr poison, i64 104
  store i64 %conv171.i8242, ptr %arrayidx191.i8261, align 8
  %shr180.i8251 = lshr i64 %add179.i8250, 0
  %7 = trunc i128 %add155.i8226 to i64
  %add182.i8253 = or i64 %shr180.i8251, %7
  %shr183.i8254 = lshr i64 %add182.i8253, 0
  %add187.i8258 = or i64 %shr183.i8254, 0
  %arrayidx190.i8260 = getelementptr i8, ptr poison, i64 96
  store i64 %add187.i8258, ptr %arrayidx190.i8260, align 8
  %and185.i8256 = and i64 %add182.i8253, 0
  %8 = getelementptr i8, ptr poison, i64 88
  store i64 %and185.i8256, ptr %8, align 8
  %and181.i8252 = and i64 %add179.i8250, 0
  %Z.i519 = getelementptr i8, ptr poison, i64 80
  store i64 %and181.i8252, ptr %Z.i519, align 8
  ret i32 0
}
