; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=slp-vectorizer -S -mtriple=x86_64-- -mcpu=znver5 \
; RUN:   | FileCheck %s --check-prefixes=CHECK,STLF-ON
; RUN: opt < %s -passes=slp-vectorizer -slp-store-load-forward-check=false -S \
; RUN:   -mtriple=x86_64-- -mcpu=znver5 \
; RUN:   | FileCheck %s --check-prefixes=CHECK,STLF-OFF

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

;
; Test 1: Backward loop-carried load at misaligned distance.
;
;   for (int i = 5; i < n; i += 4) {
;     int t = A[i-5];                ; load 20 bytes (5*4) before store base
;     A[i]   = t + 1;
;     A[i+1] = t + 2;
;     A[i+2] = t + 3;
;     A[i+3] = t + 4;
;   }
;
; After SLP with VF=4, the four stores would become a single 16-byte vector
; store at A[i].  The load at A[i-5] is 20 bytes behind:
;   20 % 16 = 4  -> misaligned, load straddles two pending vector stores
;   20 / 16 = 1  -> store still hot in store buffer
; The new check should bail out and leave the four-wide chain scalar.
;
define void @stlf_conflict_backward_misaligned(ptr noalias %A, i64 %n) {
; STLF-ON-LABEL: define void @stlf_conflict_backward_misaligned(
; STLF-ON-SAME: ptr noalias [[A:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; STLF-ON-NEXT:  [[ENTRY:.*]]:
; STLF-ON-NEXT:    br label %[[FOR_BODY:.*]]
; STLF-ON:       [[FOR_BODY]]:
; STLF-ON-NEXT:    [[I:%.*]] = phi i64 [ 5, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[FOR_BODY]] ]
; STLF-ON-NEXT:    [[BACK_IDX:%.*]] = sub i64 [[I]], 5
; STLF-ON-NEXT:    [[BACK_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[BACK_IDX]]
; STLF-ON-NEXT:    [[T:%.*]] = load i32, ptr [[BACK_GEP]], align 4
; STLF-ON-NEXT:    [[T3:%.*]] = add nsw i32 [[T]], 3
; STLF-ON-NEXT:    [[T4:%.*]] = add nsw i32 [[T]], 4
; STLF-ON-NEXT:    [[I1:%.*]] = add nuw nsw i64 [[I]], 2
; STLF-ON-NEXT:    [[I3:%.*]] = add nuw nsw i64 [[I]], 3
; STLF-ON-NEXT:    [[GEP0:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; STLF-ON-NEXT:    [[GEP1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I1]]
; STLF-ON-NEXT:    [[GEP3:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I3]]
; STLF-ON-NEXT:    [[TMP0:%.*]] = insertelement <2 x i32> poison, i32 [[T]], i32 0
; STLF-ON-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i32> [[TMP0]], <2 x i32> poison, <2 x i32> zeroinitializer
; STLF-ON-NEXT:    [[TMP2:%.*]] = add nsw <2 x i32> [[TMP1]], <i32 1, i32 2>
; STLF-ON-NEXT:    store <2 x i32> [[TMP2]], ptr [[GEP0]], align 4
; STLF-ON-NEXT:    store i32 [[T3]], ptr [[GEP1]], align 4
; STLF-ON-NEXT:    store i32 [[T4]], ptr [[GEP3]], align 4
; STLF-ON-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 4
; STLF-ON-NEXT:    [[CMP:%.*]] = icmp slt i64 [[I_NEXT]], [[N]]
; STLF-ON-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END:.*]]
; STLF-ON:       [[FOR_END]]:
; STLF-ON-NEXT:    ret void
;
; STLF-OFF-LABEL: define void @stlf_conflict_backward_misaligned(
; STLF-OFF-SAME: ptr noalias [[A:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; STLF-OFF-NEXT:  [[ENTRY:.*]]:
; STLF-OFF-NEXT:    br label %[[FOR_BODY:.*]]
; STLF-OFF:       [[FOR_BODY]]:
; STLF-OFF-NEXT:    [[I:%.*]] = phi i64 [ 5, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[FOR_BODY]] ]
; STLF-OFF-NEXT:    [[BACK_IDX:%.*]] = sub i64 [[I]], 5
; STLF-OFF-NEXT:    [[BACK_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[BACK_IDX]]
; STLF-OFF-NEXT:    [[T:%.*]] = load i32, ptr [[BACK_GEP]], align 4
; STLF-OFF-NEXT:    [[GEP0:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; STLF-OFF-NEXT:    [[TMP0:%.*]] = insertelement <4 x i32> poison, i32 [[T]], i32 0
; STLF-OFF-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <4 x i32> zeroinitializer
; STLF-OFF-NEXT:    [[TMP2:%.*]] = add nsw <4 x i32> [[TMP1]], <i32 1, i32 2, i32 3, i32 4>
; STLF-OFF-NEXT:    store <4 x i32> [[TMP2]], ptr [[GEP0]], align 4
; STLF-OFF-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 4
; STLF-OFF-NEXT:    [[CMP:%.*]] = icmp slt i64 [[I_NEXT]], [[N]]
; STLF-OFF-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END:.*]]
; STLF-OFF:       [[FOR_END]]:
; STLF-OFF-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %i = phi i64 [ 5, %entry ], [ %i.next, %for.body ]

  %back.idx = sub i64 %i, 5
  %back.gep = getelementptr inbounds i32, ptr %A, i64 %back.idx
  %t = load i32, ptr %back.gep, align 4

  %t1 = add nsw i32 %t, 1
  %t2 = add nsw i32 %t, 2
  %t3 = add nsw i32 %t, 3
  %t4 = add nsw i32 %t, 4

  %i1 = add nuw nsw i64 %i, 1
  %i2 = add nuw nsw i64 %i, 2
  %i3 = add nuw nsw i64 %i, 3

  %gep0 = getelementptr inbounds i32, ptr %A, i64 %i
  %gep1 = getelementptr inbounds i32, ptr %A, i64 %i1
  %gep2 = getelementptr inbounds i32, ptr %A, i64 %i2
  %gep3 = getelementptr inbounds i32, ptr %A, i64 %i3

  store i32 %t1, ptr %gep0, align 4
  store i32 %t2, ptr %gep1, align 4
  store i32 %t3, ptr %gep2, align 4
  store i32 %t4, ptr %gep3, align 4

  %i.next = add nuw nsw i64 %i, 4
  %cmp = icmp slt i64 %i.next, %n
  br i1 %cmp, label %for.body, label %for.end

for.end:
  ret void
}

;
; Test 2: Backward load at distance ALIGNED to vector store width.
;
;   for (int i = 4; i < n; i += 4) {
;     int t = A[i-4];                ; load 16 bytes (4*4) before store base
;     A[i]   = t + 1;  ...
;   }
;
; Distance = 16, VectorStoreBytes = 16, 16 % 16 == 0 -> NOT misaligned.
; The load lands exactly on a previous vector store, so STLF can forward.
; The check should NOT fire; vectorization is allowed.
;
define void @stlf_no_conflict_backward_aligned(ptr noalias %A, i64 %n) {
; CHECK-LABEL: define void @stlf_no_conflict_backward_aligned(
; CHECK-SAME: ptr noalias [[A:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 4, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[BACK_IDX:%.*]] = sub i64 [[I]], 4
; CHECK-NEXT:    [[BACK_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[BACK_IDX]]
; CHECK-NEXT:    [[T:%.*]] = load i32, ptr [[BACK_GEP]], align 4
; CHECK-NEXT:    [[GEP0:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x i32> poison, i32 [[T]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw <4 x i32> [[TMP1]], <i32 1, i32 2, i32 3, i32 4>
; CHECK-NEXT:    store <4 x i32> [[TMP2]], ptr [[GEP0]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END:.*]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %i = phi i64 [ 4, %entry ], [ %i.next, %for.body ]

  %back.idx = sub i64 %i, 4
  %back.gep = getelementptr inbounds i32, ptr %A, i64 %back.idx
  %t = load i32, ptr %back.gep, align 4

  %t1 = add nsw i32 %t, 1
  %t2 = add nsw i32 %t, 2
  %t3 = add nsw i32 %t, 3
  %t4 = add nsw i32 %t, 4

  %i1 = add nuw nsw i64 %i, 1
  %i2 = add nuw nsw i64 %i, 2
  %i3 = add nuw nsw i64 %i, 3

  %gep0 = getelementptr inbounds i32, ptr %A, i64 %i
  %gep1 = getelementptr inbounds i32, ptr %A, i64 %i1
  %gep2 = getelementptr inbounds i32, ptr %A, i64 %i2
  %gep3 = getelementptr inbounds i32, ptr %A, i64 %i3

  store i32 %t1, ptr %gep0, align 4
  store i32 %t2, ptr %gep1, align 4
  store i32 %t3, ptr %gep2, align 4
  store i32 %t4, ptr %gep3, align 4

  %i.next = add nuw nsw i64 %i, 4
  %cmp = icmp slt i64 %i.next, %n
  br i1 %cmp, label %for.body, label %for.end

for.end:
  ret void
}

;
; Test 3: Forward reference (load AHEAD of stores).
;
; Positive pointer diff -> not a backward loop-carried dep, no STLF concern.
; Vectorization should proceed.
;
define void @stlf_no_conflict_forward(ptr noalias %A, i64 %n) {
; CHECK-LABEL: define void @stlf_no_conflict_forward(
; CHECK-SAME: ptr noalias [[A:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[FWD_IDX:%.*]] = add nuw nsw i64 [[I]], 64
; CHECK-NEXT:    [[FWD_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[FWD_IDX]]
; CHECK-NEXT:    [[T:%.*]] = load i32, ptr [[FWD_GEP]], align 4
; CHECK-NEXT:    [[GEP0:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x i32> poison, i32 [[T]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw <4 x i32> [[TMP1]], <i32 1, i32 2, i32 3, i32 4>
; CHECK-NEXT:    store <4 x i32> [[TMP2]], ptr [[GEP0]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END:.*]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %i = phi i64 [ 0, %entry ], [ %i.next, %for.body ]

  %fwd.idx = add nuw nsw i64 %i, 64
  %fwd.gep = getelementptr inbounds i32, ptr %A, i64 %fwd.idx
  %t = load i32, ptr %fwd.gep, align 4

  %t1 = add nsw i32 %t, 1
  %t2 = add nsw i32 %t, 2
  %t3 = add nsw i32 %t, 3
  %t4 = add nsw i32 %t, 4

  %i1 = add nuw nsw i64 %i, 1
  %i2 = add nuw nsw i64 %i, 2
  %i3 = add nuw nsw i64 %i, 3

  %gep0 = getelementptr inbounds i32, ptr %A, i64 %i
  %gep1 = getelementptr inbounds i32, ptr %A, i64 %i1
  %gep2 = getelementptr inbounds i32, ptr %A, i64 %i2
  %gep3 = getelementptr inbounds i32, ptr %A, i64 %i3

  store i32 %t1, ptr %gep0, align 4
  store i32 %t2, ptr %gep1, align 4
  store i32 %t3, ptr %gep2, align 4
  store i32 %t4, ptr %gep3, align 4

  %i.next = add nuw nsw i64 %i, 4
  %cmp = icmp slt i64 %i.next, %n
  br i1 %cmp, label %for.body, label %for.end

for.end:
  ret void
}

;
; Test 4: Stores not in a loop (straight-line code).
;
; STLF stalls only matter when the same code executes repeatedly and the
; store buffer is hot.  Outside loops the check should not fire.
;
define void @stlf_no_conflict_no_loop(ptr noalias %A) {
; CHECK-LABEL: define void @stlf_no_conflict_no_loop(
; CHECK-SAME: ptr noalias [[A:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[BACK_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 -5
; CHECK-NEXT:    [[T:%.*]] = load i32, ptr [[BACK_GEP]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <4 x i32> poison, i32 [[T]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP3:%.*]] = add nsw <4 x i32> [[TMP2]], <i32 1, i32 2, i32 3, i32 4>
; CHECK-NEXT:    store <4 x i32> [[TMP3]], ptr [[A]], align 4
; CHECK-NEXT:    ret void
;
  %back.gep = getelementptr inbounds i32, ptr %A, i64 -5
  %t = load i32, ptr %back.gep, align 4

  %t1 = add nsw i32 %t, 1
  %t2 = add nsw i32 %t, 2
  %t3 = add nsw i32 %t, 3
  %t4 = add nsw i32 %t, 4

  %gep1 = getelementptr inbounds i32, ptr %A, i64 1
  %gep2 = getelementptr inbounds i32, ptr %A, i64 2
  %gep3 = getelementptr inbounds i32, ptr %A, i64 3

  store i32 %t1, ptr %A, align 4
  store i32 %t2, ptr %gep1, align 4
  store i32 %t3, ptr %gep2, align 4
  store i32 %t4, ptr %gep3, align 4
  ret void
}

;
; Test 5: Load from a DIFFERENT underlying object.
;
; The check restricts scanning to loads with the same underlying object as
; the stores.  A load from an unrelated array can never cause STLF on the
; widened store, so the check should not fire.
;
define void @stlf_no_conflict_different_base(ptr noalias %A, ptr noalias %B,
; CHECK-LABEL: define void @stlf_no_conflict_different_base(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[B:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 5, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[B_IDX:%.*]] = sub i64 [[I]], 5
; CHECK-NEXT:    [[B_GEP:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[B_IDX]]
; CHECK-NEXT:    [[T:%.*]] = load i32, ptr [[B_GEP]], align 4
; CHECK-NEXT:    [[GEP0:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x i32> poison, i32 [[T]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw <4 x i32> [[TMP1]], <i32 1, i32 2, i32 3, i32 4>
; CHECK-NEXT:    store <4 x i32> [[TMP2]], ptr [[GEP0]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END:.*]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
  i64 %n) {
entry:
  br label %for.body

for.body:
  %i = phi i64 [ 5, %entry ], [ %i.next, %for.body ]

  %b.idx = sub i64 %i, 5
  %b.gep = getelementptr inbounds i32, ptr %B, i64 %b.idx
  %t = load i32, ptr %b.gep, align 4

  %t1 = add nsw i32 %t, 1
  %t2 = add nsw i32 %t, 2
  %t3 = add nsw i32 %t, 3
  %t4 = add nsw i32 %t, 4

  %i1 = add nuw nsw i64 %i, 1
  %i2 = add nuw nsw i64 %i, 2
  %i3 = add nuw nsw i64 %i, 3

  %gep0 = getelementptr inbounds i32, ptr %A, i64 %i
  %gep1 = getelementptr inbounds i32, ptr %A, i64 %i1
  %gep2 = getelementptr inbounds i32, ptr %A, i64 %i2
  %gep3 = getelementptr inbounds i32, ptr %A, i64 %i3

  store i32 %t1, ptr %gep0, align 4
  store i32 %t2, ptr %gep1, align 4
  store i32 %t3, ptr %gep2, align 4
  store i32 %t4, ptr %gep3, align 4

  %i.next = add nuw nsw i64 %i, 4
  %cmp = icmp slt i64 %i.next, %n
  br i1 %cmp, label %for.body, label %for.end

for.end:
  ret void
}

;
; Test 6: Volatile load is skipped (not "simple").
;
; A volatile load fails LoadInst::isSimple() and is never considered by the
; STLF check, even at a clearly conflicting distance.  The check therefore
; finds no offending load and vectorization proceeds.
;
define void @stlf_volatile_load_skipped(ptr noalias %A, i64 %n) {
; CHECK-LABEL: define void @stlf_volatile_load_skipped(
; CHECK-SAME: ptr noalias [[A:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 5, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[BACK_IDX:%.*]] = sub i64 [[I]], 5
; CHECK-NEXT:    [[BACK_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[BACK_IDX]]
; CHECK-NEXT:    [[T:%.*]] = load volatile i32, ptr [[BACK_GEP]], align 4
; CHECK-NEXT:    [[GEP0:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x i32> poison, i32 [[T]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw <4 x i32> [[TMP1]], <i32 1, i32 2, i32 3, i32 4>
; CHECK-NEXT:    store <4 x i32> [[TMP2]], ptr [[GEP0]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END:.*]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %i = phi i64 [ 5, %entry ], [ %i.next, %for.body ]

  %back.idx = sub i64 %i, 5
  %back.gep = getelementptr inbounds i32, ptr %A, i64 %back.idx
  %t = load volatile i32, ptr %back.gep, align 4

  %t1 = add nsw i32 %t, 1
  %t2 = add nsw i32 %t, 2
  %t3 = add nsw i32 %t, 3
  %t4 = add nsw i32 %t, 4

  %i1 = add nuw nsw i64 %i, 1
  %i2 = add nuw nsw i64 %i, 2
  %i3 = add nuw nsw i64 %i, 3

  %gep0 = getelementptr inbounds i32, ptr %A, i64 %i
  %gep1 = getelementptr inbounds i32, ptr %A, i64 %i1
  %gep2 = getelementptr inbounds i32, ptr %A, i64 %i2
  %gep3 = getelementptr inbounds i32, ptr %A, i64 %i3

  store i32 %t1, ptr %gep0, align 4
  store i32 %t2, ptr %gep1, align 4
  store i32 %t3, ptr %gep2, align 4
  store i32 %t4, ptr %gep3, align 4

  %i.next = add nuw nsw i64 %i, 4
  %cmp = icmp slt i64 %i.next, %n
  br i1 %cmp, label %for.body, label %for.end

for.end:
  ret void
}

;
; Test 7: Multiple conflicting loads in the same loop.
;
; Both A[i-5] (distance 20 bytes) and A[i-7] (distance 28 bytes) are
; misaligned to a 16-byte vector store and within the safety window.  The
; check fires on the first one encountered and bails out.
;
define void @stlf_multiple_conflicting_loads(ptr noalias %A, i64 %n) {
; STLF-ON-LABEL: define void @stlf_multiple_conflicting_loads(
; STLF-ON-SAME: ptr noalias [[A:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; STLF-ON-NEXT:  [[ENTRY:.*]]:
; STLF-ON-NEXT:    br label %[[FOR_BODY:.*]]
; STLF-ON:       [[FOR_BODY]]:
; STLF-ON-NEXT:    [[I:%.*]] = phi i64 [ 7, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[FOR_BODY]] ]
; STLF-ON-NEXT:    [[BACK5_IDX:%.*]] = sub i64 [[I]], 5
; STLF-ON-NEXT:    [[BACK5_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[BACK5_IDX]]
; STLF-ON-NEXT:    [[T5:%.*]] = load i32, ptr [[BACK5_GEP]], align 4
; STLF-ON-NEXT:    [[BACK7_IDX:%.*]] = sub i64 [[I]], 7
; STLF-ON-NEXT:    [[BACK7_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[BACK7_IDX]]
; STLF-ON-NEXT:    [[T7:%.*]] = load i32, ptr [[BACK7_GEP]], align 4
; STLF-ON-NEXT:    [[SUM:%.*]] = add nsw i32 [[T5]], [[T7]]
; STLF-ON-NEXT:    [[T1:%.*]] = add nsw i32 [[SUM]], 1
; STLF-ON-NEXT:    [[T2:%.*]] = add nsw i32 [[SUM]], 2
; STLF-ON-NEXT:    [[T3:%.*]] = add nsw i32 [[SUM]], 3
; STLF-ON-NEXT:    [[T4:%.*]] = add nsw i32 [[SUM]], 4
; STLF-ON-NEXT:    [[I1:%.*]] = add nuw nsw i64 [[I]], 1
; STLF-ON-NEXT:    [[I2:%.*]] = add nuw nsw i64 [[I]], 2
; STLF-ON-NEXT:    [[I3:%.*]] = add nuw nsw i64 [[I]], 3
; STLF-ON-NEXT:    [[GEP0:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; STLF-ON-NEXT:    [[GEP1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I1]]
; STLF-ON-NEXT:    [[GEP2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I2]]
; STLF-ON-NEXT:    [[GEP3:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I3]]
; STLF-ON-NEXT:    store i32 [[T1]], ptr [[GEP0]], align 4
; STLF-ON-NEXT:    store i32 [[T2]], ptr [[GEP1]], align 4
; STLF-ON-NEXT:    store i32 [[T3]], ptr [[GEP2]], align 4
; STLF-ON-NEXT:    store i32 [[T4]], ptr [[GEP3]], align 4
; STLF-ON-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 4
; STLF-ON-NEXT:    [[CMP:%.*]] = icmp slt i64 [[I_NEXT]], [[N]]
; STLF-ON-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END:.*]]
; STLF-ON:       [[FOR_END]]:
; STLF-ON-NEXT:    ret void
;
; STLF-OFF-LABEL: define void @stlf_multiple_conflicting_loads(
; STLF-OFF-SAME: ptr noalias [[A:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; STLF-OFF-NEXT:  [[ENTRY:.*]]:
; STLF-OFF-NEXT:    br label %[[FOR_BODY:.*]]
; STLF-OFF:       [[FOR_BODY]]:
; STLF-OFF-NEXT:    [[I:%.*]] = phi i64 [ 7, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[FOR_BODY]] ]
; STLF-OFF-NEXT:    [[BACK5_IDX:%.*]] = sub i64 [[I]], 5
; STLF-OFF-NEXT:    [[BACK5_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[BACK5_IDX]]
; STLF-OFF-NEXT:    [[T5:%.*]] = load i32, ptr [[BACK5_GEP]], align 4
; STLF-OFF-NEXT:    [[BACK7_IDX:%.*]] = sub i64 [[I]], 7
; STLF-OFF-NEXT:    [[BACK7_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[BACK7_IDX]]
; STLF-OFF-NEXT:    [[T7:%.*]] = load i32, ptr [[BACK7_GEP]], align 4
; STLF-OFF-NEXT:    [[SUM:%.*]] = add nsw i32 [[T5]], [[T7]]
; STLF-OFF-NEXT:    [[GEP0:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; STLF-OFF-NEXT:    [[TMP0:%.*]] = insertelement <4 x i32> poison, i32 [[SUM]], i32 0
; STLF-OFF-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <4 x i32> zeroinitializer
; STLF-OFF-NEXT:    [[TMP2:%.*]] = add nsw <4 x i32> [[TMP1]], <i32 1, i32 2, i32 3, i32 4>
; STLF-OFF-NEXT:    store <4 x i32> [[TMP2]], ptr [[GEP0]], align 4
; STLF-OFF-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 4
; STLF-OFF-NEXT:    [[CMP:%.*]] = icmp slt i64 [[I_NEXT]], [[N]]
; STLF-OFF-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END:.*]]
; STLF-OFF:       [[FOR_END]]:
; STLF-OFF-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %i = phi i64 [ 7, %entry ], [ %i.next, %for.body ]

  %back5.idx = sub i64 %i, 5
  %back5.gep = getelementptr inbounds i32, ptr %A, i64 %back5.idx
  %t5 = load i32, ptr %back5.gep, align 4

  %back7.idx = sub i64 %i, 7
  %back7.gep = getelementptr inbounds i32, ptr %A, i64 %back7.idx
  %t7 = load i32, ptr %back7.gep, align 4

  %sum = add nsw i32 %t5, %t7
  %t1 = add nsw i32 %sum, 1
  %t2 = add nsw i32 %sum, 2
  %t3 = add nsw i32 %sum, 3
  %t4 = add nsw i32 %sum, 4

  %i1 = add nuw nsw i64 %i, 1
  %i2 = add nuw nsw i64 %i, 2
  %i3 = add nuw nsw i64 %i, 3

  %gep0 = getelementptr inbounds i32, ptr %A, i64 %i
  %gep1 = getelementptr inbounds i32, ptr %A, i64 %i1
  %gep2 = getelementptr inbounds i32, ptr %A, i64 %i2
  %gep3 = getelementptr inbounds i32, ptr %A, i64 %i3

  store i32 %t1, ptr %gep0, align 4
  store i32 %t2, ptr %gep1, align 4
  store i32 %t3, ptr %gep2, align 4
  store i32 %t4, ptr %gep3, align 4

  %i.next = add nuw nsw i64 %i, 4
  %cmp = icmp slt i64 %i.next, %n
  br i1 %cmp, label %for.body, label %for.end

for.end:
  ret void
}

;
; Test 8: getPointersDiff cannot determine a constant offset.
;
; The conflicting load uses a runtime index loaded from a separate array, so
; SCEV cannot determine the byte offset relative to the stores.
; getPointersDiff returns nullopt, the check skips this load, finds no
; conflict, and vectorization proceeds.
;
define void @stlf_pointer_diff_unknown(ptr noalias %A, ptr noalias %IdxA, i64 %n) {
; CHECK-LABEL: define void @stlf_pointer_diff_unknown(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[IDXA:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[IDX_GEP:%.*]] = getelementptr inbounds i64, ptr [[IDXA]], i64 [[I]]
; CHECK-NEXT:    [[DYN_IDX:%.*]] = load i64, ptr [[IDX_GEP]], align 8
; CHECK-NEXT:    [[DYN_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[DYN_IDX]]
; CHECK-NEXT:    [[T:%.*]] = load i32, ptr [[DYN_GEP]], align 4
; CHECK-NEXT:    [[GEP0:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x i32> poison, i32 [[T]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw <4 x i32> [[TMP1]], <i32 1, i32 2, i32 3, i32 4>
; CHECK-NEXT:    store <4 x i32> [[TMP2]], ptr [[GEP0]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END:.*]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %i = phi i64 [ 0, %entry ], [ %i.next, %for.body ]

  %idx.gep = getelementptr inbounds i64, ptr %IdxA, i64 %i
  %dyn.idx = load i64, ptr %idx.gep, align 8
  %dyn.gep = getelementptr inbounds i32, ptr %A, i64 %dyn.idx
  %t = load i32, ptr %dyn.gep, align 4

  %t1 = add nsw i32 %t, 1
  %t2 = add nsw i32 %t, 2
  %t3 = add nsw i32 %t, 3
  %t4 = add nsw i32 %t, 4

  %i1 = add nuw nsw i64 %i, 1
  %i2 = add nuw nsw i64 %i, 2
  %i3 = add nuw nsw i64 %i, 3

  %gep0 = getelementptr inbounds i32, ptr %A, i64 %i
  %gep1 = getelementptr inbounds i32, ptr %A, i64 %i1
  %gep2 = getelementptr inbounds i32, ptr %A, i64 %i2
  %gep3 = getelementptr inbounds i32, ptr %A, i64 %i3

  store i32 %t1, ptr %gep0, align 4
  store i32 %t2, ptr %gep1, align 4
  store i32 %t3, ptr %gep2, align 4
  store i32 %t4, ptr %gep3, align 4

  %i.next = add nuw nsw i64 %i, 4
  %cmp = icmp slt i64 %i.next, %n
  br i1 %cmp, label %for.body, label %for.end

for.end:
  ret void
}

;
; Test 9: Distance < VectorStoreBytes (load fully within previous vector
; store).
;
; The backward load is only 1 element (4 bytes) before the stores; the entire
; load lies inside the previous iteration's 16-byte vector store, so STLF
; can forward.  The check's `Distance < VectorStoreBytes` early-continue path
; catches this and allows vectorization.
;
define void @stlf_no_conflict_within_prev_store(ptr noalias %A, i64 %n) {
; CHECK-LABEL: define void @stlf_no_conflict_within_prev_store(
; CHECK-SAME: ptr noalias [[A:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 1, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[BACK_IDX:%.*]] = sub i64 [[I]], 1
; CHECK-NEXT:    [[BACK_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[BACK_IDX]]
; CHECK-NEXT:    [[T:%.*]] = load i32, ptr [[BACK_GEP]], align 4
; CHECK-NEXT:    [[GEP0:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x i32> poison, i32 [[T]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw <4 x i32> [[TMP1]], <i32 1, i32 2, i32 3, i32 4>
; CHECK-NEXT:    store <4 x i32> [[TMP2]], ptr [[GEP0]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END:.*]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %i = phi i64 [ 1, %entry ], [ %i.next, %for.body ]

  %back.idx = sub i64 %i, 1
  %back.gep = getelementptr inbounds i32, ptr %A, i64 %back.idx
  %t = load i32, ptr %back.gep, align 4

  %t1 = add nsw i32 %t, 1
  %t2 = add nsw i32 %t, 2
  %t3 = add nsw i32 %t, 3
  %t4 = add nsw i32 %t, 4

  %i1 = add nuw nsw i64 %i, 1
  %i2 = add nuw nsw i64 %i, 2
  %i3 = add nuw nsw i64 %i, 3

  %gep0 = getelementptr inbounds i32, ptr %A, i64 %i
  %gep1 = getelementptr inbounds i32, ptr %A, i64 %i1
  %gep2 = getelementptr inbounds i32, ptr %A, i64 %i2
  %gep3 = getelementptr inbounds i32, ptr %A, i64 %i3

  store i32 %t1, ptr %gep0, align 4
  store i32 %t2, ptr %gep1, align 4
  store i32 %t3, ptr %gep2, align 4
  store i32 %t4, ptr %gep3, align 4

  %i.next = add nuw nsw i64 %i, 4
  %cmp = icmp slt i64 %i.next, %n
  br i1 %cmp, label %for.body, label %for.end

for.end:
  ret void
}

;
; Test 10: Distance just past NumItersForSafety boundary.
;
; For i32 with VF=4: ElementSize=4, VectorStoreBytes=16,
; NumItersForSafety = 8 * ElementSize = 32. The check fires only when
; Distance / VectorStoreBytes < 32. With diff = -129 (load 129 elements
; back), Distance = 516 bytes, 516 / 16 = 32 (NOT < 32), so the recency
; predicate fails and the check does NOT fire even though 516 % 16 = 4
; (misaligned). Vectorization proceeds.
;
define void @stlf_no_conflict_iter_safety_boundary(ptr noalias %A, i64 %n) {
; CHECK-LABEL: define void @stlf_no_conflict_iter_safety_boundary(
; CHECK-SAME: ptr noalias [[A:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 129, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[BACK_IDX:%.*]] = sub i64 [[I]], 129
; CHECK-NEXT:    [[BACK_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[BACK_IDX]]
; CHECK-NEXT:    [[T:%.*]] = load i32, ptr [[BACK_GEP]], align 4
; CHECK-NEXT:    [[GEP0:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x i32> poison, i32 [[T]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw <4 x i32> [[TMP1]], <i32 1, i32 2, i32 3, i32 4>
; CHECK-NEXT:    store <4 x i32> [[TMP2]], ptr [[GEP0]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END:.*]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %i = phi i64 [ 129, %entry ], [ %i.next, %for.body ]

  %back.idx = sub i64 %i, 129
  %back.gep = getelementptr inbounds i32, ptr %A, i64 %back.idx
  %t = load i32, ptr %back.gep, align 4

  %t1 = add nsw i32 %t, 1
  %t2 = add nsw i32 %t, 2
  %t3 = add nsw i32 %t, 3
  %t4 = add nsw i32 %t, 4

  %i1 = add nuw nsw i64 %i, 1
  %i2 = add nuw nsw i64 %i, 2
  %i3 = add nuw nsw i64 %i, 3

  %gep0 = getelementptr inbounds i32, ptr %A, i64 %i
  %gep1 = getelementptr inbounds i32, ptr %A, i64 %i1
  %gep2 = getelementptr inbounds i32, ptr %A, i64 %i2
  %gep3 = getelementptr inbounds i32, ptr %A, i64 %i3

  store i32 %t1, ptr %gep0, align 4
  store i32 %t2, ptr %gep1, align 4
  store i32 %t3, ptr %gep2, align 4
  store i32 %t4, ptr %gep3, align 4

  %i.next = add nuw nsw i64 %i, 4
  %cmp = icmp slt i64 %i.next, %n
  br i1 %cmp, label %for.body, label %for.end

for.end:
  ret void
}

;
; Test 11: Non-i32 element type (i64 VF=2).
;
; Verifies the byte-distance math works for wider types. With i64
; (ElementSize=8) and VF=2: VectorStoreBytes=16, NumItersForSafety=64.
; A load 3 elements back has Distance = 24 bytes, 24/16=1 < 64, and
; 24%16=8 != 0, so the check fires.
;
define void @stlf_conflict_backward_misaligned_i64(ptr noalias %A, i64 %n) {
; STLF-ON-LABEL: define void @stlf_conflict_backward_misaligned_i64(
; STLF-ON-SAME: ptr noalias [[A:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; STLF-ON-NEXT:  [[ENTRY:.*]]:
; STLF-ON-NEXT:    br label %[[FOR_BODY:.*]]
; STLF-ON:       [[FOR_BODY]]:
; STLF-ON-NEXT:    [[I:%.*]] = phi i64 [ 3, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[FOR_BODY]] ]
; STLF-ON-NEXT:    [[BACK_IDX:%.*]] = sub i64 [[I]], 3
; STLF-ON-NEXT:    [[BACK_GEP:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[BACK_IDX]]
; STLF-ON-NEXT:    [[T:%.*]] = load i64, ptr [[BACK_GEP]], align 8
; STLF-ON-NEXT:    [[T1:%.*]] = add nsw i64 [[T]], 1
; STLF-ON-NEXT:    [[T2:%.*]] = add nsw i64 [[T]], 2
; STLF-ON-NEXT:    [[I1:%.*]] = add nuw nsw i64 [[I]], 1
; STLF-ON-NEXT:    [[GEP0:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[I]]
; STLF-ON-NEXT:    [[GEP1:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[I1]]
; STLF-ON-NEXT:    store i64 [[T1]], ptr [[GEP0]], align 8
; STLF-ON-NEXT:    store i64 [[T2]], ptr [[GEP1]], align 8
; STLF-ON-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 2
; STLF-ON-NEXT:    [[CMP:%.*]] = icmp slt i64 [[I_NEXT]], [[N]]
; STLF-ON-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END:.*]]
; STLF-ON:       [[FOR_END]]:
; STLF-ON-NEXT:    ret void
;
; STLF-OFF-LABEL: define void @stlf_conflict_backward_misaligned_i64(
; STLF-OFF-SAME: ptr noalias [[A:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; STLF-OFF-NEXT:  [[ENTRY:.*]]:
; STLF-OFF-NEXT:    br label %[[FOR_BODY:.*]]
; STLF-OFF:       [[FOR_BODY]]:
; STLF-OFF-NEXT:    [[I:%.*]] = phi i64 [ 3, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[FOR_BODY]] ]
; STLF-OFF-NEXT:    [[BACK_IDX:%.*]] = sub i64 [[I]], 3
; STLF-OFF-NEXT:    [[BACK_GEP:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[BACK_IDX]]
; STLF-OFF-NEXT:    [[T:%.*]] = load i64, ptr [[BACK_GEP]], align 8
; STLF-OFF-NEXT:    [[GEP0:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[I]]
; STLF-OFF-NEXT:    [[TMP0:%.*]] = insertelement <2 x i64> poison, i64 [[T]], i32 0
; STLF-OFF-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i64> [[TMP0]], <2 x i64> poison, <2 x i32> zeroinitializer
; STLF-OFF-NEXT:    [[TMP2:%.*]] = add nsw <2 x i64> [[TMP1]], <i64 1, i64 2>
; STLF-OFF-NEXT:    store <2 x i64> [[TMP2]], ptr [[GEP0]], align 8
; STLF-OFF-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 2
; STLF-OFF-NEXT:    [[CMP:%.*]] = icmp slt i64 [[I_NEXT]], [[N]]
; STLF-OFF-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END:.*]]
; STLF-OFF:       [[FOR_END]]:
; STLF-OFF-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %i = phi i64 [ 3, %entry ], [ %i.next, %for.body ]

  %back.idx = sub i64 %i, 3
  %back.gep = getelementptr inbounds i64, ptr %A, i64 %back.idx
  %t = load i64, ptr %back.gep, align 8

  %t1 = add nsw i64 %t, 1
  %t2 = add nsw i64 %t, 2

  %i1 = add nuw nsw i64 %i, 1

  %gep0 = getelementptr inbounds i64, ptr %A, i64 %i
  %gep1 = getelementptr inbounds i64, ptr %A, i64 %i1

  store i64 %t1, ptr %gep0, align 8
  store i64 %t2, ptr %gep1, align 8

  %i.next = add nuw nsw i64 %i, 2
  %cmp = icmp slt i64 %i.next, %n
  br i1 %cmp, label %for.body, label %for.end

for.end:
  ret void
}
