; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=x86_64-unknown -mcpu=core-avx2 -passes=slp-vectorizer < %s | FileCheck %s

@a = common global [4 x i32] zeroinitializer, align 16
@b = common global [4 x i32] zeroinitializer, align 16
@r = common global [4 x i32] zeroinitializer, align 16
@flags = common global [4 x i1] zeroinitializer, align 1
@c = common global [4 x i32] zeroinitializer, align 16
@structs = common global [4 x { i32, i1 }] zeroinitializer, align 16

declare {i32, i1} @llvm.sadd.with.overflow.i32(i32, i32)

; Sum field stores use permutation [2,0,3,1], overflow field stores use [3,2,1,0].
define void @store_both_fields_different_permutations() {
; CHECK-LABEL: define void @store_both_fields_different_permutations(
; CHECK-SAME: ) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr @a, align 4
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> poison, <4 x i32> <i32 2, i32 0, i32 3, i32 1>
; CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i32>, ptr @b, align 4
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> poison, <4 x i32> <i32 2, i32 0, i32 3, i32 1>
; CHECK-NEXT:    [[TMP5:%.*]] = call { <4 x i32>, <4 x i1> } @llvm.sadd.with.overflow.v4i32(<4 x i32> [[TMP2]], <4 x i32> [[TMP4]])
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <4 x i32>, <4 x i1> } [[TMP5]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <4 x i32>, <4 x i1> } [[TMP5]], 1
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <4 x i1> [[TMP7]], i32 1
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x i1> [[TMP7]], i32 3
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x i1> [[TMP7]], i32 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <4 x i1> [[TMP7]], i32 2
; CHECK-NEXT:    store <4 x i32> [[TMP6]], ptr @r, align 4
; CHECK-NEXT:    store i1 [[TMP11]], ptr @flags, align 1
; CHECK-NEXT:    store i1 [[TMP10]], ptr getelementptr inbounds ([4 x i1], ptr @flags, i64 0, i64 1), align 1
; CHECK-NEXT:    store i1 [[TMP9]], ptr getelementptr inbounds ([4 x i1], ptr @flags, i64 0, i64 2), align 1
; CHECK-NEXT:    store i1 [[TMP8]], ptr getelementptr inbounds ([4 x i1], ptr @flags, i64 0, i64 3), align 1
; CHECK-NEXT:    ret void
;
  %a0 = load i32, ptr @a, align 4
  %a1 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 1), align 4
  %a2 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 2), align 4
  %a3 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 3), align 4
  %b0 = load i32, ptr @b, align 4
  %b1 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 1), align 4
  %b2 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 2), align 4
  %b3 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 3), align 4
  %x0 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a0, i32 %b0)
  %x1 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a1, i32 %b1)
  %x2 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a2, i32 %b2)
  %x3 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a3, i32 %b3)
  %s0 = extractvalue {i32, i1} %x0, 0
  %s1 = extractvalue {i32, i1} %x1, 0
  %s2 = extractvalue {i32, i1} %x2, 0
  %s3 = extractvalue {i32, i1} %x3, 0
  %o0 = extractvalue {i32, i1} %x0, 1
  %o1 = extractvalue {i32, i1} %x1, 1
  %o2 = extractvalue {i32, i1} %x2, 1
  %o3 = extractvalue {i32, i1} %x3, 1
  store i32 %s2, ptr @r, align 4
  store i32 %s0, ptr getelementptr inbounds ([4 x i32], ptr @r, i64 0, i64 1), align 4
  store i32 %s3, ptr getelementptr inbounds ([4 x i32], ptr @r, i64 0, i64 2), align 4
  store i32 %s1, ptr getelementptr inbounds ([4 x i32], ptr @r, i64 0, i64 3), align 4
  store i1 %o3, ptr @flags, align 1
  store i1 %o2, ptr getelementptr inbounds ([4 x i1], ptr @flags, i64 0, i64 1), align 1
  store i1 %o1, ptr getelementptr inbounds ([4 x i1], ptr @flags, i64 0, i64 2), align 1
  store i1 %o0, ptr getelementptr inbounds ([4 x i1], ptr @flags, i64 0, i64 3), align 1
  ret void
}

; Extractvalues are in-tree (mul) and also feed permuted external stores.
; Bottom-to-top reorder must not break in-tree vector mul or external store order.
define void @extract_reordered_in_tree_and_external() {
; CHECK-LABEL: define void @extract_reordered_in_tree_and_external(
; CHECK-SAME: ) #[[ATTR1]] {
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr @a, align 4
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> poison, <4 x i32> <i32 2, i32 0, i32 3, i32 1>
; CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i32>, ptr @b, align 4
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> poison, <4 x i32> <i32 2, i32 0, i32 3, i32 1>
; CHECK-NEXT:    [[TMP5:%.*]] = call { <4 x i32>, <4 x i1> } @llvm.sadd.with.overflow.v4i32(<4 x i32> [[TMP2]], <4 x i32> [[TMP4]])
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <4 x i32>, <4 x i1> } [[TMP5]], 0
; CHECK-NEXT:    store <4 x i32> [[TMP6]], ptr @r, align 4
; CHECK-NEXT:    [[TMP7:%.*]] = mul <4 x i32> [[TMP6]], splat (i32 7)
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i32> [[TMP7]], <4 x i32> poison, <4 x i32> <i32 1, i32 3, i32 0, i32 2>
; CHECK-NEXT:    store <4 x i32> [[TMP8]], ptr @c, align 4
; CHECK-NEXT:    ret void
;
  %a0 = load i32, ptr @a, align 4
  %a1 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 1), align 4
  %a2 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 2), align 4
  %a3 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 3), align 4
  %b0 = load i32, ptr @b, align 4
  %b1 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 1), align 4
  %b2 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 2), align 4
  %b3 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 3), align 4
  %x0 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a0, i32 %b0)
  %x1 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a1, i32 %b1)
  %x2 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a2, i32 %b2)
  %x3 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a3, i32 %b3)
  %e0 = extractvalue {i32, i1} %x0, 0
  %e1 = extractvalue {i32, i1} %x1, 0
  %e2 = extractvalue {i32, i1} %x2, 0
  %e3 = extractvalue {i32, i1} %x3, 0
  %m0 = mul i32 %e0, 7
  %m1 = mul i32 %e1, 7
  %m2 = mul i32 %e2, 7
  %m3 = mul i32 %e3, 7
  store i32 %e2, ptr @r, align 4
  store i32 %e0, ptr getelementptr inbounds ([4 x i32], ptr @r, i64 0, i64 1), align 4
  store i32 %e3, ptr getelementptr inbounds ([4 x i32], ptr @r, i64 0, i64 2), align 4
  store i32 %e1, ptr getelementptr inbounds ([4 x i32], ptr @r, i64 0, i64 3), align 4
  store i32 %m0, ptr @c, align 4
  store i32 %m1, ptr getelementptr inbounds ([4 x i32], ptr @c, i64 0, i64 1), align 4
  store i32 %m2, ptr getelementptr inbounds ([4 x i32], ptr @c, i64 0, i64 2), align 4
  store i32 %m3, ptr getelementptr inbounds ([4 x i32], ptr @c, i64 0, i64 3), align 4
  ret void
}

; Store-chain root stores whole struct values. Non-extractvalue store users
; prevent struct-call vectorization.
define void @store_struct_root_with_extract_users() {
; CHECK-LABEL: define void @store_struct_root_with_extract_users(
; CHECK-SAME: ) #[[ATTR1]] {
; CHECK-NEXT:    [[A0:%.*]] = load i32, ptr @a, align 4
; CHECK-NEXT:    [[A1:%.*]] = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 1), align 4
; CHECK-NEXT:    [[A2:%.*]] = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 2), align 4
; CHECK-NEXT:    [[A3:%.*]] = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 3), align 4
; CHECK-NEXT:    [[B0:%.*]] = load i32, ptr @b, align 4
; CHECK-NEXT:    [[B1:%.*]] = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 1), align 4
; CHECK-NEXT:    [[B2:%.*]] = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 2), align 4
; CHECK-NEXT:    [[B3:%.*]] = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 3), align 4
; CHECK-NEXT:    [[X0:%.*]] = call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 [[A0]], i32 [[B0]])
; CHECK-NEXT:    [[X1:%.*]] = call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 [[A1]], i32 [[B1]])
; CHECK-NEXT:    [[X2:%.*]] = call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 [[A2]], i32 [[B2]])
; CHECK-NEXT:    [[X3:%.*]] = call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 [[A3]], i32 [[B3]])
; CHECK-NEXT:    [[S0:%.*]] = extractvalue { i32, i1 } [[X0]], 0
; CHECK-NEXT:    store { i32, i1 } [[X0]], ptr @structs, align 8
; CHECK-NEXT:    store { i32, i1 } [[X1]], ptr getelementptr inbounds ([4 x { i32, i1 }], ptr @structs, i64 0, i64 1), align 8
; CHECK-NEXT:    store { i32, i1 } [[X2]], ptr getelementptr inbounds ([4 x { i32, i1 }], ptr @structs, i64 0, i64 2), align 8
; CHECK-NEXT:    store { i32, i1 } [[X3]], ptr getelementptr inbounds ([4 x { i32, i1 }], ptr @structs, i64 0, i64 3), align 8
; CHECK-NEXT:    store i32 [[S0]], ptr @r, align 4
; CHECK-NEXT:    ret void
;
  %a0 = load i32, ptr @a, align 4
  %a1 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 1), align 4
  %a2 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 2), align 4
  %a3 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 3), align 4
  %b0 = load i32, ptr @b, align 4
  %b1 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 1), align 4
  %b2 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 2), align 4
  %b3 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 3), align 4
  %x0 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a0, i32 %b0)
  %x1 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a1, i32 %b1)
  %x2 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a2, i32 %b2)
  %x3 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a3, i32 %b3)
  %s0 = extractvalue {i32, i1} %x0, 0
  store {i32, i1} %x0, ptr @structs, align 8
  store {i32, i1} %x1, ptr getelementptr inbounds ([4 x { i32, i1 }], ptr @structs, i64 0, i64 1), align 8
  store {i32, i1} %x2, ptr getelementptr inbounds ([4 x { i32, i1 }], ptr @structs, i64 0, i64 2), align 8
  store {i32, i1} %x3, ptr getelementptr inbounds ([4 x { i32, i1 }], ptr @structs, i64 0, i64 3), align 8
  store i32 %s0, ptr @r, align 4
  ret void
}
