; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define i1 @test(ptr %0, i8 %1) {
; CHECK-LABEL: define i1 @test(
; CHECK-SAME: ptr [[TMP0:%.*]], i8 [[TMP1:%.*]]) {
; CHECK-NEXT:    [[TMP3:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[TMP1]], i8 1)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { i8, i1 } [[TMP3]], 1
; CHECK-NEXT:    br i1 [[TMP4]], label %[[BB8:.*]], label %[[BB5:.*]]
; CHECK:       [[BB5]]:
; CHECK-NEXT:    [[TMP6:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[TMP1]], i8 1)
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { i8, i1 } [[TMP6]], 1
; CHECK-NEXT:    br i1 [[TMP7]], label %[[BB8]], label %[[BB10:.*]]
; CHECK:       [[BB8]]:
; CHECK-NEXT:    [[TMP9:%.*]] = phi i1 [ false, %[[BB10]] ], [ false, %[[BB5]] ], [ false, [[TMP2:%.*]] ]
; CHECK-NEXT:    ret i1 [[TMP9]]
; CHECK:       [[BB10]]:
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { i8, i1 } [[TMP6]], 0
; CHECK-NEXT:    [[TMP12:%.*]] = sext i8 [[TMP11]] to i16
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { i8, i1 } [[TMP3]], 0
; CHECK-NEXT:    [[TMP14:%.*]] = sext i8 [[TMP13]] to i16
; CHECK-NEXT:    [[TMP15:%.*]] = sdiv i16 [[TMP12]], [[TMP14]]
; CHECK-NEXT:    [[TMP16:%.*]] = trunc i16 [[TMP15]] to i8
; CHECK-NEXT:    store i8 [[TMP16]], ptr [[TMP0]], align 1
; CHECK-NEXT:    br label %[[BB8]]
;
  %3 = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %1, i8 1)
  %4 = extractvalue { i8, i1 } %3, 1
  br i1 %4, label %8, label %5

5:                                                ; preds = %2
  %6 = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %1, i8 1)
  %7 = extractvalue { i8, i1 } %6, 1
  br i1 %7, label %8, label %10

8:                                                ; preds = %10, %5, %2
  %9 = phi i1 [ false, %10 ], [ false, %5 ], [ false, %2 ]
  ret i1 %9

10:                                               ; preds = %5
  %11 = extractvalue { i8, i1 } %6, 0
  %12 = sext i8 %11 to i16
  %13 = extractvalue { i8, i1 } %3, 0
  %14 = sext i8 %13 to i16
  %15 = sdiv i16 %12, %14
  %16 = trunc i16 %15 to i8
  store i8 %16, ptr %0, align 1
  br label %8
}

declare { i8, i1 } @llvm.sadd.with.overflow.i8(i8, i8)
