; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=x86_64-unknown -mcpu=core-avx2 -passes=slp-vectorizer < %s | FileCheck %s

@a = common global [4 x i32] zeroinitializer, align 16
@b = common global [4 x i32] zeroinitializer, align 16
@r = common global [4 x i32] zeroinitializer, align 16
@flags = common global [4 x i1] zeroinitializer, align 1

declare {i32, i1} @llvm.sadd.with.overflow.i32(i32, i32)
declare void @use_struct({ i32, i1 })

define void @test() {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr @a, align 4
; CHECK-NEXT:    [[TMP2:%.*]] = load <4 x i32>, ptr @b, align 4
; CHECK-NEXT:    [[TMP3:%.*]] = call { <4 x i32>, <4 x i1> } @llvm.sadd.with.overflow.v4i32(<4 x i32> [[TMP1]], <4 x i32> [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <4 x i32>, <4 x i1> } [[TMP3]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <4 x i32> [[TMP4]], i32 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x i32> [[TMP4]], i32 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <4 x i32> [[TMP4]], i32 2
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <4 x i32> [[TMP4]], i32 3
; CHECK-NEXT:    [[M0:%.*]] = mul i32 [[TMP5]], 7
; CHECK-NEXT:    [[M1:%.*]] = mul i32 [[TMP6]], 7
; CHECK-NEXT:    [[M2:%.*]] = mul i32 [[TMP7]], 7
; CHECK-NEXT:    [[M3:%.*]] = mul i32 [[TMP8]], 7
; CHECK-NEXT:    store volatile i32 [[M0]], ptr @r, align 4
; CHECK-NEXT:    store volatile i32 [[M1]], ptr @r, align 4
; CHECK-NEXT:    store volatile i32 [[M2]], ptr @r, align 4
; CHECK-NEXT:    store volatile i32 [[M3]], ptr @r, align 4
; CHECK-NEXT:    [[AD0:%.*]] = add i32 [[TMP5]], 1
; CHECK-NEXT:    [[AD1:%.*]] = add i32 [[TMP6]], 2
; CHECK-NEXT:    [[AD2:%.*]] = add i32 [[TMP7]], 3
; CHECK-NEXT:    [[AD3:%.*]] = add i32 [[TMP8]], 4
; CHECK-NEXT:    store volatile i32 [[AD0]], ptr @r, align 4
; CHECK-NEXT:    store volatile i32 [[AD1]], ptr @r, align 4
; CHECK-NEXT:    store volatile i32 [[AD2]], ptr @r, align 4
; CHECK-NEXT:    store volatile i32 [[AD3]], ptr @r, align 4
; CHECK-NEXT:    ret void
;
  %a0 = load i32, ptr @a, align 4
  %a1 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i32 0, i64 1), align 4
  %a2 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i32 0, i64 2), align 4
  %a3 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i32 0, i64 3), align 4
  %b0 = load i32, ptr @b, align 4
  %b1 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i32 0, i64 1), align 4
  %b2 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i32 0, i64 2), align 4
  %b3 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i32 0, i64 3), align 4
  %x0 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a0, i32 %b0)
  %x1 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a1, i32 %b1)
  %x2 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a2, i32 %b2)
  %x3 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a3, i32 %b3)
  %e0a = extractvalue {i32, i1} %x0, 0
  %e1a = extractvalue {i32, i1} %x1, 0
  %e2a = extractvalue {i32, i1} %x2, 0
  %e3a = extractvalue {i32, i1} %x3, 0
  %m0 = mul i32 %e0a, 7
  %m1 = mul i32 %e1a, 7
  %m2 = mul i32 %e2a, 7
  %m3 = mul i32 %e3a, 7
  store volatile i32 %m0, ptr @r, align 4
  store volatile i32 %m1, ptr @r, align 4
  store volatile i32 %m2, ptr @r, align 4
  store volatile i32 %m3, ptr @r, align 4
  %e0b = extractvalue {i32, i1} %x0, 0
  %e1b = extractvalue {i32, i1} %x1, 0
  %e2b = extractvalue {i32, i1} %x2, 0
  %e3b = extractvalue {i32, i1} %x3, 0
  %ad0 = add i32 %e0b, 1
  %ad1 = add i32 %e1b, 2
  %ad2 = add i32 %e2b, 3
  %ad3 = add i32 %e3b, 4
  store volatile i32 %ad0, ptr @r, align 4
  store volatile i32 %ad1, ptr @r, align 4
  store volatile i32 %ad2, ptr @r, align 4
  store volatile i32 %ad3, ptr @r, align 4
  ret void
}

define void @store_two_fields_different_orders() {
; CHECK-LABEL: define void @store_two_fields_different_orders(
; CHECK-SAME: ) #[[ATTR1]] {
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr @a, align 4
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> poison, <4 x i32> <i32 2, i32 0, i32 3, i32 1>
; CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i32>, ptr @b, align 4
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> poison, <4 x i32> <i32 2, i32 0, i32 3, i32 1>
; CHECK-NEXT:    [[TMP5:%.*]] = call { <4 x i32>, <4 x i1> } @llvm.sadd.with.overflow.v4i32(<4 x i32> [[TMP2]], <4 x i32> [[TMP4]])
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <4 x i32>, <4 x i1> } [[TMP5]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <4 x i32>, <4 x i1> } [[TMP5]], 1
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <4 x i1> [[TMP7]], i32 1
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x i1> [[TMP7]], i32 3
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x i1> [[TMP7]], i32 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <4 x i1> [[TMP7]], i32 2
; CHECK-NEXT:    store <4 x i32> [[TMP6]], ptr @r, align 4
; CHECK-NEXT:    store i1 [[TMP8]], ptr @flags, align 1
; CHECK-NEXT:    store i1 [[TMP9]], ptr getelementptr inbounds ([4 x i1], ptr @flags, i64 0, i64 1), align 1
; CHECK-NEXT:    store i1 [[TMP10]], ptr getelementptr inbounds ([4 x i1], ptr @flags, i64 0, i64 2), align 1
; CHECK-NEXT:    store i1 [[TMP11]], ptr getelementptr inbounds ([4 x i1], ptr @flags, i64 0, i64 3), align 1
; CHECK-NEXT:    ret void
;
  %a0 = load i32, ptr @a, align 4
  %a1 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 1), align 4
  %a2 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 2), align 4
  %a3 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 3), align 4
  %b0 = load i32, ptr @b, align 4
  %b1 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 1), align 4
  %b2 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 2), align 4
  %b3 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 3), align 4
  %x0 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a0, i32 %b0)
  %x1 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a1, i32 %b1)
  %x2 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a2, i32 %b2)
  %x3 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a3, i32 %b3)
  %s0 = extractvalue {i32, i1} %x0, 0
  %s1 = extractvalue {i32, i1} %x1, 0
  %s2 = extractvalue {i32, i1} %x2, 0
  %s3 = extractvalue {i32, i1} %x3, 0
  %o0 = extractvalue {i32, i1} %x0, 1
  %o1 = extractvalue {i32, i1} %x1, 1
  %o2 = extractvalue {i32, i1} %x2, 1
  %o3 = extractvalue {i32, i1} %x3, 1
  store i32 %s2, ptr @r, align 4
  store i32 %s0, ptr getelementptr inbounds ([4 x i32], ptr @r, i64 0, i64 1), align 4
  store i32 %s3, ptr getelementptr inbounds ([4 x i32], ptr @r, i64 0, i64 2), align 4
  store i32 %s1, ptr getelementptr inbounds ([4 x i32], ptr @r, i64 0, i64 3), align 4
  store i1 %o0, ptr @flags, align 1
  store i1 %o1, ptr getelementptr inbounds ([4 x i1], ptr @flags, i64 0, i64 1), align 1
  store i1 %o2, ptr getelementptr inbounds ([4 x i1], ptr @flags, i64 0, i64 2), align 1
  store i1 %o3, ptr getelementptr inbounds ([4 x i1], ptr @flags, i64 0, i64 3), align 1
  ret void
}

define void @non_extractvalue_user_keeps_scalar() {
; CHECK-LABEL: define void @non_extractvalue_user_keeps_scalar(
; CHECK-SAME: ) #[[ATTR1]] {
; CHECK-NEXT:    [[A0:%.*]] = load i32, ptr @a, align 4
; CHECK-NEXT:    [[A3:%.*]] = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 3), align 4
; CHECK-NEXT:    [[B0:%.*]] = load i32, ptr @b, align 4
; CHECK-NEXT:    [[B3:%.*]] = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 3), align 4
; CHECK-NEXT:    [[X0:%.*]] = call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 [[A0]], i32 [[B0]])
; CHECK-NEXT:    [[X3:%.*]] = call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 [[A3]], i32 [[B3]])
; CHECK-NEXT:    [[S0:%.*]] = extractvalue { i32, i1 } [[X0]], 0
; CHECK-NEXT:    [[S3:%.*]] = extractvalue { i32, i1 } [[X3]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i32>, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 1), align 4
; CHECK-NEXT:    [[TMP2:%.*]] = load <2 x i32>, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 1), align 4
; CHECK-NEXT:    [[TMP3:%.*]] = call { <2 x i32>, <2 x i1> } @llvm.sadd.with.overflow.v2i32(<2 x i32> [[TMP1]], <2 x i32> [[TMP2]])
; CHECK-NEXT:    call void @use_struct({ i32, i1 } [[X0]])
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <2 x i32>, <2 x i1> } [[TMP3]], 0
; CHECK-NEXT:    store i32 [[S0]], ptr @r, align 4
; CHECK-NEXT:    store <2 x i32> [[TMP4]], ptr getelementptr inbounds ([4 x i32], ptr @r, i64 0, i64 1), align 4
; CHECK-NEXT:    store i32 [[S3]], ptr getelementptr inbounds ([4 x i32], ptr @r, i64 0, i64 3), align 4
; CHECK-NEXT:    ret void
;
  %a0 = load i32, ptr @a, align 4
  %a1 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 1), align 4
  %a2 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 2), align 4
  %a3 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @a, i64 0, i64 3), align 4
  %b0 = load i32, ptr @b, align 4
  %b1 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 1), align 4
  %b2 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 2), align 4
  %b3 = load i32, ptr getelementptr inbounds ([4 x i32], ptr @b, i64 0, i64 3), align 4
  %x0 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a0, i32 %b0)
  %x1 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a1, i32 %b1)
  %x2 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a2, i32 %b2)
  %x3 = call {i32, i1} @llvm.sadd.with.overflow.i32(i32 %a3, i32 %b3)
  call void @use_struct({ i32, i1 } %x0)
  %s0 = extractvalue {i32, i1} %x0, 0
  %s1 = extractvalue {i32, i1} %x1, 0
  %s2 = extractvalue {i32, i1} %x2, 0
  %s3 = extractvalue {i32, i1} %x3, 0
  store i32 %s0, ptr @r, align 4
  store i32 %s1, ptr getelementptr inbounds ([4 x i32], ptr @r, i64 0, i64 1), align 4
  store i32 %s2, ptr getelementptr inbounds ([4 x i32], ptr @r, i64 0, i64 2), align 4
  store i32 %s3, ptr getelementptr inbounds ([4 x i32], ptr @r, i64 0, i64 3), align 4
  ret void
}
