; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=slp-vectorizer -mtriple=x86_64-unknown-linux-gnu -mcpu=icelake-server -slp-threshold=-37 < %s | FileCheck %s

declare double @llvm.fmuladd.f64(double, double, double)

define void @test(ptr %this, ptr %0, double %1) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[THIS:%.*]], ptr [[TMP0:%.*]], double [[TMP1:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[IF_ELSE:.*:]]
; CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[THIS]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = load <2 x double>, ptr [[TMP0]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = load double, ptr [[THIS]], align 8
; CHECK-NEXT:    [[TMP13:%.*]] = insertelement <2 x double> <double 1.000000e+00, double poison>, double [[TMP1]], i32 1
; CHECK-NEXT:    [[TMP23:%.*]] = fmul <2 x double> <double 1.000000e+00, double 0.000000e+00>, [[TMP13]]
; CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <2 x double> [[TMP23]], <2 x double> poison, <8 x i32> <i32 0, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1>
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x double> [[TMP3]], <2 x double> poison, <3 x i32> <i32 1, i32 poison, i32 0>
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <3 x double> [[TMP8]], double [[TMP4]], i32 1
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <3 x double> [[TMP9]], <3 x double> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 1>
; CHECK-NEXT:    [[TMP11:%.*]] = fmul <4 x double> [[TMP10]], <double 1.000000e+00, double 0.000000e+00, double 1.000000e+00, double 1.000000e+00>
; CHECK-NEXT:    [[TMP12:%.*]] = insertelement <4 x double> <double poison, double 1.000000e+00, double 1.000000e+00, double 1.000000e+00>, double [[TMP4]], i32 0
; CHECK-NEXT:    [[TMP27:%.*]] = fmul <4 x double> zeroinitializer, [[TMP12]]
; CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <3 x double> [[TMP9]], <3 x double> poison, <4 x i32> <i32 2, i32 0, i32 1, i32 1>
; CHECK-NEXT:    [[TMP15:%.*]] = fmul <4 x double> [[TMP14]], <double 1.000000e+00, double 1.000000e+00, double 1.000000e+00, double 0.000000e+00>
; CHECK-NEXT:    [[TMP16:%.*]] = insertelement <4 x double> <double 1.000000e+00, double 1.000000e+00, double poison, double 1.000000e+00>, double [[TMP4]], i32 2
; CHECK-NEXT:    [[TMP17:%.*]] = fmul <4 x double> zeroinitializer, [[TMP16]]
; CHECK-NEXT:    [[TMP18:%.*]] = fneg <4 x double> [[TMP11]]
; CHECK-NEXT:    [[TMP19:%.*]] = fneg <4 x double> [[TMP15]]
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <2 x double> [[TMP13]], <2 x double> <double undef, double 1.000000e+00>, <4 x i32> <i32 1, i32 3, i32 1, i32 1>
; CHECK-NEXT:    [[TMP21:%.*]] = fmul <4 x double> [[TMP18]], [[TMP20]]
; CHECK-NEXT:    [[TMP28:%.*]] = shufflevector <4 x double> [[TMP20]], <4 x double> poison, <4 x i32> <i32 0, i32 0, i32 0, i32 1>
; CHECK-NEXT:    [[TMP29:%.*]] = fmul <4 x double> [[TMP19]], [[TMP28]]
; CHECK-NEXT:    [[TMP24:%.*]] = call <4 x double> @llvm.fmuladd.v4f64(<4 x double> [[TMP21]], <4 x double> zeroinitializer, <4 x double> [[TMP27]])
; CHECK-NEXT:    [[TMP25:%.*]] = fneg <4 x double> [[TMP24]]
; CHECK-NEXT:    [[TMP26:%.*]] = call <4 x double> @llvm.fmuladd.v4f64(<4 x double> [[TMP29]], <4 x double> zeroinitializer, <4 x double> [[TMP17]])
; CHECK-NEXT:    [[TMP31:%.*]] = shufflevector <4 x double> [[TMP26]], <4 x double> [[TMP25]], <8 x i32> <i32 0, i32 4, i32 1, i32 5, i32 6, i32 2, i32 7, i32 3>
; CHECK-NEXT:    [[TMP34:%.*]] = fmul <8 x double> [[TMP31]], [[TMP22]]
; CHECK-NEXT:    [[TMP35:%.*]] = fptrunc <8 x double> [[TMP34]] to <8 x float>
; CHECK-NEXT:    store <8 x float> [[TMP35]], ptr [[TMP7]], align 4
; CHECK-NEXT:    ret void
;
if.else:
  %2 = load double, ptr %0, align 8
  %arrayidx.i1464 = getelementptr i8, ptr %0, i64 8
  %3 = load double, ptr %arrayidx.i1464, align 8
  %4 = load double, ptr %this, align 8
  %div251 = fmul double %1, 0.000000e+00
  %mul257 = fmul double %4, 0.000000e+00
  %mul305 = fmul double %4, 0.000000e+00
  %5 = fneg double %2
  %neg356 = fmul double %1, %5
  %6 = tail call double @llvm.fmuladd.f64(double %neg356, double 0.000000e+00, double 0.000000e+00)
  %conv358 = fptrunc double %6 to float
  %7 = load ptr, ptr %this, align 8
  store float %conv358, ptr %7, align 4
  %8 = fneg double %3
  %neg380 = fmul double %1, %8
  %9 = tail call double @llvm.fmuladd.f64(double %neg380, double 0.000000e+00, double %mul257)
  %fneg381 = fneg double %9
  %mul382 = fmul double %div251, %fneg381
  %conv383 = fptrunc double %mul382 to float
  %arrayidx.i2136 = getelementptr i8, ptr %7, i64 4
  store float %conv383, ptr %arrayidx.i2136, align 4
  %10 = tail call double @llvm.fmuladd.f64(double %neg380, double 0.000000e+00, double 0.000000e+00)
  %mul400 = fmul double %10, %div251
  %conv401 = fptrunc double %mul400 to float
  %arrayidx.i2178 = getelementptr i8, ptr %7, i64 8
  store float %conv401, ptr %arrayidx.i2178, align 4
  %neg417 = fneg double %mul257
  %11 = tail call double @llvm.fmuladd.f64(double %neg417, double 0.000000e+00, double 0.000000e+00)
  %fneg418 = fneg double %11
  %mul419 = fmul double %div251, %fneg418
  %conv420 = fptrunc double %mul419 to float
  %arrayidx.i2220 = getelementptr i8, ptr %7, i64 12
  store float %conv420, ptr %arrayidx.i2220, align 4
  %neg436 = fmul double %1, %5
  %12 = tail call double @llvm.fmuladd.f64(double %neg436, double 0.000000e+00, double 0.000000e+00)
  %fneg437 = fneg double %12
  %mul438 = fmul double %div251, %fneg437
  %conv439 = fptrunc double %mul438 to float
  %arrayidx.i2262 = getelementptr i8, ptr %7, i64 16
  store float %conv439, ptr %arrayidx.i2262, align 4
  %13 = fneg double %4
  %neg455 = fmul double %1, %13
  %14 = tail call double @llvm.fmuladd.f64(double %neg455, double 0.000000e+00, double %mul305)
  %mul456 = fmul double %14, %div251
  %conv457 = fptrunc double %mul456 to float
  %arrayidx.i2304 = getelementptr i8, ptr %7, i64 20
  store float %conv457, ptr %arrayidx.i2304, align 4
  %15 = tail call double @llvm.fmuladd.f64(double %neg455, double 0.000000e+00, double 0.000000e+00)
  %fneg474 = fneg double %15
  %mul475 = fmul double %div251, %fneg474
  %conv476 = fptrunc double %mul475 to float
  %arrayidx.i2346 = getelementptr i8, ptr %7, i64 24
  store float %conv476, ptr %arrayidx.i2346, align 4
  %neg492 = fneg double %mul305
  %16 = tail call double @llvm.fmuladd.f64(double %neg492, double 0.000000e+00, double 0.000000e+00)
  %mul493 = fmul double %16, %div251
  %conv494 = fptrunc double %mul493 to float
  %arrayidx.i2388 = getelementptr i8, ptr %7, i64 28
  store float %conv494, ptr %arrayidx.i2388, align 4
  ret void
}
