; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; bswap should be constant folded when it is passed a constant argument

; RUN: opt < %s -passes=instsimplify -S | FileCheck %s
; RUN: opt < %s -passes=instsimplify -use-constant-int-for-fixed-length-splat -use-constant-int-for-scalable-splat -S | FileCheck %s

declare i16 @llvm.bswap.i16(i16)

declare i32 @llvm.bswap.i32(i32)

declare i64 @llvm.bswap.i64(i64)

declare i80 @llvm.bswap.i80(i80)

define i16 @W() {
; CHECK-LABEL: define i16 @W() {
; CHECK-NEXT:    ret i16 256
;
  %Z = call i16 @llvm.bswap.i16( i16 1 )          ; <i16> [#uses=1]
  ret i16 %Z
}

define i32 @X() {
; CHECK-LABEL: define i32 @X() {
; CHECK-NEXT:    ret i32 16777216
;
  %Z = call i32 @llvm.bswap.i32( i32 1 )          ; <i32> [#uses=1]
  ret i32 %Z
}

define i64 @Y() {
; CHECK-LABEL: define i64 @Y() {
; CHECK-NEXT:    ret i64 72057594037927936
;
  %Z = call i64 @llvm.bswap.i64( i64 1 )          ; <i64> [#uses=1]
  ret i64 %Z
}

define i80 @Z() {
; CHECK-LABEL: define i80 @Z() {
; CHECK-NEXT:    ret i80 -450681596205739728166896
;
  %Z = call i80 @llvm.bswap.i80( i80 76151636403560493650080 )
  ret i80 %Z
}

define <4 x i32> @bswap_splat_v4i32() {
; CHECK-LABEL: define <4 x i32> @bswap_splat_v4i32() {
; CHECK-NEXT:    ret <4 x i32> splat (i32 16777216)
;
  %Z = call <4 x i32> @llvm.bswap.v4i32(<4 x i32> splat(i32 1))
  ret <4 x i32> %Z
}

define <vscale x 4 x i32> @bswap_splat_nxv4i32() {
; CHECK-LABEL: define <vscale x 4 x i32> @bswap_splat_nxv4i32() {
; CHECK-NEXT:    ret <vscale x 4 x i32> splat (i32 16777216)
;
  %Z = call <vscale x 4 x i32> @llvm.bswap.v4i32(<vscale x 4 x i32> splat(i32 1))
  ret <vscale x 4 x i32> %Z
}
