; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s | FileCheck %s

; Test custom lowering for 32-bit integer multiplication.

target datalayout = "E-m:e-p:32:32-i64:64-a:0:32-n32-S64"
target triple = "lanai"

define i32 @f6(i32 inreg %a) #0 {
; CHECK-LABEL: f6:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x3, %r3
; CHECK-NEXT:    sub %r3, %r6, %r3
; CHECK-NEXT:    sub %r3, %r6, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul nsw i32 %a, 6
  ret i32 %1
}

define i32 @f7(i32 inreg %a) #0 {
; CHECK-LABEL: f7:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x3, %r3
; CHECK-NEXT:    sub %r3, %r6, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul nsw i32 %a, 7
  ret i32 %1
}

define i32 @f8(i32 inreg %a) #0 {
; CHECK-LABEL: f8:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x3, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = shl nsw i32 %a, 3
  ret i32 %1
}

define i32 @f9(i32 inreg %a) #0 {
; CHECK-LABEL: f9:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x3, %r3
; CHECK-NEXT:    add %r3, %r6, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul nsw i32 %a, 9
  ret i32 %1
}

define i32 @f10(i32 inreg %a) #0 {
; CHECK-LABEL: f10:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x2, %r3
; CHECK-NEXT:    add %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x1, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul nsw i32 %a, 10
  ret i32 %1
}

define i32 @f1280(i32 inreg %a) #0 {
; CHECK-LABEL: f1280:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x2, %r3
; CHECK-NEXT:    add %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x8, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul nsw i32 %a, 1280
  ret i32 %1
}

define i32 @fm6(i32 inreg %a) #0 {
; CHECK-LABEL: fm6:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x2, %r3
; CHECK-NEXT:    sub %r6, %r3, %r3
; CHECK-NEXT:    sh %r3, 0x1, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul nsw i32 %a, -6
  ret i32 %1
}

define i32 @fm7(i32 inreg %a) #0 {
; CHECK-LABEL: fm7:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x3, %r3
; CHECK-NEXT:    sub %r6, %r3, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul nsw i32 %a, -7
  ret i32 %1
}

define i32 @fm8(i32 inreg %a) #0 {
; CHECK-LABEL: fm8:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x3, %r3
; CHECK-NEXT:    sub %r0, %r3, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul nsw i32 %a, -8
  ret i32 %1
}

define i32 @fm9(i32 inreg %a) #0 {
; CHECK-LABEL: fm9:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sub %r0, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x3, %r3
; CHECK-NEXT:    sub %r3, %r6, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul nsw i32 %a, -9
  ret i32 %1
}

define i32 @fm10(i32 inreg %a) #0 {
; CHECK-LABEL: fm10:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sub %r0, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x3, %r3
; CHECK-NEXT:    sub %r3, %r6, %r3
; CHECK-NEXT:    sub %r3, %r6, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul nsw i32 %a, -10
  ret i32 %1
}

define i32 @h1(i32 inreg %a) #0 {
; CHECK-LABEL: h1:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sub %r0, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x10, %r3
; CHECK-NEXT:    sub %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x8, %r9
; CHECK-NEXT:    add %r9, %r3, %r3
; CHECK-NEXT:    sh %r3, 0x4, %r9
; CHECK-NEXT:    add %r9, %r3, %r3
; CHECK-NEXT:    sh %r3, 0x2, %r9
; CHECK-NEXT:    add %r9, %r3, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, -1431655765
  ret i32 %1
}

define i32 @muli32_p10(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p10:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x2, %r3
; CHECK-NEXT:    add %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x1, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 10
  ret i32 %1
}

define i32 @muli32_p14(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p14:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x4, %r3
; CHECK-NEXT:    sub %r3, %r6, %r3
; CHECK-NEXT:    sub %r3, %r6, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 14
  ret i32 %1
}

define i32 @muli32_p18(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p18:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x3, %r3
; CHECK-NEXT:    add %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x1, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 18
  ret i32 %1
}

define i32 @muli32_p28(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p28:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x3, %r3
; CHECK-NEXT:    sub %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x2, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 28
  ret i32 %1
}

define i32 @muli32_p30(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p30:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x5, %r3
; CHECK-NEXT:    sub %r3, %r6, %r3
; CHECK-NEXT:    sub %r3, %r6, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 30
  ret i32 %1
}

define i32 @muli32_p34(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p34:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x4, %r3
; CHECK-NEXT:    add %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x1, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 34
  ret i32 %1
}

define i32 @muli32_p36(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p36:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x3, %r3
; CHECK-NEXT:    add %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x2, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 36
  ret i32 %1
}

define i32 @muli32_p56(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p56:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x3, %r3
; CHECK-NEXT:    sub %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x3, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 56
  ret i32 %1
}

define i32 @muli32_p60(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p60:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x4, %r3
; CHECK-NEXT:    sub %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x2, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 60
  ret i32 %1
}

define i32 @muli32_p62(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p62:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x6, %r3
; CHECK-NEXT:    sub %r3, %r6, %r3
; CHECK-NEXT:    sub %r3, %r6, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 62
  ret i32 %1
}

define i32 @muli32_p63(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p63:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x6, %r3
; CHECK-NEXT:    sub %r3, %r6, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 63
  ret i32 %1
}

define i32 @muli32_p65(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p65:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x6, %r3
; CHECK-NEXT:    add %r3, %r6, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 65
  ret i32 %1
}

define i32 @muli32_p66(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p66:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x5, %r3
; CHECK-NEXT:    add %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x1, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 66
  ret i32 %1
}

define i32 @muli32_m63(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_m63:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x6, %r3
; CHECK-NEXT:    sub %r6, %r3, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, -63
  ret i32 %1
}

define i32 @muli32_m65(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_m65:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sub %r0, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x6, %r3
; CHECK-NEXT:    sub %r3, %r6, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, -65
  ret i32 %1
}

define i32 @muli32_p384(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p384:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x1, %r3
; CHECK-NEXT:    add %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x7, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 384
  ret i32 %1
}

define i32 @muli32_p12288(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p12288:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x1, %r3
; CHECK-NEXT:    add %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0xc, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 12288
  ret i32 %1
}

define i32 @muli32_p4352(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p4352:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x4, %r3
; CHECK-NEXT:    add %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x8, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 4352
  ret i32 %1
}

define i32 @muli32_p3840(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_p3840:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x4, %r3
; CHECK-NEXT:    sub %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x8, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, 3840
  ret i32 %1
}

define i32 @muli32_m3840(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_m3840:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sh %r6, 0x4, %r3
; CHECK-NEXT:    sub %r6, %r3, %r3
; CHECK-NEXT:    sh %r3, 0x8, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, -3840
  ret i32 %1
}

define i32 @muli32_m4352(i32 inreg %a) #0 {
; CHECK-LABEL: muli32_m4352:
; CHECK:       ! %bb.0:
; CHECK-NEXT:    st %fp, [--%sp]
; CHECK-NEXT:    add %sp, 0x8, %fp
; CHECK-NEXT:    sub %sp, 0x8, %sp
; CHECK-NEXT:    sub %r0, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x4, %r3
; CHECK-NEXT:    sub %r3, %r6, %r3
; CHECK-NEXT:    sh %r3, 0x8, %rv
; CHECK-NEXT:    ld -4[%fp], %pc ! return
; CHECK-NEXT:    add %fp, 0x0, %sp
; CHECK-NEXT:    ld -8[%fp], %fp
  %1 = mul i32 %a, -4352
  ret i32 %1
}
