; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; Test we ignore functions that contains icmp between allocas.
; Moving lifetime markers leads to observable effect, which violate C/C++ standard. Seems we cannot model the semantic from IR level.
; RUN: opt < %s -passes=lifetime-move -S | FileCheck %s

define i1 @fn() presplitcoroutine {
; CHECK-LABEL: define i1 @fn(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A:%.*]] = alloca [1000 x i8], align 1
; CHECK-NEXT:    [[B:%.*]] = alloca [1000 x i8], align 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 1000, ptr [[A]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 1000, ptr [[B]])
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[B]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 1000, ptr [[B]])
; CHECK-NEXT:    [[UNUSED:%.*]] = call i8 @llvm.coro.suspend(token none, i1 false)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 1000, ptr [[A]])
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[A]], [[B]]
; CHECK-NEXT:    ret i1 [[TMP0]]
;
entry:
  %a = alloca [1000 x i8]
  %b = alloca [1000 x i8]
  call void @llvm.lifetime.start.p0(i64 1000, ptr %a)
  call void @llvm.lifetime.start.p0(i64 1000, ptr %b)
  %0 = load i8, ptr %b, align 8
  call void @llvm.lifetime.end.p0(i64 1000, ptr %b)
  %unused = call i8 @llvm.coro.suspend(token none, i1 false)
  call void @llvm.lifetime.end.p0(i64 1000, ptr %a)
  %cmp = icmp eq ptr %a, %b
  ret i1 %cmp
}
