; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -mtriple=x86_64-- --expand-ir-insts < %s | FileCheck %s
; RUN: opt -S -mtriple=x86_64-- -passes='require<libcall-lowering-info>,expand-ir-insts' < %s | FileCheck %s

declare <2 x i256> @llvm.fptoui.sat.v2i256.v2f32(<2 x float>)
declare <2 x i256> @llvm.fptosi.sat.v2i256.v2f32(<2 x float>)
declare <4 x i256> @llvm.fptoui.sat.v4i256.v4f64(<4 x double>)

define <2 x i256> @fptoui_sat_v2i256(<2 x float> %x) {
; CHECK-LABEL: @fptoui_sat_v2i256(
; CHECK-NEXT:  fp-to-i-entryfp-to-i-entry:
; CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x float> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = freeze float [[TMP0]]
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast float [[TMP1]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = lshr i32 [[TMP2]], 23
; CHECK-NEXT:    [[BIASED_EXP7:%.*]] = and i32 [[TMP3]], 255
; CHECK-NEXT:    [[TMP4:%.*]] = and i32 [[TMP2]], 8388607
; CHECK-NEXT:    [[SIGNIFICAND8:%.*]] = or i32 [[TMP4]], 8388608
; CHECK-NEXT:    [[EXP_IS_NEGATIVE9:%.*]] = icmp ult i32 [[BIASED_EXP7]], 127
; CHECK-NEXT:    [[IS_NAN10:%.*]] = fcmp uno float [[TMP1]], [[TMP1]]
; CHECK-NEXT:    [[TMP5:%.*]] = or i1 [[EXP_IS_NEGATIVE9]], [[IS_NAN10]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp slt i32 [[TMP2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = or i1 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[FP_TO_I_CLEANUP1:%.*]], label [[FP_TO_I_IF_CHECK_SATURATE2:%.*]]
; CHECK:       fp-to-i-if-check.saturate2:
; CHECK-NEXT:    [[TMP8:%.*]] = icmp uge i32 [[BIASED_EXP7]], 383
; CHECK-NEXT:    br i1 [[TMP8]], label [[FP_TO_I_IF_SATURATE3:%.*]], label [[FP_TO_I_IF_CHECK_EXP_SIZE4:%.*]]
; CHECK:       fp-to-i-if-saturate3:
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP1]]
; CHECK:       fp-to-i-if-check.exp.size4:
; CHECK-NEXT:    [[EXP_SMALLER_MANTISSA_WIDTH11:%.*]] = icmp ult i32 [[BIASED_EXP7]], 150
; CHECK-NEXT:    br i1 [[EXP_SMALLER_MANTISSA_WIDTH11]], label [[FP_TO_I_IF_EXP_SMALL5:%.*]], label [[FP_TO_I_IF_EXP_LARGE6:%.*]]
; CHECK:       fp-to-i-if-exp.small5:
; CHECK-NEXT:    [[TMP9:%.*]] = sub i32 150, [[BIASED_EXP7]]
; CHECK-NEXT:    [[TMP10:%.*]] = lshr i32 [[SIGNIFICAND8]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = zext i32 [[TMP10]] to i256
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP1]]
; CHECK:       fp-to-i-if-exp.large6:
; CHECK-NEXT:    [[TMP12:%.*]] = add i32 [[BIASED_EXP7]], -150
; CHECK-NEXT:    [[TMP13:%.*]] = zext i32 [[SIGNIFICAND8]] to i256
; CHECK-NEXT:    [[TMP14:%.*]] = zext i32 [[TMP12]] to i256
; CHECK-NEXT:    [[TMP15:%.*]] = shl i256 [[TMP13]], [[TMP14]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP1]]
; CHECK:       fp-to-i-cleanup1:
; CHECK-NEXT:    [[TMP16:%.*]] = phi i256 [ -1, [[FP_TO_I_IF_SATURATE3]] ], [ [[TMP11]], [[FP_TO_I_IF_EXP_SMALL5]] ], [ [[TMP15]], [[FP_TO_I_IF_EXP_LARGE6]] ], [ 0, [[FP_TO_I_ENTRYFP_TO_I_ENTRY:%.*]] ]
; CHECK-NEXT:    [[TMP17:%.*]] = insertelement <2 x i256> poison, i256 [[TMP16]], i64 0
; CHECK-NEXT:    [[TMP18:%.*]] = extractelement <2 x float> [[X]], i64 1
; CHECK-NEXT:    [[TMP19:%.*]] = freeze float [[TMP18]]
; CHECK-NEXT:    [[TMP20:%.*]] = bitcast float [[TMP19]] to i32
; CHECK-NEXT:    [[TMP21:%.*]] = lshr i32 [[TMP20]], 23
; CHECK-NEXT:    [[BIASED_EXP:%.*]] = and i32 [[TMP21]], 255
; CHECK-NEXT:    [[TMP22:%.*]] = and i32 [[TMP20]], 8388607
; CHECK-NEXT:    [[SIGNIFICAND:%.*]] = or i32 [[TMP22]], 8388608
; CHECK-NEXT:    [[EXP_IS_NEGATIVE:%.*]] = icmp ult i32 [[BIASED_EXP]], 127
; CHECK-NEXT:    [[IS_NAN:%.*]] = fcmp uno float [[TMP19]], [[TMP19]]
; CHECK-NEXT:    [[TMP23:%.*]] = or i1 [[EXP_IS_NEGATIVE]], [[IS_NAN]]
; CHECK-NEXT:    [[TMP24:%.*]] = icmp slt i32 [[TMP20]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = or i1 [[TMP23]], [[TMP24]]
; CHECK-NEXT:    br i1 [[TMP25]], label [[FP_TO_I_CLEANUP:%.*]], label [[FP_TO_I_IF_CHECK_SATURATE:%.*]]
; CHECK:       fp-to-i-if-check.saturate:
; CHECK-NEXT:    [[TMP26:%.*]] = icmp uge i32 [[BIASED_EXP]], 383
; CHECK-NEXT:    br i1 [[TMP26]], label [[FP_TO_I_IF_SATURATE:%.*]], label [[FP_TO_I_IF_CHECK_EXP_SIZE:%.*]]
; CHECK:       fp-to-i-if-saturate:
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-check.exp.size:
; CHECK-NEXT:    [[EXP_SMALLER_MANTISSA_WIDTH:%.*]] = icmp ult i32 [[BIASED_EXP]], 150
; CHECK-NEXT:    br i1 [[EXP_SMALLER_MANTISSA_WIDTH]], label [[FP_TO_I_IF_EXP_SMALL:%.*]], label [[FP_TO_I_IF_EXP_LARGE:%.*]]
; CHECK:       fp-to-i-if-exp.small:
; CHECK-NEXT:    [[TMP27:%.*]] = sub i32 150, [[BIASED_EXP]]
; CHECK-NEXT:    [[TMP28:%.*]] = lshr i32 [[SIGNIFICAND]], [[TMP27]]
; CHECK-NEXT:    [[TMP29:%.*]] = zext i32 [[TMP28]] to i256
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-exp.large:
; CHECK-NEXT:    [[TMP30:%.*]] = add i32 [[BIASED_EXP]], -150
; CHECK-NEXT:    [[TMP31:%.*]] = zext i32 [[SIGNIFICAND]] to i256
; CHECK-NEXT:    [[TMP32:%.*]] = zext i32 [[TMP30]] to i256
; CHECK-NEXT:    [[TMP33:%.*]] = shl i256 [[TMP31]], [[TMP32]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-cleanup:
; CHECK-NEXT:    [[TMP34:%.*]] = phi i256 [ -1, [[FP_TO_I_IF_SATURATE]] ], [ [[TMP29]], [[FP_TO_I_IF_EXP_SMALL]] ], [ [[TMP33]], [[FP_TO_I_IF_EXP_LARGE]] ], [ 0, [[FP_TO_I_CLEANUP1]] ]
; CHECK-NEXT:    [[TMP35:%.*]] = insertelement <2 x i256> [[TMP17]], i256 [[TMP34]], i64 1
; CHECK-NEXT:    ret <2 x i256> [[TMP35]]
;
  %r = call <2 x i256> @llvm.fptoui.sat.v2i256.v2f32(<2 x float> %x)
  ret <2 x i256> %r
}

define <2 x i256> @fptosi_sat_v2i256(<2 x float> %x) {
; CHECK-LABEL: @fptosi_sat_v2i256(
; CHECK-NEXT:  fp-to-i-entryfp-to-i-entry:
; CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x float> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = freeze float [[TMP0]]
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast float [[TMP1]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = icmp sgt i32 [[TMP2]], -1
; CHECK-NEXT:    [[SIGN7:%.*]] = select i1 [[TMP3]], i256 1, i256 -1
; CHECK-NEXT:    [[TMP4:%.*]] = lshr i32 [[TMP2]], 23
; CHECK-NEXT:    [[BIASED_EXP8:%.*]] = and i32 [[TMP4]], 255
; CHECK-NEXT:    [[TMP5:%.*]] = and i32 [[TMP2]], 8388607
; CHECK-NEXT:    [[SIGNIFICAND9:%.*]] = or i32 [[TMP5]], 8388608
; CHECK-NEXT:    [[EXP_IS_NEGATIVE10:%.*]] = icmp ult i32 [[BIASED_EXP8]], 127
; CHECK-NEXT:    [[IS_NAN11:%.*]] = fcmp uno float [[TMP1]], [[TMP1]]
; CHECK-NEXT:    [[TMP6:%.*]] = or i1 [[EXP_IS_NEGATIVE10]], [[IS_NAN11]]
; CHECK-NEXT:    br i1 [[TMP6]], label [[FP_TO_I_CLEANUP1:%.*]], label [[FP_TO_I_IF_CHECK_SATURATE2:%.*]]
; CHECK:       fp-to-i-if-check.saturate2:
; CHECK-NEXT:    [[TMP7:%.*]] = icmp uge i32 [[BIASED_EXP8]], 382
; CHECK-NEXT:    br i1 [[TMP7]], label [[FP_TO_I_IF_SATURATE3:%.*]], label [[FP_TO_I_IF_CHECK_EXP_SIZE4:%.*]]
; CHECK:       fp-to-i-if-saturate3:
; CHECK-NEXT:    [[SATURATED12:%.*]] = select i1 [[TMP3]], i256 57896044618658097711785492504343953926634992332820282019728792003956564819967, i256 -57896044618658097711785492504343953926634992332820282019728792003956564819968
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP1]]
; CHECK:       fp-to-i-if-check.exp.size4:
; CHECK-NEXT:    [[EXP_SMALLER_MANTISSA_WIDTH13:%.*]] = icmp ult i32 [[BIASED_EXP8]], 150
; CHECK-NEXT:    br i1 [[EXP_SMALLER_MANTISSA_WIDTH13]], label [[FP_TO_I_IF_EXP_SMALL5:%.*]], label [[FP_TO_I_IF_EXP_LARGE6:%.*]]
; CHECK:       fp-to-i-if-exp.small5:
; CHECK-NEXT:    [[TMP8:%.*]] = sub i32 150, [[BIASED_EXP8]]
; CHECK-NEXT:    [[TMP9:%.*]] = lshr i32 [[SIGNIFICAND9]], [[TMP8]]
; CHECK-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP9]] to i256
; CHECK-NEXT:    [[TMP11:%.*]] = mul i256 [[TMP10]], [[SIGN7]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP1]]
; CHECK:       fp-to-i-if-exp.large6:
; CHECK-NEXT:    [[TMP12:%.*]] = add i32 [[BIASED_EXP8]], -150
; CHECK-NEXT:    [[TMP13:%.*]] = zext i32 [[SIGNIFICAND9]] to i256
; CHECK-NEXT:    [[TMP14:%.*]] = zext i32 [[TMP12]] to i256
; CHECK-NEXT:    [[TMP15:%.*]] = shl i256 [[TMP13]], [[TMP14]]
; CHECK-NEXT:    [[TMP16:%.*]] = mul i256 [[TMP15]], [[SIGN7]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP1]]
; CHECK:       fp-to-i-cleanup1:
; CHECK-NEXT:    [[TMP17:%.*]] = phi i256 [ [[SATURATED12]], [[FP_TO_I_IF_SATURATE3]] ], [ [[TMP11]], [[FP_TO_I_IF_EXP_SMALL5]] ], [ [[TMP16]], [[FP_TO_I_IF_EXP_LARGE6]] ], [ 0, [[FP_TO_I_ENTRYFP_TO_I_ENTRY:%.*]] ]
; CHECK-NEXT:    [[TMP18:%.*]] = insertelement <2 x i256> poison, i256 [[TMP17]], i64 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractelement <2 x float> [[X]], i64 1
; CHECK-NEXT:    [[TMP20:%.*]] = freeze float [[TMP19]]
; CHECK-NEXT:    [[TMP21:%.*]] = bitcast float [[TMP20]] to i32
; CHECK-NEXT:    [[TMP22:%.*]] = icmp sgt i32 [[TMP21]], -1
; CHECK-NEXT:    [[SIGN:%.*]] = select i1 [[TMP22]], i256 1, i256 -1
; CHECK-NEXT:    [[TMP23:%.*]] = lshr i32 [[TMP21]], 23
; CHECK-NEXT:    [[BIASED_EXP:%.*]] = and i32 [[TMP23]], 255
; CHECK-NEXT:    [[TMP24:%.*]] = and i32 [[TMP21]], 8388607
; CHECK-NEXT:    [[SIGNIFICAND:%.*]] = or i32 [[TMP24]], 8388608
; CHECK-NEXT:    [[EXP_IS_NEGATIVE:%.*]] = icmp ult i32 [[BIASED_EXP]], 127
; CHECK-NEXT:    [[IS_NAN:%.*]] = fcmp uno float [[TMP20]], [[TMP20]]
; CHECK-NEXT:    [[TMP25:%.*]] = or i1 [[EXP_IS_NEGATIVE]], [[IS_NAN]]
; CHECK-NEXT:    br i1 [[TMP25]], label [[FP_TO_I_CLEANUP:%.*]], label [[FP_TO_I_IF_CHECK_SATURATE:%.*]]
; CHECK:       fp-to-i-if-check.saturate:
; CHECK-NEXT:    [[TMP26:%.*]] = icmp uge i32 [[BIASED_EXP]], 382
; CHECK-NEXT:    br i1 [[TMP26]], label [[FP_TO_I_IF_SATURATE:%.*]], label [[FP_TO_I_IF_CHECK_EXP_SIZE:%.*]]
; CHECK:       fp-to-i-if-saturate:
; CHECK-NEXT:    [[SATURATED:%.*]] = select i1 [[TMP22]], i256 57896044618658097711785492504343953926634992332820282019728792003956564819967, i256 -57896044618658097711785492504343953926634992332820282019728792003956564819968
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-check.exp.size:
; CHECK-NEXT:    [[EXP_SMALLER_MANTISSA_WIDTH:%.*]] = icmp ult i32 [[BIASED_EXP]], 150
; CHECK-NEXT:    br i1 [[EXP_SMALLER_MANTISSA_WIDTH]], label [[FP_TO_I_IF_EXP_SMALL:%.*]], label [[FP_TO_I_IF_EXP_LARGE:%.*]]
; CHECK:       fp-to-i-if-exp.small:
; CHECK-NEXT:    [[TMP27:%.*]] = sub i32 150, [[BIASED_EXP]]
; CHECK-NEXT:    [[TMP28:%.*]] = lshr i32 [[SIGNIFICAND]], [[TMP27]]
; CHECK-NEXT:    [[TMP29:%.*]] = zext i32 [[TMP28]] to i256
; CHECK-NEXT:    [[TMP30:%.*]] = mul i256 [[TMP29]], [[SIGN]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-exp.large:
; CHECK-NEXT:    [[TMP31:%.*]] = add i32 [[BIASED_EXP]], -150
; CHECK-NEXT:    [[TMP32:%.*]] = zext i32 [[SIGNIFICAND]] to i256
; CHECK-NEXT:    [[TMP33:%.*]] = zext i32 [[TMP31]] to i256
; CHECK-NEXT:    [[TMP34:%.*]] = shl i256 [[TMP32]], [[TMP33]]
; CHECK-NEXT:    [[TMP35:%.*]] = mul i256 [[TMP34]], [[SIGN]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-cleanup:
; CHECK-NEXT:    [[TMP36:%.*]] = phi i256 [ [[SATURATED]], [[FP_TO_I_IF_SATURATE]] ], [ [[TMP30]], [[FP_TO_I_IF_EXP_SMALL]] ], [ [[TMP35]], [[FP_TO_I_IF_EXP_LARGE]] ], [ 0, [[FP_TO_I_CLEANUP1]] ]
; CHECK-NEXT:    [[TMP37:%.*]] = insertelement <2 x i256> [[TMP18]], i256 [[TMP36]], i64 1
; CHECK-NEXT:    ret <2 x i256> [[TMP37]]
;
  %r = call <2 x i256> @llvm.fptosi.sat.v2i256.v2f32(<2 x float> %x)
  ret <2 x i256> %r
}

define <4 x i256> @fptoui_sat_v4i256(<4 x double> %x) {
; CHECK-LABEL: @fptoui_sat_v4i256(
; CHECK-NEXT:  fp-to-i-entryfp-to-i-entryfp-to-i-entryfp-to-i-entry:
; CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x double> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = freeze double [[TMP0]]
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast double [[TMP1]] to i64
; CHECK-NEXT:    [[TMP3:%.*]] = lshr i64 [[TMP2]], 52
; CHECK-NEXT:    [[BIASED_EXP29:%.*]] = and i64 [[TMP3]], 2047
; CHECK-NEXT:    [[TMP4:%.*]] = and i64 [[TMP2]], 4503599627370495
; CHECK-NEXT:    [[SIGNIFICAND30:%.*]] = or i64 [[TMP4]], 4503599627370496
; CHECK-NEXT:    [[EXP_IS_NEGATIVE31:%.*]] = icmp ult i64 [[BIASED_EXP29]], 1023
; CHECK-NEXT:    [[IS_NAN32:%.*]] = fcmp uno double [[TMP1]], [[TMP1]]
; CHECK-NEXT:    [[TMP5:%.*]] = or i1 [[EXP_IS_NEGATIVE31]], [[IS_NAN32]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp slt i64 [[TMP2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = or i1 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[FP_TO_I_CLEANUP23:%.*]], label [[FP_TO_I_IF_CHECK_SATURATE24:%.*]]
; CHECK:       fp-to-i-if-check.saturate24:
; CHECK-NEXT:    [[TMP8:%.*]] = icmp uge i64 [[BIASED_EXP29]], 1279
; CHECK-NEXT:    br i1 [[TMP8]], label [[FP_TO_I_IF_SATURATE25:%.*]], label [[FP_TO_I_IF_CHECK_EXP_SIZE26:%.*]]
; CHECK:       fp-to-i-if-saturate25:
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP23]]
; CHECK:       fp-to-i-if-check.exp.size26:
; CHECK-NEXT:    [[EXP_SMALLER_MANTISSA_WIDTH33:%.*]] = icmp ult i64 [[BIASED_EXP29]], 1075
; CHECK-NEXT:    br i1 [[EXP_SMALLER_MANTISSA_WIDTH33]], label [[FP_TO_I_IF_EXP_SMALL27:%.*]], label [[FP_TO_I_IF_EXP_LARGE28:%.*]]
; CHECK:       fp-to-i-if-exp.small27:
; CHECK-NEXT:    [[TMP9:%.*]] = sub i64 1075, [[BIASED_EXP29]]
; CHECK-NEXT:    [[TMP10:%.*]] = lshr i64 [[SIGNIFICAND30]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = zext i64 [[TMP10]] to i256
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP23]]
; CHECK:       fp-to-i-if-exp.large28:
; CHECK-NEXT:    [[TMP12:%.*]] = add i64 [[BIASED_EXP29]], -1075
; CHECK-NEXT:    [[TMP13:%.*]] = zext i64 [[SIGNIFICAND30]] to i256
; CHECK-NEXT:    [[TMP14:%.*]] = zext i64 [[TMP12]] to i256
; CHECK-NEXT:    [[TMP15:%.*]] = shl i256 [[TMP13]], [[TMP14]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP23]]
; CHECK:       fp-to-i-cleanup23:
; CHECK-NEXT:    [[TMP16:%.*]] = phi i256 [ -1, [[FP_TO_I_IF_SATURATE25]] ], [ [[TMP11]], [[FP_TO_I_IF_EXP_SMALL27]] ], [ [[TMP15]], [[FP_TO_I_IF_EXP_LARGE28]] ], [ 0, [[FP_TO_I_ENTRYFP_TO_I_ENTRYFP_TO_I_ENTRYFP_TO_I_ENTRY:%.*]] ]
; CHECK-NEXT:    [[TMP17:%.*]] = insertelement <4 x i256> poison, i256 [[TMP16]], i64 0
; CHECK-NEXT:    [[TMP18:%.*]] = extractelement <4 x double> [[X]], i64 1
; CHECK-NEXT:    [[TMP19:%.*]] = freeze double [[TMP18]]
; CHECK-NEXT:    [[TMP20:%.*]] = bitcast double [[TMP19]] to i64
; CHECK-NEXT:    [[TMP21:%.*]] = lshr i64 [[TMP20]], 52
; CHECK-NEXT:    [[BIASED_EXP18:%.*]] = and i64 [[TMP21]], 2047
; CHECK-NEXT:    [[TMP22:%.*]] = and i64 [[TMP20]], 4503599627370495
; CHECK-NEXT:    [[SIGNIFICAND19:%.*]] = or i64 [[TMP22]], 4503599627370496
; CHECK-NEXT:    [[EXP_IS_NEGATIVE20:%.*]] = icmp ult i64 [[BIASED_EXP18]], 1023
; CHECK-NEXT:    [[IS_NAN21:%.*]] = fcmp uno double [[TMP19]], [[TMP19]]
; CHECK-NEXT:    [[TMP23:%.*]] = or i1 [[EXP_IS_NEGATIVE20]], [[IS_NAN21]]
; CHECK-NEXT:    [[TMP24:%.*]] = icmp slt i64 [[TMP20]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = or i1 [[TMP23]], [[TMP24]]
; CHECK-NEXT:    br i1 [[TMP25]], label [[FP_TO_I_CLEANUP12:%.*]], label [[FP_TO_I_IF_CHECK_SATURATE13:%.*]]
; CHECK:       fp-to-i-if-check.saturate13:
; CHECK-NEXT:    [[TMP26:%.*]] = icmp uge i64 [[BIASED_EXP18]], 1279
; CHECK-NEXT:    br i1 [[TMP26]], label [[FP_TO_I_IF_SATURATE14:%.*]], label [[FP_TO_I_IF_CHECK_EXP_SIZE15:%.*]]
; CHECK:       fp-to-i-if-saturate14:
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP12]]
; CHECK:       fp-to-i-if-check.exp.size15:
; CHECK-NEXT:    [[EXP_SMALLER_MANTISSA_WIDTH22:%.*]] = icmp ult i64 [[BIASED_EXP18]], 1075
; CHECK-NEXT:    br i1 [[EXP_SMALLER_MANTISSA_WIDTH22]], label [[FP_TO_I_IF_EXP_SMALL16:%.*]], label [[FP_TO_I_IF_EXP_LARGE17:%.*]]
; CHECK:       fp-to-i-if-exp.small16:
; CHECK-NEXT:    [[TMP27:%.*]] = sub i64 1075, [[BIASED_EXP18]]
; CHECK-NEXT:    [[TMP28:%.*]] = lshr i64 [[SIGNIFICAND19]], [[TMP27]]
; CHECK-NEXT:    [[TMP29:%.*]] = zext i64 [[TMP28]] to i256
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP12]]
; CHECK:       fp-to-i-if-exp.large17:
; CHECK-NEXT:    [[TMP30:%.*]] = add i64 [[BIASED_EXP18]], -1075
; CHECK-NEXT:    [[TMP31:%.*]] = zext i64 [[SIGNIFICAND19]] to i256
; CHECK-NEXT:    [[TMP32:%.*]] = zext i64 [[TMP30]] to i256
; CHECK-NEXT:    [[TMP33:%.*]] = shl i256 [[TMP31]], [[TMP32]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP12]]
; CHECK:       fp-to-i-cleanup12:
; CHECK-NEXT:    [[TMP34:%.*]] = phi i256 [ -1, [[FP_TO_I_IF_SATURATE14]] ], [ [[TMP29]], [[FP_TO_I_IF_EXP_SMALL16]] ], [ [[TMP33]], [[FP_TO_I_IF_EXP_LARGE17]] ], [ 0, [[FP_TO_I_CLEANUP23]] ]
; CHECK-NEXT:    [[TMP35:%.*]] = insertelement <4 x i256> [[TMP17]], i256 [[TMP34]], i64 1
; CHECK-NEXT:    [[TMP36:%.*]] = extractelement <4 x double> [[X]], i64 2
; CHECK-NEXT:    [[TMP37:%.*]] = freeze double [[TMP36]]
; CHECK-NEXT:    [[TMP38:%.*]] = bitcast double [[TMP37]] to i64
; CHECK-NEXT:    [[TMP39:%.*]] = lshr i64 [[TMP38]], 52
; CHECK-NEXT:    [[BIASED_EXP7:%.*]] = and i64 [[TMP39]], 2047
; CHECK-NEXT:    [[TMP40:%.*]] = and i64 [[TMP38]], 4503599627370495
; CHECK-NEXT:    [[SIGNIFICAND8:%.*]] = or i64 [[TMP40]], 4503599627370496
; CHECK-NEXT:    [[EXP_IS_NEGATIVE9:%.*]] = icmp ult i64 [[BIASED_EXP7]], 1023
; CHECK-NEXT:    [[IS_NAN10:%.*]] = fcmp uno double [[TMP37]], [[TMP37]]
; CHECK-NEXT:    [[TMP41:%.*]] = or i1 [[EXP_IS_NEGATIVE9]], [[IS_NAN10]]
; CHECK-NEXT:    [[TMP42:%.*]] = icmp slt i64 [[TMP38]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = or i1 [[TMP41]], [[TMP42]]
; CHECK-NEXT:    br i1 [[TMP43]], label [[FP_TO_I_CLEANUP1:%.*]], label [[FP_TO_I_IF_CHECK_SATURATE2:%.*]]
; CHECK:       fp-to-i-if-check.saturate2:
; CHECK-NEXT:    [[TMP44:%.*]] = icmp uge i64 [[BIASED_EXP7]], 1279
; CHECK-NEXT:    br i1 [[TMP44]], label [[FP_TO_I_IF_SATURATE3:%.*]], label [[FP_TO_I_IF_CHECK_EXP_SIZE4:%.*]]
; CHECK:       fp-to-i-if-saturate3:
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP1]]
; CHECK:       fp-to-i-if-check.exp.size4:
; CHECK-NEXT:    [[EXP_SMALLER_MANTISSA_WIDTH11:%.*]] = icmp ult i64 [[BIASED_EXP7]], 1075
; CHECK-NEXT:    br i1 [[EXP_SMALLER_MANTISSA_WIDTH11]], label [[FP_TO_I_IF_EXP_SMALL5:%.*]], label [[FP_TO_I_IF_EXP_LARGE6:%.*]]
; CHECK:       fp-to-i-if-exp.small5:
; CHECK-NEXT:    [[TMP45:%.*]] = sub i64 1075, [[BIASED_EXP7]]
; CHECK-NEXT:    [[TMP46:%.*]] = lshr i64 [[SIGNIFICAND8]], [[TMP45]]
; CHECK-NEXT:    [[TMP47:%.*]] = zext i64 [[TMP46]] to i256
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP1]]
; CHECK:       fp-to-i-if-exp.large6:
; CHECK-NEXT:    [[TMP48:%.*]] = add i64 [[BIASED_EXP7]], -1075
; CHECK-NEXT:    [[TMP49:%.*]] = zext i64 [[SIGNIFICAND8]] to i256
; CHECK-NEXT:    [[TMP50:%.*]] = zext i64 [[TMP48]] to i256
; CHECK-NEXT:    [[TMP51:%.*]] = shl i256 [[TMP49]], [[TMP50]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP1]]
; CHECK:       fp-to-i-cleanup1:
; CHECK-NEXT:    [[TMP52:%.*]] = phi i256 [ -1, [[FP_TO_I_IF_SATURATE3]] ], [ [[TMP47]], [[FP_TO_I_IF_EXP_SMALL5]] ], [ [[TMP51]], [[FP_TO_I_IF_EXP_LARGE6]] ], [ 0, [[FP_TO_I_CLEANUP12]] ]
; CHECK-NEXT:    [[TMP53:%.*]] = insertelement <4 x i256> [[TMP35]], i256 [[TMP52]], i64 2
; CHECK-NEXT:    [[TMP54:%.*]] = extractelement <4 x double> [[X]], i64 3
; CHECK-NEXT:    [[TMP55:%.*]] = freeze double [[TMP54]]
; CHECK-NEXT:    [[TMP56:%.*]] = bitcast double [[TMP55]] to i64
; CHECK-NEXT:    [[TMP57:%.*]] = lshr i64 [[TMP56]], 52
; CHECK-NEXT:    [[BIASED_EXP:%.*]] = and i64 [[TMP57]], 2047
; CHECK-NEXT:    [[TMP58:%.*]] = and i64 [[TMP56]], 4503599627370495
; CHECK-NEXT:    [[SIGNIFICAND:%.*]] = or i64 [[TMP58]], 4503599627370496
; CHECK-NEXT:    [[EXP_IS_NEGATIVE:%.*]] = icmp ult i64 [[BIASED_EXP]], 1023
; CHECK-NEXT:    [[IS_NAN:%.*]] = fcmp uno double [[TMP55]], [[TMP55]]
; CHECK-NEXT:    [[TMP59:%.*]] = or i1 [[EXP_IS_NEGATIVE]], [[IS_NAN]]
; CHECK-NEXT:    [[TMP60:%.*]] = icmp slt i64 [[TMP56]], 0
; CHECK-NEXT:    [[TMP61:%.*]] = or i1 [[TMP59]], [[TMP60]]
; CHECK-NEXT:    br i1 [[TMP61]], label [[FP_TO_I_CLEANUP:%.*]], label [[FP_TO_I_IF_CHECK_SATURATE:%.*]]
; CHECK:       fp-to-i-if-check.saturate:
; CHECK-NEXT:    [[TMP62:%.*]] = icmp uge i64 [[BIASED_EXP]], 1279
; CHECK-NEXT:    br i1 [[TMP62]], label [[FP_TO_I_IF_SATURATE:%.*]], label [[FP_TO_I_IF_CHECK_EXP_SIZE:%.*]]
; CHECK:       fp-to-i-if-saturate:
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-check.exp.size:
; CHECK-NEXT:    [[EXP_SMALLER_MANTISSA_WIDTH:%.*]] = icmp ult i64 [[BIASED_EXP]], 1075
; CHECK-NEXT:    br i1 [[EXP_SMALLER_MANTISSA_WIDTH]], label [[FP_TO_I_IF_EXP_SMALL:%.*]], label [[FP_TO_I_IF_EXP_LARGE:%.*]]
; CHECK:       fp-to-i-if-exp.small:
; CHECK-NEXT:    [[TMP63:%.*]] = sub i64 1075, [[BIASED_EXP]]
; CHECK-NEXT:    [[TMP64:%.*]] = lshr i64 [[SIGNIFICAND]], [[TMP63]]
; CHECK-NEXT:    [[TMP65:%.*]] = zext i64 [[TMP64]] to i256
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-exp.large:
; CHECK-NEXT:    [[TMP66:%.*]] = add i64 [[BIASED_EXP]], -1075
; CHECK-NEXT:    [[TMP67:%.*]] = zext i64 [[SIGNIFICAND]] to i256
; CHECK-NEXT:    [[TMP68:%.*]] = zext i64 [[TMP66]] to i256
; CHECK-NEXT:    [[TMP69:%.*]] = shl i256 [[TMP67]], [[TMP68]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-cleanup:
; CHECK-NEXT:    [[TMP70:%.*]] = phi i256 [ -1, [[FP_TO_I_IF_SATURATE]] ], [ [[TMP65]], [[FP_TO_I_IF_EXP_SMALL]] ], [ [[TMP69]], [[FP_TO_I_IF_EXP_LARGE]] ], [ 0, [[FP_TO_I_CLEANUP1]] ]
; CHECK-NEXT:    [[TMP71:%.*]] = insertelement <4 x i256> [[TMP53]], i256 [[TMP70]], i64 3
; CHECK-NEXT:    ret <4 x i256> [[TMP71]]
;
  %r = call <4 x i256> @llvm.fptoui.sat.v4i256.v4f64(<4 x double> %x)
  ret <4 x i256> %r
}
