; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -mtriple=x86_64-- --expand-ir-insts < %s | FileCheck %s
; RUN: opt -S -mtriple=x86_64-- -passes='require<libcall-lowering-info>,expand-ir-insts' < %s | FileCheck %s

define i129 @halftosi129(half %a) {
; CHECK-LABEL: @halftosi129(
; CHECK-NEXT:    [[TMP1:%.*]] = fptosi half [[A:%.*]] to i32
; CHECK-NEXT:    [[TMP2:%.*]] = sext i32 [[TMP1]] to i129
; CHECK-NEXT:    ret i129 [[TMP2]]
;
  %conv = fptosi half %a to i129
  ret i129 %conv
}

define i129 @floattosi129(float %a) {
; CHECK-LABEL: @floattosi129(
; CHECK-NEXT:  fp-to-i-entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast float [[A:%.*]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i129
; CHECK-NEXT:    [[TMP2:%.*]] = icmp sgt i32 [[TMP0]], -1
; CHECK-NEXT:    [[SIGN:%.*]] = select i1 [[TMP2]], i129 1, i129 -1
; CHECK-NEXT:    [[TMP3:%.*]] = lshr i129 [[TMP1]], 23
; CHECK-NEXT:    [[BIASED_EXP:%.*]] = and i129 [[TMP3]], 255
; CHECK-NEXT:    [[TMP4:%.*]] = and i129 [[TMP1]], 8388607
; CHECK-NEXT:    [[SIGNIFICAND:%.*]] = or i129 [[TMP4]], 8388608
; CHECK-NEXT:    [[EXP_IS_NEGATIVE:%.*]] = icmp ult i129 [[BIASED_EXP]], 127
; CHECK-NEXT:    br i1 [[EXP_IS_NEGATIVE]], label [[FP_TO_I_CLEANUP:%.*]], label [[FP_TO_I_IF_CHECK_SATURATE:%.*]]
; CHECK:       fp-to-i-if-check.saturate:
; CHECK-NEXT:    [[TMP5:%.*]] = add i129 [[BIASED_EXP]], -256
; CHECK-NEXT:    [[TMP6:%.*]] = icmp ult i129 [[TMP5]], -129
; CHECK-NEXT:    br i1 [[TMP6]], label [[FP_TO_I_IF_SATURATE:%.*]], label [[FP_TO_I_IF_CHECK_EXP_SIZE:%.*]]
; CHECK:       fp-to-i-if-saturate:
; CHECK-NEXT:    [[SATURATED:%.*]] = select i1 [[TMP2]], i129 340282366920938463463374607431768211455, i129 -340282366920938463463374607431768211456
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-check.exp.size:
; CHECK-NEXT:    [[EXP_SMALLER_MANTISSA_WIDTH:%.*]] = icmp ult i129 [[BIASED_EXP]], 150
; CHECK-NEXT:    br i1 [[EXP_SMALLER_MANTISSA_WIDTH]], label [[FP_TO_I_IF_EXP_SMALL:%.*]], label [[FP_TO_I_IF_EXP_LARGE:%.*]]
; CHECK:       fp-to-i-if-exp.small:
; CHECK-NEXT:    [[TMP7:%.*]] = sub i129 150, [[BIASED_EXP]]
; CHECK-NEXT:    [[TMP8:%.*]] = lshr i129 [[SIGNIFICAND]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = mul i129 [[TMP8]], [[SIGN]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-exp.large:
; CHECK-NEXT:    [[TMP10:%.*]] = add i129 [[BIASED_EXP]], -150
; CHECK-NEXT:    [[TMP11:%.*]] = shl i129 [[SIGNIFICAND]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = mul i129 [[TMP11]], [[SIGN]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-cleanup:
; CHECK-NEXT:    [[TMP13:%.*]] = phi i129 [ [[SATURATED]], [[FP_TO_I_IF_SATURATE]] ], [ [[TMP9]], [[FP_TO_I_IF_EXP_SMALL]] ], [ [[TMP12]], [[FP_TO_I_IF_EXP_LARGE]] ], [ 0, [[FP_TO_I_ENTRY:%.*]] ]
; CHECK-NEXT:    ret i129 [[TMP13]]
;
  %conv = fptosi float %a to i129
  ret i129 %conv
}

define i129 @doubletosi129(double %a) {
; CHECK-LABEL: @doubletosi129(
; CHECK-NEXT:  fp-to-i-entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast double [[A:%.*]] to i64
; CHECK-NEXT:    [[TMP1:%.*]] = zext i64 [[TMP0]] to i129
; CHECK-NEXT:    [[TMP2:%.*]] = icmp sgt i64 [[TMP0]], -1
; CHECK-NEXT:    [[SIGN:%.*]] = select i1 [[TMP2]], i129 1, i129 -1
; CHECK-NEXT:    [[TMP3:%.*]] = lshr i129 [[TMP1]], 52
; CHECK-NEXT:    [[BIASED_EXP:%.*]] = and i129 [[TMP3]], 2047
; CHECK-NEXT:    [[TMP4:%.*]] = and i129 [[TMP1]], 4503599627370495
; CHECK-NEXT:    [[SIGNIFICAND:%.*]] = or i129 [[TMP4]], 4503599627370496
; CHECK-NEXT:    [[EXP_IS_NEGATIVE:%.*]] = icmp ult i129 [[BIASED_EXP]], 1023
; CHECK-NEXT:    br i1 [[EXP_IS_NEGATIVE]], label [[FP_TO_I_CLEANUP:%.*]], label [[FP_TO_I_IF_CHECK_SATURATE:%.*]]
; CHECK:       fp-to-i-if-check.saturate:
; CHECK-NEXT:    [[TMP5:%.*]] = add i129 [[BIASED_EXP]], -1152
; CHECK-NEXT:    [[TMP6:%.*]] = icmp ult i129 [[TMP5]], -129
; CHECK-NEXT:    br i1 [[TMP6]], label [[FP_TO_I_IF_SATURATE:%.*]], label [[FP_TO_I_IF_CHECK_EXP_SIZE:%.*]]
; CHECK:       fp-to-i-if-saturate:
; CHECK-NEXT:    [[SATURATED:%.*]] = select i1 [[TMP2]], i129 340282366920938463463374607431768211455, i129 -340282366920938463463374607431768211456
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-check.exp.size:
; CHECK-NEXT:    [[EXP_SMALLER_MANTISSA_WIDTH:%.*]] = icmp ult i129 [[BIASED_EXP]], 1075
; CHECK-NEXT:    br i1 [[EXP_SMALLER_MANTISSA_WIDTH]], label [[FP_TO_I_IF_EXP_SMALL:%.*]], label [[FP_TO_I_IF_EXP_LARGE:%.*]]
; CHECK:       fp-to-i-if-exp.small:
; CHECK-NEXT:    [[TMP7:%.*]] = sub i129 1075, [[BIASED_EXP]]
; CHECK-NEXT:    [[TMP8:%.*]] = lshr i129 [[SIGNIFICAND]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = mul i129 [[TMP8]], [[SIGN]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-exp.large:
; CHECK-NEXT:    [[TMP10:%.*]] = add i129 [[BIASED_EXP]], -1075
; CHECK-NEXT:    [[TMP11:%.*]] = shl i129 [[SIGNIFICAND]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = mul i129 [[TMP11]], [[SIGN]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-cleanup:
; CHECK-NEXT:    [[TMP13:%.*]] = phi i129 [ [[SATURATED]], [[FP_TO_I_IF_SATURATE]] ], [ [[TMP9]], [[FP_TO_I_IF_EXP_SMALL]] ], [ [[TMP12]], [[FP_TO_I_IF_EXP_LARGE]] ], [ 0, [[FP_TO_I_ENTRY:%.*]] ]
; CHECK-NEXT:    ret i129 [[TMP13]]
;
  %conv = fptosi double %a to i129
  ret i129 %conv
}

define i129 @x86_fp80tosi129(x86_fp80 %a) {
; CHECK-LABEL: @x86_fp80tosi129(
; CHECK-NEXT:  fp-to-i-entry:
; CHECK-NEXT:    [[TMP0:%.*]] = fpext x86_fp80 [[A:%.*]] to fp128
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast fp128 [[TMP0]] to i128
; CHECK-NEXT:    [[TMP2:%.*]] = zext i128 [[TMP1]] to i129
; CHECK-NEXT:    [[TMP3:%.*]] = icmp sgt i128 [[TMP1]], -1
; CHECK-NEXT:    [[SIGN:%.*]] = select i1 [[TMP3]], i129 1, i129 -1
; CHECK-NEXT:    [[TMP4:%.*]] = lshr i129 [[TMP2]], 112
; CHECK-NEXT:    [[BIASED_EXP:%.*]] = and i129 [[TMP4]], 32767
; CHECK-NEXT:    [[TMP5:%.*]] = and i129 [[TMP2]], 5192296858534827628530496329220095
; CHECK-NEXT:    [[SIGNIFICAND:%.*]] = or i129 [[TMP5]], 5192296858534827628530496329220096
; CHECK-NEXT:    [[EXP_IS_NEGATIVE:%.*]] = icmp ult i129 [[BIASED_EXP]], 16383
; CHECK-NEXT:    br i1 [[EXP_IS_NEGATIVE]], label [[FP_TO_I_CLEANUP:%.*]], label [[FP_TO_I_IF_CHECK_SATURATE:%.*]]
; CHECK:       fp-to-i-if-check.saturate:
; CHECK-NEXT:    [[TMP6:%.*]] = add i129 [[BIASED_EXP]], -16512
; CHECK-NEXT:    [[TMP7:%.*]] = icmp ult i129 [[TMP6]], -129
; CHECK-NEXT:    br i1 [[TMP7]], label [[FP_TO_I_IF_SATURATE:%.*]], label [[FP_TO_I_IF_CHECK_EXP_SIZE:%.*]]
; CHECK:       fp-to-i-if-saturate:
; CHECK-NEXT:    [[SATURATED:%.*]] = select i1 [[TMP3]], i129 340282366920938463463374607431768211455, i129 -340282366920938463463374607431768211456
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-check.exp.size:
; CHECK-NEXT:    [[EXP_SMALLER_MANTISSA_WIDTH:%.*]] = icmp ult i129 [[BIASED_EXP]], 16495
; CHECK-NEXT:    br i1 [[EXP_SMALLER_MANTISSA_WIDTH]], label [[FP_TO_I_IF_EXP_SMALL:%.*]], label [[FP_TO_I_IF_EXP_LARGE:%.*]]
; CHECK:       fp-to-i-if-exp.small:
; CHECK-NEXT:    [[TMP8:%.*]] = sub i129 16495, [[BIASED_EXP]]
; CHECK-NEXT:    [[TMP9:%.*]] = lshr i129 [[SIGNIFICAND]], [[TMP8]]
; CHECK-NEXT:    [[TMP10:%.*]] = mul i129 [[TMP9]], [[SIGN]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-exp.large:
; CHECK-NEXT:    [[TMP11:%.*]] = add i129 [[BIASED_EXP]], -16495
; CHECK-NEXT:    [[TMP12:%.*]] = shl i129 [[SIGNIFICAND]], [[TMP11]]
; CHECK-NEXT:    [[TMP13:%.*]] = mul i129 [[TMP12]], [[SIGN]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-cleanup:
; CHECK-NEXT:    [[TMP14:%.*]] = phi i129 [ [[SATURATED]], [[FP_TO_I_IF_SATURATE]] ], [ [[TMP10]], [[FP_TO_I_IF_EXP_SMALL]] ], [ [[TMP13]], [[FP_TO_I_IF_EXP_LARGE]] ], [ 0, [[FP_TO_I_ENTRY:%.*]] ]
; CHECK-NEXT:    ret i129 [[TMP14]]
;
  %conv = fptosi x86_fp80 %a to i129
  ret i129 %conv
}

define i129 @fp128tosi129(fp128 %a) {
; CHECK-LABEL: @fp128tosi129(
; CHECK-NEXT:  fp-to-i-entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast fp128 [[A:%.*]] to i128
; CHECK-NEXT:    [[TMP1:%.*]] = zext i128 [[TMP0]] to i129
; CHECK-NEXT:    [[TMP2:%.*]] = icmp sgt i128 [[TMP0]], -1
; CHECK-NEXT:    [[SIGN:%.*]] = select i1 [[TMP2]], i129 1, i129 -1
; CHECK-NEXT:    [[TMP3:%.*]] = lshr i129 [[TMP1]], 112
; CHECK-NEXT:    [[BIASED_EXP:%.*]] = and i129 [[TMP3]], 32767
; CHECK-NEXT:    [[TMP4:%.*]] = and i129 [[TMP1]], 5192296858534827628530496329220095
; CHECK-NEXT:    [[SIGNIFICAND:%.*]] = or i129 [[TMP4]], 5192296858534827628530496329220096
; CHECK-NEXT:    [[EXP_IS_NEGATIVE:%.*]] = icmp ult i129 [[BIASED_EXP]], 16383
; CHECK-NEXT:    br i1 [[EXP_IS_NEGATIVE]], label [[FP_TO_I_CLEANUP:%.*]], label [[FP_TO_I_IF_CHECK_SATURATE:%.*]]
; CHECK:       fp-to-i-if-check.saturate:
; CHECK-NEXT:    [[TMP5:%.*]] = add i129 [[BIASED_EXP]], -16512
; CHECK-NEXT:    [[TMP6:%.*]] = icmp ult i129 [[TMP5]], -129
; CHECK-NEXT:    br i1 [[TMP6]], label [[FP_TO_I_IF_SATURATE:%.*]], label [[FP_TO_I_IF_CHECK_EXP_SIZE:%.*]]
; CHECK:       fp-to-i-if-saturate:
; CHECK-NEXT:    [[SATURATED:%.*]] = select i1 [[TMP2]], i129 340282366920938463463374607431768211455, i129 -340282366920938463463374607431768211456
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-check.exp.size:
; CHECK-NEXT:    [[EXP_SMALLER_MANTISSA_WIDTH:%.*]] = icmp ult i129 [[BIASED_EXP]], 16495
; CHECK-NEXT:    br i1 [[EXP_SMALLER_MANTISSA_WIDTH]], label [[FP_TO_I_IF_EXP_SMALL:%.*]], label [[FP_TO_I_IF_EXP_LARGE:%.*]]
; CHECK:       fp-to-i-if-exp.small:
; CHECK-NEXT:    [[TMP7:%.*]] = sub i129 16495, [[BIASED_EXP]]
; CHECK-NEXT:    [[TMP8:%.*]] = lshr i129 [[SIGNIFICAND]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = mul i129 [[TMP8]], [[SIGN]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-exp.large:
; CHECK-NEXT:    [[TMP10:%.*]] = add i129 [[BIASED_EXP]], -16495
; CHECK-NEXT:    [[TMP11:%.*]] = shl i129 [[SIGNIFICAND]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = mul i129 [[TMP11]], [[SIGN]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-cleanup:
; CHECK-NEXT:    [[TMP13:%.*]] = phi i129 [ [[SATURATED]], [[FP_TO_I_IF_SATURATE]] ], [ [[TMP9]], [[FP_TO_I_IF_EXP_SMALL]] ], [ [[TMP12]], [[FP_TO_I_IF_EXP_LARGE]] ], [ 0, [[FP_TO_I_ENTRY:%.*]] ]
; CHECK-NEXT:    ret i129 [[TMP13]]
;
  %conv = fptosi fp128 %a to i129
  ret i129 %conv
}

define <2 x i129> @floattosi129v2(<2 x float> %a) {
; CHECK-LABEL: @floattosi129v2(
; CHECK-NEXT:  fp-to-i-entryfp-to-i-entry:
; CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x float> [[A:%.*]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast float [[TMP0]] to i32
; CHECK-NEXT:    [[TMP2:%.*]] = zext i32 [[TMP1]] to i129
; CHECK-NEXT:    [[TMP3:%.*]] = icmp sgt i32 [[TMP1]], -1
; CHECK-NEXT:    [[SIGN7:%.*]] = select i1 [[TMP3]], i129 1, i129 -1
; CHECK-NEXT:    [[TMP4:%.*]] = lshr i129 [[TMP2]], 23
; CHECK-NEXT:    [[BIASED_EXP8:%.*]] = and i129 [[TMP4]], 255
; CHECK-NEXT:    [[TMP5:%.*]] = and i129 [[TMP2]], 8388607
; CHECK-NEXT:    [[SIGNIFICAND9:%.*]] = or i129 [[TMP5]], 8388608
; CHECK-NEXT:    [[EXP_IS_NEGATIVE10:%.*]] = icmp ult i129 [[BIASED_EXP8]], 127
; CHECK-NEXT:    br i1 [[EXP_IS_NEGATIVE10]], label [[FP_TO_I_CLEANUP1:%.*]], label [[FP_TO_I_IF_CHECK_SATURATE2:%.*]]
; CHECK:       fp-to-i-if-check.saturate2:
; CHECK-NEXT:    [[TMP6:%.*]] = add i129 [[BIASED_EXP8]], -256
; CHECK-NEXT:    [[TMP7:%.*]] = icmp ult i129 [[TMP6]], -129
; CHECK-NEXT:    br i1 [[TMP7]], label [[FP_TO_I_IF_SATURATE3:%.*]], label [[FP_TO_I_IF_CHECK_EXP_SIZE4:%.*]]
; CHECK:       fp-to-i-if-saturate3:
; CHECK-NEXT:    [[SATURATED11:%.*]] = select i1 [[TMP3]], i129 340282366920938463463374607431768211455, i129 -340282366920938463463374607431768211456
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP1]]
; CHECK:       fp-to-i-if-check.exp.size4:
; CHECK-NEXT:    [[EXP_SMALLER_MANTISSA_WIDTH12:%.*]] = icmp ult i129 [[BIASED_EXP8]], 150
; CHECK-NEXT:    br i1 [[EXP_SMALLER_MANTISSA_WIDTH12]], label [[FP_TO_I_IF_EXP_SMALL5:%.*]], label [[FP_TO_I_IF_EXP_LARGE6:%.*]]
; CHECK:       fp-to-i-if-exp.small5:
; CHECK-NEXT:    [[TMP8:%.*]] = sub i129 150, [[BIASED_EXP8]]
; CHECK-NEXT:    [[TMP9:%.*]] = lshr i129 [[SIGNIFICAND9]], [[TMP8]]
; CHECK-NEXT:    [[TMP10:%.*]] = mul i129 [[TMP9]], [[SIGN7]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP1]]
; CHECK:       fp-to-i-if-exp.large6:
; CHECK-NEXT:    [[TMP11:%.*]] = add i129 [[BIASED_EXP8]], -150
; CHECK-NEXT:    [[TMP12:%.*]] = shl i129 [[SIGNIFICAND9]], [[TMP11]]
; CHECK-NEXT:    [[TMP13:%.*]] = mul i129 [[TMP12]], [[SIGN7]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP1]]
; CHECK:       fp-to-i-cleanup1:
; CHECK-NEXT:    [[TMP14:%.*]] = phi i129 [ [[SATURATED11]], [[FP_TO_I_IF_SATURATE3]] ], [ [[TMP10]], [[FP_TO_I_IF_EXP_SMALL5]] ], [ [[TMP13]], [[FP_TO_I_IF_EXP_LARGE6]] ], [ 0, [[FP_TO_I_ENTRYFP_TO_I_ENTRY:%.*]] ]
; CHECK-NEXT:    [[TMP15:%.*]] = insertelement <2 x i129> poison, i129 [[TMP14]], i64 0
; CHECK-NEXT:    [[TMP16:%.*]] = extractelement <2 x float> [[A]], i64 1
; CHECK-NEXT:    [[TMP17:%.*]] = bitcast float [[TMP16]] to i32
; CHECK-NEXT:    [[TMP18:%.*]] = zext i32 [[TMP17]] to i129
; CHECK-NEXT:    [[TMP19:%.*]] = icmp sgt i32 [[TMP17]], -1
; CHECK-NEXT:    [[SIGN:%.*]] = select i1 [[TMP19]], i129 1, i129 -1
; CHECK-NEXT:    [[TMP20:%.*]] = lshr i129 [[TMP18]], 23
; CHECK-NEXT:    [[BIASED_EXP:%.*]] = and i129 [[TMP20]], 255
; CHECK-NEXT:    [[TMP21:%.*]] = and i129 [[TMP18]], 8388607
; CHECK-NEXT:    [[SIGNIFICAND:%.*]] = or i129 [[TMP21]], 8388608
; CHECK-NEXT:    [[EXP_IS_NEGATIVE:%.*]] = icmp ult i129 [[BIASED_EXP]], 127
; CHECK-NEXT:    br i1 [[EXP_IS_NEGATIVE]], label [[FP_TO_I_CLEANUP:%.*]], label [[FP_TO_I_IF_CHECK_SATURATE:%.*]]
; CHECK:       fp-to-i-if-check.saturate:
; CHECK-NEXT:    [[TMP22:%.*]] = add i129 [[BIASED_EXP]], -256
; CHECK-NEXT:    [[TMP23:%.*]] = icmp ult i129 [[TMP22]], -129
; CHECK-NEXT:    br i1 [[TMP23]], label [[FP_TO_I_IF_SATURATE:%.*]], label [[FP_TO_I_IF_CHECK_EXP_SIZE:%.*]]
; CHECK:       fp-to-i-if-saturate:
; CHECK-NEXT:    [[SATURATED:%.*]] = select i1 [[TMP19]], i129 340282366920938463463374607431768211455, i129 -340282366920938463463374607431768211456
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-check.exp.size:
; CHECK-NEXT:    [[EXP_SMALLER_MANTISSA_WIDTH:%.*]] = icmp ult i129 [[BIASED_EXP]], 150
; CHECK-NEXT:    br i1 [[EXP_SMALLER_MANTISSA_WIDTH]], label [[FP_TO_I_IF_EXP_SMALL:%.*]], label [[FP_TO_I_IF_EXP_LARGE:%.*]]
; CHECK:       fp-to-i-if-exp.small:
; CHECK-NEXT:    [[TMP24:%.*]] = sub i129 150, [[BIASED_EXP]]
; CHECK-NEXT:    [[TMP25:%.*]] = lshr i129 [[SIGNIFICAND]], [[TMP24]]
; CHECK-NEXT:    [[TMP26:%.*]] = mul i129 [[TMP25]], [[SIGN]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-if-exp.large:
; CHECK-NEXT:    [[TMP27:%.*]] = add i129 [[BIASED_EXP]], -150
; CHECK-NEXT:    [[TMP28:%.*]] = shl i129 [[SIGNIFICAND]], [[TMP27]]
; CHECK-NEXT:    [[TMP29:%.*]] = mul i129 [[TMP28]], [[SIGN]]
; CHECK-NEXT:    br label [[FP_TO_I_CLEANUP]]
; CHECK:       fp-to-i-cleanup:
; CHECK-NEXT:    [[TMP30:%.*]] = phi i129 [ [[SATURATED]], [[FP_TO_I_IF_SATURATE]] ], [ [[TMP26]], [[FP_TO_I_IF_EXP_SMALL]] ], [ [[TMP29]], [[FP_TO_I_IF_EXP_LARGE]] ], [ 0, [[FP_TO_I_CLEANUP1]] ]
; CHECK-NEXT:    [[TMP31:%.*]] = insertelement <2 x i129> [[TMP15]], i129 [[TMP30]], i64 1
; CHECK-NEXT:    ret <2 x i129> [[TMP31]]
;
  %conv = fptosi <2 x float> %a to <2 x i129>
  ret <2 x i129> %conv
}
