; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -p scalarize-masked-mem-intrin -S < %s | FileCheck %s

define { <4 x i32>, <4 x i1> } @load_ff_v4i32(ptr %p, <4 x i1> %mask) {
; CHECK-LABEL: define { <4 x i32>, <4 x i1> } @load_ff_v4i32(
; CHECK-SAME: ptr [[P:%.*]], <4 x i1> [[MASK:%.*]]) {
; CHECK-NEXT:    [[FIRST_ACTIVE:%.*]] = extractelement <4 x i1> [[MASK]], i64 0
; CHECK-NEXT:    br i1 [[FIRST_ACTIVE]], label %[[LOAD_FF_FIRST_LANE:.*]], label %[[LOAD_FF_RESULT:.*]]
; CHECK:       [[LOAD_FF_FIRST_LANE]]:
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[P]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[TMP1]], i64 0
; CHECK-NEXT:    br label %[[LOAD_FF_RESULT]]
; CHECK:       [[LOAD_FF_RESULT]]:
; CHECK-NEXT:    [[TMP3:%.*]] = phi <4 x i32> [ poison, [[TMP0:%.*]] ], [ [[TMP2]], %[[LOAD_FF_FIRST_LANE]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = phi <4 x i1> [ zeroinitializer, [[TMP0]] ], [ <i1 true, i1 false, i1 false, i1 false>, %[[LOAD_FF_FIRST_LANE]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = insertvalue { <4 x i32>, <4 x i1> } poison, <4 x i32> [[TMP3]], 0
; CHECK-NEXT:    [[RES_FIRST_LANE_ONLY:%.*]] = insertvalue { <4 x i32>, <4 x i1> } [[TMP5]], <4 x i1> [[TMP4]], 1
; CHECK-NEXT:    ret { <4 x i32>, <4 x i1> } [[RES_FIRST_LANE_ONLY]]
;
  %res = call { <4 x i32>, <4 x i1> } @llvm.masked.load.first.fault(ptr %p, i32 16, <4 x i1> %mask)
  ret { <4 x i32>, <4 x i1> } %res
}

;; We can 'scalarize' first faulting loads for scalable vectors, since we only
;; need to insert a single element into the start of a poison splat vector.
define { <vscale x 4 x i32>, <vscale x 4 x i1> } @load_ff_nxv4i32(ptr %p, <vscale x 4 x i1> %mask) {
; CHECK-LABEL: define { <vscale x 4 x i32>, <vscale x 4 x i1> } @load_ff_nxv4i32(
; CHECK-SAME: ptr [[P:%.*]], <vscale x 4 x i1> [[MASK:%.*]]) {
; CHECK-NEXT:    [[FIRST_ACTIVE:%.*]] = extractelement <vscale x 4 x i1> [[MASK]], i64 0
; CHECK-NEXT:    br i1 [[FIRST_ACTIVE]], label %[[LOAD_FF_FIRST_LANE:.*]], label %[[LOAD_FF_RESULT:.*]]
; CHECK:       [[LOAD_FF_FIRST_LANE]]:
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[P]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <vscale x 4 x i32> poison, i32 [[TMP1]], i64 0
; CHECK-NEXT:    br label %[[LOAD_FF_RESULT]]
; CHECK:       [[LOAD_FF_RESULT]]:
; CHECK-NEXT:    [[TMP3:%.*]] = phi <vscale x 4 x i32> [ poison, [[TMP0:%.*]] ], [ [[TMP2]], %[[LOAD_FF_FIRST_LANE]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = phi <vscale x 4 x i1> [ zeroinitializer, [[TMP0]] ], [ insertelement (<vscale x 4 x i1> zeroinitializer, i1 true, i64 0), %[[LOAD_FF_FIRST_LANE]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = insertvalue { <vscale x 4 x i32>, <vscale x 4 x i1> } poison, <vscale x 4 x i32> [[TMP3]], 0
; CHECK-NEXT:    [[RES:%.*]] = insertvalue { <vscale x 4 x i32>, <vscale x 4 x i1> } [[TMP5]], <vscale x 4 x i1> [[TMP4]], 1
; CHECK-NEXT:    ret { <vscale x 4 x i32>, <vscale x 4 x i1> } [[RES]]
;
  %res = call { <vscale x 4 x i32>, <vscale x 4 x i1> } @llvm.masked.load.first.fault(ptr %p, i32 16, <vscale x 4 x i1> %mask)
  ret { <vscale x 4 x i32>, <vscale x 4 x i1> } %res
}

define { <2 x double>, <2 x i1> } @load_ff_v2f64_all_true(ptr %p) {
; CHECK-LABEL: define { <2 x double>, <2 x i1> } @load_ff_v2f64_all_true(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    br i1 true, label %[[LOAD_FF_FIRST_LANE:.*]], label %[[LOAD_FF_RESULT:.*]]
; CHECK:       [[LOAD_FF_FIRST_LANE]]:
; CHECK-NEXT:    [[TMP1:%.*]] = load double, ptr [[P]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <2 x double> poison, double [[TMP1]], i64 0
; CHECK-NEXT:    br label %[[LOAD_FF_RESULT]]
; CHECK:       [[LOAD_FF_RESULT]]:
; CHECK-NEXT:    [[TMP3:%.*]] = phi <2 x double> [ poison, [[TMP0:%.*]] ], [ [[TMP2]], %[[LOAD_FF_FIRST_LANE]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = phi <2 x i1> [ zeroinitializer, [[TMP0]] ], [ <i1 true, i1 false>, %[[LOAD_FF_FIRST_LANE]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = insertvalue { <2 x double>, <2 x i1> } poison, <2 x double> [[TMP3]], 0
; CHECK-NEXT:    [[RES_FIRST_LANE_ONLY:%.*]] = insertvalue { <2 x double>, <2 x i1> } [[TMP5]], <2 x i1> [[TMP4]], 1
; CHECK-NEXT:    ret { <2 x double>, <2 x i1> } [[RES_FIRST_LANE_ONLY]]
;
  %res = call { <2 x double>, <2 x i1> } @llvm.masked.load.first.fault(ptr %p, i32 16, <2 x i1> <i1 true, i1 true>)
  ret { <2 x double>, <2 x i1> } %res
}

define { <16 x i16>, <16 x i1> } @load_ff_v16i16_all_false(ptr %p) {
; CHECK-LABEL: define { <16 x i16>, <16 x i1> } @load_ff_v16i16_all_false(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    br i1 false, label %[[LOAD_FF_FIRST_LANE:.*]], label %[[LOAD_FF_RESULT:.*]]
; CHECK:       [[LOAD_FF_FIRST_LANE]]:
; CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[P]], align 32
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <16 x i16> poison, i16 [[TMP1]], i64 0
; CHECK-NEXT:    br label %[[LOAD_FF_RESULT]]
; CHECK:       [[LOAD_FF_RESULT]]:
; CHECK-NEXT:    [[TMP3:%.*]] = phi <16 x i16> [ poison, [[TMP0:%.*]] ], [ [[TMP2]], %[[LOAD_FF_FIRST_LANE]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = phi <16 x i1> [ zeroinitializer, [[TMP0]] ], [ <i1 true, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false>, %[[LOAD_FF_FIRST_LANE]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = insertvalue { <16 x i16>, <16 x i1> } poison, <16 x i16> [[TMP3]], 0
; CHECK-NEXT:    [[RES_FIRST_LANE_ONLY:%.*]] = insertvalue { <16 x i16>, <16 x i1> } [[TMP5]], <16 x i1> [[TMP4]], 1
; CHECK-NEXT:    ret { <16 x i16>, <16 x i1> } [[RES_FIRST_LANE_ONLY]]
;
  %res = call { <16 x i16>, <16 x i1> } @llvm.masked.load.first.fault(ptr %p, i32 32, <16 x i1> zeroinitializer)
  ret { <16 x i16>, <16 x i1> } %res
}
