; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=wasm32-unknown-unknown -mattr=+reference-types < %s | FileCheck -check-prefixes=CHECK,WASM32 %s
; RUN: llc -mtriple=wasm64-unknown-unknown -mattr=+reference-types < %s | FileCheck -check-prefixes=CHECK,WASM64 %s

%funcref = type ptr addrspace(20) ;; addrspace 20 is nonintegral

declare void @foo();

@global_var = local_unnamed_addr global i32 0

define %funcref @cast_const_funcptr() {
; CHECK-LABEL: cast_const_funcptr:
; CHECK:         .functype cast_const_funcptr () -> (funcref)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    ref.func foo
; CHECK-NEXT:    # fallthrough-return
  %result = addrspacecast ptr @foo to %funcref
  ret %funcref %result
}

define %funcref @cast_const_not_funcptr() {
; WASM32-LABEL: cast_const_not_funcptr:
; WASM32:         .functype cast_const_not_funcptr () -> (funcref)
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    i32.const global_var
; WASM32-NEXT:    table.get __indirect_function_table
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: cast_const_not_funcptr:
; WASM64:         .functype cast_const_not_funcptr () -> (funcref)
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    i64.const global_var
; WASM64-NEXT:    table.get __indirect_function_table
; WASM64-NEXT:    # fallthrough-return
  %result = addrspacecast ptr @global_var to %funcref
  ret %funcref %result
}

define %funcref @cast_param_funcptr(ptr %funcptr) {
; WASM32-LABEL: cast_param_funcptr:
; WASM32:         .functype cast_param_funcptr (i32) -> (funcref)
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    table.get __indirect_function_table
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: cast_param_funcptr:
; WASM64:         .functype cast_param_funcptr (i64) -> (funcref)
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    table.get __indirect_function_table
; WASM64-NEXT:    # fallthrough-return
  %result = addrspacecast ptr %funcptr to %funcref
  ret %funcref %result
}
