; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s --mtriple=wasm32 -mattr=+atomics,+relaxed-atomics | FileCheck %s --check-prefixes=WASM32
; RUN: llc < %s --mtriple=wasm64 -mattr=+atomics,+relaxed-atomics | FileCheck %s --check-prefixes=WASM64

define i32 @load_i32_acquire(ptr %p) {
; WASM32-LABEL: load_i32_acquire:
; WASM32:         .functype load_i32_acquire (i32) -> (i32)
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    i32.atomic.load acqrel 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: load_i32_acquire:
; WASM64:         .functype load_i32_acquire (i64) -> (i32)
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    i32.atomic.load acqrel 0
; WASM64-NEXT:    # fallthrough-return
  %v = load atomic i32, ptr %p acquire, align 4
  ret i32 %v
}

define i32 @load_i32_seq_cst(ptr %p) {
; WASM32-LABEL: load_i32_seq_cst:
; WASM32:         .functype load_i32_seq_cst (i32) -> (i32)
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    i32.atomic.load seqcst 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: load_i32_seq_cst:
; WASM64:         .functype load_i32_seq_cst (i64) -> (i32)
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    i32.atomic.load seqcst 0
; WASM64-NEXT:    # fallthrough-return
  %v = load atomic i32, ptr %p seq_cst, align 4
  ret i32 %v
}

define void @store_i32_release(ptr %p, i32 %v) {
; WASM32-LABEL: store_i32_release:
; WASM32:         .functype store_i32_release (i32, i32) -> ()
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    i32.atomic.store acqrel 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: store_i32_release:
; WASM64:         .functype store_i32_release (i64, i32) -> ()
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    i32.atomic.store acqrel 0
; WASM64-NEXT:    # fallthrough-return
  store atomic i32 %v, ptr %p release, align 4
  ret void
}

define void @store_i32_seq_cst(ptr %p, i32 %v) {
; WASM32-LABEL: store_i32_seq_cst:
; WASM32:         .functype store_i32_seq_cst (i32, i32) -> ()
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    i32.atomic.store seqcst 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: store_i32_seq_cst:
; WASM64:         .functype store_i32_seq_cst (i64, i32) -> ()
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    i32.atomic.store seqcst 0
; WASM64-NEXT:    # fallthrough-return
  store atomic i32 %v, ptr %p seq_cst, align 4
  ret void
}

define i32 @add_i32_acq_rel(ptr %p, i32 %v) {
; WASM32-LABEL: add_i32_acq_rel:
; WASM32:         .functype add_i32_acq_rel (i32, i32) -> (i32)
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    i32.atomic.rmw.add acqrel 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: add_i32_acq_rel:
; WASM64:         .functype add_i32_acq_rel (i64, i32) -> (i32)
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    i32.atomic.rmw.add acqrel 0
; WASM64-NEXT:    # fallthrough-return
  %old = atomicrmw add ptr %p, i32 %v acq_rel
  ret i32 %old
}

define i32 @add_i32_seq_cst(ptr %p, i32 %v) {
; WASM32-LABEL: add_i32_seq_cst:
; WASM32:         .functype add_i32_seq_cst (i32, i32) -> (i32)
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    i32.atomic.rmw.add seqcst 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: add_i32_seq_cst:
; WASM64:         .functype add_i32_seq_cst (i64, i32) -> (i32)
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    i32.atomic.rmw.add seqcst 0
; WASM64-NEXT:    # fallthrough-return
  %old = atomicrmw add ptr %p, i32 %v seq_cst
  ret i32 %old
}

define i32 @cmpxchg_i32_acquire_acquire(ptr %p, i32 %exp, i32 %new) {
; WASM32-LABEL: cmpxchg_i32_acquire_acquire:
; WASM32:         .functype cmpxchg_i32_acquire_acquire (i32, i32, i32) -> (i32)
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    local.get 2
; WASM32-NEXT:    i32.atomic.rmw.cmpxchg acqrel 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: cmpxchg_i32_acquire_acquire:
; WASM64:         .functype cmpxchg_i32_acquire_acquire (i64, i32, i32) -> (i32)
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    local.get 2
; WASM64-NEXT:    i32.atomic.rmw.cmpxchg acqrel 0
; WASM64-NEXT:    # fallthrough-return
  %pair = cmpxchg ptr %p, i32 %exp, i32 %new acquire acquire
  %val = extractvalue { i32, i1 } %pair, 0
  ret i32 %val
}

define i32 @cmpxchg_i32_seq_cst_seq_cst(ptr %p, i32 %exp, i32 %new) {
; WASM32-LABEL: cmpxchg_i32_seq_cst_seq_cst:
; WASM32:         .functype cmpxchg_i32_seq_cst_seq_cst (i32, i32, i32) -> (i32)
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    local.get 2
; WASM32-NEXT:    i32.atomic.rmw.cmpxchg seqcst 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: cmpxchg_i32_seq_cst_seq_cst:
; WASM64:         .functype cmpxchg_i32_seq_cst_seq_cst (i64, i32, i32) -> (i32)
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    local.get 2
; WASM64-NEXT:    i32.atomic.rmw.cmpxchg seqcst 0
; WASM64-NEXT:    # fallthrough-return
  %pair = cmpxchg ptr %p, i32 %exp, i32 %new seq_cst seq_cst
  %val = extractvalue { i32, i1 } %pair, 0
  ret i32 %val
}

define void @fence_acquire() {
; WASM32-LABEL: fence_acquire:
; WASM32:         .functype fence_acquire () -> ()
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    atomic.fence acqrel
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: fence_acquire:
; WASM64:         .functype fence_acquire () -> ()
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    atomic.fence acqrel
; WASM64-NEXT:    # fallthrough-return
  fence acquire
  ret void
}

define void @fence_seq_cst() {
; WASM32-LABEL: fence_seq_cst:
; WASM32:         .functype fence_seq_cst () -> ()
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    atomic.fence seqcst
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: fence_seq_cst:
; WASM64:         .functype fence_seq_cst () -> ()
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    atomic.fence seqcst
; WASM64-NEXT:    # fallthrough-return
  fence seq_cst
  ret void
}

define i32 @load_i32_monotonic(ptr %p) {
; WASM32-LABEL: load_i32_monotonic:
; WASM32:         .functype load_i32_monotonic (i32) -> (i32)
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    i32.atomic.load acqrel 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: load_i32_monotonic:
; WASM64:         .functype load_i32_monotonic (i64) -> (i32)
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    i32.atomic.load acqrel 0
; WASM64-NEXT:    # fallthrough-return
  %v = load atomic i32, ptr %p monotonic, align 4
  ret i32 %v
}

define void @store_i32_monotonic(ptr %p, i32 %v) {
; WASM32-LABEL: store_i32_monotonic:
; WASM32:         .functype store_i32_monotonic (i32, i32) -> ()
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    i32.atomic.store acqrel 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: store_i32_monotonic:
; WASM64:         .functype store_i32_monotonic (i64, i32) -> ()
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    i32.atomic.store acqrel 0
; WASM64-NEXT:    # fallthrough-return
  store atomic i32 %v, ptr %p monotonic, align 4
  ret void
}

define i32 @add_i32_release(ptr %p, i32 %v) {
; WASM32-LABEL: add_i32_release:
; WASM32:         .functype add_i32_release (i32, i32) -> (i32)
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    i32.atomic.rmw.add acqrel 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: add_i32_release:
; WASM64:         .functype add_i32_release (i64, i32) -> (i32)
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    i32.atomic.rmw.add acqrel 0
; WASM64-NEXT:    # fallthrough-return
  %old = atomicrmw add ptr %p, i32 %v release
  ret i32 %old
}

define i32 @add_i32_acquire(ptr %p, i32 %v) {
; WASM32-LABEL: add_i32_acquire:
; WASM32:         .functype add_i32_acquire (i32, i32) -> (i32)
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    i32.atomic.rmw.add acqrel 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: add_i32_acquire:
; WASM64:         .functype add_i32_acquire (i64, i32) -> (i32)
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    i32.atomic.rmw.add acqrel 0
; WASM64-NEXT:    # fallthrough-return
  %old = atomicrmw add ptr %p, i32 %v acquire
  ret i32 %old
}

define i32 @add_i32_monotonic(ptr %p, i32 %v) {
; WASM32-LABEL: add_i32_monotonic:
; WASM32:         .functype add_i32_monotonic (i32, i32) -> (i32)
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    i32.atomic.rmw.add acqrel 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: add_i32_monotonic:
; WASM64:         .functype add_i32_monotonic (i64, i32) -> (i32)
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    i32.atomic.rmw.add acqrel 0
; WASM64-NEXT:    # fallthrough-return
  %old = atomicrmw add ptr %p, i32 %v monotonic
  ret i32 %old
}

define i32 @cmpxchg_i32_acq_rel_monotonic(ptr %p, i32 %exp, i32 %new) {
; WASM32-LABEL: cmpxchg_i32_acq_rel_monotonic:
; WASM32:         .functype cmpxchg_i32_acq_rel_monotonic (i32, i32, i32) -> (i32)
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    local.get 2
; WASM32-NEXT:    i32.atomic.rmw.cmpxchg acqrel 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: cmpxchg_i32_acq_rel_monotonic:
; WASM64:         .functype cmpxchg_i32_acq_rel_monotonic (i64, i32, i32) -> (i32)
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    local.get 2
; WASM64-NEXT:    i32.atomic.rmw.cmpxchg acqrel 0
; WASM64-NEXT:    # fallthrough-return
  %pair = cmpxchg ptr %p, i32 %exp, i32 %new acq_rel monotonic
  %val = extractvalue { i32, i1 } %pair, 0
  ret i32 %val
}

define i32 @cmpxchg_i32_release_monotonic(ptr %p, i32 %exp, i32 %new) {
; WASM32-LABEL: cmpxchg_i32_release_monotonic:
; WASM32:         .functype cmpxchg_i32_release_monotonic (i32, i32, i32) -> (i32)
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    local.get 2
; WASM32-NEXT:    i32.atomic.rmw.cmpxchg acqrel 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: cmpxchg_i32_release_monotonic:
; WASM64:         .functype cmpxchg_i32_release_monotonic (i64, i32, i32) -> (i32)
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    local.get 2
; WASM64-NEXT:    i32.atomic.rmw.cmpxchg acqrel 0
; WASM64-NEXT:    # fallthrough-return
  %pair = cmpxchg ptr %p, i32 %exp, i32 %new release monotonic
  %val = extractvalue { i32, i1 } %pair, 0
  ret i32 %val
}

define i32 @cmpxchg_i32_monotonic_monotonic(ptr %p, i32 %exp, i32 %new) {
; WASM32-LABEL: cmpxchg_i32_monotonic_monotonic:
; WASM32:         .functype cmpxchg_i32_monotonic_monotonic (i32, i32, i32) -> (i32)
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    local.get 2
; WASM32-NEXT:    i32.atomic.rmw.cmpxchg acqrel 0
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: cmpxchg_i32_monotonic_monotonic:
; WASM64:         .functype cmpxchg_i32_monotonic_monotonic (i64, i32, i32) -> (i32)
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    local.get 2
; WASM64-NEXT:    i32.atomic.rmw.cmpxchg acqrel 0
; WASM64-NEXT:    # fallthrough-return
  %pair = cmpxchg ptr %p, i32 %exp, i32 %new monotonic monotonic
  %val = extractvalue { i32, i1 } %pair, 0
  ret i32 %val
}

define void @fence_release() {
; WASM32-LABEL: fence_release:
; WASM32:         .functype fence_release () -> ()
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    atomic.fence acqrel
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: fence_release:
; WASM64:         .functype fence_release () -> ()
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    atomic.fence acqrel
; WASM64-NEXT:    # fallthrough-return
  fence release
  ret void
}

define void @fence_acq_rel() {
; WASM32-LABEL: fence_acq_rel:
; WASM32:         .functype fence_acq_rel () -> ()
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    atomic.fence acqrel
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: fence_acq_rel:
; WASM64:         .functype fence_acq_rel () -> ()
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    atomic.fence acqrel
; WASM64-NEXT:    # fallthrough-return
  fence acq_rel
  ret void
}
