; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=wasm32 < %s | FileCheck %s

define float @maxf(float %a, float %b) {
; CHECK-LABEL: maxf:
; CHECK:         .functype maxf (f32, f32) -> (f32)
; CHECK-NEXT:  # %bb.0: # %entry
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    f32.max
; CHECK-NEXT:    # fallthrough-return
entry:
  %cmp = fcmp nnan nsz oge float %a, %b
  %cond = select nnan nsz i1 %cmp, float %a, float %b
  ret float %cond
}

define float @minf(float %a, float %b) {
; CHECK-LABEL: minf:
; CHECK:         .functype minf (f32, f32) -> (f32)
; CHECK-NEXT:  # %bb.0: # %entry
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    f32.min
; CHECK-NEXT:    # fallthrough-return
entry:
  %cmp = fcmp nnan nsz olt float %a, %b
  %cond = select nnan nsz i1 %cmp, float %a, float %b
  ret float %cond
}

define double @maxd(double %a, double %b) {
; CHECK-LABEL: maxd:
; CHECK:         .functype maxd (f64, f64) -> (f64)
; CHECK-NEXT:  # %bb.0: # %entry
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    f64.max
; CHECK-NEXT:    # fallthrough-return
entry:
  %cmp = fcmp nnan nsz oge double %a, %b
  %cond = select nnan nsz i1 %cmp, double %a, double %b
  ret double %cond
}

define double @mind(double %a, double %b) {
; CHECK-LABEL: mind:
; CHECK:         .functype mind (f64, f64) -> (f64)
; CHECK-NEXT:  # %bb.0: # %entry
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    f64.min
; CHECK-NEXT:    # fallthrough-return
entry:
  %cmp = fcmp nnan nsz olt double %a, %b
  %cond = select nnan nsz i1 %cmp, double %a, double %b
  ret double %cond
}
