; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=wasm32-unknown-unknown | FileCheck %s --check-prefix=WASM32
; RUN: llc < %s -mtriple=wasm64-unknown-unknown | FileCheck %s --check-prefix=WASM64

define void @sdivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; WASM32-LABEL: sdivrem_i128:
; WASM32:         .functype sdivrem_i128 (i32, i32, i64, i64, i64, i64) -> ()
; WASM32-NEXT:    .local i32
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    global.get __stack_pointer
; WASM32-NEXT:    i32.const 32
; WASM32-NEXT:    i32.sub
; WASM32-NEXT:    local.tee 6
; WASM32-NEXT:    global.set __stack_pointer
; WASM32-NEXT:    local.get 6
; WASM32-NEXT:    i32.const 16
; WASM32-NEXT:    i32.add
; WASM32-NEXT:    local.get 2
; WASM32-NEXT:    local.get 3
; WASM32-NEXT:    local.get 4
; WASM32-NEXT:    local.get 5
; WASM32-NEXT:    call __divti3
; WASM32-NEXT:    local.get 6
; WASM32-NEXT:    local.get 2
; WASM32-NEXT:    local.get 3
; WASM32-NEXT:    local.get 4
; WASM32-NEXT:    local.get 5
; WASM32-NEXT:    call __modti3
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 6
; WASM32-NEXT:    i64.load 16
; WASM32-NEXT:    i64.store 0
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 6
; WASM32-NEXT:    i64.load 24
; WASM32-NEXT:    i64.store 8
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    local.get 6
; WASM32-NEXT:    i64.load 0
; WASM32-NEXT:    i64.store 0
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    local.get 6
; WASM32-NEXT:    i64.load 8
; WASM32-NEXT:    i64.store 8
; WASM32-NEXT:    local.get 6
; WASM32-NEXT:    i32.const 32
; WASM32-NEXT:    i32.add
; WASM32-NEXT:    global.set __stack_pointer
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: sdivrem_i128:
; WASM64:         .functype sdivrem_i128 (i64, i64, i64, i64, i64, i64) -> ()
; WASM64-NEXT:    .local i64
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    global.get __stack_pointer
; WASM64-NEXT:    i64.const 32
; WASM64-NEXT:    i64.sub
; WASM64-NEXT:    local.tee 6
; WASM64-NEXT:    global.set __stack_pointer
; WASM64-NEXT:    local.get 6
; WASM64-NEXT:    i64.const 16
; WASM64-NEXT:    i64.add
; WASM64-NEXT:    local.get 2
; WASM64-NEXT:    local.get 3
; WASM64-NEXT:    local.get 4
; WASM64-NEXT:    local.get 5
; WASM64-NEXT:    call __divti3
; WASM64-NEXT:    local.get 6
; WASM64-NEXT:    local.get 2
; WASM64-NEXT:    local.get 3
; WASM64-NEXT:    local.get 4
; WASM64-NEXT:    local.get 5
; WASM64-NEXT:    call __modti3
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 6
; WASM64-NEXT:    i64.load 16
; WASM64-NEXT:    i64.store 0
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 6
; WASM64-NEXT:    i64.load 24
; WASM64-NEXT:    i64.store 8
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    local.get 6
; WASM64-NEXT:    i64.load 0
; WASM64-NEXT:    i64.store 0
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    local.get 6
; WASM64-NEXT:    i64.load 8
; WASM64-NEXT:    i64.store 8
; WASM64-NEXT:    local.get 6
; WASM64-NEXT:    i64.const 32
; WASM64-NEXT:    i64.add
; WASM64-NEXT:    global.set __stack_pointer
; WASM64-NEXT:    # fallthrough-return
  %q = sdiv i128 %n, %d
  %r = srem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}

define void @udivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; WASM32-LABEL: udivrem_i128:
; WASM32:         .functype udivrem_i128 (i32, i32, i64, i64, i64, i64) -> ()
; WASM32-NEXT:    .local i32
; WASM32-NEXT:  # %bb.0:
; WASM32-NEXT:    global.get __stack_pointer
; WASM32-NEXT:    i32.const 32
; WASM32-NEXT:    i32.sub
; WASM32-NEXT:    local.tee 6
; WASM32-NEXT:    global.set __stack_pointer
; WASM32-NEXT:    local.get 6
; WASM32-NEXT:    i32.const 16
; WASM32-NEXT:    i32.add
; WASM32-NEXT:    local.get 2
; WASM32-NEXT:    local.get 3
; WASM32-NEXT:    local.get 4
; WASM32-NEXT:    local.get 5
; WASM32-NEXT:    call __udivti3
; WASM32-NEXT:    local.get 6
; WASM32-NEXT:    local.get 2
; WASM32-NEXT:    local.get 3
; WASM32-NEXT:    local.get 4
; WASM32-NEXT:    local.get 5
; WASM32-NEXT:    call __umodti3
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 6
; WASM32-NEXT:    i64.load 16
; WASM32-NEXT:    i64.store 0
; WASM32-NEXT:    local.get 0
; WASM32-NEXT:    local.get 6
; WASM32-NEXT:    i64.load 24
; WASM32-NEXT:    i64.store 8
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    local.get 6
; WASM32-NEXT:    i64.load 0
; WASM32-NEXT:    i64.store 0
; WASM32-NEXT:    local.get 1
; WASM32-NEXT:    local.get 6
; WASM32-NEXT:    i64.load 8
; WASM32-NEXT:    i64.store 8
; WASM32-NEXT:    local.get 6
; WASM32-NEXT:    i32.const 32
; WASM32-NEXT:    i32.add
; WASM32-NEXT:    global.set __stack_pointer
; WASM32-NEXT:    # fallthrough-return
;
; WASM64-LABEL: udivrem_i128:
; WASM64:         .functype udivrem_i128 (i64, i64, i64, i64, i64, i64) -> ()
; WASM64-NEXT:    .local i64
; WASM64-NEXT:  # %bb.0:
; WASM64-NEXT:    global.get __stack_pointer
; WASM64-NEXT:    i64.const 32
; WASM64-NEXT:    i64.sub
; WASM64-NEXT:    local.tee 6
; WASM64-NEXT:    global.set __stack_pointer
; WASM64-NEXT:    local.get 6
; WASM64-NEXT:    i64.const 16
; WASM64-NEXT:    i64.add
; WASM64-NEXT:    local.get 2
; WASM64-NEXT:    local.get 3
; WASM64-NEXT:    local.get 4
; WASM64-NEXT:    local.get 5
; WASM64-NEXT:    call __udivti3
; WASM64-NEXT:    local.get 6
; WASM64-NEXT:    local.get 2
; WASM64-NEXT:    local.get 3
; WASM64-NEXT:    local.get 4
; WASM64-NEXT:    local.get 5
; WASM64-NEXT:    call __umodti3
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 6
; WASM64-NEXT:    i64.load 16
; WASM64-NEXT:    i64.store 0
; WASM64-NEXT:    local.get 0
; WASM64-NEXT:    local.get 6
; WASM64-NEXT:    i64.load 24
; WASM64-NEXT:    i64.store 8
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    local.get 6
; WASM64-NEXT:    i64.load 0
; WASM64-NEXT:    i64.store 0
; WASM64-NEXT:    local.get 1
; WASM64-NEXT:    local.get 6
; WASM64-NEXT:    i64.load 8
; WASM64-NEXT:    i64.store 8
; WASM64-NEXT:    local.get 6
; WASM64-NEXT:    i64.const 32
; WASM64-NEXT:    i64.add
; WASM64-NEXT:    global.set __stack_pointer
; WASM64-NEXT:    # fallthrough-return
  %q = udiv i128 %n, %d
  %r = urem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}
