; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s | FileCheck %s

; Test various loads from WASM (address space 1) globals lower as intended

target triple = "wasm32-unknown-unknown"


@globalI8 = local_unnamed_addr addrspace(1) global i8 0
@globalI32 = local_unnamed_addr addrspace(1) global i32 0
@globalI64 = local_unnamed_addr addrspace(1) global i64 0

@globalF32 = local_unnamed_addr addrspace(1) global float 0.0
@globalF64 = local_unnamed_addr addrspace(1) global double 0.0

define i32 @zext_i8_i32() {
; CHECK-LABEL: zext_i8_i32:
; CHECK:         .functype zext_i8_i32 () -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI32
; CHECK-NEXT:    i32.const 255
; CHECK-NEXT:    i32.and
; CHECK-NEXT:    # fallthrough-return
  %v = load i8, ptr addrspace(1) @globalI32
  %e = zext i8 %v to i32
  ret i32 %e
}

define i32 @sext_i8_i32() {
; CHECK-LABEL: sext_i8_i32:
; CHECK:         .functype sext_i8_i32 () -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI32
; CHECK-NEXT:    i32.extend8_s
; CHECK-NEXT:    # fallthrough-return
  %v = load i8, ptr addrspace(1) @globalI32
  %e = sext i8 %v to i32
  ret i32 %e
}

define i32 @zext_i16_i32() {
; CHECK-LABEL: zext_i16_i32:
; CHECK:         .functype zext_i16_i32 () -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI32
; CHECK-NEXT:    i32.const 65535
; CHECK-NEXT:    i32.and
; CHECK-NEXT:    # fallthrough-return
  %v = load i16, ptr addrspace(1) @globalI32
  %e = zext i16 %v to i32
  ret i32 %e
}

define i32 @sext_i16_i32() {
; CHECK-LABEL: sext_i16_i32:
; CHECK:         .functype sext_i16_i32 () -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI32
; CHECK-NEXT:    i32.extend16_s
; CHECK-NEXT:    # fallthrough-return
  %v = load i16, ptr addrspace(1) @globalI32
  %e = sext i16 %v to i32
  ret i32 %e
}


define i64 @zext_i8_i64() {
; CHECK-LABEL: zext_i8_i64:
; CHECK:         .functype zext_i8_i64 () -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI64
; CHECK-NEXT:    i64.const 255
; CHECK-NEXT:    i64.and
; CHECK-NEXT:    # fallthrough-return
  %v = load i8, ptr addrspace(1) @globalI64
  %e = zext i8 %v to i64
  ret i64 %e
}

define i64 @sext_i8_i64() {
; CHECK-LABEL: sext_i8_i64:
; CHECK:         .functype sext_i8_i64 () -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI64
; CHECK-NEXT:    i64.extend8_s
; CHECK-NEXT:    # fallthrough-return
  %v = load i8, ptr addrspace(1) @globalI64
  %e = sext i8 %v to i64
  ret i64 %e
}

define i64 @zext_i16_i64() {
; CHECK-LABEL: zext_i16_i64:
; CHECK:         .functype zext_i16_i64 () -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI64
; CHECK-NEXT:    i64.const 65535
; CHECK-NEXT:    i64.and
; CHECK-NEXT:    # fallthrough-return
  %v = load i16, ptr addrspace(1) @globalI64
  %e = zext i16 %v to i64
  ret i64 %e
}

define i64 @sext_i16_i64() {
; CHECK-LABEL: sext_i16_i64:
; CHECK:         .functype sext_i16_i64 () -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI64
; CHECK-NEXT:    i64.extend16_s
; CHECK-NEXT:    # fallthrough-return
  %v = load i16, ptr addrspace(1) @globalI64
  %e = sext i16 %v to i64
  ret i64 %e
}

define i64 @zext_i32_i64() {
; CHECK-LABEL: zext_i32_i64:
; CHECK:         .functype zext_i32_i64 () -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI64
; CHECK-NEXT:    i64.const 4294967295
; CHECK-NEXT:    i64.and
; CHECK-NEXT:    # fallthrough-return
  %v = load i32, ptr addrspace(1) @globalI64
  %e = zext i32 %v to i64
  ret i64 %e
}

define i64 @sext_i32_i64() {
; CHECK-LABEL: sext_i32_i64:
; CHECK:         .functype sext_i32_i64 () -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI64
; CHECK-NEXT:    i64.extend32_s
; CHECK-NEXT:    # fallthrough-return
  %v = load i32, ptr addrspace(1) @globalI64
  %e = sext i32 %v to i64
  ret i64 %e
}


define i64 @load_i64_from_i32() {
; CHECK-LABEL: load_i64_from_i32:
; CHECK:         .functype load_i64_from_i32 () -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI32
; CHECK-NEXT:    i64.extend_i32_u
; CHECK-NEXT:    # fallthrough-return
  %v = load i64, ptr addrspace(1) @globalI32
  ret i64 %v
}

define i32 @load_i32_from_i64() {
; CHECK-LABEL: load_i32_from_i64:
; CHECK:         .functype load_i32_from_i64 () -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI64
; CHECK-NEXT:    i32.wrap_i64
; CHECK-NEXT:    # fallthrough-return
  %v = load i32, ptr addrspace(1) @globalI64
  ret i32 %v
}

define i8 @load_i8() {
; CHECK-LABEL: load_i8:
; CHECK:         .functype load_i8 () -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI8
; CHECK-NEXT:    # fallthrough-return
  %v = load i8, ptr addrspace(1) @globalI8
  ret i8 %v
}

define i64 @load_i16_from_i8_zext_to_i64() {
; CHECK-LABEL: load_i16_from_i8_zext_to_i64:
; CHECK:         .functype load_i16_from_i8_zext_to_i64 () -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI8
; CHECK-NEXT:    i64.extend_i32_u
; CHECK-NEXT:    i64.const 65535
; CHECK-NEXT:    i64.and
; CHECK-NEXT:    # fallthrough-return
  %v = load i16, ptr addrspace(1) @globalI8
  %e = zext i16 %v to i64
  ret i64 %e
}


define double @load_f64_from_f32() {
; CHECK-LABEL: load_f64_from_f32:
; CHECK:         .functype load_f64_from_f32 () -> (f64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalF32
; CHECK-NEXT:    f64.promote_f32
; CHECK-NEXT:    # fallthrough-return
  %v = load double, ptr addrspace(1) @globalF32
  ret double %v
}

define float @load_f32_from_f64() {
; CHECK-LABEL: load_f32_from_f64:
; CHECK:         .functype load_f32_from_f64 () -> (f32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalF64
; CHECK-NEXT:    f32.demote_f64
; CHECK-NEXT:    # fallthrough-return
  %v = load float, ptr addrspace(1) @globalF64
  ret float %v
}


define i8 @load_i8_from_f32() {
; CHECK-LABEL: load_i8_from_f32:
; CHECK:         .functype load_i8_from_f32 () -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalF32
; CHECK-NEXT:    i32.reinterpret_f32
; CHECK-NEXT:    # fallthrough-return
  %v = load i8, ptr addrspace(1) @globalF32
  ret i8 %v
}

define i16 @load_i16_from_f32() {
; CHECK-LABEL: load_i16_from_f32:
; CHECK:         .functype load_i16_from_f32 () -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalF32
; CHECK-NEXT:    i32.reinterpret_f32
; CHECK-NEXT:    # fallthrough-return
  %v = load i16, ptr addrspace(1) @globalF32
  ret i16 %v
}

define i32 @load_i32_from_f32() {
; CHECK-LABEL: load_i32_from_f32:
; CHECK:         .functype load_i32_from_f32 () -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalF32
; CHECK-NEXT:    i32.reinterpret_f32
; CHECK-NEXT:    # fallthrough-return
  %v = load i32, ptr addrspace(1) @globalF32
  ret i32 %v
}

define i64 @load_i64_from_f32() {
; CHECK-LABEL: load_i64_from_f32:
; CHECK:         .functype load_i64_from_f32 () -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalF32
; CHECK-NEXT:    i32.reinterpret_f32
; CHECK-NEXT:    i64.extend_i32_u
; CHECK-NEXT:    # fallthrough-return
  %v = load i64, ptr addrspace(1) @globalF32
  ret i64 %v
}

define i8 @load_i8_from_f64() {
; CHECK-LABEL: load_i8_from_f64:
; CHECK:         .functype load_i8_from_f64 () -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalF64
; CHECK-NEXT:    i64.reinterpret_f64
; CHECK-NEXT:    i32.wrap_i64
; CHECK-NEXT:    # fallthrough-return
  %v = load i8, ptr addrspace(1) @globalF64
  ret i8 %v
}

define i16 @load_i16_from_f64() {
; CHECK-LABEL: load_i16_from_f64:
; CHECK:         .functype load_i16_from_f64 () -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalF64
; CHECK-NEXT:    i64.reinterpret_f64
; CHECK-NEXT:    i32.wrap_i64
; CHECK-NEXT:    # fallthrough-return
  %v = load i16, ptr addrspace(1) @globalF64
  ret i16 %v
}

define i32 @load_i32_from_f64() {
; CHECK-LABEL: load_i32_from_f64:
; CHECK:         .functype load_i32_from_f64 () -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalF64
; CHECK-NEXT:    i64.reinterpret_f64
; CHECK-NEXT:    i32.wrap_i64
; CHECK-NEXT:    # fallthrough-return
  %v = load i32, ptr addrspace(1) @globalF64
  ret i32 %v
}

define i64 @load_i64_from_f64() {
; CHECK-LABEL: load_i64_from_f64:
; CHECK:         .functype load_i64_from_f64 () -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalF64
; CHECK-NEXT:    i64.reinterpret_f64
; CHECK-NEXT:    # fallthrough-return
  %v = load i64, ptr addrspace(1) @globalF64
  ret i64 %v
}

define float @load_f32_from_i8() {
; CHECK-LABEL: load_f32_from_i8:
; CHECK:         .functype load_f32_from_i8 () -> (f32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI8
; CHECK-NEXT:    f32.reinterpret_i32
; CHECK-NEXT:    # fallthrough-return
  %v = load float, ptr addrspace(1) @globalI8
  ret float %v
}

define float @load_f32_from_i32() {
; CHECK-LABEL: load_f32_from_i32:
; CHECK:         .functype load_f32_from_i32 () -> (f32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI32
; CHECK-NEXT:    f32.reinterpret_i32
; CHECK-NEXT:    # fallthrough-return
  %v = load float, ptr addrspace(1) @globalI32
  ret float %v
}

define float @load_f32_from_i64() {
; CHECK-LABEL: load_f32_from_i64:
; CHECK:         .functype load_f32_from_i64 () -> (f32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI64
; CHECK-NEXT:    i32.wrap_i64
; CHECK-NEXT:    f32.reinterpret_i32
; CHECK-NEXT:    # fallthrough-return
  %v = load float, ptr addrspace(1) @globalI64
  ret float %v
}

define double @load_f64_from_i8() {
; CHECK-LABEL: load_f64_from_i8:
; CHECK:         .functype load_f64_from_i8 () -> (f64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI8
; CHECK-NEXT:    i64.extend_i32_u
; CHECK-NEXT:    f64.reinterpret_i64
; CHECK-NEXT:    # fallthrough-return
  %v = load double, ptr addrspace(1) @globalI8
  ret double %v
}

define double @load_f64_from_i32() {
; CHECK-LABEL: load_f64_from_i32:
; CHECK:         .functype load_f64_from_i32 () -> (f64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI32
; CHECK-NEXT:    i64.extend_i32_u
; CHECK-NEXT:    f64.reinterpret_i64
; CHECK-NEXT:    # fallthrough-return
  %v = load double, ptr addrspace(1) @globalI32
  ret double %v
}

define double @load_f64_from_i64() {
; CHECK-LABEL: load_f64_from_i64:
; CHECK:         .functype load_f64_from_i64 () -> (f64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get globalI64
; CHECK-NEXT:    f64.reinterpret_i64
; CHECK-NEXT:    # fallthrough-return
  %v = load double, ptr addrspace(1) @globalI64
  ret double %v
}
