# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=wasm32-unknown-unknown -run-pass wasm-fix-irreducible-control-flow %s -o - | FileCheck %s
--- |
  target triple = "wasm32-unknown-unknown"

  declare i1 @should_branch(i32) #0

  declare i8 @which_branch(i32) #0

  declare i32 @opaque_callee(i32) #0

  define i32 @random_cfg1(i32 %0) #0 {
  entry:
    br label %1

  1:                                                ; preds = %entry
    %2 = phi i32 [ %0, %entry ]
    %3 = call i32 @opaque_callee(i32 %2)
    %4 = call i1 @should_branch(i32 %3)
    br i1 %4, label %5, label %9

  5:                                                ; preds = %1
    %6 = phi i32 [ %3, %1 ]
    %7 = call i32 @opaque_callee(i32 %6)
    %8 = call i1 @should_branch(i32 %7)
    br i1 %8, label %13, label %17

  9:                                                ; preds = %76, %1
    %10 = phi i32 [ %3, %1 ], [ %78, %76 ]
    %11 = call i32 @opaque_callee(i32 %10)
    %12 = call i1 @should_branch(i32 %11)
    br i1 %12, label %21, label %29

  13:                                               ; preds = %144, %106, %95, %5
    %14 = phi i32 [ %7, %5 ], [ %97, %95 ], [ %108, %106 ], [ %146, %144 ]
    %15 = call i32 @opaque_callee(i32 %14)
    %16 = call i1 @should_branch(i32 %15)
    br i1 %16, label %17, label %72

  17:                                               ; preds = %13, %5
    %18 = phi i32 [ %7, %5 ], [ %15, %13 ]
    %19 = call i32 @opaque_callee(i32 %18)
    %20 = call i1 @should_branch(i32 %19)
    br i1 %20, label %33, label %37

  21:                                               ; preds = %9
    %22 = phi i32 [ %11, %9 ]
    %23 = call i32 @opaque_callee(i32 %22)
    %24 = call i1 @should_branch(i32 %23)
    br i1 %24, label %25, label %29

  25:                                               ; preds = %21
    %26 = phi i32 [ %23, %21 ]
    %27 = call i32 @opaque_callee(i32 %26)
    %28 = call i1 @should_branch(i32 %27)
    br i1 %28, label %41, label %147

  29:                                               ; preds = %102, %41, %21, %9
    %30 = phi i32 [ %11, %9 ], [ %23, %21 ], [ %43, %41 ], [ %104, %102 ]
    %31 = call i32 @opaque_callee(i32 %30)
    %32 = call i1 @should_branch(i32 %31)
    br i1 %32, label %45, label %49

  33:                                               ; preds = %17
    %34 = phi i32 [ %19, %17 ]
    %35 = call i32 @opaque_callee(i32 %34)
    %36 = call i1 @should_branch(i32 %35)
    br i1 %36, label %53, label %68

  37:                                               ; preds = %132, %17
    %38 = phi i32 [ %19, %17 ], [ %134, %132 ]
    %39 = call i32 @opaque_callee(i32 %38)
    %40 = call i1 @should_branch(i32 %39)
    br i1 %40, label %57, label %83

  41:                                               ; preds = %25
    %42 = phi i32 [ %27, %25 ]
    %43 = call i32 @opaque_callee(i32 %42)
    %44 = call i1 @should_branch(i32 %43)
    br i1 %44, label %68, label %29

  45:                                               ; preds = %138, %87, %29
    %46 = phi i32 [ %31, %29 ], [ %89, %87 ], [ %140, %138 ]
    %47 = call i32 @opaque_callee(i32 %46)
    %48 = call i1 @should_branch(i32 %47)
    br i1 %48, label %61, label %65

  49:                                               ; preds = %29
    %50 = phi i32 [ %31, %29 ]
    %51 = call i32 @opaque_callee(i32 %50)
    %52 = call i1 @should_branch(i32 %51)
    br i1 %52, label %144, label %147

  53:                                               ; preds = %33
    %54 = phi i32 [ %35, %33 ]
    %55 = call i32 @opaque_callee(i32 %54)
    %56 = call i1 @should_branch(i32 %55)
    br i1 %56, label %113, label %116

  57:                                               ; preds = %65, %37
    %58 = phi i32 [ %39, %37 ], [ %67, %65 ]
    %59 = call i32 @opaque_callee(i32 %58)
    %60 = call i1 @should_branch(i32 %59)
    br i1 %60, label %80, label %83

  61:                                               ; preds = %45
    %62 = phi i32 [ %47, %45 ]
    %63 = call i32 @opaque_callee(i32 %62)
    %64 = call i1 @should_branch(i32 %63)
    br i1 %64, label %72, label %76

  65:                                               ; preds = %45
    %66 = phi i32 [ %47, %45 ]
    %67 = call i32 @opaque_callee(i32 %66)
    br label %57

  68:                                               ; preds = %41, %33
    %69 = phi i32 [ %35, %33 ], [ %43, %41 ]
    %70 = call i32 @opaque_callee(i32 %69)
    %71 = call i1 @should_branch(i32 %70)
    br i1 %71, label %87, label %91

  72:                                               ; preds = %61, %13
    %73 = phi i32 [ %15, %13 ], [ %63, %61 ]
    %74 = call i32 @opaque_callee(i32 %73)
    %75 = call i1 @should_branch(i32 %74)
    br i1 %75, label %126, label %106

  76:                                               ; preds = %61
    %77 = phi i32 [ %63, %61 ]
    %78 = call i32 @opaque_callee(i32 %77)
    %79 = call i1 @should_branch(i32 %78)
    br i1 %79, label %95, label %9

  80:                                               ; preds = %57
    %81 = phi i32 [ %59, %57 ]
    %82 = call i32 @opaque_callee(i32 %81)
    ret i32 %82

  83:                                               ; preds = %57, %37
    %84 = phi i32 [ %39, %37 ], [ %59, %57 ]
    %85 = call i32 @opaque_callee(i32 %84)
    %86 = call i1 @should_branch(i32 %85)
    br i1 %86, label %98, label %102

  87:                                               ; preds = %68
    %88 = phi i32 [ %70, %68 ]
    %89 = call i32 @opaque_callee(i32 %88)
    %90 = call i1 @should_branch(i32 %89)
    br i1 %90, label %132, label %45

  91:                                               ; preds = %68
    %92 = phi i32 [ %70, %68 ]
    %93 = call i32 @opaque_callee(i32 %92)
    %94 = call i1 @should_branch(i32 %93)
    br i1 %94, label %138, label %141

  95:                                               ; preds = %147, %76
    %96 = phi i32 [ %78, %76 ], [ %149, %147 ]
    %97 = call i32 @opaque_callee(i32 %96)
    br label %13

  98:                                               ; preds = %83
    %99 = phi i32 [ %85, %83 ]
    %100 = call i32 @opaque_callee(i32 %99)
    %101 = call i1 @should_branch(i32 %100)
    br i1 %101, label %106, label %110

  102:                                              ; preds = %83
    %103 = phi i32 [ %85, %83 ]
    %104 = call i32 @opaque_callee(i32 %103)
    %105 = call i1 @should_branch(i32 %104)
    br i1 %105, label %129, label %29

  106:                                              ; preds = %98, %72
    %107 = phi i32 [ %74, %72 ], [ %100, %98 ]
    %108 = call i32 @opaque_callee(i32 %107)
    %109 = call i1 @should_branch(i32 %108)
    br i1 %109, label %135, label %13

  110:                                              ; preds = %98
    %111 = phi i32 [ %100, %98 ]
    %112 = call i32 @opaque_callee(i32 %111)
    ret i32 %112

  113:                                              ; preds = %53
    %114 = phi i32 [ %55, %53 ]
    %115 = call i32 @opaque_callee(i32 %114)
    ret i32 %115

  116:                                              ; preds = %53
    %117 = phi i32 [ %55, %53 ]
    %118 = call i32 @opaque_callee(i32 %117)
    %119 = call i1 @should_branch(i32 %118)
    br i1 %119, label %120, label %123

  120:                                              ; preds = %116
    %121 = phi i32 [ %118, %116 ]
    %122 = call i32 @opaque_callee(i32 %121)
    ret i32 %122

  123:                                              ; preds = %116
    %124 = phi i32 [ %118, %116 ]
    %125 = call i32 @opaque_callee(i32 %124)
    ret i32 %125

  126:                                              ; preds = %72
    %127 = phi i32 [ %74, %72 ]
    %128 = call i32 @opaque_callee(i32 %127)
    ret i32 %128

  129:                                              ; preds = %129, %102
    %130 = phi i32 [ %104, %102 ], [ %131, %129 ]
    %131 = call i32 @opaque_callee(i32 %130)
    br label %129

  132:                                              ; preds = %87
    %133 = phi i32 [ %89, %87 ]
    %134 = call i32 @opaque_callee(i32 %133)
    br label %37

  135:                                              ; preds = %106
    %136 = phi i32 [ %108, %106 ]
    %137 = call i32 @opaque_callee(i32 %136)
    ret i32 %137

  138:                                              ; preds = %91
    %139 = phi i32 [ %93, %91 ]
    %140 = call i32 @opaque_callee(i32 %139)
    br label %45

  141:                                              ; preds = %91
    %142 = phi i32 [ %93, %91 ]
    %143 = call i32 @opaque_callee(i32 %142)
    ret i32 %143

  144:                                              ; preds = %49
    %145 = phi i32 [ %51, %49 ]
    %146 = call i32 @opaque_callee(i32 %145)
    br label %13

  147:                                              ; preds = %49, %25
    %148 = phi i32 [ %27, %25 ], [ %51, %49 ]
    %149 = call i32 @opaque_callee(i32 %148)
    br label %95
  }

  attributes #0 = { "target-features"="-atomics,+bulk-memory,+bulk-memory-opt,+call-indirect-overlong,-exception-handling,-extended-const,-fp16,-gc,-multimemory,+multivalue,+mutable-globals,+nontrapping-fptoint,+reference-types,-relaxed-simd,+sign-ext,-simd128,-tail-call,-wide-arithmetic" }

  !llvm.module.flags = !{!0, !1, !2, !3, !4, !5, !6, !7}

  !0 = !{i32 1, !"wasm-feature-bulk-memory", i32 43}
  !1 = !{i32 1, !"wasm-feature-bulk-memory-opt", i32 43}
  !2 = !{i32 1, !"wasm-feature-call-indirect-overlong", i32 43}
  !3 = !{i32 1, !"wasm-feature-multivalue", i32 43}
  !4 = !{i32 1, !"wasm-feature-mutable-globals", i32 43}
  !5 = !{i32 1, !"wasm-feature-nontrapping-fptoint", i32 43}
  !6 = !{i32 1, !"wasm-feature-reference-types", i32 43}
  !7 = !{i32 1, !"wasm-feature-sign-ext", i32 43}
...
---
name:            random_cfg1
liveins:
  - { reg: '$arguments', virtual-reg: '' }
body:             |
  ; CHECK-LABEL: name: random_cfg1
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF4:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF5:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF6:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF7:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF8:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF9:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF10:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF11:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF12:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF13:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF14:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF15:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF16:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF17:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF18:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF19:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF20:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF21:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF22:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF23:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF24:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF25:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF26:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF27:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF28:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF29:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF30:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF31:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF32:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF33:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF34:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF35:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF36:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF37:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF38:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF39:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF40:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF41:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF42:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF43:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF44:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF45:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF46:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF47:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF48:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF49:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF50:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF51:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF52:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF53:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF54:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF55:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF56:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF57:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF58:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF59:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF60:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF61:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF62:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF63:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF64:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF65:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF66:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF67:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF68:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF69:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF70:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF71:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF72:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF73:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF74:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF75:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF76:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF77:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF78:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF79:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF80:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF81:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF82:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF83:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF84:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF85:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF86:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF87:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF88:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF89:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF90:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF91:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF92:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF93:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF94:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF95:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF96:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF97:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF98:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF99:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF100:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF101:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF102:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF103:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF104:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF105:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF106:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF107:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF108:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF109:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF110:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF111:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF112:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF113:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF114:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF115:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF116:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF117:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF118:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF119:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF120:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF121:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF122:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF123:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF124:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF125:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF126:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF127:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF128:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF129:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF130:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF131:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF132:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF133:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF134:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF135:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF136:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF137:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF138:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF139:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF140:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF141:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF142:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF143:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF144:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF145:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF146:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF147:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF148:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF149:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF150:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF151:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF152:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF153:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF154:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF155:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF156:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF157:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF158:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF159:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF160:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF161:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF162:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF163:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF164:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF165:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF166:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF167:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF168:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF169:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF170:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF171:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF172:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF173:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF174:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF175:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF176:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF177:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF178:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF179:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF180:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF181:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF182:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF183:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF184:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF185:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF186:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF187:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF188:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF189:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF190:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF191:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF192:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF193:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF194:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF195:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF196:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF197:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF198:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF199:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF200:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF201:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF202:%[0-9]+]]:i32 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF202:%[0-9]+]]:i32 = COPY_I32 [[ARGUMENT_i32_]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.1, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1 (%ir-block.1):
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.44(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF201:%[0-9]+]]:i32 = COPY_I32 [[DEF202]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF200:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF201]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF199:%[0-9]+]]:i32 = CALL @should_branch, [[DEF200]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF198:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF197:%[0-9]+]]:i32 = AND_I32 [[DEF199]], [[DEF198]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF196:%[0-9]+]]:i32 = COPY_I32 [[DEF200]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF195:%[0-9]+]]:i32 = COPY_I32 [[DEF200]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.2, [[DEF197]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.44, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2 (%ir-block.5):
  ; CHECK-NEXT:   successors: %bb.46(0x40000000), %bb.47(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF194:%[0-9]+]]:i32 = COPY_I32 [[DEF196]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF193:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF194]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF192:%[0-9]+]]:i32 = CALL @should_branch, [[DEF193]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF191:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF190:%[0-9]+]]:i32 = AND_I32 [[DEF192]], [[DEF191]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF189:%[0-9]+]]:i32 = COPY_I32 [[DEF193]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF188:%[0-9]+]]:i32 = COPY_I32 [[DEF193]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.46, [[DEF190]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.47, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3 (%ir-block.9):
  ; CHECK-NEXT:   successors: %bb.7(0x40000000), %bb.50(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF187:%[0-9]+]]:i32 = COPY_I32 [[DEF195]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF186:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF187]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF185:%[0-9]+]]:i32 = CALL @should_branch, [[DEF186]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF184:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF183:%[0-9]+]]:i32 = AND_I32 [[DEF185]], [[DEF184]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF182:%[0-9]+]]:i32 = COPY_I32 [[DEF186]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF181:%[0-9]+]]:i32 = COPY_I32 [[DEF186]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.7, [[DEF183]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.50, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4 (%ir-block.13):
  ; CHECK-NEXT:   successors: %bb.5(0x40000000), %bb.20(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF180:%[0-9]+]]:i32 = COPY_I32 [[DEF189]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF179:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF180]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF178:%[0-9]+]]:i32 = CALL @should_branch, [[DEF179]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF177:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF176:%[0-9]+]]:i32 = AND_I32 [[DEF178]], [[DEF177]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF188:%[0-9]+]]:i32 = COPY_I32 [[DEF179]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF175:%[0-9]+]]:i32 = COPY_I32 [[DEF179]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.5, [[DEF176]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.20, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.43(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:i32 = CONST_I32 2, implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.43, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6 (%ir-block.17):
  ; CHECK-NEXT:   successors: %bb.10(0x40000000), %bb.11(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF174:%[0-9]+]]:i32 = COPY_I32 [[DEF188]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF173:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF174]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF172:%[0-9]+]]:i32 = CALL @should_branch, [[DEF173]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF171:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF170:%[0-9]+]]:i32 = AND_I32 [[DEF172]], [[DEF171]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF169:%[0-9]+]]:i32 = COPY_I32 [[DEF173]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF168:%[0-9]+]]:i32 = COPY_I32 [[DEF173]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.10, [[DEF170]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.11, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7 (%ir-block.21):
  ; CHECK-NEXT:   successors: %bb.8(0x40000000), %bb.50(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF167:%[0-9]+]]:i32 = COPY_I32 [[DEF182]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF166:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF167]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF165:%[0-9]+]]:i32 = CALL @should_branch, [[DEF166]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF164:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF163:%[0-9]+]]:i32 = AND_I32 [[DEF165]], [[DEF164]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF162:%[0-9]+]]:i32 = COPY_I32 [[DEF166]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF181:%[0-9]+]]:i32 = COPY_I32 [[DEF166]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.8, [[DEF163]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.50, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8 (%ir-block.25):
  ; CHECK-NEXT:   successors: %bb.12(0x40000000), %bb.42(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF161:%[0-9]+]]:i32 = COPY_I32 [[DEF162]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF160:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF161]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF159:%[0-9]+]]:i32 = CALL @should_branch, [[DEF160]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF158:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF157:%[0-9]+]]:i32 = AND_I32 [[DEF159]], [[DEF158]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF156:%[0-9]+]]:i32 = COPY_I32 [[DEF160]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF155:%[0-9]+]]:i32 = COPY_I32 [[DEF160]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.12, [[DEF157]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.42, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.9 (%ir-block.29):
  ; CHECK-NEXT:   successors: %bb.52(0x40000000), %bb.14(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF154:%[0-9]+]]:i32 = COPY_I32 [[DEF181]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF153:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF154]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF152:%[0-9]+]]:i32 = CALL @should_branch, [[DEF153]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF151:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF150:%[0-9]+]]:i32 = AND_I32 [[DEF152]], [[DEF151]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF149:%[0-9]+]]:i32 = COPY_I32 [[DEF153]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF148:%[0-9]+]]:i32 = COPY_I32 [[DEF153]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.52, [[DEF150]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.14, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.10 (%ir-block.33):
  ; CHECK-NEXT:   successors: %bb.15(0x40000000), %bb.19(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF147:%[0-9]+]]:i32 = COPY_I32 [[DEF169]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF146:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF147]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF145:%[0-9]+]]:i32 = CALL @should_branch, [[DEF146]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF144:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF143:%[0-9]+]]:i32 = AND_I32 [[DEF145]], [[DEF144]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF142:%[0-9]+]]:i32 = COPY_I32 [[DEF146]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF141:%[0-9]+]]:i32 = COPY_I32 [[DEF146]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.15, [[DEF143]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.19, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.11 (%ir-block.37):
  ; CHECK-NEXT:   successors: %bb.54(0x40000000), %bb.55(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF140:%[0-9]+]]:i32 = COPY_I32 [[DEF168]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF139:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF140]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF138:%[0-9]+]]:i32 = CALL @should_branch, [[DEF139]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF137:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF136:%[0-9]+]]:i32 = AND_I32 [[DEF138]], [[DEF137]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF135:%[0-9]+]]:i32 = COPY_I32 [[DEF139]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF134:%[0-9]+]]:i32 = COPY_I32 [[DEF139]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.54, [[DEF136]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.55, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.12 (%ir-block.41):
  ; CHECK-NEXT:   successors: %bb.19(0x40000000), %bb.50(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF133:%[0-9]+]]:i32 = COPY_I32 [[DEF156]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF132:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF133]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF131:%[0-9]+]]:i32 = CALL @should_branch, [[DEF132]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF130:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF129:%[0-9]+]]:i32 = AND_I32 [[DEF131]], [[DEF130]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF181:%[0-9]+]]:i32 = COPY_I32 [[DEF132]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF141:%[0-9]+]]:i32 = COPY_I32 [[DEF132]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.19, [[DEF129]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.50, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.13 (%ir-block.45):
  ; CHECK-NEXT:   successors: %bb.17(0x40000000), %bb.18(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF128:%[0-9]+]]:i32 = COPY_I32 [[DEF149]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF127:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF128]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF126:%[0-9]+]]:i32 = CALL @should_branch, [[DEF127]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF125:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF124:%[0-9]+]]:i32 = AND_I32 [[DEF126]], [[DEF125]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF123:%[0-9]+]]:i32 = COPY_I32 [[DEF127]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF122:%[0-9]+]]:i32 = COPY_I32 [[DEF127]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.17, [[DEF124]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.18, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.14 (%ir-block.49):
  ; CHECK-NEXT:   successors: %bb.41(0x40000000), %bb.42(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF121:%[0-9]+]]:i32 = COPY_I32 [[DEF148]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF120:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF121]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF119:%[0-9]+]]:i32 = CALL @should_branch, [[DEF120]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF118:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF117:%[0-9]+]]:i32 = AND_I32 [[DEF119]], [[DEF118]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF116:%[0-9]+]]:i32 = COPY_I32 [[DEF120]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF155:%[0-9]+]]:i32 = COPY_I32 [[DEF120]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.41, [[DEF117]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.42, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.15 (%ir-block.53):
  ; CHECK-NEXT:   successors: %bb.31(0x40000000), %bb.32(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF115:%[0-9]+]]:i32 = COPY_I32 [[DEF142]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF114:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF115]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF113:%[0-9]+]]:i32 = CALL @should_branch, [[DEF114]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF112:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF111:%[0-9]+]]:i32 = AND_I32 [[DEF113]], [[DEF112]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF110:%[0-9]+]]:i32 = COPY_I32 [[DEF114]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF109:%[0-9]+]]:i32 = COPY_I32 [[DEF114]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.31, [[DEF111]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.32, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.16 (%ir-block.57):
  ; CHECK-NEXT:   successors: %bb.22(0x40000000), %bb.57(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF108:%[0-9]+]]:i32 = COPY_I32 [[DEF135]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF107:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF108]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF106:%[0-9]+]]:i32 = CALL @should_branch, [[DEF107]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF105:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF104:%[0-9]+]]:i32 = AND_I32 [[DEF106]], [[DEF105]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF103:%[0-9]+]]:i32 = COPY_I32 [[DEF107]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF134:%[0-9]+]]:i32 = COPY_I32 [[DEF107]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.22, [[DEF104]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.57, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.17 (%ir-block.61):
  ; CHECK-NEXT:   successors: %bb.20(0x40000000), %bb.21(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF102:%[0-9]+]]:i32 = COPY_I32 [[DEF123]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF101:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF102]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF100:%[0-9]+]]:i32 = CALL @should_branch, [[DEF101]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF99:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF98:%[0-9]+]]:i32 = AND_I32 [[DEF100]], [[DEF99]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF175:%[0-9]+]]:i32 = COPY_I32 [[DEF101]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF97:%[0-9]+]]:i32 = COPY_I32 [[DEF101]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.20, [[DEF98]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.21, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.18 (%ir-block.65):
  ; CHECK-NEXT:   successors: %bb.56(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF96:%[0-9]+]]:i32 = COPY_I32 [[DEF122]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF95:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF96]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF135:%[0-9]+]]:i32 = COPY_I32 [[DEF95]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.56, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.19 (%ir-block.68):
  ; CHECK-NEXT:   successors: %bb.24(0x40000000), %bb.25(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF94:%[0-9]+]]:i32 = COPY_I32 [[DEF141]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF93:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF94]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF92:%[0-9]+]]:i32 = CALL @should_branch, [[DEF93]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF91:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF90:%[0-9]+]]:i32 = AND_I32 [[DEF92]], [[DEF91]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF89:%[0-9]+]]:i32 = COPY_I32 [[DEF93]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF88:%[0-9]+]]:i32 = COPY_I32 [[DEF93]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.24, [[DEF90]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.25, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.20 (%ir-block.72):
  ; CHECK-NEXT:   successors: %bb.35(0x40000000), %bb.29(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF87:%[0-9]+]]:i32 = COPY_I32 [[DEF175]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF86:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF87]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF85:%[0-9]+]]:i32 = CALL @should_branch, [[DEF86]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF84:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF83:%[0-9]+]]:i32 = AND_I32 [[DEF85]], [[DEF84]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF82:%[0-9]+]]:i32 = COPY_I32 [[DEF86]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF81:%[0-9]+]]:i32 = COPY_I32 [[DEF86]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.35, [[DEF83]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.29, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.21 (%ir-block.76):
  ; CHECK-NEXT:   successors: %bb.26(0x40000000), %bb.45(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF80:%[0-9]+]]:i32 = COPY_I32 [[DEF97]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF79:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF80]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF78:%[0-9]+]]:i32 = CALL @should_branch, [[DEF79]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF77:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF76:%[0-9]+]]:i32 = AND_I32 [[DEF78]], [[DEF77]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF195:%[0-9]+]]:i32 = COPY_I32 [[DEF79]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF75:%[0-9]+]]:i32 = COPY_I32 [[DEF79]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.26, [[DEF76]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.45, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.22 (%ir-block.80):
  ; CHECK-NEXT:   [[DEF74:%[0-9]+]]:i32 = COPY_I32 [[DEF103]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF73:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF74]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN [[DEF73]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.23 (%ir-block.83):
  ; CHECK-NEXT:   successors: %bb.27(0x40000000), %bb.28(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF72:%[0-9]+]]:i32 = COPY_I32 [[DEF134]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF71:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF72]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF70:%[0-9]+]]:i32 = CALL @should_branch, [[DEF71]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF69:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF68:%[0-9]+]]:i32 = AND_I32 [[DEF70]], [[DEF69]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF67:%[0-9]+]]:i32 = COPY_I32 [[DEF71]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF66:%[0-9]+]]:i32 = COPY_I32 [[DEF71]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.27, [[DEF68]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.28, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.24 (%ir-block.87):
  ; CHECK-NEXT:   successors: %bb.37(0x40000000), %bb.53(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF65:%[0-9]+]]:i32 = COPY_I32 [[DEF89]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF64:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF65]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF63:%[0-9]+]]:i32 = CALL @should_branch, [[DEF64]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF62:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF61:%[0-9]+]]:i32 = AND_I32 [[DEF63]], [[DEF62]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF149:%[0-9]+]]:i32 = COPY_I32 [[DEF64]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF60:%[0-9]+]]:i32 = COPY_I32 [[DEF64]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.37, [[DEF61]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.53, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.25 (%ir-block.91):
  ; CHECK-NEXT:   successors: %bb.39(0x40000000), %bb.40(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF59:%[0-9]+]]:i32 = COPY_I32 [[DEF88]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF58:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF59]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF57:%[0-9]+]]:i32 = CALL @should_branch, [[DEF58]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF56:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF55:%[0-9]+]]:i32 = AND_I32 [[DEF57]], [[DEF56]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF54:%[0-9]+]]:i32 = COPY_I32 [[DEF58]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF53:%[0-9]+]]:i32 = COPY_I32 [[DEF58]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.39, [[DEF55]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.40, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.26 (%ir-block.95):
  ; CHECK-NEXT:   successors: %bb.48(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF52:%[0-9]+]]:i32 = COPY_I32 [[DEF75]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF51:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF52]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF189:%[0-9]+]]:i32 = COPY_I32 [[DEF51]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.48, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.27 (%ir-block.98):
  ; CHECK-NEXT:   successors: %bb.29(0x40000000), %bb.30(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF50:%[0-9]+]]:i32 = COPY_I32 [[DEF67]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF49:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF50]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF48:%[0-9]+]]:i32 = CALL @should_branch, [[DEF49]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF47:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF46:%[0-9]+]]:i32 = AND_I32 [[DEF48]], [[DEF47]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF82:%[0-9]+]]:i32 = COPY_I32 [[DEF49]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF45:%[0-9]+]]:i32 = COPY_I32 [[DEF49]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.29, [[DEF46]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.30, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.28 (%ir-block.102):
  ; CHECK-NEXT:   successors: %bb.36(0x40000000), %bb.51(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF44:%[0-9]+]]:i32 = COPY_I32 [[DEF66]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF43:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF44]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF42:%[0-9]+]]:i32 = CALL @should_branch, [[DEF43]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF41:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF40:%[0-9]+]]:i32 = AND_I32 [[DEF42]], [[DEF41]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF181:%[0-9]+]]:i32 = COPY_I32 [[DEF43]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF39:%[0-9]+]]:i32 = COPY_I32 [[DEF43]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.36, [[DEF40]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.51, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.29 (%ir-block.106):
  ; CHECK-NEXT:   successors: %bb.38(0x40000000), %bb.48(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF38:%[0-9]+]]:i32 = COPY_I32 [[DEF82]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF37:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF38]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF36:%[0-9]+]]:i32 = CALL @should_branch, [[DEF37]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF35:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF34:%[0-9]+]]:i32 = AND_I32 [[DEF36]], [[DEF35]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF189:%[0-9]+]]:i32 = COPY_I32 [[DEF37]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF33:%[0-9]+]]:i32 = COPY_I32 [[DEF37]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.38, [[DEF34]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.48, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.30 (%ir-block.110):
  ; CHECK-NEXT:   [[DEF32:%[0-9]+]]:i32 = COPY_I32 [[DEF45]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF31:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF32]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN [[DEF31]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.31 (%ir-block.113):
  ; CHECK-NEXT:   [[DEF30:%[0-9]+]]:i32 = COPY_I32 [[DEF110]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF29:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF30]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN [[DEF29]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.32 (%ir-block.116):
  ; CHECK-NEXT:   successors: %bb.33(0x40000000), %bb.34(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF28:%[0-9]+]]:i32 = COPY_I32 [[DEF109]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF27:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF28]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF26:%[0-9]+]]:i32 = CALL @should_branch, [[DEF27]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF25:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   [[DEF24:%[0-9]+]]:i32 = AND_I32 [[DEF26]], [[DEF25]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF23:%[0-9]+]]:i32 = COPY_I32 [[DEF27]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF22:%[0-9]+]]:i32 = COPY_I32 [[DEF27]], implicit-def $arguments
  ; CHECK-NEXT:   BR_IF %bb.33, [[DEF24]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.34, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.33 (%ir-block.120):
  ; CHECK-NEXT:   [[DEF21:%[0-9]+]]:i32 = COPY_I32 [[DEF23]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF20:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF21]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN [[DEF20]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.34 (%ir-block.123):
  ; CHECK-NEXT:   [[DEF19:%[0-9]+]]:i32 = COPY_I32 [[DEF22]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF18:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF19]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN [[DEF18]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.35 (%ir-block.126):
  ; CHECK-NEXT:   [[DEF17:%[0-9]+]]:i32 = COPY_I32 [[DEF81]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF16:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF17]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN [[DEF16]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.36 (%ir-block.129):
  ; CHECK-NEXT:   successors: %bb.36(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF15:%[0-9]+]]:i32 = COPY_I32 [[DEF39]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF14:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF15]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF39:%[0-9]+]]:i32 = COPY_I32 [[DEF14]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.36, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.37 (%ir-block.132):
  ; CHECK-NEXT:   successors: %bb.11(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF13:%[0-9]+]]:i32 = COPY_I32 [[DEF60]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF12:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF13]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF168:%[0-9]+]]:i32 = COPY_I32 [[DEF12]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.11, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.38 (%ir-block.135):
  ; CHECK-NEXT:   [[DEF11:%[0-9]+]]:i32 = COPY_I32 [[DEF33]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF10:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF11]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN [[DEF10]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.39 (%ir-block.138):
  ; CHECK-NEXT:   successors: %bb.53(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF9:%[0-9]+]]:i32 = COPY_I32 [[DEF54]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF8:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF9]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF149:%[0-9]+]]:i32 = COPY_I32 [[DEF8]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.53, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.40 (%ir-block.141):
  ; CHECK-NEXT:   [[DEF7:%[0-9]+]]:i32 = COPY_I32 [[DEF53]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF6:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF7]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   RETURN [[DEF6]], implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.41 (%ir-block.144):
  ; CHECK-NEXT:   successors: %bb.48(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF5:%[0-9]+]]:i32 = COPY_I32 [[DEF116]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF4:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF5]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF189:%[0-9]+]]:i32 = COPY_I32 [[DEF4]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.48, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.42 (%ir-block.147):
  ; CHECK-NEXT:   successors: %bb.26(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:i32 = COPY_I32 [[DEF155]], implicit-def $arguments
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:i32 = CALL @opaque_callee, [[DEF3]], implicit-def $arguments, implicit $sp32, implicit $sp64
  ; CHECK-NEXT:   [[DEF75:%[0-9]+]]:i32 = COPY_I32 [[DEF2]], implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.26, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.43:
  ; CHECK-NEXT:   successors: %bb.3(0x2aaaaaaa), %bb.4(0x2aaaaaaa), %bb.6(0x2aaaaaaa)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BR_TABLE_I32 [[DEF1]], %bb.3, %bb.4, %bb.6, %bb.6, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.44:
  ; CHECK-NEXT:   successors: %bb.43(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:i32 = CONST_I32 0, implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.43, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.45:
  ; CHECK-NEXT:   successors: %bb.43(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:i32 = CONST_I32 0, implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.43, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.46:
  ; CHECK-NEXT:   successors: %bb.43(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.43, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.47:
  ; CHECK-NEXT:   successors: %bb.43(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:i32 = CONST_I32 2, implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.43, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.48:
  ; CHECK-NEXT:   successors: %bb.43(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.43, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.49:
  ; CHECK-NEXT:   successors: %bb.9(0x20000000), %bb.13(0x20000000), %bb.16(0x20000000), %bb.23(0x20000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BR_TABLE_I32 [[DEF]], %bb.9, %bb.13, %bb.16, %bb.23, %bb.23, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.50:
  ; CHECK-NEXT:   successors: %bb.49(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:i32 = CONST_I32 0, implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.49, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.51:
  ; CHECK-NEXT:   successors: %bb.49(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:i32 = CONST_I32 0, implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.49, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.52:
  ; CHECK-NEXT:   successors: %bb.49(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.49, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.53:
  ; CHECK-NEXT:   successors: %bb.49(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:i32 = CONST_I32 1, implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.49, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.54:
  ; CHECK-NEXT:   successors: %bb.49(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:i32 = CONST_I32 2, implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.49, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.55:
  ; CHECK-NEXT:   successors: %bb.49(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:i32 = CONST_I32 3, implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.49, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.56:
  ; CHECK-NEXT:   successors: %bb.49(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:i32 = CONST_I32 2, implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.49, implicit-def $arguments
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.57:
  ; CHECK-NEXT:   successors: %bb.49(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:i32 = CONST_I32 3, implicit-def $arguments
  ; CHECK-NEXT:   BR %bb.49, implicit-def $arguments
  bb.0.entry:
    successors: %bb.1(0x80000000)
    liveins: $arguments

    %74:i32 = ARGUMENT_i32 0, implicit $arguments
    %228:i32 = COPY_I32 %74, implicit-def $arguments
    BR %bb.1, implicit-def $arguments

  bb.1 (%ir-block.1):
    successors: %bb.2(0x40000000), %bb.3(0x40000000)

    %0:i32 = COPY_I32 %228, implicit-def $arguments
    %79:i32 = CALL @opaque_callee, %0, implicit-def $arguments, implicit $sp32, implicit $sp64
    %78:i32 = CALL @should_branch, %79, implicit-def $arguments, implicit $sp32, implicit $sp64
    %76:i32 = CONST_I32 1, implicit-def $arguments
    %77:i32 = AND_I32 %78, %76, implicit-def $arguments
    %229:i32 = COPY_I32 %79, implicit-def $arguments
    %230:i32 = COPY_I32 %79, implicit-def $arguments
    BR_IF %bb.2, %77, implicit-def $arguments
    BR %bb.3, implicit-def $arguments

  bb.2 (%ir-block.5):
    successors: %bb.4(0x40000000), %bb.5(0x40000000)

    %2:i32 = COPY_I32 %229, implicit-def $arguments
    %84:i32 = CALL @opaque_callee, %2, implicit-def $arguments, implicit $sp32, implicit $sp64
    %83:i32 = CALL @should_branch, %84, implicit-def $arguments, implicit $sp32, implicit $sp64
    %81:i32 = CONST_I32 1, implicit-def $arguments
    %82:i32 = AND_I32 %83, %81, implicit-def $arguments
    %231:i32 = COPY_I32 %84, implicit-def $arguments
    %232:i32 = COPY_I32 %84, implicit-def $arguments
    BR_IF %bb.4, %82, implicit-def $arguments
    BR %bb.5, implicit-def $arguments

  bb.3 (%ir-block.9):
    successors: %bb.6(0x40000000), %bb.8(0x40000000)

    %4:i32 = COPY_I32 %230, implicit-def $arguments
    %170:i32 = CALL @opaque_callee, %4, implicit-def $arguments, implicit $sp32, implicit $sp64
    %169:i32 = CALL @should_branch, %170, implicit-def $arguments, implicit $sp32, implicit $sp64
    %167:i32 = CONST_I32 1, implicit-def $arguments
    %168:i32 = AND_I32 %169, %167, implicit-def $arguments
    %233:i32 = COPY_I32 %170, implicit-def $arguments
    %235:i32 = COPY_I32 %170, implicit-def $arguments
    BR_IF %bb.6, %168, implicit-def $arguments
    BR %bb.8, implicit-def $arguments

  bb.4 (%ir-block.13):
    successors: %bb.5(0x40000000), %bb.19(0x40000000)

    %6:i32 = COPY_I32 %231, implicit-def $arguments
    %89:i32 = CALL @opaque_callee, %6, implicit-def $arguments, implicit $sp32, implicit $sp64
    %88:i32 = CALL @should_branch, %89, implicit-def $arguments, implicit $sp32, implicit $sp64
    %86:i32 = CONST_I32 1, implicit-def $arguments
    %87:i32 = AND_I32 %88, %86, implicit-def $arguments
    %232:i32 = COPY_I32 %89, implicit-def $arguments
    %246:i32 = COPY_I32 %89, implicit-def $arguments
    BR_IF %bb.5, %87, implicit-def $arguments
    BR %bb.19, implicit-def $arguments

  bb.5 (%ir-block.17):
    successors: %bb.9(0x40000000), %bb.10(0x40000000)

    %8:i32 = COPY_I32 %232, implicit-def $arguments
    %94:i32 = CALL @opaque_callee, %8, implicit-def $arguments, implicit $sp32, implicit $sp64
    %93:i32 = CALL @should_branch, %94, implicit-def $arguments, implicit $sp32, implicit $sp64
    %91:i32 = CONST_I32 1, implicit-def $arguments
    %92:i32 = AND_I32 %93, %91, implicit-def $arguments
    %236:i32 = COPY_I32 %94, implicit-def $arguments
    %237:i32 = COPY_I32 %94, implicit-def $arguments
    BR_IF %bb.9, %92, implicit-def $arguments
    BR %bb.10, implicit-def $arguments

  bb.6 (%ir-block.21):
    successors: %bb.7(0x40000000), %bb.8(0x40000000)

    %10:i32 = COPY_I32 %233, implicit-def $arguments
    %175:i32 = CALL @opaque_callee, %10, implicit-def $arguments, implicit $sp32, implicit $sp64
    %174:i32 = CALL @should_branch, %175, implicit-def $arguments, implicit $sp32, implicit $sp64
    %172:i32 = CONST_I32 1, implicit-def $arguments
    %173:i32 = AND_I32 %174, %172, implicit-def $arguments
    %234:i32 = COPY_I32 %175, implicit-def $arguments
    %235:i32 = COPY_I32 %175, implicit-def $arguments
    BR_IF %bb.7, %173, implicit-def $arguments
    BR %bb.8, implicit-def $arguments

  bb.7 (%ir-block.25):
    successors: %bb.11(0x40000000), %bb.41(0x40000000)

    %12:i32 = COPY_I32 %234, implicit-def $arguments
    %180:i32 = CALL @opaque_callee, %12, implicit-def $arguments, implicit $sp32, implicit $sp64
    %179:i32 = CALL @should_branch, %180, implicit-def $arguments, implicit $sp32, implicit $sp64
    %177:i32 = CONST_I32 1, implicit-def $arguments
    %178:i32 = AND_I32 %179, %177, implicit-def $arguments
    %238:i32 = COPY_I32 %180, implicit-def $arguments
    %268:i32 = COPY_I32 %180, implicit-def $arguments
    BR_IF %bb.11, %178, implicit-def $arguments
    BR %bb.41, implicit-def $arguments

  bb.8 (%ir-block.29):
    successors: %bb.12(0x40000000), %bb.13(0x40000000)

    %14:i32 = COPY_I32 %235, implicit-def $arguments
    %143:i32 = CALL @opaque_callee, %14, implicit-def $arguments, implicit $sp32, implicit $sp64
    %142:i32 = CALL @should_branch, %143, implicit-def $arguments, implicit $sp32, implicit $sp64
    %140:i32 = CONST_I32 1, implicit-def $arguments
    %141:i32 = AND_I32 %142, %140, implicit-def $arguments
    %239:i32 = COPY_I32 %143, implicit-def $arguments
    %240:i32 = COPY_I32 %143, implicit-def $arguments
    BR_IF %bb.12, %141, implicit-def $arguments
    BR %bb.13, implicit-def $arguments

  bb.9 (%ir-block.33):
    successors: %bb.14(0x40000000), %bb.18(0x40000000)

    %16:i32 = COPY_I32 %236, implicit-def $arguments
    %99:i32 = CALL @opaque_callee, %16, implicit-def $arguments, implicit $sp32, implicit $sp64
    %98:i32 = CALL @should_branch, %99, implicit-def $arguments, implicit $sp32, implicit $sp64
    %96:i32 = CONST_I32 1, implicit-def $arguments
    %97:i32 = AND_I32 %98, %96, implicit-def $arguments
    %241:i32 = COPY_I32 %99, implicit-def $arguments
    %245:i32 = COPY_I32 %99, implicit-def $arguments
    BR_IF %bb.14, %97, implicit-def $arguments
    BR %bb.18, implicit-def $arguments

  bb.10 (%ir-block.37):
    successors: %bb.15(0x40000000), %bb.22(0x40000000)

    %18:i32 = COPY_I32 %237, implicit-def $arguments
    %123:i32 = CALL @opaque_callee, %18, implicit-def $arguments, implicit $sp32, implicit $sp64
    %122:i32 = CALL @should_branch, %123, implicit-def $arguments, implicit $sp32, implicit $sp64
    %120:i32 = CONST_I32 1, implicit-def $arguments
    %121:i32 = AND_I32 %122, %120, implicit-def $arguments
    %242:i32 = COPY_I32 %123, implicit-def $arguments
    %249:i32 = COPY_I32 %123, implicit-def $arguments
    BR_IF %bb.15, %121, implicit-def $arguments
    BR %bb.22, implicit-def $arguments

  bb.11 (%ir-block.41):
    successors: %bb.18(0x40000000), %bb.8(0x40000000)

    %20:i32 = COPY_I32 %238, implicit-def $arguments
    %186:i32 = CALL @opaque_callee, %20, implicit-def $arguments, implicit $sp32, implicit $sp64
    %185:i32 = CALL @should_branch, %186, implicit-def $arguments, implicit $sp32, implicit $sp64
    %183:i32 = CONST_I32 1, implicit-def $arguments
    %184:i32 = AND_I32 %185, %183, implicit-def $arguments
    %235:i32 = COPY_I32 %186, implicit-def $arguments
    %245:i32 = COPY_I32 %186, implicit-def $arguments
    BR_IF %bb.18, %184, implicit-def $arguments
    BR %bb.8, implicit-def $arguments

  bb.12 (%ir-block.45):
    successors: %bb.16(0x40000000), %bb.17(0x40000000)

    %22:i32 = COPY_I32 %239, implicit-def $arguments
    %154:i32 = CALL @opaque_callee, %22, implicit-def $arguments, implicit $sp32, implicit $sp64
    %153:i32 = CALL @should_branch, %154, implicit-def $arguments, implicit $sp32, implicit $sp64
    %151:i32 = CONST_I32 1, implicit-def $arguments
    %152:i32 = AND_I32 %153, %151, implicit-def $arguments
    %243:i32 = COPY_I32 %154, implicit-def $arguments
    %244:i32 = COPY_I32 %154, implicit-def $arguments
    BR_IF %bb.16, %152, implicit-def $arguments
    BR %bb.17, implicit-def $arguments

  bb.13 (%ir-block.49):
    successors: %bb.40(0x40000000), %bb.41(0x40000000)

    %24:i32 = COPY_I32 %240, implicit-def $arguments
    %148:i32 = CALL @opaque_callee, %24, implicit-def $arguments, implicit $sp32, implicit $sp64
    %147:i32 = CALL @should_branch, %148, implicit-def $arguments, implicit $sp32, implicit $sp64
    %145:i32 = CONST_I32 1, implicit-def $arguments
    %146:i32 = AND_I32 %147, %145, implicit-def $arguments
    %267:i32 = COPY_I32 %148, implicit-def $arguments
    %268:i32 = COPY_I32 %148, implicit-def $arguments
    BR_IF %bb.40, %146, implicit-def $arguments
    BR %bb.41, implicit-def $arguments

  bb.14 (%ir-block.53):
    successors: %bb.30(0x40000000), %bb.31(0x40000000)

    %26:i32 = COPY_I32 %241, implicit-def $arguments
    %216:i32 = CALL @opaque_callee, %26, implicit-def $arguments, implicit $sp32, implicit $sp64
    %215:i32 = CALL @should_branch, %216, implicit-def $arguments, implicit $sp32, implicit $sp64
    %213:i32 = CONST_I32 1, implicit-def $arguments
    %214:i32 = AND_I32 %215, %213, implicit-def $arguments
    %257:i32 = COPY_I32 %216, implicit-def $arguments
    %258:i32 = COPY_I32 %216, implicit-def $arguments
    BR_IF %bb.30, %214, implicit-def $arguments
    BR %bb.31, implicit-def $arguments

  bb.15 (%ir-block.57):
    successors: %bb.21(0x40000000), %bb.22(0x40000000)

    %28:i32 = COPY_I32 %242, implicit-def $arguments
    %128:i32 = CALL @opaque_callee, %28, implicit-def $arguments, implicit $sp32, implicit $sp64
    %127:i32 = CALL @should_branch, %128, implicit-def $arguments, implicit $sp32, implicit $sp64
    %125:i32 = CONST_I32 1, implicit-def $arguments
    %126:i32 = AND_I32 %127, %125, implicit-def $arguments
    %248:i32 = COPY_I32 %128, implicit-def $arguments
    %249:i32 = COPY_I32 %128, implicit-def $arguments
    BR_IF %bb.21, %126, implicit-def $arguments
    BR %bb.22, implicit-def $arguments

  bb.16 (%ir-block.61):
    successors: %bb.19(0x40000000), %bb.20(0x40000000)

    %30:i32 = COPY_I32 %243, implicit-def $arguments
    %160:i32 = CALL @opaque_callee, %30, implicit-def $arguments, implicit $sp32, implicit $sp64
    %159:i32 = CALL @should_branch, %160, implicit-def $arguments, implicit $sp32, implicit $sp64
    %157:i32 = CONST_I32 1, implicit-def $arguments
    %158:i32 = AND_I32 %159, %157, implicit-def $arguments
    %246:i32 = COPY_I32 %160, implicit-def $arguments
    %247:i32 = COPY_I32 %160, implicit-def $arguments
    BR_IF %bb.19, %158, implicit-def $arguments
    BR %bb.20, implicit-def $arguments

  bb.17 (%ir-block.65):
    successors: %bb.15(0x80000000)

    %32:i32 = COPY_I32 %244, implicit-def $arguments
    %155:i32 = CALL @opaque_callee, %32, implicit-def $arguments, implicit $sp32, implicit $sp64
    %242:i32 = COPY_I32 %155, implicit-def $arguments
    BR %bb.15, implicit-def $arguments

  bb.18 (%ir-block.68):
    successors: %bb.23(0x40000000), %bb.24(0x40000000)

    %34:i32 = COPY_I32 %245, implicit-def $arguments
    %104:i32 = CALL @opaque_callee, %34, implicit-def $arguments, implicit $sp32, implicit $sp64
    %103:i32 = CALL @should_branch, %104, implicit-def $arguments, implicit $sp32, implicit $sp64
    %101:i32 = CONST_I32 1, implicit-def $arguments
    %102:i32 = AND_I32 %103, %101, implicit-def $arguments
    %250:i32 = COPY_I32 %104, implicit-def $arguments
    %251:i32 = COPY_I32 %104, implicit-def $arguments
    BR_IF %bb.23, %102, implicit-def $arguments
    BR %bb.24, implicit-def $arguments

  bb.19 (%ir-block.72):
    successors: %bb.34(0x40000000), %bb.28(0x40000000)

    %36:i32 = COPY_I32 %246, implicit-def $arguments
    %192:i32 = CALL @opaque_callee, %36, implicit-def $arguments, implicit $sp32, implicit $sp64
    %191:i32 = CALL @should_branch, %192, implicit-def $arguments, implicit $sp32, implicit $sp64
    %189:i32 = CONST_I32 1, implicit-def $arguments
    %190:i32 = AND_I32 %191, %189, implicit-def $arguments
    %255:i32 = COPY_I32 %192, implicit-def $arguments
    %261:i32 = COPY_I32 %192, implicit-def $arguments
    BR_IF %bb.34, %190, implicit-def $arguments
    BR %bb.28, implicit-def $arguments

  bb.20 (%ir-block.76):
    successors: %bb.25(0x40000000), %bb.3(0x40000000)

    %38:i32 = COPY_I32 %247, implicit-def $arguments
    %165:i32 = CALL @opaque_callee, %38, implicit-def $arguments, implicit $sp32, implicit $sp64
    %164:i32 = CALL @should_branch, %165, implicit-def $arguments, implicit $sp32, implicit $sp64
    %162:i32 = CONST_I32 1, implicit-def $arguments
    %163:i32 = AND_I32 %164, %162, implicit-def $arguments
    %230:i32 = COPY_I32 %165, implicit-def $arguments
    %252:i32 = COPY_I32 %165, implicit-def $arguments
    BR_IF %bb.25, %163, implicit-def $arguments
    BR %bb.3, implicit-def $arguments

  bb.21 (%ir-block.80):
    %40:i32 = COPY_I32 %248, implicit-def $arguments
    %211:i32 = CALL @opaque_callee, %40, implicit-def $arguments, implicit $sp32, implicit $sp64
    RETURN %211, implicit-def $arguments

  bb.22 (%ir-block.83):
    successors: %bb.26(0x40000000), %bb.27(0x40000000)

    %41:i32 = COPY_I32 %249, implicit-def $arguments
    %133:i32 = CALL @opaque_callee, %41, implicit-def $arguments, implicit $sp32, implicit $sp64
    %132:i32 = CALL @should_branch, %133, implicit-def $arguments, implicit $sp32, implicit $sp64
    %130:i32 = CONST_I32 1, implicit-def $arguments
    %131:i32 = AND_I32 %132, %130, implicit-def $arguments
    %253:i32 = COPY_I32 %133, implicit-def $arguments
    %254:i32 = COPY_I32 %133, implicit-def $arguments
    BR_IF %bb.26, %131, implicit-def $arguments
    BR %bb.27, implicit-def $arguments

  bb.23 (%ir-block.87):
    successors: %bb.36(0x40000000), %bb.12(0x40000000)

    %43:i32 = COPY_I32 %250, implicit-def $arguments
    %117:i32 = CALL @opaque_callee, %43, implicit-def $arguments, implicit $sp32, implicit $sp64
    %116:i32 = CALL @should_branch, %117, implicit-def $arguments, implicit $sp32, implicit $sp64
    %114:i32 = CONST_I32 1, implicit-def $arguments
    %115:i32 = AND_I32 %116, %114, implicit-def $arguments
    %239:i32 = COPY_I32 %117, implicit-def $arguments
    %263:i32 = COPY_I32 %117, implicit-def $arguments
    BR_IF %bb.36, %115, implicit-def $arguments
    BR %bb.12, implicit-def $arguments

  bb.24 (%ir-block.91):
    successors: %bb.38(0x40000000), %bb.39(0x40000000)

    %45:i32 = COPY_I32 %251, implicit-def $arguments
    %109:i32 = CALL @opaque_callee, %45, implicit-def $arguments, implicit $sp32, implicit $sp64
    %108:i32 = CALL @should_branch, %109, implicit-def $arguments, implicit $sp32, implicit $sp64
    %106:i32 = CONST_I32 1, implicit-def $arguments
    %107:i32 = AND_I32 %108, %106, implicit-def $arguments
    %265:i32 = COPY_I32 %109, implicit-def $arguments
    %266:i32 = COPY_I32 %109, implicit-def $arguments
    BR_IF %bb.38, %107, implicit-def $arguments
    BR %bb.39, implicit-def $arguments

  bb.25 (%ir-block.95):
    successors: %bb.4(0x80000000)

    %47:i32 = COPY_I32 %252, implicit-def $arguments
    %187:i32 = CALL @opaque_callee, %47, implicit-def $arguments, implicit $sp32, implicit $sp64
    %231:i32 = COPY_I32 %187, implicit-def $arguments
    BR %bb.4, implicit-def $arguments

  bb.26 (%ir-block.98):
    successors: %bb.28(0x40000000), %bb.29(0x40000000)

    %49:i32 = COPY_I32 %253, implicit-def $arguments
    %200:i32 = CALL @opaque_callee, %49, implicit-def $arguments, implicit $sp32, implicit $sp64
    %199:i32 = CALL @should_branch, %200, implicit-def $arguments, implicit $sp32, implicit $sp64
    %197:i32 = CONST_I32 1, implicit-def $arguments
    %198:i32 = AND_I32 %199, %197, implicit-def $arguments
    %255:i32 = COPY_I32 %200, implicit-def $arguments
    %256:i32 = COPY_I32 %200, implicit-def $arguments
    BR_IF %bb.28, %198, implicit-def $arguments
    BR %bb.29, implicit-def $arguments

  bb.27 (%ir-block.102):
    successors: %bb.35(0x40000000), %bb.8(0x40000000)

    %51:i32 = COPY_I32 %254, implicit-def $arguments
    %138:i32 = CALL @opaque_callee, %51, implicit-def $arguments, implicit $sp32, implicit $sp64
    %137:i32 = CALL @should_branch, %138, implicit-def $arguments, implicit $sp32, implicit $sp64
    %135:i32 = CONST_I32 1, implicit-def $arguments
    %136:i32 = AND_I32 %137, %135, implicit-def $arguments
    %235:i32 = COPY_I32 %138, implicit-def $arguments
    %262:i32 = COPY_I32 %138, implicit-def $arguments
    BR_IF %bb.35, %136, implicit-def $arguments
    BR %bb.8, implicit-def $arguments

  bb.28 (%ir-block.106):
    successors: %bb.37(0x40000000), %bb.4(0x40000000)

    %53:i32 = COPY_I32 %255, implicit-def $arguments
    %207:i32 = CALL @opaque_callee, %53, implicit-def $arguments, implicit $sp32, implicit $sp64
    %206:i32 = CALL @should_branch, %207, implicit-def $arguments, implicit $sp32, implicit $sp64
    %204:i32 = CONST_I32 1, implicit-def $arguments
    %205:i32 = AND_I32 %206, %204, implicit-def $arguments
    %231:i32 = COPY_I32 %207, implicit-def $arguments
    %264:i32 = COPY_I32 %207, implicit-def $arguments
    BR_IF %bb.37, %205, implicit-def $arguments
    BR %bb.4, implicit-def $arguments

  bb.29 (%ir-block.110):
    %55:i32 = COPY_I32 %256, implicit-def $arguments
    %202:i32 = CALL @opaque_callee, %55, implicit-def $arguments, implicit $sp32, implicit $sp64
    RETURN %202, implicit-def $arguments

  bb.30 (%ir-block.113):
    %56:i32 = COPY_I32 %257, implicit-def $arguments
    %227:i32 = CALL @opaque_callee, %56, implicit-def $arguments, implicit $sp32, implicit $sp64
    RETURN %227, implicit-def $arguments

  bb.31 (%ir-block.116):
    successors: %bb.32(0x40000000), %bb.33(0x40000000)

    %57:i32 = COPY_I32 %258, implicit-def $arguments
    %221:i32 = CALL @opaque_callee, %57, implicit-def $arguments, implicit $sp32, implicit $sp64
    %220:i32 = CALL @should_branch, %221, implicit-def $arguments, implicit $sp32, implicit $sp64
    %218:i32 = CONST_I32 1, implicit-def $arguments
    %219:i32 = AND_I32 %220, %218, implicit-def $arguments
    %259:i32 = COPY_I32 %221, implicit-def $arguments
    %260:i32 = COPY_I32 %221, implicit-def $arguments
    BR_IF %bb.32, %219, implicit-def $arguments
    BR %bb.33, implicit-def $arguments

  bb.32 (%ir-block.120):
    %59:i32 = COPY_I32 %259, implicit-def $arguments
    %225:i32 = CALL @opaque_callee, %59, implicit-def $arguments, implicit $sp32, implicit $sp64
    RETURN %225, implicit-def $arguments

  bb.33 (%ir-block.123):
    %60:i32 = COPY_I32 %260, implicit-def $arguments
    %223:i32 = CALL @opaque_callee, %60, implicit-def $arguments, implicit $sp32, implicit $sp64
    RETURN %223, implicit-def $arguments

  bb.34 (%ir-block.126):
    %61:i32 = COPY_I32 %261, implicit-def $arguments
    %194:i32 = CALL @opaque_callee, %61, implicit-def $arguments, implicit $sp32, implicit $sp64
    RETURN %194, implicit-def $arguments

  bb.35 (%ir-block.129):
    successors: %bb.35(0x80000000)

    %62:i32 = COPY_I32 %262, implicit-def $arguments
    %195:i32 = CALL @opaque_callee, %62, implicit-def $arguments, implicit $sp32, implicit $sp64
    %262:i32 = COPY_I32 %195, implicit-def $arguments
    BR %bb.35, implicit-def $arguments

  bb.36 (%ir-block.132):
    successors: %bb.10(0x80000000)

    %64:i32 = COPY_I32 %263, implicit-def $arguments
    %118:i32 = CALL @opaque_callee, %64, implicit-def $arguments, implicit $sp32, implicit $sp64
    %237:i32 = COPY_I32 %118, implicit-def $arguments
    BR %bb.10, implicit-def $arguments

  bb.37 (%ir-block.135):
    %66:i32 = COPY_I32 %264, implicit-def $arguments
    %209:i32 = CALL @opaque_callee, %66, implicit-def $arguments, implicit $sp32, implicit $sp64
    RETURN %209, implicit-def $arguments

  bb.38 (%ir-block.138):
    successors: %bb.12(0x80000000)

    %67:i32 = COPY_I32 %265, implicit-def $arguments
    %112:i32 = CALL @opaque_callee, %67, implicit-def $arguments, implicit $sp32, implicit $sp64
    %239:i32 = COPY_I32 %112, implicit-def $arguments
    BR %bb.12, implicit-def $arguments

  bb.39 (%ir-block.141):
    %69:i32 = COPY_I32 %266, implicit-def $arguments
    %111:i32 = CALL @opaque_callee, %69, implicit-def $arguments, implicit $sp32, implicit $sp64
    RETURN %111, implicit-def $arguments

  bb.40 (%ir-block.144):
    successors: %bb.4(0x80000000)

    %70:i32 = COPY_I32 %267, implicit-def $arguments
    %149:i32 = CALL @opaque_callee, %70, implicit-def $arguments, implicit $sp32, implicit $sp64
    %231:i32 = COPY_I32 %149, implicit-def $arguments
    BR %bb.4, implicit-def $arguments

  bb.41 (%ir-block.147):
    successors: %bb.25(0x80000000)

    %72:i32 = COPY_I32 %268, implicit-def $arguments
    %181:i32 = CALL @opaque_callee, %72, implicit-def $arguments, implicit $sp32, implicit $sp64
    %252:i32 = COPY_I32 %181, implicit-def $arguments
    BR %bb.25, implicit-def $arguments
...
