; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -verify-machineinstrs -mattr=+simd128 | FileCheck %s

; Test that and(vnot(x), sext(cmp)) lowers to v128.andnot.
;
; DAGCombiner canonicalizes and(x, sext(cmp)) into vselect(cmp, x, zero).
; When x is vnot(y), this produces vselect(cmp, vnot(y), zero) which the
; generic vselect-to-bitselect pattern lowers as v128.not + v128.bitselect.
; A dedicated ISel pattern matches this as a single v128.andnot instead.

target triple = "wasm32-unknown-unknown"

define <4 x i32> @andnot_sext_v4i32(<4 x i32> %a, <4 x i32> %b, <4 x i32> %x) {
; CHECK-LABEL: andnot_sext_v4i32:
; CHECK:       v128.andnot
; CHECK-NOT:   v128.bitselect
  %cmp = icmp slt <4 x i32> %a, %b
  %sext = sext <4 x i1> %cmp to <4 x i32>
  %not = xor <4 x i32> %x, splat (i32 -1)
  %res = and <4 x i32> %not, %sext
  ret <4 x i32> %res
}

define <16 x i8> @andnot_sext_v16i8(<16 x i8> %a, <16 x i8> %b, <16 x i8> %x) {
; CHECK-LABEL: andnot_sext_v16i8:
; CHECK:       v128.andnot
; CHECK-NOT:   v128.bitselect
  %cmp = icmp slt <16 x i8> %a, %b
  %sext = sext <16 x i1> %cmp to <16 x i8>
  %not = xor <16 x i8> %x, splat (i8 -1)
  %res = and <16 x i8> %not, %sext
  ret <16 x i8> %res
}

define <8 x i16> @andnot_sext_v8i16(<8 x i16> %a, <8 x i16> %b, <8 x i16> %x) {
; CHECK-LABEL: andnot_sext_v8i16:
; CHECK:       v128.andnot
; CHECK-NOT:   v128.bitselect
  %cmp = icmp slt <8 x i16> %a, %b
  %sext = sext <8 x i1> %cmp to <8 x i16>
  %not = xor <8 x i16> %x, splat (i16 -1)
  %res = and <8 x i16> %not, %sext
  ret <8 x i16> %res
}

define <2 x i64> @andnot_sext_v2i64(<2 x i64> %a, <2 x i64> %b, <2 x i64> %x) {
; CHECK-LABEL: andnot_sext_v2i64:
; CHECK:       v128.andnot
; CHECK-NOT:   v128.bitselect
  %cmp = icmp slt <2 x i64> %a, %b
  %sext = sext <2 x i1> %cmp to <2 x i64>
  %not = xor <2 x i64> %x, splat (i64 -1)
  %res = and <2 x i64> %not, %sext
  ret <2 x i64> %res
}
