; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=wasm32-unknown-unknown -mattr=+simd128 | FileCheck %s

define <4 x i32> @dot_sext_1(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: dot_sext_1:
; CHECK:         .functype dot_sext_1 (v128, v128) -> (v128)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    i32x4.dot_i16x8_s
; CHECK-NEXT:    # fallthrough-return
  %sext1 = sext <8 x i16> %a to <8 x i32>
  %sext2 = sext <8 x i16> %b to <8 x i32>
  %mul = mul <8 x i32> %sext1, %sext2
  %shuffle1 = shufflevector <8 x i32> %mul, <8 x i32> poison, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %shuffle2 = shufflevector <8 x i32> %mul, <8 x i32> poison, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %res = add <4 x i32> %shuffle1, %shuffle2
  ret <4 x i32> %res
}


define <4 x i32> @dot_sext_2(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: dot_sext_2:
; CHECK:         .functype dot_sext_2 (v128, v128) -> (v128)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    i32x4.dot_i16x8_s
; CHECK-NEXT:    # fallthrough-return
  %sext1 = sext <8 x i16> %a to <8 x i32>
  %sext2 = sext <8 x i16> %b to <8 x i32>
  %mul = mul <8 x i32> %sext1, %sext2
  %shuffle1 = shufflevector <8 x i32> %mul, <8 x i32> poison, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %shuffle2 = shufflevector <8 x i32> %mul, <8 x i32> poison, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %res = add <4 x i32> %shuffle2, %shuffle1
  ret <4 x i32> %res
}

define <4 x i32> @dot_sext_self(<8 x i16> %v) {
; CHECK-LABEL: dot_sext_self:
; CHECK:         .functype dot_sext_self (v128) -> (v128)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    i32x4.dot_i16x8_s
; CHECK-NEXT:    # fallthrough-return
  %sext = sext <8 x i16> %v to <8 x i32>
  %mul = mul <8 x i32> %sext, %sext
  %shuffle1 = shufflevector <8 x i32> %mul, <8 x i32> poison, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %shuffle2 = shufflevector <8 x i32> %mul, <8 x i32> poison, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %res = add <4 x i32> %shuffle1, %shuffle2
  ret <4 x i32> %res
}

; INFO: Negative test
define <4 x i32> @dot_zext(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: dot_zext:
; CHECK:         .functype dot_zext (v128, v128) -> (v128)
; CHECK-NEXT:    .local v128
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    i32x4.extmul_low_i16x8_u
; CHECK-NEXT:    local.tee 2
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    i32x4.extmul_high_i16x8_u
; CHECK-NEXT:    local.tee 1
; CHECK-NEXT:    i8x16.shuffle 0, 1, 2, 3, 8, 9, 10, 11, 16, 17, 18, 19, 24, 25, 26, 27
; CHECK-NEXT:    local.get 2
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    i8x16.shuffle 4, 5, 6, 7, 12, 13, 14, 15, 20, 21, 22, 23, 28, 29, 30, 31
; CHECK-NEXT:    i32x4.add
; CHECK-NEXT:    # fallthrough-return
  %zext1 = zext <8 x i16> %a to <8 x i32>
  %zext2 = zext <8 x i16> %b to <8 x i32>
  %mul = mul <8 x i32> %zext1, %zext2
  %shuffle1 = shufflevector <8 x i32> %mul, <8 x i32> poison, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %shuffle2 = shufflevector <8 x i32> %mul, <8 x i32> poison, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %res = add <4 x i32> %shuffle1, %shuffle2
  ret <4 x i32> %res
}

; INFO: Negative test
define <4 x i32> @dot_wrong_shuffle(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: dot_wrong_shuffle:
; CHECK:         .functype dot_wrong_shuffle (v128, v128) -> (v128)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    i32x4.extmul_low_i16x8_s
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    i32x4.extmul_high_i16x8_s
; CHECK-NEXT:    i32x4.add
; CHECK-NEXT:    # fallthrough-return
  %sext1 = sext <8 x i16> %a to <8 x i32>
  %sext2 = sext <8 x i16> %b to <8 x i32>
  %mul = mul <8 x i32> %sext1, %sext2
  %shuffle1 = shufflevector <8 x i32> %mul, <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %shuffle2 = shufflevector <8 x i32> %mul, <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %res = add <4 x i32> %shuffle1, %shuffle2
  ret <4 x i32> %res
}

define dso_local <4 x i32> @dot_with_bitcast_both(<4 x i32> %a, <4 x i32> %b) unnamed_addr {
; CHECK-LABEL: dot_with_bitcast_both:
; CHECK:         .functype dot_with_bitcast_both (v128, v128) -> (v128)
; CHECK-NEXT:  # %bb.0: # %start
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    i32x4.dot_i16x8_s
; CHECK-NEXT:    # fallthrough-return
start:
  %_4 = bitcast <4 x i32> %a to <8 x i16>
  %_5 = bitcast <4 x i32> %b to <8 x i16>
  %0 = sext <8 x i16> %_4 to <8 x i32>
  %1 = sext <8 x i16> %_5 to <8 x i32>
  %2 = mul nsw <8 x i32> %1, %0
  %3 = shufflevector <8 x i32> %2, <8 x i32> poison, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %4 = shufflevector <8 x i32> %2, <8 x i32> poison, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %5 = add <4 x i32> %3, %4
  ret <4 x i32> %5
}

define <4 x i32> @dot_with_bitcast_one(<4 x i32> %a) {
; CHECK-LABEL: dot_with_bitcast_one:
; CHECK:         .functype dot_with_bitcast_one (v128) -> (v128)
; CHECK-NEXT:  # %bb.0: # %start
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    i32x4.extadd_pairwise_i16x8_s
; CHECK-NEXT:    # fallthrough-return
start:
  %a1 = bitcast <4 x i32> %a to <8 x i16>
  %0 = shufflevector <8 x i16> %a1, <8 x i16> %a1, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %1 = shufflevector <8 x i16> %a1, <8 x i16> %a1, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %2 = sext <4 x i16> %0 to <4 x i32>
  %3 = sext <4 x i16> %1 to <4 x i32>
  %4 = add nsw <4 x i32> %2, %3
  ret <4 x i32> %4
}

define void @load_sext_both(ptr %a, ptr %b, ptr %s) {
; CHECK-LABEL: load_sext_both:
; CHECK:         .functype load_sext_both (i32, i32, i32) -> ()
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get 2
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    v128.load 0
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    v128.load 0
; CHECK-NEXT:    i32x4.dot_i16x8_s
; CHECK-NEXT:    v128.store 0
; CHECK-NEXT:    # fallthrough-return
  %load = load <8 x i16>, ptr %a, align 16
  %1 = sext <8 x i16> %load to <8 x i32>
  %2 = load <8 x i16>, ptr %b, align 16
  %3 = sext <8 x i16> %2 to <8 x i32>
  %4 = mul nsw <8 x i32> %3, %1
  %5 = shufflevector <8 x i32> %4, <8 x i32> poison, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %6 = shufflevector <8 x i32> %4, <8 x i32> poison, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %7 = add <4 x i32> %5, %6
  store <4 x i32> %7, ptr %s, align 16
  ret void
}

define void @add_from_same_base(ptr %a, ptr %s) {
; CHECK-LABEL: add_from_same_base:
; CHECK:         .functype add_from_same_base (i32, i32) -> ()
; CHECK-NEXT:    .local v128
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    v128.load 0
; CHECK-NEXT:    local.tee 2
; CHECK-NEXT:    local.get 2
; CHECK-NEXT:    i32x4.dot_i16x8_s
; CHECK-NEXT:    v128.store 0
; CHECK-NEXT:    # fallthrough-return
  %load = load <8 x i16>, ptr %a, align 16
  %1 = sext <8 x i16> %load to <8 x i32>
  %mul = mul nsw <8 x i32> %1, %1
  %2 = shufflevector <8 x i32> %mul, <8 x i32> poison, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %3 = shufflevector <8 x i32> %mul, <8 x i32> poison, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %4 = add nsw <4 x i32> %2, %3
  store <4 x i32> %4, ptr %s, align 16
  ret void
}

define <4 x i32> @combine_with_constant(<8 x i16> %v) {
; CHECK-LABEL: combine_with_constant:
; CHECK:         .functype combine_with_constant (v128) -> (v128)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    v128.const 4096, 1, 4096, 1, 4096, 1, 4096, 1
; CHECK-NEXT:    i32x4.dot_i16x8_s
; CHECK-NEXT:    # fallthrough-return
  %sext = sext <8 x i16> %v to <8 x i32>
  %1 = mul nsw <8 x i32> %sext, <i32 4096, i32 1, i32 4096, i32 1, i32 4096, i32 1, i32 4096, i32 1>
  %2 = shufflevector <8 x i32> %1, <8 x i32> poison, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %3 = shufflevector <8 x i32> %1, <8 x i32> poison, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %4 = add <4 x i32> %2, %3
  ret <4 x i32> %4
}

define <4 x i32> @combine_with_shl(<8 x i16> %v) {
; CHECK-LABEL: combine_with_shl:
; CHECK:         .functype combine_with_shl (v128) -> (v128)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    v128.const 4096, 1, 4096, 1, 4096, 1, 4096, 1
; CHECK-NEXT:    i32x4.dot_i16x8_s
; CHECK-NEXT:    # fallthrough-return
  %sext = sext <8 x i16> %v to <8 x i32>
  %1 = shl nsw <8 x i32> %sext, <i32 12, i32 0, i32 12, i32 0, i32 12, i32 0, i32 12, i32 0>
  %2 = shufflevector <8 x i32> %1, <8 x i32> poison, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %3 = shufflevector <8 x i32> %1, <8 x i32> poison, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %4 = add <4 x i32> %2, %3
  ret <4 x i32> %4
}

; Negative - shifts by 16 overflow, so we don't optimize this.
define <4 x i32> @combine_with_shl_overflow(<8 x i16> %v) {
; CHECK-LABEL: combine_with_shl_overflow:
; CHECK:         .functype combine_with_shl_overflow (v128) -> (v128)
; CHECK-NEXT:    .local v128
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    i32x4.extend_low_i16x8_u
; CHECK-NEXT:    i32.const 16
; CHECK-NEXT:    i32x4.shl
; CHECK-NEXT:    local.tee 1
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    i32x4.extend_high_i16x8_u
; CHECK-NEXT:    i32.const 16
; CHECK-NEXT:    i32x4.shl
; CHECK-NEXT:    local.tee 0
; CHECK-NEXT:    i8x16.shuffle 0, 1, 2, 3, 8, 9, 10, 11, 16, 17, 18, 19, 24, 25, 26, 27
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    i8x16.shuffle 4, 5, 6, 7, 12, 13, 14, 15, 20, 21, 22, 23, 28, 29, 30, 31
; CHECK-NEXT:    i32x4.add
; CHECK-NEXT:    # fallthrough-return
  %sext = sext <8 x i16> %v to <8 x i32>
  %1 = shl nsw <8 x i32> %sext, <i32 16, i32 16, i32 16, i32 16, i32 16, i32 16, i32 16, i32 16>
  %2 = shufflevector <8 x i32> %1, <8 x i32> poison, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %3 = shufflevector <8 x i32> %1, <8 x i32> poison, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %4 = add <4 x i32> %2, %3
  ret <4 x i32> %4
}

; Negative - vector index is not composed of V[2*i] and V[2*i+1].
define void @load_sext_both_but_not_valid_vector_index(ptr %a, ptr %b, ptr %s) {
; CHECK-LABEL: load_sext_both_but_not_valid_vector_index:
; CHECK:         .functype load_sext_both_but_not_valid_vector_index (i32, i32, i32) -> ()
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get 2
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    v128.load 0
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    v128.load 0
; CHECK-NEXT:    i32x4.dot_i16x8_s
; CHECK-NEXT:    v128.store 0
; CHECK-NEXT:    # fallthrough-return
  %load = load <8 x i16>, ptr %a, align 16
  %1 = sext <8 x i16> %load to <8 x i32>
  %2 = load <8 x i16>, ptr %b, align 16
  %3 = sext <8 x i16> %2 to <8 x i32>
  %4 = mul nsw <8 x i32> %3, %1
  %5 = shufflevector <8 x i32> %4, <8 x i32> poison, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %6 = shufflevector <8 x i32> %4, <8 x i32> poison, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %7 = add <4 x i32> %5, %6
  store <4 x i32> %7, ptr %s, align 16
  ret void
}
