; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -o - %s -mattr=-bulk-memory | FileCheck --check-prefix=NOTLS %s
; RUN: llc -o - %s -mattr=+bulk-memory,+atomics | FileCheck --check-prefix=TLS %s

target triple = "wasm32--"

@tls = internal thread_local global i32 0

define i32 @func() {
; NOTLS-LABEL: func:
; NOTLS:         .functype func () -> (i32)
; NOTLS-NEXT:  # %bb.0:
; NOTLS-NEXT:    i32.const 0
; NOTLS-NEXT:    i32.load tls
; NOTLS-NEXT:    # fallthrough-return
;
; TLS-LABEL: func:
; TLS:         .functype func () -> (i32)
; TLS-NEXT:  # %bb.0:
; TLS-NEXT:    global.get __tls_base
; TLS-NEXT:    i32.const tls@TLSREL
; TLS-NEXT:    i32.add
; TLS-NEXT:    i32.load 0
; TLS-NEXT:    # fallthrough-return
  %p = call ptr @llvm.threadlocal.address.p0(ptr @tls)
  %v = load i32, ptr %p
  ret i32 %v
}
