; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s | FileCheck %s

target triple = "wasm32-unknown-unknown"

%pair = type { i32, i32 }

define wasm_multivalue %pair @returns_pair_mv() {
; CHECK-LABEL: returns_pair_mv:
; CHECK:         .functype returns_pair_mv () -> (i32, i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    i32.const 1
; CHECK-NEXT:    i32.const 2
; CHECK-NEXT:    # fallthrough-return
  ret %pair { i32 1, i32 2 }
}

define %pair @returns_pair_c() {
; CHECK-LABEL: returns_pair_c:
; CHECK:         .functype returns_pair_c (i32) -> ()
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    i64.const 8589934593
; CHECK-NEXT:    i64.store 0
; CHECK-NEXT:    # fallthrough-return
  ret %pair { i32 1, i32 2 }
}

define wasm_multivalue i128 @returns_i128() {
; CHECK-LABEL: returns_i128:
; CHECK:         .functype returns_i128 () -> (i64, i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    i64.const 42
; CHECK-NEXT:    i64.const 0
; CHECK-NEXT:    # fallthrough-return
  ret i128 42
}

define wasm_multivalue %pair @forward_pair() {
; CHECK-LABEL: forward_pair:
; CHECK:         .functype forward_pair () -> (i32, i32)
; CHECK-NEXT:    .local i32, i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    call returns_pair_mv
; CHECK-NEXT:    local.set 1
; CHECK-NEXT:    local.set 0
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    # fallthrough-return
  %p = call wasm_multivalue %pair @returns_pair_mv()
  ret %pair %p
}

; A multi-value caller calling a non-multi-value ABI should do the appropriate
; handling for the ABI-at-hand.
define wasm_multivalue %pair @caller_mv_callee_c() {
; CHECK-LABEL: caller_mv_callee_c:
; CHECK:         .functype caller_mv_callee_c () -> (i32, i32)
; CHECK-NEXT:    .local i32, i32, i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    global.get __stack_pointer
; CHECK-NEXT:    i32.const 16
; CHECK-NEXT:    i32.sub
; CHECK-NEXT:    local.tee 0
; CHECK-NEXT:    global.set __stack_pointer
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    i32.const 8
; CHECK-NEXT:    i32.add
; CHECK-NEXT:    call returns_pair_c
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    i32.load 12
; CHECK-NEXT:    local.set 1
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    i32.load 8
; CHECK-NEXT:    local.set 2
; CHECK-NEXT:    local.get 0
; CHECK-NEXT:    i32.const 16
; CHECK-NEXT:    i32.add
; CHECK-NEXT:    global.set __stack_pointer
; CHECK-NEXT:    local.get 2
; CHECK-NEXT:    local.get 1
; CHECK-NEXT:    # fallthrough-return
  %p = call %pair @returns_pair_c()
  ret %pair %p
}
