; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes='require<profile-summary>,codegenprepare' -mtriple=i686-unknown-linux-gnu -mattr=+sse2 < %s | FileCheck %s

define double @test_hoist_bitcast_i64_to_double(i1 %cond, i64 %a) {
; CHECK-LABEL: @test_hoist_bitcast_i64_to_double(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ADD:%.*]] = add i64 [[A:%.*]], 1
; CHECK-NEXT:    [[BC_HOISTED:%.*]] = bitcast i64 [[ADD]] to double
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[IF_THEN:%.*]], label [[EXIT:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    [[RES:%.*]] = phi double [ [[BC_HOISTED]], [[IF_THEN]] ], [ 0.000000e+00, [[ENTRY:%.*]] ]
; CHECK-NEXT:    ret double [[RES]]
;
entry:
  %add = add i64 %a, 1
  br i1 %cond, label %if.then, label %exit

if.then:
  %bc = bitcast i64 %add to double
  br label %exit

exit:
  %res = phi double [ %bc, %if.then ], [ 0.0, %entry ]
  ret double %res
}
