; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -mtriple=x86_64-- -codegenprepare < %s | FileCheck %s

; sinkCmpExpression currently sinks an "icmp eq (and X, mask), 0" comparison
; into a block that only returns the result, giving the 'and' operand a second
; cross-block use.  This causes sinkAndCmp0Expression to also duplicate the
; 'and' in the return block, producing a redundant TEST+SETCC sequence in the
; generated code (see bool-ret-from-branch-cond.ll).

define i1 @test_no_sink_into_ret(i64 %x, ptr %y) {
; CHECK-LABEL: define i1 @test_no_sink_into_ret
; CHECK-SAME: (i64 [[X:%.*]], ptr [[Y:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = and i64 [[X]], 3
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[TMP0]], 0
; CHECK-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[RETURN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    store i32 0, ptr [[Y]], align 4
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       return:
; CHECK-NEXT:    [[TMP1:%.*]] = and i64 [[X]], 3
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i64 [[TMP1]], 0
; CHECK-NEXT:    ret i1 [[TMP2]]
;
entry:
  %rem = and i64 %x, 3
  %cmp = icmp eq i64 %rem, 0
  br i1 %cmp, label %if.then, label %return

if.then:
  store i32 0, ptr %y, align 4
  br label %return

return:
  ret i1 %cmp
}

; Multiple predecessors: condition is known at each predecessor but must
; not be sunk when it fits the and+icmp-eq-0 / TEST pattern.
define i1 @test_no_sink_into_ret_multi_pred(i64 %x, ptr %y, ptr %z) {
; CHECK-LABEL: define i1 @test_no_sink_into_ret_multi_pred
; CHECK-SAME: (i64 [[X:%.*]], ptr [[Y:%.*]], ptr [[Z:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = and i64 [[X]], 3
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[TMP0]], 0
; CHECK-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[RETURN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    store i32 0, ptr [[Y]], align 4
; CHECK-NEXT:    store i32 1, ptr [[Z]], align 4
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       return:
; CHECK-NEXT:    [[TMP1:%.*]] = and i64 [[X]], 3
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i64 [[TMP1]], 0
; CHECK-NEXT:    ret i1 [[TMP2]]
;
entry:
  %rem = and i64 %x, 3
  %cmp = icmp eq i64 %rem, 0
  br i1 %cmp, label %if.then, label %return

if.then:
  store i32 0, ptr %y, align 4
  store i32 1, ptr %z, align 4
  br label %return

return:
  ret i1 %cmp
}
