; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: -p --check-globals all --version 6
; RUN: opt -S -passes="simplifycfg<switch-to-lookup>" < %s | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

$foostring = comdat any

@.str = private unnamed_addr constant [4 x i8] c"foo\00", comdat($foostring), align 1
@.str1 = private unnamed_addr constant [4 x i8] c"bar\00", comdat($foostring), align 1
@.str2 = private unnamed_addr constant [4 x i8] c"baz\00", comdat($foostring), align 1
@.str3 = private unnamed_addr constant [4 x i8] c"qux\00", comdat($foostring), align 1
@.str4 = private unnamed_addr constant [6 x i8] c"error\00", comdat($foostring), align 1

;.
; CHECK: @.str = private unnamed_addr constant [4 x i8] c"foo\00", comdat($foostring), align 1
; CHECK: @.str1 = private unnamed_addr constant [4 x i8] c"bar\00", comdat($foostring), align 1
; CHECK: @.str2 = private unnamed_addr constant [4 x i8] c"baz\00", comdat($foostring), align 1
; CHECK: @.str3 = private unnamed_addr constant [4 x i8] c"qux\00", comdat($foostring), align 1
; CHECK: @.str4 = private unnamed_addr constant [6 x i8] c"error\00", comdat($foostring), align 1
; CHECK: @switch.table.foostring = private unnamed_addr constant [4 x ptr] [ptr @.str, ptr @.str1, ptr @.str2, ptr @.str3], comdat($foostring), align 8
;.
define ptr @foostring(i32 %x) comdat {
; CHECK-LABEL: define ptr @foostring(i32 %x) comdat {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    %0 = icmp ult i32 %x, 4
; CHECK-NEXT:    br i1 %0, label %switch.lookup, label %return
; CHECK:       switch.lookup:
; CHECK-NEXT:    %1 = zext nneg i32 %x to i64
; CHECK-NEXT:    %switch.gep = getelementptr inbounds [4 x ptr], ptr @switch.table.foostring, i64 0, i64 %1
; CHECK-NEXT:    %switch.load = load ptr, ptr %switch.gep, align 8
; CHECK-NEXT:    br label %return
; CHECK:       return:
; CHECK-NEXT:    %retval.0 = phi ptr [ %switch.load, %switch.lookup ], [ @.str4, %entry ]
; CHECK-NEXT:    ret ptr %retval.0
;
entry:
  switch i32 %x, label %sw.default [
  i32 0, label %return
  i32 1, label %sw.bb1
  i32 2, label %sw.bb2
  i32 3, label %sw.bb3
  ]

sw.bb1: br label %return
sw.bb2: br label %return
sw.bb3: br label %return
sw.default: br label %return

return:
  %retval.0 = phi ptr [ @.str4, %sw.default ],
  [ @.str3, %sw.bb3 ],
  [ @.str2, %sw.bb2 ],
  [ @.str1, %sw.bb1 ],
  [ @.str, %entry ]
  ret ptr %retval.0

}

