/*
 * Copyright (c) 2020 Bitdefender
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef BDDISASM_VERSION_H
#define BDDISASM_VERSION_H

#define DISASM_VERSION_MAJOR        2
#define DISASM_VERSION_MINOR        3
#define DISASM_VERSION_REVISION     0

#define SHEMU_VERSION_MAJOR         DISASM_VERSION_MAJOR
#define SHEMU_VERSION_MINOR         DISASM_VERSION_MINOR
#define SHEMU_VERSION_REVISION      DISASM_VERSION_REVISION

#endif // BDDISASM_VERSION_H
