; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -passes=inline %s | FileCheck %s
; RUN: opt -S -passes='cgscc(inline)' %s | FileCheck %s
; RUN: opt -S -passes='module-inline' %s | FileCheck %s

declare void @h(ptr %p, ptr %q, ptr %z)

define void @f(ptr %p, ptr %q, ptr %z) {
; CHECK-LABEL: define void @f
; CHECK-SAME: (ptr [[P:%.*]], ptr [[Q:%.*]], ptr [[Z:%.*]]) {
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[P]]) ]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[Z]]) ]
; CHECK-NEXT:    call void @h(ptr [[P]], ptr [[Q]], ptr [[Z]])
; CHECK-NEXT:    ret void
;
  call void @g(ptr nonnull %p, ptr %q, ptr nonnull %z)
  ret void
}

define void @g(ptr %p, ptr %q, ptr %z) {
; CHECK-LABEL: define void @g
; CHECK-SAME: (ptr [[P:%.*]], ptr [[Q:%.*]], ptr [[Z:%.*]]) {
; CHECK-NEXT:    call void @h(ptr [[P]], ptr [[Q]], ptr [[Z]])
; CHECK-NEXT:    ret void
;
  call void @h(ptr %p, ptr %q, ptr %z)
  ret void
}
