; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=always-inline -S | FileCheck %s

define <2 x i64> @vpx_lpf_horizontal_4_sse2(<2 x i64> %0) {
; CHECK-LABEL: define <2 x i64> @vpx_lpf_horizontal_4_sse2(
; CHECK-SAME: <2 x i64> [[TMP0:%.*]]) {
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP0]] to <16 x i8>
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> zeroinitializer, <16 x i32> <i32 8, i32 24, i32 9, i32 25, i32 10, i32 26, i32 11, i32 27, i32 12, i32 28, i32 13, i32 29, i32 14, i32 30, i32 15, i32 31>
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i8> [[TMP3]] to <2 x i64>
; CHECK-NEXT:    [[TMP5:%.*]] = bitcast <2 x i64> [[TMP4]] to <8 x i16>
; CHECK-NEXT:    [[TMP6:%.*]] = ashr <8 x i16> [[TMP5]], splat (i16 1)
; CHECK-NEXT:    ret <2 x i64> zeroinitializer
;
  %2 = call fastcc <2 x i64> @_mm_unpackhi_epi8(<2 x i64> %0)
  %3 = call fastcc <2 x i64> @_mm_srai_epi16(<2 x i64> %2)
  ret <2 x i64> %3
}

define fastcc <2 x i64> @_mm_unpackhi_epi8(<2 x i64> %0) #0 {
; CHECK-LABEL: define fastcc <2 x i64> @_mm_unpackhi_epi8(
; CHECK-SAME: <2 x i64> [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP0]] to <16 x i8>
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> zeroinitializer, <16 x i32> <i32 8, i32 24, i32 9, i32 25, i32 10, i32 26, i32 11, i32 27, i32 12, i32 28, i32 13, i32 29, i32 14, i32 30, i32 15, i32 31>
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i8> [[TMP3]] to <2 x i64>
; CHECK-NEXT:    ret <2 x i64> [[TMP4]]
;
  %2 = bitcast <2 x i64> %0 to <16 x i8>
  %3 = shufflevector <16 x i8> %2, <16 x i8> zeroinitializer, <16 x i32> <i32 8, i32 24, i32 9, i32 25, i32 10, i32 26, i32 11, i32 27, i32 12, i32 28, i32 13, i32 29, i32 14, i32 30, i32 15, i32 31>
  %4 = bitcast <16 x i8> %3 to <2 x i64>
  ret <2 x i64> %4
}

define fastcc <2 x i64> @_mm_srai_epi16(<2 x i64> %0) #0 {
; CHECK-LABEL: define fastcc <2 x i64> @_mm_srai_epi16(
; CHECK-SAME: <2 x i64> [[TMP0:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[TMP0]] to <8 x i16>
; CHECK-NEXT:    [[TMP3:%.*]] = ashr <8 x i16> [[TMP2]], splat (i16 1)
; CHECK-NEXT:    ret <2 x i64> zeroinitializer
;
  %2 = bitcast <2 x i64> %0 to <8 x i16>
  %3 = ashr <8 x i16> %2, splat (i16 1)
  ret <2 x i64> zeroinitializer
}

attributes #0 = { alwaysinline }
