; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes='cgscc(inline),function(sroa,gvn)' -S | FileCheck %s
;
; Test: devirtualization of virtual calls through static_cast downcast pointers
; via llvm.type.test+assume infrastructure.
;
; At the static_cast<Impl*>(intf) site, Clang emits:
;   %tt = llvm.type.test(ptr %intf, !"_ZTS4Impl")
;   llvm.assume(%tt)
;
; After the inliner inlines Intf::foo(), tryPromoteCall finds the type.test on
; the object pointer, matches !"_ZTS4Impl" against !type metadata on @_ZTV4Impl,
; resolves the vtable slot, and promotes the indirect call to @_ZN4Impl5doFooEv.
;
; Generated from the following C++ source with:
;   clang++ -O0 -flto -fwhole-program-vtables -S -emit-llvm file.cc
; then hand-simplified.
;
; -flto is required for -fwhole-program-vtables, which causes Clang to emit
; !type metadata on vtable globals. The vtable definition must be in the same
; module for tryPromoteCall to resolve it; in a multi-TU build this happens at
; LTO link time when all modules are merged.
;
; C++ source:
;
; int glob = 0;
; int secretValue = 42;
;
; struct Intf {
;   void foo() { this->doFoo(); }
;   virtual void doFoo();
; };
;
; struct Impl final : Intf {
;   void doFoo() override { glob = secretValue; }
; };
;
; void f(Intf *intf) { static_cast<Impl *>(intf)->foo(); }


%struct.Impl = type { %struct.Intf }
%struct.Intf = type { ptr }

@glob = dso_local global i32 0, align 4
@secretValue = dso_local global i32 42, align 4
@_ZTV4Impl = linkonce_odr unnamed_addr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr null, ptr @_ZN4Impl5doFooEv] }, align 8, !type !0

; f(Intf *intf)
define dso_local void @_Z1fP4Intf(ptr noundef %intf) {
; CHECK-LABEL: define dso_local void @_Z1fP4Intf(
; CHECK-SAME: ptr noundef [[INTF:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i1 @llvm.type.test(ptr [[INTF]], metadata !"_ZTS4Impl")
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP0]])
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr @secretValue, align 4
; CHECK-NEXT:    store i32 [[TMP1]], ptr @glob, align 4
; CHECK-NEXT:    ret void
;
entry:
  %0 = call i1 @llvm.type.test(ptr %intf, metadata !"_ZTS4Impl")
  call void @llvm.assume(i1 %0)
  call void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) %intf)
  ret void
}

; Negative test: the assume does NOT dominate the call to foo() because it is
; only on one side of a branch. tryPromoteCall must not devirtualize here.
define dso_local void @NonDominatingAssume(ptr noundef %intf, i1 %cond) {
; CHECK-LABEL: define dso_local void @NonDominatingAssume(
; CHECK-SAME: ptr noundef [[INTF:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i1 @llvm.type.test(ptr [[INTF]], metadata !"_ZTS4Impl")
; CHECK-NEXT:    br i1 [[COND]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP0]])
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[VTABLE_I:%.*]] = load ptr, ptr [[INTF]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[VTABLE_I]], align 8
; CHECK-NEXT:    call void [[TMP1]](ptr noundef nonnull align 8 dereferenceable(8) [[INTF]])
; CHECK-NEXT:    ret void
;
entry:
  %0 = call i1 @llvm.type.test(ptr %intf, metadata !"_ZTS4Impl")
  br i1 %cond, label %then, label %else

then:
  call void @llvm.assume(i1 %0)
  br label %merge

else:
  br label %merge

merge:
  call void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) %intf)
  ret void
}

; Negative test: a call between the assume and foo() could clobber the vptr
; (e.g. destructor + placement new). tryPromoteCall must not devirtualize.
declare void @MayClobberVptr(ptr)

define dso_local void @VptrClobbered(ptr noundef %intf) {
; CHECK-LABEL: define dso_local void @VptrClobbered(
; CHECK-SAME: ptr noundef [[INTF:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i1 @llvm.type.test(ptr [[INTF]], metadata !"_ZTS4Impl")
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP0]])
; CHECK-NEXT:    call void @MayClobberVptr(ptr [[INTF]])
; CHECK-NEXT:    [[VTABLE_I:%.*]] = load ptr, ptr [[INTF]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[VTABLE_I]], align 8
; CHECK-NEXT:    call void [[TMP1]](ptr noundef nonnull align 8 dereferenceable(8) [[INTF]])
; CHECK-NEXT:    ret void
;
entry:
  %0 = call i1 @llvm.type.test(ptr %intf, metadata !"_ZTS4Impl")
  call void @llvm.assume(i1 %0)
  call void @MayClobberVptr(ptr %intf)
  call void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) %intf)
  ret void
}

; Positive test: a store to an unrelated global between the assume and foo()
; cannot alias the vptr slot. With alias analysis, tryPromoteCall can still
; devirtualize.
@unrelated_global = dso_local global i32 0, align 4

define dso_local void @UnrelatedWriteNoAlias(ptr noundef %intf) {
; CHECK-LABEL: define dso_local void @UnrelatedWriteNoAlias(
; CHECK-SAME: ptr noundef [[INTF:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i1 @llvm.type.test(ptr [[INTF]], metadata !"_ZTS4Impl")
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP0]])
; CHECK-NEXT:    store i32 99, ptr @unrelated_global, align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr @secretValue, align 4
; CHECK-NEXT:    store i32 [[TMP1]], ptr @glob, align 4
; CHECK-NEXT:    ret void
;
entry:
  %0 = call i1 @llvm.type.test(ptr %intf, metadata !"_ZTS4Impl")
  call void @llvm.assume(i1 %0)
  store i32 99, ptr @unrelated_global, align 4
  call void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) %intf)
  ret void
}

; Negative test: an unknown call on an alias of %intf could clobber the vptr.
; AA detects that %alias may-alias %intf, so devirtualization is blocked.
define dso_local void @VptrClobberedViaAlias(ptr noundef %intf) {
; CHECK-LABEL: define dso_local void @VptrClobberedViaAlias(
; CHECK-SAME: ptr noundef [[INTF:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i1 @llvm.type.test(ptr [[INTF]], metadata !"_ZTS4Impl")
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP0]])
; CHECK-NEXT:    call void @MayClobberVptr(ptr [[INTF]])
; CHECK-NEXT:    [[VTABLE_I:%.*]] = load ptr, ptr [[INTF]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[VTABLE_I]], align 8
; CHECK-NEXT:    call void [[TMP1]](ptr noundef nonnull align 8 dereferenceable(8) [[INTF]])
; CHECK-NEXT:    ret void
;
entry:
  %alias = getelementptr i8, ptr %intf, i64 0
  %0 = call i1 @llvm.type.test(ptr %intf, metadata !"_ZTS4Impl")
  call void @llvm.assume(i1 %0)
  call void @MayClobberVptr(ptr %alias)
  call void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) %intf)
  ret void
}

; Negative test: pointer laundered through ptrtoint/inttoptr. AA must still
; conservatively block devirtualization because the result may alias %intf.
define dso_local void @VptrClobberedViaIntToPtr(ptr noundef %intf) {
; CHECK-LABEL: define dso_local void @VptrClobberedViaIntToPtr(
; CHECK-SAME: ptr noundef [[INTF:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[INT:%.*]] = ptrtoint ptr [[INTF]] to i64
; CHECK-NEXT:    [[TMP0:%.*]] = call i1 @llvm.type.test(ptr [[INTF]], metadata !"_ZTS4Impl")
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP0]])
; CHECK-NEXT:    call void @MayClobberVptr(ptr [[INTF]])
; CHECK-NEXT:    [[VTABLE_I:%.*]] = load ptr, ptr [[INTF]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[VTABLE_I]], align 8
; CHECK-NEXT:    call void [[TMP1]](ptr noundef nonnull align 8 dereferenceable(8) [[INTF]])
; CHECK-NEXT:    ret void
;
entry:
  %int = ptrtoint ptr %intf to i64
  %laundered = inttoptr i64 %int to ptr
  %0 = call i1 @llvm.type.test(ptr %intf, metadata !"_ZTS4Impl")
  call void @llvm.assume(i1 %0)
  call void @MayClobberVptr(ptr %laundered)
  call void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) %intf)
  ret void
}

; Intf::foo() - non-virtual wrapper that makes the virtual call
define linkonce_odr void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) %this) align 2 {
entry:
  %vtable = load ptr, ptr %this, align 8
  %vfn = getelementptr inbounds ptr, ptr %vtable, i64 0
  %0 = load ptr, ptr %vfn, align 8
  call void %0(ptr noundef nonnull align 8 dereferenceable(8) %this)
  ret void
}

; Impl::doFoo()
define linkonce_odr void @_ZN4Impl5doFooEv(ptr noundef nonnull align 8 dereferenceable(8) %this) unnamed_addr align 2 {
; CHECK-LABEL: define linkonce_odr void @_ZN4Impl5doFooEv(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr align 2 {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr @secretValue, align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr @glob, align 4
; CHECK-NEXT:    ret void
;
entry:
  %0 = load i32, ptr @secretValue, align 4
  store i32 %0, ptr @glob, align 4
  ret void
}

; !type metadata: maps type ID !"_ZTS4Impl" to the vtable address point at byte
; offset 16 (past offset-to-top and RTTI pointer). Emitted by Clang with
; -fwhole-program-vtables.
!0 = !{i64 16, !"_ZTS4Impl"}
