; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt < %s -passes=inline -S | FileCheck %s

define void @callee() {
; CHECK-LABEL: define void @callee() {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[VAL_PTR:%.*]] = load ptr, ptr null, align 8
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr [[VAL_PTR]], null
; CHECK-NEXT:    [[VAL:%.*]] = load i64, ptr null, align 8
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], i64 undef, i64 [[VAL]]
; CHECK-NEXT:    ret void
;
entry:
  %val_ptr = load ptr, ptr null, align 8
  %cmp = icmp eq ptr %val_ptr, null
  %val = load i64, ptr null, align 8
  %sel = select i1 %cmp, i64 undef, i64 %val
  ret void
}

define noundef i1 @caller() {
; CHECK-LABEL: define noundef i1 @caller() {
; CHECK-NEXT:    [[VAL_PTR_I:%.*]] = load ptr, ptr null, align 8
; CHECK-NEXT:    [[CMP_I:%.*]] = icmp eq ptr [[VAL_PTR_I]], null
; CHECK-NEXT:    [[VAL_I:%.*]] = load i64, ptr null, align 8
; CHECK-NEXT:    [[SEL_I:%.*]] = select i1 [[CMP_I]], i64 undef, i64 [[VAL_I]]
; CHECK-NEXT:    ret i1 false
;
  call void @callee()
  ret i1 false
}
