; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=inline %s -S | FileCheck %s


; Ordinary function is inlined into strictfp function.

define float @inlined_01(float %a) {
; CHECK-LABEL: define float @inlined_01(
; CHECK-SAME: float [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ADD:%.*]] = fadd float [[A]], [[A]]
; CHECK-NEXT:    ret float [[ADD]]
;
entry:
  %add = fadd float %a, %a
  ret float %add
}

define float @host_02(float %a) #0 {
; CHECK-LABEL: define float @host_02(
; CHECK-SAME: float [[A:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ADD_I:%.*]] = fadd float [[A]], [[A]]
; CHECK-NEXT:    [[ADD1:%.*]] = fadd float [[ADD_I]], 2.000000e+00
; CHECK-NEXT:    ret float [[ADD1]]
;
entry:
  %0 = call float @inlined_01(float %a) #0
  %add = call float @llvm.experimental.constrained.fadd.f32(float %0, float 2.000000e+00, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  ret float %add
}


; strictfp function is inlined into another strictfp function.

define float @inlined_03(float %a) #0 {
; CHECK-LABEL: define float @inlined_03(
; CHECK-SAME: float [[A:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ADD1:%.*]] = call float @llvm.fadd.f32(float [[A]], float [[A]]) [ "fp.control"(metadata !"rtn"), "fp.except"(metadata !"maytrap") ]
; CHECK-NEXT:    ret float [[ADD1]]
;
entry:
  %add = call float @llvm.experimental.constrained.fadd.f32(float %a, float %a, metadata !"round.downward", metadata !"fpexcept.maytrap") #0
  ret float %add
}

define float @host_04(float %a) #0 {
; CHECK-LABEL: define float @host_04(
; CHECK-SAME: float [[A:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ADD1_I:%.*]] = call float @llvm.fadd.f32(float [[A]], float [[A]]) #[[ATTR0]] [ "fp.control"(metadata !"rtn"), "fp.except"(metadata !"maytrap") ]
; CHECK-NEXT:    [[ADD1:%.*]] = fadd float [[ADD1_I]], 2.000000e+00
; CHECK-NEXT:    ret float [[ADD1]]
;
entry:
  %0 = call float @inlined_03(float %a) #0
  %add = call float @llvm.experimental.constrained.fadd.f32(float %0, float 2.000000e+00, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  ret float %add
}


; strictfp function is NOT inlined into ordinary function.

define float @inlined_05(float %a) strictfp {
; CHECK-LABEL: define float @inlined_05(
; CHECK-SAME: float [[A:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ADD1:%.*]] = call float @llvm.fadd.f32(float [[A]], float [[A]]) [ "fp.control"(metadata !"rtn"), "fp.except"(metadata !"maytrap") ]
; CHECK-NEXT:    ret float [[ADD1]]
;
entry:
  %add = call float @llvm.experimental.constrained.fadd.f32(float %a, float %a, metadata !"round.downward", metadata !"fpexcept.maytrap") #0
  ret float %add
}

define float @host_06(float %a) {
; CHECK-LABEL: define float @host_06(
; CHECK-SAME: float [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call float @inlined_05(float [[A]])
; CHECK-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], 2.000000e+00
; CHECK-NEXT:    ret float [[ADD]]
;
entry:
  %0 = call float @inlined_05(float %a)
  %add = fadd float %0, 2.000000e+00
  ret float %add
}


; Calls in inlined function must get strictfp attribute.

declare float @func_ext(float);

define float @inlined_07(float %a) {
; CHECK-LABEL: define float @inlined_07(
; CHECK-SAME: float [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call float @func_ext(float [[A]])
; CHECK-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[A]]
; CHECK-NEXT:    ret float [[ADD]]
;
entry:
  %0 = call float @func_ext(float %a)
  %add = fadd float %0, %a

  ret float %add
}

define float @host_08(float %a) #0 {
; CHECK-LABEL: define float @host_08(
; CHECK-SAME: float [[A:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call float @func_ext(float [[A]]) #[[ATTR0]]
; CHECK-NEXT:    [[ADD_I:%.*]] = fadd float [[TMP0]], [[A]]
; CHECK-NEXT:    [[ADD1:%.*]] = fadd float [[ADD_I]], 2.000000e+00
; CHECK-NEXT:    ret float [[ADD1]]
;
entry:
  %0 = call float @inlined_07(float %a) #0
  %add = call float @llvm.experimental.constrained.fadd.f32(float %0, float 2.000000e+00, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  ret float %add
}


; Cloning particular instructions.

; fpext has two overloaded types.
define double @inlined_09(float %a) {
; CHECK-LABEL: define double @inlined_09(
; CHECK-SAME: float [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[T:%.*]] = fpext float [[A]] to double
; CHECK-NEXT:    ret double [[T]]
;
entry:
  %t = fpext float %a to double
  ret double %t
}

define double @host_10(float %a) #0 {
; CHECK-LABEL: define double @host_10(
; CHECK-SAME: float [[A:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[T_I:%.*]] = fpext float [[A]] to double
; CHECK-NEXT:    [[ADD1:%.*]] = fadd double [[T_I]], 2.000000e+00
; CHECK-NEXT:    ret double [[ADD1]]
;
entry:
  %0 = call double @inlined_09(float %a) #0
  %add = call double @llvm.experimental.constrained.fadd.f64(double %0, double 2.000000e+00, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  ret double %add
}

; fcmp does not depend on rounding mode and has metadata argument.
define i1 @inlined_11(float %a, float %b) {
; CHECK-LABEL: define i1 @inlined_11(
; CHECK-SAME: float [[A:%.*]], float [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[T:%.*]] = fcmp oeq float [[A]], [[B]]
; CHECK-NEXT:    ret i1 [[T]]
;
entry:
  %t = fcmp oeq float %a, %b
  ret i1 %t
}

define i1 @host_12(float %a, float %b) #0 {
; CHECK-LABEL: define i1 @host_12(
; CHECK-SAME: float [[A:%.*]], float [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ADD1:%.*]] = fadd float [[A]], [[B]]
; CHECK-NEXT:    [[T_I:%.*]] = fcmp oeq float [[A]], [[B]]
; CHECK-NEXT:    ret i1 [[T_I]]
;
entry:
  %add = call float @llvm.experimental.constrained.fadd.f32(float %a, float %b, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  %cmp = call i1 @inlined_11(float %a, float %b) #0
  ret i1 %cmp
}

; Intrinsic 'ceil' has constrained variant.
define float @inlined_13(float %a) {
; CHECK-LABEL: define float @inlined_13(
; CHECK-SAME: float [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[T:%.*]] = call float @llvm.ceil.f32(float [[A]])
; CHECK-NEXT:    ret float [[T]]
;
entry:
  %t = call float @llvm.ceil.f32(float %a)
  ret float %t
}

define float @host_14(float %a) #0 {
; CHECK-LABEL: define float @host_14(
; CHECK-SAME: float [[A:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[T_I:%.*]] = call float @llvm.ceil.f32(float [[A]]) #[[ATTR0]]
; CHECK-NEXT:    [[ADD1:%.*]] = fadd float [[T_I]], 2.000000e+00
; CHECK-NEXT:    ret float [[ADD1]]
;
entry:
  %0 = call float @inlined_13(float %a) #0
  %add = call float @llvm.experimental.constrained.fadd.f32(float %0, float 2.000000e+00, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  ret float %add
}

attributes #0 = { strictfp }

declare float  @llvm.experimental.constrained.fadd.f32(float, float, metadata, metadata)
declare double @llvm.experimental.constrained.fadd.f64(double, double, metadata, metadata)
declare double @llvm.experimental.constrained.fpext.f64.f32(float, metadata)
declare i1     @llvm.experimental.constrained.fcmp.f32(float, float, metadata, metadata)
declare float  @llvm.experimental.constrained.ceil.f32(float, metadata)
declare float  @llvm.ceil.f32(float)
