; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes="cgscc(inline)" < %s | FileCheck %s

; Test that the CGSCC inliner performs store-to-load forwarding for call
; arguments after inlining a function in the same caller. The first call
; (@init or @init_memset) is inlined, producing stores. Forwarding then
; resolves the subsequent load to a constant, enabling inlining of the
; second callee.

target datalayout = "p:64:64"

; Two paths: mode==0 is trivial (ret), otherwise too expensive to inline.
define internal i32 @callee(i32 %mode, ptr %p) {
entry:
  %cmp = icmp eq i32 %mode, 0
  br i1 %cmp, label %fast, label %slow
fast:
  %v = load i32, ptr %p
  ret i32 %v
slow:
  %a1 = load volatile i32, ptr %p
  %a2 = load volatile i32, ptr %p
  %x1 = add i32 %a1, %a2
  %a3 = load volatile i32, ptr %p
  %x2 = add i32 %x1, %a3
  %a4 = load volatile i32, ptr %p
  %x3 = add i32 %x2, %a4
  %a5 = load volatile i32, ptr %p
  %x4 = add i32 %x3, %a5
  ret i32 %x4
}

; Trivial when called with null, otherwise too expensive to inline.
define internal void @recursive_callee(ptr %x) {
; CHECK-LABEL: define internal void @recursive_callee(
; CHECK-SAME: ptr [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr [[X]], null
; CHECK-NEXT:    br i1 [[CMP]], label %[[DONE:.*]], label %[[RECURSE:.*]]
; CHECK:       [[RECURSE]]:
; CHECK-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[X]], align 8
; CHECK-NEXT:    call void @recursive_callee(ptr [[NEXT]])
; CHECK-NEXT:    [[V:%.*]] = load volatile i32, ptr [[X]], align 4
; CHECK-NEXT:    br label %[[DONE]]
; CHECK:       [[DONE]]:
; CHECK-NEXT:    ret void
;
entry:
  %cmp = icmp eq ptr %x, null
  br i1 %cmp, label %done, label %recurse
recurse:
  %next = load ptr, ptr %x
  call void @recursive_callee(ptr %next)
  %v = load volatile i32, ptr %x
  br label %done
done:
  ret void
}

; Trivially cheap — inlined first, producing a store.
define internal void @init_i32(ptr %p) {
  store i32 0, ptr %p
  ret void
}

; Trivially cheap — inlined first, producing a memset.
define internal void @init_memset(ptr %p) {
  call void @llvm.memset.p0.i64(ptr %p, i8 0, i64 8, i1 false)
  ret void
}

declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)

; After inlining @init_i32: store 0 → %p.
; Forwarding resolves %mode to 0, making only the fast path reachable.
define i32 @caller_store_forward() {
; CHECK-LABEL: define i32 @caller_store_forward() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[P:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 0, ptr [[P]], align 4
; CHECK-NEXT:    [[V_I:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    ret i32 [[V_I]]
;
entry:
  %p = alloca i32
  call void @init_i32(ptr %p)
  %mode = load i32, ptr %p
  %r = call i32 @callee(i32 %mode, ptr %p)
  ret i32 %r
}

; Memset-to-load forwarding converts the zero-filled integer to a null
; pointer, making the null check take the early exit.
define void @caller_memset_forward() {
; CHECK-LABEL: define void @caller_memset_forward() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[P:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr [[P]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    ret void
;
entry:
  %p = alloca ptr
  call void @init_memset(ptr %p)
  %x = load ptr, ptr %p
  call void @recursive_callee(ptr %x)
  ret void
}
