; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='module-inline' -inline-priority-mode=cost-benefit -S < %s | FileCheck %s

; Verify that the inliner does nothing for the call to @terminate after
; inlining @callee renders its containing basic block dead.

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-grtev4-linux-gnu"

define void @test_skip_dead_blocks() personality ptr null {
; CHECK-LABEL: define void @test_skip_dead_blocks() personality ptr null {
; CHECK-NEXT:    br label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    ret void
; CHECK:       [[BB2:.*:]]
; CHECK-NEXT:    [[TMP3:%.*]] = landingpad { ptr, i32 }
; CHECK-NEXT:            catch ptr null
; CHECK-NEXT:    call void @terminate()
; CHECK-NEXT:    unreachable
;
  %1 = invoke ptr @callee(ptr null, ptr null, ptr null)
  to label %2 unwind label %3

2:                                                ; preds = %0
  ret void

3:                                                ; preds = %0
  %4 = landingpad { ptr, i32 }
  catch ptr null
  call void @terminate()
  unreachable
}

define ptr @callee(ptr %0, ptr %1, ptr %2) {
; CHECK-LABEL: define ptr @callee(
; CHECK-SAME: ptr [[TMP0:%.*]], ptr [[TMP1:%.*]], ptr [[TMP2:%.*]]) {
; CHECK-NEXT:    ret ptr [[TMP0]]
;
  ret ptr %0
}

define void @terminate() {
; CHECK-LABEL: define void @terminate() {
; CHECK-NEXT:    unreachable
;
  unreachable
}
