; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O0 -mtriple=mipsel-linux-gnu -global-isel -mcpu=mips32r5 -mattr=+msa,+fp64,+nan2008 -verify-machineinstrs %s -o -| FileCheck %s -check-prefixes=P5600

declare <4 x float> @llvm.mips.fsqrt.w(<4 x float>)
define void @fsqrt_v4f32_builtin(<4 x float>* %a, <4 x float>* %c) {
; P5600-LABEL: fsqrt_v4f32_builtin:
; P5600:       # %bb.0: # %entry
; P5600-NEXT:    ld.w $w0, 0($4)
; P5600-NEXT:    fsqrt.w $w0, $w0
; P5600-NEXT:    st.w $w0, 0($5)
; P5600-NEXT:    jr $ra
; P5600-NEXT:    nop
entry:
  %0 = load <4 x float>, <4 x float>* %a, align 16
  %1 = tail call <4 x float> @llvm.mips.fsqrt.w(<4 x float> %0)
  store <4 x float> %1, <4 x float>* %c, align 16
  ret void
}

declare <2 x double> @llvm.mips.fsqrt.d(<2 x double>)
define void @fsqrt_v2f64_builtin(<2 x double>* %a, <2 x double>* %c) {
; P5600-LABEL: fsqrt_v2f64_builtin:
; P5600:       # %bb.0: # %entry
; P5600-NEXT:    ld.d $w0, 0($4)
; P5600-NEXT:    fsqrt.d $w0, $w0
; P5600-NEXT:    st.d $w0, 0($5)
; P5600-NEXT:    jr $ra
; P5600-NEXT:    nop
entry:
  %0 = load <2 x double>, <2 x double>* %a, align 16
  %1 = tail call <2 x double> @llvm.mips.fsqrt.d(<2 x double> %0)
  store <2 x double> %1, <2 x double>* %c, align 16
  ret void
}

