// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --prefix-filecheck-ir-name FOO_ --version 6
// REQUIRES: system-darwin


// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

struct S {
    int *__sized_by(l) bp;
    int *bp2 __sized_by(l+4);
    int l;
};

// CHECK-LABEL: define dso_local void @Test(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ARR:%.*]] = alloca [10 x i32], align 16
// CHECK-NEXT:    [[S:%.*]] = alloca [[STRUCT_S:%.*]], align 8
// CHECK-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[FOO_TMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP6:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[N:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[AGG_TEMP13:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[FOO_TMP14:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP17:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP20:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP23:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP24:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP43:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP46:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP47:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP71:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP79:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// CHECK-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY]], i64 10
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[UPPER]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP2]], align 8
// CHECK-NEXT:    [[ARRAYDECAY2:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// CHECK-NEXT:    [[UPPER3:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY2]], i64 10
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[FOO_TMP1]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[ARRAYDECAY2]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[FOO_TMP1]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[UPPER3]], ptr [[TMP4]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[FOO_TMP1]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[ARRAYDECAY2]], ptr [[TMP5]], align 8
// CHECK-NEXT:    br i1 true, label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2:![0-9]+]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    br i1 true, label %[[CONT5:.*]], label %[[TRAP4:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// CHECK:       [[TRAP4]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT5]]:
// CHECK-NEXT:    [[BP:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 0
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[TMP]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[BP]], align 8
// CHECK-NEXT:    [[BP2:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 1
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP6]], ptr align 8 [[FOO_TMP1]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP6]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR8:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR7]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP6]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB10:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR9]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP6]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB12:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR11]], align 8
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR8]], ptr [[BP2]], align 8
// CHECK-NEXT:    [[L:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 2
// CHECK-NEXT:    store i32 0, ptr [[L]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[S]], i64 20
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP6]], i8 0, i64 4, i1 false)
// CHECK-NEXT:    store i32 40, ptr [[N]], align 4
// CHECK-NEXT:    br label %[[HERE:.*]]
// CHECK:       [[HERE]]:
// CHECK-NEXT:    [[ARRAYDECAY15:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// CHECK-NEXT:    [[UPPER16:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY15]], i64 10
// CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[FOO_TMP14]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[ARRAYDECAY15]], ptr [[TMP7]], align 8
// CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[FOO_TMP14]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[UPPER16]], ptr [[TMP8]], align 8
// CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[FOO_TMP14]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[ARRAYDECAY15]], ptr [[TMP9]], align 8
// CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[FOO_TMP14]], i32 0, i32 0
// CHECK-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[TMP10]], align 8
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i32, ptr [[TMP11]], i64 1
// CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP13]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP12]], align 8
// CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[FOO_TMP14]], i32 0, i32 1
// CHECK-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[TMP13]], align 8
// CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP13]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[TMP14]], ptr [[TMP15]], align 8
// CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[FOO_TMP14]], i32 0, i32 2
// CHECK-NEXT:    [[TMP17:%.*]] = load ptr, ptr [[TMP16]], align 8
// CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP13]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[TMP17]], ptr [[TMP18]], align 8
// CHECK-NEXT:    [[ARRAYDECAY18:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// CHECK-NEXT:    [[UPPER19:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY18]], i64 10
// CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP17]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[ARRAYDECAY18]], ptr [[TMP19]], align 8
// CHECK-NEXT:    [[TMP20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP17]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[UPPER19]], ptr [[TMP20]], align 8
// CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP17]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[ARRAYDECAY18]], ptr [[TMP21]], align 8
// CHECK-NEXT:    [[TMP22:%.*]] = load i32, ptr [[N]], align 4
// CHECK-NEXT:    [[CONV:%.*]] = sext i32 [[TMP22]] to i64, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP20]], ptr align 8 [[AGG_TEMP13]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB22:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR21]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP24]], ptr align 8 [[AGG_TEMP13]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR25:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP24]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR26:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR25]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR27:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP24]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB28:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR27]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR29:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP24]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB30:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR29]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP23]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR26]], ptr [[TMP23]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP24:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP23]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB28]], ptr [[TMP24]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP23]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB30]], ptr [[TMP25]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR31:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP23]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR32:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR31]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP23]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB34:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR33]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR35:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP23]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB36:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR35]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB22]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR32]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META2]]
// CHECK-NEXT:    [[CMP:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_SUB]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP]], label %[[LAND_RHS:.*]], label %[[LAND_END:.*]], !annotation [[META2]]
// CHECK:       [[LAND_RHS]]:
// CHECK-NEXT:    [[CMP38:%.*]] = icmp sle i32 0, [[TMP22]], !annotation [[META2]]
// CHECK-NEXT:    br label %[[LAND_END]], !annotation [[META2]]
// CHECK:       [[LAND_END]]:
// CHECK-NEXT:    [[TMP26:%.*]] = phi i1 [ false, %[[HERE]] ], [ [[CMP38]], %[[LAND_RHS]] ], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TMP26]], label %[[CONT41:.*]], label %[[TRAP40:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// CHECK:       [[TRAP40]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT41]]:
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP22]], 4
// CHECK-NEXT:    [[CONV42:%.*]] = sext i32 [[ADD]] to i64
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP43]], ptr align 8 [[AGG_TEMP17]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR44:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP43]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB45:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR44]], align 8, !annotation [[META2]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP47]], ptr align 8 [[AGG_TEMP17]], i64 24, i1 false), !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR48:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP47]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR49:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR48]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR50:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP47]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB51:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR50]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR52:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP47]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB53:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR52]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP46]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR49]], ptr [[TMP27]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP46]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB51]], ptr [[TMP28]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP46]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB53]], ptr [[TMP29]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR54:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP46]], i32 0, i32 0, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_PTR55:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR54]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR56:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP46]], i32 0, i32 1, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_UB57:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR56]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR58:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP46]], i32 0, i32 2, !annotation [[META2]]
// CHECK-NEXT:    [[WIDE_PTR_LB59:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR58]], align 8, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_LHS_CAST60:%.*]] = ptrtoint ptr [[WIDE_PTR_UB45]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_RHS_CAST61:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR55]] to i64, !annotation [[META2]]
// CHECK-NEXT:    [[SUB_PTR_SUB62:%.*]] = sub i64 [[SUB_PTR_LHS_CAST60]], [[SUB_PTR_RHS_CAST61]], !annotation [[META2]]
// CHECK-NEXT:    [[CMP63:%.*]] = icmp sle i64 [[CONV42]], [[SUB_PTR_SUB62]], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[CMP63]], label %[[LAND_RHS65:.*]], label %[[LAND_END68:.*]], !annotation [[META2]]
// CHECK:       [[LAND_RHS65]]:
// CHECK-NEXT:    [[CMP66:%.*]] = icmp sle i64 0, [[CONV42]], !annotation [[META2]]
// CHECK-NEXT:    br label %[[LAND_END68]], !annotation [[META2]]
// CHECK:       [[LAND_END68]]:
// CHECK-NEXT:    [[TMP30:%.*]] = phi i1 [ false, %[[CONT41]] ], [ [[CMP66]], %[[LAND_RHS65]] ], !annotation [[META2]]
// CHECK-NEXT:    br i1 [[TMP30]], label %[[CONT70:.*]], label %[[TRAP69:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// CHECK:       [[TRAP69]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT70]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP71]], ptr align 8 [[AGG_TEMP13]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR72:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP71]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR73:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR72]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR74:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP71]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB75:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR74]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR76:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP71]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB77:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR76]], align 8
// CHECK-NEXT:    [[BP78:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR73]], ptr [[BP78]], align 8
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP79]], ptr align 8 [[AGG_TEMP17]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR80:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP79]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR81:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR80]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR82:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP79]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB83:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR82]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR84:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP79]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB85:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR84]], align 8
// CHECK-NEXT:    [[BP286:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR81]], ptr [[BP286]], align 8
// CHECK-NEXT:    [[L87:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 2
// CHECK-NEXT:    store i32 [[TMP22]], ptr [[L87]], align 8
// CHECK-NEXT:    ret void
//
void Test() {
    int arr[10];
    struct S s = {arr, arr, 0};
    int n = 10 * sizeof(int);
here:
    s.bp = &arr[1];
    s.bp2 = arr;
    s.l = n; // trap s.l > bounds of (s.bp)
}
//.
// CHECK: [[META2]] = !{!"bounds-safety-generic"}
//.
