// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 3


// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// Executable version of byte-count-attr-fields-assign.c

#include <ptrcheck.h>

struct S {
    int *__sized_by(l) bp;
    int *bp2 __sized_by(l+4);
    int l;
};

// CHECK-LABEL: define dso_local void @TestFail
// CHECK-SAME: () local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation [[META2:![0-9]+]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
//
void TestFail() {
    int arr[10];
    struct S s = {arr, arr, 0};
    int n = 10 * sizeof(int);
    s.bp = &arr[1];
    s.l = n; // run-time trap - s.l cannot be bigger than element count of &arr[1] (9) and s.1 + 1 cannot be bigger than element count of arr (10)
    s.bp2 = arr;
}

// CHECK-LABEL: define dso_local void @TestOK
// CHECK-SAME: () local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
void TestOK() {
  int arr[10];
  struct S s = {arr, arr, 0};
  s.bp = &arr[1];
  s.l = 9 * sizeof(int);
  s.bp2 = arr;
}

//.
// CHECK: [[META2]] = !{!"bounds-safety-generic"}
//.
