// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 3


// RUN: %clang_cc1 -O2  -fbounds-safety -triple x86_64 -emit-llvm %s -o - | FileCheck %s --check-prefix=CHECK-O2

#include <ptrcheck.h>

struct S {
    int *__counted_by(l) bp;
    int *bp2 __counted_by(l+1);
    int l;
};

// CHECK-O2-LABEL: define dso_local noundef i32 @foo
// CHECK-O2-SAME: () local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation [[META2:![0-9]+]]
// CHECK-O2-NEXT:    unreachable, !annotation [[META2]]
//
int foo () {
    int arr[10];
    struct S s = {arr, arr, 0};
    s.bp = &arr[1];
    s.l = 8;
    s.bp2 = arr;

    return s.bp2[9]; // trap : oob s.bp2[9]
}

// CHECK-O2-LABEL: define dso_local i32 @bar
// CHECK-O2-SAME: () local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    ret i32 undef
//
int bar () {
  int arr[10];
  struct S s = {arr, arr, 0};
  s.bp = &arr[1];
  s.l = 8;
  s.bp2 = arr;

  return s.bp2[8]; // ok
}
//.
// CHECK-O2: [[META2]] = !{!"bounds-safety-generic", !"bounds-safety-check-ptr-lt-upper-bound", !"bounds-safety-check-ptr-ge-lower-bound"}
//.
