// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6


// RUN: %clang_cc1 -O2  -fbounds-safety -triple x86_64 -emit-llvm %s -o - | FileCheck %s
#include <ptrcheck.h>
struct S {
  int *__counted_by(len) ptr;
  int *__counted_by(len - 1) ptr2;
  int len;
};

// CHECK-LABEL: define dso_local void @TestPtrFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestPtrFail() {
  int arr[10];
  struct S s = {arr, &arr[1], 10};
  s.ptr = s.ptr2; // trap! bounds_of(s.ptr2) == 9 < 10
  s.ptr2 = arr;
  s.len = 10;
}

// CHECK-LABEL: define dso_local void @TestPtrOK(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void TestPtrOK() {
  int arr[10];
  struct S s = {arr, &arr[1], 10};
  s.ptr = s.ptr2; // ok: bounds_of(s.ptr2) == 9 <= 9
  s.ptr2 += 1; // bounds_of(s.ptr2 + 1) == 8 <= 8
  s.len = 9;
}

// CHECK-LABEL: define dso_local void @TestPtrLBFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ARR:%.*]] = alloca [10 x i32], align 16
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[ARR]]) #[[ATTR6:[0-9]+]]
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i64 40
// CHECK-NEXT:    [[BOUND_PTR_ARITH17:%.*]] = getelementptr i8, ptr [[ARR]], i64 -8
// CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp ugt ptr [[BOUND_PTR_ARITH17]], [[ADD_PTR]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[CMP41_NOT:%.*]] = icmp ugt ptr [[ARR]], [[BOUND_PTR_ARITH17]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP_NOT]], [[CMP41_NOT]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[TRAP:.*]], label %[[CONT56:.*]], {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT56]]:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[ARR]]) #[[ATTR6]]
// CHECK-NEXT:    ret void
//
void TestPtrLBFail() {
  int arr[10];
  struct S s = {arr, &arr[1], 10};
  s.ptr = s.ptr - 2; // trap! ptr < lb
  s.ptr2 = arr;
  s.len = 10;
}

// CHECK-LABEL: define dso_local void @TestPtrUBFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestPtrUBFail() {
  int arr[10];
  struct S s = {arr, &arr[1], 10};
  s.ptr = s.ptr;
  s.ptr2 = s.ptr2 + 10; // trap! ptr2 oob
  s.len = 1;
}
