// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6

// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s --check-prefix=CHECK-O0
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s --check-prefix=CHECK-O2

#include <ptrcheck.h>

struct S {
    int *__counted_by(l) bp;
    int *bp2 __counted_by(l+1);
    int l;
};

// COM: rdar://154226004 (Seemingly necessary range check (ptr <= ptr + 1) has been removed after fixing materialization bug for LValues)
// COM: These checks preserve as expected: lower <= arrayidx66(ptr + 8), tmp41 (ptr + 9) <= upper
// COM: This check has been dropped. Not sure why: arrayidx66(ptr + 8) <= tmp41(ptr + 9)
// CHECK-O0-LABEL: define dso_local i32 @foo(
// CHECK-O0-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-O0-NEXT:  [[ENTRY:.*:]]
// CHECK-O0-NEXT:    [[ARR:%.*]] = alloca [10 x i32], align 16
// CHECK-O0-NEXT:    [[S:%.*]] = alloca [[STRUCT_S:%.*]], align 8
// CHECK-O0-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[TMP_TMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP6:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP13:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[TMP_TMP14:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP17:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP24:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP33:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[AGG_TEMP42:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP57:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP75:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// CHECK-O0-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY]], i64 10
// CHECK-O0-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP0]], align 8
// CHECK-O0-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER]], ptr [[TMP1]], align 8
// CHECK-O0-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP2]], align 8
// CHECK-O0-NEXT:    [[ARRAYDECAY2:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// CHECK-O0-NEXT:    [[UPPER3:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY2]], i64 10
// CHECK-O0-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP1]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY2]], ptr [[TMP3]], align 8
// CHECK-O0-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP1]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER3]], ptr [[TMP4]], align 8
// CHECK-O0-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP1]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY2]], ptr [[TMP5]], align 8
// CHECK-O0-NEXT:    br i1 true, label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT]]:
// CHECK-O0-NEXT:    br i1 true, label %[[CONT5:.*]], label %[[TRAP4:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP4]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT5]]:
// CHECK-O0-NEXT:    [[BP:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 0
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[TMP]], i64 24, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[BP]], align 8
// CHECK-O0-NEXT:    [[BP2:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 1
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP6]], ptr align 8 [[TMP_TMP1]], i64 24, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP6]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR8:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR7]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP6]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB10:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR9]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP6]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB12:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR11]], align 8
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR8]], ptr [[BP2]], align 8
// CHECK-O0-NEXT:    [[L:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 2
// CHECK-O0-NEXT:    store i32 0, ptr [[L]], align 8
// CHECK-O0-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[S]], i64 20
// CHECK-O0-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP6]], i8 0, i64 4, i1 false)
// CHECK-O0-NEXT:    [[ARRAYDECAY15:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// CHECK-O0-NEXT:    [[UPPER16:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY15]], i64 10
// CHECK-O0-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP14]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY15]], ptr [[TMP7]], align 8
// CHECK-O0-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP14]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER16]], ptr [[TMP8]], align 8
// CHECK-O0-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP14]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY15]], ptr [[TMP9]], align 8
// CHECK-O0-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP14]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[TMP10]], align 8
// CHECK-O0-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i32, ptr [[TMP11]], i64 1
// CHECK-O0-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP13]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP12]], align 8
// CHECK-O0-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP14]], i32 0, i32 1
// CHECK-O0-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[TMP13]], align 8
// CHECK-O0-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP13]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[TMP14]], ptr [[TMP15]], align 8
// CHECK-O0-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP14]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP17:%.*]] = load ptr, ptr [[TMP16]], align 8
// CHECK-O0-NEXT:    [[TMP18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP13]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[TMP17]], ptr [[TMP18]], align 8
// CHECK-O0-NEXT:    [[ARRAYDECAY18:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// CHECK-O0-NEXT:    [[UPPER19:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY18]], i64 10
// CHECK-O0-NEXT:    [[TMP19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP17]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY18]], ptr [[TMP19]], align 8
// CHECK-O0-NEXT:    [[TMP20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP17]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER19]], ptr [[TMP20]], align 8
// CHECK-O0-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP17]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY18]], ptr [[TMP21]], align 8
// CHECK-O0-NEXT:    br i1 true, label %[[CONT21:.*]], label %[[TRAP20:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP20]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT21]]:
// CHECK-O0-NEXT:    br i1 true, label %[[CONT23:.*]], label %[[TRAP22:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP22]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT23]]:
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP24]], ptr align 8 [[AGG_TEMP13]], i64 24, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR25:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP24]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR26:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR25]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR27:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP24]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB28:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR27]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR29:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP24]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB30:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR29]], align 8
// CHECK-O0-NEXT:    [[BP31:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR26]], ptr [[BP31]], align 8
// CHECK-O0-NEXT:    [[L32:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 2
// CHECK-O0-NEXT:    store i32 8, ptr [[L32]], align 8
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP33]], ptr align 8 [[AGG_TEMP17]], i64 24, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR34:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP33]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR35:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR34]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR36:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP33]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB37:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR36]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR38:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP33]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB39:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR38]], align 8
// CHECK-O0-NEXT:    [[BP240:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR35]], ptr [[BP240]], align 8
// CHECK-O0-NEXT:    store i32 0, ptr [[I]], align 4
// CHECK-O0-NEXT:    br label %[[FOR_COND:.*]]
// CHECK-O0:       [[FOR_COND]]:
// CHECK-O0-NEXT:    [[TMP22:%.*]] = load i32, ptr [[I]], align 4
// CHECK-O0-NEXT:    [[L41:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP23:%.*]] = load i32, ptr [[L41]], align 8
// CHECK-O0-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP22]], [[TMP23]]
// CHECK-O0-NEXT:    br i1 [[CMP]], label %[[FOR_BODY:.*]], label %[[FOR_END:.*]]
// CHECK-O0:       [[FOR_BODY]]:
// CHECK-O0-NEXT:    [[TMP24:%.*]] = load i32, ptr [[I]], align 4
// CHECK-O0-NEXT:    [[L43:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP25:%.*]] = load i32, ptr [[L43]], align 8
// CHECK-O0-NEXT:    [[BP44:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP26:%.*]] = load ptr, ptr [[BP44]], align 8
// CHECK-O0-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP25]] to i64
// CHECK-O0-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP26]], i64 [[IDX_EXT]]
// CHECK-O0-NEXT:    [[TMP27:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP42]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[TMP26]], ptr [[TMP27]], align 8
// CHECK-O0-NEXT:    [[TMP28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP42]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP28]], align 8
// CHECK-O0-NEXT:    [[TMP29:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP42]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[TMP26]], ptr [[TMP29]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR45:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP42]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR46:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR45]], align 8
// CHECK-O0-NEXT:    [[TMP30:%.*]] = load i32, ptr [[I]], align 4
// CHECK-O0-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP30]] to i64
// CHECK-O0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR46]], i64 [[IDXPROM]]
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR47:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP42]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB48:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR47]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR49:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP42]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB50:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR49]], align 8
// CHECK-O0-NEXT:    [[TMP31:%.*]] = getelementptr i32, ptr [[ARRAYIDX]], i64 1, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[TMP32:%.*]] = icmp ule ptr [[TMP31]], [[WIDE_PTR_UB48]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP32]], label %[[CONT52:.*]], label %[[TRAP51:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP51]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT52]]:
// CHECK-O0-NEXT:    [[TMP33:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP31]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP33]], label %[[CONT54:.*]], label %[[TRAP53:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP53]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT54]]:
// CHECK-O0-NEXT:    [[TMP34:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB50]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP34]], label %[[CONT56:.*]], label %[[TRAP55:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP55]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT56]]:
// CHECK-O0-NEXT:    store i32 [[TMP24]], ptr [[ARRAYIDX]], align 4
// CHECK-O0-NEXT:    br label %[[FOR_INC:.*]]
// CHECK-O0:       [[FOR_INC]]:
// CHECK-O0-NEXT:    [[TMP35:%.*]] = load i32, ptr [[I]], align 4
// CHECK-O0-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP35]], 1
// CHECK-O0-NEXT:    store i32 [[INC]], ptr [[I]], align 4
// CHECK-O0-NEXT:    br label %[[FOR_COND]], !llvm.loop [[LOOP5:![0-9]+]]
// CHECK-O0:       [[FOR_END]]:
// CHECK-O0-NEXT:    [[L58:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP36:%.*]] = load i32, ptr [[L58]], align 8
// CHECK-O0-NEXT:    [[BP259:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 1
// CHECK-O0-NEXT:    [[TMP37:%.*]] = load ptr, ptr [[BP259]], align 8
// CHECK-O0-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP36]], 1
// CHECK-O0-NEXT:    [[IDX_EXT60:%.*]] = sext i32 [[ADD]] to i64
// CHECK-O0-NEXT:    [[ADD_PTR61:%.*]] = getelementptr inbounds i32, ptr [[TMP37]], i64 [[IDX_EXT60]]
// CHECK-O0-NEXT:    [[TMP38:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP57]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[TMP37]], ptr [[TMP38]], align 8
// CHECK-O0-NEXT:    [[TMP39:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP57]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[ADD_PTR61]], ptr [[TMP39]], align 8
// CHECK-O0-NEXT:    [[TMP40:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP57]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[TMP37]], ptr [[TMP40]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR62:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP57]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR63:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR62]], align 8
// CHECK-O0-NEXT:    [[ARRAYIDX64:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR63]], i64 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR65:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP57]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB66:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR65]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR67:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP57]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB68:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR67]], align 8
// CHECK-O0-NEXT:    [[TMP41:%.*]] = getelementptr i32, ptr [[ARRAYIDX64]], i64 1, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[TMP42:%.*]] = icmp ule ptr [[TMP41]], [[WIDE_PTR_UB66]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP42]], label %[[CONT70:.*]], label %[[TRAP69:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP69]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT70]]:
// CHECK-O0-NEXT:    [[TMP43:%.*]] = icmp ule ptr [[ARRAYIDX64]], [[TMP41]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP43]], label %[[CONT72:.*]], label %[[TRAP71:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP71]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT72]]:
// CHECK-O0-NEXT:    [[TMP44:%.*]] = icmp uge ptr [[ARRAYIDX64]], [[WIDE_PTR_LB68]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP44]], label %[[CONT74:.*]], label %[[TRAP73:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP73]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT74]]:
// CHECK-O0-NEXT:    [[TMP45:%.*]] = load i32, ptr [[ARRAYIDX64]], align 4
// CHECK-O0-NEXT:    [[L76:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP46:%.*]] = load i32, ptr [[L76]], align 8
// CHECK-O0-NEXT:    [[BP77:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP47:%.*]] = load ptr, ptr [[BP77]], align 8
// CHECK-O0-NEXT:    [[IDX_EXT78:%.*]] = sext i32 [[TMP46]] to i64
// CHECK-O0-NEXT:    [[ADD_PTR79:%.*]] = getelementptr inbounds i32, ptr [[TMP47]], i64 [[IDX_EXT78]]
// CHECK-O0-NEXT:    [[TMP48:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP75]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[TMP47]], ptr [[TMP48]], align 8
// CHECK-O0-NEXT:    [[TMP49:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP75]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[ADD_PTR79]], ptr [[TMP49]], align 8
// CHECK-O0-NEXT:    [[TMP50:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP75]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[TMP47]], ptr [[TMP50]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR80:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP75]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR81:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR80]], align 8
// CHECK-O0-NEXT:    [[ARRAYIDX82:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR81]], i64 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR83:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP75]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB84:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR83]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR85:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP75]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB86:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR85]], align 8
// CHECK-O0-NEXT:    [[TMP51:%.*]] = getelementptr i32, ptr [[ARRAYIDX82]], i64 1, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[TMP52:%.*]] = icmp ule ptr [[TMP51]], [[WIDE_PTR_UB84]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP52]], label %[[CONT88:.*]], label %[[TRAP87:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP87]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT88]]:
// CHECK-O0-NEXT:    [[TMP53:%.*]] = icmp ule ptr [[ARRAYIDX82]], [[TMP51]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP53]], label %[[CONT90:.*]], label %[[TRAP89:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP89]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT90]]:
// CHECK-O0-NEXT:    [[TMP54:%.*]] = icmp uge ptr [[ARRAYIDX82]], [[WIDE_PTR_LB86]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP54]], label %[[CONT92:.*]], label %[[TRAP91:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP91]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT92]]:
// CHECK-O0-NEXT:    [[TMP55:%.*]] = load i32, ptr [[ARRAYIDX82]], align 4
// CHECK-O0-NEXT:    [[ADD93:%.*]] = add nsw i32 [[TMP45]], [[TMP55]]
// CHECK-O0-NEXT:    ret i32 [[ADD93]]
//
// CHECK-O2-LABEL: define dso_local noundef i32 @foo(
// CHECK-O2-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-O2-NEXT:  [[TRAP:.*:]]
// CHECK-O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR2:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
int foo () {
    int arr[10];
    struct S s = {arr, arr, 0};
    s.bp = &arr[1];
    s.l = 8;
    s.bp2 = arr;
    // run-time check here

    for (int i = 0; i < s.l; ++i)
        s.bp[i] = i;

    return s.bp2[8] + s.bp[8]; // trap : oob s.bp[8]
}


//.
// CHECK-O0: [[LOOP5]] = distinct !{[[LOOP5]], [[META6:![0-9]+]]}
// CHECK-O0: [[META6]] = !{!"llvm.loop.mustprogress"}
//.
