// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --version 6

// RUN: %clang_cc1 -O2 -fbounds-safety -emit-llvm -triple x86_64 %s -o - | FileCheck %s
#include <ptrcheck.h>

struct S {
    int len;
    int *__counted_by(len) ptr;
};

// CHECK-LABEL: define dso_local void @TestInitFail1(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestInitFail1() {
    int arr[9] = {0};
    int *ptr = arr;
    struct S s = {10, ptr}; // trap:
}

// CHECK-LABEL: define dso_local void @TestInitFail2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestInitFail2() {
  int arr[9] = {0};
  int *ptr = arr;
  int len = -1;
  struct S s = {len, ptr}; // trap:
}

struct SU {
  unsigned long len;
  int *__counted_by(len) ptr;
};

// CHECK-LABEL: define dso_local void @TestUInitFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestUInitFail() {
  int arr[9] = {0};
  int *ptr = arr;
  long len = -1;
  struct SU s = {len, ptr}; // trap:
}

// CHECK-LABEL: define dso_local void @TestUInitOK(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void TestUInitOK() {
  int arr[9] = {0};
  int *ptr = arr;
  long len = 8;
  struct SU s = {len, ptr};
}

// CHECK-LABEL: define dso_local void @TestOK(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void TestOK() {
  int arr[9] = {0};
  int *ptr = arr;
  struct S s = {9, ptr};
}

// CHECK-LABEL: define dso_local void @TestAccessOK(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void TestAccessOK() {
  int arr[9] = {0};
  int *ptr = arr;
  struct S s = {9, ptr};
  (void)s.ptr[8];
}

// CHECK-LABEL: define dso_local void @TestAccessFail(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestAccessFail() {
  int arr[9] = {0};
  int *ptr = arr;
  struct S s = {9, ptr};
  (void)s.ptr[9];
}

// CHECK-LABEL: define dso_local void @TestAccessFail2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestAccessFail2() {
  int arr[9] = {0};
  int *ptr = arr;
  struct S s = {9, ptr};
  (void)s.ptr[-1];
}

// CHECK-LABEL: define dso_local void @TestAccessFail3(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void TestAccessFail3() {
  int arr[9] = {0};
  int *ptr = arr;
  struct S s = {9, ptr};
  (void)*(s.ptr + 9);
}
