// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --version 6


// RUN: %clang_cc1 -O0  -fbounds-safety -emit-llvm -triple x86_64 %s -o - | FileCheck %s --check-prefix=CHECK-O0
#include <ptrcheck.h>

struct S {
    int len;
    int *__counted_by(len) ptr;
};

// CHECK-O0-LABEL: define dso_local void @Test(
// CHECK-O0-SAME: i32 noundef [[VAR:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-O0-NEXT:  [[ENTRY:.*:]]
// CHECK-O0-NEXT:    [[VAR_ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[S:%.*]] = alloca [[STRUCT_S:%.*]], align 8
// CHECK-O0-NEXT:    store i32 [[VAR]], ptr [[VAR_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[VAR_ADDR]], align 4
// CHECK-O0-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 0, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[CMP]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT]]:
// CHECK-O0-NEXT:    [[LEN:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 0
// CHECK-O0-NEXT:    store i32 [[TMP0]], ptr [[LEN]], align 8
// CHECK-O0-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[S]], i64 4
// CHECK-O0-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP1]], i8 0, i64 4, i1 false)
// CHECK-O0-NEXT:    [[PTR:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr null, ptr [[PTR]], align 8
// CHECK-O0-NEXT:    ret void
//
void Test(int var) {
    struct S s = {var};
}
