; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=instcombine,sccp,dce < %s | FileCheck %s

; Scenario 1: Returned attribute
; A noinline function returns its argument.
; The call instruction should be preserved, even though the return value can be
; simplified by InstCombine.

declare ptr @demo1(ptr returned) noinline memory(none)

define ptr @foo1(ptr %arg) {
; CHECK-LABEL: @foo1(
; CHECK-NEXT:    [[CALL:%.*]] = call ptr @demo1(ptr [[ARG:%.*]])
; CHECK-NEXT:    ret ptr [[CALL]]
;
  %call = call ptr @demo1(ptr %arg)
  ret ptr %call
}

; Scenario 2: Constant return value
; A noinline function returns a constant.
; The call instruction should be preserved, even though the return value
; is constant-foldable by SCCP.

define internal ptr @demo2() noinline memory(none) {
; CHECK-LABEL: @demo2(
; CHECK-NEXT:    ret ptr null
;
  ret ptr null
}

define ptr @foo2() {
; CHECK-LABEL: @foo2(
; CHECK-NEXT:    [[CALL:%.*]] = call ptr @demo2()
; CHECK-NEXT:    ret ptr [[CALL]]
;
  %call = call ptr @demo2()
  ret ptr %call
}

; Scenario 3: Unused return value
; A noinline function has no side effects, and its return value is unused.
; The call instruction should be preserved by DCE.

declare i32 @demo3() noinline memory(none)

define void @foo3() {
; CHECK-LABEL: @foo3(
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @demo3()
; CHECK-NEXT:    ret void
;
  %call = call i32 @demo3()
  ret void
}
