// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv32 -target-feature +zalrsc -disable-O0-optnone \
// RUN:   -emit-llvm %s -o - | opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefixes=CHECK-RV32 %s
// RUN: %clang_cc1 -triple riscv64 -target-feature +zalrsc -disable-O0-optnone \
// RUN:   -emit-llvm %s -o - | opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s

#include <stdint.h>
#include <riscv_atomic.h>

// CHECK-RV32-LABEL: define dso_local i32 @zalrsc_lr_w_none
// CHECK-RV32-SAME: (ptr noundef [[PTR:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.lr.w(ptr [[PTR]], i32 0)
// CHECK-RV32-NEXT:    ret i32 [[TMP0]]
//
// CHECK-RV64-LABEL: define dso_local signext i32 @zalrsc_lr_w_none
// CHECK-RV64-SAME: (ptr noundef [[PTR:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.lr.w(ptr [[PTR]], i32 0)
// CHECK-RV64-NEXT:    ret i32 [[TMP0]]
//
int zalrsc_lr_w_none(int* ptr) {
  return __riscv_lr_w(ptr, __RISCV_ORDERING_NONE);
}

// CHECK-RV32-LABEL: define dso_local i32 @zalrsc_lr_w_aq
// CHECK-RV32-SAME: (ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.lr.w(ptr [[PTR]], i32 1)
// CHECK-RV32-NEXT:    ret i32 [[TMP0]]
//
// CHECK-RV64-LABEL: define dso_local signext i32 @zalrsc_lr_w_aq
// CHECK-RV64-SAME: (ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.lr.w(ptr [[PTR]], i32 1)
// CHECK-RV64-NEXT:    ret i32 [[TMP0]]
//
int zalrsc_lr_w_aq(int* ptr) {
  return __riscv_lr_w(ptr, __RISCV_ORDERING_AQ);
}

// CHECK-RV32-LABEL: define dso_local i32 @zalrsc_lr_w_rl
// CHECK-RV32-SAME: (ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.lr.w(ptr [[PTR]], i32 2)
// CHECK-RV32-NEXT:    ret i32 [[TMP0]]
//
// CHECK-RV64-LABEL: define dso_local signext i32 @zalrsc_lr_w_rl
// CHECK-RV64-SAME: (ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.lr.w(ptr [[PTR]], i32 2)
// CHECK-RV64-NEXT:    ret i32 [[TMP0]]
//
int zalrsc_lr_w_rl(int* ptr) {
  return __riscv_lr_w(ptr, __RISCV_ORDERING_RL);
}

// CHECK-RV32-LABEL: define dso_local i32 @zalrsc_lr_w_aqrl
// CHECK-RV32-SAME: (ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.lr.w(ptr [[PTR]], i32 3)
// CHECK-RV32-NEXT:    ret i32 [[TMP0]]
//
// CHECK-RV64-LABEL: define dso_local signext i32 @zalrsc_lr_w_aqrl
// CHECK-RV64-SAME: (ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.lr.w(ptr [[PTR]], i32 3)
// CHECK-RV64-NEXT:    ret i32 [[TMP0]]
//
int zalrsc_lr_w_aqrl(int* ptr) {
  return __riscv_lr_w(ptr, __RISCV_ORDERING_AQ_RL);
}

// CHECK-RV32-LABEL: define dso_local i32 @zalrsc_sc_w_none
// CHECK-RV32-SAME: (i32 noundef [[V:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sc.w(i32 [[V]], ptr [[PTR]], i32 0)
// CHECK-RV32-NEXT:    ret i32 [[TMP0]]
//
// CHECK-RV64-LABEL: define dso_local signext i32 @zalrsc_sc_w_none
// CHECK-RV64-SAME: (i32 noundef signext [[V:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sc.w(i32 [[V]], ptr [[PTR]], i32 0)
// CHECK-RV64-NEXT:    ret i32 [[TMP0]]
//
int zalrsc_sc_w_none(int v, int* ptr) {
  return __riscv_sc_w(v, ptr, __RISCV_ORDERING_NONE);
}

// CHECK-RV32-LABEL: define dso_local i32 @zalrsc_sc_w_aq
// CHECK-RV32-SAME: (i32 noundef [[V:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sc.w(i32 [[V]], ptr [[PTR]], i32 1)
// CHECK-RV32-NEXT:    ret i32 [[TMP0]]
//
// CHECK-RV64-LABEL: define dso_local signext i32 @zalrsc_sc_w_aq
// CHECK-RV64-SAME: (i32 noundef signext [[V:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sc.w(i32 [[V]], ptr [[PTR]], i32 1)
// CHECK-RV64-NEXT:    ret i32 [[TMP0]]
//
int zalrsc_sc_w_aq(int v, int* ptr) {
  return __riscv_sc_w(v, ptr, __RISCV_ORDERING_AQ);
}

// CHECK-RV32-LABEL: define dso_local i32 @zalrsc_sc_w_rl
// CHECK-RV32-SAME: (i32 noundef [[V:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sc.w(i32 [[V]], ptr [[PTR]], i32 2)
// CHECK-RV32-NEXT:    ret i32 [[TMP0]]
//
// CHECK-RV64-LABEL: define dso_local signext i32 @zalrsc_sc_w_rl
// CHECK-RV64-SAME: (i32 noundef signext [[V:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sc.w(i32 [[V]], ptr [[PTR]], i32 2)
// CHECK-RV64-NEXT:    ret i32 [[TMP0]]
//
int zalrsc_sc_w_rl(int v, int* ptr) {
  return __riscv_sc_w(v, ptr, __RISCV_ORDERING_RL);
}

// CHECK-RV32-LABEL: define dso_local i32 @zalrsc_sc_w_aqrl
// CHECK-RV32-SAME: (i32 noundef [[V:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sc.w(i32 [[V]], ptr [[PTR]], i32 3)
// CHECK-RV32-NEXT:    ret i32 [[TMP0]]
//
// CHECK-RV64-LABEL: define dso_local signext i32 @zalrsc_sc_w_aqrl
// CHECK-RV64-SAME: (i32 noundef signext [[V:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sc.w(i32 [[V]], ptr [[PTR]], i32 3)
// CHECK-RV64-NEXT:    ret i32 [[TMP0]]
//
int zalrsc_sc_w_aqrl(int v, int* ptr) {
  return __riscv_sc_w(v, ptr, __RISCV_ORDERING_AQ_RL);
}

#if __riscv_xlen == 64
// CHECK-RV64-LABEL: define dso_local i64 @zalrsc_lr_d_none
// CHECK-RV64-SAME: (ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.lr.d(ptr [[PTR]], i32 0)
// CHECK-RV64-NEXT:    ret i64 [[TMP0]]
//
int64_t zalrsc_lr_d_none(int64_t* ptr) {
  return __riscv_lr_d(ptr, __RISCV_ORDERING_NONE);
}

// CHECK-RV64-LABEL: define dso_local i64 @zalrsc_lr_d_aq
// CHECK-RV64-SAME: (ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.lr.d(ptr [[PTR]], i32 1)
// CHECK-RV64-NEXT:    ret i64 [[TMP0]]
//
int64_t zalrsc_lr_d_aq(int64_t* ptr) {
  return __riscv_lr_d(ptr, __RISCV_ORDERING_AQ);
}

// CHECK-RV64-LABEL: define dso_local i64 @zalrsc_lr_d_rl
// CHECK-RV64-SAME: (ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.lr.d(ptr [[PTR]], i32 2)
// CHECK-RV64-NEXT:    ret i64 [[TMP0]]
//
int64_t zalrsc_lr_d_rl(int64_t* ptr) {
  return __riscv_lr_d(ptr, __RISCV_ORDERING_RL);
}

// CHECK-RV64-LABEL: define dso_local i64 @zalrsc_lr_d_aqrl
// CHECK-RV64-SAME: (ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.lr.d(ptr [[PTR]], i32 3)
// CHECK-RV64-NEXT:    ret i64 [[TMP0]]
//
int64_t zalrsc_lr_d_aqrl(int64_t* ptr) {
  return __riscv_lr_d(ptr, __RISCV_ORDERING_AQ_RL);
}

// CHECK-RV64-LABEL: define dso_local i64 @zalrsc_sc_d_none
// CHECK-RV64-SAME: (i64 noundef [[V:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.sc.d(i64 [[V]], ptr [[PTR]], i32 0)
// CHECK-RV64-NEXT:    ret i64 [[TMP0]]
//
int64_t zalrsc_sc_d_none(int64_t v, int64_t* ptr) {
  return __riscv_sc_d(v, ptr, __RISCV_ORDERING_NONE);
}

// CHECK-RV64-LABEL: define dso_local i64 @zalrsc_sc_d_aq
// CHECK-RV64-SAME: (i64 noundef [[V:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.sc.d(i64 [[V]], ptr [[PTR]], i32 1)
// CHECK-RV64-NEXT:    ret i64 [[TMP0]]
//
int64_t zalrsc_sc_d_aq(int64_t v, int64_t* ptr) {
  return __riscv_sc_d(v, ptr, __RISCV_ORDERING_AQ);
}

// CHECK-RV64-LABEL: define dso_local i64 @zalrsc_sc_d_rl
// CHECK-RV64-SAME: (i64 noundef [[V:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.sc.d(i64 [[V]], ptr [[PTR]], i32 2)
// CHECK-RV64-NEXT:    ret i64 [[TMP0]]
//
int64_t zalrsc_sc_d_rl(int64_t v, int64_t* ptr) {
  return __riscv_sc_d(v, ptr, __RISCV_ORDERING_RL);
}

// CHECK-RV64-LABEL: define dso_local i64 @zalrsc_sc_d_aqrl
// CHECK-RV64-SAME: (i64 noundef [[V:%.*]], ptr noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.sc.d(i64 [[V]], ptr [[PTR]], i32 3)
// CHECK-RV64-NEXT:    ret i64 [[TMP0]]
//
int64_t zalrsc_sc_d_aqrl(int64_t v, int64_t* ptr) {
  return __riscv_sc_d(v, ptr, __RISCV_ORDERING_AQ_RL);
}

#endif
