name: Checkout Baseline Tooling
description: >-
  Checkout the baseline tooling scripts prior to running any pre-commit hooks
  or other GH action or workflow scripts.

runs:
  using: composite
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
        sparse-checkout: |
          llvm/utils/git/
          .ci/
          .github/
        ref: main
        path: baseline-scripts
