// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +zicsr -emit-llvm %s -o - \
// RUN:     -disable-O0-optnone | opt -S -passes=mem2reg \
// RUN:     | FileCheck %s  -check-prefix=RV32ZICSR
// RUN: %clang_cc1 -triple riscv64 -target-feature +zicsr -emit-llvm %s -o - \
// RUN:     -disable-O0-optnone | opt -S -passes=mem2reg \
// RUN:     | FileCheck %s  -check-prefix=RV64ZICSR

// RV32ZICSR-LABEL: @readcsr(
// RV32ZICSR-NEXT:  entry:
// RV32ZICSR-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.csrr(i32 3)
// RV32ZICSR-NEXT:    ret i32 [[TMP0]]
//
// RV64ZICSR-LABEL: @readcsr(
// RV64ZICSR-NEXT:  entry:
// RV64ZICSR-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.csrr64(i64 3)
// RV64ZICSR-NEXT:    ret i64 [[TMP0]]
//
unsigned long readcsr() {
  return __builtin_riscv_csrr(3);
}

// RV32ZICSR-LABEL: @readcsr_arbitrary(
// RV32ZICSR-NEXT:  entry:
// RV32ZICSR-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.csrr(i32 333)
// RV32ZICSR-NEXT:    ret i32 [[TMP0]]
//
// RV64ZICSR-LABEL: @readcsr_arbitrary(
// RV64ZICSR-NEXT:  entry:
// RV64ZICSR-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.csrr64(i64 333)
// RV64ZICSR-NEXT:    ret i64 [[TMP0]]
//
unsigned long readcsr_arbitrary() {
  return __builtin_riscv_csrr(333);
}

// RV32ZICSR-LABEL: @writecsr(
// RV32ZICSR-NEXT:  entry:
// RV32ZICSR-NEXT:    call void @llvm.riscv.csrw(i32 3, i32 [[D:%.*]])
// RV32ZICSR-NEXT:    ret void
//
// RV64ZICSR-LABEL: @writecsr(
// RV64ZICSR-NEXT:  entry:
// RV64ZICSR-NEXT:    call void @llvm.riscv.csrw64(i64 3, i64 [[D:%.*]])
// RV64ZICSR-NEXT:    ret void
//
void writecsr(unsigned long d) {
  return __builtin_riscv_csrw(3, d);
}

// RV32ZICSR-LABEL: @writecsr_arbitrary(
// RV32ZICSR-NEXT:  entry:
// RV32ZICSR-NEXT:    call void @llvm.riscv.csrw(i32 333, i32 [[D:%.*]])
// RV32ZICSR-NEXT:    ret void
//
// RV64ZICSR-LABEL: @writecsr_arbitrary(
// RV64ZICSR-NEXT:  entry:
// RV64ZICSR-NEXT:    call void @llvm.riscv.csrw64(i64 333, i64 [[D:%.*]])
// RV64ZICSR-NEXT:    ret void
//
void writecsr_arbitrary(unsigned long d) {
  return __builtin_riscv_csrw(333, d);
}
