# Create symbolic links for testing.

FILE(GLOB LIBOMP_ARGOBOTS_LIBS "${LIBOMP_ARGOBOTS_INSTALL_DIR}/lib/${SHARED_LIBRARY_PREFIX}*${SHARED_LIBRARY_SUFFIX}*")
foreach(LIBOMP_ARGOBOTS_LIB IN LISTS LIBOMP_ARGOBOTS_LIBS)
  get_filename_component(LIBOMP_ARGOBOTS_LIB_NAME "${LIBOMP_ARGOBOTS_LIB}" NAME)
  execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink "${LIBOMP_ARGOBOTS_LIB}" "${LIBOMP_ARGOBOTS_LIB_NAME}"
    WORKING_DIRECTORY ${LIBBOLT_LIBRARY_DIR}
  )
endforeach()
execute_process(
  COMMAND ${CMAKE_COMMAND} -E create_symlink ${LIBOMP_ARGOBOTS_INSTALL_DIR}/include/abt.h abt.h
    WORKING_DIRECTORY ${LIBBOLT_INCLUDE_DIR}
)
