; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=consthoist -consthoist-gep -S -o - %s | FileCheck %s

target datalayout = "e-m:e-p:32:32-i64:64-v128:64:128-a:0:32-n32-S64"
target triple = "thumbv6m-none--musleabi"

%0 = type { [10 x i32], [10 x i16] }

@global = external local_unnamed_addr global %0, align 4

define void @test_inbounds() {
; CHECK-LABEL: @test_inbounds(
; CHECK-NEXT:  bb:
; CHECK-NEXT:    [[CONST:%.*]] = bitcast ptr getelementptr inbounds ([[TMP0:%.*]], ptr @global, i32 0, i32 1, i32 0) to ptr
; CHECK-NEXT:    store i16 undef, ptr [[CONST]], align 2
; CHECK-NEXT:    [[MAT_GEP:%.*]] = getelementptr i8, ptr [[CONST]], i32 2
; CHECK-NEXT:    store i16 undef, ptr [[MAT_GEP]], align 2
; CHECK-NEXT:    [[MAT_GEP1:%.*]] = getelementptr i8, ptr [[CONST]], i32 20
; CHECK-NEXT:    store i16 undef, ptr [[MAT_GEP1]], align 2
; CHECK-NEXT:    ret void
;
bb:
  store i16 undef, ptr getelementptr inbounds (%0, ptr @global, i32 0, i32 1, i32 0)
  store i16 undef, ptr getelementptr inbounds (%0, ptr @global, i32 0, i32 1, i32 1)
  store i16 undef, ptr getelementptr inbounds (%0, ptr @global, i32 0, i32 1, i32 10)
  ret void
}

define dso_local void @test_non_inbounds() {
; CHECK-LABEL: @test_non_inbounds(
; CHECK-NEXT:  bb:
; CHECK-NEXT:    store i16 undef, ptr getelementptr inbounds ([[TMP0:%.*]], ptr @global, i32 0, i32 1, i32 11), align 2
; CHECK-NEXT:    store i16 undef, ptr getelementptr ([[TMP0]], ptr @global, i32 0, i32 1, i32 12), align 2
; CHECK-NEXT:    ret void
;
bb:
  store i16 undef, ptr getelementptr inbounds (%0, ptr @global, i32 0, i32 1, i32 11)
  store i16 undef, ptr getelementptr (%0, ptr @global, i32 0, i32 1, i32 12)
  ret void
}

