int main() {
  asm volatile("li       x0,  0\n\t"
               "li       x1,  1\n\t"
               "li       x2,  2\n\t"
               "li       x3,  3\n\t"
               "li       x4,  4\n\t"
               "li       x5,  5\n\t"
               "li       x6,  6\n\t"
               "li       x7,  7\n\t"
               "li       x9,  9\n\t"
               "li       x10,  10\n\t"
               "li       x11,  11\n\t"
               "li       x12,  12\n\t"
               "li       x13,  13\n\t"
               "li       x14,  14\n\t"
               "li       x15,  15\n\t"
               "li       x16,  16\n\t"
               "li       x17,  17\n\t"
               "li       x18,  18\n\t"
               "li       x19,  19\n\t"
               "li       x20,  20\n\t"
               "li       x21,  21\n\t"
               "li       x22,  22\n\t"
               "li       x23,  23\n\t"
               "li       x24,  24\n\t"
               "li       x25,  25\n\t"
               "li       x26,  26\n\t"
               "li       x27,  27\n\t"
               "li       x28,  28\n\t"
               "li       x29,  29\n\t"
               "li       x30,  30\n\t"
               "li       x31,  31\n\t"
               "ebreak \n\t");

  return 0;
}
