; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt %s -S 2>&1 | FileCheck %s
;
define void @f(i32 %x) !dbg !6 {
; CHECK-LABEL: define void @f(
; CHECK-SAME: i32 [[X:%.*]]) !dbg [[DBG4:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:      #dbg_value(i32 [[X]], [[META8:![0-9]+]], !DIExpression(), [[META9:![0-9]+]])
; CHECK-NEXT:    ret void, !dbg [[META9]]
;
entry:
  tail call void @llvm.dbg.value(metadata i32 %x, i64 0, metadata !10, metadata !DIExpression()), !dbg !11
  ret void, !dbg !11
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3, !4}

!0 = distinct !DICompileUnit(language: DW_LANG_C99, file: !1, producer: "")
!1 = !DIFile(filename: "t.c", directory: "/")
!3 = !{i32 2, !"Dwarf Version", i32 4}
!4 = !{i32 2, !"Debug Info Version", i32 3}
!6 = distinct !DISubprogram(name: "f", scope: !1, file: !1, line: 1, type: !7, scopeLine: 1, spFlags: DISPFlagDefinition, unit: !0)
!7 = !DISubroutineType(types: !8)
!8 = !{!9}
!9 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!10 = !DILocalVariable(name: "x", arg: 1, scope: !6, file: !1, line: 1, type: !9)
!11 = !DILocation(line: 1, column: 1, scope: !6)
;.
; CHECK: [[META0:![0-9]+]] = distinct !DICompileUnit(language: DW_LANG_C99, file: [[META1:![0-9]+]], isOptimized: false, runtimeVersion: 0, emissionKind: NoDebug)
; CHECK: [[META1]] = !DIFile(filename: "{{.*}}t.c", directory: {{.*}})
; CHECK: [[DBG4]] = distinct !DISubprogram(name: "f", scope: [[META1]], file: [[META1]], line: 1, type: [[META5:![0-9]+]], scopeLine: 1, spFlags: DISPFlagDefinition, unit: [[META0]])
; CHECK: [[META5]] = !DISubroutineType(types: [[META6:![0-9]+]])
; CHECK: [[META6]] = !{[[META7:![0-9]+]]}
; CHECK: [[META7]] = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
; CHECK: [[META8]] = !DILocalVariable(name: "x", arg: 1, scope: [[DBG4]], file: [[META1]], line: 1, type: [[META7]])
; CHECK: [[META9]] = !DILocation(line: 1, column: 1, scope: [[DBG4]])
;.
