; RUN: llvm-as < %s | llvm-dis | FileCheck %s

define i1 @parse_is_fpclass(float %x) {
  %1 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"snan")
  %2 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"qnan")
  %3 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"ninf")
  %4 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"nnorm")
  %5 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"nsub")
  %6 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"nzero")
  %7 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"pzero")
  %8 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"psub")
  %9 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"pnorm")
  %10 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"pinf")
  %11 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"nan")
  %12 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"zero")
  %13 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"sub")
  %14 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"norm")
  %15 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"inf")
  %16 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"nzero nsub nnorm")
  %17 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"nfinite")
  %18 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"pzero psub pnorm")
  %19 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"pfinite")
  %20 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"zero sub norm")
  %21 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"finite")
  %22 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"pinf pzero psub pnorm")
  %23 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"pos")
  %24 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"ninf nnorm nsub nzero")
  %25 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"neg")
  %26 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"inf norm sub zero")
  %27 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"number")
  %28 = tail call i1 @llvm.is.fpclass.f32(float %x, i32 fc"qnan pinf sub nnorm")
  ret i1 %28
}

; CHECK-LABEL: parse_is_fpclass(float %x) {
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (snan) */ i32 1)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (qnan) */ i32 2)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (ninf) */ i32 4)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (nnorm) */ i32 8)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (nsub) */ i32 16)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (nzero) */ i32 32)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (pzero) */ i32 64)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (psub) */ i32 128)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (pnorm) */ i32 256)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (pinf) */ i32 512)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (nan) */ i32 3)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (zero) */ i32 96)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (sub) */ i32 144)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (norm) */ i32 264)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (inf) */ i32 516)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (nzero nsub nnorm) */ i32 56)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (nzero nsub nnorm) */ i32 56)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (pzero psub pnorm) */ i32 448)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (pzero psub pnorm) */ i32 448)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (zero sub norm) */ i32 504)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (zero sub norm) */ i32 504)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (pinf pzero psub pnorm) */ i32 960)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (pinf pzero psub pnorm) */ i32 960)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (ninf nzero nsub nnorm) */ i32 60)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (ninf nzero nsub nnorm) */ i32 60)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (inf zero sub norm) */ i32 1020)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (inf zero sub norm) */ i32 1020)
; CHECK: call i1 @llvm.is.fpclass.f32(float %x, /* (qnan pinf sub nnorm) */ i32 666)
