add_custom_target(libc_sys_xattr_unittests)

add_libc_test(
  flistxattr_test
  SUITE
    libc_sys_xattr_unittests
  SRCS
    flistxattr_test.cpp
  DEPENDS
    libc.hdr.sys_stat_macros
    libc.include.sys_xattr
    libc.src.__support.CPP.scope
    libc.src.__support.OSUtil.osutil
    libc.src.__support.libc_errno
    libc.src.errno.errno
    libc.src.fcntl.creat
    libc.src.sys.xattr.flistxattr
    libc.src.unistd.close
    libc.src.unistd.unlink
    libc.test.UnitTest.ErrnoCheckingTest
    libc.test.UnitTest.ErrnoSetterMatcher
)

add_libc_test(
  listxattr_test
  SUITE
    libc_sys_xattr_unittests
  SRCS
    listxattr_test.cpp
  DEPENDS
    libc.hdr.sys_stat_macros
    libc.include.sys_xattr
    libc.src.__support.CPP.scope
    libc.src.__support.OSUtil.osutil
    libc.src.__support.libc_errno
    libc.src.errno.errno
    libc.src.fcntl.creat
    libc.src.sys.xattr.listxattr
    libc.src.unistd.close
    libc.src.unistd.symlink
    libc.src.unistd.unlink
    libc.test.UnitTest.ErrnoCheckingTest
    libc.test.UnitTest.ErrnoSetterMatcher
)

add_libc_test(
  llistxattr_test
  SUITE
    libc_sys_xattr_unittests
  SRCS
    llistxattr_test.cpp
  DEPENDS
    libc.hdr.sys_stat_macros
    libc.include.sys_xattr
    libc.src.__support.CPP.scope
    libc.src.__support.OSUtil.osutil
    libc.src.__support.libc_errno
    libc.src.errno.errno
    libc.src.fcntl.creat
    libc.src.sys.xattr.llistxattr
    libc.src.unistd.close
    libc.src.unistd.symlink
    libc.src.unistd.unlink
    libc.test.UnitTest.ErrnoCheckingTest
    libc.test.UnitTest.ErrnoSetterMatcher
)

add_subdirectory(testdata)
