; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=irce < %s -S | FileCheck %s

declare void @deopt()

; This test verifies that IRCE and LoopConstrainer can prove loop entry
; predicates even when loop bounds are rewritten by applyLoopGuards().
define i32 @main(i32 %limit, i32 %start, i32 %length) {
; CHECK-LABEL: define i32 @main(
; CHECK-SAME: i32 [[LIMIT:%.*]], i32 [[INDVAR_START:%.*]], i32 [[LENGTH:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CHECK0:%.*]] = icmp eq i32 [[LIMIT]], 0
; CHECK-NEXT:    br i1 [[CHECK0]], label %[[EXIT:.*]], label %[[PREHEADER:.*]]
; CHECK:       [[PREHEADER]]:
; CHECK-NEXT:    [[PRE_CHECK:%.*]] = icmp slt i32 [[INDVAR_START]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[PRE_CHECK]], label %[[LOOP__PREHEADER:.*]], label %[[DEOPT:.*]]
; CHECK:       [[LOOP__PREHEADER]]:
; CHECK-NEXT:    [[SMIN:%.*]] = call i32 @llvm.smin.i32(i32 [[LENGTH]], i32 0)
; CHECK-NEXT:    [[SMAX:%.*]] = call i32 @llvm.smax.i32(i32 [[SMIN]], i32 -1)
; CHECK-NEXT:    [[TMP0:%.*]] = sub i32 -1, [[SMAX]]
; CHECK-NEXT:    [[SMIN1:%.*]] = call i32 @llvm.smin.i32(i32 [[LIMIT]], i32 [[TMP0]])
; CHECK-NEXT:    [[EXIT_PRELOOP_AT:%.*]] = call i32 @llvm.smax.i32(i32 [[INDVAR_START]], i32 [[SMIN1]])
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[LENGTH]], -2147483647
; CHECK-NEXT:    [[SMAX3:%.*]] = call i32 @llvm.smax.i32(i32 [[TMP1]], i32 1)
; CHECK-NEXT:    [[TMP2:%.*]] = sub i32 [[LENGTH]], [[SMAX3]]
; CHECK-NEXT:    [[TMP3:%.*]] = add nsw i32 [[SMAX]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = mul i32 [[TMP2]], [[TMP3]]
; CHECK-NEXT:    [[SMIN4:%.*]] = call i32 @llvm.smin.i32(i32 [[LIMIT]], i32 [[TMP4]])
; CHECK-NEXT:    [[EXIT_MAINLOOP_AT:%.*]] = call i32 @llvm.smax.i32(i32 [[INDVAR_START]], i32 [[SMIN4]])
; CHECK-NEXT:    [[TMP5:%.*]] = icmp slt i32 [[INDVAR_START]], [[EXIT_PRELOOP_AT]]
; CHECK-NEXT:    br i1 [[TMP5]], label %[[LOOP__PRELOOP_PREHEADER:.*]], label %[[PRELOOP_PSEUDO_EXIT:.*]]
; CHECK:       [[LOOP__PRELOOP_PREHEADER]]:
; CHECK-NEXT:    br label %[[LOOP__PRELOOP:.*]]
; CHECK:       [[MAINLOOP:.*]]:
; CHECK-NEXT:    [[TMP6:%.*]] = icmp slt i32 [[INDVAR_END:%.*]], [[EXIT_MAINLOOP_AT]]
; CHECK-NEXT:    br i1 [[TMP6]], label %[[LOOP__PREHEADER8:.*]], label %[[MAIN_PSEUDO_EXIT:.*]]
; CHECK:       [[LOOP__PREHEADER8]]:
; CHECK-NEXT:    br label %[[LOOP_:.*]]
; CHECK:       [[LOOP_]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[IV_NEXT:%.*]], %[[GUARDED:.*]] ], [ [[IV_PRELOOP_COPY:%.*]], %[[LOOP__PREHEADER8]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 1
; CHECK-NEXT:    [[RANGE_CHECK:%.*]] = icmp ult i32 [[IV_NEXT]], [[LENGTH]]
; CHECK-NEXT:    br i1 true, label %[[GUARDED]], label %[[DEOPT_LOOPEXIT_LOOPEXIT9:.*]]
; CHECK:       [[GUARDED]]:
; CHECK-NEXT:    [[EXIT_CHECK:%.*]] = icmp slt i32 [[IV_NEXT]], [[LIMIT]]
; CHECK-NEXT:    [[TMP7:%.*]] = icmp slt i32 [[IV_NEXT]], [[EXIT_MAINLOOP_AT]]
; CHECK-NEXT:    br i1 [[TMP7]], label %[[LOOP_]], label %[[MAIN_EXIT_SELECTOR:.*]]
; CHECK:       [[MAIN_EXIT_SELECTOR]]:
; CHECK-NEXT:    [[IV_NEXT_LCSSA:%.*]] = phi i32 [ [[IV_NEXT]], %[[GUARDED]] ]
; CHECK-NEXT:    [[TMP8:%.*]] = icmp slt i32 [[IV_NEXT_LCSSA]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[TMP8]], label %[[MAIN_PSEUDO_EXIT]], label %[[EXIT_LOOPEXIT:.*]]
; CHECK:       [[MAIN_PSEUDO_EXIT]]:
; CHECK-NEXT:    [[IV_COPY:%.*]] = phi i32 [ [[IV_PRELOOP_COPY]], %[[MAINLOOP]] ], [ [[IV_NEXT_LCSSA]], %[[MAIN_EXIT_SELECTOR]] ]
; CHECK-NEXT:    [[INDVAR_END6:%.*]] = phi i32 [ [[INDVAR_END]], %[[MAINLOOP]] ], [ [[IV_NEXT_LCSSA]], %[[MAIN_EXIT_SELECTOR]] ]
; CHECK-NEXT:    br label %[[POSTLOOP:.*]]
; CHECK:       [[DEOPT_LOOPEXIT_LOOPEXIT:.*]]:
; CHECK-NEXT:    br label %[[DEOPT_LOOPEXIT:.*]]
; CHECK:       [[DEOPT_LOOPEXIT_LOOPEXIT7:.*]]:
; CHECK-NEXT:    br label %[[DEOPT_LOOPEXIT]]
; CHECK:       [[DEOPT_LOOPEXIT_LOOPEXIT9]]:
; CHECK-NEXT:    br label %[[DEOPT_LOOPEXIT]]
; CHECK:       [[DEOPT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[DEOPT]]
; CHECK:       [[DEOPT]]:
; CHECK-NEXT:    call void @deopt()
; CHECK-NEXT:    unreachable
; CHECK:       [[EXIT_LOOPEXIT_LOOPEXIT:.*]]:
; CHECK-NEXT:    br label %[[EXIT_LOOPEXIT]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RET_OP:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ 1, %[[EXIT_LOOPEXIT]] ]
; CHECK-NEXT:    ret i32 [[RET_OP]]
; CHECK:       [[LOOP__PRELOOP]]:
; CHECK-NEXT:    [[IV_PRELOOP:%.*]] = phi i32 [ [[IV_NEXT_PRELOOP:%.*]], %[[GUARDED_PRELOOP:.*]] ], [ [[INDVAR_START]], %[[LOOP__PRELOOP_PREHEADER]] ]
; CHECK-NEXT:    [[IV_NEXT_PRELOOP]] = add nuw nsw i32 [[IV_PRELOOP]], 1
; CHECK-NEXT:    [[RANGE_CHECK_PRELOOP:%.*]] = icmp ult i32 [[IV_NEXT_PRELOOP]], [[LENGTH]]
; CHECK-NEXT:    br i1 [[RANGE_CHECK_PRELOOP]], label %[[GUARDED_PRELOOP]], label %[[DEOPT_LOOPEXIT_LOOPEXIT]]
; CHECK:       [[GUARDED_PRELOOP]]:
; CHECK-NEXT:    [[EXIT_CHECK_PRELOOP:%.*]] = icmp slt i32 [[IV_NEXT_PRELOOP]], [[LIMIT]]
; CHECK-NEXT:    [[TMP9:%.*]] = icmp slt i32 [[IV_NEXT_PRELOOP]], [[EXIT_PRELOOP_AT]]
; CHECK-NEXT:    br i1 [[TMP9]], label %[[LOOP__PRELOOP]], label %[[PRELOOP_EXIT_SELECTOR:.*]], !llvm.loop [[LOOP0:![0-9]+]], !loop_constrainer.loop.clone [[META5:![0-9]+]]
; CHECK:       [[PRELOOP_EXIT_SELECTOR]]:
; CHECK-NEXT:    [[IV_NEXT_PRELOOP_LCSSA:%.*]] = phi i32 [ [[IV_NEXT_PRELOOP]], %[[GUARDED_PRELOOP]] ]
; CHECK-NEXT:    [[TMP10:%.*]] = icmp slt i32 [[IV_NEXT_PRELOOP_LCSSA]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[TMP10]], label %[[PRELOOP_PSEUDO_EXIT]], label %[[EXIT_LOOPEXIT]]
; CHECK:       [[PRELOOP_PSEUDO_EXIT]]:
; CHECK-NEXT:    [[IV_PRELOOP_COPY]] = phi i32 [ [[INDVAR_START]], %[[LOOP__PREHEADER]] ], [ [[IV_NEXT_PRELOOP_LCSSA]], %[[PRELOOP_EXIT_SELECTOR]] ]
; CHECK-NEXT:    [[INDVAR_END]] = phi i32 [ [[INDVAR_START]], %[[LOOP__PREHEADER]] ], [ [[IV_NEXT_PRELOOP_LCSSA]], %[[PRELOOP_EXIT_SELECTOR]] ]
; CHECK-NEXT:    br label %[[MAINLOOP]]
; CHECK:       [[POSTLOOP]]:
; CHECK-NEXT:    br label %[[LOOP__POSTLOOP:.*]]
; CHECK:       [[LOOP__POSTLOOP]]:
; CHECK-NEXT:    [[IV_POSTLOOP:%.*]] = phi i32 [ [[IV_NEXT_POSTLOOP:%.*]], %[[GUARDED_POSTLOOP:.*]] ], [ [[IV_COPY]], %[[POSTLOOP]] ]
; CHECK-NEXT:    [[IV_NEXT_POSTLOOP]] = add nuw nsw i32 [[IV_POSTLOOP]], 1
; CHECK-NEXT:    [[RANGE_CHECK_POSTLOOP:%.*]] = icmp ult i32 [[IV_NEXT_POSTLOOP]], [[LENGTH]]
; CHECK-NEXT:    br i1 [[RANGE_CHECK_POSTLOOP]], label %[[GUARDED_POSTLOOP]], label %[[DEOPT_LOOPEXIT_LOOPEXIT7]]
; CHECK:       [[GUARDED_POSTLOOP]]:
; CHECK-NEXT:    [[EXIT_CHECK_POSTLOOP:%.*]] = icmp slt i32 [[IV_NEXT_POSTLOOP]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[EXIT_CHECK_POSTLOOP]], label %[[LOOP__POSTLOOP]], label %[[EXIT_LOOPEXIT_LOOPEXIT]], !llvm.loop [[LOOP6:![0-9]+]], !loop_constrainer.loop.clone [[META5]]
;
entry:
  %check0 = icmp eq i32 %limit, 0
  br i1 %check0, label %exit, label %preheader

preheader:                                        ; preds = %entry
  %pre_check = icmp slt i32 %start, %limit
  br i1 %pre_check, label %loop_, label %deopt

loop_:                                            ; preds = %guarded, %preheader
  %iv = phi i32 [ %iv.next, %guarded ], [ %start, %preheader ]
  %iv.next = add nuw nsw i32 %iv, 1
  %range_check = icmp ult i32 %iv.next, %length
  br i1 %range_check, label %guarded, label %deopt

guarded:                                          ; preds = %loop_
  %exit_check = icmp slt i32 %iv.next, %limit
  br i1 %exit_check, label %loop_, label %exit

deopt:
  call void @deopt()
  unreachable

exit:                                       ; preds = %guarded, %loop_, %preheader, %entry
  %ret.op = phi i32 [ 0, %entry ], [ 1, %guarded ]
  ret i32 %ret.op
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]], [[META4:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.unroll.disable"}
; CHECK: [[META2]] = !{!"llvm.loop.vectorize.enable", i1 false}
; CHECK: [[META3]] = !{!"llvm.loop.licm_versioning.disable"}
; CHECK: [[META4]] = !{!"llvm.loop.distribute.enable", i1 false}
; CHECK: [[META5]] = !{}
; CHECK: [[LOOP6]] = distinct !{[[LOOP6]], [[META1]], [[META2]], [[META3]], [[META4]]}
;.
