# General settings
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "")
set(CMAKE_C_COMPILER_LAUNCHER "ccache" CACHE STRING "")
set(CMAKE_CXX_COMPILER_LAUNCHER "ccache" CACHE STRING "")
set(LLVM_ENABLE_LLD ON CACHE BOOL "")

set(LLVM_ENABLE_ASSERTIONS ON CACHE BOOL "")
set(LLVM_ENABLE_PROJECTS "clang;polly" CACHE STRING "")
set(LLVM_TARGETS_TO_BUILD "X86" CACHE STRING "")

set(LLVM_POLLY_LINK_INTO_TOOLS ON CACHE BOOL "")
