// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 -triple aarch64 -emit-llvm -o - %s | FileCheck %s
// RUN: %clang_cc1 -triple aarch64 -S -o /dev/null %s

_BitInt(18) signed_src;
_BitInt(18) signed_dst;

// CHECK-LABEL: define dso_local void @test_signed(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr @signed_dst, align 4
// CHECK-NEXT:    [[TOBITINT:%.*]] = trunc i32 [[TMP0]] to i18
// CHECK-NEXT:    [[ZEXTBITINT:%.*]] = zext i18 [[TOBITINT]] to i32
// CHECK-NEXT:    store i32 [[ZEXTBITINT]], ptr @signed_src, align 4
// CHECK-NEXT:    ret void
//
void test_signed() {
  signed_src = signed_dst;
}

unsigned _BitInt(18) src;
unsigned _BitInt(18) dst;

// CHECK-LABEL: define dso_local void @test_unsigned(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr @dst, align 4
// CHECK-NEXT:    [[TOBITINT:%.*]] = trunc i32 [[TMP0]] to i18
// CHECK-NEXT:    [[ZEXTBITINT:%.*]] = zext i18 [[TOBITINT]] to i32
// CHECK-NEXT:    store i32 [[ZEXTBITINT]], ptr @src, align 4
// CHECK-NEXT:    ret void
//
void test_unsigned() {
  src = dst;
}
