// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1        -triple aarch64-none-linux-gnu -target-feature +neon -disable-O0-optnone -Werror -Wall -emit-llvm -o - %s | opt -S -p mem2reg,instcombine | FileCheck %s
// RUN: %clang_cc1 -x c++ -triple aarch64-none-linux-gnu -target-feature +neon -disable-O0-optnone -Werror -Wall -emit-llvm -o - %s | opt -S -p mem2reg,instcombine | FileCheck %s -check-prefix CHECK-CXX

// RUN: %clang_cc1        -triple aarch64-none-linux-gnu -target-feature +neon -disable-O0-optnone -Werror -Wall -S -o /dev/null %s

// REQUIRES: aarch64-registered-target

#include <arm_neon.h>

// Test for a n internal compiler error when extracting an element from an FP8
// vector and passing it to a function.

// CHECK-LABEL: define dso_local void @test_var(
// CHECK-SAME: <16 x i8> [[V:%.*]], i32 noundef [[I:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[VECEXT:%.*]] = extractelement <16 x i8> [[V]], i32 [[I]]
// CHECK-NEXT:    [[MFP8CAST:%.*]] = insertelement <1 x i8> poison, i8 [[VECEXT]], i64 0
// CHECK-NEXT:    call void @g(<1 x i8> [[MFP8CAST]]) #[[ATTR2:[0-9]+]]
// CHECK-NEXT:    ret void
//
// CHECK-CXX-LABEL: define dso_local void @_Z8test_var14__Mfloat8x16_ti(
// CHECK-CXX-SAME: <16 x i8> [[V:%.*]], i32 noundef [[I:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-CXX-NEXT:  [[ENTRY:.*:]]
// CHECK-CXX-NEXT:    [[VECEXT:%.*]] = extractelement <16 x i8> [[V]], i32 [[I]]
// CHECK-CXX-NEXT:    [[MFP8CAST:%.*]] = insertelement <1 x i8> poison, i8 [[VECEXT]], i64 0
// CHECK-CXX-NEXT:    call void @_Z1gu6__mfp8(<1 x i8> [[MFP8CAST]]) #[[ATTR2:[0-9]+]]
// CHECK-CXX-NEXT:    ret void
//
void test_var(__Mfloat8x16_t v, int i) {
  void g(__mfp8);
  g(v[i]);
}

// CHECK-LABEL: define dso_local void @test_cst(
// CHECK-SAME: <16 x i8> [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[MFP8CAST:%.*]] = shufflevector <16 x i8> [[V]], <16 x i8> poison, <1 x i32> <i32 3>
// CHECK-NEXT:    call void @g(<1 x i8> [[MFP8CAST]]) #[[ATTR2]]
// CHECK-NEXT:    ret void
//
// CHECK-CXX-LABEL: define dso_local void @_Z8test_cst14__Mfloat8x16_t(
// CHECK-CXX-SAME: <16 x i8> [[V:%.*]]) #[[ATTR0]] {
// CHECK-CXX-NEXT:  [[ENTRY:.*:]]
// CHECK-CXX-NEXT:    [[MFP8CAST:%.*]] = shufflevector <16 x i8> [[V]], <16 x i8> poison, <1 x i32> <i32 3>
// CHECK-CXX-NEXT:    call void @_Z1gu6__mfp8(<1 x i8> [[MFP8CAST]]) #[[ATTR2]]
// CHECK-CXX-NEXT:    ret void
//
void test_cst(__Mfloat8x16_t v) {
  void g(__mfp8);
  g(v[3]);
}
