// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple aarch64-none-linux-gnu -emit-llvm -o - %s | FileCheck %s

#include <arm_acle.h>

// CHECK-LABEL: define dso_local void @test_u8(
// CHECK-SAME: ptr noundef [[P:%.*]], i8 noundef [[V:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store i8 [[V]], ptr [[V_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[V_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = zext i8 [[TMP1]] to i64
// CHECK-NEXT:    call void @llvm.aarch64.stshh.atomic.store.p0(ptr [[TMP0]], i64 [[TMP2]], i32 0, i32 0, i32 8)
// CHECK-NEXT:    ret void
//
void test_u8(unsigned char *p, unsigned char v) {
  __arm_atomic_store_with_stshh(p, v, __ATOMIC_RELAXED, 0);
}

// CHECK-LABEL: define dso_local void @test_u16(
// CHECK-SAME: ptr noundef [[P:%.*]], i16 noundef [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca i16, align 2
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store i16 [[V]], ptr [[V_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[V_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = zext i16 [[TMP1]] to i64
// CHECK-NEXT:    fence release
// CHECK-NEXT:    call void @llvm.aarch64.stshh.atomic.store.p0(ptr [[TMP0]], i64 [[TMP2]], i32 3, i32 1, i32 16)
// CHECK-NEXT:    ret void
//
void test_u16(unsigned short *p, unsigned short v) {
  __arm_atomic_store_with_stshh(p, v, __ATOMIC_RELEASE, 1);
}

// CHECK-LABEL: define dso_local void @test_u32(
// CHECK-SAME: ptr noundef [[P:%.*]], i32 noundef [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store i32 [[V]], ptr [[V_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[V_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = zext i32 [[TMP1]] to i64
// CHECK-NEXT:    fence seq_cst
// CHECK-NEXT:    call void @llvm.aarch64.stshh.atomic.store.p0(ptr [[TMP0]], i64 [[TMP2]], i32 5, i32 0, i32 32)
// CHECK-NEXT:    ret void
//
void test_u32(unsigned int *p, unsigned int v) {
  __arm_atomic_store_with_stshh(p, v, __ATOMIC_SEQ_CST, 0);
}

// CHECK-LABEL: define dso_local void @test_u64(
// CHECK-SAME: ptr noundef [[P:%.*]], i64 noundef [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store i64 [[V]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    call void @llvm.aarch64.stshh.atomic.store.p0(ptr [[TMP0]], i64 [[TMP1]], i32 0, i32 1, i32 64)
// CHECK-NEXT:    ret void
//
void test_u64(unsigned long *p, unsigned long v) {
  __arm_atomic_store_with_stshh(p, v, __ATOMIC_RELAXED, 1);
}

// CHECK-LABEL: define dso_local void @test_f32(
// CHECK-SAME: ptr noundef [[P:%.*]], float noundef [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca float, align 4
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store float [[V]], ptr [[V_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr [[V_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast float [[TMP1]] to i32
// CHECK-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP2]] to i64
// CHECK-NEXT:    fence release
// CHECK-NEXT:    call void @llvm.aarch64.stshh.atomic.store.p0(ptr [[TMP0]], i64 [[TMP3]], i32 3, i32 0, i32 32)
// CHECK-NEXT:    ret void
//
void test_f32(float *p, float v) {
  __arm_atomic_store_with_stshh(p, v, __ATOMIC_RELEASE, 0);
}

// CHECK-LABEL: define dso_local void @test_ptr(
// CHECK-SAME: ptr noundef [[P:%.*]], ptr noundef [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store ptr [[V]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[TMP1]] to i64
// CHECK-NEXT:    call void @llvm.aarch64.stshh.atomic.store.p0(ptr [[TMP0]], i64 [[TMP2]], i32 0, i32 1, i32 64)
// CHECK-NEXT:    ret void
//
void test_ptr(void **p, void *v) {
  __arm_atomic_store_with_stshh(p, v, __ATOMIC_RELAXED, 1);
}
