; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt %s -passes=loop-deletion -S | FileCheck %s

declare i32 @__gxx_personality_v0(...)

define void @wombat() personality ptr @__gxx_personality_v0 {
; CHECK-LABEL: define void @wombat() personality ptr @__gxx_personality_v0 {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    br i1 false, label [[BB1:%.*]], label [[BB4:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    br label [[BB2:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    [[INVOKE:%.*]] = invoke double null()
; CHECK-NEXT:            to label [[BB2]] unwind label [[BB3:%.*]]
; CHECK:       bb3:
; CHECK-NEXT:    [[LANDINGPAD:%.*]] = landingpad { ptr, i32 }
; CHECK-NEXT:            cleanup
; CHECK-NEXT:    ret void
; CHECK:       bb4:
; CHECK-NEXT:    ret void
;
bb:
  br i1 false, label %bb1, label %bb4

bb1:                                              ; preds = %bb
  br label %bb2

bb2:                                              ; preds = %bb1, %bb2
  %invoke = invoke double null()
  to label %bb2 unwind label %bb3

bb3:                                              ; preds = %bb2
  %landingpad = landingpad { ptr, i32 }
  cleanup
  ret void

bb4:                                              ; preds = %bb
  ret void
}
