; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='loop(indvars,loop-deletion)' -S %s | FileCheck %s

; When loop-deletion breaks the inner loop's back-edge, it must also invalidate
; the outer loop's cached SCEV backedge-taken-count.  Without the fix the stale
; BTC (= 6, computed before the inner loop's blocks were reassigned to the outer
; loop) causes rewriteLoopExitValues to fold the LCSSA phi at func.exit to the
; wrong constant 6 instead of the correct value 0.

define i32 @PR197240() {
; CHECK-LABEL: define i32 @PR197240() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER_HEADER:.*]]
; CHECK:       [[OUTER_HEADER_LOOPEXIT:.*]]:
; CHECK-NEXT:    [[INDVARS_IV_NEXT:%.*]] = add nuw nsw i32 [[INDVARS_IV:%.*]], 1
; CHECK-NEXT:    unreachable
; CHECK:       [[OUTER_HEADER]]:
; CHECK-NEXT:    [[INDVARS_IV]] = phi i32 [ 1, %[[ENTRY]] ]
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[LOOP_BODY:.*]]
; CHECK:       [[LOOP_BODY]]:
; CHECK-NEXT:    switch i32 [[IV]], label %[[INNER_BODY:.*]] [
; CHECK-NEXT:      i32 7, label %[[OUTER_HEADER_LOOPEXIT]]
; CHECK-NEXT:      i32 6, label %[[EARLY_EXIT:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[EARLY_EXIT]]:
; CHECK-NEXT:    ret i32 0
; CHECK:       [[INNER_BODY]]:
; CHECK-NEXT:    br i1 false, label %[[INNER_LATCH:.*]], label %[[FUNC_EXIT:.*]]
; CHECK:       [[INNER_LATCH]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[FUNC_EXIT]]:
; CHECK-NEXT:    [[IV_LCSSA3:%.*]] = phi i32 [ 6, %[[INNER_BODY]] ]
; CHECK-NEXT:    ret i32 [[IV_LCSSA3]]
;
entry:
  br label %outer.header

; Outer loop: back-edge taken when iv == 7.
outer.header:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop.body ]
  br label %loop.body

loop.body:
  %iv.next = add i32 %iv, 1
  switch i32 %iv, label %inner.body [
  i32 7, label %outer.header
  i32 6, label %early.exit
  ]

early.exit:
  ret i32 0

; Inner loop: loop.body -> inner.body -> inner.latch -> loop.body.
; The back-edge condition is always false, so loop-deletion will break it.
inner.body:
  br i1 false, label %inner.latch, label %func.exit

inner.latch:
  br label %loop.body

; iv == 0 on entry (switch default fires on first iteration with iv=0).
func.exit:
  ret i32 %iv
}
