import("//third-party/unittest/unittest.gni")

unittest("ABITests") {
  deps = [
    "//llvm/lib/ABI",
    "//llvm/lib/IR",
    "//llvm/lib/Support",
  ]
  sources = [
    "AArch64TargetInfoTest.cpp",
    "AMDGPUTargetInfoTest.cpp",
    "FunctionInfoTest.cpp",
    "IRTypeMapperTest.cpp",
    "TargetInfoTest.cpp",
    "TypesTest.cpp",
    "X86TargetInfoTest.cpp",
  ]
}
