; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -mtriple=arm-none-eabi -passes=globalopt -S | FileCheck %s

; CHECK-NOT: [64 x i8]
@.str = private unnamed_addr constant [62 x i8] c"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\00", align 1

; Function Attrs: nounwind
define  void @foo()   {
; CHECK-LABEL: define void @foo() local_unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[SOMETHING:%.*]] = alloca [62 x i8], align 1
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds [62 x i8], ptr [[SOMETHING]], i32 0, i32 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 62, ptr nonnull [[TMP0]])
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr nonnull align 1 [[TMP0]], ptr align 1 @.str, i32 62, i1 true)
; CHECK-NEXT:    [[CALL2:%.*]] = call i32 @bar(ptr nonnull [[TMP0]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 62, ptr nonnull [[TMP0]])
; CHECK-NEXT:    ret void
;
entry:
  %something = alloca [62 x i8], align 1
  %0 = getelementptr inbounds [62 x i8], ptr %something, i32 0, i32 0
  call void @llvm.lifetime.start(i64 62, ptr nonnull %0) #3
  call void @llvm.memcpy.p0i8.p0i8.i32(ptr align 1 nonnull %0, ptr align 1 @.str, i32 62, i1 true)
  %call2 = call i32 @bar(ptr nonnull %0) #3
  call void @llvm.lifetime.end(i64 62, ptr nonnull %0) #3
  ret void
}

declare i32 @bar(...)  #2
