; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals --include-generated-funcs
; RUN: opt < %S/lower-ifunc.ll -passes=lower-ifunc -S --mtriple=powerpc64-ibm-aix-xcoff | FileCheck %s

;.
; CHECK: @initialized_with_ifunc = global ptr @ifunc_constant_initializer_user
;.
; CHECK-LABEL: @resolver1(
; CHECK-NEXT:    ret ptr inttoptr (i64 123 to ptr)
;
;
; CHECK-LABEL: @resolver2(
; CHECK-NEXT:    ret ptr inttoptr (i64 456 to ptr)
;
;
; CHECK-LABEL: @resolver3(
; CHECK-NEXT:    ret ptr inttoptr (i64 789 to ptr)
;
;
; CHECK-LABEL: @resolver4(
; CHECK-NEXT:    ret ptr inttoptr (i64 999 to ptr)
;
;
; CHECK-LABEL: @resolver5(
; CHECK-NEXT:    ret ptr inttoptr (i64 420 to ptr)
;
;
; CHECK-LABEL: define {{[^@]+}}@call_ifunc(
; CHECK-NEXT:    call void @ifunc_1()
; CHECK-NEXT:    call void @ifunc_2()
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@store_ifunc_2(
; CHECK-NEXT:    store ptr @ifunc_2, ptr [[PTR:%.*]], align 8
; CHECK-NEXT:    store ptr [[PTR]], ptr @ifunc_2, align 8
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@call_ifunc_is_argument(
; CHECK-NEXT:    call void @other_func(ptr @ifunc_2)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@call_ifunc_both_call_argument(
; CHECK-NEXT:    call void @ifunc_ptr_arg(ptr @ifunc_ptr_arg)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@call_ifunc_nonvoid(
; CHECK-NEXT:    [[RET:%.*]] = call i32 @ifunc_nonvoid_0(double [[ARG:%.*]])
; CHECK-NEXT:    ret i32 [[RET]]
;
;
; CHECK-LABEL: define {{[^@]+}}@call_different_type_ifunc_nonvoid(
; CHECK-NEXT:    [[CAST_ARG:%.*]] = bitcast double [[ARG:%.*]] to i64
; CHECK-NEXT:    [[RET:%.*]] = call float @ifunc_nonvoid_0(i64 [[CAST_ARG]])
; CHECK-NEXT:    ret float [[RET]]
;
;
; CHECK-LABEL: define {{[^@]+}}@call_addrspacecast_callee_type_ifunc_nonvoid(
; CHECK-NEXT:    [[RET:%.*]] = call addrspace(1) i32 addrspacecast (ptr @ifunc_nonvoid_1 to ptr addrspace(1))(double [[ARG:%.*]])
; CHECK-NEXT:    ret i32 [[RET]]
;
;
; CHECK-LABEL: define {{[^@]+}}@call_used_in_initializer(
; CHECK-NEXT:    [[RET:%.*]] = call i32 @ifunc_constant_initializer_user(double [[ARG:%.*]])
; CHECK-NEXT:    ret i32 [[RET]]
;
;
; CHECK-LABEL: define {{[^@]+}}@ifunc_1(
; CHECK:    [[DESC_PTR:%.*]] = call ptr @llvm.ppc.get.function.descriptor(ptr @ifunc_1)
; CHECK:    call void [[DESC_PTR]]()
; CHECK-NEXT:    ret void
;
; skip checking ifunc_2 because it's the same as ifunc_1
;
; CHECK-LABEL: define {{[^@]+}}@ifunc_no_users(
; CHECK:    [[DESC_PTR:%.*]] = call ptr @llvm.ppc.get.function.descriptor(ptr @ifunc_no_users)
; CHECK:    [[TMP3:%.*]] = call float [[DESC_PTR]](i64 [[TMP0:%.*]])
; CHECK-NEXT:    ret float [[TMP3]]
;
;
; CHECK-LABEL: define {{[^@]+}}@ifunc7(
; CHECK:    [[DESC_PTR:%.*]] = call ptr @llvm.ppc.get.function.descriptor(ptr @ifunc7)
; CHECK:    [[TMP3:%.*]] = call float [[DESC_PTR]](i64 [[TMP0:%.*]])
; CHECK-NEXT:    ret float [[TMP3]]
;
;
; CHECK-LABEL: define {{[^@]+}}@ifunc_ptr_arg(
; CHECK:    [[DESC_T_ADDR:%.*]] = getelementptr inbounds nuw { ptr, ptr, ptr }, ptr [[DESC_PTR]], i32 0, i32 0
; CHECK:    call void [[DESC_PTR]](ptr [[TMP0:%.*]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@ifunc_nonvoid_0(
; CHECK:    [[DESC_PTR:%.*]] = call ptr @llvm.ppc.get.function.descriptor(ptr @ifunc_nonvoid_0)
; CHECK:    [[TMP3:%.*]] = call i32 [[DESC_PTR]](double [[TMP0:%.*]])
; CHECK-NEXT:    ret i32 [[TMP3]]
;
;
; CHECK-LABEL: define {{[^@]+}}@ifunc_nonvoid_1(
; CHECK:    [[DESC_PTR:%.*]] = call ptr @llvm.ppc.get.function.descriptor(ptr @ifunc_nonvoid_1)
; CHECK:    [[TMP3:%.*]] = call i32 [[DESC_PTR]](double [[TMP0:%.*]])
; CHECK-NEXT:    ret i32 [[TMP3]]
;
;
; CHECK-LABEL: define {{[^@]+}}@ifunc_constant_initializer_user(
; CHECK:    [[DESC_PTR:%.*]] = call ptr @llvm.ppc.get.function.descriptor(ptr @ifunc_constant_initializer_user)
; CHECK:    [[TMP3:%.*]] = call i32 [[DESC_PTR]](double [[TMP0:%.*]])
; CHECK-NEXT:    ret i32 [[TMP3]]
;
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(none) }
;.
