; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals --include-generated-funcs
; RUN: opt < %s -passes=lower-ifunc -S --mtriple=powerpc64-ibm-aix-xcoff | FileCheck --check-prefixes=CHECK,CHECK-64 %s
; RUN: opt < %s -passes=lower-ifunc -S --mtriple=powerpc-ibm-aix-xcoff | FileCheck --check-prefixes=CHECK,CHECK-32 %s


@ifunc_1 = ifunc void (), ptr @resolver1

define ptr @resolver1() {
  ret ptr null
}

; Test call to  ifunc
define void @call_ifunc(ptr %ptr) {
  call void @ifunc_1()
  ret void
}
; CHECK-LABEL: define ptr @resolver1(
; CHECK-NEXT:    ret ptr null
;
;
; CHECK-LABEL: define void @call_ifunc(
; CHECK-NEXT:    call void @ifunc_1()
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define void @ifunc_1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[DESC_PTR:%.*]] = call ptr @llvm.ppc.get.function.descriptor(ptr @ifunc_1)
; CHECK-NEXT:    [[DESC_T_ADDR:%.*]] = getelementptr inbounds nuw { ptr, ptr, ptr }, ptr [[DESC_PTR]], i32 0, i32 0
; CHECK-64-NEXT:    [[ADDR_IN_DESC:%.*]] = load ptr, ptr [[DESC_T_ADDR]], align 8
; CHECK-32-NEXT:    [[ADDR_IN_DESC:%.*]] = load ptr, ptr [[DESC_T_ADDR]], align 4
; CHECK-NEXT:    [[ORIGINAL_ADDR:%.*]] = call ptr @llvm.ppc.get.function.entry(ptr @ifunc_1)
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[ADDR_IN_DESC]], [[ORIGINAL_ADDR]]
; CHECK-NEXT:    br i1 [[TMP0]], label [[RESOLVER:%.*]], label [[END:%.*]]
; CHECK:       resolver:
; CHECK-NEXT:    [[RESOLVED_FUNC:%.*]] = call ptr @resolver1()
; CHECK-NEXT:    [[RESOLVED_ADDR:%.*]] = call ptr @llvm.ppc.get.function.entry(ptr [[RESOLVED_FUNC]])
; CHECK-64-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[RESOLVED_ADDR]] to i64
; CHECK-64-NEXT:    store atomic i64 [[TMP1]], ptr [[DESC_T_ADDR]] release, align 8
; CHECK-32-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[RESOLVED_ADDR]] to i32
; CHECK-32-NEXT:    store atomic i32 [[TMP1]], ptr [[DESC_T_ADDR]] release, align 4
; CHECK-NEXT:    br label [[END]]
; CHECK:       end:
; CHECK-NEXT:    call void [[DESC_PTR]]()
; CHECK-NEXT:    ret void
;
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(none) }
;.
