// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --include-generated-funcs
// RUN: %clang_cc1 -O3 -triple=x86_64-unknown-linux-gnu -fopenmp -fno-unroll-loops -fopenmp-default-first-private -emit-llvm %s -o - | FileCheck %s

void foo(int *a, int size) {
#pragma omp parallel for
  for (int i = 0; i < size; ++i)
    a[i] += 5;
}
// CHECK-LABEL: @foo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SIZE_CASTED_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[SIZE:%.*]] to i64
// CHECK-NEXT:    tail call void (ptr, i32, ptr, ...) @__kmpc_fork_call(ptr nonnull @[[GLOB2:[0-9]+]], i32 2, ptr nonnull @foo.omp_outlined, i64 [[SIZE_CASTED_SROA_0_0_INSERT_EXT]], ptr [[A:%.*]])
// CHECK-NEXT:    ret void
//
//
// CHECK-LABEL: @foo.omp_outlined(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DOTOMP_LB:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[DOTOMP_UB:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[DOTOMP_STRIDE:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[DOTOMP_IS_LAST:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[SIZE_ADDR_SROA_0_0_EXTRACT_TRUNC:%.*]] = trunc i64 [[SIZE:%.*]] to i32
// CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[SIZE_ADDR_SROA_0_0_EXTRACT_TRUNC]], 0
// CHECK-NEXT:    br i1 [[CMP]], label [[OMP_PRECOND_THEN:%.*]], label [[OMP_PRECOND_END:%.*]]
// CHECK:       omp.precond.then:
// CHECK-NEXT:    [[SUB2:%.*]] = add nsw i32 [[SIZE_ADDR_SROA_0_0_EXTRACT_TRUNC]], -1
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr nonnull [[DOTOMP_LB]]) #[[ATTR3:[0-9]+]]
// CHECK-NEXT:    store i32 0, ptr [[DOTOMP_LB]], align 4, !tbaa [[TBAA3:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr nonnull [[DOTOMP_UB]]) #[[ATTR3]]
// CHECK-NEXT:    store i32 [[SUB2]], ptr [[DOTOMP_UB]], align 4, !tbaa [[TBAA3]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr nonnull [[DOTOMP_STRIDE]]) #[[ATTR3]]
// CHECK-NEXT:    store i32 1, ptr [[DOTOMP_STRIDE]], align 4, !tbaa [[TBAA3]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr nonnull [[DOTOMP_IS_LAST]]) #[[ATTR3]]
// CHECK-NEXT:    store i32 0, ptr [[DOTOMP_IS_LAST]], align 4, !tbaa [[TBAA3]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[DOTGLOBAL_TID_:%.*]], align 4, !tbaa [[TBAA3]]
// CHECK-NEXT:    call void @__kmpc_for_static_init_4(ptr nonnull @[[GLOB1:[0-9]+]], i32 [[TMP0]], i32 34, ptr nonnull [[DOTOMP_IS_LAST]], ptr nonnull [[DOTOMP_LB]], ptr nonnull [[DOTOMP_UB]], ptr nonnull [[DOTOMP_STRIDE]], i32 1, i32 1)
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[DOTOMP_UB]], align 4
// CHECK-NEXT:    [[COND:%.*]] = call i32 @llvm.smin.i32(i32 [[TMP1]], i32 [[SUB2]])
// CHECK-NEXT:    store i32 [[COND]], ptr [[DOTOMP_UB]], align 4, !tbaa [[TBAA3]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[DOTOMP_LB]], align 4, !tbaa [[TBAA3]]
// CHECK-NEXT:    [[CMP5_NOT14:%.*]] = icmp sgt i32 [[TMP2]], [[COND]]
// CHECK-NEXT:    br i1 [[CMP5_NOT14]], label [[OMP_LOOP_EXIT:%.*]], label [[OMP_INNER_FOR_BODY_PREHEADER:%.*]]
// CHECK:       omp.inner.for.body.preheader:
// CHECK-NEXT:    [[TMP3:%.*]] = sext i32 [[TMP2]] to i64
// CHECK-NEXT:    [[TMP4:%.*]] = add nsw i32 [[COND]], 1
// CHECK-NEXT:    br label [[OMP_INNER_FOR_BODY:%.*]]
// CHECK:       omp.inner.for.body:
// CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[TMP3]], [[OMP_INNER_FOR_BODY_PREHEADER]] ], [ [[INDVARS_IV_NEXT:%.*]], [[OMP_INNER_FOR_BODY]] ]
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[INDVARS_IV]]
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA3]]
// CHECK-NEXT:    [[ADD6:%.*]] = add nsw i32 [[TMP5]], 5
// CHECK-NEXT:    store i32 [[ADD6]], ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA3]]
// CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nsw i64 [[INDVARS_IV]], 1
// CHECK-NEXT:    [[LFTR_WIDEIV:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
// CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[TMP4]], [[LFTR_WIDEIV]]
// CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[OMP_LOOP_EXIT]], label [[OMP_INNER_FOR_BODY]]
// CHECK:       omp.loop.exit:
// CHECK-NEXT:    call void @__kmpc_for_static_fini(ptr nonnull @[[GLOB1]], i32 [[TMP0]])
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr nonnull [[DOTOMP_IS_LAST]]) #[[ATTR3]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr nonnull [[DOTOMP_STRIDE]]) #[[ATTR3]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr nonnull [[DOTOMP_UB]]) #[[ATTR3]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr nonnull [[DOTOMP_LB]]) #[[ATTR3]]
// CHECK-NEXT:    br label [[OMP_PRECOND_END]]
// CHECK:       omp.precond.end:
// CHECK-NEXT:    ret void
//
