# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv32 -mattr=+v -run-pass=instruction-select -simplify-mir -verify-machineinstrs %s -o - | FileCheck -check-prefix=RV32I %s
# RUN: llc -mtriple=riscv64 -mattr=+v -run-pass=instruction-select -simplify-mir -verify-machineinstrs %s -o - | FileCheck -check-prefix=RV64I %s
---
name:            vload_nx1i8
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx1i8
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE8_V_MF8_:%[0-9]+]]:vr = PseudoVLE8_V_MF8 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 1 x s8>))
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE8_V_MF8_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx1i8
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE8_V_MF8_:%[0-9]+]]:vr = PseudoVLE8_V_MF8 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 1 x s8>))
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE8_V_MF8_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 1 x s8>) = G_LOAD %0(p0) :: (load (<vscale x 1 x s8>))
    $v8 = COPY %1(<vscale x 1 x s8>)
    PseudoRET implicit $v8
...
---
name:            vload_nx2i8
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx2i8
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE8_V_MF4_:%[0-9]+]]:vr = PseudoVLE8_V_MF4 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s8>))
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE8_V_MF4_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx2i8
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE8_V_MF4_:%[0-9]+]]:vr = PseudoVLE8_V_MF4 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s8>))
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE8_V_MF4_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 2 x s8>) = G_LOAD %0(p0) :: (load (<vscale x 2 x s8>))
    $v8 = COPY %1(<vscale x 2 x s8>)
    PseudoRET implicit $v8

...
---
name:            vload_nx4i8
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx4i8
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE8_V_MF2_:%[0-9]+]]:vr = PseudoVLE8_V_MF2 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s8>))
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE8_V_MF2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx4i8
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE8_V_MF2_:%[0-9]+]]:vr = PseudoVLE8_V_MF2 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s8>))
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE8_V_MF2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 4 x s8>) = G_LOAD %0(p0) :: (load (<vscale x 4 x s8>))
    $v8 = COPY %1(<vscale x 4 x s8>)
    PseudoRET implicit $v8

...
---
name:            vload_nx8i8
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx8i8
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE8_V_M1_:%[0-9]+]]:vr = PseudoVLE8_V_M1 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 8 x s8>))
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE8_V_M1_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx8i8
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE8_V_M1_:%[0-9]+]]:vr = PseudoVLE8_V_M1 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 8 x s8>))
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE8_V_M1_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 8 x s8>) = G_LOAD %0(p0) :: (load (<vscale x 8 x s8>))
    $v8 = COPY %1(<vscale x 8 x s8>)
    PseudoRET implicit $v8

...
---
name:            vload_nx16i8
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx16i8
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE8_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE8_V_M2 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s8>))
    ; RV32I-NEXT: $v8m2 = COPY [[PseudoVLE8_V_M2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m2
    ;
    ; RV64I-LABEL: name: vload_nx16i8
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE8_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE8_V_M2 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s8>))
    ; RV64I-NEXT: $v8m2 = COPY [[PseudoVLE8_V_M2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m2
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 16 x s8>) = G_LOAD %0(p0) :: (load (<vscale x 16 x s8>))
    $v8m2 = COPY %1(<vscale x 16 x s8>)
    PseudoRET implicit $v8m2

...
---
name:            vload_nx32i8
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx32i8
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm4 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE8_V_M4_:%[0-9]+]]:vrm4 = PseudoVLE8_V_M4 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 32 x s8>))
    ; RV32I-NEXT: $v8m4 = COPY [[PseudoVLE8_V_M4_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m4
    ;
    ; RV64I-LABEL: name: vload_nx32i8
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm4 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE8_V_M4_:%[0-9]+]]:vrm4 = PseudoVLE8_V_M4 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 32 x s8>))
    ; RV64I-NEXT: $v8m4 = COPY [[PseudoVLE8_V_M4_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m4
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 32 x s8>) = G_LOAD %0(p0) :: (load (<vscale x 32 x s8>))
    $v8m4 = COPY %1(<vscale x 32 x s8>)
    PseudoRET implicit $v8m4

...
---
name:            vload_nx64i8
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx64i8
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm8 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE8_V_M8_:%[0-9]+]]:vrm8 = PseudoVLE8_V_M8 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 64 x s8>))
    ; RV32I-NEXT: $v8m8 = COPY [[PseudoVLE8_V_M8_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m8
    ;
    ; RV64I-LABEL: name: vload_nx64i8
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm8 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE8_V_M8_:%[0-9]+]]:vrm8 = PseudoVLE8_V_M8 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 64 x s8>))
    ; RV64I-NEXT: $v8m8 = COPY [[PseudoVLE8_V_M8_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 64 x s8>) = G_LOAD %0(p0) :: (load (<vscale x 64 x s8>))
    $v8m8 = COPY %1(<vscale x 64 x s8>)
    PseudoRET implicit $v8m8

...
---
name:            vload_nx1i16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx1i16
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE16_V_MF4_:%[0-9]+]]:vr = PseudoVLE16_V_MF4 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 1 x s16>))
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE16_V_MF4_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx1i16
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE16_V_MF4_:%[0-9]+]]:vr = PseudoVLE16_V_MF4 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 1 x s16>))
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE16_V_MF4_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 1 x s16>) = G_LOAD %0(p0) :: (load (<vscale x 1 x s16>))
    $v8 = COPY %1(<vscale x 1 x s16>)
    PseudoRET implicit $v8

...
---
name:            vload_nx2i16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx2i16
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE16_V_MF2_:%[0-9]+]]:vr = PseudoVLE16_V_MF2 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s16>))
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE16_V_MF2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx2i16
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE16_V_MF2_:%[0-9]+]]:vr = PseudoVLE16_V_MF2 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s16>))
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE16_V_MF2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 2 x s16>) = G_LOAD %0(p0) :: (load (<vscale x 2 x s16>))
    $v8 = COPY %1(<vscale x 2 x s16>)
    PseudoRET implicit $v8

...
---
name:            vload_nx4i16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx4i16
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE16_V_M1_:%[0-9]+]]:vr = PseudoVLE16_V_M1 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s16>))
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE16_V_M1_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx4i16
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE16_V_M1_:%[0-9]+]]:vr = PseudoVLE16_V_M1 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s16>))
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE16_V_M1_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 4 x s16>) = G_LOAD %0(p0) :: (load (<vscale x 4 x s16>))
    $v8 = COPY %1(<vscale x 4 x s16>)
    PseudoRET implicit $v8

...
---
name:            vload_nx8i16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx8i16
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE16_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE16_V_M2 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 8 x s16>))
    ; RV32I-NEXT: $v8m2 = COPY [[PseudoVLE16_V_M2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m2
    ;
    ; RV64I-LABEL: name: vload_nx8i16
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE16_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE16_V_M2 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 8 x s16>))
    ; RV64I-NEXT: $v8m2 = COPY [[PseudoVLE16_V_M2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m2
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 8 x s16>) = G_LOAD %0(p0) :: (load (<vscale x 8 x s16>))
    $v8m2 = COPY %1(<vscale x 8 x s16>)
    PseudoRET implicit $v8m2

...
---
name:            vload_nx16i16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx16i16
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm4 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE16_V_M4_:%[0-9]+]]:vrm4 = PseudoVLE16_V_M4 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s16>))
    ; RV32I-NEXT: $v8m4 = COPY [[PseudoVLE16_V_M4_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m4
    ;
    ; RV64I-LABEL: name: vload_nx16i16
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm4 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE16_V_M4_:%[0-9]+]]:vrm4 = PseudoVLE16_V_M4 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s16>))
    ; RV64I-NEXT: $v8m4 = COPY [[PseudoVLE16_V_M4_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m4
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 16 x s16>) = G_LOAD %0(p0) :: (load (<vscale x 16 x s16>))
    $v8m4 = COPY %1(<vscale x 16 x s16>)
    PseudoRET implicit $v8m4

...
---
name:            vload_nx32i16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx32i16
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm8 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE16_V_M8_:%[0-9]+]]:vrm8 = PseudoVLE16_V_M8 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 32 x s16>))
    ; RV32I-NEXT: $v8m8 = COPY [[PseudoVLE16_V_M8_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m8
    ;
    ; RV64I-LABEL: name: vload_nx32i16
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm8 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE16_V_M8_:%[0-9]+]]:vrm8 = PseudoVLE16_V_M8 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 32 x s16>))
    ; RV64I-NEXT: $v8m8 = COPY [[PseudoVLE16_V_M8_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 32 x s16>) = G_LOAD %0(p0) :: (load (<vscale x 32 x s16>))
    $v8m8 = COPY %1(<vscale x 32 x s16>)
    PseudoRET implicit $v8m8

...
---
name:            vload_nx1i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx1i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE32_V_MF2_:%[0-9]+]]:vr = PseudoVLE32_V_MF2 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 1 x s32>))
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE32_V_MF2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx1i32
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE32_V_MF2_:%[0-9]+]]:vr = PseudoVLE32_V_MF2 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 1 x s32>))
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE32_V_MF2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 1 x s32>) = G_LOAD %0(p0) :: (load (<vscale x 1 x s32>))
    $v8 = COPY %1(<vscale x 1 x s32>)
    PseudoRET implicit $v8

...
---
name:            vload_nx2i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx2i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE32_V_M1_:%[0-9]+]]:vr = PseudoVLE32_V_M1 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s32>))
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE32_V_M1_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx2i32
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE32_V_M1_:%[0-9]+]]:vr = PseudoVLE32_V_M1 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s32>))
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE32_V_M1_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 2 x s32>) = G_LOAD %0(p0) :: (load (<vscale x 2 x s32>))
    $v8 = COPY %1(<vscale x 2 x s32>)
    PseudoRET implicit $v8

...
---
name:            vload_nx4i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx4i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE32_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE32_V_M2 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s32>))
    ; RV32I-NEXT: $v8m2 = COPY [[PseudoVLE32_V_M2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m2
    ;
    ; RV64I-LABEL: name: vload_nx4i32
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE32_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE32_V_M2 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s32>))
    ; RV64I-NEXT: $v8m2 = COPY [[PseudoVLE32_V_M2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m2
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 4 x s32>) = G_LOAD %0(p0) :: (load (<vscale x 4 x s32>))
    $v8m2 = COPY %1(<vscale x 4 x s32>)
    PseudoRET implicit $v8m2

...
---
name:            vload_nx8i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx8i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm4 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE32_V_M4_:%[0-9]+]]:vrm4 = PseudoVLE32_V_M4 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 8 x s32>))
    ; RV32I-NEXT: $v8m4 = COPY [[PseudoVLE32_V_M4_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m4
    ;
    ; RV64I-LABEL: name: vload_nx8i32
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm4 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE32_V_M4_:%[0-9]+]]:vrm4 = PseudoVLE32_V_M4 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 8 x s32>))
    ; RV64I-NEXT: $v8m4 = COPY [[PseudoVLE32_V_M4_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m4
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 8 x s32>) = G_LOAD %0(p0) :: (load (<vscale x 8 x s32>))
    $v8m4 = COPY %1(<vscale x 8 x s32>)
    PseudoRET implicit $v8m4

...
---
name:            vload_nx16i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx16i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm8 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE32_V_M8_:%[0-9]+]]:vrm8 = PseudoVLE32_V_M8 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s32>))
    ; RV32I-NEXT: $v8m8 = COPY [[PseudoVLE32_V_M8_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m8
    ;
    ; RV64I-LABEL: name: vload_nx16i32
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm8 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE32_V_M8_:%[0-9]+]]:vrm8 = PseudoVLE32_V_M8 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s32>))
    ; RV64I-NEXT: $v8m8 = COPY [[PseudoVLE32_V_M8_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 16 x s32>) = G_LOAD %0(p0) :: (load (<vscale x 16 x s32>))
    $v8m8 = COPY %1(<vscale x 16 x s32>)
    PseudoRET implicit $v8m8

...
---
name:            vload_nx1i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx1i64
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE64_V_M1_:%[0-9]+]]:vr = PseudoVLE64_V_M1 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 1 x s64>))
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE64_V_M1_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx1i64
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE64_V_M1_:%[0-9]+]]:vr = PseudoVLE64_V_M1 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 1 x s64>))
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE64_V_M1_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 1 x s64>) = G_LOAD %0(p0) :: (load (<vscale x 1 x s64>))
    $v8 = COPY %1(<vscale x 1 x s64>)
    PseudoRET implicit $v8

...
---
name:            vload_nx2i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx2i64
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE64_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE64_V_M2 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s64>))
    ; RV32I-NEXT: $v8m2 = COPY [[PseudoVLE64_V_M2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m2
    ;
    ; RV64I-LABEL: name: vload_nx2i64
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE64_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE64_V_M2 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s64>))
    ; RV64I-NEXT: $v8m2 = COPY [[PseudoVLE64_V_M2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m2
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 2 x s64>) = G_LOAD %0(p0) :: (load (<vscale x 2 x s64>))
    $v8m2 = COPY %1(<vscale x 2 x s64>)
    PseudoRET implicit $v8m2

...
---
name:            vload_nx4i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx4i64
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm4 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE64_V_M4_:%[0-9]+]]:vrm4 = PseudoVLE64_V_M4 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s64>))
    ; RV32I-NEXT: $v8m4 = COPY [[PseudoVLE64_V_M4_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m4
    ;
    ; RV64I-LABEL: name: vload_nx4i64
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm4 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE64_V_M4_:%[0-9]+]]:vrm4 = PseudoVLE64_V_M4 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s64>))
    ; RV64I-NEXT: $v8m4 = COPY [[PseudoVLE64_V_M4_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m4
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 4 x s64>) = G_LOAD %0(p0) :: (load (<vscale x 4 x s64>))
    $v8m4 = COPY %1(<vscale x 4 x s64>)
    PseudoRET implicit $v8m4

...
---
name:            vload_nx8i64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx8i64
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm8 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE64_V_M8_:%[0-9]+]]:vrm8 = PseudoVLE64_V_M8 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 8 x s64>))
    ; RV32I-NEXT: $v8m8 = COPY [[PseudoVLE64_V_M8_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m8
    ;
    ; RV64I-LABEL: name: vload_nx8i64
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm8 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE64_V_M8_:%[0-9]+]]:vrm8 = PseudoVLE64_V_M8 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 8 x s64>))
    ; RV64I-NEXT: $v8m8 = COPY [[PseudoVLE64_V_M8_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 8 x s64>) = G_LOAD %0(p0) :: (load (<vscale x 8 x s64>))
    $v8m8 = COPY %1(<vscale x 8 x s64>)
    PseudoRET implicit $v8m8

...
---
name:            vload_nx16i8_align1
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx16i8_align1
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE8_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE8_V_M2 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s8>), align 1)
    ; RV32I-NEXT: $v8m2 = COPY [[PseudoVLE8_V_M2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m2
    ;
    ; RV64I-LABEL: name: vload_nx16i8_align1
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE8_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE8_V_M2 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s8>), align 1)
    ; RV64I-NEXT: $v8m2 = COPY [[PseudoVLE8_V_M2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m2
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 16 x s8>) = G_LOAD %0(p0) :: (load (<vscale x 16 x s8>), align 1)
    $v8m2 = COPY %1(<vscale x 16 x s8>)
    PseudoRET implicit $v8m2

...
---
name:            vload_nx16i8_align2
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx16i8_align2
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE8_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE8_V_M2 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s8>), align 2)
    ; RV32I-NEXT: $v8m2 = COPY [[PseudoVLE8_V_M2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m2
    ;
    ; RV64I-LABEL: name: vload_nx16i8_align2
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE8_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE8_V_M2 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s8>), align 2)
    ; RV64I-NEXT: $v8m2 = COPY [[PseudoVLE8_V_M2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m2
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 16 x s8>) = G_LOAD %0(p0) :: (load (<vscale x 16 x s8>), align 2)
    $v8m2 = COPY %1(<vscale x 16 x s8>)
    PseudoRET implicit $v8m2

...
---
name:            vload_nx16i8_align16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx16i8_align16
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE8_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE8_V_M2 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s8>))
    ; RV32I-NEXT: $v8m2 = COPY [[PseudoVLE8_V_M2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m2
    ;
    ; RV64I-LABEL: name: vload_nx16i8_align16
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE8_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE8_V_M2 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s8>))
    ; RV64I-NEXT: $v8m2 = COPY [[PseudoVLE8_V_M2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m2
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 16 x s8>) = G_LOAD %0(p0) :: (load (<vscale x 16 x s8>))
    $v8m2 = COPY %1(<vscale x 16 x s8>)
    PseudoRET implicit $v8m2

...
---
name:            vload_nx16i8_align64
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx16i8_align64
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE8_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE8_V_M2 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s8>), align 64)
    ; RV32I-NEXT: $v8m2 = COPY [[PseudoVLE8_V_M2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m2
    ;
    ; RV64I-LABEL: name: vload_nx16i8_align64
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE8_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE8_V_M2 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s8>), align 64)
    ; RV64I-NEXT: $v8m2 = COPY [[PseudoVLE8_V_M2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m2
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 16 x s8>) = G_LOAD %0(p0) :: (load (<vscale x 16 x s8>), align 64)
    $v8m2 = COPY %1(<vscale x 16 x s8>)
    PseudoRET implicit $v8m2

...
---
name:            vload_nx4i16_align1
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx4i16_align1
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE8_V_M1_:%[0-9]+]]:vr = PseudoVLE8_V_M1 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 8 x s8>), align 1)
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE8_V_M1_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx4i16_align1
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE8_V_M1_:%[0-9]+]]:vr = PseudoVLE8_V_M1 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 8 x s8>), align 1)
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE8_V_M1_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %2:vrb(<vscale x 8 x s8>) = G_LOAD %0(p0) :: (load (<vscale x 8 x s8>), align 1)
    %1:vrb(<vscale x 4 x s16>) = G_BITCAST %2(<vscale x 8 x s8>)
    $v8 = COPY %1(<vscale x 4 x s16>)
    PseudoRET implicit $v8

...
---
name:            vload_nx4i16_align2
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx4i16_align2
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE16_V_M1_:%[0-9]+]]:vr = PseudoVLE16_V_M1 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s16>), align 2)
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE16_V_M1_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx4i16_align2
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE16_V_M1_:%[0-9]+]]:vr = PseudoVLE16_V_M1 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s16>), align 2)
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE16_V_M1_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 4 x s16>) = G_LOAD %0(p0) :: (load (<vscale x 4 x s16>), align 2)
    $v8 = COPY %1(<vscale x 4 x s16>)
    PseudoRET implicit $v8

...
---
name:            vload_nx4i16_align4
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx4i16_align4
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE16_V_M1_:%[0-9]+]]:vr = PseudoVLE16_V_M1 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s16>), align 4)
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE16_V_M1_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx4i16_align4
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE16_V_M1_:%[0-9]+]]:vr = PseudoVLE16_V_M1 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s16>), align 4)
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE16_V_M1_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 4 x s16>) = G_LOAD %0(p0) :: (load (<vscale x 4 x s16>), align 4)
    $v8 = COPY %1(<vscale x 4 x s16>)
    PseudoRET implicit $v8

...
---
name:            vload_nx4i16_align8
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx4i16_align8
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE16_V_M1_:%[0-9]+]]:vr = PseudoVLE16_V_M1 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s16>))
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE16_V_M1_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx4i16_align8
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE16_V_M1_:%[0-9]+]]:vr = PseudoVLE16_V_M1 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s16>))
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE16_V_M1_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 4 x s16>) = G_LOAD %0(p0) :: (load (<vscale x 4 x s16>))
    $v8 = COPY %1(<vscale x 4 x s16>)
    PseudoRET implicit $v8

...
---
name:            vload_nx4i16_align16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx4i16_align16
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE16_V_M1_:%[0-9]+]]:vr = PseudoVLE16_V_M1 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s16>), align 16)
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE16_V_M1_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx4i16_align16
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE16_V_M1_:%[0-9]+]]:vr = PseudoVLE16_V_M1 [[DEF]], [[COPY]], -1, 4 /* e16 */, 3 /* ta, ma */ :: (load (<vscale x 4 x s16>), align 16)
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE16_V_M1_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 4 x s16>) = G_LOAD %0(p0) :: (load (<vscale x 4 x s16>), align 16)
    $v8 = COPY %1(<vscale x 4 x s16>)
    PseudoRET implicit $v8

...
---
name:            vload_nx2i32_align2
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx2i32_align2
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE8_V_M1_:%[0-9]+]]:vr = PseudoVLE8_V_M1 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 8 x s8>), align 2)
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE8_V_M1_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx2i32_align2
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE8_V_M1_:%[0-9]+]]:vr = PseudoVLE8_V_M1 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 8 x s8>), align 2)
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE8_V_M1_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %2:vrb(<vscale x 8 x s8>) = G_LOAD %0(p0) :: (load (<vscale x 8 x s8>), align 2)
    %1:vrb(<vscale x 2 x s32>) = G_BITCAST %2(<vscale x 8 x s8>)
    $v8 = COPY %1(<vscale x 2 x s32>)
    PseudoRET implicit $v8

...
---
name:            vload_nx2i32_align4
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx2i32_align4
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE32_V_M1_:%[0-9]+]]:vr = PseudoVLE32_V_M1 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s32>), align 4)
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE32_V_M1_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx2i32_align4
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE32_V_M1_:%[0-9]+]]:vr = PseudoVLE32_V_M1 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s32>), align 4)
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE32_V_M1_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 2 x s32>) = G_LOAD %0(p0) :: (load (<vscale x 2 x s32>), align 4)
    $v8 = COPY %1(<vscale x 2 x s32>)
    PseudoRET implicit $v8

...
---
name:            vload_nx2i32_align8
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx2i32_align8
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE32_V_M1_:%[0-9]+]]:vr = PseudoVLE32_V_M1 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s32>))
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE32_V_M1_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx2i32_align8
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE32_V_M1_:%[0-9]+]]:vr = PseudoVLE32_V_M1 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s32>))
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE32_V_M1_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 2 x s32>) = G_LOAD %0(p0) :: (load (<vscale x 2 x s32>))
    $v8 = COPY %1(<vscale x 2 x s32>)
    PseudoRET implicit $v8

...
---
name:            vload_nx2i32_align16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx2i32_align16
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE32_V_M1_:%[0-9]+]]:vr = PseudoVLE32_V_M1 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s32>), align 16)
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE32_V_M1_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx2i32_align16
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE32_V_M1_:%[0-9]+]]:vr = PseudoVLE32_V_M1 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s32>), align 16)
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE32_V_M1_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 2 x s32>) = G_LOAD %0(p0) :: (load (<vscale x 2 x s32>), align 16)
    $v8 = COPY %1(<vscale x 2 x s32>)
    PseudoRET implicit $v8

...
---
name:            vload_nx2i32_align256
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx2i32_align256
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE32_V_M1_:%[0-9]+]]:vr = PseudoVLE32_V_M1 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s32>), align 256)
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE32_V_M1_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx2i32_align256
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE32_V_M1_:%[0-9]+]]:vr = PseudoVLE32_V_M1 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s32>), align 256)
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE32_V_M1_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 2 x s32>) = G_LOAD %0(p0) :: (load (<vscale x 2 x s32>), align 256)
    $v8 = COPY %1(<vscale x 2 x s32>)
    PseudoRET implicit $v8

...
---
name:            vload_nx2i64_align4
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx2i64_align4
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE8_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE8_V_M2 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s8>), align 4)
    ; RV32I-NEXT: $v8m2 = COPY [[PseudoVLE8_V_M2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m2
    ;
    ; RV64I-LABEL: name: vload_nx2i64_align4
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE8_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE8_V_M2 [[DEF]], [[COPY]], -1, 3 /* e8 */, 3 /* ta, ma */ :: (load (<vscale x 16 x s8>), align 4)
    ; RV64I-NEXT: $v8m2 = COPY [[PseudoVLE8_V_M2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m2
    %0:gprb(p0) = COPY $x10
    %2:vrb(<vscale x 16 x s8>) = G_LOAD %0(p0) :: (load (<vscale x 16 x s8>), align 4)
    %1:vrb(<vscale x 2 x s64>) = G_BITCAST %2(<vscale x 16 x s8>)
    $v8m2 = COPY %1(<vscale x 2 x s64>)
    PseudoRET implicit $v8m2

...
---
name:            vload_nx2i64_align8
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx2i64_align8
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE64_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE64_V_M2 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s64>), align 8)
    ; RV32I-NEXT: $v8m2 = COPY [[PseudoVLE64_V_M2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m2
    ;
    ; RV64I-LABEL: name: vload_nx2i64_align8
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE64_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE64_V_M2 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s64>), align 8)
    ; RV64I-NEXT: $v8m2 = COPY [[PseudoVLE64_V_M2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m2
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 2 x s64>) = G_LOAD %0(p0) :: (load (<vscale x 2 x s64>), align 8)
    $v8m2 = COPY %1(<vscale x 2 x s64>)
    PseudoRET implicit $v8m2

...
---
name:            vload_nx2i64_align16
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx2i64_align16
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE64_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE64_V_M2 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s64>))
    ; RV32I-NEXT: $v8m2 = COPY [[PseudoVLE64_V_M2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m2
    ;
    ; RV64I-LABEL: name: vload_nx2i64_align16
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE64_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE64_V_M2 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s64>))
    ; RV64I-NEXT: $v8m2 = COPY [[PseudoVLE64_V_M2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m2
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 2 x s64>) = G_LOAD %0(p0) :: (load (<vscale x 2 x s64>))
    $v8m2 = COPY %1(<vscale x 2 x s64>)
    PseudoRET implicit $v8m2

...
---
name:            vload_nx2i64_align32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx2i64_align32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE64_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE64_V_M2 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s64>), align 32)
    ; RV32I-NEXT: $v8m2 = COPY [[PseudoVLE64_V_M2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m2
    ;
    ; RV64I-LABEL: name: vload_nx2i64_align32
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE64_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE64_V_M2 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 2 x s64>), align 32)
    ; RV64I-NEXT: $v8m2 = COPY [[PseudoVLE64_V_M2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m2
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 2 x s64>) = G_LOAD %0(p0) :: (load (<vscale x 2 x s64>), align 32)
    $v8m2 = COPY %1(<vscale x 2 x s64>)
    PseudoRET implicit $v8m2

...
---
name:            vload_nx1ptr
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx1ptr
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE32_V_MF2_:%[0-9]+]]:vr = PseudoVLE32_V_MF2 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 1 x p0>))
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE32_V_MF2_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx1ptr
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE64_V_M1_:%[0-9]+]]:vr = PseudoVLE64_V_M1 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 1 x p0>))
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE64_V_M1_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 1 x p0>) = G_LOAD %0(p0) :: (load (<vscale x 1 x p0>))
    $v8 = COPY %1(<vscale x 1 x p0>)
    PseudoRET implicit $v8

...
---
name:            vload_nx2ptr
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx2ptr
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vr = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE32_V_M1_:%[0-9]+]]:vr = PseudoVLE32_V_M1 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 2 x p0>))
    ; RV32I-NEXT: $v8 = COPY [[PseudoVLE32_V_M1_]]
    ; RV32I-NEXT: PseudoRET implicit $v8
    ;
    ; RV64I-LABEL: name: vload_nx2ptr
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm2 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE64_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE64_V_M2 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 2 x p0>))
    ; RV64I-NEXT: $v8 = COPY [[PseudoVLE64_V_M2_]]
    ; RV64I-NEXT: PseudoRET implicit $v8
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 2 x p0>) = G_LOAD %0(p0) :: (load (<vscale x 2 x p0>))
    $v8 = COPY %1(<vscale x 2 x p0>)
    PseudoRET implicit $v8

...
---
name:            vload_nx8ptr
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $x10

    ; RV32I-LABEL: name: vload_nx8ptr
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[DEF:%[0-9]+]]:vrm4 = IMPLICIT_DEF
    ; RV32I-NEXT: [[PseudoVLE32_V_M4_:%[0-9]+]]:vrm4 = PseudoVLE32_V_M4 [[DEF]], [[COPY]], -1, 5 /* e32 */, 3 /* ta, ma */ :: (load (<vscale x 8 x p0>))
    ; RV32I-NEXT: $v8m4 = COPY [[PseudoVLE32_V_M4_]]
    ; RV32I-NEXT: PseudoRET implicit $v8m4
    ;
    ; RV64I-LABEL: name: vload_nx8ptr
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV64I-NEXT: [[DEF:%[0-9]+]]:vrm8 = IMPLICIT_DEF
    ; RV64I-NEXT: [[PseudoVLE64_V_M8_:%[0-9]+]]:vrm8 = PseudoVLE64_V_M8 [[DEF]], [[COPY]], -1, 6 /* e64 */, 3 /* ta, ma */ :: (load (<vscale x 8 x p0>))
    ; RV64I-NEXT: $v8m4 = COPY [[PseudoVLE64_V_M8_]]
    ; RV64I-NEXT: PseudoRET implicit $v8m4
    %0:gprb(p0) = COPY $x10
    %1:vrb(<vscale x 8 x p0>) = G_LOAD %0(p0) :: (load (<vscale x 8 x p0>))
    $v8m4 = COPY %1(<vscale x 8 x p0>)
    PseudoRET implicit $v8m4

...
