; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=memcpyopt,dse -S -verify-memoryssa | FileCheck %s
; PR2077

target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:32:32"
target triple = "i386-pc-linux-gnu"

%0 = type { x86_fp80, x86_fp80 }

define internal fastcc void @initialize(ptr noalias nocapture sret(%0) %agg.result) nounwind {
; CHECK-LABEL: @initialize(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    store x86_fp80 0xK00000000000000000000, ptr [[AGG_RESULT:%.*]], align 4
; CHECK-NEXT:    [[AGG_RESULT_15:%.*]] = getelementptr [[TMP0:%.*]], ptr [[AGG_RESULT]], i32 0, i32 1
; CHECK-NEXT:    store x86_fp80 0xK00000000000000000000, ptr [[AGG_RESULT_15]], align 4
; CHECK-NEXT:    ret void
;
entry:
  store x86_fp80 0xK00000000000000000000, ptr %agg.result
  %agg.result.15 = getelementptr %0, ptr %agg.result, i32 0, i32 1
  store x86_fp80 0xK00000000000000000000, ptr %agg.result.15
  ret void
}

declare fastcc x86_fp80 @passed_uninitialized(ptr nocapture) nounwind

define fastcc void @badly_optimized() nounwind {
; CHECK-LABEL: @badly_optimized(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[Z:%.*]] = alloca [[TMP0:%.*]], align 8
; CHECK-NEXT:    [[TMP:%.*]] = alloca [[TMP0]], align 8
; CHECK-NEXT:    [[MEMTMP:%.*]] = alloca [[TMP0]], align 8
; CHECK-NEXT:    call fastcc void @initialize(ptr noalias sret([[TMP0]]) [[Z]])
; CHECK-NEXT:    [[TMP5:%.*]] = call fastcc x86_fp80 @passed_uninitialized(ptr [[Z]])
; CHECK-NEXT:    ret void
;
entry:
  %z = alloca %0
  %tmp = alloca %0
  %memtmp = alloca %0, align 8
  call fastcc void @initialize(ptr noalias sret(%0) %memtmp)
  call void @llvm.memcpy.p0.p0.i32(ptr align 8 %tmp, ptr align 8 %memtmp, i32 24, i1 false)
  call void @llvm.memcpy.p0.p0.i32(ptr align 8 %z, ptr align 8 %tmp, i32 24, i1 false)
  %tmp5 = call fastcc x86_fp80 @passed_uninitialized(ptr %z)
  ret void
}

declare void @llvm.memcpy.p0.p0.i32(ptr nocapture, ptr nocapture, i32, i1) nounwind
