; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=memcpyopt -S -verify-memoryssa | FileCheck %s

declare void @llvm.memcpy.p0.p0.i64(ptr noalias nocapture writeonly,
  ptr noalias nocapture readonly,
  i64, i1 immarg)
declare i32 @use(ptr)

; Positive: stores fully cover the byval, dest is sret
define void @byval_to_sret_full_cover(ptr noalias sret([3 x i32]) %ret,
; CHECK-LABEL: define void @byval_to_sret_full_cover(
; CHECK-SAME: ptr noalias sret([3 x i32]) [[RET:%.*]], ptr noalias byval([3 x i32]) [[A:%.*]], ptr noalias readonly [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[V0]], ptr [[RET]], align 4
; CHECK-NEXT:    [[PB1:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 1
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr [[PB1]], align 4
; CHECK-NEXT:    [[PA1:%.*]] = getelementptr inbounds i32, ptr [[RET]], i64 1
; CHECK-NEXT:    store i32 [[V1]], ptr [[PA1]], align 4
; CHECK-NEXT:    [[PB2:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 2
; CHECK-NEXT:    [[V2:%.*]] = load i32, ptr [[PB2]], align 4
; CHECK-NEXT:    [[PA2:%.*]] = getelementptr inbounds i32, ptr [[RET]], i64 2
; CHECK-NEXT:    store i32 [[V2]], ptr [[PA2]], align 4
; CHECK-NEXT:    ret void
;
  ptr noalias byval([3 x i32]) %a,
  ptr noalias readonly %b) {
entry:
  %v0 = load i32, ptr %b, align 4
  store i32 %v0, ptr %a, align 4
  %pb1 = getelementptr inbounds i32, ptr %b, i64 1
  %v1 = load i32, ptr %pb1, align 4
  %pa1 = getelementptr inbounds i32, ptr %a, i64 1
  store i32 %v1, ptr %pa1, align 4
  %pb2 = getelementptr inbounds i32, ptr %b, i64 2
  %v2 = load i32, ptr %pb2, align 4
  %pa2 = getelementptr inbounds i32, ptr %a, i64 2
  store i32 %v2, ptr %pa2, align 4
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %ret, ptr align 4 %a, i64 12, i1 false)
  ret void
}

; Positive: dest is noalias writable
define void @byval_to_writable_full_cover(ptr noalias align 4 writable dereferenceable(12) %ret,
; CHECK-LABEL: define void @byval_to_writable_full_cover(
; CHECK-SAME: ptr noalias writable align 4 dereferenceable(12) [[RET:%.*]], ptr noalias byval([3 x i32]) [[A:%.*]], ptr noalias readonly [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[V0]], ptr [[RET]], align 4
; CHECK-NEXT:    [[PB1:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 1
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr [[PB1]], align 4
; CHECK-NEXT:    [[PA1:%.*]] = getelementptr inbounds i32, ptr [[RET]], i64 1
; CHECK-NEXT:    store i32 [[V1]], ptr [[PA1]], align 4
; CHECK-NEXT:    [[PB2:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 2
; CHECK-NEXT:    [[V2:%.*]] = load i32, ptr [[PB2]], align 4
; CHECK-NEXT:    [[PA2:%.*]] = getelementptr inbounds i32, ptr [[RET]], i64 2
; CHECK-NEXT:    store i32 [[V2]], ptr [[PA2]], align 4
; CHECK-NEXT:    ret void
;
  ptr noalias byval([3 x i32]) %a,
  ptr noalias readonly %b) {
entry:
  %v0 = load i32, ptr %b, align 4
  store i32 %v0, ptr %a, align 4
  %pb1 = getelementptr inbounds i32, ptr %b, i64 1
  %v1 = load i32, ptr %pb1, align 4
  %pa1 = getelementptr inbounds i32, ptr %a, i64 1
  store i32 %v1, ptr %pa1, align 4
  %pb2 = getelementptr inbounds i32, ptr %b, i64 2
  %v2 = load i32, ptr %pb2, align 4
  %pa2 = getelementptr inbounds i32, ptr %a, i64 2
  store i32 %v2, ptr %pa2, align 4
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %ret, ptr align 4 %a, i64 12, i1 false)
  ret void
}

; Negative: only the first 4 bytes are stored
define void @byval_to_sret_partial_cover(ptr noalias sret([3 x i32]) %ret,
; CHECK-LABEL: define void @byval_to_sret_partial_cover(
; CHECK-SAME: ptr noalias sret([3 x i32]) [[RET:%.*]], ptr noalias byval([3 x i32]) [[A:%.*]], ptr noalias readonly [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[V0]], ptr [[A]], align 4
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[RET]], ptr align 4 [[A]], i64 12, i1 false)
; CHECK-NEXT:    ret void
;
  ptr noalias byval([3 x i32]) %a,
  ptr noalias readonly %b) {
entry:
  %v0 = load i32, ptr %b, align 4
  store i32 %v0, ptr %a, align 4
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %ret, ptr align 4 %a, i64 12, i1 false)
  ret void
}

@sink = external global i32

; Negative: the byval is read by something other than the memcpy
define void @byval_with_extra_load(ptr noalias sret([3 x i32]) %ret,
; CHECK-LABEL: define void @byval_with_extra_load(
; CHECK-SAME: ptr noalias sret([3 x i32]) [[RET:%.*]], ptr noalias byval([3 x i32]) [[A:%.*]], ptr noalias readonly [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[OBSERVE:%.*]] = load i32, ptr [[A]], align 4
; CHECK-NEXT:    store i32 [[OBSERVE]], ptr @sink, align 4
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[V0]], ptr [[A]], align 4
; CHECK-NEXT:    [[PB1:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 1
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr [[PB1]], align 4
; CHECK-NEXT:    [[PA1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 1
; CHECK-NEXT:    store i32 [[V1]], ptr [[PA1]], align 4
; CHECK-NEXT:    [[PB2:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 2
; CHECK-NEXT:    [[V2:%.*]] = load i32, ptr [[PB2]], align 4
; CHECK-NEXT:    [[PA2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 2
; CHECK-NEXT:    store i32 [[V2]], ptr [[PA2]], align 4
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[RET]], ptr align 4 [[A]], i64 12, i1 false)
; CHECK-NEXT:    ret void
;
  ptr noalias byval([3 x i32]) %a,
  ptr noalias readonly %b) {
entry:
  %observe = load i32, ptr %a, align 4
  store i32 %observe, ptr @sink, align 4
  %v0 = load i32, ptr %b, align 4
  store i32 %v0, ptr %a, align 4
  %pb1 = getelementptr inbounds i32, ptr %b, i64 1
  %v1 = load i32, ptr %pb1, align 4
  %pa1 = getelementptr inbounds i32, ptr %a, i64 1
  store i32 %v1, ptr %pa1, align 4
  %pb2 = getelementptr inbounds i32, ptr %b, i64 2
  %v2 = load i32, ptr %pb2, align 4
  %pa2 = getelementptr inbounds i32, ptr %a, i64 2
  store i32 %v2, ptr %pa2, align 4
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %ret, ptr align 4 %a, i64 12, i1 false)
  ret void
}

; Negative: dest is not a noalias argument
define void @dest_not_noalias(ptr sret([3 x i32]) %ret,
; CHECK-LABEL: define void @dest_not_noalias(
; CHECK-SAME: ptr sret([3 x i32]) [[RET:%.*]], ptr noalias byval([3 x i32]) [[A:%.*]], ptr noalias readonly [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[V0]], ptr [[A]], align 4
; CHECK-NEXT:    [[PB1:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 1
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr [[PB1]], align 4
; CHECK-NEXT:    [[PA1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 1
; CHECK-NEXT:    store i32 [[V1]], ptr [[PA1]], align 4
; CHECK-NEXT:    [[PB2:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 2
; CHECK-NEXT:    [[V2:%.*]] = load i32, ptr [[PB2]], align 4
; CHECK-NEXT:    [[PA2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 2
; CHECK-NEXT:    store i32 [[V2]], ptr [[PA2]], align 4
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[RET]], ptr align 4 [[A]], i64 12, i1 false)
; CHECK-NEXT:    ret void
;
  ptr noalias byval([3 x i32]) %a,
  ptr noalias readonly %b) {
entry:
  %v0 = load i32, ptr %b, align 4
  store i32 %v0, ptr %a, align 4
  %pb1 = getelementptr inbounds i32, ptr %b, i64 1
  %v1 = load i32, ptr %pb1, align 4
  %pa1 = getelementptr inbounds i32, ptr %a, i64 1
  store i32 %v1, ptr %pa1, align 4
  %pb2 = getelementptr inbounds i32, ptr %b, i64 2
  %v2 = load i32, ptr %pb2, align 4
  %pa2 = getelementptr inbounds i32, ptr %a, i64 2
  store i32 %v2, ptr %pa2, align 4
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %ret, ptr align 4 %a, i64 12, i1 false)
  ret void
}

; Negative: stores live in a different basic block than the memcpy
define void @stores_in_different_bb(ptr noalias sret([3 x i32]) %ret,
; CHECK-LABEL: define void @stores_in_different_bb(
; CHECK-SAME: ptr noalias sret([3 x i32]) [[RET:%.*]], ptr noalias byval([3 x i32]) [[A:%.*]], ptr noalias readonly [[B:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[COND]], label %[[STORE_BB:.*]], label %[[STORE_BB]]
; CHECK:       [[STORE_BB]]:
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[V0]], ptr [[A]], align 4
; CHECK-NEXT:    [[PB1:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 1
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr [[PB1]], align 4
; CHECK-NEXT:    [[PA1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 1
; CHECK-NEXT:    store i32 [[V1]], ptr [[PA1]], align 4
; CHECK-NEXT:    [[PB2:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 2
; CHECK-NEXT:    [[V2:%.*]] = load i32, ptr [[PB2]], align 4
; CHECK-NEXT:    [[PA2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 2
; CHECK-NEXT:    store i32 [[V2]], ptr [[PA2]], align 4
; CHECK-NEXT:    br label %[[CPY_BB:.*]]
; CHECK:       [[CPY_BB]]:
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[RET]], ptr align 4 [[A]], i64 12, i1 false)
; CHECK-NEXT:    ret void
;
  ptr noalias byval([3 x i32]) %a,
  ptr noalias readonly %b,
  i1 %cond) {
entry:
  br i1 %cond, label %store_bb, label %store_bb

store_bb:
  %v0 = load i32, ptr %b, align 4
  store i32 %v0, ptr %a, align 4
  %pb1 = getelementptr inbounds i32, ptr %b, i64 1
  %v1 = load i32, ptr %pb1, align 4
  %pa1 = getelementptr inbounds i32, ptr %a, i64 1
  store i32 %v1, ptr %pa1, align 4
  %pb2 = getelementptr inbounds i32, ptr %b, i64 2
  %v2 = load i32, ptr %pb2, align 4
  %pa2 = getelementptr inbounds i32, ptr %a, i64 2
  store i32 %v2, ptr %pa2, align 4
  br label %cpy_bb

cpy_bb:
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %ret, ptr align 4 %a, i64 12, i1 false)
  ret void
}

; Negative: byval is used elsewhere
define void @byval_passed_to_call(ptr noalias sret([3 x i32]) %ret,
; CHECK-LABEL: define void @byval_passed_to_call(
; CHECK-SAME: ptr noalias sret([3 x i32]) [[RET:%.*]], ptr noalias byval([3 x i32]) [[A:%.*]], ptr noalias readonly [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[V0]], ptr [[A]], align 4
; CHECK-NEXT:    [[PB1:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 1
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr [[PB1]], align 4
; CHECK-NEXT:    [[PA1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 1
; CHECK-NEXT:    store i32 [[V1]], ptr [[PA1]], align 4
; CHECK-NEXT:    [[PB2:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 2
; CHECK-NEXT:    [[V2:%.*]] = load i32, ptr [[PB2]], align 4
; CHECK-NEXT:    [[PA2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 2
; CHECK-NEXT:    store i32 [[V2]], ptr [[PA2]], align 4
; CHECK-NEXT:    [[U:%.*]] = call i32 @use(ptr [[A]])
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[RET]], ptr align 4 [[A]], i64 12, i1 false)
; CHECK-NEXT:    ret void
;
  ptr noalias byval([3 x i32]) %a,
  ptr noalias readonly %b) {
entry:
  %v0 = load i32, ptr %b, align 4
  store i32 %v0, ptr %a, align 4
  %pb1 = getelementptr inbounds i32, ptr %b, i64 1
  %v1 = load i32, ptr %pb1, align 4
  %pa1 = getelementptr inbounds i32, ptr %a, i64 1
  store i32 %v1, ptr %pa1, align 4
  %pb2 = getelementptr inbounds i32, ptr %b, i64 2
  %v2 = load i32, ptr %pb2, align 4
  %pa2 = getelementptr inbounds i32, ptr %a, i64 2
  store i32 %v2, ptr %pa2, align 4
  %u = call i32 @use(ptr %a)
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %ret, ptr align 4 %a, i64 12, i1 false)
  ret void
}

; Negative: dest's memcpy alignment is weaker than the byval's
define void @dest_underaligned(ptr noalias sret([3 x i32]) %ret,
; CHECK-LABEL: define void @dest_underaligned(
; CHECK-SAME: ptr noalias sret([3 x i32]) [[RET:%.*]], ptr noalias byval([3 x i32]) align 4 [[A:%.*]], ptr noalias readonly [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[V0]], ptr [[A]], align 4
; CHECK-NEXT:    [[PB1:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 1
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr [[PB1]], align 4
; CHECK-NEXT:    [[PA1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 1
; CHECK-NEXT:    store i32 [[V1]], ptr [[PA1]], align 4
; CHECK-NEXT:    [[PB2:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 2
; CHECK-NEXT:    [[V2:%.*]] = load i32, ptr [[PB2]], align 4
; CHECK-NEXT:    [[PA2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 2
; CHECK-NEXT:    store i32 [[V2]], ptr [[PA2]], align 4
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 1 [[RET]], ptr align 4 [[A]], i64 12, i1 false)
; CHECK-NEXT:    ret void
;
  ptr noalias byval([3 x i32]) align 4 %a,
  ptr noalias readonly %b) {
entry:
  %v0 = load i32, ptr %b, align 4
  store i32 %v0, ptr %a, align 4
  %pb1 = getelementptr inbounds i32, ptr %b, i64 1
  %v1 = load i32, ptr %pb1, align 4
  %pa1 = getelementptr inbounds i32, ptr %a, i64 1
  store i32 %v1, ptr %pa1, align 4
  %pb2 = getelementptr inbounds i32, ptr %b, i64 2
  %v2 = load i32, ptr %pb2, align 4
  %pa2 = getelementptr inbounds i32, ptr %a, i64 2
  store i32 %v2, ptr %pa2, align 4
  call void @llvm.memcpy.p0.p0.i64(ptr align 1 %ret, ptr align 4 %a, i64 12, i1 false)
  ret void
}

; Negative: a call between the first store and the memcpy may modref dest
define void @use_between_stores_and_memcpy(ptr noalias sret([3 x i32]) %ret,
; CHECK-LABEL: define void @use_between_stores_and_memcpy(
; CHECK-SAME: ptr noalias sret([3 x i32]) [[RET:%.*]], ptr noalias byval([3 x i32]) [[A:%.*]], ptr noalias readonly [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[V0]], ptr [[A]], align 4
; CHECK-NEXT:    call void @use(ptr [[RET]])
; CHECK-NEXT:    [[PB1:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 1
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr [[PB1]], align 4
; CHECK-NEXT:    [[PA1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 1
; CHECK-NEXT:    store i32 [[V1]], ptr [[PA1]], align 4
; CHECK-NEXT:    [[PB2:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 2
; CHECK-NEXT:    [[V2:%.*]] = load i32, ptr [[PB2]], align 4
; CHECK-NEXT:    [[PA2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 2
; CHECK-NEXT:    store i32 [[V2]], ptr [[PA2]], align 4
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[RET]], ptr align 4 [[A]], i64 12, i1 false)
; CHECK-NEXT:    ret void
;
  ptr noalias byval([3 x i32]) %a,
  ptr noalias readonly %b) {
entry:
  %v0 = load i32, ptr %b, align 4
  store i32 %v0, ptr %a, align 4
  call void @use(ptr %ret)
  %pb1 = getelementptr inbounds i32, ptr %b, i64 1
  %v1 = load i32, ptr %pb1, align 4
  %pa1 = getelementptr inbounds i32, ptr %a, i64 1
  store i32 %v1, ptr %pa1, align 4
  %pb2 = getelementptr inbounds i32, ptr %b, i64 2
  %v2 = load i32, ptr %pb2, align 4
  %pa2 = getelementptr inbounds i32, ptr %a, i64 2
  store i32 %v2, ptr %pa2, align 4
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %ret, ptr align 4 %a, i64 12, i1 false)
  ret void
}

; Negative: the byval pointer is stored as a value instead of just being a store address
define void @byval_address_escapes_via_store(ptr noalias sret(ptr) %ret,
; CHECK-LABEL: define void @byval_address_escapes_via_store(
; CHECK-SAME: ptr noalias sret(ptr) [[RET:%.*]], ptr noalias byval(ptr) [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store ptr [[A]], ptr [[A]], align 8
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[RET]], ptr align 8 [[A]], i64 8, i1 false)
; CHECK-NEXT:    ret void
;
  ptr noalias byval(ptr) %a) {
entry:
  store ptr %a, ptr %a, align 8
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %ret, ptr align 8 %a, i64 8, i1 false)
  ret void
}
