; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt < %s -loop-reduce -S | FileCheck %s

; LSR shouldn't consider %t8 to be an interesting user of %t6, and it
; should be able to form pretty GEPs.

target datalayout = "e-p:64:64:64-p1:16:16:16-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64"

; Copy of uglygep with a different address space
; This tests expandAddToGEP uses the right smaller integer type for
; another address space
define void @Z4(ptr addrspace(1) %ptr.i8, ptr addrspace(1) %ptr.float) {
; CHECK-LABEL: define void @Z4
; CHECK-SAME: (ptr addrspace(1) [[PTR_I8:%.*]], ptr addrspace(1) [[PTR_FLOAT:%.*]]) {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    br label [[BB3:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    br i1 true, label [[BB10:%.*]], label [[BB2:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    [[T:%.*]] = add i16 [[T4:%.*]], 1
; CHECK-NEXT:    br label [[BB3]]
; CHECK:       bb3:
; CHECK-NEXT:    [[T4]] = phi i16 [ [[T]], [[BB2]] ], [ 0, [[BB:%.*]] ]
; CHECK-NEXT:    br label [[BB1:%.*]]
; CHECK:       bb10:
; CHECK-NEXT:    [[T7:%.*]] = icmp eq i16 [[T4]], 0
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr addrspace(1) [[PTR_I8]], i16 [[T4]]
; CHECK-NEXT:    br label [[BB14:%.*]]
; CHECK:       bb14:
; CHECK-NEXT:    store i8 undef, ptr addrspace(1) [[SCEVGEP]], align 1
; CHECK-NEXT:    [[T6:%.*]] = load ptr addrspace(1), ptr addrspace(1) [[PTR_FLOAT]], align 2
; CHECK-NEXT:    [[SCEVGEP1:%.*]] = getelementptr i8, ptr addrspace(1) [[T6]], i16 16
; CHECK-NEXT:    [[SCEVGEP2:%.*]] = getelementptr i8, ptr addrspace(1) [[SCEVGEP1]], i16 [[T4]]
; CHECK-NEXT:    store i8 undef, ptr addrspace(1) [[SCEVGEP2]], align 1
; CHECK-NEXT:    br label [[BB14]]
;
bb:
  br label %bb3

bb1:                                              ; preds = %bb3
  br i1 undef, label %bb10, label %bb2

bb2:                                              ; preds = %bb1
  %t = add i16 %t4, 1                         ; <i16> [#uses=1]
  br label %bb3

bb3:                                              ; preds = %bb2, %bb
  %t4 = phi i16 [ %t, %bb2 ], [ 0, %bb ]      ; <i16> [#uses=3]
  br label %bb1

bb10:                                             ; preds = %bb9
  %t7 = icmp eq i16 %t4, 0                    ; <i1> [#uses=1]
  %t3 = add i16 %t4, 16                     ; <i16> [#uses=1]
  br label %bb14

bb14:                                             ; preds = %bb14, %bb10
  %t2 = getelementptr inbounds i8, ptr addrspace(1) %ptr.i8, i16 %t4 ; <ptr> [#uses=1]
  store i8 undef, ptr addrspace(1) %t2
  %t6 = load ptr addrspace(1), ptr addrspace(1) %ptr.float
  %t9 = getelementptr inbounds i8, ptr addrspace(1) %t6, i16 %t3 ; <ptr> [#uses=1]
  store i8 undef, ptr addrspace(1) %t9
  br label %bb14
}

