; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes="loop(invalidate<all>,loop-unroll-and-jam,loop-unroll-and-jam)" -allow-unroll-and-jam -unroll-and-jam-count=4 < %s -S | FileCheck %s

; This test completely unrolls the middle loop out of a 3-deep loop nest.

define i16 @test_it() {
; CHECK-LABEL: define i16 @test_it() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[FOR_COND:.*]]
; CHECK:       [[FOR_COND_LOOPEXIT:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND]]
; CHECK:       [[FOR_COND]]:
; CHECK-NEXT:    br label %[[DO_BODY2:.*]]
; CHECK:       [[DO_BODY2]]:
; CHECK-NEXT:    br label %[[WHILE_COND3:.*]]
; CHECK:       [[WHILE_COND3]]:
; CHECK-NEXT:    br i1 true, label %[[DO_COND:.*]], label %[[WHILE_COND3]]
; CHECK:       [[DO_COND]]:
; CHECK-NEXT:    br label %[[FOR_COND_LOOPEXIT]]
;
entry:
  br label %for.cond

for.cond:                                         ; preds = %do.cond, %entry
  br label %do.body2

do.body2:                                         ; preds = %do.cond, %for.cond
  br label %while.cond3

while.cond3:                                      ; preds = %while.cond3, %do.body2
  br i1 true, label %do.cond, label %while.cond3

do.cond:                                          ; preds = %while.cond3
  br i1 true, label %for.cond, label %do.body2
}

