; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=hotcoldsplit -S < %s | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define i64 @combined_bridge() {
; CHECK-LABEL: define i64 @combined_bridge() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 false, label %[[LOOP_I:.*]], label %[[FAILED_I:.*]], !prof [[PROF0:![0-9]+]]
; CHECK:       [[LOOP_I]]:
; CHECK-NEXT:    br i1 false, label %[[GUARDED1_I:.*]], label %[[DEOPT2_I:.*]]
; CHECK:       [[DEOPT2_I]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 (...) @llvm.experimental.deoptimize.i64() [ "deopt"() ]
; CHECK-NEXT:    ret i64 [[TMP0]]
; CHECK:       [[GUARDED1_I]]:
; CHECK-NEXT:    [[IV_NEXT_I147:%.*]] = add i32 0, 0
; CHECK-NEXT:    [[LOOP_COND_I148:%.*]] = icmp ult i32 0, 0
; CHECK-NEXT:    ret i64 0
; CHECK:       [[FAILED_I]]:
; CHECK-NEXT:    ret i64 0
;
entry:
  br i1 false, label %loop.i, label %failed.i, !prof !0

loop.i:                                           ; preds = %entry
  br i1 false, label %guarded1.i, label %deopt2.i

deopt2.i:                                         ; preds = %loop.i
  %0 = call i64 (...) @llvm.experimental.deoptimize.i64() [ "deopt"() ]
  ret i64 %0

guarded1.i:                                       ; preds = %loop.i
  %iv.next.i147 = add i32 0, 0
  %loop.cond.i148 = icmp ult i32 0, 0
  ret i64 0

failed.i:                                         ; preds = %entry
  ret i64 0
}

declare i64 @llvm.experimental.deoptimize.i64(...)

!0 = !{!"branch_weights", i32 1, i32 1000}
;.
; CHECK: [[PROF0]] = !{!"branch_weights", i32 1, i32 1000}
;.
