SWIFT_SOURCES := main.swift
SWIFT_BRIDGING_HEADER := bridging-header.h
# The overlay injection only works when the header is imported from source!
SWIFT_PRECOMPILE_BRIDGING_HEADER := NO

SWIFTFLAGS_EXTRAS = -I$(SRCDIR)

include Makefile.rules
