; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=aggressive-instcombine -S | FileCheck %s

define i1 @leaf1_and_aa(i1 %a)  {
; CHECK-LABEL: @leaf1_and_aa(
; CHECK-NEXT:    [[AND_AA:%.*]] = and i1 [[A:%.*]], [[A]]
; CHECK-NEXT:    ret i1 [[AND_AA]]
;
  %and.aa = and i1 %a, %a
  ret i1 %and.aa
}

define i1 @leaf1_xor_aa(i1 %a)  {
; CHECK-LABEL: @leaf1_xor_aa(
; CHECK-NEXT:    [[XOR_AA:%.*]] = xor i1 [[A:%.*]], [[A]]
; CHECK-NEXT:    ret i1 [[XOR_AA]]
;
  %xor.aa = xor i1 %a, %a
  ret i1 %xor.aa
}

define i1 @leaf1_and_not(i1 %a)  {
; CHECK-LABEL: @leaf1_and_not(
; CHECK-NEXT:    [[NOT_A:%.*]] = xor i1 [[A:%.*]], true
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[A]], [[NOT_A]]
; CHECK-NEXT:    ret i1 [[AND]]
;
  %not.a = xor i1 %a, true
  %and = and i1 %a, %not.a
  ret i1 %and
}

define i1 @leaf1_or_not(i1 %a)  {
; CHECK-LABEL: @leaf1_or_not(
; CHECK-NEXT:    [[NOT_A:%.*]] = xor i1 [[A:%.*]], true
; CHECK-NEXT:    [[OR:%.*]] = or i1 [[A]], [[NOT_A]]
; CHECK-NEXT:    ret i1 [[OR]]
;
  %not.a = xor i1 %a, true
  %or = or i1 %a, %not.a
  ret i1 %or
}

define i1 @leaf2_xor(i1 %a, i1 %b)  {
; CHECK-LABEL: @leaf2_xor(
; CHECK-NEXT:    [[AB:%.*]] = xor i1 [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    [[XOR_AB_A:%.*]] = xor i1 [[AB]], [[A]]
; CHECK-NEXT:    ret i1 [[XOR_AB_A]]
;
  %ab = xor i1 %a, %b
  %xor.ab.a = xor i1 %ab, %a
  ret i1 %xor.ab.a
}

define i1 @leaf2_xor_ret_const_false(i1 %a, i1 %b)  {
; CHECK-LABEL: @leaf2_xor_ret_const_false(
; CHECK-NEXT:    [[XOR_AB:%.*]] = xor i1 [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    [[XOR_AB_A:%.*]] = xor i1 [[XOR_AB]], [[A]]
; CHECK-NEXT:    [[XOR_AB_A_B:%.*]] = xor i1 [[XOR_AB_A]], [[B]]
; CHECK-NEXT:    ret i1 [[XOR_AB_A_B]]
;
  %xor.ab = xor i1 %a, %b
  %xor.ab.a = xor i1 %xor.ab, %a
  %xor.ab.a.b = xor i1 %xor.ab.a, %b
  ret i1 %xor.ab.a.b
}

define i1 @leaf2_or_ret_leaf(i1 %a, i1 %b)  {
; CHECK-LABEL: @leaf2_or_ret_leaf(
; CHECK-NEXT:    [[OR_AB:%.*]] = or i1 [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    [[AND_AB:%.*]] = and i1 [[A]], [[B]]
; CHECK-NEXT:    [[XOR1:%.*]] = xor i1 [[OR_AB]], [[AND_AB]]
; CHECK-NEXT:    [[XOR2:%.*]] = xor i1 [[XOR1]], [[A]]
; CHECK-NEXT:    ret i1 [[XOR2]]
;
  %or.ab = or i1 %a, %b
  %and.ab = and i1 %a, %b
  %xor1 = xor i1 %or.ab, %and.ab
  %xor2 = xor i1 %xor1, %a
  ret i1 %xor2
}

define i1 @leaf2_or_ret_const_false(i1 %a, i1 %b)  {
; CHECK-LABEL: @leaf2_or_ret_const_false(
; CHECK-NEXT:    [[OR_AB:%.*]] = or i1 [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    [[AND_AB:%.*]] = and i1 [[A]], [[B]]
; CHECK-NEXT:    [[XOR1:%.*]] = xor i1 [[OR_AB]], [[AND_AB]]
; CHECK-NEXT:    [[XOR2:%.*]] = xor i1 [[XOR1]], [[A]]
; CHECK-NEXT:    [[XOR3:%.*]] = xor i1 [[XOR1]], [[B]]
; CHECK-NEXT:    ret i1 [[XOR3]]
;
  %or.ab = or i1 %a, %b
  %and.ab = and i1 %a, %b
  %xor1 = xor i1 %or.ab, %and.ab
  %xor2 = xor i1 %xor1, %a
  %xor3 = xor i1 %xor1, %b
  ret i1 %xor3
}

define i4 @leaf2_type_is_i4(i4 %a, i4 %b) {
; CHECK-LABEL: @leaf2_type_is_i4(
; CHECK-NEXT:    [[XOR_AB:%.*]] = xor i4 [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    [[NOT_A:%.*]] = xor i4 [[A]], -1
; CHECK-NEXT:    [[XOR2:%.*]] = xor i4 [[NOT_A]], [[B]]
; CHECK-NEXT:    [[OR:%.*]] = or i4 [[XOR2]], [[XOR_AB]]
; CHECK-NEXT:    ret i4 [[OR]]
;
  %xor.ab = xor i4 %a, %b
  %not.a = xor i4 %a, -1
  %xor2 = xor i4 %not.a, %b
  %or = or i4 %xor2, %xor.ab
  ret i4 %or
}

define i1 @leaf3_complex_ret_const_false(i1 %a, i1 %b, i1 %c)  {
; CHECK-LABEL: @leaf3_complex_ret_const_false(
; CHECK-NEXT:    [[AB:%.*]] = or i1 [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    [[ABC:%.*]] = or i1 [[AB]], [[C:%.*]]
; CHECK-NEXT:    [[NOT_ABC:%.*]] = xor i1 [[ABC]], true
; CHECK-NEXT:    [[R:%.*]] = and i1 [[NOT_ABC]], [[A]]
; CHECK-NEXT:    ret i1 [[R]]
;
  %ab = or i1 %a, %b
  %abc = or i1 %ab, %c
  %not.abc = xor i1 %abc, true
  %r = and i1 %not.abc, %a
  ret i1 %r
}

define i1 @leaf3_complex_ret_leaf(i1 %a, i1 %b, i1 %c) {
; CHECK-LABEL: @leaf3_complex_ret_leaf(
; CHECK-NEXT:    [[AB:%.*]] = and i1 [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    [[BC:%.*]] = and i1 [[B]], [[C:%.*]]
; CHECK-NEXT:    [[XOR_AC:%.*]] = xor i1 [[A]], [[C]]
; CHECK-NEXT:    [[OR:%.*]] = or i1 [[AB]], [[XOR_AC]]
; CHECK-NEXT:    [[NOT_BC:%.*]] = xor i1 [[BC]], true
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[NOT_BC]], [[A]]
; CHECK-NEXT:    [[COND:%.*]] = xor i1 [[AND]], [[OR]]
; CHECK-NEXT:    ret i1 [[COND]]
;
  %ab = and i1 %a, %b
  %bc = and i1 %b, %c
  %xor.ac = xor i1 %a, %c
  %or = or i1 %ab, %xor.ac
  %not.bc = xor i1 %bc, true
  %and = and i1 %not.bc, %a
  %cond = xor i1 %and, %or
  ret i1 %cond
}

define i1 @leaf4_ret_const_true(i1 %a, i1 %b, i1 %c, i1 %d)  {
; CHECK-LABEL: @leaf4_ret_const_true(
; CHECK-NEXT:    [[BD:%.*]] = and i1 [[B:%.*]], [[D:%.*]]
; CHECK-NEXT:    [[NOT_BD:%.*]] = xor i1 [[BD]], true
; CHECK-NEXT:    [[XOR_AB:%.*]] = xor i1 [[A:%.*]], [[B]]
; CHECK-NEXT:    [[OR1:%.*]] = or i1 [[XOR_AB]], [[C:%.*]]
; CHECK-NEXT:    [[OR2:%.*]] = or i1 [[OR1]], [[NOT_BD]]
; CHECK-NEXT:    [[OR3:%.*]] = or i1 [[OR2]], [[A]]
; CHECK-NEXT:    ret i1 [[OR3]]
;
  %bd = and i1 %b, %d
  %not.bd = xor i1 %bd, true
  %xor.ab = xor i1 %a, %b
  %or1 = or i1 %xor.ab, %c
  %or2 = or i1 %or1, %not.bd
  %or3 = or i1 %or2, %a
  ret i1 %or3
}

define i1 @leaf4_ret_leaf(i1 %a, i1 %b, i1 %c, i1 %d)  {
; CHECK-LABEL: @leaf4_ret_leaf(
; CHECK-NEXT:    [[BD:%.*]] = and i1 [[B:%.*]], [[D:%.*]]
; CHECK-NEXT:    [[XOR:%.*]] = xor i1 [[BD]], [[C:%.*]]
; CHECK-NEXT:    [[NOT_BD:%.*]] = xor i1 [[XOR]], true
; CHECK-NEXT:    [[XOR_AB:%.*]] = xor i1 [[A:%.*]], [[B]]
; CHECK-NEXT:    [[OR1:%.*]] = or i1 [[XOR_AB]], [[C]]
; CHECK-NEXT:    [[OR2:%.*]] = or i1 [[OR1]], [[NOT_BD]]
; CHECK-NEXT:    [[OR3:%.*]] = or i1 [[OR2]], [[A]]
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[OR3]], [[B]]
; CHECK-NEXT:    ret i1 [[AND]]
;
  %bd = and i1 %b, %d
  %xor = xor i1 %bd, %c
  %not.bd = xor i1 %xor, true
  %xor.ab = xor i1 %a, %b
  %or1 = or i1 %xor.ab, %c
  %or2 = or i1 %or1, %not.bd
  %or3 = or i1 %or2, %a
  %and = and i1 %or3, %b
  ret i1 %and
}

define i1 @leaf4_ret_leaf2(i1 %a, i1 %b, i1 %c, i1 %d)  {
; CHECK-LABEL: @leaf4_ret_leaf2(
; CHECK-NEXT:    [[BD:%.*]] = and i1 [[B:%.*]], [[D:%.*]]
; CHECK-NEXT:    [[XOR:%.*]] = xor i1 [[BD]], [[C:%.*]]
; CHECK-NEXT:    [[NOT_BD:%.*]] = xor i1 [[XOR]], true
; CHECK-NEXT:    [[XOR_AB:%.*]] = xor i1 [[A:%.*]], [[B]]
; CHECK-NEXT:    [[OR1:%.*]] = or i1 [[XOR_AB]], [[C]]
; CHECK-NEXT:    [[OR2:%.*]] = or i1 [[OR1]], [[NOT_BD]]
; CHECK-NEXT:    [[OR3:%.*]] = or i1 [[OR2]], [[A]]
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[OR3]], [[B]]
; CHECK-NEXT:    ret i1 [[AND]]
;
  %bd = and i1 %b, %d
  %xor = xor i1 %bd, %c
  %not.bd = xor i1 %xor, true
  %xor.ab = xor i1 %a, %b
  %or1 = or i1 %xor.ab, %c
  %or2 = or i1 %or1, %not.bd
  %or3 = or i1 %or2, %a
  %and = and i1 %or3, %b
  ret i1 %and
}
