; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=aggressive-instcombine -S | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define dso_local noundef double @CompareDistmats(ptr noundef %distmat1, ptr noundef %distmat2) local_unnamed_addr {
; CHECK-LABEL: @CompareDistmats(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_COND:%.*]]
; CHECK:       for.cond:
; CHECK-NEXT:    [[RMSD_0:%.*]] = phi double [ 0.000000e+00, [[ENTRY:%.*]] ], [ [[TMP2:%.*]], [[FOR_BODY:%.*]] ]
; CHECK-NEXT:    [[CMP:%.*]] = phi i1 [ true, [[ENTRY]] ], [ false, [[FOR_BODY]] ]
; CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    [[SQRT:%.*]] = call double @llvm.sqrt.f64(double [[RMSD_0]])
; CHECK-NEXT:    ret double [[SQRT]]
; CHECK:       for.body:
; CHECK-NEXT:    [[TMP0:%.*]] = load double, ptr [[DISTMAT1:%.*]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = load double, ptr [[DISTMAT2:%.*]], align 8
; CHECK-NEXT:    [[SUB:%.*]] = fsub double [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[TMP2]] = call double @llvm.fmuladd.f64(double [[SUB]], double [[SUB]], double [[RMSD_0]])
; CHECK-NEXT:    br label [[FOR_COND]]
;
entry:
  br label %for.cond

for.cond:                                         ; preds = %for.body, %entry
  %RMSD.0 = phi double [ 0.000000e+00, %entry ], [ %2, %for.body ]
  %cmp = phi i1 [ true, %entry ], [ false, %for.body ]
  br i1 %cmp, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond
  %call = call double @sqrt(double noundef %RMSD.0)
  ret double %call

for.body:                                         ; preds = %for.cond
  %0 = load double, ptr %distmat1, align 8
  %1 = load double, ptr %distmat2, align 8
  %sub = fsub double %0, %1
  %2 = call double @llvm.fmuladd.f64(double %sub, double %sub, double %RMSD.0)
  br label %for.cond
}

; Function Attrs: mustprogress nofree nounwind willreturn memory(write)
declare double @sqrt(double noundef) local_unnamed_addr

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare double @llvm.fmuladd.f64(double, double, double)
