; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt < %s -passes=aggressive-instcombine -S | FileCheck %s

; ============================================================================
; POSITIVE TEST CASES - These should be transformed to ctlz intrinsic
; ============================================================================

@ZSTD_countLeadingZeros32_fallback.DeBruijnClz = internal unnamed_addr constant [32 x i32] [i32 0, i32 9, i32 1, i32 10, i32 13, i32 21, i32 2, i32 29, i32 11, i32 14, i32 16, i32 18, i32 22, i32 25, i32 3, i32 30, i32 8, i32 12, i32 20, i32 28, i32 15, i32 17, i32 24, i32 7, i32 19, i32 27, i32 23, i32 6, i32 26, i32 5, i32 4, i32 31], align 16

; Basic positive test case - standard DeBruijn CTLZ pattern
; Function Attrs: nounwind uwtable
define i32 @ZSTD_countLeadingZeros32_fallback(i32 noundef %val) {
; CHECK-LABEL: define i32 @ZSTD_countLeadingZeros32_fallback
; CHECK-SAME: (i32 noundef [[VAL:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.ctlz.i32(i32 [[VAL]], i1 true)
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq i32 [[VAL]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i32 31, i32 [[TMP0]]
; CHECK-NEXT:    ret i32 [[TMP2]]
;
entry:
  %cmp = icmp ne i32 %val, 0
  %conv = zext i1 %cmp to i32
  %shr = lshr i32 %val, 1
  %or = or i32 %shr, %val
  %shr1 = lshr i32 %or, 2
  %or2 = or i32 %shr1, %or
  %shr3 = lshr i32 %or2, 4
  %or4 = or i32 %shr3, %or2
  %shr5 = lshr i32 %or4, 8
  %or6 = or i32 %shr5, %or4
  %shr7 = lshr i32 %or6, 16
  %or8 = or i32 %shr7, %or6
  %mul = mul i32 %or8, 130329821
  %shr9 = lshr i32 %mul, 27
  %idxprom = zext i32 %shr9 to i64
  %arrayidx = getelementptr inbounds [32 x i32], ptr @ZSTD_countLeadingZeros32_fallback.DeBruijnClz, i64 0, i64 %idxprom
  %0 = load i32, ptr %arrayidx, align 4
  %sub = sub i32 31, %0
  ret i32 %sub
}

; Positive test case with AND mask applied
@ctlz_table_with_mask.DeBruijnClz = internal unnamed_addr constant [32 x i32] [i32 0, i32 9, i32 1, i32 10, i32 13, i32 21, i32 2, i32 29, i32 11, i32 14, i32 16, i32 18, i32 22, i32 25, i32 3, i32 30, i32 8, i32 12, i32 20, i32 28, i32 15, i32 17, i32 24, i32 7, i32 19, i32 27, i32 23, i32 6, i32 26, i32 5, i32 4, i32 31], align 16

define i32 @ctlz_with_and_mask(i32 noundef %val) {
; CHECK-LABEL: define i32 @ctlz_with_and_mask
; CHECK-SAME: (i32 noundef [[VAL:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.ctlz.i32(i32 [[VAL]], i1 true)
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq i32 [[VAL]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i32 31, i32 [[TMP0]]
; CHECK-NEXT:    ret i32 [[TMP2]]
;
entry:
  %shr = lshr i32 %val, 1
  %or = or i32 %shr, %val
  %shr1 = lshr i32 %or, 2
  %or2 = or i32 %shr1, %or
  %shr3 = lshr i32 %or2, 4
  %or4 = or i32 %shr3, %or2
  %shr5 = lshr i32 %or4, 8
  %or6 = or i32 %shr5, %or4
  %shr7 = lshr i32 %or6, 16
  %or8 = or i32 %shr7, %or6
  %mul = mul i32 %or8, 130329821
  %shr9 = lshr i32 %mul, 27
  %and = and i32 %shr9, 31
  %idxprom = zext i32 %and to i64
  %arrayidx = getelementptr inbounds [32 x i32], ptr @ctlz_table_with_mask.DeBruijnClz, i64 0, i64 %idxprom
  %0 = load i32, ptr %arrayidx, align 4
  %sub = sub i32 31, %0
  ret i32 %sub
}

; Positive test case - simplified without unnecessary comparison
@ctlz_table_simple.DeBruijnClz = internal unnamed_addr constant [32 x i32] [i32 0, i32 9, i32 1, i32 10, i32 13, i32 21, i32 2, i32 29, i32 11, i32 14, i32 16, i32 18, i32 22, i32 25, i32 3, i32 30, i32 8, i32 12, i32 20, i32 28, i32 15, i32 17, i32 24, i32 7, i32 19, i32 27, i32 23, i32 6, i32 26, i32 5, i32 4, i32 31], align 16

define i32 @ctlz_simple(i32 noundef %val) {
; CHECK-LABEL: define i32 @ctlz_simple
; CHECK-SAME: (i32 noundef [[VAL:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.ctlz.i32(i32 [[VAL]], i1 true)
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq i32 [[VAL]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i32 31, i32 [[TMP0]]
; CHECK-NEXT:    ret i32 [[TMP2]]
;
entry:
  %shr = lshr i32 %val, 1
  %or = or i32 %shr, %val
  %shr1 = lshr i32 %or, 2
  %or2 = or i32 %shr1, %or
  %shr3 = lshr i32 %or2, 4
  %or4 = or i32 %shr3, %or2
  %shr5 = lshr i32 %or4, 8
  %or6 = or i32 %shr5, %or4
  %shr7 = lshr i32 %or6, 16
  %or8 = or i32 %shr7, %or6
  %mul = mul i32 %or8, 130329821
  %shr9 = lshr i32 %mul, 27
  %idxprom = zext i32 %shr9 to i64
  %arrayidx = getelementptr inbounds [32 x i32], ptr @ctlz_table_simple.DeBruijnClz, i64 0, i64 %idxprom
  %0 = load i32, ptr %arrayidx, align 4
  %sub = sub i32 31, %0
  ret i32 %sub
}

; ============================================================================
; NEGATIVE TEST CASES - These should NOT be transformed
; ============================================================================

; Negative test: Wrong multiplication constant
@wrong_mul_table.DeBruijnClz = internal unnamed_addr constant [32 x i32] [i32 0, i32 9, i32 1, i32 10, i32 13, i32 21, i32 2, i32 29, i32 11, i32 14, i32 16, i32 18, i32 22, i32 25, i32 3, i32 30, i32 8, i32 12, i32 20, i32 28, i32 15, i32 17, i32 24, i32 7, i32 19, i32 27, i32 23, i32 6, i32 26, i32 5, i32 4, i32 31], align 16

define i32 @ctlz_wrong_mul_constant(i32 noundef %val) {
; CHECK-LABEL: define i32 @ctlz_wrong_mul_constant
; CHECK-SAME: (i32 noundef [[VAL:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[VAL]], 1
; CHECK-NEXT:    [[OR:%.*]] = or i32 [[SHR]], [[VAL]]
; CHECK-NEXT:    [[SHR1:%.*]] = lshr i32 [[OR]], 2
; CHECK-NEXT:    [[OR2:%.*]] = or i32 [[SHR1]], [[OR]]
; CHECK-NEXT:    [[SHR3:%.*]] = lshr i32 [[OR2]], 4
; CHECK-NEXT:    [[OR4:%.*]] = or i32 [[SHR3]], [[OR2]]
; CHECK-NEXT:    [[SHR5:%.*]] = lshr i32 [[OR4]], 8
; CHECK-NEXT:    [[OR6:%.*]] = or i32 [[SHR5]], [[OR4]]
; CHECK-NEXT:    [[SHR7:%.*]] = lshr i32 [[OR6]], 16
; CHECK-NEXT:    [[OR8:%.*]] = or i32 [[SHR7]], [[OR6]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 [[OR8]], 999999
; CHECK-NEXT:    [[SHR9:%.*]] = lshr i32 [[MUL]], 27
; CHECK-NEXT:    [[IDXPROM:%.*]] = zext i32 [[SHR9]] to i64
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [32 x i32], ptr @wrong_mul_table.DeBruijnClz, i64 0, i64 [[IDXPROM]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 31, [[TMP0]]
; CHECK-NEXT:    ret i32 [[SUB]]
;
entry:
  %shr = lshr i32 %val, 1
  %or = or i32 %shr, %val
  %shr1 = lshr i32 %or, 2
  %or2 = or i32 %shr1, %or
  %shr3 = lshr i32 %or2, 4
  %or4 = or i32 %shr3, %or2
  %shr5 = lshr i32 %or4, 8
  %or6 = or i32 %shr5, %or4
  %shr7 = lshr i32 %or6, 16
  %or8 = or i32 %shr7, %or6
  %mul = mul i32 %or8, 999999  ; Wrong constant!
  %shr9 = lshr i32 %mul, 27
  %idxprom = zext i32 %shr9 to i64
  %arrayidx = getelementptr inbounds [32 x i32], ptr @wrong_mul_table.DeBruijnClz, i64 0, i64 %idxprom
  %0 = load i32, ptr %arrayidx, align 4
  %sub = sub i32 31, %0
  ret i32 %sub
}

; Negative test: Wrong shift constant in the OR chain
@wrong_shift_table.DeBruijnClz = internal unnamed_addr constant [32 x i32] [i32 0, i32 9, i32 1, i32 10, i32 13, i32 21, i32 2, i32 29, i32 11, i32 14, i32 16, i32 18, i32 22, i32 25, i32 3, i32 30, i32 8, i32 12, i32 20, i32 28, i32 15, i32 17, i32 24, i32 7, i32 19, i32 27, i32 23, i32 6, i32 26, i32 5, i32 4, i32 31], align 16

define i32 @ctlz_wrong_shift_constant(i32 noundef %val) {
; CHECK-LABEL: define i32 @ctlz_wrong_shift_constant
; CHECK-SAME: (i32 noundef [[VAL:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[VAL]], 1
; CHECK-NEXT:    [[OR:%.*]] = or i32 [[SHR]], [[VAL]]
; CHECK-NEXT:    [[SHR1:%.*]] = lshr i32 [[OR]], 3
; CHECK-NEXT:    [[OR2:%.*]] = or i32 [[SHR1]], [[OR]]
; CHECK-NEXT:    [[SHR3:%.*]] = lshr i32 [[OR2]], 4
; CHECK-NEXT:    [[OR4:%.*]] = or i32 [[SHR3]], [[OR2]]
; CHECK-NEXT:    [[SHR5:%.*]] = lshr i32 [[OR4]], 8
; CHECK-NEXT:    [[OR6:%.*]] = or i32 [[SHR5]], [[OR4]]
; CHECK-NEXT:    [[SHR7:%.*]] = lshr i32 [[OR6]], 16
; CHECK-NEXT:    [[OR8:%.*]] = or i32 [[SHR7]], [[OR6]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 [[OR8]], 130329821
; CHECK-NEXT:    [[SHR9:%.*]] = lshr i32 [[MUL]], 27
; CHECK-NEXT:    [[IDXPROM:%.*]] = zext i32 [[SHR9]] to i64
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [32 x i32], ptr @wrong_shift_table.DeBruijnClz, i64 0, i64 [[IDXPROM]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 31, [[TMP0]]
; CHECK-NEXT:    ret i32 [[SUB]]
;
entry:
  %shr = lshr i32 %val, 1
  %or = or i32 %shr, %val
  %shr1 = lshr i32 %or, 3  ; Wrong shift constant! Should be 2
  %or2 = or i32 %shr1, %or
  %shr3 = lshr i32 %or2, 4
  %or4 = or i32 %shr3, %or2
  %shr5 = lshr i32 %or4, 8
  %or6 = or i32 %shr5, %or4
  %shr7 = lshr i32 %or6, 16
  %or8 = or i32 %shr7, %or6
  %mul = mul i32 %or8, 130329821
  %shr9 = lshr i32 %mul, 27
  %idxprom = zext i32 %shr9 to i64
  %arrayidx = getelementptr inbounds [32 x i32], ptr @wrong_shift_table.DeBruijnClz, i64 0, i64 %idxprom
  %0 = load i32, ptr %arrayidx, align 4
  %sub = sub i32 31, %0
  ret i32 %sub
}

; Negative test: Wrong table values (not DeBruijn sequence)
@wrong_table_values.BadTable = internal unnamed_addr constant [32 x i32] [i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 0], align 16

define i32 @ctlz_wrong_table_values(i32 noundef %val) {
; CHECK-LABEL: define i32 @ctlz_wrong_table_values
; CHECK-SAME: (i32 noundef [[VAL:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[VAL]], 1
; CHECK-NEXT:    [[OR:%.*]] = or i32 [[SHR]], [[VAL]]
; CHECK-NEXT:    [[SHR1:%.*]] = lshr i32 [[OR]], 2
; CHECK-NEXT:    [[OR2:%.*]] = or i32 [[SHR1]], [[OR]]
; CHECK-NEXT:    [[SHR3:%.*]] = lshr i32 [[OR2]], 4
; CHECK-NEXT:    [[OR4:%.*]] = or i32 [[SHR3]], [[OR2]]
; CHECK-NEXT:    [[SHR5:%.*]] = lshr i32 [[OR4]], 8
; CHECK-NEXT:    [[OR6:%.*]] = or i32 [[SHR5]], [[OR4]]
; CHECK-NEXT:    [[SHR7:%.*]] = lshr i32 [[OR6]], 16
; CHECK-NEXT:    [[OR8:%.*]] = or i32 [[SHR7]], [[OR6]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 [[OR8]], 130329821
; CHECK-NEXT:    [[SHR9:%.*]] = lshr i32 [[MUL]], 27
; CHECK-NEXT:    [[IDXPROM:%.*]] = zext i32 [[SHR9]] to i64
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [32 x i32], ptr @wrong_table_values.BadTable, i64 0, i64 [[IDXPROM]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 31, [[TMP0]]
; CHECK-NEXT:    ret i32 [[SUB]]
;
entry:
  %shr = lshr i32 %val, 1
  %or = or i32 %shr, %val
  %shr1 = lshr i32 %or, 2
  %or2 = or i32 %shr1, %or
  %shr3 = lshr i32 %or2, 4
  %or4 = or i32 %shr3, %or2
  %shr5 = lshr i32 %or4, 8
  %or6 = or i32 %shr5, %or4
  %shr7 = lshr i32 %or6, 16
  %or8 = or i32 %shr7, %or6
  %mul = mul i32 %or8, 130329821
  %shr9 = lshr i32 %mul, 27
  %idxprom = zext i32 %shr9 to i64
  %arrayidx = getelementptr inbounds [32 x i32], ptr @wrong_table_values.BadTable, i64 0, i64 %idxprom
  %0 = load i32, ptr %arrayidx, align 4
  %sub = sub i32 31, %0
  ret i32 %sub
}

; Negative test: Non-constant global variable (mutable)
@mutable_table.DeBruijnClz = internal unnamed_addr global [32 x i32] [i32 0, i32 9, i32 1, i32 10, i32 13, i32 21, i32 2, i32 29, i32 11, i32 14, i32 16, i32 18, i32 22, i32 25, i32 3, i32 30, i32 8, i32 12, i32 20, i32 28, i32 15, i32 17, i32 24, i32 7, i32 19, i32 27, i32 23, i32 6, i32 26, i32 5, i32 4, i32 31], align 16

define i32 @ctlz_mutable_table(i32 noundef %val) {
; CHECK-LABEL: define i32 @ctlz_mutable_table
; CHECK-SAME: (i32 noundef [[VAL:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[VAL]], 1
; CHECK-NEXT:    [[OR:%.*]] = or i32 [[SHR]], [[VAL]]
; CHECK-NEXT:    [[SHR1:%.*]] = lshr i32 [[OR]], 2
; CHECK-NEXT:    [[OR2:%.*]] = or i32 [[SHR1]], [[OR]]
; CHECK-NEXT:    [[SHR3:%.*]] = lshr i32 [[OR2]], 4
; CHECK-NEXT:    [[OR4:%.*]] = or i32 [[SHR3]], [[OR2]]
; CHECK-NEXT:    [[SHR5:%.*]] = lshr i32 [[OR4]], 8
; CHECK-NEXT:    [[OR6:%.*]] = or i32 [[SHR5]], [[OR4]]
; CHECK-NEXT:    [[SHR7:%.*]] = lshr i32 [[OR6]], 16
; CHECK-NEXT:    [[OR8:%.*]] = or i32 [[SHR7]], [[OR6]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 [[OR8]], 130329821
; CHECK-NEXT:    [[SHR9:%.*]] = lshr i32 [[MUL]], 27
; CHECK-NEXT:    [[IDXPROM:%.*]] = zext i32 [[SHR9]] to i64
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [32 x i32], ptr @mutable_table.DeBruijnClz, i64 0, i64 [[IDXPROM]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 31, [[TMP0]]
; CHECK-NEXT:    ret i32 [[SUB]]
;
entry:
  %shr = lshr i32 %val, 1
  %or = or i32 %shr, %val
  %shr1 = lshr i32 %or, 2
  %or2 = or i32 %shr1, %or
  %shr3 = lshr i32 %or2, 4
  %or4 = or i32 %shr3, %or2
  %shr5 = lshr i32 %or4, 8
  %or6 = or i32 %shr5, %or4
  %shr7 = lshr i32 %or6, 16
  %or8 = or i32 %shr7, %or6
  %mul = mul i32 %or8, 130329821
  %shr9 = lshr i32 %mul, 27
  %idxprom = zext i32 %shr9 to i64
  %arrayidx = getelementptr inbounds [32 x i32], ptr @mutable_table.DeBruijnClz, i64 0, i64 %idxprom
  %0 = load i32, ptr %arrayidx, align 4
  %sub = sub i32 31, %0
  ret i32 %sub
}

; Negative test: Missing one OR operation in the chain
@incomplete_or_table.DeBruijnClz = internal unnamed_addr constant [32 x i32] [i32 0, i32 9, i32 1, i32 10, i32 13, i32 21, i32 2, i32 29, i32 11, i32 14, i32 16, i32 18, i32 22, i32 25, i32 3, i32 30, i32 8, i32 12, i32 20, i32 28, i32 15, i32 17, i32 24, i32 7, i32 19, i32 27, i32 23, i32 6, i32 26, i32 5, i32 4, i32 31], align 16

define i32 @ctlz_incomplete_or_chain(i32 noundef %val) {
; CHECK-LABEL: define i32 @ctlz_incomplete_or_chain
; CHECK-SAME: (i32 noundef [[VAL:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[VAL]], 1
; CHECK-NEXT:    [[OR:%.*]] = or i32 [[SHR]], [[VAL]]
; CHECK-NEXT:    [[SHR1:%.*]] = lshr i32 [[OR]], 2
; CHECK-NEXT:    [[OR2:%.*]] = or i32 [[SHR1]], [[OR]]
; CHECK-NEXT:    [[SHR3:%.*]] = lshr i32 [[OR2]], 4
; CHECK-NEXT:    [[OR4:%.*]] = or i32 [[SHR3]], [[OR2]]
; CHECK-NEXT:    [[SHR5:%.*]] = lshr i32 [[OR4]], 16
; CHECK-NEXT:    [[OR6:%.*]] = or i32 [[SHR5]], [[OR4]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 [[OR6]], 130329821
; CHECK-NEXT:    [[SHR9:%.*]] = lshr i32 [[MUL]], 27
; CHECK-NEXT:    [[IDXPROM:%.*]] = zext i32 [[SHR9]] to i64
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [32 x i32], ptr @incomplete_or_table.DeBruijnClz, i64 0, i64 [[IDXPROM]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 31, [[TMP0]]
; CHECK-NEXT:    ret i32 [[SUB]]
;
entry:
  %shr = lshr i32 %val, 1
  %or = or i32 %shr, %val
  %shr1 = lshr i32 %or, 2
  %or2 = or i32 %shr1, %or
  %shr3 = lshr i32 %or2, 4
  %or4 = or i32 %shr3, %or2
  ; Missing: %shr5 = lshr i32 %or4, 8
  ; Missing: %or6 = or i32 %shr5, %or4
  %shr5 = lshr i32 %or4, 16  ; Skipping the shift by 8
  %or6 = or i32 %shr5, %or4
  %mul = mul i32 %or6, 130329821
  %shr9 = lshr i32 %mul, 27
  %idxprom = zext i32 %shr9 to i64
  %arrayidx = getelementptr inbounds [32 x i32], ptr @incomplete_or_table.DeBruijnClz, i64 0, i64 %idxprom
  %0 = load i32, ptr %arrayidx, align 4
  %sub = sub i32 31, %0
  ret i32 %sub
}

; Negative test: Wrong subtraction pattern (not "31 - load")
@wrong_sub_table.DeBruijnClz = internal unnamed_addr constant [32 x i32] [i32 0, i32 9, i32 1, i32 10, i32 13, i32 21, i32 2, i32 29, i32 11, i32 14, i32 16, i32 18, i32 22, i32 25, i32 3, i32 30, i32 8, i32 12, i32 20, i32 28, i32 15, i32 17, i32 24, i32 7, i32 19, i32 27, i32 23, i32 6, i32 26, i32 5, i32 4, i32 31], align 16

define i32 @ctlz_wrong_subtraction(i32 noundef %val) {
; CHECK-LABEL: define i32 @ctlz_wrong_subtraction
; CHECK-SAME: (i32 noundef [[VAL:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[VAL]], 1
; CHECK-NEXT:    [[OR:%.*]] = or i32 [[SHR]], [[VAL]]
; CHECK-NEXT:    [[SHR1:%.*]] = lshr i32 [[OR]], 2
; CHECK-NEXT:    [[OR2:%.*]] = or i32 [[SHR1]], [[OR]]
; CHECK-NEXT:    [[SHR3:%.*]] = lshr i32 [[OR2]], 4
; CHECK-NEXT:    [[OR4:%.*]] = or i32 [[SHR3]], [[OR2]]
; CHECK-NEXT:    [[SHR5:%.*]] = lshr i32 [[OR4]], 8
; CHECK-NEXT:    [[OR6:%.*]] = or i32 [[SHR5]], [[OR4]]
; CHECK-NEXT:    [[SHR7:%.*]] = lshr i32 [[OR6]], 16
; CHECK-NEXT:    [[OR8:%.*]] = or i32 [[SHR7]], [[OR6]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 [[OR8]], 130329821
; CHECK-NEXT:    [[SHR9:%.*]] = lshr i32 [[MUL]], 27
; CHECK-NEXT:    [[IDXPROM:%.*]] = zext i32 [[SHR9]] to i64
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [32 x i32], ptr @wrong_sub_table.DeBruijnClz, i64 0, i64 [[IDXPROM]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 32, [[TMP0]]
; CHECK-NEXT:    ret i32 [[SUB]]
;
entry:
  %shr = lshr i32 %val, 1
  %or = or i32 %shr, %val
  %shr1 = lshr i32 %or, 2
  %or2 = or i32 %shr1, %or
  %shr3 = lshr i32 %or2, 4
  %or4 = or i32 %shr3, %or2
  %shr5 = lshr i32 %or4, 8
  %or6 = or i32 %shr5, %or4
  %shr7 = lshr i32 %or6, 16
  %or8 = or i32 %shr7, %or6
  %mul = mul i32 %or8, 130329821
  %shr9 = lshr i32 %mul, 27
  %idxprom = zext i32 %shr9 to i64
  %arrayidx = getelementptr inbounds [32 x i32], ptr @wrong_sub_table.DeBruijnClz, i64 0, i64 %idxprom
  %0 = load i32, ptr %arrayidx, align 4
  %sub = sub i32 32, %0  ; Wrong! Should be 31
  ret i32 %sub
}
