; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=newgvn -S | FileCheck %s

@p = global i32 0

define noundef i32 @opt_predicateinfo_phi(i32 %0, i1 %1) {
; CHECK-LABEL: @opt_predicateinfo_phi(
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i32 [[TMP0:%.*]], 0
; CHECK-NEXT:    br i1 [[TMP1:%.*]], label [[TMP3:%.*]], label [[TMP4:%.*]]
; CHECK:       3:
; CHECK-NEXT:    store i32 1, ptr @p, align 4
; CHECK-NEXT:    br i1 [[COND]], label [[TMP5:%.*]], label [[COMMON_RET:%.*]]
; CHECK:       common.ret:
; CHECK-NEXT:    ret i32 0
; CHECK:       4:
; CHECK-NEXT:    store i32 2, ptr @p, align 4
; CHECK-NEXT:    br i1 [[COND]], label [[TMP5]], label [[COMMON_RET]]
; CHECK:       5:
; CHECK-NEXT:    store i32 0, ptr @p, align 4
; CHECK-NEXT:    br label [[COMMON_RET]]
;
  %cond = icmp eq i32 %0, 0
  br i1 %1, label %3, label %4

3:
  store i32 1, ptr @p, align 4
  br i1 %cond, label %5, label %common.ret

common.ret:
  ret i32 0

4:
  store i32 2, ptr @p, align 4
  br i1 %cond, label %5, label %common.ret

5:
  store i32 %0, ptr @p, align 4
  br label %common.ret
}
