; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -S < %s -passes=newgvn | FileCheck %s

define void @hoge(i1 %c1, i1 %c2, i1 %c3, i1 %c4) {
; CHECK-LABEL: define void @hoge(
; CHECK-SAME: i1 [[C1:%.*]], i1 [[C2:%.*]], i1 [[C3:%.*]], i1 [[C4:%.*]]) {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    br label [[BB1:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[TMP:%.*]] = phi i8 [ [[TMP3:%.*]], [[BB12:%.*]] ], [ 0, [[BB:%.*]] ]
; CHECK-NEXT:    br i1 [[C1]], label [[BB2:%.*]], label [[BB13:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    [[TMP3]] = phi i8 [ [[TMP]], [[BB1]] ], [ [[TMP5:%.*]], [[BB4:%.*]] ]
; CHECK-NEXT:    br i1 [[C2]], label [[BB12]], label [[BB4]]
; CHECK:       bb4:
; CHECK-NEXT:    [[TMP5]] = phi i8 [ [[TMP3]], [[BB2]] ], [ [[TMP7:%.*]], [[BB11:%.*]] ]
; CHECK-NEXT:    br i1 false, label [[BB6:%.*]], label [[BB2]]
; CHECK:       bb6:
; CHECK-NEXT:    [[TMP7]] = phi i8 [ poison, [[BB4]] ], [ [[TMP10:%.*]], [[BB9:%.*]] ]
; CHECK-NEXT:    br i1 [[C3]], label [[BB11]], label [[BB8:%.*]]
; CHECK:       bb8:
; CHECK-NEXT:    br i1 true, label [[BB8]], label [[BB9]]
; CHECK:       bb9:
; CHECK-NEXT:    [[TMP10]] = phi i8 [ [[TMP16:%.*]], [[BB15:%.*]] ], [ poison, [[BB8]] ]
; CHECK-NEXT:    br label [[BB6]]
; CHECK:       bb11:
; CHECK-NEXT:    br label [[BB4]]
; CHECK:       bb12:
; CHECK-NEXT:    br label [[BB1]]
; CHECK:       bb13:
; CHECK-NEXT:    br i1 [[C4]], label [[BB14:%.*]], label [[BB15]]
; CHECK:       bb14:
; CHECK-NEXT:    br label [[BB15]]
; CHECK:       bb15:
; CHECK-NEXT:    [[TMP16]] = phi i8 [ [[TMP]], [[BB13]] ], [ 9, [[BB14]] ]
; CHECK-NEXT:    br label [[BB9]]
;
bb:
br label %bb1

bb1: ; preds = %bb12, %bb
%tmp = phi i8 [ %tmp3, %bb12 ], [ 0, %bb ]
br i1 %c1, label %bb2, label %bb13

bb2: ; preds = %bb4, %bb1
%tmp3 = phi i8 [ %tmp, %bb1 ], [ %tmp5, %bb4 ]
br i1 %c2, label %bb12, label %bb4

bb4: ; preds = %bb11, %bb2
%tmp5 = phi i8 [ %tmp3, %bb2 ], [ %tmp7, %bb11 ]
br i1 false, label %bb6, label %bb2

bb6: ; preds = %bb9, %bb4
%tmp7 = phi i8 [ %tmp5, %bb4 ], [ %tmp10, %bb9 ]
br i1 %c3, label %bb11, label %bb8

bb8: ; preds = %bb8, %bb6
br i1 true, label %bb8, label %bb9

bb9: ; preds = %bb15, %bb8
%tmp10 = phi i8 [ %tmp16, %bb15 ], [ %tmp7, %bb8 ]
br label %bb6

bb11: ; preds = %bb6
br label %bb4

bb12: ; preds = %bb2
br label %bb1

bb13: ; preds = %bb1
br i1 %c4, label %bb14, label %bb15

bb14: ; preds = %bb13
br label %bb15

bb15: ; preds = %bb14, %bb13
%tmp16 = phi i8 [ %tmp, %bb13 ], [ 9, %bb14 ]
br label %bb9
}
