; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -S < %s -passes=newgvn | FileCheck %s
define i32 @function_1(i1 %arg, i1 %bc ) {
; CHECK-LABEL: define i32 @function_1(
; CHECK-SAME: i1 [[ARG:%.*]], i1 [[BC:%.*]]) {
; CHECK-NEXT:  entry_1:
; CHECK-NEXT:    br i1 [[BC]], label [[BB_5:%.*]], label [[BB_6:%.*]]
; CHECK:       bb_5:
; CHECK-NEXT:    br label [[BB_6]]
; CHECK:       bb_6:
; CHECK-NEXT:    [[A:%.*]] = phi i1 [ [[ARG]], [[BB_5]] ], [ [[A]], [[BB_4:%.*]] ], [ true, [[ENTRY_1:%.*]] ]
; CHECK-NEXT:    [[C:%.*]] = phi i1 [ [[ARG]], [[BB_5]] ], [ [[C]], [[BB_4]] ], [ true, [[ENTRY_1]] ]
; CHECK-NEXT:    br label [[BB_4]]
; CHECK:       bb_4:
; CHECK-NEXT:    br i1 [[ARG]], label [[BB_6]], label [[BB_4]]
;
entry_1:
  br i1 %bc, label %bb_5, label %bb_6

bb_5:
  br label %bb_6

bb_6:
  %a = phi i1 [ %arg, %bb_5 ], [ %a.1, %bb_4 ], [ 1, %entry_1 ]
  %c = phi i1 [ %arg, %bb_5 ], [ %c.1, %bb_4 ], [ 1, %entry_1 ]
  br label %bb_4


bb_4:
  %a.1 = phi i1  [ %a.1, %bb_4 ], [ %a, %bb_6 ]
  %c.1 = phi i1 [ %c.1, %bb_4 ], [ %c, %bb_6 ]
  br i1 %arg, label %bb_6, label %bb_4
}
