; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-apple-darwin -mattr=+shstk,+egpr --show-mc-encoding | FileCheck %s

define void @test_wrssd(i32 %a, ptr %__p) {
; CHECK-LABEL: test_wrssd:
; CHECK:       ## %bb.0: ## %entry
; CHECK-NEXT:    wrssd %edi, (%rsi) ## encoding: [0x62,0xf4,0x7c,0x08,0x66,0x3e]
; CHECK-NEXT:    retq ## encoding: [0xc3]
entry:
  tail call void @llvm.x86.wrssd(i32 %a, ptr %__p)
  ret void
}

declare void @llvm.x86.wrssd(i32, ptr)

define void @test_wrssq(i64 %a, ptr %__p) {
; CHECK-LABEL: test_wrssq:
; CHECK:       ## %bb.0: ## %entry
; CHECK-NEXT:    wrssq %rdi, (%rsi) ## encoding: [0x62,0xf4,0xfc,0x08,0x66,0x3e]
; CHECK-NEXT:    retq ## encoding: [0xc3]
entry:
  tail call void @llvm.x86.wrssq(i64 %a, ptr %__p)
  ret void
}

declare void @llvm.x86.wrssq(i64, ptr)

define void @test_wrussd(i32 %a, ptr %__p) {
; CHECK-LABEL: test_wrussd:
; CHECK:       ## %bb.0: ## %entry
; CHECK-NEXT:    wrussd %edi, (%rsi) ## encoding: [0x62,0xf4,0x7d,0x08,0x65,0x3e]
; CHECK-NEXT:    retq ## encoding: [0xc3]
entry:
  tail call void @llvm.x86.wrussd(i32 %a, ptr %__p)
  ret void
}

declare void @llvm.x86.wrussd(i32, ptr)

define void @test_wrussq(i64 %a, ptr %__p) {
; CHECK-LABEL: test_wrussq:
; CHECK:       ## %bb.0: ## %entry
; CHECK-NEXT:    wrussq %rdi, (%rsi) ## encoding: [0x62,0xf4,0xfd,0x08,0x65,0x3e]
; CHECK-NEXT:    retq ## encoding: [0xc3]
entry:
  tail call void @llvm.x86.wrussq(i64 %a, ptr %__p)
  ret void
}

declare void @llvm.x86.wrussq(i64, ptr)
