; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+invpcid,+egpr --show-mc-encoding | FileCheck %s

define void @test_invpcid(i32 %type, ptr %descriptor) {
; CHECK-LABEL: test_invpcid:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %edi, %eax # encoding: [0x89,0xf8]
; CHECK-NEXT:    invpcid (%rsi), %rax # encoding: [0x62,0xf4,0x7e,0x08,0xf2,0x06]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  call void @llvm.x86.invpcid(i32 %type, ptr %descriptor)
  ret void
}

define void @test_invpcid2(ptr readonly %type, ptr %descriptor) {
; CHECK-LABEL: test_invpcid2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl (%rdi), %eax # encoding: [0x8b,0x07]
; CHECK-NEXT:    invpcid (%rsi), %rax # encoding: [0x62,0xf4,0x7e,0x08,0xf2,0x06]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %0 = load i32, ptr %type, align 4
  tail call void @llvm.x86.invpcid(i32 %0, ptr %descriptor) #1
  ret void
}

declare void @llvm.x86.invpcid(i32, ptr)
