; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-pc-windows-gnu -mattr=egpr,ndd,ccmp,avx512vl -verify-machineinstrs | FileCheck %s

define fastcc i64 @foo(i32 %dim1, i32 %dim2, i32 %dim3, i32 %dim4, ptr %p1, ptr %p2, ptr %p3, ptr %p4, ptr %p5, ptr %p6, ptr %p7, ptr %p8, ptr %p9, ptr %p10, ptr %p11, ptr %p12, ptr %p13, ptr %p14, ptr %p15, ptr %p16, ptr %p17, ptr %p18, ptr %p19, i64 %stride, i64 %extent, i64 %arg1, i1 %cond1, i1 %cond2, i64 %idx, <8 x i1> %mask1, i64 %offset, <8 x i1> %mask2) nounwind {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    pushq %r31
; CHECK-NEXT:    pushq %r30
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    pushq %rsi
; CHECK-NEXT:    pushq %rdi
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    subq $40, %rsp
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rbp
; CHECK-NEXT:    andq $-32, %rsp
; CHECK-NEXT:    movq %rsp, %rbx
; CHECK-NEXT:    movq 328(%rbp), %rax
; CHECK-NEXT:    vpmovsxwd (%rax), %ymm0
; CHECK-NEXT:    vpslld $31, %ymm0, %ymm0
; CHECK-NEXT:    vptestmd %ymm0, %ymm0, %k2
; CHECK-NEXT:    movzbl 312(%rbp), %r15d
; CHECK-NEXT:    movzbl 304(%rbp), %r12d
; CHECK-NEXT:    movq 296(%rbp), %r13
; CHECK-NEXT:    movq 288(%rbp), %r30
; CHECK-NEXT:    movq 280(%rbp), %r31
; CHECK-NEXT:    leaq 15(,%r31,4), %rdx
; CHECK-NEXT:    andq $-16, %rdx
; CHECK-NEXT:    movq %rdx, %rax
; CHECK-NEXT:    callq ___chkstk_ms
; CHECK-NEXT:    subq %rax, %rsp
; CHECK-NEXT:    andq $-32, %rsp
; CHECK-NEXT:    movq %rdx, %rax
; CHECK-NEXT:    callq ___chkstk_ms
; CHECK-NEXT:    subq %rax, %rsp
; CHECK-NEXT:    andq $-32, %rsp
; CHECK-NEXT:    movl %ecx, %edi
; CHECK-NEXT:    xorl %esi, %esi
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    kmovw %k2, 30(%rbx) # 2-byte Spill
; CHECK-NEXT:    jmp .LBB0_1
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_9: # in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    kmovw 30(%rbx), %k2 # 2-byte Reload
; CHECK-NEXT:  .LBB0_6: # %loop_outer.backedge
; CHECK-NEXT:    # in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    subq %r31, %rsi
; CHECK-NEXT:    movq %r14, %rax
; CHECK-NEXT:  .LBB0_1: # %loop_outer
; CHECK-NEXT:    # =>This Loop Header: Depth=1
; CHECK-NEXT:    # Child Loop BB0_8 Depth 2
; CHECK-NEXT:    testq %r13, %r13
; CHECK-NEXT:    ctestgq {dfv=} %r30, %r30
; CHECK-NEXT:    jns .LBB0_10
; CHECK-NEXT:  # %bb.2: # %then_branch
; CHECK-NEXT:    # in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    testb $1, %r12b
; CHECK-NEXT:    je .LBB0_3
; CHECK-NEXT:  # %bb.5: # %early_exit
; CHECK-NEXT:    # in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    decq %rax
; CHECK-NEXT:    movq %rax, %r14
; CHECK-NEXT:    jmp .LBB0_6
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_10: # %else_branch
; CHECK-NEXT:    # in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    leaq -1(%rax), %r14
; CHECK-NEXT:    testb $1, %r15b
; CHECK-NEXT:    je .LBB0_11
; CHECK-NEXT:  # %bb.7: # %memset_path
; CHECK-NEXT:    # in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    subq $32, %rsp
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    xorl %edx, %edx
; CHECK-NEXT:    movq %rdi, %r8
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    callq memset
; CHECK-NEXT:    addq $32, %rsp
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_8: # %inner_loop
; CHECK-NEXT:    # Parent Loop BB0_1 Depth=1
; CHECK-NEXT:    # => This Inner Loop Header: Depth=2
; CHECK-NEXT:    testb $1, %r12b
; CHECK-NEXT:    jne .LBB0_8
; CHECK-NEXT:    jmp .LBB0_9
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_11: # %compute_path
; CHECK-NEXT:    # in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    testb $1, %r12b
; CHECK-NEXT:    jne .LBB0_12
; CHECK-NEXT:  # %bb.14: # %loop_exit
; CHECK-NEXT:    # in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    movq 272(%rbp), %rcx
; CHECK-NEXT:    addq %rcx, %rax
; CHECK-NEXT:    andl $1, %r31d, %ecx
; CHECK-NEXT:    andl $1, %edi, %edx
; CHECK-NEXT:    movq 336(%rbp), %r8
; CHECK-NEXT:    movq 216(%rbp), %r9
; CHECK-NEXT:    vpxor %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    vmovdqu32 %ymm0, (%r9,%r8) {%k2}
; CHECK-NEXT:    vmovups %ymm0, (%rax) {%k2}
; CHECK-NEXT:    cmpl %edx, %ecx
; CHECK-NEXT:    je .LBB0_6
; CHECK-NEXT:  # %bb.15:
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:    jmp .LBB0_13
; CHECK-NEXT:  .LBB0_3: # %vector_loop.preheader
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    vpxor %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    movq 320(%rbp), %rcx
; CHECK-NEXT:    movq 256(%rbp), %rdx
; CHECK-NEXT:    movq 248(%rbp), %r19
; CHECK-NEXT:    movq 240(%rbp), %r20
; CHECK-NEXT:    movq 232(%rbp), %r8
; CHECK-NEXT:    movq 224(%rbp), %r22
; CHECK-NEXT:    movq 208(%rbp), %r9
; CHECK-NEXT:    movq 200(%rbp), %r23
; CHECK-NEXT:    movq 192(%rbp), %r10
; CHECK-NEXT:    movq 184(%rbp), %r24
; CHECK-NEXT:    movq 176(%rbp), %r11
; CHECK-NEXT:    movq 168(%rbp), %r25
; CHECK-NEXT:    movq 160(%rbp), %r16
; CHECK-NEXT:    movq 152(%rbp), %r26
; CHECK-NEXT:    movq 144(%rbp), %r17
; CHECK-NEXT:    movq 136(%rbp), %r27
; CHECK-NEXT:    movq 128(%rbp), %r18
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_4: # %vector_loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vmovdqu (%rdx), %ymm1
; CHECK-NEXT:    vpor (%r9), %ymm1, %ymm1
; CHECK-NEXT:    vmovups %ymm0, (%r24) {%k2}
; CHECK-NEXT:    vmovups %ymm0, (%r11) {%k2}
; CHECK-NEXT:    vmovups (%r25,%rsi), %ymm2
; CHECK-NEXT:    vcmpltps (%r16,%rsi), %ymm2, %k1
; CHECK-NEXT:    vptestnmd %ymm1, %ymm1, %k1 {%k1}
; CHECK-NEXT:    vmovups (%r19), %ymm1 {%k1} {z}
; CHECK-NEXT:    vmovups %ymm1, (%r10) {%k2}
; CHECK-NEXT:    vmovdqu32 %ymm0, (%r27) {%k2}
; CHECK-NEXT:    vmovdqu32 %ymm0, (%r8) {%k2}
; CHECK-NEXT:    vmovups %ymm0, (%r23) {%k2}
; CHECK-NEXT:    vmovups (%r26), %ymm1 {%k2} {z}
; CHECK-NEXT:    vmovups %ymm1, (%r22,%rcx,4) {%k2}
; CHECK-NEXT:    vmovups %ymm0, (%r20) {%k2}
; CHECK-NEXT:    vmovups %ymm0, (%r17) {%k2}
; CHECK-NEXT:    vmovups %ymm0, (%r18) {%k2}
; CHECK-NEXT:    incq %rax
; CHECK-NEXT:    addq $4, %rsi
; CHECK-NEXT:    jmp .LBB0_4
; CHECK-NEXT:  .LBB0_12:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:  .LBB0_13: # %exit
; CHECK-NEXT:    leaq 8(%rbp), %rsp
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    popq %rdi
; CHECK-NEXT:    popq %rsi
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    popq %r30
; CHECK-NEXT:    popq %r31
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
entry:
  %buf1 = alloca float, i64 %stride, align 32
  %buf2 = alloca float, i64 %stride, align 32
  %dim1_ext = zext i32 %dim1 to i64
  br label %loop_outer

loop_outer:                                      ; preds = %loop_exit, %inner_loop, %early_exit, %entry
  %iv = phi i64 [ 0, %entry ], [ %iv_dec, %early_exit ], [ %iv_dec2, %loop_exit ], [ %iv_dec2, %inner_loop ]
  %cmp1 = icmp slt i64 0, %arg1
  %cmp2 = icmp sgt i64 0, %extent
  %both = and i1 %cmp1, %cmp2
  br i1 %both, label %then_branch, label %else_branch

then_branch:                           ; preds = %loop_outer
  br i1 %cond1, label %early_exit, label %vector_loop

early_exit:                      ; preds = %then_branch
  %iv_dec = add i64 %iv, -1
  br label %loop_outer

else_branch:                            ; preds = %loop_outer
  %iv_dec2 = add i64 %iv, -1
  %gep1 = getelementptr i8, ptr %p19, i64 %iv
  br i1 %cond2, label %memset_path, label %compute_path

vector_loop:                                        ; preds = %vector_loop, %then_branch
  %inner_iv = phi i64 [ %inner_iv_next, %vector_loop ], [ 0, %then_branch ]
  %gep2 = getelementptr i32, ptr %p10, i64 %inner_iv
  %vec1 = load <8 x i32>, ptr %p17, align 1
  %vec2 = load <8 x i32>, ptr %p11, align 1
  %base_offset = mul i64 %stride, %iv
  %base1 = getelementptr i8, ptr %p5, i64 %base_offset
  %gep3 = getelementptr float, ptr %base1, i64 %inner_iv
  %base2 = getelementptr i8, ptr %p6, i64 %base_offset
  %gep4 = getelementptr float, ptr %base2, i64 %inner_iv
  call void @llvm.masked.store.v8f32.p0(<8 x float> zeroinitializer, ptr %p8, <8 x i1> %mask1)
  call void @llvm.masked.store.v8f32.p0(<8 x float> zeroinitializer, ptr %p7, <8 x i1> %mask1)
  %or_vec = or <8 x i32> %vec1, %vec2
  %cmp_vec1 = icmp eq <8 x i32> %or_vec, zeroinitializer
  %load1 = load <8 x float>, ptr %gep3, align 1
  %load2 = load <8 x float>, ptr %gep4, align 1
  %cmp_vec2 = fcmp ogt <8 x float> %load1, %load2
  %and_mask = and <8 x i1> %cmp_vec1, %cmp_vec2
  %masked_load = call <8 x float> @llvm.masked.load.v8f32.p0(ptr %p16, <8 x i1> %and_mask, <8 x float> zeroinitializer)
  call void @llvm.masked.store.v8f32.p0(<8 x float> %masked_load, ptr %p9, <8 x i1> %mask1)
  call void @llvm.masked.store.v8i32.p0(<8 x i32> zeroinitializer, ptr %p2, <8 x i1> %mask1)
  call void @llvm.masked.store.v8i32.p0(<8 x i32> zeroinitializer, ptr %p14, <8 x i1> %mask1)
  call void @llvm.masked.store.v8f32.p0(<8 x float> zeroinitializer, ptr %p10, <8 x i1> %mask1)
  %load3 = call <8 x float> @llvm.masked.load.v8f32.p0(ptr %p4, <8 x i1> %mask1, <8 x float> zeroinitializer)
  %gep5 = getelementptr float, ptr %p13, i64 %idx
  call void @llvm.masked.store.v8f32.p0(<8 x float> %load3, ptr %gep5, <8 x i1> %mask1)
  call void @llvm.masked.store.v8f32.p0(<8 x float> zeroinitializer, ptr %p15, <8 x i1> %mask1)
  call void @llvm.masked.store.v8f32.p0(<8 x float> zeroinitializer, ptr %p3, <8 x i1> %mask1)
  call void @llvm.masked.store.v8f32.p0(<8 x float> zeroinitializer, ptr %p1, <8 x i1> %mask1)
  %inner_iv_next = add i64 %inner_iv, 1
  br label %vector_loop

memset_path:                                        ; preds = %else_branch
  call void @llvm.memset.p0.i64(ptr null, i8 0, i64 %dim1_ext, i1 false)
  br label %inner_loop

inner_loop:                                        ; preds = %inner_loop, %memset_path
  br i1 %cond1, label %inner_loop, label %loop_outer

compute_path:                                        ; preds = %else_branch
  %and1 = and i64 %stride, 1
  %and2 = and i64 %dim1_ext, 1
  br i1 %cond1, label %exit, label %loop_exit

exit:                                       ; preds = %loop_exit, %compute_path
  %ret_val = phi i64 [ 1, %loop_exit ], [ 0, %compute_path ]
  ret i64 %ret_val

loop_exit:                                   ; preds = %compute_path
  %gep6 = getelementptr i8, ptr %p12, i64 %offset
  call void @llvm.masked.store.v8i32.p0(<8 x i32> zeroinitializer, ptr %gep6, <8 x i1> %mask1)
  call void @llvm.masked.store.v8f32.p0(<8 x float> zeroinitializer, ptr %gep1, <8 x i1> %mask1)
  %cmp_exit = icmp eq i64 %and1, %and2
  br i1 %cmp_exit, label %loop_outer, label %exit
}
