; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-- -mattr=ndd -verify-machineinstrs | FileCheck %s

define fastcc i64 @foo(ptr %p0, ptr %p1, i64 %p2, i64 %p3, ptr %p4, ptr %p5, ptr %p6, ptr %p7, ptr %p8, i64 %p9, i1 %cond, i32 %n) nounwind {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    subq $24, %rsp
; CHECK-NEXT:    movzbl {{[0-9]+}}(%rsp), %ebp
; CHECK-NEXT:    testb $1, %bpl
; CHECK-NEXT:    jne .LBB0_7
; CHECK-NEXT:  # %bb.2: # %bb1
; CHECK-NEXT:    jne .LBB0_7
; CHECK-NEXT:  # %bb.4: # %bb2
; CHECK-NEXT:    movb $1, %al
; CHECK-NEXT:    testb %al, %al
; CHECK-NEXT:    jne .LBB0_7
; CHECK-NEXT:  # %bb.5: # %bb2
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    testb %al, %al
; CHECK-NEXT:    jne .LBB0_9
; CHECK-NEXT:  # %bb.6: # %bb2
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    testb %al, %al
; CHECK-NEXT:  .LBB0_7: # %bb3
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:  .LBB0_8: # %bb19
; CHECK-NEXT:    addq $24, %rsp
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB0_9: # %bb5
; CHECK-NEXT:    testb $1, %bpl
; CHECK-NEXT:    jne .LBB0_7
; CHECK-NEXT:  # %bb.10: # %bb7
; CHECK-NEXT:    jne .LBB0_7
; CHECK-NEXT:  # %bb.12: # %bb9
; CHECK-NEXT:    jne .LBB0_7
; CHECK-NEXT:  # %bb.14: # %bb10
; CHECK-NEXT:    jne .LBB0_7
; CHECK-NEXT:  # %bb.16: # %bb11
; CHECK-NEXT:    jne .LBB0_7
; CHECK-NEXT:  # %bb.18: # %bb12
; CHECK-NEXT:    je .LBB0_7
; CHECK-NEXT:  # %bb.19: # %bb13
; CHECK-NEXT:    movb $1, %al
; CHECK-NEXT:    testb %al, %al
; CHECK-NEXT:    je .LBB0_7
; CHECK-NEXT:  # %bb.20: # %bb15
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    testl %eax, %eax
; CHECK-NEXT:    je .LBB0_8
; CHECK-NEXT:  # %bb.21: # %bb15
; CHECK-NEXT:    cmpl $2, %eax
; CHECK-NEXT:    je .LBB0_7
; CHECK-NEXT:  # %bb.22: # %bb18
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:    movq %rax, (%rsp) # 8-byte Spill
; CHECK-NEXT:    movb $1, %al
; CHECK-NEXT:    testb %al, %al
; CHECK-NEXT:    jne .LBB0_27
; CHECK-NEXT:  # %bb.23:
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    movq %rsi, %r12
; CHECK-NEXT:    movq %r8, %rbx
; CHECK-NEXT:    movq %r9, %r15
; CHECK-NEXT:    xorl %r13d, %r13d
; CHECK-NEXT:  .LBB0_24: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    movq %rbx, %rdi
; CHECK-NEXT:    movq %r15, %rsi
; CHECK-NEXT:    xorl %edx, %edx
; CHECK-NEXT:    callq *%r13
; CHECK-NEXT:    movq %r12, %rdi
; CHECK-NEXT:    xorl %esi, %esi
; CHECK-NEXT:    xorl %edx, %edx
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    xorl %r8d, %r8d
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %r9
; CHECK-NEXT:    pushq $0
; CHECK-NEXT:    pushq $0
; CHECK-NEXT:    pushq $0
; CHECK-NEXT:    pushq $0
; CHECK-NEXT:    callq *%r13
; CHECK-NEXT:    addq $32, %rsp
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    movq %r14, %rsi
; CHECK-NEXT:    xorl %edx, %edx
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    xorl %r8d, %r8d
; CHECK-NEXT:    xorl %r9d, %r9d
; CHECK-NEXT:    pushq $0
; CHECK-NEXT:    pushq $0
; CHECK-NEXT:    pushq $0
; CHECK-NEXT:    pushq $0
; CHECK-NEXT:    callq *%r13
; CHECK-NEXT:    addq $32, %rsp
; CHECK-NEXT:    testb $1, %bpl
; CHECK-NEXT:    je .LBB0_24
; CHECK-NEXT:  # %bb.25: # %cleanup2
; CHECK-NEXT:    jne .LBB0_27
; CHECK-NEXT:  # %bb.26: # %bb21
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    xorl %esi, %esi
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rbx # 8-byte Reload
; CHECK-NEXT:    movq %rbx, %rdx
; CHECK-NEXT:    callq memcpy@PLT
; CHECK-NEXT:    movq %rbx, (%rsp) # 8-byte Spill
; CHECK-NEXT:  .LBB0_27: # %exit
; CHECK-NEXT:    movq (%rsp), %rax # 8-byte Reload
; CHECK-NEXT:    jmp .LBB0_8
entry:
  br i1 %cond, label %cleanup, label %bb1

bb1:                                              ; preds = %entry
  br i1 %cond, label %cleanup, label %bb2

bb2:                                              ; preds = %bb1
  switch i8 0, label %bb3 [
    i8 1, label %bb5
    i8 2, label %bb4
    i8 0, label %bb6
  ]

bb3:                                              ; preds = %bb2
  ret i64 0

bb4:                                              ; preds = %bb2
  ret i64 0

bb6:                                              ; preds = %bb2
  ret i64 0

bb5:                                              ; preds = %bb2
  br i1 %cond, label %bb8, label %bb7

bb7:                                              ; preds = %bb5
  br i1 %cond, label %cleanup, label %bb9

bb8:                                              ; preds = %bb5
  ret i64 0

bb9:                                              ; preds = %bb7
  br i1 %cond, label %cleanup, label %bb10

bb10:                                             ; preds = %bb9
  br i1 %cond, label %cleanup, label %bb11

bb11:                                             ; preds = %bb10
  br i1 %cond, label %cleanup, label %bb12

bb12:                                             ; preds = %bb11
  br i1 %cond, label %bb13, label %bb14

bb13:                                             ; preds = %bb12
  %v0 = icmp eq i32 0, 0
  br i1 %v0, label %bb15, label %bb16

bb14:                                             ; preds = %bb12
  ret i64 0

bb16:                                             ; preds = %bb13
  ret i64 0

bb15:                                             ; preds = %bb13
  switch i32 %n, label %bb18 [
    i32 2, label %bb17
    i32 0, label %bb19
  ]

bb17:                                             ; preds = %bb15
  ret i64 0

bb19:                                             ; preds = %bb15
  ret i64 0

bb18:                                             ; preds = %bb15
  %v1 = icmp eq i64 0, 0
  br i1 %v1, label %exit, label %loop

exit:                                             ; preds = %bb21, %bb18, %cleanup2
  %v2 = phi i64 [ %v3, %bb21 ], [ 1, %cleanup2 ], [ 1, %bb18 ]
  call void @llvm.lifetime.end.p0(ptr poison)
  br label %cleanup

cleanup:                                          ; preds = %exit, %bb11, %bb10, %bb9, %bb7, %bb1, %entry
  %retval = phi i64 [ 0, %entry ], [ 0, %bb1 ], [ 0, %bb10 ], [ %v2, %exit ], [ 0, %bb9 ], [ 0, %bb7 ], [ 0, %bb11 ]
  ret i64 %retval

loop:                                             ; preds = %loop, %bb18
  call fastcc void null(ptr %p4, ptr %p5, i32 0)
  %v4 = call fastcc i64 null(ptr %p1, ptr null, i64 0, i64 0, i64 0, ptr %p6, ptr null, ptr null, ptr null, ptr null)
  %v5 = call fastcc i64 null(ptr null, ptr %p0, i64 0, i64 0, i64 0, ptr null, ptr null, ptr null, ptr null, ptr null)
  br i1 %cond, label %cleanup2, label %loop

cleanup2:                                         ; preds = %loop
  br i1 %cond, label %exit, label %bb21

bb21:                                             ; preds = %cleanup2
  tail call void @llvm.memcpy.p0.p0.i64(ptr null, ptr null, i64 %p2, i1 false)
  %v3 = or i64 %p2, %p3
  br label %exit
}
