; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown -mattr=-sse,+egpr | FileCheck %s

define void @x87(ptr %0, ptr %1) nounwind {
; CHECK-LABEL: x87:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq %rsi, %r16
; CHECK-NEXT:    movq %rdi, %r17
; CHECK-NEXT:    #APP
; CHECK-NEXT:    nop
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    flds (%r17)
; CHECK-NEXT:    fstps (%r16)
; CHECK-NEXT:    retq
  tail call void asm sideeffect "nop", "~{eax},~{ecx},~{edx},~{esi},~{edi},~{r8},~{r9},~{r10},~{r11}"()
  %3 = load float, ptr %0
  store float %3, ptr %1
  ret void
}

