; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-windows-msvc | FileCheck %s --check-prefix=WIN-V3-REF
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+push2pop2 | FileCheck %s --check-prefix=WIN-V3
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+push2pop2,+ppx | FileCheck %s --check-prefix=WIN-V3-PPX
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mcpu=diamondrapids | FileCheck %s --check-prefix=WIN-V3-PPX

; V3 unwind info is enabled module-wide here. diamondrapids (which enables
; EGPR) requires V3, but with V3 enabled the SEH prolog/epilogue ordering
; differs from V1, so this is split from push2-pop2-cfi-seh.ll.

define i32 @csr6_alloc16(ptr %argv) {
; WIN-V3-REF-LABEL: csr6_alloc16:
; WIN-V3-REF:       # %bb.0: # %entry
; WIN-V3-REF-NEXT:    .seh_pushreg %r15
; WIN-V3-REF-NEXT:    pushq %r15
; WIN-V3-REF-NEXT:    .seh_pushreg %r14
; WIN-V3-REF-NEXT:    pushq %r14
; WIN-V3-REF-NEXT:    .seh_pushreg %r13
; WIN-V3-REF-NEXT:    pushq %r13
; WIN-V3-REF-NEXT:    .seh_pushreg %r12
; WIN-V3-REF-NEXT:    pushq %r12
; WIN-V3-REF-NEXT:    .seh_pushreg %rbp
; WIN-V3-REF-NEXT:    pushq %rbp
; WIN-V3-REF-NEXT:    .seh_pushreg %rbx
; WIN-V3-REF-NEXT:    pushq %rbx
; WIN-V3-REF-NEXT:    .seh_stackalloc 56
; WIN-V3-REF-NEXT:    subq $56, %rsp
; WIN-V3-REF-NEXT:    .seh_endprologue
; WIN-V3-REF-NEXT:    #APP
; WIN-V3-REF-NEXT:    #NO_APP
; WIN-V3-REF-NEXT:    xorl %eax, %eax
; WIN-V3-REF-NEXT:    callq *%rax
; WIN-V3-REF-NEXT:    nop
; WIN-V3-REF-NEXT:    .seh_startepilogue
; WIN-V3-REF-NEXT:    .seh_stackalloc 56
; WIN-V3-REF-NEXT:    addq $56, %rsp
; WIN-V3-REF-NEXT:    .seh_pushreg %rbx
; WIN-V3-REF-NEXT:    popq %rbx
; WIN-V3-REF-NEXT:    .seh_pushreg %rbp
; WIN-V3-REF-NEXT:    popq %rbp
; WIN-V3-REF-NEXT:    .seh_pushreg %r12
; WIN-V3-REF-NEXT:    popq %r12
; WIN-V3-REF-NEXT:    .seh_pushreg %r13
; WIN-V3-REF-NEXT:    popq %r13
; WIN-V3-REF-NEXT:    .seh_pushreg %r14
; WIN-V3-REF-NEXT:    popq %r14
; WIN-V3-REF-NEXT:    .seh_pushreg %r15
; WIN-V3-REF-NEXT:    popq %r15
; WIN-V3-REF-NEXT:    .seh_endepilogue
; WIN-V3-REF-NEXT:    retq
; WIN-V3-REF-NEXT:    .seh_endproc
;
; WIN-V3-LABEL: csr6_alloc16:
; WIN-V3:       # %bb.0: # %entry
; WIN-V3-NEXT:    .seh_pushreg %r15
; WIN-V3-NEXT:    pushq %r15
; WIN-V3-NEXT:    .seh_push2regs %r14, %r13
; WIN-V3-NEXT:    push2 %r13, %r14
; WIN-V3-NEXT:    .seh_push2regs %r12, %rbp
; WIN-V3-NEXT:    push2 %rbp, %r12
; WIN-V3-NEXT:    .seh_pushreg %rbx
; WIN-V3-NEXT:    pushq %rbx
; WIN-V3-NEXT:    .seh_stackalloc 56
; WIN-V3-NEXT:    subq $56, %rsp
; WIN-V3-NEXT:    .seh_endprologue
; WIN-V3-NEXT:    #APP
; WIN-V3-NEXT:    #NO_APP
; WIN-V3-NEXT:    xorl %eax, %eax
; WIN-V3-NEXT:    callq *%rax
; WIN-V3-NEXT:    nop
; WIN-V3-NEXT:    .seh_startepilogue
; WIN-V3-NEXT:    .seh_stackalloc 56
; WIN-V3-NEXT:    addq $56, %rsp
; WIN-V3-NEXT:    .seh_pushreg %rbx
; WIN-V3-NEXT:    popq %rbx
; WIN-V3-NEXT:    .seh_push2regs %rbp, %r12
; WIN-V3-NEXT:    pop2 %r12, %rbp
; WIN-V3-NEXT:    .seh_push2regs %r13, %r14
; WIN-V3-NEXT:    pop2 %r14, %r13
; WIN-V3-NEXT:    .seh_pushreg %r15
; WIN-V3-NEXT:    popq %r15
; WIN-V3-NEXT:    .seh_endepilogue
; WIN-V3-NEXT:    retq
; WIN-V3-NEXT:    .seh_endproc
;
; WIN-V3-PPX-LABEL: csr6_alloc16:
; WIN-V3-PPX:       # %bb.0: # %entry
; WIN-V3-PPX-NEXT:    .seh_pushreg %r15
; WIN-V3-PPX-NEXT:    pushp %r15
; WIN-V3-PPX-NEXT:    .seh_push2regs %r14, %r13
; WIN-V3-PPX-NEXT:    push2p %r13, %r14
; WIN-V3-PPX-NEXT:    .seh_push2regs %r12, %rbp
; WIN-V3-PPX-NEXT:    push2p %rbp, %r12
; WIN-V3-PPX-NEXT:    .seh_pushreg %rbx
; WIN-V3-PPX-NEXT:    pushp %rbx
; WIN-V3-PPX-NEXT:    .seh_stackalloc 56
; WIN-V3-PPX-NEXT:    subq $56, %rsp
; WIN-V3-PPX-NEXT:    .seh_endprologue
; WIN-V3-PPX-NEXT:    #APP
; WIN-V3-PPX-NEXT:    #NO_APP
; WIN-V3-PPX-NEXT:    xorl %eax, %eax
; WIN-V3-PPX-NEXT:    callq *%rax
; WIN-V3-PPX-NEXT:    nop
; WIN-V3-PPX-NEXT:    .seh_startepilogue
; WIN-V3-PPX-NEXT:    .seh_stackalloc 56
; WIN-V3-PPX-NEXT:    addq $56, %rsp
; WIN-V3-PPX-NEXT:    .seh_pushreg %rbx
; WIN-V3-PPX-NEXT:    popp %rbx
; WIN-V3-PPX-NEXT:    .seh_push2regs %rbp, %r12
; WIN-V3-PPX-NEXT:    pop2p %r12, %rbp
; WIN-V3-PPX-NEXT:    .seh_push2regs %r13, %r14
; WIN-V3-PPX-NEXT:    pop2p %r14, %r13
; WIN-V3-PPX-NEXT:    .seh_pushreg %r15
; WIN-V3-PPX-NEXT:    popp %r15
; WIN-V3-PPX-NEXT:    .seh_endepilogue
; WIN-V3-PPX-NEXT:    retq
; WIN-V3-PPX-NEXT:    .seh_endproc
entry:
  tail call void asm sideeffect "", "~{rbp},~{r15},~{r14},~{r13},~{r12},~{rbx},~{dirflag},~{fpsr},~{flags}"()
  %a = alloca [3 x ptr], align 8
  %b = call ptr (...) null()
  ret i32 poison
}

!llvm.module.flags = !{!0}
!0 = !{i32 1, !"winx64-eh-unwind", i32 3}
