; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown -mattr=+ndd -verify-machineinstrs --show-mc-encoding | FileCheck %s --check-prefixes=CHECK,NDD
; RUN: llc < %s -mtriple=x86_64-unknown -mattr=+ndd,+prefer-ndd-mem -verify-machineinstrs --show-mc-encoding | FileCheck %s --check-prefixes=CHECK,MEM
; RUN: llc < %s -mtriple=x86_64-unknown -mattr=+ndd,nf -verify-machineinstrs --show-mc-encoding | FileCheck --check-prefix=NF %s
; RUN: llc < %s -mtriple=x86_64-unknown -mattr=+ndd,nf -x86-enable-apx-for-relocation=true -verify-machineinstrs --show-mc-encoding | FileCheck --check-prefix=NF %s

define i8 @sub8rr(i8 noundef %a, i8 noundef %b) {
; CHECK-LABEL: sub8rr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    subb %sil, %dil, %al # encoding: [0x62,0xf4,0x7c,0x18,0x28,0xf7]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub8rr:
; NF:       # %bb.0: # %entry
; NF-NEXT:    {nf} subb %sil, %dil, %al # EVEX TO EVEX Compression encoding: [0x62,0xf4,0x7c,0x1c,0x28,0xf7]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = sub i8 %a, %b
    ret i8 %sub
}

define i16 @sub16rr(i16 noundef %a, i16 noundef %b) {
; CHECK-LABEL: sub16rr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    subw %si, %di, %ax # encoding: [0x62,0xf4,0x7d,0x18,0x29,0xf7]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub16rr:
; NF:       # %bb.0: # %entry
; NF-NEXT:    {nf} subw %si, %di, %ax # EVEX TO EVEX Compression encoding: [0x62,0xf4,0x7d,0x1c,0x29,0xf7]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = sub i16 %a, %b
    ret i16 %sub
}

define i32 @sub32rr(i32 noundef %a, i32 noundef %b) {
; CHECK-LABEL: sub32rr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    subl %esi, %edi, %eax # encoding: [0x62,0xf4,0x7c,0x18,0x29,0xf7]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub32rr:
; NF:       # %bb.0: # %entry
; NF-NEXT:    {nf} subl %esi, %edi, %eax # EVEX TO EVEX Compression encoding: [0x62,0xf4,0x7c,0x1c,0x29,0xf7]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = sub i32 %a, %b
    ret i32 %sub
}

define i64 @sub64rr(i64 noundef %a, i64 noundef %b) {
; CHECK-LABEL: sub64rr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    subq %rsi, %rdi, %rax # encoding: [0x62,0xf4,0xfc,0x18,0x29,0xf7]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub64rr:
; NF:       # %bb.0: # %entry
; NF-NEXT:    {nf} subq %rsi, %rdi, %rax # EVEX TO EVEX Compression encoding: [0x62,0xf4,0xfc,0x1c,0x29,0xf7]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = sub i64 %a, %b
    ret i64 %sub
}

define i8 @sub8rm(i8 noundef %a, ptr %ptr) {
; NDD-LABEL: sub8rm:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    movl %edi, %eax # encoding: [0x89,0xf8]
; NDD-NEXT:    subb (%rsi), %al # encoding: [0x2a,0x06]
; NDD-NEXT:    # kill: def $al killed $al killed $eax
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: sub8rm:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    subb (%rsi), %dil, %al # encoding: [0x62,0xf4,0x7c,0x18,0x2a,0x3e]
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub8rm:
; NF:       # %bb.0: # %entry
; NF-NEXT:    movl %edi, %eax # encoding: [0x89,0xf8]
; NF-NEXT:    subb (%rsi), %al # encoding: [0x2a,0x06]
; NF-NEXT:    # kill: def $al killed $al killed $eax
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %b = load i8, ptr %ptr
    %sub = sub i8 %a, %b
    ret i8 %sub
}

define i16 @sub16rm(i16 noundef %a, ptr %ptr) {
; NDD-LABEL: sub16rm:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    movl %edi, %eax # encoding: [0x89,0xf8]
; NDD-NEXT:    subw (%rsi), %ax # encoding: [0x66,0x2b,0x06]
; NDD-NEXT:    # kill: def $ax killed $ax killed $eax
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: sub16rm:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    subw (%rsi), %di, %ax # encoding: [0x62,0xf4,0x7d,0x18,0x2b,0x3e]
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub16rm:
; NF:       # %bb.0: # %entry
; NF-NEXT:    movl %edi, %eax # encoding: [0x89,0xf8]
; NF-NEXT:    subw (%rsi), %ax # encoding: [0x66,0x2b,0x06]
; NF-NEXT:    # kill: def $ax killed $ax killed $eax
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %b = load i16, ptr %ptr
    %sub = sub i16 %a, %b
    ret i16 %sub
}

define i32 @sub32rm(i32 noundef %a, ptr %ptr) {
; NDD-LABEL: sub32rm:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    movl %edi, %eax # encoding: [0x89,0xf8]
; NDD-NEXT:    subl (%rsi), %eax # encoding: [0x2b,0x06]
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: sub32rm:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    subl (%rsi), %edi, %eax # encoding: [0x62,0xf4,0x7c,0x18,0x2b,0x3e]
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub32rm:
; NF:       # %bb.0: # %entry
; NF-NEXT:    movl %edi, %eax # encoding: [0x89,0xf8]
; NF-NEXT:    subl (%rsi), %eax # encoding: [0x2b,0x06]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %b = load i32, ptr %ptr
    %sub = sub i32 %a, %b
    ret i32 %sub
}

define i64 @sub64rm(i64 noundef %a, ptr %ptr) {
; NDD-LABEL: sub64rm:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    movq %rdi, %rax # encoding: [0x48,0x89,0xf8]
; NDD-NEXT:    subq (%rsi), %rax # encoding: [0x48,0x2b,0x06]
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: sub64rm:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    subq (%rsi), %rdi, %rax # encoding: [0x62,0xf4,0xfc,0x18,0x2b,0x3e]
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub64rm:
; NF:       # %bb.0: # %entry
; NF-NEXT:    movq %rdi, %rax # encoding: [0x48,0x89,0xf8]
; NF-NEXT:    subq (%rsi), %rax # encoding: [0x48,0x2b,0x06]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %b = load i64, ptr %ptr
    %sub = sub i64 %a, %b
    ret i64 %sub
}

define i16 @sub16ri8(i16 noundef %a) {
; CHECK-LABEL: sub16ri8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    subw $-128, %di, %ax # encoding: [0x62,0xf4,0x7d,0x18,0x83,0xef,0x80]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub16ri8:
; NF:       # %bb.0: # %entry
; NF-NEXT:    {nf} subw $-128, %di, %ax # EVEX TO EVEX Compression encoding: [0x62,0xf4,0x7d,0x1c,0x83,0xef,0x80]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = sub i16 %a, -128
    ret i16 %sub
}

define i32 @sub32ri8(i32 noundef %a) {
; CHECK-LABEL: sub32ri8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    subl $-128, %edi, %eax # encoding: [0x62,0xf4,0x7c,0x18,0x83,0xef,0x80]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub32ri8:
; NF:       # %bb.0: # %entry
; NF-NEXT:    {nf} subl $-128, %edi, %eax # EVEX TO EVEX Compression encoding: [0x62,0xf4,0x7c,0x1c,0x83,0xef,0x80]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = sub i32 %a, -128
    ret i32 %sub
}

define i64 @sub64ri8(i64 noundef %a) {
; CHECK-LABEL: sub64ri8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    subq $-128, %rdi, %rax # encoding: [0x62,0xf4,0xfc,0x18,0x83,0xef,0x80]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub64ri8:
; NF:       # %bb.0: # %entry
; NF-NEXT:    {nf} subq $-128, %rdi, %rax # EVEX TO EVEX Compression encoding: [0x62,0xf4,0xfc,0x1c,0x83,0xef,0x80]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = sub i64 %a, -128
    ret i64 %sub
}

define i8 @sub8ri(i8 noundef %a) {
; CHECK-LABEL: sub8ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addb $-123, %dil, %al # encoding: [0x62,0xf4,0x7c,0x18,0x80,0xc7,0x85]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub8ri:
; NF:       # %bb.0: # %entry
; NF-NEXT:    {nf} addb $-123, %dil, %al # EVEX TO EVEX Compression encoding: [0x62,0xf4,0x7c,0x1c,0x80,0xc7,0x85]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = sub i8 %a, 123
    ret i8 %sub
}

define i16 @sub16ri(i16 noundef %a) {
; CHECK-LABEL: sub16ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addw $-1234, %di, %ax # encoding: [0x62,0xf4,0x7d,0x18,0x81,0xc7,0x2e,0xfb]
; CHECK-NEXT:    # imm = 0xFB2E
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub16ri:
; NF:       # %bb.0: # %entry
; NF-NEXT:    {nf} addw $-1234, %di, %ax # EVEX TO EVEX Compression encoding: [0x62,0xf4,0x7d,0x1c,0x81,0xc7,0x2e,0xfb]
; NF-NEXT:    # imm = 0xFB2E
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = sub i16 %a, 1234
    ret i16 %sub
}

define i32 @sub32ri(i32 noundef %a) {
; CHECK-LABEL: sub32ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    leal -123456(%rdi), %eax # encoding: [0x8d,0x87,0xc0,0x1d,0xfe,0xff]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub32ri:
; NF:       # %bb.0: # %entry
; NF-NEXT:    leal -123456(%rdi), %eax # encoding: [0x8d,0x87,0xc0,0x1d,0xfe,0xff]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = sub i32 %a, 123456
    ret i32 %sub
}

define i64 @sub64ri(i64 noundef %a) {
; CHECK-LABEL: sub64ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    subq $-2147483648, %rdi, %rax # encoding: [0x62,0xf4,0xfc,0x18,0x81,0xef,0x00,0x00,0x00,0x80]
; CHECK-NEXT:    # imm = 0x80000000
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub64ri:
; NF:       # %bb.0: # %entry
; NF-NEXT:    {nf} subq $-2147483648, %rdi, %rax # EVEX TO EVEX Compression encoding: [0x62,0xf4,0xfc,0x1c,0x81,0xef,0x00,0x00,0x00,0x80]
; NF-NEXT:    # imm = 0x80000000
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = sub i64 %a, -2147483648
    ret i64 %sub
}

define i8 @sub8mr(ptr %a, i8 noundef %b) {
; NDD-LABEL: sub8mr:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    movzbl (%rdi), %eax # encoding: [0x0f,0xb6,0x07]
; NDD-NEXT:    subb %sil, %al # EVEX TO LEGACY Compression encoding: [0x40,0x28,0xf0]
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: sub8mr:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    subb %sil, (%rdi), %al # encoding: [0x62,0xf4,0x7c,0x18,0x28,0x37]
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub8mr:
; NF:       # %bb.0: # %entry
; NF-NEXT:    movzbl (%rdi), %eax # encoding: [0x0f,0xb6,0x07]
; NF-NEXT:    subb %sil, %al # EVEX TO LEGACY Compression encoding: [0x40,0x28,0xf0]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i8, ptr %a
  %sub = sub nsw i8 %t, %b
  ret i8 %sub
}

define i16 @sub16mr(ptr %a, i16 noundef %b) {
; NDD-LABEL: sub16mr:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    movzwl (%rdi), %eax # encoding: [0x0f,0xb7,0x07]
; NDD-NEXT:    subw %si, %ax # EVEX TO LEGACY Compression encoding: [0x66,0x29,0xf0]
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: sub16mr:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    subw %si, (%rdi), %ax # encoding: [0x62,0xf4,0x7d,0x18,0x29,0x37]
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub16mr:
; NF:       # %bb.0: # %entry
; NF-NEXT:    movzwl (%rdi), %eax # encoding: [0x0f,0xb7,0x07]
; NF-NEXT:    subw %si, %ax # EVEX TO LEGACY Compression encoding: [0x66,0x29,0xf0]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i16, ptr %a
  %sub = sub nsw i16 %t, %b
  ret i16 %sub
}

define i32 @sub32mr(ptr %a, i32 noundef %b) {
; NDD-LABEL: sub32mr:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    movl (%rdi), %eax # encoding: [0x8b,0x07]
; NDD-NEXT:    subl %esi, %eax # EVEX TO LEGACY Compression encoding: [0x29,0xf0]
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: sub32mr:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    subl %esi, (%rdi), %eax # encoding: [0x62,0xf4,0x7c,0x18,0x29,0x37]
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub32mr:
; NF:       # %bb.0: # %entry
; NF-NEXT:    movl (%rdi), %eax # encoding: [0x8b,0x07]
; NF-NEXT:    subl %esi, %eax # EVEX TO LEGACY Compression encoding: [0x29,0xf0]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i32, ptr %a
  %sub = sub nsw i32 %t, %b
  ret i32 %sub
}

define i64 @sub64mr(ptr %a, i64 noundef %b) {
; NDD-LABEL: sub64mr:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    movq (%rdi), %rax # encoding: [0x48,0x8b,0x07]
; NDD-NEXT:    subq %rsi, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x29,0xf0]
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: sub64mr:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    subq %rsi, (%rdi), %rax # encoding: [0x62,0xf4,0xfc,0x18,0x29,0x37]
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub64mr:
; NF:       # %bb.0: # %entry
; NF-NEXT:    movq (%rdi), %rax # encoding: [0x48,0x8b,0x07]
; NF-NEXT:    subq %rsi, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x29,0xf0]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i64, ptr %a
  %sub = sub nsw i64 %t, %b
  ret i64 %sub
}

define i16 @sub16mi8(ptr %a) {
; NDD-LABEL: sub16mi8:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    movzwl (%rdi), %eax # encoding: [0x0f,0xb7,0x07]
; NDD-NEXT:    subw $-128, %ax # EVEX TO LEGACY Compression encoding: [0x66,0x83,0xe8,0x80]
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: sub16mi8:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    subw $-128, (%rdi), %ax # encoding: [0x62,0xf4,0x7d,0x18,0x83,0x2f,0x80]
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub16mi8:
; NF:       # %bb.0: # %entry
; NF-NEXT:    movzwl (%rdi), %eax # encoding: [0x0f,0xb7,0x07]
; NF-NEXT:    subw $-128, %ax # EVEX TO LEGACY Compression encoding: [0x66,0x83,0xe8,0x80]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i16, ptr %a
  %sub = sub nsw i16 %t, -128
  ret i16 %sub
}

define i32 @sub32mi8(ptr %a) {
; NDD-LABEL: sub32mi8:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    movl (%rdi), %eax # encoding: [0x8b,0x07]
; NDD-NEXT:    subl $-128, %eax # EVEX TO LEGACY Compression encoding: [0x83,0xe8,0x80]
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: sub32mi8:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    subl $-128, (%rdi), %eax # encoding: [0x62,0xf4,0x7c,0x18,0x83,0x2f,0x80]
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub32mi8:
; NF:       # %bb.0: # %entry
; NF-NEXT:    movl (%rdi), %eax # encoding: [0x8b,0x07]
; NF-NEXT:    subl $-128, %eax # EVEX TO LEGACY Compression encoding: [0x83,0xe8,0x80]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i32, ptr %a
  %sub = sub nsw i32 %t, -128
  ret i32 %sub
}

define i64 @sub64mi8(ptr %a) {
; NDD-LABEL: sub64mi8:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    movq (%rdi), %rax # encoding: [0x48,0x8b,0x07]
; NDD-NEXT:    subq $-128, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x83,0xe8,0x80]
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: sub64mi8:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    subq $-128, (%rdi), %rax # encoding: [0x62,0xf4,0xfc,0x18,0x83,0x2f,0x80]
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub64mi8:
; NF:       # %bb.0: # %entry
; NF-NEXT:    movq (%rdi), %rax # encoding: [0x48,0x8b,0x07]
; NF-NEXT:    subq $-128, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x83,0xe8,0x80]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i64, ptr %a
  %sub = sub nsw i64 %t, -128
  ret i64 %sub
}

define i8 @sub8mi(ptr %a) {
; NDD-LABEL: sub8mi:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    movzbl (%rdi), %eax # encoding: [0x0f,0xb6,0x07]
; NDD-NEXT:    addb $-123, %al # EVEX TO LEGACY Compression encoding: [0x04,0x85]
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: sub8mi:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    addb $-123, (%rdi), %al # encoding: [0x62,0xf4,0x7c,0x18,0x80,0x07,0x85]
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub8mi:
; NF:       # %bb.0: # %entry
; NF-NEXT:    movzbl (%rdi), %eax # encoding: [0x0f,0xb6,0x07]
; NF-NEXT:    addb $-123, %al # EVEX TO LEGACY Compression encoding: [0x04,0x85]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i8, ptr %a
  %sub = sub nsw i8 %t, 123
  ret i8 %sub
}

define i16 @sub16mi(ptr %a) {
; NDD-LABEL: sub16mi:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    movzwl (%rdi), %eax # encoding: [0x0f,0xb7,0x07]
; NDD-NEXT:    addw $-1234, %ax # EVEX TO LEGACY Compression encoding: [0x66,0x05,0x2e,0xfb]
; NDD-NEXT:    # imm = 0xFB2E
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: sub16mi:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    addw $-1234, (%rdi), %ax # encoding: [0x62,0xf4,0x7d,0x18,0x81,0x07,0x2e,0xfb]
; MEM-NEXT:    # imm = 0xFB2E
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub16mi:
; NF:       # %bb.0: # %entry
; NF-NEXT:    movzwl (%rdi), %eax # encoding: [0x0f,0xb7,0x07]
; NF-NEXT:    addw $-1234, %ax # EVEX TO LEGACY Compression encoding: [0x66,0x05,0x2e,0xfb]
; NF-NEXT:    # imm = 0xFB2E
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i16, ptr %a
  %sub = sub nsw i16 %t, 1234
  ret i16 %sub
}

define i32 @sub32mi(ptr %a) {
; NDD-LABEL: sub32mi:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    movl (%rdi), %eax # encoding: [0x8b,0x07]
; NDD-NEXT:    addl $-123456, %eax # EVEX TO LEGACY Compression encoding: [0x05,0xc0,0x1d,0xfe,0xff]
; NDD-NEXT:    # imm = 0xFFFE1DC0
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: sub32mi:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    addl $-123456, (%rdi), %eax # encoding: [0x62,0xf4,0x7c,0x18,0x81,0x07,0xc0,0x1d,0xfe,0xff]
; MEM-NEXT:    # imm = 0xFFFE1DC0
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub32mi:
; NF:       # %bb.0: # %entry
; NF-NEXT:    movl (%rdi), %eax # encoding: [0x8b,0x07]
; NF-NEXT:    addl $-123456, %eax # EVEX TO LEGACY Compression encoding: [0x05,0xc0,0x1d,0xfe,0xff]
; NF-NEXT:    # imm = 0xFFFE1DC0
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i32, ptr %a
  %sub = sub nsw i32 %t, 123456
  ret i32 %sub
}

define i64 @sub64mi(ptr %a) {
; NDD-LABEL: sub64mi:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    movq (%rdi), %rax # encoding: [0x48,0x8b,0x07]
; NDD-NEXT:    subq $-2147483648, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x2d,0x00,0x00,0x00,0x80]
; NDD-NEXT:    # imm = 0x80000000
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: sub64mi:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    subq $-2147483648, (%rdi), %rax # encoding: [0x62,0xf4,0xfc,0x18,0x81,0x2f,0x00,0x00,0x00,0x80]
; MEM-NEXT:    # imm = 0x80000000
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub64mi:
; NF:       # %bb.0: # %entry
; NF-NEXT:    movq (%rdi), %rax # encoding: [0x48,0x8b,0x07]
; NF-NEXT:    subq $-2147483648, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x2d,0x00,0x00,0x00,0x80]
; NF-NEXT:    # imm = 0x80000000
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i64, ptr %a
  %sub = sub nsw i64 %t, -2147483648
  ret i64 %sub
}

declare i8 @llvm.usub.sat.i8(i8, i8)
declare i16 @llvm.usub.sat.i16(i16, i16)
declare i32 @llvm.usub.sat.i32(i32, i32)
declare i64 @llvm.usub.sat.i64(i64, i64)

define i8 @subflag8rr(i8 noundef %a, i8 noundef %b) {
; CHECK-LABEL: subflag8rr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; CHECK-NEXT:    subb %sil, %dil, %cl # encoding: [0x62,0xf4,0x74,0x18,0x28,0xf7]
; CHECK-NEXT:    movzbl %cl, %ecx # encoding: [0x0f,0xb6,0xc9]
; CHECK-NEXT:    cmovael %ecx, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc1]
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: subflag8rr:
; NF:       # %bb.0: # %entry
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    subb %sil, %dil, %cl # encoding: [0x62,0xf4,0x74,0x18,0x28,0xf7]
; NF-NEXT:    movzbl %cl, %ecx # encoding: [0x0f,0xb6,0xc9]
; NF-NEXT:    cmovael %ecx, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc1]
; NF-NEXT:    # kill: def $al killed $al killed $eax
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = call i8 @llvm.usub.sat.i8(i8 %a, i8 %b)
    ret i8 %sub
}

define i16 @subflag16rr(i16 noundef %a, i16 noundef %b) {
; CHECK-LABEL: subflag16rr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; CHECK-NEXT:    subw %si, %di # EVEX TO LEGACY Compression encoding: [0x66,0x29,0xf7]
; CHECK-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: subflag16rr:
; NF:       # %bb.0: # %entry
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    subw %si, %di # EVEX TO LEGACY Compression encoding: [0x66,0x29,0xf7]
; NF-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; NF-NEXT:    # kill: def $ax killed $ax killed $eax
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = call i16 @llvm.usub.sat.i16(i16 %a, i16 %b)
    ret i16 %sub
}

define i32 @subflag32rr(i32 noundef %a, i32 noundef %b) {
; CHECK-LABEL: subflag32rr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; CHECK-NEXT:    subl %esi, %edi # EVEX TO LEGACY Compression encoding: [0x29,0xf7]
; CHECK-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: subflag32rr:
; NF:       # %bb.0: # %entry
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    subl %esi, %edi # EVEX TO LEGACY Compression encoding: [0x29,0xf7]
; NF-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = call i32 @llvm.usub.sat.i32(i32 %a, i32 %b)
    ret i32 %sub
}

define i64 @subflag64rr(i64 noundef %a, i64 noundef %b) {
; CHECK-LABEL: subflag64rr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; CHECK-NEXT:    subq %rsi, %rdi # EVEX TO LEGACY Compression encoding: [0x48,0x29,0xf7]
; CHECK-NEXT:    cmovaeq %rdi, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x0f,0x43,0xc7]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: subflag64rr:
; NF:       # %bb.0: # %entry
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    subq %rsi, %rdi # EVEX TO LEGACY Compression encoding: [0x48,0x29,0xf7]
; NF-NEXT:    cmovaeq %rdi, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x0f,0x43,0xc7]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = call i64 @llvm.usub.sat.i64(i64 %a, i64 %b)
    ret i64 %sub
}

define i8 @subflag8rm(i8 noundef %a, ptr %b) {
; NDD-LABEL: subflag8rm:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NDD-NEXT:    subb (%rsi), %dil # encoding: [0x40,0x2a,0x3e]
; NDD-NEXT:    movzbl %dil, %ecx # encoding: [0x40,0x0f,0xb6,0xcf]
; NDD-NEXT:    cmovael %ecx, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc1]
; NDD-NEXT:    # kill: def $al killed $al killed $eax
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: subflag8rm:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; MEM-NEXT:    subb (%rsi), %dil, %cl # encoding: [0x62,0xf4,0x74,0x18,0x2a,0x3e]
; MEM-NEXT:    movzbl %cl, %ecx # encoding: [0x0f,0xb6,0xc9]
; MEM-NEXT:    cmovael %ecx, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc1]
; MEM-NEXT:    # kill: def $al killed $al killed $eax
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: subflag8rm:
; NF:       # %bb.0: # %entry
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    subb (%rsi), %dil # encoding: [0x40,0x2a,0x3e]
; NF-NEXT:    movzbl %dil, %ecx # encoding: [0x40,0x0f,0xb6,0xcf]
; NF-NEXT:    cmovael %ecx, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc1]
; NF-NEXT:    # kill: def $al killed $al killed $eax
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %t = load i8, ptr %b
    %sub = call i8 @llvm.usub.sat.i8(i8 %a, i8 %t)
    ret i8 %sub
}

define i16 @subflag16rm(i16 noundef %a, ptr %b) {
; NDD-LABEL: subflag16rm:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NDD-NEXT:    subw (%rsi), %di # encoding: [0x66,0x2b,0x3e]
; NDD-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; NDD-NEXT:    # kill: def $ax killed $ax killed $eax
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: subflag16rm:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; MEM-NEXT:    subw (%rsi), %di # EVEX TO LEGACY Compression encoding: [0x66,0x2b,0x3e]
; MEM-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; MEM-NEXT:    # kill: def $ax killed $ax killed $eax
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: subflag16rm:
; NF:       # %bb.0: # %entry
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    subw (%rsi), %di # encoding: [0x66,0x2b,0x3e]
; NF-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; NF-NEXT:    # kill: def $ax killed $ax killed $eax
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %t = load i16, ptr %b
    %sub = call i16 @llvm.usub.sat.i16(i16 %a, i16 %t)
    ret i16 %sub
}

define i32 @subflag32rm(i32 noundef %a, ptr %b) {
; NDD-LABEL: subflag32rm:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NDD-NEXT:    subl (%rsi), %edi # encoding: [0x2b,0x3e]
; NDD-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: subflag32rm:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; MEM-NEXT:    subl (%rsi), %edi # EVEX TO LEGACY Compression encoding: [0x2b,0x3e]
; MEM-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: subflag32rm:
; NF:       # %bb.0: # %entry
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    subl (%rsi), %edi # encoding: [0x2b,0x3e]
; NF-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %t = load i32, ptr %b
    %sub = call i32 @llvm.usub.sat.i32(i32 %a, i32 %t)
    ret i32 %sub
}

define i64 @subflag64rm(i64 noundef %a, ptr %b) {
; NDD-LABEL: subflag64rm:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NDD-NEXT:    subq (%rsi), %rdi # encoding: [0x48,0x2b,0x3e]
; NDD-NEXT:    cmovaeq %rdi, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x0f,0x43,0xc7]
; NDD-NEXT:    retq # encoding: [0xc3]
;
; MEM-LABEL: subflag64rm:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; MEM-NEXT:    subq (%rsi), %rdi # EVEX TO LEGACY Compression encoding: [0x48,0x2b,0x3e]
; MEM-NEXT:    cmovaeq %rdi, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x0f,0x43,0xc7]
; MEM-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: subflag64rm:
; NF:       # %bb.0: # %entry
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    subq (%rsi), %rdi # encoding: [0x48,0x2b,0x3e]
; NF-NEXT:    cmovaeq %rdi, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x0f,0x43,0xc7]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %t = load i64, ptr %b
    %sub = call i64 @llvm.usub.sat.i64(i64 %a, i64 %t)
    ret i64 %sub
}

define i16 @subflag16ri8(i16 noundef %a) {
; CHECK-LABEL: subflag16ri8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; CHECK-NEXT:    subw $123, %di # EVEX TO LEGACY Compression encoding: [0x66,0x83,0xef,0x7b]
; CHECK-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: subflag16ri8:
; NF:       # %bb.0: # %entry
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    subw $123, %di # EVEX TO LEGACY Compression encoding: [0x66,0x83,0xef,0x7b]
; NF-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; NF-NEXT:    # kill: def $ax killed $ax killed $eax
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = call i16 @llvm.usub.sat.i16(i16 %a, i16 123)
    ret i16 %sub
}

define i32 @subflag32ri8(i32 noundef %a) {
; CHECK-LABEL: subflag32ri8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; CHECK-NEXT:    subl $123, %edi # EVEX TO LEGACY Compression encoding: [0x83,0xef,0x7b]
; CHECK-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: subflag32ri8:
; NF:       # %bb.0: # %entry
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    subl $123, %edi # EVEX TO LEGACY Compression encoding: [0x83,0xef,0x7b]
; NF-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = call i32 @llvm.usub.sat.i32(i32 %a, i32 123)
    ret i32 %sub
}

define i64 @subflag64ri8(i64 noundef %a) {
; CHECK-LABEL: subflag64ri8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; CHECK-NEXT:    subq $123, %rdi # EVEX TO LEGACY Compression encoding: [0x48,0x83,0xef,0x7b]
; CHECK-NEXT:    cmovaeq %rdi, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x0f,0x43,0xc7]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: subflag64ri8:
; NF:       # %bb.0: # %entry
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    subq $123, %rdi # EVEX TO LEGACY Compression encoding: [0x48,0x83,0xef,0x7b]
; NF-NEXT:    cmovaeq %rdi, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x0f,0x43,0xc7]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = call i64 @llvm.usub.sat.i64(i64 %a, i64 123)
    ret i64 %sub
}

define i8 @subflag8ri(i8 noundef %a) {
; CHECK-LABEL: subflag8ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; CHECK-NEXT:    subb $123, %dil, %cl # encoding: [0x62,0xf4,0x74,0x18,0x80,0xef,0x7b]
; CHECK-NEXT:    movzbl %cl, %ecx # encoding: [0x0f,0xb6,0xc9]
; CHECK-NEXT:    cmovael %ecx, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc1]
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: subflag8ri:
; NF:       # %bb.0: # %entry
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    subb $123, %dil, %cl # encoding: [0x62,0xf4,0x74,0x18,0x80,0xef,0x7b]
; NF-NEXT:    movzbl %cl, %ecx # encoding: [0x0f,0xb6,0xc9]
; NF-NEXT:    cmovael %ecx, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc1]
; NF-NEXT:    # kill: def $al killed $al killed $eax
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = call i8 @llvm.usub.sat.i8(i8 %a, i8 123)
    ret i8 %sub
}

define i16 @subflag16ri(i16 noundef %a) {
; CHECK-LABEL: subflag16ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; CHECK-NEXT:    subw $1234, %di # EVEX TO LEGACY Compression encoding: [0x66,0x81,0xef,0xd2,0x04]
; CHECK-NEXT:    # imm = 0x4D2
; CHECK-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: subflag16ri:
; NF:       # %bb.0: # %entry
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    subw $1234, %di # EVEX TO LEGACY Compression encoding: [0x66,0x81,0xef,0xd2,0x04]
; NF-NEXT:    # imm = 0x4D2
; NF-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; NF-NEXT:    # kill: def $ax killed $ax killed $eax
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = call i16 @llvm.usub.sat.i16(i16 %a, i16 1234)
    ret i16 %sub
}

define i32 @subflag32ri(i32 noundef %a) {
; CHECK-LABEL: subflag32ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; CHECK-NEXT:    subl $123456, %edi # EVEX TO LEGACY Compression encoding: [0x81,0xef,0x40,0xe2,0x01,0x00]
; CHECK-NEXT:    # imm = 0x1E240
; CHECK-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: subflag32ri:
; NF:       # %bb.0: # %entry
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    subl $123456, %edi # EVEX TO LEGACY Compression encoding: [0x81,0xef,0x40,0xe2,0x01,0x00]
; NF-NEXT:    # imm = 0x1E240
; NF-NEXT:    cmovael %edi, %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x43,0xc7]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = call i32 @llvm.usub.sat.i32(i32 %a, i32 123456)
    ret i32 %sub
}

define i64 @subflag64ri(i64 noundef %a) {
; CHECK-LABEL: subflag64ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; CHECK-NEXT:    subq $123456, %rdi # EVEX TO LEGACY Compression encoding: [0x48,0x81,0xef,0x40,0xe2,0x01,0x00]
; CHECK-NEXT:    # imm = 0x1E240
; CHECK-NEXT:    cmovaeq %rdi, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x0f,0x43,0xc7]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: subflag64ri:
; NF:       # %bb.0: # %entry
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    subq $123456, %rdi # EVEX TO LEGACY Compression encoding: [0x48,0x81,0xef,0x40,0xe2,0x01,0x00]
; NF-NEXT:    # imm = 0x1E240
; NF-NEXT:    cmovaeq %rdi, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x0f,0x43,0xc7]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
    %sub = call i64 @llvm.usub.sat.i64(i64 %a, i64 123456)
    ret i64 %sub
}

@val = external hidden global i8

declare void @f()

define void @sub64ri_reloc(i64 %val) {
; CHECK-LABEL: sub64ri_reloc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmpq $val, %rdi # encoding: [0x48,0x81,0xff,A,A,A,A]
; CHECK-NEXT:    # fixup A - offset: 3, value: val, kind: reloc_signed_4byte
; CHECK-NEXT:    jbe .LBB41_2 # encoding: [0x76,A]
; CHECK-NEXT:    # fixup A - offset: 1, value: .LBB41_2, kind: FK_PCRel_1
; CHECK-NEXT:  # %bb.1: # %t
; CHECK-NEXT:    pushq %rax # encoding: [0x50]
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    callq f@PLT # encoding: [0xe8,A,A,A,A]
; CHECK-NEXT:    # fixup A - offset: 1, value: f@PLT, kind: FK_PCRel_4
; CHECK-NEXT:    popq %rax # encoding: [0x58]
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:  .LBB41_2: # %f
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub64ri_reloc:
; NF:       # %bb.0:
; NF-NEXT:    cmpq $val, %rdi # encoding: [0x48,0x81,0xff,A,A,A,A]
; NF-NEXT:    # fixup A - offset: 3, value: val, kind: reloc_signed_4byte
; NF-NEXT:    jbe .LBB41_2 # encoding: [0x76,A]
; NF-NEXT:    # fixup A - offset: 1, value: .LBB41_2, kind: FK_PCRel_1
; NF-NEXT:  # %bb.1: # %t
; NF-NEXT:    pushq %rax # encoding: [0x50]
; NF-NEXT:    .cfi_def_cfa_offset 16
; NF-NEXT:    callq f@PLT # encoding: [0xe8,A,A,A,A]
; NF-NEXT:    # fixup A - offset: 1, value: f@PLT, kind: FK_PCRel_4
; NF-NEXT:    popq %rax # encoding: [0x58]
; NF-NEXT:    .cfi_def_cfa_offset 8
; NF-NEXT:  .LBB41_2: # %f
; NF-NEXT:    retq # encoding: [0xc3]
  %cmp = icmp ugt i64 %val, ptrtoint (ptr @val to i64)
  br i1 %cmp, label %t, label %f

t:
  call void @f()
  ret void

f:
  ret void
}

define void @sub8mr_legacy(ptr %a, i8 noundef %b) {
; CHECK-LABEL: sub8mr_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    subb %sil, (%rdi) # encoding: [0x40,0x28,0x37]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub8mr_legacy:
; NF:       # %bb.0: # %entry
; NF-NEXT:    subb %sil, (%rdi) # encoding: [0x40,0x28,0x37]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i8, ptr %a
  %sub = sub i8 %t, %b
  store i8 %sub, ptr %a
  ret void
}

define void @sub16mr_legacy(ptr %a, i16 noundef %b) {
; CHECK-LABEL: sub16mr_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    subw %si, (%rdi) # encoding: [0x66,0x29,0x37]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub16mr_legacy:
; NF:       # %bb.0: # %entry
; NF-NEXT:    subw %si, (%rdi) # encoding: [0x66,0x29,0x37]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i16, ptr %a
  %sub = sub i16 %t, %b
  store i16 %sub, ptr %a
  ret void
}

define void @sub32mr_legacy(ptr %a, i32 noundef %b) {
; CHECK-LABEL: sub32mr_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    subl %esi, (%rdi) # encoding: [0x29,0x37]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub32mr_legacy:
; NF:       # %bb.0: # %entry
; NF-NEXT:    subl %esi, (%rdi) # encoding: [0x29,0x37]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i32, ptr %a
  %sub = sub i32 %t, %b
  store i32 %sub, ptr %a
  ret void
}

define void @sub64mr_legacy(ptr %a, i64 noundef %b) {
; CHECK-LABEL: sub64mr_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    subq %rsi, (%rdi) # encoding: [0x48,0x29,0x37]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub64mr_legacy:
; NF:       # %bb.0: # %entry
; NF-NEXT:    subq %rsi, (%rdi) # encoding: [0x48,0x29,0x37]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i64, ptr %a
  %sub = sub i64 %t, %b
  store i64 %sub, ptr %a
  ret void
}

define void @sub8mi_legacy(ptr %a) {
; CHECK-LABEL: sub8mi_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addb $-123, (%rdi) # encoding: [0x80,0x07,0x85]
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub8mi_legacy:
; NF:       # %bb.0: # %entry
; NF-NEXT:    addb $-123, (%rdi) # encoding: [0x80,0x07,0x85]
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i8, ptr %a
  %sub = sub nsw i8 %t, 123
  store i8 %sub, ptr %a
  ret void
}

define void @sub16mi_legacy(ptr %a) {
; CHECK-LABEL: sub16mi_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addw $-1234, (%rdi) # encoding: [0x66,0x81,0x07,0x2e,0xfb]
; CHECK-NEXT:    # imm = 0xFB2E
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub16mi_legacy:
; NF:       # %bb.0: # %entry
; NF-NEXT:    addw $-1234, (%rdi) # encoding: [0x66,0x81,0x07,0x2e,0xfb]
; NF-NEXT:    # imm = 0xFB2E
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i16, ptr %a
  %sub = sub nsw i16 %t, 1234
  store i16 %sub, ptr %a
  ret void
}

define void @sub32mi_legacy(ptr %a) {
; CHECK-LABEL: sub32mi_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addl $-123456, (%rdi) # encoding: [0x81,0x07,0xc0,0x1d,0xfe,0xff]
; CHECK-NEXT:    # imm = 0xFFFE1DC0
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub32mi_legacy:
; NF:       # %bb.0: # %entry
; NF-NEXT:    addl $-123456, (%rdi) # encoding: [0x81,0x07,0xc0,0x1d,0xfe,0xff]
; NF-NEXT:    # imm = 0xFFFE1DC0
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i32, ptr %a
  %sub = sub nsw i32 %t, 123456
  store i32 %sub, ptr %a
  ret void
}

define void @sub64mi_legacy(ptr %a) {
; CHECK-LABEL: sub64mi_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addq $-123456, (%rdi) # encoding: [0x48,0x81,0x07,0xc0,0x1d,0xfe,0xff]
; CHECK-NEXT:    # imm = 0xFFFE1DC0
; CHECK-NEXT:    retq # encoding: [0xc3]
;
; NF-LABEL: sub64mi_legacy:
; NF:       # %bb.0: # %entry
; NF-NEXT:    addq $-123456, (%rdi) # encoding: [0x48,0x81,0x07,0xc0,0x1d,0xfe,0xff]
; NF-NEXT:    # imm = 0xFFFE1DC0
; NF-NEXT:    retq # encoding: [0xc3]
entry:
  %t= load i64, ptr %a
  %sub = sub nsw i64 %t, 123456
  store i64 %sub, ptr %a
  ret void
}

define fastcc void @fold_with_physical_reg(ptr %arg0, i64 %arg1, ptr %arg2, i1 %arg3) nounwind {
; NDD-LABEL: fold_with_physical_reg:
; NDD:       # %bb.0: # %entry
; NDD-NEXT:    pushq %rbp # encoding: [0x55]
; NDD-NEXT:    movq %rsp, %rbp # encoding: [0x48,0x89,0xe5]
; NDD-NEXT:    pushq %r15 # encoding: [0x41,0x57]
; NDD-NEXT:    pushq %r14 # encoding: [0x41,0x56]
; NDD-NEXT:    pushq %r13 # encoding: [0x41,0x55]
; NDD-NEXT:    pushq %r12 # encoding: [0x41,0x54]
; NDD-NEXT:    pushq %rbx # encoding: [0x53]
; NDD-NEXT:    subq $24, %rsp # encoding: [0x48,0x83,0xec,0x18]
; NDD-NEXT:    movl %ecx, %r14d # encoding: [0x41,0x89,0xce]
; NDD-NEXT:    movq %rdx, %rbx # encoding: [0x48,0x89,0xd3]
; NDD-NEXT:    movq %rsi, %r12 # encoding: [0x49,0x89,0xf4]
; NDD-NEXT:    movq %rdi, %r13 # encoding: [0x49,0x89,0xfd]
; NDD-NEXT:    leaq 15(%rsi), %rax # encoding: [0x48,0x8d,0x46,0x0f]
; NDD-NEXT:    andq $-16, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x83,0xe0,0xf0]
; NDD-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; NDD-NEXT:    # encoding: [0x48,0x89,0x45,0xd0]
; NDD-NEXT:    .p2align 4
; NDD-NEXT:  .LBB50_1: # %bb1
; NDD-NEXT:    # =>This Loop Header: Depth=1
; NDD-NEXT:    # Child Loop BB50_2 Depth 2
; NDD-NEXT:    movq %rsp, %rax # encoding: [0x48,0x89,0xe0]
; NDD-NEXT:    subq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Folded Reload
; NDD-NEXT:    # encoding: [0x48,0x2b,0x45,0xd0]
; NDD-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; NDD-NEXT:    # encoding: [0x48,0x89,0x45,0xc8]
; NDD-NEXT:    movq %rax, %rsp # encoding: [0x48,0x89,0xc4]
; NDD-NEXT:    xorl %r15d, %r15d # encoding: [0x45,0x31,0xff]
; NDD-NEXT:    .p2align 4
; NDD-NEXT:  .LBB50_2: # %bb2
; NDD-NEXT:    # Parent Loop BB50_1 Depth=1
; NDD-NEXT:    # => This Inner Loop Header: Depth=2
; NDD-NEXT:    xorps %xmm0, %xmm0 # encoding: [0x0f,0x57,0xc0]
; NDD-NEXT:    movq %r13, %rdi # encoding: [0x4c,0x89,0xef]
; NDD-NEXT:    xorl %esi, %esi # encoding: [0x31,0xf6]
; NDD-NEXT:    xorl %edx, %edx # encoding: [0x31,0xd2]
; NDD-NEXT:    xorl %ecx, %ecx # encoding: [0x31,0xc9]
; NDD-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NDD-NEXT:    callq *%rax # encoding: [0xff,0xd0]
; NDD-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; NDD-NEXT:    # encoding: [0x48,0x8b,0x45,0xc8]
; NDD-NEXT:    movq $0, (%rax,%r15,8) # encoding: [0x4a,0xc7,0x04,0xf8,0x00,0x00,0x00,0x00]
; NDD-NEXT:    movq $0, (%rbx) # encoding: [0x48,0xc7,0x03,0x00,0x00,0x00,0x00]
; NDD-NEXT:    testb $1, %r14b # encoding: [0x41,0xf6,0xc6,0x01]
; NDD-NEXT:    movq %r12, %r15 # encoding: [0x4d,0x89,0xe7]
; NDD-NEXT:    je .LBB50_2 # encoding: [0x74,A]
; NDD-NEXT:    # fixup A - offset: 1, value: .LBB50_2, kind: FK_PCRel_1
; NDD-NEXT:    jmp .LBB50_1 # encoding: [0xeb,A]
; NDD-NEXT:    # fixup A - offset: 1, value: .LBB50_1, kind: FK_PCRel_1
;
; MEM-LABEL: fold_with_physical_reg:
; MEM:       # %bb.0: # %entry
; MEM-NEXT:    pushq %rbp # encoding: [0x55]
; MEM-NEXT:    movq %rsp, %rbp # encoding: [0x48,0x89,0xe5]
; MEM-NEXT:    pushq %r15 # encoding: [0x41,0x57]
; MEM-NEXT:    pushq %r14 # encoding: [0x41,0x56]
; MEM-NEXT:    pushq %r13 # encoding: [0x41,0x55]
; MEM-NEXT:    pushq %r12 # encoding: [0x41,0x54]
; MEM-NEXT:    pushq %rbx # encoding: [0x53]
; MEM-NEXT:    subq $24, %rsp # encoding: [0x48,0x83,0xec,0x18]
; MEM-NEXT:    movl %ecx, %r14d # encoding: [0x41,0x89,0xce]
; MEM-NEXT:    movq %rdx, %rbx # encoding: [0x48,0x89,0xd3]
; MEM-NEXT:    movq %rsi, %r12 # encoding: [0x49,0x89,0xf4]
; MEM-NEXT:    movq %rdi, %r13 # encoding: [0x49,0x89,0xfd]
; MEM-NEXT:    leaq 15(%rsi), %rax # encoding: [0x48,0x8d,0x46,0x0f]
; MEM-NEXT:    andq $-16, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x83,0xe0,0xf0]
; MEM-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; MEM-NEXT:    # encoding: [0x48,0x89,0x45,0xd0]
; MEM-NEXT:    .p2align 4
; MEM-NEXT:  .LBB50_1: # %bb1
; MEM-NEXT:    # =>This Loop Header: Depth=1
; MEM-NEXT:    # Child Loop BB50_2 Depth 2
; MEM-NEXT:    subq {{[-0-9]+}}(%r{{[sb]}}p), %rsp, %rax # 8-byte Folded Reload
; MEM-NEXT:    # encoding: [0x62,0xf4,0xfc,0x18,0x2b,0x65,0xd0]
; MEM-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; MEM-NEXT:    # encoding: [0x48,0x89,0x45,0xc8]
; MEM-NEXT:    movq %rax, %rsp # encoding: [0x48,0x89,0xc4]
; MEM-NEXT:    xorl %r15d, %r15d # encoding: [0x45,0x31,0xff]
; MEM-NEXT:    .p2align 4
; MEM-NEXT:  .LBB50_2: # %bb2
; MEM-NEXT:    # Parent Loop BB50_1 Depth=1
; MEM-NEXT:    # => This Inner Loop Header: Depth=2
; MEM-NEXT:    xorps %xmm0, %xmm0 # encoding: [0x0f,0x57,0xc0]
; MEM-NEXT:    movq %r13, %rdi # encoding: [0x4c,0x89,0xef]
; MEM-NEXT:    xorl %esi, %esi # encoding: [0x31,0xf6]
; MEM-NEXT:    xorl %edx, %edx # encoding: [0x31,0xd2]
; MEM-NEXT:    xorl %ecx, %ecx # encoding: [0x31,0xc9]
; MEM-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; MEM-NEXT:    callq *%rax # encoding: [0xff,0xd0]
; MEM-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; MEM-NEXT:    # encoding: [0x48,0x8b,0x45,0xc8]
; MEM-NEXT:    movq $0, (%rax,%r15,8) # encoding: [0x4a,0xc7,0x04,0xf8,0x00,0x00,0x00,0x00]
; MEM-NEXT:    movq $0, (%rbx) # encoding: [0x48,0xc7,0x03,0x00,0x00,0x00,0x00]
; MEM-NEXT:    testb $1, %r14b # encoding: [0x41,0xf6,0xc6,0x01]
; MEM-NEXT:    movq %r12, %r15 # encoding: [0x4d,0x89,0xe7]
; MEM-NEXT:    je .LBB50_2 # encoding: [0x74,A]
; MEM-NEXT:    # fixup A - offset: 1, value: .LBB50_2, kind: FK_PCRel_1
; MEM-NEXT:    jmp .LBB50_1 # encoding: [0xeb,A]
; MEM-NEXT:    # fixup A - offset: 1, value: .LBB50_1, kind: FK_PCRel_1
;
; NF-LABEL: fold_with_physical_reg:
; NF:       # %bb.0: # %entry
; NF-NEXT:    pushq %rbp # encoding: [0x55]
; NF-NEXT:    movq %rsp, %rbp # encoding: [0x48,0x89,0xe5]
; NF-NEXT:    pushq %r15 # encoding: [0x41,0x57]
; NF-NEXT:    pushq %r14 # encoding: [0x41,0x56]
; NF-NEXT:    pushq %r13 # encoding: [0x41,0x55]
; NF-NEXT:    pushq %r12 # encoding: [0x41,0x54]
; NF-NEXT:    pushq %rbx # encoding: [0x53]
; NF-NEXT:    {nf} subq $24, %rsp # encoding: [0x62,0xf4,0xfc,0x0c,0x83,0xec,0x18]
; NF-NEXT:    movl %ecx, %r14d # encoding: [0x41,0x89,0xce]
; NF-NEXT:    movq %rdx, %rbx # encoding: [0x48,0x89,0xd3]
; NF-NEXT:    movq %rsi, %r12 # encoding: [0x49,0x89,0xf4]
; NF-NEXT:    movq %rdi, %r13 # encoding: [0x49,0x89,0xfd]
; NF-NEXT:    leaq 15(%rsi), %rax # encoding: [0x48,0x8d,0x46,0x0f]
; NF-NEXT:    andq $-16, %rax # EVEX TO LEGACY Compression encoding: [0x48,0x83,0xe0,0xf0]
; NF-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; NF-NEXT:    # encoding: [0x48,0x89,0x45,0xd0]
; NF-NEXT:    .p2align 4
; NF-NEXT:  .LBB50_1: # %bb1
; NF-NEXT:    # =>This Loop Header: Depth=1
; NF-NEXT:    # Child Loop BB50_2 Depth 2
; NF-NEXT:    movq %rsp, %rax # encoding: [0x48,0x89,0xe0]
; NF-NEXT:    subq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Folded Reload
; NF-NEXT:    # encoding: [0x48,0x2b,0x45,0xd0]
; NF-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; NF-NEXT:    # encoding: [0x48,0x89,0x45,0xc8]
; NF-NEXT:    movq %rax, %rsp # encoding: [0x48,0x89,0xc4]
; NF-NEXT:    xorl %r15d, %r15d # encoding: [0x45,0x31,0xff]
; NF-NEXT:    .p2align 4
; NF-NEXT:  .LBB50_2: # %bb2
; NF-NEXT:    # Parent Loop BB50_1 Depth=1
; NF-NEXT:    # => This Inner Loop Header: Depth=2
; NF-NEXT:    xorps %xmm0, %xmm0 # encoding: [0x0f,0x57,0xc0]
; NF-NEXT:    movq %r13, %rdi # encoding: [0x4c,0x89,0xef]
; NF-NEXT:    xorl %esi, %esi # encoding: [0x31,0xf6]
; NF-NEXT:    xorl %edx, %edx # encoding: [0x31,0xd2]
; NF-NEXT:    xorl %ecx, %ecx # encoding: [0x31,0xc9]
; NF-NEXT:    xorl %eax, %eax # encoding: [0x31,0xc0]
; NF-NEXT:    callq *%rax # encoding: [0xff,0xd0]
; NF-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; NF-NEXT:    # encoding: [0x48,0x8b,0x45,0xc8]
; NF-NEXT:    movq $0, (%rax,%r15,8) # encoding: [0x4a,0xc7,0x04,0xf8,0x00,0x00,0x00,0x00]
; NF-NEXT:    movq $0, (%rbx) # encoding: [0x48,0xc7,0x03,0x00,0x00,0x00,0x00]
; NF-NEXT:    testb $1, %r14b # encoding: [0x41,0xf6,0xc6,0x01]
; NF-NEXT:    movq %r12, %r15 # encoding: [0x4d,0x89,0xe7]
; NF-NEXT:    je .LBB50_2 # encoding: [0x74,A]
; NF-NEXT:    # fixup A - offset: 1, value: .LBB50_2, kind: FK_PCRel_1
; NF-NEXT:    jmp .LBB50_1 # encoding: [0xeb,A]
; NF-NEXT:    # fixup A - offset: 1, value: .LBB50_1, kind: FK_PCRel_1
entry:
  br label %bb1

bb1:                                              ; preds = %bb2, %entry
  %alloc = alloca i8, i64 %arg1, align 16
  br label %bb2

bb2:                                              ; preds = %bb2, %bb1
  %phi = phi i64 [ 0, %bb1 ], [ %arg1, %bb2 ]
  %call = call fastcc ptr null(ptr %arg0, ptr null, ptr null, ptr null, float 0.000000e+00)
  %gep = getelementptr ptr, ptr %alloc, i64 %phi
  store ptr null, ptr %gep, align 8
  store ptr null, ptr %arg2, align 8
  br i1 %arg3, label %bb1, label %bb2
}
