; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-windows-msvc | FileCheck %s --check-prefixes=NO_APX_SSE
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+egpr | FileCheck %s --check-prefixes=APX_SSE
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=-sse | FileCheck %s --check-prefixes=NO_APX_NOSSE
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+egpr,-sse | FileCheck %s --check-prefixes=APX_NOSSE
; RUN: llc < %s -mtriple=x86_64-uefi | FileCheck %s --check-prefixes=NO_APX_SSE
; RUN: llc < %s -mtriple=x86_64-uefi -mattr=+egpr | FileCheck %s --check-prefixes=APX_SSE
; RUN: llc < %s -mtriple=x86_64-uefi -mattr=-sse | FileCheck %s --check-prefixes=NO_APX_NOSSE
; RUN: llc < %s -mtriple=x86_64-uefi -mattr=+egpr,-sse | FileCheck %s --check-prefixes=APX_NOSSE

; Test in SSE/no-SSE configurations that the Win64 APX ABI used on Windows
; and UEFI targets makes r30 and r31 non-volatile (callee-saved) per
; Microsoft spec, while the ordinary Win64 ABI treats them as caller-saved.

declare void @external_function()

define void @test_win64_apx_abi() nounwind {
; NO_APX_SSE-LABEL: test_win64_apx_abi:
; NO_APX_SSE:       # %bb.0:
; NO_APX_SSE-NEXT:    pushq %r15
; NO_APX_SSE-NEXT:    pushq %r14
; NO_APX_SSE-NEXT:    pushq %r13
; NO_APX_SSE-NEXT:    pushq %r12
; NO_APX_SSE-NEXT:    pushq %rsi
; NO_APX_SSE-NEXT:    pushq %rdi
; NO_APX_SSE-NEXT:    pushq %rbp
; NO_APX_SSE-NEXT:    pushq %rbx
; NO_APX_SSE-NEXT:    subq $200, %rsp
; NO_APX_SSE-NEXT:    movaps %xmm15, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NO_APX_SSE-NEXT:    movaps %xmm14, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NO_APX_SSE-NEXT:    movaps %xmm13, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NO_APX_SSE-NEXT:    movaps %xmm12, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NO_APX_SSE-NEXT:    movaps %xmm11, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NO_APX_SSE-NEXT:    movaps %xmm10, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NO_APX_SSE-NEXT:    movaps %xmm9, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NO_APX_SSE-NEXT:    movaps %xmm8, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NO_APX_SSE-NEXT:    movaps %xmm7, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NO_APX_SSE-NEXT:    movaps %xmm6, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; NO_APX_SSE-NEXT:    callq external_function
; NO_APX_SSE-NEXT:    #APP
; NO_APX_SSE-NEXT:    #NO_APP
; NO_APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm6 # 16-byte Reload
; NO_APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm7 # 16-byte Reload
; NO_APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm8 # 16-byte Reload
; NO_APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm9 # 16-byte Reload
; NO_APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm10 # 16-byte Reload
; NO_APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm11 # 16-byte Reload
; NO_APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm12 # 16-byte Reload
; NO_APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm13 # 16-byte Reload
; NO_APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm14 # 16-byte Reload
; NO_APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm15 # 16-byte Reload
; NO_APX_SSE-NEXT:    addq $200, %rsp
; NO_APX_SSE-NEXT:    popq %rbx
; NO_APX_SSE-NEXT:    popq %rbp
; NO_APX_SSE-NEXT:    popq %rdi
; NO_APX_SSE-NEXT:    popq %rsi
; NO_APX_SSE-NEXT:    popq %r12
; NO_APX_SSE-NEXT:    popq %r13
; NO_APX_SSE-NEXT:    popq %r14
; NO_APX_SSE-NEXT:    popq %r15
; NO_APX_SSE-NEXT:    retq
;
; APX_SSE-LABEL: test_win64_apx_abi:
; APX_SSE:       # %bb.0:
; APX_SSE-NEXT:    pushq %r31
; APX_SSE-NEXT:    pushq %r30
; APX_SSE-NEXT:    pushq %r15
; APX_SSE-NEXT:    pushq %r14
; APX_SSE-NEXT:    pushq %r13
; APX_SSE-NEXT:    pushq %r12
; APX_SSE-NEXT:    pushq %rsi
; APX_SSE-NEXT:    pushq %rdi
; APX_SSE-NEXT:    pushq %rbp
; APX_SSE-NEXT:    pushq %rbx
; APX_SSE-NEXT:    subq $200, %rsp
; APX_SSE-NEXT:    movaps %xmm15, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; APX_SSE-NEXT:    movaps %xmm14, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; APX_SSE-NEXT:    movaps %xmm13, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; APX_SSE-NEXT:    movaps %xmm12, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; APX_SSE-NEXT:    movaps %xmm11, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; APX_SSE-NEXT:    movaps %xmm10, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; APX_SSE-NEXT:    movaps %xmm9, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; APX_SSE-NEXT:    movaps %xmm8, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; APX_SSE-NEXT:    movaps %xmm7, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; APX_SSE-NEXT:    movaps %xmm6, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; APX_SSE-NEXT:    callq external_function
; APX_SSE-NEXT:    #APP
; APX_SSE-NEXT:    #NO_APP
; APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm6 # 16-byte Reload
; APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm7 # 16-byte Reload
; APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm8 # 16-byte Reload
; APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm9 # 16-byte Reload
; APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm10 # 16-byte Reload
; APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm11 # 16-byte Reload
; APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm12 # 16-byte Reload
; APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm13 # 16-byte Reload
; APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm14 # 16-byte Reload
; APX_SSE-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm15 # 16-byte Reload
; APX_SSE-NEXT:    addq $200, %rsp
; APX_SSE-NEXT:    popq %rbx
; APX_SSE-NEXT:    popq %rbp
; APX_SSE-NEXT:    popq %rdi
; APX_SSE-NEXT:    popq %rsi
; APX_SSE-NEXT:    popq %r12
; APX_SSE-NEXT:    popq %r13
; APX_SSE-NEXT:    popq %r14
; APX_SSE-NEXT:    popq %r15
; APX_SSE-NEXT:    popq %r30
; APX_SSE-NEXT:    popq %r31
; APX_SSE-NEXT:    retq
;
; NO_APX_NOSSE-LABEL: test_win64_apx_abi:
; NO_APX_NOSSE:       # %bb.0:
; NO_APX_NOSSE-NEXT:    pushq %r15
; NO_APX_NOSSE-NEXT:    pushq %r14
; NO_APX_NOSSE-NEXT:    pushq %r13
; NO_APX_NOSSE-NEXT:    pushq %r12
; NO_APX_NOSSE-NEXT:    pushq %rsi
; NO_APX_NOSSE-NEXT:    pushq %rdi
; NO_APX_NOSSE-NEXT:    pushq %rbp
; NO_APX_NOSSE-NEXT:    pushq %rbx
; NO_APX_NOSSE-NEXT:    subq $40, %rsp
; NO_APX_NOSSE-NEXT:    callq external_function
; NO_APX_NOSSE-NEXT:    #APP
; NO_APX_NOSSE-NEXT:    #NO_APP
; NO_APX_NOSSE-NEXT:    addq $40, %rsp
; NO_APX_NOSSE-NEXT:    popq %rbx
; NO_APX_NOSSE-NEXT:    popq %rbp
; NO_APX_NOSSE-NEXT:    popq %rdi
; NO_APX_NOSSE-NEXT:    popq %rsi
; NO_APX_NOSSE-NEXT:    popq %r12
; NO_APX_NOSSE-NEXT:    popq %r13
; NO_APX_NOSSE-NEXT:    popq %r14
; NO_APX_NOSSE-NEXT:    popq %r15
; NO_APX_NOSSE-NEXT:    retq
;
; APX_NOSSE-LABEL: test_win64_apx_abi:
; APX_NOSSE:       # %bb.0:
; APX_NOSSE-NEXT:    pushq %r31
; APX_NOSSE-NEXT:    pushq %r30
; APX_NOSSE-NEXT:    pushq %r15
; APX_NOSSE-NEXT:    pushq %r14
; APX_NOSSE-NEXT:    pushq %r13
; APX_NOSSE-NEXT:    pushq %r12
; APX_NOSSE-NEXT:    pushq %rsi
; APX_NOSSE-NEXT:    pushq %rdi
; APX_NOSSE-NEXT:    pushq %rbp
; APX_NOSSE-NEXT:    pushq %rbx
; APX_NOSSE-NEXT:    subq $40, %rsp
; APX_NOSSE-NEXT:    callq external_function
; APX_NOSSE-NEXT:    #APP
; APX_NOSSE-NEXT:    #NO_APP
; APX_NOSSE-NEXT:    addq $40, %rsp
; APX_NOSSE-NEXT:    popq %rbx
; APX_NOSSE-NEXT:    popq %rbp
; APX_NOSSE-NEXT:    popq %rdi
; APX_NOSSE-NEXT:    popq %rsi
; APX_NOSSE-NEXT:    popq %r12
; APX_NOSSE-NEXT:    popq %r13
; APX_NOSSE-NEXT:    popq %r14
; APX_NOSSE-NEXT:    popq %r15
; APX_NOSSE-NEXT:    popq %r30
; APX_NOSSE-NEXT:    popq %r31
; APX_NOSSE-NEXT:    retq
  call void @external_function()
  call void asm sideeffect "", "~{rax},~{rbx},~{rcx},~{rdx},~{rsi},~{rdi},~{r8},~{r9},~{r10},~{r11},~{r12},~{r13},~{r14},~{r15},~{r16},~{r17},~{r18},~{r19},~{r20},~{r21},~{r22},~{r23},~{r24},~{r25},~{r26},~{r27},~{r28},~{r29},~{r30},~{r31},~{rbp},~{xmm0},~{xmm1},~{xmm2},~{xmm3},~{xmm4},~{xmm5},~{xmm6},~{xmm7},~{xmm8},~{xmm9},~{xmm10},~{xmm11},~{xmm12},~{xmm13},~{xmm14},~{xmm15}"()
  ret void
}
