; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S %s -passes='require<libcall-lowering-info>,atomic-expand' -mtriple=nvptx64-nvidia-cuda -mcpu=sm_90 -mattr=+ptx83 | FileCheck %s

target triple = "nvptx64-nvidia-cuda"

; A <1 x T> elementwise atomicrmw collapses directly to a scalar RMW and wraps
; the old value back into a single-lane vector.
define <1 x float> @fadd_v1f32_elementwise(ptr %addr, <1 x float> %val) {
; CHECK-LABEL: @fadd_v1f32_elementwise(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[LANE_VAL:%.*]] = extractelement <1 x float> [[VAL:%.*]], i64 0
; CHECK-NEXT:    [[TMP0:%.*]] = atomicrmw fadd ptr [[ADDR:%.*]], float [[LANE_VAL]] monotonic, align 4
; CHECK-NEXT:    [[LANE_OLD:%.*]] = insertelement <1 x float> poison, float [[TMP0]], i64 0
; CHECK-NEXT:    ret <1 x float> [[LANE_OLD]]
;
entry:
  %old = atomicrmw elementwise fadd ptr %addr, <1 x float> %val monotonic
  ret <1 x float> %old
}

; Elementwise expansion: scalar f32 atomics are legal, so the vector is split
; into scalar atomicrmw instructions.
define <2 x float> @fadd_v2f32_elementwise(ptr %addr, <2 x float> %val) {
; CHECK-LABEL: @fadd_v2f32_elementwise(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[LO_VAL:%.*]] = extractelement <2 x float> [[VAL:%.*]], i64 0
; CHECK-NEXT:    [[HI_VAL:%.*]] = extractelement <2 x float> [[VAL]], i64 1
; CHECK-NEXT:    [[HI_PTR:%.*]] = getelementptr inbounds float, ptr [[ADDR:%.*]], i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = atomicrmw fadd ptr [[ADDR]], float [[LO_VAL]] monotonic, align 8
; CHECK-NEXT:    [[TMP1:%.*]] = atomicrmw fadd ptr [[HI_PTR]], float [[HI_VAL]] monotonic, align 4
; CHECK-NEXT:    [[LO_OLD:%.*]] = insertelement <2 x float> poison, float [[TMP0]], i64 0
; CHECK-NEXT:    [[HI_OLD:%.*]] = insertelement <2 x float> [[LO_OLD]], float [[TMP1]], i64 1
; CHECK-NEXT:    ret <2 x float> [[HI_OLD]]
;
entry:
  %old = atomicrmw elementwise fadd ptr %addr, <2 x float> %val monotonic
  ret <2 x float> %old
}

; Metadata attached to an elementwise RMW is preserved on each split child.
define <2 x i32> @add_metadata_v2i32_elementwise(ptr %addr, <2 x i32> %val) {
; CHECK-LABEL: @add_metadata_v2i32_elementwise(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[LO_VAL:%.*]] = extractelement <2 x i32> [[VAL:%.*]], i64 0
; CHECK-NEXT:    [[HI_VAL:%.*]] = extractelement <2 x i32> [[VAL]], i64 1
; CHECK-NEXT:    [[HI_PTR:%.*]] = getelementptr inbounds i32, ptr [[ADDR:%.*]], i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = atomicrmw add ptr [[ADDR]], i32 [[LO_VAL]] monotonic, align 8, !mmra [[META0:![0-9]+]]
; CHECK-NEXT:    [[TMP1:%.*]] = atomicrmw add ptr [[HI_PTR]], i32 [[HI_VAL]] monotonic, align 4, !mmra [[META0]]
; CHECK-NEXT:    [[LO_OLD:%.*]] = insertelement <2 x i32> poison, i32 [[TMP0]], i64 0
; CHECK-NEXT:    [[HI_OLD:%.*]] = insertelement <2 x i32> [[LO_OLD]], i32 [[TMP1]], i64 1
; CHECK-NEXT:    ret <2 x i32> [[HI_OLD]]
;
entry:
  %old = atomicrmw elementwise add ptr %addr, <2 x i32> %val monotonic, !mmra !0
  ret <2 x i32> %old
}

; Volatile is preserved while splitting elementwise operations.
define <2 x float> @fadd_volatile_v2f32_elementwise(ptr %addr, <2 x float> %val) {
; CHECK-LABEL: @fadd_volatile_v2f32_elementwise(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[LO_VAL:%.*]] = extractelement <2 x float> [[VAL:%.*]], i64 0
; CHECK-NEXT:    [[HI_VAL:%.*]] = extractelement <2 x float> [[VAL]], i64 1
; CHECK-NEXT:    [[HI_PTR:%.*]] = getelementptr inbounds float, ptr [[ADDR:%.*]], i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = atomicrmw volatile fadd ptr [[ADDR]], float [[LO_VAL]] monotonic, align 8
; CHECK-NEXT:    [[TMP1:%.*]] = atomicrmw volatile fadd ptr [[HI_PTR]], float [[HI_VAL]] monotonic, align 4
; CHECK-NEXT:    [[LO_OLD:%.*]] = insertelement <2 x float> poison, float [[TMP0]], i64 0
; CHECK-NEXT:    [[HI_OLD:%.*]] = insertelement <2 x float> [[LO_OLD]], float [[TMP1]], i64 1
; CHECK-NEXT:    ret <2 x float> [[HI_OLD]]
;
entry:
  %old = atomicrmw volatile elementwise fadd ptr %addr, <2 x float> %val monotonic
  ret <2 x float> %old
}

; Ordered elementwise expansion: fences should be inserted around the whole
; split expansion rather than around each split child.
define <4 x i32> @add_acq_rel_v4i32_elementwise(ptr %addr, <4 x i32> %val) {
; CHECK-LABEL: @add_acq_rel_v4i32_elementwise(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    fence syncscope("block") release
; CHECK-NEXT:    [[LO_VAL:%.*]] = shufflevector <4 x i32> [[VAL:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[HI_VAL:%.*]] = shufflevector <4 x i32> [[VAL]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    [[HI_PTR:%.*]] = getelementptr inbounds <2 x i32>, ptr [[ADDR:%.*]], i64 1
; CHECK-NEXT:    [[LO_VAL2:%.*]] = extractelement <2 x i32> [[LO_VAL]], i64 0
; CHECK-NEXT:    [[HI_VAL3:%.*]] = extractelement <2 x i32> [[LO_VAL]], i64 1
; CHECK-NEXT:    [[HI_PTR4:%.*]] = getelementptr inbounds i32, ptr [[ADDR]], i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = atomicrmw add ptr [[ADDR]], i32 [[LO_VAL2]] syncscope("block") monotonic, align 16
; CHECK-NEXT:    [[TMP1:%.*]] = atomicrmw add ptr [[HI_PTR4]], i32 [[HI_VAL3]] syncscope("block") monotonic, align 4
; CHECK-NEXT:    [[LO_OLD:%.*]] = insertelement <2 x i32> poison, i32 [[TMP0]], i64 0
; CHECK-NEXT:    [[HI_OLD:%.*]] = insertelement <2 x i32> [[LO_OLD]], i32 [[TMP1]], i64 1
; CHECK-NEXT:    [[LO_VAL5:%.*]] = extractelement <2 x i32> [[HI_VAL]], i64 0
; CHECK-NEXT:    [[HI_VAL6:%.*]] = extractelement <2 x i32> [[HI_VAL]], i64 1
; CHECK-NEXT:    [[HI_PTR7:%.*]] = getelementptr inbounds i32, ptr [[HI_PTR]], i64 1
; CHECK-NEXT:    [[TMP2:%.*]] = atomicrmw add ptr [[HI_PTR]], i32 [[LO_VAL5]] syncscope("block") monotonic, align 8
; CHECK-NEXT:    [[TMP3:%.*]] = atomicrmw add ptr [[HI_PTR7]], i32 [[HI_VAL6]] syncscope("block") monotonic, align 4
; CHECK-NEXT:    [[LO_OLD8:%.*]] = insertelement <2 x i32> poison, i32 [[TMP2]], i64 0
; CHECK-NEXT:    [[HI_OLD9:%.*]] = insertelement <2 x i32> [[LO_OLD8]], i32 [[TMP3]], i64 1
; CHECK-NEXT:    [[OLD1:%.*]] = shufflevector <2 x i32> [[HI_OLD]], <2 x i32> [[HI_OLD9]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    fence syncscope("block") acquire
; CHECK-NEXT:    ret <4 x i32> [[OLD1]]
;
entry:
  %old = atomicrmw elementwise add ptr %addr, <4 x i32> %val syncscope("block") acq_rel, align 16
  ret <4 x i32> %old
}

; Seq-cst elementwise expansion also gets one outer fence before splitting.
define <2 x i32> @add_seq_cst_v4i32_elementwise(ptr %addr, <2 x i32> %val) {
; CHECK-LABEL: @add_seq_cst_v4i32_elementwise(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    fence syncscope("block") seq_cst
; CHECK-NEXT:    [[LO_VAL2:%.*]] = extractelement <2 x i32> [[LO_VAL:%.*]], i64 0
; CHECK-NEXT:    [[HI_VAL3:%.*]] = extractelement <2 x i32> [[LO_VAL]], i64 1
; CHECK-NEXT:    [[HI_PTR4:%.*]] = getelementptr inbounds i32, ptr [[ADDR:%.*]], i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = atomicrmw add ptr [[ADDR]], i32 [[LO_VAL2]] syncscope("block") monotonic, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = atomicrmw add ptr [[HI_PTR4]], i32 [[HI_VAL3]] syncscope("block") monotonic, align 4
; CHECK-NEXT:    [[LO_OLD8:%.*]] = insertelement <2 x i32> poison, i32 [[TMP0]], i64 0
; CHECK-NEXT:    [[HI_OLD9:%.*]] = insertelement <2 x i32> [[LO_OLD8]], i32 [[TMP3]], i64 1
; CHECK-NEXT:    fence syncscope("block") acquire
; CHECK-NEXT:    ret <2 x i32> [[HI_OLD9]]
;
entry:
  %old = atomicrmw elementwise add ptr %addr, <2 x i32> %val syncscope("block") seq_cst, align 16
  ret <2 x i32> %old
}

; Whole-vector cmpxchg expansion: sm_90 + ptx83 supports 128-bit cmpxchg, so
; this vector can stay whole during AtomicExpand.
define <8 x half> @fmin_v8f16_elementwise(ptr %addr, <8 x half> %val) {
; CHECK-LABEL: @fmin_v8f16_elementwise(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load atomic i128, ptr [[ADDR:%.*]] monotonic, align 16
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast i128 [[TMP0]] to <8 x half>
; CHECK-NEXT:    br label [[ATOMICRMW_START:%.*]]
; CHECK:       atomicrmw.start:
; CHECK-NEXT:    [[LOADED:%.*]] = phi <8 x half> [ [[TMP1]], [[ENTRY:%.*]] ], [ [[TMP6:%.*]], [[ATOMICRMW_START]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = call <8 x half> @llvm.minnum.v8f16(<8 x half> [[LOADED]], <8 x half> [[VAL:%.*]])
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x half> [[TMP2]] to i128
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <8 x half> [[LOADED]] to i128
; CHECK-NEXT:    [[TMP5:%.*]] = cmpxchg ptr [[ADDR]], i128 [[TMP4]], i128 [[TMP3]] monotonic monotonic, align 16
; CHECK-NEXT:    [[SUCCESS:%.*]] = extractvalue { i128, i1 } [[TMP5]], 1
; CHECK-NEXT:    [[NEWLOADED:%.*]] = extractvalue { i128, i1 } [[TMP5]], 0
; CHECK-NEXT:    [[TMP6]] = bitcast i128 [[NEWLOADED]] to <8 x half>
; CHECK-NEXT:    br i1 [[SUCCESS]], label [[ATOMICRMW_END:%.*]], label [[ATOMICRMW_START]]
; CHECK:       atomicrmw.end:
; CHECK-NEXT:    ret <8 x half> [[TMP6]]
;
entry:
  %old = atomicrmw elementwise fmin ptr %addr, <8 x half> %val monotonic, align 16
  ret <8 x half> %old
}

; Vector xchg is bit-equivalent to xchg on the same-width integer type.
define <4 x i8> @xchg_v4i8_elementwise(ptr %addr, <4 x i8> %val) {
; CHECK-LABEL: @xchg_v4i8_elementwise(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8> [[VAL:%.*]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = atomicrmw xchg ptr [[ADDR:%.*]], i32 [[TMP0]] monotonic, align 4
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast i32 [[TMP1]] to <4 x i8>
; CHECK-NEXT:    ret <4 x i8> [[TMP2]]
;
entry:
  %old = atomicrmw elementwise xchg ptr %addr, <4 x i8> %val monotonic, align 4
  ret <4 x i8> %old
}

; Partword bitwise vector atomics must bitcast before widening; zext directly
; from <2 x i8> to i32 is invalid IR.
define <2 x i8> @and_v2i8_partword_elementwise(ptr %addr, <2 x i8> %val) {
; CHECK-LABEL: @and_v2i8_partword_elementwise(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ALIGNEDADDR:%.*]] = call ptr @llvm.ptrmask.p0.i64(ptr [[ADDR:%.*]], i64 -4)
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[ADDR]] to i64
; CHECK-NEXT:    [[PTRLSB:%.*]] = and i64 [[TMP0]], 3
; CHECK-NEXT:    [[TMP1:%.*]] = shl i64 [[PTRLSB]], 3
; CHECK-NEXT:    [[SHIFTAMT:%.*]] = trunc i64 [[TMP1]] to i32
; CHECK-NEXT:    [[MASK:%.*]] = shl i32 65535, [[SHIFTAMT]]
; CHECK-NEXT:    [[INV_MASK:%.*]] = xor i32 [[MASK]], -1
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i8> [[VAL:%.*]] to i16
; CHECK-NEXT:    [[TMP3:%.*]] = zext i16 [[TMP2]] to i32
; CHECK-NEXT:    [[VALOPERAND_SHIFTED:%.*]] = shl i32 [[TMP3]], [[SHIFTAMT]]
; CHECK-NEXT:    [[ANDOPERAND:%.*]] = or i32 [[VALOPERAND_SHIFTED]], [[INV_MASK]]
; CHECK-NEXT:    [[TMP4:%.*]] = atomicrmw and ptr [[ALIGNEDADDR]], i32 [[ANDOPERAND]] monotonic, align 4
; CHECK-NEXT:    [[SHIFTED:%.*]] = lshr i32 [[TMP4]], [[SHIFTAMT]]
; CHECK-NEXT:    [[EXTRACTED:%.*]] = trunc i32 [[SHIFTED]] to i16
; CHECK-NEXT:    [[TMP5:%.*]] = bitcast i16 [[EXTRACTED]] to <2 x i8>
; CHECK-NEXT:    ret <2 x i8> [[TMP5]]
;
entry:
  %old = atomicrmw elementwise and ptr %addr, <2 x i8> %val monotonic
  ret <2 x i8> %old
}

; Partword vector arithmetic must operate lane-wise before reinserting into the
; containing CAS word, otherwise packed integer carries can cross lanes.
define <2 x i8> @add_v2i8_partword_elementwise(ptr %addr, <2 x i8> %val) {
; CHECK-LABEL: @add_v2i8_partword_elementwise(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ALIGNEDADDR:%.*]] = call ptr @llvm.ptrmask.p0.i64(ptr [[ADDR:%.*]], i64 -4)
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[ADDR]] to i64
; CHECK-NEXT:    [[PTRLSB:%.*]] = and i64 [[TMP0]], 3
; CHECK-NEXT:    [[TMP1:%.*]] = shl i64 [[PTRLSB]], 3
; CHECK-NEXT:    [[SHIFTAMT:%.*]] = trunc i64 [[TMP1]] to i32
; CHECK-NEXT:    [[MASK:%.*]] = shl i32 65535, [[SHIFTAMT]]
; CHECK-NEXT:    [[INV_MASK:%.*]] = xor i32 [[MASK]], -1
; CHECK-NEXT:    [[TMP2:%.*]] = load atomic i32, ptr [[ALIGNEDADDR]] monotonic, align 4
; CHECK-NEXT:    br label [[ATOMICRMW_START:%.*]]
; CHECK:       atomicrmw.start:
; CHECK-NEXT:    [[LOADED:%.*]] = phi i32 [ [[TMP2]], [[ENTRY:%.*]] ], [ [[NEWLOADED:%.*]], [[ATOMICRMW_START]] ]
; CHECK-NEXT:    [[SHIFTED:%.*]] = lshr i32 [[LOADED]], [[SHIFTAMT]]
; CHECK-NEXT:    [[EXTRACTED:%.*]] = trunc i32 [[SHIFTED]] to i16
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast i16 [[EXTRACTED]] to <2 x i8>
; CHECK-NEXT:    [[NEW:%.*]] = add <2 x i8> [[TMP3]], [[VAL:%.*]]
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <2 x i8> [[NEW]] to i16
; CHECK-NEXT:    [[EXTENDED:%.*]] = zext i16 [[TMP4]] to i32
; CHECK-NEXT:    [[SHIFTED1:%.*]] = shl nuw i32 [[EXTENDED]], [[SHIFTAMT]]
; CHECK-NEXT:    [[UNMASKED:%.*]] = and i32 [[LOADED]], [[INV_MASK]]
; CHECK-NEXT:    [[INSERTED:%.*]] = or i32 [[UNMASKED]], [[SHIFTED1]]
; CHECK-NEXT:    [[TMP5:%.*]] = cmpxchg ptr [[ALIGNEDADDR]], i32 [[LOADED]], i32 [[INSERTED]] monotonic monotonic, align 4
; CHECK-NEXT:    [[SUCCESS:%.*]] = extractvalue { i32, i1 } [[TMP5]], 1
; CHECK-NEXT:    [[NEWLOADED]] = extractvalue { i32, i1 } [[TMP5]], 0
; CHECK-NEXT:    br i1 [[SUCCESS]], label [[ATOMICRMW_END:%.*]], label [[ATOMICRMW_START]]
; CHECK:       atomicrmw.end:
; CHECK-NEXT:    [[SHIFTED2:%.*]] = lshr i32 [[NEWLOADED]], [[SHIFTAMT]]
; CHECK-NEXT:    [[EXTRACTED3:%.*]] = trunc i32 [[SHIFTED2]] to i16
; CHECK-NEXT:    [[TMP6:%.*]] = bitcast i16 [[EXTRACTED3]] to <2 x i8>
; CHECK-NEXT:    ret <2 x i8> [[TMP6]]
;
entry:
  %old = atomicrmw elementwise add ptr %addr, <2 x i8> %val monotonic
  ret <2 x i8> %old
}

; Use two 128-bit cmpxchg loops to handle the 8 x i32 vector.
define <8 x i32> @nand_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; CHECK-LABEL: @nand_acq_rel_v8i32_global_cta(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    fence syncscope("block") release
; CHECK-NEXT:    [[LO_VAL:%.*]] = shufflevector <8 x i32> [[VAL:%.*]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    [[HI_VAL:%.*]] = shufflevector <8 x i32> [[VAL]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[HI_PTR:%.*]] = getelementptr inbounds <4 x i32>, ptr addrspace(1) [[ADDR:%.*]], i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = load atomic i128, ptr addrspace(1) [[ADDR]] syncscope("block") monotonic, align 32
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast i128 [[TMP0]] to <4 x i32>
; CHECK-NEXT:    br label [[ATOMICRMW_START:%.*]]
; CHECK:       atomicrmw.start:
; CHECK-NEXT:    [[LOADED:%.*]] = phi <4 x i32> [ [[TMP1]], [[ENTRY:%.*]] ], [ [[TMP6:%.*]], [[ATOMICRMW_START]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = and <4 x i32> [[LOADED]], [[LO_VAL]]
; CHECK-NEXT:    [[NEW:%.*]] = xor <4 x i32> [[TMP2]], splat (i32 -1)
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x i32> [[NEW]] to i128
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <4 x i32> [[LOADED]] to i128
; CHECK-NEXT:    [[TMP5:%.*]] = cmpxchg ptr addrspace(1) [[ADDR]], i128 [[TMP4]], i128 [[TMP3]] syncscope("block") monotonic monotonic, align 32
; CHECK-NEXT:    [[SUCCESS:%.*]] = extractvalue { i128, i1 } [[TMP5]], 1
; CHECK-NEXT:    [[NEWLOADED:%.*]] = extractvalue { i128, i1 } [[TMP5]], 0
; CHECK-NEXT:    [[TMP6]] = bitcast i128 [[NEWLOADED]] to <4 x i32>
; CHECK-NEXT:    br i1 [[SUCCESS]], label [[ATOMICRMW_END:%.*]], label [[ATOMICRMW_START]]
; CHECK:       atomicrmw.end:
; CHECK-NEXT:    [[TMP7:%.*]] = load atomic i128, ptr addrspace(1) [[HI_PTR]] syncscope("block") monotonic, align 16
; CHECK-NEXT:    [[TMP8:%.*]] = bitcast i128 [[TMP7]] to <4 x i32>
; CHECK-NEXT:    br label [[ATOMICRMW_START2:%.*]]
; CHECK:       atomicrmw.start2:
; CHECK-NEXT:    [[LOADED3:%.*]] = phi <4 x i32> [ [[TMP8]], [[ATOMICRMW_END]] ], [ [[TMP13:%.*]], [[ATOMICRMW_START2]] ]
; CHECK-NEXT:    [[TMP9:%.*]] = and <4 x i32> [[LOADED3]], [[HI_VAL]]
; CHECK-NEXT:    [[NEW4:%.*]] = xor <4 x i32> [[TMP9]], splat (i32 -1)
; CHECK-NEXT:    [[TMP10:%.*]] = bitcast <4 x i32> [[NEW4]] to i128
; CHECK-NEXT:    [[TMP11:%.*]] = bitcast <4 x i32> [[LOADED3]] to i128
; CHECK-NEXT:    [[TMP12:%.*]] = cmpxchg ptr addrspace(1) [[HI_PTR]], i128 [[TMP11]], i128 [[TMP10]] syncscope("block") monotonic monotonic, align 16
; CHECK-NEXT:    [[SUCCESS5:%.*]] = extractvalue { i128, i1 } [[TMP12]], 1
; CHECK-NEXT:    [[NEWLOADED6:%.*]] = extractvalue { i128, i1 } [[TMP12]], 0
; CHECK-NEXT:    [[TMP13]] = bitcast i128 [[NEWLOADED6]] to <4 x i32>
; CHECK-NEXT:    br i1 [[SUCCESS5]], label [[ATOMICRMW_END1:%.*]], label [[ATOMICRMW_START2]]
; CHECK:       atomicrmw.end1:
; CHECK-NEXT:    [[OLD:%.*]] = shufflevector <4 x i32> [[TMP6]], <4 x i32> [[TMP13]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    fence syncscope("block") acquire
; CHECK-NEXT:    ret <8 x i32> [[OLD]]
;
entry:
  %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
  ret <8 x i32> %retval
}

!0 = !{!1, !2}
!1 = !{!"foo", !"bar"}
!2 = !{!"bux", !"baz"}

