# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv32 -mattr=+a,+zabha -run-pass=instruction-select %s -o - | FileCheck %s

---
name:            atomicrmw_and_i8_monotonic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; CHECK-LABEL: name: atomicrmw_and_i8_monotonic
    ; CHECK: liveins: $x10, $x11
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[AMOAND_B:%[0-9]+]]:gpr = AMOAND_B [[COPY1]], [[COPY]] :: (load store monotonic (s8))
    ; CHECK-NEXT: $x10 = COPY [[AMOAND_B]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gprb(p0) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ATOMICRMW_AND %0(p0), %1 :: (load store monotonic (s8))
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10
...
---
name:            atomicrmw_and_i16_monotonic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; CHECK-LABEL: name: atomicrmw_and_i16_monotonic
    ; CHECK: liveins: $x10, $x11
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[AMOAND_H:%[0-9]+]]:gpr = AMOAND_H [[COPY1]], [[COPY]] :: (load store monotonic (s16))
    ; CHECK-NEXT: $x10 = COPY [[AMOAND_H]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gprb(p0) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ATOMICRMW_AND %0(p0), %1 :: (load store monotonic (s16))
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10
...
---
name:            atomicrmw_and_i32_monotonic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; CHECK-LABEL: name: atomicrmw_and_i32_monotonic
    ; CHECK: liveins: $x10, $x11
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[AMOAND_W:%[0-9]+]]:gpr = AMOAND_W [[COPY1]], [[COPY]] :: (load store monotonic (s32))
    ; CHECK-NEXT: $x10 = COPY [[AMOAND_W]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gprb(p0) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ATOMICRMW_AND %0(p0), %1 :: (load store monotonic (s32))
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10
...
---
name:            atomicrmw_or_i8_monotonic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; CHECK-LABEL: name: atomicrmw_or_i8_monotonic
    ; CHECK: liveins: $x10, $x11
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[AMOOR_B:%[0-9]+]]:gpr = AMOOR_B [[COPY1]], [[COPY]] :: (load store monotonic (s8))
    ; CHECK-NEXT: $x10 = COPY [[AMOOR_B]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gprb(p0) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ATOMICRMW_OR %0(p0), %1 :: (load store monotonic (s8))
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10
...
---
name:            atomicrmw_or_i16_monotonic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; CHECK-LABEL: name: atomicrmw_or_i16_monotonic
    ; CHECK: liveins: $x10, $x11
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[AMOOR_H:%[0-9]+]]:gpr = AMOOR_H [[COPY1]], [[COPY]] :: (load store monotonic (s16))
    ; CHECK-NEXT: $x10 = COPY [[AMOOR_H]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gprb(p0) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ATOMICRMW_OR %0(p0), %1 :: (load store monotonic (s16))
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10
...
---
name:            atomicrmw_or_i32_monotonic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; CHECK-LABEL: name: atomicrmw_or_i32_monotonic
    ; CHECK: liveins: $x10, $x11
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[AMOOR_W:%[0-9]+]]:gpr = AMOOR_W [[COPY1]], [[COPY]] :: (load store monotonic (s32))
    ; CHECK-NEXT: $x10 = COPY [[AMOOR_W]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gprb(p0) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ATOMICRMW_OR %0(p0), %1 :: (load store monotonic (s32))
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10
...
---
name:            atomicrmw_xor_i8_monotonic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; CHECK-LABEL: name: atomicrmw_xor_i8_monotonic
    ; CHECK: liveins: $x10, $x11
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[AMOXOR_B:%[0-9]+]]:gpr = AMOXOR_B [[COPY1]], [[COPY]] :: (load store monotonic (s8))
    ; CHECK-NEXT: $x10 = COPY [[AMOXOR_B]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gprb(p0) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ATOMICRMW_XOR %0(p0), %1 :: (load store monotonic (s8))
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10
...
---
name:            atomicrmw_xor_i16_monotonic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; CHECK-LABEL: name: atomicrmw_xor_i16_monotonic
    ; CHECK: liveins: $x10, $x11
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[AMOXOR_H:%[0-9]+]]:gpr = AMOXOR_H [[COPY1]], [[COPY]] :: (load store monotonic (s16))
    ; CHECK-NEXT: $x10 = COPY [[AMOXOR_H]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gprb(p0) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ATOMICRMW_XOR %0(p0), %1 :: (load store monotonic (s16))
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10
...
---
name:            atomicrmw_xor_i32_monotonic
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; CHECK-LABEL: name: atomicrmw_xor_i32_monotonic
    ; CHECK: liveins: $x10, $x11
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[AMOXOR_W:%[0-9]+]]:gpr = AMOXOR_W [[COPY1]], [[COPY]] :: (load store monotonic (s32))
    ; CHECK-NEXT: $x10 = COPY [[AMOXOR_W]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gprb(p0) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ATOMICRMW_XOR %0(p0), %1 :: (load store monotonic (s32))
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10
...
