// clang-format off
// RUN: %libomp-compile && env OMP_NUM_THREADS=2 KMP_ENABLE_TASK_THROTTLING=1 KMP_ENABLE_TASK_THROTTLING_GLOBAL=0 KMP_ENABLE_TASK_THROTTLING_READY_PER_THREAD=0 KMP_ENABLE_TASK_THROTTLING_CHILDREN=1 KMP_TASK_MAXIMUM_CHILDREN=1      %libomp-run
// RUN: %libomp-compile && env OMP_NUM_THREADS=2 KMP_ENABLE_TASK_THROTTLING=1 KMP_ENABLE_TASK_THROTTLING_GLOBAL=0 KMP_ENABLE_TASK_THROTTLING_READY_PER_THREAD=0 KMP_ENABLE_TASK_THROTTLING_CHILDREN=1 KMP_TASK_MAXIMUM_CHILDREN=256    %libomp-run
// RUN: %libomp-compile && env OMP_NUM_THREADS=2 KMP_ENABLE_TASK_THROTTLING=1 KMP_ENABLE_TASK_THROTTLING_GLOBAL=0 KMP_ENABLE_TASK_THROTTLING_READY_PER_THREAD=0 KMP_ENABLE_TASK_THROTTLING_CHILDREN=1 KMP_TASK_MAXIMUM_CHILDREN=65536  %libomp-run
// RUN: %libomp-compile && env OMP_NUM_THREADS=2 KMP_ENABLE_TASK_THROTTLING=1 KMP_ENABLE_TASK_THROTTLING_GLOBAL=0 KMP_ENABLE_TASK_THROTTLING_READY_PER_THREAD=0 KMP_ENABLE_TASK_THROTTLING_CHILDREN=1 KMP_TASK_MAXIMUM_CHILDREN=100000 %libomp-run
// clang-format on

#define ENABLE_ENV_VAR ("KMP_ENABLE_TASK_THROTTLING_CHILDREN")
#define MAX_ENV_VAR ("KMP_TASK_MAXIMUM_CHILDREN")
#define USE_DEPS (1)

#include "omp_throttling.h"
