// clang-format off
// RUN: %libomp-compile && env OMP_NUM_THREADS=2 KMP_ENABLE_TASK_THROTTLING=1 KMP_ENABLE_TASK_THROTTLING_GLOBAL=1 KMP_ENABLE_TASK_THROTTLING_READY_PER_THREAD=0 KMP_ENABLE_TASK_THROTTLING_CHILDREN=0 KMP_TASK_MAXIMUM_GLOBAL=1      %libomp-run
// RUN: %libomp-compile && env OMP_NUM_THREADS=2 KMP_ENABLE_TASK_THROTTLING=1 KMP_ENABLE_TASK_THROTTLING_GLOBAL=1 KMP_ENABLE_TASK_THROTTLING_READY_PER_THREAD=0 KMP_ENABLE_TASK_THROTTLING_CHILDREN=0 KMP_TASK_MAXIMUM_GLOBAL=256    %libomp-run
// RUN: %libomp-compile && env OMP_NUM_THREADS=2 KMP_ENABLE_TASK_THROTTLING=1 KMP_ENABLE_TASK_THROTTLING_GLOBAL=1 KMP_ENABLE_TASK_THROTTLING_READY_PER_THREAD=0 KMP_ENABLE_TASK_THROTTLING_CHILDREN=0 KMP_TASK_MAXIMUM_GLOBAL=65536  %libomp-run
// RUN: %libomp-compile && env OMP_NUM_THREADS=2 KMP_ENABLE_TASK_THROTTLING=1 KMP_ENABLE_TASK_THROTTLING_GLOBAL=1 KMP_ENABLE_TASK_THROTTLING_READY_PER_THREAD=0 KMP_ENABLE_TASK_THROTTLING_CHILDREN=0 KMP_TASK_MAXIMUM_GLOBAL=100000 %libomp-run
// REQUIRES: kmp_task_throttling_global
// clang-format on

#define ENABLE_ENV_VAR ("KMP_ENABLE_TASK_THROTTLING_GLOBAL")
#define MAX_ENV_VAR ("KMP_TASK_MAXIMUM_GLOBAL")
#define USE_DEPS (1)

#include "omp_throttling.h"
