; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=pre-isel-intrinsic-lowering -S -mattr=+sve < %s | FileCheck %s
target triple = "aarch64"

define <vscale x 4 x float> @scalable_vec_atan2(<vscale x 4 x float> %a, <vscale x 4 x float> %b) {
; CHECK-LABEL: define <vscale x 4 x float> @scalable_vec_atan2(
; CHECK-SAME: <vscale x 4 x float> [[A:%.*]], <vscale x 4 x float> [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP2:%.*]] = mul nuw i64 [[TMP1]], 4
; CHECK-NEXT:    br label %[[BB3:.*]]
; CHECK:       [[BB3]]:
; CHECK-NEXT:    [[TMP4:%.*]] = phi i64 [ 0, [[TMP0:%.*]] ], [ [[TMP10:%.*]], %[[BB3]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = phi <vscale x 4 x float> [ [[A]], [[TMP0]] ], [ [[TMP9:%.*]], %[[BB3]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <vscale x 4 x float> [[TMP5]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 4 x float> [[B]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP8:%.*]] = call float @llvm.atan2.f32(float [[TMP6]], float [[TMP7]])
; CHECK-NEXT:    [[TMP9]] = insertelement <vscale x 4 x float> [[TMP5]], float [[TMP8]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP10]] = add i64 [[TMP4]], 1
; CHECK-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[TMP10]], [[TMP2]]
; CHECK-NEXT:    br i1 [[TMP11]], label %[[BB12:.*]], label %[[BB3]]
; CHECK:       [[BB12]]:
; CHECK-NEXT:    ret <vscale x 4 x float> [[TMP9]]
;
  %output = call <vscale x 4 x float> @llvm.atan2.nxv4f32(<vscale x 4 x float> %a, <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %output
}

define <vscale x 4 x float> @scalable_vec_pow(<vscale x 4 x float> %a, <vscale x 4 x float> %b) {
; CHECK-LABEL: define <vscale x 4 x float> @scalable_vec_pow(
; CHECK-SAME: <vscale x 4 x float> [[A:%.*]], <vscale x 4 x float> [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP2:%.*]] = mul nuw i64 [[TMP1]], 4
; CHECK-NEXT:    br label %[[BB3:.*]]
; CHECK:       [[BB3]]:
; CHECK-NEXT:    [[TMP4:%.*]] = phi i64 [ 0, [[TMP0:%.*]] ], [ [[TMP10:%.*]], %[[BB3]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = phi <vscale x 4 x float> [ [[A]], [[TMP0]] ], [ [[TMP9:%.*]], %[[BB3]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <vscale x 4 x float> [[TMP5]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 4 x float> [[B]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP8:%.*]] = call float @llvm.pow.f32(float [[TMP6]], float [[TMP7]])
; CHECK-NEXT:    [[TMP9]] = insertelement <vscale x 4 x float> [[TMP5]], float [[TMP8]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP10]] = add i64 [[TMP4]], 1
; CHECK-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[TMP10]], [[TMP2]]
; CHECK-NEXT:    br i1 [[TMP11]], label %[[BB12:.*]], label %[[BB3]]
; CHECK:       [[BB12]]:
; CHECK-NEXT:    ret <vscale x 4 x float> [[TMP9]]
;
  %output = call <vscale x 4 x float> @llvm.pow.nxv4f32(<vscale x 4 x float> %a, <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %output
}

define <vscale x 4 x float> @scalable_vec_ldexp(<vscale x 4 x float> %a, <vscale x 4 x i32> %b) {
; CHECK-LABEL: define <vscale x 4 x float> @scalable_vec_ldexp(
; CHECK-SAME: <vscale x 4 x float> [[A:%.*]], <vscale x 4 x i32> [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP2:%.*]] = mul nuw i64 [[TMP1]], 4
; CHECK-NEXT:    br label %[[BB3:.*]]
; CHECK:       [[BB3]]:
; CHECK-NEXT:    [[TMP4:%.*]] = phi i64 [ 0, [[TMP0:%.*]] ], [ [[TMP10:%.*]], %[[BB3]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = phi <vscale x 4 x float> [ [[A]], [[TMP0]] ], [ [[TMP9:%.*]], %[[BB3]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <vscale x 4 x float> [[TMP5]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 4 x i32> [[B]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP8:%.*]] = call float @llvm.ldexp.f32.i32(float [[TMP6]], i32 [[TMP7]])
; CHECK-NEXT:    [[TMP9]] = insertelement <vscale x 4 x float> [[TMP5]], float [[TMP8]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP10]] = add i64 [[TMP4]], 1
; CHECK-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[TMP10]], [[TMP2]]
; CHECK-NEXT:    br i1 [[TMP11]], label %[[BB12:.*]], label %[[BB3]]
; CHECK:       [[BB12]]:
; CHECK-NEXT:    ret <vscale x 4 x float> [[TMP9]]
;
  %output = call <vscale x 4 x float> @llvm.ldexp.nxv4f32.nxv4i32(<vscale x 4 x float> %a, <vscale x 4 x i32> %b)
  ret <vscale x 4 x float> %output
}

define <vscale x 4 x float> @scalable_vec_powi(<vscale x 4 x float> %a, <vscale x 4 x i32> %b) {
; CHECK-LABEL: define <vscale x 4 x float> @scalable_vec_powi(
; CHECK-SAME: <vscale x 4 x float> [[A:%.*]], <vscale x 4 x i32> [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP2:%.*]] = mul nuw i64 [[TMP1]], 4
; CHECK-NEXT:    br label %[[BB3:.*]]
; CHECK:       [[BB3]]:
; CHECK-NEXT:    [[TMP4:%.*]] = phi i64 [ 0, [[TMP0:%.*]] ], [ [[TMP10:%.*]], %[[BB3]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = phi <vscale x 4 x float> [ [[A]], [[TMP0]] ], [ [[TMP9:%.*]], %[[BB3]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <vscale x 4 x float> [[TMP5]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 4 x i32> [[B]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP8:%.*]] = call float @llvm.powi.f32.i32(float [[TMP6]], i32 [[TMP7]])
; CHECK-NEXT:    [[TMP9]] = insertelement <vscale x 4 x float> [[TMP5]], float [[TMP8]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP10]] = add i64 [[TMP4]], 1
; CHECK-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[TMP10]], [[TMP2]]
; CHECK-NEXT:    br i1 [[TMP11]], label %[[BB12:.*]], label %[[BB3]]
; CHECK:       [[BB12]]:
; CHECK-NEXT:    ret <vscale x 4 x float> [[TMP9]]
;
  %output = call <vscale x 4 x float> @llvm.powi.nxv4f32.nxv4i32(<vscale x 4 x float> %a, <vscale x 4 x i32> %b)
  ret <vscale x 4 x float> %output
}
