// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --filter "^define |^entry:" --version 2
// RUN: %clang_cc1 -triple riscv32 -target-feature +f -target-abi ilp32f -emit-llvm %s -o - \
// RUN:     | FileCheck %s

#include <stdint.h>

// CHECK-LABEL: define dso_local void @f_fpr_tracking
// CHECK-SAME: (double noundef [[A:%.*]], double noundef [[B:%.*]], double noundef [[C:%.*]], double noundef [[D:%.*]], i8 noundef signext [[E:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK:  entry:
//
void f_fpr_tracking(double a, double b, double c, double d, int8_t e) {}

// Lowering for doubles is unnmodified, as 64 > FLEN.

struct double_s { double d; };

// CHECK-LABEL: define dso_local void @f_double_s_arg
// CHECK-SAME: (i64 [[A_COERCE:%.*]]) #[[ATTR0]] {
// CHECK:  entry:
//
void f_double_s_arg(struct double_s a) {}

// CHECK-LABEL: define dso_local i64 @f_ret_double_s
// CHECK-SAME: () #[[ATTR0]] {
// CHECK:  entry:
//
struct double_s f_ret_double_s(void) {
  return (struct double_s){1.0};
}

struct double_double_s { double d; double e; };

// CHECK-LABEL: define dso_local void @f_double_double_s_arg
// CHECK-SAME: (ptr noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK:  entry:
//
void f_double_double_s_arg(struct double_double_s a) {}

// CHECK-LABEL: define dso_local void @f_ret_double_double_s
// CHECK-SAME: (ptr noalias sret([[STRUCT_DOUBLE_DOUBLE_S:%.*]]) align 8 [[AGG_RESULT:%.*]]) #[[ATTR0]] {
// CHECK:  entry:
//
struct double_double_s f_ret_double_double_s(void) {
  return (struct double_double_s){1.0, 2.0};
}

struct double_int8_s { double d; int64_t i; };

struct int_double_s { int a; double b; };

// CHECK-LABEL: define dso_local void @f_int_double_s_arg
// CHECK-SAME: (ptr noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK:  entry:
//
void f_int_double_s_arg(struct int_double_s a) {}

// CHECK-LABEL: define dso_local void @f_ret_int_double_s
// CHECK-SAME: (ptr noalias sret([[STRUCT_INT_DOUBLE_S:%.*]]) align 8 [[AGG_RESULT:%.*]]) #[[ATTR0]] {
// CHECK:  entry:
//
struct int_double_s f_ret_int_double_s(void) {
  return (struct int_double_s){1, 2.0};
}

