// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 3
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv32 -O2 -emit-llvm %s -o - \
// RUN:     | FileCheck %s
// RUN: %clang_cc1 -triple riscv64 -O2 -emit-llvm %s -o - \
// RUN:     | FileCheck %s

// Test RISC-V specific clobbered registers in inline assembly.

// CHECK-LABEL: define dso_local void @test_fflags(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void asm sideeffect "", "~{fflags},~{vl},~{vtype}"() #[[ATTR1:[0-9]+]], !srcloc [[META6:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_fflags(void) {
  asm volatile ("" :::"fflags");
}

// CHECK-LABEL: define dso_local void @test_frm(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void asm sideeffect "", "~{frm},~{vl},~{vtype}"() #[[ATTR1]], !srcloc [[META7:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_frm(void) {
  asm volatile ("" :::"frm");
}

// CHECK-LABEL: define dso_local void @test_vtype(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void asm sideeffect "", "~{vtype},~{vl},~{vtype}"() #[[ATTR1]], !srcloc [[META8:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_vtype(void) {
  asm volatile ("" :::"vtype");
}

// CHECK-LABEL: define dso_local void @test_vl(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void asm sideeffect "", "~{vl},~{vl},~{vtype}"() #[[ATTR1]], !srcloc [[META9:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_vl(void) {
  asm volatile ("" :::"vl");
}

// CHECK-LABEL: define dso_local void @test_vxsat(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void asm sideeffect "", "~{vxsat},~{vl},~{vtype}"() #[[ATTR1]], !srcloc [[META10:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_vxsat(void) {
  asm volatile ("" :::"vxsat");
}

// CHECK-LABEL: define dso_local void @test_vxrm(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void asm sideeffect "", "~{vxrm},~{vl},~{vtype}"() #[[ATTR1]], !srcloc [[META11:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_vxrm(void) {
  asm volatile ("" :::"vxrm");
}
