// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +v \
// RUN: -disable-O0-optnone \
// RUN:  -emit-llvm -o - %s | opt -S -passes=sroa | FileCheck %s
// RUN: %clang_cc1 -triple riscv64 -target-feature +v \
// RUN: -disable-O0-optnone \
// RUN:  -emit-llvm -o - %s | opt -S -passes=sroa | FileCheck %s

// REQUIRES: riscv-registered-target

#include <riscv_vector.h>

// SIGNED INTEGER

// CHECK-LABEL: @eq_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t eq_i32(vint32m1_t a, vint32m1_t b) {
  return a == b;
}

// CHECK-LABEL: @ne_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp ne <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t ne_i32(vint32m1_t a, vint32m1_t b) {
  return a != b;
}

// CHECK-LABEL: @slt_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t slt_i32(vint32m1_t a, vint32m1_t b) {
  return a < b;
}

// CHECK-LABEL: @sgt_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp sgt <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t sgt_i32(vint32m1_t a, vint32m1_t b) {
  return a > b;
}

// CHECK-LABEL: @sle_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp sle <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t sle_i32(vint32m1_t a, vint32m1_t b) {
  return a <= b;
}

// CHECK-LABEL: @sge_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp sge <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t sge_i32(vint32m1_t a, vint32m1_t b) {
  return a >= b;
}

// UNSIGNED INTEGER

// CHECK-LABEL: @eq_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t eq_u32(vuint32m1_t a, vuint32m1_t b) {
  return a == b;
}

// CHECK-LABEL: @ne_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp ne <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t ne_u32(vuint32m1_t a, vuint32m1_t b) {
  return a != b;
}

// CHECK-LABEL: @ult_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp ult <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t ult_u32(vuint32m1_t a, vuint32m1_t b) {
  return a < b;
}

// CHECK-LABEL: @ugt_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp ugt <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t ugt_u32(vuint32m1_t a, vuint32m1_t b) {
  return a > b;
}

// CHECK-LABEL: @ule_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp ule <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t ule_u32(vuint32m1_t a, vuint32m1_t b) {
  return a <= b;
}

// CHECK-LABEL: @uge_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp uge <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t uge_u32(vuint32m1_t a, vuint32m1_t b) {
  return a >= b;
}

// FLOATING POINT
//
// C operators produce ordered comparisons for relational ops and == (oeq),
// and unordered for != (une).  There is no C operator that produces the
// remaining unordered predicates (ueq, ult, ugt, ule, uge) or ordered
// not-equal (one) on vector types.

// CHECK-LABEL: @oeq_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t oeq_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a == b;
}

// CHECK-LABEL: @une_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = fcmp une <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t une_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a != b;
}

// CHECK-LABEL: @olt_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = fcmp olt <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t olt_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a < b;
}

// CHECK-LABEL: @ogt_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = fcmp ogt <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t ogt_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a > b;
}

// CHECK-LABEL: @ole_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = fcmp ole <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t ole_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a <= b;
}

// CHECK-LABEL: @oge_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = fcmp oge <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext <vscale x 2 x i1> [[CMP]] to <vscale x 2 x i32>
// CHECK-NEXT:    ret <vscale x 2 x i32> [[CONV]]
//
vint32m1_t oge_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a >= b;
}

// BOOLEAN

// CHECK-LABEL: @eq_bool(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq <vscale x 1 x i1> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i1> [[CMP]]
//
vbool64_t eq_bool(vbool64_t a, vbool64_t b) {
  return a == b;
}

// CHECK-LABEL: @ne_bool(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp ne <vscale x 1 x i1> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i1> [[CMP]]
//
vbool64_t ne_bool(vbool64_t a, vbool64_t b) {
  return a != b;
}

// CHECK-LABEL: @ult_bool(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp ult <vscale x 1 x i1> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i1> [[CMP]]
//
vbool64_t ult_bool(vbool64_t a, vbool64_t b) {
  return a < b;
}

// CHECK-LABEL: @ugt_bool(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp ugt <vscale x 1 x i1> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i1> [[CMP]]
//
vbool64_t ugt_bool(vbool64_t a, vbool64_t b) {
  return a > b;
}

// CHECK-LABEL: @ule_bool(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp ule <vscale x 1 x i1> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i1> [[CMP]]
//
vbool64_t ule_bool(vbool64_t a, vbool64_t b) {
  return a <= b;
}

// CHECK-LABEL: @uge_bool(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp uge <vscale x 1 x i1> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i1> [[CMP]]
//
vbool64_t uge_bool(vbool64_t a, vbool64_t b) {
  return a >= b;
}
