// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +v \
// RUN: -disable-O0-optnone \
// RUN:  -emit-llvm -o - %s | opt -S -passes=sroa | FileCheck %s
// RUN: %clang_cc1 -triple riscv64 -target-feature +v \
// RUN: -disable-O0-optnone \
// RUN:  -emit-llvm -o - %s | opt -S -passes=sroa | FileCheck %s

// REQUIRES: riscv-registered-target

#include <riscv_vector.h>

// SIGNED INTEGER

// CHECK-LABEL: @add_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[ADD]]
//
vint32m1_t add_i32(vint32m1_t a, vint32m1_t b) {
  return a + b;
}

// CHECK-LABEL: @sub_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SUB]]
//
vint32m1_t sub_i32(vint32m1_t a, vint32m1_t b) {
  return a - b;
}

// CHECK-LABEL: @mul_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[MUL]]
//
vint32m1_t mul_i32(vint32m1_t a, vint32m1_t b) {
  return a * b;
}

// CHECK-LABEL: @sdiv_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[DIV]]
//
vint32m1_t sdiv_i32(vint32m1_t a, vint32m1_t b) {
  return a / b;
}

// CHECK-LABEL: @srem_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[REM]]
//
vint32m1_t srem_i32(vint32m1_t a, vint32m1_t b) {
  return a % b;
}

// CHECK-LABEL: @neg_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 2 x i32> zeroinitializer, [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SUB]]
//
vint32m1_t neg_i32(vint32m1_t a) {
  return -a;
}

// UNSIGNED INTEGER

// CHECK-LABEL: @add_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[ADD]]
//
vuint32m1_t add_u32(vuint32m1_t a, vuint32m1_t b) {
  return a + b;
}

// CHECK-LABEL: @udiv_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = udiv <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[DIV]]
//
vuint32m1_t udiv_u32(vuint32m1_t a, vuint32m1_t b) {
  return a / b;
}

// CHECK-LABEL: @urem_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = urem <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[REM]]
//
vuint32m1_t urem_u32(vuint32m1_t a, vuint32m1_t b) {
  return a % b;
}

// FLOATING POINT

// CHECK-LABEL: @fadd_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = fadd <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[ADD]]
//
vfloat32m1_t fadd_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a + b;
}

// CHECK-LABEL: @fsub_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = fsub <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[SUB]]
//
vfloat32m1_t fsub_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a - b;
}

// CHECK-LABEL: @fmul_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = fmul <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[MUL]]
//
vfloat32m1_t fmul_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a * b;
}

// CHECK-LABEL: @fdiv_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = fdiv <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[DIV]]
//
vfloat32m1_t fdiv_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a / b;
}

// CHECK-LABEL: @fneg_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[FNEG:%.*]] = fneg <vscale x 2 x float> [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[FNEG]]
//
vfloat32m1_t fneg_f32(vfloat32m1_t a) {
  return -a;
}

// 64-BIT ELEMENT

// CHECK-LABEL: @add_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[ADD]]
//
vint64m1_t add_i64(vint64m1_t a, vint64m1_t b) {
  return a + b;
}

// CHECK-LABEL: @sdiv_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[DIV]]
//
vint64m1_t sdiv_i64(vint64m1_t a, vint64m1_t b) {
  return a / b;
}

// CHECK-LABEL: @udiv_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = udiv <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[DIV]]
//
vuint64m1_t udiv_u64(vuint64m1_t a, vuint64m1_t b) {
  return a / b;
}

// DIFFERENT LMUL

// CHECK-LABEL: @add_i32_m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 4 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i32> [[ADD]]
//
vint32m2_t add_i32_m2(vint32m2_t a, vint32m2_t b) {
  return a + b;
}

// SCALAR SPLAT

// CHECK-LABEL: @add_scalar_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[ADD]]
//
vint32m1_t add_scalar_i32(vint32m1_t a, int b) {
  return a + b;
}

// CHECK-LABEL: @add_scalar_lhs_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[A:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 2 x i32> [[SPLAT_SPLAT]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[ADD]]
//
vint32m1_t add_scalar_lhs_i32(int a, vint32m1_t b) {
  return a + b;
}

// CHECK-LABEL: @mul_scalar_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[MUL]]
//
vuint32m1_t mul_scalar_u32(vuint32m1_t a, unsigned b) {
  return a * b;
}

// CHECK-LABEL: @fsub_scalar_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x float> poison, float [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x float> [[SPLAT_SPLATINSERT]], <vscale x 2 x float> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[SUB:%.*]] = fsub <vscale x 2 x float> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[SUB]]
//
vfloat32m1_t fsub_scalar_f32(vfloat32m1_t a, float b) {
  return a - b;
}

// TERNARY

// CHECK-LABEL: @ternary_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[C:%.*]], 0
// CHECK-NEXT:    br i1 [[TOBOOL]], label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]]
// CHECK:       cond.true:
// CHECK-NEXT:    br label [[COND_END:%.*]]
// CHECK:       cond.false:
// CHECK-NEXT:    br label [[COND_END]]
// CHECK:       cond.end:
// CHECK-NEXT:    [[COND:%.*]] = phi <vscale x 2 x i32> [ [[A:%.*]], [[COND_TRUE]] ], [ [[B:%.*]], [[COND_FALSE]] ]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[COND]]
//
vint32m1_t ternary_i32(int c, vint32m1_t a, vint32m1_t b) {
  return c ? a : b;
}

// COMPOUND ASSIGNMENT

// CHECK-LABEL: @compound_add_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[ADD]]
//
vint32m1_t compound_add_i32(vint32m1_t a, vint32m1_t b) {
  a += b;
  return a;
}
