; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=simplifycfg < %s | FileCheck %s

define i1 @bitmap_expand(i32 %type) {
; CHECK-LABEL: define i1 @bitmap_expand(
; CHECK-SAME: i32 [[TYPE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i32 [[TYPE]], 16
; CHECK-NEXT:    [[SWITCH_CAST:%.*]] = trunc i32 [[TYPE]] to i16
; CHECK-NEXT:    [[SWITCH_DOWNSHIFT:%.*]] = lshr i16 -32703, [[SWITCH_CAST]]
; CHECK-NEXT:    [[SWITCH_MASKED:%.*]] = trunc i16 [[SWITCH_DOWNSHIFT]] to i1
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[TMP0]], i1 [[SWITCH_MASKED]], i1 false
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[TYPE]], 12
; CHECK-NEXT:    [[SPEC_SELECT:%.*]] = select i1 [[TMP1]], i1 true, i1 [[CMP2]]
; CHECK-NEXT:    ret i1 [[SPEC_SELECT]]
;
entry:
  %0 = icmp ult i32 %type, 16
  %switch.cast = trunc i32 %type to i16
  %switch.downshift = lshr i16 -32703, %switch.cast
  %switch.masked = trunc i16 %switch.downshift to i1
  %1 = select i1 %0, i1 %switch.masked, i1 false
  br i1 %1, label %exit, label %other.cmp

other.cmp:
  %cmp2 = icmp eq i32 %type, 12
  br label %exit

exit:
  %ret.val = phi i1 [ true, %entry ], [ %cmp2, %other.cmp ]
  ret i1 %ret.val
}

define i1 @bitmap_expand_wide(i32 %type) {
; CHECK-LABEL: define i1 @bitmap_expand_wide(
; CHECK-SAME: i32 [[TYPE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i32 [[TYPE]], 16
; CHECK-NEXT:    [[SWITCH_CAST:%.*]] = trunc i32 [[TYPE]] to i16
; CHECK-NEXT:    [[SWITCH_DOWNSHIFT:%.*]] = lshr i16 -32703, [[SWITCH_CAST]]
; CHECK-NEXT:    [[SWITCH_MASKED:%.*]] = trunc i16 [[SWITCH_DOWNSHIFT]] to i1
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[TMP0]], i1 [[SWITCH_MASKED]], i1 false
; CHECK-NEXT:    br i1 [[TMP1]], label %[[EXIT:.*]], label %[[OTHER_CMP:.*]]
; CHECK:       [[OTHER_CMP]]:
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[TYPE]], 19
; CHECK-NEXT:    [[CMP3:%.*]] = icmp eq i32 [[TYPE]], 23
; CHECK-NEXT:    [[CMP_OR:%.*]] = or i1 [[CMP2]], [[CMP3]]
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RET_VAL:%.*]] = phi i1 [ true, %[[ENTRY]] ], [ [[CMP_OR]], %[[OTHER_CMP]] ]
; CHECK-NEXT:    ret i1 [[RET_VAL]]
;
entry:
  %0 = icmp ult i32 %type, 16
  %switch.cast = trunc i32 %type to i16
  %switch.downshift = lshr i16 -32703, %switch.cast
  %switch.masked = trunc i16 %switch.downshift to i1
  %1 = select i1 %0, i1 %switch.masked, i1 false
  br i1 %1, label %exit, label %other.cmp

other.cmp:
  %cmp2 = icmp eq i32 %type, 19
  %cmp3 = icmp eq i32 %type, 23
  %cmp.or = or i1 %cmp2, %cmp3
  br label %exit

exit:
  %ret.val = phi i1 [ true, %entry ], [ %cmp.or, %other.cmp ]
  ret i1 %ret.val
}

define i1 @bitmap_expand_deep(i32 %type) {
; CHECK-LABEL: define i1 @bitmap_expand_deep(
; CHECK-SAME: i32 [[TYPE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i32 [[TYPE]], 16
; CHECK-NEXT:    [[SWITCH_CAST:%.*]] = trunc i32 [[TYPE]] to i16
; CHECK-NEXT:    [[SWITCH_DOWNSHIFT:%.*]] = lshr i16 -32703, [[SWITCH_CAST]]
; CHECK-NEXT:    [[SWITCH_MASKED:%.*]] = trunc i16 [[SWITCH_DOWNSHIFT]] to i1
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[TMP0]], i1 [[SWITCH_MASKED]], i1 false
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[TYPE]], 19
; CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[TMP1]], [[CMP2]]
; CHECK-NEXT:    [[CMP3:%.*]] = icmp eq i32 [[TYPE]], 31
; CHECK-NEXT:    [[RET_VAL:%.*]] = select i1 [[OR_COND]], i1 true, i1 [[CMP3]]
; CHECK-NEXT:    ret i1 [[RET_VAL]]
;
entry:
  %0 = icmp ult i32 %type, 16
  %switch.cast = trunc i32 %type to i16
  %switch.downshift = lshr i16 -32703, %switch.cast
  %switch.masked = trunc i16 %switch.downshift to i1
  %1 = select i1 %0, i1 %switch.masked, i1 false
  br i1 %1, label %exit, label %other.cmp

other.cmp:
  %cmp2 = icmp eq i32 %type, 19
  br i1 %cmp2, label %exit, label %another.cmp

another.cmp:
  %cmp3 = icmp eq i32 %type, 31
  br label %exit

exit:
  %ret.val = phi i1 [ true, %entry ], [ true, %other.cmp ], [ %cmp3, %another.cmp ]
  ret i1 %ret.val
}
