; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=simplifycfg -S | FileCheck %s


declare void @use()

; Reduced from _ZN12_GLOBAL__N_116AArch64AsmParser20parseRegisterInRangeERjjjj @ llvm/AArch64AsmParser.ll
define fastcc i1 @foo(i1 %v) {
; CHECK-LABEL: define fastcc i1 @foo(
; CHECK-SAME: i1 [[V:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[SELECT:%.*]] = select i1 [[V]], i8 3, i8 2
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i8 [[SELECT]], 0
; CHECK-NEXT:    br i1 [[COND]], label %[[TRUEBB:.*]], label %[[COMMON_RET:.*]]
; CHECK:       [[COMMON_RET]]:
; CHECK-NEXT:    [[COMMON_RET_OP:%.*]] = phi i1 [ true, %[[TRUEBB]] ], [ false, %[[ENTRY]] ]
; CHECK-NEXT:    ret i1 [[COMMON_RET_OP]]
; CHECK:       [[TRUEBB]]:
; CHECK-NEXT:    call void @use()
; CHECK-NEXT:    br label %[[COMMON_RET]]
;
entry:
  %select = select i1 %v, i8 3, i8 2
  %cond = icmp eq i8 %select, 0
  br i1 %cond, label %TrueBB, label %FalseBB

TrueBB:                                           ; preds = %entry
  call void @use()
  ret i1 true

FalseBB:                                          ; preds = %entry
  ret i1 false
}
