; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes='simplifycfg<no-keep-loops>' < %s | FileCheck %s

declare void @barrier() convergent

define void @preserve_loop_header_branch(i32 %tid, ptr %ptr) convergent {
; CHECK-LABEL: define void @preserve_loop_header_branch(
; CHECK-SAME: i32 [[TID:%.*]], ptr [[PTR:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i32 [[TID]], 0
; CHECK-NEXT:    call void @barrier()
; CHECK-NEXT:    br i1 [[COND]], label %[[OUTER_THEN:.*]], label %[[LOOP_HEADER:.*]]
; CHECK:       [[OUTER_THEN]]:
; CHECK-NEXT:    store i32 1, ptr [[PTR]], align 4
; CHECK-NEXT:    br label %[[LOOP_THEN:.*]]
; CHECK:       [[LOOP_THEN]]:
; CHECK-NEXT:    store i32 2, ptr [[PTR]], align 4
; CHECK-NEXT:    br label %[[LOOP_HEADER]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    call void @barrier()
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP_THEN]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %cond = icmp eq i32 %tid, 0
  br label %outer

outer:
  call void @barrier()
  br i1 %cond, label %outer.then, label %loop.header

outer.then:
  store i32 1, ptr %ptr, align 4
  br label %loop.header

loop.header:
  br i1 %cond, label %loop.then, label %loop.body

loop.then:
  store i32 2, ptr %ptr, align 4
  br label %loop.body

loop.body:
  call void @barrier()
  br i1 %cond, label %loop.header, label %exit

exit:
  ret void
}
