; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=simplifycfg -simplifycfg-require-and-preserve-domtree=1 -S | FileCheck %s

define i1 @a_and_b(i1 %a) {
; CHECK-LABEL: define i1 @a_and_b(
; CHECK-SAME: i1 [[A:%.*]]) {
; CHECK-NEXT:  [[START:.*]]:
; CHECK-NEXT:    br i1 [[A]], label %[[A_IS_TRUE:.*]], label %[[END:.*]]
; CHECK:       [[A_IS_TRUE]]:
; CHECK-NEXT:    [[B:%.*]] = call i1 @get_b()
; CHECK-NEXT:    [[SPEC_SELECT:%.*]] = select i1 [[B]], i1 true, i1 false
; CHECK-NEXT:    br label %[[END]]
; CHECK:       [[END]]:
; CHECK-NEXT:    [[RETVAL:%.*]] = phi i1 [ false, %[[START]] ], [ [[SPEC_SELECT]], %[[A_IS_TRUE]] ]
; CHECK-NEXT:    ret i1 [[RETVAL]]
;
start:
  br i1 %a, label %a_is_true, label %a_or_b_is_false

a_is_true:
  %b = call i1 @get_b()
  br i1 %b, label %end, label %a_or_b_is_false

a_or_b_is_false:
  br label %end

end:
  %retval = phi i1 [ true, %a_is_true ], [ false, %a_or_b_is_false ]
  ret i1 %retval
}

declare i1 @get_b()

define void @func_143(i32 %0, ptr %g_329) {
; CHECK-LABEL: define void @func_143(
; CHECK-SAME: i32 [[TMP0:%.*]], ptr [[G_329:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    switch i32 [[TMP0]], label %[[COMMON_RET:.*]] [
; CHECK-NEXT:      i32 0, label %[[FOR_INC295:.*]]
; CHECK-NEXT:      i32 1, label %[[FOR_END297:.*]]
; CHECK-NEXT:      i32 33, label %[[FOR_INC295]]
; CHECK-NEXT:    ]
; CHECK:       [[FOR_INC295]]:
; CHECK-NEXT:    br label %[[FOR_END297]]
; CHECK:       [[COMMON_RET]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_END297]]:
; CHECK-NEXT:    [[STOREMERGE739_LCSSA761:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ 1, %[[FOR_INC295]] ]
; CHECK-NEXT:    store i8 0, ptr [[G_329]], align 1
; CHECK-NEXT:    br label %[[COMMON_RET]]
;
entry:
  switch i32 %0, label %common.ret [
  i32 0, label %for.inc295
  i32 1, label %for.end297
  i32 33, label %for.inc295
  ]

for.inc295:                                       ; preds = %entry, %entry
  br label %for.end297

common.ret:                                       ; preds = %for.end297, %entry
  ret void

for.end297:                                       ; preds = %for.inc295, %entry
  %storemerge739.lcssa761 = phi i64 [ 0, %entry ], [ 1, %for.inc295 ]
  store i8 0, ptr %g_329, align 1
  br label %common.ret
}
