; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -S -passes=simplifycfg < %s | FileCheck %s

; Tests from PR67342
define i16 @test1(i32 %err) {
; CHECK-LABEL: define i16 @test1(
; CHECK-SAME: i32 [[ERR:%.*]]) {
; CHECK-NEXT:  bb3:
; CHECK-NEXT:    [[_3:%.*]] = icmp slt i32 [[ERR]], 0
; CHECK-NEXT:    [[OK:%.*]] = trunc i32 [[ERR]] to i16
; CHECK-NEXT:    ret i16 [[OK]]
;
  %_3 = icmp slt i32 %err, 0
  br i1 %_3, label %bb1, label %bb2

bb2:
  %ok = trunc i32 %err to i16
  br label %bb3

bb1:
  br label %bb3

bb3:
  %r.sroa.3.0 = phi i16 [ undef, %bb1 ], [ %ok, %bb2 ]
  ret i16 %r.sroa.3.0
}

; commuted test
define i16 @test2(i32 %err) {
; CHECK-LABEL: define i16 @test2(
; CHECK-SAME: i32 [[ERR:%.*]]) {
; CHECK-NEXT:  bb3:
; CHECK-NEXT:    [[_3:%.*]] = icmp slt i32 [[ERR]], 0
; CHECK-NEXT:    [[OK:%.*]] = trunc i32 [[ERR]] to i16
; CHECK-NEXT:    ret i16 [[OK]]
;
  %_3 = icmp slt i32 %err, 0
  br i1 %_3, label %bb1, label %bb2

bb2:
  br label %bb3

bb1:
  %ok = trunc i32 %err to i16
  br label %bb3

bb3:
  %r.sroa.3.0 = phi i16 [ %ok, %bb1 ], [ undef, %bb2 ]
  ret i16 %r.sroa.3.0
}
