; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=simplifycfg < %s | FileCheck %s

; Verify SimplifyCFG does not speculate loads through non-noop addrspacecasts.

target datalayout = "e-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-n8:16:32:64-G1"

define i32 @no_speculate_addrspacecast_load(ptr addrspace(4) noalias nocapture readonly dereferenceable(4) %p) {
; CHECK-LABEL: define i32 @no_speculate_addrspacecast_load(
; CHECK-SAME: ptr addrspace(4) noalias readonly captures(none) dereferenceable(4) [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr addrspace(4) [[P]] to i64
; CHECK-NEXT:    [[TMP1:%.*]] = lshr i64 [[TMP0]], 61
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i64 [[TMP1]], 2
; CHECK-NEXT:    br i1 [[COND]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[TMP2:%.*]] = addrspacecast ptr addrspace(4) [[P]] to ptr addrspace(3)
; CHECK-NEXT:    [[LOAD1:%.*]] = load i32, ptr addrspace(3) [[TMP2]], align 1
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    [[TMP3:%.*]] = addrspacecast ptr addrspace(4) [[P]] to ptr addrspace(1)
; CHECK-NEXT:    [[LOAD2:%.*]] = load i32, ptr addrspace(1) [[TMP3]], align 1
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RESULT:%.*]] = phi i32 [ [[LOAD1]], %[[THEN]] ], [ [[LOAD2]], %[[ELSE]] ]
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[RESULT]], 1
; CHECK-NEXT:    ret i32 [[ADD]]
;
entry:
  %0 = ptrtoint ptr addrspace(4) %p to i64
  %1 = lshr i64 %0, 61
  switch i64 %1, label %else [
  i64 2, label %then
  ]

then:
  %2 = addrspacecast ptr addrspace(4) %p to ptr addrspace(3)
  %load1 = load i32, ptr addrspace(3) %2, align 1
  br label %exit

else:
  %3 = addrspacecast ptr addrspace(4) %p to ptr addrspace(1)
  %load2 = load i32, ptr addrspace(1) %3, align 1
  br label %exit

exit:
  %result = phi i32 [ %load1, %then ], [ %load2, %else ]
  %add = add nsw i32 %result, 1
  ret i32 %add
}
