; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt < %s -passes=simplifycfg -simplifycfg-require-and-preserve-domtree=1 -S | FileCheck %s

define i1 @test(i32 %c) {
; CHECK-LABEL: define i1 @test(
; CHECK-SAME: i32 [[C:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    switch i32 [[C]], label [[BB8:%.*]] [
; CHECK-NEXT:      i32 115, label [[BB9:%.*]]
; CHECK-NEXT:      i32 109, label [[BB9]]
; CHECK-NEXT:      i32 104, label [[BB9]]
; CHECK-NEXT:      i32 100, label [[BB9]]
; CHECK-NEXT:    ]
; CHECK:       bb8:
; CHECK-NEXT:    br label [[BB9]]
; CHECK:       bb9:
; CHECK-NEXT:    [[_3_0:%.*]] = phi i1 [ false, [[BB8]] ], [ true, [[ENTRY:%.*]] ], [ true, [[ENTRY]] ], [ true, [[ENTRY]] ], [ true, [[ENTRY]] ]
; CHECK-NEXT:    [[_12:%.*]] = icmp eq i32 [[C]], 119
; CHECK-NEXT:    [[SPEC_SELECT:%.*]] = select i1 [[_3_0]], i1 true, i1 [[_12]]
; CHECK-NEXT:    ret i1 [[SPEC_SELECT]]
;
entry:
  %i1 = icmp eq i32 %c, 115
  br i1 %i1, label %bb12, label %bb11

bb11:                                             ; preds = %entry
  %_6 = icmp eq i32 %c, 109
  br label %bb12

bb12:                                             ; preds = %entry, %bb11
  %_4.0 = phi i1 [ %_6, %bb11 ], [ true, %entry ]
  br i1 %_4.0, label %bb9, label %bb8

bb8:                                              ; preds = %bb12
  %_8 = icmp eq i32 %c, 104
  br label %bb9

bb9:                                              ; preds = %bb12, %bb8
  %_3.0 = phi i1 [ %_8, %bb8 ], [ true, %bb12 ]
  br i1 %_3.0, label %bb6, label %bb5

bb5:                                              ; preds = %bb9
  %_10 = icmp eq i32 %c, 100
  br label %bb6

bb6:                                              ; preds = %bb9, %bb5
  %_2.0 = phi i1 [ %_10, %bb5 ], [ true, %bb9 ]
  br i1 %_2.0, label %bb3, label %bb2

bb2:                                              ; preds = %bb6
  %_12 = icmp eq i32 %c, 119
  br label %bb3

bb3:                                              ; preds = %bb6, %bb2
  %i.0 = phi i1 [ %_12, %bb2 ], [ true, %bb6 ]
  ret i1 %i.0
}
