; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=simplifycfg -simplifycfg-require-and-preserve-domtree=1 < %s | FileCheck %s

; See https://github.com/llvm/llvm-project/issues/56087

; Test that branching on an icmp chain is converted to a switch
define i32 @branch_icmp_chain(i32 %c){
; CHECK-LABEL: define i32 @branch_icmp_chain(
; CHECK-SAME: i32 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    switch i32 [[C]], label %[[IF_ELSE:.*]] [
; CHECK-NEXT:      i32 119, label %[[CLEANUP:.*]]
; CHECK-NEXT:      i32 111, label %[[CLEANUP]]
; CHECK-NEXT:      i32 108, label %[[CLEANUP]]
; CHECK-NEXT:      i32 104, label %[[CLEANUP]]
; CHECK-NEXT:      i32 101, label %[[CLEANUP]]
; CHECK-NEXT:      i32 0, label %[[CLEANUP]]
; CHECK-NEXT:    ]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    br label %[[CLEANUP]]
; CHECK:       [[CLEANUP]]:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ -1, %[[IF_ELSE]] ], [ 1, %[[ENTRY]] ], [ 1, %[[ENTRY]] ], [ 1, %[[ENTRY]] ], [ 1, %[[ENTRY]] ], [ 1, %[[ENTRY]] ], [ 1, %[[ENTRY]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %cmp1 = icmp eq i32 %c, 101
  %0 = and i32 %c, -5
  %1 = icmp eq i32 %0, 104
  %or521 = or i1 %1, %cmp1
  %cmp6 = icmp eq i32 %c, 111
  %or822 = or i1 %or521, %cmp6
  %cmp9 = icmp eq i32 %c, 119
  %or1123 = or i1 %or822, %cmp9
  %cmp12 = icmp eq i32 %c, 0
  %or1424 = or i1 %or1123, %cmp12
  br i1 %or1424, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  br label %cleanup

if.else:                                          ; preds = %entry
  br label %cleanup

cleanup:                                          ; preds = %if.else, %if.then
  %retval.0 = phi i32 [ 1, %if.then ], [ -1, %if.else ]
  ret i32 %retval.0
}

; Test that returning an icmp chain directly is converted to a switch
define i1 @return_icmp_chain(i32 %c) {
; CHECK-LABEL: define i1 @return_icmp_chain(
; CHECK-SAME: i32 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    switch i32 [[C]], label %[[RET_FALSE:.*]] [
; CHECK-NEXT:      i32 119, label %[[SWITCH_RETURN:.*]]
; CHECK-NEXT:      i32 111, label %[[SWITCH_RETURN]]
; CHECK-NEXT:      i32 108, label %[[SWITCH_RETURN]]
; CHECK-NEXT:      i32 104, label %[[SWITCH_RETURN]]
; CHECK-NEXT:      i32 101, label %[[SWITCH_RETURN]]
; CHECK-NEXT:      i32 0, label %[[SWITCH_RETURN]]
; CHECK-NEXT:    ]
; CHECK:       [[RET_FALSE]]:
; CHECK-NEXT:    br label %[[SWITCH_RETURN]]
; CHECK:       [[SWITCH_RETURN]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ false, %[[RET_FALSE]] ], [ true, %[[ENTRY]] ], [ true, %[[ENTRY]] ], [ true, %[[ENTRY]] ], [ true, %[[ENTRY]] ], [ true, %[[ENTRY]] ], [ true, %[[ENTRY]] ]
; CHECK-NEXT:    ret i1 [[TMP0]]
;
entry:
  %cmp1 = icmp eq i32 %c, 101
  %0 = and i32 %c, -5
  %1 = icmp eq i32 %0, 104
  %or521 = or i1 %1, %cmp1
  %cmp6 = icmp eq i32 %c, 111
  %or822 = or i1 %or521, %cmp6
  %cmp9 = icmp eq i32 %c, 119
  %or1123 = or i1 %or822, %cmp9
  %cmp12 = icmp eq i32 %c, 0
  %or1424 = or i1 %or1123, %cmp12
  ret i1 %or1424
}

; Test that a select with icmp chain condition is converted to a switch
define i32 @select_icmp_chain(i32 %c) {
; CHECK-LABEL: define i32 @select_icmp_chain(
; CHECK-SAME: i32 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    switch i32 [[C]], label %[[RET_FALSE:.*]] [
; CHECK-NEXT:      i32 119, label %[[SWITCH_RETURN:.*]]
; CHECK-NEXT:      i32 111, label %[[SWITCH_RETURN]]
; CHECK-NEXT:      i32 108, label %[[SWITCH_RETURN]]
; CHECK-NEXT:      i32 104, label %[[SWITCH_RETURN]]
; CHECK-NEXT:      i32 101, label %[[SWITCH_RETURN]]
; CHECK-NEXT:      i32 0, label %[[SWITCH_RETURN]]
; CHECK-NEXT:    ]
; CHECK:       [[RET_FALSE]]:
; CHECK-NEXT:    br label %[[SWITCH_RETURN]]
; CHECK:       [[SWITCH_RETURN]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i32 [ -1, %[[RET_FALSE]] ], [ 1, %[[ENTRY]] ], [ 1, %[[ENTRY]] ], [ 1, %[[ENTRY]] ], [ 1, %[[ENTRY]] ], [ 1, %[[ENTRY]] ], [ 1, %[[ENTRY]] ]
; CHECK-NEXT:    ret i32 [[TMP0]]
;
entry:
  %cmp1 = icmp eq i32 %c, 101
  %0 = and i32 %c, -5
  %1 = icmp eq i32 %0, 104
  %or521 = or i1 %1, %cmp1
  %cmp6 = icmp eq i32 %c, 111
  %or822 = or i1 %or521, %cmp6
  %cmp9 = icmp eq i32 %c, 119
  %or1123 = or i1 %or822, %cmp9
  %cmp12 = icmp eq i32 %c, 0
  %or1424 = or i1 %or1123, %cmp12
  %cond = select i1 %or1424, i32 1, i32 -1
  ret i32 %cond
}

; Test that branch weights on select are preserved through the transformation
define i32 @select_icmp_chain_with_prof(i32 %c) {
; CHECK-LABEL: define i32 @select_icmp_chain_with_prof(
; CHECK-SAME: i32 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    switch i32 [[C]], label %[[RET_FALSE:.*]] [
; CHECK-NEXT:      i32 119, label %[[SWITCH_RETURN:.*]]
; CHECK-NEXT:      i32 111, label %[[SWITCH_RETURN]]
; CHECK-NEXT:      i32 108, label %[[SWITCH_RETURN]]
; CHECK-NEXT:      i32 104, label %[[SWITCH_RETURN]]
; CHECK-NEXT:      i32 101, label %[[SWITCH_RETURN]]
; CHECK-NEXT:      i32 0, label %[[SWITCH_RETURN]]
; CHECK-NEXT:    ], !prof [[PROF0:![0-9]+]]
; CHECK:       [[RET_FALSE]]:
; CHECK-NEXT:    br label %[[SWITCH_RETURN]]
; CHECK:       [[SWITCH_RETURN]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i32 [ -1, %[[RET_FALSE]] ], [ 1, %[[ENTRY]] ], [ 1, %[[ENTRY]] ], [ 1, %[[ENTRY]] ], [ 1, %[[ENTRY]] ], [ 1, %[[ENTRY]] ], [ 1, %[[ENTRY]] ]
; CHECK-NEXT:    ret i32 [[TMP0]]
;
entry:
  %cmp1 = icmp eq i32 %c, 101
  %0 = and i32 %c, -5
  %1 = icmp eq i32 %0, 104
  %or521 = or i1 %1, %cmp1
  %cmp6 = icmp eq i32 %c, 111
  %or822 = or i1 %or521, %cmp6
  %cmp9 = icmp eq i32 %c, 119
  %or1123 = or i1 %or822, %cmp9
  %cmp12 = icmp eq i32 %c, 0
  %or1424 = or i1 %or1123, %cmp12
  %cond = select i1 %or1424, i32 1, i32 -1, !prof !0
  ret i32 %cond
}

!0 = !{!"branch_weights", i32 600, i32 100}
;.
; CHECK: [[PROF0]] = !{!"branch_weights", i32 100, i32 100, i32 100, i32 100, i32 100, i32 100, i32 100}
;.
