; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mips64-elf -O2 -mcpu=mips64r2 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=R2-O2
; RUN: llc -mtriple=mips64-elf -O3 -mcpu=mips64r2 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=R2-O3
; RUN: llc -mtriple=mips64el-elf -O2 -mcpu=mips64r2 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=R2-O2
; RUN: llc -mtriple=mips64el-elf -O3 -mcpu=mips64r2 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=R2-O3
; RUN: llc -mtriple=mips64-elf -O2 -mcpu=mips64r6 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=R6-O2
; RUN: llc -mtriple=mips64-elf -O3 -mcpu=mips64r6 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=R6-O3
; RUN: llc -mtriple=mips64el-elf -O2 -mcpu=mips64r6 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=R6-O2
; RUN: llc -mtriple=mips64el-elf -O3 -mcpu=mips64r6 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=R6-O3

declare void @exit(i32) noreturn

define void @test_func(ptr %ptr, i32 %val, i1 %cond) nounwind {
; R2-O2-LABEL: test_func:
; R2-O2:       # %bb.0: # %entry
; R2-O2-NEXT:    move $2, $4
; R2-O2-NEXT:    sll $1, $6, 0
; R2-O2-NEXT:    andi $1, $1, 1
; R2-O2-NEXT:    beqz $1, .LBB0_4
; R2-O2-NEXT:    sll $4, $5, 0
; R2-O2-NEXT:  # %bb.1: # %bb5
; R2-O2-NEXT:    .insn
; R2-O2-NEXT:  .LBB0_2: # %bb5
; R2-O2-NEXT:    # =>This Inner Loop Header: Depth=1
; R2-O2-NEXT:    ll $1, 0($2)
; R2-O2-NEXT:    sltu $5, $1, $4
; R2-O2-NEXT:    move $3, $1
; R2-O2-NEXT:    movn $3, $4, $5
; R2-O2-NEXT:    sc $3, 0($2)
; R2-O2-NEXT:    beqz $3, .LBB0_2
; R2-O2-NEXT:    nop
; R2-O2-NEXT:  # %bb.3: # %bb5
; R2-O2-NEXT:    jr $ra
; R2-O2-NEXT:    nop
; R2-O2-NEXT:  .LBB0_4: # %bb4
; R2-O2-NEXT:    daddiu $sp, $sp, -16
; R2-O2-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; R2-O2-NEXT:    jal exit
; R2-O2-NEXT:    nop
;
; R2-O3-LABEL: test_func:
; R2-O3:       # %bb.0: # %entry
; R2-O3-NEXT:    sll $1, $6, 0
; R2-O3-NEXT:    move $2, $4
; R2-O3-NEXT:    andi $1, $1, 1
; R2-O3-NEXT:    beqz $1, .LBB0_4
; R2-O3-NEXT:    sll $4, $5, 0
; R2-O3-NEXT:  # %bb.1: # %bb5
; R2-O3-NEXT:    .insn
; R2-O3-NEXT:  .LBB0_2: # %bb5
; R2-O3-NEXT:    # =>This Inner Loop Header: Depth=1
; R2-O3-NEXT:    ll $1, 0($2)
; R2-O3-NEXT:    sltu $5, $1, $4
; R2-O3-NEXT:    move $3, $1
; R2-O3-NEXT:    movn $3, $4, $5
; R2-O3-NEXT:    sc $3, 0($2)
; R2-O3-NEXT:    beqz $3, .LBB0_2
; R2-O3-NEXT:    nop
; R2-O3-NEXT:  # %bb.3: # %bb5
; R2-O3-NEXT:    jr $ra
; R2-O3-NEXT:    nop
; R2-O3-NEXT:  .LBB0_4: # %bb4
; R2-O3-NEXT:    daddiu $sp, $sp, -16
; R2-O3-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; R2-O3-NEXT:    jal exit
; R2-O3-NEXT:    nop
;
; R6-O2-LABEL: test_func:
; R6-O2:       # %bb.0: # %entry
; R6-O2-NEXT:    move $2, $4
; R6-O2-NEXT:    sll $1, $6, 0
; R6-O2-NEXT:    andi $1, $1, 1
; R6-O2-NEXT:    beqz $1, .LBB0_4
; R6-O2-NEXT:    sll $4, $5, 0
; R6-O2-NEXT:  # %bb.1: # %bb5
; R6-O2-NEXT:    .insn
; R6-O2-NEXT:  .LBB0_2: # %bb5
; R6-O2-NEXT:    # =>This Inner Loop Header: Depth=1
; R6-O2-NEXT:    ll $1, 0($2)
; R6-O2-NEXT:    sltu $5, $1, $4
; R6-O2-NEXT:    seleqz $3, $1, $5
; R6-O2-NEXT:    selnez $5, $4, $5
; R6-O2-NEXT:    or $3, $3, $5
; R6-O2-NEXT:    sc $3, 0($2)
; R6-O2-NEXT:    beqzc $3, .LBB0_2
; R6-O2-NEXT:    nop
; R6-O2-NEXT:  # %bb.3: # %bb5
; R6-O2-NEXT:    jrc $ra
; R6-O2-NEXT:  .LBB0_4: # %bb4
; R6-O2-NEXT:    daddiu $sp, $sp, -16
; R6-O2-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; R6-O2-NEXT:    jal exit
; R6-O2-NEXT:    nop
;
; R6-O3-LABEL: test_func:
; R6-O3:       # %bb.0: # %entry
; R6-O3-NEXT:    sll $1, $6, 0
; R6-O3-NEXT:    move $2, $4
; R6-O3-NEXT:    andi $1, $1, 1
; R6-O3-NEXT:    beqz $1, .LBB0_4
; R6-O3-NEXT:    sll $4, $5, 0
; R6-O3-NEXT:  # %bb.1: # %bb5
; R6-O3-NEXT:    .insn
; R6-O3-NEXT:  .LBB0_2: # %bb5
; R6-O3-NEXT:    # =>This Inner Loop Header: Depth=1
; R6-O3-NEXT:    ll $1, 0($2)
; R6-O3-NEXT:    sltu $5, $1, $4
; R6-O3-NEXT:    seleqz $3, $1, $5
; R6-O3-NEXT:    selnez $5, $4, $5
; R6-O3-NEXT:    or $3, $3, $5
; R6-O3-NEXT:    sc $3, 0($2)
; R6-O3-NEXT:    beqzc $3, .LBB0_2
; R6-O3-NEXT:    nop
; R6-O3-NEXT:  # %bb.3: # %bb5
; R6-O3-NEXT:    jrc $ra
; R6-O3-NEXT:  .LBB0_4: # %bb4
; R6-O3-NEXT:    daddiu $sp, $sp, -16
; R6-O3-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; R6-O3-NEXT:    jal exit
; R6-O3-NEXT:    nop
entry:
  br i1 %cond, label %bb5, label %bb4

bb4:
  call void @exit(i32 %val)
  unreachable

bb5:
  %old = atomicrmw umax ptr %ptr, i32 %val monotonic, align 4
  ret void
}
