; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple mipsisa32r6el-unknown-linux < %s | FileCheck --check-prefixes=CHECK,R6 %s
; RUN: llc -mtriple mipsel-unknown-linux < %s | FileCheck --check-prefixes=CHECK,R2  %s

define float @maxf(float %a, float %b) {
; R6-LABEL: maxf:
; R6:       # %bb.0: # %entry
; R6-NEXT:    jr $ra
; R6-NEXT:    max.s $f0, $f12, $f14
;
; R2-LABEL: maxf:
; R2:       # %bb.0: # %entry
; R2-NEXT:    mov.s $f0, $f14
; R2-NEXT:    c.ult.s $f12, $f14
; R2-NEXT:    jr $ra
; R2-NEXT:    movf.s $f0, $f12, $fcc0
entry:
  %cmp = fcmp nnan nsz oge float %a, %b
  %cond = select nnan nsz i1 %cmp, float %a, float %b
  ret float %cond
}

define float @minf(float %a, float %b) {
; R6-LABEL: minf:
; R6:       # %bb.0: # %entry
; R6-NEXT:    jr $ra
; R6-NEXT:    min.s $f0, $f12, $f14
;
; R2-LABEL: minf:
; R2:       # %bb.0: # %entry
; R2-NEXT:    mov.s $f0, $f14
; R2-NEXT:    c.olt.s $f12, $f14
; R2-NEXT:    jr $ra
; R2-NEXT:    movt.s $f0, $f12, $fcc0
entry:
  %cmp = fcmp nnan nsz olt float %a, %b
  %cond = select nnan nsz i1 %cmp, float %a, float %b
  ret float %cond
}

define double @maxd(double %a, double %b) {
; R6-LABEL: maxd:
; R6:       # %bb.0: # %entry
; R6-NEXT:    jr $ra
; R6-NEXT:    max.d $f0, $f12, $f14
;
; R2-LABEL: maxd:
; R2:       # %bb.0: # %entry
; R2-NEXT:    mov.d $f0, $f14
; R2-NEXT:    c.ult.d $f12, $f14
; R2-NEXT:    jr $ra
; R2-NEXT:    movf.d $f0, $f12, $fcc0
entry:
  %cmp = fcmp nnan nsz oge double %a, %b
  %cond = select nnan nsz i1 %cmp, double %a, double %b
  ret double %cond
}

define double @mind(double %a, double %b) {
; R6-LABEL: mind:
; R6:       # %bb.0: # %entry
; R6-NEXT:    jr $ra
; R6-NEXT:    min.d $f0, $f12, $f14
;
; R2-LABEL: mind:
; R2:       # %bb.0: # %entry
; R2-NEXT:    mov.d $f0, $f14
; R2-NEXT:    c.olt.d $f12, $f14
; R2-NEXT:    jr $ra
; R2-NEXT:    movt.d $f0, $f12, $fcc0
entry:
  %cmp = fcmp nnan nsz olt double %a, %b
  %cond = select nnan nsz i1 %cmp, double %a, double %b
  ret double %cond
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
