; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mipsisa32r6-linux-gnu < %s | FileCheck %s

; test expandFMINNUM_FMAXNUM on backend with FMINNUM_IEEE/FMAXNUM_IEEE.
; N -> not NaN
; S -> not SNaN
; Y -> may be NaN or SNaN

define double @test_maxnumNN(double nofpclass(nan) %f1, double nofpclass(nan) %f2) {
; CHECK-LABEL: test_maxnumNN:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    max.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumSS(double nofpclass(snan) %f1, double nofpclass(snan) %f2) {
; CHECK-LABEL: test_maxnumSS:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    max.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumYY(double nofpclass(zero) %f1, double nofpclass(zero) %f2) {
; CHECK-LABEL: test_maxnumYY:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    max.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumNS(double nofpclass(nan) %f1, double nofpclass(snan) %f2) {
; CHECK-LABEL: test_maxnumNS:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    max.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumNY(double nofpclass(nan) %f1, double nofpclass(zero) %f2) {
; CHECK-LABEL: test_maxnumNY:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    max.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumSN(double nofpclass(snan) %f1, double nofpclass(nan) %f2) {
; CHECK-LABEL: test_maxnumSN:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    max.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumSY(double nofpclass(snan) %f1, double nofpclass(zero) %f2) {
; CHECK-LABEL: test_maxnumSY:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    max.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumYN(double nofpclass(zero) %f1, double nofpclass(nan) %f2) {
; CHECK-LABEL: test_maxnumYN:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    max.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_maxnumYS(double nofpclass(zero) %f1, double nofpclass(snan) %f2) {
; CHECK-LABEL: test_maxnumYS:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    max.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.maxnum.f64(double %f1, double %f2)
  ret double %0
}


define double @test_minnumNN(double nofpclass(nan) %f1, double nofpclass(nan) %f2) {
; CHECK-LABEL: test_minnumNN:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    min.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumSS(double nofpclass(snan) %f1, double nofpclass(snan) %f2) {
; CHECK-LABEL: test_minnumSS:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    min.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumYY(double nofpclass(zero) %f1, double nofpclass(zero) %f2) {
; CHECK-LABEL: test_minnumYY:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    min.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumNS(double nofpclass(nan) %f1, double nofpclass(snan) %f2) {
; CHECK-LABEL: test_minnumNS:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    min.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumNY(double nofpclass(nan) %f1, double nofpclass(zero) %f2) {
; CHECK-LABEL: test_minnumNY:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    min.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumSN(double nofpclass(snan) %f1, double nofpclass(nan) %f2) {
; CHECK-LABEL: test_minnumSN:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    min.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumSY(double nofpclass(snan) %f1, double nofpclass(zero) %f2) {
; CHECK-LABEL: test_minnumSY:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    min.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumYN(double nofpclass(zero) %f1, double nofpclass(nan) %f2) {
; CHECK-LABEL: test_minnumYN:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    min.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

define double @test_minnumYS(double nofpclass(zero) %f1, double nofpclass(snan) %f2) {
; CHECK-LABEL: test_minnumYS:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    min.d $f0, $f12, $f14
entry:
  %0 = tail call double @llvm.minnum.f64(double %f1, double %f2)
  ret double %0
}

