; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=mips -mcpu=mips32r2 < %s | FileCheck %s -check-prefixes=CHECK,CHECK-R2
; RUN: llc -mtriple=mips -mcpu=mips32r6 < %s | FileCheck %s -check-prefixes=CHECK,CHECK-R6
; RUN: llc -mtriple=mips -mcpu=mips32r2 -mattr=+fp64,+fpxx -o - %s | FileCheck %s -check-prefixes=CHECK,CHECK-R2
; RUN: llc -mtriple=mips -mcpu=mips64r2 -o - %s | FileCheck %s -check-prefixes=CHECK,CHECK-R2

; Single-precision intrinsics

define float @add_f32(float %x, float %y) #0 {
; CHECK-R6-LABEL: add_f32:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    add.s $f0, $f12, $f14
  %val = call float @llvm.experimental.constrained.fadd.f32(float %x, float %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @sub_f32(float %x, float %y) #0 {
; CHECK-R6-LABEL: sub_f32:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    sub.s $f0, $f12, $f14
  %val = call float @llvm.experimental.constrained.fsub.f32(float %x, float %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @mul_f32(float %x, float %y) #0 {
; CHECK-R6-LABEL: mul_f32:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    mul.s $f0, $f12, $f14
  %val = call float @llvm.experimental.constrained.fmul.f32(float %x, float %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @div_f32(float %x, float %y) #0 {
; CHECK-R6-LABEL: div_f32:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    div.s $f0, $f12, $f14
  %val = call float @llvm.experimental.constrained.fdiv.f32(float %x, float %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @frem_f32(float %x, float %y) #0 {
; CHECK-LABEL: frem_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal fmodf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.frem.f32(float %x, float %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @fma_f32(float %x, float %y, float %z) #0 {
; CHECK-LABEL: fma_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal fmaf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.fma.f32(float %x, float %y, float %z, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define i32 @fptosi_f32(float %x) #0 {
; CHECK-LABEL: fptosi_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    trunc.w.s $f0, $f12
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    mfc1 $2, $f0
  %val = call i32 @llvm.experimental.constrained.fptosi.i32.f32(float %x, metadata !"fpexcept.strict") #0
  ret i32 %val
}

define i32 @fptoui_f32(float %x) #0 {
; CHECK-R2-LABEL: fptoui_f32:
; CHECK-R2:       # %bb.0:
; CHECK-R2-NEXT:    lui $1, %hi($CPI7_0)
; CHECK-R2-NEXT:    lwc1 $f0, %lo($CPI7_0)($1)
; CHECK-R2-NEXT:    sub.s $f1, $f12, $f0
; CHECK-R2-NEXT:    trunc.w.s $f1, $f1
; CHECK-R2-NEXT:    mfc1 $1, $f1
; CHECK-R2-NEXT:    lui $2, 32768
; CHECK-R2-NEXT:    xor $2, $1, $2
; CHECK-R2-NEXT:    trunc.w.s $f1, $f12
; CHECK-R2-NEXT:    mfc1 $1, $f1
; CHECK-R2-NEXT:    c.olt.s $f12, $f0
; CHECK-R2-NEXT:    jr $ra
; CHECK-R2-NEXT:    movt $2, $1, $fcc0
;
; CHECK-R6-LABEL: fptoui_f32:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    lui $1, %hi($CPI7_0)
; CHECK-R6-NEXT:    lwc1 $f0, %lo($CPI7_0)($1)
; CHECK-R6-NEXT:    cmp.lt.s $f1, $f12, $f0
; CHECK-R6-NEXT:    sub.s $f0, $f12, $f0
; CHECK-R6-NEXT:    trunc.w.s $f0, $f0
; CHECK-R6-NEXT:    mfc1 $1, $f0
; CHECK-R6-NEXT:    lui $2, 32768
; CHECK-R6-NEXT:    xor $1, $1, $2
; CHECK-R6-NEXT:    mfc1 $2, $f1
; CHECK-R6-NEXT:    seleqz $1, $1, $2
; CHECK-R6-NEXT:    trunc.w.s $f0, $f12
; CHECK-R6-NEXT:    mfc1 $3, $f0
; CHECK-R6-NEXT:    selnez $2, $3, $2
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    or $2, $2, $1
  %val = call i32 @llvm.experimental.constrained.fptoui.i32.f32(float %x, metadata !"fpexcept.strict") #0
  ret i32 %val
}

define float @sqrt_f32(float %x) #0 {
; CHECK-LABEL: sqrt_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    sqrt.s $f0, $f12
  %val = call float @llvm.experimental.constrained.sqrt.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @powi_f32(float %x, i32 %y) #0 {
; CHECK-R6-LABEL: powi_f32:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    addiu $sp, $sp, -24
; CHECK-R6-NEXT:    .cfi_def_cfa_offset 24
; CHECK-R6-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-R6-NEXT:    .cfi_offset 31, -4
; CHECK-R6-NEXT:    jal __powisf2
; CHECK-R6-NEXT:    nop
; CHECK-R6-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.powi.f32(float %x, i32 %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @sin_f32(float %x) #0 {
; CHECK-LABEL: sin_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal sinf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.sin.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @cos_f32(float %x) #0 {
; CHECK-LABEL: cos_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal cosf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.cos.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @tan_f32(float %x) #0 {
; CHECK-LABEL: tan_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal tanf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.tan.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @acos_f32(float %x, float %y) #0 {
; CHECK-LABEL: acos_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal acosf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.acos.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @asin_f32(float %x, float %y) #0 {
; CHECK-LABEL: asin_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal asinf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.asin.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @atan_f32(float %x, float %y) #0 {
; CHECK-LABEL: atan_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal atanf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.atan.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @cosh_f32(float %x, float %y) #0 {
; CHECK-LABEL: cosh_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal coshf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.cosh.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @sinh_f32(float %x, float %y) #0 {
; CHECK-LABEL: sinh_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal sinhf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.sinh.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @tanh_f32(float %x, float %y) #0 {
; CHECK-LABEL: tanh_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal tanhf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.tanh.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @fmuladd_f32(float %x, float %y, float %z) #0 {
; CHECK-R6-LABEL: fmuladd_f32:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    mul.s $f0, $f12, $f14
; CHECK-R6-NEXT:    mtc1 $6, $f1
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    add.s $f0, $f0, $f1
  %val = call float @llvm.experimental.constrained.fmuladd.f32(float %x, float %y, float %z, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @ldexp_f32(float %x, i32 %y) #0 {
; CHECK-R6-LABEL: ldexp_f32:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    addiu $sp, $sp, -24
; CHECK-R6-NEXT:    .cfi_def_cfa_offset 24
; CHECK-R6-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-R6-NEXT:    .cfi_offset 31, -4
; CHECK-R6-NEXT:    jal ldexpf
; CHECK-R6-NEXT:    nop
; CHECK-R6-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.ldexp.f32.i32(float %x, i32 %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @roundeven_f32(float %x) #0 {
; CHECK-LABEL: roundeven_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal roundevenf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.roundeven.f32(float %x, metadata !"fpexcept.strict") #0
  ret float %val
}

define float @uitofp_f32_i32(i32 %x) #0 {
; CHECK-R6-LABEL: uitofp_f32_i32:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    addiu $sp, $sp, -8
; CHECK-R6-NEXT:    .cfi_def_cfa_offset 8
; CHECK-R6-NEXT:    sw $4, 4($sp)
; CHECK-R6-NEXT:    lui $1, 17200
; CHECK-R6-NEXT:    sw $1, 0($sp)
; CHECK-R6-NEXT:    lui $1, %hi($CPI22_0)
; CHECK-R6-NEXT:    ldc1 $f0, %lo($CPI22_0)($1)
; CHECK-R6-NEXT:    ldc1 $f1, 0($sp)
; CHECK-R6-NEXT:    sub.d $f0, $f1, $f0
; CHECK-R6-NEXT:    cvt.s.d $f0, $f0
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    addiu $sp, $sp, 8
  %val = call float @llvm.experimental.constrained.uitofp.f32.i32(i32 %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @atan2_f32(float %x, float %y) #0 {
; CHECK-LABEL: atan2_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal atan2f
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.atan2.f32(float %x, float %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @pow_f32(float %x, float %y) #0 {
; CHECK-LABEL: pow_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal powf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.pow.f32(float %x, float %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @log_f32(float %x) #0 {
; CHECK-LABEL: log_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal logf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.log.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @log10_f32(float %x) #0 {
; CHECK-LABEL: log10_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal log10f
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.log10.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @log2_f32(float %x) #0 {
; CHECK-LABEL: log2_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal log2f
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.log2.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @exp_f32(float %x) #0 {
; CHECK-LABEL: exp_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal expf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.exp.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @exp2_f32(float %x) #0 {
; CHECK-LABEL: exp2_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal exp2f
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.exp2.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @rint_f32(float %x) #0 {
; CHECK-LABEL: rint_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal rintf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.rint.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define float @nearbyint_f32(float %x) #0 {
; CHECK-LABEL: nearbyint_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal nearbyintf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.nearbyint.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define i32 @lrint_f32(float %x) #0 {
; CHECK-LABEL: lrint_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal lrintf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call i32 @llvm.experimental.constrained.lrint.i32.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret i32 %val
}

define i32 @llrint_f32(float %x) #0 {
; CHECK-LABEL: llrint_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal llrintf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call i32 @llvm.experimental.constrained.llrint.i32.f32(float %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret i32 %val
}

define float @maxnum_f32(float %x, float %y) #0 {
; CHECK-R2-LABEL: maxnum_f32:
; CHECK-R2:       # %bb.0:
; CHECK-R2-NEXT:    addiu $sp, $sp, -24
; CHECK-R2-NEXT:    .cfi_def_cfa_offset 24
; CHECK-R2-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-R2-NEXT:    .cfi_offset 31, -4
; CHECK-R2-NEXT:    jal fmaxf
; CHECK-R2-NEXT:    nop
; CHECK-R2-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-R2-NEXT:    jr $ra
; CHECK-R2-NEXT:    addiu $sp, $sp, 24
;
; CHECK-R6-LABEL: maxnum_f32:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    max.s $f0, $f12, $f14
  %val = call float @llvm.experimental.constrained.maxnum.f32(float %x, float %y, metadata !"fpexcept.strict") #0
  ret float %val
}

define float @minnum_f32(float %x, float %y) #0 {
; CHECK-R2-LABEL: minnum_f32:
; CHECK-R2:       # %bb.0:
; CHECK-R2-NEXT:    addiu $sp, $sp, -24
; CHECK-R2-NEXT:    .cfi_def_cfa_offset 24
; CHECK-R2-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-R2-NEXT:    .cfi_offset 31, -4
; CHECK-R2-NEXT:    jal fminf
; CHECK-R2-NEXT:    nop
; CHECK-R2-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-R2-NEXT:    jr $ra
; CHECK-R2-NEXT:    addiu $sp, $sp, 24
;
; CHECK-R6-LABEL: minnum_f32:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    min.s $f0, $f12, $f14
  %val = call float @llvm.experimental.constrained.minnum.f32(float %x, float %y, metadata !"fpexcept.strict") #0
  ret float %val
}

define float @ceil_f32(float %x) #0 {
; CHECK-LABEL: ceil_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal ceilf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.ceil.f32(float %x, metadata !"fpexcept.strict") #0
  ret float %val
}

define float @floor_f32(float %x) #0 {
; CHECK-LABEL: floor_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal floorf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.floor.f32(float %x, metadata !"fpexcept.strict") #0
  ret float %val
}

define i32 @lround_f32(float %x) #0 {
; CHECK-LABEL: lround_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal lroundf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call i32 @llvm.experimental.constrained.lround.i32.f32(float %x, metadata !"fpexcept.strict") #0
  ret i32 %val
}

define i32 @llround_f32(float %x) #0 {
; CHECK-LABEL: llround_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal llroundf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call i32 @llvm.experimental.constrained.llround.i32.f32(float %x, metadata !"fpexcept.strict") #0
  ret i32 %val
}

define float @round_f32(float %x) #0 {
; CHECK-LABEL: round_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal roundf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.round.f32(float %x, metadata !"fpexcept.strict") #0
  ret float %val
}

define float @trunc_f32(float %x) #0 {
; CHECK-LABEL: trunc_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal truncf
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call float @llvm.experimental.constrained.trunc.f32(float %x, metadata !"fpexcept.strict") #0
  ret float %val
}

; Double-precision intrinsics

define double @add_f64(double %x, double %y) #0 {
; CHECK-R6-LABEL: add_f64:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    add.d $f0, $f12, $f14
  %val = call double @llvm.experimental.constrained.fadd.f64(double %x, double %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @sub_f64(double %x, double %y) #0 {
; CHECK-R6-LABEL: sub_f64:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    sub.d $f0, $f12, $f14
  %val = call double @llvm.experimental.constrained.fsub.f64(double %x, double %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @mul_f64(double %x, double %y) #0 {
; CHECK-R6-LABEL: mul_f64:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    mul.d $f0, $f12, $f14
  %val = call double @llvm.experimental.constrained.fmul.f64(double %x, double %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @div_f64(double %x, double %y) #0 {
; CHECK-R6-LABEL: div_f64:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    div.d $f0, $f12, $f14
  %val = call double @llvm.experimental.constrained.fdiv.f64(double %x, double %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @frem_f64(double %x, double %y) #0 {
; CHECK-LABEL: frem_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal fmod
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.frem.f64(double %x, double %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @fma_f64(double %x, double %y, double %z) #0 {
; CHECK-R6-LABEL: fma_f64:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    addiu $sp, $sp, -32
; CHECK-R6-NEXT:    .cfi_def_cfa_offset 32
; CHECK-R6-NEXT:    sw $ra, 28($sp) # 4-byte Folded Spill
; CHECK-R6-NEXT:    .cfi_offset 31, -4
; CHECK-R6-NEXT:    ldc1 $f0, 48($sp)
; CHECK-R6-NEXT:    jal fma
; CHECK-R6-NEXT:    sdc1 $f0, 16($sp)
; CHECK-R6-NEXT:    lw $ra, 28($sp) # 4-byte Folded Reload
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    addiu $sp, $sp, 32
  %val = call double @llvm.experimental.constrained.fma.f64(double %x, double %y, double %z, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define i32 @fptosi_f64(double %x) #0 {
; CHECK-LABEL: fptosi_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    trunc.w.d $f0, $f12
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    mfc1 $2, $f0
  %val = call i32 @llvm.experimental.constrained.fptosi.i32.f64(double %x, metadata !"fpexcept.strict") #0
  ret i32 %val
}

define i32 @fptoui_f64(double %x) #0 {
; CHECK-R6-LABEL: fptoui_f64:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    lui $1, %hi($CPI49_0)
; CHECK-R6-NEXT:    ldc1 $f0, %lo($CPI49_0)($1)
; CHECK-R6-NEXT:    cmp.lt.d $f1, $f12, $f0
; CHECK-R6-NEXT:    sub.d $f0, $f12, $f0
; CHECK-R6-NEXT:    trunc.w.d $f0, $f0
; CHECK-R6-NEXT:    mfc1 $1, $f0
; CHECK-R6-NEXT:    lui $2, 32768
; CHECK-R6-NEXT:    xor $1, $1, $2
; CHECK-R6-NEXT:    mfc1 $2, $f1
; CHECK-R6-NEXT:    seleqz $1, $1, $2
; CHECK-R6-NEXT:    trunc.w.d $f0, $f12
; CHECK-R6-NEXT:    mfc1 $3, $f0
; CHECK-R6-NEXT:    selnez $2, $3, $2
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    or $2, $2, $1
  %val = call i32 @llvm.experimental.constrained.fptoui.i32.f64(double %x, metadata !"fpexcept.strict") #0
  ret i32 %val
}

define double @sqrt_f64(double %x) #0 {
; CHECK-LABEL: sqrt_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    sqrt.d $f0, $f12
  %val = call double @llvm.experimental.constrained.sqrt.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @powi_f64(double %x, i32 %y) #0 {
; CHECK-R6-LABEL: powi_f64:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    addiu $sp, $sp, -24
; CHECK-R6-NEXT:    .cfi_def_cfa_offset 24
; CHECK-R6-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-R6-NEXT:    .cfi_offset 31, -4
; CHECK-R6-NEXT:    jal __powidf2
; CHECK-R6-NEXT:    nop
; CHECK-R6-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.powi.f64(double %x, i32 %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @sin_f64(double %x) #0 {
; CHECK-LABEL: sin_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal sin
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.sin.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @cos_f64(double %x) #0 {
; CHECK-LABEL: cos_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal cos
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.cos.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @tan_f64(double %x) #0 {
; CHECK-LABEL: tan_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal tan
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.tan.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @acos_f64(double %x, double %y) #0 {
; CHECK-LABEL: acos_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal acos
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.acos.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @asin_f64(double %x, double %y) #0 {
; CHECK-LABEL: asin_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal asin
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.asin.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @atan_f64(double %x, double %y) #0 {
; CHECK-LABEL: atan_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal atan
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.atan.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @cosh_f64(double %x, double %y) #0 {
; CHECK-LABEL: cosh_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal cosh
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.cosh.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @sinh_f64(double %x, double %y) #0 {
; CHECK-LABEL: sinh_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal sinh
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.sinh.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @tanh_f64(double %x, double %y) #0 {
; CHECK-LABEL: tanh_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal tanh
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.tanh.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @fmuladd_f64(double %x, double %y, double %z) #0 {
; CHECK-R6-LABEL: fmuladd_f64:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    mul.d $f0, $f12, $f14
; CHECK-R6-NEXT:    ldc1 $f1, 16($sp)
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    add.d $f0, $f0, $f1
  %val = call double @llvm.experimental.constrained.fmuladd.f64(double %x, double %y, double %z, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @ldexp_f64(double %x, i32 %y) #0 {
; CHECK-R6-LABEL: ldexp_f64:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    addiu $sp, $sp, -24
; CHECK-R6-NEXT:    .cfi_def_cfa_offset 24
; CHECK-R6-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-R6-NEXT:    .cfi_offset 31, -4
; CHECK-R6-NEXT:    jal ldexp
; CHECK-R6-NEXT:    nop
; CHECK-R6-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.ldexp.f64.i32(double %x, i32 %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @roundeven_f64(double %x) #0 {
; CHECK-LABEL: roundeven_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal roundeven
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.roundeven.f64(double %x, metadata !"fpexcept.strict") #0
  ret double %val
}

define double @uitofp_f64_i32(i32 %x) #0 {
; CHECK-R6-LABEL: uitofp_f64_i32:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    addiu $sp, $sp, -8
; CHECK-R6-NEXT:    .cfi_def_cfa_offset 8
; CHECK-R6-NEXT:    sw $4, 4($sp)
; CHECK-R6-NEXT:    lui $1, 17200
; CHECK-R6-NEXT:    sw $1, 0($sp)
; CHECK-R6-NEXT:    lui $1, %hi($CPI64_0)
; CHECK-R6-NEXT:    ldc1 $f0, %lo($CPI64_0)($1)
; CHECK-R6-NEXT:    ldc1 $f1, 0($sp)
; CHECK-R6-NEXT:    sub.d $f0, $f1, $f0
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    addiu $sp, $sp, 8
  %val = call double @llvm.experimental.constrained.uitofp.f64.i32(i32 %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @atan2_f64(double %x, double %y) #0 {
; CHECK-LABEL: atan2_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal atan2
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.atan2.f64(double %x, double %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @pow_f64(double %x, double %y) #0 {
; CHECK-LABEL: pow_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal pow
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.pow.f64(double %x, double %y, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @log_f64(double %x) #0 {
; CHECK-LABEL: log_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal log
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.log.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @log10_f64(double %x) #0 {
; CHECK-LABEL: log10_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal log10
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.log10.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @log2_f64(double %x) #0 {
; CHECK-LABEL: log2_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal log2
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.log2.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @exp_f64(double %x) #0 {
; CHECK-LABEL: exp_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal exp
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.exp.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @exp2_f64(double %x) #0 {
; CHECK-LABEL: exp2_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal exp2
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.exp2.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @rint_f64(double %x) #0 {
; CHECK-LABEL: rint_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal rint
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.rint.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define double @nearbyint_f64(double %x) #0 {
; CHECK-LABEL: nearbyint_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal nearbyint
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.nearbyint.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}

define i32 @lrint_f64(double %x) #0 {
; CHECK-LABEL: lrint_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal lrint
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call i32 @llvm.experimental.constrained.lrint.i32.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret i32 %val
}

define i32 @llrint_f64(double %x) #0 {
; CHECK-LABEL: llrint_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal llrint
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call i32 @llvm.experimental.constrained.llrint.i32.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret i32 %val
}

define double @maxnum_f64(double %x, double %y) #0 {
; CHECK-R2-LABEL: maxnum_f64:
; CHECK-R2:       # %bb.0:
; CHECK-R2-NEXT:    addiu $sp, $sp, -24
; CHECK-R2-NEXT:    .cfi_def_cfa_offset 24
; CHECK-R2-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-R2-NEXT:    .cfi_offset 31, -4
; CHECK-R2-NEXT:    jal fmax
; CHECK-R2-NEXT:    nop
; CHECK-R2-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-R2-NEXT:    jr $ra
; CHECK-R2-NEXT:    addiu $sp, $sp, 24
;
; CHECK-R6-LABEL: maxnum_f64:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    max.d $f0, $f12, $f14
  %val = call double @llvm.experimental.constrained.maxnum.f64(double %x, double %y, metadata !"fpexcept.strict") #0
  ret double %val
}

define double @minnum_f64(double %x, double %y) #0 {
; CHECK-R2-LABEL: minnum_f64:
; CHECK-R2:       # %bb.0:
; CHECK-R2-NEXT:    addiu $sp, $sp, -24
; CHECK-R2-NEXT:    .cfi_def_cfa_offset 24
; CHECK-R2-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-R2-NEXT:    .cfi_offset 31, -4
; CHECK-R2-NEXT:    jal fmin
; CHECK-R2-NEXT:    nop
; CHECK-R2-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-R2-NEXT:    jr $ra
; CHECK-R2-NEXT:    addiu $sp, $sp, 24
;
; CHECK-R6-LABEL: minnum_f64:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    min.d $f0, $f12, $f14
  %val = call double @llvm.experimental.constrained.minnum.f64(double %x, double %y, metadata !"fpexcept.strict") #0
  ret double %val
}

define double @ceil_f64(double %x) #0 {
; CHECK-LABEL: ceil_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal ceil
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.ceil.f64(double %x, metadata !"fpexcept.strict") #0
  ret double %val
}

define double @floor_f64(double %x) #0 {
; CHECK-LABEL: floor_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal floor
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.floor.f64(double %x, metadata !"fpexcept.strict") #0
  ret double %val
}

define i32 @lround_f64(double %x) #0 {
; CHECK-LABEL: lround_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal lround
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call i32 @llvm.experimental.constrained.lround.i32.f64(double %x, metadata !"fpexcept.strict") #0
  ret i32 %val
}

define i32 @llround_f64(double %x) #0 {
; CHECK-LABEL: llround_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal llround
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call i32 @llvm.experimental.constrained.llround.i32.f64(double %x, metadata !"fpexcept.strict") #0
  ret i32 %val
}

define double @round_f64(double %x) #0 {
; CHECK-LABEL: round_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal round
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.round.f64(double %x, metadata !"fpexcept.strict") #0
  ret double %val
}

define double @trunc_f64(double %x) #0 {
; CHECK-LABEL: trunc_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiu $sp, $sp, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    sw $ra, 20($sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    jal trunc
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw $ra, 20($sp) # 4-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    addiu $sp, $sp, 24
  %val = call double @llvm.experimental.constrained.trunc.f64(double %x, metadata !"fpexcept.strict") #0
  ret double %val
}

define float @fptrunc_f32(double %x) #0 {
; CHECK-LABEL: fptrunc_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    cvt.s.d $f0, $f12
  %val = call float @llvm.experimental.constrained.fptrunc.f32.f64(double %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define double @fpext_f32(float %x) #0 {
; CHECK-LABEL: fpext_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    cvt.d.s $f0, $f12
  %val = call double @llvm.experimental.constrained.fpext.f64.f32(float %x, metadata !"fpexcept.strict") #0
  ret double %val
}

define float @sitofp_f32_i32(i32 %x) #0 {
; CHECK-R6-LABEL: sitofp_f32_i32:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    addiu $sp, $sp, -8
; CHECK-R6-NEXT:    .cfi_def_cfa_offset 8
; CHECK-R6-NEXT:    lui $1, 17200
; CHECK-R6-NEXT:    sw $1, 0($sp)
; CHECK-R6-NEXT:    lui $1, 32768
; CHECK-R6-NEXT:    xor $1, $4, $1
; CHECK-R6-NEXT:    sw $1, 4($sp)
; CHECK-R6-NEXT:    lui $1, %hi($CPI86_0)
; CHECK-R6-NEXT:    ldc1 $f0, %lo($CPI86_0)($1)
; CHECK-R6-NEXT:    ldc1 $f1, 0($sp)
; CHECK-R6-NEXT:    sub.d $f0, $f1, $f0
; CHECK-R6-NEXT:    cvt.s.d $f0, $f0
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    addiu $sp, $sp, 8
  %val = call float @llvm.experimental.constrained.sitofp.f32.i32(i32 %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret float %val
}

define double @sitofp_f64_i32(i32 %x) #0 {
; CHECK-R6-LABEL: sitofp_f64_i32:
; CHECK-R6:       # %bb.0:
; CHECK-R6-NEXT:    addiu $sp, $sp, -8
; CHECK-R6-NEXT:    .cfi_def_cfa_offset 8
; CHECK-R6-NEXT:    lui $1, 17200
; CHECK-R6-NEXT:    sw $1, 0($sp)
; CHECK-R6-NEXT:    lui $1, 32768
; CHECK-R6-NEXT:    xor $1, $4, $1
; CHECK-R6-NEXT:    sw $1, 4($sp)
; CHECK-R6-NEXT:    lui $1, %hi($CPI87_0)
; CHECK-R6-NEXT:    ldc1 $f0, %lo($CPI87_0)($1)
; CHECK-R6-NEXT:    ldc1 $f1, 0($sp)
; CHECK-R6-NEXT:    sub.d $f0, $f1, $f0
; CHECK-R6-NEXT:    jr $ra
; CHECK-R6-NEXT:    addiu $sp, $sp, 8
  %val = call double @llvm.experimental.constrained.sitofp.f64.i32(i32 %x, metadata !"round.tonearest", metadata !"fpexcept.strict") #0
  ret double %val
}


attributes #0 = { strictfp }

declare float @llvm.experimental.constrained.fadd.f32(float, float, metadata, metadata)
declare float @llvm.experimental.constrained.fsub.f32(float, float, metadata, metadata)
declare float @llvm.experimental.constrained.fmul.f32(float, float, metadata, metadata)
declare float @llvm.experimental.constrained.fdiv.f32(float, float, metadata, metadata)
declare float @llvm.experimental.constrained.frem.f32(float, float, metadata, metadata)
declare float @llvm.experimental.constrained.fma.f32(float, float, float, metadata, metadata)
declare i32 @llvm.experimental.constrained.fptosi.i32.f32(float, metadata)
declare i32 @llvm.experimental.constrained.fptoui.i32.f32(float, metadata)
declare float @llvm.experimental.constrained.sqrt.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.powi.f32(float, i32, metadata, metadata)
declare float @llvm.experimental.constrained.sin.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.cos.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.tan.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.acos.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.asin.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.atan.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.cosh.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.sinh.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.tanh.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.fmuladd.f32(float, float, float, metadata, metadata)
declare float @llvm.experimental.constrained.ldexp.f32.i32(float, i32, metadata, metadata)
declare float @llvm.experimental.constrained.roundeven.f32(float, metadata)
declare float @llvm.experimental.constrained.uitofp.f32.i32(i32, metadata, metadata)
declare float @llvm.experimental.constrained.atan2.f32(float, float, metadata, metadata)
declare float @llvm.experimental.constrained.pow.f32(float, float, metadata, metadata)
declare float @llvm.experimental.constrained.log.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.log10.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.log2.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.exp.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.exp2.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.rint.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.nearbyint.f32(float, metadata, metadata)
declare i32 @llvm.experimental.constrained.lrint.i32.f32(float, metadata, metadata)
declare i32 @llvm.experimental.constrained.llrint.i32.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.maxnum.f32(float, float, metadata)
declare float @llvm.experimental.constrained.minnum.f32(float, float, metadata)
declare float @llvm.experimental.constrained.ceil.f32(float, metadata)
declare float @llvm.experimental.constrained.floor.f32(float, metadata)
declare i32 @llvm.experimental.constrained.lround.i32.f32(float, metadata)
declare i32 @llvm.experimental.constrained.llround.i32.f32(float, metadata)
declare float @llvm.experimental.constrained.round.f32(float, metadata)
declare float @llvm.experimental.constrained.trunc.f32(float, metadata)

declare double @llvm.experimental.constrained.fadd.f64(double, double, metadata, metadata)
declare double @llvm.experimental.constrained.fsub.f64(double, double, metadata, metadata)
declare double @llvm.experimental.constrained.fmul.f64(double, double, metadata, metadata)
declare double @llvm.experimental.constrained.fdiv.f64(double, double, metadata, metadata)
declare double @llvm.experimental.constrained.frem.f64(double, double, metadata, metadata)
declare double @llvm.experimental.constrained.fma.f64(double, double, double, metadata, metadata)
declare i32 @llvm.experimental.constrained.fptosi.i32.f64(double, metadata)
declare i32 @llvm.experimental.constrained.fptoui.i32.f64(double, metadata)
declare double @llvm.experimental.constrained.sqrt.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.powi.f64(double, i32, metadata, metadata)
declare double @llvm.experimental.constrained.sin.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.cos.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.tan.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.acos.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.asin.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.atan.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.cosh.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.sinh.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.tanh.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.fmuladd.f64(double, double, double, metadata, metadata)
declare double @llvm.experimental.constrained.ldexp.f64.i32(double, i32, metadata, metadata)
declare double @llvm.experimental.constrained.roundeven.f64(double, metadata)
declare double @llvm.experimental.constrained.uitofp.f64.i32(i32, metadata, metadata)
declare double @llvm.experimental.constrained.atan2.f64(double, double, metadata, metadata)
declare double @llvm.experimental.constrained.pow.f64(double, double, metadata, metadata)
declare double @llvm.experimental.constrained.log.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.log10.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.log2.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.exp.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.exp2.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.rint.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.nearbyint.f64(double, metadata, metadata)
declare i32 @llvm.experimental.constrained.lrint.i32.f64(double, metadata, metadata)
declare i32 @llvm.experimental.constrained.llrint.i32.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.maxnum.f64(double, double, metadata)
declare double @llvm.experimental.constrained.minnum.f64(double, double, metadata)
declare double @llvm.experimental.constrained.ceil.f64(double, metadata)
declare double @llvm.experimental.constrained.floor.f64(double, metadata)
declare i32 @llvm.experimental.constrained.lround.i32.f64(double, metadata)
declare i32 @llvm.experimental.constrained.llround.i32.f64(double, metadata)
declare double @llvm.experimental.constrained.round.f64(double, metadata)
declare double @llvm.experimental.constrained.trunc.f64(double, metadata)

declare float @llvm.experimental.constrained.fptrunc.f32.f64(double, metadata, metadata)
declare double @llvm.experimental.constrained.fpext.f64.f32(float, metadata)
declare float @llvm.experimental.constrained.sitofp.f32.i32(i32, metadata, metadata)
declare double @llvm.experimental.constrained.sitofp.f64.i32(i32, metadata, metadata)
