; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=mipsisa32r6 < %s | FileCheck %s --check-prefix=MIPS32R6
; RUN: llc --mtriple=mips64 -mattr=+mips64r2 < %s | FileCheck %s --check-prefix=MIPS64R2
; RUN: llc --mtriple=mips64 -mattr=+mips64 < %s | FileCheck %s --check-prefix=MIPS64
; RUN: llc --mtriple=mips -mattr=+mips32r2 < %s | FileCheck %s --check-prefix=MIPS32R2
; RUN: llc --mtriple=mips -mattr=+mips32 < %s | FileCheck %s --check-prefix=MIPS32

declare float @llvm.maximum.f32(float, float)
declare double @llvm.maximum.f64(double, double)
declare float @llvm.minimum.f32(float, float)
declare double @llvm.minimum.f64(double, double)

define float @maximum_float(float %x, float %y) {
; MIPS32R6-LABEL: maximum_float:
; MIPS32R6:       # %bb.0:
; MIPS32R6-NEXT:    max.s $f1, $f12, $f14
; MIPS32R6-NEXT:    cmp.un.s $f0, $f12, $f14
; MIPS32R6-NEXT:    lui $1, %hi($CPI0_0)
; MIPS32R6-NEXT:    lwc1 $f2, %lo($CPI0_0)($1)
; MIPS32R6-NEXT:    jr $ra
; MIPS32R6-NEXT:    sel.s $f0, $f1, $f2
;
; MIPS64R2-LABEL: maximum_float:
; MIPS64R2:       # %bb.0:
; MIPS64R2-NEXT:    mov.s $f0, $f13
; MIPS64R2-NEXT:    c.un.s $f13, $f13
; MIPS64R2-NEXT:    movt.s $f12, $f13, $fcc0
; MIPS64R2-NEXT:    c.ole.s $f12, $f13
; MIPS64R2-NEXT:    movf.s $f0, $f12, $fcc0
; MIPS64R2-NEXT:    mfc1 $1, $f12
; MIPS64R2-NEXT:    slti $1, $1, 0
; MIPS64R2-NEXT:    mov.s $f1, $f0
; MIPS64R2-NEXT:    movz.s $f1, $f12, $1
; MIPS64R2-NEXT:    mtc1 $zero, $f2
; MIPS64R2-NEXT:    c.eq.s $f0, $f2
; MIPS64R2-NEXT:    jr $ra
; MIPS64R2-NEXT:    movt.s $f0, $f1, $fcc0
;
; MIPS64-LABEL: maximum_float:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    mov.s $f0, $f13
; MIPS64-NEXT:    c.un.s $f13, $f13
; MIPS64-NEXT:    movt.s $f12, $f13, $fcc0
; MIPS64-NEXT:    c.ole.s $f12, $f13
; MIPS64-NEXT:    movf.s $f0, $f12, $fcc0
; MIPS64-NEXT:    mfc1 $1, $f12
; MIPS64-NEXT:    slti $1, $1, 0
; MIPS64-NEXT:    mov.s $f1, $f0
; MIPS64-NEXT:    movz.s $f1, $f12, $1
; MIPS64-NEXT:    mtc1 $zero, $f2
; MIPS64-NEXT:    c.eq.s $f0, $f2
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    movt.s $f0, $f1, $fcc0
;
; MIPS32R2-LABEL: maximum_float:
; MIPS32R2:       # %bb.0:
; MIPS32R2-NEXT:    mov.s $f0, $f14
; MIPS32R2-NEXT:    c.un.s $f14, $f14
; MIPS32R2-NEXT:    movt.s $f12, $f14, $fcc0
; MIPS32R2-NEXT:    c.ole.s $f12, $f14
; MIPS32R2-NEXT:    movf.s $f0, $f12, $fcc0
; MIPS32R2-NEXT:    mfc1 $1, $f12
; MIPS32R2-NEXT:    slti $1, $1, 0
; MIPS32R2-NEXT:    mov.s $f1, $f0
; MIPS32R2-NEXT:    movz.s $f1, $f12, $1
; MIPS32R2-NEXT:    mtc1 $zero, $f2
; MIPS32R2-NEXT:    c.eq.s $f0, $f2
; MIPS32R2-NEXT:    jr $ra
; MIPS32R2-NEXT:    movt.s $f0, $f1, $fcc0
;
; MIPS32-LABEL: maximum_float:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    mov.s $f0, $f14
; MIPS32-NEXT:    c.un.s $f14, $f14
; MIPS32-NEXT:    movt.s $f12, $f14, $fcc0
; MIPS32-NEXT:    c.ole.s $f12, $f14
; MIPS32-NEXT:    movf.s $f0, $f12, $fcc0
; MIPS32-NEXT:    mfc1 $1, $f12
; MIPS32-NEXT:    slti $1, $1, 0
; MIPS32-NEXT:    mov.s $f1, $f0
; MIPS32-NEXT:    movz.s $f1, $f12, $1
; MIPS32-NEXT:    mtc1 $zero, $f2
; MIPS32-NEXT:    c.eq.s $f0, $f2
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    movt.s $f0, $f1, $fcc0
; MIPS32R5-LABEL: maximum_float:
; MIPS32R5:       # %bb.0:
; MIPS32R5-NEXT:    mov.s $f0, $f14
; MIPS32R5-NEXT:    c.un.s $f12, $f12
; MIPS32R5-NEXT:    movt.s $f12, $f14, $fcc0
; MIPS32R5-NEXT:    c.un.s $f14, $f14
; MIPS32R5-NEXT:    movt.s $f0, $f12, $fcc0
; MIPS32R5-NEXT:    c.ule.s $f12, $f0
; MIPS32R5-NEXT:    movf.s $f0, $f12, $fcc0
; MIPS32R5-NEXT:    mfc1 $1, $f12
; MIPS32R5-NEXT:    mov.s $f1, $f0
; MIPS32R5-NEXT:    movz.s $f1, $f12, $1
; MIPS32R5-NEXT:    mtc1 $zero, $f2
; MIPS32R5-NEXT:    c.eq.s $f0, $f2
; MIPS32R5-NEXT:    jr $ra
; MIPS32R5-NEXT:    movt.s $f0, $f1, $fcc0
  %z = call float @llvm.maximum.f32(float %x, float %y)
  ret float %z
}

define float @maximum_float_nsz(float %x, float %y) {
; MIPS32R6-LABEL: maximum_float_nsz:
; MIPS32R6:       # %bb.0:
; MIPS32R6-NEXT:    max.s $f1, $f12, $f14
; MIPS32R6-NEXT:    cmp.un.s $f0, $f12, $f14
; MIPS32R6-NEXT:    lui $1, %hi($CPI1_0)
; MIPS32R6-NEXT:    lwc1 $f2, %lo($CPI1_0)($1)
; MIPS32R6-NEXT:    jr $ra
; MIPS32R6-NEXT:    sel.s $f0, $f1, $f2
;
; MIPS64R2-LABEL: maximum_float_nsz:
; MIPS64R2:       # %bb.0:
; MIPS64R2-NEXT:    mov.s $f0, $f13
; MIPS64R2-NEXT:    c.un.s $f13, $f13
; MIPS64R2-NEXT:    movt.s $f12, $f13, $fcc0
; MIPS64R2-NEXT:    c.ole.s $f12, $f13
; MIPS64R2-NEXT:    jr $ra
; MIPS64R2-NEXT:    movf.s $f0, $f12, $fcc0
;
; MIPS64-LABEL: maximum_float_nsz:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    mov.s $f0, $f13
; MIPS64-NEXT:    c.un.s $f13, $f13
; MIPS64-NEXT:    movt.s $f12, $f13, $fcc0
; MIPS64-NEXT:    c.ole.s $f12, $f13
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    movf.s $f0, $f12, $fcc0
;
; MIPS32R2-LABEL: maximum_float_nsz:
; MIPS32R2:       # %bb.0:
; MIPS32R2-NEXT:    mov.s $f0, $f14
; MIPS32R2-NEXT:    c.un.s $f14, $f14
; MIPS32R2-NEXT:    movt.s $f12, $f14, $fcc0
; MIPS32R2-NEXT:    c.ole.s $f12, $f14
; MIPS32R2-NEXT:    jr $ra
; MIPS32R2-NEXT:    movf.s $f0, $f12, $fcc0
;
; MIPS32-LABEL: maximum_float_nsz:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    mov.s $f0, $f14
; MIPS32-NEXT:    c.un.s $f14, $f14
; MIPS32-NEXT:    movt.s $f12, $f14, $fcc0
; MIPS32-NEXT:    c.ole.s $f12, $f14
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    movf.s $f0, $f12, $fcc0
; MIPS32R5-LABEL: maximum_float_nsz:
; MIPS32R5:       # %bb.0:
; MIPS32R5-NEXT:    mov.s $f0, $f14
; MIPS32R5-NEXT:    c.un.s $f12, $f12
; MIPS32R5-NEXT:    movt.s $f12, $f14, $fcc0
; MIPS32R5-NEXT:    c.un.s $f14, $f14
; MIPS32R5-NEXT:    movt.s $f0, $f12, $fcc0
; MIPS32R5-NEXT:    c.ule.s $f12, $f0
; MIPS32R5-NEXT:    jr $ra
; MIPS32R5-NEXT:    movf.s $f0, $f12, $fcc0
  %z = call nsz float @llvm.maximum.f32(float %x, float %y)
  ret float %z
}

define float @maximum_float_nnan(float %x, float %y) {
; MIPS32R6-LABEL: maximum_float_nnan:
; MIPS32R6:       # %bb.0:
; MIPS32R6-NEXT:    jr $ra
; MIPS32R6-NEXT:    max.s $f0, $f12, $f14
;
; MIPS64R2-LABEL: maximum_float_nnan:
; MIPS64R2:       # %bb.0:
; MIPS64R2-NEXT:    mov.s $f0, $f13
; MIPS64R2-NEXT:    c.ole.s $f12, $f13
; MIPS64R2-NEXT:    movf.s $f0, $f12, $fcc0
; MIPS64R2-NEXT:    mfc1 $1, $f12
; MIPS64R2-NEXT:    slti $1, $1, 0
; MIPS64R2-NEXT:    mov.s $f1, $f0
; MIPS64R2-NEXT:    movz.s $f1, $f12, $1
; MIPS64R2-NEXT:    mtc1 $zero, $f2
; MIPS64R2-NEXT:    c.eq.s $f0, $f2
; MIPS64R2-NEXT:    jr $ra
; MIPS64R2-NEXT:    movt.s $f0, $f1, $fcc0
;
; MIPS64-LABEL: maximum_float_nnan:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    mov.s $f0, $f13
; MIPS64-NEXT:    c.ole.s $f12, $f13
; MIPS64-NEXT:    movf.s $f0, $f12, $fcc0
; MIPS64-NEXT:    mfc1 $1, $f12
; MIPS64-NEXT:    slti $1, $1, 0
; MIPS64-NEXT:    mov.s $f1, $f0
; MIPS64-NEXT:    movz.s $f1, $f12, $1
; MIPS64-NEXT:    mtc1 $zero, $f2
; MIPS64-NEXT:    c.eq.s $f0, $f2
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    movt.s $f0, $f1, $fcc0
;
; MIPS32R2-LABEL: maximum_float_nnan:
; MIPS32R2:       # %bb.0:
; MIPS32R2-NEXT:    mov.s $f0, $f14
; MIPS32R2-NEXT:    c.ole.s $f12, $f14
; MIPS32R2-NEXT:    movf.s $f0, $f12, $fcc0
; MIPS32R2-NEXT:    mfc1 $1, $f12
; MIPS32R2-NEXT:    slti $1, $1, 0
; MIPS32R2-NEXT:    mov.s $f1, $f0
; MIPS32R2-NEXT:    movz.s $f1, $f12, $1
; MIPS32R2-NEXT:    mtc1 $zero, $f2
; MIPS32R2-NEXT:    c.eq.s $f0, $f2
; MIPS32R2-NEXT:    jr $ra
; MIPS32R2-NEXT:    movt.s $f0, $f1, $fcc0
;
; MIPS32-LABEL: maximum_float_nnan:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    mov.s $f0, $f14
; MIPS32-NEXT:    c.ole.s $f12, $f14
; MIPS32-NEXT:    movf.s $f0, $f12, $fcc0
; MIPS32-NEXT:    mfc1 $1, $f12
; MIPS32-NEXT:    slti $1, $1, 0
; MIPS32-NEXT:    mov.s $f1, $f0
; MIPS32-NEXT:    movz.s $f1, $f12, $1
; MIPS32-NEXT:    mtc1 $zero, $f2
; MIPS32-NEXT:    c.eq.s $f0, $f2
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    movt.s $f0, $f1, $fcc0
; MIPS32R5-LABEL: maximum_float_nnan:
; MIPS32R5:       # %bb.0:
; MIPS32R5-NEXT:    mov.s $f0, $f14
; MIPS32R5-NEXT:    c.ule.s $f12, $f14
; MIPS32R5-NEXT:    movf.s $f0, $f12, $fcc0
; MIPS32R5-NEXT:    mfc1 $1, $f12
; MIPS32R5-NEXT:    mov.s $f1, $f0
; MIPS32R5-NEXT:    movz.s $f1, $f12, $1
; MIPS32R5-NEXT:    mtc1 $zero, $f2
; MIPS32R5-NEXT:    c.eq.s $f0, $f2
; MIPS32R5-NEXT:    jr $ra
; MIPS32R5-NEXT:    movt.s $f0, $f1, $fcc0
  %z = call nnan float @llvm.maximum.f32(float %x, float %y)
  ret float %z
}


define double @maximum_double(double %x, double %y) {
; MIPS32R6-LABEL: maximum_double:
; MIPS32R6:       # %bb.0:
; MIPS32R6-NEXT:    max.d $f1, $f12, $f14
; MIPS32R6-NEXT:    cmp.un.d $f0, $f12, $f14
; MIPS32R6-NEXT:    lui $1, %hi($CPI3_0)
; MIPS32R6-NEXT:    ldc1 $f2, %lo($CPI3_0)($1)
; MIPS32R6-NEXT:    jr $ra
; MIPS32R6-NEXT:    sel.d $f0, $f1, $f2
;
; MIPS64R2-LABEL: maximum_double:
; MIPS64R2:       # %bb.0:
; MIPS64R2-NEXT:    mov.d $f0, $f13
; MIPS64R2-NEXT:    c.un.d $f13, $f13
; MIPS64R2-NEXT:    movt.d $f12, $f13, $fcc0
; MIPS64R2-NEXT:    c.ole.d $f12, $f13
; MIPS64R2-NEXT:    movf.d $f0, $f12, $fcc0
; MIPS64R2-NEXT:    dmfc1 $1, $f12
; MIPS64R2-NEXT:    slti $1, $1, 0
; MIPS64R2-NEXT:    mov.d $f1, $f0
; MIPS64R2-NEXT:    movz.d $f1, $f12, $1
; MIPS64R2-NEXT:    dmtc1 $zero, $f2
; MIPS64R2-NEXT:    c.eq.d $f0, $f2
; MIPS64R2-NEXT:    jr $ra
; MIPS64R2-NEXT:    movt.d $f0, $f1, $fcc0
;
; MIPS64-LABEL: maximum_double:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    mov.d $f0, $f13
; MIPS64-NEXT:    c.un.d $f13, $f13
; MIPS64-NEXT:    movt.d $f12, $f13, $fcc0
; MIPS64-NEXT:    c.ole.d $f12, $f13
; MIPS64-NEXT:    movf.d $f0, $f12, $fcc0
; MIPS64-NEXT:    dmfc1 $1, $f12
; MIPS64-NEXT:    slti $1, $1, 0
; MIPS64-NEXT:    mov.d $f1, $f0
; MIPS64-NEXT:    movz.d $f1, $f12, $1
; MIPS64-NEXT:    dmtc1 $zero, $f2
; MIPS64-NEXT:    c.eq.d $f0, $f2
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    movt.d $f0, $f1, $fcc0
;
; MIPS32R2-LABEL: maximum_double:
; MIPS32R2:       # %bb.0:
; MIPS32R2-NEXT:    mov.d $f0, $f14
; MIPS32R2-NEXT:    c.un.d $f14, $f14
; MIPS32R2-NEXT:    movt.d $f12, $f14, $fcc0
; MIPS32R2-NEXT:    c.ole.d $f12, $f14
; MIPS32R2-NEXT:    movf.d $f0, $f12, $fcc0
; MIPS32R2-NEXT:    cvt.s.d $f2, $f12
; MIPS32R2-NEXT:    mfc1 $1, $f2
; MIPS32R2-NEXT:    slti $1, $1, 0
; MIPS32R2-NEXT:    mov.d $f2, $f0
; MIPS32R2-NEXT:    movz.d $f2, $f12, $1
; MIPS32R2-NEXT:    mtc1 $zero, $f4
; MIPS32R2-NEXT:    mthc1 $zero, $f4
; MIPS32R2-NEXT:    c.eq.d $f0, $f4
; MIPS32R2-NEXT:    jr $ra
; MIPS32R2-NEXT:    movt.d $f0, $f2, $fcc0
;
; MIPS32-LABEL: maximum_double:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    mov.d $f0, $f14
; MIPS32-NEXT:    c.un.d $f14, $f14
; MIPS32-NEXT:    movt.d $f12, $f14, $fcc0
; MIPS32-NEXT:    c.ole.d $f12, $f14
; MIPS32-NEXT:    movf.d $f0, $f12, $fcc0
; MIPS32-NEXT:    cvt.s.d $f2, $f12
; MIPS32-NEXT:    mfc1 $1, $f2
; MIPS32-NEXT:    slti $1, $1, 0
; MIPS32-NEXT:    mov.d $f2, $f0
; MIPS32-NEXT:    movz.d $f2, $f12, $1
; MIPS32-NEXT:    mtc1 $zero, $f4
; MIPS32-NEXT:    mtc1 $zero, $f5
; MIPS32-NEXT:    c.eq.d $f0, $f4
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    movt.d $f0, $f2, $fcc0
; MIPS32R5-LABEL: maximum_double:
; MIPS32R5:       # %bb.0:
; MIPS32R5-NEXT:    mov.d $f0, $f14
; MIPS32R5-NEXT:    c.un.d $f12, $f12
; MIPS32R5-NEXT:    movt.d $f12, $f14, $fcc0
; MIPS32R5-NEXT:    c.un.d $f14, $f14
; MIPS32R5-NEXT:    movt.d $f0, $f12, $fcc0
; MIPS32R5-NEXT:    c.ule.d $f12, $f0
; MIPS32R5-NEXT:    movf.d $f0, $f12, $fcc0
; MIPS32R5-NEXT:    cvt.s.d $f1, $f12
; MIPS32R5-NEXT:    mfc1 $1, $f1
; MIPS32R5-NEXT:    mov.d $f1, $f0
; MIPS32R5-NEXT:    movz.d $f1, $f12, $1
; MIPS32R5-NEXT:    mtc1 $zero, $f2
; MIPS32R5-NEXT:    mthc1 $zero, $f2
; MIPS32R5-NEXT:    c.eq.d $f0, $f2
; MIPS32R5-NEXT:    jr $ra
; MIPS32R5-NEXT:    movt.d $f0, $f1, $fcc0
  %z = call double @llvm.maximum.f64(double %x, double %y)
  ret double %z
}

define double @maximum_double_nsz(double %x, double %y) {
; MIPS32R6-LABEL: maximum_double_nsz:
; MIPS32R6:       # %bb.0:
; MIPS32R6-NEXT:    max.d $f1, $f12, $f14
; MIPS32R6-NEXT:    cmp.un.d $f0, $f12, $f14
; MIPS32R6-NEXT:    lui $1, %hi($CPI4_0)
; MIPS32R6-NEXT:    ldc1 $f2, %lo($CPI4_0)($1)
; MIPS32R6-NEXT:    jr $ra
; MIPS32R6-NEXT:    sel.d $f0, $f1, $f2
;
; MIPS64R2-LABEL: maximum_double_nsz:
; MIPS64R2:       # %bb.0:
; MIPS64R2-NEXT:    mov.d $f0, $f13
; MIPS64R2-NEXT:    c.un.d $f13, $f13
; MIPS64R2-NEXT:    movt.d $f12, $f13, $fcc0
; MIPS64R2-NEXT:    c.ole.d $f12, $f13
; MIPS64R2-NEXT:    jr $ra
; MIPS64R2-NEXT:    movf.d $f0, $f12, $fcc0
;
; MIPS64-LABEL: maximum_double_nsz:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    mov.d $f0, $f13
; MIPS64-NEXT:    c.un.d $f13, $f13
; MIPS64-NEXT:    movt.d $f12, $f13, $fcc0
; MIPS64-NEXT:    c.ole.d $f12, $f13
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    movf.d $f0, $f12, $fcc0
;
; MIPS32R2-LABEL: maximum_double_nsz:
; MIPS32R2:       # %bb.0:
; MIPS32R2-NEXT:    mov.d $f0, $f14
; MIPS32R2-NEXT:    c.un.d $f14, $f14
; MIPS32R2-NEXT:    movt.d $f12, $f14, $fcc0
; MIPS32R2-NEXT:    c.ole.d $f12, $f14
; MIPS32R2-NEXT:    jr $ra
; MIPS32R2-NEXT:    movf.d $f0, $f12, $fcc0
;
; MIPS32-LABEL: maximum_double_nsz:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    mov.d $f0, $f14
; MIPS32-NEXT:    c.un.d $f14, $f14
; MIPS32-NEXT:    movt.d $f12, $f14, $fcc0
; MIPS32-NEXT:    c.ole.d $f12, $f14
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    movf.d $f0, $f12, $fcc0
; MIPS32R5-LABEL: maximum_double_nsz:
; MIPS32R5:       # %bb.0:
; MIPS32R5-NEXT:    mov.d $f0, $f14
; MIPS32R5-NEXT:    c.un.d $f12, $f12
; MIPS32R5-NEXT:    movt.d $f12, $f14, $fcc0
; MIPS32R5-NEXT:    c.un.d $f14, $f14
; MIPS32R5-NEXT:    movt.d $f0, $f12, $fcc0
; MIPS32R5-NEXT:    c.ule.d $f12, $f0
; MIPS32R5-NEXT:    jr $ra
; MIPS32R5-NEXT:    movf.d $f0, $f12, $fcc0
  %z = call nsz double @llvm.maximum.f64(double %x, double %y)
  ret double %z
}

define double @maximum_double_nnan(double %x, double %y) {
; MIPS32R6-LABEL: maximum_double_nnan:
; MIPS32R6:       # %bb.0:
; MIPS32R6-NEXT:    jr $ra
; MIPS32R6-NEXT:    max.d $f0, $f12, $f14
;
; MIPS64R2-LABEL: maximum_double_nnan:
; MIPS64R2:       # %bb.0:
; MIPS64R2-NEXT:    mov.d $f0, $f13
; MIPS64R2-NEXT:    c.ole.d $f12, $f13
; MIPS64R2-NEXT:    movf.d $f0, $f12, $fcc0
; MIPS64R2-NEXT:    dmfc1 $1, $f12
; MIPS64R2-NEXT:    slti $1, $1, 0
; MIPS64R2-NEXT:    mov.d $f1, $f0
; MIPS64R2-NEXT:    movz.d $f1, $f12, $1
; MIPS64R2-NEXT:    dmtc1 $zero, $f2
; MIPS64R2-NEXT:    c.eq.d $f0, $f2
; MIPS64R2-NEXT:    jr $ra
; MIPS64R2-NEXT:    movt.d $f0, $f1, $fcc0
;
; MIPS64-LABEL: maximum_double_nnan:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    mov.d $f0, $f13
; MIPS64-NEXT:    c.ole.d $f12, $f13
; MIPS64-NEXT:    movf.d $f0, $f12, $fcc0
; MIPS64-NEXT:    dmfc1 $1, $f12
; MIPS64-NEXT:    slti $1, $1, 0
; MIPS64-NEXT:    mov.d $f1, $f0
; MIPS64-NEXT:    movz.d $f1, $f12, $1
; MIPS64-NEXT:    dmtc1 $zero, $f2
; MIPS64-NEXT:    c.eq.d $f0, $f2
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    movt.d $f0, $f1, $fcc0
;
; MIPS32R2-LABEL: maximum_double_nnan:
; MIPS32R2:       # %bb.0:
; MIPS32R2-NEXT:    mov.d $f0, $f14
; MIPS32R2-NEXT:    c.ole.d $f12, $f14
; MIPS32R2-NEXT:    movf.d $f0, $f12, $fcc0
; MIPS32R2-NEXT:    cvt.s.d $f2, $f12
; MIPS32R2-NEXT:    mfc1 $1, $f2
; MIPS32R2-NEXT:    slti $1, $1, 0
; MIPS32R2-NEXT:    mov.d $f2, $f0
; MIPS32R2-NEXT:    movz.d $f2, $f12, $1
; MIPS32R2-NEXT:    mtc1 $zero, $f4
; MIPS32R2-NEXT:    mthc1 $zero, $f4
; MIPS32R2-NEXT:    c.eq.d $f0, $f4
; MIPS32R2-NEXT:    jr $ra
; MIPS32R2-NEXT:    movt.d $f0, $f2, $fcc0
;
; MIPS32-LABEL: maximum_double_nnan:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    mov.d $f0, $f14
; MIPS32-NEXT:    c.ole.d $f12, $f14
; MIPS32-NEXT:    movf.d $f0, $f12, $fcc0
; MIPS32-NEXT:    cvt.s.d $f2, $f12
; MIPS32-NEXT:    mfc1 $1, $f2
; MIPS32-NEXT:    slti $1, $1, 0
; MIPS32-NEXT:    mov.d $f2, $f0
; MIPS32-NEXT:    movz.d $f2, $f12, $1
; MIPS32-NEXT:    mtc1 $zero, $f4
; MIPS32-NEXT:    mtc1 $zero, $f5
; MIPS32-NEXT:    c.eq.d $f0, $f4
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    movt.d $f0, $f2, $fcc0
; MIPS32R5-LABEL: maximum_double_nnan:
; MIPS32R5:       # %bb.0:
; MIPS32R5-NEXT:    mov.d $f0, $f14
; MIPS32R5-NEXT:    c.ule.d $f12, $f14
; MIPS32R5-NEXT:    movf.d $f0, $f12, $fcc0
; MIPS32R5-NEXT:    cvt.s.d $f1, $f12
; MIPS32R5-NEXT:    mfc1 $1, $f1
; MIPS32R5-NEXT:    mov.d $f1, $f0
; MIPS32R5-NEXT:    movz.d $f1, $f12, $1
; MIPS32R5-NEXT:    mtc1 $zero, $f2
; MIPS32R5-NEXT:    mthc1 $zero, $f2
; MIPS32R5-NEXT:    c.eq.d $f0, $f2
; MIPS32R5-NEXT:    jr $ra
; MIPS32R5-NEXT:    movt.d $f0, $f1, $fcc0
  %z = call nnan double @llvm.maximum.f64(double %x, double %y)
  ret double %z
}

define float @minimum_float(float %x, float %y) {
; MIPS32R6-LABEL: minimum_float:
; MIPS32R6:       # %bb.0:
; MIPS32R6-NEXT:    min.s $f1, $f12, $f14
; MIPS32R6-NEXT:    cmp.un.s $f0, $f12, $f14
; MIPS32R6-NEXT:    lui $1, %hi($CPI6_0)
; MIPS32R6-NEXT:    lwc1 $f2, %lo($CPI6_0)($1)
; MIPS32R6-NEXT:    jr $ra
; MIPS32R6-NEXT:    sel.s $f0, $f1, $f2
;
; MIPS64R2-LABEL: minimum_float:
; MIPS64R2:       # %bb.0:
; MIPS64R2-NEXT:    mov.s $f0, $f13
; MIPS64R2-NEXT:    c.un.s $f13, $f13
; MIPS64R2-NEXT:    movt.s $f12, $f13, $fcc0
; MIPS64R2-NEXT:    c.ult.s $f12, $f13
; MIPS64R2-NEXT:    movt.s $f0, $f12, $fcc0
; MIPS64R2-NEXT:    mfc1 $1, $f12
; MIPS64R2-NEXT:    slti $1, $1, 0
; MIPS64R2-NEXT:    mov.s $f1, $f0
; MIPS64R2-NEXT:    movn.s $f1, $f12, $1
; MIPS64R2-NEXT:    mtc1 $zero, $f2
; MIPS64R2-NEXT:    c.eq.s $f0, $f2
; MIPS64R2-NEXT:    jr $ra
; MIPS64R2-NEXT:    movt.s $f0, $f1, $fcc0
;
; MIPS64-LABEL: minimum_float:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    mov.s $f0, $f13
; MIPS64-NEXT:    c.un.s $f13, $f13
; MIPS64-NEXT:    movt.s $f12, $f13, $fcc0
; MIPS64-NEXT:    c.ult.s $f12, $f13
; MIPS64-NEXT:    movt.s $f0, $f12, $fcc0
; MIPS64-NEXT:    mfc1 $1, $f12
; MIPS64-NEXT:    slti $1, $1, 0
; MIPS64-NEXT:    mov.s $f1, $f0
; MIPS64-NEXT:    movn.s $f1, $f12, $1
; MIPS64-NEXT:    mtc1 $zero, $f2
; MIPS64-NEXT:    c.eq.s $f0, $f2
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    movt.s $f0, $f1, $fcc0
;
; MIPS32R2-LABEL: minimum_float:
; MIPS32R2:       # %bb.0:
; MIPS32R2-NEXT:    mov.s $f0, $f14
; MIPS32R2-NEXT:    c.un.s $f14, $f14
; MIPS32R2-NEXT:    movt.s $f12, $f14, $fcc0
; MIPS32R2-NEXT:    c.ult.s $f12, $f14
; MIPS32R2-NEXT:    movt.s $f0, $f12, $fcc0
; MIPS32R2-NEXT:    mfc1 $1, $f12
; MIPS32R2-NEXT:    slti $1, $1, 0
; MIPS32R2-NEXT:    mov.s $f1, $f0
; MIPS32R2-NEXT:    movn.s $f1, $f12, $1
; MIPS32R2-NEXT:    mtc1 $zero, $f2
; MIPS32R2-NEXT:    c.eq.s $f0, $f2
; MIPS32R2-NEXT:    jr $ra
; MIPS32R2-NEXT:    movt.s $f0, $f1, $fcc0
;
; MIPS32-LABEL: minimum_float:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    mov.s $f0, $f14
; MIPS32-NEXT:    c.un.s $f14, $f14
; MIPS32-NEXT:    movt.s $f12, $f14, $fcc0
; MIPS32-NEXT:    c.ult.s $f12, $f14
; MIPS32-NEXT:    movt.s $f0, $f12, $fcc0
; MIPS32-NEXT:    mfc1 $1, $f12
; MIPS32-NEXT:    slti $1, $1, 0
; MIPS32-NEXT:    mov.s $f1, $f0
; MIPS32-NEXT:    movn.s $f1, $f12, $1
; MIPS32-NEXT:    mtc1 $zero, $f2
; MIPS32-NEXT:    c.eq.s $f0, $f2
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    movt.s $f0, $f1, $fcc0
; MIPS32R5-LABEL: minimum_float:
; MIPS32R5:       # %bb.0:
; MIPS32R5-NEXT:    mov.s $f0, $f14
; MIPS32R5-NEXT:    c.un.s $f12, $f12
; MIPS32R5-NEXT:    movt.s $f12, $f14, $fcc0
; MIPS32R5-NEXT:    c.un.s $f14, $f14
; MIPS32R5-NEXT:    movt.s $f0, $f12, $fcc0
; MIPS32R5-NEXT:    c.olt.s $f12, $f0
; MIPS32R5-NEXT:    movt.s $f0, $f12, $fcc0
; MIPS32R5-NEXT:    mfc1 $1, $f12
; MIPS32R5-NEXT:    lui $2, 32768
; MIPS32R5-NEXT:    xor $1, $1, $2
; MIPS32R5-NEXT:    mov.s $f1, $f0
; MIPS32R5-NEXT:    movz.s $f1, $f12, $1
; MIPS32R5-NEXT:    mtc1 $zero, $f2
; MIPS32R5-NEXT:    c.eq.s $f0, $f2
; MIPS32R5-NEXT:    jr $ra
; MIPS32R5-NEXT:    movt.s $f0, $f1, $fcc0
  %z = call float @llvm.minimum.f32(float %x, float %y)
  ret float %z
}

define float @minimum_float_nsz(float %x, float %y) {
; MIPS32R6-LABEL: minimum_float_nsz:
; MIPS32R6:       # %bb.0:
; MIPS32R6-NEXT:    min.s $f1, $f12, $f14
; MIPS32R6-NEXT:    cmp.un.s $f0, $f12, $f14
; MIPS32R6-NEXT:    lui $1, %hi($CPI7_0)
; MIPS32R6-NEXT:    lwc1 $f2, %lo($CPI7_0)($1)
; MIPS32R6-NEXT:    jr $ra
; MIPS32R6-NEXT:    sel.s $f0, $f1, $f2
;
; MIPS64R2-LABEL: minimum_float_nsz:
; MIPS64R2:       # %bb.0:
; MIPS64R2-NEXT:    mov.s $f0, $f13
; MIPS64R2-NEXT:    c.un.s $f13, $f13
; MIPS64R2-NEXT:    movt.s $f12, $f13, $fcc0
; MIPS64R2-NEXT:    c.ult.s $f12, $f13
; MIPS64R2-NEXT:    jr $ra
; MIPS64R2-NEXT:    movt.s $f0, $f12, $fcc0
;
; MIPS64-LABEL: minimum_float_nsz:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    mov.s $f0, $f13
; MIPS64-NEXT:    c.un.s $f13, $f13
; MIPS64-NEXT:    movt.s $f12, $f13, $fcc0
; MIPS64-NEXT:    c.ult.s $f12, $f13
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    movt.s $f0, $f12, $fcc0
;
; MIPS32R2-LABEL: minimum_float_nsz:
; MIPS32R2:       # %bb.0:
; MIPS32R2-NEXT:    mov.s $f0, $f14
; MIPS32R2-NEXT:    c.un.s $f14, $f14
; MIPS32R2-NEXT:    movt.s $f12, $f14, $fcc0
; MIPS32R2-NEXT:    c.ult.s $f12, $f14
; MIPS32R2-NEXT:    jr $ra
; MIPS32R2-NEXT:    movt.s $f0, $f12, $fcc0
;
; MIPS32-LABEL: minimum_float_nsz:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    mov.s $f0, $f14
; MIPS32-NEXT:    c.un.s $f14, $f14
; MIPS32-NEXT:    movt.s $f12, $f14, $fcc0
; MIPS32-NEXT:    c.ult.s $f12, $f14
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    movt.s $f0, $f12, $fcc0
; MIPS32R5-LABEL: minimum_float_nsz:
; MIPS32R5:       # %bb.0:
; MIPS32R5-NEXT:    mov.s $f0, $f14
; MIPS32R5-NEXT:    c.un.s $f12, $f12
; MIPS32R5-NEXT:    movt.s $f12, $f14, $fcc0
; MIPS32R5-NEXT:    c.un.s $f14, $f14
; MIPS32R5-NEXT:    movt.s $f0, $f12, $fcc0
; MIPS32R5-NEXT:    c.olt.s $f12, $f0
; MIPS32R5-NEXT:    jr $ra
; MIPS32R5-NEXT:    movt.s $f0, $f12, $fcc0
  %z = call nsz float @llvm.minimum.f32(float %x, float %y)
  ret float %z
}

define float @minimum_float_nnan(float %x, float %y) {
; MIPS32R6-LABEL: minimum_float_nnan:
; MIPS32R6:       # %bb.0:
; MIPS32R6-NEXT:    jr $ra
; MIPS32R6-NEXT:    min.s $f0, $f12, $f14
;
; MIPS64R2-LABEL: minimum_float_nnan:
; MIPS64R2:       # %bb.0:
; MIPS64R2-NEXT:    mov.s $f0, $f13
; MIPS64R2-NEXT:    c.ult.s $f12, $f13
; MIPS64R2-NEXT:    movt.s $f0, $f12, $fcc0
; MIPS64R2-NEXT:    mfc1 $1, $f12
; MIPS64R2-NEXT:    slti $1, $1, 0
; MIPS64R2-NEXT:    mov.s $f1, $f0
; MIPS64R2-NEXT:    movn.s $f1, $f12, $1
; MIPS64R2-NEXT:    mtc1 $zero, $f2
; MIPS64R2-NEXT:    c.eq.s $f0, $f2
; MIPS64R2-NEXT:    jr $ra
; MIPS64R2-NEXT:    movt.s $f0, $f1, $fcc0
;
; MIPS64-LABEL: minimum_float_nnan:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    mov.s $f0, $f13
; MIPS64-NEXT:    c.ult.s $f12, $f13
; MIPS64-NEXT:    movt.s $f0, $f12, $fcc0
; MIPS64-NEXT:    mfc1 $1, $f12
; MIPS64-NEXT:    slti $1, $1, 0
; MIPS64-NEXT:    mov.s $f1, $f0
; MIPS64-NEXT:    movn.s $f1, $f12, $1
; MIPS64-NEXT:    mtc1 $zero, $f2
; MIPS64-NEXT:    c.eq.s $f0, $f2
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    movt.s $f0, $f1, $fcc0
;
; MIPS32R2-LABEL: minimum_float_nnan:
; MIPS32R2:       # %bb.0:
; MIPS32R2-NEXT:    mov.s $f0, $f14
; MIPS32R2-NEXT:    c.ult.s $f12, $f14
; MIPS32R2-NEXT:    movt.s $f0, $f12, $fcc0
; MIPS32R2-NEXT:    mfc1 $1, $f12
; MIPS32R2-NEXT:    slti $1, $1, 0
; MIPS32R2-NEXT:    mov.s $f1, $f0
; MIPS32R2-NEXT:    movn.s $f1, $f12, $1
; MIPS32R2-NEXT:    mtc1 $zero, $f2
; MIPS32R2-NEXT:    c.eq.s $f0, $f2
; MIPS32R2-NEXT:    jr $ra
; MIPS32R2-NEXT:    movt.s $f0, $f1, $fcc0
;
; MIPS32-LABEL: minimum_float_nnan:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    mov.s $f0, $f14
; MIPS32-NEXT:    c.ult.s $f12, $f14
; MIPS32-NEXT:    movt.s $f0, $f12, $fcc0
; MIPS32-NEXT:    mfc1 $1, $f12
; MIPS32-NEXT:    slti $1, $1, 0
; MIPS32-NEXT:    mov.s $f1, $f0
; MIPS32-NEXT:    movn.s $f1, $f12, $1
; MIPS32-NEXT:    mtc1 $zero, $f2
; MIPS32-NEXT:    c.eq.s $f0, $f2
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    movt.s $f0, $f1, $fcc0
; MIPS32R5-LABEL: minimum_float_nnan:
; MIPS32R5:       # %bb.0:
; MIPS32R5-NEXT:    mov.s $f0, $f14
; MIPS32R5-NEXT:    c.olt.s $f12, $f14
; MIPS32R5-NEXT:    movt.s $f0, $f12, $fcc0
; MIPS32R5-NEXT:    mfc1 $1, $f12
; MIPS32R5-NEXT:    lui $2, 32768
; MIPS32R5-NEXT:    xor $1, $1, $2
; MIPS32R5-NEXT:    mov.s $f1, $f0
; MIPS32R5-NEXT:    movz.s $f1, $f12, $1
; MIPS32R5-NEXT:    mtc1 $zero, $f2
; MIPS32R5-NEXT:    c.eq.s $f0, $f2
; MIPS32R5-NEXT:    jr $ra
; MIPS32R5-NEXT:    movt.s $f0, $f1, $fcc0
  %z = call nnan float @llvm.minimum.f32(float %x, float %y)
  ret float %z
}

define double @minimum_double(double %x, double %y) {
; MIPS32R6-LABEL: minimum_double:
; MIPS32R6:       # %bb.0:
; MIPS32R6-NEXT:    min.d $f1, $f12, $f14
; MIPS32R6-NEXT:    cmp.un.d $f0, $f12, $f14
; MIPS32R6-NEXT:    lui $1, %hi($CPI9_0)
; MIPS32R6-NEXT:    ldc1 $f2, %lo($CPI9_0)($1)
; MIPS32R6-NEXT:    jr $ra
; MIPS32R6-NEXT:    sel.d $f0, $f1, $f2
;
; MIPS64R2-LABEL: minimum_double:
; MIPS64R2:       # %bb.0:
; MIPS64R2-NEXT:    mov.d $f0, $f13
; MIPS64R2-NEXT:    c.un.d $f13, $f13
; MIPS64R2-NEXT:    movt.d $f12, $f13, $fcc0
; MIPS64R2-NEXT:    c.ult.d $f12, $f13
; MIPS64R2-NEXT:    movt.d $f0, $f12, $fcc0
; MIPS64R2-NEXT:    dmfc1 $1, $f12
; MIPS64R2-NEXT:    slti $1, $1, 0
; MIPS64R2-NEXT:    mov.d $f1, $f0
; MIPS64R2-NEXT:    movn.d $f1, $f12, $1
; MIPS64R2-NEXT:    dmtc1 $zero, $f2
; MIPS64R2-NEXT:    c.eq.d $f0, $f2
; MIPS64R2-NEXT:    jr $ra
; MIPS64R2-NEXT:    movt.d $f0, $f1, $fcc0
;
; MIPS64-LABEL: minimum_double:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    mov.d $f0, $f13
; MIPS64-NEXT:    c.un.d $f13, $f13
; MIPS64-NEXT:    movt.d $f12, $f13, $fcc0
; MIPS64-NEXT:    c.ult.d $f12, $f13
; MIPS64-NEXT:    movt.d $f0, $f12, $fcc0
; MIPS64-NEXT:    dmfc1 $1, $f12
; MIPS64-NEXT:    slti $1, $1, 0
; MIPS64-NEXT:    mov.d $f1, $f0
; MIPS64-NEXT:    movn.d $f1, $f12, $1
; MIPS64-NEXT:    dmtc1 $zero, $f2
; MIPS64-NEXT:    c.eq.d $f0, $f2
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    movt.d $f0, $f1, $fcc0
;
; MIPS32R2-LABEL: minimum_double:
; MIPS32R2:       # %bb.0:
; MIPS32R2-NEXT:    mov.d $f0, $f14
; MIPS32R2-NEXT:    c.un.d $f14, $f14
; MIPS32R2-NEXT:    movt.d $f12, $f14, $fcc0
; MIPS32R2-NEXT:    c.ult.d $f12, $f14
; MIPS32R2-NEXT:    movt.d $f0, $f12, $fcc0
; MIPS32R2-NEXT:    cvt.s.d $f2, $f12
; MIPS32R2-NEXT:    mfc1 $1, $f2
; MIPS32R2-NEXT:    slti $1, $1, 0
; MIPS32R2-NEXT:    mov.d $f2, $f0
; MIPS32R2-NEXT:    movn.d $f2, $f12, $1
; MIPS32R2-NEXT:    mtc1 $zero, $f4
; MIPS32R2-NEXT:    mthc1 $zero, $f4
; MIPS32R2-NEXT:    c.eq.d $f0, $f4
; MIPS32R2-NEXT:    jr $ra
; MIPS32R2-NEXT:    movt.d $f0, $f2, $fcc0
;
; MIPS32-LABEL: minimum_double:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    mov.d $f0, $f14
; MIPS32-NEXT:    c.un.d $f14, $f14
; MIPS32-NEXT:    movt.d $f12, $f14, $fcc0
; MIPS32-NEXT:    c.ult.d $f12, $f14
; MIPS32-NEXT:    movt.d $f0, $f12, $fcc0
; MIPS32-NEXT:    cvt.s.d $f2, $f12
; MIPS32-NEXT:    mfc1 $1, $f2
; MIPS32-NEXT:    slti $1, $1, 0
; MIPS32-NEXT:    mov.d $f2, $f0
; MIPS32-NEXT:    movn.d $f2, $f12, $1
; MIPS32-NEXT:    mtc1 $zero, $f4
; MIPS32-NEXT:    mtc1 $zero, $f5
; MIPS32-NEXT:    c.eq.d $f0, $f4
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    movt.d $f0, $f2, $fcc0
; MIPS32R5-LABEL: minimum_double:
; MIPS32R5:       # %bb.0:
; MIPS32R5-NEXT:    mov.d $f0, $f14
; MIPS32R5-NEXT:    c.un.d $f12, $f12
; MIPS32R5-NEXT:    movt.d $f12, $f14, $fcc0
; MIPS32R5-NEXT:    c.un.d $f14, $f14
; MIPS32R5-NEXT:    movt.d $f0, $f12, $fcc0
; MIPS32R5-NEXT:    c.olt.d $f12, $f0
; MIPS32R5-NEXT:    movt.d $f0, $f12, $fcc0
; MIPS32R5-NEXT:    cvt.s.d $f1, $f12
; MIPS32R5-NEXT:    mfc1 $1, $f1
; MIPS32R5-NEXT:    lui $2, 32768
; MIPS32R5-NEXT:    xor $1, $1, $2
; MIPS32R5-NEXT:    mov.d $f1, $f0
; MIPS32R5-NEXT:    movz.d $f1, $f12, $1
; MIPS32R5-NEXT:    mtc1 $zero, $f2
; MIPS32R5-NEXT:    mthc1 $zero, $f2
; MIPS32R5-NEXT:    c.eq.d $f0, $f2
; MIPS32R5-NEXT:    jr $ra
; MIPS32R5-NEXT:    movt.d $f0, $f1, $fcc0
  %z = call double @llvm.minimum.f64(double %x, double %y)
  ret double %z
}

define double @minimum_double_nsz(double %x, double %y) {
; MIPS32R6-LABEL: minimum_double_nsz:
; MIPS32R6:       # %bb.0:
; MIPS32R6-NEXT:    min.d $f1, $f12, $f14
; MIPS32R6-NEXT:    cmp.un.d $f0, $f12, $f14
; MIPS32R6-NEXT:    lui $1, %hi($CPI10_0)
; MIPS32R6-NEXT:    ldc1 $f2, %lo($CPI10_0)($1)
; MIPS32R6-NEXT:    jr $ra
; MIPS32R6-NEXT:    sel.d $f0, $f1, $f2
;
; MIPS64R2-LABEL: minimum_double_nsz:
; MIPS64R2:       # %bb.0:
; MIPS64R2-NEXT:    mov.d $f0, $f13
; MIPS64R2-NEXT:    c.un.d $f13, $f13
; MIPS64R2-NEXT:    movt.d $f12, $f13, $fcc0
; MIPS64R2-NEXT:    c.ult.d $f12, $f13
; MIPS64R2-NEXT:    jr $ra
; MIPS64R2-NEXT:    movt.d $f0, $f12, $fcc0
;
; MIPS64-LABEL: minimum_double_nsz:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    mov.d $f0, $f13
; MIPS64-NEXT:    c.un.d $f13, $f13
; MIPS64-NEXT:    movt.d $f12, $f13, $fcc0
; MIPS64-NEXT:    c.ult.d $f12, $f13
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    movt.d $f0, $f12, $fcc0
;
; MIPS32R2-LABEL: minimum_double_nsz:
; MIPS32R2:       # %bb.0:
; MIPS32R2-NEXT:    mov.d $f0, $f14
; MIPS32R2-NEXT:    c.un.d $f14, $f14
; MIPS32R2-NEXT:    movt.d $f12, $f14, $fcc0
; MIPS32R2-NEXT:    c.ult.d $f12, $f14
; MIPS32R2-NEXT:    jr $ra
; MIPS32R2-NEXT:    movt.d $f0, $f12, $fcc0
;
; MIPS32-LABEL: minimum_double_nsz:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    mov.d $f0, $f14
; MIPS32-NEXT:    c.un.d $f14, $f14
; MIPS32-NEXT:    movt.d $f12, $f14, $fcc0
; MIPS32-NEXT:    c.ult.d $f12, $f14
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    movt.d $f0, $f12, $fcc0
; MIPS32R5-LABEL: minimum_double_nsz:
; MIPS32R5:       # %bb.0:
; MIPS32R5-NEXT:    mov.d $f0, $f14
; MIPS32R5-NEXT:    c.un.d $f12, $f12
; MIPS32R5-NEXT:    movt.d $f12, $f14, $fcc0
; MIPS32R5-NEXT:    c.un.d $f14, $f14
; MIPS32R5-NEXT:    movt.d $f0, $f12, $fcc0
; MIPS32R5-NEXT:    c.olt.d $f12, $f0
; MIPS32R5-NEXT:    jr $ra
; MIPS32R5-NEXT:    movt.d $f0, $f12, $fcc0
  %z = call nsz double @llvm.minimum.f64(double %x, double %y)
  ret double %z
}

define double @minimum_double_nnan(double %x, double %y) {
; MIPS32R6-LABEL: minimum_double_nnan:
; MIPS32R6:       # %bb.0:
; MIPS32R6-NEXT:    jr $ra
; MIPS32R6-NEXT:    min.d $f0, $f12, $f14
;
; MIPS64R2-LABEL: minimum_double_nnan:
; MIPS64R2:       # %bb.0:
; MIPS64R2-NEXT:    mov.d $f0, $f13
; MIPS64R2-NEXT:    c.ult.d $f12, $f13
; MIPS64R2-NEXT:    movt.d $f0, $f12, $fcc0
; MIPS64R2-NEXT:    dmfc1 $1, $f12
; MIPS64R2-NEXT:    slti $1, $1, 0
; MIPS64R2-NEXT:    mov.d $f1, $f0
; MIPS64R2-NEXT:    movn.d $f1, $f12, $1
; MIPS64R2-NEXT:    dmtc1 $zero, $f2
; MIPS64R2-NEXT:    c.eq.d $f0, $f2
; MIPS64R2-NEXT:    jr $ra
; MIPS64R2-NEXT:    movt.d $f0, $f1, $fcc0
;
; MIPS64-LABEL: minimum_double_nnan:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    mov.d $f0, $f13
; MIPS64-NEXT:    c.ult.d $f12, $f13
; MIPS64-NEXT:    movt.d $f0, $f12, $fcc0
; MIPS64-NEXT:    dmfc1 $1, $f12
; MIPS64-NEXT:    slti $1, $1, 0
; MIPS64-NEXT:    mov.d $f1, $f0
; MIPS64-NEXT:    movn.d $f1, $f12, $1
; MIPS64-NEXT:    dmtc1 $zero, $f2
; MIPS64-NEXT:    c.eq.d $f0, $f2
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    movt.d $f0, $f1, $fcc0
;
; MIPS32R2-LABEL: minimum_double_nnan:
; MIPS32R2:       # %bb.0:
; MIPS32R2-NEXT:    mov.d $f0, $f14
; MIPS32R2-NEXT:    c.ult.d $f12, $f14
; MIPS32R2-NEXT:    movt.d $f0, $f12, $fcc0
; MIPS32R2-NEXT:    cvt.s.d $f2, $f12
; MIPS32R2-NEXT:    mfc1 $1, $f2
; MIPS32R2-NEXT:    slti $1, $1, 0
; MIPS32R2-NEXT:    mov.d $f2, $f0
; MIPS32R2-NEXT:    movn.d $f2, $f12, $1
; MIPS32R2-NEXT:    mtc1 $zero, $f4
; MIPS32R2-NEXT:    mthc1 $zero, $f4
; MIPS32R2-NEXT:    c.eq.d $f0, $f4
; MIPS32R2-NEXT:    jr $ra
; MIPS32R2-NEXT:    movt.d $f0, $f2, $fcc0
;
; MIPS32-LABEL: minimum_double_nnan:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    mov.d $f0, $f14
; MIPS32-NEXT:    c.ult.d $f12, $f14
; MIPS32-NEXT:    movt.d $f0, $f12, $fcc0
; MIPS32-NEXT:    cvt.s.d $f2, $f12
; MIPS32-NEXT:    mfc1 $1, $f2
; MIPS32-NEXT:    slti $1, $1, 0
; MIPS32-NEXT:    mov.d $f2, $f0
; MIPS32-NEXT:    movn.d $f2, $f12, $1
; MIPS32-NEXT:    mtc1 $zero, $f4
; MIPS32-NEXT:    mtc1 $zero, $f5
; MIPS32-NEXT:    c.eq.d $f0, $f4
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    movt.d $f0, $f2, $fcc0
; MIPS32R5-LABEL: minimum_double_nnan:
; MIPS32R5:       # %bb.0:
; MIPS32R5-NEXT:    mov.d $f0, $f14
; MIPS32R5-NEXT:    c.olt.d $f12, $f14
; MIPS32R5-NEXT:    movt.d $f0, $f12, $fcc0
; MIPS32R5-NEXT:    cvt.s.d $f1, $f12
; MIPS32R5-NEXT:    mfc1 $1, $f1
; MIPS32R5-NEXT:    lui $2, 32768
; MIPS32R5-NEXT:    xor $1, $1, $2
; MIPS32R5-NEXT:    mov.d $f1, $f0
; MIPS32R5-NEXT:    movz.d $f1, $f12, $1
; MIPS32R5-NEXT:    mtc1 $zero, $f2
; MIPS32R5-NEXT:    mthc1 $zero, $f2
; MIPS32R5-NEXT:    c.eq.d $f0, $f2
; MIPS32R5-NEXT:    jr $ra
; MIPS32R5-NEXT:    movt.d $f0, $f1, $fcc0
  %z = call nnan double @llvm.minimum.f64(double %x, double %y)
  ret double %z
}
