; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=mips -mcpu=mips32r2 < %s | FileCheck %s
; RUN: llc -mtriple=mips -mattr=+micromips < %s | FileCheck %s --check-prefix=CHECK-MM

define i32 @get_rounding() {
; CHECK-LABEL: get_rounding:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cfc1 $1, 31
; CHECK-NEXT:    andi $2, $1, 3
; CHECK-NEXT:    not $1, $1
; CHECK-NEXT:    andi $1, $1, 2
; CHECK-NEXT:    srl $1, $1, 1
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    xor $2, $2, $1
;
; CHECK-MM-LABEL: get_rounding:
; CHECK-MM:       # %bb.0: # %entry
; CHECK-MM-NEXT:    cfc1 $2, 31
; CHECK-MM-NEXT:    andi16 $3, $2, 3
; CHECK-MM-NEXT:    not16 $2, $2
; CHECK-MM-NEXT:    andi16 $2, $2, 2
; CHECK-MM-NEXT:    srl16 $2, $2, 1
; CHECK-MM-NEXT:    xor16 $2, $3
; CHECK-MM-NEXT:    jrc $ra
entry:
  %0 = call i32 @llvm.get.rounding()
  ret i32 %0
}

define void @set_rounding(i32 %a) {
; CHECK-LABEL: set_rounding:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addiu $1, $zero, -4
; CHECK-NEXT:    cfc1 $2, 31
; CHECK-NEXT:    and $1, $2, $1
; CHECK-NEXT:    andi $2, $4, 2
; CHECK-NEXT:    sltiu $2, $2, 1
; CHECK-NEXT:    xor $2, $4, $2
; CHECK-NEXT:    or $1, $1, $2
; CHECK-NEXT:    ctc1 $1, 31
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    nop
;
; CHECK-MM-LABEL: set_rounding:
; CHECK-MM:       # %bb.0: # %entry
; CHECK-MM-NEXT:    addiu $2, $zero, -4
; CHECK-MM-NEXT:    cfc1 $3, 31
; CHECK-MM-NEXT:    and16 $3, $2
; CHECK-MM-NEXT:    andi16 $2, $4, 2
; CHECK-MM-NEXT:    sltiu $2, $2, 1
; CHECK-MM-NEXT:    xor16 $2, $4
; CHECK-MM-NEXT:    or16 $2, $3
; CHECK-MM-NEXT:    ctc1 $2, 31
; CHECK-MM-NEXT:    jrc $ra
entry:
  call void @llvm.set.rounding(i32 %a)
  ret void
}
