; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=mips < %s | FileCheck %s --check-prefix=MIPS32
; RUN: llc -mtriple=mips64 < %s | FileCheck %s --check-prefix=MIPS64

define dso_local void @read_double(ptr nocapture noundef readonly %0) local_unnamed_addr #0 {
; MIPS32-LABEL: read_double:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    lw $2, 4($4)
; MIPS32-NEXT:    lw $3, 0($4)
; MIPS32-NEXT:    #APP
; MIPS32-NEXT:    #NO_APP
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    nop
;
; MIPS64-LABEL: read_double:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    ld $2, 0($4)
; MIPS64-NEXT:    #APP
; MIPS64-NEXT:    #NO_APP
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    nop
  %2 = load double, ptr %0, align 8
  tail call void asm sideeffect "", "r,~{$1}"(double %2)
  ret void
}

define dso_local void @read_float(ptr nocapture noundef readonly %0) local_unnamed_addr #0 {
; MIPS32-LABEL: read_float:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    lw $2, 0($4)
; MIPS32-NEXT:    #APP
; MIPS32-NEXT:    #NO_APP
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    nop
;
; MIPS64-LABEL: read_float:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    lw $2, 0($4)
; MIPS64-NEXT:    #APP
; MIPS64-NEXT:    #NO_APP
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    nop
  %2 = load float, ptr %0, align 8
  tail call void asm sideeffect "", "r,~{$1}"(float %2)
  ret void
}

attributes #0 = { "target-features"="+soft-float" "use-soft-float"="true" }
