; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mipsisa32r6-unknown-linux-gnu -o - %s | FileCheck %s --check-prefix=R6
; RUN: llc -mtriple=mipsel-unknown-linux-gnu -o - %s | FileCheck %s --check-prefix=R2


define i1 @isnan_float(float %x) nounwind {
; R6-LABEL: isnan_float:
; R6:       # %bb.0:
; R6-NEXT:    class.s $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 3
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isnan_float:
; R2:       # %bb.0:
; R2-NEXT:    addiu $2, $zero, 1
; R2-NEXT:    c.un.s $f12, $f12
; R2-NEXT:    jr $ra
; R2-NEXT:    movf $2, $zero, $fcc0
  %1 = call i1 @llvm.is.fpclass.f32(float %x, i32 3)  ; nan
  ret i1 %1
}

define i1 @isnan_double(double %x) nounwind {
; R6-LABEL: isnan_double:
; R6:       # %bb.0:
; R6-NEXT:    class.d $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 3
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isnan_double:
; R2:       # %bb.0:
; R2-NEXT:    addiu $2, $zero, 1
; R2-NEXT:    c.un.d $f12, $f12
; R2-NEXT:    jr $ra
; R2-NEXT:    movf $2, $zero, $fcc0
  %1 = call i1 @llvm.is.fpclass.f64(double %x, i32 3)  ; nan
  ret i1 %1
}

define i1 @isnan_float_strictfp(float %x) strictfp nounwind {
; R6-LABEL: isnan_float_strictfp:
; R6:       # %bb.0:
; R6-NEXT:    class.s $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 3
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isnan_float_strictfp:
; R2:       # %bb.0:
; R2-NEXT:    lui $1, 32767
; R2-NEXT:    ori $1, $1, 65535
; R2-NEXT:    mfc1 $2, $f12
; R2-NEXT:    and $1, $2, $1
; R2-NEXT:    lui $2, 32640
; R2-NEXT:    jr $ra
; R2-NEXT:    slt $2, $2, $1
  %1 = call i1 @llvm.is.fpclass.f32(float %x, i32 3) strictfp ; nan
  ret i1 %1
}

define i1 @isnan_double_strictfp(double %x) strictfp nounwind {
; R6-LABEL: isnan_double_strictfp:
; R6:       # %bb.0:
; R6-NEXT:    class.d $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 3
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isnan_double_strictfp:
; R2:       # %bb.0:
; R2-NEXT:    addiu $sp, $sp, -8
; R2-NEXT:    sdc1 $f12, 0($sp)
; R2-NEXT:    lui $1, 32767
; R2-NEXT:    ori $1, $1, 65535
; R2-NEXT:    lw $2, 4($sp)
; R2-NEXT:    and $1, $2, $1
; R2-NEXT:    lui $3, 32752
; R2-NEXT:    slt $2, $3, $1
; R2-NEXT:    xor $1, $1, $3
; R2-NEXT:    lw $3, 0($sp)
; R2-NEXT:    sltu $3, $zero, $3
; R2-NEXT:    movz $2, $3, $1
; R2-NEXT:    jr $ra
; R2-NEXT:    addiu $sp, $sp, 8
  %1 = call i1 @llvm.is.fpclass.f64(double %x, i32 3) strictfp ; nan
  ret i1 %1
}

define i1 @isinf_float(float %x) nounwind {
; R6-LABEL: isinf_float:
; R6:       # %bb.0:
; R6-NEXT:    class.s $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 68
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isinf_float:
; R2:       # %bb.0:
; R2-NEXT:    lui $1, 32767
; R2-NEXT:    ori $1, $1, 65535
; R2-NEXT:    mfc1 $2, $f12
; R2-NEXT:    and $1, $2, $1
; R2-NEXT:    lui $2, 32640
; R2-NEXT:    xor $1, $1, $2
; R2-NEXT:    jr $ra
; R2-NEXT:    sltiu $2, $1, 1
  %1 = call i1 @llvm.is.fpclass.f32(float %x, i32 516)  ; 0x204 = "inf"
  ret i1 %1
}

define i1 @isfinite_float(float %x) nounwind {
; R6-LABEL: isfinite_float:
; R6:       # %bb.0:
; R6-NEXT:    class.s $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 952
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isfinite_float:
; R2:       # %bb.0:
; R2-NEXT:    mfc1 $1, $f12
; R2-NEXT:    srl $1, $1, 23
; R2-NEXT:    andi $1, $1, 255
; R2-NEXT:    jr $ra
; R2-NEXT:    sltiu $2, $1, 255
  %1 = call i1 @llvm.is.fpclass.f32(float %x, i32 504)  ; 0x1f8 = "finite"
  ret i1 %1
}

define i1 @isnormal_float(float %x) nounwind {
; R6-LABEL: isnormal_float:
; R6:       # %bb.0:
; R6-NEXT:    class.s $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 136
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isnormal_float:
; R2:       # %bb.0:
; R2-NEXT:    lui $1, 32767
; R2-NEXT:    ori $1, $1, 65535
; R2-NEXT:    mfc1 $2, $f12
; R2-NEXT:    and $1, $2, $1
; R2-NEXT:    lui $2, 65408
; R2-NEXT:    addu $1, $1, $2
; R2-NEXT:    srl $1, $1, 24
; R2-NEXT:    jr $ra
; R2-NEXT:    sltiu $2, $1, 127
  %1 = call i1 @llvm.is.fpclass.f32(float %x, i32 264)  ; 0x108 = "normal"
  ret i1 %1
}

define i1 @issubnormal_float(float %x) nounwind {
; R6-LABEL: issubnormal_float:
; R6:       # %bb.0:
; R6-NEXT:    class.s $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 272
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: issubnormal_float:
; R2:       # %bb.0:
; R2-NEXT:    lui $1, 32767
; R2-NEXT:    ori $1, $1, 65535
; R2-NEXT:    mfc1 $2, $f12
; R2-NEXT:    and $1, $2, $1
; R2-NEXT:    addiu $1, $1, -1
; R2-NEXT:    lui $2, 127
; R2-NEXT:    ori $2, $2, 65535
; R2-NEXT:    jr $ra
; R2-NEXT:    sltu $2, $1, $2
  %1 = call i1 @llvm.is.fpclass.f32(float %x, i32 144)  ; 0x90 = "subnormal"
  ret i1 %1
}

define i1 @iszero_float(float %x) nounwind {
; R6-LABEL: iszero_float:
; R6:       # %bb.0:
; R6-NEXT:    class.s $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 544
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: iszero_float:
; R2:       # %bb.0:
; R2-NEXT:    mtc1 $zero, $f0
; R2-NEXT:    addiu $2, $zero, 1
; R2-NEXT:    c.eq.s $f12, $f0
; R2-NEXT:    jr $ra
; R2-NEXT:    movf $2, $zero, $fcc0
  %1 = call i1 @llvm.is.fpclass.f32(float %x, i32 96)  ; 0x60 = "zero"
  ret i1 %1
}

define i1 @issnan_float(float %x) nounwind {
; R6-LABEL: issnan_float:
; R6:       # %bb.0:
; R6-NEXT:    class.s $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 1
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: issnan_float:
; R2:       # %bb.0:
; R2-NEXT:    lui $1, 32767
; R2-NEXT:    ori $1, $1, 65535
; R2-NEXT:    mfc1 $2, $f12
; R2-NEXT:    and $1, $2, $1
; R2-NEXT:    lui $2, 32704
; R2-NEXT:    slt $2, $1, $2
; R2-NEXT:    lui $3, 32640
; R2-NEXT:    slt $1, $3, $1
; R2-NEXT:    jr $ra
; R2-NEXT:    and $2, $1, $2
  %1 = call i1 @llvm.is.fpclass.f32(float %x, i32 1)
  ret i1 %1
}

define i1 @issnan_double(double %x) nounwind {
; R6-LABEL: issnan_double:
; R6:       # %bb.0:
; R6-NEXT:    class.d $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 1
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: issnan_double:
; R2:       # %bb.0:
; R2-NEXT:    addiu $sp, $sp, -8
; R2-NEXT:    sdc1 $f12, 0($sp)
; R2-NEXT:    lui $1, 32767
; R2-NEXT:    ori $1, $1, 65535
; R2-NEXT:    lw $2, 4($sp)
; R2-NEXT:    and $1, $2, $1
; R2-NEXT:    lui $2, 32752
; R2-NEXT:    slt $3, $2, $1
; R2-NEXT:    xor $2, $1, $2
; R2-NEXT:    lw $4, 0($sp)
; R2-NEXT:    sltu $4, $zero, $4
; R2-NEXT:    movz $3, $4, $2
; R2-NEXT:    lui $2, 32760
; R2-NEXT:    slt $1, $1, $2
; R2-NEXT:    and $2, $3, $1
; R2-NEXT:    jr $ra
; R2-NEXT:    addiu $sp, $sp, 8
  %1 = call i1 @llvm.is.fpclass.f64(double %x, i32 1)
  ret i1 %1
}

define i1 @isqnan_float(float %x) nounwind {
; R6-LABEL: isqnan_float:
; R6:       # %bb.0:
; R6-NEXT:    class.s $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 2
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isqnan_float:
; R2:       # %bb.0:
; R2-NEXT:    lui $1, 32767
; R2-NEXT:    ori $1, $1, 65535
; R2-NEXT:    mfc1 $2, $f12
; R2-NEXT:    and $1, $2, $1
; R2-NEXT:    lui $2, 32703
; R2-NEXT:    ori $2, $2, 65535
; R2-NEXT:    jr $ra
; R2-NEXT:    slt $2, $2, $1
  %1 = call i1 @llvm.is.fpclass.f32(float %x, i32 2)
  ret i1 %1
}

define i1 @isqnan_double(double %x) nounwind {
; R6-LABEL: isqnan_double:
; R6:       # %bb.0:
; R6-NEXT:    class.d $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 2
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isqnan_double:
; R2:       # %bb.0:
; R2-NEXT:    addiu $sp, $sp, -8
; R2-NEXT:    sdc1 $f12, 0($sp)
; R2-NEXT:    lui $1, 32767
; R2-NEXT:    ori $1, $1, 65535
; R2-NEXT:    lw $2, 4($sp)
; R2-NEXT:    and $1, $2, $1
; R2-NEXT:    lui $2, 32759
; R2-NEXT:    ori $2, $2, 65535
; R2-NEXT:    slt $2, $2, $1
; R2-NEXT:    jr $ra
; R2-NEXT:    addiu $sp, $sp, 8
  %1 = call i1 @llvm.is.fpclass.f64(double %x, i32 2)
  ret i1 %1
}

define i1 @isposzero_double(double %x) nounwind {
; R6-LABEL: isposzero_double:
; R6:       # %bb.0:
; R6-NEXT:    class.d $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 512
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isposzero_double:
; R2:       # %bb.0:
; R2-NEXT:    addiu $sp, $sp, -8
; R2-NEXT:    sdc1 $f12, 0($sp)
; R2-NEXT:    lw $1, 4($sp)
; R2-NEXT:    lw $2, 0($sp)
; R2-NEXT:    or $1, $2, $1
; R2-NEXT:    sltiu $2, $1, 1
; R2-NEXT:    jr $ra
; R2-NEXT:    addiu $sp, $sp, 8
  %1 = call i1 @llvm.is.fpclass.f64(double %x, i32 64)
  ret i1 %1
}

define i1 @isnegzero_double(double %x) nounwind {
; R6-LABEL: isnegzero_double:
; R6:       # %bb.0:
; R6-NEXT:    class.d $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 32
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isnegzero_double:
; R2:       # %bb.0:
; R2-NEXT:    addiu $sp, $sp, -8
; R2-NEXT:    sdc1 $f12, 0($sp)
; R2-NEXT:    lui $1, 32768
; R2-NEXT:    lw $2, 4($sp)
; R2-NEXT:    xor $1, $2, $1
; R2-NEXT:    lw $2, 0($sp)
; R2-NEXT:    or $1, $2, $1
; R2-NEXT:    sltiu $2, $1, 1
; R2-NEXT:    jr $ra
; R2-NEXT:    addiu $sp, $sp, 8
  %1 = call i1 @llvm.is.fpclass.f64(double %x, i32 32)
  ret i1 %1
}

define i1 @isposnormal_double(double %x) nounwind {
; R6-LABEL: isposnormal_double:
; R6:       # %bb.0:
; R6-NEXT:    class.d $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 128
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isposnormal_double:
; R2:       # %bb.0:
; R2-NEXT:    addiu $sp, $sp, -8
; R2-NEXT:    sdc1 $f12, 0($sp)
; R2-NEXT:    addiu $1, $zero, -1
; R2-NEXT:    lw $2, 4($sp)
; R2-NEXT:    slt $1, $1, $2
; R2-NEXT:    lui $3, 32767
; R2-NEXT:    ori $3, $3, 65535
; R2-NEXT:    and $2, $2, $3
; R2-NEXT:    lui $3, 65520
; R2-NEXT:    addu $2, $2, $3
; R2-NEXT:    srl $2, $2, 21
; R2-NEXT:    sltiu $2, $2, 1023
; R2-NEXT:    and $2, $2, $1
; R2-NEXT:    jr $ra
; R2-NEXT:    addiu $sp, $sp, 8
  %1 = call i1 @llvm.is.fpclass.f64(double %x, i32 256)
  ret i1 %1
}

define i1 @isnegnormal_double(double %x) nounwind {
; R6-LABEL: isnegnormal_double:
; R6:       # %bb.0:
; R6-NEXT:    class.d $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 8
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isnegnormal_double:
; R2:       # %bb.0:
; R2-NEXT:    addiu $sp, $sp, -8
; R2-NEXT:    sdc1 $f12, 0($sp)
; R2-NEXT:    lui $1, 32767
; R2-NEXT:    ori $1, $1, 65535
; R2-NEXT:    lw $2, 4($sp)
; R2-NEXT:    and $1, $2, $1
; R2-NEXT:    lui $3, 65520
; R2-NEXT:    addu $1, $1, $3
; R2-NEXT:    srl $1, $1, 21
; R2-NEXT:    sltiu $1, $1, 1023
; R2-NEXT:    slti $2, $2, 0
; R2-NEXT:    and $2, $1, $2
; R2-NEXT:    jr $ra
; R2-NEXT:    addiu $sp, $sp, 8
  %1 = call i1 @llvm.is.fpclass.f64(double %x, i32 8)
  ret i1 %1
}

define i1 @isnormal_double(double %x) nounwind {
; R6-LABEL: isnormal_double:
; R6:       # %bb.0:
; R6-NEXT:    class.d $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 136
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isnormal_double:
; R2:       # %bb.0:
; R2-NEXT:    addiu $sp, $sp, -8
; R2-NEXT:    sdc1 $f12, 0($sp)
; R2-NEXT:    lui $1, 32767
; R2-NEXT:    ori $1, $1, 65535
; R2-NEXT:    lw $2, 4($sp)
; R2-NEXT:    and $1, $2, $1
; R2-NEXT:    lui $2, 65520
; R2-NEXT:    addu $1, $1, $2
; R2-NEXT:    srl $1, $1, 21
; R2-NEXT:    sltiu $2, $1, 1023
; R2-NEXT:    jr $ra
; R2-NEXT:    addiu $sp, $sp, 8
  %1 = call i1 @llvm.is.fpclass.f64(double %x, i32 264)
  ret i1 %1
}

define i1 @isclass_00d_double(double %x) nounwind {
; R6-LABEL: isclass_00d_double:
; R6:       # %bb.0:
; R6-NEXT:    class.d $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 13
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isclass_00d_double:
; R2:       # %bb.0:
; R2-NEXT:    addiu $sp, $sp, -8
; R2-NEXT:    sdc1 $f12, 0($sp)
; R2-NEXT:    lui $1, 32767
; R2-NEXT:    ori $1, $1, 65535
; R2-NEXT:    lw $2, 4($sp)
; R2-NEXT:    and $1, $2, $1
; R2-NEXT:    lui $3, 32752
; R2-NEXT:    slt $4, $3, $1
; R2-NEXT:    xor $3, $1, $3
; R2-NEXT:    lw $5, 0($sp)
; R2-NEXT:    sltu $6, $zero, $5
; R2-NEXT:    movz $4, $6, $3
; R2-NEXT:    lui $3, 32760
; R2-NEXT:    slt $3, $1, $3
; R2-NEXT:    and $3, $4, $3
; R2-NEXT:    lui $4, 65520
; R2-NEXT:    xor $6, $2, $4
; R2-NEXT:    or $5, $5, $6
; R2-NEXT:    sltiu $5, $5, 1
; R2-NEXT:    or $3, $5, $3
; R2-NEXT:    addu $1, $1, $4
; R2-NEXT:    srl $1, $1, 21
; R2-NEXT:    sltiu $1, $1, 1023
; R2-NEXT:    slti $2, $2, 0
; R2-NEXT:    and $1, $1, $2
; R2-NEXT:    or $2, $3, $1
; R2-NEXT:    jr $ra
; R2-NEXT:    addiu $sp, $sp, 8
  %1 = call i1 @llvm.is.fpclass.f64(double %x, i32 13)
  ret i1 %1
}

define i1 @isclass_1c0_float(float %x) nounwind {
; R6-LABEL: isclass_1c0_float:
; R6:       # %bb.0:
; R6-NEXT:    class.s $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 896
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isclass_1c0_float:
; R2:       # %bb.0:
; R2-NEXT:    mfc1 $1, $f12
; R2-NEXT:    srl $1, $1, 23
; R2-NEXT:    jr $ra
; R2-NEXT:    sltiu $2, $1, 255
  %1 = call i1 @llvm.is.fpclass.f32(float %x, i32 448)
  ret i1 %1
}

define i1 @isclass_positive_float(float %x) nounwind {
; R6-LABEL: isclass_positive_float:
; R6:       # %bb.0:
; R6-NEXT:    class.s $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 960
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isclass_positive_float:
; R2:       # %bb.0:
; R2-NEXT:    lui $1, 32640
; R2-NEXT:    ori $1, $1, 1
; R2-NEXT:    mfc1 $2, $f12
; R2-NEXT:    jr $ra
; R2-NEXT:    sltu $2, $2, $1
  %1 = call i1 @llvm.is.fpclass.f32(float %x, i32 960)
  ret i1 %1
}

define i1 @isclass_positive_nnan_float(float nofpclass(nan) %x) nounwind {
; R6-LABEL: isclass_positive_nnan_float:
; R6:       # %bb.0:
; R6-NEXT:    class.s $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 960
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isclass_positive_nnan_float:
; R2:       # %bb.0:
; R2-NEXT:    mfc1 $1, $f12
; R2-NEXT:    addiu $2, $zero, -1
; R2-NEXT:    jr $ra
; R2-NEXT:    slt $2, $2, $1
  %1 = call i1 @llvm.is.fpclass.f32(float %x, i32 960)
  ret i1 %1
}

define i1 @isclass_positive_nnan_double(double nofpclass(nan) %x) nounwind {
; R6-LABEL: isclass_positive_nnan_double:
; R6:       # %bb.0:
; R6-NEXT:    class.d $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 960
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isclass_positive_nnan_double:
; R2:       # %bb.0:
; R2-NEXT:    cvt.s.d $f0, $f12
; R2-NEXT:    mfc1 $1, $f0
; R2-NEXT:    addiu $2, $zero, -1
; R2-NEXT:    jr $ra
; R2-NEXT:    slt $2, $2, $1
  %1 = call i1 @llvm.is.fpclass.f64(double %x, i32 960)
  ret i1 %1
}

define i1 @isclass_negative_float(float %x) nounwind {
; R6-LABEL: isclass_negative_float:
; R6:       # %bb.0:
; R6-NEXT:    class.s $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 60
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isclass_negative_float:
; R2:       # %bb.0:
; R2-NEXT:    addiu $1, $zero, 1
; R2-NEXT:    c.un.s $f12, $f12
; R2-NEXT:    movt $1, $zero, $fcc0
; R2-NEXT:    mfc1 $2, $f12
; R2-NEXT:    slti $2, $2, 0
; R2-NEXT:    jr $ra
; R2-NEXT:    and $2, $1, $2
  %1 = call i1 @llvm.is.fpclass.f32(float %x, i32 60)
  ret i1 %1
}

define i1 @isclass_negative_nnan_float(float nofpclass(nan) %x) nounwind {
; R6-LABEL: isclass_negative_nnan_float:
; R6:       # %bb.0:
; R6-NEXT:    class.s $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 60
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isclass_negative_nnan_float:
; R2:       # %bb.0:
; R2-NEXT:    mfc1 $1, $f12
; R2-NEXT:    jr $ra
; R2-NEXT:    srl $2, $1, 31
  %1 = call i1 @llvm.is.fpclass.f32(float %x, i32 60)
  ret i1 %1
}

define i1 @isclass_negative_nnan_double(double nofpclass(nan) %x) nounwind {
; R6-LABEL: isclass_negative_nnan_double:
; R6:       # %bb.0:
; R6-NEXT:    class.d $f0, $f12
; R6-NEXT:    mfc1 $1, $f0
; R6-NEXT:    andi $1, $1, 60
; R6-NEXT:    jr $ra
; R6-NEXT:    sltu $2, $zero, $1
;
; R2-LABEL: isclass_negative_nnan_double:
; R2:       # %bb.0:
; R2-NEXT:    cvt.s.d $f0, $f12
; R2-NEXT:    mfc1 $1, $f0
; R2-NEXT:    jr $ra
; R2-NEXT:    srl $2, $1, 31
  %1 = call i1 @llvm.is.fpclass.f64(double %x, i32 60)
  ret i1 %1
}

declare i1 @llvm.is.fpclass.f32(float, i32)
declare i1 @llvm.is.fpclass.f64(double, i32)
