; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mipsel-linux-gnu -march=mipsel -mattr=mips16 -mattr=+soft-float -mips16-hard-float -relocation-model=static     < %s | FileCheck %s -check-prefix=ci

@i = global i32 0, align 4
@j = common global i32 0, align 4
@k = common global i32 0, align 4

; Function Attrs: nounwind optsize
define i32 @x0() #0 {
; ci-LABEL: x0:
; ci:       # %bb.0: # %entry
; ci-NEXT:    li $2, %hi(i)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    lw $3, %lo(i)($2)
; ci-NEXT:    beqz $3, $BB0_2
; ci-NEXT:  # %bb.1: # %if.else
; ci-NEXT:    li $3, 1
; ci-NEXT:    #APP
; ci-NEXT:    .set push
; ci-NEXT:    .set at
; ci-NEXT:    .set macro
; ci-NEXT:    .set reorder
; ci-EMPTY:
; ci-NEXT:    .space 1004
; ci-EMPTY:
; ci-NEXT:    .set pop
; ci-NEXT:    #NO_APP
; ci-NEXT:    b $BB0_3 # 16 bit inst
; ci-NEXT:  $BB0_2: # %if.then
; ci-NEXT:    li $3, 0
; ci-NEXT:    #APP
; ci-NEXT:    .set push
; ci-NEXT:    .set at
; ci-NEXT:    .set macro
; ci-NEXT:    .set reorder
; ci-EMPTY:
; ci-NEXT:    .space 1000
; ci-EMPTY:
; ci-NEXT:    .set pop
; ci-NEXT:    #NO_APP
; ci-NEXT:  $BB0_3: # %if.end
; ci-NEXT:    sw $3, %lo(i)($2)
; ci-NEXT:    li $2, 0
; ci-NEXT:    jrc $ra
entry:
  %0 = load i32, i32* @i, align 4, !tbaa !1
  %cmp = icmp eq i32 %0, 0
  br i1 %cmp, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  tail call void asm sideeffect ".space 1000", ""() #1, !srcloc !5
  br label %if.end

if.else:                                          ; preds = %entry
  tail call void asm sideeffect ".space 1004", ""() #1, !srcloc !6
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  %storemerge = phi i32 [ 1, %if.else ], [ 0, %if.then ]
  store i32 %storemerge, i32* @i, align 4, !tbaa !1
  ret i32 0
}

; Function Attrs: nounwind optsize
define i32 @x1() #0 {
; ci-LABEL: x1:
; ci:       # %bb.0: # %entry
; ci-NEXT:    li $2, %hi(i)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    lw $3, %lo(i)($2)
; ci-NEXT:    bnez $3, $BB1_1 # 16 bit inst
; ci-NEXT:    jal $BB1_2 # branch
; ci-NEXT:    nop
; ci-NEXT:  $BB1_1: # %if.else
; ci-NEXT:    li $3, 1
; ci-NEXT:    #APP
; ci-NEXT:    .set push
; ci-NEXT:    .set at
; ci-NEXT:    .set macro
; ci-NEXT:    .set reorder
; ci-EMPTY:
; ci-NEXT:    .space 1000004
; ci-EMPTY:
; ci-NEXT:    .set pop
; ci-NEXT:    #NO_APP
; ci-NEXT:    jal $BB1_3 # branch
; ci-NEXT:    nop
; ci-NEXT:    .p2align 2
; ci-NEXT:  $BB1_2: # %if.then
; ci-NEXT:    li $3, 0
; ci-NEXT:    #APP
; ci-NEXT:    .set push
; ci-NEXT:    .set at
; ci-NEXT:    .set macro
; ci-NEXT:    .set reorder
; ci-EMPTY:
; ci-NEXT:    .space 1000000
; ci-EMPTY:
; ci-NEXT:    .set pop
; ci-NEXT:    #NO_APP
; ci-NEXT:    .p2align 2
; ci-NEXT:  $BB1_3: # %if.end
; ci-NEXT:    sw $3, %lo(i)($2)
; ci-NEXT:    li $2, 0
; ci-NEXT:    jrc $ra
entry:
  %0 = load i32, i32* @i, align 4, !tbaa !1
  %cmp = icmp eq i32 %0, 0
  br i1 %cmp, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  tail call void asm sideeffect ".space 1000000", ""() #1, !srcloc !7
  br label %if.end

if.else:                                          ; preds = %entry
  tail call void asm sideeffect ".space 1000004", ""() #1, !srcloc !8
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  %storemerge = phi i32 [ 1, %if.else ], [ 0, %if.then ]
  store i32 %storemerge, i32* @i, align 4, !tbaa !1
  ret i32 0
}


; Function Attrs: nounwind optsize
define i32 @y0() #0 {
; ci-LABEL: y0:
; ci:       # %bb.0: # %entry
; ci-NEXT:    li $2, %hi(i)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    lw $2, %lo(i)($2)
; ci-NEXT:    beqz $2, $BB2_2
; ci-NEXT:  # %bb.1: # %if.else
; ci-NEXT:    li $2, %hi(j)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    li $3, 55
; ci-NEXT:    sw $3, %lo(j)($2)
; ci-NEXT:    #APP
; ci-NEXT:    .set push
; ci-NEXT:    .set at
; ci-NEXT:    .set macro
; ci-NEXT:    .set reorder
; ci-EMPTY:
; ci-NEXT:    .space 1004
; ci-EMPTY:
; ci-NEXT:    .set pop
; ci-NEXT:    #NO_APP
; ci-NEXT:    b $BB2_3 # 16 bit inst
; ci-NEXT:  $BB2_2: # %if.then
; ci-NEXT:    li $2, %hi(j)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    li $3, 10
; ci-NEXT:    sw $3, %lo(j)($2)
; ci-NEXT:    #APP
; ci-NEXT:    .set push
; ci-NEXT:    .set at
; ci-NEXT:    .set macro
; ci-NEXT:    .set reorder
; ci-EMPTY:
; ci-NEXT:    .space 1000
; ci-EMPTY:
; ci-NEXT:    .set pop
; ci-NEXT:    #NO_APP
; ci-NEXT:  $BB2_3: # %if.end
; ci-NEXT:    li $2, 0
; ci-NEXT:    jrc $ra
entry:
  %0 = load i32, i32* @i, align 4, !tbaa !1
  %cmp = icmp eq i32 %0, 0
  br i1 %cmp, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  store i32 10, i32* @j, align 4, !tbaa !1
  tail call void asm sideeffect ".space 1000", ""() #1, !srcloc !9
  br label %if.end

if.else:                                          ; preds = %entry
  store i32 55, i32* @j, align 4, !tbaa !1
  tail call void asm sideeffect ".space 1004", ""() #1, !srcloc !10
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  ret i32 0
}

; Function Attrs: nounwind optsize
define i32 @y1() #0 {
; ci-LABEL: y1:
; ci:       # %bb.0: # %entry
; ci-NEXT:    li $2, %hi(i)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    lw $2, %lo(i)($2)
; ci-NEXT:    bnez $2, $BB3_1 # 16 bit inst
; ci-NEXT:    jal $BB3_2 # branch
; ci-NEXT:    nop
; ci-NEXT:  $BB3_1: # %if.else
; ci-NEXT:    li $2, %hi(j)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    li $3, 55
; ci-NEXT:    sw $3, %lo(j)($2)
; ci-NEXT:    #APP
; ci-NEXT:    .set push
; ci-NEXT:    .set at
; ci-NEXT:    .set macro
; ci-NEXT:    .set reorder
; ci-EMPTY:
; ci-NEXT:    .space 1000004
; ci-EMPTY:
; ci-NEXT:    .set pop
; ci-NEXT:    #NO_APP
; ci-NEXT:    jal $BB3_3 # branch
; ci-NEXT:    nop
; ci-NEXT:    .p2align 2
; ci-NEXT:  $BB3_2: # %if.then
; ci-NEXT:    li $2, %hi(j)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    li $3, 10
; ci-NEXT:    sw $3, %lo(j)($2)
; ci-NEXT:    #APP
; ci-NEXT:    .set push
; ci-NEXT:    .set at
; ci-NEXT:    .set macro
; ci-NEXT:    .set reorder
; ci-EMPTY:
; ci-NEXT:    .space 1000000
; ci-EMPTY:
; ci-NEXT:    .set pop
; ci-NEXT:    #NO_APP
; ci-NEXT:    .p2align 2
; ci-NEXT:  $BB3_3: # %if.end
; ci-NEXT:    li $2, 0
; ci-NEXT:    jrc $ra
entry:
  %0 = load i32, i32* @i, align 4, !tbaa !1
  %cmp = icmp eq i32 %0, 0
  br i1 %cmp, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  store i32 10, i32* @j, align 4, !tbaa !1
  tail call void asm sideeffect ".space 1000000", ""() #1, !srcloc !11
  br label %if.end

if.else:                                          ; preds = %entry
  store i32 55, i32* @j, align 4, !tbaa !1
  tail call void asm sideeffect ".space 1000004", ""() #1, !srcloc !12
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  ret i32 0
}


; Function Attrs: nounwind optsize
define void @z0() #0 {
; ci-LABEL: z0:
; ci:       # %bb.0: # %entry
; ci-NEXT:    li $2, %hi(j)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    lw $2, %lo(j)($2)
; ci-NEXT:    li $3, %hi(i)
; ci-NEXT:    sll $3, $3, 16
; ci-NEXT:    lw $3, %lo(i)($3)
; ci-NEXT:    cmp $3, $2
; ci-NEXT:    bteqz $BB4_2
; ci-NEXT:  # %bb.1: # %if.else
; ci-NEXT:    li $2, %hi(k)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    #APP
; ci-NEXT:    .set push
; ci-NEXT:    .set at
; ci-NEXT:    .set macro
; ci-NEXT:    .set reorder
; ci-EMPTY:
; ci-NEXT:    .space 10004
; ci-EMPTY:
; ci-NEXT:    .set pop
; ci-NEXT:    #NO_APP
; ci-NEXT:    li $3, 2
; ci-NEXT:    sw $3, %lo(k)($2)
; ci-NEXT:    jrc $ra
; ci-NEXT:  $BB4_2: # %if.then
; ci-NEXT:    li $2, %hi(k)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    li $3, 1
; ci-NEXT:    sw $3, %lo(k)($2)
; ci-NEXT:    #APP
; ci-NEXT:    .set push
; ci-NEXT:    .set at
; ci-NEXT:    .set macro
; ci-NEXT:    .set reorder
; ci-EMPTY:
; ci-NEXT:    .space 10000
; ci-EMPTY:
; ci-NEXT:    .set pop
; ci-NEXT:    #NO_APP
; ci-NEXT:    jrc $ra
entry:
  %0 = load i32, i32* @i, align 4, !tbaa !1
  %1 = load i32, i32* @j, align 4, !tbaa !1
  %cmp = icmp eq i32 %0, %1
  br i1 %cmp, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  store i32 1, i32* @k, align 4, !tbaa !1
  tail call void asm sideeffect ".space 10000", ""() #1, !srcloc !13
  br label %if.end

if.else:                                          ; preds = %entry
  tail call void asm sideeffect ".space 10004", ""() #1, !srcloc !14
  store i32 2, i32* @k, align 4, !tbaa !1
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  ret void
}


; Function Attrs: nounwind optsize
define void @z1() #0 {
; ci-LABEL: z1:
; ci:       # %bb.0: # %entry
; ci-NEXT:    li $2, %hi(j)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    lw $2, %lo(j)($2)
; ci-NEXT:    li $3, %hi(i)
; ci-NEXT:    sll $3, $3, 16
; ci-NEXT:    lw $3, %lo(i)($3)
; ci-NEXT:    cmp $3, $2
; ci-NEXT:    btnez $BB5_1 # 16 bit inst
; ci-NEXT:    jal $BB5_2 # branch
; ci-NEXT:    nop
; ci-NEXT:  $BB5_1: # %if.else
; ci-NEXT:    li $2, %hi(k)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    #APP
; ci-NEXT:    .set push
; ci-NEXT:    .set at
; ci-NEXT:    .set macro
; ci-NEXT:    .set reorder
; ci-EMPTY:
; ci-NEXT:    .space 10000004
; ci-EMPTY:
; ci-NEXT:    .set pop
; ci-NEXT:    #NO_APP
; ci-NEXT:    li $3, 2
; ci-NEXT:    sw $3, %lo(k)($2)
; ci-NEXT:    jrc $ra
; ci-NEXT:    .p2align 2
; ci-NEXT:  $BB5_2: # %if.then
; ci-NEXT:    li $2, %hi(k)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    li $3, 1
; ci-NEXT:    sw $3, %lo(k)($2)
; ci-NEXT:    #APP
; ci-NEXT:    .set push
; ci-NEXT:    .set at
; ci-NEXT:    .set macro
; ci-NEXT:    .set reorder
; ci-EMPTY:
; ci-NEXT:    .space 10000000
; ci-EMPTY:
; ci-NEXT:    .set pop
; ci-NEXT:    #NO_APP
; ci-NEXT:    jrc $ra
entry:
  %0 = load i32, i32* @i, align 4, !tbaa !1
  %1 = load i32, i32* @j, align 4, !tbaa !1
  %cmp = icmp eq i32 %0, %1
  br i1 %cmp, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  store i32 1, i32* @k, align 4, !tbaa !1
  tail call void asm sideeffect ".space 10000000", ""() #1, !srcloc !15
  br label %if.end

if.else:                                          ; preds = %entry
  tail call void asm sideeffect ".space 10000004", ""() #1, !srcloc !16
  store i32 2, i32* @k, align 4, !tbaa !1
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  ret void
}


; Function Attrs: nounwind optsize
define void @z3() #0 {
; ci-LABEL: z3:
; ci:       # %bb.0: # %entry
; ci-NEXT:    li $2, %hi(i)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    lw $4, %lo(i)($2)
; ci-NEXT:    li $3, %hi(j)
; ci-NEXT:    sll $3, $3, 16
; ci-NEXT:    lw $5, %lo(j)($3)
; ci-NEXT:    slt $5, $4
; ci-NEXT:    bteqz $BB6_2
; ci-NEXT:  $BB6_1: # %if.then
; ci-NEXT:    # =>This Inner Loop Header: Depth=1
; ci-NEXT:    #APP
; ci-NEXT:    .set push
; ci-NEXT:    .set at
; ci-NEXT:    .set macro
; ci-NEXT:    .set reorder
; ci-EMPTY:
; ci-NEXT:    .space 10000
; ci-EMPTY:
; ci-NEXT:    .set pop
; ci-NEXT:    #NO_APP
; ci-NEXT:    lw $4, %lo(i)($2)
; ci-NEXT:    lw $5, %lo(j)($3)
; ci-NEXT:    slt $5, $4
; ci-NEXT:    btnez $BB6_1
; ci-NEXT:  $BB6_2: # %if.end
; ci-NEXT:    jrc $ra
entry:
  %0 = load i32, i32* @i, align 4, !tbaa !1
  %1 = load i32, i32* @j, align 4, !tbaa !1
  %cmp1 = icmp sgt i32 %0, %1
  br i1 %cmp1, label %if.then, label %if.end

if.then:                                          ; preds = %entry, %if.then
  tail call void asm sideeffect ".space 10000", ""() #1, !srcloc !17
  %2 = load i32, i32* @i, align 4, !tbaa !1
  %3 = load i32, i32* @j, align 4, !tbaa !1
  %cmp = icmp sgt i32 %2, %3
  br i1 %cmp, label %if.then, label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

; Function Attrs: nounwind optsize
define void @z4() #0 {
; ci-LABEL: z4:
; ci:       # %bb.0: # %entry
; ci-NEXT:    li $2, %hi(i)
; ci-NEXT:    sll $2, $2, 16
; ci-NEXT:    lw $4, %lo(i)($2)
; ci-NEXT:    li $3, %hi(j)
; ci-NEXT:    sll $3, $3, 16
; ci-NEXT:    lw $5, %lo(j)($3)
; ci-NEXT:    slt $5, $4
; ci-NEXT:    btnez $BB7_1 # 16 bit inst
; ci-NEXT:    jal $BB7_2 # branch
; ci-NEXT:    nop
; ci-NEXT:    .p2align 2
; ci-NEXT:  $BB7_1: # %if.then
; ci-NEXT:    # =>This Inner Loop Header: Depth=1
; ci-NEXT:    #APP
; ci-NEXT:    .set push
; ci-NEXT:    .set at
; ci-NEXT:    .set macro
; ci-NEXT:    .set reorder
; ci-EMPTY:
; ci-NEXT:    .space 10000000
; ci-EMPTY:
; ci-NEXT:    .set pop
; ci-NEXT:    #NO_APP
; ci-NEXT:    lw $4, %lo(i)($2)
; ci-NEXT:    lw $5, %lo(j)($3)
; ci-NEXT:    slt $5, $4
; ci-NEXT:    bteqz $BB7_2 # 16 bit inst
; ci-NEXT:    jal $BB7_1 # branch
; ci-NEXT:    nop
; ci-NEXT:    .p2align 2
; ci-NEXT:  $BB7_2: # %if.end
; ci-NEXT:    jrc $ra
entry:
  %0 = load i32, i32* @i, align 4, !tbaa !1
  %1 = load i32, i32* @j, align 4, !tbaa !1
  %cmp1 = icmp sgt i32 %0, %1
  br i1 %cmp1, label %if.then, label %if.end

if.then:                                          ; preds = %entry, %if.then
  tail call void asm sideeffect ".space 10000000", ""() #1, !srcloc !18
  %2 = load i32, i32* @i, align 4, !tbaa !1
  %3 = load i32, i32* @j, align 4, !tbaa !1
  %cmp = icmp sgt i32 %2, %3
  br i1 %cmp, label %if.then, label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

attributes #0 = { nounwind optsize "less-precise-fpmad"="false" "frame-pointer"="none" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { nounwind }


!1 = !{!2, !2, i64 0}
!2 = !{!"int", !3, i64 0}
!3 = !{!"omnipotent char", !4, i64 0}
!4 = !{!"Simple C/C++ TBAA"}
!5 = !{i32 57}
!6 = !{i32 107}
!7 = !{i32 188}
!8 = !{i32 241}
!9 = !{i32 338}
!10 = !{i32 391}
!11 = !{i32 477}
!12 = !{i32 533}
!13 = !{i32 621}
!14 = !{i32 663}
!15 = !{i32 747}
!16 = !{i32 792}
!17 = !{i32 867}
!18 = !{i32 953}
