; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=mips64el -mcpu=mips4 < %s | FileCheck %s -check-prefixes=ACC
; RUN: llc -mtriple=mips64el -mcpu=mips64 < %s | FileCheck %s -check-prefixes=ACC
; RUN: llc -mtriple=mips64el -mcpu=mips64r2 < %s | FileCheck %s -check-prefixes=ACC
; RUN: llc -mtriple=mips64el -mcpu=mips64r6 < %s | FileCheck %s -check-prefixes=GPR

; FileCheck prefixes:
;   ACC - Targets with accumulator based mul/div (i.e. pre-MIPS32r6)
;   GPR - Targets with register based mul/div (i.e. MIPS32r6)

define i64 @m0(i64 %a0, i64 %a1) nounwind readnone {
; GPR-LABEL: m0:
; GPR:       # %bb.0: # %entry
; GPR-NEXT:    jr $ra
; GPR-NEXT:    dmul $2, $5, $4
entry:
  %mul = mul i64 %a1, %a0
  ret i64 %mul
}

define i64 @m1(i64 %a) nounwind readnone {
; ACC-LABEL: m1:
; ACC:       # %bb.0: # %entry
; ACC-NEXT:    lui $1, 21845
; ACC-NEXT:    daddiu $1, $1, 21845
; ACC-NEXT:    dsll $1, $1, 16
; ACC-NEXT:    daddiu $1, $1, 21845
; ACC-NEXT:    dsll $1, $1, 16
; ACC-NEXT:    daddiu $1, $1, 21846
; ACC-NEXT:    dmult $4, $1
; ACC-NEXT:    mfhi $1
; ACC-NEXT:    dsra $2, $4, 63
; ACC-NEXT:    jr $ra
; ACC-NEXT:    dsubu $2, $1, $2
;
; GPR-LABEL: m1:
; GPR:       # %bb.0: # %entry
; GPR-NEXT:    lui $1, 21845
; GPR-NEXT:    daddiu $1, $1, 21845
; GPR-NEXT:    dsll $1, $1, 16
; GPR-NEXT:    daddiu $1, $1, 21845
; GPR-NEXT:    dsll $1, $1, 16
; GPR-NEXT:    daddiu $1, $1, 21846
; GPR-NEXT:    dmuh $1, $4, $1
; GPR-NEXT:    dsra $2, $4, 63
; GPR-NEXT:    jr $ra
; GPR-NEXT:    dsubu $2, $1, $2
entry:


  %div = sdiv i64 %a, 3
  ret i64 %div
}

define i64 @d0(i64 %a0, i64 %a1) nounwind readnone {
; GPR-LABEL: d0:
; GPR:       # %bb.0: # %entry
; GPR-NEXT:    ddivu $2, $4, $5
; GPR-NEXT:    teq $5, $zero, 7
; GPR-NEXT:    jrc $ra
entry:
  %div = udiv i64 %a0, %a1
  ret i64 %div
}

define i64 @d1(i64 %a0, i64 %a1) nounwind readnone {
; GPR-LABEL: d1:
; GPR:       # %bb.0: # %entry
; GPR-NEXT:    ddiv $2, $4, $5
; GPR-NEXT:    teq $5, $zero, 7
; GPR-NEXT:    jrc $ra
entry:
  %div = sdiv i64 %a0, %a1
  ret i64 %div
}

define i64 @d2(i64 %a0, i64 %a1) nounwind readnone {
; GPR-LABEL: d2:
; GPR:       # %bb.0: # %entry
; GPR-NEXT:    dmodu $2, $4, $5
; GPR-NEXT:    teq $5, $zero, 7
; GPR-NEXT:    jrc $ra
entry:
  %rem = urem i64 %a0, %a1
  ret i64 %rem
}

define i64 @d3(i64 %a0, i64 %a1) nounwind readnone {
; GPR-LABEL: d3:
; GPR:       # %bb.0: # %entry
; GPR-NEXT:    dmod $2, $4, $5
; GPR-NEXT:    teq $5, $zero, 7
; GPR-NEXT:    jrc $ra
entry:
  %rem = srem i64 %a0, %a1
  ret i64 %rem
}
