# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mips -run-pass=postra-machine-sink -o - %s | FileCheck %s

---
name:            test_undef_use_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_undef_use_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $a0 = LUi 1
  ; CHECK-NEXT:   renamable $a1 = COPY killed renamable $a0, implicit undef $a2
  ; CHECK-NEXT:   $a2 = LUi 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $a1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   RetRA implicit $a1
  bb.0:
    successors: %bb.1

    renamable $a0 = LUi 1
    renamable $a1 = COPY killed renamable $a0, implicit undef $a2
    $a2 = LUi 0

  bb.1:
    liveins: $a1
    RetRA implicit $a1
...
---
name:            test_internal_read_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_internal_read_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $a0 = LUi 1
  ; CHECK-NEXT:   renamable $a1 = COPY killed renamable $a0, implicit-def $a2, implicit internal $a2
  ; CHECK-NEXT:   $a3 = LUi 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $a1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   RetRA implicit $a1
  bb.0:
    successors: %bb.1

    renamable $a0 = LUi 1
    renamable $a1 = COPY killed renamable $a0, implicit-def $a2, implicit internal $a2
    $a3 = LUi 0

  bb.1:
    liveins: $a1
    RetRA implicit $a1
...
