; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt --passes=sandbox-vectorizer -sbvec-passes='regions-from-bbs<null>' %s -S | FileCheck %s

define void @foo(i8 %v) {
; CHECK-LABEL: define void @foo(
; CHECK-SAME: i8 [[V:%.*]]) {
; CHECK-NEXT:  [[BBA:.*:]]
; CHECK-NEXT:    [[ADD0:%.*]] = add i8 [[V]], 0, !sandboxvec [[META0:![0-9]+]]
; CHECK-NEXT:    br label %[[BBB:.*]], !sandboxvec [[META0]]
; CHECK:       [[BBB]]:
; CHECK-NEXT:    [[ADD1:%.*]] = add i8 [[V]], 1, !sandboxvec [[META1:![0-9]+]]
; CHECK-NEXT:    br label %[[BBC:.*]], !sandboxvec [[META1]]
; CHECK:       [[BBC]]:
; CHECK-NEXT:    ret void, !sandboxvec [[META2:![0-9]+]]
;
bbA:
  %add0 = add i8 %v, 0
  br label %bbB

bbB:
  %add1 = add i8 %v, 1
  br label %bbC

bbC:
  ret void
}
;.
; CHECK: [[META0]] = distinct !{!"sandboxregion"}
; CHECK: [[META1]] = distinct !{!"sandboxregion"}
; CHECK: [[META2]] = distinct !{!"sandboxregion"}
;.
