; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=vector-combine -S %s | FileCheck %s

define i8 @fold_selects_from_bitcast_dominance(i8 %0, <2 x i32> %v) {
; CHECK-LABEL: define i8 @fold_selects_from_bitcast_dominance(
; CHECK-SAME: i8 [[TMP0:%.*]], <2 x i32> [[V:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i8 [[TMP0]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[COND]], <2 x i32> [[V]], <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to <8 x i8>
; CHECK-NEXT:    [[SHIFT:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> poison, <8 x i32> <i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[FOLDEXTEXTBINOP:%.*]] = add <8 x i8> [[TMP2]], [[SHIFT]]
; CHECK-NEXT:    [[SHIFT2:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> poison, <8 x i32> <i32 2, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[FOLDEXTEXTBINOP3:%.*]] = add <8 x i8> [[FOLDEXTEXTBINOP]], [[SHIFT2]]
; CHECK-NEXT:    [[SHIFT5:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> poison, <8 x i32> <i32 3, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[FOLDEXTEXTBINOP6:%.*]] = add <8 x i8> [[FOLDEXTEXTBINOP3]], [[SHIFT5]]
; CHECK-NEXT:    [[SHIFT8:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> poison, <8 x i32> <i32 4, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[FOLDEXTEXTBINOP9:%.*]] = add <8 x i8> [[FOLDEXTEXTBINOP6]], [[SHIFT8]]
; CHECK-NEXT:    [[SHIFT11:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> poison, <8 x i32> <i32 5, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[FOLDEXTEXTBINOP12:%.*]] = add <8 x i8> [[FOLDEXTEXTBINOP9]], [[SHIFT11]]
; CHECK-NEXT:    [[SHIFT14:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> poison, <8 x i32> <i32 6, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[FOLDEXTEXTBINOP15:%.*]] = add <8 x i8> [[FOLDEXTEXTBINOP12]], [[SHIFT14]]
; CHECK-NEXT:    [[SHIFT17:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> poison, <8 x i32> <i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[FOLDEXTEXTBINOP18:%.*]] = add <8 x i8> [[FOLDEXTEXTBINOP15]], [[SHIFT17]]
; CHECK-NEXT:    [[SUM6:%.*]] = extractelement <8 x i8> [[FOLDEXTEXTBINOP18]], i64 0
; CHECK-NEXT:    ret i8 [[SUM6]]
;
entry:
  %bc = bitcast <2 x i32> %v to <8 x i8>
  %e0 = extractelement <8 x i8> %bc, i64 0
  %cond = icmp eq i8 %0, 0
  %e1 = extractelement <8 x i8> %bc, i64 1
  %e2 = extractelement <8 x i8> %bc, i64 2
  %e3 = extractelement <8 x i8> %bc, i64 3
  %e4 = extractelement <8 x i8> %bc, i64 4
  %e5 = extractelement <8 x i8> %bc, i64 5
  %e6 = extractelement <8 x i8> %bc, i64 6
  %e7 = extractelement <8 x i8> %bc, i64 7
  %s0 = select i1 %cond, i8 %e0, i8 0
  %s1 = select i1 %cond, i8 %e1, i8 0
  %s2 = select i1 %cond, i8 %e2, i8 0
  %s3 = select i1 %cond, i8 %e3, i8 0
  %s4 = select i1 %cond, i8 %e4, i8 0
  %s5 = select i1 %cond, i8 %e5, i8 0
  %s6 = select i1 %cond, i8 %e6, i8 0
  %s7 = select i1 %cond, i8 %e7, i8 0
  %sum0 = add i8 %s0, %s1
  %sum1 = add i8 %sum0, %s2
  %sum2 = add i8 %sum1, %s3
  %sum3 = add i8 %sum2, %s4
  %sum4 = add i8 %sum3, %s5
  %sum5 = add i8 %sum4, %s6
  %sum6 = add i8 %sum5, %s7
  ret i8 %sum6
}

define i8 @fold_selects_from_bitcast_dominance_multiblock1(<4 x i32> %src, i8 %a, i1 %flag) {
; CHECK-LABEL: define i8 @fold_selects_from_bitcast_dominance_multiblock1(
; CHECK-SAME: <4 x i32> [[SRC:%.*]], i8 [[A:%.*]], i1 [[FLAG:%.*]]) {
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i8 [[A]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[COND]], <4 x i32> [[SRC]], <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[TMP1]] to <16 x i8>
; CHECK-NEXT:    br i1 [[FLAG]], label %[[FIRST:.*]], label %[[SECOND:.*]]
; CHECK:       [[FIRST]]:
; CHECK-NEXT:    [[S0:%.*]] = extractelement <16 x i8> [[TMP2]], i32 0
; CHECK-NEXT:    br label %[[END:.*]]
; CHECK:       [[SECOND]]:
; CHECK-NEXT:    [[S1:%.*]] = extractelement <16 x i8> [[TMP2]], i32 7
; CHECK-NEXT:    br label %[[END]]
; CHECK:       [[END]]:
; CHECK-NEXT:    [[RES:%.*]] = phi i8 [ [[S0]], %[[FIRST]] ], [ [[S1]], %[[SECOND]] ]
; CHECK-NEXT:    ret i8 [[RES]]
;
  %bc = bitcast <4 x i32> %src to <16 x i8>
  %cond = icmp eq i8 %a, 0
  br i1 %flag, label %first, label %second

first:
  %e0 = extractelement <16 x i8> %bc, i32 0
  %s0 = select i1 %cond, i8 %e0, i8 0
  br label %end

second:
  %e1 = extractelement <16 x i8> %bc, i32 7
  %s1 = select i1 %cond, i8 %e1, i8 0
  br label %end

end:
  %res = phi i8 [%s0, %first], [%s1, %second]
  ret i8 %res
}

define i8 @fold_selects_from_bitcast_dominance_multiblock2(<4 x i64> %v, i8 %a, i1 %flag) {
; CHECK-LABEL: define i8 @fold_selects_from_bitcast_dominance_multiblock2(
; CHECK-SAME: <4 x i64> [[V:%.*]], i8 [[A:%.*]], i1 [[FLAG:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[FIRST:.*]]
; CHECK:       [[FIRST]]:
; CHECK-NEXT:    br label %[[SECOND:.*]]
; CHECK:       [[SECOND]]:
; CHECK-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i8 [[A]], 0
; CHECK-NEXT:    [[TMP0:%.*]] = select i1 [[TOBOOL_NOT]], <4 x i64> [[V]], <4 x i64> zeroinitializer
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i64> [[TMP0]] to <32 x i8>
; CHECK-NEXT:    br i1 [[FLAG]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[NARROW8:%.*]] = extractelement <32 x i8> [[TMP1]], i64 0
; CHECK-NEXT:    ret i8 [[NARROW8]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    [[NARROW:%.*]] = extractelement <32 x i8> [[TMP1]], i64 7
; CHECK-NEXT:    ret i8 [[NARROW]]
;
entry:
  %0 = bitcast <4 x i64> %v to <32 x i8>
  br label %first

first:
  %vecext56 = extractelement <32 x i8> %0, i64 0
  %vecext36 = extractelement <32 x i8> %0, i64 7
  br label %second

second:
  %tobool.not = icmp eq i8 %a, 0
  br i1 %flag, label %then, label %else

then:
  %narrow8 = select i1 %tobool.not, i8 %vecext56, i8 0
  ret i8 %narrow8

else:
  %narrow = select i1 %tobool.not, i8 %vecext36, i8 0
  ret i8 %narrow
}

define i8 @fold_selects_from_bitcast_dominance_multiblock3(<4 x i64> %v, <4 x i64> %v2, i8 %a, i1 %flag1, i1 %cond2) {
; CHECK-LABEL: define i8 @fold_selects_from_bitcast_dominance_multiblock3(
; CHECK-SAME: <4 x i64> [[V:%.*]], <4 x i64> [[V2:%.*]], i8 [[A:%.*]], i1 [[FLAG1:%.*]], i1 [[COND2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = select i1 [[COND2]], <4 x i64> [[V]], <4 x i64> zeroinitializer
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i64> [[TMP0]] to <32 x i8>
; CHECK-NEXT:    br label %[[FIRST:.*]]
; CHECK:       [[FIRST]]:
; CHECK-NEXT:    br label %[[SECOND:.*]]
; CHECK:       [[SECOND]]:
; CHECK-NEXT:    [[COND1:%.*]] = icmp eq i8 [[A]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[COND1]], <4 x i64> [[V]], <4 x i64> zeroinitializer
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x i64> [[TMP2]] to <32 x i8>
; CHECK-NEXT:    br i1 [[FLAG1]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[SHIFT:%.*]] = shufflevector <32 x i8> [[TMP1]], <32 x i8> poison, <32 x i32> <i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[FOLDEXTEXTBINOP:%.*]] = add <32 x i8> [[TMP3]], [[SHIFT]]
; CHECK-NEXT:    [[RES12:%.*]] = extractelement <32 x i8> [[FOLDEXTEXTBINOP]], i64 0
; CHECK-NEXT:    ret i8 [[RES12]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    [[SHIFT2:%.*]] = shufflevector <32 x i8> [[TMP1]], <32 x i8> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 8, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[FOLDEXTEXTBINOP3:%.*]] = add <32 x i8> [[TMP3]], [[SHIFT2]]
; CHECK-NEXT:    [[RES34:%.*]] = extractelement <32 x i8> [[FOLDEXTEXTBINOP3]], i64 7
; CHECK-NEXT:    ret i8 [[RES34]]
;
entry:
  %0 = bitcast <4 x i64> %v to <32 x i8>
  %1 = bitcast <4 x i64> %v to <32 x i8>
  br label %first

first:
  %vecext00 = extractelement <32 x i8> %0, i64 0
  %vecext07 = extractelement <32 x i8> %0, i64 7
  %vecext11 = extractelement <32 x i8> %1, i64 1
  %vecext18 = extractelement <32 x i8> %1, i64 8
  br label %second

second:
  %cond1 = icmp eq i8 %a, 0
  br i1 %flag1, label %then, label %else

then:
  %res1 = select i1 %cond1, i8 %vecext00, i8 0
  %res2 = select i1 %cond2, i8 %vecext11, i8 0
  %res12 = add i8 %res1, %res2
  ret i8 %res12

else:
  %res3 = select i1 %cond1, i8 %vecext07, i8 0
  %res4 = select i1 %cond2, i8 %vecext18, i8 0
  %res34 = add i8 %res3, %res4
  ret i8 %res34
}
