; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -S -p vector-combine | FileCheck %s

define <4 x float> @fneg_fixed(float %x) {
; CHECK-LABEL: define <4 x float> @fneg_fixed(
; CHECK-SAME: float [[X:%.*]]) {
; CHECK-NEXT:    [[X_INSERT:%.*]] = insertelement <4 x float> poison, float [[X]], i32 0
; CHECK-NEXT:    [[V:%.*]] = fneg <4 x float> [[X_INSERT]]
; CHECK-NEXT:    ret <4 x float> [[V]]
;
  %x.insert = insertelement <4 x float> poison, float %x, i32 0
  %v = fneg <4 x float> %x.insert
  ret <4 x float> %v
}

define <vscale x 4 x float> @fneg_scalable(float %x) {
; CHECK-LABEL: define <vscale x 4 x float> @fneg_scalable(
; CHECK-SAME: float [[X:%.*]]) {
; CHECK-NEXT:    [[X_INSERT:%.*]] = insertelement <vscale x 4 x float> poison, float [[X]], i32 0
; CHECK-NEXT:    [[V:%.*]] = fneg <vscale x 4 x float> [[X_INSERT]]
; CHECK-NEXT:    ret <vscale x 4 x float> [[V]]
;
  %x.insert = insertelement <vscale x 4 x float> poison, float %x, i32 0
  %v = fneg <vscale x 4 x float> %x.insert
  ret <vscale x 4 x float> %v
}
