; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S %s -passes='require<libcall-lowering-info>,atomic-expand' -mtriple=x86_64-linux-gnu | FileCheck %s

; By default, elementwise atomicrmws are treated the same as the non-elementwise versions and are not expanded.
; Targets in the future can take advantage of elementwise expansion by returning AtomicExpansionKind::Elementwise from shouldExpandAtomicRMWInIR.
; Elementwise atomics work on integer vectors, but normal atomics don't.

define <4 x i32> @atomicrmw_add_elementwise(ptr %p, <4 x i32> %v) {
; CHECK-LABEL: define <4 x i32> @atomicrmw_add_elementwise(
; CHECK-SAME: ptr [[P:%.*]], <4 x i32> [[V:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[V]] to i128
; CHECK-NEXT:    [[TMP2:%.*]] = call i128 @__atomic_fetch_add_16(ptr [[P]], i128 [[TMP1]], i32 0)
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast i128 [[TMP2]] to <4 x i32>
; CHECK-NEXT:    ret <4 x i32> [[TMP3]]
;
  %old = atomicrmw elementwise add ptr %p, <4 x i32> %v monotonic
  ret <4 x i32> %old
}

define <4 x float> @atomicrmw_fadd_elementwise(ptr %p, <4 x float> %v) {
; CHECK-LABEL: define <4 x float> @atomicrmw_fadd_elementwise(
; CHECK-SAME: ptr [[P:%.*]], <4 x float> [[V:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = alloca <4 x float>, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = load <4 x float>, ptr [[P]], align 16
; CHECK-NEXT:    br label %[[ATOMICRMW_START:.*]]
; CHECK:       [[ATOMICRMW_START]]:
; CHECK-NEXT:    [[LOADED:%.*]] = phi <4 x float> [ [[TMP2]], [[TMP0:%.*]] ], [ [[NEWLOADED:%.*]], %[[ATOMICRMW_START]] ]
; CHECK-NEXT:    [[NEW:%.*]] = fadd <4 x float> [[LOADED]], [[V]]
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[TMP1]])
; CHECK-NEXT:    store <4 x float> [[LOADED]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x float> [[NEW]] to i128
; CHECK-NEXT:    [[TMP4:%.*]] = call zeroext i1 @__atomic_compare_exchange_16(ptr [[P]], ptr [[TMP1]], i128 [[TMP3]], i32 0, i32 0)
; CHECK-NEXT:    [[TMP5:%.*]] = load <4 x float>, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[TMP1]])
; CHECK-NEXT:    [[TMP6:%.*]] = insertvalue { <4 x float>, i1 } poison, <4 x float> [[TMP5]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = insertvalue { <4 x float>, i1 } [[TMP6]], i1 [[TMP4]], 1
; CHECK-NEXT:    [[SUCCESS:%.*]] = extractvalue { <4 x float>, i1 } [[TMP7]], 1
; CHECK-NEXT:    [[NEWLOADED]] = extractvalue { <4 x float>, i1 } [[TMP7]], 0
; CHECK-NEXT:    br i1 [[SUCCESS]], label %[[ATOMICRMW_END:.*]], label %[[ATOMICRMW_START]]
; CHECK:       [[ATOMICRMW_END]]:
; CHECK-NEXT:    ret <4 x float> [[NEWLOADED]]
;
  %old = atomicrmw elementwise fadd ptr %p, <4 x float> %v monotonic
  ret <4 x float> %old
}

define <4 x float> @atomicrmw_fadd(ptr %p, <4 x float> %v) {
; CHECK-LABEL: define <4 x float> @atomicrmw_fadd(
; CHECK-SAME: ptr [[P:%.*]], <4 x float> [[V:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = alloca <4 x float>, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = load <4 x float>, ptr [[P]], align 16
; CHECK-NEXT:    br label %[[ATOMICRMW_START:.*]]
; CHECK:       [[ATOMICRMW_START]]:
; CHECK-NEXT:    [[LOADED:%.*]] = phi <4 x float> [ [[TMP2]], [[TMP0:%.*]] ], [ [[NEWLOADED:%.*]], %[[ATOMICRMW_START]] ]
; CHECK-NEXT:    [[NEW:%.*]] = fadd <4 x float> [[LOADED]], [[V]]
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[TMP1]])
; CHECK-NEXT:    store <4 x float> [[LOADED]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x float> [[NEW]] to i128
; CHECK-NEXT:    [[TMP4:%.*]] = call zeroext i1 @__atomic_compare_exchange_16(ptr [[P]], ptr [[TMP1]], i128 [[TMP3]], i32 0, i32 0)
; CHECK-NEXT:    [[TMP5:%.*]] = load <4 x float>, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[TMP1]])
; CHECK-NEXT:    [[TMP6:%.*]] = insertvalue { <4 x float>, i1 } poison, <4 x float> [[TMP5]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = insertvalue { <4 x float>, i1 } [[TMP6]], i1 [[TMP4]], 1
; CHECK-NEXT:    [[SUCCESS:%.*]] = extractvalue { <4 x float>, i1 } [[TMP7]], 1
; CHECK-NEXT:    [[NEWLOADED]] = extractvalue { <4 x float>, i1 } [[TMP7]], 0
; CHECK-NEXT:    br i1 [[SUCCESS]], label %[[ATOMICRMW_END:.*]], label %[[ATOMICRMW_START]]
; CHECK:       [[ATOMICRMW_END]]:
; CHECK-NEXT:    ret <4 x float> [[NEWLOADED]]
;
  %old = atomicrmw fadd ptr %p, <4 x float> %v monotonic
  ret <4 x float> %old
}
