; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mips64el-unknown-linux-gnu -mcpu=mips64 < %s | FileCheck %s

define fp128 @call_fmaxl(fp128 %a, fp128 %b) {
; CHECK-LABEL: call_fmaxl:
; CHECK:       # %bb.0:
; CHECK-NEXT:    daddiu $sp, $sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -8
; CHECK-NEXT:    jal fmaxf128
; CHECK-NEXT:    nop
; CHECK-NEXT:    mov.d $f12, $f0
; CHECK-NEXT:    jal f
; CHECK-NEXT:    mov.d $f13, $f2
; CHECK-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    daddiu $sp, $sp, 16
    %1 = call fp128 @llvm.maxnum.f128(fp128 %a, fp128 %b)
    %2 = call fp128 @f(fp128 %1)
    ret fp128 %2
}

declare fp128 @llvm.maxnum.f128(fp128, fp128)
declare fp128 @f(fp128)
