; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=indvars -S %s | FileCheck %s
;
; Verify that IndVarSimplify folds correlated IV comparisons. When multiple
; pointer IVs share the same stride and their bounds are equidistant from their
; bases, a dominating equality check (p2 == bound2) implies the same for the
; other IVs (p1 == bound1, p3 == bound3). The redundant icmp ne instructions
; in the dominated block should be folded to false.
; Target-dependent because SCEV pointer handling depends on the data layout.

target triple = "x86_64-unknown-linux-gnu"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"

define void @fold_correlated_iv_comparisons(ptr %base1, ptr %base2, ptr %base3, i64 %n) {
; CHECK-LABEL: @fold_correlated_iv_comparisons(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[BOUND2:%.*]] = getelementptr i64, ptr [[BASE2:%.*]], i64 [[N:%.*]]
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[SCEVGEP:%.*]] = phi ptr [ [[BASE1:%.*]], [[ENTRY:%.*]] ], [ [[P1_NEXT:%.*]], [[LOOP_LATCH:%.*]] ]
; CHECK-NEXT:    [[SCEVGEP1:%.*]] = phi ptr [ [[BASE2]], [[ENTRY]] ], [ [[P2_NEXT:%.*]], [[LOOP_LATCH]] ]
; CHECK-NEXT:    [[SCEVGEP2:%.*]] = phi ptr [ [[BASE3:%.*]], [[ENTRY]] ], [ [[P3_NEXT:%.*]], [[LOOP_LATCH]] ]
; CHECK-NEXT:    [[CMP_EXIT:%.*]] = icmp eq ptr [[SCEVGEP1]], [[BOUND2]]
; CHECK-NEXT:    br i1 [[CMP_EXIT]], label [[CHECK:%.*]], label [[BODY:%.*]]
; CHECK:       check:
; CHECK-NEXT:    [[SEL:%.*]] = select i1 false, i1 true, i1 false
; CHECK-NEXT:    br i1 [[SEL]], label [[BODY]], label [[EXIT:%.*]]
; CHECK:       body:
; CHECK-NEXT:    [[V1:%.*]] = load i64, ptr [[SCEVGEP]], align 8
; CHECK-NEXT:    [[V2:%.*]] = load i64, ptr [[SCEVGEP1]], align 8
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[V1]], [[V2]]
; CHECK-NEXT:    store i64 [[SUM]], ptr [[SCEVGEP2]], align 8
; CHECK-NEXT:    br label [[LOOP_LATCH]]
; CHECK:       loop.latch:
; CHECK-NEXT:    [[P1_NEXT]] = getelementptr inbounds i8, ptr [[SCEVGEP]], i64 8
; CHECK-NEXT:    [[P2_NEXT]] = getelementptr inbounds i8, ptr [[SCEVGEP1]], i64 8
; CHECK-NEXT:    [[P3_NEXT]] = getelementptr inbounds i8, ptr [[SCEVGEP2]], i64 8
; CHECK-NEXT:    br label [[LOOP]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %bound1 = getelementptr i64, ptr %base1, i64 %n
  %bound2 = getelementptr i64, ptr %base2, i64 %n
  %bound3 = getelementptr i64, ptr %base3, i64 %n
  br label %loop

loop:
  %p1 = phi ptr [ %base1, %entry ], [ %p1.next, %loop.latch ]
  %p2 = phi ptr [ %base2, %entry ], [ %p2.next, %loop.latch ]
  %p3 = phi ptr [ %base3, %entry ], [ %p3.next, %loop.latch ]
  %cmp.exit = icmp eq ptr %p2, %bound2
  br i1 %cmp.exit, label %check, label %body

check:
  %cmp1 = icmp ne ptr %p1, %bound1
  %cmp3 = icmp ne ptr %p3, %bound3
  %sel = select i1 %cmp1, i1 true, i1 %cmp3
  br i1 %sel, label %body, label %exit

body:
  %v1 = load i64, ptr %p1, align 8
  %v2 = load i64, ptr %p2, align 8
  %sum = add i64 %v1, %v2
  store i64 %sum, ptr %p3, align 8
  br label %loop.latch

loop.latch:
  %p1.next = getelementptr inbounds i8, ptr %p1, i64 8
  %p2.next = getelementptr inbounds i8, ptr %p2, i64 8
  %p3.next = getelementptr inbounds i8, ptr %p3, i64 8
  br label %loop

exit:
  ret void
}
