// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -fexperimental-relative-c++-abi-vtables -fclangir -emit-llvm %s -o - | FileCheck --check-prefix=LLVM %s
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -fexperimental-relative-c++-abi-vtables -emit-llvm %s -o - | FileCheck --check-prefix=OGCG %s

struct A {
  virtual int f();
};

// LLVM-LABEL: define dso_local noundef i32 @_Z4callP1A(
// LLVM-SAME: ptr noundef [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
// LLVM-NEXT:    [[TMP2:%.*]] = alloca ptr, i64 1, align 8
// LLVM-NEXT:    [[TMP3:%.*]] = alloca i32, i64 1, align 4
// LLVM-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
// LLVM-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP2]], align 8
// LLVM-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
// LLVM-NEXT:    [[TMP6:%.*]] = call ptr @llvm.load.relative.i32(ptr [[TMP5]], i32 0)
// LLVM-NEXT:    [[TMP7:%.*]] = call noundef i32 [[TMP6]](ptr noundef nonnull align 8 dereferenceable(8) [[TMP4]])
// LLVM-NEXT:    store i32 [[TMP7]], ptr [[TMP3]], align 4
// LLVM-NEXT:    [[TMP8:%.*]] = load i32, ptr [[TMP3]], align 4
// LLVM-NEXT:    ret i32 [[TMP8]]
//
// OGCG-LABEL: define dso_local noundef i32 @_Z4callP1A(
// OGCG-SAME: ptr noundef [[A:%.*]]) #[[ATTR0:[0-9]+]] {
// OGCG-NEXT:  [[ENTRY:.*:]]
// OGCG-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// OGCG-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// OGCG-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// OGCG-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[TMP0]], align 8
// OGCG-NEXT:    [[TMP1:%.*]] = call ptr @llvm.load.relative.i32(ptr [[VTABLE]], i32 0)
// OGCG-NEXT:    [[CALL:%.*]] = call noundef i32 [[TMP1]](ptr noundef nonnull align 8 dereferenceable(8) [[TMP0]])
// OGCG-NEXT:    ret i32 [[CALL]]
//
int call(A *a) {
  return a->f();
}
