; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -passes='infer-alignment,load-store-vectorizer' -S < %s  | FileCheck %s

$_ZZ11test_kernelILi256ELi4096EEvPfS0_E4smem = comdat any
@_ZZ11test_kernelILi256ELi4096EEvPfS0_E4smem = linkonce_odr hidden addrspace(3) global [4096 x i8] undef, comdat, align 16

; Function Attrs: alwaysinline convergent mustprogress nounwind
define amdgpu_kernel void @vectorized_load() unnamed_addr align 2 {
; CHECK-LABEL: define amdgpu_kernel void @vectorized_load() unnamed_addr align 2 {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[IDX:%.*]] = call noundef i32 @llvm.amdgcn.workitem.id.x()
; CHECK-NEXT:    [[MUL32_I:%.*]] = shl nuw nsw i32 [[IDX]], 2
; CHECK-NEXT:    [[ADD36_I:%.*]] = add nuw nsw i32 [[MUL32_I]], 1024
; CHECK-NEXT:    [[IDXPROM37_I21:%.*]] = zext i32 [[ADD36_I]] to i64
; CHECK-NEXT:    [[ARRAYIDX38_I22:%.*]] = getelementptr inbounds float, ptr addrspacecast (ptr addrspace(3) @_ZZ11test_kernelILi256ELi4096EEvPfS0_E4smem to ptr), i64 [[IDXPROM37_I21]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <4 x float>, ptr [[ARRAYIDX38_I22]], align 16
; CHECK-NEXT:    [[L11:%.*]] = extractelement <4 x float> [[TMP0]], i32 0
; CHECK-NEXT:    [[L22:%.*]] = extractelement <4 x float> [[TMP0]], i32 1
; CHECK-NEXT:    [[L33:%.*]] = extractelement <4 x float> [[TMP0]], i32 2
; CHECK-NEXT:    [[L44:%.*]] = extractelement <4 x float> [[TMP0]], i32 3
; CHECK-NEXT:    ret void
;
entry:
  %idx = call noundef i32 @llvm.amdgcn.workitem.id.x()
  %mul32.i = shl nuw nsw i32 %idx, 2
  %add36.i = add nuw nsw i32 %mul32.i, 1024
  %idxprom37.i21 = zext i32 %add36.i to i64
  %arrayidx38.i22 = getelementptr inbounds float, ptr addrspacecast (ptr addrspace(3) @_ZZ11test_kernelILi256ELi4096EEvPfS0_E4smem to ptr), i64 %idxprom37.i21
  %l1 = load float, ptr  %arrayidx38.i22, align 4
  %add45.i = add nuw nsw i32 %mul32.i, 1025
  %idxprom46.i23 = zext i32 %add45.i to i64
  %arrayidx47.i24 = getelementptr inbounds float, ptr addrspacecast (ptr addrspace(3) @_ZZ11test_kernelILi256ELi4096EEvPfS0_E4smem to ptr), i64 %idxprom46.i23
  %l2 = load float, ptr  %arrayidx47.i24, align 4
  %add54.i = add nuw nsw i32 %mul32.i, 1026
  %idxprom55.i25 = zext i32 %add54.i to i64
  %arrayidx56.i26 = getelementptr inbounds float, ptr addrspacecast (ptr addrspace(3) @_ZZ11test_kernelILi256ELi4096EEvPfS0_E4smem to ptr), i64 %idxprom55.i25
  %l3 = load float, ptr  %arrayidx56.i26, align 4
  %add63.i = add nuw nsw i32 %mul32.i, 1027
  %idxprom64.i27 = zext i32 %add63.i to i64
  %arrayidx65.i28= getelementptr inbounds float, ptr addrspacecast (ptr addrspace(3) @_ZZ11test_kernelILi256ELi4096EEvPfS0_E4smem to ptr), i64 %idxprom64.i27
  %l4 = load float, ptr  %arrayidx65.i28, align 4
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.amdgcn.workitem.id.x()
