; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1200 -passes=separate-const-offset-from-gep -S | FileCheck %s

; Verify that we drop "nuw" from trunc.
define ptr @pr154116_nuw(ptr %p, i128 %i) {
; CHECK-LABEL: define ptr @pr154116_nuw(
; CHECK-SAME: ptr [[P:%.*]], i128 [[I:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i128 [[I]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i32, ptr [[P]], i64 [[TMP1]]
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr i8, ptr [[TMP2]], i64 80
; CHECK-NEXT:    ret ptr [[ARRAYIDX2]]
;
  %idx = add i128 %i, 20
  %idx.conv = trunc nuw i128 %idx to i64
  %arrayidx = getelementptr i32, ptr %p, i64 %idx.conv
  ret ptr %arrayidx
}

; Verify that we drop "nsw" from trunc.
define ptr @pr154116_nsw(ptr %p, i128 %i) {
; CHECK-LABEL: define ptr @pr154116_nsw(
; CHECK-SAME: ptr [[P:%.*]], i128 [[I:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i128 [[I]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i32, ptr [[P]], i64 [[TMP1]]
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr i8, ptr [[TMP2]], i64 4
; CHECK-NEXT:    ret ptr [[ARRAYIDX2]]
;
  %idx = add i128 %i, 1
  %idx.conv = trunc nsw i128 %idx to i64
  %arrayidx = getelementptr i32, ptr %p, i64 %idx.conv
  ret ptr %arrayidx
}
