; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=jump-threading,dce %s | FileCheck %s

define i32 @nonull(ptr %ptr) {
; CHECK-LABEL: define i32 @nonull(
; CHECK-SAME: ptr [[PTR:%.*]]) {
; CHECK-NEXT:  [[TRUE:.*:]]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[PTR]]) ]
; CHECK-NEXT:    ret i32 1
;
  call void @llvm.assume(i1 true) [ "nonnull"(ptr %ptr) ]
  %is_nonnull = icmp ne ptr %ptr, null
  br i1 %is_nonnull, label %true, label %false

true:
  ret i32 1

false:
  ret i32 2
}

define i32 @nonull_on_other_ptr(ptr %ptr, ptr %other_ptr) {
; CHECK-LABEL: define i32 @nonull_on_other_ptr(
; CHECK-SAME: ptr [[PTR:%.*]], ptr [[OTHER_PTR:%.*]]) {
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[OTHER_PTR]]) ]
; CHECK-NEXT:    [[IS_NONNULL:%.*]] = icmp ne ptr [[PTR]], null
; CHECK-NEXT:    br i1 [[IS_NONNULL]], label %[[TRUE:.*]], label %[[FALSE:.*]]
; CHECK:       [[TRUE]]:
; CHECK-NEXT:    ret i32 1
; CHECK:       [[FALSE]]:
; CHECK-NEXT:    ret i32 2
;
  call void @llvm.assume(i1 true) [ "nonnull"(ptr %other_ptr) ]
  %is_nonnull = icmp ne ptr %ptr, null
  br i1 %is_nonnull, label %true, label %false

true:
  ret i32 1

false:
  ret i32 2
}

define i32 @dereferenceable(ptr %ptr) {
; CHECK-LABEL: define i32 @dereferenceable(
; CHECK-SAME: ptr [[PTR:%.*]]) {
; CHECK-NEXT:  [[TRUE:.*:]]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "dereferenceable"(ptr [[PTR]], i32 1) ]
; CHECK-NEXT:    ret i32 1
;
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %ptr, i32 1) ]
  %is_nonnull = icmp ne ptr %ptr, null
  br i1 %is_nonnull, label %true, label %false

true:
  ret i32 1

false:
  ret i32 2
}
