; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=jump-threading < %s | FileCheck %s

; @process_block_branch checks that JumpThreading's processBlock() propagates
; the debug location to the new branch instruction.

; @process_threadable_edges_branch checks that JumpThreading's processThreadableEdges()
; propagates the debug location to the new branch instruction.

define i32 @process_block_branch(i32 %action) #0 !dbg !5 {
; CHECK-LABEL: define i32 @process_block_branch(
; CHECK-SAME: i32 [[ACTION:%.*]]) #[[ATTR0:[0-9]+]] !dbg [[DBG5:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    switch i32 [[ACTION]], label %[[IF_THEN:.*]] [
; CHECK-NEXT:      i32 1, label %[[IF_THEN]]
; CHECK-NEXT:      i32 0, label %[[IF_THEN]]
; CHECK-NEXT:    ], !dbg [[DBG8:![0-9]+]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    ret i32 0, !dbg [[DBG9:![0-9]+]]
;
entry:
  switch i32 %action, label %lor.rhs [
  i32 1, label %if.then
  i32 0, label %lor.end
  ], !dbg !8

if.then:                                          ; preds = %for.cond, %lor.end, %entry
  ret i32 0, !dbg !9

lor.rhs:                                          ; preds = %entry
  br label %lor.end, !dbg !10

lor.end:                                          ; preds = %lor.rhs, %entry
  br i1 false, label %for.cond, label %if.then, !dbg !12

for.cond:                                         ; preds = %for.body, %lor.end
  br i1 false, label %if.then, label %for.body, !dbg !13

for.body:                                         ; preds = %for.cond
  br label %for.cond, !dbg !14
}

define void @process_threadable_edges_branch(i32 %value) #0 !dbg !15 {
; CHECK-LABEL: define void @process_threadable_edges_branch(
; CHECK-SAME: i32 [[VALUE:%.*]]) #[[ATTR0]] !dbg [[DBG10:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[VALUE]], 32, !dbg [[DBG11:![0-9]+]]
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[VALUE]], 64, !dbg [[DBG12:![0-9]+]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[L0:.*]], label %[[L2:.*]], !dbg [[DBG13:![0-9]+]]
; CHECK:       [[L0]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @f2(), !dbg [[DBG14:![0-9]+]]
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @f2(), !dbg [[DBG15:![0-9]+]]
; CHECK-NEXT:    br label %[[L2]], !dbg [[DBG16:![0-9]+]]
; CHECK:       [[L2]]:
; CHECK-NEXT:    call void @f4(i32 [[ADD]]), !dbg [[DBG17:![0-9]+]]
; CHECK-NEXT:    ret void, !dbg [[DBG18:![0-9]+]]
;
entry:
  %cmp = icmp eq i32 %value, 32, !dbg !16
  %add = add i32 %value, 64, !dbg !17
  br i1 %cmp, label %L0, label %L2, !dbg !18

L0:                                               ; preds = %entry
  %0 = call i32 @f2(), !dbg !19
  %1 = call i32 @f2(), !dbg !20
  switch i32 %add, label %L3 [
  i32 32, label %L1
  i32 96, label %L2
  ], !dbg !21

L1:                                               ; preds = %L0
  call void @f3(), !dbg !22
  ret void, !dbg !23

L2:                                               ; preds = %L0, %entry
  call void @f4(i32 %add), !dbg !24
  ret void, !dbg !25

L3:                                               ; preds = %L0
  call void @f3(), !dbg !26
  ret void, !dbg !27
}

declare i32 @f1()

declare i32 @f2()

declare void @f3()

declare void @f4(i32)

attributes #0 = { nounwind }

!llvm.dbg.cu = !{!0}
!llvm.debugify = !{!2, !3}
!llvm.module.flags = !{!4}


!0 = distinct !DICompileUnit(language: DW_LANG_C, file: !1, producer: "debugify", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
!1 = !DIFile(filename: "temp.ll", directory: "/")
!2 = !{i32 30}
!3 = !{i32 0}
!4 = !{i32 2, !"Debug Info Version", i32 3}
!5 = distinct !DISubprogram(name: "process_block_branch", linkageName: "process_block_branch", scope: null, file: !1, line: 1, type: !6, scopeLine: 1, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0)
!6 = !DISubroutineType(types: !7)
!7 = !{}
!8 = !DILocation(line: 1, column: 1, scope: !5)
!9 = !DILocation(line: 2, column: 1, scope: !5)
!10 = !DILocation(line: 3, column: 1, scope: !5)
!11 = !DILocation(line: 4, column: 1, scope: !5)
!12 = !DILocation(line: 5, column: 1, scope: !5)
!13 = !DILocation(line: 6, column: 1, scope: !5)
!14 = !DILocation(line: 7, column: 1, scope: !5)
!15 = distinct !DISubprogram(name: "process_threadable_edges_branch", linkageName: "process_threadable_edges_branch", scope: null, file: !1, line: 8, type: !6, scopeLine: 8, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0)
!16 = !DILocation(line: 8, column: 1, scope: !15)
!17 = !DILocation(line: 9, column: 1, scope: !15)
!18 = !DILocation(line: 10, column: 1, scope: !15)
!19 = !DILocation(line: 11, column: 1, scope: !15)
!20 = !DILocation(line: 12, column: 1, scope: !15)
!21 = !DILocation(line: 13, column: 1, scope: !15)
!22 = !DILocation(line: 14, column: 1, scope: !15)
!23 = !DILocation(line: 15, column: 1, scope: !15)
!24 = !DILocation(line: 16, column: 1, scope: !15)
!25 = !DILocation(line: 17, column: 1, scope: !15)
!26 = !DILocation(line: 18, column: 1, scope: !15)
!27 = !DILocation(line: 19, column: 1, scope: !15)
;.
; CHECK: [[META0:![0-9]+]] = distinct !DICompileUnit(language: DW_LANG_C, file: [[META1:![0-9]+]], producer: "debugify", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
; CHECK: [[META1]] = !DIFile(filename: "temp.ll", directory: {{.*}})
; CHECK: [[DBG5]] = distinct !DISubprogram(name: "process_block_branch", linkageName: "process_block_branch", scope: null, file: [[META1]], line: 1, type: [[META6:![0-9]+]], scopeLine: 1, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: [[META0]])
; CHECK: [[META6]] = !DISubroutineType(types: [[META7:![0-9]+]])
; CHECK: [[META7]] = !{}
; CHECK: [[DBG8]] = !DILocation(line: 1, column: 1, scope: [[DBG5]])
; CHECK: [[DBG9]] = !DILocation(line: 2, column: 1, scope: [[DBG5]])
; CHECK: [[DBG10]] = distinct !DISubprogram(name: "process_threadable_edges_branch", linkageName: "process_threadable_edges_branch", scope: null, file: [[META1]], line: 8, type: [[META6]], scopeLine: 8, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: [[META0]])
; CHECK: [[DBG11]] = !DILocation(line: 8, column: 1, scope: [[DBG10]])
; CHECK: [[DBG12]] = !DILocation(line: 9, column: 1, scope: [[DBG10]])
; CHECK: [[DBG13]] = !DILocation(line: 10, column: 1, scope: [[DBG10]])
; CHECK: [[DBG14]] = !DILocation(line: 11, column: 1, scope: [[DBG10]])
; CHECK: [[DBG15]] = !DILocation(line: 12, column: 1, scope: [[DBG10]])
; CHECK: [[DBG16]] = !DILocation(line: 13, column: 1, scope: [[DBG10]])
; CHECK: [[DBG17]] = !DILocation(line: 16, column: 1, scope: [[DBG10]])
; CHECK: [[DBG18]] = !DILocation(line: 17, column: 1, scope: [[DBG10]])
;.
