; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=jump-threading -S | FileCheck %s

declare i64 @llvm.ptrauth.sign(i64, i32, i64)
declare i64 @llvm.ptrauth.auth(i64, i32, i64)

define i64 @test_i64_all_signed(i64 %p1, i64 %p2, i1 %cond) {
; CHECK-LABEL: define i64 @test_i64_all_signed(
; CHECK-SAME: i64 [[P1:%.*]], i64 [[P2:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[COND]], label %[[BB1:.*]], label %[[BB2:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[SIGNED1:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P1]], i32 2, i64 1234)
; CHECK-NEXT:    br label %[[JOIN:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[SIGNED2:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P2]], i32 2, i64 1234)
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ [[P1]], %[[BB1]] ], [ [[P2]], %[[BB2]] ]
; CHECK-NEXT:    ret i64 [[PHI]]
;
entry:
  br i1 %cond, label %bb1, label %bb2

bb1:
  %signed1 = call i64 @llvm.ptrauth.sign(i64 %p1, i32 2, i64 1234)
  br label %join

bb2:
  %signed2 = call i64 @llvm.ptrauth.sign(i64 %p2, i32 2, i64 1234)
  br label %join

join:
  %phi = phi i64 [ %signed1, %bb1 ], [ %signed2, %bb2 ]
  %auth = call i64 @llvm.ptrauth.auth(i64 %phi, i32 2, i64 1234)
  ret i64 %auth
}

define i64 @test_i64_hoist(i64 %p1, i64 %p2, i1 %cond) {
; CHECK-LABEL: define i64 @test_i64_hoist(
; CHECK-SAME: i64 [[P1:%.*]], i64 [[P2:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[COND]], label %[[ENTRY_JOIN_CRIT_EDGE:.*]], label %[[BB2:.*]]
; CHECK:       [[ENTRY_JOIN_CRIT_EDGE]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P1]], i32 2, i64 1234)
; CHECK-NEXT:    br label %[[JOIN:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[TMP1:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P2]], i32 2, i64 1234)
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ [[TMP1]], %[[BB2]] ], [ [[TMP0]], %[[ENTRY_JOIN_CRIT_EDGE]] ]
; CHECK-NEXT:    ret i64 [[PHI]]
;
entry:
  br i1 %cond, label %bb1, label %bb2

bb1:
  br label %join

bb2:
  br label %join

join:
  %phi = phi i64 [ %p1, %bb1 ], [ %p2, %bb2 ]
  %auth = call i64 @llvm.ptrauth.auth(i64 %phi, i32 2, i64 1234)
  ret i64 %auth
}

define ptr @test_ptr_hoist(ptr %p1, ptr %p2, i1 %cond) {
; CHECK-LABEL: define ptr @test_ptr_hoist(
; CHECK-SAME: ptr [[P1:%.*]], ptr [[P2:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[COND]], label %[[ENTRY_JOIN_CRIT_EDGE:.*]], label %[[BB2:.*]]
; CHECK:       [[ENTRY_JOIN_CRIT_EDGE]]:
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[P1]] to i64
; CHECK-NEXT:    [[TMP1:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[TMP0]], i32 2, i64 1234)
; CHECK-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[TMP1]] to ptr
; CHECK-NEXT:    br label %[[JOIN:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[P2]] to i64
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[TMP3]], i32 2, i64 1234)
; CHECK-NEXT:    [[TMP5:%.*]] = inttoptr i64 [[TMP4]] to ptr
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi ptr [ [[TMP5]], %[[BB2]] ], [ [[TMP2]], %[[ENTRY_JOIN_CRIT_EDGE]] ]
; CHECK-NEXT:    [[P2I:%.*]] = ptrtoint ptr [[PHI]] to i64
; CHECK-NEXT:    [[AUTH:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P2I]], i32 2, i64 1234)
; CHECK-NEXT:    ret ptr [[PHI]]
;
entry:
  br i1 %cond, label %bb1, label %bb2

bb1:
  br label %join

bb2:
  br label %join

join:
  %phi = phi ptr [ %p1, %bb1 ], [ %p2, %bb2 ]
  %p2i = ptrtoint ptr %phi to i64
  %auth = call i64 @llvm.ptrauth.auth(i64 %p2i, i32 2, i64 1234)
  %i2p = inttoptr i64 %auth to ptr
  ret ptr %i2p
}

define i64 @test_i64_hoist_split(i64 %p1, i64 %p2, i1 %cond, i1 %cond2) {
; CHECK-LABEL: define i64 @test_i64_hoist_split(
; CHECK-SAME: i64 [[P1:%.*]], i64 [[P2:%.*]], i1 [[COND:%.*]], i1 [[COND2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[COND]], label %[[BB1:.*]], label %[[ENTRY_JOIN_CRIT_EDGE:.*]]
; CHECK:       [[ENTRY_JOIN_CRIT_EDGE]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P2]], i32 2, i64 1234)
; CHECK-NEXT:    br label %[[JOIN:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    br i1 [[COND2]], label %[[BB1_JOIN_CRIT_EDGE:.*]], label %[[OTHER_BLOCK:.*]]
; CHECK:       [[BB1_JOIN_CRIT_EDGE]]:
; CHECK-NEXT:    [[TMP1:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P1]], i32 2, i64 1234)
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[OTHER_BLOCK]]:
; CHECK-NEXT:    ret i64 0
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ [[TMP1]], %[[BB1_JOIN_CRIT_EDGE]] ], [ [[TMP0]], %[[ENTRY_JOIN_CRIT_EDGE]] ]
; CHECK-NEXT:    ret i64 [[PHI]]
;
entry:
  br i1 %cond, label %bb1, label %bb2

bb1:
  br i1 %cond2, label %join, label %other_block

bb2:
  br label %join

other_block:
  ret i64 0

join:
  %phi = phi i64 [ %p1, %bb1 ], [ %p2, %bb2 ]
  %auth = call i64 @llvm.ptrauth.auth(i64 %phi, i32 2, i64 1234)
  ret i64 %auth
}

define i64 @test_single_incoming(i64 %p1) {
; CHECK-LABEL: define i64 @test_single_incoming(
; CHECK-SAME: i64 [[P1:%.*]]) {
; CHECK-NEXT:  [[JOIN:.*:]]
; CHECK-NEXT:    [[AUTH:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P1]], i32 2, i64 1234)
; CHECK-NEXT:    ret i64 [[AUTH]]
;
entry:
  br label %join

join:
  %phi = phi i64 [ %p1, %entry ]
  %auth = call i64 @llvm.ptrauth.auth(i64 %phi, i32 2, i64 1234)
  ret i64 %auth
}

declare i32 @other_func(i64)

define i64 @test_multiple_users(i64 %p1, i64 %p2, i1 %cond) {
; CHECK-LABEL: define i64 @test_multiple_users(
; CHECK-SAME: i64 [[P1:%.*]], i64 [[P2:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br i1 [[COND]], label %[[JOIN:.*]], label %[[BB2:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ [[P2]], %[[BB2]] ], [ [[P1]], %[[ENTRY]] ]
; CHECK-NEXT:    [[AUTH:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[PHI]], i32 2, i64 1234)
; CHECK-NEXT:    [[OTHER:%.*]] = call i32 @other_func(i64 [[PHI]])
; CHECK-NEXT:    ret i64 [[AUTH]]
;
entry:
  br i1 %cond, label %bb1, label %bb2

bb1:
  br label %join

bb2:
  br label %join

join:
  %phi = phi i64 [ %p1, %bb1 ], [ %p2, %bb2 ]
  %auth = call i64 @llvm.ptrauth.auth(i64 %phi, i32 2, i64 1234)
  %other = call i32 @other_func(i64 %phi)
  ret i64 %auth
}

define i64 @test_other_intrinsic(i64 %p1, i64 %p2, i1 %cond) {
; CHECK-LABEL: define i64 @test_other_intrinsic(
; CHECK-SAME: i64 [[P1:%.*]], i64 [[P2:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br i1 [[COND]], label %[[JOIN:.*]], label %[[BB2:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ [[P2]], %[[BB2]] ], [ [[P1]], %[[ENTRY]] ]
; CHECK-NEXT:    [[NOT_AUTH:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[PHI]], i32 2, i64 1234)
; CHECK-NEXT:    ret i64 [[NOT_AUTH]]
;
entry:
  br i1 %cond, label %bb1, label %bb2

bb1:
  br label %join

bb2:
  br label %join

join:
  %phi = phi i64 [ %p1, %bb1 ], [ %p2, %bb2 ]
  %not_auth = call i64 @llvm.ptrauth.sign(i64 %phi, i32 2, i64 1234)
  ret i64 %not_auth
}

define i64 @test_diff_block_all_signed(i64 %p1, i64 %p2, i1 %cond) {
; CHECK-LABEL: define i64 @test_diff_block_all_signed(
; CHECK-SAME: i64 [[P1:%.*]], i64 [[P2:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[COND]], label %[[BB1:.*]], label %[[BB2:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[SIGNED1:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P1]], i32 2, i64 1234)
; CHECK-NEXT:    br label %[[OTHER_BLOCK:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[SIGNED2:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P2]], i32 2, i64 1234)
; CHECK-NEXT:    br label %[[OTHER_BLOCK]]
; CHECK:       [[OTHER_BLOCK]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ [[P1]], %[[BB1]] ], [ [[P2]], %[[BB2]] ]
; CHECK-NEXT:    ret i64 [[PHI]]
;
entry:
  br i1 %cond, label %bb1, label %bb2

bb1:
  %signed1 = call i64 @llvm.ptrauth.sign(i64 %p1, i32 2, i64 1234)
  br label %join

bb2:
  %signed2 = call i64 @llvm.ptrauth.sign(i64 %p2, i32 2, i64 1234)
  br label %join

join:
  %phi = phi i64 [ %signed1, %bb1 ], [ %signed2, %bb2 ]
  br label %other_block

other_block:
  %auth = call i64 @llvm.ptrauth.auth(i64 %phi, i32 2, i64 1234)
  ret i64 %auth
}

define i64 @test_diff_block_not_all_signed(i64 %p1, i64 %p2, i1 %cond) {
; CHECK-LABEL: define i64 @test_diff_block_not_all_signed(
; CHECK-SAME: i64 [[P1:%.*]], i64 [[P2:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[COND]], label %[[ENTRY_OTHER_BLOCK_CRIT_EDGE:.*]], label %[[BB2:.*]]
; CHECK:       [[ENTRY_OTHER_BLOCK_CRIT_EDGE]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P1]], i32 2, i64 1234)
; CHECK-NEXT:    br label %[[OTHER_BLOCK:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[TMP1:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P2]], i32 2, i64 1234)
; CHECK-NEXT:    br label %[[OTHER_BLOCK]]
; CHECK:       [[OTHER_BLOCK]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ [[TMP1]], %[[BB2]] ], [ [[TMP0]], %[[ENTRY_OTHER_BLOCK_CRIT_EDGE]] ]
; CHECK-NEXT:    ret i64 [[PHI]]
;
entry:
  br i1 %cond, label %bb1, label %bb2

bb1:
  br label %join

bb2:
  br label %join

join:
  %phi = phi i64 [ %p1, %bb1 ], [ %p2, %bb2 ]
  br label %other_block

other_block:
  %auth = call i64 @llvm.ptrauth.auth(i64 %phi, i32 2, i64 1234)
  ret i64 %auth
}

define i64 @test_lcssa_phi(i64 %p1, i32 %n) {
; CHECK-LABEL: define i64 @test_lcssa_phi(
; CHECK-SAME: i64 [[P1:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[P:%.*]] = phi i64 [ [[P1]], %[[ENTRY]] ], [ [[P]], %[[LOOP]] ]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[COND:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[PHI_LCSSA:%.*]] = phi i64 [ [[P]], %[[LOOP]] ]
; CHECK-NEXT:    [[AUTH:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[PHI_LCSSA]], i32 2, i64 1234)
; CHECK-NEXT:    ret i64 [[AUTH]]
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %p = phi i64 [ %p1, %entry ], [ %p, %loop ]
  %i.next = add i32 %i, 1
  %cond = icmp slt i32 %i.next, %n
  br i1 %cond, label %loop, label %exit

exit:
  %phi.lcssa = phi i64 [ %p, %loop ]
  %auth = call i64 @llvm.ptrauth.auth(i64 %phi.lcssa, i32 2, i64 1234)
  ret i64 %auth
}

define i64 @test_loop_header_all_signed(i64 %p1, i32 %n) {
; CHECK-LABEL: define i64 @test_loop_header_all_signed(
; CHECK-SAME: i64 [[P1:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[SIGNED_ENTRY:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P1]], i32 2, i64 1234)
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ [[P1]], %[[ENTRY]] ], [ [[VAL:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[VAL]] = add i64 [[PHI]], 1
; CHECK-NEXT:    [[SIGNED_BACKEDGE:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[VAL]], i32 2, i64 1234)
; CHECK-NEXT:    [[COND:%.*]] = icmp slt i64 [[VAL]], 100
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i64 [[VAL]]
;
entry:
  %signed.entry = call i64 @llvm.ptrauth.sign(i64 %p1, i32 2, i64 1234)
  br label %loop

loop:
  %phi = phi i64 [ %signed.entry, %entry ], [ %signed.backedge, %loop ]
  %auth = call i64 @llvm.ptrauth.auth(i64 %phi, i32 2, i64 1234)
  %val = add i64 %auth, 1
  %signed.backedge = call i64 @llvm.ptrauth.sign(i64 %val, i32 2, i64 1234)
  %cond = icmp slt i64 %val, 100
  br i1 %cond, label %loop, label %exit

exit:
  ret i64 %val
}

define i64 @test_loop_header_hoist(i64 %p1, i32 %n) {
; CHECK-LABEL: define i64 @test_loop_header_hoist(
; CHECK-SAME: i64 [[P1:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P1]], i32 2, i64 1234)
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ [[TMP0]], %[[ENTRY]] ], [ [[TMP1:%.*]], %[[LOOP_LOOP_CRIT_EDGE:.*]] ]
; CHECK-NEXT:    [[VAL:%.*]] = add i64 [[PHI]], 1
; CHECK-NEXT:    [[BACKEDGE:%.*]] = call i64 @get_ptr()
; CHECK-NEXT:    [[COND:%.*]] = icmp slt i64 [[VAL]], 100
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP_LOOP_CRIT_EDGE]], label %[[EXIT:.*]]
; CHECK:       [[LOOP_LOOP_CRIT_EDGE]]:
; CHECK-NEXT:    [[TMP1]] = call i64 @llvm.ptrauth.auth(i64 [[BACKEDGE]], i32 2, i64 1234)
; CHECK-NEXT:    br label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i64 [[VAL]]
;
entry:
  br label %loop

loop:
  %phi = phi i64 [ %p1, %entry ], [ %backedge, %loop ]
  %auth = call i64 @llvm.ptrauth.auth(i64 %phi, i32 2, i64 1234)
  %val = add i64 %auth, 1
  %backedge = call i64 @get_ptr()
  %cond = icmp slt i64 %val, 100
  br i1 %cond, label %loop, label %exit

exit:
  ret i64 %val
}

declare i64 @get_ptr()

define i64 @test_casted_no_i2p(ptr %p1, ptr %p2, i1 %cond) {
; CHECK-LABEL: define i64 @test_casted_no_i2p(
; CHECK-SAME: ptr [[P1:%.*]], ptr [[P2:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br i1 [[COND]], label %[[JOIN:.*]], label %[[BB2:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi ptr [ [[P2]], %[[BB2]] ], [ [[P1]], %[[ENTRY]] ]
; CHECK-NEXT:    [[P2I:%.*]] = ptrtoint ptr [[PHI]] to i64
; CHECK-NEXT:    [[AUTH:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P2I]], i32 2, i64 1234)
; CHECK-NEXT:    ret i64 [[AUTH]]
;
entry:
  br i1 %cond, label %bb1, label %bb2

bb1:
  br label %join

bb2:
  br label %join

join:
  %phi = phi ptr [ %p1, %bb1 ], [ %p2, %bb2 ]
  %p2i = ptrtoint ptr %phi to i64
  %auth = call i64 @llvm.ptrauth.auth(i64 %p2i, i32 2, i64 1234)
  ret i64 %auth
}

declare void @may_not_return()

define i64 @test_not_willreturn(i64 %p1, i64 %p2, i1 %cond) {
; CHECK-LABEL: define i64 @test_not_willreturn(
; CHECK-SAME: i64 [[P1:%.*]], i64 [[P2:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br i1 [[COND]], label %[[ENTRY_JOIN_CRIT_EDGE:.*]], label %[[BB2:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    br label %[[ENTRY_JOIN_CRIT_EDGE]]
; CHECK:       [[ENTRY_JOIN_CRIT_EDGE]]:
; CHECK-NEXT:    [[PHI1:%.*]] = phi i64 [ [[P2]], %[[BB2]] ], [ [[P1]], %[[ENTRY]] ]
; CHECK-NEXT:    call void @may_not_return()
; CHECK-NEXT:    [[PHI:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[PHI1]], i32 2, i64 1234)
; CHECK-NEXT:    ret i64 [[PHI]]
;
entry:
  br i1 %cond, label %bb1, label %bb2

bb1:
  br label %join

bb2:
  br label %join

join:
  %phi = phi i64 [ %p1, %bb1 ], [ %p2, %bb2 ]
  call void @may_not_return()
  %auth = call i64 @llvm.ptrauth.auth(i64 %phi, i32 2, i64 1234)
  ret i64 %auth
}
