// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6

// RUN: %clang_cc1 -O2 -fbounds-safety -emit-llvm -triple arm64e-apple-iphoneos %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm -triple arm64e-apple-iphoneos %s -o - | FileCheck %s

#include <ptrcheck.h>

struct foo {
  char *ptr;
  int i;
  long l;
};

// CHECK-LABEL: define dso_local noundef ptr @addrof_single_ptr_to_single(
// CHECK-SAME: ptr noundef readnone returned captures(ret: address, provenance) [[F:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret ptr [[F]]
//
char **addrof_single_ptr_to_single(struct foo *f) {
  return &f->ptr;
}

// CHECK-LABEL: define dso_local nonnull ptr @addrof_single_i_to_single(
// CHECK-SAME: ptr noundef readnone captures(ret: address, provenance) [[F:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i8, ptr [[F]], i64 8
// CHECK-NEXT:    ret ptr [[TMP0]]
//
int *addrof_single_i_to_single(struct foo *f) {
  return &f->i;
}

// CHECK-LABEL: define dso_local nonnull ptr @addrof_single_l_to_single(
// CHECK-SAME: ptr noundef readnone captures(ret: address, provenance) [[F:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i8, ptr [[F]], i64 16
// CHECK-NEXT:    ret ptr [[TMP0]]
//
long *addrof_single_l_to_single(struct foo *f) {
  return &f->l;
}

static inline char **__addrof_bidi_ptr_to_single(struct foo *__bidi_indexable f) {
  return &f->ptr;
}

// CHECK-LABEL: define dso_local noalias noundef nonnull ptr @addrof_bidi_ptr_to_single(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[__ADDROF_BIDI_PTR_TO_SINGLE_EXIT:.*:]]
// CHECK-NEXT:    [[F:%.*]] = alloca [[STRUCT_FOO:%.*]], align 8
// CHECK-NEXT:    ret ptr [[F]]
//
char **addrof_bidi_ptr_to_single(void) {
  struct foo f;
  return __addrof_bidi_ptr_to_single(&f);
}

// CHECK-LABEL: define dso_local noalias noundef nonnull ptr @addrof_bidi_ptr_to_single_oob_upper(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  [[TRAP_I:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
char **addrof_bidi_ptr_to_single_oob_upper(void) {
  struct foo f;
  struct foo *fp = &f + 1;
  return __addrof_bidi_ptr_to_single(fp);
}


// CHECK-LABEL: define dso_local noundef ptr @addrof_bidi_ptr_to_single_oob_lower(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[F:%.*]] = alloca [[STRUCT_FOO:%.*]], align 8
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[F]]) #[[ATTR6:[0-9]+]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i8, ptr [[F]], i64 24
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[F]], i64 -24
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ult ptr [[BOUND_PTR_ARITH]], [[TMP0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp uge ptr [[BOUND_PTR_ARITH]], [[F]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND_I:%.*]] = and i1 [[TMP1]], [[TMP2]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND_I]], label %[[__ADDROF_BIDI_PTR_TO_SINGLE_EXIT:.*]], label %[[TRAP_I:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP_I]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[__ADDROF_BIDI_PTR_TO_SINGLE_EXIT]]:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[F]]) #[[ATTR6]]
// CHECK-NEXT:    ret ptr [[BOUND_PTR_ARITH]]
//
char **addrof_bidi_ptr_to_single_oob_lower(void) {
  struct foo f;
  struct foo *fp = &f - 1;
  return __addrof_bidi_ptr_to_single(fp);
}

static inline int *__addrof_bidi_i_to_single(struct foo *__bidi_indexable f) {
  return &f->i;
}

// CHECK-LABEL: define dso_local noalias nonnull ptr @addrof_bidi_i_to_single(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[__ADDROF_BIDI_I_TO_SINGLE_EXIT:.*:]]
// CHECK-NEXT:    [[F:%.*]] = alloca [[STRUCT_FOO:%.*]], align 8
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[F]]) #[[ATTR6]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i8, ptr [[F]], i64 8
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[F]]) #[[ATTR6]]
// CHECK-NEXT:    ret ptr [[TMP0]]
//
int *addrof_bidi_i_to_single(void) {
  struct foo f;
  return __addrof_bidi_i_to_single(&f);
}

// CHECK-LABEL: define dso_local noalias noundef nonnull ptr @addrof_bidi_i_to_single_oob_upper(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[TRAP_I:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
int *addrof_bidi_i_to_single_oob_upper(void) {
  struct foo f;
  struct foo *fp = &f+1;
  return __addrof_bidi_i_to_single(fp);
}

// CHECK-LABEL: define dso_local noundef ptr @addrof_bidi_i_to_single_oob_lower(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR4]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[F:%.*]] = alloca [[STRUCT_FOO:%.*]], align 8
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[F]]) #[[ATTR6]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i8, ptr [[F]], i64 24
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[F]], i64 -24
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ult ptr [[BOUND_PTR_ARITH]], [[TMP0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp uge ptr [[BOUND_PTR_ARITH]], [[F]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND_I:%.*]] = and i1 [[TMP1]], [[TMP2]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND_I]], label %[[__ADDROF_BIDI_I_TO_SINGLE_EXIT:.*]], label %[[TRAP_I:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP_I]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[__ADDROF_BIDI_I_TO_SINGLE_EXIT]]:
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[F]], i64 -16
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[F]]) #[[ATTR6]]
// CHECK-NEXT:    ret ptr [[TMP3]]
//
int *addrof_bidi_i_to_single_oob_lower(void) {
  struct foo f;
  struct foo *fp = &f-1;
  return __addrof_bidi_i_to_single(fp);
}

static inline long *__addrof_bidi_l_to_single(struct foo *__bidi_indexable f) {
  return &f->l;
}

// CHECK-LABEL: define dso_local noalias nonnull ptr @addrof_bidi_l_to_single(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[__ADDROF_BIDI_L_TO_SINGLE_EXIT:.*:]]
// CHECK-NEXT:    [[F:%.*]] = alloca [[STRUCT_FOO:%.*]], align 8
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[F]]) #[[ATTR6]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i8, ptr [[F]], i64 16
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[F]]) #[[ATTR6]]
// CHECK-NEXT:    ret ptr [[TMP0]]
//
long *addrof_bidi_l_to_single(void) {
  struct foo f;
  return __addrof_bidi_l_to_single(&f);
}

// CHECK-LABEL: define dso_local noalias noundef nonnull ptr @addrof_bidi_l_to_single_oob_upper(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[TRAP_I:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
long *addrof_bidi_l_to_single_oob_upper(void) {
  struct foo f;
  struct foo *fp = &f+1;
  return __addrof_bidi_l_to_single(fp);
}

// CHECK-LABEL: define dso_local noundef ptr @addrof_bidi_l_to_single_oob_lower(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR4]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[F:%.*]] = alloca [[STRUCT_FOO:%.*]], align 8
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[F]]) #[[ATTR6]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i8, ptr [[F]], i64 24
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[F]], i64 -24
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ult ptr [[BOUND_PTR_ARITH]], [[TMP0]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp uge ptr [[BOUND_PTR_ARITH]], [[F]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND_I:%.*]] = and i1 [[TMP1]], [[TMP2]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND_I]], label %[[__ADDROF_BIDI_L_TO_SINGLE_EXIT:.*]], label %[[TRAP_I:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP_I]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[__ADDROF_BIDI_L_TO_SINGLE_EXIT]]:
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[F]], i64 -8
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[F]]) #[[ATTR6]]
// CHECK-NEXT:    ret ptr [[TMP3]]
//
long *addrof_bidi_l_to_single_oob_lower(void) {
  struct foo f;
  struct foo *fp = &f-1;
  return __addrof_bidi_l_to_single(fp);
}
