// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --version 6


// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s --check-prefix=CHECK-O0
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s --check-prefix=CHECK-O2
// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s --check-prefix=CHECK-O0
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s --check-prefix=CHECK-O2
#include <ptrcheck.h>

int *__sized_by(len) alloc(int len);

// CHECK-O0-LABEL: define dso_local i32 @Test1(
// CHECK-O0-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-O0-NEXT:  [[ENTRY:.*:]]
// CHECK-O0-NEXT:    [[LEN:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[BUFAUTO:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[BUFBOUND:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    store i32 16, ptr [[LEN]], align 4
// CHECK-O0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LEN]], align 4
// CHECK-O0-NEXT:    [[CALL:%.*]] = call ptr @alloc(i32 noundef [[TMP0]])
// CHECK-O0-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP0]] to i64
// CHECK-O0-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[CALL]], i64 [[IDX_EXT]]
// CHECK-O0-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BUFAUTO]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[CALL]], ptr [[TMP1]], align 8
// CHECK-O0-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BUFAUTO]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP2]], align 8
// CHECK-O0-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BUFAUTO]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[CALL]], ptr [[TMP3]], align 8
// CHECK-O0-NEXT:    [[CALL1:%.*]] = call ptr @alloc(i32 noundef 40)
// CHECK-O0-NEXT:    [[ADD_PTR2:%.*]] = getelementptr inbounds i8, ptr [[CALL1]], i64 40
// CHECK-O0-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BUFBOUND]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[CALL1]], ptr [[TMP4]], align 8
// CHECK-O0-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BUFBOUND]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[ADD_PTR2]], ptr [[TMP5]], align 8
// CHECK-O0-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BUFBOUND]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[CALL1]], ptr [[TMP6]], align 8
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[BUFBOUND]], i64 24, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-O0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 9
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP7:%.*]] = icmp ult ptr [[ARRAYIDX]], [[WIDE_PTR_UB]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP7]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT]]:
// CHECK-O0-NEXT:    [[TMP8:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP8]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP3]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT4]]:
// CHECK-O0-NEXT:    [[TMP9:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-O0-NEXT:    ret i32 [[TMP9]]
//
// CHECK-O2-LABEL: define dso_local i32 @Test1(
// CHECK-O2-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-O2-NEXT:  [[CONT3:.*:]]
// CHECK-O2-NEXT:    [[CALL:%.*]] = tail call ptr @alloc(i32 noundef 16) #[[ATTR4:[0-9]+]]
// CHECK-O2-NEXT:    [[CALL1:%.*]] = tail call ptr @alloc(i32 noundef 40) #[[ATTR4]]
// CHECK-O2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i8, ptr [[CALL1]], i64 36
// CHECK-O2-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, {{!tbaa ![0-9]+}}
// CHECK-O2-NEXT:    ret i32 [[TMP0]]
//
int Test1() {
    int len = 16;
    int *bufAuto = alloc(len);
    int *__bidi_indexable bufBound = alloc(sizeof(int) * 10);
    return bufBound[9];
}

// CHECK-O0-LABEL: define dso_local i32 @Test2(
// CHECK-O0-SAME: ) #[[ATTR0]] {
// CHECK-O0-NEXT:  [[ENTRY:.*:]]
// CHECK-O0-NEXT:    [[LEN:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[BUFAUTO:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[BUFBOUND:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    store i32 16, ptr [[LEN]], align 4
// CHECK-O0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LEN]], align 4
// CHECK-O0-NEXT:    [[CALL:%.*]] = call ptr @alloc(i32 noundef [[TMP0]])
// CHECK-O0-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP0]] to i64
// CHECK-O0-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[CALL]], i64 [[IDX_EXT]]
// CHECK-O0-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BUFAUTO]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[CALL]], ptr [[TMP1]], align 8
// CHECK-O0-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BUFAUTO]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP2]], align 8
// CHECK-O0-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BUFAUTO]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[CALL]], ptr [[TMP3]], align 8
// CHECK-O0-NEXT:    [[CALL1:%.*]] = call ptr @alloc(i32 noundef 40)
// CHECK-O0-NEXT:    [[ADD_PTR2:%.*]] = getelementptr inbounds i8, ptr [[CALL1]], i64 40
// CHECK-O0-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BUFBOUND]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[CALL1]], ptr [[TMP4]], align 8
// CHECK-O0-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BUFBOUND]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[ADD_PTR2]], ptr [[TMP5]], align 8
// CHECK-O0-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BUFBOUND]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[CALL1]], ptr [[TMP6]], align 8
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[BUFBOUND]], i64 24, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-O0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 10
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP7:%.*]] = icmp ult ptr [[ARRAYIDX]], [[WIDE_PTR_UB]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP7]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT]]:
// CHECK-O0-NEXT:    [[TMP8:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP8]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP3]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT4]]:
// CHECK-O0-NEXT:    [[TMP9:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-O0-NEXT:    ret i32 [[TMP9]]
//
// CHECK-O2-LABEL: define dso_local noundef i32 @Test2(
// CHECK-O2-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-O2-NEXT:  [[ENTRY:.*:]]
// CHECK-O2-NEXT:    [[CALL:%.*]] = tail call ptr @alloc(i32 noundef 16) #[[ATTR4]]
// CHECK-O2-NEXT:    [[CALL1:%.*]] = tail call ptr @alloc(i32 noundef 40) #[[ATTR4]]
// CHECK-O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
int Test2() {
    int len = 16;
    int *bufAuto = alloc(len);
    int *__bidi_indexable bufBound = alloc(sizeof(int) * 10);
    return bufBound[10];
}
