// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

typedef void (*ended_by_t)(const char *__ended_by(end) start, const char *end);

void ended_by(const char *__ended_by(end) start, const char *end);

ended_by_t ended_by_p = &ended_by;

struct {
  char _dummy;
  const char array[10];
  char _dummy2;
} x;

// CHECK-LABEL: define dso_local void @ok(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr @ended_by_p, align 8, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    tail call void [[TMP0]](ptr noundef nonnull getelementptr inbounds nuw (i8, ptr @x, i64 1), ptr noundef nonnull getelementptr inbounds nuw (i8, ptr @x, i64 11)) #[[ATTR4:[0-9]+]]
// CHECK-NEXT:    ret void
//
void ok(void) {
	ended_by_p(x.array, x.array + 10);
}

// FIXME: rdar://105524069
// CHECK-LABEL: define dso_local void @start_fail_lower(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr @ended_by_p, align 8, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    tail call void [[TMP0]](ptr noundef nonnull @x, ptr noundef nonnull getelementptr inbounds nuw (i8, ptr @x, i64 11)) #[[ATTR4]]
// CHECK-NEXT:    ret void
//
void start_fail_lower(void) {
	ended_by_p(x.array - 1, x.array + 10);
}

// CHECK-LABEL: define dso_local void @start_fail_upper(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void start_fail_upper(void) {
	ended_by_p(x.array + 11, x.array + 10);
}

// CHECK-LABEL: define dso_local void @end_fail_lower(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void end_fail_lower(void) {
  ended_by_p(x.array, x.array - 1);
}

// CHECK-LABEL: define dso_local void @end_fail_upper(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void end_fail_upper(void) {
  ended_by_p(x.array, x.array + 11);
}
