// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --version 6
// REQUIRES: system-darwin
// RUN: %clang_cc1 -O0 -triple arm64-apple-iphoneos -fbounds-safety -emit-llvm %s -o - | FileCheck %s


#include <ptrcheck.h>

typedef struct {
  int len;
  int offs;
	int fam[__counted_by(len - offs)];
} S;


// CHECK-LABEL: define dso_local void @trap_len_too_big(
// CHECK-SAME: ptr noundef [[S:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[ARR:%.*]] = alloca [40 x i8], align 1
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP3:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP10:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP40:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable.1", align 8
// CHECK-NEXT:    [[AGG_TEMP43:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 1 [[ARR]], i8 0, i64 40, i1 false)
// CHECK-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [40 x i8], ptr [[ARR]], i64 0, i64 0
// CHECK-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i8, ptr [[ARRAYDECAY]], i64 40
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[UPPER]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP2]], align 8
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.0", ptr [[AGG_TEMP1]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP4]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[WIDE_PTR_LB]], ptr [[TMP5]], align 8
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP3]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP3]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR5:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR4]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP3]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB7:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR6]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP3]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB9:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR8]], align 8
// CHECK-NEXT:    [[FLEX_BASE_NULL_CHECK:%.*]] = icmp ne ptr [[WIDE_PTR_PTR5]], null, !annotation [[META1:![0-9]+]]
// CHECK-NEXT:    br i1 [[FLEX_BASE_NULL_CHECK]], label %[[FLEX_BASE_NONNULL:.*]], label %[[FLEX_BASE_NULL:.*]], !annotation [[META1]]
// CHECK:       [[FLEX_BASE_NONNULL]]:
// CHECK-NEXT:    [[TMP6:%.*]] = getelementptr [[STRUCT_S:%.*]], ptr [[WIDE_PTR_PTR5]], i64 1
// CHECK-NEXT:    [[TMP7:%.*]] = icmp ule ptr [[WIDE_PTR_PTR5]], [[TMP6]], !annotation [[META2:![0-9]+]]
// CHECK-NEXT:    br i1 [[TMP7]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META2]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], !annotation [[META2]]
// CHECK-NEXT:    unreachable, !annotation [[META2]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP10]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP10]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR12:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR11]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP10]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB14:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR13]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR15:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP10]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB16:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR15]], align 8
// CHECK-NEXT:    [[TMP8:%.*]] = getelementptr [[STRUCT_S]], ptr [[WIDE_PTR_PTR12]], i64 1
// CHECK-NEXT:    [[TMP9:%.*]] = icmp ule ptr [[TMP8]], [[WIDE_PTR_UB14]], !annotation [[META4:![0-9]+]]
// CHECK-NEXT:    br i1 [[TMP9]], label %[[CONT18:.*]], label %[[TRAP17:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// CHECK:       [[TRAP17]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META4]]
// CHECK-NEXT:    unreachable, !annotation [[META4]]
// CHECK:       [[CONT18]]:
// CHECK-NEXT:    [[TMP10:%.*]] = icmp ule ptr [[WIDE_PTR_LB16]], [[WIDE_PTR_PTR12]], !annotation [[META5:![0-9]+]]
// CHECK-NEXT:    br i1 [[TMP10]], label %[[CONT20:.*]], label %[[TRAP19:.*]], {{!prof ![0-9]+}}, !annotation [[META5]]
// CHECK:       [[TRAP19]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META5]]
// CHECK-NEXT:    unreachable, !annotation [[META5]]
// CHECK:       [[CONT20]]:
// CHECK-NEXT:    [[FAM:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[WIDE_PTR_PTR12]], i32 0, i32 2
// CHECK-NEXT:    [[ARRAYDECAY21:%.*]] = getelementptr inbounds [0 x i32], ptr [[FAM]], i64 0, i64 0
// CHECK-NEXT:    br i1 true, label %[[CONT23:.*]], label %[[TRAP22:.*]], {{!prof ![0-9]+}}, !annotation [[META6:![0-9]+]]
// CHECK:       [[TRAP22]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META6]]
// CHECK-NEXT:    unreachable, !annotation [[META6]]
// CHECK:       [[CONT23]]:
// CHECK-NEXT:    [[TMP11:%.*]] = icmp ule ptr [[ARRAYDECAY21]], [[WIDE_PTR_UB7]], !annotation [[META7:![0-9]+]]
// CHECK-NEXT:    br i1 [[TMP11]], label %[[CONT25:.*]], label %[[TRAP24:.*]], {{!prof ![0-9]+}}, !annotation [[META7]]
// CHECK:       [[TRAP24]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META7]]
// CHECK-NEXT:    unreachable, !annotation [[META7]]
// CHECK:       [[CONT25]]:
// CHECK-NEXT:    [[TMP12:%.*]] = icmp uge ptr [[WIDE_PTR_PTR5]], [[WIDE_PTR_LB9]], !annotation [[META8:![0-9]+]]
// CHECK-NEXT:    br i1 [[TMP12]], label %[[CONT27:.*]], label %[[TRAP26:.*]], {{!prof ![0-9]+}}, !annotation [[META8]]
// CHECK:       [[TRAP26]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META8]]
// CHECK-NEXT:    unreachable, !annotation [[META8]]
// CHECK:       [[CONT27]]:
// CHECK-NEXT:    [[UPPER_INTPTR:%.*]] = ptrtoint ptr [[WIDE_PTR_UB7]] to i64, !annotation [[META9:![0-9]+]]
// CHECK-NEXT:    [[FAM_INTPTR:%.*]] = ptrtoint ptr [[ARRAYDECAY21]] to i64, !annotation [[META9]]
// CHECK-NEXT:    [[FLEX_AVAIL_COUNT:%.*]] = sub nuw i64 [[UPPER_INTPTR]], [[FAM_INTPTR]], !annotation [[META9]]
// CHECK-NEXT:    [[FLEX_AVAIL_COUNT_DIV:%.*]] = sdiv exact i64 [[FLEX_AVAIL_COUNT]], 4, !annotation [[META9]]
// CHECK-NEXT:    [[FLEX_COUNT_CHECK:%.*]] = icmp ule i64 9, [[FLEX_AVAIL_COUNT_DIV]], !annotation [[META9]]
// CHECK-NEXT:    br i1 [[FLEX_COUNT_CHECK]], label %[[CONT29:.*]], label %[[TRAP28:.*]], {{!prof ![0-9]+}}, !annotation [[META9]]
// CHECK:       [[TRAP28]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META9]]
// CHECK-NEXT:    unreachable, !annotation [[META9]]
// CHECK:       [[CONT29]]:
// CHECK-NEXT:    br label %[[FLEX_BASE_NULL]]
// CHECK:       [[FLEX_BASE_NULL]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP2]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR30:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR31:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR30]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR32:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB33:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR32]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR34:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB35:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR34]], align 8
// CHECK-NEXT:    [[TMP13:%.*]] = icmp ne ptr [[WIDE_PTR_PTR31]], null, !annotation [[META1]]
// CHECK-NEXT:    br i1 [[TMP13]], label %[[BOUNDSCHECK_NOTNULL:.*]], label %[[BOUNDSCHECK_NULL:.*]], !annotation [[META1]]
// CHECK:       [[BOUNDSCHECK_NOTNULL]]:
// CHECK-NEXT:    [[TMP14:%.*]] = icmp ult ptr [[WIDE_PTR_PTR31]], [[WIDE_PTR_UB33]], !annotation [[META4]]
// CHECK-NEXT:    br i1 [[TMP14]], label %[[CONT37:.*]], label %[[TRAP36:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// CHECK:       [[TRAP36]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META4]]
// CHECK-NEXT:    unreachable, !annotation [[META4]]
// CHECK:       [[CONT37]]:
// CHECK-NEXT:    [[TMP15:%.*]] = icmp uge ptr [[WIDE_PTR_PTR31]], [[WIDE_PTR_LB35]], !annotation [[META5]]
// CHECK-NEXT:    br i1 [[TMP15]], label %[[CONT39:.*]], label %[[TRAP38:.*]], {{!prof ![0-9]+}}, !annotation [[META5]]
// CHECK:       [[TRAP38]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META5]]
// CHECK-NEXT:    unreachable, !annotation [[META5]]
// CHECK:       [[CONT39]]:
// CHECK-NEXT:    br label %[[BOUNDSCHECK_NULL]]
// CHECK:       [[BOUNDSCHECK_NULL]]:
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR31]], ptr [[S_ADDR]], align 8
// CHECK-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// CHECK-NEXT:    [[OFFS:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[TMP16]], i32 0, i32 1
// CHECK-NEXT:    store i32 2, ptr [[OFFS]], align 4
// CHECK-NEXT:    [[TMP17:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// CHECK-NEXT:    [[LEN:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[TMP17]], i32 0, i32 0
// CHECK-NEXT:    store i32 11, ptr [[LEN]], align 4
// CHECK-NEXT:    [[TMP18:%.*]] = load ptr, ptr [[S_ADDR]], align 8
// CHECK-NEXT:    [[FAM41:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[TMP18]], i32 0, i32 2
// CHECK-NEXT:    [[ARRAYDECAY42:%.*]] = getelementptr inbounds [0 x i32], ptr [[FAM41]], i64 0, i64 0
// CHECK-NEXT:    [[FAM44:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[TMP18]], i32 0, i32 2
// CHECK-NEXT:    [[ARRAYDECAY45:%.*]] = getelementptr inbounds [0 x i32], ptr [[FAM44]], i64 0, i64 0
// CHECK-NEXT:    [[LEN46:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[TMP18]], i32 0, i32 0
// CHECK-NEXT:    [[TMP19:%.*]] = load i32, ptr [[LEN46]], align 4
// CHECK-NEXT:    [[OFFS47:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[TMP18]], i32 0, i32 1
// CHECK-NEXT:    [[TMP20:%.*]] = load i32, ptr [[OFFS47]], align 4
// CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 [[TMP19]], [[TMP20]]
// CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[SUB]] to i64
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY45]], i64 [[IDX_EXT]]
// CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP43]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[TMP18]], ptr [[TMP21]], align 8
// CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP43]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP22]], align 8
// CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP43]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[TMP18]], ptr [[TMP23]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR48:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP43]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB49:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR48]], align 8
// CHECK-NEXT:    [[TMP24:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP43]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB49]], ptr [[TMP24]], align 8
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR50:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP43]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR51:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR50]], align 8
// CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP40]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[ARRAYDECAY42]], ptr [[TMP25]], align 8
// CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP40]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR51]], ptr [[TMP26]], align 8
// CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP40]], i32 0, i32 2
// CHECK-NEXT:    store ptr [[ARRAYDECAY42]], ptr [[TMP27]], align 8
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR52:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP40]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR53:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR52]], align 8
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR53]], i64 0
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR54:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP40]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB55:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR54]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR56:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable.1", ptr [[AGG_TEMP40]], i32 0, i32 2
// CHECK-NEXT:    [[WIDE_PTR_LB57:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR56]], align 8
// CHECK-NEXT:    [[TMP28:%.*]] = icmp ult ptr [[ARRAYIDX]], [[WIDE_PTR_UB55]], !annotation [[META4]]
// CHECK-NEXT:    br i1 [[TMP28]], label %[[CONT59:.*]], label %[[TRAP58:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// CHECK:       [[TRAP58]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META4]]
// CHECK-NEXT:    unreachable, !annotation [[META4]]
// CHECK:       [[CONT59]]:
// CHECK-NEXT:    [[TMP29:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB57]], !annotation [[META5]]
// CHECK-NEXT:    br i1 [[TMP29]], label %[[CONT61:.*]], label %[[TRAP60:.*]], {{!prof ![0-9]+}}, !annotation [[META5]]
// CHECK:       [[TRAP60]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META5]]
// CHECK-NEXT:    unreachable, !annotation [[META5]]
// CHECK:       [[CONT61]]:
// CHECK-NEXT:    store i32 0, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    ret void
//
void trap_len_too_big(S *s) {
  char arr[40] = {0};
  s = (S *)arr;
  s->offs = 2;
  s->len = 11;

  s->fam[0] = 0;
}
//.
// CHECK: [[META1]] = !{!"bounds-safety-check-ptr-neq-null"}
// CHECK: [[META2]] = !{!"bounds-safety-check-one-past-end-overflow"}
// CHECK: [[META4]] = !{!"bounds-safety-check-ptr-lt-upper-bound"}
// CHECK: [[META5]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
// CHECK: [[META6]] = !{!"bounds-safety-check-count-negative"}
// CHECK: [[META7]] = !{!"bounds-safety-check-flexible-count-gt-bounds", !"bounds-safety-check-ptr-le-upper-bound"}
// CHECK: [[META8]] = !{!"bounds-safety-check-flexible-count-gt-bounds", !"bounds-safety-check-ptr-ge-lower-bound"}
// CHECK: [[META9]] = !{!"bounds-safety-check-flexible-count-gt-bounds"}
//.
