// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple arm64-apple-iphoneos -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s


#include <ptrcheck.h>

typedef struct {
  int count;
  int elems[__counted_by(count)];
} flex_t;

inline flex_t *return_flex(int *__counted_by(11) buf) {
  return (flex_t *)buf;
}

// CHECK-LABEL: define dso_local void @pointer_assign_good(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[BOUNDSCHECK_NULL46:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_assign_good() {
  int arr[11] = {10};
  flex_t *__single a;
  a = return_flex(arr);
}

// CHECK-LABEL: define dso_local void @pointer_assign_good2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[BOUNDSCHECK_NULL46:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_assign_good2() {
  int arr[11] = {10};
  flex_t *__single a;
  a = (flex_t *)return_flex(arr);
}

// CHECK-LABEL: define dso_local void @pointer_init_good(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[BOUNDSCHECK_NULL46:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_init_good() {
  int arr[11] = {10};
  flex_t *__single a = return_flex(arr);
}

// CHECK-LABEL: define dso_local void @pointer_init_good2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[BOUNDSCHECK_NULL46:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_init_good2() {
  int arr[11] = {10};
  flex_t *__single a = (flex_t *)return_flex(arr);
}

// CHECK-LABEL: define dso_local void @pointer_count_assign_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void pointer_count_assign_trap() {
  int arr[11] = {10};
  flex_t *__single a;
  a = return_flex(arr);
  a->count = 11;
}

// CHECK-LABEL: define dso_local void @pointer_count_init_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void pointer_count_init_trap() {
  int arr[11] = {10};
  flex_t *__single a = return_flex(arr);
  a->count = 11;
}

// CHECK-LABEL: define dso_local void @pointer_count_assign_good(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_count_assign_good() {
  int arr[11] = {10};
  flex_t *__single a;
  a = return_flex(arr);
  a->count = 9;
}

// CHECK-LABEL: define dso_local void @pointer_count_init_good(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void pointer_count_init_good() {
  int arr[11] = {10};
  flex_t *__single a = return_flex(arr);
  a->count = 9;
}

// CHECK-LABEL: define dso_local void @elem_access_good(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[CONT67:.*:]]
// CHECK-NEXT:    ret void
//
void elem_access_good() {
  int arr[11] = {10};
  flex_t *__single a;
  a = return_flex(arr);
  a->elems[9] = 0;
}

// CHECK-LABEL: define dso_local void @elem_access_trap(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[TRAP:.*:]]
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
void elem_access_trap() {
  int arr[11] = {10};
  flex_t *__single a;
  a = return_flex(arr);
  a->elems[10] = 0;
}
