// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --version 6

// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

// CHECK-LABEL: define dso_local ptr @indexable(
// CHECK-SAME: ptr noundef [[PTR_COERCE0:%.*]], ptr noundef [[PTR_COERCE1:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[PTR:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-NEXT:    [[TERMINATED_BY_CUR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[PTR]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[PTR_COERCE0]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[PTR]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[PTR_COERCE1]], ptr [[TMP1]], align 8
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 16, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ult ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[TMP2]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TERMINATED_BY_CUR]], align 8
// CHECK-NEXT:    br label %[[TERMINATED_BY_LOOP_COND:.*]]
// CHECK:       [[TERMINATED_BY_LOOP_COND]]:
// CHECK-NEXT:    [[TERMINATED_BY_CUR1:%.*]] = load ptr, ptr [[TERMINATED_BY_CUR]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TERMINATED_BY_ONE_PAST_CUR:%.*]] = getelementptr inbounds i32, ptr [[TERMINATED_BY_CUR1]], i64 1, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TERMINATED_BY_CHECK_ACCESS:%.*]] = icmp ule ptr [[TERMINATED_BY_ONE_PAST_CUR]], [[WIDE_PTR_UB]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[TERMINATED_BY_CHECK_ACCESS]], label %[[CONT3:.*]], label %[[TRAP2:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP2]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT3]]:
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TERMINATED_BY_CUR1]], align 4
// CHECK-NEXT:    [[TERMINATED_BY_CHECK_TERMINATOR:%.*]] = icmp eq i32 [[TMP3]], 0
// CHECK-NEXT:    br i1 [[TERMINATED_BY_CHECK_TERMINATOR]], label %[[TERMINATED_BY_LOOP_END:.*]], label %[[TERMINATED_BY_LOOP_CONT:.*]]
// CHECK:       [[TERMINATED_BY_LOOP_CONT]]:
// CHECK-NEXT:    store ptr [[TERMINATED_BY_ONE_PAST_CUR]], ptr [[TERMINATED_BY_CUR]], align 8
// CHECK-NEXT:    br label %[[TERMINATED_BY_LOOP_COND]]
// CHECK:       [[TERMINATED_BY_LOOP_END]]:
// CHECK-NEXT:    ret ptr [[WIDE_PTR_PTR]]
//
int *__null_terminated indexable(int *__indexable ptr) {
  return __unsafe_null_terminated_from_indexable(ptr);
}

// CHECK-LABEL: define dso_local ptr @bidi_indexable(
// CHECK-SAME: ptr noundef byval(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-NEXT:    [[TERMINATED_BY_CUR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[PTR]], i64 24, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP0:%.*]] = icmp uge ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_LB]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[TMP0]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP2]], align 8
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR3:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR2]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB5:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR4]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = icmp ult ptr [[WIDE_PTR_PTR3]], [[WIDE_PTR_UB5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[TMP3]], label %[[CONT7:.*]], label %[[TRAP6:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP6]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT7]]:
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR3]], ptr [[TERMINATED_BY_CUR]], align 8
// CHECK-NEXT:    br label %[[TERMINATED_BY_LOOP_COND:.*]]
// CHECK:       [[TERMINATED_BY_LOOP_COND]]:
// CHECK-NEXT:    [[TERMINATED_BY_CUR8:%.*]] = load ptr, ptr [[TERMINATED_BY_CUR]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TERMINATED_BY_ONE_PAST_CUR:%.*]] = getelementptr inbounds i32, ptr [[TERMINATED_BY_CUR8]], i64 1, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TERMINATED_BY_CHECK_ACCESS:%.*]] = icmp ule ptr [[TERMINATED_BY_ONE_PAST_CUR]], [[WIDE_PTR_UB5]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[TERMINATED_BY_CHECK_ACCESS]], label %[[CONT10:.*]], label %[[TRAP9:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP9]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT10]]:
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[TERMINATED_BY_CUR8]], align 4
// CHECK-NEXT:    [[TERMINATED_BY_CHECK_TERMINATOR:%.*]] = icmp eq i32 [[TMP4]], 0
// CHECK-NEXT:    br i1 [[TERMINATED_BY_CHECK_TERMINATOR]], label %[[TERMINATED_BY_LOOP_END:.*]], label %[[TERMINATED_BY_LOOP_CONT:.*]]
// CHECK:       [[TERMINATED_BY_LOOP_CONT]]:
// CHECK-NEXT:    store ptr [[TERMINATED_BY_ONE_PAST_CUR]], ptr [[TERMINATED_BY_CUR]], align 8
// CHECK-NEXT:    br label %[[TERMINATED_BY_LOOP_COND]]
// CHECK:       [[TERMINATED_BY_LOOP_END]]:
// CHECK-NEXT:    ret ptr [[WIDE_PTR_PTR3]]
//
int *__null_terminated bidi_indexable(int *__bidi_indexable ptr) {
  return __unsafe_null_terminated_from_indexable(ptr);
}

// CHECK-LABEL: define dso_local ptr @nested_indexable(
// CHECK-SAME: ptr noundef [[PTR_COERCE0:%.*]], ptr noundef [[PTR_COERCE1:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[PTR:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable.0", align 8
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable.0", align 8
// CHECK-NEXT:    [[TERMINATED_BY_CUR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[PTR]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[PTR_COERCE0]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw { ptr, ptr }, ptr [[PTR]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[PTR_COERCE1]], ptr [[TMP1]], align 8
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 16, i1 false)
// CHECK-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable.0", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable.0", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ult ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_UB]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[TMP2]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT]]:
// CHECK-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TERMINATED_BY_CUR]], align 8
// CHECK-NEXT:    br label %[[TERMINATED_BY_LOOP_COND:.*]]
// CHECK:       [[TERMINATED_BY_LOOP_COND]]:
// CHECK-NEXT:    [[TERMINATED_BY_CUR1:%.*]] = load ptr, ptr [[TERMINATED_BY_CUR]], align 8, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TERMINATED_BY_ONE_PAST_CUR:%.*]] = getelementptr inbounds ptr, ptr [[TERMINATED_BY_CUR1]], i64 1, {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TERMINATED_BY_CHECK_ACCESS:%.*]] = icmp ule ptr [[TERMINATED_BY_ONE_PAST_CUR]], [[WIDE_PTR_UB]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[TERMINATED_BY_CHECK_ACCESS]], label %[[CONT3:.*]], label %[[TRAP2:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP2]]:
// CHECK-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT3]]:
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TERMINATED_BY_CUR1]], align 8
// CHECK-NEXT:    [[TERMINATED_BY_CHECK_TERMINATOR:%.*]] = icmp eq ptr [[TMP3]], inttoptr (i64 -1 to ptr)
// CHECK-NEXT:    br i1 [[TERMINATED_BY_CHECK_TERMINATOR]], label %[[TERMINATED_BY_LOOP_END:.*]], label %[[TERMINATED_BY_LOOP_CONT:.*]]
// CHECK:       [[TERMINATED_BY_LOOP_CONT]]:
// CHECK-NEXT:    store ptr [[TERMINATED_BY_ONE_PAST_CUR]], ptr [[TERMINATED_BY_CUR]], align 8
// CHECK-NEXT:    br label %[[TERMINATED_BY_LOOP_COND]]
// CHECK:       [[TERMINATED_BY_LOOP_END]]:
// CHECK-NEXT:    ret ptr [[WIDE_PTR_PTR]]
//
int *__single *__terminated_by(-1) nested_indexable(int *__single *__indexable ptr) {
  return __unsafe_terminated_by_from_indexable(-1, ptr);
}
