// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --include-generated-funcs --version 5

// RUN: %clang_cc1 -O0 -triple arm64e-apple-ios -fbounds-safety \
// RUN:   -funique-traps -emit-llvm %s -o - \
// RUN: | FileCheck -check-prefix=OPT0 %s
// RUN: %clang_cc1 -O2 -triple arm64e-apple-ios -fbounds-safety \
// RUN:   -funique-traps -emit-llvm %s -disable-llvm-passes -o - \
// RUN: | FileCheck -check-prefix=OPT2 %s

#include <ptrcheck.h>

int consume(int* __bidi_indexable ptr, int idx) {
  return ptr[idx];
}
// OPT0-LABEL: define i32 @consume(
// OPT0-SAME: ptr dead_on_return noundef [[PTR:%.*]], i32 noundef [[IDX:%.*]]) #[[ATTR0:[0-9]+]] {
// OPT0-NEXT:  [[ENTRY:.*:]]
// OPT0-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// OPT0-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// OPT0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OPT0-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// OPT0-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4
// OPT0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// OPT0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OPT0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// OPT0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4
// OPT0-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP0]] to i64
// OPT0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// OPT0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OPT0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// OPT0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OPT0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// OPT0-NEXT:    [[TMP1:%.*]] = icmp ult ptr [[ARRAYIDX]], [[WIDE_PTR_UB]], !annotation [[META2:![0-9]+]]
// OPT0-NEXT:    br i1 [[TMP1]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF3:![0-9]+]], !annotation [[META2]]
// OPT0:       [[TRAP]]:
// OPT0-NEXT:    call void asm sideeffect "", "n"(i64 0), !annotation [[META2]]
// OPT0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation [[META2]]
// OPT0-NEXT:    unreachable, !annotation [[META2]]
// OPT0:       [[CONT]]:
// OPT0-NEXT:    [[TMP2:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META4:![0-9]+]]
// OPT0-NEXT:    br i1 [[TMP2]], label %[[CONT2:.*]], label %[[TRAP1:.*]], !prof [[PROF3]], !annotation [[META4]]
// OPT0:       [[TRAP1]]:
// OPT0-NEXT:    call void asm sideeffect "", "n"(i64 1), !annotation [[META4]]
// OPT0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META4]]
// OPT0-NEXT:    unreachable, !annotation [[META4]]
// OPT0:       [[CONT2]]:
// OPT0-NEXT:    [[TMP3:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// OPT0-NEXT:    ret i32 [[TMP3]]
//
//
// OPT2-LABEL: define i32 @consume(
// OPT2-SAME: ptr dead_on_return noundef [[PTR:%.*]], i32 noundef [[IDX:%.*]]) #[[ATTR0:[0-9]+]] {
// OPT2-NEXT:  [[ENTRY:.*:]]
// OPT2-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// OPT2-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// OPT2-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OPT2-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8, !tbaa [[TBAA2:![0-9]+]]
// OPT2-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4, !tbaa [[TBAA8:![0-9]+]]
// OPT2-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false), !tbaa.struct [[TBAA_STRUCT10:![0-9]+]]
// OPT2-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OPT2-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// OPT2-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4, !tbaa [[TBAA8]]
// OPT2-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP0]] to i64
// OPT2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// OPT2-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OPT2-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// OPT2-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OPT2-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// OPT2-NEXT:    [[TMP1:%.*]] = icmp ult ptr [[ARRAYIDX]], [[WIDE_PTR_UB]], !annotation [[META13:![0-9]+]]
// OPT2-NEXT:    br i1 [[TMP1]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF14:![0-9]+]], !annotation [[META13]]
// OPT2:       [[TRAP]]:
// OPT2-NEXT:    call void asm sideeffect "", "n"(i64 0), !annotation [[META13]]
// OPT2-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation [[META13]]
// OPT2-NEXT:    unreachable, !annotation [[META13]]
// OPT2:       [[CONT]]:
// OPT2-NEXT:    [[TMP2:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META15:![0-9]+]]
// OPT2-NEXT:    br i1 [[TMP2]], label %[[CONT2:.*]], label %[[TRAP1:.*]], !prof [[PROF14]], !annotation [[META15]]
// OPT2:       [[TRAP1]]:
// OPT2-NEXT:    call void asm sideeffect "", "n"(i64 1), !annotation [[META15]]
// OPT2-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META15]]
// OPT2-NEXT:    unreachable, !annotation [[META15]]
// OPT2:       [[CONT2]]:
// OPT2-NEXT:    [[TMP3:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA8]]
// OPT2-NEXT:    ret i32 [[TMP3]]
//
//.
// OPT0: [[META2]] = !{!"bounds-safety-check-ptr-lt-upper-bound"}
// OPT0: [[PROF3]] = !{!"branch_weights", i32 1048575, i32 1}
// OPT0: [[META4]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
//.
// OPT2: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// OPT2: [[META3]] = !{!"p2 int", [[META4:![0-9]+]], i64 0}
// OPT2: [[META4]] = !{!"any p2 pointer", [[META5:![0-9]+]], i64 0}
// OPT2: [[META5]] = !{!"any pointer", [[META6:![0-9]+]], i64 0}
// OPT2: [[META6]] = !{!"omnipotent char", [[META7:![0-9]+]], i64 0}
// OPT2: [[META7]] = !{!"Simple C/C++ TBAA"}
// OPT2: [[TBAA8]] = !{[[META9:![0-9]+]], [[META9]], i64 0}
// OPT2: [[META9]] = !{!"int", [[META6]], i64 0}
// OPT2: [[TBAA_STRUCT10]] = !{i64 0, i64 24, [[META11:![0-9]+]]}
// OPT2: [[META11]] = !{[[META12:![0-9]+]], [[META12]], i64 0}
// OPT2: [[META12]] = !{!"p1 int", [[META5]], i64 0}
// OPT2: [[META13]] = !{!"bounds-safety-check-ptr-lt-upper-bound"}
// OPT2: [[PROF14]] = !{!"branch_weights", i32 1048575, i32 1}
// OPT2: [[META15]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
//.
