# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 3
# RUN: llc -mtriple=amdgcn -mcpu=gfx1030 -run-pass amdgpu-prelegalizer-combiner %s -o - | FileCheck -check-prefix=GCN %s

---
name:            non_inlineable_imm_splat
body:             |
  bb.1:
    liveins: $vgpr0

    ; GCN-LABEL: name: non_inlineable_imm_splat
    ; GCN: liveins: $vgpr0
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: [[COPY:%[0-9]+]]:_(<2 x i16>) = COPY $vgpr0
    ; GCN-NEXT: [[C:%[0-9]+]]:_(f16) = G_FCONSTANT half 0xH4200
    ; GCN-NEXT: [[BITCAST:%[0-9]+]]:_(i16) = G_BITCAST [[C]](f16)
    ; GCN-NEXT: [[BITCAST1:%[0-9]+]]:_(i16) = G_BITCAST [[C]](f16)
    ; GCN-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x i16>) = G_BUILD_VECTOR [[BITCAST]](i16), [[BITCAST1]](i16)
    ; GCN-NEXT: [[SUB:%[0-9]+]]:_(<2 x i16>) = G_SUB [[COPY]], [[BUILD_VECTOR]]
    ; GCN-NEXT: $vgpr0 = COPY [[SUB]](<2 x i16>)
    ; GCN-NEXT: SI_RETURN implicit $vgpr0
    %0:_(<2 x i16>) = COPY $vgpr0
    %1:_(f16) = G_FCONSTANT half 0xH4200
    %2:_(i16) = G_BITCAST %1(f16)
    %3:_(i16) = G_BITCAST %1(f16)
    %4:_(<2 x i16>) = G_BUILD_VECTOR %2(i16), %3(i16)
    %5:_(<2 x i16>) = G_SUB %0, %4
    $vgpr0 = COPY %5(<2 x i16>)
    SI_RETURN implicit $vgpr0

...
