# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=amdgcn -run-pass=amdgpu-prelegalizer-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name: fshl_i32
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3

    ; CHECK-LABEL: name: fshl_i32
    ; CHECK: liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %a:_(s32) = COPY $vgpr0
    ; CHECK-NEXT: %b:_(s32) = COPY $vgpr1
    ; CHECK-NEXT: %amt:_(s32) = COPY $vgpr2
    ; CHECK-NEXT: %or:_(s32) = G_FSHL %a, %b, %amt(s32)
    ; CHECK-NEXT: $vgpr3 = COPY %or(s32)
    %a:_(s32) = COPY $vgpr0
    %b:_(s32) = COPY $vgpr1
    %amt:_(s32) = COPY $vgpr2
    %bw:_(s32) = G_CONSTANT i32 32
    %shl:_(s32) = G_SHL %a:_, %amt:_(s32)
    %sub:_(s32) = G_SUB %bw:_, %amt:_
    %lshr:_(s32) = G_LSHR %b:_, %sub:_(s32)
    %or:_(s32) = G_OR %shl:_, %lshr:_
    $vgpr3 = COPY %or
...

---
name: fshl_commute_i32
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3

    ; CHECK-LABEL: name: fshl_commute_i32
    ; CHECK: liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %a:_(s32) = COPY $vgpr0
    ; CHECK-NEXT: %b:_(s32) = COPY $vgpr1
    ; CHECK-NEXT: %amt:_(s32) = COPY $vgpr2
    ; CHECK-NEXT: %or:_(s32) = G_FSHL %a, %b, %amt(s32)
    ; CHECK-NEXT: $vgpr3 = COPY %or(s32)
    %a:_(s32) = COPY $vgpr0
    %b:_(s32) = COPY $vgpr1
    %amt:_(s32) = COPY $vgpr2
    %bw:_(s32) = G_CONSTANT i32 32
    %shl:_(s32) = G_SHL %a:_, %amt:_(s32)
    %sub:_(s32) = G_SUB %bw:_, %amt:_
    %lshr:_(s32) = G_LSHR %b:_, %sub:_(s32)
    %or:_(s32) = G_OR %lshr:_, %shl:_
    $vgpr3 = COPY %or
...

---
name: fshr_i32
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3

    ; CHECK-LABEL: name: fshr_i32
    ; CHECK: liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %a:_(s32) = COPY $vgpr0
    ; CHECK-NEXT: %b:_(s32) = COPY $vgpr1
    ; CHECK-NEXT: %amt:_(s32) = COPY $vgpr2
    ; CHECK-NEXT: %or:_(s32) = G_FSHR %a, %b, %amt(s32)
    ; CHECK-NEXT: $vgpr3 = COPY %or(s32)
    %a:_(s32) = COPY $vgpr0
    %b:_(s32) = COPY $vgpr1
    %amt:_(s32) = COPY $vgpr2
    %bw:_(s32) = G_CONSTANT i32 32
    %lshr:_(s32) = G_LSHR %b:_, %amt:_(s32)
    %sub:_(s32) = G_SUB %bw:_, %amt:_
    %shl:_(s32) = G_SHL %a:_, %sub:_(s32)
    %or:_(s32) = G_OR %shl:_, %lshr:_
    $vgpr3 = COPY %or
...

---
name: fshl_i32_bad_const
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3

    ; CHECK-LABEL: name: fshl_i32_bad_const
    ; CHECK: liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %a:_(s32) = COPY $vgpr0
    ; CHECK-NEXT: %b:_(s32) = COPY $vgpr1
    ; CHECK-NEXT: %amt:_(s32) = COPY $vgpr2
    ; CHECK-NEXT: %bw:_(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: %shl:_(s32) = G_SHL %a, %amt(s32)
    ; CHECK-NEXT: %sub:_(s32) = G_SUB %bw, %amt
    ; CHECK-NEXT: %lshr:_(s32) = G_LSHR %b, %sub(s32)
    ; CHECK-NEXT: %or:_(s32) = G_OR %shl, %lshr
    ; CHECK-NEXT: $vgpr3 = COPY %or(s32)
    %a:_(s32) = COPY $vgpr0
    %b:_(s32) = COPY $vgpr1
    %amt:_(s32) = COPY $vgpr2
    %bw:_(s32) = G_CONSTANT i32 31
    %shl:_(s32) = G_SHL %a:_, %amt:_(s32)
    %sub:_(s32) = G_SUB %bw:_, %amt:_
    %lshr:_(s32) = G_LSHR %b:_, %sub:_(s32)
    %or:_(s32) = G_OR %shl:_, %lshr:_
    $vgpr3 = COPY %or
...

---
name: fshl_i32_bad_amt_reg
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4

    ; CHECK-LABEL: name: fshl_i32_bad_amt_reg
    ; CHECK: liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %a:_(s32) = COPY $vgpr0
    ; CHECK-NEXT: %b:_(s32) = COPY $vgpr1
    ; CHECK-NEXT: %amt:_(s32) = COPY $vgpr2
    ; CHECK-NEXT: %amt1:_(s32) = COPY $vgpr3
    ; CHECK-NEXT: %bw:_(s32) = G_CONSTANT i32 32
    ; CHECK-NEXT: %shl:_(s32) = G_SHL %a, %amt(s32)
    ; CHECK-NEXT: %sub:_(s32) = G_SUB %bw, %amt1
    ; CHECK-NEXT: %lshr:_(s32) = G_LSHR %b, %sub(s32)
    ; CHECK-NEXT: %or:_(s32) = G_OR %shl, %lshr
    ; CHECK-NEXT: $vgpr4 = COPY %or(s32)
    %a:_(s32) = COPY $vgpr0
    %b:_(s32) = COPY $vgpr1
    %amt:_(s32) = COPY $vgpr2
    %amt1:_(s32) = COPY $vgpr3
    %bw:_(s32) = G_CONSTANT i32 32
    %shl:_(s32) = G_SHL %a:_, %amt:_(s32)
    %sub:_(s32) = G_SUB %bw:_, %amt1:_
    %lshr:_(s32) = G_LSHR %b:_, %sub:_(s32)
    %or:_(s32) = G_OR %shl:_, %lshr:_
    $vgpr4 = COPY %or
...
