; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -global-isel -new-reg-bank-select -mtriple=amdgcn -mcpu=gfx900 < %s | FileCheck -check-prefixes=GCN,GFX9 %s
; RUN: llc -global-isel -new-reg-bank-select -mtriple=amdgcn -mcpu=gfx1200 < %s | FileCheck -check-prefixes=GCN,GFX12 %s

define amdgpu_ps half @fsqrt_f16_uniform(half inreg %x) {
; GFX9-LABEL: fsqrt_f16_uniform:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    v_sqrt_f16_e32 v0, s0
; GFX9-NEXT:    ; return to shader part epilog
;
; GFX12-LABEL: fsqrt_f16_uniform:
; GFX12:       ; %bb.0:
; GFX12-NEXT:    v_s_sqrt_f16 s0, s0
; GFX12-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-NEXT:    s_delay_alu instid0(TRANS32_DEP_1)
; GFX12-NEXT:    v_mov_b32_e32 v0, s0
; GFX12-NEXT:    ; return to shader part epilog
  %result = call half @llvm.sqrt.f16(half %x)
  ret half %result
}

define amdgpu_ps half @fsqrt_f16_divergent(half %x) {
; GCN-LABEL: fsqrt_f16_divergent:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_sqrt_f16_e32 v0, v0
; GCN-NEXT:    ; return to shader part epilog
  %result = call half @llvm.sqrt.f16(half %x)
  ret half %result
}

declare half @llvm.sqrt.f16(half)
