# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -amdgpu-global-isel-new-legality -march=amdgcn -mcpu=tahiti -run-pass=instruction-select -verify-machineinstrs  -global-isel-abort=0 -o - %s | FileCheck -check-prefix=GFX6 %s
# RUN: llc -amdgpu-global-isel-new-legality -march=amdgcn -mcpu=hawaii -run-pass=instruction-select -verify-machineinstrs  -global-isel-abort=0 -o - %s | FileCheck -check-prefix=GFX7 %s
# RUN: llc -amdgpu-global-isel-new-legality -march=amdgcn -mcpu=fiji -run-pass=instruction-select -verify-machineinstrs -global-isel-abort=0 -o - %s | FileCheck -check-prefix=GFX8 %s
# RUN: llc -amdgpu-global-isel-new-legality -march=amdgcn -mcpu=gfx1010 -run-pass=instruction-select -verify-machineinstrs -global-isel-abort=0 -o - %s | FileCheck -check-prefix=GFX10 %s
# RUN: llc -amdgpu-global-isel-new-legality -march=amdgcn -mcpu=gfx1100 -run-pass=instruction-select -verify-machineinstrs -global-isel-abort=0 -o - %s | FileCheck -check-prefix=GFX10 %s

---

name: load_constant_s32_from_4
legalized:       true
regBankSelected: true
tracksRegLiveness: true


body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_s32_from_4
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (s32), addrspace 4)
    ; GFX6-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX7-LABEL: name: load_constant_s32_from_4
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (s32), addrspace 4)
    ; GFX7-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX8-LABEL: name: load_constant_s32_from_4
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (s32), addrspace 4)
    ; GFX8-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX10-LABEL: name: load_constant_s32_from_4
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (s32), addrspace 4)
    ; GFX10-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(s32) = G_LOAD %0 :: (load (s32), align 4, addrspace 4)
    $sgpr0 = COPY %1

...

---

name: load_constant_v2s16_from_4
legalized:       true
regBankSelected: true
tracksRegLiveness: true


body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_v2s16_from_4
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s16>), addrspace 4)
    ; GFX6-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX7-LABEL: name: load_constant_v2s16_from_4
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s16>), addrspace 4)
    ; GFX7-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX8-LABEL: name: load_constant_v2s16_from_4
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s16>), addrspace 4)
    ; GFX8-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX10-LABEL: name: load_constant_v2s16_from_4
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s16>), addrspace 4)
    ; GFX10-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(<2 x s16>) = G_LOAD %0 :: (load (<2 x s16>), align 4, addrspace 4)
    $sgpr0 = COPY %1

...


---
name: load_constant_v2s32
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_v2s32
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s32>), addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX7-LABEL: name: load_constant_v2s32
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s32>), addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX8-LABEL: name: load_constant_v2s32
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s32>), addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX10-LABEL: name: load_constant_v2s32
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s32>), addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(<2 x s32>) = G_LOAD %0 :: (load (<2 x s32>), align 8, addrspace 4)
    $sgpr0_sgpr1 = COPY %1

...

---
name: load_constant_v2s32_align4
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_v2s32_align4
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s32>), align 4, addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX7-LABEL: name: load_constant_v2s32_align4
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s32>), align 4, addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX8-LABEL: name: load_constant_v2s32_align4
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s32>), align 4, addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX10-LABEL: name: load_constant_v2s32_align4
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s32>), align 4, addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(<2 x s32>) = G_LOAD %0 :: (load (<2 x s32>), align 4, addrspace 4)
    $sgpr0_sgpr1 = COPY %1

...

---
name: load_constant_v4s16_align4
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_v4s16_align4
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<4 x s16>), align 4, addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX7-LABEL: name: load_constant_v4s16_align4
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<4 x s16>), align 4, addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX8-LABEL: name: load_constant_v4s16_align4
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<4 x s16>), align 4, addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX10-LABEL: name: load_constant_v4s16_align4
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<4 x s16>), align 4, addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(<4 x s16>) = G_LOAD %0 :: (load (<4 x s16>), align 4, addrspace 4)
    $sgpr0_sgpr1 = COPY %1

...

---

name: load_constant_v4s32_align4
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_v4s32_align4
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORDX4_IMM:%[0-9]+]]:sgpr_128 = S_LOAD_DWORDX4_IMM [[PRED_COPY]], 0, 0 :: (load (<4 x s32>), align 4, addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[S_LOAD_DWORDX4_IMM]]
    ; GFX7-LABEL: name: load_constant_v4s32_align4
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORDX4_IMM:%[0-9]+]]:sgpr_128 = S_LOAD_DWORDX4_IMM [[PRED_COPY]], 0, 0 :: (load (<4 x s32>), align 4, addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[S_LOAD_DWORDX4_IMM]]
    ; GFX8-LABEL: name: load_constant_v4s32_align4
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORDX4_IMM:%[0-9]+]]:sgpr_128 = S_LOAD_DWORDX4_IMM [[PRED_COPY]], 0, 0 :: (load (<4 x s32>), align 4, addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[S_LOAD_DWORDX4_IMM]]
    ; GFX10-LABEL: name: load_constant_v4s32_align4
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORDX4_IMM:%[0-9]+]]:sgpr_128 = S_LOAD_DWORDX4_IMM [[PRED_COPY]], 0, 0 :: (load (<4 x s32>), align 4, addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[S_LOAD_DWORDX4_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(<4 x  s32>) = G_LOAD %0 :: (load (<4 x s32>), align 4, addrspace 4)
    $sgpr0_sgpr1_sgpr2_sgpr3 = COPY %1

...

---

name: load_constant_s64
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_s64
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (s64), addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX7-LABEL: name: load_constant_s64
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (s64), addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX8-LABEL: name: load_constant_s64
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (s64), addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX10-LABEL: name: load_constant_s64
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (s64), addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(s64) = G_LOAD %0 :: (load (s64), align 8, addrspace 4)
    $sgpr0_sgpr1 = COPY %1

...

---

name: load_constant_s64_align4
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_s64_align4
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (s64), align 4, addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX7-LABEL: name: load_constant_s64_align4
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (s64), align 4, addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX8-LABEL: name: load_constant_s64_align4
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (s64), align 4, addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX10-LABEL: name: load_constant_s64_align4
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (s64), align 4, addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(s64) = G_LOAD %0 :: (load (s64), align 4, addrspace 4)
    $sgpr0_sgpr1 = COPY %1

...

---

name: load_constant_v2s64
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_v2s64
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORDX4_IMM:%[0-9]+]]:sgpr_128 = S_LOAD_DWORDX4_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s64>), align 4, addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[S_LOAD_DWORDX4_IMM]]
    ; GFX7-LABEL: name: load_constant_v2s64
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORDX4_IMM:%[0-9]+]]:sgpr_128 = S_LOAD_DWORDX4_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s64>), align 4, addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[S_LOAD_DWORDX4_IMM]]
    ; GFX8-LABEL: name: load_constant_v2s64
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORDX4_IMM:%[0-9]+]]:sgpr_128 = S_LOAD_DWORDX4_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s64>), align 4, addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[S_LOAD_DWORDX4_IMM]]
    ; GFX10-LABEL: name: load_constant_v2s64
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORDX4_IMM:%[0-9]+]]:sgpr_128 = S_LOAD_DWORDX4_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s64>), align 4, addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[S_LOAD_DWORDX4_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(<2 x s64>) = G_LOAD %0 :: (load (<2 x s64>), align 4, addrspace 4)
    $sgpr0_sgpr1_sgpr2_sgpr3 = COPY %1

...

---

name: load_constant_v2p1
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_v2p1
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[LOAD:%[0-9]+]]:sgpr_128(<2 x p1>) = G_LOAD [[COPY]](p4) :: (load (<2 x p1>), align 4, addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[LOAD]](<2 x p1>)
    ; GFX7-LABEL: name: load_constant_v2p1
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[LOAD:%[0-9]+]]:sgpr_128(<2 x p1>) = G_LOAD [[COPY]](p4) :: (load (<2 x p1>), align 4, addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[LOAD]](<2 x p1>)
    ; GFX8-LABEL: name: load_constant_v2p1
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[LOAD:%[0-9]+]]:sgpr_128(<2 x p1>) = G_LOAD [[COPY]](p4) :: (load (<2 x p1>), align 4, addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[LOAD]](<2 x p1>)
    ; GFX10-LABEL: name: load_constant_v2p1
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[LOAD:%[0-9]+]]:sgpr_128(<2 x p1>) = G_LOAD [[COPY]](p4) :: (load (<2 x p1>), align 4, addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[LOAD]](<2 x p1>)
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(<2 x p1>) = G_LOAD %0 :: (load (<2 x p1>), align 4, addrspace 4)
    $sgpr0_sgpr1_sgpr2_sgpr3 = COPY %1

...

---

name: load_constant_s128_align4
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_s128_align4
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[LOAD:%[0-9]+]]:sgpr_128(s128) = G_LOAD [[COPY]](p4) :: (load (s128), align 4, addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[LOAD]](s128)
    ; GFX7-LABEL: name: load_constant_s128_align4
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[LOAD:%[0-9]+]]:sgpr_128(s128) = G_LOAD [[COPY]](p4) :: (load (s128), align 4, addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[LOAD]](s128)
    ; GFX8-LABEL: name: load_constant_s128_align4
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[LOAD:%[0-9]+]]:sgpr_128(s128) = G_LOAD [[COPY]](p4) :: (load (s128), align 4, addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[LOAD]](s128)
    ; GFX10-LABEL: name: load_constant_s128_align4
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[LOAD:%[0-9]+]]:sgpr_128(s128) = G_LOAD [[COPY]](p4) :: (load (s128), align 4, addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[LOAD]](s128)
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(s128) = G_LOAD %0 :: (load (s128), align 4, addrspace 4)
    $sgpr0_sgpr1_sgpr2_sgpr3 = COPY %1

...

---

name: load_constant_p3_from_4
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_p3_from_4
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (p3), addrspace 4)
    ; GFX6-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX7-LABEL: name: load_constant_p3_from_4
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (p3), addrspace 4)
    ; GFX7-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX8-LABEL: name: load_constant_p3_from_4
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (p3), addrspace 4)
    ; GFX8-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX10-LABEL: name: load_constant_p3_from_4
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (p3), addrspace 4)
    ; GFX10-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(p3) = G_LOAD %0 :: (load (p3), align 4, addrspace 4)
    $sgpr0 = COPY %1

...

---

name: load_constant_p4_from_8
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_p4_from_8
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (p4), addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX7-LABEL: name: load_constant_p4_from_8
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (p4), addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX8-LABEL: name: load_constant_p4_from_8
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (p4), addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX10-LABEL: name: load_constant_p4_from_8
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (p4), addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(p4) = G_LOAD %0 :: (load (p4), align 8, addrspace 4)
    $sgpr0_sgpr1 = COPY %1

...

---

name: load_constant_p999_from_8
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_p999_from_8
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[LOAD:%[0-9]+]]:sreg_64(p999) = G_LOAD [[COPY]](p4) :: (load (p999), addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1 = PRED_COPY [[LOAD]](p999)
    ; GFX7-LABEL: name: load_constant_p999_from_8
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[LOAD:%[0-9]+]]:sreg_64(p999) = G_LOAD [[COPY]](p4) :: (load (p999), addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1 = PRED_COPY [[LOAD]](p999)
    ; GFX8-LABEL: name: load_constant_p999_from_8
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[LOAD:%[0-9]+]]:sreg_64(p999) = G_LOAD [[COPY]](p4) :: (load (p999), addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1 = PRED_COPY [[LOAD]](p999)
    ; GFX10-LABEL: name: load_constant_p999_from_8
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[LOAD:%[0-9]+]]:sreg_64(p999) = G_LOAD [[COPY]](p4) :: (load (p999), addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1 = PRED_COPY [[LOAD]](p999)
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(p999) = G_LOAD %0 :: (load (p999), align 8, addrspace 4)
    $sgpr0_sgpr1 = COPY %1

...

---

name: load_constant_v2p3
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_v2p3
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[LOAD:%[0-9]+]]:sreg_64(<2 x p3>) = G_LOAD [[COPY]](p4) :: (load (<2 x p3>), addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1 = PRED_COPY [[LOAD]](<2 x p3>)
    ; GFX7-LABEL: name: load_constant_v2p3
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[LOAD:%[0-9]+]]:sreg_64(<2 x p3>) = G_LOAD [[COPY]](p4) :: (load (<2 x p3>), addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1 = PRED_COPY [[LOAD]](<2 x p3>)
    ; GFX8-LABEL: name: load_constant_v2p3
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[LOAD:%[0-9]+]]:sreg_64(<2 x p3>) = G_LOAD [[COPY]](p4) :: (load (<2 x p3>), addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1 = PRED_COPY [[LOAD]](<2 x p3>)
    ; GFX10-LABEL: name: load_constant_v2p3
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:sgpr(p4) = COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[LOAD:%[0-9]+]]:sreg_64(<2 x p3>) = G_LOAD [[COPY]](p4) :: (load (<2 x p3>), addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1 = PRED_COPY [[LOAD]](<2 x p3>)
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(<2 x p3>) = G_LOAD %0 :: (load (<2 x p3>), align 8, addrspace 4)
    $sgpr0_sgpr1 = COPY %1

...

---

name: load_constant_v2s16
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_v2s16
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s16>), addrspace 4)
    ; GFX6-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX7-LABEL: name: load_constant_v2s16
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s16>), addrspace 4)
    ; GFX7-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX8-LABEL: name: load_constant_v2s16
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s16>), addrspace 4)
    ; GFX8-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX10-LABEL: name: load_constant_v2s16
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 0, 0 :: (load (<2 x s16>), addrspace 4)
    ; GFX10-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(<2 x s16>) = G_LOAD %0 :: (load (<2 x s16>), align 4, addrspace 4)
    $sgpr0 = COPY %1

...

---

name: load_constant_v4s16
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_v4s16
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<4 x s16>), addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX7-LABEL: name: load_constant_v4s16
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<4 x s16>), addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX8-LABEL: name: load_constant_v4s16
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<4 x s16>), addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX10-LABEL: name: load_constant_v4s16
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[PRED_COPY]], 0, 0 :: (load (<4 x s16>), addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1 = PRED_COPY [[S_LOAD_DWORDX2_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(<4 x s16>) = G_LOAD %0 :: (load (<4 x s16>), align 8, addrspace 4)
    $sgpr0_sgpr1 = COPY %1

...

---

name: load_constant_v8s16
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_v8s16
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORDX4_IMM:%[0-9]+]]:sgpr_128 = S_LOAD_DWORDX4_IMM [[PRED_COPY]], 0, 0 :: (load (<8 x s16>), align 4, addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[S_LOAD_DWORDX4_IMM]]
    ; GFX7-LABEL: name: load_constant_v8s16
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORDX4_IMM:%[0-9]+]]:sgpr_128 = S_LOAD_DWORDX4_IMM [[PRED_COPY]], 0, 0 :: (load (<8 x s16>), align 4, addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[S_LOAD_DWORDX4_IMM]]
    ; GFX8-LABEL: name: load_constant_v8s16
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORDX4_IMM:%[0-9]+]]:sgpr_128 = S_LOAD_DWORDX4_IMM [[PRED_COPY]], 0, 0 :: (load (<8 x s16>), align 4, addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[S_LOAD_DWORDX4_IMM]]
    ; GFX10-LABEL: name: load_constant_v8s16
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORDX4_IMM:%[0-9]+]]:sgpr_128 = S_LOAD_DWORDX4_IMM [[PRED_COPY]], 0, 0 :: (load (<8 x s16>), align 4, addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = PRED_COPY [[S_LOAD_DWORDX4_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(<8 x s16>) = G_LOAD %0 :: (load (<8 x s16>), align 4, addrspace 4)
    $sgpr0_sgpr1_sgpr2_sgpr3 = COPY %1

...

---

name: load_constant_v8s32
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_v8s32
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORDX8_IMM:%[0-9]+]]:sgpr_256 = S_LOAD_DWORDX8_IMM [[PRED_COPY]], 0, 0 :: (load (<8 x s32>), align 4, addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7 = PRED_COPY [[S_LOAD_DWORDX8_IMM]]
    ; GFX7-LABEL: name: load_constant_v8s32
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORDX8_IMM:%[0-9]+]]:sgpr_256 = S_LOAD_DWORDX8_IMM [[PRED_COPY]], 0, 0 :: (load (<8 x s32>), align 4, addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7 = PRED_COPY [[S_LOAD_DWORDX8_IMM]]
    ; GFX8-LABEL: name: load_constant_v8s32
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORDX8_IMM:%[0-9]+]]:sgpr_256 = S_LOAD_DWORDX8_IMM [[PRED_COPY]], 0, 0 :: (load (<8 x s32>), align 4, addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7 = PRED_COPY [[S_LOAD_DWORDX8_IMM]]
    ; GFX10-LABEL: name: load_constant_v8s32
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORDX8_IMM:%[0-9]+]]:sgpr_256 = S_LOAD_DWORDX8_IMM [[PRED_COPY]], 0, 0 :: (load (<8 x s32>), align 4, addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7 = PRED_COPY [[S_LOAD_DWORDX8_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(<8 x s32>) = G_LOAD %0 :: (load (<8 x s32>), align 4, addrspace 4)
    $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7 = COPY %1

...

---

name: load_constant_v16s32
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_v16s32
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORDX16_IMM:%[0-9]+]]:sgpr_512 = S_LOAD_DWORDX16_IMM [[PRED_COPY]], 0, 0 :: (load (<16 x s32>), align 4, addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11_sgpr12_sgpr13_sgpr14_sgpr15 = PRED_COPY [[S_LOAD_DWORDX16_IMM]]
    ; GFX7-LABEL: name: load_constant_v16s32
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORDX16_IMM:%[0-9]+]]:sgpr_512 = S_LOAD_DWORDX16_IMM [[PRED_COPY]], 0, 0 :: (load (<16 x s32>), align 4, addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11_sgpr12_sgpr13_sgpr14_sgpr15 = PRED_COPY [[S_LOAD_DWORDX16_IMM]]
    ; GFX8-LABEL: name: load_constant_v16s32
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORDX16_IMM:%[0-9]+]]:sgpr_512 = S_LOAD_DWORDX16_IMM [[PRED_COPY]], 0, 0 :: (load (<16 x s32>), align 4, addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11_sgpr12_sgpr13_sgpr14_sgpr15 = PRED_COPY [[S_LOAD_DWORDX16_IMM]]
    ; GFX10-LABEL: name: load_constant_v16s32
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORDX16_IMM:%[0-9]+]]:sgpr_512 = S_LOAD_DWORDX16_IMM [[PRED_COPY]], 0, 0 :: (load (<16 x s32>), align 4, addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11_sgpr12_sgpr13_sgpr14_sgpr15 = PRED_COPY [[S_LOAD_DWORDX16_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(<16 x s32>) = G_LOAD %0 :: (load (<16 x s32>), align 4, addrspace 4)
    $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11_sgpr12_sgpr13_sgpr14_sgpr15 = COPY %1

...

---

name: load_constant_v8s64
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_v8s64
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORDX16_IMM:%[0-9]+]]:sgpr_512 = S_LOAD_DWORDX16_IMM [[PRED_COPY]], 0, 0 :: (load (<8 x s64>), align 4, addrspace 4)
    ; GFX6-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11_sgpr12_sgpr13_sgpr14_sgpr15 = PRED_COPY [[S_LOAD_DWORDX16_IMM]]
    ; GFX7-LABEL: name: load_constant_v8s64
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORDX16_IMM:%[0-9]+]]:sgpr_512 = S_LOAD_DWORDX16_IMM [[PRED_COPY]], 0, 0 :: (load (<8 x s64>), align 4, addrspace 4)
    ; GFX7-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11_sgpr12_sgpr13_sgpr14_sgpr15 = PRED_COPY [[S_LOAD_DWORDX16_IMM]]
    ; GFX8-LABEL: name: load_constant_v8s64
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORDX16_IMM:%[0-9]+]]:sgpr_512 = S_LOAD_DWORDX16_IMM [[PRED_COPY]], 0, 0 :: (load (<8 x s64>), align 4, addrspace 4)
    ; GFX8-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11_sgpr12_sgpr13_sgpr14_sgpr15 = PRED_COPY [[S_LOAD_DWORDX16_IMM]]
    ; GFX10-LABEL: name: load_constant_v8s64
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORDX16_IMM:%[0-9]+]]:sgpr_512 = S_LOAD_DWORDX16_IMM [[PRED_COPY]], 0, 0 :: (load (<8 x s64>), align 4, addrspace 4)
    ; GFX10-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11_sgpr12_sgpr13_sgpr14_sgpr15 = PRED_COPY [[S_LOAD_DWORDX16_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(<8 x s64>) = G_LOAD %0 :: (load (<8 x s64>), align 4, addrspace 4)
    $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11_sgpr12_sgpr13_sgpr14_sgpr15 = COPY %1

...

################################################################################
### Stress addressing modes
################################################################################

---

name: load_constant_s32_from_4_gep_1020
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_s32_from_4_gep_1020
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 255, 0 :: (load (s32), addrspace 4)
    ; GFX6-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX7-LABEL: name: load_constant_s32_from_4_gep_1020
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 255, 0 :: (load (s32), addrspace 4)
    ; GFX7-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX8-LABEL: name: load_constant_s32_from_4_gep_1020
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 1020, 0 :: (load (s32), addrspace 4)
    ; GFX8-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX10-LABEL: name: load_constant_s32_from_4_gep_1020
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 1020, 0 :: (load (s32), addrspace 4)
    ; GFX10-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(s64) = G_CONSTANT i64 1020
    %2:sgpr(p4) = G_PTR_ADD %0, %1
    %3:sgpr(s32) = G_LOAD %2 :: (load (s32), align 4, addrspace 4)
    $sgpr0 = COPY %3

...

---

name: load_constant_s32_from_4_gep_1024
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_s32_from_4_gep_1024
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1024
    ; GFX6-NEXT: [[S_LOAD_DWORD_SGPR:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_SGPR [[PRED_COPY]], [[S_MOV_B32_]], 0 :: (load (s32), addrspace 4)
    ; GFX6-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_SGPR]]
    ; GFX7-LABEL: name: load_constant_s32_from_4_gep_1024
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORD_IMM_ci:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM_ci [[PRED_COPY]], 256, 0 :: (load (s32), addrspace 4)
    ; GFX7-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM_ci]]
    ; GFX8-LABEL: name: load_constant_s32_from_4_gep_1024
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 1024, 0 :: (load (s32), addrspace 4)
    ; GFX8-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX10-LABEL: name: load_constant_s32_from_4_gep_1024
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 1024, 0 :: (load (s32), addrspace 4)
    ; GFX10-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(s64) = G_CONSTANT i64 1024
    %2:sgpr(p4) = G_PTR_ADD %0, %1
    %3:sgpr(s32) = G_LOAD %2 :: (load (s32), align 4, addrspace 4)
    $sgpr0 = COPY %3

...

---

name: load_constant_s32_from_4_gep_1048575
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_s32_from_4_gep_1048575
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1048575
    ; GFX6-NEXT: [[S_LOAD_DWORD_SGPR:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_SGPR [[PRED_COPY]], [[S_MOV_B32_]], 0 :: (load (s32), addrspace 4)
    ; GFX6-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_SGPR]]
    ; GFX7-LABEL: name: load_constant_s32_from_4_gep_1048575
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1048575
    ; GFX7-NEXT: [[S_LOAD_DWORD_SGPR:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_SGPR [[PRED_COPY]], [[S_MOV_B32_]], 0 :: (load (s32), addrspace 4)
    ; GFX7-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_SGPR]]
    ; GFX8-LABEL: name: load_constant_s32_from_4_gep_1048575
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], 1048575, 0 :: (load (s32), addrspace 4)
    ; GFX8-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX10-LABEL: name: load_constant_s32_from_4_gep_1048575
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1048575
    ; GFX10-NEXT: [[S_LOAD_DWORD_SGPR_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_SGPR_IMM [[PRED_COPY]], [[S_MOV_B32_]], 0, 0 :: (load (s32), addrspace 4)
    ; GFX10-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_SGPR_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(s64) = G_CONSTANT i64 1048575
    %2:sgpr(p4) = G_PTR_ADD %0, %1
    %3:sgpr(s32) = G_LOAD %2 :: (load (s32), align 4, addrspace 4)
    $sgpr0 = COPY %3

...

---

name: load_constant_s32_from_4_gep_1048576
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_s32_from_4_gep_1048576
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1048576
    ; GFX6-NEXT: [[S_LOAD_DWORD_SGPR:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_SGPR [[PRED_COPY]], [[S_MOV_B32_]], 0 :: (load (s32), addrspace 4)
    ; GFX6-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_SGPR]]
    ; GFX7-LABEL: name: load_constant_s32_from_4_gep_1048576
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_LOAD_DWORD_IMM_ci:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM_ci [[PRED_COPY]], 262144, 0 :: (load (s32), addrspace 4)
    ; GFX7-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM_ci]]
    ; GFX8-LABEL: name: load_constant_s32_from_4_gep_1048576
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1048576
    ; GFX8-NEXT: [[S_LOAD_DWORD_SGPR:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_SGPR [[PRED_COPY]], [[S_MOV_B32_]], 0 :: (load (s32), addrspace 4)
    ; GFX8-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_SGPR]]
    ; GFX10-LABEL: name: load_constant_s32_from_4_gep_1048576
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1048576
    ; GFX10-NEXT: [[S_LOAD_DWORD_SGPR_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_SGPR_IMM [[PRED_COPY]], [[S_MOV_B32_]], 0, 0 :: (load (s32), addrspace 4)
    ; GFX10-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_SGPR_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(s64) = G_CONSTANT i64 1048576
    %2:sgpr(p4) = G_PTR_ADD %0, %1
    %3:sgpr(s32) = G_LOAD %2 :: (load (s32), align 4, addrspace 4)
    $sgpr0 = COPY %3

...

---

name: load_constant_s32_from_4_gep_1073741823
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_s32_from_4_gep_1073741823
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1073741823
    ; GFX6-NEXT: [[S_LOAD_DWORD_SGPR:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_SGPR [[PRED_COPY]], [[S_MOV_B32_]], 0 :: (load (s32), addrspace 4)
    ; GFX6-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_SGPR]]
    ; GFX7-LABEL: name: load_constant_s32_from_4_gep_1073741823
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1073741823
    ; GFX7-NEXT: [[S_LOAD_DWORD_SGPR:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_SGPR [[PRED_COPY]], [[S_MOV_B32_]], 0 :: (load (s32), addrspace 4)
    ; GFX7-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_SGPR]]
    ; GFX8-LABEL: name: load_constant_s32_from_4_gep_1073741823
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1073741823
    ; GFX8-NEXT: [[S_LOAD_DWORD_SGPR:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_SGPR [[PRED_COPY]], [[S_MOV_B32_]], 0 :: (load (s32), addrspace 4)
    ; GFX8-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_SGPR]]
    ; GFX10-LABEL: name: load_constant_s32_from_4_gep_1073741823
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1073741823
    ; GFX10-NEXT: [[S_LOAD_DWORD_SGPR_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_SGPR_IMM [[PRED_COPY]], [[S_MOV_B32_]], 0, 0 :: (load (s32), addrspace 4)
    ; GFX10-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_SGPR_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(s64) = G_CONSTANT i64 1073741823
    %2:sgpr(p4) = G_PTR_ADD %0, %1
    %3:sgpr(s32) = G_LOAD %2 :: (load (s32), align 4, addrspace 4)
    $sgpr0 = COPY %3

...

---

name: load_constant_s32_from_4_gep_negative_1
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_s32_from_4_gep_negative_1
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_MOV_B64_:%[0-9]+]]:sreg_64 = S_MOV_B64 -1
    ; GFX6-NEXT: [[PRED_COPY1:%[0-9]+]]:sreg_32 = PRED_COPY [[PRED_COPY]].sub0
    ; GFX6-NEXT: [[PRED_COPY2:%[0-9]+]]:sreg_32 = PRED_COPY [[S_MOV_B64_]].sub0
    ; GFX6-NEXT: [[PRED_COPY3:%[0-9]+]]:sreg_32 = PRED_COPY [[PRED_COPY]].sub1
    ; GFX6-NEXT: [[PRED_COPY4:%[0-9]+]]:sreg_32 = PRED_COPY [[S_MOV_B64_]].sub1
    ; GFX6-NEXT: [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PRED_COPY1]], [[PRED_COPY2]], implicit-def $scc
    ; GFX6-NEXT: [[S_ADDC_U32_:%[0-9]+]]:sreg_32 = S_ADDC_U32 [[PRED_COPY3]], [[PRED_COPY4]], implicit-def $scc, implicit $scc
    ; GFX6-NEXT: [[REG_SEQUENCE:%[0-9]+]]:sreg_64_xexec = REG_SEQUENCE [[S_ADD_U32_]], %subreg.sub0, [[S_ADDC_U32_]], %subreg.sub1
    ; GFX6-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[REG_SEQUENCE]], 0, 0 :: (load (s32), addrspace 4)
    ; GFX6-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX7-LABEL: name: load_constant_s32_from_4_gep_negative_1
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_MOV_B64_:%[0-9]+]]:sreg_64 = S_MOV_B64 -1
    ; GFX7-NEXT: [[PRED_COPY1:%[0-9]+]]:sreg_32 = PRED_COPY [[PRED_COPY]].sub0
    ; GFX7-NEXT: [[PRED_COPY2:%[0-9]+]]:sreg_32 = PRED_COPY [[S_MOV_B64_]].sub0
    ; GFX7-NEXT: [[PRED_COPY3:%[0-9]+]]:sreg_32 = PRED_COPY [[PRED_COPY]].sub1
    ; GFX7-NEXT: [[PRED_COPY4:%[0-9]+]]:sreg_32 = PRED_COPY [[S_MOV_B64_]].sub1
    ; GFX7-NEXT: [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PRED_COPY1]], [[PRED_COPY2]], implicit-def $scc
    ; GFX7-NEXT: [[S_ADDC_U32_:%[0-9]+]]:sreg_32 = S_ADDC_U32 [[PRED_COPY3]], [[PRED_COPY4]], implicit-def $scc, implicit $scc
    ; GFX7-NEXT: [[REG_SEQUENCE:%[0-9]+]]:sreg_64_xexec = REG_SEQUENCE [[S_ADD_U32_]], %subreg.sub0, [[S_ADDC_U32_]], %subreg.sub1
    ; GFX7-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[REG_SEQUENCE]], 0, 0 :: (load (s32), addrspace 4)
    ; GFX7-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX8-LABEL: name: load_constant_s32_from_4_gep_negative_1
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_MOV_B64_:%[0-9]+]]:sreg_64 = S_MOV_B64 -1
    ; GFX8-NEXT: [[PRED_COPY1:%[0-9]+]]:sreg_32 = PRED_COPY [[PRED_COPY]].sub0
    ; GFX8-NEXT: [[PRED_COPY2:%[0-9]+]]:sreg_32 = PRED_COPY [[S_MOV_B64_]].sub0
    ; GFX8-NEXT: [[PRED_COPY3:%[0-9]+]]:sreg_32 = PRED_COPY [[PRED_COPY]].sub1
    ; GFX8-NEXT: [[PRED_COPY4:%[0-9]+]]:sreg_32 = PRED_COPY [[S_MOV_B64_]].sub1
    ; GFX8-NEXT: [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PRED_COPY1]], [[PRED_COPY2]], implicit-def $scc
    ; GFX8-NEXT: [[S_ADDC_U32_:%[0-9]+]]:sreg_32 = S_ADDC_U32 [[PRED_COPY3]], [[PRED_COPY4]], implicit-def $scc, implicit $scc
    ; GFX8-NEXT: [[REG_SEQUENCE:%[0-9]+]]:sreg_64_xexec = REG_SEQUENCE [[S_ADD_U32_]], %subreg.sub0, [[S_ADDC_U32_]], %subreg.sub1
    ; GFX8-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[REG_SEQUENCE]], 0, 0 :: (load (s32), addrspace 4)
    ; GFX8-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX10-LABEL: name: load_constant_s32_from_4_gep_negative_1
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], -1, 0 :: (load (s32), addrspace 4)
    ; GFX10-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(s64) = G_CONSTANT i64 -1
    %2:sgpr(p4) = G_PTR_ADD %0, %1
    %3:sgpr(s32) = G_LOAD %2 :: (load (s32), align 4, addrspace 4)
    $sgpr0 = COPY %3

...

---

name: load_constant_s32_from_4_gep_negative_524288
legalized:       true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins:  $sgpr0_sgpr1

    ; GFX6-LABEL: name: load_constant_s32_from_4_gep_negative_524288
    ; GFX6: liveins: $sgpr0_sgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX6-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 4294443008
    ; GFX6-NEXT: [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
    ; GFX6-NEXT: [[REG_SEQUENCE:%[0-9]+]]:sreg_64 = REG_SEQUENCE [[S_MOV_B32_]], %subreg.sub0, [[S_MOV_B32_1]], %subreg.sub1
    ; GFX6-NEXT: [[PRED_COPY1:%[0-9]+]]:sreg_32 = PRED_COPY [[PRED_COPY]].sub0
    ; GFX6-NEXT: [[PRED_COPY2:%[0-9]+]]:sreg_32 = PRED_COPY [[REG_SEQUENCE]].sub0
    ; GFX6-NEXT: [[PRED_COPY3:%[0-9]+]]:sreg_32 = PRED_COPY [[PRED_COPY]].sub1
    ; GFX6-NEXT: [[PRED_COPY4:%[0-9]+]]:sreg_32 = PRED_COPY [[REG_SEQUENCE]].sub1
    ; GFX6-NEXT: [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PRED_COPY1]], [[PRED_COPY2]], implicit-def $scc
    ; GFX6-NEXT: [[S_ADDC_U32_:%[0-9]+]]:sreg_32 = S_ADDC_U32 [[PRED_COPY3]], [[PRED_COPY4]], implicit-def $scc, implicit $scc
    ; GFX6-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:sreg_64_xexec = REG_SEQUENCE [[S_ADD_U32_]], %subreg.sub0, [[S_ADDC_U32_]], %subreg.sub1
    ; GFX6-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[REG_SEQUENCE1]], 0, 0 :: (load (s32), addrspace 4)
    ; GFX6-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX7-LABEL: name: load_constant_s32_from_4_gep_negative_524288
    ; GFX7: liveins: $sgpr0_sgpr1
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX7-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 4294443008
    ; GFX7-NEXT: [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
    ; GFX7-NEXT: [[REG_SEQUENCE:%[0-9]+]]:sreg_64 = REG_SEQUENCE [[S_MOV_B32_]], %subreg.sub0, [[S_MOV_B32_1]], %subreg.sub1
    ; GFX7-NEXT: [[PRED_COPY1:%[0-9]+]]:sreg_32 = PRED_COPY [[PRED_COPY]].sub0
    ; GFX7-NEXT: [[PRED_COPY2:%[0-9]+]]:sreg_32 = PRED_COPY [[REG_SEQUENCE]].sub0
    ; GFX7-NEXT: [[PRED_COPY3:%[0-9]+]]:sreg_32 = PRED_COPY [[PRED_COPY]].sub1
    ; GFX7-NEXT: [[PRED_COPY4:%[0-9]+]]:sreg_32 = PRED_COPY [[REG_SEQUENCE]].sub1
    ; GFX7-NEXT: [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PRED_COPY1]], [[PRED_COPY2]], implicit-def $scc
    ; GFX7-NEXT: [[S_ADDC_U32_:%[0-9]+]]:sreg_32 = S_ADDC_U32 [[PRED_COPY3]], [[PRED_COPY4]], implicit-def $scc, implicit $scc
    ; GFX7-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:sreg_64_xexec = REG_SEQUENCE [[S_ADD_U32_]], %subreg.sub0, [[S_ADDC_U32_]], %subreg.sub1
    ; GFX7-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[REG_SEQUENCE1]], 0, 0 :: (load (s32), addrspace 4)
    ; GFX7-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX8-LABEL: name: load_constant_s32_from_4_gep_negative_524288
    ; GFX8: liveins: $sgpr0_sgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX8-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 4294443008
    ; GFX8-NEXT: [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
    ; GFX8-NEXT: [[REG_SEQUENCE:%[0-9]+]]:sreg_64 = REG_SEQUENCE [[S_MOV_B32_]], %subreg.sub0, [[S_MOV_B32_1]], %subreg.sub1
    ; GFX8-NEXT: [[PRED_COPY1:%[0-9]+]]:sreg_32 = PRED_COPY [[PRED_COPY]].sub0
    ; GFX8-NEXT: [[PRED_COPY2:%[0-9]+]]:sreg_32 = PRED_COPY [[REG_SEQUENCE]].sub0
    ; GFX8-NEXT: [[PRED_COPY3:%[0-9]+]]:sreg_32 = PRED_COPY [[PRED_COPY]].sub1
    ; GFX8-NEXT: [[PRED_COPY4:%[0-9]+]]:sreg_32 = PRED_COPY [[REG_SEQUENCE]].sub1
    ; GFX8-NEXT: [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PRED_COPY1]], [[PRED_COPY2]], implicit-def $scc
    ; GFX8-NEXT: [[S_ADDC_U32_:%[0-9]+]]:sreg_32 = S_ADDC_U32 [[PRED_COPY3]], [[PRED_COPY4]], implicit-def $scc, implicit $scc
    ; GFX8-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:sreg_64_xexec = REG_SEQUENCE [[S_ADD_U32_]], %subreg.sub0, [[S_ADDC_U32_]], %subreg.sub1
    ; GFX8-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[REG_SEQUENCE1]], 0, 0 :: (load (s32), addrspace 4)
    ; GFX8-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    ; GFX10-LABEL: name: load_constant_s32_from_4_gep_negative_524288
    ; GFX10: liveins: $sgpr0_sgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr0_sgpr1
    ; GFX10-NEXT: [[S_LOAD_DWORD_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_LOAD_DWORD_IMM [[PRED_COPY]], -524288, 0 :: (load (s32), addrspace 4)
    ; GFX10-NEXT: $sgpr0 = PRED_COPY [[S_LOAD_DWORD_IMM]]
    %0:sgpr(p4) = COPY $sgpr0_sgpr1
    %1:sgpr(s64) = G_CONSTANT i64 -524288
    %2:sgpr(p4) = G_PTR_ADD %0, %1
    %3:sgpr(s32) = G_LOAD %2 :: (load (s32), align 4, addrspace 4)
    $sgpr0 = COPY %3

...
