# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=amdgcn -mcpu=fiji -run-pass=instruction-select -global-isel-abort=0 -verify-machineinstrs -o - %s | FileCheck -check-prefix=GCN %s

---
name: frint_s16_ss
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins: $sgpr0

    ; GCN-LABEL: name: frint_s16_ss
    ; GCN: liveins: $sgpr0
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: [[COPY:%[0-9]+]]:sgpr(s32) = COPY $sgpr0
    ; GCN-NEXT: [[TRUNC:%[0-9]+]]:sgpr(s16) = G_TRUNC [[COPY]](s32)
    ; GCN-NEXT: [[FRINT:%[0-9]+]]:sreg_32(s16) = G_FRINT [[TRUNC]]
    ; GCN-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32(s32) = PRED_COPY [[FRINT]](s16)
    ; GCN-NEXT: $sgpr0 = PRED_COPY [[PRED_COPY]](s32)
    %0:sgpr(s32) = COPY $sgpr0
    %1:sgpr(s16) = G_TRUNC %0
    %2:sgpr(s16) = G_FRINT %1
    %3:sgpr(s32) = G_ANYEXT %2
    $sgpr0 = COPY %3
...

---
name: frint_s16_vv
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins: $vgpr0

    ; GCN-LABEL: name: frint_s16_vv
    ; GCN: liveins: $vgpr0
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GCN-NEXT: [[V_RNDNE_F16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_RNDNE_F16_e64 0, [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; GCN-NEXT: $vgpr0 = PRED_COPY [[V_RNDNE_F16_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s16) = G_TRUNC %0
    %2:vgpr(s16) = G_FRINT %1
    %3:vgpr(s32) = G_ANYEXT %2
    $vgpr0 = COPY %3
...

---
name: frint_s16_vs
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins: $sgpr0

    ; GCN-LABEL: name: frint_s16_vs
    ; GCN: liveins: $sgpr0
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; GCN-NEXT: [[V_RNDNE_F16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_RNDNE_F16_e64 0, [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; GCN-NEXT: $vgpr0 = PRED_COPY [[V_RNDNE_F16_e64_]]
    %0:sgpr(s32) = COPY $sgpr0
    %1:sgpr(s16) = G_TRUNC %0
    %2:vgpr(s16) = G_FRINT %1
    %3:vgpr(s32) = G_ANYEXT %2
    $vgpr0 = COPY %3
...

---
name: frint_fneg_s16_vv
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins: $vgpr0

    ; GCN-LABEL: name: frint_fneg_s16_vv
    ; GCN: liveins: $vgpr0
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GCN-NEXT: [[V_RNDNE_F16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_RNDNE_F16_e64 1, [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; GCN-NEXT: $vgpr0 = PRED_COPY [[V_RNDNE_F16_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s16) = G_TRUNC %0
    %2:vgpr(s16) = G_FNEG %1
    %3:vgpr(s16) = G_FRINT %2
    %4:vgpr(s32) = G_ANYEXT %3
    $vgpr0 = COPY %4
...
