# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-mesa-mesa3d -mcpu=tahiti -run-pass=instruction-select %s -o - | FileCheck -check-prefix=GFX6 %s
# RUN: llc -mtriple=amdgcn-mesa-mesa3d -mcpu=fiji -run-pass=instruction-select %s -o - | FileCheck -check-prefix=GFX6 %s
# RUN: llc -march=amdgcn -mcpu=gfx1010 -run-pass=instruction-select %s -o - |  FileCheck -check-prefix=GFX10 %s
# RUN: llc -march=amdgcn -mcpu=gfx1100 -run-pass=instruction-select %s -o - |  FileCheck -check-prefix=GFX10 %s

---
name:            test_freeze_s1_vgpr_to_vgpr
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX6-LABEL: name: test_freeze_s1_vgpr_to_vgpr
    ; GFX6: liveins: $vgpr0
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX6-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_s1_vgpr_to_vgpr
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX10-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s1) = G_TRUNC %0(s32)
    %2:vgpr(s1) = G_FREEZE %1
    %3:vgpr(s32) = G_ANYEXT %2(s1)
    $vgpr0 = COPY %3(s32)

...

---
name:            test_freeze_s1_vgpr_to_agpr
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX6-LABEL: name: test_freeze_s1_vgpr_to_agpr
    ; GFX6: liveins: $vgpr0
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX6-NEXT: $agpr0 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_s1_vgpr_to_agpr
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX10-NEXT: $agpr0 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s1) = G_TRUNC %0(s32)
    %2:vgpr(s1) = G_FREEZE %1
    %3:vgpr(s32) = G_ANYEXT %2(s1)
    $agpr0 = COPY %3(s32)

...

---
name:            test_freeze_s1_vcc
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0, $vgpr1
    ; GFX6-LABEL: name: test_freeze_s1_vcc
    ; GFX6: liveins: $vgpr0, $vgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX6-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; GFX6-NEXT: [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_64 = V_CMP_EQ_U32_e64 [[PRED_COPY]], [[PRED_COPY1]], implicit $exec
    ; GFX6-NEXT: [[PRED_COPY2:%[0-9]+]]:sreg_64_xexec = PRED_COPY [[V_CMP_EQ_U32_e64_]]
    ; GFX6-NEXT: S_ENDPGM 0, implicit [[PRED_COPY2]]
    ; GFX10-LABEL: name: test_freeze_s1_vcc
    ; GFX10: liveins: $vgpr0, $vgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX10-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; GFX10-NEXT: [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 [[PRED_COPY]], [[PRED_COPY1]], implicit $exec
    ; GFX10-NEXT: [[PRED_COPY2:%[0-9]+]]:sreg_32_xm0_xexec = PRED_COPY [[V_CMP_EQ_U32_e64_]]
    ; GFX10-NEXT: S_ENDPGM 0, implicit [[PRED_COPY2]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vcc(s1) = G_ICMP intpred(eq), %0(s32), %1
    %3:vcc(s1) = G_FREEZE %2
    S_ENDPGM 0, implicit %3(s1)

...

---
name:            test_freeze_s16_vgpr_to_vgpr
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX6-LABEL: name: test_freeze_s16_vgpr_to_vgpr
    ; GFX6: liveins: $vgpr0
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX6-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_s16_vgpr_to_vgpr
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX10-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s16) = G_TRUNC %0(s32)
    %2:vgpr(s16) = G_FREEZE %1
    %3:vgpr(s32) = G_ANYEXT %2(s16)
    $vgpr0 = COPY %3(s32)

...

---
name:            test_freeze_s32_vgpr_to_vgpr
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX6-LABEL: name: test_freeze_s32_vgpr_to_vgpr
    ; GFX6: liveins: $vgpr0
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX6-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_s32_vgpr_to_vgpr
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX10-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = G_FREEZE %0
    $vgpr0 = COPY %1(s32)

...

---
name:            test_freeze_s32_sgpr_to_sgpr
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $sgpr0
    ; GFX6-LABEL: name: test_freeze_s32_sgpr_to_sgpr
    ; GFX6: liveins: $sgpr0
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; GFX6-NEXT: $sgpr0 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_s32_sgpr_to_sgpr
    ; GFX10: liveins: $sgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; GFX10-NEXT: $sgpr0 = PRED_COPY [[PRED_COPY]]
    %0:sgpr(s32) = COPY $sgpr0
    %1:sgpr(s32) = G_FREEZE %0
    $sgpr0 = COPY %1(s32)

...

---
name:            test_freeze_s32_sgpr_to_vgpr
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $sgpr0
    ; GFX6-LABEL: name: test_freeze_s32_sgpr_to_vgpr
    ; GFX6: liveins: $sgpr0
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; GFX6-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_s32_sgpr_to_vgpr
    ; GFX10: liveins: $sgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; GFX10-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    %0:sgpr(s32) = COPY $sgpr0
    %1:sgpr(s32) = G_FREEZE %0
    $vgpr0 = COPY %1(s32)

...

---
name:            test_freeze_s32_vgpr_to_agpr
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX6-LABEL: name: test_freeze_s32_vgpr_to_agpr
    ; GFX6: liveins: $vgpr0
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX6-NEXT: $agpr0 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_s32_vgpr_to_agpr
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX10-NEXT: $agpr0 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = G_FREEZE %0
    $agpr0 = COPY %1(s32)

...

---
name:            test_freeze_s32_sgpr_to_agpr
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $sgpr0
    ; GFX6-LABEL: name: test_freeze_s32_sgpr_to_agpr
    ; GFX6: liveins: $sgpr0
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; GFX6-NEXT: $agpr0 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_s32_sgpr_to_agpr
    ; GFX10: liveins: $sgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; GFX10-NEXT: $agpr0 = PRED_COPY [[PRED_COPY]]
    %0:sgpr(s32) = COPY $sgpr0
    %1:sgpr(s32) = G_FREEZE %0
    $agpr0 = COPY %1(s32)

...

---
name:            test_freeze_s32_agpr_to_vgpr
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $agpr0
    ; GFX6-LABEL: name: test_freeze_s32_agpr_to_vgpr
    ; GFX6: liveins: $agpr0
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:agpr_32 = PRED_COPY $agpr0
    ; GFX6-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_s32_agpr_to_vgpr
    ; GFX10: liveins: $agpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:agpr_32 = PRED_COPY $agpr0
    ; GFX10-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    %0:agpr(s32) = COPY $agpr0
    %1:agpr(s32) = G_FREEZE %0
    $vgpr0 = COPY %1(s32)

...

---
name:            test_freeze_s32_agpr_to_agpr
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $agpr0
    ; GFX6-LABEL: name: test_freeze_s32_agpr_to_agpr
    ; GFX6: liveins: $agpr0
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:agpr_32 = PRED_COPY $agpr0
    ; GFX6-NEXT: $agpr0 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_s32_agpr_to_agpr
    ; GFX10: liveins: $agpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:agpr_32 = PRED_COPY $agpr0
    ; GFX10-NEXT: $agpr0 = PRED_COPY [[PRED_COPY]]
    %0:agpr(s32) = COPY $agpr0
    %1:agpr(s32) = G_FREEZE %0
    $agpr0 = COPY %1(s32)

...

---
name:            test_freeze_s64
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1
    ; GFX6-LABEL: name: test_freeze_s64
    ; GFX6: liveins: $vgpr0_vgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GFX6-NEXT: $vgpr0_vgpr1 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_s64
    ; GFX10: liveins: $vgpr0_vgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GFX10-NEXT: $vgpr0_vgpr1 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(s64) = COPY $vgpr0_vgpr1
    %1:vgpr(s64) = G_FREEZE %0
    $vgpr0_vgpr1 = COPY %1(s64)

...

---
name:            test_freeze_s128
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX6-LABEL: name: test_freeze_s128
    ; GFX6: liveins: $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_128 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX6-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_s128
    ; GFX10: liveins: $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_128 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX10-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(s128) = COPY $vgpr0_vgpr1_vgpr2_vgpr3
    %1:vgpr(s128) = G_FREEZE %0
    $vgpr0_vgpr1_vgpr2_vgpr3 = COPY %1(s128)

...

---
name:            test_freeze_256
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX6-LABEL: name: test_freeze_256
    ; GFX6: liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_256 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX6-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_256
    ; GFX10: liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_256 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX10-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(s256) = COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
    %1:vgpr(s256) = G_FREEZE %0
    $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7 = COPY %1(s256)

...

---
name:            test_freeze_s512
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
    ; GFX6-LABEL: name: test_freeze_s512
    ; GFX6: liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_512 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
    ; GFX6-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_s512
    ; GFX10: liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_512 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
    ; GFX10-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(s512) = COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
    %1:vgpr(s512) = G_FREEZE %0
    $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15 = COPY %1(s512)

...

---
name:            test_freeze_v2s32
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1
    ; GFX6-LABEL: name: test_freeze_v2s32
    ; GFX6: liveins: $vgpr0_vgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GFX6-NEXT: $vgpr0_vgpr1 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_v2s32
    ; GFX10: liveins: $vgpr0_vgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GFX10-NEXT: $vgpr0_vgpr1 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(<2 x s32>) = COPY $vgpr0_vgpr1
    %1:vgpr(<2 x s32>) = G_FREEZE %0
    $vgpr0_vgpr1 = COPY %1(<2 x s32>)

...

---
name:            test_freeze_v3s32
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2
    ; GFX6-LABEL: name: test_freeze_v3s32
    ; GFX6: liveins: $vgpr0_vgpr1_vgpr2
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_96 = PRED_COPY $vgpr0_vgpr1_vgpr2
    ; GFX6-NEXT: $vgpr0_vgpr1_vgpr2 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_v3s32
    ; GFX10: liveins: $vgpr0_vgpr1_vgpr2
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_96 = PRED_COPY $vgpr0_vgpr1_vgpr2
    ; GFX10-NEXT: $vgpr0_vgpr1_vgpr2 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(<3 x s32>) = COPY $vgpr0_vgpr1_vgpr2
    %1:vgpr(<3 x s32>) = G_FREEZE %0
    $vgpr0_vgpr1_vgpr2 = COPY %1(<3 x s32>)

...

---
name:            test_freeze_v4s32
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX6-LABEL: name: test_freeze_v4s32
    ; GFX6: liveins: $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_128 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX6-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_v4s32
    ; GFX10: liveins: $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_128 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX10-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(<4 x s32>) = COPY $vgpr0_vgpr1_vgpr2_vgpr3
    %1:vgpr(<4 x s32>) = G_FREEZE %0
    $vgpr0_vgpr1_vgpr2_vgpr3 = COPY %1(<4 x s32>)

...

---
name:            test_freeze_v5s32
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4
    ; GFX6-LABEL: name: test_freeze_v5s32
    ; GFX6: liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_160 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4
    ; GFX6-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_v5s32
    ; GFX10: liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_160 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4
    ; GFX10-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(<5 x s32>) = COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4
    %1:vgpr(<5 x s32>) = G_FREEZE %0
    $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4 = COPY %1(<5 x s32>)

...

---
name:            test_freeze_v8s32
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX6-LABEL: name: test_freeze_v8s32
    ; GFX6: liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_256 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX6-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_v8s32
    ; GFX10: liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_256 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX10-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(<8 x s32>) = COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
    %1:vgpr(<8 x s32>) = G_FREEZE %0
    $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7 = COPY %1(<8 x s32>)

...

---
name:            test_freeze_v16s32
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
    ; GFX6-LABEL: name: test_freeze_v16s32
    ; GFX6: liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_512 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
    ; GFX6-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_v16s32
    ; GFX10: liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_512 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
    ; GFX10-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(<16 x s32>) = COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
    %1:vgpr(<16 x s32>) = G_FREEZE %0
    $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15 = COPY %1(<16 x s32>)

...

---
name:            test_freeze_v2s16
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX6-LABEL: name: test_freeze_v2s16
    ; GFX6: liveins: $vgpr0
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX6-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_v2s16
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX10-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(<2 x s16>) = COPY $vgpr0
    %1:vgpr(<2 x s16>) = G_FREEZE %0
    $vgpr0 = COPY %1(<2 x s16>)

...

---
name:            test_freeze_v4s16
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1
    ; GFX6-LABEL: name: test_freeze_v4s16
    ; GFX6: liveins: $vgpr0_vgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GFX6-NEXT: $vgpr0_vgpr1 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_v4s16
    ; GFX10: liveins: $vgpr0_vgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GFX10-NEXT: $vgpr0_vgpr1 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(<4 x s16>) = COPY $vgpr0_vgpr1
    %1:vgpr(<4 x s16>) = G_FREEZE %0
    $vgpr0_vgpr1 = COPY %1(<4 x s16>)

...

---
name:            test_freeze_v6s16
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2
    ; GFX6-LABEL: name: test_freeze_v6s16
    ; GFX6: liveins: $vgpr0_vgpr1_vgpr2
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_96 = PRED_COPY $vgpr0_vgpr1_vgpr2
    ; GFX6-NEXT: $vgpr0_vgpr1_vgpr2 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_v6s16
    ; GFX10: liveins: $vgpr0_vgpr1_vgpr2
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_96 = PRED_COPY $vgpr0_vgpr1_vgpr2
    ; GFX10-NEXT: $vgpr0_vgpr1_vgpr2 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(<6 x s16>) = COPY $vgpr0_vgpr1_vgpr2
    %1:vgpr(<6 x s16>) = G_FREEZE %0
    $vgpr0_vgpr1_vgpr2 = COPY %1(<6 x s16>)

...

---
name:            test_freeze_v8s16
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX6-LABEL: name: test_freeze_v8s16
    ; GFX6: liveins: $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_128 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX6-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_v8s16
    ; GFX10: liveins: $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_128 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX10-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(<8 x s16>) = COPY $vgpr0_vgpr1_vgpr2_vgpr3
    %1:vgpr(<8 x s16>) = G_FREEZE %0
    $vgpr0_vgpr1_vgpr2_vgpr3 = COPY %1(<8 x s16>)

...

---
name:            test_freeze_v2s64
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX6-LABEL: name: test_freeze_v2s64
    ; GFX6: liveins: $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_128 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX6-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_v2s64
    ; GFX10: liveins: $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_128 = PRED_COPY $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX10-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(<2 x s64>) = COPY $vgpr0_vgpr1_vgpr2_vgpr3
    %1:vgpr(<2 x s64>) = G_FREEZE %0
    $vgpr0_vgpr1_vgpr2_vgpr3 = COPY %1(<2 x s64>)

...

---
name:            test_freeze_p0
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1
    ; GFX6-LABEL: name: test_freeze_p0
    ; GFX6: liveins: $vgpr0_vgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GFX6-NEXT: $vgpr0_vgpr1 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_p0
    ; GFX10: liveins: $vgpr0_vgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GFX10-NEXT: $vgpr0_vgpr1 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(p0) = COPY $vgpr0_vgpr1
    %1:vgpr(p0) = G_FREEZE %0
    $vgpr0_vgpr1 = COPY %1(p0)

...

---
name:            test_freeze_p1
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1
    ; GFX6-LABEL: name: test_freeze_p1
    ; GFX6: liveins: $vgpr0_vgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GFX6-NEXT: $vgpr0_vgpr1 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_p1
    ; GFX10: liveins: $vgpr0_vgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GFX10-NEXT: $vgpr0_vgpr1 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(p1) = COPY $vgpr0_vgpr1
    %1:vgpr(p1) = G_FREEZE %0
    $vgpr0_vgpr1 = COPY %1(p1)

...

---
name:            test_freeze_p2
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX6-LABEL: name: test_freeze_p2
    ; GFX6: liveins: $vgpr0
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX6-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_p2
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX10-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(p2) = COPY $vgpr0
    %1:vgpr(p2) = G_FREEZE %0
    $vgpr0 = COPY %1(p2)

...

---
name:            test_freeze_p3
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX6-LABEL: name: test_freeze_p3
    ; GFX6: liveins: $vgpr0
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX6-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_p3
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX10-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(p3) = COPY $vgpr0
    %1:vgpr(p3) = G_FREEZE %0
    $vgpr0 = COPY %1(p3)

...

---
name:            test_freeze_p4
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1
    ; GFX6-LABEL: name: test_freeze_p4
    ; GFX6: liveins: $vgpr0_vgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GFX6-NEXT: $vgpr0_vgpr1 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_p4
    ; GFX10: liveins: $vgpr0_vgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GFX10-NEXT: $vgpr0_vgpr1 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(p4) = COPY $vgpr0_vgpr1
    %1:vgpr(p4) = G_FREEZE %0
    $vgpr0_vgpr1 = COPY %1(p4)

...

---
name:            test_freeze_p5
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX6-LABEL: name: test_freeze_p5
    ; GFX6: liveins: $vgpr0
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX6-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_p5
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX10-NEXT: $vgpr0 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(p5) = COPY $vgpr0
    %1:vgpr(p5) = G_FREEZE %0
    $vgpr0 = COPY %1(p5)

...

---
name:            test_freeze_p999
alignment:       1
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1
    ; GFX6-LABEL: name: test_freeze_p999
    ; GFX6: liveins: $vgpr0_vgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GFX6-NEXT: $vgpr0_vgpr1 = PRED_COPY [[PRED_COPY]]
    ; GFX10-LABEL: name: test_freeze_p999
    ; GFX10: liveins: $vgpr0_vgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GFX10-NEXT: $vgpr0_vgpr1 = PRED_COPY [[PRED_COPY]]
    %0:vgpr(p999) = COPY $vgpr0_vgpr1
    %1:vgpr(p999) = G_FREEZE %0
    $vgpr0_vgpr1 = COPY %1(p999)

...
