# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=amdgcn -mcpu=hawaii -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck -check-prefix=WAVE64 %s
# RUN: llc -march=amdgcn -mcpu=gfx1010 -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck -check-prefix=WAVE32 %s
# RUN: llc -march=amdgcn -mcpu=gfx1100 -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck -check-prefix=GFX11 %s

---
name: uitofp_s32_to_s32_vv
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins: $vgpr0

    ; WAVE64-LABEL: name: uitofp_s32_to_s32_vv
    ; WAVE64: liveins: $vgpr0
    ; WAVE64-NEXT: {{  $}}
    ; WAVE64-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; WAVE64-NEXT: [[V_CVT_F32_U32_e64_:%[0-9]+]]:vgpr_32 = V_CVT_F32_U32_e64 [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; WAVE64-NEXT: $vgpr0 = PRED_COPY [[V_CVT_F32_U32_e64_]]
    ; WAVE32-LABEL: name: uitofp_s32_to_s32_vv
    ; WAVE32: liveins: $vgpr0
    ; WAVE32-NEXT: {{  $}}
    ; WAVE32-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; WAVE32-NEXT: [[V_CVT_F32_U32_e64_:%[0-9]+]]:vgpr_32 = V_CVT_F32_U32_e64 [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; WAVE32-NEXT: $vgpr0 = PRED_COPY [[V_CVT_F32_U32_e64_]]
    ; GFX11-LABEL: name: uitofp_s32_to_s32_vv
    ; GFX11: liveins: $vgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX11-NEXT: [[V_CVT_F32_U32_e64_:%[0-9]+]]:vgpr_32 = V_CVT_F32_U32_e64 [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: $vgpr0 = PRED_COPY [[V_CVT_F32_U32_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = G_UITOFP %0
    $vgpr0 = COPY %1
...

---
name: uitofp_s32_to_s32_vs
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins: $sgpr0

    ; WAVE64-LABEL: name: uitofp_s32_to_s32_vs
    ; WAVE64: liveins: $sgpr0
    ; WAVE64-NEXT: {{  $}}
    ; WAVE64-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; WAVE64-NEXT: [[V_CVT_F32_U32_e64_:%[0-9]+]]:vgpr_32 = V_CVT_F32_U32_e64 [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; WAVE64-NEXT: $vgpr0 = PRED_COPY [[V_CVT_F32_U32_e64_]]
    ; WAVE32-LABEL: name: uitofp_s32_to_s32_vs
    ; WAVE32: liveins: $sgpr0
    ; WAVE32-NEXT: {{  $}}
    ; WAVE32-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; WAVE32-NEXT: [[V_CVT_F32_U32_e64_:%[0-9]+]]:vgpr_32 = V_CVT_F32_U32_e64 [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; WAVE32-NEXT: $vgpr0 = PRED_COPY [[V_CVT_F32_U32_e64_]]
    ; GFX11-LABEL: name: uitofp_s32_to_s32_vs
    ; GFX11: liveins: $sgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; GFX11-NEXT: [[V_CVT_F32_U32_e64_:%[0-9]+]]:vgpr_32 = V_CVT_F32_U32_e64 [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: $vgpr0 = PRED_COPY [[V_CVT_F32_U32_e64_]]
    %0:sgpr(s32) = COPY $sgpr0
    %1:vgpr(s32) = G_UITOFP %0
    $vgpr0 = COPY %1
...

---
name: uitofp_s32_to_s16_vv
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins: $vgpr0

    ; WAVE64-LABEL: name: uitofp_s32_to_s16_vv
    ; WAVE64: liveins: $vgpr0
    ; WAVE64-NEXT: {{  $}}
    ; WAVE64-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; WAVE64-NEXT: [[V_CVT_F32_U32_e32_:%[0-9]+]]:vgpr_32 = V_CVT_F32_U32_e32 [[PRED_COPY]], implicit $mode, implicit $exec
    ; WAVE64-NEXT: [[V_CVT_F16_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_CVT_F16_F32_e64 0, [[V_CVT_F32_U32_e32_]], 0, 0, implicit $mode, implicit $exec
    ; WAVE64-NEXT: $vgpr0 = PRED_COPY [[V_CVT_F16_F32_e64_]]
    ; WAVE32-LABEL: name: uitofp_s32_to_s16_vv
    ; WAVE32: liveins: $vgpr0
    ; WAVE32-NEXT: {{  $}}
    ; WAVE32-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; WAVE32-NEXT: [[V_CVT_F32_U32_e32_:%[0-9]+]]:vgpr_32 = V_CVT_F32_U32_e32 [[PRED_COPY]], implicit $mode, implicit $exec
    ; WAVE32-NEXT: [[V_CVT_F16_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_CVT_F16_F32_e64 0, [[V_CVT_F32_U32_e32_]], 0, 0, implicit $mode, implicit $exec
    ; WAVE32-NEXT: $vgpr0 = PRED_COPY [[V_CVT_F16_F32_e64_]]
    ; GFX11-LABEL: name: uitofp_s32_to_s16_vv
    ; GFX11: liveins: $vgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX11-NEXT: [[V_CVT_F32_U32_e32_:%[0-9]+]]:vgpr_32 = V_CVT_F32_U32_e32 [[PRED_COPY]], implicit $mode, implicit $exec
    ; GFX11-NEXT: [[V_CVT_F16_F32_t16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_CVT_F16_F32_t16_e64 0, [[V_CVT_F32_U32_e32_]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: $vgpr0 = PRED_COPY [[V_CVT_F16_F32_t16_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s16) = G_UITOFP %0
    %2:vgpr(s32) = G_ANYEXT %1
    $vgpr0 = COPY %2
...

---
name: uitofp_s32_to_s16_vs
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins: $sgpr0

    ; WAVE64-LABEL: name: uitofp_s32_to_s16_vs
    ; WAVE64: liveins: $sgpr0
    ; WAVE64-NEXT: {{  $}}
    ; WAVE64-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; WAVE64-NEXT: [[V_CVT_F32_U32_e32_:%[0-9]+]]:vgpr_32 = V_CVT_F32_U32_e32 [[PRED_COPY]], implicit $mode, implicit $exec
    ; WAVE64-NEXT: [[V_CVT_F16_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_CVT_F16_F32_e64 0, [[V_CVT_F32_U32_e32_]], 0, 0, implicit $mode, implicit $exec
    ; WAVE64-NEXT: $vgpr0 = PRED_COPY [[V_CVT_F16_F32_e64_]]
    ; WAVE32-LABEL: name: uitofp_s32_to_s16_vs
    ; WAVE32: liveins: $sgpr0
    ; WAVE32-NEXT: {{  $}}
    ; WAVE32-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; WAVE32-NEXT: [[V_CVT_F32_U32_e32_:%[0-9]+]]:vgpr_32 = V_CVT_F32_U32_e32 [[PRED_COPY]], implicit $mode, implicit $exec
    ; WAVE32-NEXT: [[V_CVT_F16_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_CVT_F16_F32_e64 0, [[V_CVT_F32_U32_e32_]], 0, 0, implicit $mode, implicit $exec
    ; WAVE32-NEXT: $vgpr0 = PRED_COPY [[V_CVT_F16_F32_e64_]]
    ; GFX11-LABEL: name: uitofp_s32_to_s16_vs
    ; GFX11: liveins: $sgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; GFX11-NEXT: [[V_CVT_F32_U32_e32_:%[0-9]+]]:vgpr_32 = V_CVT_F32_U32_e32 [[PRED_COPY]], implicit $mode, implicit $exec
    ; GFX11-NEXT: [[V_CVT_F16_F32_t16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_CVT_F16_F32_t16_e64 0, [[V_CVT_F32_U32_e32_]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: $vgpr0 = PRED_COPY [[V_CVT_F16_F32_t16_e64_]]
    %0:sgpr(s32) = COPY $sgpr0
    %1:vgpr(s16) = G_UITOFP %0
    %2:vgpr(s32) = G_ANYEXT %1
    $vgpr0 = COPY %2
...
