# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=amdgcn -mcpu=bonaire -run-pass=instruction-select -verify-machineinstrs -o - %s | FileCheck -check-prefix=GCN %s
# RUN: llc -march=amdgcn -mcpu=fiji -run-pass=instruction-select -verify-machineinstrs -o - %s | FileCheck -check-prefix=GCN %s

---
name: frint_s32_vv
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins: $vgpr0

    ; GCN-LABEL: name: frint_s32_vv
    ; GCN: liveins: $vgpr0
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GCN-NEXT: [[V_RNDNE_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_RNDNE_F32_e64 0, [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; GCN-NEXT: $vgpr0 = PRED_COPY [[V_RNDNE_F32_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = G_FRINT %0
    $vgpr0 = COPY %1
...

---
name: frint_s32_vs
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins: $sgpr0

    ; GCN-LABEL: name: frint_s32_vs
    ; GCN: liveins: $sgpr0
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; GCN-NEXT: [[V_RNDNE_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_RNDNE_F32_e64 0, [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; GCN-NEXT: $vgpr0 = PRED_COPY [[V_RNDNE_F32_e64_]]
    %0:sgpr(s32) = COPY $sgpr0
    %1:vgpr(s32) = G_FRINT %0
    $vgpr0 = COPY %1
...

---
name: frint_fneg_s32_vv
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins: $vgpr0

    ; GCN-LABEL: name: frint_fneg_s32_vv
    ; GCN: liveins: $vgpr0
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GCN-NEXT: [[V_RNDNE_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_RNDNE_F32_e64 1, [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; GCN-NEXT: $vgpr0 = PRED_COPY [[V_RNDNE_F32_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = G_FNEG %0
    %2:vgpr(s32) = G_FRINT %1
    $vgpr0 = COPY %2
...

---
name: frint_s64_vv
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1

    ; GCN-LABEL: name: frint_s64_vv
    ; GCN: liveins: $vgpr0_vgpr1
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GCN-NEXT: [[V_RNDNE_F64_e64_:%[0-9]+]]:vreg_64 = nofpexcept V_RNDNE_F64_e64 0, [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; GCN-NEXT: $vgpr0_vgpr1 = PRED_COPY [[V_RNDNE_F64_e64_]]
    %0:vgpr(s64) = COPY $vgpr0_vgpr1
    %1:vgpr(s64) = G_FRINT %0
    $vgpr0_vgpr1 = COPY %1
...

---
name: frint_s64_fneg_vv
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1

    ; GCN-LABEL: name: frint_s64_fneg_vv
    ; GCN: liveins: $vgpr0_vgpr1
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: [[PRED_COPY:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr0_vgpr1
    ; GCN-NEXT: [[V_RNDNE_F64_e64_:%[0-9]+]]:vreg_64 = nofpexcept V_RNDNE_F64_e64 1, [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; GCN-NEXT: $vgpr0_vgpr1 = PRED_COPY [[V_RNDNE_F64_e64_]]
    %0:vgpr(s64) = COPY $vgpr0_vgpr1
    %1:vgpr(s64) = G_FNEG %0
    %2:vgpr(s64) = G_FRINT %1
    $vgpr0_vgpr1 = COPY %2
...
