# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=hawaii -run-pass=instruction-select -verify-machineinstrs -o - %s  | FileCheck -check-prefix=GFX7 %s

# FIXME: Ideally this would fail to select with ieee mode enabled.
---

name: fmaxnum_f32_f64_ieee_mode_on
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    ieee: true

body: |
  bb.0:
    liveins: $sgpr0, $vgpr0, $vgpr1, $vgpr3_vgpr4, $sgpr10_sgpr11, $vgpr10_vgpr11, $vgpr12_vgpr13
    ; GFX7-LABEL: name: fmaxnum_f32_f64_ieee_mode_on
    ; GFX7: liveins: $sgpr0, $vgpr0, $vgpr1, $vgpr3_vgpr4, $sgpr10_sgpr11, $vgpr10_vgpr11, $vgpr12_vgpr13
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; GFX7-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX7-NEXT: [[PRED_COPY2:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; GFX7-NEXT: [[PRED_COPY3:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr3_vgpr4
    ; GFX7-NEXT: [[PRED_COPY4:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr10_sgpr11
    ; GFX7-NEXT: [[PRED_COPY5:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr10_vgpr11
    ; GFX7-NEXT: [[PRED_COPY6:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr12_vgpr13
    ; GFX7-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 0, [[PRED_COPY1]], 0, [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX7-NEXT: [[V_MAX_F32_e64_1:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 0, [[PRED_COPY]], 0, [[PRED_COPY1]], 0, 0, implicit $mode, implicit $exec
    ; GFX7-NEXT: [[V_MAX_F32_e64_2:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 0, [[PRED_COPY1]], 0, [[PRED_COPY2]], 0, 0, implicit $mode, implicit $exec
    ; GFX7-NEXT: FLAT_STORE_DWORD [[PRED_COPY3]], [[V_MAX_F32_e64_]], 0, 0, implicit $exec, implicit $flat_scr :: (store (s32), addrspace 1)
    ; GFX7-NEXT: FLAT_STORE_DWORD [[PRED_COPY3]], [[V_MAX_F32_e64_1]], 0, 0, implicit $exec, implicit $flat_scr :: (store (s32), addrspace 1)
    ; GFX7-NEXT: FLAT_STORE_DWORD [[PRED_COPY3]], [[V_MAX_F32_e64_2]], 0, 0, implicit $exec, implicit $flat_scr :: (store (s32), addrspace 1)
    ; GFX7-NEXT: [[V_MAX_F64_e64_:%[0-9]+]]:vreg_64 = nofpexcept V_MAX_F64_e64 0, [[PRED_COPY4]], 0, [[PRED_COPY5]], 0, 0, implicit $mode, implicit $exec
    ; GFX7-NEXT: [[V_MAX_F64_e64_1:%[0-9]+]]:vreg_64 = nofpexcept V_MAX_F64_e64 0, [[PRED_COPY5]], 0, [[PRED_COPY4]], 0, 0, implicit $mode, implicit $exec
    ; GFX7-NEXT: [[V_MAX_F64_e64_2:%[0-9]+]]:vreg_64 = nofpexcept V_MAX_F64_e64 0, [[PRED_COPY5]], 0, [[PRED_COPY6]], 0, 0, implicit $mode, implicit $exec
    ; GFX7-NEXT: S_ENDPGM 0, implicit [[V_MAX_F64_e64_]], implicit [[V_MAX_F64_e64_1]], implicit [[V_MAX_F64_e64_2]]
    %0:sgpr(s32) = COPY $sgpr0
    %1:vgpr(s32) = COPY $vgpr0
    %2:vgpr(s32) = COPY $vgpr1
    %3:vgpr(p1) = COPY $vgpr3_vgpr4

    %10:sgpr(s64) = COPY $sgpr10_sgpr11
    %11:vgpr(s64) = COPY $vgpr10_vgpr11
    %12:vgpr(s64) = COPY $vgpr12_vgpr13

    ; maxnum vs
    %4:vgpr(s32) = G_FMAXNUM %1, %0

    ; maxnum sv
    %5:vgpr(s32) = G_FMAXNUM %0, %1

    ; maxnum vv
    %6:vgpr(s32) = G_FMAXNUM %1, %2

    G_STORE %4, %3 :: (store (s32), addrspace 1)
    G_STORE %5, %3 :: (store (s32), addrspace 1)
    G_STORE %6, %3 :: (store (s32), addrspace 1)

    ; 64-bit

    ; maxnum vs
    %14:vgpr(s64) = G_FMAXNUM %10, %11

    ; maxnum sv
    %15:vgpr(s64) = G_FMAXNUM %11, %10

    ; maxnum vv
    %16:vgpr(s64) = G_FMAXNUM %11, %12

    S_ENDPGM 0, implicit %14, implicit %15, implicit %16
...

---

name: fmaxnum_f32_f64_ieee_mode_off
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    ieee: false

body: |
  bb.0:
    liveins: $sgpr0, $vgpr0, $vgpr1, $vgpr3_vgpr4, $sgpr10_sgpr11, $vgpr10_vgpr11, $vgpr12_vgpr13
    ; GFX7-LABEL: name: fmaxnum_f32_f64_ieee_mode_off
    ; GFX7: liveins: $sgpr0, $vgpr0, $vgpr1, $vgpr3_vgpr4, $sgpr10_sgpr11, $vgpr10_vgpr11, $vgpr12_vgpr13
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; GFX7-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX7-NEXT: [[PRED_COPY2:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; GFX7-NEXT: [[PRED_COPY3:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr3_vgpr4
    ; GFX7-NEXT: [[PRED_COPY4:%[0-9]+]]:sreg_64 = PRED_COPY $sgpr10_sgpr11
    ; GFX7-NEXT: [[PRED_COPY5:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr10_vgpr11
    ; GFX7-NEXT: [[PRED_COPY6:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr12_vgpr13
    ; GFX7-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 0, [[PRED_COPY1]], 0, [[PRED_COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX7-NEXT: [[V_MAX_F32_e64_1:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 0, [[PRED_COPY]], 0, [[PRED_COPY1]], 0, 0, implicit $mode, implicit $exec
    ; GFX7-NEXT: [[V_MAX_F32_e64_2:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 0, [[PRED_COPY1]], 0, [[PRED_COPY2]], 0, 0, implicit $mode, implicit $exec
    ; GFX7-NEXT: FLAT_STORE_DWORD [[PRED_COPY3]], [[V_MAX_F32_e64_]], 0, 0, implicit $exec, implicit $flat_scr :: (store (s32), addrspace 1)
    ; GFX7-NEXT: FLAT_STORE_DWORD [[PRED_COPY3]], [[V_MAX_F32_e64_1]], 0, 0, implicit $exec, implicit $flat_scr :: (store (s32), addrspace 1)
    ; GFX7-NEXT: FLAT_STORE_DWORD [[PRED_COPY3]], [[V_MAX_F32_e64_2]], 0, 0, implicit $exec, implicit $flat_scr :: (store (s32), addrspace 1)
    ; GFX7-NEXT: [[V_MAX_F64_e64_:%[0-9]+]]:vreg_64 = nofpexcept V_MAX_F64_e64 0, [[PRED_COPY4]], 0, [[PRED_COPY5]], 0, 0, implicit $mode, implicit $exec
    ; GFX7-NEXT: [[V_MAX_F64_e64_1:%[0-9]+]]:vreg_64 = nofpexcept V_MAX_F64_e64 0, [[PRED_COPY5]], 0, [[PRED_COPY4]], 0, 0, implicit $mode, implicit $exec
    ; GFX7-NEXT: [[V_MAX_F64_e64_2:%[0-9]+]]:vreg_64 = nofpexcept V_MAX_F64_e64 0, [[PRED_COPY5]], 0, [[PRED_COPY6]], 0, 0, implicit $mode, implicit $exec
    ; GFX7-NEXT: S_ENDPGM 0, implicit [[V_MAX_F64_e64_]], implicit [[V_MAX_F64_e64_1]], implicit [[V_MAX_F64_e64_2]]
    %0:sgpr(s32) = COPY $sgpr0
    %1:vgpr(s32) = COPY $vgpr0
    %2:vgpr(s32) = COPY $vgpr1
    %3:vgpr(p1) = COPY $vgpr3_vgpr4

    %10:sgpr(s64) = COPY $sgpr10_sgpr11
    %11:vgpr(s64) = COPY $vgpr10_vgpr11
    %12:vgpr(s64) = COPY $vgpr12_vgpr13

    ; maxnum vs
    %4:vgpr(s32) = G_FMAXNUM %1, %0

    ; maxnum sv
    %5:vgpr(s32) = G_FMAXNUM %0, %1

    ; maxnum vv
    %6:vgpr(s32) = G_FMAXNUM %1, %2

    G_STORE %4, %3 :: (store (s32), addrspace 1)
    G_STORE %5, %3 :: (store (s32), addrspace 1)
    G_STORE %6, %3 :: (store (s32), addrspace 1)

    ; 64-bit

    ; maxnum vs
    %14:vgpr(s64) = G_FMAXNUM %10, %11

    ; maxnum sv
    %15:vgpr(s64) = G_FMAXNUM %11, %10

    ; maxnum vv
    %16:vgpr(s64) = G_FMAXNUM %11, %12

    S_ENDPGM 0, implicit %14, implicit %15, implicit %16
...
