# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=amdgcn -mcpu=gfx900 -run-pass=instruction-select -verify-machineinstrs -global-isel %s -o - | FileCheck %s -check-prefixes=WAVE64
# RUN: llc -march=amdgcn -mcpu=gfx1010 -run-pass=instruction-select -verify-machineinstrs -global-isel %s -o - | FileCheck %s -check-prefixes=WAVE32

---
name: i1_vcc_to_vcc_copy
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4

    ; WAVE64-LABEL: name: i1_vcc_to_vcc_copy
    ; WAVE64: liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4
    ; WAVE64-NEXT: {{  $}}
    ; WAVE64-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; WAVE64-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; WAVE64-NEXT: [[PRED_COPY2:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr2
    ; WAVE64-NEXT: [[PRED_COPY3:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr3
    ; WAVE64-NEXT: [[PRED_COPY4:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr4
    ; WAVE64-NEXT: [[DEF:%[0-9]+]]:sreg_32 = IMPLICIT_DEF
    ; WAVE64-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 2
    ; WAVE64-NEXT: [[PRED_COPY5:%[0-9]+]]:vgpr_32 = PRED_COPY [[S_MOV_B32_]]
    ; WAVE64-NEXT: [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_64_xexec = V_CMP_EQ_U32_e64 [[PRED_COPY]], [[PRED_COPY5]], implicit $exec
    ; WAVE64-NEXT: [[V_CNDMASK_B32_e64_:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[PRED_COPY2]], 0, [[PRED_COPY1]], [[V_CMP_EQ_U32_e64_]], implicit $exec
    ; WAVE64-NEXT: [[V_CNDMASK_B32_e64_1:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[PRED_COPY4]], 0, [[PRED_COPY3]], [[V_CMP_EQ_U32_e64_]], implicit $exec
    ; WAVE64-NEXT: [[PRED_COPY6:%[0-9]+]]:vgpr_32 = PRED_COPY [[DEF]]
    ; WAVE64-NEXT: [[PRED_COPY7:%[0-9]+]]:vgpr_32 = PRED_COPY [[DEF]]
    ; WAVE64-NEXT: EXP_DONE 0, [[V_CNDMASK_B32_e64_]], [[V_CNDMASK_B32_e64_1]], [[PRED_COPY6]], [[PRED_COPY7]], -1, 0, 15, implicit $exec
    ; WAVE64-NEXT: S_ENDPGM 0
    ; WAVE32-LABEL: name: i1_vcc_to_vcc_copy
    ; WAVE32: liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4
    ; WAVE32-NEXT: {{  $}}
    ; WAVE32-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; WAVE32-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; WAVE32-NEXT: [[PRED_COPY2:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr2
    ; WAVE32-NEXT: [[PRED_COPY3:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr3
    ; WAVE32-NEXT: [[PRED_COPY4:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr4
    ; WAVE32-NEXT: [[DEF:%[0-9]+]]:sreg_32 = IMPLICIT_DEF
    ; WAVE32-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 2
    ; WAVE32-NEXT: [[PRED_COPY5:%[0-9]+]]:vgpr_32 = PRED_COPY [[S_MOV_B32_]]
    ; WAVE32-NEXT: [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32_xm0_xexec = V_CMP_EQ_U32_e64 [[PRED_COPY]], [[PRED_COPY5]], implicit $exec
    ; WAVE32-NEXT: [[V_CNDMASK_B32_e64_:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[PRED_COPY2]], 0, [[PRED_COPY1]], [[V_CMP_EQ_U32_e64_]], implicit $exec
    ; WAVE32-NEXT: [[V_CNDMASK_B32_e64_1:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[PRED_COPY4]], 0, [[PRED_COPY3]], [[V_CMP_EQ_U32_e64_]], implicit $exec
    ; WAVE32-NEXT: [[PRED_COPY6:%[0-9]+]]:vgpr_32 = PRED_COPY [[DEF]]
    ; WAVE32-NEXT: [[PRED_COPY7:%[0-9]+]]:vgpr_32 = PRED_COPY [[DEF]]
    ; WAVE32-NEXT: EXP_DONE 0, [[V_CNDMASK_B32_e64_]], [[V_CNDMASK_B32_e64_1]], [[PRED_COPY6]], [[PRED_COPY7]], -1, 0, 15, implicit $exec
    ; WAVE32-NEXT: S_ENDPGM 0
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vgpr(s32) = COPY $vgpr2
    %3:vgpr(s32) = COPY $vgpr3
    %4:vgpr(s32) = COPY $vgpr4
    %5:sgpr(s32) = G_IMPLICIT_DEF
    %6:sgpr(s32) = G_CONSTANT i32 2
    %7:vgpr(s32) = COPY %6(s32)
    %8:vcc(s1) = G_ICMP intpred(eq), %0(s32), %7
    %9:vgpr(s32) = G_SELECT %8(s1), %1, %2
    %10:vgpr(s32) = G_SELECT %8(s1), %3, %4
    %11:vgpr(s32) = COPY %5(s32)
    %12:vgpr(s32) = COPY %5(s32)
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.amdgcn.exp), 0, 15, %9(s32), %10(s32), %11(s32), %12(s32), -1, -1
    S_ENDPGM 0
...

---
name: i1_sgpr_to_vcc_copy
legalized: true
regBankSelected: true
tracksRegLiveness: true

body: |
  bb.0:
    liveins: $sgpr0, $vgpr0, $vgpr1, $vgpr2, $vgpr3

    ; WAVE64-LABEL: name: i1_sgpr_to_vcc_copy
    ; WAVE64: liveins: $sgpr0, $vgpr0, $vgpr1, $vgpr2, $vgpr3
    ; WAVE64-NEXT: {{  $}}
    ; WAVE64-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; WAVE64-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; WAVE64-NEXT: [[PRED_COPY2:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; WAVE64-NEXT: [[PRED_COPY3:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr2
    ; WAVE64-NEXT: [[PRED_COPY4:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr3
    ; WAVE64-NEXT: [[DEF:%[0-9]+]]:sreg_32 = IMPLICIT_DEF
    ; WAVE64-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 2
    ; WAVE64-NEXT: S_CMP_EQ_U32 [[PRED_COPY]], [[S_MOV_B32_]], implicit-def $scc
    ; WAVE64-NEXT: [[PRED_COPY5:%[0-9]+]]:sreg_32 = PRED_COPY $scc
    ; WAVE64-NEXT: [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 1, [[PRED_COPY5]], implicit-def $scc
    ; WAVE64-NEXT: [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_64_xexec = V_CMP_NE_U32_e64 0, [[S_AND_B32_]], implicit $exec
    ; WAVE64-NEXT: [[V_CNDMASK_B32_e64_:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[PRED_COPY2]], 0, [[PRED_COPY1]], [[V_CMP_NE_U32_e64_]], implicit $exec
    ; WAVE64-NEXT: [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 1, [[PRED_COPY5]], implicit-def $scc
    ; WAVE64-NEXT: [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_64_xexec = V_CMP_NE_U32_e64 0, [[S_AND_B32_1]], implicit $exec
    ; WAVE64-NEXT: [[V_CNDMASK_B32_e64_1:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[PRED_COPY4]], 0, [[PRED_COPY3]], [[V_CMP_NE_U32_e64_1]], implicit $exec
    ; WAVE64-NEXT: [[PRED_COPY6:%[0-9]+]]:vgpr_32 = PRED_COPY [[DEF]]
    ; WAVE64-NEXT: [[PRED_COPY7:%[0-9]+]]:vgpr_32 = PRED_COPY [[DEF]]
    ; WAVE64-NEXT: EXP_DONE 0, [[V_CNDMASK_B32_e64_]], [[V_CNDMASK_B32_e64_1]], [[PRED_COPY6]], [[PRED_COPY7]], -1, 0, 15, implicit $exec
    ; WAVE64-NEXT: S_ENDPGM 0
    ; WAVE32-LABEL: name: i1_sgpr_to_vcc_copy
    ; WAVE32: liveins: $sgpr0, $vgpr0, $vgpr1, $vgpr2, $vgpr3
    ; WAVE32-NEXT: {{  $}}
    ; WAVE32-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY $sgpr0
    ; WAVE32-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; WAVE32-NEXT: [[PRED_COPY2:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; WAVE32-NEXT: [[PRED_COPY3:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr2
    ; WAVE32-NEXT: [[PRED_COPY4:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr3
    ; WAVE32-NEXT: [[DEF:%[0-9]+]]:sreg_32 = IMPLICIT_DEF
    ; WAVE32-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 2
    ; WAVE32-NEXT: S_CMP_EQ_U32 [[PRED_COPY]], [[S_MOV_B32_]], implicit-def $scc
    ; WAVE32-NEXT: [[PRED_COPY5:%[0-9]+]]:sreg_32 = PRED_COPY $scc
    ; WAVE32-NEXT: [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 1, [[PRED_COPY5]], implicit-def $scc
    ; WAVE32-NEXT: [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32_xm0_xexec = V_CMP_NE_U32_e64 0, [[S_AND_B32_]], implicit $exec
    ; WAVE32-NEXT: [[V_CNDMASK_B32_e64_:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[PRED_COPY2]], 0, [[PRED_COPY1]], [[V_CMP_NE_U32_e64_]], implicit $exec
    ; WAVE32-NEXT: [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 1, [[PRED_COPY5]], implicit-def $scc
    ; WAVE32-NEXT: [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32_xm0_xexec = V_CMP_NE_U32_e64 0, [[S_AND_B32_1]], implicit $exec
    ; WAVE32-NEXT: [[V_CNDMASK_B32_e64_1:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, [[PRED_COPY4]], 0, [[PRED_COPY3]], [[V_CMP_NE_U32_e64_1]], implicit $exec
    ; WAVE32-NEXT: [[PRED_COPY6:%[0-9]+]]:vgpr_32 = PRED_COPY [[DEF]]
    ; WAVE32-NEXT: [[PRED_COPY7:%[0-9]+]]:vgpr_32 = PRED_COPY [[DEF]]
    ; WAVE32-NEXT: EXP_DONE 0, [[V_CNDMASK_B32_e64_]], [[V_CNDMASK_B32_e64_1]], [[PRED_COPY6]], [[PRED_COPY7]], -1, 0, 15, implicit $exec
    ; WAVE32-NEXT: S_ENDPGM 0
    %0:sgpr(s32) = COPY $sgpr0
    %1:vgpr(s32) = COPY $vgpr0
    %2:vgpr(s32) = COPY $vgpr1
    %3:vgpr(s32) = COPY $vgpr2
    %4:vgpr(s32) = COPY $vgpr3
    %5:sgpr(s32) = G_IMPLICIT_DEF
    %6:sgpr(s32) = G_CONSTANT i32 2
    %7:sgpr(s32) = G_ICMP intpred(eq), %0(s32), %6
    %8:sgpr(s1) = G_TRUNC %7(s32)
    %9:vcc(s1) = COPY %8(s1)
    %10:vgpr(s32) = G_SELECT %9(s1), %1, %2
    %11:vcc(s1) = COPY %8(s1)
    %12:vgpr(s32) = G_SELECT %11(s1), %3, %4
    %13:vgpr(s32) = COPY %5(s32)
    %14:vgpr(s32) = COPY %5(s32)
    G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.amdgcn.exp), 0, 15, %10(s32), %12(s32), %13(s32), %14(s32), -1, -1
    S_ENDPGM 0
...

