# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=amdgcn -run-pass=instruction-select -verify-machineinstrs -o - %s | FileCheck %s
---
name:            extract512
legalized:       true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: extract512
    ; CHECK: [[DEF:%[0-9]+]]:sgpr_512 = IMPLICIT_DEF
    ; CHECK-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub0
    ; CHECK-NEXT: [[PRED_COPY1:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub1
    ; CHECK-NEXT: [[PRED_COPY2:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub2
    ; CHECK-NEXT: [[PRED_COPY3:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub3
    ; CHECK-NEXT: [[PRED_COPY4:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub4
    ; CHECK-NEXT: [[PRED_COPY5:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub5
    ; CHECK-NEXT: [[PRED_COPY6:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub6
    ; CHECK-NEXT: [[PRED_COPY7:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub7
    ; CHECK-NEXT: [[PRED_COPY8:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub8
    ; CHECK-NEXT: [[PRED_COPY9:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub9
    ; CHECK-NEXT: [[PRED_COPY10:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub10
    ; CHECK-NEXT: [[PRED_COPY11:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub11
    ; CHECK-NEXT: [[PRED_COPY12:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub12
    ; CHECK-NEXT: [[PRED_COPY13:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub13
    ; CHECK-NEXT: [[PRED_COPY14:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub14
    ; CHECK-NEXT: [[PRED_COPY15:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub15
    ; CHECK-NEXT: $sgpr0 = PRED_COPY [[PRED_COPY]]
    ; CHECK-NEXT: $sgpr1 = PRED_COPY [[PRED_COPY1]]
    ; CHECK-NEXT: $sgpr2 = PRED_COPY [[PRED_COPY2]]
    ; CHECK-NEXT: $sgpr3 = PRED_COPY [[PRED_COPY3]]
    ; CHECK-NEXT: $sgpr4 = PRED_COPY [[PRED_COPY4]]
    ; CHECK-NEXT: $sgpr5 = PRED_COPY [[PRED_COPY5]]
    ; CHECK-NEXT: $sgpr6 = PRED_COPY [[PRED_COPY6]]
    ; CHECK-NEXT: $sgpr7 = PRED_COPY [[PRED_COPY7]]
    ; CHECK-NEXT: $sgpr8 = PRED_COPY [[PRED_COPY8]]
    ; CHECK-NEXT: $sgpr9 = PRED_COPY [[PRED_COPY9]]
    ; CHECK-NEXT: $sgpr10 = PRED_COPY [[PRED_COPY10]]
    ; CHECK-NEXT: $sgpr11 = PRED_COPY [[PRED_COPY11]]
    ; CHECK-NEXT: $sgpr12 = PRED_COPY [[PRED_COPY12]]
    ; CHECK-NEXT: $sgpr13 = PRED_COPY [[PRED_COPY13]]
    ; CHECK-NEXT: $sgpr14 = PRED_COPY [[PRED_COPY14]]
    ; CHECK-NEXT: $sgpr15 = PRED_COPY [[PRED_COPY15]]
    ; CHECK-NEXT: SI_RETURN_TO_EPILOG $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $sgpr12, $sgpr13, $sgpr14, $sgpr15
    %0:sgpr(s512) = G_IMPLICIT_DEF
    %1:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 0
    %2:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 32
    %3:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 64
    %4:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 96
    %5:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 128
    %6:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 160
    %7:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 192
    %8:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 224
    %9:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 256
    %10:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 288
    %11:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 320
    %12:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 352
    %13:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 384
    %14:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 416
    %15:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 448
    %16:sgpr(s32) = G_EXTRACT %0:sgpr(s512), 480
    $sgpr0 = COPY %1:sgpr(s32)
    $sgpr1 = COPY %2:sgpr(s32)
    $sgpr2 = COPY %3:sgpr(s32)
    $sgpr3 = COPY %4:sgpr(s32)
    $sgpr4 = COPY %5:sgpr(s32)
    $sgpr5 = COPY %6:sgpr(s32)
    $sgpr6 = COPY %7:sgpr(s32)
    $sgpr7 = COPY %8:sgpr(s32)
    $sgpr8 = COPY %9:sgpr(s32)
    $sgpr9 = COPY %10:sgpr(s32)
    $sgpr10 = COPY %11:sgpr(s32)
    $sgpr11 = COPY %12:sgpr(s32)
    $sgpr12 = COPY %13:sgpr(s32)
    $sgpr13 = COPY %14:sgpr(s32)
    $sgpr14 = COPY %15:sgpr(s32)
    $sgpr15 = COPY %16:sgpr(s32)
    SI_RETURN_TO_EPILOG $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $sgpr12, $sgpr13, $sgpr14, $sgpr15
...

---
name:            extract_s_s32_s1024
legalized:       true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: extract_s_s32_s1024
    ; CHECK: [[DEF:%[0-9]+]]:sgpr_1024 = IMPLICIT_DEF
    ; CHECK-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub0
    ; CHECK-NEXT: [[PRED_COPY1:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub1
    ; CHECK-NEXT: [[PRED_COPY2:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub2
    ; CHECK-NEXT: [[PRED_COPY3:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub3
    ; CHECK-NEXT: [[PRED_COPY4:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub4
    ; CHECK-NEXT: [[PRED_COPY5:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub5
    ; CHECK-NEXT: [[PRED_COPY6:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub6
    ; CHECK-NEXT: [[PRED_COPY7:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub7
    ; CHECK-NEXT: [[PRED_COPY8:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub8
    ; CHECK-NEXT: [[PRED_COPY9:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub9
    ; CHECK-NEXT: [[PRED_COPY10:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub10
    ; CHECK-NEXT: [[PRED_COPY11:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub11
    ; CHECK-NEXT: [[PRED_COPY12:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub12
    ; CHECK-NEXT: [[PRED_COPY13:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub13
    ; CHECK-NEXT: [[PRED_COPY14:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub14
    ; CHECK-NEXT: [[PRED_COPY15:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub15
    ; CHECK-NEXT: [[PRED_COPY16:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub16
    ; CHECK-NEXT: [[PRED_COPY17:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub17
    ; CHECK-NEXT: [[PRED_COPY18:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub18
    ; CHECK-NEXT: [[PRED_COPY19:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub19
    ; CHECK-NEXT: [[PRED_COPY20:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub20
    ; CHECK-NEXT: [[PRED_COPY21:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub21
    ; CHECK-NEXT: [[PRED_COPY22:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub22
    ; CHECK-NEXT: [[PRED_COPY23:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub23
    ; CHECK-NEXT: [[PRED_COPY24:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub24
    ; CHECK-NEXT: [[PRED_COPY25:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub25
    ; CHECK-NEXT: [[PRED_COPY26:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub26
    ; CHECK-NEXT: [[PRED_COPY27:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub27
    ; CHECK-NEXT: [[PRED_COPY28:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub28
    ; CHECK-NEXT: [[PRED_COPY29:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub29
    ; CHECK-NEXT: [[PRED_COPY30:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub30
    ; CHECK-NEXT: [[PRED_COPY31:%[0-9]+]]:sreg_32 = PRED_COPY [[DEF]].sub31
    ; CHECK-NEXT: S_ENDPGM 0, implicit [[DEF]], implicit [[PRED_COPY]], implicit [[PRED_COPY1]], implicit [[PRED_COPY2]], implicit [[PRED_COPY3]], implicit [[PRED_COPY4]], implicit [[PRED_COPY5]], implicit [[PRED_COPY6]], implicit [[PRED_COPY7]], implicit [[PRED_COPY8]], implicit [[PRED_COPY9]], implicit [[PRED_COPY10]], implicit [[PRED_COPY11]], implicit [[PRED_COPY12]], implicit [[PRED_COPY13]], implicit [[PRED_COPY14]], implicit [[PRED_COPY15]], implicit [[PRED_COPY16]], implicit [[PRED_COPY17]], implicit [[PRED_COPY18]], implicit [[PRED_COPY19]], implicit [[PRED_COPY20]], implicit [[PRED_COPY21]], implicit [[PRED_COPY22]], implicit [[PRED_COPY23]], implicit [[PRED_COPY24]], implicit [[PRED_COPY25]], implicit [[PRED_COPY26]], implicit [[PRED_COPY27]], implicit [[PRED_COPY28]], implicit [[PRED_COPY29]], implicit [[PRED_COPY30]], implicit [[PRED_COPY31]]
    %0:sgpr(s1024) = G_IMPLICIT_DEF
    %1:sgpr(s32) = G_EXTRACT %0:sgpr, 0
    %2:sgpr(s32) = G_EXTRACT %0:sgpr, 32
    %3:sgpr(s32) = G_EXTRACT %0:sgpr, 64
    %4:sgpr(s32) = G_EXTRACT %0:sgpr, 96
    %5:sgpr(s32) = G_EXTRACT %0:sgpr, 128
    %6:sgpr(s32) = G_EXTRACT %0:sgpr, 160
    %7:sgpr(s32) = G_EXTRACT %0:sgpr, 192
    %8:sgpr(s32) = G_EXTRACT %0:sgpr, 224
    %9:sgpr(s32) = G_EXTRACT %0:sgpr, 256
    %10:sgpr(s32) = G_EXTRACT %0:sgpr, 288
    %11:sgpr(s32) = G_EXTRACT %0:sgpr, 320
    %12:sgpr(s32) = G_EXTRACT %0:sgpr, 352
    %13:sgpr(s32) = G_EXTRACT %0:sgpr, 384
    %14:sgpr(s32) = G_EXTRACT %0:sgpr, 416
    %15:sgpr(s32) = G_EXTRACT %0:sgpr, 448
    %16:sgpr(s32) = G_EXTRACT %0:sgpr, 480

    %17:sgpr(s32) = G_EXTRACT %0:sgpr, 512
    %18:sgpr(s32) = G_EXTRACT %0:sgpr, 544
    %19:sgpr(s32) = G_EXTRACT %0:sgpr, 576
    %20:sgpr(s32) = G_EXTRACT %0:sgpr, 608
    %21:sgpr(s32) = G_EXTRACT %0:sgpr, 640
    %22:sgpr(s32) = G_EXTRACT %0:sgpr, 672
    %23:sgpr(s32) = G_EXTRACT %0:sgpr, 704
    %24:sgpr(s32) = G_EXTRACT %0:sgpr, 736
    %25:sgpr(s32) = G_EXTRACT %0:sgpr, 768
    %26:sgpr(s32) = G_EXTRACT %0:sgpr, 800
    %27:sgpr(s32) = G_EXTRACT %0:sgpr, 832
    %28:sgpr(s32) = G_EXTRACT %0:sgpr, 864
    %29:sgpr(s32) = G_EXTRACT %0:sgpr, 896
    %30:sgpr(s32) = G_EXTRACT %0:sgpr, 928
    %31:sgpr(s32) = G_EXTRACT %0:sgpr, 960
    %32:sgpr(s32) = G_EXTRACT %0:sgpr, 992

    S_ENDPGM 0, implicit %0, implicit %1, implicit %2, implicit %3, implicit %4, implicit %5, implicit %6, implicit %7, implicit %8, implicit %9, implicit %10, implicit %11, implicit %12, implicit %13, implicit %14, implicit %15, implicit %16, implicit %17, implicit %18, implicit %19, implicit %20, implicit %21, implicit %22, implicit %23, implicit %24, implicit %25, implicit %26, implicit %27, implicit %28, implicit %29, implicit %30, implicit %31, implicit %32
...

# TODO: Handle offset 32
---
name:            extract_sgpr_s64_from_s128
legalized:       true
regBankSelected: true

body: |
  bb.0:
    ; CHECK-LABEL: name: extract_sgpr_s64_from_s128
    ; CHECK: [[DEF:%[0-9]+]]:sgpr_128 = IMPLICIT_DEF
    ; CHECK-NEXT: [[PRED_COPY:%[0-9]+]]:sreg_64 = PRED_COPY [[DEF]].sub0_sub1
    ; CHECK-NEXT: [[PRED_COPY1:%[0-9]+]]:sreg_64 = PRED_COPY [[DEF]].sub2_sub3
    ; CHECK-NEXT: S_ENDPGM 0, implicit [[PRED_COPY]], implicit [[PRED_COPY1]]
    %0:sgpr(s128) = G_IMPLICIT_DEF
    %1:sgpr(s64) = G_EXTRACT %0, 0
    %2:sgpr(s64) = G_EXTRACT %0, 64
    S_ENDPGM 0, implicit %1, implicit %2

...

---
name:            extract_sgpr_s96_from_s128
legalized:       true
regBankSelected: true

body: |
  bb.0:
    liveins: $sgpr0_sgpr1_sgpr2_sgpr3
    ; CHECK-LABEL: name: extract_sgpr_s96_from_s128
    ; CHECK: liveins: $sgpr0_sgpr1_sgpr2_sgpr3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[PRED_COPY:%[0-9]+]]:sgpr_128 = PRED_COPY $sgpr0_sgpr1_sgpr2_sgpr3
    ; CHECK-NEXT: [[PRED_COPY1:%[0-9]+]]:sgpr_96 = PRED_COPY [[PRED_COPY]].sub0_sub1_sub2
    ; CHECK-NEXT: S_ENDPGM 0, implicit [[PRED_COPY1]]
    %0:sgpr(s128) = COPY $sgpr0_sgpr1_sgpr2_sgpr3
    %1:sgpr(s96) = G_EXTRACT %0, 0
    S_ENDPGM 0, implicit %1

...
