# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn -mcpu=fiji -run-pass=instruction-select -verify-machineinstrs -global-isel-abort=0 -disable-gisel-legality-check -o - %s | FileCheck -check-prefix=GFX8 %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx900 -run-pass=instruction-select -verify-machineinstrs -o - %s | FileCheck -check-prefix=GFX9 %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx1010 -run-pass=instruction-select -verify-machineinstrs -o - %s | FileCheck -check-prefix=GFX10 %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx1100 -run-pass=instruction-select -mattr=+real-true16 -verify-machineinstrs -o - %s | FileCheck -check-prefixes=GFX11,GFX11-TRUE16 %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx1100 -run-pass=instruction-select -mattr=-real-true16 -verify-machineinstrs -o - %s | FileCheck -check-prefixes=GFX11,GFX11-FAKE16 %s

---

name:            fcanonicalize_f16_denorm
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    fp64-fp16-input-denormals: true
    fp64-fp16-output-denormals: true

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX8-LABEL: name: fcanonicalize_f16_denorm
    ; GFX8: liveins: $vgpr0
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX8-NEXT: [[V_MAX_F16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F16_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX8-NEXT: S_ENDPGM 0, implicit [[V_MAX_F16_e64_]]
    ;
    ; GFX9-LABEL: name: fcanonicalize_f16_denorm
    ; GFX9: liveins: $vgpr0
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_MAX_F16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F16_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: S_ENDPGM 0, implicit [[V_MAX_F16_e64_]]
    ;
    ; GFX10-LABEL: name: fcanonicalize_f16_denorm
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX10-NEXT: [[V_MAX_F16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F16_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX10-NEXT: S_ENDPGM 0, implicit [[V_MAX_F16_e64_]]
    ;
    ; GFX11-TRUE16-LABEL: name: fcanonicalize_f16_denorm
    ; GFX11-TRUE16: liveins: $vgpr0
    ; GFX11-TRUE16-NEXT: {{  $}}
    ; GFX11-TRUE16-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX11-TRUE16-NEXT: [[COPY1:%[0-9]+]]:vgpr_16 = COPY [[COPY]].lo16
    ; GFX11-TRUE16-NEXT: [[V_MAX_F16_t16_e64_:%[0-9]+]]:vgpr_16 = nofpexcept V_MAX_F16_t16_e64 0, [[COPY1]], 0, [[COPY1]], 0, 0, 0, implicit $mode, implicit $exec
    ; GFX11-TRUE16-NEXT: S_ENDPGM 0, implicit [[V_MAX_F16_t16_e64_]]
    ;
    ; GFX11-FAKE16-LABEL: name: fcanonicalize_f16_denorm
    ; GFX11-FAKE16: liveins: $vgpr0
    ; GFX11-FAKE16-NEXT: {{  $}}
    ; GFX11-FAKE16-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX11-FAKE16-NEXT: [[V_MAX_F16_fake16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F16_fake16_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-FAKE16-NEXT: S_ENDPGM 0, implicit [[V_MAX_F16_fake16_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s16) = G_TRUNC %0
    %2:vgpr(f16) = G_FCANONICALIZE %1
    S_ENDPGM 0, implicit %2
...

---

name:            fcanonicalize_f16_flush
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    fp64-fp16-input-denormals: false
    fp64-fp16-output-denormals: false

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX8-LABEL: name: fcanonicalize_f16_flush
    ; GFX8: liveins: $vgpr0
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX8-NEXT: [[V_MUL_F16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_e64 0, 15360, 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX8-NEXT: S_ENDPGM 0, implicit [[V_MUL_F16_e64_]]
    ;
    ; GFX9-LABEL: name: fcanonicalize_f16_flush
    ; GFX9: liveins: $vgpr0
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_MAX_F16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F16_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: S_ENDPGM 0, implicit [[V_MAX_F16_e64_]]
    ;
    ; GFX10-LABEL: name: fcanonicalize_f16_flush
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX10-NEXT: [[V_MAX_F16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F16_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX10-NEXT: S_ENDPGM 0, implicit [[V_MAX_F16_e64_]]
    ;
    ; GFX11-TRUE16-LABEL: name: fcanonicalize_f16_flush
    ; GFX11-TRUE16: liveins: $vgpr0
    ; GFX11-TRUE16-NEXT: {{  $}}
    ; GFX11-TRUE16-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX11-TRUE16-NEXT: [[COPY1:%[0-9]+]]:vgpr_16 = COPY [[COPY]].lo16
    ; GFX11-TRUE16-NEXT: [[V_MAX_F16_t16_e64_:%[0-9]+]]:vgpr_16 = nofpexcept V_MAX_F16_t16_e64 0, [[COPY1]], 0, [[COPY1]], 0, 0, 0, implicit $mode, implicit $exec
    ; GFX11-TRUE16-NEXT: S_ENDPGM 0, implicit [[V_MAX_F16_t16_e64_]]
    ;
    ; GFX11-FAKE16-LABEL: name: fcanonicalize_f16_flush
    ; GFX11-FAKE16: liveins: $vgpr0
    ; GFX11-FAKE16-NEXT: {{  $}}
    ; GFX11-FAKE16-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX11-FAKE16-NEXT: [[V_MAX_F16_fake16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F16_fake16_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-FAKE16-NEXT: S_ENDPGM 0, implicit [[V_MAX_F16_fake16_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s16) = G_TRUNC %0
    %2:vgpr(f16) = G_FCANONICALIZE %1
    S_ENDPGM 0, implicit %2
...

---

name:            fcanonicalize_f32_denorm
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    fp32-input-denormals: true
    fp32-output-denormals: true

body: |
  bb.0:
    liveins: $vgpr0

    ; GFX8-LABEL: name: fcanonicalize_f32_denorm
    ; GFX8: liveins: $vgpr0
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX8-NEXT: [[V_MUL_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F32_e64 0, 1065353216, 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX8-NEXT: S_ENDPGM 0, implicit [[V_MUL_F32_e64_]]
    ;
    ; GFX9-LABEL: name: fcanonicalize_f32_denorm
    ; GFX9: liveins: $vgpr0
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX10-LABEL: name: fcanonicalize_f32_denorm
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX10-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX10-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX11-LABEL: name: fcanonicalize_f32_denorm
    ; GFX11: liveins: $vgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX11-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(f32) = G_FCANONICALIZE %0
    S_ENDPGM 0, implicit %1
...

---

name:            fcanonicalize_f32_flush
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    fp32-input-denormals: false
    fp32-output-denormals: false

body: |
  bb.0:
    liveins: $vgpr0

    ; GFX8-LABEL: name: fcanonicalize_f32_flush
    ; GFX8: liveins: $vgpr0
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX8-NEXT: [[V_MUL_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F32_e64 0, 1065353216, 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX8-NEXT: S_ENDPGM 0, implicit [[V_MUL_F32_e64_]]
    ;
    ; GFX9-LABEL: name: fcanonicalize_f32_flush
    ; GFX9: liveins: $vgpr0
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX10-LABEL: name: fcanonicalize_f32_flush
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX10-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX10-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX11-LABEL: name: fcanonicalize_f32_flush
    ; GFX11: liveins: $vgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX11-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(f32) = G_FCANONICALIZE %0
    S_ENDPGM 0, implicit %1
...

---

name:            fcanonicalize_v2f16_denorm
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    fp64-fp16-input-denormals: true
    fp64-fp16-output-denormals: true

body: |
  bb.0:
    liveins: $vgpr0

    ; GFX8-LABEL: name: fcanonicalize_v2f16_denorm
    ; GFX8: liveins: $vgpr0
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX8-NEXT: [[V_PK_MAX_F16_:%[0-9]+]]:vgpr_32 = nofpexcept V_PK_MAX_F16 8, [[COPY]], 8, [[COPY]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; GFX8-NEXT: S_ENDPGM 0, implicit [[V_PK_MAX_F16_]]
    ;
    ; GFX9-LABEL: name: fcanonicalize_v2f16_denorm
    ; GFX9: liveins: $vgpr0
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_PK_MAX_F16_:%[0-9]+]]:vgpr_32 = nofpexcept V_PK_MAX_F16 8, [[COPY]], 8, [[COPY]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: S_ENDPGM 0, implicit [[V_PK_MAX_F16_]]
    ;
    ; GFX10-LABEL: name: fcanonicalize_v2f16_denorm
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX10-NEXT: [[V_PK_MAX_F16_:%[0-9]+]]:vgpr_32 = nofpexcept V_PK_MAX_F16 8, [[COPY]], 8, [[COPY]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; GFX10-NEXT: S_ENDPGM 0, implicit [[V_PK_MAX_F16_]]
    ;
    ; GFX11-LABEL: name: fcanonicalize_v2f16_denorm
    ; GFX11: liveins: $vgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX11-NEXT: [[V_PK_MAX_F16_:%[0-9]+]]:vgpr_32 = nofpexcept V_PK_MAX_F16 8, [[COPY]], 8, [[COPY]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: S_ENDPGM 0, implicit [[V_PK_MAX_F16_]]
    %0:vgpr(<2 x s16>) = COPY $vgpr0
    %1:vgpr(<2 x f16>) = G_FCANONICALIZE %0
    S_ENDPGM 0, implicit %1
...

---

name:            fcanonicalize_v2f16_flush
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    fp64-fp16-input-denormals: false
    fp64-fp16-output-denormals: false

body: |
  bb.0:
    liveins: $vgpr0

    ; GFX8-LABEL: name: fcanonicalize_v2f16_flush
    ; GFX8: liveins: $vgpr0
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX8-NEXT: [[V_PK_MUL_F16_:%[0-9]+]]:vgpr_32 = nofpexcept V_PK_MUL_F16 0, 15360, 8, [[COPY]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; GFX8-NEXT: S_ENDPGM 0, implicit [[V_PK_MUL_F16_]]
    ;
    ; GFX9-LABEL: name: fcanonicalize_v2f16_flush
    ; GFX9: liveins: $vgpr0
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_PK_MAX_F16_:%[0-9]+]]:vgpr_32 = nofpexcept V_PK_MAX_F16 8, [[COPY]], 8, [[COPY]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: S_ENDPGM 0, implicit [[V_PK_MAX_F16_]]
    ;
    ; GFX10-LABEL: name: fcanonicalize_v2f16_flush
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX10-NEXT: [[V_PK_MAX_F16_:%[0-9]+]]:vgpr_32 = nofpexcept V_PK_MAX_F16 8, [[COPY]], 8, [[COPY]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; GFX10-NEXT: S_ENDPGM 0, implicit [[V_PK_MAX_F16_]]
    ;
    ; GFX11-LABEL: name: fcanonicalize_v2f16_flush
    ; GFX11: liveins: $vgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX11-NEXT: [[V_PK_MAX_F16_:%[0-9]+]]:vgpr_32 = nofpexcept V_PK_MAX_F16 8, [[COPY]], 8, [[COPY]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: S_ENDPGM 0, implicit [[V_PK_MAX_F16_]]
    %0:vgpr(<2 x s16>) = COPY $vgpr0
    %1:vgpr(<2 x f16>) = G_FCANONICALIZE %0
    S_ENDPGM 0, implicit %1
...

---

name:            fcanonicalize_f64_denorm
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    fp64-fp16-input-denormals: true
    fp64-fp16-output-denormals: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1

    ; GFX8-LABEL: name: fcanonicalize_f64_denorm
    ; GFX8: liveins: $vgpr0_vgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:vreg_64 = COPY $vgpr0_vgpr1
    ; GFX8-NEXT: [[V_MAX_F64_e64_:%[0-9]+]]:vreg_64 = nofpexcept V_MAX_F64_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX8-NEXT: S_ENDPGM 0, implicit [[V_MAX_F64_e64_]]
    ;
    ; GFX9-LABEL: name: fcanonicalize_f64_denorm
    ; GFX9: liveins: $vgpr0_vgpr1
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vreg_64 = COPY $vgpr0_vgpr1
    ; GFX9-NEXT: [[V_MAX_F64_e64_:%[0-9]+]]:vreg_64 = nofpexcept V_MAX_F64_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: S_ENDPGM 0, implicit [[V_MAX_F64_e64_]]
    ;
    ; GFX10-LABEL: name: fcanonicalize_f64_denorm
    ; GFX10: liveins: $vgpr0_vgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:vreg_64 = COPY $vgpr0_vgpr1
    ; GFX10-NEXT: [[V_MAX_F64_e64_:%[0-9]+]]:vreg_64 = nofpexcept V_MAX_F64_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX10-NEXT: S_ENDPGM 0, implicit [[V_MAX_F64_e64_]]
    ;
    ; GFX11-LABEL: name: fcanonicalize_f64_denorm
    ; GFX11: liveins: $vgpr0_vgpr1
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:vreg_64 = COPY $vgpr0_vgpr1
    ; GFX11-NEXT: [[V_MAX_F64_e64_:%[0-9]+]]:vreg_64 = nofpexcept V_MAX_F64_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: S_ENDPGM 0, implicit [[V_MAX_F64_e64_]]
    %0:vgpr(s64) = COPY $vgpr0_vgpr1
    %1:vgpr(f64) = G_FCANONICALIZE %0
    S_ENDPGM 0, implicit %1
...

---

name:            fcanonicalize_f64_flush
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    fp64-fp16-input-denormals: false
    fp64-fp16-output-denormals: false

body: |
  bb.0:
    liveins: $vgpr0_vgpr1

    ; GFX8-LABEL: name: fcanonicalize_f64_flush
    ; GFX8: liveins: $vgpr0_vgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:vreg_64 = COPY $vgpr0_vgpr1
    ; GFX8-NEXT: [[V_MUL_F64_e64_:%[0-9]+]]:vreg_64 = nofpexcept V_MUL_F64_e64 0, 4607182418800017408, 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX8-NEXT: S_ENDPGM 0, implicit [[V_MUL_F64_e64_]]
    ;
    ; GFX9-LABEL: name: fcanonicalize_f64_flush
    ; GFX9: liveins: $vgpr0_vgpr1
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vreg_64 = COPY $vgpr0_vgpr1
    ; GFX9-NEXT: [[V_MAX_F64_e64_:%[0-9]+]]:vreg_64 = nofpexcept V_MAX_F64_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: S_ENDPGM 0, implicit [[V_MAX_F64_e64_]]
    ;
    ; GFX10-LABEL: name: fcanonicalize_f64_flush
    ; GFX10: liveins: $vgpr0_vgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:vreg_64 = COPY $vgpr0_vgpr1
    ; GFX10-NEXT: [[V_MAX_F64_e64_:%[0-9]+]]:vreg_64 = nofpexcept V_MAX_F64_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX10-NEXT: S_ENDPGM 0, implicit [[V_MAX_F64_e64_]]
    ;
    ; GFX11-LABEL: name: fcanonicalize_f64_flush
    ; GFX11: liveins: $vgpr0_vgpr1
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:vreg_64 = COPY $vgpr0_vgpr1
    ; GFX11-NEXT: [[V_MAX_F64_e64_:%[0-9]+]]:vreg_64 = nofpexcept V_MAX_F64_e64 0, [[COPY]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: S_ENDPGM 0, implicit [[V_MAX_F64_e64_]]
    %0:vgpr(s64) = COPY $vgpr0_vgpr1
    %1:vgpr(f64) = G_FCANONICALIZE %0
    S_ENDPGM 0, implicit %1
...

---

name:            fcanonicalize_fabs_f32_denorm
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    fp32-input-denormals: true
    fp32-output-denormals: true

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX8-LABEL: name: fcanonicalize_fabs_f32_denorm
    ; GFX8: liveins: $vgpr0
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX8-NEXT: [[V_MUL_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F32_e64 0, 1065353216, 2, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX8-NEXT: S_ENDPGM 0, implicit [[V_MUL_F32_e64_]]
    ;
    ; GFX9-LABEL: name: fcanonicalize_fabs_f32_denorm
    ; GFX9: liveins: $vgpr0
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 2, [[COPY]], 2, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX10-LABEL: name: fcanonicalize_fabs_f32_denorm
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX10-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 2, [[COPY]], 2, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX10-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX11-LABEL: name: fcanonicalize_fabs_f32_denorm
    ; GFX11: liveins: $vgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX11-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 2, [[COPY]], 2, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = G_FABS %0
    %2:vgpr(f32) = G_FCANONICALIZE %1
    S_ENDPGM 0, implicit %2
...


---

name:            fcanonicalize_fabs_f32_flush
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    fp32-input-denormals: false
    fp32-output-denormals: false

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX8-LABEL: name: fcanonicalize_fabs_f32_flush
    ; GFX8: liveins: $vgpr0
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX8-NEXT: [[V_MUL_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F32_e64 0, 1065353216, 2, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX8-NEXT: S_ENDPGM 0, implicit [[V_MUL_F32_e64_]]
    ;
    ; GFX9-LABEL: name: fcanonicalize_fabs_f32_flush
    ; GFX9: liveins: $vgpr0
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 2, [[COPY]], 2, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX10-LABEL: name: fcanonicalize_fabs_f32_flush
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX10-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 2, [[COPY]], 2, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX10-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX11-LABEL: name: fcanonicalize_fabs_f32_flush
    ; GFX11: liveins: $vgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX11-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 2, [[COPY]], 2, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = G_FABS %0
    %2:vgpr(f32) = G_FCANONICALIZE %1
    S_ENDPGM 0, implicit %2
...

---

name:            fcanonicalize_fneg_f32_denorm
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    fp32-input-denormals: true
    fp32-output-denormals: true

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX8-LABEL: name: fcanonicalize_fneg_f32_denorm
    ; GFX8: liveins: $vgpr0
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX8-NEXT: [[V_MUL_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F32_e64 0, 3212836864, 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX8-NEXT: S_ENDPGM 0, implicit [[V_MUL_F32_e64_]]
    ;
    ; GFX9-LABEL: name: fcanonicalize_fneg_f32_denorm
    ; GFX9: liveins: $vgpr0
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 1, [[COPY]], 1, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX10-LABEL: name: fcanonicalize_fneg_f32_denorm
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX10-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 1, [[COPY]], 1, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX10-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX11-LABEL: name: fcanonicalize_fneg_f32_denorm
    ; GFX11: liveins: $vgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX11-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 1, [[COPY]], 1, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(f32) = G_FNEG %0
    %2:vgpr(f32) = G_FCANONICALIZE %1
    S_ENDPGM 0, implicit %2
...

---

name:            fcanonicalize_fneg_f32_flush
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    fp32-input-denormals: false
    fp32-output-denormals: false

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX8-LABEL: name: fcanonicalize_fneg_f32_flush
    ; GFX8: liveins: $vgpr0
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX8-NEXT: [[V_MUL_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F32_e64 0, 3212836864, 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX8-NEXT: S_ENDPGM 0, implicit [[V_MUL_F32_e64_]]
    ;
    ; GFX9-LABEL: name: fcanonicalize_fneg_f32_flush
    ; GFX9: liveins: $vgpr0
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 1, [[COPY]], 1, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX10-LABEL: name: fcanonicalize_fneg_f32_flush
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX10-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 1, [[COPY]], 1, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX10-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX11-LABEL: name: fcanonicalize_fneg_f32_flush
    ; GFX11: liveins: $vgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX11-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 1, [[COPY]], 1, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(f32) = G_FNEG %0
    %2:vgpr(f32) = G_FCANONICALIZE %1
    S_ENDPGM 0, implicit %2
...

---

name:            fcanonicalize_fneg_fabs_f32_denorm
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    fp32-input-denormals: true
    fp32-output-denormals: true

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX8-LABEL: name: fcanonicalize_fneg_fabs_f32_denorm
    ; GFX8: liveins: $vgpr0
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX8-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 2147483648
    ; GFX8-NEXT: [[V_XOR_B32_e64_:%[0-9]+]]:vgpr_32 = V_XOR_B32_e64 [[S_MOV_B32_]], [[COPY]], implicit $exec
    ; GFX8-NEXT: [[V_MUL_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F32_e64 0, 1065353216, 2, [[V_XOR_B32_e64_]], 0, 0, implicit $mode, implicit $exec
    ; GFX8-NEXT: S_ENDPGM 0, implicit [[V_MUL_F32_e64_]]
    ;
    ; GFX9-LABEL: name: fcanonicalize_fneg_fabs_f32_denorm
    ; GFX9: liveins: $vgpr0
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 2147483648
    ; GFX9-NEXT: [[V_XOR_B32_e64_:%[0-9]+]]:vgpr_32 = V_XOR_B32_e64 [[S_MOV_B32_]], [[COPY]], implicit $exec
    ; GFX9-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 2, [[V_XOR_B32_e64_]], 2, [[V_XOR_B32_e64_]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX10-LABEL: name: fcanonicalize_fneg_fabs_f32_denorm
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX10-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 2147483648
    ; GFX10-NEXT: [[V_XOR_B32_e64_:%[0-9]+]]:vgpr_32 = V_XOR_B32_e64 [[S_MOV_B32_]], [[COPY]], implicit $exec
    ; GFX10-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 2, [[V_XOR_B32_e64_]], 2, [[V_XOR_B32_e64_]], 0, 0, implicit $mode, implicit $exec
    ; GFX10-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX11-LABEL: name: fcanonicalize_fneg_fabs_f32_denorm
    ; GFX11: liveins: $vgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX11-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 2147483648
    ; GFX11-NEXT: [[V_XOR_B32_e64_:%[0-9]+]]:vgpr_32 = V_XOR_B32_e64 [[S_MOV_B32_]], [[COPY]], implicit $exec
    ; GFX11-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 2, [[V_XOR_B32_e64_]], 2, [[V_XOR_B32_e64_]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(f32) = G_FNEG %0
    %2:vgpr(s32) = G_FABS %1
    %3:vgpr(f32) = G_FCANONICALIZE %2
    S_ENDPGM 0, implicit %3
...

---

name:            fcanonicalize_fneg_fabs_f32_flush
legalized:       true
regBankSelected: true
machineFunctionInfo:
  mode:
    fp32-input-denormals: false
    fp32-output-denormals: false

body: |
  bb.0:
    liveins: $vgpr0
    ; GFX8-LABEL: name: fcanonicalize_fneg_fabs_f32_flush
    ; GFX8: liveins: $vgpr0
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX8-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 2147483648
    ; GFX8-NEXT: [[V_XOR_B32_e64_:%[0-9]+]]:vgpr_32 = V_XOR_B32_e64 [[S_MOV_B32_]], [[COPY]], implicit $exec
    ; GFX8-NEXT: [[V_MUL_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F32_e64 0, 1065353216, 2, [[V_XOR_B32_e64_]], 0, 0, implicit $mode, implicit $exec
    ; GFX8-NEXT: S_ENDPGM 0, implicit [[V_MUL_F32_e64_]]
    ;
    ; GFX9-LABEL: name: fcanonicalize_fneg_fabs_f32_flush
    ; GFX9: liveins: $vgpr0
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 2147483648
    ; GFX9-NEXT: [[V_XOR_B32_e64_:%[0-9]+]]:vgpr_32 = V_XOR_B32_e64 [[S_MOV_B32_]], [[COPY]], implicit $exec
    ; GFX9-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 2, [[V_XOR_B32_e64_]], 2, [[V_XOR_B32_e64_]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX10-LABEL: name: fcanonicalize_fneg_fabs_f32_flush
    ; GFX10: liveins: $vgpr0
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX10-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 2147483648
    ; GFX10-NEXT: [[V_XOR_B32_e64_:%[0-9]+]]:vgpr_32 = V_XOR_B32_e64 [[S_MOV_B32_]], [[COPY]], implicit $exec
    ; GFX10-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 2, [[V_XOR_B32_e64_]], 2, [[V_XOR_B32_e64_]], 0, 0, implicit $mode, implicit $exec
    ; GFX10-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    ;
    ; GFX11-LABEL: name: fcanonicalize_fneg_fabs_f32_flush
    ; GFX11: liveins: $vgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX11-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 2147483648
    ; GFX11-NEXT: [[V_XOR_B32_e64_:%[0-9]+]]:vgpr_32 = V_XOR_B32_e64 [[S_MOV_B32_]], [[COPY]], implicit $exec
    ; GFX11-NEXT: [[V_MAX_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MAX_F32_e64 2, [[V_XOR_B32_e64_]], 2, [[V_XOR_B32_e64_]], 0, 0, implicit $mode, implicit $exec
    ; GFX11-NEXT: S_ENDPGM 0, implicit [[V_MAX_F32_e64_]]
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(f32) = G_FNEG %0
    %2:vgpr(s32) = G_FABS %1
    %3:vgpr(f32) = G_FCANONICALIZE %2
    S_ENDPGM 0, implicit %3
...
