# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=amdgcn -mcpu=tahiti -run-pass=instruction-select -verify-machineinstrs  -global-isel-abort=0 -o - %s | FileCheck -check-prefix=GFX6 %s
# RUN: llc -march=amdgcn -mcpu=hawaii -run-pass=instruction-select -verify-machineinstrs  -global-isel-abort=0 -o - %s | FileCheck -check-prefix=GFX7 %s
# RUN: llc -march=amdgcn -mcpu=fiji -run-pass=instruction-select -verify-machineinstrs  -global-isel-abort=0 -o - %s | FileCheck -check-prefix=GFX7 %s
# RUN: llc -march=amdgcn -mcpu=gfx900 -run-pass=instruction-select -verify-machineinstrs -global-isel-abort=0 -o - %s | FileCheck -check-prefix=GFX9 %s
# RUN: llc -march=amdgcn -mcpu=gfx1010 -run-pass=instruction-select -verify-machineinstrs -global-isel-abort=0 -o - %s | FileCheck -check-prefix=GFX9 %s
# RUN: llc -march=amdgcn -mcpu=gfx1100 -run-pass=instruction-select -verify-machineinstrs -global-isel-abort=0 -o - %s | FileCheck -check-prefix=GFX11 %s


---
name:            atomic_cmpxchg_s32_local
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2

    ; GFX6-LABEL: name: atomic_cmpxchg_s32_local
    ; GFX6: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX6-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; GFX6-NEXT: [[PRED_COPY2:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr2
    ; GFX6-NEXT: $m0 = S_MOV_B32 -1
    ; GFX6-NEXT: [[DS_CMPST_RTN_B32_:%[0-9]+]]:vgpr_32 = DS_CMPST_RTN_B32 [[PRED_COPY]], [[PRED_COPY1]], [[PRED_COPY2]], 0, 0, implicit $m0, implicit $exec :: (load store seq_cst (s32), addrspace 3)
    ; GFX6-NEXT: $vgpr0 = PRED_COPY [[DS_CMPST_RTN_B32_]]
    ; GFX7-LABEL: name: atomic_cmpxchg_s32_local
    ; GFX7: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX7-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; GFX7-NEXT: [[PRED_COPY2:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr2
    ; GFX7-NEXT: $m0 = S_MOV_B32 -1
    ; GFX7-NEXT: [[DS_CMPST_RTN_B32_:%[0-9]+]]:vgpr_32 = DS_CMPST_RTN_B32 [[PRED_COPY]], [[PRED_COPY1]], [[PRED_COPY2]], 0, 0, implicit $m0, implicit $exec :: (load store seq_cst (s32), addrspace 3)
    ; GFX7-NEXT: $vgpr0 = PRED_COPY [[DS_CMPST_RTN_B32_]]
    ; GFX9-LABEL: name: atomic_cmpxchg_s32_local
    ; GFX9: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX9-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; GFX9-NEXT: [[PRED_COPY2:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr2
    ; GFX9-NEXT: [[DS_CMPST_RTN_B32_gfx9_:%[0-9]+]]:vgpr_32 = DS_CMPST_RTN_B32_gfx9 [[PRED_COPY]], [[PRED_COPY1]], [[PRED_COPY2]], 0, 0, implicit $exec :: (load store seq_cst (s32), addrspace 3)
    ; GFX9-NEXT: $vgpr0 = PRED_COPY [[DS_CMPST_RTN_B32_gfx9_]]
    ; GFX11-LABEL: name: atomic_cmpxchg_s32_local
    ; GFX11: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX11-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; GFX11-NEXT: [[PRED_COPY2:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr2
    ; GFX11-NEXT: [[DS_CMPSTORE_RTN_B32_gfx9_:%[0-9]+]]:vgpr_32 = DS_CMPSTORE_RTN_B32_gfx9 [[PRED_COPY]], [[PRED_COPY2]], [[PRED_COPY1]], 0, 0, implicit $exec :: (load store seq_cst (s32), addrspace 3)
    ; GFX11-NEXT: $vgpr0 = PRED_COPY [[DS_CMPSTORE_RTN_B32_gfx9_]]
    %0:vgpr(p3) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vgpr(s32) = COPY $vgpr2
    %3:vgpr(s32) = G_ATOMIC_CMPXCHG %0, %1, %2 :: (load store seq_cst (s32), addrspace 3)
    $vgpr0 = COPY %3

...

---
name:            atomic_cmpxchg_s32_local_gep4
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2

    ; GFX6-LABEL: name: atomic_cmpxchg_s32_local_gep4
    ; GFX6: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX6-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; GFX6-NEXT: [[PRED_COPY2:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr2
    ; GFX6-NEXT: [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 4, implicit $exec
    ; GFX6-NEXT: [[V_ADD_CO_U32_e64_:%[0-9]+]]:vgpr_32, dead [[V_ADD_CO_U32_e64_1:%[0-9]+]]:sreg_64_xexec = V_ADD_CO_U32_e64 [[PRED_COPY]], [[V_MOV_B32_e32_]], 0, implicit $exec
    ; GFX6-NEXT: $m0 = S_MOV_B32 -1
    ; GFX6-NEXT: [[DS_CMPST_RTN_B32_:%[0-9]+]]:vgpr_32 = DS_CMPST_RTN_B32 [[V_ADD_CO_U32_e64_]], [[PRED_COPY1]], [[PRED_COPY2]], 0, 0, implicit $m0, implicit $exec :: (load store seq_cst (s32), addrspace 3)
    ; GFX6-NEXT: $vgpr0 = PRED_COPY [[DS_CMPST_RTN_B32_]]
    ; GFX7-LABEL: name: atomic_cmpxchg_s32_local_gep4
    ; GFX7: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX7-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; GFX7-NEXT: [[PRED_COPY2:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr2
    ; GFX7-NEXT: $m0 = S_MOV_B32 -1
    ; GFX7-NEXT: [[DS_CMPST_RTN_B32_:%[0-9]+]]:vgpr_32 = DS_CMPST_RTN_B32 [[PRED_COPY]], [[PRED_COPY1]], [[PRED_COPY2]], 4, 0, implicit $m0, implicit $exec :: (load store seq_cst (s32), addrspace 3)
    ; GFX7-NEXT: $vgpr0 = PRED_COPY [[DS_CMPST_RTN_B32_]]
    ; GFX9-LABEL: name: atomic_cmpxchg_s32_local_gep4
    ; GFX9: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX9-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; GFX9-NEXT: [[PRED_COPY2:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr2
    ; GFX9-NEXT: [[DS_CMPST_RTN_B32_gfx9_:%[0-9]+]]:vgpr_32 = DS_CMPST_RTN_B32_gfx9 [[PRED_COPY]], [[PRED_COPY1]], [[PRED_COPY2]], 4, 0, implicit $exec :: (load store seq_cst (s32), addrspace 3)
    ; GFX9-NEXT: $vgpr0 = PRED_COPY [[DS_CMPST_RTN_B32_gfx9_]]
    ; GFX11-LABEL: name: atomic_cmpxchg_s32_local_gep4
    ; GFX11: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX11-NEXT: [[PRED_COPY1:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr1
    ; GFX11-NEXT: [[PRED_COPY2:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr2
    ; GFX11-NEXT: [[DS_CMPSTORE_RTN_B32_gfx9_:%[0-9]+]]:vgpr_32 = DS_CMPSTORE_RTN_B32_gfx9 [[PRED_COPY]], [[PRED_COPY2]], [[PRED_COPY1]], 4, 0, implicit $exec :: (load store seq_cst (s32), addrspace 3)
    ; GFX11-NEXT: $vgpr0 = PRED_COPY [[DS_CMPSTORE_RTN_B32_gfx9_]]
    %0:vgpr(p3) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vgpr(s32) = COPY $vgpr2
    %3:vgpr(s32) = G_CONSTANT i32 4
    %4:vgpr(p3) = G_PTR_ADD %0, %3
    %5:vgpr(s32) = G_ATOMIC_CMPXCHG %4, %1, %2 :: (load store seq_cst (s32), addrspace 3)
    $vgpr0 = COPY %5

...

---
name:            atomic_cmpxchg_s64_local
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1_vgpr2, $vgpr3_vgpr4

    ; GFX6-LABEL: name: atomic_cmpxchg_s64_local
    ; GFX6: liveins: $vgpr0, $vgpr1_vgpr2, $vgpr3_vgpr4
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX6-NEXT: [[PRED_COPY1:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr1_vgpr2
    ; GFX6-NEXT: [[PRED_COPY2:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr3_vgpr4
    ; GFX6-NEXT: $m0 = S_MOV_B32 -1
    ; GFX6-NEXT: [[DS_CMPST_RTN_B64_:%[0-9]+]]:vreg_64 = DS_CMPST_RTN_B64 [[PRED_COPY]], [[PRED_COPY1]], [[PRED_COPY2]], 0, 0, implicit $m0, implicit $exec :: (load store seq_cst (s64), addrspace 3)
    ; GFX6-NEXT: $vgpr0_vgpr1 = PRED_COPY [[DS_CMPST_RTN_B64_]]
    ; GFX7-LABEL: name: atomic_cmpxchg_s64_local
    ; GFX7: liveins: $vgpr0, $vgpr1_vgpr2, $vgpr3_vgpr4
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX7-NEXT: [[PRED_COPY1:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr1_vgpr2
    ; GFX7-NEXT: [[PRED_COPY2:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr3_vgpr4
    ; GFX7-NEXT: $m0 = S_MOV_B32 -1
    ; GFX7-NEXT: [[DS_CMPST_RTN_B64_:%[0-9]+]]:vreg_64 = DS_CMPST_RTN_B64 [[PRED_COPY]], [[PRED_COPY1]], [[PRED_COPY2]], 0, 0, implicit $m0, implicit $exec :: (load store seq_cst (s64), addrspace 3)
    ; GFX7-NEXT: $vgpr0_vgpr1 = PRED_COPY [[DS_CMPST_RTN_B64_]]
    ; GFX9-LABEL: name: atomic_cmpxchg_s64_local
    ; GFX9: liveins: $vgpr0, $vgpr1_vgpr2, $vgpr3_vgpr4
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX9-NEXT: [[PRED_COPY1:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr1_vgpr2
    ; GFX9-NEXT: [[PRED_COPY2:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr3_vgpr4
    ; GFX9-NEXT: [[DS_CMPST_RTN_B64_gfx9_:%[0-9]+]]:vreg_64 = DS_CMPST_RTN_B64_gfx9 [[PRED_COPY]], [[PRED_COPY1]], [[PRED_COPY2]], 0, 0, implicit $exec :: (load store seq_cst (s64), addrspace 3)
    ; GFX9-NEXT: $vgpr0_vgpr1 = PRED_COPY [[DS_CMPST_RTN_B64_gfx9_]]
    ; GFX11-LABEL: name: atomic_cmpxchg_s64_local
    ; GFX11: liveins: $vgpr0, $vgpr1_vgpr2, $vgpr3_vgpr4
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX11-NEXT: [[PRED_COPY1:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr1_vgpr2
    ; GFX11-NEXT: [[PRED_COPY2:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr3_vgpr4
    ; GFX11-NEXT: [[DS_CMPSTORE_RTN_B64_gfx9_:%[0-9]+]]:vreg_64 = DS_CMPSTORE_RTN_B64_gfx9 [[PRED_COPY]], [[PRED_COPY2]], [[PRED_COPY1]], 0, 0, implicit $exec :: (load store seq_cst (s64), addrspace 3)
    ; GFX11-NEXT: $vgpr0_vgpr1 = PRED_COPY [[DS_CMPSTORE_RTN_B64_gfx9_]]
    %0:vgpr(p3) = COPY $vgpr0
    %1:vgpr(s64) = COPY $vgpr1_vgpr2
    %2:vgpr(s64) = COPY $vgpr3_vgpr4
    %3:vgpr(s64) = G_ATOMIC_CMPXCHG %0, %1, %2 :: (load store seq_cst (s64), addrspace 3)
    $vgpr0_vgpr1 = COPY %3

...

---
name:            atomic_cmpxchg_s64_local_gep4
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1_vgpr2, $vgpr3_vgpr4

    ; GFX6-LABEL: name: atomic_cmpxchg_s64_local_gep4
    ; GFX6: liveins: $vgpr0, $vgpr1_vgpr2, $vgpr3_vgpr4
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX6-NEXT: [[PRED_COPY1:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr1_vgpr2
    ; GFX6-NEXT: [[PRED_COPY2:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr3_vgpr4
    ; GFX6-NEXT: $m0 = S_MOV_B32 -1
    ; GFX6-NEXT: [[DS_CMPST_RTN_B64_:%[0-9]+]]:vreg_64 = DS_CMPST_RTN_B64 [[PRED_COPY]], [[PRED_COPY1]], [[PRED_COPY2]], 0, 0, implicit $m0, implicit $exec :: (load store seq_cst (s64), addrspace 3)
    ; GFX6-NEXT: $vgpr0_vgpr1 = PRED_COPY [[DS_CMPST_RTN_B64_]]
    ; GFX7-LABEL: name: atomic_cmpxchg_s64_local_gep4
    ; GFX7: liveins: $vgpr0, $vgpr1_vgpr2, $vgpr3_vgpr4
    ; GFX7-NEXT: {{  $}}
    ; GFX7-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX7-NEXT: [[PRED_COPY1:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr1_vgpr2
    ; GFX7-NEXT: [[PRED_COPY2:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr3_vgpr4
    ; GFX7-NEXT: $m0 = S_MOV_B32 -1
    ; GFX7-NEXT: [[DS_CMPST_RTN_B64_:%[0-9]+]]:vreg_64 = DS_CMPST_RTN_B64 [[PRED_COPY]], [[PRED_COPY1]], [[PRED_COPY2]], 0, 0, implicit $m0, implicit $exec :: (load store seq_cst (s64), addrspace 3)
    ; GFX7-NEXT: $vgpr0_vgpr1 = PRED_COPY [[DS_CMPST_RTN_B64_]]
    ; GFX9-LABEL: name: atomic_cmpxchg_s64_local_gep4
    ; GFX9: liveins: $vgpr0, $vgpr1_vgpr2, $vgpr3_vgpr4
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX9-NEXT: [[PRED_COPY1:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr1_vgpr2
    ; GFX9-NEXT: [[PRED_COPY2:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr3_vgpr4
    ; GFX9-NEXT: [[DS_CMPST_RTN_B64_gfx9_:%[0-9]+]]:vreg_64 = DS_CMPST_RTN_B64_gfx9 [[PRED_COPY]], [[PRED_COPY1]], [[PRED_COPY2]], 0, 0, implicit $exec :: (load store seq_cst (s64), addrspace 3)
    ; GFX9-NEXT: $vgpr0_vgpr1 = PRED_COPY [[DS_CMPST_RTN_B64_gfx9_]]
    ; GFX11-LABEL: name: atomic_cmpxchg_s64_local_gep4
    ; GFX11: liveins: $vgpr0, $vgpr1_vgpr2, $vgpr3_vgpr4
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[PRED_COPY:%[0-9]+]]:vgpr_32 = PRED_COPY $vgpr0
    ; GFX11-NEXT: [[PRED_COPY1:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr1_vgpr2
    ; GFX11-NEXT: [[PRED_COPY2:%[0-9]+]]:vreg_64 = PRED_COPY $vgpr3_vgpr4
    ; GFX11-NEXT: [[DS_CMPSTORE_RTN_B64_gfx9_:%[0-9]+]]:vreg_64 = DS_CMPSTORE_RTN_B64_gfx9 [[PRED_COPY]], [[PRED_COPY2]], [[PRED_COPY1]], 0, 0, implicit $exec :: (load store seq_cst (s64), addrspace 3)
    ; GFX11-NEXT: $vgpr0_vgpr1 = PRED_COPY [[DS_CMPSTORE_RTN_B64_gfx9_]]
    %0:vgpr(p3) = COPY $vgpr0
    %1:vgpr(s64) = COPY $vgpr1_vgpr2
    %2:vgpr(s64) = COPY $vgpr3_vgpr4
    %3:vgpr(s32) = G_CONSTANT i32 4
    %4:vgpr(p3) = G_PTR_ADD %0, %3
    %5:vgpr(s64) = G_ATOMIC_CMPXCHG %0, %1, %2 :: (load store seq_cst (s64), addrspace 3)
    $vgpr0_vgpr1 = COPY %5

...
