; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc -global-isel -mtriple=amdgcn -mcpu=fiji -stop-after=irtranslator -o - %s | FileCheck %s

define void @void_func_v2i65(<2 x i65> %arg0) #0 {
  ; CHECK-LABEL: name: void_func_v2i65
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $vgpr0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $vgpr1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(i32) = COPY $vgpr2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY $vgpr3
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(i32) = COPY $vgpr4
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(i32) = COPY $vgpr5
  ; CHECK-NEXT:   [[MV:%[0-9]+]]:_(s96) = G_MERGE_VALUES [[COPY]](i32), [[COPY1]](i32), [[COPY2]](i32)
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i65) = G_TRUNC [[MV]](s96)
  ; CHECK-NEXT:   [[MV1:%[0-9]+]]:_(s96) = G_MERGE_VALUES [[COPY3]](i32), [[COPY4]](i32), [[COPY5]](i32)
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(i65) = G_TRUNC [[MV1]](s96)
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<2 x i65>) = G_BUILD_VECTOR [[TRUNC]](i65), [[TRUNC1]](i65)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(p1) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR]](<2 x i65>), [[DEF]](p1) :: (store (<2 x i65>) into `ptr addrspace(1) poison`, align 32, addrspace 1)
  ; CHECK-NEXT:   SI_RETURN
  store <2 x i65> %arg0, ptr addrspace(1) poison
  ret void
}
