# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-mesa-mesa3d -mcpu=fiji -O0 -run-pass=legalizer %s -o - | FileCheck --check-prefix=GCN %s
# RUN: llc -mtriple=amdgcn-mesa-mesa3d -mcpu=gfx900 -O0 -run-pass=legalizer %s -o - | FileCheck --check-prefix=GCN %s
# RUN: llc -mtriple=amdgcn-mesa-mesa3d -mcpu=gfx1010 -O0 -run-pass=legalizer %s -o - | FileCheck --check-prefix=GCN %s
...
---
name:            test_ubfx_s32
body: |
  bb.0.entry:
    liveins: $vgpr0, $vgpr1, $vgpr2

    ; GCN-LABEL: name: test_ubfx_s32
    ; GCN: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: %copy:_(s32) = COPY $vgpr0
    ; GCN-NEXT: %offset:_(s32) = COPY $vgpr1
    ; GCN-NEXT: %width:_(s32) = COPY $vgpr2
    ; GCN-NEXT: %ubfx:_(s32) = G_UBFX %copy, %offset(s32), %width
    ; GCN-NEXT: $vgpr0 = COPY %ubfx(s32)
    %copy:_(s32) = COPY $vgpr0
    %offset:_(s32) = COPY $vgpr1
    %width:_(s32) = COPY $vgpr2
    %ubfx:_(s32) = G_UBFX %copy, %offset(s32), %width
    $vgpr0 = COPY %ubfx(s32)
...

---
name:            test_ubfx_s64
body: |
  bb.0.entry:
    liveins: $vgpr0_vgpr1, $vgpr2, $vgpr3

    ; GCN-LABEL: name: test_ubfx_s64
    ; GCN: liveins: $vgpr0_vgpr1, $vgpr2, $vgpr3
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: %copy:_(s64) = COPY $vgpr0_vgpr1
    ; GCN-NEXT: %offset:_(s32) = COPY $vgpr2
    ; GCN-NEXT: %width:_(s32) = COPY $vgpr3
    ; GCN-NEXT: %ubfx:_(s64) = G_UBFX %copy, %offset(s32), %width
    ; GCN-NEXT: $vgpr0_vgpr1 = COPY %ubfx(s64)
    %copy:_(s64) = COPY $vgpr0_vgpr1
    %offset:_(s32) = COPY $vgpr2
    %width:_(s32) = COPY $vgpr3
    %ubfx:_(s64) = G_UBFX %copy, %offset(s32), %width
    $vgpr0_vgpr1 = COPY %ubfx(s64)
...

---
name:            test_ubfx_s8
body: |
  bb.0.entry:
    liveins: $vgpr0, $vgpr1, $vgpr2

    ; GCN-LABEL: name: test_ubfx_s8
    ; GCN: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GCN-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GCN-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $vgpr2
    ; GCN-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY1]](s32)
    ; GCN-NEXT: [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 255
    ; GCN-NEXT: [[AND:%[0-9]+]]:_(s16) = G_AND [[TRUNC]], [[C]]
    ; GCN-NEXT: [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[COPY2]](s32)
    ; GCN-NEXT: [[AND1:%[0-9]+]]:_(s16) = G_AND [[TRUNC1]], [[C]]
    ; GCN-NEXT: [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
    ; GCN-NEXT: [[UBFX:%[0-9]+]]:_(s16) = G_UBFX [[TRUNC2]], [[AND]](s16), [[AND1]]
    ; GCN-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[UBFX]](s16)
    ; GCN-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; GCN-NEXT: [[AND2:%[0-9]+]]:_(s32) = G_AND [[ANYEXT]], [[C1]]
    ; GCN-NEXT: $vgpr0 = COPY [[AND2]](s32)
    %0:_(s32) = COPY $vgpr0
    %1:_(s32) = COPY $vgpr1
    %2:_(s32) = COPY $vgpr2
    %copy:_(s8) = G_TRUNC %0
    %offset:_(s8) = G_TRUNC %1
    %width:_(s8) = G_TRUNC %2
    %ubfx:_(s8) = G_UBFX %copy, %offset, %width
    %4:_(s32) = G_ZEXT %ubfx
    $vgpr0 = COPY %4
...

---
name:            test_ubfx_s16
body: |
  bb.0.entry:
    liveins: $vgpr0, $vgpr1, $vgpr2

    ; GCN-LABEL: name: test_ubfx_s16
    ; GCN: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GCN-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GCN-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $vgpr2
    ; GCN-NEXT: %copy:_(s16) = G_TRUNC [[COPY]](s32)
    ; GCN-NEXT: %offset:_(s16) = G_TRUNC [[COPY1]](s32)
    ; GCN-NEXT: %width:_(s16) = G_TRUNC [[COPY2]](s32)
    ; GCN-NEXT: %sbfx:_(s16) = G_UBFX %copy, %offset(s16), %width
    ; GCN-NEXT: [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT %sbfx(s16)
    ; GCN-NEXT: $vgpr0 = COPY [[ZEXT]](s32)
    %0:_(s32) = COPY $vgpr0
    %1:_(s32) = COPY $vgpr1
    %2:_(s32) = COPY $vgpr2
    %copy:_(s16) = G_TRUNC %0
    %offset:_(s16) = G_TRUNC %1
    %width:_(s16) = G_TRUNC %2
    %sbfx:_(s16) = G_UBFX %copy, %offset, %width
    %4:_(s32) = G_ZEXT %sbfx
    $vgpr0 = COPY %4
...

