# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=amdgcn-mesa-mesa3d -mcpu=tahiti -run-pass=legalizer %s -o - | FileCheck %s --check-prefix=TAHITI
# RUN: llc -O0 -mtriple=amdgcn-mesa-mesa3d -mcpu=fiji -run-pass=legalizer %s -o - | FileCheck %s --check-prefix=FIJI

---
name: test_implicit_def_s1025
body: |
  bb.0:
    ; TAHITI-LABEL: name: test_implicit_def_s1025
    ; TAHITI: [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 0
    ; TAHITI-NEXT: [[C1:%[0-9]+]]:_(i32) = G_CONSTANT i32 1
    ; TAHITI-NEXT: [[SHL:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C1]](i32)
    ; TAHITI-NEXT: [[OR:%[0-9]+]]:_(i32) = G_OR [[C]], [[SHL]]
    ; TAHITI-NEXT: [[C2:%[0-9]+]]:_(i32) = G_CONSTANT i32 2
    ; TAHITI-NEXT: [[SHL1:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C2]](i32)
    ; TAHITI-NEXT: [[OR1:%[0-9]+]]:_(i32) = G_OR [[OR]], [[SHL1]]
    ; TAHITI-NEXT: [[C3:%[0-9]+]]:_(i32) = G_CONSTANT i32 3
    ; TAHITI-NEXT: [[SHL2:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C3]](i32)
    ; TAHITI-NEXT: [[OR2:%[0-9]+]]:_(i32) = G_OR [[OR1]], [[SHL2]]
    ; TAHITI-NEXT: [[C4:%[0-9]+]]:_(i32) = G_CONSTANT i32 4
    ; TAHITI-NEXT: [[SHL3:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C4]](i32)
    ; TAHITI-NEXT: [[OR3:%[0-9]+]]:_(i32) = G_OR [[OR2]], [[SHL3]]
    ; TAHITI-NEXT: [[C5:%[0-9]+]]:_(i32) = G_CONSTANT i32 5
    ; TAHITI-NEXT: [[SHL4:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C5]](i32)
    ; TAHITI-NEXT: [[OR4:%[0-9]+]]:_(i32) = G_OR [[OR3]], [[SHL4]]
    ; TAHITI-NEXT: [[C6:%[0-9]+]]:_(i32) = G_CONSTANT i32 6
    ; TAHITI-NEXT: [[SHL5:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C6]](i32)
    ; TAHITI-NEXT: [[OR5:%[0-9]+]]:_(i32) = G_OR [[OR4]], [[SHL5]]
    ; TAHITI-NEXT: [[C7:%[0-9]+]]:_(i32) = G_CONSTANT i32 7
    ; TAHITI-NEXT: [[SHL6:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C7]](i32)
    ; TAHITI-NEXT: [[OR6:%[0-9]+]]:_(i32) = G_OR [[OR5]], [[SHL6]]
    ; TAHITI-NEXT: [[C8:%[0-9]+]]:_(i32) = G_CONSTANT i32 8
    ; TAHITI-NEXT: [[SHL7:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C8]](i32)
    ; TAHITI-NEXT: [[OR7:%[0-9]+]]:_(i32) = G_OR [[OR6]], [[SHL7]]
    ; TAHITI-NEXT: [[C9:%[0-9]+]]:_(i32) = G_CONSTANT i32 9
    ; TAHITI-NEXT: [[SHL8:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C9]](i32)
    ; TAHITI-NEXT: [[OR8:%[0-9]+]]:_(i32) = G_OR [[OR7]], [[SHL8]]
    ; TAHITI-NEXT: [[C10:%[0-9]+]]:_(i32) = G_CONSTANT i32 10
    ; TAHITI-NEXT: [[SHL9:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C10]](i32)
    ; TAHITI-NEXT: [[OR9:%[0-9]+]]:_(i32) = G_OR [[OR8]], [[SHL9]]
    ; TAHITI-NEXT: [[C11:%[0-9]+]]:_(i32) = G_CONSTANT i32 11
    ; TAHITI-NEXT: [[SHL10:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C11]](i32)
    ; TAHITI-NEXT: [[OR10:%[0-9]+]]:_(i32) = G_OR [[OR9]], [[SHL10]]
    ; TAHITI-NEXT: [[C12:%[0-9]+]]:_(i32) = G_CONSTANT i32 12
    ; TAHITI-NEXT: [[SHL11:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C12]](i32)
    ; TAHITI-NEXT: [[OR11:%[0-9]+]]:_(i32) = G_OR [[OR10]], [[SHL11]]
    ; TAHITI-NEXT: [[C13:%[0-9]+]]:_(i32) = G_CONSTANT i32 13
    ; TAHITI-NEXT: [[SHL12:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C13]](i32)
    ; TAHITI-NEXT: [[OR12:%[0-9]+]]:_(i32) = G_OR [[OR11]], [[SHL12]]
    ; TAHITI-NEXT: [[C14:%[0-9]+]]:_(i32) = G_CONSTANT i32 14
    ; TAHITI-NEXT: [[SHL13:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C14]](i32)
    ; TAHITI-NEXT: [[OR13:%[0-9]+]]:_(i32) = G_OR [[OR12]], [[SHL13]]
    ; TAHITI-NEXT: [[C15:%[0-9]+]]:_(i32) = G_CONSTANT i32 15
    ; TAHITI-NEXT: [[SHL14:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C15]](i32)
    ; TAHITI-NEXT: [[OR14:%[0-9]+]]:_(i32) = G_OR [[OR13]], [[SHL14]]
    ; TAHITI-NEXT: [[C16:%[0-9]+]]:_(i32) = G_CONSTANT i32 16
    ; TAHITI-NEXT: [[SHL15:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C16]](i32)
    ; TAHITI-NEXT: [[OR15:%[0-9]+]]:_(i32) = G_OR [[OR14]], [[SHL15]]
    ; TAHITI-NEXT: [[C17:%[0-9]+]]:_(i32) = G_CONSTANT i32 17
    ; TAHITI-NEXT: [[SHL16:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C17]](i32)
    ; TAHITI-NEXT: [[OR16:%[0-9]+]]:_(i32) = G_OR [[OR15]], [[SHL16]]
    ; TAHITI-NEXT: [[C18:%[0-9]+]]:_(i32) = G_CONSTANT i32 18
    ; TAHITI-NEXT: [[SHL17:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C18]](i32)
    ; TAHITI-NEXT: [[OR17:%[0-9]+]]:_(i32) = G_OR [[OR16]], [[SHL17]]
    ; TAHITI-NEXT: [[C19:%[0-9]+]]:_(i32) = G_CONSTANT i32 19
    ; TAHITI-NEXT: [[SHL18:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C19]](i32)
    ; TAHITI-NEXT: [[OR18:%[0-9]+]]:_(i32) = G_OR [[OR17]], [[SHL18]]
    ; TAHITI-NEXT: [[C20:%[0-9]+]]:_(i32) = G_CONSTANT i32 20
    ; TAHITI-NEXT: [[SHL19:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C20]](i32)
    ; TAHITI-NEXT: [[OR19:%[0-9]+]]:_(i32) = G_OR [[OR18]], [[SHL19]]
    ; TAHITI-NEXT: [[C21:%[0-9]+]]:_(i32) = G_CONSTANT i32 21
    ; TAHITI-NEXT: [[SHL20:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C21]](i32)
    ; TAHITI-NEXT: [[OR20:%[0-9]+]]:_(i32) = G_OR [[OR19]], [[SHL20]]
    ; TAHITI-NEXT: [[C22:%[0-9]+]]:_(i32) = G_CONSTANT i32 22
    ; TAHITI-NEXT: [[SHL21:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C22]](i32)
    ; TAHITI-NEXT: [[OR21:%[0-9]+]]:_(i32) = G_OR [[OR20]], [[SHL21]]
    ; TAHITI-NEXT: [[C23:%[0-9]+]]:_(i32) = G_CONSTANT i32 23
    ; TAHITI-NEXT: [[SHL22:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C23]](i32)
    ; TAHITI-NEXT: [[OR22:%[0-9]+]]:_(i32) = G_OR [[OR21]], [[SHL22]]
    ; TAHITI-NEXT: [[C24:%[0-9]+]]:_(i32) = G_CONSTANT i32 24
    ; TAHITI-NEXT: [[SHL23:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C24]](i32)
    ; TAHITI-NEXT: [[OR23:%[0-9]+]]:_(i32) = G_OR [[OR22]], [[SHL23]]
    ; TAHITI-NEXT: [[C25:%[0-9]+]]:_(i32) = G_CONSTANT i32 25
    ; TAHITI-NEXT: [[SHL24:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C25]](i32)
    ; TAHITI-NEXT: [[OR24:%[0-9]+]]:_(i32) = G_OR [[OR23]], [[SHL24]]
    ; TAHITI-NEXT: [[C26:%[0-9]+]]:_(i32) = G_CONSTANT i32 26
    ; TAHITI-NEXT: [[SHL25:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C26]](i32)
    ; TAHITI-NEXT: [[OR25:%[0-9]+]]:_(i32) = G_OR [[OR24]], [[SHL25]]
    ; TAHITI-NEXT: [[C27:%[0-9]+]]:_(i32) = G_CONSTANT i32 27
    ; TAHITI-NEXT: [[SHL26:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C27]](i32)
    ; TAHITI-NEXT: [[OR26:%[0-9]+]]:_(i32) = G_OR [[OR25]], [[SHL26]]
    ; TAHITI-NEXT: [[C28:%[0-9]+]]:_(i32) = G_CONSTANT i32 28
    ; TAHITI-NEXT: [[SHL27:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C28]](i32)
    ; TAHITI-NEXT: [[OR27:%[0-9]+]]:_(i32) = G_OR [[OR26]], [[SHL27]]
    ; TAHITI-NEXT: [[C29:%[0-9]+]]:_(i32) = G_CONSTANT i32 29
    ; TAHITI-NEXT: [[SHL28:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C29]](i32)
    ; TAHITI-NEXT: [[OR28:%[0-9]+]]:_(i32) = G_OR [[OR27]], [[SHL28]]
    ; TAHITI-NEXT: [[C30:%[0-9]+]]:_(i32) = G_CONSTANT i32 30
    ; TAHITI-NEXT: [[SHL29:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C30]](i32)
    ; TAHITI-NEXT: [[OR29:%[0-9]+]]:_(i32) = G_OR [[OR28]], [[SHL29]]
    ; TAHITI-NEXT: [[C31:%[0-9]+]]:_(i32) = G_CONSTANT i32 31
    ; TAHITI-NEXT: [[SHL30:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C31]](i32)
    ; TAHITI-NEXT: [[OR30:%[0-9]+]]:_(s32) = G_OR [[OR29]], [[SHL30]]
    ; TAHITI-NEXT: $vgpr0 = COPY [[OR30]](s32)
    ;
    ; FIJI-LABEL: name: test_implicit_def_s1025
    ; FIJI: [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 0
    ; FIJI-NEXT: [[C1:%[0-9]+]]:_(i32) = G_CONSTANT i32 1
    ; FIJI-NEXT: [[SHL:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C1]](i32)
    ; FIJI-NEXT: [[OR:%[0-9]+]]:_(i32) = G_OR [[C]], [[SHL]]
    ; FIJI-NEXT: [[C2:%[0-9]+]]:_(i32) = G_CONSTANT i32 2
    ; FIJI-NEXT: [[SHL1:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C2]](i32)
    ; FIJI-NEXT: [[OR1:%[0-9]+]]:_(i32) = G_OR [[OR]], [[SHL1]]
    ; FIJI-NEXT: [[C3:%[0-9]+]]:_(i32) = G_CONSTANT i32 3
    ; FIJI-NEXT: [[SHL2:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C3]](i32)
    ; FIJI-NEXT: [[OR2:%[0-9]+]]:_(i32) = G_OR [[OR1]], [[SHL2]]
    ; FIJI-NEXT: [[C4:%[0-9]+]]:_(i32) = G_CONSTANT i32 4
    ; FIJI-NEXT: [[SHL3:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C4]](i32)
    ; FIJI-NEXT: [[OR3:%[0-9]+]]:_(i32) = G_OR [[OR2]], [[SHL3]]
    ; FIJI-NEXT: [[C5:%[0-9]+]]:_(i32) = G_CONSTANT i32 5
    ; FIJI-NEXT: [[SHL4:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C5]](i32)
    ; FIJI-NEXT: [[OR4:%[0-9]+]]:_(i32) = G_OR [[OR3]], [[SHL4]]
    ; FIJI-NEXT: [[C6:%[0-9]+]]:_(i32) = G_CONSTANT i32 6
    ; FIJI-NEXT: [[SHL5:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C6]](i32)
    ; FIJI-NEXT: [[OR5:%[0-9]+]]:_(i32) = G_OR [[OR4]], [[SHL5]]
    ; FIJI-NEXT: [[C7:%[0-9]+]]:_(i32) = G_CONSTANT i32 7
    ; FIJI-NEXT: [[SHL6:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C7]](i32)
    ; FIJI-NEXT: [[OR6:%[0-9]+]]:_(i32) = G_OR [[OR5]], [[SHL6]]
    ; FIJI-NEXT: [[C8:%[0-9]+]]:_(i32) = G_CONSTANT i32 8
    ; FIJI-NEXT: [[SHL7:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C8]](i32)
    ; FIJI-NEXT: [[OR7:%[0-9]+]]:_(i32) = G_OR [[OR6]], [[SHL7]]
    ; FIJI-NEXT: [[C9:%[0-9]+]]:_(i32) = G_CONSTANT i32 9
    ; FIJI-NEXT: [[SHL8:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C9]](i32)
    ; FIJI-NEXT: [[OR8:%[0-9]+]]:_(i32) = G_OR [[OR7]], [[SHL8]]
    ; FIJI-NEXT: [[C10:%[0-9]+]]:_(i32) = G_CONSTANT i32 10
    ; FIJI-NEXT: [[SHL9:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C10]](i32)
    ; FIJI-NEXT: [[OR9:%[0-9]+]]:_(i32) = G_OR [[OR8]], [[SHL9]]
    ; FIJI-NEXT: [[C11:%[0-9]+]]:_(i32) = G_CONSTANT i32 11
    ; FIJI-NEXT: [[SHL10:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C11]](i32)
    ; FIJI-NEXT: [[OR10:%[0-9]+]]:_(i32) = G_OR [[OR9]], [[SHL10]]
    ; FIJI-NEXT: [[C12:%[0-9]+]]:_(i32) = G_CONSTANT i32 12
    ; FIJI-NEXT: [[SHL11:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C12]](i32)
    ; FIJI-NEXT: [[OR11:%[0-9]+]]:_(i32) = G_OR [[OR10]], [[SHL11]]
    ; FIJI-NEXT: [[C13:%[0-9]+]]:_(i32) = G_CONSTANT i32 13
    ; FIJI-NEXT: [[SHL12:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C13]](i32)
    ; FIJI-NEXT: [[OR12:%[0-9]+]]:_(i32) = G_OR [[OR11]], [[SHL12]]
    ; FIJI-NEXT: [[C14:%[0-9]+]]:_(i32) = G_CONSTANT i32 14
    ; FIJI-NEXT: [[SHL13:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C14]](i32)
    ; FIJI-NEXT: [[OR13:%[0-9]+]]:_(i32) = G_OR [[OR12]], [[SHL13]]
    ; FIJI-NEXT: [[C15:%[0-9]+]]:_(i32) = G_CONSTANT i32 15
    ; FIJI-NEXT: [[SHL14:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C15]](i32)
    ; FIJI-NEXT: [[OR14:%[0-9]+]]:_(i32) = G_OR [[OR13]], [[SHL14]]
    ; FIJI-NEXT: [[C16:%[0-9]+]]:_(i32) = G_CONSTANT i32 16
    ; FIJI-NEXT: [[SHL15:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C16]](i32)
    ; FIJI-NEXT: [[OR15:%[0-9]+]]:_(i32) = G_OR [[OR14]], [[SHL15]]
    ; FIJI-NEXT: [[C17:%[0-9]+]]:_(i32) = G_CONSTANT i32 17
    ; FIJI-NEXT: [[SHL16:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C17]](i32)
    ; FIJI-NEXT: [[OR16:%[0-9]+]]:_(i32) = G_OR [[OR15]], [[SHL16]]
    ; FIJI-NEXT: [[C18:%[0-9]+]]:_(i32) = G_CONSTANT i32 18
    ; FIJI-NEXT: [[SHL17:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C18]](i32)
    ; FIJI-NEXT: [[OR17:%[0-9]+]]:_(i32) = G_OR [[OR16]], [[SHL17]]
    ; FIJI-NEXT: [[C19:%[0-9]+]]:_(i32) = G_CONSTANT i32 19
    ; FIJI-NEXT: [[SHL18:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C19]](i32)
    ; FIJI-NEXT: [[OR18:%[0-9]+]]:_(i32) = G_OR [[OR17]], [[SHL18]]
    ; FIJI-NEXT: [[C20:%[0-9]+]]:_(i32) = G_CONSTANT i32 20
    ; FIJI-NEXT: [[SHL19:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C20]](i32)
    ; FIJI-NEXT: [[OR19:%[0-9]+]]:_(i32) = G_OR [[OR18]], [[SHL19]]
    ; FIJI-NEXT: [[C21:%[0-9]+]]:_(i32) = G_CONSTANT i32 21
    ; FIJI-NEXT: [[SHL20:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C21]](i32)
    ; FIJI-NEXT: [[OR20:%[0-9]+]]:_(i32) = G_OR [[OR19]], [[SHL20]]
    ; FIJI-NEXT: [[C22:%[0-9]+]]:_(i32) = G_CONSTANT i32 22
    ; FIJI-NEXT: [[SHL21:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C22]](i32)
    ; FIJI-NEXT: [[OR21:%[0-9]+]]:_(i32) = G_OR [[OR20]], [[SHL21]]
    ; FIJI-NEXT: [[C23:%[0-9]+]]:_(i32) = G_CONSTANT i32 23
    ; FIJI-NEXT: [[SHL22:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C23]](i32)
    ; FIJI-NEXT: [[OR22:%[0-9]+]]:_(i32) = G_OR [[OR21]], [[SHL22]]
    ; FIJI-NEXT: [[C24:%[0-9]+]]:_(i32) = G_CONSTANT i32 24
    ; FIJI-NEXT: [[SHL23:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C24]](i32)
    ; FIJI-NEXT: [[OR23:%[0-9]+]]:_(i32) = G_OR [[OR22]], [[SHL23]]
    ; FIJI-NEXT: [[C25:%[0-9]+]]:_(i32) = G_CONSTANT i32 25
    ; FIJI-NEXT: [[SHL24:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C25]](i32)
    ; FIJI-NEXT: [[OR24:%[0-9]+]]:_(i32) = G_OR [[OR23]], [[SHL24]]
    ; FIJI-NEXT: [[C26:%[0-9]+]]:_(i32) = G_CONSTANT i32 26
    ; FIJI-NEXT: [[SHL25:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C26]](i32)
    ; FIJI-NEXT: [[OR25:%[0-9]+]]:_(i32) = G_OR [[OR24]], [[SHL25]]
    ; FIJI-NEXT: [[C27:%[0-9]+]]:_(i32) = G_CONSTANT i32 27
    ; FIJI-NEXT: [[SHL26:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C27]](i32)
    ; FIJI-NEXT: [[OR26:%[0-9]+]]:_(i32) = G_OR [[OR25]], [[SHL26]]
    ; FIJI-NEXT: [[C28:%[0-9]+]]:_(i32) = G_CONSTANT i32 28
    ; FIJI-NEXT: [[SHL27:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C28]](i32)
    ; FIJI-NEXT: [[OR27:%[0-9]+]]:_(i32) = G_OR [[OR26]], [[SHL27]]
    ; FIJI-NEXT: [[C29:%[0-9]+]]:_(i32) = G_CONSTANT i32 29
    ; FIJI-NEXT: [[SHL28:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C29]](i32)
    ; FIJI-NEXT: [[OR28:%[0-9]+]]:_(i32) = G_OR [[OR27]], [[SHL28]]
    ; FIJI-NEXT: [[C30:%[0-9]+]]:_(i32) = G_CONSTANT i32 30
    ; FIJI-NEXT: [[SHL29:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C30]](i32)
    ; FIJI-NEXT: [[OR29:%[0-9]+]]:_(i32) = G_OR [[OR28]], [[SHL29]]
    ; FIJI-NEXT: [[C31:%[0-9]+]]:_(i32) = G_CONSTANT i32 31
    ; FIJI-NEXT: [[SHL30:%[0-9]+]]:_(i32) = G_SHL [[C]], [[C31]](i32)
    ; FIJI-NEXT: [[OR30:%[0-9]+]]:_(s32) = G_OR [[OR29]], [[SHL30]]
    ; FIJI-NEXT: $vgpr0 = COPY [[OR30]](s32)
    %0:_(s1025) = G_IMPLICIT_DEF
    %1:_(s32) = G_TRUNC %0
    $vgpr0 = COPY %1
...
