# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-mesa-mesa3d -mcpu=tahiti -O0 -run-pass=legalizer -o - %s | FileCheck -check-prefix=GFX6 %s
# RUN: llc -mtriple=amdgcn-mesa-mesa3d -mcpu=fiji -O0 -run-pass=legalizer -o - %s | FileCheck -check-prefix=GFX8 %s
# RUN: llc -mtriple=amdgcn-mesa-mesa3d -mcpu=gfx900 -O0 -run-pass=legalizer -o - %s | FileCheck -check-prefix=GFX9 %s
# RUN: llc -mtriple=amdgcn-mesa-mesa3d -mcpu=gfx1010 -O0 -run-pass=legalizer -o - %s | FileCheck -check-prefix=GFX10 %s
# RUN: llc -mtriple=amdgcn-mesa-mesa3d -mcpu=gfx1100 -mattr=-real-true16 -O0 -run-pass=legalizer -o - %s | FileCheck -check-prefixes=GFX10 %s

---
name: test_srem_s32
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1

    ; GFX6-LABEL: name: test_srem_s32
    ; GFX6: liveins: $vgpr0, $vgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX6-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX6-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX6-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[COPY]], [[C]](s32)
    ; GFX6-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[COPY1]], [[C]](s32)
    ; GFX6-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY]], [[ASHR]]
    ; GFX6-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[COPY1]], [[ASHR1]]
    ; GFX6-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX6-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX6-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX6-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX6-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX6-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX6-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX6-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX6-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX6-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX6-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX6-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX6-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX6-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX6-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX6-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX6-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX6-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX6-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX6-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX6-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX6-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX6-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX6-NEXT: $vgpr0 = COPY [[SUB4]](s32)
    ;
    ; GFX8-LABEL: name: test_srem_s32
    ; GFX8: liveins: $vgpr0, $vgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX8-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX8-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX8-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[COPY]], [[C]](s32)
    ; GFX8-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[COPY1]], [[C]](s32)
    ; GFX8-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY]], [[ASHR]]
    ; GFX8-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[COPY1]], [[ASHR1]]
    ; GFX8-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX8-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX8-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX8-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX8-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX8-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX8-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX8-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX8-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX8-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX8-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX8-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX8-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX8-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX8-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX8-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX8-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX8-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX8-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX8-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX8-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX8-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX8-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX8-NEXT: $vgpr0 = COPY [[SUB4]](s32)
    ;
    ; GFX9-LABEL: name: test_srem_s32
    ; GFX9: liveins: $vgpr0, $vgpr1
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX9-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX9-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[COPY]], [[C]](s32)
    ; GFX9-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[COPY1]], [[C]](s32)
    ; GFX9-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY]], [[ASHR]]
    ; GFX9-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[COPY1]], [[ASHR1]]
    ; GFX9-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX9-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX9-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX9-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX9-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX9-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX9-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX9-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX9-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX9-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX9-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX9-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX9-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX9-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX9-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX9-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX9-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX9-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX9-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX9-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX9-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX9-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX9-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX9-NEXT: $vgpr0 = COPY [[SUB4]](s32)
    ;
    ; GFX10-LABEL: name: test_srem_s32
    ; GFX10: liveins: $vgpr0, $vgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX10-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX10-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX10-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[COPY]], [[C]](s32)
    ; GFX10-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[COPY1]], [[C]](s32)
    ; GFX10-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY]], [[ASHR]]
    ; GFX10-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[COPY1]], [[ASHR1]]
    ; GFX10-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX10-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX10-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX10-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX10-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX10-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX10-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX10-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX10-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX10-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX10-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX10-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX10-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX10-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX10-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX10-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX10-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX10-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX10-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX10-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX10-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX10-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX10-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX10-NEXT: $vgpr0 = COPY [[SUB4]](s32)
    %0:_(s32) = COPY $vgpr0
    %1:_(s32) = COPY $vgpr1
    %2:_(s32) = G_SREM %0, %1
    $vgpr0 = COPY %2
...

---
name: test_srem_v2s32
body: |
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2_vgpr3

    ; GFX6-LABEL: name: test_srem_v2s32
    ; GFX6: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[COPY:%[0-9]+]]:_(<2 x s32>) = COPY $vgpr0_vgpr1
    ; GFX6-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s32>) = COPY $vgpr2_vgpr3
    ; GFX6-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](<2 x s32>)
    ; GFX6-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY1]](<2 x s32>)
    ; GFX6-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX6-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[UV]], [[C]](s32)
    ; GFX6-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[UV2]], [[C]](s32)
    ; GFX6-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[UV]], [[ASHR]]
    ; GFX6-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[UV2]], [[ASHR1]]
    ; GFX6-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX6-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX6-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX6-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX6-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX6-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX6-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX6-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX6-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX6-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX6-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX6-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX6-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX6-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX6-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX6-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX6-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX6-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX6-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX6-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX6-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX6-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX6-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX6-NEXT: [[ASHR2:%[0-9]+]]:_(s32) = G_ASHR [[UV1]], [[C]](s32)
    ; GFX6-NEXT: [[ASHR3:%[0-9]+]]:_(s32) = G_ASHR [[UV3]], [[C]](s32)
    ; GFX6-NEXT: [[ADD3:%[0-9]+]]:_(s32) = G_ADD [[UV1]], [[ASHR2]]
    ; GFX6-NEXT: [[ADD4:%[0-9]+]]:_(s32) = G_ADD [[UV3]], [[ASHR3]]
    ; GFX6-NEXT: [[XOR3:%[0-9]+]]:_(s32) = G_XOR [[ADD3]], [[ASHR2]]
    ; GFX6-NEXT: [[XOR4:%[0-9]+]]:_(s32) = G_XOR [[ADD4]], [[ASHR3]]
    ; GFX6-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[XOR4]](s32)
    ; GFX6-NEXT: [[AMDGPU_RCP_IFLAG1:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP1]](f32)
    ; GFX6-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG1]], [[C1]]
    ; GFX6-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL1]](f32)
    ; GFX6-NEXT: [[SUB5:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR4]]
    ; GFX6-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[SUB5]], [[FPTOUI1]]
    ; GFX6-NEXT: [[UMULH2:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI1]], [[MUL2]]
    ; GFX6-NEXT: [[ADD5:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI1]], [[UMULH2]]
    ; GFX6-NEXT: [[UMULH3:%[0-9]+]]:_(s32) = G_UMULH [[XOR3]], [[ADD5]]
    ; GFX6-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[UMULH3]], [[XOR4]]
    ; GFX6-NEXT: [[SUB6:%[0-9]+]]:_(i32) = G_SUB [[XOR3]], [[MUL3]]
    ; GFX6-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB6]](i32), [[XOR4]]
    ; GFX6-NEXT: [[SUB7:%[0-9]+]]:_(s32) = G_SUB [[SUB6]], [[XOR4]]
    ; GFX6-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SUB7]], [[SUB6]]
    ; GFX6-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT2]](s32), [[XOR4]]
    ; GFX6-NEXT: [[SUB8:%[0-9]+]]:_(s32) = G_SUB [[SELECT2]], [[XOR4]]
    ; GFX6-NEXT: [[SELECT3:%[0-9]+]]:_(s32) = G_SELECT [[ICMP3]](s1), [[SUB8]], [[SELECT2]]
    ; GFX6-NEXT: [[XOR5:%[0-9]+]]:_(s32) = G_XOR [[SELECT3]], [[ASHR2]]
    ; GFX6-NEXT: [[SUB9:%[0-9]+]]:_(s32) = G_SUB [[XOR5]], [[ASHR2]]
    ; GFX6-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s32>) = G_BUILD_VECTOR [[SUB4]](s32), [[SUB9]](s32)
    ; GFX6-NEXT: $vgpr0_vgpr1 = COPY [[BUILD_VECTOR]](<2 x s32>)
    ;
    ; GFX8-LABEL: name: test_srem_v2s32
    ; GFX8: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:_(<2 x s32>) = COPY $vgpr0_vgpr1
    ; GFX8-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s32>) = COPY $vgpr2_vgpr3
    ; GFX8-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](<2 x s32>)
    ; GFX8-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY1]](<2 x s32>)
    ; GFX8-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX8-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[UV]], [[C]](s32)
    ; GFX8-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[UV2]], [[C]](s32)
    ; GFX8-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[UV]], [[ASHR]]
    ; GFX8-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[UV2]], [[ASHR1]]
    ; GFX8-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX8-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX8-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX8-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX8-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX8-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX8-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX8-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX8-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX8-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX8-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX8-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX8-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX8-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX8-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX8-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX8-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX8-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX8-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX8-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX8-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX8-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX8-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX8-NEXT: [[ASHR2:%[0-9]+]]:_(s32) = G_ASHR [[UV1]], [[C]](s32)
    ; GFX8-NEXT: [[ASHR3:%[0-9]+]]:_(s32) = G_ASHR [[UV3]], [[C]](s32)
    ; GFX8-NEXT: [[ADD3:%[0-9]+]]:_(s32) = G_ADD [[UV1]], [[ASHR2]]
    ; GFX8-NEXT: [[ADD4:%[0-9]+]]:_(s32) = G_ADD [[UV3]], [[ASHR3]]
    ; GFX8-NEXT: [[XOR3:%[0-9]+]]:_(s32) = G_XOR [[ADD3]], [[ASHR2]]
    ; GFX8-NEXT: [[XOR4:%[0-9]+]]:_(s32) = G_XOR [[ADD4]], [[ASHR3]]
    ; GFX8-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[XOR4]](s32)
    ; GFX8-NEXT: [[AMDGPU_RCP_IFLAG1:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP1]](f32)
    ; GFX8-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG1]], [[C1]]
    ; GFX8-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL1]](f32)
    ; GFX8-NEXT: [[SUB5:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR4]]
    ; GFX8-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[SUB5]], [[FPTOUI1]]
    ; GFX8-NEXT: [[UMULH2:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI1]], [[MUL2]]
    ; GFX8-NEXT: [[ADD5:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI1]], [[UMULH2]]
    ; GFX8-NEXT: [[UMULH3:%[0-9]+]]:_(s32) = G_UMULH [[XOR3]], [[ADD5]]
    ; GFX8-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[UMULH3]], [[XOR4]]
    ; GFX8-NEXT: [[SUB6:%[0-9]+]]:_(i32) = G_SUB [[XOR3]], [[MUL3]]
    ; GFX8-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB6]](i32), [[XOR4]]
    ; GFX8-NEXT: [[SUB7:%[0-9]+]]:_(s32) = G_SUB [[SUB6]], [[XOR4]]
    ; GFX8-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SUB7]], [[SUB6]]
    ; GFX8-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT2]](s32), [[XOR4]]
    ; GFX8-NEXT: [[SUB8:%[0-9]+]]:_(s32) = G_SUB [[SELECT2]], [[XOR4]]
    ; GFX8-NEXT: [[SELECT3:%[0-9]+]]:_(s32) = G_SELECT [[ICMP3]](s1), [[SUB8]], [[SELECT2]]
    ; GFX8-NEXT: [[XOR5:%[0-9]+]]:_(s32) = G_XOR [[SELECT3]], [[ASHR2]]
    ; GFX8-NEXT: [[SUB9:%[0-9]+]]:_(s32) = G_SUB [[XOR5]], [[ASHR2]]
    ; GFX8-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s32>) = G_BUILD_VECTOR [[SUB4]](s32), [[SUB9]](s32)
    ; GFX8-NEXT: $vgpr0_vgpr1 = COPY [[BUILD_VECTOR]](<2 x s32>)
    ;
    ; GFX9-LABEL: name: test_srem_v2s32
    ; GFX9: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:_(<2 x s32>) = COPY $vgpr0_vgpr1
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s32>) = COPY $vgpr2_vgpr3
    ; GFX9-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](<2 x s32>)
    ; GFX9-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY1]](<2 x s32>)
    ; GFX9-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX9-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[UV]], [[C]](s32)
    ; GFX9-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[UV2]], [[C]](s32)
    ; GFX9-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[UV]], [[ASHR]]
    ; GFX9-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[UV2]], [[ASHR1]]
    ; GFX9-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX9-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX9-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX9-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX9-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX9-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX9-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX9-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX9-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX9-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX9-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX9-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX9-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX9-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX9-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX9-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX9-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX9-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX9-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX9-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX9-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX9-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX9-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX9-NEXT: [[ASHR2:%[0-9]+]]:_(s32) = G_ASHR [[UV1]], [[C]](s32)
    ; GFX9-NEXT: [[ASHR3:%[0-9]+]]:_(s32) = G_ASHR [[UV3]], [[C]](s32)
    ; GFX9-NEXT: [[ADD3:%[0-9]+]]:_(s32) = G_ADD [[UV1]], [[ASHR2]]
    ; GFX9-NEXT: [[ADD4:%[0-9]+]]:_(s32) = G_ADD [[UV3]], [[ASHR3]]
    ; GFX9-NEXT: [[XOR3:%[0-9]+]]:_(s32) = G_XOR [[ADD3]], [[ASHR2]]
    ; GFX9-NEXT: [[XOR4:%[0-9]+]]:_(s32) = G_XOR [[ADD4]], [[ASHR3]]
    ; GFX9-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[XOR4]](s32)
    ; GFX9-NEXT: [[AMDGPU_RCP_IFLAG1:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP1]](f32)
    ; GFX9-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG1]], [[C1]]
    ; GFX9-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL1]](f32)
    ; GFX9-NEXT: [[SUB5:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR4]]
    ; GFX9-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[SUB5]], [[FPTOUI1]]
    ; GFX9-NEXT: [[UMULH2:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI1]], [[MUL2]]
    ; GFX9-NEXT: [[ADD5:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI1]], [[UMULH2]]
    ; GFX9-NEXT: [[UMULH3:%[0-9]+]]:_(s32) = G_UMULH [[XOR3]], [[ADD5]]
    ; GFX9-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[UMULH3]], [[XOR4]]
    ; GFX9-NEXT: [[SUB6:%[0-9]+]]:_(i32) = G_SUB [[XOR3]], [[MUL3]]
    ; GFX9-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB6]](i32), [[XOR4]]
    ; GFX9-NEXT: [[SUB7:%[0-9]+]]:_(s32) = G_SUB [[SUB6]], [[XOR4]]
    ; GFX9-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SUB7]], [[SUB6]]
    ; GFX9-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT2]](s32), [[XOR4]]
    ; GFX9-NEXT: [[SUB8:%[0-9]+]]:_(s32) = G_SUB [[SELECT2]], [[XOR4]]
    ; GFX9-NEXT: [[SELECT3:%[0-9]+]]:_(s32) = G_SELECT [[ICMP3]](s1), [[SUB8]], [[SELECT2]]
    ; GFX9-NEXT: [[XOR5:%[0-9]+]]:_(s32) = G_XOR [[SELECT3]], [[ASHR2]]
    ; GFX9-NEXT: [[SUB9:%[0-9]+]]:_(s32) = G_SUB [[XOR5]], [[ASHR2]]
    ; GFX9-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s32>) = G_BUILD_VECTOR [[SUB4]](s32), [[SUB9]](s32)
    ; GFX9-NEXT: $vgpr0_vgpr1 = COPY [[BUILD_VECTOR]](<2 x s32>)
    ;
    ; GFX10-LABEL: name: test_srem_v2s32
    ; GFX10: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:_(<2 x s32>) = COPY $vgpr0_vgpr1
    ; GFX10-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s32>) = COPY $vgpr2_vgpr3
    ; GFX10-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](<2 x s32>)
    ; GFX10-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY1]](<2 x s32>)
    ; GFX10-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX10-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[UV]], [[C]](s32)
    ; GFX10-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[UV2]], [[C]](s32)
    ; GFX10-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[UV]], [[ASHR]]
    ; GFX10-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[UV2]], [[ASHR1]]
    ; GFX10-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX10-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX10-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX10-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX10-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX10-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX10-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX10-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX10-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX10-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX10-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX10-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX10-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX10-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX10-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX10-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX10-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX10-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX10-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX10-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX10-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX10-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX10-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX10-NEXT: [[ASHR2:%[0-9]+]]:_(s32) = G_ASHR [[UV1]], [[C]](s32)
    ; GFX10-NEXT: [[ASHR3:%[0-9]+]]:_(s32) = G_ASHR [[UV3]], [[C]](s32)
    ; GFX10-NEXT: [[ADD3:%[0-9]+]]:_(s32) = G_ADD [[UV1]], [[ASHR2]]
    ; GFX10-NEXT: [[ADD4:%[0-9]+]]:_(s32) = G_ADD [[UV3]], [[ASHR3]]
    ; GFX10-NEXT: [[XOR3:%[0-9]+]]:_(s32) = G_XOR [[ADD3]], [[ASHR2]]
    ; GFX10-NEXT: [[XOR4:%[0-9]+]]:_(s32) = G_XOR [[ADD4]], [[ASHR3]]
    ; GFX10-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[XOR4]](s32)
    ; GFX10-NEXT: [[AMDGPU_RCP_IFLAG1:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP1]](f32)
    ; GFX10-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG1]], [[C1]]
    ; GFX10-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL1]](f32)
    ; GFX10-NEXT: [[SUB5:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR4]]
    ; GFX10-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[SUB5]], [[FPTOUI1]]
    ; GFX10-NEXT: [[UMULH2:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI1]], [[MUL2]]
    ; GFX10-NEXT: [[ADD5:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI1]], [[UMULH2]]
    ; GFX10-NEXT: [[UMULH3:%[0-9]+]]:_(s32) = G_UMULH [[XOR3]], [[ADD5]]
    ; GFX10-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[UMULH3]], [[XOR4]]
    ; GFX10-NEXT: [[SUB6:%[0-9]+]]:_(i32) = G_SUB [[XOR3]], [[MUL3]]
    ; GFX10-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB6]](i32), [[XOR4]]
    ; GFX10-NEXT: [[SUB7:%[0-9]+]]:_(s32) = G_SUB [[SUB6]], [[XOR4]]
    ; GFX10-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SUB7]], [[SUB6]]
    ; GFX10-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT2]](s32), [[XOR4]]
    ; GFX10-NEXT: [[SUB8:%[0-9]+]]:_(s32) = G_SUB [[SELECT2]], [[XOR4]]
    ; GFX10-NEXT: [[SELECT3:%[0-9]+]]:_(s32) = G_SELECT [[ICMP3]](s1), [[SUB8]], [[SELECT2]]
    ; GFX10-NEXT: [[XOR5:%[0-9]+]]:_(s32) = G_XOR [[SELECT3]], [[ASHR2]]
    ; GFX10-NEXT: [[SUB9:%[0-9]+]]:_(s32) = G_SUB [[XOR5]], [[ASHR2]]
    ; GFX10-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s32>) = G_BUILD_VECTOR [[SUB4]](s32), [[SUB9]](s32)
    ; GFX10-NEXT: $vgpr0_vgpr1 = COPY [[BUILD_VECTOR]](<2 x s32>)
    %0:_(<2 x s32>) = COPY $vgpr0_vgpr1
    %1:_(<2 x s32>) = COPY $vgpr2_vgpr3
    %2:_(<2 x s32>) = G_SREM %0, %1
    $vgpr0_vgpr1 = COPY %2
...

---
name: test_srem_s64
body: |
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2_vgpr3

    ; GFX6-LABEL: name: test_srem_s64
    ; GFX6: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $vgpr0_vgpr1
    ; GFX6-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $vgpr2_vgpr3
    ; GFX6-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; GFX6-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[COPY]], [[C]](s32)
    ; GFX6-NEXT: [[ASHR1:%[0-9]+]]:_(s64) = G_ASHR [[COPY1]], [[C]](s32)
    ; GFX6-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; GFX6-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX6-NEXT: [[UADDO:%[0-9]+]]:_(s32), [[UADDO1:%[0-9]+]]:_(i1) = G_UADDO [[UV]], [[UV2]]
    ; GFX6-NEXT: [[UADDE:%[0-9]+]]:_(s32), [[UADDE1:%[0-9]+]]:_(i1) = G_UADDE [[UV1]], [[UV3]], [[UADDO1]]
    ; GFX6-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO]](s32), [[UADDE]](s32)
    ; GFX6-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY1]](s64)
    ; GFX6-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR1]](s64)
    ; GFX6-NEXT: [[UADDO2:%[0-9]+]]:_(s32), [[UADDO3:%[0-9]+]]:_(i1) = G_UADDO [[UV4]], [[UV6]]
    ; GFX6-NEXT: [[UADDE2:%[0-9]+]]:_(s32), [[UADDE3:%[0-9]+]]:_(i1) = G_UADDE [[UV5]], [[UV7]], [[UADDO3]]
    ; GFX6-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO2]](s32), [[UADDE2]](s32)
    ; GFX6-NEXT: [[XOR:%[0-9]+]]:_(s64) = G_XOR [[MV]], [[ASHR]]
    ; GFX6-NEXT: [[XOR1:%[0-9]+]]:_(s64) = G_XOR [[MV1]], [[ASHR1]]
    ; GFX6-NEXT: [[UV8:%[0-9]+]]:_(i32), [[UV9:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX6-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[UV8]](i32)
    ; GFX6-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[UV9]](i32)
    ; GFX6-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F800000
    ; GFX6-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP1]], [[C1]]
    ; GFX6-NEXT: [[FADD:%[0-9]+]]:_(f32) = G_FADD [[FMUL]], [[UITOFP]]
    ; GFX6-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD]](f32)
    ; GFX6-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x5F7FFFFC
    ; GFX6-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX6-NEXT: [[C3:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x2F800000
    ; GFX6-NEXT: [[FMUL2:%[0-9]+]]:_(f32) = G_FMUL [[FMUL1]], [[C3]]
    ; GFX6-NEXT: [[INTRINSIC_TRUNC:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL2]]
    ; GFX6-NEXT: [[C4:%[0-9]+]]:_(s32) = G_FCONSTANT float f0xCF800000
    ; GFX6-NEXT: [[FMUL3:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC]], [[C4]]
    ; GFX6-NEXT: [[FADD1:%[0-9]+]]:_(f32) = G_FADD [[FMUL3]], [[FMUL1]]
    ; GFX6-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD1]](f32)
    ; GFX6-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC]](f32)
    ; GFX6-NEXT: [[C5:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; GFX6-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX6-NEXT: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX6-NEXT: [[USUBO:%[0-9]+]]:_(s32), [[USUBO1:%[0-9]+]]:_(i1) = G_USUBO [[UV10]], [[UV12]]
    ; GFX6-NEXT: [[USUBE:%[0-9]+]]:_(s32), [[USUBE1:%[0-9]+]]:_(i1) = G_USUBE [[UV11]], [[UV13]], [[USUBO1]]
    ; GFX6-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[FPTOUI]]
    ; GFX6-NEXT: [[UMULH:%[0-9]+]]:_(i32) = G_UMULH [[USUBO]], [[FPTOUI]]
    ; GFX6-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[FPTOUI1]]
    ; GFX6-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[USUBE]], [[FPTOUI]]
    ; GFX6-NEXT: [[ADD:%[0-9]+]]:_(i32) = G_ADD [[UMULH]], [[MUL1]]
    ; GFX6-NEXT: [[ADD1:%[0-9]+]]:_(i32) = G_ADD [[ADD]], [[MUL2]]
    ; GFX6-NEXT: [[UMULH1:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX6-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI]], [[ADD1]]
    ; GFX6-NEXT: [[MUL4:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[MUL]]
    ; GFX6-NEXT: [[UADDO4:%[0-9]+]]:_(i32), [[UADDO5:%[0-9]+]]:_(i1) = G_UADDO [[UMULH1]], [[MUL3]]
    ; GFX6-NEXT: [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO5]](i1)
    ; GFX6-NEXT: [[UADDO6:%[0-9]+]]:_(i32), [[UADDO7:%[0-9]+]]:_(i1) = G_UADDO [[UADDO4]], [[MUL4]]
    ; GFX6-NEXT: [[ZEXT1:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO7]](i1)
    ; GFX6-NEXT: [[ADD2:%[0-9]+]]:_(i32) = G_ADD [[ZEXT]], [[ZEXT1]]
    ; GFX6-NEXT: [[UMULH2:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[MUL]]
    ; GFX6-NEXT: [[UMULH3:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[ADD1]]
    ; GFX6-NEXT: [[MUL5:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[ADD1]]
    ; GFX6-NEXT: [[UADDO8:%[0-9]+]]:_(i32), [[UADDO9:%[0-9]+]]:_(i1) = G_UADDO [[UMULH2]], [[UMULH3]]
    ; GFX6-NEXT: [[ZEXT2:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO9]](i1)
    ; GFX6-NEXT: [[UADDO10:%[0-9]+]]:_(i32), [[UADDO11:%[0-9]+]]:_(i1) = G_UADDO [[UADDO8]], [[MUL5]]
    ; GFX6-NEXT: [[ZEXT3:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO11]](i1)
    ; GFX6-NEXT: [[ADD3:%[0-9]+]]:_(i32) = G_ADD [[ZEXT2]], [[ZEXT3]]
    ; GFX6-NEXT: [[UADDO12:%[0-9]+]]:_(i32), [[UADDO13:%[0-9]+]]:_(i1) = G_UADDO [[UADDO10]], [[ADD2]]
    ; GFX6-NEXT: [[ZEXT4:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO13]](i1)
    ; GFX6-NEXT: [[ADD4:%[0-9]+]]:_(i32) = G_ADD [[ADD3]], [[ZEXT4]]
    ; GFX6-NEXT: [[UMULH4:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[ADD1]]
    ; GFX6-NEXT: [[ADD5:%[0-9]+]]:_(i32) = G_ADD [[UMULH4]], [[ADD4]]
    ; GFX6-NEXT: [[UADDO14:%[0-9]+]]:_(s32), [[UADDO15:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI]], [[UADDO12]]
    ; GFX6-NEXT: [[UADDE4:%[0-9]+]]:_(s32), [[UADDE5:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI1]], [[ADD5]], [[UADDO15]]
    ; GFX6-NEXT: [[MUL6:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[UADDO14]]
    ; GFX6-NEXT: [[UMULH5:%[0-9]+]]:_(i32) = G_UMULH [[USUBO]], [[UADDO14]]
    ; GFX6-NEXT: [[MUL7:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[UADDE4]]
    ; GFX6-NEXT: [[MUL8:%[0-9]+]]:_(i32) = G_MUL [[USUBE]], [[UADDO14]]
    ; GFX6-NEXT: [[ADD6:%[0-9]+]]:_(i32) = G_ADD [[UMULH5]], [[MUL7]]
    ; GFX6-NEXT: [[ADD7:%[0-9]+]]:_(i32) = G_ADD [[ADD6]], [[MUL8]]
    ; GFX6-NEXT: [[UMULH6:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[MUL6]]
    ; GFX6-NEXT: [[MUL9:%[0-9]+]]:_(i32) = G_MUL [[UADDO14]], [[ADD7]]
    ; GFX6-NEXT: [[MUL10:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[MUL6]]
    ; GFX6-NEXT: [[UADDO16:%[0-9]+]]:_(i32), [[UADDO17:%[0-9]+]]:_(i1) = G_UADDO [[UMULH6]], [[MUL9]]
    ; GFX6-NEXT: [[ZEXT5:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO17]](i1)
    ; GFX6-NEXT: [[UADDO18:%[0-9]+]]:_(i32), [[UADDO19:%[0-9]+]]:_(i1) = G_UADDO [[UADDO16]], [[MUL10]]
    ; GFX6-NEXT: [[ZEXT6:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO19]](i1)
    ; GFX6-NEXT: [[ADD8:%[0-9]+]]:_(i32) = G_ADD [[ZEXT5]], [[ZEXT6]]
    ; GFX6-NEXT: [[UMULH7:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[MUL6]]
    ; GFX6-NEXT: [[UMULH8:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[ADD7]]
    ; GFX6-NEXT: [[MUL11:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[ADD7]]
    ; GFX6-NEXT: [[UADDO20:%[0-9]+]]:_(i32), [[UADDO21:%[0-9]+]]:_(i1) = G_UADDO [[UMULH7]], [[UMULH8]]
    ; GFX6-NEXT: [[ZEXT7:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO21]](i1)
    ; GFX6-NEXT: [[UADDO22:%[0-9]+]]:_(i32), [[UADDO23:%[0-9]+]]:_(i1) = G_UADDO [[UADDO20]], [[MUL11]]
    ; GFX6-NEXT: [[ZEXT8:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO23]](i1)
    ; GFX6-NEXT: [[ADD9:%[0-9]+]]:_(i32) = G_ADD [[ZEXT7]], [[ZEXT8]]
    ; GFX6-NEXT: [[UADDO24:%[0-9]+]]:_(i32), [[UADDO25:%[0-9]+]]:_(i1) = G_UADDO [[UADDO22]], [[ADD8]]
    ; GFX6-NEXT: [[ZEXT9:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO25]](i1)
    ; GFX6-NEXT: [[ADD10:%[0-9]+]]:_(i32) = G_ADD [[ADD9]], [[ZEXT9]]
    ; GFX6-NEXT: [[UMULH9:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[ADD7]]
    ; GFX6-NEXT: [[ADD11:%[0-9]+]]:_(i32) = G_ADD [[UMULH9]], [[ADD10]]
    ; GFX6-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX6-NEXT: [[UADDO26:%[0-9]+]]:_(s32), [[UADDO27:%[0-9]+]]:_(s1) = G_UADDO [[UADDO14]], [[UADDO24]]
    ; GFX6-NEXT: [[UADDE6:%[0-9]+]]:_(s32), [[UADDE7:%[0-9]+]]:_(s1) = G_UADDE [[UADDE4]], [[ADD11]], [[UADDO27]]
    ; GFX6-NEXT: [[UV14:%[0-9]+]]:_(i32), [[UV15:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX6-NEXT: [[UV16:%[0-9]+]]:_(i32), [[UV17:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX6-NEXT: [[UMULH10:%[0-9]+]]:_(i32) = G_UMULH [[UV16]], [[UADDO26]]
    ; GFX6-NEXT: [[MUL12:%[0-9]+]]:_(i32) = G_MUL [[UV16]], [[UADDE6]]
    ; GFX6-NEXT: [[MUL13:%[0-9]+]]:_(i32) = G_MUL [[UV17]], [[UADDO26]]
    ; GFX6-NEXT: [[UADDO28:%[0-9]+]]:_(i32), [[UADDO29:%[0-9]+]]:_(i1) = G_UADDO [[UMULH10]], [[MUL12]]
    ; GFX6-NEXT: [[ZEXT10:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO29]](i1)
    ; GFX6-NEXT: [[UADDO30:%[0-9]+]]:_(i32), [[UADDO31:%[0-9]+]]:_(i1) = G_UADDO [[UADDO28]], [[MUL13]]
    ; GFX6-NEXT: [[ZEXT11:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO31]](i1)
    ; GFX6-NEXT: [[ADD12:%[0-9]+]]:_(i32) = G_ADD [[ZEXT10]], [[ZEXT11]]
    ; GFX6-NEXT: [[UMULH11:%[0-9]+]]:_(i32) = G_UMULH [[UV17]], [[UADDO26]]
    ; GFX6-NEXT: [[UMULH12:%[0-9]+]]:_(i32) = G_UMULH [[UV16]], [[UADDE6]]
    ; GFX6-NEXT: [[MUL14:%[0-9]+]]:_(i32) = G_MUL [[UV17]], [[UADDE6]]
    ; GFX6-NEXT: [[UADDO32:%[0-9]+]]:_(i32), [[UADDO33:%[0-9]+]]:_(i1) = G_UADDO [[UMULH11]], [[UMULH12]]
    ; GFX6-NEXT: [[ZEXT12:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO33]](i1)
    ; GFX6-NEXT: [[UADDO34:%[0-9]+]]:_(i32), [[UADDO35:%[0-9]+]]:_(i1) = G_UADDO [[UADDO32]], [[MUL14]]
    ; GFX6-NEXT: [[ZEXT13:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO35]](i1)
    ; GFX6-NEXT: [[ADD13:%[0-9]+]]:_(i32) = G_ADD [[ZEXT12]], [[ZEXT13]]
    ; GFX6-NEXT: [[UADDO36:%[0-9]+]]:_(i32), [[UADDO37:%[0-9]+]]:_(i1) = G_UADDO [[UADDO34]], [[ADD12]]
    ; GFX6-NEXT: [[ZEXT14:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO37]](i1)
    ; GFX6-NEXT: [[ADD14:%[0-9]+]]:_(i32) = G_ADD [[ADD13]], [[ZEXT14]]
    ; GFX6-NEXT: [[UMULH13:%[0-9]+]]:_(i32) = G_UMULH [[UV17]], [[UADDE6]]
    ; GFX6-NEXT: [[ADD15:%[0-9]+]]:_(i32) = G_ADD [[UMULH13]], [[ADD14]]
    ; GFX6-NEXT: [[UV18:%[0-9]+]]:_(i32), [[UV19:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX6-NEXT: [[MUL15:%[0-9]+]]:_(i32) = G_MUL [[UV18]], [[UADDO36]]
    ; GFX6-NEXT: [[UMULH14:%[0-9]+]]:_(i32) = G_UMULH [[UV18]], [[UADDO36]]
    ; GFX6-NEXT: [[MUL16:%[0-9]+]]:_(i32) = G_MUL [[UV18]], [[ADD15]]
    ; GFX6-NEXT: [[MUL17:%[0-9]+]]:_(i32) = G_MUL [[UV19]], [[UADDO36]]
    ; GFX6-NEXT: [[ADD16:%[0-9]+]]:_(i32) = G_ADD [[UMULH14]], [[MUL16]]
    ; GFX6-NEXT: [[ADD17:%[0-9]+]]:_(i32) = G_ADD [[ADD16]], [[MUL17]]
    ; GFX6-NEXT: [[USUBO2:%[0-9]+]]:_(s32), [[USUBO3:%[0-9]+]]:_(s1) = G_USUBO [[UV14]], [[MUL15]]
    ; GFX6-NEXT: [[USUBE2:%[0-9]+]]:_(s32), [[USUBE3:%[0-9]+]]:_(s1) = G_USUBE [[UV15]], [[ADD17]], [[USUBO3]]
    ; GFX6-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[UV15]], [[ADD17]]
    ; GFX6-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO2]](s32), [[USUBE2]](s32)
    ; GFX6-NEXT: [[UV20:%[0-9]+]]:_(i32), [[UV21:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX6-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE2]](s32), [[UV21]]
    ; GFX6-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[ICMP]](s1)
    ; GFX6-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO2]](s32), [[UV20]]
    ; GFX6-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[ICMP1]](s1)
    ; GFX6-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE2]](s32), [[UV21]]
    ; GFX6-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SEXT1]], [[SEXT]]
    ; GFX6-NEXT: [[USUBO4:%[0-9]+]]:_(s32), [[USUBO5:%[0-9]+]]:_(s1) = G_USUBO [[USUBO2]], [[UV20]]
    ; GFX6-NEXT: [[USUBE4:%[0-9]+]]:_(s32), [[USUBE5:%[0-9]+]]:_(s1) = G_USUBE [[SUB]], [[UV21]], [[USUBO3]]
    ; GFX6-NEXT: [[USUBE6:%[0-9]+]]:_(s32), [[USUBE7:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[C6]], [[USUBO5]]
    ; GFX6-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO4]](s32), [[USUBE6]](s32)
    ; GFX6-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE6]](s32), [[UV21]]
    ; GFX6-NEXT: [[SEXT2:%[0-9]+]]:_(s32) = G_SEXT [[ICMP3]](s1)
    ; GFX6-NEXT: [[ICMP4:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO4]](s32), [[UV20]]
    ; GFX6-NEXT: [[SEXT3:%[0-9]+]]:_(s32) = G_SEXT [[ICMP4]](s1)
    ; GFX6-NEXT: [[ICMP5:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE6]](s32), [[UV21]]
    ; GFX6-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP5]](s1), [[SEXT3]], [[SEXT2]]
    ; GFX6-NEXT: [[USUBO6:%[0-9]+]]:_(s32), [[USUBO7:%[0-9]+]]:_(s1) = G_USUBO [[USUBO4]], [[UV20]]
    ; GFX6-NEXT: [[USUBE8:%[0-9]+]]:_(s32), [[USUBE9:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[UV21]], [[USUBO5]]
    ; GFX6-NEXT: [[USUBE10:%[0-9]+]]:_(s32), [[USUBE11:%[0-9]+]]:_(s1) = G_USUBE [[USUBE8]], [[C6]], [[USUBO7]]
    ; GFX6-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO6]](s32), [[USUBE10]](s32)
    ; GFX6-NEXT: [[ICMP6:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT1]](s32), [[C6]]
    ; GFX6-NEXT: [[SELECT2:%[0-9]+]]:_(s64) = G_SELECT [[ICMP6]](s1), [[MV4]], [[MV3]]
    ; GFX6-NEXT: [[ICMP7:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT]](s32), [[C6]]
    ; GFX6-NEXT: [[SELECT3:%[0-9]+]]:_(s64) = G_SELECT [[ICMP7]](s1), [[SELECT2]], [[MV2]]
    ; GFX6-NEXT: [[XOR2:%[0-9]+]]:_(s64) = G_XOR [[SELECT3]], [[ASHR]]
    ; GFX6-NEXT: [[UV22:%[0-9]+]]:_(s32), [[UV23:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR2]](s64)
    ; GFX6-NEXT: [[UV24:%[0-9]+]]:_(s32), [[UV25:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX6-NEXT: [[USUBO8:%[0-9]+]]:_(s32), [[USUBO9:%[0-9]+]]:_(i1) = G_USUBO [[UV22]], [[UV24]]
    ; GFX6-NEXT: [[USUBE12:%[0-9]+]]:_(s32), [[USUBE13:%[0-9]+]]:_(i1) = G_USUBE [[UV23]], [[UV25]], [[USUBO9]]
    ; GFX6-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO8]](s32), [[USUBE12]](s32)
    ; GFX6-NEXT: $vgpr0_vgpr1 = COPY [[MV5]](s64)
    ;
    ; GFX8-LABEL: name: test_srem_s64
    ; GFX8: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $vgpr0_vgpr1
    ; GFX8-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $vgpr2_vgpr3
    ; GFX8-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; GFX8-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[COPY]], [[C]](s32)
    ; GFX8-NEXT: [[ASHR1:%[0-9]+]]:_(s64) = G_ASHR [[COPY1]], [[C]](s32)
    ; GFX8-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; GFX8-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX8-NEXT: [[UADDO:%[0-9]+]]:_(s32), [[UADDO1:%[0-9]+]]:_(i1) = G_UADDO [[UV]], [[UV2]]
    ; GFX8-NEXT: [[UADDE:%[0-9]+]]:_(s32), [[UADDE1:%[0-9]+]]:_(i1) = G_UADDE [[UV1]], [[UV3]], [[UADDO1]]
    ; GFX8-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO]](s32), [[UADDE]](s32)
    ; GFX8-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY1]](s64)
    ; GFX8-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR1]](s64)
    ; GFX8-NEXT: [[UADDO2:%[0-9]+]]:_(s32), [[UADDO3:%[0-9]+]]:_(i1) = G_UADDO [[UV4]], [[UV6]]
    ; GFX8-NEXT: [[UADDE2:%[0-9]+]]:_(s32), [[UADDE3:%[0-9]+]]:_(i1) = G_UADDE [[UV5]], [[UV7]], [[UADDO3]]
    ; GFX8-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO2]](s32), [[UADDE2]](s32)
    ; GFX8-NEXT: [[XOR:%[0-9]+]]:_(s64) = G_XOR [[MV]], [[ASHR]]
    ; GFX8-NEXT: [[XOR1:%[0-9]+]]:_(s64) = G_XOR [[MV1]], [[ASHR1]]
    ; GFX8-NEXT: [[UV8:%[0-9]+]]:_(i32), [[UV9:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX8-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[UV8]](i32)
    ; GFX8-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[UV9]](i32)
    ; GFX8-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F800000
    ; GFX8-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP1]], [[C1]]
    ; GFX8-NEXT: [[FADD:%[0-9]+]]:_(f32) = G_FADD [[FMUL]], [[UITOFP]]
    ; GFX8-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD]](f32)
    ; GFX8-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x5F7FFFFC
    ; GFX8-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX8-NEXT: [[C3:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x2F800000
    ; GFX8-NEXT: [[FMUL2:%[0-9]+]]:_(f32) = G_FMUL [[FMUL1]], [[C3]]
    ; GFX8-NEXT: [[INTRINSIC_TRUNC:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL2]]
    ; GFX8-NEXT: [[C4:%[0-9]+]]:_(s32) = G_FCONSTANT float f0xCF800000
    ; GFX8-NEXT: [[FMUL3:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC]], [[C4]]
    ; GFX8-NEXT: [[FADD1:%[0-9]+]]:_(f32) = G_FADD [[FMUL3]], [[FMUL1]]
    ; GFX8-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD1]](f32)
    ; GFX8-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC]](f32)
    ; GFX8-NEXT: [[C5:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; GFX8-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX8-NEXT: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX8-NEXT: [[USUBO:%[0-9]+]]:_(s32), [[USUBO1:%[0-9]+]]:_(i1) = G_USUBO [[UV10]], [[UV12]]
    ; GFX8-NEXT: [[USUBE:%[0-9]+]]:_(s32), [[USUBE1:%[0-9]+]]:_(i1) = G_USUBE [[UV11]], [[UV13]], [[USUBO1]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_1:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[FPTOUI]], [[C5]]
    ; GFX8-NEXT: [[UV14:%[0-9]+]]:_(i32), [[UV15:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_]](s64)
    ; GFX8-NEXT: [[ANYEXT:%[0-9]+]]:_(s64) = G_ANYEXT [[UV15]](i32)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_2:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_3:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[FPTOUI1]], [[ANYEXT]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_4:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_5:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE]](s32), [[FPTOUI]], [[AMDGPU_MAD_U64_U32_2]]
    ; GFX8-NEXT: [[UV16:%[0-9]+]]:_(i32), [[UV17:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_4]](s64)
    ; GFX8-NEXT: [[UMULH:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[UV14]]
    ; GFX8-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI]], [[UV16]]
    ; GFX8-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[UV14]]
    ; GFX8-NEXT: [[UADDO4:%[0-9]+]]:_(i32), [[UADDO5:%[0-9]+]]:_(i1) = G_UADDO [[UMULH]], [[MUL]]
    ; GFX8-NEXT: [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO5]](i1)
    ; GFX8-NEXT: [[UADDO6:%[0-9]+]]:_(i32), [[UADDO7:%[0-9]+]]:_(i1) = G_UADDO [[UADDO4]], [[MUL1]]
    ; GFX8-NEXT: [[ZEXT1:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO7]](i1)
    ; GFX8-NEXT: [[ADD:%[0-9]+]]:_(i32) = G_ADD [[ZEXT]], [[ZEXT1]]
    ; GFX8-NEXT: [[UMULH1:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[UV14]]
    ; GFX8-NEXT: [[UMULH2:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[UV16]]
    ; GFX8-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[UV16]]
    ; GFX8-NEXT: [[UADDO8:%[0-9]+]]:_(i32), [[UADDO9:%[0-9]+]]:_(i1) = G_UADDO [[UMULH1]], [[UMULH2]]
    ; GFX8-NEXT: [[ZEXT2:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO9]](i1)
    ; GFX8-NEXT: [[UADDO10:%[0-9]+]]:_(i32), [[UADDO11:%[0-9]+]]:_(i1) = G_UADDO [[UADDO8]], [[MUL2]]
    ; GFX8-NEXT: [[ZEXT3:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO11]](i1)
    ; GFX8-NEXT: [[ADD1:%[0-9]+]]:_(i32) = G_ADD [[ZEXT2]], [[ZEXT3]]
    ; GFX8-NEXT: [[UADDO12:%[0-9]+]]:_(i32), [[UADDO13:%[0-9]+]]:_(i1) = G_UADDO [[UADDO10]], [[ADD]]
    ; GFX8-NEXT: [[ZEXT4:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO13]](i1)
    ; GFX8-NEXT: [[ADD2:%[0-9]+]]:_(i32) = G_ADD [[ADD1]], [[ZEXT4]]
    ; GFX8-NEXT: [[UMULH3:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[UV16]]
    ; GFX8-NEXT: [[ADD3:%[0-9]+]]:_(i32) = G_ADD [[UMULH3]], [[ADD2]]
    ; GFX8-NEXT: [[UADDO14:%[0-9]+]]:_(s32), [[UADDO15:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI]], [[UADDO12]]
    ; GFX8-NEXT: [[UADDE4:%[0-9]+]]:_(s32), [[UADDE5:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI1]], [[ADD3]], [[UADDO15]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_6:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_7:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[UADDO14]], [[C5]]
    ; GFX8-NEXT: [[UV18:%[0-9]+]]:_(i32), [[UV19:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_6]](s64)
    ; GFX8-NEXT: [[ANYEXT1:%[0-9]+]]:_(s64) = G_ANYEXT [[UV19]](i32)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_8:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_9:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[UADDE4]], [[ANYEXT1]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_10:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_11:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE]](s32), [[UADDO14]], [[AMDGPU_MAD_U64_U32_8]]
    ; GFX8-NEXT: [[UV20:%[0-9]+]]:_(i32), [[UV21:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_10]](s64)
    ; GFX8-NEXT: [[UMULH4:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[UV18]]
    ; GFX8-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[UADDO14]], [[UV20]]
    ; GFX8-NEXT: [[MUL4:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[UV18]]
    ; GFX8-NEXT: [[UADDO16:%[0-9]+]]:_(i32), [[UADDO17:%[0-9]+]]:_(i1) = G_UADDO [[UMULH4]], [[MUL3]]
    ; GFX8-NEXT: [[ZEXT5:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO17]](i1)
    ; GFX8-NEXT: [[UADDO18:%[0-9]+]]:_(i32), [[UADDO19:%[0-9]+]]:_(i1) = G_UADDO [[UADDO16]], [[MUL4]]
    ; GFX8-NEXT: [[ZEXT6:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO19]](i1)
    ; GFX8-NEXT: [[ADD4:%[0-9]+]]:_(i32) = G_ADD [[ZEXT5]], [[ZEXT6]]
    ; GFX8-NEXT: [[UMULH5:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[UV18]]
    ; GFX8-NEXT: [[UMULH6:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[UV20]]
    ; GFX8-NEXT: [[MUL5:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[UV20]]
    ; GFX8-NEXT: [[UADDO20:%[0-9]+]]:_(i32), [[UADDO21:%[0-9]+]]:_(i1) = G_UADDO [[UMULH5]], [[UMULH6]]
    ; GFX8-NEXT: [[ZEXT7:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO21]](i1)
    ; GFX8-NEXT: [[UADDO22:%[0-9]+]]:_(i32), [[UADDO23:%[0-9]+]]:_(i1) = G_UADDO [[UADDO20]], [[MUL5]]
    ; GFX8-NEXT: [[ZEXT8:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO23]](i1)
    ; GFX8-NEXT: [[ADD5:%[0-9]+]]:_(i32) = G_ADD [[ZEXT7]], [[ZEXT8]]
    ; GFX8-NEXT: [[UADDO24:%[0-9]+]]:_(i32), [[UADDO25:%[0-9]+]]:_(i1) = G_UADDO [[UADDO22]], [[ADD4]]
    ; GFX8-NEXT: [[ZEXT9:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO25]](i1)
    ; GFX8-NEXT: [[ADD6:%[0-9]+]]:_(i32) = G_ADD [[ADD5]], [[ZEXT9]]
    ; GFX8-NEXT: [[UMULH7:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[UV20]]
    ; GFX8-NEXT: [[ADD7:%[0-9]+]]:_(i32) = G_ADD [[UMULH7]], [[ADD6]]
    ; GFX8-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX8-NEXT: [[UADDO26:%[0-9]+]]:_(s32), [[UADDO27:%[0-9]+]]:_(s1) = G_UADDO [[UADDO14]], [[UADDO24]]
    ; GFX8-NEXT: [[UADDE6:%[0-9]+]]:_(s32), [[UADDE7:%[0-9]+]]:_(s1) = G_UADDE [[UADDE4]], [[ADD7]], [[UADDO27]]
    ; GFX8-NEXT: [[UV22:%[0-9]+]]:_(i32), [[UV23:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX8-NEXT: [[UV24:%[0-9]+]]:_(i32), [[UV25:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX8-NEXT: [[UMULH8:%[0-9]+]]:_(i32) = G_UMULH [[UV24]], [[UADDO26]]
    ; GFX8-NEXT: [[MUL6:%[0-9]+]]:_(i32) = G_MUL [[UV24]], [[UADDE6]]
    ; GFX8-NEXT: [[MUL7:%[0-9]+]]:_(i32) = G_MUL [[UV25]], [[UADDO26]]
    ; GFX8-NEXT: [[UADDO28:%[0-9]+]]:_(i32), [[UADDO29:%[0-9]+]]:_(i1) = G_UADDO [[UMULH8]], [[MUL6]]
    ; GFX8-NEXT: [[ZEXT10:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO29]](i1)
    ; GFX8-NEXT: [[UADDO30:%[0-9]+]]:_(i32), [[UADDO31:%[0-9]+]]:_(i1) = G_UADDO [[UADDO28]], [[MUL7]]
    ; GFX8-NEXT: [[ZEXT11:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO31]](i1)
    ; GFX8-NEXT: [[ADD8:%[0-9]+]]:_(i32) = G_ADD [[ZEXT10]], [[ZEXT11]]
    ; GFX8-NEXT: [[UMULH9:%[0-9]+]]:_(i32) = G_UMULH [[UV25]], [[UADDO26]]
    ; GFX8-NEXT: [[UMULH10:%[0-9]+]]:_(i32) = G_UMULH [[UV24]], [[UADDE6]]
    ; GFX8-NEXT: [[MUL8:%[0-9]+]]:_(i32) = G_MUL [[UV25]], [[UADDE6]]
    ; GFX8-NEXT: [[UADDO32:%[0-9]+]]:_(i32), [[UADDO33:%[0-9]+]]:_(i1) = G_UADDO [[UMULH9]], [[UMULH10]]
    ; GFX8-NEXT: [[ZEXT12:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO33]](i1)
    ; GFX8-NEXT: [[UADDO34:%[0-9]+]]:_(i32), [[UADDO35:%[0-9]+]]:_(i1) = G_UADDO [[UADDO32]], [[MUL8]]
    ; GFX8-NEXT: [[ZEXT13:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO35]](i1)
    ; GFX8-NEXT: [[ADD9:%[0-9]+]]:_(i32) = G_ADD [[ZEXT12]], [[ZEXT13]]
    ; GFX8-NEXT: [[UADDO36:%[0-9]+]]:_(i32), [[UADDO37:%[0-9]+]]:_(i1) = G_UADDO [[UADDO34]], [[ADD8]]
    ; GFX8-NEXT: [[ZEXT14:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO37]](i1)
    ; GFX8-NEXT: [[ADD10:%[0-9]+]]:_(i32) = G_ADD [[ADD9]], [[ZEXT14]]
    ; GFX8-NEXT: [[UMULH11:%[0-9]+]]:_(i32) = G_UMULH [[UV25]], [[UADDE6]]
    ; GFX8-NEXT: [[ADD11:%[0-9]+]]:_(i32) = G_ADD [[UMULH11]], [[ADD10]]
    ; GFX8-NEXT: [[UV26:%[0-9]+]]:_(i32), [[UV27:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_12:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_13:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV26]](i32), [[UADDO36]], [[C5]]
    ; GFX8-NEXT: [[UV28:%[0-9]+]]:_(i32), [[UV29:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_12]](s64)
    ; GFX8-NEXT: [[ANYEXT2:%[0-9]+]]:_(s64) = G_ANYEXT [[UV29]](i32)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_14:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_15:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV26]](i32), [[ADD11]], [[ANYEXT2]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_16:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_17:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV27]](i32), [[UADDO36]], [[AMDGPU_MAD_U64_U32_14]]
    ; GFX8-NEXT: [[UV30:%[0-9]+]]:_(i32), [[UV31:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_16]](s64)
    ; GFX8-NEXT: [[USUBO2:%[0-9]+]]:_(s32), [[USUBO3:%[0-9]+]]:_(s1) = G_USUBO [[UV22]], [[UV28]]
    ; GFX8-NEXT: [[USUBE2:%[0-9]+]]:_(s32), [[USUBE3:%[0-9]+]]:_(s1) = G_USUBE [[UV23]], [[UV30]], [[USUBO3]]
    ; GFX8-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[UV23]], [[UV30]]
    ; GFX8-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO2]](s32), [[USUBE2]](s32)
    ; GFX8-NEXT: [[UV32:%[0-9]+]]:_(i32), [[UV33:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX8-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE2]](s32), [[UV33]]
    ; GFX8-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[ICMP]](s1)
    ; GFX8-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO2]](s32), [[UV32]]
    ; GFX8-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[ICMP1]](s1)
    ; GFX8-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE2]](s32), [[UV33]]
    ; GFX8-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SEXT1]], [[SEXT]]
    ; GFX8-NEXT: [[USUBO4:%[0-9]+]]:_(s32), [[USUBO5:%[0-9]+]]:_(s1) = G_USUBO [[USUBO2]], [[UV32]]
    ; GFX8-NEXT: [[USUBE4:%[0-9]+]]:_(s32), [[USUBE5:%[0-9]+]]:_(s1) = G_USUBE [[SUB]], [[UV33]], [[USUBO3]]
    ; GFX8-NEXT: [[USUBE6:%[0-9]+]]:_(s32), [[USUBE7:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[C6]], [[USUBO5]]
    ; GFX8-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO4]](s32), [[USUBE6]](s32)
    ; GFX8-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE6]](s32), [[UV33]]
    ; GFX8-NEXT: [[SEXT2:%[0-9]+]]:_(s32) = G_SEXT [[ICMP3]](s1)
    ; GFX8-NEXT: [[ICMP4:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO4]](s32), [[UV32]]
    ; GFX8-NEXT: [[SEXT3:%[0-9]+]]:_(s32) = G_SEXT [[ICMP4]](s1)
    ; GFX8-NEXT: [[ICMP5:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE6]](s32), [[UV33]]
    ; GFX8-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP5]](s1), [[SEXT3]], [[SEXT2]]
    ; GFX8-NEXT: [[USUBO6:%[0-9]+]]:_(s32), [[USUBO7:%[0-9]+]]:_(s1) = G_USUBO [[USUBO4]], [[UV32]]
    ; GFX8-NEXT: [[USUBE8:%[0-9]+]]:_(s32), [[USUBE9:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[UV33]], [[USUBO5]]
    ; GFX8-NEXT: [[USUBE10:%[0-9]+]]:_(s32), [[USUBE11:%[0-9]+]]:_(s1) = G_USUBE [[USUBE8]], [[C6]], [[USUBO7]]
    ; GFX8-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO6]](s32), [[USUBE10]](s32)
    ; GFX8-NEXT: [[ICMP6:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT1]](s32), [[C6]]
    ; GFX8-NEXT: [[SELECT2:%[0-9]+]]:_(s64) = G_SELECT [[ICMP6]](s1), [[MV4]], [[MV3]]
    ; GFX8-NEXT: [[ICMP7:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT]](s32), [[C6]]
    ; GFX8-NEXT: [[SELECT3:%[0-9]+]]:_(s64) = G_SELECT [[ICMP7]](s1), [[SELECT2]], [[MV2]]
    ; GFX8-NEXT: [[XOR2:%[0-9]+]]:_(s64) = G_XOR [[SELECT3]], [[ASHR]]
    ; GFX8-NEXT: [[UV34:%[0-9]+]]:_(s32), [[UV35:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR2]](s64)
    ; GFX8-NEXT: [[UV36:%[0-9]+]]:_(s32), [[UV37:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX8-NEXT: [[USUBO8:%[0-9]+]]:_(s32), [[USUBO9:%[0-9]+]]:_(i1) = G_USUBO [[UV34]], [[UV36]]
    ; GFX8-NEXT: [[USUBE12:%[0-9]+]]:_(s32), [[USUBE13:%[0-9]+]]:_(i1) = G_USUBE [[UV35]], [[UV37]], [[USUBO9]]
    ; GFX8-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO8]](s32), [[USUBE12]](s32)
    ; GFX8-NEXT: $vgpr0_vgpr1 = COPY [[MV5]](s64)
    ;
    ; GFX9-LABEL: name: test_srem_s64
    ; GFX9: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $vgpr0_vgpr1
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $vgpr2_vgpr3
    ; GFX9-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; GFX9-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[COPY]], [[C]](s32)
    ; GFX9-NEXT: [[ASHR1:%[0-9]+]]:_(s64) = G_ASHR [[COPY1]], [[C]](s32)
    ; GFX9-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; GFX9-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX9-NEXT: [[UADDO:%[0-9]+]]:_(s32), [[UADDO1:%[0-9]+]]:_(i1) = G_UADDO [[UV]], [[UV2]]
    ; GFX9-NEXT: [[UADDE:%[0-9]+]]:_(s32), [[UADDE1:%[0-9]+]]:_(i1) = G_UADDE [[UV1]], [[UV3]], [[UADDO1]]
    ; GFX9-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO]](s32), [[UADDE]](s32)
    ; GFX9-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY1]](s64)
    ; GFX9-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR1]](s64)
    ; GFX9-NEXT: [[UADDO2:%[0-9]+]]:_(s32), [[UADDO3:%[0-9]+]]:_(i1) = G_UADDO [[UV4]], [[UV6]]
    ; GFX9-NEXT: [[UADDE2:%[0-9]+]]:_(s32), [[UADDE3:%[0-9]+]]:_(i1) = G_UADDE [[UV5]], [[UV7]], [[UADDO3]]
    ; GFX9-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO2]](s32), [[UADDE2]](s32)
    ; GFX9-NEXT: [[XOR:%[0-9]+]]:_(s64) = G_XOR [[MV]], [[ASHR]]
    ; GFX9-NEXT: [[XOR1:%[0-9]+]]:_(s64) = G_XOR [[MV1]], [[ASHR1]]
    ; GFX9-NEXT: [[UV8:%[0-9]+]]:_(i32), [[UV9:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX9-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[UV8]](i32)
    ; GFX9-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[UV9]](i32)
    ; GFX9-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F800000
    ; GFX9-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP1]], [[C1]]
    ; GFX9-NEXT: [[FADD:%[0-9]+]]:_(f32) = G_FADD [[FMUL]], [[UITOFP]]
    ; GFX9-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD]](f32)
    ; GFX9-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x5F7FFFFC
    ; GFX9-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX9-NEXT: [[C3:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x2F800000
    ; GFX9-NEXT: [[FMUL2:%[0-9]+]]:_(f32) = G_FMUL [[FMUL1]], [[C3]]
    ; GFX9-NEXT: [[INTRINSIC_TRUNC:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL2]]
    ; GFX9-NEXT: [[C4:%[0-9]+]]:_(s32) = G_FCONSTANT float f0xCF800000
    ; GFX9-NEXT: [[FMUL3:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC]], [[C4]]
    ; GFX9-NEXT: [[FADD1:%[0-9]+]]:_(f32) = G_FADD [[FMUL3]], [[FMUL1]]
    ; GFX9-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD1]](f32)
    ; GFX9-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC]](f32)
    ; GFX9-NEXT: [[C5:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; GFX9-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX9-NEXT: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX9-NEXT: [[USUBO:%[0-9]+]]:_(s32), [[USUBO1:%[0-9]+]]:_(i1) = G_USUBO [[UV10]], [[UV12]]
    ; GFX9-NEXT: [[USUBE:%[0-9]+]]:_(s32), [[USUBE1:%[0-9]+]]:_(i1) = G_USUBE [[UV11]], [[UV13]], [[USUBO1]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_1:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[FPTOUI]], [[C5]]
    ; GFX9-NEXT: [[UV14:%[0-9]+]]:_(i32), [[UV15:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_]](s64)
    ; GFX9-NEXT: [[ANYEXT:%[0-9]+]]:_(s64) = G_ANYEXT [[UV15]](i32)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_2:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_3:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[FPTOUI1]], [[ANYEXT]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_4:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_5:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE]](s32), [[FPTOUI]], [[AMDGPU_MAD_U64_U32_2]]
    ; GFX9-NEXT: [[UV16:%[0-9]+]]:_(i32), [[UV17:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_4]](s64)
    ; GFX9-NEXT: [[UMULH:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[UV14]]
    ; GFX9-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI]], [[UV16]]
    ; GFX9-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[UV14]]
    ; GFX9-NEXT: [[UADDO4:%[0-9]+]]:_(i32), [[UADDO5:%[0-9]+]]:_(i1) = G_UADDO [[UMULH]], [[MUL]]
    ; GFX9-NEXT: [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO5]](i1)
    ; GFX9-NEXT: [[UADDO6:%[0-9]+]]:_(i32), [[UADDO7:%[0-9]+]]:_(i1) = G_UADDO [[UADDO4]], [[MUL1]]
    ; GFX9-NEXT: [[ZEXT1:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO7]](i1)
    ; GFX9-NEXT: [[ADD:%[0-9]+]]:_(i32) = G_ADD [[ZEXT]], [[ZEXT1]]
    ; GFX9-NEXT: [[UMULH1:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[UV14]]
    ; GFX9-NEXT: [[UMULH2:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[UV16]]
    ; GFX9-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[UV16]]
    ; GFX9-NEXT: [[UADDO8:%[0-9]+]]:_(i32), [[UADDO9:%[0-9]+]]:_(i1) = G_UADDO [[UMULH1]], [[UMULH2]]
    ; GFX9-NEXT: [[ZEXT2:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO9]](i1)
    ; GFX9-NEXT: [[UADDO10:%[0-9]+]]:_(i32), [[UADDO11:%[0-9]+]]:_(i1) = G_UADDO [[UADDO8]], [[MUL2]]
    ; GFX9-NEXT: [[ZEXT3:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO11]](i1)
    ; GFX9-NEXT: [[ADD1:%[0-9]+]]:_(i32) = G_ADD [[ZEXT2]], [[ZEXT3]]
    ; GFX9-NEXT: [[UADDO12:%[0-9]+]]:_(i32), [[UADDO13:%[0-9]+]]:_(i1) = G_UADDO [[UADDO10]], [[ADD]]
    ; GFX9-NEXT: [[ZEXT4:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO13]](i1)
    ; GFX9-NEXT: [[ADD2:%[0-9]+]]:_(i32) = G_ADD [[ADD1]], [[ZEXT4]]
    ; GFX9-NEXT: [[UMULH3:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[UV16]]
    ; GFX9-NEXT: [[ADD3:%[0-9]+]]:_(i32) = G_ADD [[UMULH3]], [[ADD2]]
    ; GFX9-NEXT: [[UADDO14:%[0-9]+]]:_(s32), [[UADDO15:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI]], [[UADDO12]]
    ; GFX9-NEXT: [[UADDE4:%[0-9]+]]:_(s32), [[UADDE5:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI1]], [[ADD3]], [[UADDO15]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_6:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_7:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[UADDO14]], [[C5]]
    ; GFX9-NEXT: [[UV18:%[0-9]+]]:_(i32), [[UV19:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_6]](s64)
    ; GFX9-NEXT: [[ANYEXT1:%[0-9]+]]:_(s64) = G_ANYEXT [[UV19]](i32)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_8:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_9:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[UADDE4]], [[ANYEXT1]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_10:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_11:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE]](s32), [[UADDO14]], [[AMDGPU_MAD_U64_U32_8]]
    ; GFX9-NEXT: [[UV20:%[0-9]+]]:_(i32), [[UV21:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_10]](s64)
    ; GFX9-NEXT: [[UMULH4:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[UV18]]
    ; GFX9-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[UADDO14]], [[UV20]]
    ; GFX9-NEXT: [[MUL4:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[UV18]]
    ; GFX9-NEXT: [[UADDO16:%[0-9]+]]:_(i32), [[UADDO17:%[0-9]+]]:_(i1) = G_UADDO [[UMULH4]], [[MUL3]]
    ; GFX9-NEXT: [[ZEXT5:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO17]](i1)
    ; GFX9-NEXT: [[UADDO18:%[0-9]+]]:_(i32), [[UADDO19:%[0-9]+]]:_(i1) = G_UADDO [[UADDO16]], [[MUL4]]
    ; GFX9-NEXT: [[ZEXT6:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO19]](i1)
    ; GFX9-NEXT: [[ADD4:%[0-9]+]]:_(i32) = G_ADD [[ZEXT5]], [[ZEXT6]]
    ; GFX9-NEXT: [[UMULH5:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[UV18]]
    ; GFX9-NEXT: [[UMULH6:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[UV20]]
    ; GFX9-NEXT: [[MUL5:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[UV20]]
    ; GFX9-NEXT: [[UADDO20:%[0-9]+]]:_(i32), [[UADDO21:%[0-9]+]]:_(i1) = G_UADDO [[UMULH5]], [[UMULH6]]
    ; GFX9-NEXT: [[ZEXT7:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO21]](i1)
    ; GFX9-NEXT: [[UADDO22:%[0-9]+]]:_(i32), [[UADDO23:%[0-9]+]]:_(i1) = G_UADDO [[UADDO20]], [[MUL5]]
    ; GFX9-NEXT: [[ZEXT8:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO23]](i1)
    ; GFX9-NEXT: [[ADD5:%[0-9]+]]:_(i32) = G_ADD [[ZEXT7]], [[ZEXT8]]
    ; GFX9-NEXT: [[UADDO24:%[0-9]+]]:_(i32), [[UADDO25:%[0-9]+]]:_(i1) = G_UADDO [[UADDO22]], [[ADD4]]
    ; GFX9-NEXT: [[ZEXT9:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO25]](i1)
    ; GFX9-NEXT: [[ADD6:%[0-9]+]]:_(i32) = G_ADD [[ADD5]], [[ZEXT9]]
    ; GFX9-NEXT: [[UMULH7:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[UV20]]
    ; GFX9-NEXT: [[ADD7:%[0-9]+]]:_(i32) = G_ADD [[UMULH7]], [[ADD6]]
    ; GFX9-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX9-NEXT: [[UADDO26:%[0-9]+]]:_(s32), [[UADDO27:%[0-9]+]]:_(s1) = G_UADDO [[UADDO14]], [[UADDO24]]
    ; GFX9-NEXT: [[UADDE6:%[0-9]+]]:_(s32), [[UADDE7:%[0-9]+]]:_(s1) = G_UADDE [[UADDE4]], [[ADD7]], [[UADDO27]]
    ; GFX9-NEXT: [[UV22:%[0-9]+]]:_(i32), [[UV23:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX9-NEXT: [[UV24:%[0-9]+]]:_(i32), [[UV25:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX9-NEXT: [[UMULH8:%[0-9]+]]:_(i32) = G_UMULH [[UV24]], [[UADDO26]]
    ; GFX9-NEXT: [[MUL6:%[0-9]+]]:_(i32) = G_MUL [[UV24]], [[UADDE6]]
    ; GFX9-NEXT: [[MUL7:%[0-9]+]]:_(i32) = G_MUL [[UV25]], [[UADDO26]]
    ; GFX9-NEXT: [[UADDO28:%[0-9]+]]:_(i32), [[UADDO29:%[0-9]+]]:_(i1) = G_UADDO [[UMULH8]], [[MUL6]]
    ; GFX9-NEXT: [[ZEXT10:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO29]](i1)
    ; GFX9-NEXT: [[UADDO30:%[0-9]+]]:_(i32), [[UADDO31:%[0-9]+]]:_(i1) = G_UADDO [[UADDO28]], [[MUL7]]
    ; GFX9-NEXT: [[ZEXT11:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO31]](i1)
    ; GFX9-NEXT: [[ADD8:%[0-9]+]]:_(i32) = G_ADD [[ZEXT10]], [[ZEXT11]]
    ; GFX9-NEXT: [[UMULH9:%[0-9]+]]:_(i32) = G_UMULH [[UV25]], [[UADDO26]]
    ; GFX9-NEXT: [[UMULH10:%[0-9]+]]:_(i32) = G_UMULH [[UV24]], [[UADDE6]]
    ; GFX9-NEXT: [[MUL8:%[0-9]+]]:_(i32) = G_MUL [[UV25]], [[UADDE6]]
    ; GFX9-NEXT: [[UADDO32:%[0-9]+]]:_(i32), [[UADDO33:%[0-9]+]]:_(i1) = G_UADDO [[UMULH9]], [[UMULH10]]
    ; GFX9-NEXT: [[ZEXT12:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO33]](i1)
    ; GFX9-NEXT: [[UADDO34:%[0-9]+]]:_(i32), [[UADDO35:%[0-9]+]]:_(i1) = G_UADDO [[UADDO32]], [[MUL8]]
    ; GFX9-NEXT: [[ZEXT13:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO35]](i1)
    ; GFX9-NEXT: [[ADD9:%[0-9]+]]:_(i32) = G_ADD [[ZEXT12]], [[ZEXT13]]
    ; GFX9-NEXT: [[UADDO36:%[0-9]+]]:_(i32), [[UADDO37:%[0-9]+]]:_(i1) = G_UADDO [[UADDO34]], [[ADD8]]
    ; GFX9-NEXT: [[ZEXT14:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO37]](i1)
    ; GFX9-NEXT: [[ADD10:%[0-9]+]]:_(i32) = G_ADD [[ADD9]], [[ZEXT14]]
    ; GFX9-NEXT: [[UMULH11:%[0-9]+]]:_(i32) = G_UMULH [[UV25]], [[UADDE6]]
    ; GFX9-NEXT: [[ADD11:%[0-9]+]]:_(i32) = G_ADD [[UMULH11]], [[ADD10]]
    ; GFX9-NEXT: [[UV26:%[0-9]+]]:_(i32), [[UV27:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_12:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_13:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV26]](i32), [[UADDO36]], [[C5]]
    ; GFX9-NEXT: [[UV28:%[0-9]+]]:_(i32), [[UV29:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_12]](s64)
    ; GFX9-NEXT: [[ANYEXT2:%[0-9]+]]:_(s64) = G_ANYEXT [[UV29]](i32)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_14:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_15:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV26]](i32), [[ADD11]], [[ANYEXT2]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_16:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_17:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV27]](i32), [[UADDO36]], [[AMDGPU_MAD_U64_U32_14]]
    ; GFX9-NEXT: [[UV30:%[0-9]+]]:_(i32), [[UV31:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_16]](s64)
    ; GFX9-NEXT: [[USUBO2:%[0-9]+]]:_(s32), [[USUBO3:%[0-9]+]]:_(s1) = G_USUBO [[UV22]], [[UV28]]
    ; GFX9-NEXT: [[USUBE2:%[0-9]+]]:_(s32), [[USUBE3:%[0-9]+]]:_(s1) = G_USUBE [[UV23]], [[UV30]], [[USUBO3]]
    ; GFX9-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[UV23]], [[UV30]]
    ; GFX9-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO2]](s32), [[USUBE2]](s32)
    ; GFX9-NEXT: [[UV32:%[0-9]+]]:_(i32), [[UV33:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX9-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE2]](s32), [[UV33]]
    ; GFX9-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[ICMP]](s1)
    ; GFX9-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO2]](s32), [[UV32]]
    ; GFX9-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[ICMP1]](s1)
    ; GFX9-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE2]](s32), [[UV33]]
    ; GFX9-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SEXT1]], [[SEXT]]
    ; GFX9-NEXT: [[USUBO4:%[0-9]+]]:_(s32), [[USUBO5:%[0-9]+]]:_(s1) = G_USUBO [[USUBO2]], [[UV32]]
    ; GFX9-NEXT: [[USUBE4:%[0-9]+]]:_(s32), [[USUBE5:%[0-9]+]]:_(s1) = G_USUBE [[SUB]], [[UV33]], [[USUBO3]]
    ; GFX9-NEXT: [[USUBE6:%[0-9]+]]:_(s32), [[USUBE7:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[C6]], [[USUBO5]]
    ; GFX9-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO4]](s32), [[USUBE6]](s32)
    ; GFX9-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE6]](s32), [[UV33]]
    ; GFX9-NEXT: [[SEXT2:%[0-9]+]]:_(s32) = G_SEXT [[ICMP3]](s1)
    ; GFX9-NEXT: [[ICMP4:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO4]](s32), [[UV32]]
    ; GFX9-NEXT: [[SEXT3:%[0-9]+]]:_(s32) = G_SEXT [[ICMP4]](s1)
    ; GFX9-NEXT: [[ICMP5:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE6]](s32), [[UV33]]
    ; GFX9-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP5]](s1), [[SEXT3]], [[SEXT2]]
    ; GFX9-NEXT: [[USUBO6:%[0-9]+]]:_(s32), [[USUBO7:%[0-9]+]]:_(s1) = G_USUBO [[USUBO4]], [[UV32]]
    ; GFX9-NEXT: [[USUBE8:%[0-9]+]]:_(s32), [[USUBE9:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[UV33]], [[USUBO5]]
    ; GFX9-NEXT: [[USUBE10:%[0-9]+]]:_(s32), [[USUBE11:%[0-9]+]]:_(s1) = G_USUBE [[USUBE8]], [[C6]], [[USUBO7]]
    ; GFX9-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO6]](s32), [[USUBE10]](s32)
    ; GFX9-NEXT: [[ICMP6:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT1]](s32), [[C6]]
    ; GFX9-NEXT: [[SELECT2:%[0-9]+]]:_(s64) = G_SELECT [[ICMP6]](s1), [[MV4]], [[MV3]]
    ; GFX9-NEXT: [[ICMP7:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT]](s32), [[C6]]
    ; GFX9-NEXT: [[SELECT3:%[0-9]+]]:_(s64) = G_SELECT [[ICMP7]](s1), [[SELECT2]], [[MV2]]
    ; GFX9-NEXT: [[XOR2:%[0-9]+]]:_(s64) = G_XOR [[SELECT3]], [[ASHR]]
    ; GFX9-NEXT: [[UV34:%[0-9]+]]:_(s32), [[UV35:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR2]](s64)
    ; GFX9-NEXT: [[UV36:%[0-9]+]]:_(s32), [[UV37:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX9-NEXT: [[USUBO8:%[0-9]+]]:_(s32), [[USUBO9:%[0-9]+]]:_(i1) = G_USUBO [[UV34]], [[UV36]]
    ; GFX9-NEXT: [[USUBE12:%[0-9]+]]:_(s32), [[USUBE13:%[0-9]+]]:_(i1) = G_USUBE [[UV35]], [[UV37]], [[USUBO9]]
    ; GFX9-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO8]](s32), [[USUBE12]](s32)
    ; GFX9-NEXT: $vgpr0_vgpr1 = COPY [[MV5]](s64)
    ;
    ; GFX10-LABEL: name: test_srem_s64
    ; GFX10: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $vgpr0_vgpr1
    ; GFX10-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $vgpr2_vgpr3
    ; GFX10-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; GFX10-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[COPY]], [[C]](s32)
    ; GFX10-NEXT: [[ASHR1:%[0-9]+]]:_(s64) = G_ASHR [[COPY1]], [[C]](s32)
    ; GFX10-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; GFX10-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX10-NEXT: [[UADDO:%[0-9]+]]:_(s32), [[UADDO1:%[0-9]+]]:_(i1) = G_UADDO [[UV]], [[UV2]]
    ; GFX10-NEXT: [[UADDE:%[0-9]+]]:_(s32), [[UADDE1:%[0-9]+]]:_(i1) = G_UADDE [[UV1]], [[UV3]], [[UADDO1]]
    ; GFX10-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO]](s32), [[UADDE]](s32)
    ; GFX10-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY1]](s64)
    ; GFX10-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR1]](s64)
    ; GFX10-NEXT: [[UADDO2:%[0-9]+]]:_(s32), [[UADDO3:%[0-9]+]]:_(i1) = G_UADDO [[UV4]], [[UV6]]
    ; GFX10-NEXT: [[UADDE2:%[0-9]+]]:_(s32), [[UADDE3:%[0-9]+]]:_(i1) = G_UADDE [[UV5]], [[UV7]], [[UADDO3]]
    ; GFX10-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO2]](s32), [[UADDE2]](s32)
    ; GFX10-NEXT: [[XOR:%[0-9]+]]:_(s64) = G_XOR [[MV]], [[ASHR]]
    ; GFX10-NEXT: [[XOR1:%[0-9]+]]:_(s64) = G_XOR [[MV1]], [[ASHR1]]
    ; GFX10-NEXT: [[UV8:%[0-9]+]]:_(i32), [[UV9:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX10-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[UV8]](i32)
    ; GFX10-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[UV9]](i32)
    ; GFX10-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F800000
    ; GFX10-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP1]], [[C1]]
    ; GFX10-NEXT: [[FADD:%[0-9]+]]:_(f32) = G_FADD [[FMUL]], [[UITOFP]]
    ; GFX10-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD]](f32)
    ; GFX10-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x5F7FFFFC
    ; GFX10-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX10-NEXT: [[C3:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x2F800000
    ; GFX10-NEXT: [[FMUL2:%[0-9]+]]:_(f32) = G_FMUL [[FMUL1]], [[C3]]
    ; GFX10-NEXT: [[INTRINSIC_TRUNC:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL2]]
    ; GFX10-NEXT: [[C4:%[0-9]+]]:_(s32) = G_FCONSTANT float f0xCF800000
    ; GFX10-NEXT: [[FMUL3:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC]], [[C4]]
    ; GFX10-NEXT: [[FADD1:%[0-9]+]]:_(f32) = G_FADD [[FMUL3]], [[FMUL1]]
    ; GFX10-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD1]](f32)
    ; GFX10-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC]](f32)
    ; GFX10-NEXT: [[C5:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; GFX10-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX10-NEXT: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX10-NEXT: [[USUBO:%[0-9]+]]:_(s32), [[USUBO1:%[0-9]+]]:_(i1) = G_USUBO [[UV10]], [[UV12]]
    ; GFX10-NEXT: [[USUBE:%[0-9]+]]:_(s32), [[USUBE1:%[0-9]+]]:_(i1) = G_USUBE [[UV11]], [[UV13]], [[USUBO1]]
    ; GFX10-NEXT: [[AMDGPU_MAD_U64_U32_:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_1:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[FPTOUI]], [[C5]]
    ; GFX10-NEXT: [[UV14:%[0-9]+]]:_(i32), [[UV15:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_]](s64)
    ; GFX10-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[FPTOUI1]]
    ; GFX10-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[UV15]], [[MUL]]
    ; GFX10-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[USUBE]], [[FPTOUI]]
    ; GFX10-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[ADD]], [[MUL1]]
    ; GFX10-NEXT: [[UMULH:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[UV14]]
    ; GFX10-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI]], [[ADD1]]
    ; GFX10-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[UV14]]
    ; GFX10-NEXT: [[UADDO4:%[0-9]+]]:_(i32), [[UADDO5:%[0-9]+]]:_(i1) = G_UADDO [[UMULH]], [[MUL2]]
    ; GFX10-NEXT: [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO5]](i1)
    ; GFX10-NEXT: [[UADDO6:%[0-9]+]]:_(i32), [[UADDO7:%[0-9]+]]:_(i1) = G_UADDO [[UADDO4]], [[MUL3]]
    ; GFX10-NEXT: [[ZEXT1:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO7]](i1)
    ; GFX10-NEXT: [[ADD2:%[0-9]+]]:_(i32) = G_ADD [[ZEXT]], [[ZEXT1]]
    ; GFX10-NEXT: [[UMULH1:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[UV14]]
    ; GFX10-NEXT: [[UMULH2:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[ADD1]]
    ; GFX10-NEXT: [[MUL4:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[ADD1]]
    ; GFX10-NEXT: [[UADDO8:%[0-9]+]]:_(i32), [[UADDO9:%[0-9]+]]:_(i1) = G_UADDO [[UMULH1]], [[UMULH2]]
    ; GFX10-NEXT: [[ZEXT2:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO9]](i1)
    ; GFX10-NEXT: [[UADDO10:%[0-9]+]]:_(i32), [[UADDO11:%[0-9]+]]:_(i1) = G_UADDO [[UADDO8]], [[MUL4]]
    ; GFX10-NEXT: [[ZEXT3:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO11]](i1)
    ; GFX10-NEXT: [[ADD3:%[0-9]+]]:_(i32) = G_ADD [[ZEXT2]], [[ZEXT3]]
    ; GFX10-NEXT: [[UADDO12:%[0-9]+]]:_(i32), [[UADDO13:%[0-9]+]]:_(i1) = G_UADDO [[UADDO10]], [[ADD2]]
    ; GFX10-NEXT: [[ZEXT4:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO13]](i1)
    ; GFX10-NEXT: [[ADD4:%[0-9]+]]:_(i32) = G_ADD [[ADD3]], [[ZEXT4]]
    ; GFX10-NEXT: [[UMULH3:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[ADD1]]
    ; GFX10-NEXT: [[ADD5:%[0-9]+]]:_(i32) = G_ADD [[UMULH3]], [[ADD4]]
    ; GFX10-NEXT: [[UADDO14:%[0-9]+]]:_(s32), [[UADDO15:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI]], [[UADDO12]]
    ; GFX10-NEXT: [[UADDE4:%[0-9]+]]:_(s32), [[UADDE5:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI1]], [[ADD5]], [[UADDO15]]
    ; GFX10-NEXT: [[AMDGPU_MAD_U64_U32_2:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_3:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[UADDO14]], [[C5]]
    ; GFX10-NEXT: [[UV16:%[0-9]+]]:_(i32), [[UV17:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_2]](s64)
    ; GFX10-NEXT: [[MUL5:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[UADDE4]]
    ; GFX10-NEXT: [[ADD6:%[0-9]+]]:_(s32) = G_ADD [[UV17]], [[MUL5]]
    ; GFX10-NEXT: [[MUL6:%[0-9]+]]:_(i32) = G_MUL [[USUBE]], [[UADDO14]]
    ; GFX10-NEXT: [[ADD7:%[0-9]+]]:_(s32) = G_ADD [[ADD6]], [[MUL6]]
    ; GFX10-NEXT: [[UMULH4:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[UV16]]
    ; GFX10-NEXT: [[MUL7:%[0-9]+]]:_(i32) = G_MUL [[UADDO14]], [[ADD7]]
    ; GFX10-NEXT: [[MUL8:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[UV16]]
    ; GFX10-NEXT: [[UADDO16:%[0-9]+]]:_(i32), [[UADDO17:%[0-9]+]]:_(i1) = G_UADDO [[UMULH4]], [[MUL7]]
    ; GFX10-NEXT: [[ZEXT5:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO17]](i1)
    ; GFX10-NEXT: [[UADDO18:%[0-9]+]]:_(i32), [[UADDO19:%[0-9]+]]:_(i1) = G_UADDO [[UADDO16]], [[MUL8]]
    ; GFX10-NEXT: [[ZEXT6:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO19]](i1)
    ; GFX10-NEXT: [[ADD8:%[0-9]+]]:_(i32) = G_ADD [[ZEXT5]], [[ZEXT6]]
    ; GFX10-NEXT: [[UMULH5:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[UV16]]
    ; GFX10-NEXT: [[UMULH6:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[ADD7]]
    ; GFX10-NEXT: [[MUL9:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[ADD7]]
    ; GFX10-NEXT: [[UADDO20:%[0-9]+]]:_(i32), [[UADDO21:%[0-9]+]]:_(i1) = G_UADDO [[UMULH5]], [[UMULH6]]
    ; GFX10-NEXT: [[ZEXT7:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO21]](i1)
    ; GFX10-NEXT: [[UADDO22:%[0-9]+]]:_(i32), [[UADDO23:%[0-9]+]]:_(i1) = G_UADDO [[UADDO20]], [[MUL9]]
    ; GFX10-NEXT: [[ZEXT8:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO23]](i1)
    ; GFX10-NEXT: [[ADD9:%[0-9]+]]:_(i32) = G_ADD [[ZEXT7]], [[ZEXT8]]
    ; GFX10-NEXT: [[UADDO24:%[0-9]+]]:_(i32), [[UADDO25:%[0-9]+]]:_(i1) = G_UADDO [[UADDO22]], [[ADD8]]
    ; GFX10-NEXT: [[ZEXT9:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO25]](i1)
    ; GFX10-NEXT: [[ADD10:%[0-9]+]]:_(i32) = G_ADD [[ADD9]], [[ZEXT9]]
    ; GFX10-NEXT: [[UMULH7:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[ADD7]]
    ; GFX10-NEXT: [[ADD11:%[0-9]+]]:_(i32) = G_ADD [[UMULH7]], [[ADD10]]
    ; GFX10-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX10-NEXT: [[UADDO26:%[0-9]+]]:_(s32), [[UADDO27:%[0-9]+]]:_(s1) = G_UADDO [[UADDO14]], [[UADDO24]]
    ; GFX10-NEXT: [[UADDE6:%[0-9]+]]:_(s32), [[UADDE7:%[0-9]+]]:_(s1) = G_UADDE [[UADDE4]], [[ADD11]], [[UADDO27]]
    ; GFX10-NEXT: [[UV18:%[0-9]+]]:_(i32), [[UV19:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX10-NEXT: [[UV20:%[0-9]+]]:_(i32), [[UV21:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX10-NEXT: [[UMULH8:%[0-9]+]]:_(i32) = G_UMULH [[UV20]], [[UADDO26]]
    ; GFX10-NEXT: [[MUL10:%[0-9]+]]:_(i32) = G_MUL [[UV20]], [[UADDE6]]
    ; GFX10-NEXT: [[MUL11:%[0-9]+]]:_(i32) = G_MUL [[UV21]], [[UADDO26]]
    ; GFX10-NEXT: [[UADDO28:%[0-9]+]]:_(i32), [[UADDO29:%[0-9]+]]:_(i1) = G_UADDO [[UMULH8]], [[MUL10]]
    ; GFX10-NEXT: [[ZEXT10:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO29]](i1)
    ; GFX10-NEXT: [[UADDO30:%[0-9]+]]:_(i32), [[UADDO31:%[0-9]+]]:_(i1) = G_UADDO [[UADDO28]], [[MUL11]]
    ; GFX10-NEXT: [[ZEXT11:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO31]](i1)
    ; GFX10-NEXT: [[ADD12:%[0-9]+]]:_(i32) = G_ADD [[ZEXT10]], [[ZEXT11]]
    ; GFX10-NEXT: [[UMULH9:%[0-9]+]]:_(i32) = G_UMULH [[UV21]], [[UADDO26]]
    ; GFX10-NEXT: [[UMULH10:%[0-9]+]]:_(i32) = G_UMULH [[UV20]], [[UADDE6]]
    ; GFX10-NEXT: [[MUL12:%[0-9]+]]:_(i32) = G_MUL [[UV21]], [[UADDE6]]
    ; GFX10-NEXT: [[UADDO32:%[0-9]+]]:_(i32), [[UADDO33:%[0-9]+]]:_(i1) = G_UADDO [[UMULH9]], [[UMULH10]]
    ; GFX10-NEXT: [[ZEXT12:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO33]](i1)
    ; GFX10-NEXT: [[UADDO34:%[0-9]+]]:_(i32), [[UADDO35:%[0-9]+]]:_(i1) = G_UADDO [[UADDO32]], [[MUL12]]
    ; GFX10-NEXT: [[ZEXT13:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO35]](i1)
    ; GFX10-NEXT: [[ADD13:%[0-9]+]]:_(i32) = G_ADD [[ZEXT12]], [[ZEXT13]]
    ; GFX10-NEXT: [[UADDO36:%[0-9]+]]:_(i32), [[UADDO37:%[0-9]+]]:_(i1) = G_UADDO [[UADDO34]], [[ADD12]]
    ; GFX10-NEXT: [[ZEXT14:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO37]](i1)
    ; GFX10-NEXT: [[ADD14:%[0-9]+]]:_(i32) = G_ADD [[ADD13]], [[ZEXT14]]
    ; GFX10-NEXT: [[UMULH11:%[0-9]+]]:_(i32) = G_UMULH [[UV21]], [[UADDE6]]
    ; GFX10-NEXT: [[ADD15:%[0-9]+]]:_(i32) = G_ADD [[UMULH11]], [[ADD14]]
    ; GFX10-NEXT: [[UV22:%[0-9]+]]:_(i32), [[UV23:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX10-NEXT: [[AMDGPU_MAD_U64_U32_4:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_5:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV22]](i32), [[UADDO36]], [[C5]]
    ; GFX10-NEXT: [[UV24:%[0-9]+]]:_(i32), [[UV25:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_4]](s64)
    ; GFX10-NEXT: [[MUL13:%[0-9]+]]:_(i32) = G_MUL [[UV22]], [[ADD15]]
    ; GFX10-NEXT: [[ADD16:%[0-9]+]]:_(s32) = G_ADD [[UV25]], [[MUL13]]
    ; GFX10-NEXT: [[MUL14:%[0-9]+]]:_(i32) = G_MUL [[UV23]], [[UADDO36]]
    ; GFX10-NEXT: [[ADD17:%[0-9]+]]:_(s32) = G_ADD [[ADD16]], [[MUL14]]
    ; GFX10-NEXT: [[USUBO2:%[0-9]+]]:_(s32), [[USUBO3:%[0-9]+]]:_(s1) = G_USUBO [[UV18]], [[UV24]]
    ; GFX10-NEXT: [[USUBE2:%[0-9]+]]:_(s32), [[USUBE3:%[0-9]+]]:_(s1) = G_USUBE [[UV19]], [[ADD17]], [[USUBO3]]
    ; GFX10-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[UV19]], [[ADD17]]
    ; GFX10-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO2]](s32), [[USUBE2]](s32)
    ; GFX10-NEXT: [[UV26:%[0-9]+]]:_(i32), [[UV27:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX10-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE2]](s32), [[UV27]]
    ; GFX10-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[ICMP]](s1)
    ; GFX10-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO2]](s32), [[UV26]]
    ; GFX10-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[ICMP1]](s1)
    ; GFX10-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE2]](s32), [[UV27]]
    ; GFX10-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SEXT1]], [[SEXT]]
    ; GFX10-NEXT: [[USUBO4:%[0-9]+]]:_(s32), [[USUBO5:%[0-9]+]]:_(s1) = G_USUBO [[USUBO2]], [[UV26]]
    ; GFX10-NEXT: [[USUBE4:%[0-9]+]]:_(s32), [[USUBE5:%[0-9]+]]:_(s1) = G_USUBE [[SUB]], [[UV27]], [[USUBO3]]
    ; GFX10-NEXT: [[USUBE6:%[0-9]+]]:_(s32), [[USUBE7:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[C6]], [[USUBO5]]
    ; GFX10-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO4]](s32), [[USUBE6]](s32)
    ; GFX10-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE6]](s32), [[UV27]]
    ; GFX10-NEXT: [[SEXT2:%[0-9]+]]:_(s32) = G_SEXT [[ICMP3]](s1)
    ; GFX10-NEXT: [[ICMP4:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO4]](s32), [[UV26]]
    ; GFX10-NEXT: [[SEXT3:%[0-9]+]]:_(s32) = G_SEXT [[ICMP4]](s1)
    ; GFX10-NEXT: [[ICMP5:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE6]](s32), [[UV27]]
    ; GFX10-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP5]](s1), [[SEXT3]], [[SEXT2]]
    ; GFX10-NEXT: [[USUBO6:%[0-9]+]]:_(s32), [[USUBO7:%[0-9]+]]:_(s1) = G_USUBO [[USUBO4]], [[UV26]]
    ; GFX10-NEXT: [[USUBE8:%[0-9]+]]:_(s32), [[USUBE9:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[UV27]], [[USUBO5]]
    ; GFX10-NEXT: [[USUBE10:%[0-9]+]]:_(s32), [[USUBE11:%[0-9]+]]:_(s1) = G_USUBE [[USUBE8]], [[C6]], [[USUBO7]]
    ; GFX10-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO6]](s32), [[USUBE10]](s32)
    ; GFX10-NEXT: [[ICMP6:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT1]](s32), [[C6]]
    ; GFX10-NEXT: [[SELECT2:%[0-9]+]]:_(s64) = G_SELECT [[ICMP6]](s1), [[MV4]], [[MV3]]
    ; GFX10-NEXT: [[ICMP7:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT]](s32), [[C6]]
    ; GFX10-NEXT: [[SELECT3:%[0-9]+]]:_(s64) = G_SELECT [[ICMP7]](s1), [[SELECT2]], [[MV2]]
    ; GFX10-NEXT: [[XOR2:%[0-9]+]]:_(s64) = G_XOR [[SELECT3]], [[ASHR]]
    ; GFX10-NEXT: [[UV28:%[0-9]+]]:_(s32), [[UV29:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR2]](s64)
    ; GFX10-NEXT: [[UV30:%[0-9]+]]:_(s32), [[UV31:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX10-NEXT: [[USUBO8:%[0-9]+]]:_(s32), [[USUBO9:%[0-9]+]]:_(i1) = G_USUBO [[UV28]], [[UV30]]
    ; GFX10-NEXT: [[USUBE12:%[0-9]+]]:_(s32), [[USUBE13:%[0-9]+]]:_(i1) = G_USUBE [[UV29]], [[UV31]], [[USUBO9]]
    ; GFX10-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO8]](s32), [[USUBE12]](s32)
    ; GFX10-NEXT: $vgpr0_vgpr1 = COPY [[MV5]](s64)
    %0:_(s64) = COPY $vgpr0_vgpr1
    %1:_(s64) = COPY $vgpr2_vgpr3
    %2:_(s64) = G_SREM %0, %1
    $vgpr0_vgpr1 = COPY %2
...

---
name: test_srem_v2s64
body: |
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3, $vgpr4_vgpr5_vgpr6_vgpr7

    ; GFX6-LABEL: name: test_srem_v2s64
    ; GFX6: liveins: $vgpr0_vgpr1_vgpr2_vgpr3, $vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[COPY:%[0-9]+]]:_(<2 x s64>) = COPY $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX6-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s64>) = COPY $vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX6-NEXT: [[UV:%[0-9]+]]:_(s64), [[UV1:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[COPY]](<2 x s64>)
    ; GFX6-NEXT: [[UV2:%[0-9]+]]:_(s64), [[UV3:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[COPY1]](<2 x s64>)
    ; GFX6-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; GFX6-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[UV]], [[C]](s32)
    ; GFX6-NEXT: [[ASHR1:%[0-9]+]]:_(s64) = G_ASHR [[UV2]], [[C]](s32)
    ; GFX6-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV]](s64)
    ; GFX6-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX6-NEXT: [[UADDO:%[0-9]+]]:_(s32), [[UADDO1:%[0-9]+]]:_(i1) = G_UADDO [[UV4]], [[UV6]]
    ; GFX6-NEXT: [[UADDE:%[0-9]+]]:_(s32), [[UADDE1:%[0-9]+]]:_(i1) = G_UADDE [[UV5]], [[UV7]], [[UADDO1]]
    ; GFX6-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO]](s32), [[UADDE]](s32)
    ; GFX6-NEXT: [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV2]](s64)
    ; GFX6-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR1]](s64)
    ; GFX6-NEXT: [[UADDO2:%[0-9]+]]:_(s32), [[UADDO3:%[0-9]+]]:_(i1) = G_UADDO [[UV8]], [[UV10]]
    ; GFX6-NEXT: [[UADDE2:%[0-9]+]]:_(s32), [[UADDE3:%[0-9]+]]:_(i1) = G_UADDE [[UV9]], [[UV11]], [[UADDO3]]
    ; GFX6-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO2]](s32), [[UADDE2]](s32)
    ; GFX6-NEXT: [[XOR:%[0-9]+]]:_(s64) = G_XOR [[MV]], [[ASHR]]
    ; GFX6-NEXT: [[XOR1:%[0-9]+]]:_(s64) = G_XOR [[MV1]], [[ASHR1]]
    ; GFX6-NEXT: [[UV12:%[0-9]+]]:_(i32), [[UV13:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX6-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[UV12]](i32)
    ; GFX6-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[UV13]](i32)
    ; GFX6-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F800000
    ; GFX6-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP1]], [[C1]]
    ; GFX6-NEXT: [[FADD:%[0-9]+]]:_(f32) = G_FADD [[FMUL]], [[UITOFP]]
    ; GFX6-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD]](f32)
    ; GFX6-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x5F7FFFFC
    ; GFX6-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX6-NEXT: [[C3:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x2F800000
    ; GFX6-NEXT: [[FMUL2:%[0-9]+]]:_(f32) = G_FMUL [[FMUL1]], [[C3]]
    ; GFX6-NEXT: [[INTRINSIC_TRUNC:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL2]]
    ; GFX6-NEXT: [[C4:%[0-9]+]]:_(s32) = G_FCONSTANT float f0xCF800000
    ; GFX6-NEXT: [[FMUL3:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC]], [[C4]]
    ; GFX6-NEXT: [[FADD1:%[0-9]+]]:_(f32) = G_FADD [[FMUL3]], [[FMUL1]]
    ; GFX6-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD1]](f32)
    ; GFX6-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC]](f32)
    ; GFX6-NEXT: [[C5:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; GFX6-NEXT: [[UV14:%[0-9]+]]:_(s32), [[UV15:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX6-NEXT: [[UV16:%[0-9]+]]:_(s32), [[UV17:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX6-NEXT: [[USUBO:%[0-9]+]]:_(s32), [[USUBO1:%[0-9]+]]:_(i1) = G_USUBO [[UV14]], [[UV16]]
    ; GFX6-NEXT: [[USUBE:%[0-9]+]]:_(s32), [[USUBE1:%[0-9]+]]:_(i1) = G_USUBE [[UV15]], [[UV17]], [[USUBO1]]
    ; GFX6-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[FPTOUI]]
    ; GFX6-NEXT: [[UMULH:%[0-9]+]]:_(i32) = G_UMULH [[USUBO]], [[FPTOUI]]
    ; GFX6-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[FPTOUI1]]
    ; GFX6-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[USUBE]], [[FPTOUI]]
    ; GFX6-NEXT: [[ADD:%[0-9]+]]:_(i32) = G_ADD [[UMULH]], [[MUL1]]
    ; GFX6-NEXT: [[ADD1:%[0-9]+]]:_(i32) = G_ADD [[ADD]], [[MUL2]]
    ; GFX6-NEXT: [[UMULH1:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX6-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI]], [[ADD1]]
    ; GFX6-NEXT: [[MUL4:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[MUL]]
    ; GFX6-NEXT: [[UADDO4:%[0-9]+]]:_(i32), [[UADDO5:%[0-9]+]]:_(i1) = G_UADDO [[UMULH1]], [[MUL3]]
    ; GFX6-NEXT: [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO5]](i1)
    ; GFX6-NEXT: [[UADDO6:%[0-9]+]]:_(i32), [[UADDO7:%[0-9]+]]:_(i1) = G_UADDO [[UADDO4]], [[MUL4]]
    ; GFX6-NEXT: [[ZEXT1:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO7]](i1)
    ; GFX6-NEXT: [[ADD2:%[0-9]+]]:_(i32) = G_ADD [[ZEXT]], [[ZEXT1]]
    ; GFX6-NEXT: [[UMULH2:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[MUL]]
    ; GFX6-NEXT: [[UMULH3:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[ADD1]]
    ; GFX6-NEXT: [[MUL5:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[ADD1]]
    ; GFX6-NEXT: [[UADDO8:%[0-9]+]]:_(i32), [[UADDO9:%[0-9]+]]:_(i1) = G_UADDO [[UMULH2]], [[UMULH3]]
    ; GFX6-NEXT: [[ZEXT2:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO9]](i1)
    ; GFX6-NEXT: [[UADDO10:%[0-9]+]]:_(i32), [[UADDO11:%[0-9]+]]:_(i1) = G_UADDO [[UADDO8]], [[MUL5]]
    ; GFX6-NEXT: [[ZEXT3:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO11]](i1)
    ; GFX6-NEXT: [[ADD3:%[0-9]+]]:_(i32) = G_ADD [[ZEXT2]], [[ZEXT3]]
    ; GFX6-NEXT: [[UADDO12:%[0-9]+]]:_(i32), [[UADDO13:%[0-9]+]]:_(i1) = G_UADDO [[UADDO10]], [[ADD2]]
    ; GFX6-NEXT: [[ZEXT4:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO13]](i1)
    ; GFX6-NEXT: [[ADD4:%[0-9]+]]:_(i32) = G_ADD [[ADD3]], [[ZEXT4]]
    ; GFX6-NEXT: [[UMULH4:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[ADD1]]
    ; GFX6-NEXT: [[ADD5:%[0-9]+]]:_(i32) = G_ADD [[UMULH4]], [[ADD4]]
    ; GFX6-NEXT: [[UADDO14:%[0-9]+]]:_(s32), [[UADDO15:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI]], [[UADDO12]]
    ; GFX6-NEXT: [[UADDE4:%[0-9]+]]:_(s32), [[UADDE5:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI1]], [[ADD5]], [[UADDO15]]
    ; GFX6-NEXT: [[MUL6:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[UADDO14]]
    ; GFX6-NEXT: [[UMULH5:%[0-9]+]]:_(i32) = G_UMULH [[USUBO]], [[UADDO14]]
    ; GFX6-NEXT: [[MUL7:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[UADDE4]]
    ; GFX6-NEXT: [[MUL8:%[0-9]+]]:_(i32) = G_MUL [[USUBE]], [[UADDO14]]
    ; GFX6-NEXT: [[ADD6:%[0-9]+]]:_(i32) = G_ADD [[UMULH5]], [[MUL7]]
    ; GFX6-NEXT: [[ADD7:%[0-9]+]]:_(i32) = G_ADD [[ADD6]], [[MUL8]]
    ; GFX6-NEXT: [[UMULH6:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[MUL6]]
    ; GFX6-NEXT: [[MUL9:%[0-9]+]]:_(i32) = G_MUL [[UADDO14]], [[ADD7]]
    ; GFX6-NEXT: [[MUL10:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[MUL6]]
    ; GFX6-NEXT: [[UADDO16:%[0-9]+]]:_(i32), [[UADDO17:%[0-9]+]]:_(i1) = G_UADDO [[UMULH6]], [[MUL9]]
    ; GFX6-NEXT: [[ZEXT5:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO17]](i1)
    ; GFX6-NEXT: [[UADDO18:%[0-9]+]]:_(i32), [[UADDO19:%[0-9]+]]:_(i1) = G_UADDO [[UADDO16]], [[MUL10]]
    ; GFX6-NEXT: [[ZEXT6:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO19]](i1)
    ; GFX6-NEXT: [[ADD8:%[0-9]+]]:_(i32) = G_ADD [[ZEXT5]], [[ZEXT6]]
    ; GFX6-NEXT: [[UMULH7:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[MUL6]]
    ; GFX6-NEXT: [[UMULH8:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[ADD7]]
    ; GFX6-NEXT: [[MUL11:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[ADD7]]
    ; GFX6-NEXT: [[UADDO20:%[0-9]+]]:_(i32), [[UADDO21:%[0-9]+]]:_(i1) = G_UADDO [[UMULH7]], [[UMULH8]]
    ; GFX6-NEXT: [[ZEXT7:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO21]](i1)
    ; GFX6-NEXT: [[UADDO22:%[0-9]+]]:_(i32), [[UADDO23:%[0-9]+]]:_(i1) = G_UADDO [[UADDO20]], [[MUL11]]
    ; GFX6-NEXT: [[ZEXT8:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO23]](i1)
    ; GFX6-NEXT: [[ADD9:%[0-9]+]]:_(i32) = G_ADD [[ZEXT7]], [[ZEXT8]]
    ; GFX6-NEXT: [[UADDO24:%[0-9]+]]:_(i32), [[UADDO25:%[0-9]+]]:_(i1) = G_UADDO [[UADDO22]], [[ADD8]]
    ; GFX6-NEXT: [[ZEXT9:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO25]](i1)
    ; GFX6-NEXT: [[ADD10:%[0-9]+]]:_(i32) = G_ADD [[ADD9]], [[ZEXT9]]
    ; GFX6-NEXT: [[UMULH9:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[ADD7]]
    ; GFX6-NEXT: [[ADD11:%[0-9]+]]:_(i32) = G_ADD [[UMULH9]], [[ADD10]]
    ; GFX6-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX6-NEXT: [[UADDO26:%[0-9]+]]:_(s32), [[UADDO27:%[0-9]+]]:_(s1) = G_UADDO [[UADDO14]], [[UADDO24]]
    ; GFX6-NEXT: [[UADDE6:%[0-9]+]]:_(s32), [[UADDE7:%[0-9]+]]:_(s1) = G_UADDE [[UADDE4]], [[ADD11]], [[UADDO27]]
    ; GFX6-NEXT: [[UV18:%[0-9]+]]:_(i32), [[UV19:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX6-NEXT: [[UV20:%[0-9]+]]:_(i32), [[UV21:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX6-NEXT: [[UMULH10:%[0-9]+]]:_(i32) = G_UMULH [[UV20]], [[UADDO26]]
    ; GFX6-NEXT: [[MUL12:%[0-9]+]]:_(i32) = G_MUL [[UV20]], [[UADDE6]]
    ; GFX6-NEXT: [[MUL13:%[0-9]+]]:_(i32) = G_MUL [[UV21]], [[UADDO26]]
    ; GFX6-NEXT: [[UADDO28:%[0-9]+]]:_(i32), [[UADDO29:%[0-9]+]]:_(i1) = G_UADDO [[UMULH10]], [[MUL12]]
    ; GFX6-NEXT: [[ZEXT10:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO29]](i1)
    ; GFX6-NEXT: [[UADDO30:%[0-9]+]]:_(i32), [[UADDO31:%[0-9]+]]:_(i1) = G_UADDO [[UADDO28]], [[MUL13]]
    ; GFX6-NEXT: [[ZEXT11:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO31]](i1)
    ; GFX6-NEXT: [[ADD12:%[0-9]+]]:_(i32) = G_ADD [[ZEXT10]], [[ZEXT11]]
    ; GFX6-NEXT: [[UMULH11:%[0-9]+]]:_(i32) = G_UMULH [[UV21]], [[UADDO26]]
    ; GFX6-NEXT: [[UMULH12:%[0-9]+]]:_(i32) = G_UMULH [[UV20]], [[UADDE6]]
    ; GFX6-NEXT: [[MUL14:%[0-9]+]]:_(i32) = G_MUL [[UV21]], [[UADDE6]]
    ; GFX6-NEXT: [[UADDO32:%[0-9]+]]:_(i32), [[UADDO33:%[0-9]+]]:_(i1) = G_UADDO [[UMULH11]], [[UMULH12]]
    ; GFX6-NEXT: [[ZEXT12:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO33]](i1)
    ; GFX6-NEXT: [[UADDO34:%[0-9]+]]:_(i32), [[UADDO35:%[0-9]+]]:_(i1) = G_UADDO [[UADDO32]], [[MUL14]]
    ; GFX6-NEXT: [[ZEXT13:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO35]](i1)
    ; GFX6-NEXT: [[ADD13:%[0-9]+]]:_(i32) = G_ADD [[ZEXT12]], [[ZEXT13]]
    ; GFX6-NEXT: [[UADDO36:%[0-9]+]]:_(i32), [[UADDO37:%[0-9]+]]:_(i1) = G_UADDO [[UADDO34]], [[ADD12]]
    ; GFX6-NEXT: [[ZEXT14:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO37]](i1)
    ; GFX6-NEXT: [[ADD14:%[0-9]+]]:_(i32) = G_ADD [[ADD13]], [[ZEXT14]]
    ; GFX6-NEXT: [[UMULH13:%[0-9]+]]:_(i32) = G_UMULH [[UV21]], [[UADDE6]]
    ; GFX6-NEXT: [[ADD15:%[0-9]+]]:_(i32) = G_ADD [[UMULH13]], [[ADD14]]
    ; GFX6-NEXT: [[UV22:%[0-9]+]]:_(i32), [[UV23:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX6-NEXT: [[MUL15:%[0-9]+]]:_(i32) = G_MUL [[UV22]], [[UADDO36]]
    ; GFX6-NEXT: [[UMULH14:%[0-9]+]]:_(i32) = G_UMULH [[UV22]], [[UADDO36]]
    ; GFX6-NEXT: [[MUL16:%[0-9]+]]:_(i32) = G_MUL [[UV22]], [[ADD15]]
    ; GFX6-NEXT: [[MUL17:%[0-9]+]]:_(i32) = G_MUL [[UV23]], [[UADDO36]]
    ; GFX6-NEXT: [[ADD16:%[0-9]+]]:_(i32) = G_ADD [[UMULH14]], [[MUL16]]
    ; GFX6-NEXT: [[ADD17:%[0-9]+]]:_(i32) = G_ADD [[ADD16]], [[MUL17]]
    ; GFX6-NEXT: [[USUBO2:%[0-9]+]]:_(s32), [[USUBO3:%[0-9]+]]:_(s1) = G_USUBO [[UV18]], [[MUL15]]
    ; GFX6-NEXT: [[USUBE2:%[0-9]+]]:_(s32), [[USUBE3:%[0-9]+]]:_(s1) = G_USUBE [[UV19]], [[ADD17]], [[USUBO3]]
    ; GFX6-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[UV19]], [[ADD17]]
    ; GFX6-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO2]](s32), [[USUBE2]](s32)
    ; GFX6-NEXT: [[UV24:%[0-9]+]]:_(i32), [[UV25:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX6-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE2]](s32), [[UV25]]
    ; GFX6-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[ICMP]](s1)
    ; GFX6-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO2]](s32), [[UV24]]
    ; GFX6-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[ICMP1]](s1)
    ; GFX6-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE2]](s32), [[UV25]]
    ; GFX6-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SEXT1]], [[SEXT]]
    ; GFX6-NEXT: [[USUBO4:%[0-9]+]]:_(s32), [[USUBO5:%[0-9]+]]:_(s1) = G_USUBO [[USUBO2]], [[UV24]]
    ; GFX6-NEXT: [[USUBE4:%[0-9]+]]:_(s32), [[USUBE5:%[0-9]+]]:_(s1) = G_USUBE [[SUB]], [[UV25]], [[USUBO3]]
    ; GFX6-NEXT: [[USUBE6:%[0-9]+]]:_(s32), [[USUBE7:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[C6]], [[USUBO5]]
    ; GFX6-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO4]](s32), [[USUBE6]](s32)
    ; GFX6-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE6]](s32), [[UV25]]
    ; GFX6-NEXT: [[SEXT2:%[0-9]+]]:_(s32) = G_SEXT [[ICMP3]](s1)
    ; GFX6-NEXT: [[ICMP4:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO4]](s32), [[UV24]]
    ; GFX6-NEXT: [[SEXT3:%[0-9]+]]:_(s32) = G_SEXT [[ICMP4]](s1)
    ; GFX6-NEXT: [[ICMP5:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE6]](s32), [[UV25]]
    ; GFX6-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP5]](s1), [[SEXT3]], [[SEXT2]]
    ; GFX6-NEXT: [[USUBO6:%[0-9]+]]:_(s32), [[USUBO7:%[0-9]+]]:_(s1) = G_USUBO [[USUBO4]], [[UV24]]
    ; GFX6-NEXT: [[USUBE8:%[0-9]+]]:_(s32), [[USUBE9:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[UV25]], [[USUBO5]]
    ; GFX6-NEXT: [[USUBE10:%[0-9]+]]:_(s32), [[USUBE11:%[0-9]+]]:_(s1) = G_USUBE [[USUBE8]], [[C6]], [[USUBO7]]
    ; GFX6-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO6]](s32), [[USUBE10]](s32)
    ; GFX6-NEXT: [[ICMP6:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT1]](s32), [[C6]]
    ; GFX6-NEXT: [[SELECT2:%[0-9]+]]:_(s64) = G_SELECT [[ICMP6]](s1), [[MV4]], [[MV3]]
    ; GFX6-NEXT: [[ICMP7:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT]](s32), [[C6]]
    ; GFX6-NEXT: [[SELECT3:%[0-9]+]]:_(s64) = G_SELECT [[ICMP7]](s1), [[SELECT2]], [[MV2]]
    ; GFX6-NEXT: [[XOR2:%[0-9]+]]:_(s64) = G_XOR [[SELECT3]], [[ASHR]]
    ; GFX6-NEXT: [[UV26:%[0-9]+]]:_(s32), [[UV27:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR2]](s64)
    ; GFX6-NEXT: [[UV28:%[0-9]+]]:_(s32), [[UV29:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX6-NEXT: [[USUBO8:%[0-9]+]]:_(s32), [[USUBO9:%[0-9]+]]:_(i1) = G_USUBO [[UV26]], [[UV28]]
    ; GFX6-NEXT: [[USUBE12:%[0-9]+]]:_(s32), [[USUBE13:%[0-9]+]]:_(i1) = G_USUBE [[UV27]], [[UV29]], [[USUBO9]]
    ; GFX6-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO8]](s32), [[USUBE12]](s32)
    ; GFX6-NEXT: [[ASHR2:%[0-9]+]]:_(s64) = G_ASHR [[UV1]], [[C]](s32)
    ; GFX6-NEXT: [[ASHR3:%[0-9]+]]:_(s64) = G_ASHR [[UV3]], [[C]](s32)
    ; GFX6-NEXT: [[UV30:%[0-9]+]]:_(s32), [[UV31:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV1]](s64)
    ; GFX6-NEXT: [[UV32:%[0-9]+]]:_(s32), [[UV33:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR2]](s64)
    ; GFX6-NEXT: [[UADDO38:%[0-9]+]]:_(s32), [[UADDO39:%[0-9]+]]:_(i1) = G_UADDO [[UV30]], [[UV32]]
    ; GFX6-NEXT: [[UADDE8:%[0-9]+]]:_(s32), [[UADDE9:%[0-9]+]]:_(i1) = G_UADDE [[UV31]], [[UV33]], [[UADDO39]]
    ; GFX6-NEXT: [[MV6:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO38]](s32), [[UADDE8]](s32)
    ; GFX6-NEXT: [[UV34:%[0-9]+]]:_(s32), [[UV35:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV3]](s64)
    ; GFX6-NEXT: [[UV36:%[0-9]+]]:_(s32), [[UV37:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR3]](s64)
    ; GFX6-NEXT: [[UADDO40:%[0-9]+]]:_(s32), [[UADDO41:%[0-9]+]]:_(i1) = G_UADDO [[UV34]], [[UV36]]
    ; GFX6-NEXT: [[UADDE10:%[0-9]+]]:_(s32), [[UADDE11:%[0-9]+]]:_(i1) = G_UADDE [[UV35]], [[UV37]], [[UADDO41]]
    ; GFX6-NEXT: [[MV7:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO40]](s32), [[UADDE10]](s32)
    ; GFX6-NEXT: [[XOR3:%[0-9]+]]:_(s64) = G_XOR [[MV6]], [[ASHR2]]
    ; GFX6-NEXT: [[XOR4:%[0-9]+]]:_(s64) = G_XOR [[MV7]], [[ASHR3]]
    ; GFX6-NEXT: [[UV38:%[0-9]+]]:_(i32), [[UV39:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX6-NEXT: [[UITOFP2:%[0-9]+]]:_(f32) = G_UITOFP [[UV38]](i32)
    ; GFX6-NEXT: [[UITOFP3:%[0-9]+]]:_(f32) = G_UITOFP [[UV39]](i32)
    ; GFX6-NEXT: [[FMUL4:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP3]], [[C1]]
    ; GFX6-NEXT: [[FADD2:%[0-9]+]]:_(f32) = G_FADD [[FMUL4]], [[UITOFP2]]
    ; GFX6-NEXT: [[AMDGPU_RCP_IFLAG1:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD2]](f32)
    ; GFX6-NEXT: [[FMUL5:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG1]], [[C2]]
    ; GFX6-NEXT: [[FMUL6:%[0-9]+]]:_(f32) = G_FMUL [[FMUL5]], [[C3]]
    ; GFX6-NEXT: [[INTRINSIC_TRUNC1:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL6]]
    ; GFX6-NEXT: [[FMUL7:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC1]], [[C4]]
    ; GFX6-NEXT: [[FADD3:%[0-9]+]]:_(f32) = G_FADD [[FMUL7]], [[FMUL5]]
    ; GFX6-NEXT: [[FPTOUI2:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD3]](f32)
    ; GFX6-NEXT: [[FPTOUI3:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC1]](f32)
    ; GFX6-NEXT: [[UV40:%[0-9]+]]:_(s32), [[UV41:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX6-NEXT: [[UV42:%[0-9]+]]:_(s32), [[UV43:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX6-NEXT: [[USUBO10:%[0-9]+]]:_(s32), [[USUBO11:%[0-9]+]]:_(i1) = G_USUBO [[UV40]], [[UV42]]
    ; GFX6-NEXT: [[USUBE14:%[0-9]+]]:_(s32), [[USUBE15:%[0-9]+]]:_(i1) = G_USUBE [[UV41]], [[UV43]], [[USUBO11]]
    ; GFX6-NEXT: [[MUL18:%[0-9]+]]:_(i32) = G_MUL [[USUBO10]], [[FPTOUI2]]
    ; GFX6-NEXT: [[UMULH15:%[0-9]+]]:_(i32) = G_UMULH [[USUBO10]], [[FPTOUI2]]
    ; GFX6-NEXT: [[MUL19:%[0-9]+]]:_(i32) = G_MUL [[USUBO10]], [[FPTOUI3]]
    ; GFX6-NEXT: [[MUL20:%[0-9]+]]:_(i32) = G_MUL [[USUBE14]], [[FPTOUI2]]
    ; GFX6-NEXT: [[ADD18:%[0-9]+]]:_(i32) = G_ADD [[UMULH15]], [[MUL19]]
    ; GFX6-NEXT: [[ADD19:%[0-9]+]]:_(i32) = G_ADD [[ADD18]], [[MUL20]]
    ; GFX6-NEXT: [[UMULH16:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI2]], [[MUL18]]
    ; GFX6-NEXT: [[MUL21:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI2]], [[ADD19]]
    ; GFX6-NEXT: [[MUL22:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI3]], [[MUL18]]
    ; GFX6-NEXT: [[UADDO42:%[0-9]+]]:_(i32), [[UADDO43:%[0-9]+]]:_(i1) = G_UADDO [[UMULH16]], [[MUL21]]
    ; GFX6-NEXT: [[ZEXT15:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO43]](i1)
    ; GFX6-NEXT: [[UADDO44:%[0-9]+]]:_(i32), [[UADDO45:%[0-9]+]]:_(i1) = G_UADDO [[UADDO42]], [[MUL22]]
    ; GFX6-NEXT: [[ZEXT16:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO45]](i1)
    ; GFX6-NEXT: [[ADD20:%[0-9]+]]:_(i32) = G_ADD [[ZEXT15]], [[ZEXT16]]
    ; GFX6-NEXT: [[UMULH17:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI3]], [[MUL18]]
    ; GFX6-NEXT: [[UMULH18:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI2]], [[ADD19]]
    ; GFX6-NEXT: [[MUL23:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI3]], [[ADD19]]
    ; GFX6-NEXT: [[UADDO46:%[0-9]+]]:_(i32), [[UADDO47:%[0-9]+]]:_(i1) = G_UADDO [[UMULH17]], [[UMULH18]]
    ; GFX6-NEXT: [[ZEXT17:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO47]](i1)
    ; GFX6-NEXT: [[UADDO48:%[0-9]+]]:_(i32), [[UADDO49:%[0-9]+]]:_(i1) = G_UADDO [[UADDO46]], [[MUL23]]
    ; GFX6-NEXT: [[ZEXT18:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO49]](i1)
    ; GFX6-NEXT: [[ADD21:%[0-9]+]]:_(i32) = G_ADD [[ZEXT17]], [[ZEXT18]]
    ; GFX6-NEXT: [[UADDO50:%[0-9]+]]:_(i32), [[UADDO51:%[0-9]+]]:_(i1) = G_UADDO [[UADDO48]], [[ADD20]]
    ; GFX6-NEXT: [[ZEXT19:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO51]](i1)
    ; GFX6-NEXT: [[ADD22:%[0-9]+]]:_(i32) = G_ADD [[ADD21]], [[ZEXT19]]
    ; GFX6-NEXT: [[UMULH19:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI3]], [[ADD19]]
    ; GFX6-NEXT: [[ADD23:%[0-9]+]]:_(i32) = G_ADD [[UMULH19]], [[ADD22]]
    ; GFX6-NEXT: [[UADDO52:%[0-9]+]]:_(s32), [[UADDO53:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI2]], [[UADDO50]]
    ; GFX6-NEXT: [[UADDE12:%[0-9]+]]:_(s32), [[UADDE13:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI3]], [[ADD23]], [[UADDO53]]
    ; GFX6-NEXT: [[MUL24:%[0-9]+]]:_(i32) = G_MUL [[USUBO10]], [[UADDO52]]
    ; GFX6-NEXT: [[UMULH20:%[0-9]+]]:_(i32) = G_UMULH [[USUBO10]], [[UADDO52]]
    ; GFX6-NEXT: [[MUL25:%[0-9]+]]:_(i32) = G_MUL [[USUBO10]], [[UADDE12]]
    ; GFX6-NEXT: [[MUL26:%[0-9]+]]:_(i32) = G_MUL [[USUBE14]], [[UADDO52]]
    ; GFX6-NEXT: [[ADD24:%[0-9]+]]:_(i32) = G_ADD [[UMULH20]], [[MUL25]]
    ; GFX6-NEXT: [[ADD25:%[0-9]+]]:_(i32) = G_ADD [[ADD24]], [[MUL26]]
    ; GFX6-NEXT: [[UMULH21:%[0-9]+]]:_(i32) = G_UMULH [[UADDO52]], [[MUL24]]
    ; GFX6-NEXT: [[MUL27:%[0-9]+]]:_(i32) = G_MUL [[UADDO52]], [[ADD25]]
    ; GFX6-NEXT: [[MUL28:%[0-9]+]]:_(i32) = G_MUL [[UADDE12]], [[MUL24]]
    ; GFX6-NEXT: [[UADDO54:%[0-9]+]]:_(i32), [[UADDO55:%[0-9]+]]:_(i1) = G_UADDO [[UMULH21]], [[MUL27]]
    ; GFX6-NEXT: [[ZEXT20:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO55]](i1)
    ; GFX6-NEXT: [[UADDO56:%[0-9]+]]:_(i32), [[UADDO57:%[0-9]+]]:_(i1) = G_UADDO [[UADDO54]], [[MUL28]]
    ; GFX6-NEXT: [[ZEXT21:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO57]](i1)
    ; GFX6-NEXT: [[ADD26:%[0-9]+]]:_(i32) = G_ADD [[ZEXT20]], [[ZEXT21]]
    ; GFX6-NEXT: [[UMULH22:%[0-9]+]]:_(i32) = G_UMULH [[UADDE12]], [[MUL24]]
    ; GFX6-NEXT: [[UMULH23:%[0-9]+]]:_(i32) = G_UMULH [[UADDO52]], [[ADD25]]
    ; GFX6-NEXT: [[MUL29:%[0-9]+]]:_(i32) = G_MUL [[UADDE12]], [[ADD25]]
    ; GFX6-NEXT: [[UADDO58:%[0-9]+]]:_(i32), [[UADDO59:%[0-9]+]]:_(i1) = G_UADDO [[UMULH22]], [[UMULH23]]
    ; GFX6-NEXT: [[ZEXT22:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO59]](i1)
    ; GFX6-NEXT: [[UADDO60:%[0-9]+]]:_(i32), [[UADDO61:%[0-9]+]]:_(i1) = G_UADDO [[UADDO58]], [[MUL29]]
    ; GFX6-NEXT: [[ZEXT23:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO61]](i1)
    ; GFX6-NEXT: [[ADD27:%[0-9]+]]:_(i32) = G_ADD [[ZEXT22]], [[ZEXT23]]
    ; GFX6-NEXT: [[UADDO62:%[0-9]+]]:_(i32), [[UADDO63:%[0-9]+]]:_(i1) = G_UADDO [[UADDO60]], [[ADD26]]
    ; GFX6-NEXT: [[ZEXT24:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO63]](i1)
    ; GFX6-NEXT: [[ADD28:%[0-9]+]]:_(i32) = G_ADD [[ADD27]], [[ZEXT24]]
    ; GFX6-NEXT: [[UMULH24:%[0-9]+]]:_(i32) = G_UMULH [[UADDE12]], [[ADD25]]
    ; GFX6-NEXT: [[ADD29:%[0-9]+]]:_(i32) = G_ADD [[UMULH24]], [[ADD28]]
    ; GFX6-NEXT: [[UADDO64:%[0-9]+]]:_(s32), [[UADDO65:%[0-9]+]]:_(s1) = G_UADDO [[UADDO52]], [[UADDO62]]
    ; GFX6-NEXT: [[UADDE14:%[0-9]+]]:_(s32), [[UADDE15:%[0-9]+]]:_(s1) = G_UADDE [[UADDE12]], [[ADD29]], [[UADDO65]]
    ; GFX6-NEXT: [[UV44:%[0-9]+]]:_(i32), [[UV45:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR3]](s64)
    ; GFX6-NEXT: [[UV46:%[0-9]+]]:_(i32), [[UV47:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR3]](s64)
    ; GFX6-NEXT: [[UMULH25:%[0-9]+]]:_(i32) = G_UMULH [[UV46]], [[UADDO64]]
    ; GFX6-NEXT: [[MUL30:%[0-9]+]]:_(i32) = G_MUL [[UV46]], [[UADDE14]]
    ; GFX6-NEXT: [[MUL31:%[0-9]+]]:_(i32) = G_MUL [[UV47]], [[UADDO64]]
    ; GFX6-NEXT: [[UADDO66:%[0-9]+]]:_(i32), [[UADDO67:%[0-9]+]]:_(i1) = G_UADDO [[UMULH25]], [[MUL30]]
    ; GFX6-NEXT: [[ZEXT25:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO67]](i1)
    ; GFX6-NEXT: [[UADDO68:%[0-9]+]]:_(i32), [[UADDO69:%[0-9]+]]:_(i1) = G_UADDO [[UADDO66]], [[MUL31]]
    ; GFX6-NEXT: [[ZEXT26:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO69]](i1)
    ; GFX6-NEXT: [[ADD30:%[0-9]+]]:_(i32) = G_ADD [[ZEXT25]], [[ZEXT26]]
    ; GFX6-NEXT: [[UMULH26:%[0-9]+]]:_(i32) = G_UMULH [[UV47]], [[UADDO64]]
    ; GFX6-NEXT: [[UMULH27:%[0-9]+]]:_(i32) = G_UMULH [[UV46]], [[UADDE14]]
    ; GFX6-NEXT: [[MUL32:%[0-9]+]]:_(i32) = G_MUL [[UV47]], [[UADDE14]]
    ; GFX6-NEXT: [[UADDO70:%[0-9]+]]:_(i32), [[UADDO71:%[0-9]+]]:_(i1) = G_UADDO [[UMULH26]], [[UMULH27]]
    ; GFX6-NEXT: [[ZEXT27:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO71]](i1)
    ; GFX6-NEXT: [[UADDO72:%[0-9]+]]:_(i32), [[UADDO73:%[0-9]+]]:_(i1) = G_UADDO [[UADDO70]], [[MUL32]]
    ; GFX6-NEXT: [[ZEXT28:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO73]](i1)
    ; GFX6-NEXT: [[ADD31:%[0-9]+]]:_(i32) = G_ADD [[ZEXT27]], [[ZEXT28]]
    ; GFX6-NEXT: [[UADDO74:%[0-9]+]]:_(i32), [[UADDO75:%[0-9]+]]:_(i1) = G_UADDO [[UADDO72]], [[ADD30]]
    ; GFX6-NEXT: [[ZEXT29:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO75]](i1)
    ; GFX6-NEXT: [[ADD32:%[0-9]+]]:_(i32) = G_ADD [[ADD31]], [[ZEXT29]]
    ; GFX6-NEXT: [[UMULH28:%[0-9]+]]:_(i32) = G_UMULH [[UV47]], [[UADDE14]]
    ; GFX6-NEXT: [[ADD33:%[0-9]+]]:_(i32) = G_ADD [[UMULH28]], [[ADD32]]
    ; GFX6-NEXT: [[UV48:%[0-9]+]]:_(i32), [[UV49:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX6-NEXT: [[MUL33:%[0-9]+]]:_(i32) = G_MUL [[UV48]], [[UADDO74]]
    ; GFX6-NEXT: [[UMULH29:%[0-9]+]]:_(i32) = G_UMULH [[UV48]], [[UADDO74]]
    ; GFX6-NEXT: [[MUL34:%[0-9]+]]:_(i32) = G_MUL [[UV48]], [[ADD33]]
    ; GFX6-NEXT: [[MUL35:%[0-9]+]]:_(i32) = G_MUL [[UV49]], [[UADDO74]]
    ; GFX6-NEXT: [[ADD34:%[0-9]+]]:_(i32) = G_ADD [[UMULH29]], [[MUL34]]
    ; GFX6-NEXT: [[ADD35:%[0-9]+]]:_(i32) = G_ADD [[ADD34]], [[MUL35]]
    ; GFX6-NEXT: [[USUBO12:%[0-9]+]]:_(s32), [[USUBO13:%[0-9]+]]:_(s1) = G_USUBO [[UV44]], [[MUL33]]
    ; GFX6-NEXT: [[USUBE16:%[0-9]+]]:_(s32), [[USUBE17:%[0-9]+]]:_(s1) = G_USUBE [[UV45]], [[ADD35]], [[USUBO13]]
    ; GFX6-NEXT: [[SUB1:%[0-9]+]]:_(s32) = G_SUB [[UV45]], [[ADD35]]
    ; GFX6-NEXT: [[MV8:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO12]](s32), [[USUBE16]](s32)
    ; GFX6-NEXT: [[UV50:%[0-9]+]]:_(i32), [[UV51:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX6-NEXT: [[ICMP8:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE16]](s32), [[UV51]]
    ; GFX6-NEXT: [[SEXT4:%[0-9]+]]:_(s32) = G_SEXT [[ICMP8]](s1)
    ; GFX6-NEXT: [[ICMP9:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO12]](s32), [[UV50]]
    ; GFX6-NEXT: [[SEXT5:%[0-9]+]]:_(s32) = G_SEXT [[ICMP9]](s1)
    ; GFX6-NEXT: [[ICMP10:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE16]](s32), [[UV51]]
    ; GFX6-NEXT: [[SELECT4:%[0-9]+]]:_(s32) = G_SELECT [[ICMP10]](s1), [[SEXT5]], [[SEXT4]]
    ; GFX6-NEXT: [[USUBO14:%[0-9]+]]:_(s32), [[USUBO15:%[0-9]+]]:_(s1) = G_USUBO [[USUBO12]], [[UV50]]
    ; GFX6-NEXT: [[USUBE18:%[0-9]+]]:_(s32), [[USUBE19:%[0-9]+]]:_(s1) = G_USUBE [[SUB1]], [[UV51]], [[USUBO13]]
    ; GFX6-NEXT: [[USUBE20:%[0-9]+]]:_(s32), [[USUBE21:%[0-9]+]]:_(s1) = G_USUBE [[USUBE18]], [[C6]], [[USUBO15]]
    ; GFX6-NEXT: [[MV9:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO14]](s32), [[USUBE20]](s32)
    ; GFX6-NEXT: [[ICMP11:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE20]](s32), [[UV51]]
    ; GFX6-NEXT: [[SEXT6:%[0-9]+]]:_(s32) = G_SEXT [[ICMP11]](s1)
    ; GFX6-NEXT: [[ICMP12:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO14]](s32), [[UV50]]
    ; GFX6-NEXT: [[SEXT7:%[0-9]+]]:_(s32) = G_SEXT [[ICMP12]](s1)
    ; GFX6-NEXT: [[ICMP13:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE20]](s32), [[UV51]]
    ; GFX6-NEXT: [[SELECT5:%[0-9]+]]:_(s32) = G_SELECT [[ICMP13]](s1), [[SEXT7]], [[SEXT6]]
    ; GFX6-NEXT: [[USUBO16:%[0-9]+]]:_(s32), [[USUBO17:%[0-9]+]]:_(s1) = G_USUBO [[USUBO14]], [[UV50]]
    ; GFX6-NEXT: [[USUBE22:%[0-9]+]]:_(s32), [[USUBE23:%[0-9]+]]:_(s1) = G_USUBE [[USUBE18]], [[UV51]], [[USUBO15]]
    ; GFX6-NEXT: [[USUBE24:%[0-9]+]]:_(s32), [[USUBE25:%[0-9]+]]:_(s1) = G_USUBE [[USUBE22]], [[C6]], [[USUBO17]]
    ; GFX6-NEXT: [[MV10:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO16]](s32), [[USUBE24]](s32)
    ; GFX6-NEXT: [[ICMP14:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT5]](s32), [[C6]]
    ; GFX6-NEXT: [[SELECT6:%[0-9]+]]:_(s64) = G_SELECT [[ICMP14]](s1), [[MV10]], [[MV9]]
    ; GFX6-NEXT: [[ICMP15:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT4]](s32), [[C6]]
    ; GFX6-NEXT: [[SELECT7:%[0-9]+]]:_(s64) = G_SELECT [[ICMP15]](s1), [[SELECT6]], [[MV8]]
    ; GFX6-NEXT: [[XOR5:%[0-9]+]]:_(s64) = G_XOR [[SELECT7]], [[ASHR2]]
    ; GFX6-NEXT: [[UV52:%[0-9]+]]:_(s32), [[UV53:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR5]](s64)
    ; GFX6-NEXT: [[UV54:%[0-9]+]]:_(s32), [[UV55:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR2]](s64)
    ; GFX6-NEXT: [[USUBO18:%[0-9]+]]:_(s32), [[USUBO19:%[0-9]+]]:_(i1) = G_USUBO [[UV52]], [[UV54]]
    ; GFX6-NEXT: [[USUBE26:%[0-9]+]]:_(s32), [[USUBE27:%[0-9]+]]:_(i1) = G_USUBE [[UV53]], [[UV55]], [[USUBO19]]
    ; GFX6-NEXT: [[MV11:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO18]](s32), [[USUBE26]](s32)
    ; GFX6-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s64>) = G_BUILD_VECTOR [[MV5]](s64), [[MV11]](s64)
    ; GFX6-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3 = COPY [[BUILD_VECTOR]](<2 x s64>)
    ;
    ; GFX8-LABEL: name: test_srem_v2s64
    ; GFX8: liveins: $vgpr0_vgpr1_vgpr2_vgpr3, $vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:_(<2 x s64>) = COPY $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX8-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s64>) = COPY $vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX8-NEXT: [[UV:%[0-9]+]]:_(s64), [[UV1:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[COPY]](<2 x s64>)
    ; GFX8-NEXT: [[UV2:%[0-9]+]]:_(s64), [[UV3:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[COPY1]](<2 x s64>)
    ; GFX8-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; GFX8-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[UV]], [[C]](s32)
    ; GFX8-NEXT: [[ASHR1:%[0-9]+]]:_(s64) = G_ASHR [[UV2]], [[C]](s32)
    ; GFX8-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV]](s64)
    ; GFX8-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX8-NEXT: [[UADDO:%[0-9]+]]:_(s32), [[UADDO1:%[0-9]+]]:_(i1) = G_UADDO [[UV4]], [[UV6]]
    ; GFX8-NEXT: [[UADDE:%[0-9]+]]:_(s32), [[UADDE1:%[0-9]+]]:_(i1) = G_UADDE [[UV5]], [[UV7]], [[UADDO1]]
    ; GFX8-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO]](s32), [[UADDE]](s32)
    ; GFX8-NEXT: [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV2]](s64)
    ; GFX8-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR1]](s64)
    ; GFX8-NEXT: [[UADDO2:%[0-9]+]]:_(s32), [[UADDO3:%[0-9]+]]:_(i1) = G_UADDO [[UV8]], [[UV10]]
    ; GFX8-NEXT: [[UADDE2:%[0-9]+]]:_(s32), [[UADDE3:%[0-9]+]]:_(i1) = G_UADDE [[UV9]], [[UV11]], [[UADDO3]]
    ; GFX8-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO2]](s32), [[UADDE2]](s32)
    ; GFX8-NEXT: [[XOR:%[0-9]+]]:_(s64) = G_XOR [[MV]], [[ASHR]]
    ; GFX8-NEXT: [[XOR1:%[0-9]+]]:_(s64) = G_XOR [[MV1]], [[ASHR1]]
    ; GFX8-NEXT: [[UV12:%[0-9]+]]:_(i32), [[UV13:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX8-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[UV12]](i32)
    ; GFX8-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[UV13]](i32)
    ; GFX8-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F800000
    ; GFX8-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP1]], [[C1]]
    ; GFX8-NEXT: [[FADD:%[0-9]+]]:_(f32) = G_FADD [[FMUL]], [[UITOFP]]
    ; GFX8-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD]](f32)
    ; GFX8-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x5F7FFFFC
    ; GFX8-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX8-NEXT: [[C3:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x2F800000
    ; GFX8-NEXT: [[FMUL2:%[0-9]+]]:_(f32) = G_FMUL [[FMUL1]], [[C3]]
    ; GFX8-NEXT: [[INTRINSIC_TRUNC:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL2]]
    ; GFX8-NEXT: [[C4:%[0-9]+]]:_(s32) = G_FCONSTANT float f0xCF800000
    ; GFX8-NEXT: [[FMUL3:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC]], [[C4]]
    ; GFX8-NEXT: [[FADD1:%[0-9]+]]:_(f32) = G_FADD [[FMUL3]], [[FMUL1]]
    ; GFX8-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD1]](f32)
    ; GFX8-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC]](f32)
    ; GFX8-NEXT: [[C5:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; GFX8-NEXT: [[UV14:%[0-9]+]]:_(s32), [[UV15:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX8-NEXT: [[UV16:%[0-9]+]]:_(s32), [[UV17:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX8-NEXT: [[USUBO:%[0-9]+]]:_(s32), [[USUBO1:%[0-9]+]]:_(i1) = G_USUBO [[UV14]], [[UV16]]
    ; GFX8-NEXT: [[USUBE:%[0-9]+]]:_(s32), [[USUBE1:%[0-9]+]]:_(i1) = G_USUBE [[UV15]], [[UV17]], [[USUBO1]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_1:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[FPTOUI]], [[C5]]
    ; GFX8-NEXT: [[UV18:%[0-9]+]]:_(i32), [[UV19:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_]](s64)
    ; GFX8-NEXT: [[ANYEXT:%[0-9]+]]:_(s64) = G_ANYEXT [[UV19]](i32)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_2:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_3:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[FPTOUI1]], [[ANYEXT]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_4:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_5:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE]](s32), [[FPTOUI]], [[AMDGPU_MAD_U64_U32_2]]
    ; GFX8-NEXT: [[UV20:%[0-9]+]]:_(i32), [[UV21:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_4]](s64)
    ; GFX8-NEXT: [[UMULH:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[UV18]]
    ; GFX8-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI]], [[UV20]]
    ; GFX8-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[UV18]]
    ; GFX8-NEXT: [[UADDO4:%[0-9]+]]:_(i32), [[UADDO5:%[0-9]+]]:_(i1) = G_UADDO [[UMULH]], [[MUL]]
    ; GFX8-NEXT: [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO5]](i1)
    ; GFX8-NEXT: [[UADDO6:%[0-9]+]]:_(i32), [[UADDO7:%[0-9]+]]:_(i1) = G_UADDO [[UADDO4]], [[MUL1]]
    ; GFX8-NEXT: [[ZEXT1:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO7]](i1)
    ; GFX8-NEXT: [[ADD:%[0-9]+]]:_(i32) = G_ADD [[ZEXT]], [[ZEXT1]]
    ; GFX8-NEXT: [[UMULH1:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[UV18]]
    ; GFX8-NEXT: [[UMULH2:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[UV20]]
    ; GFX8-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[UV20]]
    ; GFX8-NEXT: [[UADDO8:%[0-9]+]]:_(i32), [[UADDO9:%[0-9]+]]:_(i1) = G_UADDO [[UMULH1]], [[UMULH2]]
    ; GFX8-NEXT: [[ZEXT2:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO9]](i1)
    ; GFX8-NEXT: [[UADDO10:%[0-9]+]]:_(i32), [[UADDO11:%[0-9]+]]:_(i1) = G_UADDO [[UADDO8]], [[MUL2]]
    ; GFX8-NEXT: [[ZEXT3:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO11]](i1)
    ; GFX8-NEXT: [[ADD1:%[0-9]+]]:_(i32) = G_ADD [[ZEXT2]], [[ZEXT3]]
    ; GFX8-NEXT: [[UADDO12:%[0-9]+]]:_(i32), [[UADDO13:%[0-9]+]]:_(i1) = G_UADDO [[UADDO10]], [[ADD]]
    ; GFX8-NEXT: [[ZEXT4:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO13]](i1)
    ; GFX8-NEXT: [[ADD2:%[0-9]+]]:_(i32) = G_ADD [[ADD1]], [[ZEXT4]]
    ; GFX8-NEXT: [[UMULH3:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[UV20]]
    ; GFX8-NEXT: [[ADD3:%[0-9]+]]:_(i32) = G_ADD [[UMULH3]], [[ADD2]]
    ; GFX8-NEXT: [[UADDO14:%[0-9]+]]:_(s32), [[UADDO15:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI]], [[UADDO12]]
    ; GFX8-NEXT: [[UADDE4:%[0-9]+]]:_(s32), [[UADDE5:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI1]], [[ADD3]], [[UADDO15]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_6:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_7:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[UADDO14]], [[C5]]
    ; GFX8-NEXT: [[UV22:%[0-9]+]]:_(i32), [[UV23:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_6]](s64)
    ; GFX8-NEXT: [[ANYEXT1:%[0-9]+]]:_(s64) = G_ANYEXT [[UV23]](i32)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_8:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_9:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[UADDE4]], [[ANYEXT1]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_10:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_11:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE]](s32), [[UADDO14]], [[AMDGPU_MAD_U64_U32_8]]
    ; GFX8-NEXT: [[UV24:%[0-9]+]]:_(i32), [[UV25:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_10]](s64)
    ; GFX8-NEXT: [[UMULH4:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[UV22]]
    ; GFX8-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[UADDO14]], [[UV24]]
    ; GFX8-NEXT: [[MUL4:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[UV22]]
    ; GFX8-NEXT: [[UADDO16:%[0-9]+]]:_(i32), [[UADDO17:%[0-9]+]]:_(i1) = G_UADDO [[UMULH4]], [[MUL3]]
    ; GFX8-NEXT: [[ZEXT5:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO17]](i1)
    ; GFX8-NEXT: [[UADDO18:%[0-9]+]]:_(i32), [[UADDO19:%[0-9]+]]:_(i1) = G_UADDO [[UADDO16]], [[MUL4]]
    ; GFX8-NEXT: [[ZEXT6:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO19]](i1)
    ; GFX8-NEXT: [[ADD4:%[0-9]+]]:_(i32) = G_ADD [[ZEXT5]], [[ZEXT6]]
    ; GFX8-NEXT: [[UMULH5:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[UV22]]
    ; GFX8-NEXT: [[UMULH6:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[UV24]]
    ; GFX8-NEXT: [[MUL5:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[UV24]]
    ; GFX8-NEXT: [[UADDO20:%[0-9]+]]:_(i32), [[UADDO21:%[0-9]+]]:_(i1) = G_UADDO [[UMULH5]], [[UMULH6]]
    ; GFX8-NEXT: [[ZEXT7:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO21]](i1)
    ; GFX8-NEXT: [[UADDO22:%[0-9]+]]:_(i32), [[UADDO23:%[0-9]+]]:_(i1) = G_UADDO [[UADDO20]], [[MUL5]]
    ; GFX8-NEXT: [[ZEXT8:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO23]](i1)
    ; GFX8-NEXT: [[ADD5:%[0-9]+]]:_(i32) = G_ADD [[ZEXT7]], [[ZEXT8]]
    ; GFX8-NEXT: [[UADDO24:%[0-9]+]]:_(i32), [[UADDO25:%[0-9]+]]:_(i1) = G_UADDO [[UADDO22]], [[ADD4]]
    ; GFX8-NEXT: [[ZEXT9:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO25]](i1)
    ; GFX8-NEXT: [[ADD6:%[0-9]+]]:_(i32) = G_ADD [[ADD5]], [[ZEXT9]]
    ; GFX8-NEXT: [[UMULH7:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[UV24]]
    ; GFX8-NEXT: [[ADD7:%[0-9]+]]:_(i32) = G_ADD [[UMULH7]], [[ADD6]]
    ; GFX8-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX8-NEXT: [[UADDO26:%[0-9]+]]:_(s32), [[UADDO27:%[0-9]+]]:_(s1) = G_UADDO [[UADDO14]], [[UADDO24]]
    ; GFX8-NEXT: [[UADDE6:%[0-9]+]]:_(s32), [[UADDE7:%[0-9]+]]:_(s1) = G_UADDE [[UADDE4]], [[ADD7]], [[UADDO27]]
    ; GFX8-NEXT: [[UV26:%[0-9]+]]:_(i32), [[UV27:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX8-NEXT: [[UV28:%[0-9]+]]:_(i32), [[UV29:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX8-NEXT: [[UMULH8:%[0-9]+]]:_(i32) = G_UMULH [[UV28]], [[UADDO26]]
    ; GFX8-NEXT: [[MUL6:%[0-9]+]]:_(i32) = G_MUL [[UV28]], [[UADDE6]]
    ; GFX8-NEXT: [[MUL7:%[0-9]+]]:_(i32) = G_MUL [[UV29]], [[UADDO26]]
    ; GFX8-NEXT: [[UADDO28:%[0-9]+]]:_(i32), [[UADDO29:%[0-9]+]]:_(i1) = G_UADDO [[UMULH8]], [[MUL6]]
    ; GFX8-NEXT: [[ZEXT10:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO29]](i1)
    ; GFX8-NEXT: [[UADDO30:%[0-9]+]]:_(i32), [[UADDO31:%[0-9]+]]:_(i1) = G_UADDO [[UADDO28]], [[MUL7]]
    ; GFX8-NEXT: [[ZEXT11:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO31]](i1)
    ; GFX8-NEXT: [[ADD8:%[0-9]+]]:_(i32) = G_ADD [[ZEXT10]], [[ZEXT11]]
    ; GFX8-NEXT: [[UMULH9:%[0-9]+]]:_(i32) = G_UMULH [[UV29]], [[UADDO26]]
    ; GFX8-NEXT: [[UMULH10:%[0-9]+]]:_(i32) = G_UMULH [[UV28]], [[UADDE6]]
    ; GFX8-NEXT: [[MUL8:%[0-9]+]]:_(i32) = G_MUL [[UV29]], [[UADDE6]]
    ; GFX8-NEXT: [[UADDO32:%[0-9]+]]:_(i32), [[UADDO33:%[0-9]+]]:_(i1) = G_UADDO [[UMULH9]], [[UMULH10]]
    ; GFX8-NEXT: [[ZEXT12:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO33]](i1)
    ; GFX8-NEXT: [[UADDO34:%[0-9]+]]:_(i32), [[UADDO35:%[0-9]+]]:_(i1) = G_UADDO [[UADDO32]], [[MUL8]]
    ; GFX8-NEXT: [[ZEXT13:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO35]](i1)
    ; GFX8-NEXT: [[ADD9:%[0-9]+]]:_(i32) = G_ADD [[ZEXT12]], [[ZEXT13]]
    ; GFX8-NEXT: [[UADDO36:%[0-9]+]]:_(i32), [[UADDO37:%[0-9]+]]:_(i1) = G_UADDO [[UADDO34]], [[ADD8]]
    ; GFX8-NEXT: [[ZEXT14:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO37]](i1)
    ; GFX8-NEXT: [[ADD10:%[0-9]+]]:_(i32) = G_ADD [[ADD9]], [[ZEXT14]]
    ; GFX8-NEXT: [[UMULH11:%[0-9]+]]:_(i32) = G_UMULH [[UV29]], [[UADDE6]]
    ; GFX8-NEXT: [[ADD11:%[0-9]+]]:_(i32) = G_ADD [[UMULH11]], [[ADD10]]
    ; GFX8-NEXT: [[UV30:%[0-9]+]]:_(i32), [[UV31:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_12:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_13:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV30]](i32), [[UADDO36]], [[C5]]
    ; GFX8-NEXT: [[UV32:%[0-9]+]]:_(i32), [[UV33:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_12]](s64)
    ; GFX8-NEXT: [[ANYEXT2:%[0-9]+]]:_(s64) = G_ANYEXT [[UV33]](i32)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_14:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_15:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV30]](i32), [[ADD11]], [[ANYEXT2]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_16:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_17:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV31]](i32), [[UADDO36]], [[AMDGPU_MAD_U64_U32_14]]
    ; GFX8-NEXT: [[UV34:%[0-9]+]]:_(i32), [[UV35:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_16]](s64)
    ; GFX8-NEXT: [[USUBO2:%[0-9]+]]:_(s32), [[USUBO3:%[0-9]+]]:_(s1) = G_USUBO [[UV26]], [[UV32]]
    ; GFX8-NEXT: [[USUBE2:%[0-9]+]]:_(s32), [[USUBE3:%[0-9]+]]:_(s1) = G_USUBE [[UV27]], [[UV34]], [[USUBO3]]
    ; GFX8-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[UV27]], [[UV34]]
    ; GFX8-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO2]](s32), [[USUBE2]](s32)
    ; GFX8-NEXT: [[UV36:%[0-9]+]]:_(i32), [[UV37:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX8-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE2]](s32), [[UV37]]
    ; GFX8-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[ICMP]](s1)
    ; GFX8-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO2]](s32), [[UV36]]
    ; GFX8-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[ICMP1]](s1)
    ; GFX8-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE2]](s32), [[UV37]]
    ; GFX8-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SEXT1]], [[SEXT]]
    ; GFX8-NEXT: [[USUBO4:%[0-9]+]]:_(s32), [[USUBO5:%[0-9]+]]:_(s1) = G_USUBO [[USUBO2]], [[UV36]]
    ; GFX8-NEXT: [[USUBE4:%[0-9]+]]:_(s32), [[USUBE5:%[0-9]+]]:_(s1) = G_USUBE [[SUB]], [[UV37]], [[USUBO3]]
    ; GFX8-NEXT: [[USUBE6:%[0-9]+]]:_(s32), [[USUBE7:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[C6]], [[USUBO5]]
    ; GFX8-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO4]](s32), [[USUBE6]](s32)
    ; GFX8-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE6]](s32), [[UV37]]
    ; GFX8-NEXT: [[SEXT2:%[0-9]+]]:_(s32) = G_SEXT [[ICMP3]](s1)
    ; GFX8-NEXT: [[ICMP4:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO4]](s32), [[UV36]]
    ; GFX8-NEXT: [[SEXT3:%[0-9]+]]:_(s32) = G_SEXT [[ICMP4]](s1)
    ; GFX8-NEXT: [[ICMP5:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE6]](s32), [[UV37]]
    ; GFX8-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP5]](s1), [[SEXT3]], [[SEXT2]]
    ; GFX8-NEXT: [[USUBO6:%[0-9]+]]:_(s32), [[USUBO7:%[0-9]+]]:_(s1) = G_USUBO [[USUBO4]], [[UV36]]
    ; GFX8-NEXT: [[USUBE8:%[0-9]+]]:_(s32), [[USUBE9:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[UV37]], [[USUBO5]]
    ; GFX8-NEXT: [[USUBE10:%[0-9]+]]:_(s32), [[USUBE11:%[0-9]+]]:_(s1) = G_USUBE [[USUBE8]], [[C6]], [[USUBO7]]
    ; GFX8-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO6]](s32), [[USUBE10]](s32)
    ; GFX8-NEXT: [[ICMP6:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT1]](s32), [[C6]]
    ; GFX8-NEXT: [[SELECT2:%[0-9]+]]:_(s64) = G_SELECT [[ICMP6]](s1), [[MV4]], [[MV3]]
    ; GFX8-NEXT: [[ICMP7:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT]](s32), [[C6]]
    ; GFX8-NEXT: [[SELECT3:%[0-9]+]]:_(s64) = G_SELECT [[ICMP7]](s1), [[SELECT2]], [[MV2]]
    ; GFX8-NEXT: [[XOR2:%[0-9]+]]:_(s64) = G_XOR [[SELECT3]], [[ASHR]]
    ; GFX8-NEXT: [[UV38:%[0-9]+]]:_(s32), [[UV39:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR2]](s64)
    ; GFX8-NEXT: [[UV40:%[0-9]+]]:_(s32), [[UV41:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX8-NEXT: [[USUBO8:%[0-9]+]]:_(s32), [[USUBO9:%[0-9]+]]:_(i1) = G_USUBO [[UV38]], [[UV40]]
    ; GFX8-NEXT: [[USUBE12:%[0-9]+]]:_(s32), [[USUBE13:%[0-9]+]]:_(i1) = G_USUBE [[UV39]], [[UV41]], [[USUBO9]]
    ; GFX8-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO8]](s32), [[USUBE12]](s32)
    ; GFX8-NEXT: [[ASHR2:%[0-9]+]]:_(s64) = G_ASHR [[UV1]], [[C]](s32)
    ; GFX8-NEXT: [[ASHR3:%[0-9]+]]:_(s64) = G_ASHR [[UV3]], [[C]](s32)
    ; GFX8-NEXT: [[UV42:%[0-9]+]]:_(s32), [[UV43:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV1]](s64)
    ; GFX8-NEXT: [[UV44:%[0-9]+]]:_(s32), [[UV45:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR2]](s64)
    ; GFX8-NEXT: [[UADDO38:%[0-9]+]]:_(s32), [[UADDO39:%[0-9]+]]:_(i1) = G_UADDO [[UV42]], [[UV44]]
    ; GFX8-NEXT: [[UADDE8:%[0-9]+]]:_(s32), [[UADDE9:%[0-9]+]]:_(i1) = G_UADDE [[UV43]], [[UV45]], [[UADDO39]]
    ; GFX8-NEXT: [[MV6:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO38]](s32), [[UADDE8]](s32)
    ; GFX8-NEXT: [[UV46:%[0-9]+]]:_(s32), [[UV47:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV3]](s64)
    ; GFX8-NEXT: [[UV48:%[0-9]+]]:_(s32), [[UV49:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR3]](s64)
    ; GFX8-NEXT: [[UADDO40:%[0-9]+]]:_(s32), [[UADDO41:%[0-9]+]]:_(i1) = G_UADDO [[UV46]], [[UV48]]
    ; GFX8-NEXT: [[UADDE10:%[0-9]+]]:_(s32), [[UADDE11:%[0-9]+]]:_(i1) = G_UADDE [[UV47]], [[UV49]], [[UADDO41]]
    ; GFX8-NEXT: [[MV7:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO40]](s32), [[UADDE10]](s32)
    ; GFX8-NEXT: [[XOR3:%[0-9]+]]:_(s64) = G_XOR [[MV6]], [[ASHR2]]
    ; GFX8-NEXT: [[XOR4:%[0-9]+]]:_(s64) = G_XOR [[MV7]], [[ASHR3]]
    ; GFX8-NEXT: [[UV50:%[0-9]+]]:_(i32), [[UV51:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX8-NEXT: [[UITOFP2:%[0-9]+]]:_(f32) = G_UITOFP [[UV50]](i32)
    ; GFX8-NEXT: [[UITOFP3:%[0-9]+]]:_(f32) = G_UITOFP [[UV51]](i32)
    ; GFX8-NEXT: [[FMUL4:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP3]], [[C1]]
    ; GFX8-NEXT: [[FADD2:%[0-9]+]]:_(f32) = G_FADD [[FMUL4]], [[UITOFP2]]
    ; GFX8-NEXT: [[AMDGPU_RCP_IFLAG1:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD2]](f32)
    ; GFX8-NEXT: [[FMUL5:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG1]], [[C2]]
    ; GFX8-NEXT: [[FMUL6:%[0-9]+]]:_(f32) = G_FMUL [[FMUL5]], [[C3]]
    ; GFX8-NEXT: [[INTRINSIC_TRUNC1:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL6]]
    ; GFX8-NEXT: [[FMUL7:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC1]], [[C4]]
    ; GFX8-NEXT: [[FADD3:%[0-9]+]]:_(f32) = G_FADD [[FMUL7]], [[FMUL5]]
    ; GFX8-NEXT: [[FPTOUI2:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD3]](f32)
    ; GFX8-NEXT: [[FPTOUI3:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC1]](f32)
    ; GFX8-NEXT: [[UV52:%[0-9]+]]:_(s32), [[UV53:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX8-NEXT: [[UV54:%[0-9]+]]:_(s32), [[UV55:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX8-NEXT: [[USUBO10:%[0-9]+]]:_(s32), [[USUBO11:%[0-9]+]]:_(i1) = G_USUBO [[UV52]], [[UV54]]
    ; GFX8-NEXT: [[USUBE14:%[0-9]+]]:_(s32), [[USUBE15:%[0-9]+]]:_(i1) = G_USUBE [[UV53]], [[UV55]], [[USUBO11]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_18:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_19:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO10]](s32), [[FPTOUI2]], [[C5]]
    ; GFX8-NEXT: [[UV56:%[0-9]+]]:_(i32), [[UV57:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_18]](s64)
    ; GFX8-NEXT: [[ANYEXT3:%[0-9]+]]:_(s64) = G_ANYEXT [[UV57]](i32)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_20:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_21:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO10]](s32), [[FPTOUI3]], [[ANYEXT3]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_22:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_23:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE14]](s32), [[FPTOUI2]], [[AMDGPU_MAD_U64_U32_20]]
    ; GFX8-NEXT: [[UV58:%[0-9]+]]:_(i32), [[UV59:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_22]](s64)
    ; GFX8-NEXT: [[UMULH12:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI2]], [[UV56]]
    ; GFX8-NEXT: [[MUL9:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI2]], [[UV58]]
    ; GFX8-NEXT: [[MUL10:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI3]], [[UV56]]
    ; GFX8-NEXT: [[UADDO42:%[0-9]+]]:_(i32), [[UADDO43:%[0-9]+]]:_(i1) = G_UADDO [[UMULH12]], [[MUL9]]
    ; GFX8-NEXT: [[ZEXT15:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO43]](i1)
    ; GFX8-NEXT: [[UADDO44:%[0-9]+]]:_(i32), [[UADDO45:%[0-9]+]]:_(i1) = G_UADDO [[UADDO42]], [[MUL10]]
    ; GFX8-NEXT: [[ZEXT16:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO45]](i1)
    ; GFX8-NEXT: [[ADD12:%[0-9]+]]:_(i32) = G_ADD [[ZEXT15]], [[ZEXT16]]
    ; GFX8-NEXT: [[UMULH13:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI3]], [[UV56]]
    ; GFX8-NEXT: [[UMULH14:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI2]], [[UV58]]
    ; GFX8-NEXT: [[MUL11:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI3]], [[UV58]]
    ; GFX8-NEXT: [[UADDO46:%[0-9]+]]:_(i32), [[UADDO47:%[0-9]+]]:_(i1) = G_UADDO [[UMULH13]], [[UMULH14]]
    ; GFX8-NEXT: [[ZEXT17:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO47]](i1)
    ; GFX8-NEXT: [[UADDO48:%[0-9]+]]:_(i32), [[UADDO49:%[0-9]+]]:_(i1) = G_UADDO [[UADDO46]], [[MUL11]]
    ; GFX8-NEXT: [[ZEXT18:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO49]](i1)
    ; GFX8-NEXT: [[ADD13:%[0-9]+]]:_(i32) = G_ADD [[ZEXT17]], [[ZEXT18]]
    ; GFX8-NEXT: [[UADDO50:%[0-9]+]]:_(i32), [[UADDO51:%[0-9]+]]:_(i1) = G_UADDO [[UADDO48]], [[ADD12]]
    ; GFX8-NEXT: [[ZEXT19:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO51]](i1)
    ; GFX8-NEXT: [[ADD14:%[0-9]+]]:_(i32) = G_ADD [[ADD13]], [[ZEXT19]]
    ; GFX8-NEXT: [[UMULH15:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI3]], [[UV58]]
    ; GFX8-NEXT: [[ADD15:%[0-9]+]]:_(i32) = G_ADD [[UMULH15]], [[ADD14]]
    ; GFX8-NEXT: [[UADDO52:%[0-9]+]]:_(s32), [[UADDO53:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI2]], [[UADDO50]]
    ; GFX8-NEXT: [[UADDE12:%[0-9]+]]:_(s32), [[UADDE13:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI3]], [[ADD15]], [[UADDO53]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_24:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_25:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO10]](s32), [[UADDO52]], [[C5]]
    ; GFX8-NEXT: [[UV60:%[0-9]+]]:_(i32), [[UV61:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_24]](s64)
    ; GFX8-NEXT: [[ANYEXT4:%[0-9]+]]:_(s64) = G_ANYEXT [[UV61]](i32)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_26:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_27:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO10]](s32), [[UADDE12]], [[ANYEXT4]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_28:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_29:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE14]](s32), [[UADDO52]], [[AMDGPU_MAD_U64_U32_26]]
    ; GFX8-NEXT: [[UV62:%[0-9]+]]:_(i32), [[UV63:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_28]](s64)
    ; GFX8-NEXT: [[UMULH16:%[0-9]+]]:_(i32) = G_UMULH [[UADDO52]], [[UV60]]
    ; GFX8-NEXT: [[MUL12:%[0-9]+]]:_(i32) = G_MUL [[UADDO52]], [[UV62]]
    ; GFX8-NEXT: [[MUL13:%[0-9]+]]:_(i32) = G_MUL [[UADDE12]], [[UV60]]
    ; GFX8-NEXT: [[UADDO54:%[0-9]+]]:_(i32), [[UADDO55:%[0-9]+]]:_(i1) = G_UADDO [[UMULH16]], [[MUL12]]
    ; GFX8-NEXT: [[ZEXT20:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO55]](i1)
    ; GFX8-NEXT: [[UADDO56:%[0-9]+]]:_(i32), [[UADDO57:%[0-9]+]]:_(i1) = G_UADDO [[UADDO54]], [[MUL13]]
    ; GFX8-NEXT: [[ZEXT21:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO57]](i1)
    ; GFX8-NEXT: [[ADD16:%[0-9]+]]:_(i32) = G_ADD [[ZEXT20]], [[ZEXT21]]
    ; GFX8-NEXT: [[UMULH17:%[0-9]+]]:_(i32) = G_UMULH [[UADDE12]], [[UV60]]
    ; GFX8-NEXT: [[UMULH18:%[0-9]+]]:_(i32) = G_UMULH [[UADDO52]], [[UV62]]
    ; GFX8-NEXT: [[MUL14:%[0-9]+]]:_(i32) = G_MUL [[UADDE12]], [[UV62]]
    ; GFX8-NEXT: [[UADDO58:%[0-9]+]]:_(i32), [[UADDO59:%[0-9]+]]:_(i1) = G_UADDO [[UMULH17]], [[UMULH18]]
    ; GFX8-NEXT: [[ZEXT22:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO59]](i1)
    ; GFX8-NEXT: [[UADDO60:%[0-9]+]]:_(i32), [[UADDO61:%[0-9]+]]:_(i1) = G_UADDO [[UADDO58]], [[MUL14]]
    ; GFX8-NEXT: [[ZEXT23:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO61]](i1)
    ; GFX8-NEXT: [[ADD17:%[0-9]+]]:_(i32) = G_ADD [[ZEXT22]], [[ZEXT23]]
    ; GFX8-NEXT: [[UADDO62:%[0-9]+]]:_(i32), [[UADDO63:%[0-9]+]]:_(i1) = G_UADDO [[UADDO60]], [[ADD16]]
    ; GFX8-NEXT: [[ZEXT24:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO63]](i1)
    ; GFX8-NEXT: [[ADD18:%[0-9]+]]:_(i32) = G_ADD [[ADD17]], [[ZEXT24]]
    ; GFX8-NEXT: [[UMULH19:%[0-9]+]]:_(i32) = G_UMULH [[UADDE12]], [[UV62]]
    ; GFX8-NEXT: [[ADD19:%[0-9]+]]:_(i32) = G_ADD [[UMULH19]], [[ADD18]]
    ; GFX8-NEXT: [[UADDO64:%[0-9]+]]:_(s32), [[UADDO65:%[0-9]+]]:_(s1) = G_UADDO [[UADDO52]], [[UADDO62]]
    ; GFX8-NEXT: [[UADDE14:%[0-9]+]]:_(s32), [[UADDE15:%[0-9]+]]:_(s1) = G_UADDE [[UADDE12]], [[ADD19]], [[UADDO65]]
    ; GFX8-NEXT: [[UV64:%[0-9]+]]:_(i32), [[UV65:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR3]](s64)
    ; GFX8-NEXT: [[UV66:%[0-9]+]]:_(i32), [[UV67:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR3]](s64)
    ; GFX8-NEXT: [[UMULH20:%[0-9]+]]:_(i32) = G_UMULH [[UV66]], [[UADDO64]]
    ; GFX8-NEXT: [[MUL15:%[0-9]+]]:_(i32) = G_MUL [[UV66]], [[UADDE14]]
    ; GFX8-NEXT: [[MUL16:%[0-9]+]]:_(i32) = G_MUL [[UV67]], [[UADDO64]]
    ; GFX8-NEXT: [[UADDO66:%[0-9]+]]:_(i32), [[UADDO67:%[0-9]+]]:_(i1) = G_UADDO [[UMULH20]], [[MUL15]]
    ; GFX8-NEXT: [[ZEXT25:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO67]](i1)
    ; GFX8-NEXT: [[UADDO68:%[0-9]+]]:_(i32), [[UADDO69:%[0-9]+]]:_(i1) = G_UADDO [[UADDO66]], [[MUL16]]
    ; GFX8-NEXT: [[ZEXT26:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO69]](i1)
    ; GFX8-NEXT: [[ADD20:%[0-9]+]]:_(i32) = G_ADD [[ZEXT25]], [[ZEXT26]]
    ; GFX8-NEXT: [[UMULH21:%[0-9]+]]:_(i32) = G_UMULH [[UV67]], [[UADDO64]]
    ; GFX8-NEXT: [[UMULH22:%[0-9]+]]:_(i32) = G_UMULH [[UV66]], [[UADDE14]]
    ; GFX8-NEXT: [[MUL17:%[0-9]+]]:_(i32) = G_MUL [[UV67]], [[UADDE14]]
    ; GFX8-NEXT: [[UADDO70:%[0-9]+]]:_(i32), [[UADDO71:%[0-9]+]]:_(i1) = G_UADDO [[UMULH21]], [[UMULH22]]
    ; GFX8-NEXT: [[ZEXT27:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO71]](i1)
    ; GFX8-NEXT: [[UADDO72:%[0-9]+]]:_(i32), [[UADDO73:%[0-9]+]]:_(i1) = G_UADDO [[UADDO70]], [[MUL17]]
    ; GFX8-NEXT: [[ZEXT28:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO73]](i1)
    ; GFX8-NEXT: [[ADD21:%[0-9]+]]:_(i32) = G_ADD [[ZEXT27]], [[ZEXT28]]
    ; GFX8-NEXT: [[UADDO74:%[0-9]+]]:_(i32), [[UADDO75:%[0-9]+]]:_(i1) = G_UADDO [[UADDO72]], [[ADD20]]
    ; GFX8-NEXT: [[ZEXT29:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO75]](i1)
    ; GFX8-NEXT: [[ADD22:%[0-9]+]]:_(i32) = G_ADD [[ADD21]], [[ZEXT29]]
    ; GFX8-NEXT: [[UMULH23:%[0-9]+]]:_(i32) = G_UMULH [[UV67]], [[UADDE14]]
    ; GFX8-NEXT: [[ADD23:%[0-9]+]]:_(i32) = G_ADD [[UMULH23]], [[ADD22]]
    ; GFX8-NEXT: [[UV68:%[0-9]+]]:_(i32), [[UV69:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_30:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_31:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV68]](i32), [[UADDO74]], [[C5]]
    ; GFX8-NEXT: [[UV70:%[0-9]+]]:_(i32), [[UV71:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_30]](s64)
    ; GFX8-NEXT: [[ANYEXT5:%[0-9]+]]:_(s64) = G_ANYEXT [[UV71]](i32)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_32:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_33:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV68]](i32), [[ADD23]], [[ANYEXT5]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_34:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_35:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV69]](i32), [[UADDO74]], [[AMDGPU_MAD_U64_U32_32]]
    ; GFX8-NEXT: [[UV72:%[0-9]+]]:_(i32), [[UV73:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_34]](s64)
    ; GFX8-NEXT: [[USUBO12:%[0-9]+]]:_(s32), [[USUBO13:%[0-9]+]]:_(s1) = G_USUBO [[UV64]], [[UV70]]
    ; GFX8-NEXT: [[USUBE16:%[0-9]+]]:_(s32), [[USUBE17:%[0-9]+]]:_(s1) = G_USUBE [[UV65]], [[UV72]], [[USUBO13]]
    ; GFX8-NEXT: [[SUB1:%[0-9]+]]:_(s32) = G_SUB [[UV65]], [[UV72]]
    ; GFX8-NEXT: [[MV8:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO12]](s32), [[USUBE16]](s32)
    ; GFX8-NEXT: [[UV74:%[0-9]+]]:_(i32), [[UV75:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX8-NEXT: [[ICMP8:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE16]](s32), [[UV75]]
    ; GFX8-NEXT: [[SEXT4:%[0-9]+]]:_(s32) = G_SEXT [[ICMP8]](s1)
    ; GFX8-NEXT: [[ICMP9:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO12]](s32), [[UV74]]
    ; GFX8-NEXT: [[SEXT5:%[0-9]+]]:_(s32) = G_SEXT [[ICMP9]](s1)
    ; GFX8-NEXT: [[ICMP10:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE16]](s32), [[UV75]]
    ; GFX8-NEXT: [[SELECT4:%[0-9]+]]:_(s32) = G_SELECT [[ICMP10]](s1), [[SEXT5]], [[SEXT4]]
    ; GFX8-NEXT: [[USUBO14:%[0-9]+]]:_(s32), [[USUBO15:%[0-9]+]]:_(s1) = G_USUBO [[USUBO12]], [[UV74]]
    ; GFX8-NEXT: [[USUBE18:%[0-9]+]]:_(s32), [[USUBE19:%[0-9]+]]:_(s1) = G_USUBE [[SUB1]], [[UV75]], [[USUBO13]]
    ; GFX8-NEXT: [[USUBE20:%[0-9]+]]:_(s32), [[USUBE21:%[0-9]+]]:_(s1) = G_USUBE [[USUBE18]], [[C6]], [[USUBO15]]
    ; GFX8-NEXT: [[MV9:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO14]](s32), [[USUBE20]](s32)
    ; GFX8-NEXT: [[ICMP11:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE20]](s32), [[UV75]]
    ; GFX8-NEXT: [[SEXT6:%[0-9]+]]:_(s32) = G_SEXT [[ICMP11]](s1)
    ; GFX8-NEXT: [[ICMP12:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO14]](s32), [[UV74]]
    ; GFX8-NEXT: [[SEXT7:%[0-9]+]]:_(s32) = G_SEXT [[ICMP12]](s1)
    ; GFX8-NEXT: [[ICMP13:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE20]](s32), [[UV75]]
    ; GFX8-NEXT: [[SELECT5:%[0-9]+]]:_(s32) = G_SELECT [[ICMP13]](s1), [[SEXT7]], [[SEXT6]]
    ; GFX8-NEXT: [[USUBO16:%[0-9]+]]:_(s32), [[USUBO17:%[0-9]+]]:_(s1) = G_USUBO [[USUBO14]], [[UV74]]
    ; GFX8-NEXT: [[USUBE22:%[0-9]+]]:_(s32), [[USUBE23:%[0-9]+]]:_(s1) = G_USUBE [[USUBE18]], [[UV75]], [[USUBO15]]
    ; GFX8-NEXT: [[USUBE24:%[0-9]+]]:_(s32), [[USUBE25:%[0-9]+]]:_(s1) = G_USUBE [[USUBE22]], [[C6]], [[USUBO17]]
    ; GFX8-NEXT: [[MV10:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO16]](s32), [[USUBE24]](s32)
    ; GFX8-NEXT: [[ICMP14:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT5]](s32), [[C6]]
    ; GFX8-NEXT: [[SELECT6:%[0-9]+]]:_(s64) = G_SELECT [[ICMP14]](s1), [[MV10]], [[MV9]]
    ; GFX8-NEXT: [[ICMP15:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT4]](s32), [[C6]]
    ; GFX8-NEXT: [[SELECT7:%[0-9]+]]:_(s64) = G_SELECT [[ICMP15]](s1), [[SELECT6]], [[MV8]]
    ; GFX8-NEXT: [[XOR5:%[0-9]+]]:_(s64) = G_XOR [[SELECT7]], [[ASHR2]]
    ; GFX8-NEXT: [[UV76:%[0-9]+]]:_(s32), [[UV77:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR5]](s64)
    ; GFX8-NEXT: [[UV78:%[0-9]+]]:_(s32), [[UV79:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR2]](s64)
    ; GFX8-NEXT: [[USUBO18:%[0-9]+]]:_(s32), [[USUBO19:%[0-9]+]]:_(i1) = G_USUBO [[UV76]], [[UV78]]
    ; GFX8-NEXT: [[USUBE26:%[0-9]+]]:_(s32), [[USUBE27:%[0-9]+]]:_(i1) = G_USUBE [[UV77]], [[UV79]], [[USUBO19]]
    ; GFX8-NEXT: [[MV11:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO18]](s32), [[USUBE26]](s32)
    ; GFX8-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s64>) = G_BUILD_VECTOR [[MV5]](s64), [[MV11]](s64)
    ; GFX8-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3 = COPY [[BUILD_VECTOR]](<2 x s64>)
    ;
    ; GFX9-LABEL: name: test_srem_v2s64
    ; GFX9: liveins: $vgpr0_vgpr1_vgpr2_vgpr3, $vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:_(<2 x s64>) = COPY $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s64>) = COPY $vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX9-NEXT: [[UV:%[0-9]+]]:_(s64), [[UV1:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[COPY]](<2 x s64>)
    ; GFX9-NEXT: [[UV2:%[0-9]+]]:_(s64), [[UV3:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[COPY1]](<2 x s64>)
    ; GFX9-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; GFX9-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[UV]], [[C]](s32)
    ; GFX9-NEXT: [[ASHR1:%[0-9]+]]:_(s64) = G_ASHR [[UV2]], [[C]](s32)
    ; GFX9-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV]](s64)
    ; GFX9-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX9-NEXT: [[UADDO:%[0-9]+]]:_(s32), [[UADDO1:%[0-9]+]]:_(i1) = G_UADDO [[UV4]], [[UV6]]
    ; GFX9-NEXT: [[UADDE:%[0-9]+]]:_(s32), [[UADDE1:%[0-9]+]]:_(i1) = G_UADDE [[UV5]], [[UV7]], [[UADDO1]]
    ; GFX9-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO]](s32), [[UADDE]](s32)
    ; GFX9-NEXT: [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV2]](s64)
    ; GFX9-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR1]](s64)
    ; GFX9-NEXT: [[UADDO2:%[0-9]+]]:_(s32), [[UADDO3:%[0-9]+]]:_(i1) = G_UADDO [[UV8]], [[UV10]]
    ; GFX9-NEXT: [[UADDE2:%[0-9]+]]:_(s32), [[UADDE3:%[0-9]+]]:_(i1) = G_UADDE [[UV9]], [[UV11]], [[UADDO3]]
    ; GFX9-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO2]](s32), [[UADDE2]](s32)
    ; GFX9-NEXT: [[XOR:%[0-9]+]]:_(s64) = G_XOR [[MV]], [[ASHR]]
    ; GFX9-NEXT: [[XOR1:%[0-9]+]]:_(s64) = G_XOR [[MV1]], [[ASHR1]]
    ; GFX9-NEXT: [[UV12:%[0-9]+]]:_(i32), [[UV13:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX9-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[UV12]](i32)
    ; GFX9-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[UV13]](i32)
    ; GFX9-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F800000
    ; GFX9-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP1]], [[C1]]
    ; GFX9-NEXT: [[FADD:%[0-9]+]]:_(f32) = G_FADD [[FMUL]], [[UITOFP]]
    ; GFX9-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD]](f32)
    ; GFX9-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x5F7FFFFC
    ; GFX9-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX9-NEXT: [[C3:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x2F800000
    ; GFX9-NEXT: [[FMUL2:%[0-9]+]]:_(f32) = G_FMUL [[FMUL1]], [[C3]]
    ; GFX9-NEXT: [[INTRINSIC_TRUNC:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL2]]
    ; GFX9-NEXT: [[C4:%[0-9]+]]:_(s32) = G_FCONSTANT float f0xCF800000
    ; GFX9-NEXT: [[FMUL3:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC]], [[C4]]
    ; GFX9-NEXT: [[FADD1:%[0-9]+]]:_(f32) = G_FADD [[FMUL3]], [[FMUL1]]
    ; GFX9-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD1]](f32)
    ; GFX9-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC]](f32)
    ; GFX9-NEXT: [[C5:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; GFX9-NEXT: [[UV14:%[0-9]+]]:_(s32), [[UV15:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX9-NEXT: [[UV16:%[0-9]+]]:_(s32), [[UV17:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX9-NEXT: [[USUBO:%[0-9]+]]:_(s32), [[USUBO1:%[0-9]+]]:_(i1) = G_USUBO [[UV14]], [[UV16]]
    ; GFX9-NEXT: [[USUBE:%[0-9]+]]:_(s32), [[USUBE1:%[0-9]+]]:_(i1) = G_USUBE [[UV15]], [[UV17]], [[USUBO1]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_1:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[FPTOUI]], [[C5]]
    ; GFX9-NEXT: [[UV18:%[0-9]+]]:_(i32), [[UV19:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_]](s64)
    ; GFX9-NEXT: [[ANYEXT:%[0-9]+]]:_(s64) = G_ANYEXT [[UV19]](i32)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_2:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_3:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[FPTOUI1]], [[ANYEXT]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_4:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_5:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE]](s32), [[FPTOUI]], [[AMDGPU_MAD_U64_U32_2]]
    ; GFX9-NEXT: [[UV20:%[0-9]+]]:_(i32), [[UV21:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_4]](s64)
    ; GFX9-NEXT: [[UMULH:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[UV18]]
    ; GFX9-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI]], [[UV20]]
    ; GFX9-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[UV18]]
    ; GFX9-NEXT: [[UADDO4:%[0-9]+]]:_(i32), [[UADDO5:%[0-9]+]]:_(i1) = G_UADDO [[UMULH]], [[MUL]]
    ; GFX9-NEXT: [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO5]](i1)
    ; GFX9-NEXT: [[UADDO6:%[0-9]+]]:_(i32), [[UADDO7:%[0-9]+]]:_(i1) = G_UADDO [[UADDO4]], [[MUL1]]
    ; GFX9-NEXT: [[ZEXT1:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO7]](i1)
    ; GFX9-NEXT: [[ADD:%[0-9]+]]:_(i32) = G_ADD [[ZEXT]], [[ZEXT1]]
    ; GFX9-NEXT: [[UMULH1:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[UV18]]
    ; GFX9-NEXT: [[UMULH2:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[UV20]]
    ; GFX9-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[UV20]]
    ; GFX9-NEXT: [[UADDO8:%[0-9]+]]:_(i32), [[UADDO9:%[0-9]+]]:_(i1) = G_UADDO [[UMULH1]], [[UMULH2]]
    ; GFX9-NEXT: [[ZEXT2:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO9]](i1)
    ; GFX9-NEXT: [[UADDO10:%[0-9]+]]:_(i32), [[UADDO11:%[0-9]+]]:_(i1) = G_UADDO [[UADDO8]], [[MUL2]]
    ; GFX9-NEXT: [[ZEXT3:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO11]](i1)
    ; GFX9-NEXT: [[ADD1:%[0-9]+]]:_(i32) = G_ADD [[ZEXT2]], [[ZEXT3]]
    ; GFX9-NEXT: [[UADDO12:%[0-9]+]]:_(i32), [[UADDO13:%[0-9]+]]:_(i1) = G_UADDO [[UADDO10]], [[ADD]]
    ; GFX9-NEXT: [[ZEXT4:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO13]](i1)
    ; GFX9-NEXT: [[ADD2:%[0-9]+]]:_(i32) = G_ADD [[ADD1]], [[ZEXT4]]
    ; GFX9-NEXT: [[UMULH3:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[UV20]]
    ; GFX9-NEXT: [[ADD3:%[0-9]+]]:_(i32) = G_ADD [[UMULH3]], [[ADD2]]
    ; GFX9-NEXT: [[UADDO14:%[0-9]+]]:_(s32), [[UADDO15:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI]], [[UADDO12]]
    ; GFX9-NEXT: [[UADDE4:%[0-9]+]]:_(s32), [[UADDE5:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI1]], [[ADD3]], [[UADDO15]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_6:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_7:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[UADDO14]], [[C5]]
    ; GFX9-NEXT: [[UV22:%[0-9]+]]:_(i32), [[UV23:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_6]](s64)
    ; GFX9-NEXT: [[ANYEXT1:%[0-9]+]]:_(s64) = G_ANYEXT [[UV23]](i32)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_8:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_9:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[UADDE4]], [[ANYEXT1]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_10:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_11:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE]](s32), [[UADDO14]], [[AMDGPU_MAD_U64_U32_8]]
    ; GFX9-NEXT: [[UV24:%[0-9]+]]:_(i32), [[UV25:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_10]](s64)
    ; GFX9-NEXT: [[UMULH4:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[UV22]]
    ; GFX9-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[UADDO14]], [[UV24]]
    ; GFX9-NEXT: [[MUL4:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[UV22]]
    ; GFX9-NEXT: [[UADDO16:%[0-9]+]]:_(i32), [[UADDO17:%[0-9]+]]:_(i1) = G_UADDO [[UMULH4]], [[MUL3]]
    ; GFX9-NEXT: [[ZEXT5:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO17]](i1)
    ; GFX9-NEXT: [[UADDO18:%[0-9]+]]:_(i32), [[UADDO19:%[0-9]+]]:_(i1) = G_UADDO [[UADDO16]], [[MUL4]]
    ; GFX9-NEXT: [[ZEXT6:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO19]](i1)
    ; GFX9-NEXT: [[ADD4:%[0-9]+]]:_(i32) = G_ADD [[ZEXT5]], [[ZEXT6]]
    ; GFX9-NEXT: [[UMULH5:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[UV22]]
    ; GFX9-NEXT: [[UMULH6:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[UV24]]
    ; GFX9-NEXT: [[MUL5:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[UV24]]
    ; GFX9-NEXT: [[UADDO20:%[0-9]+]]:_(i32), [[UADDO21:%[0-9]+]]:_(i1) = G_UADDO [[UMULH5]], [[UMULH6]]
    ; GFX9-NEXT: [[ZEXT7:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO21]](i1)
    ; GFX9-NEXT: [[UADDO22:%[0-9]+]]:_(i32), [[UADDO23:%[0-9]+]]:_(i1) = G_UADDO [[UADDO20]], [[MUL5]]
    ; GFX9-NEXT: [[ZEXT8:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO23]](i1)
    ; GFX9-NEXT: [[ADD5:%[0-9]+]]:_(i32) = G_ADD [[ZEXT7]], [[ZEXT8]]
    ; GFX9-NEXT: [[UADDO24:%[0-9]+]]:_(i32), [[UADDO25:%[0-9]+]]:_(i1) = G_UADDO [[UADDO22]], [[ADD4]]
    ; GFX9-NEXT: [[ZEXT9:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO25]](i1)
    ; GFX9-NEXT: [[ADD6:%[0-9]+]]:_(i32) = G_ADD [[ADD5]], [[ZEXT9]]
    ; GFX9-NEXT: [[UMULH7:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[UV24]]
    ; GFX9-NEXT: [[ADD7:%[0-9]+]]:_(i32) = G_ADD [[UMULH7]], [[ADD6]]
    ; GFX9-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX9-NEXT: [[UADDO26:%[0-9]+]]:_(s32), [[UADDO27:%[0-9]+]]:_(s1) = G_UADDO [[UADDO14]], [[UADDO24]]
    ; GFX9-NEXT: [[UADDE6:%[0-9]+]]:_(s32), [[UADDE7:%[0-9]+]]:_(s1) = G_UADDE [[UADDE4]], [[ADD7]], [[UADDO27]]
    ; GFX9-NEXT: [[UV26:%[0-9]+]]:_(i32), [[UV27:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX9-NEXT: [[UV28:%[0-9]+]]:_(i32), [[UV29:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX9-NEXT: [[UMULH8:%[0-9]+]]:_(i32) = G_UMULH [[UV28]], [[UADDO26]]
    ; GFX9-NEXT: [[MUL6:%[0-9]+]]:_(i32) = G_MUL [[UV28]], [[UADDE6]]
    ; GFX9-NEXT: [[MUL7:%[0-9]+]]:_(i32) = G_MUL [[UV29]], [[UADDO26]]
    ; GFX9-NEXT: [[UADDO28:%[0-9]+]]:_(i32), [[UADDO29:%[0-9]+]]:_(i1) = G_UADDO [[UMULH8]], [[MUL6]]
    ; GFX9-NEXT: [[ZEXT10:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO29]](i1)
    ; GFX9-NEXT: [[UADDO30:%[0-9]+]]:_(i32), [[UADDO31:%[0-9]+]]:_(i1) = G_UADDO [[UADDO28]], [[MUL7]]
    ; GFX9-NEXT: [[ZEXT11:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO31]](i1)
    ; GFX9-NEXT: [[ADD8:%[0-9]+]]:_(i32) = G_ADD [[ZEXT10]], [[ZEXT11]]
    ; GFX9-NEXT: [[UMULH9:%[0-9]+]]:_(i32) = G_UMULH [[UV29]], [[UADDO26]]
    ; GFX9-NEXT: [[UMULH10:%[0-9]+]]:_(i32) = G_UMULH [[UV28]], [[UADDE6]]
    ; GFX9-NEXT: [[MUL8:%[0-9]+]]:_(i32) = G_MUL [[UV29]], [[UADDE6]]
    ; GFX9-NEXT: [[UADDO32:%[0-9]+]]:_(i32), [[UADDO33:%[0-9]+]]:_(i1) = G_UADDO [[UMULH9]], [[UMULH10]]
    ; GFX9-NEXT: [[ZEXT12:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO33]](i1)
    ; GFX9-NEXT: [[UADDO34:%[0-9]+]]:_(i32), [[UADDO35:%[0-9]+]]:_(i1) = G_UADDO [[UADDO32]], [[MUL8]]
    ; GFX9-NEXT: [[ZEXT13:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO35]](i1)
    ; GFX9-NEXT: [[ADD9:%[0-9]+]]:_(i32) = G_ADD [[ZEXT12]], [[ZEXT13]]
    ; GFX9-NEXT: [[UADDO36:%[0-9]+]]:_(i32), [[UADDO37:%[0-9]+]]:_(i1) = G_UADDO [[UADDO34]], [[ADD8]]
    ; GFX9-NEXT: [[ZEXT14:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO37]](i1)
    ; GFX9-NEXT: [[ADD10:%[0-9]+]]:_(i32) = G_ADD [[ADD9]], [[ZEXT14]]
    ; GFX9-NEXT: [[UMULH11:%[0-9]+]]:_(i32) = G_UMULH [[UV29]], [[UADDE6]]
    ; GFX9-NEXT: [[ADD11:%[0-9]+]]:_(i32) = G_ADD [[UMULH11]], [[ADD10]]
    ; GFX9-NEXT: [[UV30:%[0-9]+]]:_(i32), [[UV31:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_12:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_13:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV30]](i32), [[UADDO36]], [[C5]]
    ; GFX9-NEXT: [[UV32:%[0-9]+]]:_(i32), [[UV33:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_12]](s64)
    ; GFX9-NEXT: [[ANYEXT2:%[0-9]+]]:_(s64) = G_ANYEXT [[UV33]](i32)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_14:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_15:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV30]](i32), [[ADD11]], [[ANYEXT2]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_16:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_17:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV31]](i32), [[UADDO36]], [[AMDGPU_MAD_U64_U32_14]]
    ; GFX9-NEXT: [[UV34:%[0-9]+]]:_(i32), [[UV35:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_16]](s64)
    ; GFX9-NEXT: [[USUBO2:%[0-9]+]]:_(s32), [[USUBO3:%[0-9]+]]:_(s1) = G_USUBO [[UV26]], [[UV32]]
    ; GFX9-NEXT: [[USUBE2:%[0-9]+]]:_(s32), [[USUBE3:%[0-9]+]]:_(s1) = G_USUBE [[UV27]], [[UV34]], [[USUBO3]]
    ; GFX9-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[UV27]], [[UV34]]
    ; GFX9-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO2]](s32), [[USUBE2]](s32)
    ; GFX9-NEXT: [[UV36:%[0-9]+]]:_(i32), [[UV37:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX9-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE2]](s32), [[UV37]]
    ; GFX9-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[ICMP]](s1)
    ; GFX9-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO2]](s32), [[UV36]]
    ; GFX9-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[ICMP1]](s1)
    ; GFX9-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE2]](s32), [[UV37]]
    ; GFX9-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SEXT1]], [[SEXT]]
    ; GFX9-NEXT: [[USUBO4:%[0-9]+]]:_(s32), [[USUBO5:%[0-9]+]]:_(s1) = G_USUBO [[USUBO2]], [[UV36]]
    ; GFX9-NEXT: [[USUBE4:%[0-9]+]]:_(s32), [[USUBE5:%[0-9]+]]:_(s1) = G_USUBE [[SUB]], [[UV37]], [[USUBO3]]
    ; GFX9-NEXT: [[USUBE6:%[0-9]+]]:_(s32), [[USUBE7:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[C6]], [[USUBO5]]
    ; GFX9-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO4]](s32), [[USUBE6]](s32)
    ; GFX9-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE6]](s32), [[UV37]]
    ; GFX9-NEXT: [[SEXT2:%[0-9]+]]:_(s32) = G_SEXT [[ICMP3]](s1)
    ; GFX9-NEXT: [[ICMP4:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO4]](s32), [[UV36]]
    ; GFX9-NEXT: [[SEXT3:%[0-9]+]]:_(s32) = G_SEXT [[ICMP4]](s1)
    ; GFX9-NEXT: [[ICMP5:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE6]](s32), [[UV37]]
    ; GFX9-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP5]](s1), [[SEXT3]], [[SEXT2]]
    ; GFX9-NEXT: [[USUBO6:%[0-9]+]]:_(s32), [[USUBO7:%[0-9]+]]:_(s1) = G_USUBO [[USUBO4]], [[UV36]]
    ; GFX9-NEXT: [[USUBE8:%[0-9]+]]:_(s32), [[USUBE9:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[UV37]], [[USUBO5]]
    ; GFX9-NEXT: [[USUBE10:%[0-9]+]]:_(s32), [[USUBE11:%[0-9]+]]:_(s1) = G_USUBE [[USUBE8]], [[C6]], [[USUBO7]]
    ; GFX9-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO6]](s32), [[USUBE10]](s32)
    ; GFX9-NEXT: [[ICMP6:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT1]](s32), [[C6]]
    ; GFX9-NEXT: [[SELECT2:%[0-9]+]]:_(s64) = G_SELECT [[ICMP6]](s1), [[MV4]], [[MV3]]
    ; GFX9-NEXT: [[ICMP7:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT]](s32), [[C6]]
    ; GFX9-NEXT: [[SELECT3:%[0-9]+]]:_(s64) = G_SELECT [[ICMP7]](s1), [[SELECT2]], [[MV2]]
    ; GFX9-NEXT: [[XOR2:%[0-9]+]]:_(s64) = G_XOR [[SELECT3]], [[ASHR]]
    ; GFX9-NEXT: [[UV38:%[0-9]+]]:_(s32), [[UV39:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR2]](s64)
    ; GFX9-NEXT: [[UV40:%[0-9]+]]:_(s32), [[UV41:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX9-NEXT: [[USUBO8:%[0-9]+]]:_(s32), [[USUBO9:%[0-9]+]]:_(i1) = G_USUBO [[UV38]], [[UV40]]
    ; GFX9-NEXT: [[USUBE12:%[0-9]+]]:_(s32), [[USUBE13:%[0-9]+]]:_(i1) = G_USUBE [[UV39]], [[UV41]], [[USUBO9]]
    ; GFX9-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO8]](s32), [[USUBE12]](s32)
    ; GFX9-NEXT: [[ASHR2:%[0-9]+]]:_(s64) = G_ASHR [[UV1]], [[C]](s32)
    ; GFX9-NEXT: [[ASHR3:%[0-9]+]]:_(s64) = G_ASHR [[UV3]], [[C]](s32)
    ; GFX9-NEXT: [[UV42:%[0-9]+]]:_(s32), [[UV43:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV1]](s64)
    ; GFX9-NEXT: [[UV44:%[0-9]+]]:_(s32), [[UV45:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR2]](s64)
    ; GFX9-NEXT: [[UADDO38:%[0-9]+]]:_(s32), [[UADDO39:%[0-9]+]]:_(i1) = G_UADDO [[UV42]], [[UV44]]
    ; GFX9-NEXT: [[UADDE8:%[0-9]+]]:_(s32), [[UADDE9:%[0-9]+]]:_(i1) = G_UADDE [[UV43]], [[UV45]], [[UADDO39]]
    ; GFX9-NEXT: [[MV6:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO38]](s32), [[UADDE8]](s32)
    ; GFX9-NEXT: [[UV46:%[0-9]+]]:_(s32), [[UV47:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV3]](s64)
    ; GFX9-NEXT: [[UV48:%[0-9]+]]:_(s32), [[UV49:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR3]](s64)
    ; GFX9-NEXT: [[UADDO40:%[0-9]+]]:_(s32), [[UADDO41:%[0-9]+]]:_(i1) = G_UADDO [[UV46]], [[UV48]]
    ; GFX9-NEXT: [[UADDE10:%[0-9]+]]:_(s32), [[UADDE11:%[0-9]+]]:_(i1) = G_UADDE [[UV47]], [[UV49]], [[UADDO41]]
    ; GFX9-NEXT: [[MV7:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO40]](s32), [[UADDE10]](s32)
    ; GFX9-NEXT: [[XOR3:%[0-9]+]]:_(s64) = G_XOR [[MV6]], [[ASHR2]]
    ; GFX9-NEXT: [[XOR4:%[0-9]+]]:_(s64) = G_XOR [[MV7]], [[ASHR3]]
    ; GFX9-NEXT: [[UV50:%[0-9]+]]:_(i32), [[UV51:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX9-NEXT: [[UITOFP2:%[0-9]+]]:_(f32) = G_UITOFP [[UV50]](i32)
    ; GFX9-NEXT: [[UITOFP3:%[0-9]+]]:_(f32) = G_UITOFP [[UV51]](i32)
    ; GFX9-NEXT: [[FMUL4:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP3]], [[C1]]
    ; GFX9-NEXT: [[FADD2:%[0-9]+]]:_(f32) = G_FADD [[FMUL4]], [[UITOFP2]]
    ; GFX9-NEXT: [[AMDGPU_RCP_IFLAG1:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD2]](f32)
    ; GFX9-NEXT: [[FMUL5:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG1]], [[C2]]
    ; GFX9-NEXT: [[FMUL6:%[0-9]+]]:_(f32) = G_FMUL [[FMUL5]], [[C3]]
    ; GFX9-NEXT: [[INTRINSIC_TRUNC1:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL6]]
    ; GFX9-NEXT: [[FMUL7:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC1]], [[C4]]
    ; GFX9-NEXT: [[FADD3:%[0-9]+]]:_(f32) = G_FADD [[FMUL7]], [[FMUL5]]
    ; GFX9-NEXT: [[FPTOUI2:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD3]](f32)
    ; GFX9-NEXT: [[FPTOUI3:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC1]](f32)
    ; GFX9-NEXT: [[UV52:%[0-9]+]]:_(s32), [[UV53:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX9-NEXT: [[UV54:%[0-9]+]]:_(s32), [[UV55:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX9-NEXT: [[USUBO10:%[0-9]+]]:_(s32), [[USUBO11:%[0-9]+]]:_(i1) = G_USUBO [[UV52]], [[UV54]]
    ; GFX9-NEXT: [[USUBE14:%[0-9]+]]:_(s32), [[USUBE15:%[0-9]+]]:_(i1) = G_USUBE [[UV53]], [[UV55]], [[USUBO11]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_18:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_19:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO10]](s32), [[FPTOUI2]], [[C5]]
    ; GFX9-NEXT: [[UV56:%[0-9]+]]:_(i32), [[UV57:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_18]](s64)
    ; GFX9-NEXT: [[ANYEXT3:%[0-9]+]]:_(s64) = G_ANYEXT [[UV57]](i32)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_20:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_21:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO10]](s32), [[FPTOUI3]], [[ANYEXT3]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_22:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_23:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE14]](s32), [[FPTOUI2]], [[AMDGPU_MAD_U64_U32_20]]
    ; GFX9-NEXT: [[UV58:%[0-9]+]]:_(i32), [[UV59:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_22]](s64)
    ; GFX9-NEXT: [[UMULH12:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI2]], [[UV56]]
    ; GFX9-NEXT: [[MUL9:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI2]], [[UV58]]
    ; GFX9-NEXT: [[MUL10:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI3]], [[UV56]]
    ; GFX9-NEXT: [[UADDO42:%[0-9]+]]:_(i32), [[UADDO43:%[0-9]+]]:_(i1) = G_UADDO [[UMULH12]], [[MUL9]]
    ; GFX9-NEXT: [[ZEXT15:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO43]](i1)
    ; GFX9-NEXT: [[UADDO44:%[0-9]+]]:_(i32), [[UADDO45:%[0-9]+]]:_(i1) = G_UADDO [[UADDO42]], [[MUL10]]
    ; GFX9-NEXT: [[ZEXT16:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO45]](i1)
    ; GFX9-NEXT: [[ADD12:%[0-9]+]]:_(i32) = G_ADD [[ZEXT15]], [[ZEXT16]]
    ; GFX9-NEXT: [[UMULH13:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI3]], [[UV56]]
    ; GFX9-NEXT: [[UMULH14:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI2]], [[UV58]]
    ; GFX9-NEXT: [[MUL11:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI3]], [[UV58]]
    ; GFX9-NEXT: [[UADDO46:%[0-9]+]]:_(i32), [[UADDO47:%[0-9]+]]:_(i1) = G_UADDO [[UMULH13]], [[UMULH14]]
    ; GFX9-NEXT: [[ZEXT17:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO47]](i1)
    ; GFX9-NEXT: [[UADDO48:%[0-9]+]]:_(i32), [[UADDO49:%[0-9]+]]:_(i1) = G_UADDO [[UADDO46]], [[MUL11]]
    ; GFX9-NEXT: [[ZEXT18:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO49]](i1)
    ; GFX9-NEXT: [[ADD13:%[0-9]+]]:_(i32) = G_ADD [[ZEXT17]], [[ZEXT18]]
    ; GFX9-NEXT: [[UADDO50:%[0-9]+]]:_(i32), [[UADDO51:%[0-9]+]]:_(i1) = G_UADDO [[UADDO48]], [[ADD12]]
    ; GFX9-NEXT: [[ZEXT19:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO51]](i1)
    ; GFX9-NEXT: [[ADD14:%[0-9]+]]:_(i32) = G_ADD [[ADD13]], [[ZEXT19]]
    ; GFX9-NEXT: [[UMULH15:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI3]], [[UV58]]
    ; GFX9-NEXT: [[ADD15:%[0-9]+]]:_(i32) = G_ADD [[UMULH15]], [[ADD14]]
    ; GFX9-NEXT: [[UADDO52:%[0-9]+]]:_(s32), [[UADDO53:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI2]], [[UADDO50]]
    ; GFX9-NEXT: [[UADDE12:%[0-9]+]]:_(s32), [[UADDE13:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI3]], [[ADD15]], [[UADDO53]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_24:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_25:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO10]](s32), [[UADDO52]], [[C5]]
    ; GFX9-NEXT: [[UV60:%[0-9]+]]:_(i32), [[UV61:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_24]](s64)
    ; GFX9-NEXT: [[ANYEXT4:%[0-9]+]]:_(s64) = G_ANYEXT [[UV61]](i32)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_26:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_27:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO10]](s32), [[UADDE12]], [[ANYEXT4]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_28:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_29:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE14]](s32), [[UADDO52]], [[AMDGPU_MAD_U64_U32_26]]
    ; GFX9-NEXT: [[UV62:%[0-9]+]]:_(i32), [[UV63:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_28]](s64)
    ; GFX9-NEXT: [[UMULH16:%[0-9]+]]:_(i32) = G_UMULH [[UADDO52]], [[UV60]]
    ; GFX9-NEXT: [[MUL12:%[0-9]+]]:_(i32) = G_MUL [[UADDO52]], [[UV62]]
    ; GFX9-NEXT: [[MUL13:%[0-9]+]]:_(i32) = G_MUL [[UADDE12]], [[UV60]]
    ; GFX9-NEXT: [[UADDO54:%[0-9]+]]:_(i32), [[UADDO55:%[0-9]+]]:_(i1) = G_UADDO [[UMULH16]], [[MUL12]]
    ; GFX9-NEXT: [[ZEXT20:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO55]](i1)
    ; GFX9-NEXT: [[UADDO56:%[0-9]+]]:_(i32), [[UADDO57:%[0-9]+]]:_(i1) = G_UADDO [[UADDO54]], [[MUL13]]
    ; GFX9-NEXT: [[ZEXT21:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO57]](i1)
    ; GFX9-NEXT: [[ADD16:%[0-9]+]]:_(i32) = G_ADD [[ZEXT20]], [[ZEXT21]]
    ; GFX9-NEXT: [[UMULH17:%[0-9]+]]:_(i32) = G_UMULH [[UADDE12]], [[UV60]]
    ; GFX9-NEXT: [[UMULH18:%[0-9]+]]:_(i32) = G_UMULH [[UADDO52]], [[UV62]]
    ; GFX9-NEXT: [[MUL14:%[0-9]+]]:_(i32) = G_MUL [[UADDE12]], [[UV62]]
    ; GFX9-NEXT: [[UADDO58:%[0-9]+]]:_(i32), [[UADDO59:%[0-9]+]]:_(i1) = G_UADDO [[UMULH17]], [[UMULH18]]
    ; GFX9-NEXT: [[ZEXT22:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO59]](i1)
    ; GFX9-NEXT: [[UADDO60:%[0-9]+]]:_(i32), [[UADDO61:%[0-9]+]]:_(i1) = G_UADDO [[UADDO58]], [[MUL14]]
    ; GFX9-NEXT: [[ZEXT23:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO61]](i1)
    ; GFX9-NEXT: [[ADD17:%[0-9]+]]:_(i32) = G_ADD [[ZEXT22]], [[ZEXT23]]
    ; GFX9-NEXT: [[UADDO62:%[0-9]+]]:_(i32), [[UADDO63:%[0-9]+]]:_(i1) = G_UADDO [[UADDO60]], [[ADD16]]
    ; GFX9-NEXT: [[ZEXT24:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO63]](i1)
    ; GFX9-NEXT: [[ADD18:%[0-9]+]]:_(i32) = G_ADD [[ADD17]], [[ZEXT24]]
    ; GFX9-NEXT: [[UMULH19:%[0-9]+]]:_(i32) = G_UMULH [[UADDE12]], [[UV62]]
    ; GFX9-NEXT: [[ADD19:%[0-9]+]]:_(i32) = G_ADD [[UMULH19]], [[ADD18]]
    ; GFX9-NEXT: [[UADDO64:%[0-9]+]]:_(s32), [[UADDO65:%[0-9]+]]:_(s1) = G_UADDO [[UADDO52]], [[UADDO62]]
    ; GFX9-NEXT: [[UADDE14:%[0-9]+]]:_(s32), [[UADDE15:%[0-9]+]]:_(s1) = G_UADDE [[UADDE12]], [[ADD19]], [[UADDO65]]
    ; GFX9-NEXT: [[UV64:%[0-9]+]]:_(i32), [[UV65:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR3]](s64)
    ; GFX9-NEXT: [[UV66:%[0-9]+]]:_(i32), [[UV67:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR3]](s64)
    ; GFX9-NEXT: [[UMULH20:%[0-9]+]]:_(i32) = G_UMULH [[UV66]], [[UADDO64]]
    ; GFX9-NEXT: [[MUL15:%[0-9]+]]:_(i32) = G_MUL [[UV66]], [[UADDE14]]
    ; GFX9-NEXT: [[MUL16:%[0-9]+]]:_(i32) = G_MUL [[UV67]], [[UADDO64]]
    ; GFX9-NEXT: [[UADDO66:%[0-9]+]]:_(i32), [[UADDO67:%[0-9]+]]:_(i1) = G_UADDO [[UMULH20]], [[MUL15]]
    ; GFX9-NEXT: [[ZEXT25:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO67]](i1)
    ; GFX9-NEXT: [[UADDO68:%[0-9]+]]:_(i32), [[UADDO69:%[0-9]+]]:_(i1) = G_UADDO [[UADDO66]], [[MUL16]]
    ; GFX9-NEXT: [[ZEXT26:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO69]](i1)
    ; GFX9-NEXT: [[ADD20:%[0-9]+]]:_(i32) = G_ADD [[ZEXT25]], [[ZEXT26]]
    ; GFX9-NEXT: [[UMULH21:%[0-9]+]]:_(i32) = G_UMULH [[UV67]], [[UADDO64]]
    ; GFX9-NEXT: [[UMULH22:%[0-9]+]]:_(i32) = G_UMULH [[UV66]], [[UADDE14]]
    ; GFX9-NEXT: [[MUL17:%[0-9]+]]:_(i32) = G_MUL [[UV67]], [[UADDE14]]
    ; GFX9-NEXT: [[UADDO70:%[0-9]+]]:_(i32), [[UADDO71:%[0-9]+]]:_(i1) = G_UADDO [[UMULH21]], [[UMULH22]]
    ; GFX9-NEXT: [[ZEXT27:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO71]](i1)
    ; GFX9-NEXT: [[UADDO72:%[0-9]+]]:_(i32), [[UADDO73:%[0-9]+]]:_(i1) = G_UADDO [[UADDO70]], [[MUL17]]
    ; GFX9-NEXT: [[ZEXT28:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO73]](i1)
    ; GFX9-NEXT: [[ADD21:%[0-9]+]]:_(i32) = G_ADD [[ZEXT27]], [[ZEXT28]]
    ; GFX9-NEXT: [[UADDO74:%[0-9]+]]:_(i32), [[UADDO75:%[0-9]+]]:_(i1) = G_UADDO [[UADDO72]], [[ADD20]]
    ; GFX9-NEXT: [[ZEXT29:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO75]](i1)
    ; GFX9-NEXT: [[ADD22:%[0-9]+]]:_(i32) = G_ADD [[ADD21]], [[ZEXT29]]
    ; GFX9-NEXT: [[UMULH23:%[0-9]+]]:_(i32) = G_UMULH [[UV67]], [[UADDE14]]
    ; GFX9-NEXT: [[ADD23:%[0-9]+]]:_(i32) = G_ADD [[UMULH23]], [[ADD22]]
    ; GFX9-NEXT: [[UV68:%[0-9]+]]:_(i32), [[UV69:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_30:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_31:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV68]](i32), [[UADDO74]], [[C5]]
    ; GFX9-NEXT: [[UV70:%[0-9]+]]:_(i32), [[UV71:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_30]](s64)
    ; GFX9-NEXT: [[ANYEXT5:%[0-9]+]]:_(s64) = G_ANYEXT [[UV71]](i32)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_32:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_33:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV68]](i32), [[ADD23]], [[ANYEXT5]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_34:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_35:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV69]](i32), [[UADDO74]], [[AMDGPU_MAD_U64_U32_32]]
    ; GFX9-NEXT: [[UV72:%[0-9]+]]:_(i32), [[UV73:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_34]](s64)
    ; GFX9-NEXT: [[USUBO12:%[0-9]+]]:_(s32), [[USUBO13:%[0-9]+]]:_(s1) = G_USUBO [[UV64]], [[UV70]]
    ; GFX9-NEXT: [[USUBE16:%[0-9]+]]:_(s32), [[USUBE17:%[0-9]+]]:_(s1) = G_USUBE [[UV65]], [[UV72]], [[USUBO13]]
    ; GFX9-NEXT: [[SUB1:%[0-9]+]]:_(s32) = G_SUB [[UV65]], [[UV72]]
    ; GFX9-NEXT: [[MV8:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO12]](s32), [[USUBE16]](s32)
    ; GFX9-NEXT: [[UV74:%[0-9]+]]:_(i32), [[UV75:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX9-NEXT: [[ICMP8:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE16]](s32), [[UV75]]
    ; GFX9-NEXT: [[SEXT4:%[0-9]+]]:_(s32) = G_SEXT [[ICMP8]](s1)
    ; GFX9-NEXT: [[ICMP9:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO12]](s32), [[UV74]]
    ; GFX9-NEXT: [[SEXT5:%[0-9]+]]:_(s32) = G_SEXT [[ICMP9]](s1)
    ; GFX9-NEXT: [[ICMP10:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE16]](s32), [[UV75]]
    ; GFX9-NEXT: [[SELECT4:%[0-9]+]]:_(s32) = G_SELECT [[ICMP10]](s1), [[SEXT5]], [[SEXT4]]
    ; GFX9-NEXT: [[USUBO14:%[0-9]+]]:_(s32), [[USUBO15:%[0-9]+]]:_(s1) = G_USUBO [[USUBO12]], [[UV74]]
    ; GFX9-NEXT: [[USUBE18:%[0-9]+]]:_(s32), [[USUBE19:%[0-9]+]]:_(s1) = G_USUBE [[SUB1]], [[UV75]], [[USUBO13]]
    ; GFX9-NEXT: [[USUBE20:%[0-9]+]]:_(s32), [[USUBE21:%[0-9]+]]:_(s1) = G_USUBE [[USUBE18]], [[C6]], [[USUBO15]]
    ; GFX9-NEXT: [[MV9:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO14]](s32), [[USUBE20]](s32)
    ; GFX9-NEXT: [[ICMP11:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE20]](s32), [[UV75]]
    ; GFX9-NEXT: [[SEXT6:%[0-9]+]]:_(s32) = G_SEXT [[ICMP11]](s1)
    ; GFX9-NEXT: [[ICMP12:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO14]](s32), [[UV74]]
    ; GFX9-NEXT: [[SEXT7:%[0-9]+]]:_(s32) = G_SEXT [[ICMP12]](s1)
    ; GFX9-NEXT: [[ICMP13:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE20]](s32), [[UV75]]
    ; GFX9-NEXT: [[SELECT5:%[0-9]+]]:_(s32) = G_SELECT [[ICMP13]](s1), [[SEXT7]], [[SEXT6]]
    ; GFX9-NEXT: [[USUBO16:%[0-9]+]]:_(s32), [[USUBO17:%[0-9]+]]:_(s1) = G_USUBO [[USUBO14]], [[UV74]]
    ; GFX9-NEXT: [[USUBE22:%[0-9]+]]:_(s32), [[USUBE23:%[0-9]+]]:_(s1) = G_USUBE [[USUBE18]], [[UV75]], [[USUBO15]]
    ; GFX9-NEXT: [[USUBE24:%[0-9]+]]:_(s32), [[USUBE25:%[0-9]+]]:_(s1) = G_USUBE [[USUBE22]], [[C6]], [[USUBO17]]
    ; GFX9-NEXT: [[MV10:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO16]](s32), [[USUBE24]](s32)
    ; GFX9-NEXT: [[ICMP14:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT5]](s32), [[C6]]
    ; GFX9-NEXT: [[SELECT6:%[0-9]+]]:_(s64) = G_SELECT [[ICMP14]](s1), [[MV10]], [[MV9]]
    ; GFX9-NEXT: [[ICMP15:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT4]](s32), [[C6]]
    ; GFX9-NEXT: [[SELECT7:%[0-9]+]]:_(s64) = G_SELECT [[ICMP15]](s1), [[SELECT6]], [[MV8]]
    ; GFX9-NEXT: [[XOR5:%[0-9]+]]:_(s64) = G_XOR [[SELECT7]], [[ASHR2]]
    ; GFX9-NEXT: [[UV76:%[0-9]+]]:_(s32), [[UV77:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR5]](s64)
    ; GFX9-NEXT: [[UV78:%[0-9]+]]:_(s32), [[UV79:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR2]](s64)
    ; GFX9-NEXT: [[USUBO18:%[0-9]+]]:_(s32), [[USUBO19:%[0-9]+]]:_(i1) = G_USUBO [[UV76]], [[UV78]]
    ; GFX9-NEXT: [[USUBE26:%[0-9]+]]:_(s32), [[USUBE27:%[0-9]+]]:_(i1) = G_USUBE [[UV77]], [[UV79]], [[USUBO19]]
    ; GFX9-NEXT: [[MV11:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO18]](s32), [[USUBE26]](s32)
    ; GFX9-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s64>) = G_BUILD_VECTOR [[MV5]](s64), [[MV11]](s64)
    ; GFX9-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3 = COPY [[BUILD_VECTOR]](<2 x s64>)
    ;
    ; GFX10-LABEL: name: test_srem_v2s64
    ; GFX10: liveins: $vgpr0_vgpr1_vgpr2_vgpr3, $vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:_(<2 x s64>) = COPY $vgpr0_vgpr1_vgpr2_vgpr3
    ; GFX10-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s64>) = COPY $vgpr4_vgpr5_vgpr6_vgpr7
    ; GFX10-NEXT: [[UV:%[0-9]+]]:_(s64), [[UV1:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[COPY]](<2 x s64>)
    ; GFX10-NEXT: [[UV2:%[0-9]+]]:_(s64), [[UV3:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[COPY1]](<2 x s64>)
    ; GFX10-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; GFX10-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[UV]], [[C]](s32)
    ; GFX10-NEXT: [[ASHR1:%[0-9]+]]:_(s64) = G_ASHR [[UV2]], [[C]](s32)
    ; GFX10-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV]](s64)
    ; GFX10-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX10-NEXT: [[UADDO:%[0-9]+]]:_(s32), [[UADDO1:%[0-9]+]]:_(i1) = G_UADDO [[UV4]], [[UV6]]
    ; GFX10-NEXT: [[UADDE:%[0-9]+]]:_(s32), [[UADDE1:%[0-9]+]]:_(i1) = G_UADDE [[UV5]], [[UV7]], [[UADDO1]]
    ; GFX10-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO]](s32), [[UADDE]](s32)
    ; GFX10-NEXT: [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV2]](s64)
    ; GFX10-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR1]](s64)
    ; GFX10-NEXT: [[UADDO2:%[0-9]+]]:_(s32), [[UADDO3:%[0-9]+]]:_(i1) = G_UADDO [[UV8]], [[UV10]]
    ; GFX10-NEXT: [[UADDE2:%[0-9]+]]:_(s32), [[UADDE3:%[0-9]+]]:_(i1) = G_UADDE [[UV9]], [[UV11]], [[UADDO3]]
    ; GFX10-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO2]](s32), [[UADDE2]](s32)
    ; GFX10-NEXT: [[XOR:%[0-9]+]]:_(s64) = G_XOR [[MV]], [[ASHR]]
    ; GFX10-NEXT: [[XOR1:%[0-9]+]]:_(s64) = G_XOR [[MV1]], [[ASHR1]]
    ; GFX10-NEXT: [[UV12:%[0-9]+]]:_(i32), [[UV13:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX10-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[UV12]](i32)
    ; GFX10-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[UV13]](i32)
    ; GFX10-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F800000
    ; GFX10-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP1]], [[C1]]
    ; GFX10-NEXT: [[FADD:%[0-9]+]]:_(f32) = G_FADD [[FMUL]], [[UITOFP]]
    ; GFX10-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD]](f32)
    ; GFX10-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x5F7FFFFC
    ; GFX10-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX10-NEXT: [[C3:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x2F800000
    ; GFX10-NEXT: [[FMUL2:%[0-9]+]]:_(f32) = G_FMUL [[FMUL1]], [[C3]]
    ; GFX10-NEXT: [[INTRINSIC_TRUNC:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL2]]
    ; GFX10-NEXT: [[C4:%[0-9]+]]:_(s32) = G_FCONSTANT float f0xCF800000
    ; GFX10-NEXT: [[FMUL3:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC]], [[C4]]
    ; GFX10-NEXT: [[FADD1:%[0-9]+]]:_(f32) = G_FADD [[FMUL3]], [[FMUL1]]
    ; GFX10-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD1]](f32)
    ; GFX10-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC]](f32)
    ; GFX10-NEXT: [[C5:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; GFX10-NEXT: [[UV14:%[0-9]+]]:_(s32), [[UV15:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX10-NEXT: [[UV16:%[0-9]+]]:_(s32), [[UV17:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX10-NEXT: [[USUBO:%[0-9]+]]:_(s32), [[USUBO1:%[0-9]+]]:_(i1) = G_USUBO [[UV14]], [[UV16]]
    ; GFX10-NEXT: [[USUBE:%[0-9]+]]:_(s32), [[USUBE1:%[0-9]+]]:_(i1) = G_USUBE [[UV15]], [[UV17]], [[USUBO1]]
    ; GFX10-NEXT: [[AMDGPU_MAD_U64_U32_:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_1:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[FPTOUI]], [[C5]]
    ; GFX10-NEXT: [[UV18:%[0-9]+]]:_(i32), [[UV19:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_]](s64)
    ; GFX10-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[FPTOUI1]]
    ; GFX10-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[UV19]], [[MUL]]
    ; GFX10-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[USUBE]], [[FPTOUI]]
    ; GFX10-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[ADD]], [[MUL1]]
    ; GFX10-NEXT: [[UMULH:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[UV18]]
    ; GFX10-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI]], [[ADD1]]
    ; GFX10-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[UV18]]
    ; GFX10-NEXT: [[UADDO4:%[0-9]+]]:_(i32), [[UADDO5:%[0-9]+]]:_(i1) = G_UADDO [[UMULH]], [[MUL2]]
    ; GFX10-NEXT: [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO5]](i1)
    ; GFX10-NEXT: [[UADDO6:%[0-9]+]]:_(i32), [[UADDO7:%[0-9]+]]:_(i1) = G_UADDO [[UADDO4]], [[MUL3]]
    ; GFX10-NEXT: [[ZEXT1:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO7]](i1)
    ; GFX10-NEXT: [[ADD2:%[0-9]+]]:_(i32) = G_ADD [[ZEXT]], [[ZEXT1]]
    ; GFX10-NEXT: [[UMULH1:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[UV18]]
    ; GFX10-NEXT: [[UMULH2:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[ADD1]]
    ; GFX10-NEXT: [[MUL4:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[ADD1]]
    ; GFX10-NEXT: [[UADDO8:%[0-9]+]]:_(i32), [[UADDO9:%[0-9]+]]:_(i1) = G_UADDO [[UMULH1]], [[UMULH2]]
    ; GFX10-NEXT: [[ZEXT2:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO9]](i1)
    ; GFX10-NEXT: [[UADDO10:%[0-9]+]]:_(i32), [[UADDO11:%[0-9]+]]:_(i1) = G_UADDO [[UADDO8]], [[MUL4]]
    ; GFX10-NEXT: [[ZEXT3:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO11]](i1)
    ; GFX10-NEXT: [[ADD3:%[0-9]+]]:_(i32) = G_ADD [[ZEXT2]], [[ZEXT3]]
    ; GFX10-NEXT: [[UADDO12:%[0-9]+]]:_(i32), [[UADDO13:%[0-9]+]]:_(i1) = G_UADDO [[UADDO10]], [[ADD2]]
    ; GFX10-NEXT: [[ZEXT4:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO13]](i1)
    ; GFX10-NEXT: [[ADD4:%[0-9]+]]:_(i32) = G_ADD [[ADD3]], [[ZEXT4]]
    ; GFX10-NEXT: [[UMULH3:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[ADD1]]
    ; GFX10-NEXT: [[ADD5:%[0-9]+]]:_(i32) = G_ADD [[UMULH3]], [[ADD4]]
    ; GFX10-NEXT: [[UADDO14:%[0-9]+]]:_(s32), [[UADDO15:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI]], [[UADDO12]]
    ; GFX10-NEXT: [[UADDE4:%[0-9]+]]:_(s32), [[UADDE5:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI1]], [[ADD5]], [[UADDO15]]
    ; GFX10-NEXT: [[AMDGPU_MAD_U64_U32_2:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_3:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[UADDO14]], [[C5]]
    ; GFX10-NEXT: [[UV20:%[0-9]+]]:_(i32), [[UV21:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_2]](s64)
    ; GFX10-NEXT: [[MUL5:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[UADDE4]]
    ; GFX10-NEXT: [[ADD6:%[0-9]+]]:_(s32) = G_ADD [[UV21]], [[MUL5]]
    ; GFX10-NEXT: [[MUL6:%[0-9]+]]:_(i32) = G_MUL [[USUBE]], [[UADDO14]]
    ; GFX10-NEXT: [[ADD7:%[0-9]+]]:_(s32) = G_ADD [[ADD6]], [[MUL6]]
    ; GFX10-NEXT: [[UMULH4:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[UV20]]
    ; GFX10-NEXT: [[MUL7:%[0-9]+]]:_(i32) = G_MUL [[UADDO14]], [[ADD7]]
    ; GFX10-NEXT: [[MUL8:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[UV20]]
    ; GFX10-NEXT: [[UADDO16:%[0-9]+]]:_(i32), [[UADDO17:%[0-9]+]]:_(i1) = G_UADDO [[UMULH4]], [[MUL7]]
    ; GFX10-NEXT: [[ZEXT5:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO17]](i1)
    ; GFX10-NEXT: [[UADDO18:%[0-9]+]]:_(i32), [[UADDO19:%[0-9]+]]:_(i1) = G_UADDO [[UADDO16]], [[MUL8]]
    ; GFX10-NEXT: [[ZEXT6:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO19]](i1)
    ; GFX10-NEXT: [[ADD8:%[0-9]+]]:_(i32) = G_ADD [[ZEXT5]], [[ZEXT6]]
    ; GFX10-NEXT: [[UMULH5:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[UV20]]
    ; GFX10-NEXT: [[UMULH6:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[ADD7]]
    ; GFX10-NEXT: [[MUL9:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[ADD7]]
    ; GFX10-NEXT: [[UADDO20:%[0-9]+]]:_(i32), [[UADDO21:%[0-9]+]]:_(i1) = G_UADDO [[UMULH5]], [[UMULH6]]
    ; GFX10-NEXT: [[ZEXT7:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO21]](i1)
    ; GFX10-NEXT: [[UADDO22:%[0-9]+]]:_(i32), [[UADDO23:%[0-9]+]]:_(i1) = G_UADDO [[UADDO20]], [[MUL9]]
    ; GFX10-NEXT: [[ZEXT8:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO23]](i1)
    ; GFX10-NEXT: [[ADD9:%[0-9]+]]:_(i32) = G_ADD [[ZEXT7]], [[ZEXT8]]
    ; GFX10-NEXT: [[UADDO24:%[0-9]+]]:_(i32), [[UADDO25:%[0-9]+]]:_(i1) = G_UADDO [[UADDO22]], [[ADD8]]
    ; GFX10-NEXT: [[ZEXT9:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO25]](i1)
    ; GFX10-NEXT: [[ADD10:%[0-9]+]]:_(i32) = G_ADD [[ADD9]], [[ZEXT9]]
    ; GFX10-NEXT: [[UMULH7:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[ADD7]]
    ; GFX10-NEXT: [[ADD11:%[0-9]+]]:_(i32) = G_ADD [[UMULH7]], [[ADD10]]
    ; GFX10-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX10-NEXT: [[UADDO26:%[0-9]+]]:_(s32), [[UADDO27:%[0-9]+]]:_(s1) = G_UADDO [[UADDO14]], [[UADDO24]]
    ; GFX10-NEXT: [[UADDE6:%[0-9]+]]:_(s32), [[UADDE7:%[0-9]+]]:_(s1) = G_UADDE [[UADDE4]], [[ADD11]], [[UADDO27]]
    ; GFX10-NEXT: [[UV22:%[0-9]+]]:_(i32), [[UV23:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX10-NEXT: [[UV24:%[0-9]+]]:_(i32), [[UV25:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX10-NEXT: [[UMULH8:%[0-9]+]]:_(i32) = G_UMULH [[UV24]], [[UADDO26]]
    ; GFX10-NEXT: [[MUL10:%[0-9]+]]:_(i32) = G_MUL [[UV24]], [[UADDE6]]
    ; GFX10-NEXT: [[MUL11:%[0-9]+]]:_(i32) = G_MUL [[UV25]], [[UADDO26]]
    ; GFX10-NEXT: [[UADDO28:%[0-9]+]]:_(i32), [[UADDO29:%[0-9]+]]:_(i1) = G_UADDO [[UMULH8]], [[MUL10]]
    ; GFX10-NEXT: [[ZEXT10:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO29]](i1)
    ; GFX10-NEXT: [[UADDO30:%[0-9]+]]:_(i32), [[UADDO31:%[0-9]+]]:_(i1) = G_UADDO [[UADDO28]], [[MUL11]]
    ; GFX10-NEXT: [[ZEXT11:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO31]](i1)
    ; GFX10-NEXT: [[ADD12:%[0-9]+]]:_(i32) = G_ADD [[ZEXT10]], [[ZEXT11]]
    ; GFX10-NEXT: [[UMULH9:%[0-9]+]]:_(i32) = G_UMULH [[UV25]], [[UADDO26]]
    ; GFX10-NEXT: [[UMULH10:%[0-9]+]]:_(i32) = G_UMULH [[UV24]], [[UADDE6]]
    ; GFX10-NEXT: [[MUL12:%[0-9]+]]:_(i32) = G_MUL [[UV25]], [[UADDE6]]
    ; GFX10-NEXT: [[UADDO32:%[0-9]+]]:_(i32), [[UADDO33:%[0-9]+]]:_(i1) = G_UADDO [[UMULH9]], [[UMULH10]]
    ; GFX10-NEXT: [[ZEXT12:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO33]](i1)
    ; GFX10-NEXT: [[UADDO34:%[0-9]+]]:_(i32), [[UADDO35:%[0-9]+]]:_(i1) = G_UADDO [[UADDO32]], [[MUL12]]
    ; GFX10-NEXT: [[ZEXT13:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO35]](i1)
    ; GFX10-NEXT: [[ADD13:%[0-9]+]]:_(i32) = G_ADD [[ZEXT12]], [[ZEXT13]]
    ; GFX10-NEXT: [[UADDO36:%[0-9]+]]:_(i32), [[UADDO37:%[0-9]+]]:_(i1) = G_UADDO [[UADDO34]], [[ADD12]]
    ; GFX10-NEXT: [[ZEXT14:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO37]](i1)
    ; GFX10-NEXT: [[ADD14:%[0-9]+]]:_(i32) = G_ADD [[ADD13]], [[ZEXT14]]
    ; GFX10-NEXT: [[UMULH11:%[0-9]+]]:_(i32) = G_UMULH [[UV25]], [[UADDE6]]
    ; GFX10-NEXT: [[ADD15:%[0-9]+]]:_(i32) = G_ADD [[UMULH11]], [[ADD14]]
    ; GFX10-NEXT: [[UV26:%[0-9]+]]:_(i32), [[UV27:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX10-NEXT: [[AMDGPU_MAD_U64_U32_4:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_5:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV26]](i32), [[UADDO36]], [[C5]]
    ; GFX10-NEXT: [[UV28:%[0-9]+]]:_(i32), [[UV29:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_4]](s64)
    ; GFX10-NEXT: [[MUL13:%[0-9]+]]:_(i32) = G_MUL [[UV26]], [[ADD15]]
    ; GFX10-NEXT: [[ADD16:%[0-9]+]]:_(s32) = G_ADD [[UV29]], [[MUL13]]
    ; GFX10-NEXT: [[MUL14:%[0-9]+]]:_(i32) = G_MUL [[UV27]], [[UADDO36]]
    ; GFX10-NEXT: [[ADD17:%[0-9]+]]:_(s32) = G_ADD [[ADD16]], [[MUL14]]
    ; GFX10-NEXT: [[USUBO2:%[0-9]+]]:_(s32), [[USUBO3:%[0-9]+]]:_(s1) = G_USUBO [[UV22]], [[UV28]]
    ; GFX10-NEXT: [[USUBE2:%[0-9]+]]:_(s32), [[USUBE3:%[0-9]+]]:_(s1) = G_USUBE [[UV23]], [[ADD17]], [[USUBO3]]
    ; GFX10-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[UV23]], [[ADD17]]
    ; GFX10-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO2]](s32), [[USUBE2]](s32)
    ; GFX10-NEXT: [[UV30:%[0-9]+]]:_(i32), [[UV31:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX10-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE2]](s32), [[UV31]]
    ; GFX10-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[ICMP]](s1)
    ; GFX10-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO2]](s32), [[UV30]]
    ; GFX10-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[ICMP1]](s1)
    ; GFX10-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE2]](s32), [[UV31]]
    ; GFX10-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SEXT1]], [[SEXT]]
    ; GFX10-NEXT: [[USUBO4:%[0-9]+]]:_(s32), [[USUBO5:%[0-9]+]]:_(s1) = G_USUBO [[USUBO2]], [[UV30]]
    ; GFX10-NEXT: [[USUBE4:%[0-9]+]]:_(s32), [[USUBE5:%[0-9]+]]:_(s1) = G_USUBE [[SUB]], [[UV31]], [[USUBO3]]
    ; GFX10-NEXT: [[USUBE6:%[0-9]+]]:_(s32), [[USUBE7:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[C6]], [[USUBO5]]
    ; GFX10-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO4]](s32), [[USUBE6]](s32)
    ; GFX10-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE6]](s32), [[UV31]]
    ; GFX10-NEXT: [[SEXT2:%[0-9]+]]:_(s32) = G_SEXT [[ICMP3]](s1)
    ; GFX10-NEXT: [[ICMP4:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO4]](s32), [[UV30]]
    ; GFX10-NEXT: [[SEXT3:%[0-9]+]]:_(s32) = G_SEXT [[ICMP4]](s1)
    ; GFX10-NEXT: [[ICMP5:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE6]](s32), [[UV31]]
    ; GFX10-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP5]](s1), [[SEXT3]], [[SEXT2]]
    ; GFX10-NEXT: [[USUBO6:%[0-9]+]]:_(s32), [[USUBO7:%[0-9]+]]:_(s1) = G_USUBO [[USUBO4]], [[UV30]]
    ; GFX10-NEXT: [[USUBE8:%[0-9]+]]:_(s32), [[USUBE9:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[UV31]], [[USUBO5]]
    ; GFX10-NEXT: [[USUBE10:%[0-9]+]]:_(s32), [[USUBE11:%[0-9]+]]:_(s1) = G_USUBE [[USUBE8]], [[C6]], [[USUBO7]]
    ; GFX10-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO6]](s32), [[USUBE10]](s32)
    ; GFX10-NEXT: [[ICMP6:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT1]](s32), [[C6]]
    ; GFX10-NEXT: [[SELECT2:%[0-9]+]]:_(s64) = G_SELECT [[ICMP6]](s1), [[MV4]], [[MV3]]
    ; GFX10-NEXT: [[ICMP7:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT]](s32), [[C6]]
    ; GFX10-NEXT: [[SELECT3:%[0-9]+]]:_(s64) = G_SELECT [[ICMP7]](s1), [[SELECT2]], [[MV2]]
    ; GFX10-NEXT: [[XOR2:%[0-9]+]]:_(s64) = G_XOR [[SELECT3]], [[ASHR]]
    ; GFX10-NEXT: [[UV32:%[0-9]+]]:_(s32), [[UV33:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR2]](s64)
    ; GFX10-NEXT: [[UV34:%[0-9]+]]:_(s32), [[UV35:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX10-NEXT: [[USUBO8:%[0-9]+]]:_(s32), [[USUBO9:%[0-9]+]]:_(i1) = G_USUBO [[UV32]], [[UV34]]
    ; GFX10-NEXT: [[USUBE12:%[0-9]+]]:_(s32), [[USUBE13:%[0-9]+]]:_(i1) = G_USUBE [[UV33]], [[UV35]], [[USUBO9]]
    ; GFX10-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO8]](s32), [[USUBE12]](s32)
    ; GFX10-NEXT: [[ASHR2:%[0-9]+]]:_(s64) = G_ASHR [[UV1]], [[C]](s32)
    ; GFX10-NEXT: [[ASHR3:%[0-9]+]]:_(s64) = G_ASHR [[UV3]], [[C]](s32)
    ; GFX10-NEXT: [[UV36:%[0-9]+]]:_(s32), [[UV37:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV1]](s64)
    ; GFX10-NEXT: [[UV38:%[0-9]+]]:_(s32), [[UV39:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR2]](s64)
    ; GFX10-NEXT: [[UADDO38:%[0-9]+]]:_(s32), [[UADDO39:%[0-9]+]]:_(i1) = G_UADDO [[UV36]], [[UV38]]
    ; GFX10-NEXT: [[UADDE8:%[0-9]+]]:_(s32), [[UADDE9:%[0-9]+]]:_(i1) = G_UADDE [[UV37]], [[UV39]], [[UADDO39]]
    ; GFX10-NEXT: [[MV6:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO38]](s32), [[UADDE8]](s32)
    ; GFX10-NEXT: [[UV40:%[0-9]+]]:_(s32), [[UV41:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[UV3]](s64)
    ; GFX10-NEXT: [[UV42:%[0-9]+]]:_(s32), [[UV43:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR3]](s64)
    ; GFX10-NEXT: [[UADDO40:%[0-9]+]]:_(s32), [[UADDO41:%[0-9]+]]:_(i1) = G_UADDO [[UV40]], [[UV42]]
    ; GFX10-NEXT: [[UADDE10:%[0-9]+]]:_(s32), [[UADDE11:%[0-9]+]]:_(i1) = G_UADDE [[UV41]], [[UV43]], [[UADDO41]]
    ; GFX10-NEXT: [[MV7:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO40]](s32), [[UADDE10]](s32)
    ; GFX10-NEXT: [[XOR3:%[0-9]+]]:_(s64) = G_XOR [[MV6]], [[ASHR2]]
    ; GFX10-NEXT: [[XOR4:%[0-9]+]]:_(s64) = G_XOR [[MV7]], [[ASHR3]]
    ; GFX10-NEXT: [[UV44:%[0-9]+]]:_(i32), [[UV45:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX10-NEXT: [[UITOFP2:%[0-9]+]]:_(f32) = G_UITOFP [[UV44]](i32)
    ; GFX10-NEXT: [[UITOFP3:%[0-9]+]]:_(f32) = G_UITOFP [[UV45]](i32)
    ; GFX10-NEXT: [[FMUL4:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP3]], [[C1]]
    ; GFX10-NEXT: [[FADD2:%[0-9]+]]:_(f32) = G_FADD [[FMUL4]], [[UITOFP2]]
    ; GFX10-NEXT: [[AMDGPU_RCP_IFLAG1:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD2]](f32)
    ; GFX10-NEXT: [[FMUL5:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG1]], [[C2]]
    ; GFX10-NEXT: [[FMUL6:%[0-9]+]]:_(f32) = G_FMUL [[FMUL5]], [[C3]]
    ; GFX10-NEXT: [[INTRINSIC_TRUNC1:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL6]]
    ; GFX10-NEXT: [[FMUL7:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC1]], [[C4]]
    ; GFX10-NEXT: [[FADD3:%[0-9]+]]:_(f32) = G_FADD [[FMUL7]], [[FMUL5]]
    ; GFX10-NEXT: [[FPTOUI2:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD3]](f32)
    ; GFX10-NEXT: [[FPTOUI3:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC1]](f32)
    ; GFX10-NEXT: [[UV46:%[0-9]+]]:_(s32), [[UV47:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX10-NEXT: [[UV48:%[0-9]+]]:_(s32), [[UV49:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX10-NEXT: [[USUBO10:%[0-9]+]]:_(s32), [[USUBO11:%[0-9]+]]:_(i1) = G_USUBO [[UV46]], [[UV48]]
    ; GFX10-NEXT: [[USUBE14:%[0-9]+]]:_(s32), [[USUBE15:%[0-9]+]]:_(i1) = G_USUBE [[UV47]], [[UV49]], [[USUBO11]]
    ; GFX10-NEXT: [[AMDGPU_MAD_U64_U32_6:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_7:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO10]](s32), [[FPTOUI2]], [[C5]]
    ; GFX10-NEXT: [[UV50:%[0-9]+]]:_(i32), [[UV51:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_6]](s64)
    ; GFX10-NEXT: [[MUL15:%[0-9]+]]:_(i32) = G_MUL [[USUBO10]], [[FPTOUI3]]
    ; GFX10-NEXT: [[ADD18:%[0-9]+]]:_(s32) = G_ADD [[UV51]], [[MUL15]]
    ; GFX10-NEXT: [[MUL16:%[0-9]+]]:_(i32) = G_MUL [[USUBE14]], [[FPTOUI2]]
    ; GFX10-NEXT: [[ADD19:%[0-9]+]]:_(s32) = G_ADD [[ADD18]], [[MUL16]]
    ; GFX10-NEXT: [[UMULH12:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI2]], [[UV50]]
    ; GFX10-NEXT: [[MUL17:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI2]], [[ADD19]]
    ; GFX10-NEXT: [[MUL18:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI3]], [[UV50]]
    ; GFX10-NEXT: [[UADDO42:%[0-9]+]]:_(i32), [[UADDO43:%[0-9]+]]:_(i1) = G_UADDO [[UMULH12]], [[MUL17]]
    ; GFX10-NEXT: [[ZEXT15:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO43]](i1)
    ; GFX10-NEXT: [[UADDO44:%[0-9]+]]:_(i32), [[UADDO45:%[0-9]+]]:_(i1) = G_UADDO [[UADDO42]], [[MUL18]]
    ; GFX10-NEXT: [[ZEXT16:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO45]](i1)
    ; GFX10-NEXT: [[ADD20:%[0-9]+]]:_(i32) = G_ADD [[ZEXT15]], [[ZEXT16]]
    ; GFX10-NEXT: [[UMULH13:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI3]], [[UV50]]
    ; GFX10-NEXT: [[UMULH14:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI2]], [[ADD19]]
    ; GFX10-NEXT: [[MUL19:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI3]], [[ADD19]]
    ; GFX10-NEXT: [[UADDO46:%[0-9]+]]:_(i32), [[UADDO47:%[0-9]+]]:_(i1) = G_UADDO [[UMULH13]], [[UMULH14]]
    ; GFX10-NEXT: [[ZEXT17:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO47]](i1)
    ; GFX10-NEXT: [[UADDO48:%[0-9]+]]:_(i32), [[UADDO49:%[0-9]+]]:_(i1) = G_UADDO [[UADDO46]], [[MUL19]]
    ; GFX10-NEXT: [[ZEXT18:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO49]](i1)
    ; GFX10-NEXT: [[ADD21:%[0-9]+]]:_(i32) = G_ADD [[ZEXT17]], [[ZEXT18]]
    ; GFX10-NEXT: [[UADDO50:%[0-9]+]]:_(i32), [[UADDO51:%[0-9]+]]:_(i1) = G_UADDO [[UADDO48]], [[ADD20]]
    ; GFX10-NEXT: [[ZEXT19:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO51]](i1)
    ; GFX10-NEXT: [[ADD22:%[0-9]+]]:_(i32) = G_ADD [[ADD21]], [[ZEXT19]]
    ; GFX10-NEXT: [[UMULH15:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI3]], [[ADD19]]
    ; GFX10-NEXT: [[ADD23:%[0-9]+]]:_(i32) = G_ADD [[UMULH15]], [[ADD22]]
    ; GFX10-NEXT: [[UADDO52:%[0-9]+]]:_(s32), [[UADDO53:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI2]], [[UADDO50]]
    ; GFX10-NEXT: [[UADDE12:%[0-9]+]]:_(s32), [[UADDE13:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI3]], [[ADD23]], [[UADDO53]]
    ; GFX10-NEXT: [[AMDGPU_MAD_U64_U32_8:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_9:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO10]](s32), [[UADDO52]], [[C5]]
    ; GFX10-NEXT: [[UV52:%[0-9]+]]:_(i32), [[UV53:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_8]](s64)
    ; GFX10-NEXT: [[MUL20:%[0-9]+]]:_(i32) = G_MUL [[USUBO10]], [[UADDE12]]
    ; GFX10-NEXT: [[ADD24:%[0-9]+]]:_(s32) = G_ADD [[UV53]], [[MUL20]]
    ; GFX10-NEXT: [[MUL21:%[0-9]+]]:_(i32) = G_MUL [[USUBE14]], [[UADDO52]]
    ; GFX10-NEXT: [[ADD25:%[0-9]+]]:_(s32) = G_ADD [[ADD24]], [[MUL21]]
    ; GFX10-NEXT: [[UMULH16:%[0-9]+]]:_(i32) = G_UMULH [[UADDO52]], [[UV52]]
    ; GFX10-NEXT: [[MUL22:%[0-9]+]]:_(i32) = G_MUL [[UADDO52]], [[ADD25]]
    ; GFX10-NEXT: [[MUL23:%[0-9]+]]:_(i32) = G_MUL [[UADDE12]], [[UV52]]
    ; GFX10-NEXT: [[UADDO54:%[0-9]+]]:_(i32), [[UADDO55:%[0-9]+]]:_(i1) = G_UADDO [[UMULH16]], [[MUL22]]
    ; GFX10-NEXT: [[ZEXT20:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO55]](i1)
    ; GFX10-NEXT: [[UADDO56:%[0-9]+]]:_(i32), [[UADDO57:%[0-9]+]]:_(i1) = G_UADDO [[UADDO54]], [[MUL23]]
    ; GFX10-NEXT: [[ZEXT21:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO57]](i1)
    ; GFX10-NEXT: [[ADD26:%[0-9]+]]:_(i32) = G_ADD [[ZEXT20]], [[ZEXT21]]
    ; GFX10-NEXT: [[UMULH17:%[0-9]+]]:_(i32) = G_UMULH [[UADDE12]], [[UV52]]
    ; GFX10-NEXT: [[UMULH18:%[0-9]+]]:_(i32) = G_UMULH [[UADDO52]], [[ADD25]]
    ; GFX10-NEXT: [[MUL24:%[0-9]+]]:_(i32) = G_MUL [[UADDE12]], [[ADD25]]
    ; GFX10-NEXT: [[UADDO58:%[0-9]+]]:_(i32), [[UADDO59:%[0-9]+]]:_(i1) = G_UADDO [[UMULH17]], [[UMULH18]]
    ; GFX10-NEXT: [[ZEXT22:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO59]](i1)
    ; GFX10-NEXT: [[UADDO60:%[0-9]+]]:_(i32), [[UADDO61:%[0-9]+]]:_(i1) = G_UADDO [[UADDO58]], [[MUL24]]
    ; GFX10-NEXT: [[ZEXT23:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO61]](i1)
    ; GFX10-NEXT: [[ADD27:%[0-9]+]]:_(i32) = G_ADD [[ZEXT22]], [[ZEXT23]]
    ; GFX10-NEXT: [[UADDO62:%[0-9]+]]:_(i32), [[UADDO63:%[0-9]+]]:_(i1) = G_UADDO [[UADDO60]], [[ADD26]]
    ; GFX10-NEXT: [[ZEXT24:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO63]](i1)
    ; GFX10-NEXT: [[ADD28:%[0-9]+]]:_(i32) = G_ADD [[ADD27]], [[ZEXT24]]
    ; GFX10-NEXT: [[UMULH19:%[0-9]+]]:_(i32) = G_UMULH [[UADDE12]], [[ADD25]]
    ; GFX10-NEXT: [[ADD29:%[0-9]+]]:_(i32) = G_ADD [[UMULH19]], [[ADD28]]
    ; GFX10-NEXT: [[UADDO64:%[0-9]+]]:_(s32), [[UADDO65:%[0-9]+]]:_(s1) = G_UADDO [[UADDO52]], [[UADDO62]]
    ; GFX10-NEXT: [[UADDE14:%[0-9]+]]:_(s32), [[UADDE15:%[0-9]+]]:_(s1) = G_UADDE [[UADDE12]], [[ADD29]], [[UADDO65]]
    ; GFX10-NEXT: [[UV54:%[0-9]+]]:_(i32), [[UV55:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR3]](s64)
    ; GFX10-NEXT: [[UV56:%[0-9]+]]:_(i32), [[UV57:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR3]](s64)
    ; GFX10-NEXT: [[UMULH20:%[0-9]+]]:_(i32) = G_UMULH [[UV56]], [[UADDO64]]
    ; GFX10-NEXT: [[MUL25:%[0-9]+]]:_(i32) = G_MUL [[UV56]], [[UADDE14]]
    ; GFX10-NEXT: [[MUL26:%[0-9]+]]:_(i32) = G_MUL [[UV57]], [[UADDO64]]
    ; GFX10-NEXT: [[UADDO66:%[0-9]+]]:_(i32), [[UADDO67:%[0-9]+]]:_(i1) = G_UADDO [[UMULH20]], [[MUL25]]
    ; GFX10-NEXT: [[ZEXT25:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO67]](i1)
    ; GFX10-NEXT: [[UADDO68:%[0-9]+]]:_(i32), [[UADDO69:%[0-9]+]]:_(i1) = G_UADDO [[UADDO66]], [[MUL26]]
    ; GFX10-NEXT: [[ZEXT26:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO69]](i1)
    ; GFX10-NEXT: [[ADD30:%[0-9]+]]:_(i32) = G_ADD [[ZEXT25]], [[ZEXT26]]
    ; GFX10-NEXT: [[UMULH21:%[0-9]+]]:_(i32) = G_UMULH [[UV57]], [[UADDO64]]
    ; GFX10-NEXT: [[UMULH22:%[0-9]+]]:_(i32) = G_UMULH [[UV56]], [[UADDE14]]
    ; GFX10-NEXT: [[MUL27:%[0-9]+]]:_(i32) = G_MUL [[UV57]], [[UADDE14]]
    ; GFX10-NEXT: [[UADDO70:%[0-9]+]]:_(i32), [[UADDO71:%[0-9]+]]:_(i1) = G_UADDO [[UMULH21]], [[UMULH22]]
    ; GFX10-NEXT: [[ZEXT27:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO71]](i1)
    ; GFX10-NEXT: [[UADDO72:%[0-9]+]]:_(i32), [[UADDO73:%[0-9]+]]:_(i1) = G_UADDO [[UADDO70]], [[MUL27]]
    ; GFX10-NEXT: [[ZEXT28:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO73]](i1)
    ; GFX10-NEXT: [[ADD31:%[0-9]+]]:_(i32) = G_ADD [[ZEXT27]], [[ZEXT28]]
    ; GFX10-NEXT: [[UADDO74:%[0-9]+]]:_(i32), [[UADDO75:%[0-9]+]]:_(i1) = G_UADDO [[UADDO72]], [[ADD30]]
    ; GFX10-NEXT: [[ZEXT29:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO75]](i1)
    ; GFX10-NEXT: [[ADD32:%[0-9]+]]:_(i32) = G_ADD [[ADD31]], [[ZEXT29]]
    ; GFX10-NEXT: [[UMULH23:%[0-9]+]]:_(i32) = G_UMULH [[UV57]], [[UADDE14]]
    ; GFX10-NEXT: [[ADD33:%[0-9]+]]:_(i32) = G_ADD [[UMULH23]], [[ADD32]]
    ; GFX10-NEXT: [[UV58:%[0-9]+]]:_(i32), [[UV59:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX10-NEXT: [[AMDGPU_MAD_U64_U32_10:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_11:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV58]](i32), [[UADDO74]], [[C5]]
    ; GFX10-NEXT: [[UV60:%[0-9]+]]:_(i32), [[UV61:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_10]](s64)
    ; GFX10-NEXT: [[MUL28:%[0-9]+]]:_(i32) = G_MUL [[UV58]], [[ADD33]]
    ; GFX10-NEXT: [[ADD34:%[0-9]+]]:_(s32) = G_ADD [[UV61]], [[MUL28]]
    ; GFX10-NEXT: [[MUL29:%[0-9]+]]:_(i32) = G_MUL [[UV59]], [[UADDO74]]
    ; GFX10-NEXT: [[ADD35:%[0-9]+]]:_(s32) = G_ADD [[ADD34]], [[MUL29]]
    ; GFX10-NEXT: [[USUBO12:%[0-9]+]]:_(s32), [[USUBO13:%[0-9]+]]:_(s1) = G_USUBO [[UV54]], [[UV60]]
    ; GFX10-NEXT: [[USUBE16:%[0-9]+]]:_(s32), [[USUBE17:%[0-9]+]]:_(s1) = G_USUBE [[UV55]], [[ADD35]], [[USUBO13]]
    ; GFX10-NEXT: [[SUB1:%[0-9]+]]:_(s32) = G_SUB [[UV55]], [[ADD35]]
    ; GFX10-NEXT: [[MV8:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO12]](s32), [[USUBE16]](s32)
    ; GFX10-NEXT: [[UV62:%[0-9]+]]:_(i32), [[UV63:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR4]](s64)
    ; GFX10-NEXT: [[ICMP8:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE16]](s32), [[UV63]]
    ; GFX10-NEXT: [[SEXT4:%[0-9]+]]:_(s32) = G_SEXT [[ICMP8]](s1)
    ; GFX10-NEXT: [[ICMP9:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO12]](s32), [[UV62]]
    ; GFX10-NEXT: [[SEXT5:%[0-9]+]]:_(s32) = G_SEXT [[ICMP9]](s1)
    ; GFX10-NEXT: [[ICMP10:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE16]](s32), [[UV63]]
    ; GFX10-NEXT: [[SELECT4:%[0-9]+]]:_(s32) = G_SELECT [[ICMP10]](s1), [[SEXT5]], [[SEXT4]]
    ; GFX10-NEXT: [[USUBO14:%[0-9]+]]:_(s32), [[USUBO15:%[0-9]+]]:_(s1) = G_USUBO [[USUBO12]], [[UV62]]
    ; GFX10-NEXT: [[USUBE18:%[0-9]+]]:_(s32), [[USUBE19:%[0-9]+]]:_(s1) = G_USUBE [[SUB1]], [[UV63]], [[USUBO13]]
    ; GFX10-NEXT: [[USUBE20:%[0-9]+]]:_(s32), [[USUBE21:%[0-9]+]]:_(s1) = G_USUBE [[USUBE18]], [[C6]], [[USUBO15]]
    ; GFX10-NEXT: [[MV9:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO14]](s32), [[USUBE20]](s32)
    ; GFX10-NEXT: [[ICMP11:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE20]](s32), [[UV63]]
    ; GFX10-NEXT: [[SEXT6:%[0-9]+]]:_(s32) = G_SEXT [[ICMP11]](s1)
    ; GFX10-NEXT: [[ICMP12:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO14]](s32), [[UV62]]
    ; GFX10-NEXT: [[SEXT7:%[0-9]+]]:_(s32) = G_SEXT [[ICMP12]](s1)
    ; GFX10-NEXT: [[ICMP13:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE20]](s32), [[UV63]]
    ; GFX10-NEXT: [[SELECT5:%[0-9]+]]:_(s32) = G_SELECT [[ICMP13]](s1), [[SEXT7]], [[SEXT6]]
    ; GFX10-NEXT: [[USUBO16:%[0-9]+]]:_(s32), [[USUBO17:%[0-9]+]]:_(s1) = G_USUBO [[USUBO14]], [[UV62]]
    ; GFX10-NEXT: [[USUBE22:%[0-9]+]]:_(s32), [[USUBE23:%[0-9]+]]:_(s1) = G_USUBE [[USUBE18]], [[UV63]], [[USUBO15]]
    ; GFX10-NEXT: [[USUBE24:%[0-9]+]]:_(s32), [[USUBE25:%[0-9]+]]:_(s1) = G_USUBE [[USUBE22]], [[C6]], [[USUBO17]]
    ; GFX10-NEXT: [[MV10:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO16]](s32), [[USUBE24]](s32)
    ; GFX10-NEXT: [[ICMP14:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT5]](s32), [[C6]]
    ; GFX10-NEXT: [[SELECT6:%[0-9]+]]:_(s64) = G_SELECT [[ICMP14]](s1), [[MV10]], [[MV9]]
    ; GFX10-NEXT: [[ICMP15:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT4]](s32), [[C6]]
    ; GFX10-NEXT: [[SELECT7:%[0-9]+]]:_(s64) = G_SELECT [[ICMP15]](s1), [[SELECT6]], [[MV8]]
    ; GFX10-NEXT: [[XOR5:%[0-9]+]]:_(s64) = G_XOR [[SELECT7]], [[ASHR2]]
    ; GFX10-NEXT: [[UV64:%[0-9]+]]:_(s32), [[UV65:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR5]](s64)
    ; GFX10-NEXT: [[UV66:%[0-9]+]]:_(s32), [[UV67:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR2]](s64)
    ; GFX10-NEXT: [[USUBO18:%[0-9]+]]:_(s32), [[USUBO19:%[0-9]+]]:_(i1) = G_USUBO [[UV64]], [[UV66]]
    ; GFX10-NEXT: [[USUBE26:%[0-9]+]]:_(s32), [[USUBE27:%[0-9]+]]:_(i1) = G_USUBE [[UV65]], [[UV67]], [[USUBO19]]
    ; GFX10-NEXT: [[MV11:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO18]](s32), [[USUBE26]](s32)
    ; GFX10-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s64>) = G_BUILD_VECTOR [[MV5]](s64), [[MV11]](s64)
    ; GFX10-NEXT: $vgpr0_vgpr1_vgpr2_vgpr3 = COPY [[BUILD_VECTOR]](<2 x s64>)
    %0:_(<2 x s64>) = COPY $vgpr0_vgpr1_vgpr2_vgpr3
    %1:_(<2 x s64>) = COPY $vgpr4_vgpr5_vgpr6_vgpr7
    %2:_(<2 x s64>) = G_SREM %0, %1
    $vgpr0_vgpr1_vgpr2_vgpr3 = COPY %2
...

---
name: test_srem_s16
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1

    ; GFX6-LABEL: name: test_srem_s16
    ; GFX6: liveins: $vgpr0, $vgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX6-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX6-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 16
    ; GFX6-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 16
    ; GFX6-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX6-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX6-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX6-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX6-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX6-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX6-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX6-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX6-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX6-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX6-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX6-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX6-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX6-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX6-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX6-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX6-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX6-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX6-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX6-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX6-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX6-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX6-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX6-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX6-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX6-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX6-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX6-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX6-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; GFX6-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[SUB4]], [[C3]]
    ; GFX6-NEXT: $vgpr0 = COPY [[AND]](s32)
    ;
    ; GFX8-LABEL: name: test_srem_s16
    ; GFX8: liveins: $vgpr0, $vgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX8-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX8-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 16
    ; GFX8-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 16
    ; GFX8-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX8-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX8-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX8-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX8-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX8-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX8-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX8-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX8-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX8-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX8-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX8-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX8-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX8-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX8-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX8-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX8-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX8-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX8-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX8-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX8-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX8-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX8-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX8-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX8-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX8-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX8-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX8-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX8-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; GFX8-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[SUB4]], [[C3]]
    ; GFX8-NEXT: $vgpr0 = COPY [[AND]](s32)
    ;
    ; GFX9-LABEL: name: test_srem_s16
    ; GFX9: liveins: $vgpr0, $vgpr1
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX9-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 16
    ; GFX9-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 16
    ; GFX9-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX9-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX9-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX9-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX9-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX9-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX9-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX9-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX9-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX9-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX9-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX9-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX9-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX9-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX9-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX9-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX9-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX9-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX9-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX9-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX9-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX9-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX9-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX9-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX9-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX9-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX9-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX9-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX9-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; GFX9-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[SUB4]], [[C3]]
    ; GFX9-NEXT: $vgpr0 = COPY [[AND]](s32)
    ;
    ; GFX10-LABEL: name: test_srem_s16
    ; GFX10: liveins: $vgpr0, $vgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX10-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX10-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 16
    ; GFX10-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 16
    ; GFX10-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX10-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX10-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX10-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX10-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX10-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX10-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX10-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX10-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX10-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX10-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX10-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX10-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX10-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX10-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX10-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX10-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX10-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX10-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX10-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX10-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX10-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX10-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX10-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX10-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX10-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX10-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX10-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX10-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; GFX10-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[SUB4]], [[C3]]
    ; GFX10-NEXT: $vgpr0 = COPY [[AND]](s32)
    %0:_(s32) = COPY $vgpr0
    %1:_(s32) = COPY $vgpr1
    %2:_(s16) = G_TRUNC %0
    %3:_(s16) = G_TRUNC %1
    %4:_(s16) = G_SREM %2, %3
    %5:_(s32) = G_ZEXT %4
    $vgpr0 = COPY %5
...

---
name: test_srem_v2s16
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1

    ; GFX6-LABEL: name: test_srem_v2s16
    ; GFX6: liveins: $vgpr0, $vgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[COPY:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr0
    ; GFX6-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr1
    ; GFX6-NEXT: [[BITCAST:%[0-9]+]]:_(i32) = G_BITCAST [[COPY]](<2 x s16>)
    ; GFX6-NEXT: [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 16
    ; GFX6-NEXT: [[LSHR:%[0-9]+]]:_(i32) = G_LSHR [[BITCAST]], [[C]](i32)
    ; GFX6-NEXT: [[BITCAST1:%[0-9]+]]:_(i32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX6-NEXT: [[LSHR1:%[0-9]+]]:_(i32) = G_LSHR [[BITCAST1]], [[C]](i32)
    ; GFX6-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[BITCAST]], 16
    ; GFX6-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[BITCAST1]], 16
    ; GFX6-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX6-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C1]](s32)
    ; GFX6-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C1]](s32)
    ; GFX6-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX6-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX6-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX6-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX6-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX6-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX6-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX6-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX6-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX6-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX6-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C3]], [[XOR1]]
    ; GFX6-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX6-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX6-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX6-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX6-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX6-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX6-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX6-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX6-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX6-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX6-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX6-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX6-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX6-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX6-NEXT: [[SEXT_INREG2:%[0-9]+]]:_(s32) = G_SEXT_INREG [[LSHR]], 16
    ; GFX6-NEXT: [[SEXT_INREG3:%[0-9]+]]:_(s32) = G_SEXT_INREG [[LSHR1]], 16
    ; GFX6-NEXT: [[ASHR2:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG2]], [[C1]](s32)
    ; GFX6-NEXT: [[ASHR3:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG3]], [[C1]](s32)
    ; GFX6-NEXT: [[ADD3:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG2]], [[ASHR2]]
    ; GFX6-NEXT: [[ADD4:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG3]], [[ASHR3]]
    ; GFX6-NEXT: [[XOR3:%[0-9]+]]:_(s32) = G_XOR [[ADD3]], [[ASHR2]]
    ; GFX6-NEXT: [[XOR4:%[0-9]+]]:_(s32) = G_XOR [[ADD4]], [[ASHR3]]
    ; GFX6-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[XOR4]](s32)
    ; GFX6-NEXT: [[AMDGPU_RCP_IFLAG1:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP1]](f32)
    ; GFX6-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG1]], [[C2]]
    ; GFX6-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL1]](f32)
    ; GFX6-NEXT: [[SUB5:%[0-9]+]]:_(s32) = G_SUB [[C3]], [[XOR4]]
    ; GFX6-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[SUB5]], [[FPTOUI1]]
    ; GFX6-NEXT: [[UMULH2:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI1]], [[MUL2]]
    ; GFX6-NEXT: [[ADD5:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI1]], [[UMULH2]]
    ; GFX6-NEXT: [[UMULH3:%[0-9]+]]:_(s32) = G_UMULH [[XOR3]], [[ADD5]]
    ; GFX6-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[UMULH3]], [[XOR4]]
    ; GFX6-NEXT: [[SUB6:%[0-9]+]]:_(i32) = G_SUB [[XOR3]], [[MUL3]]
    ; GFX6-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB6]](i32), [[XOR4]]
    ; GFX6-NEXT: [[SUB7:%[0-9]+]]:_(s32) = G_SUB [[SUB6]], [[XOR4]]
    ; GFX6-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SUB7]], [[SUB6]]
    ; GFX6-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT2]](s32), [[XOR4]]
    ; GFX6-NEXT: [[SUB8:%[0-9]+]]:_(s32) = G_SUB [[SELECT2]], [[XOR4]]
    ; GFX6-NEXT: [[SELECT3:%[0-9]+]]:_(s32) = G_SELECT [[ICMP3]](s1), [[SUB8]], [[SELECT2]]
    ; GFX6-NEXT: [[XOR5:%[0-9]+]]:_(s32) = G_XOR [[SELECT3]], [[ASHR2]]
    ; GFX6-NEXT: [[SUB9:%[0-9]+]]:_(s32) = G_SUB [[XOR5]], [[ASHR2]]
    ; GFX6-NEXT: [[C4:%[0-9]+]]:_(i32) = G_CONSTANT i32 65535
    ; GFX6-NEXT: [[AND:%[0-9]+]]:_(i32) = G_AND [[SUB4]], [[C4]]
    ; GFX6-NEXT: [[AND1:%[0-9]+]]:_(i32) = G_AND [[SUB9]], [[C4]]
    ; GFX6-NEXT: [[SHL:%[0-9]+]]:_(i32) = G_SHL [[AND1]], [[C]](i32)
    ; GFX6-NEXT: [[OR:%[0-9]+]]:_(i32) = G_OR [[AND]], [[SHL]]
    ; GFX6-NEXT: [[BITCAST2:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](i32)
    ; GFX6-NEXT: $vgpr0 = COPY [[BITCAST2]](<2 x s16>)
    ;
    ; GFX8-LABEL: name: test_srem_v2s16
    ; GFX8: liveins: $vgpr0, $vgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr0
    ; GFX8-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr1
    ; GFX8-NEXT: [[BITCAST:%[0-9]+]]:_(i32) = G_BITCAST [[COPY]](<2 x s16>)
    ; GFX8-NEXT: [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 16
    ; GFX8-NEXT: [[LSHR:%[0-9]+]]:_(i32) = G_LSHR [[BITCAST]], [[C]](i32)
    ; GFX8-NEXT: [[BITCAST1:%[0-9]+]]:_(i32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX8-NEXT: [[LSHR1:%[0-9]+]]:_(i32) = G_LSHR [[BITCAST1]], [[C]](i32)
    ; GFX8-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[BITCAST]], 16
    ; GFX8-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[BITCAST1]], 16
    ; GFX8-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX8-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C1]](s32)
    ; GFX8-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C1]](s32)
    ; GFX8-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX8-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX8-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX8-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX8-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX8-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX8-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX8-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX8-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX8-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX8-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C3]], [[XOR1]]
    ; GFX8-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX8-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX8-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX8-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX8-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX8-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX8-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX8-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX8-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX8-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX8-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX8-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX8-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX8-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX8-NEXT: [[SEXT_INREG2:%[0-9]+]]:_(s32) = G_SEXT_INREG [[LSHR]], 16
    ; GFX8-NEXT: [[SEXT_INREG3:%[0-9]+]]:_(s32) = G_SEXT_INREG [[LSHR1]], 16
    ; GFX8-NEXT: [[ASHR2:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG2]], [[C1]](s32)
    ; GFX8-NEXT: [[ASHR3:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG3]], [[C1]](s32)
    ; GFX8-NEXT: [[ADD3:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG2]], [[ASHR2]]
    ; GFX8-NEXT: [[ADD4:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG3]], [[ASHR3]]
    ; GFX8-NEXT: [[XOR3:%[0-9]+]]:_(s32) = G_XOR [[ADD3]], [[ASHR2]]
    ; GFX8-NEXT: [[XOR4:%[0-9]+]]:_(s32) = G_XOR [[ADD4]], [[ASHR3]]
    ; GFX8-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[XOR4]](s32)
    ; GFX8-NEXT: [[AMDGPU_RCP_IFLAG1:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP1]](f32)
    ; GFX8-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG1]], [[C2]]
    ; GFX8-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL1]](f32)
    ; GFX8-NEXT: [[SUB5:%[0-9]+]]:_(s32) = G_SUB [[C3]], [[XOR4]]
    ; GFX8-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[SUB5]], [[FPTOUI1]]
    ; GFX8-NEXT: [[UMULH2:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI1]], [[MUL2]]
    ; GFX8-NEXT: [[ADD5:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI1]], [[UMULH2]]
    ; GFX8-NEXT: [[UMULH3:%[0-9]+]]:_(s32) = G_UMULH [[XOR3]], [[ADD5]]
    ; GFX8-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[UMULH3]], [[XOR4]]
    ; GFX8-NEXT: [[SUB6:%[0-9]+]]:_(i32) = G_SUB [[XOR3]], [[MUL3]]
    ; GFX8-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB6]](i32), [[XOR4]]
    ; GFX8-NEXT: [[SUB7:%[0-9]+]]:_(s32) = G_SUB [[SUB6]], [[XOR4]]
    ; GFX8-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SUB7]], [[SUB6]]
    ; GFX8-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT2]](s32), [[XOR4]]
    ; GFX8-NEXT: [[SUB8:%[0-9]+]]:_(s32) = G_SUB [[SELECT2]], [[XOR4]]
    ; GFX8-NEXT: [[SELECT3:%[0-9]+]]:_(s32) = G_SELECT [[ICMP3]](s1), [[SUB8]], [[SELECT2]]
    ; GFX8-NEXT: [[XOR5:%[0-9]+]]:_(s32) = G_XOR [[SELECT3]], [[ASHR2]]
    ; GFX8-NEXT: [[SUB9:%[0-9]+]]:_(s32) = G_SUB [[XOR5]], [[ASHR2]]
    ; GFX8-NEXT: [[C4:%[0-9]+]]:_(i32) = G_CONSTANT i32 65535
    ; GFX8-NEXT: [[AND:%[0-9]+]]:_(i32) = G_AND [[SUB4]], [[C4]]
    ; GFX8-NEXT: [[AND1:%[0-9]+]]:_(i32) = G_AND [[SUB9]], [[C4]]
    ; GFX8-NEXT: [[SHL:%[0-9]+]]:_(i32) = G_SHL [[AND1]], [[C]](i32)
    ; GFX8-NEXT: [[OR:%[0-9]+]]:_(i32) = G_OR [[AND]], [[SHL]]
    ; GFX8-NEXT: [[BITCAST2:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](i32)
    ; GFX8-NEXT: $vgpr0 = COPY [[BITCAST2]](<2 x s16>)
    ;
    ; GFX9-LABEL: name: test_srem_v2s16
    ; GFX9: liveins: $vgpr0, $vgpr1
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr0
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr1
    ; GFX9-NEXT: [[BITCAST:%[0-9]+]]:_(i32) = G_BITCAST [[COPY]](<2 x s16>)
    ; GFX9-NEXT: [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 16
    ; GFX9-NEXT: [[LSHR:%[0-9]+]]:_(i32) = G_LSHR [[BITCAST]], [[C]](i32)
    ; GFX9-NEXT: [[BITCAST1:%[0-9]+]]:_(i32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX9-NEXT: [[LSHR1:%[0-9]+]]:_(i32) = G_LSHR [[BITCAST1]], [[C]](i32)
    ; GFX9-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[BITCAST]], 16
    ; GFX9-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[BITCAST1]], 16
    ; GFX9-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX9-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C1]](s32)
    ; GFX9-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C1]](s32)
    ; GFX9-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX9-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX9-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX9-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX9-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX9-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX9-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX9-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX9-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX9-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX9-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C3]], [[XOR1]]
    ; GFX9-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX9-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX9-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX9-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX9-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX9-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX9-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX9-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX9-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX9-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX9-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX9-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX9-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX9-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX9-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[SUB4]](s32)
    ; GFX9-NEXT: [[SEXT_INREG2:%[0-9]+]]:_(s32) = G_SEXT_INREG [[LSHR]], 16
    ; GFX9-NEXT: [[SEXT_INREG3:%[0-9]+]]:_(s32) = G_SEXT_INREG [[LSHR1]], 16
    ; GFX9-NEXT: [[ASHR2:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG2]], [[C1]](s32)
    ; GFX9-NEXT: [[ASHR3:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG3]], [[C1]](s32)
    ; GFX9-NEXT: [[ADD3:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG2]], [[ASHR2]]
    ; GFX9-NEXT: [[ADD4:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG3]], [[ASHR3]]
    ; GFX9-NEXT: [[XOR3:%[0-9]+]]:_(s32) = G_XOR [[ADD3]], [[ASHR2]]
    ; GFX9-NEXT: [[XOR4:%[0-9]+]]:_(s32) = G_XOR [[ADD4]], [[ASHR3]]
    ; GFX9-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[XOR4]](s32)
    ; GFX9-NEXT: [[AMDGPU_RCP_IFLAG1:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP1]](f32)
    ; GFX9-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG1]], [[C2]]
    ; GFX9-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL1]](f32)
    ; GFX9-NEXT: [[SUB5:%[0-9]+]]:_(s32) = G_SUB [[C3]], [[XOR4]]
    ; GFX9-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[SUB5]], [[FPTOUI1]]
    ; GFX9-NEXT: [[UMULH2:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI1]], [[MUL2]]
    ; GFX9-NEXT: [[ADD5:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI1]], [[UMULH2]]
    ; GFX9-NEXT: [[UMULH3:%[0-9]+]]:_(s32) = G_UMULH [[XOR3]], [[ADD5]]
    ; GFX9-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[UMULH3]], [[XOR4]]
    ; GFX9-NEXT: [[SUB6:%[0-9]+]]:_(i32) = G_SUB [[XOR3]], [[MUL3]]
    ; GFX9-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB6]](i32), [[XOR4]]
    ; GFX9-NEXT: [[SUB7:%[0-9]+]]:_(s32) = G_SUB [[SUB6]], [[XOR4]]
    ; GFX9-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SUB7]], [[SUB6]]
    ; GFX9-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT2]](s32), [[XOR4]]
    ; GFX9-NEXT: [[SUB8:%[0-9]+]]:_(s32) = G_SUB [[SELECT2]], [[XOR4]]
    ; GFX9-NEXT: [[SELECT3:%[0-9]+]]:_(s32) = G_SELECT [[ICMP3]](s1), [[SUB8]], [[SELECT2]]
    ; GFX9-NEXT: [[XOR5:%[0-9]+]]:_(s32) = G_XOR [[SELECT3]], [[ASHR2]]
    ; GFX9-NEXT: [[SUB9:%[0-9]+]]:_(s32) = G_SUB [[XOR5]], [[ASHR2]]
    ; GFX9-NEXT: [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[SUB9]](s32)
    ; GFX9-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
    ; GFX9-NEXT: $vgpr0 = COPY [[BUILD_VECTOR]](<2 x s16>)
    ;
    ; GFX10-LABEL: name: test_srem_v2s16
    ; GFX10: liveins: $vgpr0, $vgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr0
    ; GFX10-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr1
    ; GFX10-NEXT: [[BITCAST:%[0-9]+]]:_(i32) = G_BITCAST [[COPY]](<2 x s16>)
    ; GFX10-NEXT: [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 16
    ; GFX10-NEXT: [[LSHR:%[0-9]+]]:_(i32) = G_LSHR [[BITCAST]], [[C]](i32)
    ; GFX10-NEXT: [[BITCAST1:%[0-9]+]]:_(i32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX10-NEXT: [[LSHR1:%[0-9]+]]:_(i32) = G_LSHR [[BITCAST1]], [[C]](i32)
    ; GFX10-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[BITCAST]], 16
    ; GFX10-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[BITCAST1]], 16
    ; GFX10-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX10-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C1]](s32)
    ; GFX10-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C1]](s32)
    ; GFX10-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX10-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX10-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX10-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX10-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX10-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX10-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX10-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX10-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX10-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX10-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C3]], [[XOR1]]
    ; GFX10-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX10-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX10-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX10-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX10-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX10-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX10-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX10-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX10-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX10-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX10-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX10-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX10-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX10-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX10-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[SUB4]](s32)
    ; GFX10-NEXT: [[SEXT_INREG2:%[0-9]+]]:_(s32) = G_SEXT_INREG [[LSHR]], 16
    ; GFX10-NEXT: [[SEXT_INREG3:%[0-9]+]]:_(s32) = G_SEXT_INREG [[LSHR1]], 16
    ; GFX10-NEXT: [[ASHR2:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG2]], [[C1]](s32)
    ; GFX10-NEXT: [[ASHR3:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG3]], [[C1]](s32)
    ; GFX10-NEXT: [[ADD3:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG2]], [[ASHR2]]
    ; GFX10-NEXT: [[ADD4:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG3]], [[ASHR3]]
    ; GFX10-NEXT: [[XOR3:%[0-9]+]]:_(s32) = G_XOR [[ADD3]], [[ASHR2]]
    ; GFX10-NEXT: [[XOR4:%[0-9]+]]:_(s32) = G_XOR [[ADD4]], [[ASHR3]]
    ; GFX10-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[XOR4]](s32)
    ; GFX10-NEXT: [[AMDGPU_RCP_IFLAG1:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP1]](f32)
    ; GFX10-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG1]], [[C2]]
    ; GFX10-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL1]](f32)
    ; GFX10-NEXT: [[SUB5:%[0-9]+]]:_(s32) = G_SUB [[C3]], [[XOR4]]
    ; GFX10-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[SUB5]], [[FPTOUI1]]
    ; GFX10-NEXT: [[UMULH2:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI1]], [[MUL2]]
    ; GFX10-NEXT: [[ADD5:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI1]], [[UMULH2]]
    ; GFX10-NEXT: [[UMULH3:%[0-9]+]]:_(s32) = G_UMULH [[XOR3]], [[ADD5]]
    ; GFX10-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[UMULH3]], [[XOR4]]
    ; GFX10-NEXT: [[SUB6:%[0-9]+]]:_(i32) = G_SUB [[XOR3]], [[MUL3]]
    ; GFX10-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB6]](i32), [[XOR4]]
    ; GFX10-NEXT: [[SUB7:%[0-9]+]]:_(s32) = G_SUB [[SUB6]], [[XOR4]]
    ; GFX10-NEXT: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SUB7]], [[SUB6]]
    ; GFX10-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT2]](s32), [[XOR4]]
    ; GFX10-NEXT: [[SUB8:%[0-9]+]]:_(s32) = G_SUB [[SELECT2]], [[XOR4]]
    ; GFX10-NEXT: [[SELECT3:%[0-9]+]]:_(s32) = G_SELECT [[ICMP3]](s1), [[SUB8]], [[SELECT2]]
    ; GFX10-NEXT: [[XOR5:%[0-9]+]]:_(s32) = G_XOR [[SELECT3]], [[ASHR2]]
    ; GFX10-NEXT: [[SUB9:%[0-9]+]]:_(s32) = G_SUB [[XOR5]], [[ASHR2]]
    ; GFX10-NEXT: [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[SUB9]](s32)
    ; GFX10-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
    ; GFX10-NEXT: $vgpr0 = COPY [[BUILD_VECTOR]](<2 x s16>)
    %0:_(<2 x s16>) = COPY $vgpr0
    %1:_(<2 x s16>) = COPY $vgpr1
    %2:_(<2 x s16>) = G_SREM %0, %1
    $vgpr0 = COPY %2
...

---
name: test_srem_s7
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1

    ; GFX6-LABEL: name: test_srem_s7
    ; GFX6: liveins: $vgpr0, $vgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX6-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX6-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 7
    ; GFX6-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 7
    ; GFX6-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX6-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX6-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX6-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX6-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX6-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX6-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX6-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX6-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX6-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX6-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX6-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX6-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX6-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX6-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX6-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX6-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX6-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX6-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX6-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX6-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX6-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX6-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX6-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX6-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX6-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX6-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX6-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX6-NEXT: $vgpr0 = COPY [[SUB4]](s32)
    ;
    ; GFX8-LABEL: name: test_srem_s7
    ; GFX8: liveins: $vgpr0, $vgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX8-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX8-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 7
    ; GFX8-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 7
    ; GFX8-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX8-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX8-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX8-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX8-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX8-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX8-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX8-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX8-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX8-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX8-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX8-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX8-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX8-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX8-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX8-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX8-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX8-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX8-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX8-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX8-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX8-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX8-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX8-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX8-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX8-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX8-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX8-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX8-NEXT: $vgpr0 = COPY [[SUB4]](s32)
    ;
    ; GFX9-LABEL: name: test_srem_s7
    ; GFX9: liveins: $vgpr0, $vgpr1
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX9-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 7
    ; GFX9-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 7
    ; GFX9-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX9-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX9-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX9-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX9-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX9-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX9-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX9-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX9-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX9-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX9-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX9-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX9-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX9-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX9-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX9-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX9-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX9-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX9-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX9-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX9-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX9-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX9-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX9-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX9-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX9-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX9-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX9-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX9-NEXT: $vgpr0 = COPY [[SUB4]](s32)
    ;
    ; GFX10-LABEL: name: test_srem_s7
    ; GFX10: liveins: $vgpr0, $vgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX10-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX10-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 7
    ; GFX10-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 7
    ; GFX10-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX10-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX10-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX10-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX10-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX10-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX10-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX10-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX10-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX10-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX10-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX10-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX10-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX10-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX10-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX10-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX10-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX10-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX10-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX10-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX10-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX10-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX10-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX10-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX10-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX10-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX10-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX10-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX10-NEXT: $vgpr0 = COPY [[SUB4]](s32)
    %0:_(s32) = COPY $vgpr0
    %1:_(s32) = COPY $vgpr1
    %2:_(s7) = G_TRUNC %0
    %3:_(s7) = G_TRUNC %1
    %4:_(s7) = G_SREM %2, %3
    %5:_(s32) = G_ANYEXT %4
    $vgpr0 = COPY %5
...

---
name: test_srem_s17
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1

    ; GFX6-LABEL: name: test_srem_s17
    ; GFX6: liveins: $vgpr0, $vgpr1
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX6-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX6-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 17
    ; GFX6-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 17
    ; GFX6-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX6-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX6-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX6-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX6-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX6-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX6-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX6-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX6-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX6-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX6-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX6-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX6-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX6-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX6-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX6-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX6-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX6-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX6-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX6-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX6-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX6-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX6-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX6-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX6-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX6-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX6-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX6-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX6-NEXT: $vgpr0 = COPY [[SUB4]](s32)
    ;
    ; GFX8-LABEL: name: test_srem_s17
    ; GFX8: liveins: $vgpr0, $vgpr1
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX8-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX8-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 17
    ; GFX8-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 17
    ; GFX8-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX8-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX8-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX8-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX8-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX8-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX8-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX8-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX8-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX8-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX8-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX8-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX8-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX8-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX8-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX8-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX8-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX8-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX8-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX8-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX8-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX8-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX8-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX8-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX8-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX8-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX8-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX8-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX8-NEXT: $vgpr0 = COPY [[SUB4]](s32)
    ;
    ; GFX9-LABEL: name: test_srem_s17
    ; GFX9: liveins: $vgpr0, $vgpr1
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX9-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 17
    ; GFX9-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 17
    ; GFX9-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX9-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX9-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX9-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX9-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX9-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX9-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX9-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX9-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX9-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX9-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX9-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX9-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX9-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX9-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX9-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX9-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX9-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX9-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX9-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX9-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX9-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX9-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX9-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX9-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX9-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX9-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX9-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX9-NEXT: $vgpr0 = COPY [[SUB4]](s32)
    ;
    ; GFX10-LABEL: name: test_srem_s17
    ; GFX10: liveins: $vgpr0, $vgpr1
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $vgpr0
    ; GFX10-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX10-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY]], 17
    ; GFX10-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 17
    ; GFX10-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; GFX10-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX10-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX10-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG]], [[ASHR]]
    ; GFX10-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[SEXT_INREG1]], [[ASHR1]]
    ; GFX10-NEXT: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[ADD]], [[ASHR]]
    ; GFX10-NEXT: [[XOR1:%[0-9]+]]:_(s32) = G_XOR [[ADD1]], [[ASHR1]]
    ; GFX10-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[XOR1]](s32)
    ; GFX10-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(f32) = G_AMDGPU_RCP_IFLAG [[UITOFP]](f32)
    ; GFX10-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F7FFFFE
    ; GFX10-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C1]]
    ; GFX10-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FMUL]](f32)
    ; GFX10-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX10-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C2]], [[XOR1]]
    ; GFX10-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[SUB]], [[FPTOUI]]
    ; GFX10-NEXT: [[UMULH:%[0-9]+]]:_(s32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX10-NEXT: [[ADD2:%[0-9]+]]:_(s32) = G_ADD [[FPTOUI]], [[UMULH]]
    ; GFX10-NEXT: [[UMULH1:%[0-9]+]]:_(s32) = G_UMULH [[XOR]], [[ADD2]]
    ; GFX10-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[UMULH1]], [[XOR1]]
    ; GFX10-NEXT: [[SUB1:%[0-9]+]]:_(i32) = G_SUB [[XOR]], [[MUL1]]
    ; GFX10-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SUB1]](i32), [[XOR1]]
    ; GFX10-NEXT: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[XOR1]]
    ; GFX10-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP]](s1), [[SUB2]], [[SUB1]]
    ; GFX10-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[SELECT]](s32), [[XOR1]]
    ; GFX10-NEXT: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[SELECT]], [[XOR1]]
    ; GFX10-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](s1), [[SUB3]], [[SELECT]]
    ; GFX10-NEXT: [[XOR2:%[0-9]+]]:_(s32) = G_XOR [[SELECT1]], [[ASHR]]
    ; GFX10-NEXT: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[XOR2]], [[ASHR]]
    ; GFX10-NEXT: $vgpr0 = COPY [[SUB4]](s32)
    %0:_(s32) = COPY $vgpr0
    %1:_(s32) = COPY $vgpr1
    %2:_(s17) = G_TRUNC %0
    %3:_(s17) = G_TRUNC %1
    %4:_(s17) = G_SREM %2, %3
    %5:_(s32) = G_ANYEXT %4
    $vgpr0 = COPY %5
...

---
name: test_srem_s33
body: |
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2_vgpr3

    ; GFX6-LABEL: name: test_srem_s33
    ; GFX6: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3
    ; GFX6-NEXT: {{  $}}
    ; GFX6-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $vgpr0_vgpr1
    ; GFX6-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $vgpr2_vgpr3
    ; GFX6-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY]], 33
    ; GFX6-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY1]], 33
    ; GFX6-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; GFX6-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX6-NEXT: [[ASHR1:%[0-9]+]]:_(s64) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX6-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[SEXT_INREG]](s64)
    ; GFX6-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX6-NEXT: [[UADDO:%[0-9]+]]:_(s32), [[UADDO1:%[0-9]+]]:_(i1) = G_UADDO [[UV]], [[UV2]]
    ; GFX6-NEXT: [[UADDE:%[0-9]+]]:_(s32), [[UADDE1:%[0-9]+]]:_(i1) = G_UADDE [[UV1]], [[UV3]], [[UADDO1]]
    ; GFX6-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO]](s32), [[UADDE]](s32)
    ; GFX6-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[SEXT_INREG1]](s64)
    ; GFX6-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR1]](s64)
    ; GFX6-NEXT: [[UADDO2:%[0-9]+]]:_(s32), [[UADDO3:%[0-9]+]]:_(i1) = G_UADDO [[UV4]], [[UV6]]
    ; GFX6-NEXT: [[UADDE2:%[0-9]+]]:_(s32), [[UADDE3:%[0-9]+]]:_(i1) = G_UADDE [[UV5]], [[UV7]], [[UADDO3]]
    ; GFX6-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO2]](s32), [[UADDE2]](s32)
    ; GFX6-NEXT: [[XOR:%[0-9]+]]:_(s64) = G_XOR [[MV]], [[ASHR]]
    ; GFX6-NEXT: [[XOR1:%[0-9]+]]:_(s64) = G_XOR [[MV1]], [[ASHR1]]
    ; GFX6-NEXT: [[UV8:%[0-9]+]]:_(i32), [[UV9:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX6-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[UV8]](i32)
    ; GFX6-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[UV9]](i32)
    ; GFX6-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F800000
    ; GFX6-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP1]], [[C1]]
    ; GFX6-NEXT: [[FADD:%[0-9]+]]:_(f32) = G_FADD [[FMUL]], [[UITOFP]]
    ; GFX6-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD]](f32)
    ; GFX6-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x5F7FFFFC
    ; GFX6-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX6-NEXT: [[C3:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x2F800000
    ; GFX6-NEXT: [[FMUL2:%[0-9]+]]:_(f32) = G_FMUL [[FMUL1]], [[C3]]
    ; GFX6-NEXT: [[INTRINSIC_TRUNC:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL2]]
    ; GFX6-NEXT: [[C4:%[0-9]+]]:_(s32) = G_FCONSTANT float f0xCF800000
    ; GFX6-NEXT: [[FMUL3:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC]], [[C4]]
    ; GFX6-NEXT: [[FADD1:%[0-9]+]]:_(f32) = G_FADD [[FMUL3]], [[FMUL1]]
    ; GFX6-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD1]](f32)
    ; GFX6-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC]](f32)
    ; GFX6-NEXT: [[C5:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; GFX6-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX6-NEXT: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX6-NEXT: [[USUBO:%[0-9]+]]:_(s32), [[USUBO1:%[0-9]+]]:_(i1) = G_USUBO [[UV10]], [[UV12]]
    ; GFX6-NEXT: [[USUBE:%[0-9]+]]:_(s32), [[USUBE1:%[0-9]+]]:_(i1) = G_USUBE [[UV11]], [[UV13]], [[USUBO1]]
    ; GFX6-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[FPTOUI]]
    ; GFX6-NEXT: [[UMULH:%[0-9]+]]:_(i32) = G_UMULH [[USUBO]], [[FPTOUI]]
    ; GFX6-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[FPTOUI1]]
    ; GFX6-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[USUBE]], [[FPTOUI]]
    ; GFX6-NEXT: [[ADD:%[0-9]+]]:_(i32) = G_ADD [[UMULH]], [[MUL1]]
    ; GFX6-NEXT: [[ADD1:%[0-9]+]]:_(i32) = G_ADD [[ADD]], [[MUL2]]
    ; GFX6-NEXT: [[UMULH1:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[MUL]]
    ; GFX6-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI]], [[ADD1]]
    ; GFX6-NEXT: [[MUL4:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[MUL]]
    ; GFX6-NEXT: [[UADDO4:%[0-9]+]]:_(i32), [[UADDO5:%[0-9]+]]:_(i1) = G_UADDO [[UMULH1]], [[MUL3]]
    ; GFX6-NEXT: [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO5]](i1)
    ; GFX6-NEXT: [[UADDO6:%[0-9]+]]:_(i32), [[UADDO7:%[0-9]+]]:_(i1) = G_UADDO [[UADDO4]], [[MUL4]]
    ; GFX6-NEXT: [[ZEXT1:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO7]](i1)
    ; GFX6-NEXT: [[ADD2:%[0-9]+]]:_(i32) = G_ADD [[ZEXT]], [[ZEXT1]]
    ; GFX6-NEXT: [[UMULH2:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[MUL]]
    ; GFX6-NEXT: [[UMULH3:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[ADD1]]
    ; GFX6-NEXT: [[MUL5:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[ADD1]]
    ; GFX6-NEXT: [[UADDO8:%[0-9]+]]:_(i32), [[UADDO9:%[0-9]+]]:_(i1) = G_UADDO [[UMULH2]], [[UMULH3]]
    ; GFX6-NEXT: [[ZEXT2:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO9]](i1)
    ; GFX6-NEXT: [[UADDO10:%[0-9]+]]:_(i32), [[UADDO11:%[0-9]+]]:_(i1) = G_UADDO [[UADDO8]], [[MUL5]]
    ; GFX6-NEXT: [[ZEXT3:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO11]](i1)
    ; GFX6-NEXT: [[ADD3:%[0-9]+]]:_(i32) = G_ADD [[ZEXT2]], [[ZEXT3]]
    ; GFX6-NEXT: [[UADDO12:%[0-9]+]]:_(i32), [[UADDO13:%[0-9]+]]:_(i1) = G_UADDO [[UADDO10]], [[ADD2]]
    ; GFX6-NEXT: [[ZEXT4:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO13]](i1)
    ; GFX6-NEXT: [[ADD4:%[0-9]+]]:_(i32) = G_ADD [[ADD3]], [[ZEXT4]]
    ; GFX6-NEXT: [[UMULH4:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[ADD1]]
    ; GFX6-NEXT: [[ADD5:%[0-9]+]]:_(i32) = G_ADD [[UMULH4]], [[ADD4]]
    ; GFX6-NEXT: [[UADDO14:%[0-9]+]]:_(s32), [[UADDO15:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI]], [[UADDO12]]
    ; GFX6-NEXT: [[UADDE4:%[0-9]+]]:_(s32), [[UADDE5:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI1]], [[ADD5]], [[UADDO15]]
    ; GFX6-NEXT: [[MUL6:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[UADDO14]]
    ; GFX6-NEXT: [[UMULH5:%[0-9]+]]:_(i32) = G_UMULH [[USUBO]], [[UADDO14]]
    ; GFX6-NEXT: [[MUL7:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[UADDE4]]
    ; GFX6-NEXT: [[MUL8:%[0-9]+]]:_(i32) = G_MUL [[USUBE]], [[UADDO14]]
    ; GFX6-NEXT: [[ADD6:%[0-9]+]]:_(i32) = G_ADD [[UMULH5]], [[MUL7]]
    ; GFX6-NEXT: [[ADD7:%[0-9]+]]:_(i32) = G_ADD [[ADD6]], [[MUL8]]
    ; GFX6-NEXT: [[UMULH6:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[MUL6]]
    ; GFX6-NEXT: [[MUL9:%[0-9]+]]:_(i32) = G_MUL [[UADDO14]], [[ADD7]]
    ; GFX6-NEXT: [[MUL10:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[MUL6]]
    ; GFX6-NEXT: [[UADDO16:%[0-9]+]]:_(i32), [[UADDO17:%[0-9]+]]:_(i1) = G_UADDO [[UMULH6]], [[MUL9]]
    ; GFX6-NEXT: [[ZEXT5:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO17]](i1)
    ; GFX6-NEXT: [[UADDO18:%[0-9]+]]:_(i32), [[UADDO19:%[0-9]+]]:_(i1) = G_UADDO [[UADDO16]], [[MUL10]]
    ; GFX6-NEXT: [[ZEXT6:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO19]](i1)
    ; GFX6-NEXT: [[ADD8:%[0-9]+]]:_(i32) = G_ADD [[ZEXT5]], [[ZEXT6]]
    ; GFX6-NEXT: [[UMULH7:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[MUL6]]
    ; GFX6-NEXT: [[UMULH8:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[ADD7]]
    ; GFX6-NEXT: [[MUL11:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[ADD7]]
    ; GFX6-NEXT: [[UADDO20:%[0-9]+]]:_(i32), [[UADDO21:%[0-9]+]]:_(i1) = G_UADDO [[UMULH7]], [[UMULH8]]
    ; GFX6-NEXT: [[ZEXT7:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO21]](i1)
    ; GFX6-NEXT: [[UADDO22:%[0-9]+]]:_(i32), [[UADDO23:%[0-9]+]]:_(i1) = G_UADDO [[UADDO20]], [[MUL11]]
    ; GFX6-NEXT: [[ZEXT8:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO23]](i1)
    ; GFX6-NEXT: [[ADD9:%[0-9]+]]:_(i32) = G_ADD [[ZEXT7]], [[ZEXT8]]
    ; GFX6-NEXT: [[UADDO24:%[0-9]+]]:_(i32), [[UADDO25:%[0-9]+]]:_(i1) = G_UADDO [[UADDO22]], [[ADD8]]
    ; GFX6-NEXT: [[ZEXT9:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO25]](i1)
    ; GFX6-NEXT: [[ADD10:%[0-9]+]]:_(i32) = G_ADD [[ADD9]], [[ZEXT9]]
    ; GFX6-NEXT: [[UMULH9:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[ADD7]]
    ; GFX6-NEXT: [[ADD11:%[0-9]+]]:_(i32) = G_ADD [[UMULH9]], [[ADD10]]
    ; GFX6-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX6-NEXT: [[UADDO26:%[0-9]+]]:_(s32), [[UADDO27:%[0-9]+]]:_(s1) = G_UADDO [[UADDO14]], [[UADDO24]]
    ; GFX6-NEXT: [[UADDE6:%[0-9]+]]:_(s32), [[UADDE7:%[0-9]+]]:_(s1) = G_UADDE [[UADDE4]], [[ADD11]], [[UADDO27]]
    ; GFX6-NEXT: [[UV14:%[0-9]+]]:_(i32), [[UV15:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX6-NEXT: [[UV16:%[0-9]+]]:_(i32), [[UV17:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX6-NEXT: [[UMULH10:%[0-9]+]]:_(i32) = G_UMULH [[UV16]], [[UADDO26]]
    ; GFX6-NEXT: [[MUL12:%[0-9]+]]:_(i32) = G_MUL [[UV16]], [[UADDE6]]
    ; GFX6-NEXT: [[MUL13:%[0-9]+]]:_(i32) = G_MUL [[UV17]], [[UADDO26]]
    ; GFX6-NEXT: [[UADDO28:%[0-9]+]]:_(i32), [[UADDO29:%[0-9]+]]:_(i1) = G_UADDO [[UMULH10]], [[MUL12]]
    ; GFX6-NEXT: [[ZEXT10:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO29]](i1)
    ; GFX6-NEXT: [[UADDO30:%[0-9]+]]:_(i32), [[UADDO31:%[0-9]+]]:_(i1) = G_UADDO [[UADDO28]], [[MUL13]]
    ; GFX6-NEXT: [[ZEXT11:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO31]](i1)
    ; GFX6-NEXT: [[ADD12:%[0-9]+]]:_(i32) = G_ADD [[ZEXT10]], [[ZEXT11]]
    ; GFX6-NEXT: [[UMULH11:%[0-9]+]]:_(i32) = G_UMULH [[UV17]], [[UADDO26]]
    ; GFX6-NEXT: [[UMULH12:%[0-9]+]]:_(i32) = G_UMULH [[UV16]], [[UADDE6]]
    ; GFX6-NEXT: [[MUL14:%[0-9]+]]:_(i32) = G_MUL [[UV17]], [[UADDE6]]
    ; GFX6-NEXT: [[UADDO32:%[0-9]+]]:_(i32), [[UADDO33:%[0-9]+]]:_(i1) = G_UADDO [[UMULH11]], [[UMULH12]]
    ; GFX6-NEXT: [[ZEXT12:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO33]](i1)
    ; GFX6-NEXT: [[UADDO34:%[0-9]+]]:_(i32), [[UADDO35:%[0-9]+]]:_(i1) = G_UADDO [[UADDO32]], [[MUL14]]
    ; GFX6-NEXT: [[ZEXT13:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO35]](i1)
    ; GFX6-NEXT: [[ADD13:%[0-9]+]]:_(i32) = G_ADD [[ZEXT12]], [[ZEXT13]]
    ; GFX6-NEXT: [[UADDO36:%[0-9]+]]:_(i32), [[UADDO37:%[0-9]+]]:_(i1) = G_UADDO [[UADDO34]], [[ADD12]]
    ; GFX6-NEXT: [[ZEXT14:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO37]](i1)
    ; GFX6-NEXT: [[ADD14:%[0-9]+]]:_(i32) = G_ADD [[ADD13]], [[ZEXT14]]
    ; GFX6-NEXT: [[UMULH13:%[0-9]+]]:_(i32) = G_UMULH [[UV17]], [[UADDE6]]
    ; GFX6-NEXT: [[ADD15:%[0-9]+]]:_(i32) = G_ADD [[UMULH13]], [[ADD14]]
    ; GFX6-NEXT: [[UV18:%[0-9]+]]:_(i32), [[UV19:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX6-NEXT: [[MUL15:%[0-9]+]]:_(i32) = G_MUL [[UV18]], [[UADDO36]]
    ; GFX6-NEXT: [[UMULH14:%[0-9]+]]:_(i32) = G_UMULH [[UV18]], [[UADDO36]]
    ; GFX6-NEXT: [[MUL16:%[0-9]+]]:_(i32) = G_MUL [[UV18]], [[ADD15]]
    ; GFX6-NEXT: [[MUL17:%[0-9]+]]:_(i32) = G_MUL [[UV19]], [[UADDO36]]
    ; GFX6-NEXT: [[ADD16:%[0-9]+]]:_(i32) = G_ADD [[UMULH14]], [[MUL16]]
    ; GFX6-NEXT: [[ADD17:%[0-9]+]]:_(i32) = G_ADD [[ADD16]], [[MUL17]]
    ; GFX6-NEXT: [[USUBO2:%[0-9]+]]:_(s32), [[USUBO3:%[0-9]+]]:_(s1) = G_USUBO [[UV14]], [[MUL15]]
    ; GFX6-NEXT: [[USUBE2:%[0-9]+]]:_(s32), [[USUBE3:%[0-9]+]]:_(s1) = G_USUBE [[UV15]], [[ADD17]], [[USUBO3]]
    ; GFX6-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[UV15]], [[ADD17]]
    ; GFX6-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO2]](s32), [[USUBE2]](s32)
    ; GFX6-NEXT: [[UV20:%[0-9]+]]:_(i32), [[UV21:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX6-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE2]](s32), [[UV21]]
    ; GFX6-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[ICMP]](s1)
    ; GFX6-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO2]](s32), [[UV20]]
    ; GFX6-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[ICMP1]](s1)
    ; GFX6-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE2]](s32), [[UV21]]
    ; GFX6-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SEXT1]], [[SEXT]]
    ; GFX6-NEXT: [[USUBO4:%[0-9]+]]:_(s32), [[USUBO5:%[0-9]+]]:_(s1) = G_USUBO [[USUBO2]], [[UV20]]
    ; GFX6-NEXT: [[USUBE4:%[0-9]+]]:_(s32), [[USUBE5:%[0-9]+]]:_(s1) = G_USUBE [[SUB]], [[UV21]], [[USUBO3]]
    ; GFX6-NEXT: [[USUBE6:%[0-9]+]]:_(s32), [[USUBE7:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[C6]], [[USUBO5]]
    ; GFX6-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO4]](s32), [[USUBE6]](s32)
    ; GFX6-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE6]](s32), [[UV21]]
    ; GFX6-NEXT: [[SEXT2:%[0-9]+]]:_(s32) = G_SEXT [[ICMP3]](s1)
    ; GFX6-NEXT: [[ICMP4:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO4]](s32), [[UV20]]
    ; GFX6-NEXT: [[SEXT3:%[0-9]+]]:_(s32) = G_SEXT [[ICMP4]](s1)
    ; GFX6-NEXT: [[ICMP5:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE6]](s32), [[UV21]]
    ; GFX6-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP5]](s1), [[SEXT3]], [[SEXT2]]
    ; GFX6-NEXT: [[USUBO6:%[0-9]+]]:_(s32), [[USUBO7:%[0-9]+]]:_(s1) = G_USUBO [[USUBO4]], [[UV20]]
    ; GFX6-NEXT: [[USUBE8:%[0-9]+]]:_(s32), [[USUBE9:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[UV21]], [[USUBO5]]
    ; GFX6-NEXT: [[USUBE10:%[0-9]+]]:_(s32), [[USUBE11:%[0-9]+]]:_(s1) = G_USUBE [[USUBE8]], [[C6]], [[USUBO7]]
    ; GFX6-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO6]](s32), [[USUBE10]](s32)
    ; GFX6-NEXT: [[ICMP6:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT1]](s32), [[C6]]
    ; GFX6-NEXT: [[SELECT2:%[0-9]+]]:_(s64) = G_SELECT [[ICMP6]](s1), [[MV4]], [[MV3]]
    ; GFX6-NEXT: [[ICMP7:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT]](s32), [[C6]]
    ; GFX6-NEXT: [[SELECT3:%[0-9]+]]:_(s64) = G_SELECT [[ICMP7]](s1), [[SELECT2]], [[MV2]]
    ; GFX6-NEXT: [[XOR2:%[0-9]+]]:_(s64) = G_XOR [[SELECT3]], [[ASHR]]
    ; GFX6-NEXT: [[UV22:%[0-9]+]]:_(s32), [[UV23:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR2]](s64)
    ; GFX6-NEXT: [[UV24:%[0-9]+]]:_(s32), [[UV25:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX6-NEXT: [[USUBO8:%[0-9]+]]:_(s32), [[USUBO9:%[0-9]+]]:_(i1) = G_USUBO [[UV22]], [[UV24]]
    ; GFX6-NEXT: [[USUBE12:%[0-9]+]]:_(s32), [[USUBE13:%[0-9]+]]:_(i1) = G_USUBE [[UV23]], [[UV25]], [[USUBO9]]
    ; GFX6-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO8]](s32), [[USUBE12]](s32)
    ; GFX6-NEXT: $vgpr0_vgpr1 = COPY [[MV5]](s64)
    ;
    ; GFX8-LABEL: name: test_srem_s33
    ; GFX8: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3
    ; GFX8-NEXT: {{  $}}
    ; GFX8-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $vgpr0_vgpr1
    ; GFX8-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $vgpr2_vgpr3
    ; GFX8-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY]], 33
    ; GFX8-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY1]], 33
    ; GFX8-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; GFX8-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX8-NEXT: [[ASHR1:%[0-9]+]]:_(s64) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX8-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[SEXT_INREG]](s64)
    ; GFX8-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX8-NEXT: [[UADDO:%[0-9]+]]:_(s32), [[UADDO1:%[0-9]+]]:_(i1) = G_UADDO [[UV]], [[UV2]]
    ; GFX8-NEXT: [[UADDE:%[0-9]+]]:_(s32), [[UADDE1:%[0-9]+]]:_(i1) = G_UADDE [[UV1]], [[UV3]], [[UADDO1]]
    ; GFX8-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO]](s32), [[UADDE]](s32)
    ; GFX8-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[SEXT_INREG1]](s64)
    ; GFX8-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR1]](s64)
    ; GFX8-NEXT: [[UADDO2:%[0-9]+]]:_(s32), [[UADDO3:%[0-9]+]]:_(i1) = G_UADDO [[UV4]], [[UV6]]
    ; GFX8-NEXT: [[UADDE2:%[0-9]+]]:_(s32), [[UADDE3:%[0-9]+]]:_(i1) = G_UADDE [[UV5]], [[UV7]], [[UADDO3]]
    ; GFX8-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO2]](s32), [[UADDE2]](s32)
    ; GFX8-NEXT: [[XOR:%[0-9]+]]:_(s64) = G_XOR [[MV]], [[ASHR]]
    ; GFX8-NEXT: [[XOR1:%[0-9]+]]:_(s64) = G_XOR [[MV1]], [[ASHR1]]
    ; GFX8-NEXT: [[UV8:%[0-9]+]]:_(i32), [[UV9:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX8-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[UV8]](i32)
    ; GFX8-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[UV9]](i32)
    ; GFX8-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F800000
    ; GFX8-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP1]], [[C1]]
    ; GFX8-NEXT: [[FADD:%[0-9]+]]:_(f32) = G_FADD [[FMUL]], [[UITOFP]]
    ; GFX8-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD]](f32)
    ; GFX8-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x5F7FFFFC
    ; GFX8-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX8-NEXT: [[C3:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x2F800000
    ; GFX8-NEXT: [[FMUL2:%[0-9]+]]:_(f32) = G_FMUL [[FMUL1]], [[C3]]
    ; GFX8-NEXT: [[INTRINSIC_TRUNC:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL2]]
    ; GFX8-NEXT: [[C4:%[0-9]+]]:_(s32) = G_FCONSTANT float f0xCF800000
    ; GFX8-NEXT: [[FMUL3:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC]], [[C4]]
    ; GFX8-NEXT: [[FADD1:%[0-9]+]]:_(f32) = G_FADD [[FMUL3]], [[FMUL1]]
    ; GFX8-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD1]](f32)
    ; GFX8-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC]](f32)
    ; GFX8-NEXT: [[C5:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; GFX8-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX8-NEXT: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX8-NEXT: [[USUBO:%[0-9]+]]:_(s32), [[USUBO1:%[0-9]+]]:_(i1) = G_USUBO [[UV10]], [[UV12]]
    ; GFX8-NEXT: [[USUBE:%[0-9]+]]:_(s32), [[USUBE1:%[0-9]+]]:_(i1) = G_USUBE [[UV11]], [[UV13]], [[USUBO1]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_1:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[FPTOUI]], [[C5]]
    ; GFX8-NEXT: [[UV14:%[0-9]+]]:_(i32), [[UV15:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_]](s64)
    ; GFX8-NEXT: [[ANYEXT:%[0-9]+]]:_(s64) = G_ANYEXT [[UV15]](i32)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_2:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_3:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[FPTOUI1]], [[ANYEXT]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_4:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_5:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE]](s32), [[FPTOUI]], [[AMDGPU_MAD_U64_U32_2]]
    ; GFX8-NEXT: [[UV16:%[0-9]+]]:_(i32), [[UV17:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_4]](s64)
    ; GFX8-NEXT: [[UMULH:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[UV14]]
    ; GFX8-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI]], [[UV16]]
    ; GFX8-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[UV14]]
    ; GFX8-NEXT: [[UADDO4:%[0-9]+]]:_(i32), [[UADDO5:%[0-9]+]]:_(i1) = G_UADDO [[UMULH]], [[MUL]]
    ; GFX8-NEXT: [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO5]](i1)
    ; GFX8-NEXT: [[UADDO6:%[0-9]+]]:_(i32), [[UADDO7:%[0-9]+]]:_(i1) = G_UADDO [[UADDO4]], [[MUL1]]
    ; GFX8-NEXT: [[ZEXT1:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO7]](i1)
    ; GFX8-NEXT: [[ADD:%[0-9]+]]:_(i32) = G_ADD [[ZEXT]], [[ZEXT1]]
    ; GFX8-NEXT: [[UMULH1:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[UV14]]
    ; GFX8-NEXT: [[UMULH2:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[UV16]]
    ; GFX8-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[UV16]]
    ; GFX8-NEXT: [[UADDO8:%[0-9]+]]:_(i32), [[UADDO9:%[0-9]+]]:_(i1) = G_UADDO [[UMULH1]], [[UMULH2]]
    ; GFX8-NEXT: [[ZEXT2:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO9]](i1)
    ; GFX8-NEXT: [[UADDO10:%[0-9]+]]:_(i32), [[UADDO11:%[0-9]+]]:_(i1) = G_UADDO [[UADDO8]], [[MUL2]]
    ; GFX8-NEXT: [[ZEXT3:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO11]](i1)
    ; GFX8-NEXT: [[ADD1:%[0-9]+]]:_(i32) = G_ADD [[ZEXT2]], [[ZEXT3]]
    ; GFX8-NEXT: [[UADDO12:%[0-9]+]]:_(i32), [[UADDO13:%[0-9]+]]:_(i1) = G_UADDO [[UADDO10]], [[ADD]]
    ; GFX8-NEXT: [[ZEXT4:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO13]](i1)
    ; GFX8-NEXT: [[ADD2:%[0-9]+]]:_(i32) = G_ADD [[ADD1]], [[ZEXT4]]
    ; GFX8-NEXT: [[UMULH3:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[UV16]]
    ; GFX8-NEXT: [[ADD3:%[0-9]+]]:_(i32) = G_ADD [[UMULH3]], [[ADD2]]
    ; GFX8-NEXT: [[UADDO14:%[0-9]+]]:_(s32), [[UADDO15:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI]], [[UADDO12]]
    ; GFX8-NEXT: [[UADDE4:%[0-9]+]]:_(s32), [[UADDE5:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI1]], [[ADD3]], [[UADDO15]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_6:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_7:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[UADDO14]], [[C5]]
    ; GFX8-NEXT: [[UV18:%[0-9]+]]:_(i32), [[UV19:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_6]](s64)
    ; GFX8-NEXT: [[ANYEXT1:%[0-9]+]]:_(s64) = G_ANYEXT [[UV19]](i32)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_8:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_9:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[UADDE4]], [[ANYEXT1]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_10:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_11:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE]](s32), [[UADDO14]], [[AMDGPU_MAD_U64_U32_8]]
    ; GFX8-NEXT: [[UV20:%[0-9]+]]:_(i32), [[UV21:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_10]](s64)
    ; GFX8-NEXT: [[UMULH4:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[UV18]]
    ; GFX8-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[UADDO14]], [[UV20]]
    ; GFX8-NEXT: [[MUL4:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[UV18]]
    ; GFX8-NEXT: [[UADDO16:%[0-9]+]]:_(i32), [[UADDO17:%[0-9]+]]:_(i1) = G_UADDO [[UMULH4]], [[MUL3]]
    ; GFX8-NEXT: [[ZEXT5:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO17]](i1)
    ; GFX8-NEXT: [[UADDO18:%[0-9]+]]:_(i32), [[UADDO19:%[0-9]+]]:_(i1) = G_UADDO [[UADDO16]], [[MUL4]]
    ; GFX8-NEXT: [[ZEXT6:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO19]](i1)
    ; GFX8-NEXT: [[ADD4:%[0-9]+]]:_(i32) = G_ADD [[ZEXT5]], [[ZEXT6]]
    ; GFX8-NEXT: [[UMULH5:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[UV18]]
    ; GFX8-NEXT: [[UMULH6:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[UV20]]
    ; GFX8-NEXT: [[MUL5:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[UV20]]
    ; GFX8-NEXT: [[UADDO20:%[0-9]+]]:_(i32), [[UADDO21:%[0-9]+]]:_(i1) = G_UADDO [[UMULH5]], [[UMULH6]]
    ; GFX8-NEXT: [[ZEXT7:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO21]](i1)
    ; GFX8-NEXT: [[UADDO22:%[0-9]+]]:_(i32), [[UADDO23:%[0-9]+]]:_(i1) = G_UADDO [[UADDO20]], [[MUL5]]
    ; GFX8-NEXT: [[ZEXT8:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO23]](i1)
    ; GFX8-NEXT: [[ADD5:%[0-9]+]]:_(i32) = G_ADD [[ZEXT7]], [[ZEXT8]]
    ; GFX8-NEXT: [[UADDO24:%[0-9]+]]:_(i32), [[UADDO25:%[0-9]+]]:_(i1) = G_UADDO [[UADDO22]], [[ADD4]]
    ; GFX8-NEXT: [[ZEXT9:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO25]](i1)
    ; GFX8-NEXT: [[ADD6:%[0-9]+]]:_(i32) = G_ADD [[ADD5]], [[ZEXT9]]
    ; GFX8-NEXT: [[UMULH7:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[UV20]]
    ; GFX8-NEXT: [[ADD7:%[0-9]+]]:_(i32) = G_ADD [[UMULH7]], [[ADD6]]
    ; GFX8-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX8-NEXT: [[UADDO26:%[0-9]+]]:_(s32), [[UADDO27:%[0-9]+]]:_(s1) = G_UADDO [[UADDO14]], [[UADDO24]]
    ; GFX8-NEXT: [[UADDE6:%[0-9]+]]:_(s32), [[UADDE7:%[0-9]+]]:_(s1) = G_UADDE [[UADDE4]], [[ADD7]], [[UADDO27]]
    ; GFX8-NEXT: [[UV22:%[0-9]+]]:_(i32), [[UV23:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX8-NEXT: [[UV24:%[0-9]+]]:_(i32), [[UV25:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX8-NEXT: [[UMULH8:%[0-9]+]]:_(i32) = G_UMULH [[UV24]], [[UADDO26]]
    ; GFX8-NEXT: [[MUL6:%[0-9]+]]:_(i32) = G_MUL [[UV24]], [[UADDE6]]
    ; GFX8-NEXT: [[MUL7:%[0-9]+]]:_(i32) = G_MUL [[UV25]], [[UADDO26]]
    ; GFX8-NEXT: [[UADDO28:%[0-9]+]]:_(i32), [[UADDO29:%[0-9]+]]:_(i1) = G_UADDO [[UMULH8]], [[MUL6]]
    ; GFX8-NEXT: [[ZEXT10:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO29]](i1)
    ; GFX8-NEXT: [[UADDO30:%[0-9]+]]:_(i32), [[UADDO31:%[0-9]+]]:_(i1) = G_UADDO [[UADDO28]], [[MUL7]]
    ; GFX8-NEXT: [[ZEXT11:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO31]](i1)
    ; GFX8-NEXT: [[ADD8:%[0-9]+]]:_(i32) = G_ADD [[ZEXT10]], [[ZEXT11]]
    ; GFX8-NEXT: [[UMULH9:%[0-9]+]]:_(i32) = G_UMULH [[UV25]], [[UADDO26]]
    ; GFX8-NEXT: [[UMULH10:%[0-9]+]]:_(i32) = G_UMULH [[UV24]], [[UADDE6]]
    ; GFX8-NEXT: [[MUL8:%[0-9]+]]:_(i32) = G_MUL [[UV25]], [[UADDE6]]
    ; GFX8-NEXT: [[UADDO32:%[0-9]+]]:_(i32), [[UADDO33:%[0-9]+]]:_(i1) = G_UADDO [[UMULH9]], [[UMULH10]]
    ; GFX8-NEXT: [[ZEXT12:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO33]](i1)
    ; GFX8-NEXT: [[UADDO34:%[0-9]+]]:_(i32), [[UADDO35:%[0-9]+]]:_(i1) = G_UADDO [[UADDO32]], [[MUL8]]
    ; GFX8-NEXT: [[ZEXT13:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO35]](i1)
    ; GFX8-NEXT: [[ADD9:%[0-9]+]]:_(i32) = G_ADD [[ZEXT12]], [[ZEXT13]]
    ; GFX8-NEXT: [[UADDO36:%[0-9]+]]:_(i32), [[UADDO37:%[0-9]+]]:_(i1) = G_UADDO [[UADDO34]], [[ADD8]]
    ; GFX8-NEXT: [[ZEXT14:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO37]](i1)
    ; GFX8-NEXT: [[ADD10:%[0-9]+]]:_(i32) = G_ADD [[ADD9]], [[ZEXT14]]
    ; GFX8-NEXT: [[UMULH11:%[0-9]+]]:_(i32) = G_UMULH [[UV25]], [[UADDE6]]
    ; GFX8-NEXT: [[ADD11:%[0-9]+]]:_(i32) = G_ADD [[UMULH11]], [[ADD10]]
    ; GFX8-NEXT: [[UV26:%[0-9]+]]:_(i32), [[UV27:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_12:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_13:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV26]](i32), [[UADDO36]], [[C5]]
    ; GFX8-NEXT: [[UV28:%[0-9]+]]:_(i32), [[UV29:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_12]](s64)
    ; GFX8-NEXT: [[ANYEXT2:%[0-9]+]]:_(s64) = G_ANYEXT [[UV29]](i32)
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_14:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_15:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV26]](i32), [[ADD11]], [[ANYEXT2]]
    ; GFX8-NEXT: [[AMDGPU_MAD_U64_U32_16:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_17:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV27]](i32), [[UADDO36]], [[AMDGPU_MAD_U64_U32_14]]
    ; GFX8-NEXT: [[UV30:%[0-9]+]]:_(i32), [[UV31:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_16]](s64)
    ; GFX8-NEXT: [[USUBO2:%[0-9]+]]:_(s32), [[USUBO3:%[0-9]+]]:_(s1) = G_USUBO [[UV22]], [[UV28]]
    ; GFX8-NEXT: [[USUBE2:%[0-9]+]]:_(s32), [[USUBE3:%[0-9]+]]:_(s1) = G_USUBE [[UV23]], [[UV30]], [[USUBO3]]
    ; GFX8-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[UV23]], [[UV30]]
    ; GFX8-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO2]](s32), [[USUBE2]](s32)
    ; GFX8-NEXT: [[UV32:%[0-9]+]]:_(i32), [[UV33:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX8-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE2]](s32), [[UV33]]
    ; GFX8-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[ICMP]](s1)
    ; GFX8-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO2]](s32), [[UV32]]
    ; GFX8-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[ICMP1]](s1)
    ; GFX8-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE2]](s32), [[UV33]]
    ; GFX8-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SEXT1]], [[SEXT]]
    ; GFX8-NEXT: [[USUBO4:%[0-9]+]]:_(s32), [[USUBO5:%[0-9]+]]:_(s1) = G_USUBO [[USUBO2]], [[UV32]]
    ; GFX8-NEXT: [[USUBE4:%[0-9]+]]:_(s32), [[USUBE5:%[0-9]+]]:_(s1) = G_USUBE [[SUB]], [[UV33]], [[USUBO3]]
    ; GFX8-NEXT: [[USUBE6:%[0-9]+]]:_(s32), [[USUBE7:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[C6]], [[USUBO5]]
    ; GFX8-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO4]](s32), [[USUBE6]](s32)
    ; GFX8-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE6]](s32), [[UV33]]
    ; GFX8-NEXT: [[SEXT2:%[0-9]+]]:_(s32) = G_SEXT [[ICMP3]](s1)
    ; GFX8-NEXT: [[ICMP4:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO4]](s32), [[UV32]]
    ; GFX8-NEXT: [[SEXT3:%[0-9]+]]:_(s32) = G_SEXT [[ICMP4]](s1)
    ; GFX8-NEXT: [[ICMP5:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE6]](s32), [[UV33]]
    ; GFX8-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP5]](s1), [[SEXT3]], [[SEXT2]]
    ; GFX8-NEXT: [[USUBO6:%[0-9]+]]:_(s32), [[USUBO7:%[0-9]+]]:_(s1) = G_USUBO [[USUBO4]], [[UV32]]
    ; GFX8-NEXT: [[USUBE8:%[0-9]+]]:_(s32), [[USUBE9:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[UV33]], [[USUBO5]]
    ; GFX8-NEXT: [[USUBE10:%[0-9]+]]:_(s32), [[USUBE11:%[0-9]+]]:_(s1) = G_USUBE [[USUBE8]], [[C6]], [[USUBO7]]
    ; GFX8-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO6]](s32), [[USUBE10]](s32)
    ; GFX8-NEXT: [[ICMP6:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT1]](s32), [[C6]]
    ; GFX8-NEXT: [[SELECT2:%[0-9]+]]:_(s64) = G_SELECT [[ICMP6]](s1), [[MV4]], [[MV3]]
    ; GFX8-NEXT: [[ICMP7:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT]](s32), [[C6]]
    ; GFX8-NEXT: [[SELECT3:%[0-9]+]]:_(s64) = G_SELECT [[ICMP7]](s1), [[SELECT2]], [[MV2]]
    ; GFX8-NEXT: [[XOR2:%[0-9]+]]:_(s64) = G_XOR [[SELECT3]], [[ASHR]]
    ; GFX8-NEXT: [[UV34:%[0-9]+]]:_(s32), [[UV35:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR2]](s64)
    ; GFX8-NEXT: [[UV36:%[0-9]+]]:_(s32), [[UV37:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX8-NEXT: [[USUBO8:%[0-9]+]]:_(s32), [[USUBO9:%[0-9]+]]:_(i1) = G_USUBO [[UV34]], [[UV36]]
    ; GFX8-NEXT: [[USUBE12:%[0-9]+]]:_(s32), [[USUBE13:%[0-9]+]]:_(i1) = G_USUBE [[UV35]], [[UV37]], [[USUBO9]]
    ; GFX8-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO8]](s32), [[USUBE12]](s32)
    ; GFX8-NEXT: $vgpr0_vgpr1 = COPY [[MV5]](s64)
    ;
    ; GFX9-LABEL: name: test_srem_s33
    ; GFX9: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $vgpr0_vgpr1
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $vgpr2_vgpr3
    ; GFX9-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY]], 33
    ; GFX9-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY1]], 33
    ; GFX9-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; GFX9-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX9-NEXT: [[ASHR1:%[0-9]+]]:_(s64) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX9-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[SEXT_INREG]](s64)
    ; GFX9-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX9-NEXT: [[UADDO:%[0-9]+]]:_(s32), [[UADDO1:%[0-9]+]]:_(i1) = G_UADDO [[UV]], [[UV2]]
    ; GFX9-NEXT: [[UADDE:%[0-9]+]]:_(s32), [[UADDE1:%[0-9]+]]:_(i1) = G_UADDE [[UV1]], [[UV3]], [[UADDO1]]
    ; GFX9-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO]](s32), [[UADDE]](s32)
    ; GFX9-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[SEXT_INREG1]](s64)
    ; GFX9-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR1]](s64)
    ; GFX9-NEXT: [[UADDO2:%[0-9]+]]:_(s32), [[UADDO3:%[0-9]+]]:_(i1) = G_UADDO [[UV4]], [[UV6]]
    ; GFX9-NEXT: [[UADDE2:%[0-9]+]]:_(s32), [[UADDE3:%[0-9]+]]:_(i1) = G_UADDE [[UV5]], [[UV7]], [[UADDO3]]
    ; GFX9-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO2]](s32), [[UADDE2]](s32)
    ; GFX9-NEXT: [[XOR:%[0-9]+]]:_(s64) = G_XOR [[MV]], [[ASHR]]
    ; GFX9-NEXT: [[XOR1:%[0-9]+]]:_(s64) = G_XOR [[MV1]], [[ASHR1]]
    ; GFX9-NEXT: [[UV8:%[0-9]+]]:_(i32), [[UV9:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX9-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[UV8]](i32)
    ; GFX9-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[UV9]](i32)
    ; GFX9-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F800000
    ; GFX9-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP1]], [[C1]]
    ; GFX9-NEXT: [[FADD:%[0-9]+]]:_(f32) = G_FADD [[FMUL]], [[UITOFP]]
    ; GFX9-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD]](f32)
    ; GFX9-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x5F7FFFFC
    ; GFX9-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX9-NEXT: [[C3:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x2F800000
    ; GFX9-NEXT: [[FMUL2:%[0-9]+]]:_(f32) = G_FMUL [[FMUL1]], [[C3]]
    ; GFX9-NEXT: [[INTRINSIC_TRUNC:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL2]]
    ; GFX9-NEXT: [[C4:%[0-9]+]]:_(s32) = G_FCONSTANT float f0xCF800000
    ; GFX9-NEXT: [[FMUL3:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC]], [[C4]]
    ; GFX9-NEXT: [[FADD1:%[0-9]+]]:_(f32) = G_FADD [[FMUL3]], [[FMUL1]]
    ; GFX9-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD1]](f32)
    ; GFX9-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC]](f32)
    ; GFX9-NEXT: [[C5:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; GFX9-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX9-NEXT: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX9-NEXT: [[USUBO:%[0-9]+]]:_(s32), [[USUBO1:%[0-9]+]]:_(i1) = G_USUBO [[UV10]], [[UV12]]
    ; GFX9-NEXT: [[USUBE:%[0-9]+]]:_(s32), [[USUBE1:%[0-9]+]]:_(i1) = G_USUBE [[UV11]], [[UV13]], [[USUBO1]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_1:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[FPTOUI]], [[C5]]
    ; GFX9-NEXT: [[UV14:%[0-9]+]]:_(i32), [[UV15:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_]](s64)
    ; GFX9-NEXT: [[ANYEXT:%[0-9]+]]:_(s64) = G_ANYEXT [[UV15]](i32)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_2:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_3:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[FPTOUI1]], [[ANYEXT]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_4:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_5:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE]](s32), [[FPTOUI]], [[AMDGPU_MAD_U64_U32_2]]
    ; GFX9-NEXT: [[UV16:%[0-9]+]]:_(i32), [[UV17:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_4]](s64)
    ; GFX9-NEXT: [[UMULH:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[UV14]]
    ; GFX9-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI]], [[UV16]]
    ; GFX9-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[UV14]]
    ; GFX9-NEXT: [[UADDO4:%[0-9]+]]:_(i32), [[UADDO5:%[0-9]+]]:_(i1) = G_UADDO [[UMULH]], [[MUL]]
    ; GFX9-NEXT: [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO5]](i1)
    ; GFX9-NEXT: [[UADDO6:%[0-9]+]]:_(i32), [[UADDO7:%[0-9]+]]:_(i1) = G_UADDO [[UADDO4]], [[MUL1]]
    ; GFX9-NEXT: [[ZEXT1:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO7]](i1)
    ; GFX9-NEXT: [[ADD:%[0-9]+]]:_(i32) = G_ADD [[ZEXT]], [[ZEXT1]]
    ; GFX9-NEXT: [[UMULH1:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[UV14]]
    ; GFX9-NEXT: [[UMULH2:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[UV16]]
    ; GFX9-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[UV16]]
    ; GFX9-NEXT: [[UADDO8:%[0-9]+]]:_(i32), [[UADDO9:%[0-9]+]]:_(i1) = G_UADDO [[UMULH1]], [[UMULH2]]
    ; GFX9-NEXT: [[ZEXT2:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO9]](i1)
    ; GFX9-NEXT: [[UADDO10:%[0-9]+]]:_(i32), [[UADDO11:%[0-9]+]]:_(i1) = G_UADDO [[UADDO8]], [[MUL2]]
    ; GFX9-NEXT: [[ZEXT3:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO11]](i1)
    ; GFX9-NEXT: [[ADD1:%[0-9]+]]:_(i32) = G_ADD [[ZEXT2]], [[ZEXT3]]
    ; GFX9-NEXT: [[UADDO12:%[0-9]+]]:_(i32), [[UADDO13:%[0-9]+]]:_(i1) = G_UADDO [[UADDO10]], [[ADD]]
    ; GFX9-NEXT: [[ZEXT4:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO13]](i1)
    ; GFX9-NEXT: [[ADD2:%[0-9]+]]:_(i32) = G_ADD [[ADD1]], [[ZEXT4]]
    ; GFX9-NEXT: [[UMULH3:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[UV16]]
    ; GFX9-NEXT: [[ADD3:%[0-9]+]]:_(i32) = G_ADD [[UMULH3]], [[ADD2]]
    ; GFX9-NEXT: [[UADDO14:%[0-9]+]]:_(s32), [[UADDO15:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI]], [[UADDO12]]
    ; GFX9-NEXT: [[UADDE4:%[0-9]+]]:_(s32), [[UADDE5:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI1]], [[ADD3]], [[UADDO15]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_6:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_7:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[UADDO14]], [[C5]]
    ; GFX9-NEXT: [[UV18:%[0-9]+]]:_(i32), [[UV19:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_6]](s64)
    ; GFX9-NEXT: [[ANYEXT1:%[0-9]+]]:_(s64) = G_ANYEXT [[UV19]](i32)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_8:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_9:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[UADDE4]], [[ANYEXT1]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_10:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_11:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBE]](s32), [[UADDO14]], [[AMDGPU_MAD_U64_U32_8]]
    ; GFX9-NEXT: [[UV20:%[0-9]+]]:_(i32), [[UV21:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_10]](s64)
    ; GFX9-NEXT: [[UMULH4:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[UV18]]
    ; GFX9-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[UADDO14]], [[UV20]]
    ; GFX9-NEXT: [[MUL4:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[UV18]]
    ; GFX9-NEXT: [[UADDO16:%[0-9]+]]:_(i32), [[UADDO17:%[0-9]+]]:_(i1) = G_UADDO [[UMULH4]], [[MUL3]]
    ; GFX9-NEXT: [[ZEXT5:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO17]](i1)
    ; GFX9-NEXT: [[UADDO18:%[0-9]+]]:_(i32), [[UADDO19:%[0-9]+]]:_(i1) = G_UADDO [[UADDO16]], [[MUL4]]
    ; GFX9-NEXT: [[ZEXT6:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO19]](i1)
    ; GFX9-NEXT: [[ADD4:%[0-9]+]]:_(i32) = G_ADD [[ZEXT5]], [[ZEXT6]]
    ; GFX9-NEXT: [[UMULH5:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[UV18]]
    ; GFX9-NEXT: [[UMULH6:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[UV20]]
    ; GFX9-NEXT: [[MUL5:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[UV20]]
    ; GFX9-NEXT: [[UADDO20:%[0-9]+]]:_(i32), [[UADDO21:%[0-9]+]]:_(i1) = G_UADDO [[UMULH5]], [[UMULH6]]
    ; GFX9-NEXT: [[ZEXT7:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO21]](i1)
    ; GFX9-NEXT: [[UADDO22:%[0-9]+]]:_(i32), [[UADDO23:%[0-9]+]]:_(i1) = G_UADDO [[UADDO20]], [[MUL5]]
    ; GFX9-NEXT: [[ZEXT8:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO23]](i1)
    ; GFX9-NEXT: [[ADD5:%[0-9]+]]:_(i32) = G_ADD [[ZEXT7]], [[ZEXT8]]
    ; GFX9-NEXT: [[UADDO24:%[0-9]+]]:_(i32), [[UADDO25:%[0-9]+]]:_(i1) = G_UADDO [[UADDO22]], [[ADD4]]
    ; GFX9-NEXT: [[ZEXT9:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO25]](i1)
    ; GFX9-NEXT: [[ADD6:%[0-9]+]]:_(i32) = G_ADD [[ADD5]], [[ZEXT9]]
    ; GFX9-NEXT: [[UMULH7:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[UV20]]
    ; GFX9-NEXT: [[ADD7:%[0-9]+]]:_(i32) = G_ADD [[UMULH7]], [[ADD6]]
    ; GFX9-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX9-NEXT: [[UADDO26:%[0-9]+]]:_(s32), [[UADDO27:%[0-9]+]]:_(s1) = G_UADDO [[UADDO14]], [[UADDO24]]
    ; GFX9-NEXT: [[UADDE6:%[0-9]+]]:_(s32), [[UADDE7:%[0-9]+]]:_(s1) = G_UADDE [[UADDE4]], [[ADD7]], [[UADDO27]]
    ; GFX9-NEXT: [[UV22:%[0-9]+]]:_(i32), [[UV23:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX9-NEXT: [[UV24:%[0-9]+]]:_(i32), [[UV25:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX9-NEXT: [[UMULH8:%[0-9]+]]:_(i32) = G_UMULH [[UV24]], [[UADDO26]]
    ; GFX9-NEXT: [[MUL6:%[0-9]+]]:_(i32) = G_MUL [[UV24]], [[UADDE6]]
    ; GFX9-NEXT: [[MUL7:%[0-9]+]]:_(i32) = G_MUL [[UV25]], [[UADDO26]]
    ; GFX9-NEXT: [[UADDO28:%[0-9]+]]:_(i32), [[UADDO29:%[0-9]+]]:_(i1) = G_UADDO [[UMULH8]], [[MUL6]]
    ; GFX9-NEXT: [[ZEXT10:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO29]](i1)
    ; GFX9-NEXT: [[UADDO30:%[0-9]+]]:_(i32), [[UADDO31:%[0-9]+]]:_(i1) = G_UADDO [[UADDO28]], [[MUL7]]
    ; GFX9-NEXT: [[ZEXT11:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO31]](i1)
    ; GFX9-NEXT: [[ADD8:%[0-9]+]]:_(i32) = G_ADD [[ZEXT10]], [[ZEXT11]]
    ; GFX9-NEXT: [[UMULH9:%[0-9]+]]:_(i32) = G_UMULH [[UV25]], [[UADDO26]]
    ; GFX9-NEXT: [[UMULH10:%[0-9]+]]:_(i32) = G_UMULH [[UV24]], [[UADDE6]]
    ; GFX9-NEXT: [[MUL8:%[0-9]+]]:_(i32) = G_MUL [[UV25]], [[UADDE6]]
    ; GFX9-NEXT: [[UADDO32:%[0-9]+]]:_(i32), [[UADDO33:%[0-9]+]]:_(i1) = G_UADDO [[UMULH9]], [[UMULH10]]
    ; GFX9-NEXT: [[ZEXT12:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO33]](i1)
    ; GFX9-NEXT: [[UADDO34:%[0-9]+]]:_(i32), [[UADDO35:%[0-9]+]]:_(i1) = G_UADDO [[UADDO32]], [[MUL8]]
    ; GFX9-NEXT: [[ZEXT13:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO35]](i1)
    ; GFX9-NEXT: [[ADD9:%[0-9]+]]:_(i32) = G_ADD [[ZEXT12]], [[ZEXT13]]
    ; GFX9-NEXT: [[UADDO36:%[0-9]+]]:_(i32), [[UADDO37:%[0-9]+]]:_(i1) = G_UADDO [[UADDO34]], [[ADD8]]
    ; GFX9-NEXT: [[ZEXT14:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO37]](i1)
    ; GFX9-NEXT: [[ADD10:%[0-9]+]]:_(i32) = G_ADD [[ADD9]], [[ZEXT14]]
    ; GFX9-NEXT: [[UMULH11:%[0-9]+]]:_(i32) = G_UMULH [[UV25]], [[UADDE6]]
    ; GFX9-NEXT: [[ADD11:%[0-9]+]]:_(i32) = G_ADD [[UMULH11]], [[ADD10]]
    ; GFX9-NEXT: [[UV26:%[0-9]+]]:_(i32), [[UV27:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_12:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_13:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV26]](i32), [[UADDO36]], [[C5]]
    ; GFX9-NEXT: [[UV28:%[0-9]+]]:_(i32), [[UV29:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_12]](s64)
    ; GFX9-NEXT: [[ANYEXT2:%[0-9]+]]:_(s64) = G_ANYEXT [[UV29]](i32)
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_14:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_15:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV26]](i32), [[ADD11]], [[ANYEXT2]]
    ; GFX9-NEXT: [[AMDGPU_MAD_U64_U32_16:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_17:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV27]](i32), [[UADDO36]], [[AMDGPU_MAD_U64_U32_14]]
    ; GFX9-NEXT: [[UV30:%[0-9]+]]:_(i32), [[UV31:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_16]](s64)
    ; GFX9-NEXT: [[USUBO2:%[0-9]+]]:_(s32), [[USUBO3:%[0-9]+]]:_(s1) = G_USUBO [[UV22]], [[UV28]]
    ; GFX9-NEXT: [[USUBE2:%[0-9]+]]:_(s32), [[USUBE3:%[0-9]+]]:_(s1) = G_USUBE [[UV23]], [[UV30]], [[USUBO3]]
    ; GFX9-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[UV23]], [[UV30]]
    ; GFX9-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO2]](s32), [[USUBE2]](s32)
    ; GFX9-NEXT: [[UV32:%[0-9]+]]:_(i32), [[UV33:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX9-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE2]](s32), [[UV33]]
    ; GFX9-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[ICMP]](s1)
    ; GFX9-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO2]](s32), [[UV32]]
    ; GFX9-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[ICMP1]](s1)
    ; GFX9-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE2]](s32), [[UV33]]
    ; GFX9-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SEXT1]], [[SEXT]]
    ; GFX9-NEXT: [[USUBO4:%[0-9]+]]:_(s32), [[USUBO5:%[0-9]+]]:_(s1) = G_USUBO [[USUBO2]], [[UV32]]
    ; GFX9-NEXT: [[USUBE4:%[0-9]+]]:_(s32), [[USUBE5:%[0-9]+]]:_(s1) = G_USUBE [[SUB]], [[UV33]], [[USUBO3]]
    ; GFX9-NEXT: [[USUBE6:%[0-9]+]]:_(s32), [[USUBE7:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[C6]], [[USUBO5]]
    ; GFX9-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO4]](s32), [[USUBE6]](s32)
    ; GFX9-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE6]](s32), [[UV33]]
    ; GFX9-NEXT: [[SEXT2:%[0-9]+]]:_(s32) = G_SEXT [[ICMP3]](s1)
    ; GFX9-NEXT: [[ICMP4:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO4]](s32), [[UV32]]
    ; GFX9-NEXT: [[SEXT3:%[0-9]+]]:_(s32) = G_SEXT [[ICMP4]](s1)
    ; GFX9-NEXT: [[ICMP5:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE6]](s32), [[UV33]]
    ; GFX9-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP5]](s1), [[SEXT3]], [[SEXT2]]
    ; GFX9-NEXT: [[USUBO6:%[0-9]+]]:_(s32), [[USUBO7:%[0-9]+]]:_(s1) = G_USUBO [[USUBO4]], [[UV32]]
    ; GFX9-NEXT: [[USUBE8:%[0-9]+]]:_(s32), [[USUBE9:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[UV33]], [[USUBO5]]
    ; GFX9-NEXT: [[USUBE10:%[0-9]+]]:_(s32), [[USUBE11:%[0-9]+]]:_(s1) = G_USUBE [[USUBE8]], [[C6]], [[USUBO7]]
    ; GFX9-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO6]](s32), [[USUBE10]](s32)
    ; GFX9-NEXT: [[ICMP6:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT1]](s32), [[C6]]
    ; GFX9-NEXT: [[SELECT2:%[0-9]+]]:_(s64) = G_SELECT [[ICMP6]](s1), [[MV4]], [[MV3]]
    ; GFX9-NEXT: [[ICMP7:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT]](s32), [[C6]]
    ; GFX9-NEXT: [[SELECT3:%[0-9]+]]:_(s64) = G_SELECT [[ICMP7]](s1), [[SELECT2]], [[MV2]]
    ; GFX9-NEXT: [[XOR2:%[0-9]+]]:_(s64) = G_XOR [[SELECT3]], [[ASHR]]
    ; GFX9-NEXT: [[UV34:%[0-9]+]]:_(s32), [[UV35:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR2]](s64)
    ; GFX9-NEXT: [[UV36:%[0-9]+]]:_(s32), [[UV37:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX9-NEXT: [[USUBO8:%[0-9]+]]:_(s32), [[USUBO9:%[0-9]+]]:_(i1) = G_USUBO [[UV34]], [[UV36]]
    ; GFX9-NEXT: [[USUBE12:%[0-9]+]]:_(s32), [[USUBE13:%[0-9]+]]:_(i1) = G_USUBE [[UV35]], [[UV37]], [[USUBO9]]
    ; GFX9-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO8]](s32), [[USUBE12]](s32)
    ; GFX9-NEXT: $vgpr0_vgpr1 = COPY [[MV5]](s64)
    ;
    ; GFX10-LABEL: name: test_srem_s33
    ; GFX10: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3
    ; GFX10-NEXT: {{  $}}
    ; GFX10-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $vgpr0_vgpr1
    ; GFX10-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $vgpr2_vgpr3
    ; GFX10-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY]], 33
    ; GFX10-NEXT: [[SEXT_INREG1:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY1]], 33
    ; GFX10-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 63
    ; GFX10-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; GFX10-NEXT: [[ASHR1:%[0-9]+]]:_(s64) = G_ASHR [[SEXT_INREG1]], [[C]](s32)
    ; GFX10-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[SEXT_INREG]](s64)
    ; GFX10-NEXT: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX10-NEXT: [[UADDO:%[0-9]+]]:_(s32), [[UADDO1:%[0-9]+]]:_(i1) = G_UADDO [[UV]], [[UV2]]
    ; GFX10-NEXT: [[UADDE:%[0-9]+]]:_(s32), [[UADDE1:%[0-9]+]]:_(i1) = G_UADDE [[UV1]], [[UV3]], [[UADDO1]]
    ; GFX10-NEXT: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO]](s32), [[UADDE]](s32)
    ; GFX10-NEXT: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[SEXT_INREG1]](s64)
    ; GFX10-NEXT: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR1]](s64)
    ; GFX10-NEXT: [[UADDO2:%[0-9]+]]:_(s32), [[UADDO3:%[0-9]+]]:_(i1) = G_UADDO [[UV4]], [[UV6]]
    ; GFX10-NEXT: [[UADDE2:%[0-9]+]]:_(s32), [[UADDE3:%[0-9]+]]:_(i1) = G_UADDE [[UV5]], [[UV7]], [[UADDO3]]
    ; GFX10-NEXT: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UADDO2]](s32), [[UADDE2]](s32)
    ; GFX10-NEXT: [[XOR:%[0-9]+]]:_(s64) = G_XOR [[MV]], [[ASHR]]
    ; GFX10-NEXT: [[XOR1:%[0-9]+]]:_(s64) = G_XOR [[MV1]], [[ASHR1]]
    ; GFX10-NEXT: [[UV8:%[0-9]+]]:_(i32), [[UV9:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX10-NEXT: [[UITOFP:%[0-9]+]]:_(f32) = G_UITOFP [[UV8]](i32)
    ; GFX10-NEXT: [[UITOFP1:%[0-9]+]]:_(f32) = G_UITOFP [[UV9]](i32)
    ; GFX10-NEXT: [[C1:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x4F800000
    ; GFX10-NEXT: [[FMUL:%[0-9]+]]:_(f32) = G_FMUL [[UITOFP1]], [[C1]]
    ; GFX10-NEXT: [[FADD:%[0-9]+]]:_(f32) = G_FADD [[FMUL]], [[UITOFP]]
    ; GFX10-NEXT: [[AMDGPU_RCP_IFLAG:%[0-9]+]]:_(s32) = G_AMDGPU_RCP_IFLAG [[FADD]](f32)
    ; GFX10-NEXT: [[C2:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x5F7FFFFC
    ; GFX10-NEXT: [[FMUL1:%[0-9]+]]:_(f32) = G_FMUL [[AMDGPU_RCP_IFLAG]], [[C2]]
    ; GFX10-NEXT: [[C3:%[0-9]+]]:_(s32) = G_FCONSTANT float f0x2F800000
    ; GFX10-NEXT: [[FMUL2:%[0-9]+]]:_(f32) = G_FMUL [[FMUL1]], [[C3]]
    ; GFX10-NEXT: [[INTRINSIC_TRUNC:%[0-9]+]]:_(f32) = G_INTRINSIC_TRUNC [[FMUL2]]
    ; GFX10-NEXT: [[C4:%[0-9]+]]:_(s32) = G_FCONSTANT float f0xCF800000
    ; GFX10-NEXT: [[FMUL3:%[0-9]+]]:_(f32) = G_FMUL [[INTRINSIC_TRUNC]], [[C4]]
    ; GFX10-NEXT: [[FADD1:%[0-9]+]]:_(f32) = G_FADD [[FMUL3]], [[FMUL1]]
    ; GFX10-NEXT: [[FPTOUI:%[0-9]+]]:_(i32) = G_FPTOUI [[FADD1]](f32)
    ; GFX10-NEXT: [[FPTOUI1:%[0-9]+]]:_(i32) = G_FPTOUI [[INTRINSIC_TRUNC]](f32)
    ; GFX10-NEXT: [[C5:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; GFX10-NEXT: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C5]](s64)
    ; GFX10-NEXT: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX10-NEXT: [[USUBO:%[0-9]+]]:_(s32), [[USUBO1:%[0-9]+]]:_(i1) = G_USUBO [[UV10]], [[UV12]]
    ; GFX10-NEXT: [[USUBE:%[0-9]+]]:_(s32), [[USUBE1:%[0-9]+]]:_(i1) = G_USUBE [[UV11]], [[UV13]], [[USUBO1]]
    ; GFX10-NEXT: [[AMDGPU_MAD_U64_U32_:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_1:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[FPTOUI]], [[C5]]
    ; GFX10-NEXT: [[UV14:%[0-9]+]]:_(i32), [[UV15:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_]](s64)
    ; GFX10-NEXT: [[MUL:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[FPTOUI1]]
    ; GFX10-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[UV15]], [[MUL]]
    ; GFX10-NEXT: [[MUL1:%[0-9]+]]:_(i32) = G_MUL [[USUBE]], [[FPTOUI]]
    ; GFX10-NEXT: [[ADD1:%[0-9]+]]:_(s32) = G_ADD [[ADD]], [[MUL1]]
    ; GFX10-NEXT: [[UMULH:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[UV14]]
    ; GFX10-NEXT: [[MUL2:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI]], [[ADD1]]
    ; GFX10-NEXT: [[MUL3:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[UV14]]
    ; GFX10-NEXT: [[UADDO4:%[0-9]+]]:_(i32), [[UADDO5:%[0-9]+]]:_(i1) = G_UADDO [[UMULH]], [[MUL2]]
    ; GFX10-NEXT: [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO5]](i1)
    ; GFX10-NEXT: [[UADDO6:%[0-9]+]]:_(i32), [[UADDO7:%[0-9]+]]:_(i1) = G_UADDO [[UADDO4]], [[MUL3]]
    ; GFX10-NEXT: [[ZEXT1:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO7]](i1)
    ; GFX10-NEXT: [[ADD2:%[0-9]+]]:_(i32) = G_ADD [[ZEXT]], [[ZEXT1]]
    ; GFX10-NEXT: [[UMULH1:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[UV14]]
    ; GFX10-NEXT: [[UMULH2:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI]], [[ADD1]]
    ; GFX10-NEXT: [[MUL4:%[0-9]+]]:_(i32) = G_MUL [[FPTOUI1]], [[ADD1]]
    ; GFX10-NEXT: [[UADDO8:%[0-9]+]]:_(i32), [[UADDO9:%[0-9]+]]:_(i1) = G_UADDO [[UMULH1]], [[UMULH2]]
    ; GFX10-NEXT: [[ZEXT2:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO9]](i1)
    ; GFX10-NEXT: [[UADDO10:%[0-9]+]]:_(i32), [[UADDO11:%[0-9]+]]:_(i1) = G_UADDO [[UADDO8]], [[MUL4]]
    ; GFX10-NEXT: [[ZEXT3:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO11]](i1)
    ; GFX10-NEXT: [[ADD3:%[0-9]+]]:_(i32) = G_ADD [[ZEXT2]], [[ZEXT3]]
    ; GFX10-NEXT: [[UADDO12:%[0-9]+]]:_(i32), [[UADDO13:%[0-9]+]]:_(i1) = G_UADDO [[UADDO10]], [[ADD2]]
    ; GFX10-NEXT: [[ZEXT4:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO13]](i1)
    ; GFX10-NEXT: [[ADD4:%[0-9]+]]:_(i32) = G_ADD [[ADD3]], [[ZEXT4]]
    ; GFX10-NEXT: [[UMULH3:%[0-9]+]]:_(i32) = G_UMULH [[FPTOUI1]], [[ADD1]]
    ; GFX10-NEXT: [[ADD5:%[0-9]+]]:_(i32) = G_ADD [[UMULH3]], [[ADD4]]
    ; GFX10-NEXT: [[UADDO14:%[0-9]+]]:_(s32), [[UADDO15:%[0-9]+]]:_(s1) = G_UADDO [[FPTOUI]], [[UADDO12]]
    ; GFX10-NEXT: [[UADDE4:%[0-9]+]]:_(s32), [[UADDE5:%[0-9]+]]:_(s1) = G_UADDE [[FPTOUI1]], [[ADD5]], [[UADDO15]]
    ; GFX10-NEXT: [[AMDGPU_MAD_U64_U32_2:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_3:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[USUBO]](s32), [[UADDO14]], [[C5]]
    ; GFX10-NEXT: [[UV16:%[0-9]+]]:_(i32), [[UV17:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_2]](s64)
    ; GFX10-NEXT: [[MUL5:%[0-9]+]]:_(i32) = G_MUL [[USUBO]], [[UADDE4]]
    ; GFX10-NEXT: [[ADD6:%[0-9]+]]:_(s32) = G_ADD [[UV17]], [[MUL5]]
    ; GFX10-NEXT: [[MUL6:%[0-9]+]]:_(i32) = G_MUL [[USUBE]], [[UADDO14]]
    ; GFX10-NEXT: [[ADD7:%[0-9]+]]:_(s32) = G_ADD [[ADD6]], [[MUL6]]
    ; GFX10-NEXT: [[UMULH4:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[UV16]]
    ; GFX10-NEXT: [[MUL7:%[0-9]+]]:_(i32) = G_MUL [[UADDO14]], [[ADD7]]
    ; GFX10-NEXT: [[MUL8:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[UV16]]
    ; GFX10-NEXT: [[UADDO16:%[0-9]+]]:_(i32), [[UADDO17:%[0-9]+]]:_(i1) = G_UADDO [[UMULH4]], [[MUL7]]
    ; GFX10-NEXT: [[ZEXT5:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO17]](i1)
    ; GFX10-NEXT: [[UADDO18:%[0-9]+]]:_(i32), [[UADDO19:%[0-9]+]]:_(i1) = G_UADDO [[UADDO16]], [[MUL8]]
    ; GFX10-NEXT: [[ZEXT6:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO19]](i1)
    ; GFX10-NEXT: [[ADD8:%[0-9]+]]:_(i32) = G_ADD [[ZEXT5]], [[ZEXT6]]
    ; GFX10-NEXT: [[UMULH5:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[UV16]]
    ; GFX10-NEXT: [[UMULH6:%[0-9]+]]:_(i32) = G_UMULH [[UADDO14]], [[ADD7]]
    ; GFX10-NEXT: [[MUL9:%[0-9]+]]:_(i32) = G_MUL [[UADDE4]], [[ADD7]]
    ; GFX10-NEXT: [[UADDO20:%[0-9]+]]:_(i32), [[UADDO21:%[0-9]+]]:_(i1) = G_UADDO [[UMULH5]], [[UMULH6]]
    ; GFX10-NEXT: [[ZEXT7:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO21]](i1)
    ; GFX10-NEXT: [[UADDO22:%[0-9]+]]:_(i32), [[UADDO23:%[0-9]+]]:_(i1) = G_UADDO [[UADDO20]], [[MUL9]]
    ; GFX10-NEXT: [[ZEXT8:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO23]](i1)
    ; GFX10-NEXT: [[ADD9:%[0-9]+]]:_(i32) = G_ADD [[ZEXT7]], [[ZEXT8]]
    ; GFX10-NEXT: [[UADDO24:%[0-9]+]]:_(i32), [[UADDO25:%[0-9]+]]:_(i1) = G_UADDO [[UADDO22]], [[ADD8]]
    ; GFX10-NEXT: [[ZEXT9:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO25]](i1)
    ; GFX10-NEXT: [[ADD10:%[0-9]+]]:_(i32) = G_ADD [[ADD9]], [[ZEXT9]]
    ; GFX10-NEXT: [[UMULH7:%[0-9]+]]:_(i32) = G_UMULH [[UADDE4]], [[ADD7]]
    ; GFX10-NEXT: [[ADD11:%[0-9]+]]:_(i32) = G_ADD [[UMULH7]], [[ADD10]]
    ; GFX10-NEXT: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX10-NEXT: [[UADDO26:%[0-9]+]]:_(s32), [[UADDO27:%[0-9]+]]:_(s1) = G_UADDO [[UADDO14]], [[UADDO24]]
    ; GFX10-NEXT: [[UADDE6:%[0-9]+]]:_(s32), [[UADDE7:%[0-9]+]]:_(s1) = G_UADDE [[UADDE4]], [[ADD11]], [[UADDO27]]
    ; GFX10-NEXT: [[UV18:%[0-9]+]]:_(i32), [[UV19:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX10-NEXT: [[UV20:%[0-9]+]]:_(i32), [[UV21:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR]](s64)
    ; GFX10-NEXT: [[UMULH8:%[0-9]+]]:_(i32) = G_UMULH [[UV20]], [[UADDO26]]
    ; GFX10-NEXT: [[MUL10:%[0-9]+]]:_(i32) = G_MUL [[UV20]], [[UADDE6]]
    ; GFX10-NEXT: [[MUL11:%[0-9]+]]:_(i32) = G_MUL [[UV21]], [[UADDO26]]
    ; GFX10-NEXT: [[UADDO28:%[0-9]+]]:_(i32), [[UADDO29:%[0-9]+]]:_(i1) = G_UADDO [[UMULH8]], [[MUL10]]
    ; GFX10-NEXT: [[ZEXT10:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO29]](i1)
    ; GFX10-NEXT: [[UADDO30:%[0-9]+]]:_(i32), [[UADDO31:%[0-9]+]]:_(i1) = G_UADDO [[UADDO28]], [[MUL11]]
    ; GFX10-NEXT: [[ZEXT11:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO31]](i1)
    ; GFX10-NEXT: [[ADD12:%[0-9]+]]:_(i32) = G_ADD [[ZEXT10]], [[ZEXT11]]
    ; GFX10-NEXT: [[UMULH9:%[0-9]+]]:_(i32) = G_UMULH [[UV21]], [[UADDO26]]
    ; GFX10-NEXT: [[UMULH10:%[0-9]+]]:_(i32) = G_UMULH [[UV20]], [[UADDE6]]
    ; GFX10-NEXT: [[MUL12:%[0-9]+]]:_(i32) = G_MUL [[UV21]], [[UADDE6]]
    ; GFX10-NEXT: [[UADDO32:%[0-9]+]]:_(i32), [[UADDO33:%[0-9]+]]:_(i1) = G_UADDO [[UMULH9]], [[UMULH10]]
    ; GFX10-NEXT: [[ZEXT12:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO33]](i1)
    ; GFX10-NEXT: [[UADDO34:%[0-9]+]]:_(i32), [[UADDO35:%[0-9]+]]:_(i1) = G_UADDO [[UADDO32]], [[MUL12]]
    ; GFX10-NEXT: [[ZEXT13:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO35]](i1)
    ; GFX10-NEXT: [[ADD13:%[0-9]+]]:_(i32) = G_ADD [[ZEXT12]], [[ZEXT13]]
    ; GFX10-NEXT: [[UADDO36:%[0-9]+]]:_(i32), [[UADDO37:%[0-9]+]]:_(i1) = G_UADDO [[UADDO34]], [[ADD12]]
    ; GFX10-NEXT: [[ZEXT14:%[0-9]+]]:_(i32) = G_ZEXT [[UADDO37]](i1)
    ; GFX10-NEXT: [[ADD14:%[0-9]+]]:_(i32) = G_ADD [[ADD13]], [[ZEXT14]]
    ; GFX10-NEXT: [[UMULH11:%[0-9]+]]:_(i32) = G_UMULH [[UV21]], [[UADDE6]]
    ; GFX10-NEXT: [[ADD15:%[0-9]+]]:_(i32) = G_ADD [[UMULH11]], [[ADD14]]
    ; GFX10-NEXT: [[UV22:%[0-9]+]]:_(i32), [[UV23:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX10-NEXT: [[AMDGPU_MAD_U64_U32_4:%[0-9]+]]:_(s64), [[AMDGPU_MAD_U64_U32_5:%[0-9]+]]:_(s1) = G_AMDGPU_MAD_U64_U32 [[UV22]](i32), [[UADDO36]], [[C5]]
    ; GFX10-NEXT: [[UV24:%[0-9]+]]:_(i32), [[UV25:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[AMDGPU_MAD_U64_U32_4]](s64)
    ; GFX10-NEXT: [[MUL13:%[0-9]+]]:_(i32) = G_MUL [[UV22]], [[ADD15]]
    ; GFX10-NEXT: [[ADD16:%[0-9]+]]:_(s32) = G_ADD [[UV25]], [[MUL13]]
    ; GFX10-NEXT: [[MUL14:%[0-9]+]]:_(i32) = G_MUL [[UV23]], [[UADDO36]]
    ; GFX10-NEXT: [[ADD17:%[0-9]+]]:_(s32) = G_ADD [[ADD16]], [[MUL14]]
    ; GFX10-NEXT: [[USUBO2:%[0-9]+]]:_(s32), [[USUBO3:%[0-9]+]]:_(s1) = G_USUBO [[UV18]], [[UV24]]
    ; GFX10-NEXT: [[USUBE2:%[0-9]+]]:_(s32), [[USUBE3:%[0-9]+]]:_(s1) = G_USUBE [[UV19]], [[ADD17]], [[USUBO3]]
    ; GFX10-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[UV19]], [[ADD17]]
    ; GFX10-NEXT: [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO2]](s32), [[USUBE2]](s32)
    ; GFX10-NEXT: [[UV26:%[0-9]+]]:_(i32), [[UV27:%[0-9]+]]:_(i32) = G_UNMERGE_VALUES [[XOR1]](s64)
    ; GFX10-NEXT: [[ICMP:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE2]](s32), [[UV27]]
    ; GFX10-NEXT: [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[ICMP]](s1)
    ; GFX10-NEXT: [[ICMP1:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO2]](s32), [[UV26]]
    ; GFX10-NEXT: [[SEXT1:%[0-9]+]]:_(s32) = G_SEXT [[ICMP1]](s1)
    ; GFX10-NEXT: [[ICMP2:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE2]](s32), [[UV27]]
    ; GFX10-NEXT: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[ICMP2]](s1), [[SEXT1]], [[SEXT]]
    ; GFX10-NEXT: [[USUBO4:%[0-9]+]]:_(s32), [[USUBO5:%[0-9]+]]:_(s1) = G_USUBO [[USUBO2]], [[UV26]]
    ; GFX10-NEXT: [[USUBE4:%[0-9]+]]:_(s32), [[USUBE5:%[0-9]+]]:_(s1) = G_USUBE [[SUB]], [[UV27]], [[USUBO3]]
    ; GFX10-NEXT: [[USUBE6:%[0-9]+]]:_(s32), [[USUBE7:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[C6]], [[USUBO5]]
    ; GFX10-NEXT: [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO4]](s32), [[USUBE6]](s32)
    ; GFX10-NEXT: [[ICMP3:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBE6]](s32), [[UV27]]
    ; GFX10-NEXT: [[SEXT2:%[0-9]+]]:_(s32) = G_SEXT [[ICMP3]](s1)
    ; GFX10-NEXT: [[ICMP4:%[0-9]+]]:_(s1) = G_ICMP intpred(uge), [[USUBO4]](s32), [[UV26]]
    ; GFX10-NEXT: [[SEXT3:%[0-9]+]]:_(s32) = G_SEXT [[ICMP4]](s1)
    ; GFX10-NEXT: [[ICMP5:%[0-9]+]]:_(s1) = G_ICMP intpred(eq), [[USUBE6]](s32), [[UV27]]
    ; GFX10-NEXT: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP5]](s1), [[SEXT3]], [[SEXT2]]
    ; GFX10-NEXT: [[USUBO6:%[0-9]+]]:_(s32), [[USUBO7:%[0-9]+]]:_(s1) = G_USUBO [[USUBO4]], [[UV26]]
    ; GFX10-NEXT: [[USUBE8:%[0-9]+]]:_(s32), [[USUBE9:%[0-9]+]]:_(s1) = G_USUBE [[USUBE4]], [[UV27]], [[USUBO5]]
    ; GFX10-NEXT: [[USUBE10:%[0-9]+]]:_(s32), [[USUBE11:%[0-9]+]]:_(s1) = G_USUBE [[USUBE8]], [[C6]], [[USUBO7]]
    ; GFX10-NEXT: [[MV4:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO6]](s32), [[USUBE10]](s32)
    ; GFX10-NEXT: [[ICMP6:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT1]](s32), [[C6]]
    ; GFX10-NEXT: [[SELECT2:%[0-9]+]]:_(s64) = G_SELECT [[ICMP6]](s1), [[MV4]], [[MV3]]
    ; GFX10-NEXT: [[ICMP7:%[0-9]+]]:_(s1) = G_ICMP intpred(ne), [[SELECT]](s32), [[C6]]
    ; GFX10-NEXT: [[SELECT3:%[0-9]+]]:_(s64) = G_SELECT [[ICMP7]](s1), [[SELECT2]], [[MV2]]
    ; GFX10-NEXT: [[XOR2:%[0-9]+]]:_(s64) = G_XOR [[SELECT3]], [[ASHR]]
    ; GFX10-NEXT: [[UV28:%[0-9]+]]:_(s32), [[UV29:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[XOR2]](s64)
    ; GFX10-NEXT: [[UV30:%[0-9]+]]:_(s32), [[UV31:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ASHR]](s64)
    ; GFX10-NEXT: [[USUBO8:%[0-9]+]]:_(s32), [[USUBO9:%[0-9]+]]:_(i1) = G_USUBO [[UV28]], [[UV30]]
    ; GFX10-NEXT: [[USUBE12:%[0-9]+]]:_(s32), [[USUBE13:%[0-9]+]]:_(i1) = G_USUBE [[UV29]], [[UV31]], [[USUBO9]]
    ; GFX10-NEXT: [[MV5:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO8]](s32), [[USUBE12]](s32)
    ; GFX10-NEXT: $vgpr0_vgpr1 = COPY [[MV5]](s64)
    %0:_(s64) = COPY $vgpr0_vgpr1
    %1:_(s64) = COPY $vgpr2_vgpr3
    %2:_(s33) = G_TRUNC %0
    %3:_(s33) = G_TRUNC %1
    %4:_(s33) = G_SREM %2, %3
    %5:_(s64) = G_ANYEXT %4
    $vgpr0_vgpr1 = COPY %5
...
