# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py

# RUN: llc -global-isel -new-reg-bank-select -mtriple=amdgcn-mesa-mesa3d -mcpu=gfx1100 -run-pass=amdgpu-regbanklegalize -mattr=+real-true16 -o - %s | FileCheck -check-prefix=GFX11 %s

# RUN: llc -global-isel -new-reg-bank-select -mtriple=amdgcn-mesa-mesa3d -mcpu=gfx1200 -run-pass=amdgpu-regbanklegalize -mattr=+real-true16 -o - %s | FileCheck -check-prefix=GFX12 %s

---
name: test_merge_s16_into_s32_sgpr
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $sgpr0, $sgpr1

    ; GFX11-LABEL: name: test_merge_s16_into_s32_sgpr
    ; GFX11: liveins: $sgpr0, $sgpr1
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:sgpr(s32) = COPY $sgpr0
    ; GFX11-NEXT: [[COPY1:%[0-9]+]]:sgpr(s32) = COPY $sgpr1
    ; GFX11-NEXT: [[TRUNC:%[0-9]+]]:sgpr(s16) = G_TRUNC [[COPY]](s32)
    ; GFX11-NEXT: [[TRUNC1:%[0-9]+]]:sgpr(s16) = G_TRUNC [[COPY1]](s32)
    ; GFX11-NEXT: [[MV:%[0-9]+]]:sgpr(s32) = G_MERGE_VALUES [[TRUNC]](s16), [[TRUNC1]](s16)
    ; GFX11-NEXT: $sgpr0 = COPY [[MV]](s32)
    ;
    ; GFX12-LABEL: name: test_merge_s16_into_s32_sgpr
    ; GFX12: liveins: $sgpr0, $sgpr1
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:sgpr(s32) = COPY $sgpr0
    ; GFX12-NEXT: [[COPY1:%[0-9]+]]:sgpr(s32) = COPY $sgpr1
    ; GFX12-NEXT: [[TRUNC:%[0-9]+]]:sgpr(s16) = G_TRUNC [[COPY]](s32)
    ; GFX12-NEXT: [[TRUNC1:%[0-9]+]]:sgpr(s16) = G_TRUNC [[COPY1]](s32)
    ; GFX12-NEXT: [[MV:%[0-9]+]]:sgpr(s32) = G_MERGE_VALUES [[TRUNC]](s16), [[TRUNC1]](s16)
    ; GFX12-NEXT: $sgpr0 = COPY [[MV]](s32)
    %0:sgpr(s32) = COPY $sgpr0
    %1:sgpr(s32) = COPY $sgpr1
    %2:sgpr(s16) = G_TRUNC %0:sgpr(s32)
    %3:sgpr(s16) = G_TRUNC %1:sgpr(s32)
    %4:sgpr(s32) = G_MERGE_VALUES %2:sgpr(s16), %3:sgpr(s16)
    $sgpr0 = COPY %4:sgpr(s32)
...

---
name: test_build_s16_into_s32_sgpr
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $sgpr0, $sgpr1

    ; GFX11-LABEL: name: test_build_s16_into_s32_sgpr
    ; GFX11: liveins: $sgpr0, $sgpr1
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:sgpr(s32) = COPY $sgpr0
    ; GFX11-NEXT: [[COPY1:%[0-9]+]]:sgpr(s32) = COPY $sgpr1
    ; GFX11-NEXT: [[TRUNC:%[0-9]+]]:sgpr(s16) = G_TRUNC [[COPY]](s32)
    ; GFX11-NEXT: [[TRUNC1:%[0-9]+]]:sgpr(s16) = G_TRUNC [[COPY1]](s32)
    ; GFX11-NEXT: [[BUILD_VECTOR:%[0-9]+]]:sgpr(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
    ; GFX11-NEXT: $sgpr0 = COPY [[BUILD_VECTOR]](<2 x s16>)
    ;
    ; GFX12-LABEL: name: test_build_s16_into_s32_sgpr
    ; GFX12: liveins: $sgpr0, $sgpr1
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:sgpr(s32) = COPY $sgpr0
    ; GFX12-NEXT: [[COPY1:%[0-9]+]]:sgpr(s32) = COPY $sgpr1
    ; GFX12-NEXT: [[TRUNC:%[0-9]+]]:sgpr(s16) = G_TRUNC [[COPY]](s32)
    ; GFX12-NEXT: [[TRUNC1:%[0-9]+]]:sgpr(s16) = G_TRUNC [[COPY1]](s32)
    ; GFX12-NEXT: [[BUILD_VECTOR:%[0-9]+]]:sgpr(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
    ; GFX12-NEXT: $sgpr0 = COPY [[BUILD_VECTOR]](<2 x s16>)
    %0:sgpr(s32) = COPY $sgpr0
    %1:sgpr(s32) = COPY $sgpr1
    %2:sgpr(s16) = G_TRUNC %0:sgpr(s32)
    %3:sgpr(s16) = G_TRUNC %1:sgpr(s32)
    %4:sgpr(<2 x s16>) = G_BUILD_VECTOR %2:sgpr(s16), %3:sgpr(s16)
    $sgpr0 = COPY %4:sgpr(<2 x s16>)
...

---
name: test_merge_s16_into_s32_vgpr
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $sgpr0, $sgpr1, $vgpr0, $vgpr1

    ; GFX11-LABEL: name: test_merge_s16_into_s32_vgpr
    ; GFX11: liveins: $sgpr0, $sgpr1, $vgpr0, $vgpr1
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; GFX11-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; GFX11-NEXT: [[TRUNC:%[0-9]+]]:vgpr(s16) = G_TRUNC [[COPY]](s32)
    ; GFX11-NEXT: [[TRUNC1:%[0-9]+]]:vgpr(s16) = G_TRUNC [[COPY1]](s32)
    ; GFX11-NEXT: [[MV:%[0-9]+]]:vgpr(s32) = G_MERGE_VALUES [[TRUNC]](s16), [[TRUNC1]](s16)
    ; GFX11-NEXT: $vgpr0 = COPY [[MV]](s32)
    ;
    ; GFX12-LABEL: name: test_merge_s16_into_s32_vgpr
    ; GFX12: liveins: $sgpr0, $sgpr1, $vgpr0, $vgpr1
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; GFX12-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; GFX12-NEXT: [[TRUNC:%[0-9]+]]:vgpr(s16) = G_TRUNC [[COPY]](s32)
    ; GFX12-NEXT: [[TRUNC1:%[0-9]+]]:vgpr(s16) = G_TRUNC [[COPY1]](s32)
    ; GFX12-NEXT: [[MV:%[0-9]+]]:vgpr(s32) = G_MERGE_VALUES [[TRUNC]](s16), [[TRUNC1]](s16)
    ; GFX12-NEXT: $vgpr0 = COPY [[MV]](s32)
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vgpr(s16) = G_TRUNC %0:vgpr(s32)
    %3:vgpr(s16) = G_TRUNC %1:vgpr(s32)
    %4:vgpr(s32) = G_MERGE_VALUES %2:vgpr(s16), %3:vgpr(s16)
    $vgpr0 = COPY %4:vgpr(s32)
...

---
name: test_build_s16_into_s32_vgpr
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $vgpr0, $vgpr1

    ; GFX11-LABEL: name: test_build_s16_into_s32_vgpr
    ; GFX11: liveins: $vgpr0, $vgpr1
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; GFX11-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; GFX11-NEXT: [[TRUNC:%[0-9]+]]:vgpr(s16) = G_TRUNC [[COPY]](s32)
    ; GFX11-NEXT: [[TRUNC1:%[0-9]+]]:vgpr(s16) = G_TRUNC [[COPY1]](s32)
    ; GFX11-NEXT: [[BUILD_VECTOR:%[0-9]+]]:vgpr(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
    ; GFX11-NEXT: $vgpr0 = COPY [[BUILD_VECTOR]](<2 x s16>)
    ;
    ; GFX12-LABEL: name: test_build_s16_into_s32_vgpr
    ; GFX12: liveins: $vgpr0, $vgpr1
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; GFX12-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; GFX12-NEXT: [[TRUNC:%[0-9]+]]:vgpr(s16) = G_TRUNC [[COPY]](s32)
    ; GFX12-NEXT: [[TRUNC1:%[0-9]+]]:vgpr(s16) = G_TRUNC [[COPY1]](s32)
    ; GFX12-NEXT: [[BUILD_VECTOR:%[0-9]+]]:vgpr(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
    ; GFX12-NEXT: $vgpr0 = COPY [[BUILD_VECTOR]](<2 x s16>)
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vgpr(s16) = G_TRUNC %0:vgpr(s32)
    %3:vgpr(s16) = G_TRUNC %1:vgpr(s32)
    %4:vgpr(<2 x s16>) = G_BUILD_VECTOR %2:vgpr(s16), %3:vgpr(s16)
    $vgpr0 = COPY %4:vgpr(<2 x s16>)
...
