# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 -mattr=+real-true16 -run-pass=legalizer %s -o - | FileCheck --allow-unused-prefixes --check-prefixes=GFX11,GFX11-TRUE16 %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 -mattr=-real-true16 -run-pass=legalizer %s -o - | FileCheck --allow-unused-prefixes --check-prefixes=GFX11,GFX11-FAKE16 %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1200 -mattr=+real-true16 -run-pass=legalizer %s -o - | FileCheck --allow-unused-prefixes --check-prefixes=GFX12,GFX12-TRUE16 %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1200 -mattr=-real-true16 -run-pass=legalizer %s -o - | FileCheck --allow-unused-prefixes --check-prefixes=GFX12,GFX12-FAKE16 %s
#
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 -mattr=+real-true16 -run-pass=legalizer,amdgpu-postlegalizer-combiner,amdgpu-regbankselect,amdgpu-regbanklegalize,amdgpu-regbank-combiner %s -o - | FileCheck --allow-unused-prefixes --check-prefixes=GFX11-TO-COMBINER,GFX11-TO-COMBINER-TRUE16 %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 -mattr=-real-true16 -run-pass=legalizer,amdgpu-postlegalizer-combiner,amdgpu-regbankselect,amdgpu-regbanklegalize,amdgpu-regbank-combiner %s -o - | FileCheck --allow-unused-prefixes --check-prefixes=GFX11-TO-COMBINER,GFX11-TO-COMBINER-FAKE16 %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1200 -mattr=+real-true16 -run-pass=legalizer,amdgpu-postlegalizer-combiner,amdgpu-regbankselect,amdgpu-regbanklegalize,amdgpu-regbank-combiner %s -o - | FileCheck --allow-unused-prefixes --check-prefixes=GFX12-TO-COMBINER,GFX12-TO-COMBINER-TRUE16 %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1200 -mattr=-real-true16 -run-pass=legalizer,amdgpu-postlegalizer-combiner,amdgpu-regbankselect,amdgpu-regbanklegalize,amdgpu-regbank-combiner %s -o - | FileCheck --allow-unused-prefixes --check-prefixes=GFX12-TO-COMBINER,GFX12-TO-COMBINER-FAKE16 %s

---
name: test_sextload_global_s16_from_s8
body: |
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2

    ; GFX11-LABEL: name: test_sextload_global_s16_from_s8
    ; GFX11: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX11-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr2
    ; GFX11-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[COPY]](p1) :: (load (s8), addrspace 1)
    ; GFX11-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX11-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX11-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; GFX11-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[SEXTLOAD]], [[C1]]
    ; GFX11-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[AND]], [[C]](s32)
    ; GFX11-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; GFX11-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C2]]
    ; GFX11-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[SHL]]
    ; GFX11-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](s32)
    ; GFX11-NEXT: $vgpr0 = COPY [[BITCAST1]](<2 x s16>)
    ;
    ; GFX12-LABEL: name: test_sextload_global_s16_from_s8
    ; GFX12: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX12-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr2
    ; GFX12-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[COPY]](p1) :: (load (s8), addrspace 1)
    ; GFX12-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX12-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX12-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; GFX12-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[SEXTLOAD]], [[C1]]
    ; GFX12-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[AND]], [[C]](s32)
    ; GFX12-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; GFX12-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C2]]
    ; GFX12-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[SHL]]
    ; GFX12-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](s32)
    ; GFX12-NEXT: $vgpr0 = COPY [[BITCAST1]](<2 x s16>)
    ;
    ; GFX11-TO-COMBINER-LABEL: name: test_sextload_global_s16_from_s8
    ; GFX11-TO-COMBINER: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX11-TO-COMBINER-NEXT: {{  $}}
    ; GFX11-TO-COMBINER-NEXT: [[COPY:%[0-9]+]]:vgpr(p1) = COPY $vgpr0_vgpr1
    ; GFX11-TO-COMBINER-NEXT: [[COPY1:%[0-9]+]]:vgpr(<2 x s16>) = COPY $vgpr2
    ; GFX11-TO-COMBINER-NEXT: [[AMDGPU_LOAD_D16_LO_I8_:%[0-9]+]]:vgpr(<2 x s16>) = G_AMDGPU_LOAD_D16_LO_I8 [[COPY]](p1), [[COPY1]] :: (load (s8), addrspace 1)
    ; GFX11-TO-COMBINER-NEXT: $vgpr0 = COPY [[AMDGPU_LOAD_D16_LO_I8_]](<2 x s16>)
    ;
    ; GFX12-TO-COMBINER-LABEL: name: test_sextload_global_s16_from_s8
    ; GFX12-TO-COMBINER: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX12-TO-COMBINER-NEXT: {{  $}}
    ; GFX12-TO-COMBINER-NEXT: [[COPY:%[0-9]+]]:vgpr(p1) = COPY $vgpr0_vgpr1
    ; GFX12-TO-COMBINER-NEXT: [[COPY1:%[0-9]+]]:vgpr(<2 x s16>) = COPY $vgpr2
    ; GFX12-TO-COMBINER-NEXT: [[AMDGPU_LOAD_D16_LO_I8_:%[0-9]+]]:vgpr(<2 x s16>) = G_AMDGPU_LOAD_D16_LO_I8 [[COPY]](p1), [[COPY1]] :: (load (s8), addrspace 1)
    ; GFX12-TO-COMBINER-NEXT: $vgpr0 = COPY [[AMDGPU_LOAD_D16_LO_I8_]](<2 x s16>)
    %0:_(p1) = COPY $vgpr0_vgpr1
    %1:_(<2 x s16>) = COPY $vgpr2
    %2:_(s16) = G_SEXTLOAD %0 :: (load (s8), addrspace 1)
    %3:_(s32) = G_CONSTANT i32 0
    %4:_(<2 x s16>) = G_INSERT_VECTOR_ELT %1:_, %2:_(s16), %3:_(s32)
    $vgpr0 = COPY %4
...

---
name: test_sextload_local_s16_from_s8
body: |
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2

    ; GFX11-LABEL: name: test_sextload_local_s16_from_s8
    ; GFX11: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX11-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr2
    ; GFX11-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[COPY]](p1) :: (load (s8), addrspace 3)
    ; GFX11-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX11-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX11-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; GFX11-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[SEXTLOAD]], [[C1]]
    ; GFX11-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[AND]], [[C]](s32)
    ; GFX11-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; GFX11-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C2]]
    ; GFX11-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[SHL]]
    ; GFX11-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](s32)
    ; GFX11-NEXT: $vgpr0 = COPY [[BITCAST1]](<2 x s16>)
    ;
    ; GFX12-LABEL: name: test_sextload_local_s16_from_s8
    ; GFX12: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX12-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr2
    ; GFX12-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[COPY]](p1) :: (load (s8), addrspace 3)
    ; GFX12-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX12-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX12-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; GFX12-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[SEXTLOAD]], [[C1]]
    ; GFX12-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[AND]], [[C]](s32)
    ; GFX12-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; GFX12-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C2]]
    ; GFX12-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[SHL]]
    ; GFX12-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](s32)
    ; GFX12-NEXT: $vgpr0 = COPY [[BITCAST1]](<2 x s16>)
    ;
    ; GFX11-TO-COMBINER-LABEL: name: test_sextload_local_s16_from_s8
    ; GFX11-TO-COMBINER: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX11-TO-COMBINER-NEXT: {{  $}}
    ; GFX11-TO-COMBINER-NEXT: [[COPY:%[0-9]+]]:vgpr(p1) = COPY $vgpr0_vgpr1
    ; GFX11-TO-COMBINER-NEXT: [[COPY1:%[0-9]+]]:vgpr(<2 x s16>) = COPY $vgpr2
    ; GFX11-TO-COMBINER-NEXT: [[AMDGPU_LOAD_D16_LO_I8_:%[0-9]+]]:vgpr(<2 x s16>) = G_AMDGPU_LOAD_D16_LO_I8 [[COPY]](p1), [[COPY1]] :: (load (s8), addrspace 3)
    ; GFX11-TO-COMBINER-NEXT: $vgpr0 = COPY [[AMDGPU_LOAD_D16_LO_I8_]](<2 x s16>)
    ;
    ; GFX12-TO-COMBINER-LABEL: name: test_sextload_local_s16_from_s8
    ; GFX12-TO-COMBINER: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX12-TO-COMBINER-NEXT: {{  $}}
    ; GFX12-TO-COMBINER-NEXT: [[COPY:%[0-9]+]]:vgpr(p1) = COPY $vgpr0_vgpr1
    ; GFX12-TO-COMBINER-NEXT: [[COPY1:%[0-9]+]]:vgpr(<2 x s16>) = COPY $vgpr2
    ; GFX12-TO-COMBINER-NEXT: [[AMDGPU_LOAD_D16_LO_I8_:%[0-9]+]]:vgpr(<2 x s16>) = G_AMDGPU_LOAD_D16_LO_I8 [[COPY]](p1), [[COPY1]] :: (load (s8), addrspace 3)
    ; GFX12-TO-COMBINER-NEXT: $vgpr0 = COPY [[AMDGPU_LOAD_D16_LO_I8_]](<2 x s16>)
    %0:_(p1) = COPY $vgpr0_vgpr1
    %1:_(<2 x s16>) = COPY $vgpr2
    %2:_(s16) = G_SEXTLOAD %0 :: (load (s8), addrspace 3)
    %3:_(s32) = G_CONSTANT i32 0
    %4:_(<2 x s16>) = G_INSERT_VECTOR_ELT %1:_, %2:_(s16), %3:_(s32)
    $vgpr0 = COPY %4
...

---
name: test_sextload_private_s16_from_s8
body: |
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2

    ; GFX11-LABEL: name: test_sextload_private_s16_from_s8
    ; GFX11: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX11-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr2
    ; GFX11-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[COPY]](p1) :: (load (s8), addrspace 5)
    ; GFX11-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX11-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX11-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; GFX11-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[SEXTLOAD]], [[C1]]
    ; GFX11-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[AND]], [[C]](s32)
    ; GFX11-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; GFX11-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C2]]
    ; GFX11-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[SHL]]
    ; GFX11-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](s32)
    ; GFX11-NEXT: $vgpr0 = COPY [[BITCAST1]](<2 x s16>)
    ;
    ; GFX12-LABEL: name: test_sextload_private_s16_from_s8
    ; GFX12: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX12-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr2
    ; GFX12-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[COPY]](p1) :: (load (s8), addrspace 5)
    ; GFX12-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX12-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX12-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; GFX12-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[SEXTLOAD]], [[C1]]
    ; GFX12-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[AND]], [[C]](s32)
    ; GFX12-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; GFX12-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C2]]
    ; GFX12-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[SHL]]
    ; GFX12-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](s32)
    ; GFX12-NEXT: $vgpr0 = COPY [[BITCAST1]](<2 x s16>)
    ;
    ; GFX11-TO-COMBINER-LABEL: name: test_sextload_private_s16_from_s8
    ; GFX11-TO-COMBINER: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX11-TO-COMBINER-NEXT: {{  $}}
    ; GFX11-TO-COMBINER-NEXT: [[COPY:%[0-9]+]]:vgpr(p1) = COPY $vgpr0_vgpr1
    ; GFX11-TO-COMBINER-NEXT: [[COPY1:%[0-9]+]]:vgpr(<2 x s16>) = COPY $vgpr2
    ; GFX11-TO-COMBINER-NEXT: [[AMDGPU_LOAD_D16_LO_I8_:%[0-9]+]]:vgpr(<2 x s16>) = G_AMDGPU_LOAD_D16_LO_I8 [[COPY]](p1), [[COPY1]] :: (load (s8), addrspace 5)
    ; GFX11-TO-COMBINER-NEXT: $vgpr0 = COPY [[AMDGPU_LOAD_D16_LO_I8_]](<2 x s16>)
    ;
    ; GFX12-TO-COMBINER-LABEL: name: test_sextload_private_s16_from_s8
    ; GFX12-TO-COMBINER: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX12-TO-COMBINER-NEXT: {{  $}}
    ; GFX12-TO-COMBINER-NEXT: [[COPY:%[0-9]+]]:vgpr(p1) = COPY $vgpr0_vgpr1
    ; GFX12-TO-COMBINER-NEXT: [[COPY1:%[0-9]+]]:vgpr(<2 x s16>) = COPY $vgpr2
    ; GFX12-TO-COMBINER-NEXT: [[AMDGPU_LOAD_D16_LO_I8_:%[0-9]+]]:vgpr(<2 x s16>) = G_AMDGPU_LOAD_D16_LO_I8 [[COPY]](p1), [[COPY1]] :: (load (s8), addrspace 5)
    ; GFX12-TO-COMBINER-NEXT: $vgpr0 = COPY [[AMDGPU_LOAD_D16_LO_I8_]](<2 x s16>)
    %0:_(p1) = COPY $vgpr0_vgpr1
    %1:_(<2 x s16>) = COPY $vgpr2
    %2:_(s16) = G_SEXTLOAD %0 :: (load (s8), addrspace 5)
    %3:_(s32) = G_CONSTANT i32 0
    %4:_(<2 x s16>) = G_INSERT_VECTOR_ELT %1:_, %2:_(s16), %3:_(s32)
    $vgpr0 = COPY %4
...

---
name: test_zextload_global_s16_from_s8
body: |
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2

    ; GFX11-LABEL: name: test_zextload_global_s16_from_s8
    ; GFX11: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX11-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr2
    ; GFX11-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[COPY]](p1) :: (load (s8), addrspace 1)
    ; GFX11-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX11-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX11-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ZEXTLOAD]], [[C]](s32)
    ; GFX11-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; GFX11-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C1]]
    ; GFX11-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND]], [[SHL]]
    ; GFX11-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](s32)
    ; GFX11-NEXT: $vgpr0 = COPY [[BITCAST1]](<2 x s16>)
    ;
    ; GFX12-LABEL: name: test_zextload_global_s16_from_s8
    ; GFX12: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX12-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr2
    ; GFX12-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[COPY]](p1) :: (load (s8), addrspace 1)
    ; GFX12-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX12-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX12-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ZEXTLOAD]], [[C]](s32)
    ; GFX12-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; GFX12-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C1]]
    ; GFX12-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND]], [[SHL]]
    ; GFX12-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](s32)
    ; GFX12-NEXT: $vgpr0 = COPY [[BITCAST1]](<2 x s16>)
    ;
    ; GFX11-TO-COMBINER-LABEL: name: test_zextload_global_s16_from_s8
    ; GFX11-TO-COMBINER: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX11-TO-COMBINER-NEXT: {{  $}}
    ; GFX11-TO-COMBINER-NEXT: [[COPY:%[0-9]+]]:vgpr(p1) = COPY $vgpr0_vgpr1
    ; GFX11-TO-COMBINER-NEXT: [[COPY1:%[0-9]+]]:vgpr(<2 x s16>) = COPY $vgpr2
    ; GFX11-TO-COMBINER-NEXT: [[AMDGPU_LOAD_D16_LO_U8_:%[0-9]+]]:vgpr(<2 x s16>) = G_AMDGPU_LOAD_D16_LO_U8 [[COPY]](p1), [[COPY1]] :: (load (s8), addrspace 1)
    ; GFX11-TO-COMBINER-NEXT: $vgpr0 = COPY [[AMDGPU_LOAD_D16_LO_U8_]](<2 x s16>)
    ;
    ; GFX12-TO-COMBINER-LABEL: name: test_zextload_global_s16_from_s8
    ; GFX12-TO-COMBINER: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX12-TO-COMBINER-NEXT: {{  $}}
    ; GFX12-TO-COMBINER-NEXT: [[COPY:%[0-9]+]]:vgpr(p1) = COPY $vgpr0_vgpr1
    ; GFX12-TO-COMBINER-NEXT: [[COPY1:%[0-9]+]]:vgpr(<2 x s16>) = COPY $vgpr2
    ; GFX12-TO-COMBINER-NEXT: [[AMDGPU_LOAD_D16_LO_U8_:%[0-9]+]]:vgpr(<2 x s16>) = G_AMDGPU_LOAD_D16_LO_U8 [[COPY]](p1), [[COPY1]] :: (load (s8), addrspace 1)
    ; GFX12-TO-COMBINER-NEXT: $vgpr0 = COPY [[AMDGPU_LOAD_D16_LO_U8_]](<2 x s16>)
    %0:_(p1) = COPY $vgpr0_vgpr1
    %1:_(<2 x s16>) = COPY $vgpr2
    %2:_(s16) = G_ZEXTLOAD %0 :: (load (s8), addrspace 1)
    %3:_(s32) = G_CONSTANT i32 0
    %4:_(<2 x s16>) = G_INSERT_VECTOR_ELT %1:_, %2:_(s16), %3:_(s32)
    $vgpr0 = COPY %4
...

---
name: test_zextload_local_s16_from_s8
body: |
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2

    ; GFX11-LABEL: name: test_zextload_local_s16_from_s8
    ; GFX11: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX11-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr2
    ; GFX11-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[COPY]](p1) :: (load (s8), addrspace 3)
    ; GFX11-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX11-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX11-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ZEXTLOAD]], [[C]](s32)
    ; GFX11-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; GFX11-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C1]]
    ; GFX11-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND]], [[SHL]]
    ; GFX11-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](s32)
    ; GFX11-NEXT: $vgpr0 = COPY [[BITCAST1]](<2 x s16>)
    ;
    ; GFX12-LABEL: name: test_zextload_local_s16_from_s8
    ; GFX12: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX12-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr2
    ; GFX12-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[COPY]](p1) :: (load (s8), addrspace 3)
    ; GFX12-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX12-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX12-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ZEXTLOAD]], [[C]](s32)
    ; GFX12-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; GFX12-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C1]]
    ; GFX12-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND]], [[SHL]]
    ; GFX12-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](s32)
    ; GFX12-NEXT: $vgpr0 = COPY [[BITCAST1]](<2 x s16>)
    ;
    ; GFX11-TO-COMBINER-LABEL: name: test_zextload_local_s16_from_s8
    ; GFX11-TO-COMBINER: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX11-TO-COMBINER-NEXT: {{  $}}
    ; GFX11-TO-COMBINER-NEXT: [[COPY:%[0-9]+]]:vgpr(p1) = COPY $vgpr0_vgpr1
    ; GFX11-TO-COMBINER-NEXT: [[COPY1:%[0-9]+]]:vgpr(<2 x s16>) = COPY $vgpr2
    ; GFX11-TO-COMBINER-NEXT: [[AMDGPU_LOAD_D16_LO_U8_:%[0-9]+]]:vgpr(<2 x s16>) = G_AMDGPU_LOAD_D16_LO_U8 [[COPY]](p1), [[COPY1]] :: (load (s8), addrspace 3)
    ; GFX11-TO-COMBINER-NEXT: $vgpr0 = COPY [[AMDGPU_LOAD_D16_LO_U8_]](<2 x s16>)
    ;
    ; GFX12-TO-COMBINER-LABEL: name: test_zextload_local_s16_from_s8
    ; GFX12-TO-COMBINER: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX12-TO-COMBINER-NEXT: {{  $}}
    ; GFX12-TO-COMBINER-NEXT: [[COPY:%[0-9]+]]:vgpr(p1) = COPY $vgpr0_vgpr1
    ; GFX12-TO-COMBINER-NEXT: [[COPY1:%[0-9]+]]:vgpr(<2 x s16>) = COPY $vgpr2
    ; GFX12-TO-COMBINER-NEXT: [[AMDGPU_LOAD_D16_LO_U8_:%[0-9]+]]:vgpr(<2 x s16>) = G_AMDGPU_LOAD_D16_LO_U8 [[COPY]](p1), [[COPY1]] :: (load (s8), addrspace 3)
    ; GFX12-TO-COMBINER-NEXT: $vgpr0 = COPY [[AMDGPU_LOAD_D16_LO_U8_]](<2 x s16>)
    %0:_(p1) = COPY $vgpr0_vgpr1
    %1:_(<2 x s16>) = COPY $vgpr2
    %2:_(s16) = G_ZEXTLOAD %0 :: (load (s8), addrspace 3)
    %3:_(s32) = G_CONSTANT i32 0
    %4:_(<2 x s16>) = G_INSERT_VECTOR_ELT %1:_, %2:_(s16), %3:_(s32)
    $vgpr0 = COPY %4
...

---
name: test_zextload_private_s16_from_s8
body: |
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2

    ; GFX11-LABEL: name: test_zextload_private_s16_from_s8
    ; GFX11: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX11-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr2
    ; GFX11-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[COPY]](p1) :: (load (s8), addrspace 5)
    ; GFX11-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX11-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX11-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ZEXTLOAD]], [[C]](s32)
    ; GFX11-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; GFX11-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C1]]
    ; GFX11-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND]], [[SHL]]
    ; GFX11-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](s32)
    ; GFX11-NEXT: $vgpr0 = COPY [[BITCAST1]](<2 x s16>)
    ;
    ; GFX12-LABEL: name: test_zextload_private_s16_from_s8
    ; GFX12: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX12-NEXT: [[COPY1:%[0-9]+]]:_(<2 x s16>) = COPY $vgpr2
    ; GFX12-NEXT: [[ZEXTLOAD:%[0-9]+]]:_(s32) = G_ZEXTLOAD [[COPY]](p1) :: (load (s8), addrspace 5)
    ; GFX12-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; GFX12-NEXT: [[BITCAST:%[0-9]+]]:_(s32) = G_BITCAST [[COPY1]](<2 x s16>)
    ; GFX12-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ZEXTLOAD]], [[C]](s32)
    ; GFX12-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; GFX12-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[BITCAST]], [[C1]]
    ; GFX12-NEXT: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND]], [[SHL]]
    ; GFX12-NEXT: [[BITCAST1:%[0-9]+]]:_(<2 x s16>) = G_BITCAST [[OR]](s32)
    ; GFX12-NEXT: $vgpr0 = COPY [[BITCAST1]](<2 x s16>)
    ;
    ; GFX11-TO-COMBINER-LABEL: name: test_zextload_private_s16_from_s8
    ; GFX11-TO-COMBINER: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX11-TO-COMBINER-NEXT: {{  $}}
    ; GFX11-TO-COMBINER-NEXT: [[COPY:%[0-9]+]]:vgpr(p1) = COPY $vgpr0_vgpr1
    ; GFX11-TO-COMBINER-NEXT: [[COPY1:%[0-9]+]]:vgpr(<2 x s16>) = COPY $vgpr2
    ; GFX11-TO-COMBINER-NEXT: [[AMDGPU_LOAD_D16_LO_U8_:%[0-9]+]]:vgpr(<2 x s16>) = G_AMDGPU_LOAD_D16_LO_U8 [[COPY]](p1), [[COPY1]] :: (load (s8), addrspace 5)
    ; GFX11-TO-COMBINER-NEXT: $vgpr0 = COPY [[AMDGPU_LOAD_D16_LO_U8_]](<2 x s16>)
    ;
    ; GFX12-TO-COMBINER-LABEL: name: test_zextload_private_s16_from_s8
    ; GFX12-TO-COMBINER: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX12-TO-COMBINER-NEXT: {{  $}}
    ; GFX12-TO-COMBINER-NEXT: [[COPY:%[0-9]+]]:vgpr(p1) = COPY $vgpr0_vgpr1
    ; GFX12-TO-COMBINER-NEXT: [[COPY1:%[0-9]+]]:vgpr(<2 x s16>) = COPY $vgpr2
    ; GFX12-TO-COMBINER-NEXT: [[AMDGPU_LOAD_D16_LO_U8_:%[0-9]+]]:vgpr(<2 x s16>) = G_AMDGPU_LOAD_D16_LO_U8 [[COPY]](p1), [[COPY1]] :: (load (s8), addrspace 5)
    ; GFX12-TO-COMBINER-NEXT: $vgpr0 = COPY [[AMDGPU_LOAD_D16_LO_U8_]](<2 x s16>)
    %0:_(p1) = COPY $vgpr0_vgpr1
    %1:_(<2 x s16>) = COPY $vgpr2
    %2:_(s16) = G_ZEXTLOAD %0 :: (load (s8), addrspace 5)
    %3:_(s32) = G_CONSTANT i32 0
    %4:_(<2 x s16>) = G_INSERT_VECTOR_ELT %1:_, %2:_(s16), %3:_(s32)
    $vgpr0 = COPY %4
...
