; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -global-isel -mtriple=amdgcn-mesa-mesa3d -mcpu=gfx900 -verify-machineinstrs -stop-after=legalizer -o - %s | FileCheck -check-prefix=GFX9 %s
; RUN: llc -global-isel -mtriple=amdgcn-mesa-mesa3d -mcpu=gfx1010 -verify-machineinstrs -stop-after=legalizer -o - %s | FileCheck -check-prefix=GFX10NSA %s
; RUN: llc -global-isel -mtriple=amdgcn-mesa-mesa3d -mcpu=gfx1100 -verify-machineinstrs -stop-after=legalizer -o - %s | FileCheck -check-prefix=GFX10NSA %s

define amdgpu_ps float @atomic_swap_1d(<8 x i32> inreg %rsrc, i32 %data, i16 %s) {
  ; GFX9-LABEL: name: atomic_swap_1d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.swap.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_swap_1d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.swap.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.swap.1d.i32.i16(i32 %data, i16 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_1d(<8 x i32> inreg %rsrc, i32 %data, i16 %s) {
  ; GFX9-LABEL: name: atomic_add_1d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_add_1d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.1d.i32.i16(i32 %data, i16 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_sub_1d(<8 x i32> inreg %rsrc, i32 %data, i16 %s) {
  ; GFX9-LABEL: name: atomic_sub_1d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.sub.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_sub_1d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.sub.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.sub.1d.i32.i16(i32 %data, i16 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_smin_1d(<8 x i32> inreg %rsrc, i32 %data, i16 %s) {
  ; GFX9-LABEL: name: atomic_smin_1d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.smin.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_smin_1d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.smin.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.smin.1d.i32.i16(i32 %data, i16 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}


define amdgpu_ps float @atomic_umin_1d(<8 x i32> inreg %rsrc, i32 %data, i16 %s) {
  ; GFX9-LABEL: name: atomic_umin_1d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.umin.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_umin_1d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.umin.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.umin.1d.i32.i16(i32 %data, i16 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_smax_1d(<8 x i32> inreg %rsrc, i32 %data, i16 %s) {
  ; GFX9-LABEL: name: atomic_smax_1d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.smax.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_smax_1d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.smax.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.smax.1d.i32.i16(i32 %data, i16 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_umax_1d(<8 x i32> inreg %rsrc, i32 %data, i16 %s) {
  ; GFX9-LABEL: name: atomic_umax_1d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.umax.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_umax_1d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.umax.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.umax.1d.i32.i16(i32 %data, i16 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_and_1d(<8 x i32> inreg %rsrc, i32 %data, i16 %s) {
  ; GFX9-LABEL: name: atomic_and_1d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.and.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_and_1d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.and.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.and.1d.i32.i16(i32 %data, i16 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_or_1d(<8 x i32> inreg %rsrc, i32 %data, i16 %s) {
  ; GFX9-LABEL: name: atomic_or_1d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.or.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_or_1d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.or.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.or.1d.i32.i16(i32 %data, i16 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_xor_1d(<8 x i32> inreg %rsrc, i32 %data, i16 %s) {
  ; GFX9-LABEL: name: atomic_xor_1d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.xor.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_xor_1d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.xor.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.xor.1d.i32.i16(i32 %data, i16 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_inc_1d(<8 x i32> inreg %rsrc, i32 %data, i16 %s) {
  ; GFX9-LABEL: name: atomic_inc_1d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.inc.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_inc_1d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.inc.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.inc.1d.i32.i16(i32 %data, i16 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_dec_1d(<8 x i32> inreg %rsrc, i32 %data, i16 %s) {
  ; GFX9-LABEL: name: atomic_dec_1d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.dec.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_dec_1d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.dec.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.dec.1d.i32.i16(i32 %data, i16 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_cmpswap_1d(<8 x i32> inreg %rsrc, i32 %cmp, i32 %swap, i16 %s) {
  ; GFX9-LABEL: name: atomic_cmpswap_1d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX9-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s32>) = G_BUILD_VECTOR [[PRED_COPY8]](s32), [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.cmpswap.1d), [[BUILD_VECTOR1]](<2 x s32>), $noreg, [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_cmpswap_1d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s32>) = G_BUILD_VECTOR [[PRED_COPY8]](s32), [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.cmpswap.1d), [[BUILD_VECTOR1]](<2 x s32>), $noreg, [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.cmpswap.1d.i32.i16(i32 %cmp, i32 %swap, i16 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_2d(<8 x i32> inreg %rsrc, i32 %data, i16 %s, i16 %t) {
  ; GFX9-LABEL: name: atomic_add_2d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX9-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX9-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.2d), [[PRED_COPY8]](s32), [[BUILD_VECTOR1]](<2 x s16>), $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_add_2d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX10NSA-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.2d), [[PRED_COPY8]](s32), [[BUILD_VECTOR1]](<2 x s16>), $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.2d.i32.i16(i32 %data, i16 %s, i16 %t, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_3d(<8 x i32> inreg %rsrc, i32 %data, i16 %s, i16 %t, i16 %r) {
  ; GFX9-LABEL: name: atomic_add_3d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX9-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX9-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX9-NEXT:   [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX9-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX9-NEXT:   [[DEF:%[0-9]+]]:_(s16) = G_IMPLICIT_DEF
  ; GFX9-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC2]](s16), [[DEF]](s16)
  ; GFX9-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<4 x s16>) = G_CONCAT_VECTORS [[BUILD_VECTOR1]](<2 x s16>), [[BUILD_VECTOR2]](<2 x s16>)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.3d), [[PRED_COPY8]](s32), [[CONCAT_VECTORS]](<4 x s16>), $noreg, $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_add_3d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX10NSA-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX10NSA-NEXT:   [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX10NSA-NEXT:   [[DEF:%[0-9]+]]:_(s16) = G_IMPLICIT_DEF
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC2]](s16), [[DEF]](s16)
  ; GFX10NSA-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<4 x s16>) = G_CONCAT_VECTORS [[BUILD_VECTOR1]](<2 x s16>), [[BUILD_VECTOR2]](<2 x s16>)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.3d), [[PRED_COPY8]](s32), [[CONCAT_VECTORS]](<4 x s16>), $noreg, $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.3d.i32.i16(i32 %data, i16 %s, i16 %t, i16 %r, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_cube(<8 x i32> inreg %rsrc, i32 %data, i16 %s, i16 %t, i16 %face) {
  ; GFX9-LABEL: name: atomic_add_cube
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX9-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX9-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX9-NEXT:   [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX9-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX9-NEXT:   [[DEF:%[0-9]+]]:_(s16) = G_IMPLICIT_DEF
  ; GFX9-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC2]](s16), [[DEF]](s16)
  ; GFX9-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<4 x s16>) = G_CONCAT_VECTORS [[BUILD_VECTOR1]](<2 x s16>), [[BUILD_VECTOR2]](<2 x s16>)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.cube), [[PRED_COPY8]](s32), [[CONCAT_VECTORS]](<4 x s16>), $noreg, $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_add_cube
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX10NSA-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX10NSA-NEXT:   [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX10NSA-NEXT:   [[DEF:%[0-9]+]]:_(s16) = G_IMPLICIT_DEF
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC2]](s16), [[DEF]](s16)
  ; GFX10NSA-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<4 x s16>) = G_CONCAT_VECTORS [[BUILD_VECTOR1]](<2 x s16>), [[BUILD_VECTOR2]](<2 x s16>)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.cube), [[PRED_COPY8]](s32), [[CONCAT_VECTORS]](<4 x s16>), $noreg, $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.cube.i32.i16(i32 %data, i16 %s, i16 %t, i16 %face, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_1darray(<8 x i32> inreg %rsrc, i32 %data, i16 %s, i16 %slice) {
  ; GFX9-LABEL: name: atomic_add_1darray
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX9-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX9-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.1darray), [[PRED_COPY8]](s32), [[BUILD_VECTOR1]](<2 x s16>), $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_add_1darray
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX10NSA-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.1darray), [[PRED_COPY8]](s32), [[BUILD_VECTOR1]](<2 x s16>), $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.1darray.i32.i16(i32 %data, i16 %s, i16 %slice, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_2darray(<8 x i32> inreg %rsrc, i32 %data, i16 %s, i16 %t, i16 %slice) {
  ; GFX9-LABEL: name: atomic_add_2darray
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX9-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX9-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX9-NEXT:   [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX9-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX9-NEXT:   [[DEF:%[0-9]+]]:_(s16) = G_IMPLICIT_DEF
  ; GFX9-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC2]](s16), [[DEF]](s16)
  ; GFX9-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<4 x s16>) = G_CONCAT_VECTORS [[BUILD_VECTOR1]](<2 x s16>), [[BUILD_VECTOR2]](<2 x s16>)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.2darray), [[PRED_COPY8]](s32), [[CONCAT_VECTORS]](<4 x s16>), $noreg, $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_add_2darray
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX10NSA-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX10NSA-NEXT:   [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX10NSA-NEXT:   [[DEF:%[0-9]+]]:_(s16) = G_IMPLICIT_DEF
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC2]](s16), [[DEF]](s16)
  ; GFX10NSA-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<4 x s16>) = G_CONCAT_VECTORS [[BUILD_VECTOR1]](<2 x s16>), [[BUILD_VECTOR2]](<2 x s16>)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.2darray), [[PRED_COPY8]](s32), [[CONCAT_VECTORS]](<4 x s16>), $noreg, $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.2darray.i32.i16(i32 %data, i16 %s, i16 %t, i16 %slice, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_2dmsaa(<8 x i32> inreg %rsrc, i32 %data, i16 %s, i16 %t, i16 %fragid) {
  ; GFX9-LABEL: name: atomic_add_2dmsaa
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX9-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX9-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX9-NEXT:   [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX9-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX9-NEXT:   [[DEF:%[0-9]+]]:_(s16) = G_IMPLICIT_DEF
  ; GFX9-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC2]](s16), [[DEF]](s16)
  ; GFX9-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<4 x s16>) = G_CONCAT_VECTORS [[BUILD_VECTOR1]](<2 x s16>), [[BUILD_VECTOR2]](<2 x s16>)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.2dmsaa), [[PRED_COPY8]](s32), [[CONCAT_VECTORS]](<4 x s16>), $noreg, $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_add_2dmsaa
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX10NSA-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX10NSA-NEXT:   [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX10NSA-NEXT:   [[DEF:%[0-9]+]]:_(s16) = G_IMPLICIT_DEF
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC2]](s16), [[DEF]](s16)
  ; GFX10NSA-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<4 x s16>) = G_CONCAT_VECTORS [[BUILD_VECTOR1]](<2 x s16>), [[BUILD_VECTOR2]](<2 x s16>)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.2dmsaa), [[PRED_COPY8]](s32), [[CONCAT_VECTORS]](<4 x s16>), $noreg, $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.2dmsaa.i32.i16(i32 %data, i16 %s, i16 %t, i16 %fragid, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_2darraymsaa(<8 x i32> inreg %rsrc, i32 %data, i16 %s, i16 %t, i16 %slice, i16 %fragid) {
  ; GFX9-LABEL: name: atomic_add_2darraymsaa
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX9-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX9-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX9-NEXT:   [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX9-NEXT:   [[PRED_COPY12:%[0-9]+]]:_(s32) = PRED_COPY $vgpr4
  ; GFX9-NEXT:   [[TRUNC3:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY12]](s32)
  ; GFX9-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX9-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC2]](s16), [[TRUNC3]](s16)
  ; GFX9-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<4 x s16>) = G_CONCAT_VECTORS [[BUILD_VECTOR1]](<2 x s16>), [[BUILD_VECTOR2]](<2 x s16>)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.2darraymsaa), [[PRED_COPY8]](s32), [[CONCAT_VECTORS]](<4 x s16>), $noreg, $noreg, $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_add_2darraymsaa
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX10NSA-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX10NSA-NEXT:   [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY12:%[0-9]+]]:_(s32) = PRED_COPY $vgpr4
  ; GFX10NSA-NEXT:   [[TRUNC3:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY12]](s32)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC2]](s16), [[TRUNC3]](s16)
  ; GFX10NSA-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<4 x s16>) = G_CONCAT_VECTORS [[BUILD_VECTOR1]](<2 x s16>), [[BUILD_VECTOR2]](<2 x s16>)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.2darraymsaa), [[PRED_COPY8]](s32), [[CONCAT_VECTORS]](<4 x s16>), $noreg, $noreg, $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.2darraymsaa.i32.i16(i32 %data, i16 %s, i16 %t, i16 %slice, i16 %fragid, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_1d_slc(<8 x i32> inreg %rsrc, i32 %data, i16 %s) {
  ; GFX9-LABEL: name: atomic_add_1d_slc
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 2, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_add_1d_slc
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.add.1d), [[PRED_COPY8]](s32), [[TRUNC]](s16), [[BUILD_VECTOR]](<8 x s32>), 0, 2, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.1d.i32.i16(i32 %data, i16 %s, <8 x i32> %rsrc, i32 0, i32 2)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_cmpswap_2d(<8 x i32> inreg %rsrc, i32 %cmp, i32 %swap, i16 %s, i16 %t) {
  ; GFX9-LABEL: name: atomic_cmpswap_2d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX9-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX9-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX9-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s32>) = G_BUILD_VECTOR [[PRED_COPY8]](s32), [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.cmpswap.2d), [[BUILD_VECTOR1]](<2 x s32>), $noreg, [[BUILD_VECTOR2]](<2 x s16>), $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_cmpswap_2d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX10NSA-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s32>) = G_BUILD_VECTOR [[PRED_COPY8]](s32), [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.cmpswap.2d), [[BUILD_VECTOR1]](<2 x s32>), $noreg, [[BUILD_VECTOR2]](<2 x s16>), $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.cmpswap.2d.i32.i16(i32 %cmp, i32 %swap, i16 %s, i16 %t, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_cmpswap_3d(<8 x i32> inreg %rsrc, i32 %cmp, i32 %swap, i16 %s, i16 %t, i16 %r) {
  ; GFX9-LABEL: name: atomic_cmpswap_3d
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX9-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX9-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX9-NEXT:   [[PRED_COPY12:%[0-9]+]]:_(s32) = PRED_COPY $vgpr4
  ; GFX9-NEXT:   [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY12]](s32)
  ; GFX9-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s32>) = G_BUILD_VECTOR [[PRED_COPY8]](s32), [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX9-NEXT:   [[DEF:%[0-9]+]]:_(s16) = G_IMPLICIT_DEF
  ; GFX9-NEXT:   [[BUILD_VECTOR3:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC2]](s16), [[DEF]](s16)
  ; GFX9-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<4 x s16>) = G_CONCAT_VECTORS [[BUILD_VECTOR2]](<2 x s16>), [[BUILD_VECTOR3]](<2 x s16>)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.cmpswap.3d), [[BUILD_VECTOR1]](<2 x s32>), $noreg, [[CONCAT_VECTORS]](<4 x s16>), $noreg, $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_cmpswap_3d
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX10NSA-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY12:%[0-9]+]]:_(s32) = PRED_COPY $vgpr4
  ; GFX10NSA-NEXT:   [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY12]](s32)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s32>) = G_BUILD_VECTOR [[PRED_COPY8]](s32), [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX10NSA-NEXT:   [[DEF:%[0-9]+]]:_(s16) = G_IMPLICIT_DEF
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR3:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC2]](s16), [[DEF]](s16)
  ; GFX10NSA-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<4 x s16>) = G_CONCAT_VECTORS [[BUILD_VECTOR2]](<2 x s16>), [[BUILD_VECTOR3]](<2 x s16>)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.cmpswap.3d), [[BUILD_VECTOR1]](<2 x s32>), $noreg, [[CONCAT_VECTORS]](<4 x s16>), $noreg, $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.cmpswap.3d.i32.i16(i32 %cmp, i32 %swap, i16 %s, i16 %t, i16 %r, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_cmpswap_2darraymsaa(<8 x i32> inreg %rsrc, i32 %cmp, i32 %swap, i16 %s, i16 %t, i16 %slice, i16 %fragid) {
  ; GFX9-LABEL: name: atomic_cmpswap_2darraymsaa
  ; GFX9: bb.1.main_body:
  ; GFX9-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX9-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX9-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX9-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX9-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX9-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX9-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX9-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX9-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX9-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX9-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX9-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX9-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX9-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX9-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX9-NEXT:   [[PRED_COPY12:%[0-9]+]]:_(s32) = PRED_COPY $vgpr4
  ; GFX9-NEXT:   [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY12]](s32)
  ; GFX9-NEXT:   [[PRED_COPY13:%[0-9]+]]:_(s32) = PRED_COPY $vgpr5
  ; GFX9-NEXT:   [[TRUNC3:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY13]](s32)
  ; GFX9-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s32>) = G_BUILD_VECTOR [[PRED_COPY8]](s32), [[PRED_COPY9]](s32)
  ; GFX9-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX9-NEXT:   [[BUILD_VECTOR3:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC2]](s16), [[TRUNC3]](s16)
  ; GFX9-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<4 x s16>) = G_CONCAT_VECTORS [[BUILD_VECTOR2]](<2 x s16>), [[BUILD_VECTOR3]](<2 x s16>)
  ; GFX9-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.cmpswap.2darraymsaa), [[BUILD_VECTOR1]](<2 x s32>), $noreg, [[CONCAT_VECTORS]](<4 x s16>), $noreg, $noreg, $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 3 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX9-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX9-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
  ; GFX10NSA-LABEL: name: atomic_cmpswap_2darraymsaa
  ; GFX10NSA: bb.1.main_body:
  ; GFX10NSA-NEXT:   liveins: $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5
  ; GFX10NSA-NEXT: {{  $}}
  ; GFX10NSA-NEXT:   [[PRED_COPY:%[0-9]+]]:_(s32) = PRED_COPY $sgpr2
  ; GFX10NSA-NEXT:   [[PRED_COPY1:%[0-9]+]]:_(s32) = PRED_COPY $sgpr3
  ; GFX10NSA-NEXT:   [[PRED_COPY2:%[0-9]+]]:_(s32) = PRED_COPY $sgpr4
  ; GFX10NSA-NEXT:   [[PRED_COPY3:%[0-9]+]]:_(s32) = PRED_COPY $sgpr5
  ; GFX10NSA-NEXT:   [[PRED_COPY4:%[0-9]+]]:_(s32) = PRED_COPY $sgpr6
  ; GFX10NSA-NEXT:   [[PRED_COPY5:%[0-9]+]]:_(s32) = PRED_COPY $sgpr7
  ; GFX10NSA-NEXT:   [[PRED_COPY6:%[0-9]+]]:_(s32) = PRED_COPY $sgpr8
  ; GFX10NSA-NEXT:   [[PRED_COPY7:%[0-9]+]]:_(s32) = PRED_COPY $sgpr9
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<8 x s32>) = G_BUILD_VECTOR [[PRED_COPY]](s32), [[PRED_COPY1]](s32), [[PRED_COPY2]](s32), [[PRED_COPY3]](s32), [[PRED_COPY4]](s32), [[PRED_COPY5]](s32), [[PRED_COPY6]](s32), [[PRED_COPY7]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY8:%[0-9]+]]:_(s32) = PRED_COPY $vgpr0
  ; GFX10NSA-NEXT:   [[PRED_COPY9:%[0-9]+]]:_(s32) = PRED_COPY $vgpr1
  ; GFX10NSA-NEXT:   [[PRED_COPY10:%[0-9]+]]:_(s32) = PRED_COPY $vgpr2
  ; GFX10NSA-NEXT:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY10]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY11:%[0-9]+]]:_(s32) = PRED_COPY $vgpr3
  ; GFX10NSA-NEXT:   [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY11]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY12:%[0-9]+]]:_(s32) = PRED_COPY $vgpr4
  ; GFX10NSA-NEXT:   [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY12]](s32)
  ; GFX10NSA-NEXT:   [[PRED_COPY13:%[0-9]+]]:_(s32) = PRED_COPY $vgpr5
  ; GFX10NSA-NEXT:   [[TRUNC3:%[0-9]+]]:_(s16) = G_TRUNC [[PRED_COPY13]](s32)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s32>) = G_BUILD_VECTOR [[PRED_COPY8]](s32), [[PRED_COPY9]](s32)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR2:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC]](s16), [[TRUNC1]](s16)
  ; GFX10NSA-NEXT:   [[BUILD_VECTOR3:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[TRUNC2]](s16), [[TRUNC3]](s16)
  ; GFX10NSA-NEXT:   [[CONCAT_VECTORS:%[0-9]+]]:_(<4 x s16>) = G_CONCAT_VECTORS [[BUILD_VECTOR2]](<2 x s16>), [[BUILD_VECTOR3]](<2 x s16>)
  ; GFX10NSA-NEXT:   [[AMDGPU_INTRIN_IMAGE_LOAD:%[0-9]+]]:_(s32) = G_AMDGPU_INTRIN_IMAGE_LOAD intrinsic(@llvm.amdgcn.image.atomic.cmpswap.2darraymsaa), [[BUILD_VECTOR1]](<2 x s32>), $noreg, [[CONCAT_VECTORS]](<4 x s16>), $noreg, $noreg, $noreg, [[BUILD_VECTOR]](<8 x s32>), 0, 0, 1 :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10NSA-NEXT:   $vgpr0 = PRED_COPY [[AMDGPU_INTRIN_IMAGE_LOAD]](s32)
  ; GFX10NSA-NEXT:   SI_RETURN_TO_EPILOG implicit $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.cmpswap.2darraymsaa.i32.i16(i32 %cmp, i32 %swap, i16 %s, i16 %t, i16 %slice, i16 %fragid, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

declare i32 @llvm.amdgcn.image.atomic.swap.1d.i32.i16(i32, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.add.1d.i32.i16(i32, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.sub.1d.i32.i16(i32, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.smin.1d.i32.i16(i32, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.umin.1d.i32.i16(i32, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.smax.1d.i32.i16(i32, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.umax.1d.i32.i16(i32, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.and.1d.i32.i16(i32, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.or.1d.i32.i16(i32, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.xor.1d.i32.i16(i32, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.inc.1d.i32.i16(i32, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.dec.1d.i32.i16(i32, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.cmpswap.1d.i32.i16(i32, i32, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.add.2d.i32.i16(i32, i16, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.add.3d.i32.i16(i32, i16, i16, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.add.cube.i32.i16(i32, i16, i16, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.add.1darray.i32.i16(i32, i16, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.add.2darray.i32.i16(i32, i16, i16, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.add.2dmsaa.i32.i16(i32, i16, i16, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.add.2darraymsaa.i32.i16(i32, i16, i16, i16, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.cmpswap.2d.i32.i16(i32, i32, i16, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.cmpswap.3d.i32.i16(i32, i32, i16, i16, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.cmpswap.cube.i32.i16(i32, i32, i16, i16, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.cmpswap.1darray.i32.i16(i32, i32, i16, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.cmpswap.2darray.i32.i16(i32, i32, i16, i16, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.cmpswap.2dmsaa.i32.i16(i32, i32, i16, i16, i16, <8 x i32>, i32 immarg, i32 immarg) #0
declare i32 @llvm.amdgcn.image.atomic.cmpswap.2darraymsaa.i32.i16(i32, i32, i16, i16, i16, i16, <8 x i32>, i32 immarg, i32 immarg) #0

attributes #0 = { nounwind }
