# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-mesa-mesa3d -mcpu=tahiti -O0 -run-pass=legalizer %s -o - | FileCheck -check-prefix=GCN  %s
# RUN: llc -mtriple=amdgcn-mesa-mesa3d -mcpu=fiji -O0 -run-pass=legalizer %s -o - | FileCheck -check-prefix=GCN  %s

---
name: test_fconstant_s32
body: |
  bb.0:

    ; GCN-LABEL: name: test_fconstant_s32
    ; GCN: [[C:%[0-9]+]]:_(f32) = G_FCONSTANT float 1.000000e+00
    ; GCN-NEXT: [[BITCAST:%[0-9]+]]:_(i32) = G_BITCAST [[C]](f32)
    ; GCN-NEXT: $vgpr0 = COPY [[BITCAST]](i32)
    %0:_(f32) = G_FCONSTANT float 1.000000e+00
    %1:_(i32) = G_BITCAST %0(f32)
    $vgpr0 = COPY %1(i32)
...
---
name: test_fconstant_s64
body: |
  bb.0:

    ; GCN-LABEL: name: test_fconstant_s64
    ; GCN: [[C:%[0-9]+]]:_(f64) = G_FCONSTANT double 1.000000e+00
    ; GCN-NEXT: [[BITCAST:%[0-9]+]]:_(i64) = G_BITCAST [[C]](f64)
    ; GCN-NEXT: $vgpr0_vgpr1 = COPY [[BITCAST]](i64)
    %0:_(f64) = G_FCONSTANT double 1.000000e+00
    %1:_(i64) = G_BITCAST %0(f64)
    $vgpr0_vgpr1 = COPY %1(i64)
...

---
name: test_fconstant_s16
body: |
  bb.0:

    ; GCN-LABEL: name: test_fconstant_s16
    ; GCN: [[C:%[0-9]+]]:_(f16) = G_FCONSTANT half 0xH3C00
    ; GCN-NEXT: [[BITCAST:%[0-9]+]]:_(i16) = G_BITCAST [[C]](f16)
    ; GCN-NEXT: [[ANYEXT:%[0-9]+]]:_(i32) = G_ANYEXT [[BITCAST]](i16)
    ; GCN-NEXT: $vgpr0 = COPY [[ANYEXT]](i32)
    %0:_(f16) = G_FCONSTANT half 0xH3C00
    %1:_(i16) = G_BITCAST %0(f16)
    %2:_(i32) = G_ANYEXT %1(i16)
    $vgpr0 = COPY %2(i32)
...
