# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-mesa-mesa3d -mcpu=tahiti -O0 -run-pass=legalizer %s -o - | FileCheck %s
# RUN: llc -mtriple=amdgcn-mesa-mesa3d -mcpu=fiji -O0 -run-pass=legalizer %s -o - | FileCheck %s

---
name: atomicrmw_umin_global_i32

body: |
  bb.0:
    liveins: $sgpr0_sgpr1, $sgpr2
    ; CHECK-LABEL: name: atomicrmw_umin_global_i32
    ; CHECK: liveins: $sgpr0_sgpr1, $sgpr2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $sgpr0_sgpr1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(i32) = COPY $sgpr2
    ; CHECK-NEXT: [[ATOMICRMW_UMIN:%[0-9]+]]:_(i32) = G_ATOMICRMW_UMIN [[COPY]](p1), [[COPY1]] :: (load store seq_cst (i32), addrspace 1)
    %0:_(p1) = COPY $sgpr0_sgpr1
    %1:_(i32) = COPY $sgpr2
    %2:_(i32) = G_ATOMICRMW_UMIN %0(p1), %1 :: (load store seq_cst (i32), addrspace 1)
...

---
name: atomicrmw_umin_local_i32

body: |
  bb.0:
    liveins: $sgpr0, $sgpr1
    ; CHECK-LABEL: name: atomicrmw_umin_local_i32
    ; CHECK: liveins: $sgpr0, $sgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $sgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(i32) = COPY $sgpr1
    ; CHECK-NEXT: [[ATOMICRMW_UMIN:%[0-9]+]]:_(i32) = G_ATOMICRMW_UMIN [[COPY]](p3), [[COPY1]] :: (load store seq_cst (i32), addrspace 3)
    %0:_(p3) = COPY $sgpr0
    %1:_(i32) = COPY $sgpr1
    %2:_(i32) = G_ATOMICRMW_UMIN %0(p3), %1 :: (load store seq_cst (i32), addrspace 3)
...

---
name: atomicrmw_umin_global_i64

body: |
  bb.0:
    liveins: $sgpr0_sgpr1, $sgpr2
    ; CHECK-LABEL: name: atomicrmw_umin_global_i64
    ; CHECK: liveins: $sgpr0_sgpr1, $sgpr2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $sgpr0_sgpr1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(i32) = COPY $sgpr2
    ; CHECK-NEXT: [[ATOMICRMW_UMIN:%[0-9]+]]:_(i32) = G_ATOMICRMW_UMIN [[COPY]](p1), [[COPY1]] :: (load store seq_cst (i32), addrspace 1)
    %0:_(p1) = COPY $sgpr0_sgpr1
    %1:_(i32) = COPY $sgpr2
    %2:_(i32) = G_ATOMICRMW_UMIN %0(p1), %1 :: (load store seq_cst (i32), addrspace 1)
...

---
name: atomicrmw_umin_local_i64

body: |
  bb.0:
    liveins: $sgpr0, $sgpr1
    ; CHECK-LABEL: name: atomicrmw_umin_local_i64
    ; CHECK: liveins: $sgpr0, $sgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $sgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(i32) = COPY $sgpr1
    ; CHECK-NEXT: [[ATOMICRMW_UMIN:%[0-9]+]]:_(i32) = G_ATOMICRMW_UMIN [[COPY]](p3), [[COPY1]] :: (load store seq_cst (i32), addrspace 3)
    %0:_(p3) = COPY $sgpr0
    %1:_(i32) = COPY $sgpr1
    %2:_(i32) = G_ATOMICRMW_UMIN %0(p3), %1 :: (load store seq_cst (i32), addrspace 3)
...
