# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1200 -mattr=+real-true16 -run-pass=legalizer %s -o - | FileCheck --check-prefixes=TRUE16 %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1200 -mattr=-real-true16 -run-pass=legalizer %s -o - | FileCheck --check-prefixes=FAKE16 %s

---
name: test_sextload_global_s16_from_s8
body: |
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2

    ; TRUE16-LABEL: name: test_sextload_global_s16_from_s8
    ; TRUE16: liveins: $vgpr0_vgpr1, $vgpr2
    ; TRUE16-NEXT: {{  $}}
    ; TRUE16-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; TRUE16-NEXT: [[COPY1:%[0-9]+]]:_(p5) = COPY $vgpr2
    ; TRUE16-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s16) = G_SEXTLOAD [[COPY1]](p5) :: (load (s8), addrspace 5)
    ; TRUE16-NEXT: G_STORE [[SEXTLOAD]](s16), [[COPY]](p1) :: (store (s16), addrspace 1)
    ;
    ; FAKE16-LABEL: name: test_sextload_global_s16_from_s8
    ; FAKE16: liveins: $vgpr0_vgpr1, $vgpr2
    ; FAKE16-NEXT: {{  $}}
    ; FAKE16-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; FAKE16-NEXT: [[COPY1:%[0-9]+]]:_(p5) = COPY $vgpr2
    ; FAKE16-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[COPY1]](p5) :: (load (s8), addrspace 5)
    ; FAKE16-NEXT: G_STORE [[SEXTLOAD]](s32), [[COPY]](p1) :: (store (s16), addrspace 1)
    %0:_(p1) = COPY $vgpr0_vgpr1
    %1:_(p5) = COPY $vgpr2
    %2:_(s16) = G_SEXTLOAD %1 :: (load (s8), addrspace 5)
    G_STORE %2(s16), %0(p1) :: (store (s16), addrspace 1)
...

---
name: test_sextload_local_s16_from_s8
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1

    ; TRUE16-LABEL: name: test_sextload_local_s16_from_s8
    ; TRUE16: liveins: $vgpr0, $vgpr1
    ; TRUE16-NEXT: {{  $}}
    ; TRUE16-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $vgpr0
    ; TRUE16-NEXT: [[COPY1:%[0-9]+]]:_(p5) = COPY $vgpr1
    ; TRUE16-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s16) = G_SEXTLOAD [[COPY1]](p5) :: (load (s8), addrspace 5)
    ; TRUE16-NEXT: G_STORE [[SEXTLOAD]](s16), [[COPY]](p3) :: (store (s16), addrspace 3)
    ;
    ; FAKE16-LABEL: name: test_sextload_local_s16_from_s8
    ; FAKE16: liveins: $vgpr0, $vgpr1
    ; FAKE16-NEXT: {{  $}}
    ; FAKE16-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $vgpr0
    ; FAKE16-NEXT: [[COPY1:%[0-9]+]]:_(p5) = COPY $vgpr1
    ; FAKE16-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[COPY1]](p5) :: (load (s8), addrspace 5)
    ; FAKE16-NEXT: G_STORE [[SEXTLOAD]](s32), [[COPY]](p3) :: (store (s16), addrspace 3)
    %0:_(p3) = COPY $vgpr0
    %1:_(p5) = COPY $vgpr1
    %2:_(s16) = G_SEXTLOAD %1 :: (load (s8), addrspace 5)
    G_STORE %2(s16), %0(p3) :: (store (s16), addrspace 3)
...

---
name: test_sextload_private_s16_from_s8
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1

    ; TRUE16-LABEL: name: test_sextload_private_s16_from_s8
    ; TRUE16: liveins: $vgpr0, $vgpr1
    ; TRUE16-NEXT: {{  $}}
    ; TRUE16-NEXT: [[COPY:%[0-9]+]]:_(p5) = COPY $vgpr0
    ; TRUE16-NEXT: [[COPY1:%[0-9]+]]:_(p5) = COPY $vgpr1
    ; TRUE16-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s16) = G_SEXTLOAD [[COPY1]](p5) :: (load (s8), addrspace 5)
    ; TRUE16-NEXT: G_STORE [[SEXTLOAD]](s16), [[COPY]](p5) :: (store (s16), addrspace 5)
    ;
    ; FAKE16-LABEL: name: test_sextload_private_s16_from_s8
    ; FAKE16: liveins: $vgpr0, $vgpr1
    ; FAKE16-NEXT: {{  $}}
    ; FAKE16-NEXT: [[COPY:%[0-9]+]]:_(p5) = COPY $vgpr0
    ; FAKE16-NEXT: [[COPY1:%[0-9]+]]:_(p5) = COPY $vgpr1
    ; FAKE16-NEXT: [[SEXTLOAD:%[0-9]+]]:_(s32) = G_SEXTLOAD [[COPY1]](p5) :: (load (s8), addrspace 5)
    ; FAKE16-NEXT: G_STORE [[SEXTLOAD]](s32), [[COPY]](p5) :: (store (s16), addrspace 5)
    %0:_(p5) = COPY $vgpr0
    %1:_(p5) = COPY $vgpr1
    %2:_(s16) = G_SEXTLOAD %1 :: (load (s8), addrspace 5)
    G_STORE %2(s16), %0(p5) :: (store (s16), addrspace 5)
...
