# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 -mattr=+real-true16 -run-pass=legalizer %s -o - | FileCheck -check-prefix=GFX11,GFX11-TRUE16 %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 -mattr=-real-true16 -run-pass=legalizer %s -o - | FileCheck -check-prefix=GFX11,GFX11-FAKE16 %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1200 -mattr=+real-true16 -run-pass=legalizer %s -o - | FileCheck -check-prefix=GFX12,GFX12-TRUE16 %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1200 -mattr=-real-true16 -run-pass=legalizer %s -o - | FileCheck -check-prefix=GFX12,GFX12-FAKE16 %s

---
name: test_extload_global_s16_from_s8
body: |
  bb.0:
    liveins: $vgpr0_vgpr1

    ; GFX11-LABEL: name: test_extload_global_s16_from_s8
    ; GFX11: liveins: $vgpr0_vgpr1
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX11-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p1) :: (load (s8), addrspace 1)
    ; GFX11-NEXT: $vgpr0 = COPY [[LOAD]](s32)
    ;
    ; GFX12-LABEL: name: test_extload_global_s16_from_s8
    ; GFX12: liveins: $vgpr0_vgpr1
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX12-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p1) :: (load (s8), addrspace 1)
    ; GFX12-NEXT: $vgpr0 = COPY [[LOAD]](s32)
    %0:_(p1) = COPY $vgpr0_vgpr1
    %1:_(s16) = G_LOAD %0 :: (load (s8), addrspace 1)
    %2:_(s32) = G_ANYEXT %1
    $vgpr0 = COPY %2
...

---
name: test_sextload_global_s16_from_s8
body: |
  bb.0:
    liveins: $vgpr0_vgpr1

    ; GFX11-LABEL: name: test_sextload_global_s16_from_s8
    ; GFX11: liveins: $vgpr0_vgpr1
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX11-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p1) :: (load (s8), addrspace 1)
    ; GFX11-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[LOAD]], 16
    ; GFX11-NEXT: $vgpr0 = COPY [[SEXT_INREG]](s32)
    ;
    ; GFX12-LABEL: name: test_sextload_global_s16_from_s8
    ; GFX12: liveins: $vgpr0_vgpr1
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX12-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p1) :: (load (s8), addrspace 1)
    ; GFX12-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[LOAD]], 16
    ; GFX12-NEXT: $vgpr0 = COPY [[SEXT_INREG]](s32)
    %0:_(p1) = COPY $vgpr0_vgpr1
    %1:_(s16) = G_LOAD %0 :: (load (s8), addrspace 1)
    %2:_(s32) = G_SEXT %1
    $vgpr0 = COPY %2
...

---
name: test_zextload_global_s16_from_s8
body: |
  bb.0:
    liveins: $vgpr0_vgpr1

    ; GFX11-LABEL: name: test_zextload_global_s16_from_s8
    ; GFX11: liveins: $vgpr0_vgpr1
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX11-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p1) :: (load (s8), addrspace 1)
    ; GFX11-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; GFX11-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[LOAD]], [[C]]
    ; GFX11-NEXT: $vgpr0 = COPY [[AND]](s32)
    ;
    ; GFX12-LABEL: name: test_zextload_global_s16_from_s8
    ; GFX12: liveins: $vgpr0_vgpr1
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX12-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p1) :: (load (s8), addrspace 1)
    ; GFX12-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; GFX12-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[LOAD]], [[C]]
    ; GFX12-NEXT: $vgpr0 = COPY [[AND]](s32)
    %0:_(p1) = COPY $vgpr0_vgpr1
    %1:_(s16) = G_LOAD %0 :: (load (s8), addrspace 1)
    %2:_(s32) = G_ZEXT %1
    $vgpr0 = COPY %2
...

---
name: test_load_global_s16_from_s16
body: |
  bb.0:
    liveins: $vgpr0_vgpr1

    ; GFX11-TRUE16-LABEL: name: test_load_global_s16_from_s16
    ; GFX11-TRUE16: liveins: $vgpr0_vgpr1
    ; GFX11-TRUE16-NEXT: {{  $}}
    ; GFX11-TRUE16-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX11-TRUE16-NEXT: [[LOAD:%[0-9]+]]:_(s16) = G_LOAD [[COPY]](p1) :: (load (s16), addrspace 1)
    ; GFX11-TRUE16-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[LOAD]](s16)
    ; GFX11-TRUE16-NEXT: $vgpr0 = COPY [[ANYEXT]](s32)
    ;
    ; GFX11-FAKE16-LABEL: name: test_load_global_s16_from_s16
    ; GFX11-FAKE16: liveins: $vgpr0_vgpr1
    ; GFX11-FAKE16-NEXT: {{  $}}
    ; GFX11-FAKE16-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX11-FAKE16-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p1) :: (load (s16), addrspace 1)
    ; GFX11-FAKE16-NEXT: $vgpr0 = COPY [[LOAD]](s32)
    ;
    ; GFX12-TRUE16-LABEL: name: test_load_global_s16_from_s16
    ; GFX12-TRUE16: liveins: $vgpr0_vgpr1
    ; GFX12-TRUE16-NEXT: {{  $}}
    ; GFX12-TRUE16-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX12-TRUE16-NEXT: [[LOAD:%[0-9]+]]:_(s16) = G_LOAD [[COPY]](p1) :: (load (s16), addrspace 1)
    ; GFX12-TRUE16-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[LOAD]](s16)
    ; GFX12-TRUE16-NEXT: $vgpr0 = COPY [[ANYEXT]](s32)
    ;
    ; GFX12-FAKE16-LABEL: name: test_load_global_s16_from_s16
    ; GFX12-FAKE16: liveins: $vgpr0_vgpr1
    ; GFX12-FAKE16-NEXT: {{  $}}
    ; GFX12-FAKE16-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX12-FAKE16-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p1) :: (load (s16), addrspace 1)
    ; GFX12-FAKE16-NEXT: $vgpr0 = COPY [[LOAD]](s32)
    %0:_(p1) = COPY $vgpr0_vgpr1
    %1:_(s16) = G_LOAD %0 :: (load (s16), addrspace 1)
    %2:_(s32) = G_ANYEXT %1
    $vgpr0 = COPY %2
...

---
name: test_truncstore_global_s16_to_s8
body: |
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2

    ; GFX11-LABEL: name: test_truncstore_global_s16_to_s8
    ; GFX11: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX11-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr2
    ; GFX11-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p1) :: (store (s8), addrspace 1)
    ; GFX11-NEXT: S_ENDPGM 0
    ;
    ; GFX12-LABEL: name: test_truncstore_global_s16_to_s8
    ; GFX12: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX12-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr2
    ; GFX12-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p1) :: (store (s8), addrspace 1)
    ; GFX12-NEXT: S_ENDPGM 0
    %0:_(p1) = COPY $vgpr0_vgpr1
    %1:_(s32) = COPY $vgpr2
    %2:_(s16) = G_TRUNC %1
    G_STORE %2, %0 :: (store (s8), addrspace 1)
    S_ENDPGM 0
...

---
name: test_store_global_s16_to_s16
body: |
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2

    ; GFX11-TRUE16-LABEL: name: test_store_global_s16_to_s16
    ; GFX11-TRUE16: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX11-TRUE16-NEXT: {{  $}}
    ; GFX11-TRUE16-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX11-TRUE16-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr2
    ; GFX11-TRUE16-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY1]](s32)
    ; GFX11-TRUE16-NEXT: G_STORE [[TRUNC]](s16), [[COPY]](p1) :: (store (s16), addrspace 1)
    ; GFX11-TRUE16-NEXT: S_ENDPGM 0
    ;
    ; GFX11-FAKE16-LABEL: name: test_store_global_s16_to_s16
    ; GFX11-FAKE16: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX11-FAKE16-NEXT: {{  $}}
    ; GFX11-FAKE16-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX11-FAKE16-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr2
    ; GFX11-FAKE16-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p1) :: (store (s16), addrspace 1)
    ; GFX11-FAKE16-NEXT: S_ENDPGM 0
    ;
    ; GFX12-TRUE16-LABEL: name: test_store_global_s16_to_s16
    ; GFX12-TRUE16: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX12-TRUE16-NEXT: {{  $}}
    ; GFX12-TRUE16-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX12-TRUE16-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr2
    ; GFX12-TRUE16-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY1]](s32)
    ; GFX12-TRUE16-NEXT: G_STORE [[TRUNC]](s16), [[COPY]](p1) :: (store (s16), addrspace 1)
    ; GFX12-TRUE16-NEXT: S_ENDPGM 0
    ;
    ; GFX12-FAKE16-LABEL: name: test_store_global_s16_to_s16
    ; GFX12-FAKE16: liveins: $vgpr0_vgpr1, $vgpr2
    ; GFX12-FAKE16-NEXT: {{  $}}
    ; GFX12-FAKE16-NEXT: [[COPY:%[0-9]+]]:_(p1) = COPY $vgpr0_vgpr1
    ; GFX12-FAKE16-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr2
    ; GFX12-FAKE16-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p1) :: (store (s16), addrspace 1)
    ; GFX12-FAKE16-NEXT: S_ENDPGM 0
    %0:_(p1) = COPY $vgpr0_vgpr1
    %1:_(s32) = COPY $vgpr2
    %2:_(s16) = G_TRUNC %1
    G_STORE %2, %0 :: (store (s16), addrspace 1)
    S_ENDPGM 0
...

---
name: test_extload_local_s16_from_s8
body: |
  bb.0:
    liveins: $vgpr0

    ; GFX11-LABEL: name: test_extload_local_s16_from_s8
    ; GFX11: liveins: $vgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $vgpr0
    ; GFX11-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p3) :: (load (s8), addrspace 3)
    ; GFX11-NEXT: $vgpr0 = COPY [[LOAD]](s32)
    ;
    ; GFX12-LABEL: name: test_extload_local_s16_from_s8
    ; GFX12: liveins: $vgpr0
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $vgpr0
    ; GFX12-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p3) :: (load (s8), addrspace 3)
    ; GFX12-NEXT: $vgpr0 = COPY [[LOAD]](s32)
    %0:_(p3) = COPY $vgpr0
    %1:_(s16) = G_LOAD %0 :: (load (s8), addrspace 3)
    %2:_(s32) = G_ANYEXT %1
    $vgpr0 = COPY %2
...

---
name: test_load_local_s16_from_s16
body: |
  bb.0:
    liveins: $vgpr0

    ; GFX11-TRUE16-LABEL: name: test_load_local_s16_from_s16
    ; GFX11-TRUE16: liveins: $vgpr0
    ; GFX11-TRUE16-NEXT: {{  $}}
    ; GFX11-TRUE16-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $vgpr0
    ; GFX11-TRUE16-NEXT: [[LOAD:%[0-9]+]]:_(s16) = G_LOAD [[COPY]](p3) :: (load (s16), addrspace 3)
    ; GFX11-TRUE16-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[LOAD]](s16)
    ; GFX11-TRUE16-NEXT: $vgpr0 = COPY [[ANYEXT]](s32)
    ;
    ; GFX11-FAKE16-LABEL: name: test_load_local_s16_from_s16
    ; GFX11-FAKE16: liveins: $vgpr0
    ; GFX11-FAKE16-NEXT: {{  $}}
    ; GFX11-FAKE16-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $vgpr0
    ; GFX11-FAKE16-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p3) :: (load (s16), addrspace 3)
    ; GFX11-FAKE16-NEXT: $vgpr0 = COPY [[LOAD]](s32)
    ;
    ; GFX12-TRUE16-LABEL: name: test_load_local_s16_from_s16
    ; GFX12-TRUE16: liveins: $vgpr0
    ; GFX12-TRUE16-NEXT: {{  $}}
    ; GFX12-TRUE16-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $vgpr0
    ; GFX12-TRUE16-NEXT: [[LOAD:%[0-9]+]]:_(s16) = G_LOAD [[COPY]](p3) :: (load (s16), addrspace 3)
    ; GFX12-TRUE16-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[LOAD]](s16)
    ; GFX12-TRUE16-NEXT: $vgpr0 = COPY [[ANYEXT]](s32)
    ;
    ; GFX12-FAKE16-LABEL: name: test_load_local_s16_from_s16
    ; GFX12-FAKE16: liveins: $vgpr0
    ; GFX12-FAKE16-NEXT: {{  $}}
    ; GFX12-FAKE16-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $vgpr0
    ; GFX12-FAKE16-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p3) :: (load (s16), addrspace 3)
    ; GFX12-FAKE16-NEXT: $vgpr0 = COPY [[LOAD]](s32)
    %0:_(p3) = COPY $vgpr0
    %1:_(s16) = G_LOAD %0 :: (load (s16), addrspace 3)
    %2:_(s32) = G_ANYEXT %1
    $vgpr0 = COPY %2
...

---
name: test_truncstore_local_s16_to_s8
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1

    ; GFX11-LABEL: name: test_truncstore_local_s16_to_s8
    ; GFX11: liveins: $vgpr0, $vgpr1
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $vgpr0
    ; GFX11-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX11-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p3) :: (store (s8), addrspace 3)
    ; GFX11-NEXT: S_ENDPGM 0
    ;
    ; GFX12-LABEL: name: test_truncstore_local_s16_to_s8
    ; GFX12: liveins: $vgpr0, $vgpr1
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $vgpr0
    ; GFX12-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX12-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p3) :: (store (s8), addrspace 3)
    ; GFX12-NEXT: S_ENDPGM 0
    %0:_(p3) = COPY $vgpr0
    %1:_(s32) = COPY $vgpr1
    %2:_(s16) = G_TRUNC %1
    G_STORE %2, %0 :: (store (s8), addrspace 3)
    S_ENDPGM 0
...

---
name: test_store_local_s16_to_s16
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1

    ; GFX11-TRUE16-LABEL: name: test_store_local_s16_to_s16
    ; GFX11-TRUE16: liveins: $vgpr0, $vgpr1
    ; GFX11-TRUE16-NEXT: {{  $}}
    ; GFX11-TRUE16-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $vgpr0
    ; GFX11-TRUE16-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX11-TRUE16-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY1]](s32)
    ; GFX11-TRUE16-NEXT: G_STORE [[TRUNC]](s16), [[COPY]](p3) :: (store (s16), addrspace 3)
    ; GFX11-TRUE16-NEXT: S_ENDPGM 0
    ;
    ; GFX11-FAKE16-LABEL: name: test_store_local_s16_to_s16
    ; GFX11-FAKE16: liveins: $vgpr0, $vgpr1
    ; GFX11-FAKE16-NEXT: {{  $}}
    ; GFX11-FAKE16-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $vgpr0
    ; GFX11-FAKE16-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX11-FAKE16-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p3) :: (store (s16), addrspace 3)
    ; GFX11-FAKE16-NEXT: S_ENDPGM 0
    ;
    ; GFX12-TRUE16-LABEL: name: test_store_local_s16_to_s16
    ; GFX12-TRUE16: liveins: $vgpr0, $vgpr1
    ; GFX12-TRUE16-NEXT: {{  $}}
    ; GFX12-TRUE16-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $vgpr0
    ; GFX12-TRUE16-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX12-TRUE16-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY1]](s32)
    ; GFX12-TRUE16-NEXT: G_STORE [[TRUNC]](s16), [[COPY]](p3) :: (store (s16), addrspace 3)
    ; GFX12-TRUE16-NEXT: S_ENDPGM 0
    ;
    ; GFX12-FAKE16-LABEL: name: test_store_local_s16_to_s16
    ; GFX12-FAKE16: liveins: $vgpr0, $vgpr1
    ; GFX12-FAKE16-NEXT: {{  $}}
    ; GFX12-FAKE16-NEXT: [[COPY:%[0-9]+]]:_(p3) = COPY $vgpr0
    ; GFX12-FAKE16-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX12-FAKE16-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p3) :: (store (s16), addrspace 3)
    ; GFX12-FAKE16-NEXT: S_ENDPGM 0
    %0:_(p3) = COPY $vgpr0
    %1:_(s32) = COPY $vgpr1
    %2:_(s16) = G_TRUNC %1
    G_STORE %2, %0 :: (store (s16), addrspace 3)
    S_ENDPGM 0
...

---
name: test_extload_private_s16_from_s8
body: |
  bb.0:
    liveins: $vgpr0

    ; GFX11-LABEL: name: test_extload_private_s16_from_s8
    ; GFX11: liveins: $vgpr0
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:_(p5) = COPY $vgpr0
    ; GFX11-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p5) :: (load (s8), addrspace 5)
    ; GFX11-NEXT: $vgpr0 = COPY [[LOAD]](s32)
    ;
    ; GFX12-LABEL: name: test_extload_private_s16_from_s8
    ; GFX12: liveins: $vgpr0
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:_(p5) = COPY $vgpr0
    ; GFX12-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p5) :: (load (s8), addrspace 5)
    ; GFX12-NEXT: $vgpr0 = COPY [[LOAD]](s32)
    %0:_(p5) = COPY $vgpr0
    %1:_(s16) = G_LOAD %0 :: (load (s8), addrspace 5)
    %2:_(s32) = G_ANYEXT %1
    $vgpr0 = COPY %2
...

---
name: test_load_private_s16_from_s16
body: |
  bb.0:
    liveins: $vgpr0

    ; GFX11-TRUE16-LABEL: name: test_load_private_s16_from_s16
    ; GFX11-TRUE16: liveins: $vgpr0
    ; GFX11-TRUE16-NEXT: {{  $}}
    ; GFX11-TRUE16-NEXT: [[COPY:%[0-9]+]]:_(p5) = COPY $vgpr0
    ; GFX11-TRUE16-NEXT: [[LOAD:%[0-9]+]]:_(s16) = G_LOAD [[COPY]](p5) :: (load (s16), addrspace 5)
    ; GFX11-TRUE16-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[LOAD]](s16)
    ; GFX11-TRUE16-NEXT: $vgpr0 = COPY [[ANYEXT]](s32)
    ;
    ; GFX11-FAKE16-LABEL: name: test_load_private_s16_from_s16
    ; GFX11-FAKE16: liveins: $vgpr0
    ; GFX11-FAKE16-NEXT: {{  $}}
    ; GFX11-FAKE16-NEXT: [[COPY:%[0-9]+]]:_(p5) = COPY $vgpr0
    ; GFX11-FAKE16-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p5) :: (load (s16), addrspace 5)
    ; GFX11-FAKE16-NEXT: $vgpr0 = COPY [[LOAD]](s32)
    ;
    ; GFX12-TRUE16-LABEL: name: test_load_private_s16_from_s16
    ; GFX12-TRUE16: liveins: $vgpr0
    ; GFX12-TRUE16-NEXT: {{  $}}
    ; GFX12-TRUE16-NEXT: [[COPY:%[0-9]+]]:_(p5) = COPY $vgpr0
    ; GFX12-TRUE16-NEXT: [[LOAD:%[0-9]+]]:_(s16) = G_LOAD [[COPY]](p5) :: (load (s16), addrspace 5)
    ; GFX12-TRUE16-NEXT: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[LOAD]](s16)
    ; GFX12-TRUE16-NEXT: $vgpr0 = COPY [[ANYEXT]](s32)
    ;
    ; GFX12-FAKE16-LABEL: name: test_load_private_s16_from_s16
    ; GFX12-FAKE16: liveins: $vgpr0
    ; GFX12-FAKE16-NEXT: {{  $}}
    ; GFX12-FAKE16-NEXT: [[COPY:%[0-9]+]]:_(p5) = COPY $vgpr0
    ; GFX12-FAKE16-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p5) :: (load (s16), addrspace 5)
    ; GFX12-FAKE16-NEXT: $vgpr0 = COPY [[LOAD]](s32)
    %0:_(p5) = COPY $vgpr0
    %1:_(s16) = G_LOAD %0 :: (load (s16), addrspace 5)
    %2:_(s32) = G_ANYEXT %1
    $vgpr0 = COPY %2
...

---
name: test_truncstore_private_s16_to_s8
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1

    ; GFX11-LABEL: name: test_truncstore_private_s16_to_s8
    ; GFX11: liveins: $vgpr0, $vgpr1
    ; GFX11-NEXT: {{  $}}
    ; GFX11-NEXT: [[COPY:%[0-9]+]]:_(p5) = COPY $vgpr0
    ; GFX11-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX11-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p5) :: (store (s8), addrspace 5)
    ; GFX11-NEXT: S_ENDPGM 0
    ;
    ; GFX12-LABEL: name: test_truncstore_private_s16_to_s8
    ; GFX12: liveins: $vgpr0, $vgpr1
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:_(p5) = COPY $vgpr0
    ; GFX12-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX12-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p5) :: (store (s8), addrspace 5)
    ; GFX12-NEXT: S_ENDPGM 0
    %0:_(p5) = COPY $vgpr0
    %1:_(s32) = COPY $vgpr1
    %2:_(s16) = G_TRUNC %1
    G_STORE %2, %0 :: (store (s8), addrspace 5)
    S_ENDPGM 0
...

---
name: test_store_private_s16_to_s16
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1

    ; GFX11-TRUE16-LABEL: name: test_store_private_s16_to_s16
    ; GFX11-TRUE16: liveins: $vgpr0, $vgpr1
    ; GFX11-TRUE16-NEXT: {{  $}}
    ; GFX11-TRUE16-NEXT: [[COPY:%[0-9]+]]:_(p5) = COPY $vgpr0
    ; GFX11-TRUE16-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX11-TRUE16-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY1]](s32)
    ; GFX11-TRUE16-NEXT: G_STORE [[TRUNC]](s16), [[COPY]](p5) :: (store (s16), addrspace 5)
    ; GFX11-TRUE16-NEXT: S_ENDPGM 0
    ;
    ; GFX11-FAKE16-LABEL: name: test_store_private_s16_to_s16
    ; GFX11-FAKE16: liveins: $vgpr0, $vgpr1
    ; GFX11-FAKE16-NEXT: {{  $}}
    ; GFX11-FAKE16-NEXT: [[COPY:%[0-9]+]]:_(p5) = COPY $vgpr0
    ; GFX11-FAKE16-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX11-FAKE16-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p5) :: (store (s16), addrspace 5)
    ; GFX11-FAKE16-NEXT: S_ENDPGM 0
    ;
    ; GFX12-TRUE16-LABEL: name: test_store_private_s16_to_s16
    ; GFX12-TRUE16: liveins: $vgpr0, $vgpr1
    ; GFX12-TRUE16-NEXT: {{  $}}
    ; GFX12-TRUE16-NEXT: [[COPY:%[0-9]+]]:_(p5) = COPY $vgpr0
    ; GFX12-TRUE16-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX12-TRUE16-NEXT: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY1]](s32)
    ; GFX12-TRUE16-NEXT: G_STORE [[TRUNC]](s16), [[COPY]](p5) :: (store (s16), addrspace 5)
    ; GFX12-TRUE16-NEXT: S_ENDPGM 0
    ;
    ; GFX12-FAKE16-LABEL: name: test_store_private_s16_to_s16
    ; GFX12-FAKE16: liveins: $vgpr0, $vgpr1
    ; GFX12-FAKE16-NEXT: {{  $}}
    ; GFX12-FAKE16-NEXT: [[COPY:%[0-9]+]]:_(p5) = COPY $vgpr0
    ; GFX12-FAKE16-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $vgpr1
    ; GFX12-FAKE16-NEXT: G_STORE [[COPY1]](s32), [[COPY]](p5) :: (store (s16), addrspace 5)
    ; GFX12-FAKE16-NEXT: S_ENDPGM 0
    %0:_(p5) = COPY $vgpr0
    %1:_(s32) = COPY $vgpr1
    %2:_(s16) = G_TRUNC %1
    G_STORE %2, %0 :: (store (s16), addrspace 5)
    S_ENDPGM 0
...
