; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -global-isel=0 -amdgpu-load-store-vectorizer=0 -mtriple=amdgcn -mcpu=gfx1300 -verify-machineinstrs < %s | FileCheck -check-prefix=GFX13-SDAG %s
; RUN: llc -global-isel=1 -amdgpu-load-store-vectorizer=0 -mtriple=amdgcn -mcpu=gfx1300 -verify-machineinstrs < %s | FileCheck -check-prefix=GFX13-GISEL %s

define amdgpu_kernel void @v_wave_match_sgpr(ptr addrspace(1) %out, i32 %src) {
; GFX13-SDAG-LABEL: v_wave_match_sgpr:
; GFX13-SDAG:       ; %bb.0:
; GFX13-SDAG-NEXT:    s_load_b96 s[0:2], s[2:3], 0x24
; GFX13-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX13-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-NEXT:    v_wave_match_e32 v1, s2
; GFX13-SDAG-NEXT:    global_store_b32 v0, v1, s[0:1]
; GFX13-SDAG-NEXT:    s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
; GFX13-SDAG-NEXT:    s_endpgm
;
; GFX13-GISEL-LABEL: v_wave_match_sgpr:
; GFX13-GISEL:       ; %bb.0:
; GFX13-GISEL-NEXT:    s_load_b96 s[0:2], s[2:3], 0x24
; GFX13-GISEL-NEXT:    v_mov_b32_e32 v1, 0
; GFX13-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX13-GISEL-NEXT:    v_wave_match_e32 v0, s2
; GFX13-GISEL-NEXT:    global_store_b32 v1, v0, s[0:1]
; GFX13-GISEL-NEXT:    s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
; GFX13-GISEL-NEXT:    s_endpgm
  %v = call i32 @llvm.amdgcn.wave.match(i32 %src)
  store i32 %v, ptr addrspace(1) %out
  ret void
}

define amdgpu_kernel void @v_wave_match_vgpr(i32 addrspace(1)* %out) {
; GFX13-SDAG-LABEL: v_wave_match_vgpr:
; GFX13-SDAG:       ; %bb.0:
; GFX13-SDAG-NEXT:    s_load_b64 s[0:1], s[2:3], 0x24
; GFX13-SDAG-NEXT:    v_and_b32_e32 v0, 0x3ff, v0
; GFX13-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-SDAG-NEXT:    v_wave_match_e32 v1, v0
; GFX13-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-NEXT:    global_store_b32 v0, v1, s[0:1] scale_offset
; GFX13-SDAG-NEXT:    s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
; GFX13-SDAG-NEXT:    s_endpgm
;
; GFX13-GISEL-LABEL: v_wave_match_vgpr:
; GFX13-GISEL:       ; %bb.0:
; GFX13-GISEL-NEXT:    s_load_b64 s[0:1], s[2:3], 0x24
; GFX13-GISEL-NEXT:    v_and_b32_e32 v0, 0x3ff, v0
; GFX13-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-GISEL-NEXT:    v_wave_match_e32 v1, v0
; GFX13-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX13-GISEL-NEXT:    global_store_b32 v0, v1, s[0:1] scale_offset
; GFX13-GISEL-NEXT:    s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
; GFX13-GISEL-NEXT:    s_endpgm
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %v = call i32 @llvm.amdgcn.wave.match(i32 %tid)
  %out_ptr = getelementptr i32, i32 addrspace(1)* %out, i32 %tid
  store i32 %v, i32 addrspace(1)* %out_ptr
  ret void
}

define amdgpu_kernel void @v_wave_match_constant(ptr addrspace(1) %out) {
; GFX13-SDAG-LABEL: v_wave_match_constant:
; GFX13-SDAG:       ; %bb.0:
; GFX13-SDAG-NEXT:    s_load_b64 s[0:1], s[2:3], 0x24
; GFX13-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX13-SDAG-NEXT:    v_wave_match_e32 v1, 7
; GFX13-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-NEXT:    global_store_b32 v0, v1, s[0:1]
; GFX13-SDAG-NEXT:    s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
; GFX13-SDAG-NEXT:    s_endpgm
;
; GFX13-GISEL-LABEL: v_wave_match_constant:
; GFX13-GISEL:       ; %bb.0:
; GFX13-GISEL-NEXT:    s_load_b64 s[0:1], s[2:3], 0x24
; GFX13-GISEL-NEXT:    v_wave_match_e32 v0, 7
; GFX13-GISEL-NEXT:    v_mov_b32_e32 v1, 0
; GFX13-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX13-GISEL-NEXT:    global_store_b32 v1, v0, s[0:1]
; GFX13-GISEL-NEXT:    s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
; GFX13-GISEL-NEXT:    s_endpgm
  %v = call i32 @llvm.amdgcn.wave.match(i32 7)
  store i32 %v, ptr addrspace(1) %out
  ret void
}

define amdgpu_kernel void @v_wave_match_undef(ptr addrspace(1) %out) {
; GFX13-SDAG-LABEL: v_wave_match_undef:
; GFX13-SDAG:       ; %bb.0:
; GFX13-SDAG-NEXT:    s_load_b64 s[0:1], s[2:3], 0x24
; GFX13-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX13-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-NEXT:    v_wave_match_e32 v1, s0
; GFX13-SDAG-NEXT:    global_store_b32 v0, v1, s[0:1]
; GFX13-SDAG-NEXT:    s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
; GFX13-SDAG-NEXT:    s_endpgm
;
; GFX13-GISEL-LABEL: v_wave_match_undef:
; GFX13-GISEL:       ; %bb.0:
; GFX13-GISEL-NEXT:    s_load_b64 s[0:1], s[2:3], 0x24
; GFX13-GISEL-NEXT:    v_mov_b32_e32 v1, 0
; GFX13-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX13-GISEL-NEXT:    v_wave_match_e32 v0, s0
; GFX13-GISEL-NEXT:    global_store_b32 v1, v0, s[0:1]
; GFX13-GISEL-NEXT:    s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
; GFX13-GISEL-NEXT:    s_endpgm
  %v = call i32 @llvm.amdgcn.wave.match(i32 undef)
  store i32 %v, ptr addrspace(1) %out
  ret void
}
