# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -global-isel -mtriple=amdgcn -mcpu=gfx1031 -verify-machineinstrs -run-pass=localizer -o - %s | FileCheck %s

# Previously this was placing the new G_CONSTANT after the use call
---
name:            wrong_user_insert_pt
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: wrong_user_insert_pt
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(p0) = G_CONSTANT i64 0
  ; CHECK-NEXT:   G_BR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $scc
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(p0) = G_CONSTANT i64 0
  ; CHECK-NEXT:   $sgpr30_sgpr31 = G_SI_CALL [[C1]](p0), 0, csr_amdgpu
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $scc
  ; CHECK-NEXT:   S_SETPC_B64_return undef $sgpr30_sgpr31
  bb.0:
    %0:_(p0) = G_CONSTANT i64 0
    G_BR %bb.1

  bb.1:
    ADJCALLSTACKUP 0, 0, implicit-def $scc
    $sgpr30_sgpr31 = G_SI_CALL %0, 0, csr_amdgpu
    ADJCALLSTACKDOWN 0, 0, implicit-def $scc
    S_SETPC_B64_return undef $sgpr30_sgpr31

...
