; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -new-reg-bank-select -mtriple=amdgcn -mcpu=gfx1100 < %s | FileCheck %s

define amdgpu_ps void @s_mul_i32(i32 inreg %a, i32 inreg %b, ptr addrspace(1) %out) {
; CHECK-LABEL: s_mul_i32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_mul_i32 s0, s0, s1
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    v_mov_b32_e32 v2, s0
; CHECK-NEXT:    global_store_b32 v[0:1], v2, off
; CHECK-NEXT:    s_endpgm
  %result = mul i32 %a, %b
  store i32 %result, ptr addrspace(1) %out
  ret void
}

define amdgpu_ps void @v_mul_i32(i32 %a, i32 %b, ptr addrspace(1) %out) {
; CHECK-LABEL: v_mul_i32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    v_mul_lo_u32 v0, v0, v1
; CHECK-NEXT:    global_store_b32 v[2:3], v0, off
; CHECK-NEXT:    s_endpgm
  %result = mul i32 %a, %b
  store i32 %result, ptr addrspace(1) %out
  ret void
}
