; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -global-isel -stop-after=prologepilog -o - %s | FileCheck %s

define amdgpu_kernel void @wavegroup_kernel_3x64x2(ptr addrspace(1) %p) "amdgpu-wavegroup-enable" !reqd_work_group_size !{i32 3, i32 64, i32 2} {
  ; CHECK-LABEL: name: wavegroup_kernel_3x64x2
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $sgpr4_sgpr5, $sgpr8
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   frame-setup CFI_INSTRUCTION escape 0x0f, 0x04, 0x30, 0x36, 0xe9, 0x02
  ; CHECK-NEXT:   frame-setup CFI_INSTRUCTION undefined $pc_reg
  ; CHECK-NEXT:   $sgpr0 = S_GETREG_B32 7195, implicit $mode
  ; CHECK-NEXT:   $sgpr1 = S_MUL_I32 $sgpr0, target-index(amdgpu-num-vgprs)
  ; CHECK-NEXT:   $idx0 = S_SET_GPR_IDX_U32 $sgpr1
  ; CHECK-NEXT:   $sgpr33 = S_MUL_I32 $sgpr0, $sgpr8
  ; CHECK-NEXT:   SCHED_BARRIER 0
  ; CHECK-NEXT:   renamable $sgpr0_sgpr1 = S_LOAD_DWORDX2_IMM killed renamable $sgpr4_sgpr5, 0, 0 :: (dereferenceable invariant load (p1) from %ir.p.kernarg.offset1, align 16, addrspace 4)
  ; CHECK-NEXT:   renamable $vgpr0 = V_MOV_B32_e32 0, implicit $exec
  ; CHECK-NEXT:   GLOBAL_STORE_DWORD_SADDR killed renamable $vgpr0, renamable $vgpr0, killed renamable $sgpr0_sgpr1, 0, 0, implicit $exec :: (store (s32) into %ir.p.load, addrspace 1)
  ; CHECK-NEXT:   S_ENDPGM 0
entry:
  %p0 = getelementptr i32, ptr addrspace(1) %p, i32 0
  store i32 0, ptr addrspace(1) %p0
  ret void
}
