; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -new-reg-bank-select -mtriple=amdgcn-amd-mesa3d -mcpu=gfx900 %s -o - | FileCheck -check-prefixes=GCN,GFX9 %s
; RUN: llc -global-isel -new-reg-bank-select -mtriple=amdgcn-amd-mesa3d -mcpu=gfx1010 -mattr=+wavefrontsize64 %s -o - | FileCheck -check-prefixes=GCN,GFX10 %s

define amdgpu_ps void @test_fpclass_zext(float inreg %x, i32 %y, ptr addrspace(1) %ptr) {
; GFX9-LABEL: test_fpclass_zext:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GFX9-NEXT:    v_cndmask_b32_e64 v3, 0, 1, s[0:1]
; GFX9-NEXT:    v_add_u32_e32 v0, v3, v0
; GFX9-NEXT:    global_store_dword v[1:2], v0, off
; GFX9-NEXT:    s_endpgm
;
; GFX10-LABEL: test_fpclass_zext:
; GFX10:       ; %bb.0:
; GFX10-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GFX10-NEXT:    v_cndmask_b32_e64 v3, 0, 1, s[0:1]
; GFX10-NEXT:    v_add_nc_u32_e32 v0, v3, v0
; GFX10-NEXT:    global_store_dword v[1:2], v0, off
; GFX10-NEXT:    s_endpgm
  %cond = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  %sel = zext i1 %cond to i32
  %add = add i32 %sel, %y
  store i32 %add, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_fpclass_sext(float inreg %x, i32 %y, ptr addrspace(1) %ptr) {
; GFX9-LABEL: test_fpclass_sext:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GFX9-NEXT:    v_cndmask_b32_e64 v3, 0, -1, s[0:1]
; GFX9-NEXT:    v_add_u32_e32 v0, v3, v0
; GFX9-NEXT:    global_store_dword v[1:2], v0, off
; GFX9-NEXT:    s_endpgm
;
; GFX10-LABEL: test_fpclass_sext:
; GFX10:       ; %bb.0:
; GFX10-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GFX10-NEXT:    v_cndmask_b32_e64 v3, 0, -1, s[0:1]
; GFX10-NEXT:    v_add_nc_u32_e32 v0, v3, v0
; GFX10-NEXT:    global_store_dword v[1:2], v0, off
; GFX10-NEXT:    s_endpgm
  %cond = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  %sel = sext i1 %cond to i32
  %add = add i32 %sel, %y
  store i32 %add, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_fpclass_select_ss(float inreg %x, float inreg %y, float inreg %z, float %a, ptr addrspace(1) %ptr) {
; GCN-LABEL: test_fpclass_select_ss:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GCN-NEXT:    s_cmp_lg_u64 s[0:1], 0
; GCN-NEXT:    s_cselect_b32 s0, s3, s4
; GCN-NEXT:    v_add_f32_e32 v0, s0, v0
; GCN-NEXT:    global_store_dword v[1:2], v0, off
; GCN-NEXT:    s_endpgm
  %cond = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  %sel = select i1 %cond, float %y, float %z
  %add = fadd float %sel, %a
  store float %add, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_fpclass_f32_select_s_imm(float inreg %x, float inreg %y, float %z, ptr addrspace(1) %ptr) {
; GCN-LABEL: test_fpclass_f32_select_s_imm:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GCN-NEXT:    s_cmp_lg_u64 s[0:1], 0
; GCN-NEXT:    s_cselect_b32 s0, 1.0, s3
; GCN-NEXT:    v_add_f32_e32 v0, s0, v0
; GCN-NEXT:    global_store_dword v[1:2], v0, off
; GCN-NEXT:    s_endpgm
  %cond = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  %sel = select i1 %cond, float 1.0, float %y
  %add = fadd float %sel, %z
  store float %add, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_fpclass_select_vv(float inreg %x, i32 %y, i32 %z, ptr addrspace(1) %ptr) {
; GCN-LABEL: test_fpclass_select_vv:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GCN-NEXT:    s_cmp_lg_u64 s[0:1], 0
; GCN-NEXT:    s_cselect_b64 vcc, exec, 0
; GCN-NEXT:    v_cndmask_b32_e32 v0, v1, v0, vcc
; GCN-NEXT:    global_store_dword v[2:3], v0, off
; GCN-NEXT:    s_endpgm
  %cond = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  %sel = select i1 %cond, i32 %y, i32 %z
  store i32 %sel, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_fpclass_select_v_imm(float inreg %x, i32 %y, ptr addrspace(1) %ptr) {
; GCN-LABEL: test_fpclass_select_v_imm:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GCN-NEXT:    s_cmp_lg_u64 s[0:1], 0
; GCN-NEXT:    s_cselect_b64 vcc, exec, 0
; GCN-NEXT:    v_cndmask_b32_e32 v0, 1, v0, vcc
; GCN-NEXT:    global_store_dword v[1:2], v0, off
; GCN-NEXT:    s_endpgm
  %cond = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  %sel = select i1 %cond, i32 %y, i32 1
  store i32 %sel, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_fpclass_select_imm_imm(float inreg %x, ptr addrspace(1) %ptr) {
; GCN-LABEL: test_fpclass_select_imm_imm:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GCN-NEXT:    s_cmp_lg_u64 s[0:1], 0
; GCN-NEXT:    s_cselect_b32 s0, -1, 0
; GCN-NEXT:    s_add_i32 s0, s0, 2
; GCN-NEXT:    v_mov_b32_e32 v2, s0
; GCN-NEXT:    global_store_dword v[0:1], v2, off
; GCN-NEXT:    s_endpgm
  %cond = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  %sel = select i1 %cond, i32 1, i32 2
  store i32 %sel, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_fpclass_select_fconst_fconst(float inreg %x, ptr addrspace(1) %ptr) {
; GCN-LABEL: test_fpclass_select_fconst_fconst:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GCN-NEXT:    v_cndmask_b32_e64 v2, -1.0, 1.0, s[0:1]
; GCN-NEXT:    global_store_dword v[0:1], v2, off
; GCN-NEXT:    s_endpgm
  %cond = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  %sel = select i1 %cond, float 1.0, float -1.0
  store float %sel, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_fpclass_select_fconst_f16(half inreg %x, float inreg %y, ptr addrspace(1) %ptr) {
; GFX9-LABEL: test_fpclass_select_fconst_f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    v_add_f16_e64 v2, s2, s2
; GFX9-NEXT:    v_mov_b32_e32 v3, 0x3c00
; GFX9-NEXT:    v_cmp_class_f32_e64 vcc, s3, 3
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v2, vcc
; GFX9-NEXT:    global_store_short v[0:1], v2, off
; GFX9-NEXT:    s_endpgm
;
; GFX10-LABEL: test_fpclass_select_fconst_f16:
; GFX10:       ; %bb.0:
; GFX10-NEXT:    v_add_f16_e64 v2, s2, s2
; GFX10-NEXT:    v_cmp_class_f32_e64 vcc, s3, 3
; GFX10-NEXT:    v_cndmask_b32_e32 v2, 0x3c00, v2, vcc
; GFX10-NEXT:    global_store_short v[0:1], v2, off
; GFX10-NEXT:    s_endpgm
  %res = fadd half %x, %x
  %cond = call i1 @llvm.is.fpclass.f32(float %y, i32 3)
  %sel = select i1 %cond, half %res, half 1.0
  store half %sel, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_fpclass_multiple_uses(float inreg %x, float inreg %y, float inreg %z, float inreg %a, float %b, ptr addrspace(1) %ptr) {
; GFX9-LABEL: test_fpclass_multiple_uses:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GFX9-NEXT:    s_cmp_lg_u64 s[0:1], 0
; GFX9-NEXT:    s_cselect_b32 s0, s3, s4
; GFX9-NEXT:    v_mov_b32_e32 v3, s5
; GFX9-NEXT:    v_add_f32_e32 v3, s0, v3
; GFX9-NEXT:    v_mul_f32_e32 v4, s0, v0
; GFX9-NEXT:    global_store_dwordx2 v[1:2], v[3:4], off
; GFX9-NEXT:    s_endpgm
;
; GFX10-LABEL: test_fpclass_multiple_uses:
; GFX10:       ; %bb.0:
; GFX10-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GFX10-NEXT:    s_cmp_lg_u64 s[0:1], 0
; GFX10-NEXT:    s_cselect_b32 s0, s3, s4
; GFX10-NEXT:    v_add_f32_e64 v3, s0, s5
; GFX10-NEXT:    v_mul_f32_e32 v4, s0, v0
; GFX10-NEXT:    global_store_dwordx2 v[1:2], v[3:4], off
; GFX10-NEXT:    s_endpgm
  %cond = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  %sel = select i1 %cond, float %y, float %z
  %add = fadd float %sel, %a
  %or = fmul float %sel, %b
  store float %add, ptr addrspace(1) %ptr
  %ptr1 = getelementptr float, ptr addrspace(1) %ptr, i32 1
  store float %or, ptr addrspace(1) %ptr1
  ret void
}

define amdgpu_ps void @test_fpclass_multiple_select(
; GFX9-LABEL: test_fpclass_multiple_select:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GFX9-NEXT:    v_mov_b32_e32 v4, 0x60
; GFX9-NEXT:    s_cmp_lg_u64 s[0:1], 0
; GFX9-NEXT:    v_cmp_class_f32_e32 vcc, s2, v4
; GFX9-NEXT:    s_cselect_b32 s0, 1, 0
; GFX9-NEXT:    s_cmp_lg_u64 vcc, 0
; GFX9-NEXT:    s_cselect_b32 s1, 1, 0
; GFX9-NEXT:    s_cmp_lg_u32 s0, 0
; GFX9-NEXT:    s_cselect_b32 s0, s3, s4
; GFX9-NEXT:    v_mov_b32_e32 v4, s5
; GFX9-NEXT:    s_cmp_lg_u32 s1, 0
; GFX9-NEXT:    v_add_f32_e32 v4, s0, v4
; GFX9-NEXT:    v_mul_f32_e32 v5, s0, v0
; GFX9-NEXT:    s_cselect_b32 s0, s6, s7
; GFX9-NEXT:    v_mov_b32_e32 v0, s8
; GFX9-NEXT:    v_add_f32_e32 v6, s0, v0
; GFX9-NEXT:    v_mul_f32_e32 v7, s0, v1
; GFX9-NEXT:    global_store_dwordx4 v[2:3], v[4:7], off
; GFX9-NEXT:    s_endpgm
;
; GFX10-LABEL: test_fpclass_multiple_select:
; GFX10:       ; %bb.0:
; GFX10-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GFX10-NEXT:    v_cmp_class_f32_e64 s[10:11], s2, 0x60
; GFX10-NEXT:    s_cmp_lg_u64 s[0:1], 0
; GFX10-NEXT:    s_cselect_b32 s0, 1, 0
; GFX10-NEXT:    s_cmp_lg_u64 s[10:11], 0
; GFX10-NEXT:    s_cselect_b32 s1, 1, 0
; GFX10-NEXT:    s_cmp_lg_u32 s0, 0
; GFX10-NEXT:    s_cselect_b32 s0, s3, s4
; GFX10-NEXT:    s_cmp_lg_u32 s1, 0
; GFX10-NEXT:    v_add_f32_e64 v4, s0, s5
; GFX10-NEXT:    s_cselect_b32 s1, s6, s7
; GFX10-NEXT:    v_mul_f32_e32 v5, s0, v0
; GFX10-NEXT:    v_add_f32_e64 v6, s1, s8
; GFX10-NEXT:    v_mul_f32_e32 v7, s1, v1
; GFX10-NEXT:    global_store_dwordx4 v[2:3], v[4:7], off
; GFX10-NEXT:    s_endpgm
    float inreg %x,
    float inreg %y, float inreg %z, float inreg %a,
    float inreg %b, float inreg %c, float inreg %d,
    float %e, float %f, ptr addrspace(1) %ptr) {
  %cond1 = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  %cond2 = call i1 @llvm.is.fpclass.f32(float %x, i32 96)
  %sel1 = select i1 %cond1, float %y, float %z
  %add1 = fadd float %sel1, %a
  %or1 = fmul float %sel1, %e
  %sel2 = select i1 %cond2, float %b, float %c
  %add2 = fadd float %sel2, %d
  %or2 = fmul float %sel2, %f
  store float %add1, ptr addrspace(1) %ptr
  %ptr1 = getelementptr float, ptr addrspace(1) %ptr, i32 1
  store float %or1, ptr addrspace(1) %ptr1
  %ptr2 = getelementptr float, ptr addrspace(1) %ptr, i32 2
  store float %add2, ptr addrspace(1) %ptr2
  %ptr3 = getelementptr float, ptr addrspace(1) %ptr, i32 3
  store float %or2, ptr addrspace(1) %ptr3
  ret void
}

define amdgpu_ps float @test_brcond(float inreg %x) {
; GCN-LABEL: test_brcond:
; GCN:       ; %bb.0: ; %entry
; GCN-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GCN-NEXT:    s_cmp_lg_u64 s[0:1], 0
; GCN-NEXT:    s_cselect_b32 s0, 1, 0
; GCN-NEXT:    s_xor_b32 s0, s0, 1
; GCN-NEXT:    s_cmp_lg_u32 s0, 0
; GCN-NEXT:    s_cbranch_scc1 .LBB11_2
; GCN-NEXT:  ; %bb.1: ; %if.true
; GCN-NEXT:    v_mov_b32_e32 v0, 1.0
; GCN-NEXT:    s_branch .LBB11_3
; GCN-NEXT:  .LBB11_2: ; %if.false
; GCN-NEXT:    v_mov_b32_e32 v0, 0
; GCN-NEXT:    s_branch .LBB11_3
; GCN-NEXT:  .LBB11_3:
entry:
  %cond = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  br i1 %cond, label %if.true, label %if.false
if.true:
  ret float 1.0
if.false:
  ret float 0.0
}

define amdgpu_ps void @test_fpclass_select_readanylane_f16(half inreg %x, float inreg %y, half inreg %z, ptr addrspace(1) %ptr) {
; GFX9-LABEL: test_fpclass_select_readanylane_f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    v_add_f16_e64 v2, s2, s2
; GFX9-NEXT:    v_mov_b32_e32 v3, s4
; GFX9-NEXT:    v_cmp_class_f32_e64 vcc, s3, 3
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v2, v3, vcc
; GFX9-NEXT:    global_store_short v[0:1], v2, off
; GFX9-NEXT:    s_endpgm
;
; GFX10-LABEL: test_fpclass_select_readanylane_f16:
; GFX10:       ; %bb.0:
; GFX10-NEXT:    v_add_f16_e64 v2, s2, s2
; GFX10-NEXT:    v_cmp_class_f32_e64 s[0:1], s3, 3
; GFX10-NEXT:    v_cndmask_b32_e64 v2, v2, s4, s[0:1]
; GFX10-NEXT:    global_store_short v[0:1], v2, off
; GFX10-NEXT:    s_endpgm
  %res = fadd half %x, %x
  %cond = call i1 @llvm.is.fpclass.f32(float %y, i32 3)
  %sel = select i1 %cond, half %z, half %res
  store half %sel, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_fpclass_select_readanylane2_f16(half inreg %x, half inreg %y, float inreg %z, ptr addrspace(1) %ptr) {
; GCN-LABEL: test_fpclass_select_readanylane2_f16:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_add_f16_e64 v2, s2, s2
; GCN-NEXT:    v_add_f16_e64 v3, s3, s3
; GCN-NEXT:    v_cmp_class_f32_e64 vcc, s4, 3
; GCN-NEXT:    v_cndmask_b32_e32 v2, v3, v2, vcc
; GCN-NEXT:    global_store_short v[0:1], v2, off
; GCN-NEXT:    s_endpgm
  %res1 = fadd half %x, %x
  %res2 = fadd half %y, %y
  %cond = call i1 @llvm.is.fpclass.f32(float %z, i32 3)
  %sel = select i1 %cond, half %res1, half %res2
  store half %sel, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_fpclass_select_readanylane_f32(float inreg %x, float inreg %y, float inreg %z, ptr addrspace(1) %ptr) {
; GFX9-LABEL: test_fpclass_select_readanylane_f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    v_add_f32_e64 v2, s2, s2
; GFX9-NEXT:    v_mov_b32_e32 v3, s4
; GFX9-NEXT:    v_cmp_class_f32_e64 vcc, s3, 3
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v2, v3, vcc
; GFX9-NEXT:    global_store_dword v[0:1], v2, off
; GFX9-NEXT:    s_endpgm
;
; GFX10-LABEL: test_fpclass_select_readanylane_f32:
; GFX10:       ; %bb.0:
; GFX10-NEXT:    v_add_f32_e64 v2, s2, s2
; GFX10-NEXT:    v_cmp_class_f32_e64 s[0:1], s3, 3
; GFX10-NEXT:    v_cndmask_b32_e64 v2, v2, s4, s[0:1]
; GFX10-NEXT:    global_store_dword v[0:1], v2, off
; GFX10-NEXT:    s_endpgm
  %res = fadd float %x, %x
  %cond = call i1 @llvm.is.fpclass.f32(float %y, i32 3)
  %sel = select i1 %cond, float %z, float %res
  store float %sel, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_fpclass_select_readanylane2_f32(float inreg %x, float inreg %y, float inreg %z, ptr addrspace(1) %ptr) {
; GCN-LABEL: test_fpclass_select_readanylane2_f32:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_add_f32_e64 v2, s2, s2
; GCN-NEXT:    v_add_f32_e64 v3, s3, s3
; GCN-NEXT:    v_cmp_class_f32_e64 vcc, s4, 3
; GCN-NEXT:    v_cndmask_b32_e32 v2, v3, v2, vcc
; GCN-NEXT:    global_store_dword v[0:1], v2, off
; GCN-NEXT:    s_endpgm
  %res1 = fadd float %x, %x
  %res2 = fadd float %y, %y
  %cond = call i1 @llvm.is.fpclass.f32(float %z, i32 3)
  %sel = select i1 %cond, float %res1, float %res2
  store float %sel, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_fpclass_select_readanylane_f64(double inreg %x, float inreg %y, double inreg %z, ptr addrspace(1) %ptr) {
; GFX9-LABEL: test_fpclass_select_readanylane_f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    v_add_f64 v[2:3], s[2:3], s[2:3]
; GFX9-NEXT:    s_mov_b32 s0, s5
; GFX9-NEXT:    v_cmp_class_f32_e64 s[4:5], s4, 3
; GFX9-NEXT:    s_mov_b32 s1, s6
; GFX9-NEXT:    s_cmp_lg_u64 s[4:5], 0
; GFX9-NEXT:    v_readfirstlane_b32 s2, v2
; GFX9-NEXT:    v_readfirstlane_b32 s3, v3
; GFX9-NEXT:    s_cselect_b64 s[0:1], s[0:1], s[2:3]
; GFX9-NEXT:    v_mov_b32_e32 v3, s1
; GFX9-NEXT:    v_mov_b32_e32 v2, s0
; GFX9-NEXT:    global_store_dwordx2 v[0:1], v[2:3], off
; GFX9-NEXT:    s_endpgm
;
; GFX10-LABEL: test_fpclass_select_readanylane_f64:
; GFX10:       ; %bb.0:
; GFX10-NEXT:    v_add_f64 v[2:3], s[2:3], s[2:3]
; GFX10-NEXT:    v_cmp_class_f32_e64 s[2:3], s4, 3
; GFX10-NEXT:    s_mov_b32 s0, s5
; GFX10-NEXT:    s_mov_b32 s1, s6
; GFX10-NEXT:    s_cmp_lg_u64 s[2:3], 0
; GFX10-NEXT:    v_readfirstlane_b32 s4, v2
; GFX10-NEXT:    v_readfirstlane_b32 s5, v3
; GFX10-NEXT:    s_cselect_b64 s[0:1], s[0:1], s[4:5]
; GFX10-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-NEXT:    global_store_dwordx2 v[0:1], v[2:3], off
; GFX10-NEXT:    s_endpgm
  %res = fadd double %x, %x
  %cond = call i1 @llvm.is.fpclass.f32(float %y, i32 3)
  %sel = select i1 %cond, double %z, double %res
  store double %sel, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_fpclass_select_readanylane2_f64(double inreg %x, double inreg %y, float inreg %z, ptr addrspace(1) %ptr) {
; GFX9-LABEL: test_fpclass_select_readanylane2_f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    v_add_f64 v[2:3], s[2:3], s[2:3]
; GFX9-NEXT:    v_add_f64 v[4:5], s[4:5], s[4:5]
; GFX9-NEXT:    v_cmp_class_f32_e64 s[4:5], s6, 3
; GFX9-NEXT:    s_cmp_lg_u64 s[4:5], 0
; GFX9-NEXT:    v_readfirstlane_b32 s0, v2
; GFX9-NEXT:    v_readfirstlane_b32 s1, v3
; GFX9-NEXT:    v_readfirstlane_b32 s2, v4
; GFX9-NEXT:    v_readfirstlane_b32 s3, v5
; GFX9-NEXT:    s_cselect_b64 s[0:1], s[0:1], s[2:3]
; GFX9-NEXT:    v_mov_b32_e32 v3, s1
; GFX9-NEXT:    v_mov_b32_e32 v2, s0
; GFX9-NEXT:    global_store_dwordx2 v[0:1], v[2:3], off
; GFX9-NEXT:    s_endpgm
;
; GFX10-LABEL: test_fpclass_select_readanylane2_f64:
; GFX10:       ; %bb.0:
; GFX10-NEXT:    v_add_f64 v[2:3], s[2:3], s[2:3]
; GFX10-NEXT:    v_add_f64 v[4:5], s[4:5], s[4:5]
; GFX10-NEXT:    v_cmp_class_f32_e64 s[0:1], s6, 3
; GFX10-NEXT:    s_cmp_lg_u64 s[0:1], 0
; GFX10-NEXT:    v_readfirstlane_b32 s2, v2
; GFX10-NEXT:    v_readfirstlane_b32 s3, v3
; GFX10-NEXT:    v_readfirstlane_b32 s4, v4
; GFX10-NEXT:    v_readfirstlane_b32 s5, v5
; GFX10-NEXT:    s_cselect_b64 s[0:1], s[2:3], s[4:5]
; GFX10-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-NEXT:    global_store_dwordx2 v[0:1], v[2:3], off
; GFX10-NEXT:    s_endpgm
  %res1 = fadd double %x, %x
  %res2 = fadd double %y, %y
  %cond = call i1 @llvm.is.fpclass.f32(float %z, i32 3)
  %sel = select i1 %cond, double %res1, double %res2
  store double %sel, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_select_literal_imm_gfx10plus(float inreg %x, float %y, ptr addrspace(1) %ptr) {
; GFX9-LABEL: test_select_literal_imm_gfx10plus:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GFX9-NEXT:    s_cmp_lg_u64 s[0:1], 0
; GFX9-NEXT:    s_cselect_b32 s0, 0x42c80000, 0
; GFX9-NEXT:    v_add_f32_e32 v0, s0, v0
; GFX9-NEXT:    global_store_dword v[1:2], v0, off
; GFX9-NEXT:    s_endpgm
;
; GFX10-LABEL: test_select_literal_imm_gfx10plus:
; GFX10:       ; %bb.0:
; GFX10-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GFX10-NEXT:    v_cndmask_b32_e64 v3, 0, 0x42c80000, s[0:1]
; GFX10-NEXT:    v_add_f32_e32 v0, v3, v0
; GFX10-NEXT:    global_store_dword v[1:2], v0, off
; GFX10-NEXT:    s_endpgm
  %cond = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  %sel = select i1 %cond, float 100.0, float 0.0
  %add = fadd float %sel, %y
  store float %add, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_select_two_literal_imm(float inreg %x, float %y, ptr addrspace(1) %ptr) {
; GFX9-LABEL: test_select_two_literal_imm:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GFX9-NEXT:    s_cmp_lg_u64 s[0:1], 0
; GFX9-NEXT:    s_mov_b32 s0, 0x42c80000
; GFX9-NEXT:    s_cselect_b32 s0, s0, 0x43480000
; GFX9-NEXT:    v_add_f32_e32 v0, s0, v0
; GFX9-NEXT:    global_store_dword v[1:2], v0, off
; GFX9-NEXT:    s_endpgm
;
; GFX10-LABEL: test_select_two_literal_imm:
; GFX10:       ; %bb.0:
; GFX10-NEXT:    v_mov_b32_e32 v3, 0x43480000
; GFX10-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GFX10-NEXT:    v_cndmask_b32_e64 v3, v3, 0x42c80000, s[0:1]
; GFX10-NEXT:    v_add_f32_e32 v0, v3, v0
; GFX10-NEXT:    global_store_dword v[1:2], v0, off
; GFX10-NEXT:    s_endpgm
  %cond = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  %sel = select i1 %cond, float 100.0, float 200.0
  %add = fadd float %sel, %y
  store float %add, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_select_two_literals_store(float inreg %x, ptr addrspace(1) %ptr) {
; GFX9-LABEL: test_select_two_literals_store:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    v_mov_b32_e32 v2, 0x64
; GFX9-NEXT:    v_mov_b32_e32 v3, 0xc8
; GFX9-NEXT:    v_cmp_class_f32_e64 vcc, s2, 3
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v2, vcc
; GFX9-NEXT:    global_store_dword v[0:1], v2, off
; GFX9-NEXT:    s_endpgm
;
; GFX10-LABEL: test_select_two_literals_store:
; GFX10:       ; %bb.0:
; GFX10-NEXT:    v_mov_b32_e32 v2, 0xc8
; GFX10-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GFX10-NEXT:    v_cndmask_b32_e64 v2, v2, 0x64, s[0:1]
; GFX10-NEXT:    global_store_dword v[0:1], v2, off
; GFX10-NEXT:    s_endpgm
  %cond = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  %sel = select i1 %cond, i32 100, i32 200
  store i32 %sel, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_ps void @test_float_select_combine_inline_const(float inreg %x, float inreg %w, ptr addrspace(1) %ptr) {
; GCN-LABEL: test_float_select_combine_inline_const:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GCN-NEXT:    v_cndmask_b32_e64 v2, 1.0, 0, s[0:1]
; GCN-NEXT:    v_mul_f32_e32 v2, s3, v2
; GCN-NEXT:    global_store_dword v[0:1], v2, off
; GCN-NEXT:    s_endpgm
  %cond = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  %sel = select i1 %cond, float 0.0, float 1.0
  %mul = fmul float %sel, %w
  store float %mul, ptr addrspace(1) %ptr
  ret void
}

; TODO: Improve combine heuristic for GFX9, this is a net 0 gain.
define amdgpu_ps void @test_select_preexisting_copy(float inreg %x, float inreg %y, float %z, ptr addrspace(1) %ptr) {
; GFX9-LABEL: test_select_preexisting_copy:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    v_mov_b32_e32 v3, s3
; GFX9-NEXT:    v_cmp_class_f32_e64 vcc, s2, 3
; GFX9-NEXT:    v_add_f32_e32 v0, s3, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v3, 0, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v0, v3, v0
; GFX9-NEXT:    global_store_dword v[1:2], v0, off
; GFX9-NEXT:    s_endpgm
;
; GFX10-LABEL: test_select_preexisting_copy:
; GFX10:       ; %bb.0:
; GFX10-NEXT:    v_cmp_class_f32_e64 s[0:1], s2, 3
; GFX10-NEXT:    v_add_f32_e32 v0, s3, v0
; GFX10-NEXT:    v_cndmask_b32_e64 v3, 0, s3, s[0:1]
; GFX10-NEXT:    v_add_f32_e32 v0, v3, v0
; GFX10-NEXT:    global_store_dword v[1:2], v0, off
; GFX10-NEXT:    s_endpgm
  %cond = call i1 @llvm.is.fpclass.f32(float %x, i32 3)
  %use_y = fadd float %y, %z
  %sel = select i1 %cond, float %y, float 0.0
  %add = fadd float %sel, %use_y
  store float %add, ptr addrspace(1) %ptr
  ret void
}

declare i1 @llvm.is.fpclass.f32(float, i32 immarg)
