# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn -mcpu=fiji -run-pass="amdgpu-regbankselect,amdgpu-regbanklegalize" %s -verify-machineinstrs -o - | FileCheck -check-prefix=FIJI %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx1200 -run-pass="amdgpu-regbankselect,amdgpu-regbanklegalize" %s -verify-machineinstrs -o - | FileCheck -check-prefix=GFX12 %s

---
name: ffloor_s
legalized: true

body: |
  bb.0:
    liveins: $sgpr0
    ; FIJI-LABEL: name: ffloor_s
    ; FIJI: liveins: $sgpr0
    ; FIJI-NEXT: {{  $}}
    ; FIJI-NEXT: [[COPY:%[0-9]+]]:sgpr(s32) = COPY $sgpr0
    ; FIJI-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY [[COPY]](s32)
    ; FIJI-NEXT: [[FFLOOR:%[0-9]+]]:vgpr(s32) = G_FFLOOR [[COPY1]]
    ; GFX12-LABEL: name: ffloor_s
    ; GFX12: liveins: $sgpr0
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:sgpr(s32) = COPY $sgpr0
    ; GFX12-NEXT: [[FFLOOR:%[0-9]+]]:sgpr(s32) = G_FFLOOR [[COPY]]
    %0:_(s32) = COPY $sgpr0
    %1:_(s32) = G_FFLOOR %0
...

---
name: ffloor_v
legalized: true

body: |
  bb.0:
    liveins: $vgpr0
    ; FIJI-LABEL: name: ffloor_v
    ; FIJI: liveins: $vgpr0
    ; FIJI-NEXT: {{  $}}
    ; FIJI-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; FIJI-NEXT: [[FFLOOR:%[0-9]+]]:vgpr(s32) = G_FFLOOR [[COPY]]
    ; GFX12-LABEL: name: ffloor_v
    ; GFX12: liveins: $vgpr0
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; GFX12-NEXT: [[FFLOOR:%[0-9]+]]:vgpr(s32) = G_FFLOOR [[COPY]]
    %0:_(s32) = COPY $vgpr0
    %1:_(s32) = G_FFLOOR %0
...

---
name: ffloor_s16_s
legalized: true

body: |
  bb.0:
    liveins: $sgpr0
    ; FIJI-LABEL: name: ffloor_s16_s
    ; FIJI: liveins: $sgpr0
    ; FIJI-NEXT: {{  $}}
    ; FIJI-NEXT: [[COPY:%[0-9]+]]:sgpr(s32) = COPY $sgpr0
    ; FIJI-NEXT: [[TRUNC:%[0-9]+]]:sgpr(s16) = G_TRUNC [[COPY]](s32)
    ; FIJI-NEXT: [[COPY1:%[0-9]+]]:vgpr(s16) = COPY [[TRUNC]](s16)
    ; FIJI-NEXT: [[FFLOOR:%[0-9]+]]:vgpr(s16) = G_FFLOOR [[COPY1]]
    ; GFX12-LABEL: name: ffloor_s16_s
    ; GFX12: liveins: $sgpr0
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:sgpr(s32) = COPY $sgpr0
    ; GFX12-NEXT: [[TRUNC:%[0-9]+]]:sgpr(s16) = G_TRUNC [[COPY]](s32)
    ; GFX12-NEXT: [[FFLOOR:%[0-9]+]]:sgpr(s16) = G_FFLOOR [[TRUNC]]
    %0:_(s32) = COPY $sgpr0
    %1:_(s16) = G_TRUNC %0
    %2:_(s16) = G_FFLOOR %1
...

---
name: ffloor_s16_v
legalized: true

body: |
  bb.0:
    liveins: $vgpr0
    ; FIJI-LABEL: name: ffloor_s16_v
    ; FIJI: liveins: $vgpr0
    ; FIJI-NEXT: {{  $}}
    ; FIJI-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; FIJI-NEXT: [[TRUNC:%[0-9]+]]:vgpr(s16) = G_TRUNC [[COPY]](s32)
    ; FIJI-NEXT: [[FFLOOR:%[0-9]+]]:vgpr(s16) = G_FFLOOR [[TRUNC]]
    ; GFX12-LABEL: name: ffloor_s16_v
    ; GFX12: liveins: $vgpr0
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; GFX12-NEXT: [[TRUNC:%[0-9]+]]:vgpr(s16) = G_TRUNC [[COPY]](s32)
    ; GFX12-NEXT: [[FFLOOR:%[0-9]+]]:vgpr(s16) = G_FFLOOR [[TRUNC]]
    %0:_(s32) = COPY $vgpr0
    %1:_(s16) = G_TRUNC %0
    %2:_(s16) = G_FFLOOR %1
...

---
name: ffloor_s64_s
legalized: true

body: |
  bb.0:
    liveins: $sgpr0_sgpr1
    ; FIJI-LABEL: name: ffloor_s64_s
    ; FIJI: liveins: $sgpr0_sgpr1
    ; FIJI-NEXT: {{  $}}
    ; FIJI-NEXT: [[COPY:%[0-9]+]]:sgpr(s64) = COPY $sgpr0_sgpr1
    ; FIJI-NEXT: [[COPY1:%[0-9]+]]:vgpr(s64) = COPY [[COPY]](s64)
    ; FIJI-NEXT: [[FFLOOR:%[0-9]+]]:vgpr(s64) = G_FFLOOR [[COPY1]]
    ; GFX12-LABEL: name: ffloor_s64_s
    ; GFX12: liveins: $sgpr0_sgpr1
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:sgpr(s64) = COPY $sgpr0_sgpr1
    ; GFX12-NEXT: [[COPY1:%[0-9]+]]:vgpr(s64) = COPY [[COPY]](s64)
    ; GFX12-NEXT: [[FFLOOR:%[0-9]+]]:vgpr(s64) = G_FFLOOR [[COPY1]]
    %0:_(s64) = COPY $sgpr0_sgpr1
    %1:_(s64) = G_FFLOOR %0
...

---
name: ffloor_s64_v
legalized: true

body: |
  bb.0:
    liveins: $vgpr0_vgpr1
    ; FIJI-LABEL: name: ffloor_s64_v
    ; FIJI: liveins: $vgpr0_vgpr1
    ; FIJI-NEXT: {{  $}}
    ; FIJI-NEXT: [[COPY:%[0-9]+]]:vgpr(s64) = COPY $vgpr0_vgpr1
    ; FIJI-NEXT: [[FFLOOR:%[0-9]+]]:vgpr(s64) = G_FFLOOR [[COPY]]
    ; GFX12-LABEL: name: ffloor_s64_v
    ; GFX12: liveins: $vgpr0_vgpr1
    ; GFX12-NEXT: {{  $}}
    ; GFX12-NEXT: [[COPY:%[0-9]+]]:vgpr(s64) = COPY $vgpr0_vgpr1
    ; GFX12-NEXT: [[FFLOOR:%[0-9]+]]:vgpr(s64) = G_FFLOOR [[COPY]]
    %0:_(s64) = COPY $vgpr0_vgpr1
    %1:_(s64) = G_FFLOOR %0
...
