# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-amd-mesa3d -mcpu=gfx900 -run-pass=amdgpu-regbank-combiner -verify-machineinstrs %s -o - | FileCheck %s

---
name: test_sext_i32
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0, $vgpr1

    ; CHECK-LABEL: name: test_sext_i32
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vcc(s1) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:vgpr(s32) = G_SELECT [[ICMP]](s1), [[C]], [[C1]]
    ; CHECK-NEXT: $vgpr0 = COPY [[SELECT]](s32)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vcc(s1) = G_ICMP intpred(eq), %0, %1
    %3:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %2
    %4:sgpr(s32) = G_CONSTANT i32 1
    %5:sgpr(s32) = G_AND %3, %4
    %6:sgpr(s32) = G_CONSTANT i32 -1
    %7:sgpr(s32) = G_CONSTANT i32 0
    %8:sgpr(s32) = G_SELECT %5, %6, %7
    %9:vgpr(s32) = COPY %8
    $vgpr0 = COPY %9(s32)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
...

---
name: test_zext_i32
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0, $vgpr1

    ; CHECK-LABEL: name: test_zext_i32
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vcc(s1) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:vgpr(s32) = G_SELECT [[ICMP]](s1), [[C]], [[C1]]
    ; CHECK-NEXT: $vgpr0 = COPY [[SELECT]](s32)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vcc(s1) = G_ICMP intpred(eq), %0, %1
    %3:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %2
    %4:sgpr(s32) = G_CONSTANT i32 1
    %5:sgpr(s32) = G_AND %3, %4
    %6:sgpr(s32) = G_CONSTANT i32 1
    %7:sgpr(s32) = G_CONSTANT i32 0
    %8:sgpr(s32) = G_SELECT %5, %6, %7
    %9:vgpr(s32) = COPY %8
    $vgpr0 = COPY %9(s32)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
...

---
name: test_sext_s64
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0, $vgpr1

    ; CHECK-LABEL: name: test_sext_s64
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vcc(s1) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: [[AMDGPU_COPY_SCC_VCC:%[0-9]+]]:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC [[ICMP]](s1)
    ; CHECK-NEXT: [[C:%[0-9]+]]:sgpr(s64) = G_CONSTANT i64 -1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:sgpr(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:sgpr(s64) = G_SELECT [[AMDGPU_COPY_SCC_VCC]](s32), [[C]], [[C1]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vgpr(s64) = COPY [[SELECT]](s64)
    ; CHECK-NEXT: $vgpr0_vgpr1 = COPY [[COPY2]](s64)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0_vgpr1
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vcc(s1) = G_ICMP intpred(eq), %0, %1
    %3:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %2
    %4:sgpr(s32) = G_CONSTANT i32 1
    %5:sgpr(s32) = G_AND %3, %4
    %6:sgpr(s64) = G_CONSTANT i64 -1
    %7:sgpr(s64) = G_CONSTANT i64 0
    %8:sgpr(s64) = G_SELECT %5, %6, %7
    %9:vgpr(s64) = COPY %8
    $vgpr0_vgpr1 = COPY %9(s64)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0_vgpr1
...

---
name: test_zext_s64
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0, $vgpr1

    ; CHECK-LABEL: name: test_zext_s64
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vcc(s1) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: [[AMDGPU_COPY_SCC_VCC:%[0-9]+]]:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC [[ICMP]](s1)
    ; CHECK-NEXT: [[C:%[0-9]+]]:sgpr(s64) = G_CONSTANT i64 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:sgpr(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:sgpr(s64) = G_SELECT [[AMDGPU_COPY_SCC_VCC]](s32), [[C]], [[C1]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vgpr(s64) = COPY [[SELECT]](s64)
    ; CHECK-NEXT: $vgpr0_vgpr1 = COPY [[COPY2]](s64)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0_vgpr1
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vcc(s1) = G_ICMP intpred(eq), %0, %1
    %3:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %2
    %4:sgpr(s32) = G_CONSTANT i32 1
    %5:sgpr(s32) = G_AND %3, %4
    %6:sgpr(s64) = G_CONSTANT i64 1
    %7:sgpr(s64) = G_CONSTANT i64 0
    %8:sgpr(s64) = G_SELECT %5, %6, %7
    %9:vgpr(s64) = COPY %8
    $vgpr0_vgpr1 = COPY %9(s64)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0_vgpr1
...

---
name: test_fcmp_source
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0, $vgpr1

    ; CHECK-LABEL: name: test_fcmp_source
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:vcc(s1) = G_FCMP floatpred(oeq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:vgpr(s32) = G_SELECT [[FCMP]](s1), [[C]], [[C1]]
    ; CHECK-NEXT: $vgpr0 = COPY [[SELECT]](s32)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vcc(s1) = G_FCMP floatpred(oeq), %0, %1
    %3:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %2
    %4:sgpr(s32) = G_CONSTANT i32 1
    %5:sgpr(s32) = G_AND %3, %4
    %6:sgpr(s32) = G_CONSTANT i32 1
    %7:sgpr(s32) = G_CONSTANT i32 0
    %8:sgpr(s32) = G_SELECT %5, %6, %7
    %9:vgpr(s32) = COPY %8
    $vgpr0 = COPY %9(s32)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
...

---
name: test_multiple_vgpr_copies
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0, $vgpr1

    ; CHECK-LABEL: name: test_multiple_vgpr_copies
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vcc(s1) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: [[AMDGPU_COPY_SCC_VCC:%[0-9]+]]:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC [[ICMP]](s1)
    ; CHECK-NEXT: [[C:%[0-9]+]]:sgpr(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:sgpr(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:sgpr(s32) = G_SELECT [[AMDGPU_COPY_SCC_VCC]](s32), [[C]], [[C1]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vgpr(s32) = COPY [[SELECT]](s32)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vgpr(s32) = COPY [[SELECT]](s32)
    ; CHECK-NEXT: $vgpr0 = COPY [[COPY2]](s32)
    ; CHECK-NEXT: $vgpr1 = COPY [[COPY3]](s32)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0, implicit $vgpr1
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vcc(s1) = G_ICMP intpred(eq), %0, %1
    %3:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %2
    %4:sgpr(s32) = G_CONSTANT i32 1
    %5:sgpr(s32) = G_AND %3, %4
    %6:sgpr(s32) = G_CONSTANT i32 -1
    %7:sgpr(s32) = G_CONSTANT i32 0
    %8:sgpr(s32) = G_SELECT %5, %6, %7
    %9:vgpr(s32) = COPY %8
    %10:vgpr(s32) = COPY %8
    $vgpr0 = COPY %9(s32)
    $vgpr1 = COPY %10(s32)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0, implicit $vgpr1
...

---
name: test_is_fpclass_source
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0

    ; CHECK-LABEL: name: test_is_fpclass_source
    ; CHECK: liveins: $vgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[IS_FPCLASS:%[0-9]+]]:vcc(s1) = G_IS_FPCLASS [[COPY]](s32), 3
    ; CHECK-NEXT: [[C:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:vgpr(s32) = G_SELECT [[IS_FPCLASS]](s1), [[C]], [[C1]]
    ; CHECK-NEXT: $vgpr0 = COPY [[SELECT]](s32)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
    %0:vgpr(s32) = COPY $vgpr0
    %1:vcc(s1) = G_IS_FPCLASS %0, 3
    %2:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %1
    %3:sgpr(s32) = G_CONSTANT i32 1
    %4:sgpr(s32) = G_AND %2, %3
    %5:sgpr(s32) = G_CONSTANT i32 -1
    %6:sgpr(s32) = G_CONSTANT i32 0
    %7:sgpr(s32) = G_SELECT %4, %5, %6
    %8:vgpr(s32) = COPY %7
    $vgpr0 = COPY %8(s32)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
...

---
name: test_and_commuted
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0, $vgpr1

    ; CHECK-LABEL: name: test_and_commuted
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vcc(s1) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:vgpr(s32) = G_SELECT [[ICMP]](s1), [[C]], [[C1]]
    ; CHECK-NEXT: $vgpr0 = COPY [[SELECT]](s32)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vcc(s1) = G_ICMP intpred(eq), %0, %1
    %3:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %2
    %4:sgpr(s32) = G_CONSTANT i32 1
    %5:sgpr(s32) = G_AND %4, %3
    %6:sgpr(s32) = G_CONSTANT i32 1
    %7:sgpr(s32) = G_CONSTANT i32 0
    %8:sgpr(s32) = G_SELECT %5, %6, %7
    %9:vgpr(s32) = COPY %8
    $vgpr0 = COPY %9(s32)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
...

---
name: test_mixed_uses
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0, $vgpr1, $sgpr0

    ; CHECK-LABEL: name: test_mixed_uses
    ; CHECK: liveins: $vgpr0, $vgpr1, $sgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:sgpr(s32) = COPY $sgpr0
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vcc(s1) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: [[AMDGPU_COPY_SCC_VCC:%[0-9]+]]:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC [[ICMP]](s1)
    ; CHECK-NEXT: [[C:%[0-9]+]]:sgpr(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:sgpr(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:sgpr(s32) = G_SELECT [[AMDGPU_COPY_SCC_VCC]](s32), [[C]], [[C1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vgpr(s32) = COPY [[SELECT]](s32)
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:sgpr(s32) = G_ADD [[SELECT]], [[COPY2]]
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vgpr(s32) = COPY [[ADD]](s32)
    ; CHECK-NEXT: $vgpr0 = COPY [[COPY3]](s32)
    ; CHECK-NEXT: $vgpr1 = COPY [[COPY4]](s32)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0, implicit $vgpr1
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:sgpr(s32) = COPY $sgpr0
    %3:vcc(s1) = G_ICMP intpred(eq), %0, %1
    %4:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %3
    %5:sgpr(s32) = G_CONSTANT i32 1
    %6:sgpr(s32) = G_AND %4, %5
    %7:sgpr(s32) = G_CONSTANT i32 -1
    %8:sgpr(s32) = G_CONSTANT i32 0
    %9:sgpr(s32) = G_SELECT %6, %7, %8
    %10:vgpr(s32) = COPY %9
    %11:sgpr(s32) = G_ADD %9, %2
    %12:vgpr(s32) = COPY %11
    $vgpr0 = COPY %10(s32)
    $vgpr1 = COPY %12(s32)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0, implicit $vgpr1
...

---
name: test_no_eliminate_branch
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: test_no_eliminate_branch
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $vgpr0, $vgpr1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:vcc(s1) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
  ; CHECK-NEXT:   [[AMDGPU_COPY_SCC_VCC:%[0-9]+]]:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC [[ICMP]](s1)
  ; CHECK-NEXT:   G_BRCOND [[AMDGPU_COPY_SCC_VCC]](s32), %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   S_ENDPGM 0
  bb.0:
    liveins: $vgpr0, $vgpr1
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vcc(s1) = G_ICMP intpred(eq), %0, %1
    %3:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %2
    %4:sgpr(s32) = G_CONSTANT i32 1
    %5:sgpr(s32) = G_AND %3, %4
    G_BRCOND %5(s32), %bb.1

  bb.1:
    S_ENDPGM 0
...

---
name: test_no_eliminate_scalar_arithmetic_use
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0, $vgpr1, $sgpr0

    ; CHECK-LABEL: name: test_no_eliminate_scalar_arithmetic_use
    ; CHECK: liveins: $vgpr0, $vgpr1, $sgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:sgpr(s32) = COPY $sgpr0
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vcc(s1) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: [[AMDGPU_COPY_SCC_VCC:%[0-9]+]]:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC [[ICMP]](s1)
    ; CHECK-NEXT: [[C:%[0-9]+]]:sgpr(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:sgpr(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:sgpr(s32) = G_SELECT [[AMDGPU_COPY_SCC_VCC]](s32), [[C]], [[C1]]
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:sgpr(s32) = G_ADD [[SELECT]], [[COPY2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vgpr(s32) = COPY [[ADD]](s32)
    ; CHECK-NEXT: $vgpr0 = COPY [[COPY3]](s32)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:sgpr(s32) = COPY $sgpr0
    %3:vcc(s1) = G_ICMP intpred(eq), %0, %1
    %4:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %3
    %5:sgpr(s32) = G_CONSTANT i32 1
    %6:sgpr(s32) = G_AND %4, %5
    %7:sgpr(s32) = G_CONSTANT i32 -1
    %8:sgpr(s32) = G_CONSTANT i32 0
    %9:sgpr(s32) = G_SELECT %6, %7, %8
    %10:sgpr(s32) = G_ADD %9, %2
    %11:vgpr(s32) = COPY %10
    $vgpr0 = COPY %11(s32)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
...

---
name: test_no_match_physical_reg_dst
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0, $vgpr1

    ; CHECK-LABEL: name: test_no_match_physical_reg_dst
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vcc(s1) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: [[AMDGPU_COPY_SCC_VCC:%[0-9]+]]:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC [[ICMP]](s1)
    ; CHECK-NEXT: [[C:%[0-9]+]]:sgpr(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:sgpr(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:sgpr(s32) = G_SELECT [[AMDGPU_COPY_SCC_VCC]](s32), [[C]], [[C1]]
    ; CHECK-NEXT: $vgpr0 = COPY [[SELECT]](s32)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vcc(s1) = G_ICMP intpred(eq), %0, %1
    %3:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %2
    %4:sgpr(s32) = G_CONSTANT i32 1
    %5:sgpr(s32) = G_AND %3, %4
    %6:sgpr(s32) = G_CONSTANT i32 -1
    %7:sgpr(s32) = G_CONSTANT i32 0
    %8:sgpr(s32) = G_SELECT %5, %6, %7
    $vgpr0 = COPY %8(s32)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
...

---
name: test_no_and_needed
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0, $vgpr1

    ; CHECK-LABEL: name: test_no_and_needed
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vcc(s1) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:vgpr(s32) = G_SELECT [[ICMP]](s1), [[C]], [[C1]]
    ; CHECK-NEXT: $vgpr0 = COPY [[SELECT]](s32)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vcc(s1) = G_ICMP intpred(eq), %0, %1
    %3:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %2
    %4:sgpr(s32) = G_CONSTANT i32 -1
    %5:sgpr(s32) = G_CONSTANT i32 0
    %6:sgpr(s32) = G_SELECT %3, %4, %5
    %7:vgpr(s32) = COPY %6
    $vgpr0 = COPY %7(s32)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
...

---
name: test_and_mask_not_1
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0, $vgpr1

    ; CHECK-LABEL: name: test_and_mask_not_1
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vcc(s1) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:vgpr(s32) = G_SELECT [[ICMP]](s1), [[C]], [[C1]]
    ; CHECK-NEXT: $vgpr0 = COPY [[SELECT]](s32)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vcc(s1) = G_ICMP intpred(eq), %0, %1
    %3:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %2
    %4:sgpr(s32) = G_CONSTANT i32 3
    %5:sgpr(s32) = G_AND %3, %4
    %6:sgpr(s32) = G_CONSTANT i32 -1
    %7:sgpr(s32) = G_CONSTANT i32 0
    %8:sgpr(s32) = G_SELECT %5, %6, %7
    %9:vgpr(s32) = COPY %8
    $vgpr0 = COPY %9(s32)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
...

---
name: test_arbitrary_inline_trueval
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0, $vgpr1

    ; CHECK-LABEL: name: test_arbitrary_inline_trueval
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vcc(s1) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 2
    ; CHECK-NEXT: [[C1:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:vgpr(s32) = G_SELECT [[ICMP]](s1), [[C]], [[C1]]
    ; CHECK-NEXT: $vgpr0 = COPY [[SELECT]](s32)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vcc(s1) = G_ICMP intpred(eq), %0, %1
    %3:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %2
    %4:sgpr(s32) = G_CONSTANT i32 1
    %5:sgpr(s32) = G_AND %3, %4
    %6:sgpr(s32) = G_CONSTANT i32 2
    %7:sgpr(s32) = G_CONSTANT i32 0
    %8:sgpr(s32) = G_SELECT %5, %6, %7
    %9:vgpr(s32) = COPY %8
    $vgpr0 = COPY %9(s32)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
...

---
name: test_no_match_sgpr_dst
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0, $vgpr1

    ; CHECK-LABEL: name: test_no_match_sgpr_dst
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vcc(s1) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: [[AMDGPU_COPY_SCC_VCC:%[0-9]+]]:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC [[ICMP]](s1)
    ; CHECK-NEXT: [[C:%[0-9]+]]:sgpr(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:sgpr(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:sgpr(s32) = G_SELECT [[AMDGPU_COPY_SCC_VCC]](s32), [[C]], [[C1]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:sgpr(s32) = COPY [[SELECT]](s32)
    ; CHECK-NEXT: $sgpr0 = COPY [[COPY2]](s32)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $sgpr0
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vcc(s1) = G_ICMP intpred(eq), %0, %1
    %3:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %2
    %4:sgpr(s32) = G_CONSTANT i32 1
    %5:sgpr(s32) = G_AND %3, %4
    %6:sgpr(s32) = G_CONSTANT i32 -1
    %7:sgpr(s32) = G_CONSTANT i32 0
    %8:sgpr(s32) = G_SELECT %5, %6, %7
    %9:sgpr(s32) = COPY %8
    $sgpr0 = COPY %9(s32)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $sgpr0
...

---
name: test_arbitrary_inline_falseval
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.1:
    liveins: $vgpr0, $vgpr1

    ; CHECK-LABEL: name: test_arbitrary_inline_falseval
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr(s32) = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr(s32) = COPY $vgpr1
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vcc(s1) = G_ICMP intpred(eq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:vgpr(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:vgpr(s32) = G_SELECT [[ICMP]](s1), [[C]], [[C1]]
    ; CHECK-NEXT: $vgpr0 = COPY [[SELECT]](s32)
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
    %0:vgpr(s32) = COPY $vgpr0
    %1:vgpr(s32) = COPY $vgpr1
    %2:vcc(s1) = G_ICMP intpred(eq), %0, %1
    %3:sgpr(s32) = G_AMDGPU_COPY_SCC_VCC %2
    %4:sgpr(s32) = G_CONSTANT i32 1
    %5:sgpr(s32) = G_AND %3, %4
    %6:sgpr(s32) = G_CONSTANT i32 -1
    %7:sgpr(s32) = G_CONSTANT i32 5
    %8:sgpr(s32) = G_SELECT %5, %6, %7
    %9:vgpr(s32) = COPY %8
    $vgpr0 = COPY %9(s32)
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
...
