# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn -mcpu=gfx942 -global-isel=true -run-pass=instruction-select -o - %s | FileCheck %s
#
# Test that selectSMRDBufferSgprImm correctly handles 64-bit types returned
# by getBaseWithConstantOffset when looking through
# G_PTRTOINT(G_PTR_ADD( G_INTTOPTR(s64), const))

---
name:            smrd_buffer_sgpr_imm_s64_offset
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $sgpr0


    ; CHECK-LABEL: name: smrd_buffer_sgpr_imm_s64_offset
    ; CHECK: liveins: $sgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:sreg_32 = COPY $sgpr0
    ; CHECK-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 16
    ; CHECK-NEXT: [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[S_MOV_B32_]], [[COPY]], implicit-def dead $scc
    ; CHECK-NEXT: [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 0
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:sgpr_128 = REG_SEQUENCE [[S_MOV_B32_1]], %subreg.sub0, [[S_MOV_B32_1]], %subreg.sub1, [[S_MOV_B32_1]], %subreg.sub2, [[S_MOV_B32_1]], %subreg.sub3
    ; CHECK-NEXT: [[S_BUFFER_LOAD_DWORD_SGPR_IMM:%[0-9]+]]:sreg_32_xm0_xexec = S_BUFFER_LOAD_DWORD_SGPR_IMM [[REG_SEQUENCE]], [[S_ADD_U32_]], 16, 0 :: (dereferenceable invariant load (s32))
    ; CHECK-NEXT: $sgpr0 = COPY [[S_BUFFER_LOAD_DWORD_SGPR_IMM]]
    ; CHECK-NEXT: SI_RETURN implicit $sgpr0
    %0:sgpr(s32) = COPY $sgpr0
    %1:sgpr(s32) = G_CONSTANT i32 16
    %2:sgpr(p6) = G_INTTOPTR %1(s32)
    %3:sgpr(p6) = G_PTR_ADD %2, %0(s32)
    %4:sgpr(p6) = G_PTR_ADD %3, %1(s32)
    %5:sgpr(s32) = G_PTRTOINT %4(p6)

    %6:sgpr(s32) = G_CONSTANT i32 0
    %7:sgpr(<4 x s32>) = G_BUILD_VECTOR %6(s32), %6(s32), %6(s32), %6(s32)
    %8:sgpr(s32) = G_AMDGPU_S_BUFFER_LOAD %7, %5, 0 :: (dereferenceable invariant load (s32))

    $sgpr0 = COPY %8(s32)
    SI_RETURN implicit $sgpr0
...
