; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn -mcpu=gfx90a -O0 -global-isel=true -stop-after=legalizer -o - %s | FileCheck -check-prefix=UNPACKED %s

define void @store_i48(ptr addrspace(1) %ptr, i48 %arg) #0 {
  ; UNPACKED-LABEL: name: store_i48
  ; UNPACKED: bb.1 (%ir-block.0):
  ; UNPACKED-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3
  ; UNPACKED-NEXT: {{  $}}
  ; UNPACKED-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $vgpr0
  ; UNPACKED-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $vgpr1
  ; UNPACKED-NEXT:   [[MV:%[0-9]+]]:_(p1) = G_MERGE_VALUES [[COPY]](i32), [[COPY1]](i32)
  ; UNPACKED-NEXT:   [[COPY2:%[0-9]+]]:_(i32) = COPY $vgpr2
  ; UNPACKED-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY $vgpr3
  ; UNPACKED-NEXT:   [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY2]](i32), [[COPY3]](i32)
  ; UNPACKED-NEXT:   [[COPY4:%[0-9]+]]:_(i64) = COPY [[MV1]](s64)
  ; UNPACKED-NEXT:   [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 32
  ; UNPACKED-NEXT:   [[LSHR:%[0-9]+]]:_(i64) = G_LSHR [[COPY4]], [[C]](i32)
  ; UNPACKED-NEXT:   [[C1:%[0-9]+]]:_(i64) = G_CONSTANT i64 4
  ; UNPACKED-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p1) = nuw inbounds G_PTR_ADD [[MV]], [[C1]](i64)
  ; UNPACKED-NEXT:   G_STORE [[COPY2]](i32), [[MV]](p1) :: (store (s32) into %ir.ptr, addrspace 1)
  ; UNPACKED-NEXT:   [[TRUNC:%[0-9]+]]:_(i32) = G_TRUNC [[LSHR]](i64)
  ; UNPACKED-NEXT:   G_STORE [[TRUNC]](i32), [[PTR_ADD]](p1) :: (store (s16) into %ir.ptr + 4, align 4, addrspace 1)
  ; UNPACKED-NEXT:   SI_RETURN
  store i48 %arg, ptr addrspace(1) %ptr, align 4
  ret void
}

define void @store_i55(ptr addrspace(1) %ptr, i55 %arg) #0 {
  ; UNPACKED-LABEL: name: store_i55
  ; UNPACKED: bb.1 (%ir-block.0):
  ; UNPACKED-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3
  ; UNPACKED-NEXT: {{  $}}
  ; UNPACKED-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $vgpr0
  ; UNPACKED-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $vgpr1
  ; UNPACKED-NEXT:   [[MV:%[0-9]+]]:_(p1) = G_MERGE_VALUES [[COPY]](i32), [[COPY1]](i32)
  ; UNPACKED-NEXT:   [[COPY2:%[0-9]+]]:_(i32) = COPY $vgpr2
  ; UNPACKED-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY $vgpr3
  ; UNPACKED-NEXT:   [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY2]](i32), [[COPY3]](i32)
  ; UNPACKED-NEXT:   [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 36028797018963967
  ; UNPACKED-NEXT:   [[AND:%[0-9]+]]:_(i64) = G_AND [[MV1]], [[C]]
  ; UNPACKED-NEXT:   [[COPY4:%[0-9]+]]:_(i64) = COPY [[AND]](i64)
  ; UNPACKED-NEXT:   [[C1:%[0-9]+]]:_(i32) = G_CONSTANT i32 32
  ; UNPACKED-NEXT:   [[LSHR:%[0-9]+]]:_(i64) = G_LSHR [[COPY4]], [[C1]](i32)
  ; UNPACKED-NEXT:   [[C2:%[0-9]+]]:_(i64) = G_CONSTANT i64 4
  ; UNPACKED-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p1) = nuw inbounds G_PTR_ADD [[MV]], [[C2]](i64)
  ; UNPACKED-NEXT:   [[TRUNC:%[0-9]+]]:_(i32) = G_TRUNC [[COPY4]](i64)
  ; UNPACKED-NEXT:   G_STORE [[TRUNC]](i32), [[MV]](p1) :: (store (s32) into %ir.ptr, addrspace 1)
  ; UNPACKED-NEXT:   [[TRUNC1:%[0-9]+]]:_(i32) = G_TRUNC [[LSHR]](i64)
  ; UNPACKED-NEXT:   [[C3:%[0-9]+]]:_(i32) = G_CONSTANT i32 16
  ; UNPACKED-NEXT:   [[LSHR1:%[0-9]+]]:_(i32) = G_LSHR [[TRUNC1]], [[C3]](i32)
  ; UNPACKED-NEXT:   [[C4:%[0-9]+]]:_(i64) = G_CONSTANT i64 2
  ; UNPACKED-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p1) = nuw inbounds G_PTR_ADD [[PTR_ADD]], [[C4]](i64)
  ; UNPACKED-NEXT:   G_STORE [[TRUNC1]](i32), [[PTR_ADD]](p1) :: (store (s16) into %ir.ptr + 4, align 4, addrspace 1)
  ; UNPACKED-NEXT:   G_STORE [[LSHR1]](i32), [[PTR_ADD1]](p1) :: (store (s8) into %ir.ptr + 6, align 2, basealign 4, addrspace 1)
  ; UNPACKED-NEXT:   SI_RETURN
  store i55 %arg, ptr addrspace(1) %ptr, align 4
  ret void
}

define void @store_i56(ptr addrspace(1) %ptr, i56 %arg) #0 {
  ; UNPACKED-LABEL: name: store_i56
  ; UNPACKED: bb.1 (%ir-block.0):
  ; UNPACKED-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3
  ; UNPACKED-NEXT: {{  $}}
  ; UNPACKED-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $vgpr0
  ; UNPACKED-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $vgpr1
  ; UNPACKED-NEXT:   [[MV:%[0-9]+]]:_(p1) = G_MERGE_VALUES [[COPY]](i32), [[COPY1]](i32)
  ; UNPACKED-NEXT:   [[COPY2:%[0-9]+]]:_(i32) = COPY $vgpr2
  ; UNPACKED-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY $vgpr3
  ; UNPACKED-NEXT:   [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY2]](i32), [[COPY3]](i32)
  ; UNPACKED-NEXT:   [[COPY4:%[0-9]+]]:_(i64) = COPY [[MV1]](s64)
  ; UNPACKED-NEXT:   [[C:%[0-9]+]]:_(i32) = G_CONSTANT i32 32
  ; UNPACKED-NEXT:   [[LSHR:%[0-9]+]]:_(i64) = G_LSHR [[COPY4]], [[C]](i32)
  ; UNPACKED-NEXT:   [[C1:%[0-9]+]]:_(i64) = G_CONSTANT i64 4
  ; UNPACKED-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p1) = nuw inbounds G_PTR_ADD [[MV]], [[C1]](i64)
  ; UNPACKED-NEXT:   G_STORE [[COPY2]](i32), [[MV]](p1) :: (store (s32) into %ir.ptr, addrspace 1)
  ; UNPACKED-NEXT:   [[TRUNC:%[0-9]+]]:_(i32) = G_TRUNC [[LSHR]](i64)
  ; UNPACKED-NEXT:   [[C2:%[0-9]+]]:_(i32) = G_CONSTANT i32 16
  ; UNPACKED-NEXT:   [[LSHR1:%[0-9]+]]:_(i32) = G_LSHR [[TRUNC]], [[C2]](i32)
  ; UNPACKED-NEXT:   [[C3:%[0-9]+]]:_(i64) = G_CONSTANT i64 2
  ; UNPACKED-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p1) = nuw inbounds G_PTR_ADD [[PTR_ADD]], [[C3]](i64)
  ; UNPACKED-NEXT:   G_STORE [[TRUNC]](i32), [[PTR_ADD]](p1) :: (store (s16) into %ir.ptr + 4, align 4, addrspace 1)
  ; UNPACKED-NEXT:   G_STORE [[LSHR1]](i32), [[PTR_ADD1]](p1) :: (store (s8) into %ir.ptr + 6, align 2, basealign 4, addrspace 1)
  ; UNPACKED-NEXT:   SI_RETURN
  store i56 %arg, ptr addrspace(1) %ptr, align 4
  ret void
}

define void @store_i65(ptr addrspace(1) %ptr, i65 %arg) #0 {
  ; UNPACKED-LABEL: name: store_i65
  ; UNPACKED: bb.1 (%ir-block.0):
  ; UNPACKED-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4
  ; UNPACKED-NEXT: {{  $}}
  ; UNPACKED-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $vgpr0
  ; UNPACKED-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $vgpr1
  ; UNPACKED-NEXT:   [[MV:%[0-9]+]]:_(p1) = G_MERGE_VALUES [[COPY]](i32), [[COPY1]](i32)
  ; UNPACKED-NEXT:   [[COPY2:%[0-9]+]]:_(i32) = COPY $vgpr2
  ; UNPACKED-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY $vgpr3
  ; UNPACKED-NEXT:   [[COPY4:%[0-9]+]]:_(i32) = COPY $vgpr4
  ; UNPACKED-NEXT:   [[DEF:%[0-9]+]]:_(i32) = G_IMPLICIT_DEF
  ; UNPACKED-NEXT:   [[MV1:%[0-9]+]]:_(i64) = G_MERGE_VALUES [[COPY2]](i32), [[COPY3]](i32)
  ; UNPACKED-NEXT:   [[MV2:%[0-9]+]]:_(i64) = G_MERGE_VALUES [[COPY4]](i32), [[DEF]](i32)
  ; UNPACKED-NEXT:   [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 -1
  ; UNPACKED-NEXT:   [[C1:%[0-9]+]]:_(i64) = G_CONSTANT i64 1
  ; UNPACKED-NEXT:   [[AND:%[0-9]+]]:_(i64) = G_AND [[MV1]], [[C]]
  ; UNPACKED-NEXT:   [[AND1:%[0-9]+]]:_(i64) = G_AND [[MV2]], [[C1]]
  ; UNPACKED-NEXT:   [[C2:%[0-9]+]]:_(i64) = G_CONSTANT i64 8
  ; UNPACKED-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p1) = nuw inbounds G_PTR_ADD [[MV]], [[C2]](i64)
  ; UNPACKED-NEXT:   G_STORE [[AND]](i64), [[MV]](p1) :: (store (s64) into %ir.ptr, align 4, addrspace 1)
  ; UNPACKED-NEXT:   [[TRUNC:%[0-9]+]]:_(i32) = G_TRUNC [[AND1]](i64)
  ; UNPACKED-NEXT:   G_STORE [[TRUNC]](i32), [[PTR_ADD]](p1) :: (store (s8) into %ir.ptr + 8, align 4, addrspace 1)
  ; UNPACKED-NEXT:   SI_RETURN
  store i65 %arg, ptr addrspace(1) %ptr, align 4
  ret void
}

define void @store_i95(ptr addrspace(1) %ptr, i95 %arg) #0 {
  ; UNPACKED-LABEL: name: store_i95
  ; UNPACKED: bb.1 (%ir-block.0):
  ; UNPACKED-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4
  ; UNPACKED-NEXT: {{  $}}
  ; UNPACKED-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $vgpr0
  ; UNPACKED-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $vgpr1
  ; UNPACKED-NEXT:   [[MV:%[0-9]+]]:_(p1) = G_MERGE_VALUES [[COPY]](i32), [[COPY1]](i32)
  ; UNPACKED-NEXT:   [[COPY2:%[0-9]+]]:_(i32) = COPY $vgpr2
  ; UNPACKED-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY $vgpr3
  ; UNPACKED-NEXT:   [[COPY4:%[0-9]+]]:_(i32) = COPY $vgpr4
  ; UNPACKED-NEXT:   [[DEF:%[0-9]+]]:_(i32) = G_IMPLICIT_DEF
  ; UNPACKED-NEXT:   [[MV1:%[0-9]+]]:_(i64) = G_MERGE_VALUES [[COPY2]](i32), [[COPY3]](i32)
  ; UNPACKED-NEXT:   [[MV2:%[0-9]+]]:_(i64) = G_MERGE_VALUES [[COPY4]](i32), [[DEF]](i32)
  ; UNPACKED-NEXT:   [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 -1
  ; UNPACKED-NEXT:   [[C1:%[0-9]+]]:_(i64) = G_CONSTANT i64 2147483647
  ; UNPACKED-NEXT:   [[AND:%[0-9]+]]:_(i64) = G_AND [[MV1]], [[C]]
  ; UNPACKED-NEXT:   [[AND1:%[0-9]+]]:_(i64) = G_AND [[MV2]], [[C1]]
  ; UNPACKED-NEXT:   [[C2:%[0-9]+]]:_(i64) = G_CONSTANT i64 8
  ; UNPACKED-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p1) = nuw inbounds G_PTR_ADD [[MV]], [[C2]](i64)
  ; UNPACKED-NEXT:   G_STORE [[AND]](i64), [[MV]](p1) :: (store (s64) into %ir.ptr, align 4, addrspace 1)
  ; UNPACKED-NEXT:   [[TRUNC:%[0-9]+]]:_(i32) = G_TRUNC [[AND1]](i64)
  ; UNPACKED-NEXT:   G_STORE [[TRUNC]](i32), [[PTR_ADD]](p1) :: (store (s32) into %ir.ptr + 8, addrspace 1)
  ; UNPACKED-NEXT:   SI_RETURN
  store i95 %arg, ptr addrspace(1) %ptr, align 4
  ret void
}

define void @store_i96(ptr addrspace(1) %ptr, i96 %arg) #0 {
  ; UNPACKED-LABEL: name: store_i96
  ; UNPACKED: bb.1 (%ir-block.0):
  ; UNPACKED-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4
  ; UNPACKED-NEXT: {{  $}}
  ; UNPACKED-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $vgpr0
  ; UNPACKED-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $vgpr1
  ; UNPACKED-NEXT:   [[MV:%[0-9]+]]:_(p1) = G_MERGE_VALUES [[COPY]](i32), [[COPY1]](i32)
  ; UNPACKED-NEXT:   [[COPY2:%[0-9]+]]:_(i32) = COPY $vgpr2
  ; UNPACKED-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY $vgpr3
  ; UNPACKED-NEXT:   [[COPY4:%[0-9]+]]:_(i32) = COPY $vgpr4
  ; UNPACKED-NEXT:   [[MV1:%[0-9]+]]:_(i96) = G_MERGE_VALUES [[COPY2]](i32), [[COPY3]](i32), [[COPY4]](i32)
  ; UNPACKED-NEXT:   [[BITCAST:%[0-9]+]]:_(<3 x i32>) = G_BITCAST [[MV1]](i96)
  ; UNPACKED-NEXT:   G_STORE [[BITCAST]](<3 x i32>), [[MV]](p1) :: (store (<3 x i32>) into %ir.ptr, align 4, addrspace 1)
  ; UNPACKED-NEXT:   SI_RETURN
  store i96 %arg, ptr addrspace(1) %ptr, align 4
  ret void
}

define void @store_i97(ptr addrspace(1) %ptr, i97 %arg) #0 {
  ; UNPACKED-LABEL: name: store_i97
  ; UNPACKED: bb.1 (%ir-block.0):
  ; UNPACKED-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5
  ; UNPACKED-NEXT: {{  $}}
  ; UNPACKED-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $vgpr0
  ; UNPACKED-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $vgpr1
  ; UNPACKED-NEXT:   [[MV:%[0-9]+]]:_(p1) = G_MERGE_VALUES [[COPY]](i32), [[COPY1]](i32)
  ; UNPACKED-NEXT:   [[COPY2:%[0-9]+]]:_(i32) = COPY $vgpr2
  ; UNPACKED-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY $vgpr3
  ; UNPACKED-NEXT:   [[COPY4:%[0-9]+]]:_(i32) = COPY $vgpr4
  ; UNPACKED-NEXT:   [[COPY5:%[0-9]+]]:_(i32) = COPY $vgpr5
  ; UNPACKED-NEXT:   [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 -1
  ; UNPACKED-NEXT:   [[C1:%[0-9]+]]:_(i64) = G_CONSTANT i64 8589934591
  ; UNPACKED-NEXT:   [[MV1:%[0-9]+]]:_(i64) = G_MERGE_VALUES [[COPY2]](i32), [[COPY3]](i32)
  ; UNPACKED-NEXT:   [[MV2:%[0-9]+]]:_(i64) = G_MERGE_VALUES [[COPY4]](i32), [[COPY5]](i32)
  ; UNPACKED-NEXT:   [[AND:%[0-9]+]]:_(i64) = G_AND [[MV1]], [[C]]
  ; UNPACKED-NEXT:   [[AND1:%[0-9]+]]:_(i64) = G_AND [[MV2]], [[C1]]
  ; UNPACKED-NEXT:   [[C2:%[0-9]+]]:_(i64) = G_CONSTANT i64 8
  ; UNPACKED-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p1) = nuw inbounds G_PTR_ADD [[MV]], [[C2]](i64)
  ; UNPACKED-NEXT:   G_STORE [[AND]](i64), [[MV]](p1) :: (store (s64) into %ir.ptr, align 4, addrspace 1)
  ; UNPACKED-NEXT:   [[C3:%[0-9]+]]:_(i32) = G_CONSTANT i32 32
  ; UNPACKED-NEXT:   [[LSHR:%[0-9]+]]:_(i64) = G_LSHR [[AND1]], [[C3]](i32)
  ; UNPACKED-NEXT:   [[C4:%[0-9]+]]:_(i64) = G_CONSTANT i64 4
  ; UNPACKED-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p1) = nuw inbounds G_PTR_ADD [[PTR_ADD]], [[C4]](i64)
  ; UNPACKED-NEXT:   [[TRUNC:%[0-9]+]]:_(i32) = G_TRUNC [[AND1]](i64)
  ; UNPACKED-NEXT:   G_STORE [[TRUNC]](i32), [[PTR_ADD]](p1) :: (store (s32) into %ir.ptr + 8, addrspace 1)
  ; UNPACKED-NEXT:   [[TRUNC1:%[0-9]+]]:_(i32) = G_TRUNC [[LSHR]](i64)
  ; UNPACKED-NEXT:   G_STORE [[TRUNC1]](i32), [[PTR_ADD1]](p1) :: (store (s8) into %ir.ptr + 12, align 4, addrspace 1)
  ; UNPACKED-NEXT:   SI_RETURN
  store i97 %arg, ptr addrspace(1) %ptr, align 4
  ret void
}

define void @store_i127(ptr addrspace(1) %ptr, i127 %arg) #0 {
  ; UNPACKED-LABEL: name: store_i127
  ; UNPACKED: bb.1 (%ir-block.0):
  ; UNPACKED-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5
  ; UNPACKED-NEXT: {{  $}}
  ; UNPACKED-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $vgpr0
  ; UNPACKED-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $vgpr1
  ; UNPACKED-NEXT:   [[MV:%[0-9]+]]:_(p1) = G_MERGE_VALUES [[COPY]](i32), [[COPY1]](i32)
  ; UNPACKED-NEXT:   [[COPY2:%[0-9]+]]:_(i32) = COPY $vgpr2
  ; UNPACKED-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY $vgpr3
  ; UNPACKED-NEXT:   [[COPY4:%[0-9]+]]:_(i32) = COPY $vgpr4
  ; UNPACKED-NEXT:   [[COPY5:%[0-9]+]]:_(i32) = COPY $vgpr5
  ; UNPACKED-NEXT:   [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 -1
  ; UNPACKED-NEXT:   [[C1:%[0-9]+]]:_(i64) = G_CONSTANT i64 9223372036854775807
  ; UNPACKED-NEXT:   [[MV1:%[0-9]+]]:_(i64) = G_MERGE_VALUES [[COPY2]](i32), [[COPY3]](i32)
  ; UNPACKED-NEXT:   [[MV2:%[0-9]+]]:_(i64) = G_MERGE_VALUES [[COPY4]](i32), [[COPY5]](i32)
  ; UNPACKED-NEXT:   [[AND:%[0-9]+]]:_(i64) = G_AND [[MV1]], [[C]]
  ; UNPACKED-NEXT:   [[AND1:%[0-9]+]]:_(i64) = G_AND [[MV2]], [[C1]]
  ; UNPACKED-NEXT:   [[MV3:%[0-9]+]]:_(i128) = G_MERGE_VALUES [[AND]](i64), [[AND1]](i64)
  ; UNPACKED-NEXT:   [[BITCAST:%[0-9]+]]:_(<4 x i32>) = G_BITCAST [[MV3]](i128)
  ; UNPACKED-NEXT:   G_STORE [[BITCAST]](<4 x i32>), [[MV]](p1) :: (store (<4 x i32>) into %ir.ptr, align 4, addrspace 1)
  ; UNPACKED-NEXT:   SI_RETURN
  store i127 %arg, ptr addrspace(1) %ptr, align 4
  ret void
}

attributes #0 = { nounwind }
