// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %clang_cc1 -triple loongarch64 -emit-llvm -o - %s | FileCheck %s --check-prefixes=CHECK-LA64
// RUN: %clang_cc1 -triple loongarch32 -emit-llvm -o - %s | FileCheck %s --check-prefixes=CHECK-LA32

// CHECK-LA64-LABEL: define dso_local void @_Z3fooDF16b
// CHECK-LA64-SAME: (bfloat noundef [[B:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-LA64-NEXT:  entry:
// CHECK-LA64-NEXT:    [[B_ADDR:%.*]] = alloca bfloat, align 2
// CHECK-LA64-NEXT:    store bfloat [[B]], ptr [[B_ADDR]], align 2
// CHECK-LA64-NEXT:    ret void
//
// CHECK-LA32-LABEL: define dso_local void @_Z3fooDF16b
// CHECK-LA32-SAME: (bfloat noundef [[B:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-LA32-NEXT:  entry:
// CHECK-LA32-NEXT:    [[B_ADDR:%.*]] = alloca bfloat, align 2
// CHECK-LA32-NEXT:    store bfloat [[B]], ptr [[B_ADDR]], align 2
// CHECK-LA32-NEXT:    ret void
//
void foo(__bf16 b) {}
