; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+zfbfmin \
; RUN:   -verify-machineinstrs -target-abi ilp32f | \
; RUN:   FileCheck -check-prefixes=CHECK %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+zfbfmin \
; RUN:   -verify-machineinstrs -target-abi lp64f | \
; RUN:   FileCheck -check-prefixes=CHECK %s

define bfloat @fminimum_bf16(bfloat %a, bfloat %b) nounwind {
; CHECK-LABEL: fminimum_bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcvt.s.bf16 fa4, fa1
; CHECK-NEXT:    fcvt.s.bf16 fa5, fa0
; CHECK-NEXT:    feq.s a0, fa5, fa5
; CHECK-NEXT:    fmv.s fa3, fa4
; CHECK-NEXT:    bnez a0, .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    fmv.s fa3, fa5
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    feq.s a0, fa4, fa4
; CHECK-NEXT:    bnez a0, .LBB0_4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    fmv.s fa5, fa4
; CHECK-NEXT:  .LBB0_4:
; CHECK-NEXT:    fmin.s fa5, fa5, fa3
; CHECK-NEXT:    fcvt.bf16.s fa0, fa5
; CHECK-NEXT:    ret
  %1 = call bfloat @llvm.minimum.bf16(bfloat %a, bfloat %b)
  ret bfloat %1
}

define bfloat @fmaximum_bf16(bfloat %a, bfloat %b) nounwind {
; CHECK-LABEL: fmaximum_bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcvt.s.bf16 fa4, fa1
; CHECK-NEXT:    fcvt.s.bf16 fa5, fa0
; CHECK-NEXT:    feq.s a0, fa5, fa5
; CHECK-NEXT:    fmv.s fa3, fa4
; CHECK-NEXT:    bnez a0, .LBB1_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    fmv.s fa3, fa5
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    feq.s a0, fa4, fa4
; CHECK-NEXT:    bnez a0, .LBB1_4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    fmv.s fa5, fa4
; CHECK-NEXT:  .LBB1_4:
; CHECK-NEXT:    fmax.s fa5, fa5, fa3
; CHECK-NEXT:    fcvt.bf16.s fa0, fa5
; CHECK-NEXT:    ret
  %1 = call bfloat @llvm.maximum.bf16(bfloat %a, bfloat %b)
  ret bfloat %1
}

define bfloat @fminimum_nnan_bf16(bfloat %a, bfloat %b) nounwind {
; CHECK-LABEL: fminimum_nnan_bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcvt.s.bf16 fa5, fa1
; CHECK-NEXT:    fcvt.s.bf16 fa4, fa0
; CHECK-NEXT:    fmin.s fa5, fa4, fa5
; CHECK-NEXT:    fcvt.bf16.s fa0, fa5
; CHECK-NEXT:    ret
  %1 = call nnan bfloat @llvm.minimum.bf16(bfloat %a, bfloat %b)
  ret bfloat %1
}

define bfloat @fmaximum_nnan_bf16(bfloat %a, bfloat %b) nounwind {
; CHECK-LABEL: fmaximum_nnan_bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcvt.s.bf16 fa5, fa1
; CHECK-NEXT:    fcvt.s.bf16 fa4, fa0
; CHECK-NEXT:    fmax.s fa5, fa4, fa5
; CHECK-NEXT:    fcvt.bf16.s fa0, fa5
; CHECK-NEXT:    ret
  %1 = call nnan bfloat @llvm.maximum.bf16(bfloat %a, bfloat %b)
  ret bfloat %1
}

define bfloat @fminimum_nnan_op_bf16(bfloat %a, bfloat %b) nounwind {
; CHECK-LABEL: fminimum_nnan_op_bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcvt.s.bf16 fa5, fa0
; CHECK-NEXT:    feq.s a0, fa5, fa5
; CHECK-NEXT:    bnez a0, .LBB4_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    fmv.s fa4, fa5
; CHECK-NEXT:    j .LBB4_3
; CHECK-NEXT:  .LBB4_2:
; CHECK-NEXT:    fadd.s fa4, fa5, fa5
; CHECK-NEXT:    fcvt.bf16.s fa4, fa4
; CHECK-NEXT:    fcvt.s.bf16 fa4, fa4
; CHECK-NEXT:  .LBB4_3:
; CHECK-NEXT:    fmin.s fa5, fa5, fa4
; CHECK-NEXT:    fcvt.bf16.s fa0, fa5
; CHECK-NEXT:    ret
  %c = fadd nnan bfloat %a, %a
  %1 = call bfloat @llvm.minimum.bf16(bfloat %a, bfloat %c)
  ret bfloat %1
}

define bfloat @fmaximum_nnan_op_bf16(bfloat %a, bfloat %b) nounwind {
; CHECK-LABEL: fmaximum_nnan_op_bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcvt.s.bf16 fa5, fa1
; CHECK-NEXT:    fcvt.s.bf16 fa4, fa0
; CHECK-NEXT:    fadd.s fa3, fa4, fa5
; CHECK-NEXT:    fsub.s fa5, fa4, fa5
; CHECK-NEXT:    fcvt.bf16.s fa4, fa3
; CHECK-NEXT:    fcvt.bf16.s fa5, fa5
; CHECK-NEXT:    fcvt.s.bf16 fa5, fa5
; CHECK-NEXT:    fcvt.s.bf16 fa4, fa4
; CHECK-NEXT:    fmax.s fa5, fa4, fa5
; CHECK-NEXT:    fcvt.bf16.s fa0, fa5
; CHECK-NEXT:    ret
  %c = fadd nnan bfloat %a, %b
  %d = fsub nnan bfloat %a, %b
  %1 = call bfloat @llvm.maximum.bf16(bfloat %c, bfloat %d)
  ret bfloat %1
}
