; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=riscv32 -mattr=+zfbfmin -verify-machineinstrs \
; RUN:   -target-abi ilp32f < %s | FileCheck %s
; RUN: llc -mtriple=riscv64 -mattr=+zfbfmin -verify-machineinstrs \
; RUN:   -target-abi lp64f < %s | FileCheck %s

define zeroext i1 @bfloat_is_nan(bfloat %a) nounwind {
; CHECK-LABEL: bfloat_is_nan:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcvt.s.bf16 fa5, fa0
; CHECK-NEXT:    feq.s a0, fa5, fa5
; CHECK-NEXT:    xori a0, a0, 1
; CHECK-NEXT:    ret
  %1 = fcmp uno bfloat %a, 0.000000e+00
  ret i1 %1
}

define zeroext i1 @bfloat_not_nan(bfloat %a) nounwind {
; CHECK-LABEL: bfloat_not_nan:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcvt.s.bf16 fa5, fa0
; CHECK-NEXT:    feq.s a0, fa5, fa5
; CHECK-NEXT:    ret
  %1 = fcmp ord bfloat %a, 0.000000e+00
  ret i1 %1
}
