; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32I

@addr = global ptr zeroinitializer

define void @test_blockaddress() nounwind {
; RV32I-LABEL: test_blockaddress:
; RV32I:       # %bb.0:
; RV32I-NEXT:    lui a0, %hi(addr)
; RV32I-NEXT:    lui a1, %hi(.Ltmp0)
; RV32I-NEXT:    addi a1, a1, %lo(.Ltmp0)
; RV32I-NEXT:    sw a1, %lo(addr)(a0)
; RV32I-NEXT:    lw a0, %lo(addr)(a0)
; RV32I-NEXT:    jr a0
; RV32I-NEXT:  .Ltmp0: # Block address taken
; RV32I-NEXT:  .LBB0_1: # %block
; RV32I-NEXT:    ret
  store volatile ptr blockaddress(@test_blockaddress, %block), ptr @addr
  %val = load volatile ptr, ptr @addr
  indirectbr ptr %val, [label %block]

block:
  ret void
}
