; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -verify-machineinstrs -filetype=obj < %s \
; RUN:   -o /dev/null 2>&1
; RUN: llc -mtriple=riscv32 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; This file contains tests similar to branch-relaxation-rv32.ll but with
; cf-protection-branch module flag enabled.
; Software-guarded branches should use t2 (x7) for the target address.

define void @relax_bcc(i1 %a) nounwind {
; CHECK-LABEL: relax_bcc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lpad 0
; CHECK-NEXT:    andi a0, a0, 1
; CHECK-NEXT:    bnez a0, .LBB0_1
; CHECK-NEXT:    j .LBB0_2
; CHECK-NEXT:  .LBB0_1: # %iftrue
; CHECK-NEXT:    #APP
; CHECK-NEXT:    .zero 4096
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:  .LBB0_2: # %tail
; CHECK-NEXT:    ret
  br i1 %a, label %iftrue, label %tail

iftrue:
  call void asm sideeffect ".space 4096", ""()
  br label %tail

tail:
  ret void
}

define i32 @relax_jal(i1 %a) nounwind {
; CHECK-LABEL: relax_jal:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lpad 0
; CHECK-NEXT:    andi a0, a0, 1
; CHECK-NEXT:    bnez a0, .LBB1_1
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jump .LBB1_2, t2
; CHECK-NEXT:  .LBB1_1: # %iftrue
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    sw ra, 60(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s0, 56(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s1, 52(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s2, 48(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s3, 44(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s4, 40(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s5, 36(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s6, 32(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s7, 28(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s8, 24(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s9, 20(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s10, 16(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s11, 12(sp) # 4-byte Folded Spill
; CHECK-NEXT:    #APP
; CHECK-NEXT:    # clobber lots of registers
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    #APP
; CHECK-NEXT:    .zero 1048576
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    lw ra, 60(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s0, 56(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s1, 52(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s2, 48(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s3, 44(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s4, 40(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s5, 36(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s6, 32(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s7, 28(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s8, 24(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s9, 20(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s10, 16(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s11, 12(sp) # 4-byte Folded Reload
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:  .LBB1_2: # %tail
; CHECK-NEXT:    ret
  br i1 %a, label %iftrue, label %iffalse

iftrue:
  call void asm sideeffect "# clobber lots of registers", "~{x1},~{x3},~{x4},~{x5},~{x6},~{x7},~{x8},~{x9},~{x10},~{x11},~{x12},~{x13},~{x14},~{x15},~{x16},~{x17},~{x18},~{x19},~{x20},~{x21},~{x22},~{x23},~{x24},~{x25},~{x26},~{x27},~{x28},~{x29},~{x30},~{x31}"()
  call void asm sideeffect ".space 1048576", ""()
  br label %tail

iffalse:
  br label %tail

tail:
  %val = phi i32 [1, %iftrue], [0, %iffalse]
  ret i32 %val
}

!llvm.module.flags = !{!0}
!0 = !{i32 8, !"cf-protection-branch", i32 1}
