# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc %s -mtriple=riscv64 \
# RUN: -run-pass=cfi-instr-inserter \
# RUN: -riscv-enable-cfi-instr-inserter=true \
# RUN: -o - | FileCheck %s

# Technically, it is possible that a callee-saved register is saved in multiple different locations.

---
name: multiple_locations
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: multiple_locations
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $x10, $x9, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BEQ $x10, $x0, %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $x10, $x9, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $x5 = COPY $x9
  ; CHECK-NEXT:   CFI_INSTRUCTION register $x9, $x5
  ; CHECK-NEXT:   $x9 = COPY $x5
  ; CHECK-NEXT:   CFI_INSTRUCTION register $x9, $x9
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $x10, $x9, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   SD $x9, $x2, 0 :: (store (s64))
  ; CHECK-NEXT:   CFI_INSTRUCTION offset $x9, 0
  ; CHECK-NEXT:   $x9 = LD $x2, 0 :: (load (s64))
  ; CHECK-NEXT:   CFI_INSTRUCTION register $x9, $x9
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   PseudoRET
  bb.0.entry:
    liveins: $x10, $x9, $x2
    BEQ $x10, $x0, %bb.2

  bb.1:
    liveins: $x10, $x9, $x2
    $x5 = COPY $x9
    CFI_INSTRUCTION register $x9, $x5
    $x9 = COPY $x5
    CFI_INSTRUCTION register $x9, $x9
    PseudoBR %bb.3

  bb.2:
    liveins: $x10, $x9, $x2
    SD $x9, $x2, 0 :: (store (s64))
    CFI_INSTRUCTION offset $x9, 0
    $x9  = LD $x2, 0 :: (load (s64))
    CFI_INSTRUCTION register $x9, $x9
    PseudoBR %bb.3

  bb.3:
    PseudoRET
...
