# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -verify-machineinstrs -O3 -march=riscv64 -run-pass register-coalescer -o - %s| FileCheck %s

---
name:            foo
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: foo
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   undef [[PseudoVMV_S_X:%[0-9]+]].sub_vrm1_0:vrm8 = PseudoVMV_S_X undef [[PseudoVMV_S_X]].sub_vrm1_0, [[COPY1]], 16, 6 /* e64 */
  ; CHECK-NEXT:   undef [[PseudoVMV_S_X:%[0-9]+]].sub_vrm1_0:vrm8 = PseudoVMV_S_X [[PseudoVMV_S_X]].sub_vrm1_0, $x0, 16, 6 /* e64 */
  ; CHECK-NEXT:   undef [[PseudoVMV_V_I_M1_:%[0-9]+]].sub_vrm1_0:vrm2 = PseudoVMV_V_I_M1 undef [[PseudoVMV_V_I_M1_]].sub_vrm1_0, 1, 16, 6 /* e64 */, 0 /* tu, mu */
  ; CHECK-NEXT:   [[PseudoVMV_V_I_M1_:%[0-9]+]].sub_vrm1_1:vrm2 = INIT_UNDEF
  ; CHECK-NEXT:   undef [[COPY2:%[0-9]+]].sub_vrm2_0:vrm8 = COPY [[PseudoVMV_S_X]].sub_vrm2_0
  ; CHECK-NEXT:   early-clobber [[COPY2]].sub_vrm2_0:vrm8 = PseudoVSLIDEUP_VI_M2 [[COPY2]].sub_vrm2_0, [[PseudoVMV_V_I_M1_]], 2, 3, 6 /* e64 */, 0 /* tu, mu */
  ; CHECK-NEXT:   [[PseudoVMV_S_X:%[0-9]+]].sub_vrm4_1:vrm8 = INIT_UNDEF
  ; CHECK-NEXT:   [[PseudoVMV_S_X:%[0-9]+]].sub_vrm2_1:vrm8 = INIT_UNDEF
  ; CHECK-NEXT:   [[PseudoVMV_S_X:%[0-9]+]].sub_vrm1_1:vrm8 = INIT_UNDEF
  ; CHECK-NEXT:   early-clobber %19:vr = PseudoVMSLE_VI_M8 [[PseudoVMV_S_X]], -1, 16, 6 /* e64 */
  ; CHECK-NEXT:   [[PseudoVMV_X_S:%[0-9]+]]:gpr = PseudoVMV_X_S %19, 4 /* e16 */
  ; CHECK-NEXT:   undef [[PseudoVMV_S_X1:%[0-9]+]].sub_vrm1_0:vrm2 = PseudoVMV_S_X undef [[PseudoVMV_S_X1]].sub_vrm1_0, $x0, 16, 6 /* e64 */
  ; CHECK-NEXT:   [[PseudoVMV_S_X1:%[0-9]+]].sub_vrm1_1:vrm2 = INIT_UNDEF
  ; CHECK-NEXT:   early-clobber [[COPY2]].sub_vrm2_0:vrm8 = PseudoVSLIDEUP_VI_M2 [[COPY2]].sub_vrm2_0, [[PseudoVMV_S_X1]], 3, 4, 6 /* e64 */, 0 /* tu, mu */
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]].sub_vrm4_1:vrm8 = INIT_UNDEF
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]].sub_vrm2_1:vrm8 = INIT_UNDEF
  ; CHECK-NEXT:   early-clobber %32:vr = PseudoVMSLE_VI_M8 [[COPY2]], -1, 16, 6 /* e64 */
  ; CHECK-NEXT:   [[PseudoVMV_X_S1:%[0-9]+]]:gpr = PseudoVMV_X_S %32, 4 /* e16 */
  ; CHECK-NEXT:   [[SLLI:%[0-9]+]]:gpr = SLLI [[PseudoVMV_X_S1]], 48
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BNE [[SLLI]], $x0, %bb.1
  ; CHECK-NEXT:   PseudoBR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ANDI:%[0-9]+]]:gpr = ANDI [[COPY]], 1
  ; CHECK-NEXT:   BNE [[ANDI]], $x0, %bb.4
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.8(0x50000000), %bb.7(0x30000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BNE [[PseudoVMV_X_S]], $x0, %bb.8
  ; CHECK-NEXT:   PseudoBR %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.6(0x50000000), %bb.5(0x30000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BNE [[PseudoVMV_X_S1]], $x0, %bb.6
  ; CHECK-NEXT:   PseudoBR %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   PseudoRET
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   PseudoRET
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   PseudoRET
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8:
  ; CHECK-NEXT:   PseudoRET
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x10, $x11

    %4:gpr = COPY killed $x11
    %3:gpr = COPY killed $x10
    %6:vr = PseudoVMV_S_X undef %6, killed %3, 16, 6 /* e64 */
    %12:gpr = COPY $x0
    %13:vr = COPY killed %6
    %13:vr = PseudoVMV_S_X %13, %12, 16, 6 /* e64 */
    undef %14.sub_vrm1_0:vrm8 = COPY killed %13
    %16:vrm2 = COPY %14.sub_vrm2_0
    %17:vr = PseudoVMV_V_I_M1 undef %17, 1, 16, 6 /* e64 */, 0 /* tu, mu */
    undef %18.sub_vrm1_0:vrm2 = COPY killed %17
    %36:vrnov0 = INIT_UNDEF
    %37:vrm2 = COPY killed %18
    %37.sub_vrm1_1:vrm2 = COPY killed %36
    %20:vrm2 = COPY killed %16
    early-clobber %20:vrm2 = PseudoVSLIDEUP_VI_M2 %20, killed %37, 2, 3, 6 /* e64 */, 0 /* tu, mu */
    %38:vrm4nov0 = INIT_UNDEF
    %39:vrm8 = COPY %14
    %39.sub_vrm4_1:vrm8 = COPY killed %38
    %40:vrm2nov0 = INIT_UNDEF
    %41:vrm8 = COPY killed %39
    %41.sub_vrm2_1:vrm8 = COPY killed %40
    %42:vrnov0 = INIT_UNDEF
    %43:vrm8 = COPY killed %41
    %43.sub_vrm1_1:vrm8 = COPY killed %42
    early-clobber %21:vr = PseudoVMSLE_VI_M8 killed %43, -1, 16, 6 /* e64 */
    %22:vr = COPY killed %21
    %1:gpr = PseudoVMV_X_S killed %22, 4 /* e16 */
    %24:vr = PseudoVMV_S_X undef %24, killed %12, 16, 6 /* e64 */
    undef %25.sub_vrm1_0:vrm2 = COPY killed %24
    %45:vrnov0 = INIT_UNDEF
    %46:vrm2 = COPY killed %25
    %46.sub_vrm1_1:vrm2 = COPY killed %45
    %27:vrm2 = COPY killed %20
    early-clobber %27:vrm2 = PseudoVSLIDEUP_VI_M2 %27, killed %46, 3, 4, 6 /* e64 */, 0 /* tu, mu */
    %28:vrm8 = COPY killed %14
    %28.sub_vrm2_0:vrm8 = COPY killed %27
    %47:vrm4nov0 = INIT_UNDEF
    %48:vrm8 = COPY killed %28
    %48.sub_vrm4_1:vrm8 = COPY killed %47
    %49:vrm2nov0 = INIT_UNDEF
    %50:vrm8 = COPY killed %48
    %50.sub_vrm2_1:vrm8 = COPY killed %49
    early-clobber %29:vr = PseudoVMSLE_VI_M8 killed %50, -1, 16, 6 /* e64 */
    %30:vr = COPY killed %29
    %2:gpr = PseudoVMV_X_S killed %30, 4 /* e16 */
    %32:gpr = SLLI %2, 48

  bb.1:
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)

    BNE %32, $x0, %bb.1
    PseudoBR %bb.2

  bb.2:
    successors: %bb.4(0x40000000), %bb.3(0x40000000)

    %33:gpr = ANDI killed %4, 1
    BNE killed %33, $x0, %bb.4
    PseudoBR %bb.3

  bb.3:
    successors: %bb.8(0x50000000), %bb.7(0x30000000)

    BNE killed %1, $x0, %bb.8
    PseudoBR %bb.7

  bb.4:
    successors: %bb.6(0x50000000), %bb.5(0x30000000)

    BNE killed %2, $x0, %bb.6
    PseudoBR %bb.5

  bb.5:
    PseudoRET

  bb.6:
    PseudoRET

  bb.7:
    PseudoRET

  bb.8:
    PseudoRET
