# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -verify-coalescing -mtriple=riscv64 -run-pass=register-coalescer -o - %s| FileCheck %s

---
name:            foo
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: foo
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   undef [[PseudoVMV_S_X:%[0-9]+]].sub_vrm1_0:vrm8 = PseudoVMV_S_X undef [[PseudoVMV_S_X]].sub_vrm1_0, [[COPY1]], 16 /* vl */, 6 /* e64 */
  ; CHECK-NEXT:   undef [[PseudoVMV_S_X:%[0-9]+]].sub_vrm1_0:vrm8 = PseudoVMV_S_X [[PseudoVMV_S_X]].sub_vrm1_0, $x0, 16 /* vl */, 6 /* e64 */
  ; CHECK-NEXT:   undef [[PseudoVMV_V_I_M1_:%[0-9]+]].sub_vrm1_0:vrm2 = PseudoVMV_V_I_M1 undef [[PseudoVMV_V_I_M1_]].sub_vrm1_0, 1, 16 /* vl */, 6 /* e64 */, 0 /* tu, mu */
  ; CHECK-NEXT:   [[PseudoVMV_V_I_M1_:%[0-9]+]].sub_vrm1_1:vrm2 = INIT_UNDEF
  ; CHECK-NEXT:   undef [[COPY2:%[0-9]+]].sub_vrm2_0:vrm8 = COPY [[PseudoVMV_S_X]].sub_vrm2_0
  ; CHECK-NEXT:   early-clobber [[COPY2]].sub_vrm2_0:vrm8 = PseudoVSLIDEUP_VI_M2 [[COPY2]].sub_vrm2_0, [[PseudoVMV_V_I_M1_]], 2, 3 /* vl */, 6 /* e64 */, 0 /* tu, mu */
  ; CHECK-NEXT:   [[PseudoVMV_S_X:%[0-9]+]].sub_vrm4_1:vrm8 = INIT_UNDEF
  ; CHECK-NEXT:   [[PseudoVMV_S_X:%[0-9]+]].sub_vrm2_1:vrm8 = INIT_UNDEF
  ; CHECK-NEXT:   [[PseudoVMV_S_X:%[0-9]+]].sub_vrm1_1:vrm8 = INIT_UNDEF
  ; CHECK-NEXT:   early-clobber %19:vr = PseudoVMSLE_VI_M8 [[PseudoVMV_S_X]], -1, 16 /* vl */, 6 /* e64 */
  ; CHECK-NEXT:   [[PseudoVMV_X_S:%[0-9]+]]:gpr = PseudoVMV_X_S %19, 4 /* e16 */
  ; CHECK-NEXT:   undef [[PseudoVMV_S_X1:%[0-9]+]].sub_vrm1_0:vrm2 = PseudoVMV_S_X undef [[PseudoVMV_S_X1]].sub_vrm1_0, $x0, 16 /* vl */, 6 /* e64 */
  ; CHECK-NEXT:   [[PseudoVMV_S_X1:%[0-9]+]].sub_vrm1_1:vrm2 = INIT_UNDEF
  ; CHECK-NEXT:   early-clobber [[COPY2]].sub_vrm2_0:vrm8 = PseudoVSLIDEUP_VI_M2 [[COPY2]].sub_vrm2_0, [[PseudoVMV_S_X1]], 3, 4 /* vl */, 6 /* e64 */, 0 /* tu, mu */
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]].sub_vrm4_1:vrm8 = INIT_UNDEF
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]].sub_vrm2_1:vrm8 = INIT_UNDEF
  ; CHECK-NEXT:   early-clobber %32:vr = PseudoVMSLE_VI_M8 [[COPY2]], -1, 16 /* vl */, 6 /* e64 */
  ; CHECK-NEXT:   [[PseudoVMV_X_S1:%[0-9]+]]:gpr = PseudoVMV_X_S %32, 4 /* e16 */
  ; CHECK-NEXT:   [[SLLI:%[0-9]+]]:gpr = SLLI [[PseudoVMV_X_S1]], 48
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BNE [[SLLI]], $x0, %bb.1
  ; CHECK-NEXT:   PseudoBR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ANDI:%[0-9]+]]:gpr = ANDI [[COPY]], 1
  ; CHECK-NEXT:   BNE [[ANDI]], $x0, %bb.4
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.8(0x50000000), %bb.7(0x30000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BNE [[PseudoVMV_X_S]], $x0, %bb.8
  ; CHECK-NEXT:   PseudoBR %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.6(0x50000000), %bb.5(0x30000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BNE [[PseudoVMV_X_S1]], $x0, %bb.6
  ; CHECK-NEXT:   PseudoBR %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   PseudoRET
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   PseudoRET
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   PseudoRET
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8:
  ; CHECK-NEXT:   PseudoRET
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x10, $x11

    %0:gpr = COPY killed $x11
    %1:gpr = COPY killed $x10
    %2:vr  = PseudoVMV_S_X undef %2, killed %1, 16, 6
    %3:gpr = COPY $x0
    %4:vr  = COPY killed %2
    %4:vr  = PseudoVMV_S_X %4, %3, 16, 6
    undef %5.sub_vrm1_0:vrm8 = COPY killed %4
    %6:vrm2 = COPY %5.sub_vrm2_0
    %7:vr  = PseudoVMV_V_I_M1 undef %7, 1, 16, 6, 0
    undef %8.sub_vrm1_0:vrm2 = COPY killed %7
    %9:vrnov0 = INIT_UNDEF
    %10:vrm2 = COPY killed %8
    %10.sub_vrm1_1:vrm2 = COPY killed %9
    %11:vrm2 = COPY killed %6
    early-clobber %11:vrm2 = PseudoVSLIDEUP_VI_M2 %11, killed %10, 2, 3, 6, 0
    %12:vrm4nov0 = INIT_UNDEF
    %13:vrm8 = COPY %5
    %13.sub_vrm4_1:vrm8 = COPY killed %12
    %14:vrm2nov0 = INIT_UNDEF
    %15:vrm8 = COPY killed %13
    %15.sub_vrm2_1:vrm8 = COPY killed %14
    %16:vrnov0 = INIT_UNDEF
    %17:vrm8 = COPY killed %15
    %17.sub_vrm1_1:vrm8 = COPY killed %16
    early-clobber %18:vr = PseudoVMSLE_VI_M8 killed %17, -1, 16, 6
    %19:vr = COPY killed %18
    %20:gpr = PseudoVMV_X_S killed %19, 4
    %21:vr = PseudoVMV_S_X undef %21, killed %3, 16, 6
    undef %22.sub_vrm1_0:vrm2 = COPY killed %21
    %23:vrnov0 = INIT_UNDEF
    %24:vrm2 = COPY killed %22
    %24.sub_vrm1_1:vrm2 = COPY killed %23
    %25:vrm2 = COPY killed %11
    early-clobber %25:vrm2 = PseudoVSLIDEUP_VI_M2 %25, killed %24, 3, 4, 6, 0
    %26:vrm8 = COPY killed %5
    %26.sub_vrm2_0:vrm8 = COPY killed %25
    %27:vrm4nov0 = INIT_UNDEF
    %28:vrm8 = COPY killed %26
    %28.sub_vrm4_1:vrm8 = COPY killed %27
    %29:vrm2nov0 = INIT_UNDEF
    %30:vrm8 = COPY killed %28
    %30.sub_vrm2_1:vrm8 = COPY killed %29
    early-clobber %31:vr = PseudoVMSLE_VI_M8 killed %30, -1, 16, 6
    %32:vr = COPY killed %31
    %33:gpr = PseudoVMV_X_S killed %32, 4
    %34:gpr = SLLI %33, 48

  bb.1:
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)
    BNE %34, $x0, %bb.1
    PseudoBR %bb.2

  bb.2:
    successors: %bb.4(0x40000000), %bb.3(0x40000000)
    %35:gpr = ANDI killed %0, 1
    BNE killed %35, $x0, %bb.4
    PseudoBR %bb.3

  bb.3:
    successors: %bb.8(0x50000000), %bb.7(0x30000000)
    BNE killed %20, $x0, %bb.8
    PseudoBR %bb.7

  bb.4:
    successors: %bb.6(0x50000000), %bb.5(0x30000000)
    BNE killed %33, $x0, %bb.6
    PseudoBR %bb.5

  bb.5:
    PseudoRET

  bb.6:
    PseudoRET

  bb.7:
    PseudoRET

  bb.8:
    PseudoRET
