# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc %s -mtriple=riscv64 -run-pass=compute-live-ins -o - | FileCheck %s

---
name:            compute_live_ins
body:             |
  ; CHECK-LABEL: name: compute_live_ins
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $x10, $x12
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $x11 = ADDI $x10, 1
  ; CHECK-NEXT:   BEQ $x10, $x0, %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $x12
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $x12 = ADDI $x12, 1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET
  bb.0:
    $x11 = ADDI $x10, 1
    BEQ $x10, $x0, %bb.2

  bb.1:
    $x12 = ADDI $x12, 1

  bb.2:
    PseudoRET
...
