; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 -riscv-cbc-max-branch=4 < %s | FileCheck %s
; RUN: llc -mtriple=riscv64 -riscv-cbc-max-branch=4 < %s | FileCheck %s

;
; Test whether a chain of consecutive conditional branches needs to be broken.

define void @func(i32 noundef signext %0, ptr noundef %1, ptr noundef %2, ptr noundef %3, ptr noundef %4, ptr noundef %5, ptr noundef %6, ptr noundef %7) {
; CHECK:      # %bb.0:
; CHECK-NEXT:	  beqz	a6, .LBB0_7
; CHECK-NEXT:	# %bb.1:
; CHECK-NEXT:		beqz	a5, .LBB0_7
; CHECK-NEXT:	# %bb.2:
; CHECK-NEXT:		beqz	a4, .LBB0_7
; CHECK-NEXT:	# %bb.3:
; CHECK-NEXT:		seqz	a0, a3
; CHECK-NEXT:		seqz	a2, a2
; CHECK-NEXT:		or	a0, a0, a2
; CHECK-NEXT:		bnez	a0, .LBB0_7
; CHECK-NEXT:	# %bb.4:
; CHECK-NEXT:		beqz	a1, .LBB0_7
; CHECK-NEXT:	# %bb.5:
; CHECK-NEXT:		beqz	a7, .LBB0_7
; CHECK-NEXT:	# %bb.6:
; CHECK-NEXT:		ret
  %9 = icmp eq ptr %7, null
  %10 = icmp eq ptr %1, null
  %11 = or i1 %10, %9
  %12 = icmp eq ptr %2, null
  %13 = or i1 %12, %11
  %14 = icmp eq ptr %3, null
  %15 = or i1 %14, %13
  %16 = icmp eq ptr %4, null
  %17 = or i1 %16, %15
  %18 = icmp eq ptr %5, null
  %19 = or i1 %18, %17
  %20 = icmp eq ptr %6, null
  %21 = or i1 %20, %19
  br i1 %21, label %22, label %25

22:
  tail call void @exit(i32 noundef signext -1) #2
  unreachable

25:
  ret void
}

; Function Attrs: nofree noreturn nounwind
declare void @exit(i32 noundef signext) local_unnamed_addr #1
