# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# RUN: llc -mtriple=riscv64  -run-pass=prologepilog  -o - %s \
# RUN:   | FileCheck %s -check-prefixes=RV64I
# RUN: llc -mtriple=riscv64 -mattr=+zcmp  -run-pass=prologepilog  -o - %s \
# RUN:   | FileCheck %s -check-prefixes=RV64I-ZCMP
# RUN: llc -mtriple=riscv64 -frame-pointer=all  -run-pass=prologepilog  -o - %s \
# RUN:   | FileCheck %s -check-prefixes=RV64I-FP
# RUN: llc -mtriple=riscv64 -mattr=+zcmp -frame-pointer=all  -run-pass=prologepilog  -o - %s \
# RUN:   | FileCheck %s -check-prefixes=RV64I-ZCMP-FP
# RUN: llc -mtriple=riscv64 -mattr=+save-restore  -run-pass=prologepilog  -o - %s \
# RUN:   | FileCheck %s -check-prefixes=RV64I-SR

--- |
  define void @csr_modified() { entry: unreachable }
  define void @csr_not_modified() { entry: unreachable }
  define void @calls_unwind_init() {
  entry:
    call void @llvm.eh.unwind.init()
    ret void
  }
  declare void @llvm.eh.unwind.init()
  define void @naked_no_saves() naked { entry: unreachable }
  define void @noreturn_nounwind_still_saves() noreturn nounwind { entry: unreachable }
  define void @fp_forces_ra_fp() { entry: unreachable }
  define void @bp_saves_x9(i64 %n) {
  entry:
    %v = alloca i32, i64 %n, align 64
    ret void
  }
  define void @zcmp_x26_forces_x27() { entry: unreachable }
  define void @save_restore_libcall() { entry: unreachable }
  define void @interrupt_saves_caller_saved() "interrupt"="machine" { entry: unreachable }
...

---
name:            csr_modified
tracksRegLiveness: true
frameInfo:
  maxCallFrameSize: 0
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body: |
  bb.0:
    ; RV64I-LABEL: name: csr_modified
    ; RV64I: liveins: $x18, $x19
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 16
    ; RV64I-NEXT: frame-setup SD killed $x18, $x2, 8 :: (store (s64) into %stack.0)
    ; RV64I-NEXT: frame-setup SD killed $x19, $x2, 0 :: (store (s64) into %stack.1)
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -8
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -16
    ; RV64I-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-NEXT: $x19 = IMPLICIT_DEF
    ; RV64I-NEXT: $x18 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.0)
    ; RV64I-NEXT: $x19 = frame-destroy LD $x2, 0 :: (load (s64) from %stack.1)
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x19
    ; RV64I-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-LABEL: name: csr_modified
    ; RV64I-ZCMP: liveins: $x18, $x19
    ; RV64I-ZCMP-NEXT: {{  $}}
    ; RV64I-ZCMP-NEXT: frame-setup CM_PUSH 8, 0, implicit-def $x2, implicit $x2, implicit $x1, implicit $x8, implicit $x9, implicit $x18, implicit $x19
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 48
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -16
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -8
    ; RV64I-ZCMP-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: $x19 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: frame-destroy CM_POP 8, 0, implicit-def $x2, implicit $x2, implicit-def $x1, implicit-def $x8, implicit-def $x9, implicit-def $x18, implicit-def $x19
    ; RV64I-ZCMP-NEXT: PseudoRET
    ;
    ; RV64I-FP-LABEL: name: csr_modified
    ; RV64I-FP: liveins: $x1, $x18, $x19
    ; RV64I-FP-NEXT: {{  $}}
    ; RV64I-FP-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; RV64I-FP-NEXT: frame-setup SD killed $x1, $x2, 24 :: (store (s64) into %stack.0)
    ; RV64I-FP-NEXT: frame-setup SD killed $x8, $x2, 16 :: (store (s64) into %stack.1)
    ; RV64I-FP-NEXT: frame-setup SD killed $x18, $x2, 8 :: (store (s64) into %stack.2)
    ; RV64I-FP-NEXT: frame-setup SD killed $x19, $x2, 0 :: (store (s64) into %stack.3)
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -24
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -32
    ; RV64I-FP-NEXT: $x8 = frame-setup ADDI $x2, 32
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-FP-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: $x19 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 32
    ; RV64I-FP-NEXT: $x1 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.0)
    ; RV64I-FP-NEXT: $x8 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.1)
    ; RV64I-FP-NEXT: $x18 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.2)
    ; RV64I-FP-NEXT: $x19 = frame-destroy LD $x2, 0 :: (load (s64) from %stack.3)
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x19
    ; RV64I-FP-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-FP-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-FP-LABEL: name: csr_modified
    ; RV64I-ZCMP-FP: liveins: $x1, $x18, $x19
    ; RV64I-ZCMP-FP-NEXT: {{  $}}
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x1, $x2, 24 :: (store (s64) into %stack.0)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x8, $x2, 16 :: (store (s64) into %stack.1)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x18, $x2, 8 :: (store (s64) into %stack.2)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x19, $x2, 0 :: (store (s64) into %stack.3)
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -24
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -32
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-setup ADDI $x2, 32
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-ZCMP-FP-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: $x19 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 32
    ; RV64I-ZCMP-FP-NEXT: $x1 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.0)
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.1)
    ; RV64I-ZCMP-FP-NEXT: $x18 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.2)
    ; RV64I-ZCMP-FP-NEXT: $x19 = frame-destroy LD $x2, 0 :: (load (s64) from %stack.3)
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x19
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-ZCMP-FP-NEXT: PseudoRET
    ;
    ; RV64I-SR-LABEL: name: csr_modified
    ; RV64I-SR: liveins: $x18, $x19
    ; RV64I-SR-NEXT: {{  $}}
    ; RV64I-SR-NEXT: $x5 = frame-setup PseudoCALLReg target-flags(riscv-call) &__riscv_save_4, implicit $x2, implicit-def $x2, implicit $x18, implicit $x19
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 48
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -32
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -40
    ; RV64I-SR-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: $x19 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: frame-destroy PseudoTAIL target-flags(riscv-call) &__riscv_restore_4, implicit $x2, implicit-def $x2, implicit-def $x18, implicit-def $x19
    $x18 = IMPLICIT_DEF
    $x19 = IMPLICIT_DEF
    PseudoRET
...

---
name:            csr_not_modified
tracksRegLiveness: true
frameInfo:
  maxCallFrameSize: 0
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body: |
  bb.0:
    ; RV64I-LABEL: name: csr_not_modified
    ; RV64I: PseudoRET
    ;
    ; RV64I-ZCMP-LABEL: name: csr_not_modified
    ; RV64I-ZCMP: PseudoRET
    ;
    ; RV64I-FP-LABEL: name: csr_not_modified
    ; RV64I-FP: liveins: $x1
    ; RV64I-FP-NEXT: {{  $}}
    ; RV64I-FP-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 16
    ; RV64I-FP-NEXT: frame-setup SD killed $x1, $x2, 8 :: (store (s64) into %stack.0)
    ; RV64I-FP-NEXT: frame-setup SD killed $x8, $x2, 0 :: (store (s64) into %stack.1)
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-FP-NEXT: $x8 = frame-setup ADDI $x2, 16
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 16
    ; RV64I-FP-NEXT: $x1 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.0)
    ; RV64I-FP-NEXT: $x8 = frame-destroy LD $x2, 0 :: (load (s64) from %stack.1)
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-FP-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-FP-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-FP-LABEL: name: csr_not_modified
    ; RV64I-ZCMP-FP: liveins: $x1
    ; RV64I-ZCMP-FP-NEXT: {{  $}}
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 16
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x1, $x2, 8 :: (store (s64) into %stack.0)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x8, $x2, 0 :: (store (s64) into %stack.1)
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-setup ADDI $x2, 16
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 16
    ; RV64I-ZCMP-FP-NEXT: $x1 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.0)
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-destroy LD $x2, 0 :: (load (s64) from %stack.1)
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-ZCMP-FP-NEXT: PseudoRET
    ;
    ; RV64I-SR-LABEL: name: csr_not_modified
    ; RV64I-SR: PseudoRET
    PseudoRET
...

---
name:            calls_unwind_init
tracksRegLiveness: true
callsUnwindInit: true
frameInfo:
  maxCallFrameSize: 0
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body: |
  bb.0:
    ; RV64I-LABEL: name: calls_unwind_init
    ; RV64I: liveins: $x1, $x8, $x9, $x18, $x19, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x27
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: $x2 = frame-setup ADDI $x2, -112
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 112
    ; RV64I-NEXT: frame-setup SD killed $x1, $x2, 104 :: (store (s64) into %stack.0)
    ; RV64I-NEXT: frame-setup SD killed $x8, $x2, 96 :: (store (s64) into %stack.1)
    ; RV64I-NEXT: frame-setup SD killed $x9, $x2, 88 :: (store (s64) into %stack.2)
    ; RV64I-NEXT: frame-setup SD killed $x18, $x2, 80 :: (store (s64) into %stack.3)
    ; RV64I-NEXT: frame-setup SD killed $x19, $x2, 72 :: (store (s64) into %stack.4)
    ; RV64I-NEXT: frame-setup SD killed $x20, $x2, 64 :: (store (s64) into %stack.5)
    ; RV64I-NEXT: frame-setup SD killed $x21, $x2, 56 :: (store (s64) into %stack.6)
    ; RV64I-NEXT: frame-setup SD killed $x22, $x2, 48 :: (store (s64) into %stack.7)
    ; RV64I-NEXT: frame-setup SD killed $x23, $x2, 40 :: (store (s64) into %stack.8)
    ; RV64I-NEXT: frame-setup SD killed $x24, $x2, 32 :: (store (s64) into %stack.9)
    ; RV64I-NEXT: frame-setup SD killed $x25, $x2, 24 :: (store (s64) into %stack.10)
    ; RV64I-NEXT: frame-setup SD killed $x26, $x2, 16 :: (store (s64) into %stack.11)
    ; RV64I-NEXT: frame-setup SD killed $x27, $x2, 8 :: (store (s64) into %stack.12)
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x9, -24
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -32
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -40
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x20, -48
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x21, -56
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x22, -64
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x23, -72
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x24, -80
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x25, -88
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -96
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x27, -104
    ; RV64I-NEXT: $x1 = frame-destroy LD $x2, 104 :: (load (s64) from %stack.0)
    ; RV64I-NEXT: $x8 = frame-destroy LD $x2, 96 :: (load (s64) from %stack.1)
    ; RV64I-NEXT: $x9 = frame-destroy LD $x2, 88 :: (load (s64) from %stack.2)
    ; RV64I-NEXT: $x18 = frame-destroy LD $x2, 80 :: (load (s64) from %stack.3)
    ; RV64I-NEXT: $x19 = frame-destroy LD $x2, 72 :: (load (s64) from %stack.4)
    ; RV64I-NEXT: $x20 = frame-destroy LD $x2, 64 :: (load (s64) from %stack.5)
    ; RV64I-NEXT: $x21 = frame-destroy LD $x2, 56 :: (load (s64) from %stack.6)
    ; RV64I-NEXT: $x22 = frame-destroy LD $x2, 48 :: (load (s64) from %stack.7)
    ; RV64I-NEXT: $x23 = frame-destroy LD $x2, 40 :: (load (s64) from %stack.8)
    ; RV64I-NEXT: $x24 = frame-destroy LD $x2, 32 :: (load (s64) from %stack.9)
    ; RV64I-NEXT: $x25 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.10)
    ; RV64I-NEXT: $x26 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.11)
    ; RV64I-NEXT: $x27 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.12)
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x9
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x19
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x20
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x21
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x22
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x23
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x24
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x25
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x26
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x27
    ; RV64I-NEXT: $x2 = frame-destroy ADDI $x2, 112
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-LABEL: name: calls_unwind_init
    ; RV64I-ZCMP: liveins: $x1, $x8, $x9, $x18, $x19, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x27
    ; RV64I-ZCMP-NEXT: {{  $}}
    ; RV64I-ZCMP-NEXT: frame-setup CM_PUSH 15, 0, implicit-def $x2, implicit $x2, implicit $x1, implicit $x8, implicit $x9, implicit $x18, implicit $x19, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24, implicit $x25, implicit $x26, implicit $x27
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 112
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -104
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -96
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x9, -88
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -80
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -72
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x20, -64
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x21, -56
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x22, -48
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x23, -40
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x24, -32
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x25, -24
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -16
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x27, -8
    ; RV64I-ZCMP-NEXT: frame-destroy CM_POP 15, 0, implicit-def $x2, implicit $x2, implicit-def $x1, implicit-def $x8, implicit-def $x9, implicit-def $x18, implicit-def $x19, implicit-def $x20, implicit-def $x21, implicit-def $x22, implicit-def $x23, implicit-def $x24, implicit-def $x25, implicit-def $x26, implicit-def $x27
    ; RV64I-ZCMP-NEXT: PseudoRET
    ;
    ; RV64I-FP-LABEL: name: calls_unwind_init
    ; RV64I-FP: liveins: $x1, $x9, $x18, $x19, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x27
    ; RV64I-FP-NEXT: {{  $}}
    ; RV64I-FP-NEXT: $x2 = frame-setup ADDI $x2, -112
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 112
    ; RV64I-FP-NEXT: frame-setup SD killed $x1, $x2, 104 :: (store (s64) into %stack.0)
    ; RV64I-FP-NEXT: frame-setup SD killed $x8, $x2, 96 :: (store (s64) into %stack.1)
    ; RV64I-FP-NEXT: frame-setup SD killed $x9, $x2, 88 :: (store (s64) into %stack.2)
    ; RV64I-FP-NEXT: frame-setup SD killed $x18, $x2, 80 :: (store (s64) into %stack.3)
    ; RV64I-FP-NEXT: frame-setup SD killed $x19, $x2, 72 :: (store (s64) into %stack.4)
    ; RV64I-FP-NEXT: frame-setup SD killed $x20, $x2, 64 :: (store (s64) into %stack.5)
    ; RV64I-FP-NEXT: frame-setup SD killed $x21, $x2, 56 :: (store (s64) into %stack.6)
    ; RV64I-FP-NEXT: frame-setup SD killed $x22, $x2, 48 :: (store (s64) into %stack.7)
    ; RV64I-FP-NEXT: frame-setup SD killed $x23, $x2, 40 :: (store (s64) into %stack.8)
    ; RV64I-FP-NEXT: frame-setup SD killed $x24, $x2, 32 :: (store (s64) into %stack.9)
    ; RV64I-FP-NEXT: frame-setup SD killed $x25, $x2, 24 :: (store (s64) into %stack.10)
    ; RV64I-FP-NEXT: frame-setup SD killed $x26, $x2, 16 :: (store (s64) into %stack.11)
    ; RV64I-FP-NEXT: frame-setup SD killed $x27, $x2, 8 :: (store (s64) into %stack.12)
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x9, -24
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -32
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -40
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x20, -48
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x21, -56
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x22, -64
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x23, -72
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x24, -80
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x25, -88
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -96
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x27, -104
    ; RV64I-FP-NEXT: $x8 = frame-setup ADDI $x2, 112
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 112
    ; RV64I-FP-NEXT: $x1 = frame-destroy LD $x2, 104 :: (load (s64) from %stack.0)
    ; RV64I-FP-NEXT: $x8 = frame-destroy LD $x2, 96 :: (load (s64) from %stack.1)
    ; RV64I-FP-NEXT: $x9 = frame-destroy LD $x2, 88 :: (load (s64) from %stack.2)
    ; RV64I-FP-NEXT: $x18 = frame-destroy LD $x2, 80 :: (load (s64) from %stack.3)
    ; RV64I-FP-NEXT: $x19 = frame-destroy LD $x2, 72 :: (load (s64) from %stack.4)
    ; RV64I-FP-NEXT: $x20 = frame-destroy LD $x2, 64 :: (load (s64) from %stack.5)
    ; RV64I-FP-NEXT: $x21 = frame-destroy LD $x2, 56 :: (load (s64) from %stack.6)
    ; RV64I-FP-NEXT: $x22 = frame-destroy LD $x2, 48 :: (load (s64) from %stack.7)
    ; RV64I-FP-NEXT: $x23 = frame-destroy LD $x2, 40 :: (load (s64) from %stack.8)
    ; RV64I-FP-NEXT: $x24 = frame-destroy LD $x2, 32 :: (load (s64) from %stack.9)
    ; RV64I-FP-NEXT: $x25 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.10)
    ; RV64I-FP-NEXT: $x26 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.11)
    ; RV64I-FP-NEXT: $x27 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.12)
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x9
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x19
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x20
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x21
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x22
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x23
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x24
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x25
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x26
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x27
    ; RV64I-FP-NEXT: $x2 = frame-destroy ADDI $x2, 112
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-FP-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-FP-LABEL: name: calls_unwind_init
    ; RV64I-ZCMP-FP: liveins: $x1, $x9, $x18, $x19, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x27
    ; RV64I-ZCMP-FP-NEXT: {{  $}}
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-setup ADDI $x2, -112
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 112
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x1, $x2, 104 :: (store (s64) into %stack.0)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x8, $x2, 96 :: (store (s64) into %stack.1)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x9, $x2, 88 :: (store (s64) into %stack.2)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x18, $x2, 80 :: (store (s64) into %stack.3)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x19, $x2, 72 :: (store (s64) into %stack.4)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x20, $x2, 64 :: (store (s64) into %stack.5)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x21, $x2, 56 :: (store (s64) into %stack.6)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x22, $x2, 48 :: (store (s64) into %stack.7)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x23, $x2, 40 :: (store (s64) into %stack.8)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x24, $x2, 32 :: (store (s64) into %stack.9)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x25, $x2, 24 :: (store (s64) into %stack.10)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x26, $x2, 16 :: (store (s64) into %stack.11)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x27, $x2, 8 :: (store (s64) into %stack.12)
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x9, -24
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -32
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -40
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x20, -48
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x21, -56
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x22, -64
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x23, -72
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x24, -80
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x25, -88
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -96
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x27, -104
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-setup ADDI $x2, 112
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 112
    ; RV64I-ZCMP-FP-NEXT: $x1 = frame-destroy LD $x2, 104 :: (load (s64) from %stack.0)
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-destroy LD $x2, 96 :: (load (s64) from %stack.1)
    ; RV64I-ZCMP-FP-NEXT: $x9 = frame-destroy LD $x2, 88 :: (load (s64) from %stack.2)
    ; RV64I-ZCMP-FP-NEXT: $x18 = frame-destroy LD $x2, 80 :: (load (s64) from %stack.3)
    ; RV64I-ZCMP-FP-NEXT: $x19 = frame-destroy LD $x2, 72 :: (load (s64) from %stack.4)
    ; RV64I-ZCMP-FP-NEXT: $x20 = frame-destroy LD $x2, 64 :: (load (s64) from %stack.5)
    ; RV64I-ZCMP-FP-NEXT: $x21 = frame-destroy LD $x2, 56 :: (load (s64) from %stack.6)
    ; RV64I-ZCMP-FP-NEXT: $x22 = frame-destroy LD $x2, 48 :: (load (s64) from %stack.7)
    ; RV64I-ZCMP-FP-NEXT: $x23 = frame-destroy LD $x2, 40 :: (load (s64) from %stack.8)
    ; RV64I-ZCMP-FP-NEXT: $x24 = frame-destroy LD $x2, 32 :: (load (s64) from %stack.9)
    ; RV64I-ZCMP-FP-NEXT: $x25 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.10)
    ; RV64I-ZCMP-FP-NEXT: $x26 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.11)
    ; RV64I-ZCMP-FP-NEXT: $x27 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.12)
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x9
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x19
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x20
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x21
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x22
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x23
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x24
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x25
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x26
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x27
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-destroy ADDI $x2, 112
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-ZCMP-FP-NEXT: PseudoRET
    ;
    ; RV64I-SR-LABEL: name: calls_unwind_init
    ; RV64I-SR: liveins: $x1, $x8, $x9, $x18, $x19, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x27
    ; RV64I-SR-NEXT: {{  $}}
    ; RV64I-SR-NEXT: $x5 = frame-setup PseudoCALLReg target-flags(riscv-call) &__riscv_save_12, implicit $x2, implicit-def $x2, implicit $x1, implicit $x8, implicit $x9, implicit $x18, implicit $x19, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24, implicit $x25, implicit $x26, implicit $x27
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 112
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x9, -24
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -32
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -40
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x20, -48
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x21, -56
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x22, -64
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x23, -72
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x24, -80
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x25, -88
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -96
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x27, -104
    ; RV64I-SR-NEXT: frame-destroy PseudoTAIL target-flags(riscv-call) &__riscv_restore_12, implicit $x2, implicit-def $x2, implicit-def $x1, implicit-def $x8, implicit-def $x9, implicit-def $x18, implicit-def $x19, implicit-def $x20, implicit-def $x21, implicit-def $x22, implicit-def $x23, implicit-def $x24, implicit-def $x25, implicit-def $x26, implicit-def $x27
    PseudoRET
...

---
name:            naked_no_saves
tracksRegLiveness: true
frameInfo:
  maxCallFrameSize: 0
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body: |
  bb.0:
    ; RV64I-LABEL: name: naked_no_saves
    ; RV64I: PseudoRET
    ;
    ; RV64I-ZCMP-LABEL: name: naked_no_saves
    ; RV64I-ZCMP: PseudoRET
    ;
    ; RV64I-FP-LABEL: name: naked_no_saves
    ; RV64I-FP: PseudoRET
    ;
    ; RV64I-ZCMP-FP-LABEL: name: naked_no_saves
    ; RV64I-ZCMP-FP: PseudoRET
    ;
    ; RV64I-SR-LABEL: name: naked_no_saves
    ; RV64I-SR: PseudoRET
    PseudoRET
...

---
name:            noreturn_nounwind_still_saves
tracksRegLiveness: true
frameInfo:
  maxCallFrameSize: 0
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body: |
  bb.0:
    ; RV64I-LABEL: name: noreturn_nounwind_still_saves
    ; RV64I: $x10 = IMPLICIT_DEF
    ; RV64I-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-LABEL: name: noreturn_nounwind_still_saves
    ; RV64I-ZCMP: $x10 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: PseudoRET
    ;
    ; RV64I-FP-LABEL: name: noreturn_nounwind_still_saves
    ; RV64I-FP: liveins: $x1
    ; RV64I-FP-NEXT: {{  $}}
    ; RV64I-FP-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; RV64I-FP-NEXT: frame-setup SD killed $x1, $x2, 8 :: (store (s64) into %stack.0)
    ; RV64I-FP-NEXT: frame-setup SD killed $x8, $x2, 0 :: (store (s64) into %stack.1)
    ; RV64I-FP-NEXT: $x8 = frame-setup ADDI $x2, 16
    ; RV64I-FP-NEXT: $x10 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: $x1 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.0)
    ; RV64I-FP-NEXT: $x8 = frame-destroy LD $x2, 0 :: (load (s64) from %stack.1)
    ; RV64I-FP-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; RV64I-FP-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-FP-LABEL: name: noreturn_nounwind_still_saves
    ; RV64I-ZCMP-FP: liveins: $x1
    ; RV64I-ZCMP-FP-NEXT: {{  $}}
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x1, $x2, 8 :: (store (s64) into %stack.0)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x8, $x2, 0 :: (store (s64) into %stack.1)
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-setup ADDI $x2, 16
    ; RV64I-ZCMP-FP-NEXT: $x10 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: $x1 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.0)
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-destroy LD $x2, 0 :: (load (s64) from %stack.1)
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; RV64I-ZCMP-FP-NEXT: PseudoRET
    ;
    ; RV64I-SR-LABEL: name: noreturn_nounwind_still_saves
    ; RV64I-SR: $x10 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: PseudoRET
    $x10 = IMPLICIT_DEF
    PseudoRET
...

---
name:            fp_forces_ra_fp
tracksRegLiveness: true
frameInfo:
  isFrameAddressTaken: true
  maxCallFrameSize: 0
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body: |
  bb.0:
    ; RV64I-LABEL: name: fp_forces_ra_fp
    ; RV64I: liveins: $x1, $x18
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; RV64I-NEXT: frame-setup SD killed $x1, $x2, 24 :: (store (s64) into %stack.0)
    ; RV64I-NEXT: frame-setup SD killed $x8, $x2, 16 :: (store (s64) into %stack.1)
    ; RV64I-NEXT: frame-setup SD killed $x18, $x2, 8 :: (store (s64) into %stack.2)
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -24
    ; RV64I-NEXT: $x8 = frame-setup ADDI $x2, 32
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 32
    ; RV64I-NEXT: $x1 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.0)
    ; RV64I-NEXT: $x8 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.1)
    ; RV64I-NEXT: $x18 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.2)
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; RV64I-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-LABEL: name: fp_forces_ra_fp
    ; RV64I-ZCMP: liveins: $x1, $x18
    ; RV64I-ZCMP-NEXT: {{  $}}
    ; RV64I-ZCMP-NEXT: frame-setup CM_PUSH 7, 0, implicit-def $x2, implicit $x2, implicit $x1, implicit $x8, implicit $x9, implicit $x18
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -32
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -24
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -8
    ; RV64I-ZCMP-NEXT: $x8 = frame-setup ADDI $x2, 32
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-ZCMP-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 32
    ; RV64I-ZCMP-NEXT: frame-destroy CM_POP 7, 0, implicit-def $x2, implicit $x2, implicit-def $x1, implicit-def $x8, implicit-def $x9, implicit-def $x18
    ; RV64I-ZCMP-NEXT: PseudoRET
    ;
    ; RV64I-FP-LABEL: name: fp_forces_ra_fp
    ; RV64I-FP: liveins: $x1, $x18
    ; RV64I-FP-NEXT: {{  $}}
    ; RV64I-FP-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; RV64I-FP-NEXT: frame-setup SD killed $x1, $x2, 24 :: (store (s64) into %stack.0)
    ; RV64I-FP-NEXT: frame-setup SD killed $x8, $x2, 16 :: (store (s64) into %stack.1)
    ; RV64I-FP-NEXT: frame-setup SD killed $x18, $x2, 8 :: (store (s64) into %stack.2)
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -24
    ; RV64I-FP-NEXT: $x8 = frame-setup ADDI $x2, 32
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-FP-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 32
    ; RV64I-FP-NEXT: $x1 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.0)
    ; RV64I-FP-NEXT: $x8 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.1)
    ; RV64I-FP-NEXT: $x18 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.2)
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; RV64I-FP-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-FP-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-FP-LABEL: name: fp_forces_ra_fp
    ; RV64I-ZCMP-FP: liveins: $x1, $x18
    ; RV64I-ZCMP-FP-NEXT: {{  $}}
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x1, $x2, 24 :: (store (s64) into %stack.0)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x8, $x2, 16 :: (store (s64) into %stack.1)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x18, $x2, 8 :: (store (s64) into %stack.2)
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -24
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-setup ADDI $x2, 32
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-ZCMP-FP-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 32
    ; RV64I-ZCMP-FP-NEXT: $x1 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.0)
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.1)
    ; RV64I-ZCMP-FP-NEXT: $x18 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.2)
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-ZCMP-FP-NEXT: PseudoRET
    ;
    ; RV64I-SR-LABEL: name: fp_forces_ra_fp
    ; RV64I-SR: liveins: $x1, $x18
    ; RV64I-SR-NEXT: {{  $}}
    ; RV64I-SR-NEXT: $x5 = frame-setup PseudoCALLReg target-flags(riscv-call) &__riscv_save_3, implicit $x2, implicit-def $x2, implicit $x1, implicit $x8, implicit $x18
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -32
    ; RV64I-SR-NEXT: $x8 = frame-setup ADDI $x2, 32
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-SR-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 32
    ; RV64I-SR-NEXT: frame-destroy PseudoTAIL target-flags(riscv-call) &__riscv_restore_3, implicit $x2, implicit-def $x2, implicit-def $x1, implicit-def $x8, implicit-def $x18
    $x18 = IMPLICIT_DEF
    PseudoRET
...

---
name:            bp_saves_x9
tracksRegLiveness: true
frameInfo:
  maxCallFrameSize: 0
  maxAlignment: 64
stack:
  - { id: 0, name: v, type: variable-sized, offset: 0, alignment: 64, stack-id: default,
      callee-saved-register: '', callee-saved-restored: true, local-offset: 0,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body: |
  bb.0:
    liveins: $x10
    ; RV64I-LABEL: name: bp_saves_x9
    ; RV64I: liveins: $x10, $x1, $x18
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: $x2 = frame-setup ADDI $x2, -64
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 64
    ; RV64I-NEXT: frame-setup SD killed $x1, $x2, 56 :: (store (s64) into %stack.1)
    ; RV64I-NEXT: frame-setup SD killed $x8, $x2, 48 :: (store (s64) into %stack.2)
    ; RV64I-NEXT: frame-setup SD killed $x9, $x2, 40 :: (store (s64) into %stack.3)
    ; RV64I-NEXT: frame-setup SD killed $x18, $x2, 32 :: (store (s64) into %stack.4)
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x9, -24
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -32
    ; RV64I-NEXT: $x8 = frame-setup ADDI $x2, 64
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-NEXT: $x2 = frame-setup ANDI $x2, -64
    ; RV64I-NEXT: $x9 = frame-setup ADDI $x2, 0
    ; RV64I-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-NEXT: $x2 = frame-destroy ADDI $x8, -64
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 64
    ; RV64I-NEXT: $x1 = frame-destroy LD $x2, 56 :: (load (s64) from %stack.1)
    ; RV64I-NEXT: $x8 = frame-destroy LD $x2, 48 :: (load (s64) from %stack.2)
    ; RV64I-NEXT: $x9 = frame-destroy LD $x2, 40 :: (load (s64) from %stack.3)
    ; RV64I-NEXT: $x18 = frame-destroy LD $x2, 32 :: (load (s64) from %stack.4)
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x9
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; RV64I-NEXT: $x2 = frame-destroy ADDI $x2, 64
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-LABEL: name: bp_saves_x9
    ; RV64I-ZCMP: liveins: $x10, $x1, $x18
    ; RV64I-ZCMP-NEXT: {{  $}}
    ; RV64I-ZCMP-NEXT: frame-setup CM_PUSH 7, 32, implicit-def $x2, implicit $x2, implicit $x1, implicit $x8, implicit $x9, implicit $x18
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 64
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -32
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -24
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x9, -16
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -8
    ; RV64I-ZCMP-NEXT: $x8 = frame-setup ADDI $x2, 64
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-ZCMP-NEXT: $x2 = frame-setup ANDI $x2, -64
    ; RV64I-ZCMP-NEXT: $x9 = frame-setup ADDI $x2, 0
    ; RV64I-ZCMP-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: $x2 = frame-destroy ADDI $x8, -64
    ; RV64I-ZCMP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 64
    ; RV64I-ZCMP-NEXT: frame-destroy CM_POP 7, 32, implicit-def $x2, implicit $x2, implicit-def $x1, implicit-def $x8, implicit-def $x9, implicit-def $x18
    ; RV64I-ZCMP-NEXT: PseudoRET
    ;
    ; RV64I-FP-LABEL: name: bp_saves_x9
    ; RV64I-FP: liveins: $x10, $x1, $x18
    ; RV64I-FP-NEXT: {{  $}}
    ; RV64I-FP-NEXT: $x2 = frame-setup ADDI $x2, -64
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 64
    ; RV64I-FP-NEXT: frame-setup SD killed $x1, $x2, 56 :: (store (s64) into %stack.1)
    ; RV64I-FP-NEXT: frame-setup SD killed $x8, $x2, 48 :: (store (s64) into %stack.2)
    ; RV64I-FP-NEXT: frame-setup SD killed $x9, $x2, 40 :: (store (s64) into %stack.3)
    ; RV64I-FP-NEXT: frame-setup SD killed $x18, $x2, 32 :: (store (s64) into %stack.4)
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x9, -24
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -32
    ; RV64I-FP-NEXT: $x8 = frame-setup ADDI $x2, 64
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-FP-NEXT: $x2 = frame-setup ANDI $x2, -64
    ; RV64I-FP-NEXT: $x9 = frame-setup ADDI $x2, 0
    ; RV64I-FP-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: $x2 = frame-destroy ADDI $x8, -64
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 64
    ; RV64I-FP-NEXT: $x1 = frame-destroy LD $x2, 56 :: (load (s64) from %stack.1)
    ; RV64I-FP-NEXT: $x8 = frame-destroy LD $x2, 48 :: (load (s64) from %stack.2)
    ; RV64I-FP-NEXT: $x9 = frame-destroy LD $x2, 40 :: (load (s64) from %stack.3)
    ; RV64I-FP-NEXT: $x18 = frame-destroy LD $x2, 32 :: (load (s64) from %stack.4)
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x9
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; RV64I-FP-NEXT: $x2 = frame-destroy ADDI $x2, 64
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-FP-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-FP-LABEL: name: bp_saves_x9
    ; RV64I-ZCMP-FP: liveins: $x10, $x1, $x18
    ; RV64I-ZCMP-FP-NEXT: {{  $}}
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-setup ADDI $x2, -64
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 64
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x1, $x2, 56 :: (store (s64) into %stack.1)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x8, $x2, 48 :: (store (s64) into %stack.2)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x9, $x2, 40 :: (store (s64) into %stack.3)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x18, $x2, 32 :: (store (s64) into %stack.4)
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x9, -24
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -32
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-setup ADDI $x2, 64
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-setup ANDI $x2, -64
    ; RV64I-ZCMP-FP-NEXT: $x9 = frame-setup ADDI $x2, 0
    ; RV64I-ZCMP-FP-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-destroy ADDI $x8, -64
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 64
    ; RV64I-ZCMP-FP-NEXT: $x1 = frame-destroy LD $x2, 56 :: (load (s64) from %stack.1)
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-destroy LD $x2, 48 :: (load (s64) from %stack.2)
    ; RV64I-ZCMP-FP-NEXT: $x9 = frame-destroy LD $x2, 40 :: (load (s64) from %stack.3)
    ; RV64I-ZCMP-FP-NEXT: $x18 = frame-destroy LD $x2, 32 :: (load (s64) from %stack.4)
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x9
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-destroy ADDI $x2, 64
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-ZCMP-FP-NEXT: PseudoRET
    ;
    ; RV64I-SR-LABEL: name: bp_saves_x9
    ; RV64I-SR: liveins: $x10, $x1, $x18
    ; RV64I-SR-NEXT: {{  $}}
    ; RV64I-SR-NEXT: $x5 = frame-setup PseudoCALLReg target-flags(riscv-call) &__riscv_save_3, implicit $x2, implicit-def $x2, implicit $x1, implicit $x8, implicit $x9, implicit $x18
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x9, -24
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -32
    ; RV64I-SR-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 64
    ; RV64I-SR-NEXT: $x8 = frame-setup ADDI $x2, 64
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-SR-NEXT: $x2 = frame-setup ANDI $x2, -64
    ; RV64I-SR-NEXT: $x9 = frame-setup ADDI $x2, 0
    ; RV64I-SR-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: $x2 = frame-destroy ADDI $x8, -64
    ; RV64I-SR-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 64
    ; RV64I-SR-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; RV64I-SR-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 32
    ; RV64I-SR-NEXT: frame-destroy PseudoTAIL target-flags(riscv-call) &__riscv_restore_3, implicit $x2, implicit-def $x2, implicit-def $x1, implicit-def $x8, implicit-def $x9, implicit-def $x18
    $x18 = IMPLICIT_DEF
    PseudoRET
...

---
name:            zcmp_x26_forces_x27
tracksRegLiveness: true
frameInfo:
  maxCallFrameSize: 0
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body: |
  bb.0:
    ; RV64I-LABEL: name: zcmp_x26_forces_x27
    ; RV64I: liveins: $x26
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 16
    ; RV64I-NEXT: frame-setup SD killed $x26, $x2, 8 :: (store (s64) into %stack.0)
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -8
    ; RV64I-NEXT: $x26 = IMPLICIT_DEF
    ; RV64I-NEXT: $x26 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.0)
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x26
    ; RV64I-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-LABEL: name: zcmp_x26_forces_x27
    ; RV64I-ZCMP: liveins: $x26, $x27
    ; RV64I-ZCMP-NEXT: {{  $}}
    ; RV64I-ZCMP-NEXT: frame-setup CM_PUSH 15, 0, implicit-def $x2, implicit $x2, implicit $x1, implicit $x8, implicit $x9, implicit $x18, implicit $x19, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24, implicit $x25, implicit $x26, implicit $x27
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 112
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -16
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x27, -8
    ; RV64I-ZCMP-NEXT: $x26 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: frame-destroy CM_POP 15, 0, implicit-def $x2, implicit $x2, implicit-def $x1, implicit-def $x8, implicit-def $x9, implicit-def $x18, implicit-def $x19, implicit-def $x20, implicit-def $x21, implicit-def $x22, implicit-def $x23, implicit-def $x24, implicit-def $x25, implicit-def $x26, implicit-def $x27
    ; RV64I-ZCMP-NEXT: PseudoRET
    ;
    ; RV64I-FP-LABEL: name: zcmp_x26_forces_x27
    ; RV64I-FP: liveins: $x1, $x26
    ; RV64I-FP-NEXT: {{  $}}
    ; RV64I-FP-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; RV64I-FP-NEXT: frame-setup SD killed $x1, $x2, 24 :: (store (s64) into %stack.0)
    ; RV64I-FP-NEXT: frame-setup SD killed $x8, $x2, 16 :: (store (s64) into %stack.1)
    ; RV64I-FP-NEXT: frame-setup SD killed $x26, $x2, 8 :: (store (s64) into %stack.2)
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -24
    ; RV64I-FP-NEXT: $x8 = frame-setup ADDI $x2, 32
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-FP-NEXT: $x26 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 32
    ; RV64I-FP-NEXT: $x1 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.0)
    ; RV64I-FP-NEXT: $x8 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.1)
    ; RV64I-FP-NEXT: $x26 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.2)
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x26
    ; RV64I-FP-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-FP-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-FP-LABEL: name: zcmp_x26_forces_x27
    ; RV64I-ZCMP-FP: liveins: $x1, $x26
    ; RV64I-ZCMP-FP-NEXT: {{  $}}
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x1, $x2, 24 :: (store (s64) into %stack.0)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x8, $x2, 16 :: (store (s64) into %stack.1)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x26, $x2, 8 :: (store (s64) into %stack.2)
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -24
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-setup ADDI $x2, 32
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-ZCMP-FP-NEXT: $x26 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 32
    ; RV64I-ZCMP-FP-NEXT: $x1 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.0)
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.1)
    ; RV64I-ZCMP-FP-NEXT: $x26 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.2)
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x26
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-ZCMP-FP-NEXT: PseudoRET
    ;
    ; RV64I-SR-LABEL: name: zcmp_x26_forces_x27
    ; RV64I-SR: liveins: $x26
    ; RV64I-SR-NEXT: {{  $}}
    ; RV64I-SR-NEXT: $x5 = frame-setup PseudoCALLReg target-flags(riscv-call) &__riscv_save_11, implicit $x2, implicit-def $x2, implicit $x26
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 96
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -96
    ; RV64I-SR-NEXT: $x26 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: frame-destroy PseudoTAIL target-flags(riscv-call) &__riscv_restore_11, implicit $x2, implicit-def $x2, implicit-def $x26
    $x26 = IMPLICIT_DEF
    PseudoRET
...

---
name:            save_restore_libcall
tracksRegLiveness: true
frameInfo:
  maxCallFrameSize: 0
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body: |
  bb.0:
    ; RV64I-LABEL: name: save_restore_libcall
    ; RV64I: liveins: $x18, $x19, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x27
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: $x2 = frame-setup ADDI $x2, -80
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 80
    ; RV64I-NEXT: frame-setup SD killed $x18, $x2, 72 :: (store (s64) into %stack.0)
    ; RV64I-NEXT: frame-setup SD killed $x19, $x2, 64 :: (store (s64) into %stack.1)
    ; RV64I-NEXT: frame-setup SD killed $x20, $x2, 56 :: (store (s64) into %stack.2)
    ; RV64I-NEXT: frame-setup SD killed $x21, $x2, 48 :: (store (s64) into %stack.3)
    ; RV64I-NEXT: frame-setup SD killed $x22, $x2, 40 :: (store (s64) into %stack.4)
    ; RV64I-NEXT: frame-setup SD killed $x23, $x2, 32 :: (store (s64) into %stack.5)
    ; RV64I-NEXT: frame-setup SD killed $x24, $x2, 24 :: (store (s64) into %stack.6)
    ; RV64I-NEXT: frame-setup SD killed $x25, $x2, 16 :: (store (s64) into %stack.7)
    ; RV64I-NEXT: frame-setup SD killed $x26, $x2, 8 :: (store (s64) into %stack.8)
    ; RV64I-NEXT: frame-setup SD killed $x27, $x2, 0 :: (store (s64) into %stack.9)
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -8
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -16
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x20, -24
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x21, -32
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x22, -40
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x23, -48
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x24, -56
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x25, -64
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -72
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x27, -80
    ; RV64I-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-NEXT: $x19 = IMPLICIT_DEF
    ; RV64I-NEXT: $x20 = IMPLICIT_DEF
    ; RV64I-NEXT: $x21 = IMPLICIT_DEF
    ; RV64I-NEXT: $x22 = IMPLICIT_DEF
    ; RV64I-NEXT: $x23 = IMPLICIT_DEF
    ; RV64I-NEXT: $x24 = IMPLICIT_DEF
    ; RV64I-NEXT: $x25 = IMPLICIT_DEF
    ; RV64I-NEXT: $x26 = IMPLICIT_DEF
    ; RV64I-NEXT: $x27 = IMPLICIT_DEF
    ; RV64I-NEXT: $x18 = frame-destroy LD $x2, 72 :: (load (s64) from %stack.0)
    ; RV64I-NEXT: $x19 = frame-destroy LD $x2, 64 :: (load (s64) from %stack.1)
    ; RV64I-NEXT: $x20 = frame-destroy LD $x2, 56 :: (load (s64) from %stack.2)
    ; RV64I-NEXT: $x21 = frame-destroy LD $x2, 48 :: (load (s64) from %stack.3)
    ; RV64I-NEXT: $x22 = frame-destroy LD $x2, 40 :: (load (s64) from %stack.4)
    ; RV64I-NEXT: $x23 = frame-destroy LD $x2, 32 :: (load (s64) from %stack.5)
    ; RV64I-NEXT: $x24 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.6)
    ; RV64I-NEXT: $x25 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.7)
    ; RV64I-NEXT: $x26 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.8)
    ; RV64I-NEXT: $x27 = frame-destroy LD $x2, 0 :: (load (s64) from %stack.9)
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x19
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x20
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x21
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x22
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x23
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x24
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x25
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x26
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x27
    ; RV64I-NEXT: $x2 = frame-destroy ADDI $x2, 80
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-LABEL: name: save_restore_libcall
    ; RV64I-ZCMP: liveins: $x18, $x19, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x27
    ; RV64I-ZCMP-NEXT: {{  $}}
    ; RV64I-ZCMP-NEXT: frame-setup CM_PUSH 15, 0, implicit-def $x2, implicit $x2, implicit $x1, implicit $x8, implicit $x9, implicit $x18, implicit $x19, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24, implicit $x25, implicit $x26, implicit $x27
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 112
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -80
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -72
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x20, -64
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x21, -56
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x22, -48
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x23, -40
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x24, -32
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x25, -24
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -16
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x27, -8
    ; RV64I-ZCMP-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: $x19 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: $x20 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: $x21 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: $x22 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: $x23 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: $x24 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: $x25 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: $x26 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: $x27 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: frame-destroy CM_POP 15, 0, implicit-def $x2, implicit $x2, implicit-def $x1, implicit-def $x8, implicit-def $x9, implicit-def $x18, implicit-def $x19, implicit-def $x20, implicit-def $x21, implicit-def $x22, implicit-def $x23, implicit-def $x24, implicit-def $x25, implicit-def $x26, implicit-def $x27
    ; RV64I-ZCMP-NEXT: PseudoRET
    ;
    ; RV64I-FP-LABEL: name: save_restore_libcall
    ; RV64I-FP: liveins: $x1, $x18, $x19, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x27
    ; RV64I-FP-NEXT: {{  $}}
    ; RV64I-FP-NEXT: $x2 = frame-setup ADDI $x2, -96
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 96
    ; RV64I-FP-NEXT: frame-setup SD killed $x1, $x2, 88 :: (store (s64) into %stack.0)
    ; RV64I-FP-NEXT: frame-setup SD killed $x8, $x2, 80 :: (store (s64) into %stack.1)
    ; RV64I-FP-NEXT: frame-setup SD killed $x18, $x2, 72 :: (store (s64) into %stack.2)
    ; RV64I-FP-NEXT: frame-setup SD killed $x19, $x2, 64 :: (store (s64) into %stack.3)
    ; RV64I-FP-NEXT: frame-setup SD killed $x20, $x2, 56 :: (store (s64) into %stack.4)
    ; RV64I-FP-NEXT: frame-setup SD killed $x21, $x2, 48 :: (store (s64) into %stack.5)
    ; RV64I-FP-NEXT: frame-setup SD killed $x22, $x2, 40 :: (store (s64) into %stack.6)
    ; RV64I-FP-NEXT: frame-setup SD killed $x23, $x2, 32 :: (store (s64) into %stack.7)
    ; RV64I-FP-NEXT: frame-setup SD killed $x24, $x2, 24 :: (store (s64) into %stack.8)
    ; RV64I-FP-NEXT: frame-setup SD killed $x25, $x2, 16 :: (store (s64) into %stack.9)
    ; RV64I-FP-NEXT: frame-setup SD killed $x26, $x2, 8 :: (store (s64) into %stack.10)
    ; RV64I-FP-NEXT: frame-setup SD killed $x27, $x2, 0 :: (store (s64) into %stack.11)
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -24
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -32
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x20, -40
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x21, -48
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x22, -56
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x23, -64
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x24, -72
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x25, -80
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -88
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x27, -96
    ; RV64I-FP-NEXT: $x8 = frame-setup ADDI $x2, 96
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-FP-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: $x19 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: $x20 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: $x21 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: $x22 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: $x23 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: $x24 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: $x25 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: $x26 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: $x27 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 96
    ; RV64I-FP-NEXT: $x1 = frame-destroy LD $x2, 88 :: (load (s64) from %stack.0)
    ; RV64I-FP-NEXT: $x8 = frame-destroy LD $x2, 80 :: (load (s64) from %stack.1)
    ; RV64I-FP-NEXT: $x18 = frame-destroy LD $x2, 72 :: (load (s64) from %stack.2)
    ; RV64I-FP-NEXT: $x19 = frame-destroy LD $x2, 64 :: (load (s64) from %stack.3)
    ; RV64I-FP-NEXT: $x20 = frame-destroy LD $x2, 56 :: (load (s64) from %stack.4)
    ; RV64I-FP-NEXT: $x21 = frame-destroy LD $x2, 48 :: (load (s64) from %stack.5)
    ; RV64I-FP-NEXT: $x22 = frame-destroy LD $x2, 40 :: (load (s64) from %stack.6)
    ; RV64I-FP-NEXT: $x23 = frame-destroy LD $x2, 32 :: (load (s64) from %stack.7)
    ; RV64I-FP-NEXT: $x24 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.8)
    ; RV64I-FP-NEXT: $x25 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.9)
    ; RV64I-FP-NEXT: $x26 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.10)
    ; RV64I-FP-NEXT: $x27 = frame-destroy LD $x2, 0 :: (load (s64) from %stack.11)
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x19
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x20
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x21
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x22
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x23
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x24
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x25
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x26
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x27
    ; RV64I-FP-NEXT: $x2 = frame-destroy ADDI $x2, 96
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-FP-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-FP-LABEL: name: save_restore_libcall
    ; RV64I-ZCMP-FP: liveins: $x1, $x18, $x19, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x27
    ; RV64I-ZCMP-FP-NEXT: {{  $}}
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-setup ADDI $x2, -96
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 96
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x1, $x2, 88 :: (store (s64) into %stack.0)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x8, $x2, 80 :: (store (s64) into %stack.1)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x18, $x2, 72 :: (store (s64) into %stack.2)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x19, $x2, 64 :: (store (s64) into %stack.3)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x20, $x2, 56 :: (store (s64) into %stack.4)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x21, $x2, 48 :: (store (s64) into %stack.5)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x22, $x2, 40 :: (store (s64) into %stack.6)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x23, $x2, 32 :: (store (s64) into %stack.7)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x24, $x2, 24 :: (store (s64) into %stack.8)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x25, $x2, 16 :: (store (s64) into %stack.9)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x26, $x2, 8 :: (store (s64) into %stack.10)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x27, $x2, 0 :: (store (s64) into %stack.11)
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -24
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -32
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x20, -40
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x21, -48
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x22, -56
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x23, -64
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x24, -72
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x25, -80
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -88
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x27, -96
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-setup ADDI $x2, 96
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-ZCMP-FP-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: $x19 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: $x20 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: $x21 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: $x22 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: $x23 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: $x24 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: $x25 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: $x26 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: $x27 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 96
    ; RV64I-ZCMP-FP-NEXT: $x1 = frame-destroy LD $x2, 88 :: (load (s64) from %stack.0)
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-destroy LD $x2, 80 :: (load (s64) from %stack.1)
    ; RV64I-ZCMP-FP-NEXT: $x18 = frame-destroy LD $x2, 72 :: (load (s64) from %stack.2)
    ; RV64I-ZCMP-FP-NEXT: $x19 = frame-destroy LD $x2, 64 :: (load (s64) from %stack.3)
    ; RV64I-ZCMP-FP-NEXT: $x20 = frame-destroy LD $x2, 56 :: (load (s64) from %stack.4)
    ; RV64I-ZCMP-FP-NEXT: $x21 = frame-destroy LD $x2, 48 :: (load (s64) from %stack.5)
    ; RV64I-ZCMP-FP-NEXT: $x22 = frame-destroy LD $x2, 40 :: (load (s64) from %stack.6)
    ; RV64I-ZCMP-FP-NEXT: $x23 = frame-destroy LD $x2, 32 :: (load (s64) from %stack.7)
    ; RV64I-ZCMP-FP-NEXT: $x24 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.8)
    ; RV64I-ZCMP-FP-NEXT: $x25 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.9)
    ; RV64I-ZCMP-FP-NEXT: $x26 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.10)
    ; RV64I-ZCMP-FP-NEXT: $x27 = frame-destroy LD $x2, 0 :: (load (s64) from %stack.11)
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x19
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x20
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x21
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x22
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x23
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x24
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x25
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x26
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x27
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-destroy ADDI $x2, 96
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-ZCMP-FP-NEXT: PseudoRET
    ;
    ; RV64I-SR-LABEL: name: save_restore_libcall
    ; RV64I-SR: liveins: $x18, $x19, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x27
    ; RV64I-SR-NEXT: {{  $}}
    ; RV64I-SR-NEXT: $x5 = frame-setup PseudoCALLReg target-flags(riscv-call) &__riscv_save_12, implicit $x2, implicit-def $x2, implicit $x18, implicit $x19, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24, implicit $x25, implicit $x26, implicit $x27
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 112
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -32
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -40
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x20, -48
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x21, -56
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x22, -64
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x23, -72
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x24, -80
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x25, -88
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -96
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x27, -104
    ; RV64I-SR-NEXT: $x18 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: $x19 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: $x20 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: $x21 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: $x22 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: $x23 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: $x24 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: $x25 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: $x26 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: $x27 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: frame-destroy PseudoTAIL target-flags(riscv-call) &__riscv_restore_12, implicit $x2, implicit-def $x2, implicit-def $x18, implicit-def $x19, implicit-def $x20, implicit-def $x21, implicit-def $x22, implicit-def $x23, implicit-def $x24, implicit-def $x25, implicit-def $x26, implicit-def $x27
    $x18 = IMPLICIT_DEF
    $x19 = IMPLICIT_DEF
    $x20 = IMPLICIT_DEF
    $x21 = IMPLICIT_DEF
    $x22 = IMPLICIT_DEF
    $x23 = IMPLICIT_DEF
    $x24 = IMPLICIT_DEF
    $x25 = IMPLICIT_DEF
    $x26 = IMPLICIT_DEF
    $x27 = IMPLICIT_DEF
    PseudoRET
...

---
name:            interrupt_saves_caller_saved
tracksRegLiveness: true
frameInfo:
  maxCallFrameSize: 0
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body: |
  bb.0:
    ; RV64I-LABEL: name: interrupt_saves_caller_saved
    ; RV64I: liveins: $x10
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 16
    ; RV64I-NEXT: frame-setup SD killed $x10, $x2, 8 :: (store (s64) into %stack.0)
    ; RV64I-NEXT: frame-setup CFI_INSTRUCTION offset $x10, -8
    ; RV64I-NEXT: $x10 = IMPLICIT_DEF
    ; RV64I-NEXT: $x10 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.0)
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION restore $x10
    ; RV64I-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; RV64I-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-LABEL: name: interrupt_saves_caller_saved
    ; RV64I-ZCMP: liveins: $x10
    ; RV64I-ZCMP-NEXT: {{  $}}
    ; RV64I-ZCMP-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 16
    ; RV64I-ZCMP-NEXT: frame-setup SD killed $x10, $x2, 8 :: (store (s64) into %stack.0)
    ; RV64I-ZCMP-NEXT: frame-setup CFI_INSTRUCTION offset $x10, -8
    ; RV64I-ZCMP-NEXT: $x10 = IMPLICIT_DEF
    ; RV64I-ZCMP-NEXT: $x10 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.0)
    ; RV64I-ZCMP-NEXT: frame-destroy CFI_INSTRUCTION restore $x10
    ; RV64I-ZCMP-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; RV64I-ZCMP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-ZCMP-NEXT: PseudoRET
    ;
    ; RV64I-FP-LABEL: name: interrupt_saves_caller_saved
    ; RV64I-FP: liveins: $x1, $x10
    ; RV64I-FP-NEXT: {{  $}}
    ; RV64I-FP-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; RV64I-FP-NEXT: frame-setup SD killed $x1, $x2, 24 :: (store (s64) into %stack.0)
    ; RV64I-FP-NEXT: frame-setup SD killed $x8, $x2, 16 :: (store (s64) into %stack.1)
    ; RV64I-FP-NEXT: frame-setup SD killed $x10, $x2, 8 :: (store (s64) into %stack.2)
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x10, -24
    ; RV64I-FP-NEXT: $x8 = frame-setup ADDI $x2, 32
    ; RV64I-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-FP-NEXT: $x10 = IMPLICIT_DEF
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 32
    ; RV64I-FP-NEXT: $x1 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.0)
    ; RV64I-FP-NEXT: $x8 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.1)
    ; RV64I-FP-NEXT: $x10 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.2)
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x10
    ; RV64I-FP-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; RV64I-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-FP-NEXT: PseudoRET
    ;
    ; RV64I-ZCMP-FP-LABEL: name: interrupt_saves_caller_saved
    ; RV64I-ZCMP-FP: liveins: $x1, $x10
    ; RV64I-ZCMP-FP-NEXT: {{  $}}
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x1, $x2, 24 :: (store (s64) into %stack.0)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x8, $x2, 16 :: (store (s64) into %stack.1)
    ; RV64I-ZCMP-FP-NEXT: frame-setup SD killed $x10, $x2, 8 :: (store (s64) into %stack.2)
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION offset $x10, -24
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-setup ADDI $x2, 32
    ; RV64I-ZCMP-FP-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; RV64I-ZCMP-FP-NEXT: $x10 = IMPLICIT_DEF
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 32
    ; RV64I-ZCMP-FP-NEXT: $x1 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.0)
    ; RV64I-ZCMP-FP-NEXT: $x8 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.1)
    ; RV64I-ZCMP-FP-NEXT: $x10 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.2)
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION restore $x10
    ; RV64I-ZCMP-FP-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; RV64I-ZCMP-FP-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-ZCMP-FP-NEXT: PseudoRET
    ;
    ; RV64I-SR-LABEL: name: interrupt_saves_caller_saved
    ; RV64I-SR: liveins: $x10
    ; RV64I-SR-NEXT: {{  $}}
    ; RV64I-SR-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 16
    ; RV64I-SR-NEXT: frame-setup SD killed $x10, $x2, 8 :: (store (s64) into %stack.0)
    ; RV64I-SR-NEXT: frame-setup CFI_INSTRUCTION offset $x10, -8
    ; RV64I-SR-NEXT: $x10 = IMPLICIT_DEF
    ; RV64I-SR-NEXT: $x10 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.0)
    ; RV64I-SR-NEXT: frame-destroy CFI_INSTRUCTION restore $x10
    ; RV64I-SR-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; RV64I-SR-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; RV64I-SR-NEXT: PseudoRET
    $x10 = IMPLICIT_DEF
    PseudoRET
...
