# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6

# RUN: llc %s -mtriple=riscv64 -run-pass=prologepilog \
# RUN: --riscv-save-csrs-early=false \
# RUN: -o - | FileCheck %s  -check-prefixes=NOEARLYCSR

# RUN: llc %s -mtriple=riscv64 -run-pass=prologepilog \
# RUN: --riscv-save-csrs-early=true \
# RUN: -o - | FileCheck %s -check-prefixes=EARLYCSR

--- |
  define void @use_callee_saved_no_nounwind() {
  entry:
    ret void
  }

  define void @use_callee_saved() nounwind {
  entry:
    ret void
  }

  define void @make_a_call() nounwind {
  entry:
    tail call void @bar()
    ret void
  }

  define void @make_a_call_and_use_callee_saved() nounwind {
  entry:
    tail call void @bar()
    ret void
  }

  define void @use_frame_pointer() nounwind {
  entry:
    ret void
  }

  declare void @bar(...) nounwind
...
---
name: use_callee_saved_no_nounwind
tracksRegLiveness: true
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 8, alignment: 8,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.0.entry:
    liveins: $x10
    ; NOEARLYCSR-LABEL: name: use_callee_saved_no_nounwind
    ; NOEARLYCSR: liveins: $x10, $x18
    ; NOEARLYCSR-NEXT: {{  $}}
    ; NOEARLYCSR-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; NOEARLYCSR-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 16
    ; NOEARLYCSR-NEXT: frame-setup SD killed $x18, $x2, 8 :: (store (s64) into %stack.1)
    ; NOEARLYCSR-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -8
    ; NOEARLYCSR-NEXT: $x18 = LD $x2, 0 :: (load (s64))
    ; NOEARLYCSR-NEXT: $x18 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.1)
    ; NOEARLYCSR-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; NOEARLYCSR-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; NOEARLYCSR-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; NOEARLYCSR-NEXT: PseudoRET
    ;
    ; EARLYCSR-LABEL: name: use_callee_saved_no_nounwind
    ; EARLYCSR: liveins: $x10, $x18
    ; EARLYCSR-NEXT: {{  $}}
    ; EARLYCSR-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; EARLYCSR-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 16
    ; EARLYCSR-NEXT: frame-setup SD killed $x18, $x2, 8 :: (store (s64) into %stack.1)
    ; EARLYCSR-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -8
    ; EARLYCSR-NEXT: $x18 = LD $x2, 0 :: (load (s64))
    ; EARLYCSR-NEXT: $x18 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.1)
    ; EARLYCSR-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; EARLYCSR-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; EARLYCSR-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; EARLYCSR-NEXT: PseudoRET
    $x18 = LD %stack.0, 0 :: (load (s64))
    PseudoRET

...
---
name: use_callee_saved
tracksRegLiveness: true
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 8, alignment: 8,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.0.entry:
    liveins: $x10
    ; NOEARLYCSR-LABEL: name: use_callee_saved
    ; NOEARLYCSR: liveins: $x10, $x18
    ; NOEARLYCSR-NEXT: {{  $}}
    ; NOEARLYCSR-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; NOEARLYCSR-NEXT: frame-setup SD killed $x18, $x2, 8 :: (store (s64) into %stack.1)
    ; NOEARLYCSR-NEXT: $x18 = LD $x2, 0 :: (load (s64))
    ; NOEARLYCSR-NEXT: $x18 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.1)
    ; NOEARLYCSR-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; NOEARLYCSR-NEXT: PseudoRET
    ;
    ; EARLYCSR-LABEL: name: use_callee_saved
    ; EARLYCSR: liveins: $x10
    ; EARLYCSR-NEXT: {{  $}}
    ; EARLYCSR-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; EARLYCSR-NEXT: $x18 = LD $x2, 8 :: (load (s64))
    ; EARLYCSR-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; EARLYCSR-NEXT: PseudoRET
    $x18 = LD %stack.0, 0 :: (load (s64))
    PseudoRET

...
---
name: make_a_call
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; NOEARLYCSR-LABEL: name: make_a_call
    ; NOEARLYCSR: PseudoTAIL target-flags(riscv-call) @bar, csr_ilp32d_lp64d, implicit $x2
    ;
    ; EARLYCSR-LABEL: name: make_a_call
    ; EARLYCSR: PseudoTAIL target-flags(riscv-call) @bar, csr_ilp32d_lp64d, implicit $x2
    PseudoTAIL target-flags(riscv-call) @bar, csr_ilp32d_lp64d, implicit $x2

...
---
name: make_a_call_and_use_callee_saved
tracksRegLiveness: true
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 8, alignment: 8,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.0.entry:
    ; NOEARLYCSR-LABEL: name: make_a_call_and_use_callee_saved
    ; NOEARLYCSR: liveins: $x18
    ; NOEARLYCSR-NEXT: {{  $}}
    ; NOEARLYCSR-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; NOEARLYCSR-NEXT: frame-setup SD killed $x18, $x2, 8 :: (store (s64) into %stack.1)
    ; NOEARLYCSR-NEXT: $x18 = LD $x2, 0 :: (load (s64))
    ; NOEARLYCSR-NEXT: $x18 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.1)
    ; NOEARLYCSR-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; NOEARLYCSR-NEXT: PseudoTAIL target-flags(riscv-call) @bar, csr_ilp32d_lp64d, implicit $x2
    ;
    ; EARLYCSR-LABEL: name: make_a_call_and_use_callee_saved
    ; EARLYCSR: $x2 = frame-setup ADDI $x2, -16
    ; EARLYCSR-NEXT: $x18 = LD $x2, 8 :: (load (s64))
    ; EARLYCSR-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; EARLYCSR-NEXT: PseudoTAIL target-flags(riscv-call) @bar, csr_ilp32d_lp64d, implicit $x2
    $x18 = LD %stack.0, 0 :: (load (s64))
    PseudoTAIL target-flags(riscv-call) @bar, csr_ilp32d_lp64d, implicit $x2
...
---
name: use_frame_pointer
tracksRegLiveness: true
frameInfo:
  isFrameAddressTaken: true
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 8, alignment: 8,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.0.entry:
    liveins: $x10
    ; NOEARLYCSR-LABEL: name: use_frame_pointer
    ; NOEARLYCSR: liveins: $x10, $x1, $x18
    ; NOEARLYCSR-NEXT: {{  $}}
    ; NOEARLYCSR-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; NOEARLYCSR-NEXT: frame-setup SD killed $x1, $x2, 24 :: (store (s64) into %stack.1)
    ; NOEARLYCSR-NEXT: frame-setup SD killed $x8, $x2, 16 :: (store (s64) into %stack.2)
    ; NOEARLYCSR-NEXT: frame-setup SD killed $x18, $x2, 8 :: (store (s64) into %stack.3)
    ; NOEARLYCSR-NEXT: $x8 = frame-setup ADDI $x2, 32
    ; NOEARLYCSR-NEXT: $x18 = LD $x8, -32 :: (load (s64))
    ; NOEARLYCSR-NEXT: $x1 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.1)
    ; NOEARLYCSR-NEXT: $x8 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.2)
    ; NOEARLYCSR-NEXT: $x18 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.3)
    ; NOEARLYCSR-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; NOEARLYCSR-NEXT: PseudoRET
    ;
    ; EARLYCSR-LABEL: name: use_frame_pointer
    ; EARLYCSR: liveins: $x10, $x1
    ; EARLYCSR-NEXT: {{  $}}
    ; EARLYCSR-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; EARLYCSR-NEXT: frame-setup SD killed $x1, $x2, 24 :: (store (s64) into %stack.1)
    ; EARLYCSR-NEXT: frame-setup SD killed $x8, $x2, 16 :: (store (s64) into %stack.2)
    ; EARLYCSR-NEXT: $x8 = frame-setup ADDI $x2, 32
    ; EARLYCSR-NEXT: $x18 = LD $x8, -24 :: (load (s64))
    ; EARLYCSR-NEXT: $x1 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.1)
    ; EARLYCSR-NEXT: $x8 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.2)
    ; EARLYCSR-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; EARLYCSR-NEXT: PseudoRET
    $x18 = LD %stack.0, 0 :: (load (s64))
    PseudoRET

...
