# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6

# RUN: llc %s -mtriple=riscv64 -run-pass=prologepilog \
# RUN: --riscv-save-csrs-early=false \
# RUN: -o - | FileCheck %s  -check-prefixes=NOEARLYCSR_UNCONDX19

# RUN: llc %s -mtriple=riscv64 -run-pass=prologepilog \
# RUN: --riscv-save-csrs-early=true \
# RUN: -o - | FileCheck %s -check-prefixes=EARLYCSR_UNCONDX19

--- |
  define void @use_callee_saved_no_nounwind() #1 {
  entry:
    ret void
  }

  define void @use_callee_saved() #0 {
  entry:
    ret void
  }

  define void @make_a_call() #0 {
  entry:
    tail call void @bar()
    ret void
  }

  define void @make_a_call_and_use_callee_saved() #0 {
  entry:
    tail call void @bar()
    ret void
  }

  attributes #0 = {"riscv-user-defined-uncond-prolog-csrs"="x19" nounwind}
  attributes #1 = {"riscv-user-defined-uncond-prolog-csrs"="x19"}
  declare void @bar(...) nounwind
...
---
name: use_callee_saved_no_nounwind
tracksRegLiveness: true
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 8, alignment: 8,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.0.entry:
    liveins: $x10
    ; NOEARLYCSR_UNCONDX19-LABEL: name: use_callee_saved_no_nounwind
    ; NOEARLYCSR_UNCONDX19: liveins: $x10, $x18, $x19
    ; NOEARLYCSR_UNCONDX19-NEXT: {{  $}}
    ; NOEARLYCSR_UNCONDX19-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; NOEARLYCSR_UNCONDX19-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; NOEARLYCSR_UNCONDX19-NEXT: frame-setup SD killed $x18, $x2, 24 :: (store (s64) into %stack.1)
    ; NOEARLYCSR_UNCONDX19-NEXT: frame-setup SD killed $x19, $x2, 16 :: (store (s64) into %stack.2)
    ; NOEARLYCSR_UNCONDX19-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -8
    ; NOEARLYCSR_UNCONDX19-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -16
    ; NOEARLYCSR_UNCONDX19-NEXT: $x18 = LD $x2, 8 :: (load (s64))
    ; NOEARLYCSR_UNCONDX19-NEXT: $x18 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.1)
    ; NOEARLYCSR_UNCONDX19-NEXT: $x19 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.2)
    ; NOEARLYCSR_UNCONDX19-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; NOEARLYCSR_UNCONDX19-NEXT: frame-destroy CFI_INSTRUCTION restore $x19
    ; NOEARLYCSR_UNCONDX19-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; NOEARLYCSR_UNCONDX19-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; NOEARLYCSR_UNCONDX19-NEXT: PseudoRET
    ;
    ; EARLYCSR_UNCONDX19-LABEL: name: use_callee_saved_no_nounwind
    ; EARLYCSR_UNCONDX19: liveins: $x10, $x18, $x19
    ; EARLYCSR_UNCONDX19-NEXT: {{  $}}
    ; EARLYCSR_UNCONDX19-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; EARLYCSR_UNCONDX19-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; EARLYCSR_UNCONDX19-NEXT: frame-setup SD killed $x18, $x2, 24 :: (store (s64) into %stack.1)
    ; EARLYCSR_UNCONDX19-NEXT: frame-setup SD killed $x19, $x2, 16 :: (store (s64) into %stack.2)
    ; EARLYCSR_UNCONDX19-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -8
    ; EARLYCSR_UNCONDX19-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -16
    ; EARLYCSR_UNCONDX19-NEXT: $x18 = LD $x2, 8 :: (load (s64))
    ; EARLYCSR_UNCONDX19-NEXT: $x18 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.1)
    ; EARLYCSR_UNCONDX19-NEXT: $x19 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.2)
    ; EARLYCSR_UNCONDX19-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; EARLYCSR_UNCONDX19-NEXT: frame-destroy CFI_INSTRUCTION restore $x19
    ; EARLYCSR_UNCONDX19-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; EARLYCSR_UNCONDX19-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; EARLYCSR_UNCONDX19-NEXT: PseudoRET
    $x18 = LD %stack.0, 0 :: (load (s64))
    PseudoRET

...
---
name: use_callee_saved
tracksRegLiveness: true
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 8, alignment: 8,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.0.entry:
    liveins: $x10
    ; NOEARLYCSR_UNCONDX19-LABEL: name: use_callee_saved
    ; NOEARLYCSR_UNCONDX19: liveins: $x10, $x18, $x19
    ; NOEARLYCSR_UNCONDX19-NEXT: {{  $}}
    ; NOEARLYCSR_UNCONDX19-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; NOEARLYCSR_UNCONDX19-NEXT: frame-setup SD killed $x18, $x2, 24 :: (store (s64) into %stack.1)
    ; NOEARLYCSR_UNCONDX19-NEXT: frame-setup SD killed $x19, $x2, 16 :: (store (s64) into %stack.2)
    ; NOEARLYCSR_UNCONDX19-NEXT: $x18 = LD $x2, 8 :: (load (s64))
    ; NOEARLYCSR_UNCONDX19-NEXT: $x18 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.1)
    ; NOEARLYCSR_UNCONDX19-NEXT: $x19 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.2)
    ; NOEARLYCSR_UNCONDX19-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; NOEARLYCSR_UNCONDX19-NEXT: PseudoRET
    ;
    ; EARLYCSR_UNCONDX19-LABEL: name: use_callee_saved
    ; EARLYCSR_UNCONDX19: liveins: $x10, $x19
    ; EARLYCSR_UNCONDX19-NEXT: {{  $}}
    ; EARLYCSR_UNCONDX19-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; EARLYCSR_UNCONDX19-NEXT: frame-setup SD killed $x19, $x2, 8 :: (store (s64) into %stack.1)
    ; EARLYCSR_UNCONDX19-NEXT: $x18 = LD $x2, 0 :: (load (s64))
    ; EARLYCSR_UNCONDX19-NEXT: $x19 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.1)
    ; EARLYCSR_UNCONDX19-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; EARLYCSR_UNCONDX19-NEXT: PseudoRET
    $x18 = LD %stack.0, 0 :: (load (s64))
    PseudoRET

...
---
name: make_a_call
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; NOEARLYCSR_UNCONDX19-LABEL: name: make_a_call
    ; NOEARLYCSR_UNCONDX19: liveins: $x19
    ; NOEARLYCSR_UNCONDX19-NEXT: {{  $}}
    ; NOEARLYCSR_UNCONDX19-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; NOEARLYCSR_UNCONDX19-NEXT: frame-setup SD killed $x19, $x2, 8 :: (store (s64) into %stack.0)
    ; NOEARLYCSR_UNCONDX19-NEXT: $x19 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.0)
    ; NOEARLYCSR_UNCONDX19-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; NOEARLYCSR_UNCONDX19-NEXT: PseudoTAIL target-flags(riscv-call) @bar, csr_ilp32d_lp64d, implicit $x2
    ;
    ; EARLYCSR_UNCONDX19-LABEL: name: make_a_call
    ; EARLYCSR_UNCONDX19: liveins: $x19
    ; EARLYCSR_UNCONDX19-NEXT: {{  $}}
    ; EARLYCSR_UNCONDX19-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; EARLYCSR_UNCONDX19-NEXT: frame-setup SD killed $x19, $x2, 8 :: (store (s64) into %stack.0)
    ; EARLYCSR_UNCONDX19-NEXT: $x19 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.0)
    ; EARLYCSR_UNCONDX19-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; EARLYCSR_UNCONDX19-NEXT: PseudoTAIL target-flags(riscv-call) @bar, csr_ilp32d_lp64d, implicit $x2
    PseudoTAIL target-flags(riscv-call) @bar, csr_ilp32d_lp64d, implicit $x2

...
---
name: make_a_call_and_use_callee_saved
tracksRegLiveness: true
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 8, alignment: 8,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.0.entry:
    ; NOEARLYCSR_UNCONDX19-LABEL: name: make_a_call_and_use_callee_saved
    ; NOEARLYCSR_UNCONDX19: liveins: $x18, $x19
    ; NOEARLYCSR_UNCONDX19-NEXT: {{  $}}
    ; NOEARLYCSR_UNCONDX19-NEXT: $x2 = frame-setup ADDI $x2, -32
    ; NOEARLYCSR_UNCONDX19-NEXT: frame-setup SD killed $x18, $x2, 24 :: (store (s64) into %stack.1)
    ; NOEARLYCSR_UNCONDX19-NEXT: frame-setup SD killed $x19, $x2, 16 :: (store (s64) into %stack.2)
    ; NOEARLYCSR_UNCONDX19-NEXT: $x18 = LD $x2, 8 :: (load (s64))
    ; NOEARLYCSR_UNCONDX19-NEXT: $x18 = frame-destroy LD $x2, 24 :: (load (s64) from %stack.1)
    ; NOEARLYCSR_UNCONDX19-NEXT: $x19 = frame-destroy LD $x2, 16 :: (load (s64) from %stack.2)
    ; NOEARLYCSR_UNCONDX19-NEXT: $x2 = frame-destroy ADDI $x2, 32
    ; NOEARLYCSR_UNCONDX19-NEXT: PseudoTAIL target-flags(riscv-call) @bar, csr_ilp32d_lp64d, implicit $x2
    ;
    ; EARLYCSR_UNCONDX19-LABEL: name: make_a_call_and_use_callee_saved
    ; EARLYCSR_UNCONDX19: liveins: $x19
    ; EARLYCSR_UNCONDX19-NEXT: {{  $}}
    ; EARLYCSR_UNCONDX19-NEXT: $x2 = frame-setup ADDI $x2, -16
    ; EARLYCSR_UNCONDX19-NEXT: frame-setup SD killed $x19, $x2, 8 :: (store (s64) into %stack.1)
    ; EARLYCSR_UNCONDX19-NEXT: $x18 = LD $x2, 0 :: (load (s64))
    ; EARLYCSR_UNCONDX19-NEXT: $x19 = frame-destroy LD $x2, 8 :: (load (s64) from %stack.1)
    ; EARLYCSR_UNCONDX19-NEXT: $x2 = frame-destroy ADDI $x2, 16
    ; EARLYCSR_UNCONDX19-NEXT: PseudoTAIL target-flags(riscv-call) @bar, csr_ilp32d_lp64d, implicit $x2
    $x18 = LD %stack.0, 0 :: (load (s64))
    PseudoTAIL target-flags(riscv-call) @bar, csr_ilp32d_lp64d, implicit $x2
...
