; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+d -verify-machineinstrs < %s \
; RUN:   -target-abi=ilp32d | FileCheck -check-prefix=RV32IFD %s
; RUN: llc -mtriple=riscv64 -mattr=+d -verify-machineinstrs < %s \
; RUN:   -target-abi=lp64d | FileCheck -check-prefix=RV64IFD %s

define double @double_imm() nounwind {
; RV32IFD-LABEL: double_imm:
; RV32IFD:       # %bb.0:
; RV32IFD-NEXT:    lui a0, %hi(.LCPI0_0)
; RV32IFD-NEXT:    fld fa0, %lo(.LCPI0_0)(a0)
; RV32IFD-NEXT:    ret
;
; RV64IFD-LABEL: double_imm:
; RV64IFD:       # %bb.0:
; RV64IFD-NEXT:    lui a0, %hi(.LCPI0_0)
; RV64IFD-NEXT:    fld fa0, %lo(.LCPI0_0)(a0)
; RV64IFD-NEXT:    ret
  ret double 3.1415926535897931159979634685441851615905761718750
}

define double @double_imm_op(double %a) nounwind {
; RV32IFD-LABEL: double_imm_op:
; RV32IFD:       # %bb.0:
; RV32IFD-NEXT:    lui a0, %hi(.LCPI1_0)
; RV32IFD-NEXT:    fld ft0, %lo(.LCPI1_0)(a0)
; RV32IFD-NEXT:    fadd.d fa0, fa0, ft0
; RV32IFD-NEXT:    ret
;
; RV64IFD-LABEL: double_imm_op:
; RV64IFD:       # %bb.0:
; RV64IFD-NEXT:    lui a0, %hi(.LCPI1_0)
; RV64IFD-NEXT:    fld ft0, %lo(.LCPI1_0)(a0)
; RV64IFD-NEXT:    fadd.d fa0, fa0, ft0
; RV64IFD-NEXT:    ret
  %1 = fadd double %a, 1.0
  ret double %1
}
