# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=riscv32 -mcp-use-is-copy-instr -run-pass=machine-cp -o - %s | FileCheck %s
# RUN: llc -mtriple=riscv64 -mcp-use-is-copy-instr -run-pass=machine-cp -o - %s | FileCheck %s

---
name:            gpr_self_copy_copy
alignment:       4
noPhis:          true
isSSA:           false
liveins:
  - { reg: '$x10' }
frameInfo:
  maxAlignment:    1
  maxCallFrameSize: 0
  isCalleeSavedInfoValid: true
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body:             |
  bb.0:
    liveins: $x10
    ; CHECK-LABEL: name: gpr_self_copy_copy
    ; CHECK: liveins: $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: PseudoRET implicit $x10
    $x10 = COPY $x10
    PseudoRET implicit $x10
...
---
name:            gpr_self_copy_addi
alignment:       4
noPhis:          true
isSSA:           false
liveins:
  - { reg: '$x10' }
frameInfo:
  maxAlignment:    1
  maxCallFrameSize: 0
  isCalleeSavedInfoValid: true
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body:             |
  bb.0:
    liveins: $x10
    ; CHECK-LABEL: name: gpr_self_copy_addi
    ; CHECK: liveins: $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: PseudoRET implicit $x10
    $x10 = ADDI $x10, 0
    PseudoRET implicit $x10
...
---
name:            gpr_self_copy_xor
alignment:       4
noPhis:          true
isSSA:           false
liveins:
  - { reg: '$x10' }
frameInfo:
  maxAlignment:    1
  maxCallFrameSize: 0
  isCalleeSavedInfoValid: true
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body:             |
  bb.0:
    liveins: $x10
    ; CHECK-LABEL: name: gpr_self_copy_xor
    ; CHECK: liveins: $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: PseudoRET implicit $x10
    $x10 = XOR $x10, $x0
    PseudoRET implicit $x10
...
