; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc %s -mtriple=riscv64 -mattr=+reserve-x24 | FileCheck %s

define i32 @main() {
; CHECK-LABEL: main:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd s8, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset s8, -8
; CHECK-NEXT:    li s8, 123
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ld s8, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore s8
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.write_register.i64(metadata !0, i64 123)
  ret i32 0
}

declare void @llvm.write_register.i64(metadata, i64) #1

!llvm.named.register.x24 = !{!0}

!0 = !{!"x24"}

