; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=riscv64 --mattr=+f,+zfa < %s | FileCheck %s --check-prefix=RISCV64
; RUN: llc --mtriple=riscv64 --mattr=+f,-zfa < %s | FileCheck %s --check-prefix=RISCV64-NOZFA
; RUN: llc --mtriple=aarch64 < %s | FileCheck %s --check-prefix=AARCH64

define i1 @f_olt_or(float %a, float %b, float %c) {
; RISCV64-LABEL: f_olt_or:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmin.s fa5, fa0, fa1
; RISCV64-NEXT:    flt.s a0, fa5, fa2
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_olt_or:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmin.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    flt.s a0, fa5, fa2
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_olt_or:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w8, mi
; AARCH64-NEXT:    fcmp s1, s2
; AARCH64-NEXT:    csinc w0, w8, wzr, pl
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp olt float %a, %c
  %cmp1 = fcmp olt float %b, %c
  %0 = or i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_olt_or_nan(float nofpclass(nan) %a, float nofpclass(nan) %b, float nofpclass(nan) %c) {
; RISCV64-LABEL: f_olt_or_nan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmin.s fa5, fa0, fa1
; RISCV64-NEXT:    flt.s a0, fa5, fa2
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_olt_or_nan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmin.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    flt.s a0, fa5, fa2
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_olt_or_nan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fminnm s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, mi
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp olt float %a, %c
  %cmp1 = fcmp olt float %b, %c
  %0 = or i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_olt_or_snan(float nofpclass(snan) %a, float nofpclass(snan) %b, float nofpclass(snan) %c) {
; RISCV64-LABEL: f_olt_or_snan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmin.s fa5, fa0, fa1
; RISCV64-NEXT:    flt.s a0, fa5, fa2
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_olt_or_snan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmin.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    flt.s a0, fa5, fa2
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_olt_or_snan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fminnm s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, mi
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp olt float %a, %c
  %cmp1 = fcmp olt float %b, %c
  %0 = or i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ugt_and(float %a, float %b, float %c) {
; RISCV64-LABEL: f_ugt_and:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmin.s fa5, fa0, fa1
; RISCV64-NEXT:    fle.s a0, fa5, fa2
; RISCV64-NEXT:    xori a0, a0, 1
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ugt_and:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmin.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    fle.s a0, fa5, fa2
; RISCV64-NOZFA-NEXT:    xori a0, a0, 1
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ugt_and:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fcmp s1, s2
; AARCH64-NEXT:    fccmp s0, s2, #0, hi
; AARCH64-NEXT:    cset w0, hi
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ugt float %a, %c
  %cmp1 = fcmp ugt float %b, %c
  %0 = and i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ugt_and_nan(float nofpclass(nan) %a, float nofpclass(nan) %b, float nofpclass(nan) %c) {
; RISCV64-LABEL: f_ugt_and_nan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmin.s fa5, fa0, fa1
; RISCV64-NEXT:    fle.s a0, fa5, fa2
; RISCV64-NEXT:    xori a0, a0, 1
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ugt_and_nan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmin.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    fle.s a0, fa5, fa2
; RISCV64-NOZFA-NEXT:    xori a0, a0, 1
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ugt_and_nan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fminnm s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, hi
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ugt float %a, %c
  %cmp1 = fcmp ugt float %b, %c
  %0 = and i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ugt_and_snan(float nofpclass(snan) %a, float nofpclass(snan) %b, float nofpclass(snan) %c) {
; RISCV64-LABEL: f_ugt_and_snan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmin.s fa5, fa0, fa1
; RISCV64-NEXT:    fle.s a0, fa5, fa2
; RISCV64-NEXT:    xori a0, a0, 1
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ugt_and_snan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmin.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    fle.s a0, fa5, fa2
; RISCV64-NOZFA-NEXT:    xori a0, a0, 1
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ugt_and_snan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fminnm s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, hi
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ugt float %a, %c
  %cmp1 = fcmp ugt float %b, %c
  %0 = and i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_olt_and(float %a, float %b, float %c) {
; RISCV64-LABEL: f_olt_and:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmaxm.s fa5, fa0, fa1
; RISCV64-NEXT:    flt.s a0, fa5, fa2
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_olt_and:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa0, fa0
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB6_2
; RISCV64-NOZFA-NEXT:  # %bb.1: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa0
; RISCV64-NOZFA-NEXT:  .LBB6_2: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa1, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB6_4
; RISCV64-NOZFA-NEXT:  # %bb.3: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa0, fa1
; RISCV64-NOZFA-NEXT:  .LBB6_4: # %entry
; RISCV64-NOZFA-NEXT:    fmax.s fa5, fa0, fa5
; RISCV64-NOZFA-NEXT:    flt.s a0, fa5, fa2
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_olt_and:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmax s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, mi
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp olt float %a, %c
  %cmp1 = fcmp olt float %b, %c
  %0 = and i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_olt_and_nan(float nofpclass(nan) %a, float nofpclass(nan) %b, float nofpclass(nan) %c) {
; RISCV64-LABEL: f_olt_and_nan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmaxm.s fa5, fa0, fa1
; RISCV64-NEXT:    flt.s a0, fa5, fa2
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_olt_and_nan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmax.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    flt.s a0, fa5, fa2
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_olt_and_nan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmax s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, mi
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp olt float %a, %c
  %cmp1 = fcmp olt float %b, %c
  %0 = and i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_olt_and_snan(float nofpclass(snan) %a, float nofpclass(snan) %b, float nofpclass(snan) %c) {
; RISCV64-LABEL: f_olt_and_snan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmaxm.s fa5, fa0, fa1
; RISCV64-NEXT:    flt.s a0, fa5, fa2
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_olt_and_snan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa0, fa0
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB8_2
; RISCV64-NOZFA-NEXT:  # %bb.1: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa0
; RISCV64-NOZFA-NEXT:  .LBB8_2: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa1, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB8_4
; RISCV64-NOZFA-NEXT:  # %bb.3: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa0, fa1
; RISCV64-NOZFA-NEXT:  .LBB8_4: # %entry
; RISCV64-NOZFA-NEXT:    fmax.s fa5, fa0, fa5
; RISCV64-NOZFA-NEXT:    flt.s a0, fa5, fa2
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_olt_and_snan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmax s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, mi
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp olt float %a, %c
  %cmp1 = fcmp olt float %b, %c
  %0 = and i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ugt_or(float %a, float %b, float %c) {
; RISCV64-LABEL: f_ugt_or:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmaxm.s fa5, fa0, fa1
; RISCV64-NEXT:    fle.s a0, fa5, fa2
; RISCV64-NEXT:    xori a0, a0, 1
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ugt_or:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa0, fa0
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB9_2
; RISCV64-NOZFA-NEXT:  # %bb.1: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa0
; RISCV64-NOZFA-NEXT:  .LBB9_2: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa1, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB9_4
; RISCV64-NOZFA-NEXT:  # %bb.3: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa0, fa1
; RISCV64-NOZFA-NEXT:  .LBB9_4: # %entry
; RISCV64-NOZFA-NEXT:    fmax.s fa5, fa0, fa5
; RISCV64-NOZFA-NEXT:    fle.s a0, fa5, fa2
; RISCV64-NOZFA-NEXT:    xori a0, a0, 1
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ugt_or:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmax s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, hi
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ugt float %a, %c
  %cmp1 = fcmp ugt float %b, %c
  %0 = or i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ugt_or_nan(float nofpclass(nan) %a, float nofpclass(nan) %b, float nofpclass(nan) %c) {
; RISCV64-LABEL: f_ugt_or_nan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmaxm.s fa5, fa0, fa1
; RISCV64-NEXT:    fle.s a0, fa5, fa2
; RISCV64-NEXT:    xori a0, a0, 1
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ugt_or_nan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmax.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    fle.s a0, fa5, fa2
; RISCV64-NOZFA-NEXT:    xori a0, a0, 1
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ugt_or_nan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmax s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, hi
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ugt float %a, %c
  %cmp1 = fcmp ugt float %b, %c
  %0 = or i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ugt_or_snan(float nofpclass(snan) %a, float nofpclass(snan) %b, float nofpclass(snan) %c) {
; RISCV64-LABEL: f_ugt_or_snan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmaxm.s fa5, fa0, fa1
; RISCV64-NEXT:    fle.s a0, fa5, fa2
; RISCV64-NEXT:    xori a0, a0, 1
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ugt_or_snan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa0, fa0
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB11_2
; RISCV64-NOZFA-NEXT:  # %bb.1: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa0
; RISCV64-NOZFA-NEXT:  .LBB11_2: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa1, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB11_4
; RISCV64-NOZFA-NEXT:  # %bb.3: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa0, fa1
; RISCV64-NOZFA-NEXT:  .LBB11_4: # %entry
; RISCV64-NOZFA-NEXT:    fmax.s fa5, fa0, fa5
; RISCV64-NOZFA-NEXT:    fle.s a0, fa5, fa2
; RISCV64-NOZFA-NEXT:    xori a0, a0, 1
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ugt_or_snan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmax s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, hi
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ugt float %a, %c
  %cmp1 = fcmp ugt float %b, %c
  %0 = or i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ogt_or(float %a, float %b, float %c) {
; RISCV64-LABEL: f_ogt_or:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmax.s fa5, fa0, fa1
; RISCV64-NEXT:    flt.s a0, fa2, fa5
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ogt_or:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmax.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    flt.s a0, fa2, fa5
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ogt_or:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w8, gt
; AARCH64-NEXT:    fcmp s1, s2
; AARCH64-NEXT:    csinc w0, w8, wzr, le
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ogt float %a, %c
  %cmp1 = fcmp ogt float %b, %c
  %0 = or i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ogt_or_nan(float nofpclass(nan) %a, float nofpclass(nan) %b, float nofpclass(nan) %c) {
; RISCV64-LABEL: f_ogt_or_nan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmax.s fa5, fa0, fa1
; RISCV64-NEXT:    flt.s a0, fa2, fa5
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ogt_or_nan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmax.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    flt.s a0, fa2, fa5
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ogt_or_nan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmaxnm s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, gt
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ogt float %a, %c
  %cmp1 = fcmp ogt float %b, %c
  %0 = or i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ogt_or_snan(float nofpclass(snan) %a, float nofpclass(snan) %b, float nofpclass(snan) %c) {
; RISCV64-LABEL: f_ogt_or_snan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmax.s fa5, fa0, fa1
; RISCV64-NEXT:    flt.s a0, fa2, fa5
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ogt_or_snan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmax.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    flt.s a0, fa2, fa5
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ogt_or_snan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmaxnm s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, gt
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ogt float %a, %c
  %cmp1 = fcmp ogt float %b, %c
  %0 = or i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ult_and(float %a, float %b, float %c) {
; RISCV64-LABEL: f_ult_and:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmax.s fa5, fa0, fa1
; RISCV64-NEXT:    fle.s a0, fa2, fa5
; RISCV64-NEXT:    xori a0, a0, 1
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ult_and:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmax.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    fle.s a0, fa2, fa5
; RISCV64-NOZFA-NEXT:    xori a0, a0, 1
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ult_and:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fcmp s1, s2
; AARCH64-NEXT:    fccmp s0, s2, #0, lt
; AARCH64-NEXT:    cset w0, lt
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ult float %a, %c
  %cmp1 = fcmp ult float %b, %c
  %0 = and i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ult_and_nan(float nofpclass(nan) %a, float nofpclass(nan) %b, float nofpclass(nan) %c) {
; RISCV64-LABEL: f_ult_and_nan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmax.s fa5, fa0, fa1
; RISCV64-NEXT:    fle.s a0, fa2, fa5
; RISCV64-NEXT:    xori a0, a0, 1
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ult_and_nan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmax.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    fle.s a0, fa2, fa5
; RISCV64-NOZFA-NEXT:    xori a0, a0, 1
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ult_and_nan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmaxnm s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, lt
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ult float %a, %c
  %cmp1 = fcmp ult float %b, %c
  %0 = and i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ult_and_snan(float nofpclass(snan) %a, float nofpclass(snan) %b, float nofpclass(snan) %c) {
; RISCV64-LABEL: f_ult_and_snan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fmax.s fa5, fa0, fa1
; RISCV64-NEXT:    fle.s a0, fa2, fa5
; RISCV64-NEXT:    xori a0, a0, 1
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ult_and_snan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmax.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    fle.s a0, fa2, fa5
; RISCV64-NOZFA-NEXT:    xori a0, a0, 1
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ult_and_snan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmaxnm s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, lt
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ult float %a, %c
  %cmp1 = fcmp ult float %b, %c
  %0 = and i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ogt_and(float %a, float %b, float %c) {
; RISCV64-LABEL: f_ogt_and:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fminm.s fa5, fa0, fa1
; RISCV64-NEXT:    flt.s a0, fa2, fa5
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ogt_and:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa0, fa0
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB18_2
; RISCV64-NOZFA-NEXT:  # %bb.1: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa0
; RISCV64-NOZFA-NEXT:  .LBB18_2: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa1, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB18_4
; RISCV64-NOZFA-NEXT:  # %bb.3: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa0, fa1
; RISCV64-NOZFA-NEXT:  .LBB18_4: # %entry
; RISCV64-NOZFA-NEXT:    fmin.s fa5, fa0, fa5
; RISCV64-NOZFA-NEXT:    flt.s a0, fa2, fa5
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ogt_and:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmin s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, gt
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ogt float %a, %c
  %cmp1 = fcmp ogt float %b, %c
  %0 = and i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ogt_and_nan(float nofpclass(nan) %a, float nofpclass(nan) %b, float nofpclass(nan) %c) {
; RISCV64-LABEL: f_ogt_and_nan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fminm.s fa5, fa0, fa1
; RISCV64-NEXT:    flt.s a0, fa2, fa5
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ogt_and_nan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmin.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    flt.s a0, fa2, fa5
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ogt_and_nan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmin s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, gt
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ogt float %a, %c
  %cmp1 = fcmp ogt float %b, %c
  %0 = and i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ogt_and_snan(float nofpclass(snan) %a, float nofpclass(snan) %b, float nofpclass(snan) %c) {
; RISCV64-LABEL: f_ogt_and_snan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fminm.s fa5, fa0, fa1
; RISCV64-NEXT:    flt.s a0, fa2, fa5
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ogt_and_snan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa0, fa0
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB20_2
; RISCV64-NOZFA-NEXT:  # %bb.1: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa0
; RISCV64-NOZFA-NEXT:  .LBB20_2: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa1, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB20_4
; RISCV64-NOZFA-NEXT:  # %bb.3: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa0, fa1
; RISCV64-NOZFA-NEXT:  .LBB20_4: # %entry
; RISCV64-NOZFA-NEXT:    fmin.s fa5, fa0, fa5
; RISCV64-NOZFA-NEXT:    flt.s a0, fa2, fa5
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ogt_and_snan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmin s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, gt
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ogt float %a, %c
  %cmp1 = fcmp ogt float %b, %c
  %0 = and i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ult_or(float %a, float %b, float %c) {
; RISCV64-LABEL: f_ult_or:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fminm.s fa5, fa0, fa1
; RISCV64-NEXT:    fle.s a0, fa2, fa5
; RISCV64-NEXT:    xori a0, a0, 1
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ult_or:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa0, fa0
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB21_2
; RISCV64-NOZFA-NEXT:  # %bb.1: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa0
; RISCV64-NOZFA-NEXT:  .LBB21_2: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa1, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB21_4
; RISCV64-NOZFA-NEXT:  # %bb.3: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa0, fa1
; RISCV64-NOZFA-NEXT:  .LBB21_4: # %entry
; RISCV64-NOZFA-NEXT:    fmin.s fa5, fa0, fa5
; RISCV64-NOZFA-NEXT:    fle.s a0, fa2, fa5
; RISCV64-NOZFA-NEXT:    xori a0, a0, 1
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ult_or:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmin s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, lt
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ult float %a, %c
  %cmp1 = fcmp ult float %b, %c
  %0 = or i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ult_or_nan(float nofpclass(nan) %a, float nofpclass(nan) %b, float nofpclass(nan) %c) {
; RISCV64-LABEL: f_ult_or_nan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fminm.s fa5, fa0, fa1
; RISCV64-NEXT:    fle.s a0, fa2, fa5
; RISCV64-NEXT:    xori a0, a0, 1
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ult_or_nan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    fmin.s fa5, fa0, fa1
; RISCV64-NOZFA-NEXT:    fle.s a0, fa2, fa5
; RISCV64-NOZFA-NEXT:    xori a0, a0, 1
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ult_or_nan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmin s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, lt
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ult float %a, %c
  %cmp1 = fcmp ult float %b, %c
  %0 = or i1 %cmp, %cmp1
  ret i1 %0
}

define i1 @f_ult_or_snan(float nofpclass(snan) %a, float nofpclass(snan) %b, float nofpclass(snan) %c) {
; RISCV64-LABEL: f_ult_or_snan:
; RISCV64:       # %bb.0: # %entry
; RISCV64-NEXT:    fminm.s fa5, fa0, fa1
; RISCV64-NEXT:    fle.s a0, fa2, fa5
; RISCV64-NEXT:    xori a0, a0, 1
; RISCV64-NEXT:    ret
;
; RISCV64-NOZFA-LABEL: f_ult_or_snan:
; RISCV64-NOZFA:       # %bb.0: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa0, fa0
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB23_2
; RISCV64-NOZFA-NEXT:  # %bb.1: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa5, fa0
; RISCV64-NOZFA-NEXT:  .LBB23_2: # %entry
; RISCV64-NOZFA-NEXT:    feq.s a0, fa1, fa1
; RISCV64-NOZFA-NEXT:    bnez a0, .LBB23_4
; RISCV64-NOZFA-NEXT:  # %bb.3: # %entry
; RISCV64-NOZFA-NEXT:    fmv.s fa0, fa1
; RISCV64-NOZFA-NEXT:  .LBB23_4: # %entry
; RISCV64-NOZFA-NEXT:    fmin.s fa5, fa0, fa5
; RISCV64-NOZFA-NEXT:    fle.s a0, fa2, fa5
; RISCV64-NOZFA-NEXT:    xori a0, a0, 1
; RISCV64-NOZFA-NEXT:    ret
;
; AARCH64-LABEL: f_ult_or_snan:
; AARCH64:       // %bb.0: // %entry
; AARCH64-NEXT:    fmin s0, s0, s1
; AARCH64-NEXT:    fcmp s0, s2
; AARCH64-NEXT:    cset w0, lt
; AARCH64-NEXT:    ret
entry:
  %cmp = fcmp ult float %a, %c
  %cmp1 = fcmp ult float %b, %c
  %0 = or i1 %cmp, %cmp1
  ret i1 %0
}
