; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=riscv64 < %s  | FileCheck  %s

define i64 @select_add(i1 %c, i64 %x) {
; CHECK-LABEL: select_add:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 1
; CHECK-NEXT:    addi a1, a1, 2
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %select_ = select i1 %c, i64 -2, i64 %x
  %res = add i64 %select_, 2
  ret i64 %res
}

define i64 @select_and(i1 %c, i64 %x) {
; CHECK-LABEL: select_and:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 1
; CHECK-NEXT:    addiw a0, a0, -1
; CHECK-NEXT:    and a0, a1, a0
; CHECK-NEXT:    andi a0, a0, 64
; CHECK-NEXT:    ret
entry:
  %select_ = select i1 %c, i64 63, i64 %x
  %res = and i64 %select_, 64
  ret i64 %res
}

