; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -riscv-enable-global-merge=false -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV32I %s
; RUN: llc -mtriple=riscv32  -riscv-enable-global-merge=false -mattr=+zba -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV32ZBA %s
; RUN: llc -mtriple=riscv64 -riscv-enable-global-merge=false -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64I %s
; RUN: llc -mtriple=riscv64 -mattr=+zba -riscv-enable-global-merge=false -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64ZBA %s

@g1 = dso_local local_unnamed_addr global [100 x i8] zeroinitializer, align 1
@g2 = dso_local local_unnamed_addr global [100 x i16] zeroinitializer, align 2
@g3 = dso_local local_unnamed_addr global [100 x i32] zeroinitializer, align 4
@g4 = dso_local local_unnamed_addr global [100 x i64] zeroinitializer, align 8

define i8 @char_load(i32 %index) {
; RV32I-LABEL: char_load:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, %hi(g1)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g1)
; RV32I-NEXT:    lbu a0, %regrel_lo(g1)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: char_load:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g1)
; RV32ZBA-NEXT:    add a0, a0, a1, %regrel_add(g1)
; RV32ZBA-NEXT:    lbu a0, %regrel_lo(g1)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: char_load:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    lui a1, %hi(g1)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g1)
; RV64I-NEXT:    lbu a0, %regrel_lo(g1)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: char_load:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g1)
; RV64ZBA-NEXT:    add a0, a0, a1, %regrel_add(g1)
; RV64ZBA-NEXT:    lbu a0, %regrel_lo(g1)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = sext i32 %index to i64
  %arrayidx = getelementptr inbounds [100 x i8], ptr @g1, i64 0, i64 %idxprom
  %0 = load i8, ptr %arrayidx, align 1
  ret i8 %0
}

define i8 @char_load_offset(i32 %index) {
; RV32I-LABEL: char_load_offset:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, %hi(g1+4)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g1+4)
; RV32I-NEXT:    lbu a0, %regrel_lo(g1+4)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: char_load_offset:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g1+4)
; RV32ZBA-NEXT:    add a0, a0, a1, %regrel_add(g1+4)
; RV32ZBA-NEXT:    lbu a0, %regrel_lo(g1+4)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: char_load_offset:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    lui a1, %hi(g1+4)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g1+4)
; RV64I-NEXT:    lbu a0, %regrel_lo(g1+4)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: char_load_offset:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g1+4)
; RV64ZBA-NEXT:    add a0, a0, a1, %regrel_add(g1+4)
; RV64ZBA-NEXT:    lbu a0, %regrel_lo(g1+4)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %add = add nsw i32 %index, 4
  %idxprom = sext i32 %add to i64
  %arrayidx = getelementptr inbounds [100 x i8], ptr @g1, i64 0, i64 %idxprom
  %0 = load i8, ptr %arrayidx, align 1
  ret i8 %0
}

define i8 @char_load_uw(i32 %index) {
; RV32I-LABEL: char_load_uw:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, %hi(g1)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g1)
; RV32I-NEXT:    lbu a0, %regrel_lo(g1)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: char_load_uw:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g1)
; RV32ZBA-NEXT:    add a0, a0, a1, %regrel_add(g1)
; RV32ZBA-NEXT:    lbu a0, %regrel_lo(g1)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: char_load_uw:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 32
; RV64I-NEXT:    lui a1, %hi(g1)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g1)
; RV64I-NEXT:    lbu a0, %regrel_lo(g1)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: char_load_uw:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g1)
; RV64ZBA-NEXT:    add.uw a0, a0, a1, %regrel_add(g1)
; RV64ZBA-NEXT:    lbu a0, %regrel_lo(g1)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = zext i32 %index to i64
  %arrayidx = getelementptr inbounds nuw [100 x i8], ptr @g1, i64 0, i64 %idxprom
  %0 = load i8, ptr %arrayidx, align 1
  ret i8 %0
}

define i16 @short_load(i32 %index) {
; RV32I-LABEL: short_load:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 1
; RV32I-NEXT:    lui a1, %hi(g2)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g2)
; RV32I-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: short_load:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g2)
; RV32ZBA-NEXT:    sh1add a0, a0, a1, %regrel_shxadd(g2)
; RV32ZBA-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: short_load:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    slli a0, a0, 1
; RV64I-NEXT:    lui a1, %hi(g2)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g2)
; RV64I-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: short_load:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g2)
; RV64ZBA-NEXT:    sh1add a0, a0, a1, %regrel_shxadd(g2)
; RV64ZBA-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = sext i32 %index to i64
  %arrayidx = getelementptr inbounds [100 x i16], ptr @g2, i64 0, i64 %idxprom
  %0 = load i16, ptr %arrayidx, align 2
  ret i16 %0
}

define i16 @short_load_offset(i32 %index) {
; RV32I-LABEL: short_load_offset:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 1
; RV32I-NEXT:    lui a1, %hi(g2+8)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g2+8)
; RV32I-NEXT:    lh a0, %regrel_lo(g2+8)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: short_load_offset:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g2+8)
; RV32ZBA-NEXT:    sh1add a0, a0, a1, %regrel_shxadd(g2+8)
; RV32ZBA-NEXT:    lh a0, %regrel_lo(g2+8)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: short_load_offset:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    slli a0, a0, 1
; RV64I-NEXT:    lui a1, %hi(g2+8)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g2+8)
; RV64I-NEXT:    lh a0, %regrel_lo(g2+8)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: short_load_offset:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g2+8)
; RV64ZBA-NEXT:    sh1add a0, a0, a1, %regrel_shxadd(g2+8)
; RV64ZBA-NEXT:    lh a0, %regrel_lo(g2+8)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %add = add nsw i32 %index, 4
  %idxprom = sext i32 %add to i64
  %arrayidx = getelementptr inbounds [100 x i16], ptr @g2, i64 0, i64 %idxprom
  %0 = load i16, ptr %arrayidx, align 2
  ret i16 %0
}

define i16 @short_load_uw(i32 %index) {
; RV32I-LABEL: short_load_uw:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 1
; RV32I-NEXT:    lui a1, %hi(g2)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g2)
; RV32I-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: short_load_uw:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g2)
; RV32ZBA-NEXT:    sh1add a0, a0, a1, %regrel_shxadd(g2)
; RV32ZBA-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: short_load_uw:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 31
; RV64I-NEXT:    lui a1, %hi(g2)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g2)
; RV64I-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: short_load_uw:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g2)
; RV64ZBA-NEXT:    sh1add.uw a0, a0, a1, %regrel_shxadd(g2)
; RV64ZBA-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = zext i32 %index to i64
  %arrayidx = getelementptr inbounds nuw [100 x i16], ptr @g2, i64 0, i64 %idxprom
  %0 = load i16, ptr %arrayidx, align 2
  ret i16 %0
}

define i32 @int_load(i32 %index) {
; RV32I-LABEL: int_load:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 2
; RV32I-NEXT:    lui a1, %hi(g3)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g3)
; RV32I-NEXT:    lw a0, %regrel_lo(g3)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: int_load:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g3)
; RV32ZBA-NEXT:    sh2add a0, a0, a1, %regrel_shxadd(g3)
; RV32ZBA-NEXT:    lw a0, %regrel_lo(g3)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: int_load:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    slli a0, a0, 2
; RV64I-NEXT:    lui a1, %hi(g3)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g3)
; RV64I-NEXT:    lw a0, %regrel_lo(g3)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: int_load:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g3)
; RV64ZBA-NEXT:    sh2add a0, a0, a1, %regrel_shxadd(g3)
; RV64ZBA-NEXT:    lw a0, %regrel_lo(g3)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = sext i32 %index to i64
  %arrayidx = getelementptr inbounds [100 x i32], ptr @g3, i64 0, i64 %idxprom
  %0 = load i32, ptr %arrayidx, align 4
  ret i32 %0
}

define i32 @int_load_offset(i32 %index) {
; RV32I-LABEL: int_load_offset:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 2
; RV32I-NEXT:    lui a1, %hi(g3+16)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g3+16)
; RV32I-NEXT:    lw a0, %regrel_lo(g3+16)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: int_load_offset:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g3+16)
; RV32ZBA-NEXT:    sh2add a0, a0, a1, %regrel_shxadd(g3+16)
; RV32ZBA-NEXT:    lw a0, %regrel_lo(g3+16)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: int_load_offset:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    slli a0, a0, 2
; RV64I-NEXT:    lui a1, %hi(g3+16)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g3+16)
; RV64I-NEXT:    lw a0, %regrel_lo(g3+16)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: int_load_offset:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g3+16)
; RV64ZBA-NEXT:    sh2add a0, a0, a1, %regrel_shxadd(g3+16)
; RV64ZBA-NEXT:    lw a0, %regrel_lo(g3+16)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %add = add nsw i32 %index, 4
  %idxprom = sext i32 %add to i64
  %arrayidx = getelementptr inbounds [100 x i32], ptr @g3, i64 0, i64 %idxprom
  %0 = load i32, ptr %arrayidx, align 4
  ret i32 %0
}

define i32 @int_load_uw(i32 %index) {
; RV32I-LABEL: int_load_uw:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 2
; RV32I-NEXT:    lui a1, %hi(g3)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g3)
; RV32I-NEXT:    lw a0, %regrel_lo(g3)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: int_load_uw:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g3)
; RV32ZBA-NEXT:    sh2add a0, a0, a1, %regrel_shxadd(g3)
; RV32ZBA-NEXT:    lw a0, %regrel_lo(g3)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: int_load_uw:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 30
; RV64I-NEXT:    lui a1, %hi(g3)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g3)
; RV64I-NEXT:    lw a0, %regrel_lo(g3)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: int_load_uw:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g3)
; RV64ZBA-NEXT:    sh2add.uw a0, a0, a1, %regrel_shxadd(g3)
; RV64ZBA-NEXT:    lw a0, %regrel_lo(g3)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = zext i32 %index to i64
  %arrayidx = getelementptr inbounds nuw [100 x i32], ptr @g3, i64 0, i64 %idxprom
  %0 = load i32, ptr %arrayidx, align 4
  ret i32 %0
}

define i64 @long_long_load(i32 %index) {
; RV32I-LABEL: long_long_load:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 3
; RV32I-NEXT:    lui a1, %hi(g4)
; RV32I-NEXT:    addi a1, a1, %lo(g4)
; RV32I-NEXT:    add a1, a1, a0
; RV32I-NEXT:    lw a0, 0(a1)
; RV32I-NEXT:    lw a1, 4(a1)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: long_long_load:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g4)
; RV32ZBA-NEXT:    addi a1, a1, %lo(g4)
; RV32ZBA-NEXT:    sh3add a1, a0, a1
; RV32ZBA-NEXT:    lw a0, 0(a1)
; RV32ZBA-NEXT:    lw a1, 4(a1)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: long_long_load:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    slli a0, a0, 3
; RV64I-NEXT:    lui a1, %hi(g4)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g4)
; RV64I-NEXT:    ld a0, %regrel_lo(g4)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: long_long_load:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g4)
; RV64ZBA-NEXT:    sh3add a0, a0, a1, %regrel_shxadd(g4)
; RV64ZBA-NEXT:    ld a0, %regrel_lo(g4)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = sext i32 %index to i64
  %arrayidx = getelementptr inbounds [100 x i64], ptr @g4, i64 0, i64 %idxprom
  %0 = load i64, ptr %arrayidx, align 8
  ret i64 %0
}

define i64 @long_long_load_offset(i32 %index) {
; RV32I-LABEL: long_long_load_offset:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 3
; RV32I-NEXT:    lui a1, %hi(g4)
; RV32I-NEXT:    addi a1, a1, %lo(g4)
; RV32I-NEXT:    add a1, a0, a1
; RV32I-NEXT:    lw a0, 32(a1)
; RV32I-NEXT:    lw a1, 36(a1)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: long_long_load_offset:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g4)
; RV32ZBA-NEXT:    addi a1, a1, %lo(g4)
; RV32ZBA-NEXT:    sh3add a1, a0, a1
; RV32ZBA-NEXT:    lw a0, 32(a1)
; RV32ZBA-NEXT:    lw a1, 36(a1)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: long_long_load_offset:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    slli a0, a0, 3
; RV64I-NEXT:    lui a1, %hi(g4+32)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g4+32)
; RV64I-NEXT:    ld a0, %regrel_lo(g4+32)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: long_long_load_offset:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g4+32)
; RV64ZBA-NEXT:    sh3add a0, a0, a1, %regrel_shxadd(g4+32)
; RV64ZBA-NEXT:    ld a0, %regrel_lo(g4+32)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %add = add nsw i32 %index, 4
  %idxprom = sext i32 %add to i64
  %arrayidx = getelementptr inbounds [100 x i64], ptr @g4, i64 0, i64 %idxprom
  %0 = load i64, ptr %arrayidx, align 8
  ret i64 %0
}

define i64 @long_long_load_uw(i32 %index) {
; RV32I-LABEL: long_long_load_uw:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 3
; RV32I-NEXT:    lui a1, %hi(g4)
; RV32I-NEXT:    addi a1, a1, %lo(g4)
; RV32I-NEXT:    add a1, a1, a0
; RV32I-NEXT:    lw a0, 0(a1)
; RV32I-NEXT:    lw a1, 4(a1)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: long_long_load_uw:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g4)
; RV32ZBA-NEXT:    addi a1, a1, %lo(g4)
; RV32ZBA-NEXT:    sh3add a1, a0, a1
; RV32ZBA-NEXT:    lw a0, 0(a1)
; RV32ZBA-NEXT:    lw a1, 4(a1)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: long_long_load_uw:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 29
; RV64I-NEXT:    lui a1, %hi(g4)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g4)
; RV64I-NEXT:    ld a0, %regrel_lo(g4)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: long_long_load_uw:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g4)
; RV64ZBA-NEXT:    sh3add.uw a0, a0, a1, %regrel_shxadd(g4)
; RV64ZBA-NEXT:    ld a0, %regrel_lo(g4)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = zext i32 %index to i64
  %arrayidx = getelementptr inbounds nuw [100 x i64], ptr @g4, i64 0, i64 %idxprom
  %0 = load i64, ptr %arrayidx, align 8
  ret i64 %0
}

define i64 @add_more_oneuse_load(i32 %index) {
; RV32I-LABEL: add_more_oneuse_load:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 3
; RV32I-NEXT:    lui a1, %hi(g4)
; RV32I-NEXT:    addi a1, a1, %lo(g4)
; RV32I-NEXT:    add a0, a1, a0
; RV32I-NEXT:    lw a0, 0(a0)
; RV32I-NEXT:    slli a0, a0, 3
; RV32I-NEXT:    add a1, a1, a0
; RV32I-NEXT:    lw a0, 0(a1)
; RV32I-NEXT:    lw a1, 4(a1)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: add_more_oneuse_load:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g4)
; RV32ZBA-NEXT:    addi a1, a1, %lo(g4)
; RV32ZBA-NEXT:    sh3add a0, a0, a1
; RV32ZBA-NEXT:    lw a0, 0(a0)
; RV32ZBA-NEXT:    sh3add a1, a0, a1
; RV32ZBA-NEXT:    lw a0, 0(a1)
; RV32ZBA-NEXT:    lw a1, 4(a1)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: add_more_oneuse_load:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    slli a0, a0, 3
; RV64I-NEXT:    lui a1, %hi(g4)
; RV64I-NEXT:    addi a1, a1, %lo(g4)
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    ld a0, 0(a0)
; RV64I-NEXT:    slli a0, a0, 3
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    ld a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: add_more_oneuse_load:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    sext.w a0, a0
; RV64ZBA-NEXT:    lui a1, %hi(g4)
; RV64ZBA-NEXT:    addi a1, a1, %lo(g4)
; RV64ZBA-NEXT:    sh3add a0, a0, a1
; RV64ZBA-NEXT:    ld a0, 0(a0)
; RV64ZBA-NEXT:    sh3add a0, a0, a1
; RV64ZBA-NEXT:    ld a0, 0(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = sext i32 %index to i64
  %arrayidx = getelementptr inbounds [100 x i64], ptr @g4, i64 0, i64 %idxprom
  %0 = load i64, ptr %arrayidx, align 8
  %arrayidx1 = getelementptr inbounds [100 x i64], ptr @g4, i64 0, i64 %0
  %1 = load i64, ptr %arrayidx1, align 8
  ret i64 %1
}

define i64 @test_nesting_load(i32 %index) {
; RV32I-LABEL: test_nesting_load:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 1
; RV32I-NEXT:    lui a1, %hi(g2)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g2)
; RV32I-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV32I-NEXT:    lui a1, %hi(g4)
; RV32I-NEXT:    addi a1, a1, %lo(g4)
; RV32I-NEXT:    slli a0, a0, 3
; RV32I-NEXT:    add a1, a1, a0
; RV32I-NEXT:    lw a0, 0(a1)
; RV32I-NEXT:    lw a1, 4(a1)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: test_nesting_load:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g2)
; RV32ZBA-NEXT:    sh1add a0, a0, a1, %regrel_shxadd(g2)
; RV32ZBA-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV32ZBA-NEXT:    lui a1, %hi(g4)
; RV32ZBA-NEXT:    addi a1, a1, %lo(g4)
; RV32ZBA-NEXT:    sh3add a1, a0, a1
; RV32ZBA-NEXT:    lw a0, 0(a1)
; RV32ZBA-NEXT:    lw a1, 4(a1)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: test_nesting_load:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    lui a1, %hi(g2)
; RV64I-NEXT:    slli a0, a0, 1
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g2)
; RV64I-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV64I-NEXT:    slli a0, a0, 3
; RV64I-NEXT:    lui a1, %hi(g4)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g4)
; RV64I-NEXT:    ld a0, %regrel_lo(g4)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: test_nesting_load:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g2)
; RV64ZBA-NEXT:    sh1add a0, a0, a1, %regrel_shxadd(g2)
; RV64ZBA-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV64ZBA-NEXT:    lui a1, %hi(g4)
; RV64ZBA-NEXT:    sh3add a0, a0, a1, %regrel_shxadd(g4)
; RV64ZBA-NEXT:    ld a0, %regrel_lo(g4)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = sext i32 %index to i64
  %arrayidx = getelementptr inbounds [100 x i16], ptr @g2, i64 0, i64 %idxprom
  %0 = load i16, ptr %arrayidx, align 2
  %idxprom1 = sext i16 %0 to i64
  %arrayidx2 = getelementptr inbounds [100 x i64], ptr @g4, i64 0, i64 %idxprom1
  %1 = load i64, ptr %arrayidx2, align 8
  ret i64 %1
}

define void @char_store(i32 %index) {
; RV32I-LABEL: char_store:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, %hi(g1)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g1)
; RV32I-NEXT:    li a1, 100
; RV32I-NEXT:    sb a1, %regrel_lo(g1)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: char_store:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g1)
; RV32ZBA-NEXT:    add a0, a0, a1, %regrel_add(g1)
; RV32ZBA-NEXT:    li a1, 100
; RV32ZBA-NEXT:    sb a1, %regrel_lo(g1)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: char_store:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    lui a1, %hi(g1)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g1)
; RV64I-NEXT:    li a1, 100
; RV64I-NEXT:    sb a1, %regrel_lo(g1)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: char_store:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g1)
; RV64ZBA-NEXT:    add a0, a0, a1, %regrel_add(g1)
; RV64ZBA-NEXT:    li a1, 100
; RV64ZBA-NEXT:    sb a1, %regrel_lo(g1)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = sext i32 %index to i64
  %arrayidx = getelementptr inbounds [100 x i8], ptr @g1, i64 0, i64 %idxprom
  store i8 100, ptr %arrayidx, align 1
  ret void
}

define void @char_store_offset(i32 %index) {
; RV32I-LABEL: char_store_offset:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, %hi(g1+4)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g1+4)
; RV32I-NEXT:    li a1, 100
; RV32I-NEXT:    sb a1, %regrel_lo(g1+4)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: char_store_offset:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g1+4)
; RV32ZBA-NEXT:    add a0, a0, a1, %regrel_add(g1+4)
; RV32ZBA-NEXT:    li a1, 100
; RV32ZBA-NEXT:    sb a1, %regrel_lo(g1+4)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: char_store_offset:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    lui a1, %hi(g1+4)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g1+4)
; RV64I-NEXT:    li a1, 100
; RV64I-NEXT:    sb a1, %regrel_lo(g1+4)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: char_store_offset:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g1+4)
; RV64ZBA-NEXT:    add a0, a0, a1, %regrel_add(g1+4)
; RV64ZBA-NEXT:    li a1, 100
; RV64ZBA-NEXT:    sb a1, %regrel_lo(g1+4)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %add = add nsw i32 %index, 4
  %idxprom = sext i32 %add to i64
  %arrayidx = getelementptr inbounds [100 x i8], ptr @g1, i64 0, i64 %idxprom
  store i8 100, ptr %arrayidx, align 1
  ret void
}

define void @char_store_uw(i32 %index) {
; RV32I-LABEL: char_store_uw:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, %hi(g1)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g1)
; RV32I-NEXT:    li a1, 100
; RV32I-NEXT:    sb a1, %regrel_lo(g1)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: char_store_uw:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g1)
; RV32ZBA-NEXT:    add a0, a0, a1, %regrel_add(g1)
; RV32ZBA-NEXT:    li a1, 100
; RV32ZBA-NEXT:    sb a1, %regrel_lo(g1)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: char_store_uw:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 32
; RV64I-NEXT:    lui a1, %hi(g1)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g1)
; RV64I-NEXT:    li a1, 100
; RV64I-NEXT:    sb a1, %regrel_lo(g1)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: char_store_uw:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g1)
; RV64ZBA-NEXT:    add.uw a0, a0, a1, %regrel_add(g1)
; RV64ZBA-NEXT:    li a1, 100
; RV64ZBA-NEXT:    sb a1, %regrel_lo(g1)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = zext i32 %index to i64
  %arrayidx = getelementptr inbounds nuw [100 x i8], ptr @g1, i64 0, i64 %idxprom
  store i8 100, ptr %arrayidx, align 1
  ret void
}

define void @short_store(i32 %index) {
; RV32I-LABEL: short_store:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 1
; RV32I-NEXT:    lui a1, %hi(g2)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g2)
; RV32I-NEXT:    li a1, 100
; RV32I-NEXT:    sh a1, %regrel_lo(g2)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: short_store:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g2)
; RV32ZBA-NEXT:    sh1add a0, a0, a1, %regrel_shxadd(g2)
; RV32ZBA-NEXT:    li a1, 100
; RV32ZBA-NEXT:    sh a1, %regrel_lo(g2)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: short_store:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    slli a0, a0, 1
; RV64I-NEXT:    lui a1, %hi(g2)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g2)
; RV64I-NEXT:    li a1, 100
; RV64I-NEXT:    sh a1, %regrel_lo(g2)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: short_store:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g2)
; RV64ZBA-NEXT:    sh1add a0, a0, a1, %regrel_shxadd(g2)
; RV64ZBA-NEXT:    li a1, 100
; RV64ZBA-NEXT:    sh a1, %regrel_lo(g2)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = sext i32 %index to i64
  %arrayidx = getelementptr inbounds [100 x i16], ptr @g2, i64 0, i64 %idxprom
  store i16 100, ptr %arrayidx, align 2
  ret void
}

define void @short_store_offset(i32 %index) {
; RV32I-LABEL: short_store_offset:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 1
; RV32I-NEXT:    lui a1, %hi(g2+8)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g2+8)
; RV32I-NEXT:    li a1, 100
; RV32I-NEXT:    sh a1, %regrel_lo(g2+8)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: short_store_offset:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g2+8)
; RV32ZBA-NEXT:    sh1add a0, a0, a1, %regrel_shxadd(g2+8)
; RV32ZBA-NEXT:    li a1, 100
; RV32ZBA-NEXT:    sh a1, %regrel_lo(g2+8)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: short_store_offset:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    slli a0, a0, 1
; RV64I-NEXT:    lui a1, %hi(g2+8)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g2+8)
; RV64I-NEXT:    li a1, 100
; RV64I-NEXT:    sh a1, %regrel_lo(g2+8)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: short_store_offset:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g2+8)
; RV64ZBA-NEXT:    sh1add a0, a0, a1, %regrel_shxadd(g2+8)
; RV64ZBA-NEXT:    li a1, 100
; RV64ZBA-NEXT:    sh a1, %regrel_lo(g2+8)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %add = add nsw i32 %index, 4
  %idxprom = sext i32 %add to i64
  %arrayidx = getelementptr inbounds [100 x i16], ptr @g2, i64 0, i64 %idxprom
  store i16 100, ptr %arrayidx, align 2
  ret void
}

define void @short_store_uw(i32 %index) {
; RV32I-LABEL: short_store_uw:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 1
; RV32I-NEXT:    lui a1, %hi(g2)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g2)
; RV32I-NEXT:    li a1, 100
; RV32I-NEXT:    sh a1, %regrel_lo(g2)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: short_store_uw:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g2)
; RV32ZBA-NEXT:    sh1add a0, a0, a1, %regrel_shxadd(g2)
; RV32ZBA-NEXT:    li a1, 100
; RV32ZBA-NEXT:    sh a1, %regrel_lo(g2)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: short_store_uw:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 31
; RV64I-NEXT:    lui a1, %hi(g2)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g2)
; RV64I-NEXT:    li a1, 100
; RV64I-NEXT:    sh a1, %regrel_lo(g2)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: short_store_uw:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g2)
; RV64ZBA-NEXT:    sh1add.uw a0, a0, a1, %regrel_shxadd(g2)
; RV64ZBA-NEXT:    li a1, 100
; RV64ZBA-NEXT:    sh a1, %regrel_lo(g2)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = zext i32 %index to i64
  %arrayidx = getelementptr inbounds nuw [100 x i16], ptr @g2, i64 0, i64 %idxprom
  store i16 100, ptr %arrayidx, align 2
  ret void
}

define void @int_store(i32 %index) {
; RV32I-LABEL: int_store:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 2
; RV32I-NEXT:    lui a1, %hi(g3)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g3)
; RV32I-NEXT:    li a1, 100
; RV32I-NEXT:    sw a1, %regrel_lo(g3)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: int_store:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g3)
; RV32ZBA-NEXT:    sh2add a0, a0, a1, %regrel_shxadd(g3)
; RV32ZBA-NEXT:    li a1, 100
; RV32ZBA-NEXT:    sw a1, %regrel_lo(g3)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: int_store:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    slli a0, a0, 2
; RV64I-NEXT:    lui a1, %hi(g3)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g3)
; RV64I-NEXT:    li a1, 100
; RV64I-NEXT:    sw a1, %regrel_lo(g3)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: int_store:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g3)
; RV64ZBA-NEXT:    sh2add a0, a0, a1, %regrel_shxadd(g3)
; RV64ZBA-NEXT:    li a1, 100
; RV64ZBA-NEXT:    sw a1, %regrel_lo(g3)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = sext i32 %index to i64
  %arrayidx = getelementptr inbounds [100 x i32], ptr @g3, i64 0, i64 %idxprom
  store i32 100, ptr %arrayidx, align 4
  ret void
}

define void @int_store_offset(i32 %index) {
; RV32I-LABEL: int_store_offset:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 2
; RV32I-NEXT:    lui a1, %hi(g3+16)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g3+16)
; RV32I-NEXT:    li a1, 100
; RV32I-NEXT:    sw a1, %regrel_lo(g3+16)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: int_store_offset:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g3+16)
; RV32ZBA-NEXT:    sh2add a0, a0, a1, %regrel_shxadd(g3+16)
; RV32ZBA-NEXT:    li a1, 100
; RV32ZBA-NEXT:    sw a1, %regrel_lo(g3+16)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: int_store_offset:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    slli a0, a0, 2
; RV64I-NEXT:    lui a1, %hi(g3+16)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g3+16)
; RV64I-NEXT:    li a1, 100
; RV64I-NEXT:    sw a1, %regrel_lo(g3+16)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: int_store_offset:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g3+16)
; RV64ZBA-NEXT:    sh2add a0, a0, a1, %regrel_shxadd(g3+16)
; RV64ZBA-NEXT:    li a1, 100
; RV64ZBA-NEXT:    sw a1, %regrel_lo(g3+16)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %add = add nsw i32 %index, 4
  %idxprom = sext i32 %add to i64
  %arrayidx = getelementptr inbounds [100 x i32], ptr @g3, i64 0, i64 %idxprom
  store i32 100, ptr %arrayidx, align 4
  ret void
}

define void @int_store_uw(i32 %index) {
; RV32I-LABEL: int_store_uw:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 2
; RV32I-NEXT:    lui a1, %hi(g3)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g3)
; RV32I-NEXT:    li a1, 100
; RV32I-NEXT:    sw a1, %regrel_lo(g3)(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: int_store_uw:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g3)
; RV32ZBA-NEXT:    sh2add a0, a0, a1, %regrel_shxadd(g3)
; RV32ZBA-NEXT:    li a1, 100
; RV32ZBA-NEXT:    sw a1, %regrel_lo(g3)(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: int_store_uw:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 30
; RV64I-NEXT:    lui a1, %hi(g3)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g3)
; RV64I-NEXT:    li a1, 100
; RV64I-NEXT:    sw a1, %regrel_lo(g3)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: int_store_uw:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g3)
; RV64ZBA-NEXT:    sh2add.uw a0, a0, a1, %regrel_shxadd(g3)
; RV64ZBA-NEXT:    li a1, 100
; RV64ZBA-NEXT:    sw a1, %regrel_lo(g3)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = zext i32 %index to i64
  %arrayidx = getelementptr inbounds nuw [100 x i32], ptr @g3, i64 0, i64 %idxprom
  store i32 100, ptr %arrayidx, align 4
  ret void
}

define void @long_long_store(i32 %index) {
; RV32I-LABEL: long_long_store:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 3
; RV32I-NEXT:    lui a1, %hi(g4)
; RV32I-NEXT:    addi a1, a1, %lo(g4)
; RV32I-NEXT:    add a0, a1, a0
; RV32I-NEXT:    li a1, 100
; RV32I-NEXT:    sw a1, 0(a0)
; RV32I-NEXT:    sw zero, 4(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: long_long_store:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g4)
; RV32ZBA-NEXT:    addi a1, a1, %lo(g4)
; RV32ZBA-NEXT:    sh3add a0, a0, a1
; RV32ZBA-NEXT:    li a1, 100
; RV32ZBA-NEXT:    sw a1, 0(a0)
; RV32ZBA-NEXT:    sw zero, 4(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: long_long_store:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    slli a0, a0, 3
; RV64I-NEXT:    lui a1, %hi(g4)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g4)
; RV64I-NEXT:    li a1, 100
; RV64I-NEXT:    sd a1, %regrel_lo(g4)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: long_long_store:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g4)
; RV64ZBA-NEXT:    sh3add a0, a0, a1, %regrel_shxadd(g4)
; RV64ZBA-NEXT:    li a1, 100
; RV64ZBA-NEXT:    sd a1, %regrel_lo(g4)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = sext i32 %index to i64
  %arrayidx = getelementptr inbounds [100 x i64], ptr @g4, i64 0, i64 %idxprom
  store i64 100, ptr %arrayidx, align 8
  ret void
}

define void @long_long_store_offset(i32 %index) {
; RV32I-LABEL: long_long_store_offset:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 3
; RV32I-NEXT:    lui a1, %hi(g4)
; RV32I-NEXT:    addi a1, a1, %lo(g4)
; RV32I-NEXT:    add a0, a0, a1
; RV32I-NEXT:    li a1, 100
; RV32I-NEXT:    sw a1, 32(a0)
; RV32I-NEXT:    sw zero, 36(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: long_long_store_offset:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g4)
; RV32ZBA-NEXT:    addi a1, a1, %lo(g4)
; RV32ZBA-NEXT:    sh3add a0, a0, a1
; RV32ZBA-NEXT:    li a1, 100
; RV32ZBA-NEXT:    sw a1, 32(a0)
; RV32ZBA-NEXT:    sw zero, 36(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: long_long_store_offset:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    slli a0, a0, 3
; RV64I-NEXT:    lui a1, %hi(g4+32)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g4+32)
; RV64I-NEXT:    li a1, 100
; RV64I-NEXT:    sd a1, %regrel_lo(g4+32)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: long_long_store_offset:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g4+32)
; RV64ZBA-NEXT:    sh3add a0, a0, a1, %regrel_shxadd(g4+32)
; RV64ZBA-NEXT:    li a1, 100
; RV64ZBA-NEXT:    sd a1, %regrel_lo(g4+32)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %add = add nsw i32 %index, 4
  %idxprom = sext i32 %add to i64
  %arrayidx = getelementptr inbounds [100 x i64], ptr @g4, i64 0, i64 %idxprom
  store i64 100, ptr %arrayidx, align 8
  ret void
}

define void @long_long_store_uw(i32 %index) {
; RV32I-LABEL: long_long_store_uw:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 3
; RV32I-NEXT:    lui a1, %hi(g4)
; RV32I-NEXT:    addi a1, a1, %lo(g4)
; RV32I-NEXT:    add a0, a1, a0
; RV32I-NEXT:    li a1, 100
; RV32I-NEXT:    sw a1, 0(a0)
; RV32I-NEXT:    sw zero, 4(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: long_long_store_uw:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g4)
; RV32ZBA-NEXT:    addi a1, a1, %lo(g4)
; RV32ZBA-NEXT:    sh3add a0, a0, a1
; RV32ZBA-NEXT:    li a1, 100
; RV32ZBA-NEXT:    sw a1, 0(a0)
; RV32ZBA-NEXT:    sw zero, 4(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: long_long_store_uw:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 29
; RV64I-NEXT:    lui a1, %hi(g4)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g4)
; RV64I-NEXT:    li a1, 100
; RV64I-NEXT:    sd a1, %regrel_lo(g4)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: long_long_store_uw:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g4)
; RV64ZBA-NEXT:    sh3add.uw a0, a0, a1, %regrel_shxadd(g4)
; RV64ZBA-NEXT:    li a1, 100
; RV64ZBA-NEXT:    sd a1, %regrel_lo(g4)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = zext i32 %index to i64
  %arrayidx = getelementptr inbounds nuw [100 x i64], ptr @g4, i64 0, i64 %idxprom
  store i64 100, ptr %arrayidx, align 8
  ret void
}

define void @add_more_oneuse_store(i32 %index) {
; RV32I-LABEL: add_more_oneuse_store:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 3
; RV32I-NEXT:    lui a1, %hi(g4)
; RV32I-NEXT:    addi a1, a1, %lo(g4)
; RV32I-NEXT:    add a0, a1, a0
; RV32I-NEXT:    lw a0, 0(a0)
; RV32I-NEXT:    slli a0, a0, 3
; RV32I-NEXT:    add a0, a1, a0
; RV32I-NEXT:    li a1, 100
; RV32I-NEXT:    sw a1, 0(a0)
; RV32I-NEXT:    sw zero, 4(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: add_more_oneuse_store:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g4)
; RV32ZBA-NEXT:    addi a1, a1, %lo(g4)
; RV32ZBA-NEXT:    sh3add a0, a0, a1
; RV32ZBA-NEXT:    lw a0, 0(a0)
; RV32ZBA-NEXT:    sh3add a0, a0, a1
; RV32ZBA-NEXT:    li a1, 100
; RV32ZBA-NEXT:    sw a1, 0(a0)
; RV32ZBA-NEXT:    sw zero, 4(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: add_more_oneuse_store:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    lui a1, %hi(g4)
; RV64I-NEXT:    addi a1, a1, %lo(g4)
; RV64I-NEXT:    slli a0, a0, 3
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    ld a0, 0(a0)
; RV64I-NEXT:    slli a0, a0, 3
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    li a1, 100
; RV64I-NEXT:    sd a1, 0(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: add_more_oneuse_store:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    sext.w a0, a0
; RV64ZBA-NEXT:    lui a1, %hi(g4)
; RV64ZBA-NEXT:    addi a1, a1, %lo(g4)
; RV64ZBA-NEXT:    sh3add a0, a0, a1
; RV64ZBA-NEXT:    ld a0, 0(a0)
; RV64ZBA-NEXT:    sh3add a0, a0, a1
; RV64ZBA-NEXT:    li a1, 100
; RV64ZBA-NEXT:    sd a1, 0(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = sext i32 %index to i64
  %arrayidx = getelementptr inbounds [100 x i64], ptr @g4, i64 0, i64 %idxprom
  %0 = load i64, ptr %arrayidx, align 8
  %arrayidx1 = getelementptr inbounds [100 x i64], ptr @g4, i64 0, i64 %0
  store i64 100, ptr %arrayidx1, align 8
  ret void
}

define void @test_nesting_store(i32 %index) {
; RV32I-LABEL: test_nesting_store:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a0, a0, 1
; RV32I-NEXT:    lui a1, %hi(g2)
; RV32I-NEXT:    add a0, a0, a1, %regrel_add(g2)
; RV32I-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV32I-NEXT:    lui a1, %hi(g4)
; RV32I-NEXT:    addi a1, a1, %lo(g4)
; RV32I-NEXT:    slli a0, a0, 3
; RV32I-NEXT:    add a0, a1, a0
; RV32I-NEXT:    li a1, 100
; RV32I-NEXT:    sw a1, 0(a0)
; RV32I-NEXT:    sw zero, 4(a0)
; RV32I-NEXT:    ret
;
; RV32ZBA-LABEL: test_nesting_store:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    lui a1, %hi(g2)
; RV32ZBA-NEXT:    sh1add a0, a0, a1, %regrel_shxadd(g2)
; RV32ZBA-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV32ZBA-NEXT:    lui a1, %hi(g4)
; RV32ZBA-NEXT:    addi a1, a1, %lo(g4)
; RV32ZBA-NEXT:    sh3add a0, a0, a1
; RV32ZBA-NEXT:    li a1, 100
; RV32ZBA-NEXT:    sw a1, 0(a0)
; RV32ZBA-NEXT:    sw zero, 4(a0)
; RV32ZBA-NEXT:    ret
;
; RV64I-LABEL: test_nesting_store:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    lui a1, %hi(g2)
; RV64I-NEXT:    slli a0, a0, 1
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g2)
; RV64I-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV64I-NEXT:    slli a0, a0, 3
; RV64I-NEXT:    lui a1, %hi(g4)
; RV64I-NEXT:    add a0, a0, a1, %regrel_add(g4)
; RV64I-NEXT:    li a1, 100
; RV64I-NEXT:    sd a1, %regrel_lo(g4)(a0)
; RV64I-NEXT:    ret
;
; RV64ZBA-LABEL: test_nesting_store:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    lui a1, %hi(g2)
; RV64ZBA-NEXT:    sh1add a0, a0, a1, %regrel_shxadd(g2)
; RV64ZBA-NEXT:    lh a0, %regrel_lo(g2)(a0)
; RV64ZBA-NEXT:    lui a1, %hi(g4)
; RV64ZBA-NEXT:    sh3add a0, a0, a1, %regrel_shxadd(g4)
; RV64ZBA-NEXT:    li a1, 100
; RV64ZBA-NEXT:    sd a1, %regrel_lo(g4)(a0)
; RV64ZBA-NEXT:    ret
entry:
  %idxprom = sext i32 %index to i64
  %arrayidx = getelementptr inbounds [100 x i16], ptr @g2, i64 0, i64 %idxprom
  %0 = load i16, ptr %arrayidx, align 2
  %idxprom1 = sext i16 %0 to i64
  %arrayidx2 = getelementptr inbounds [100 x i64], ptr @g4, i64 0, i64 %idxprom1
  store i64 100, ptr %arrayidx2, align 8
  ret void
}
