; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+f,+d,+v -target-abi=lp64d < %s | FileCheck %s


define i1 @sqrt_nnan_check_f32(float %a0) {
; CHECK-LABEL: sqrt_nnan_check_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
  %sqr = call nnan float @llvm.sqrt.f32(float %a0)
  %res = tail call i1 @llvm.is.fpclass.f32(float %sqr, i32 3)
  ret i1 %res
}

define i1 @sqrt_neginf_f32(float %a0) {
; CHECK-LABEL: sqrt_neginf_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
  %sqr = call float @llvm.sqrt.f32(float %a0)
  %res = tail call i1 @llvm.is.fpclass.f32(float %sqr, i32 4)
  ret i1 %res
}

define i1 @sqrt_negnormal_f32(float %a0) {
; CHECK-LABEL: sqrt_negnormal_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
  %sqr = call float @llvm.sqrt.f32(float %a0)
  %res = tail call i1 @llvm.is.fpclass.f32(float %sqr, i32 8)
  ret i1 %res
}

define i1 @sqrt_nsz_negzero_f32(float %a0) {
; CHECK-LABEL: sqrt_nsz_negzero_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
  %sqr = call nsz float @llvm.sqrt.f32(float %a0)
  %res = tail call i1 @llvm.is.fpclass.f32(float %sqr, i32 32)
  ret i1 %res
}

define i1 @sqrt_posinf_f32(float %a0) {
; CHECK-LABEL: sqrt_posinf_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fsqrt.s fa5, fa0
; CHECK-NEXT:    fclass.s a0, fa5
; CHECK-NEXT:    slli a0, a0, 56
; CHECK-NEXT:    srli a0, a0, 63
; CHECK-NEXT:    ret
  %sqr = call float @llvm.sqrt.f32(float %a0)
  %res = tail call i1 @llvm.is.fpclass.f32(float %sqr, i32 512)
  ret i1 %res
}

declare float @llvm.sqrt.f32(float)
declare i1 @llvm.is.fpclass.f32(float, i32)

declare <vscale x 2 x float> @llvm.sqrt.nxv2f32(<vscale x 2 x float>)
declare <vscale x 2 x i1> @llvm.is.fpclass.nxv2f32(<vscale x 2 x float>, i32)

define <vscale x 2 x i1> @vsqrt_nnan_check_nxv2f32(<vscale x 2 x float> %a0) {
; CHECK-LABEL: vsqrt_nnan_check_nxv2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmclr.m v0
; CHECK-NEXT:    ret
  %sqr = call nnan <vscale x 2 x float> @llvm.sqrt.nxv2f32(<vscale x 2 x float> %a0)
  %res = tail call <vscale x 2 x i1> @llvm.is.fpclass.nxv2f32(<vscale x 2 x float> %sqr, i32 3)
  ret <vscale x 2 x i1> %res
}

define <vscale x 2 x i1> @vsqrt_neginf_nxv2f32(<vscale x 2 x float> %a0) {
; CHECK-LABEL: vsqrt_neginf_nxv2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmclr.m v0
; CHECK-NEXT:    ret
  %sqr = call <vscale x 2 x float> @llvm.sqrt.nxv2f32(<vscale x 2 x float> %a0)
  %res = tail call <vscale x 2 x i1> @llvm.is.fpclass.nxv2f32(<vscale x 2 x float> %sqr, i32 4)
  ret <vscale x 2 x i1> %res
}

define <vscale x 2 x i1> @vsqrt_negnormal_nxv2f32(<vscale x 2 x float> %a0) {
; CHECK-LABEL: vsqrt_negnormal_nxv2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmclr.m v0
; CHECK-NEXT:    ret
  %sqr = call <vscale x 2 x float> @llvm.sqrt.nxv2f32(<vscale x 2 x float> %a0)
  %res = tail call <vscale x 2 x i1> @llvm.is.fpclass.nxv2f32(<vscale x 2 x float> %sqr, i32 8)
  ret <vscale x 2 x i1> %res
}

define <vscale x 2 x i1> @vsqrt_nsz_negzero_nxv2f32(<vscale x 2 x float> %a0) {
; CHECK-LABEL: vsqrt_nsz_negzero_nxv2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmclr.m v0
; CHECK-NEXT:    ret
  %sqr = call nsz <vscale x 2 x float> @llvm.sqrt.nxv2f32(<vscale x 2 x float> %a0)
  %res = tail call <vscale x 2 x i1> @llvm.is.fpclass.nxv2f32(<vscale x 2 x float> %sqr, i32 32)
  ret <vscale x 2 x i1> %res
}

define <vscale x 2 x i1> @vsqrt_posinf_nxv2f32(<vscale x 2 x float> %a0) {
; CHECK-LABEL: vsqrt_posinf_nxv2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; CHECK-NEXT:    vfsqrt.v v8, v8
; CHECK-NEXT:    vfclass.v v8, v8
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    vmseq.vx v0, v8, a0
; CHECK-NEXT:    ret
  %sqr = call <vscale x 2 x float> @llvm.sqrt.nxv2f32(<vscale x 2 x float> %a0)
  %res = tail call <vscale x 2 x i1> @llvm.is.fpclass.nxv2f32(<vscale x 2 x float> %sqr, i32 512)
  ret <vscale x 2 x i1> %res
}
