; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv64 -mattr=+v,+d,+zvfh -o - %s | FileCheck %s

define void @forward_store(<32 x half> %halves, ptr %p, ptr %p2, ptr %p3, ptr %p4) {
; CHECK-LABEL: forward_store:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a4, a0, 16
; CHECK-NEXT:    li a5, 32
; CHECK-NEXT:    vsetvli zero, a5, e16, m4, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    addi a5, a0, 32
; CHECK-NEXT:    addi a0, a0, 48
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a4)
; CHECK-NEXT:    vle16.v v9, (a5)
; CHECK-NEXT:    vle16.v v10, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    vse16.v v10, (a3)
; CHECK-NEXT:    ret
  store <32 x half> %halves, ptr %p, align 256
  %gep1 = getelementptr inbounds nuw i8, ptr %p, i32 16
  %gep2 = getelementptr inbounds nuw i8, ptr %p, i32 32
  %gep3 = getelementptr inbounds nuw i8, ptr %p, i32 48
  %ld1 = load <8 x half>, ptr %gep1, align 4
  %ld2 = load <8 x half>, ptr %gep2, align 4
  %ld3 = load <8 x half>, ptr %gep3, align 4
  store <8 x half> %ld1, ptr %p2
  store <8 x half> %ld2, ptr %p3
  store <8 x half> %ld3, ptr %p4
  ret void
}

define void @no_forward_store(<32 x half> %halves, ptr %p, ptr %p2, ptr %p3, ptr %p4) {
; CHECK-LABEL: no_forward_store:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a4, a0, 8
; CHECK-NEXT:    li a5, 32
; CHECK-NEXT:    vsetvli zero, a5, e16, m4, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    addi a5, a0, 16
; CHECK-NEXT:    addi a0, a0, 64
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a4)
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v9, (a5)
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v10, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vse16.v v10, (a3)
; CHECK-NEXT:    ret
  store <32 x half> %halves, ptr %p, align 256
  %gep1 = getelementptr inbounds nuw i8, ptr %p, i32 8
  %gep2 = getelementptr inbounds nuw i8, ptr %p, i32 16
  %gep3 = getelementptr inbounds nuw i8, ptr %p, i32 64
  %ld1 = load <8 x half>, ptr %gep1, align 4
  %ld2 = load <4 x i32>, ptr %gep2, align 4
  %ld3 = load <8 x half>, ptr %gep3, align 4
  store <8 x half> %ld1, ptr %p2
  store <4 x i32> %ld2, ptr %p3
  store <8 x half> %ld3, ptr %p4
  ret void
}
