; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+f -verify-machineinstrs | FileCheck %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+f -verify-machineinstrs | FileCheck %s
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+zfinx -verify-machineinstrs | FileCheck %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+zfinx -verify-machineinstrs | FileCheck %s
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+f -verify-machineinstrs -O0 | FileCheck %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+f -verify-machineinstrs -O0 | FileCheck %s

define iXLen @func_get_fpenv() {
; CHECK-LABEL: func_get_fpenv:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    frcsr a0
; CHECK-NEXT:    ret
entry:
  %fpenv = call iXLen @llvm.get.fpenv.iXLen()
  ret iXLen %fpenv
}

define void @func_set_fpenv(iXLen %fpenv) {
; CHECK-LABEL: func_set_fpenv:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fscsr a0
; CHECK-NEXT:    ret
entry:
  call void @llvm.set.fpenv.iXLen(iXLen %fpenv)
  ret void
}

define void @func_reset_fpenv() {
; CHECK-LABEL: func_reset_fpenv:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fscsr zero
; CHECK-NEXT:    ret
entry:
  call void @llvm.reset.fpenv()
  ret void
}

define iXLen @func_get_fpmode() {
; CHECK-LABEL: func_get_fpmode:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    frcsr a0
; CHECK-NEXT:    ret
entry:
  %fpenv = call iXLen @llvm.get.fpmode.iXLen()
  ret iXLen %fpenv
}

define void @func_set_fpmode(iXLen %fpmode) {
; CHECK-LABEL: func_set_fpmode:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li    a1, -32
; CHECK-NEXT:    csrc  fcsr, a1
; CHECK-NEXT:    andi  a0, a0, -32
; CHECK-NEXT:    csrs  fcsr, a0
; CHECK-NEXT:    ret
entry:
  call void @llvm.set.fpmode.iXLen(iXLen %fpmode)
  ret void
}

define void @func_reset_fpmode() {
; CHECK-LABEL: func_reset_fpmode:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li   a0, -32
; CHECK-NEXT:    csrc fcsr, a0
; CHECK-NEXT:    ret
entry:
  call void @llvm.reset.fpmode()
  ret void
}
