; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv64 -mattr=+f -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=riscv64 -mattr=+zfinx -verify-machineinstrs < %s | FileCheck %s

define i64 @func_get_fpenv() {
; CHECK-LABEL: func_get_fpenv:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    frcsr a0
; CHECK-NEXT:    ret
entry:
  %fpenv = call i64 @llvm.get.fpenv.i64()
  ret i64 %fpenv
}

define void @func_set_fpenv(i64 %fpenv) {
; CHECK-LABEL: func_set_fpenv:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fscsr a0
; CHECK-NEXT:    ret
entry:
  call void @llvm.set.fpenv.i64(i64 %fpenv)
  ret void
}

define void @func_reset_fpenv() {
; CHECK-LABEL: func_reset_fpenv:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fscsr zero
; CHECK-NEXT:    ret
entry:
  call void @llvm.reset.fpenv()
  ret void
}
