; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=riscv32-linux-gnu             | FileCheck %s --check-prefix=RV32I
; RUN: llc < %s -mtriple=riscv32-linux-gnu -mattr=+m   | FileCheck %s --check-prefix=RV32M

; RV32 inline-expands i128 div/rem, so keep the checks focused on the absence
; of libcalls instead of the whole expanded algorithm.

define void @sdivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; RV32I-LABEL: sdivrem_i128:
; RV32I:       # %bb.0: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    addi sp, sp, -288
; RV32I-NEXT:    .cfi_def_cfa_offset 288
; RV32I-NEXT:    sw ra, 284(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s0, 280(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s1, 276(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s2, 272(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s3, 268(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s4, 264(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s5, 260(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s6, 256(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s7, 252(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s8, 248(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s9, 244(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s10, 240(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s11, 236(sp) # 4-byte Folded Spill
; RV32I-NEXT:    .cfi_offset ra, -4
; RV32I-NEXT:    .cfi_offset s0, -8
; RV32I-NEXT:    .cfi_offset s1, -12
; RV32I-NEXT:    .cfi_offset s2, -16
; RV32I-NEXT:    .cfi_offset s3, -20
; RV32I-NEXT:    .cfi_offset s4, -24
; RV32I-NEXT:    .cfi_offset s5, -28
; RV32I-NEXT:    .cfi_offset s6, -32
; RV32I-NEXT:    .cfi_offset s7, -36
; RV32I-NEXT:    .cfi_offset s8, -40
; RV32I-NEXT:    .cfi_offset s9, -44
; RV32I-NEXT:    .cfi_offset s10, -48
; RV32I-NEXT:    .cfi_offset s11, -52
; RV32I-NEXT:    sw a1, 52(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw a0, 48(sp) # 4-byte Folded Spill
; RV32I-NEXT:    lw t2, 0(a2)
; RV32I-NEXT:    lw s3, 4(a2)
; RV32I-NEXT:    lw s11, 8(a2)
; RV32I-NEXT:    lw ra, 0(a3)
; RV32I-NEXT:    lw t3, 4(a3)
; RV32I-NEXT:    lw a7, 8(a3)
; RV32I-NEXT:    lw t0, 12(a3)
; RV32I-NEXT:    lw t4, 12(a2)
; RV32I-NEXT:    or a0, t2, s3
; RV32I-NEXT:    snez a1, s11
; RV32I-NEXT:    snez t1, a0
; RV32I-NEXT:    add a1, t4, a1
; RV32I-NEXT:    snez s2, t2
; RV32I-NEXT:    sw a1, 24(sp) # 4-byte Folded Spill
; RV32I-NEXT:    bltz t4, .LBB0_2
; RV32I-NEXT:  # %bb.1: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    mv s4, t4
; RV32I-NEXT:    mv t6, s11
; RV32I-NEXT:    mv s5, s3
; RV32I-NEXT:    mv s6, t2
; RV32I-NEXT:    j .LBB0_3
; RV32I-NEXT:  .LBB0_2:
; RV32I-NEXT:    neg a0, s11
; RV32I-NEXT:    neg a1, a1
; RV32I-NEXT:    neg a2, s3
; RV32I-NEXT:    sltu a3, a0, t1
; RV32I-NEXT:    sub t6, a0, t1
; RV32I-NEXT:    sub s5, a2, s2
; RV32I-NEXT:    sub s4, a1, a3
; RV32I-NEXT:    neg s6, t2
; RV32I-NEXT:  .LBB0_3: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    or a0, ra, t3
; RV32I-NEXT:    snez a1, a7
; RV32I-NEXT:    snez a4, a0
; RV32I-NEXT:    add a1, t0, a1
; RV32I-NEXT:    snez a5, ra
; RV32I-NEXT:    sw a4, 20(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw a5, 16(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw a1, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    bltz t0, .LBB0_5
; RV32I-NEXT:  # %bb.4: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    mv s9, t0
; RV32I-NEXT:    mv s8, a7
; RV32I-NEXT:    mv t5, t3
; RV32I-NEXT:    sw ra, 92(sp) # 4-byte Folded Spill
; RV32I-NEXT:    j .LBB0_6
; RV32I-NEXT:  .LBB0_5:
; RV32I-NEXT:    neg a0, a7
; RV32I-NEXT:    neg a1, a1
; RV32I-NEXT:    neg a2, t3
; RV32I-NEXT:    sltu a3, a0, a4
; RV32I-NEXT:    sub s8, a0, a4
; RV32I-NEXT:    sub t5, a2, a5
; RV32I-NEXT:    sub s9, a1, a3
; RV32I-NEXT:    neg a0, ra
; RV32I-NEXT:    sw a0, 92(sp) # 4-byte Folded Spill
; RV32I-NEXT:  .LBB0_6: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    lui a0, 349525
; RV32I-NEXT:    lui a1, 209715
; RV32I-NEXT:    lui a2, 61681
; RV32I-NEXT:    addi s7, a0, 1365
; RV32I-NEXT:    addi s1, a1, 819
; RV32I-NEXT:    addi a1, a2, -241
; RV32I-NEXT:    bnez t5, .LBB0_9
; RV32I-NEXT:  # %bb.7: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    lw a2, 92(sp) # 4-byte Folded Reload
; RV32I-NEXT:    srli a0, a2, 1
; RV32I-NEXT:    or a0, a2, a0
; RV32I-NEXT:    srli a2, a0, 2
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 8
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 16
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    not a0, a0
; RV32I-NEXT:    srli a2, a0, 1
; RV32I-NEXT:    and a2, a2, s7
; RV32I-NEXT:    sub a0, a0, a2
; RV32I-NEXT:    and a2, a0, s1
; RV32I-NEXT:    srli a0, a0, 2
; RV32I-NEXT:    and a0, a0, s1
; RV32I-NEXT:    add a0, a2, a0
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    and a0, a0, a1
; RV32I-NEXT:    slli a2, a0, 8
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    slli a2, a0, 16
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    srli a0, a0, 24
; RV32I-NEXT:    addi a5, a0, 32
; RV32I-NEXT:    or a6, s8, s9
; RV32I-NEXT:    beqz s9, .LBB0_10
; RV32I-NEXT:  .LBB0_8:
; RV32I-NEXT:    srli a0, s9, 1
; RV32I-NEXT:    or a0, s9, a0
; RV32I-NEXT:    srli a2, a0, 2
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 8
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 16
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    not a0, a0
; RV32I-NEXT:    srli a2, a0, 1
; RV32I-NEXT:    and a2, a2, s7
; RV32I-NEXT:    sub a0, a0, a2
; RV32I-NEXT:    and a2, a0, s1
; RV32I-NEXT:    srli a0, a0, 2
; RV32I-NEXT:    and a0, a0, s1
; RV32I-NEXT:    add a0, a2, a0
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    and a0, a0, a1
; RV32I-NEXT:    slli a2, a0, 8
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    slli a2, a0, 16
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    srli a4, a0, 24
; RV32I-NEXT:    j .LBB0_11
; RV32I-NEXT:  .LBB0_9:
; RV32I-NEXT:    srli a0, t5, 1
; RV32I-NEXT:    or a0, t5, a0
; RV32I-NEXT:    srli a2, a0, 2
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 8
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 16
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    not a0, a0
; RV32I-NEXT:    srli a2, a0, 1
; RV32I-NEXT:    and a2, a2, s7
; RV32I-NEXT:    sub a0, a0, a2
; RV32I-NEXT:    and a2, a0, s1
; RV32I-NEXT:    srli a0, a0, 2
; RV32I-NEXT:    and a0, a0, s1
; RV32I-NEXT:    add a0, a2, a0
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    and a0, a0, a1
; RV32I-NEXT:    slli a2, a0, 8
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    slli a2, a0, 16
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    srli a5, a0, 24
; RV32I-NEXT:    or a6, s8, s9
; RV32I-NEXT:    bnez s9, .LBB0_8
; RV32I-NEXT:  .LBB0_10: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    srli a0, s8, 1
; RV32I-NEXT:    or a0, s8, a0
; RV32I-NEXT:    srli a2, a0, 2
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 8
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 16
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    not a0, a0
; RV32I-NEXT:    srli a2, a0, 1
; RV32I-NEXT:    and a2, a2, s7
; RV32I-NEXT:    sub a0, a0, a2
; RV32I-NEXT:    and a2, a0, s1
; RV32I-NEXT:    srli a0, a0, 2
; RV32I-NEXT:    and a0, a0, s1
; RV32I-NEXT:    add a0, a2, a0
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    and a0, a0, a1
; RV32I-NEXT:    slli a2, a0, 8
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    slli a2, a0, 16
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    srli a0, a0, 24
; RV32I-NEXT:    addi a4, a0, 32
; RV32I-NEXT:  .LBB0_11: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    sw t0, 100(sp) # 4-byte Folded Spill
; RV32I-NEXT:    addi a0, a5, 64
; RV32I-NEXT:    bnez a6, .LBB0_13
; RV32I-NEXT:  # %bb.12: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    mv a4, a0
; RV32I-NEXT:  .LBB0_13: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    snez s0, a6
; RV32I-NEXT:    sw a7, 96(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw t1, 32(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s2, 28(sp) # 4-byte Folded Spill
; RV32I-NEXT:    bnez s5, .LBB0_15
; RV32I-NEXT:  # %bb.14: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    srli a2, s6, 1
; RV32I-NEXT:    or a2, s6, a2
; RV32I-NEXT:    srli a3, a2, 2
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 4
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 8
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 16
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    not a2, a2
; RV32I-NEXT:    srli a3, a2, 1
; RV32I-NEXT:    and a3, a3, s7
; RV32I-NEXT:    sub a2, a2, a3
; RV32I-NEXT:    and a3, a2, s1
; RV32I-NEXT:    srli a2, a2, 2
; RV32I-NEXT:    and a2, a2, s1
; RV32I-NEXT:    add a2, a3, a2
; RV32I-NEXT:    srli a3, a2, 4
; RV32I-NEXT:    add a2, a2, a3
; RV32I-NEXT:    and a2, a2, a1
; RV32I-NEXT:    slli a3, a2, 8
; RV32I-NEXT:    add a2, a2, a3
; RV32I-NEXT:    slli a3, a2, 16
; RV32I-NEXT:    add a2, a2, a3
; RV32I-NEXT:    srli a2, a2, 24
; RV32I-NEXT:    addi a2, a2, 32
; RV32I-NEXT:    j .LBB0_16
; RV32I-NEXT:  .LBB0_15:
; RV32I-NEXT:    srli a2, s5, 1
; RV32I-NEXT:    or a2, s5, a2
; RV32I-NEXT:    srli a3, a2, 2
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 4
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 8
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 16
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    not a2, a2
; RV32I-NEXT:    srli a3, a2, 1
; RV32I-NEXT:    and a3, a3, s7
; RV32I-NEXT:    sub a2, a2, a3
; RV32I-NEXT:    and a3, a2, s1
; RV32I-NEXT:    srli a2, a2, 2
; RV32I-NEXT:    and a2, a2, s1
; RV32I-NEXT:    add a2, a3, a2
; RV32I-NEXT:    srli a3, a2, 4
; RV32I-NEXT:    add a2, a2, a3
; RV32I-NEXT:    and a2, a2, a1
; RV32I-NEXT:    slli a3, a2, 8
; RV32I-NEXT:    add a2, a2, a3
; RV32I-NEXT:    slli a3, a2, 16
; RV32I-NEXT:    add a2, a2, a3
; RV32I-NEXT:    srli a2, a2, 24
; RV32I-NEXT:  .LBB0_16: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    sw s8, 88(sp) # 4-byte Folded Spill
; RV32I-NEXT:    lw a3, 92(sp) # 4-byte Folded Reload
; RV32I-NEXT:    or a6, a3, s8
; RV32I-NEXT:    sw s9, 84(sp) # 4-byte Folded Spill
; RV32I-NEXT:    or a7, t5, s9
; RV32I-NEXT:    or t0, s6, t6
; RV32I-NEXT:    or t1, s5, s4
; RV32I-NEXT:    sltu a5, a0, a5
; RV32I-NEXT:    addi s0, s0, -1
; RV32I-NEXT:    addi a0, a2, 64
; RV32I-NEXT:    or s2, t6, s4
; RV32I-NEXT:    sltu s8, a0, a2
; RV32I-NEXT:    snez s9, s2
; RV32I-NEXT:    addi s9, s9, -1
; RV32I-NEXT:    bnez s4, .LBB0_18
; RV32I-NEXT:  # %bb.17: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    srli a2, t6, 1
; RV32I-NEXT:    or a2, t6, a2
; RV32I-NEXT:    srli a3, a2, 2
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 4
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 8
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 16
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    not a2, a2
; RV32I-NEXT:    srli a3, a2, 1
; RV32I-NEXT:    and a3, a3, s7
; RV32I-NEXT:    sub a2, a2, a3
; RV32I-NEXT:    and a3, a2, s1
; RV32I-NEXT:    srli a2, a2, 2
; RV32I-NEXT:    and a2, a2, s1
; RV32I-NEXT:    add a2, a3, a2
; RV32I-NEXT:    srli a3, a2, 4
; RV32I-NEXT:    add a2, a2, a3
; RV32I-NEXT:    and a1, a2, a1
; RV32I-NEXT:    slli a2, a1, 8
; RV32I-NEXT:    add a1, a1, a2
; RV32I-NEXT:    slli a2, a1, 16
; RV32I-NEXT:    add a1, a1, a2
; RV32I-NEXT:    srli a1, a1, 24
; RV32I-NEXT:    addi a2, a1, 32
; RV32I-NEXT:    j .LBB0_19
; RV32I-NEXT:  .LBB0_18:
; RV32I-NEXT:    srli a2, s4, 1
; RV32I-NEXT:    or a2, s4, a2
; RV32I-NEXT:    srli a3, a2, 2
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 4
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 8
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 16
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    not a2, a2
; RV32I-NEXT:    srli a3, a2, 1
; RV32I-NEXT:    and a3, a3, s7
; RV32I-NEXT:    sub a2, a2, a3
; RV32I-NEXT:    and a3, a2, s1
; RV32I-NEXT:    srli a2, a2, 2
; RV32I-NEXT:    and a2, a2, s1
; RV32I-NEXT:    add a2, a3, a2
; RV32I-NEXT:    srli a3, a2, 4
; RV32I-NEXT:    add a2, a2, a3
; RV32I-NEXT:    and a1, a2, a1
; RV32I-NEXT:    slli a2, a1, 8
; RV32I-NEXT:    add a1, a1, a2
; RV32I-NEXT:    slli a2, a1, 16
; RV32I-NEXT:    add a1, a1, a2
; RV32I-NEXT:    srli a2, a1, 24
; RV32I-NEXT:  .LBB0_19: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    or a3, a6, a7
; RV32I-NEXT:    or a6, t0, t1
; RV32I-NEXT:    and a5, s0, a5
; RV32I-NEXT:    and a1, s9, s8
; RV32I-NEXT:    bnez s2, .LBB0_21
; RV32I-NEXT:  # %bb.20: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    mv a2, a0
; RV32I-NEXT:  .LBB0_21: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    sw t3, 56(sp) # 4-byte Folded Spill
; RV32I-NEXT:    seqz a0, a3
; RV32I-NEXT:    seqz a3, a6
; RV32I-NEXT:    sltu a7, a4, a2
; RV32I-NEXT:    sub t0, a5, a1
; RV32I-NEXT:    mv a6, a7
; RV32I-NEXT:    lw t1, 100(sp) # 4-byte Folded Reload
; RV32I-NEXT:    beq a5, a1, .LBB0_23
; RV32I-NEXT:  # %bb.22: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    sltu a6, a5, a1
; RV32I-NEXT:  .LBB0_23: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    sub a1, t0, a7
; RV32I-NEXT:    or a3, a0, a3
; RV32I-NEXT:    neg a0, a6
; RV32I-NEXT:    seqz s10, a6
; RV32I-NEXT:    addi s10, s10, -1
; RV32I-NEXT:    sub a2, a4, a2
; RV32I-NEXT:    or a5, a0, s10
; RV32I-NEXT:    xor a4, t1, t4
; RV32I-NEXT:    beqz a5, .LBB0_25
; RV32I-NEXT:  # %bb.24: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    snez a5, a5
; RV32I-NEXT:    j .LBB0_26
; RV32I-NEXT:  .LBB0_25:
; RV32I-NEXT:    snez a5, a1
; RV32I-NEXT:    sltiu a6, a2, 128
; RV32I-NEXT:    xori a6, a6, 1
; RV32I-NEXT:    or a5, a6, a5
; RV32I-NEXT:  .LBB0_26: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    srai s2, a4, 31
; RV32I-NEXT:    or a5, a3, a5
; RV32I-NEXT:    addi a4, a5, -1
; RV32I-NEXT:    and s8, a4, s4
; RV32I-NEXT:    and s7, a4, t6
; RV32I-NEXT:    and a3, a4, s5
; RV32I-NEXT:    and a4, a4, s6
; RV32I-NEXT:    sw t4, 60(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s2, 64(sp) # 4-byte Folded Spill
; RV32I-NEXT:    bnez a5, .LBB0_37
; RV32I-NEXT:  # %bb.27: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    xori a5, a2, 127
; RV32I-NEXT:    or a5, a5, a0
; RV32I-NEXT:    or a6, a1, s10
; RV32I-NEXT:    or a5, a5, a6
; RV32I-NEXT:    beqz a5, .LBB0_37
; RV32I-NEXT:  # %bb.28: # %udiv-bb15
; RV32I-NEXT:    sw ra, 44(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s11, 68(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s3, 72(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw t2, 76(sp) # 4-byte Folded Spill
; RV32I-NEXT:    addi s7, a2, 1
; RV32I-NEXT:    li a4, 127
; RV32I-NEXT:    sub a4, a4, a2
; RV32I-NEXT:    sw zero, 200(sp)
; RV32I-NEXT:    sw zero, 204(sp)
; RV32I-NEXT:    sw zero, 208(sp)
; RV32I-NEXT:    sw zero, 212(sp)
; RV32I-NEXT:    sw s6, 216(sp)
; RV32I-NEXT:    sw s5, 220(sp)
; RV32I-NEXT:    sw t6, 224(sp)
; RV32I-NEXT:    sw s4, 228(sp)
; RV32I-NEXT:    addi a2, sp, 216
; RV32I-NEXT:    seqz s8, s7
; RV32I-NEXT:    srli a3, a4, 3
; RV32I-NEXT:    andi a5, a4, 31
; RV32I-NEXT:    add s8, a1, s8
; RV32I-NEXT:    andi a3, a3, 12
; RV32I-NEXT:    xori a5, a5, 31
; RV32I-NEXT:    or a1, s7, s8
; RV32I-NEXT:    sub a2, a2, a3
; RV32I-NEXT:    seqz a1, a1
; RV32I-NEXT:    lw a3, 0(a2)
; RV32I-NEXT:    lw a6, 4(a2)
; RV32I-NEXT:    lw a7, 8(a2)
; RV32I-NEXT:    lw a2, 12(a2)
; RV32I-NEXT:    add a1, a0, a1
; RV32I-NEXT:    sltu a0, a1, a0
; RV32I-NEXT:    or t0, s7, a1
; RV32I-NEXT:    add s10, s10, a0
; RV32I-NEXT:    or a0, s8, s10
; RV32I-NEXT:    srli t1, a7, 1
; RV32I-NEXT:    srli t2, a6, 1
; RV32I-NEXT:    or a0, t0, a0
; RV32I-NEXT:    srli t0, a3, 1
; RV32I-NEXT:    srl t1, t1, a5
; RV32I-NEXT:    srl t2, t2, a5
; RV32I-NEXT:    srl a5, t0, a5
; RV32I-NEXT:    sll a2, a2, a4
; RV32I-NEXT:    or t0, a2, t1
; RV32I-NEXT:    sll a2, a7, a4
; RV32I-NEXT:    sll a6, a6, a4
; RV32I-NEXT:    or t2, a2, t2
; RV32I-NEXT:    or a6, a6, a5
; RV32I-NEXT:    sll s9, a3, a4
; RV32I-NEXT:    li ra, 0
; RV32I-NEXT:    beqz a0, .LBB0_36
; RV32I-NEXT:  # %bb.29: # %udiv-preheader4
; RV32I-NEXT:    li t1, 0
; RV32I-NEXT:    li a4, 0
; RV32I-NEXT:    li a7, 0
; RV32I-NEXT:    sw zero, 184(sp)
; RV32I-NEXT:    sw zero, 188(sp)
; RV32I-NEXT:    sw zero, 192(sp)
; RV32I-NEXT:    sw zero, 196(sp)
; RV32I-NEXT:    sw s6, 168(sp)
; RV32I-NEXT:    sw s5, 172(sp)
; RV32I-NEXT:    sw t6, 176(sp)
; RV32I-NEXT:    sw s4, 180(sp)
; RV32I-NEXT:    srli a0, s7, 3
; RV32I-NEXT:    addi a2, sp, 168
; RV32I-NEXT:    andi a0, a0, 12
; RV32I-NEXT:    add a0, a2, a0
; RV32I-NEXT:    lw a2, 4(a0)
; RV32I-NEXT:    lw a3, 8(a0)
; RV32I-NEXT:    lw a5, 12(a0)
; RV32I-NEXT:    lw t3, 0(a0)
; RV32I-NEXT:    andi a0, s7, 31
; RV32I-NEXT:    xori a0, a0, 31
; RV32I-NEXT:    slli t4, a5, 1
; RV32I-NEXT:    slli t6, a3, 1
; RV32I-NEXT:    slli s0, a2, 1
; RV32I-NEXT:    sll t4, t4, a0
; RV32I-NEXT:    sll s1, t6, a0
; RV32I-NEXT:    sll s2, s0, a0
; RV32I-NEXT:    lw s3, 92(sp) # 4-byte Folded Reload
; RV32I-NEXT:    seqz a0, s3
; RV32I-NEXT:    srl a3, a3, s7
; RV32I-NEXT:    or s0, a3, t4
; RV32I-NEXT:    or a3, s3, t5
; RV32I-NEXT:    sub t6, t5, a0
; RV32I-NEXT:    seqz a3, a3
; RV32I-NEXT:    srl a0, a2, s7
; RV32I-NEXT:    or a0, a0, s1
; RV32I-NEXT:    lw a2, 88(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sub s4, a2, a3
; RV32I-NEXT:    sltu a2, a2, a3
; RV32I-NEXT:    lw a3, 84(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sub s5, a3, a2
; RV32I-NEXT:    srl a2, t3, s7
; RV32I-NEXT:    srl s1, a5, s7
; RV32I-NEXT:    or s2, a2, s2
; RV32I-NEXT:    addi s3, s3, -1
; RV32I-NEXT:    sw s3, 80(sp) # 4-byte Folded Spill
; RV32I-NEXT:    j .LBB0_31
; RV32I-NEXT:  .LBB0_30: # %udiv-do-while3
; RV32I-NEXT:    # in Loop: Header=BB0_31 Depth=1
; RV32I-NEXT:    srli a5, t2, 31
; RV32I-NEXT:    slli t0, t0, 1
; RV32I-NEXT:    sub a3, s3, a3
; RV32I-NEXT:    srli s3, a6, 31
; RV32I-NEXT:    slli t2, t2, 1
; RV32I-NEXT:    or a5, t0, a5
; RV32I-NEXT:    srli t0, s9, 31
; RV32I-NEXT:    slli a6, a6, 1
; RV32I-NEXT:    slli s9, s9, 1
; RV32I-NEXT:    or t2, t2, s3
; RV32I-NEXT:    lw t3, 84(sp) # 4-byte Folded Reload
; RV32I-NEXT:    and s3, s0, t3
; RV32I-NEXT:    or a6, a6, t0
; RV32I-NEXT:    lw t0, 88(sp) # 4-byte Folded Reload
; RV32I-NEXT:    and t0, s0, t0
; RV32I-NEXT:    or s9, ra, s9
; RV32I-NEXT:    sub t3, a2, t0
; RV32I-NEXT:    sltu a2, a2, t0
; RV32I-NEXT:    or t0, s7, s8
; RV32I-NEXT:    sub s3, a0, s3
; RV32I-NEXT:    seqz t4, s7
; RV32I-NEXT:    addi s7, s7, -1
; RV32I-NEXT:    andi ra, s0, 1
; RV32I-NEXT:    sub a0, a3, s6
; RV32I-NEXT:    seqz a3, t0
; RV32I-NEXT:    sub s8, s8, t4
; RV32I-NEXT:    or a6, t1, a6
; RV32I-NEXT:    or t2, a4, t2
; RV32I-NEXT:    or t0, a7, a5
; RV32I-NEXT:    sub s0, t3, s1
; RV32I-NEXT:    sltu a4, t3, s1
; RV32I-NEXT:    sub s1, s3, a2
; RV32I-NEXT:    sltu a2, a1, a3
; RV32I-NEXT:    sub a1, a1, a3
; RV32I-NEXT:    sub s1, s1, a4
; RV32I-NEXT:    sub s10, s10, a2
; RV32I-NEXT:    or a2, s8, s10
; RV32I-NEXT:    or a3, s7, a1
; RV32I-NEXT:    or a2, a3, a2
; RV32I-NEXT:    sub s2, s11, s2
; RV32I-NEXT:    li t1, 0
; RV32I-NEXT:    li a4, 0
; RV32I-NEXT:    li a7, 0
; RV32I-NEXT:    beqz a2, .LBB0_36
; RV32I-NEXT:  .LBB0_31: # %udiv-do-while3
; RV32I-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32I-NEXT:    srli a2, s2, 31
; RV32I-NEXT:    slli a3, a0, 1
; RV32I-NEXT:    slli s2, s2, 1
; RV32I-NEXT:    or s3, a3, a2
; RV32I-NEXT:    srli a2, t0, 31
; RV32I-NEXT:    or s11, s2, a2
; RV32I-NEXT:    beq t6, s3, .LBB0_33
; RV32I-NEXT:  # %bb.32: # %udiv-do-while3
; RV32I-NEXT:    # in Loop: Header=BB0_31 Depth=1
; RV32I-NEXT:    sltu a3, t6, s3
; RV32I-NEXT:    j .LBB0_34
; RV32I-NEXT:  .LBB0_33: # in Loop: Header=BB0_31 Depth=1
; RV32I-NEXT:    lw a2, 80(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sltu a3, a2, s11
; RV32I-NEXT:  .LBB0_34: # %udiv-do-while3
; RV32I-NEXT:    # in Loop: Header=BB0_31 Depth=1
; RV32I-NEXT:    srli a2, s0, 31
; RV32I-NEXT:    slli s1, s1, 1
; RV32I-NEXT:    srli s2, a0, 31
; RV32I-NEXT:    slli s0, s0, 1
; RV32I-NEXT:    or a0, s1, a2
; RV32I-NEXT:    or a2, s0, s2
; RV32I-NEXT:    sub s0, s4, a2
; RV32I-NEXT:    sltu s1, s4, a2
; RV32I-NEXT:    sub s2, s5, a0
; RV32I-NEXT:    sltu a3, s0, a3
; RV32I-NEXT:    sub s0, s2, s1
; RV32I-NEXT:    sub s0, s0, a3
; RV32I-NEXT:    srai s0, s0, 31
; RV32I-NEXT:    lw a3, 92(sp) # 4-byte Folded Reload
; RV32I-NEXT:    and s2, s0, a3
; RV32I-NEXT:    and a3, s0, t5
; RV32I-NEXT:    sltu s6, s11, s2
; RV32I-NEXT:    mv s1, s6
; RV32I-NEXT:    beq s3, a3, .LBB0_30
; RV32I-NEXT:  # %bb.35: # %udiv-do-while3
; RV32I-NEXT:    # in Loop: Header=BB0_31 Depth=1
; RV32I-NEXT:    sltu s1, s3, a3
; RV32I-NEXT:    j .LBB0_30
; RV32I-NEXT:  .LBB0_36: # %udiv-loop-exit2
; RV32I-NEXT:    srli a0, s9, 31
; RV32I-NEXT:    slli a3, a6, 1
; RV32I-NEXT:    srli a1, a6, 31
; RV32I-NEXT:    or a3, a3, a0
; RV32I-NEXT:    slli a0, t2, 1
; RV32I-NEXT:    srli a5, t2, 31
; RV32I-NEXT:    slli t0, t0, 1
; RV32I-NEXT:    slli s9, s9, 1
; RV32I-NEXT:    or s7, a0, a1
; RV32I-NEXT:    or s8, t0, a5
; RV32I-NEXT:    or a4, ra, s9
; RV32I-NEXT:    lw t2, 76(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s3, 72(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s11, 68(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw ra, 44(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw t4, 60(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw t1, 100(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s2, 64(sp) # 4-byte Folded Reload
; RV32I-NEXT:  .LBB0_37: # %udiv-end1
; RV32I-NEXT:    xor a0, a4, s2
; RV32I-NEXT:    sw a0, 44(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sltu a0, a0, s2
; RV32I-NEXT:    xor a1, a3, s2
; RV32I-NEXT:    sw a0, 40(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw a0, 84(sp) # 4-byte Folded Spill
; RV32I-NEXT:    lw s9, 96(sp) # 4-byte Folded Reload
; RV32I-NEXT:    beqz a3, .LBB0_39
; RV32I-NEXT:  # %bb.38: # %udiv-end1
; RV32I-NEXT:    sltu a0, a1, s2
; RV32I-NEXT:    sw a0, 84(sp) # 4-byte Folded Spill
; RV32I-NEXT:  .LBB0_39: # %udiv-end1
; RV32I-NEXT:    lw s10, 56(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sw a1, 36(sp) # 4-byte Folded Spill
; RV32I-NEXT:    bltz t4, .LBB0_41
; RV32I-NEXT:  # %bb.40: # %udiv-end1
; RV32I-NEXT:    mv s4, t4
; RV32I-NEXT:    bltz t1, .LBB0_42
; RV32I-NEXT:    j .LBB0_43
; RV32I-NEXT:  .LBB0_41:
; RV32I-NEXT:    neg a0, s11
; RV32I-NEXT:    lw a1, 24(sp) # 4-byte Folded Reload
; RV32I-NEXT:    neg a1, a1
; RV32I-NEXT:    lw a2, 28(sp) # 4-byte Folded Reload
; RV32I-NEXT:    add a2, s3, a2
; RV32I-NEXT:    lw a4, 32(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sltu a3, a0, a4
; RV32I-NEXT:    sub s11, a0, a4
; RV32I-NEXT:    neg s3, a2
; RV32I-NEXT:    sub s4, a1, a3
; RV32I-NEXT:    neg t2, t2
; RV32I-NEXT:    bgez t1, .LBB0_43
; RV32I-NEXT:  .LBB0_42:
; RV32I-NEXT:    neg a0, s9
; RV32I-NEXT:    lw a1, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    neg a1, a1
; RV32I-NEXT:    lw a2, 16(sp) # 4-byte Folded Reload
; RV32I-NEXT:    add a2, s10, a2
; RV32I-NEXT:    lw a4, 20(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sltu a3, a0, a4
; RV32I-NEXT:    sub s9, a0, a4
; RV32I-NEXT:    neg s10, a2
; RV32I-NEXT:    sub t1, a1, a3
; RV32I-NEXT:    neg ra, ra
; RV32I-NEXT:  .LBB0_43: # %udiv-end1
; RV32I-NEXT:    lui a0, 349525
; RV32I-NEXT:    lui a2, 209715
; RV32I-NEXT:    lui a3, 61681
; RV32I-NEXT:    addi a1, a0, 1365
; RV32I-NEXT:    addi a5, a2, 819
; RV32I-NEXT:    addi a4, a3, -241
; RV32I-NEXT:    bnez s10, .LBB0_46
; RV32I-NEXT:  # %bb.44: # %udiv-end1
; RV32I-NEXT:    srli a0, ra, 1
; RV32I-NEXT:    or a0, ra, a0
; RV32I-NEXT:    srli a2, a0, 2
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 8
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 16
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    not a0, a0
; RV32I-NEXT:    srli a2, a0, 1
; RV32I-NEXT:    and a2, a2, a1
; RV32I-NEXT:    sub a0, a0, a2
; RV32I-NEXT:    and a2, a0, a5
; RV32I-NEXT:    srli a0, a0, 2
; RV32I-NEXT:    and a0, a0, a5
; RV32I-NEXT:    add a0, a2, a0
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    and a0, a0, a4
; RV32I-NEXT:    slli a2, a0, 8
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    slli a2, a0, 16
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    srli a0, a0, 24
; RV32I-NEXT:    addi a7, a0, 32
; RV32I-NEXT:    or t0, s9, t1
; RV32I-NEXT:    beqz t1, .LBB0_47
; RV32I-NEXT:  .LBB0_45:
; RV32I-NEXT:    srli a0, t1, 1
; RV32I-NEXT:    or a0, t1, a0
; RV32I-NEXT:    srli a2, a0, 2
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 8
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 16
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    not a0, a0
; RV32I-NEXT:    srli a2, a0, 1
; RV32I-NEXT:    and a2, a2, a1
; RV32I-NEXT:    sub a0, a0, a2
; RV32I-NEXT:    and a2, a0, a5
; RV32I-NEXT:    srli a0, a0, 2
; RV32I-NEXT:    and a0, a0, a5
; RV32I-NEXT:    add a0, a2, a0
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    and a0, a0, a4
; RV32I-NEXT:    slli a2, a0, 8
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    slli a2, a0, 16
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    srli a6, a0, 24
; RV32I-NEXT:    addi a0, a7, 64
; RV32I-NEXT:    beqz t0, .LBB0_48
; RV32I-NEXT:    j .LBB0_49
; RV32I-NEXT:  .LBB0_46:
; RV32I-NEXT:    srli a0, s10, 1
; RV32I-NEXT:    or a0, s10, a0
; RV32I-NEXT:    srli a2, a0, 2
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 8
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 16
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    not a0, a0
; RV32I-NEXT:    srli a2, a0, 1
; RV32I-NEXT:    and a2, a2, a1
; RV32I-NEXT:    sub a0, a0, a2
; RV32I-NEXT:    and a2, a0, a5
; RV32I-NEXT:    srli a0, a0, 2
; RV32I-NEXT:    and a0, a0, a5
; RV32I-NEXT:    add a0, a2, a0
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    and a0, a0, a4
; RV32I-NEXT:    slli a2, a0, 8
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    slli a2, a0, 16
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    srli a7, a0, 24
; RV32I-NEXT:    or t0, s9, t1
; RV32I-NEXT:    bnez t1, .LBB0_45
; RV32I-NEXT:  .LBB0_47: # %udiv-end1
; RV32I-NEXT:    srli a0, s9, 1
; RV32I-NEXT:    or a0, s9, a0
; RV32I-NEXT:    srli a2, a0, 2
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 8
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    srli a2, a0, 16
; RV32I-NEXT:    or a0, a0, a2
; RV32I-NEXT:    not a0, a0
; RV32I-NEXT:    srli a2, a0, 1
; RV32I-NEXT:    and a2, a2, a1
; RV32I-NEXT:    sub a0, a0, a2
; RV32I-NEXT:    and a2, a0, a5
; RV32I-NEXT:    srli a0, a0, 2
; RV32I-NEXT:    and a0, a0, a5
; RV32I-NEXT:    add a0, a2, a0
; RV32I-NEXT:    srli a2, a0, 4
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    and a0, a0, a4
; RV32I-NEXT:    slli a2, a0, 8
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    slli a2, a0, 16
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    srli a0, a0, 24
; RV32I-NEXT:    addi a6, a0, 32
; RV32I-NEXT:    addi a0, a7, 64
; RV32I-NEXT:    bnez t0, .LBB0_49
; RV32I-NEXT:  .LBB0_48: # %udiv-end1
; RV32I-NEXT:    mv a6, a0
; RV32I-NEXT:  .LBB0_49: # %udiv-end1
; RV32I-NEXT:    snez t5, t0
; RV32I-NEXT:    bnez s3, .LBB0_51
; RV32I-NEXT:  # %bb.50: # %udiv-end1
; RV32I-NEXT:    srli a2, t2, 1
; RV32I-NEXT:    or a2, t2, a2
; RV32I-NEXT:    srli a3, a2, 2
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 4
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 8
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 16
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    not a2, a2
; RV32I-NEXT:    srli a3, a2, 1
; RV32I-NEXT:    and a3, a3, a1
; RV32I-NEXT:    sub a2, a2, a3
; RV32I-NEXT:    and a3, a2, a5
; RV32I-NEXT:    srli a2, a2, 2
; RV32I-NEXT:    and a2, a2, a5
; RV32I-NEXT:    add a2, a3, a2
; RV32I-NEXT:    srli a3, a2, 4
; RV32I-NEXT:    add a2, a2, a3
; RV32I-NEXT:    and a2, a2, a4
; RV32I-NEXT:    slli a3, a2, 8
; RV32I-NEXT:    add a2, a2, a3
; RV32I-NEXT:    slli a3, a2, 16
; RV32I-NEXT:    add a2, a2, a3
; RV32I-NEXT:    srli a2, a2, 24
; RV32I-NEXT:    addi a2, a2, 32
; RV32I-NEXT:    j .LBB0_52
; RV32I-NEXT:  .LBB0_51:
; RV32I-NEXT:    srli a2, s3, 1
; RV32I-NEXT:    or a2, s3, a2
; RV32I-NEXT:    srli a3, a2, 2
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 4
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 8
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 16
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    not a2, a2
; RV32I-NEXT:    srli a3, a2, 1
; RV32I-NEXT:    and a3, a3, a1
; RV32I-NEXT:    sub a2, a2, a3
; RV32I-NEXT:    and a3, a2, a5
; RV32I-NEXT:    srli a2, a2, 2
; RV32I-NEXT:    and a2, a2, a5
; RV32I-NEXT:    add a2, a3, a2
; RV32I-NEXT:    srli a3, a2, 4
; RV32I-NEXT:    add a2, a2, a3
; RV32I-NEXT:    and a2, a2, a4
; RV32I-NEXT:    slli a3, a2, 8
; RV32I-NEXT:    add a2, a2, a3
; RV32I-NEXT:    slli a3, a2, 16
; RV32I-NEXT:    add a2, a2, a3
; RV32I-NEXT:    srli a2, a2, 24
; RV32I-NEXT:  .LBB0_52: # %udiv-end1
; RV32I-NEXT:    or t0, ra, s9
; RV32I-NEXT:    sw t1, 100(sp) # 4-byte Folded Spill
; RV32I-NEXT:    or t1, s10, t1
; RV32I-NEXT:    or t3, t2, s11
; RV32I-NEXT:    or t4, s3, s4
; RV32I-NEXT:    sltu a7, a0, a7
; RV32I-NEXT:    addi t5, t5, -1
; RV32I-NEXT:    addi a0, a2, 64
; RV32I-NEXT:    or t6, s11, s4
; RV32I-NEXT:    sltu s0, a0, a2
; RV32I-NEXT:    snez s1, t6
; RV32I-NEXT:    addi s1, s1, -1
; RV32I-NEXT:    bnez s4, .LBB0_54
; RV32I-NEXT:  # %bb.53: # %udiv-end1
; RV32I-NEXT:    srli a2, s11, 1
; RV32I-NEXT:    or a2, s11, a2
; RV32I-NEXT:    srli a3, a2, 2
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 4
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 8
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 16
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    not a2, a2
; RV32I-NEXT:    srli a3, a2, 1
; RV32I-NEXT:    and a1, a3, a1
; RV32I-NEXT:    sub a2, a2, a1
; RV32I-NEXT:    and a1, a2, a5
; RV32I-NEXT:    srli a2, a2, 2
; RV32I-NEXT:    and a2, a2, a5
; RV32I-NEXT:    add a1, a1, a2
; RV32I-NEXT:    srli a2, a1, 4
; RV32I-NEXT:    add a1, a1, a2
; RV32I-NEXT:    and a1, a1, a4
; RV32I-NEXT:    slli a2, a1, 8
; RV32I-NEXT:    add a1, a1, a2
; RV32I-NEXT:    slli a2, a1, 16
; RV32I-NEXT:    add a1, a1, a2
; RV32I-NEXT:    srli a1, a1, 24
; RV32I-NEXT:    addi a2, a1, 32
; RV32I-NEXT:    j .LBB0_55
; RV32I-NEXT:  .LBB0_54:
; RV32I-NEXT:    srli a2, s4, 1
; RV32I-NEXT:    or a2, s4, a2
; RV32I-NEXT:    srli a3, a2, 2
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 4
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 8
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    srli a3, a2, 16
; RV32I-NEXT:    or a2, a2, a3
; RV32I-NEXT:    not a2, a2
; RV32I-NEXT:    srli a3, a2, 1
; RV32I-NEXT:    and a1, a3, a1
; RV32I-NEXT:    sub a2, a2, a1
; RV32I-NEXT:    and a1, a2, a5
; RV32I-NEXT:    srli a2, a2, 2
; RV32I-NEXT:    and a2, a2, a5
; RV32I-NEXT:    add a1, a1, a2
; RV32I-NEXT:    srli a2, a1, 4
; RV32I-NEXT:    add a1, a1, a2
; RV32I-NEXT:    and a1, a1, a4
; RV32I-NEXT:    slli a2, a1, 8
; RV32I-NEXT:    add a1, a1, a2
; RV32I-NEXT:    slli a2, a1, 16
; RV32I-NEXT:    add a1, a1, a2
; RV32I-NEXT:    srli a2, a1, 24
; RV32I-NEXT:  .LBB0_55: # %udiv-end1
; RV32I-NEXT:    or a3, t0, t1
; RV32I-NEXT:    or a4, t3, t4
; RV32I-NEXT:    and a1, t5, a7
; RV32I-NEXT:    and s0, s1, s0
; RV32I-NEXT:    bnez t6, .LBB0_57
; RV32I-NEXT:  # %bb.56: # %udiv-end1
; RV32I-NEXT:    mv a2, a0
; RV32I-NEXT:  .LBB0_57: # %udiv-end1
; RV32I-NEXT:    seqz a0, a3
; RV32I-NEXT:    seqz a5, a4
; RV32I-NEXT:    sltu a7, a6, a2
; RV32I-NEXT:    sub t1, a1, s0
; RV32I-NEXT:    mv t0, a7
; RV32I-NEXT:    beq a1, s0, .LBB0_59
; RV32I-NEXT:  # %bb.58: # %udiv-end1
; RV32I-NEXT:    sltu t0, a1, s0
; RV32I-NEXT:  .LBB0_59: # %udiv-end1
; RV32I-NEXT:    xor a3, s8, s2
; RV32I-NEXT:    xor a4, s7, s2
; RV32I-NEXT:    sub a1, t1, a7
; RV32I-NEXT:    or a7, a0, a5
; RV32I-NEXT:    neg a0, t0
; RV32I-NEXT:    seqz t0, t0
; RV32I-NEXT:    addi t0, t0, -1
; RV32I-NEXT:    or a5, a0, t0
; RV32I-NEXT:    sub a2, a6, a2
; RV32I-NEXT:    beqz a5, .LBB0_61
; RV32I-NEXT:  # %bb.60: # %udiv-end1
; RV32I-NEXT:    snez a6, a5
; RV32I-NEXT:    j .LBB0_62
; RV32I-NEXT:  .LBB0_61:
; RV32I-NEXT:    snez a5, a1
; RV32I-NEXT:    sltiu a6, a2, 128
; RV32I-NEXT:    xori a6, a6, 1
; RV32I-NEXT:    or a6, a6, a5
; RV32I-NEXT:  .LBB0_62: # %udiv-end1
; RV32I-NEXT:    sub a5, a4, s2
; RV32I-NEXT:    sw a5, 80(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sltu a4, a4, s2
; RV32I-NEXT:    sub a5, a3, s2
; RV32I-NEXT:    or a3, a7, a6
; RV32I-NEXT:    addi a6, a3, -1
; RV32I-NEXT:    sw s4, 56(sp) # 4-byte Folded Spill
; RV32I-NEXT:    and s5, a6, s4
; RV32I-NEXT:    and s7, a6, s11
; RV32I-NEXT:    and s4, a6, s3
; RV32I-NEXT:    and s6, a6, t2
; RV32I-NEXT:    sw t2, 76(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s3, 72(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s11, 68(sp) # 4-byte Folded Spill
; RV32I-NEXT:    bnez a3, .LBB0_73
; RV32I-NEXT:  # %bb.63: # %udiv-end1
; RV32I-NEXT:    xori a3, a2, 127
; RV32I-NEXT:    or a3, a3, a0
; RV32I-NEXT:    or a6, a1, t0
; RV32I-NEXT:    or a3, a3, a6
; RV32I-NEXT:    beqz a3, .LBB0_73
; RV32I-NEXT:  # %bb.64: # %udiv-bb1
; RV32I-NEXT:    sw a5, 28(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw a4, 32(sp) # 4-byte Folded Spill
; RV32I-NEXT:    addi a6, a2, 1
; RV32I-NEXT:    li a3, 127
; RV32I-NEXT:    sub a7, a3, a2
; RV32I-NEXT:    sw zero, 136(sp)
; RV32I-NEXT:    sw zero, 140(sp)
; RV32I-NEXT:    sw zero, 144(sp)
; RV32I-NEXT:    sw zero, 148(sp)
; RV32I-NEXT:    lw s0, 76(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sw s0, 152(sp)
; RV32I-NEXT:    lw s1, 72(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sw s1, 156(sp)
; RV32I-NEXT:    lw s2, 68(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sw s2, 160(sp)
; RV32I-NEXT:    lw s3, 56(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sw s3, 164(sp)
; RV32I-NEXT:    addi a2, sp, 152
; RV32I-NEXT:    seqz a3, a6
; RV32I-NEXT:    srli a4, a7, 3
; RV32I-NEXT:    andi a5, a7, 31
; RV32I-NEXT:    add a1, a1, a3
; RV32I-NEXT:    andi a4, a4, 12
; RV32I-NEXT:    xori a3, a5, 31
; RV32I-NEXT:    or a5, a6, a1
; RV32I-NEXT:    sub a2, a2, a4
; RV32I-NEXT:    seqz t3, a5
; RV32I-NEXT:    lw a4, 0(a2)
; RV32I-NEXT:    lw a5, 4(a2)
; RV32I-NEXT:    lw t1, 8(a2)
; RV32I-NEXT:    lw a2, 12(a2)
; RV32I-NEXT:    add t3, a0, t3
; RV32I-NEXT:    sltu a0, t3, a0
; RV32I-NEXT:    or t2, a6, t3
; RV32I-NEXT:    add t0, t0, a0
; RV32I-NEXT:    or a0, a1, t0
; RV32I-NEXT:    srli t4, t1, 1
; RV32I-NEXT:    srli t5, a5, 1
; RV32I-NEXT:    or a0, t2, a0
; RV32I-NEXT:    srli t2, a4, 1
; RV32I-NEXT:    srl t4, t4, a3
; RV32I-NEXT:    srl t5, t5, a3
; RV32I-NEXT:    srl a3, t2, a3
; RV32I-NEXT:    sll a2, a2, a7
; RV32I-NEXT:    or t6, a2, t4
; RV32I-NEXT:    sll a2, t1, a7
; RV32I-NEXT:    sll a5, a5, a7
; RV32I-NEXT:    or t4, a2, t5
; RV32I-NEXT:    or t5, a5, a3
; RV32I-NEXT:    sll a7, a4, a7
; RV32I-NEXT:    sw s9, 96(sp) # 4-byte Folded Spill
; RV32I-NEXT:    li t1, 0
; RV32I-NEXT:    beqz a0, .LBB0_72
; RV32I-NEXT:  # %bb.65: # %udiv-preheader
; RV32I-NEXT:    li s4, 0
; RV32I-NEXT:    li s5, 0
; RV32I-NEXT:    li s6, 0
; RV32I-NEXT:    sw zero, 120(sp)
; RV32I-NEXT:    sw zero, 124(sp)
; RV32I-NEXT:    sw zero, 128(sp)
; RV32I-NEXT:    sw zero, 132(sp)
; RV32I-NEXT:    sw s0, 104(sp)
; RV32I-NEXT:    sw s1, 108(sp)
; RV32I-NEXT:    sw s2, 112(sp)
; RV32I-NEXT:    sw s3, 116(sp)
; RV32I-NEXT:    srli a0, a6, 3
; RV32I-NEXT:    addi a2, sp, 104
; RV32I-NEXT:    andi a0, a0, 12
; RV32I-NEXT:    add a0, a2, a0
; RV32I-NEXT:    lw a2, 4(a0)
; RV32I-NEXT:    lw a3, 8(a0)
; RV32I-NEXT:    lw a4, 12(a0)
; RV32I-NEXT:    lw a5, 0(a0)
; RV32I-NEXT:    andi a0, a6, 31
; RV32I-NEXT:    xori a0, a0, 31
; RV32I-NEXT:    slli t2, a4, 1
; RV32I-NEXT:    slli s0, a3, 1
; RV32I-NEXT:    slli s1, a2, 1
; RV32I-NEXT:    sll t2, t2, a0
; RV32I-NEXT:    sll s2, s0, a0
; RV32I-NEXT:    sll s3, s1, a0
; RV32I-NEXT:    seqz a0, ra
; RV32I-NEXT:    srl a3, a3, a6
; RV32I-NEXT:    or s0, a3, t2
; RV32I-NEXT:    or a3, ra, s10
; RV32I-NEXT:    sub s7, s10, a0
; RV32I-NEXT:    seqz a3, a3
; RV32I-NEXT:    srl a0, a2, a6
; RV32I-NEXT:    or a0, a0, s2
; RV32I-NEXT:    sub s8, s9, a3
; RV32I-NEXT:    sltu a2, s9, a3
; RV32I-NEXT:    lw a3, 100(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sub a3, a3, a2
; RV32I-NEXT:    sw a3, 92(sp) # 4-byte Folded Spill
; RV32I-NEXT:    srl a2, a5, a6
; RV32I-NEXT:    srl s1, a4, a6
; RV32I-NEXT:    or s2, a2, s3
; RV32I-NEXT:    addi a2, ra, -1
; RV32I-NEXT:    sw a2, 88(sp) # 4-byte Folded Spill
; RV32I-NEXT:    j .LBB0_67
; RV32I-NEXT:  .LBB0_66: # %udiv-do-while
; RV32I-NEXT:    # in Loop: Header=BB0_67 Depth=1
; RV32I-NEXT:    srli t2, t4, 31
; RV32I-NEXT:    slli t6, t6, 1
; RV32I-NEXT:    sub s3, s3, s10
; RV32I-NEXT:    srli s10, t5, 31
; RV32I-NEXT:    slli t4, t4, 1
; RV32I-NEXT:    or t2, t6, t2
; RV32I-NEXT:    srli t6, a7, 31
; RV32I-NEXT:    slli t5, t5, 1
; RV32I-NEXT:    slli a7, a7, 1
; RV32I-NEXT:    or t4, t4, s10
; RV32I-NEXT:    lw a4, 100(sp) # 4-byte Folded Reload
; RV32I-NEXT:    and s10, s0, a4
; RV32I-NEXT:    or t5, t5, t6
; RV32I-NEXT:    lw a4, 96(sp) # 4-byte Folded Reload
; RV32I-NEXT:    and t6, s0, a4
; RV32I-NEXT:    or a7, t1, a7
; RV32I-NEXT:    sub a4, a3, t6
; RV32I-NEXT:    sltu a3, a3, t6
; RV32I-NEXT:    or t6, a6, a1
; RV32I-NEXT:    sub s10, a0, s10
; RV32I-NEXT:    seqz a5, a6
; RV32I-NEXT:    addi a6, a6, -1
; RV32I-NEXT:    andi t1, s0, 1
; RV32I-NEXT:    sub a0, s3, a2
; RV32I-NEXT:    seqz a2, t6
; RV32I-NEXT:    sub a1, a1, a5
; RV32I-NEXT:    or t5, s4, t5
; RV32I-NEXT:    or t4, s5, t4
; RV32I-NEXT:    or t6, s6, t2
; RV32I-NEXT:    sub s0, a4, s1
; RV32I-NEXT:    sltu a4, a4, s1
; RV32I-NEXT:    sub s1, s10, a3
; RV32I-NEXT:    sltu a3, t3, a2
; RV32I-NEXT:    sub t3, t3, a2
; RV32I-NEXT:    sub s1, s1, a4
; RV32I-NEXT:    sub t0, t0, a3
; RV32I-NEXT:    or a2, a1, t0
; RV32I-NEXT:    or a3, a6, t3
; RV32I-NEXT:    or a2, a3, a2
; RV32I-NEXT:    sub s2, s11, s2
; RV32I-NEXT:    li s4, 0
; RV32I-NEXT:    li s5, 0
; RV32I-NEXT:    li s6, 0
; RV32I-NEXT:    mv s10, ra
; RV32I-NEXT:    mv ra, s9
; RV32I-NEXT:    beqz a2, .LBB0_72
; RV32I-NEXT:  .LBB0_67: # %udiv-do-while
; RV32I-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32I-NEXT:    srli a2, s2, 31
; RV32I-NEXT:    slli a3, a0, 1
; RV32I-NEXT:    slli s2, s2, 1
; RV32I-NEXT:    or s3, a3, a2
; RV32I-NEXT:    srli a2, t6, 31
; RV32I-NEXT:    or s11, s2, a2
; RV32I-NEXT:    beq s7, s3, .LBB0_69
; RV32I-NEXT:  # %bb.68: # %udiv-do-while
; RV32I-NEXT:    # in Loop: Header=BB0_67 Depth=1
; RV32I-NEXT:    sltu a2, s7, s3
; RV32I-NEXT:    j .LBB0_70
; RV32I-NEXT:  .LBB0_69: # in Loop: Header=BB0_67 Depth=1
; RV32I-NEXT:    lw a2, 88(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sltu a2, a2, s11
; RV32I-NEXT:  .LBB0_70: # %udiv-do-while
; RV32I-NEXT:    # in Loop: Header=BB0_67 Depth=1
; RV32I-NEXT:    srli a3, s0, 31
; RV32I-NEXT:    slli s1, s1, 1
; RV32I-NEXT:    srli s2, a0, 31
; RV32I-NEXT:    slli s0, s0, 1
; RV32I-NEXT:    or a0, s1, a3
; RV32I-NEXT:    or a3, s0, s2
; RV32I-NEXT:    sub s0, s8, a3
; RV32I-NEXT:    sltu s1, s8, a3
; RV32I-NEXT:    lw a4, 92(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sub s2, a4, a0
; RV32I-NEXT:    sltu a2, s0, a2
; RV32I-NEXT:    sub s0, s2, s1
; RV32I-NEXT:    sub s0, s0, a2
; RV32I-NEXT:    srai s0, s0, 31
; RV32I-NEXT:    mv s9, ra
; RV32I-NEXT:    and s2, s0, ra
; RV32I-NEXT:    mv ra, s10
; RV32I-NEXT:    and s10, s0, s10
; RV32I-NEXT:    sltu a2, s11, s2
; RV32I-NEXT:    mv s1, a2
; RV32I-NEXT:    beq s3, s10, .LBB0_66
; RV32I-NEXT:  # %bb.71: # %udiv-do-while
; RV32I-NEXT:    # in Loop: Header=BB0_67 Depth=1
; RV32I-NEXT:    sltu s1, s3, s10
; RV32I-NEXT:    j .LBB0_66
; RV32I-NEXT:  .LBB0_72: # %udiv-loop-exit
; RV32I-NEXT:    srli a0, a7, 31
; RV32I-NEXT:    slli a1, t5, 1
; RV32I-NEXT:    srli a2, t5, 31
; RV32I-NEXT:    or s4, a1, a0
; RV32I-NEXT:    slli a0, t4, 1
; RV32I-NEXT:    srli a1, t4, 31
; RV32I-NEXT:    slli t6, t6, 1
; RV32I-NEXT:    slli a7, a7, 1
; RV32I-NEXT:    or s7, a0, a2
; RV32I-NEXT:    or s5, t6, a1
; RV32I-NEXT:    or s6, t1, a7
; RV32I-NEXT:    lw s9, 96(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw a4, 32(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw a5, 28(sp) # 4-byte Folded Reload
; RV32I-NEXT:  .LBB0_73: # %udiv-end
; RV32I-NEXT:    lw a0, 84(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw a1, 80(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sltu a0, a1, a0
; RV32I-NEXT:    sw a0, 92(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sub a5, a5, a4
; RV32I-NEXT:    sw a5, 88(sp) # 4-byte Folded Spill
; RV32I-NEXT:    mv s11, s10
; RV32I-NEXT:    lw a0, 64(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw a1, 36(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sub s10, a1, a0
; RV32I-NEXT:    lw s0, 60(sp) # 4-byte Folded Reload
; RV32I-NEXT:    srai s0, s0, 31
; RV32I-NEXT:    mv a0, s6
; RV32I-NEXT:    mv a1, s4
; RV32I-NEXT:    mv a2, s9
; RV32I-NEXT:    lw a3, 100(sp) # 4-byte Folded Reload
; RV32I-NEXT:    mv s1, ra
; RV32I-NEXT:    call __muldi3
; RV32I-NEXT:    mv s8, a0
; RV32I-NEXT:    mv s9, a1
; RV32I-NEXT:    mv a0, s7
; RV32I-NEXT:    mv a1, s5
; RV32I-NEXT:    mv a2, s1
; RV32I-NEXT:    mv a3, s11
; RV32I-NEXT:    call __muldi3
; RV32I-NEXT:    add a1, a1, s9
; RV32I-NEXT:    add s8, a0, s8
; RV32I-NEXT:    sltu s2, s8, a0
; RV32I-NEXT:    add s2, a1, s2
; RV32I-NEXT:    mv a0, s1
; RV32I-NEXT:    li a1, 0
; RV32I-NEXT:    mv a2, s6
; RV32I-NEXT:    li a3, 0
; RV32I-NEXT:    call __muldi3
; RV32I-NEXT:    mv s5, a0
; RV32I-NEXT:    mv s7, a1
; RV32I-NEXT:    mv a0, s11
; RV32I-NEXT:    li a1, 0
; RV32I-NEXT:    mv a2, s6
; RV32I-NEXT:    li a3, 0
; RV32I-NEXT:    call __muldi3
; RV32I-NEXT:    add s3, a0, s7
; RV32I-NEXT:    sltu a0, s3, a0
; RV32I-NEXT:    add s6, a1, a0
; RV32I-NEXT:    mv a0, s1
; RV32I-NEXT:    li a1, 0
; RV32I-NEXT:    mv a2, s4
; RV32I-NEXT:    li a3, 0
; RV32I-NEXT:    call __muldi3
; RV32I-NEXT:    add s3, a0, s3
; RV32I-NEXT:    sltu a0, s3, a0
; RV32I-NEXT:    add a0, a1, a0
; RV32I-NEXT:    add s7, s6, a0
; RV32I-NEXT:    mv a0, s11
; RV32I-NEXT:    li a1, 0
; RV32I-NEXT:    mv a2, s4
; RV32I-NEXT:    li a3, 0
; RV32I-NEXT:    call __muldi3
; RV32I-NEXT:    add a2, a0, s7
; RV32I-NEXT:    sltu a3, s7, s6
; RV32I-NEXT:    lw t1, 76(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sltu a4, t1, s5
; RV32I-NEXT:    sltu a0, a2, a0
; RV32I-NEXT:    add a1, a1, a3
; RV32I-NEXT:    add s8, a2, s8
; RV32I-NEXT:    add a0, a1, a0
; RV32I-NEXT:    sltu a1, s8, a2
; RV32I-NEXT:    lw a3, 68(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sltu a2, a3, s8
; RV32I-NEXT:    add a0, a0, s2
; RV32I-NEXT:    lw a5, 56(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sub a1, a5, a1
; RV32I-NEXT:    sub a1, a1, a0
; RV32I-NEXT:    sub a5, a1, a2
; RV32I-NEXT:    sub a6, a3, s8
; RV32I-NEXT:    mv a7, a4
; RV32I-NEXT:    lw t2, 72(sp) # 4-byte Folded Reload
; RV32I-NEXT:    beq t2, s3, .LBB0_75
; RV32I-NEXT:  # %bb.74: # %udiv-end
; RV32I-NEXT:    sltu a7, t2, s3
; RV32I-NEXT:  .LBB0_75: # %udiv-end
; RV32I-NEXT:    lw a0, 92(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw a1, 88(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sub a0, a1, a0
; RV32I-NEXT:    lw a1, 40(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sub a1, s10, a1
; RV32I-NEXT:    lw a2, 84(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw a3, 80(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sub a2, a3, a2
; RV32I-NEXT:    lw a3, 64(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw t0, 44(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sub a3, t0, a3
; RV32I-NEXT:    sltu t0, a6, a7
; RV32I-NEXT:    sub a6, a6, a7
; RV32I-NEXT:    sub a7, t2, s3
; RV32I-NEXT:    sub t1, t1, s5
; RV32I-NEXT:    sub a5, a5, t0
; RV32I-NEXT:    sub t2, a7, a4
; RV32I-NEXT:    xor t0, a6, s0
; RV32I-NEXT:    xor a4, t1, s0
; RV32I-NEXT:    xor a6, a5, s0
; RV32I-NEXT:    xor a7, t2, s0
; RV32I-NEXT:    sltu t1, t0, s0
; RV32I-NEXT:    sltu a5, a4, s0
; RV32I-NEXT:    add t1, s0, t1
; RV32I-NEXT:    sub a6, a6, t1
; RV32I-NEXT:    sub t0, t0, s0
; RV32I-NEXT:    mv t1, a5
; RV32I-NEXT:    beqz t2, .LBB0_77
; RV32I-NEXT:  # %bb.76: # %udiv-end
; RV32I-NEXT:    sltu t1, a7, s0
; RV32I-NEXT:  .LBB0_77: # %udiv-end
; RV32I-NEXT:    sltu t2, t0, t1
; RV32I-NEXT:    sub t0, t0, t1
; RV32I-NEXT:    sub a7, a7, s0
; RV32I-NEXT:    sub a4, a4, s0
; RV32I-NEXT:    lw t1, 48(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sw a3, 0(t1)
; RV32I-NEXT:    sw a1, 4(t1)
; RV32I-NEXT:    sw a2, 8(t1)
; RV32I-NEXT:    sw a0, 12(t1)
; RV32I-NEXT:    sub a0, a6, t2
; RV32I-NEXT:    sub a1, a7, a5
; RV32I-NEXT:    lw a2, 52(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sw a4, 0(a2)
; RV32I-NEXT:    sw a1, 4(a2)
; RV32I-NEXT:    sw t0, 8(a2)
; RV32I-NEXT:    sw a0, 12(a2)
; RV32I-NEXT:    lw ra, 284(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s0, 280(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s1, 276(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s2, 272(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s3, 268(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s4, 264(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s5, 260(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s6, 256(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s7, 252(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s8, 248(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s9, 244(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s10, 240(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s11, 236(sp) # 4-byte Folded Reload
; RV32I-NEXT:    .cfi_restore ra
; RV32I-NEXT:    .cfi_restore s0
; RV32I-NEXT:    .cfi_restore s1
; RV32I-NEXT:    .cfi_restore s2
; RV32I-NEXT:    .cfi_restore s3
; RV32I-NEXT:    .cfi_restore s4
; RV32I-NEXT:    .cfi_restore s5
; RV32I-NEXT:    .cfi_restore s6
; RV32I-NEXT:    .cfi_restore s7
; RV32I-NEXT:    .cfi_restore s8
; RV32I-NEXT:    .cfi_restore s9
; RV32I-NEXT:    .cfi_restore s10
; RV32I-NEXT:    .cfi_restore s11
; RV32I-NEXT:    addi sp, sp, 288
; RV32I-NEXT:    .cfi_def_cfa_offset 0
; RV32I-NEXT:    ret
;
; RV32M-LABEL: sdivrem_i128:
; RV32M:       # %bb.0: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    addi sp, sp, -272
; RV32M-NEXT:    .cfi_def_cfa_offset 272
; RV32M-NEXT:    sw ra, 268(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s0, 264(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s1, 260(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s2, 256(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s3, 252(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s4, 248(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s5, 244(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s6, 240(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s7, 236(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s8, 232(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s9, 228(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s10, 224(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s11, 220(sp) # 4-byte Folded Spill
; RV32M-NEXT:    .cfi_offset ra, -4
; RV32M-NEXT:    .cfi_offset s0, -8
; RV32M-NEXT:    .cfi_offset s1, -12
; RV32M-NEXT:    .cfi_offset s2, -16
; RV32M-NEXT:    .cfi_offset s3, -20
; RV32M-NEXT:    .cfi_offset s4, -24
; RV32M-NEXT:    .cfi_offset s5, -28
; RV32M-NEXT:    .cfi_offset s6, -32
; RV32M-NEXT:    .cfi_offset s7, -36
; RV32M-NEXT:    .cfi_offset s8, -40
; RV32M-NEXT:    .cfi_offset s9, -44
; RV32M-NEXT:    .cfi_offset s10, -48
; RV32M-NEXT:    .cfi_offset s11, -52
; RV32M-NEXT:    sw a1, 32(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw a0, 28(sp) # 4-byte Folded Spill
; RV32M-NEXT:    lw a4, 0(a2)
; RV32M-NEXT:    lw s9, 4(a2)
; RV32M-NEXT:    lw s7, 8(a2)
; RV32M-NEXT:    lw a5, 0(a3)
; RV32M-NEXT:    lw t4, 4(a3)
; RV32M-NEXT:    lw a6, 8(a3)
; RV32M-NEXT:    lw t3, 12(a3)
; RV32M-NEXT:    lw t5, 12(a2)
; RV32M-NEXT:    or a0, a4, s9
; RV32M-NEXT:    snez a1, s7
; RV32M-NEXT:    snez a7, a0
; RV32M-NEXT:    add a1, t5, a1
; RV32M-NEXT:    snez t0, a4
; RV32M-NEXT:    sw s9, 52(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s7, 48(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw a1, 12(sp) # 4-byte Folded Spill
; RV32M-NEXT:    bltz t5, .LBB0_2
; RV32M-NEXT:  # %bb.1: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    mv s8, t5
; RV32M-NEXT:    mv s10, a4
; RV32M-NEXT:    j .LBB0_3
; RV32M-NEXT:  .LBB0_2:
; RV32M-NEXT:    neg a0, s7
; RV32M-NEXT:    neg a1, a1
; RV32M-NEXT:    neg a2, s9
; RV32M-NEXT:    sltu a3, a0, a7
; RV32M-NEXT:    sub s7, a0, a7
; RV32M-NEXT:    sub s9, a2, t0
; RV32M-NEXT:    sub s8, a1, a3
; RV32M-NEXT:    neg s10, a4
; RV32M-NEXT:  .LBB0_3: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    sw a4, 56(sp) # 4-byte Folded Spill
; RV32M-NEXT:    or a0, a5, t4
; RV32M-NEXT:    snez a1, a6
; RV32M-NEXT:    snez a4, a0
; RV32M-NEXT:    add a1, t3, a1
; RV32M-NEXT:    snez t1, a5
; RV32M-NEXT:    sw a7, 20(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw t0, 16(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw a4, 8(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw t1, 4(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw a1, 0(sp) # 4-byte Folded Spill
; RV32M-NEXT:    bltz t3, .LBB0_5
; RV32M-NEXT:  # %bb.4: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    mv s6, t3
; RV32M-NEXT:    mv s5, a6
; RV32M-NEXT:    mv a7, t4
; RV32M-NEXT:    sw a5, 72(sp) # 4-byte Folded Spill
; RV32M-NEXT:    j .LBB0_6
; RV32M-NEXT:  .LBB0_5:
; RV32M-NEXT:    neg a0, a6
; RV32M-NEXT:    neg a1, a1
; RV32M-NEXT:    neg a2, t4
; RV32M-NEXT:    sltu a3, a0, a4
; RV32M-NEXT:    sub s5, a0, a4
; RV32M-NEXT:    sub a7, a2, t1
; RV32M-NEXT:    sub s6, a1, a3
; RV32M-NEXT:    neg a0, a5
; RV32M-NEXT:    sw a0, 72(sp) # 4-byte Folded Spill
; RV32M-NEXT:  .LBB0_6: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    lui a0, 349525
; RV32M-NEXT:    lui a1, 209715
; RV32M-NEXT:    lui a2, 61681
; RV32M-NEXT:    lui a3, 4112
; RV32M-NEXT:    addi s1, a0, 1365
; RV32M-NEXT:    addi s0, a1, 819
; RV32M-NEXT:    addi t6, a2, -241
; RV32M-NEXT:    addi t2, a3, 257
; RV32M-NEXT:    bnez a7, .LBB0_9
; RV32M-NEXT:  # %bb.7: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    lw a1, 72(sp) # 4-byte Folded Reload
; RV32M-NEXT:    srli a0, a1, 1
; RV32M-NEXT:    or a0, a1, a0
; RV32M-NEXT:    srli a1, a0, 2
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 8
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 16
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a1, a0, 1
; RV32M-NEXT:    and a1, a1, s1
; RV32M-NEXT:    sub a0, a0, a1
; RV32M-NEXT:    and a1, a0, s0
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, s0
; RV32M-NEXT:    add a0, a1, a0
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    add a0, a0, a1
; RV32M-NEXT:    and a0, a0, t6
; RV32M-NEXT:    mul a0, a0, t2
; RV32M-NEXT:    srli a0, a0, 24
; RV32M-NEXT:    addi a1, a0, 32
; RV32M-NEXT:    or a2, s5, s6
; RV32M-NEXT:    beqz s6, .LBB0_10
; RV32M-NEXT:  .LBB0_8:
; RV32M-NEXT:    srli a0, s6, 1
; RV32M-NEXT:    or a0, s6, a0
; RV32M-NEXT:    srli a3, a0, 2
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    srli a3, a0, 4
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    srli a3, a0, 8
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    srli a3, a0, 16
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a3, a0, 1
; RV32M-NEXT:    and a3, a3, s1
; RV32M-NEXT:    sub a0, a0, a3
; RV32M-NEXT:    and a3, a0, s0
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, s0
; RV32M-NEXT:    add a0, a3, a0
; RV32M-NEXT:    srli a3, a0, 4
; RV32M-NEXT:    add a0, a0, a3
; RV32M-NEXT:    and a0, a0, t6
; RV32M-NEXT:    mul a0, a0, t2
; RV32M-NEXT:    srli a0, a0, 24
; RV32M-NEXT:    addi a4, a1, 64
; RV32M-NEXT:    beqz a2, .LBB0_11
; RV32M-NEXT:    j .LBB0_12
; RV32M-NEXT:  .LBB0_9:
; RV32M-NEXT:    srli a0, a7, 1
; RV32M-NEXT:    or a0, a7, a0
; RV32M-NEXT:    srli a1, a0, 2
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 8
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 16
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a1, a0, 1
; RV32M-NEXT:    and a1, a1, s1
; RV32M-NEXT:    sub a0, a0, a1
; RV32M-NEXT:    and a1, a0, s0
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, s0
; RV32M-NEXT:    add a0, a1, a0
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    add a0, a0, a1
; RV32M-NEXT:    and a0, a0, t6
; RV32M-NEXT:    mul a1, a0, t2
; RV32M-NEXT:    srli a1, a1, 24
; RV32M-NEXT:    or a2, s5, s6
; RV32M-NEXT:    bnez s6, .LBB0_8
; RV32M-NEXT:  .LBB0_10: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    srli a0, s5, 1
; RV32M-NEXT:    or a0, s5, a0
; RV32M-NEXT:    srli a3, a0, 2
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    srli a3, a0, 4
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    srli a3, a0, 8
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    srli a3, a0, 16
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a3, a0, 1
; RV32M-NEXT:    and a3, a3, s1
; RV32M-NEXT:    sub a0, a0, a3
; RV32M-NEXT:    and a3, a0, s0
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, s0
; RV32M-NEXT:    add a0, a3, a0
; RV32M-NEXT:    srli a3, a0, 4
; RV32M-NEXT:    add a0, a0, a3
; RV32M-NEXT:    and a0, a0, t6
; RV32M-NEXT:    mul a0, a0, t2
; RV32M-NEXT:    srli a0, a0, 24
; RV32M-NEXT:    addi a0, a0, 32
; RV32M-NEXT:    addi a4, a1, 64
; RV32M-NEXT:    bnez a2, .LBB0_12
; RV32M-NEXT:  .LBB0_11: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    mv a0, a4
; RV32M-NEXT:  .LBB0_12: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    snez s2, a2
; RV32M-NEXT:    sw a5, 36(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw a6, 84(sp) # 4-byte Folded Spill
; RV32M-NEXT:    bnez s9, .LBB0_14
; RV32M-NEXT:  # %bb.13: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    srli a2, s10, 1
; RV32M-NEXT:    or a2, s10, a2
; RV32M-NEXT:    srli a3, a2, 2
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    srli a3, a2, 4
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    srli a3, a2, 8
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    srli a3, a2, 16
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    not a2, a2
; RV32M-NEXT:    srli a3, a2, 1
; RV32M-NEXT:    and a3, a3, s1
; RV32M-NEXT:    sub a2, a2, a3
; RV32M-NEXT:    and a3, a2, s0
; RV32M-NEXT:    srli a2, a2, 2
; RV32M-NEXT:    and a2, a2, s0
; RV32M-NEXT:    add a2, a3, a2
; RV32M-NEXT:    srli a3, a2, 4
; RV32M-NEXT:    add a2, a2, a3
; RV32M-NEXT:    and a2, a2, t6
; RV32M-NEXT:    mul a2, a2, t2
; RV32M-NEXT:    srli a2, a2, 24
; RV32M-NEXT:    addi a3, a2, 32
; RV32M-NEXT:    j .LBB0_15
; RV32M-NEXT:  .LBB0_14:
; RV32M-NEXT:    srli a2, s9, 1
; RV32M-NEXT:    or a2, s9, a2
; RV32M-NEXT:    srli a3, a2, 2
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    srli a3, a2, 4
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    srli a3, a2, 8
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    srli a3, a2, 16
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    not a2, a2
; RV32M-NEXT:    srli a3, a2, 1
; RV32M-NEXT:    and a3, a3, s1
; RV32M-NEXT:    sub a2, a2, a3
; RV32M-NEXT:    and a3, a2, s0
; RV32M-NEXT:    srli a2, a2, 2
; RV32M-NEXT:    and a2, a2, s0
; RV32M-NEXT:    add a2, a3, a2
; RV32M-NEXT:    srli a3, a2, 4
; RV32M-NEXT:    add a2, a2, a3
; RV32M-NEXT:    and a2, a2, t6
; RV32M-NEXT:    mul a3, a2, t2
; RV32M-NEXT:    srli a3, a3, 24
; RV32M-NEXT:  .LBB0_15: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    lw a2, 72(sp) # 4-byte Folded Reload
; RV32M-NEXT:    or a2, a2, s5
; RV32M-NEXT:    sw a7, 64(sp) # 4-byte Folded Spill
; RV32M-NEXT:    or a5, a7, s6
; RV32M-NEXT:    or a6, s10, s7
; RV32M-NEXT:    or a7, s9, s8
; RV32M-NEXT:    sltu a4, a4, a1
; RV32M-NEXT:    addi s2, s2, -1
; RV32M-NEXT:    addi a1, a3, 64
; RV32M-NEXT:    or s3, s7, s8
; RV32M-NEXT:    sltu t0, a1, a3
; RV32M-NEXT:    snez a3, s3
; RV32M-NEXT:    addi a3, a3, -1
; RV32M-NEXT:    bnez s8, .LBB0_17
; RV32M-NEXT:  # %bb.16: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    srli t1, s7, 1
; RV32M-NEXT:    or t1, s7, t1
; RV32M-NEXT:    srli s4, t1, 2
; RV32M-NEXT:    or t1, t1, s4
; RV32M-NEXT:    srli s4, t1, 4
; RV32M-NEXT:    or t1, t1, s4
; RV32M-NEXT:    srli s4, t1, 8
; RV32M-NEXT:    or t1, t1, s4
; RV32M-NEXT:    srli s4, t1, 16
; RV32M-NEXT:    or t1, t1, s4
; RV32M-NEXT:    not t1, t1
; RV32M-NEXT:    srli s4, t1, 1
; RV32M-NEXT:    and s1, s4, s1
; RV32M-NEXT:    sub t1, t1, s1
; RV32M-NEXT:    and s1, t1, s0
; RV32M-NEXT:    srli t1, t1, 2
; RV32M-NEXT:    and t1, t1, s0
; RV32M-NEXT:    add t1, s1, t1
; RV32M-NEXT:    srli s0, t1, 4
; RV32M-NEXT:    add t1, t1, s0
; RV32M-NEXT:    and t1, t1, t6
; RV32M-NEXT:    mul t1, t1, t2
; RV32M-NEXT:    srli t1, t1, 24
; RV32M-NEXT:    addi t1, t1, 32
; RV32M-NEXT:    j .LBB0_18
; RV32M-NEXT:  .LBB0_17:
; RV32M-NEXT:    srli t1, s8, 1
; RV32M-NEXT:    or t1, s8, t1
; RV32M-NEXT:    srli s4, t1, 2
; RV32M-NEXT:    or t1, t1, s4
; RV32M-NEXT:    srli s4, t1, 4
; RV32M-NEXT:    or t1, t1, s4
; RV32M-NEXT:    srli s4, t1, 8
; RV32M-NEXT:    or t1, t1, s4
; RV32M-NEXT:    srli s4, t1, 16
; RV32M-NEXT:    or t1, t1, s4
; RV32M-NEXT:    not t1, t1
; RV32M-NEXT:    srli s4, t1, 1
; RV32M-NEXT:    and s1, s4, s1
; RV32M-NEXT:    sub t1, t1, s1
; RV32M-NEXT:    and s1, t1, s0
; RV32M-NEXT:    srli t1, t1, 2
; RV32M-NEXT:    and t1, t1, s0
; RV32M-NEXT:    add t1, s1, t1
; RV32M-NEXT:    srli s0, t1, 4
; RV32M-NEXT:    add t1, t1, s0
; RV32M-NEXT:    and t1, t1, t6
; RV32M-NEXT:    mul t1, t1, t2
; RV32M-NEXT:    srli t1, t1, 24
; RV32M-NEXT:  .LBB0_18: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    or a5, a2, a5
; RV32M-NEXT:    or a6, a6, a7
; RV32M-NEXT:    and a2, s2, a4
; RV32M-NEXT:    and a3, a3, t0
; RV32M-NEXT:    bnez s3, .LBB0_20
; RV32M-NEXT:  # %bb.19: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    mv t1, a1
; RV32M-NEXT:  .LBB0_20: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    seqz a1, a5
; RV32M-NEXT:    seqz a4, a6
; RV32M-NEXT:    sltu a6, a0, t1
; RV32M-NEXT:    sub a7, a2, a3
; RV32M-NEXT:    mv a5, a6
; RV32M-NEXT:    beq a2, a3, .LBB0_22
; RV32M-NEXT:  # %bb.21: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    sltu a5, a2, a3
; RV32M-NEXT:  .LBB0_22: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    sub a2, a7, a6
; RV32M-NEXT:    or a3, a1, a4
; RV32M-NEXT:    neg a1, a5
; RV32M-NEXT:    seqz s1, a5
; RV32M-NEXT:    addi s1, s1, -1
; RV32M-NEXT:    sub a0, a0, t1
; RV32M-NEXT:    or a5, a1, s1
; RV32M-NEXT:    xor a4, t3, t5
; RV32M-NEXT:    lw s3, 36(sp) # 4-byte Folded Reload
; RV32M-NEXT:    beqz a5, .LBB0_24
; RV32M-NEXT:  # %bb.23: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    snez a5, a5
; RV32M-NEXT:    j .LBB0_25
; RV32M-NEXT:  .LBB0_24:
; RV32M-NEXT:    snez a5, a2
; RV32M-NEXT:    sltiu a6, a0, 128
; RV32M-NEXT:    xori a6, a6, 1
; RV32M-NEXT:    or a5, a6, a5
; RV32M-NEXT:  .LBB0_25: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    sw t5, 44(sp) # 4-byte Folded Spill
; RV32M-NEXT:    srai a4, a4, 31
; RV32M-NEXT:    sw a4, 40(sp) # 4-byte Folded Spill
; RV32M-NEXT:    or a5, a3, a5
; RV32M-NEXT:    addi a4, a5, -1
; RV32M-NEXT:    and ra, a4, s8
; RV32M-NEXT:    and s11, a4, s7
; RV32M-NEXT:    and a3, a4, s9
; RV32M-NEXT:    and a4, a4, s10
; RV32M-NEXT:    sw t4, 76(sp) # 4-byte Folded Spill
; RV32M-NEXT:    bnez a5, .LBB0_36
; RV32M-NEXT:  # %bb.26: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    sw s5, 68(sp) # 4-byte Folded Spill
; RV32M-NEXT:    xori a5, a0, 127
; RV32M-NEXT:    or a5, a5, a1
; RV32M-NEXT:    or a6, a2, s1
; RV32M-NEXT:    or a5, a5, a6
; RV32M-NEXT:    beqz a5, .LBB0_36
; RV32M-NEXT:  # %bb.27: # %udiv-bb15
; RV32M-NEXT:    sw t3, 80(sp) # 4-byte Folded Spill
; RV32M-NEXT:    addi s11, a0, 1
; RV32M-NEXT:    li a3, 127
; RV32M-NEXT:    sub a0, a3, a0
; RV32M-NEXT:    sw zero, 184(sp)
; RV32M-NEXT:    sw zero, 188(sp)
; RV32M-NEXT:    sw zero, 192(sp)
; RV32M-NEXT:    sw zero, 196(sp)
; RV32M-NEXT:    sw s10, 200(sp)
; RV32M-NEXT:    sw s9, 204(sp)
; RV32M-NEXT:    sw s7, 208(sp)
; RV32M-NEXT:    sw s8, 212(sp)
; RV32M-NEXT:    addi a3, sp, 200
; RV32M-NEXT:    seqz ra, s11
; RV32M-NEXT:    srli a4, a0, 3
; RV32M-NEXT:    andi a5, a0, 31
; RV32M-NEXT:    add ra, a2, ra
; RV32M-NEXT:    andi a4, a4, 12
; RV32M-NEXT:    xori a2, a5, 31
; RV32M-NEXT:    or a5, s11, ra
; RV32M-NEXT:    sub a3, a3, a4
; RV32M-NEXT:    seqz s4, a5
; RV32M-NEXT:    lw a4, 0(a3)
; RV32M-NEXT:    lw a5, 4(a3)
; RV32M-NEXT:    lw a6, 8(a3)
; RV32M-NEXT:    lw a3, 12(a3)
; RV32M-NEXT:    add s4, a1, s4
; RV32M-NEXT:    sltu a1, s4, a1
; RV32M-NEXT:    or a7, s11, s4
; RV32M-NEXT:    add s1, s1, a1
; RV32M-NEXT:    or a1, ra, s1
; RV32M-NEXT:    srli t0, a6, 1
; RV32M-NEXT:    srli t1, a5, 1
; RV32M-NEXT:    or a7, a7, a1
; RV32M-NEXT:    srli a1, a4, 1
; RV32M-NEXT:    srl t0, t0, a2
; RV32M-NEXT:    srl t1, t1, a2
; RV32M-NEXT:    srl a2, a1, a2
; RV32M-NEXT:    sll a1, a3, a0
; RV32M-NEXT:    or a1, a1, t0
; RV32M-NEXT:    sll a3, a6, a0
; RV32M-NEXT:    sll a5, a5, a0
; RV32M-NEXT:    or s5, a3, t1
; RV32M-NEXT:    or t6, a5, a2
; RV32M-NEXT:    sll s0, a4, a0
; RV32M-NEXT:    li s2, 0
; RV32M-NEXT:    beqz a7, .LBB0_35
; RV32M-NEXT:  # %bb.28: # %udiv-preheader4
; RV32M-NEXT:    li a0, 0
; RV32M-NEXT:    li s3, 0
; RV32M-NEXT:    li a2, 0
; RV32M-NEXT:    sw zero, 168(sp)
; RV32M-NEXT:    sw zero, 172(sp)
; RV32M-NEXT:    sw zero, 176(sp)
; RV32M-NEXT:    sw zero, 180(sp)
; RV32M-NEXT:    sw s10, 152(sp)
; RV32M-NEXT:    sw s9, 156(sp)
; RV32M-NEXT:    sw s7, 160(sp)
; RV32M-NEXT:    sw s8, 164(sp)
; RV32M-NEXT:    srli a3, s11, 3
; RV32M-NEXT:    addi a4, sp, 152
; RV32M-NEXT:    andi a3, a3, 12
; RV32M-NEXT:    add a3, a4, a3
; RV32M-NEXT:    lw a4, 4(a3)
; RV32M-NEXT:    lw a5, 8(a3)
; RV32M-NEXT:    lw t0, 12(a3)
; RV32M-NEXT:    lw a3, 0(a3)
; RV32M-NEXT:    andi a6, s11, 31
; RV32M-NEXT:    xori a6, a6, 31
; RV32M-NEXT:    slli a7, t0, 1
; RV32M-NEXT:    slli t1, a5, 1
; RV32M-NEXT:    slli t2, a4, 1
; RV32M-NEXT:    sll a7, a7, a6
; RV32M-NEXT:    sll t1, t1, a6
; RV32M-NEXT:    sll t3, t2, a6
; RV32M-NEXT:    lw t4, 72(sp) # 4-byte Folded Reload
; RV32M-NEXT:    seqz a6, t4
; RV32M-NEXT:    srl a5, a5, s11
; RV32M-NEXT:    or a7, a5, a7
; RV32M-NEXT:    lw t2, 64(sp) # 4-byte Folded Reload
; RV32M-NEXT:    or a5, t4, t2
; RV32M-NEXT:    sub s7, t2, a6
; RV32M-NEXT:    seqz a5, a5
; RV32M-NEXT:    srl a4, a4, s11
; RV32M-NEXT:    or a6, a4, t1
; RV32M-NEXT:    lw a4, 68(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sub s8, a4, a5
; RV32M-NEXT:    sltu a4, a4, a5
; RV32M-NEXT:    sub s9, s6, a4
; RV32M-NEXT:    srl a3, a3, s11
; RV32M-NEXT:    srl t2, t0, s11
; RV32M-NEXT:    or a5, a3, t3
; RV32M-NEXT:    addi t4, t4, -1
; RV32M-NEXT:    sw t4, 60(sp) # 4-byte Folded Spill
; RV32M-NEXT:    j .LBB0_30
; RV32M-NEXT:  .LBB0_29: # %udiv-do-while3
; RV32M-NEXT:    # in Loop: Header=BB0_30 Depth=1
; RV32M-NEXT:    srli t3, s5, 31
; RV32M-NEXT:    slli a1, a1, 1
; RV32M-NEXT:    sub t0, t0, s10
; RV32M-NEXT:    srli s10, t6, 31
; RV32M-NEXT:    slli s5, s5, 1
; RV32M-NEXT:    or a1, a1, t3
; RV32M-NEXT:    srli t3, s0, 31
; RV32M-NEXT:    slli t6, t6, 1
; RV32M-NEXT:    slli s0, s0, 1
; RV32M-NEXT:    or s5, s5, s10
; RV32M-NEXT:    and s10, a7, s6
; RV32M-NEXT:    or t3, t6, t3
; RV32M-NEXT:    lw t4, 68(sp) # 4-byte Folded Reload
; RV32M-NEXT:    and t6, a7, t4
; RV32M-NEXT:    or s0, s2, s0
; RV32M-NEXT:    sub t4, t1, t6
; RV32M-NEXT:    sltu t1, t1, t6
; RV32M-NEXT:    or t6, s11, ra
; RV32M-NEXT:    sub s10, a6, s10
; RV32M-NEXT:    seqz t5, s11
; RV32M-NEXT:    addi s11, s11, -1
; RV32M-NEXT:    andi s2, a7, 1
; RV32M-NEXT:    sub a6, t0, a3
; RV32M-NEXT:    seqz a3, t6
; RV32M-NEXT:    sub ra, ra, t5
; RV32M-NEXT:    or t6, a0, t3
; RV32M-NEXT:    or s5, s3, s5
; RV32M-NEXT:    or a1, a2, a1
; RV32M-NEXT:    sub a7, t4, t2
; RV32M-NEXT:    sltu a0, t4, t2
; RV32M-NEXT:    sub a2, s10, t1
; RV32M-NEXT:    sltu t0, s4, a3
; RV32M-NEXT:    sub s4, s4, a3
; RV32M-NEXT:    sub t2, a2, a0
; RV32M-NEXT:    sub s1, s1, t0
; RV32M-NEXT:    or a0, ra, s1
; RV32M-NEXT:    or a2, s11, s4
; RV32M-NEXT:    or a3, a2, a0
; RV32M-NEXT:    sub a5, a5, a4
; RV32M-NEXT:    li a0, 0
; RV32M-NEXT:    li s3, 0
; RV32M-NEXT:    li a2, 0
; RV32M-NEXT:    beqz a3, .LBB0_35
; RV32M-NEXT:  .LBB0_30: # %udiv-do-while3
; RV32M-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32M-NEXT:    srli a3, a5, 31
; RV32M-NEXT:    slli a4, a6, 1
; RV32M-NEXT:    slli a5, a5, 1
; RV32M-NEXT:    or t0, a4, a3
; RV32M-NEXT:    srli a3, a1, 31
; RV32M-NEXT:    or a5, a5, a3
; RV32M-NEXT:    beq s7, t0, .LBB0_32
; RV32M-NEXT:  # %bb.31: # %udiv-do-while3
; RV32M-NEXT:    # in Loop: Header=BB0_30 Depth=1
; RV32M-NEXT:    sltu a3, s7, t0
; RV32M-NEXT:    j .LBB0_33
; RV32M-NEXT:  .LBB0_32: # in Loop: Header=BB0_30 Depth=1
; RV32M-NEXT:    lw a3, 60(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sltu a3, a3, a5
; RV32M-NEXT:  .LBB0_33: # %udiv-do-while3
; RV32M-NEXT:    # in Loop: Header=BB0_30 Depth=1
; RV32M-NEXT:    srli a4, a7, 31
; RV32M-NEXT:    slli t2, t2, 1
; RV32M-NEXT:    srli t1, a6, 31
; RV32M-NEXT:    slli a7, a7, 1
; RV32M-NEXT:    or a6, t2, a4
; RV32M-NEXT:    or t1, a7, t1
; RV32M-NEXT:    sub a4, s8, t1
; RV32M-NEXT:    sltu a7, s8, t1
; RV32M-NEXT:    sub t2, s9, a6
; RV32M-NEXT:    sltu a3, a4, a3
; RV32M-NEXT:    sub a4, t2, a7
; RV32M-NEXT:    sub a4, a4, a3
; RV32M-NEXT:    srai a7, a4, 31
; RV32M-NEXT:    lw a3, 72(sp) # 4-byte Folded Reload
; RV32M-NEXT:    and a4, a7, a3
; RV32M-NEXT:    lw a3, 64(sp) # 4-byte Folded Reload
; RV32M-NEXT:    and s10, a7, a3
; RV32M-NEXT:    sltu a3, a5, a4
; RV32M-NEXT:    mv t2, a3
; RV32M-NEXT:    beq t0, s10, .LBB0_29
; RV32M-NEXT:  # %bb.34: # %udiv-do-while3
; RV32M-NEXT:    # in Loop: Header=BB0_30 Depth=1
; RV32M-NEXT:    sltu t2, t0, s10
; RV32M-NEXT:    j .LBB0_29
; RV32M-NEXT:  .LBB0_35: # %udiv-loop-exit2
; RV32M-NEXT:    srli a0, s0, 31
; RV32M-NEXT:    slli a3, t6, 1
; RV32M-NEXT:    srli a2, t6, 31
; RV32M-NEXT:    or a3, a3, a0
; RV32M-NEXT:    slli a0, s5, 1
; RV32M-NEXT:    srli a4, s5, 31
; RV32M-NEXT:    slli a1, a1, 1
; RV32M-NEXT:    slli s0, s0, 1
; RV32M-NEXT:    or s11, a0, a2
; RV32M-NEXT:    or ra, a1, a4
; RV32M-NEXT:    or a4, s2, s0
; RV32M-NEXT:    lw s3, 36(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw t3, 80(sp) # 4-byte Folded Reload
; RV32M-NEXT:  .LBB0_36: # %udiv-end1
; RV32M-NEXT:    lw s4, 40(sp) # 4-byte Folded Reload
; RV32M-NEXT:    xor a0, a4, s4
; RV32M-NEXT:    sw a0, 64(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sltu s5, a0, s4
; RV32M-NEXT:    xor a1, a3, s4
; RV32M-NEXT:    sw s5, 60(sp) # 4-byte Folded Spill
; RV32M-NEXT:    lw a6, 84(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw t6, 76(sp) # 4-byte Folded Reload
; RV32M-NEXT:    beqz a3, .LBB0_38
; RV32M-NEXT:  # %bb.37: # %udiv-end1
; RV32M-NEXT:    sltu s5, a1, s4
; RV32M-NEXT:  .LBB0_38: # %udiv-end1
; RV32M-NEXT:    lw s6, 56(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s8, 52(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s10, 48(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw a0, 44(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sw a1, 24(sp) # 4-byte Folded Spill
; RV32M-NEXT:    bltz a0, .LBB0_40
; RV32M-NEXT:  # %bb.39: # %udiv-end1
; RV32M-NEXT:    mv s9, a0
; RV32M-NEXT:    bltz t3, .LBB0_41
; RV32M-NEXT:    j .LBB0_42
; RV32M-NEXT:  .LBB0_40:
; RV32M-NEXT:    neg a0, s10
; RV32M-NEXT:    lw a1, 12(sp) # 4-byte Folded Reload
; RV32M-NEXT:    neg a1, a1
; RV32M-NEXT:    lw a2, 16(sp) # 4-byte Folded Reload
; RV32M-NEXT:    add a2, s8, a2
; RV32M-NEXT:    lw a4, 20(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sltu a3, a0, a4
; RV32M-NEXT:    sub s10, a0, a4
; RV32M-NEXT:    neg s8, a2
; RV32M-NEXT:    sub s9, a1, a3
; RV32M-NEXT:    neg s6, s6
; RV32M-NEXT:    bgez t3, .LBB0_42
; RV32M-NEXT:  .LBB0_41:
; RV32M-NEXT:    neg a0, a6
; RV32M-NEXT:    lw a1, 0(sp) # 4-byte Folded Reload
; RV32M-NEXT:    neg a1, a1
; RV32M-NEXT:    lw a2, 4(sp) # 4-byte Folded Reload
; RV32M-NEXT:    add a2, t6, a2
; RV32M-NEXT:    lw a4, 8(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sltu a3, a0, a4
; RV32M-NEXT:    sub a6, a0, a4
; RV32M-NEXT:    neg t6, a2
; RV32M-NEXT:    sub t3, a1, a3
; RV32M-NEXT:    neg s3, s3
; RV32M-NEXT:  .LBB0_42: # %udiv-end1
; RV32M-NEXT:    lui a0, 349525
; RV32M-NEXT:    lui a1, 209715
; RV32M-NEXT:    lui a2, 61681
; RV32M-NEXT:    lui a3, 4112
; RV32M-NEXT:    addi s2, a0, 1365
; RV32M-NEXT:    addi s1, a1, 819
; RV32M-NEXT:    addi s0, a2, -241
; RV32M-NEXT:    addi a1, a3, 257
; RV32M-NEXT:    bnez t6, .LBB0_45
; RV32M-NEXT:  # %bb.43: # %udiv-end1
; RV32M-NEXT:    srli a0, s3, 1
; RV32M-NEXT:    or a0, s3, a0
; RV32M-NEXT:    srli a2, a0, 2
; RV32M-NEXT:    or a0, a0, a2
; RV32M-NEXT:    srli a2, a0, 4
; RV32M-NEXT:    or a0, a0, a2
; RV32M-NEXT:    srli a2, a0, 8
; RV32M-NEXT:    or a0, a0, a2
; RV32M-NEXT:    srli a2, a0, 16
; RV32M-NEXT:    or a0, a0, a2
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a2, a0, 1
; RV32M-NEXT:    and a2, a2, s2
; RV32M-NEXT:    sub a0, a0, a2
; RV32M-NEXT:    and a2, a0, s1
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, s1
; RV32M-NEXT:    add a0, a2, a0
; RV32M-NEXT:    srli a2, a0, 4
; RV32M-NEXT:    add a0, a0, a2
; RV32M-NEXT:    and a0, a0, s0
; RV32M-NEXT:    mul a0, a0, a1
; RV32M-NEXT:    srli a0, a0, 24
; RV32M-NEXT:    addi a2, a0, 32
; RV32M-NEXT:    or a4, a6, t3
; RV32M-NEXT:    beqz t3, .LBB0_46
; RV32M-NEXT:  .LBB0_44:
; RV32M-NEXT:    srli a0, t3, 1
; RV32M-NEXT:    or a0, t3, a0
; RV32M-NEXT:    srli a3, a0, 2
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    srli a3, a0, 4
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    srli a3, a0, 8
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    srli a3, a0, 16
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a3, a0, 1
; RV32M-NEXT:    and a3, a3, s2
; RV32M-NEXT:    sub a0, a0, a3
; RV32M-NEXT:    and a3, a0, s1
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, s1
; RV32M-NEXT:    add a0, a3, a0
; RV32M-NEXT:    srli a3, a0, 4
; RV32M-NEXT:    add a0, a0, a3
; RV32M-NEXT:    and a0, a0, s0
; RV32M-NEXT:    mul a0, a0, a1
; RV32M-NEXT:    srli a0, a0, 24
; RV32M-NEXT:    addi a5, a2, 64
; RV32M-NEXT:    beqz a4, .LBB0_47
; RV32M-NEXT:    j .LBB0_48
; RV32M-NEXT:  .LBB0_45:
; RV32M-NEXT:    srli a0, t6, 1
; RV32M-NEXT:    or a0, t6, a0
; RV32M-NEXT:    srli a2, a0, 2
; RV32M-NEXT:    or a0, a0, a2
; RV32M-NEXT:    srli a2, a0, 4
; RV32M-NEXT:    or a0, a0, a2
; RV32M-NEXT:    srli a2, a0, 8
; RV32M-NEXT:    or a0, a0, a2
; RV32M-NEXT:    srli a2, a0, 16
; RV32M-NEXT:    or a0, a0, a2
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a2, a0, 1
; RV32M-NEXT:    and a2, a2, s2
; RV32M-NEXT:    sub a0, a0, a2
; RV32M-NEXT:    and a2, a0, s1
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, s1
; RV32M-NEXT:    add a0, a2, a0
; RV32M-NEXT:    srli a2, a0, 4
; RV32M-NEXT:    add a0, a0, a2
; RV32M-NEXT:    and a0, a0, s0
; RV32M-NEXT:    mul a2, a0, a1
; RV32M-NEXT:    srli a2, a2, 24
; RV32M-NEXT:    or a4, a6, t3
; RV32M-NEXT:    bnez t3, .LBB0_44
; RV32M-NEXT:  .LBB0_46: # %udiv-end1
; RV32M-NEXT:    srli a0, a6, 1
; RV32M-NEXT:    or a0, a6, a0
; RV32M-NEXT:    srli a3, a0, 2
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    srli a3, a0, 4
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    srli a3, a0, 8
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    srli a3, a0, 16
; RV32M-NEXT:    or a0, a0, a3
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a3, a0, 1
; RV32M-NEXT:    and a3, a3, s2
; RV32M-NEXT:    sub a0, a0, a3
; RV32M-NEXT:    and a3, a0, s1
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, s1
; RV32M-NEXT:    add a0, a3, a0
; RV32M-NEXT:    srli a3, a0, 4
; RV32M-NEXT:    add a0, a0, a3
; RV32M-NEXT:    and a0, a0, s0
; RV32M-NEXT:    mul a0, a0, a1
; RV32M-NEXT:    srli a0, a0, 24
; RV32M-NEXT:    addi a0, a0, 32
; RV32M-NEXT:    addi a5, a2, 64
; RV32M-NEXT:    bnez a4, .LBB0_48
; RV32M-NEXT:  .LBB0_47: # %udiv-end1
; RV32M-NEXT:    mv a0, a5
; RV32M-NEXT:  .LBB0_48: # %udiv-end1
; RV32M-NEXT:    snez t0, a4
; RV32M-NEXT:    bnez s8, .LBB0_50
; RV32M-NEXT:  # %bb.49: # %udiv-end1
; RV32M-NEXT:    srli a3, s6, 1
; RV32M-NEXT:    or a3, s6, a3
; RV32M-NEXT:    srli a4, a3, 2
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    srli a4, a3, 4
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    srli a4, a3, 8
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    srli a4, a3, 16
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    not a3, a3
; RV32M-NEXT:    srli a4, a3, 1
; RV32M-NEXT:    and a4, a4, s2
; RV32M-NEXT:    sub a3, a3, a4
; RV32M-NEXT:    and a4, a3, s1
; RV32M-NEXT:    srli a3, a3, 2
; RV32M-NEXT:    and a3, a3, s1
; RV32M-NEXT:    add a3, a4, a3
; RV32M-NEXT:    srli a4, a3, 4
; RV32M-NEXT:    add a3, a3, a4
; RV32M-NEXT:    and a3, a3, s0
; RV32M-NEXT:    mul a3, a3, a1
; RV32M-NEXT:    srli a3, a3, 24
; RV32M-NEXT:    addi a3, a3, 32
; RV32M-NEXT:    j .LBB0_51
; RV32M-NEXT:  .LBB0_50:
; RV32M-NEXT:    srli a3, s8, 1
; RV32M-NEXT:    or a3, s8, a3
; RV32M-NEXT:    srli a4, a3, 2
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    srli a4, a3, 4
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    srli a4, a3, 8
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    srli a4, a3, 16
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    not a3, a3
; RV32M-NEXT:    srli a4, a3, 1
; RV32M-NEXT:    and a4, a4, s2
; RV32M-NEXT:    sub a3, a3, a4
; RV32M-NEXT:    and a4, a3, s1
; RV32M-NEXT:    srli a3, a3, 2
; RV32M-NEXT:    and a3, a3, s1
; RV32M-NEXT:    add a3, a4, a3
; RV32M-NEXT:    srli a4, a3, 4
; RV32M-NEXT:    add a3, a3, a4
; RV32M-NEXT:    and a3, a3, s0
; RV32M-NEXT:    mul a3, a3, a1
; RV32M-NEXT:    srli a3, a3, 24
; RV32M-NEXT:  .LBB0_51: # %udiv-end1
; RV32M-NEXT:    sw a6, 84(sp) # 4-byte Folded Spill
; RV32M-NEXT:    or a4, s3, a6
; RV32M-NEXT:    sw t3, 80(sp) # 4-byte Folded Spill
; RV32M-NEXT:    or a6, t6, t3
; RV32M-NEXT:    or a7, s6, s10
; RV32M-NEXT:    or t2, s8, s9
; RV32M-NEXT:    sltu a5, a5, a2
; RV32M-NEXT:    addi t0, t0, -1
; RV32M-NEXT:    addi a2, a3, 64
; RV32M-NEXT:    or t3, s10, s9
; RV32M-NEXT:    sltu t4, a2, a3
; RV32M-NEXT:    snez a3, t3
; RV32M-NEXT:    addi a3, a3, -1
; RV32M-NEXT:    bnez s9, .LBB0_53
; RV32M-NEXT:  # %bb.52: # %udiv-end1
; RV32M-NEXT:    srli t1, s10, 1
; RV32M-NEXT:    or t1, s10, t1
; RV32M-NEXT:    srli t5, t1, 2
; RV32M-NEXT:    or t1, t1, t5
; RV32M-NEXT:    srli t5, t1, 4
; RV32M-NEXT:    or t1, t1, t5
; RV32M-NEXT:    srli t5, t1, 8
; RV32M-NEXT:    or t1, t1, t5
; RV32M-NEXT:    srli t5, t1, 16
; RV32M-NEXT:    or t1, t1, t5
; RV32M-NEXT:    not t1, t1
; RV32M-NEXT:    srli t5, t1, 1
; RV32M-NEXT:    and t5, t5, s2
; RV32M-NEXT:    sub t1, t1, t5
; RV32M-NEXT:    and t5, t1, s1
; RV32M-NEXT:    srli t1, t1, 2
; RV32M-NEXT:    and t1, t1, s1
; RV32M-NEXT:    add t1, t5, t1
; RV32M-NEXT:    srli t5, t1, 4
; RV32M-NEXT:    add t1, t1, t5
; RV32M-NEXT:    and t1, t1, s0
; RV32M-NEXT:    mul a1, t1, a1
; RV32M-NEXT:    srli a1, a1, 24
; RV32M-NEXT:    addi t1, a1, 32
; RV32M-NEXT:    j .LBB0_54
; RV32M-NEXT:  .LBB0_53:
; RV32M-NEXT:    srli t1, s9, 1
; RV32M-NEXT:    or t1, s9, t1
; RV32M-NEXT:    srli t5, t1, 2
; RV32M-NEXT:    or t1, t1, t5
; RV32M-NEXT:    srli t5, t1, 4
; RV32M-NEXT:    or t1, t1, t5
; RV32M-NEXT:    srli t5, t1, 8
; RV32M-NEXT:    or t1, t1, t5
; RV32M-NEXT:    srli t5, t1, 16
; RV32M-NEXT:    or t1, t1, t5
; RV32M-NEXT:    not t1, t1
; RV32M-NEXT:    srli t5, t1, 1
; RV32M-NEXT:    and t5, t5, s2
; RV32M-NEXT:    sub t1, t1, t5
; RV32M-NEXT:    and t5, t1, s1
; RV32M-NEXT:    srli t1, t1, 2
; RV32M-NEXT:    and t1, t1, s1
; RV32M-NEXT:    add t1, t5, t1
; RV32M-NEXT:    srli t5, t1, 4
; RV32M-NEXT:    add t1, t1, t5
; RV32M-NEXT:    and t1, t1, s0
; RV32M-NEXT:    mul a1, t1, a1
; RV32M-NEXT:    srli t1, a1, 24
; RV32M-NEXT:  .LBB0_54: # %udiv-end1
; RV32M-NEXT:    or a4, a4, a6
; RV32M-NEXT:    or a6, a7, t2
; RV32M-NEXT:    and a1, t0, a5
; RV32M-NEXT:    and a3, a3, t4
; RV32M-NEXT:    bnez t3, .LBB0_56
; RV32M-NEXT:  # %bb.55: # %udiv-end1
; RV32M-NEXT:    mv t1, a2
; RV32M-NEXT:  .LBB0_56: # %udiv-end1
; RV32M-NEXT:    seqz a4, a4
; RV32M-NEXT:    seqz a5, a6
; RV32M-NEXT:    sltu a6, a0, t1
; RV32M-NEXT:    sub t0, a1, a3
; RV32M-NEXT:    mv a7, a6
; RV32M-NEXT:    beq a1, a3, .LBB0_58
; RV32M-NEXT:  # %bb.57: # %udiv-end1
; RV32M-NEXT:    sltu a7, a1, a3
; RV32M-NEXT:  .LBB0_58: # %udiv-end1
; RV32M-NEXT:    xor a2, ra, s4
; RV32M-NEXT:    xor a3, s11, s4
; RV32M-NEXT:    sub s0, t0, a6
; RV32M-NEXT:    or a4, a4, a5
; RV32M-NEXT:    neg a1, a7
; RV32M-NEXT:    seqz s7, a7
; RV32M-NEXT:    addi s7, s7, -1
; RV32M-NEXT:    or a5, a1, s7
; RV32M-NEXT:    sub a0, a0, t1
; RV32M-NEXT:    beqz a5, .LBB0_60
; RV32M-NEXT:  # %bb.59: # %udiv-end1
; RV32M-NEXT:    snez a5, a5
; RV32M-NEXT:    j .LBB0_61
; RV32M-NEXT:  .LBB0_60:
; RV32M-NEXT:    snez a5, s0
; RV32M-NEXT:    sltiu a6, a0, 128
; RV32M-NEXT:    xori a6, a6, 1
; RV32M-NEXT:    or a5, a6, a5
; RV32M-NEXT:  .LBB0_61: # %udiv-end1
; RV32M-NEXT:    sub s11, a3, s4
; RV32M-NEXT:    sltu t1, a3, s4
; RV32M-NEXT:    sub t2, a2, s4
; RV32M-NEXT:    or a5, a4, a5
; RV32M-NEXT:    addi a2, a5, -1
; RV32M-NEXT:    and a7, a2, s9
; RV32M-NEXT:    and t0, a2, s10
; RV32M-NEXT:    and a4, a2, s8
; RV32M-NEXT:    and a6, a2, s6
; RV32M-NEXT:    sw t6, 76(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s9, 68(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s5, 36(sp) # 4-byte Folded Spill
; RV32M-NEXT:    bnez a5, .LBB0_73
; RV32M-NEXT:  # %bb.62: # %udiv-end1
; RV32M-NEXT:    xori a2, a0, 127
; RV32M-NEXT:    or a2, a2, a1
; RV32M-NEXT:    or a3, s0, s7
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    beqz a2, .LBB0_73
; RV32M-NEXT:  # %bb.63: # %udiv-bb1
; RV32M-NEXT:    sw t2, 12(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw t1, 16(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s11, 20(sp) # 4-byte Folded Spill
; RV32M-NEXT:    addi s4, a0, 1
; RV32M-NEXT:    li a2, 127
; RV32M-NEXT:    sub a2, a2, a0
; RV32M-NEXT:    sw zero, 120(sp)
; RV32M-NEXT:    sw zero, 124(sp)
; RV32M-NEXT:    sw zero, 128(sp)
; RV32M-NEXT:    sw zero, 132(sp)
; RV32M-NEXT:    sw s6, 136(sp)
; RV32M-NEXT:    sw s8, 140(sp)
; RV32M-NEXT:    sw s10, 144(sp)
; RV32M-NEXT:    lw t3, 68(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sw t3, 148(sp)
; RV32M-NEXT:    addi a0, sp, 136
; RV32M-NEXT:    seqz a3, s4
; RV32M-NEXT:    srli a4, a2, 3
; RV32M-NEXT:    andi a5, a2, 31
; RV32M-NEXT:    add s0, s0, a3
; RV32M-NEXT:    andi a4, a4, 12
; RV32M-NEXT:    xori a3, a5, 31
; RV32M-NEXT:    or a5, s4, s0
; RV32M-NEXT:    sub a0, a0, a4
; RV32M-NEXT:    seqz s9, a5
; RV32M-NEXT:    lw a4, 0(a0)
; RV32M-NEXT:    lw a5, 4(a0)
; RV32M-NEXT:    lw a6, 8(a0)
; RV32M-NEXT:    lw a0, 12(a0)
; RV32M-NEXT:    add s9, a1, s9
; RV32M-NEXT:    sltu a1, s9, a1
; RV32M-NEXT:    or a7, s4, s9
; RV32M-NEXT:    add s7, s7, a1
; RV32M-NEXT:    or a1, s0, s7
; RV32M-NEXT:    srli t0, a6, 1
; RV32M-NEXT:    srli t1, a5, 1
; RV32M-NEXT:    or a7, a7, a1
; RV32M-NEXT:    srli a1, a4, 1
; RV32M-NEXT:    srl t0, t0, a3
; RV32M-NEXT:    srl t1, t1, a3
; RV32M-NEXT:    srl a1, a1, a3
; RV32M-NEXT:    sll a0, a0, a2
; RV32M-NEXT:    or a0, a0, t0
; RV32M-NEXT:    sll a3, a6, a2
; RV32M-NEXT:    sll a5, a5, a2
; RV32M-NEXT:    mv a6, s10
; RV32M-NEXT:    or s10, a3, t1
; RV32M-NEXT:    or a1, a5, a1
; RV32M-NEXT:    sll s5, a4, a2
; RV32M-NEXT:    sw s6, 56(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s8, 52(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw a6, 48(sp) # 4-byte Folded Spill
; RV32M-NEXT:    beqz a7, .LBB0_71
; RV32M-NEXT:  # %bb.64: # %udiv-preheader
; RV32M-NEXT:    mv t2, s8
; RV32M-NEXT:    li s8, 0
; RV32M-NEXT:    li s11, 0
; RV32M-NEXT:    li ra, 0
; RV32M-NEXT:    li a2, 0
; RV32M-NEXT:    sw zero, 104(sp)
; RV32M-NEXT:    sw zero, 108(sp)
; RV32M-NEXT:    sw zero, 112(sp)
; RV32M-NEXT:    sw zero, 116(sp)
; RV32M-NEXT:    sw s6, 88(sp)
; RV32M-NEXT:    sw t2, 92(sp)
; RV32M-NEXT:    sw a6, 96(sp)
; RV32M-NEXT:    sw t3, 100(sp)
; RV32M-NEXT:    srli a3, s4, 3
; RV32M-NEXT:    addi a4, sp, 88
; RV32M-NEXT:    andi a3, a3, 12
; RV32M-NEXT:    add a3, a4, a3
; RV32M-NEXT:    lw a4, 4(a3)
; RV32M-NEXT:    lw a5, 8(a3)
; RV32M-NEXT:    lw a7, 12(a3)
; RV32M-NEXT:    lw a3, 0(a3)
; RV32M-NEXT:    andi a6, s4, 31
; RV32M-NEXT:    xori a6, a6, 31
; RV32M-NEXT:    slli t0, a7, 1
; RV32M-NEXT:    slli t1, a5, 1
; RV32M-NEXT:    slli t2, a4, 1
; RV32M-NEXT:    sll t0, t0, a6
; RV32M-NEXT:    sll t1, t1, a6
; RV32M-NEXT:    sll t6, t2, a6
; RV32M-NEXT:    seqz a6, s3
; RV32M-NEXT:    srl a5, a5, s4
; RV32M-NEXT:    or t5, a5, t0
; RV32M-NEXT:    lw t0, 76(sp) # 4-byte Folded Reload
; RV32M-NEXT:    or a5, s3, t0
; RV32M-NEXT:    sub s6, t0, a6
; RV32M-NEXT:    seqz a5, a5
; RV32M-NEXT:    srl a4, a4, s4
; RV32M-NEXT:    or a6, a4, t1
; RV32M-NEXT:    lw a4, 84(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sub t3, a4, a5
; RV32M-NEXT:    sltu a4, a4, a5
; RV32M-NEXT:    lw a5, 80(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sub t4, a5, a4
; RV32M-NEXT:    srl a3, a3, s4
; RV32M-NEXT:    srl t2, a7, s4
; RV32M-NEXT:    or a5, a3, t6
; RV32M-NEXT:    addi a3, s3, -1
; RV32M-NEXT:    sw a3, 72(sp) # 4-byte Folded Spill
; RV32M-NEXT:    j .LBB0_66
; RV32M-NEXT:  .LBB0_65: # %udiv-do-while
; RV32M-NEXT:    # in Loop: Header=BB0_66 Depth=1
; RV32M-NEXT:    srli s3, s10, 31
; RV32M-NEXT:    slli a0, a0, 1
; RV32M-NEXT:    sub t0, t0, s2
; RV32M-NEXT:    srli s2, a1, 31
; RV32M-NEXT:    slli s10, s10, 1
; RV32M-NEXT:    or a0, a0, s3
; RV32M-NEXT:    srli s3, s5, 31
; RV32M-NEXT:    slli a1, a1, 1
; RV32M-NEXT:    slli s5, s5, 1
; RV32M-NEXT:    or s2, s10, s2
; RV32M-NEXT:    lw t6, 80(sp) # 4-byte Folded Reload
; RV32M-NEXT:    and s10, t5, t6
; RV32M-NEXT:    or a1, a1, s3
; RV32M-NEXT:    lw t6, 84(sp) # 4-byte Folded Reload
; RV32M-NEXT:    and s3, t5, t6
; RV32M-NEXT:    or s5, s8, s5
; RV32M-NEXT:    sub s1, t1, s3
; RV32M-NEXT:    sltu t1, t1, s3
; RV32M-NEXT:    or s3, s4, s0
; RV32M-NEXT:    sub t6, a6, s10
; RV32M-NEXT:    seqz s10, s4
; RV32M-NEXT:    addi s4, s4, -1
; RV32M-NEXT:    andi s8, t5, 1
; RV32M-NEXT:    sub a6, t0, a3
; RV32M-NEXT:    seqz a3, s3
; RV32M-NEXT:    sub s0, s0, s10
; RV32M-NEXT:    or a1, s11, a1
; RV32M-NEXT:    or s10, ra, s2
; RV32M-NEXT:    or a0, a2, a0
; RV32M-NEXT:    sub t5, s1, t2
; RV32M-NEXT:    sltu a2, s1, t2
; RV32M-NEXT:    sub t0, t6, t1
; RV32M-NEXT:    sltu t1, s9, a3
; RV32M-NEXT:    sub s9, s9, a3
; RV32M-NEXT:    sub t2, t0, a2
; RV32M-NEXT:    sub s7, s7, t1
; RV32M-NEXT:    or a2, s0, s7
; RV32M-NEXT:    or a3, s4, s9
; RV32M-NEXT:    or a3, a3, a2
; RV32M-NEXT:    sub a5, a5, a4
; RV32M-NEXT:    li s11, 0
; RV32M-NEXT:    li ra, 0
; RV32M-NEXT:    li a2, 0
; RV32M-NEXT:    mv s3, a7
; RV32M-NEXT:    beqz a3, .LBB0_72
; RV32M-NEXT:  .LBB0_66: # %udiv-do-while
; RV32M-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32M-NEXT:    srli a3, a5, 31
; RV32M-NEXT:    slli a4, a6, 1
; RV32M-NEXT:    slli a5, a5, 1
; RV32M-NEXT:    or t0, a4, a3
; RV32M-NEXT:    srli a3, a0, 31
; RV32M-NEXT:    or a5, a5, a3
; RV32M-NEXT:    beq s6, t0, .LBB0_68
; RV32M-NEXT:  # %bb.67: # %udiv-do-while
; RV32M-NEXT:    # in Loop: Header=BB0_66 Depth=1
; RV32M-NEXT:    sltu a3, s6, t0
; RV32M-NEXT:    j .LBB0_69
; RV32M-NEXT:  .LBB0_68: # in Loop: Header=BB0_66 Depth=1
; RV32M-NEXT:    lw a3, 72(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sltu a3, a3, a5
; RV32M-NEXT:  .LBB0_69: # %udiv-do-while
; RV32M-NEXT:    # in Loop: Header=BB0_66 Depth=1
; RV32M-NEXT:    srli a4, t5, 31
; RV32M-NEXT:    slli t2, t2, 1
; RV32M-NEXT:    srli t1, a6, 31
; RV32M-NEXT:    slli t5, t5, 1
; RV32M-NEXT:    or a6, t2, a4
; RV32M-NEXT:    or t1, t5, t1
; RV32M-NEXT:    sub a4, t3, t1
; RV32M-NEXT:    sltu t2, t3, t1
; RV32M-NEXT:    sub t5, t4, a6
; RV32M-NEXT:    sltu a3, a4, a3
; RV32M-NEXT:    sub a4, t5, t2
; RV32M-NEXT:    sub a4, a4, a3
; RV32M-NEXT:    srai t5, a4, 31
; RV32M-NEXT:    mv a7, s3
; RV32M-NEXT:    and a4, t5, s3
; RV32M-NEXT:    lw a3, 76(sp) # 4-byte Folded Reload
; RV32M-NEXT:    and s2, t5, a3
; RV32M-NEXT:    sltu a3, a5, a4
; RV32M-NEXT:    mv t2, a3
; RV32M-NEXT:    beq t0, s2, .LBB0_65
; RV32M-NEXT:  # %bb.70: # %udiv-do-while
; RV32M-NEXT:    # in Loop: Header=BB0_66 Depth=1
; RV32M-NEXT:    sltu t2, t0, s2
; RV32M-NEXT:    j .LBB0_65
; RV32M-NEXT:  .LBB0_71:
; RV32M-NEXT:    li s8, 0
; RV32M-NEXT:  .LBB0_72: # %udiv-loop-exit
; RV32M-NEXT:    srli a2, s5, 31
; RV32M-NEXT:    slli a4, a1, 1
; RV32M-NEXT:    srli a1, a1, 31
; RV32M-NEXT:    or a4, a4, a2
; RV32M-NEXT:    slli a2, s10, 1
; RV32M-NEXT:    srli a3, s10, 31
; RV32M-NEXT:    slli a0, a0, 1
; RV32M-NEXT:    slli s5, s5, 1
; RV32M-NEXT:    or t0, a2, a1
; RV32M-NEXT:    or a7, a0, a3
; RV32M-NEXT:    or a6, s8, s5
; RV32M-NEXT:    lw s6, 56(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s8, 52(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s10, 48(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s11, 20(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw t1, 16(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw t2, 12(sp) # 4-byte Folded Reload
; RV32M-NEXT:  .LBB0_73: # %udiv-end
; RV32M-NEXT:    lw s9, 36(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sltu a1, s11, s9
; RV32M-NEXT:    sub a2, t2, t1
; RV32M-NEXT:    lw s7, 40(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw a0, 24(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sub a5, a0, s7
; RV32M-NEXT:    lw a0, 44(sp) # 4-byte Folded Reload
; RV32M-NEXT:    srai a0, a0, 31
; RV32M-NEXT:    mulhu t1, s3, a6
; RV32M-NEXT:    lw s5, 76(sp) # 4-byte Folded Reload
; RV32M-NEXT:    mul t2, s5, a6
; RV32M-NEXT:    mulhu t3, s5, a6
; RV32M-NEXT:    mul t4, s3, a4
; RV32M-NEXT:    mulhu t5, s3, a4
; RV32M-NEXT:    mul t6, s5, a4
; RV32M-NEXT:    lw s4, 84(sp) # 4-byte Folded Reload
; RV32M-NEXT:    mul s0, a6, s4
; RV32M-NEXT:    mul s1, t0, s3
; RV32M-NEXT:    mulhu s2, s5, a4
; RV32M-NEXT:    mv a3, s3
; RV32M-NEXT:    mul s3, t0, s5
; RV32M-NEXT:    mulhu t0, t0, a3
; RV32M-NEXT:    mul a7, a7, a3
; RV32M-NEXT:    mul a4, a4, s4
; RV32M-NEXT:    mulhu s4, a6, s4
; RV32M-NEXT:    lw s5, 80(sp) # 4-byte Folded Reload
; RV32M-NEXT:    mul s5, a6, s5
; RV32M-NEXT:    mul a3, a3, a6
; RV32M-NEXT:    add a6, t2, t1
; RV32M-NEXT:    add s0, s1, s0
; RV32M-NEXT:    add t0, t0, s3
; RV32M-NEXT:    add s4, s4, s5
; RV32M-NEXT:    sltu t1, a6, t2
; RV32M-NEXT:    add a6, t4, a6
; RV32M-NEXT:    add a7, t0, a7
; RV32M-NEXT:    add a4, s4, a4
; RV32M-NEXT:    sltu t0, s0, s1
; RV32M-NEXT:    add t1, t3, t1
; RV32M-NEXT:    sltu t2, a6, t4
; RV32M-NEXT:    add a4, a7, a4
; RV32M-NEXT:    add t2, t5, t2
; RV32M-NEXT:    add a4, a4, t0
; RV32M-NEXT:    add t2, t1, t2
; RV32M-NEXT:    add a7, t6, t2
; RV32M-NEXT:    sltu t1, t2, t1
; RV32M-NEXT:    add t0, a7, s0
; RV32M-NEXT:    sltu t2, a7, t6
; RV32M-NEXT:    add t1, s2, t1
; RV32M-NEXT:    sltu a7, t0, a7
; RV32M-NEXT:    add t1, t1, t2
; RV32M-NEXT:    sltu t2, s10, t0
; RV32M-NEXT:    add a4, t1, a4
; RV32M-NEXT:    lw t1, 68(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sub a7, t1, a7
; RV32M-NEXT:    sub a4, a7, a4
; RV32M-NEXT:    sltu t1, s6, a3
; RV32M-NEXT:    sub a7, a4, t2
; RV32M-NEXT:    mv t2, t1
; RV32M-NEXT:    beq s8, a6, .LBB0_75
; RV32M-NEXT:  # %bb.74: # %udiv-end
; RV32M-NEXT:    sltu t2, s8, a6
; RV32M-NEXT:  .LBB0_75: # %udiv-end
; RV32M-NEXT:    sub a2, a2, a1
; RV32M-NEXT:    lw a1, 60(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sub a1, a5, a1
; RV32M-NEXT:    sub a4, s11, s9
; RV32M-NEXT:    lw a5, 64(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sub a5, a5, s7
; RV32M-NEXT:    sub t0, s10, t0
; RV32M-NEXT:    sub a6, s8, a6
; RV32M-NEXT:    sub a3, s6, a3
; RV32M-NEXT:    sltu t3, t0, t2
; RV32M-NEXT:    sub t0, t0, t2
; RV32M-NEXT:    sub t4, a6, t1
; RV32M-NEXT:    xor a3, a3, a0
; RV32M-NEXT:    sub t1, a7, t3
; RV32M-NEXT:    xor t2, t0, a0
; RV32M-NEXT:    xor a7, t4, a0
; RV32M-NEXT:    sltu a6, a3, a0
; RV32M-NEXT:    xor t0, t1, a0
; RV32M-NEXT:    sltu t1, t2, a0
; RV32M-NEXT:    add t1, a0, t1
; RV32M-NEXT:    sub t0, t0, t1
; RV32M-NEXT:    sub t1, t2, a0
; RV32M-NEXT:    mv t2, a6
; RV32M-NEXT:    beqz t4, .LBB0_77
; RV32M-NEXT:  # %bb.76: # %udiv-end
; RV32M-NEXT:    sltu t2, a7, a0
; RV32M-NEXT:  .LBB0_77: # %udiv-end
; RV32M-NEXT:    sltu t3, t1, t2
; RV32M-NEXT:    sub t1, t1, t2
; RV32M-NEXT:    sub a7, a7, a0
; RV32M-NEXT:    sub a3, a3, a0
; RV32M-NEXT:    lw a0, 28(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sw a5, 0(a0)
; RV32M-NEXT:    sw a1, 4(a0)
; RV32M-NEXT:    sw a4, 8(a0)
; RV32M-NEXT:    sw a2, 12(a0)
; RV32M-NEXT:    sub a0, t0, t3
; RV32M-NEXT:    sub a1, a7, a6
; RV32M-NEXT:    lw a2, 32(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sw a3, 0(a2)
; RV32M-NEXT:    sw a1, 4(a2)
; RV32M-NEXT:    sw t1, 8(a2)
; RV32M-NEXT:    sw a0, 12(a2)
; RV32M-NEXT:    lw ra, 268(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s0, 264(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s1, 260(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s2, 256(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s3, 252(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s4, 248(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s5, 244(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s6, 240(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s7, 236(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s8, 232(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s9, 228(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s10, 224(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s11, 220(sp) # 4-byte Folded Reload
; RV32M-NEXT:    .cfi_restore ra
; RV32M-NEXT:    .cfi_restore s0
; RV32M-NEXT:    .cfi_restore s1
; RV32M-NEXT:    .cfi_restore s2
; RV32M-NEXT:    .cfi_restore s3
; RV32M-NEXT:    .cfi_restore s4
; RV32M-NEXT:    .cfi_restore s5
; RV32M-NEXT:    .cfi_restore s6
; RV32M-NEXT:    .cfi_restore s7
; RV32M-NEXT:    .cfi_restore s8
; RV32M-NEXT:    .cfi_restore s9
; RV32M-NEXT:    .cfi_restore s10
; RV32M-NEXT:    .cfi_restore s11
; RV32M-NEXT:    addi sp, sp, 272
; RV32M-NEXT:    .cfi_def_cfa_offset 0
; RV32M-NEXT:    ret
  %q = sdiv i128 %n, %d
  %r = srem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}

define void @udivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; RV32I-LABEL: udivrem_i128:
; RV32I:       # %bb.0: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    addi sp, sp, -240
; RV32I-NEXT:    .cfi_def_cfa_offset 240
; RV32I-NEXT:    sw ra, 236(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s0, 232(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s1, 228(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s2, 224(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s3, 220(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s4, 216(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s5, 212(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s6, 208(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s7, 204(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s8, 200(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s9, 196(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s10, 192(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s11, 188(sp) # 4-byte Folded Spill
; RV32I-NEXT:    .cfi_offset ra, -4
; RV32I-NEXT:    .cfi_offset s0, -8
; RV32I-NEXT:    .cfi_offset s1, -12
; RV32I-NEXT:    .cfi_offset s2, -16
; RV32I-NEXT:    .cfi_offset s3, -20
; RV32I-NEXT:    .cfi_offset s4, -24
; RV32I-NEXT:    .cfi_offset s5, -28
; RV32I-NEXT:    .cfi_offset s6, -32
; RV32I-NEXT:    .cfi_offset s7, -36
; RV32I-NEXT:    .cfi_offset s8, -40
; RV32I-NEXT:    .cfi_offset s9, -44
; RV32I-NEXT:    .cfi_offset s10, -48
; RV32I-NEXT:    .cfi_offset s11, -52
; RV32I-NEXT:    mv a4, a2
; RV32I-NEXT:    sw a1, 24(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw a0, 20(sp) # 4-byte Folded Spill
; RV32I-NEXT:    lw s11, 0(a3)
; RV32I-NEXT:    lw s10, 4(a3)
; RV32I-NEXT:    lw s9, 8(a3)
; RV32I-NEXT:    lw ra, 12(a3)
; RV32I-NEXT:    lui a5, 349525
; RV32I-NEXT:    addi a5, a5, 1365
; RV32I-NEXT:    lui a1, 209715
; RV32I-NEXT:    addi a1, a1, 819
; RV32I-NEXT:    lui a0, 61681
; RV32I-NEXT:    addi a0, a0, -241
; RV32I-NEXT:    bnez s10, .LBB1_2
; RV32I-NEXT:  # %bb.1: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    srli a6, s11, 1
; RV32I-NEXT:    or a6, s11, a6
; RV32I-NEXT:    srli a7, a6, 2
; RV32I-NEXT:    or a6, a6, a7
; RV32I-NEXT:    srli a7, a6, 4
; RV32I-NEXT:    or a6, a6, a7
; RV32I-NEXT:    srli a7, a6, 8
; RV32I-NEXT:    or a6, a6, a7
; RV32I-NEXT:    srli a7, a6, 16
; RV32I-NEXT:    or a6, a6, a7
; RV32I-NEXT:    not a6, a6
; RV32I-NEXT:    srli a7, a6, 1
; RV32I-NEXT:    and a7, a7, a5
; RV32I-NEXT:    sub a6, a6, a7
; RV32I-NEXT:    and a7, a6, a1
; RV32I-NEXT:    srli a6, a6, 2
; RV32I-NEXT:    and a6, a6, a1
; RV32I-NEXT:    add a6, a7, a6
; RV32I-NEXT:    srli a7, a6, 4
; RV32I-NEXT:    add a6, a6, a7
; RV32I-NEXT:    and a6, a6, a0
; RV32I-NEXT:    slli a7, a6, 8
; RV32I-NEXT:    add a6, a6, a7
; RV32I-NEXT:    slli a7, a6, 16
; RV32I-NEXT:    add a6, a6, a7
; RV32I-NEXT:    srli a6, a6, 24
; RV32I-NEXT:    addi a7, a6, 32
; RV32I-NEXT:    j .LBB1_3
; RV32I-NEXT:  .LBB1_2:
; RV32I-NEXT:    srli a6, s10, 1
; RV32I-NEXT:    or a6, s10, a6
; RV32I-NEXT:    srli a7, a6, 2
; RV32I-NEXT:    or a6, a6, a7
; RV32I-NEXT:    srli a7, a6, 4
; RV32I-NEXT:    or a6, a6, a7
; RV32I-NEXT:    srli a7, a6, 8
; RV32I-NEXT:    or a6, a6, a7
; RV32I-NEXT:    srli a7, a6, 16
; RV32I-NEXT:    or a6, a6, a7
; RV32I-NEXT:    not a6, a6
; RV32I-NEXT:    srli a7, a6, 1
; RV32I-NEXT:    and a7, a7, a5
; RV32I-NEXT:    sub a6, a6, a7
; RV32I-NEXT:    and a7, a6, a1
; RV32I-NEXT:    srli a6, a6, 2
; RV32I-NEXT:    and a6, a6, a1
; RV32I-NEXT:    add a6, a7, a6
; RV32I-NEXT:    srli a7, a6, 4
; RV32I-NEXT:    add a6, a6, a7
; RV32I-NEXT:    and a6, a6, a0
; RV32I-NEXT:    slli a7, a6, 8
; RV32I-NEXT:    add a6, a6, a7
; RV32I-NEXT:    slli a7, a6, 16
; RV32I-NEXT:    add a6, a6, a7
; RV32I-NEXT:    srli a7, a6, 24
; RV32I-NEXT:  .LBB1_3: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    lw s3, 4(a4)
; RV32I-NEXT:    or t1, s9, ra
; RV32I-NEXT:    bnez ra, .LBB1_5
; RV32I-NEXT:  # %bb.4: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    srli a6, s9, 1
; RV32I-NEXT:    or a6, s9, a6
; RV32I-NEXT:    srli t0, a6, 2
; RV32I-NEXT:    or a6, a6, t0
; RV32I-NEXT:    srli t0, a6, 4
; RV32I-NEXT:    or a6, a6, t0
; RV32I-NEXT:    srli t0, a6, 8
; RV32I-NEXT:    or a6, a6, t0
; RV32I-NEXT:    srli t0, a6, 16
; RV32I-NEXT:    or a6, a6, t0
; RV32I-NEXT:    not a6, a6
; RV32I-NEXT:    srli t0, a6, 1
; RV32I-NEXT:    and t0, t0, a5
; RV32I-NEXT:    sub a6, a6, t0
; RV32I-NEXT:    and t0, a6, a1
; RV32I-NEXT:    srli a6, a6, 2
; RV32I-NEXT:    and a6, a6, a1
; RV32I-NEXT:    add a6, t0, a6
; RV32I-NEXT:    srli t0, a6, 4
; RV32I-NEXT:    add a6, a6, t0
; RV32I-NEXT:    and a6, a6, a0
; RV32I-NEXT:    slli t0, a6, 8
; RV32I-NEXT:    add a6, a6, t0
; RV32I-NEXT:    slli t0, a6, 16
; RV32I-NEXT:    add a6, a6, t0
; RV32I-NEXT:    srli a6, a6, 24
; RV32I-NEXT:    addi a6, a6, 32
; RV32I-NEXT:    j .LBB1_6
; RV32I-NEXT:  .LBB1_5:
; RV32I-NEXT:    srli a6, ra, 1
; RV32I-NEXT:    or a6, ra, a6
; RV32I-NEXT:    srli t0, a6, 2
; RV32I-NEXT:    or a6, a6, t0
; RV32I-NEXT:    srli t0, a6, 4
; RV32I-NEXT:    or a6, a6, t0
; RV32I-NEXT:    srli t0, a6, 8
; RV32I-NEXT:    or a6, a6, t0
; RV32I-NEXT:    srli t0, a6, 16
; RV32I-NEXT:    or a6, a6, t0
; RV32I-NEXT:    not a6, a6
; RV32I-NEXT:    srli t0, a6, 1
; RV32I-NEXT:    and t0, t0, a5
; RV32I-NEXT:    sub a6, a6, t0
; RV32I-NEXT:    and t0, a6, a1
; RV32I-NEXT:    srli a6, a6, 2
; RV32I-NEXT:    and a6, a6, a1
; RV32I-NEXT:    add a6, t0, a6
; RV32I-NEXT:    srli t0, a6, 4
; RV32I-NEXT:    add a6, a6, t0
; RV32I-NEXT:    and a6, a6, a0
; RV32I-NEXT:    slli t0, a6, 8
; RV32I-NEXT:    add a6, a6, t0
; RV32I-NEXT:    slli t0, a6, 16
; RV32I-NEXT:    add a6, a6, t0
; RV32I-NEXT:    srli a6, a6, 24
; RV32I-NEXT:  .LBB1_6: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    lw s5, 12(a4)
; RV32I-NEXT:    addi t0, a7, 64
; RV32I-NEXT:    bnez t1, .LBB1_8
; RV32I-NEXT:  # %bb.7: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    mv a6, t0
; RV32I-NEXT:  .LBB1_8: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    lw s2, 0(a4)
; RV32I-NEXT:    lw s6, 8(a4)
; RV32I-NEXT:    snez a4, t1
; RV32I-NEXT:    bnez s3, .LBB1_10
; RV32I-NEXT:  # %bb.9: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    srli t1, s2, 1
; RV32I-NEXT:    or t1, s2, t1
; RV32I-NEXT:    srli t2, t1, 2
; RV32I-NEXT:    or t1, t1, t2
; RV32I-NEXT:    srli t2, t1, 4
; RV32I-NEXT:    or t1, t1, t2
; RV32I-NEXT:    srli t2, t1, 8
; RV32I-NEXT:    or t1, t1, t2
; RV32I-NEXT:    srli t2, t1, 16
; RV32I-NEXT:    or t1, t1, t2
; RV32I-NEXT:    not t1, t1
; RV32I-NEXT:    srli t2, t1, 1
; RV32I-NEXT:    and t2, t2, a5
; RV32I-NEXT:    sub t1, t1, t2
; RV32I-NEXT:    and t2, t1, a1
; RV32I-NEXT:    srli t1, t1, 2
; RV32I-NEXT:    and t1, t1, a1
; RV32I-NEXT:    add t1, t2, t1
; RV32I-NEXT:    srli t2, t1, 4
; RV32I-NEXT:    add t1, t1, t2
; RV32I-NEXT:    and t1, t1, a0
; RV32I-NEXT:    slli t2, t1, 8
; RV32I-NEXT:    add t1, t1, t2
; RV32I-NEXT:    slli t2, t1, 16
; RV32I-NEXT:    add t1, t1, t2
; RV32I-NEXT:    srli t1, t1, 24
; RV32I-NEXT:    addi t6, t1, 32
; RV32I-NEXT:    j .LBB1_11
; RV32I-NEXT:  .LBB1_10:
; RV32I-NEXT:    srli t1, s3, 1
; RV32I-NEXT:    or t1, s3, t1
; RV32I-NEXT:    srli t2, t1, 2
; RV32I-NEXT:    or t1, t1, t2
; RV32I-NEXT:    srli t2, t1, 4
; RV32I-NEXT:    or t1, t1, t2
; RV32I-NEXT:    srli t2, t1, 8
; RV32I-NEXT:    or t1, t1, t2
; RV32I-NEXT:    srli t2, t1, 16
; RV32I-NEXT:    or t1, t1, t2
; RV32I-NEXT:    not t1, t1
; RV32I-NEXT:    srli t2, t1, 1
; RV32I-NEXT:    and t2, t2, a5
; RV32I-NEXT:    sub t1, t1, t2
; RV32I-NEXT:    and t2, t1, a1
; RV32I-NEXT:    srli t1, t1, 2
; RV32I-NEXT:    and t1, t1, a1
; RV32I-NEXT:    add t1, t2, t1
; RV32I-NEXT:    srli t2, t1, 4
; RV32I-NEXT:    add t1, t1, t2
; RV32I-NEXT:    and t1, t1, a0
; RV32I-NEXT:    slli t2, t1, 8
; RV32I-NEXT:    add t1, t1, t2
; RV32I-NEXT:    slli t2, t1, 16
; RV32I-NEXT:    add t1, t1, t2
; RV32I-NEXT:    srli t6, t1, 24
; RV32I-NEXT:  .LBB1_11: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    or t1, s10, ra
; RV32I-NEXT:    or t2, s11, s9
; RV32I-NEXT:    or t3, s3, s5
; RV32I-NEXT:    or t4, s2, s6
; RV32I-NEXT:    sltu a7, t0, a7
; RV32I-NEXT:    addi t0, a4, -1
; RV32I-NEXT:    addi a4, t6, 64
; RV32I-NEXT:    or t5, s6, s5
; RV32I-NEXT:    sltu t6, a4, t6
; RV32I-NEXT:    snez s4, t5
; RV32I-NEXT:    addi s4, s4, -1
; RV32I-NEXT:    bnez s5, .LBB1_13
; RV32I-NEXT:  # %bb.12: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    srli s0, s6, 1
; RV32I-NEXT:    or s0, s6, s0
; RV32I-NEXT:    srli s1, s0, 2
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    srli s1, s0, 4
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    srli s1, s0, 8
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    srli s1, s0, 16
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    not s0, s0
; RV32I-NEXT:    srli s1, s0, 1
; RV32I-NEXT:    and a5, s1, a5
; RV32I-NEXT:    sub s0, s0, a5
; RV32I-NEXT:    and a5, s0, a1
; RV32I-NEXT:    srli s0, s0, 2
; RV32I-NEXT:    and a1, s0, a1
; RV32I-NEXT:    add a1, a5, a1
; RV32I-NEXT:    srli a5, a1, 4
; RV32I-NEXT:    add a1, a1, a5
; RV32I-NEXT:    and a0, a1, a0
; RV32I-NEXT:    slli a1, a0, 8
; RV32I-NEXT:    add a0, a0, a1
; RV32I-NEXT:    slli a1, a0, 16
; RV32I-NEXT:    add a0, a0, a1
; RV32I-NEXT:    srli a0, a0, 24
; RV32I-NEXT:    addi a0, a0, 32
; RV32I-NEXT:    j .LBB1_14
; RV32I-NEXT:  .LBB1_13:
; RV32I-NEXT:    srli s0, s5, 1
; RV32I-NEXT:    or s0, s5, s0
; RV32I-NEXT:    srli s1, s0, 2
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    srli s1, s0, 4
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    srli s1, s0, 8
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    srli s1, s0, 16
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    not s0, s0
; RV32I-NEXT:    srli s1, s0, 1
; RV32I-NEXT:    and a5, s1, a5
; RV32I-NEXT:    sub s0, s0, a5
; RV32I-NEXT:    and a5, s0, a1
; RV32I-NEXT:    srli s0, s0, 2
; RV32I-NEXT:    and a1, s0, a1
; RV32I-NEXT:    add a1, a5, a1
; RV32I-NEXT:    srli a5, a1, 4
; RV32I-NEXT:    add a1, a1, a5
; RV32I-NEXT:    and a0, a1, a0
; RV32I-NEXT:    slli a1, a0, 8
; RV32I-NEXT:    add a0, a0, a1
; RV32I-NEXT:    slli a1, a0, 16
; RV32I-NEXT:    add a0, a0, a1
; RV32I-NEXT:    srli a0, a0, 24
; RV32I-NEXT:  .LBB1_14: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    or t1, t2, t1
; RV32I-NEXT:    or t2, t4, t3
; RV32I-NEXT:    and a1, t0, a7
; RV32I-NEXT:    and a5, s4, t6
; RV32I-NEXT:    bnez t5, .LBB1_16
; RV32I-NEXT:  # %bb.15: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    mv a0, a4
; RV32I-NEXT:  .LBB1_16: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    seqz a7, t1
; RV32I-NEXT:    seqz t0, t2
; RV32I-NEXT:    sltu a4, a6, a0
; RV32I-NEXT:    sub t2, a1, a5
; RV32I-NEXT:    mv t1, a4
; RV32I-NEXT:    beq a1, a5, .LBB1_18
; RV32I-NEXT:  # %bb.17: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    sltu t1, a1, a5
; RV32I-NEXT:  .LBB1_18: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    sub a4, t2, a4
; RV32I-NEXT:    or a1, a7, t0
; RV32I-NEXT:    neg a5, t1
; RV32I-NEXT:    seqz a7, t1
; RV32I-NEXT:    addi a7, a7, -1
; RV32I-NEXT:    or t0, a5, a7
; RV32I-NEXT:    sub a0, a6, a0
; RV32I-NEXT:    beqz t0, .LBB1_20
; RV32I-NEXT:  # %bb.19: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    snez a6, t0
; RV32I-NEXT:    j .LBB1_21
; RV32I-NEXT:  .LBB1_20:
; RV32I-NEXT:    snez a6, a4
; RV32I-NEXT:    sltiu t0, a0, 128
; RV32I-NEXT:    xori t0, t0, 1
; RV32I-NEXT:    or a6, t0, a6
; RV32I-NEXT:  .LBB1_21: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    li s8, 127
; RV32I-NEXT:    or a1, a1, a6
; RV32I-NEXT:    addi a6, a1, -1
; RV32I-NEXT:    and t1, a6, s5
; RV32I-NEXT:    and t2, a6, s6
; RV32I-NEXT:    and t0, a6, s3
; RV32I-NEXT:    and t3, a6, s2
; RV32I-NEXT:    sw s10, 52(sp) # 4-byte Folded Spill
; RV32I-NEXT:    mv a2, s11
; RV32I-NEXT:    sw s3, 28(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw ra, 48(sp) # 4-byte Folded Spill
; RV32I-NEXT:    mv a3, s9
; RV32I-NEXT:    sw s2, 40(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s5, 36(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s6, 32(sp) # 4-byte Folded Spill
; RV32I-NEXT:    bnez a1, .LBB1_32
; RV32I-NEXT:  # %bb.22: # %_udiv-special-cases_udiv-special-cases
; RV32I-NEXT:    xori a1, a0, 127
; RV32I-NEXT:    or a1, a1, a5
; RV32I-NEXT:    or a6, a4, a7
; RV32I-NEXT:    or a1, a1, a6
; RV32I-NEXT:    beqz a1, .LBB1_32
; RV32I-NEXT:  # %bb.23: # %udiv-bb15
; RV32I-NEXT:    addi a1, a0, 1
; RV32I-NEXT:    sub a0, s8, a0
; RV32I-NEXT:    sw zero, 152(sp)
; RV32I-NEXT:    sw zero, 156(sp)
; RV32I-NEXT:    sw zero, 160(sp)
; RV32I-NEXT:    sw zero, 164(sp)
; RV32I-NEXT:    sw s2, 168(sp)
; RV32I-NEXT:    sw s3, 172(sp)
; RV32I-NEXT:    sw s6, 176(sp)
; RV32I-NEXT:    sw s5, 180(sp)
; RV32I-NEXT:    addi a6, sp, 168
; RV32I-NEXT:    seqz t0, a1
; RV32I-NEXT:    srli t1, a0, 3
; RV32I-NEXT:    andi t2, a0, 31
; RV32I-NEXT:    add a4, a4, t0
; RV32I-NEXT:    andi t0, t1, 12
; RV32I-NEXT:    xori t1, t2, 31
; RV32I-NEXT:    or t2, a1, a4
; RV32I-NEXT:    sub a6, a6, t0
; RV32I-NEXT:    seqz t0, t2
; RV32I-NEXT:    lw t4, 0(a6)
; RV32I-NEXT:    lw t2, 4(a6)
; RV32I-NEXT:    lw t5, 8(a6)
; RV32I-NEXT:    lw t3, 12(a6)
; RV32I-NEXT:    add t0, a5, t0
; RV32I-NEXT:    sltu a6, t0, a5
; RV32I-NEXT:    or a5, a1, t0
; RV32I-NEXT:    add a6, a7, a6
; RV32I-NEXT:    or a7, a4, a6
; RV32I-NEXT:    srli t6, t5, 1
; RV32I-NEXT:    srli s0, t2, 1
; RV32I-NEXT:    or a7, a5, a7
; RV32I-NEXT:    srli a5, t4, 1
; RV32I-NEXT:    srl t6, t6, t1
; RV32I-NEXT:    srl s0, s0, t1
; RV32I-NEXT:    srl a5, a5, t1
; RV32I-NEXT:    sll t1, t3, a0
; RV32I-NEXT:    or t3, t1, t6
; RV32I-NEXT:    sll t1, t5, a0
; RV32I-NEXT:    sll t2, t2, a0
; RV32I-NEXT:    or t1, t1, s0
; RV32I-NEXT:    or t2, t2, a5
; RV32I-NEXT:    sll a5, t4, a0
; RV32I-NEXT:    beqz a7, .LBB1_31
; RV32I-NEXT:  # %bb.24: # %udiv-preheader4
; RV32I-NEXT:    li a7, 0
; RV32I-NEXT:    li t4, 0
; RV32I-NEXT:    li t5, 0
; RV32I-NEXT:    li t6, 0
; RV32I-NEXT:    sw zero, 136(sp)
; RV32I-NEXT:    sw zero, 140(sp)
; RV32I-NEXT:    sw zero, 144(sp)
; RV32I-NEXT:    sw zero, 148(sp)
; RV32I-NEXT:    sw s2, 120(sp)
; RV32I-NEXT:    sw s3, 124(sp)
; RV32I-NEXT:    sw s6, 128(sp)
; RV32I-NEXT:    sw s5, 132(sp)
; RV32I-NEXT:    srli a0, a1, 3
; RV32I-NEXT:    addi s0, sp, 120
; RV32I-NEXT:    andi a0, a0, 12
; RV32I-NEXT:    add a0, s0, a0
; RV32I-NEXT:    lw s0, 4(a0)
; RV32I-NEXT:    lw s1, 8(a0)
; RV32I-NEXT:    lw s2, 12(a0)
; RV32I-NEXT:    lw a0, 0(a0)
; RV32I-NEXT:    andi s3, a1, 31
; RV32I-NEXT:    xori s3, s3, 31
; RV32I-NEXT:    slli s4, s2, 1
; RV32I-NEXT:    slli s5, s1, 1
; RV32I-NEXT:    slli s6, s0, 1
; RV32I-NEXT:    sll s4, s4, s3
; RV32I-NEXT:    sll s5, s5, s3
; RV32I-NEXT:    sll s3, s6, s3
; RV32I-NEXT:    seqz s6, s11
; RV32I-NEXT:    srl s1, s1, a1
; RV32I-NEXT:    or s8, s1, s4
; RV32I-NEXT:    or s1, s11, s10
; RV32I-NEXT:    sub s4, s10, s6
; RV32I-NEXT:    seqz s1, s1
; RV32I-NEXT:    srl s0, s0, a1
; RV32I-NEXT:    or s9, s0, s5
; RV32I-NEXT:    sub s5, a3, s1
; RV32I-NEXT:    sltu s0, a3, s1
; RV32I-NEXT:    sub s6, ra, s0
; RV32I-NEXT:    srl s0, a0, a1
; RV32I-NEXT:    srl a0, s2, a1
; RV32I-NEXT:    mv s1, s11
; RV32I-NEXT:    or s11, s0, s3
; RV32I-NEXT:    addi s1, s1, -1
; RV32I-NEXT:    sw s1, 44(sp) # 4-byte Folded Spill
; RV32I-NEXT:    j .LBB1_26
; RV32I-NEXT:  .LBB1_25: # %udiv-do-while3
; RV32I-NEXT:    # in Loop: Header=BB1_26 Depth=1
; RV32I-NEXT:    srli s2, t1, 31
; RV32I-NEXT:    slli t3, t3, 1
; RV32I-NEXT:    sub s7, s10, s7
; RV32I-NEXT:    srli s10, t2, 31
; RV32I-NEXT:    slli t1, t1, 1
; RV32I-NEXT:    or t3, t3, s2
; RV32I-NEXT:    srli s2, a5, 31
; RV32I-NEXT:    slli t2, t2, 1
; RV32I-NEXT:    slli a5, a5, 1
; RV32I-NEXT:    or t1, t1, s10
; RV32I-NEXT:    lw s3, 48(sp) # 4-byte Folded Reload
; RV32I-NEXT:    and s10, s9, s3
; RV32I-NEXT:    or t2, t2, s2
; RV32I-NEXT:    and s2, s9, a3
; RV32I-NEXT:    or a5, a7, a5
; RV32I-NEXT:    sub s3, s0, s2
; RV32I-NEXT:    sltu s0, s0, s2
; RV32I-NEXT:    or s2, a1, a4
; RV32I-NEXT:    sub s10, s8, s10
; RV32I-NEXT:    seqz s8, a1
; RV32I-NEXT:    addi a1, a1, -1
; RV32I-NEXT:    andi a7, s9, 1
; RV32I-NEXT:    sub s9, s7, s1
; RV32I-NEXT:    seqz s1, s2
; RV32I-NEXT:    sub a4, a4, s8
; RV32I-NEXT:    or t2, t4, t2
; RV32I-NEXT:    or t1, t5, t1
; RV32I-NEXT:    or t3, t6, t3
; RV32I-NEXT:    sub s8, s3, a0
; RV32I-NEXT:    sltu a0, s3, a0
; RV32I-NEXT:    sub t4, s10, s0
; RV32I-NEXT:    sltu t5, t0, s1
; RV32I-NEXT:    sub t0, t0, s1
; RV32I-NEXT:    sub a0, t4, a0
; RV32I-NEXT:    sub a6, a6, t5
; RV32I-NEXT:    or t4, a4, a6
; RV32I-NEXT:    or t5, a1, t0
; RV32I-NEXT:    or s0, t5, t4
; RV32I-NEXT:    sub s11, ra, s11
; RV32I-NEXT:    li t4, 0
; RV32I-NEXT:    li t5, 0
; RV32I-NEXT:    li t6, 0
; RV32I-NEXT:    beqz s0, .LBB1_31
; RV32I-NEXT:  .LBB1_26: # %udiv-do-while3
; RV32I-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32I-NEXT:    srli s0, s11, 31
; RV32I-NEXT:    slli s1, s9, 1
; RV32I-NEXT:    slli s11, s11, 1
; RV32I-NEXT:    or s10, s1, s0
; RV32I-NEXT:    srli s0, t3, 31
; RV32I-NEXT:    or ra, s11, s0
; RV32I-NEXT:    beq s4, s10, .LBB1_28
; RV32I-NEXT:  # %bb.27: # %udiv-do-while3
; RV32I-NEXT:    # in Loop: Header=BB1_26 Depth=1
; RV32I-NEXT:    sltu s1, s4, s10
; RV32I-NEXT:    j .LBB1_29
; RV32I-NEXT:  .LBB1_28: # in Loop: Header=BB1_26 Depth=1
; RV32I-NEXT:    lw s0, 44(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sltu s1, s0, ra
; RV32I-NEXT:  .LBB1_29: # %udiv-do-while3
; RV32I-NEXT:    # in Loop: Header=BB1_26 Depth=1
; RV32I-NEXT:    srli s0, s8, 31
; RV32I-NEXT:    slli a0, a0, 1
; RV32I-NEXT:    srli s7, s9, 31
; RV32I-NEXT:    slli s9, s8, 1
; RV32I-NEXT:    or s8, a0, s0
; RV32I-NEXT:    or s0, s9, s7
; RV32I-NEXT:    sub a0, s5, s0
; RV32I-NEXT:    sltu s7, s5, s0
; RV32I-NEXT:    sub s9, s6, s8
; RV32I-NEXT:    sltu a0, a0, s1
; RV32I-NEXT:    sub s1, s9, s7
; RV32I-NEXT:    sub s1, s1, a0
; RV32I-NEXT:    srai s9, s1, 31
; RV32I-NEXT:    and s11, s9, a2
; RV32I-NEXT:    lw a0, 52(sp) # 4-byte Folded Reload
; RV32I-NEXT:    and s7, s9, a0
; RV32I-NEXT:    sltu s1, ra, s11
; RV32I-NEXT:    mv a0, s1
; RV32I-NEXT:    beq s10, s7, .LBB1_25
; RV32I-NEXT:  # %bb.30: # %udiv-do-while3
; RV32I-NEXT:    # in Loop: Header=BB1_26 Depth=1
; RV32I-NEXT:    sltu a0, s10, s7
; RV32I-NEXT:    j .LBB1_25
; RV32I-NEXT:  .LBB1_31: # %udiv-loop-exit2
; RV32I-NEXT:    srli a0, a5, 31
; RV32I-NEXT:    slli a1, t2, 1
; RV32I-NEXT:    srli a4, t2, 31
; RV32I-NEXT:    or t0, a1, a0
; RV32I-NEXT:    slli a0, t1, 1
; RV32I-NEXT:    srli a1, t1, 31
; RV32I-NEXT:    slli t3, t3, 1
; RV32I-NEXT:    slli a5, a5, 1
; RV32I-NEXT:    or t2, a0, a4
; RV32I-NEXT:    or t1, t3, a1
; RV32I-NEXT:    or t3, a7, a5
; RV32I-NEXT:    lw s10, 52(sp) # 4-byte Folded Reload
; RV32I-NEXT:    mv s11, a2
; RV32I-NEXT:    lw s3, 28(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw ra, 48(sp) # 4-byte Folded Reload
; RV32I-NEXT:    mv s9, a3
; RV32I-NEXT:    lw s2, 40(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s5, 36(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s6, 32(sp) # 4-byte Folded Reload
; RV32I-NEXT:    li s8, 127
; RV32I-NEXT:  .LBB1_32: # %udiv-end1
; RV32I-NEXT:    lui a0, 349525
; RV32I-NEXT:    lui a1, 209715
; RV32I-NEXT:    lui a6, 61681
; RV32I-NEXT:    addi a5, a0, 1365
; RV32I-NEXT:    addi a4, a1, 819
; RV32I-NEXT:    addi a1, a6, -241
; RV32I-NEXT:    sw t0, 16(sp) # 4-byte Folded Spill
; RV32I-NEXT:    bnez s10, .LBB1_35
; RV32I-NEXT:  # %bb.33: # %udiv-end1
; RV32I-NEXT:    srli a0, s11, 1
; RV32I-NEXT:    or a0, s11, a0
; RV32I-NEXT:    srli a6, a0, 2
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    srli a6, a0, 4
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    srli a6, a0, 8
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    srli a6, a0, 16
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    not a0, a0
; RV32I-NEXT:    srli a6, a0, 1
; RV32I-NEXT:    and a6, a6, a5
; RV32I-NEXT:    sub a0, a0, a6
; RV32I-NEXT:    and a6, a0, a4
; RV32I-NEXT:    srli a0, a0, 2
; RV32I-NEXT:    and a0, a0, a4
; RV32I-NEXT:    add a0, a6, a0
; RV32I-NEXT:    srli a6, a0, 4
; RV32I-NEXT:    add a0, a0, a6
; RV32I-NEXT:    and a0, a0, a1
; RV32I-NEXT:    slli a6, a0, 8
; RV32I-NEXT:    add a0, a0, a6
; RV32I-NEXT:    slli a6, a0, 16
; RV32I-NEXT:    add a0, a0, a6
; RV32I-NEXT:    srli a0, a0, 24
; RV32I-NEXT:    addi a7, a0, 32
; RV32I-NEXT:    or t0, s9, ra
; RV32I-NEXT:    beqz ra, .LBB1_36
; RV32I-NEXT:  .LBB1_34:
; RV32I-NEXT:    srli a0, ra, 1
; RV32I-NEXT:    or a0, ra, a0
; RV32I-NEXT:    srli a6, a0, 2
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    srli a6, a0, 4
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    srli a6, a0, 8
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    srli a6, a0, 16
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    not a0, a0
; RV32I-NEXT:    srli a6, a0, 1
; RV32I-NEXT:    and a6, a6, a5
; RV32I-NEXT:    sub a0, a0, a6
; RV32I-NEXT:    and a6, a0, a4
; RV32I-NEXT:    srli a0, a0, 2
; RV32I-NEXT:    and a0, a0, a4
; RV32I-NEXT:    add a0, a6, a0
; RV32I-NEXT:    srli a6, a0, 4
; RV32I-NEXT:    add a0, a0, a6
; RV32I-NEXT:    and a0, a0, a1
; RV32I-NEXT:    slli a6, a0, 8
; RV32I-NEXT:    add a0, a0, a6
; RV32I-NEXT:    slli a6, a0, 16
; RV32I-NEXT:    add a0, a0, a6
; RV32I-NEXT:    srli a6, a0, 24
; RV32I-NEXT:    addi a0, a7, 64
; RV32I-NEXT:    beqz t0, .LBB1_37
; RV32I-NEXT:    j .LBB1_38
; RV32I-NEXT:  .LBB1_35:
; RV32I-NEXT:    srli a0, s10, 1
; RV32I-NEXT:    or a0, s10, a0
; RV32I-NEXT:    srli a6, a0, 2
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    srli a6, a0, 4
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    srli a6, a0, 8
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    srli a6, a0, 16
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    not a0, a0
; RV32I-NEXT:    srli a6, a0, 1
; RV32I-NEXT:    and a6, a6, a5
; RV32I-NEXT:    sub a0, a0, a6
; RV32I-NEXT:    and a6, a0, a4
; RV32I-NEXT:    srli a0, a0, 2
; RV32I-NEXT:    and a0, a0, a4
; RV32I-NEXT:    add a0, a6, a0
; RV32I-NEXT:    srli a6, a0, 4
; RV32I-NEXT:    add a0, a0, a6
; RV32I-NEXT:    and a0, a0, a1
; RV32I-NEXT:    slli a6, a0, 8
; RV32I-NEXT:    add a0, a0, a6
; RV32I-NEXT:    slli a6, a0, 16
; RV32I-NEXT:    add a0, a0, a6
; RV32I-NEXT:    srli a7, a0, 24
; RV32I-NEXT:    or t0, s9, ra
; RV32I-NEXT:    bnez ra, .LBB1_34
; RV32I-NEXT:  .LBB1_36: # %udiv-end1
; RV32I-NEXT:    srli a0, s9, 1
; RV32I-NEXT:    or a0, s9, a0
; RV32I-NEXT:    srli a6, a0, 2
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    srli a6, a0, 4
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    srli a6, a0, 8
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    srli a6, a0, 16
; RV32I-NEXT:    or a0, a0, a6
; RV32I-NEXT:    not a0, a0
; RV32I-NEXT:    srli a6, a0, 1
; RV32I-NEXT:    and a6, a6, a5
; RV32I-NEXT:    sub a0, a0, a6
; RV32I-NEXT:    and a6, a0, a4
; RV32I-NEXT:    srli a0, a0, 2
; RV32I-NEXT:    and a0, a0, a4
; RV32I-NEXT:    add a0, a6, a0
; RV32I-NEXT:    srli a6, a0, 4
; RV32I-NEXT:    add a0, a0, a6
; RV32I-NEXT:    and a0, a0, a1
; RV32I-NEXT:    slli a6, a0, 8
; RV32I-NEXT:    add a0, a0, a6
; RV32I-NEXT:    slli a6, a0, 16
; RV32I-NEXT:    add a0, a0, a6
; RV32I-NEXT:    srli a0, a0, 24
; RV32I-NEXT:    addi a6, a0, 32
; RV32I-NEXT:    addi a0, a7, 64
; RV32I-NEXT:    bnez t0, .LBB1_38
; RV32I-NEXT:  .LBB1_37: # %udiv-end1
; RV32I-NEXT:    mv a6, a0
; RV32I-NEXT:  .LBB1_38: # %udiv-end1
; RV32I-NEXT:    sw t1, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    snez t4, t0
; RV32I-NEXT:    sw t2, 8(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw t3, 4(sp) # 4-byte Folded Spill
; RV32I-NEXT:    bnez s3, .LBB1_40
; RV32I-NEXT:  # %bb.39: # %udiv-end1
; RV32I-NEXT:    srli t0, s2, 1
; RV32I-NEXT:    or t0, s2, t0
; RV32I-NEXT:    srli t1, t0, 2
; RV32I-NEXT:    or t0, t0, t1
; RV32I-NEXT:    srli t1, t0, 4
; RV32I-NEXT:    or t0, t0, t1
; RV32I-NEXT:    srli t1, t0, 8
; RV32I-NEXT:    or t0, t0, t1
; RV32I-NEXT:    srli t1, t0, 16
; RV32I-NEXT:    or t0, t0, t1
; RV32I-NEXT:    not t0, t0
; RV32I-NEXT:    srli t1, t0, 1
; RV32I-NEXT:    and t1, t1, a5
; RV32I-NEXT:    sub t0, t0, t1
; RV32I-NEXT:    and t1, t0, a4
; RV32I-NEXT:    srli t0, t0, 2
; RV32I-NEXT:    and t0, t0, a4
; RV32I-NEXT:    add t0, t1, t0
; RV32I-NEXT:    srli t1, t0, 4
; RV32I-NEXT:    add t0, t0, t1
; RV32I-NEXT:    and t0, t0, a1
; RV32I-NEXT:    slli t1, t0, 8
; RV32I-NEXT:    add t0, t0, t1
; RV32I-NEXT:    slli t1, t0, 16
; RV32I-NEXT:    add t0, t0, t1
; RV32I-NEXT:    srli t0, t0, 24
; RV32I-NEXT:    addi t6, t0, 32
; RV32I-NEXT:    j .LBB1_41
; RV32I-NEXT:  .LBB1_40:
; RV32I-NEXT:    srli t0, s3, 1
; RV32I-NEXT:    or t0, s3, t0
; RV32I-NEXT:    srli t1, t0, 2
; RV32I-NEXT:    or t0, t0, t1
; RV32I-NEXT:    srli t1, t0, 4
; RV32I-NEXT:    or t0, t0, t1
; RV32I-NEXT:    srli t1, t0, 8
; RV32I-NEXT:    or t0, t0, t1
; RV32I-NEXT:    srli t1, t0, 16
; RV32I-NEXT:    or t0, t0, t1
; RV32I-NEXT:    not t0, t0
; RV32I-NEXT:    srli t1, t0, 1
; RV32I-NEXT:    and t1, t1, a5
; RV32I-NEXT:    sub t0, t0, t1
; RV32I-NEXT:    and t1, t0, a4
; RV32I-NEXT:    srli t0, t0, 2
; RV32I-NEXT:    and t0, t0, a4
; RV32I-NEXT:    add t0, t1, t0
; RV32I-NEXT:    srli t1, t0, 4
; RV32I-NEXT:    add t0, t0, t1
; RV32I-NEXT:    and t0, t0, a1
; RV32I-NEXT:    slli t1, t0, 8
; RV32I-NEXT:    add t0, t0, t1
; RV32I-NEXT:    slli t1, t0, 16
; RV32I-NEXT:    add t0, t0, t1
; RV32I-NEXT:    srli t6, t0, 24
; RV32I-NEXT:  .LBB1_41: # %udiv-end1
; RV32I-NEXT:    or t0, s11, s9
; RV32I-NEXT:    or t1, s10, ra
; RV32I-NEXT:    or t2, s2, s6
; RV32I-NEXT:    or t3, s3, s5
; RV32I-NEXT:    sltu a7, a0, a7
; RV32I-NEXT:    addi t4, t4, -1
; RV32I-NEXT:    addi a0, t6, 64
; RV32I-NEXT:    or t5, s6, s5
; RV32I-NEXT:    sltu t6, a0, t6
; RV32I-NEXT:    snez s4, t5
; RV32I-NEXT:    addi s4, s4, -1
; RV32I-NEXT:    bnez s5, .LBB1_43
; RV32I-NEXT:  # %bb.42: # %udiv-end1
; RV32I-NEXT:    srli s0, s6, 1
; RV32I-NEXT:    or s0, s6, s0
; RV32I-NEXT:    srli s1, s0, 2
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    srli s1, s0, 4
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    srli s1, s0, 8
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    srli s1, s0, 16
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    not s0, s0
; RV32I-NEXT:    srli s1, s0, 1
; RV32I-NEXT:    and a5, s1, a5
; RV32I-NEXT:    sub s0, s0, a5
; RV32I-NEXT:    and a5, s0, a4
; RV32I-NEXT:    srli s0, s0, 2
; RV32I-NEXT:    and a4, s0, a4
; RV32I-NEXT:    add a4, a5, a4
; RV32I-NEXT:    srli a5, a4, 4
; RV32I-NEXT:    add a4, a4, a5
; RV32I-NEXT:    and a1, a4, a1
; RV32I-NEXT:    slli a4, a1, 8
; RV32I-NEXT:    add a1, a1, a4
; RV32I-NEXT:    slli a4, a1, 16
; RV32I-NEXT:    add a1, a1, a4
; RV32I-NEXT:    srli a1, a1, 24
; RV32I-NEXT:    addi a1, a1, 32
; RV32I-NEXT:    j .LBB1_44
; RV32I-NEXT:  .LBB1_43:
; RV32I-NEXT:    srli s0, s5, 1
; RV32I-NEXT:    or s0, s5, s0
; RV32I-NEXT:    srli s1, s0, 2
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    srli s1, s0, 4
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    srli s1, s0, 8
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    srli s1, s0, 16
; RV32I-NEXT:    or s0, s0, s1
; RV32I-NEXT:    not s0, s0
; RV32I-NEXT:    srli s1, s0, 1
; RV32I-NEXT:    and a5, s1, a5
; RV32I-NEXT:    sub s0, s0, a5
; RV32I-NEXT:    and a5, s0, a4
; RV32I-NEXT:    srli s0, s0, 2
; RV32I-NEXT:    and a4, s0, a4
; RV32I-NEXT:    add a4, a5, a4
; RV32I-NEXT:    srli a5, a4, 4
; RV32I-NEXT:    add a4, a4, a5
; RV32I-NEXT:    and a1, a4, a1
; RV32I-NEXT:    slli a4, a1, 8
; RV32I-NEXT:    add a1, a1, a4
; RV32I-NEXT:    slli a4, a1, 16
; RV32I-NEXT:    add a1, a1, a4
; RV32I-NEXT:    srli a1, a1, 24
; RV32I-NEXT:  .LBB1_44: # %udiv-end1
; RV32I-NEXT:    or t0, t0, t1
; RV32I-NEXT:    or t1, t2, t3
; RV32I-NEXT:    and a4, t4, a7
; RV32I-NEXT:    and a5, s4, t6
; RV32I-NEXT:    bnez t5, .LBB1_46
; RV32I-NEXT:  # %bb.45: # %udiv-end1
; RV32I-NEXT:    mv a1, a0
; RV32I-NEXT:  .LBB1_46: # %udiv-end1
; RV32I-NEXT:    seqz a0, t0
; RV32I-NEXT:    seqz t0, t1
; RV32I-NEXT:    sltu a7, a6, a1
; RV32I-NEXT:    sub t2, a4, a5
; RV32I-NEXT:    mv t1, a7
; RV32I-NEXT:    beq a4, a5, .LBB1_48
; RV32I-NEXT:  # %bb.47: # %udiv-end1
; RV32I-NEXT:    sltu t1, a4, a5
; RV32I-NEXT:  .LBB1_48: # %udiv-end1
; RV32I-NEXT:    sub a7, t2, a7
; RV32I-NEXT:    or t0, a0, t0
; RV32I-NEXT:    neg a4, t1
; RV32I-NEXT:    seqz a5, t1
; RV32I-NEXT:    addi a5, a5, -1
; RV32I-NEXT:    or t1, a4, a5
; RV32I-NEXT:    sub a0, a6, a1
; RV32I-NEXT:    beqz t1, .LBB1_50
; RV32I-NEXT:  # %bb.49: # %udiv-end1
; RV32I-NEXT:    snez a1, t1
; RV32I-NEXT:    j .LBB1_51
; RV32I-NEXT:  .LBB1_50:
; RV32I-NEXT:    snez a1, a7
; RV32I-NEXT:    sltiu a6, a0, 128
; RV32I-NEXT:    xori a6, a6, 1
; RV32I-NEXT:    or a1, a6, a1
; RV32I-NEXT:  .LBB1_51: # %udiv-end1
; RV32I-NEXT:    or a1, t0, a1
; RV32I-NEXT:    addi a6, a1, -1
; RV32I-NEXT:    and s5, a6, s5
; RV32I-NEXT:    and s7, a6, s6
; RV32I-NEXT:    and s4, a6, s3
; RV32I-NEXT:    and s6, a6, s2
; RV32I-NEXT:    bnez a1, .LBB1_62
; RV32I-NEXT:  # %bb.52: # %udiv-end1
; RV32I-NEXT:    xori a1, a0, 127
; RV32I-NEXT:    or a1, a1, a4
; RV32I-NEXT:    or a6, a7, a5
; RV32I-NEXT:    or a1, a1, a6
; RV32I-NEXT:    beqz a1, .LBB1_62
; RV32I-NEXT:  # %bb.53: # %udiv-bb1
; RV32I-NEXT:    addi a1, a0, 1
; RV32I-NEXT:    sub a6, s8, a0
; RV32I-NEXT:    sw zero, 88(sp)
; RV32I-NEXT:    sw zero, 92(sp)
; RV32I-NEXT:    sw zero, 96(sp)
; RV32I-NEXT:    sw zero, 100(sp)
; RV32I-NEXT:    lw s2, 40(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sw s2, 104(sp)
; RV32I-NEXT:    sw s3, 108(sp)
; RV32I-NEXT:    lw s5, 32(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sw s5, 112(sp)
; RV32I-NEXT:    lw s4, 36(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sw s4, 116(sp)
; RV32I-NEXT:    addi t0, sp, 104
; RV32I-NEXT:    seqz a0, a1
; RV32I-NEXT:    srli t1, a6, 3
; RV32I-NEXT:    andi t2, a6, 31
; RV32I-NEXT:    add a0, a7, a0
; RV32I-NEXT:    andi a7, t1, 12
; RV32I-NEXT:    xori t1, t2, 31
; RV32I-NEXT:    or t2, a1, a0
; RV32I-NEXT:    sub a7, t0, a7
; RV32I-NEXT:    seqz t0, t2
; RV32I-NEXT:    lw t3, 0(a7)
; RV32I-NEXT:    lw t4, 4(a7)
; RV32I-NEXT:    lw t5, 8(a7)
; RV32I-NEXT:    lw t2, 12(a7)
; RV32I-NEXT:    add a7, a4, t0
; RV32I-NEXT:    sltu a4, a7, a4
; RV32I-NEXT:    or t0, a1, a7
; RV32I-NEXT:    add a5, a5, a4
; RV32I-NEXT:    or a4, a0, a5
; RV32I-NEXT:    srli t6, t5, 1
; RV32I-NEXT:    srli s0, t4, 1
; RV32I-NEXT:    or s1, t0, a4
; RV32I-NEXT:    srli a4, t3, 1
; RV32I-NEXT:    srl t0, t6, t1
; RV32I-NEXT:    srl t6, s0, t1
; RV32I-NEXT:    srl a4, a4, t1
; RV32I-NEXT:    sll t1, t2, a6
; RV32I-NEXT:    or t2, t1, t0
; RV32I-NEXT:    sll t0, t5, a6
; RV32I-NEXT:    sll t1, t4, a6
; RV32I-NEXT:    or t0, t0, t6
; RV32I-NEXT:    or t1, t1, a4
; RV32I-NEXT:    sll a4, t3, a6
; RV32I-NEXT:    li a6, 0
; RV32I-NEXT:    beqz s1, .LBB1_61
; RV32I-NEXT:  # %bb.54: # %udiv-preheader
; RV32I-NEXT:    li t3, 0
; RV32I-NEXT:    li t4, 0
; RV32I-NEXT:    li t5, 0
; RV32I-NEXT:    sw zero, 72(sp)
; RV32I-NEXT:    sw zero, 76(sp)
; RV32I-NEXT:    sw zero, 80(sp)
; RV32I-NEXT:    sw zero, 84(sp)
; RV32I-NEXT:    sw s2, 56(sp)
; RV32I-NEXT:    sw s3, 60(sp)
; RV32I-NEXT:    sw s5, 64(sp)
; RV32I-NEXT:    sw s4, 68(sp)
; RV32I-NEXT:    srli t6, a1, 3
; RV32I-NEXT:    addi s0, sp, 56
; RV32I-NEXT:    andi t6, t6, 12
; RV32I-NEXT:    add t6, s0, t6
; RV32I-NEXT:    lw s0, 4(t6)
; RV32I-NEXT:    lw s1, 8(t6)
; RV32I-NEXT:    lw s2, 12(t6)
; RV32I-NEXT:    lw s3, 0(t6)
; RV32I-NEXT:    andi t6, a1, 31
; RV32I-NEXT:    xori t6, t6, 31
; RV32I-NEXT:    slli s4, s2, 1
; RV32I-NEXT:    slli s5, s1, 1
; RV32I-NEXT:    slli s6, s0, 1
; RV32I-NEXT:    sll s4, s4, t6
; RV32I-NEXT:    sll s5, s5, t6
; RV32I-NEXT:    sll s6, s6, t6
; RV32I-NEXT:    seqz t6, s11
; RV32I-NEXT:    srl s1, s1, a1
; RV32I-NEXT:    or s7, s1, s4
; RV32I-NEXT:    or s1, s11, s10
; RV32I-NEXT:    sub t6, s10, t6
; RV32I-NEXT:    seqz s1, s1
; RV32I-NEXT:    srl s0, s0, a1
; RV32I-NEXT:    or s8, s0, s5
; RV32I-NEXT:    sub s4, s9, s1
; RV32I-NEXT:    sltu s0, s9, s1
; RV32I-NEXT:    sub s5, ra, s0
; RV32I-NEXT:    srl s0, s3, a1
; RV32I-NEXT:    srl ra, s2, a1
; RV32I-NEXT:    or s9, s0, s6
; RV32I-NEXT:    addi s0, s11, -1
; RV32I-NEXT:    sw s0, 44(sp) # 4-byte Folded Spill
; RV32I-NEXT:    j .LBB1_56
; RV32I-NEXT:  .LBB1_55: # %udiv-do-while
; RV32I-NEXT:    # in Loop: Header=BB1_56 Depth=1
; RV32I-NEXT:    srli s2, t0, 31
; RV32I-NEXT:    slli t2, t2, 1
; RV32I-NEXT:    sub s3, s10, s6
; RV32I-NEXT:    srli s6, t1, 31
; RV32I-NEXT:    slli t0, t0, 1
; RV32I-NEXT:    or t2, t2, s2
; RV32I-NEXT:    srli s2, a4, 31
; RV32I-NEXT:    slli t1, t1, 1
; RV32I-NEXT:    slli a4, a4, 1
; RV32I-NEXT:    or t0, t0, s6
; RV32I-NEXT:    lw s6, 48(sp) # 4-byte Folded Reload
; RV32I-NEXT:    and s6, s8, s6
; RV32I-NEXT:    or t1, t1, s2
; RV32I-NEXT:    and s2, s8, a3
; RV32I-NEXT:    or a4, a6, a4
; RV32I-NEXT:    sub s10, s0, s2
; RV32I-NEXT:    sltu s0, s0, s2
; RV32I-NEXT:    or s2, a1, a0
; RV32I-NEXT:    sub s6, s7, s6
; RV32I-NEXT:    seqz s7, a1
; RV32I-NEXT:    addi a1, a1, -1
; RV32I-NEXT:    andi a6, s8, 1
; RV32I-NEXT:    sub s8, s3, s1
; RV32I-NEXT:    seqz s1, s2
; RV32I-NEXT:    sub a0, a0, s7
; RV32I-NEXT:    or t1, t3, t1
; RV32I-NEXT:    or t0, t4, t0
; RV32I-NEXT:    or t2, t5, t2
; RV32I-NEXT:    sub s7, s10, ra
; RV32I-NEXT:    sltu t3, s10, ra
; RV32I-NEXT:    sub t4, s6, s0
; RV32I-NEXT:    sltu t5, a7, s1
; RV32I-NEXT:    sub a7, a7, s1
; RV32I-NEXT:    sub ra, t4, t3
; RV32I-NEXT:    sub a5, a5, t5
; RV32I-NEXT:    or t3, a0, a5
; RV32I-NEXT:    or t4, a1, a7
; RV32I-NEXT:    or s0, t4, t3
; RV32I-NEXT:    sub s9, s9, s11
; RV32I-NEXT:    li t3, 0
; RV32I-NEXT:    li t4, 0
; RV32I-NEXT:    li t5, 0
; RV32I-NEXT:    mv s11, a2
; RV32I-NEXT:    beqz s0, .LBB1_61
; RV32I-NEXT:  .LBB1_56: # %udiv-do-while
; RV32I-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32I-NEXT:    srli s0, s9, 31
; RV32I-NEXT:    slli s1, s8, 1
; RV32I-NEXT:    slli s9, s9, 1
; RV32I-NEXT:    or s10, s1, s0
; RV32I-NEXT:    srli s0, t2, 31
; RV32I-NEXT:    or s9, s9, s0
; RV32I-NEXT:    beq t6, s10, .LBB1_58
; RV32I-NEXT:  # %bb.57: # %udiv-do-while
; RV32I-NEXT:    # in Loop: Header=BB1_56 Depth=1
; RV32I-NEXT:    sltu s1, t6, s10
; RV32I-NEXT:    j .LBB1_59
; RV32I-NEXT:  .LBB1_58: # in Loop: Header=BB1_56 Depth=1
; RV32I-NEXT:    lw s0, 44(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sltu s1, s0, s9
; RV32I-NEXT:  .LBB1_59: # %udiv-do-while
; RV32I-NEXT:    # in Loop: Header=BB1_56 Depth=1
; RV32I-NEXT:    srli s0, s7, 31
; RV32I-NEXT:    slli ra, ra, 1
; RV32I-NEXT:    srli s2, s8, 31
; RV32I-NEXT:    slli s3, s7, 1
; RV32I-NEXT:    or s7, ra, s0
; RV32I-NEXT:    or s0, s3, s2
; RV32I-NEXT:    sub s2, s4, s0
; RV32I-NEXT:    sltu s3, s4, s0
; RV32I-NEXT:    sub s6, s5, s7
; RV32I-NEXT:    sltu s1, s2, s1
; RV32I-NEXT:    sub s2, s6, s3
; RV32I-NEXT:    sub s1, s2, s1
; RV32I-NEXT:    srai s8, s1, 31
; RV32I-NEXT:    and s11, s8, s11
; RV32I-NEXT:    lw s1, 52(sp) # 4-byte Folded Reload
; RV32I-NEXT:    and s6, s8, s1
; RV32I-NEXT:    sltu s1, s9, s11
; RV32I-NEXT:    mv ra, s1
; RV32I-NEXT:    beq s10, s6, .LBB1_55
; RV32I-NEXT:  # %bb.60: # %udiv-do-while
; RV32I-NEXT:    # in Loop: Header=BB1_56 Depth=1
; RV32I-NEXT:    sltu ra, s10, s6
; RV32I-NEXT:    j .LBB1_55
; RV32I-NEXT:  .LBB1_61: # %udiv-loop-exit
; RV32I-NEXT:    srli a0, a4, 31
; RV32I-NEXT:    slli a1, t1, 1
; RV32I-NEXT:    srli a5, t1, 31
; RV32I-NEXT:    or s4, a1, a0
; RV32I-NEXT:    slli a0, t0, 1
; RV32I-NEXT:    srli a1, t0, 31
; RV32I-NEXT:    slli t2, t2, 1
; RV32I-NEXT:    slli a4, a4, 1
; RV32I-NEXT:    or s7, a0, a5
; RV32I-NEXT:    or s5, t2, a1
; RV32I-NEXT:    or s6, a6, a4
; RV32I-NEXT:    lw s10, 52(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s3, 28(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw ra, 48(sp) # 4-byte Folded Reload
; RV32I-NEXT:    mv s9, a3
; RV32I-NEXT:  .LBB1_62: # %udiv-end
; RV32I-NEXT:    mv a0, s6
; RV32I-NEXT:    mv a1, s4
; RV32I-NEXT:    mv a2, s9
; RV32I-NEXT:    mv a3, ra
; RV32I-NEXT:    call __muldi3
; RV32I-NEXT:    mv s8, a0
; RV32I-NEXT:    mv s9, a1
; RV32I-NEXT:    mv a0, s7
; RV32I-NEXT:    mv a1, s5
; RV32I-NEXT:    mv a2, s11
; RV32I-NEXT:    mv a3, s10
; RV32I-NEXT:    call __muldi3
; RV32I-NEXT:    add a1, a1, s9
; RV32I-NEXT:    add s9, a0, s8
; RV32I-NEXT:    sltu s8, s9, a0
; RV32I-NEXT:    add s8, a1, s8
; RV32I-NEXT:    mv a0, s11
; RV32I-NEXT:    li a1, 0
; RV32I-NEXT:    mv a2, s6
; RV32I-NEXT:    li a3, 0
; RV32I-NEXT:    call __muldi3
; RV32I-NEXT:    mv s5, a0
; RV32I-NEXT:    mv s7, a1
; RV32I-NEXT:    mv a0, s10
; RV32I-NEXT:    li a1, 0
; RV32I-NEXT:    mv a2, s6
; RV32I-NEXT:    li a3, 0
; RV32I-NEXT:    call __muldi3
; RV32I-NEXT:    add s0, a0, s7
; RV32I-NEXT:    sltu a0, s0, a0
; RV32I-NEXT:    add s1, a1, a0
; RV32I-NEXT:    mv a0, s11
; RV32I-NEXT:    li a1, 0
; RV32I-NEXT:    mv a2, s4
; RV32I-NEXT:    li a3, 0
; RV32I-NEXT:    call __muldi3
; RV32I-NEXT:    add s0, a0, s0
; RV32I-NEXT:    sltu a0, s0, a0
; RV32I-NEXT:    add a0, a1, a0
; RV32I-NEXT:    add s2, s1, a0
; RV32I-NEXT:    mv a0, s10
; RV32I-NEXT:    li a1, 0
; RV32I-NEXT:    mv a2, s4
; RV32I-NEXT:    li a3, 0
; RV32I-NEXT:    call __muldi3
; RV32I-NEXT:    add a3, a0, s2
; RV32I-NEXT:    sltu a4, s2, s1
; RV32I-NEXT:    lw a5, 40(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sltu a2, a5, s5
; RV32I-NEXT:    sltu a0, a3, a0
; RV32I-NEXT:    add a1, a1, a4
; RV32I-NEXT:    add s9, a3, s9
; RV32I-NEXT:    add a0, a1, a0
; RV32I-NEXT:    sltu a1, s9, a3
; RV32I-NEXT:    lw a6, 32(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sltu a3, a6, s9
; RV32I-NEXT:    add a0, a0, s8
; RV32I-NEXT:    lw a4, 36(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sub a1, a4, a1
; RV32I-NEXT:    sub a0, a1, a0
; RV32I-NEXT:    sub a0, a0, a3
; RV32I-NEXT:    sub a1, a6, s9
; RV32I-NEXT:    mv a3, a2
; RV32I-NEXT:    beq s3, s0, .LBB1_64
; RV32I-NEXT:  # %bb.63: # %udiv-end
; RV32I-NEXT:    sltu a3, s3, s0
; RV32I-NEXT:  .LBB1_64: # %udiv-end
; RV32I-NEXT:    sltu a4, a1, a3
; RV32I-NEXT:    sub a1, a1, a3
; RV32I-NEXT:    sub a3, s3, s0
; RV32I-NEXT:    sub a5, a5, s5
; RV32I-NEXT:    lw a6, 20(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw a7, 4(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sw a7, 0(a6)
; RV32I-NEXT:    lw a7, 16(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sw a7, 4(a6)
; RV32I-NEXT:    lw a7, 8(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sw a7, 8(a6)
; RV32I-NEXT:    lw a7, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sw a7, 12(a6)
; RV32I-NEXT:    sub a0, a0, a4
; RV32I-NEXT:    sub a3, a3, a2
; RV32I-NEXT:    lw a2, 24(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sw a5, 0(a2)
; RV32I-NEXT:    sw a3, 4(a2)
; RV32I-NEXT:    sw a1, 8(a2)
; RV32I-NEXT:    sw a0, 12(a2)
; RV32I-NEXT:    lw ra, 236(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s0, 232(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s1, 228(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s2, 224(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s3, 220(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s4, 216(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s5, 212(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s6, 208(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s7, 204(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s8, 200(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s9, 196(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s10, 192(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s11, 188(sp) # 4-byte Folded Reload
; RV32I-NEXT:    .cfi_restore ra
; RV32I-NEXT:    .cfi_restore s0
; RV32I-NEXT:    .cfi_restore s1
; RV32I-NEXT:    .cfi_restore s2
; RV32I-NEXT:    .cfi_restore s3
; RV32I-NEXT:    .cfi_restore s4
; RV32I-NEXT:    .cfi_restore s5
; RV32I-NEXT:    .cfi_restore s6
; RV32I-NEXT:    .cfi_restore s7
; RV32I-NEXT:    .cfi_restore s8
; RV32I-NEXT:    .cfi_restore s9
; RV32I-NEXT:    .cfi_restore s10
; RV32I-NEXT:    .cfi_restore s11
; RV32I-NEXT:    addi sp, sp, 240
; RV32I-NEXT:    .cfi_def_cfa_offset 0
; RV32I-NEXT:    ret
;
; RV32M-LABEL: udivrem_i128:
; RV32M:       # %bb.0: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    addi sp, sp, -256
; RV32M-NEXT:    .cfi_def_cfa_offset 256
; RV32M-NEXT:    sw ra, 252(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s0, 248(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s1, 244(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s2, 240(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s3, 236(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s4, 232(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s5, 228(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s6, 224(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s7, 220(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s8, 216(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s9, 212(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s10, 208(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s11, 204(sp) # 4-byte Folded Spill
; RV32M-NEXT:    .cfi_offset ra, -4
; RV32M-NEXT:    .cfi_offset s0, -8
; RV32M-NEXT:    .cfi_offset s1, -12
; RV32M-NEXT:    .cfi_offset s2, -16
; RV32M-NEXT:    .cfi_offset s3, -20
; RV32M-NEXT:    .cfi_offset s4, -24
; RV32M-NEXT:    .cfi_offset s5, -28
; RV32M-NEXT:    .cfi_offset s6, -32
; RV32M-NEXT:    .cfi_offset s7, -36
; RV32M-NEXT:    .cfi_offset s8, -40
; RV32M-NEXT:    .cfi_offset s9, -44
; RV32M-NEXT:    .cfi_offset s10, -48
; RV32M-NEXT:    .cfi_offset s11, -52
; RV32M-NEXT:    sw a1, 32(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw a0, 28(sp) # 4-byte Folded Spill
; RV32M-NEXT:    lw a6, 0(a3)
; RV32M-NEXT:    lw s11, 4(a3)
; RV32M-NEXT:    lw ra, 8(a3)
; RV32M-NEXT:    lw s10, 12(a3)
; RV32M-NEXT:    lui a0, 349525
; RV32M-NEXT:    lui a1, 209715
; RV32M-NEXT:    addi t5, a0, 1365
; RV32M-NEXT:    addi t4, a1, 819
; RV32M-NEXT:    lui t2, 61681
; RV32M-NEXT:    addi t2, t2, -241
; RV32M-NEXT:    lui t3, 4112
; RV32M-NEXT:    addi t3, t3, 257
; RV32M-NEXT:    bnez s11, .LBB1_2
; RV32M-NEXT:  # %bb.1: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    srli a0, a6, 1
; RV32M-NEXT:    or a0, a6, a0
; RV32M-NEXT:    srli a1, a0, 2
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 8
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 16
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a1, a0, 1
; RV32M-NEXT:    and a1, a1, t5
; RV32M-NEXT:    sub a0, a0, a1
; RV32M-NEXT:    and a1, a0, t4
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, t4
; RV32M-NEXT:    add a0, a1, a0
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    add a0, a0, a1
; RV32M-NEXT:    and a0, a0, t2
; RV32M-NEXT:    mul a0, a0, t3
; RV32M-NEXT:    srli a0, a0, 24
; RV32M-NEXT:    addi a1, a0, 32
; RV32M-NEXT:    j .LBB1_3
; RV32M-NEXT:  .LBB1_2:
; RV32M-NEXT:    srli a0, s11, 1
; RV32M-NEXT:    or a0, s11, a0
; RV32M-NEXT:    srli a1, a0, 2
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 8
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 16
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a1, a0, 1
; RV32M-NEXT:    and a1, a1, t5
; RV32M-NEXT:    sub a0, a0, a1
; RV32M-NEXT:    and a1, a0, t4
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, t4
; RV32M-NEXT:    add a0, a1, a0
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    add a0, a0, a1
; RV32M-NEXT:    and a0, a0, t2
; RV32M-NEXT:    mul a1, a0, t3
; RV32M-NEXT:    srli a1, a1, 24
; RV32M-NEXT:  .LBB1_3: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    lw s8, 4(a2)
; RV32M-NEXT:    or t6, ra, s10
; RV32M-NEXT:    bnez s10, .LBB1_5
; RV32M-NEXT:  # %bb.4: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    srli a0, ra, 1
; RV32M-NEXT:    or a0, ra, a0
; RV32M-NEXT:    srli a7, a0, 2
; RV32M-NEXT:    or a0, a0, a7
; RV32M-NEXT:    srli a7, a0, 4
; RV32M-NEXT:    or a0, a0, a7
; RV32M-NEXT:    srli a7, a0, 8
; RV32M-NEXT:    or a0, a0, a7
; RV32M-NEXT:    srli a7, a0, 16
; RV32M-NEXT:    or a0, a0, a7
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a7, a0, 1
; RV32M-NEXT:    and a7, a7, t5
; RV32M-NEXT:    sub a0, a0, a7
; RV32M-NEXT:    and a7, a0, t4
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, t4
; RV32M-NEXT:    add a0, a7, a0
; RV32M-NEXT:    srli a7, a0, 4
; RV32M-NEXT:    add a0, a0, a7
; RV32M-NEXT:    and a0, a0, t2
; RV32M-NEXT:    mul a0, a0, t3
; RV32M-NEXT:    srli a0, a0, 24
; RV32M-NEXT:    addi a0, a0, 32
; RV32M-NEXT:    j .LBB1_6
; RV32M-NEXT:  .LBB1_5:
; RV32M-NEXT:    srli a0, s10, 1
; RV32M-NEXT:    or a0, s10, a0
; RV32M-NEXT:    srli a7, a0, 2
; RV32M-NEXT:    or a0, a0, a7
; RV32M-NEXT:    srli a7, a0, 4
; RV32M-NEXT:    or a0, a0, a7
; RV32M-NEXT:    srli a7, a0, 8
; RV32M-NEXT:    or a0, a0, a7
; RV32M-NEXT:    srli a7, a0, 16
; RV32M-NEXT:    or a0, a0, a7
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a7, a0, 1
; RV32M-NEXT:    and a7, a7, t5
; RV32M-NEXT:    sub a0, a0, a7
; RV32M-NEXT:    and a7, a0, t4
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, t4
; RV32M-NEXT:    add a0, a7, a0
; RV32M-NEXT:    srli a7, a0, 4
; RV32M-NEXT:    add a0, a0, a7
; RV32M-NEXT:    and a0, a0, t2
; RV32M-NEXT:    mul a0, a0, t3
; RV32M-NEXT:    srli a0, a0, 24
; RV32M-NEXT:  .LBB1_6: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    lw s7, 12(a2)
; RV32M-NEXT:    addi t0, a1, 64
; RV32M-NEXT:    bnez t6, .LBB1_8
; RV32M-NEXT:  # %bb.7: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    mv a0, t0
; RV32M-NEXT:  .LBB1_8: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    lw s9, 0(a2)
; RV32M-NEXT:    lw s6, 8(a2)
; RV32M-NEXT:    snez s3, t6
; RV32M-NEXT:    bnez s8, .LBB1_10
; RV32M-NEXT:  # %bb.9: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    srli a2, s9, 1
; RV32M-NEXT:    or a2, s9, a2
; RV32M-NEXT:    srli a7, a2, 2
; RV32M-NEXT:    or a2, a2, a7
; RV32M-NEXT:    srli a7, a2, 4
; RV32M-NEXT:    or a2, a2, a7
; RV32M-NEXT:    srli a7, a2, 8
; RV32M-NEXT:    or a2, a2, a7
; RV32M-NEXT:    srli a7, a2, 16
; RV32M-NEXT:    or a2, a2, a7
; RV32M-NEXT:    not a2, a2
; RV32M-NEXT:    srli a7, a2, 1
; RV32M-NEXT:    and a7, a7, t5
; RV32M-NEXT:    sub a2, a2, a7
; RV32M-NEXT:    and a7, a2, t4
; RV32M-NEXT:    srli a2, a2, 2
; RV32M-NEXT:    and a2, a2, t4
; RV32M-NEXT:    add a2, a7, a2
; RV32M-NEXT:    srli a7, a2, 4
; RV32M-NEXT:    add a2, a2, a7
; RV32M-NEXT:    and a2, a2, t2
; RV32M-NEXT:    mul a2, a2, t3
; RV32M-NEXT:    srli a2, a2, 24
; RV32M-NEXT:    addi a2, a2, 32
; RV32M-NEXT:    j .LBB1_11
; RV32M-NEXT:  .LBB1_10:
; RV32M-NEXT:    srli a2, s8, 1
; RV32M-NEXT:    or a2, s8, a2
; RV32M-NEXT:    srli a7, a2, 2
; RV32M-NEXT:    or a2, a2, a7
; RV32M-NEXT:    srli a7, a2, 4
; RV32M-NEXT:    or a2, a2, a7
; RV32M-NEXT:    srli a7, a2, 8
; RV32M-NEXT:    or a2, a2, a7
; RV32M-NEXT:    srli a7, a2, 16
; RV32M-NEXT:    or a2, a2, a7
; RV32M-NEXT:    not a2, a2
; RV32M-NEXT:    srli a7, a2, 1
; RV32M-NEXT:    and a7, a7, t5
; RV32M-NEXT:    sub a2, a2, a7
; RV32M-NEXT:    and a7, a2, t4
; RV32M-NEXT:    srli a2, a2, 2
; RV32M-NEXT:    and a2, a2, t4
; RV32M-NEXT:    add a2, a7, a2
; RV32M-NEXT:    srli a7, a2, 4
; RV32M-NEXT:    add a2, a2, a7
; RV32M-NEXT:    and a2, a2, t2
; RV32M-NEXT:    mul a2, a2, t3
; RV32M-NEXT:    srli a2, a2, 24
; RV32M-NEXT:  .LBB1_11: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    or t6, s11, s10
; RV32M-NEXT:    or s0, a6, ra
; RV32M-NEXT:    or s1, s8, s7
; RV32M-NEXT:    or s2, s9, s6
; RV32M-NEXT:    sltu t0, t0, a1
; RV32M-NEXT:    addi s3, s3, -1
; RV32M-NEXT:    addi a1, a2, 64
; RV32M-NEXT:    or s4, s6, s7
; RV32M-NEXT:    sltu a7, a1, a2
; RV32M-NEXT:    snez a2, s4
; RV32M-NEXT:    addi a2, a2, -1
; RV32M-NEXT:    bnez s7, .LBB1_13
; RV32M-NEXT:  # %bb.12: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    srli t1, s6, 1
; RV32M-NEXT:    or t1, s6, t1
; RV32M-NEXT:    srli s5, t1, 2
; RV32M-NEXT:    or t1, t1, s5
; RV32M-NEXT:    srli s5, t1, 4
; RV32M-NEXT:    or t1, t1, s5
; RV32M-NEXT:    srli s5, t1, 8
; RV32M-NEXT:    or t1, t1, s5
; RV32M-NEXT:    srli s5, t1, 16
; RV32M-NEXT:    or t1, t1, s5
; RV32M-NEXT:    not t1, t1
; RV32M-NEXT:    srli s5, t1, 1
; RV32M-NEXT:    and t5, s5, t5
; RV32M-NEXT:    sub t1, t1, t5
; RV32M-NEXT:    and t5, t1, t4
; RV32M-NEXT:    srli t1, t1, 2
; RV32M-NEXT:    and t1, t1, t4
; RV32M-NEXT:    add t1, t5, t1
; RV32M-NEXT:    srli t4, t1, 4
; RV32M-NEXT:    add t1, t1, t4
; RV32M-NEXT:    and t1, t1, t2
; RV32M-NEXT:    mul t1, t1, t3
; RV32M-NEXT:    srli t1, t1, 24
; RV32M-NEXT:    addi t1, t1, 32
; RV32M-NEXT:    j .LBB1_14
; RV32M-NEXT:  .LBB1_13:
; RV32M-NEXT:    srli t1, s7, 1
; RV32M-NEXT:    or t1, s7, t1
; RV32M-NEXT:    srli s5, t1, 2
; RV32M-NEXT:    or t1, t1, s5
; RV32M-NEXT:    srli s5, t1, 4
; RV32M-NEXT:    or t1, t1, s5
; RV32M-NEXT:    srli s5, t1, 8
; RV32M-NEXT:    or t1, t1, s5
; RV32M-NEXT:    srli s5, t1, 16
; RV32M-NEXT:    or t1, t1, s5
; RV32M-NEXT:    not t1, t1
; RV32M-NEXT:    srli s5, t1, 1
; RV32M-NEXT:    and t5, s5, t5
; RV32M-NEXT:    sub t1, t1, t5
; RV32M-NEXT:    and t5, t1, t4
; RV32M-NEXT:    srli t1, t1, 2
; RV32M-NEXT:    and t1, t1, t4
; RV32M-NEXT:    add t1, t5, t1
; RV32M-NEXT:    srli t4, t1, 4
; RV32M-NEXT:    add t1, t1, t4
; RV32M-NEXT:    and t1, t1, t2
; RV32M-NEXT:    mul t1, t1, t3
; RV32M-NEXT:    srli t1, t1, 24
; RV32M-NEXT:  .LBB1_14: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    or t2, s0, t6
; RV32M-NEXT:    or t3, s2, s1
; RV32M-NEXT:    and t0, s3, t0
; RV32M-NEXT:    and a2, a2, a7
; RV32M-NEXT:    bnez s4, .LBB1_16
; RV32M-NEXT:  # %bb.15: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    mv t1, a1
; RV32M-NEXT:  .LBB1_16: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    seqz a1, t2
; RV32M-NEXT:    seqz a7, t3
; RV32M-NEXT:    sltu t2, a0, t1
; RV32M-NEXT:    sub t3, t0, a2
; RV32M-NEXT:    mv t4, t2
; RV32M-NEXT:    beq t0, a2, .LBB1_18
; RV32M-NEXT:  # %bb.17: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    sltu t4, t0, a2
; RV32M-NEXT:  .LBB1_18: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    sub t3, t3, t2
; RV32M-NEXT:    or a2, a1, a7
; RV32M-NEXT:    neg a1, t4
; RV32M-NEXT:    seqz t4, t4
; RV32M-NEXT:    addi t4, t4, -1
; RV32M-NEXT:    or a7, a1, t4
; RV32M-NEXT:    sub a0, a0, t1
; RV32M-NEXT:    beqz a7, .LBB1_20
; RV32M-NEXT:  # %bb.19: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    snez a7, a7
; RV32M-NEXT:    j .LBB1_21
; RV32M-NEXT:  .LBB1_20:
; RV32M-NEXT:    snez a7, t3
; RV32M-NEXT:    sltiu t0, a0, 128
; RV32M-NEXT:    xori t0, t0, 1
; RV32M-NEXT:    or a7, t0, a7
; RV32M-NEXT:  .LBB1_21: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    li s5, 127
; RV32M-NEXT:    or a2, a2, a7
; RV32M-NEXT:    addi a7, a2, -1
; RV32M-NEXT:    and a4, a7, s7
; RV32M-NEXT:    and a5, a7, s6
; RV32M-NEXT:    and a3, a7, s8
; RV32M-NEXT:    and t0, a7, s9
; RV32M-NEXT:    sw s10, 68(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw ra, 64(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s11, 60(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s8, 48(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s9, 44(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s6, 40(sp) # 4-byte Folded Spill
; RV32M-NEXT:    sw s7, 36(sp) # 4-byte Folded Spill
; RV32M-NEXT:    bnez a2, .LBB1_33
; RV32M-NEXT:  # %bb.22: # %_udiv-special-cases_udiv-special-cases
; RV32M-NEXT:    xori a2, a0, 127
; RV32M-NEXT:    or a2, a2, a1
; RV32M-NEXT:    or a7, t3, t4
; RV32M-NEXT:    or a2, a2, a7
; RV32M-NEXT:    beqz a2, .LBB1_33
; RV32M-NEXT:  # %bb.23: # %udiv-bb15
; RV32M-NEXT:    addi t2, a0, 1
; RV32M-NEXT:    sub a0, s5, a0
; RV32M-NEXT:    sw zero, 168(sp)
; RV32M-NEXT:    sw zero, 172(sp)
; RV32M-NEXT:    sw zero, 176(sp)
; RV32M-NEXT:    sw zero, 180(sp)
; RV32M-NEXT:    sw s9, 184(sp)
; RV32M-NEXT:    sw s8, 188(sp)
; RV32M-NEXT:    sw s6, 192(sp)
; RV32M-NEXT:    sw s7, 196(sp)
; RV32M-NEXT:    addi a2, sp, 184
; RV32M-NEXT:    seqz a3, t2
; RV32M-NEXT:    srli a4, a0, 3
; RV32M-NEXT:    andi a5, a0, 31
; RV32M-NEXT:    add t3, t3, a3
; RV32M-NEXT:    andi a4, a4, 12
; RV32M-NEXT:    xori a3, a5, 31
; RV32M-NEXT:    or a5, t2, t3
; RV32M-NEXT:    sub a2, a2, a4
; RV32M-NEXT:    seqz s1, a5
; RV32M-NEXT:    lw a4, 0(a2)
; RV32M-NEXT:    lw a5, 4(a2)
; RV32M-NEXT:    lw a7, 8(a2)
; RV32M-NEXT:    lw a2, 12(a2)
; RV32M-NEXT:    add s1, a1, s1
; RV32M-NEXT:    sltu t5, s1, a1
; RV32M-NEXT:    or a1, t2, s1
; RV32M-NEXT:    add t5, t4, t5
; RV32M-NEXT:    or t0, t3, t5
; RV32M-NEXT:    srli t1, a7, 1
; RV32M-NEXT:    srli t4, a5, 1
; RV32M-NEXT:    or a1, a1, t0
; RV32M-NEXT:    srli t0, a4, 1
; RV32M-NEXT:    srl t1, t1, a3
; RV32M-NEXT:    srl t4, t4, a3
; RV32M-NEXT:    srl a3, t0, a3
; RV32M-NEXT:    sll a2, a2, a0
; RV32M-NEXT:    or s4, a2, t1
; RV32M-NEXT:    sll a2, a7, a0
; RV32M-NEXT:    sll a5, a5, a0
; RV32M-NEXT:    or s2, a2, t4
; RV32M-NEXT:    or s3, a5, a3
; RV32M-NEXT:    sll t4, a4, a0
; RV32M-NEXT:    beqz a1, .LBB1_31
; RV32M-NEXT:  # %bb.24: # %udiv-preheader4
; RV32M-NEXT:    mv a0, s6
; RV32M-NEXT:    mv a2, s7
; RV32M-NEXT:    li s0, 0
; RV32M-NEXT:    li s5, 0
; RV32M-NEXT:    li s6, 0
; RV32M-NEXT:    li s7, 0
; RV32M-NEXT:    sw zero, 152(sp)
; RV32M-NEXT:    sw zero, 156(sp)
; RV32M-NEXT:    sw zero, 160(sp)
; RV32M-NEXT:    sw zero, 164(sp)
; RV32M-NEXT:    sw s9, 136(sp)
; RV32M-NEXT:    sw s8, 140(sp)
; RV32M-NEXT:    sw a0, 144(sp)
; RV32M-NEXT:    sw a2, 148(sp)
; RV32M-NEXT:    srli a0, t2, 3
; RV32M-NEXT:    addi a1, sp, 136
; RV32M-NEXT:    andi a0, a0, 12
; RV32M-NEXT:    add a0, a1, a0
; RV32M-NEXT:    lw a1, 4(a0)
; RV32M-NEXT:    lw a2, 8(a0)
; RV32M-NEXT:    lw a3, 12(a0)
; RV32M-NEXT:    lw a4, 0(a0)
; RV32M-NEXT:    andi a0, t2, 31
; RV32M-NEXT:    xori a0, a0, 31
; RV32M-NEXT:    slli a5, a3, 1
; RV32M-NEXT:    slli a7, a2, 1
; RV32M-NEXT:    slli t0, a1, 1
; RV32M-NEXT:    sll a5, a5, a0
; RV32M-NEXT:    sll a7, a7, a0
; RV32M-NEXT:    sll t0, t0, a0
; RV32M-NEXT:    seqz t1, a6
; RV32M-NEXT:    srl a0, a2, t2
; RV32M-NEXT:    or a0, a0, a5
; RV32M-NEXT:    or a2, a6, s11
; RV32M-NEXT:    sub s8, s11, t1
; RV32M-NEXT:    seqz a2, a2
; RV32M-NEXT:    srl a1, a1, t2
; RV32M-NEXT:    or s11, a1, a7
; RV32M-NEXT:    sub s9, ra, a2
; RV32M-NEXT:    sltu a1, ra, a2
; RV32M-NEXT:    sub s10, s10, a1
; RV32M-NEXT:    srl a1, a4, t2
; RV32M-NEXT:    srl t6, a3, t2
; RV32M-NEXT:    or t0, a1, t0
; RV32M-NEXT:    j .LBB1_26
; RV32M-NEXT:  .LBB1_25: # %udiv-do-while3
; RV32M-NEXT:    # in Loop: Header=BB1_26 Depth=1
; RV32M-NEXT:    srli a4, s2, 31
; RV32M-NEXT:    slli s4, s4, 1
; RV32M-NEXT:    sub a1, a7, a1
; RV32M-NEXT:    srli a7, s3, 31
; RV32M-NEXT:    slli s2, s2, 1
; RV32M-NEXT:    or a4, s4, a4
; RV32M-NEXT:    srli s4, t4, 31
; RV32M-NEXT:    slli s3, s3, 1
; RV32M-NEXT:    slli t4, t4, 1
; RV32M-NEXT:    or a7, s2, a7
; RV32M-NEXT:    lw a3, 68(sp) # 4-byte Folded Reload
; RV32M-NEXT:    and s2, s11, a3
; RV32M-NEXT:    or s3, s3, s4
; RV32M-NEXT:    lw a3, 64(sp) # 4-byte Folded Reload
; RV32M-NEXT:    and s4, s11, a3
; RV32M-NEXT:    or t4, s0, t4
; RV32M-NEXT:    sub a3, t1, s4
; RV32M-NEXT:    sltu t1, t1, s4
; RV32M-NEXT:    or s4, t2, t3
; RV32M-NEXT:    sub a5, a0, s2
; RV32M-NEXT:    seqz a0, t2
; RV32M-NEXT:    addi t2, t2, -1
; RV32M-NEXT:    andi s0, s11, 1
; RV32M-NEXT:    sub s11, a1, a2
; RV32M-NEXT:    seqz a1, s4
; RV32M-NEXT:    sub t3, t3, a0
; RV32M-NEXT:    or s3, s5, s3
; RV32M-NEXT:    or s2, s6, a7
; RV32M-NEXT:    or s4, s7, a4
; RV32M-NEXT:    sub a0, a3, t6
; RV32M-NEXT:    sltu a2, a3, t6
; RV32M-NEXT:    sub a3, a5, t1
; RV32M-NEXT:    sltu a4, s1, a1
; RV32M-NEXT:    sub s1, s1, a1
; RV32M-NEXT:    sub t6, a3, a2
; RV32M-NEXT:    sub t5, t5, a4
; RV32M-NEXT:    or a1, t3, t5
; RV32M-NEXT:    or a2, t2, s1
; RV32M-NEXT:    or a1, a2, a1
; RV32M-NEXT:    sub t0, ra, t0
; RV32M-NEXT:    li s5, 0
; RV32M-NEXT:    li s6, 0
; RV32M-NEXT:    li s7, 0
; RV32M-NEXT:    beqz a1, .LBB1_32
; RV32M-NEXT:  .LBB1_26: # %udiv-do-while3
; RV32M-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32M-NEXT:    srli a1, t0, 31
; RV32M-NEXT:    slli a2, s11, 1
; RV32M-NEXT:    slli t0, t0, 1
; RV32M-NEXT:    or a7, a2, a1
; RV32M-NEXT:    srli a1, s4, 31
; RV32M-NEXT:    or ra, t0, a1
; RV32M-NEXT:    beq s8, a7, .LBB1_28
; RV32M-NEXT:  # %bb.27: # %udiv-do-while3
; RV32M-NEXT:    # in Loop: Header=BB1_26 Depth=1
; RV32M-NEXT:    sltu a1, s8, a7
; RV32M-NEXT:    j .LBB1_29
; RV32M-NEXT:  .LBB1_28: # in Loop: Header=BB1_26 Depth=1
; RV32M-NEXT:    addi a1, a6, -1
; RV32M-NEXT:    sltu a1, a1, ra
; RV32M-NEXT:  .LBB1_29: # %udiv-do-while3
; RV32M-NEXT:    # in Loop: Header=BB1_26 Depth=1
; RV32M-NEXT:    srli a2, a0, 31
; RV32M-NEXT:    slli t6, t6, 1
; RV32M-NEXT:    srli t0, s11, 31
; RV32M-NEXT:    slli t1, a0, 1
; RV32M-NEXT:    or a0, t6, a2
; RV32M-NEXT:    or t1, t1, t0
; RV32M-NEXT:    sub a2, s9, t1
; RV32M-NEXT:    sltu t0, s9, t1
; RV32M-NEXT:    sub t6, s10, a0
; RV32M-NEXT:    sltu a1, a2, a1
; RV32M-NEXT:    sub a2, t6, t0
; RV32M-NEXT:    sub a2, a2, a1
; RV32M-NEXT:    srai s11, a2, 31
; RV32M-NEXT:    and t0, s11, a6
; RV32M-NEXT:    lw a1, 60(sp) # 4-byte Folded Reload
; RV32M-NEXT:    and a1, s11, a1
; RV32M-NEXT:    sltu a2, ra, t0
; RV32M-NEXT:    mv t6, a2
; RV32M-NEXT:    beq a7, a1, .LBB1_25
; RV32M-NEXT:  # %bb.30: # %udiv-do-while3
; RV32M-NEXT:    # in Loop: Header=BB1_26 Depth=1
; RV32M-NEXT:    sltu t6, a7, a1
; RV32M-NEXT:    j .LBB1_25
; RV32M-NEXT:  .LBB1_31:
; RV32M-NEXT:    li s0, 0
; RV32M-NEXT:  .LBB1_32: # %udiv-loop-exit2
; RV32M-NEXT:    srli a0, t4, 31
; RV32M-NEXT:    slli a1, s3, 1
; RV32M-NEXT:    srli a2, s3, 31
; RV32M-NEXT:    or a3, a1, a0
; RV32M-NEXT:    slli a0, s2, 1
; RV32M-NEXT:    srli a1, s2, 31
; RV32M-NEXT:    slli s4, s4, 1
; RV32M-NEXT:    slli t4, t4, 1
; RV32M-NEXT:    or a5, a0, a2
; RV32M-NEXT:    or a4, s4, a1
; RV32M-NEXT:    or t0, s0, t4
; RV32M-NEXT:    lw s10, 68(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw ra, 64(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s11, 60(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s8, 48(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s9, 44(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s6, 40(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s7, 36(sp) # 4-byte Folded Reload
; RV32M-NEXT:    li s5, 127
; RV32M-NEXT:  .LBB1_33: # %udiv-end1
; RV32M-NEXT:    sw a3, 24(sp) # 4-byte Folded Spill
; RV32M-NEXT:    lui a0, 349525
; RV32M-NEXT:    lui a1, 209715
; RV32M-NEXT:    lui a2, 61681
; RV32M-NEXT:    lui a3, 4112
; RV32M-NEXT:    addi s3, a0, 1365
; RV32M-NEXT:    addi s2, a1, 819
; RV32M-NEXT:    addi s1, a2, -241
; RV32M-NEXT:    addi s0, a3, 257
; RV32M-NEXT:    bnez s11, .LBB1_36
; RV32M-NEXT:  # %bb.34: # %udiv-end1
; RV32M-NEXT:    srli a0, a6, 1
; RV32M-NEXT:    or a0, a6, a0
; RV32M-NEXT:    srli a1, a0, 2
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 8
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 16
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a1, a0, 1
; RV32M-NEXT:    and a1, a1, s3
; RV32M-NEXT:    sub a0, a0, a1
; RV32M-NEXT:    and a1, a0, s2
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, s2
; RV32M-NEXT:    add a0, a1, a0
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    add a0, a0, a1
; RV32M-NEXT:    and a0, a0, s1
; RV32M-NEXT:    mul a0, a0, s0
; RV32M-NEXT:    srli a0, a0, 24
; RV32M-NEXT:    addi t2, a0, 32
; RV32M-NEXT:    or a7, ra, s10
; RV32M-NEXT:    beqz s10, .LBB1_37
; RV32M-NEXT:  .LBB1_35:
; RV32M-NEXT:    srli a0, s10, 1
; RV32M-NEXT:    or a0, s10, a0
; RV32M-NEXT:    srli a1, a0, 2
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 8
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 16
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a1, a0, 1
; RV32M-NEXT:    and a1, a1, s3
; RV32M-NEXT:    sub a0, a0, a1
; RV32M-NEXT:    and a1, a0, s2
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, s2
; RV32M-NEXT:    add a0, a1, a0
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    add a0, a0, a1
; RV32M-NEXT:    and a0, a0, s1
; RV32M-NEXT:    mul a1, a0, s0
; RV32M-NEXT:    srli a1, a1, 24
; RV32M-NEXT:    addi a0, t2, 64
; RV32M-NEXT:    beqz a7, .LBB1_38
; RV32M-NEXT:    j .LBB1_39
; RV32M-NEXT:  .LBB1_36:
; RV32M-NEXT:    srli a0, s11, 1
; RV32M-NEXT:    or a0, s11, a0
; RV32M-NEXT:    srli a1, a0, 2
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 8
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 16
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a1, a0, 1
; RV32M-NEXT:    and a1, a1, s3
; RV32M-NEXT:    sub a0, a0, a1
; RV32M-NEXT:    and a1, a0, s2
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, s2
; RV32M-NEXT:    add a0, a1, a0
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    add a0, a0, a1
; RV32M-NEXT:    and a0, a0, s1
; RV32M-NEXT:    mul a0, a0, s0
; RV32M-NEXT:    srli t2, a0, 24
; RV32M-NEXT:    or a7, ra, s10
; RV32M-NEXT:    bnez s10, .LBB1_35
; RV32M-NEXT:  .LBB1_37: # %udiv-end1
; RV32M-NEXT:    srli a0, ra, 1
; RV32M-NEXT:    or a0, ra, a0
; RV32M-NEXT:    srli a1, a0, 2
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 8
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    srli a1, a0, 16
; RV32M-NEXT:    or a0, a0, a1
; RV32M-NEXT:    not a0, a0
; RV32M-NEXT:    srli a1, a0, 1
; RV32M-NEXT:    and a1, a1, s3
; RV32M-NEXT:    sub a0, a0, a1
; RV32M-NEXT:    and a1, a0, s2
; RV32M-NEXT:    srli a0, a0, 2
; RV32M-NEXT:    and a0, a0, s2
; RV32M-NEXT:    add a0, a1, a0
; RV32M-NEXT:    srli a1, a0, 4
; RV32M-NEXT:    add a0, a0, a1
; RV32M-NEXT:    and a0, a0, s1
; RV32M-NEXT:    mul a0, a0, s0
; RV32M-NEXT:    srli a0, a0, 24
; RV32M-NEXT:    addi a1, a0, 32
; RV32M-NEXT:    addi a0, t2, 64
; RV32M-NEXT:    bnez a7, .LBB1_39
; RV32M-NEXT:  .LBB1_38: # %udiv-end1
; RV32M-NEXT:    mv a1, a0
; RV32M-NEXT:  .LBB1_39: # %udiv-end1
; RV32M-NEXT:    snez a7, a7
; RV32M-NEXT:    sw t0, 12(sp) # 4-byte Folded Spill
; RV32M-NEXT:    bnez s8, .LBB1_41
; RV32M-NEXT:  # %bb.40: # %udiv-end1
; RV32M-NEXT:    srli a2, s9, 1
; RV32M-NEXT:    or a2, s9, a2
; RV32M-NEXT:    srli a3, a2, 2
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    srli a3, a2, 4
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    srli a3, a2, 8
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    srli a3, a2, 16
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    not a2, a2
; RV32M-NEXT:    srli a3, a2, 1
; RV32M-NEXT:    and a3, a3, s3
; RV32M-NEXT:    sub a2, a2, a3
; RV32M-NEXT:    and a3, a2, s2
; RV32M-NEXT:    srli a2, a2, 2
; RV32M-NEXT:    and a2, a2, s2
; RV32M-NEXT:    add a2, a3, a2
; RV32M-NEXT:    srli a3, a2, 4
; RV32M-NEXT:    add a2, a2, a3
; RV32M-NEXT:    and a2, a2, s1
; RV32M-NEXT:    mul a2, a2, s0
; RV32M-NEXT:    srli a2, a2, 24
; RV32M-NEXT:    addi a2, a2, 32
; RV32M-NEXT:    j .LBB1_42
; RV32M-NEXT:  .LBB1_41:
; RV32M-NEXT:    srli a2, s8, 1
; RV32M-NEXT:    or a2, s8, a2
; RV32M-NEXT:    srli a3, a2, 2
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    srli a3, a2, 4
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    srli a3, a2, 8
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    srli a3, a2, 16
; RV32M-NEXT:    or a2, a2, a3
; RV32M-NEXT:    not a2, a2
; RV32M-NEXT:    srli a3, a2, 1
; RV32M-NEXT:    and a3, a3, s3
; RV32M-NEXT:    sub a2, a2, a3
; RV32M-NEXT:    and a3, a2, s2
; RV32M-NEXT:    srli a2, a2, 2
; RV32M-NEXT:    and a2, a2, s2
; RV32M-NEXT:    add a2, a3, a2
; RV32M-NEXT:    srli a3, a2, 4
; RV32M-NEXT:    add a2, a2, a3
; RV32M-NEXT:    and a2, a2, s1
; RV32M-NEXT:    mul a2, a2, s0
; RV32M-NEXT:    srli a2, a2, 24
; RV32M-NEXT:  .LBB1_42: # %udiv-end1
; RV32M-NEXT:    sw a4, 20(sp) # 4-byte Folded Spill
; RV32M-NEXT:    or t0, a6, ra
; RV32M-NEXT:    or t3, s11, s10
; RV32M-NEXT:    or t4, s9, s6
; RV32M-NEXT:    or t5, s8, s7
; RV32M-NEXT:    sltu t2, a0, t2
; RV32M-NEXT:    addi a7, a7, -1
; RV32M-NEXT:    addi a0, a2, 64
; RV32M-NEXT:    or t6, s6, s7
; RV32M-NEXT:    sltu s4, a0, a2
; RV32M-NEXT:    snez a2, t6
; RV32M-NEXT:    addi a2, a2, -1
; RV32M-NEXT:    bnez s7, .LBB1_44
; RV32M-NEXT:  # %bb.43: # %udiv-end1
; RV32M-NEXT:    srli a3, s6, 1
; RV32M-NEXT:    or a3, s6, a3
; RV32M-NEXT:    srli a4, a3, 2
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    srli a4, a3, 4
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    srli a4, a3, 8
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    srli a4, a3, 16
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    not a3, a3
; RV32M-NEXT:    srli a4, a3, 1
; RV32M-NEXT:    and a4, a4, s3
; RV32M-NEXT:    sub a3, a3, a4
; RV32M-NEXT:    and a4, a3, s2
; RV32M-NEXT:    srli a3, a3, 2
; RV32M-NEXT:    and a3, a3, s2
; RV32M-NEXT:    add a3, a4, a3
; RV32M-NEXT:    srli a4, a3, 4
; RV32M-NEXT:    add a3, a3, a4
; RV32M-NEXT:    and a3, a3, s1
; RV32M-NEXT:    mul a3, a3, s0
; RV32M-NEXT:    srli a3, a3, 24
; RV32M-NEXT:    addi t1, a3, 32
; RV32M-NEXT:    j .LBB1_45
; RV32M-NEXT:  .LBB1_44:
; RV32M-NEXT:    srli a3, s7, 1
; RV32M-NEXT:    or a3, s7, a3
; RV32M-NEXT:    srli a4, a3, 2
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    srli a4, a3, 4
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    srli a4, a3, 8
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    srli a4, a3, 16
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    not a3, a3
; RV32M-NEXT:    srli a4, a3, 1
; RV32M-NEXT:    and a4, a4, s3
; RV32M-NEXT:    sub a3, a3, a4
; RV32M-NEXT:    and a4, a3, s2
; RV32M-NEXT:    srli a3, a3, 2
; RV32M-NEXT:    and a3, a3, s2
; RV32M-NEXT:    add a3, a4, a3
; RV32M-NEXT:    srli a4, a3, 4
; RV32M-NEXT:    add a3, a3, a4
; RV32M-NEXT:    and a3, a3, s1
; RV32M-NEXT:    mul a3, a3, s0
; RV32M-NEXT:    srli t1, a3, 24
; RV32M-NEXT:  .LBB1_45: # %udiv-end1
; RV32M-NEXT:    or t0, t0, t3
; RV32M-NEXT:    or t3, t4, t5
; RV32M-NEXT:    and a7, a7, t2
; RV32M-NEXT:    and a2, a2, s4
; RV32M-NEXT:    bnez t6, .LBB1_47
; RV32M-NEXT:  # %bb.46: # %udiv-end1
; RV32M-NEXT:    mv t1, a0
; RV32M-NEXT:  .LBB1_47: # %udiv-end1
; RV32M-NEXT:    seqz a0, t0
; RV32M-NEXT:    seqz t0, t3
; RV32M-NEXT:    sltu t3, a1, t1
; RV32M-NEXT:    sub t4, a7, a2
; RV32M-NEXT:    mv t2, t3
; RV32M-NEXT:    beq a7, a2, .LBB1_49
; RV32M-NEXT:  # %bb.48: # %udiv-end1
; RV32M-NEXT:    sltu t2, a7, a2
; RV32M-NEXT:  .LBB1_49: # %udiv-end1
; RV32M-NEXT:    sub t6, t4, t3
; RV32M-NEXT:    or a2, a0, t0
; RV32M-NEXT:    neg a0, t2
; RV32M-NEXT:    seqz s2, t2
; RV32M-NEXT:    addi s2, s2, -1
; RV32M-NEXT:    or a7, a0, s2
; RV32M-NEXT:    sub t1, a1, t1
; RV32M-NEXT:    beqz a7, .LBB1_51
; RV32M-NEXT:  # %bb.50: # %udiv-end1
; RV32M-NEXT:    snez a1, a7
; RV32M-NEXT:    j .LBB1_52
; RV32M-NEXT:  .LBB1_51:
; RV32M-NEXT:    snez a1, t6
; RV32M-NEXT:    sltiu a3, t1, 128
; RV32M-NEXT:    xori a3, a3, 1
; RV32M-NEXT:    or a1, a3, a1
; RV32M-NEXT:  .LBB1_52: # %udiv-end1
; RV32M-NEXT:    or a3, a2, a1
; RV32M-NEXT:    addi a4, a3, -1
; RV32M-NEXT:    and a7, a4, s7
; RV32M-NEXT:    and a2, a4, s6
; RV32M-NEXT:    and a1, a4, s8
; RV32M-NEXT:    and t0, a4, s9
; RV32M-NEXT:    sw a5, 16(sp) # 4-byte Folded Spill
; RV32M-NEXT:    bnez a3, .LBB1_64
; RV32M-NEXT:  # %bb.53: # %udiv-end1
; RV32M-NEXT:    xori a3, t1, 127
; RV32M-NEXT:    or a3, a3, a0
; RV32M-NEXT:    or a4, t6, s2
; RV32M-NEXT:    or a3, a3, a4
; RV32M-NEXT:    beqz a3, .LBB1_64
; RV32M-NEXT:  # %bb.54: # %udiv-bb1
; RV32M-NEXT:    sw a6, 56(sp) # 4-byte Folded Spill
; RV32M-NEXT:    addi s0, t1, 1
; RV32M-NEXT:    sub a1, s5, t1
; RV32M-NEXT:    sw zero, 104(sp)
; RV32M-NEXT:    sw zero, 108(sp)
; RV32M-NEXT:    sw zero, 112(sp)
; RV32M-NEXT:    sw zero, 116(sp)
; RV32M-NEXT:    sw s9, 120(sp)
; RV32M-NEXT:    sw s8, 124(sp)
; RV32M-NEXT:    sw s6, 128(sp)
; RV32M-NEXT:    sw s7, 132(sp)
; RV32M-NEXT:    addi a2, sp, 120
; RV32M-NEXT:    seqz a3, s0
; RV32M-NEXT:    srli a4, a1, 3
; RV32M-NEXT:    andi a5, a1, 31
; RV32M-NEXT:    add t6, t6, a3
; RV32M-NEXT:    andi a4, a4, 12
; RV32M-NEXT:    xori a3, a5, 31
; RV32M-NEXT:    or a5, s0, t6
; RV32M-NEXT:    sub a2, a2, a4
; RV32M-NEXT:    seqz s4, a5
; RV32M-NEXT:    lw a4, 0(a2)
; RV32M-NEXT:    lw a5, 4(a2)
; RV32M-NEXT:    lw a6, 8(a2)
; RV32M-NEXT:    lw a2, 12(a2)
; RV32M-NEXT:    add s4, a0, s4
; RV32M-NEXT:    sltu a0, s4, a0
; RV32M-NEXT:    or a7, s0, s4
; RV32M-NEXT:    add s2, s2, a0
; RV32M-NEXT:    or a0, t6, s2
; RV32M-NEXT:    srli t0, a6, 1
; RV32M-NEXT:    srli t1, a5, 1
; RV32M-NEXT:    or a0, a7, a0
; RV32M-NEXT:    srli a7, a4, 1
; RV32M-NEXT:    srl t0, t0, a3
; RV32M-NEXT:    srl t1, t1, a3
; RV32M-NEXT:    srl a3, a7, a3
; RV32M-NEXT:    sll a2, a2, a1
; RV32M-NEXT:    mv a7, s7
; RV32M-NEXT:    or s7, a2, t0
; RV32M-NEXT:    sll a2, a6, a1
; RV32M-NEXT:    sll a5, a5, a1
; RV32M-NEXT:    or s5, a2, t1
; RV32M-NEXT:    mv a6, s6
; RV32M-NEXT:    or s6, a5, a3
; RV32M-NEXT:    sll s1, a4, a1
; RV32M-NEXT:    beqz a0, .LBB1_62
; RV32M-NEXT:  # %bb.55: # %udiv-preheader
; RV32M-NEXT:    mv a1, s8
; RV32M-NEXT:    mv a2, s9
; RV32M-NEXT:    li s3, 0
; RV32M-NEXT:    li s8, 0
; RV32M-NEXT:    li s9, 0
; RV32M-NEXT:    li s10, 0
; RV32M-NEXT:    sw zero, 88(sp)
; RV32M-NEXT:    sw zero, 92(sp)
; RV32M-NEXT:    sw zero, 96(sp)
; RV32M-NEXT:    sw zero, 100(sp)
; RV32M-NEXT:    sw a2, 72(sp)
; RV32M-NEXT:    sw a1, 76(sp)
; RV32M-NEXT:    sw a6, 80(sp)
; RV32M-NEXT:    sw a7, 84(sp)
; RV32M-NEXT:    srli a0, s0, 3
; RV32M-NEXT:    addi a1, sp, 72
; RV32M-NEXT:    andi a0, a0, 12
; RV32M-NEXT:    add a0, a1, a0
; RV32M-NEXT:    lw a1, 4(a0)
; RV32M-NEXT:    lw a2, 8(a0)
; RV32M-NEXT:    lw a3, 12(a0)
; RV32M-NEXT:    lw a4, 0(a0)
; RV32M-NEXT:    andi a0, s0, 31
; RV32M-NEXT:    xori a0, a0, 31
; RV32M-NEXT:    slli a5, a3, 1
; RV32M-NEXT:    slli a6, a2, 1
; RV32M-NEXT:    slli a7, a1, 1
; RV32M-NEXT:    sll a5, a5, a0
; RV32M-NEXT:    sll a6, a6, a0
; RV32M-NEXT:    sll a7, a7, a0
; RV32M-NEXT:    lw t1, 56(sp) # 4-byte Folded Reload
; RV32M-NEXT:    seqz t0, t1
; RV32M-NEXT:    srl a0, a2, s0
; RV32M-NEXT:    or a0, a0, a5
; RV32M-NEXT:    or a2, t1, s11
; RV32M-NEXT:    sub s11, s11, t0
; RV32M-NEXT:    seqz a2, a2
; RV32M-NEXT:    srl a1, a1, s0
; RV32M-NEXT:    or t3, a1, a6
; RV32M-NEXT:    mv a6, t1
; RV32M-NEXT:    mv a1, ra
; RV32M-NEXT:    sub ra, ra, a2
; RV32M-NEXT:    sltu a1, a1, a2
; RV32M-NEXT:    lw a2, 68(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sub t2, a2, a1
; RV32M-NEXT:    srl a1, a4, s0
; RV32M-NEXT:    srl t5, a3, s0
; RV32M-NEXT:    or t0, a1, a7
; RV32M-NEXT:    addi a1, t1, -1
; RV32M-NEXT:    sw a1, 52(sp) # 4-byte Folded Spill
; RV32M-NEXT:    j .LBB1_57
; RV32M-NEXT:  .LBB1_56: # %udiv-do-while
; RV32M-NEXT:    # in Loop: Header=BB1_57 Depth=1
; RV32M-NEXT:    srli a3, s5, 31
; RV32M-NEXT:    slli s7, s7, 1
; RV32M-NEXT:    sub a1, a7, a1
; RV32M-NEXT:    srli a4, s6, 31
; RV32M-NEXT:    slli s5, s5, 1
; RV32M-NEXT:    or a3, s7, a3
; RV32M-NEXT:    srli a5, s1, 31
; RV32M-NEXT:    slli s6, s6, 1
; RV32M-NEXT:    slli s1, s1, 1
; RV32M-NEXT:    or a4, s5, a4
; RV32M-NEXT:    lw a6, 68(sp) # 4-byte Folded Reload
; RV32M-NEXT:    and a7, t3, a6
; RV32M-NEXT:    or a5, s6, a5
; RV32M-NEXT:    lw a6, 64(sp) # 4-byte Folded Reload
; RV32M-NEXT:    and s5, t3, a6
; RV32M-NEXT:    or s1, s3, s1
; RV32M-NEXT:    sub a6, t1, s5
; RV32M-NEXT:    sltu t1, t1, s5
; RV32M-NEXT:    or s5, s0, t6
; RV32M-NEXT:    sub a7, a0, a7
; RV32M-NEXT:    seqz a0, s0
; RV32M-NEXT:    addi s0, s0, -1
; RV32M-NEXT:    andi s3, t3, 1
; RV32M-NEXT:    sub t3, a1, a2
; RV32M-NEXT:    seqz a1, s5
; RV32M-NEXT:    sub t6, t6, a0
; RV32M-NEXT:    or s6, s8, a5
; RV32M-NEXT:    or s5, s9, a4
; RV32M-NEXT:    or s7, s10, a3
; RV32M-NEXT:    sub a0, a6, t5
; RV32M-NEXT:    sltu a2, a6, t5
; RV32M-NEXT:    sub a3, a7, t1
; RV32M-NEXT:    sltu a4, s4, a1
; RV32M-NEXT:    sub s4, s4, a1
; RV32M-NEXT:    sub t5, a3, a2
; RV32M-NEXT:    sub s2, s2, a4
; RV32M-NEXT:    or a1, t6, s2
; RV32M-NEXT:    or a2, s0, s4
; RV32M-NEXT:    or a1, a2, a1
; RV32M-NEXT:    sub t0, t4, t0
; RV32M-NEXT:    li s8, 0
; RV32M-NEXT:    li s9, 0
; RV32M-NEXT:    li s10, 0
; RV32M-NEXT:    lw a6, 56(sp) # 4-byte Folded Reload
; RV32M-NEXT:    beqz a1, .LBB1_63
; RV32M-NEXT:  .LBB1_57: # %udiv-do-while
; RV32M-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32M-NEXT:    srli a1, t0, 31
; RV32M-NEXT:    slli a2, t3, 1
; RV32M-NEXT:    slli t0, t0, 1
; RV32M-NEXT:    or a7, a2, a1
; RV32M-NEXT:    srli a1, s7, 31
; RV32M-NEXT:    or t4, t0, a1
; RV32M-NEXT:    beq s11, a7, .LBB1_59
; RV32M-NEXT:  # %bb.58: # %udiv-do-while
; RV32M-NEXT:    # in Loop: Header=BB1_57 Depth=1
; RV32M-NEXT:    sltu a1, s11, a7
; RV32M-NEXT:    j .LBB1_60
; RV32M-NEXT:  .LBB1_59: # in Loop: Header=BB1_57 Depth=1
; RV32M-NEXT:    lw a1, 52(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sltu a1, a1, t4
; RV32M-NEXT:  .LBB1_60: # %udiv-do-while
; RV32M-NEXT:    # in Loop: Header=BB1_57 Depth=1
; RV32M-NEXT:    srli a2, a0, 31
; RV32M-NEXT:    slli t5, t5, 1
; RV32M-NEXT:    srli a3, t3, 31
; RV32M-NEXT:    slli a4, a0, 1
; RV32M-NEXT:    or a0, t5, a2
; RV32M-NEXT:    or t1, a4, a3
; RV32M-NEXT:    sub a2, ra, t1
; RV32M-NEXT:    sltu a3, ra, t1
; RV32M-NEXT:    sub a4, t2, a0
; RV32M-NEXT:    sltu a1, a2, a1
; RV32M-NEXT:    sub a4, a4, a3
; RV32M-NEXT:    sub a4, a4, a1
; RV32M-NEXT:    srai t3, a4, 31
; RV32M-NEXT:    and t0, t3, a6
; RV32M-NEXT:    lw a1, 60(sp) # 4-byte Folded Reload
; RV32M-NEXT:    and a1, t3, a1
; RV32M-NEXT:    sltu a2, t4, t0
; RV32M-NEXT:    mv t5, a2
; RV32M-NEXT:    beq a7, a1, .LBB1_56
; RV32M-NEXT:  # %bb.61: # %udiv-do-while
; RV32M-NEXT:    # in Loop: Header=BB1_57 Depth=1
; RV32M-NEXT:    sltu t5, a7, a1
; RV32M-NEXT:    j .LBB1_56
; RV32M-NEXT:  .LBB1_62:
; RV32M-NEXT:    li s3, 0
; RV32M-NEXT:    lw a6, 56(sp) # 4-byte Folded Reload
; RV32M-NEXT:  .LBB1_63: # %udiv-loop-exit
; RV32M-NEXT:    srli a0, s1, 31
; RV32M-NEXT:    slli a1, s6, 1
; RV32M-NEXT:    srli a2, s6, 31
; RV32M-NEXT:    or a1, a1, a0
; RV32M-NEXT:    slli a0, s5, 1
; RV32M-NEXT:    srli a3, s5, 31
; RV32M-NEXT:    slli s7, s7, 1
; RV32M-NEXT:    slli s1, s1, 1
; RV32M-NEXT:    or a2, a0, a2
; RV32M-NEXT:    or a7, s7, a3
; RV32M-NEXT:    or t0, s3, s1
; RV32M-NEXT:    lw ra, 64(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s11, 60(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s8, 48(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s9, 44(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s6, 40(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s7, 36(sp) # 4-byte Folded Reload
; RV32M-NEXT:  .LBB1_64: # %udiv-end
; RV32M-NEXT:    mulhu a3, a6, t0
; RV32M-NEXT:    mul a4, s11, t0
; RV32M-NEXT:    mulhu a5, s11, t0
; RV32M-NEXT:    mv a0, a6
; RV32M-NEXT:    mul a6, a6, a1
; RV32M-NEXT:    mulhu t1, a0, a1
; RV32M-NEXT:    mul t2, s11, a1
; RV32M-NEXT:    mul t3, t0, ra
; RV32M-NEXT:    mul t4, a2, a0
; RV32M-NEXT:    mulhu t5, s11, a1
; RV32M-NEXT:    mul t6, a2, s11
; RV32M-NEXT:    mulhu a2, a2, a0
; RV32M-NEXT:    mul a7, a7, a0
; RV32M-NEXT:    mul s0, a1, ra
; RV32M-NEXT:    mulhu a1, t0, ra
; RV32M-NEXT:    lw s1, 68(sp) # 4-byte Folded Reload
; RV32M-NEXT:    mul s1, t0, s1
; RV32M-NEXT:    mul a0, a0, t0
; RV32M-NEXT:    add a3, a4, a3
; RV32M-NEXT:    add t3, t4, t3
; RV32M-NEXT:    add a2, a2, t6
; RV32M-NEXT:    add s1, a1, s1
; RV32M-NEXT:    sltu a4, a3, a4
; RV32M-NEXT:    add a1, a6, a3
; RV32M-NEXT:    add a2, a2, a7
; RV32M-NEXT:    add s0, s1, s0
; RV32M-NEXT:    sltu a3, t3, t4
; RV32M-NEXT:    add a4, a5, a4
; RV32M-NEXT:    sltu a5, a1, a6
; RV32M-NEXT:    add a2, a2, s0
; RV32M-NEXT:    add a5, t1, a5
; RV32M-NEXT:    add a2, a2, a3
; RV32M-NEXT:    add a5, a4, a5
; RV32M-NEXT:    add a3, t2, a5
; RV32M-NEXT:    sltu a5, a5, a4
; RV32M-NEXT:    add a4, a3, t3
; RV32M-NEXT:    sltu a6, a3, t2
; RV32M-NEXT:    add a5, t5, a5
; RV32M-NEXT:    sltu a3, a4, a3
; RV32M-NEXT:    add a5, a5, a6
; RV32M-NEXT:    sltu a6, s6, a4
; RV32M-NEXT:    add a2, a5, a2
; RV32M-NEXT:    sub a3, s7, a3
; RV32M-NEXT:    sub a2, a3, a2
; RV32M-NEXT:    sltu a3, s9, a0
; RV32M-NEXT:    sub a2, a2, a6
; RV32M-NEXT:    mv a5, a3
; RV32M-NEXT:    beq s8, a1, .LBB1_66
; RV32M-NEXT:  # %bb.65: # %udiv-end
; RV32M-NEXT:    sltu a5, s8, a1
; RV32M-NEXT:  .LBB1_66: # %udiv-end
; RV32M-NEXT:    sub a4, s6, a4
; RV32M-NEXT:    sub a1, s8, a1
; RV32M-NEXT:    sub a0, s9, a0
; RV32M-NEXT:    lw a6, 28(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw a7, 12(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sw a7, 0(a6)
; RV32M-NEXT:    lw a7, 24(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sw a7, 4(a6)
; RV32M-NEXT:    lw a7, 16(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sw a7, 8(a6)
; RV32M-NEXT:    lw a7, 20(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sw a7, 12(a6)
; RV32M-NEXT:    sltu a6, a4, a5
; RV32M-NEXT:    sub a4, a4, a5
; RV32M-NEXT:    sub a1, a1, a3
; RV32M-NEXT:    sub a2, a2, a6
; RV32M-NEXT:    lw a3, 32(sp) # 4-byte Folded Reload
; RV32M-NEXT:    sw a0, 0(a3)
; RV32M-NEXT:    sw a1, 4(a3)
; RV32M-NEXT:    sw a4, 8(a3)
; RV32M-NEXT:    sw a2, 12(a3)
; RV32M-NEXT:    lw ra, 252(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s0, 248(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s1, 244(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s2, 240(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s3, 236(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s4, 232(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s5, 228(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s6, 224(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s7, 220(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s8, 216(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s9, 212(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s10, 208(sp) # 4-byte Folded Reload
; RV32M-NEXT:    lw s11, 204(sp) # 4-byte Folded Reload
; RV32M-NEXT:    .cfi_restore ra
; RV32M-NEXT:    .cfi_restore s0
; RV32M-NEXT:    .cfi_restore s1
; RV32M-NEXT:    .cfi_restore s2
; RV32M-NEXT:    .cfi_restore s3
; RV32M-NEXT:    .cfi_restore s4
; RV32M-NEXT:    .cfi_restore s5
; RV32M-NEXT:    .cfi_restore s6
; RV32M-NEXT:    .cfi_restore s7
; RV32M-NEXT:    .cfi_restore s8
; RV32M-NEXT:    .cfi_restore s9
; RV32M-NEXT:    .cfi_restore s10
; RV32M-NEXT:    .cfi_restore s11
; RV32M-NEXT:    addi sp, sp, 256
; RV32M-NEXT:    .cfi_def_cfa_offset 0
; RV32M-NEXT:    ret
  %q = udiv i128 %n, %d
  %r = urem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}
