; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv32 | FileCheck %s --check-prefix=RV32
; RUN: llc < %s -mtriple=riscv64 | FileCheck %s --check-prefix=RV64

; i256 add
define i256 @add_i256(i256 %a, i256 %b) nounwind {
; RV32-LABEL: add_i256:
; RV32:       # %bb.0:
; RV32-NEXT:    lw a3, 0(a2)
; RV32-NEXT:    lw a4, 4(a2)
; RV32-NEXT:    lw a6, 8(a2)
; RV32-NEXT:    lw a5, 12(a2)
; RV32-NEXT:    lw t2, 4(a1)
; RV32-NEXT:    lw a7, 0(a1)
; RV32-NEXT:    lw t1, 8(a1)
; RV32-NEXT:    lw t0, 12(a1)
; RV32-NEXT:    add a4, t2, a4
; RV32-NEXT:    add a3, a7, a3
; RV32-NEXT:    sltu a7, a3, a7
; RV32-NEXT:    add a4, a4, a7
; RV32-NEXT:    beq a4, t2, .LBB0_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    sltu a7, a4, t2
; RV32-NEXT:  .LBB0_2:
; RV32-NEXT:    add a6, t1, a6
; RV32-NEXT:    add t2, t0, a5
; RV32-NEXT:    add a5, a6, a7
; RV32-NEXT:    sltu t3, a6, t1
; RV32-NEXT:    sltu a6, a5, a6
; RV32-NEXT:    add t2, t2, t3
; RV32-NEXT:    add a6, t2, a6
; RV32-NEXT:    beq a6, t0, .LBB0_4
; RV32-NEXT:  # %bb.3:
; RV32-NEXT:    sltu t3, a6, t0
; RV32-NEXT:    j .LBB0_5
; RV32-NEXT:  .LBB0_4:
; RV32-NEXT:    sltu t3, a5, t1
; RV32-NEXT:  .LBB0_5:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    sw s0, 12(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw s0, 16(a2)
; RV32-NEXT:    lw t6, 20(a2)
; RV32-NEXT:    lw t5, 16(a1)
; RV32-NEXT:    lw t2, 20(a1)
; RV32-NEXT:    xor t1, a5, t1
; RV32-NEXT:    xor t0, a6, t0
; RV32-NEXT:    or t0, t1, t0
; RV32-NEXT:    beqz t0, .LBB0_7
; RV32-NEXT:  # %bb.6:
; RV32-NEXT:    mv a7, t3
; RV32-NEXT:  .LBB0_7:
; RV32-NEXT:    lw t4, 24(a2)
; RV32-NEXT:    lw t0, 28(a2)
; RV32-NEXT:    lw a2, 24(a1)
; RV32-NEXT:    lw t3, 28(a1)
; RV32-NEXT:    add s0, t5, s0
; RV32-NEXT:    add t6, t2, t6
; RV32-NEXT:    add a7, s0, a7
; RV32-NEXT:    sltu t1, s0, t5
; RV32-NEXT:    sltu t5, a7, s0
; RV32-NEXT:    add t6, t6, t1
; RV32-NEXT:    add a1, t6, t5
; RV32-NEXT:    sltu s0, a1, t6
; RV32-NEXT:    and t5, t5, s0
; RV32-NEXT:    beq t6, t2, .LBB0_9
; RV32-NEXT:  # %bb.8:
; RV32-NEXT:    sltu t1, t6, t2
; RV32-NEXT:  .LBB0_9:
; RV32-NEXT:    add t4, a2, t4
; RV32-NEXT:    add t0, t3, t0
; RV32-NEXT:    sw a3, 0(a0)
; RV32-NEXT:    sw a4, 4(a0)
; RV32-NEXT:    sw a5, 8(a0)
; RV32-NEXT:    sw a6, 12(a0)
; RV32-NEXT:    add t1, t4, t1
; RV32-NEXT:    sltu a2, t4, a2
; RV32-NEXT:    add t5, t1, t5
; RV32-NEXT:    sltu a3, t1, t4
; RV32-NEXT:    add a2, t0, a2
; RV32-NEXT:    sltu a4, t5, t1
; RV32-NEXT:    add a2, a2, a3
; RV32-NEXT:    add a2, a2, a4
; RV32-NEXT:    sw a7, 16(a0)
; RV32-NEXT:    sw a1, 20(a0)
; RV32-NEXT:    sw t5, 24(a0)
; RV32-NEXT:    sw a2, 28(a0)
; RV32-NEXT:    lw s0, 12(sp) # 4-byte Folded Reload
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    ret
;
; RV64-LABEL: add_i256:
; RV64:       # %bb.0:
; RV64-NEXT:    ld a5, 0(a2)
; RV64-NEXT:    ld t0, 8(a2)
; RV64-NEXT:    ld a4, 16(a2)
; RV64-NEXT:    ld a2, 24(a2)
; RV64-NEXT:    ld a7, 8(a1)
; RV64-NEXT:    ld t1, 0(a1)
; RV64-NEXT:    ld a3, 16(a1)
; RV64-NEXT:    ld a6, 24(a1)
; RV64-NEXT:    add t2, a7, t0
; RV64-NEXT:    add a1, t1, a5
; RV64-NEXT:    sltu t0, a1, t1
; RV64-NEXT:    add a5, t2, t0
; RV64-NEXT:    beq a5, a7, .LBB0_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    sltu t0, a5, a7
; RV64-NEXT:  .LBB0_2:
; RV64-NEXT:    add a4, a3, a4
; RV64-NEXT:    add a2, a6, a2
; RV64-NEXT:    add t0, a4, t0
; RV64-NEXT:    sltu a3, a4, a3
; RV64-NEXT:    sltu a4, t0, a4
; RV64-NEXT:    add a2, a2, a3
; RV64-NEXT:    add a2, a2, a4
; RV64-NEXT:    sd a1, 0(a0)
; RV64-NEXT:    sd a5, 8(a0)
; RV64-NEXT:    sd t0, 16(a0)
; RV64-NEXT:    sd a2, 24(a0)
; RV64-NEXT:    ret
  %r = add i256 %a, %b
  ret i256 %r
}

; i256 sub
define i256 @sub_i256(i256 %a, i256 %b) nounwind {
; RV32-LABEL: sub_i256:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -48
; RV32-NEXT:    sw s0, 44(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s1, 40(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s2, 36(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s3, 32(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s4, 28(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s5, 24(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s6, 20(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s7, 16(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s8, 12(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a3, 0(a2)
; RV32-NEXT:    lw a4, 4(a2)
; RV32-NEXT:    lw a7, 8(a2)
; RV32-NEXT:    lw t3, 12(a2)
; RV32-NEXT:    lw a5, 0(a1)
; RV32-NEXT:    lw t2, 8(a1)
; RV32-NEXT:    lw t5, 12(a1)
; RV32-NEXT:    lw t0, 4(a1)
; RV32-NEXT:    sltu a6, t2, a7
; RV32-NEXT:    mv s2, a6
; RV32-NEXT:    beq t5, t3, .LBB1_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    sltu s2, t5, t3
; RV32-NEXT:  .LBB1_2:
; RV32-NEXT:    sltu t1, a5, a3
; RV32-NEXT:    mv t4, t1
; RV32-NEXT:    beq t0, a4, .LBB1_4
; RV32-NEXT:  # %bb.3:
; RV32-NEXT:    sltu t4, t0, a4
; RV32-NEXT:  .LBB1_4:
; RV32-NEXT:    lw s7, 16(a2)
; RV32-NEXT:    lw s0, 20(a2)
; RV32-NEXT:    lw s8, 16(a1)
; RV32-NEXT:    lw s1, 20(a1)
; RV32-NEXT:    xor t6, t5, t3
; RV32-NEXT:    xor s3, t2, a7
; RV32-NEXT:    or s3, s3, t6
; RV32-NEXT:    mv t6, t4
; RV32-NEXT:    beqz s3, .LBB1_6
; RV32-NEXT:  # %bb.5:
; RV32-NEXT:    mv t6, s2
; RV32-NEXT:  .LBB1_6:
; RV32-NEXT:    lw s4, 24(a2)
; RV32-NEXT:    lw s3, 28(a2)
; RV32-NEXT:    lw s6, 24(a1)
; RV32-NEXT:    lw s5, 28(a1)
; RV32-NEXT:    sub s2, s8, s7
; RV32-NEXT:    sltu a2, s8, s7
; RV32-NEXT:    sub a1, s1, s0
; RV32-NEXT:    sltu s7, s2, t6
; RV32-NEXT:    sub s8, a1, a2
; RV32-NEXT:    snez a1, s8
; RV32-NEXT:    addi a1, a1, -1
; RV32-NEXT:    and a1, a1, s7
; RV32-NEXT:    beq s1, s0, .LBB1_8
; RV32-NEXT:  # %bb.7:
; RV32-NEXT:    sltu a2, s1, s0
; RV32-NEXT:  .LBB1_8:
; RV32-NEXT:    sub s0, s6, s4
; RV32-NEXT:    sltu s1, s6, s4
; RV32-NEXT:    sub s3, s5, s3
; RV32-NEXT:    sub s4, s8, s7
; RV32-NEXT:    sub t6, s2, t6
; RV32-NEXT:    sub t3, t5, t3
; RV32-NEXT:    sub a7, t2, a7
; RV32-NEXT:    sub a4, t0, a4
; RV32-NEXT:    sub a5, a5, a3
; RV32-NEXT:    sub a3, s0, a2
; RV32-NEXT:    sub t0, s3, s1
; RV32-NEXT:    sltu a2, s0, a2
; RV32-NEXT:    sub a6, t3, a6
; RV32-NEXT:    sltu t2, a7, t4
; RV32-NEXT:    sub a7, a7, t4
; RV32-NEXT:    sub a4, a4, t1
; RV32-NEXT:    sltu t1, a3, a1
; RV32-NEXT:    sub a2, t0, a2
; RV32-NEXT:    sub a3, a3, a1
; RV32-NEXT:    sub a1, a6, t2
; RV32-NEXT:    sub a2, a2, t1
; RV32-NEXT:    sw a5, 0(a0)
; RV32-NEXT:    sw a4, 4(a0)
; RV32-NEXT:    sw a7, 8(a0)
; RV32-NEXT:    sw a1, 12(a0)
; RV32-NEXT:    sw t6, 16(a0)
; RV32-NEXT:    sw s4, 20(a0)
; RV32-NEXT:    sw a3, 24(a0)
; RV32-NEXT:    sw a2, 28(a0)
; RV32-NEXT:    lw s0, 44(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s1, 40(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s2, 36(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s3, 32(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s4, 28(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s5, 24(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s6, 20(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s7, 16(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s8, 12(sp) # 4-byte Folded Reload
; RV32-NEXT:    addi sp, sp, 48
; RV32-NEXT:    ret
;
; RV64-LABEL: sub_i256:
; RV64:       # %bb.0:
; RV64-NEXT:    ld a3, 0(a2)
; RV64-NEXT:    ld a4, 8(a2)
; RV64-NEXT:    ld a5, 16(a2)
; RV64-NEXT:    ld a6, 24(a2)
; RV64-NEXT:    ld t0, 16(a1)
; RV64-NEXT:    ld a7, 24(a1)
; RV64-NEXT:    ld a2, 0(a1)
; RV64-NEXT:    ld a1, 8(a1)
; RV64-NEXT:    sltu t1, t0, a5
; RV64-NEXT:    sub a6, a7, a6
; RV64-NEXT:    sltu a7, a2, a3
; RV64-NEXT:    sub a6, a6, t1
; RV64-NEXT:    mv t1, a7
; RV64-NEXT:    beq a1, a4, .LBB1_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    sltu t1, a1, a4
; RV64-NEXT:  .LBB1_2:
; RV64-NEXT:    sub a5, t0, a5
; RV64-NEXT:    sub a1, a1, a4
; RV64-NEXT:    sub a2, a2, a3
; RV64-NEXT:    sltu a3, a5, t1
; RV64-NEXT:    sub a4, a5, t1
; RV64-NEXT:    sub a1, a1, a7
; RV64-NEXT:    sub a3, a6, a3
; RV64-NEXT:    sd a2, 0(a0)
; RV64-NEXT:    sd a1, 8(a0)
; RV64-NEXT:    sd a4, 16(a0)
; RV64-NEXT:    sd a3, 24(a0)
; RV64-NEXT:    ret
  %r = sub i256 %a, %b
  ret i256 %r
}

; i256 shift left by constant
define i256 @shl_i256_const(i256 %a) nounwind {
; RV32-LABEL: shl_i256_const:
; RV32:       # %bb.0:
; RV32-NEXT:    lw a2, 0(a1)
; RV32-NEXT:    lw a3, 4(a1)
; RV32-NEXT:    lw a4, 8(a1)
; RV32-NEXT:    lw a5, 12(a1)
; RV32-NEXT:    lw a6, 16(a1)
; RV32-NEXT:    lw a1, 20(a1)
; RV32-NEXT:    sw a4, 16(a0)
; RV32-NEXT:    sw a5, 20(a0)
; RV32-NEXT:    sw a6, 24(a0)
; RV32-NEXT:    sw a1, 28(a0)
; RV32-NEXT:    sw zero, 0(a0)
; RV32-NEXT:    sw zero, 4(a0)
; RV32-NEXT:    sw a2, 8(a0)
; RV32-NEXT:    sw a3, 12(a0)
; RV32-NEXT:    ret
;
; RV64-LABEL: shl_i256_const:
; RV64:       # %bb.0:
; RV64-NEXT:    ld a2, 0(a1)
; RV64-NEXT:    ld a3, 8(a1)
; RV64-NEXT:    ld a1, 16(a1)
; RV64-NEXT:    sd zero, 0(a0)
; RV64-NEXT:    sd a2, 8(a0)
; RV64-NEXT:    sd a3, 16(a0)
; RV64-NEXT:    sd a1, 24(a0)
; RV64-NEXT:    ret
  %r = shl i256 %a, 64
  ret i256 %r
}

; i256 shift left by variable
define i256 @shl_i256(i256 %a, i256 %b) nounwind {
; RV32-LABEL: shl_i256:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -80
; RV32-NEXT:    sw s0, 76(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s1, 72(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a2, 0(a2)
; RV32-NEXT:    lw a3, 0(a1)
; RV32-NEXT:    lw a4, 4(a1)
; RV32-NEXT:    lw a5, 8(a1)
; RV32-NEXT:    lw a6, 12(a1)
; RV32-NEXT:    lw a7, 16(a1)
; RV32-NEXT:    lw t0, 20(a1)
; RV32-NEXT:    lw t1, 24(a1)
; RV32-NEXT:    lw a1, 28(a1)
; RV32-NEXT:    sw zero, 24(sp)
; RV32-NEXT:    sw zero, 28(sp)
; RV32-NEXT:    sw zero, 32(sp)
; RV32-NEXT:    sw zero, 36(sp)
; RV32-NEXT:    sw zero, 8(sp)
; RV32-NEXT:    sw zero, 12(sp)
; RV32-NEXT:    sw zero, 16(sp)
; RV32-NEXT:    sw zero, 20(sp)
; RV32-NEXT:    addi t2, sp, 40
; RV32-NEXT:    sw a7, 56(sp)
; RV32-NEXT:    sw t0, 60(sp)
; RV32-NEXT:    sw t1, 64(sp)
; RV32-NEXT:    sw a1, 68(sp)
; RV32-NEXT:    sw a3, 40(sp)
; RV32-NEXT:    sw a4, 44(sp)
; RV32-NEXT:    sw a5, 48(sp)
; RV32-NEXT:    sw a6, 52(sp)
; RV32-NEXT:    srli a1, a2, 3
; RV32-NEXT:    andi a3, a2, 31
; RV32-NEXT:    andi a1, a1, 28
; RV32-NEXT:    xori a3, a3, 31
; RV32-NEXT:    sub a1, t2, a1
; RV32-NEXT:    lw a4, 0(a1)
; RV32-NEXT:    lw a5, 4(a1)
; RV32-NEXT:    lw a6, 8(a1)
; RV32-NEXT:    lw a7, 12(a1)
; RV32-NEXT:    lw t0, 16(a1)
; RV32-NEXT:    lw t1, 20(a1)
; RV32-NEXT:    lw t2, 24(a1)
; RV32-NEXT:    lw a1, 28(a1)
; RV32-NEXT:    sll t3, a5, a2
; RV32-NEXT:    srli t4, a4, 1
; RV32-NEXT:    sll t5, a6, a2
; RV32-NEXT:    srli a5, a5, 1
; RV32-NEXT:    sll t6, a7, a2
; RV32-NEXT:    srli a6, a6, 1
; RV32-NEXT:    sll s0, t0, a2
; RV32-NEXT:    srli a7, a7, 1
; RV32-NEXT:    sll s1, t1, a2
; RV32-NEXT:    srli t0, t0, 1
; RV32-NEXT:    sll a1, a1, a2
; RV32-NEXT:    sll a4, a4, a2
; RV32-NEXT:    sll a2, t2, a2
; RV32-NEXT:    srli t1, t1, 1
; RV32-NEXT:    srli t2, t2, 1
; RV32-NEXT:    srl t4, t4, a3
; RV32-NEXT:    srl a5, a5, a3
; RV32-NEXT:    srl a6, a6, a3
; RV32-NEXT:    srl a7, a7, a3
; RV32-NEXT:    srl t0, t0, a3
; RV32-NEXT:    srl t1, t1, a3
; RV32-NEXT:    srl a3, t2, a3
; RV32-NEXT:    or t2, t3, t4
; RV32-NEXT:    or a5, t5, a5
; RV32-NEXT:    or a6, t6, a6
; RV32-NEXT:    or a7, s0, a7
; RV32-NEXT:    or t0, s1, t0
; RV32-NEXT:    or a2, a2, t1
; RV32-NEXT:    or a1, a1, a3
; RV32-NEXT:    sw a7, 16(a0)
; RV32-NEXT:    sw t0, 20(a0)
; RV32-NEXT:    sw a2, 24(a0)
; RV32-NEXT:    sw a1, 28(a0)
; RV32-NEXT:    sw a4, 0(a0)
; RV32-NEXT:    sw t2, 4(a0)
; RV32-NEXT:    sw a5, 8(a0)
; RV32-NEXT:    sw a6, 12(a0)
; RV32-NEXT:    lw s0, 76(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s1, 72(sp) # 4-byte Folded Reload
; RV32-NEXT:    addi sp, sp, 80
; RV32-NEXT:    ret
;
; RV64-LABEL: shl_i256:
; RV64:       # %bb.0:
; RV64-NEXT:    addi sp, sp, -64
; RV64-NEXT:    ld a2, 0(a2)
; RV64-NEXT:    ld a3, 0(a1)
; RV64-NEXT:    ld a4, 8(a1)
; RV64-NEXT:    ld a5, 16(a1)
; RV64-NEXT:    ld a1, 24(a1)
; RV64-NEXT:    sd zero, 0(sp)
; RV64-NEXT:    sd zero, 8(sp)
; RV64-NEXT:    sd zero, 16(sp)
; RV64-NEXT:    sd zero, 24(sp)
; RV64-NEXT:    addi a6, sp, 32
; RV64-NEXT:    sd a3, 32(sp)
; RV64-NEXT:    sd a4, 40(sp)
; RV64-NEXT:    sd a5, 48(sp)
; RV64-NEXT:    sd a1, 56(sp)
; RV64-NEXT:    srli a1, a2, 3
; RV64-NEXT:    andi a3, a2, 63
; RV64-NEXT:    andi a1, a1, 24
; RV64-NEXT:    sub a1, a6, a1
; RV64-NEXT:    ld a4, 0(a1)
; RV64-NEXT:    ld a5, 8(a1)
; RV64-NEXT:    ld a6, 16(a1)
; RV64-NEXT:    ld a1, 24(a1)
; RV64-NEXT:    xori a3, a3, 63
; RV64-NEXT:    sll a7, a5, a2
; RV64-NEXT:    srli t0, a4, 1
; RV64-NEXT:    sll a1, a1, a2
; RV64-NEXT:    sll a4, a4, a2
; RV64-NEXT:    sll a2, a6, a2
; RV64-NEXT:    srli a5, a5, 1
; RV64-NEXT:    srli a6, a6, 1
; RV64-NEXT:    srl t0, t0, a3
; RV64-NEXT:    srl a5, a5, a3
; RV64-NEXT:    srl a3, a6, a3
; RV64-NEXT:    or a6, a7, t0
; RV64-NEXT:    or a2, a2, a5
; RV64-NEXT:    or a1, a1, a3
; RV64-NEXT:    sd a4, 0(a0)
; RV64-NEXT:    sd a6, 8(a0)
; RV64-NEXT:    sd a2, 16(a0)
; RV64-NEXT:    sd a1, 24(a0)
; RV64-NEXT:    addi sp, sp, 64
; RV64-NEXT:    ret
  %r = shl i256 %a, %b
  ret i256 %r
}

; i256 multiply
define i256 @mul_i256(i256 %a, i256 %b) nounwind {
; RV32-LABEL: mul_i256:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -240
; RV32-NEXT:    sw ra, 236(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s0, 232(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s1, 228(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s2, 224(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s3, 220(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s4, 216(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s5, 212(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s6, 208(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s7, 204(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s8, 200(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s9, 196(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s10, 192(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s11, 188(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a3, 16(a2)
; RV32-NEXT:    sw a3, 172(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a3, 20(a2)
; RV32-NEXT:    sw a3, 152(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a3, 24(a2)
; RV32-NEXT:    sw a3, 124(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a3, 28(a2)
; RV32-NEXT:    sw a3, 120(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a3, 16(a1)
; RV32-NEXT:    sw a3, 164(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a3, 20(a1)
; RV32-NEXT:    sw a3, 116(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a3, 24(a1)
; RV32-NEXT:    sw a3, 112(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a3, 28(a1)
; RV32-NEXT:    sw a3, 108(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw s9, 0(a2)
; RV32-NEXT:    lw s8, 4(a2)
; RV32-NEXT:    lw a3, 8(a2)
; RV32-NEXT:    sw a3, 156(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a2, 12(a2)
; RV32-NEXT:    sw a2, 176(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw s3, 0(a1)
; RV32-NEXT:    lw s2, 4(a1)
; RV32-NEXT:    lw s6, 8(a1)
; RV32-NEXT:    lw s7, 12(a1)
; RV32-NEXT:    sw a0, 136(sp) # 4-byte Folded Spill
; RV32-NEXT:    mv a0, s3
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    mv a2, s9
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    sw a0, 132(sp) # 4-byte Folded Spill
; RV32-NEXT:    mv s0, a1
; RV32-NEXT:    mv a0, s2
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    mv a2, s9
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    add s0, a0, s0
; RV32-NEXT:    sltu a0, s0, a0
; RV32-NEXT:    add s1, a1, a0
; RV32-NEXT:    sw s3, 180(sp) # 4-byte Folded Spill
; RV32-NEXT:    mv a0, s3
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    mv a2, s8
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    add s0, a0, s0
; RV32-NEXT:    sw s0, 128(sp) # 4-byte Folded Spill
; RV32-NEXT:    sltu a0, s0, a0
; RV32-NEXT:    add a0, a1, a0
; RV32-NEXT:    add s0, s1, a0
; RV32-NEXT:    sw s2, 184(sp) # 4-byte Folded Spill
; RV32-NEXT:    mv a0, s2
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    mv a2, s8
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    add s4, a0, s0
; RV32-NEXT:    sltu a2, s0, s1
; RV32-NEXT:    sltu a0, s4, a0
; RV32-NEXT:    add a1, a1, a2
; RV32-NEXT:    add s1, a1, a0
; RV32-NEXT:    mv a0, s6
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    mv a2, s9
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    mv s3, a0
; RV32-NEXT:    mv s5, a1
; RV32-NEXT:    mv a0, s7
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    sw s9, 160(sp) # 4-byte Folded Spill
; RV32-NEXT:    mv a2, s9
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    mv s2, a0
; RV32-NEXT:    mv s0, a1
; RV32-NEXT:    add s5, a0, s5
; RV32-NEXT:    sw s6, 144(sp) # 4-byte Folded Spill
; RV32-NEXT:    mv a0, s6
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    sw s8, 168(sp) # 4-byte Folded Spill
; RV32-NEXT:    mv a2, s8
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    add a2, a0, s5
; RV32-NEXT:    add s4, s3, s4
; RV32-NEXT:    add s1, a2, s1
; RV32-NEXT:    sltu s6, s4, s3
; RV32-NEXT:    add s8, s1, s6
; RV32-NEXT:    beq s8, a2, .LBB4_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    sltu s6, s8, a2
; RV32-NEXT:  .LBB4_2:
; RV32-NEXT:    sltu a3, s5, s2
; RV32-NEXT:    sltu a0, a2, a0
; RV32-NEXT:    add a3, s0, a3
; RV32-NEXT:    add a0, a1, a0
; RV32-NEXT:    sw a3, 140(sp) # 4-byte Folded Spill
; RV32-NEXT:    add s0, a3, a0
; RV32-NEXT:    sw s7, 148(sp) # 4-byte Folded Spill
; RV32-NEXT:    mv a0, s7
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    lw a2, 168(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    sw a1, 92(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s0, 96(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw a0, 88(sp) # 4-byte Folded Spill
; RV32-NEXT:    add a0, a0, s0
; RV32-NEXT:    sw a0, 84(sp) # 4-byte Folded Spill
; RV32-NEXT:    add s6, a0, s6
; RV32-NEXT:    lw s0, 180(sp) # 4-byte Folded Reload
; RV32-NEXT:    mv a0, s0
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    lw s1, 156(sp) # 4-byte Folded Reload
; RV32-NEXT:    mv a2, s1
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    mv s5, a0
; RV32-NEXT:    mv s7, a1
; RV32-NEXT:    lw a0, 184(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    mv a2, s1
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    mv s3, a0
; RV32-NEXT:    mv s2, a1
; RV32-NEXT:    add s7, a0, s7
; RV32-NEXT:    mv a0, s0
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    lw a2, 176(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    add a2, a0, s7
; RV32-NEXT:    add s4, s5, s4
; RV32-NEXT:    sw s4, 104(sp) # 4-byte Folded Spill
; RV32-NEXT:    sltu s0, s4, s5
; RV32-NEXT:    add a3, a2, s0
; RV32-NEXT:    add a3, a3, s8
; RV32-NEXT:    beq a3, a2, .LBB4_4
; RV32-NEXT:  # %bb.3:
; RV32-NEXT:    sltu s0, a3, a2
; RV32-NEXT:  .LBB4_4:
; RV32-NEXT:    sw a3, 100(sp) # 4-byte Folded Spill
; RV32-NEXT:    sltu a3, s7, s3
; RV32-NEXT:    sltu a0, a2, a0
; RV32-NEXT:    add s11, s2, a3
; RV32-NEXT:    add a0, a1, a0
; RV32-NEXT:    add s10, s11, a0
; RV32-NEXT:    lw a0, 184(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    lw a2, 176(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    mv s5, a0
; RV32-NEXT:    sw a1, 60(sp) # 4-byte Folded Spill
; RV32-NEXT:    add s2, a0, s10
; RV32-NEXT:    add s9, s2, s0
; RV32-NEXT:    add s0, s6, s9
; RV32-NEXT:    lw s8, 144(sp) # 4-byte Folded Reload
; RV32-NEXT:    mv a0, s8
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    lw s1, 156(sp) # 4-byte Folded Reload
; RV32-NEXT:    mv a2, s1
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    mv s3, a0
; RV32-NEXT:    sw a1, 64(sp) # 4-byte Folded Spill
; RV32-NEXT:    add s7, a0, s0
; RV32-NEXT:    lw a0, 160(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    lw a2, 164(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    mv s4, a0
; RV32-NEXT:    sw a1, 68(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a0, 172(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    lw a2, 180(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    sw a0, 80(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw a1, 76(sp) # 4-byte Folded Spill
; RV32-NEXT:    add a6, a0, s4
; RV32-NEXT:    sw a6, 72(sp) # 4-byte Folded Spill
; RV32-NEXT:    sltu a7, s0, s6
; RV32-NEXT:    lw a2, 84(sp) # 4-byte Folded Reload
; RV32-NEXT:    sltu a0, s6, a2
; RV32-NEXT:    lw a1, 88(sp) # 4-byte Folded Reload
; RV32-NEXT:    sltu a1, a2, a1
; RV32-NEXT:    lw a2, 140(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw a3, 96(sp) # 4-byte Folded Reload
; RV32-NEXT:    sltu a2, a3, a2
; RV32-NEXT:    sltu a3, s9, s2
; RV32-NEXT:    sltu a4, s2, s5
; RV32-NEXT:    sltu a5, s10, s11
; RV32-NEXT:    add a6, s7, a6
; RV32-NEXT:    lw t0, 92(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a2, t0, a2
; RV32-NEXT:    lw t0, 60(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a5, t0, a5
; RV32-NEXT:    sw a6, 96(sp) # 4-byte Folded Spill
; RV32-NEXT:    sltu s9, a6, s7
; RV32-NEXT:    add a1, a2, a1
; RV32-NEXT:    add a4, a5, a4
; RV32-NEXT:    add s4, a1, a0
; RV32-NEXT:    add a3, a4, a3
; RV32-NEXT:    add a3, s4, a3
; RV32-NEXT:    sw a7, 88(sp) # 4-byte Folded Spill
; RV32-NEXT:    add s11, a3, a7
; RV32-NEXT:    lw a0, 148(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    mv a2, s1
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    mv s1, a0
; RV32-NEXT:    sw a1, 84(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw s10, 64(sp) # 4-byte Folded Reload
; RV32-NEXT:    add s10, a0, s10
; RV32-NEXT:    mv a0, s8
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    lw a2, 176(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    mv s2, a0
; RV32-NEXT:    sw a1, 52(sp) # 4-byte Folded Spill
; RV32-NEXT:    add s5, a0, s10
; RV32-NEXT:    sltu s0, s7, s3
; RV32-NEXT:    add s6, s5, s0
; RV32-NEXT:    add s6, s6, s11
; RV32-NEXT:    lw a0, 168(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    lw a2, 164(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    sw a1, 48(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw a0, 32(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw s7, 68(sp) # 4-byte Folded Reload
; RV32-NEXT:    add s7, a0, s7
; RV32-NEXT:    lw a0, 160(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    lw s3, 116(sp) # 4-byte Folded Reload
; RV32-NEXT:    mv a2, s3
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    sw a1, 16(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s7, 28(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw a0, 12(sp) # 4-byte Folded Spill
; RV32-NEXT:    add s7, a0, s7
; RV32-NEXT:    lw a0, 152(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    lw a2, 180(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    sw a1, 68(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw a0, 64(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw s8, 76(sp) # 4-byte Folded Reload
; RV32-NEXT:    add s8, a0, s8
; RV32-NEXT:    lw a0, 172(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    lw a2, 184(sp) # 4-byte Folded Reload
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    sw s8, 60(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw a0, 56(sp) # 4-byte Folded Spill
; RV32-NEXT:    add a0, a0, s8
; RV32-NEXT:    sw a0, 76(sp) # 4-byte Folded Spill
; RV32-NEXT:    add a0, a0, s7
; RV32-NEXT:    lw a2, 80(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw a3, 72(sp) # 4-byte Folded Reload
; RV32-NEXT:    sltu a3, a3, a2
; RV32-NEXT:    add a4, a0, a3
; RV32-NEXT:    sw s9, 140(sp) # 4-byte Folded Spill
; RV32-NEXT:    add a0, a4, s9
; RV32-NEXT:    add a2, s6, a0
; RV32-NEXT:    sw a1, 44(sp) # 4-byte Folded Spill
; RV32-NEXT:    beq a2, s6, .LBB4_6
; RV32-NEXT:  # %bb.5:
; RV32-NEXT:    sltu a0, a2, s6
; RV32-NEXT:    sw a0, 140(sp) # 4-byte Folded Spill
; RV32-NEXT:  .LBB4_6:
; RV32-NEXT:    beq s6, s5, .LBB4_8
; RV32-NEXT:  # %bb.7:
; RV32-NEXT:    sltu s0, s6, s5
; RV32-NEXT:  .LBB4_8:
; RV32-NEXT:    sw a4, 72(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw a3, 80(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw a2, 92(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw s6, 88(sp) # 4-byte Folded Reload
; RV32-NEXT:    beq s11, s4, .LBB4_10
; RV32-NEXT:  # %bb.9:
; RV32-NEXT:    sltu s6, s11, s4
; RV32-NEXT:  .LBB4_10:
; RV32-NEXT:    sltu a0, s10, s1
; RV32-NEXT:    sltu a1, s5, s2
; RV32-NEXT:    lw a2, 84(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a0, a2, a0
; RV32-NEXT:    lw a2, 52(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a1, a2, a1
; RV32-NEXT:    sw a0, 24(sp) # 4-byte Folded Spill
; RV32-NEXT:    add s2, a0, a1
; RV32-NEXT:    lw s5, 148(sp) # 4-byte Folded Reload
; RV32-NEXT:    mv a0, s5
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    lw s1, 176(sp) # 4-byte Folded Reload
; RV32-NEXT:    mv a2, s1
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    sw a1, 84(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw a0, 52(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s2, 20(sp) # 4-byte Folded Spill
; RV32-NEXT:    add a0, a0, s2
; RV32-NEXT:    sw a0, 40(sp) # 4-byte Folded Spill
; RV32-NEXT:    add a0, a0, s6
; RV32-NEXT:    sw a0, 36(sp) # 4-byte Folded Spill
; RV32-NEXT:    add s0, a0, s0
; RV32-NEXT:    sw s0, 88(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a0, 164(sp) # 4-byte Folded Reload
; RV32-NEXT:    mv a1, s3
; RV32-NEXT:    lw a2, 156(sp) # 4-byte Folded Reload
; RV32-NEXT:    mv a3, s1
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    mv s0, a0
; RV32-NEXT:    sw a1, 164(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a0, 112(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw a1, 108(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw a2, 160(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s4, 168(sp) # 4-byte Folded Reload
; RV32-NEXT:    mv a3, s4
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    sw a1, 156(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw a0, 160(sp) # 4-byte Folded Spill
; RV32-NEXT:    add s1, a0, s0
; RV32-NEXT:    lw a0, 32(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw a1, 28(sp) # 4-byte Folded Reload
; RV32-NEXT:    sltu s6, a1, a0
; RV32-NEXT:    lw a0, 12(sp) # 4-byte Folded Reload
; RV32-NEXT:    sltu a0, s7, a0
; RV32-NEXT:    lw a1, 48(sp) # 4-byte Folded Reload
; RV32-NEXT:    add s6, a1, s6
; RV32-NEXT:    lw a1, 16(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a0, a1, a0
; RV32-NEXT:    add s8, s6, a0
; RV32-NEXT:    mv a0, s4
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    mv a2, s3
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    sw a1, 116(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw a0, 176(sp) # 4-byte Folded Spill
; RV32-NEXT:    add s0, a0, s8
; RV32-NEXT:    sw s1, 168(sp) # 4-byte Folded Spill
; RV32-NEXT:    add s1, s0, s1
; RV32-NEXT:    lw a0, 180(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s9, 184(sp) # 4-byte Folded Reload
; RV32-NEXT:    mv a1, s9
; RV32-NEXT:    lw a2, 124(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw a3, 120(sp) # 4-byte Folded Reload
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    mv s4, a0
; RV32-NEXT:    sw a1, 180(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a0, 144(sp) # 4-byte Folded Reload
; RV32-NEXT:    mv a1, s5
; RV32-NEXT:    lw a2, 172(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s5, 152(sp) # 4-byte Folded Reload
; RV32-NEXT:    mv a3, s5
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    mv s10, a0
; RV32-NEXT:    mv s11, a1
; RV32-NEXT:    add s4, a0, s4
; RV32-NEXT:    lw a0, 64(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw a1, 60(sp) # 4-byte Folded Reload
; RV32-NEXT:    sltu s7, a1, a0
; RV32-NEXT:    lw s2, 76(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw a0, 56(sp) # 4-byte Folded Reload
; RV32-NEXT:    sltu a0, s2, a0
; RV32-NEXT:    lw a1, 68(sp) # 4-byte Folded Reload
; RV32-NEXT:    add s7, a1, s7
; RV32-NEXT:    lw a1, 44(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a0, a1, a0
; RV32-NEXT:    add s3, s7, a0
; RV32-NEXT:    mv a0, s5
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    mv a2, s9
; RV32-NEXT:    li a3, 0
; RV32-NEXT:    call __muldi3
; RV32-NEXT:    add a7, a0, s3
; RV32-NEXT:    add a6, a7, s4
; RV32-NEXT:    add a2, a6, s1
; RV32-NEXT:    lw t3, 80(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw a4, 72(sp) # 4-byte Folded Reload
; RV32-NEXT:    beq a4, s2, .LBB4_12
; RV32-NEXT:  # %bb.11:
; RV32-NEXT:    sltu t3, a4, s2
; RV32-NEXT:  .LBB4_12:
; RV32-NEXT:    lw a3, 24(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw a4, 20(sp) # 4-byte Folded Reload
; RV32-NEXT:    sltu a4, a4, a3
; RV32-NEXT:    sltu a3, s8, s6
; RV32-NEXT:    sltu t0, s3, s7
; RV32-NEXT:    lw a5, 164(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw t1, 156(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a5, t1, a5
; RV32-NEXT:    lw t1, 160(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw t2, 168(sp) # 4-byte Folded Reload
; RV32-NEXT:    sltu t1, t2, t1
; RV32-NEXT:    lw t2, 116(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a3, t2, a3
; RV32-NEXT:    lw t2, 180(sp) # 4-byte Folded Reload
; RV32-NEXT:    add s11, s11, t2
; RV32-NEXT:    sltu t2, s4, s10
; RV32-NEXT:    add a1, a1, t0
; RV32-NEXT:    add t0, a2, t3
; RV32-NEXT:    lw t3, 52(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw t4, 40(sp) # 4-byte Folded Reload
; RV32-NEXT:    sltu t3, t4, t3
; RV32-NEXT:    lw t5, 36(sp) # 4-byte Folded Reload
; RV32-NEXT:    sltu t4, t5, t4
; RV32-NEXT:    lw s3, 88(sp) # 4-byte Folded Reload
; RV32-NEXT:    sltu t5, s3, t5
; RV32-NEXT:    lw t6, 176(sp) # 4-byte Folded Reload
; RV32-NEXT:    sltu t6, s0, t6
; RV32-NEXT:    sltu s0, s1, s0
; RV32-NEXT:    sltu a0, a7, a0
; RV32-NEXT:    sltu a7, a6, a7
; RV32-NEXT:    sltu a6, a2, a6
; RV32-NEXT:    lw s2, 136(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s1, 132(sp) # 4-byte Folded Reload
; RV32-NEXT:    sw s1, 0(s2)
; RV32-NEXT:    lw s1, 128(sp) # 4-byte Folded Reload
; RV32-NEXT:    sw s1, 4(s2)
; RV32-NEXT:    lw s1, 104(sp) # 4-byte Folded Reload
; RV32-NEXT:    sw s1, 8(s2)
; RV32-NEXT:    lw s1, 100(sp) # 4-byte Folded Reload
; RV32-NEXT:    sw s1, 12(s2)
; RV32-NEXT:    add s1, s3, t0
; RV32-NEXT:    lw s4, 84(sp) # 4-byte Folded Reload
; RV32-NEXT:    add a4, s4, a4
; RV32-NEXT:    sltu a2, t0, a2
; RV32-NEXT:    add a5, a5, t1
; RV32-NEXT:    add t2, s11, t2
; RV32-NEXT:    lw t0, 140(sp) # 4-byte Folded Reload
; RV32-NEXT:    add t0, s1, t0
; RV32-NEXT:    sltu t1, s1, s3
; RV32-NEXT:    add a4, a4, t3
; RV32-NEXT:    add a3, a3, t6
; RV32-NEXT:    add a0, a1, a0
; RV32-NEXT:    add a2, a6, a2
; RV32-NEXT:    sltu a1, t0, s1
; RV32-NEXT:    add a4, a4, t4
; RV32-NEXT:    add a3, a3, a5
; RV32-NEXT:    add a0, a0, t2
; RV32-NEXT:    add a4, a4, t5
; RV32-NEXT:    add a3, a3, s0
; RV32-NEXT:    add a0, a0, a7
; RV32-NEXT:    add a0, a0, a3
; RV32-NEXT:    add a0, a0, a2
; RV32-NEXT:    add a0, a4, a0
; RV32-NEXT:    add a0, a0, t1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a1, 96(sp) # 4-byte Folded Reload
; RV32-NEXT:    sw a1, 16(s2)
; RV32-NEXT:    lw a1, 92(sp) # 4-byte Folded Reload
; RV32-NEXT:    sw a1, 20(s2)
; RV32-NEXT:    sw t0, 24(s2)
; RV32-NEXT:    sw a0, 28(s2)
; RV32-NEXT:    lw ra, 236(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s0, 232(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s1, 228(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s2, 224(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s3, 220(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s4, 216(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s5, 212(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s6, 208(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s7, 204(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s8, 200(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s9, 196(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s10, 192(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s11, 188(sp) # 4-byte Folded Reload
; RV32-NEXT:    addi sp, sp, 240
; RV32-NEXT:    ret
;
; RV64-LABEL: mul_i256:
; RV64:       # %bb.0:
; RV64-NEXT:    addi sp, sp, -80
; RV64-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s1, 56(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s2, 48(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s3, 40(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s4, 32(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s5, 24(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s6, 16(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s7, 8(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s8, 0(sp) # 8-byte Folded Spill
; RV64-NEXT:    ld s3, 0(a2)
; RV64-NEXT:    ld s1, 8(a2)
; RV64-NEXT:    ld s4, 16(a2)
; RV64-NEXT:    ld s5, 24(a2)
; RV64-NEXT:    ld s6, 0(a1)
; RV64-NEXT:    ld s2, 8(a1)
; RV64-NEXT:    ld a2, 16(a1)
; RV64-NEXT:    ld a3, 24(a1)
; RV64-NEXT:    mv s0, a0
; RV64-NEXT:    mv a0, s3
; RV64-NEXT:    mv a1, s1
; RV64-NEXT:    call __multi3
; RV64-NEXT:    mv s7, a0
; RV64-NEXT:    mv s8, a1
; RV64-NEXT:    mv a0, s4
; RV64-NEXT:    mv a1, s5
; RV64-NEXT:    mv a2, s6
; RV64-NEXT:    mv a3, s2
; RV64-NEXT:    call __multi3
; RV64-NEXT:    add a1, a1, s8
; RV64-NEXT:    add s7, a0, s7
; RV64-NEXT:    sltu a0, s7, a0
; RV64-NEXT:    add s8, a1, a0
; RV64-NEXT:    mv a0, s6
; RV64-NEXT:    li a1, 0
; RV64-NEXT:    mv a2, s3
; RV64-NEXT:    li a3, 0
; RV64-NEXT:    call __multi3
; RV64-NEXT:    mv s4, a0
; RV64-NEXT:    mv s5, a1
; RV64-NEXT:    mv a0, s2
; RV64-NEXT:    li a1, 0
; RV64-NEXT:    mv a2, s3
; RV64-NEXT:    li a3, 0
; RV64-NEXT:    call __multi3
; RV64-NEXT:    add s5, a0, s5
; RV64-NEXT:    sltu a0, s5, a0
; RV64-NEXT:    add s3, a1, a0
; RV64-NEXT:    mv a0, s6
; RV64-NEXT:    li a1, 0
; RV64-NEXT:    mv a2, s1
; RV64-NEXT:    li a3, 0
; RV64-NEXT:    call __multi3
; RV64-NEXT:    add s5, a0, s5
; RV64-NEXT:    sltu a0, s5, a0
; RV64-NEXT:    add a0, a1, a0
; RV64-NEXT:    add s6, s3, a0
; RV64-NEXT:    mv a0, s2
; RV64-NEXT:    li a1, 0
; RV64-NEXT:    mv a2, s1
; RV64-NEXT:    li a3, 0
; RV64-NEXT:    call __multi3
; RV64-NEXT:    add a2, a0, s6
; RV64-NEXT:    sltu a3, s6, s3
; RV64-NEXT:    sltu a0, a2, a0
; RV64-NEXT:    add a1, a1, a3
; RV64-NEXT:    add s7, a2, s7
; RV64-NEXT:    add a0, a1, a0
; RV64-NEXT:    sltu a1, s7, a2
; RV64-NEXT:    add a0, a0, s8
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sd s4, 0(s0)
; RV64-NEXT:    sd s5, 8(s0)
; RV64-NEXT:    sd s7, 16(s0)
; RV64-NEXT:    sd a0, 24(s0)
; RV64-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s1, 56(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s2, 48(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s3, 40(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s4, 32(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s5, 24(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s6, 16(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s7, 8(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s8, 0(sp) # 8-byte Folded Reload
; RV64-NEXT:    addi sp, sp, 80
; RV64-NEXT:    ret
  %r = mul i256 %a, %b
  ret i256 %r
}

; i256 bitwise and
define i256 @and_i256(i256 %a, i256 %b) nounwind {
; RV32-LABEL: and_i256:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    sw s0, 12(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s1, 8(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a3, 16(a2)
; RV32-NEXT:    lw a4, 20(a2)
; RV32-NEXT:    lw a5, 24(a2)
; RV32-NEXT:    lw a6, 28(a2)
; RV32-NEXT:    lw a7, 16(a1)
; RV32-NEXT:    lw t0, 20(a1)
; RV32-NEXT:    lw t1, 24(a1)
; RV32-NEXT:    lw t2, 28(a1)
; RV32-NEXT:    lw t3, 0(a2)
; RV32-NEXT:    lw t4, 4(a2)
; RV32-NEXT:    lw t5, 8(a2)
; RV32-NEXT:    lw a2, 12(a2)
; RV32-NEXT:    lw t6, 0(a1)
; RV32-NEXT:    lw s0, 4(a1)
; RV32-NEXT:    lw s1, 8(a1)
; RV32-NEXT:    lw a1, 12(a1)
; RV32-NEXT:    and t3, t6, t3
; RV32-NEXT:    and t4, s0, t4
; RV32-NEXT:    and t5, s1, t5
; RV32-NEXT:    and a1, a1, a2
; RV32-NEXT:    and a2, a7, a3
; RV32-NEXT:    and a3, t0, a4
; RV32-NEXT:    and a4, t1, a5
; RV32-NEXT:    and a5, t2, a6
; RV32-NEXT:    sw a2, 16(a0)
; RV32-NEXT:    sw a3, 20(a0)
; RV32-NEXT:    sw a4, 24(a0)
; RV32-NEXT:    sw a5, 28(a0)
; RV32-NEXT:    sw t3, 0(a0)
; RV32-NEXT:    sw t4, 4(a0)
; RV32-NEXT:    sw t5, 8(a0)
; RV32-NEXT:    sw a1, 12(a0)
; RV32-NEXT:    lw s0, 12(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s1, 8(sp) # 4-byte Folded Reload
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    ret
;
; RV64-LABEL: and_i256:
; RV64:       # %bb.0:
; RV64-NEXT:    ld a3, 0(a2)
; RV64-NEXT:    ld a4, 8(a2)
; RV64-NEXT:    ld a5, 16(a2)
; RV64-NEXT:    ld a2, 24(a2)
; RV64-NEXT:    ld a6, 0(a1)
; RV64-NEXT:    ld a7, 8(a1)
; RV64-NEXT:    ld t0, 16(a1)
; RV64-NEXT:    ld a1, 24(a1)
; RV64-NEXT:    and a3, a6, a3
; RV64-NEXT:    and a4, a7, a4
; RV64-NEXT:    and a5, t0, a5
; RV64-NEXT:    and a1, a1, a2
; RV64-NEXT:    sd a3, 0(a0)
; RV64-NEXT:    sd a4, 8(a0)
; RV64-NEXT:    sd a5, 16(a0)
; RV64-NEXT:    sd a1, 24(a0)
; RV64-NEXT:    ret
  %r = and i256 %a, %b
  ret i256 %r
}

; i256 bitwise xor
define i256 @xor_i256(i256 %a, i256 %b) nounwind {
; RV32-LABEL: xor_i256:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    sw s0, 12(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s1, 8(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a3, 16(a2)
; RV32-NEXT:    lw a4, 20(a2)
; RV32-NEXT:    lw a5, 24(a2)
; RV32-NEXT:    lw a6, 28(a2)
; RV32-NEXT:    lw a7, 16(a1)
; RV32-NEXT:    lw t0, 20(a1)
; RV32-NEXT:    lw t1, 24(a1)
; RV32-NEXT:    lw t2, 28(a1)
; RV32-NEXT:    lw t3, 0(a2)
; RV32-NEXT:    lw t4, 4(a2)
; RV32-NEXT:    lw t5, 8(a2)
; RV32-NEXT:    lw a2, 12(a2)
; RV32-NEXT:    lw t6, 0(a1)
; RV32-NEXT:    lw s0, 4(a1)
; RV32-NEXT:    lw s1, 8(a1)
; RV32-NEXT:    lw a1, 12(a1)
; RV32-NEXT:    xor t3, t6, t3
; RV32-NEXT:    xor t4, s0, t4
; RV32-NEXT:    xor t5, s1, t5
; RV32-NEXT:    xor a1, a1, a2
; RV32-NEXT:    xor a2, a7, a3
; RV32-NEXT:    xor a3, t0, a4
; RV32-NEXT:    xor a4, t1, a5
; RV32-NEXT:    xor a5, t2, a6
; RV32-NEXT:    sw a2, 16(a0)
; RV32-NEXT:    sw a3, 20(a0)
; RV32-NEXT:    sw a4, 24(a0)
; RV32-NEXT:    sw a5, 28(a0)
; RV32-NEXT:    sw t3, 0(a0)
; RV32-NEXT:    sw t4, 4(a0)
; RV32-NEXT:    sw t5, 8(a0)
; RV32-NEXT:    sw a1, 12(a0)
; RV32-NEXT:    lw s0, 12(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s1, 8(sp) # 4-byte Folded Reload
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    ret
;
; RV64-LABEL: xor_i256:
; RV64:       # %bb.0:
; RV64-NEXT:    ld a3, 0(a2)
; RV64-NEXT:    ld a4, 8(a2)
; RV64-NEXT:    ld a5, 16(a2)
; RV64-NEXT:    ld a2, 24(a2)
; RV64-NEXT:    ld a6, 0(a1)
; RV64-NEXT:    ld a7, 8(a1)
; RV64-NEXT:    ld t0, 16(a1)
; RV64-NEXT:    ld a1, 24(a1)
; RV64-NEXT:    xor a3, a6, a3
; RV64-NEXT:    xor a4, a7, a4
; RV64-NEXT:    xor a5, t0, a5
; RV64-NEXT:    xor a1, a1, a2
; RV64-NEXT:    sd a3, 0(a0)
; RV64-NEXT:    sd a4, 8(a0)
; RV64-NEXT:    sd a5, 16(a0)
; RV64-NEXT:    sd a1, 24(a0)
; RV64-NEXT:    ret
  %r = xor i256 %a, %b
  ret i256 %r
}

; i256 popcount
define i256 @ctpop_i256(i256 %a) nounwind {
; RV32-LABEL: ctpop_i256:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    sw s0, 12(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s1, 8(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s2, 4(sp) # 4-byte Folded Spill
; RV32-NEXT:    lw a3, 16(a1)
; RV32-NEXT:    lw a5, 20(a1)
; RV32-NEXT:    lw a7, 24(a1)
; RV32-NEXT:    lw t0, 28(a1)
; RV32-NEXT:    lw a2, 0(a1)
; RV32-NEXT:    lw a4, 4(a1)
; RV32-NEXT:    lw a6, 8(a1)
; RV32-NEXT:    lw a1, 12(a1)
; RV32-NEXT:    lui t1, 349525
; RV32-NEXT:    addi t1, t1, 1365
; RV32-NEXT:    srli t2, t0, 1
; RV32-NEXT:    srli t3, a7, 1
; RV32-NEXT:    srli t4, a5, 1
; RV32-NEXT:    srli t5, a3, 1
; RV32-NEXT:    srli t6, a1, 1
; RV32-NEXT:    srli s0, a6, 1
; RV32-NEXT:    srli s1, a4, 1
; RV32-NEXT:    srli s2, a2, 1
; RV32-NEXT:    and t2, t2, t1
; RV32-NEXT:    and t3, t3, t1
; RV32-NEXT:    and t4, t4, t1
; RV32-NEXT:    and t5, t5, t1
; RV32-NEXT:    and t6, t6, t1
; RV32-NEXT:    and s0, s0, t1
; RV32-NEXT:    and s1, s1, t1
; RV32-NEXT:    and t1, s2, t1
; RV32-NEXT:    lui s2, 209715
; RV32-NEXT:    addi s2, s2, 819
; RV32-NEXT:    sub t0, t0, t2
; RV32-NEXT:    sub a7, a7, t3
; RV32-NEXT:    sub a5, a5, t4
; RV32-NEXT:    sub a3, a3, t5
; RV32-NEXT:    sub a1, a1, t6
; RV32-NEXT:    sub a6, a6, s0
; RV32-NEXT:    sub a4, a4, s1
; RV32-NEXT:    sub a2, a2, t1
; RV32-NEXT:    and t1, t0, s2
; RV32-NEXT:    srli t0, t0, 2
; RV32-NEXT:    and t2, a7, s2
; RV32-NEXT:    srli a7, a7, 2
; RV32-NEXT:    and t3, a5, s2
; RV32-NEXT:    srli a5, a5, 2
; RV32-NEXT:    and t4, a3, s2
; RV32-NEXT:    srli a3, a3, 2
; RV32-NEXT:    and t5, a1, s2
; RV32-NEXT:    srli a1, a1, 2
; RV32-NEXT:    and t6, a6, s2
; RV32-NEXT:    srli a6, a6, 2
; RV32-NEXT:    and s0, a4, s2
; RV32-NEXT:    srli a4, a4, 2
; RV32-NEXT:    and s1, a2, s2
; RV32-NEXT:    srli a2, a2, 2
; RV32-NEXT:    and t0, t0, s2
; RV32-NEXT:    and a7, a7, s2
; RV32-NEXT:    and a5, a5, s2
; RV32-NEXT:    and a3, a3, s2
; RV32-NEXT:    and a1, a1, s2
; RV32-NEXT:    and a6, a6, s2
; RV32-NEXT:    and a4, a4, s2
; RV32-NEXT:    and a2, a2, s2
; RV32-NEXT:    add t0, t1, t0
; RV32-NEXT:    add a7, t2, a7
; RV32-NEXT:    add a5, t3, a5
; RV32-NEXT:    add a3, t4, a3
; RV32-NEXT:    add a1, t5, a1
; RV32-NEXT:    lui t1, 61681
; RV32-NEXT:    addi t1, t1, -241
; RV32-NEXT:    add a6, t6, a6
; RV32-NEXT:    add a4, s0, a4
; RV32-NEXT:    add a2, s1, a2
; RV32-NEXT:    srli t2, t0, 4
; RV32-NEXT:    srli t3, a7, 4
; RV32-NEXT:    srli t4, a5, 4
; RV32-NEXT:    add t0, t0, t2
; RV32-NEXT:    srli t2, a3, 4
; RV32-NEXT:    add a7, a7, t3
; RV32-NEXT:    srli t3, a1, 4
; RV32-NEXT:    add a5, a5, t4
; RV32-NEXT:    srli t4, a6, 4
; RV32-NEXT:    add a3, a3, t2
; RV32-NEXT:    srli t2, a4, 4
; RV32-NEXT:    add a1, a1, t3
; RV32-NEXT:    srli t3, a2, 4
; RV32-NEXT:    add a6, a6, t4
; RV32-NEXT:    add a4, a4, t2
; RV32-NEXT:    add a2, a2, t3
; RV32-NEXT:    and t0, t0, t1
; RV32-NEXT:    and a7, a7, t1
; RV32-NEXT:    and a5, a5, t1
; RV32-NEXT:    and a3, a3, t1
; RV32-NEXT:    and a1, a1, t1
; RV32-NEXT:    and a6, a6, t1
; RV32-NEXT:    and a4, a4, t1
; RV32-NEXT:    and a2, a2, t1
; RV32-NEXT:    slli t1, t0, 8
; RV32-NEXT:    slli t2, a7, 8
; RV32-NEXT:    slli t3, a5, 8
; RV32-NEXT:    slli t4, a3, 8
; RV32-NEXT:    add t0, t0, t1
; RV32-NEXT:    slli t1, a1, 8
; RV32-NEXT:    add a7, a7, t2
; RV32-NEXT:    slli t2, a6, 8
; RV32-NEXT:    add a5, a5, t3
; RV32-NEXT:    slli t3, a4, 8
; RV32-NEXT:    add a3, a3, t4
; RV32-NEXT:    slli t4, a2, 8
; RV32-NEXT:    add a1, a1, t1
; RV32-NEXT:    add a6, a6, t2
; RV32-NEXT:    add a4, a4, t3
; RV32-NEXT:    add a2, a2, t4
; RV32-NEXT:    slli t1, t0, 16
; RV32-NEXT:    slli t2, a7, 16
; RV32-NEXT:    slli t3, a5, 16
; RV32-NEXT:    slli t4, a3, 16
; RV32-NEXT:    add t0, t0, t1
; RV32-NEXT:    slli t1, a1, 16
; RV32-NEXT:    add a7, a7, t2
; RV32-NEXT:    slli t2, a6, 16
; RV32-NEXT:    add a5, a5, t3
; RV32-NEXT:    slli t3, a4, 16
; RV32-NEXT:    add a3, a3, t4
; RV32-NEXT:    slli t4, a2, 16
; RV32-NEXT:    add a1, a1, t1
; RV32-NEXT:    add a6, a6, t2
; RV32-NEXT:    add a4, a4, t3
; RV32-NEXT:    add a2, a2, t4
; RV32-NEXT:    srli t0, t0, 24
; RV32-NEXT:    srli a7, a7, 24
; RV32-NEXT:    srli a5, a5, 24
; RV32-NEXT:    srli a3, a3, 24
; RV32-NEXT:    srli a1, a1, 24
; RV32-NEXT:    srli a6, a6, 24
; RV32-NEXT:    srli a4, a4, 24
; RV32-NEXT:    srli a2, a2, 24
; RV32-NEXT:    add a7, a7, t0
; RV32-NEXT:    add a3, a3, a5
; RV32-NEXT:    add a1, a6, a1
; RV32-NEXT:    add a2, a2, a4
; RV32-NEXT:    add a7, a3, a7
; RV32-NEXT:    add a5, a2, a1
; RV32-NEXT:    add a1, a5, a7
; RV32-NEXT:    sltu a3, a7, a3
; RV32-NEXT:    sltu a4, a5, a2
; RV32-NEXT:    sltu a2, a1, a5
; RV32-NEXT:    add a3, a4, a3
; RV32-NEXT:    add a3, a3, a2
; RV32-NEXT:    beq a3, a4, .LBB7_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    sltu a2, a3, a4
; RV32-NEXT:  .LBB7_2:
; RV32-NEXT:    sw zero, 16(a0)
; RV32-NEXT:    sw zero, 20(a0)
; RV32-NEXT:    sw zero, 24(a0)
; RV32-NEXT:    sw zero, 28(a0)
; RV32-NEXT:    sw a1, 0(a0)
; RV32-NEXT:    sw a3, 4(a0)
; RV32-NEXT:    sw a2, 8(a0)
; RV32-NEXT:    sw zero, 12(a0)
; RV32-NEXT:    lw s0, 12(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s1, 8(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s2, 4(sp) # 4-byte Folded Reload
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    ret
;
; RV64-LABEL: ctpop_i256:
; RV64:       # %bb.0:
; RV64-NEXT:    ld a2, 0(a1)
; RV64-NEXT:    ld a3, 8(a1)
; RV64-NEXT:    ld a4, 16(a1)
; RV64-NEXT:    ld a5, 24(a1)
; RV64-NEXT:    lui a1, 349525
; RV64-NEXT:    lui a6, 209715
; RV64-NEXT:    lui a7, 61681
; RV64-NEXT:    addi a1, a1, 1365
; RV64-NEXT:    addi a6, a6, 819
; RV64-NEXT:    addi a7, a7, -241
; RV64-NEXT:    slli t0, a1, 32
; RV64-NEXT:    slli t1, a6, 32
; RV64-NEXT:    slli t2, a7, 32
; RV64-NEXT:    add t0, a1, t0
; RV64-NEXT:    add a6, a6, t1
; RV64-NEXT:    add a1, a7, t2
; RV64-NEXT:    srli a7, a5, 1
; RV64-NEXT:    srli t1, a4, 1
; RV64-NEXT:    srli t2, a3, 1
; RV64-NEXT:    srli t3, a2, 1
; RV64-NEXT:    and a7, a7, t0
; RV64-NEXT:    and t1, t1, t0
; RV64-NEXT:    and t2, t2, t0
; RV64-NEXT:    and t0, t3, t0
; RV64-NEXT:    sub a5, a5, a7
; RV64-NEXT:    sub a4, a4, t1
; RV64-NEXT:    sub a3, a3, t2
; RV64-NEXT:    sub a2, a2, t0
; RV64-NEXT:    and a7, a5, a6
; RV64-NEXT:    srli a5, a5, 2
; RV64-NEXT:    and t0, a4, a6
; RV64-NEXT:    srli a4, a4, 2
; RV64-NEXT:    and t1, a3, a6
; RV64-NEXT:    srli a3, a3, 2
; RV64-NEXT:    and t2, a2, a6
; RV64-NEXT:    srli a2, a2, 2
; RV64-NEXT:    and a5, a5, a6
; RV64-NEXT:    and a4, a4, a6
; RV64-NEXT:    and a3, a3, a6
; RV64-NEXT:    and a2, a2, a6
; RV64-NEXT:    add a5, a7, a5
; RV64-NEXT:    add a4, t0, a4
; RV64-NEXT:    add a3, t1, a3
; RV64-NEXT:    add a2, t2, a2
; RV64-NEXT:    srli a6, a5, 4
; RV64-NEXT:    srli a7, a4, 4
; RV64-NEXT:    srli t0, a3, 4
; RV64-NEXT:    add a5, a5, a6
; RV64-NEXT:    srli a6, a2, 4
; RV64-NEXT:    add a4, a4, a7
; RV64-NEXT:    add a3, a3, t0
; RV64-NEXT:    add a2, a2, a6
; RV64-NEXT:    and a5, a5, a1
; RV64-NEXT:    and a4, a4, a1
; RV64-NEXT:    and a3, a3, a1
; RV64-NEXT:    and a1, a2, a1
; RV64-NEXT:    slli a2, a5, 8
; RV64-NEXT:    slli a6, a4, 8
; RV64-NEXT:    slli a7, a3, 8
; RV64-NEXT:    slli t0, a1, 8
; RV64-NEXT:    add a2, a5, a2
; RV64-NEXT:    add a4, a4, a6
; RV64-NEXT:    add a3, a3, a7
; RV64-NEXT:    add a1, a1, t0
; RV64-NEXT:    slli a5, a2, 16
; RV64-NEXT:    slli a6, a4, 16
; RV64-NEXT:    slli a7, a3, 16
; RV64-NEXT:    slli t0, a1, 16
; RV64-NEXT:    add a2, a2, a5
; RV64-NEXT:    add a4, a4, a6
; RV64-NEXT:    add a3, a3, a7
; RV64-NEXT:    add a1, a1, t0
; RV64-NEXT:    slli a5, a2, 32
; RV64-NEXT:    slli a6, a4, 32
; RV64-NEXT:    slli a7, a3, 32
; RV64-NEXT:    slli t0, a1, 32
; RV64-NEXT:    add a2, a2, a5
; RV64-NEXT:    add a4, a4, a6
; RV64-NEXT:    add a3, a3, a7
; RV64-NEXT:    add a1, a1, t0
; RV64-NEXT:    srli a2, a2, 56
; RV64-NEXT:    srli a4, a4, 56
; RV64-NEXT:    srli a3, a3, 56
; RV64-NEXT:    srli a1, a1, 56
; RV64-NEXT:    add a2, a4, a2
; RV64-NEXT:    add a1, a1, a3
; RV64-NEXT:    add a2, a1, a2
; RV64-NEXT:    sltu a1, a2, a1
; RV64-NEXT:    sd a2, 0(a0)
; RV64-NEXT:    sd a1, 8(a0)
; RV64-NEXT:    sd zero, 16(a0)
; RV64-NEXT:    sd zero, 24(a0)
; RV64-NEXT:    ret
  %r = call i256 @llvm.ctpop.i256(i256 %a)
  ret i256 %r
}
