; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=riscv64 -mattr=+v,+f,+d | FileCheck %s

declare i1 @llvm.is.fpclass.f32(float, i32)
declare <4 x i1> @llvm.is.fpclass.vf32(<4 x float>, i32)

define i1 @fneg_const_not_inf() nounwind {
; CHECK-LABEL: fneg_const_not_inf:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
  %n = fneg float 1.0
  %r = call i1 @llvm.is.fpclass.f32(float %n, i32 512) ; +inf
  ret i1 %r
}

define i1 @fneg_mask_not_nan(i32 %a) nounwind {
; CHECK-LABEL: fneg_mask_not_nan:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
  %m = and i32 %a, u0x007fffff
  %x = bitcast i32 %m to float
  %n = fneg float %x
  %r = call i1 @llvm.is.fpclass.f32(float %n, i32 3) ; nan
  ret i1 %r
}

define i1 @fneg_shift_not_inf(i32 %x) nounwind {
; CHECK-LABEL: fneg_shift_not_inf:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
  %shl = shl i32 %x, 2
  %shr = lshr i32 %shl, 2
  %y = bitcast i32 %shr to float

  %n = fneg float %y
  %r = call i1 @llvm.is.fpclass.f32(float %n, i32 512) ; +inf
  ret i1 %r
}

define <4 x i1> @fneg_vec_not_inf(<4 x i32> %vecbits) nounwind {
; CHECK-LABEL: fneg_vec_not_inf:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, 262144
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    vfneg.v v8, v8
; CHECK-NEXT:    vfclass.v v8, v8
; CHECK-NEXT:    vand.vi v8, v8, 14
; CHECK-NEXT:    vmsne.vi v0, v8, 0
; CHECK-NEXT:    ret
  %masked = and <4 x i32> %vecbits, <i32 u0x3fffffff, i32 u0x3fffffff, i32 u0x3fffffff, i32 u0x3fffffff>
  %fvec = bitcast <4 x i32> %masked to <4 x float>
  %neg = fneg <4 x float> %fvec
  %res = call <4 x i1> @llvm.is.fpclass.vf32(<4 x float> %neg, i32 312) ; +inf
  ret <4 x i1> %res
}
