; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; Pre-regalloc test
; RUN: llc -mtriple=riscv64 -riscv-enable-live-variables -verify-machineinstrs \
; RUN: -stop-after=sparse-live-variables \
; RUN: < %s | FileCheck %s

; Post-regalloc test
; RUN: llc -mtriple=riscv64 -riscv-enable-live-variables -verify-machineinstrs \
; RUN: -stop-after=sparse-live-variables,1 \
; RUN: < %s | FileCheck %s --check-prefix=CHECK-PR

; Basic test: simple function with two arguments

define i64 @test_mbb_liveins(i64 %a, i64 %b) {
  ; CHECK-LABEL: name: test_mbb_liveins
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[COPY1]], [[COPY]]
  ; CHECK-NEXT:   $x10 = COPY [[ADD]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
  ;
  ; CHECK-PR-LABEL: name: test_mbb_liveins
  ; CHECK-PR: bb.0.entry:
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x10 = ADD killed renamable $x10, killed renamable $x11
  ; CHECK-PR-NEXT:   PseudoRET implicit $x10
entry:
  %sum = add i64 %a, %b
  ret i64 %sum
}

; Test with control flow: verify live-ins are correct for entry block with multiple args




define i64 @test_control_flow(i64 %a, i64 %b, i64 %cond) {
  ; CHECK-LABEL: name: test_control_flow
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x30000000), %bb.2(0x50000000)
  ; CHECK-NEXT:   liveins: $x10, $x11, $x12
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x12
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   BNE [[COPY]], $x0, %bb.2
  ; CHECK-NEXT:   PseudoBR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.then:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[COPY2]], [[COPY1]]
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.else:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:gpr = SUB [[COPY2]], [[COPY1]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.end:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[SUB]], %bb.2, [[ADD]], %bb.1
  ; CHECK-NEXT:   $x10 = COPY [[PHI]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
  ;
  ; CHECK-PR-LABEL: name: test_control_flow
  ; CHECK-PR: bb.0.entry:
  ; CHECK-PR-NEXT:   successors: %bb.1(0x30000000), %bb.2(0x50000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11, $x12
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   BNE killed renamable $x12, $x0, %bb.2
  ; CHECK-PR-NEXT:   PseudoBR %bb.1
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.1.then:
  ; CHECK-PR-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x10 = ADD killed renamable $x10, killed renamable $x11
  ; CHECK-PR-NEXT:   PseudoBR %bb.3
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.2.else:
  ; CHECK-PR-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x10 = SUB killed renamable $x10, killed renamable $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.3.end:
  ; CHECK-PR-NEXT:   liveins: $x10
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   PseudoRET implicit $x10
entry:
  %cmp = icmp eq i64 %cond, 0
  br i1 %cmp, label %then, label %else

then:
  %add = add i64 %a, %b
  br label %end

else:
  %sub = sub i64 %a, %b
  br label %end

end:
  %result = phi i64 [ %add, %then ], [ %sub, %else ]
  ret i64 %result
}

; Test with loops: verify live-ins for loop headers

define i64 @test_loop(i64 %n) {
  ; CHECK-LABEL: name: test_loop
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY [[COPY1]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.loop:
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[COPY2]], %bb.0, %1, %bb.1
  ; CHECK-NEXT:   [[ADDI:%[0-9]+]]:gpr = ADDI [[PHI]], 1
  ; CHECK-NEXT:   BLTU [[ADDI]], [[COPY]], %bb.1
  ; CHECK-NEXT:   PseudoBR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.exit:
  ; CHECK-NEXT:   $x10 = COPY [[ADDI]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
  ;
  ; CHECK-PR-LABEL: name: test_loop
  ; CHECK-PR: bb.0.entry:
  ; CHECK-PR-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x10
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x11 = COPY $x0
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.1.loop:
  ; CHECK-PR-NEXT:   successors: %bb.1(0x7c000000), %bb.2(0x04000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x11 = ADDI killed renamable $x11, 1
  ; CHECK-PR-NEXT:   BLTU renamable $x11, renamable $x10, %bb.1
  ; CHECK-PR-NEXT:   PseudoBR %bb.2
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.2.exit:
  ; CHECK-PR-NEXT:   liveins: $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   $x10 = COPY killed renamable $x11
  ; CHECK-PR-NEXT:   PseudoRET implicit $x10
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %next, %loop ]
  %next = add i64 %i, 1
  %cmp = icmp ult i64 %next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret i64 %next
}

; Test that reserved registers (like $x2 stack pointer) are NOT in live-ins
; This test uses function calls which implicitly use $x2 for stack operations

define i64 @test_reserved_regs(i64 %a, i64 %b) {
  ; CHECK-LABEL: name: test_reserved_regs
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   $x10 = COPY [[COPY1]]
  ; CHECK-NEXT:   $x11 = COPY [[COPY]]
  ; CHECK-NEXT:   PseudoCALL target-flags(riscv-call) @__adddi3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   $x10 = COPY [[COPY2]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
  ;
  ; CHECK-PR-LABEL: name: test_reserved_regs
  ; CHECK-PR: bb.0.entry:
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-PR-NEXT:   PseudoCALL target-flags(riscv-call) @__adddi3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-PR-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-PR-NEXT:   PseudoRET implicit $x10
entry:
  %sum = call i64 @__adddi3(i64 %a, i64 %b)
  ret i64 %sum
}

declare i64 @__adddi3(i64, i64)

; Test with multiple arguments to verify all live-ins are tracked

define i64 @test_many_args(i64 %a, i64 %b, i64 %c, i64 %d) {
  ; CHECK-LABEL: name: test_many_args
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $x10, $x11, $x12, $x13
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x13
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x12
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[COPY3]], [[COPY2]]
  ; CHECK-NEXT:   [[ADD1:%[0-9]+]]:gpr = ADD [[COPY1]], [[COPY]]
  ; CHECK-NEXT:   [[ADD2:%[0-9]+]]:gpr = ADD killed [[ADD]], killed [[ADD1]]
  ; CHECK-NEXT:   $x10 = COPY [[ADD2]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
  ;
  ; CHECK-PR-LABEL: name: test_many_args
  ; CHECK-PR: bb.0.entry:
  ; CHECK-PR-NEXT:   liveins: $x10, $x11, $x12, $x13
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x10 = ADD killed renamable $x10, killed renamable $x11
  ; CHECK-PR-NEXT:   renamable $x12 = ADD killed renamable $x12, killed renamable $x13
  ; CHECK-PR-NEXT:   renamable $x10 = ADD killed renamable $x10, killed renamable $x12
  ; CHECK-PR-NEXT:   PseudoRET implicit $x10
entry:
  %sum1 = add i64 %a, %b
  %sum2 = add i64 %c, %d
  %result = add i64 %sum1, %sum2
  ret i64 %result
}

; Test with nested control flow to ensure entry block has correct live-ins

define i64 @test_nested_control_flow(i64 %a, i64 %b, i64 %c) {
  ; CHECK-LABEL: name: test_nested_control_flow
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x30000000), %bb.4(0x50000000)
  ; CHECK-NEXT:   liveins: $x10, $x11, $x12
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x12
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   BNE [[COPY]], $x0, %bb.4
  ; CHECK-NEXT:   PseudoBR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.outer_then:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BGE [[COPY1]], [[COPY2]], %bb.3
  ; CHECK-NEXT:   PseudoBR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.inner_then:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[COPY2]], [[COPY1]]
  ; CHECK-NEXT:   PseudoBR %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.inner_else:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:gpr = SUB [[COPY2]], [[COPY1]]
  ; CHECK-NEXT:   PseudoBR %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.outer_else:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY2]], 1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.end:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[SLLI]], %bb.4, [[SUB]], %bb.3, [[ADD]], %bb.2
  ; CHECK-NEXT:   $x10 = COPY [[PHI]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
  ;
  ; CHECK-PR-LABEL: name: test_nested_control_flow
  ; CHECK-PR: bb.0.entry:
  ; CHECK-PR-NEXT:   successors: %bb.1(0x30000000), %bb.4(0x50000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11, $x12
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   BNE killed renamable $x12, $x0, %bb.4
  ; CHECK-PR-NEXT:   PseudoBR %bb.1
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.1.outer_then:
  ; CHECK-PR-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   BGE renamable $x11, renamable $x10, %bb.3
  ; CHECK-PR-NEXT:   PseudoBR %bb.2
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.2.inner_then:
  ; CHECK-PR-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x10 = ADD killed renamable $x10, killed renamable $x11
  ; CHECK-PR-NEXT:   PseudoBR %bb.5
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.3.inner_else:
  ; CHECK-PR-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x10 = SUB killed renamable $x10, killed renamable $x11
  ; CHECK-PR-NEXT:   PseudoBR %bb.5
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.4.outer_else:
  ; CHECK-PR-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x10
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x10 = SLLI killed renamable $x10, 1
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.5.end:
  ; CHECK-PR-NEXT:   liveins: $x10
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   PseudoRET implicit $x10
entry:
  %cmp1 = icmp eq i64 %c, 0
  br i1 %cmp1, label %outer_then, label %outer_else

outer_then:
  %cmp2 = icmp sgt i64 %a, %b
  br i1 %cmp2, label %inner_then, label %inner_else

inner_then:
  %add = add i64 %a, %b
  br label %end

inner_else:
  %sub = sub i64 %a, %b
  br label %end

outer_else:
  %mul = mul i64 %a, 2
  br label %end

end:
  %result = phi i64 [ %add, %inner_then ], [ %sub, %inner_else ], [ %mul, %outer_else ]
  ret i64 %result
}

; Test with doubly nested loops

define i64 @test_doubly_nested_loop(i64 %n, i64 %m) {
  ; CHECK-LABEL: name: test_doubly_nested_loop
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY [[COPY2]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.outer_loop:
  ; CHECK-NEXT:   successors: %bb.2(0x7c000000), %bb.5(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[COPY3]], %bb.0, %6, %bb.4
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gpr = PHI [[COPY3]], %bb.0, %4, %bb.4
  ; CHECK-NEXT:   BGEU [[PHI]], [[COPY1]], %bb.5
  ; CHECK-NEXT:   PseudoBR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.inner_loop.preheader:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gpr = COPY [[COPY4]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.inner_loop:
  ; CHECK-NEXT:   successors: %bb.3(0x7c000000), %bb.4(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:gpr = PHI [[COPY5]], %bb.2, %5, %bb.3
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:gpr = PHI [[PHI1]], %bb.2, %4, %bb.3
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[PHI3]], [[PHI2]]
  ; CHECK-NEXT:   [[ADDI:%[0-9]+]]:gpr = ADDI [[PHI2]], 1
  ; CHECK-NEXT:   BLTU [[ADDI]], [[COPY]], %bb.3
  ; CHECK-NEXT:   PseudoBR %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.outer_latch:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDI1:%[0-9]+]]:gpr = ADDI [[PHI]], 1
  ; CHECK-NEXT:   PseudoBR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.exit:
  ; CHECK-NEXT:   $x10 = COPY [[PHI1]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
  ;
  ; CHECK-PR-LABEL: name: test_doubly_nested_loop
  ; CHECK-PR: bb.0.entry:
  ; CHECK-PR-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x13 = COPY $x0
  ; CHECK-PR-NEXT:   renamable $x12 = COPY $x0
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.1.outer_loop:
  ; CHECK-PR-NEXT:   successors: %bb.2(0x7c000000), %bb.5(0x04000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11, $x12, $x13
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   BGEU renamable $x13, renamable $x10, %bb.5
  ; CHECK-PR-NEXT:   PseudoBR %bb.2
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.2.inner_loop.preheader:
  ; CHECK-PR-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11, $x12, $x13
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x14 = COPY $x0
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.3.inner_loop:
  ; CHECK-PR-NEXT:   successors: %bb.3(0x7c000000), %bb.4(0x04000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11, $x12, $x13, $x14
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x12 = ADD killed renamable $x12, renamable $x14
  ; CHECK-PR-NEXT:   renamable $x14 = ADDI killed renamable $x14, 1
  ; CHECK-PR-NEXT:   BLTU renamable $x14, renamable $x11, %bb.3
  ; CHECK-PR-NEXT:   PseudoBR %bb.4
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.4.outer_latch:
  ; CHECK-PR-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11, $x12, $x13
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x13 = ADDI killed renamable $x13, 1
  ; CHECK-PR-NEXT:   PseudoBR %bb.1
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.5.exit:
  ; CHECK-PR-NEXT:   liveins: $x12
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   $x10 = COPY killed renamable $x12
  ; CHECK-PR-NEXT:   PseudoRET implicit $x10
entry:
  br label %outer_loop

outer_loop:
  %i = phi i64 [ 0, %entry ], [ %i_next, %outer_latch ]
  %sum_outer = phi i64 [ 0, %entry ], [ %sum_final, %outer_latch ]
  %i_cmp = icmp ult i64 %i, %n
  br i1 %i_cmp, label %inner_loop, label %exit

inner_loop:
  %j = phi i64 [ 0, %outer_loop ], [ %j_next, %inner_loop ]
  %sum_inner = phi i64 [ %sum_outer, %outer_loop ], [ %sum_new, %inner_loop ]
  %sum_new = add i64 %sum_inner, %j
  %j_next = add i64 %j, 1
  %j_cmp = icmp ult i64 %j_next, %m
  br i1 %j_cmp, label %inner_loop, label %outer_latch

outer_latch:
  %sum_final = phi i64 [ %sum_new, %inner_loop ]
  %i_next = add i64 %i, 1
  br label %outer_loop

exit:
  ret i64 %sum_outer
}

; Test with triply nested loops and function calls
; This tests that reserved registers ($x2) are not added to live-ins even with deep nesting

define i64 @test_triply_nested_loop_with_calls(i64 %n, i64 %m, i64 %p) {
  ; CHECK-LABEL: name: test_triply_nested_loop_with_calls
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x10, $x11, $x12
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x12
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY [[COPY3]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.loop_i:
  ; CHECK-NEXT:   successors: %bb.2(0x7c000000), %bb.8(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[COPY4]], %bb.0, %9, %bb.7
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gpr = PHI [[COPY4]], %bb.0, %3, %bb.7
  ; CHECK-NEXT:   BGEU [[PHI]], [[COPY2]], %bb.8
  ; CHECK-NEXT:   PseudoBR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.loop_j_header:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:gpr = COPY [[COPY5]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.loop_j:
  ; CHECK-NEXT:   successors: %bb.4(0x7c000000), %bb.7(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:gpr = PHI [[COPY6]], %bb.2, %8, %bb.6
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:gpr = PHI [[PHI1]], %bb.2, %6, %bb.6
  ; CHECK-NEXT:   BGEU [[PHI2]], [[COPY1]], %bb.7
  ; CHECK-NEXT:   PseudoBR %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.loop_k_header:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:gpr = COPY [[COPY7]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.loop_k:
  ; CHECK-NEXT:   successors: %bb.5(0x7c000000), %bb.6(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI4:%[0-9]+]]:gpr = PHI [[COPY8]], %bb.4, %7, %bb.5
  ; CHECK-NEXT:   [[PHI5:%[0-9]+]]:gpr = PHI [[PHI3]], %bb.4, %6, %bb.5
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   $x10 = COPY [[PHI]]
  ; CHECK-NEXT:   $x11 = COPY [[PHI2]]
  ; CHECK-NEXT:   PseudoCALL target-flags(riscv-call) @__muldi3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[PHI5]], [[COPY9]]
  ; CHECK-NEXT:   [[ADDI:%[0-9]+]]:gpr = ADDI [[PHI4]], 1
  ; CHECK-NEXT:   BLTU [[ADDI]], [[COPY]], %bb.5
  ; CHECK-NEXT:   PseudoBR %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6.loop_k_exit:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDI1:%[0-9]+]]:gpr = ADDI [[PHI2]], 1
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7.loop_j_exit:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDI2:%[0-9]+]]:gpr = ADDI [[PHI]], 1
  ; CHECK-NEXT:   PseudoBR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8.exit:
  ; CHECK-NEXT:   $x10 = COPY [[PHI1]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
  ;
  ; CHECK-PR-LABEL: name: test_triply_nested_loop_with_calls
  ; CHECK-PR: bb.0.entry:
  ; CHECK-PR-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11, $x12
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x8 = COPY $x12
  ; CHECK-PR-NEXT:   renamable $x9 = COPY $x11
  ; CHECK-PR-NEXT:   renamable $x18 = COPY $x10
  ; CHECK-PR-NEXT:   renamable $x20 = COPY $x0
  ; CHECK-PR-NEXT:   renamable $x19 = COPY $x0
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.1.loop_i:
  ; CHECK-PR-NEXT:   successors: %bb.2(0x7c000000), %bb.8(0x04000000)
  ; CHECK-PR-NEXT:   liveins: $x8, $x9, $x18, $x19, $x20
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   BGEU renamable $x20, renamable $x18, %bb.8
  ; CHECK-PR-NEXT:   PseudoBR %bb.2
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.2.loop_j_header:
  ; CHECK-PR-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x8, $x9, $x18, $x19, $x20
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x21 = COPY $x0
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.3.loop_j:
  ; CHECK-PR-NEXT:   successors: %bb.4(0x7c000000), %bb.7(0x04000000)
  ; CHECK-PR-NEXT:   liveins: $x8, $x9, $x18, $x19, $x20, $x21
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   BGEU renamable $x21, renamable $x9, %bb.7
  ; CHECK-PR-NEXT:   PseudoBR %bb.4
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.4.loop_k_header:
  ; CHECK-PR-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x8, $x9, $x18, $x19, $x20, $x21
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x22 = COPY $x0
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.5.loop_k:
  ; CHECK-PR-NEXT:   successors: %bb.5(0x7c000000), %bb.6(0x04000000)
  ; CHECK-PR-NEXT:   liveins: $x8, $x9, $x18, $x19, $x20, $x21, $x22
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-PR-NEXT:   $x10 = COPY renamable $x20
  ; CHECK-PR-NEXT:   $x11 = COPY renamable $x21
  ; CHECK-PR-NEXT:   PseudoCALL target-flags(riscv-call) @__muldi3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-PR-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-PR-NEXT:   renamable $x22 = ADDI killed renamable $x22, 1
  ; CHECK-PR-NEXT:   renamable $x19 = ADD killed renamable $x19, killed renamable $x10
  ; CHECK-PR-NEXT:   BLTU renamable $x22, renamable $x8, %bb.5
  ; CHECK-PR-NEXT:   PseudoBR %bb.6
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.6.loop_k_exit:
  ; CHECK-PR-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x8, $x9, $x18, $x19, $x20, $x21
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x21 = ADDI killed renamable $x21, 1
  ; CHECK-PR-NEXT:   PseudoBR %bb.3
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.7.loop_j_exit:
  ; CHECK-PR-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x8, $x9, $x18, $x19, $x20
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x20 = ADDI killed renamable $x20, 1
  ; CHECK-PR-NEXT:   PseudoBR %bb.1
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.8.exit:
  ; CHECK-PR-NEXT:   liveins: $x19
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   $x10 = COPY killed renamable $x19
  ; CHECK-PR-NEXT:   PseudoRET implicit $x10
entry:
  br label %loop_i

loop_i:
  %i = phi i64 [ 0, %entry ], [ %i_next, %loop_i_latch ]
  %sum_i = phi i64 [ 0, %entry ], [ %sum_after_j, %loop_i_latch ]
  %i_cmp = icmp ult i64 %i, %n
  br i1 %i_cmp, label %loop_j_header, label %exit

loop_j_header:
  br label %loop_j

loop_j:
  %j = phi i64 [ 0, %loop_j_header ], [ %j_next, %loop_j_latch ]
  %sum_j = phi i64 [ %sum_i, %loop_j_header ], [ %sum_after_k, %loop_j_latch ]
  %j_cmp = icmp ult i64 %j, %m
  br i1 %j_cmp, label %loop_k_header, label %loop_j_exit

loop_k_header:
  br label %loop_k

loop_k:
  %k = phi i64 [ 0, %loop_k_header ], [ %k_next, %loop_k ]
  %sum_k = phi i64 [ %sum_j, %loop_k_header ], [ %sum_k_new, %loop_k ]

  ; Function call inside innermost loop - uses stack pointer $x2 implicitly
  %prod = call i64 @__muldi3(i64 %i, i64 %j)
  %sum_k_new = add i64 %sum_k, %prod

  %k_next = add i64 %k, 1
  %k_cmp = icmp ult i64 %k_next, %p
  br i1 %k_cmp, label %loop_k, label %loop_k_exit

loop_k_exit:
  br label %loop_j_latch

loop_j_latch:
  %sum_after_k = phi i64 [ %sum_k_new, %loop_k_exit ]
  %j_next = add i64 %j, 1
  br label %loop_j

loop_j_exit:
  br label %loop_i_latch

loop_i_latch:
  %sum_after_j = phi i64 [ %sum_j, %loop_j_exit ]
  %i_next = add i64 %i, 1
  br label %loop_i

exit:
  ret i64 %sum_i
}

declare i64 @__muldi3(i64, i64)

; Test with unstructured control flow (multiple entries, irreducible loop)

define i64 @test_unstructured_cfg(i64 %a, i64 %b, i64 %selector) {
  ; CHECK-LABEL: name: test_unstructured_cfg
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x30000000), %bb.2(0x50000000)
  ; CHECK-NEXT:   liveins: $x10, $x11, $x12
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x12
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   BNE [[COPY]], $x0, %bb.2
  ; CHECK-NEXT:   PseudoBR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.block_a:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDI:%[0-9]+]]:gpr = ADDI [[COPY2]], 1
  ; CHECK-NEXT:   [[ADDI1:%[0-9]+]]:gpr = ADDI $x0, 9
  ; CHECK-NEXT:   BLT killed [[ADDI1]], [[ADDI]], %bb.3
  ; CHECK-NEXT:   PseudoBR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.block_b:
  ; CHECK-NEXT:   successors: %bb.4(0x04000000), %bb.3(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[COPY1]], %bb.0, [[ADDI]], %bb.1, %4, %bb.3
  ; CHECK-NEXT:   [[SLLI:%[0-9]+]]:gpr = SLLI [[PHI]], 1
  ; CHECK-NEXT:   [[ADDI2:%[0-9]+]]:gpr = ADDI $x0, 100
  ; CHECK-NEXT:   BLT killed [[ADDI2]], [[SLLI]], %bb.4
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.block_c:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gpr = PHI [[ADDI]], %bb.1, [[SLLI]], %bb.2
  ; CHECK-NEXT:   [[ADDI3:%[0-9]+]]:gpr = ADDI [[PHI1]], -1
  ; CHECK-NEXT:   [[ADDI4:%[0-9]+]]:gpr = ADDI $x0, 5
  ; CHECK-NEXT:   BLTU killed [[ADDI4]], [[ADDI3]], %bb.2
  ; CHECK-NEXT:   PseudoBR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.exit:
  ; CHECK-NEXT:   $x10 = COPY [[SLLI]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
  ;
  ; CHECK-PR-LABEL: name: test_unstructured_cfg
  ; CHECK-PR: bb.0.entry:
  ; CHECK-PR-NEXT:   successors: %bb.1(0x30000000), %bb.2(0x50000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11, $x12
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   BNE killed renamable $x12, $x0, %bb.2
  ; CHECK-PR-NEXT:   PseudoBR %bb.1
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.1.block_a:
  ; CHECK-PR-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-PR-NEXT:   liveins: $x10
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x11 = ADDI renamable $x10, 1
  ; CHECK-PR-NEXT:   renamable $x12 = ADDI $x0, 9
  ; CHECK-PR-NEXT:   BLT killed renamable $x12, renamable $x11, %bb.3
  ; CHECK-PR-NEXT:   PseudoBR %bb.2
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.2.block_b:
  ; CHECK-PR-NEXT:   successors: %bb.4(0x04000000), %bb.5(0x7c000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x11 = SLLI killed renamable $x11, 1
  ; CHECK-PR-NEXT:   renamable $x12 = ADDI $x0, 100
  ; CHECK-PR-NEXT:   BLT killed renamable $x12, renamable $x11, %bb.4
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.5:
  ; CHECK-PR-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.3.block_c:
  ; CHECK-PR-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x11 = ADDI killed renamable $x11, -1
  ; CHECK-PR-NEXT:   renamable $x12 = ADDI $x0, 5
  ; CHECK-PR-NEXT:   BLTU killed renamable $x12, renamable $x11, %bb.2
  ; CHECK-PR-NEXT:   PseudoBR %bb.1
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.4.exit:
  ; CHECK-PR-NEXT:   liveins: $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   $x10 = COPY killed renamable $x11
  ; CHECK-PR-NEXT:   PseudoRET implicit $x10
entry:
  %cmp1 = icmp eq i64 %selector, 0
  br i1 %cmp1, label %block_a, label %block_b

block_a:
  %val_a = add i64 %a, 1
  %cmp_a = icmp slt i64 %val_a, 10
  br i1 %cmp_a, label %block_b, label %block_c

block_b:
  %phi_b = phi i64 [ %b, %entry ], [ %val_a, %block_a ], [ %val_c, %block_c ]
  %val_b = mul i64 %phi_b, 2
  %cmp_b = icmp sgt i64 %val_b, 100
  br i1 %cmp_b, label %exit, label %block_c

block_c:
  %phi_c = phi i64 [ %val_a, %block_a ], [ %val_b, %block_b ]
  %val_c = sub i64 %phi_c, 1
  %cmp_c = icmp ugt i64 %val_c, 5
  br i1 %cmp_c, label %block_b, label %block_a

exit:
  %result = phi i64 [ %val_b, %block_b ]
  ret i64 %result
}

; Test with multiple function calls and complex control flow
; Ensures reserved registers are not in live-ins across multiple call sites

define i64 @test_multiple_calls(i64 %a, i64 %b, i64 %c, i64 %d) {
  ; CHECK-LABEL: name: test_multiple_calls
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $x10, $x11, $x12, $x13
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x13
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x12
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   BGE [[COPY2]], [[COPY3]], %bb.2
  ; CHECK-NEXT:   PseudoBR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.call1:
  ; CHECK-NEXT:   successors: %bb.3(0x30000000), %bb.4(0x50000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   $x10 = COPY [[COPY3]]
  ; CHECK-NEXT:   $x11 = COPY [[COPY2]]
  ; CHECK-NEXT:   PseudoCALL target-flags(riscv-call) @__adddi3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gpr = COPY [[COPY4]]
  ; CHECK-NEXT:   BEQ [[COPY4]], $x0, %bb.3
  ; CHECK-NEXT:   PseudoBR %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.call2:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   $x10 = COPY [[COPY1]]
  ; CHECK-NEXT:   $x11 = COPY [[COPY]]
  ; CHECK-NEXT:   PseudoCALL target-flags(riscv-call) @__muldi3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:gpr = COPY [[COPY6]]
  ; CHECK-NEXT:   PseudoBR %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.call3:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   $x10 = COPY [[COPY1]]
  ; CHECK-NEXT:   $x11 = COPY [[COPY]]
  ; CHECK-NEXT:   PseudoCALL target-flags(riscv-call) @__adddi3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:gpr = COPY [[COPY8]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.merge:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[COPY7]], %bb.2, [[COPY5]], %bb.1, [[COPY9]], %bb.3
  ; CHECK-NEXT:   $x10 = COPY [[PHI]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
  ;
  ; CHECK-PR-LABEL: name: test_multiple_calls
  ; CHECK-PR: bb.0.entry:
  ; CHECK-PR-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11, $x12, $x13
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   BGE renamable $x11, renamable $x10, %bb.2
  ; CHECK-PR-NEXT:   PseudoBR %bb.1
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.1.call1:
  ; CHECK-PR-NEXT:   successors: %bb.3(0x30000000), %bb.4(0x50000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11, $x12, $x13
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x9 = COPY killed renamable $x12
  ; CHECK-PR-NEXT:   renamable $x8 = COPY killed renamable $x13
  ; CHECK-PR-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-PR-NEXT:   PseudoCALL target-flags(riscv-call) @__adddi3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-PR-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-PR-NEXT:   BEQ renamable $x10, $x0, %bb.3
  ; CHECK-PR-NEXT:   PseudoBR %bb.4
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.2.call2:
  ; CHECK-PR-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x12, $x13
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-PR-NEXT:   $x10 = COPY killed renamable $x12
  ; CHECK-PR-NEXT:   $x11 = COPY killed renamable $x13
  ; CHECK-PR-NEXT:   PseudoCALL target-flags(riscv-call) @__muldi3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-PR-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-PR-NEXT:   PseudoBR %bb.4
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.3.call3:
  ; CHECK-PR-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x8, $x9
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-PR-NEXT:   $x10 = COPY killed renamable $x9
  ; CHECK-PR-NEXT:   $x11 = COPY killed renamable $x8
  ; CHECK-PR-NEXT:   PseudoCALL target-flags(riscv-call) @__adddi3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-PR-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.4.merge:
  ; CHECK-PR-NEXT:   liveins: $x10
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   PseudoRET implicit $x10
entry:
  %cmp = icmp sgt i64 %a, %b
  br i1 %cmp, label %call1, label %call2

call1:
  %res1 = call i64 @__adddi3(i64 %a, i64 %b)
  %cmp1 = icmp eq i64 %res1, 0
  br i1 %cmp1, label %call3, label %merge

call2:
  %res2 = call i64 @__muldi3(i64 %c, i64 %d)
  br label %merge

call3:
  %res3 = call i64 @__adddi3(i64 %c, i64 %d)
  br label %merge

merge:
  %final = phi i64 [ %res1, %call1 ], [ %res2, %call2 ], [ %res3, %call3 ]
  ret i64 %final
}

; Test with switch-like control flow

define i64 @test_switch_cfg(i64 %selector, i64 %value) {
  ; CHECK-LABEL: name: test_switch_cfg
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.7(0x40000000), %bb.8(0x40000000)
  ; CHECK-NEXT:   liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[ADDI:%[0-9]+]]:gpr = ADDI $x0, 1
  ; CHECK-NEXT:   BLT killed [[ADDI]], [[COPY1]], %bb.8
  ; CHECK-NEXT:   PseudoBR %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x33333333), %bb.10(0x4ccccccd)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BEQ [[COPY1]], $x0, %bb.1
  ; CHECK-NEXT:   PseudoBR %bb.10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.10.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x55555555), %bb.5(0x2aaaaaab)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDI1:%[0-9]+]]:gpr = ADDI $x0, 1
  ; CHECK-NEXT:   BEQ [[COPY1]], killed [[ADDI1]], %bb.2
  ; CHECK-NEXT:   PseudoBR %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8.entry:
  ; CHECK-NEXT:   successors: %bb.3(0x33333333), %bb.9(0x4ccccccd)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDI2:%[0-9]+]]:gpr = ADDI $x0, 2
  ; CHECK-NEXT:   BEQ [[COPY1]], killed [[ADDI2]], %bb.3
  ; CHECK-NEXT:   PseudoBR %bb.9
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.9.entry:
  ; CHECK-NEXT:   successors: %bb.4(0x55555555), %bb.5(0x2aaaaaab)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDI3:%[0-9]+]]:gpr = ADDI $x0, 3
  ; CHECK-NEXT:   BEQ [[COPY1]], killed [[ADDI3]], %bb.4
  ; CHECK-NEXT:   PseudoBR %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.case0:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDI4:%[0-9]+]]:gpr = ADDI [[COPY]], 10
  ; CHECK-NEXT:   PseudoBR %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.case1:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDI5:%[0-9]+]]:gpr = ADDI [[COPY]], -10
  ; CHECK-NEXT:   PseudoBR %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.case2:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY]], 1
  ; CHECK-NEXT:   PseudoBR %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.case3:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[SLLI1:%[0-9]+]]:gpr = SLLI [[COPY]], 1
  ; CHECK-NEXT:   PseudoBR %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.default:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY [[COPY2]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6.exit:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[SLLI1]], %bb.4, [[SLLI]], %bb.3, [[ADDI5]], %bb.2, [[ADDI4]], %bb.1, [[COPY3]], %bb.5
  ; CHECK-NEXT:   $x10 = COPY [[PHI]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
  ;
  ; CHECK-PR-LABEL: name: test_switch_cfg
  ; CHECK-PR: bb.0.entry:
  ; CHECK-PR-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x12 = ADDI $x0, 1
  ; CHECK-PR-NEXT:   BLT killed renamable $x12, renamable $x10, %bb.3
  ; CHECK-PR-NEXT:   PseudoBR %bb.1
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.1.entry:
  ; CHECK-PR-NEXT:   successors: %bb.5(0x33333333), %bb.2(0x4ccccccd)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   BEQ renamable $x10, $x0, %bb.5
  ; CHECK-PR-NEXT:   PseudoBR %bb.2
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.2.entry:
  ; CHECK-PR-NEXT:   successors: %bb.6(0x55555555), %bb.9(0x2aaaaaab)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x12 = ADDI $x0, 1
  ; CHECK-PR-NEXT:   BEQ killed renamable $x10, killed renamable $x12, %bb.6
  ; CHECK-PR-NEXT:   PseudoBR %bb.9
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.3.entry:
  ; CHECK-PR-NEXT:   successors: %bb.7(0x33333333), %bb.4(0x4ccccccd)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x12 = ADDI $x0, 2
  ; CHECK-PR-NEXT:   BEQ renamable $x10, killed renamable $x12, %bb.7
  ; CHECK-PR-NEXT:   PseudoBR %bb.4
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.4.entry:
  ; CHECK-PR-NEXT:   successors: %bb.8(0x55555555), %bb.9(0x2aaaaaab)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x12 = ADDI $x0, 3
  ; CHECK-PR-NEXT:   BEQ killed renamable $x10, killed renamable $x12, %bb.8
  ; CHECK-PR-NEXT:   PseudoBR %bb.9
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.5.case0:
  ; CHECK-PR-NEXT:   successors: %bb.10(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x10 = ADDI killed renamable $x11, 10
  ; CHECK-PR-NEXT:   PseudoBR %bb.10
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.6.case1:
  ; CHECK-PR-NEXT:   successors: %bb.10(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x10 = ADDI killed renamable $x11, -10
  ; CHECK-PR-NEXT:   PseudoBR %bb.10
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.7.case2:
  ; CHECK-PR-NEXT:   successors: %bb.10(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x10 = SLLI killed renamable $x11, 1
  ; CHECK-PR-NEXT:   PseudoBR %bb.10
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.8.case3:
  ; CHECK-PR-NEXT:   successors: %bb.10(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x11
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x10 = SLLI killed renamable $x11, 1
  ; CHECK-PR-NEXT:   PseudoBR %bb.10
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.9.default:
  ; CHECK-PR-NEXT:   successors: %bb.10(0x80000000)
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x10 = COPY $x0
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.10.exit:
  ; CHECK-PR-NEXT:   liveins: $x10
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   PseudoRET implicit $x10
entry:
  switch i64 %selector, label %default [
    i64 0, label %case0
    i64 1, label %case1
    i64 2, label %case2
    i64 3, label %case3
  ]

case0:
  %res0 = add i64 %value, 10
  br label %exit

case1:
  %res1 = sub i64 %value, 10
  br label %exit

case2:
  %res2 = mul i64 %value, 2
  br label %exit

case3:
  %res3 = shl i64 %value, 1
  br label %exit

default:
  br label %exit

exit:
  %result = phi i64 [ %res0, %case0 ], [ %res1, %case1 ], [ %res2, %case2 ], [ %res3, %case3 ], [ 0, %default ]
  ret i64 %result
}

; Test with loop with multiple exits










define i64 @test_loop_multiple_exits(i64 %n, i64 %threshold, i64 %increment) {
  ; CHECK-LABEL: name: test_loop_multiple_exits
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x10, $x11, $x12
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x12
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY]], 1
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY [[COPY3]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.loop:
  ; CHECK-NEXT:   successors: %bb.4(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[COPY4]], %bb.0, %6, %bb.3
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gpr = PHI [[COPY4]], %bb.0, %5, %bb.3
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:gpr = PHI [[COPY4]], %bb.0, %4, %bb.3
  ; CHECK-NEXT:   BLTU [[COPY1]], [[PHI2]], %bb.4
  ; CHECK-NEXT:   PseudoBR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.check2:
  ; CHECK-NEXT:   successors: %bb.5(0x04000000), %bb.3(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BLTU [[COPY2]], [[PHI1]], %bb.5
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.loop_continue:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[PHI2]], [[COPY]]
  ; CHECK-NEXT:   [[ADDI:%[0-9]+]]:gpr = ADDI [[PHI1]], 1
  ; CHECK-NEXT:   [[ADD1:%[0-9]+]]:gpr = ADD [[PHI]], [[SLLI]]
  ; CHECK-NEXT:   PseudoBR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.exit1:
  ; CHECK-NEXT:   $x10 = COPY [[PHI2]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.exit2:
  ; CHECK-NEXT:   $x10 = COPY [[PHI]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
  ;
  ; CHECK-PR-LABEL: name: test_loop_multiple_exits
  ; CHECK-PR: bb.0.entry:
  ; CHECK-PR-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11, $x12
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x13 = COPY $x10
  ; CHECK-PR-NEXT:   renamable $x10 = COPY $x0
  ; CHECK-PR-NEXT:   renamable $x15 = COPY $x0
  ; CHECK-PR-NEXT:   renamable $x14 = COPY $x0
  ; CHECK-PR-NEXT:   renamable $x16 = SLLI renamable $x12, 1
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.1.loop:
  ; CHECK-PR-NEXT:   successors: %bb.4(0x04000000), %bb.2(0x7c000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11, $x12, $x13, $x14, $x15, $x16
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   BLTU renamable $x11, renamable $x14, %bb.4
  ; CHECK-PR-NEXT:   PseudoBR %bb.2
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.2.check2:
  ; CHECK-PR-NEXT:   successors: %bb.5(0x04000000), %bb.3(0x7c000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11, $x12, $x13, $x14, $x15, $x16
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   BLTU renamable $x13, renamable $x15, %bb.5
  ; CHECK-PR-NEXT:   PseudoBR %bb.3
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.3.loop_continue:
  ; CHECK-PR-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-PR-NEXT:   liveins: $x10, $x11, $x12, $x13, $x14, $x15, $x16
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   renamable $x14 = ADD killed renamable $x14, renamable $x12
  ; CHECK-PR-NEXT:   renamable $x15 = ADDI killed renamable $x15, 1
  ; CHECK-PR-NEXT:   renamable $x10 = ADD killed renamable $x10, renamable $x16
  ; CHECK-PR-NEXT:   PseudoBR %bb.1
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.4.exit1:
  ; CHECK-PR-NEXT:   liveins: $x14
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   $x10 = COPY killed renamable $x14
  ; CHECK-PR-NEXT:   PseudoRET implicit $x10
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT: bb.5.exit2:
  ; CHECK-PR-NEXT:   liveins: $x10
  ; CHECK-PR-NEXT: {{  $}}
  ; CHECK-PR-NEXT:   PseudoRET implicit $x10
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i_next, %loop_continue ]
  %sum = phi i64 [ 0, %entry ], [ %sum_next, %loop_continue ]

  %cmp1 = icmp ugt i64 %sum, %threshold
  br i1 %cmp1, label %exit1, label %check2

check2:
  %cmp2 = icmp ugt i64 %i, %n
  br i1 %cmp2, label %exit2, label %loop_continue

loop_continue:
  %sum_next = add i64 %sum, %increment
  %i_next = add i64 %i, 1
  br label %loop

exit1:
  ret i64 %sum

exit2:
  %final = mul i64 %sum, 2
  ret i64 %final
}
