; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -mtriple=riscv64 -riscv-enable-live-variables -verify-machineinstrs \
; RUN: -riscv-enable-live-variables -stop-after=sparse-live-variables \
; RUN: -o - %s | FileCheck %s

; Test live variable analysis for RV64-specific scenarios
; This includes 64-bit operations, wide registers, and RV64-specific instructions

;

define i64 @test_64bit_ops(i64 %a, i64 %b) {
  ; CHECK-LABEL: name: test_64bit_ops
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY1]], 32
  ; CHECK-NEXT:   [[OR:%[0-9]+]]:gpr = OR killed [[SLLI]], [[COPY]]
  ; CHECK-NEXT:   $x10 = COPY [[OR]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
entry:
  %shl = shl i64 %a, 32
  %or = or i64 %shl, %b
  ret i64 %or
}

;

define i64 @test_word_ops(i64 %a, i64 %b) {
  ; CHECK-LABEL: name: test_word_ops
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[ADDW:%[0-9]+]]:gpr = ADDW [[COPY1]], [[COPY]]
  ; CHECK-NEXT:   $x10 = COPY [[ADDW]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
entry:
  %trunc_a = trunc i64 %a to i32
  %trunc_b = trunc i64 %b to i32
  %add = add i32 %trunc_a, %trunc_b
  %ext = sext i32 %add to i64
  ret i64 %ext
}

;

define i64 @test_mixed_width(i64 %a, i32 %b) {
  ; CHECK-LABEL: name: test_mixed_width
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   $x10 = COPY [[COPY1]]
  ; CHECK-NEXT:   $x11 = COPY [[COPY]]
  ; CHECK-NEXT:   PseudoCALL target-flags(riscv-call) &__muldi3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[ADDIW:%[0-9]+]]:gpr = ADDIW [[COPY2]], 0
  ; CHECK-NEXT:   $x10 = COPY [[ADDIW]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
entry:
  %ext_b = sext i32 %b to i64
  %mul = mul i64 %a, %ext_b
  %trunc = trunc i64 %mul to i32
  %final = sext i32 %trunc to i64
  ret i64 %final
}

;
;
;
;
;
;

define double @test_float_64(double %a, double %b, i64 %selector) {
  ; CHECK-LABEL: name: test_float_64
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x30000000), %bb.2(0x50000000)
  ; CHECK-NEXT:   liveins: $x10, $x11, $x12
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x12
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY [[COPY1]]
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY [[COPY2]]
  ; CHECK-NEXT:   BNE [[COPY]], $x0, %bb.2
  ; CHECK-NEXT:   PseudoBR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.then:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   $x10 = COPY [[COPY4]]
  ; CHECK-NEXT:   $x11 = COPY [[COPY3]]
  ; CHECK-NEXT:   PseudoCALL target-flags(riscv-call) &__adddf3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:gpr = COPY [[COPY5]]
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.else:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   $x10 = COPY [[COPY4]]
  ; CHECK-NEXT:   $x11 = COPY [[COPY3]]
  ; CHECK-NEXT:   PseudoCALL target-flags(riscv-call) &__muldf3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:gpr = COPY [[COPY7]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.end:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[COPY8]], %bb.2, [[COPY6]], %bb.1
  ; CHECK-NEXT:   $x10 = COPY [[PHI]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
entry:
  %cmp = icmp eq i64 %selector, 0
  br i1 %cmp, label %then, label %else

then:
  %add = fadd double %a, %b
  br label %end

else:
  %mul = fmul double %a, %b
  br label %end

end:
  %result = phi double [ %add, %then ], [ %mul, %else ]
  ret double %result
}
