# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv64 -riscv-enable-live-variables -verify-machineinstrs -run-pass=sparse-live-variables -o - %s | FileCheck %s
#
# Test basic live variable analysis with simple control flow and basic blocks

# REQUIRES: asserts

---
name:            test_simple_add
alignment:       4
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
  - { id: 1, class: gpr }
  - { id: 2, class: gpr }
liveins:
  - { reg: '$x10', virtual-reg: '%0' }
  - { reg: '$x11', virtual-reg: '%1' }
body:             |
  bb.0:
    liveins: $x10, $x11
    ; Test that %0 and %1 are live-in, used once, and %2 is defined

    ; CHECK-LABEL: name: test_simple_add
    ; CHECK: liveins: $x10, $x11
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[ADD]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gpr = COPY $x10
    %1:gpr = COPY $x11
    %2:gpr = ADD %0, %1
    $x10 = COPY %2
    PseudoRET implicit $x10
...
---
name:            test_if_then_else
alignment:       4
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
  - { id: 1, class: gpr }
  - { id: 2, class: gpr }
  - { id: 3, class: gpr }
  - { id: 4, class: gpr }
liveins:
  - { reg: '$x10', virtual-reg: '%0' }
  - { reg: '$x11', virtual-reg: '%1' }
body:             |
  ; CHECK-LABEL: name: test_if_then_else
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[SLT:%[0-9]+]]:gpr = SLT [[COPY1]], [[COPY]]
  ; CHECK-NEXT:   BEQ [[SLT]], $x0, %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MUL:%[0-9]+]]:gpr = MUL [[COPY]], [[COPY1]]
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:gpr = SUB [[COPY]], [[COPY1]]
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[MUL]], %bb.1, [[SUB]], %bb.2
  ; CHECK-NEXT:   $x10 = COPY [[PHI]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
  bb.0:
    liveins: $x10, $x11
    ; Test that %0 and %1 are live across multiple blocks

    %0:gpr = COPY $x10
    %1:gpr = COPY $x11
    %2:gpr = SLT %1, %0
    BEQ %2, $x0, %bb.2

  bb.1:
    ; %0 and %1 should be live-in here
    %3:gpr = MUL %0, %1
    PseudoBR %bb.3

  bb.2:
    ; %0 and %1 should be live-in here
    %4:gpr = SUB %0, %1
    PseudoBR %bb.3

  bb.3:
    ; Either %3 or %4 should be live-in (phi sources)
    %5:gpr = PHI %3, %bb.1, %4, %bb.2
    $x10 = COPY %5
    PseudoRET implicit $x10
...
---
name:            test_multiple_uses
alignment:       4
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
  - { id: 1, class: gpr }
  - { id: 2, class: gpr }
  - { id: 3, class: gpr }
  - { id: 4, class: gpr }
  - { id: 5, class: gpr }
  - { id: 6, class: gpr }
liveins:
  - { reg: '$x10', virtual-reg: '%0' }
  - { reg: '$x11', virtual-reg: '%1' }
  - { reg: '$x12', virtual-reg: '%2' }
body:             |
  bb.0:
    liveins: $x10, $x11, $x12
    ; Test that variables with multiple uses have correct liveness ranges

    ; CHECK-LABEL: name: test_multiple_uses
    ; CHECK: liveins: $x10, $x11, $x12
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr = COPY $x12
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:gpr = MUL [[ADD]], [[COPY2]]
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gpr = SUB [[MUL]], [[COPY]]
    ; CHECK-NEXT: [[ADD1:%[0-9]+]]:gpr = ADD [[SUB]], [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[ADD1]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gpr = COPY $x10
    %1:gpr = COPY $x11
    %2:gpr = COPY $x12
    ; %0 used here and later
    %3:gpr = ADD %0, %1
    ; %3 used in next instruction
    %4:gpr = MUL %3, %2
    ; %0 used again here (should still be live)
    %5:gpr = SUB %4, %0
    ; %1 used again here
    %6:gpr = ADD %5, %1
    $x10 = COPY %6
    PseudoRET implicit $x10
...
