; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -mtriple=riscv64 -riscv-enable-live-variables -verify-machineinstrs \
; RUN: -riscv-enable-live-variables -stop-after=sparse-live-variables \
; RUN: -o - %s | FileCheck %s

; Test live variable analysis with loops and backward edges
; Loops create interesting liveness patterns with phi nodes and variables
; that are live across backedges

;
;
;
;

define i64 @test_simple_loop(i64 %n) {
  ; CHECK-LABEL: name: test_simple_loop
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY [[COPY1]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.loop:
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[COPY2]], %bb.0, %3, %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gpr = PHI [[COPY2]], %bb.0, %2, %bb.1
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[PHI1]], [[PHI]]
  ; CHECK-NEXT:   [[ADDI:%[0-9]+]]:gpr = ADDI [[PHI]], 1
  ; CHECK-NEXT:   BLT [[ADDI]], [[COPY]], %bb.1
  ; CHECK-NEXT:   PseudoBR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.exit:
  ; CHECK-NEXT:   $x10 = COPY [[ADD]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %sum = phi i64 [ 0, %entry ], [ %sum.next, %loop ]
  %sum.next = add i64 %sum, %i
  %i.next = add i64 %i, 1
  %cmp = icmp slt i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret i64 %sum.next
}

;
;
;
;
;
;
;
;

define i64 @test_nested_loop(i64 %n, i64 %m) {
  ; CHECK-LABEL: name: test_nested_loop
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY [[COPY2]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.outer.loop:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[COPY3]], %bb.0, %9, %bb.3
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gpr = PHI [[COPY3]], %bb.0, %8, %bb.3
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gpr = COPY [[COPY4]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.inner.loop:
  ; CHECK-NEXT:   successors: %bb.2(0x7c000000), %bb.3(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:gpr = PHI [[COPY5]], %bb.1, %7, %bb.2
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:gpr = PHI [[COPY5]], %bb.1, %6, %bb.2
  ; CHECK-NEXT:   [[PHI4:%[0-9]+]]:gpr = PHI [[COPY5]], %bb.1, %5, %bb.2
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[PHI4]], [[PHI2]]
  ; CHECK-NEXT:   [[ADDI:%[0-9]+]]:gpr = ADDI [[PHI3]], 1
  ; CHECK-NEXT:   [[ADD1:%[0-9]+]]:gpr = ADD [[PHI2]], [[PHI]]
  ; CHECK-NEXT:   BLT [[ADDI]], [[COPY]], %bb.2
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.outer.latch:
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.4(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADD2:%[0-9]+]]:gpr = ADD [[PHI1]], [[ADD]]
  ; CHECK-NEXT:   [[ADDI1:%[0-9]+]]:gpr = ADDI [[PHI]], 1
  ; CHECK-NEXT:   BLT [[ADDI1]], [[COPY1]], %bb.1
  ; CHECK-NEXT:   PseudoBR %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.exit:
  ; CHECK-NEXT:   $x10 = COPY [[ADD2]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
entry:
  br label %outer.loop

outer.loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %outer.latch ]
  %outer.sum = phi i64 [ 0, %entry ], [ %new.outer.sum, %outer.latch ]
  br label %inner.loop

inner.loop:
  %j = phi i64 [ 0, %outer.loop ], [ %j.next, %inner.loop ]
  %inner.sum = phi i64 [ 0, %outer.loop ], [ %inner.sum.next, %inner.loop ]
  %prod = mul i64 %i, %j
  %inner.sum.next = add i64 %inner.sum, %prod
  %j.next = add i64 %j, 1
  %inner.cmp = icmp slt i64 %j.next, %m
  br i1 %inner.cmp, label %inner.loop, label %outer.latch

outer.latch:
  %new.outer.sum = add i64 %outer.sum, %inner.sum.next
  %i.next = add i64 %i, 1
  %outer.cmp = icmp slt i64 %i.next, %n
  br i1 %outer.cmp, label %outer.loop, label %exit

exit:
  ret i64 %new.outer.sum
}

;
;
;
;

define i64 @test_loop_with_invariant(i64 %n, i64 %k) {
  ; CHECK-LABEL: name: test_loop_with_invariant
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY]], 1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY [[COPY2]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.loop:
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[COPY3]], %bb.0, %6, %bb.1
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gpr = PHI [[COPY3]], %bb.0, %5, %bb.1
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:gpr = PHI [[COPY3]], %bb.0, %4, %bb.1
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[PHI2]], [[PHI]]
  ; CHECK-NEXT:   [[ADDI:%[0-9]+]]:gpr = ADDI [[PHI1]], 1
  ; CHECK-NEXT:   [[ADD1:%[0-9]+]]:gpr = ADD [[PHI]], [[SLLI]]
  ; CHECK-NEXT:   BLT [[ADDI]], [[COPY1]], %bb.1
  ; CHECK-NEXT:   PseudoBR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.exit:
  ; CHECK-NEXT:   $x10 = COPY [[ADD]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
entry:
  %double_k = mul i64 %k, 2
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %sum = phi i64 [ 0, %entry ], [ %sum.next, %loop ]
  ; double_k is loop-invariant and should be live throughout the loop
  %scaled = mul i64 %i, %double_k
  %sum.next = add i64 %sum, %scaled
  %i.next = add i64 %i, 1
  %cmp = icmp slt i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret i64 %sum.next
}
