; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -mtriple riscv64 -mattr=+d -riscv-enable-live-variables \
; RUN: --stop-after=sparse-live-variables < %s | FileCheck %s

; Issue: #166141 Pessimistic MachineLICM due to missing liveness info.

; Check that live variable analysis correctly marks %41 as kill
;

; Check that the loop invariant `fld` is hoisted out of the loop.

define void @f(ptr %p) {
  ; CHECK-LABEL: name: f
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[LUI:%[0-9]+]]:gpr = LUI 2
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[COPY]], killed [[LUI]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.loop:
  ; CHECK-NEXT:   successors: %bb.2(0x50000000), %bb.3(0x30000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[COPY]], %bb.0, %3, %bb.3
  ; CHECK-NEXT:   [[FLD:%[0-9]+]]:fpr64 = FLD [[PHI]], 0 :: (load (s64) from %ir.lsr.iv1)
  ; CHECK-NEXT:   [[FMUL_D:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FLD]], [[FLD]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D1:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D]], [[FMUL_D]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D2:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D1]], [[FMUL_D1]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D3:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D2]], [[FMUL_D2]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D4:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D3]], [[FMUL_D3]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D5:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D4]], [[FMUL_D4]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D6:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D5]], [[FMUL_D5]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D7:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D6]], [[FMUL_D6]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D8:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D7]], [[FMUL_D7]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D9:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D8]], [[FMUL_D8]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D10:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D9]], [[FMUL_D9]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D11:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D10]], [[FMUL_D10]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D12:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D11]], [[FMUL_D11]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D13:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D12]], [[FMUL_D12]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D14:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D13]], [[FMUL_D13]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D15:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D14]], [[FMUL_D14]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D16:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D15]], [[FMUL_D15]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D17:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D16]], [[FMUL_D16]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D18:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D17]], [[FMUL_D17]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D19:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D18]], [[FMUL_D18]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D20:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D19]], [[FMUL_D19]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D21:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D20]], [[FMUL_D20]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D22:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D21]], [[FMUL_D21]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D23:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D22]], [[FMUL_D22]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D24:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D23]], [[FMUL_D23]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D25:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D24]], [[FMUL_D24]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D26:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D25]], [[FMUL_D25]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D27:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D26]], [[FMUL_D26]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D28:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D27]], [[FMUL_D27]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D29:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D28]], [[FMUL_D28]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D30:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D29]], [[FMUL_D29]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_D31:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D30]], [[FMUL_D30]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMV_D_X:%[0-9]+]]:fpr64 = FMV_D_X $x0
  ; CHECK-NEXT:   [[FEQ_D:%[0-9]+]]:gpr = nofpexcept FEQ_D [[FMUL_D31]], killed [[FMV_D_X]]
  ; CHECK-NEXT:   BNE killed [[FEQ_D]], $x0, %bb.3
  ; CHECK-NEXT:   PseudoBR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.if:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LUI1:%[0-9]+]]:gpr = LUI target-flags(riscv-hi) %const.0
  ; CHECK-NEXT:   [[FLD1:%[0-9]+]]:fpr64 = FLD killed [[LUI1]], target-flags(riscv-lo) %const.0 :: (load (s64) from constant-pool)
  ; CHECK-NEXT:   [[FMUL_D32:%[0-9]+]]:fpr64 = nofpexcept FMUL_D [[FMUL_D31]], killed [[FLD1]], 7, implicit $frm
  ; CHECK-NEXT:   FSD killed [[FMUL_D32]], [[PHI]], 0 :: (store (s64) into %ir.lsr.iv1)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.latch:
  ; CHECK-NEXT:   successors: %bb.4(0x04000000), %bb.1(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDI:%[0-9]+]]:gpr = ADDI [[PHI]], 8
  ; CHECK-NEXT:   BNE [[ADDI]], [[ADD]], %bb.1
  ; CHECK-NEXT:   PseudoBR %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.exit:
  ; CHECK-NEXT:   PseudoRET
entry:
  br label %loop

loop:
  %iv = phi i64 [0, %entry], [%iv.next, %latch]

  %gep = getelementptr double, ptr %p, i64 %iv

  %x = load double, ptr %gep
  %y0 = fmul double %x, %x
  %y1 = fmul double %y0, %y0
  %y2 = fmul double %y1, %y1
  %y3 = fmul double %y2, %y2
  %y4 = fmul double %y3, %y3
  %y5 = fmul double %y4, %y4
  %y6 = fmul double %y5, %y5
  %y7 = fmul double %y6, %y6
  %y8 = fmul double %y7, %y7
  %y9 = fmul double %y8, %y8
  %y10 = fmul double %y9, %y9
  %y11 = fmul double %y10, %y10
  %y12 = fmul double %y11, %y11
  %y13 = fmul double %y12, %y12
  %y14 = fmul double %y13, %y13
  %y15 = fmul double %y14, %y14
  %y16 = fmul double %y15, %y15
  %y17 = fmul double %y16, %y16
  %y18 = fmul double %y17, %y17
  %y19 = fmul double %y18, %y18
  %y20 = fmul double %y19, %y19
  %y21 = fmul double %y20, %y20
  %y22 = fmul double %y21, %y21
  %y23 = fmul double %y22, %y22
  %y24 = fmul double %y23, %y23
  %y25 = fmul double %y24, %y24
  %y26 = fmul double %y25, %y25
  %y27 = fmul double %y26, %y26
  %y28 = fmul double %y27, %y27
  %y29 = fmul double %y28, %y28
  %y30 = fmul double %y29, %y29
  %y31 = fmul double %y30, %y30

  %c = fcmp une double %y31, 0.0
  br i1 %c, label %if, label %latch

if:
  %z = fmul double %y31, 3.14159274101257324218750
  store double %z, ptr %gep
  br label %latch

latch:
  %iv.next = add i64 %iv, 1
  %ec = icmp eq i64 %iv.next, 1024
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}
