; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -mtriple=riscv64 -riscv-enable-live-variables -verify-machineinstrs \
; RUN: -riscv-enable-live-variables -stop-after=sparse-live-variables \
; RUN: -o - %s | FileCheck %s

; Test live variable analysis edge cases and special scenarios
; Including: dead code, unreachable blocks, critical edges, and complex phi nodes


define i64 @test_dead_code(i64 %a, i64 %b) {
  ; CHECK-LABEL: name: test_dead_code
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $x10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   $x10 = COPY [[COPY]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
entry:
  %dead = add i64 %a, %b
  ret i64 %a
}

;
;
;
;
;
;
;
;

define i64 @test_critical_edge(i64 %a, i64 %b, i64 %c) {
  ; CHECK-LABEL: name: test_critical_edge
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x50000000), %bb.1(0x30000000)
  ; CHECK-NEXT:   liveins: $x10, $x11, $x12
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x12
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   BLT [[COPY3]], [[COPY2]], %bb.2
  ; CHECK-NEXT:   PseudoBR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.check2:
  ; CHECK-NEXT:   successors: %bb.2(0x50000000), %bb.3(0x30000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   BGE [[COPY4]], [[COPY1]], %bb.3
  ; CHECK-NEXT:   PseudoBR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.then:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   $x10 = COPY [[COPY2]]
  ; CHECK-NEXT:   $x11 = COPY [[COPY1]]
  ; CHECK-NEXT:   PseudoCALL target-flags(riscv-call) &__muldi3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:gpr = COPY [[COPY5]]
  ; CHECK-NEXT:   PseudoBR %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.else:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:gpr = SUB [[COPY2]], [[COPY]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.end:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[SUB]], %bb.3, [[COPY6]], %bb.2
  ; CHECK-NEXT:   $x10 = COPY [[PHI]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
entry:
  %cmp1 = icmp sgt i64 %a, 0
  br i1 %cmp1, label %then, label %check2

check2:
  %cmp2 = icmp sgt i64 %b, 0
  br i1 %cmp2, label %then, label %else

then:
  %mul = mul i64 %a, %b
  br label %end

else:
  %sub = sub i64 %a, %c
  br label %end

end:
  %result = phi i64 [ %mul, %then ], [ %sub, %else ]
  ret i64 %result
}

;
;
;
;
;
;
;
;
;
;

define i64 @test_complex_phi(i64 %a, i64 %b, i64 %c, i64 %d) {
  ; CHECK-LABEL: name: test_complex_phi
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $x10, $x11, $x12, $x13
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x13
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x12
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   BGE [[COPY4]], [[COPY3]], %bb.2
  ; CHECK-NEXT:   PseudoBR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.path1:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[COPY3]], [[COPY2]]
  ; CHECK-NEXT:   PseudoBR %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.path2:
  ; CHECK-NEXT:   successors: %bb.3(0x50000000), %bb.4(0x30000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   BGE [[COPY5]], [[COPY1]], %bb.4
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.path2a:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   $x10 = COPY [[COPY1]]
  ; CHECK-NEXT:   $x11 = COPY [[COPY]]
  ; CHECK-NEXT:   PseudoCALL target-flags(riscv-call) &__muldi3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:gpr = COPY [[COPY6]]
  ; CHECK-NEXT:   PseudoBR %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.path2b:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[SUB:%[0-9]+]]:gpr = SUB [[COPY1]], [[COPY]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.merge:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[SUB]], %bb.4, [[COPY7]], %bb.3, [[ADD]], %bb.1
  ; CHECK-NEXT:   $x10 = COPY [[PHI]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
entry:
  %cmp1 = icmp sgt i64 %a, 0
  br i1 %cmp1, label %path1, label %path2

path1:
  %v1 = add i64 %a, %b
  br label %merge

path2:
  %cmp2 = icmp sgt i64 %c, 0
  br i1 %cmp2, label %path2a, label %path2b

path2a:
  %v2a = mul i64 %c, %d
  br label %merge

path2b:
  %v2b = sub i64 %c, %d
  br label %merge

merge:
  %result = phi i64 [ %v1, %path1 ], [ %v2a, %path2a ], [ %v2b, %path2b ]
  ret i64 %result
}

;

define i64 @test_use_after_def(i64 %a) {
  ; CHECK-LABEL: name: test_use_after_def
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $x10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[ADDI:%[0-9]+]]:gpr = ADDI [[COPY]], 1
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[ADDI]], [[ADDI]]
  ; CHECK-NEXT:   [[ADDI1:%[0-9]+]]:gpr = ADDI killed [[ADD]], 5
  ; CHECK-NEXT:   $x10 = COPY [[ADDI1]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
entry:
  %v1 = add i64 %a, 1
  %v2 = add i64 %v1, 2
  %v3 = add i64 %v2, 3
  %v4 = add i64 %v1, %v3
  ret i64 %v4
}

;

define i64 @test_implicit_defs(i64 %a, i64 %b) {
  ; CHECK-LABEL: name: test_implicit_defs
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $x10, $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   $x10 = COPY [[COPY1]]
  ; CHECK-NEXT:   $x11 = COPY [[COPY]]
  ; CHECK-NEXT:   PseudoCALL target-flags(riscv-call) &__divdi3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   $x10 = COPY [[COPY1]]
  ; CHECK-NEXT:   $x11 = COPY [[COPY]]
  ; CHECK-NEXT:   PseudoCALL target-flags(riscv-call) &__moddi3, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit-def $x2, implicit-def $x10
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[COPY2]], [[COPY3]]
  ; CHECK-NEXT:   $x10 = COPY [[ADD]]
  ; CHECK-NEXT:   PseudoRET implicit $x10
entry:
  %div = sdiv i64 %a, %b
  %rem = srem i64 %a, %b
  %sum = add i64 %div, %rem
  ret i64 %sum
}
