# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv32 -mattr=+Xmipslsp -use-riscv-mips-load-store-pairs=1 \
# RUN:   -run-pass=riscv-load-store-opt %s -o - | FileCheck %s --check-prefix=RV32
# RUN: llc -mtriple=riscv64 -mattr=+Xmipslsp -use-riscv-mips-load-store-pairs=1 \
# RUN:   -run-pass=riscv-load-store-opt %s -o - | FileCheck %s --check-prefix=RV64

--- |
  define void @merge_sb_sb_to_sh() nounwind { ret void }
  define void @merge_sh_sh_to_sw() nounwind { ret void }
  define void @merge_sw_sw_to_sd() nounwind { ret void }
  define void @no_merge_sb_sb_unaligned() nounwind { ret void }
  define void @no_merge_sh_sh_unaligned() nounwind { ret void }
  define void @no_merge_non_adjacent() nounwind { ret void }
  define void @no_merge_non_zero() nounwind { ret void }
  define void @no_merge_volatile() nounwind { ret void }
...
---
name: merge_sb_sb_to_sh
tracksRegLiveness: false
body: |
  bb.0:
    liveins: $x10
    ; RV32-LABEL: name: merge_sb_sb_to_sh
    ; RV32: liveins: $x10
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: SH $x0, $x10, 0 :: (store (s8), align 2), (store (s8))
    ; RV32-NEXT: PseudoRET
    ;
    ; RV64-LABEL: name: merge_sb_sb_to_sh
    ; RV64: liveins: $x10
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: SH $x0, $x10, 0 :: (store (s8), align 2), (store (s8))
    ; RV64-NEXT: PseudoRET
    SB $x0, $x10, 0 :: (store (s8), align 2)
    SB $x0, $x10, 1 :: (store (s8))
    PseudoRET
...
---
name: merge_sh_sh_to_sw
tracksRegLiveness: false
body: |
  bb.0:
    liveins: $x10
    ; RV32-LABEL: name: merge_sh_sh_to_sw
    ; RV32: liveins: $x10
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: SW $x0, $x10, 0 :: (store (s16), align 4), (store (s16))
    ; RV32-NEXT: PseudoRET
    ;
    ; RV64-LABEL: name: merge_sh_sh_to_sw
    ; RV64: liveins: $x10
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: SW $x0, $x10, 0 :: (store (s16), align 4), (store (s16))
    ; RV64-NEXT: PseudoRET
    SH $x0, $x10, 0 :: (store (s16), align 4)
    SH $x0, $x10, 2 :: (store (s16))
    PseudoRET
...
---
name: merge_sw_sw_to_sd
tracksRegLiveness: false
body: |
  bb.0:
    liveins: $x10
    ; RV32-LABEL: name: merge_sw_sw_to_sd
    ; RV32: liveins: $x10
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: MIPS_SWP $x0, $x0, $x10, 0 :: (store (s32), align 8), (store (s32))
    ; RV32-NEXT: PseudoRET
    ;
    ; RV64-LABEL: name: merge_sw_sw_to_sd
    ; RV64: liveins: $x10
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: SD $x0, $x10, 0 :: (store (s32), align 8), (store (s32))
    ; RV64-NEXT: PseudoRET
    SW $x0, $x10, 0 :: (store (s32), align 8)
    SW $x0, $x10, 4 :: (store (s32))
    PseudoRET
...
---
name: no_merge_sb_sb_unaligned
tracksRegLiveness: false
body: |
  bb.0:
    liveins: $x10
    ; RV32-LABEL: name: no_merge_sb_sb_unaligned
    ; RV32: liveins: $x10
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: SB $x0, $x10, 0 :: (store (s8))
    ; RV32-NEXT: SB $x0, $x10, 1 :: (store (s8))
    ; RV32-NEXT: PseudoRET
    ;
    ; RV64-LABEL: name: no_merge_sb_sb_unaligned
    ; RV64: liveins: $x10
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: SB $x0, $x10, 0 :: (store (s8))
    ; RV64-NEXT: SB $x0, $x10, 1 :: (store (s8))
    ; RV64-NEXT: PseudoRET
    SB $x0, $x10, 0 :: (store (s8))
    SB $x0, $x10, 1 :: (store (s8))
    PseudoRET
...
---
name: no_merge_sh_sh_unaligned
tracksRegLiveness: false
body: |
  bb.0:
    liveins: $x10
    ; RV32-LABEL: name: no_merge_sh_sh_unaligned
    ; RV32: liveins: $x10
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: SH $x0, $x10, 0 :: (store (s16))
    ; RV32-NEXT: SH $x0, $x10, 2 :: (store (s16))
    ; RV32-NEXT: PseudoRET
    ;
    ; RV64-LABEL: name: no_merge_sh_sh_unaligned
    ; RV64: liveins: $x10
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: SH $x0, $x10, 0 :: (store (s16))
    ; RV64-NEXT: SH $x0, $x10, 2 :: (store (s16))
    ; RV64-NEXT: PseudoRET
    SH $x0, $x10, 0 :: (store (s16), align 2)
    SH $x0, $x10, 2 :: (store (s16), align 2)
    PseudoRET
...
---
name: no_merge_non_adjacent
tracksRegLiveness: false
body: |
  bb.0:
    liveins: $x10
    ; RV32-LABEL: name: no_merge_non_adjacent
    ; RV32: liveins: $x10
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: SB $x0, $x10, 0 :: (store (s8), align 2)
    ; RV32-NEXT: SB $x0, $x10, 2 :: (store (s8), align 2)
    ; RV32-NEXT: PseudoRET
    ;
    ; RV64-LABEL: name: no_merge_non_adjacent
    ; RV64: liveins: $x10
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: SB $x0, $x10, 0 :: (store (s8), align 2)
    ; RV64-NEXT: SB $x0, $x10, 2 :: (store (s8), align 2)
    ; RV64-NEXT: PseudoRET
    SB $x0, $x10, 0 :: (store (s8), align 2)
    SB $x0, $x10, 2 :: (store (s8), align 2)
    PseudoRET
...
---
name: no_merge_non_zero
tracksRegLiveness: false
body: |
  bb.0:
    liveins: $x10, $x11
    ; RV32-LABEL: name: no_merge_non_zero
    ; RV32: liveins: $x10, $x11
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: SB $x11, $x10, 0 :: (store (s8), align 2)
    ; RV32-NEXT: SB $x11, $x10, 1 :: (store (s8))
    ; RV32-NEXT: PseudoRET
    ;
    ; RV64-LABEL: name: no_merge_non_zero
    ; RV64: liveins: $x10, $x11
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: SB $x11, $x10, 0 :: (store (s8), align 2)
    ; RV64-NEXT: SB $x11, $x10, 1 :: (store (s8))
    ; RV64-NEXT: PseudoRET
    SB $x11, $x10, 0 :: (store (s8), align 2)
    SB $x11, $x10, 1 :: (store (s8))
    PseudoRET
...
---
name: no_merge_volatile
tracksRegLiveness: false
body: |
  bb.0:
    liveins: $x10
    ; RV32-LABEL: name: no_merge_volatile
    ; RV32: liveins: $x10
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: SB $x0, $x10, 0 :: (volatile store (s8), align 2)
    ; RV32-NEXT: SB $x0, $x10, 1 :: (volatile store (s8))
    ; RV32-NEXT: PseudoRET
    ;
    ; RV64-LABEL: name: no_merge_volatile
    ; RV64: liveins: $x10
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: SB $x0, $x10, 0 :: (volatile store (s8), align 2)
    ; RV64-NEXT: SB $x0, $x10, 1 :: (volatile store (s8))
    ; RV64-NEXT: PseudoRET
    SB $x0, $x10, 0 :: (volatile store (s8), align 2)
    SB $x0, $x10, 1 :: (volatile store (s8))
    PseudoRET
...
