; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+d -verify-machineinstrs < %s | FileCheck %s

define double @repro_lean(double %div, double %base) {
; CHECK-LABEL: repro_lean:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    fmv.d.x fa5, zero
; CHECK-NEXT:    lui a1, 38147
; CHECK-NEXT:    addi a1, a1, -112
; CHECK-NEXT:  .LBB0_1: # %for.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    fcvt.d.lu fa4, a0
; CHECK-NEXT:    fmul.d fa4, fa0, fa4
; CHECK-NEXT:    fmadd.d fa4, fa4, fa4, fa1
; CHECK-NEXT:    addi a0, a0, 1
; CHECK-NEXT:    fadd.d fa5, fa4, fa5
; CHECK-NEXT:    bne a0, a1, .LBB0_1
; CHECK-NEXT:  # %bb.2: # %for.end
; CHECK-NEXT:    fmv.d fa0, fa5
; CHECK-NEXT:    ret
entry:
  br label %for.body

for.body:
  %s.0 = phi double [ 0.000000e+00, %entry ], [ %add, %for.body ]
  %i.0 = phi i64 [ 1, %entry ], [ %inc, %for.body ]
  %conv = uitofp nneg i64 %i.0 to double
  %mul = fmul double %div, %conv
  %1 = tail call double @llvm.fmuladd.f64(double %mul, double %mul, double %base)
  %add = fadd double %1, %s.0
  %inc = add nuw nsw i64 %i.0, 1
  %exitcond = icmp eq i64 %inc, 156250000
  br i1 %exitcond, label %for.end, label %for.body

for.end:
  ret double %add
}

declare double @llvm.fmuladd.f64(double, double, double)
