; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 -verify-machineinstrs -mattr=+c < %s \
; RUN: | FileCheck %s -check-prefix=RV32IC
; RUN: llc -mtriple=riscv32 -verify-machineinstrs -mattr=+c,+xqcilsm < %s \
; RUN: | FileCheck %s -check-prefixes=RV32ICXQCILSM
; RUN: llc -mtriple=riscv32 -verify-machineinstrs -mattr=+c,+Xmipslsp -use-riscv-mips-load-store-pairs=1 < %s \
; RUN: | FileCheck %s -check-prefixes=RV32ICXMIPS

  define i32 @load_large_offset(ptr %p) #0 {
; RV32IC-LABEL: load_large_offset:
; RV32IC:       # %bb.0: # %entry
; RV32IC-NEXT:    addi a3, a0, 384
; RV32IC-NEXT:    lw a1, 16(a3)
; RV32IC-NEXT:    lw a2, 20(a3)
; RV32IC-NEXT:    lw a0, 24(a3)
; RV32IC-NEXT:    add a1, a1, a2
; RV32IC-NEXT:    add a0, a0, a1
; RV32IC-NEXT:    ret
;
; RV32ICXQCILSM-LABEL: load_large_offset:
; RV32ICXQCILSM:       # %bb.0: # %entry
; RV32ICXQCILSM-NEXT:    addi a3, a0, 384
; RV32ICXQCILSM-NEXT:    lw a1, 16(a3)
; RV32ICXQCILSM-NEXT:    lw a2, 20(a3)
; RV32ICXQCILSM-NEXT:    lw a0, 24(a3)
; RV32ICXQCILSM-NEXT:    add a1, a1, a2
; RV32ICXQCILSM-NEXT:    add a0, a0, a1
; RV32ICXQCILSM-NEXT:    ret
;
; RV32ICXMIPS-LABEL: load_large_offset:
; RV32ICXMIPS:       # %bb.0: # %entry
; RV32ICXMIPS-NEXT:    addi a3, a0, 384
; RV32ICXMIPS-NEXT:    lw a1, 16(a3)
; RV32ICXMIPS-NEXT:    lw a2, 20(a3)
; RV32ICXMIPS-NEXT:    lw a0, 24(a3)
; RV32ICXMIPS-NEXT:    add a1, a1, a2
; RV32ICXMIPS-NEXT:    add a0, a0, a1
; RV32ICXMIPS-NEXT:    ret
  entry:
    %0 = getelementptr inbounds i32, ptr %p, i32 100
    %a = load i32, ptr %0, align 8
    %1 = getelementptr inbounds i32, ptr %p, i32 101
    %b = load i32, ptr %1, align 8
    %2 = getelementptr inbounds i32, ptr %p, i32 102
    %c = load i32, ptr %2, align 8
    %4 = add i32 %a, %b
    %5 = add i32 %4, %c
    ret i32 %5
  }

  attributes #0 = { minsize }
