; RUN: llc -enable-new-pm -mtriple=riscv32 -O3 -print-pipeline-passes=tree < %s 2>&1 \
; RUN:   | FileCheck %s
; RUN: llc -enable-new-pm -mtriple=riscv64 -O3 -print-pipeline-passes=tree < %s 2>&1 \
; RUN:   | FileCheck %s

; CHECK: require<MachineModuleAnalysis>
; CHECK-NEXT: require<profile-summary>
; CHECK-NEXT: require<collector-metadata>
; CHECK-NEXT: require<runtime-libcall-info>
; CHECK-NEXT: require<libcall-lowering-info>
; CHECK-NEXT: function
; CHECK-NEXT:   objc-arc-contract
; CHECK-NEXT: pre-isel-intrinsic-lowering
; CHECK-NEXT: function
; CHECK-NEXT:   expand-ir-insts<O3>
; CHECK-NEXT:   atomic-expand
; CHECK-NEXT:   loop-data-prefetch
; CHECK-NEXT:   interleaved-access
; CHECK-NEXT:   riscv-codegenprepare
; CHECK-NEXT:   verify
; CHECK-NEXT:   loop
; CHECK-NEXT:     canon-freeze
; CHECK-NEXT:     loop-reduce
; CHECK-NEXT:   gc-lowering
; CHECK-NEXT: shadow-stack-gc-lowering
; CHECK-NEXT: function
; CHECK-NEXT:   unreachableblockelim
; CHECK-NEXT:   consthoist
; CHECK-NEXT:   replace-with-veclib
; CHECK-NEXT:   partially-inline-libcalls
; CHECK-NEXT:   ee-instrument<post-inline>
; CHECK-NEXT:   scalarize-masked-mem-intrin
; CHECK-NEXT:   expand-reductions
; CHECK-NEXT:   typepromotion
; CHECK-NEXT:   codegenprepare
; CHECK-NEXT:   dwarf-eh-prepare
; CHECK-NEXT:   inline-asm-prepare
; CHECK-NEXT:   safe-stack
; CHECK-NEXT:   stack-protector
; CHECK-NEXT:   verify
; CHECK-NEXT: riscv-asm-printer-begin
; CHECK-NEXT: function
; CHECK-NEXT:   machine-function
; CHECK-NEXT:     riscv-isel
; CHECK-NEXT:     finalize-isel
; CHECK-NEXT:     early-machinelicm
; CHECK-NEXT:     early-tailduplication
; CHECK-NEXT:     opt-phis
; CHECK-NEXT:     stack-coloring
; CHECK-NEXT:     localstackalloc
; CHECK-NEXT:     dead-mi-elimination
; CHECK-NEXT:     early-machinelicm
; CHECK-NEXT:     machine-cse
; CHECK-NEXT:     machine-sink
; CHECK-NEXT:     peephole-opt
; CHECK-NEXT:     dead-mi-elimination
; CHECK-NEXT:     detect-dead-lanes
; CHECK-NEXT:     init-undef
; CHECK-NEXT:     process-imp-defs
; CHECK-NEXT:     unreachable-mbb-elimination
; CHECK-NEXT:     require<live-vars>
; CHECK-NEXT:     require<machine-loops>
; CHECK-NEXT:     phi-node-elimination
; CHECK-NEXT:     two-address-instruction
; CHECK-NEXT:     register-coalescer
; CHECK-NEXT:     rename-independent-subregs
; CHECK-NEXT:     machine-scheduler
; CHECK-NEXT:     greedy<all>
; CHECK-NEXT:     virt-reg-rewriter
; CHECK-NEXT:     stack-slot-coloring
; CHECK-NEXT:     machine-cp
; CHECK-NEXT:     machinelicm
; CHECK-NEXT:     remove-redundant-debug-values
; CHECK-NEXT:     fixup-statepoint-caller-saved
; CHECK-NEXT:     postra-machine-sink
; CHECK-NEXT:     shrink-wrap
; CHECK-NEXT:     prolog-epilog
; CHECK-NEXT:     machine-latecleanup
; CHECK-NEXT:     branch-folder
; CHECK-NEXT:     tailduplication
; CHECK-NEXT:     machine-cp
; CHECK-NEXT:     post-ra-pseudos
; CHECK-NEXT:     kcfi
; CHECK-NEXT:     post-RA-sched
; CHECK-NEXT:     block-placement
; CHECK-NEXT:     fentry-insert
; CHECK-NEXT:     xray-instrumentation
; CHECK-NEXT:     patchable-function
; CHECK-NEXT:     machine-cp
; CHECK-NEXT:     branch-relaxation
; CHECK-NEXT:     FuncletLayoutPass
; CHECK-NEXT:     remove-loads-into-fake-uses
; CHECK-NEXT:     StackMapLivenessPass
; CHECK-NEXT:     live-debug-values<emit-debug-entry-values>
; CHECK-NEXT:     machine-sanmd
; CHECK-NEXT: MachineOutlinerPass
; CHECK-NEXT: function
; CHECK-NEXT:   machine-function
; CHECK-NEXT:     stack-frame-layout
; CHECK-NEXT:     unpack-mi-bundles
; CHECK-NEXT:     verify
; CHECK-NEXT:     riscv-asm-printer
; CHECK-NEXT:   free-machine-function
; CHECK-NEXT: riscv-asm-printer-end

define void @f() {
  ret void
}
