# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv64 -run-pass=postra-machine-sink -o - %s | FileCheck %s

---
name:            test_undef_use_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_undef_use_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $x10 = ADDI $x0, 1
  ; CHECK-NEXT:   renamable $x11 = COPY killed renamable $x10, implicit undef $x12
  ; CHECK-NEXT:   $x12 = ADDI $x0, 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoRET implicit $x11
  bb.0:
    successors: %bb.1

    renamable $x10 = ADDI $x0, 1
    renamable $x11 = COPY killed renamable $x10, implicit undef $x12
    $x12 = ADDI $x0, 0

  bb.1:
    liveins: $x11
    PseudoRET implicit $x11
...
---
name:            test_internal_read_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_internal_read_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $x10 = ADDI $x0, 1
  ; CHECK-NEXT:   renamable $x11 = COPY killed renamable $x10, implicit-def $x12, implicit internal $x12
  ; CHECK-NEXT:   $x13 = ADDI $x0, 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $x11
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   PseudoRET implicit $x11
  bb.0:
    successors: %bb.1

    renamable $x10 = ADDI $x0, 1
    renamable $x11 = COPY killed renamable $x10, implicit-def $x12, implicit internal $x12
    $x13 = ADDI $x0, 0

  bb.1:
    liveins: $x11
    PseudoRET implicit $x11
...
