; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=riscv64 -mattr=+m | FileCheck %s

define i32 @signed(i32 %0, ptr %1) {
; CHECK-LABEL: signed:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sraiw a2, a0, 31
; CHECK-NEXT:    srliw a2, a2, 24
; CHECK-NEXT:    add a2, a0, a2
; CHECK-NEXT:    andi a3, a2, -256
; CHECK-NEXT:    sraiw a2, a0, 8
; CHECK-NEXT:    sub a3, a0, a3
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    sw a3, 0(a1)
; CHECK-NEXT:    ret
  %rem = srem i32 %0, 256
  store i32 %rem, ptr %1, align 4
  %div = sdiv exact i32 %0, 256
  ret i32 %div
}

define i32 @unsigned(i32 %0, ptr %1) {
; CHECK-LABEL: unsigned:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a2, 699051
; CHECK-NEXT:    addi a2, a2, -1365
; CHECK-NEXT:    slli a3, a0, 32
; CHECK-NEXT:    slli a4, a2, 32
; CHECK-NEXT:    mulhu a3, a3, a4
; CHECK-NEXT:    srliw a4, a0, 3
; CHECK-NEXT:    srli a3, a3, 36
; CHECK-NEXT:    mulw a2, a4, a2
; CHECK-NEXT:    slli a4, a3, 3
; CHECK-NEXT:    slli a3, a3, 4
; CHECK-NEXT:    add a3, a3, a4
; CHECK-NEXT:    sub a3, a0, a3
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    sw a3, 0(a1)
; CHECK-NEXT:    ret
  %rem = urem i32 %0, 24
  store i32 %rem, ptr %1, align 4
  %div = udiv exact i32 %0, 24
  ret i32 %div
}

define i32 @signed_div_first(i32 %0, ptr %1) {
; CHECK-LABEL: signed_div_first:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sraiw a2, a0, 31
; CHECK-NEXT:    srliw a2, a2, 24
; CHECK-NEXT:    add a3, a0, a2
; CHECK-NEXT:    sraiw a2, a3, 8
; CHECK-NEXT:    andi a3, a3, -256
; CHECK-NEXT:    sub a3, a0, a3
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    sw a3, 0(a1)
; CHECK-NEXT:    ret
  %div = sdiv exact i32 %0, 256
  %rem = srem i32 %0, 256
  store i32 %rem, ptr %1, align 4
  ret i32 %div
}

define i32 @unsigned_div_first(i32 %0, ptr %1) {
; CHECK-LABEL: unsigned_div_first:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a2, 699051
; CHECK-NEXT:    addi a2, a2, -1365
; CHECK-NEXT:    slli a3, a0, 32
; CHECK-NEXT:    slli a2, a2, 32
; CHECK-NEXT:    mulhu a2, a3, a2
; CHECK-NEXT:    srli a2, a2, 36
; CHECK-NEXT:    slli a3, a2, 3
; CHECK-NEXT:    slli a4, a2, 4
; CHECK-NEXT:    add a3, a4, a3
; CHECK-NEXT:    sub a3, a0, a3
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    sw a3, 0(a1)
; CHECK-NEXT:    ret
  %div = udiv exact i32 %0, 24
  %rem = urem i32 %0, 24
  store i32 %rem, ptr %1, align 4
  ret i32 %div
}
