; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=RV32
; RUN: llc -mtriple=riscv64 %s -o - | FileCheck %s --check-prefix=RV64

%Box = type { i32, i32, i32, i8, [3 x i8], i32, i8, [1 x i8], i16, i16, i8, [5 x i8], { i64, ptr }, { i64, ptr }, { i64, ptr } }

define void @test(ptr byval(%Box) %0) nounwind {
; RV32-LABEL: test:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -112
; RV32-NEXT:    sw ra, 108(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s0, 104(sp) # 4-byte Folded Spill
; RV32-NEXT:    addi a0, sp, 24
; RV32-NEXT:    li a2, 80
; RV32-NEXT:    li s0, 0
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    call memcpy
; RV32-NEXT:    addi a3, sp, 24
; RV32-NEXT:    sw zero, 0(sp)
; RV32-NEXT:    sw zero, 4(sp)
; RV32-NEXT:    sw zero, 8(sp)
; RV32-NEXT:    li a0, 0
; RV32-NEXT:    li a1, 0
; RV32-NEXT:    li a2, 0
; RV32-NEXT:    li a4, 0
; RV32-NEXT:    li a5, 0
; RV32-NEXT:    li a6, 0
; RV32-NEXT:    li a7, 0
; RV32-NEXT:    jalr s0
; RV32-NEXT:    lw ra, 108(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s0, 104(sp) # 4-byte Folded Reload
; RV32-NEXT:    addi sp, sp, 112
; RV32-NEXT:    ret
;
; RV64-LABEL: test:
; RV64:       # %bb.0:
; RV64-NEXT:    li a0, 0
; RV64-NEXT:    li a1, 0
; RV64-NEXT:    li a2, 0
; RV64-NEXT:    li a3, 0
; RV64-NEXT:    li a4, 0
; RV64-NEXT:    li a5, 0
; RV64-NEXT:    li a6, 0
; RV64-NEXT:    li a7, 0
; RV64-NEXT:    jr a0
  tail call void null(ptr null, double 0.000000e+00, ptr byval(%Box) null, { i64, ptr } zeroinitializer, i32 0, i64 0, i1 false)
  ret void
}
