; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -verify-machineinstrs < %s | FileCheck -check-prefixes=CHECK %s
; RUN: llc -mtriple=riscv64 -verify-machineinstrs < %s | FileCheck -check-prefixes=CHECK %s
; RUN: llc -mtriple=riscv32 -mattr=+zicbop -verify-machineinstrs < %s | FileCheck -check-prefixes=CHECK %s
; RUN: llc -mtriple=riscv64 -mattr=+zicbop -verify-machineinstrs < %s | FileCheck -check-prefixes=CHECK %s
; RUN: llc -mtriple=riscv64 -mattr=+zicbop,+zihintntl -verify-machineinstrs < %s | FileCheck -check-prefixes=CHECK %s

define void @test_prefetch_read_locality_0(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_read_locality_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    ret
  call void @llvm.prefetch(ptr %a, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_write_locality_0(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_write_locality_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.w 0(a0)
; CHECK-NEXT:    ret
  call void @llvm.prefetch(ptr %a, i32 1, i32 0, i32 1)
  ret void
}

define void @test_prefetch_instruction_locality_0(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_instruction_locality_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.i 0(a0)
; CHECK-NEXT:    ret
  call void @llvm.prefetch(ptr %a, i32 0, i32 0, i32 0)
  ret void
}

define void @test_prefetch_read_locality_1(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_read_locality_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ntl.pall
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    ret
  call void @llvm.prefetch(ptr %a, i32 0, i32 1, i32 1)
  ret void
}

define void @test_prefetch_write_locality_1(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_write_locality_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ntl.pall
; CHECK-NEXT:    prefetch.w 0(a0)
; CHECK-NEXT:    ret
  call void @llvm.prefetch(ptr %a, i32 1, i32 1, i32 1)
  ret void
}

define void @test_prefetch_instruction_locality_1(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_instruction_locality_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ntl.pall
; CHECK-NEXT:    prefetch.i 0(a0)
; CHECK-NEXT:    ret
  call void @llvm.prefetch(ptr %a, i32 0, i32 1, i32 0)
  ret void
}

define void @test_prefetch_read_locality_2(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_read_locality_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ntl.p1
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    ret
  call void @llvm.prefetch(ptr %a, i32 0, i32 2, i32 1)
  ret void
}

define void @test_prefetch_write_locality_2(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_write_locality_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ntl.p1
; CHECK-NEXT:    prefetch.w 0(a0)
; CHECK-NEXT:    ret
  call void @llvm.prefetch(ptr %a, i32 1, i32 2, i32 1)
  ret void
}

define void @test_prefetch_instruction_locality_2(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_instruction_locality_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ntl.p1
; CHECK-NEXT:    prefetch.i 0(a0)
; CHECK-NEXT:    ret
  call void @llvm.prefetch(ptr %a, i32 0, i32 2, i32 0)
  ret void
}

define void @test_prefetch_read_locality_3(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_read_locality_3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    ret
  call void @llvm.prefetch(ptr %a, i32 0, i32 3, i32 1)
  ret void
}

define void @test_prefetch_write_locality_3(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_write_locality_3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    prefetch.w 0(a0)
; CHECK-NEXT:    ret
  call void @llvm.prefetch(ptr %a, i32 1, i32 3, i32 1)
  ret void
}

define void @test_prefetch_instruction_locality_3(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_instruction_locality_3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    prefetch.i 0(a0)
; CHECK-NEXT:    ret
  call void @llvm.prefetch(ptr %a, i32 0, i32 3, i32 0)
  ret void
}

define void @test_prefetch_offsetable_0(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_offsetable_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 2016(a0)
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %a, i64 2016
  call void @llvm.prefetch(ptr %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_1(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_offsetable_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r -2048(a0)
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %a, i64 -2048
  call void @llvm.prefetch(ptr %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_2(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_offsetable_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 32(a0)
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %a, i64 32
  call void @llvm.prefetch(ptr %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_3(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_offsetable_3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r -32(a0)
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %a, i64 -32
  call void @llvm.prefetch(ptr %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_4(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_offsetable_4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a0, a0, 32
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 2016(a0)
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %a, i64 2048
  call void @llvm.prefetch(ptr %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_5(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_offsetable_5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r -2048(a0)
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %a, i64 -2049
  call void @llvm.prefetch(ptr %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_6(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_offsetable_6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %a, i64 16
  call void @llvm.prefetch(ptr %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_7(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_offsetable_7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a0, a0, -16
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %a, i64 -16
  call void @llvm.prefetch(ptr %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_9(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_offsetable_9:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, 1
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 64(a0)
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %a, i64 4160
  call void @llvm.prefetch(ptr %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_8(ptr %a) nounwind {
; CHECK-LABEL: test_prefetch_offsetable_8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, 1048575
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r -64(a0)
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %a, i64 -4160
  call void @llvm.prefetch(ptr %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_0() nounwind {
; CHECK-LABEL: test_prefetch_frameindex_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -512
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 0(sp)
; CHECK-NEXT:    addi sp, sp, 512
; CHECK-NEXT:    ret
  %data = alloca [128 x i32], align 4
  %base = bitcast ptr %data to ptr
  %ptr = getelementptr [128 x i32], ptr %base, i32 0, i32 0
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_1() nounwind {
; CHECK-LABEL: test_prefetch_frameindex_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, 1
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    lui a0, 1
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    ret
  %data = alloca [1024 x i32], align 4
  %ptr = bitcast ptr %data to ptr
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_2() nounwind {
; CHECK-LABEL: test_prefetch_frameindex_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -512
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    addi sp, sp, 512
; CHECK-NEXT:    ret
  %data = alloca [128 x i32], align 4
  %base = bitcast ptr %data to ptr
  %ptr = getelementptr [128 x i32], ptr %base, i32 0, i32 4
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_3() nounwind {
; CHECK-LABEL: test_prefetch_frameindex_3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -512
; CHECK-NEXT:    addi a0, sp, -16
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    addi sp, sp, 512
; CHECK-NEXT:    ret
  %data = alloca [128 x i32], align 4
  %base = bitcast ptr %data to ptr
  %ptr = getelementptr [128 x i32], ptr %base, i32 0, i32 -4
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_4() nounwind {
; CHECK-LABEL: test_prefetch_frameindex_4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -512
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 32(sp)
; CHECK-NEXT:    addi sp, sp, 512
; CHECK-NEXT:    ret
  %data = alloca [128 x i32], align 4
  %base = bitcast ptr %data to ptr
  %ptr = getelementptr [128 x i32], ptr %base, i32 0, i32 8
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_5() nounwind {
; CHECK-LABEL: test_prefetch_frameindex_5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -512
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r -32(sp)
; CHECK-NEXT:    addi sp, sp, 512
; CHECK-NEXT:    ret
  %data = alloca [128 x i32], align 4
  %base = bitcast ptr %data to ptr
  %ptr = getelementptr [128 x i32], ptr %base, i32 0, i32 -8
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_6() nounwind {
; CHECK-LABEL: test_prefetch_frameindex_6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -512
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 2016(sp)
; CHECK-NEXT:    addi sp, sp, 512
; CHECK-NEXT:    ret
  %data = alloca [128 x i32], align 4
  %base = bitcast ptr %data to ptr
  %ptr = getelementptr [128 x i32], ptr %base, i32 0, i32 504
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_7() nounwind {
; CHECK-LABEL: test_prefetch_frameindex_7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -512
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r -2048(sp)
; CHECK-NEXT:    addi sp, sp, 512
; CHECK-NEXT:    ret
  %data = alloca [128 x i32], align 4
  %base = bitcast ptr %data to ptr
  %ptr = getelementptr [128 x i32], ptr %base, i32 0, i32 -512
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_8() nounwind {
; CHECK-LABEL: test_prefetch_frameindex_8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -512
; CHECK-NEXT:    addi a0, sp, 2020
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    addi sp, sp, 512
; CHECK-NEXT:    ret
  %data = alloca [128 x i32], align 4
  %base = bitcast ptr %data to ptr
  %ptr = getelementptr [128 x i32], ptr %base, i32 0, i32 505
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_9() nounwind {
; CHECK-LABEL: test_prefetch_frameindex_9:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -512
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    addi a0, a0, -4
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r -2048(a0)
; CHECK-NEXT:    addi sp, sp, 512
; CHECK-NEXT:    ret
  %data = alloca [128 x i32], align 4
  %base = bitcast ptr %data to ptr
  %ptr = getelementptr [128 x i32], ptr %base, i32 0, i32 -513
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_constant_address_0() nounwind {
; CHECK-LABEL: test_prefetch_constant_address_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, 1
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 32(a0)
; CHECK-NEXT:    ret
  %ptr = inttoptr i64 4128 to ptr
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_constant_address_1() nounwind {
; CHECK-LABEL: test_prefetch_constant_address_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, 1
; CHECK-NEXT:    addi a0, a0, 31
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    ret
  %ptr = inttoptr i64 4127 to ptr
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_constant_address_2() nounwind {
; CHECK-LABEL: test_prefetch_constant_address_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, 1048561
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 32(a0)
; CHECK-NEXT:    ret
  %ptr = inttoptr i64 18446744073709490208 to ptr
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_constant_address_3() nounwind {
; CHECK-LABEL: test_prefetch_constant_address_3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, 1048561
; CHECK-NEXT:    addi a0, a0, 31
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    ret
  %ptr = inttoptr i64 18446744073709490207 to ptr
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

@g = external global [1024 x i32], align 4

define void @test_prefetch_global_0() nounwind {
; CHECK-LABEL: test_prefetch_global_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, %hi(g)
; CHECK-NEXT:    addi a0, a0, %lo(g)
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr @g, i32 0, i32 0
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_1() nounwind {
; CHECK-LABEL: test_prefetch_global_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, %hi(g+16)
; CHECK-NEXT:    addi a0, a0, %lo(g+16)
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr @g, i32 0, i32 4
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_2() nounwind {
; CHECK-LABEL: test_prefetch_global_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, %hi(g-16)
; CHECK-NEXT:    addi a0, a0, %lo(g-16)
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr @g, i32 0, i32 -4
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_3() nounwind {
; CHECK-LABEL: test_prefetch_global_3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, %hi(g)
; CHECK-NEXT:    addi a0, a0, %lo(g)
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 32(a0)
; CHECK-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr @g, i32 0, i32 8
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_4() nounwind {
; CHECK-LABEL: test_prefetch_global_4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, %hi(g)
; CHECK-NEXT:    addi a0, a0, %lo(g)
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r -32(a0)
; CHECK-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr @g, i32 0, i32 -8
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_5() nounwind {
; CHECK-LABEL: test_prefetch_global_5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, %hi(g)
; CHECK-NEXT:    addi a0, a0, %lo(g)
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 2016(a0)
; CHECK-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr @g, i32 0, i32 504
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_6() nounwind {
; CHECK-LABEL: test_prefetch_global_6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, %hi(g)
; CHECK-NEXT:    addi a0, a0, %lo(g)
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r -2048(a0)
; CHECK-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr @g, i32 0, i32 -512
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_7() nounwind {
; CHECK-LABEL: test_prefetch_global_7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, %hi(g+2020)
; CHECK-NEXT:    addi a0, a0, %lo(g+2020)
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r 0(a0)
; CHECK-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr @g, i32 0, i32 505
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_8() nounwind {
; CHECK-LABEL: test_prefetch_global_8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, %hi(g-4)
; CHECK-NEXT:    addi a0, a0, %lo(g-4)
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    prefetch.r -2048(a0)
; CHECK-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr @g, i32 0, i32 -513
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}
