; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 -mattr=+d -target-abi ilp32 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=CHECK32D %s

define double @twice_double(double %1) {
; CHECK32D-LABEL: twice_double:
; CHECK32D:       # %bb.0:
; CHECK32D-NEXT:    addi sp, sp, -16
; CHECK32D-NEXT:    .cfi_def_cfa_offset 16
; CHECK32D-NEXT:    sw a0, 8(sp)
; CHECK32D-NEXT:    sw a1, 12(sp)
; CHECK32D-NEXT:    fld fa5, 8(sp)
; CHECK32D-NEXT:    fadd.d fa5, fa5, fa5
; CHECK32D-NEXT:    fsd fa5, 8(sp)
; CHECK32D-NEXT:    lw a0, 8(sp)
; CHECK32D-NEXT:    lw a1, 12(sp)
; CHECK32D-NEXT:    addi sp, sp, 16
; CHECK32D-NEXT:    .cfi_def_cfa_offset 0
; CHECK32D-NEXT:    ret
    %res = fadd double %1, %1
    ret double %res
}
