; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+zicsr -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32ZICSR

declare i32 @llvm.riscv.csrr(i32 immarg)
declare void @llvm.riscv.csrw(i32 immarg, i32)

define i32 @read() nounwind {
; RV32ZICSR-LABEL: read:
; RV32ZICSR:       # %bb.0:
; RV32ZICSR-NEXT:    csrr a0, fcsr
; RV32ZICSR-NEXT:    csrr a1, fcsr
; RV32ZICSR-NEXT:    csrr a2, stval
; RV32ZICSR-NEXT:    add a1, a1, a2
; RV32ZICSR-NEXT:    add a0, a0, a1
; RV32ZICSR-NEXT:    ret
  %val = call i32 @llvm.riscv.csrr(i32 3)
  %val2 = call i32 @llvm.riscv.csrr(i32 3)
  %val3 = call i32 @llvm.riscv.csrr(i32 323)
  %add = add i32 %val2, %val3
  %ret = add i32 %val, %add
  ret i32 %ret
}

define void @testwrite(i32 %d) nounwind {
; RV32ZICSR-LABEL: testwrite:
; RV32ZICSR:       # %bb.0:
; RV32ZICSR-NEXT:    csrw fcsr, a0
; RV32ZICSR-NEXT:    csrw 3435, a0
; RV32ZICSR-NEXT:    ret
  call void @llvm.riscv.csrw(i32 3, i32 %d)
  call void @llvm.riscv.csrw(i32 3435, i32 %d)
  ret void
}
