; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 | FileCheck %s --check-prefix=CHECK
; RUN: llc < %s -mtriple=riscv64 -mattr=+c | FileCheck %s --check-prefix=RVC

define void @test_shadow_optimization() {
; CHECK-LABEL: test_shadow_optimization:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret
;
; RVC-LABEL: test_shadow_optimization:
; RVC:       # %bb.0: # %entry
; RVC-NEXT:  .Ltmp0:
; RVC-NEXT:    nop
; RVC-NEXT:    nop
; RVC-NEXT:    nop
; RVC-NEXT:    nop
; RVC-NEXT:    nop
; RVC-NEXT:    nop
; RVC-NEXT:    nop
; RVC-NEXT:    ret
entry:
  tail call void (i64, i32, ...) @llvm.experimental.stackmap(i64  0, i32  16)
  ret void
}
