; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+zbc -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64ZBC-ZBKC
; RUN: llc -mtriple=riscv64 -mattr=+zbkc -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64ZBC-ZBKC

; NOTE: This intrinsic has been removed so this tests autoupgrade to llvm.clmul.
define i64 @clmul64(i64 %a, i64 %b) nounwind {
; RV64ZBC-ZBKC-LABEL: clmul64:
; RV64ZBC-ZBKC:       # %bb.0:
; RV64ZBC-ZBKC-NEXT:    clmul a0, a0, a1
; RV64ZBC-ZBKC-NEXT:    ret
  %tmp = call i64 @llvm.riscv.clmul.i64(i64 %a, i64 %b)
  ret i64 %tmp
}

define i64 @clmul64h(i64 %a, i64 %b) nounwind {
; RV64ZBC-ZBKC-LABEL: clmul64h:
; RV64ZBC-ZBKC:       # %bb.0:
; RV64ZBC-ZBKC-NEXT:    clmulh a0, a0, a1
; RV64ZBC-ZBKC-NEXT:    ret
  %tmp = call i64 @llvm.riscv.clmulh.i64(i64 %a, i64 %b)
  ret i64 %tmp
}

; NOTE: This intrinsic has been removed so this tests autoupgrade to llvm.clmul.
define signext i32 @clmul32(i32 signext %a, i32 signext %b) nounwind {
; RV64ZBC-ZBKC-LABEL: clmul32:
; RV64ZBC-ZBKC:       # %bb.0:
; RV64ZBC-ZBKC-NEXT:    clmul a0, a0, a1
; RV64ZBC-ZBKC-NEXT:    sext.w a0, a0
; RV64ZBC-ZBKC-NEXT:    ret
  %tmp = call i32 @llvm.riscv.clmul.i32(i32 %a, i32 %b)
  ret i32 %tmp
}

define signext i32 @clmul32h(i32 signext %a, i32 signext %b) nounwind {
; RV64ZBC-ZBKC-LABEL: clmul32h:
; RV64ZBC-ZBKC:       # %bb.0:
; RV64ZBC-ZBKC-NEXT:    slli a1, a1, 32
; RV64ZBC-ZBKC-NEXT:    slli a0, a0, 32
; RV64ZBC-ZBKC-NEXT:    clmulh a0, a0, a1
; RV64ZBC-ZBKC-NEXT:    srai a0, a0, 32
; RV64ZBC-ZBKC-NEXT:    ret
  %tmp = call i32 @llvm.riscv.clmulh.i32(i32 %a, i32 %b)
  ret i32 %tmp
}

; FIXME: We could avoid the slli instructions by using clmul+srai since the
; inputs are zero extended.
define signext i32 @clmul32h_zext(i32 zeroext %a, i32 zeroext %b) nounwind {
; RV64ZBC-ZBKC-LABEL: clmul32h_zext:
; RV64ZBC-ZBKC:       # %bb.0:
; RV64ZBC-ZBKC-NEXT:    slli a1, a1, 32
; RV64ZBC-ZBKC-NEXT:    slli a0, a0, 32
; RV64ZBC-ZBKC-NEXT:    clmulh a0, a0, a1
; RV64ZBC-ZBKC-NEXT:    srai a0, a0, 32
; RV64ZBC-ZBKC-NEXT:    ret
  %tmp = call i32 @llvm.riscv.clmulh.i32(i32 %a, i32 %b)
  ret i32 %tmp
}

define i64 @llvm_clmul_i64(i64 %a, i64 %b) nounwind {
; RV64ZBC-ZBKC-LABEL: llvm_clmul_i64:
; RV64ZBC-ZBKC:       # %bb.0:
; RV64ZBC-ZBKC-NEXT:    clmul a0, a0, a1
; RV64ZBC-ZBKC-NEXT:    ret
  %tmp = call i64 @llvm.clmul.i64(i64 %a, i64 %b)
  ret i64 %tmp
}

define i64 @llvm_clmulh_i64(i64 %a, i64 %b) nounwind {
; RV64ZBC-ZBKC-LABEL: llvm_clmulh_i64:
; RV64ZBC-ZBKC:       # %bb.0:
; RV64ZBC-ZBKC-NEXT:    clmulh a0, a0, a1
; RV64ZBC-ZBKC-NEXT:    ret
  %tmp1 = zext i64 %a to i128
  %tmp2 = zext i64 %b to i128
  %tmp3 = call i128 @llvm.clmul.i128(i128 %tmp1, i128 %tmp2)
  %tmp4 = lshr i128 %tmp3, 64
  %tmp5 = trunc i128 %tmp4 to i64
  ret i64 %tmp5
}

define signext i32 @llvm_clmul_i32(i32 signext %a, i32 signext %b) nounwind {
; RV64ZBC-ZBKC-LABEL: llvm_clmul_i32:
; RV64ZBC-ZBKC:       # %bb.0:
; RV64ZBC-ZBKC-NEXT:    clmul a0, a0, a1
; RV64ZBC-ZBKC-NEXT:    sext.w a0, a0
; RV64ZBC-ZBKC-NEXT:    ret
  %tmp = call i32 @llvm.clmul.i32(i32 %a, i32 %b)
  ret i32 %tmp
}

define signext i32 @llvm_clmulh_i32(i32 signext %a, i32 signext %b) nounwind {
; RV64ZBC-ZBKC-LABEL: llvm_clmulh_i32:
; RV64ZBC-ZBKC:       # %bb.0:
; RV64ZBC-ZBKC-NEXT:    slli a1, a1, 32
; RV64ZBC-ZBKC-NEXT:    slli a0, a0, 32
; RV64ZBC-ZBKC-NEXT:    clmulh a0, a0, a1
; RV64ZBC-ZBKC-NEXT:    srli a0, a0, 32
; RV64ZBC-ZBKC-NEXT:    ret
  %tmp1 = zext i32 %a to i64
  %tmp2 = zext i32 %b to i64
  %tmp3 = call i64 @llvm.clmul.i64(i64 %tmp1, i64 %tmp2)
  %tmp4 = lshr i64 %tmp3, 32
  %tmp5 = trunc i64 %tmp4 to i32
  ret i32 %tmp5
}
