; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=riscv64 -mattr=+e -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; TODO: Add more tests.

define i64 @exhausted(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i64 %f, i64 %g) {
; CHECK-LABEL: exhausted:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld t0, 0(sp)
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    add a0, a2, a0
; CHECK-NEXT:    add a0, a3, a0
; CHECK-NEXT:    add a0, a4, a0
; CHECK-NEXT:    add a0, a5, a0
; CHECK-NEXT:    add a0, t0, a0
; CHECK-NEXT:    ret
  %1 = add i64 %a, %b
  %2 = add i64 %c, %1
  %3 = add i64 %d, %2
  %4 = add i64 %e, %3
  %5 = add i64 %f, %4
  %6 = add i64 %g, %5
  ret i64 %6
}
