; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+zicsr -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

declare i64 @llvm.riscv.csrr64(i64 immarg)
declare void @llvm.riscv.csrw64(i64 immarg, i64)

define i64 @read() nounwind {
; CHECK-LABEL: read:
; CHECK:       # %bb.0:
; CHECK-NEXT:    csrr a0, fcsr
; CHECK-NEXT:    csrr a1, fcsr
; CHECK-NEXT:    csrr a2, 111
; CHECK-NEXT:    add a1, a1, a2
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    ret
  %val = call i64 @llvm.riscv.csrr64(i64 3)
  %val2 = call i64 @llvm.riscv.csrr64(i64 3)
  %val3 = call i64 @llvm.riscv.csrr64(i64 111)
  %add = add i64 %val2, %val3
  %ret = add i64 %val, %add
  ret i64 %ret
}

define void @testwrite(i64 %d) nounwind {
; CHECK-LABEL: testwrite:
; CHECK:       # %bb.0:
; CHECK-NEXT:    csrw fcsr, a0
; CHECK-NEXT:    csrw 3231, a0
; CHECK-NEXT:    ret
  call void @llvm.riscv.csrw64(i64 3, i64 %d)
  call void @llvm.riscv.csrw64(i64 3231, i64 %d)
  ret void
}
