; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+q -target-abi lp64 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=CHECK32D %s

define fp128 @twice_fp128(fp128 %1) {
; CHECK32D-LABEL: twice_fp128:
; CHECK32D:       # %bb.0:
; CHECK32D-NEXT:    addi sp, sp, -16
; CHECK32D-NEXT:    .cfi_def_cfa_offset 16
; CHECK32D-NEXT:    sd a0, 0(sp)
; CHECK32D-NEXT:    sd a1, 8(sp)
; CHECK32D-NEXT:    flq fa5, 0(sp)
; CHECK32D-NEXT:    fadd.q fa5, fa5, fa5
; CHECK32D-NEXT:    fsq fa5, 0(sp)
; CHECK32D-NEXT:    ld a0, 0(sp)
; CHECK32D-NEXT:    ld a1, 8(sp)
; CHECK32D-NEXT:    addi sp, sp, 16
; CHECK32D-NEXT:    .cfi_def_cfa_offset 0
; CHECK32D-NEXT:    ret
    %res = fadd fp128 %1, %1
    ret fp128 %res
}
