; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p,+m,+zbb \
; RUN:   -verify-machineinstrs < %s | \
; RUN:   FileCheck --check-prefixes=CHECK-RV32 %s
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p,+m,+zbb \
; RUN:   -verify-machineinstrs < %s | \
; RUN:   FileCheck --check-prefixes=CHECK-RV64 %s

define i16 @srl_bitcast_buildvector_extract_last(<2 x i16> %v, ptr %p) {
; CHECK-RV32-LABEL: srl_bitcast_buildvector_extract_last:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    li a2, 1
; CHECK-RV32-NEXT:    srai a3, a0, 16
; CHECK-RV32-NEXT:    div a3, a2, a3
; CHECK-RV32-NEXT:    sext.h a0, a0
; CHECK-RV32-NEXT:    div a0, a2, a0
; CHECK-RV32-NEXT:    pack a2, a0, a3
; CHECK-RV32-NEXT:    srli a0, a2, 16
; CHECK-RV32-NEXT:    sw a2, 0(a1)
; CHECK-RV32-NEXT:    ret
;
; CHECK-RV64-LABEL: srl_bitcast_buildvector_extract_last:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    li a2, 1
; CHECK-RV64-NEXT:    sext.h a3, a0
; CHECK-RV64-NEXT:    divw a3, a2, a3
; CHECK-RV64-NEXT:    slli a0, a0, 32
; CHECK-RV64-NEXT:    srai a0, a0, 48
; CHECK-RV64-NEXT:    divw a2, a2, a0
; CHECK-RV64-NEXT:    sext.h a0, a2
; CHECK-RV64-NEXT:    ppaire.h a2, a3, a2
; CHECK-RV64-NEXT:    sw a2, 0(a1)
; CHECK-RV64-NEXT:    ret
  %div = sdiv <2 x i16> splat (i16 1), %v
  store <2 x i16> %div, ptr %p
  %e = extractelement <2 x i16> %div, i64 1
  ret i16 %e
}
