; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -riscv-enable-p-ext-simd-codegen -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,RV32
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -riscv-enable-p-ext-simd-codegen -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,RV64

define <4 x i8> @test_padd_v4i8(<4 x i8> %a, <4 x i8> %b) {
; CHECK-LABEL: test_padd_v4i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    padd.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call <4 x i8> @llvm.riscv.padd.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %res
}

define <2 x i16> @test_padd_v2i16(<2 x i16> %a, <2 x i16> %b) {
; CHECK-LABEL: test_padd_v2i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    padd.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call <2 x i16> @llvm.riscv.padd.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %res
}

define <8 x i8> @test_padd_v8i8(<8 x i8> %a, <8 x i8> %b) {
; RV32-LABEL: test_padd_v8i8:
; RV32:       # %bb.0:
; RV32-NEXT:    padd.db a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_padd_v8i8:
; RV64:       # %bb.0:
; RV64-NEXT:    padd.b a0, a0, a1
; RV64-NEXT:    ret
  %res = call <8 x i8> @llvm.riscv.padd.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %res
}

define <4 x i16> @test_padd_v4i16(<4 x i16> %a, <4 x i16> %b) {
; RV32-LABEL: test_padd_v4i16:
; RV32:       # %bb.0:
; RV32-NEXT:    padd.dh a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_padd_v4i16:
; RV64:       # %bb.0:
; RV64-NEXT:    padd.h a0, a0, a1
; RV64-NEXT:    ret
  %res = call <4 x i16> @llvm.riscv.padd.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %res
}

define <2 x i32> @test_padd_v2i32(<2 x i32> %a, <2 x i32> %b) {
; RV32-LABEL: test_padd_v2i32:
; RV32:       # %bb.0:
; RV32-NEXT:    padd.dw a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_padd_v2i32:
; RV64:       # %bb.0:
; RV64-NEXT:    padd.w a0, a0, a1
; RV64-NEXT:    ret
  %res = call <2 x i32> @llvm.riscv.padd.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %res
}

define <4 x i8> @test_psub_v4i8(<4 x i8> %a, <4 x i8> %b) {
; CHECK-LABEL: test_psub_v4i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    psub.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call <4 x i8> @llvm.riscv.psub.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %res
}

define <2 x i16> @test_psub_v2i16(<2 x i16> %a, <2 x i16> %b) {
; CHECK-LABEL: test_psub_v2i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    psub.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call <2 x i16> @llvm.riscv.psub.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %res
}

define <8 x i8> @test_psub_v8i8(<8 x i8> %a, <8 x i8> %b) {
; RV32-LABEL: test_psub_v8i8:
; RV32:       # %bb.0:
; RV32-NEXT:    psub.db a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_psub_v8i8:
; RV64:       # %bb.0:
; RV64-NEXT:    psub.b a0, a0, a1
; RV64-NEXT:    ret
  %res = call <8 x i8> @llvm.riscv.psub.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %res
}

define <4 x i16> @test_psub_v4i16(<4 x i16> %a, <4 x i16> %b) {
; RV32-LABEL: test_psub_v4i16:
; RV32:       # %bb.0:
; RV32-NEXT:    psub.dh a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_psub_v4i16:
; RV64:       # %bb.0:
; RV64-NEXT:    psub.h a0, a0, a1
; RV64-NEXT:    ret
  %res = call <4 x i16> @llvm.riscv.psub.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %res
}

define <2 x i32> @test_psub_v2i32(<2 x i32> %a, <2 x i32> %b) {
; RV32-LABEL: test_psub_v2i32:
; RV32:       # %bb.0:
; RV32-NEXT:    psub.dw a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_psub_v2i32:
; RV64:       # %bb.0:
; RV64-NEXT:    psub.w a0, a0, a1
; RV64-NEXT:    ret
  %res = call <2 x i32> @llvm.riscv.psub.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %res
}

declare <4 x i8> @llvm.riscv.padd.v4i8(<4 x i8>, <4 x i8>)
declare <2 x i16> @llvm.riscv.padd.v2i16(<2 x i16>, <2 x i16>)
declare <8 x i8> @llvm.riscv.padd.v8i8(<8 x i8>, <8 x i8>)
declare <4 x i16> @llvm.riscv.padd.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.padd.v2i32(<2 x i32>, <2 x i32>)

declare <4 x i8> @llvm.riscv.psub.v4i8(<4 x i8>, <4 x i8>)
declare <2 x i16> @llvm.riscv.psub.v2i16(<2 x i16>, <2 x i16>)
declare <8 x i8> @llvm.riscv.psub.v8i8(<8 x i8>, <8 x i8>)
declare <4 x i16> @llvm.riscv.psub.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.psub.v2i32(<2 x i32>, <2 x i32>)
