; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc %s -mtriple=riscv64 -riscv-save-csrs-early=true \
; RUN: -stop-after=finalize-isel -o - | FileCheck %s

define void @test0() {
  ; CHECK-LABEL: name: test0
  ; CHECK: bb.0 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $x1, $x8, $x9, $x18, $x19, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x27
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gprjalrnonx7_and_gprnox31 = COPY $x27
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gprjalrnonx7_and_gprnox31 = COPY $x26
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gprjalrnonx7_and_gprnox31 = COPY $x25
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gprjalrnonx7_and_gprnox31 = COPY $x24
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:sr07 = COPY $x23
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:sr07 = COPY $x22
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:sr07 = COPY $x21
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:sr07 = COPY $x20
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:sr07 = COPY $x19
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:sr07 = COPY $x18
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:gprc_and_sr07 = COPY $x9
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:gprc_and_sr07 = COPY $x8
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:gprx1 = COPY $x1
  ; CHECK-NEXT:   $x1 = COPY [[COPY12]]
  ; CHECK-NEXT:   $x8 = COPY [[COPY11]]
  ; CHECK-NEXT:   $x9 = COPY [[COPY10]]
  ; CHECK-NEXT:   $x18 = COPY [[COPY9]]
  ; CHECK-NEXT:   $x19 = COPY [[COPY8]]
  ; CHECK-NEXT:   $x20 = COPY [[COPY7]]
  ; CHECK-NEXT:   $x21 = COPY [[COPY6]]
  ; CHECK-NEXT:   $x22 = COPY [[COPY5]]
  ; CHECK-NEXT:   $x23 = COPY [[COPY4]]
  ; CHECK-NEXT:   $x24 = COPY [[COPY3]]
  ; CHECK-NEXT:   $x25 = COPY [[COPY2]]
  ; CHECK-NEXT:   $x26 = COPY [[COPY1]]
  ; CHECK-NEXT:   $x27 = COPY [[COPY]]
  ; CHECK-NEXT:   PseudoRET implicit $x1, implicit $x8, implicit $x9, implicit $x18, implicit $x19, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24, implicit $x25, implicit $x26, implicit $x27
  ret void
}

declare void @__cxa_throw(ptr, ptr, ptr)

define void @test1(i1 %x, ptr %p0, ptr %p1, ptr %p2) {
  ; CHECK-LABEL: name: test1
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x00000000), %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $x10, $x11, $x12, $x13, $x1, $x8, $x9, $x18, $x19, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x27
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gprjalrnonx7_and_gprnox31 = COPY $x27
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gprjalrnonx7_and_gprnox31 = COPY $x26
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gprjalrnonx7_and_gprnox31 = COPY $x25
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gprjalrnonx7_and_gprnox31 = COPY $x24
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:sr07 = COPY $x23
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:sr07 = COPY $x22
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:sr07 = COPY $x21
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:sr07 = COPY $x20
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:sr07 = COPY $x19
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:sr07 = COPY $x18
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:gprc_and_sr07 = COPY $x9
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:gprc_and_sr07 = COPY $x8
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:gprx1 = COPY $x1
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:gpr = COPY $x13
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:gpr = COPY $x12
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[ANDI:%[0-9]+]]:gpr = ANDI [[COPY16]], 1
  ; CHECK-NEXT:   BEQ killed [[ANDI]], $x0, %bb.2
  ; CHECK-NEXT:   PseudoBR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.throw:
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   $x10 = COPY [[COPY15]]
  ; CHECK-NEXT:   $x11 = COPY [[COPY14]]
  ; CHECK-NEXT:   $x12 = COPY [[COPY13]]
  ; CHECK-NEXT:   PseudoCALL target-flags(riscv-call) @__cxa_throw, csr_ilp32_lp64, implicit-def dead $x1, implicit $x10, implicit $x11, implicit $x12, implicit-def $x2
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
  ; CHECK-NEXT:   $x1 = COPY [[COPY12]]
  ; CHECK-NEXT:   $x8 = COPY [[COPY11]]
  ; CHECK-NEXT:   $x9 = COPY [[COPY10]]
  ; CHECK-NEXT:   $x18 = COPY [[COPY9]]
  ; CHECK-NEXT:   $x19 = COPY [[COPY8]]
  ; CHECK-NEXT:   $x20 = COPY [[COPY7]]
  ; CHECK-NEXT:   $x21 = COPY [[COPY6]]
  ; CHECK-NEXT:   $x22 = COPY [[COPY5]]
  ; CHECK-NEXT:   $x23 = COPY [[COPY4]]
  ; CHECK-NEXT:   $x24 = COPY [[COPY3]]
  ; CHECK-NEXT:   $x25 = COPY [[COPY2]]
  ; CHECK-NEXT:   $x26 = COPY [[COPY1]]
  ; CHECK-NEXT:   $x27 = COPY [[COPY]]
  ; CHECK-NEXT:   UnreachableRET implicit $x1, implicit $x8, implicit $x9, implicit $x18, implicit $x19, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24, implicit $x25, implicit $x26, implicit $x27
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.return:
  ; CHECK-NEXT:   $x1 = COPY [[COPY12]]
  ; CHECK-NEXT:   $x8 = COPY [[COPY11]]
  ; CHECK-NEXT:   $x9 = COPY [[COPY10]]
  ; CHECK-NEXT:   $x18 = COPY [[COPY9]]
  ; CHECK-NEXT:   $x19 = COPY [[COPY8]]
  ; CHECK-NEXT:   $x20 = COPY [[COPY7]]
  ; CHECK-NEXT:   $x21 = COPY [[COPY6]]
  ; CHECK-NEXT:   $x22 = COPY [[COPY5]]
  ; CHECK-NEXT:   $x23 = COPY [[COPY4]]
  ; CHECK-NEXT:   $x24 = COPY [[COPY3]]
  ; CHECK-NEXT:   $x25 = COPY [[COPY2]]
  ; CHECK-NEXT:   $x26 = COPY [[COPY1]]
  ; CHECK-NEXT:   $x27 = COPY [[COPY]]
  ; CHECK-NEXT:   PseudoRET implicit $x1, implicit $x8, implicit $x9, implicit $x18, implicit $x19, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24, implicit $x25, implicit $x26, implicit $x27
entry:
  br i1 %x, label %throw, label %return
throw:
  call void @__cxa_throw(ptr %p0, ptr %p1, ptr %p2)
  unreachable
return:
  ret void
}
