; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 -mattr=+save-restore -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=SR
; RUN: llc -mtriple=riscv32 -mattr=+save-restore,+zilsd -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=SR-ZILSD

define void @fixed_location_sr() nounwind {
; SR-LABEL: fixed_location_sr:
; SR:       # %bb.0: # %entry
; SR-NEXT:    call t0, __riscv_save_5
; SR-NEXT:    #APP
; SR-NEXT:    #NO_APP
; SR-NEXT:    tail __riscv_restore_5
;
; SR-ZILSD-LABEL: fixed_location_sr:
; SR-ZILSD:       # %bb.0: # %entry
; SR-ZILSD-NEXT:    call t0, __riscv_save_5
; SR-ZILSD-NEXT:    addi sp, sp, -16
; SR-ZILSD-NEXT:    sd s2, 8(sp) # 8-byte Folded Spill
; SR-ZILSD-NEXT:    #APP
; SR-ZILSD-NEXT:    #NO_APP
; SR-ZILSD-NEXT:    ld s2, 8(sp) # 8-byte Folded Reload
; SR-ZILSD-NEXT:    addi sp, sp, 16
; SR-ZILSD-NEXT:    tail __riscv_restore_5
entry:
  call void asm sideeffect "", "~{x9},~{x18},~{x19},~{x20}"()
  ret void
}
