; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -verify-machineinstrs -mtriple=riscv32 | FileCheck %s --check-prefixes=RV32I
; RUN: llc < %s -verify-machineinstrs -mtriple=riscv32 -mattr=+xqci,+short-forward-branch-ialu,+short-forward-branch-imul,+short-forward-branch-iload,+short-forward-branch-imm,+m | \
; RUN:   FileCheck %s --check-prefixes=RV32I-SFB-WITH-IMM

define i32 @branch_with_immSFB_mv(i32 %a, i32 %c, i32 %d) {
; RV32I-LABEL: branch_with_immSFB_mv:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a3, 2
; RV32I-NEXT:    addi a3, a3, 1819
; RV32I-NEXT:    bne a2, a3, .LBB0_2
; RV32I-NEXT:  # %bb.1: # %entry
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:  .LBB0_2: # %entry
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_mv:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.bnei a2, 10011, .LBB0_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a1
; RV32I-SFB-WITH-IMM-NEXT:  .LBB0_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %sel = select i1 %x, i32 %a, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_mv_zerofalsev(i32 %a, i32 %c, i32 %d) {
; RV32I-LABEL: branch_with_immSFB_mv_zerofalsev:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, 2
; RV32I-NEXT:    addi a1, a1, 1819
; RV32I-NEXT:    xor a1, a2, a1
; RV32I-NEXT:    seqz a1, a1
; RV32I-NEXT:    addi a1, a1, -1
; RV32I-NEXT:    and a0, a1, a0
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_mv_zerofalsev:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.bnei a2, 10011, .LBB1_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    li a0, 0
; RV32I-SFB-WITH-IMM-NEXT:  .LBB1_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %sel = select i1 %x, i32 %a, i32 0
  ret i32 %sel
}

define i32 @branch_with_immSFB_mv_zerofalsev_swapped(i32 %a, i32 %c, i32 %d) {
; RV32I-LABEL: branch_with_immSFB_mv_zerofalsev_swapped:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, 2
; RV32I-NEXT:    addi a1, a1, 1819
; RV32I-NEXT:    xor a1, a2, a1
; RV32I-NEXT:    snez a1, a1
; RV32I-NEXT:    addi a1, a1, -1
; RV32I-NEXT:    and a0, a1, a0
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_mv_zerofalsev_swapped:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a2, 10011, .LBB2_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    li a0, 0
; RV32I-SFB-WITH-IMM-NEXT:  .LBB2_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %sel = select i1 %x, i32 0, i32 %a
  ret i32 %sel
}

define i32 @branch_with_immSFB_mv_minusOnefalsev(i32 %a, i32 %c, i32 %d) {
; RV32I-LABEL: branch_with_immSFB_mv_minusOnefalsev:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, 2
; RV32I-NEXT:    addi a1, a1, 1819
; RV32I-NEXT:    xor a1, a2, a1
; RV32I-NEXT:    snez a1, a1
; RV32I-NEXT:    addi a1, a1, -1
; RV32I-NEXT:    or a0, a1, a0
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_mv_minusOnefalsev:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    li a1, -1
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.bnei a2, 10011, .LBB3_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a1
; RV32I-SFB-WITH-IMM-NEXT:  .LBB3_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %sel = select i1 %x, i32 %a, i32 -1
  ret i32 %sel
}

define i32 @branch_with_immSFB_mv_minusOnefalsev_swapped(i32 %a, i32 %c, i32 %d) {
; RV32I-LABEL: branch_with_immSFB_mv_minusOnefalsev_swapped:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, 2
; RV32I-NEXT:    addi a1, a1, 1819
; RV32I-NEXT:    xor a1, a2, a1
; RV32I-NEXT:    seqz a1, a1
; RV32I-NEXT:    addi a1, a1, -1
; RV32I-NEXT:    or a0, a1, a0
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_mv_minusOnefalsev_swapped:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    li a1, -1
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a2, 10011, .LBB4_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a1
; RV32I-SFB-WITH-IMM-NEXT:  .LBB4_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %sel = select i1 %x, i32 -1, i32 %a
  ret i32 %sel
}

define i32 @branch_with_immSFB_add(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_add:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a4, 2
; RV32I-NEXT:    addi a4, a4, 1819
; RV32I-NEXT:    beq a3, a4, .LBB5_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    add a2, a0, a1
; RV32I-NEXT:  .LBB5_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_add:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB5_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    add a2, a0, a1
; RV32I-SFB-WITH-IMM-NEXT:  .LBB5_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %addi = add i32 %a, %b
  %sel = select i1 %x, i32 %addi, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_sub(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_sub:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a4, 2
; RV32I-NEXT:    addi a4, a4, 1819
; RV32I-NEXT:    beq a3, a4, .LBB6_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    sub a2, a0, a1
; RV32I-NEXT:  .LBB6_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_sub:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB6_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    sub a2, a0, a1
; RV32I-SFB-WITH-IMM-NEXT:  .LBB6_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %subi = sub i32 %a, %b
  %sel = select i1 %x, i32 %subi, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_shl(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_shl:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a4, 2
; RV32I-NEXT:    addi a4, a4, 1819
; RV32I-NEXT:    beq a3, a4, .LBB7_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    sll a2, a0, a1
; RV32I-NEXT:  .LBB7_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_shl:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB7_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    sll a2, a0, a1
; RV32I-SFB-WITH-IMM-NEXT:  .LBB7_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %shli = shl i32 %a, %b
  %sel = select i1 %x, i32 %shli, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_lshr(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_lshr:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a4, 2
; RV32I-NEXT:    addi a4, a4, 1819
; RV32I-NEXT:    beq a3, a4, .LBB8_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    srl a2, a0, a1
; RV32I-NEXT:  .LBB8_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_lshr:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB8_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    srl a2, a0, a1
; RV32I-SFB-WITH-IMM-NEXT:  .LBB8_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %lshri = lshr i32 %a, %b
  %sel = select i1 %x, i32 %lshri, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_ashr(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_ashr:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a4, 2
; RV32I-NEXT:    addi a4, a4, 1819
; RV32I-NEXT:    beq a3, a4, .LBB9_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    sra a2, a0, a1
; RV32I-NEXT:  .LBB9_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_ashr:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB9_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    sra a2, a0, a1
; RV32I-SFB-WITH-IMM-NEXT:  .LBB9_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %ashri = ashr i32 %a, %b
  %sel = select i1 %x, i32 %ashri, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_xor(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_xor:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a4, 2
; RV32I-NEXT:    addi a4, a4, 1819
; RV32I-NEXT:    beq a3, a4, .LBB10_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    xor a2, a0, a1
; RV32I-NEXT:  .LBB10_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_xor:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB10_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    xor a2, a0, a1
; RV32I-SFB-WITH-IMM-NEXT:  .LBB10_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %xori = xor i32 %a, %b
  %sel = select i1 %x, i32 %xori, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_and(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_and:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a4, 2
; RV32I-NEXT:    addi a4, a4, 1819
; RV32I-NEXT:    beq a3, a4, .LBB11_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    and a2, a0, a1
; RV32I-NEXT:  .LBB11_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_and:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB11_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    and a2, a0, a1
; RV32I-SFB-WITH-IMM-NEXT:  .LBB11_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %andi = and i32 %a, %b
  %sel = select i1 %x, i32 %andi, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_or(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_or:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a4, 2
; RV32I-NEXT:    addi a4, a4, 1819
; RV32I-NEXT:    beq a3, a4, .LBB12_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    or a2, a0, a1
; RV32I-NEXT:  .LBB12_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_or:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB12_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    or a2, a0, a1
; RV32I-SFB-WITH-IMM-NEXT:  .LBB12_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %ori = or i32 %a, %b
  %sel = select i1 %x, i32 %ori, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_addi(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_addi:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, 2
; RV32I-NEXT:    addi a1, a1, 1819
; RV32I-NEXT:    beq a3, a1, .LBB13_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    addi a2, a0, 11
; RV32I-NEXT:  .LBB13_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_addi:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB13_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    addi a2, a0, 11
; RV32I-SFB-WITH-IMM-NEXT:  .LBB13_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %addi = add i32 %a, 11
  %sel = select i1 %x, i32 %addi, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_xori(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_xori:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, 2
; RV32I-NEXT:    addi a1, a1, 1819
; RV32I-NEXT:    beq a3, a1, .LBB14_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    xori a2, a0, 11
; RV32I-NEXT:  .LBB14_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_xori:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB14_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    xori a2, a0, 11
; RV32I-SFB-WITH-IMM-NEXT:  .LBB14_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %xori = xor i32 %a, 11
  %sel = select i1 %x, i32 %xori, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_shli(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_shli:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, 2
; RV32I-NEXT:    addi a1, a1, 1819
; RV32I-NEXT:    beq a3, a1, .LBB15_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    slli a2, a0, 11
; RV32I-NEXT:  .LBB15_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_shli:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB15_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    slli a2, a0, 11
; RV32I-SFB-WITH-IMM-NEXT:  .LBB15_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %shli = shl i32 %a, 11
  %sel = select i1 %x, i32 %shli, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_lshri(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_lshri:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, 2
; RV32I-NEXT:    addi a1, a1, 1819
; RV32I-NEXT:    beq a3, a1, .LBB16_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    srli a2, a0, 11
; RV32I-NEXT:  .LBB16_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_lshri:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB16_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    srli a2, a0, 11
; RV32I-SFB-WITH-IMM-NEXT:  .LBB16_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %lshri = lshr i32 %a, 11
  %sel = select i1 %x, i32 %lshri, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_ashri(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_ashri:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, 2
; RV32I-NEXT:    addi a1, a1, 1819
; RV32I-NEXT:    beq a3, a1, .LBB17_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    srai a2, a0, 11
; RV32I-NEXT:  .LBB17_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_ashri:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB17_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    srai a2, a0, 11
; RV32I-SFB-WITH-IMM-NEXT:  .LBB17_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %ashri = ashr i32 %a, 11
  %sel = select i1 %x, i32 %ashri, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_andi(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_andi:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, 2
; RV32I-NEXT:    addi a1, a1, 1819
; RV32I-NEXT:    beq a3, a1, .LBB18_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    andi a2, a0, 11
; RV32I-NEXT:  .LBB18_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_andi:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB18_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    andi a2, a0, 11
; RV32I-SFB-WITH-IMM-NEXT:  .LBB18_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %andi = and i32 %a, 11
  %sel = select i1 %x, i32 %andi, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_ori(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_ori:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a1, 2
; RV32I-NEXT:    addi a1, a1, 1819
; RV32I-NEXT:    beq a3, a1, .LBB19_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    ori a2, a0, 11
; RV32I-NEXT:  .LBB19_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_ori:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB19_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    ori a2, a0, 11
; RV32I-SFB-WITH-IMM-NEXT:  .LBB19_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %ori = or i32 %a, 11
  %sel = select i1 %x, i32 %ori, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_mul(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) {
; RV32I-LABEL: branch_with_immSFB_mul:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    .cfi_def_cfa_offset 16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s0, 8(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s1, 4(sp) # 4-byte Folded Spill
; RV32I-NEXT:    .cfi_offset ra, -4
; RV32I-NEXT:    .cfi_offset s0, -8
; RV32I-NEXT:    .cfi_offset s1, -12
; RV32I-NEXT:    mv s1, a3
; RV32I-NEXT:    mv s0, a2
; RV32I-NEXT:    call __mulsi3
; RV32I-NEXT:    lui a1, 2
; RV32I-NEXT:    addi a1, a1, 1819
; RV32I-NEXT:    bne s1, a1, .LBB20_2
; RV32I-NEXT:  # %bb.1: # %entry
; RV32I-NEXT:    mv a0, s0
; RV32I-NEXT:  .LBB20_2: # %entry
; RV32I-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s0, 8(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s1, 4(sp) # 4-byte Folded Reload
; RV32I-NEXT:    .cfi_restore ra
; RV32I-NEXT:    .cfi_restore s0
; RV32I-NEXT:    .cfi_restore s1
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    .cfi_def_cfa_offset 0
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_mul:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a3, 10011, .LBB20_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mul a2, a0, a1
; RV32I-SFB-WITH-IMM-NEXT:  .LBB20_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %muli = mul i32 %a, %b
  %sel = select i1 %x, i32 %muli, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_li(i32 %a, i32 %c, i32 %d) {
; RV32I-LABEL: branch_with_immSFB_li:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a0, 2
; RV32I-NEXT:    addi a3, a0, 1819
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:    beq a2, a3, .LBB21_2
; RV32I-NEXT:  # %bb.1: # %entry
; RV32I-NEXT:    lui a0, 16
; RV32I-NEXT:    addi a0, a0, 7
; RV32I-NEXT:  .LBB21_2: # %entry
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_li:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a1
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a2, 10011, .LBB21_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.li a0, 65543
; RV32I-SFB-WITH-IMM-NEXT:  .LBB21_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %sel = select i1 %x, i32 65543, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_qc_e_li(i32 %a, i32 %c, i32 %d) {
; RV32I-LABEL: branch_with_immSFB_qc_e_li:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a0, 2
; RV32I-NEXT:    addi a3, a0, 1819
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:    beq a2, a3, .LBB22_2
; RV32I-NEXT:  # %bb.1: # %entry
; RV32I-NEXT:    lui a0, 1025
; RV32I-NEXT:    addi a0, a0, 528
; RV32I-NEXT:  .LBB22_2: # %entry
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_qc_e_li:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a1
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a2, 10011, .LBB22_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.li a0, 4198928
; RV32I-SFB-WITH-IMM-NEXT:  .LBB22_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %sel = select i1 %x, i32 4198928, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_lui(i32 %a, i32 %c, i32 %d) {
; RV32I-LABEL: branch_with_immSFB_lui:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a0, 2
; RV32I-NEXT:    addi a3, a0, 1819
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:    beq a2, a3, .LBB23_2
; RV32I-NEXT:  # %bb.1: # %entry
; RV32I-NEXT:    lui a0, 16
; RV32I-NEXT:  .LBB23_2: # %entry
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_lui:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a1
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a2, 10011, .LBB23_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    lui a0, 16
; RV32I-SFB-WITH-IMM-NEXT:  .LBB23_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %d, 10011
  %sel = select i1 %x, i32 65536, i32 %c
  ret i32 %sel
}

define i32 @branch_with_immSFB_lb(ptr %base, i32 %a, i32 %b) nounwind {
; RV32I-LABEL: branch_with_immSFB_lb:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a3, 2
; RV32I-NEXT:    addi a3, a3, 1819
; RV32I-NEXT:    beq a1, a3, .LBB24_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    lb a2, 4(a0)
; RV32I-NEXT:  .LBB24_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_lb:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a1, 10011, .LBB24_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    lb a2, 4(a0)
; RV32I-SFB-WITH-IMM-NEXT:  .LBB24_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %a, 10011
  %addr = getelementptr i8, ptr %base, i32 4   ; compute base + 4
  %val = load i8, ptr %addr          ; load 8-bit value
  %ext = sext i8 %val to i32         ; sign-extend to 32 bits
  %res = select i1 %x, i32 %ext, i32 %b
  ret i32 %res
}

define i32 @branch_with_immSFB_lbu(ptr %base, i32 %a, i32 %b) nounwind {
; RV32I-LABEL: branch_with_immSFB_lbu:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a3, 2
; RV32I-NEXT:    addi a3, a3, 1819
; RV32I-NEXT:    beq a1, a3, .LBB25_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    lbu a2, 4(a0)
; RV32I-NEXT:  .LBB25_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_lbu:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a1, 10011, .LBB25_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    lbu a2, 4(a0)
; RV32I-SFB-WITH-IMM-NEXT:  .LBB25_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %a, 10011
  %addr = getelementptr i8, ptr %base, i32 4   ; compute base + 4
  %val = load i8, ptr %addr          ; load 8-bit value
  %ext = zext i8 %val to i32         ; zero-extend to 32 bits
  %res = select i1 %x, i32 %ext, i32 %b
  ret i32 %res
}

define i32 @branch_with_immSFB_lh(ptr %base, i32 %a, i32 %b) nounwind {
; RV32I-LABEL: branch_with_immSFB_lh:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a3, 2
; RV32I-NEXT:    addi a3, a3, 1819
; RV32I-NEXT:    beq a1, a3, .LBB26_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    lh a2, 8(a0)
; RV32I-NEXT:  .LBB26_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_lh:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a1, 10011, .LBB26_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    lh a2, 8(a0)
; RV32I-SFB-WITH-IMM-NEXT:  .LBB26_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %a, 10011
  %addr = getelementptr i16, ptr %base, i32 4   ; compute base + 4
  %val = load i16, ptr %addr          ; load 16-bit value
  %ext = sext i16 %val to i32         ; sign-extend to 32 bits
  %res = select i1 %x, i32 %ext, i32 %b
  ret i32 %res
}

define i32 @branch_with_immSFB_lhu(ptr %base, i32 %a, i32 %b) nounwind {
; RV32I-LABEL: branch_with_immSFB_lhu:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a3, 2
; RV32I-NEXT:    addi a3, a3, 1819
; RV32I-NEXT:    beq a1, a3, .LBB27_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    lhu a2, 8(a0)
; RV32I-NEXT:  .LBB27_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_lhu:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a1, 10011, .LBB27_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    lhu a2, 8(a0)
; RV32I-SFB-WITH-IMM-NEXT:  .LBB27_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %a, 10011
  %addr = getelementptr i16, ptr %base, i32 4   ; compute base + 4
  %val = load i16, ptr %addr          ; load 16-bit value
  %ext = zext i16 %val to i32         ; zero-extend to 32 bits
  %res = select i1 %x, i32 %ext, i32 %b
  ret i32 %res
}

define i32 @branch_with_immSFB_lw(ptr %base, i32 %a, i32 %b) nounwind {
; RV32I-LABEL: branch_with_immSFB_lw:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a3, 2
; RV32I-NEXT:    addi a3, a3, 1819
; RV32I-NEXT:    beq a1, a3, .LBB28_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    lw a2, 16(a0)
; RV32I-NEXT:  .LBB28_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_lw:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a1, 10011, .LBB28_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    lw a2, 16(a0)
; RV32I-SFB-WITH-IMM-NEXT:  .LBB28_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %a, 10011
  %addr = getelementptr i32, ptr %base, i32 4   ; compute base + 4
  %val = load i32, ptr %addr          ; load 32-bit value
  %res = select i1 %x, i32 %val, i32 %b
  ret i32 %res
}

define i32 @branch_with_immSFB_lb_qc_e(ptr %base, i32 %a, i32 %b) nounwind {
; RV32I-LABEL: branch_with_immSFB_lb_qc_e:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a3, 2
; RV32I-NEXT:    addi a4, a3, 1819
; RV32I-NEXT:    beq a1, a4, .LBB29_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    add a0, a0, a3
; RV32I-NEXT:    lb a2, 1808(a0)
; RV32I-NEXT:  .LBB29_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_lb_qc_e:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a1, 10011, .LBB29_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.lb a2, 10000(a0)
; RV32I-SFB-WITH-IMM-NEXT:  .LBB29_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %a, 10011
  %addr = getelementptr i8, ptr %base, i32 10000   ; compute base + 10000
  %val = load i8, ptr %addr          ; load 8-bit value
  %ext = sext i8 %val to i32         ; sign-extend to 32 bits
  %res = select i1 %x, i32 %ext, i32 %b
  ret i32 %res
}

define i32 @branch_with_immSFB_lbu_qc_e(ptr %base, i32 %a, i32 %b) nounwind {
; RV32I-LABEL: branch_with_immSFB_lbu_qc_e:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a3, 2
; RV32I-NEXT:    addi a4, a3, 1819
; RV32I-NEXT:    beq a1, a4, .LBB30_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    add a0, a0, a3
; RV32I-NEXT:    lbu a2, 1808(a0)
; RV32I-NEXT:  .LBB30_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_lbu_qc_e:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a1, 10011, .LBB30_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.lbu a2, 10000(a0)
; RV32I-SFB-WITH-IMM-NEXT:  .LBB30_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %a, 10011
  %addr = getelementptr i8, ptr %base, i32 10000   ; compute base + 10000
  %val = load i8, ptr %addr          ; load 8-bit value
  %ext = zext i8 %val to i32         ; zero-extend to 32 bits
  %res = select i1 %x, i32 %ext, i32 %b
  ret i32 %res
}

define i32 @branch_with_immSFB_lh_qc_e(ptr %base, i32 %a, i32 %b) nounwind {
; RV32I-LABEL: branch_with_immSFB_lh_qc_e:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a3, 2
; RV32I-NEXT:    addi a3, a3, 1819
; RV32I-NEXT:    beq a1, a3, .LBB31_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    lui a1, 5
; RV32I-NEXT:    add a0, a0, a1
; RV32I-NEXT:    lh a2, -480(a0)
; RV32I-NEXT:  .LBB31_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_lh_qc_e:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a1, 10011, .LBB31_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.lh a2, 20000(a0)
; RV32I-SFB-WITH-IMM-NEXT:  .LBB31_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %a, 10011
  %addr = getelementptr i16, ptr %base, i32 10000   ; compute base + 10000
  %val = load i16, ptr %addr          ; load 16-bit value
  %ext = sext i16 %val to i32         ; sign-extend to 32 bits
  %res = select i1 %x, i32 %ext, i32 %b
  ret i32 %res
}

define i32 @branch_with_immSFB_lhu_qc_e(ptr %base, i32 %a, i32 %b) nounwind {
; RV32I-LABEL: branch_with_immSFB_lhu_qc_e:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a3, 2
; RV32I-NEXT:    addi a3, a3, 1819
; RV32I-NEXT:    beq a1, a3, .LBB32_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    lui a1, 5
; RV32I-NEXT:    add a0, a0, a1
; RV32I-NEXT:    lhu a2, -480(a0)
; RV32I-NEXT:  .LBB32_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_lhu_qc_e:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a1, 10011, .LBB32_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.lhu a2, 20000(a0)
; RV32I-SFB-WITH-IMM-NEXT:  .LBB32_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %a, 10011
  %addr = getelementptr i16, ptr %base, i32 10000   ; compute base + 10000
  %val = load i16, ptr %addr          ; load 16-bit value
  %ext = zext i16 %val to i32         ; zero-extend to 32 bits
  %res = select i1 %x, i32 %ext, i32 %b
  ret i32 %res
}

define i32 @branch_with_immSFB_lw_qc_e(ptr %base, i32 %a, i32 %b) nounwind {
; RV32I-LABEL: branch_with_immSFB_lw_qc_e:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a3, 2
; RV32I-NEXT:    addi a3, a3, 1819
; RV32I-NEXT:    beq a1, a3, .LBB33_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    lui a1, 10
; RV32I-NEXT:    add a0, a0, a1
; RV32I-NEXT:    lw a2, -960(a0)
; RV32I-NEXT:  .LBB33_2: # %entry
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    ret
;
; RV32I-SFB-WITH-IMM-LABEL: branch_with_immSFB_lw_qc_e:
; RV32I-SFB-WITH-IMM:       # %bb.0: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.beqi a1, 10011, .LBB33_2
; RV32I-SFB-WITH-IMM-NEXT:  # %bb.1: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    qc.e.lw a2, 40000(a0)
; RV32I-SFB-WITH-IMM-NEXT:  .LBB33_2: # %entry
; RV32I-SFB-WITH-IMM-NEXT:    mv a0, a2
; RV32I-SFB-WITH-IMM-NEXT:    ret
entry:
  %x = icmp ne i32 %a, 10011
  %addr = getelementptr i32, ptr %base, i32 10000   ; compute base + 10000
  %val = load i32, ptr %addr          ; load 32-bit value
  %res = select i1 %x, i32 %val, i32 %b
  ret i32 %res
}
