; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=STRIP %s
; RUN: llc -mtriple=riscv64 -mattr=+m,+no-strip-w-suffix -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=NO-STRIP %s

define i32 @addiw(i32 %a) {
; STRIP-LABEL: addiw:
; STRIP:       # %bb.0:
; STRIP-NEXT:    lui a1, 1
; STRIP-NEXT:    addi a1, a1, -1
; STRIP-NEXT:    addw a0, a0, a1
; STRIP-NEXT:    ret
;
; NO-STRIP-LABEL: addiw:
; NO-STRIP:       # %bb.0:
; NO-STRIP-NEXT:    lui a1, 1
; NO-STRIP-NEXT:    addiw a1, a1, -1
; NO-STRIP-NEXT:    addw a0, a0, a1
; NO-STRIP-NEXT:    ret
  %ret = add i32 %a, 4095
  ret i32 %ret
}

define i32 @addw(i32 %a, i32 %b) {
; STRIP-LABEL: addw:
; STRIP:       # %bb.0:
; STRIP-NEXT:    add a0, a0, a1
; STRIP-NEXT:    addiw a0, a0, 1024
; STRIP-NEXT:    ret
;
; NO-STRIP-LABEL: addw:
; NO-STRIP:       # %bb.0:
; NO-STRIP-NEXT:    addw a0, a0, a1
; NO-STRIP-NEXT:    addiw a0, a0, 1024
; NO-STRIP-NEXT:    ret
  %add = add i32 %a, %b
  %ret = add i32 %add, 1024
  ret i32 %ret
}

define i32 @mulw(i32 %a, i32 %b) {
; STRIP-LABEL: mulw:
; STRIP:       # %bb.0:
; STRIP-NEXT:    mul a0, a0, a1
; STRIP-NEXT:    addiw a0, a0, 1024
; STRIP-NEXT:    ret
;
; NO-STRIP-LABEL: mulw:
; NO-STRIP:       # %bb.0:
; NO-STRIP-NEXT:    mulw a0, a0, a1
; NO-STRIP-NEXT:    addiw a0, a0, 1024
; NO-STRIP-NEXT:    ret
  %mul = mul i32 %a, %b
  %ret = add i32 %mul, 1024
  ret i32 %ret
}

define i32 @slliw(i32 %a) {
; STRIP-LABEL: slliw:
; STRIP:       # %bb.0:
; STRIP-NEXT:    slli a0, a0, 1
; STRIP-NEXT:    addiw a0, a0, 1024
; STRIP-NEXT:    ret
;
; NO-STRIP-LABEL: slliw:
; NO-STRIP:       # %bb.0:
; NO-STRIP-NEXT:    slliw a0, a0, 1
; NO-STRIP-NEXT:    addiw a0, a0, 1024
; NO-STRIP-NEXT:    ret
  %shl = shl i32 %a, 1
  %ret = add i32 %shl, 1024
  ret i32 %ret
}
