; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+v -relocation-model=pic -enable-tlsdesc < %s \
; RUN:     | FileCheck %s --check-prefix=RV64
; RUN: llc -mtriple=riscv32 -mattr=+v -relocation-model=pic -enable-tlsdesc < %s \
; RUN:     | FileCheck %s --check-prefix=RV32

;; Verify that when the V extension is enabled, the TLSDESC resolver clobbers
;; vector CSRs (vl, vtype, vxrm, vxsat) per the psABI.  The compiler must
;; re-emit a vsetvl after the TLSDESC call to recover the vector configuration

@tls_var = external thread_local global i32

define void @test_vector_csr_clobber(ptr %in, ptr %out) nounwind {
; RV64-LABEL: test_vector_csr_clobber:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    mv a2, a0
; RV64-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; RV64-NEXT:    vle32.v v8, (a0)
; RV64-NEXT:  .Ltlsdesc_hi0:
; RV64-NEXT:    auipc a0, %tlsdesc_hi(tls_var)
; RV64-NEXT:    vse32.v v8, (a1)
; RV64-NEXT:    ld a3, %tlsdesc_load_lo(.Ltlsdesc_hi0)(a0)
; RV64-NEXT:    addi a0, a0, %tlsdesc_add_lo(.Ltlsdesc_hi0)
; RV64-NEXT:    jalr t0, 0(a3), %tlsdesc_call(.Ltlsdesc_hi0)
; RV64-NEXT:    add a0, a0, tp
; RV64-NEXT:    li a3, 1
; RV64-NEXT:    sw a3, 0(a0)
; RV64-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; RV64-NEXT:    vle32.v v8, (a2)
; RV64-NEXT:    vse32.v v8, (a1)
; RV64-NEXT:    ret
;
; RV32-LABEL: test_vector_csr_clobber:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    mv a2, a0
; RV32-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; RV32-NEXT:    vle32.v v8, (a0)
; RV32-NEXT:  .Ltlsdesc_hi0:
; RV32-NEXT:    auipc a0, %tlsdesc_hi(tls_var)
; RV32-NEXT:    vse32.v v8, (a1)
; RV32-NEXT:    lw a3, %tlsdesc_load_lo(.Ltlsdesc_hi0)(a0)
; RV32-NEXT:    addi a0, a0, %tlsdesc_add_lo(.Ltlsdesc_hi0)
; RV32-NEXT:    jalr t0, 0(a3), %tlsdesc_call(.Ltlsdesc_hi0)
; RV32-NEXT:    add a0, a0, tp
; RV32-NEXT:    li a3, 1
; RV32-NEXT:    sw a3, 0(a0)
; RV32-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; RV32-NEXT:    vle32.v v8, (a2)
; RV32-NEXT:    vse32.v v8, (a1)
; RV32-NEXT:    ret
entry:
  %v1 = load <4 x i32>, ptr %in
  store <4 x i32> %v1, ptr %out

  store i32 1, ptr @tls_var

  ;; We must re-emit vsetvli here because TLSDESC clobbered it
  %v2 = load <4 x i32>, ptr %in
  store <4 x i32> %v2, ptr %out
  ret void
}
