; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv32 -mattr=+m,+v | FileCheck %s --check-prefix=RV32I
; RUN: llc < %s -mtriple=riscv64 -mattr=+m,+v | FileCheck %s --check-prefix=RV64I
; RUN: llc < %s -mtriple=riscv32 -mattr=+m,+zbb,+v | FileCheck %s --check-prefix=RV32IZbb
; RUN: llc < %s -mtriple=riscv64 -mattr=+m,+zbb,+v | FileCheck %s --check-prefix=RV64IZbb

define signext i32 @func(i32 signext %x, i32 signext %y) nounwind {
; RV32I-LABEL: func:
; RV32I:       # %bb.0:
; RV32I-NEXT:    sub a2, a0, a1
; RV32I-NEXT:    sltu a0, a1, a0
; RV32I-NEXT:    addi a0, a0, -1
; RV32I-NEXT:    and a0, a0, a2
; RV32I-NEXT:    ret
;
; RV64I-LABEL: func:
; RV64I:       # %bb.0:
; RV64I-NEXT:    subw a1, a0, a1
; RV64I-NEXT:    sltu a0, a0, a1
; RV64I-NEXT:    addi a0, a0, -1
; RV64I-NEXT:    and a0, a0, a1
; RV64I-NEXT:    ret
;
; RV32IZbb-LABEL: func:
; RV32IZbb:       # %bb.0:
; RV32IZbb-NEXT:    maxu a0, a0, a1
; RV32IZbb-NEXT:    sub a0, a0, a1
; RV32IZbb-NEXT:    ret
;
; RV64IZbb-LABEL: func:
; RV64IZbb:       # %bb.0:
; RV64IZbb-NEXT:    maxu a0, a0, a1
; RV64IZbb-NEXT:    subw a0, a0, a1
; RV64IZbb-NEXT:    ret
  %tmp = call i32 @llvm.usub.sat.i32(i32 %x, i32 %y);
  ret i32 %tmp;
}

define i64 @func2(i64 %x, i64 %y) nounwind {
; RV32I-LABEL: func2:
; RV32I:       # %bb.0:
; RV32I-NEXT:    sltu a4, a0, a2
; RV32I-NEXT:    sub a3, a1, a3
; RV32I-NEXT:    sub a3, a3, a4
; RV32I-NEXT:    sub a2, a0, a2
; RV32I-NEXT:    beq a3, a1, .LBB1_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    sltu a0, a1, a3
; RV32I-NEXT:    j .LBB1_3
; RV32I-NEXT:  .LBB1_2:
; RV32I-NEXT:    sltu a0, a0, a2
; RV32I-NEXT:  .LBB1_3:
; RV32I-NEXT:    addi a1, a0, -1
; RV32I-NEXT:    and a0, a1, a2
; RV32I-NEXT:    and a1, a1, a3
; RV32I-NEXT:    ret
;
; RV64I-LABEL: func2:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sub a2, a0, a1
; RV64I-NEXT:    sltu a0, a1, a0
; RV64I-NEXT:    addi a0, a0, -1
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    ret
;
; RV32IZbb-LABEL: func2:
; RV32IZbb:       # %bb.0:
; RV32IZbb-NEXT:    sltu a4, a0, a2
; RV32IZbb-NEXT:    sub a3, a1, a3
; RV32IZbb-NEXT:    sub a3, a3, a4
; RV32IZbb-NEXT:    sub a2, a0, a2
; RV32IZbb-NEXT:    beq a3, a1, .LBB1_2
; RV32IZbb-NEXT:  # %bb.1:
; RV32IZbb-NEXT:    sltu a0, a1, a3
; RV32IZbb-NEXT:    j .LBB1_3
; RV32IZbb-NEXT:  .LBB1_2:
; RV32IZbb-NEXT:    sltu a0, a0, a2
; RV32IZbb-NEXT:  .LBB1_3:
; RV32IZbb-NEXT:    addi a1, a0, -1
; RV32IZbb-NEXT:    and a0, a1, a2
; RV32IZbb-NEXT:    and a1, a1, a3
; RV32IZbb-NEXT:    ret
;
; RV64IZbb-LABEL: func2:
; RV64IZbb:       # %bb.0:
; RV64IZbb-NEXT:    maxu a0, a0, a1
; RV64IZbb-NEXT:    sub a0, a0, a1
; RV64IZbb-NEXT:    ret
  %tmp = call i64 @llvm.usub.sat.i64(i64 %x, i64 %y);
  ret i64 %tmp;
}

define zeroext i16 @func16(i16 zeroext %x, i16 zeroext %y) nounwind {
; RV32I-LABEL: func16:
; RV32I:       # %bb.0:
; RV32I-NEXT:    sub a2, a0, a1
; RV32I-NEXT:    sltu a0, a1, a0
; RV32I-NEXT:    addi a0, a0, -1
; RV32I-NEXT:    and a0, a0, a2
; RV32I-NEXT:    ret
;
; RV64I-LABEL: func16:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sub a2, a0, a1
; RV64I-NEXT:    sltu a0, a1, a0
; RV64I-NEXT:    addi a0, a0, -1
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    ret
;
; RV32IZbb-LABEL: func16:
; RV32IZbb:       # %bb.0:
; RV32IZbb-NEXT:    maxu a0, a0, a1
; RV32IZbb-NEXT:    sub a0, a0, a1
; RV32IZbb-NEXT:    ret
;
; RV64IZbb-LABEL: func16:
; RV64IZbb:       # %bb.0:
; RV64IZbb-NEXT:    maxu a0, a0, a1
; RV64IZbb-NEXT:    sub a0, a0, a1
; RV64IZbb-NEXT:    ret
  %tmp = call i16 @llvm.usub.sat.i16(i16 %x, i16 %y);
  ret i16 %tmp;
}

define zeroext i8 @func8(i8 zeroext %x, i8 zeroext %y) nounwind {
; RV32I-LABEL: func8:
; RV32I:       # %bb.0:
; RV32I-NEXT:    sub a2, a0, a1
; RV32I-NEXT:    sltu a0, a1, a0
; RV32I-NEXT:    addi a0, a0, -1
; RV32I-NEXT:    and a0, a0, a2
; RV32I-NEXT:    ret
;
; RV64I-LABEL: func8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sub a2, a0, a1
; RV64I-NEXT:    sltu a0, a1, a0
; RV64I-NEXT:    addi a0, a0, -1
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    ret
;
; RV32IZbb-LABEL: func8:
; RV32IZbb:       # %bb.0:
; RV32IZbb-NEXT:    maxu a0, a0, a1
; RV32IZbb-NEXT:    sub a0, a0, a1
; RV32IZbb-NEXT:    ret
;
; RV64IZbb-LABEL: func8:
; RV64IZbb:       # %bb.0:
; RV64IZbb-NEXT:    maxu a0, a0, a1
; RV64IZbb-NEXT:    sub a0, a0, a1
; RV64IZbb-NEXT:    ret
  %tmp = call i8 @llvm.usub.sat.i8(i8 %x, i8 %y);
  ret i8 %tmp;
}

define zeroext i4 @func3(i4 zeroext %x, i4 zeroext %y) nounwind {
; RV32I-LABEL: func3:
; RV32I:       # %bb.0:
; RV32I-NEXT:    sub a2, a0, a1
; RV32I-NEXT:    sltu a0, a1, a0
; RV32I-NEXT:    addi a0, a0, -1
; RV32I-NEXT:    and a0, a0, a2
; RV32I-NEXT:    ret
;
; RV64I-LABEL: func3:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sub a2, a0, a1
; RV64I-NEXT:    sltu a0, a1, a0
; RV64I-NEXT:    addi a0, a0, -1
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    ret
;
; RV32IZbb-LABEL: func3:
; RV32IZbb:       # %bb.0:
; RV32IZbb-NEXT:    maxu a0, a0, a1
; RV32IZbb-NEXT:    sub a0, a0, a1
; RV32IZbb-NEXT:    ret
;
; RV64IZbb-LABEL: func3:
; RV64IZbb:       # %bb.0:
; RV64IZbb-NEXT:    maxu a0, a0, a1
; RV64IZbb-NEXT:    sub a0, a0, a1
; RV64IZbb-NEXT:    ret
  %tmp = call i4 @llvm.usub.sat.i4(i4 %x, i4 %y);
  ret i4 %tmp;
}

define signext i32 @fun9(i32 signext %x) nounwind {
; RV32I-LABEL: fun9:
; RV32I:       # %bb.0:
; RV32I-NEXT:    snez a1, a0
; RV32I-NEXT:    sub a0, a0, a1
; RV32I-NEXT:    ret
;
; RV64I-LABEL: fun9:
; RV64I:       # %bb.0:
; RV64I-NEXT:    snez a1, a0
; RV64I-NEXT:    subw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV32IZbb-LABEL: fun9:
; RV32IZbb:       # %bb.0:
; RV32IZbb-NEXT:    li a1, 1
; RV32IZbb-NEXT:    maxu a0, a0, a1
; RV32IZbb-NEXT:    addi a0, a0, -1
; RV32IZbb-NEXT:    ret
;
; RV64IZbb-LABEL: fun9:
; RV64IZbb:       # %bb.0:
; RV64IZbb-NEXT:    li a1, 1
; RV64IZbb-NEXT:    maxu a0, a0, a1
; RV64IZbb-NEXT:    addiw a0, a0, -1
; RV64IZbb-NEXT:    ret
  %tmp = call i32 @llvm.usub.sat.i32(i32 %x, i32 1)
  ret i32 %tmp
}

define signext i32 @fun10(i32 signext %x) nounwind {
; RV32I-LABEL: fun10:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: fun10:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32IZbb-LABEL: fun10:
; RV32IZbb:       # %bb.0:
; RV32IZbb-NEXT:    ret
;
; RV64IZbb-LABEL: fun10:
; RV64IZbb:       # %bb.0:
; RV64IZbb-NEXT:    ret
  %tmp = call i32 @llvm.usub.sat.i32(i32 %x, i32 0)
  ret i32 %tmp
}

define signext i32 @fun11(i32 signext %x) nounwind {
; RV32I-LABEL: fun11:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi a1, a0, 1
; RV32I-NEXT:    sltu a0, a0, a1
; RV32I-NEXT:    addi a0, a0, -1
; RV32I-NEXT:    and a0, a0, a1
; RV32I-NEXT:    ret
;
; RV64I-LABEL: fun11:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addiw a1, a0, 1
; RV64I-NEXT:    sltu a0, a0, a1
; RV64I-NEXT:    addi a0, a0, -1
; RV64I-NEXT:    and a0, a0, a1
; RV64I-NEXT:    ret
;
; RV32IZbb-LABEL: fun11:
; RV32IZbb:       # %bb.0:
; RV32IZbb-NEXT:    li a0, 0
; RV32IZbb-NEXT:    ret
;
; RV64IZbb-LABEL: fun11:
; RV64IZbb:       # %bb.0:
; RV64IZbb-NEXT:    li a0, 0
; RV64IZbb-NEXT:    ret
  %tmp = call i32 @llvm.usub.sat.i32(i32 %x, i32 -1)
  ret i32 %tmp
}

define <4 x i32> @fun12(<4 x i32> %a0) nounwind {
; RV32I-LABEL: fun12:
; RV32I:       # %bb.0:
; RV32I-NEXT:    li a0, 1
; RV32I-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; RV32I-NEXT:    vssubu.vx v8, v8, a0
; RV32I-NEXT:    ret
;
; RV64I-LABEL: fun12:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a0, 1
; RV64I-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; RV64I-NEXT:    vssubu.vx v8, v8, a0
; RV64I-NEXT:    ret
;
; RV32IZbb-LABEL: fun12:
; RV32IZbb:       # %bb.0:
; RV32IZbb-NEXT:    li a0, 1
; RV32IZbb-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; RV32IZbb-NEXT:    vssubu.vx v8, v8, a0
; RV32IZbb-NEXT:    ret
;
; RV64IZbb-LABEL: fun12:
; RV64IZbb:       # %bb.0:
; RV64IZbb-NEXT:    li a0, 1
; RV64IZbb-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; RV64IZbb-NEXT:    vssubu.vx v8, v8, a0
; RV64IZbb-NEXT:    ret
  %1 = call <4 x i32> @llvm.usub.sat.v4i32(<4 x i32> %a0, <4 x i32> splat (i32 1))
  ret <4 x i32> %1
}

define <4 x i32> @fun13(<4 x i32> %a0) nounwind {
; RV32I-LABEL: fun13:
; RV32I:       # %bb.0:
; RV32I-NEXT:    li a0, -1
; RV32I-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; RV32I-NEXT:    vssubu.vx v8, v8, a0
; RV32I-NEXT:    ret
;
; RV64I-LABEL: fun13:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a0, -1
; RV64I-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; RV64I-NEXT:    vssubu.vx v8, v8, a0
; RV64I-NEXT:    ret
;
; RV32IZbb-LABEL: fun13:
; RV32IZbb:       # %bb.0:
; RV32IZbb-NEXT:    li a0, -1
; RV32IZbb-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; RV32IZbb-NEXT:    vssubu.vx v8, v8, a0
; RV32IZbb-NEXT:    ret
;
; RV64IZbb-LABEL: fun13:
; RV64IZbb:       # %bb.0:
; RV64IZbb-NEXT:    li a0, -1
; RV64IZbb-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; RV64IZbb-NEXT:    vssubu.vx v8, v8, a0
; RV64IZbb-NEXT:    ret
  %1 = call <4 x i32> @llvm.usub.sat.v4i32(<4 x i32> %a0, <4 x i32> splat (i32 -1))
  ret <4 x i32> %1
}

define <4 x i32> @fun14(<4 x i32> %a0) nounwind {
; RV32I-LABEL: fun14:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: fun14:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32IZbb-LABEL: fun14:
; RV32IZbb:       # %bb.0:
; RV32IZbb-NEXT:    ret
;
; RV64IZbb-LABEL: fun14:
; RV64IZbb:       # %bb.0:
; RV64IZbb-NEXT:    ret
  %1 = call <4 x i32> @llvm.usub.sat.v4i32(<4 x i32> %a0, <4 x i32> splat (i32 0))
  ret <4 x i32> %1
}
