; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+m,+xcvbitmanip -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; This file tests that generic C bitfield idioms are automatically lowered
; to XCVbitmanip instructions without requiring explicit builtin calls.

;===----------------------------------------------------------------------===;
; cv.extractu — unsigned bitfield extract: (x >> offset) & mask
;===----------------------------------------------------------------------===;

; Extract 3 bits starting at bit 4: (x >> 4) & 0x7
define i32 @test_extractu_3_4(i32 %x) {
; CHECK-LABEL: test_extractu_3_4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.extractu a0, a0, 2, 4
; CHECK-NEXT:    ret
  %shr = lshr i32 %x, 4
  %res = and i32 %shr, 7
  ret i32 %res
}

; Extract 8 bits starting at bit 8: (x >> 8) & 0xFF
define i32 @test_extractu_8_8(i32 %x) {
; CHECK-LABEL: test_extractu_8_8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.extractu a0, a0, 7, 8
; CHECK-NEXT:    ret
  %shr = lshr i32 %x, 8
  %res = and i32 %shr, 255
  ret i32 %res
}

; Extract 16 bits starting at bit 16: compiler folds (srl >> 16) & 0xFFFF
; into just srli because the upper 16 bits are already zero after the shift,
; making the AND mask redundant. The AND node is removed before ISel runs.
define i32 @test_extractu_16_16(i32 %x) {
; CHECK-LABEL: test_extractu_16_16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srli a0, a0, 16
; CHECK-NEXT:    ret
  %shr = lshr i32 %x, 16
  %res = and i32 %shr, 65535
  ret i32 %res
}

; Extract 1 bit at bit 31: compiler folds (srl >> 31) & 1 into just srli
; because only bit 0 can be set after a 31-bit logical shift, making the
; AND mask redundant.
define i32 @test_extractu_1_31(i32 %x) {
; CHECK-LABEL: test_extractu_1_31:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srli a0, a0, 31
; CHECK-NEXT:    ret
  %shr = lshr i32 %x, 31
  %res = and i32 %shr, 1
  ret i32 %res
}

; Extract 5 bits at offset 0 (no shift): x & 0x1F
define i32 @test_extractu_5_0(i32 %x) {
; CHECK-LABEL: test_extractu_5_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.extractu a0, a0, 4, 0
; CHECK-NEXT:    ret
  %res = and i32 %x, 31
  ret i32 %res
}

; Excluded: x & 0xFF should NOT become cv.extractu (handled by base ISA zext.b
; or cv.extbz when xcvalu is enabled)
define i32 @test_no_extractu_0xff(i32 %x) {
; CHECK-LABEL: test_no_extractu_0xff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    zext.b a0, a0
; CHECK-NEXT:    ret
  %res = and i32 %x, 255
  ret i32 %res
}

; Excluded: x & 0xFFFF should NOT become cv.extractu (handled by base ISA
; shift pair or cv.exthz when xcvalu is enabled)
define i32 @test_no_extractu_0xffff(i32 %x) {
; CHECK-LABEL: test_no_extractu_0xffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli a0, a0, 16
; CHECK-NEXT:    srli a0, a0, 16
; CHECK-NEXT:    ret
  %res = and i32 %x, 65535
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; cv.extract — signed bitfield extract: (sra (shl x, C1), C2)
;===----------------------------------------------------------------------===;

; Signed extract 4 bits at offset 4: ((int)(x << 24)) >> 28
; C1=24, C2=28 → width=4, offset=4
define i32 @test_extract_4_4(i32 %x) {
; CHECK-LABEL: test_extract_4_4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.extract a0, a0, 3, 4
; CHECK-NEXT:    ret
  %shl = shl i32 %x, 24
  %res = ashr i32 %shl, 28
  ret i32 %res
}

; Signed extract 8 bits at offset 8: ((int)(x << 16)) >> 24
; C1=16, C2=24 → width=8, offset=8
define i32 @test_extract_8_8(i32 %x) {
; CHECK-LABEL: test_extract_8_8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.extract a0, a0, 7, 8
; CHECK-NEXT:    ret
  %shl = shl i32 %x, 16
  %res = ashr i32 %shl, 24
  ret i32 %res
}

; Signed extract 12 bits at offset 4: ((int)(x << 16)) >> 20
; C1=16, C2=20 → width=12, offset=4
define i32 @test_extract_12_4(i32 %x) {
; CHECK-LABEL: test_extract_12_4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.extract a0, a0, 11, 4
; CHECK-NEXT:    ret
  %shl = shl i32 %x, 16
  %res = ashr i32 %shl, 20
  ret i32 %res
}

; Signed extract 1 bit at offset 15 (sign bit of upper halfword):
; C1=16, C2=31 → width=1, offset=15
define i32 @test_extract_1_15(i32 %x) {
; CHECK-LABEL: test_extract_1_15:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.extract a0, a0, 0, 15
; CHECK-NEXT:    ret
  %shl = shl i32 %x, 16
  %res = ashr i32 %shl, 31
  ret i32 %res
}

; Excluded: signed extract of low 8 bits (width=8, offset=0) should NOT become
; cv.extract. Handled by sext_inreg i8 → cv.extbs when xcvalu is enabled, or
; slli+srai pair otherwise.
define i32 @test_no_extract_extbs(i32 %x) {
; CHECK-LABEL: test_no_extract_extbs:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli a0, a0, 24
; CHECK-NEXT:    srai a0, a0, 24
; CHECK-NEXT:    ret
  %shl = shl i32 %x, 24
  %res = ashr i32 %shl, 24
  ret i32 %res
}

; Excluded: signed extract of low 16 bits (width=16, offset=0) should NOT
; become cv.extract. Handled by sext_inreg i16 → cv.exths when xcvalu is
; enabled, or slli+srai pair otherwise.
define i32 @test_no_extract_exths(i32 %x) {
; CHECK-LABEL: test_no_extract_exths:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli a0, a0, 16
; CHECK-NEXT:    srai a0, a0, 16
; CHECK-NEXT:    ret
  %shl = shl i32 %x, 16
  %res = ashr i32 %shl, 16
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; cv.bclr — clear a contiguous range of bits: x & ~(mask << offset)
;===----------------------------------------------------------------------===;

; Clear bits [4:6] (3 bits at offset 4): x & 0xFFFFFF8F
define i32 @test_bclr_3_4(i32 %x) {
; CHECK-LABEL: test_bclr_3_4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.bclr a0, a0, 2, 4
; CHECK-NEXT:    ret
  %res = and i32 %x, -113   ; 0xFFFFFF8F = ~(0x7 << 4)
  ret i32 %res
}

; Clear bit 15 (1 bit at offset 15): x & 0xFFFF7FFF
define i32 @test_bclr_1_15(i32 %x) {
; CHECK-LABEL: test_bclr_1_15:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.bclr a0, a0, 0, 15
; CHECK-NEXT:    ret
  %res = and i32 %x, -32769   ; 0xFFFF7FFF = ~(1 << 15)
  ret i32 %res
}

; Clear bits [8:15] (8 bits at offset 8): x & 0xFFFF00FF
define i32 @test_bclr_8_8(i32 %x) {
; CHECK-LABEL: test_bclr_8_8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.bclr a0, a0, 7, 8
; CHECK-NEXT:    ret
  %res = and i32 %x, -65281   ; 0xFFFF00FF = ~(0xFF << 8)
  ret i32 %res
}

; Clear bits [0:3] (4 bits at offset 0): x & 0xFFFFFFF0
define i32 @test_bclr_4_0(i32 %x) {
; CHECK-LABEL: test_bclr_4_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.bclr a0, a0, 3, 0
; CHECK-NEXT:    ret
  %res = and i32 %x, -16   ; 0xFFFFFFF0 = ~(0xF << 0)
  ret i32 %res
}

; Excluded: x & 0x0000FFFF is a low mask, should NOT become cv.bclr.
; Handled by base ISA shift pair or cv.exthz when xcvalu is enabled.
define i32 @test_no_bclr_exthz(i32 %x) {
; CHECK-LABEL: test_no_bclr_exthz:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli a0, a0, 16
; CHECK-NEXT:    srli a0, a0, 16
; CHECK-NEXT:    ret
  %res = and i32 %x, 65535
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; cv.bset — set a contiguous range of bits: x | (mask << offset)
;===----------------------------------------------------------------------===;

; Set bits [4:6] (3 bits at offset 4): x | 0x70
define i32 @test_bset_3_4(i32 %x) {
; CHECK-LABEL: test_bset_3_4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.bset a0, a0, 2, 4
; CHECK-NEXT:    ret
  %res = or i32 %x, 112   ; 0x70 = 0x7 << 4
  ret i32 %res
}

; Set bit 15: x | 0x8000
define i32 @test_bset_1_15(i32 %x) {
; CHECK-LABEL: test_bset_1_15:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.bset a0, a0, 0, 15
; CHECK-NEXT:    ret
  %res = or i32 %x, 32768   ; 0x8000 = 1 << 15
  ret i32 %res
}

; Set bits [8:15] (8 bits at offset 8): x | 0xFF00
define i32 @test_bset_8_8(i32 %x) {
; CHECK-LABEL: test_bset_8_8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.bset a0, a0, 7, 8
; CHECK-NEXT:    ret
  %res = or i32 %x, 65280   ; 0xFF00 = 0xFF << 8
  ret i32 %res
}

; Set bits [0:3] (4 bits at offset 0): x | 0xF
define i32 @test_bset_4_0(i32 %x) {
; CHECK-LABEL: test_bset_4_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.bset a0, a0, 3, 0
; CHECK-NEXT:    ret
  %res = or i32 %x, 15   ; 0xF = (1 << 4) - 1
  ret i32 %res
}

; Set single bit at MSB: x | 0x80000000
define i32 @test_bset_1_31(i32 %x) {
; CHECK-LABEL: test_bset_1_31:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.bset a0, a0, 0, 31
; CHECK-NEXT:    ret
  %res = or i32 %x, -2147483648   ; 0x80000000 = 1 << 31
  ret i32 %res
}

; Non-contiguous constant (0x55 = 01010101): should NOT become cv.bset,
; falls through to standard ORI lowering.
define i32 @test_no_bset_noncontiguous(i32 %x) {
; CHECK-LABEL: test_no_bset_noncontiguous:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori a0, a0, 85
; CHECK-NEXT:    ret
  %res = or i32 %x, 85   ; 0x55 = 01010101, not a shifted mask
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; cv.insert — insert low bits of rs1 into a bitfield of rd
; C idiom: reg = (reg & ~(mask << offset)) | ((val & mask) << offset)
;===----------------------------------------------------------------------===;

; Insert 3 bits at offset 4: (rd & ~(0x7<<4)) | ((rs1 & 0x7) << 4)
define i32 @test_insert_3_4(i32 %rd, i32 %rs1) {
; CHECK-LABEL: test_insert_3_4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.insert a0, a1, 2, 4
; CHECK-NEXT:    ret
  %clear = and i32 %rd, -113         ; 0xFFFFFF8F = ~(0x7 << 4)
  %masked = and i32 %rs1, 7          ; 0x7 = (1 << 3) - 1
  %shifted = shl i32 %masked, 4
  %res = or i32 %clear, %shifted
  ret i32 %res
}

; Insert 8 bits at offset 8: (rd & ~(0xFF<<8)) | ((rs1 & 0xFF) << 8)
define i32 @test_insert_8_8(i32 %rd, i32 %rs1) {
; CHECK-LABEL: test_insert_8_8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.insert a0, a1, 7, 8
; CHECK-NEXT:    ret
  %clear = and i32 %rd, -65281       ; 0xFFFF00FF = ~(0xFF << 8)
  %masked = and i32 %rs1, 255        ; 0xFF
  %shifted = shl i32 %masked, 8
  %res = or i32 %clear, %shifted
  ret i32 %res
}

; Insert 1 bit at offset 15: (rd & ~(1<<15)) | ((rs1 & 1) << 15)
define i32 @test_insert_1_15(i32 %rd, i32 %rs1) {
; CHECK-LABEL: test_insert_1_15:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.insert a0, a1, 0, 15
; CHECK-NEXT:    ret
  %clear = and i32 %rd, -32769       ; 0xFFFF7FFF = ~(1 << 15)
  %masked = and i32 %rs1, 1
  %shifted = shl i32 %masked, 15
  %res = or i32 %clear, %shifted
  ret i32 %res
}

; Insert 4 bits at offset 0 (no shift): (rd & ~0xF) | (rs1 & 0xF)
define i32 @test_insert_4_0(i32 %rd, i32 %rs1) {
; CHECK-LABEL: test_insert_4_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.insert a0, a1, 3, 0
; CHECK-NEXT:    ret
  %clear = and i32 %rd, -16          ; 0xFFFFFFF0 = ~0xF
  %masked = and i32 %rs1, 15         ; 0xF
  %res = or i32 %clear, %masked
  ret i32 %res
}

; Insert 16 bits at offset 16: the (and rd, 0xFFFF) clear mask gets folded
; into a shift pair by the DAG combiner before ISel, preventing the insert
; pattern from matching. This is a known limitation for width+offset=32 cases
; where the clear mask happens to be a simple low mask.
define i32 @test_insert_16_16(i32 %rd, i32 %rs1) {
; CHECK-LABEL: test_insert_16_16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli a0, a0, 16
; CHECK-NEXT:    srli a0, a0, 16
; CHECK-NEXT:    slli a1, a1, 16
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    ret
  %clear = and i32 %rd, 65535        ; 0x0000FFFF = ~(0xFFFF << 16)
  %masked = and i32 %rs1, 65535      ; 0xFFFF
  %shifted = shl i32 %masked, 16
  %res = or i32 %clear, %shifted
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; Realistic embedded bitfield examples
;===----------------------------------------------------------------------===;

; Read STATUS register bits [3:5] (3-bit field at offset 3)
; Equivalent to: (reg >> 3) & 0x7
define i32 @test_read_status_field(i32 %reg) {
; CHECK-LABEL: test_read_status_field:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.extractu a0, a0, 2, 3
; CHECK-NEXT:    ret
  %shr = lshr i32 %reg, 3
  %field = and i32 %shr, 7
  ret i32 %field
}

; Signed extract of a 10-bit ADC value at bits [2:11]
; Equivalent to: ((int)(x << 20)) >> 22
define i32 @test_signed_adc_extract(i32 %reg) {
; CHECK-LABEL: test_signed_adc_extract:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.extract a0, a0, 9, 2
; CHECK-NEXT:    ret
  %shl = shl i32 %reg, 20
  %res = ashr i32 %shl, 22
  ret i32 %res
}

; Clear an interrupt flag at bit 5
; Equivalent to: reg & ~(1 << 5)
define i32 @test_clear_irq_flag(i32 %reg) {
; CHECK-LABEL: test_clear_irq_flag:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.bclr a0, a0, 0, 5
; CHECK-NEXT:    ret
  %res = and i32 %reg, -33   ; ~(1 << 5) = 0xFFFFFFDF
  ret i32 %res
}

; Set enable bits [8:11] in a control register
; Equivalent to: reg | (0xF << 8)
define i32 @test_set_enable_bits(i32 %reg) {
; CHECK-LABEL: test_set_enable_bits:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.bset a0, a0, 3, 8
; CHECK-NEXT:    ret
  %res = or i32 %reg, 3840   ; 0xF00 = 0xF << 8
  ret i32 %res
}

; Write a 3-bit priority value into STATUS register bits [3:5]
; Equivalent to: reg = (reg & ~(0x7 << 3)) | ((val & 0x7) << 3)
define i32 @test_write_status_field(i32 %reg, i32 %val) {
; CHECK-LABEL: test_write_status_field:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.insert a0, a1, 2, 3
; CHECK-NEXT:    ret
  %clear = and i32 %reg, -57         ; 0xFFFFFFC7 = ~(0x7 << 3)
  %masked = and i32 %val, 7
  %shifted = shl i32 %masked, 3
  %res = or i32 %clear, %shifted
  ret i32 %res
}

; Write a byte into a register's second byte lane (bits [8:15])
; Common pattern for MMIO register writes
define i32 @test_write_byte_lane(i32 %reg, i32 %byte) {
; CHECK-LABEL: test_write_byte_lane:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.insert a0, a1, 7, 8
; CHECK-NEXT:    ret
  %clear = and i32 %reg, -65281      ; 0xFFFF00FF
  %masked = and i32 %byte, 255
  %shifted = shl i32 %masked, 8
  %res = or i32 %clear, %shifted
  ret i32 %res
}
