; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -mattr=+xmipscbop -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=riscv64 -mattr=+xmipscbop -verify-machineinstrs < %s | FileCheck %s

define void @prefetch_data_read(ptr noundef %ptr) nounwind {
; CHECK-LABEL: prefetch_data_read:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    mips.pref 8, 1(a0)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds nuw i8, ptr %ptr, i64 1
  tail call void @llvm.prefetch.p0(ptr nonnull %arrayidx, i32 0, i32 0, i32 1)
  ret void
}

define void @prefetch_data_write(ptr noundef %ptr) nounwind  {
; CHECK-LABEL: prefetch_data_write:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a0, a0, 512
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    mips.pref 9, 0(a0)
; CHECK-NEXT:    ret
  %arrayidx = getelementptr inbounds nuw i8, ptr %ptr, i64 512
  tail call void @llvm.prefetch.p0(ptr nonnull %arrayidx, i32 1, i32 0, i32 1)
  ret void
}

define void @prefetch_inst_read(ptr noundef %ptr) nounwind  {
; CHECK-LABEL: prefetch_inst_read:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
  %arrayidx = getelementptr inbounds nuw i8, ptr %ptr, i64 512
  tail call void @llvm.prefetch.p0(ptr nonnull %arrayidx, i32 0, i32 0, i32 0)
  ret void
}

define void @prefetch_frameindex_test_neg() nounwind {
; CHECK-LABEL: prefetch_frameindex_test_neg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, 1
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    addi a0, sp, 524
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    mips.pref 8, 0(a0)
; CHECK-NEXT:    lui a0, 1
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    ret
  %data = alloca [1024 x i32], align 4
  %ptr = getelementptr [1024 x i32], ptr %data, i32 0, i32 127
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @prefetch_frameindex_test() nounwind {
; CHECK-LABEL: prefetch_frameindex_test:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -512
; CHECK-NEXT:    ntl.all
; CHECK-NEXT:    mips.pref 8, 32(sp)
; CHECK-NEXT:    addi sp, sp, 512
; CHECK-NEXT:    ret
  %data = alloca [128 x i32], align 4
  %base = bitcast ptr %data to ptr
  %ptr = getelementptr [128 x i32], ptr %base, i32 0, i32 8
  call void @llvm.prefetch(ptr %ptr, i32 0, i32 0, i32 1)
  ret void
}
