# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# RUN: llc -mtriple=riscv32 -mattr=+xqccmp -x mir -run-pass=prologepilog -verify-machineinstrs -o - %s \
# RUN: | FileCheck -check-prefixes=CHECK-XQCCMP32 %s
# RUN: llc -mtriple=riscv64 -mattr=+xqccmp -x mir -run-pass=prologepilog -verify-machineinstrs -o - %s \
# RUN: | FileCheck -check-prefixes=CHECK-XQCCMP64 %s
---
name: push_rvlist15
tracksRegLiveness: true
frameInfo:
  maxCallFrameSize: 0
body:                   |
  bb.0:
    ; CHECK-XQCCMP32-LABEL: name: push_rvlist15
    ; CHECK-XQCCMP32: liveins: $x1, $x8, $x9, $x18, $x19, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x27
    ; CHECK-XQCCMP32-NEXT: {{  $}}
    ; CHECK-XQCCMP32-NEXT: frame-setup QC_CM_PUSH 15, 0, implicit-def $x2, implicit $x2, implicit $x1, implicit $x8, implicit $x9, implicit $x18, implicit $x19, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24, implicit $x25, implicit $x26, implicit $x27
    ; CHECK-XQCCMP32-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 64
    ; CHECK-XQCCMP32-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -4
    ; CHECK-XQCCMP32-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -8
    ; CHECK-XQCCMP32-NEXT: frame-setup CFI_INSTRUCTION offset $x9, -12
    ; CHECK-XQCCMP32-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -16
    ; CHECK-XQCCMP32-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -20
    ; CHECK-XQCCMP32-NEXT: frame-setup CFI_INSTRUCTION offset $x20, -24
    ; CHECK-XQCCMP32-NEXT: frame-setup CFI_INSTRUCTION offset $x21, -28
    ; CHECK-XQCCMP32-NEXT: frame-setup CFI_INSTRUCTION offset $x22, -32
    ; CHECK-XQCCMP32-NEXT: frame-setup CFI_INSTRUCTION offset $x23, -36
    ; CHECK-XQCCMP32-NEXT: frame-setup CFI_INSTRUCTION offset $x24, -40
    ; CHECK-XQCCMP32-NEXT: frame-setup CFI_INSTRUCTION offset $x25, -44
    ; CHECK-XQCCMP32-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -48
    ; CHECK-XQCCMP32-NEXT: frame-setup CFI_INSTRUCTION offset $x27, -52
    ; CHECK-XQCCMP32-NEXT: $x1 = IMPLICIT_DEF
    ; CHECK-XQCCMP32-NEXT: $x8 = IMPLICIT_DEF
    ; CHECK-XQCCMP32-NEXT: $x9 = IMPLICIT_DEF
    ; CHECK-XQCCMP32-NEXT: $x18 = IMPLICIT_DEF
    ; CHECK-XQCCMP32-NEXT: $x19 = IMPLICIT_DEF
    ; CHECK-XQCCMP32-NEXT: $x20 = IMPLICIT_DEF
    ; CHECK-XQCCMP32-NEXT: $x21 = IMPLICIT_DEF
    ; CHECK-XQCCMP32-NEXT: $x22 = IMPLICIT_DEF
    ; CHECK-XQCCMP32-NEXT: $x23 = IMPLICIT_DEF
    ; CHECK-XQCCMP32-NEXT: $x24 = IMPLICIT_DEF
    ; CHECK-XQCCMP32-NEXT: $x25 = IMPLICIT_DEF
    ; CHECK-XQCCMP32-NEXT: $x26 = IMPLICIT_DEF
    ; CHECK-XQCCMP32-NEXT: $x27 = IMPLICIT_DEF
    ; CHECK-XQCCMP32-NEXT: frame-destroy QC_CM_POP 15, 0, implicit-def $x2, implicit $x2, implicit-def $x1, implicit-def $x8, implicit-def $x9, implicit-def $x18, implicit-def $x19, implicit-def $x20, implicit-def $x21, implicit-def $x22, implicit-def $x23, implicit-def $x24, implicit-def $x25, implicit-def $x26, implicit-def $x27
    ; CHECK-XQCCMP32-NEXT: PseudoRET
    ;
    ; CHECK-XQCCMP64-LABEL: name: push_rvlist15
    ; CHECK-XQCCMP64: liveins: $x1, $x8, $x9, $x18, $x19, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x27
    ; CHECK-XQCCMP64-NEXT: {{  $}}
    ; CHECK-XQCCMP64-NEXT: frame-setup QC_CM_PUSH 15, 0, implicit-def $x2, implicit $x2, implicit $x1, implicit $x8, implicit $x9, implicit $x18, implicit $x19, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24, implicit $x25, implicit $x26, implicit $x27
    ; CHECK-XQCCMP64-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 112
    ; CHECK-XQCCMP64-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -8
    ; CHECK-XQCCMP64-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -16
    ; CHECK-XQCCMP64-NEXT: frame-setup CFI_INSTRUCTION offset $x9, -24
    ; CHECK-XQCCMP64-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -32
    ; CHECK-XQCCMP64-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -40
    ; CHECK-XQCCMP64-NEXT: frame-setup CFI_INSTRUCTION offset $x20, -48
    ; CHECK-XQCCMP64-NEXT: frame-setup CFI_INSTRUCTION offset $x21, -56
    ; CHECK-XQCCMP64-NEXT: frame-setup CFI_INSTRUCTION offset $x22, -64
    ; CHECK-XQCCMP64-NEXT: frame-setup CFI_INSTRUCTION offset $x23, -72
    ; CHECK-XQCCMP64-NEXT: frame-setup CFI_INSTRUCTION offset $x24, -80
    ; CHECK-XQCCMP64-NEXT: frame-setup CFI_INSTRUCTION offset $x25, -88
    ; CHECK-XQCCMP64-NEXT: frame-setup CFI_INSTRUCTION offset $x26, -96
    ; CHECK-XQCCMP64-NEXT: frame-setup CFI_INSTRUCTION offset $x27, -104
    ; CHECK-XQCCMP64-NEXT: $x1 = IMPLICIT_DEF
    ; CHECK-XQCCMP64-NEXT: $x8 = IMPLICIT_DEF
    ; CHECK-XQCCMP64-NEXT: $x9 = IMPLICIT_DEF
    ; CHECK-XQCCMP64-NEXT: $x18 = IMPLICIT_DEF
    ; CHECK-XQCCMP64-NEXT: $x19 = IMPLICIT_DEF
    ; CHECK-XQCCMP64-NEXT: $x20 = IMPLICIT_DEF
    ; CHECK-XQCCMP64-NEXT: $x21 = IMPLICIT_DEF
    ; CHECK-XQCCMP64-NEXT: $x22 = IMPLICIT_DEF
    ; CHECK-XQCCMP64-NEXT: $x23 = IMPLICIT_DEF
    ; CHECK-XQCCMP64-NEXT: $x24 = IMPLICIT_DEF
    ; CHECK-XQCCMP64-NEXT: $x25 = IMPLICIT_DEF
    ; CHECK-XQCCMP64-NEXT: $x26 = IMPLICIT_DEF
    ; CHECK-XQCCMP64-NEXT: $x27 = IMPLICIT_DEF
    ; CHECK-XQCCMP64-NEXT: frame-destroy QC_CM_POP 15, 0, implicit-def $x2, implicit $x2, implicit-def $x1, implicit-def $x8, implicit-def $x9, implicit-def $x18, implicit-def $x19, implicit-def $x20, implicit-def $x21, implicit-def $x22, implicit-def $x23, implicit-def $x24, implicit-def $x25, implicit-def $x26, implicit-def $x27
    ; CHECK-XQCCMP64-NEXT: PseudoRET
    $x1 = IMPLICIT_DEF
    $x8 = IMPLICIT_DEF
    $x9 = IMPLICIT_DEF
    $x18 = IMPLICIT_DEF
    $x19 = IMPLICIT_DEF
    $x20 = IMPLICIT_DEF
    $x21 = IMPLICIT_DEF
    $x22 = IMPLICIT_DEF
    $x23 = IMPLICIT_DEF
    $x24 = IMPLICIT_DEF
    $x25 = IMPLICIT_DEF
    $x26 = IMPLICIT_DEF
    $x27 = IMPLICIT_DEF
    PseudoRET
...
