; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5

; CodeGenPrepare's splitLargeGEPOffsets queries
; RISCVTargetLowering::isLegalAddressingMode to decide whether a large constant
; GEP offset must be split into a separate base address. Currently, with Xqcilo
; enabled, the offset is reported as not foldable, so the base address is
; computed separately and each access uses a plain lw with a small offset. A
; follow-up extends isLegalAddressingMode to accept 26-bit offsets, after which
; each access folds its full offset into a single qc.e.lw.

; RUN: llc < %s -mtriple=riscv32 | FileCheck %s -check-prefix=RV32I
; RUN: llc < %s -mtriple=riscv32 -mattr=+xqcilo | FileCheck %s -check-prefix=RV32XQCILO

define i32 @split_large_geps(ptr %p, i1 %c) {
; RV32I-LABEL: split_large_geps:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    andi a1, a1, 1
; RV32I-NEXT:    lui a2, 5
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    beqz a1, .LBB0_2
; RV32I-NEXT:  # %bb.1: # %a
; RV32I-NEXT:    lw a0, -480(a0)
; RV32I-NEXT:    ret
; RV32I-NEXT:  .LBB0_2: # %b
; RV32I-NEXT:    lw a0, -476(a0)
; RV32I-NEXT:    ret
;
; RV32XQCILO-LABEL: split_large_geps:
; RV32XQCILO:       # %bb.0: # %entry
; RV32XQCILO-NEXT:    andi a1, a1, 1
; RV32XQCILO-NEXT:    lui a2, 5
; RV32XQCILO-NEXT:    add a0, a0, a2
; RV32XQCILO-NEXT:    beqz a1, .LBB0_2
; RV32XQCILO-NEXT:  # %bb.1: # %a
; RV32XQCILO-NEXT:    lw a0, -480(a0)
; RV32XQCILO-NEXT:    ret
; RV32XQCILO-NEXT:  .LBB0_2: # %b
; RV32XQCILO-NEXT:    lw a0, -476(a0)
; RV32XQCILO-NEXT:    ret
entry:
  br i1 %c, label %a, label %b

a:
  %g0 = getelementptr i8, ptr %p, i32 20000
  %v0 = load i32, ptr %g0
  br label %merge

b:
  %g1 = getelementptr i8, ptr %p, i32 20004
  %v1 = load i32, ptr %g1
  br label %merge

merge:
  %r = phi i32 [ %v0, %a ], [ %v1, %b ]
  ret i32 %r
}
