# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=riscv32 -mattr=+xqcilsm -run-pass=riscv-load-store-opt %s -o - | FileCheck %s

--- |

  define void @lwmi() { ret void }
  define void @lwmi_x0() { ret void }
  define void @lwmi_nonconsecutive() { ret void }
  define void @lwmi_misaligned() { ret void }
  define void @swmi() { ret void }
  define void @swmi_x0() { ret void }
  define void @swmi_nonconsecutive() { ret void }
  define void @swmi_misaligned() { ret void}

  define void @setwmi(ptr %a, ptr %b, ptr %c, ptr %d) {
    entry:
      store i32 0, ptr %a, align 4
      store i32 0, ptr %b, align 4
      store i32 0, ptr %c, align 4
      store i32 0, ptr %d, align 4
      ret void
  }

  define void @setwmi_no_pair_move_insn_back() { ret void }

...
---
name:            lwmi
body:             |
  bb.0:
    liveins: $x10
    ; CHECK-LABEL: name: lwmi
    ; CHECK: liveins: $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x28 = QC_LWMI $x10, 4, 0, implicit-def $x29, implicit-def $x30, implicit-def $x31 :: (load (s32))
    ; CHECK-NEXT: $x10 = ADD $x28, $x29
    ; CHECK-NEXT: $x10 = ADD $x10, $x30
    ; CHECK-NEXT: $x10 = ADD $x10, $x31
    ; CHECK-NEXT: PseudoRET
    $x28 = LW $x10, 0 :: (load (s32), align 4)
    $x29 = LW $x10, 4 :: (load (s32), align 4)
    $x30 = LW $x10, 8 :: (load (s32), align 4)
    $x31 = LW $x10, 12 :: (load (s32), align 4)
    $x10 = ADD $x28, $x29
    $x10 = ADD $x10, $x30
    $x10 = ADD $x10, $x31
    PseudoRET
...
---
name:            lwmi_x0
body:             |
  bb.0:
    liveins: $x10
    ; CHECK-LABEL: name: lwmi_x0
    ; CHECK: liveins: $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x0 = LW $x10, 0 :: (load (s32))
    ; CHECK-NEXT: $x1 = QC_LWMI killed $x10, 3, 4, implicit-def $x2, implicit-def $x3 :: (load (s32))
    ; CHECK-NEXT: PseudoRET
    $x0 = LW $x10, 0 :: (load (s32), align 4)
    $x1 = LW $x10, 4 :: (load (s32), align 4)
    $x2 = LW $x10, 8 :: (load (s32), align 4)
    $x3 = LW killed $x10, 12 :: (load (s32), align 4)
    PseudoRET
...
---
name:            lwmi_nonconsecutive
body:             |
  bb.0:
    liveins: $x10
    ; CHECK-LABEL: name: lwmi_nonconsecutive
    ; CHECK: liveins: $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x28 = LW $x10, 0 :: (load (s32))
    ; CHECK-NEXT: $x30 = LW $x10, 4 :: (load (s32))
    ; CHECK-NEXT: $x29 = LW $x10, 8 :: (load (s32))
    ; CHECK-NEXT: $x31 = LW $x10, 12 :: (load (s32))
    ; CHECK-NEXT: PseudoRET
    $x28 = LW $x10, 0 :: (load (s32), align 4)
    $x29 = LW $x10, 8 :: (load (s32), align 4)
    $x30 = LW $x10, 4 :: (load (s32), align 4)
    $x31 = LW $x10, 12 :: (load (s32), align 4)
    PseudoRET
...
---
name:            lwmi_misaligned
body:             |
  bb.0:
    liveins: $x10
    ; CHECK-LABEL: name: lwmi_misaligned
    ; CHECK: liveins: $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x28 = LW $x10, 2 :: (load (s32))
    ; CHECK-NEXT: $x29 = LW $x10, 6 :: (load (s32))
    ; CHECK-NEXT: $x30 = LW $x10, 10 :: (load (s32))
    ; CHECK-NEXT: PseudoRET
    $x28 = LW $x10, 2 :: (load (s32), align 4)
    $x29 = LW $x10, 6 :: (load (s32), align 4)
    $x30 = LW $x10, 10 :: (load (s32), align 4)
    PseudoRET
...
---
name:            swmi
body:             |
  bb.0:
    liveins: $x10
    ; CHECK-LABEL: name: swmi
    ; CHECK: liveins: $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: QC_SWMI killed $x28, $x10, 4, 0, implicit killed $x29, implicit $x30, implicit killed $x31 :: (store (s32))
    ; CHECK-NEXT: PseudoRET
    SW killed $x28, $x10, 0 :: (store (s32), align 4)
    SW killed $x29, $x10, 4 :: (store (s32), align 4)
    SW $x30, $x10, 8 :: (store (s32), align 4)
    SW killed $x31, $x10, 12 :: (store (s32), align 4)
    PseudoRET
...
---
name:            swmi_x0
body:             |
  bb.0:
    liveins: $x10
    ; CHECK-LABEL: name: swmi_x0
    ; CHECK: liveins: $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: SW $x0, $x10, 0 :: (store (s32))
    ; CHECK-NEXT: QC_SWMI $x1, $x10, 3, 4, implicit $x2, implicit $x3 :: (store (s32))
    ; CHECK-NEXT: PseudoRET
    SW $x0, $x10, 0 :: (store (s32), align 4)
    SW $x1, $x10, 4 :: (store (s32), align 4)
    SW $x2, $x10, 8 :: (store (s32), align 4)
    SW $x3, $x10, 12 :: (store (s32), align 4)
    PseudoRET
...
---
name:            swmi_nonconsecutive
body:             |
  bb.0:
    liveins: $x10
    ; CHECK-LABEL: name: swmi_nonconsecutive
    ; CHECK: liveins: $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: QC_SWMI $x28, $x10, 2, 0, implicit killed $x29 :: (store (s32))
    ; CHECK-NEXT: $x11 = ADDI $x28, 1
    ; CHECK-NEXT: QC_SWMI $x30, $x10, 2, 8, implicit killed $x31 :: (store (s32))
    ; CHECK-NEXT: $x12 = ADDI $x30, 1
    ; CHECK-NEXT: PseudoRET
    SW $x28, $x10, 0 :: (store (s32), align 4)
    $x11 = ADDI $x28, 1
    SW killed $x29, $x10, 4 :: (store (s32), align 4)
    SW $x30, $x10, 8 :: (store (s32), align 4)
    $x12 = ADDI $x30, 1
    SW killed $x31, $x10, 12 :: (store (s32), align 4)
    PseudoRET
...
---
name:            swmi_misaligned
body:             |
  bb.0:
    liveins: $x10
    ; CHECK-LABEL: name: swmi_misaligned
    ; CHECK: liveins: $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: SW $x0, $x10, 0 :: (store (s32))
    ; CHECK-NEXT: SW $x1, $x10, 4 :: (store (s32))
    ; CHECK-NEXT: SW $x2, $x10, 8 :: (store (s32), align 2)
    ; CHECK-NEXT: SW $x3, $x10, 12 :: (store (s32))
    ; CHECK-NEXT: PseudoRET
    SW $x0, $x10, 0 :: (store (s32), align 4)
    SW $x1, $x10, 4 :: (store (s32), align 4)
    SW $x2, $x10, 8 :: (store (s32), align 2)
    SW $x3, $x10, 12 :: (store (s32), align 4)
    PseudoRET
...
---
name:            setwmi
body:             |
  bb.0:
    liveins: $x10
    ; CHECK-LABEL: name: setwmi
    ; CHECK: liveins: $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: QC_SETWMI $x0, $x10, 4, 0 :: (store (s32) into %ir.a), (store (s32) into %ir.b), (store (s32) into %ir.c), (store (s32) into %ir.d)
    ; CHECK-NEXT: PseudoRET
    SW $x0, $x10, 0 :: (store (s32) into %ir.a, align 4)
    SW $x0, $x10, 4 :: (store (s32) into %ir.b, align 4)
    SW $x0, $x10, 8 :: (store (s32) into %ir.c, align 4)
    SW $x0, $x10, 12 :: (store (s32) into %ir.d, align 4)
    PseudoRET
...
---
name:            setwmi_no_pair_move_insn_back
body:             |
  bb.0:
    liveins: $x1, $x2
    ; CHECK-LABEL: name: setwmi_no_pair_move_insn_back
    ; CHECK: liveins: $x1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: SW $x0, $x2, 8 :: (store (s32))
    ; CHECK-NEXT: SW killed $x1, $x2, 12 :: (store (s32))
    ; CHECK-NEXT: QC_SETWMI $x0, $x2, 2, 0 :: (store (s32))
    ; CHECK-NEXT: PseudoRET
    SW killed $x1, $x2, 12 :: (store (s32), align 4)
    SW $x0, $x2, 0 :: (store (s32), align 4)
    SW $x0, $x2, 4 :: (store (s32), align 4)
    SW $x0, $x2, 8 :: (store (s32), align 4)
    PseudoRET
...
