; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+zawrs -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32
; RUN: llc -mtriple=riscv64 -mattr=+zawrs -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64

define void @wrs_nto() {
; RV32-LABEL: wrs_nto:
; RV32:       # %bb.0:
; RV32-NEXT:    wrs.nto
; RV32-NEXT:    ret
;
; RV64-LABEL: wrs_nto:
; RV64:       # %bb.0:
; RV64-NEXT:    wrs.nto
; RV64-NEXT:    ret
  call void @llvm.riscv.wrs.nto()
  ret void
}

define void @wrs_sto() {
; RV32-LABEL: wrs_sto:
; RV32:       # %bb.0:
; RV32-NEXT:    wrs.nto
; RV32-NEXT:    ret
;
; RV64-LABEL: wrs_sto:
; RV64:       # %bb.0:
; RV64-NEXT:    wrs.nto
; RV64-NEXT:    ret
  call void @llvm.riscv.wrs.sto()
  ret void
}
