; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=riscv32 -target-abi ilp32f -mattr=+f,+zcmp -verify-machineinstrs < %s | FileCheck %s

; Test the file could be compiled successfully.
define void @bar() {
; CHECK-LABEL: bar:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    fsw fs0, 12(sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset fs0, -4
; CHECK-NEXT:    #APP
; CHECK-NEXT:    fmv.w.x fs0, zero
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    flw fs0, 12(sp) # 4-byte Folded Reload
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
entry:
  tail call void asm sideeffect "fmv.w.x fs0, zero", "~{fs0}"()
  ret void
}
