; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -verify-machineinstrs -mtriple=riscv32-unknown-unknown -mattr="+i,+m,+Zfh,+f" | FileCheck %s --check-prefixes=32-BITS-F
; RUN: llc < %s -verify-machineinstrs -mtriple=riscv32-unknown-unknown -mattr="+i,+m,+Zfh,+d" | FileCheck %s --check-prefixes=32-BITS-D
; RUN: llc < %s -verify-machineinstrs -mtriple=riscv32-unknown-unknown -mattr="+i,+m,+Zfh,+q" | FileCheck %s --check-prefixes=32-BITS-Q
; RUN: llc < %s -verify-machineinstrs -mtriple=riscv64-unknown-unknown -mattr="+i,+m,+Zfh,+f" | FileCheck %s  --check-prefixes=64-BITS-F
; RUN: llc < %s -verify-machineinstrs -mtriple=riscv64-unknown-unknown -mattr="+i,+m,+Zfh,+d" | FileCheck %s  --check-prefixes=64-BITS-D
; RUN: llc < %s -verify-machineinstrs -mtriple=riscv64-unknown-unknown -mattr="+i,+m,+Zfh,+q" | FileCheck %s  --check-prefixes=64-BITS-Q

define double @used(double noundef %a, float noundef %b) "zero-call-used-regs"="used" {
; 32-BITS-F-LABEL: used:
; 32-BITS-F:       # %bb.0: # %entry
; 32-BITS-F-NEXT:    addi sp, sp, -16
; 32-BITS-F-NEXT:    .cfi_def_cfa_offset 16
; 32-BITS-F-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; 32-BITS-F-NEXT:    sw s0, 8(sp) # 4-byte Folded Spill
; 32-BITS-F-NEXT:    sw s1, 4(sp) # 4-byte Folded Spill
; 32-BITS-F-NEXT:    .cfi_offset ra, -4
; 32-BITS-F-NEXT:    .cfi_offset s0, -8
; 32-BITS-F-NEXT:    .cfi_offset s1, -12
; 32-BITS-F-NEXT:    mv s0, a1
; 32-BITS-F-NEXT:    mv s1, a0
; 32-BITS-F-NEXT:    call __extendsfdf2
; 32-BITS-F-NEXT:    mv a2, s1
; 32-BITS-F-NEXT:    mv a3, s0
; 32-BITS-F-NEXT:    call __muldf3
; 32-BITS-F-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; 32-BITS-F-NEXT:    lw s0, 8(sp) # 4-byte Folded Reload
; 32-BITS-F-NEXT:    lw s1, 4(sp) # 4-byte Folded Reload
; 32-BITS-F-NEXT:    .cfi_restore ra
; 32-BITS-F-NEXT:    .cfi_restore s0
; 32-BITS-F-NEXT:    .cfi_restore s1
; 32-BITS-F-NEXT:    addi sp, sp, 16
; 32-BITS-F-NEXT:    .cfi_def_cfa_offset 0
; 32-BITS-F-NEXT:    li a2, 0
; 32-BITS-F-NEXT:    li a3, 0
; 32-BITS-F-NEXT:    ret
;
; 32-BITS-D-LABEL: used:
; 32-BITS-D:       # %bb.0: # %entry
; 32-BITS-D-NEXT:    fcvt.d.s fa5, fa1
; 32-BITS-D-NEXT:    fmul.d fa0, fa5, fa0
; 32-BITS-D-NEXT:    fcvt.d.w fa1, zero
; 32-BITS-D-NEXT:    fcvt.d.w fa5, zero
; 32-BITS-D-NEXT:    ret
;
; 32-BITS-Q-LABEL: used:
; 32-BITS-Q:       # %bb.0: # %entry
; 32-BITS-Q-NEXT:    fcvt.d.s fa5, fa1
; 32-BITS-Q-NEXT:    fmul.d fa0, fa5, fa0
; 32-BITS-Q-NEXT:    fcvt.q.w fa1, zero
; 32-BITS-Q-NEXT:    fcvt.q.w fa5, zero
; 32-BITS-Q-NEXT:    ret
;
; 64-BITS-F-LABEL: used:
; 64-BITS-F:       # %bb.0: # %entry
; 64-BITS-F-NEXT:    addi sp, sp, -16
; 64-BITS-F-NEXT:    .cfi_def_cfa_offset 16
; 64-BITS-F-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; 64-BITS-F-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; 64-BITS-F-NEXT:    .cfi_offset ra, -8
; 64-BITS-F-NEXT:    .cfi_offset s0, -16
; 64-BITS-F-NEXT:    mv s0, a0
; 64-BITS-F-NEXT:    call __extendsfdf2
; 64-BITS-F-NEXT:    mv a1, s0
; 64-BITS-F-NEXT:    call __muldf3
; 64-BITS-F-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; 64-BITS-F-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; 64-BITS-F-NEXT:    .cfi_restore ra
; 64-BITS-F-NEXT:    .cfi_restore s0
; 64-BITS-F-NEXT:    addi sp, sp, 16
; 64-BITS-F-NEXT:    .cfi_def_cfa_offset 0
; 64-BITS-F-NEXT:    li a1, 0
; 64-BITS-F-NEXT:    ret
;
; 64-BITS-D-LABEL: used:
; 64-BITS-D:       # %bb.0: # %entry
; 64-BITS-D-NEXT:    fcvt.d.s fa5, fa1
; 64-BITS-D-NEXT:    fmul.d fa0, fa5, fa0
; 64-BITS-D-NEXT:    fmv.d.x fa1, zero
; 64-BITS-D-NEXT:    fmv.d.x fa5, zero
; 64-BITS-D-NEXT:    ret
;
; 64-BITS-Q-LABEL: used:
; 64-BITS-Q:       # %bb.0: # %entry
; 64-BITS-Q-NEXT:    fcvt.d.s fa5, fa1
; 64-BITS-Q-NEXT:    fmul.d fa0, fa5, fa0
; 64-BITS-Q-NEXT:    fcvt.q.w fa1, zero
; 64-BITS-Q-NEXT:    fcvt.q.w fa5, zero
; 64-BITS-Q-NEXT:    ret
entry:
  %conv = fpext float %b to double
  %mul = fmul double %conv, %a
  ret double %mul
}

define half @used_arg_half(half noundef %a, half noundef %b) "zero-call-used-regs"="used-arg" {
; 32-BITS-F-LABEL: used_arg_half:
; 32-BITS-F:       # %bb.0: # %entry
; 32-BITS-F-NEXT:    fmul.h fa0, fa0, fa1
; 32-BITS-F-NEXT:    fmv.w.x fa1, zero
; 32-BITS-F-NEXT:    ret
;
; 32-BITS-D-LABEL: used_arg_half:
; 32-BITS-D:       # %bb.0: # %entry
; 32-BITS-D-NEXT:    fmul.h fa0, fa0, fa1
; 32-BITS-D-NEXT:    fcvt.d.w fa1, zero
; 32-BITS-D-NEXT:    ret
;
; 32-BITS-Q-LABEL: used_arg_half:
; 32-BITS-Q:       # %bb.0: # %entry
; 32-BITS-Q-NEXT:    fmul.h fa0, fa0, fa1
; 32-BITS-Q-NEXT:    fcvt.q.w fa1, zero
; 32-BITS-Q-NEXT:    ret
;
; 64-BITS-F-LABEL: used_arg_half:
; 64-BITS-F:       # %bb.0: # %entry
; 64-BITS-F-NEXT:    fmul.h fa0, fa0, fa1
; 64-BITS-F-NEXT:    fmv.w.x fa1, zero
; 64-BITS-F-NEXT:    ret
;
; 64-BITS-D-LABEL: used_arg_half:
; 64-BITS-D:       # %bb.0: # %entry
; 64-BITS-D-NEXT:    fmul.h fa0, fa0, fa1
; 64-BITS-D-NEXT:    fmv.d.x fa1, zero
; 64-BITS-D-NEXT:    ret
;
; 64-BITS-Q-LABEL: used_arg_half:
; 64-BITS-Q:       # %bb.0: # %entry
; 64-BITS-Q-NEXT:    fmul.h fa0, fa0, fa1
; 64-BITS-Q-NEXT:    fcvt.q.w fa1, zero
; 64-BITS-Q-NEXT:    ret
entry:
  %mul = fmul half %a, %b
  ret half %mul
}

define float @used_arg_float(float noundef %a, float noundef %b) "zero-call-used-regs"="used-arg" {
; 32-BITS-F-LABEL: used_arg_float:
; 32-BITS-F:       # %bb.0: # %entry
; 32-BITS-F-NEXT:    fmul.s fa0, fa0, fa1
; 32-BITS-F-NEXT:    fmv.w.x fa1, zero
; 32-BITS-F-NEXT:    ret
;
; 32-BITS-D-LABEL: used_arg_float:
; 32-BITS-D:       # %bb.0: # %entry
; 32-BITS-D-NEXT:    fmul.s fa0, fa0, fa1
; 32-BITS-D-NEXT:    fcvt.d.w fa1, zero
; 32-BITS-D-NEXT:    ret
;
; 32-BITS-Q-LABEL: used_arg_float:
; 32-BITS-Q:       # %bb.0: # %entry
; 32-BITS-Q-NEXT:    fmul.s fa0, fa0, fa1
; 32-BITS-Q-NEXT:    fcvt.q.w fa1, zero
; 32-BITS-Q-NEXT:    ret
;
; 64-BITS-F-LABEL: used_arg_float:
; 64-BITS-F:       # %bb.0: # %entry
; 64-BITS-F-NEXT:    fmul.s fa0, fa0, fa1
; 64-BITS-F-NEXT:    fmv.w.x fa1, zero
; 64-BITS-F-NEXT:    ret
;
; 64-BITS-D-LABEL: used_arg_float:
; 64-BITS-D:       # %bb.0: # %entry
; 64-BITS-D-NEXT:    fmul.s fa0, fa0, fa1
; 64-BITS-D-NEXT:    fmv.d.x fa1, zero
; 64-BITS-D-NEXT:    ret
;
; 64-BITS-Q-LABEL: used_arg_float:
; 64-BITS-Q:       # %bb.0: # %entry
; 64-BITS-Q-NEXT:    fmul.s fa0, fa0, fa1
; 64-BITS-Q-NEXT:    fcvt.q.w fa1, zero
; 64-BITS-Q-NEXT:    ret
entry:
  %mul = fmul float %a, %b
  ret float %mul
}

define double @used_arg_double(double noundef %a, double noundef %b) "zero-call-used-regs"="used-arg" {
; 32-BITS-F-LABEL: used_arg_double:
; 32-BITS-F:       # %bb.0: # %entry
; 32-BITS-F-NEXT:    addi sp, sp, -16
; 32-BITS-F-NEXT:    .cfi_def_cfa_offset 16
; 32-BITS-F-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; 32-BITS-F-NEXT:    .cfi_offset ra, -4
; 32-BITS-F-NEXT:    call __muldf3
; 32-BITS-F-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; 32-BITS-F-NEXT:    .cfi_restore ra
; 32-BITS-F-NEXT:    addi sp, sp, 16
; 32-BITS-F-NEXT:    .cfi_def_cfa_offset 0
; 32-BITS-F-NEXT:    ret
;
; 32-BITS-D-LABEL: used_arg_double:
; 32-BITS-D:       # %bb.0: # %entry
; 32-BITS-D-NEXT:    fmul.d fa0, fa0, fa1
; 32-BITS-D-NEXT:    fcvt.d.w fa1, zero
; 32-BITS-D-NEXT:    ret
;
; 32-BITS-Q-LABEL: used_arg_double:
; 32-BITS-Q:       # %bb.0: # %entry
; 32-BITS-Q-NEXT:    fmul.d fa0, fa0, fa1
; 32-BITS-Q-NEXT:    fcvt.q.w fa1, zero
; 32-BITS-Q-NEXT:    ret
;
; 64-BITS-F-LABEL: used_arg_double:
; 64-BITS-F:       # %bb.0: # %entry
; 64-BITS-F-NEXT:    addi sp, sp, -16
; 64-BITS-F-NEXT:    .cfi_def_cfa_offset 16
; 64-BITS-F-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; 64-BITS-F-NEXT:    .cfi_offset ra, -8
; 64-BITS-F-NEXT:    call __muldf3
; 64-BITS-F-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; 64-BITS-F-NEXT:    .cfi_restore ra
; 64-BITS-F-NEXT:    addi sp, sp, 16
; 64-BITS-F-NEXT:    .cfi_def_cfa_offset 0
; 64-BITS-F-NEXT:    ret
;
; 64-BITS-D-LABEL: used_arg_double:
; 64-BITS-D:       # %bb.0: # %entry
; 64-BITS-D-NEXT:    fmul.d fa0, fa0, fa1
; 64-BITS-D-NEXT:    fmv.d.x fa1, zero
; 64-BITS-D-NEXT:    ret
;
; 64-BITS-Q-LABEL: used_arg_double:
; 64-BITS-Q:       # %bb.0: # %entry
; 64-BITS-Q-NEXT:    fmul.d fa0, fa0, fa1
; 64-BITS-Q-NEXT:    fcvt.q.w fa1, zero
; 64-BITS-Q-NEXT:    ret
entry:
  %mul = fmul double %a, %b
  ret double %mul
}

define void @all_fp() "zero-call-used-regs"="all" {
; 32-BITS-F-LABEL: all_fp:
; 32-BITS-F:       # %bb.0: # %entry
; 32-BITS-F-NEXT:    li t0, 0
; 32-BITS-F-NEXT:    li t1, 0
; 32-BITS-F-NEXT:    li t2, 0
; 32-BITS-F-NEXT:    li a0, 0
; 32-BITS-F-NEXT:    li a1, 0
; 32-BITS-F-NEXT:    li a2, 0
; 32-BITS-F-NEXT:    li a3, 0
; 32-BITS-F-NEXT:    li a4, 0
; 32-BITS-F-NEXT:    li a5, 0
; 32-BITS-F-NEXT:    li a6, 0
; 32-BITS-F-NEXT:    li a7, 0
; 32-BITS-F-NEXT:    li t3, 0
; 32-BITS-F-NEXT:    li t4, 0
; 32-BITS-F-NEXT:    li t5, 0
; 32-BITS-F-NEXT:    li t6, 0
; 32-BITS-F-NEXT:    fmv.w.x ft0, zero
; 32-BITS-F-NEXT:    fmv.w.x ft1, zero
; 32-BITS-F-NEXT:    fmv.w.x ft2, zero
; 32-BITS-F-NEXT:    fmv.w.x ft3, zero
; 32-BITS-F-NEXT:    fmv.w.x ft4, zero
; 32-BITS-F-NEXT:    fmv.w.x ft5, zero
; 32-BITS-F-NEXT:    fmv.w.x ft6, zero
; 32-BITS-F-NEXT:    fmv.w.x ft7, zero
; 32-BITS-F-NEXT:    fmv.w.x fa0, zero
; 32-BITS-F-NEXT:    fmv.w.x fa1, zero
; 32-BITS-F-NEXT:    fmv.w.x fa2, zero
; 32-BITS-F-NEXT:    fmv.w.x fa3, zero
; 32-BITS-F-NEXT:    fmv.w.x fa4, zero
; 32-BITS-F-NEXT:    fmv.w.x fa5, zero
; 32-BITS-F-NEXT:    fmv.w.x fa6, zero
; 32-BITS-F-NEXT:    fmv.w.x fa7, zero
; 32-BITS-F-NEXT:    fmv.w.x ft8, zero
; 32-BITS-F-NEXT:    fmv.w.x ft9, zero
; 32-BITS-F-NEXT:    fmv.w.x ft10, zero
; 32-BITS-F-NEXT:    fmv.w.x ft11, zero
; 32-BITS-F-NEXT:    ret
;
; 32-BITS-D-LABEL: all_fp:
; 32-BITS-D:       # %bb.0: # %entry
; 32-BITS-D-NEXT:    li t0, 0
; 32-BITS-D-NEXT:    li t1, 0
; 32-BITS-D-NEXT:    li t2, 0
; 32-BITS-D-NEXT:    li a0, 0
; 32-BITS-D-NEXT:    li a1, 0
; 32-BITS-D-NEXT:    li a2, 0
; 32-BITS-D-NEXT:    li a3, 0
; 32-BITS-D-NEXT:    li a4, 0
; 32-BITS-D-NEXT:    li a5, 0
; 32-BITS-D-NEXT:    li a6, 0
; 32-BITS-D-NEXT:    li a7, 0
; 32-BITS-D-NEXT:    li t3, 0
; 32-BITS-D-NEXT:    li t4, 0
; 32-BITS-D-NEXT:    li t5, 0
; 32-BITS-D-NEXT:    li t6, 0
; 32-BITS-D-NEXT:    fcvt.d.w ft0, zero
; 32-BITS-D-NEXT:    fcvt.d.w ft1, zero
; 32-BITS-D-NEXT:    fcvt.d.w ft2, zero
; 32-BITS-D-NEXT:    fcvt.d.w ft3, zero
; 32-BITS-D-NEXT:    fcvt.d.w ft4, zero
; 32-BITS-D-NEXT:    fcvt.d.w ft5, zero
; 32-BITS-D-NEXT:    fcvt.d.w ft6, zero
; 32-BITS-D-NEXT:    fcvt.d.w ft7, zero
; 32-BITS-D-NEXT:    fcvt.d.w fa0, zero
; 32-BITS-D-NEXT:    fcvt.d.w fa1, zero
; 32-BITS-D-NEXT:    fcvt.d.w fa2, zero
; 32-BITS-D-NEXT:    fcvt.d.w fa3, zero
; 32-BITS-D-NEXT:    fcvt.d.w fa4, zero
; 32-BITS-D-NEXT:    fcvt.d.w fa5, zero
; 32-BITS-D-NEXT:    fcvt.d.w fa6, zero
; 32-BITS-D-NEXT:    fcvt.d.w fa7, zero
; 32-BITS-D-NEXT:    fcvt.d.w ft8, zero
; 32-BITS-D-NEXT:    fcvt.d.w ft9, zero
; 32-BITS-D-NEXT:    fcvt.d.w ft10, zero
; 32-BITS-D-NEXT:    fcvt.d.w ft11, zero
; 32-BITS-D-NEXT:    ret
;
; 32-BITS-Q-LABEL: all_fp:
; 32-BITS-Q:       # %bb.0: # %entry
; 32-BITS-Q-NEXT:    li t0, 0
; 32-BITS-Q-NEXT:    li t1, 0
; 32-BITS-Q-NEXT:    li t2, 0
; 32-BITS-Q-NEXT:    li a0, 0
; 32-BITS-Q-NEXT:    li a1, 0
; 32-BITS-Q-NEXT:    li a2, 0
; 32-BITS-Q-NEXT:    li a3, 0
; 32-BITS-Q-NEXT:    li a4, 0
; 32-BITS-Q-NEXT:    li a5, 0
; 32-BITS-Q-NEXT:    li a6, 0
; 32-BITS-Q-NEXT:    li a7, 0
; 32-BITS-Q-NEXT:    li t3, 0
; 32-BITS-Q-NEXT:    li t4, 0
; 32-BITS-Q-NEXT:    li t5, 0
; 32-BITS-Q-NEXT:    li t6, 0
; 32-BITS-Q-NEXT:    fcvt.q.w ft0, zero
; 32-BITS-Q-NEXT:    fcvt.q.w ft1, zero
; 32-BITS-Q-NEXT:    fcvt.q.w ft2, zero
; 32-BITS-Q-NEXT:    fcvt.q.w ft3, zero
; 32-BITS-Q-NEXT:    fcvt.q.w ft4, zero
; 32-BITS-Q-NEXT:    fcvt.q.w ft5, zero
; 32-BITS-Q-NEXT:    fcvt.q.w ft6, zero
; 32-BITS-Q-NEXT:    fcvt.q.w ft7, zero
; 32-BITS-Q-NEXT:    fcvt.q.w fa0, zero
; 32-BITS-Q-NEXT:    fcvt.q.w fa1, zero
; 32-BITS-Q-NEXT:    fcvt.q.w fa2, zero
; 32-BITS-Q-NEXT:    fcvt.q.w fa3, zero
; 32-BITS-Q-NEXT:    fcvt.q.w fa4, zero
; 32-BITS-Q-NEXT:    fcvt.q.w fa5, zero
; 32-BITS-Q-NEXT:    fcvt.q.w fa6, zero
; 32-BITS-Q-NEXT:    fcvt.q.w fa7, zero
; 32-BITS-Q-NEXT:    fcvt.q.w ft8, zero
; 32-BITS-Q-NEXT:    fcvt.q.w ft9, zero
; 32-BITS-Q-NEXT:    fcvt.q.w ft10, zero
; 32-BITS-Q-NEXT:    fcvt.q.w ft11, zero
; 32-BITS-Q-NEXT:    ret
;
; 64-BITS-F-LABEL: all_fp:
; 64-BITS-F:       # %bb.0: # %entry
; 64-BITS-F-NEXT:    li t0, 0
; 64-BITS-F-NEXT:    li t1, 0
; 64-BITS-F-NEXT:    li t2, 0
; 64-BITS-F-NEXT:    li a0, 0
; 64-BITS-F-NEXT:    li a1, 0
; 64-BITS-F-NEXT:    li a2, 0
; 64-BITS-F-NEXT:    li a3, 0
; 64-BITS-F-NEXT:    li a4, 0
; 64-BITS-F-NEXT:    li a5, 0
; 64-BITS-F-NEXT:    li a6, 0
; 64-BITS-F-NEXT:    li a7, 0
; 64-BITS-F-NEXT:    li t3, 0
; 64-BITS-F-NEXT:    li t4, 0
; 64-BITS-F-NEXT:    li t5, 0
; 64-BITS-F-NEXT:    li t6, 0
; 64-BITS-F-NEXT:    fmv.w.x ft0, zero
; 64-BITS-F-NEXT:    fmv.w.x ft1, zero
; 64-BITS-F-NEXT:    fmv.w.x ft2, zero
; 64-BITS-F-NEXT:    fmv.w.x ft3, zero
; 64-BITS-F-NEXT:    fmv.w.x ft4, zero
; 64-BITS-F-NEXT:    fmv.w.x ft5, zero
; 64-BITS-F-NEXT:    fmv.w.x ft6, zero
; 64-BITS-F-NEXT:    fmv.w.x ft7, zero
; 64-BITS-F-NEXT:    fmv.w.x fa0, zero
; 64-BITS-F-NEXT:    fmv.w.x fa1, zero
; 64-BITS-F-NEXT:    fmv.w.x fa2, zero
; 64-BITS-F-NEXT:    fmv.w.x fa3, zero
; 64-BITS-F-NEXT:    fmv.w.x fa4, zero
; 64-BITS-F-NEXT:    fmv.w.x fa5, zero
; 64-BITS-F-NEXT:    fmv.w.x fa6, zero
; 64-BITS-F-NEXT:    fmv.w.x fa7, zero
; 64-BITS-F-NEXT:    fmv.w.x ft8, zero
; 64-BITS-F-NEXT:    fmv.w.x ft9, zero
; 64-BITS-F-NEXT:    fmv.w.x ft10, zero
; 64-BITS-F-NEXT:    fmv.w.x ft11, zero
; 64-BITS-F-NEXT:    ret
;
; 64-BITS-D-LABEL: all_fp:
; 64-BITS-D:       # %bb.0: # %entry
; 64-BITS-D-NEXT:    li t0, 0
; 64-BITS-D-NEXT:    li t1, 0
; 64-BITS-D-NEXT:    li t2, 0
; 64-BITS-D-NEXT:    li a0, 0
; 64-BITS-D-NEXT:    li a1, 0
; 64-BITS-D-NEXT:    li a2, 0
; 64-BITS-D-NEXT:    li a3, 0
; 64-BITS-D-NEXT:    li a4, 0
; 64-BITS-D-NEXT:    li a5, 0
; 64-BITS-D-NEXT:    li a6, 0
; 64-BITS-D-NEXT:    li a7, 0
; 64-BITS-D-NEXT:    li t3, 0
; 64-BITS-D-NEXT:    li t4, 0
; 64-BITS-D-NEXT:    li t5, 0
; 64-BITS-D-NEXT:    li t6, 0
; 64-BITS-D-NEXT:    fmv.d.x ft0, zero
; 64-BITS-D-NEXT:    fmv.d.x ft1, zero
; 64-BITS-D-NEXT:    fmv.d.x ft2, zero
; 64-BITS-D-NEXT:    fmv.d.x ft3, zero
; 64-BITS-D-NEXT:    fmv.d.x ft4, zero
; 64-BITS-D-NEXT:    fmv.d.x ft5, zero
; 64-BITS-D-NEXT:    fmv.d.x ft6, zero
; 64-BITS-D-NEXT:    fmv.d.x ft7, zero
; 64-BITS-D-NEXT:    fmv.d.x fa0, zero
; 64-BITS-D-NEXT:    fmv.d.x fa1, zero
; 64-BITS-D-NEXT:    fmv.d.x fa2, zero
; 64-BITS-D-NEXT:    fmv.d.x fa3, zero
; 64-BITS-D-NEXT:    fmv.d.x fa4, zero
; 64-BITS-D-NEXT:    fmv.d.x fa5, zero
; 64-BITS-D-NEXT:    fmv.d.x fa6, zero
; 64-BITS-D-NEXT:    fmv.d.x fa7, zero
; 64-BITS-D-NEXT:    fmv.d.x ft8, zero
; 64-BITS-D-NEXT:    fmv.d.x ft9, zero
; 64-BITS-D-NEXT:    fmv.d.x ft10, zero
; 64-BITS-D-NEXT:    fmv.d.x ft11, zero
; 64-BITS-D-NEXT:    ret
;
; 64-BITS-Q-LABEL: all_fp:
; 64-BITS-Q:       # %bb.0: # %entry
; 64-BITS-Q-NEXT:    li t0, 0
; 64-BITS-Q-NEXT:    li t1, 0
; 64-BITS-Q-NEXT:    li t2, 0
; 64-BITS-Q-NEXT:    li a0, 0
; 64-BITS-Q-NEXT:    li a1, 0
; 64-BITS-Q-NEXT:    li a2, 0
; 64-BITS-Q-NEXT:    li a3, 0
; 64-BITS-Q-NEXT:    li a4, 0
; 64-BITS-Q-NEXT:    li a5, 0
; 64-BITS-Q-NEXT:    li a6, 0
; 64-BITS-Q-NEXT:    li a7, 0
; 64-BITS-Q-NEXT:    li t3, 0
; 64-BITS-Q-NEXT:    li t4, 0
; 64-BITS-Q-NEXT:    li t5, 0
; 64-BITS-Q-NEXT:    li t6, 0
; 64-BITS-Q-NEXT:    fcvt.q.w ft0, zero
; 64-BITS-Q-NEXT:    fcvt.q.w ft1, zero
; 64-BITS-Q-NEXT:    fcvt.q.w ft2, zero
; 64-BITS-Q-NEXT:    fcvt.q.w ft3, zero
; 64-BITS-Q-NEXT:    fcvt.q.w ft4, zero
; 64-BITS-Q-NEXT:    fcvt.q.w ft5, zero
; 64-BITS-Q-NEXT:    fcvt.q.w ft6, zero
; 64-BITS-Q-NEXT:    fcvt.q.w ft7, zero
; 64-BITS-Q-NEXT:    fcvt.q.w fa0, zero
; 64-BITS-Q-NEXT:    fcvt.q.w fa1, zero
; 64-BITS-Q-NEXT:    fcvt.q.w fa2, zero
; 64-BITS-Q-NEXT:    fcvt.q.w fa3, zero
; 64-BITS-Q-NEXT:    fcvt.q.w fa4, zero
; 64-BITS-Q-NEXT:    fcvt.q.w fa5, zero
; 64-BITS-Q-NEXT:    fcvt.q.w fa6, zero
; 64-BITS-Q-NEXT:    fcvt.q.w fa7, zero
; 64-BITS-Q-NEXT:    fcvt.q.w ft8, zero
; 64-BITS-Q-NEXT:    fcvt.q.w ft9, zero
; 64-BITS-Q-NEXT:    fcvt.q.w ft10, zero
; 64-BITS-Q-NEXT:    fcvt.q.w ft11, zero
; 64-BITS-Q-NEXT:    ret
entry:
  ret void
}
