; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -verify-machineinstrs -mtriple=riscv64-unknown-unknown -mattr="+i,+m,+v" | FileCheck %s  --check-prefixes=CHECK

define void @all() "zero-call-used-regs"="all" {
; CHECK-LABEL: all:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli t0, zero, e32, m1, tu, mu
; CHECK-NEXT:    vmv.v.i v0, 0
; CHECK-NEXT:    vmv.v.i v1, 0
; CHECK-NEXT:    vmv.v.i v2, 0
; CHECK-NEXT:    vmv.v.i v3, 0
; CHECK-NEXT:    vmv.v.i v4, 0
; CHECK-NEXT:    vmv.v.i v5, 0
; CHECK-NEXT:    vmv.v.i v6, 0
; CHECK-NEXT:    vmv.v.i v7, 0
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    vmv.v.i v10, 0
; CHECK-NEXT:    vmv.v.i v11, 0
; CHECK-NEXT:    vmv.v.i v12, 0
; CHECK-NEXT:    vmv.v.i v13, 0
; CHECK-NEXT:    vmv.v.i v14, 0
; CHECK-NEXT:    vmv.v.i v15, 0
; CHECK-NEXT:    vmv.v.i v16, 0
; CHECK-NEXT:    vmv.v.i v17, 0
; CHECK-NEXT:    vmv.v.i v18, 0
; CHECK-NEXT:    vmv.v.i v19, 0
; CHECK-NEXT:    vmv.v.i v20, 0
; CHECK-NEXT:    vmv.v.i v21, 0
; CHECK-NEXT:    vmv.v.i v22, 0
; CHECK-NEXT:    vmv.v.i v23, 0
; CHECK-NEXT:    vmv.v.i v24, 0
; CHECK-NEXT:    vmv.v.i v25, 0
; CHECK-NEXT:    vmv.v.i v26, 0
; CHECK-NEXT:    vmv.v.i v27, 0
; CHECK-NEXT:    vmv.v.i v28, 0
; CHECK-NEXT:    vmv.v.i v29, 0
; CHECK-NEXT:    vmv.v.i v30, 0
; CHECK-NEXT:    vmv.v.i v31, 0
; CHECK-NEXT:    li t0, 0
; CHECK-NEXT:    li t1, 0
; CHECK-NEXT:    li t2, 0
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    li a1, 0
; CHECK-NEXT:    li a2, 0
; CHECK-NEXT:    li a3, 0
; CHECK-NEXT:    li a4, 0
; CHECK-NEXT:    li a5, 0
; CHECK-NEXT:    li a6, 0
; CHECK-NEXT:    li a7, 0
; CHECK-NEXT:    li t3, 0
; CHECK-NEXT:    li t4, 0
; CHECK-NEXT:    li t5, 0
; CHECK-NEXT:    li t6, 0
; CHECK-NEXT:    fmv.d.x ft0, zero
; CHECK-NEXT:    fmv.d.x ft1, zero
; CHECK-NEXT:    fmv.d.x ft2, zero
; CHECK-NEXT:    fmv.d.x ft3, zero
; CHECK-NEXT:    fmv.d.x ft4, zero
; CHECK-NEXT:    fmv.d.x ft5, zero
; CHECK-NEXT:    fmv.d.x ft6, zero
; CHECK-NEXT:    fmv.d.x ft7, zero
; CHECK-NEXT:    fmv.d.x fa0, zero
; CHECK-NEXT:    fmv.d.x fa1, zero
; CHECK-NEXT:    fmv.d.x fa2, zero
; CHECK-NEXT:    fmv.d.x fa3, zero
; CHECK-NEXT:    fmv.d.x fa4, zero
; CHECK-NEXT:    fmv.d.x fa5, zero
; CHECK-NEXT:    fmv.d.x fa6, zero
; CHECK-NEXT:    fmv.d.x fa7, zero
; CHECK-NEXT:    fmv.d.x ft8, zero
; CHECK-NEXT:    fmv.d.x ft9, zero
; CHECK-NEXT:    fmv.d.x ft10, zero
; CHECK-NEXT:    fmv.d.x ft11, zero
; CHECK-NEXT:    ret
entry:
  ret void
}

define void @all_arg() "zero-call-used-regs"="all-arg" {
; CHECK-LABEL: all_arg:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli t0, zero, e32, m1, tu, mu
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    vmv.v.i v10, 0
; CHECK-NEXT:    vmv.v.i v11, 0
; CHECK-NEXT:    vmv.v.i v12, 0
; CHECK-NEXT:    vmv.v.i v13, 0
; CHECK-NEXT:    vmv.v.i v14, 0
; CHECK-NEXT:    vmv.v.i v15, 0
; CHECK-NEXT:    vmv.v.i v16, 0
; CHECK-NEXT:    vmv.v.i v17, 0
; CHECK-NEXT:    vmv.v.i v18, 0
; CHECK-NEXT:    vmv.v.i v19, 0
; CHECK-NEXT:    vmv.v.i v20, 0
; CHECK-NEXT:    vmv.v.i v21, 0
; CHECK-NEXT:    vmv.v.i v22, 0
; CHECK-NEXT:    vmv.v.i v23, 0
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    li a1, 0
; CHECK-NEXT:    li a2, 0
; CHECK-NEXT:    li a3, 0
; CHECK-NEXT:    li a4, 0
; CHECK-NEXT:    li a5, 0
; CHECK-NEXT:    li a6, 0
; CHECK-NEXT:    li a7, 0
; CHECK-NEXT:    fmv.d.x fa0, zero
; CHECK-NEXT:    fmv.d.x fa1, zero
; CHECK-NEXT:    fmv.d.x fa2, zero
; CHECK-NEXT:    fmv.d.x fa3, zero
; CHECK-NEXT:    fmv.d.x fa4, zero
; CHECK-NEXT:    fmv.d.x fa5, zero
; CHECK-NEXT:    fmv.d.x fa6, zero
; CHECK-NEXT:    fmv.d.x fa7, zero
; CHECK-NEXT:    ret
entry:
  ret void
}

define i32 @used(i32 %x) "zero-call-used-regs"="used" {
; CHECK-LABEL: used:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, zero
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vredsum.vs v8, v9, v8
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    vsetvli t0, zero, e32, m1, tu, mu
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    ret
entry:
    %tmp = insertelement <4 x i32> poison, i32 %x, i32 0
    %vec = shufflevector <4 x i32> %tmp, <4 x i32> poison,
                         <4 x i32> zeroinitializer

    %sum = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> %vec)
    ret i32 %sum
}

define <4 x i32> @used_arg(<4 x i32> %a, <4 x i32> %b) "zero-call-used-regs"="used-arg" {
; CHECK-LABEL: used_arg:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vadd.vv v8, v8, v9
; CHECK-NEXT:    vsetvli t0, zero, e32, m1, tu, mu
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    ret
entry:
    %sum = add <4 x i32> %a, %b
    ret <4 x i32> %sum
}

