; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-zibimm -verify-machineinstrs < %s \
; RUN:     | FileCheck -check-prefix=RV32I-ZIBIMM %s
; RUN: llc -mtriple=riscv64 -mattr=+experimental-zibimm -verify-machineinstrs < %s \
; RUN:     | FileCheck -check-prefix=RV64I-ZIBIMM %s

define void @test_bne_neg(ptr %b) nounwind {
; RV32I-ZIBIMM-LABEL: test_bne_neg:
; RV32I-ZIBIMM:       # %bb.0:
; RV32I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV32I-ZIBIMM-NEXT:    bnei a1, -1, .LBB0_2
; RV32I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV32I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV32I-ZIBIMM-NEXT:  .LBB0_2: # %end
; RV32I-ZIBIMM-NEXT:    ret
;
; RV64I-ZIBIMM-LABEL: test_bne_neg:
; RV64I-ZIBIMM:       # %bb.0:
; RV64I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV64I-ZIBIMM-NEXT:    bnei a1, -1, .LBB0_2
; RV64I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV64I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV64I-ZIBIMM-NEXT:  .LBB0_2: # %end
; RV64I-ZIBIMM-NEXT:    ret
  %val1 = load volatile i32, ptr %b
  %tst1 = icmp ne i32 %val1, -1
  br i1 %tst1, label %end, label %test2, !prof !0
test2:
  %val2 = load volatile i32, ptr %b
  br label %end
end:
  ret void
}
!0 = !{!"branch_weights", i32 1, i32 99}

define void @test_beq_neg(ptr %b) nounwind {
; RV32I-ZIBIMM-LABEL: test_beq_neg:
; RV32I-ZIBIMM:       # %bb.0:
; RV32I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV32I-ZIBIMM-NEXT:    beqi a1, -1, .LBB1_2
; RV32I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV32I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV32I-ZIBIMM-NEXT:  .LBB1_2: # %end
; RV32I-ZIBIMM-NEXT:    ret
;
; RV64I-ZIBIMM-LABEL: test_beq_neg:
; RV64I-ZIBIMM:       # %bb.0:
; RV64I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV64I-ZIBIMM-NEXT:    beqi a1, -1, .LBB1_2
; RV64I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV64I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV64I-ZIBIMM-NEXT:  .LBB1_2: # %end
; RV64I-ZIBIMM-NEXT:    ret
  %val1 = load volatile i32, ptr %b
  %tst1 = icmp eq i32 %val1, -1
  br i1 %tst1, label %end, label %test2, !prof !1
test2:
  %val2 = load volatile i32, ptr %b
  br label %end
end:
  ret void
}
!1 = !{!"branch_weights", i32 1, i32 99}

define void @test_bne_zero(ptr %b) nounwind {
; RV32I-ZIBIMM-LABEL: test_bne_zero:
; RV32I-ZIBIMM:       # %bb.0:
; RV32I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV32I-ZIBIMM-NEXT:    bnez a1, .LBB2_2
; RV32I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV32I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV32I-ZIBIMM-NEXT:  .LBB2_2: # %end
; RV32I-ZIBIMM-NEXT:    ret
;
; RV64I-ZIBIMM-LABEL: test_bne_zero:
; RV64I-ZIBIMM:       # %bb.0:
; RV64I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV64I-ZIBIMM-NEXT:    bnez a1, .LBB2_2
; RV64I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV64I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV64I-ZIBIMM-NEXT:  .LBB2_2: # %end
; RV64I-ZIBIMM-NEXT:    ret
  %val1 = load volatile i32, ptr %b
  %tst1 = icmp ne i32 %val1, 0
  br i1 %tst1, label %end, label %test2, !prof !2
test2:
  %val2 = load volatile i32, ptr %b
  br label %end
end:
  ret void
}
!2 = !{!"branch_weights", i32 1, i32 99}

define void @test_beq_zero(ptr %b) nounwind {
; RV32I-ZIBIMM-LABEL: test_beq_zero:
; RV32I-ZIBIMM:       # %bb.0:
; RV32I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV32I-ZIBIMM-NEXT:    beqz a1, .LBB3_2
; RV32I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV32I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV32I-ZIBIMM-NEXT:  .LBB3_2: # %end
; RV32I-ZIBIMM-NEXT:    ret
;
; RV64I-ZIBIMM-LABEL: test_beq_zero:
; RV64I-ZIBIMM:       # %bb.0:
; RV64I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV64I-ZIBIMM-NEXT:    beqz a1, .LBB3_2
; RV64I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV64I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV64I-ZIBIMM-NEXT:  .LBB3_2: # %end
; RV64I-ZIBIMM-NEXT:    ret
  %val1 = load volatile i32, ptr %b
  %tst1 = icmp eq i32 %val1, 0
  br i1 %tst1, label %end, label %test2, !prof !3
test2:
  %val2 = load volatile i32, ptr %b
  br label %end
end:
  ret void
}
!3 = !{!"branch_weights", i32 1, i32 99}

define void @test_bne_1(ptr %b) nounwind {
; RV32I-ZIBIMM-LABEL: test_bne_1:
; RV32I-ZIBIMM:       # %bb.0:
; RV32I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV32I-ZIBIMM-NEXT:    bnei a1, 1, .LBB4_2
; RV32I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV32I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV32I-ZIBIMM-NEXT:  .LBB4_2: # %end
; RV32I-ZIBIMM-NEXT:    ret
;
; RV64I-ZIBIMM-LABEL: test_bne_1:
; RV64I-ZIBIMM:       # %bb.0:
; RV64I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV64I-ZIBIMM-NEXT:    bnei a1, 1, .LBB4_2
; RV64I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV64I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV64I-ZIBIMM-NEXT:  .LBB4_2: # %end
; RV64I-ZIBIMM-NEXT:    ret
  %val1 = load volatile i32, ptr %b
  %tst1 = icmp ne i32 %val1, 1
  br i1 %tst1, label %end, label %test2, !prof !4
test2:
  %val2 = load volatile i32, ptr %b
  br label %end
end:
  ret void
}
!4 = !{!"branch_weights", i32 1, i32 99}

define void @test_beq_1(ptr %b) nounwind {
; RV32I-ZIBIMM-LABEL: test_beq_1:
; RV32I-ZIBIMM:       # %bb.0:
; RV32I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV32I-ZIBIMM-NEXT:    beqi a1, 1, .LBB5_2
; RV32I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV32I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV32I-ZIBIMM-NEXT:  .LBB5_2: # %end
; RV32I-ZIBIMM-NEXT:    ret
;
; RV64I-ZIBIMM-LABEL: test_beq_1:
; RV64I-ZIBIMM:       # %bb.0:
; RV64I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV64I-ZIBIMM-NEXT:    beqi a1, 1, .LBB5_2
; RV64I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV64I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV64I-ZIBIMM-NEXT:  .LBB5_2: # %end
; RV64I-ZIBIMM-NEXT:    ret
  %val1 = load volatile i32, ptr %b
  %tst1 = icmp eq i32 %val1, 1
  br i1 %tst1, label %end, label %test2, !prof !5
test2:
  %val2 = load volatile i32, ptr %b
  br label %end
end:
  ret void
}
!5 = !{!"branch_weights", i32 1, i32 99}

define void @test_bne_31(ptr %b) nounwind {
; RV32I-ZIBIMM-LABEL: test_bne_31:
; RV32I-ZIBIMM:       # %bb.0:
; RV32I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV32I-ZIBIMM-NEXT:    bnei a1, 31, .LBB6_2
; RV32I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV32I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV32I-ZIBIMM-NEXT:  .LBB6_2: # %end
; RV32I-ZIBIMM-NEXT:    ret
;
; RV64I-ZIBIMM-LABEL: test_bne_31:
; RV64I-ZIBIMM:       # %bb.0:
; RV64I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV64I-ZIBIMM-NEXT:    bnei a1, 31, .LBB6_2
; RV64I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV64I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV64I-ZIBIMM-NEXT:  .LBB6_2: # %end
; RV64I-ZIBIMM-NEXT:    ret
  %val1 = load volatile i32, ptr %b
  %tst1 = icmp ne i32 %val1, 31
  br i1 %tst1, label %end, label %test2, !prof !6
test2:
  %val2 = load volatile i32, ptr %b
  br label %end
end:
  ret void
}
!6 = !{!"branch_weights", i32 1, i32 99}

define void @test_beq_31(ptr %b) nounwind {
; RV32I-ZIBIMM-LABEL: test_beq_31:
; RV32I-ZIBIMM:       # %bb.0:
; RV32I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV32I-ZIBIMM-NEXT:    beqi a1, 1, .LBB7_2
; RV32I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV32I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV32I-ZIBIMM-NEXT:  .LBB7_2: # %end
; RV32I-ZIBIMM-NEXT:    ret
;
; RV64I-ZIBIMM-LABEL: test_beq_31:
; RV64I-ZIBIMM:       # %bb.0:
; RV64I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV64I-ZIBIMM-NEXT:    beqi a1, 1, .LBB7_2
; RV64I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV64I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV64I-ZIBIMM-NEXT:  .LBB7_2: # %end
; RV64I-ZIBIMM-NEXT:    ret
  %val1 = load volatile i32, ptr %b
  %tst1 = icmp eq i32 %val1, 1
  br i1 %tst1, label %end, label %test2, !prof !7
test2:
  %val2 = load volatile i32, ptr %b
  br label %end
end:
  ret void
}
!7 = !{!"branch_weights", i32 1, i32 99}

define void @test_bne_32(ptr %b) nounwind {
; RV32I-ZIBIMM-LABEL: test_bne_32:
; RV32I-ZIBIMM:       # %bb.0:
; RV32I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV32I-ZIBIMM-NEXT:    li a2, 32
; RV32I-ZIBIMM-NEXT:    bne a1, a2, .LBB8_2
; RV32I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV32I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV32I-ZIBIMM-NEXT:  .LBB8_2: # %end
; RV32I-ZIBIMM-NEXT:    ret
;
; RV64I-ZIBIMM-LABEL: test_bne_32:
; RV64I-ZIBIMM:       # %bb.0:
; RV64I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV64I-ZIBIMM-NEXT:    li a2, 32
; RV64I-ZIBIMM-NEXT:    bne a1, a2, .LBB8_2
; RV64I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV64I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV64I-ZIBIMM-NEXT:  .LBB8_2: # %end
; RV64I-ZIBIMM-NEXT:    ret
  %val1 = load volatile i32, ptr %b
  %tst1 = icmp ne i32 %val1, 32
  br i1 %tst1, label %end, label %test2, !prof !8
test2:
  %val2 = load volatile i32, ptr %b
  br label %end
end:
  ret void
}
!8 = !{!"branch_weights", i32 1, i32 99}

define void @test_beq_32(ptr %b) nounwind {
; RV32I-ZIBIMM-LABEL: test_beq_32:
; RV32I-ZIBIMM:       # %bb.0:
; RV32I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV32I-ZIBIMM-NEXT:    li a2, 32
; RV32I-ZIBIMM-NEXT:    beq a1, a2, .LBB9_2
; RV32I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV32I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV32I-ZIBIMM-NEXT:  .LBB9_2: # %end
; RV32I-ZIBIMM-NEXT:    ret
;
; RV64I-ZIBIMM-LABEL: test_beq_32:
; RV64I-ZIBIMM:       # %bb.0:
; RV64I-ZIBIMM-NEXT:    lw a1, 0(a0)
; RV64I-ZIBIMM-NEXT:    li a2, 32
; RV64I-ZIBIMM-NEXT:    beq a1, a2, .LBB9_2
; RV64I-ZIBIMM-NEXT:  # %bb.1: # %test2
; RV64I-ZIBIMM-NEXT:    lw zero, 0(a0)
; RV64I-ZIBIMM-NEXT:  .LBB9_2: # %end
; RV64I-ZIBIMM-NEXT:    ret
  %val1 = load volatile i32, ptr %b
  %tst1 = icmp eq i32 %val1, 32
  br i1 %tst1, label %end, label %test2, !prof !9
test2:
  %val2 = load volatile i32, ptr %b
  br label %end
end:
  ret void
}
!9 = !{!"branch_weights", i32 1, i32 99}
