# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple riscv32 -mattr=+zcmp,+zilsd --run-pass=prologepilog %s -verify-machineinstrs -o - \
# RUN: | FileCheck --check-prefix=ZCMP-ZILSD %s
# RUN: llc -mtriple riscv32 -mattr=+xqccmp,+zilsd --run-pass=prologepilog %s -verify-machineinstrs -o - \
# RUN: | FileCheck --check-prefix=XQCCMP-ZILSD %s

--- |
  declare i32 @foo()
  declare void @bar()

  ; Function Attrs: nounwind optsize
  define void @zilsd_dup_csr(ptr %p, i32 %a) #1 {
  entry:
    %call1 = call i32 @foo()
    %0 = alloca i8, i32 %a, align 8
    store ptr %0, ptr %p, align 8
    tail call void @bar()
    ret void
  }

...
---
name:            zilsd_dup_csr
alignment:       2
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          true
isSSA:           false
noVRegs:         true
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: true
registers:       []
liveins:
  - { reg: '$x10', virtual-reg: '' }
  - { reg: '$x11', virtual-reg: '' }
calleeSavedRegisters: [ '$x1', '$x8', '$x9', '$x18', '$x19', '$x20', '$x21',
                        '$x22', '$x23', '$x24', '$x25', '$x26', '$x27',
                        '$x8_x9', '$x18_x19', '$x20_x21', '$x22_x23', '$x24_x25',
                        '$x26_x27' ]
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    true
  hasCalls:        true
  framePointerPolicy: none
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 0
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     true
  isCalleeSavedInfoValid: false
  localFrameSize:  0
fixedStack:      []
stack:
  - { id: 0, name: '', type: variable-sized, offset: 0, alignment: 1, stack-id: default,
      callee-saved-register: '', callee-saved-restored: true, local-offset: 0,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; ZCMP-ZILSD-LABEL: name: zilsd_dup_csr
    ; ZCMP-ZILSD: liveins: $x10, $x11, $x1, $x18_x19
    ; ZCMP-ZILSD-NEXT: {{  $}}
    ; ZCMP-ZILSD-NEXT: frame-setup CM_PUSH 4, 16, implicit-def $x2, implicit $x2, implicit $x1
    ; ZCMP-ZILSD-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; ZCMP-ZILSD-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -4
    ; ZCMP-ZILSD-NEXT: frame-setup SD_RV32 killed $x8_x9, $x2, 8 :: (store (s64) into %stack.1)
    ; ZCMP-ZILSD-NEXT: frame-setup SD_RV32 killed $x18_x19, $x2, 0 :: (store (s64) into %stack.2)
    ; ZCMP-ZILSD-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -24
    ; ZCMP-ZILSD-NEXT: frame-setup CFI_INSTRUCTION offset $x9, -20
    ; ZCMP-ZILSD-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -32
    ; ZCMP-ZILSD-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -28
    ; ZCMP-ZILSD-NEXT: $x8 = frame-setup ADDI $x2, 32
    ; ZCMP-ZILSD-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; ZCMP-ZILSD-NEXT: renamable $x9 = COPY $x11
    ; ZCMP-ZILSD-NEXT: renamable $x18 = COPY $x10
    ; ZCMP-ZILSD-NEXT: PseudoCALL target-flags(riscv-call) @foo, csr_ilp32_lp64, implicit-def dead $x1, implicit-def $x2, implicit-def dead $x10
    ; ZCMP-ZILSD-NEXT: renamable $x9 = nuw ADDI killed renamable $x9, 15
    ; ZCMP-ZILSD-NEXT: renamable $x9 = ANDI killed renamable $x9, -16
    ; ZCMP-ZILSD-NEXT: renamable $x10 = SUB $x2, killed renamable $x9
    ; ZCMP-ZILSD-NEXT: $x2 = COPY renamable $x10
    ; ZCMP-ZILSD-NEXT: SW killed renamable $x10, killed renamable $x18, 0 :: (store (s32) into %ir.p, align 8)
    ; ZCMP-ZILSD-NEXT: $x2 = frame-destroy ADDI $x8, -32
    ; ZCMP-ZILSD-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 32
    ; ZCMP-ZILSD-NEXT: $x8_x9 = frame-destroy LD_RV32 $x2, 8 :: (load (s64) from %stack.1)
    ; ZCMP-ZILSD-NEXT: $x18_x19 = frame-destroy LD_RV32 $x2, 0 :: (load (s64) from %stack.2)
    ; ZCMP-ZILSD-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; ZCMP-ZILSD-NEXT: frame-destroy CFI_INSTRUCTION restore $x9
    ; ZCMP-ZILSD-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; ZCMP-ZILSD-NEXT: frame-destroy CFI_INSTRUCTION restore $x19
    ; ZCMP-ZILSD-NEXT: frame-destroy CM_POP 4, 16, implicit-def $x2, implicit $x2, implicit-def $x1
    ; ZCMP-ZILSD-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; ZCMP-ZILSD-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; ZCMP-ZILSD-NEXT: PseudoTAIL target-flags(riscv-call) @bar, csr_ilp32_lp64, implicit $x2
    ;
    ; XQCCMP-ZILSD-LABEL: name: zilsd_dup_csr
    ; XQCCMP-ZILSD: liveins: $x10, $x11, $x1, $x18_x19
    ; XQCCMP-ZILSD-NEXT: {{  $}}
    ; XQCCMP-ZILSD-NEXT: frame-setup QC_CM_PUSH 4, 16, implicit-def $x2, implicit $x2, implicit $x1
    ; XQCCMP-ZILSD-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 32
    ; XQCCMP-ZILSD-NEXT: frame-setup CFI_INSTRUCTION offset $x1, -4
    ; XQCCMP-ZILSD-NEXT: frame-setup SD_RV32 killed $x8_x9, $x2, 8 :: (store (s64) into %stack.1)
    ; XQCCMP-ZILSD-NEXT: frame-setup SD_RV32 killed $x18_x19, $x2, 0 :: (store (s64) into %stack.2)
    ; XQCCMP-ZILSD-NEXT: frame-setup CFI_INSTRUCTION offset $x8, -24
    ; XQCCMP-ZILSD-NEXT: frame-setup CFI_INSTRUCTION offset $x9, -20
    ; XQCCMP-ZILSD-NEXT: frame-setup CFI_INSTRUCTION offset $x18, -32
    ; XQCCMP-ZILSD-NEXT: frame-setup CFI_INSTRUCTION offset $x19, -28
    ; XQCCMP-ZILSD-NEXT: $x8 = frame-setup ADDI $x2, 32
    ; XQCCMP-ZILSD-NEXT: frame-setup CFI_INSTRUCTION def_cfa $x8, 0
    ; XQCCMP-ZILSD-NEXT: renamable $x9 = COPY $x11
    ; XQCCMP-ZILSD-NEXT: renamable $x18 = COPY $x10
    ; XQCCMP-ZILSD-NEXT: PseudoCALL target-flags(riscv-call) @foo, csr_ilp32_lp64, implicit-def dead $x1, implicit-def $x2, implicit-def dead $x10
    ; XQCCMP-ZILSD-NEXT: renamable $x9 = nuw ADDI killed renamable $x9, 15
    ; XQCCMP-ZILSD-NEXT: renamable $x9 = ANDI killed renamable $x9, -16
    ; XQCCMP-ZILSD-NEXT: renamable $x10 = SUB $x2, killed renamable $x9
    ; XQCCMP-ZILSD-NEXT: $x2 = COPY renamable $x10
    ; XQCCMP-ZILSD-NEXT: SW killed renamable $x10, killed renamable $x18, 0 :: (store (s32) into %ir.p, align 8)
    ; XQCCMP-ZILSD-NEXT: $x2 = frame-destroy ADDI $x8, -32
    ; XQCCMP-ZILSD-NEXT: frame-destroy CFI_INSTRUCTION def_cfa $x2, 32
    ; XQCCMP-ZILSD-NEXT: $x8_x9 = frame-destroy LD_RV32 $x2, 8 :: (load (s64) from %stack.1)
    ; XQCCMP-ZILSD-NEXT: $x18_x19 = frame-destroy LD_RV32 $x2, 0 :: (load (s64) from %stack.2)
    ; XQCCMP-ZILSD-NEXT: frame-destroy CFI_INSTRUCTION restore $x8
    ; XQCCMP-ZILSD-NEXT: frame-destroy CFI_INSTRUCTION restore $x9
    ; XQCCMP-ZILSD-NEXT: frame-destroy CFI_INSTRUCTION restore $x18
    ; XQCCMP-ZILSD-NEXT: frame-destroy CFI_INSTRUCTION restore $x19
    ; XQCCMP-ZILSD-NEXT: frame-destroy QC_CM_POP 4, 16, implicit-def $x2, implicit $x2, implicit-def $x1
    ; XQCCMP-ZILSD-NEXT: frame-destroy CFI_INSTRUCTION restore $x1
    ; XQCCMP-ZILSD-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_offset 0
    ; XQCCMP-ZILSD-NEXT: PseudoTAIL target-flags(riscv-call) @bar, csr_ilp32_lp64, implicit $x2
    renamable $x9 = COPY $x11
    renamable $x18 = COPY $x10
    ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
    PseudoCALL target-flags(riscv-call) @foo, csr_ilp32_lp64, implicit-def dead $x1, implicit-def $x2, implicit-def dead $x10
    ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
    ADJCALLSTACKDOWN 0, 0, implicit-def dead $x2, implicit $x2
    renamable $x9 = nuw ADDI killed renamable $x9, 15
    renamable $x9 = ANDI killed renamable $x9, -16
    renamable $x10 = SUB $x2, killed renamable $x9
    $x2 = COPY renamable $x10
    ADJCALLSTACKUP 0, 0, implicit-def dead $x2, implicit $x2
    SW killed renamable $x10, killed renamable $x18, 0 :: (store (s32) into %ir.p, align 8)
    PseudoTAIL target-flags(riscv-call) @bar, csr_ilp32_lp64, implicit $x2
...
