// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-globals all --replace-value-regex "!prof ![0-9]+" --version 6
// RUN: %clang_cc1 -O0 -fbounds-safety -triple arm64-apple-iphoneos \
// RUN:   -emit-llvm %s -o - -fbounds-safety-soft-traps=call-minimal \
// RUN:   -fsanitize=signed-integer-overflow \
// RUN:   -fsanitize-trap=signed-integer-overflow | \
// RUN:   FileCheck --check-prefixes=UNOPT %s

// Check `-ftrap-function=` is used for UBSan traps but not -fbounds-safety
// traps when using `-fbounds-safety-soft-traps=`.
// RUN: %clang_cc1 -O0 -fbounds-safety -triple arm64-apple-iphoneos \
// RUN:   -emit-llvm %s -o - -fbounds-safety-soft-traps=call-minimal \
// RUN:   -fsanitize=signed-integer-overflow \
// RUN:   -fsanitize-trap=signed-integer-overflow \
// RUN:   -ftrap-function=ubsan_handler | \
// RUN:   FileCheck --check-prefixes=UNOPT-TF %s

// Check `-ftrap-function=` is used for UBSan traps but not -fbounds-safety
// traps when using `-fbounds-safety-soft-traps=` and that
// `-ftrap-function-returns` is applied to UBSan traps calls only.
// RUN: %clang_cc1 -O0 -fbounds-safety -triple arm64-apple-iphoneos \
// RUN:   -emit-llvm %s -o - -fbounds-safety-soft-traps=call-minimal \
// RUN:   -fsanitize=signed-integer-overflow \
// RUN:   -fsanitize-trap=signed-integer-overflow \
// RUN:   -ftrap-function=ubsan_handler -ftrap-function-returns | \
// RUN:   FileCheck --check-prefixes=UNOPT-TFR %s

// RUN: %clang_cc1 -O2 -fbounds-safety -triple arm64-apple-iphoneos \
// RUN:   -emit-llvm %s -o - -fbounds-safety-soft-traps=call-minimal \
// RUN:   -fsanitize=signed-integer-overflow \
// RUN:   -fsanitize-trap=signed-integer-overflow | \
// RUN:   FileCheck --check-prefixes=OPT %s

#include <ptrcheck.h>

// FIXME: the `@.src` global contains the absolute path to this source file
// which is not portable. It isn't possible to get `update_cc_test_checks.py`
// to filter this because:
//
// * `--filter-out` doesn't apply to globals
// * `--global-value-regex` doesn't work on `attributes #N =` which we need to
//   keep.
//
// To workaround this these lines have been manually patched.

//.
// UNOPT: @.src = private unnamed_addr constant [{{[0-9]+}} x i8] c"{{.+}}", align 1
// UNOPT: @[[GLOB0:[0-9]+]] = private unnamed_addr constant { i16, i16, [6 x i8] } { i16 0, i16 11, [6 x i8] c"'int'\00" }
//.
// UNOPT-TF: @.src = private unnamed_addr constant [{{[0-9]+}} x i8] c"{{.+}}", align 1
// UNOPT-TF: @[[GLOB0:[0-9]+]] = private unnamed_addr constant { i16, i16, [6 x i8] } { i16 0, i16 11, [6 x i8] c"'int'\00" }
//.
// UNOPT-TFR: @.src = private unnamed_addr constant [{{[0-9]+}} x i8] c"{{.+}}", align 1
// UNOPT-TFR: @[[GLOB0:[0-9]+]] = private unnamed_addr constant { i16, i16, [6 x i8] } { i16 0, i16 11, [6 x i8] c"'int'\00" }
//.
// UNOPT-LABEL: define dso_local i32 @read(
// UNOPT-SAME: ptr noundef dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[OTHER:%.*]]) #[[ATTR0:[0-9]+]] {
// UNOPT-NEXT:  [[ENTRY:.*:]]
// UNOPT-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// UNOPT-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// UNOPT-NEXT:    [[OTHER_ADDR:%.*]] = alloca i32, align 4
// UNOPT-NEXT:    [[TMP:%.*]] = alloca i32, align 4
// UNOPT-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// UNOPT-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4
// UNOPT-NEXT:    store i32 [[OTHER]], ptr [[OTHER_ADDR]], align 4
// UNOPT-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4
// UNOPT-NEXT:    [[TMP1:%.*]] = load i32, ptr [[OTHER_ADDR]], align 4
// UNOPT-NEXT:    [[TMP2:%.*]] = call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 [[TMP0]], i32 [[TMP1]]), !nosanitize [[META1:![0-9]+]]
// UNOPT-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i1 } [[TMP2]], 0, !nosanitize [[META1]]
// UNOPT-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i1 } [[TMP2]], 1, !nosanitize [[META1]]
// UNOPT-NEXT:    [[TMP5:%.*]] = xor i1 [[TMP4]], true, !nosanitize [[META1]]
// UNOPT-NEXT:    br i1 [[TMP5]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !nosanitize [[META1]]
// UNOPT:       [[TRAP]]:
// UNOPT-NEXT:    call void @llvm.ubsantrap(i8 0) #[[ATTR4:[0-9]+]], !nosanitize [[META1]]
// UNOPT-NEXT:    unreachable, !nosanitize [[META1]]
// UNOPT:       [[CONT]]:
// UNOPT-NEXT:    store i32 [[TMP3]], ptr [[TMP]], align 4
// UNOPT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// UNOPT-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// UNOPT-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// UNOPT-NEXT:    [[TMP6:%.*]] = load i32, ptr [[TMP]], align 4
// UNOPT-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP6]] to i64
// UNOPT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// UNOPT-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// UNOPT-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// UNOPT-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// UNOPT-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// UNOPT-NEXT:    [[TMP7:%.*]] = getelementptr i32, ptr [[ARRAYIDX]], i64 1, !annotation [[META3:![0-9]+]]
// UNOPT-NEXT:    [[TMP8:%.*]] = icmp ule ptr [[TMP7]], [[WIDE_PTR_UB]], !annotation [[META3]]
// UNOPT-NEXT:    br i1 [[TMP8]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// UNOPT:       [[TRAP1]]:
// UNOPT-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR5:[0-9]+]], !annotation [[META3]]
// UNOPT-NEXT:    br label %[[CONT2]], !annotation [[META3]]
// UNOPT:       [[CONT2]]:
// UNOPT-NEXT:    [[TMP9:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP7]], !annotation [[META3]]
// UNOPT-NEXT:    br i1 [[TMP9]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// UNOPT:       [[TRAP3]]:
// UNOPT-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR5]], !annotation [[META3]]
// UNOPT-NEXT:    br label %[[CONT4]], !annotation [[META3]]
// UNOPT:       [[CONT4]]:
// UNOPT-NEXT:    [[TMP10:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META4:![0-9]+]]
// UNOPT-NEXT:    br i1 [[TMP10]], label %[[CONT6:.*]], label %[[TRAP5:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// UNOPT:       [[TRAP5]]:
// UNOPT-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR5]], !annotation [[META4]]
// UNOPT-NEXT:    br label %[[CONT6]], !annotation [[META4]]
// UNOPT:       [[CONT6]]:
// UNOPT-NEXT:    [[TMP11:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// UNOPT-NEXT:    ret i32 [[TMP11]]
//
// UNOPT-TF-LABEL: define dso_local i32 @read(
// UNOPT-TF-SAME: ptr noundef dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[OTHER:%.*]]) #[[ATTR0:[0-9]+]] {
// UNOPT-TF-NEXT:  [[ENTRY:.*:]]
// UNOPT-TF-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// UNOPT-TF-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// UNOPT-TF-NEXT:    [[OTHER_ADDR:%.*]] = alloca i32, align 4
// UNOPT-TF-NEXT:    [[TMP:%.*]] = alloca i32, align 4
// UNOPT-TF-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-TF-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// UNOPT-TF-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4
// UNOPT-TF-NEXT:    store i32 [[OTHER]], ptr [[OTHER_ADDR]], align 4
// UNOPT-TF-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4
// UNOPT-TF-NEXT:    [[TMP1:%.*]] = load i32, ptr [[OTHER_ADDR]], align 4
// UNOPT-TF-NEXT:    [[TMP2:%.*]] = call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 [[TMP0]], i32 [[TMP1]]), !nosanitize [[META1:![0-9]+]]
// UNOPT-TF-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i1 } [[TMP2]], 0, !nosanitize [[META1]]
// UNOPT-TF-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i1 } [[TMP2]], 1, !nosanitize [[META1]]
// UNOPT-TF-NEXT:    [[TMP5:%.*]] = xor i1 [[TMP4]], true, !nosanitize [[META1]]
// UNOPT-TF-NEXT:    br i1 [[TMP5]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !nosanitize [[META1]]
// UNOPT-TF:       [[TRAP]]:
// UNOPT-TF-NEXT:    call void @llvm.ubsantrap(i8 0) #[[ATTR4:[0-9]+]], !nosanitize [[META1]]
// UNOPT-TF-NEXT:    unreachable, !nosanitize [[META1]]
// UNOPT-TF:       [[CONT]]:
// UNOPT-TF-NEXT:    store i32 [[TMP3]], ptr [[TMP]], align 4
// UNOPT-TF-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// UNOPT-TF-NEXT:    [[TMP6:%.*]] = load i32, ptr [[TMP]], align 4
// UNOPT-TF-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP6]] to i64
// UNOPT-TF-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// UNOPT-TF-NEXT:    [[TMP7:%.*]] = getelementptr i32, ptr [[ARRAYIDX]], i64 1, !annotation [[META3:![0-9]+]]
// UNOPT-TF-NEXT:    [[TMP8:%.*]] = icmp ule ptr [[TMP7]], [[WIDE_PTR_UB]], !annotation [[META3]]
// UNOPT-TF-NEXT:    br i1 [[TMP8]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// UNOPT-TF:       [[TRAP1]]:
// UNOPT-TF-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR5:[0-9]+]], !annotation [[META3]]
// UNOPT-TF-NEXT:    br label %[[CONT2]], !annotation [[META3]]
// UNOPT-TF:       [[CONT2]]:
// UNOPT-TF-NEXT:    [[TMP9:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP7]], !annotation [[META3]]
// UNOPT-TF-NEXT:    br i1 [[TMP9]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// UNOPT-TF:       [[TRAP3]]:
// UNOPT-TF-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR5]], !annotation [[META3]]
// UNOPT-TF-NEXT:    br label %[[CONT4]], !annotation [[META3]]
// UNOPT-TF:       [[CONT4]]:
// UNOPT-TF-NEXT:    [[TMP10:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META4:![0-9]+]]
// UNOPT-TF-NEXT:    br i1 [[TMP10]], label %[[CONT6:.*]], label %[[TRAP5:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// UNOPT-TF:       [[TRAP5]]:
// UNOPT-TF-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR5]], !annotation [[META4]]
// UNOPT-TF-NEXT:    br label %[[CONT6]], !annotation [[META4]]
// UNOPT-TF:       [[CONT6]]:
// UNOPT-TF-NEXT:    [[TMP11:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// UNOPT-TF-NEXT:    ret i32 [[TMP11]]
//
// UNOPT-TFR-LABEL: define dso_local i32 @read(
// UNOPT-TFR-SAME: ptr noundef dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[OTHER:%.*]]) #[[ATTR0:[0-9]+]] {
// UNOPT-TFR-NEXT:  [[ENTRY:.*:]]
// UNOPT-TFR-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// UNOPT-TFR-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// UNOPT-TFR-NEXT:    [[OTHER_ADDR:%.*]] = alloca i32, align 4
// UNOPT-TFR-NEXT:    [[TMP:%.*]] = alloca i32, align 4
// UNOPT-TFR-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-TFR-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// UNOPT-TFR-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4
// UNOPT-TFR-NEXT:    store i32 [[OTHER]], ptr [[OTHER_ADDR]], align 4
// UNOPT-TFR-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4
// UNOPT-TFR-NEXT:    [[TMP1:%.*]] = load i32, ptr [[OTHER_ADDR]], align 4
// UNOPT-TFR-NEXT:    [[TMP2:%.*]] = call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 [[TMP0]], i32 [[TMP1]]), !nosanitize [[META1:![0-9]+]]
// UNOPT-TFR-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i1 } [[TMP2]], 0, !nosanitize [[META1]]
// UNOPT-TFR-NEXT:    [[TMP4:%.*]] = extractvalue { i32, i1 } [[TMP2]], 1, !nosanitize [[META1]]
// UNOPT-TFR-NEXT:    [[TMP5:%.*]] = xor i1 [[TMP4]], true, !nosanitize [[META1]]
// UNOPT-TFR-NEXT:    br i1 [[TMP5]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !nosanitize [[META1]]
// UNOPT-TFR:       [[TRAP]]:
// UNOPT-TFR-NEXT:    call void @ubsan_handler(i8 0) #[[ATTR3:[0-9]+]], !nosanitize [[META1]]
// UNOPT-TFR-NEXT:    br label %[[CONT]], !nosanitize [[META1]]
// UNOPT-TFR:       [[CONT]]:
// UNOPT-TFR-NEXT:    store i32 [[TMP3]], ptr [[TMP]], align 4
// UNOPT-TFR-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// UNOPT-TFR-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// UNOPT-TFR-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// UNOPT-TFR-NEXT:    [[TMP6:%.*]] = load i32, ptr [[TMP]], align 4
// UNOPT-TFR-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP6]] to i64
// UNOPT-TFR-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// UNOPT-TFR-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// UNOPT-TFR-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// UNOPT-TFR-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// UNOPT-TFR-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// UNOPT-TFR-NEXT:    [[TMP7:%.*]] = getelementptr i32, ptr [[ARRAYIDX]], i64 1, !annotation [[META3:![0-9]+]]
// UNOPT-TFR-NEXT:    [[TMP8:%.*]] = icmp ule ptr [[TMP7]], [[WIDE_PTR_UB]], !annotation [[META3]]
// UNOPT-TFR-NEXT:    br i1 [[TMP8]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// UNOPT-TFR:       [[TRAP1]]:
// UNOPT-TFR-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR4:[0-9]+]], !annotation [[META3]]
// UNOPT-TFR-NEXT:    br label %[[CONT2]], !annotation [[META3]]
// UNOPT-TFR:       [[CONT2]]:
// UNOPT-TFR-NEXT:    [[TMP9:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP7]], !annotation [[META3]]
// UNOPT-TFR-NEXT:    br i1 [[TMP9]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// UNOPT-TFR:       [[TRAP3]]:
// UNOPT-TFR-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR4]], !annotation [[META3]]
// UNOPT-TFR-NEXT:    br label %[[CONT4]], !annotation [[META3]]
// UNOPT-TFR:       [[CONT4]]:
// UNOPT-TFR-NEXT:    [[TMP10:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META4:![0-9]+]]
// UNOPT-TFR-NEXT:    br i1 [[TMP10]], label %[[CONT6:.*]], label %[[TRAP5:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// UNOPT-TFR:       [[TRAP5]]:
// UNOPT-TFR-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR4]], !annotation [[META4]]
// UNOPT-TFR-NEXT:    br label %[[CONT6]], !annotation [[META4]]
// UNOPT-TFR:       [[CONT6]]:
// UNOPT-TFR-NEXT:    [[TMP11:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// UNOPT-TFR-NEXT:    ret i32 [[TMP11]]
//
// OPT-LABEL: define dso_local i32 @read(
// OPT-SAME: ptr noundef readonly captures(none) dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]], i32 noundef [[OTHER:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// OPT-NEXT:  [[ENTRY:.*:]]
// OPT-NEXT:    [[TMP0:%.*]] = tail call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 [[IDX]], i32 [[OTHER]]), !nosanitize [[META5:![0-9]+]]
// OPT-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i1 } [[TMP0]], 1, !nosanitize [[META5]]
// OPT-NEXT:    br i1 [[TMP1]], label %[[TRAP:.*]], label %[[CONT:.*]], {{!prof ![0-9]+}}, !nosanitize [[META5]]
// OPT:       [[TRAP]]:
// OPT-NEXT:    tail call void @llvm.ubsantrap(i8 0) #[[ATTR3:[0-9]+]], !nosanitize [[META5]]
// OPT-NEXT:    unreachable, !nosanitize [[META5]]
// OPT:       [[CONT]]:
// OPT-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i1 } [[TMP0]], 0, !nosanitize [[META5]]
// OPT-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// OPT-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// OPT-NEXT:    [[AGG_TEMP_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// OPT-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// OPT-NEXT:    [[AGG_TEMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[INTPTR_TBAA7:![0-9]+]]
// OPT-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP2]] to i64
// OPT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [4 x i8], ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 [[IDXPROM]]
// OPT-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[ARRAYIDX]], i64 4, !annotation [[META10:![0-9]+]]
// OPT-NEXT:    [[DOTNOT:%.*]] = icmp ugt ptr [[TMP3]], [[AGG_TEMP_SROA_2_0_COPYLOAD]], !annotation [[META10]]
// OPT-NEXT:    br i1 [[DOTNOT]], label %[[TRAP1:.*]], label %[[CONT2:.*]], {{!prof ![0-9]+}}, !annotation [[META10]]
// OPT:       [[TRAP1]]:
// OPT-NEXT:    tail call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR4:[0-9]+]], !annotation [[META10]]
// OPT-NEXT:    br label %[[CONT2]], !annotation [[META10]]
// OPT:       [[CONT2]]:
// OPT-NEXT:    [[DOTNOT7:%.*]] = icmp ugt ptr [[ARRAYIDX]], [[TMP3]], !annotation [[META10]]
// OPT-NEXT:    br i1 [[DOTNOT7]], label %[[TRAP3:.*]], label %[[CONT4:.*]], {{!prof ![0-9]+}}, !annotation [[META10]]
// OPT:       [[TRAP3]]:
// OPT-NEXT:    tail call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR4]], !annotation [[META10]]
// OPT-NEXT:    br label %[[CONT4]], !annotation [[META10]]
// OPT:       [[CONT4]]:
// OPT-NEXT:    [[DOTNOT8:%.*]] = icmp ult ptr [[ARRAYIDX]], [[AGG_TEMP_SROA_3_0_COPYLOAD]], !annotation [[META11:![0-9]+]]
// OPT-NEXT:    br i1 [[DOTNOT8]], label %[[TRAP5:.*]], label %[[CONT6:.*]], {{!prof ![0-9]+}}, !annotation [[META11]]
// OPT:       [[TRAP5]]:
// OPT-NEXT:    tail call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR4]], !annotation [[META11]]
// OPT-NEXT:    br label %[[CONT6]], !annotation [[META11]]
// OPT:       [[CONT6]]:
// OPT-NEXT:    [[TMP4:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[INT_TBAA1:![0-9]+]]
// OPT-NEXT:    ret i32 [[TMP4]]
//
int read(int* __bidi_indexable ptr, int idx, int other) {
    int tmp = idx + other;
    return ptr[tmp];
}

//.
// UNOPT: attributes #[[ATTR0]] = { noinline nounwind optnone "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
// UNOPT: attributes #[[ATTR1:[0-9]+]] = { nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none) }
// UNOPT: attributes #[[ATTR2:[0-9]+]] = { cold noreturn nounwind memory(inaccessiblemem: write) }
// UNOPT: attributes #[[ATTR3:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
// UNOPT: attributes #[[ATTR4]] = { nomerge noreturn nounwind }
// UNOPT: attributes #[[ATTR5]] = { nomerge nounwind }
//.
// UNOPT-TF: attributes #[[ATTR0]] = { noinline nounwind optnone "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
// UNOPT-TF: attributes #[[ATTR1:[0-9]+]] = { nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none) }
// UNOPT-TF: attributes #[[ATTR2:[0-9]+]] = { cold noreturn nounwind memory(inaccessiblemem: write) }
// UNOPT-TF: attributes #[[ATTR3:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
// UNOPT-TF: attributes #[[ATTR4]] = { nomerge noreturn nounwind "trap-func-name"="ubsan_handler" }
// UNOPT-TF: attributes #[[ATTR5]] = { nomerge nounwind }
//.
// UNOPT-TFR: attributes #[[ATTR0]] = { noinline nounwind optnone "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
// UNOPT-TFR: attributes #[[ATTR1:[0-9]+]] = { nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none) }
// UNOPT-TFR: attributes #[[ATTR2:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
// UNOPT-TFR: attributes #[[ATTR3]] = { nounwind }
// UNOPT-TFR: attributes #[[ATTR4]] = { nomerge nounwind }
//.
// OPT: attributes #[[ATTR0]] = { nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
// OPT: attributes #[[ATTR1:[0-9]+]] = { mustprogress nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none) }
// OPT: attributes #[[ATTR2:[0-9]+]] = { cold noreturn nounwind memory(inaccessiblemem: write) }
// OPT: attributes #[[ATTR3]] = { nomerge noreturn nounwind }
// OPT: attributes #[[ATTR4]] = { nomerge nounwind }
//.
// UNOPT: [[META0:![0-9]+]] = !{!"{{.*}}clang version {{.*}}"}
// UNOPT: [[META1]] = !{}
// UNOPT: [[META2:![0-9]+]] = !{!"branch_weights", i32 1048575, i32 1}
// UNOPT: [[META3]] = !{!"bounds-safety-check-ptr-le-upper-bound"}
// UNOPT: [[META4]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
//.
// UNOPT-TF: [[META0:![0-9]+]] = !{!"{{.*}}clang version {{.*}}"}
// UNOPT-TF: [[META1]] = !{}
// UNOPT-TF: [[META2:![0-9]+]] = !{!"branch_weights", i32 1048575, i32 1}
// UNOPT-TF: [[META3]] = !{!"bounds-safety-check-ptr-le-upper-bound"}
// UNOPT-TF: [[META4]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
//.
// UNOPT-TFR: [[META0:![0-9]+]] = !{!"{{.*}}clang version {{.*}}"}
// UNOPT-TFR: [[META1]] = !{}
// UNOPT-TFR: [[META2:![0-9]+]] = !{!"branch_weights", i32 1048575, i32 1}
// UNOPT-TFR: [[META3]] = !{!"bounds-safety-check-ptr-le-upper-bound"}
// UNOPT-TFR: [[META4]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
//.
// OPT: [[META0:![0-9]+]] = !{!"{{.*}}clang version {{.*}}"}
// OPT: [[INT_TBAA1]] = !{[[META2:![0-9]+]], [[META2]], i64 0}
// OPT: [[META2]] = !{!"int", [[META3:![0-9]+]], i64 0}
// OPT: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// OPT: [[META4]] = !{!"Simple C/C++ TBAA"}
// OPT: [[META5]] = !{}
// OPT: [[META6:![0-9]+]] = !{!"branch_weights", i32 1, i32 1048575}
// OPT: [[INTPTR_TBAA7]] = !{[[META8:![0-9]+]], [[META8]], i64 0}
// OPT: [[META8]] = !{!"p1 int", [[META9:![0-9]+]], i64 0}
// OPT: [[META9]] = !{!"any pointer", [[META3]], i64 0}
// OPT: [[META10]] = !{!"bounds-safety-check-ptr-le-upper-bound"}
// OPT: [[META11]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
//.
