// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-globals all --replace-value-regex "!prof ![0-9]+" --version 6
// RUN: %clang_cc1 -O0 -fbounds-safety -triple arm64-apple-iphoneos \
// RUN:   -emit-llvm %s -o - -fbounds-safety-soft-traps=call-with-str | \
// RUN:   FileCheck --check-prefixes=UNOPT %s

// Note: Building with and without `-ftrap-function=not_used` results in
// almost the same codegen but not exactly. It seems the `trap-func-name"="not_used"`
// attribute gets put on the call to `receive_cb` because the IR attribute is
// added to calls by default when building with `-ftrap-function=`.
// Unfortunately this means we need slightly different FileCheck lines even
// though they are almost identical. This seems like a compiler bug
// (rdar://162790015).
//
// Check `-ftrap-function` is ignored for `-fbounds-safety` when using
// `-fbounds-safety-soft-traps=`
// RUN: %clang_cc1 -O0 -fbounds-safety -triple arm64-apple-iphoneos \
// RUN:   -emit-llvm %s -o - -fbounds-safety-soft-traps=call-with-str \
// RUN:   -ftrap-function=not_used | \
// RUN:   FileCheck --check-prefixes=UNOPT-TF %s

// RUN: %clang_cc1 -O2 -fbounds-safety -triple arm64-apple-iphoneos \
// RUN:   -emit-llvm %s -o - -fbounds-safety-soft-traps=call-with-str | \
// RUN:   FileCheck --check-prefixes=OPT %s
#include <ptrcheck.h>


//.
// UNOPT: @trap.reason = private unnamed_addr constant [41 x i8] c"indexing above upper bound in 'ptr[idx]'\00", align 4
// UNOPT: @trap.reason.1 = private unnamed_addr constant [47 x i8] c"indexing overflows address space in 'ptr[idx]'\00", align 4
// UNOPT: @trap.reason.2 = private unnamed_addr constant [41 x i8] c"indexing below lower bound in 'ptr[idx]'\00", align 4
//.
// UNOPT-TF: @trap.reason = private unnamed_addr constant [41 x i8] c"indexing above upper bound in 'ptr[idx]'\00", align 4
// UNOPT-TF: @trap.reason.1 = private unnamed_addr constant [47 x i8] c"indexing overflows address space in 'ptr[idx]'\00", align 4
// UNOPT-TF: @trap.reason.2 = private unnamed_addr constant [41 x i8] c"indexing below lower bound in 'ptr[idx]'\00", align 4
//.
// OPT: @trap.reason = private unnamed_addr constant [41 x i8] c"indexing above upper bound in 'ptr[idx]'\00", align 4
// OPT: @trap.reason.1 = private unnamed_addr constant [47 x i8] c"indexing overflows address space in 'ptr[idx]'\00", align 4
// OPT: @trap.reason.2 = private unnamed_addr constant [41 x i8] c"indexing below lower bound in 'ptr[idx]'\00", align 4
//.
// UNOPT-LABEL: define dso_local i32 @read(
// UNOPT-SAME: ptr noundef dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]]) #[[ATTR0:[0-9]+]] {
// UNOPT-NEXT:  [[ENTRY:.*:]]
// UNOPT-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// UNOPT-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// UNOPT-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// UNOPT-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4
// UNOPT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// UNOPT-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// UNOPT-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// UNOPT-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4
// UNOPT-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP0]] to i64
// UNOPT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// UNOPT-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// UNOPT-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// UNOPT-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// UNOPT-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// UNOPT-NEXT:    [[TMP1:%.*]] = getelementptr i32, ptr [[ARRAYIDX]], i64 1, !annotation [[META1:![0-9]+]]
// UNOPT-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[TMP1]], [[WIDE_PTR_UB]], !annotation [[META1]]
// UNOPT-NEXT:    br i1 [[TMP2]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// UNOPT:       [[TRAP]]:
// UNOPT-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap_s(ptr @trap.reason) #[[ATTR3:[0-9]+]], !annotation [[META1]]
// UNOPT-NEXT:    br label %[[CONT]], !annotation [[META1]]
// UNOPT:       [[CONT]]:
// UNOPT-NEXT:    [[TMP3:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP1]], !annotation [[META1]]
// UNOPT-NEXT:    br i1 [[TMP3]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// UNOPT:       [[TRAP1]]:
// UNOPT-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap_s(ptr @trap.reason.1) #[[ATTR3]], !annotation [[META1]]
// UNOPT-NEXT:    br label %[[CONT2]], !annotation [[META1]]
// UNOPT:       [[CONT2]]:
// UNOPT-NEXT:    [[TMP4:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META3:![0-9]+]]
// UNOPT-NEXT:    br i1 [[TMP4]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// UNOPT:       [[TRAP3]]:
// UNOPT-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap_s(ptr @trap.reason.2) #[[ATTR3]], !annotation [[META3]]
// UNOPT-NEXT:    br label %[[CONT4]], !annotation [[META3]]
// UNOPT:       [[CONT4]]:
// UNOPT-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// UNOPT-NEXT:    ret i32 [[TMP5]]
//
// UNOPT-TF-LABEL: define dso_local i32 @read(
// UNOPT-TF-SAME: ptr noundef dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]]) #[[ATTR0:[0-9]+]] {
// UNOPT-TF-NEXT:  [[ENTRY:.*:]]
// UNOPT-TF-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// UNOPT-TF-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// UNOPT-TF-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-TF-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// UNOPT-TF-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4
// UNOPT-TF-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// UNOPT-TF-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4
// UNOPT-TF-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP0]] to i64
// UNOPT-TF-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// UNOPT-TF-NEXT:    [[TMP1:%.*]] = getelementptr i32, ptr [[ARRAYIDX]], i64 1, !annotation [[META1:![0-9]+]]
// UNOPT-TF-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[TMP1]], [[WIDE_PTR_UB]], !annotation [[META1]]
// UNOPT-TF-NEXT:    br i1 [[TMP2]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// UNOPT-TF:       [[TRAP]]:
// UNOPT-TF-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap_s(ptr @trap.reason) #[[ATTR3:[0-9]+]], !annotation [[META1]]
// UNOPT-TF-NEXT:    br label %[[CONT]], !annotation [[META1]]
// UNOPT-TF:       [[CONT]]:
// UNOPT-TF-NEXT:    [[TMP3:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP1]], !annotation [[META1]]
// UNOPT-TF-NEXT:    br i1 [[TMP3]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, !annotation [[META1]]
// UNOPT-TF:       [[TRAP1]]:
// UNOPT-TF-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap_s(ptr @trap.reason.1) #[[ATTR3]], !annotation [[META1]]
// UNOPT-TF-NEXT:    br label %[[CONT2]], !annotation [[META1]]
// UNOPT-TF:       [[CONT2]]:
// UNOPT-TF-NEXT:    [[TMP4:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META3:![0-9]+]]
// UNOPT-TF-NEXT:    br i1 [[TMP4]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, !annotation [[META3]]
// UNOPT-TF:       [[TRAP3]]:
// UNOPT-TF-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap_s(ptr @trap.reason.2) #[[ATTR3]], !annotation [[META3]]
// UNOPT-TF-NEXT:    br label %[[CONT4]], !annotation [[META3]]
// UNOPT-TF:       [[CONT4]]:
// UNOPT-TF-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// UNOPT-TF-NEXT:    ret i32 [[TMP5]]
//
// OPT-LABEL: define dso_local i32 @read(
// OPT-SAME: ptr noundef readonly captures(none) dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// OPT-NEXT:  [[ENTRY:.*:]]
// OPT-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// OPT-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// OPT-NEXT:    [[AGG_TEMP_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// OPT-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// OPT-NEXT:    [[AGG_TEMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[INTPTR_TBAA5:![0-9]+]]
// OPT-NEXT:    [[IDXPROM:%.*]] = sext i32 [[IDX]] to i64
// OPT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [4 x i8], ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 [[IDXPROM]]
// OPT-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[ARRAYIDX]], i64 4, !annotation [[META8:![0-9]+]]
// OPT-NEXT:    [[DOTNOT:%.*]] = icmp ugt ptr [[TMP0]], [[AGG_TEMP_SROA_2_0_COPYLOAD]], !annotation [[META8]]
// OPT-NEXT:    br i1 [[DOTNOT]], label %[[TRAP:.*]], label %[[CONT:.*]], {{!prof ![0-9]+}}, !annotation [[META8]]
// OPT:       [[TRAP]]:
// OPT-NEXT:    tail call preserve_allcc void @__bounds_safety_soft_trap_s(ptr nonnull @trap.reason) #[[ATTR2:[0-9]+]], !annotation [[META8]]
// OPT-NEXT:    br label %[[CONT]], !annotation [[META8]]
// OPT:       [[CONT]]:
// OPT-NEXT:    [[DOTNOT5:%.*]] = icmp ugt ptr [[ARRAYIDX]], [[TMP0]], !annotation [[META8]]
// OPT-NEXT:    br i1 [[DOTNOT5]], label %[[TRAP1:.*]], label %[[CONT2:.*]], {{!prof ![0-9]+}}, !annotation [[META8]]
// OPT:       [[TRAP1]]:
// OPT-NEXT:    tail call preserve_allcc void @__bounds_safety_soft_trap_s(ptr nonnull @trap.reason.1) #[[ATTR2]], !annotation [[META8]]
// OPT-NEXT:    br label %[[CONT2]], !annotation [[META8]]
// OPT:       [[CONT2]]:
// OPT-NEXT:    [[DOTNOT6:%.*]] = icmp ult ptr [[ARRAYIDX]], [[AGG_TEMP_SROA_3_0_COPYLOAD]], !annotation [[META10:![0-9]+]]
// OPT-NEXT:    br i1 [[DOTNOT6]], label %[[TRAP3:.*]], label %[[CONT4:.*]], {{!prof ![0-9]+}}, !annotation [[META10]]
// OPT:       [[TRAP3]]:
// OPT-NEXT:    tail call preserve_allcc void @__bounds_safety_soft_trap_s(ptr nonnull @trap.reason.2) #[[ATTR2]], !annotation [[META10]]
// OPT-NEXT:    br label %[[CONT4]], !annotation [[META10]]
// OPT:       [[CONT4]]:
// OPT-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[INT_TBAA1:![0-9]+]]
// OPT-NEXT:    ret i32 [[TMP1]]
//
int read(int* __bidi_indexable ptr, int idx) {
    return ptr[idx];
}

void receive_cb(int*__counted_by(count) ptr, int count);

// UNOPT-LABEL: define dso_local i32 @read_cb(
// UNOPT-SAME: ptr noundef [[PTR:%.*]], i32 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// UNOPT-NEXT:  [[ENTRY:.*]]:
// UNOPT-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr, align 8
// UNOPT-NEXT:    [[COUNT_ADDR:%.*]] = alloca i32, align 4
// UNOPT-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-NEXT:    [[AGG_TEMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-NEXT:    [[AGG_TEMP11:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-NEXT:    [[AGG_TEMP20:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-NEXT:    [[AGG_TEMP28:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-NEXT:    [[AGG_TEMP37:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-NEXT:    [[AGG_TEMP50:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-NEXT:    store ptr [[PTR]], ptr [[PTR_ADDR]], align 8
// UNOPT-NEXT:    store i32 [[COUNT]], ptr [[COUNT_ADDR]], align 4
// UNOPT-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[PTR_ADDR]], align 8
// UNOPT-NEXT:    [[TMP1:%.*]] = load i32, ptr [[COUNT_ADDR]], align 4
// UNOPT-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP1]] to i64
// UNOPT-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 [[IDX_EXT]]
// UNOPT-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// UNOPT-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
// UNOPT-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// UNOPT-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP3]], align 8
// UNOPT-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// UNOPT-NEXT:    store ptr [[TMP0]], ptr [[TMP4]], align 8
// UNOPT-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT_ADDR]], align 4
// UNOPT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META4:![0-9]+]]
// UNOPT-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP2]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB_ADDR3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB4:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR3]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-NEXT:    store ptr [[WIDE_PTR_UB4]], ptr [[TMP6]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_PTR_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_PTR6:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR5]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB_ADDR7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB8:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR7]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_LB_ADDR9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 2, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_LB10:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR9]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_PTR6]], !annotation [[META4]]
// UNOPT-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END49:.*]], !annotation [[META4]]
// UNOPT:       [[LAND_LHS_TRUE]]:
// UNOPT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP11]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 2, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-NEXT:    store ptr [[WIDE_PTR_LB13]], ptr [[TMP7]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_PTR_ADDR14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_PTR15:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR14]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB17:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR16]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_LB_ADDR18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 2, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_LB19:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR18]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP20]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_PTR_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_PTR22:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR21]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB24:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR23]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_LB_ADDR25:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 2, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_LB26:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR25]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[CMP27:%.*]] = icmp ule ptr [[WIDE_PTR_PTR15]], [[WIDE_PTR_PTR22]], !annotation [[META4]]
// UNOPT-NEXT:    br i1 [[CMP27]], label %[[LAND_RHS:.*]], label %[[LAND_END49]], !annotation [[META4]]
// UNOPT:       [[LAND_RHS]]:
// UNOPT-NEXT:    [[CONV:%.*]] = sext i32 [[TMP5]] to i64, !annotation [[META4]]
// UNOPT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP28]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB_ADDR29:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB30:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR29]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-NEXT:    store ptr [[WIDE_PTR_UB30]], ptr [[TMP8]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_PTR_ADDR31:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_PTR32:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR31]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB34:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR33]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_LB_ADDR35:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 2, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_LB36:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR35]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP37]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_PTR_ADDR38:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP37]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_PTR39:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR38]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB_ADDR40:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP37]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_UB41:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR40]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_LB_ADDR42:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP37]], i32 0, i32 2, !annotation [[META4]]
// UNOPT-NEXT:    [[WIDE_PTR_LB43:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR42]], align 8, !annotation [[META4]]
// UNOPT-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR32]] to i64, !annotation [[META4]]
// UNOPT-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR39]] to i64, !annotation [[META4]]
// UNOPT-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META4]]
// UNOPT-NEXT:    [[SUB_PTR_DIV:%.*]] = sdiv exact i64 [[SUB_PTR_SUB]], 4, !annotation [[META4]]
// UNOPT-NEXT:    [[CMP44:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_DIV]], !annotation [[META4]]
// UNOPT-NEXT:    br i1 [[CMP44]], label %[[LAND_RHS46:.*]], label %[[LAND_END:.*]], !annotation [[META4]]
// UNOPT:       [[LAND_RHS46]]:
// UNOPT-NEXT:    [[CMP47:%.*]] = icmp sle i32 0, [[TMP5]], !annotation [[META4]]
// UNOPT-NEXT:    br label %[[LAND_END]], !annotation [[META4]]
// UNOPT:       [[LAND_END]]:
// UNOPT-NEXT:    [[TMP9:%.*]] = phi i1 [ false, %[[LAND_RHS]] ], [ [[CMP47]], %[[LAND_RHS46]] ]
// UNOPT-NEXT:    br label %[[LAND_END49]], !annotation [[META4]]
// UNOPT:       [[LAND_END49]]:
// UNOPT-NEXT:    [[TMP10:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP9]], %[[LAND_END]] ], !annotation [[META4]]
// UNOPT-NEXT:    br i1 [[TMP10]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// UNOPT:       [[TRAP]]:
// UNOPT-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap_s(ptr null) #[[ATTR3]], !annotation [[META4]]
// UNOPT-NEXT:    br label %[[CONT]], !annotation [[META4]]
// UNOPT:       [[CONT]]:
// UNOPT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP50]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false)
// UNOPT-NEXT:    [[WIDE_PTR_PTR_ADDR51:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP50]], i32 0, i32 0
// UNOPT-NEXT:    [[WIDE_PTR_PTR52:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR51]], align 8
// UNOPT-NEXT:    [[WIDE_PTR_UB_ADDR53:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP50]], i32 0, i32 1
// UNOPT-NEXT:    [[WIDE_PTR_UB54:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR53]], align 8
// UNOPT-NEXT:    [[WIDE_PTR_LB_ADDR55:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP50]], i32 0, i32 2
// UNOPT-NEXT:    [[WIDE_PTR_LB56:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR55]], align 8
// UNOPT-NEXT:    call void @receive_cb(ptr noundef [[WIDE_PTR_PTR52]], i32 noundef [[TMP5]])
// UNOPT-NEXT:    ret i32 0
//
// UNOPT-TF-LABEL: define dso_local i32 @read_cb(
// UNOPT-TF-SAME: ptr noundef [[PTR:%.*]], i32 noundef [[COUNT:%.*]]) #[[ATTR0]] {
// UNOPT-TF-NEXT:  [[ENTRY:.*]]:
// UNOPT-TF-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr, align 8
// UNOPT-TF-NEXT:    [[COUNT_ADDR:%.*]] = alloca i32, align 4
// UNOPT-TF-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-TF-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-TF-NEXT:    [[AGG_TEMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-TF-NEXT:    [[AGG_TEMP11:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-TF-NEXT:    [[AGG_TEMP20:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-TF-NEXT:    [[AGG_TEMP28:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-TF-NEXT:    [[AGG_TEMP37:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-TF-NEXT:    [[AGG_TEMP50:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-TF-NEXT:    store ptr [[PTR]], ptr [[PTR_ADDR]], align 8
// UNOPT-TF-NEXT:    store i32 [[COUNT]], ptr [[COUNT_ADDR]], align 4
// UNOPT-TF-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[PTR_ADDR]], align 8
// UNOPT-TF-NEXT:    [[TMP1:%.*]] = load i32, ptr [[COUNT_ADDR]], align 4
// UNOPT-TF-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP1]] to i64
// UNOPT-TF-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 [[IDX_EXT]]
// UNOPT-TF-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// UNOPT-TF-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
// UNOPT-TF-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// UNOPT-TF-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP3]], align 8
// UNOPT-TF-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// UNOPT-TF-NEXT:    store ptr [[TMP0]], ptr [[TMP4]], align 8
// UNOPT-TF-NEXT:    [[TMP5:%.*]] = load i32, ptr [[COUNT_ADDR]], align 4
// UNOPT-TF-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META4:![0-9]+]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP2]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB_ADDR3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB4:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR3]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-TF-NEXT:    store ptr [[WIDE_PTR_UB4]], ptr [[TMP6]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR6:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR5]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB_ADDR7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB8:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR7]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB_ADDR9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 2, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB10:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR9]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[CMP:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_PTR6]], !annotation [[META4]]
// UNOPT-TF-NEXT:    br i1 [[CMP]], label %[[LAND_LHS_TRUE:.*]], label %[[LAND_END49:.*]], !annotation [[META4]]
// UNOPT-TF:       [[LAND_LHS_TRUE]]:
// UNOPT-TF-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP11]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 2, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-TF-NEXT:    store ptr [[WIDE_PTR_LB13]], ptr [[TMP7]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR_ADDR14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR15:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR14]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB_ADDR16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB17:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR16]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB_ADDR18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP11]], i32 0, i32 2, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB19:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR18]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP20]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR_ADDR21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR22:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR21]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB_ADDR23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB24:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR23]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB_ADDR25:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP20]], i32 0, i32 2, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB26:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR25]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[CMP27:%.*]] = icmp ule ptr [[WIDE_PTR_PTR15]], [[WIDE_PTR_PTR22]], !annotation [[META4]]
// UNOPT-TF-NEXT:    br i1 [[CMP27]], label %[[LAND_RHS:.*]], label %[[LAND_END49]], !annotation [[META4]]
// UNOPT-TF:       [[LAND_RHS]]:
// UNOPT-TF-NEXT:    [[CONV:%.*]] = sext i32 [[TMP5]] to i64, !annotation [[META4]]
// UNOPT-TF-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP28]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB_ADDR29:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB30:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR29]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-TF-NEXT:    store ptr [[WIDE_PTR_UB30]], ptr [[TMP8]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR_ADDR31:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR32:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR31]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB_ADDR33:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB34:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR33]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB_ADDR35:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP28]], i32 0, i32 2, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB36:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR35]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP37]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false), !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR_ADDR38:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP37]], i32 0, i32 0, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR39:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR38]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB_ADDR40:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP37]], i32 0, i32 1, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB41:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR40]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB_ADDR42:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP37]], i32 0, i32 2, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB43:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR42]], align 8, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR32]] to i64, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR39]] to i64, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], !annotation [[META4]]
// UNOPT-TF-NEXT:    [[SUB_PTR_DIV:%.*]] = sdiv exact i64 [[SUB_PTR_SUB]], 4, !annotation [[META4]]
// UNOPT-TF-NEXT:    [[CMP44:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_DIV]], !annotation [[META4]]
// UNOPT-TF-NEXT:    br i1 [[CMP44]], label %[[LAND_RHS46:.*]], label %[[LAND_END:.*]], !annotation [[META4]]
// UNOPT-TF:       [[LAND_RHS46]]:
// UNOPT-TF-NEXT:    [[CMP47:%.*]] = icmp sle i32 0, [[TMP5]], !annotation [[META4]]
// UNOPT-TF-NEXT:    br label %[[LAND_END]], !annotation [[META4]]
// UNOPT-TF:       [[LAND_END]]:
// UNOPT-TF-NEXT:    [[TMP9:%.*]] = phi i1 [ false, %[[LAND_RHS]] ], [ [[CMP47]], %[[LAND_RHS46]] ]
// UNOPT-TF-NEXT:    br label %[[LAND_END49]], !annotation [[META4]]
// UNOPT-TF:       [[LAND_END49]]:
// UNOPT-TF-NEXT:    [[TMP10:%.*]] = phi i1 [ false, %[[LAND_LHS_TRUE]] ], [ false, %[[ENTRY]] ], [ [[TMP9]], %[[LAND_END]] ], !annotation [[META4]]
// UNOPT-TF-NEXT:    br i1 [[TMP10]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, !annotation [[META4]]
// UNOPT-TF:       [[TRAP]]:
// UNOPT-TF-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap_s(ptr null) #[[ATTR3]], !annotation [[META4]]
// UNOPT-TF-NEXT:    br label %[[CONT]], !annotation [[META4]]
// UNOPT-TF:       [[CONT]]:
// UNOPT-TF-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP50]], ptr align 8 [[AGG_TEMP]], i64 24, i1 false)
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR_ADDR51:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP50]], i32 0, i32 0
// UNOPT-TF-NEXT:    [[WIDE_PTR_PTR52:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR51]], align 8
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB_ADDR53:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP50]], i32 0, i32 1
// UNOPT-TF-NEXT:    [[WIDE_PTR_UB54:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR53]], align 8
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB_ADDR55:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP50]], i32 0, i32 2
// UNOPT-TF-NEXT:    [[WIDE_PTR_LB56:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR55]], align 8
// UNOPT-TF-NEXT:    call void @receive_cb(ptr noundef [[WIDE_PTR_PTR52]], i32 noundef [[TMP5]]) #[[ATTR4:[0-9]+]]
// UNOPT-TF-NEXT:    ret i32 0
//
// OPT-LABEL: define dso_local noundef i32 @read_cb(
// OPT-SAME: ptr noundef [[PTR:%.*]], i32 noundef [[COUNT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// OPT-NEXT:  [[ENTRY:.*:]]
// OPT-NEXT:    [[CMP_NOT:%.*]] = icmp slt i32 [[COUNT]], 0, !annotation [[META11:![0-9]+]]
// OPT-NEXT:    br i1 [[CMP_NOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !annotation [[META11]]
// OPT:       [[TRAP]]:
// OPT-NEXT:    tail call preserve_allcc void @__bounds_safety_soft_trap_s(ptr null) #[[ATTR2]], !annotation [[META11]]
// OPT-NEXT:    br label %[[CONT]], !annotation [[META11]]
// OPT:       [[CONT]]:
// OPT-NEXT:    tail call void @receive_cb(ptr noundef [[PTR]], i32 noundef [[COUNT]]) #[[ATTR3:[0-9]+]]
// OPT-NEXT:    ret i32 0
//
int read_cb(int*__counted_by(count) ptr, int count) {
    receive_cb(ptr, count);
    return 0;
}
//.
// UNOPT: attributes #[[ATTR0]] = { noinline nounwind optnone "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
// UNOPT: attributes #[[ATTR1:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
// UNOPT: attributes #[[ATTR2:[0-9]+]] = { "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
// UNOPT: attributes #[[ATTR3]] = { nomerge nounwind }
//.
// UNOPT-TF: attributes #[[ATTR0]] = { noinline nounwind optnone "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
// UNOPT-TF: attributes #[[ATTR1:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
// UNOPT-TF: attributes #[[ATTR2:[0-9]+]] = { "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
// UNOPT-TF: attributes #[[ATTR3]] = { nomerge nounwind }
// UNOPT-TF: attributes #[[ATTR4]] = { "trap-func-name"="not_used" }
//.
// OPT: attributes #[[ATTR0]] = { nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
// OPT: attributes #[[ATTR1:[0-9]+]] = { "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
// OPT: attributes #[[ATTR2]] = { nomerge nounwind }
// OPT: attributes #[[ATTR3]] = { nounwind }
//.
// UNOPT: [[META0:![0-9]+]] = !{!"{{.*}}clang version {{.*}}"}
// UNOPT: [[META1]] = !{!"bounds-safety-check-ptr-le-upper-bound"}
// UNOPT: [[META2:![0-9]+]] = !{!"branch_weights", i32 1048575, i32 1}
// UNOPT: [[META3]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
// UNOPT: [[META4]] = !{!"bounds-safety-generic"}
//.
// UNOPT-TF: [[META0:![0-9]+]] = !{!"{{.*}}clang version {{.*}}"}
// UNOPT-TF: [[META1]] = !{!"bounds-safety-check-ptr-le-upper-bound"}
// UNOPT-TF: [[META2:![0-9]+]] = !{!"branch_weights", i32 1048575, i32 1}
// UNOPT-TF: [[META3]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
// UNOPT-TF: [[META4]] = !{!"bounds-safety-generic"}
//.
// OPT: [[META0:![0-9]+]] = !{!"{{.*}}clang version {{.*}}"}
// OPT: [[INT_TBAA1]] = !{[[META2:![0-9]+]], [[META2]], i64 0}
// OPT: [[META2]] = !{!"int", [[META3:![0-9]+]], i64 0}
// OPT: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// OPT: [[META4]] = !{!"Simple C/C++ TBAA"}
// OPT: [[INTPTR_TBAA5]] = !{[[META6:![0-9]+]], [[META6]], i64 0}
// OPT: [[META6]] = !{!"p1 int", [[META7:![0-9]+]], i64 0}
// OPT: [[META7]] = !{!"any pointer", [[META3]], i64 0}
// OPT: [[META8]] = !{!"bounds-safety-check-ptr-le-upper-bound"}
// OPT: [[META9:![0-9]+]] = !{!"branch_weights", i32 1, i32 1048575}
// OPT: [[META10]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
// OPT: [[META11]] = !{!"bounds-safety-generic"}
//.
