// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-globals all --version 6
// RUN: %clang_cc1 -O0 -fbounds-safety -triple arm64-apple-iphoneos \
// RUN:   -emit-llvm %s -o - -fbounds-safety-soft-traps=call-minimal | \
// RUN:   FileCheck --check-prefixes=UNOPT %s

// Check `-ftrap-function` is ignored for `-fbounds-safety` when using
// `-fbounds-safety-soft-traps=`
// RUN: %clang_cc1 -O0 -fbounds-safety -triple arm64-apple-iphoneos \
// RUN:   -emit-llvm %s -o - -fbounds-safety-soft-traps=call-minimal \
// RUN:   -ftrap-function=not_used | \
// RUN:   FileCheck --check-prefixes=UNOPT %s

// RUN: %clang_cc1 -O2 -fbounds-safety -triple arm64-apple-iphoneos \
// RUN:   -emit-llvm %s -o - -fbounds-safety-soft-traps=call-minimal | \
// RUN:   FileCheck --check-prefixes=OPT %s
#include <ptrcheck.h>

// UNOPT-LABEL: define dso_local i32 @read(
// UNOPT-SAME: ptr noundef dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]]) #[[ATTR0:[0-9]+]] {
// UNOPT-NEXT:  [[ENTRY:.*:]]
// UNOPT-NEXT:    [[PTR_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// UNOPT-NEXT:    [[IDX_ADDR:%.*]] = alloca i32, align 4
// UNOPT-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// UNOPT-NEXT:    store ptr [[PTR]], ptr [[PTR_INDIRECT_ADDR]], align 8
// UNOPT-NEXT:    store i32 [[IDX]], ptr [[IDX_ADDR]], align 4
// UNOPT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[PTR]], i64 24, i1 false)
// UNOPT-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// UNOPT-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// UNOPT-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IDX_ADDR]], align 4
// UNOPT-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP0]] to i64
// UNOPT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 [[IDXPROM]]
// UNOPT-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// UNOPT-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// UNOPT-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// UNOPT-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// UNOPT-NEXT:    [[TMP1:%.*]] = getelementptr i32, ptr [[ARRAYIDX]], i64 1, !annotation [[META2:![0-9]+]]
// UNOPT-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[TMP1]], [[WIDE_PTR_UB]], !annotation [[META2]]
// UNOPT-NEXT:    br i1 [[TMP2]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF3:![0-9]+]], !annotation [[META2]]
// UNOPT:       [[TRAP]]:
// UNOPT-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR2:[0-9]+]], !annotation [[META2]]
// UNOPT-NEXT:    br label %[[CONT]], !annotation [[META2]]
// UNOPT:       [[CONT]]:
// UNOPT-NEXT:    [[TMP3:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP1]], !annotation [[META2]]
// UNOPT-NEXT:    br i1 [[TMP3]], label %[[CONT2:.*]], label %[[TRAP1:.*]], !prof [[PROF3]], !annotation [[META2]]
// UNOPT:       [[TRAP1]]:
// UNOPT-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR2]], !annotation [[META2]]
// UNOPT-NEXT:    br label %[[CONT2]], !annotation [[META2]]
// UNOPT:       [[CONT2]]:
// UNOPT-NEXT:    [[TMP4:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], !annotation [[META4:![0-9]+]]
// UNOPT-NEXT:    br i1 [[TMP4]], label %[[CONT4:.*]], label %[[TRAP3:.*]], !prof [[PROF3]], !annotation [[META4]]
// UNOPT:       [[TRAP3]]:
// UNOPT-NEXT:    call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR2]], !annotation [[META4]]
// UNOPT-NEXT:    br label %[[CONT4]], !annotation [[META4]]
// UNOPT:       [[CONT4]]:
// UNOPT-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// UNOPT-NEXT:    ret i32 [[TMP5]]
//
// OPT-LABEL: define dso_local i32 @read(
// OPT-SAME: ptr noundef readonly captures(none) dead_on_return [[PTR:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// OPT-NEXT:  [[ENTRY:.*:]]
// OPT-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// OPT-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// OPT-NEXT:    [[AGG_TEMP_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// OPT-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// OPT-NEXT:    [[AGG_TEMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[INTPTR_TBAA6:![0-9]+]]
// OPT-NEXT:    [[IDXPROM:%.*]] = sext i32 [[IDX]] to i64
// OPT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [4 x i8], ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 [[IDXPROM]]
// OPT-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[ARRAYIDX]], i64 4, !annotation [[META9:![0-9]+]]
// OPT-NEXT:    [[DOTNOT:%.*]] = icmp ugt ptr [[TMP0]], [[AGG_TEMP_SROA_2_0_COPYLOAD]], !annotation [[META9]]
// OPT-NEXT:    br i1 [[DOTNOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !prof [[PROF10:![0-9]+]], !annotation [[META9]]
// OPT:       [[TRAP]]:
// OPT-NEXT:    tail call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR1:[0-9]+]], !annotation [[META9]]
// OPT-NEXT:    br label %[[CONT]], !annotation [[META9]]
// OPT:       [[CONT]]:
// OPT-NEXT:    [[DOTNOT5:%.*]] = icmp ugt ptr [[ARRAYIDX]], [[TMP0]], !annotation [[META9]]
// OPT-NEXT:    br i1 [[DOTNOT5]], label %[[TRAP1:.*]], label %[[CONT2:.*]], !prof [[PROF10]], !annotation [[META9]]
// OPT:       [[TRAP1]]:
// OPT-NEXT:    tail call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR1]], !annotation [[META9]]
// OPT-NEXT:    br label %[[CONT2]], !annotation [[META9]]
// OPT:       [[CONT2]]:
// OPT-NEXT:    [[DOTNOT6:%.*]] = icmp ult ptr [[ARRAYIDX]], [[AGG_TEMP_SROA_3_0_COPYLOAD]], !annotation [[META11:![0-9]+]]
// OPT-NEXT:    br i1 [[DOTNOT6]], label %[[TRAP3:.*]], label %[[CONT4:.*]], !prof [[PROF10]], !annotation [[META11]]
// OPT:       [[TRAP3]]:
// OPT-NEXT:    tail call preserve_allcc void @__bounds_safety_soft_trap() #[[ATTR1]], !annotation [[META11]]
// OPT-NEXT:    br label %[[CONT4]], !annotation [[META11]]
// OPT:       [[CONT4]]:
// OPT-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[INT_TBAA2:![0-9]+]]
// OPT-NEXT:    ret i32 [[TMP1]]
//
int read(int* __bidi_indexable ptr, int idx) {
    return ptr[idx];
}

//
//
//
//.
// UNOPT: attributes #[[ATTR0]] = { noinline nounwind optnone "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
// UNOPT: attributes #[[ATTR1:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
// UNOPT: attributes #[[ATTR2]] = { nomerge nounwind }
//.
// OPT: attributes #[[ATTR0]] = { nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
// OPT: attributes #[[ATTR1]] = { nomerge nounwind }
//.
// UNOPT: [[META1:![0-9]+]] = !{!"{{.*}}clang version {{.*}}"}
// UNOPT: [[META2]] = !{!"bounds-safety-check-ptr-le-upper-bound"}
// UNOPT: [[PROF3]] = !{!"branch_weights", i32 1048575, i32 1}
// UNOPT: [[META4]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
//.
// OPT: [[META1:![0-9]+]] = !{!"{{.*}}clang version {{.*}}"}
// OPT: [[INT_TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// OPT: [[META3]] = !{!"int", [[META4:![0-9]+]], i64 0}
// OPT: [[META4]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// OPT: [[META5]] = !{!"Simple C/C++ TBAA"}
// OPT: [[INTPTR_TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
// OPT: [[META7]] = !{!"p1 int", [[META8:![0-9]+]], i64 0}
// OPT: [[META8]] = !{!"any pointer", [[META4]], i64 0}
// OPT: [[META9]] = !{!"bounds-safety-check-ptr-le-upper-bound"}
// OPT: [[PROF10]] = !{!"branch_weights", i32 1, i32 1048575}
// OPT: [[META11]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
//.
