; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=mergeicmps -mtriple=x86_64-unknown-unknown -S | FileCheck %s

define i1 @test(ptr dereferenceable(4) %a, ptr dereferenceable(4) %b) {
; CHECK-LABEL: define i1 @test(
; CHECK-SAME: ptr dereferenceable(4) [[A:%.*]], ptr dereferenceable(4) [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[A_ELEM1_ADDR:%.*]] = getelementptr i8, ptr [[A]], i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[A_ELEM1_ADDR]], align 1
; CHECK-NEXT:    [[B_ELEM1_ADDR:%.*]] = getelementptr i8, ptr [[B]], i64 1
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[B_ELEM1_ADDR]], align 1
; CHECK-NEXT:    [[CMP_ELEM1:%.*]] = icmp eq i8 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[CMP_ELEM1]], label %[[LAND_ELEM0:.*]], label %[[OPEQ_EXIT:.*]]
; CHECK:       [[LAND_ELEM0]]:
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[A]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[B]], align 1
; CHECK-NEXT:    [[CMP_ELEM0:%.*]] = icmp eq i8 [[TMP2]], [[TMP3]]
; CHECK-NEXT:    br label %[[OPEQ_EXIT]]
; CHECK:       [[OPEQ_EXIT]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ [[CMP_ELEM0]], %[[LAND_ELEM0]] ]
; CHECK-NEXT:    ret i1 [[PHI]]
;
entry:
  %a.elem1.addr = getelementptr i8, ptr %a, i64 1
  %0 = load i8, ptr %a.elem1.addr, align 1
  %b.elem1.addr = getelementptr i8, ptr %b, i64 1
  %1 = load i8, ptr %b.elem1.addr, align 1
  %cmp.elem1 = icmp eq i8 %0, %1
  br i1 %cmp.elem1, label %land.elem0, label %opeq.exit

land.elem0:
  %2 = load i8, ptr %a, align 1
  %3 = load i8, ptr %b, align 1
  %cmp.elem0 = icmp eq i8 %2, %3
  br label %opeq.exit

opeq.exit:
  %phi = phi i1 [ false, %entry ], [ %cmp.elem0, %land.elem0 ]
  ret i1 %phi
}

declare i32 @memcmp()
