; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5

; RUN: llc -mtriple=x86_64-linux-gnu -mattr=+sse4.1 -global-isel -global-isel-abort=1 < %s | FileCheck %s --check-prefixes=GISEL-SSE41
; RUN: llc -mtriple=x86_64-linux-gnu -mattr=+avx -global-isel -global-isel-abort=1 < %s | FileCheck %s --check-prefixes=GISEL-AVX
; RUN: llc -mtriple=x86_64-linux-gnu -mattr=+sse4.1 < %s | FileCheck %s --check-prefixes=SDAG-SSE41
; RUN: llc -mtriple=x86_64-linux-gnu -mattr=+avx < %s | FileCheck %s --check-prefixes=SDAG-AVX

;128-bit integer vectors

define <4 x i32> @build_vector_v4i32(i32 %a, i32 %b, i32 %c, i32 %d) {
; GISEL-SSE41-LABEL: build_vector_v4i32:
; GISEL-SSE41:       # %bb.0:
; GISEL-SSE41-NEXT:    movd %edi, %xmm0
; GISEL-SSE41-NEXT:    pinsrd $1, %esi, %xmm0
; GISEL-SSE41-NEXT:    pinsrd $2, %edx, %xmm0
; GISEL-SSE41-NEXT:    pinsrd $3, %ecx, %xmm0
; GISEL-SSE41-NEXT:    retq
;
; GISEL-AVX-LABEL: build_vector_v4i32:
; GISEL-AVX:       # %bb.0:
; GISEL-AVX-NEXT:    vmovd %edi, %xmm0
; GISEL-AVX-NEXT:    vpinsrd $1, %esi, %xmm0, %xmm0
; GISEL-AVX-NEXT:    vpinsrd $2, %edx, %xmm0, %xmm0
; GISEL-AVX-NEXT:    vpinsrd $3, %ecx, %xmm0, %xmm0
; GISEL-AVX-NEXT:    retq
;
; SDAG-SSE41-LABEL: build_vector_v4i32:
; SDAG-SSE41:       # %bb.0:
; SDAG-SSE41-NEXT:    movd %edi, %xmm0
; SDAG-SSE41-NEXT:    pinsrd $1, %esi, %xmm0
; SDAG-SSE41-NEXT:    pinsrd $2, %edx, %xmm0
; SDAG-SSE41-NEXT:    pinsrd $3, %ecx, %xmm0
; SDAG-SSE41-NEXT:    retq
;
; SDAG-AVX-LABEL: build_vector_v4i32:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vmovd %edi, %xmm0
; SDAG-AVX-NEXT:    vpinsrd $1, %esi, %xmm0, %xmm0
; SDAG-AVX-NEXT:    vpinsrd $2, %edx, %xmm0, %xmm0
; SDAG-AVX-NEXT:    vpinsrd $3, %ecx, %xmm0, %xmm0
; SDAG-AVX-NEXT:    retq
  %v0 = insertelement <4 x i32> undef, i32 %a, i64 0
  %v1 = insertelement <4 x i32> %v0, i32 %b, i64 1
  %v2 = insertelement <4 x i32> %v1, i32 %c, i64 2
  %v3 = insertelement <4 x i32> %v2, i32 %d, i64 3
  ret <4 x i32> %v3
}

define <2 x i64> @build_vector_v2i64(i64 %a, i64 %b) {
; GISEL-SSE41-LABEL: build_vector_v2i64:
; GISEL-SSE41:       # %bb.0:
; GISEL-SSE41-NEXT:    movq %rsi, %xmm1
; GISEL-SSE41-NEXT:    movq %rdi, %xmm0
; GISEL-SSE41-NEXT:    punpcklqdq {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; GISEL-SSE41-NEXT:    retq
;
; GISEL-AVX-LABEL: build_vector_v2i64:
; GISEL-AVX:       # %bb.0:
; GISEL-AVX-NEXT:    vmovq %rsi, %xmm0
; GISEL-AVX-NEXT:    vmovq %rdi, %xmm1
; GISEL-AVX-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; GISEL-AVX-NEXT:    retq
;
; SDAG-SSE41-LABEL: build_vector_v2i64:
; SDAG-SSE41:       # %bb.0:
; SDAG-SSE41-NEXT:    movq %rsi, %xmm1
; SDAG-SSE41-NEXT:    movq %rdi, %xmm0
; SDAG-SSE41-NEXT:    punpcklqdq {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; SDAG-SSE41-NEXT:    retq
;
; SDAG-AVX-LABEL: build_vector_v2i64:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vmovq %rsi, %xmm0
; SDAG-AVX-NEXT:    vmovq %rdi, %xmm1
; SDAG-AVX-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; SDAG-AVX-NEXT:    retq
  %v0 = insertelement <2 x i64> undef, i64 %a, i64 0
  %v1 = insertelement <2 x i64> %v0, i64 %b, i64 1
  ret <2 x i64> %v1
}

;128-bit floating-point vectors

define <4 x float> @build_vector_v4f32(float %a, float %b, float %c, float %d) {
; GISEL-SSE41-LABEL: build_vector_v4f32:
; GISEL-SSE41:       # %bb.0:
; GISEL-SSE41-NEXT:    movd %xmm0, %eax
; GISEL-SSE41-NEXT:    movd %eax, %xmm0
; GISEL-SSE41-NEXT:    movd %xmm1, %eax
; GISEL-SSE41-NEXT:    pinsrd $1, %eax, %xmm0
; GISEL-SSE41-NEXT:    movd %xmm2, %eax
; GISEL-SSE41-NEXT:    pinsrd $2, %eax, %xmm0
; GISEL-SSE41-NEXT:    movd %xmm3, %eax
; GISEL-SSE41-NEXT:    pinsrd $3, %eax, %xmm0
; GISEL-SSE41-NEXT:    retq
;
; GISEL-AVX-LABEL: build_vector_v4f32:
; GISEL-AVX:       # %bb.0:
; GISEL-AVX-NEXT:    vmovd %xmm0, %eax
; GISEL-AVX-NEXT:    vmovd %eax, %xmm0
; GISEL-AVX-NEXT:    vmovd %xmm1, %eax
; GISEL-AVX-NEXT:    vpinsrd $1, %eax, %xmm0, %xmm0
; GISEL-AVX-NEXT:    vmovd %xmm2, %eax
; GISEL-AVX-NEXT:    vpinsrd $2, %eax, %xmm0, %xmm0
; GISEL-AVX-NEXT:    vmovd %xmm3, %eax
; GISEL-AVX-NEXT:    vpinsrd $3, %eax, %xmm0, %xmm0
; GISEL-AVX-NEXT:    retq
;
; SDAG-SSE41-LABEL: build_vector_v4f32:
; SDAG-SSE41:       # %bb.0:
; SDAG-SSE41-NEXT:    insertps {{.*#+}} xmm0 = xmm0[0],xmm1[0],xmm0[2,3]
; SDAG-SSE41-NEXT:    insertps {{.*#+}} xmm0 = xmm0[0,1],xmm2[0],xmm0[3]
; SDAG-SSE41-NEXT:    insertps {{.*#+}} xmm0 = xmm0[0,1,2],xmm3[0]
; SDAG-SSE41-NEXT:    retq
;
; SDAG-AVX-LABEL: build_vector_v4f32:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm0 = xmm0[0],xmm1[0],xmm0[2,3]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm0 = xmm0[0,1],xmm2[0],xmm0[3]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm0 = xmm0[0,1,2],xmm3[0]
; SDAG-AVX-NEXT:    retq
  %v0 = insertelement <4 x float> undef, float %a, i64 0
  %v1 = insertelement <4 x float> %v0, float %b, i64 1
  %v2 = insertelement <4 x float> %v1, float %c, i64 2
  %v3 = insertelement <4 x float> %v2, float %d, i64 3
  ret <4 x float> %v3
}

define <2 x double> @build_vector_v2f64(double %a, double %b) {
; GISEL-SSE41-LABEL: build_vector_v2f64:
; GISEL-SSE41:       # %bb.0:
; GISEL-SSE41-NEXT:    movlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; GISEL-SSE41-NEXT:    retq
;
; GISEL-AVX-LABEL: build_vector_v2f64:
; GISEL-AVX:       # %bb.0:
; GISEL-AVX-NEXT:    vmovlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; GISEL-AVX-NEXT:    retq
;
; SDAG-SSE41-LABEL: build_vector_v2f64:
; SDAG-SSE41:       # %bb.0:
; SDAG-SSE41-NEXT:    movlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; SDAG-SSE41-NEXT:    retq
;
; SDAG-AVX-LABEL: build_vector_v2f64:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vmovlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; SDAG-AVX-NEXT:    retq
  %v0 = insertelement <2 x double> undef, double %a, i64 0
  %v1 = insertelement <2 x double> %v0, double %b, i64 1
  ret <2 x double> %v1
}

;256-bit integer vectors (require AVX)

define <8 x i32> @build_vector_v8i32(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e, i32 %f, i32 %g, i32 %h) #1 {
; GISEL-SSE41-LABEL: build_vector_v8i32:
; GISEL-SSE41:       # %bb.0:
; GISEL-SSE41-NEXT:    vmovd %edi, %xmm0
; GISEL-SSE41-NEXT:    vinsertf128 $0, %xmm0, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vpinsrd $1, %esi, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vpinsrd $2, %edx, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vpinsrd $3, %ecx, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $0, %r8d, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $1, %r9d, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    retq
;
; GISEL-AVX-LABEL: build_vector_v8i32:
; GISEL-AVX:       # %bb.0:
; GISEL-AVX-NEXT:    vmovd %edi, %xmm0
; GISEL-AVX-NEXT:    vinsertf128 $0, %xmm0, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vpinsrd $1, %esi, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vpinsrd $2, %edx, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vpinsrd $3, %ecx, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $0, %r8d, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $1, %r9d, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    retq
;
; SDAG-SSE41-LABEL: build_vector_v8i32:
; SDAG-SSE41:       # %bb.0:
; SDAG-SSE41-NEXT:    vmovd %edi, %xmm0
; SDAG-SSE41-NEXT:    vpinsrd $1, %esi, %xmm0, %xmm0
; SDAG-SSE41-NEXT:    vpinsrd $2, %edx, %xmm0, %xmm0
; SDAG-SSE41-NEXT:    vpinsrd $3, %ecx, %xmm0, %xmm0
; SDAG-SSE41-NEXT:    vmovd %r8d, %xmm1
; SDAG-SSE41-NEXT:    vpinsrd $1, %r9d, %xmm1, %xmm1
; SDAG-SSE41-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; SDAG-SSE41-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; SDAG-SSE41-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; SDAG-SSE41-NEXT:    retq
;
; SDAG-AVX-LABEL: build_vector_v8i32:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vmovd %edi, %xmm0
; SDAG-AVX-NEXT:    vpinsrd $1, %esi, %xmm0, %xmm0
; SDAG-AVX-NEXT:    vpinsrd $2, %edx, %xmm0, %xmm0
; SDAG-AVX-NEXT:    vpinsrd $3, %ecx, %xmm0, %xmm0
; SDAG-AVX-NEXT:    vmovd %r8d, %xmm1
; SDAG-AVX-NEXT:    vpinsrd $1, %r9d, %xmm1, %xmm1
; SDAG-AVX-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; SDAG-AVX-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; SDAG-AVX-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; SDAG-AVX-NEXT:    retq
  %v0 = insertelement <8 x i32> undef, i32 %a, i64 0
  %v1 = insertelement <8 x i32> %v0, i32 %b, i64 1
  %v2 = insertelement <8 x i32> %v1, i32 %c, i64 2
  %v3 = insertelement <8 x i32> %v2, i32 %d, i64 3
  %v4 = insertelement <8 x i32> %v3, i32 %e, i64 4
  %v5 = insertelement <8 x i32> %v4, i32 %f, i64 5
  %v6 = insertelement <8 x i32> %v5, i32 %g, i64 6
  %v7 = insertelement <8 x i32> %v6, i32 %h, i64 7
  ret <8 x i32> %v7
}

define <4 x i64> @build_vector_v4i64(i64 %a, i64 %b, i64 %c, i64 %d) #1 {
; GISEL-SSE41-LABEL: build_vector_v4i64:
; GISEL-SSE41:       # %bb.0:
; GISEL-SSE41-NEXT:    vmovq %rdi, %xmm0
; GISEL-SSE41-NEXT:    vinsertf128 $0, %xmm0, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vpinsrq $1, %rsi, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrq $0, %rdx, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrq $1, %rcx, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    retq
;
; GISEL-AVX-LABEL: build_vector_v4i64:
; GISEL-AVX:       # %bb.0:
; GISEL-AVX-NEXT:    vmovq %rdi, %xmm0
; GISEL-AVX-NEXT:    vinsertf128 $0, %xmm0, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vpinsrq $1, %rsi, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrq $0, %rdx, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrq $1, %rcx, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    retq
;
; SDAG-SSE41-LABEL: build_vector_v4i64:
; SDAG-SSE41:       # %bb.0:
; SDAG-SSE41-NEXT:    vmovq %rcx, %xmm0
; SDAG-SSE41-NEXT:    vmovq %rdx, %xmm1
; SDAG-SSE41-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; SDAG-SSE41-NEXT:    vmovq %rsi, %xmm1
; SDAG-SSE41-NEXT:    vmovq %rdi, %xmm2
; SDAG-SSE41-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm2[0],xmm1[0]
; SDAG-SSE41-NEXT:    vinsertf128 $1, %xmm0, %ymm1, %ymm0
; SDAG-SSE41-NEXT:    retq
;
; SDAG-AVX-LABEL: build_vector_v4i64:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vmovq %rcx, %xmm0
; SDAG-AVX-NEXT:    vmovq %rdx, %xmm1
; SDAG-AVX-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; SDAG-AVX-NEXT:    vmovq %rsi, %xmm1
; SDAG-AVX-NEXT:    vmovq %rdi, %xmm2
; SDAG-AVX-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm2[0],xmm1[0]
; SDAG-AVX-NEXT:    vinsertf128 $1, %xmm0, %ymm1, %ymm0
; SDAG-AVX-NEXT:    retq
  %v0 = insertelement <4 x i64> undef, i64 %a, i64 0
  %v1 = insertelement <4 x i64> %v0, i64 %b, i64 1
  %v2 = insertelement <4 x i64> %v1, i64 %c, i64 2
  %v3 = insertelement <4 x i64> %v2, i64 %d, i64 3
  ret <4 x i64> %v3
}

;256-bit floating-point vectors (require AVX)

define <8 x float> @build_vector_v8f32(float %a, float %b, float %c, float %d, float %e, float %f, float %g, float %h) #1 {
; GISEL-SSE41-LABEL: build_vector_v8f32:
; GISEL-SSE41:       # %bb.0:
; GISEL-SSE41-NEXT:    vmovd %xmm0, %eax
; GISEL-SSE41-NEXT:    vmovd %eax, %xmm0
; GISEL-SSE41-NEXT:    vinsertf128 $0, %xmm0, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vmovd %xmm1, %eax
; GISEL-SSE41-NEXT:    vpinsrd $1, %eax, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vmovd %xmm2, %eax
; GISEL-SSE41-NEXT:    vpinsrd $2, %eax, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vmovd %xmm3, %eax
; GISEL-SSE41-NEXT:    vpinsrd $3, %eax, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-SSE41-NEXT:    vmovd %xmm4, %eax
; GISEL-SSE41-NEXT:    vpinsrd $0, %eax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-SSE41-NEXT:    vmovd %xmm5, %eax
; GISEL-SSE41-NEXT:    vpinsrd $1, %eax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-SSE41-NEXT:    vmovd %xmm6, %eax
; GISEL-SSE41-NEXT:    vpinsrd $2, %eax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-SSE41-NEXT:    vmovd %xmm7, %eax
; GISEL-SSE41-NEXT:    vpinsrd $3, %eax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    retq
;
; GISEL-AVX-LABEL: build_vector_v8f32:
; GISEL-AVX:       # %bb.0:
; GISEL-AVX-NEXT:    vmovd %xmm0, %eax
; GISEL-AVX-NEXT:    vmovd %eax, %xmm0
; GISEL-AVX-NEXT:    vinsertf128 $0, %xmm0, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vmovd %xmm1, %eax
; GISEL-AVX-NEXT:    vpinsrd $1, %eax, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vmovd %xmm2, %eax
; GISEL-AVX-NEXT:    vpinsrd $2, %eax, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vmovd %xmm3, %eax
; GISEL-AVX-NEXT:    vpinsrd $3, %eax, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-AVX-NEXT:    vmovd %xmm4, %eax
; GISEL-AVX-NEXT:    vpinsrd $0, %eax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-AVX-NEXT:    vmovd %xmm5, %eax
; GISEL-AVX-NEXT:    vpinsrd $1, %eax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-AVX-NEXT:    vmovd %xmm6, %eax
; GISEL-AVX-NEXT:    vpinsrd $2, %eax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-AVX-NEXT:    vmovd %xmm7, %eax
; GISEL-AVX-NEXT:    vpinsrd $3, %eax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    retq
;
; SDAG-SSE41-LABEL: build_vector_v8f32:
; SDAG-SSE41:       # %bb.0:
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm4 = xmm4[0],xmm5[0],xmm4[2,3]
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm4 = xmm4[0,1],xmm6[0],xmm4[3]
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm4 = xmm4[0,1,2],xmm7[0]
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm0 = xmm0[0],xmm1[0],xmm0[2,3]
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm0 = xmm0[0,1],xmm2[0],xmm0[3]
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm0 = xmm0[0,1,2],xmm3[0]
; SDAG-SSE41-NEXT:    vinsertf128 $1, %xmm4, %ymm0, %ymm0
; SDAG-SSE41-NEXT:    retq
;
; SDAG-AVX-LABEL: build_vector_v8f32:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm4 = xmm4[0],xmm5[0],xmm4[2,3]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm4 = xmm4[0,1],xmm6[0],xmm4[3]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm4 = xmm4[0,1,2],xmm7[0]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm0 = xmm0[0],xmm1[0],xmm0[2,3]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm0 = xmm0[0,1],xmm2[0],xmm0[3]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm0 = xmm0[0,1,2],xmm3[0]
; SDAG-AVX-NEXT:    vinsertf128 $1, %xmm4, %ymm0, %ymm0
; SDAG-AVX-NEXT:    retq
  %v0 = insertelement <8 x float> undef, float %a, i64 0
  %v1 = insertelement <8 x float> %v0, float %b, i64 1
  %v2 = insertelement <8 x float> %v1, float %c, i64 2
  %v3 = insertelement <8 x float> %v2, float %d, i64 3
  %v4 = insertelement <8 x float> %v3, float %e, i64 4
  %v5 = insertelement <8 x float> %v4, float %f, i64 5
  %v6 = insertelement <8 x float> %v5, float %g, i64 6
  %v7 = insertelement <8 x float> %v6, float %h, i64 7
  ret <8 x float> %v7
}

define <4 x double> @build_vector_v4f64(double %a, double %b, double %c, double %d) #1 {
; GISEL-SSE41-LABEL: build_vector_v4f64:
; GISEL-SSE41:       # %bb.0:
; GISEL-SSE41-NEXT:    vmovq %xmm0, %rax
; GISEL-SSE41-NEXT:    vmovq %rax, %xmm0
; GISEL-SSE41-NEXT:    vinsertf128 $0, %xmm0, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vmovq %xmm1, %rax
; GISEL-SSE41-NEXT:    vpinsrq $1, %rax, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-SSE41-NEXT:    vmovq %xmm2, %rax
; GISEL-SSE41-NEXT:    vpinsrq $0, %rax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-SSE41-NEXT:    vmovq %xmm3, %rax
; GISEL-SSE41-NEXT:    vpinsrq $1, %rax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-SSE41-NEXT:    retq
;
; GISEL-AVX-LABEL: build_vector_v4f64:
; GISEL-AVX:       # %bb.0:
; GISEL-AVX-NEXT:    vmovq %xmm0, %rax
; GISEL-AVX-NEXT:    vmovq %rax, %xmm0
; GISEL-AVX-NEXT:    vinsertf128 $0, %xmm0, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vmovq %xmm1, %rax
; GISEL-AVX-NEXT:    vpinsrq $1, %rax, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $0, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-AVX-NEXT:    vmovq %xmm2, %rax
; GISEL-AVX-NEXT:    vpinsrq $0, %rax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    vextractf128 $1, %ymm0, %xmm1
; GISEL-AVX-NEXT:    vmovq %xmm3, %rax
; GISEL-AVX-NEXT:    vpinsrq $1, %rax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; GISEL-AVX-NEXT:    retq
;
; SDAG-SSE41-LABEL: build_vector_v4f64:
; SDAG-SSE41:       # %bb.0:
; SDAG-SSE41-NEXT:    vmovlhps {{.*#+}} xmm2 = xmm2[0],xmm3[0]
; SDAG-SSE41-NEXT:    vmovlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; SDAG-SSE41-NEXT:    vinsertf128 $1, %xmm2, %ymm0, %ymm0
; SDAG-SSE41-NEXT:    retq
;
; SDAG-AVX-LABEL: build_vector_v4f64:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vmovlhps {{.*#+}} xmm2 = xmm2[0],xmm3[0]
; SDAG-AVX-NEXT:    vmovlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; SDAG-AVX-NEXT:    vinsertf128 $1, %xmm2, %ymm0, %ymm0
; SDAG-AVX-NEXT:    retq
  %v0 = insertelement <4 x double> undef, double %a, i64 0
  %v1 = insertelement <4 x double> %v0, double %b, i64 1
  %v2 = insertelement <4 x double> %v1, double %c, i64 2
  %v3 = insertelement <4 x double> %v2, double %d, i64 3
  ret <4 x double> %v3
}

;512-bit integer vectors (require AVX512)

define <16 x i32> @build_vector_v16i32(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e, i32 %f, i32 %g, i32 %h,
; GISEL-SSE41-LABEL: build_vector_v16i32:
; GISEL-SSE41:       # %bb.0:
; GISEL-SSE41-NEXT:    vmovd %edi, %xmm0
; GISEL-SSE41-NEXT:    vinserti32x4 $0, %xmm0, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vpinsrd $1, %esi, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vpinsrd $2, %edx, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vpinsrd $3, %ecx, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $0, %r8d, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $1, %r9d, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $0, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $1, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $0, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $1, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    retq
;
; GISEL-AVX-LABEL: build_vector_v16i32:
; GISEL-AVX:       # %bb.0:
; GISEL-AVX-NEXT:    vmovd %edi, %xmm0
; GISEL-AVX-NEXT:    vinserti32x4 $0, %xmm0, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vpinsrd $1, %esi, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vpinsrd $2, %edx, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vpinsrd $3, %ecx, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $0, %r8d, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $1, %r9d, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $0, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $1, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $0, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $1, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    retq
;
; SDAG-SSE41-LABEL: build_vector_v16i32:
; SDAG-SSE41:       # %bb.0:
; SDAG-SSE41-NEXT:    vmovd %edi, %xmm0
; SDAG-SSE41-NEXT:    vpinsrd $1, %esi, %xmm0, %xmm0
; SDAG-SSE41-NEXT:    vpinsrd $2, %edx, %xmm0, %xmm0
; SDAG-SSE41-NEXT:    vpinsrd $3, %ecx, %xmm0, %xmm0
; SDAG-SSE41-NEXT:    vmovd %r8d, %xmm1
; SDAG-SSE41-NEXT:    vpinsrd $1, %r9d, %xmm1, %xmm1
; SDAG-SSE41-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; SDAG-SSE41-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; SDAG-SSE41-NEXT:    vinserti128 $1, %xmm1, %ymm0, %ymm0
; SDAG-SSE41-NEXT:    vmovd {{.*#+}} xmm1 = mem[0],zero,zero,zero
; SDAG-SSE41-NEXT:    vpinsrd $1, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; SDAG-SSE41-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; SDAG-SSE41-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; SDAG-SSE41-NEXT:    vmovd {{.*#+}} xmm2 = mem[0],zero,zero,zero
; SDAG-SSE41-NEXT:    vpinsrd $1, {{[0-9]+}}(%rsp), %xmm2, %xmm2
; SDAG-SSE41-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm2, %xmm2
; SDAG-SSE41-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm2, %xmm2
; SDAG-SSE41-NEXT:    vinserti128 $1, %xmm2, %ymm1, %ymm1
; SDAG-SSE41-NEXT:    vinserti64x4 $1, %ymm1, %zmm0, %zmm0
; SDAG-SSE41-NEXT:    retq
;
; SDAG-AVX-LABEL: build_vector_v16i32:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vmovd %edi, %xmm0
; SDAG-AVX-NEXT:    vpinsrd $1, %esi, %xmm0, %xmm0
; SDAG-AVX-NEXT:    vpinsrd $2, %edx, %xmm0, %xmm0
; SDAG-AVX-NEXT:    vpinsrd $3, %ecx, %xmm0, %xmm0
; SDAG-AVX-NEXT:    vmovd %r8d, %xmm1
; SDAG-AVX-NEXT:    vpinsrd $1, %r9d, %xmm1, %xmm1
; SDAG-AVX-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; SDAG-AVX-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; SDAG-AVX-NEXT:    vinserti128 $1, %xmm1, %ymm0, %ymm0
; SDAG-AVX-NEXT:    vmovd {{.*#+}} xmm1 = mem[0],zero,zero,zero
; SDAG-AVX-NEXT:    vpinsrd $1, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; SDAG-AVX-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; SDAG-AVX-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; SDAG-AVX-NEXT:    vmovd {{.*#+}} xmm2 = mem[0],zero,zero,zero
; SDAG-AVX-NEXT:    vpinsrd $1, {{[0-9]+}}(%rsp), %xmm2, %xmm2
; SDAG-AVX-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm2, %xmm2
; SDAG-AVX-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm2, %xmm2
; SDAG-AVX-NEXT:    vinserti128 $1, %xmm2, %ymm1, %ymm1
; SDAG-AVX-NEXT:    vinserti64x4 $1, %ymm1, %zmm0, %zmm0
; SDAG-AVX-NEXT:    retq
                                       i32 %i, i32 %j, i32 %k, i32 %l, i32 %m, i32 %n, i32 %o, i32 %p) #2 {
  %v0  = insertelement <16 x i32> undef, i32 %a, i64 0
  %v1  = insertelement <16 x i32> %v0,  i32 %b, i64 1
  %v2  = insertelement <16 x i32> %v1,  i32 %c, i64 2
  %v3  = insertelement <16 x i32> %v2,  i32 %d, i64 3
  %v4  = insertelement <16 x i32> %v3,  i32 %e, i64 4
  %v5  = insertelement <16 x i32> %v4,  i32 %f, i64 5
  %v6  = insertelement <16 x i32> %v5,  i32 %g, i64 6
  %v7  = insertelement <16 x i32> %v6,  i32 %h, i64 7
  %v8  = insertelement <16 x i32> %v7,  i32 %i, i64 8
  %v9  = insertelement <16 x i32> %v8,  i32 %j, i64 9
  %v10 = insertelement <16 x i32> %v9,  i32 %k, i64 10
  %v11 = insertelement <16 x i32> %v10, i32 %l, i64 11
  %v12 = insertelement <16 x i32> %v11, i32 %m, i64 12
  %v13 = insertelement <16 x i32> %v12, i32 %n, i64 13
  %v14 = insertelement <16 x i32> %v13, i32 %o, i64 14
  %v15 = insertelement <16 x i32> %v14, i32 %p, i64 15
  ret <16 x i32> %v15
}

define <8 x i64> @build_vector_v8i64(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i64 %f, i64 %g, i64 %h) #2 {
; GISEL-SSE41-LABEL: build_vector_v8i64:
; GISEL-SSE41:       # %bb.0:
; GISEL-SSE41-NEXT:    vmovq %rdi, %xmm0
; GISEL-SSE41-NEXT:    vinserti32x4 $0, %xmm0, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vpinsrq $1, %rsi, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrq $0, %rdx, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrq $1, %rcx, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrq $0, %r8, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrq $1, %r9, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrq $0, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrq $1, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    retq
;
; GISEL-AVX-LABEL: build_vector_v8i64:
; GISEL-AVX:       # %bb.0:
; GISEL-AVX-NEXT:    vmovq %rdi, %xmm0
; GISEL-AVX-NEXT:    vinserti32x4 $0, %xmm0, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vpinsrq $1, %rsi, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrq $0, %rdx, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrq $1, %rcx, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrq $0, %r8, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrq $1, %r9, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrq $0, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrq $1, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    retq
;
; SDAG-SSE41-LABEL: build_vector_v8i64:
; SDAG-SSE41:       # %bb.0:
; SDAG-SSE41-NEXT:    vmovq %rcx, %xmm0
; SDAG-SSE41-NEXT:    vmovq %rdx, %xmm1
; SDAG-SSE41-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; SDAG-SSE41-NEXT:    vmovq %rsi, %xmm1
; SDAG-SSE41-NEXT:    vmovq %rdi, %xmm2
; SDAG-SSE41-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm2[0],xmm1[0]
; SDAG-SSE41-NEXT:    vinserti128 $1, %xmm0, %ymm1, %ymm0
; SDAG-SSE41-NEXT:    vmovq %r9, %xmm1
; SDAG-SSE41-NEXT:    vmovq %r8, %xmm2
; SDAG-SSE41-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm2[0],xmm1[0]
; SDAG-SSE41-NEXT:    vinserti128 $1, {{[0-9]+}}(%rsp), %ymm1, %ymm1
; SDAG-SSE41-NEXT:    vinserti64x4 $1, %ymm1, %zmm0, %zmm0
; SDAG-SSE41-NEXT:    retq
;
; SDAG-AVX-LABEL: build_vector_v8i64:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vmovq %rcx, %xmm0
; SDAG-AVX-NEXT:    vmovq %rdx, %xmm1
; SDAG-AVX-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; SDAG-AVX-NEXT:    vmovq %rsi, %xmm1
; SDAG-AVX-NEXT:    vmovq %rdi, %xmm2
; SDAG-AVX-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm2[0],xmm1[0]
; SDAG-AVX-NEXT:    vinserti128 $1, %xmm0, %ymm1, %ymm0
; SDAG-AVX-NEXT:    vmovq %r9, %xmm1
; SDAG-AVX-NEXT:    vmovq %r8, %xmm2
; SDAG-AVX-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm2[0],xmm1[0]
; SDAG-AVX-NEXT:    vinserti128 $1, {{[0-9]+}}(%rsp), %ymm1, %ymm1
; SDAG-AVX-NEXT:    vinserti64x4 $1, %ymm1, %zmm0, %zmm0
; SDAG-AVX-NEXT:    retq
  %v0 = insertelement <8 x i64> undef, i64 %a, i64 0
  %v1 = insertelement <8 x i64> %v0, i64 %b, i64 1
  %v2 = insertelement <8 x i64> %v1, i64 %c, i64 2
  %v3 = insertelement <8 x i64> %v2, i64 %d, i64 3
  %v4 = insertelement <8 x i64> %v3, i64 %e, i64 4
  %v5 = insertelement <8 x i64> %v4, i64 %f, i64 5
  %v6 = insertelement <8 x i64> %v5, i64 %g, i64 6
  %v7 = insertelement <8 x i64> %v6, i64 %h, i64 7
  ret <8 x i64> %v7
}

;512-bit floating-point vectors (require AVX512)

define <16 x float> @build_vector_v16f32(float %a, float %b, float %c, float %d, float %e, float %f, float %g, float %h,
; GISEL-SSE41-LABEL: build_vector_v16f32:
; GISEL-SSE41:       # %bb.0:
; GISEL-SSE41-NEXT:    vmovd %xmm0, %eax
; GISEL-SSE41-NEXT:    vmovd %eax, %xmm0
; GISEL-SSE41-NEXT:    vinserti32x4 $0, %xmm0, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vmovd %xmm1, %eax
; GISEL-SSE41-NEXT:    vpinsrd $1, %eax, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vmovd %xmm2, %eax
; GISEL-SSE41-NEXT:    vpinsrd $2, %eax, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vmovd %xmm3, %eax
; GISEL-SSE41-NEXT:    vpinsrd $3, %eax, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vmovd %xmm4, %eax
; GISEL-SSE41-NEXT:    vpinsrd $0, %eax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vmovd %xmm5, %eax
; GISEL-SSE41-NEXT:    vpinsrd $1, %eax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vmovd %xmm6, %eax
; GISEL-SSE41-NEXT:    vpinsrd $2, %eax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vmovd %xmm7, %eax
; GISEL-SSE41-NEXT:    vpinsrd $3, %eax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $0, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $1, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $0, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $1, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    retq
;
; GISEL-AVX-LABEL: build_vector_v16f32:
; GISEL-AVX:       # %bb.0:
; GISEL-AVX-NEXT:    vmovd %xmm0, %eax
; GISEL-AVX-NEXT:    vmovd %eax, %xmm0
; GISEL-AVX-NEXT:    vinserti32x4 $0, %xmm0, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vmovd %xmm1, %eax
; GISEL-AVX-NEXT:    vpinsrd $1, %eax, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vmovd %xmm2, %eax
; GISEL-AVX-NEXT:    vpinsrd $2, %eax, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vmovd %xmm3, %eax
; GISEL-AVX-NEXT:    vpinsrd $3, %eax, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vmovd %xmm4, %eax
; GISEL-AVX-NEXT:    vpinsrd $0, %eax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vmovd %xmm5, %eax
; GISEL-AVX-NEXT:    vpinsrd $1, %eax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vmovd %xmm6, %eax
; GISEL-AVX-NEXT:    vpinsrd $2, %eax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vmovd %xmm7, %eax
; GISEL-AVX-NEXT:    vpinsrd $3, %eax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $0, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $1, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $0, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $1, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $2, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vpinsrd $3, {{[0-9]+}}(%rsp), %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    retq
;
; SDAG-SSE41-LABEL: build_vector_v16f32:
; SDAG-SSE41:       # %bb.0:
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm4 = xmm4[0],xmm5[0],xmm4[2,3]
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm4 = xmm4[0,1],xmm6[0],xmm4[3]
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm4 = xmm4[0,1,2],xmm7[0]
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm0 = xmm0[0],xmm1[0],xmm0[2,3]
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm0 = xmm0[0,1],xmm2[0],xmm0[3]
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm0 = xmm0[0,1,2],xmm3[0]
; SDAG-SSE41-NEXT:    vinsertf128 $1, %xmm4, %ymm0, %ymm0
; SDAG-SSE41-NEXT:    vmovss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm1 = xmm1[0],mem[0],xmm1[2,3]
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm1 = xmm1[0,1],mem[0],xmm1[3]
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm1 = xmm1[0,1,2],mem[0]
; SDAG-SSE41-NEXT:    vmovss {{.*#+}} xmm2 = mem[0],zero,zero,zero
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm2 = xmm2[0],mem[0],xmm2[2,3]
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm2 = xmm2[0,1],mem[0],xmm2[3]
; SDAG-SSE41-NEXT:    vinsertps {{.*#+}} xmm2 = xmm2[0,1,2],mem[0]
; SDAG-SSE41-NEXT:    vinsertf128 $1, %xmm2, %ymm1, %ymm1
; SDAG-SSE41-NEXT:    vinsertf64x4 $1, %ymm1, %zmm0, %zmm0
; SDAG-SSE41-NEXT:    retq
;
; SDAG-AVX-LABEL: build_vector_v16f32:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm4 = xmm4[0],xmm5[0],xmm4[2,3]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm4 = xmm4[0,1],xmm6[0],xmm4[3]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm4 = xmm4[0,1,2],xmm7[0]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm0 = xmm0[0],xmm1[0],xmm0[2,3]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm0 = xmm0[0,1],xmm2[0],xmm0[3]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm0 = xmm0[0,1,2],xmm3[0]
; SDAG-AVX-NEXT:    vinsertf128 $1, %xmm4, %ymm0, %ymm0
; SDAG-AVX-NEXT:    vmovss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm1 = xmm1[0],mem[0],xmm1[2,3]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm1 = xmm1[0,1],mem[0],xmm1[3]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm1 = xmm1[0,1,2],mem[0]
; SDAG-AVX-NEXT:    vmovss {{.*#+}} xmm2 = mem[0],zero,zero,zero
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm2 = xmm2[0],mem[0],xmm2[2,3]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm2 = xmm2[0,1],mem[0],xmm2[3]
; SDAG-AVX-NEXT:    vinsertps {{.*#+}} xmm2 = xmm2[0,1,2],mem[0]
; SDAG-AVX-NEXT:    vinsertf128 $1, %xmm2, %ymm1, %ymm1
; SDAG-AVX-NEXT:    vinsertf64x4 $1, %ymm1, %zmm0, %zmm0
; SDAG-AVX-NEXT:    retq
                                         float %i, float %j, float %k, float %l, float %m, float %n, float %o, float %p) #2 {
  %v0  = insertelement <16 x float> undef, float %a, i64 0
  %v1  = insertelement <16 x float> %v0,  float %b, i64 1
  %v2  = insertelement <16 x float> %v1,  float %c, i64 2
  %v3  = insertelement <16 x float> %v2,  float %d, i64 3
  %v4  = insertelement <16 x float> %v3,  float %e, i64 4
  %v5  = insertelement <16 x float> %v4,  float %f, i64 5
  %v6  = insertelement <16 x float> %v5,  float %g, i64 6
  %v7  = insertelement <16 x float> %v6,  float %h, i64 7
  %v8  = insertelement <16 x float> %v7,  float %i, i64 8
  %v9  = insertelement <16 x float> %v8,  float %j, i64 9
  %v10 = insertelement <16 x float> %v9,  float %k, i64 10
  %v11 = insertelement <16 x float> %v10, float %l, i64 11
  %v12 = insertelement <16 x float> %v11, float %m, i64 12
  %v13 = insertelement <16 x float> %v12, float %n, i64 13
  %v14 = insertelement <16 x float> %v13, float %o, i64 14
  %v15 = insertelement <16 x float> %v14, float %p, i64 15
  ret <16 x float> %v15
}

define <8 x double> @build_vector_v8f64(double %a, double %b, double %c, double %d, double %e, double %f, double %g, double %h) #2 {
; GISEL-SSE41-LABEL: build_vector_v8f64:
; GISEL-SSE41:       # %bb.0:
; GISEL-SSE41-NEXT:    vmovq %xmm0, %rax
; GISEL-SSE41-NEXT:    vmovq %rax, %xmm0
; GISEL-SSE41-NEXT:    vinserti32x4 $0, %xmm0, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vmovq %xmm1, %rax
; GISEL-SSE41-NEXT:    vpinsrq $1, %rax, %xmm0, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vmovq %xmm2, %rax
; GISEL-SSE41-NEXT:    vpinsrq $0, %rax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vmovq %xmm3, %rax
; GISEL-SSE41-NEXT:    vpinsrq $1, %rax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vmovq %xmm4, %rax
; GISEL-SSE41-NEXT:    vpinsrq $0, %rax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vmovq %xmm5, %rax
; GISEL-SSE41-NEXT:    vpinsrq $1, %rax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vmovq %xmm6, %rax
; GISEL-SSE41-NEXT:    vpinsrq $0, %rax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-SSE41-NEXT:    vmovq %xmm7, %rax
; GISEL-SSE41-NEXT:    vpinsrq $1, %rax, %xmm1, %xmm1
; GISEL-SSE41-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-SSE41-NEXT:    retq
;
; GISEL-AVX-LABEL: build_vector_v8f64:
; GISEL-AVX:       # %bb.0:
; GISEL-AVX-NEXT:    vmovq %xmm0, %rax
; GISEL-AVX-NEXT:    vmovq %rax, %xmm0
; GISEL-AVX-NEXT:    vinserti32x4 $0, %xmm0, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vmovq %xmm1, %rax
; GISEL-AVX-NEXT:    vpinsrq $1, %rax, %xmm0, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $0, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vmovq %xmm2, %rax
; GISEL-AVX-NEXT:    vpinsrq $0, %rax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $1, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vmovq %xmm3, %rax
; GISEL-AVX-NEXT:    vpinsrq $1, %rax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $1, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vmovq %xmm4, %rax
; GISEL-AVX-NEXT:    vpinsrq $0, %rax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $2, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vmovq %xmm5, %rax
; GISEL-AVX-NEXT:    vpinsrq $1, %rax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $2, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vmovq %xmm6, %rax
; GISEL-AVX-NEXT:    vpinsrq $0, %rax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; GISEL-AVX-NEXT:    vmovq %xmm7, %rax
; GISEL-AVX-NEXT:    vpinsrq $1, %rax, %xmm1, %xmm1
; GISEL-AVX-NEXT:    vinserti32x4 $3, %xmm1, %zmm0, %zmm0
; GISEL-AVX-NEXT:    retq
;
; SDAG-SSE41-LABEL: build_vector_v8f64:
; SDAG-SSE41:       # %bb.0:
; SDAG-SSE41-NEXT:    vmovlhps {{.*#+}} xmm6 = xmm6[0],xmm7[0]
; SDAG-SSE41-NEXT:    vmovlhps {{.*#+}} xmm4 = xmm4[0],xmm5[0]
; SDAG-SSE41-NEXT:    vinsertf128 $1, %xmm6, %ymm4, %ymm4
; SDAG-SSE41-NEXT:    vmovlhps {{.*#+}} xmm2 = xmm2[0],xmm3[0]
; SDAG-SSE41-NEXT:    vmovlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; SDAG-SSE41-NEXT:    vinsertf128 $1, %xmm2, %ymm0, %ymm0
; SDAG-SSE41-NEXT:    vinsertf64x4 $1, %ymm4, %zmm0, %zmm0
; SDAG-SSE41-NEXT:    retq
;
; SDAG-AVX-LABEL: build_vector_v8f64:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vmovlhps {{.*#+}} xmm6 = xmm6[0],xmm7[0]
; SDAG-AVX-NEXT:    vmovlhps {{.*#+}} xmm4 = xmm4[0],xmm5[0]
; SDAG-AVX-NEXT:    vinsertf128 $1, %xmm6, %ymm4, %ymm4
; SDAG-AVX-NEXT:    vmovlhps {{.*#+}} xmm2 = xmm2[0],xmm3[0]
; SDAG-AVX-NEXT:    vmovlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; SDAG-AVX-NEXT:    vinsertf128 $1, %xmm2, %ymm0, %ymm0
; SDAG-AVX-NEXT:    vinsertf64x4 $1, %ymm4, %zmm0, %zmm0
; SDAG-AVX-NEXT:    retq
  %v0 = insertelement <8 x double> undef, double %a, i64 0
  %v1 = insertelement <8 x double> %v0, double %b, i64 1
  %v2 = insertelement <8 x double> %v1, double %c, i64 2
  %v3 = insertelement <8 x double> %v2, double %d, i64 3
  %v4 = insertelement <8 x double> %v3, double %e, i64 4
  %v5 = insertelement <8 x double> %v4, double %f, i64 5
  %v6 = insertelement <8 x double> %v5, double %g, i64 6
  %v7 = insertelement <8 x double> %v6, double %h, i64 7
  ret <8 x double> %v7
}

attributes #1 = { "target-features"="+avx" }
attributes #2 = { "target-features"="+avx512f,+avx512bw,+avx512dq" }
