; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -mtriple=x86_64-linux-gnu -o - -global-isel %s -stop-after=irtranslator | FileCheck %s

define <4 x i1> @foo_undef() {
  ; CHECK-LABEL: name: foo_undef
  ; CHECK: bb.1.entry:
  ; CHECK:   [[DEF:%[0-9]+]]:_(<4 x s1>) = G_IMPLICIT_DEF
  ; CHECK:   [[ANYEXT:%[0-9]+]]:_(<4 x s32>) = G_ANYEXT [[DEF]](<4 x s1>)
  ; CHECK:   $xmm0 = COPY [[ANYEXT]](<4 x s32>)
  ; CHECK:   RET 0, implicit $xmm0
entry:
  ret <4 x i1> undef ;
}

define <4 x i1> @foo_poison() {
  ; CHECK-LABEL: name: foo_poison
  ; CHECK: bb.1.entry:
  ; CHECK:   [[DEF:%[0-9]+]]:_(<4 x s1>) = G_POISON
  ; CHECK:   [[ANYEXT:%[0-9]+]]:_(<4 x s32>) = G_ANYEXT [[DEF]](<4 x s1>)
  ; CHECK:   $xmm0 = COPY [[ANYEXT]](<4 x s32>)
  ; CHECK:   RET 0, implicit $xmm0
entry:
  ret <4 x i1> poison ;
}
