; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -mtriple=i686-pc-win32 -global-isel -stop-after=irtranslator -verify-machineinstrs %s -o - | FileCheck %s

; inalloca and preallocated formal arguments used to crash CallLowering with
; an isByVal() assertion in setByValSize; check they translate instead.

define void @inalloca_arg(ptr inalloca(i32) %p) {
  ; CHECK-LABEL: name: inalloca_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY [[FRAME_INDEX]](p0)
  ; CHECK-NEXT:   RET 0
  ret void
}

define void @preallocated_arg(ptr preallocated(i32) %p) {
  ; CHECK-LABEL: name: preallocated_arg
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY [[FRAME_INDEX]](p0)
  ; CHECK-NEXT:   RET 0
  ret void
}
