# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=i686-linux-gnu -run-pass=regbankselect,instruction-select %s -o -  | FileCheck %s --check-prefixes GISEL-I686

---
name:            fneg_f64
alignment:       16
legalized:       true
fixedStack:
  - { id: 0, type: default, offset: 0, size: 8, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.1:
    ; GISEL-I686-LABEL: name: fneg_f64
    ; GISEL-I686: [[DEF:%[0-9]+]]:rfp64 = IMPLICIT_DEF
    ; GISEL-I686-NEXT: [[CHS_Fp64_:%[0-9]+]]:rfp64 = CHS_Fp64 [[DEF]], implicit-def dead $fpsw
    ; GISEL-I686-NEXT: $fp0 = COPY [[CHS_Fp64_]]
    ; GISEL-I686-NEXT: RET 0, implicit $fp0
    %1:_(p0) = G_FRAME_INDEX %fixed-stack.0
    %0:_(s64) = IMPLICIT_DEF
    %2:_(s64) = G_FNEG %0
    $fp0 = COPY %2(s64)
    RET 0, implicit $fp0
...
---
name:            fneg_f32
alignment:       16
legalized:       true
fixedStack:
  - { id: 0, type: default, offset: 0, size: 4, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.1:
    ; GISEL-I686-LABEL: name: fneg_f32
    ; GISEL-I686: [[LD_Fp32m:%[0-9]+]]:rfp32 = nofpexcept LD_Fp32m %fixed-stack.0, 1, $noreg, 0, $noreg, implicit-def dead $fpsw, implicit $fpcw :: (invariant load (s32) from %fixed-stack.0, align 16)
    ; GISEL-I686-NEXT: [[CHS_Fp32_:%[0-9]+]]:rfp32 = CHS_Fp32 [[LD_Fp32m]], implicit-def dead $fpsw
    ; GISEL-I686-NEXT: $fp0 = COPY [[CHS_Fp32_]]
    ; GISEL-I686-NEXT: RET 0, implicit $fp0
    %1:_(p0) = G_FRAME_INDEX %fixed-stack.0
    %0:_(s32) = G_LOAD %1(p0) :: (invariant load (s32) from %fixed-stack.0, align 16)
    %2:_(s32) = G_FNEG %0
    $fp0 = COPY %2(s32)
    RET 0, implicit $fp0
...
---
name:            fneg_f64_mem
alignment:       16
legalized:       true
fixedStack:
  - { id: 0, type: default, offset: 4, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 1, type: default, offset: 0, size: 4, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.1:
    ; GISEL-I686-LABEL: name: fneg_f64_mem
    ; GISEL-I686: [[DEF:%[0-9]+]]:rfp64 = IMPLICIT_DEF
    ; GISEL-I686-NEXT: [[CHS_Fp64_:%[0-9]+]]:rfp64 = CHS_Fp64 [[DEF]], implicit-def dead $fpsw
    ; GISEL-I686-NEXT: $fp0 = COPY [[CHS_Fp64_]]
    ; GISEL-I686-NEXT: RET 0, implicit $fp0
    %1:_(p0) = G_FRAME_INDEX %fixed-stack.1
    %0:_(s64) = IMPLICIT_DEF
    %2:_(s64) = G_FNEG %0
    $fp0 = COPY %2(s64)
    RET 0, implicit $fp0
...
---
name:            fneg_f32_mem
alignment:       16
legalized:       true
fixedStack:
  - { id: 0, type: default, offset: 4, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 1, type: default, offset: 0, size: 4, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.1:
    ; GISEL-I686-LABEL: name: fneg_f32_mem
    ; GISEL-I686: [[LD_Fp32m:%[0-9]+]]:rfp32 = nofpexcept LD_Fp32m %fixed-stack.1, 1, $noreg, 0, $noreg, implicit-def dead $fpsw, implicit $fpcw :: (invariant load (p0) from %fixed-stack.1)
    ; GISEL-I686-NEXT: [[CHS_Fp32_:%[0-9]+]]:rfp32 = CHS_Fp32 [[LD_Fp32m]], implicit-def dead $fpsw
    ; GISEL-I686-NEXT: $fp0 = COPY [[CHS_Fp32_]]
    ; GISEL-I686-NEXT: RET 0, implicit $fp0
    %2:_(p0) = G_FRAME_INDEX %fixed-stack.1
    %0:_(p0) = G_LOAD %2(p0) :: (invariant load (p0) from %fixed-stack.1, align 16)
    %3:_(p0) = G_FRAME_INDEX %fixed-stack.0
    %1:_(s32) = G_LOAD %3(p0) :: (invariant load (p0) from %fixed-stack.0)
    %4:_(s32) = G_FNEG %1
    $fp0 = COPY %4(s32)
    RET 0, implicit $fp0
...
---
name:            test_fp80
alignment:       16
legalized:       true
fixedStack:
  - { id: 0, type: default, offset: 0, size: 10, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.1:
    ; GISEL-I686-LABEL: name: test_fp80
    ; GISEL-I686: [[LD_Fp80m:%[0-9]+]]:rfp80 = nofpexcept LD_Fp80m %fixed-stack.0, 1, $noreg, 0, $noreg, implicit-def dead $fpsw, implicit $fpcw :: (invariant load (s80) from %fixed-stack.0, align 16)
    ; GISEL-I686-NEXT: [[CHS_Fp80_:%[0-9]+]]:rfp80 = CHS_Fp80 [[LD_Fp80m]], implicit-def dead $fpsw
    ; GISEL-I686-NEXT: $fp0 = COPY [[CHS_Fp80_]]
    ; GISEL-I686-NEXT: RET 0, implicit $fp0
    %1:_(p0) = G_FRAME_INDEX %fixed-stack.0
    %0:_(s80) = G_LOAD %1(p0) :: (invariant load (s80) from %fixed-stack.0, align 16)
    %2:_(s80) = G_FNEG %0
    $fp0 = COPY %2(s80)
    RET 0, implicit $fp0
...
