# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# RUN: llc -mtriple=x86_64-linux-gnu -run-pass=legalizer %s -o - | FileCheck %s --check-prefix=X64
# RUN: llc -mtriple=i386-linux-gnu   -run-pass=legalizer %s -o - | FileCheck %s --check-prefix=X32

---
name:            test_block_address
alignment:       16
legalized:       false
jumpTable:
  kind:            block-address
  entries:
    - id:              0
      blocks:          [ '%bb.2', '%bb.3', ]
body:             |
  ; X64-LABEL: name: test_block_address
  ; X64: bb.0.entry:
  ; X64-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; X64-NEXT:   liveins: $edi
  ; X64-NEXT: {{  $}}
  ; X64-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $edi
  ; X64-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
  ; X64-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; X64-NEXT:   [[SUB:%[0-9]+]]:_(s32) = G_SUB [[COPY]], [[C1]]
  ; X64-NEXT:   [[ICMP:%[0-9]+]]:_(s8) = G_ICMP intpred(ugt), [[SUB]](s32), [[C]]
  ; X64-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[ICMP]](s8)
  ; X64-NEXT:   G_BRCOND [[TRUNC]](s1), %bb.4
  ; X64-NEXT: {{  $}}
  ; X64-NEXT: bb.1.entry:
  ; X64-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; X64-NEXT: {{  $}}
  ; X64-NEXT:   [[JUMP_TABLE:%[0-9]+]]:_(p0) = G_JUMP_TABLE %jump-table.0
  ; X64-NEXT:   [[C2:%[0-9]+]]:_(s8) = G_CONSTANT i8 3
  ; X64-NEXT:   [[SHL:%[0-9]+]]:_(s32) = G_SHL [[SUB]], [[C2]](s8)
  ; X64-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[JUMP_TABLE]], [[SHL]](s32)
  ; X64-NEXT:   [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[PTR_ADD]](p0) :: (load (s64) from jump-table)
  ; X64-NEXT:   G_BRINDIRECT [[LOAD]](p0)
  ; X64-NEXT: {{  $}}
  ; X64-NEXT: bb.2:
  ; X64-NEXT:   successors: %bb.5(0x80000000)
  ; X64-NEXT: {{  $}}
  ; X64-NEXT:   G_BR %bb.5
  ; X64-NEXT: {{  $}}
  ; X64-NEXT: bb.3:
  ; X64-NEXT:   successors: %bb.5(0x80000000)
  ; X64-NEXT: {{  $}}
  ; X64-NEXT:   G_BR %bb.5
  ; X64-NEXT: {{  $}}
  ; X64-NEXT: bb.4:
  ; X64-NEXT:   successors: %bb.5(0x80000000)
  ; X64-NEXT: {{  $}}
  ; X64-NEXT: bb.5:
  ; X64-NEXT:   $eax = COPY [[COPY]](s32)
  ; X64-NEXT:   RET 0, implicit $eax
  ;
  ; X32-LABEL: name: test_block_address
  ; X32: bb.0.entry:
  ; X32-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; X32-NEXT:   liveins: $edi
  ; X32-NEXT: {{  $}}
  ; X32-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $edi
  ; X32-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
  ; X32-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; X32-NEXT:   [[SUB:%[0-9]+]]:_(s32) = G_SUB [[COPY]], [[C1]]
  ; X32-NEXT:   [[ICMP:%[0-9]+]]:_(s8) = G_ICMP intpred(ugt), [[SUB]](s32), [[C]]
  ; X32-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[ICMP]](s8)
  ; X32-NEXT:   G_BRCOND [[TRUNC]](s1), %bb.4
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.1.entry:
  ; X32-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; X32-NEXT: {{  $}}
  ; X32-NEXT:   [[JUMP_TABLE:%[0-9]+]]:_(p0) = G_JUMP_TABLE %jump-table.0
  ; X32-NEXT:   [[C2:%[0-9]+]]:_(s8) = G_CONSTANT i8 2
  ; X32-NEXT:   [[SHL:%[0-9]+]]:_(s32) = G_SHL [[SUB]], [[C2]](s8)
  ; X32-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[JUMP_TABLE]], [[SHL]](s32)
  ; X32-NEXT:   [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from jump-table)
  ; X32-NEXT:   G_BRINDIRECT [[LOAD]](p0)
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.2:
  ; X32-NEXT:   successors: %bb.5(0x80000000)
  ; X32-NEXT: {{  $}}
  ; X32-NEXT:   G_BR %bb.5
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.3:
  ; X32-NEXT:   successors: %bb.5(0x80000000)
  ; X32-NEXT: {{  $}}
  ; X32-NEXT:   G_BR %bb.5
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.4:
  ; X32-NEXT:   successors: %bb.5(0x80000000)
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.5:
  ; X32-NEXT:   $eax = COPY [[COPY]](s32)
  ; X32-NEXT:   RET 0, implicit $eax
  bb.0.entry:
    successors: %bb.1(0x40000000), %bb.4(0x40000000)
    liveins: $edi

    %0:_(s32) = COPY $edi
    %4:_(s32) = G_CONSTANT i32 4
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s32) = G_SUB %0, %1
    %5:_(s1) = G_ICMP intpred(ugt), %2(s32), %4
    G_BRCOND %5(s1), %bb.4

  bb.1.entry:
    successors: %bb.2(0x1999999a), %bb.3(0x1999999a)

    %6:_(p0) = G_JUMP_TABLE %jump-table.0
    G_BRJT %6(p0), %jump-table.0, %2(s32)

  bb.2:
    successors: %bb.5(0x80000000)

    G_BR %bb.5

  bb.3:
    successors: %bb.5(0x80000000)

    G_BR %bb.5

  bb.4:
    successors: %bb.5(0x80000000)

  bb.5:
    $eax = COPY %0(s32)
    RET 0, implicit $eax

...

---
name:            test_label_diff32
alignment:       16
legalized:       false
jumpTable:
  kind:            label-difference32
  entries:
    - id:              0
      blocks:          [ '%bb.2', '%bb.3', ]
body:             |
  ; X64-LABEL: name: test_label_diff32
  ; X64: bb.0.entry:
  ; X64-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; X64-NEXT:   liveins: $edi
  ; X64-NEXT: {{  $}}
  ; X64-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $edi
  ; X64-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
  ; X64-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; X64-NEXT:   [[SUB:%[0-9]+]]:_(s32) = G_SUB [[COPY]], [[C1]]
  ; X64-NEXT:   [[ICMP:%[0-9]+]]:_(s8) = G_ICMP intpred(ugt), [[SUB]](s32), [[C]]
  ; X64-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[ICMP]](s8)
  ; X64-NEXT:   G_BRCOND [[TRUNC]](s1), %bb.4
  ; X64-NEXT: {{  $}}
  ; X64-NEXT: bb.1.entry:
  ; X64-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; X64-NEXT: {{  $}}
  ; X64-NEXT:   [[JUMP_TABLE:%[0-9]+]]:_(p0) = G_JUMP_TABLE %jump-table.0
  ; X64-NEXT:   [[C2:%[0-9]+]]:_(s8) = G_CONSTANT i8 3
  ; X64-NEXT:   [[SHL:%[0-9]+]]:_(s32) = G_SHL [[SUB]], [[C2]](s8)
  ; X64-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[JUMP_TABLE]], [[SHL]](s32)
  ; X64-NEXT:   [[LOAD:%[0-9]+]]:_(s64) = G_LOAD [[PTR_ADD]](p0) :: (load (s64) from jump-table, align 4)
  ; X64-NEXT:   [[TRUNC1:%[0-9]+]]:_(s32) = G_TRUNC [[LOAD]](s64)
  ; X64-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[JUMP_TABLE]], [[TRUNC1]](s32)
  ; X64-NEXT:   G_BRINDIRECT [[PTR_ADD1]](p0)
  ; X64-NEXT: {{  $}}
  ; X64-NEXT: bb.2:
  ; X64-NEXT:   successors: %bb.5(0x80000000)
  ; X64-NEXT: {{  $}}
  ; X64-NEXT:   G_BR %bb.5
  ; X64-NEXT: {{  $}}
  ; X64-NEXT: bb.3:
  ; X64-NEXT:   successors: %bb.5(0x80000000)
  ; X64-NEXT: {{  $}}
  ; X64-NEXT:   G_BR %bb.5
  ; X64-NEXT: {{  $}}
  ; X64-NEXT: bb.4:
  ; X64-NEXT:   successors: %bb.5(0x80000000)
  ; X64-NEXT: {{  $}}
  ; X64-NEXT: bb.5:
  ; X64-NEXT:   $eax = COPY [[COPY]](s32)
  ; X64-NEXT:   RET 0, implicit $eax
  ;
  ; X32-LABEL: name: test_label_diff32
  ; X32: bb.0.entry:
  ; X32-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; X32-NEXT:   liveins: $edi
  ; X32-NEXT: {{  $}}
  ; X32-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $edi
  ; X32-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
  ; X32-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; X32-NEXT:   [[SUB:%[0-9]+]]:_(s32) = G_SUB [[COPY]], [[C1]]
  ; X32-NEXT:   [[ICMP:%[0-9]+]]:_(s8) = G_ICMP intpred(ugt), [[SUB]](s32), [[C]]
  ; X32-NEXT:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[ICMP]](s8)
  ; X32-NEXT:   G_BRCOND [[TRUNC]](s1), %bb.4
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.1.entry:
  ; X32-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; X32-NEXT: {{  $}}
  ; X32-NEXT:   [[JUMP_TABLE:%[0-9]+]]:_(p0) = G_JUMP_TABLE %jump-table.0
  ; X32-NEXT:   [[C2:%[0-9]+]]:_(s8) = G_CONSTANT i8 2
  ; X32-NEXT:   [[SHL:%[0-9]+]]:_(s32) = G_SHL [[SUB]], [[C2]](s8)
  ; X32-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[JUMP_TABLE]], [[SHL]](s32)
  ; X32-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (load (s32) from jump-table)
  ; X32-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY [[LOAD]](s32)
  ; X32-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[JUMP_TABLE]], [[COPY1]](s32)
  ; X32-NEXT:   G_BRINDIRECT [[PTR_ADD1]](p0)
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.2:
  ; X32-NEXT:   successors: %bb.5(0x80000000)
  ; X32-NEXT: {{  $}}
  ; X32-NEXT:   G_BR %bb.5
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.3:
  ; X32-NEXT:   successors: %bb.5(0x80000000)
  ; X32-NEXT: {{  $}}
  ; X32-NEXT:   G_BR %bb.5
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.4:
  ; X32-NEXT:   successors: %bb.5(0x80000000)
  ; X32-NEXT: {{  $}}
  ; X32-NEXT: bb.5:
  ; X32-NEXT:   $eax = COPY [[COPY]](s32)
  ; X32-NEXT:   RET 0, implicit $eax
  bb.0.entry:
    successors: %bb.1(0x40000000), %bb.4(0x40000000)
    liveins: $edi

    %0:_(s32) = COPY $edi
    %4:_(s32) = G_CONSTANT i32 4
    %1:_(s32) = G_CONSTANT i32 0
    %2:_(s32) = G_SUB %0, %1
    %5:_(s1) = G_ICMP intpred(ugt), %2(s32), %4
    G_BRCOND %5(s1), %bb.4

  bb.1.entry:
    successors: %bb.2(0x1999999a), %bb.3(0x1999999a)

    %6:_(p0) = G_JUMP_TABLE %jump-table.0
    G_BRJT %6(p0), %jump-table.0, %2(s32)

  bb.2:
    successors: %bb.5(0x80000000)

    G_BR %bb.5

  bb.3:
    successors: %bb.5(0x80000000)

    G_BR %bb.5

  bb.4:
    successors: %bb.5(0x80000000)

  bb.5:
    $eax = COPY %0(s32)
    RET 0, implicit $eax

...
