# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=x86_64-linux-gnu -run-pass=legalizer %s -o - | FileCheck %s --check-prefixes=X64

--- |
  define void @test_gep_i64c(ptr %addr) {
    %arrayidx = getelementptr i32, ptr undef, i64 5
    ret void
  }
  define void @test_gep_i64(ptr %addr, i64 %ofs) {
    %arrayidx = getelementptr i32, ptr undef, i64 %ofs
    ret void
  }
...
---
name:            test_gep_i64c
legalized:       false
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
body:             |
  bb.1 (%ir-block.0):
    ; X64-LABEL: name: test_gep_i64c
    ; X64: [[DEF:%[0-9]+]]:_(p0) = IMPLICIT_DEF
    ; X64-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 20
    ; X64-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[DEF]], [[C]](s64)
    ; X64-NEXT: G_STORE [[PTR_ADD]](p0), [[DEF]](p0) :: (store (p0) into %ir.addr)
    ; X64-NEXT: RET 0
    %0(p0) = IMPLICIT_DEF
    %1(s64) = G_CONSTANT i64 20
    %2(p0) = G_PTR_ADD %0, %1(s64)
    G_STORE %2, %0 :: (store (p0) into %ir.addr)
    RET 0
...
---
name:            test_gep_i64
legalized:       false
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
body:             |
  bb.1 (%ir-block.0):
    ; X64-LABEL: name: test_gep_i64
    ; X64: [[DEF:%[0-9]+]]:_(p0) = IMPLICIT_DEF
    ; X64-NEXT: [[DEF1:%[0-9]+]]:_(s64) = IMPLICIT_DEF
    ; X64-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[DEF]], [[DEF1]](s64)
    ; X64-NEXT: G_STORE [[PTR_ADD]](p0), [[DEF]](p0) :: (store (p0) into %ir.addr)
    ; X64-NEXT: RET 0
    %0(p0) = IMPLICIT_DEF
    %1(s64) = IMPLICIT_DEF
    %2(p0) = G_PTR_ADD %0, %1(s64)
    G_STORE %2, %0 :: (store (p0) into %ir.addr)
    RET 0
...
