# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# RUN: split-file %s %t
# RUN: llc -mtriple=x86_64-linux-gnu -run-pass=legalizer %t/x64.mir -o - | FileCheck %t/x64.mir
# RUN: llc -mtriple=i386-linux-gnu   -run-pass=legalizer %t/x32.mir -o - | FileCheck %t/x32.mir

#--- x64.mir
---
name:            test64
alignment:       16
legalized:       false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
body:             |
  bb.1.entry:
    successors:
    liveins: $rdi

    ; CHECK-LABEL: name: test64
    ; CHECK: liveins: $rdi
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $rdi
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[COPY]](s64)
    ; CHECK-NEXT: G_BRINDIRECT [[INTTOPTR]](p0)
    %0(s64) = COPY $rdi
    %1(p0) = G_INTTOPTR %0(s64)
    G_BRINDIRECT %1(p0)

...

#--- x32.mir
---
name:            test32
alignment:       16
legalized:       false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
body:             |
  bb.1.entry:
    successors:
    liveins: $edi

    ; CHECK-LABEL: name: test32
    ; CHECK: liveins: $edi
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $edi
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[COPY]](s32)
    ; CHECK-NEXT: G_BRINDIRECT [[INTTOPTR]](p0)
    %0(s32) = COPY $edi
    %1(p0) = G_INTTOPTR %0(s32)
    G_BRINDIRECT %1(p0)

...

