# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple x86_64 -run-pass=x86-prelegalizer-combiner %s -o - | FileCheck %s

---
name:            right_ident_sub
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $eax
    ; Fold (x - 0) -> x
    ; CHECK-LABEL: name: right_ident_sub
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $eax
    ; CHECK-NEXT: $eax = COPY %x(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 0
    %op:_(s32) = G_SUB %x(s32), %cst
    $eax = COPY %op(s32)
    RET implicit $eax

...
---
name:            right_ident_add
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eax
    ; Fold (x + 0) -> x
    ; CHECK-LABEL: name: right_ident_add
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $eax
    ; CHECK-NEXT: $eax = COPY %x(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 0
    %op:_(s32) = G_ADD %x(s32), %cst
    $eax = COPY %op(s32)
    RET implicit $eax
...
---
name:            mul_0
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eax
    ; Fold (x * 0) -> 0
    ; CHECK-LABEL: name: mul_0
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %cst:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: $eax = COPY %cst(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 0
    %op:_(s32) = G_MUL %x(s32), %cst
    $eax = COPY %op(s32)
    RET implicit $eax
...
---
name:            mul_0_cant_replace
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eax
    ; Fold (x * 0) -> 0
    ; CHECK-LABEL: name: mul_0_cant_replace
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $eax
    ; CHECK-NEXT: %cst:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: %op:gpr(s32) = G_MUL %x, %cst
    ; CHECK-NEXT: $eax = COPY %op(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 0
    %op:gpr(s32) = G_MUL %x(s32), %cst
    $eax = COPY %op(s32)
    RET implicit $eax
...
---
name:            sdiv_0
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eax
    ; Fold (0 / x) -> 0
    ; CHECK-LABEL: name: sdiv_0
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %cst:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: $eax = COPY %cst(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 0
    %op:_(s32) = G_SDIV %cst, %x
    $eax = COPY %op(s32)
    RET implicit $eax
...
---
name:            udiv_0
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eax
    ; Fold (0 / x) -> 0
    ; CHECK-LABEL: name: udiv_0
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %cst:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: $eax = COPY %cst(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 0
    %op:_(s32) = G_UDIV %cst, %x
    $eax = COPY %op(s32)
    RET implicit $eax
...
---
name:            srem_0
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eax
    ; Fold (0 % x) -> 0
    ; CHECK-LABEL: name: srem_0
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %cst:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: $eax = COPY %cst(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 0
    %op:_(s32) = G_SREM %cst, %x
    $eax = COPY %op(s32)
    RET implicit $eax
...

---
name:            urem_0
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eax
    ; Fold (0 % x) -> 0
    ; CHECK-LABEL: name: urem_0
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %cst:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: $eax = COPY %cst(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 0
    %op:_(s32) = G_UREM %cst, %x
    $eax = COPY %op(s32)
    RET implicit $eax
...
---
name:            right_ident_or
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eax
    ; Fold (x || 0) -> x
    ; CHECK-LABEL: name: right_ident_or
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $eax
    ; CHECK-NEXT: $eax = COPY %x(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 0
    %op:_(s32) = G_OR %x(s32), %cst
    $eax = COPY %op(s32)
    RET implicit $eax
...

---
name:            right_ident_xor
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eax
    ; Fold (x | 0) -> x
    ; CHECK-LABEL: name: right_ident_xor
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $eax
    ; CHECK-NEXT: $eax = COPY %x(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 0
    %op:_(s32) = G_XOR %x(s32), %cst
    $eax = COPY %op(s32)
    RET implicit $eax
...
---
name:            right_ident_shl
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eax
    ; Fold (x << 0) -> x
    ; CHECK-LABEL: name: right_ident_shl
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $eax
    ; CHECK-NEXT: $eax = COPY %x(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 0
    %op:_(s32) = G_SHL %x(s32), %cst
    $eax = COPY %op(s32)
    RET implicit $eax
...
---
name:            right_ident_ashr
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eax
    ; Fold (x ashr 0) -> x
    ; CHECK-LABEL: name: right_ident_ashr
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $eax
    ; CHECK-NEXT: $eax = COPY %x(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 0
    %op:_(s32) = G_ASHR %x(s32), %cst
    $eax = COPY %op(s32)
    RET implicit $eax
...
---
name:            right_ident_lshr
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eax
    ; Fold (x lshr 0) -> x
    ; CHECK-LABEL: name: right_ident_lshr
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $eax
    ; CHECK-NEXT: $eax = COPY %x(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 0
    %op:_(s32) = G_LSHR %x(s32), %cst
    $eax = COPY %op(s32)
    RET implicit $eax
...
---
name:            dont_fold_sub
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eax
    ; Not an identity, no folding.
    ; CHECK-LABEL: name: dont_fold_sub
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $eax
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: %op:_(s32) = G_ADD %x, [[C]]
    ; CHECK-NEXT: $eax = COPY %op(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 1
    %op:_(s32) = G_SUB %x(s32), %cst
    $eax = COPY %op(s32)
    RET implicit $eax
...
---
name:            look_through_zext
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $rax
    ; CHECK-LABEL: name: look_through_zext
    ; CHECK: liveins: $rax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %zero:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: %zext_zero:_(s64) = G_ZEXT %zero(s8)
    ; CHECK-NEXT: $rax = COPY %zext_zero(s64)
    ; CHECK-NEXT: RET implicit $rax
    %zero:_(s8) = G_CONSTANT i8 0
    %zext_zero:_(s64) = G_ZEXT %zero(s8)
    %c:_(s64) = G_CONSTANT i64 72340172838076673
    %mul:_(s64) = G_MUL %c, %zext_zero
    $rax = COPY %mul(s64)
    RET implicit $rax
...
---
name:            right_ident_ptr_add
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $rax
    ; Fold (x + 0) -> x
    ; CHECK-LABEL: name: right_ident_ptr_add
    ; CHECK: liveins: $rax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(p0) = COPY $rax
    ; CHECK-NEXT: $rax = COPY %x(p0)
    ; CHECK-NEXT: RET implicit $rax
    %x:_(p0) = COPY $rax
    %cst:_(s64) = G_CONSTANT i64 0
    %op:_(p0) = G_PTR_ADD %x(p0), %cst
    $rax = COPY %op(p0)
    RET implicit $rax
...
---
name:            right_identity_rotl
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $eax, $ebx
    ; CHECK-LABEL: name: right_identity_rotl
    ; CHECK: liveins: $eax, $ebx
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %copy:_(s32) = COPY $eax
    ; CHECK-NEXT: $eax = COPY %copy(s32)
    ; CHECK-NEXT: RET implicit $eax
    %copy:_(s32) = COPY $eax
    %zero:_(s32) = G_CONSTANT i32 0
    %rot:_(s32) = G_ROTL %copy(s32), %zero(s32)
    $eax = COPY %rot(s32)
    RET implicit $eax
...
---
name:            right_identity_rotr
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $eax, $ebx
    ; CHECK-LABEL: name: right_identity_rotr
    ; CHECK: liveins: $eax, $ebx
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %copy:_(s32) = COPY $eax
    ; CHECK-NEXT: $eax = COPY %copy(s32)
    ; CHECK-NEXT: RET implicit $eax
    %copy:_(s32) = COPY $eax
    %zero:_(s32) = G_CONSTANT i32 0
    %rot:_(s32) = G_ROTR %copy(s32), %zero(s32)
    $eax = COPY %rot(s32)
    RET implicit $eax
...
---
name: lshr_of_vec_zero
body:             |
  bb.1:
  liveins: $xmm0
    ; CHECK-LABEL: name: lshr_of_vec_zero
    ; CHECK: liveins: $xmm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<8 x s16>) = COPY $xmm0
    ; CHECK-NEXT: $xmm0 = COPY [[COPY]](<8 x s16>)
    ; CHECK-NEXT: RET implicit $xmm0
    %0:_(<8 x s16>) = COPY $xmm0
    %5:_(s16) = G_CONSTANT i16 0
    %zero_vec:_(<8 x s16>) = G_BUILD_VECTOR %5(s16), %5(s16), %5(s16), %5(s16), %5(s16), %5(s16), %5(s16), %5(s16)
    %shift:_(<8 x s16>) = G_LSHR %0, %zero_vec(<8 x s16>)
    $xmm0 = COPY %shift(<8 x s16>)
    RET implicit $xmm0
...
---
name: ptradd_of_vec_zero
body:             |
  bb.1:
  liveins: $xmm0
    ; CHECK-LABEL: name: ptradd_of_vec_zero
    ; CHECK: liveins: $xmm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(<2 x p0>) = COPY $xmm0
    ; CHECK-NEXT: $xmm0 = COPY [[COPY]](<2 x p0>)
    ; CHECK-NEXT: RET implicit $xmm0
    %0:_(<2 x p0>) = COPY $xmm0
    %5:_(s64) = G_CONSTANT i64 0
    %zero_vec:_(<2 x s64>) = G_BUILD_VECTOR %5(s64), %5(s64)
    %ptr:_(<2 x p0>) = G_PTR_ADD %0, %zero_vec(<2 x s64>)
    $xmm0 = COPY %ptr(<2 x p0>)
    RET implicit $xmm0
...
---
name:            i128_or_cst
liveins:
  - { reg: '$rax' }
body:             |
  bb.1:
    liveins: $rax

    ; CHECK-LABEL: name: i128_or_cst
    ; CHECK: liveins: $rax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $rax
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s128) = G_LOAD [[COPY]](p0) :: (load (s128))
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s128) = G_CONSTANT i128 9223372036854775808
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s128) = G_OR [[LOAD]], [[C]]
    ; CHECK-NEXT: G_STORE [[OR]](s128), [[COPY]](p0) :: (store (s128), align 4)
    ; CHECK-NEXT: RET 0
    %0:_(p0) = COPY $rax
    %2:_(s128) = G_LOAD %0(p0) :: (load (s128))
    %4:_(s128) = G_CONSTANT i128 9223372036854775808
    %5:_(s128) = G_OR %2, %4
    G_STORE %5(s128), %0(p0) :: (store (s128), align 4)
    RET 0
...
---
name:            mul_1_shift_of_shift
liveins:
  - { reg: '$rax' }
body:             |
  bb.1:
    liveins: $rax

    ; CHECK-LABEL: name: mul_1_shift_of_shift
    ; CHECK: liveins: $rax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s64) = COPY $rax
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s64) = G_SHL [[COPY]], [[C]](s64)
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s64) = G_OR [[SHL]], [[C]]
    ; CHECK-NEXT: $rax = COPY [[OR]](s64)
    ; CHECK-NEXT: RET implicit $rax
    %0:_(s64) = COPY $rax
    %1:_(s64) = G_CONSTANT i64 1
    %2:_(s64) = G_SHL %0, %1(s64)
    %3:_(s64) = G_OR %2, %1
    %4:_(s64) = G_MUL %3, %1
    $rax = COPY %4(s64)
    RET implicit $rax
...
---
name:            sub_to_add
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eax
    ; CHECK-LABEL: name: sub_to_add
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $eax
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: %op:_(s32) = G_ADD %x, [[C]]
    ; CHECK-NEXT: $eax = COPY %op(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 1
    %op:_(s32) = G_SUB %x(s32), %cst
    $eax = COPY %op(s32)
    RET implicit $eax
...
---
name:            sub_to_add_nuw
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $eax
    ; CHECK-LABEL: name: sub_to_add_nuw
    ; CHECK: liveins: $eax
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %x:_(s32) = COPY $eax
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: %op:_(s32) = G_ADD %x, [[C]]
    ; CHECK-NEXT: $eax = COPY %op(s32)
    ; CHECK-NEXT: RET implicit $eax
    %x:_(s32) = COPY $eax
    %cst:_(s32) = G_CONSTANT i32 1
    %op:_(s32) = nuw G_SUB %x(s32), %cst
    $eax = COPY %op(s32)
    RET implicit $eax
...
---
name:   sub_to_add_nsw_128
body:             |
  bb.0:
    liveins: $eax, $ebx

    ; CHECK-LABEL: name: sub_to_add_nsw_128
    ; CHECK: liveins: $eax, $ebx
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %a:_(s32) = COPY $eax
    ; CHECK-NEXT: %b:_(s8) = G_TRUNC %a(s32)
    ; CHECK-NEXT: %c:_(s8) = G_CONSTANT i8 -128
    ; CHECK-NEXT: %add:_(s8) = G_ADD %b, %c
    ; CHECK-NEXT: %d:_(s32) = G_ZEXT %add(s8)
    ; CHECK-NEXT: $eax = COPY %d(s32)
    ; CHECK-NEXT: RET implicit $rax
    %a:_(s32) = COPY $eax
    %b:_(s8) = G_TRUNC %a
    %c:_(s8) = G_CONSTANT i8 -128
    %add:_(s8) = nsw nuw G_SUB %b, %c
    %d:_(s32) = G_ZEXT %add
    $eax = COPY %d
    RET implicit $rax
...
---
name:   sub_to_add_nsw_intmin
body:             |
  bb.0:
    liveins: $eax, $ebx

    ; CHECK-LABEL: name: sub_to_add_nsw_intmin
    ; CHECK: liveins: $eax, $ebx
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %a:_(s32) = COPY $eax
    ; CHECK-NEXT: %c:_(s32) = G_CONSTANT i32 -2147483648
    ; CHECK-NEXT: %add:_(s32) = G_ADD %a, %c
    ; CHECK-NEXT: $eax = COPY %add(s32)
    ; CHECK-NEXT: RET implicit $rax
    %a:_(s32) = COPY $eax
    %c:_(s32) = G_CONSTANT i32 -2147483648
    %add:_(s32) = nsw nuw G_SUB %a, %c
    $eax = COPY %add
    RET implicit $rax
...
