; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -global-isel -mtriple=x86_64-linux-gnux32 -stop-after=irtranslator -verify-machineinstrs < %s -o - | FileCheck -check-prefix=X32ABI %s

define i32* @ret_ptr() {
  ; X32ABI-LABEL: name: ret_ptr
  ; X32ABI: bb.1 (%ir-block.0):
  ; X32ABI-NEXT:   [[DEF:%[0-9]+]]:_(p0) = G_IMPLICIT_DEF
  ; X32ABI-NEXT:   [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[DEF]](p0) :: (load (p0) from `ptr undef`)
  ; X32ABI-NEXT:   [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[LOAD]](p0)
  ; X32ABI-NEXT:   [[ZEXT:%[0-9]+]]:_(s64) = G_ZEXT [[PTRTOINT]](s32)
  ; X32ABI-NEXT:   $rax = COPY [[ZEXT]](s64)
  ; X32ABI-NEXT:   RET 0, implicit $rax
  %ptr = load i32*, i32** undef
  ret i32* %ptr
}

define void @arg_ptr(i32* %ptr) {
  ; X32ABI-LABEL: name: arg_ptr
  ; X32ABI: bb.1 (%ir-block.0):
  ; X32ABI-NEXT:   liveins: $rdi
  ; X32ABI-NEXT: {{  $}}
  ; X32ABI-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $rdi
  ; X32ABI-NEXT:   [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
  ; X32ABI-NEXT:   [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[TRUNC]](s32)
  ; X32ABI-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; X32ABI-NEXT:   G_STORE [[C]](s32), [[INTTOPTR]](p0) :: (store (s32) into %ir.ptr)
  ; X32ABI-NEXT:   RET 0
  store i32 1, i32* %ptr
  ret void
}
