; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple loongarch64-unknown-linux-gnu < %s | FileCheck %s

define float @maxf(float %a, float %b) {
; CHECK-LABEL: maxf:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmax.s $fa0, $fa0, $fa1
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp nnan nsz oge float %a, %b
  %cond = select nnan nsz i1 %cmp, float %a, float %b
  ret float %cond
}

define float @minf(float %a, float %b) {
; CHECK-LABEL: minf:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmin.s $fa0, $fa0, $fa1
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp nnan nsz olt float %a, %b
  %cond = select nnan nsz i1 %cmp, float %a, float %b
  ret float %cond
}

define double @maxd(double %a, double %b) {
; CHECK-LABEL: maxd:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmax.d $fa0, $fa0, $fa1
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp nnan nsz oge double %a, %b
  %cond = select nnan nsz i1 %cmp, double %a, double %b
  ret double %cond
}

define double @mind(double %a, double %b) {
; CHECK-LABEL: mind:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmin.d $fa0, $fa0, $fa1
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp nnan nsz olt double %a, %b
  %cond = select nnan nsz i1 %cmp, double %a, double %b
  ret double %cond
}
