; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc --mtriple=loongarch64 -mattr=+d < %s | FileCheck %s

define void @test(ptr %sp, ptr %t, i32 %n) {
; CHECK-LABEL: test:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld.d $a0, $a0, 0
; CHECK-NEXT:    move $a3, $zero
; CHECK-NEXT:    addi.w $a2, $a2, 0
; CHECK-NEXT:    bge $a3, $a2, .LBB0_2
; CHECK-NEXT:    .p2align 4, , 16
; CHECK-NEXT:  .LBB0_1: # %while_body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    addi.w $a4, $a3, 1
; CHECK-NEXT:    stptr.w $a4, $a0, 8000
; CHECK-NEXT:    stptr.w $a3, $a0, 8004
; CHECK-NEXT:    stptr.w $a4, $a1, 8000
; CHECK-NEXT:    stptr.w $a3, $a1, 8004
; CHECK-NEXT:    move $a3, $a4
; CHECK-NEXT:    blt $a3, $a2, .LBB0_1
; CHECK-NEXT:  .LBB0_2: # %while_end
; CHECK-NEXT:    ret
entry:
  %s = load ptr, ptr %sp
  br label %while_cond

while_cond:
  %phi = phi i32 [ 0, %entry ], [ %i, %while_body ]
  %gep0 = getelementptr [65536 x i32], ptr %s, i64 0, i64 2000
  %gep1 = getelementptr [65536 x i32], ptr %s, i64 0, i64 2001
  %gep2 = getelementptr [65536 x i32], ptr %t, i64 0, i64 2000
  %gep3 = getelementptr [65536 x i32], ptr %t, i64 0, i64 2001
  %cmp = icmp slt i32 %phi, %n
  br i1 %cmp, label %while_body, label %while_end

while_body:
  %i = add i32 %phi, 1
  store i32 %i, ptr %gep0
  store i32 %phi, ptr %gep1
  store i32 %i, ptr %gep2
  store i32 %phi, ptr %gep3
  br label %while_cond

while_end:
  ret void
}
