; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=loongarch64-linux-gnu | FileCheck %s

define void @sdivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; CHECK-LABEL: sdivrem_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.d $sp, $sp, -48
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; CHECK-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; CHECK-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 1, -8
; CHECK-NEXT:    .cfi_offset 22, -16
; CHECK-NEXT:    .cfi_offset 23, -24
; CHECK-NEXT:    move $a6, $a4
; CHECK-NEXT:    move $fp, $a1
; CHECK-NEXT:    move $s0, $a0
; CHECK-NEXT:    addi.d $a4, $sp, 0
; CHECK-NEXT:    move $a0, $a2
; CHECK-NEXT:    move $a1, $a3
; CHECK-NEXT:    move $a2, $a6
; CHECK-NEXT:    move $a3, $a5
; CHECK-NEXT:    pcaddu18i $ra, %call36(__divmodti4)
; CHECK-NEXT:    jirl $ra, $ra, 0
; CHECK-NEXT:    ld.d $a2, $sp, 0
; CHECK-NEXT:    ld.d $a3, $sp, 8
; CHECK-NEXT:    st.d $a0, $s0, 0
; CHECK-NEXT:    st.d $a1, $s0, 8
; CHECK-NEXT:    st.d $a2, $fp, 0
; CHECK-NEXT:    st.d $a3, $fp, 8
; CHECK-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; CHECK-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; CHECK-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; CHECK-NEXT:    addi.d $sp, $sp, 48
; CHECK-NEXT:    ret
  %q = sdiv i128 %n, %d
  %r = srem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}

define void @udivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; CHECK-LABEL: udivrem_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.d $sp, $sp, -48
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; CHECK-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; CHECK-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 1, -8
; CHECK-NEXT:    .cfi_offset 22, -16
; CHECK-NEXT:    .cfi_offset 23, -24
; CHECK-NEXT:    move $a6, $a4
; CHECK-NEXT:    move $fp, $a1
; CHECK-NEXT:    move $s0, $a0
; CHECK-NEXT:    addi.d $a4, $sp, 0
; CHECK-NEXT:    move $a0, $a2
; CHECK-NEXT:    move $a1, $a3
; CHECK-NEXT:    move $a2, $a6
; CHECK-NEXT:    move $a3, $a5
; CHECK-NEXT:    pcaddu18i $ra, %call36(__udivmodti4)
; CHECK-NEXT:    jirl $ra, $ra, 0
; CHECK-NEXT:    ld.d $a2, $sp, 0
; CHECK-NEXT:    ld.d $a3, $sp, 8
; CHECK-NEXT:    st.d $a0, $s0, 0
; CHECK-NEXT:    st.d $a1, $s0, 8
; CHECK-NEXT:    st.d $a2, $fp, 0
; CHECK-NEXT:    st.d $a3, $fp, 8
; CHECK-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; CHECK-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; CHECK-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; CHECK-NEXT:    addi.d $sp, $sp, 48
; CHECK-NEXT:    ret
  %q = udiv i128 %n, %d
  %r = urem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}
