; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch64 < %s | FileCheck %s

define i1 @test(i104 %conv2, i64 %0) {
; CHECK-LABEL: test:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lu12i.w $a1, 431166
; CHECK-NEXT:    ori $a1, $a1, 1831
; CHECK-NEXT:    lu32i.d $a1, 117859
; CHECK-NEXT:    lu52i.d $a1, $a1, -335
; CHECK-NEXT:    xor $a0, $a0, $a1
; CHECK-NEXT:    and $a0, $a0, $a2
; CHECK-NEXT:    sltu $a0, $zero, $a0
; CHECK-NEXT:    ret
entry:
  %xor = xor i104 %conv2, 16938544400857032487
  %conv3 = zext i64 %0 to i104
  %and = and i104 %xor, %conv3
  %tobool = icmp ne i104 %and, 0
  ret i1 %tobool
}
