; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch32 < %s | FileCheck %s --check-prefix=LA32
; RUN: llc --mtriple=loongarch64 < %s | FileCheck %s --check-prefix=LA64

define i32 @icmpimm(i32 %x) {
; LA32-LABEL: icmpimm:
; LA32:       # %bb.0:
; LA32-NEXT:    srli.w $a0, $a0, 12
; LA32-NEXT:    addi.w $a0, $a0, -1
; LA32-NEXT:    sltui $a0, $a0, 1
; LA32-NEXT:    ret
;
; LA64-LABEL: icmpimm:
; LA64:       # %bb.0:
; LA64-NEXT:    bstrpick.d $a0, $a0, 31, 12
; LA64-NEXT:    addi.d $a0, $a0, -1
; LA64-NEXT:    sltui $a0, $a0, 1
; LA64-NEXT:    ret
  %1 = and i32 %x, -4096
  %2 = icmp eq i32 %1, 4096
  %3 = zext i1 %2 to i32
  ret i32 %3
}
