; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc --mtriple=loongarch32 --mattr=+lsx < %s | FileCheck %s --check-prefix=LA32
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s --check-prefix=LA64

define void @test_v2f32_load(ptr %saddr, ptr %daddr) nounwind {
; LA32-LABEL: test_v2f32_load:
; LA32:       # %bb.0:
; LA32-NEXT:    fld.s $fa0, $a0, 4
; LA32-NEXT:    fld.s $fa1, $a0, 0
; LA32-NEXT:    vextrins.w $vr1, $vr0, 16
; LA32-NEXT:    vfadd.s $vr0, $vr1, $vr1
; LA32-NEXT:    vstelm.w $vr0, $a1, 0, 0
; LA32-NEXT:    vstelm.w $vr0, $a1, 4, 1
; LA32-NEXT:    ret
;
; LA64-LABEL: test_v2f32_load:
; LA64:       # %bb.0:
; LA64-NEXT:    ld.d $a0, $a0, 0
; LA64-NEXT:    vinsgr2vr.d $vr0, $a0, 0
; LA64-NEXT:    vfadd.s $vr0, $vr0, $vr0
; LA64-NEXT:    vstelm.d $vr0, $a1, 0, 0
; LA64-NEXT:    ret
  %s0 = load <2 x float>, ptr %saddr
  %dst = fadd <2 x float> %s0, %s0
  store <2 x float> %dst, ptr %daddr
  ret void
}
