; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=loongarch32 | FileCheck %s -check-prefix=LA32
; RUN: llc < %s -mtriple=loongarch64 | FileCheck %s -check-prefix=LA64

; tailcc will turn all of these musttail calls into tail calls.

declare dso_local tailcc i32 @tailcallee(i32 %a1, i32 %a2)

define dso_local tailcc i32 @tailcaller(i32 %in1, i32 %in2) nounwind {
; LA32-LABEL: tailcaller:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    b tailcallee
;
; LA64-LABEL: tailcaller:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    pcaddu18i $t8, %call36(tailcallee)
; LA64-NEXT:    jr $t8
entry:
  %tmp11 = musttail call tailcc i32 @tailcallee(i32 %in1, i32 %in2)
  ret i32 %tmp11
}

declare dso_local tailcc ptr @alias_callee()

define tailcc noalias ptr @noalias_caller() nounwind {
; LA32-LABEL: noalias_caller:
; LA32:       # %bb.0:
; LA32-NEXT:    b alias_callee
;
; LA64-LABEL: noalias_caller:
; LA64:       # %bb.0:
; LA64-NEXT:    pcaddu18i $t8, %call36(alias_callee)
; LA64-NEXT:    jr $t8
  %p = musttail call tailcc ptr @alias_callee()
  ret ptr %p
}

declare dso_local tailcc noalias ptr @noalias_callee()

define dso_local tailcc ptr @alias_caller() nounwind {
; LA32-LABEL: alias_caller:
; LA32:       # %bb.0:
; LA32-NEXT:    b noalias_callee
;
; LA64-LABEL: alias_caller:
; LA64:       # %bb.0:
; LA64-NEXT:    pcaddu18i $t8, %call36(noalias_callee)
; LA64-NEXT:    jr $t8
  %p = musttail call tailcc noalias ptr @noalias_callee()
  ret ptr %p
}

define dso_local tailcc void @void_test(i32, i32, i32, i32) {
; LA32-LABEL: void_test:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    b void_test
;
; LA64-LABEL: void_test:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    pcaddu18i $t8, %call36(void_test)
; LA64-NEXT:    jr $t8
  entry:
   musttail call tailcc void @void_test( i32 %0, i32 %1, i32 %2, i32 %3)
   ret void
}

define dso_local tailcc i1 @i1test(i32, i32, i32, i32) {
; LA32-LABEL: i1test:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    b i1test
;
; LA64-LABEL: i1test:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    pcaddu18i $t8, %call36(i1test)
; LA64-NEXT:    jr $t8
  entry:
  %4 = musttail call tailcc i1 @i1test( i32 %0, i32 %1, i32 %2, i32 %3)
  ret i1 %4
}

; Regression test: musttail tailcc with non-forwarded stack args.
declare tailcc void @f1_64(i64, i64, i64, i64, i64, i64, i64, i64, i64)

define tailcc void @stack_arg_const_64(i64, i64, i64, i64, i64, i64, i64, i64, i64) {
; LA32-LABEL: stack_arg_const_64:
; LA32:       # %bb.0:
; LA32-NEXT:    st.w $zero, $sp, 36
; LA32-NEXT:    ori $a0, $zero, 61
; LA32-NEXT:    st.w $a0, $sp, 32
; LA32-NEXT:    st.w $zero, $sp, 28
; LA32-NEXT:    ori $a0, $zero, 53
; LA32-NEXT:    st.w $a0, $sp, 24
; LA32-NEXT:    st.w $zero, $sp, 20
; LA32-NEXT:    ori $a0, $zero, 42
; LA32-NEXT:    st.w $a0, $sp, 16
; LA32-NEXT:    st.w $zero, $sp, 12
; LA32-NEXT:    ori $a0, $zero, 23
; LA32-NEXT:    st.w $a0, $sp, 8
; LA32-NEXT:    st.w $zero, $sp, 4
; LA32-NEXT:    ori $a1, $zero, 16
; LA32-NEXT:    ori $a0, $zero, 1
; LA32-NEXT:    ori $a2, $zero, 4
; LA32-NEXT:    ori $a4, $zero, 8
; LA32-NEXT:    ori $a6, $zero, 15
; LA32-NEXT:    st.w $a1, $sp, 0
; LA32-NEXT:    move $a1, $zero
; LA32-NEXT:    move $a3, $zero
; LA32-NEXT:    move $a5, $zero
; LA32-NEXT:    move $a7, $zero
; LA32-NEXT:    b f1_64
;
; LA64-LABEL: stack_arg_const_64:
; LA64:       # %bb.0:
; LA64-NEXT:    ori $t0, $zero, 61
; LA64-NEXT:    ori $a0, $zero, 1
; LA64-NEXT:    ori $a1, $zero, 4
; LA64-NEXT:    ori $a2, $zero, 8
; LA64-NEXT:    ori $a3, $zero, 15
; LA64-NEXT:    ori $a4, $zero, 16
; LA64-NEXT:    ori $a5, $zero, 23
; LA64-NEXT:    ori $a6, $zero, 42
; LA64-NEXT:    ori $a7, $zero, 53
; LA64-NEXT:    st.d $t0, $sp, 0
; LA64-NEXT:    pcaddu18i $t8, %call36(f1_64)
; LA64-NEXT:    jr $t8
  musttail call tailcc void @f1_64(i64 1, i64 4, i64 8, i64 15, i64 16, i64 23, i64 42, i64 53, i64 61)
  ret void
}

declare tailcc void @f1_32(i32, i32, i32, i32, i32, i32, i32, i32, i32)

define tailcc void @stack_arg_const_32(i32, i32, i32, i32, i32, i32, i32, i32, i32) {
; LA32-LABEL: stack_arg_const_32:
; LA32:       # %bb.0:
; LA32-NEXT:    ori $t0, $zero, 61
; LA32-NEXT:    ori $a0, $zero, 1
; LA32-NEXT:    ori $a1, $zero, 4
; LA32-NEXT:    ori $a2, $zero, 8
; LA32-NEXT:    ori $a3, $zero, 15
; LA32-NEXT:    ori $a4, $zero, 16
; LA32-NEXT:    ori $a5, $zero, 23
; LA32-NEXT:    ori $a6, $zero, 42
; LA32-NEXT:    ori $a7, $zero, 53
; LA32-NEXT:    st.w $t0, $sp, 0
; LA32-NEXT:    b f1_32
;
; LA64-LABEL: stack_arg_const_32:
; LA64:       # %bb.0:
; LA64-NEXT:    ori $t0, $zero, 61
; LA64-NEXT:    ori $a0, $zero, 1
; LA64-NEXT:    ori $a1, $zero, 4
; LA64-NEXT:    ori $a2, $zero, 8
; LA64-NEXT:    ori $a3, $zero, 15
; LA64-NEXT:    ori $a4, $zero, 16
; LA64-NEXT:    ori $a5, $zero, 23
; LA64-NEXT:    ori $a6, $zero, 42
; LA64-NEXT:    ori $a7, $zero, 53
; LA64-NEXT:    st.d $t0, $sp, 0
; LA64-NEXT:    pcaddu18i $t8, %call36(f1_32)
; LA64-NEXT:    jr $t8
  musttail call tailcc void @f1_32(i32 1, i32 4, i32 8, i32 15, i32 16, i32 23, i32 42, i32 53, i32 61)
  ret void
}
