; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=loongarch32 < %s | FileCheck --check-prefix=LA32 %s
; RUN: llc -mtriple=loongarch64 < %s | FileCheck --check-prefix=LA64 %s

; This test checks various function call behaviors between preserve_none and
; normal calling conventions.

declare preserve_nonecc void @callee(ptr)

; Normal caller calls preserve_none callee. Will not generated tail call because
; of incompatible calling convention. Callee saved registers are saved/restored
; around the call.
define void @caller1(ptr %a) nounwind {
; LA32-LABEL: caller1:
; LA32:       # %bb.0:
; LA32-NEXT:    addi.w $sp, $sp, -48
; LA32-NEXT:    st.w $ra, $sp, 44 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s0, $sp, 40 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s1, $sp, 36 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s2, $sp, 32 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s3, $sp, 28 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s4, $sp, 24 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s5, $sp, 20 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s6, $sp, 16 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s7, $sp, 12 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s8, $sp, 8 # 4-byte Folded Spill
; LA32-NEXT:    move $s0, $a0
; LA32-NEXT:    bl callee
; LA32-NEXT:    ld.w $s8, $sp, 8 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s7, $sp, 12 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s6, $sp, 16 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s5, $sp, 20 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s4, $sp, 24 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s3, $sp, 28 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s2, $sp, 32 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s1, $sp, 36 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s0, $sp, 40 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $ra, $sp, 44 # 4-byte Folded Reload
; LA32-NEXT:    addi.w $sp, $sp, 48
; LA32-NEXT:    ret
;
; LA64-LABEL: caller1:
; LA64:       # %bb.0:
; LA64-NEXT:    addi.d $sp, $sp, -160
; LA64-NEXT:    st.d $ra, $sp, 152 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s0, $sp, 144 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s1, $sp, 136 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s2, $sp, 128 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s3, $sp, 120 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s4, $sp, 112 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s5, $sp, 104 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s6, $sp, 96 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s7, $sp, 88 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s8, $sp, 80 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs0, $sp, 72 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs1, $sp, 64 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs2, $sp, 56 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs3, $sp, 48 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs4, $sp, 40 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs5, $sp, 32 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs6, $sp, 24 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs7, $sp, 16 # 8-byte Folded Spill
; LA64-NEXT:    move $s0, $a0
; LA64-NEXT:    pcaddu18i $ra, %call36(callee)
; LA64-NEXT:    jirl $ra, $ra, 0
; LA64-NEXT:    fld.d $fs7, $sp, 16 # 8-byte Folded Reload
; LA64-NEXT:    fld.d $fs6, $sp, 24 # 8-byte Folded Reload
; LA64-NEXT:    fld.d $fs5, $sp, 32 # 8-byte Folded Reload
; LA64-NEXT:    fld.d $fs4, $sp, 40 # 8-byte Folded Reload
; LA64-NEXT:    fld.d $fs3, $sp, 48 # 8-byte Folded Reload
; LA64-NEXT:    fld.d $fs2, $sp, 56 # 8-byte Folded Reload
; LA64-NEXT:    fld.d $fs1, $sp, 64 # 8-byte Folded Reload
; LA64-NEXT:    fld.d $fs0, $sp, 72 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s8, $sp, 80 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s7, $sp, 88 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s6, $sp, 96 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s5, $sp, 104 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s4, $sp, 112 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s3, $sp, 120 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s2, $sp, 128 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s1, $sp, 136 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s0, $sp, 144 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $ra, $sp, 152 # 8-byte Folded Reload
; LA64-NEXT:    addi.d $sp, $sp, 160
; LA64-NEXT:    ret
  tail call preserve_nonecc void @callee(ptr %a)
  ret void
}

; Preserve_none caller calls preserve_none callee. Same function body.
; The tail call is preserved. No registers are saved/restored around the call.
; Actually a simple jmp instruction is generated.
define preserve_nonecc void @caller2(ptr %a) nounwind {
; LA32-LABEL: caller2:
; LA32:       # %bb.0:
; LA32-NEXT:    b callee
;
; LA64-LABEL: caller2:
; LA64:       # %bb.0:
; LA64-NEXT:    pcaddu18i $t8, %call36(callee)
; LA64-NEXT:    jr $t8
  tail call preserve_nonecc void @callee(ptr %a)
  ret void
}

; Preserve_none function can use more registers to pass parameters.
declare preserve_nonecc i64 @callee_with_many_param2(i64 %a1, i64 %a2, i64 %a3, i64 %a4, i64 %a5, i64 %a6, i64 %a7, i64 %a8, i64 %a9, i64 %a10, i64 %a11, i64 %a12, i64 %a13, i64 %a14, i64 %a15, i64 %a16, i64 %a17, i64 %a18, i64 %a19, i64 %a20, i64 %a21, i64 %a22, i64 %a23, i64 %a24, i64 %a25, i64 %a26)
define preserve_nonecc i64 @callee_with_many_param(i64 %a1, i64 %a2, i64 %a3, i64 %a4, i64 %a5, i64 %a6, i64 %a7, i64 %a8, i64 %a9, i64 %a10, i64 %a11, i64 %a12, i64 %a13, i64 %a14, i64 %a15, i64 %a16, i64 %a17, i64 %a18, i64 %a19, i64 %a20, i64 %a21, i64 %a22, i64 %a23, i64 %a24, i64 %a25, i64 %a26) nounwind {
; LA32-LABEL: callee_with_many_param:
; LA32:       # %bb.0:
; LA32-NEXT:    addi.w $sp, $sp, -224
; LA32-NEXT:    st.w $ra, $sp, 220 # 4-byte Folded Spill
; LA32-NEXT:    st.w $fp, $sp, 216 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 224
; LA32-NEXT:    st.w $s8, $sp, 212 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 232
; LA32-NEXT:    st.w $s8, $sp, 208 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 236
; LA32-NEXT:    st.w $s8, $sp, 204 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 240
; LA32-NEXT:    st.w $s8, $sp, 200 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 244
; LA32-NEXT:    st.w $s8, $sp, 196 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 248
; LA32-NEXT:    st.w $s8, $sp, 192 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 252
; LA32-NEXT:    st.w $s8, $sp, 188 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 256
; LA32-NEXT:    st.w $s8, $sp, 184 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 260
; LA32-NEXT:    st.w $s8, $sp, 180 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 264
; LA32-NEXT:    st.w $s8, $sp, 176 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 268
; LA32-NEXT:    st.w $s8, $sp, 172 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 272
; LA32-NEXT:    st.w $s8, $sp, 168 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 276
; LA32-NEXT:    st.w $s8, $sp, 164 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 280
; LA32-NEXT:    st.w $s8, $sp, 160 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 284
; LA32-NEXT:    st.w $s8, $sp, 156 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 288
; LA32-NEXT:    st.w $s8, $sp, 152 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 292
; LA32-NEXT:    st.w $s8, $sp, 148 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 296
; LA32-NEXT:    st.w $s8, $sp, 144 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 300
; LA32-NEXT:    st.w $s8, $sp, 140 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 304
; LA32-NEXT:    st.w $s8, $sp, 136 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 308
; LA32-NEXT:    st.w $s8, $sp, 132 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 312
; LA32-NEXT:    st.w $s8, $sp, 128 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 316
; LA32-NEXT:    st.w $s8, $sp, 124 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $s8, $sp, 320
; LA32-NEXT:    st.w $s8, $sp, 120 # 4-byte Folded Spill
; LA32-NEXT:    ld.w $ra, $sp, 324
; LA32-NEXT:    ld.w $fp, $sp, 328
; LA32-NEXT:    ld.w $s8, $sp, 332
; LA32-NEXT:    st.w $s1, $sp, 108
; LA32-NEXT:    st.w $s0, $sp, 104
; LA32-NEXT:    st.w $s8, $sp, 100
; LA32-NEXT:    st.w $fp, $sp, 96
; LA32-NEXT:    st.w $ra, $sp, 92
; LA32-NEXT:    ld.w $s0, $sp, 120 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 88
; LA32-NEXT:    ld.w $s0, $sp, 124 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 84
; LA32-NEXT:    ld.w $s0, $sp, 128 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 80
; LA32-NEXT:    ld.w $s0, $sp, 132 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 76
; LA32-NEXT:    ld.w $s0, $sp, 136 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 72
; LA32-NEXT:    ld.w $s0, $sp, 140 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 68
; LA32-NEXT:    ld.w $s0, $sp, 144 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 64
; LA32-NEXT:    ld.w $s0, $sp, 148 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 60
; LA32-NEXT:    ld.w $s0, $sp, 152 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 56
; LA32-NEXT:    ld.w $s0, $sp, 156 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 52
; LA32-NEXT:    ld.w $s0, $sp, 160 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 48
; LA32-NEXT:    ld.w $s0, $sp, 164 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 44
; LA32-NEXT:    ld.w $s0, $sp, 168 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 40
; LA32-NEXT:    ld.w $s0, $sp, 172 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 36
; LA32-NEXT:    ld.w $s0, $sp, 176 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 32
; LA32-NEXT:    ld.w $s0, $sp, 180 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 28
; LA32-NEXT:    ld.w $s0, $sp, 184 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 24
; LA32-NEXT:    ld.w $s0, $sp, 188 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 20
; LA32-NEXT:    ld.w $s0, $sp, 192 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 16
; LA32-NEXT:    ld.w $s0, $sp, 196 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 12
; LA32-NEXT:    ld.w $s0, $sp, 200 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 8
; LA32-NEXT:    ld.w $s0, $sp, 204 # 4-byte Folded Reload
; LA32-NEXT:    st.w $s0, $sp, 0
; LA32-NEXT:    move $s0, $s2
; LA32-NEXT:    move $s1, $s3
; LA32-NEXT:    move $s2, $s4
; LA32-NEXT:    move $s3, $s5
; LA32-NEXT:    move $s4, $s6
; LA32-NEXT:    move $s5, $s7
; LA32-NEXT:    move $s6, $a0
; LA32-NEXT:    move $s7, $a1
; LA32-NEXT:    move $a0, $a2
; LA32-NEXT:    move $a1, $a3
; LA32-NEXT:    move $a2, $a4
; LA32-NEXT:    move $a3, $a5
; LA32-NEXT:    move $a4, $a6
; LA32-NEXT:    move $a5, $a7
; LA32-NEXT:    move $a6, $t0
; LA32-NEXT:    move $a7, $t1
; LA32-NEXT:    move $t0, $t2
; LA32-NEXT:    move $t1, $t3
; LA32-NEXT:    move $t2, $t4
; LA32-NEXT:    move $t3, $t5
; LA32-NEXT:    move $t4, $t6
; LA32-NEXT:    move $t5, $t7
; LA32-NEXT:    move $t6, $t8
; LA32-NEXT:    ld.w $t7, $sp, 212 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $t8, $sp, 208 # 4-byte Folded Reload
; LA32-NEXT:    bl callee_with_many_param2
; LA32-NEXT:    ld.w $fp, $sp, 216 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $ra, $sp, 220 # 4-byte Folded Reload
; LA32-NEXT:    addi.w $sp, $sp, 224
; LA32-NEXT:    ret
;
; LA64-LABEL: callee_with_many_param:
; LA64:       # %bb.0:
; LA64-NEXT:    addi.d $sp, $sp, -16
; LA64-NEXT:    st.d $ra, $sp, 8 # 8-byte Folded Spill
; LA64-NEXT:    ld.d $s8, $sp, 16
; LA64-NEXT:    st.d $s0, $sp, 0
; LA64-NEXT:    move $s0, $s1
; LA64-NEXT:    move $s1, $s2
; LA64-NEXT:    move $s2, $s3
; LA64-NEXT:    move $s3, $s4
; LA64-NEXT:    move $s4, $s5
; LA64-NEXT:    move $s5, $s6
; LA64-NEXT:    move $s6, $s7
; LA64-NEXT:    move $s7, $a0
; LA64-NEXT:    move $a0, $a1
; LA64-NEXT:    move $a1, $a2
; LA64-NEXT:    move $a2, $a3
; LA64-NEXT:    move $a3, $a4
; LA64-NEXT:    move $a4, $a5
; LA64-NEXT:    move $a5, $a6
; LA64-NEXT:    move $a6, $a7
; LA64-NEXT:    move $a7, $t0
; LA64-NEXT:    move $t0, $t1
; LA64-NEXT:    move $t1, $t2
; LA64-NEXT:    move $t2, $t3
; LA64-NEXT:    move $t3, $t4
; LA64-NEXT:    move $t4, $t5
; LA64-NEXT:    move $t5, $t6
; LA64-NEXT:    move $t6, $t7
; LA64-NEXT:    move $t7, $t8
; LA64-NEXT:    move $t8, $s8
; LA64-NEXT:    pcaddu18i $ra, %call36(callee_with_many_param2)
; LA64-NEXT:    jirl $ra, $ra, 0
; LA64-NEXT:    ld.d $ra, $sp, 8 # 8-byte Folded Reload
; LA64-NEXT:    addi.d $sp, $sp, 16
; LA64-NEXT:    ret
  %ret = call preserve_nonecc i64 @callee_with_many_param2(i64 %a2, i64 %a3, i64 %a4, i64 %a5, i64 %a6, i64 %a7, i64 %a8, i64 %a9, i64 %a10, i64 %a11, i64 %a12, i64 %a13, i64 %a14, i64 %a15, i64 %a16, i64 %a17, i64 %a18, i64 %a19, i64 %a20, i64 %a21, i64 %a22, i64 %a23, i64 %a24, i64 %a25, i64 %a26, i64 %a1)
  ret i64 %ret
}

define i64 @caller3() nounwind {
; LA32-LABEL: caller3:
; LA32:       # %bb.0:
; LA32-NEXT:    addi.w $sp, $sp, -160
; LA32-NEXT:    st.w $ra, $sp, 156 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s0, $sp, 152 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s1, $sp, 148 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s2, $sp, 144 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s3, $sp, 140 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s4, $sp, 136 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s5, $sp, 132 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s6, $sp, 128 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s7, $sp, 124 # 4-byte Folded Spill
; LA32-NEXT:    st.w $s8, $sp, 120 # 4-byte Folded Spill
; LA32-NEXT:    st.w $zero, $sp, 108
; LA32-NEXT:    ori $a0, $zero, 26
; LA32-NEXT:    st.w $a0, $sp, 104
; LA32-NEXT:    st.w $zero, $sp, 100
; LA32-NEXT:    ori $a0, $zero, 25
; LA32-NEXT:    st.w $a0, $sp, 96
; LA32-NEXT:    st.w $zero, $sp, 92
; LA32-NEXT:    ori $a0, $zero, 24
; LA32-NEXT:    st.w $a0, $sp, 88
; LA32-NEXT:    st.w $zero, $sp, 84
; LA32-NEXT:    ori $a0, $zero, 23
; LA32-NEXT:    st.w $a0, $sp, 80
; LA32-NEXT:    st.w $zero, $sp, 76
; LA32-NEXT:    ori $a0, $zero, 22
; LA32-NEXT:    st.w $a0, $sp, 72
; LA32-NEXT:    st.w $zero, $sp, 68
; LA32-NEXT:    ori $a0, $zero, 21
; LA32-NEXT:    st.w $a0, $sp, 64
; LA32-NEXT:    st.w $zero, $sp, 60
; LA32-NEXT:    ori $a0, $zero, 20
; LA32-NEXT:    st.w $a0, $sp, 56
; LA32-NEXT:    st.w $zero, $sp, 52
; LA32-NEXT:    ori $a0, $zero, 19
; LA32-NEXT:    st.w $a0, $sp, 48
; LA32-NEXT:    st.w $zero, $sp, 44
; LA32-NEXT:    ori $a0, $zero, 18
; LA32-NEXT:    st.w $a0, $sp, 40
; LA32-NEXT:    st.w $zero, $sp, 36
; LA32-NEXT:    ori $a0, $zero, 17
; LA32-NEXT:    st.w $a0, $sp, 32
; LA32-NEXT:    st.w $zero, $sp, 28
; LA32-NEXT:    ori $a0, $zero, 16
; LA32-NEXT:    st.w $a0, $sp, 24
; LA32-NEXT:    st.w $zero, $sp, 20
; LA32-NEXT:    ori $a0, $zero, 15
; LA32-NEXT:    st.w $a0, $sp, 16
; LA32-NEXT:    st.w $zero, $sp, 12
; LA32-NEXT:    ori $a0, $zero, 14
; LA32-NEXT:    st.w $a0, $sp, 8
; LA32-NEXT:    st.w $zero, $sp, 0
; LA32-NEXT:    ori $s0, $zero, 1
; LA32-NEXT:    ori $s2, $zero, 2
; LA32-NEXT:    ori $s4, $zero, 3
; LA32-NEXT:    ori $s6, $zero, 4
; LA32-NEXT:    ori $a0, $zero, 5
; LA32-NEXT:    ori $a2, $zero, 6
; LA32-NEXT:    ori $a4, $zero, 7
; LA32-NEXT:    ori $a6, $zero, 8
; LA32-NEXT:    ori $t0, $zero, 9
; LA32-NEXT:    ori $t2, $zero, 10
; LA32-NEXT:    ori $t4, $zero, 11
; LA32-NEXT:    ori $t6, $zero, 12
; LA32-NEXT:    ori $t8, $zero, 13
; LA32-NEXT:    move $s1, $zero
; LA32-NEXT:    move $s3, $zero
; LA32-NEXT:    move $s5, $zero
; LA32-NEXT:    move $s7, $zero
; LA32-NEXT:    move $a1, $zero
; LA32-NEXT:    move $a3, $zero
; LA32-NEXT:    move $a5, $zero
; LA32-NEXT:    move $a7, $zero
; LA32-NEXT:    move $t1, $zero
; LA32-NEXT:    move $t3, $zero
; LA32-NEXT:    move $t5, $zero
; LA32-NEXT:    move $t7, $zero
; LA32-NEXT:    bl callee_with_many_param
; LA32-NEXT:    move $a0, $s0
; LA32-NEXT:    move $a1, $s1
; LA32-NEXT:    ld.w $s8, $sp, 120 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s7, $sp, 124 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s6, $sp, 128 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s5, $sp, 132 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s4, $sp, 136 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s3, $sp, 140 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s2, $sp, 144 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s1, $sp, 148 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $s0, $sp, 152 # 4-byte Folded Reload
; LA32-NEXT:    ld.w $ra, $sp, 156 # 4-byte Folded Reload
; LA32-NEXT:    addi.w $sp, $sp, 160
; LA32-NEXT:    ret
;
; LA64-LABEL: caller3:
; LA64:       # %bb.0:
; LA64-NEXT:    addi.d $sp, $sp, -160
; LA64-NEXT:    st.d $ra, $sp, 152 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s0, $sp, 144 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s1, $sp, 136 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s2, $sp, 128 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s3, $sp, 120 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s4, $sp, 112 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s5, $sp, 104 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s6, $sp, 96 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s7, $sp, 88 # 8-byte Folded Spill
; LA64-NEXT:    st.d $s8, $sp, 80 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs0, $sp, 72 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs1, $sp, 64 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs2, $sp, 56 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs3, $sp, 48 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs4, $sp, 40 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs5, $sp, 32 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs6, $sp, 24 # 8-byte Folded Spill
; LA64-NEXT:    fst.d $fs7, $sp, 16 # 8-byte Folded Spill
; LA64-NEXT:    ori $a0, $zero, 26
; LA64-NEXT:    st.d $a0, $sp, 0
; LA64-NEXT:    ori $s0, $zero, 1
; LA64-NEXT:    ori $s1, $zero, 2
; LA64-NEXT:    ori $s2, $zero, 3
; LA64-NEXT:    ori $s3, $zero, 4
; LA64-NEXT:    ori $s4, $zero, 5
; LA64-NEXT:    ori $s5, $zero, 6
; LA64-NEXT:    ori $s6, $zero, 7
; LA64-NEXT:    ori $s7, $zero, 8
; LA64-NEXT:    ori $a0, $zero, 9
; LA64-NEXT:    ori $a1, $zero, 10
; LA64-NEXT:    ori $a2, $zero, 11
; LA64-NEXT:    ori $a3, $zero, 12
; LA64-NEXT:    ori $a4, $zero, 13
; LA64-NEXT:    ori $a5, $zero, 14
; LA64-NEXT:    ori $a6, $zero, 15
; LA64-NEXT:    ori $a7, $zero, 16
; LA64-NEXT:    ori $t0, $zero, 17
; LA64-NEXT:    ori $t1, $zero, 18
; LA64-NEXT:    ori $t2, $zero, 19
; LA64-NEXT:    ori $t3, $zero, 20
; LA64-NEXT:    ori $t4, $zero, 21
; LA64-NEXT:    ori $t5, $zero, 22
; LA64-NEXT:    ori $t6, $zero, 23
; LA64-NEXT:    ori $t7, $zero, 24
; LA64-NEXT:    ori $t8, $zero, 25
; LA64-NEXT:    pcaddu18i $ra, %call36(callee_with_many_param)
; LA64-NEXT:    jirl $ra, $ra, 0
; LA64-NEXT:    move $a0, $s0
; LA64-NEXT:    fld.d $fs7, $sp, 16 # 8-byte Folded Reload
; LA64-NEXT:    fld.d $fs6, $sp, 24 # 8-byte Folded Reload
; LA64-NEXT:    fld.d $fs5, $sp, 32 # 8-byte Folded Reload
; LA64-NEXT:    fld.d $fs4, $sp, 40 # 8-byte Folded Reload
; LA64-NEXT:    fld.d $fs3, $sp, 48 # 8-byte Folded Reload
; LA64-NEXT:    fld.d $fs2, $sp, 56 # 8-byte Folded Reload
; LA64-NEXT:    fld.d $fs1, $sp, 64 # 8-byte Folded Reload
; LA64-NEXT:    fld.d $fs0, $sp, 72 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s8, $sp, 80 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s7, $sp, 88 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s6, $sp, 96 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s5, $sp, 104 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s4, $sp, 112 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s3, $sp, 120 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s2, $sp, 128 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s1, $sp, 136 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $s0, $sp, 144 # 8-byte Folded Reload
; LA64-NEXT:    ld.d $ra, $sp, 152 # 8-byte Folded Reload
; LA64-NEXT:    addi.d $sp, $sp, 160
; LA64-NEXT:    ret
  %ret = call preserve_nonecc i64 @callee_with_many_param(i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15, i64 16, i64 17, i64 18, i64 19, i64 20, i64 21, i64 22, i64 23, i64 24, i64 25, i64 26)
  ret i64 %ret
}
