; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch64 --mattr=+f < %s | FileCheck %s --check-prefix=CHECK-F
; RUN: llc --mtriple=loongarch64 < %s | FileCheck %s --check-prefix=CHECK-NOF
; RUN: not llc --mtriple=loongarch64 --mattr=+f < %s 2>&1 | FileCheck %s --check-prefix=CHECK-ERR

;; LLVM rounding mode encoding: 0=RTZ, 1=RNE, 2=RUP, 3=RDN.
;; LoongArch FCSR encoding:      0=RNE, 1=RZ,  2=RP,  3=RN.
;; Translation: swap 0↔1, keep 2 and 3.
;; The RM field in FCSR is at bits [9:8], so the value is shifted left by 8.

define void @set_rounding_rne() nounwind {
; CHECK-F-LABEL: set_rounding_rne:
; CHECK-F:       movgr2fcsr $fcsr3, $zero
; CHECK-F-NEXT:  ret
  tail call void @llvm.set.rounding(i32 1)
  ret void
}

define void @set_rounding_rtz() nounwind {
; CHECK-F-LABEL: set_rounding_rtz:
; CHECK-F:       ori $a0, $zero, 256
; CHECK-F-NEXT:  movgr2fcsr $fcsr3, $a0
; CHECK-F-NEXT:  ret
  tail call void @llvm.set.rounding(i32 0)
  ret void
}

define void @set_rounding_rup() nounwind {
; CHECK-F-LABEL: set_rounding_rup:
; CHECK-F:       ori $a0, $zero, 512
; CHECK-F-NEXT:  movgr2fcsr $fcsr3, $a0
; CHECK-F-NEXT:  ret
  tail call void @llvm.set.rounding(i32 2)
  ret void
}

define void @set_rounding_rdn() nounwind {
; CHECK-F-LABEL: set_rounding_rdn:
; CHECK-F:       ori $a0, $zero, 768
; CHECK-F-NEXT:  movgr2fcsr $fcsr3, $a0
; CHECK-F-NEXT:  ret
  tail call void @llvm.set.rounding(i32 3)
  ret void
}

;; Test dynamic rounding mode argument.
define void @set_rounding_dynamic(i32 %rm) nounwind {
; CHECK-F-LABEL: set_rounding_dynamic:
; CHECK-F:       movgr2fcsr $fcsr3, $a0
; CHECK-F-NEXT:  ret
  tail call void @llvm.set.rounding(i32 %rm)
  ret void
}

;; Test without FP feature - should not emit movgr2fcsr.
; CHECK-NOF-LABEL: set_rounding_no_fp:
; CHECK-NOF:      ret
define void @set_rounding_no_fp() nounwind {
  tail call void @llvm.set.rounding(i32 0)
  ret void
}

;; Test invalid rounding mode >= 4 (constant) - should emit error.
; CHECK-ERR: invalid rounding mode
define void @set_rounding_invalid() nounwind {
  tail call void @llvm.set.rounding(i32 4)
  ret void
}

declare void @llvm.set.rounding(i32)
