; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6

; RUN: llc --mtriple=loongarch32 -mattr=+d --verify-machineinstrs < %s | FileCheck %s --check-prefix=LA32
; RUN: llc --mtriple=loongarch64 -mattr=+d --verify-machineinstrs < %s | FileCheck %s --check-prefix=LA64

define <4 x i1> @backsmith_pure_1(<4 x i64> %shuffle2, <4 x i64> %shuffle4) #0 {
; LA32-LABEL: backsmith_pure_1:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    ld.w $a3, $a1, 8
; LA32-NEXT:    ld.w $a4, $a2, 8
; LA32-NEXT:    ld.w $a5, $a1, 0
; LA32-NEXT:    ld.w $a6, $a1, 24
; LA32-NEXT:    ld.w $a7, $a2, 24
; LA32-NEXT:    ld.w $a1, $a1, 16
; LA32-NEXT:    ld.w $t0, $a2, 16
; LA32-NEXT:    ld.w $a2, $a2, 0
; LA32-NEXT:    xor $a6, $a7, $a6
; LA32-NEXT:    sltu $a6, $zero, $a6
; LA32-NEXT:    xor $a1, $t0, $a1
; LA32-NEXT:    sltu $a1, $zero, $a1
; LA32-NEXT:    xor $a2, $a2, $a5
; LA32-NEXT:    sltu $a2, $zero, $a2
; LA32-NEXT:    xor $a3, $a4, $a3
; LA32-NEXT:    sltu $a3, $zero, $a3
; LA32-NEXT:    slli.w $a3, $a3, 1
; LA32-NEXT:    or $a2, $a2, $a3
; LA32-NEXT:    slli.w $a1, $a1, 2
; LA32-NEXT:    or $a1, $a2, $a1
; LA32-NEXT:    slli.w $a2, $a6, 3
; LA32-NEXT:    or $a1, $a1, $a2
; LA32-NEXT:    st.b $a1, $a0, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: backsmith_pure_1:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    vpickev.w $vr2, $vr3, $vr2
; LA64-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA64-NEXT:    vseq.w $vr0, $vr2, $vr0
; LA64-NEXT:    vrepli.b $vr1, -1
; LA64-NEXT:    vxor.v $vr0, $vr0, $vr1
; LA64-NEXT:    ret
entry:
  %conv5 = trunc nuw <4 x i64> %shuffle4 to <4 x i32>
  %conv3 = trunc nuw <4 x i64> %shuffle2 to <4 x i32>
  %cmp = icmp ne <4 x i32> %conv5, %conv3
  ret <4 x i1> %cmp
}
