; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch32 -mattr=+d --verify-machineinstrs < %s | \
; RUN:   FileCheck %s --check-prefixes=CHECK,CHECK-AMSWAP
; RUN: llc --mtriple=loongarch32 -mattr=+d --verify-machineinstrs \
; RUN:   --loongarch-trap-break-code=1 < %s | \
; RUN:   FileCheck %s --check-prefixes=CHECK,CHECK-BREAK
; RUN: llc --mtriple=loongarch64 -mattr=+d --verify-machineinstrs < %s | \
; RUN:   FileCheck %s --check-prefixes=CHECK,CHECK-AMSWAP
; RUN: llc --mtriple=loongarch64 -mattr=+d --verify-machineinstrs \
; RUN:   --loongarch-trap-break-code=1 < %s | \
; RUN:   FileCheck %s --check-prefixes=CHECK,CHECK-BREAK

;; Verify that we lower @llvm.trap() and @llvm.debugtrap() correctly.

declare void @llvm.trap()
declare void @llvm.debugtrap()

define void @test_trap() nounwind {
; CHECK-AMSWAP-LABEL: test_trap:
; CHECK-AMSWAP:       # %bb.0:
; CHECK-AMSWAP-NEXT:    amswap.w $zero, $ra, $zero
; CHECK-AMSWAP-NEXT:    ret
;
; CHECK-BREAK-LABEL: test_trap:
; CHECK-BREAK:       # %bb.0:
; CHECK-BREAK-NEXT:    break 1
; CHECK-BREAK-NEXT:    ret
  tail call void @llvm.trap()
  ret void
}

define void @test_debugtrap() nounwind {
; CHECK-LABEL: test_debugtrap:
; CHECK:       # %bb.0:
; CHECK-NEXT:    break 0
; CHECK-NEXT:    ret
  tail call void @llvm.debugtrap()
  ret void
}
