// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu gfx1300 -target-feature +wavefrontsize32 -emit-llvm -o - %s | FileCheck %s --check-prefix=CHECK-GFX1300

typedef unsigned int uint;
typedef unsigned long ulong;
typedef half  v2h   __attribute__((ext_vector_type(2)));
typedef half  v4h   __attribute__((ext_vector_type(4)));
typedef half  v6h   __attribute__((ext_vector_type(6)));
typedef half  v8h   __attribute__((ext_vector_type(8)));
typedef half  v10h   __attribute__((ext_vector_type(10)));
typedef half  v12h   __attribute__((ext_vector_type(12)));
typedef half  v16h   __attribute__((ext_vector_type(16)));
typedef half  v18h   __attribute__((ext_vector_type(18)));
typedef half  v36h   __attribute__((ext_vector_type(36)));

typedef __bf16  v2bf16   __attribute__((ext_vector_type(2)));
typedef __bf16  v4bf16   __attribute__((ext_vector_type(4)));
typedef __bf16  v6bf16   __attribute__((ext_vector_type(6)));
typedef __bf16  v8bf16   __attribute__((ext_vector_type(8)));
typedef __bf16  v10bf16   __attribute__((ext_vector_type(10)));
typedef __bf16  v12bf16   __attribute__((ext_vector_type(12)));
typedef __bf16  v16bf16   __attribute__((ext_vector_type(16)));
typedef __bf16  v18bf16   __attribute__((ext_vector_type(18)));
typedef __bf16  v36bf16   __attribute__((ext_vector_type(36)));

typedef float  v4f   __attribute__((ext_vector_type(4)));

typedef int    v2i   __attribute__((ext_vector_type(2)));
typedef int    v3i   __attribute__((ext_vector_type(3)));
typedef int    v4i   __attribute__((ext_vector_type(4)));
typedef int    v5i   __attribute__((ext_vector_type(5)));
typedef int    v6i   __attribute__((ext_vector_type(6)));
typedef int    v8i   __attribute__((ext_vector_type(8)));
typedef int    v9i   __attribute__((ext_vector_type(9)));
typedef int   v18i   __attribute__((ext_vector_type(18)));

#define CONV_FILTER_1x1  (0 << 3)
#define CONV_FILTER_3x3  (1 << 3)

#define CONV_ITER_1      (0 << 12)
#define CONV_ITER_2      (1 << 12)
#define CONV_ITER_3      (2 << 12)
#define CONV_ITER_4      (3 << 12)

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_iu4_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.iu4.3x3.v4f32.v4f32.v18i32.v3i32(<4 x float> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4:![0-9]+]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_iu4_4x2_3x3(global v4f* out, v4f acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f32_iu4_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.iu4.3x3.v4f16.v4f16.v18i32.v3i32(<4 x half> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x2_3x3(global v4h* out, v4h acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_iu4_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu4.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half> [[ACC:%.*]], <9 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 10, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x4_3x3(global v8h* out, v8h acc, v9i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_iu4_4x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu4_8x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu4.3x3.v8f16.v8f16.v5i32.v4i32(<8 x half> [[ACC:%.*]], <5 x i32> [[WEIGHTS:%.*]], <4 x i32> [[COL_CENTER:%.*]], <4 x i32> [[COL_LEFT:%.*]], <4 x i32> [[COL_RIGHT:%.*]], i32 8, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu4_8x4_3x3(global v8h* out, v8h acc, v5i weights, v4i col_center, v4i col_left, v4i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_iu4_8x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_i32_iu4_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.convolve.i32.iu4.3x3.v4i32.v4i32.v18i32.v3i32(<4 x i32> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_i32_iu4_4x2_3x3(global v4i* out, v4i acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_i32_iu4_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32i32_iu4_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32i32.iu4.3x3.v4f32.v4i32.v18i32.v3i32(<4 x i32> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32i32_iu4_4x2_3x3(global v4f* out, v4i acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f32i32_iu4_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_iu8_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.iu8.3x3.v4f32.v4f32.v18i32.v3i32(<4 x float> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_iu8_4x2_3x3(global v4f* out, v4f acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f32_iu8_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.iu8.3x3.v4f16.v4f16.v18i32.v3i32(<4 x half> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x2_3x3(global v4h* out, v4h acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_iu8_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half> [[ACC:%.*]], <9 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 10, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x4_3x3(global v8h* out, v8h acc, v9i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_iu8_4x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu8_8x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu8.3x3.v8f16.v8f16.v5i32.v4i32(<8 x half> [[ACC:%.*]], <5 x i32> [[WEIGHTS:%.*]], <4 x i32> [[COL_CENTER:%.*]], <4 x i32> [[COL_LEFT:%.*]], <4 x i32> [[COL_RIGHT:%.*]], i32 8, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu8_8x4_3x3(global v8h* out, v8h acc, v5i weights, v4i col_center, v4i col_left, v4i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_iu8_8x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_i32_iu8_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.convolve.i32.iu8.3x3.v4i32.v4i32.v18i32.v3i32(<4 x i32> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_i32_iu8_4x2_3x3(global v4i* out, v4i acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_i32_iu8_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32i32_iu8_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32i32.iu8.3x3.v4f32.v4i32.v18i32.v3i32(<4 x i32> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32i32_iu8_4x2_3x3(global v4f* out, v4i acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f32i32_iu8_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_fp8_fp8_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.fp8.fp8.3x3.v4f32.v4f32.v18i32.v3i32(<4 x float> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_fp8_fp8_4x2_3x3(global v4f* out, v4f acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f32_fp8_fp8_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.3x3.v4f16.v4f16.v18i32.v3i32(<4 x half> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x2_3x3(global v4h* out, v4h acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_fp8_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half> [[ACC:%.*]], <9 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 10, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x4_3x3(global v8h* out, v8h acc, v9i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_fp8_4x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_8x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.3x3.v8f16.v8f16.v5i32.v4i32(<8 x half> [[ACC:%.*]], <5 x i32> [[WEIGHTS:%.*]], <4 x i32> [[COL_CENTER:%.*]], <4 x i32> [[COL_LEFT:%.*]], <4 x i32> [[COL_RIGHT:%.*]], i32 8, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_8x4_3x3(global v8h* out, v8h acc, v5i weights, v4i col_center, v4i col_left, v4i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_fp8_8x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_fp8_bf8_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.fp8.bf8.3x3.v4f32.v4f32.v18i32.v3i32(<4 x float> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_fp8_bf8_4x2_3x3(global v4f* out, v4f acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f32_fp8_bf8_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.fp8.bf8.3x3.v4f16.v4f16.v18i32.v3i32(<4 x half> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x2_3x3(global v4h* out, v4h acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_bf8_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.bf8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half> [[ACC:%.*]], <9 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 10, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x4_3x3(global v8h* out, v8h acc, v9i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_bf8_4x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_8x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.bf8.3x3.v8f16.v8f16.v5i32.v4i32(<8 x half> [[ACC:%.*]], <5 x i32> [[WEIGHTS:%.*]], <4 x i32> [[COL_CENTER:%.*]], <4 x i32> [[COL_LEFT:%.*]], <4 x i32> [[COL_RIGHT:%.*]], i32 8, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_8x4_3x3(global v8h* out, v8h acc, v5i weights, v4i col_center, v4i col_left, v4i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_bf8_8x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_bf8_fp8_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.bf8.fp8.3x3.v4f32.v4f32.v18i32.v3i32(<4 x float> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_bf8_fp8_4x2_3x3(global v4f* out, v4f acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f32_bf8_fp8_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.bf8.fp8.3x3.v4f16.v4f16.v18i32.v3i32(<4 x half> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x2_3x3(global v4h* out, v4h acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_fp8_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.fp8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half> [[ACC:%.*]], <9 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 10, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x4_3x3(global v8h* out, v8h acc, v9i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_fp8_4x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_8x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.fp8.3x3.v8f16.v8f16.v5i32.v4i32(<8 x half> [[ACC:%.*]], <5 x i32> [[WEIGHTS:%.*]], <4 x i32> [[COL_CENTER:%.*]], <4 x i32> [[COL_LEFT:%.*]], <4 x i32> [[COL_RIGHT:%.*]], i32 8, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_8x4_3x3(global v8h* out, v8h acc, v5i weights, v4i col_center, v4i col_left, v4i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_fp8_8x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_bf8_bf8_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.bf8.bf8.3x3.v4f32.v4f32.v18i32.v3i32(<4 x float> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_bf8_bf8_4x2_3x3(global v4f* out, v4f acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f32_bf8_bf8_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.bf8.bf8.3x3.v4f16.v4f16.v18i32.v3i32(<4 x half> [[ACC:%.*]], <18 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x2_3x3(global v4h* out, v4h acc, v18i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_bf8_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.bf8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half> [[ACC:%.*]], <9 x i32> [[WEIGHTS:%.*]], <3 x i32> [[COL_CENTER:%.*]], <3 x i32> [[COL_LEFT:%.*]], <3 x i32> [[COL_RIGHT:%.*]], i32 10, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x4_3x3(global v8h* out, v8h acc, v9i weights, v3i col_center, v3i col_left, v3i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_bf8_4x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_8x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.bf8.3x3.v8f16.v8f16.v5i32.v4i32(<8 x half> [[ACC:%.*]], <5 x i32> [[WEIGHTS:%.*]], <4 x i32> [[COL_CENTER:%.*]], <4 x i32> [[COL_LEFT:%.*]], <4 x i32> [[COL_RIGHT:%.*]], i32 8, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_8x4_3x3(global v8h* out, v8h acc, v5i weights, v4i col_center, v4i col_left, v4i col_right)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_bf8_8x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_f16_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.f16.3x3.v4f32.v4f32.v36f16.v6f16(<4 x float> [[ACC:%.*]], <36 x half> [[WEIGHTS:%.*]], <6 x half> [[COL_CENTER:%.*]], <6 x half> [[COL_LEFT:%.*]], <6 x half> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_f16_4x2_3x3(global v4f* out, v4f acc, v36h weights, v6h col_center, v6h col_left, v6h col_right)
{
   *out = __builtin_amdgcn_convolve_f32_f16_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.f16.3x3.v4f16.v4f16.v36f16.v6f16(<4 x half> [[ACC:%.*]], <36 x half> [[WEIGHTS:%.*]], <6 x half> [[COL_CENTER:%.*]], <6 x half> [[COL_LEFT:%.*]], <6 x half> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x2_3x3(global v4h* out, v4h acc, v36h weights, v6h col_center, v6h col_left, v6h col_right)
{
   *out = __builtin_amdgcn_convolve_f16_f16_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.f16.3x3.v8f16.v8f16.v18f16.v6f16(<8 x half> [[ACC:%.*]], <18 x half> [[WEIGHTS:%.*]], <6 x half> [[COL_CENTER:%.*]], <6 x half> [[COL_LEFT:%.*]], <6 x half> [[COL_RIGHT:%.*]], i32 10, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x4_3x3(global v8h* out, v8h acc, v18h weights, v6h col_center, v6h col_left, v6h col_right)
{
   *out = __builtin_amdgcn_convolve_f16_f16_4x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_f16_8x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.f16.3x3.v8f16.v8f16.v10f16.v8f16(<8 x half> [[ACC:%.*]], <10 x half> [[WEIGHTS:%.*]], <8 x half> [[COL_CENTER:%.*]], <8 x half> [[COL_LEFT:%.*]], <8 x half> [[COL_RIGHT:%.*]], i32 8, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_f16_8x4_3x3(global v8h* out, v8h acc, v10h weights, v8h col_center, v8h col_left, v8h col_right)
{
   *out = __builtin_amdgcn_convolve_f16_f16_8x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_bf16_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.bf16.3x3.v4f32.v4f32.v36bf16.v6bf16(<4 x float> [[ACC:%.*]], <36 x bfloat> [[WEIGHTS:%.*]], <6 x bfloat> [[COL_CENTER:%.*]], <6 x bfloat> [[COL_LEFT:%.*]], <6 x bfloat> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_bf16_4x2_3x3(global v4f* out, v4f acc, v36bf16 weights, v6bf16 col_center, v6bf16 col_left, v6bf16 col_right)
{
   *out = __builtin_amdgcn_convolve_f32_bf16_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x2_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x bfloat> @llvm.amdgcn.convolve.bf16.bf16.3x3.v4bf16.v4bf16.v36bf16.v6bf16(<4 x bfloat> [[ACC:%.*]], <36 x bfloat> [[WEIGHTS:%.*]], <6 x bfloat> [[COL_CENTER:%.*]], <6 x bfloat> [[COL_LEFT:%.*]], <6 x bfloat> [[COL_RIGHT:%.*]], i32 11, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x2_3x3(global v4bf16* out, v4bf16 acc, v36bf16 weights, v6bf16 col_center, v6bf16 col_left, v6bf16 col_right)
{
   *out = __builtin_amdgcn_convolve_bf16_bf16_4x2(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x bfloat> @llvm.amdgcn.convolve.bf16.bf16.3x3.v8bf16.v8bf16.v18bf16.v6bf16(<8 x bfloat> [[ACC:%.*]], <18 x bfloat> [[WEIGHTS:%.*]], <6 x bfloat> [[COL_CENTER:%.*]], <6 x bfloat> [[COL_LEFT:%.*]], <6 x bfloat> [[COL_RIGHT:%.*]], i32 10, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x4_3x3(global v8bf16* out, v8bf16 acc, v18bf16 weights, v6bf16 col_center, v6bf16 col_left, v6bf16 col_right)
{
   *out = __builtin_amdgcn_convolve_bf16_bf16_4x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_8x4_3x3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x bfloat> @llvm.amdgcn.convolve.bf16.bf16.3x3.v8bf16.v8bf16.v10bf16.v8bf16(<8 x bfloat> [[ACC:%.*]], <10 x bfloat> [[WEIGHTS:%.*]], <8 x bfloat> [[COL_CENTER:%.*]], <8 x bfloat> [[COL_LEFT:%.*]], <8 x bfloat> [[COL_RIGHT:%.*]], i32 8, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_8x4_3x3(global v8bf16* out, v8bf16 acc, v10bf16 weights, v8bf16 col_center, v8bf16 col_left, v8bf16 col_right)
{
   *out = __builtin_amdgcn_convolve_bf16_bf16_8x4(acc, weights, col_center, col_left, col_right, CONV_FILTER_3x3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_iu4_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.iu4.1x1.v4f32.v4f32.v2i32.i32(<4 x float> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_iu4_4x2_1x1_iter_1(global v4f* out, v4f acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f32_iu4_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.iu4.1x1.v4f16.v4f16.v2i32.i32(<4 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x2_1x1_iter_1(global v4h* out, v4h acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_iu4_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu4.1x1.v8f16.v8f16.i32.i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 2, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x4_1x1_iter_1(global v8h* out, v8h acc, int weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_iu4_4x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu4_8x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu4.1x1.v8f16.v8f16.i32.v2i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> undef, <2 x i32> undef, <2 x i32> undef, i32 0, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu4_8x4_1x1_iter_1(global v8h* out, v8h acc, int weights, v2i ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_iu4_8x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_i32_iu4_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.convolve.i32.iu4.1x1.v4i32.v4i32.v2i32.i32(<4 x i32> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_i32_iu4_4x2_1x1_iter_1(global v4i* out, v4i acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_i32_iu4_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32i32_iu4_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32i32.iu4.1x1.v4f32.v4i32.v2i32.i32(<4 x i32> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32i32_iu4_4x2_1x1_iter_1(global v4f* out, v4i acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f32i32_iu4_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_iu4_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.iu4.1x1.v4f32.v4f32.v4i32.i32(<4 x float> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_iu4_4x2_1x1_iter_2(global v4f* out, v4f acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f32_iu4_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.iu4.1x1.v4f16.v4f16.v4i32.i32(<4 x half> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x2_1x1_iter_2(global v4h* out, v4h acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_iu4_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu4.1x1.v8f16.v8f16.v2i32.i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4098, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x4_1x1_iter_2(global v8h* out, v8h acc, v2i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_iu4_4x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu4_8x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu4.1x1.v8f16.v8f16.i32.v2i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> undef, <2 x i32> undef, i32 4096, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu4_8x4_1x1_iter_2(global v8h* out, v8h acc, int weights, v2i ten_it0, v2i ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_iu4_8x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_i32_iu4_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.convolve.i32.iu4.1x1.v4i32.v4i32.v4i32.i32(<4 x i32> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_i32_iu4_4x2_1x1_iter_2(global v4i* out, v4i acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_i32_iu4_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32i32_iu4_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32i32.iu4.1x1.v4f32.v4i32.v4i32.i32(<4 x i32> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32i32_iu4_4x2_1x1_iter_2(global v4f* out, v4i acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f32i32_iu4_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_iu4_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.iu4.1x1.v4f32.v4f32.v6i32.i32(<4 x float> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_iu4_4x2_1x1_iter_3(global v4f* out, v4f acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f32_iu4_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.iu4.1x1.v4f16.v4f16.v6i32.i32(<4 x half> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x2_1x1_iter_3(global v4h* out, v4h acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_iu4_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu4.1x1.v8f16.v8f16.v3i32.i32(<8 x half> [[ACC:%.*]], <3 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8194, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x4_1x1_iter_3(global v8h* out, v8h acc, v3i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_iu4_4x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu4_8x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu4.1x1.v8f16.v8f16.v2i32.v2i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> [[TEN_IT2:%.*]], <2 x i32> undef, i32 8192, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu4_8x4_1x1_iter_3(global v8h* out, v8h acc, v2i weights, v2i ten_it0, v2i ten_it1, v2i ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_iu4_8x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_i32_iu4_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.convolve.i32.iu4.1x1.v4i32.v4i32.v6i32.i32(<4 x i32> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_i32_iu4_4x2_1x1_iter_3(global v4i* out, v4i acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_i32_iu4_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32i32_iu4_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32i32.iu4.1x1.v4f32.v4i32.v6i32.i32(<4 x i32> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32i32_iu4_4x2_1x1_iter_3(global v4f* out, v4i acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f32i32_iu4_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_iu4_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.iu4.1x1.v4f32.v4f32.v8i32.i32(<4 x float> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_iu4_4x2_1x1_iter_4(global v4f* out, v4f acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f32_iu4_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.iu4.1x1.v4f16.v4f16.v8i32.i32(<4 x half> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x2_1x1_iter_4(global v4h* out, v4h acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_iu4_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu4.1x1.v8f16.v8f16.v4i32.i32(<8 x half> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12290, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu4_4x4_1x1_iter_4(global v8h* out, v8h acc, v4i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_iu4_4x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu4_8x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu4.1x1.v8f16.v8f16.v2i32.v2i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> [[TEN_IT2:%.*]], <2 x i32> [[TEN_IT3:%.*]], i32 12288, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu4_8x4_1x1_iter_4(global v8h* out, v8h acc, v2i weights, v2i ten_it0, v2i ten_it1, v2i ten_it2, v2i ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_iu4_8x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_i32_iu4_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.convolve.i32.iu4.1x1.v4i32.v4i32.v8i32.i32(<4 x i32> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_i32_iu4_4x2_1x1_iter_4(global v4i* out, v4i acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_i32_iu4_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32i32_iu4_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32i32.iu4.1x1.v4f32.v4i32.v8i32.i32(<4 x i32> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32i32_iu4_4x2_1x1_iter_4(global v4f* out, v4i acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f32i32_iu4_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_iu8_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.iu8.1x1.v4f32.v4f32.v2i32.i32(<4 x float> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_iu8_4x2_1x1_iter_1(global v4f* out, v4f acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f32_iu8_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.iu8.1x1.v4f16.v4f16.v2i32.i32(<4 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x2_1x1_iter_1(global v4h* out, v4h acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_iu8_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu8.1x1.v8f16.v8f16.i32.i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 2, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x4_1x1_iter_1(global v8h* out, v8h acc, int weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_iu8_4x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu8_8x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu8.1x1.v8f16.v8f16.i32.v2i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> undef, <2 x i32> undef, <2 x i32> undef, i32 0, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu8_8x4_1x1_iter_1(global v8h* out, v8h acc, int weights, v2i ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_iu8_8x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_i32_iu8_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.convolve.i32.iu8.1x1.v4i32.v4i32.v2i32.i32(<4 x i32> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_i32_iu8_4x2_1x1_iter_1(global v4i* out, v4i acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_i32_iu8_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32i32_iu8_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32i32.iu8.1x1.v4f32.v4i32.v2i32.i32(<4 x i32> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32i32_iu8_4x2_1x1_iter_1(global v4f* out, v4i acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f32i32_iu8_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_iu8_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.iu8.1x1.v4f32.v4f32.v4i32.i32(<4 x float> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_iu8_4x2_1x1_iter_2(global v4f* out, v4f acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f32_iu8_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.iu8.1x1.v4f16.v4f16.v4i32.i32(<4 x half> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x2_1x1_iter_2(global v4h* out, v4h acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_iu8_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu8.1x1.v8f16.v8f16.v2i32.i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4098, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x4_1x1_iter_2(global v8h* out, v8h acc, v2i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_iu8_4x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu8_8x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu8.1x1.v8f16.v8f16.i32.v2i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> undef, <2 x i32> undef, i32 4096, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu8_8x4_1x1_iter_2(global v8h* out, v8h acc, int weights, v2i ten_it0, v2i ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_iu8_8x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_i32_iu8_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.convolve.i32.iu8.1x1.v4i32.v4i32.v4i32.i32(<4 x i32> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_i32_iu8_4x2_1x1_iter_2(global v4i* out, v4i acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_i32_iu8_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32i32_iu8_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32i32.iu8.1x1.v4f32.v4i32.v4i32.i32(<4 x i32> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32i32_iu8_4x2_1x1_iter_2(global v4f* out, v4i acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f32i32_iu8_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_iu8_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.iu8.1x1.v4f32.v4f32.v6i32.i32(<4 x float> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_iu8_4x2_1x1_iter_3(global v4f* out, v4f acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f32_iu8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.iu8.1x1.v4f16.v4f16.v6i32.i32(<4 x half> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x2_1x1_iter_3(global v4h* out, v4h acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_iu8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu8.1x1.v8f16.v8f16.v3i32.i32(<8 x half> [[ACC:%.*]], <3 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8194, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x4_1x1_iter_3(global v8h* out, v8h acc, v3i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_iu8_4x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu8_8x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu8.1x1.v8f16.v8f16.v2i32.v2i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> [[TEN_IT2:%.*]], <2 x i32> undef, i32 8192, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu8_8x4_1x1_iter_3(global v8h* out, v8h acc, v2i weights, v2i ten_it0, v2i ten_it1, v2i ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_iu8_8x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_i32_iu8_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.convolve.i32.iu8.1x1.v4i32.v4i32.v6i32.i32(<4 x i32> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_i32_iu8_4x2_1x1_iter_3(global v4i* out, v4i acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_i32_iu8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32i32_iu8_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32i32.iu8.1x1.v4f32.v4i32.v6i32.i32(<4 x i32> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32i32_iu8_4x2_1x1_iter_3(global v4f* out, v4i acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f32i32_iu8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_iu8_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.iu8.1x1.v4f32.v4f32.v8i32.i32(<4 x float> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_iu8_4x2_1x1_iter_4(global v4f* out, v4f acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f32_iu8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.iu8.1x1.v4f16.v4f16.v8i32.i32(<4 x half> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x2_1x1_iter_4(global v4h* out, v4h acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_iu8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu8.1x1.v8f16.v8f16.v4i32.i32(<8 x half> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12290, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu8_4x4_1x1_iter_4(global v8h* out, v8h acc, v4i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_iu8_4x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_iu8_8x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.iu8.1x1.v8f16.v8f16.v2i32.v2i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> [[TEN_IT2:%.*]], <2 x i32> [[TEN_IT3:%.*]], i32 12288, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_iu8_8x4_1x1_iter_4(global v8h* out, v8h acc, v2i weights, v2i ten_it0, v2i ten_it1, v2i ten_it2, v2i ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_iu8_8x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_i32_iu8_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.convolve.i32.iu8.1x1.v4i32.v4i32.v8i32.i32(<4 x i32> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_i32_iu8_4x2_1x1_iter_4(global v4i* out, v4i acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_i32_iu8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32i32_iu8_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32i32.iu8.1x1.v4f32.v4i32.v8i32.i32(<4 x i32> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32i32_iu8_4x2_1x1_iter_4(global v4f* out, v4i acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f32i32_iu8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_fp8_fp8_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.fp8.fp8.1x1.v4f32.v4f32.v2i32.i32(<4 x float> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_fp8_fp8_4x2_1x1_iter_1(global v4f* out, v4f acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f32_fp8_fp8_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.1x1.v4f16.v4f16.v2i32.i32(<4 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x2_1x1_iter_1(global v4h* out, v4h acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_fp8_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.1x1.v8f16.v8f16.i32.i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 2, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x4_1x1_iter_1(global v8h* out, v8h acc, int weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_fp8_4x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_8x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.1x1.v8f16.v8f16.i32.v2i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> undef, <2 x i32> undef, <2 x i32> undef, i32 0, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_8x4_1x1_iter_1(global v8h* out, v8h acc, int weights, v2i ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_fp8_8x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_fp8_fp8_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.fp8.fp8.1x1.v4f32.v4f32.v4i32.i32(<4 x float> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_fp8_fp8_4x2_1x1_iter_2(global v4f* out, v4f acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f32_fp8_fp8_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.1x1.v4f16.v4f16.v4i32.i32(<4 x half> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x2_1x1_iter_2(global v4h* out, v4h acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_fp8_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.1x1.v8f16.v8f16.v2i32.i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4098, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x4_1x1_iter_2(global v8h* out, v8h acc, v2i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_fp8_4x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_8x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.1x1.v8f16.v8f16.i32.v2i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> undef, <2 x i32> undef, i32 4096, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_8x4_1x1_iter_2(global v8h* out, v8h acc, int weights, v2i ten_it0, v2i ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_fp8_8x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_fp8_fp8_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.fp8.fp8.1x1.v4f32.v4f32.v6i32.i32(<4 x float> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_fp8_fp8_4x2_1x1_iter_3(global v4f* out, v4f acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f32_fp8_fp8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.1x1.v4f16.v4f16.v6i32.i32(<4 x half> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x2_1x1_iter_3(global v4h* out, v4h acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_fp8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.1x1.v8f16.v8f16.v3i32.i32(<8 x half> [[ACC:%.*]], <3 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8194, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x4_1x1_iter_3(global v8h* out, v8h acc, v3i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_fp8_4x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_8x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.1x1.v8f16.v8f16.v2i32.v2i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> [[TEN_IT2:%.*]], <2 x i32> undef, i32 8192, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_8x4_1x1_iter_3(global v8h* out, v8h acc, v2i weights, v2i ten_it0, v2i ten_it1, v2i ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_fp8_8x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_fp8_fp8_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.fp8.fp8.1x1.v4f32.v4f32.v8i32.i32(<4 x float> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_fp8_fp8_4x2_1x1_iter_4(global v4f* out, v4f acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f32_fp8_fp8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.1x1.v4f16.v4f16.v8i32.i32(<4 x half> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x2_1x1_iter_4(global v4h* out, v4h acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_fp8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.1x1.v8f16.v8f16.v4i32.i32(<8 x half> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12290, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_4x4_1x1_iter_4(global v8h* out, v8h acc, v4i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_fp8_4x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_8x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.1x1.v8f16.v8f16.v2i32.v2i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> [[TEN_IT2:%.*]], <2 x i32> [[TEN_IT3:%.*]], i32 12288, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_fp8_8x4_1x1_iter_4(global v8h* out, v8h acc, v2i weights, v2i ten_it0, v2i ten_it1, v2i ten_it2, v2i ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_fp8_8x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_fp8_bf8_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.fp8.bf8.1x1.v4f32.v4f32.v2i32.i32(<4 x float> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_fp8_bf8_4x2_1x1_iter_1(global v4f* out, v4f acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f32_fp8_bf8_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.fp8.bf8.1x1.v4f16.v4f16.v2i32.i32(<4 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x2_1x1_iter_1(global v4h* out, v4h acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_bf8_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.bf8.1x1.v8f16.v8f16.i32.i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 2, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x4_1x1_iter_1(global v8h* out, v8h acc, int weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_bf8_4x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_8x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.bf8.1x1.v8f16.v8f16.i32.v2i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> undef, <2 x i32> undef, <2 x i32> undef, i32 0, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_8x4_1x1_iter_1(global v8h* out, v8h acc, int weights, v2i ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_bf8_8x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_fp8_bf8_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.fp8.bf8.1x1.v4f32.v4f32.v4i32.i32(<4 x float> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_fp8_bf8_4x2_1x1_iter_2(global v4f* out, v4f acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f32_fp8_bf8_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.fp8.bf8.1x1.v4f16.v4f16.v4i32.i32(<4 x half> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x2_1x1_iter_2(global v4h* out, v4h acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_bf8_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.bf8.1x1.v8f16.v8f16.v2i32.i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4098, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x4_1x1_iter_2(global v8h* out, v8h acc, v2i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_bf8_4x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_8x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.bf8.1x1.v8f16.v8f16.i32.v2i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> undef, <2 x i32> undef, i32 4096, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_8x4_1x1_iter_2(global v8h* out, v8h acc, int weights, v2i ten_it0, v2i ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_bf8_8x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_fp8_bf8_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.fp8.bf8.1x1.v4f32.v4f32.v6i32.i32(<4 x float> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_fp8_bf8_4x2_1x1_iter_3(global v4f* out, v4f acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f32_fp8_bf8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.fp8.bf8.1x1.v4f16.v4f16.v6i32.i32(<4 x half> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x2_1x1_iter_3(global v4h* out, v4h acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_bf8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.bf8.1x1.v8f16.v8f16.v3i32.i32(<8 x half> [[ACC:%.*]], <3 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8194, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x4_1x1_iter_3(global v8h* out, v8h acc, v3i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_bf8_4x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_8x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.bf8.1x1.v8f16.v8f16.v2i32.v2i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> [[TEN_IT2:%.*]], <2 x i32> undef, i32 8192, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_8x4_1x1_iter_3(global v8h* out, v8h acc, v2i weights, v2i ten_it0, v2i ten_it1, v2i ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_bf8_8x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_fp8_bf8_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.fp8.bf8.1x1.v4f32.v4f32.v8i32.i32(<4 x float> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_fp8_bf8_4x2_1x1_iter_4(global v4f* out, v4f acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f32_fp8_bf8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.fp8.bf8.1x1.v4f16.v4f16.v8i32.i32(<4 x half> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x2_1x1_iter_4(global v4h* out, v4h acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_bf8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.bf8.1x1.v8f16.v8f16.v4i32.i32(<8 x half> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12290, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_4x4_1x1_iter_4(global v8h* out, v8h acc, v4i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_bf8_4x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_8x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.fp8.bf8.1x1.v8f16.v8f16.v2i32.v2i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> [[TEN_IT2:%.*]], <2 x i32> [[TEN_IT3:%.*]], i32 12288, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_fp8_bf8_8x4_1x1_iter_4(global v8h* out, v8h acc, v2i weights, v2i ten_it0, v2i ten_it1, v2i ten_it2, v2i ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_fp8_bf8_8x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_bf8_fp8_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.bf8.fp8.1x1.v4f32.v4f32.v2i32.i32(<4 x float> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_bf8_fp8_4x2_1x1_iter_1(global v4f* out, v4f acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f32_bf8_fp8_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.bf8.fp8.1x1.v4f16.v4f16.v2i32.i32(<4 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x2_1x1_iter_1(global v4h* out, v4h acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_fp8_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.fp8.1x1.v8f16.v8f16.i32.i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 2, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x4_1x1_iter_1(global v8h* out, v8h acc, int weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_fp8_4x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_8x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.fp8.1x1.v8f16.v8f16.i32.v2i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> undef, <2 x i32> undef, <2 x i32> undef, i32 0, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_8x4_1x1_iter_1(global v8h* out, v8h acc, int weights, v2i ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_fp8_8x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_bf8_fp8_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.bf8.fp8.1x1.v4f32.v4f32.v4i32.i32(<4 x float> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_bf8_fp8_4x2_1x1_iter_2(global v4f* out, v4f acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f32_bf8_fp8_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.bf8.fp8.1x1.v4f16.v4f16.v4i32.i32(<4 x half> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x2_1x1_iter_2(global v4h* out, v4h acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_fp8_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.fp8.1x1.v8f16.v8f16.v2i32.i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4098, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x4_1x1_iter_2(global v8h* out, v8h acc, v2i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_fp8_4x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_8x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.fp8.1x1.v8f16.v8f16.i32.v2i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> undef, <2 x i32> undef, i32 4096, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_8x4_1x1_iter_2(global v8h* out, v8h acc, int weights, v2i ten_it0, v2i ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_fp8_8x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_bf8_fp8_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.bf8.fp8.1x1.v4f32.v4f32.v6i32.i32(<4 x float> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_bf8_fp8_4x2_1x1_iter_3(global v4f* out, v4f acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f32_bf8_fp8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.bf8.fp8.1x1.v4f16.v4f16.v6i32.i32(<4 x half> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x2_1x1_iter_3(global v4h* out, v4h acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_fp8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.fp8.1x1.v8f16.v8f16.v3i32.i32(<8 x half> [[ACC:%.*]], <3 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8194, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x4_1x1_iter_3(global v8h* out, v8h acc, v3i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_fp8_4x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_8x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.fp8.1x1.v8f16.v8f16.v2i32.v2i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> [[TEN_IT2:%.*]], <2 x i32> undef, i32 8192, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_8x4_1x1_iter_3(global v8h* out, v8h acc, v2i weights, v2i ten_it0, v2i ten_it1, v2i ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_fp8_8x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_bf8_fp8_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.bf8.fp8.1x1.v4f32.v4f32.v8i32.i32(<4 x float> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_bf8_fp8_4x2_1x1_iter_4(global v4f* out, v4f acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f32_bf8_fp8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.bf8.fp8.1x1.v4f16.v4f16.v8i32.i32(<4 x half> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x2_1x1_iter_4(global v4h* out, v4h acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_fp8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.fp8.1x1.v8f16.v8f16.v4i32.i32(<8 x half> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12290, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_4x4_1x1_iter_4(global v8h* out, v8h acc, v4i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_fp8_4x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_8x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.fp8.1x1.v8f16.v8f16.v2i32.v2i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> [[TEN_IT2:%.*]], <2 x i32> [[TEN_IT3:%.*]], i32 12288, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_fp8_8x4_1x1_iter_4(global v8h* out, v8h acc, v2i weights, v2i ten_it0, v2i ten_it1, v2i ten_it2, v2i ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_fp8_8x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_bf8_bf8_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.bf8.bf8.1x1.v4f32.v4f32.v2i32.i32(<4 x float> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_bf8_bf8_4x2_1x1_iter_1(global v4f* out, v4f acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f32_bf8_bf8_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.bf8.bf8.1x1.v4f16.v4f16.v2i32.i32(<4 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x2_1x1_iter_1(global v4h* out, v4h acc, v2i weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_bf8_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.bf8.1x1.v8f16.v8f16.i32.i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 undef, i32 undef, i32 undef, i32 2, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x4_1x1_iter_1(global v8h* out, v8h acc, int weights, int ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_bf8_4x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_8x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.bf8.1x1.v8f16.v8f16.i32.v2i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> undef, <2 x i32> undef, <2 x i32> undef, i32 0, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_8x4_1x1_iter_1(global v8h* out, v8h acc, int weights, v2i ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_bf8_8x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_bf8_bf8_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.bf8.bf8.1x1.v4f32.v4f32.v4i32.i32(<4 x float> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_bf8_bf8_4x2_1x1_iter_2(global v4f* out, v4f acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f32_bf8_bf8_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.bf8.bf8.1x1.v4f16.v4f16.v4i32.i32(<4 x half> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x2_1x1_iter_2(global v4h* out, v4h acc, v4i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_bf8_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.bf8.1x1.v8f16.v8f16.v2i32.i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 undef, i32 undef, i32 4098, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x4_1x1_iter_2(global v8h* out, v8h acc, v2i weights, int ten_it0, int ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_bf8_4x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_8x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.bf8.1x1.v8f16.v8f16.i32.v2i32(<8 x half> [[ACC:%.*]], i32 [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> undef, <2 x i32> undef, i32 4096, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_8x4_1x1_iter_2(global v8h* out, v8h acc, int weights, v2i ten_it0, v2i ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_bf8_8x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_bf8_bf8_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.bf8.bf8.1x1.v4f32.v4f32.v6i32.i32(<4 x float> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_bf8_bf8_4x2_1x1_iter_3(global v4f* out, v4f acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f32_bf8_bf8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.bf8.bf8.1x1.v4f16.v4f16.v6i32.i32(<4 x half> [[ACC:%.*]], <6 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x2_1x1_iter_3(global v4h* out, v4h acc, v6i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_bf8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.bf8.1x1.v8f16.v8f16.v3i32.i32(<8 x half> [[ACC:%.*]], <3 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 undef, i32 8194, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x4_1x1_iter_3(global v8h* out, v8h acc, v3i weights, int ten_it0, int ten_it1, int ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_bf8_4x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_8x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.bf8.1x1.v8f16.v8f16.v2i32.v2i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> [[TEN_IT2:%.*]], <2 x i32> undef, i32 8192, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_8x4_1x1_iter_3(global v8h* out, v8h acc, v2i weights, v2i ten_it0, v2i ten_it1, v2i ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_bf8_8x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_bf8_bf8_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.bf8.bf8.1x1.v4f32.v4f32.v8i32.i32(<4 x float> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_bf8_bf8_4x2_1x1_iter_4(global v4f* out, v4f acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f32_bf8_bf8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.bf8.bf8.1x1.v4f16.v4f16.v8i32.i32(<4 x half> [[ACC:%.*]], <8 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x2_1x1_iter_4(global v4h* out, v4h acc, v8i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_bf8_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.bf8.1x1.v8f16.v8f16.v4i32.i32(<8 x half> [[ACC:%.*]], <4 x i32> [[WEIGHTS:%.*]], i32 [[TEN_IT0:%.*]], i32 [[TEN_IT1:%.*]], i32 [[TEN_IT2:%.*]], i32 [[TEN_IT3:%.*]], i32 12290, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_4x4_1x1_iter_4(global v8h* out, v8h acc, v4i weights, int ten_it0, int ten_it1, int ten_it2, int ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_bf8_4x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_8x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.bf8.bf8.1x1.v8f16.v8f16.v2i32.v2i32(<8 x half> [[ACC:%.*]], <2 x i32> [[WEIGHTS:%.*]], <2 x i32> [[TEN_IT0:%.*]], <2 x i32> [[TEN_IT1:%.*]], <2 x i32> [[TEN_IT2:%.*]], <2 x i32> [[TEN_IT3:%.*]], i32 12288, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_bf8_bf8_8x4_1x1_iter_4(global v8h* out, v8h acc, v2i weights, v2i ten_it0, v2i ten_it1, v2i ten_it2, v2i ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_bf8_bf8_8x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_f16_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.f16.1x1.v4f32.v4f32.v4f16.v2f16(<4 x float> [[ACC:%.*]], <4 x half> [[WEIGHTS:%.*]], <2 x half> [[TEN_IT0:%.*]], <2 x half> undef, <2 x half> undef, <2 x half> undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_f16_4x2_1x1_iter_1(global v4f* out, v4f acc, v4h weights, v2h ten_it0)
{
   *out = __builtin_amdgcn_convolve_f32_f16_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.f16.1x1.v4f16.v4f16.v4f16.v2f16(<4 x half> [[ACC:%.*]], <4 x half> [[WEIGHTS:%.*]], <2 x half> [[TEN_IT0:%.*]], <2 x half> undef, <2 x half> undef, <2 x half> undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x2_1x1_iter_1(global v4h* out, v4h acc, v4h weights, v2h ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_f16_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.f16.1x1.v8f16.v8f16.v2f16.v2f16(<8 x half> [[ACC:%.*]], <2 x half> [[WEIGHTS:%.*]], <2 x half> [[TEN_IT0:%.*]], <2 x half> undef, <2 x half> undef, <2 x half> undef, i32 2, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x4_1x1_iter_1(global v8h* out, v8h acc, v2h weights, v2h ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_f16_4x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_f16_8x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.f16.1x1.v8f16.v8f16.v2f16.v4f16(<8 x half> [[ACC:%.*]], <2 x half> [[WEIGHTS:%.*]], <4 x half> [[TEN_IT0:%.*]], <4 x half> undef, <4 x half> undef, <4 x half> undef, i32 0, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_f16_8x4_1x1_iter_1(global v8h* out, v8h acc, v2h weights, v4h ten_it0)
{
   *out = __builtin_amdgcn_convolve_f16_f16_8x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_f16_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.f16.1x1.v4f32.v4f32.v8f16.v2f16(<4 x float> [[ACC:%.*]], <8 x half> [[WEIGHTS:%.*]], <2 x half> [[TEN_IT0:%.*]], <2 x half> [[TEN_IT1:%.*]], <2 x half> undef, <2 x half> undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_f16_4x2_1x1_iter_2(global v4f* out, v4f acc, v8h weights, v2h ten_it0, v2h ten_it1)
{
   *out = __builtin_amdgcn_convolve_f32_f16_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.f16.1x1.v4f16.v4f16.v8f16.v2f16(<4 x half> [[ACC:%.*]], <8 x half> [[WEIGHTS:%.*]], <2 x half> [[TEN_IT0:%.*]], <2 x half> [[TEN_IT1:%.*]], <2 x half> undef, <2 x half> undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x2_1x1_iter_2(global v4h* out, v4h acc, v8h weights, v2h ten_it0, v2h ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_f16_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.f16.1x1.v8f16.v8f16.v4f16.v2f16(<8 x half> [[ACC:%.*]], <4 x half> [[WEIGHTS:%.*]], <2 x half> [[TEN_IT0:%.*]], <2 x half> [[TEN_IT1:%.*]], <2 x half> undef, <2 x half> undef, i32 4098, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x4_1x1_iter_2(global v8h* out, v8h acc, v4h weights, v2h ten_it0, v2h ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_f16_4x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_f16_8x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.f16.1x1.v8f16.v8f16.v2f16.v4f16(<8 x half> [[ACC:%.*]], <2 x half> [[WEIGHTS:%.*]], <4 x half> [[TEN_IT0:%.*]], <4 x half> [[TEN_IT1:%.*]], <4 x half> undef, <4 x half> undef, i32 4096, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_f16_8x4_1x1_iter_2(global v8h* out, v8h acc, v2h weights, v4h ten_it0, v4h ten_it1)
{
   *out = __builtin_amdgcn_convolve_f16_f16_8x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_f16_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = shufflevector <12 x half> [[WEIGHTS:%.*]], <12 x half> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-GFX1300-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.f16.1x1.v4f32.v4f32.v16f16.v2f16(<4 x float> [[ACC:%.*]], <16 x half> [[TMP0]], <2 x half> [[TEN_IT0:%.*]], <2 x half> [[TEN_IT1:%.*]], <2 x half> [[TEN_IT2:%.*]], <2 x half> undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP1]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_f16_4x2_1x1_iter_3(global v4f* out, v4f acc, v12h weights, v2h ten_it0, v2h ten_it1, v2h ten_it2)
{
   *out = __builtin_amdgcn_convolve_f32_f16_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = shufflevector <12 x half> [[WEIGHTS:%.*]], <12 x half> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-GFX1300-NEXT:    [[TMP1:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.f16.1x1.v4f16.v4f16.v16f16.v2f16(<4 x half> [[ACC:%.*]], <16 x half> [[TMP0]], <2 x half> [[TEN_IT0:%.*]], <2 x half> [[TEN_IT1:%.*]], <2 x half> [[TEN_IT2:%.*]], <2 x half> undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP1]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x2_1x1_iter_3(global v4h* out, v4h acc, v12h weights, v2h ten_it0, v2h ten_it1, v2h ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_f16_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.f16.1x1.v8f16.v8f16.v6f16.v2f16(<8 x half> [[ACC:%.*]], <6 x half> [[WEIGHTS:%.*]], <2 x half> [[TEN_IT0:%.*]], <2 x half> [[TEN_IT1:%.*]], <2 x half> [[TEN_IT2:%.*]], <2 x half> undef, i32 8194, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x4_1x1_iter_3(global v8h* out, v8h acc, v6h weights, v2h ten_it0, v2h ten_it1, v2h ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_f16_4x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_f16_8x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.f16.1x1.v8f16.v8f16.v4f16.v4f16(<8 x half> [[ACC:%.*]], <4 x half> [[WEIGHTS:%.*]], <4 x half> [[TEN_IT0:%.*]], <4 x half> [[TEN_IT1:%.*]], <4 x half> [[TEN_IT2:%.*]], <4 x half> undef, i32 8192, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_f16_8x4_1x1_iter_3(global v8h* out, v8h acc, v4h weights, v4h ten_it0, v4h ten_it1, v4h ten_it2)
{
   *out = __builtin_amdgcn_convolve_f16_f16_8x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_f16_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.f16.1x1.v4f32.v4f32.v16f16.v2f16(<4 x float> [[ACC:%.*]], <16 x half> [[WEIGHTS:%.*]], <2 x half> [[TEN_IT0:%.*]], <2 x half> [[TEN_IT1:%.*]], <2 x half> [[TEN_IT2:%.*]], <2 x half> [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_f16_4x2_1x1_iter_4(global v4f* out, v4f acc, v16h weights, v2h ten_it0, v2h ten_it1, v2h ten_it2, v2h ten_it3)
{
   *out = __builtin_amdgcn_convolve_f32_f16_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.amdgcn.convolve.f16.f16.1x1.v4f16.v4f16.v16f16.v2f16(<4 x half> [[ACC:%.*]], <16 x half> [[WEIGHTS:%.*]], <2 x half> [[TEN_IT0:%.*]], <2 x half> [[TEN_IT1:%.*]], <2 x half> [[TEN_IT2:%.*]], <2 x half> [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x2_1x1_iter_4(global v4h* out, v4h acc, v16h weights, v2h ten_it0, v2h ten_it1, v2h ten_it2, v2h ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_f16_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.f16.1x1.v8f16.v8f16.v8f16.v2f16(<8 x half> [[ACC:%.*]], <8 x half> [[WEIGHTS:%.*]], <2 x half> [[TEN_IT0:%.*]], <2 x half> [[TEN_IT1:%.*]], <2 x half> [[TEN_IT2:%.*]], <2 x half> [[TEN_IT3:%.*]], i32 12290, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_f16_4x4_1x1_iter_4(global v8h* out, v8h acc, v8h weights, v2h ten_it0, v2h ten_it1, v2h ten_it2, v2h ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_f16_4x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f16_f16_8x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.convolve.f16.f16.1x1.v8f16.v8f16.v4f16.v4f16(<8 x half> [[ACC:%.*]], <4 x half> [[WEIGHTS:%.*]], <4 x half> [[TEN_IT0:%.*]], <4 x half> [[TEN_IT1:%.*]], <4 x half> [[TEN_IT2:%.*]], <4 x half> [[TEN_IT3:%.*]], i32 12288, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f16_f16_8x4_1x1_iter_4(global v8h* out, v8h acc, v4h weights, v4h ten_it0, v4h ten_it1, v4h ten_it2, v4h ten_it3)
{
   *out = __builtin_amdgcn_convolve_f16_f16_8x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_bf16_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.bf16.1x1.v4f32.v4f32.v4bf16.v2bf16(<4 x float> [[ACC:%.*]], <4 x bfloat> [[WEIGHTS:%.*]], <2 x bfloat> [[TEN_IT0:%.*]], <2 x bfloat> undef, <2 x bfloat> undef, <2 x bfloat> undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_bf16_4x2_1x1_iter_1(global v4f* out, v4f acc, v4bf16 weights, v2bf16 ten_it0)
{
   *out = __builtin_amdgcn_convolve_f32_bf16_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x2_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x bfloat> @llvm.amdgcn.convolve.bf16.bf16.1x1.v4bf16.v4bf16.v4bf16.v2bf16(<4 x bfloat> [[ACC:%.*]], <4 x bfloat> [[WEIGHTS:%.*]], <2 x bfloat> [[TEN_IT0:%.*]], <2 x bfloat> undef, <2 x bfloat> undef, <2 x bfloat> undef, i32 3, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x2_1x1_iter_1(global v4bf16* out, v4bf16 acc, v4bf16 weights, v2bf16 ten_it0)
{
   *out = __builtin_amdgcn_convolve_bf16_bf16_4x2(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x bfloat> @llvm.amdgcn.convolve.bf16.bf16.1x1.v8bf16.v8bf16.v2bf16.v2bf16(<8 x bfloat> [[ACC:%.*]], <2 x bfloat> [[WEIGHTS:%.*]], <2 x bfloat> [[TEN_IT0:%.*]], <2 x bfloat> undef, <2 x bfloat> undef, <2 x bfloat> undef, i32 2, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x4_1x1_iter_1(global v8bf16* out, v8bf16 acc, v2bf16 weights, v2bf16 ten_it0)
{
   *out = __builtin_amdgcn_convolve_bf16_bf16_4x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_8x4_1x1_iter_1(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x bfloat> @llvm.amdgcn.convolve.bf16.bf16.1x1.v8bf16.v8bf16.v2bf16.v4bf16(<8 x bfloat> [[ACC:%.*]], <2 x bfloat> [[WEIGHTS:%.*]], <4 x bfloat> [[TEN_IT0:%.*]], <4 x bfloat> undef, <4 x bfloat> undef, <4 x bfloat> undef, i32 0, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_8x4_1x1_iter_1(global v8bf16* out, v8bf16 acc, v2bf16 weights, v4bf16 ten_it0)
{
   *out = __builtin_amdgcn_convolve_bf16_bf16_8x4(acc, weights, ten_it0, CONV_FILTER_1x1 | CONV_ITER_1, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_bf16_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.bf16.1x1.v4f32.v4f32.v8bf16.v2bf16(<4 x float> [[ACC:%.*]], <8 x bfloat> [[WEIGHTS:%.*]], <2 x bfloat> [[TEN_IT0:%.*]], <2 x bfloat> [[TEN_IT1:%.*]], <2 x bfloat> undef, <2 x bfloat> undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_bf16_4x2_1x1_iter_2(global v4f* out, v4f acc, v8bf16 weights, v2bf16 ten_it0, v2bf16 ten_it1)
{
   *out = __builtin_amdgcn_convolve_f32_bf16_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x2_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x bfloat> @llvm.amdgcn.convolve.bf16.bf16.1x1.v4bf16.v4bf16.v8bf16.v2bf16(<4 x bfloat> [[ACC:%.*]], <8 x bfloat> [[WEIGHTS:%.*]], <2 x bfloat> [[TEN_IT0:%.*]], <2 x bfloat> [[TEN_IT1:%.*]], <2 x bfloat> undef, <2 x bfloat> undef, i32 4099, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x2_1x1_iter_2(global v4bf16* out, v4bf16 acc, v8bf16 weights, v2bf16 ten_it0, v2bf16 ten_it1)
{
   *out = __builtin_amdgcn_convolve_bf16_bf16_4x2(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x bfloat> @llvm.amdgcn.convolve.bf16.bf16.1x1.v8bf16.v8bf16.v4bf16.v2bf16(<8 x bfloat> [[ACC:%.*]], <4 x bfloat> [[WEIGHTS:%.*]], <2 x bfloat> [[TEN_IT0:%.*]], <2 x bfloat> [[TEN_IT1:%.*]], <2 x bfloat> undef, <2 x bfloat> undef, i32 4098, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x4_1x1_iter_2(global v8bf16* out, v8bf16 acc, v4bf16 weights, v2bf16 ten_it0, v2bf16 ten_it1)
{
   *out = __builtin_amdgcn_convolve_bf16_bf16_4x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_8x4_1x1_iter_2(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x bfloat> @llvm.amdgcn.convolve.bf16.bf16.1x1.v8bf16.v8bf16.v2bf16.v4bf16(<8 x bfloat> [[ACC:%.*]], <2 x bfloat> [[WEIGHTS:%.*]], <4 x bfloat> [[TEN_IT0:%.*]], <4 x bfloat> [[TEN_IT1:%.*]], <4 x bfloat> undef, <4 x bfloat> undef, i32 4096, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_8x4_1x1_iter_2(global v8bf16* out, v8bf16 acc, v2bf16 weights, v4bf16 ten_it0, v4bf16 ten_it1)
{
   *out = __builtin_amdgcn_convolve_bf16_bf16_8x4(acc, weights, ten_it0, ten_it1, CONV_FILTER_1x1 | CONV_ITER_2, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_bf16_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = shufflevector <12 x bfloat> [[WEIGHTS:%.*]], <12 x bfloat> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-GFX1300-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.bf16.1x1.v4f32.v4f32.v16bf16.v2bf16(<4 x float> [[ACC:%.*]], <16 x bfloat> [[TMP0]], <2 x bfloat> [[TEN_IT0:%.*]], <2 x bfloat> [[TEN_IT1:%.*]], <2 x bfloat> [[TEN_IT2:%.*]], <2 x bfloat> undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP1]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_bf16_4x2_1x1_iter_3(global v4f* out, v4f acc, v12bf16 weights, v2bf16 ten_it0, v2bf16 ten_it1, v2bf16 ten_it2)
{
   *out = __builtin_amdgcn_convolve_f32_bf16_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x2_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = shufflevector <12 x bfloat> [[WEIGHTS:%.*]], <12 x bfloat> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-GFX1300-NEXT:    [[TMP1:%.*]] = tail call <4 x bfloat> @llvm.amdgcn.convolve.bf16.bf16.1x1.v4bf16.v4bf16.v16bf16.v2bf16(<4 x bfloat> [[ACC:%.*]], <16 x bfloat> [[TMP0]], <2 x bfloat> [[TEN_IT0:%.*]], <2 x bfloat> [[TEN_IT1:%.*]], <2 x bfloat> [[TEN_IT2:%.*]], <2 x bfloat> undef, i32 8195, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x bfloat> [[TMP1]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x2_1x1_iter_3(global v4bf16* out, v4bf16 acc, v12bf16 weights, v2bf16 ten_it0, v2bf16 ten_it1, v2bf16 ten_it2)
{
   *out = __builtin_amdgcn_convolve_bf16_bf16_4x2(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x bfloat> @llvm.amdgcn.convolve.bf16.bf16.1x1.v8bf16.v8bf16.v6bf16.v2bf16(<8 x bfloat> [[ACC:%.*]], <6 x bfloat> [[WEIGHTS:%.*]], <2 x bfloat> [[TEN_IT0:%.*]], <2 x bfloat> [[TEN_IT1:%.*]], <2 x bfloat> [[TEN_IT2:%.*]], <2 x bfloat> undef, i32 8194, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x4_1x1_iter_3(global v8bf16* out, v8bf16 acc, v6bf16 weights, v2bf16 ten_it0, v2bf16 ten_it1, v2bf16 ten_it2)
{
   *out = __builtin_amdgcn_convolve_bf16_bf16_4x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_8x4_1x1_iter_3(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x bfloat> @llvm.amdgcn.convolve.bf16.bf16.1x1.v8bf16.v8bf16.v4bf16.v4bf16(<8 x bfloat> [[ACC:%.*]], <4 x bfloat> [[WEIGHTS:%.*]], <4 x bfloat> [[TEN_IT0:%.*]], <4 x bfloat> [[TEN_IT1:%.*]], <4 x bfloat> [[TEN_IT2:%.*]], <4 x bfloat> undef, i32 8192, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_8x4_1x1_iter_3(global v8bf16* out, v8bf16 acc, v4bf16 weights, v4bf16 ten_it0, v4bf16 ten_it1, v4bf16 ten_it2)
{
   *out = __builtin_amdgcn_convolve_bf16_bf16_8x4(acc, weights, ten_it0, ten_it1, ten_it2, CONV_FILTER_1x1 | CONV_ITER_3, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_f32_bf16_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.amdgcn.convolve.f32.bf16.1x1.v4f32.v4f32.v16bf16.v2bf16(<4 x float> [[ACC:%.*]], <16 x bfloat> [[WEIGHTS:%.*]], <2 x bfloat> [[TEN_IT0:%.*]], <2 x bfloat> [[TEN_IT1:%.*]], <2 x bfloat> [[TEN_IT2:%.*]], <2 x bfloat> [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_f32_bf16_4x2_1x1_iter_4(global v4f* out, v4f acc, v16bf16 weights, v2bf16 ten_it0, v2bf16 ten_it1, v2bf16 ten_it2, v2bf16 ten_it3)
{
   *out = __builtin_amdgcn_convolve_f32_bf16_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x2_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <4 x bfloat> @llvm.amdgcn.convolve.bf16.bf16.1x1.v4bf16.v4bf16.v16bf16.v2bf16(<4 x bfloat> [[ACC:%.*]], <16 x bfloat> [[WEIGHTS:%.*]], <2 x bfloat> [[TEN_IT0:%.*]], <2 x bfloat> [[TEN_IT1:%.*]], <2 x bfloat> [[TEN_IT2:%.*]], <2 x bfloat> [[TEN_IT3:%.*]], i32 12291, i1 true)
// CHECK-GFX1300-NEXT:    store <4 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 8, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x2_1x1_iter_4(global v4bf16* out, v4bf16 acc, v16bf16 weights, v2bf16 ten_it0, v2bf16 ten_it1, v2bf16 ten_it2, v2bf16 ten_it3)
{
   *out = __builtin_amdgcn_convolve_bf16_bf16_4x2(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x bfloat> @llvm.amdgcn.convolve.bf16.bf16.1x1.v8bf16.v8bf16.v8bf16.v2bf16(<8 x bfloat> [[ACC:%.*]], <8 x bfloat> [[WEIGHTS:%.*]], <2 x bfloat> [[TEN_IT0:%.*]], <2 x bfloat> [[TEN_IT1:%.*]], <2 x bfloat> [[TEN_IT2:%.*]], <2 x bfloat> [[TEN_IT3:%.*]], i32 12290, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_4x4_1x1_iter_4(global v8bf16* out, v8bf16 acc, v8bf16 weights, v2bf16 ten_it0, v2bf16 ten_it1, v2bf16 ten_it2, v2bf16 ten_it3)
{
   *out = __builtin_amdgcn_convolve_bf16_bf16_4x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_8x4_1x1_iter_4(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x bfloat> @llvm.amdgcn.convolve.bf16.bf16.1x1.v8bf16.v8bf16.v4bf16.v4bf16(<8 x bfloat> [[ACC:%.*]], <4 x bfloat> [[WEIGHTS:%.*]], <4 x bfloat> [[TEN_IT0:%.*]], <4 x bfloat> [[TEN_IT1:%.*]], <4 x bfloat> [[TEN_IT2:%.*]], <4 x bfloat> [[TEN_IT3:%.*]], i32 12288, i1 true)
// CHECK-GFX1300-NEXT:    store <8 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_builtin_amdgcn_convolve_bf16_bf16_8x4_1x1_iter_4(global v8bf16* out, v8bf16 acc, v4bf16 weights, v4bf16 ten_it0, v4bf16 ten_it1, v4bf16 ten_it2, v4bf16 ten_it3)
{
   *out = __builtin_amdgcn_convolve_bf16_bf16_8x4(acc, weights, ten_it0, ten_it1, ten_it2, ten_it3, CONV_FILTER_1x1 | CONV_ITER_4, true);
}

