// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -cl-std=CL2.0 -triple amdgcn-unknown-unknown -target-cpu gfx1210 -emit-llvm -o - %s | FileCheck %s --check-prefix=CHECK-GFX1210

typedef int    v2i   __attribute__((ext_vector_type(2)));
typedef int    v4i   __attribute__((ext_vector_type(4)));

// CHECK-GFX1210-LABEL: @test_amdgcn_global_load_monitor_b32(
// CHECK-GFX1210-NEXT:  entry:
// CHECK-GFX1210-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.amdgcn.global.load.monitor.b32.i32(ptr addrspace(1) [[INPTR:%.*]], i32 1)
// CHECK-GFX1210-NEXT:    ret i32 [[TMP0]]
//
int test_amdgcn_global_load_monitor_b32(global int* inptr)
{
  return __builtin_amdgcn_global_load_monitor_b32(inptr, 1);
}

// CHECK-GFX1210-LABEL: @test_amdgcn_global_load_monitor_b64(
// CHECK-GFX1210-NEXT:  entry:
// CHECK-GFX1210-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.amdgcn.global.load.monitor.b64.v2i32(ptr addrspace(1) [[INPTR:%.*]], i32 10)
// CHECK-GFX1210-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i test_amdgcn_global_load_monitor_b64(global v2i* inptr)
{
  return __builtin_amdgcn_global_load_monitor_b64(inptr, 10);
}

// CHECK-GFX1210-LABEL: @test_amdgcn_global_load_monitor_b128(
// CHECK-GFX1210-NEXT:  entry:
// CHECK-GFX1210-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.global.load.monitor.b128.v4i32(ptr addrspace(1) [[INPTR:%.*]], i32 22)
// CHECK-GFX1210-NEXT:    ret <4 x i32> [[TMP0]]
//
v4i test_amdgcn_global_load_monitor_b128(global v4i* inptr)
{
  return __builtin_amdgcn_global_load_monitor_b128(inptr, 22);
}

// CHECK-GFX1210-LABEL: @test_amdgcn_flat_load_monitor_b32(
// CHECK-GFX1210-NEXT:  entry:
// CHECK-GFX1210-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.amdgcn.flat.load.monitor.b32.i32(ptr [[INPTR:%.*]], i32 27)
// CHECK-GFX1210-NEXT:    ret i32 [[TMP0]]
//
int test_amdgcn_flat_load_monitor_b32(int* inptr)
{
  return __builtin_amdgcn_flat_load_monitor_b32(inptr, 27);
}

// CHECK-GFX1210-LABEL: @test_amdgcn_flat_load_monitor_b64(
// CHECK-GFX1210-NEXT:  entry:
// CHECK-GFX1210-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.amdgcn.flat.load.monitor.b64.v2i32(ptr [[INPTR:%.*]], i32 1)
// CHECK-GFX1210-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i test_amdgcn_flat_load_monitor_b64(v2i* inptr)
{
  return __builtin_amdgcn_flat_load_monitor_b64(inptr, 1);
}

// CHECK-GFX1210-LABEL: @test_amdgcn_flat_load_monitor_b128(
// CHECK-GFX1210-NEXT:  entry:
// CHECK-GFX1210-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.flat.load.monitor.b128.v4i32(ptr [[INPTR:%.*]], i32 0)
// CHECK-GFX1210-NEXT:    ret <4 x i32> [[TMP0]]
//
v4i test_amdgcn_flat_load_monitor_b128(v4i* inptr)
{
  return __builtin_amdgcn_flat_load_monitor_b128(inptr, 0);
}
