// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu gfx1300 -target-feature +wavefrontsize32 -emit-llvm -o - %s | FileCheck %s --check-prefix=CHECK-GFX1300

typedef int    v2i   __attribute__((ext_vector_type(2)));
typedef int    v4i   __attribute__((ext_vector_type(4)));
typedef float  v8f   __attribute__((ext_vector_type(8)));
typedef half   v8h   __attribute__((ext_vector_type(8)));
typedef short  v8s   __attribute__((ext_vector_type(8)));
typedef int    v8i   __attribute__((ext_vector_type(8)));
typedef __bf16 v8bf16 __attribute__((ext_vector_type(8)));

// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32_16x16x16_iu8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.iu8.clamp(i1 true, <2 x i32> [[A:%.*]], i1 true, <2 x i32> [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4:![0-9]+]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x16_iu8_gfx13(global v8f* out, v2i a, v2i b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x16_iu8_clamp(1, a, 1, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32i32_16x16x16_iu8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32i32.16x16x16.iu8.clamp(i1 true, <2 x i32> [[A:%.*]], i1 true, <2 x i32> [[B:%.*]], <8 x i32> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32i32_16x16x16_iu8_gfx13(global v8f* out, v2i a, v2i b, v8i c)
{
   *out = __builtin_amdgcn_wmma_f32i32_16x16x16_iu8_clamp(1, a, 1, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_i32_16x16x16_iu8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x i32> @llvm.amdgcn.wmma.i32.16x16x16.iu8.clamp(i1 true, <2 x i32> [[A:%.*]], i1 true, <2 x i32> [[B:%.*]], <8 x i32> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_i32_16x16x16_iu8_gfx13(global v8i* out, v2i a, v2i b, v8i c)
{
   *out = __builtin_amdgcn_wmma_i32_16x16x16_iu8_clamp(1, a, 1, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32_16x16x16_iu4_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.iu4.clamp(i1 true, i32 [[A:%.*]], i1 true, i32 [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x16_iu4_gfx13(global v8f* out, int a, int b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x16_iu4_clamp(1, a, 1, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32i32_16x16x16_iu4_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32i32.16x16x16.iu4.clamp(i1 true, i32 [[A:%.*]], i1 true, i32 [[B:%.*]], <8 x i32> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32i32_16x16x16_iu4_gfx13(global v8f* out, int a, int b, v8i c)
{
   *out = __builtin_amdgcn_wmma_f32i32_16x16x16_iu4_clamp(1, a, 1, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_i32_16x16x16_iu4_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x i32> @llvm.amdgcn.wmma.i32.16x16x16.iu4.clamp(i1 true, i32 [[A:%.*]], i1 true, i32 [[B:%.*]], <8 x i32> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_i32_16x16x16_iu4_gfx13(global v8i* out, int a, int b, v8i c)
{
   *out = __builtin_amdgcn_wmma_i32_16x16x16_iu4_clamp(1, a, 1, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32_16x16x32_iu8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x32.iu8.clamp(i1 true, <4 x i32> [[A:%.*]], i1 true, <4 x i32> [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x32_iu8_gfx13(global v8f* out, v4i a, v4i b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x32_iu8_clamp(1, a, 1, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32i32_16x16x32_iu8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32i32.16x16x32.iu8.clamp(i1 true, <4 x i32> [[A:%.*]], i1 true, <4 x i32> [[B:%.*]], <8 x i32> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32i32_16x16x32_iu8_gfx13(global v8f* out, v4i a, v4i b, v8i c)
{
   *out = __builtin_amdgcn_wmma_f32i32_16x16x32_iu8_clamp(1, a, 1, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_i32_16x16x32_iu8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x i32> @llvm.amdgcn.wmma.i32.16x16x32.iu8.clamp(i1 true, <4 x i32> [[A:%.*]], i1 true, <4 x i32> [[B:%.*]], <8 x i32> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_i32_16x16x32_iu8_gfx13(global v8i* out, v4i a, v4i b, v8i c)
{
   *out = __builtin_amdgcn_wmma_i32_16x16x32_iu8_clamp(1, a, 1, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32_16x16x32_iu4_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x32.iu4.clamp(i1 true, <2 x i32> [[A:%.*]], i1 true, <2 x i32> [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x32_iu4_gfx13(global v8f* out, v2i a, v2i b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x32_iu4_clamp(1, a, 1, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32i32_16x16x32_iu4_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32i32.16x16x32.iu4.clamp(i1 true, <2 x i32> [[A:%.*]], i1 true, <2 x i32> [[B:%.*]], <8 x i32> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32i32_16x16x32_iu4_gfx13(global v8f* out, v2i a, v2i b, v8i c)
{
   *out = __builtin_amdgcn_wmma_f32i32_16x16x32_iu4_clamp(1, a, 1, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_i32_16x16x32_iu4_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x i32> @llvm.amdgcn.wmma.i32.16x16x32.iu4.clamp(i1 true, <2 x i32> [[A:%.*]], i1 true, <2 x i32> [[B:%.*]], <8 x i32> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_i32_16x16x32_iu4_gfx13(global v8i* out, v2i a, v2i b, v8i c)
{
   *out = __builtin_amdgcn_wmma_i32_16x16x32_iu4_clamp(1, a, 1, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32_16x16x64_iu4_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x64.iu4.clamp(i1 true, <4 x i32> [[A:%.*]], i1 true, <4 x i32> [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x64_iu4_gfx13(global v8f* out, v4i a, v4i b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x64_iu4_clamp(1, a, 1, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32i32_16x16x64_iu4_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32i32.16x16x64.iu4.clamp(i1 true, <4 x i32> [[A:%.*]], i1 true, <4 x i32> [[B:%.*]], <8 x i32> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32i32_16x16x64_iu4_gfx13(global v8f* out, v4i a, v4i b, v8i c)
{
   *out = __builtin_amdgcn_wmma_f32i32_16x16x64_iu4_clamp(1, a, 1, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_i32_16x16x64_iu4_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x i32> @llvm.amdgcn.wmma.i32.16x16x64.iu4.clamp(i1 true, <4 x i32> [[A:%.*]], i1 true, <4 x i32> [[B:%.*]], <8 x i32> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x i32> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_i32_16x16x64_iu4_gfx13(global v8i* out, v4i a, v4i b, v8i c)
{
   *out = __builtin_amdgcn_wmma_i32_16x16x64_iu4_clamp(1, a, 1, b, c, 1);
}
