// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu gfx1211 -target-feature +wavefrontsize32 -emit-llvm -o - %s | FileCheck %s --check-prefix=CHECK-GFX1211

typedef double v8d   __attribute__((ext_vector_type(8)));
typedef double v4d   __attribute__((ext_vector_type(4)));
typedef double v2d   __attribute__((ext_vector_type(2)));

// CHECK-GFX1211-LABEL: @test_amdgcn_wmma_f64_16x16x4_f64(
// CHECK-GFX1211-NEXT:  entry:
// CHECK-GFX1211-NEXT:    [[TMP0:%.*]] = tail call <8 x double> @llvm.amdgcn.wmma.f64.16x16x4.f64.v8f64.v2f64(i1 false, <2 x double> [[A:%.*]], i1 false, <2 x double> [[B:%.*]], i16 0, <8 x double> [[C:%.*]])
// CHECK-GFX1211-NEXT:    store <8 x double> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 64, !tbaa [[TBAA4:![0-9]+]]
// CHECK-GFX1211-NEXT:    ret void
//
void test_amdgcn_wmma_f64_16x16x4_f64(global v8d* out, v2d a, v2d b, v8d c)
{
  *out = __builtin_amdgcn_wmma_f64_16x16x4_f64(0, a, 0, b, 0, c);
}

// CHECK-GFX1211-LABEL: @test_amdgcn_wmma_f64_16x16x8_f64(
// CHECK-GFX1211-NEXT:  entry:
// CHECK-GFX1211-NEXT:    [[TMP0:%.*]] = tail call <8 x double> @llvm.amdgcn.wmma.f64.16x16x8.f64.v8f64.v4f64(i1 false, <4 x double> [[A:%.*]], i1 false, <4 x double> [[B:%.*]], i16 0, <8 x double> [[C:%.*]])
// CHECK-GFX1211-NEXT:    store <8 x double> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 64, !tbaa [[TBAA4]]
// CHECK-GFX1211-NEXT:    ret void
//
void test_amdgcn_wmma_f64_16x16x8_f64(global v8d* out, v4d a, v4d b, v8d c)
{
  *out = __builtin_amdgcn_wmma_f64_16x16x8_f64(0, a, 0, b, 0, c);
}
