// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -cl-std=CL2.0 -triple amdgcn-unknown-unknown -target-cpu gfx1300 -emit-llvm -o - %s | FileCheck %s --check-prefix=CHECK-GFX13

typedef int    v2i   __attribute__((ext_vector_type(2)));
typedef int    v4i   __attribute__((ext_vector_type(4)));

// CHECK-GFX13-LABEL: @test_amdgcn_load_mcast_b32_global(
// CHECK-GFX13-NEXT:  entry:
// CHECK-GFX13-NEXT:    tail call void @llvm.amdgcn.load.mcast.b32.p1(ptr addrspace(10) [[OUTPTR:%.*]], ptr addrspace(1) [[INPTR:%.*]], i32 10, i32 [[MASK:%.*]])
// CHECK-GFX13-NEXT:    ret void
//
void test_amdgcn_load_mcast_b32_global(__attribute__((address_space(10))) int* outptr, global int* inptr, int mask)
{
  __builtin_amdgcn_load_mcast_b32(outptr, inptr, 10, mask);
}

// CHECK-GFX13-LABEL: @test_amdgcn_load_mcast_b64_global(
// CHECK-GFX13-NEXT:  entry:
// CHECK-GFX13-NEXT:    tail call void @llvm.amdgcn.load.mcast.b64.p1(ptr addrspace(10) [[OUTPTR:%.*]], ptr addrspace(1) [[INPTR:%.*]], i32 22, i32 [[MASK:%.*]])
// CHECK-GFX13-NEXT:    ret void
//
void test_amdgcn_load_mcast_b64_global(__attribute__((address_space(10))) v2i* outptr, global v2i* inptr, int mask)
{
  __builtin_amdgcn_load_mcast_b64(outptr, inptr, 22, mask);
}

// CHECK-GFX13-LABEL: @test_amdgcn_load_mcast_b128_global(
// CHECK-GFX13-NEXT:  entry:
// CHECK-GFX13-NEXT:    tail call void @llvm.amdgcn.load.mcast.b128.p1(ptr addrspace(10) [[OUTPTR:%.*]], ptr addrspace(1) [[INPTR:%.*]], i32 27, i32 [[MASK:%.*]])
// CHECK-GFX13-NEXT:    ret void
//
void test_amdgcn_load_mcast_b128_global(__attribute__((address_space(10))) v4i* outptr, global v4i* inptr, int mask)
{
  __builtin_amdgcn_load_mcast_b128(outptr, inptr, 27, mask);
}

// CHECK-GFX13-LABEL: @test_amdgcn_load_mcast_b32_local(
// CHECK-GFX13-NEXT:  entry:
// CHECK-GFX13-NEXT:    tail call void @llvm.amdgcn.load.mcast.b32.p3(ptr addrspace(10) [[OUTPTR:%.*]], ptr addrspace(3) [[INPTR:%.*]], i32 10, i32 [[MASK:%.*]])
// CHECK-GFX13-NEXT:    ret void
//
void test_amdgcn_load_mcast_b32_local(__attribute__((address_space(10))) int* outptr, local int* inptr, int mask)
{
  __builtin_amdgcn_load_mcast_b32(outptr, inptr, 10, mask);
}

// CHECK-GFX13-LABEL: @test_amdgcn_load_mcast_b64_local(
// CHECK-GFX13-NEXT:  entry:
// CHECK-GFX13-NEXT:    tail call void @llvm.amdgcn.load.mcast.b64.p3(ptr addrspace(10) [[OUTPTR:%.*]], ptr addrspace(3) [[INPTR:%.*]], i32 22, i32 [[MASK:%.*]])
// CHECK-GFX13-NEXT:    ret void
//
void test_amdgcn_load_mcast_b64_local(__attribute__((address_space(10))) v2i* outptr, local v2i* inptr, int mask)
{
  __builtin_amdgcn_load_mcast_b64(outptr, inptr, 22, mask);
}

// CHECK-GFX13-LABEL: @test_amdgcn_load_mcast_b128_local(
// CHECK-GFX13-NEXT:  entry:
// CHECK-GFX13-NEXT:    tail call void @llvm.amdgcn.load.mcast.b128.p3(ptr addrspace(10) [[OUTPTR:%.*]], ptr addrspace(3) [[INPTR:%.*]], i32 27, i32 [[MASK:%.*]])
// CHECK-GFX13-NEXT:    ret void
//
void test_amdgcn_load_mcast_b128_local(__attribute__((address_space(10))) v4i* outptr, local v4i* inptr, int mask)
{
  __builtin_amdgcn_load_mcast_b128(outptr, inptr, 27, mask);
}

// CHECK-GFX13-LABEL: @test_amdgcn_load_mcast_b32_distributed(
// CHECK-GFX13-NEXT:  entry:
// CHECK-GFX13-NEXT:    tail call void @llvm.amdgcn.load.mcast.b32.p11(ptr addrspace(10) [[OUTPTR:%.*]], ptr addrspace(11) [[INPTR:%.*]], i32 10, i32 [[MASK:%.*]])
// CHECK-GFX13-NEXT:    ret void
//
void test_amdgcn_load_mcast_b32_distributed(__attribute__((address_space(10))) int* outptr, __attribute__((address_space(11))) int* inptr, int mask)
{
  __builtin_amdgcn_load_mcast_b32(outptr, inptr, 10, mask);
}

// CHECK-GFX13-LABEL: @test_amdgcn_load_mcast_b64_distributed(
// CHECK-GFX13-NEXT:  entry:
// CHECK-GFX13-NEXT:    tail call void @llvm.amdgcn.load.mcast.b64.p11(ptr addrspace(10) [[OUTPTR:%.*]], ptr addrspace(11) [[INPTR:%.*]], i32 22, i32 [[MASK:%.*]])
// CHECK-GFX13-NEXT:    ret void
//
void test_amdgcn_load_mcast_b64_distributed(__attribute__((address_space(10))) v2i* outptr, __attribute__((address_space(11))) v2i* inptr, int mask)
{
  __builtin_amdgcn_load_mcast_b64(outptr, inptr, 22, mask);
}

// CHECK-GFX13-LABEL: @test_amdgcn_load_mcast_b128_distributed(
// CHECK-GFX13-NEXT:  entry:
// CHECK-GFX13-NEXT:    tail call void @llvm.amdgcn.load.mcast.b128.p11(ptr addrspace(10) [[OUTPTR:%.*]], ptr addrspace(11) [[INPTR:%.*]], i32 27, i32 [[MASK:%.*]])
// CHECK-GFX13-NEXT:    ret void
//
void test_amdgcn_load_mcast_b128_distributed(__attribute__((address_space(10))) v4i* outptr, __attribute__((address_space(11))) v4i* inptr, int mask)
{
  __builtin_amdgcn_load_mcast_b128(outptr, inptr, 27, mask);
}
