// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-globals smart
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -cl-std=CL2.0 -triple amdgcn-unknown-unknown -target-cpu gfx900  -emit-llvm -o - %s | FileCheck %s
// RUN: %clang_cc1 -cl-std=CL2.0 -triple amdgcn-unknown-unknown -target-cpu gfx1010 -emit-llvm -o - %s | FileCheck %s
// RUN: %clang_cc1 -cl-std=CL2.0 -triple amdgcn-unknown-unknown -target-cpu gfx1100 -emit-llvm -o - %s | FileCheck %s
// RUN: %clang_cc1 -cl-std=CL2.0 -triple amdgcn-unknown-unknown -target-cpu gfx1200 -emit-llvm -o - %s | FileCheck %s
// RUN: %clang_cc1 -cl-std=CL2.0 -triple amdgcn-unknown-unknown -target-cpu gfx1250 -emit-llvm -o - %s | FileCheck %s

typedef __attribute__((__vector_size__(4 * sizeof(unsigned int)))) unsigned int v4u32;
typedef v4u32 __global *global_ptr_to_v4u32;

//------------------------------------------------------------------------------
// Global Load
//------------------------------------------------------------------------------

// CHECK-LABEL: @test_amdgcn_global_load_b128_wave(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.av.load.b128.p1(ptr addrspace(1) [[PTR:%.*]], metadata [[META7:![0-9]+]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4u32 test_amdgcn_global_load_b128_wave(global_ptr_to_v4u32 ptr) {
  return __builtin_amdgcn_av_load_b128(ptr, __MEMORY_SCOPE_WVFRNT);
}

// CHECK-LABEL: @test_amdgcn_global_load_b128_workgroup(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.av.load.b128.p1(ptr addrspace(1) [[PTR:%.*]], metadata [[META8:![0-9]+]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4u32 test_amdgcn_global_load_b128_workgroup(global_ptr_to_v4u32 ptr) {
  return __builtin_amdgcn_av_load_b128(ptr, __MEMORY_SCOPE_WRKGRP);
}

// CHECK-LABEL: @test_amdgcn_global_load_b128_device(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.av.load.b128.p1(ptr addrspace(1) [[PTR:%.*]], metadata [[META9:![0-9]+]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4u32 test_amdgcn_global_load_b128_device(global_ptr_to_v4u32 ptr) {
  return __builtin_amdgcn_av_load_b128(ptr, __MEMORY_SCOPE_DEVICE);
}

// CHECK-LABEL: @test_amdgcn_global_load_b128_system(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.av.load.b128.p1(ptr addrspace(1) [[PTR:%.*]], metadata [[META10:![0-9]+]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4u32 test_amdgcn_global_load_b128_system(global_ptr_to_v4u32 ptr) {
  return __builtin_amdgcn_av_load_b128(ptr, __MEMORY_SCOPE_SYSTEM);
}

// CHECK-LABEL: @test_amdgcn_global_load_b128_single(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.av.load.b128.p1(ptr addrspace(1) [[PTR:%.*]], metadata [[META11:![0-9]+]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4u32 test_amdgcn_global_load_b128_single(global_ptr_to_v4u32 ptr) {
  return __builtin_amdgcn_av_load_b128(ptr, __MEMORY_SCOPE_SINGLE);
}

// CHECK-LABEL: @test_amdgcn_global_load_b128_cluster(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.av.load.b128.p1(ptr addrspace(1) [[PTR:%.*]], metadata [[META12:![0-9]+]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4u32 test_amdgcn_global_load_b128_cluster(global_ptr_to_v4u32 ptr) {
  return __builtin_amdgcn_av_load_b128(ptr, __MEMORY_SCOPE_CLUSTR);
}

//------------------------------------------------------------------------------
// Global Store
//------------------------------------------------------------------------------

// CHECK-LABEL: @test_amdgcn_global_store_b128_wave(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.av.store.b128.p1(ptr addrspace(1) [[PTR:%.*]], <4 x i32> [[DATA:%.*]], metadata [[META7]])
// CHECK-NEXT:    ret void
//
void test_amdgcn_global_store_b128_wave(global_ptr_to_v4u32 ptr, v4u32 data) {
  __builtin_amdgcn_av_store_b128(ptr, data, __MEMORY_SCOPE_WVFRNT);
}

// CHECK-LABEL: @test_amdgcn_global_store_b128_workgroup(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.av.store.b128.p1(ptr addrspace(1) [[PTR:%.*]], <4 x i32> [[DATA:%.*]], metadata [[META8]])
// CHECK-NEXT:    ret void
//
void test_amdgcn_global_store_b128_workgroup(global_ptr_to_v4u32 ptr, v4u32 data) {
  __builtin_amdgcn_av_store_b128(ptr, data, __MEMORY_SCOPE_WRKGRP);
}

// CHECK-LABEL: @test_amdgcn_global_store_b128_device(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.av.store.b128.p1(ptr addrspace(1) [[PTR:%.*]], <4 x i32> [[DATA:%.*]], metadata [[META9]])
// CHECK-NEXT:    ret void
//
void test_amdgcn_global_store_b128_device(global_ptr_to_v4u32 ptr, v4u32 data) {
  __builtin_amdgcn_av_store_b128(ptr, data, __MEMORY_SCOPE_DEVICE);
}

// CHECK-LABEL: @test_amdgcn_global_store_b128_system(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.av.store.b128.p1(ptr addrspace(1) [[PTR:%.*]], <4 x i32> [[DATA:%.*]], metadata [[META10]])
// CHECK-NEXT:    ret void
//
void test_amdgcn_global_store_b128_system(global_ptr_to_v4u32 ptr, v4u32 data) {
  __builtin_amdgcn_av_store_b128(ptr, data, __MEMORY_SCOPE_SYSTEM);
}

// CHECK-LABEL: @test_amdgcn_global_store_b128_single(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.av.store.b128.p1(ptr addrspace(1) [[PTR:%.*]], <4 x i32> [[DATA:%.*]], metadata [[META11]])
// CHECK-NEXT:    ret void
//
void test_amdgcn_global_store_b128_single(global_ptr_to_v4u32 ptr, v4u32 data) {
  __builtin_amdgcn_av_store_b128(ptr, data, __MEMORY_SCOPE_SINGLE);
}

// CHECK-LABEL: @test_amdgcn_global_store_b128_cluster(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.av.store.b128.p1(ptr addrspace(1) [[PTR:%.*]], <4 x i32> [[DATA:%.*]], metadata [[META12]])
// CHECK-NEXT:    ret void
//
void test_amdgcn_global_store_b128_cluster(global_ptr_to_v4u32 ptr, v4u32 data) {
  __builtin_amdgcn_av_store_b128(ptr, data, __MEMORY_SCOPE_CLUSTR);
}

//------------------------------------------------------------------------------
// Flat Load
//------------------------------------------------------------------------------

// CHECK-LABEL: @test_amdgcn_flat_load_b128_wave(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.av.load.b128.p0(ptr [[PTR:%.*]], metadata [[META7]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4u32 test_amdgcn_flat_load_b128_wave(v4u32 * ptr) {
  return __builtin_amdgcn_av_load_b128(ptr, __MEMORY_SCOPE_WVFRNT);
}

// CHECK-LABEL: @test_amdgcn_flat_load_b128_workgroup(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.av.load.b128.p0(ptr [[PTR:%.*]], metadata [[META8]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4u32 test_amdgcn_flat_load_b128_workgroup(v4u32 * ptr) {
  return __builtin_amdgcn_av_load_b128(ptr, __MEMORY_SCOPE_WRKGRP);
}

// CHECK-LABEL: @test_amdgcn_flat_load_b128_device(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.av.load.b128.p0(ptr [[PTR:%.*]], metadata [[META9]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4u32 test_amdgcn_flat_load_b128_device(v4u32 * ptr) {
  return __builtin_amdgcn_av_load_b128(ptr, __MEMORY_SCOPE_DEVICE);
}

// CHECK-LABEL: @test_amdgcn_flat_load_b128_system(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.av.load.b128.p0(ptr [[PTR:%.*]], metadata [[META10]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4u32 test_amdgcn_flat_load_b128_system(v4u32 * ptr) {
  return __builtin_amdgcn_av_load_b128(ptr, __MEMORY_SCOPE_SYSTEM);
}

// CHECK-LABEL: @test_amdgcn_flat_load_b128_single(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.av.load.b128.p0(ptr [[PTR:%.*]], metadata [[META11]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4u32 test_amdgcn_flat_load_b128_single(v4u32 * ptr) {
  return __builtin_amdgcn_av_load_b128(ptr, __MEMORY_SCOPE_SINGLE);
}

// CHECK-LABEL: @test_amdgcn_flat_load_b128_cluster(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.amdgcn.av.load.b128.p0(ptr [[PTR:%.*]], metadata [[META12]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4u32 test_amdgcn_flat_load_b128_cluster(v4u32 * ptr) {
  return __builtin_amdgcn_av_load_b128(ptr, __MEMORY_SCOPE_CLUSTR);
}

//------------------------------------------------------------------------------
// Flat Store
//------------------------------------------------------------------------------

// CHECK-LABEL: @test_amdgcn_flat_store_b128_wave(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.av.store.b128.p0(ptr [[PTR:%.*]], <4 x i32> [[DATA:%.*]], metadata [[META7]])
// CHECK-NEXT:    ret void
//
void test_amdgcn_flat_store_b128_wave(v4u32 * ptr, v4u32 data) {
  __builtin_amdgcn_av_store_b128(ptr, data, __MEMORY_SCOPE_WVFRNT);
}

// CHECK-LABEL: @test_amdgcn_flat_store_b128_workgroup(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.av.store.b128.p0(ptr [[PTR:%.*]], <4 x i32> [[DATA:%.*]], metadata [[META8]])
// CHECK-NEXT:    ret void
//
void test_amdgcn_flat_store_b128_workgroup(v4u32 * ptr, v4u32 data) {
  __builtin_amdgcn_av_store_b128(ptr, data, __MEMORY_SCOPE_WRKGRP);
}

// CHECK-LABEL: @test_amdgcn_flat_store_b128_device(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.av.store.b128.p0(ptr [[PTR:%.*]], <4 x i32> [[DATA:%.*]], metadata [[META9]])
// CHECK-NEXT:    ret void
//
void test_amdgcn_flat_store_b128_device(v4u32 * ptr, v4u32 data) {
  __builtin_amdgcn_av_store_b128(ptr, data, __MEMORY_SCOPE_DEVICE);
}

// CHECK-LABEL: @test_amdgcn_flat_store_b128_system(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.av.store.b128.p0(ptr [[PTR:%.*]], <4 x i32> [[DATA:%.*]], metadata [[META10]])
// CHECK-NEXT:    ret void
//
void test_amdgcn_flat_store_b128_system(v4u32 * ptr, v4u32 data) {
  __builtin_amdgcn_av_store_b128(ptr, data, __MEMORY_SCOPE_SYSTEM);
}

// CHECK-LABEL: @test_amdgcn_flat_store_b128_single(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.av.store.b128.p0(ptr [[PTR:%.*]], <4 x i32> [[DATA:%.*]], metadata [[META11]])
// CHECK-NEXT:    ret void
//
void test_amdgcn_flat_store_b128_single(v4u32 * ptr, v4u32 data) {
  __builtin_amdgcn_av_store_b128(ptr, data, __MEMORY_SCOPE_SINGLE);
}

// CHECK-LABEL: @test_amdgcn_flat_store_b128_cluster(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.amdgcn.av.store.b128.p0(ptr [[PTR:%.*]], <4 x i32> [[DATA:%.*]], metadata [[META12]])
// CHECK-NEXT:    ret void
//
void test_amdgcn_flat_store_b128_cluster(v4u32 * ptr, v4u32 data) {
  __builtin_amdgcn_av_store_b128(ptr, data, __MEMORY_SCOPE_CLUSTR);
}
//.
// CHECK: [[META7]] = !{!"wavefront"}
// CHECK: [[META8]] = !{!"workgroup"}
// CHECK: [[META9]] = !{!"agent"}
// CHECK: [[META10]] = !{!""}
// CHECK: [[META11]] = !{!"singlethread"}
// CHECK: [[META12]] = !{!"cluster"}
//.
