// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu gfx1300 -target-feature +wavefrontsize32 -emit-llvm -o - %s | FileCheck %s --check-prefix=CHECK-GFX1300

typedef int    v2i   __attribute__((ext_vector_type(2)));
typedef int    v4i   __attribute__((ext_vector_type(4)));
typedef float  v8f   __attribute__((ext_vector_type(8)));
typedef half   v8h   __attribute__((ext_vector_type(8)));
typedef short  v8s   __attribute__((ext_vector_type(8)));
typedef int    v8i   __attribute__((ext_vector_type(8)));
typedef __bf16 v8bf16 __attribute__((ext_vector_type(8)));

// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32_16x16x16_fp8_fp8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.fp8.fp8.clamp(<2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4:![0-9]+]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x16_fp8_fp8_gfx13(global v8f* out, v2i a, v2i b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x16_fp8_fp8_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f16_16x16x16_fp8_fp8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x16.fp8.fp8.clamp(<2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <8 x half> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x16_fp8_fp8_gfx13(global v8h* out, v2i a, v2i b, v8h c)
{
   *out = __builtin_amdgcn_wmma_f16_16x16x16_fp8_fp8_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32_16x16x16_fp8_bf8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.fp8.bf8.clamp(<2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x16_fp8_bf8_gfx13(global v8f* out, v2i a, v2i b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x16_fp8_bf8_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f16_16x16x16_fp8_bf8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x16.fp8.bf8.clamp(<2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <8 x half> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x16_fp8_bf8_gfx13(global v8h* out, v2i a, v2i b, v8h c)
{
   *out = __builtin_amdgcn_wmma_f16_16x16x16_fp8_bf8_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32_16x16x16_bf8_fp8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf8.fp8.clamp(<2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x16_bf8_fp8_gfx13(global v8f* out, v2i a, v2i b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x16_bf8_fp8_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f16_16x16x16_bf8_fp8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x16.bf8.fp8.clamp(<2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <8 x half> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x16_bf8_fp8_gfx13(global v8h* out, v2i a, v2i b, v8h c)
{
   *out = __builtin_amdgcn_wmma_f16_16x16x16_bf8_fp8_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32_16x16x16_bf8_bf8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf8.bf8.clamp(<2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x16_bf8_bf8_gfx13(global v8f* out, v2i a, v2i b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x16_bf8_bf8_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f16_16x16x16_bf8_bf8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x16.bf8.bf8.clamp(<2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <8 x half> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x16_bf8_bf8_gfx13(global v8h* out, v2i a, v2i b, v8h c)
{
   *out = __builtin_amdgcn_wmma_f16_16x16x16_bf8_bf8_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32_16x16x16_f16_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.f16.clamp(<8 x half> [[A:%.*]], <8 x half> [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x16_f16_gfx13(global v8f* out, v8h a, v8h b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x16_f16_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f16_16x16x16_f16_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x16.f16.clamp(<8 x half> [[A:%.*]], <8 x half> [[B:%.*]], <8 x half> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x16_f16_gfx13(global v8h* out, v8h a, v8h b, v8h c)
{
   *out = __builtin_amdgcn_wmma_f16_16x16x16_f16_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32_16x16x16_bf16_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf16.clamp(<8 x bfloat> [[A:%.*]], <8 x bfloat> [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x16_bf16_gfx13(global v8f* out, v8bf16 a, v8bf16 b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x16_bf16_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_bf16_16x16x16_bf16_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x bfloat> @llvm.amdgcn.wmma.bf16.16x16x16.bf16.clamp(<8 x bfloat> [[A:%.*]], <8 x bfloat> [[B:%.*]], <8 x bfloat> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x bfloat> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_bf16_16x16x16_bf16_gfx13(global v8bf16* out, v8bf16 a, v8bf16 b, v8bf16 c)
{
   *out = __builtin_amdgcn_wmma_bf16_16x16x16_bf16_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32_16x16x32_fp8_fp8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x32.fp8.fp8.clamp(<4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x32_fp8_fp8_gfx13(global v8f* out, v4i a, v4i b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x32_fp8_fp8_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f16_16x16x32_fp8_fp8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x32.fp8.fp8.clamp(<4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <8 x half> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x32_fp8_fp8_gfx13(global v8h* out, v4i a, v4i b, v8h c)
{
   *out = __builtin_amdgcn_wmma_f16_16x16x32_fp8_fp8_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32_16x16x32_fp8_bf8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x32.fp8.bf8.clamp(<4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x32_fp8_bf8_gfx13(global v8f* out, v4i a, v4i b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x32_fp8_bf8_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f16_16x16x32_fp8_bf8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x32.fp8.bf8.clamp(<4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <8 x half> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x32_fp8_bf8_gfx13(global v8h* out, v4i a, v4i b, v8h c)
{
   *out = __builtin_amdgcn_wmma_f16_16x16x32_fp8_bf8_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32_16x16x32_bf8_fp8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x32.bf8.fp8.clamp(<4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x32_bf8_fp8_gfx13(global v8f* out, v4i a, v4i b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x32_bf8_fp8_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f16_16x16x32_bf8_fp8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x32.bf8.fp8.clamp(<4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <8 x half> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x32_bf8_fp8_gfx13(global v8h* out, v4i a, v4i b, v8h c)
{
   *out = __builtin_amdgcn_wmma_f16_16x16x32_bf8_fp8_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f32_16x16x32_bf8_bf8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x float> @llvm.amdgcn.wmma.f32.16x16x32.bf8.bf8.clamp(<4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <8 x float> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x float> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 32, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f32_16x16x32_bf8_bf8_gfx13(global v8f* out, v4i a, v4i b, v8f c)
{
   *out = __builtin_amdgcn_wmma_f32_16x16x32_bf8_bf8_clamp(a, b, c, 1);
}
// CHECK-GFX1300-LABEL: @test_amdgcn_wmma_f16_16x16x32_bf8_bf8_gfx13(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.amdgcn.wmma.f16.16x16x32.bf8.bf8.clamp(<4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]], <8 x half> [[C:%.*]], i1 true)
// CHECK-GFX1300-NEXT:    store <8 x half> [[TMP0]], ptr addrspace(1) [[OUT:%.*]], align 16, !tbaa [[TBAA4]]
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_wmma_f16_16x16x32_bf8_bf8_gfx13(global v8h* out, v4i a, v4i b, v8h c)
{
   *out = __builtin_amdgcn_wmma_f16_16x16x32_bf8_bf8_clamp(a, b, c, 1);
}
