// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu gfx1300 -target-feature +wavefrontsize32 -emit-llvm -o - %s | FileCheck %s --check-prefix=CHECK-GFX1300

typedef unsigned int uint;

// CHECK-GFX1300-LABEL: @test_amdgcn_s_sema_set_state(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = addrspacecast ptr addrspace(5) [[SEM:%.*]] to ptr addrspace(3)
// CHECK-GFX1300-NEXT:    tail call void @llvm.amdgcn.s.sema.set.state(ptr addrspace(3) [[TMP0]], i32 1)
// CHECK-GFX1300-NEXT:    tail call void @llvm.amdgcn.s.sema.set.state(ptr addrspace(3) [[TMP0]], i32 [[ARG:%.*]])
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_s_sema_set_state(void *sem, uint arg)
{
  __builtin_amdgcn_s_sema_set_state(sem, 1);
  __builtin_amdgcn_s_sema_set_state(sem, arg);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_s_sema_set_limit(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = addrspacecast ptr addrspace(5) [[SEM:%.*]] to ptr addrspace(3)
// CHECK-GFX1300-NEXT:    tail call void @llvm.amdgcn.s.sema.set.limit(ptr addrspace(3) [[TMP0]], i32 1)
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_s_sema_set_limit(void *sem)
{
  __builtin_amdgcn_s_sema_set_limit(sem, 1);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_s_sema_signal(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = addrspacecast ptr addrspace(5) [[SEM:%.*]] to ptr addrspace(3)
// CHECK-GFX1300-NEXT:    tail call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) [[TMP0]])
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_s_sema_signal(void *sem)
{
  __builtin_amdgcn_s_sema_signal(sem);
}

// CHECK-GFX1300-LABEL: @test_amdgcn_s_sema_wait(
// CHECK-GFX1300-NEXT:  entry:
// CHECK-GFX1300-NEXT:    [[TMP0:%.*]] = addrspacecast ptr addrspace(5) [[SEM:%.*]] to ptr addrspace(3)
// CHECK-GFX1300-NEXT:    tail call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) [[TMP0]])
// CHECK-GFX1300-NEXT:    ret void
//
void test_amdgcn_s_sema_wait(void *sem)
{
  __builtin_amdgcn_s_sema_wait(sem);
}
