// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-attributes --check-globals all --version 6
// RUN: %clang_cc1 -emit-llvm -O0 -cl-std=CL1.2 -o - %s | FileCheck %s -check-prefixes CHECK,CHECK-UNIFORM-12
// RUN: %clang_cc1 -emit-llvm -O0 -cl-std=CL2.0 -o - %s | FileCheck %s -check-prefixes CHECK,CHECK-NONUNIFORM-20
// RUN: %clang_cc1 -emit-llvm -O0 -cl-std=CL2.0 -cl-uniform-work-group-size -o - %s | FileCheck %s -check-prefixes CHECK,CHECK-UNIFORM-20
// RUN: %clang_cc1 -emit-llvm -O0 -cl-std=CL2.0 -foffload-uniform-block -o - %s | FileCheck %s -check-prefixes CHECK,CHECK-UNIFORM-20

// CHECK: Function Attrs: convergent noinline norecurse nounwind optnone
// CHECK-LABEL: define dso_local spir_kernel void @ker(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] !kernel_arg_addr_space [[META3:![0-9]+]] !kernel_arg_access_qual [[META3]] !kernel_arg_type [[META3]] !kernel_arg_base_type [[META3]] !kernel_arg_type_qual [[META3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    call void @__clang_ocl_kern_imp_ker() #[[ATTR2:[0-9]+]]
// CHECK-NEXT:    ret void
//
kernel void ker() {};

// CHECK: Function Attrs: convergent noinline norecurse nounwind optnone
// CHECK-LABEL: define dso_local void @foo(
// CHECK-SAME: ) #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void foo() {};

//.
// CHECK-UNIFORM-12: attributes #[[ATTR0]] = { convergent noinline norecurse nounwind optnone "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+cx8,+mmx,+sse,+sse2,+x87" "uniform-work-group-size"="true" }
// CHECK-UNIFORM-12: attributes #[[ATTR1]] = { convergent noinline norecurse nounwind optnone "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+cx8,+mmx,+sse,+sse2,+x87" }
// CHECK-UNIFORM-12: attributes #[[ATTR2]] = { convergent nounwind }
//.
// CHECK-NONUNIFORM-20: attributes #[[ATTR0]] = { convergent noinline norecurse nounwind optnone "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+cx8,+mmx,+sse,+sse2,+x87" "uniform-work-group-size"="false" }
// CHECK-NONUNIFORM-20: attributes #[[ATTR1]] = { convergent noinline norecurse nounwind optnone "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+cx8,+mmx,+sse,+sse2,+x87" }
// CHECK-NONUNIFORM-20: attributes #[[ATTR2]] = { convergent nounwind }
//.
// CHECK-UNIFORM-20: attributes #[[ATTR0]] = { convergent noinline norecurse nounwind optnone "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+cx8,+mmx,+sse,+sse2,+x87" "uniform-work-group-size"="true" }
// CHECK-UNIFORM-20: attributes #[[ATTR1]] = { convergent noinline norecurse nounwind optnone "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+cx8,+mmx,+sse,+sse2,+x87" }
// CHECK-UNIFORM-20: attributes #[[ATTR2]] = { convergent nounwind }
//.
