// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 %s -triple spir-unknown-unknown -finclude-default-header -fdeclare-opencl-builtins -cl-std=CL3.0 -emit-llvm -o - -O0 | FileCheck %s

// CHECK-LABEL: define dso_local spir_func void @test_shuffle_long(
// CHECK-SAME: i64 noundef [[L:%.*]], i64 noundef [[UL:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[L_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[UL_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store i64 [[L]], ptr [[L_ADDR]], align 8
// CHECK-NEXT:    store i64 [[UL]], ptr [[UL_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[L_ADDR]], align 8
// CHECK-NEXT:    [[CALL:%.*]] = call spir_func i64 @_Z23intel_sub_group_shufflelj(i64 noundef [[TMP0]], i32 noundef 1) #[[ATTR2:[0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[UL_ADDR]], align 8
// CHECK-NEXT:    [[CALL1:%.*]] = call spir_func i64 @_Z27intel_sub_group_shuffle_xormj(i64 noundef [[TMP1]], i32 noundef 1) #[[ATTR2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[L_ADDR]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[L_ADDR]], align 8
// CHECK-NEXT:    [[CALL2:%.*]] = call spir_func i64 @_Z28intel_sub_group_shuffle_downllj(i64 noundef [[TMP2]], i64 noundef [[TMP3]], i32 noundef 1) #[[ATTR2]]
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, ptr [[UL_ADDR]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = load i64, ptr [[UL_ADDR]], align 8
// CHECK-NEXT:    [[CALL3:%.*]] = call spir_func i64 @_Z26intel_sub_group_shuffle_upmmj(i64 noundef [[TMP4]], i64 noundef [[TMP5]], i32 noundef 1) #[[ATTR2]]
// CHECK-NEXT:    ret void
//
void test_shuffle_long(long l, ulong ul) {
  (void)intel_sub_group_shuffle(l, 1u);
  (void)intel_sub_group_shuffle_xor(ul, 1u);
  (void)intel_sub_group_shuffle_down(l, l, 1u);
  (void)intel_sub_group_shuffle_up(ul, ul, 1u);
}

// CHECK-LABEL: define dso_local spir_func void @test_block_read_ul_global(
// CHECK-SAME: ptr addrspace(1) noundef [[IN:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[IN_ADDR:%.*]] = alloca ptr addrspace(1), align 4
// CHECK-NEXT:    store ptr addrspace(1) [[IN]], ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(1), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL:%.*]] = call spir_func i64 @_Z29intel_sub_group_block_read_ulPU3AS1Km(ptr addrspace(1) noundef [[TMP0]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr addrspace(1), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL1:%.*]] = call spir_func <2 x i64> @_Z30intel_sub_group_block_read_ul2PU3AS1Km(ptr addrspace(1) noundef [[TMP1]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr addrspace(1), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL2:%.*]] = call spir_func <4 x i64> @_Z30intel_sub_group_block_read_ul4PU3AS1Km(ptr addrspace(1) noundef [[TMP2]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr addrspace(1), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL3:%.*]] = call spir_func <8 x i64> @_Z30intel_sub_group_block_read_ul8PU3AS1Km(ptr addrspace(1) noundef [[TMP3]]) #[[ATTR2]]
// CHECK-NEXT:    ret void
//
void test_block_read_ul_global(const __global ulong *in) {
  (void)intel_sub_group_block_read_ul(in);
  (void)intel_sub_group_block_read_ul2(in);
  (void)intel_sub_group_block_read_ul4(in);
  (void)intel_sub_group_block_read_ul8(in);
}

// CHECK-LABEL: define dso_local spir_func void @test_block_read_ul_image(
// CHECK-SAME: target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 0) [[ROIMG:%.*]], target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 2) [[RWIMG:%.*]], <2 x i32> noundef [[COORD:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ROIMG_ADDR:%.*]] = alloca target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 0), align 4
// CHECK-NEXT:    [[RWIMG_ADDR:%.*]] = alloca target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 2), align 4
// CHECK-NEXT:    [[COORD_ADDR:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    store target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 0) [[ROIMG]], ptr [[ROIMG_ADDR]], align 4
// CHECK-NEXT:    store target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 2) [[RWIMG]], ptr [[RWIMG_ADDR]], align 4
// CHECK-NEXT:    store <2 x i32> [[COORD]], ptr [[COORD_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 0), ptr [[ROIMG_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i32>, ptr [[COORD_ADDR]], align 8
// CHECK-NEXT:    [[CALL:%.*]] = call spir_func i64 @_Z29intel_sub_group_block_read_ul14ocl_image2d_roDv2_i(target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 0) [[TMP0]], <2 x i32> noundef [[TMP1]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 2), ptr [[RWIMG_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = load <2 x i32>, ptr [[COORD_ADDR]], align 8
// CHECK-NEXT:    [[CALL1:%.*]] = call spir_func <4 x i64> @_Z30intel_sub_group_block_read_ul414ocl_image2d_rwDv2_i(target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 2) [[TMP2]], <2 x i32> noundef [[TMP3]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP4:%.*]] = load target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 2), ptr [[RWIMG_ADDR]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = load <2 x i32>, ptr [[COORD_ADDR]], align 8
// CHECK-NEXT:    [[CALL2:%.*]] = call spir_func <16 x i64> @_Z31intel_sub_group_block_read_ul1614ocl_image2d_rwDv2_i(target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 2) [[TMP4]], <2 x i32> noundef [[TMP5]]) #[[ATTR2]]
// CHECK-NEXT:    ret void
//
void test_block_read_ul_image(read_only image2d_t roimg,
                              read_write image2d_t rwimg, int2 coord) {
  (void)intel_sub_group_block_read_ul(roimg, coord);
  (void)intel_sub_group_block_read_ul4(rwimg, coord);
  (void)intel_sub_group_block_read_ul16(rwimg, coord);
}

// CHECK-LABEL: define dso_local spir_func void @test_block_write_ul_global(
// CHECK-SAME: ptr addrspace(1) noundef [[OUT:%.*]], i64 noundef [[VALUE:%.*]], <2 x i64> noundef [[VALUE2:%.*]], <4 x i64> noundef [[VALUE4:%.*]], <8 x i64> noundef [[VALUE8:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[OUT_ADDR:%.*]] = alloca ptr addrspace(1), align 4
// CHECK-NEXT:    [[VALUE_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[VALUE2_ADDR:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[VALUE4_ADDR:%.*]] = alloca <4 x i64>, align 32
// CHECK-NEXT:    [[VALUE8_ADDR:%.*]] = alloca <8 x i64>, align 64
// CHECK-NEXT:    store ptr addrspace(1) [[OUT]], ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    store i64 [[VALUE]], ptr [[VALUE_ADDR]], align 8
// CHECK-NEXT:    store <2 x i64> [[VALUE2]], ptr [[VALUE2_ADDR]], align 16
// CHECK-NEXT:    store <4 x i64> [[VALUE4]], ptr [[VALUE4_ADDR]], align 32
// CHECK-NEXT:    store <8 x i64> [[VALUE8]], ptr [[VALUE8_ADDR]], align 64
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(1), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[VALUE_ADDR]], align 8
// CHECK-NEXT:    call spir_func void @_Z30intel_sub_group_block_write_ulPU3AS1mm(ptr addrspace(1) noundef [[TMP0]], i64 noundef [[TMP1]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr addrspace(1), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = load <2 x i64>, ptr [[VALUE2_ADDR]], align 16
// CHECK-NEXT:    call spir_func void @_Z31intel_sub_group_block_write_ul2PU3AS1mDv2_m(ptr addrspace(1) noundef [[TMP2]], <2 x i64> noundef [[TMP3]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr addrspace(1), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = load <4 x i64>, ptr [[VALUE4_ADDR]], align 32
// CHECK-NEXT:    call spir_func void @_Z31intel_sub_group_block_write_ul4PU3AS1mDv4_m(ptr addrspace(1) noundef [[TMP4]], <4 x i64> noundef [[TMP5]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP6:%.*]] = load ptr addrspace(1), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <8 x i64>, ptr [[VALUE8_ADDR]], align 64
// CHECK-NEXT:    call spir_func void @_Z31intel_sub_group_block_write_ul8PU3AS1mDv8_m(ptr addrspace(1) noundef [[TMP6]], <8 x i64> noundef [[TMP7]]) #[[ATTR2]]
// CHECK-NEXT:    ret void
//
void test_block_write_ul_global(__global ulong *out, ulong value,
                                ulong2 value2, ulong4 value4,
                                ulong8 value8) {
  intel_sub_group_block_write_ul(out, value);
  intel_sub_group_block_write_ul2(out, value2);
  intel_sub_group_block_write_ul4(out, value4);
  intel_sub_group_block_write_ul8(out, value8);
}

// CHECK-LABEL: define dso_local spir_func void @test_block_write_ul_image(
// CHECK-SAME: target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 1) [[WOIMG:%.*]], target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 2) [[RWIMG:%.*]], <2 x i32> noundef [[COORD:%.*]], i64 noundef [[VALUE:%.*]], <16 x i64> noundef [[VALUE16:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[WOIMG_ADDR:%.*]] = alloca target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 1), align 4
// CHECK-NEXT:    [[RWIMG_ADDR:%.*]] = alloca target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 2), align 4
// CHECK-NEXT:    [[COORD_ADDR:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[VALUE_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[VALUE16_ADDR:%.*]] = alloca <16 x i64>, align 128
// CHECK-NEXT:    store target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 1) [[WOIMG]], ptr [[WOIMG_ADDR]], align 4
// CHECK-NEXT:    store target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 2) [[RWIMG]], ptr [[RWIMG_ADDR]], align 4
// CHECK-NEXT:    store <2 x i32> [[COORD]], ptr [[COORD_ADDR]], align 8
// CHECK-NEXT:    store i64 [[VALUE]], ptr [[VALUE_ADDR]], align 8
// CHECK-NEXT:    store <16 x i64> [[VALUE16]], ptr [[VALUE16_ADDR]], align 128
// CHECK-NEXT:    [[TMP0:%.*]] = load target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 1), ptr [[WOIMG_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i32>, ptr [[COORD_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[VALUE_ADDR]], align 8
// CHECK-NEXT:    call spir_func void @_Z30intel_sub_group_block_write_ul14ocl_image2d_woDv2_im(target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 1) [[TMP0]], <2 x i32> noundef [[TMP1]], i64 noundef [[TMP2]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP3:%.*]] = load target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 2), ptr [[RWIMG_ADDR]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = load <2 x i32>, ptr [[COORD_ADDR]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = load <16 x i64>, ptr [[VALUE16_ADDR]], align 128
// CHECK-NEXT:    call spir_func void @_Z32intel_sub_group_block_write_ul1614ocl_image2d_rwDv2_iDv16_m(target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 2) [[TMP3]], <2 x i32> noundef [[TMP4]], <16 x i64> noundef [[TMP5]]) #[[ATTR2]]
// CHECK-NEXT:    ret void
//
void test_block_write_ul_image(write_only image2d_t woimg,
                               read_write image2d_t rwimg, int2 coord,
                               ulong value, ulong16 value16) {
  intel_sub_group_block_write_ul(woimg, coord, value);
  intel_sub_group_block_write_ul16(rwimg, coord, value16);
}
