// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 %s -triple spir-unknown-unknown -finclude-default-header -fdeclare-opencl-builtins -cl-std=CL3.0 -emit-llvm -o - -O0 | FileCheck %s

// CHECK-LABEL: define dso_local spir_func void @test_block_read_local(
// CHECK-SAME: ptr addrspace(3) noundef [[IN:%.*]], ptr addrspace(3) noundef [[OUT:%.*]], i32 noundef [[VALUE:%.*]], <2 x i32> noundef [[VALUE2:%.*]], <4 x i32> noundef [[VALUE4:%.*]], <8 x i32> noundef [[VALUE8:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[IN_ADDR:%.*]] = alloca ptr addrspace(3), align 4
// CHECK-NEXT:    [[OUT_ADDR:%.*]] = alloca ptr addrspace(3), align 4
// CHECK-NEXT:    [[VALUE_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[VALUE2_ADDR:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[VALUE4_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[VALUE8_ADDR:%.*]] = alloca <8 x i32>, align 32
// CHECK-NEXT:    [[V:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[V2:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[V4:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[V8:%.*]] = alloca <8 x i32>, align 32
// CHECK-NEXT:    store ptr addrspace(3) [[IN]], ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    store ptr addrspace(3) [[OUT]], ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    store i32 [[VALUE]], ptr [[VALUE_ADDR]], align 4
// CHECK-NEXT:    store <2 x i32> [[VALUE2]], ptr [[VALUE2_ADDR]], align 8
// CHECK-NEXT:    store <4 x i32> [[VALUE4]], ptr [[VALUE4_ADDR]], align 16
// CHECK-NEXT:    store <8 x i32> [[VALUE8]], ptr [[VALUE8_ADDR]], align 32
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL:%.*]] = call spir_func i32 @_Z26intel_sub_group_block_readPU3AS3Kj(ptr addrspace(3) noundef [[TMP0]]) #[[ATTR2:[0-9]+]]
// CHECK-NEXT:    store i32 [[CALL]], ptr [[V]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL1:%.*]] = call spir_func <2 x i32> @_Z27intel_sub_group_block_read2PU3AS3Kj(ptr addrspace(3) noundef [[TMP1]]) #[[ATTR2]]
// CHECK-NEXT:    store <2 x i32> [[CALL1]], ptr [[V2]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL2:%.*]] = call spir_func <4 x i32> @_Z27intel_sub_group_block_read4PU3AS3Kj(ptr addrspace(3) noundef [[TMP2]]) #[[ATTR2]]
// CHECK-NEXT:    store <4 x i32> [[CALL2]], ptr [[V4]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL3:%.*]] = call spir_func <8 x i32> @_Z27intel_sub_group_block_read8PU3AS3Kj(ptr addrspace(3) noundef [[TMP3]]) #[[ATTR2]]
// CHECK-NEXT:    store <8 x i32> [[CALL3]], ptr [[V8]], align 32
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[VALUE_ADDR]], align 4
// CHECK-NEXT:    call spir_func void @_Z27intel_sub_group_block_writePU3AS3jj(ptr addrspace(3) noundef [[TMP4]], i32 noundef [[TMP5]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP6:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <2 x i32>, ptr [[VALUE2_ADDR]], align 8
// CHECK-NEXT:    call spir_func void @_Z28intel_sub_group_block_write2PU3AS3jDv2_j(ptr addrspace(3) noundef [[TMP6]], <2 x i32> noundef [[TMP7]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP8:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = load <4 x i32>, ptr [[VALUE4_ADDR]], align 16
// CHECK-NEXT:    call spir_func void @_Z28intel_sub_group_block_write4PU3AS3jDv4_j(ptr addrspace(3) noundef [[TMP8]], <4 x i32> noundef [[TMP9]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP10:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP11:%.*]] = load <8 x i32>, ptr [[VALUE8_ADDR]], align 32
// CHECK-NEXT:    call spir_func void @_Z28intel_sub_group_block_write8PU3AS3jDv8_j(ptr addrspace(3) noundef [[TMP10]], <8 x i32> noundef [[TMP11]]) #[[ATTR2]]
// CHECK-NEXT:    ret void
//
void test_block_read_local(const __local uint *in, __local uint *out,
                           uint value, uint2 value2, uint4 value4,
                           uint8 value8) {
  uint v = intel_sub_group_block_read(in);
  uint2 v2 = intel_sub_group_block_read2(in);
  uint4 v4 = intel_sub_group_block_read4(in);
  uint8 v8 = intel_sub_group_block_read8(in);

  intel_sub_group_block_write(out, value);
  intel_sub_group_block_write2(out, value2);
  intel_sub_group_block_write4(out, value4);
  intel_sub_group_block_write8(out, value8);
}

// CHECK-LABEL: define dso_local spir_func void @test_block_read_ui_local(
// CHECK-SAME: ptr addrspace(3) noundef [[IN:%.*]], ptr addrspace(3) noundef [[OUT:%.*]], i32 noundef [[VALUE:%.*]], <2 x i32> noundef [[VALUE2:%.*]], <4 x i32> noundef [[VALUE4:%.*]], <8 x i32> noundef [[VALUE8:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[IN_ADDR:%.*]] = alloca ptr addrspace(3), align 4
// CHECK-NEXT:    [[OUT_ADDR:%.*]] = alloca ptr addrspace(3), align 4
// CHECK-NEXT:    [[VALUE_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[VALUE2_ADDR:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[VALUE4_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[VALUE8_ADDR:%.*]] = alloca <8 x i32>, align 32
// CHECK-NEXT:    [[V:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[V2:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[V4:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[V8:%.*]] = alloca <8 x i32>, align 32
// CHECK-NEXT:    store ptr addrspace(3) [[IN]], ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    store ptr addrspace(3) [[OUT]], ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    store i32 [[VALUE]], ptr [[VALUE_ADDR]], align 4
// CHECK-NEXT:    store <2 x i32> [[VALUE2]], ptr [[VALUE2_ADDR]], align 8
// CHECK-NEXT:    store <4 x i32> [[VALUE4]], ptr [[VALUE4_ADDR]], align 16
// CHECK-NEXT:    store <8 x i32> [[VALUE8]], ptr [[VALUE8_ADDR]], align 32
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL:%.*]] = call spir_func i32 @_Z29intel_sub_group_block_read_uiPU3AS3Kj(ptr addrspace(3) noundef [[TMP0]]) #[[ATTR2]]
// CHECK-NEXT:    store i32 [[CALL]], ptr [[V]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL1:%.*]] = call spir_func <2 x i32> @_Z30intel_sub_group_block_read_ui2PU3AS3Kj(ptr addrspace(3) noundef [[TMP1]]) #[[ATTR2]]
// CHECK-NEXT:    store <2 x i32> [[CALL1]], ptr [[V2]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL2:%.*]] = call spir_func <4 x i32> @_Z30intel_sub_group_block_read_ui4PU3AS3Kj(ptr addrspace(3) noundef [[TMP2]]) #[[ATTR2]]
// CHECK-NEXT:    store <4 x i32> [[CALL2]], ptr [[V4]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL3:%.*]] = call spir_func <8 x i32> @_Z30intel_sub_group_block_read_ui8PU3AS3Kj(ptr addrspace(3) noundef [[TMP3]]) #[[ATTR2]]
// CHECK-NEXT:    store <8 x i32> [[CALL3]], ptr [[V8]], align 32
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[VALUE_ADDR]], align 4
// CHECK-NEXT:    call spir_func void @_Z30intel_sub_group_block_write_uiPU3AS3jj(ptr addrspace(3) noundef [[TMP4]], i32 noundef [[TMP5]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP6:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <2 x i32>, ptr [[VALUE2_ADDR]], align 8
// CHECK-NEXT:    call spir_func void @_Z31intel_sub_group_block_write_ui2PU3AS3jDv2_j(ptr addrspace(3) noundef [[TMP6]], <2 x i32> noundef [[TMP7]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP8:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = load <4 x i32>, ptr [[VALUE4_ADDR]], align 16
// CHECK-NEXT:    call spir_func void @_Z31intel_sub_group_block_write_ui4PU3AS3jDv4_j(ptr addrspace(3) noundef [[TMP8]], <4 x i32> noundef [[TMP9]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP10:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP11:%.*]] = load <8 x i32>, ptr [[VALUE8_ADDR]], align 32
// CHECK-NEXT:    call spir_func void @_Z31intel_sub_group_block_write_ui8PU3AS3jDv8_j(ptr addrspace(3) noundef [[TMP10]], <8 x i32> noundef [[TMP11]]) #[[ATTR2]]
// CHECK-NEXT:    ret void
//
void test_block_read_ui_local(const __local uint *in, __local uint *out,
                              uint value, uint2 value2, uint4 value4,
                              uint8 value8) {
  uint v = intel_sub_group_block_read_ui(in);
  uint2 v2 = intel_sub_group_block_read_ui2(in);
  uint4 v4 = intel_sub_group_block_read_ui4(in);
  uint8 v8 = intel_sub_group_block_read_ui8(in);

  intel_sub_group_block_write_ui(out, value);
  intel_sub_group_block_write_ui2(out, value2);
  intel_sub_group_block_write_ui4(out, value4);
  intel_sub_group_block_write_ui8(out, value8);
}

// CHECK-LABEL: define dso_local spir_func void @test_block_read_uc_local(
// CHECK-SAME: ptr addrspace(3) noundef [[IN:%.*]], ptr addrspace(3) noundef [[OUT:%.*]], i8 noundef zeroext [[VALUE:%.*]], <2 x i8> noundef [[VALUE2:%.*]], <4 x i8> noundef [[VALUE4:%.*]], <8 x i8> noundef [[VALUE8:%.*]], <16 x i8> noundef [[VALUE16:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[IN_ADDR:%.*]] = alloca ptr addrspace(3), align 4
// CHECK-NEXT:    [[OUT_ADDR:%.*]] = alloca ptr addrspace(3), align 4
// CHECK-NEXT:    [[VALUE_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[VALUE2_ADDR:%.*]] = alloca <2 x i8>, align 2
// CHECK-NEXT:    [[VALUE4_ADDR:%.*]] = alloca <4 x i8>, align 4
// CHECK-NEXT:    [[VALUE8_ADDR:%.*]] = alloca <8 x i8>, align 8
// CHECK-NEXT:    [[VALUE16_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[V:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[V2:%.*]] = alloca <2 x i8>, align 2
// CHECK-NEXT:    [[V4:%.*]] = alloca <4 x i8>, align 4
// CHECK-NEXT:    [[V8:%.*]] = alloca <8 x i8>, align 8
// CHECK-NEXT:    [[V16:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    store ptr addrspace(3) [[IN]], ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    store ptr addrspace(3) [[OUT]], ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    store i8 [[VALUE]], ptr [[VALUE_ADDR]], align 1
// CHECK-NEXT:    store <2 x i8> [[VALUE2]], ptr [[VALUE2_ADDR]], align 2
// CHECK-NEXT:    store <4 x i8> [[VALUE4]], ptr [[VALUE4_ADDR]], align 4
// CHECK-NEXT:    store <8 x i8> [[VALUE8]], ptr [[VALUE8_ADDR]], align 8
// CHECK-NEXT:    store <16 x i8> [[VALUE16]], ptr [[VALUE16_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL:%.*]] = call spir_func zeroext i8 @_Z29intel_sub_group_block_read_ucPU3AS3Kh(ptr addrspace(3) noundef [[TMP0]]) #[[ATTR2]]
// CHECK-NEXT:    store i8 [[CALL]], ptr [[V]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL1:%.*]] = call spir_func <2 x i8> @_Z30intel_sub_group_block_read_uc2PU3AS3Kh(ptr addrspace(3) noundef [[TMP1]]) #[[ATTR2]]
// CHECK-NEXT:    store <2 x i8> [[CALL1]], ptr [[V2]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL2:%.*]] = call spir_func <4 x i8> @_Z30intel_sub_group_block_read_uc4PU3AS3Kh(ptr addrspace(3) noundef [[TMP2]]) #[[ATTR2]]
// CHECK-NEXT:    store <4 x i8> [[CALL2]], ptr [[V4]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL3:%.*]] = call spir_func <8 x i8> @_Z30intel_sub_group_block_read_uc8PU3AS3Kh(ptr addrspace(3) noundef [[TMP3]]) #[[ATTR2]]
// CHECK-NEXT:    store <8 x i8> [[CALL3]], ptr [[V8]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL4:%.*]] = call spir_func <16 x i8> @_Z31intel_sub_group_block_read_uc16PU3AS3Kh(ptr addrspace(3) noundef [[TMP4]]) #[[ATTR2]]
// CHECK-NEXT:    store <16 x i8> [[CALL4]], ptr [[V16]], align 16
// CHECK-NEXT:    [[TMP5:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[VALUE_ADDR]], align 1
// CHECK-NEXT:    call spir_func void @_Z30intel_sub_group_block_write_ucPU3AS3hh(ptr addrspace(3) noundef [[TMP5]], i8 noundef zeroext [[TMP6]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP7:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = load <2 x i8>, ptr [[VALUE2_ADDR]], align 2
// CHECK-NEXT:    call spir_func void @_Z31intel_sub_group_block_write_uc2PU3AS3hDv2_h(ptr addrspace(3) noundef [[TMP7]], <2 x i8> noundef [[TMP8]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP9:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = load <4 x i8>, ptr [[VALUE4_ADDR]], align 4
// CHECK-NEXT:    call spir_func void @_Z31intel_sub_group_block_write_uc4PU3AS3hDv4_h(ptr addrspace(3) noundef [[TMP9]], <4 x i8> noundef [[TMP10]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP11:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP12:%.*]] = load <8 x i8>, ptr [[VALUE8_ADDR]], align 8
// CHECK-NEXT:    call spir_func void @_Z31intel_sub_group_block_write_uc8PU3AS3hDv8_h(ptr addrspace(3) noundef [[TMP11]], <8 x i8> noundef [[TMP12]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP13:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP14:%.*]] = load <16 x i8>, ptr [[VALUE16_ADDR]], align 16
// CHECK-NEXT:    call spir_func void @_Z32intel_sub_group_block_write_uc16PU3AS3hDv16_h(ptr addrspace(3) noundef [[TMP13]], <16 x i8> noundef [[TMP14]]) #[[ATTR2]]
// CHECK-NEXT:    ret void
//
void test_block_read_uc_local(const __local uchar *in, __local uchar *out,
                              uchar value, uchar2 value2, uchar4 value4,
                              uchar8 value8, uchar16 value16) {
  uchar v = intel_sub_group_block_read_uc(in);
  uchar2 v2 = intel_sub_group_block_read_uc2(in);
  uchar4 v4 = intel_sub_group_block_read_uc4(in);
  uchar8 v8 = intel_sub_group_block_read_uc8(in);
  uchar16 v16 = intel_sub_group_block_read_uc16(in);

  intel_sub_group_block_write_uc(out, value);
  intel_sub_group_block_write_uc2(out, value2);
  intel_sub_group_block_write_uc4(out, value4);
  intel_sub_group_block_write_uc8(out, value8);
  intel_sub_group_block_write_uc16(out, value16);
}

// CHECK-LABEL: define dso_local spir_func void @test_block_read_us_local(
// CHECK-SAME: ptr addrspace(3) noundef [[IN:%.*]], ptr addrspace(3) noundef [[OUT:%.*]], i16 noundef zeroext [[VALUE:%.*]], <2 x i16> noundef [[VALUE2:%.*]], <4 x i16> noundef [[VALUE4:%.*]], <8 x i16> noundef [[VALUE8:%.*]], <16 x i16> noundef [[VALUE16:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[IN_ADDR:%.*]] = alloca ptr addrspace(3), align 4
// CHECK-NEXT:    [[OUT_ADDR:%.*]] = alloca ptr addrspace(3), align 4
// CHECK-NEXT:    [[VALUE_ADDR:%.*]] = alloca i16, align 2
// CHECK-NEXT:    [[VALUE2_ADDR:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    [[VALUE4_ADDR:%.*]] = alloca <4 x i16>, align 8
// CHECK-NEXT:    [[VALUE8_ADDR:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[VALUE16_ADDR:%.*]] = alloca <16 x i16>, align 32
// CHECK-NEXT:    [[V:%.*]] = alloca i16, align 2
// CHECK-NEXT:    [[V2:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    [[V4:%.*]] = alloca <4 x i16>, align 8
// CHECK-NEXT:    [[V8:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[V16:%.*]] = alloca <16 x i16>, align 32
// CHECK-NEXT:    store ptr addrspace(3) [[IN]], ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    store ptr addrspace(3) [[OUT]], ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    store i16 [[VALUE]], ptr [[VALUE_ADDR]], align 2
// CHECK-NEXT:    store <2 x i16> [[VALUE2]], ptr [[VALUE2_ADDR]], align 4
// CHECK-NEXT:    store <4 x i16> [[VALUE4]], ptr [[VALUE4_ADDR]], align 8
// CHECK-NEXT:    store <8 x i16> [[VALUE8]], ptr [[VALUE8_ADDR]], align 16
// CHECK-NEXT:    store <16 x i16> [[VALUE16]], ptr [[VALUE16_ADDR]], align 32
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL:%.*]] = call spir_func zeroext i16 @_Z29intel_sub_group_block_read_usPU3AS3Kt(ptr addrspace(3) noundef [[TMP0]]) #[[ATTR2]]
// CHECK-NEXT:    store i16 [[CALL]], ptr [[V]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL1:%.*]] = call spir_func <2 x i16> @_Z30intel_sub_group_block_read_us2PU3AS3Kt(ptr addrspace(3) noundef [[TMP1]]) #[[ATTR2]]
// CHECK-NEXT:    store <2 x i16> [[CALL1]], ptr [[V2]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL2:%.*]] = call spir_func <4 x i16> @_Z30intel_sub_group_block_read_us4PU3AS3Kt(ptr addrspace(3) noundef [[TMP2]]) #[[ATTR2]]
// CHECK-NEXT:    store <4 x i16> [[CALL2]], ptr [[V4]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL3:%.*]] = call spir_func <8 x i16> @_Z30intel_sub_group_block_read_us8PU3AS3Kt(ptr addrspace(3) noundef [[TMP3]]) #[[ATTR2]]
// CHECK-NEXT:    store <8 x i16> [[CALL3]], ptr [[V8]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL4:%.*]] = call spir_func <16 x i16> @_Z31intel_sub_group_block_read_us16PU3AS3Kt(ptr addrspace(3) noundef [[TMP4]]) #[[ATTR2]]
// CHECK-NEXT:    store <16 x i16> [[CALL4]], ptr [[V16]], align 32
// CHECK-NEXT:    [[TMP5:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[VALUE_ADDR]], align 2
// CHECK-NEXT:    call spir_func void @_Z30intel_sub_group_block_write_usPU3AS3tt(ptr addrspace(3) noundef [[TMP5]], i16 noundef zeroext [[TMP6]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP7:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = load <2 x i16>, ptr [[VALUE2_ADDR]], align 4
// CHECK-NEXT:    call spir_func void @_Z31intel_sub_group_block_write_us2PU3AS3tDv2_t(ptr addrspace(3) noundef [[TMP7]], <2 x i16> noundef [[TMP8]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP9:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = load <4 x i16>, ptr [[VALUE4_ADDR]], align 8
// CHECK-NEXT:    call spir_func void @_Z31intel_sub_group_block_write_us4PU3AS3tDv4_t(ptr addrspace(3) noundef [[TMP9]], <4 x i16> noundef [[TMP10]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP11:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP12:%.*]] = load <8 x i16>, ptr [[VALUE8_ADDR]], align 16
// CHECK-NEXT:    call spir_func void @_Z31intel_sub_group_block_write_us8PU3AS3tDv8_t(ptr addrspace(3) noundef [[TMP11]], <8 x i16> noundef [[TMP12]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP13:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP14:%.*]] = load <16 x i16>, ptr [[VALUE16_ADDR]], align 32
// CHECK-NEXT:    call spir_func void @_Z32intel_sub_group_block_write_us16PU3AS3tDv16_t(ptr addrspace(3) noundef [[TMP13]], <16 x i16> noundef [[TMP14]]) #[[ATTR2]]
// CHECK-NEXT:    ret void
//
void test_block_read_us_local(const __local ushort *in, __local ushort *out,
                              ushort value, ushort2 value2, ushort4 value4,
                              ushort8 value8, ushort16 value16) {
  ushort v = intel_sub_group_block_read_us(in);
  ushort2 v2 = intel_sub_group_block_read_us2(in);
  ushort4 v4 = intel_sub_group_block_read_us4(in);
  ushort8 v8 = intel_sub_group_block_read_us8(in);
  ushort16 v16 = intel_sub_group_block_read_us16(in);

  intel_sub_group_block_write_us(out, value);
  intel_sub_group_block_write_us2(out, value2);
  intel_sub_group_block_write_us4(out, value4);
  intel_sub_group_block_write_us8(out, value8);
  intel_sub_group_block_write_us16(out, value16);
}

// CHECK-LABEL: define dso_local spir_func void @test_block_read_ul_local(
// CHECK-SAME: ptr addrspace(3) noundef [[IN:%.*]], ptr addrspace(3) noundef [[OUT:%.*]], i64 noundef [[VALUE:%.*]], <2 x i64> noundef [[VALUE2:%.*]], <4 x i64> noundef [[VALUE4:%.*]], <8 x i64> noundef [[VALUE8:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[IN_ADDR:%.*]] = alloca ptr addrspace(3), align 4
// CHECK-NEXT:    [[OUT_ADDR:%.*]] = alloca ptr addrspace(3), align 4
// CHECK-NEXT:    [[VALUE_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[VALUE2_ADDR:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[VALUE4_ADDR:%.*]] = alloca <4 x i64>, align 32
// CHECK-NEXT:    [[VALUE8_ADDR:%.*]] = alloca <8 x i64>, align 64
// CHECK-NEXT:    [[V:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[V2:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[V4:%.*]] = alloca <4 x i64>, align 32
// CHECK-NEXT:    [[V8:%.*]] = alloca <8 x i64>, align 64
// CHECK-NEXT:    store ptr addrspace(3) [[IN]], ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    store ptr addrspace(3) [[OUT]], ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    store i64 [[VALUE]], ptr [[VALUE_ADDR]], align 8
// CHECK-NEXT:    store <2 x i64> [[VALUE2]], ptr [[VALUE2_ADDR]], align 16
// CHECK-NEXT:    store <4 x i64> [[VALUE4]], ptr [[VALUE4_ADDR]], align 32
// CHECK-NEXT:    store <8 x i64> [[VALUE8]], ptr [[VALUE8_ADDR]], align 64
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL:%.*]] = call spir_func i64 @_Z29intel_sub_group_block_read_ulPU3AS3Km(ptr addrspace(3) noundef [[TMP0]]) #[[ATTR2]]
// CHECK-NEXT:    store i64 [[CALL]], ptr [[V]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL1:%.*]] = call spir_func <2 x i64> @_Z30intel_sub_group_block_read_ul2PU3AS3Km(ptr addrspace(3) noundef [[TMP1]]) #[[ATTR2]]
// CHECK-NEXT:    store <2 x i64> [[CALL1]], ptr [[V2]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL2:%.*]] = call spir_func <4 x i64> @_Z30intel_sub_group_block_read_ul4PU3AS3Km(ptr addrspace(3) noundef [[TMP2]]) #[[ATTR2]]
// CHECK-NEXT:    store <4 x i64> [[CALL2]], ptr [[V4]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr addrspace(3), ptr [[IN_ADDR]], align 4
// CHECK-NEXT:    [[CALL3:%.*]] = call spir_func <8 x i64> @_Z30intel_sub_group_block_read_ul8PU3AS3Km(ptr addrspace(3) noundef [[TMP3]]) #[[ATTR2]]
// CHECK-NEXT:    store <8 x i64> [[CALL3]], ptr [[V8]], align 64
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = load i64, ptr [[VALUE_ADDR]], align 8
// CHECK-NEXT:    call spir_func void @_Z30intel_sub_group_block_write_ulPU3AS3mm(ptr addrspace(3) noundef [[TMP4]], i64 noundef [[TMP5]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP6:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load <2 x i64>, ptr [[VALUE2_ADDR]], align 16
// CHECK-NEXT:    call spir_func void @_Z31intel_sub_group_block_write_ul2PU3AS3mDv2_m(ptr addrspace(3) noundef [[TMP6]], <2 x i64> noundef [[TMP7]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP8:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = load <4 x i64>, ptr [[VALUE4_ADDR]], align 32
// CHECK-NEXT:    call spir_func void @_Z31intel_sub_group_block_write_ul4PU3AS3mDv4_m(ptr addrspace(3) noundef [[TMP8]], <4 x i64> noundef [[TMP9]]) #[[ATTR2]]
// CHECK-NEXT:    [[TMP10:%.*]] = load ptr addrspace(3), ptr [[OUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP11:%.*]] = load <8 x i64>, ptr [[VALUE8_ADDR]], align 64
// CHECK-NEXT:    call spir_func void @_Z31intel_sub_group_block_write_ul8PU3AS3mDv8_m(ptr addrspace(3) noundef [[TMP10]], <8 x i64> noundef [[TMP11]]) #[[ATTR2]]
// CHECK-NEXT:    ret void
//
void test_block_read_ul_local(const __local ulong *in, __local ulong *out,
                              ulong value, ulong2 value2, ulong4 value4,
                              ulong8 value8) {
  ulong v = intel_sub_group_block_read_ul(in);
  ulong2 v2 = intel_sub_group_block_read_ul2(in);
  ulong4 v4 = intel_sub_group_block_read_ul4(in);
  ulong8 v8 = intel_sub_group_block_read_ul8(in);

  intel_sub_group_block_write_ul(out, value);
  intel_sub_group_block_write_ul2(out, value2);
  intel_sub_group_block_write_ul4(out, value4);
  intel_sub_group_block_write_ul8(out, value8);
}
