#ifdef HAVE_S390_MIN_Z196_ZARCH_ASM_SUPPORT
# define USE_ROUND_BUILTIN 1
# define USE_ROUNDF_BUILTIN 1
# define USE_ROUNDL_BUILTIN 1
# if __GNUC_PREREQ (8, 0)
#  define USE_ROUNDF128_BUILTIN 1
# else
#  define USE_ROUNDF128_BUILTIN 0
# endif
#else
# define USE_ROUND_BUILTIN 0
# define USE_ROUNDF_BUILTIN 0
# define USE_ROUNDL_BUILTIN 0
# define USE_ROUNDF128_BUILTIN 0
#endif
