#ifdef HAVE_S390_MIN_Z196_ZARCH_ASM_SUPPORT
# define USE_NEARBYINT_BUILTIN 1
# define USE_NEARBYINTF_BUILTIN 1
# define USE_NEARBYINTL_BUILTIN 1
# if __GNUC_PREREQ (8, 0)
#  define USE_NEARBYINTF128_BUILTIN 1
# else
#  define USE_NEARBYINTF128_BUILTIN 0
# endif
#else
# define USE_NEARBYINT_BUILTIN 0
# define USE_NEARBYINTF_BUILTIN 0
# define USE_NEARBYINTL_BUILTIN 0
# define USE_NEARBYINTF128_BUILTIN 0
#endif
