#ifdef HAVE_S390_MIN_Z196_ZARCH_ASM_SUPPORT
# define USE_FLOOR_BUILTIN 1
# define USE_FLOORF_BUILTIN 1
# define USE_FLOORL_BUILTIN 1
# if __GNUC_PREREQ (8, 0)
#  define USE_FLOORF128_BUILTIN 1
# else
#  define USE_FLOORF128_BUILTIN 0
# endif
#else
# define USE_FLOOR_BUILTIN 0
# define USE_FLOORF_BUILTIN 0
# define USE_FLOORL_BUILTIN 0
# define USE_FLOORF128_BUILTIN 0
#endif
