; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -O0 -mtriple=spirv64-unknown-unknown < %s | FileCheck %s
; RUN: %if spirv-tools %{ llc -O0 -mtriple=spirv64-unknown-unknown < %s -filetype=obj | spirv-val %}

define spir_kernel void @_Z6kernelPi() addrspace(4) {
; CHECK-LABEL: _Z6kernelPi
; CHECK:       %12 = OpFunction %3 None %4 ; -- Begin function _Z6kernelPi
; CHECK-NEXT:    %17 = OpLabel
; CHECK-NEXT:    %13 = OpBitcast %6 %11
; CHECK-NEXT:    %14 = OpInBoundsPtrAccessChain %6 %13 %10
; CHECK-NEXT:    %15 = OpConvertPtrToU %5 %14
; CHECK-NEXT:    %16 = OpBitcast %6 %11
; CHECK-NEXT:    OpStore %16 %15 Aligned 4
; CHECK-NEXT:    OpReturn
; CHECK-NEXT:    OpFunctionEnd
entry:
  store i32 ptrtoint (ptr addrspace(4) getelementptr inbounds ([0 x i32], ptr addrspace(4) null, i64 0, i64 1) to i32), ptr addrspace(4) null, align 4
  ret void
}
