; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -O0 -mtriple=spirv64-unknown-unknown %s -o - | FileCheck %s

define spir_kernel void @test() {
; CHECK-LABEL: test
; CHECK:       %17 = OpFunction %2 None %3 ; -- Begin function test
; CHECK-NEXT:    %29 = OpLabel
; CHECK-NEXT:    %18 = OpCompositeExtract %4 %15 8
; CHECK-NEXT:    %19 = OpCompositeExtract %4 %15 9
; CHECK-NEXT:    %20 = OpCompositeExtract %4 %15 10
; CHECK-NEXT:    %21 = OpCompositeExtract %4 %15 11
; CHECK-NEXT:    %22 = OpCompositeExtract %4 %15 12
; CHECK-NEXT:    %23 = OpCompositeExtract %4 %15 13
; CHECK-NEXT:    %24 = OpCompositeExtract %4 %15 14
; CHECK-NEXT:    %25 = OpCompositeExtract %4 %15 15
; CHECK-NEXT:    %26 = OpCompositeConstruct %5 %18 %19 %20 %21 %22 %23 %24 %25
; CHECK-NEXT:    %27 = OpCompositeInsert %8 %26 %16 7
; CHECK-NEXT:    %28 = OpBitcast %9 %14
; CHECK-NEXT:    OpStore %28 %27 Aligned 64
; CHECK-NEXT:    OpReturn
; CHECK-NEXT:    OpFunctionEnd
  %1 = shufflevector <64 x double> zeroinitializer, <64 x double> zeroinitializer, <8 x i32> <i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  %2 = insertvalue [8 x <8 x double>] zeroinitializer, <8 x double> %1, 7
  store [8 x <8 x double>] %2, ptr addrspace(1) null, align 64
  ret void
}
