; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes='module(function(mem2reg,mergereturn),ripple,function(dce))' -S < %s | FileCheck %s --implicit-check-not="warning:"

; ModuleID = '2vecadd.c'
source_filename = "2vecadd.c"
target datalayout = "e-m:e-p:32:32:32-a:0-n16:32-i64:64:64-i32:32:32-i16:16:16-i1:8:8-f32:32:32-f64:64:64-v32:32:32-v64:64:64-v512:512:512-v1024:1024:1024-v2048:2048:2048"
; target triple = "hexagon"

; Function Attrs: nounwind
define dso_local void @foo(ptr noundef %A, ptr noundef %B, ptr noundef %C) #0 {
; CHECK-LABEL: define dso_local void @foo(
; CHECK-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], ptr noundef [[C:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 8, 0
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[MUL]], 0
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, ptr [[B]], i32 [[ADD]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <32 x float>, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[MUL1:%.*]] = mul i32 8, 0
; CHECK-NEXT:    [[ADD2:%.*]] = add i32 [[MUL1]], 0
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds float, ptr [[C]], i32 [[ADD2]]
; CHECK-NEXT:    [[TMP1:%.*]] = load <32 x float>, ptr [[ARRAYIDX3]], align 4
; CHECK-NEXT:    [[RIPPLEBINOP:%.*]] = fadd <32 x float> [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[MUL5:%.*]] = mul i32 8, 0
; CHECK-NEXT:    [[ADD6:%.*]] = add i32 [[MUL5]], 0
; CHECK-NEXT:    [[ARRAYIDX7:%.*]] = getelementptr inbounds float, ptr [[A]], i32 [[ADD6]]
; CHECK-NEXT:    store <32 x float> [[RIPPLEBINOP]], ptr [[ARRAYIDX7]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %A.addr = alloca ptr, align 4
  %B.addr = alloca ptr, align 4
  %C.addr = alloca ptr, align 4
  %v0 = alloca i32, align 4
  %v1 = alloca i32, align 4
  store ptr %A, ptr %A.addr, align 4, !tbaa !2
  store ptr %B, ptr %B.addr, align 4, !tbaa !2
  store ptr %C, ptr %C.addr, align 4, !tbaa !2
  %BS = call ptr @llvm.ripple.block.setshape.i32(i32 0, i32 8, i32 4, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1)
  call void @llvm.lifetime.start.p0(i64 4, ptr %v0) #4
  %0 = call i32 @llvm.ripple.block.index.i32(ptr %BS, i32 0)
  store i32 %0, ptr %v0, align 4, !tbaa !6
  call void @llvm.lifetime.start.p0(i64 4, ptr %v1) #4
  %1 = call i32 @llvm.ripple.block.index.i32(ptr %BS, i32 1)
  store i32 %1, ptr %v1, align 4, !tbaa !6
  %2 = load ptr, ptr %B.addr, align 4, !tbaa !2
  %3 = load i32, ptr %v1, align 4, !tbaa !6
  %mul = mul i32 8, %3
  %4 = load i32, ptr %v0, align 4, !tbaa !6
  %add = add i32 %mul, %4
  %arrayidx = getelementptr inbounds float, ptr %2, i32 %add
  %5 = load float, ptr %arrayidx, align 4, !tbaa !8
  %6 = load ptr, ptr %C.addr, align 4, !tbaa !2
  %7 = load i32, ptr %v1, align 4, !tbaa !6
  %mul1 = mul i32 8, %7
  %8 = load i32, ptr %v0, align 4, !tbaa !6
  %add2 = add i32 %mul1, %8
  %arrayidx3 = getelementptr inbounds float, ptr %6, i32 %add2
  %9 = load float, ptr %arrayidx3, align 4, !tbaa !8
  %add4 = fadd float %5, %9
  %10 = load ptr, ptr %A.addr, align 4, !tbaa !2
  %11 = load i32, ptr %v1, align 4, !tbaa !6
  %mul5 = mul i32 8, %11
  %12 = load i32, ptr %v0, align 4, !tbaa !6
  %add6 = add i32 %mul5, %12
  %arrayidx7 = getelementptr inbounds float, ptr %10, i32 %add6
  store float %add4, ptr %arrayidx7, align 4, !tbaa !8
  call void @llvm.lifetime.end.p0(i64 4, ptr %v1) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %v0) #4
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write)
declare ptr @llvm.ripple.block.setshape.i32(i32 immarg, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare i32 @llvm.ripple.block.index.i32(ptr, i32 immarg) #3

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #2

attributes #0 = { nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="-long-calls" }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write) }
attributes #2 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #3 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) }
attributes #4 = { nounwind }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"Clang $LLVM_VERSION_MAJOR.$LLVM_VERSION_MINOR"}
!2 = !{!3, !3, i64 0}
!3 = !{!"any pointer", !4, i64 0}
!4 = !{!"omnipotent char", !5, i64 0}
!5 = !{!"Simple C/C++ TBAA"}
!6 = !{!7, !7, i64 0}
!7 = !{!"int", !4, i64 0}
!8 = !{!9, !9, i64 0}
!9 = !{!"float", !4, i64 0}
