; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes='module(function(mem2reg),ripple,function(dce))' -S %s | FileCheck %s --implicit-check-not="warning:"

; ModuleID = '3vecadds.c'
source_filename = "3vecadds.c"
target datalayout = "e-m:e-p:32:32:32-a:0-n16:32-i64:64:64-i32:32:32-i16:16:16-i1:8:8-f32:32:32-f64:64:64-v32:32:32-v64:64:64-v512:512:512-v1024:1024:1024-v2048:2048:2048"
; target triple = "hexagon"

; Function Attrs: nounwind
define dso_local void @foo(ptr noundef %A, ptr noundef %B, ptr noundef %C) #0 {
; CHECK-LABEL: define dso_local void @foo(
; CHECK-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], ptr noundef [[C:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_COND:%.*]]
; CHECK:       for.cond:
; CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[ADD11:%.*]], [[FOR_INC:%.*]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i32 [[I_0]], 1024
; CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    br label [[FOR_END:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[B]], i32 [[I_0]]
; CHECK-NEXT:    [[TMP4:%.*]] = load <32 x float>, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[C]], i32 [[I_0]]
; CHECK-NEXT:    [[TMP9:%.*]] = load <32 x float>, ptr [[ARRAYIDX5]], align 4
; CHECK-NEXT:    [[RIPPLEBINOP:%.*]] = fadd <32 x float> [[TMP4]], [[TMP9]]
; CHECK-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[A]], i32 [[I_0]]
; CHECK-NEXT:    store <32 x float> [[RIPPLEBINOP]], ptr [[ARRAYIDX10]], align 4
; CHECK-NEXT:    br label [[FOR_INC]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[ADD11]] = add nuw nsw i32 [[I_0]], 32
; CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP2:![0-9]+]]
; CHECK:       for.end:
; CHECK-NEXT:    ret void
;
entry:
  %A.addr = alloca ptr, align 4
  %B.addr = alloca ptr, align 4
  %C.addr = alloca ptr, align 4
  %v0 = alloca i32, align 4
  %v1 = alloca i32, align 4
  %nv0 = alloca i32, align 4
  %i = alloca i32, align 4
  store ptr %A, ptr %A.addr, align 4, !tbaa !2
  store ptr %B, ptr %B.addr, align 4, !tbaa !2
  store ptr %C, ptr %C.addr, align 4, !tbaa !2
  %BS = call ptr @llvm.ripple.block.setshape.i32(i32 0, i32 8, i32 4, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1)
  call void @llvm.lifetime.start.p0(i64 4, ptr %v0) #4
  %0 = call i32 @llvm.ripple.block.index.i32(ptr %BS, i32 0)
  store i32 %0, ptr %v0, align 4, !tbaa !6
  call void @llvm.lifetime.start.p0(i64 4, ptr %v1) #4
  %1 = call i32 @llvm.ripple.block.index.i32(ptr %BS, i32 1)
  store i32 %1, ptr %v1, align 4, !tbaa !6
  call void @llvm.lifetime.start.p0(i64 4, ptr %nv0) #4
  %2 = call i32 @llvm.ripple.block.getsize.i32(ptr %BS, i32 0)
  store i32 %2, ptr %nv0, align 4, !tbaa !6
  call void @llvm.lifetime.start.p0(i64 4, ptr %i) #4
  store i32 0, ptr %i, align 4, !tbaa !6
  br label %for.cond

for.cond:                                         ; preds = %for.inc, %entry
  %3 = load i32, ptr %i, align 4, !tbaa !6
  %cmp = icmp slt i32 %3, 1024
  br i1 %cmp, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond
  call void @llvm.lifetime.end.p0(i64 4, ptr %i) #4
  br label %for.end

for.body:                                         ; preds = %for.cond
  %4 = load ptr, ptr %B.addr, align 4, !tbaa !2
  %5 = load i32, ptr %i, align 4, !tbaa !6
  %6 = load i32, ptr %nv0, align 4, !tbaa !6
  %7 = load i32, ptr %v1, align 4, !tbaa !6
  %mul = mul i32 %6, %7
  %add = add i32 %5, %mul
  %8 = load i32, ptr %v0, align 4, !tbaa !6
  %add1 = add i32 %add, %8
  %arrayidx = getelementptr inbounds [4 x i8], ptr %4, i32 %add1
  %9 = load float, ptr %arrayidx, align 4, !tbaa !8
  %10 = load ptr, ptr %C.addr, align 4, !tbaa !2
  %11 = load i32, ptr %i, align 4, !tbaa !6
  %12 = load i32, ptr %nv0, align 4, !tbaa !6
  %13 = load i32, ptr %v1, align 4, !tbaa !6
  %mul2 = mul i32 %12, %13
  %add3 = add i32 %11, %mul2
  %14 = load i32, ptr %v0, align 4, !tbaa !6
  %add4 = add i32 %add3, %14
  %arrayidx5 = getelementptr inbounds [4 x i8], ptr %10, i32 %add4
  %15 = load float, ptr %arrayidx5, align 4, !tbaa !8
  %add6 = fadd float %9, %15
  %16 = load ptr, ptr %A.addr, align 4, !tbaa !2
  %17 = load i32, ptr %i, align 4, !tbaa !6
  %18 = load i32, ptr %nv0, align 4, !tbaa !6
  %19 = load i32, ptr %v1, align 4, !tbaa !6
  %mul7 = mul i32 %18, %19
  %add8 = add i32 %17, %mul7
  %20 = load i32, ptr %v0, align 4, !tbaa !6
  %add9 = add i32 %add8, %20
  %arrayidx10 = getelementptr inbounds [4 x i8], ptr %16, i32 %add9
  store float %add6, ptr %arrayidx10, align 4, !tbaa !8
  br label %for.inc

for.inc:                                          ; preds = %for.body
  %21 = load i32, ptr %i, align 4, !tbaa !6
  %add11 = add nsw i32 %21, 32
  store i32 %add11, ptr %i, align 4, !tbaa !6
  br label %for.cond, !llvm.loop !10

for.end:                                          ; preds = %for.cond.cleanup
  call void @llvm.lifetime.end.p0(i64 4, ptr %nv0) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %v1) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %v0) #4
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write)
declare ptr @llvm.ripple.block.setshape.i32(i32 immarg, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare i32 @llvm.ripple.block.index.i32(ptr, i32 immarg) #3

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare i32 @llvm.ripple.block.getsize.i32(ptr, i32 immarg) #3

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #2

attributes #0 = { nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="-long-calls" }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write) }
attributes #2 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #3 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) }
attributes #4 = { nounwind }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"Clang $LLVM_VERSION_MAJOR.$LLVM_VERSION_MINOR"}
!2 = !{!3, !3, i64 0}
!3 = !{!"any pointer", !4, i64 0}
!4 = !{!"omnipotent char", !5, i64 0}
!5 = !{!"Simple C/C++ TBAA"}
!6 = !{!7, !7, i64 0}
!7 = !{!"int", !4, i64 0}
!8 = !{!9, !9, i64 0}
!9 = !{!"float", !4, i64 0}
!10 = distinct !{!10, !11, !12}
!11 = !{!"llvm.loop.mustprogress"}
!12 = !{!"llvm.loop.unroll.disable"}
;.
; CHECK: [[LOOP2]] = distinct !{[[LOOP2]], [[META3:![0-9]+]], [[META4:![0-9]+]]}
; CHECK: [[META3]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[META4]] = !{!"llvm.loop.unroll.disable"}
;.
