; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='module(ripple,function(dce))' -S < %s | FileCheck %s --implicit-check-not="warning:"

; ModuleID = '1vecadd.c'
source_filename = "1vecadd.c"
target datalayout = "e-m:e-p:32:32:32-a:0-n16:32-i64:64:64-i32:32:32-i16:16:16-i1:8:8-f32:32:32-f64:64:64-v32:32:32-v64:64:64-v512:512:512-v1024:1024:1024-v2048:2048:2048"
; target triple = "hexagon"

; Function Attrs: nounwind
define dso_local void @foo(ptr noundef %A, ptr noundef %B, ptr noundef %C) #0 {
; CHECK-LABEL: define dso_local void @foo(
; CHECK-SAME: ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], ptr noundef [[C:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 4
; CHECK-NEXT:    [[V_RIPPLE_LS_INSTANCE:%.*]] = alloca [32 x i32], align 128
; CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 4, !tbaa [[ANYPTR_TBAA2:![0-9]+]]
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[V_RIPPLE_LS_INSTANCE]])
; CHECK-NEXT:    store <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>, ptr [[V_RIPPLE_LS_INSTANCE]], align 128
; CHECK-NEXT:    [[ARRAYIDX_RIPPLE_LS_INSTANCE5:%.*]] = getelementptr inbounds [4 x i8], ptr [[B]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
; CHECK-NEXT:    [[TMP0:%.*]] = call <32 x float> @llvm.masked.gather.v32f32.v32p0(<32 x ptr> align 4 [[ARRAYIDX_RIPPLE_LS_INSTANCE5]], <32 x i1> splat (i1 true), <32 x float> poison)
; CHECK-NEXT:    [[ARRAYIDX1_RIPPLE_LS_INSTANCE6:%.*]] = getelementptr inbounds [4 x i8], ptr [[C]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
; CHECK-NEXT:    [[TMP1:%.*]] = call <32 x float> @llvm.masked.gather.v32f32.v32p0(<32 x ptr> align 4 [[ARRAYIDX1_RIPPLE_LS_INSTANCE6]], <32 x i1> splat (i1 true), <32 x float> poison)
; CHECK-NEXT:    [[ADD_RIPPLE_VECTORIZED:%.*]] = fadd <32 x float> [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[DOTRIPPLE_LS_INSTANCE4:%.*]] = load ptr, ptr [[A_ADDR]], align 4, !tbaa [[ANYPTR_TBAA2]]
; CHECK-NEXT:    [[DOTRIPPLE3:%.*]] = load <32 x i32>, ptr [[V_RIPPLE_LS_INSTANCE]], align 128
; CHECK-NEXT:    [[ARRAYIDX2_RIPPLE_LS_INSTANCE7:%.*]] = getelementptr inbounds [4 x i8], ptr [[DOTRIPPLE_LS_INSTANCE4]], <32 x i32> [[DOTRIPPLE3]]
; CHECK-NEXT:    call void @llvm.masked.scatter.v32f32.v32p0(<32 x float> [[ADD_RIPPLE_VECTORIZED]], <32 x ptr> align 4 [[ARRAYIDX2_RIPPLE_LS_INSTANCE7]], <32 x i1> splat (i1 true))
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[V_RIPPLE_LS_INSTANCE]])
; CHECK-NEXT:    ret void
;
entry:
  %A.addr = alloca ptr, align 4
  %B.addr = alloca ptr, align 4
  %C.addr = alloca ptr, align 4
  %v = alloca i32, align 4
  store ptr %A, ptr %A.addr, align 4, !tbaa !2
  store ptr %B, ptr %B.addr, align 4, !tbaa !2
  store ptr %C, ptr %C.addr, align 4, !tbaa !2
  %BS = call ptr @llvm.ripple.block.setshape.i32(i32 0, i32 32, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1)
  call void @llvm.lifetime.start.p0(i64 4, ptr %v) #4
  %0 = call i32 @llvm.ripple.block.index.i32(ptr %BS, i32 0)
  store i32 %0, ptr %v, align 4, !tbaa !6
  %1 = load ptr, ptr %B.addr, align 4, !tbaa !2
  %2 = load i32, ptr %v, align 4, !tbaa !6
  %arrayidx = getelementptr inbounds float, ptr %1, i32 %2
  %3 = load float, ptr %arrayidx, align 4, !tbaa !8
  %4 = load ptr, ptr %C.addr, align 4, !tbaa !2
  %5 = load i32, ptr %v, align 4, !tbaa !6
  %arrayidx1 = getelementptr inbounds float, ptr %4, i32 %5
  %6 = load float, ptr %arrayidx1, align 4, !tbaa !8
  %add = fadd float %3, %6
  %7 = load ptr, ptr %A.addr, align 4, !tbaa !2
  %8 = load i32, ptr %v, align 4, !tbaa !6
  %arrayidx2 = getelementptr inbounds float, ptr %7, i32 %8
  store float %add, ptr %arrayidx2, align 4, !tbaa !8
  call void @llvm.lifetime.end.p0(i64 4, ptr %v) #4
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write)
declare ptr @llvm.ripple.block.setshape.i32(i32 immarg, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read)
declare i32 @llvm.ripple.block.index.i32(ptr, i32 immarg) #3

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #2

attributes #0 = { nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="-long-calls" }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write) }
attributes #2 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #3 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: read) }
attributes #4 = { nounwind }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"Clang $LLVM_VERSION_MAJOR.$LLVM_VERSION_MINOR"}
!2 = !{!3, !3, i64 0}
!3 = !{!"any pointer", !4, i64 0}
!4 = !{!"omnipotent char", !5, i64 0}
!5 = !{!"Simple C/C++ TBAA"}
!6 = !{!7, !7, i64 0}
!7 = !{!"int", !4, i64 0}
!8 = !{!9, !9, i64 0}
!9 = !{!"float", !4, i64 0}
;.
; CHECK: [[ANYPTR_TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
; CHECK: [[META3]] = !{!"any pointer", [[META4:![0-9]+]], i64 0}
; CHECK: [[META4]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
; CHECK: [[META5]] = !{!"Simple C/C++ TBAA"}
;.
