; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=ripple,dce -S < %s | FileCheck %s --implicit-check-not="warning:"

target datalayout = "e-m:e-p:32:32:32-a:0-n16:32-i64:64:64-i32:32:32-i16:16:16-i1:8:8-f32:32:32-f64:64:64-v32:32:32-v64:64:64-v512:512:512-v1024:1024:1024-v2048:2048:2048"

; Function Attrs: nofree norecurse nounwind
define dso_local void @moments_f2(i32 noundef %n_in_red, i32 noundef %n_contig_el, i32 noundef %inner_red, i32 noundef %outer_red, ptr nocapture noundef writeonly %mean_out, ptr nocapture noundef writeonly %variance_out, ptr nocapture noundef readonly %inp) local_unnamed_addr {
; CHECK-LABEL: define dso_local void @moments_f2(
; CHECK-SAME: i32 noundef [[N_IN_RED:%.*]], i32 noundef [[N_CONTIG_EL:%.*]], i32 noundef [[INNER_RED:%.*]], i32 noundef [[OUTER_RED:%.*]], ptr noundef writeonly captures(none) [[MEAN_OUT:%.*]], ptr noundef writeonly captures(none) [[VARIANCE_OUT:%.*]], ptr noundef readonly captures(none) [[INP:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[N_CONTIG_EL_RIPPLE_BCAST_SPLATINSERT:%.*]] = insertelement <32 x i32> poison, i32 [[N_CONTIG_EL]], i64 0
; CHECK-NEXT:    [[N_CONTIG_EL_RIPPLE_BCAST_SPLAT:%.*]] = shufflevector <32 x i32> [[N_CONTIG_EL_RIPPLE_BCAST_SPLATINSERT]], <32 x i32> poison, <32 x i32> zeroinitializer
; CHECK-NEXT:    [[N_IN_RED_RIPPLE_BCAST_SPLATINSERT:%.*]] = insertelement <4 x i32> poison, i32 [[N_IN_RED]], i64 0
; CHECK-NEXT:    [[N_IN_RED_RIPPLE_BCAST_SPLAT:%.*]] = shufflevector <4 x i32> [[N_IN_RED_RIPPLE_BCAST_SPLATINSERT]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[CMP140_NOT:%.*]] = icmp eq i32 [[N_IN_RED]], 0
; CHECK-NEXT:    br i1 [[CMP140_NOT]], label %[[FOR_COND_CLEANUP:.*]], label %[[FOR_COND1_PREHEADER_LR_PH:.*]]
; CHECK:       [[FOR_COND1_PREHEADER_LR_PH]]:
; CHECK-NEXT:    [[FACTOR_OP_MUL139:%.*]] = mul i32 [[INNER_RED]], [[N_IN_RED]]
; CHECK-NEXT:    [[FACTOR_OP_MUL136:%.*]] = mul i32 [[FACTOR_OP_MUL139]], [[N_CONTIG_EL]]
; CHECK-NEXT:    [[CMP2137_NOT:%.*]] = icmp eq i32 [[N_CONTIG_EL]], 0
; CHECK-NEXT:    [[FACTOR_OP_MUL124:%.*]] = mul i32 [[INNER_RED]], [[N_CONTIG_EL]]
; CHECK-NEXT:    [[CMP10125_NOT:%.*]] = icmp eq i32 [[OUTER_RED]], 0
; CHECK-NEXT:    [[CMP15119_NOT:%.*]] = icmp eq i32 [[INNER_RED]], 0
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 [[OUTER_RED]], [[INNER_RED]]
; CHECK-NEXT:    [[CONV43:%.*]] = uitofp i32 [[MUL]] to float
; CHECK-NEXT:    [[CONV43_RIPPLE_BCAST_SPLATINSERT62:%.*]] = insertelement <128 x float> poison, float [[CONV43]], i64 0
; CHECK-NEXT:    [[CONV43_RIPPLE_BCAST_SPLAT63:%.*]] = shufflevector <128 x float> [[CONV43_RIPPLE_BCAST_SPLATINSERT62]], <128 x float> poison, <128 x i32> zeroinitializer
; CHECK-NEXT:    [[CONV43_RIPPLE_BCAST_SPLATINSERT:%.*]] = insertelement <128 x float> poison, float [[CONV43]], i64 0
; CHECK-NEXT:    [[CONV43_RIPPLE_BCAST_SPLAT:%.*]] = shufflevector <128 x float> [[CONV43_RIPPLE_BCAST_SPLATINSERT]], <128 x float> poison, <128 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[FOR_COND1_PREHEADER:.*]]
; CHECK:       [[FOR_COND1_PREHEADER]]:
; CHECK-NEXT:    [[N_0141:%.*]] = phi i32 [ 0, %[[FOR_COND1_PREHEADER_LR_PH]] ], [ [[ADD62:%.*]], %[[FOR_COND_CLEANUP3:.*]] ]
; CHECK-NEXT:    br i1 [[CMP2137_NOT]], label %[[FOR_COND_CLEANUP3]], label %[[FOR_BODY4_LR_PH:.*]]
; CHECK:       [[FOR_BODY4_LR_PH]]:
; CHECK-NEXT:    [[ADD_RIPPLE_BCAST_SPLATINSERT:%.*]] = insertelement <4 x i32> poison, i32 [[N_0141]], i64 0
; CHECK-NEXT:    [[ADD_RIPPLE_BCAST_SPLAT:%.*]] = shufflevector <4 x i32> [[ADD_RIPPLE_BCAST_SPLATINSERT]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[ADD_RIPPLE_LS_INSTANCE:%.*]] = or disjoint <4 x i32> [[ADD_RIPPLE_BCAST_SPLAT]], <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    [[CMP5_RIPPLE_LS_INSTANCE:%.*]] = icmp ult <4 x i32> [[ADD_RIPPLE_LS_INSTANCE]], [[N_IN_RED_RIPPLE_BCAST_SPLAT]]
; CHECK-NEXT:    [[CMP5_RIPPLE_LS_INSTANCE_RIPPLE_BCAST:%.*]] = shufflevector <4 x i1> [[CMP5_RIPPLE_LS_INSTANCE]], <4 x i1> poison, <128 x i32> <i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3>
; CHECK-NEXT:    [[FACTOR_OP_MUL118:%.*]] = mul i32 [[FACTOR_OP_MUL124]], [[N_0141]]
; CHECK-NEXT:    [[RIPPLE_SLOPE_GEP_INBYTES11:%.*]] = shl i32 [[FACTOR_OP_MUL124]], 2
; CHECK-NEXT:    [[INVARIANT_GEP132:%.*]] = getelementptr [4 x i8], ptr [[INP]], i32 [[FACTOR_OP_MUL118]]
; CHECK-NEXT:    [[TMP0:%.*]] = mul nsw i32 [[N_0141]], [[N_CONTIG_EL]]
; CHECK-NEXT:    [[RIPPLE_SLOPE_GEP_INBYTES17:%.*]] = shl i32 [[N_CONTIG_EL]], 2
; CHECK-NEXT:    [[ARRAYIDX46:%.*]] = getelementptr inbounds [4 x i8], ptr [[MEAN_OUT]], i32 [[TMP0]]
; CHECK-NEXT:    [[RIPPLE_SLOPE_GEP_INBYTES21:%.*]] = shl i32 [[N_CONTIG_EL]], 2
; CHECK-NEXT:    [[ARRAYIDX55:%.*]] = getelementptr inbounds [4 x i8], ptr [[VARIANCE_OUT]], i32 [[TMP0]]
; CHECK-NEXT:    br label %[[FOR_BODY4:.*]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_COND_CLEANUP3]]:
; CHECK-NEXT:    [[ADD62]] = add i32 [[N_0141]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[ADD62]], [[N_IN_RED]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[FOR_COND1_PREHEADER]], label %[[FOR_COND_CLEANUP]]
; CHECK:       [[FOR_BODY4]]:
; CHECK-NEXT:    [[J_0138:%.*]] = phi i32 [ 0, %[[FOR_BODY4_LR_PH]] ], [ [[ADD59:%.*]], %[[FOR_INC58:.*]] ]
; CHECK-NEXT:    [[ADD6_RIPPLE_BCAST_SPLATINSERT:%.*]] = insertelement <32 x i32> poison, i32 [[J_0138]], i64 0
; CHECK-NEXT:    [[ADD6_RIPPLE_BCAST_SPLAT:%.*]] = shufflevector <32 x i32> [[ADD6_RIPPLE_BCAST_SPLATINSERT]], <32 x i32> poison, <32 x i32> zeroinitializer
; CHECK-NEXT:    [[ADD6_RIPPLE_LS_INSTANCE:%.*]] = or disjoint <32 x i32> [[ADD6_RIPPLE_BCAST_SPLAT]], <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
; CHECK-NEXT:    [[CMP7_RIPPLE_LS_INSTANCE:%.*]] = icmp ult <32 x i32> [[ADD6_RIPPLE_LS_INSTANCE]], [[N_CONTIG_EL_RIPPLE_BCAST_SPLAT]]
; CHECK-NEXT:    [[CMP7_RIPPLE_LS_INSTANCE_RIPPLE_BCAST:%.*]] = shufflevector <32 x i1> [[CMP7_RIPPLE_LS_INSTANCE]], <32 x i1> poison, <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
; CHECK-NEXT:    [[AND116_RIPPLE_LS_INSTANCE:%.*]] = and <128 x i1> [[CMP5_RIPPLE_LS_INSTANCE_RIPPLE_BCAST]], [[CMP7_RIPPLE_LS_INSTANCE_RIPPLE_BCAST]]
; CHECK-NEXT:    br label %[[FOR_COND9_PREHEADER_RIPPLE_VECBRANCH_SUCC_RIPPLE_BRANCH_CLONE:.*]]
; CHECK:       [[FOR_INC58RIPPLE_VECBRANCH_SELECTBLOCK:.*]]:
; CHECK-NEXT:    br label %[[FOR_INC58]]
; CHECK:       [[FOR_INC58]]:
; CHECK-NEXT:    [[ADD59]] = add i32 [[J_0138]], 32
; CHECK-NEXT:    [[CMP2:%.*]] = icmp ult i32 [[ADD59]], [[N_CONTIG_EL]]
; CHECK-NEXT:    br i1 [[CMP2]], label %[[FOR_BODY4]], label %[[FOR_COND_CLEANUP3]]
; CHECK:       [[FOR_COND9_PREHEADER_RIPPLE_VECBRANCH_SUCC_RIPPLE_BRANCH_CLONE]]:
; CHECK-NEXT:    br label %[[FOR_COND9_PREHEADER_RIPPLE_BRANCH_CLONE:.*]]
; CHECK:       [[FOR_COND9_PREHEADER_RIPPLE_BRANCH_CLONE]]:
; CHECK-NEXT:    br i1 [[CMP10125_NOT]], label %[[FOR_COND_CLEANUP12_RIPPLE_BRANCH_CLONE:.*]], label %[[FOR_COND14_PREHEADER_LR_PH_RIPPLE_BRANCH_CLONE:.*]]
; CHECK:       [[FOR_COND_CLEANUP12_RIPPLE_BRANCH_CLONE]]:
; CHECK-NEXT:    [[SUM_0_LCSSA_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE:%.*]] = phi <128 x float> [ zeroinitializer, %[[FOR_COND9_PREHEADER_RIPPLE_BRANCH_CLONE]] ], [ [[SUM_1_LCSSA_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE:%.*]], %[[FOR_COND_CLEANUP17_RIPPLE_BRANCH_CLONE:.*]] ]
; CHECK-NEXT:    [[SUM2_0_LCSSA_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE:%.*]] = phi <128 x float> [ zeroinitializer, %[[FOR_COND9_PREHEADER_RIPPLE_BRANCH_CLONE]] ], [ [[SUM2_1_LCSSA_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE:%.*]], %[[FOR_COND_CLEANUP17_RIPPLE_BRANCH_CLONE]] ]
; CHECK-NEXT:    [[DIV_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE:%.*]] = fdiv <128 x float> [[SUM_0_LCSSA_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]], [[CONV43_RIPPLE_BCAST_SPLAT]]
; CHECK-NEXT:    [[ARRAYIDX48_RIPPLE_BRANCH_CLONE:%.*]] = getelementptr inbounds [4 x i8], ptr [[ARRAYIDX46]], i32 [[J_0138]]
; CHECK-NEXT:    [[ARRAYIDX48_RIPPLE_LS_DIM_SLOPE_BCAST_SPLATINSERT_RIPPLE_BRANCH_CLONE:%.*]] = insertelement <4 x i32> poison, i32 [[RIPPLE_SLOPE_GEP_INBYTES17]], i64 0
; CHECK-NEXT:    [[ARRAYIDX48_RIPPLE_LS_DIM_SLOPE_BCAST_SPLAT_RIPPLE_BRANCH_CLONE:%.*]] = shufflevector <4 x i32> [[ARRAYIDX48_RIPPLE_LS_DIM_SLOPE_BCAST_SPLATINSERT_RIPPLE_BRANCH_CLONE]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[ARRAYIDX48_RIPPLE_LS_DIM_SLOPE_RIPPLE_BRANCH_CLONE:%.*]] = mul <4 x i32> [[ARRAYIDX48_RIPPLE_LS_DIM_SLOPE_BCAST_SPLAT_RIPPLE_BRANCH_CLONE]], <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    [[ARRAYIDX48_RIPPLE_LS_DIM_SLOPE_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE:%.*]] = shufflevector <4 x i32> [[ARRAYIDX48_RIPPLE_LS_DIM_SLOPE_RIPPLE_BRANCH_CLONE]], <4 x i32> poison, <128 x i32> <i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3>
; CHECK-NEXT:    [[ARRAYIDX48_RIPPLE_LS_SLOPE_RIPPLE_BRANCH_CLONE:%.*]] = add <128 x i32> [[ARRAYIDX48_RIPPLE_LS_DIM_SLOPE_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE]], <i32 0, i32 4, i32 8, i32 12, i32 16, i32 20, i32 24, i32 28, i32 32, i32 36, i32 40, i32 44, i32 48, i32 52, i32 56, i32 60, i32 64, i32 68, i32 72, i32 76, i32 80, i32 84, i32 88, i32 92, i32 96, i32 100, i32 104, i32 108, i32 112, i32 116, i32 120, i32 124, i32 0, i32 4, i32 8, i32 12, i32 16, i32 20, i32 24, i32 28, i32 32, i32 36, i32 40, i32 44, i32 48, i32 52, i32 56, i32 60, i32 64, i32 68, i32 72, i32 76, i32 80, i32 84, i32 88, i32 92, i32 96, i32 100, i32 104, i32 108, i32 112, i32 116, i32 120, i32 124, i32 0, i32 4, i32 8, i32 12, i32 16, i32 20, i32 24, i32 28, i32 32, i32 36, i32 40, i32 44, i32 48, i32 52, i32 56, i32 60, i32 64, i32 68, i32 72, i32 76, i32 80, i32 84, i32 88, i32 92, i32 96, i32 100, i32 104, i32 108, i32 112, i32 116, i32 120, i32 124, i32 0, i32 4, i32 8, i32 12, i32 16, i32 20, i32 24, i32 28, i32 32, i32 36, i32 40, i32 44, i32 48, i32 52, i32 56, i32 60, i32 64, i32 68, i32 72, i32 76, i32 80, i32 84, i32 88, i32 92, i32 96, i32 100, i32 104, i32 108, i32 112, i32 116, i32 120, i32 124>
; CHECK-NEXT:    [[ARRAYIDX48_RIPPLE_LS_INSTANCE_RIPPLE_BRANCH_CLONE:%.*]] = getelementptr i8, ptr [[ARRAYIDX48_RIPPLE_BRANCH_CLONE]], <128 x i32> [[ARRAYIDX48_RIPPLE_LS_SLOPE_RIPPLE_BRANCH_CLONE]]
; CHECK-NEXT:    call void @llvm.masked.scatter.v128f32.v128p0(<128 x float> [[DIV_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]], <128 x ptr> align 4 [[ARRAYIDX48_RIPPLE_LS_INSTANCE_RIPPLE_BRANCH_CLONE]], <128 x i1> [[AND116_RIPPLE_LS_INSTANCE]])
; CHECK-NEXT:    [[DIV51_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE:%.*]] = fdiv <128 x float> [[SUM2_0_LCSSA_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]], [[CONV43_RIPPLE_BCAST_SPLAT63]]
; CHECK-NEXT:    [[NEG_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE:%.*]] = fneg <128 x float> [[DIV_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]]
; CHECK-NEXT:    [[DOTRIPPLE_VECTORIZED64_RIPPLE_BRANCH_CLONE:%.*]] = call <128 x float> @llvm.fmuladd.v128f32(<128 x float> [[NEG_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]], <128 x float> [[DIV_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]], <128 x float> [[DIV51_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]])
; CHECK-NEXT:    [[ARRAYIDX57_RIPPLE_BRANCH_CLONE:%.*]] = getelementptr inbounds [4 x i8], ptr [[ARRAYIDX55]], i32 [[J_0138]]
; CHECK-NEXT:    [[ARRAYIDX57_RIPPLE_LS_DIM_SLOPE_BCAST_SPLATINSERT_RIPPLE_BRANCH_CLONE:%.*]] = insertelement <4 x i32> poison, i32 [[RIPPLE_SLOPE_GEP_INBYTES21]], i64 0
; CHECK-NEXT:    [[ARRAYIDX57_RIPPLE_LS_DIM_SLOPE_BCAST_SPLAT_RIPPLE_BRANCH_CLONE:%.*]] = shufflevector <4 x i32> [[ARRAYIDX57_RIPPLE_LS_DIM_SLOPE_BCAST_SPLATINSERT_RIPPLE_BRANCH_CLONE]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[ARRAYIDX57_RIPPLE_LS_DIM_SLOPE_RIPPLE_BRANCH_CLONE:%.*]] = mul <4 x i32> [[ARRAYIDX57_RIPPLE_LS_DIM_SLOPE_BCAST_SPLAT_RIPPLE_BRANCH_CLONE]], <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    [[ARRAYIDX57_RIPPLE_LS_DIM_SLOPE_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE:%.*]] = shufflevector <4 x i32> [[ARRAYIDX57_RIPPLE_LS_DIM_SLOPE_RIPPLE_BRANCH_CLONE]], <4 x i32> poison, <128 x i32> <i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3>
; CHECK-NEXT:    [[ARRAYIDX57_RIPPLE_LS_SLOPE_RIPPLE_BRANCH_CLONE:%.*]] = add <128 x i32> [[ARRAYIDX57_RIPPLE_LS_DIM_SLOPE_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE]], <i32 0, i32 4, i32 8, i32 12, i32 16, i32 20, i32 24, i32 28, i32 32, i32 36, i32 40, i32 44, i32 48, i32 52, i32 56, i32 60, i32 64, i32 68, i32 72, i32 76, i32 80, i32 84, i32 88, i32 92, i32 96, i32 100, i32 104, i32 108, i32 112, i32 116, i32 120, i32 124, i32 0, i32 4, i32 8, i32 12, i32 16, i32 20, i32 24, i32 28, i32 32, i32 36, i32 40, i32 44, i32 48, i32 52, i32 56, i32 60, i32 64, i32 68, i32 72, i32 76, i32 80, i32 84, i32 88, i32 92, i32 96, i32 100, i32 104, i32 108, i32 112, i32 116, i32 120, i32 124, i32 0, i32 4, i32 8, i32 12, i32 16, i32 20, i32 24, i32 28, i32 32, i32 36, i32 40, i32 44, i32 48, i32 52, i32 56, i32 60, i32 64, i32 68, i32 72, i32 76, i32 80, i32 84, i32 88, i32 92, i32 96, i32 100, i32 104, i32 108, i32 112, i32 116, i32 120, i32 124, i32 0, i32 4, i32 8, i32 12, i32 16, i32 20, i32 24, i32 28, i32 32, i32 36, i32 40, i32 44, i32 48, i32 52, i32 56, i32 60, i32 64, i32 68, i32 72, i32 76, i32 80, i32 84, i32 88, i32 92, i32 96, i32 100, i32 104, i32 108, i32 112, i32 116, i32 120, i32 124>
; CHECK-NEXT:    [[ARRAYIDX57_RIPPLE_LS_INSTANCE_RIPPLE_BRANCH_CLONE:%.*]] = getelementptr i8, ptr [[ARRAYIDX57_RIPPLE_BRANCH_CLONE]], <128 x i32> [[ARRAYIDX57_RIPPLE_LS_SLOPE_RIPPLE_BRANCH_CLONE]]
; CHECK-NEXT:    call void @llvm.masked.scatter.v128f32.v128p0(<128 x float> [[DOTRIPPLE_VECTORIZED64_RIPPLE_BRANCH_CLONE]], <128 x ptr> align 4 [[ARRAYIDX57_RIPPLE_LS_INSTANCE_RIPPLE_BRANCH_CLONE]], <128 x i1> [[AND116_RIPPLE_LS_INSTANCE]])
; CHECK-NEXT:    br label %[[FOR_INC58_RIPPLE_PREDSPLIT_RIPPLE_BRANCH_CLONE:.*]]
; CHECK:       [[FOR_COND14_PREHEADER_LR_PH_RIPPLE_BRANCH_CLONE]]:
; CHECK-NEXT:    [[INVARIANT_GEP134_RIPPLE_BRANCH_CLONE:%.*]] = getelementptr [4 x i8], ptr [[INVARIANT_GEP132]], i32 [[J_0138]]
; CHECK-NEXT:    br label %[[FOR_COND14_PREHEADER_RIPPLE_BRANCH_CLONE:.*]]
; CHECK:       [[FOR_INC58_RIPPLE_PREDSPLIT_RIPPLE_BRANCH_CLONE]]:
; CHECK-NEXT:    br label %[[FOR_INC58_RIPPLE_VECBRANCH_SUCC_RIPPLE_BRANCH_CLONE:.*]]
; CHECK:       [[FOR_COND14_PREHEADER_RIPPLE_BRANCH_CLONE]]:
; CHECK-NEXT:    [[I_0128_RIPPLE_BRANCH_CLONE:%.*]] = phi i32 [ 0, %[[FOR_COND14_PREHEADER_LR_PH_RIPPLE_BRANCH_CLONE]] ], [ [[INC41_RIPPLE_BRANCH_CLONE:%.*]], %[[FOR_COND_CLEANUP17_RIPPLE_BRANCH_CLONE]] ]
; CHECK-NEXT:    [[SUM2_0127_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE:%.*]] = phi <128 x float> [ zeroinitializer, %[[FOR_COND14_PREHEADER_LR_PH_RIPPLE_BRANCH_CLONE]] ], [ [[SUM2_1_LCSSA_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]], %[[FOR_COND_CLEANUP17_RIPPLE_BRANCH_CLONE]] ]
; CHECK-NEXT:    [[SUM_0126_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE:%.*]] = phi <128 x float> [ zeroinitializer, %[[FOR_COND14_PREHEADER_LR_PH_RIPPLE_BRANCH_CLONE]] ], [ [[SUM_1_LCSSA_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]], %[[FOR_COND_CLEANUP17_RIPPLE_BRANCH_CLONE]] ]
; CHECK-NEXT:    br i1 [[CMP15119_NOT]], label %[[FOR_COND_CLEANUP17_RIPPLE_BRANCH_CLONE]], label %[[FOR_BODY18_LR_PH_RIPPLE_BRANCH_CLONE:.*]]
; CHECK:       [[FOR_COND_CLEANUP17_RIPPLE_BRANCH_CLONE]]:
; CHECK-NEXT:    [[SUM_1_LCSSA_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]] = phi <128 x float> [ [[SUM_0126_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]], %[[FOR_COND14_PREHEADER_RIPPLE_BRANCH_CLONE]] ], [ [[ADD25_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE:%.*]], %[[FOR_BODY18_RIPPLE_BRANCH_CLONE:.*]] ]
; CHECK-NEXT:    [[SUM2_1_LCSSA_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]] = phi <128 x float> [ [[SUM2_0127_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]], %[[FOR_COND14_PREHEADER_RIPPLE_BRANCH_CLONE]] ], [ [[DOTRIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE:%.*]], %[[FOR_BODY18_RIPPLE_BRANCH_CLONE]] ]
; CHECK-NEXT:    [[INC41_RIPPLE_BRANCH_CLONE]] = add nuw i32 [[I_0128_RIPPLE_BRANCH_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND142_NOT_RIPPLE_BRANCH_CLONE:%.*]] = icmp eq i32 [[INC41_RIPPLE_BRANCH_CLONE]], [[OUTER_RED]]
; CHECK-NEXT:    br i1 [[EXITCOND142_NOT_RIPPLE_BRANCH_CLONE]], label %[[FOR_COND_CLEANUP12_RIPPLE_BRANCH_CLONE]], label %[[FOR_COND14_PREHEADER_RIPPLE_BRANCH_CLONE]]
; CHECK:       [[FOR_BODY18_LR_PH_RIPPLE_BRANCH_CLONE]]:
; CHECK-NEXT:    [[FACTOR_OP_MUL117_RIPPLE_BRANCH_CLONE:%.*]] = mul i32 [[FACTOR_OP_MUL136]], [[I_0128_RIPPLE_BRANCH_CLONE]]
; CHECK-NEXT:    [[GEP135_RIPPLE_BRANCH_CLONE:%.*]] = getelementptr [4 x i8], ptr [[INVARIANT_GEP134_RIPPLE_BRANCH_CLONE]], i32 [[FACTOR_OP_MUL117_RIPPLE_BRANCH_CLONE]]
; CHECK-NEXT:    br label %[[FOR_BODY18_RIPPLE_BRANCH_CLONE]]
; CHECK:       [[FOR_BODY18_RIPPLE_BRANCH_CLONE]]:
; CHECK-NEXT:    [[B_0122_RIPPLE_BRANCH_CLONE:%.*]] = phi i32 [ 0, %[[FOR_BODY18_LR_PH_RIPPLE_BRANCH_CLONE]] ], [ [[INC_RIPPLE_BRANCH_CLONE:%.*]], %[[FOR_BODY18_RIPPLE_BRANCH_CLONE]] ]
; CHECK-NEXT:    [[SUM2_1121_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE:%.*]] = phi <128 x float> [ [[SUM2_0127_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]], %[[FOR_BODY18_LR_PH_RIPPLE_BRANCH_CLONE]] ], [ [[DOTRIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]], %[[FOR_BODY18_RIPPLE_BRANCH_CLONE]] ]
; CHECK-NEXT:    [[SUM_1120_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE:%.*]] = phi <128 x float> [ [[SUM_0126_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]], %[[FOR_BODY18_LR_PH_RIPPLE_BRANCH_CLONE]] ], [ [[ADD25_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]], %[[FOR_BODY18_RIPPLE_BRANCH_CLONE]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = mul nsw i32 [[B_0122_RIPPLE_BRANCH_CLONE]], [[N_CONTIG_EL]]
; CHECK-NEXT:    [[GEP_RIPPLE_BRANCH_CLONE:%.*]] = getelementptr [4 x i8], ptr [[GEP135_RIPPLE_BRANCH_CLONE]], i32 [[TMP1]]
; CHECK-NEXT:    [[GEP_RIPPLE_LS_DIM_SLOPE_BCAST_SPLATINSERT57_RIPPLE_BRANCH_CLONE:%.*]] = insertelement <4 x i32> poison, i32 [[RIPPLE_SLOPE_GEP_INBYTES11]], i64 0
; CHECK-NEXT:    [[GEP_RIPPLE_LS_DIM_SLOPE_BCAST_SPLAT58_RIPPLE_BRANCH_CLONE:%.*]] = shufflevector <4 x i32> [[GEP_RIPPLE_LS_DIM_SLOPE_BCAST_SPLATINSERT57_RIPPLE_BRANCH_CLONE]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[GEP_RIPPLE_LS_DIM_SLOPE59_RIPPLE_BRANCH_CLONE:%.*]] = mul <4 x i32> [[GEP_RIPPLE_LS_DIM_SLOPE_BCAST_SPLAT58_RIPPLE_BRANCH_CLONE]], <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    [[GEP_RIPPLE_LS_DIM_SLOPE59_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE:%.*]] = shufflevector <4 x i32> [[GEP_RIPPLE_LS_DIM_SLOPE59_RIPPLE_BRANCH_CLONE]], <4 x i32> poison, <128 x i32> <i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3>
; CHECK-NEXT:    [[GEP_RIPPLE_LS_SLOPE60_RIPPLE_BRANCH_CLONE:%.*]] = add <128 x i32> [[GEP_RIPPLE_LS_DIM_SLOPE59_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE]], <i32 0, i32 4, i32 8, i32 12, i32 16, i32 20, i32 24, i32 28, i32 32, i32 36, i32 40, i32 44, i32 48, i32 52, i32 56, i32 60, i32 64, i32 68, i32 72, i32 76, i32 80, i32 84, i32 88, i32 92, i32 96, i32 100, i32 104, i32 108, i32 112, i32 116, i32 120, i32 124, i32 0, i32 4, i32 8, i32 12, i32 16, i32 20, i32 24, i32 28, i32 32, i32 36, i32 40, i32 44, i32 48, i32 52, i32 56, i32 60, i32 64, i32 68, i32 72, i32 76, i32 80, i32 84, i32 88, i32 92, i32 96, i32 100, i32 104, i32 108, i32 112, i32 116, i32 120, i32 124, i32 0, i32 4, i32 8, i32 12, i32 16, i32 20, i32 24, i32 28, i32 32, i32 36, i32 40, i32 44, i32 48, i32 52, i32 56, i32 60, i32 64, i32 68, i32 72, i32 76, i32 80, i32 84, i32 88, i32 92, i32 96, i32 100, i32 104, i32 108, i32 112, i32 116, i32 120, i32 124, i32 0, i32 4, i32 8, i32 12, i32 16, i32 20, i32 24, i32 28, i32 32, i32 36, i32 40, i32 44, i32 48, i32 52, i32 56, i32 60, i32 64, i32 68, i32 72, i32 76, i32 80, i32 84, i32 88, i32 92, i32 96, i32 100, i32 104, i32 108, i32 112, i32 116, i32 120, i32 124>
; CHECK-NEXT:    [[GEP_RIPPLE_LS_INSTANCE61_RIPPLE_BRANCH_CLONE:%.*]] = getelementptr i8, ptr [[GEP_RIPPLE_BRANCH_CLONE]], <128 x i32> [[GEP_RIPPLE_LS_SLOPE60_RIPPLE_BRANCH_CLONE]]
; CHECK-NEXT:    [[TMP2:%.*]] = call <128 x float> @llvm.masked.gather.v128f32.v128p0(<128 x ptr> align 4 [[GEP_RIPPLE_LS_INSTANCE61_RIPPLE_BRANCH_CLONE]], <128 x i1> [[AND116_RIPPLE_LS_INSTANCE]], <128 x float> poison)
; CHECK-NEXT:    [[ADD25_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]] = fadd <128 x float> [[SUM_1120_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]], [[TMP2]]
; CHECK-NEXT:    [[DOTRIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]] = call <128 x float> @llvm.fmuladd.v128f32(<128 x float> [[TMP2]], <128 x float> [[TMP2]], <128 x float> [[SUM2_1121_RIPPLE_VECTORIZED_RIPPLE_BRANCH_CLONE]])
; CHECK-NEXT:    [[INC_RIPPLE_BRANCH_CLONE]] = add nuw i32 [[B_0122_RIPPLE_BRANCH_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_RIPPLE_BRANCH_CLONE:%.*]] = icmp eq i32 [[INC_RIPPLE_BRANCH_CLONE]], [[INNER_RED]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_RIPPLE_BRANCH_CLONE]], label %[[FOR_COND_CLEANUP17_RIPPLE_BRANCH_CLONE]], label %[[FOR_BODY18_RIPPLE_BRANCH_CLONE]]
; CHECK:       [[FOR_INC58_RIPPLE_VECBRANCH_SUCC_RIPPLE_BRANCH_CLONE]]:
; CHECK-NEXT:    br label %[[FOR_INC58_RIPPLE_PREDSPLIT_RIPPLE_BRANCH_CLONE67:.*]]
; CHECK:       [[FOR_INC58_RIPPLE_PREDSPLIT_RIPPLE_BRANCH_CLONE67]]:
; CHECK-NEXT:    br label %[[FOR_INC58RIPPLE_VECBRANCH_SELECTBLOCK]]
;
entry:
  %BS = tail call ptr @llvm.ripple.block.setshape(i32 0, i32 32, i32 4, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1)
  %0 = tail call i32 @llvm.ripple.block.getsize(ptr %BS, i32 0)
  %1 = tail call i32 @llvm.ripple.block.getsize(ptr %BS, i32 1)
  %2 = tail call i32 @llvm.ripple.block.index(ptr %BS, i32 0)
  %3 = tail call i32 @llvm.ripple.block.index(ptr %BS, i32 1)
  %cmp140.not = icmp eq i32 %n_in_red, 0
  br i1 %cmp140.not, label %for.cond.cleanup, label %for.cond1.preheader.lr.ph

for.cond1.preheader.lr.ph:                        ; preds = %entry
  %factor.op.mul139 = mul i32 %inner_red, %n_in_red
  %factor.op.mul136 = mul i32 %factor.op.mul139, %n_contig_el
  %cmp2137.not = icmp eq i32 %n_contig_el, 0
  %factor.op.mul124 = mul i32 %inner_red, %n_contig_el
  %cmp10125.not = icmp eq i32 %outer_red, 0
  %cmp15119.not = icmp eq i32 %inner_red, 0
  %mul = mul i32 %outer_red, %inner_red
  %conv43 = uitofp i32 %mul to float
  br label %for.cond1.preheader

for.cond1.preheader:                              ; preds = %for.cond1.preheader.lr.ph, %for.cond.cleanup3
  %n.0141 = phi i32 [ 0, %for.cond1.preheader.lr.ph ], [ %add62, %for.cond.cleanup3 ]
  br i1 %cmp2137.not, label %for.cond.cleanup3, label %for.body4.lr.ph

for.body4.lr.ph:                                  ; preds = %for.cond1.preheader
  %add = add i32 %n.0141, %3
  %cmp5 = icmp ult i32 %add, %n_in_red
  %factor.op.mul118 = mul i32 %factor.op.mul124, %add
  %invariant.gep132 = getelementptr float, ptr %inp, i32 %factor.op.mul118
  %4 = mul nsw i32 %add, %n_contig_el
  %arrayidx46 = getelementptr inbounds float, ptr %mean_out, i32 %4
  %arrayidx55 = getelementptr inbounds float, ptr %variance_out, i32 %4
  br label %for.body4

for.cond.cleanup:                                 ; preds = %for.cond.cleanup3, %entry
  ret void

for.cond.cleanup3:                                ; preds = %for.inc58, %for.cond1.preheader
  %add62 = add i32 %n.0141, %1
  %cmp = icmp ult i32 %add62, %n_in_red
  br i1 %cmp, label %for.cond1.preheader, label %for.cond.cleanup

for.body4:                                        ; preds = %for.body4.lr.ph, %for.inc58
  %j.0138 = phi i32 [ 0, %for.body4.lr.ph ], [ %add59, %for.inc58 ]
  %add6 = add i32 %j.0138, %2
  %cmp7 = icmp ult i32 %add6, %n_contig_el
  %and116 = and i1 %cmp5, %cmp7
  br i1 %and116, label %for.cond9.preheader, label %for.inc58

for.cond9.preheader:                              ; preds = %for.body4
  br i1 %cmp10125.not, label %for.cond.cleanup12, label %for.cond14.preheader.lr.ph

for.cond14.preheader.lr.ph:                       ; preds = %for.cond9.preheader
  %invariant.gep134 = getelementptr float, ptr %invariant.gep132, i32 %add6
  br label %for.cond14.preheader

for.cond14.preheader:                             ; preds = %for.cond14.preheader.lr.ph, %for.cond.cleanup17
  %i.0128 = phi i32 [ 0, %for.cond14.preheader.lr.ph ], [ %inc41, %for.cond.cleanup17 ]
  %sum2.0127 = phi float [ 0.000000e+00, %for.cond14.preheader.lr.ph ], [ %sum2.1.lcssa, %for.cond.cleanup17 ]
  %sum.0126 = phi float [ 0.000000e+00, %for.cond14.preheader.lr.ph ], [ %sum.1.lcssa, %for.cond.cleanup17 ]
  br i1 %cmp15119.not, label %for.cond.cleanup17, label %for.body18.lr.ph

for.body18.lr.ph:                                 ; preds = %for.cond14.preheader
  %factor.op.mul117 = mul i32 %factor.op.mul136, %i.0128
  %gep135 = getelementptr float, ptr %invariant.gep134, i32 %factor.op.mul117
  br label %for.body18

for.cond.cleanup12:                               ; preds = %for.cond.cleanup17, %for.cond9.preheader
  %sum.0.lcssa = phi float [ 0.000000e+00, %for.cond9.preheader ], [ %sum.1.lcssa, %for.cond.cleanup17 ]
  %sum2.0.lcssa = phi float [ 0.000000e+00, %for.cond9.preheader ], [ %sum2.1.lcssa, %for.cond.cleanup17 ]
  %div = fdiv float %sum.0.lcssa, %conv43
  %arrayidx48 = getelementptr inbounds float, ptr %arrayidx46, i32 %add6
  store float %div, ptr %arrayidx48, align 4
  %div51 = fdiv float %sum2.0.lcssa, %conv43
  %neg = fneg float %div
  %5 = tail call float @llvm.fmuladd.f32(float %neg, float %div, float %div51)
  %arrayidx57 = getelementptr inbounds float, ptr %arrayidx55, i32 %add6
  store float %5, ptr %arrayidx57, align 4
  br label %for.inc58

for.cond.cleanup17:                               ; preds = %for.body18, %for.cond14.preheader
  %sum.1.lcssa = phi float [ %sum.0126, %for.cond14.preheader ], [ %add25, %for.body18 ]
  %sum2.1.lcssa = phi float [ %sum2.0127, %for.cond14.preheader ], [ %8, %for.body18 ]
  %inc41 = add nuw i32 %i.0128, 1
  %exitcond142.not = icmp eq i32 %inc41, %outer_red
  br i1 %exitcond142.not, label %for.cond.cleanup12, label %for.cond14.preheader

for.body18:                                       ; preds = %for.body18.lr.ph, %for.body18
  %b.0122 = phi i32 [ 0, %for.body18.lr.ph ], [ %inc, %for.body18 ]
  %sum2.1121 = phi float [ %sum2.0127, %for.body18.lr.ph ], [ %8, %for.body18 ]
  %sum.1120 = phi float [ %sum.0126, %for.body18.lr.ph ], [ %add25, %for.body18 ]
  %6 = mul nsw i32 %b.0122, %n_contig_el
  %gep = getelementptr float, ptr %gep135, i32 %6
  %7 = load float, ptr %gep, align 4
  %add25 = fadd float %sum.1120, %7
  %8 = tail call float @llvm.fmuladd.f32(float %7, float %7, float %sum2.1121)
  %inc = add nuw i32 %b.0122, 1
  %exitcond.not = icmp eq i32 %inc, %inner_red
  br i1 %exitcond.not, label %for.cond.cleanup17, label %for.body18

for.inc58:                                        ; preds = %for.body4, %for.cond.cleanup12
  %add59 = add i32 %j.0138, %0
  %cmp2 = icmp ult i32 %add59, %n_contig_el
  br i1 %cmp2, label %for.body4, label %for.cond.cleanup3
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare float @llvm.fmuladd.f32(float, float, float)
