; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='module(ripple)' -ripple-run-only-sese -S < %s | FileCheck %s --implicit-check-not="warning:"
target datalayout = "e-m:e-p:32:32:32-a:0-n16:32-i64:64:64-i32:32:32-i16:16:16-i1:8:8-f32:32:32-f64:64:64-v32:32:32-v64:64:64-v512:512:512-v1024:1024:1024-v2048:2048:2048"

; Function Attrs: nounwind
define dso_local void @check(ptr noundef readonly captures(none) %Arr) local_unnamed_addr {
; CHECK-LABEL: define dso_local void @check(
; CHECK-SAME: ptr noundef readonly captures(none) [[ARR:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = tail call ptr @llvm.ripple.block.setshape.i32(i32 0, i32 32, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.ripple.block.index.i32(ptr [[TMP0]], i32 0)
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[TMP1]], 7
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[ARR]], i32 [[TMP1]]
; CHECK-NEXT:    [[TMP2:%.*]] = load float, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp ogt float [[TMP2]], 0.000000e+00
; CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[CMP]], i1 true, i1 [[CMP1]]
; CHECK-NEXT:    br i1 [[OR_COND]], label %[[DO_BODY5:.*]], label %[[IF_THEN2:.*]]
; CHECK:       [[IF_THEN2]]:
; CHECK-NEXT:    br label %[[ABORT_NORETURN:.*]]
; CHECK:       [[DO_BODY5]]:
; CHECK-NEXT:    [[CMP7:%.*]] = fcmp olt float [[TMP2]], 4.200000e+01
; CHECK-NEXT:    br i1 [[CMP7]], label %[[DO_END12:.*]], label %[[ABORT_NORETURN_CLONED:.*]]
; CHECK:       [[ABORT_NORETURN]]:
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i32 28
; CHECK-NEXT:    [[ARG0:%.*]] = load float, ptr [[ARRAYIDX3]], align 4
; CHECK-NEXT:    tail call void @abort(float noundef [[ARG0]]) #[[ATTR2:[0-9]+]]
; CHECK-NEXT:    br label %[[DO_BODY5]]
; CHECK:       [[DO_END12]]:
; CHECK-NEXT:    ret void
; CHECK:       [[ABORT_NORETURN_CLONED]]:
; CHECK-NEXT:    [[ARG0_CLONED:%.*]] = load float, ptr [[ARR]], align 4
; CHECK-NEXT:    tail call void @abort(float noundef [[ARG0_CLONED]]) #[[ATTR2]]
; CHECK-NEXT:    br label %[[DO_END12]]
;
entry:
  %0 = tail call ptr @llvm.ripple.block.setshape.i32(i32 0, i32 32, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1)
  %1 = tail call i32 @llvm.ripple.block.index.i32(ptr %0, i32 0)
  %cmp = icmp ult i32 %1, 7
  %arrayidx = getelementptr inbounds nuw float, ptr %Arr, i32 %1
  %2 = load float, ptr %arrayidx, align 4
  %cmp1 = fcmp ogt float %2, 0.000000e+00
  %or.cond = select i1 %cmp, i1 true, i1 %cmp1
  br i1 %or.cond, label %do.body5, label %if.then2

if.then2:                                         ; preds = %entry
  %arrayidx3 = getelementptr inbounds nuw i8, ptr %Arr, i32 28
  br label %abort.noreturn

do.body5:                                         ; preds = %entry
  %cmp7 = fcmp olt float %2, 4.200000e+01
  br i1 %cmp7, label %do.end12, label %abort.noreturn

abort.noreturn:                                   ; preds = %do.body5, %if.then2
  %arg0.in = phi ptr [ %arrayidx3, %if.then2 ], [ %Arr, %do.body5 ]
  %arg0 = load float, ptr %arg0.in, align 4
  tail call void @abort(float noundef %arg0) #3
  unreachable

do.end12:                                         ; preds = %do.body5
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare ptr @llvm.ripple.block.setshape.i32(i32 immarg, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare i32 @llvm.ripple.block.index.i32(ptr, i32 immarg) #1

; Function Attrs: noreturn
declare dso_local void @abort(float noundef) local_unnamed_addr #2

attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(none) }
attributes #2 = { noreturn }
attributes #3 = { nobuiltin noreturn nounwind "no-builtins" }
