; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='module(ripple)' -ripple-run-only-sese -S < %s | FileCheck %s --implicit-check-not="warning:"
target datalayout = "e-m:e-p:32:32:32-a:0-n16:32-i64:64:64-i32:32:32-i16:16:16-i1:8:8-f32:32:32-f64:64:64-v32:32:32-v64:64:64-v512:512:512-v1024:1024:1024-v2048:2048:2048"

define dso_local void @check(ptr noundef captures(none) %Arr) local_unnamed_addr {
; CHECK-LABEL: define dso_local void @check(
; CHECK-SAME: ptr noundef captures(none) [[ARR:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = tail call ptr @llvm.ripple.block.setshape.i32(i32 0, i32 32, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.ripple.block.index.i32(ptr [[TMP0]], i32 0)
; CHECK-NEXT:    [[CMP:%.*]] = icmp ugt i32 [[TMP1]], 6
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_THEN2:.*]], label %[[IF_END4:.*]]
; CHECK:       [[IF_THEN2]]:
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i32 28
; CHECK-NEXT:    br label %[[ABORT_NORETURN:.*]]
; CHECK:       [[IF_END4]]:
; CHECK-NEXT:    br label %[[ABORT_NORETURN]]
; CHECK:       [[ABORT_NORETURN]]:
; CHECK-NEXT:    [[ARG0_IN:%.*]] = phi ptr [ [[ARRAYIDX3]], %[[IF_THEN2]] ], [ [[ARR]], %[[IF_END4]] ]
; CHECK-NEXT:    [[ARG0:%.*]] = load float, ptr [[ARG0_IN]], align 4
; CHECK-NEXT:    tail call void @abort(float noundef [[ARG0]]) #[[ATTR1:[0-9]+]]
; CHECK-NEXT:    unreachable
;
entry:
  %0 = tail call ptr @llvm.ripple.block.setshape.i32(i32 0, i32 32, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1)
  %1 = tail call i32 @llvm.ripple.block.index.i32(ptr %0, i32 0)
  %cmp = icmp ugt i32 %1, 6
  br i1 %cmp, label %if.then2, label %if.end4

if.then2:                                         ; preds = %do.body
  %arrayidx3 = getelementptr inbounds nuw i8, ptr %Arr, i32 28
  br label %abort.noreturn

if.end4:                                          ; preds = %entry
  br label %abort.noreturn

abort.noreturn:                                   ; preds = %if.end4, %if.then2
  %arg0.in = phi ptr [ %arrayidx3, %if.then2 ], [ %Arr, %if.end4 ]
  %arg0 = load float, ptr %arg0.in, align 4
  tail call void @abort(float noundef %arg0) #1
  unreachable
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare ptr @llvm.ripple.block.setshape.i32(i32 immarg, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare i32 @llvm.ripple.block.index.i32(ptr, i32 immarg) #0

declare dso_local void @abort(float noundef) local_unnamed_addr

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(none) }
attributes #1 = { nobuiltin noreturn nounwind "no-builtins" }
