; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='module(ripple)' -ripple-run-only-sese -S < %s | FileCheck %s --implicit-check-not="warning:"
target datalayout = "e-m:e-p:32:32:32-a:0-n16:32-i64:64:64-i32:32:32-i16:16:16-i1:8:8-f32:32:32-f64:64:64-v32:32:32-v64:64:64-v512:512:512-v1024:1024:1024-v2048:2048:2048"

define dso_local void @check(ptr noundef captures(none) %Arr) local_unnamed_addr {
; CHECK-LABEL: define dso_local void @check(
; CHECK-SAME: ptr noundef captures(none) [[ARR:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = tail call ptr @llvm.ripple.block.setshape.i32(i32 0, i32 32, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.ripple.block.index.i32(ptr [[TMP0]], i32 0)
; CHECK-NEXT:    [[CMP:%.*]] = icmp ugt i32 [[TMP1]], 6
; CHECK-NEXT:    br i1 [[CMP]], label %[[DO_BODY:.*]], label %[[IF_END4:.*]]
; CHECK:       [[DO_BODY]]:
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[ARR]], i32 [[TMP1]]
; CHECK-NEXT:    [[TMP2:%.*]] = load float, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp ogt float [[TMP2]], 0.000000e+00
; CHECK-NEXT:    br i1 [[CMP1]], label %[[IF_END15:.*]], label %[[IF_THEN2:.*]]
; CHECK:       [[IF_THEN2]]:
; CHECK-NEXT:    br label %[[ABORT_NORETURN_CLONED:.*]]
; CHECK:       [[IF_END4]]:
; CHECK-NEXT:    [[CMP5:%.*]] = icmp ugt i32 [[TMP1]], 4
; CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[ARR]], i32 [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = load float, ptr [[ARRAYIDX8]], align 4
; CHECK-NEXT:    [[CMP9:%.*]] = fcmp olt float [[TMP3]], 4.200000e+01
; CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[CMP5]], i1 true, i1 [[CMP9]]
; CHECK-NEXT:    br i1 [[OR_COND]], label %[[IF_END15]], label %[[ABORT_NORETURN:.*]]
; CHECK:       [[ABORT_NORETURN]]:
; CHECK-NEXT:    [[ARG0:%.*]] = load float, ptr [[ARR]], align 4
; CHECK-NEXT:    tail call void @abort(float noundef [[ARG0]]) #[[ATTR1:[0-9]+]]
; CHECK-NEXT:    br label %[[IF_END15]]
; CHECK:       [[IF_END15]]:
; CHECK-NEXT:    [[TMP4:%.*]] = phi float [ [[TMP3]], %[[IF_END4]] ], [ [[TMP2]], %[[DO_BODY]] ], [ undef, %[[ABORT_NORETURN_CLONED]] ], [ undef, %[[ABORT_NORETURN]] ]
; CHECK-NEXT:    [[ARRAYIDX16:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[ARR]], i32 [[TMP1]]
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[TMP4]], [[TMP4]]
; CHECK-NEXT:    store float [[MUL]], ptr [[ARRAYIDX16]], align 4
; CHECK-NEXT:    ret void
; CHECK:       [[ABORT_NORETURN_CLONED]]:
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i32 28
; CHECK-NEXT:    [[ARG0_CLONED:%.*]] = load float, ptr [[ARRAYIDX3]], align 4
; CHECK-NEXT:    tail call void @abort(float noundef [[ARG0_CLONED]]) #[[ATTR1]]
; CHECK-NEXT:    br label %[[IF_END15]]
;
entry:
  %0 = tail call ptr @llvm.ripple.block.setshape.i32(i32 0, i32 32, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1)
  %1 = tail call i32 @llvm.ripple.block.index.i32(ptr %0, i32 0)
  %cmp = icmp ugt i32 %1, 6
  br i1 %cmp, label %do.body, label %if.end4

do.body:                                          ; preds = %entry
  %arrayidx = getelementptr inbounds nuw float, ptr %Arr, i32 %1
  %2 = load float, ptr %arrayidx, align 4
  %cmp1 = fcmp ogt float %2, 0.000000e+00
  br i1 %cmp1, label %if.end15, label %if.then2

if.then2:                                         ; preds = %do.body
  %arrayidx3 = getelementptr inbounds nuw i8, ptr %Arr, i32 28
  br label %abort.noreturn

if.end4:                                          ; preds = %entry
  %cmp5 = icmp ugt i32 %1, 4
  %arrayidx8 = getelementptr inbounds nuw float, ptr %Arr, i32 %1
  %3 = load float, ptr %arrayidx8, align 4
  %cmp9 = fcmp olt float %3, 4.200000e+01
  %or.cond = select i1 %cmp5, i1 true, i1 %cmp9
  br i1 %or.cond, label %if.end15, label %abort.noreturn

abort.noreturn:                                   ; preds = %if.end4, %if.then2
  %arg0.in = phi ptr [ %arrayidx3, %if.then2 ], [ %Arr, %if.end4 ]
  %arg0 = load float, ptr %arg0.in, align 4
  tail call void @abort(float noundef %arg0) #3
  unreachable

if.end15:                                         ; preds = %if.end4, %do.body
  %4 = phi float [ %3, %if.end4 ], [ %2, %do.body ]
  %arrayidx16 = getelementptr inbounds nuw float, ptr %Arr, i32 %1
  %mul = fmul float %4, %4
  store float %mul, ptr %arrayidx16, align 4
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare ptr @llvm.ripple.block.setshape.i32(i32 immarg, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare i32 @llvm.ripple.block.index.i32(ptr, i32 immarg) #1

; Function Attrs: noreturn
declare dso_local void @abort(float noundef) local_unnamed_addr

attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(none) }
attributes #2 = { noreturn }
attributes #3 = { nobuiltin noreturn nounwind "no-builtins" }
