; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mtriple=amdgcn -S -passes=simplifycfg < %s | FileCheck %s

declare void @bar1()
declare void @bar2()
declare void @bar3()

define i32 @test_01a(i32 %a) {
; CHECK-LABEL: define i32 @test_01a(
; CHECK-SAME: i32 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i32 [[A]], 0
; CHECK-NEXT:    br i1 [[COND]], label %[[MERGE:.*]], label %[[IF_FALSE:.*]]
; CHECK:       [[IF_FALSE]]:
; CHECK-NEXT:    call void @bar1()
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    call void @bar2()
; CHECK-NEXT:    br i1 [[COND]], label %[[EXIT:.*]], label %[[IF_FALSE_2:.*]]
; CHECK:       [[IF_FALSE_2]]:
; CHECK-NEXT:    call void @bar3()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 [[A]]
;
entry:
  %cond = icmp eq i32 %a, 0
  br i1 %cond, label %merge, label %if.false

if.false:
  call void @bar1()
  br label %merge

merge:
  call void @bar2()
  br i1 %cond, label %exit, label %if.false.2

if.false.2:
  call void @bar3()
  br label %exit

exit:
  ret i32 %a
}
