; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=sparc-- -passes='require<libcall-lowering-info>,safe-stack' %s | FileCheck %s

define void @foo(i32 %t) #0 {
; CHECK-LABEL: define void @foo(
; CHECK-SAME: i32 [[T:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[UNSAFE_STACK_PTR:%.*]] = load ptr, ptr @__safestack_unsafe_stack_ptr, align 4
; CHECK-NEXT:    [[TMP2:%.*]] = call ptr @llvm.stackguard()
; CHECK-NEXT:    [[TMP3:%.*]] = alloca ptr, align 4
; CHECK-NEXT:    store ptr [[TMP2]], ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = mul i32 [[T]], 4
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr @__safestack_unsafe_stack_ptr, align 4
; CHECK-NEXT:    [[TMP6:%.*]] = sub i32 0, [[TMP4]]
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[TMP5]], i32 [[TMP6]]
; CHECK-NEXT:    [[VLA:%.*]] = call ptr @llvm.ptrmask.p0.i32(ptr [[TMP7]], i32 -16)
; CHECK-NEXT:    store ptr [[VLA]], ptr @__safestack_unsafe_stack_ptr, align 4
; CHECK-NEXT:    call void @baz(ptr [[VLA]])
; CHECK-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = icmp ne ptr [[TMP2]], [[TMP8]]
; CHECK-NEXT:    br i1 [[TMP9]], label %[[BB10:.*]], label %[[BB11:.*]], !prof [[PROF0:![0-9]+]]
; CHECK:       [[BB10]]:
; CHECK-NEXT:    call void @__stack_chk_fail()
; CHECK-NEXT:    unreachable
; CHECK:       [[BB11]]:
; CHECK-NEXT:    store ptr [[UNSAFE_STACK_PTR]], ptr @__safestack_unsafe_stack_ptr, align 4
; CHECK-NEXT:    ret void
;
  %vla = alloca i32, i32 %t, align 4
  call void @baz(ptr %vla)
  ret void
}

declare void @baz(ptr)

attributes #0 = { nounwind safestack sspstrong }
;.
; CHECK: [[PROF0]] = !{!"branch_weights", i32 2147481600, i32 2048}
;.
