; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-unknown-linux < %s | FileCheck %s

declare i32 @llvm.umin.i32(i32, i32)

define i32 @f(i1 %c0, i1 %c1, i32 %x) {
; CHECK-LABEL: f:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-NEXT:    and x8, x1, #0x1
; CHECK-NEXT:    mov w9, #1 // =0x1
; CHECK-NEXT:    tst w0, #0x1
; CHECK-NEXT:    mov w10, #4 // =0x4
; CHECK-NEXT:    lsl w8, w9, w8
; CHECK-NEXT:    csel w9, w10, wzr, ne
; CHECK-NEXT:    cmp w9, w8
; CHECK-NEXT:    csel w8, w9, w8, lo
; CHECK-NEXT:    bic w0, w8, w2
; CHECK-NEXT:    ret
entry:
  %a = select i1 %c0, i32 4, i32 0
  %e = zext i1 %c1 to i32
  %b = shl i32 1, %e
  %y = call i32 @llvm.umin.i32(i32 %a, i32 %b)
  %sum = add i32 %x, %y
  %r = and i32 %y, %sum
  ret i32 %r
}

declare <4 x i32> @llvm.umin.v4i32(<4 x i32>, <4 x i32>)

define <4 x i32> @vec_alllanes(<4 x i1> %cond, <4 x i32> %x) {
; CHECK-LABEL: vec_alllanes:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-NEXT:    movi v2.4s, #4
; CHECK-NEXT:    shl v0.4s, v0.4s, #31
; CHECK-NEXT:    cmlt v0.4s, v0.4s, #0
; CHECK-NEXT:    bic v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    and v0.16b, v0.16b, v2.16b
; CHECK-NEXT:    ret
entry:
  ; Vector select: each lane is either 4 or 0 (pow2-or-zero)
  %a = select <4 x i1> %cond, <4 x i32> <i32 4, i32 4, i32 4, i32 4>, <4 x i32> zeroinitializer
  ; Constant vector of pow2 values
  %b = add <4 x i32> <i32 8, i32 8, i32 8, i32 8>, zeroinitializer
  %y = call <4 x i32> @llvm.umin.v4i32(<4 x i32> %a, <4 x i32> %b)
  %sum = add <4 x i32> %x, %y
  %r = and <4 x i32> %y, %sum
  ret <4 x i32> %r
}

