; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=aarch64 %s -o - | FileCheck %s

define <2 x i64> @fhsl_to_rev2i64(<2 x i64> %r) {
; CHECK-LABEL: fhsl_to_rev2i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    rev64 v0.4s, v0.4s
; CHECK-NEXT:    ret
    %or = tail call <2 x i64> @llvm.fshl.v2i64(<2 x i64> %r, <2 x i64> %r, <2 x i64> splat (i64 32))
    ret <2 x i64> %or
}

define <4 x i32> @fshl_to_rev4i32(<4 x i32> %r) {
; CHECK-LABEL: fshl_to_rev4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    rev32 v0.8h, v0.8h
; CHECK-NEXT:    ret
    %or = tail call <4 x i32> @llvm.fshl.v4i32(<4 x i32> %r, <4 x i32> %r, <4 x i32> splat (i32 16))
    ret <4 x i32> %or
}

define <2 x i32> @fshl_to_rev2i32(<2 x i32> %r) {
; CHECK-LABEL: fshl_to_rev2i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    rev32 v0.4h, v0.4h
; CHECK-NEXT:    ret
    %or = tail call <2 x i32> @llvm.fshl.v2i32(<2 x i32> %r, <2 x i32> %r, <2 x i32> splat (i32 16))
    ret <2 x i32> %or
}
