; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=aarch64-linux-gnu -mattr=+sve | FileCheck %s

;; This file tests basic use of `target("aarch64.svcount")` works with only +sve.

declare void @svcount_fn_arg(target("aarch64.svcount"))

define void @svcount_fn_call() {
; CHECK-LABEL: svcount_fn_call:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset w30, -16
; CHECK-NEXT:    pfalse p0.b
; CHECK-NEXT:    bl svcount_fn_arg
; CHECK-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
entry:
  call void @svcount_fn_arg(target("aarch64.svcount") zeroinitializer)
  ret void
}

define target("aarch64.svcount") @select_svcount(i1 %cond, target("aarch64.svcount") %pn0, target("aarch64.svcount") %pn1) {
; CHECK-LABEL: select_svcount:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $w0 killed $w0 def $x0
; CHECK-NEXT:    sbfx x8, x0, #0, #1
; CHECK-NEXT:    whilelo p2.b, xzr, x8
; CHECK-NEXT:    sel p0.b, p2, p0.b, p1.b
; CHECK-NEXT:    ret
  %sel = select i1 %cond, target("aarch64.svcount") %pn0, target("aarch64.svcount") %pn1
  ret target("aarch64.svcount") %sel
}

define void @store_svcount(ptr %ptr, target("aarch64.svcount") %pn) {
; CHECK-LABEL: store_svcount:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str p0, [x0]
; CHECK-NEXT:    ret
  store target("aarch64.svcount") %pn, ptr %ptr, align 2
  ret void
}

define target("aarch64.svcount")  @load_svcount(ptr %ptr) {
; CHECK-LABEL: load_svcount:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldr p0, [x0]
; CHECK-NEXT:    ret
  %pn = load target("aarch64.svcount"), ptr %ptr, align 2
  ret target("aarch64.svcount") %pn
}
