# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -run-pass=machine-combiner -mtriple=aarch64-macos-darwin %s -o - | FileCheck %s

---
name:            split_loads_to_fpr128
body:             |
  bb.0.entry:
    liveins: $x0, $x1, $x2, $x3, $x4

    ; CHECK-LABEL: name: split_loads_to_fpr128
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr64common = COPY $x0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr64common = COPY $x2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gpr64common = COPY $x3
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gpr64common = COPY $x4
    ; CHECK-NEXT: [[LDRSroX:%[0-9]+]]:fpr32 = LDRSroX [[COPY]], killed [[COPY1]], 0, 1
    ; CHECK-NEXT: [[SUBREG_TO_REG:%[0-9]+]]:fpr128 = SUBREG_TO_REG 0, killed [[LDRSroX]], %subreg.ssub
    ; CHECK-NEXT: [[LD1i32_:%[0-9]+]]:fpr128 = LD1i32 [[SUBREG_TO_REG]], 1, killed [[COPY2]]
    ; CHECK-NEXT: [[LD1i32_1:%[0-9]+]]:fpr128 = LD1i32 [[LD1i32_]], 2, killed [[COPY3]]
    ; CHECK-NEXT: [[LD1i32_2:%[0-9]+]]:fpr128 = LD1i32 [[LD1i32_1]], 3, killed [[COPY4]]
    ; CHECK-NEXT: $q0 = COPY [[LD1i32_2]]
    ; CHECK-NEXT: RET_ReallyLR implicit $q0
    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %2:gpr64common = COPY $x2
    %3:gpr64common = COPY $x3
    %4:gpr64common = COPY $x4
    %5:fpr32 = LDRSroX %0, killed %1, 0, 1
    %6:fpr128 = SUBREG_TO_REG 0, killed %5, %subreg.ssub
    %7:fpr128 = LD1i32 %6, 1, killed %2
    %8:fpr128 = LD1i32 %7, 2, killed %3
    %9:fpr128 = LD1i32 %8, 3, killed %4
    $q0 = COPY %9
    RET_ReallyLR implicit $q0
