; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -o - | FileCheck %s

target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-n32:64"
target triple = "arm64-apple-macosx10.9"

; Check that sexts get promoted above adds.
define void @foo(ptr nocapture %a, i32 %i) {
; CHECK-LABEL: foo:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    ; kill: def $w1 killed $w1 def $x1
; CHECK-NEXT:    sxtw x8, w1
; CHECK-NEXT:    add x9, x8, #1
; CHECK-NEXT:    add x8, x8, #2
; CHECK-NEXT:    ldr w9, [x0, x9, lsl #2]
; CHECK-NEXT:    ldr w8, [x0, x8, lsl #2]
; CHECK-NEXT:    add w8, w8, w9
; CHECK-NEXT:    str w8, [x0, w1, sxtw #2]
; CHECK-NEXT:    ret
entry:
  %add = add nsw i32 %i, 1
  %idxprom = sext i32 %add to i64
  %arrayidx = getelementptr inbounds i32, ptr %a, i64 %idxprom
  %0 = load i32, ptr %arrayidx, align 4
  %add1 = add nsw i32 %i, 2
  %idxprom2 = sext i32 %add1 to i64
  %arrayidx3 = getelementptr inbounds i32, ptr %a, i64 %idxprom2
  %1 = load i32, ptr %arrayidx3, align 4
  %add4 = add nsw i32 %1, %0
  %idxprom5 = sext i32 %i to i64
  %arrayidx6 = getelementptr inbounds i32, ptr %a, i64 %idxprom5
  store i32 %add4, ptr %arrayidx6, align 4
  ret void
}
