# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=aarch64-linux-gnu -run-pass=aarch64-condopt -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple=aarch64-linux-gnu -passes=aarch64-condopt %s -o - | FileCheck %s

---
# Non-adjacent dominator pair: bb.1 sits between bb.0 and bb.2 in the CFG, but
# bb.0 dominates bb.2, so the SHT makes bb.0's pair visible when processing bb.2.
#
# Input:  bb.0: CMP #9 GT; bb.2: CMP #11 LT
# Output: bb.0: CMP #10 GE; bb.2: CMP #10 LE
name:            non_adjacent_dominator_pair
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr32sp }
body:             |
  ; CHECK-LABEL: name: non_adjacent_dominator_pair
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $w0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr32sp = COPY $w0
  ; CHECK-NEXT:   dead $wzr = SUBSWri [[COPY]], 10, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 10, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead $wzr = SUBSWri [[COPY]], 10, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 13, %bb.3, implicit $nzcv
  ; CHECK-NEXT:   B %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   $w0 = MOVi32imm 1
  ; CHECK-NEXT:   RET_ReallyLR implicit $w0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   $w0 = MOVi32imm 0
  ; CHECK-NEXT:   RET_ReallyLR implicit $w0
  bb.0:
    liveins: $w0
    successors: %bb.1, %bb.2

    %0:gpr32sp = COPY $w0
    dead $wzr = SUBSWri %0, 9, 0, implicit-def $nzcv
    Bcc 12, %bb.1, implicit $nzcv
    B %bb.2

  bb.1:
    successors: %bb.2
    B %bb.2

  bb.2:
    successors: %bb.3, %bb.4

    dead $wzr = SUBSWri %0, 11, 0, implicit-def $nzcv
    Bcc 11, %bb.3, implicit $nzcv
    B %bb.4

  bb.3:
    $w0 = MOVi32imm 1
    RET_ReallyLR implicit $w0

  bb.4:
    $w0 = MOVi32imm 0
    RET_ReallyLR implicit $w0
...
---
# Cross-block select-pair: bb.0 dominates bb.1, so the SHT makes bb.0's pair
# visible when processing bb.1.
#
# Input:  bb.0: CMP #9 GT CSINC;  bb.1: CMP #11 LT CSINC
# Output: bb.0: CMP #10 GE CSINC; bb.1: CMP #10 LE CSINC
name:            cross_block_select_pair
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr32sp }
  - { id: 1, class: gpr32 }
  - { id: 2, class: gpr32 }
  - { id: 3, class: gpr32 }
body:             |
  ; CHECK-LABEL: name: cross_block_select_pair
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $w0, $w1, $w2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr32sp = COPY $w0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr32 = COPY $w1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr32 = COPY $w2
  ; CHECK-NEXT:   dead $wzr = SUBSWri [[COPY]], 10, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[CSINCWr:%[0-9]+]]:gpr32 = CSINCWr [[COPY1]], [[COPY2]], 10, implicit $nzcv
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   dead $wzr = SUBSWri [[COPY]], 10, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[CSINCWr1:%[0-9]+]]:gpr32 = CSINCWr [[CSINCWr]], [[COPY2]], 13, implicit $nzcv
  ; CHECK-NEXT:   $w0 = COPY [[CSINCWr1]]
  ; CHECK-NEXT:   RET_ReallyLR implicit $w0
  bb.0:
    liveins: $w0, $w1, $w2
    successors: %bb.1

    %0:gpr32sp = COPY $w0
    %1:gpr32 = COPY $w1
    %2:gpr32 = COPY $w2
    dead $wzr = SUBSWri %0, 9, 0, implicit-def $nzcv
    %3:gpr32 = CSINCWr %1, %2, 12, implicit $nzcv

  bb.1:
    dead $wzr = SUBSWri %0, 11, 0, implicit-def $nzcv
    %4:gpr32 = CSINCWr %3, %2, 11, implicit $nzcv
    $w0 = COPY %4
    RET_ReallyLR implicit $w0
...
