; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple aarch64-none-linux-gnu -mattr=+sve | FileCheck %s


define <8 x double> @uitofp_fadd_02(ptr %p) {
; CHECK-LABEL: uitofp_fadd_02:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldp q3, q2, [x0]
; CHECK-NEXT:    ldp q1, q0, [x0, #32]
; CHECK-NEXT:    ushr v5.2d, v3.2d, #16
; CHECK-NEXT:    ushr v6.2d, v2.2d, #16
; CHECK-NEXT:    ushr v20.2d, v3.2d, #32
; CHECK-NEXT:    ushr v7.2d, v1.2d, #16
; CHECK-NEXT:    ushr v19.2d, v0.2d, #16
; CHECK-NEXT:    ushr v21.2d, v2.2d, #32
; CHECK-NEXT:    ushr v22.2d, v1.2d, #32
; CHECK-NEXT:    ushr v23.2d, v0.2d, #32
; CHECK-NEXT:    movprfx z4, z3
; CHECK-NEXT:    and z4.d, z4.d, #0xffff
; CHECK-NEXT:    movprfx z16, z2
; CHECK-NEXT:    and z16.d, z16.d, #0xffff
; CHECK-NEXT:    movprfx z17, z1
; CHECK-NEXT:    and z17.d, z17.d, #0xffff
; CHECK-NEXT:    movprfx z18, z0
; CHECK-NEXT:    and z18.d, z18.d, #0xffff
; CHECK-NEXT:    and z5.d, z5.d, #0xffff
; CHECK-NEXT:    and z6.d, z6.d, #0xffff
; CHECK-NEXT:    and z7.d, z7.d, #0xffff
; CHECK-NEXT:    and z19.d, z19.d, #0xffff
; CHECK-NEXT:    and z20.d, z20.d, #0xffff
; CHECK-NEXT:    and z21.d, z21.d, #0xffff
; CHECK-NEXT:    and z22.d, z22.d, #0xffff
; CHECK-NEXT:    and z23.d, z23.d, #0xffff
; CHECK-NEXT:    ushr v3.2d, v3.2d, #48
; CHECK-NEXT:    ushr v2.2d, v2.2d, #48
; CHECK-NEXT:    ushr v1.2d, v1.2d, #48
; CHECK-NEXT:    ushr v0.2d, v0.2d, #48
; CHECK-NEXT:    ucvtf v4.2d, v4.2d
; CHECK-NEXT:    ucvtf v16.2d, v16.2d
; CHECK-NEXT:    ucvtf v17.2d, v17.2d
; CHECK-NEXT:    ucvtf v18.2d, v18.2d
; CHECK-NEXT:    ucvtf v5.2d, v5.2d
; CHECK-NEXT:    ucvtf v6.2d, v6.2d
; CHECK-NEXT:    ucvtf v7.2d, v7.2d
; CHECK-NEXT:    ucvtf v19.2d, v19.2d
; CHECK-NEXT:    ucvtf v20.2d, v20.2d
; CHECK-NEXT:    ucvtf v21.2d, v21.2d
; CHECK-NEXT:    ucvtf v22.2d, v22.2d
; CHECK-NEXT:    ucvtf v23.2d, v23.2d
; CHECK-NEXT:    ucvtf v3.2d, v3.2d
; CHECK-NEXT:    ucvtf v2.2d, v2.2d
; CHECK-NEXT:    ucvtf v1.2d, v1.2d
; CHECK-NEXT:    ucvtf v0.2d, v0.2d
; CHECK-NEXT:    fadd v6.2d, v16.2d, v6.2d
; CHECK-NEXT:    fadd v4.2d, v4.2d, v5.2d
; CHECK-NEXT:    fadd v18.2d, v18.2d, v19.2d
; CHECK-NEXT:    fadd v7.2d, v17.2d, v7.2d
; CHECK-NEXT:    fadd v3.2d, v20.2d, v3.2d
; CHECK-NEXT:    fadd v16.2d, v22.2d, v1.2d
; CHECK-NEXT:    fadd v1.2d, v21.2d, v2.2d
; CHECK-NEXT:    fadd v5.2d, v23.2d, v0.2d
; CHECK-NEXT:    fadd v0.2d, v4.2d, v3.2d
; CHECK-NEXT:    fadd v1.2d, v6.2d, v1.2d
; CHECK-NEXT:    fadd v2.2d, v7.2d, v16.2d
; CHECK-NEXT:    fadd v3.2d, v18.2d, v5.2d
; CHECK-NEXT:    ret
    %l = load <32 x i16>, ptr %p
    %deint = call {<8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.vector.deinterleave4(<32 x i16> %l)
    %s1 = extractvalue {<8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %deint, 0
    %s2 = extractvalue {<8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %deint, 1
    %s3 = extractvalue {<8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %deint, 2
    %s4 = extractvalue {<8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %deint, 3
    %z1 = uitofp <8 x i16> %s1 to <8 x double>
    %z2 = uitofp <8 x i16> %s2 to <8 x double>
    %z3 = uitofp <8 x i16> %s3 to <8 x double>
    %z4 = uitofp <8 x i16> %s4 to <8 x double>
    %a = fadd <8 x double> %z1, %z2
    %b = fadd <8 x double> %z3, %z4
    %c = fadd <8 x double> %a, %b
    ret <8 x double> %c
}

define <8 x double> @uitofp_load_fadd(ptr %p) {
; CHECK-LABEL: uitofp_load_fadd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldp q3, q2, [x0]
; CHECK-NEXT:    ldp q1, q0, [x0, #32]
; CHECK-NEXT:    ushr v5.2d, v3.2d, #16
; CHECK-NEXT:    ushr v6.2d, v2.2d, #16
; CHECK-NEXT:    ushr v20.2d, v3.2d, #32
; CHECK-NEXT:    ushr v7.2d, v1.2d, #16
; CHECK-NEXT:    ushr v19.2d, v0.2d, #16
; CHECK-NEXT:    ushr v21.2d, v2.2d, #32
; CHECK-NEXT:    ushr v22.2d, v1.2d, #32
; CHECK-NEXT:    ushr v23.2d, v0.2d, #32
; CHECK-NEXT:    movprfx z4, z3
; CHECK-NEXT:    and z4.d, z4.d, #0xffff
; CHECK-NEXT:    movprfx z16, z2
; CHECK-NEXT:    and z16.d, z16.d, #0xffff
; CHECK-NEXT:    movprfx z17, z1
; CHECK-NEXT:    and z17.d, z17.d, #0xffff
; CHECK-NEXT:    movprfx z18, z0
; CHECK-NEXT:    and z18.d, z18.d, #0xffff
; CHECK-NEXT:    and z5.d, z5.d, #0xffff
; CHECK-NEXT:    and z6.d, z6.d, #0xffff
; CHECK-NEXT:    and z7.d, z7.d, #0xffff
; CHECK-NEXT:    and z19.d, z19.d, #0xffff
; CHECK-NEXT:    and z20.d, z20.d, #0xffff
; CHECK-NEXT:    and z21.d, z21.d, #0xffff
; CHECK-NEXT:    and z22.d, z22.d, #0xffff
; CHECK-NEXT:    and z23.d, z23.d, #0xffff
; CHECK-NEXT:    ushr v3.2d, v3.2d, #48
; CHECK-NEXT:    ushr v2.2d, v2.2d, #48
; CHECK-NEXT:    ushr v1.2d, v1.2d, #48
; CHECK-NEXT:    ushr v0.2d, v0.2d, #48
; CHECK-NEXT:    ucvtf v4.2d, v4.2d
; CHECK-NEXT:    ucvtf v16.2d, v16.2d
; CHECK-NEXT:    ucvtf v17.2d, v17.2d
; CHECK-NEXT:    ucvtf v18.2d, v18.2d
; CHECK-NEXT:    ucvtf v5.2d, v5.2d
; CHECK-NEXT:    ucvtf v6.2d, v6.2d
; CHECK-NEXT:    ucvtf v7.2d, v7.2d
; CHECK-NEXT:    ucvtf v19.2d, v19.2d
; CHECK-NEXT:    ucvtf v20.2d, v20.2d
; CHECK-NEXT:    ucvtf v21.2d, v21.2d
; CHECK-NEXT:    ucvtf v22.2d, v22.2d
; CHECK-NEXT:    ucvtf v23.2d, v23.2d
; CHECK-NEXT:    ucvtf v3.2d, v3.2d
; CHECK-NEXT:    ucvtf v2.2d, v2.2d
; CHECK-NEXT:    ucvtf v1.2d, v1.2d
; CHECK-NEXT:    ucvtf v0.2d, v0.2d
; CHECK-NEXT:    fadd v6.2d, v16.2d, v6.2d
; CHECK-NEXT:    fadd v4.2d, v4.2d, v5.2d
; CHECK-NEXT:    fadd v18.2d, v18.2d, v19.2d
; CHECK-NEXT:    fadd v7.2d, v17.2d, v7.2d
; CHECK-NEXT:    fadd v3.2d, v20.2d, v3.2d
; CHECK-NEXT:    fadd v16.2d, v22.2d, v1.2d
; CHECK-NEXT:    fadd v1.2d, v21.2d, v2.2d
; CHECK-NEXT:    fadd v5.2d, v23.2d, v0.2d
; CHECK-NEXT:    fadd v0.2d, v4.2d, v3.2d
; CHECK-NEXT:    fadd v1.2d, v6.2d, v1.2d
; CHECK-NEXT:    fadd v2.2d, v7.2d, v16.2d
; CHECK-NEXT:    fadd v3.2d, v18.2d, v5.2d
; CHECK-NEXT:    ret
    %l = load <32 x i16>, ptr %p
    %s1 = shufflevector <32 x i16> %l, <32 x i16> poison, <8 x i32> <i32 0, i32 4, i32 8, i32 12, i32 16, i32 20, i32 24, i32 28>
    %s2 = shufflevector <32 x i16> %l, <32 x i16> poison, <8 x i32> <i32 1, i32 5, i32 9, i32 13, i32 17, i32 21, i32 25, i32 29>
    %s3 = shufflevector <32 x i16> %l, <32 x i16> poison, <8 x i32> <i32 2, i32 6, i32 10, i32 14, i32 18, i32 22, i32 26, i32 30>
    %s4 = shufflevector <32 x i16> %l, <32 x i16> poison, <8 x i32> <i32 3, i32 7, i32 11, i32 15, i32 19, i32 23, i32 27, i32 31>
    %z1 = uitofp <8 x i16> %s1 to <8 x double>
    %z2 = uitofp <8 x i16> %s2 to <8 x double>
    %z3 = uitofp <8 x i16> %s3 to <8 x double>
    %z4 = uitofp <8 x i16> %s4 to <8 x double>
    %a = fadd <8 x double> %z1, %z2
    %b = fadd <8 x double> %z3, %z4
    %c = fadd <8 x double> %a, %b
    ret <8 x double> %c
}
