; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple aarch64-none-linux-gnu -mattr=+sve | FileCheck %s

define void @deinterleave_intrinsic_uitofp(ptr %src, ptr %dst0, ptr %dst1,
; CHECK-LABEL: deinterleave_intrinsic_uitofp:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cbz x5, .LBB0_3
; CHECK-NEXT:  // %bb.1: // %loop.preheader
; CHECK-NEXT:    adrp x8, .LCPI0_0
; CHECK-NEXT:    adrp x9, .LCPI0_1
; CHECK-NEXT:    ldr q0, [x8, :lo12:.LCPI0_0]
; CHECK-NEXT:    ldr q1, [x9, :lo12:.LCPI0_1]
; CHECK-NEXT:    mov x8, xzr
; CHECK-NEXT:  .LBB0_2: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    lsl x9, x8, #5
; CHECK-NEXT:    add x8, x8, #1
; CHECK-NEXT:    cmp x8, x5
; CHECK-NEXT:    add x10, x0, x9
; CHECK-NEXT:    add x11, x2, x9
; CHECK-NEXT:    ldp q2, q3, [x10]
; CHECK-NEXT:    add x10, x1, x9
; CHECK-NEXT:    uzp1 v4.16b, v2.16b, v3.16b
; CHECK-NEXT:    uzp2 v5.16b, v3.16b, v0.16b
; CHECK-NEXT:    uzp2 v6.16b, v2.16b, v0.16b
; CHECK-NEXT:    xtn v3.8b, v3.8h
; CHECK-NEXT:    xtn v2.8b, v2.8h
; CHECK-NEXT:    xtn v4.8b, v4.8h
; CHECK-NEXT:    uzp1 v7.8b, v6.8b, v5.8b
; CHECK-NEXT:    uzp2 v5.8b, v6.8b, v5.8b
; CHECK-NEXT:    uzp2 v2.8b, v2.8b, v3.8b
; CHECK-NEXT:    tbl v3.16b, { v4.16b }, v0.16b
; CHECK-NEXT:    tbl v4.16b, { v4.16b }, v1.16b
; CHECK-NEXT:    tbl v6.16b, { v7.16b }, v0.16b
; CHECK-NEXT:    tbl v7.16b, { v7.16b }, v1.16b
; CHECK-NEXT:    tbl v16.16b, { v2.16b }, v0.16b
; CHECK-NEXT:    tbl v2.16b, { v2.16b }, v1.16b
; CHECK-NEXT:    tbl v17.16b, { v5.16b }, v0.16b
; CHECK-NEXT:    tbl v5.16b, { v5.16b }, v1.16b
; CHECK-NEXT:    ucvtf v3.4s, v3.4s
; CHECK-NEXT:    ucvtf v4.4s, v4.4s
; CHECK-NEXT:    ucvtf v6.4s, v6.4s
; CHECK-NEXT:    ucvtf v7.4s, v7.4s
; CHECK-NEXT:    ucvtf v16.4s, v16.4s
; CHECK-NEXT:    ucvtf v2.4s, v2.4s
; CHECK-NEXT:    stp q4, q3, [x10]
; CHECK-NEXT:    ucvtf v3.4s, v17.4s
; CHECK-NEXT:    ucvtf v4.4s, v5.4s
; CHECK-NEXT:    add x10, x3, x9
; CHECK-NEXT:    add x9, x4, x9
; CHECK-NEXT:    stp q7, q6, [x11]
; CHECK-NEXT:    stp q2, q16, [x10]
; CHECK-NEXT:    stp q4, q3, [x9]
; CHECK-NEXT:    b.lo .LBB0_2
; CHECK-NEXT:  .LBB0_3: // %exit
; CHECK-NEXT:    ret
ptr %dst2, ptr %dst3, i64 %n) {
entry:
%empty = icmp eq i64 %n, 0
br i1 %empty, label %exit, label %loop

loop:
%i = phi i64 [ 0, %entry ], [ %next, %loop ]
%src.off = mul i64 %i, 32
%dst.off = mul i64 %i, 8
%src.ptr = getelementptr i8, ptr %src, i64 %src.off
%p0 = getelementptr float, ptr %dst0, i64 %dst.off
%p1 = getelementptr float, ptr %dst1, i64 %dst.off
%p2 = getelementptr float, ptr %dst2, i64 %dst.off
%p3 = getelementptr float, ptr %dst3, i64 %dst.off

%wide = load <32 x i8>, ptr %src.ptr, align 1
%di = call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.vector.deinterleave4.v32i8(<32 x i8> %wide)

%v0 = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %di, 0
%v1 = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %di, 1
%v2 = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %di, 2
%v3 = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %di, 3

%f0 = uitofp <8 x i8> %v0 to <8 x float>
%f1 = uitofp <8 x i8> %v1 to <8 x float>
%f2 = uitofp <8 x i8> %v2 to <8 x float>
%f3 = uitofp <8 x i8> %v3 to <8 x float>

store <8 x float> %f0, ptr %p0, align 4
store <8 x float> %f1, ptr %p1, align 4
store <8 x float> %f2, ptr %p2, align 4
store <8 x float> %f3, ptr %p3, align 4

%next = add i64 %i, 1
%more = icmp ult i64 %next, %n
br i1 %more, label %loop, label %exit

exit:
ret void
}

define void @shuffle_uitofp(ptr %src, ptr %dst0, ptr %dst1,
; CHECK-LABEL: shuffle_uitofp:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cbz x5, .LBB1_3
; CHECK-NEXT:  // %bb.1: // %loop.preheader
; CHECK-NEXT:    adrp x8, .LCPI1_0
; CHECK-NEXT:    adrp x9, .LCPI1_1
; CHECK-NEXT:    adrp x10, .LCPI1_2
; CHECK-NEXT:    adrp x11, .LCPI1_3
; CHECK-NEXT:    ldr q0, [x8, :lo12:.LCPI1_0]
; CHECK-NEXT:    ldr q1, [x9, :lo12:.LCPI1_1]
; CHECK-NEXT:    ldr q2, [x10, :lo12:.LCPI1_2]
; CHECK-NEXT:    ldr q3, [x11, :lo12:.LCPI1_3]
; CHECK-NEXT:    mov x8, xzr
; CHECK-NEXT:  .LBB1_2: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    lsl x9, x8, #5
; CHECK-NEXT:    add x8, x8, #1
; CHECK-NEXT:    cmp x8, x5
; CHECK-NEXT:    add x10, x0, x9
; CHECK-NEXT:    add x11, x2, x9
; CHECK-NEXT:    ldp q5, q4, [x10]
; CHECK-NEXT:    add x10, x1, x9
; CHECK-NEXT:    tbl v6.16b, { v4.16b }, v0.16b
; CHECK-NEXT:    tbl v7.16b, { v5.16b }, v0.16b
; CHECK-NEXT:    tbl v16.16b, { v4.16b }, v1.16b
; CHECK-NEXT:    tbl v17.16b, { v5.16b }, v1.16b
; CHECK-NEXT:    tbl v18.16b, { v4.16b }, v2.16b
; CHECK-NEXT:    tbl v19.16b, { v5.16b }, v2.16b
; CHECK-NEXT:    tbl v4.16b, { v4.16b }, v3.16b
; CHECK-NEXT:    tbl v5.16b, { v5.16b }, v3.16b
; CHECK-NEXT:    ucvtf v6.4s, v6.4s
; CHECK-NEXT:    ucvtf v7.4s, v7.4s
; CHECK-NEXT:    ucvtf v16.4s, v16.4s
; CHECK-NEXT:    ucvtf v17.4s, v17.4s
; CHECK-NEXT:    ucvtf v18.4s, v18.4s
; CHECK-NEXT:    ucvtf v4.4s, v4.4s
; CHECK-NEXT:    ucvtf v5.4s, v5.4s
; CHECK-NEXT:    stp q7, q6, [x10]
; CHECK-NEXT:    ucvtf v6.4s, v19.4s
; CHECK-NEXT:    add x10, x3, x9
; CHECK-NEXT:    add x9, x4, x9
; CHECK-NEXT:    stp q17, q16, [x11]
; CHECK-NEXT:    stp q6, q18, [x10]
; CHECK-NEXT:    stp q5, q4, [x9]
; CHECK-NEXT:    b.lo .LBB1_2
; CHECK-NEXT:  .LBB1_3: // %exit
; CHECK-NEXT:    ret
ptr %dst2, ptr %dst3, i64 %n) {
entry:
%empty = icmp eq i64 %n, 0
br i1 %empty, label %exit, label %loop

loop:
%i = phi i64 [ 0, %entry ], [ %next, %loop ]
%src.off = mul i64 %i, 32
%dst.off = mul i64 %i, 8
%src.ptr = getelementptr i8, ptr %src, i64 %src.off
%p0 = getelementptr float, ptr %dst0, i64 %dst.off
%p1 = getelementptr float, ptr %dst1, i64 %dst.off
%p2 = getelementptr float, ptr %dst2, i64 %dst.off
%p3 = getelementptr float, ptr %dst3, i64 %dst.off

%wide = load <32 x i8>, ptr %src.ptr, align 1

%v0 = shufflevector <32 x i8> %wide, <32 x i8> poison,
<8 x i32> <i32 0, i32 4, i32 8, i32 12, i32 16, i32 20, i32 24, i32 28>
%v1 = shufflevector <32 x i8> %wide, <32 x i8> poison,
<8 x i32> <i32 1, i32 5, i32 9, i32 13, i32 17, i32 21, i32 25, i32 29>
%v2 = shufflevector <32 x i8> %wide, <32 x i8> poison,
<8 x i32> <i32 2, i32 6, i32 10, i32 14, i32 18, i32 22, i32 26, i32 30>
%v3 = shufflevector <32 x i8> %wide, <32 x i8> poison,
<8 x i32> <i32 3, i32 7, i32 11, i32 15, i32 19, i32 23, i32 27, i32 31>

%f0 = uitofp <8 x i8> %v0 to <8 x float>
%f1 = uitofp <8 x i8> %v1 to <8 x float>
%f2 = uitofp <8 x i8> %v2 to <8 x float>
%f3 = uitofp <8 x i8> %v3 to <8 x float>

store <8 x float> %f0, ptr %p0, align 4
store <8 x float> %f1, ptr %p1, align 4
store <8 x float> %f2, ptr %p2, align 4
store <8 x float> %f3, ptr %p3, align 4

%next = add i64 %i, 1
%more = icmp ult i64 %next, %n
br i1 %more, label %loop, label %exit

exit:
ret void
}
