; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=aarch64-linux-gnu -o - < %s | FileCheck %s

define i64 @absdiff(i64 %0, i64 %1) {
; CHECK-LABEL: absdiff:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sub x8, x1, x0
; CHECK-NEXT:    subs x9, x0, x1
; CHECK-NEXT:    csel x0, x8, x9, lo
; CHECK-NEXT:    ret
  %3 = icmp ult i64 %0, %1
  %4 = sub i64 %0, %1
  %5 = sub i64 %1, %0
  %6 = select i1 %3, i64 %5, i64 %4
  ret i64 %6
}

define i64 @absdiff1(i64 %0, i64 %1) {
; CHECK-LABEL: absdiff1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    subs x8, x0, x1
; CHECK-NEXT:    csetm x9, lo
; CHECK-NEXT:    cinv x8, x8, lo
; CHECK-NEXT:    sub x0, x8, x9
; CHECK-NEXT:    ret
  %3 = icmp ult i64 %0, %1
  %4 = sext i1 %3 to i64
  %5 = sub i64 %0, %1
  %6 = xor i64 %5, %4
  %7 = sub i64 %6, %4
  ret i64 %7
}

define i64 @absdiff2(i64 %0, i64 %1) {
; CHECK-LABEL: absdiff2:
; CHECK:       // %bb.0:
; CHECK-NEXT:    subs x8, x0, x1
; CHECK-NEXT:    cneg x0, x8, lo
; CHECK-NEXT:    ret
  %3 = icmp ult i64 %0, %1
  %4 = sub i64 %0, %1
  %5 = sub i64 0, %4
  %6 = select i1 %3, i64 %5, i64 %4
  ret i64 %6
}
