; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=aarch64 -mattr=+sve %s -o - | FileCheck %s

define <vscale x 16 x i1> @whilewr_8(i64 %a, i64 %b) {
; CHECK-LABEL: whilewr_8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    sub x8, x1, x0
; CHECK-NEXT:    cmp x8, #1
; CHECK-NEXT:    csinv x8, x8, xzr, ge
; CHECK-NEXT:    whilelo p0.b, xzr, x8
; CHECK-NEXT:    ret
entry:
  %0 = call <vscale x 16 x i1> @llvm.loop.dependence.war.mask.nxv16i1.i64(i64 %a, i64 %b, i64 1)
  ret <vscale x 16 x i1> %0
}

define <vscale x 4 x i1> @whilewr_i32_addresses(i32 %a, i32 %b) {
; CHECK-LABEL: whilewr_i32_addresses:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    sub w8, w1, w0
; CHECK-NEXT:    asr w9, w8, #31
; CHECK-NEXT:    add w8, w8, w9, lsr #30
; CHECK-NEXT:    asr w8, w8, #2
; CHECK-NEXT:    cmp w8, #1
; CHECK-NEXT:    csinv w8, w8, wzr, ge
; CHECK-NEXT:    whilelo p0.s, wzr, w8
; CHECK-NEXT:    ret
entry:
  %0 = call <vscale x 4 x i1> @llvm.loop.dependence.war.mask.nxv4i1.i32(i32 %a, i32 %b, i32 4)
  ret <vscale x 4 x i1> %0
}
