; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-none-elf -verify-machineinstrs %s -o - | FileCheck %s --check-prefixes=CHECK,CHECK-SD
; RUN: llc -mtriple=aarch64-none-elf -global-isel -verify-machineinstrs %s -o - | FileCheck %s --check-prefixes=CHECK,CHECK-GI

define i64 @left_full(i64 %bits) {
; CHECK-LABEL: left_full:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    eor x8, x0, x0, lsl #30
; CHECK-NEXT:    and x0, x8, #0x100000000
; CHECK-NEXT:    ret
entry:
  %shl = shl i64 %bits, 30
  %xor = xor i64 %shl, %bits
  %and = and i64 %xor, 4294967296
  ret i64 %and
}

define i64 @right_full(i64 %bits) {
; CHECK-LABEL: right_full:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    eor x8, x0, x0, lsr #30
; CHECK-NEXT:    and x0, x8, #0x100000000
; CHECK-NEXT:    ret
entry:
  %shr = lshr i64 %bits, 30
  %xor = xor i64 %shr, %bits
  %and = and i64 %xor, 4294967296
  ret i64 %and
}

define i64 @left_opt(i64 %bits) {
; CHECK-LABEL: left_opt:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    and x0, x0, #0x10000000
; CHECK-NEXT:    ret
entry:
  %and = and i64 %bits, 268435456
  ret i64 %and
}

define i64 @right_opt(i64 %bits) {
; CHECK-LABEL: right_opt:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    eor x8, x0, x0, lsr #30
; CHECK-NEXT:    and x0, x8, #0x10000000
; CHECK-NEXT:    ret
entry:
  %shr = lshr i64 %bits, 30
  %xor = xor i64 %shr, %bits
  %and = and i64 %xor, 268435456
  ret i64 %and
}

define i64 @right_opt_32bit_logical_mask(i64 %bits) {
; CHECK-SD-LABEL: right_opt_32bit_logical_mask:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    eor x8, x0, x0, lsr #30
; CHECK-SD-NEXT:    and w0, w8, #0x55555555
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: right_opt_32bit_logical_mask:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    eor x8, x0, x0, lsr #30
; CHECK-GI-NEXT:    mov w9, #1431655765 // =0x55555555
; CHECK-GI-NEXT:    and x0, x8, x9
; CHECK-GI-NEXT:    ret
entry:
  %shr = lshr i64 %bits, 30
  %xor = xor i64 %shr, %bits
  %and = and i64 %xor, 1431655765 ; 0x55555555
  ret i64 %and
}
