; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=aarch64-unknown-unknown -mattr=+neon,+fullfp16,+fprcvt | FileCheck %s --check-prefixes=CHECK
; RUN: llc < %s -mtriple aarch64-unknown-unknown -mattr=+sme,+neon,+fullfp16,+fprcvt -force-streaming | FileCheck %s --check-prefixes=CHECK-SME
; RUN: llc < %s -mtriple aarch64-unknown-unknown -mattr=+sve,+neon,+fullfp16,+fprcvt -force-streaming-compatible | FileCheck %s --check-prefixes=CHECK-SVE

define double @scvtf_bitcast_f32_to_f64(float %f) nounwind {
; CHECK-LABEL: scvtf_bitcast_f32_to_f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    scvtf d0, s0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: scvtf_bitcast_f32_to_f64:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    scvtf d0, s0
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: scvtf_bitcast_f32_to_f64:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    scvtf d0, s0
; CHECK-SVE-NEXT:    ret
  %i = bitcast float %f to i32
  %r = sitofp i32 %i to double
  ret double %r
}

define double @ucvtf_bitcast_f32_to_f64(float %f) nounwind {
; CHECK-LABEL: ucvtf_bitcast_f32_to_f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ucvtf d0, s0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: ucvtf_bitcast_f32_to_f64:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ucvtf d0, s0
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: ucvtf_bitcast_f32_to_f64:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ucvtf d0, s0
; CHECK-SVE-NEXT:    ret
  %i = bitcast float %f to i32
  %r = uitofp i32 %i to double
  ret double %r
}

define half @scvtf_bitcast_f32_to_f16(float %f) nounwind {
; CHECK-LABEL: scvtf_bitcast_f32_to_f16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    scvtf h0, s0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: scvtf_bitcast_f32_to_f16:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ptrue p0.s
; CHECK-SME-NEXT:    scvtf z0.h, p0/m, z0.s
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: scvtf_bitcast_f32_to_f16:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.s
; CHECK-SVE-NEXT:    // kill: def $s0 killed $s0 def $z0
; CHECK-SVE-NEXT:    scvtf z0.h, p0/m, z0.s
; CHECK-SVE-NEXT:    // kill: def $h0 killed $h0 killed $z0
; CHECK-SVE-NEXT:    ret
  %i = bitcast float %f to i32
  %r = sitofp i32 %i to half
  ret half %r
}

define half @ucvtf_bitcast_f32_to_f16(float %f) nounwind {
; CHECK-LABEL: ucvtf_bitcast_f32_to_f16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ucvtf h0, s0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: ucvtf_bitcast_f32_to_f16:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ptrue p0.s
; CHECK-SME-NEXT:    ucvtf z0.h, p0/m, z0.s
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: ucvtf_bitcast_f32_to_f16:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.s
; CHECK-SVE-NEXT:    // kill: def $s0 killed $s0 def $z0
; CHECK-SVE-NEXT:    ucvtf z0.h, p0/m, z0.s
; CHECK-SVE-NEXT:    // kill: def $h0 killed $h0 killed $z0
; CHECK-SVE-NEXT:    ret
  %i = bitcast float %f to i32
  %r = uitofp i32 %i to half
  ret half %r
}

define float @scvtf_bitcast_f64_to_f32(double %d) nounwind {
; CHECK-LABEL: scvtf_bitcast_f64_to_f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    scvtf s0, d0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: scvtf_bitcast_f64_to_f32:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ptrue p0.d
; CHECK-SME-NEXT:    scvtf z0.s, p0/m, z0.d
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: scvtf_bitcast_f64_to_f32:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.d
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-SVE-NEXT:    scvtf z0.s, p0/m, z0.d
; CHECK-SVE-NEXT:    // kill: def $s0 killed $s0 killed $z0
; CHECK-SVE-NEXT:    ret
  %i = bitcast double %d to i64
  %r = sitofp i64 %i to float
  ret float %r
}

define float @ucvtf_bitcast_f64_to_f32(double %d) nounwind {
; CHECK-LABEL: ucvtf_bitcast_f64_to_f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ucvtf s0, d0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: ucvtf_bitcast_f64_to_f32:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ptrue p0.d
; CHECK-SME-NEXT:    ucvtf z0.s, p0/m, z0.d
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: ucvtf_bitcast_f64_to_f32:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.d
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-SVE-NEXT:    ucvtf z0.s, p0/m, z0.d
; CHECK-SVE-NEXT:    // kill: def $s0 killed $s0 killed $z0
; CHECK-SVE-NEXT:    ret
  %i = bitcast double %d to i64
  %r = uitofp i64 %i to float
  ret float %r
}

define half @scvtf_bitcast_f64_to_f16(double %d) nounwind {
; CHECK-LABEL: scvtf_bitcast_f64_to_f16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    scvtf h0, d0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: scvtf_bitcast_f64_to_f16:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ptrue p0.d
; CHECK-SME-NEXT:    scvtf z0.h, p0/m, z0.d
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: scvtf_bitcast_f64_to_f16:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.d
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-SVE-NEXT:    scvtf z0.h, p0/m, z0.d
; CHECK-SVE-NEXT:    // kill: def $h0 killed $h0 killed $z0
; CHECK-SVE-NEXT:    ret
  %i = bitcast double %d to i64
  %r = sitofp i64 %i to half
  ret half %r
}

define half @ucvtf_bitcast_f64_to_f16(double %d) nounwind {
; CHECK-LABEL: ucvtf_bitcast_f64_to_f16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ucvtf h0, d0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: ucvtf_bitcast_f64_to_f16:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ptrue p0.d
; CHECK-SME-NEXT:    ucvtf z0.h, p0/m, z0.d
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: ucvtf_bitcast_f64_to_f16:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.d
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-SVE-NEXT:    ucvtf z0.h, p0/m, z0.d
; CHECK-SVE-NEXT:    // kill: def $h0 killed $h0 killed $z0
; CHECK-SVE-NEXT:    ret
  %i = bitcast double %d to i64
  %r = uitofp i64 %i to half
  ret half %r
}

define float @scvtf_bitcast_f32_to_f32(float %f) nounwind {
; CHECK-LABEL: scvtf_bitcast_f32_to_f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    scvtf s0, s0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: scvtf_bitcast_f32_to_f32:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ptrue p0.s
; CHECK-SME-NEXT:    scvtf z0.s, p0/m, z0.s
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: scvtf_bitcast_f32_to_f32:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.s
; CHECK-SVE-NEXT:    // kill: def $s0 killed $s0 def $z0
; CHECK-SVE-NEXT:    scvtf z0.s, p0/m, z0.s
; CHECK-SVE-NEXT:    // kill: def $s0 killed $s0 killed $z0
; CHECK-SVE-NEXT:    ret
  %i = bitcast float %f to i32
  %r = sitofp i32 %i to float
  ret float %r
}

define float @ucvtf_bitcast_f32_to_f32(float %f) nounwind {
; CHECK-LABEL: ucvtf_bitcast_f32_to_f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ucvtf s0, s0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: ucvtf_bitcast_f32_to_f32:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ptrue p0.s
; CHECK-SME-NEXT:    ucvtf z0.s, p0/m, z0.s
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: ucvtf_bitcast_f32_to_f32:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.s
; CHECK-SVE-NEXT:    // kill: def $s0 killed $s0 def $z0
; CHECK-SVE-NEXT:    ucvtf z0.s, p0/m, z0.s
; CHECK-SVE-NEXT:    // kill: def $s0 killed $s0 killed $z0
; CHECK-SVE-NEXT:    ret
  %i = bitcast float %f to i32
  %r = uitofp i32 %i to float
  ret float %r
}

define double @scvtf_bitcast_f64_to_f64(double %d) nounwind {
; CHECK-LABEL: scvtf_bitcast_f64_to_f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    scvtf d0, d0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: scvtf_bitcast_f64_to_f64:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ptrue p0.d
; CHECK-SME-NEXT:    scvtf z0.d, p0/m, z0.d
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: scvtf_bitcast_f64_to_f64:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.d
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-SVE-NEXT:    scvtf z0.d, p0/m, z0.d
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-SVE-NEXT:    ret
  %i = bitcast double %d to i64
  %r = sitofp i64 %i to double
  ret double %r
}

define double @ucvtf_bitcast_f64_to_f64(double %d) nounwind {
; CHECK-LABEL: ucvtf_bitcast_f64_to_f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ucvtf d0, d0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: ucvtf_bitcast_f64_to_f64:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ptrue p0.d
; CHECK-SME-NEXT:    ucvtf z0.d, p0/m, z0.d
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: ucvtf_bitcast_f64_to_f64:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.d
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-SVE-NEXT:    ucvtf z0.d, p0/m, z0.d
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-SVE-NEXT:    ret
  %i = bitcast double %d to i64
  %r = uitofp i64 %i to double
  ret double %r
}

;
; Also test `strictfp` nodes
;

define double @scvtf_bitcast_f32_to_f64_strict(float %f) nounwind strictfp {
; CHECK-LABEL: scvtf_bitcast_f32_to_f64_strict:
; CHECK:       // %bb.0:
; CHECK-NEXT:    scvtf d0, s0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: scvtf_bitcast_f32_to_f64_strict:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    scvtf d0, s0
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: scvtf_bitcast_f32_to_f64_strict:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    scvtf d0, s0
; CHECK-SVE-NEXT:    ret
  %i = bitcast float %f to i32
  %r = call double @llvm.experimental.constrained.sitofp.f64.i32(i32 %i, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret double %r
}

define double @ucvtf_bitcast_f32_to_f64_strict(float %f) nounwind strictfp {
; CHECK-LABEL: ucvtf_bitcast_f32_to_f64_strict:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ucvtf d0, s0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: ucvtf_bitcast_f32_to_f64_strict:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ucvtf d0, s0
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: ucvtf_bitcast_f32_to_f64_strict:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ucvtf d0, s0
; CHECK-SVE-NEXT:    ret
  %i = bitcast float %f to i32
  %r = call double @llvm.experimental.constrained.uitofp.f64.i32(i32 %i, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret double %r
}

define half @scvtf_bitcast_f32_to_f16_strict(float %f) nounwind strictfp {
; CHECK-LABEL: scvtf_bitcast_f32_to_f16_strict:
; CHECK:       // %bb.0:
; CHECK-NEXT:    scvtf h0, s0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: scvtf_bitcast_f32_to_f16_strict:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    scvtf h0, s0
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: scvtf_bitcast_f32_to_f16_strict:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    scvtf h0, s0
; CHECK-SVE-NEXT:    ret
  %i = bitcast float %f to i32
  %r = call half @llvm.experimental.constrained.sitofp.f16.i32(i32 %i, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret half %r
}

define half @ucvtf_bitcast_f32_to_f16_strict(float %f) nounwind strictfp {
; CHECK-LABEL: ucvtf_bitcast_f32_to_f16_strict:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ucvtf h0, s0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: ucvtf_bitcast_f32_to_f16_strict:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ucvtf h0, s0
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: ucvtf_bitcast_f32_to_f16_strict:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ucvtf h0, s0
; CHECK-SVE-NEXT:    ret
  %i = bitcast float %f to i32
  %r = call half @llvm.experimental.constrained.uitofp.f16.i32(i32 %i, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret half %r
}

define float @scvtf_bitcast_f64_to_f32_strict(double %d) nounwind strictfp {
; CHECK-LABEL: scvtf_bitcast_f64_to_f32_strict:
; CHECK:       // %bb.0:
; CHECK-NEXT:    scvtf s0, d0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: scvtf_bitcast_f64_to_f32_strict:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    scvtf s0, d0
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: scvtf_bitcast_f64_to_f32_strict:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    scvtf s0, d0
; CHECK-SVE-NEXT:    ret
  %i = bitcast double %d to i64
  %r = call float @llvm.experimental.constrained.sitofp.f32.i64(i64 %i, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret float %r
}

define float @ucvtf_bitcast_f64_to_f32_strict(double %d) nounwind strictfp {
; CHECK-LABEL: ucvtf_bitcast_f64_to_f32_strict:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ucvtf s0, d0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: ucvtf_bitcast_f64_to_f32_strict:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ucvtf s0, d0
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: ucvtf_bitcast_f64_to_f32_strict:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ucvtf s0, d0
; CHECK-SVE-NEXT:    ret
  %i = bitcast double %d to i64
  %r = call float @llvm.experimental.constrained.uitofp.f32.i64(i64 %i, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret float %r
}

define half @scvtf_bitcast_f64_to_f16_strict(double %d) nounwind strictfp {
; CHECK-LABEL: scvtf_bitcast_f64_to_f16_strict:
; CHECK:       // %bb.0:
; CHECK-NEXT:    scvtf h0, d0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: scvtf_bitcast_f64_to_f16_strict:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    scvtf h0, d0
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: scvtf_bitcast_f64_to_f16_strict:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    scvtf h0, d0
; CHECK-SVE-NEXT:    ret
  %i = bitcast double %d to i64
  %r = call half @llvm.experimental.constrained.sitofp.f16.i64(i64 %i, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret half %r
}

define half @ucvtf_bitcast_f64_to_f16_strict(double %d) nounwind strictfp {
; CHECK-LABEL: ucvtf_bitcast_f64_to_f16_strict:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ucvtf h0, d0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: ucvtf_bitcast_f64_to_f16_strict:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ucvtf h0, d0
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: ucvtf_bitcast_f64_to_f16_strict:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ucvtf h0, d0
; CHECK-SVE-NEXT:    ret
  %i = bitcast double %d to i64
  %r = call half @llvm.experimental.constrained.uitofp.f16.i64(i64 %i, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret half %r
}

define float @scvtf_bitcast_f32_to_f32_strict(float %f) nounwind strictfp {
; CHECK-LABEL: scvtf_bitcast_f32_to_f32_strict:
; CHECK:       // %bb.0:
; CHECK-NEXT:    scvtf s0, s0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: scvtf_bitcast_f32_to_f32_strict:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    scvtf s0, s0
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: scvtf_bitcast_f32_to_f32_strict:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    scvtf s0, s0
; CHECK-SVE-NEXT:    ret
  %i = bitcast float %f to i32
  %r = call float @llvm.experimental.constrained.sitofp.f32.i32(i32 %i, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret float %r
}

define float @ucvtf_bitcast_f32_to_f32_strict(float %f) nounwind strictfp {
; CHECK-LABEL: ucvtf_bitcast_f32_to_f32_strict:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ucvtf s0, s0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: ucvtf_bitcast_f32_to_f32_strict:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ucvtf s0, s0
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: ucvtf_bitcast_f32_to_f32_strict:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ucvtf s0, s0
; CHECK-SVE-NEXT:    ret
  %i = bitcast float %f to i32
  %r = call float @llvm.experimental.constrained.uitofp.f32.i32(i32 %i, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret float %r
}

define double @scvtf_bitcast_f64_to_f64_strict(double %d) nounwind strictfp {
; CHECK-LABEL: scvtf_bitcast_f64_to_f64_strict:
; CHECK:       // %bb.0:
; CHECK-NEXT:    scvtf d0, d0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: scvtf_bitcast_f64_to_f64_strict:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    scvtf d0, d0
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: scvtf_bitcast_f64_to_f64_strict:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    scvtf d0, d0
; CHECK-SVE-NEXT:    ret
  %i = bitcast double %d to i64
  %r = call double @llvm.experimental.constrained.sitofp.f64.i64(i64 %i, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret double %r
}

define double @ucvtf_bitcast_f64_to_f64_strict(double %d) nounwind strictfp {
; CHECK-LABEL: ucvtf_bitcast_f64_to_f64_strict:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ucvtf d0, d0
; CHECK-NEXT:    ret
;
; CHECK-SME-LABEL: ucvtf_bitcast_f64_to_f64_strict:
; CHECK-SME:       // %bb.0:
; CHECK-SME-NEXT:    ucvtf d0, d0
; CHECK-SME-NEXT:    ret
;
; CHECK-SVE-LABEL: ucvtf_bitcast_f64_to_f64_strict:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ucvtf d0, d0
; CHECK-SVE-NEXT:    ret
  %i = bitcast double %d to i64
  %r = call double @llvm.experimental.constrained.uitofp.f64.i64(i64 %i, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret double %r
}
