; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple aarch64-unknown-unknown -mattr=+fprcvt,+fullfp16 | FileCheck %s --check-prefixes=CHECK,CHECK-FPRCVT
; RUN: llc < %s -mtriple aarch64-unknown-unknown -mattr=+fullfp16 | FileCheck %s --check-prefixes=CHECK,CHECK-NOFPRCVT
; RUN: llc < %s -mtriple aarch64-unknown-unknown -global-isel -mattr=+fprcvt,+fullfp16 | FileCheck %s --check-prefixes=CHECK,CHECK-FPRCVT
; RUN: llc < %s -mtriple aarch64-unknown-unknown -global-isel -mattr=+fullfp16 | FileCheck %s --check-prefixes=CHECK,CHECK-NOFPRCVT


;
; Lround
;

define float @lround_i32_f16_simd(half %x)  {
; CHECK-FPRCVT-LABEL: lround_i32_f16_simd:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    fcvtas s0, h0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: lround_i32_f16_simd:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    fcvtas w8, h0
; CHECK-NOFPRCVT-NEXT:    fmov s0, w8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i32 @llvm.lround.i32.f16(half %x)
  %sum = bitcast i32 %val to float
  ret float %sum
}

define float @lround_i32_f32_simd(float %x)  {
; CHECK-LABEL: lround_i32_f32_simd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtas s0, s0
; CHECK-NEXT:    ret
  %val = call i32 @llvm.lround.i32.f32(float %x)
  %bc  = bitcast i32 %val to float
  ret float %bc
}

define float @lround_i32_f64_simd(double %x)  {
; CHECK-FPRCVT-LABEL: lround_i32_f64_simd:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    fcvtas s0, d0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: lround_i32_f64_simd:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    fcvtas w8, d0
; CHECK-NOFPRCVT-NEXT:    fmov s0, w8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i32 @llvm.lround.i32.f64(double %x)
  %bc  = bitcast i32 %val to float
  ret float %bc
}

define double @lround_i64_f16_simd(half %x)  {
; CHECK-FPRCVT-LABEL: lround_i64_f16_simd:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    fcvtas d0, h0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: lround_i64_f16_simd:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    fcvtas x8, h0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.lround.i64.f16(half %x)
  %bc  = bitcast i64 %val to double
  ret double %bc
}

define double @lround_i64_f32_simd(float %x)  {
; CHECK-FPRCVT-LABEL: lround_i64_f32_simd:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    fcvtas d0, s0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: lround_i64_f32_simd:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    fcvtas x8, s0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.lround.i64.f32(float %x)
  %bc  = bitcast i64 %val to double
  ret double %bc
}

define double @lround_i64_f64_simd(double %x)  {
; CHECK-LABEL: lround_i64_f64_simd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtas d0, d0
; CHECK-NEXT:    ret
  %val = call i64 @llvm.lround.i64.f64(double %x)
  %bc  = bitcast i64 %val to double
  ret double %bc
}

;
; Llround
;

define double @llround_i64_f16_simd(half %x)  {
; CHECK-FPRCVT-LABEL: llround_i64_f16_simd:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    fcvtas d0, h0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: llround_i64_f16_simd:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    fcvtas x8, h0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.llround.i64.f16(half %x)
  %sum = bitcast i64 %val to double
  ret double %sum
}

define double @llround_i64_f32_simd(float %x)  {
; CHECK-FPRCVT-LABEL: llround_i64_f32_simd:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    fcvtas d0, s0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: llround_i64_f32_simd:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    fcvtas x8, s0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.llround.i64.f32(float %x)
  %bc  = bitcast i64 %val to double
  ret double %bc
}

define double @llround_i64_f64_simd(double %x)  {
; CHECK-LABEL: llround_i64_f64_simd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtas d0, d0
; CHECK-NEXT:    ret
  %val = call i64 @llvm.llround.i64.f64(double %x)
  %bc  = bitcast i64 %val to double
  ret double %bc
}

;
; Lrint
;

define float @lrint_i32_f16_simd(half %x)  {
; CHECK-FPRCVT-LABEL: lrint_i32_f16_simd:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    frintx h0, h0
; CHECK-FPRCVT-NEXT:    fcvtzs s0, h0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: lrint_i32_f16_simd:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    frintx h0, h0
; CHECK-NOFPRCVT-NEXT:    fcvtzs w8, h0
; CHECK-NOFPRCVT-NEXT:    fmov s0, w8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i32 @llvm.lrint.i32.f16(half %x)
  %sum = bitcast i32 %val to float
  ret float %sum
}

define float @lrint_i32_f32_simd(float %x)  {
; CHECK-LABEL: lrint_i32_f32_simd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frintx s0, s0
; CHECK-NEXT:    fcvtzs s0, s0
; CHECK-NEXT:    ret
  %val = call i32 @llvm.lrint.i32.f32(float %x)
  %bc  = bitcast i32 %val to float
  ret float %bc
}

define float @lrint_i32_f64_simd(double %x)  {
; CHECK-FPRCVT-LABEL: lrint_i32_f64_simd:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    frintx d0, d0
; CHECK-FPRCVT-NEXT:    fcvtzs s0, d0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: lrint_i32_f64_simd:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    frintx d0, d0
; CHECK-NOFPRCVT-NEXT:    fcvtzs w8, d0
; CHECK-NOFPRCVT-NEXT:    fmov s0, w8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i32 @llvm.lrint.i32.f64(double %x)
  %bc  = bitcast i32 %val to float
  ret float %bc
}

define double @lrint_i64_f16_simd(half %x)  {
; CHECK-FPRCVT-LABEL: lrint_i64_f16_simd:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    frintx h0, h0
; CHECK-FPRCVT-NEXT:    fcvtzs d0, h0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: lrint_i64_f16_simd:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    frintx h0, h0
; CHECK-NOFPRCVT-NEXT:    fcvtzs x8, h0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.lrint.i64.f16(half %x)
  %bc  = bitcast i64 %val to double
  ret double %bc
}

define double @lrint_i64_f32_simd(float %x)  {
; CHECK-FPRCVT-LABEL: lrint_i64_f32_simd:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    frintx s0, s0
; CHECK-FPRCVT-NEXT:    fcvtzs d0, s0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: lrint_i64_f32_simd:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    frintx s0, s0
; CHECK-NOFPRCVT-NEXT:    fcvtzs x8, s0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.lrint.i64.f32(float %x)
  %bc  = bitcast i64 %val to double
  ret double %bc
}

define double @lrint_i64_f64_simd(double %x)  {
; CHECK-LABEL: lrint_i64_f64_simd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frintx d0, d0
; CHECK-NEXT:    fcvtzs d0, d0
; CHECK-NEXT:    ret
  %val = call i64 @llvm.lrint.i64.f64(double %x)
  %bc  = bitcast i64 %val to double
  ret double %bc
}

;
; Llrint
;

define double @llrint_i64_f16_simd(half %x)  {
; CHECK-FPRCVT-LABEL: llrint_i64_f16_simd:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    frintx h0, h0
; CHECK-FPRCVT-NEXT:    fcvtzs d0, h0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: llrint_i64_f16_simd:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    frintx h0, h0
; CHECK-NOFPRCVT-NEXT:    fcvtzs x8, h0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.llrint.i64.f16(half %x)
  %sum = bitcast i64 %val to double
  ret double %sum
}

define double @llrint_i64_f32_simd(float %x)  {
; CHECK-FPRCVT-LABEL: llrint_i64_f32_simd:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    frintx s0, s0
; CHECK-FPRCVT-NEXT:    fcvtzs d0, s0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: llrint_i64_f32_simd:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    frintx s0, s0
; CHECK-NOFPRCVT-NEXT:    fcvtzs x8, s0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.llrint.i64.f32(float %x)
  %bc  = bitcast i64 %val to double
  ret double %bc
}

define double @llrint_i64_f64_simd(double %x)  {
; CHECK-LABEL: llrint_i64_f64_simd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frintx d0, d0
; CHECK-NEXT:    fcvtzs d0, d0
; CHECK-NEXT:    ret
  %val = call i64 @llvm.llrint.i64.f64(double %x)
  %bc  = bitcast i64 %val to double
  ret double %bc
}

;
; Lround scalar_to_vector
;

define <1 x i64> @lround_i64_f16_scalar_to_vec(half %x)  {
; CHECK-FPRCVT-LABEL: lround_i64_f16_scalar_to_vec:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    fcvtas d0, h0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: lround_i64_f16_scalar_to_vec:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    fcvtas x8, h0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.lround.i64.f16(half %x)
  %vec = insertelement <1 x i64> poison, i64 %val, i32 0
  ret <1 x i64> %vec
}

define <1 x i64> @lround_i64_f32_scalar_to_vec(float %x)  {
; CHECK-FPRCVT-LABEL: lround_i64_f32_scalar_to_vec:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    fcvtas d0, s0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: lround_i64_f32_scalar_to_vec:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    fcvtas x8, s0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.lround.i64.f32(float %x)
  %vec = insertelement <1 x i64> poison, i64 %val, i32 0
  ret <1 x i64> %vec
}

define <1 x i64> @lround_i64_f64_scalar_to_vec(double %x)  {
; CHECK-LABEL: lround_i64_f64_scalar_to_vec:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtas d0, d0
; CHECK-NEXT:    ret
  %val = call i64 @llvm.lround.i64.f64(double %x)
  %vec = insertelement <1 x i64> poison, i64 %val, i32 0
  ret <1 x i64> %vec
}

;
; Llround scalar_to_vector
;

define <1 x i64> @llround_i64_f16_scalar_to_vec(half %x)  {
; CHECK-FPRCVT-LABEL: llround_i64_f16_scalar_to_vec:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    fcvtas d0, h0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: llround_i64_f16_scalar_to_vec:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    fcvtas x8, h0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.llround.i64.f16(half %x)
  %vec = insertelement <1 x i64> poison, i64 %val, i32 0
  ret <1 x i64> %vec
}

define <1 x i64> @llround_i64_f32_scalar_to_vec(float %x)  {
; CHECK-FPRCVT-LABEL: llround_i64_f32_scalar_to_vec:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    fcvtas d0, s0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: llround_i64_f32_scalar_to_vec:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    fcvtas x8, s0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.llround.i64.f32(float %x)
  %vec = insertelement <1 x i64> poison, i64 %val, i32 0
  ret <1 x i64> %vec
}

define <1 x i64> @llround_i64_f64_scalar_to_vec(double %x)  {
; CHECK-LABEL: llround_i64_f64_scalar_to_vec:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtas d0, d0
; CHECK-NEXT:    ret
  %val = call i64 @llvm.llround.i64.f64(double %x)
  %vec = insertelement <1 x i64> poison, i64 %val, i32 0
  ret <1 x i64> %vec
}

;
; Lrint scalar_to_vector
;

define <1 x i64> @lrint_i64_f16_scalar_to_vec(half %x)  {
; CHECK-FPRCVT-LABEL: lrint_i64_f16_scalar_to_vec:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    frintx h0, h0
; CHECK-FPRCVT-NEXT:    fcvtzs d0, h0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: lrint_i64_f16_scalar_to_vec:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    frintx h0, h0
; CHECK-NOFPRCVT-NEXT:    fcvtzs x8, h0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.lrint.i64.f16(half %x)
  %vec = insertelement <1 x i64> poison, i64 %val, i32 0
  ret <1 x i64> %vec
}

define <1 x i64> @lrint_i64_f32_scalar_to_vec(float %x)  {
; CHECK-FPRCVT-LABEL: lrint_i64_f32_scalar_to_vec:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    frintx s0, s0
; CHECK-FPRCVT-NEXT:    fcvtzs d0, s0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: lrint_i64_f32_scalar_to_vec:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    frintx s0, s0
; CHECK-NOFPRCVT-NEXT:    fcvtzs x8, s0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.lrint.i64.f32(float %x)
  %vec = insertelement <1 x i64> poison, i64 %val, i32 0
  ret <1 x i64> %vec
}

define <1 x i64> @lrint_i64_f64_scalar_to_vec(double %x)  {
; CHECK-LABEL: lrint_i64_f64_scalar_to_vec:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frintx d0, d0
; CHECK-NEXT:    fcvtzs d0, d0
; CHECK-NEXT:    ret
  %val = call i64 @llvm.lrint.i64.f64(double %x)
  %vec = insertelement <1 x i64> poison, i64 %val, i32 0
  ret <1 x i64> %vec
}

;
; Llrint scalar_to_vector
;

define <1 x i64> @llrint_i64_f16_scalar_to_vec(half %x)  {
; CHECK-FPRCVT-LABEL: llrint_i64_f16_scalar_to_vec:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    frintx h0, h0
; CHECK-FPRCVT-NEXT:    fcvtzs d0, h0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: llrint_i64_f16_scalar_to_vec:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    frintx h0, h0
; CHECK-NOFPRCVT-NEXT:    fcvtzs x8, h0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.llrint.i64.f16(half %x)
  %vec = insertelement <1 x i64> poison, i64 %val, i32 0
  ret <1 x i64> %vec
}

define <1 x i64> @llrint_i64_f32_scalar_to_vec(float %x)  {
; CHECK-FPRCVT-LABEL: llrint_i64_f32_scalar_to_vec:
; CHECK-FPRCVT:       // %bb.0:
; CHECK-FPRCVT-NEXT:    frintx s0, s0
; CHECK-FPRCVT-NEXT:    fcvtzs d0, s0
; CHECK-FPRCVT-NEXT:    ret
;
; CHECK-NOFPRCVT-LABEL: llrint_i64_f32_scalar_to_vec:
; CHECK-NOFPRCVT:       // %bb.0:
; CHECK-NOFPRCVT-NEXT:    frintx s0, s0
; CHECK-NOFPRCVT-NEXT:    fcvtzs x8, s0
; CHECK-NOFPRCVT-NEXT:    fmov d0, x8
; CHECK-NOFPRCVT-NEXT:    ret
  %val = call i64 @llvm.llrint.i64.f32(float %x)
  %vec = insertelement <1 x i64> poison, i64 %val, i32 0
  ret <1 x i64> %vec
}

define <1 x i64> @llrint_i64_f64_scalar_to_vec(double %x)  {
; CHECK-LABEL: llrint_i64_f64_scalar_to_vec:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frintx d0, d0
; CHECK-NEXT:    fcvtzs d0, d0
; CHECK-NEXT:    ret
  %val = call i64 @llvm.llrint.i64.f64(double %x)
  %vec = insertelement <1 x i64> poison, i64 %val, i32 0
  ret <1 x i64> %vec
}
