; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=arm64ec-pc-windows-msvc < %s | FileCheck %s

@a = external dllimport global i32
declare dllimport void @b()

define ptr @dllimport_var() nounwind {
; CHECK-LABEL: dllimport_var:
; CHECK:       // %bb.0:
; CHECK-NEXT:    adrp x0, __imp_a
; CHECK-NEXT:    ldr x0, [x0, :lo12:__imp_a]
; CHECK-NEXT:    ret
  ret ptr @a
}

define ptr @dllimport_fn() nounwind {
; CHECK-LABEL: dllimport_fn:
; CHECK:       // %bb.0:
; CHECK-NEXT:    .globl __imp_b
; CHECK-NEXT:    adrp x0, __imp_aux_b
; CHECK-NEXT:    .globl __imp_b
; CHECK-NEXT:    ldr x0, [x0, :lo12:__imp_aux_b]
; CHECK-NEXT:    ret
  ret ptr @b
}

define void @dllimport_fn_call() nounwind {
; CHECK-LABEL: dllimport_fn_call:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    adrp x8, __imp_b
; CHECK-NEXT:    ldr x8, [x8, :lo12:__imp_b]
; CHECK-NEXT:    blr x8
; CHECK-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  call void @b()
  ret void
}
