; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=arm64-none-linux-gnu -mattr=-neon < %s | FileCheck %s

define float @copy_FPR32(float %a, float %b) {
; CHECK-LABEL: copy_FPR32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fmov s0, s1
; CHECK-NEXT:    ret
  ret float %b;
}

define double @copy_FPR64(double %a, double %b) {
; CHECK-LABEL: copy_FPR64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fmov d0, d1
; CHECK-NEXT:    ret
  ret double %b;
}

define fp128 @copy_FPR128(fp128 %a, fp128 %b) {
; CHECK-LABEL: copy_FPR128:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str q1, [sp, #-16]!
; CHECK-NEXT:    ldr q0, [sp], #16
; CHECK-NEXT:    ret
  ret fp128 %b;
}
