; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=arm64-apple-darwin | FileCheck --check-prefixes=CHECK,CHECK-SD %s
; RUN: llc < %s -mtriple=arm64-apple-darwin -global-isel | FileCheck --check-prefixes=CHECK,CHECK-GI %s

define double @foo() {
; CHECK-LABEL: foo:
; CHECK:       ; %bb.0:
; CHECK-NEXT:  Lloh0:
; CHECK-NEXT:    adrp x8, lCPI0_0@PAGE
; CHECK-NEXT:  Lloh1:
; CHECK-NEXT:    ldr d0, [x8, lCPI0_0@PAGEOFF]
; CHECK-NEXT:    ret
; CHECK-NEXT:    .loh AdrpLdr Lloh0, Lloh1
  ret double 0x400921FB54442D18
}

define float @bar() {
; CHECK-LABEL: bar:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov w8, #4059 ; =0xfdb
; CHECK-NEXT:    movk w8, #16457, lsl #16
; CHECK-NEXT:    fmov s0, w8
; CHECK-NEXT:    ret
  ret float 0x400921FB60000000
}

define fp128 @baz() {
; CHECK-SD-LABEL: baz:
; CHECK-SD:       ; %bb.0:
; CHECK-SD-NEXT:    movi d0, #0000000000000000
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: baz:
; CHECK-GI:       ; %bb.0:
; CHECK-GI-NEXT:    movi.2d v0, #0000000000000000
; CHECK-GI-NEXT:    ret
  ret fp128 0xL00000000000000000000000000000000
}
