; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -verify-machineinstrs -mtriple=arm64-none-linux-gnu | FileCheck %s --check-prefixes=CHECK,CHECK-SD
; RUN: llc < %s -verify-machineinstrs -mtriple=arm64-none-linux-gnu -global-isel -global-isel-abort=2 2>&1 | FileCheck %s --check-prefixes=CHECK,CHECK-GI

; CHECK-GI:       warning: Instruction selection used fallback path for poly_mulv8i8
; CHECK-GI-NEXT:  warning: Instruction selection used fallback path for poly_mulv16i8
; CHECK-GI-NEXT:  warning: Instruction selection used fallback path for commutable_poly_mul

define <8 x i8> @mul8xi8(<8 x i8> %A, <8 x i8> %B) {
; CHECK-LABEL: mul8xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mul v0.8b, v0.8b, v1.8b
; CHECK-NEXT:    ret
	%tmp3 = mul <8 x i8> %A, %B;
	ret <8 x i8> %tmp3
}

define <16 x i8> @mul16xi8(<16 x i8> %A, <16 x i8> %B) {
; CHECK-LABEL: mul16xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mul v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    ret
	%tmp3 = mul <16 x i8> %A, %B;
	ret <16 x i8> %tmp3
}

define <4 x i16> @mul4xi16(<4 x i16> %A, <4 x i16> %B) {
; CHECK-LABEL: mul4xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mul v0.4h, v0.4h, v1.4h
; CHECK-NEXT:    ret
	%tmp3 = mul <4 x i16> %A, %B;
	ret <4 x i16> %tmp3
}

define <8 x i16> @mul8xi16(<8 x i16> %A, <8 x i16> %B) {
; CHECK-LABEL: mul8xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mul v0.8h, v0.8h, v1.8h
; CHECK-NEXT:    ret
	%tmp3 = mul <8 x i16> %A, %B;
	ret <8 x i16> %tmp3
}

define <2 x i32> @mul2xi32(<2 x i32> %A, <2 x i32> %B) {
; CHECK-LABEL: mul2xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mul v0.2s, v0.2s, v1.2s
; CHECK-NEXT:    ret
	%tmp3 = mul <2 x i32> %A, %B;
	ret <2 x i32> %tmp3
}

define <4 x i32> @mul4x32(<4 x i32> %A, <4 x i32> %B) {
; CHECK-LABEL: mul4x32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mul v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
	%tmp3 = mul <4 x i32> %A, %B;
	ret <4 x i32> %tmp3
}

define <1 x i64> @mul1xi64(<1 x i64> %A, <1 x i64> %B) {
; CHECK-SD-LABEL: mul1xi64:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    fmov x8, d1
; CHECK-SD-NEXT:    fmov x9, d0
; CHECK-SD-NEXT:    mul x8, x9, x8
; CHECK-SD-NEXT:    fmov d0, x8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: mul1xi64:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov x8, d0
; CHECK-GI-NEXT:    fmov x9, d1
; CHECK-GI-NEXT:    mul x8, x8, x9
; CHECK-GI-NEXT:    fmov d0, x8
; CHECK-GI-NEXT:    ret
  %tmp3 = mul <1 x i64> %A, %B;
  ret <1 x i64> %tmp3
}

define <2 x i64> @mul2xi64(<2 x i64> %A, <2 x i64> %B) {
; CHECK-SD-LABEL: mul2xi64:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    fmov x10, d1
; CHECK-SD-NEXT:    fmov x11, d0
; CHECK-SD-NEXT:    mov x8, v1.d[1]
; CHECK-SD-NEXT:    mov x9, v0.d[1]
; CHECK-SD-NEXT:    mul x10, x11, x10
; CHECK-SD-NEXT:    mul x8, x9, x8
; CHECK-SD-NEXT:    fmov d0, x10
; CHECK-SD-NEXT:    mov v0.d[1], x8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: mul2xi64:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov x10, d0
; CHECK-GI-NEXT:    fmov x11, d1
; CHECK-GI-NEXT:    mov x8, v0.d[1]
; CHECK-GI-NEXT:    mov x9, v1.d[1]
; CHECK-GI-NEXT:    mul x10, x10, x11
; CHECK-GI-NEXT:    mul x8, x8, x9
; CHECK-GI-NEXT:    fmov d0, x10
; CHECK-GI-NEXT:    mov v0.d[1], x8
; CHECK-GI-NEXT:    ret
  %tmp3 = mul <2 x i64> %A, %B;
  ret <2 x i64> %tmp3
}

 define <2 x float> @mul2xfloat(<2 x float> %A, <2 x float> %B) {
; CHECK-LABEL: mul2xfloat:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NEXT:    ret
	%tmp3 = fmul <2 x float> %A, %B;
	ret <2 x float> %tmp3
}

define <4 x float> @mul4xfloat(<4 x float> %A, <4 x float> %B) {
; CHECK-LABEL: mul4xfloat:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
	%tmp3 = fmul <4 x float> %A, %B;
	ret <4 x float> %tmp3
}
define <2 x double> @mul2xdouble(<2 x double> %A, <2 x double> %B) {
; CHECK-LABEL: mul2xdouble:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fmul v0.2d, v0.2d, v1.2d
; CHECK-NEXT:    ret
	%tmp3 = fmul <2 x double> %A, %B;
	ret <2 x double> %tmp3
}


 define <2 x float> @div2xfloat(<2 x float> %A, <2 x float> %B) {
; CHECK-LABEL: div2xfloat:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fdiv v0.2s, v0.2s, v1.2s
; CHECK-NEXT:    ret
	%tmp3 = fdiv <2 x float> %A, %B;
	ret <2 x float> %tmp3
}

define <4 x float> @div4xfloat(<4 x float> %A, <4 x float> %B) {
; CHECK-LABEL: div4xfloat:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fdiv v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
	%tmp3 = fdiv <4 x float> %A, %B;
	ret <4 x float> %tmp3
}
define <2 x double> @div2xdouble(<2 x double> %A, <2 x double> %B) {
; CHECK-LABEL: div2xdouble:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fdiv v0.2d, v0.2d, v1.2d
; CHECK-NEXT:    ret
	%tmp3 = fdiv <2 x double> %A, %B;
	ret <2 x double> %tmp3
}

define <1 x i8> @sdiv1x8(<1 x i8> %A, <1 x i8> %B) {
; CHECK-SD-LABEL: sdiv1x8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    smov w8, v1.b[0]
; CHECK-SD-NEXT:    smov w9, v0.b[0]
; CHECK-SD-NEXT:    sdiv w8, w9, w8
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: sdiv1x8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    smov w8, v0.b[0]
; CHECK-GI-NEXT:    smov w9, v1.b[0]
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    ret
	%tmp3 = sdiv <1 x i8> %A, %B;
	ret <1 x i8> %tmp3
}

define <8 x i8> @sdiv8x8(<8 x i8> %A, <8 x i8> %B) {
; CHECK-SD-LABEL: sdiv8x8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    smov w8, v1.b[1]
; CHECK-SD-NEXT:    smov w9, v0.b[1]
; CHECK-SD-NEXT:    smov w10, v0.b[0]
; CHECK-SD-NEXT:    smov w11, v0.b[2]
; CHECK-SD-NEXT:    smov w12, v0.b[3]
; CHECK-SD-NEXT:    smov w13, v0.b[4]
; CHECK-SD-NEXT:    smov w14, v0.b[5]
; CHECK-SD-NEXT:    sdiv w8, w9, w8
; CHECK-SD-NEXT:    smov w9, v1.b[0]
; CHECK-SD-NEXT:    sdiv w9, w10, w9
; CHECK-SD-NEXT:    smov w10, v1.b[2]
; CHECK-SD-NEXT:    sdiv w10, w11, w10
; CHECK-SD-NEXT:    smov w11, v1.b[3]
; CHECK-SD-NEXT:    fmov s2, w9
; CHECK-SD-NEXT:    smov w9, v1.b[6]
; CHECK-SD-NEXT:    mov v2.b[1], w8
; CHECK-SD-NEXT:    sdiv w11, w12, w11
; CHECK-SD-NEXT:    smov w12, v1.b[4]
; CHECK-SD-NEXT:    mov v2.b[2], w10
; CHECK-SD-NEXT:    smov w10, v0.b[6]
; CHECK-SD-NEXT:    sdiv w12, w13, w12
; CHECK-SD-NEXT:    smov w13, v1.b[5]
; CHECK-SD-NEXT:    mov v2.b[3], w11
; CHECK-SD-NEXT:    smov w11, v0.b[7]
; CHECK-SD-NEXT:    sdiv w8, w14, w13
; CHECK-SD-NEXT:    mov v2.b[4], w12
; CHECK-SD-NEXT:    sdiv w9, w10, w9
; CHECK-SD-NEXT:    smov w10, v1.b[7]
; CHECK-SD-NEXT:    mov v2.b[5], w8
; CHECK-SD-NEXT:    sdiv w8, w11, w10
; CHECK-SD-NEXT:    mov v2.b[6], w9
; CHECK-SD-NEXT:    mov v2.b[7], w8
; CHECK-SD-NEXT:    fmov d0, d2
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: sdiv8x8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    smov w8, v0.b[0]
; CHECK-GI-NEXT:    smov w9, v1.b[0]
; CHECK-GI-NEXT:    smov w10, v1.b[1]
; CHECK-GI-NEXT:    smov w11, v1.b[2]
; CHECK-GI-NEXT:    smov w12, v1.b[3]
; CHECK-GI-NEXT:    smov w13, v1.b[4]
; CHECK-GI-NEXT:    smov w14, v1.b[5]
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    smov w9, v0.b[1]
; CHECK-GI-NEXT:    sdiv w9, w9, w10
; CHECK-GI-NEXT:    smov w10, v0.b[2]
; CHECK-GI-NEXT:    fmov s2, w8
; CHECK-GI-NEXT:    sdiv w10, w10, w11
; CHECK-GI-NEXT:    smov w11, v0.b[3]
; CHECK-GI-NEXT:    mov v2.b[1], w9
; CHECK-GI-NEXT:    smov w9, v0.b[6]
; CHECK-GI-NEXT:    sdiv w11, w11, w12
; CHECK-GI-NEXT:    smov w12, v0.b[4]
; CHECK-GI-NEXT:    mov v2.b[2], w10
; CHECK-GI-NEXT:    smov w10, v0.b[7]
; CHECK-GI-NEXT:    sdiv w12, w12, w13
; CHECK-GI-NEXT:    smov w13, v0.b[5]
; CHECK-GI-NEXT:    mov v2.b[3], w11
; CHECK-GI-NEXT:    smov w11, v1.b[7]
; CHECK-GI-NEXT:    sdiv w8, w13, w14
; CHECK-GI-NEXT:    smov w13, v1.b[6]
; CHECK-GI-NEXT:    mov v2.b[4], w12
; CHECK-GI-NEXT:    sdiv w9, w9, w13
; CHECK-GI-NEXT:    mov v2.b[5], w8
; CHECK-GI-NEXT:    sdiv w8, w10, w11
; CHECK-GI-NEXT:    mov v2.b[6], w9
; CHECK-GI-NEXT:    mov v2.b[7], w8
; CHECK-GI-NEXT:    fmov d0, d2
; CHECK-GI-NEXT:    ret
	%tmp3 = sdiv <8 x i8> %A, %B;
	ret <8 x i8> %tmp3
}

define <16 x i8> @sdiv16x8(<16 x i8> %A, <16 x i8> %B) {
; CHECK-SD-LABEL: sdiv16x8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    smov w8, v1.b[1]
; CHECK-SD-NEXT:    smov w9, v0.b[1]
; CHECK-SD-NEXT:    smov w10, v0.b[0]
; CHECK-SD-NEXT:    smov w11, v0.b[2]
; CHECK-SD-NEXT:    smov w12, v0.b[3]
; CHECK-SD-NEXT:    smov w13, v0.b[4]
; CHECK-SD-NEXT:    smov w14, v0.b[5]
; CHECK-SD-NEXT:    smov w15, v0.b[6]
; CHECK-SD-NEXT:    smov w16, v0.b[7]
; CHECK-SD-NEXT:    smov w17, v0.b[8]
; CHECK-SD-NEXT:    smov w18, v0.b[9]
; CHECK-SD-NEXT:    sdiv w8, w9, w8
; CHECK-SD-NEXT:    smov w9, v1.b[0]
; CHECK-SD-NEXT:    sdiv w9, w10, w9
; CHECK-SD-NEXT:    smov w10, v1.b[2]
; CHECK-SD-NEXT:    sdiv w10, w11, w10
; CHECK-SD-NEXT:    smov w11, v1.b[3]
; CHECK-SD-NEXT:    fmov s2, w9
; CHECK-SD-NEXT:    smov w9, v1.b[10]
; CHECK-SD-NEXT:    mov v2.b[1], w8
; CHECK-SD-NEXT:    sdiv w11, w12, w11
; CHECK-SD-NEXT:    smov w12, v1.b[4]
; CHECK-SD-NEXT:    mov v2.b[2], w10
; CHECK-SD-NEXT:    smov w10, v0.b[10]
; CHECK-SD-NEXT:    sdiv w12, w13, w12
; CHECK-SD-NEXT:    smov w13, v1.b[5]
; CHECK-SD-NEXT:    mov v2.b[3], w11
; CHECK-SD-NEXT:    smov w11, v0.b[11]
; CHECK-SD-NEXT:    sdiv w13, w14, w13
; CHECK-SD-NEXT:    smov w14, v1.b[6]
; CHECK-SD-NEXT:    mov v2.b[4], w12
; CHECK-SD-NEXT:    smov w12, v0.b[12]
; CHECK-SD-NEXT:    sdiv w14, w15, w14
; CHECK-SD-NEXT:    smov w15, v1.b[7]
; CHECK-SD-NEXT:    mov v2.b[5], w13
; CHECK-SD-NEXT:    smov w13, v0.b[13]
; CHECK-SD-NEXT:    sdiv w15, w16, w15
; CHECK-SD-NEXT:    smov w16, v1.b[8]
; CHECK-SD-NEXT:    mov v2.b[6], w14
; CHECK-SD-NEXT:    sdiv w16, w17, w16
; CHECK-SD-NEXT:    smov w17, v1.b[9]
; CHECK-SD-NEXT:    mov v2.b[7], w15
; CHECK-SD-NEXT:    sdiv w8, w18, w17
; CHECK-SD-NEXT:    mov v2.b[8], w16
; CHECK-SD-NEXT:    sdiv w9, w10, w9
; CHECK-SD-NEXT:    smov w10, v1.b[11]
; CHECK-SD-NEXT:    mov v2.b[9], w8
; CHECK-SD-NEXT:    sdiv w10, w11, w10
; CHECK-SD-NEXT:    smov w11, v1.b[12]
; CHECK-SD-NEXT:    mov v2.b[10], w9
; CHECK-SD-NEXT:    smov w9, v1.b[14]
; CHECK-SD-NEXT:    sdiv w11, w12, w11
; CHECK-SD-NEXT:    smov w12, v1.b[13]
; CHECK-SD-NEXT:    mov v2.b[11], w10
; CHECK-SD-NEXT:    smov w10, v1.b[15]
; CHECK-SD-NEXT:    sdiv w8, w13, w12
; CHECK-SD-NEXT:    smov w12, v0.b[14]
; CHECK-SD-NEXT:    mov v2.b[12], w11
; CHECK-SD-NEXT:    smov w11, v0.b[15]
; CHECK-SD-NEXT:    sdiv w9, w12, w9
; CHECK-SD-NEXT:    mov v2.b[13], w8
; CHECK-SD-NEXT:    sdiv w8, w11, w10
; CHECK-SD-NEXT:    mov v2.b[14], w9
; CHECK-SD-NEXT:    mov v2.b[15], w8
; CHECK-SD-NEXT:    mov v0.16b, v2.16b
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: sdiv16x8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    smov w8, v0.b[0]
; CHECK-GI-NEXT:    smov w9, v1.b[0]
; CHECK-GI-NEXT:    smov w10, v1.b[1]
; CHECK-GI-NEXT:    smov w11, v1.b[2]
; CHECK-GI-NEXT:    smov w12, v1.b[3]
; CHECK-GI-NEXT:    smov w13, v1.b[4]
; CHECK-GI-NEXT:    smov w14, v1.b[5]
; CHECK-GI-NEXT:    smov w15, v1.b[6]
; CHECK-GI-NEXT:    smov w16, v1.b[7]
; CHECK-GI-NEXT:    smov w17, v1.b[8]
; CHECK-GI-NEXT:    smov w18, v1.b[9]
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    smov w9, v0.b[1]
; CHECK-GI-NEXT:    sdiv w9, w9, w10
; CHECK-GI-NEXT:    smov w10, v0.b[2]
; CHECK-GI-NEXT:    fmov s2, w8
; CHECK-GI-NEXT:    sdiv w10, w10, w11
; CHECK-GI-NEXT:    smov w11, v0.b[3]
; CHECK-GI-NEXT:    mov v2.b[1], w9
; CHECK-GI-NEXT:    smov w9, v0.b[10]
; CHECK-GI-NEXT:    sdiv w11, w11, w12
; CHECK-GI-NEXT:    smov w12, v0.b[4]
; CHECK-GI-NEXT:    mov v2.b[2], w10
; CHECK-GI-NEXT:    smov w10, v0.b[11]
; CHECK-GI-NEXT:    sdiv w12, w12, w13
; CHECK-GI-NEXT:    smov w13, v0.b[5]
; CHECK-GI-NEXT:    mov v2.b[3], w11
; CHECK-GI-NEXT:    smov w11, v1.b[11]
; CHECK-GI-NEXT:    sdiv w13, w13, w14
; CHECK-GI-NEXT:    smov w14, v0.b[6]
; CHECK-GI-NEXT:    mov v2.b[4], w12
; CHECK-GI-NEXT:    smov w12, v1.b[12]
; CHECK-GI-NEXT:    sdiv w14, w14, w15
; CHECK-GI-NEXT:    smov w15, v0.b[7]
; CHECK-GI-NEXT:    mov v2.b[5], w13
; CHECK-GI-NEXT:    smov w13, v1.b[13]
; CHECK-GI-NEXT:    sdiv w15, w15, w16
; CHECK-GI-NEXT:    smov w16, v0.b[8]
; CHECK-GI-NEXT:    mov v2.b[6], w14
; CHECK-GI-NEXT:    sdiv w16, w16, w17
; CHECK-GI-NEXT:    smov w17, v0.b[9]
; CHECK-GI-NEXT:    mov v2.b[7], w15
; CHECK-GI-NEXT:    sdiv w8, w17, w18
; CHECK-GI-NEXT:    smov w17, v1.b[10]
; CHECK-GI-NEXT:    mov v2.b[8], w16
; CHECK-GI-NEXT:    sdiv w9, w9, w17
; CHECK-GI-NEXT:    mov v2.b[9], w8
; CHECK-GI-NEXT:    smov w8, v0.b[14]
; CHECK-GI-NEXT:    sdiv w10, w10, w11
; CHECK-GI-NEXT:    smov w11, v0.b[12]
; CHECK-GI-NEXT:    mov v2.b[10], w9
; CHECK-GI-NEXT:    smov w9, v0.b[15]
; CHECK-GI-NEXT:    sdiv w11, w11, w12
; CHECK-GI-NEXT:    smov w12, v0.b[13]
; CHECK-GI-NEXT:    mov v2.b[11], w10
; CHECK-GI-NEXT:    smov w10, v1.b[15]
; CHECK-GI-NEXT:    sdiv w12, w12, w13
; CHECK-GI-NEXT:    smov w13, v1.b[14]
; CHECK-GI-NEXT:    mov v2.b[12], w11
; CHECK-GI-NEXT:    sdiv w8, w8, w13
; CHECK-GI-NEXT:    mov v2.b[13], w12
; CHECK-GI-NEXT:    sdiv w9, w9, w10
; CHECK-GI-NEXT:    mov v2.b[14], w8
; CHECK-GI-NEXT:    mov v2.b[15], w9
; CHECK-GI-NEXT:    mov v0.16b, v2.16b
; CHECK-GI-NEXT:    ret
	%tmp3 = sdiv <16 x i8> %A, %B;
	ret <16 x i8> %tmp3
}

define <1 x i16> @sdiv1x16(<1 x i16> %A, <1 x i16> %B) {
; CHECK-SD-LABEL: sdiv1x16:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    smov w8, v1.h[0]
; CHECK-SD-NEXT:    smov w9, v0.h[0]
; CHECK-SD-NEXT:    sdiv w8, w9, w8
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: sdiv1x16:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    smov w8, v0.h[0]
; CHECK-GI-NEXT:    smov w9, v1.h[0]
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    ret
	%tmp3 = sdiv <1 x i16> %A, %B;
	ret <1 x i16> %tmp3
}

define <4 x i16> @sdiv4x16(<4 x i16> %A, <4 x i16> %B) {
; CHECK-SD-LABEL: sdiv4x16:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    smov w8, v1.h[1]
; CHECK-SD-NEXT:    smov w9, v0.h[1]
; CHECK-SD-NEXT:    smov w10, v0.h[0]
; CHECK-SD-NEXT:    smov w11, v0.h[2]
; CHECK-SD-NEXT:    smov w12, v0.h[3]
; CHECK-SD-NEXT:    sdiv w8, w9, w8
; CHECK-SD-NEXT:    smov w9, v1.h[0]
; CHECK-SD-NEXT:    sdiv w9, w10, w9
; CHECK-SD-NEXT:    smov w10, v1.h[2]
; CHECK-SD-NEXT:    sdiv w10, w11, w10
; CHECK-SD-NEXT:    smov w11, v1.h[3]
; CHECK-SD-NEXT:    fmov s0, w9
; CHECK-SD-NEXT:    mov v0.h[1], w8
; CHECK-SD-NEXT:    sdiv w8, w12, w11
; CHECK-SD-NEXT:    mov v0.h[2], w10
; CHECK-SD-NEXT:    mov v0.h[3], w8
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: sdiv4x16:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    smov w8, v0.h[0]
; CHECK-GI-NEXT:    smov w9, v1.h[0]
; CHECK-GI-NEXT:    smov w10, v1.h[1]
; CHECK-GI-NEXT:    smov w11, v1.h[2]
; CHECK-GI-NEXT:    smov w12, v1.h[3]
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    smov w9, v0.h[1]
; CHECK-GI-NEXT:    sdiv w9, w9, w10
; CHECK-GI-NEXT:    smov w10, v0.h[2]
; CHECK-GI-NEXT:    sdiv w10, w10, w11
; CHECK-GI-NEXT:    smov w11, v0.h[3]
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    mov v0.h[1], w9
; CHECK-GI-NEXT:    sdiv w8, w11, w12
; CHECK-GI-NEXT:    mov v0.h[2], w10
; CHECK-GI-NEXT:    mov v0.h[3], w8
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-GI-NEXT:    ret
	%tmp3 = sdiv <4 x i16> %A, %B;
	ret <4 x i16> %tmp3
}

define <8 x i16> @sdiv8x16(<8 x i16> %A, <8 x i16> %B) {
; CHECK-SD-LABEL: sdiv8x16:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    smov w8, v1.h[1]
; CHECK-SD-NEXT:    smov w9, v0.h[1]
; CHECK-SD-NEXT:    smov w10, v0.h[0]
; CHECK-SD-NEXT:    smov w11, v0.h[2]
; CHECK-SD-NEXT:    smov w12, v0.h[3]
; CHECK-SD-NEXT:    smov w13, v0.h[4]
; CHECK-SD-NEXT:    smov w14, v0.h[5]
; CHECK-SD-NEXT:    sdiv w8, w9, w8
; CHECK-SD-NEXT:    smov w9, v1.h[0]
; CHECK-SD-NEXT:    sdiv w9, w10, w9
; CHECK-SD-NEXT:    smov w10, v1.h[2]
; CHECK-SD-NEXT:    sdiv w10, w11, w10
; CHECK-SD-NEXT:    smov w11, v1.h[3]
; CHECK-SD-NEXT:    fmov s2, w9
; CHECK-SD-NEXT:    smov w9, v1.h[6]
; CHECK-SD-NEXT:    mov v2.h[1], w8
; CHECK-SD-NEXT:    sdiv w11, w12, w11
; CHECK-SD-NEXT:    smov w12, v1.h[4]
; CHECK-SD-NEXT:    mov v2.h[2], w10
; CHECK-SD-NEXT:    smov w10, v0.h[6]
; CHECK-SD-NEXT:    sdiv w12, w13, w12
; CHECK-SD-NEXT:    smov w13, v1.h[5]
; CHECK-SD-NEXT:    mov v2.h[3], w11
; CHECK-SD-NEXT:    smov w11, v0.h[7]
; CHECK-SD-NEXT:    sdiv w8, w14, w13
; CHECK-SD-NEXT:    mov v2.h[4], w12
; CHECK-SD-NEXT:    sdiv w9, w10, w9
; CHECK-SD-NEXT:    smov w10, v1.h[7]
; CHECK-SD-NEXT:    mov v2.h[5], w8
; CHECK-SD-NEXT:    sdiv w8, w11, w10
; CHECK-SD-NEXT:    mov v2.h[6], w9
; CHECK-SD-NEXT:    mov v2.h[7], w8
; CHECK-SD-NEXT:    mov v0.16b, v2.16b
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: sdiv8x16:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    smov w8, v0.h[0]
; CHECK-GI-NEXT:    smov w9, v1.h[0]
; CHECK-GI-NEXT:    smov w10, v1.h[1]
; CHECK-GI-NEXT:    smov w11, v1.h[2]
; CHECK-GI-NEXT:    smov w12, v1.h[3]
; CHECK-GI-NEXT:    smov w13, v1.h[4]
; CHECK-GI-NEXT:    smov w14, v1.h[5]
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    smov w9, v0.h[1]
; CHECK-GI-NEXT:    sdiv w9, w9, w10
; CHECK-GI-NEXT:    smov w10, v0.h[2]
; CHECK-GI-NEXT:    fmov s2, w8
; CHECK-GI-NEXT:    sdiv w10, w10, w11
; CHECK-GI-NEXT:    smov w11, v0.h[3]
; CHECK-GI-NEXT:    mov v2.h[1], w9
; CHECK-GI-NEXT:    smov w9, v0.h[6]
; CHECK-GI-NEXT:    sdiv w11, w11, w12
; CHECK-GI-NEXT:    smov w12, v0.h[4]
; CHECK-GI-NEXT:    mov v2.h[2], w10
; CHECK-GI-NEXT:    smov w10, v0.h[7]
; CHECK-GI-NEXT:    sdiv w12, w12, w13
; CHECK-GI-NEXT:    smov w13, v0.h[5]
; CHECK-GI-NEXT:    mov v2.h[3], w11
; CHECK-GI-NEXT:    smov w11, v1.h[7]
; CHECK-GI-NEXT:    sdiv w8, w13, w14
; CHECK-GI-NEXT:    smov w13, v1.h[6]
; CHECK-GI-NEXT:    mov v2.h[4], w12
; CHECK-GI-NEXT:    sdiv w9, w9, w13
; CHECK-GI-NEXT:    mov v2.h[5], w8
; CHECK-GI-NEXT:    sdiv w8, w10, w11
; CHECK-GI-NEXT:    mov v2.h[6], w9
; CHECK-GI-NEXT:    mov v2.h[7], w8
; CHECK-GI-NEXT:    mov v0.16b, v2.16b
; CHECK-GI-NEXT:    ret
	%tmp3 = sdiv <8 x i16> %A, %B;
	ret <8 x i16> %tmp3
}

define <1 x i32> @sdiv1x32(<1 x i32> %A, <1 x i32> %B) {
; CHECK-SD-LABEL: sdiv1x32:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    fmov w8, s1
; CHECK-SD-NEXT:    fmov w9, s0
; CHECK-SD-NEXT:    sdiv w8, w9, w8
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: sdiv1x32:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:    fmov w9, s1
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    ret
	%tmp3 = sdiv <1 x i32> %A, %B;
	ret <1 x i32> %tmp3
}

define <2 x i32> @sdiv2x32(<2 x i32> %A, <2 x i32> %B) {
; CHECK-SD-LABEL: sdiv2x32:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    fmov w8, s1
; CHECK-SD-NEXT:    fmov w9, s0
; CHECK-SD-NEXT:    mov w10, v0.s[1]
; CHECK-SD-NEXT:    sdiv w8, w9, w8
; CHECK-SD-NEXT:    mov w9, v1.s[1]
; CHECK-SD-NEXT:    sdiv w9, w10, w9
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    mov v0.s[1], w9
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: sdiv2x32:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:    fmov w9, s1
; CHECK-GI-NEXT:    mov w10, v1.s[1]
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    mov w9, v0.s[1]
; CHECK-GI-NEXT:    sdiv w9, w9, w10
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    mov v0.s[1], w9
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-GI-NEXT:    ret
	%tmp3 = sdiv <2 x i32> %A, %B;
	ret <2 x i32> %tmp3
}

define <4 x i32> @sdiv4x32(<4 x i32> %A, <4 x i32> %B) {
; CHECK-SD-LABEL: sdiv4x32:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    mov w8, v1.s[1]
; CHECK-SD-NEXT:    mov w9, v0.s[1]
; CHECK-SD-NEXT:    fmov w10, s0
; CHECK-SD-NEXT:    mov w11, v0.s[2]
; CHECK-SD-NEXT:    mov w12, v0.s[3]
; CHECK-SD-NEXT:    sdiv w8, w9, w8
; CHECK-SD-NEXT:    fmov w9, s1
; CHECK-SD-NEXT:    sdiv w9, w10, w9
; CHECK-SD-NEXT:    mov w10, v1.s[2]
; CHECK-SD-NEXT:    sdiv w10, w11, w10
; CHECK-SD-NEXT:    mov w11, v1.s[3]
; CHECK-SD-NEXT:    fmov s0, w9
; CHECK-SD-NEXT:    mov v0.s[1], w8
; CHECK-SD-NEXT:    sdiv w8, w12, w11
; CHECK-SD-NEXT:    mov v0.s[2], w10
; CHECK-SD-NEXT:    mov v0.s[3], w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: sdiv4x32:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:    fmov w9, s1
; CHECK-GI-NEXT:    mov w10, v1.s[1]
; CHECK-GI-NEXT:    mov w11, v1.s[2]
; CHECK-GI-NEXT:    mov w12, v1.s[3]
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    mov w9, v0.s[1]
; CHECK-GI-NEXT:    sdiv w9, w9, w10
; CHECK-GI-NEXT:    mov w10, v0.s[2]
; CHECK-GI-NEXT:    sdiv w10, w10, w11
; CHECK-GI-NEXT:    mov w11, v0.s[3]
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    mov v0.s[1], w9
; CHECK-GI-NEXT:    sdiv w8, w11, w12
; CHECK-GI-NEXT:    mov v0.s[2], w10
; CHECK-GI-NEXT:    mov v0.s[3], w8
; CHECK-GI-NEXT:    ret
	%tmp3 = sdiv <4 x i32> %A, %B;
	ret <4 x i32> %tmp3
}

define <1 x i64> @sdiv1x64(<1 x i64> %A, <1 x i64> %B) {
; CHECK-SD-LABEL: sdiv1x64:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    fmov x8, d1
; CHECK-SD-NEXT:    fmov x9, d0
; CHECK-SD-NEXT:    sdiv x8, x9, x8
; CHECK-SD-NEXT:    fmov d0, x8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: sdiv1x64:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov x8, d0
; CHECK-GI-NEXT:    fmov x9, d1
; CHECK-GI-NEXT:    sdiv x8, x8, x9
; CHECK-GI-NEXT:    fmov d0, x8
; CHECK-GI-NEXT:    ret
	%tmp3 = sdiv <1 x i64> %A, %B;
	ret <1 x i64> %tmp3
}

define <2 x i64> @sdiv2x64(<2 x i64> %A, <2 x i64> %B) {
; CHECK-SD-LABEL: sdiv2x64:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    fmov x8, d1
; CHECK-SD-NEXT:    fmov x9, d0
; CHECK-SD-NEXT:    mov x10, v0.d[1]
; CHECK-SD-NEXT:    sdiv x8, x9, x8
; CHECK-SD-NEXT:    mov x9, v1.d[1]
; CHECK-SD-NEXT:    sdiv x9, x10, x9
; CHECK-SD-NEXT:    fmov d0, x8
; CHECK-SD-NEXT:    mov v0.d[1], x9
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: sdiv2x64:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov x8, d0
; CHECK-GI-NEXT:    fmov x9, d1
; CHECK-GI-NEXT:    mov x10, v1.d[1]
; CHECK-GI-NEXT:    sdiv x8, x8, x9
; CHECK-GI-NEXT:    mov x9, v0.d[1]
; CHECK-GI-NEXT:    sdiv x9, x9, x10
; CHECK-GI-NEXT:    fmov d0, x8
; CHECK-GI-NEXT:    mov v0.d[1], x9
; CHECK-GI-NEXT:    ret
	%tmp3 = sdiv <2 x i64> %A, %B;
	ret <2 x i64> %tmp3
}

define <1 x i8> @udiv1x8(<1 x i8> %A, <1 x i8> %B) {
; CHECK-SD-LABEL: udiv1x8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    umov w8, v1.b[0]
; CHECK-SD-NEXT:    umov w9, v0.b[0]
; CHECK-SD-NEXT:    udiv w8, w9, w8
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: udiv1x8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    umov w8, v0.b[0]
; CHECK-GI-NEXT:    umov w9, v1.b[0]
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    ret
	%tmp3 = udiv <1 x i8> %A, %B;
	ret <1 x i8> %tmp3
}

define <8 x i8> @udiv8x8(<8 x i8> %A, <8 x i8> %B) {
; CHECK-SD-LABEL: udiv8x8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    umov w8, v1.b[1]
; CHECK-SD-NEXT:    umov w9, v0.b[1]
; CHECK-SD-NEXT:    umov w10, v0.b[0]
; CHECK-SD-NEXT:    umov w11, v0.b[2]
; CHECK-SD-NEXT:    umov w12, v0.b[3]
; CHECK-SD-NEXT:    umov w13, v0.b[4]
; CHECK-SD-NEXT:    umov w14, v0.b[5]
; CHECK-SD-NEXT:    udiv w8, w9, w8
; CHECK-SD-NEXT:    umov w9, v1.b[0]
; CHECK-SD-NEXT:    udiv w9, w10, w9
; CHECK-SD-NEXT:    umov w10, v1.b[2]
; CHECK-SD-NEXT:    udiv w10, w11, w10
; CHECK-SD-NEXT:    umov w11, v1.b[3]
; CHECK-SD-NEXT:    fmov s2, w9
; CHECK-SD-NEXT:    umov w9, v1.b[6]
; CHECK-SD-NEXT:    mov v2.b[1], w8
; CHECK-SD-NEXT:    udiv w11, w12, w11
; CHECK-SD-NEXT:    umov w12, v1.b[4]
; CHECK-SD-NEXT:    mov v2.b[2], w10
; CHECK-SD-NEXT:    umov w10, v0.b[6]
; CHECK-SD-NEXT:    udiv w12, w13, w12
; CHECK-SD-NEXT:    umov w13, v1.b[5]
; CHECK-SD-NEXT:    mov v2.b[3], w11
; CHECK-SD-NEXT:    umov w11, v0.b[7]
; CHECK-SD-NEXT:    udiv w8, w14, w13
; CHECK-SD-NEXT:    mov v2.b[4], w12
; CHECK-SD-NEXT:    udiv w9, w10, w9
; CHECK-SD-NEXT:    umov w10, v1.b[7]
; CHECK-SD-NEXT:    mov v2.b[5], w8
; CHECK-SD-NEXT:    udiv w8, w11, w10
; CHECK-SD-NEXT:    mov v2.b[6], w9
; CHECK-SD-NEXT:    mov v2.b[7], w8
; CHECK-SD-NEXT:    fmov d0, d2
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: udiv8x8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    umov w8, v0.b[0]
; CHECK-GI-NEXT:    umov w9, v1.b[0]
; CHECK-GI-NEXT:    umov w10, v1.b[1]
; CHECK-GI-NEXT:    umov w11, v1.b[2]
; CHECK-GI-NEXT:    umov w12, v1.b[3]
; CHECK-GI-NEXT:    umov w13, v1.b[4]
; CHECK-GI-NEXT:    umov w14, v1.b[5]
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    umov w9, v0.b[1]
; CHECK-GI-NEXT:    udiv w9, w9, w10
; CHECK-GI-NEXT:    umov w10, v0.b[2]
; CHECK-GI-NEXT:    fmov s2, w8
; CHECK-GI-NEXT:    udiv w10, w10, w11
; CHECK-GI-NEXT:    umov w11, v0.b[3]
; CHECK-GI-NEXT:    mov v2.b[1], w9
; CHECK-GI-NEXT:    umov w9, v0.b[6]
; CHECK-GI-NEXT:    udiv w11, w11, w12
; CHECK-GI-NEXT:    umov w12, v0.b[4]
; CHECK-GI-NEXT:    mov v2.b[2], w10
; CHECK-GI-NEXT:    umov w10, v0.b[7]
; CHECK-GI-NEXT:    udiv w12, w12, w13
; CHECK-GI-NEXT:    umov w13, v0.b[5]
; CHECK-GI-NEXT:    mov v2.b[3], w11
; CHECK-GI-NEXT:    umov w11, v1.b[7]
; CHECK-GI-NEXT:    udiv w8, w13, w14
; CHECK-GI-NEXT:    umov w13, v1.b[6]
; CHECK-GI-NEXT:    mov v2.b[4], w12
; CHECK-GI-NEXT:    udiv w9, w9, w13
; CHECK-GI-NEXT:    mov v2.b[5], w8
; CHECK-GI-NEXT:    udiv w8, w10, w11
; CHECK-GI-NEXT:    mov v2.b[6], w9
; CHECK-GI-NEXT:    mov v2.b[7], w8
; CHECK-GI-NEXT:    fmov d0, d2
; CHECK-GI-NEXT:    ret
	%tmp3 = udiv <8 x i8> %A, %B;
	ret <8 x i8> %tmp3
}

define <16 x i8> @udiv16x8(<16 x i8> %A, <16 x i8> %B) {
; CHECK-SD-LABEL: udiv16x8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    umov w8, v1.b[1]
; CHECK-SD-NEXT:    umov w9, v0.b[1]
; CHECK-SD-NEXT:    umov w10, v0.b[0]
; CHECK-SD-NEXT:    umov w11, v0.b[2]
; CHECK-SD-NEXT:    umov w12, v0.b[3]
; CHECK-SD-NEXT:    umov w13, v0.b[4]
; CHECK-SD-NEXT:    umov w14, v0.b[5]
; CHECK-SD-NEXT:    umov w15, v0.b[6]
; CHECK-SD-NEXT:    umov w16, v0.b[7]
; CHECK-SD-NEXT:    umov w17, v0.b[8]
; CHECK-SD-NEXT:    umov w18, v0.b[9]
; CHECK-SD-NEXT:    udiv w8, w9, w8
; CHECK-SD-NEXT:    umov w9, v1.b[0]
; CHECK-SD-NEXT:    udiv w9, w10, w9
; CHECK-SD-NEXT:    umov w10, v1.b[2]
; CHECK-SD-NEXT:    udiv w10, w11, w10
; CHECK-SD-NEXT:    umov w11, v1.b[3]
; CHECK-SD-NEXT:    fmov s2, w9
; CHECK-SD-NEXT:    umov w9, v1.b[10]
; CHECK-SD-NEXT:    mov v2.b[1], w8
; CHECK-SD-NEXT:    udiv w11, w12, w11
; CHECK-SD-NEXT:    umov w12, v1.b[4]
; CHECK-SD-NEXT:    mov v2.b[2], w10
; CHECK-SD-NEXT:    umov w10, v0.b[10]
; CHECK-SD-NEXT:    udiv w12, w13, w12
; CHECK-SD-NEXT:    umov w13, v1.b[5]
; CHECK-SD-NEXT:    mov v2.b[3], w11
; CHECK-SD-NEXT:    umov w11, v0.b[11]
; CHECK-SD-NEXT:    udiv w13, w14, w13
; CHECK-SD-NEXT:    umov w14, v1.b[6]
; CHECK-SD-NEXT:    mov v2.b[4], w12
; CHECK-SD-NEXT:    umov w12, v0.b[12]
; CHECK-SD-NEXT:    udiv w14, w15, w14
; CHECK-SD-NEXT:    umov w15, v1.b[7]
; CHECK-SD-NEXT:    mov v2.b[5], w13
; CHECK-SD-NEXT:    umov w13, v0.b[13]
; CHECK-SD-NEXT:    udiv w15, w16, w15
; CHECK-SD-NEXT:    umov w16, v1.b[8]
; CHECK-SD-NEXT:    mov v2.b[6], w14
; CHECK-SD-NEXT:    udiv w16, w17, w16
; CHECK-SD-NEXT:    umov w17, v1.b[9]
; CHECK-SD-NEXT:    mov v2.b[7], w15
; CHECK-SD-NEXT:    udiv w8, w18, w17
; CHECK-SD-NEXT:    mov v2.b[8], w16
; CHECK-SD-NEXT:    udiv w9, w10, w9
; CHECK-SD-NEXT:    umov w10, v1.b[11]
; CHECK-SD-NEXT:    mov v2.b[9], w8
; CHECK-SD-NEXT:    udiv w10, w11, w10
; CHECK-SD-NEXT:    umov w11, v1.b[12]
; CHECK-SD-NEXT:    mov v2.b[10], w9
; CHECK-SD-NEXT:    umov w9, v1.b[14]
; CHECK-SD-NEXT:    udiv w11, w12, w11
; CHECK-SD-NEXT:    umov w12, v1.b[13]
; CHECK-SD-NEXT:    mov v2.b[11], w10
; CHECK-SD-NEXT:    umov w10, v1.b[15]
; CHECK-SD-NEXT:    udiv w8, w13, w12
; CHECK-SD-NEXT:    umov w12, v0.b[14]
; CHECK-SD-NEXT:    mov v2.b[12], w11
; CHECK-SD-NEXT:    umov w11, v0.b[15]
; CHECK-SD-NEXT:    udiv w9, w12, w9
; CHECK-SD-NEXT:    mov v2.b[13], w8
; CHECK-SD-NEXT:    udiv w8, w11, w10
; CHECK-SD-NEXT:    mov v2.b[14], w9
; CHECK-SD-NEXT:    mov v2.b[15], w8
; CHECK-SD-NEXT:    mov v0.16b, v2.16b
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: udiv16x8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    umov w8, v0.b[0]
; CHECK-GI-NEXT:    umov w9, v1.b[0]
; CHECK-GI-NEXT:    umov w10, v1.b[1]
; CHECK-GI-NEXT:    umov w11, v1.b[2]
; CHECK-GI-NEXT:    umov w12, v1.b[3]
; CHECK-GI-NEXT:    umov w13, v1.b[4]
; CHECK-GI-NEXT:    umov w14, v1.b[5]
; CHECK-GI-NEXT:    umov w15, v1.b[6]
; CHECK-GI-NEXT:    umov w16, v1.b[7]
; CHECK-GI-NEXT:    umov w17, v1.b[8]
; CHECK-GI-NEXT:    umov w18, v1.b[9]
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    umov w9, v0.b[1]
; CHECK-GI-NEXT:    udiv w9, w9, w10
; CHECK-GI-NEXT:    umov w10, v0.b[2]
; CHECK-GI-NEXT:    fmov s2, w8
; CHECK-GI-NEXT:    udiv w10, w10, w11
; CHECK-GI-NEXT:    umov w11, v0.b[3]
; CHECK-GI-NEXT:    mov v2.b[1], w9
; CHECK-GI-NEXT:    umov w9, v0.b[10]
; CHECK-GI-NEXT:    udiv w11, w11, w12
; CHECK-GI-NEXT:    umov w12, v0.b[4]
; CHECK-GI-NEXT:    mov v2.b[2], w10
; CHECK-GI-NEXT:    umov w10, v0.b[11]
; CHECK-GI-NEXT:    udiv w12, w12, w13
; CHECK-GI-NEXT:    umov w13, v0.b[5]
; CHECK-GI-NEXT:    mov v2.b[3], w11
; CHECK-GI-NEXT:    umov w11, v1.b[11]
; CHECK-GI-NEXT:    udiv w13, w13, w14
; CHECK-GI-NEXT:    umov w14, v0.b[6]
; CHECK-GI-NEXT:    mov v2.b[4], w12
; CHECK-GI-NEXT:    umov w12, v1.b[12]
; CHECK-GI-NEXT:    udiv w14, w14, w15
; CHECK-GI-NEXT:    umov w15, v0.b[7]
; CHECK-GI-NEXT:    mov v2.b[5], w13
; CHECK-GI-NEXT:    umov w13, v1.b[13]
; CHECK-GI-NEXT:    udiv w15, w15, w16
; CHECK-GI-NEXT:    umov w16, v0.b[8]
; CHECK-GI-NEXT:    mov v2.b[6], w14
; CHECK-GI-NEXT:    udiv w16, w16, w17
; CHECK-GI-NEXT:    umov w17, v0.b[9]
; CHECK-GI-NEXT:    mov v2.b[7], w15
; CHECK-GI-NEXT:    udiv w8, w17, w18
; CHECK-GI-NEXT:    umov w17, v1.b[10]
; CHECK-GI-NEXT:    mov v2.b[8], w16
; CHECK-GI-NEXT:    udiv w9, w9, w17
; CHECK-GI-NEXT:    mov v2.b[9], w8
; CHECK-GI-NEXT:    umov w8, v0.b[14]
; CHECK-GI-NEXT:    udiv w10, w10, w11
; CHECK-GI-NEXT:    umov w11, v0.b[12]
; CHECK-GI-NEXT:    mov v2.b[10], w9
; CHECK-GI-NEXT:    umov w9, v0.b[15]
; CHECK-GI-NEXT:    udiv w11, w11, w12
; CHECK-GI-NEXT:    umov w12, v0.b[13]
; CHECK-GI-NEXT:    mov v2.b[11], w10
; CHECK-GI-NEXT:    umov w10, v1.b[15]
; CHECK-GI-NEXT:    udiv w12, w12, w13
; CHECK-GI-NEXT:    umov w13, v1.b[14]
; CHECK-GI-NEXT:    mov v2.b[12], w11
; CHECK-GI-NEXT:    udiv w8, w8, w13
; CHECK-GI-NEXT:    mov v2.b[13], w12
; CHECK-GI-NEXT:    udiv w9, w9, w10
; CHECK-GI-NEXT:    mov v2.b[14], w8
; CHECK-GI-NEXT:    mov v2.b[15], w9
; CHECK-GI-NEXT:    mov v0.16b, v2.16b
; CHECK-GI-NEXT:    ret
	%tmp3 = udiv <16 x i8> %A, %B;
	ret <16 x i8> %tmp3
}

define <1 x i16> @udiv1x16(<1 x i16> %A, <1 x i16> %B) {
; CHECK-SD-LABEL: udiv1x16:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    umov w8, v1.h[0]
; CHECK-SD-NEXT:    umov w9, v0.h[0]
; CHECK-SD-NEXT:    udiv w8, w9, w8
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: udiv1x16:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    umov w8, v0.h[0]
; CHECK-GI-NEXT:    umov w9, v1.h[0]
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    ret
	%tmp3 = udiv <1 x i16> %A, %B;
	ret <1 x i16> %tmp3
}

define <4 x i16> @udiv4x16(<4 x i16> %A, <4 x i16> %B) {
; CHECK-SD-LABEL: udiv4x16:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    umov w8, v1.h[1]
; CHECK-SD-NEXT:    umov w9, v0.h[1]
; CHECK-SD-NEXT:    umov w10, v0.h[0]
; CHECK-SD-NEXT:    umov w11, v0.h[2]
; CHECK-SD-NEXT:    umov w12, v0.h[3]
; CHECK-SD-NEXT:    udiv w8, w9, w8
; CHECK-SD-NEXT:    umov w9, v1.h[0]
; CHECK-SD-NEXT:    udiv w9, w10, w9
; CHECK-SD-NEXT:    umov w10, v1.h[2]
; CHECK-SD-NEXT:    udiv w10, w11, w10
; CHECK-SD-NEXT:    umov w11, v1.h[3]
; CHECK-SD-NEXT:    fmov s0, w9
; CHECK-SD-NEXT:    mov v0.h[1], w8
; CHECK-SD-NEXT:    udiv w8, w12, w11
; CHECK-SD-NEXT:    mov v0.h[2], w10
; CHECK-SD-NEXT:    mov v0.h[3], w8
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: udiv4x16:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    umov w8, v0.h[0]
; CHECK-GI-NEXT:    umov w9, v1.h[0]
; CHECK-GI-NEXT:    umov w10, v1.h[1]
; CHECK-GI-NEXT:    umov w11, v1.h[2]
; CHECK-GI-NEXT:    umov w12, v1.h[3]
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    umov w9, v0.h[1]
; CHECK-GI-NEXT:    udiv w9, w9, w10
; CHECK-GI-NEXT:    umov w10, v0.h[2]
; CHECK-GI-NEXT:    udiv w10, w10, w11
; CHECK-GI-NEXT:    umov w11, v0.h[3]
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    mov v0.h[1], w9
; CHECK-GI-NEXT:    udiv w8, w11, w12
; CHECK-GI-NEXT:    mov v0.h[2], w10
; CHECK-GI-NEXT:    mov v0.h[3], w8
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-GI-NEXT:    ret
	%tmp3 = udiv <4 x i16> %A, %B;
	ret <4 x i16> %tmp3
}

define <8 x i16> @udiv8x16(<8 x i16> %A, <8 x i16> %B) {
; CHECK-SD-LABEL: udiv8x16:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    umov w8, v1.h[1]
; CHECK-SD-NEXT:    umov w9, v0.h[1]
; CHECK-SD-NEXT:    umov w10, v0.h[0]
; CHECK-SD-NEXT:    umov w11, v0.h[2]
; CHECK-SD-NEXT:    umov w12, v0.h[3]
; CHECK-SD-NEXT:    umov w13, v0.h[4]
; CHECK-SD-NEXT:    umov w14, v0.h[5]
; CHECK-SD-NEXT:    udiv w8, w9, w8
; CHECK-SD-NEXT:    umov w9, v1.h[0]
; CHECK-SD-NEXT:    udiv w9, w10, w9
; CHECK-SD-NEXT:    umov w10, v1.h[2]
; CHECK-SD-NEXT:    udiv w10, w11, w10
; CHECK-SD-NEXT:    umov w11, v1.h[3]
; CHECK-SD-NEXT:    fmov s2, w9
; CHECK-SD-NEXT:    umov w9, v1.h[6]
; CHECK-SD-NEXT:    mov v2.h[1], w8
; CHECK-SD-NEXT:    udiv w11, w12, w11
; CHECK-SD-NEXT:    umov w12, v1.h[4]
; CHECK-SD-NEXT:    mov v2.h[2], w10
; CHECK-SD-NEXT:    umov w10, v0.h[6]
; CHECK-SD-NEXT:    udiv w12, w13, w12
; CHECK-SD-NEXT:    umov w13, v1.h[5]
; CHECK-SD-NEXT:    mov v2.h[3], w11
; CHECK-SD-NEXT:    umov w11, v0.h[7]
; CHECK-SD-NEXT:    udiv w8, w14, w13
; CHECK-SD-NEXT:    mov v2.h[4], w12
; CHECK-SD-NEXT:    udiv w9, w10, w9
; CHECK-SD-NEXT:    umov w10, v1.h[7]
; CHECK-SD-NEXT:    mov v2.h[5], w8
; CHECK-SD-NEXT:    udiv w8, w11, w10
; CHECK-SD-NEXT:    mov v2.h[6], w9
; CHECK-SD-NEXT:    mov v2.h[7], w8
; CHECK-SD-NEXT:    mov v0.16b, v2.16b
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: udiv8x16:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    umov w8, v0.h[0]
; CHECK-GI-NEXT:    umov w9, v1.h[0]
; CHECK-GI-NEXT:    umov w10, v1.h[1]
; CHECK-GI-NEXT:    umov w11, v1.h[2]
; CHECK-GI-NEXT:    umov w12, v1.h[3]
; CHECK-GI-NEXT:    umov w13, v1.h[4]
; CHECK-GI-NEXT:    umov w14, v1.h[5]
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    umov w9, v0.h[1]
; CHECK-GI-NEXT:    udiv w9, w9, w10
; CHECK-GI-NEXT:    umov w10, v0.h[2]
; CHECK-GI-NEXT:    fmov s2, w8
; CHECK-GI-NEXT:    udiv w10, w10, w11
; CHECK-GI-NEXT:    umov w11, v0.h[3]
; CHECK-GI-NEXT:    mov v2.h[1], w9
; CHECK-GI-NEXT:    umov w9, v0.h[6]
; CHECK-GI-NEXT:    udiv w11, w11, w12
; CHECK-GI-NEXT:    umov w12, v0.h[4]
; CHECK-GI-NEXT:    mov v2.h[2], w10
; CHECK-GI-NEXT:    umov w10, v0.h[7]
; CHECK-GI-NEXT:    udiv w12, w12, w13
; CHECK-GI-NEXT:    umov w13, v0.h[5]
; CHECK-GI-NEXT:    mov v2.h[3], w11
; CHECK-GI-NEXT:    umov w11, v1.h[7]
; CHECK-GI-NEXT:    udiv w8, w13, w14
; CHECK-GI-NEXT:    umov w13, v1.h[6]
; CHECK-GI-NEXT:    mov v2.h[4], w12
; CHECK-GI-NEXT:    udiv w9, w9, w13
; CHECK-GI-NEXT:    mov v2.h[5], w8
; CHECK-GI-NEXT:    udiv w8, w10, w11
; CHECK-GI-NEXT:    mov v2.h[6], w9
; CHECK-GI-NEXT:    mov v2.h[7], w8
; CHECK-GI-NEXT:    mov v0.16b, v2.16b
; CHECK-GI-NEXT:    ret
	%tmp3 = udiv <8 x i16> %A, %B;
	ret <8 x i16> %tmp3
}

define <1 x i32> @udiv1x32(<1 x i32> %A, <1 x i32> %B) {
; CHECK-SD-LABEL: udiv1x32:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    fmov w8, s1
; CHECK-SD-NEXT:    fmov w9, s0
; CHECK-SD-NEXT:    udiv w8, w9, w8
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: udiv1x32:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:    fmov w9, s1
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    ret
	%tmp3 = udiv <1 x i32> %A, %B;
	ret <1 x i32> %tmp3
}

define <2 x i32> @udiv2x32(<2 x i32> %A, <2 x i32> %B) {
; CHECK-SD-LABEL: udiv2x32:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    fmov w8, s1
; CHECK-SD-NEXT:    fmov w9, s0
; CHECK-SD-NEXT:    mov w10, v0.s[1]
; CHECK-SD-NEXT:    udiv w8, w9, w8
; CHECK-SD-NEXT:    mov w9, v1.s[1]
; CHECK-SD-NEXT:    udiv w9, w10, w9
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    mov v0.s[1], w9
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: udiv2x32:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:    fmov w9, s1
; CHECK-GI-NEXT:    mov w10, v1.s[1]
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    mov w9, v0.s[1]
; CHECK-GI-NEXT:    udiv w9, w9, w10
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    mov v0.s[1], w9
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-GI-NEXT:    ret
	%tmp3 = udiv <2 x i32> %A, %B;
	ret <2 x i32> %tmp3
}

define <4 x i32> @udiv4x32(<4 x i32> %A, <4 x i32> %B) {
; CHECK-SD-LABEL: udiv4x32:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    mov w8, v1.s[1]
; CHECK-SD-NEXT:    mov w9, v0.s[1]
; CHECK-SD-NEXT:    fmov w10, s0
; CHECK-SD-NEXT:    mov w11, v0.s[2]
; CHECK-SD-NEXT:    mov w12, v0.s[3]
; CHECK-SD-NEXT:    udiv w8, w9, w8
; CHECK-SD-NEXT:    fmov w9, s1
; CHECK-SD-NEXT:    udiv w9, w10, w9
; CHECK-SD-NEXT:    mov w10, v1.s[2]
; CHECK-SD-NEXT:    udiv w10, w11, w10
; CHECK-SD-NEXT:    mov w11, v1.s[3]
; CHECK-SD-NEXT:    fmov s0, w9
; CHECK-SD-NEXT:    mov v0.s[1], w8
; CHECK-SD-NEXT:    udiv w8, w12, w11
; CHECK-SD-NEXT:    mov v0.s[2], w10
; CHECK-SD-NEXT:    mov v0.s[3], w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: udiv4x32:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:    fmov w9, s1
; CHECK-GI-NEXT:    mov w10, v1.s[1]
; CHECK-GI-NEXT:    mov w11, v1.s[2]
; CHECK-GI-NEXT:    mov w12, v1.s[3]
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    mov w9, v0.s[1]
; CHECK-GI-NEXT:    udiv w9, w9, w10
; CHECK-GI-NEXT:    mov w10, v0.s[2]
; CHECK-GI-NEXT:    udiv w10, w10, w11
; CHECK-GI-NEXT:    mov w11, v0.s[3]
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    mov v0.s[1], w9
; CHECK-GI-NEXT:    udiv w8, w11, w12
; CHECK-GI-NEXT:    mov v0.s[2], w10
; CHECK-GI-NEXT:    mov v0.s[3], w8
; CHECK-GI-NEXT:    ret
	%tmp3 = udiv <4 x i32> %A, %B;
	ret <4 x i32> %tmp3
}

define <1 x i64> @udiv1x64(<1 x i64> %A, <1 x i64> %B) {
; CHECK-SD-LABEL: udiv1x64:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    fmov x8, d1
; CHECK-SD-NEXT:    fmov x9, d0
; CHECK-SD-NEXT:    udiv x8, x9, x8
; CHECK-SD-NEXT:    fmov d0, x8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: udiv1x64:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov x8, d0
; CHECK-GI-NEXT:    fmov x9, d1
; CHECK-GI-NEXT:    udiv x8, x8, x9
; CHECK-GI-NEXT:    fmov d0, x8
; CHECK-GI-NEXT:    ret
	%tmp3 = udiv <1 x i64> %A, %B;
	ret <1 x i64> %tmp3
}

define <2 x i64> @udiv2x64(<2 x i64> %A, <2 x i64> %B) {
; CHECK-SD-LABEL: udiv2x64:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    fmov x8, d1
; CHECK-SD-NEXT:    fmov x9, d0
; CHECK-SD-NEXT:    mov x10, v0.d[1]
; CHECK-SD-NEXT:    udiv x8, x9, x8
; CHECK-SD-NEXT:    mov x9, v1.d[1]
; CHECK-SD-NEXT:    udiv x9, x10, x9
; CHECK-SD-NEXT:    fmov d0, x8
; CHECK-SD-NEXT:    mov v0.d[1], x9
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: udiv2x64:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov x8, d0
; CHECK-GI-NEXT:    fmov x9, d1
; CHECK-GI-NEXT:    mov x10, v1.d[1]
; CHECK-GI-NEXT:    udiv x8, x8, x9
; CHECK-GI-NEXT:    mov x9, v0.d[1]
; CHECK-GI-NEXT:    udiv x9, x9, x10
; CHECK-GI-NEXT:    fmov d0, x8
; CHECK-GI-NEXT:    mov v0.d[1], x9
; CHECK-GI-NEXT:    ret
	%tmp3 = udiv <2 x i64> %A, %B;
	ret <2 x i64> %tmp3
}

define <1 x i8> @srem1x8(<1 x i8> %A, <1 x i8> %B) {
; CHECK-SD-LABEL: srem1x8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    smov w8, v1.b[0]
; CHECK-SD-NEXT:    smov w9, v0.b[0]
; CHECK-SD-NEXT:    sdiv w10, w9, w8
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: srem1x8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    smov w8, v0.b[0]
; CHECK-GI-NEXT:    smov w9, v1.b[0]
; CHECK-GI-NEXT:    umov w10, v0.b[0]
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    umov w9, v1.b[0]
; CHECK-GI-NEXT:    msub w8, w8, w9, w10
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    ret
	%tmp3 = srem <1 x i8> %A, %B;
	ret <1 x i8> %tmp3
}

define <8 x i8> @srem8x8(<8 x i8> %A, <8 x i8> %B) {
; CHECK-SD-LABEL: srem8x8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    smov w11, v1.b[0]
; CHECK-SD-NEXT:    smov w12, v0.b[0]
; CHECK-SD-NEXT:    smov w8, v1.b[1]
; CHECK-SD-NEXT:    smov w9, v0.b[1]
; CHECK-SD-NEXT:    smov w14, v1.b[2]
; CHECK-SD-NEXT:    smov w15, v0.b[2]
; CHECK-SD-NEXT:    smov w17, v1.b[3]
; CHECK-SD-NEXT:    smov w18, v0.b[3]
; CHECK-SD-NEXT:    smov w1, v1.b[4]
; CHECK-SD-NEXT:    smov w2, v0.b[4]
; CHECK-SD-NEXT:    smov w4, v1.b[5]
; CHECK-SD-NEXT:    smov w5, v0.b[5]
; CHECK-SD-NEXT:    sdiv w13, w12, w11
; CHECK-SD-NEXT:    sdiv w10, w9, w8
; CHECK-SD-NEXT:    msub w11, w13, w11, w12
; CHECK-SD-NEXT:    smov w13, v1.b[7]
; CHECK-SD-NEXT:    fmov s2, w11
; CHECK-SD-NEXT:    smov w11, v0.b[6]
; CHECK-SD-NEXT:    sdiv w16, w15, w14
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    smov w10, v1.b[6]
; CHECK-SD-NEXT:    mov v2.b[1], w8
; CHECK-SD-NEXT:    sdiv w0, w18, w17
; CHECK-SD-NEXT:    msub w8, w16, w14, w15
; CHECK-SD-NEXT:    smov w14, v0.b[7]
; CHECK-SD-NEXT:    mov v2.b[2], w8
; CHECK-SD-NEXT:    sdiv w3, w2, w1
; CHECK-SD-NEXT:    msub w8, w0, w17, w18
; CHECK-SD-NEXT:    mov v2.b[3], w8
; CHECK-SD-NEXT:    sdiv w9, w5, w4
; CHECK-SD-NEXT:    msub w8, w3, w1, w2
; CHECK-SD-NEXT:    mov v2.b[4], w8
; CHECK-SD-NEXT:    sdiv w12, w11, w10
; CHECK-SD-NEXT:    msub w8, w9, w4, w5
; CHECK-SD-NEXT:    mov v2.b[5], w8
; CHECK-SD-NEXT:    sdiv w9, w14, w13
; CHECK-SD-NEXT:    msub w8, w12, w10, w11
; CHECK-SD-NEXT:    mov v2.b[6], w8
; CHECK-SD-NEXT:    msub w8, w9, w13, w14
; CHECK-SD-NEXT:    mov v2.b[7], w8
; CHECK-SD-NEXT:    fmov d0, d2
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: srem8x8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-GI-NEXT:    sshll v1.8h, v1.8b, #0
; CHECK-GI-NEXT:    sshll v2.4s, v0.4h, #0
; CHECK-GI-NEXT:    sshll v3.4s, v1.4h, #0
; CHECK-GI-NEXT:    sshll2 v0.4s, v0.8h, #0
; CHECK-GI-NEXT:    sshll2 v1.4s, v1.8h, #0
; CHECK-GI-NEXT:    fmov w8, s2
; CHECK-GI-NEXT:    fmov w9, s3
; CHECK-GI-NEXT:    mov w10, v3.s[1]
; CHECK-GI-NEXT:    mov w11, v3.s[2]
; CHECK-GI-NEXT:    mov w12, v3.s[3]
; CHECK-GI-NEXT:    fmov w13, s1
; CHECK-GI-NEXT:    mov w14, v1.s[1]
; CHECK-GI-NEXT:    mov w15, v1.s[2]
; CHECK-GI-NEXT:    mov w16, v1.s[3]
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    mov w9, v2.s[1]
; CHECK-GI-NEXT:    sdiv w9, w9, w10
; CHECK-GI-NEXT:    mov w10, v2.s[2]
; CHECK-GI-NEXT:    fmov s4, w8
; CHECK-GI-NEXT:    sdiv w10, w10, w11
; CHECK-GI-NEXT:    mov w11, v2.s[3]
; CHECK-GI-NEXT:    mov v4.s[1], w9
; CHECK-GI-NEXT:    sdiv w11, w11, w12
; CHECK-GI-NEXT:    fmov w12, s0
; CHECK-GI-NEXT:    mov v4.s[2], w10
; CHECK-GI-NEXT:    sdiv w12, w12, w13
; CHECK-GI-NEXT:    mov w13, v0.s[1]
; CHECK-GI-NEXT:    mov v4.s[3], w11
; CHECK-GI-NEXT:    mls v2.4s, v4.4s, v3.4s
; CHECK-GI-NEXT:    sdiv w13, w13, w14
; CHECK-GI-NEXT:    mov w14, v0.s[2]
; CHECK-GI-NEXT:    fmov s5, w12
; CHECK-GI-NEXT:    sdiv w14, w14, w15
; CHECK-GI-NEXT:    mov w15, v0.s[3]
; CHECK-GI-NEXT:    mov v5.s[1], w13
; CHECK-GI-NEXT:    sdiv w8, w15, w16
; CHECK-GI-NEXT:    mov v5.s[2], w14
; CHECK-GI-NEXT:    mov v5.s[3], w8
; CHECK-GI-NEXT:    mls v0.4s, v5.4s, v1.4s
; CHECK-GI-NEXT:    uzp1 v0.8h, v2.8h, v0.8h
; CHECK-GI-NEXT:    xtn v0.8b, v0.8h
; CHECK-GI-NEXT:    ret
	%tmp3 = srem <8 x i8> %A, %B;
	ret <8 x i8> %tmp3
}

define <16 x i8> @srem16x8(<16 x i8> %A, <16 x i8> %B) {
; CHECK-SD-LABEL: srem16x8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    stp x28, x27, [sp, #-80]! // 16-byte Folded Spill
; CHECK-SD-NEXT:    stp x26, x25, [sp, #16] // 16-byte Folded Spill
; CHECK-SD-NEXT:    stp x24, x23, [sp, #32] // 16-byte Folded Spill
; CHECK-SD-NEXT:    stp x22, x21, [sp, #48] // 16-byte Folded Spill
; CHECK-SD-NEXT:    stp x20, x19, [sp, #64] // 16-byte Folded Spill
; CHECK-SD-NEXT:    .cfi_def_cfa_offset 80
; CHECK-SD-NEXT:    .cfi_offset w19, -8
; CHECK-SD-NEXT:    .cfi_offset w20, -16
; CHECK-SD-NEXT:    .cfi_offset w21, -24
; CHECK-SD-NEXT:    .cfi_offset w22, -32
; CHECK-SD-NEXT:    .cfi_offset w23, -40
; CHECK-SD-NEXT:    .cfi_offset w24, -48
; CHECK-SD-NEXT:    .cfi_offset w25, -56
; CHECK-SD-NEXT:    .cfi_offset w26, -64
; CHECK-SD-NEXT:    .cfi_offset w27, -72
; CHECK-SD-NEXT:    .cfi_offset w28, -80
; CHECK-SD-NEXT:    smov w11, v1.b[0]
; CHECK-SD-NEXT:    smov w12, v0.b[0]
; CHECK-SD-NEXT:    smov w8, v1.b[1]
; CHECK-SD-NEXT:    smov w9, v0.b[1]
; CHECK-SD-NEXT:    smov w14, v1.b[2]
; CHECK-SD-NEXT:    smov w15, v0.b[2]
; CHECK-SD-NEXT:    smov w17, v1.b[3]
; CHECK-SD-NEXT:    smov w18, v0.b[3]
; CHECK-SD-NEXT:    smov w1, v1.b[4]
; CHECK-SD-NEXT:    smov w2, v0.b[4]
; CHECK-SD-NEXT:    smov w4, v1.b[5]
; CHECK-SD-NEXT:    smov w5, v0.b[5]
; CHECK-SD-NEXT:    sdiv w13, w12, w11
; CHECK-SD-NEXT:    smov w7, v1.b[6]
; CHECK-SD-NEXT:    smov w19, v0.b[6]
; CHECK-SD-NEXT:    smov w21, v1.b[7]
; CHECK-SD-NEXT:    smov w22, v0.b[7]
; CHECK-SD-NEXT:    smov w24, v1.b[8]
; CHECK-SD-NEXT:    smov w25, v0.b[8]
; CHECK-SD-NEXT:    smov w27, v1.b[9]
; CHECK-SD-NEXT:    smov w28, v0.b[9]
; CHECK-SD-NEXT:    sdiv w10, w9, w8
; CHECK-SD-NEXT:    msub w11, w13, w11, w12
; CHECK-SD-NEXT:    smov w13, v1.b[11]
; CHECK-SD-NEXT:    fmov s2, w11
; CHECK-SD-NEXT:    smov w11, v0.b[10]
; CHECK-SD-NEXT:    sdiv w16, w15, w14
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    smov w10, v1.b[10]
; CHECK-SD-NEXT:    mov v2.b[1], w8
; CHECK-SD-NEXT:    sdiv w0, w18, w17
; CHECK-SD-NEXT:    msub w8, w16, w14, w15
; CHECK-SD-NEXT:    smov w14, v0.b[11]
; CHECK-SD-NEXT:    smov w16, v1.b[12]
; CHECK-SD-NEXT:    mov v2.b[2], w8
; CHECK-SD-NEXT:    sdiv w3, w2, w1
; CHECK-SD-NEXT:    msub w8, w0, w17, w18
; CHECK-SD-NEXT:    smov w17, v0.b[12]
; CHECK-SD-NEXT:    smov w0, v1.b[13]
; CHECK-SD-NEXT:    mov v2.b[3], w8
; CHECK-SD-NEXT:    sdiv w6, w5, w4
; CHECK-SD-NEXT:    msub w8, w3, w1, w2
; CHECK-SD-NEXT:    smov w1, v0.b[13]
; CHECK-SD-NEXT:    mov v2.b[4], w8
; CHECK-SD-NEXT:    sdiv w20, w19, w7
; CHECK-SD-NEXT:    msub w8, w6, w4, w5
; CHECK-SD-NEXT:    mov v2.b[5], w8
; CHECK-SD-NEXT:    sdiv w23, w22, w21
; CHECK-SD-NEXT:    msub w8, w20, w7, w19
; CHECK-SD-NEXT:    ldp x20, x19, [sp, #64] // 16-byte Folded Reload
; CHECK-SD-NEXT:    mov v2.b[6], w8
; CHECK-SD-NEXT:    sdiv w26, w25, w24
; CHECK-SD-NEXT:    msub w8, w23, w21, w22
; CHECK-SD-NEXT:    ldp x22, x21, [sp, #48] // 16-byte Folded Reload
; CHECK-SD-NEXT:    mov v2.b[7], w8
; CHECK-SD-NEXT:    sdiv w9, w28, w27
; CHECK-SD-NEXT:    msub w8, w26, w24, w25
; CHECK-SD-NEXT:    ldp x24, x23, [sp, #32] // 16-byte Folded Reload
; CHECK-SD-NEXT:    ldp x26, x25, [sp, #16] // 16-byte Folded Reload
; CHECK-SD-NEXT:    mov v2.b[8], w8
; CHECK-SD-NEXT:    sdiv w12, w11, w10
; CHECK-SD-NEXT:    msub w8, w9, w27, w28
; CHECK-SD-NEXT:    mov v2.b[9], w8
; CHECK-SD-NEXT:    sdiv w15, w14, w13
; CHECK-SD-NEXT:    msub w8, w12, w10, w11
; CHECK-SD-NEXT:    smov w10, v1.b[14]
; CHECK-SD-NEXT:    smov w11, v0.b[14]
; CHECK-SD-NEXT:    mov v2.b[10], w8
; CHECK-SD-NEXT:    sdiv w18, w17, w16
; CHECK-SD-NEXT:    msub w8, w15, w13, w14
; CHECK-SD-NEXT:    smov w13, v1.b[15]
; CHECK-SD-NEXT:    smov w14, v0.b[15]
; CHECK-SD-NEXT:    mov v2.b[11], w8
; CHECK-SD-NEXT:    sdiv w9, w1, w0
; CHECK-SD-NEXT:    msub w8, w18, w16, w17
; CHECK-SD-NEXT:    mov v2.b[12], w8
; CHECK-SD-NEXT:    sdiv w12, w11, w10
; CHECK-SD-NEXT:    msub w8, w9, w0, w1
; CHECK-SD-NEXT:    mov v2.b[13], w8
; CHECK-SD-NEXT:    sdiv w9, w14, w13
; CHECK-SD-NEXT:    msub w8, w12, w10, w11
; CHECK-SD-NEXT:    mov v2.b[14], w8
; CHECK-SD-NEXT:    msub w8, w9, w13, w14
; CHECK-SD-NEXT:    mov v2.b[15], w8
; CHECK-SD-NEXT:    mov v0.16b, v2.16b
; CHECK-SD-NEXT:    ldp x28, x27, [sp], #80 // 16-byte Folded Reload
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: srem16x8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    sshll v4.8h, v0.8b, #0
; CHECK-GI-NEXT:    sshll v5.8h, v1.8b, #0
; CHECK-GI-NEXT:    sshll2 v6.8h, v0.16b, #0
; CHECK-GI-NEXT:    sshll2 v7.8h, v1.16b, #0
; CHECK-GI-NEXT:    sshll v2.4s, v4.4h, #0
; CHECK-GI-NEXT:    sshll v3.4s, v5.4h, #0
; CHECK-GI-NEXT:    sshll2 v4.4s, v4.8h, #0
; CHECK-GI-NEXT:    sshll2 v5.4s, v5.8h, #0
; CHECK-GI-NEXT:    sshll v0.4s, v6.4h, #0
; CHECK-GI-NEXT:    sshll v1.4s, v7.4h, #0
; CHECK-GI-NEXT:    sshll2 v6.4s, v6.8h, #0
; CHECK-GI-NEXT:    sshll2 v7.4s, v7.8h, #0
; CHECK-GI-NEXT:    fmov w8, s2
; CHECK-GI-NEXT:    fmov w9, s3
; CHECK-GI-NEXT:    mov w12, v3.s[3]
; CHECK-GI-NEXT:    fmov w13, s5
; CHECK-GI-NEXT:    mov w16, v5.s[3]
; CHECK-GI-NEXT:    fmov w17, s1
; CHECK-GI-NEXT:    mov w18, v1.s[1]
; CHECK-GI-NEXT:    mov w0, v1.s[2]
; CHECK-GI-NEXT:    mov w1, v1.s[3]
; CHECK-GI-NEXT:    sdiv w10, w8, w9
; CHECK-GI-NEXT:    mov w8, v2.s[1]
; CHECK-GI-NEXT:    mov w9, v3.s[1]
; CHECK-GI-NEXT:    fmov w2, s7
; CHECK-GI-NEXT:    mov w3, v7.s[1]
; CHECK-GI-NEXT:    mov w4, v7.s[2]
; CHECK-GI-NEXT:    mov w5, v7.s[3]
; CHECK-GI-NEXT:    sdiv w11, w8, w9
; CHECK-GI-NEXT:    mov w8, v2.s[2]
; CHECK-GI-NEXT:    mov w9, v3.s[2]
; CHECK-GI-NEXT:    fmov s16, w10
; CHECK-GI-NEXT:    sdiv w9, w8, w9
; CHECK-GI-NEXT:    mov w8, v2.s[3]
; CHECK-GI-NEXT:    mov v16.s[1], w11
; CHECK-GI-NEXT:    sdiv w8, w8, w12
; CHECK-GI-NEXT:    fmov w12, s4
; CHECK-GI-NEXT:    mov v16.s[2], w9
; CHECK-GI-NEXT:    sdiv w14, w12, w13
; CHECK-GI-NEXT:    mov w12, v4.s[1]
; CHECK-GI-NEXT:    mov w13, v5.s[1]
; CHECK-GI-NEXT:    mov v16.s[3], w8
; CHECK-GI-NEXT:    mls v2.4s, v16.4s, v3.4s
; CHECK-GI-NEXT:    sdiv w15, w12, w13
; CHECK-GI-NEXT:    mov w12, v4.s[2]
; CHECK-GI-NEXT:    mov w13, v5.s[2]
; CHECK-GI-NEXT:    fmov s17, w14
; CHECK-GI-NEXT:    sdiv w13, w12, w13
; CHECK-GI-NEXT:    mov w12, v4.s[3]
; CHECK-GI-NEXT:    mov v17.s[1], w15
; CHECK-GI-NEXT:    sdiv w12, w12, w16
; CHECK-GI-NEXT:    fmov w16, s0
; CHECK-GI-NEXT:    mov v17.s[2], w13
; CHECK-GI-NEXT:    sdiv w16, w16, w17
; CHECK-GI-NEXT:    mov w17, v0.s[1]
; CHECK-GI-NEXT:    mov v17.s[3], w12
; CHECK-GI-NEXT:    mls v4.4s, v17.4s, v5.4s
; CHECK-GI-NEXT:    sdiv w17, w17, w18
; CHECK-GI-NEXT:    mov w18, v0.s[2]
; CHECK-GI-NEXT:    fmov s18, w16
; CHECK-GI-NEXT:    sdiv w18, w18, w0
; CHECK-GI-NEXT:    mov w0, v0.s[3]
; CHECK-GI-NEXT:    mov v18.s[1], w17
; CHECK-GI-NEXT:    sdiv w0, w0, w1
; CHECK-GI-NEXT:    fmov w1, s6
; CHECK-GI-NEXT:    mov v18.s[2], w18
; CHECK-GI-NEXT:    sdiv w1, w1, w2
; CHECK-GI-NEXT:    mov w2, v6.s[1]
; CHECK-GI-NEXT:    mov v18.s[3], w0
; CHECK-GI-NEXT:    mls v0.4s, v18.4s, v1.4s
; CHECK-GI-NEXT:    uzp1 v1.8h, v2.8h, v4.8h
; CHECK-GI-NEXT:    sdiv w2, w2, w3
; CHECK-GI-NEXT:    mov w3, v6.s[2]
; CHECK-GI-NEXT:    fmov s19, w1
; CHECK-GI-NEXT:    sdiv w3, w3, w4
; CHECK-GI-NEXT:    mov w4, v6.s[3]
; CHECK-GI-NEXT:    mov v19.s[1], w2
; CHECK-GI-NEXT:    sdiv w10, w4, w5
; CHECK-GI-NEXT:    mov v19.s[2], w3
; CHECK-GI-NEXT:    mov v19.s[3], w10
; CHECK-GI-NEXT:    mls v6.4s, v19.4s, v7.4s
; CHECK-GI-NEXT:    uzp1 v0.8h, v0.8h, v6.8h
; CHECK-GI-NEXT:    uzp1 v0.16b, v1.16b, v0.16b
; CHECK-GI-NEXT:    ret
	%tmp3 = srem <16 x i8> %A, %B;
	ret <16 x i8> %tmp3
}

define <1 x i16> @srem1x16(<1 x i16> %A, <1 x i16> %B) {
; CHECK-SD-LABEL: srem1x16:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    smov w8, v1.h[0]
; CHECK-SD-NEXT:    smov w9, v0.h[0]
; CHECK-SD-NEXT:    sdiv w10, w9, w8
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: srem1x16:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    smov w8, v0.h[0]
; CHECK-GI-NEXT:    smov w9, v1.h[0]
; CHECK-GI-NEXT:    umov w10, v0.h[0]
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    umov w9, v1.h[0]
; CHECK-GI-NEXT:    msub w8, w8, w9, w10
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    ret
	%tmp3 = srem <1 x i16> %A, %B;
	ret <1 x i16> %tmp3
}

define <4 x i16> @srem4x16(<4 x i16> %A, <4 x i16> %B) {
; CHECK-SD-LABEL: srem4x16:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    smov w11, v1.h[0]
; CHECK-SD-NEXT:    smov w12, v0.h[0]
; CHECK-SD-NEXT:    smov w8, v1.h[1]
; CHECK-SD-NEXT:    smov w9, v0.h[1]
; CHECK-SD-NEXT:    smov w14, v1.h[2]
; CHECK-SD-NEXT:    smov w15, v0.h[2]
; CHECK-SD-NEXT:    smov w17, v1.h[3]
; CHECK-SD-NEXT:    smov w18, v0.h[3]
; CHECK-SD-NEXT:    sdiv w13, w12, w11
; CHECK-SD-NEXT:    sdiv w10, w9, w8
; CHECK-SD-NEXT:    msub w11, w13, w11, w12
; CHECK-SD-NEXT:    fmov s0, w11
; CHECK-SD-NEXT:    sdiv w16, w15, w14
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    mov v0.h[1], w8
; CHECK-SD-NEXT:    sdiv w9, w18, w17
; CHECK-SD-NEXT:    msub w8, w16, w14, w15
; CHECK-SD-NEXT:    mov v0.h[2], w8
; CHECK-SD-NEXT:    msub w8, w9, w17, w18
; CHECK-SD-NEXT:    mov v0.h[3], w8
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: srem4x16:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-GI-NEXT:    sshll v1.4s, v1.4h, #0
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:    fmov w9, s1
; CHECK-GI-NEXT:    mov w10, v1.s[1]
; CHECK-GI-NEXT:    mov w11, v1.s[2]
; CHECK-GI-NEXT:    mov w12, v1.s[3]
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    mov w9, v0.s[1]
; CHECK-GI-NEXT:    sdiv w9, w9, w10
; CHECK-GI-NEXT:    mov w10, v0.s[2]
; CHECK-GI-NEXT:    fmov s2, w8
; CHECK-GI-NEXT:    sdiv w10, w10, w11
; CHECK-GI-NEXT:    mov w11, v0.s[3]
; CHECK-GI-NEXT:    mov v2.s[1], w9
; CHECK-GI-NEXT:    sdiv w8, w11, w12
; CHECK-GI-NEXT:    mov v2.s[2], w10
; CHECK-GI-NEXT:    mov v2.s[3], w8
; CHECK-GI-NEXT:    mls v0.4s, v2.4s, v1.4s
; CHECK-GI-NEXT:    xtn v0.4h, v0.4s
; CHECK-GI-NEXT:    ret
	%tmp3 = srem <4 x i16> %A, %B;
	ret <4 x i16> %tmp3
}

define <8 x i16> @srem8x16(<8 x i16> %A, <8 x i16> %B) {
; CHECK-SD-LABEL: srem8x16:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    smov w11, v1.h[0]
; CHECK-SD-NEXT:    smov w12, v0.h[0]
; CHECK-SD-NEXT:    smov w8, v1.h[1]
; CHECK-SD-NEXT:    smov w9, v0.h[1]
; CHECK-SD-NEXT:    smov w14, v1.h[2]
; CHECK-SD-NEXT:    smov w15, v0.h[2]
; CHECK-SD-NEXT:    smov w17, v1.h[3]
; CHECK-SD-NEXT:    smov w18, v0.h[3]
; CHECK-SD-NEXT:    smov w1, v1.h[4]
; CHECK-SD-NEXT:    smov w2, v0.h[4]
; CHECK-SD-NEXT:    smov w4, v1.h[5]
; CHECK-SD-NEXT:    smov w5, v0.h[5]
; CHECK-SD-NEXT:    sdiv w13, w12, w11
; CHECK-SD-NEXT:    sdiv w10, w9, w8
; CHECK-SD-NEXT:    msub w11, w13, w11, w12
; CHECK-SD-NEXT:    smov w13, v1.h[7]
; CHECK-SD-NEXT:    fmov s2, w11
; CHECK-SD-NEXT:    smov w11, v0.h[6]
; CHECK-SD-NEXT:    sdiv w16, w15, w14
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    smov w10, v1.h[6]
; CHECK-SD-NEXT:    mov v2.h[1], w8
; CHECK-SD-NEXT:    sdiv w0, w18, w17
; CHECK-SD-NEXT:    msub w8, w16, w14, w15
; CHECK-SD-NEXT:    smov w14, v0.h[7]
; CHECK-SD-NEXT:    mov v2.h[2], w8
; CHECK-SD-NEXT:    sdiv w3, w2, w1
; CHECK-SD-NEXT:    msub w8, w0, w17, w18
; CHECK-SD-NEXT:    mov v2.h[3], w8
; CHECK-SD-NEXT:    sdiv w9, w5, w4
; CHECK-SD-NEXT:    msub w8, w3, w1, w2
; CHECK-SD-NEXT:    mov v2.h[4], w8
; CHECK-SD-NEXT:    sdiv w12, w11, w10
; CHECK-SD-NEXT:    msub w8, w9, w4, w5
; CHECK-SD-NEXT:    mov v2.h[5], w8
; CHECK-SD-NEXT:    sdiv w9, w14, w13
; CHECK-SD-NEXT:    msub w8, w12, w10, w11
; CHECK-SD-NEXT:    mov v2.h[6], w8
; CHECK-SD-NEXT:    msub w8, w9, w13, w14
; CHECK-SD-NEXT:    mov v2.h[7], w8
; CHECK-SD-NEXT:    mov v0.16b, v2.16b
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: srem8x16:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    sshll v2.4s, v0.4h, #0
; CHECK-GI-NEXT:    sshll v3.4s, v1.4h, #0
; CHECK-GI-NEXT:    sshll2 v0.4s, v0.8h, #0
; CHECK-GI-NEXT:    sshll2 v1.4s, v1.8h, #0
; CHECK-GI-NEXT:    fmov w8, s2
; CHECK-GI-NEXT:    fmov w9, s3
; CHECK-GI-NEXT:    mov w10, v3.s[1]
; CHECK-GI-NEXT:    mov w11, v3.s[2]
; CHECK-GI-NEXT:    mov w12, v3.s[3]
; CHECK-GI-NEXT:    fmov w13, s1
; CHECK-GI-NEXT:    mov w14, v1.s[1]
; CHECK-GI-NEXT:    mov w15, v1.s[2]
; CHECK-GI-NEXT:    mov w16, v1.s[3]
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    mov w9, v2.s[1]
; CHECK-GI-NEXT:    sdiv w9, w9, w10
; CHECK-GI-NEXT:    mov w10, v2.s[2]
; CHECK-GI-NEXT:    fmov s4, w8
; CHECK-GI-NEXT:    sdiv w10, w10, w11
; CHECK-GI-NEXT:    mov w11, v2.s[3]
; CHECK-GI-NEXT:    mov v4.s[1], w9
; CHECK-GI-NEXT:    sdiv w11, w11, w12
; CHECK-GI-NEXT:    fmov w12, s0
; CHECK-GI-NEXT:    mov v4.s[2], w10
; CHECK-GI-NEXT:    sdiv w12, w12, w13
; CHECK-GI-NEXT:    mov w13, v0.s[1]
; CHECK-GI-NEXT:    mov v4.s[3], w11
; CHECK-GI-NEXT:    mls v2.4s, v4.4s, v3.4s
; CHECK-GI-NEXT:    sdiv w13, w13, w14
; CHECK-GI-NEXT:    mov w14, v0.s[2]
; CHECK-GI-NEXT:    fmov s5, w12
; CHECK-GI-NEXT:    sdiv w14, w14, w15
; CHECK-GI-NEXT:    mov w15, v0.s[3]
; CHECK-GI-NEXT:    mov v5.s[1], w13
; CHECK-GI-NEXT:    sdiv w8, w15, w16
; CHECK-GI-NEXT:    mov v5.s[2], w14
; CHECK-GI-NEXT:    mov v5.s[3], w8
; CHECK-GI-NEXT:    mls v0.4s, v5.4s, v1.4s
; CHECK-GI-NEXT:    uzp1 v0.8h, v2.8h, v0.8h
; CHECK-GI-NEXT:    ret
	%tmp3 = srem <8 x i16> %A, %B;
	ret <8 x i16> %tmp3
}

define <1 x i32> @srem1x32(<1 x i32> %A, <1 x i32> %B) {
; CHECK-SD-LABEL: srem1x32:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    fmov w8, s1
; CHECK-SD-NEXT:    fmov w9, s0
; CHECK-SD-NEXT:    sdiv w10, w9, w8
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: srem1x32:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:    fmov w9, s1
; CHECK-GI-NEXT:    sdiv w10, w8, w9
; CHECK-GI-NEXT:    msub w8, w10, w9, w8
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    ret
	%tmp3 = srem <1 x i32> %A, %B;
	ret <1 x i32> %tmp3
}

define <2 x i32> @srem2x32(<2 x i32> %A, <2 x i32> %B) {
; CHECK-SD-LABEL: srem2x32:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    fmov w8, s1
; CHECK-SD-NEXT:    fmov w9, s0
; CHECK-SD-NEXT:    mov w11, v1.s[1]
; CHECK-SD-NEXT:    mov w12, v0.s[1]
; CHECK-SD-NEXT:    sdiv w10, w9, w8
; CHECK-SD-NEXT:    sdiv w13, w12, w11
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    msub w9, w13, w11, w12
; CHECK-SD-NEXT:    mov v0.s[1], w9
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: srem2x32:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:    fmov w9, s1
; CHECK-GI-NEXT:    mov w10, v1.s[1]
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    mov w9, v0.s[1]
; CHECK-GI-NEXT:    sdiv w9, w9, w10
; CHECK-GI-NEXT:    fmov s2, w8
; CHECK-GI-NEXT:    mov v2.s[1], w9
; CHECK-GI-NEXT:    mls v0.2s, v2.2s, v1.2s
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-GI-NEXT:    ret
	%tmp3 = srem <2 x i32> %A, %B;
	ret <2 x i32> %tmp3
}

define <4 x i32> @srem4x32(<4 x i32> %A, <4 x i32> %B) {
; CHECK-SD-LABEL: srem4x32:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    fmov w11, s1
; CHECK-SD-NEXT:    fmov w12, s0
; CHECK-SD-NEXT:    mov w8, v1.s[1]
; CHECK-SD-NEXT:    mov w9, v0.s[1]
; CHECK-SD-NEXT:    mov w14, v1.s[2]
; CHECK-SD-NEXT:    mov w15, v0.s[2]
; CHECK-SD-NEXT:    mov w17, v1.s[3]
; CHECK-SD-NEXT:    mov w18, v0.s[3]
; CHECK-SD-NEXT:    sdiv w13, w12, w11
; CHECK-SD-NEXT:    sdiv w10, w9, w8
; CHECK-SD-NEXT:    msub w11, w13, w11, w12
; CHECK-SD-NEXT:    fmov s0, w11
; CHECK-SD-NEXT:    sdiv w16, w15, w14
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    mov v0.s[1], w8
; CHECK-SD-NEXT:    sdiv w9, w18, w17
; CHECK-SD-NEXT:    msub w8, w16, w14, w15
; CHECK-SD-NEXT:    mov v0.s[2], w8
; CHECK-SD-NEXT:    msub w8, w9, w17, w18
; CHECK-SD-NEXT:    mov v0.s[3], w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: srem4x32:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:    fmov w9, s1
; CHECK-GI-NEXT:    mov w10, v1.s[1]
; CHECK-GI-NEXT:    mov w11, v1.s[2]
; CHECK-GI-NEXT:    mov w12, v1.s[3]
; CHECK-GI-NEXT:    sdiv w8, w8, w9
; CHECK-GI-NEXT:    mov w9, v0.s[1]
; CHECK-GI-NEXT:    sdiv w9, w9, w10
; CHECK-GI-NEXT:    mov w10, v0.s[2]
; CHECK-GI-NEXT:    fmov s2, w8
; CHECK-GI-NEXT:    sdiv w10, w10, w11
; CHECK-GI-NEXT:    mov w11, v0.s[3]
; CHECK-GI-NEXT:    mov v2.s[1], w9
; CHECK-GI-NEXT:    sdiv w8, w11, w12
; CHECK-GI-NEXT:    mov v2.s[2], w10
; CHECK-GI-NEXT:    mov v2.s[3], w8
; CHECK-GI-NEXT:    mls v0.4s, v2.4s, v1.4s
; CHECK-GI-NEXT:    ret
	%tmp3 = srem <4 x i32> %A, %B;
	ret <4 x i32> %tmp3
}

define <1 x i64> @srem1x64(<1 x i64> %A, <1 x i64> %B) {
; CHECK-SD-LABEL: srem1x64:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    fmov x8, d1
; CHECK-SD-NEXT:    fmov x9, d0
; CHECK-SD-NEXT:    sdiv x10, x9, x8
; CHECK-SD-NEXT:    msub x8, x10, x8, x9
; CHECK-SD-NEXT:    fmov d0, x8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: srem1x64:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov x8, d0
; CHECK-GI-NEXT:    fmov x9, d1
; CHECK-GI-NEXT:    sdiv x10, x8, x9
; CHECK-GI-NEXT:    msub x8, x10, x9, x8
; CHECK-GI-NEXT:    fmov d0, x8
; CHECK-GI-NEXT:    ret
	%tmp3 = srem <1 x i64> %A, %B;
	ret <1 x i64> %tmp3
}

define <2 x i64> @srem2x64(<2 x i64> %A, <2 x i64> %B) {
; CHECK-SD-LABEL: srem2x64:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    fmov x8, d1
; CHECK-SD-NEXT:    fmov x9, d0
; CHECK-SD-NEXT:    mov x11, v1.d[1]
; CHECK-SD-NEXT:    mov x12, v0.d[1]
; CHECK-SD-NEXT:    sdiv x10, x9, x8
; CHECK-SD-NEXT:    sdiv x13, x12, x11
; CHECK-SD-NEXT:    msub x8, x10, x8, x9
; CHECK-SD-NEXT:    fmov d0, x8
; CHECK-SD-NEXT:    msub x9, x13, x11, x12
; CHECK-SD-NEXT:    mov v0.d[1], x9
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: srem2x64:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov x8, d0
; CHECK-GI-NEXT:    fmov x9, d1
; CHECK-GI-NEXT:    mov x10, v1.d[1]
; CHECK-GI-NEXT:    mov x11, v0.d[1]
; CHECK-GI-NEXT:    sdiv x8, x8, x9
; CHECK-GI-NEXT:    sdiv x11, x11, x10
; CHECK-GI-NEXT:    fmov d1, x8
; CHECK-GI-NEXT:    mov v1.d[1], x11
; CHECK-GI-NEXT:    fmov x11, d1
; CHECK-GI-NEXT:    mov x8, v1.d[1]
; CHECK-GI-NEXT:    mul x9, x11, x9
; CHECK-GI-NEXT:    mul x8, x8, x10
; CHECK-GI-NEXT:    fmov d1, x9
; CHECK-GI-NEXT:    mov v1.d[1], x8
; CHECK-GI-NEXT:    sub v0.2d, v0.2d, v1.2d
; CHECK-GI-NEXT:    ret
	%tmp3 = srem <2 x i64> %A, %B;
	ret <2 x i64> %tmp3
}

define <1 x i8> @urem1x8(<1 x i8> %A, <1 x i8> %B) {
; CHECK-SD-LABEL: urem1x8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    umov w8, v1.b[0]
; CHECK-SD-NEXT:    umov w9, v0.b[0]
; CHECK-SD-NEXT:    udiv w10, w9, w8
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: urem1x8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    umov w8, v0.b[0]
; CHECK-GI-NEXT:    umov w9, v1.b[0]
; CHECK-GI-NEXT:    umov w10, v0.b[0]
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    umov w9, v1.b[0]
; CHECK-GI-NEXT:    msub w8, w8, w9, w10
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    ret
	%tmp3 = urem <1 x i8> %A, %B;
	ret <1 x i8> %tmp3
}

define <8 x i8> @urem8x8(<8 x i8> %A, <8 x i8> %B) {
; CHECK-SD-LABEL: urem8x8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    umov w11, v1.b[0]
; CHECK-SD-NEXT:    umov w12, v0.b[0]
; CHECK-SD-NEXT:    umov w8, v1.b[1]
; CHECK-SD-NEXT:    umov w9, v0.b[1]
; CHECK-SD-NEXT:    umov w14, v1.b[2]
; CHECK-SD-NEXT:    umov w15, v0.b[2]
; CHECK-SD-NEXT:    umov w17, v1.b[3]
; CHECK-SD-NEXT:    umov w18, v0.b[3]
; CHECK-SD-NEXT:    umov w1, v1.b[4]
; CHECK-SD-NEXT:    umov w2, v0.b[4]
; CHECK-SD-NEXT:    umov w4, v1.b[5]
; CHECK-SD-NEXT:    umov w5, v0.b[5]
; CHECK-SD-NEXT:    udiv w13, w12, w11
; CHECK-SD-NEXT:    udiv w10, w9, w8
; CHECK-SD-NEXT:    msub w11, w13, w11, w12
; CHECK-SD-NEXT:    umov w13, v1.b[7]
; CHECK-SD-NEXT:    fmov s2, w11
; CHECK-SD-NEXT:    umov w11, v0.b[6]
; CHECK-SD-NEXT:    udiv w16, w15, w14
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    umov w10, v1.b[6]
; CHECK-SD-NEXT:    mov v2.b[1], w8
; CHECK-SD-NEXT:    udiv w0, w18, w17
; CHECK-SD-NEXT:    msub w8, w16, w14, w15
; CHECK-SD-NEXT:    umov w14, v0.b[7]
; CHECK-SD-NEXT:    mov v2.b[2], w8
; CHECK-SD-NEXT:    udiv w3, w2, w1
; CHECK-SD-NEXT:    msub w8, w0, w17, w18
; CHECK-SD-NEXT:    mov v2.b[3], w8
; CHECK-SD-NEXT:    udiv w9, w5, w4
; CHECK-SD-NEXT:    msub w8, w3, w1, w2
; CHECK-SD-NEXT:    mov v2.b[4], w8
; CHECK-SD-NEXT:    udiv w12, w11, w10
; CHECK-SD-NEXT:    msub w8, w9, w4, w5
; CHECK-SD-NEXT:    mov v2.b[5], w8
; CHECK-SD-NEXT:    udiv w9, w14, w13
; CHECK-SD-NEXT:    msub w8, w12, w10, w11
; CHECK-SD-NEXT:    mov v2.b[6], w8
; CHECK-SD-NEXT:    msub w8, w9, w13, w14
; CHECK-SD-NEXT:    mov v2.b[7], w8
; CHECK-SD-NEXT:    fmov d0, d2
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: urem8x8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    ushll v2.8h, v0.8b, #0
; CHECK-GI-NEXT:    ushll v1.8h, v1.8b, #0
; CHECK-GI-NEXT:    ushll v0.4s, v2.4h, #0
; CHECK-GI-NEXT:    ushll v3.4s, v1.4h, #0
; CHECK-GI-NEXT:    ushll2 v2.4s, v2.8h, #0
; CHECK-GI-NEXT:    ext v5.16b, v1.16b, v1.16b, #8
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:    fmov w9, s3
; CHECK-GI-NEXT:    mov w10, v0.s[1]
; CHECK-GI-NEXT:    mov w11, v0.s[2]
; CHECK-GI-NEXT:    mov w12, v0.s[3]
; CHECK-GI-NEXT:    mov w14, v2.s[1]
; CHECK-GI-NEXT:    mov w15, v2.s[2]
; CHECK-GI-NEXT:    mov w16, v2.s[3]
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    mov w9, v3.s[1]
; CHECK-GI-NEXT:    udiv w9, w10, w9
; CHECK-GI-NEXT:    mov w10, v3.s[2]
; CHECK-GI-NEXT:    udiv w10, w11, w10
; CHECK-GI-NEXT:    mov w11, v3.s[3]
; CHECK-GI-NEXT:    ushll2 v3.4s, v1.8h, #0
; CHECK-GI-NEXT:    fmov w13, s3
; CHECK-GI-NEXT:    udiv w11, w12, w11
; CHECK-GI-NEXT:    fmov w12, s2
; CHECK-GI-NEXT:    udiv w12, w12, w13
; CHECK-GI-NEXT:    mov w13, v3.s[1]
; CHECK-GI-NEXT:    udiv w13, w14, w13
; CHECK-GI-NEXT:    mov w14, v3.s[2]
; CHECK-GI-NEXT:    fmov s4, w12
; CHECK-GI-NEXT:    udiv w14, w15, w14
; CHECK-GI-NEXT:    mov w15, v3.s[3]
; CHECK-GI-NEXT:    fmov s3, w8
; CHECK-GI-NEXT:    mov v4.h[1], w13
; CHECK-GI-NEXT:    mov v3.h[1], w9
; CHECK-GI-NEXT:    mov v3.h[2], w10
; CHECK-GI-NEXT:    udiv w8, w16, w15
; CHECK-GI-NEXT:    mov v4.h[2], w14
; CHECK-GI-NEXT:    mov v3.h[3], w11
; CHECK-GI-NEXT:    umlsl v0.4s, v3.4h, v1.4h
; CHECK-GI-NEXT:    mov v4.h[3], w8
; CHECK-GI-NEXT:    umlsl v2.4s, v4.4h, v5.4h
; CHECK-GI-NEXT:    uzp1 v0.8h, v0.8h, v2.8h
; CHECK-GI-NEXT:    xtn v0.8b, v0.8h
; CHECK-GI-NEXT:    ret
	%tmp3 = urem <8 x i8> %A, %B;
	ret <8 x i8> %tmp3
}

define <16 x i8> @urem16x8(<16 x i8> %A, <16 x i8> %B) {
; CHECK-SD-LABEL: urem16x8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    stp x28, x27, [sp, #-80]! // 16-byte Folded Spill
; CHECK-SD-NEXT:    stp x26, x25, [sp, #16] // 16-byte Folded Spill
; CHECK-SD-NEXT:    stp x24, x23, [sp, #32] // 16-byte Folded Spill
; CHECK-SD-NEXT:    stp x22, x21, [sp, #48] // 16-byte Folded Spill
; CHECK-SD-NEXT:    stp x20, x19, [sp, #64] // 16-byte Folded Spill
; CHECK-SD-NEXT:    .cfi_def_cfa_offset 80
; CHECK-SD-NEXT:    .cfi_offset w19, -8
; CHECK-SD-NEXT:    .cfi_offset w20, -16
; CHECK-SD-NEXT:    .cfi_offset w21, -24
; CHECK-SD-NEXT:    .cfi_offset w22, -32
; CHECK-SD-NEXT:    .cfi_offset w23, -40
; CHECK-SD-NEXT:    .cfi_offset w24, -48
; CHECK-SD-NEXT:    .cfi_offset w25, -56
; CHECK-SD-NEXT:    .cfi_offset w26, -64
; CHECK-SD-NEXT:    .cfi_offset w27, -72
; CHECK-SD-NEXT:    .cfi_offset w28, -80
; CHECK-SD-NEXT:    umov w11, v1.b[0]
; CHECK-SD-NEXT:    umov w12, v0.b[0]
; CHECK-SD-NEXT:    umov w8, v1.b[1]
; CHECK-SD-NEXT:    umov w9, v0.b[1]
; CHECK-SD-NEXT:    umov w14, v1.b[2]
; CHECK-SD-NEXT:    umov w15, v0.b[2]
; CHECK-SD-NEXT:    umov w17, v1.b[3]
; CHECK-SD-NEXT:    umov w18, v0.b[3]
; CHECK-SD-NEXT:    umov w1, v1.b[4]
; CHECK-SD-NEXT:    umov w2, v0.b[4]
; CHECK-SD-NEXT:    umov w4, v1.b[5]
; CHECK-SD-NEXT:    umov w5, v0.b[5]
; CHECK-SD-NEXT:    udiv w13, w12, w11
; CHECK-SD-NEXT:    umov w7, v1.b[6]
; CHECK-SD-NEXT:    umov w19, v0.b[6]
; CHECK-SD-NEXT:    umov w21, v1.b[7]
; CHECK-SD-NEXT:    umov w22, v0.b[7]
; CHECK-SD-NEXT:    umov w24, v1.b[8]
; CHECK-SD-NEXT:    umov w25, v0.b[8]
; CHECK-SD-NEXT:    umov w27, v1.b[9]
; CHECK-SD-NEXT:    umov w28, v0.b[9]
; CHECK-SD-NEXT:    udiv w10, w9, w8
; CHECK-SD-NEXT:    msub w11, w13, w11, w12
; CHECK-SD-NEXT:    umov w13, v1.b[11]
; CHECK-SD-NEXT:    fmov s2, w11
; CHECK-SD-NEXT:    umov w11, v0.b[10]
; CHECK-SD-NEXT:    udiv w16, w15, w14
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    umov w10, v1.b[10]
; CHECK-SD-NEXT:    mov v2.b[1], w8
; CHECK-SD-NEXT:    udiv w0, w18, w17
; CHECK-SD-NEXT:    msub w8, w16, w14, w15
; CHECK-SD-NEXT:    umov w14, v0.b[11]
; CHECK-SD-NEXT:    umov w16, v1.b[12]
; CHECK-SD-NEXT:    mov v2.b[2], w8
; CHECK-SD-NEXT:    udiv w3, w2, w1
; CHECK-SD-NEXT:    msub w8, w0, w17, w18
; CHECK-SD-NEXT:    umov w17, v0.b[12]
; CHECK-SD-NEXT:    umov w0, v1.b[13]
; CHECK-SD-NEXT:    mov v2.b[3], w8
; CHECK-SD-NEXT:    udiv w6, w5, w4
; CHECK-SD-NEXT:    msub w8, w3, w1, w2
; CHECK-SD-NEXT:    umov w1, v0.b[13]
; CHECK-SD-NEXT:    mov v2.b[4], w8
; CHECK-SD-NEXT:    udiv w20, w19, w7
; CHECK-SD-NEXT:    msub w8, w6, w4, w5
; CHECK-SD-NEXT:    mov v2.b[5], w8
; CHECK-SD-NEXT:    udiv w23, w22, w21
; CHECK-SD-NEXT:    msub w8, w20, w7, w19
; CHECK-SD-NEXT:    ldp x20, x19, [sp, #64] // 16-byte Folded Reload
; CHECK-SD-NEXT:    mov v2.b[6], w8
; CHECK-SD-NEXT:    udiv w26, w25, w24
; CHECK-SD-NEXT:    msub w8, w23, w21, w22
; CHECK-SD-NEXT:    ldp x22, x21, [sp, #48] // 16-byte Folded Reload
; CHECK-SD-NEXT:    mov v2.b[7], w8
; CHECK-SD-NEXT:    udiv w9, w28, w27
; CHECK-SD-NEXT:    msub w8, w26, w24, w25
; CHECK-SD-NEXT:    ldp x24, x23, [sp, #32] // 16-byte Folded Reload
; CHECK-SD-NEXT:    ldp x26, x25, [sp, #16] // 16-byte Folded Reload
; CHECK-SD-NEXT:    mov v2.b[8], w8
; CHECK-SD-NEXT:    udiv w12, w11, w10
; CHECK-SD-NEXT:    msub w8, w9, w27, w28
; CHECK-SD-NEXT:    mov v2.b[9], w8
; CHECK-SD-NEXT:    udiv w15, w14, w13
; CHECK-SD-NEXT:    msub w8, w12, w10, w11
; CHECK-SD-NEXT:    umov w10, v1.b[14]
; CHECK-SD-NEXT:    umov w11, v0.b[14]
; CHECK-SD-NEXT:    mov v2.b[10], w8
; CHECK-SD-NEXT:    udiv w18, w17, w16
; CHECK-SD-NEXT:    msub w8, w15, w13, w14
; CHECK-SD-NEXT:    umov w13, v1.b[15]
; CHECK-SD-NEXT:    umov w14, v0.b[15]
; CHECK-SD-NEXT:    mov v2.b[11], w8
; CHECK-SD-NEXT:    udiv w9, w1, w0
; CHECK-SD-NEXT:    msub w8, w18, w16, w17
; CHECK-SD-NEXT:    mov v2.b[12], w8
; CHECK-SD-NEXT:    udiv w12, w11, w10
; CHECK-SD-NEXT:    msub w8, w9, w0, w1
; CHECK-SD-NEXT:    mov v2.b[13], w8
; CHECK-SD-NEXT:    udiv w9, w14, w13
; CHECK-SD-NEXT:    msub w8, w12, w10, w11
; CHECK-SD-NEXT:    mov v2.b[14], w8
; CHECK-SD-NEXT:    msub w8, w9, w13, w14
; CHECK-SD-NEXT:    mov v2.b[15], w8
; CHECK-SD-NEXT:    mov v0.16b, v2.16b
; CHECK-SD-NEXT:    ldp x28, x27, [sp], #80 // 16-byte Folded Reload
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: urem16x8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    ushll v4.8h, v0.8b, #0
; CHECK-GI-NEXT:    ushll v3.8h, v1.8b, #0
; CHECK-GI-NEXT:    ushll2 v1.8h, v1.16b, #0
; CHECK-GI-NEXT:    ushll v2.4s, v4.4h, #0
; CHECK-GI-NEXT:    ushll v5.4s, v3.4h, #0
; CHECK-GI-NEXT:    ushll2 v4.4s, v4.8h, #0
; CHECK-GI-NEXT:    ushll v6.4s, v1.4h, #0
; CHECK-GI-NEXT:    ext v18.16b, v3.16b, v3.16b, #8
; CHECK-GI-NEXT:    ext v19.16b, v1.16b, v1.16b, #8
; CHECK-GI-NEXT:    fmov w8, s2
; CHECK-GI-NEXT:    fmov w9, s5
; CHECK-GI-NEXT:    mov w12, v2.s[3]
; CHECK-GI-NEXT:    mov w16, v4.s[3]
; CHECK-GI-NEXT:    fmov w17, s6
; CHECK-GI-NEXT:    udiv w10, w8, w9
; CHECK-GI-NEXT:    mov w8, v5.s[1]
; CHECK-GI-NEXT:    mov w9, v2.s[1]
; CHECK-GI-NEXT:    udiv w11, w9, w8
; CHECK-GI-NEXT:    mov w8, v5.s[2]
; CHECK-GI-NEXT:    mov w9, v2.s[2]
; CHECK-GI-NEXT:    udiv w9, w9, w8
; CHECK-GI-NEXT:    mov w8, v5.s[3]
; CHECK-GI-NEXT:    ushll2 v5.4s, v3.8h, #0
; CHECK-GI-NEXT:    fmov w13, s5
; CHECK-GI-NEXT:    udiv w8, w12, w8
; CHECK-GI-NEXT:    fmov w12, s4
; CHECK-GI-NEXT:    udiv w14, w12, w13
; CHECK-GI-NEXT:    mov w12, v5.s[1]
; CHECK-GI-NEXT:    mov w13, v4.s[1]
; CHECK-GI-NEXT:    udiv w15, w13, w12
; CHECK-GI-NEXT:    mov w12, v5.s[2]
; CHECK-GI-NEXT:    mov w13, v4.s[2]
; CHECK-GI-NEXT:    fmov s7, w14
; CHECK-GI-NEXT:    udiv w13, w13, w12
; CHECK-GI-NEXT:    mov w12, v5.s[3]
; CHECK-GI-NEXT:    ushll2 v5.8h, v0.16b, #0
; CHECK-GI-NEXT:    mov v7.h[1], w15
; CHECK-GI-NEXT:    ushll v0.4s, v5.4h, #0
; CHECK-GI-NEXT:    ushll2 v5.4s, v5.8h, #0
; CHECK-GI-NEXT:    mov w18, v0.s[1]
; CHECK-GI-NEXT:    mov w0, v0.s[2]
; CHECK-GI-NEXT:    mov w1, v0.s[3]
; CHECK-GI-NEXT:    mov w3, v5.s[1]
; CHECK-GI-NEXT:    mov w4, v5.s[2]
; CHECK-GI-NEXT:    mov w5, v5.s[3]
; CHECK-GI-NEXT:    udiv w12, w16, w12
; CHECK-GI-NEXT:    fmov w16, s0
; CHECK-GI-NEXT:    mov v7.h[2], w13
; CHECK-GI-NEXT:    udiv w16, w16, w17
; CHECK-GI-NEXT:    mov w17, v6.s[1]
; CHECK-GI-NEXT:    mov v7.h[3], w12
; CHECK-GI-NEXT:    umlsl v4.4s, v7.4h, v18.4h
; CHECK-GI-NEXT:    udiv w17, w18, w17
; CHECK-GI-NEXT:    mov w18, v6.s[2]
; CHECK-GI-NEXT:    fmov s16, w16
; CHECK-GI-NEXT:    udiv w18, w0, w18
; CHECK-GI-NEXT:    mov w0, v6.s[3]
; CHECK-GI-NEXT:    ushll2 v6.4s, v1.8h, #0
; CHECK-GI-NEXT:    mov v16.h[1], w17
; CHECK-GI-NEXT:    fmov w2, s6
; CHECK-GI-NEXT:    udiv w0, w1, w0
; CHECK-GI-NEXT:    fmov w1, s5
; CHECK-GI-NEXT:    mov v16.h[2], w18
; CHECK-GI-NEXT:    udiv w1, w1, w2
; CHECK-GI-NEXT:    mov w2, v6.s[1]
; CHECK-GI-NEXT:    mov v16.h[3], w0
; CHECK-GI-NEXT:    umlsl v0.4s, v16.4h, v1.4h
; CHECK-GI-NEXT:    udiv w2, w3, w2
; CHECK-GI-NEXT:    mov w3, v6.s[2]
; CHECK-GI-NEXT:    fmov s17, w1
; CHECK-GI-NEXT:    udiv w3, w4, w3
; CHECK-GI-NEXT:    mov w4, v6.s[3]
; CHECK-GI-NEXT:    fmov s6, w10
; CHECK-GI-NEXT:    mov v17.h[1], w2
; CHECK-GI-NEXT:    mov v6.h[1], w11
; CHECK-GI-NEXT:    mov v6.h[2], w9
; CHECK-GI-NEXT:    udiv w10, w5, w4
; CHECK-GI-NEXT:    mov v17.h[2], w3
; CHECK-GI-NEXT:    mov v6.h[3], w8
; CHECK-GI-NEXT:    umlsl v2.4s, v6.4h, v3.4h
; CHECK-GI-NEXT:    mov v17.h[3], w10
; CHECK-GI-NEXT:    uzp1 v1.8h, v2.8h, v4.8h
; CHECK-GI-NEXT:    umlsl v5.4s, v17.4h, v19.4h
; CHECK-GI-NEXT:    uzp1 v0.8h, v0.8h, v5.8h
; CHECK-GI-NEXT:    uzp1 v0.16b, v1.16b, v0.16b
; CHECK-GI-NEXT:    ret
	%tmp3 = urem <16 x i8> %A, %B;
	ret <16 x i8> %tmp3
}

define <1 x i16> @urem1x16(<1 x i16> %A, <1 x i16> %B) {
; CHECK-SD-LABEL: urem1x16:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    umov w8, v1.h[0]
; CHECK-SD-NEXT:    umov w9, v0.h[0]
; CHECK-SD-NEXT:    udiv w10, w9, w8
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: urem1x16:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    umov w8, v0.h[0]
; CHECK-GI-NEXT:    umov w9, v1.h[0]
; CHECK-GI-NEXT:    umov w10, v0.h[0]
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    umov w9, v1.h[0]
; CHECK-GI-NEXT:    msub w8, w8, w9, w10
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    ret
	%tmp3 = urem <1 x i16> %A, %B;
	ret <1 x i16> %tmp3
}

define <4 x i16> @urem4x16(<4 x i16> %A, <4 x i16> %B) {
; CHECK-SD-LABEL: urem4x16:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    umov w11, v1.h[0]
; CHECK-SD-NEXT:    umov w12, v0.h[0]
; CHECK-SD-NEXT:    umov w8, v1.h[1]
; CHECK-SD-NEXT:    umov w9, v0.h[1]
; CHECK-SD-NEXT:    umov w14, v1.h[2]
; CHECK-SD-NEXT:    umov w15, v0.h[2]
; CHECK-SD-NEXT:    umov w17, v1.h[3]
; CHECK-SD-NEXT:    umov w18, v0.h[3]
; CHECK-SD-NEXT:    udiv w13, w12, w11
; CHECK-SD-NEXT:    udiv w10, w9, w8
; CHECK-SD-NEXT:    msub w11, w13, w11, w12
; CHECK-SD-NEXT:    fmov s0, w11
; CHECK-SD-NEXT:    udiv w16, w15, w14
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    mov v0.h[1], w8
; CHECK-SD-NEXT:    udiv w9, w18, w17
; CHECK-SD-NEXT:    msub w8, w16, w14, w15
; CHECK-SD-NEXT:    mov v0.h[2], w8
; CHECK-SD-NEXT:    msub w8, w9, w17, w18
; CHECK-SD-NEXT:    mov v0.h[3], w8
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: urem4x16:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-GI-NEXT:    ushll v2.4s, v1.4h, #0
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:    fmov w9, s2
; CHECK-GI-NEXT:    mov w10, v0.s[1]
; CHECK-GI-NEXT:    mov w11, v0.s[2]
; CHECK-GI-NEXT:    mov w12, v0.s[3]
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    mov w9, v2.s[1]
; CHECK-GI-NEXT:    udiv w9, w10, w9
; CHECK-GI-NEXT:    mov w10, v2.s[2]
; CHECK-GI-NEXT:    udiv w10, w11, w10
; CHECK-GI-NEXT:    mov w11, v2.s[3]
; CHECK-GI-NEXT:    fmov s2, w8
; CHECK-GI-NEXT:    mov v2.h[1], w9
; CHECK-GI-NEXT:    udiv w8, w12, w11
; CHECK-GI-NEXT:    mov v2.h[2], w10
; CHECK-GI-NEXT:    mov v2.h[3], w8
; CHECK-GI-NEXT:    umlsl v0.4s, v2.4h, v1.4h
; CHECK-GI-NEXT:    xtn v0.4h, v0.4s
; CHECK-GI-NEXT:    ret
	%tmp3 = urem <4 x i16> %A, %B;
	ret <4 x i16> %tmp3
}

define <8 x i16> @urem8x16(<8 x i16> %A, <8 x i16> %B) {
; CHECK-SD-LABEL: urem8x16:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    umov w11, v1.h[0]
; CHECK-SD-NEXT:    umov w12, v0.h[0]
; CHECK-SD-NEXT:    umov w8, v1.h[1]
; CHECK-SD-NEXT:    umov w9, v0.h[1]
; CHECK-SD-NEXT:    umov w14, v1.h[2]
; CHECK-SD-NEXT:    umov w15, v0.h[2]
; CHECK-SD-NEXT:    umov w17, v1.h[3]
; CHECK-SD-NEXT:    umov w18, v0.h[3]
; CHECK-SD-NEXT:    umov w1, v1.h[4]
; CHECK-SD-NEXT:    umov w2, v0.h[4]
; CHECK-SD-NEXT:    umov w4, v1.h[5]
; CHECK-SD-NEXT:    umov w5, v0.h[5]
; CHECK-SD-NEXT:    udiv w13, w12, w11
; CHECK-SD-NEXT:    udiv w10, w9, w8
; CHECK-SD-NEXT:    msub w11, w13, w11, w12
; CHECK-SD-NEXT:    umov w13, v1.h[7]
; CHECK-SD-NEXT:    fmov s2, w11
; CHECK-SD-NEXT:    umov w11, v0.h[6]
; CHECK-SD-NEXT:    udiv w16, w15, w14
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    umov w10, v1.h[6]
; CHECK-SD-NEXT:    mov v2.h[1], w8
; CHECK-SD-NEXT:    udiv w0, w18, w17
; CHECK-SD-NEXT:    msub w8, w16, w14, w15
; CHECK-SD-NEXT:    umov w14, v0.h[7]
; CHECK-SD-NEXT:    mov v2.h[2], w8
; CHECK-SD-NEXT:    udiv w3, w2, w1
; CHECK-SD-NEXT:    msub w8, w0, w17, w18
; CHECK-SD-NEXT:    mov v2.h[3], w8
; CHECK-SD-NEXT:    udiv w9, w5, w4
; CHECK-SD-NEXT:    msub w8, w3, w1, w2
; CHECK-SD-NEXT:    mov v2.h[4], w8
; CHECK-SD-NEXT:    udiv w12, w11, w10
; CHECK-SD-NEXT:    msub w8, w9, w4, w5
; CHECK-SD-NEXT:    mov v2.h[5], w8
; CHECK-SD-NEXT:    udiv w9, w14, w13
; CHECK-SD-NEXT:    msub w8, w12, w10, w11
; CHECK-SD-NEXT:    mov v2.h[6], w8
; CHECK-SD-NEXT:    msub w8, w9, w13, w14
; CHECK-SD-NEXT:    mov v2.h[7], w8
; CHECK-SD-NEXT:    mov v0.16b, v2.16b
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: urem8x16:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    ushll v2.4s, v0.4h, #0
; CHECK-GI-NEXT:    ushll v3.4s, v1.4h, #0
; CHECK-GI-NEXT:    ushll2 v0.4s, v0.8h, #0
; CHECK-GI-NEXT:    ext v5.16b, v1.16b, v1.16b, #8
; CHECK-GI-NEXT:    fmov w8, s2
; CHECK-GI-NEXT:    fmov w9, s3
; CHECK-GI-NEXT:    mov w10, v2.s[1]
; CHECK-GI-NEXT:    mov w11, v2.s[2]
; CHECK-GI-NEXT:    mov w12, v2.s[3]
; CHECK-GI-NEXT:    mov w14, v0.s[1]
; CHECK-GI-NEXT:    mov w15, v0.s[2]
; CHECK-GI-NEXT:    mov w16, v0.s[3]
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    mov w9, v3.s[1]
; CHECK-GI-NEXT:    udiv w9, w10, w9
; CHECK-GI-NEXT:    mov w10, v3.s[2]
; CHECK-GI-NEXT:    udiv w10, w11, w10
; CHECK-GI-NEXT:    mov w11, v3.s[3]
; CHECK-GI-NEXT:    ushll2 v3.4s, v1.8h, #0
; CHECK-GI-NEXT:    fmov w13, s3
; CHECK-GI-NEXT:    udiv w11, w12, w11
; CHECK-GI-NEXT:    fmov w12, s0
; CHECK-GI-NEXT:    udiv w12, w12, w13
; CHECK-GI-NEXT:    mov w13, v3.s[1]
; CHECK-GI-NEXT:    udiv w13, w14, w13
; CHECK-GI-NEXT:    mov w14, v3.s[2]
; CHECK-GI-NEXT:    fmov s4, w12
; CHECK-GI-NEXT:    udiv w14, w15, w14
; CHECK-GI-NEXT:    mov w15, v3.s[3]
; CHECK-GI-NEXT:    fmov s3, w8
; CHECK-GI-NEXT:    mov v4.h[1], w13
; CHECK-GI-NEXT:    mov v3.h[1], w9
; CHECK-GI-NEXT:    mov v3.h[2], w10
; CHECK-GI-NEXT:    udiv w8, w16, w15
; CHECK-GI-NEXT:    mov v4.h[2], w14
; CHECK-GI-NEXT:    mov v3.h[3], w11
; CHECK-GI-NEXT:    umlsl v2.4s, v3.4h, v1.4h
; CHECK-GI-NEXT:    mov v4.h[3], w8
; CHECK-GI-NEXT:    umlsl v0.4s, v4.4h, v5.4h
; CHECK-GI-NEXT:    uzp1 v0.8h, v2.8h, v0.8h
; CHECK-GI-NEXT:    ret
	%tmp3 = urem <8 x i16> %A, %B;
	ret <8 x i16> %tmp3
}

define <1 x i32> @urem1x32(<1 x i32> %A, <1 x i32> %B) {
; CHECK-SD-LABEL: urem1x32:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    fmov w8, s1
; CHECK-SD-NEXT:    fmov w9, s0
; CHECK-SD-NEXT:    udiv w10, w9, w8
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: urem1x32:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:    fmov w9, s1
; CHECK-GI-NEXT:    udiv w10, w8, w9
; CHECK-GI-NEXT:    msub w8, w10, w9, w8
; CHECK-GI-NEXT:    fmov s0, w8
; CHECK-GI-NEXT:    ret
	%tmp3 = urem <1 x i32> %A, %B;
	ret <1 x i32> %tmp3
}

define <2 x i32> @urem2x32(<2 x i32> %A, <2 x i32> %B) {
; CHECK-SD-LABEL: urem2x32:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    fmov w8, s1
; CHECK-SD-NEXT:    fmov w9, s0
; CHECK-SD-NEXT:    mov w11, v1.s[1]
; CHECK-SD-NEXT:    mov w12, v0.s[1]
; CHECK-SD-NEXT:    udiv w10, w9, w8
; CHECK-SD-NEXT:    udiv w13, w12, w11
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    fmov s0, w8
; CHECK-SD-NEXT:    msub w9, w13, w11, w12
; CHECK-SD-NEXT:    mov v0.s[1], w9
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: urem2x32:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:    fmov w9, s1
; CHECK-GI-NEXT:    mov w10, v1.s[1]
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    mov w9, v0.s[1]
; CHECK-GI-NEXT:    udiv w9, w9, w10
; CHECK-GI-NEXT:    fmov s2, w8
; CHECK-GI-NEXT:    mov v2.s[1], w9
; CHECK-GI-NEXT:    mls v0.2s, v2.2s, v1.2s
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-GI-NEXT:    ret
	%tmp3 = urem <2 x i32> %A, %B;
	ret <2 x i32> %tmp3
}

define <4 x i32> @urem4x32(<4 x i32> %A, <4 x i32> %B) {
; CHECK-SD-LABEL: urem4x32:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    fmov w11, s1
; CHECK-SD-NEXT:    fmov w12, s0
; CHECK-SD-NEXT:    mov w8, v1.s[1]
; CHECK-SD-NEXT:    mov w9, v0.s[1]
; CHECK-SD-NEXT:    mov w14, v1.s[2]
; CHECK-SD-NEXT:    mov w15, v0.s[2]
; CHECK-SD-NEXT:    mov w17, v1.s[3]
; CHECK-SD-NEXT:    mov w18, v0.s[3]
; CHECK-SD-NEXT:    udiv w13, w12, w11
; CHECK-SD-NEXT:    udiv w10, w9, w8
; CHECK-SD-NEXT:    msub w11, w13, w11, w12
; CHECK-SD-NEXT:    fmov s0, w11
; CHECK-SD-NEXT:    udiv w16, w15, w14
; CHECK-SD-NEXT:    msub w8, w10, w8, w9
; CHECK-SD-NEXT:    mov v0.s[1], w8
; CHECK-SD-NEXT:    udiv w9, w18, w17
; CHECK-SD-NEXT:    msub w8, w16, w14, w15
; CHECK-SD-NEXT:    mov v0.s[2], w8
; CHECK-SD-NEXT:    msub w8, w9, w17, w18
; CHECK-SD-NEXT:    mov v0.s[3], w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: urem4x32:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:    fmov w9, s1
; CHECK-GI-NEXT:    mov w10, v1.s[1]
; CHECK-GI-NEXT:    mov w11, v1.s[2]
; CHECK-GI-NEXT:    mov w12, v1.s[3]
; CHECK-GI-NEXT:    udiv w8, w8, w9
; CHECK-GI-NEXT:    mov w9, v0.s[1]
; CHECK-GI-NEXT:    udiv w9, w9, w10
; CHECK-GI-NEXT:    mov w10, v0.s[2]
; CHECK-GI-NEXT:    fmov s2, w8
; CHECK-GI-NEXT:    udiv w10, w10, w11
; CHECK-GI-NEXT:    mov w11, v0.s[3]
; CHECK-GI-NEXT:    mov v2.s[1], w9
; CHECK-GI-NEXT:    udiv w8, w11, w12
; CHECK-GI-NEXT:    mov v2.s[2], w10
; CHECK-GI-NEXT:    mov v2.s[3], w8
; CHECK-GI-NEXT:    mls v0.4s, v2.4s, v1.4s
; CHECK-GI-NEXT:    ret
	%tmp3 = urem <4 x i32> %A, %B;
	ret <4 x i32> %tmp3
}

define <1 x i64> @urem1x64(<1 x i64> %A, <1 x i64> %B) {
; CHECK-SD-LABEL: urem1x64:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    fmov x8, d1
; CHECK-SD-NEXT:    fmov x9, d0
; CHECK-SD-NEXT:    udiv x10, x9, x8
; CHECK-SD-NEXT:    msub x8, x10, x8, x9
; CHECK-SD-NEXT:    fmov d0, x8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: urem1x64:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov x8, d0
; CHECK-GI-NEXT:    fmov x9, d1
; CHECK-GI-NEXT:    udiv x10, x8, x9
; CHECK-GI-NEXT:    msub x8, x10, x9, x8
; CHECK-GI-NEXT:    fmov d0, x8
; CHECK-GI-NEXT:    ret
	%tmp3 = urem <1 x i64> %A, %B;
	ret <1 x i64> %tmp3
}

define <2 x i64> @urem2x64(<2 x i64> %A, <2 x i64> %B) {
; CHECK-SD-LABEL: urem2x64:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    fmov x8, d1
; CHECK-SD-NEXT:    fmov x9, d0
; CHECK-SD-NEXT:    mov x11, v1.d[1]
; CHECK-SD-NEXT:    mov x12, v0.d[1]
; CHECK-SD-NEXT:    udiv x10, x9, x8
; CHECK-SD-NEXT:    udiv x13, x12, x11
; CHECK-SD-NEXT:    msub x8, x10, x8, x9
; CHECK-SD-NEXT:    fmov d0, x8
; CHECK-SD-NEXT:    msub x9, x13, x11, x12
; CHECK-SD-NEXT:    mov v0.d[1], x9
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: urem2x64:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    fmov x8, d0
; CHECK-GI-NEXT:    fmov x9, d1
; CHECK-GI-NEXT:    mov x10, v1.d[1]
; CHECK-GI-NEXT:    mov x11, v0.d[1]
; CHECK-GI-NEXT:    udiv x8, x8, x9
; CHECK-GI-NEXT:    udiv x11, x11, x10
; CHECK-GI-NEXT:    fmov d1, x8
; CHECK-GI-NEXT:    mov v1.d[1], x11
; CHECK-GI-NEXT:    fmov x11, d1
; CHECK-GI-NEXT:    mov x8, v1.d[1]
; CHECK-GI-NEXT:    mul x9, x11, x9
; CHECK-GI-NEXT:    mul x8, x8, x10
; CHECK-GI-NEXT:    fmov d1, x9
; CHECK-GI-NEXT:    mov v1.d[1], x8
; CHECK-GI-NEXT:    sub v0.2d, v0.2d, v1.2d
; CHECK-GI-NEXT:    ret
	%tmp3 = urem <2 x i64> %A, %B;
	ret <2 x i64> %tmp3
}

define <2 x float> @frem2f32(<2 x float> %A, <2 x float> %B) {
; CHECK-SD-LABEL: frem2f32:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    sub sp, sp, #64
; CHECK-SD-NEXT:    str x30, [sp, #48] // 8-byte Spill
; CHECK-SD-NEXT:    .cfi_def_cfa_offset 64
; CHECK-SD-NEXT:    .cfi_offset w30, -16
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    stp q0, q1, [sp] // 32-byte Folded Spill
; CHECK-SD-NEXT:    mov s0, v0.s[1]
; CHECK-SD-NEXT:    mov s1, v1.s[1]
; CHECK-SD-NEXT:    bl fmodf
; CHECK-SD-NEXT:    // kill: def $s0 killed $s0 def $q0
; CHECK-SD-NEXT:    str q0, [sp, #32] // 16-byte Spill
; CHECK-SD-NEXT:    ldp q0, q1, [sp] // 32-byte Folded Reload
; CHECK-SD-NEXT:    // kill: def $s0 killed $s0 killed $q0
; CHECK-SD-NEXT:    // kill: def $s1 killed $s1 killed $q1
; CHECK-SD-NEXT:    bl fmodf
; CHECK-SD-NEXT:    ldr q1, [sp, #32] // 16-byte Reload
; CHECK-SD-NEXT:    // kill: def $s0 killed $s0 def $q0
; CHECK-SD-NEXT:    ldr x30, [sp, #48] // 8-byte Reload
; CHECK-SD-NEXT:    mov v0.s[1], v1.s[0]
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-SD-NEXT:    add sp, sp, #64
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: frem2f32:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    sub sp, sp, #48
; CHECK-GI-NEXT:    stp d9, d8, [sp, #16] // 16-byte Folded Spill
; CHECK-GI-NEXT:    str x30, [sp, #32] // 8-byte Spill
; CHECK-GI-NEXT:    .cfi_def_cfa_offset 48
; CHECK-GI-NEXT:    .cfi_offset w30, -16
; CHECK-GI-NEXT:    .cfi_offset b8, -24
; CHECK-GI-NEXT:    .cfi_offset b9, -32
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-GI-NEXT:    mov s8, v0.s[1]
; CHECK-GI-NEXT:    mov s9, v1.s[1]
; CHECK-GI-NEXT:    // kill: def $s0 killed $s0 killed $q0
; CHECK-GI-NEXT:    // kill: def $s1 killed $s1 killed $q1
; CHECK-GI-NEXT:    bl fmodf
; CHECK-GI-NEXT:    // kill: def $s0 killed $s0 def $q0
; CHECK-GI-NEXT:    str q0, [sp] // 16-byte Spill
; CHECK-GI-NEXT:    fmov s1, s9
; CHECK-GI-NEXT:    fmov s0, s8
; CHECK-GI-NEXT:    bl fmodf
; CHECK-GI-NEXT:    ldr q1, [sp] // 16-byte Reload
; CHECK-GI-NEXT:    // kill: def $s0 killed $s0 def $q0
; CHECK-GI-NEXT:    ldp d9, d8, [sp, #16] // 16-byte Folded Reload
; CHECK-GI-NEXT:    ldr x30, [sp, #32] // 8-byte Reload
; CHECK-GI-NEXT:    mov v1.s[1], v0.s[0]
; CHECK-GI-NEXT:    fmov d0, d1
; CHECK-GI-NEXT:    add sp, sp, #48
; CHECK-GI-NEXT:    ret
	%tmp3 = frem <2 x float> %A, %B;
	ret <2 x float> %tmp3
}

define <4 x float> @frem4f32(<4 x float> %A, <4 x float> %B) {
; CHECK-SD-LABEL: frem4f32:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    sub sp, sp, #64
; CHECK-SD-NEXT:    str x30, [sp, #48] // 8-byte Spill
; CHECK-SD-NEXT:    .cfi_def_cfa_offset 64
; CHECK-SD-NEXT:    .cfi_offset w30, -16
; CHECK-SD-NEXT:    stp q0, q1, [sp, #16] // 32-byte Folded Spill
; CHECK-SD-NEXT:    mov s0, v0.s[1]
; CHECK-SD-NEXT:    mov s1, v1.s[1]
; CHECK-SD-NEXT:    bl fmodf
; CHECK-SD-NEXT:    // kill: def $s0 killed $s0 def $q0
; CHECK-SD-NEXT:    str q0, [sp] // 16-byte Spill
; CHECK-SD-NEXT:    ldp q0, q1, [sp, #16] // 32-byte Folded Reload
; CHECK-SD-NEXT:    // kill: def $s0 killed $s0 killed $q0
; CHECK-SD-NEXT:    // kill: def $s1 killed $s1 killed $q1
; CHECK-SD-NEXT:    bl fmodf
; CHECK-SD-NEXT:    ldr q1, [sp] // 16-byte Reload
; CHECK-SD-NEXT:    // kill: def $s0 killed $s0 def $q0
; CHECK-SD-NEXT:    mov v0.s[1], v1.s[0]
; CHECK-SD-NEXT:    str q0, [sp] // 16-byte Spill
; CHECK-SD-NEXT:    ldp q0, q1, [sp, #16] // 32-byte Folded Reload
; CHECK-SD-NEXT:    mov s0, v0.s[2]
; CHECK-SD-NEXT:    mov s1, v1.s[2]
; CHECK-SD-NEXT:    bl fmodf
; CHECK-SD-NEXT:    ldr q1, [sp] // 16-byte Reload
; CHECK-SD-NEXT:    // kill: def $s0 killed $s0 def $q0
; CHECK-SD-NEXT:    mov v1.s[2], v0.s[0]
; CHECK-SD-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-SD-NEXT:    ldp q0, q1, [sp, #16] // 32-byte Folded Reload
; CHECK-SD-NEXT:    mov s0, v0.s[3]
; CHECK-SD-NEXT:    mov s1, v1.s[3]
; CHECK-SD-NEXT:    bl fmodf
; CHECK-SD-NEXT:    ldr q1, [sp] // 16-byte Reload
; CHECK-SD-NEXT:    // kill: def $s0 killed $s0 def $q0
; CHECK-SD-NEXT:    ldr x30, [sp, #48] // 8-byte Reload
; CHECK-SD-NEXT:    mov v1.s[3], v0.s[0]
; CHECK-SD-NEXT:    mov v0.16b, v1.16b
; CHECK-SD-NEXT:    add sp, sp, #64
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: frem4f32:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    sub sp, sp, #112
; CHECK-GI-NEXT:    stp d13, d12, [sp, #48] // 16-byte Folded Spill
; CHECK-GI-NEXT:    stp d11, d10, [sp, #64] // 16-byte Folded Spill
; CHECK-GI-NEXT:    stp d9, d8, [sp, #80] // 16-byte Folded Spill
; CHECK-GI-NEXT:    str x30, [sp, #96] // 8-byte Spill
; CHECK-GI-NEXT:    .cfi_def_cfa_offset 112
; CHECK-GI-NEXT:    .cfi_offset w30, -16
; CHECK-GI-NEXT:    .cfi_offset b8, -24
; CHECK-GI-NEXT:    .cfi_offset b9, -32
; CHECK-GI-NEXT:    .cfi_offset b10, -40
; CHECK-GI-NEXT:    .cfi_offset b11, -48
; CHECK-GI-NEXT:    .cfi_offset b12, -56
; CHECK-GI-NEXT:    .cfi_offset b13, -64
; CHECK-GI-NEXT:    mov s8, v0.s[1]
; CHECK-GI-NEXT:    mov s9, v0.s[2]
; CHECK-GI-NEXT:    mov s10, v0.s[3]
; CHECK-GI-NEXT:    mov s11, v1.s[1]
; CHECK-GI-NEXT:    // kill: def $s0 killed $s0 killed $q0
; CHECK-GI-NEXT:    mov s12, v1.s[2]
; CHECK-GI-NEXT:    mov s13, v1.s[3]
; CHECK-GI-NEXT:    // kill: def $s1 killed $s1 killed $q1
; CHECK-GI-NEXT:    bl fmodf
; CHECK-GI-NEXT:    // kill: def $s0 killed $s0 def $q0
; CHECK-GI-NEXT:    str q0, [sp, #32] // 16-byte Spill
; CHECK-GI-NEXT:    fmov s1, s11
; CHECK-GI-NEXT:    fmov s0, s8
; CHECK-GI-NEXT:    bl fmodf
; CHECK-GI-NEXT:    // kill: def $s0 killed $s0 def $q0
; CHECK-GI-NEXT:    str q0, [sp, #16] // 16-byte Spill
; CHECK-GI-NEXT:    fmov s1, s12
; CHECK-GI-NEXT:    fmov s0, s9
; CHECK-GI-NEXT:    bl fmodf
; CHECK-GI-NEXT:    // kill: def $s0 killed $s0 def $q0
; CHECK-GI-NEXT:    str q0, [sp] // 16-byte Spill
; CHECK-GI-NEXT:    fmov s1, s13
; CHECK-GI-NEXT:    fmov s0, s10
; CHECK-GI-NEXT:    bl fmodf
; CHECK-GI-NEXT:    ldp q2, q1, [sp, #16] // 32-byte Folded Reload
; CHECK-GI-NEXT:    // kill: def $s0 killed $s0 def $q0
; CHECK-GI-NEXT:    ldr x30, [sp, #96] // 8-byte Reload
; CHECK-GI-NEXT:    ldp d9, d8, [sp, #80] // 16-byte Folded Reload
; CHECK-GI-NEXT:    ldp d11, d10, [sp, #64] // 16-byte Folded Reload
; CHECK-GI-NEXT:    mov v1.s[1], v2.s[0]
; CHECK-GI-NEXT:    ldr q2, [sp] // 16-byte Reload
; CHECK-GI-NEXT:    ldp d13, d12, [sp, #48] // 16-byte Folded Reload
; CHECK-GI-NEXT:    mov v1.s[2], v2.s[0]
; CHECK-GI-NEXT:    mov v1.s[3], v0.s[0]
; CHECK-GI-NEXT:    mov v0.16b, v1.16b
; CHECK-GI-NEXT:    add sp, sp, #112
; CHECK-GI-NEXT:    ret
	%tmp3 = frem <4 x float> %A, %B;
	ret <4 x float> %tmp3
}

define <1 x double> @frem1d64(<1 x double> %A, <1 x double> %B) {
; CHECK-LABEL: frem1d64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset w30, -16
; CHECK-NEXT:    bl fmod
; CHECK-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
	%tmp3 = frem <1 x double> %A, %B;
	ret <1 x double> %tmp3
}

define <2 x double> @frem2d64(<2 x double> %A, <2 x double> %B) {
; CHECK-SD-LABEL: frem2d64:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    sub sp, sp, #64
; CHECK-SD-NEXT:    str x30, [sp, #48] // 8-byte Spill
; CHECK-SD-NEXT:    .cfi_def_cfa_offset 64
; CHECK-SD-NEXT:    .cfi_offset w30, -16
; CHECK-SD-NEXT:    stp q0, q1, [sp] // 32-byte Folded Spill
; CHECK-SD-NEXT:    mov d0, v0.d[1]
; CHECK-SD-NEXT:    mov d1, v1.d[1]
; CHECK-SD-NEXT:    bl fmod
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    str q0, [sp, #32] // 16-byte Spill
; CHECK-SD-NEXT:    ldp q0, q1, [sp] // 32-byte Folded Reload
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 killed $q1
; CHECK-SD-NEXT:    bl fmod
; CHECK-SD-NEXT:    ldr q1, [sp, #32] // 16-byte Reload
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    ldr x30, [sp, #48] // 8-byte Reload
; CHECK-SD-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-SD-NEXT:    add sp, sp, #64
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: frem2d64:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    sub sp, sp, #48
; CHECK-GI-NEXT:    stp d9, d8, [sp, #16] // 16-byte Folded Spill
; CHECK-GI-NEXT:    str x30, [sp, #32] // 8-byte Spill
; CHECK-GI-NEXT:    .cfi_def_cfa_offset 48
; CHECK-GI-NEXT:    .cfi_offset w30, -16
; CHECK-GI-NEXT:    .cfi_offset b8, -24
; CHECK-GI-NEXT:    .cfi_offset b9, -32
; CHECK-GI-NEXT:    mov d8, v0.d[1]
; CHECK-GI-NEXT:    mov d9, v1.d[1]
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-GI-NEXT:    // kill: def $d1 killed $d1 killed $q1
; CHECK-GI-NEXT:    bl fmod
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    str q0, [sp] // 16-byte Spill
; CHECK-GI-NEXT:    fmov d1, d9
; CHECK-GI-NEXT:    fmov d0, d8
; CHECK-GI-NEXT:    bl fmod
; CHECK-GI-NEXT:    ldr q1, [sp] // 16-byte Reload
; CHECK-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-NEXT:    ldp d9, d8, [sp, #16] // 16-byte Folded Reload
; CHECK-GI-NEXT:    ldr x30, [sp, #32] // 8-byte Reload
; CHECK-GI-NEXT:    mov v1.d[1], v0.d[0]
; CHECK-GI-NEXT:    mov v0.16b, v1.16b
; CHECK-GI-NEXT:    add sp, sp, #48
; CHECK-GI-NEXT:    ret
	%tmp3 = frem <2 x double> %A, %B;
	ret <2 x double> %tmp3
}

define <8 x i8> @poly_mulv8i8(<8 x i8> %lhs, <8 x i8> %rhs) {
; CHECK-LABEL: poly_mulv8i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    pmul v0.8b, v0.8b, v1.8b
; CHECK-NEXT:    ret
   %prod = call <8 x i8> @llvm.aarch64.neon.pmul.v8i8(<8 x i8> %lhs, <8 x i8> %rhs)
   ret <8 x i8> %prod
}

define <16 x i8> @poly_mulv16i8(<16 x i8> %lhs, <16 x i8> %rhs) {
; CHECK-LABEL: poly_mulv16i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    pmul v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    ret
   %prod = call <16 x i8> @llvm.aarch64.neon.pmul.v16i8(<16 x i8> %lhs, <16 x i8> %rhs)
   ret <16 x i8> %prod
}

define <16 x i8> @commutable_poly_mul(<16 x i8> %lhs, <16 x i8> %rhs) {
; CHECK-LABEL: commutable_poly_mul:
; CHECK:       // %bb.0:
; CHECK-NEXT:    pmul v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    add v0.16b, v0.16b, v0.16b
; CHECK-NEXT:    ret
  %1 = call <16 x i8> @llvm.aarch64.neon.pmul.v16i8(<16 x i8> %lhs, <16 x i8> %rhs)
  %2 = call <16 x i8> @llvm.aarch64.neon.pmul.v16i8(<16 x i8> %rhs, <16 x i8> %lhs)
  %3 = add <16 x i8> %1, %2
  ret <16 x i8> %3
}

define <4 x i16> @test_sqdmulh_v4i16(<4 x i16> %lhs, <4 x i16> %rhs) {
; CHECK-LABEL: test_sqdmulh_v4i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sqdmulh v0.4h, v0.4h, v1.4h
; CHECK-NEXT:    ret
   %prod = call <4 x i16> @llvm.aarch64.neon.sqdmulh.v4i16(<4 x i16> %lhs, <4 x i16> %rhs)
   ret <4 x i16> %prod
}

define <8 x i16> @test_sqdmulh_v8i16(<8 x i16> %lhs, <8 x i16> %rhs) {
; CHECK-LABEL: test_sqdmulh_v8i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sqdmulh v0.8h, v0.8h, v1.8h
; CHECK-NEXT:    ret
   %prod = call <8 x i16> @llvm.aarch64.neon.sqdmulh.v8i16(<8 x i16> %lhs, <8 x i16> %rhs)
   ret <8 x i16> %prod
}

define <2 x i32> @test_sqdmulh_v2i32(<2 x i32> %lhs, <2 x i32> %rhs) {
; CHECK-LABEL: test_sqdmulh_v2i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sqdmulh v0.2s, v0.2s, v1.2s
; CHECK-NEXT:    ret
   %prod = call <2 x i32> @llvm.aarch64.neon.sqdmulh.v2i32(<2 x i32> %lhs, <2 x i32> %rhs)
   ret <2 x i32> %prod
}

define <4 x i32> @test_sqdmulh_v4i32(<4 x i32> %lhs, <4 x i32> %rhs) {
; CHECK-LABEL: test_sqdmulh_v4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sqdmulh v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
   %prod = call <4 x i32> @llvm.aarch64.neon.sqdmulh.v4i32(<4 x i32> %lhs, <4 x i32> %rhs)
   ret <4 x i32> %prod
}

define <4 x i16> @test_sqrdmulh_v4i16(<4 x i16> %lhs, <4 x i16> %rhs) {
; CHECK-LABEL: test_sqrdmulh_v4i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sqrdmulh v0.4h, v0.4h, v1.4h
; CHECK-NEXT:    ret
   %prod = call <4 x i16> @llvm.aarch64.neon.sqrdmulh.v4i16(<4 x i16> %lhs, <4 x i16> %rhs)
   ret <4 x i16> %prod
}

define <8 x i16> @test_sqrdmulh_v8i16(<8 x i16> %lhs, <8 x i16> %rhs) {
; CHECK-LABEL: test_sqrdmulh_v8i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sqrdmulh v0.8h, v0.8h, v1.8h
; CHECK-NEXT:    ret
   %prod = call <8 x i16> @llvm.aarch64.neon.sqrdmulh.v8i16(<8 x i16> %lhs, <8 x i16> %rhs)
   ret <8 x i16> %prod
}

define <2 x i32> @test_sqrdmulh_v2i32(<2 x i32> %lhs, <2 x i32> %rhs) {
; CHECK-LABEL: test_sqrdmulh_v2i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sqrdmulh v0.2s, v0.2s, v1.2s
; CHECK-NEXT:    ret
   %prod = call <2 x i32> @llvm.aarch64.neon.sqrdmulh.v2i32(<2 x i32> %lhs, <2 x i32> %rhs)
   ret <2 x i32> %prod
}

define <4 x i32> @test_sqrdmulh_v4i32(<4 x i32> %lhs, <4 x i32> %rhs) {
; CHECK-LABEL: test_sqrdmulh_v4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sqrdmulh v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
   %prod = call <4 x i32> @llvm.aarch64.neon.sqrdmulh.v4i32(<4 x i32> %lhs, <4 x i32> %rhs)
   ret <4 x i32> %prod
}

define <2 x float> @fmulx_v2f32(<2 x float> %lhs, <2 x float> %rhs) {
; CHECK-LABEL: fmulx_v2f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fmulx v0.2s, v0.2s, v1.2s
; CHECK-NEXT:    ret
        %val = call <2 x float> @llvm.aarch64.neon.fmulx.v2f32(<2 x float> %lhs, <2 x float> %rhs)
        ret <2 x float> %val
}

define <4 x float> @fmulx_v4f32(<4 x float> %lhs, <4 x float> %rhs) {
; CHECK-LABEL: fmulx_v4f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fmulx v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
        %val = call <4 x float> @llvm.aarch64.neon.fmulx.v4f32(<4 x float> %lhs, <4 x float> %rhs)
        ret <4 x float> %val
}

define <2 x double> @fmulx_v2f64(<2 x double> %lhs, <2 x double> %rhs) {
; CHECK-LABEL: fmulx_v2f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fmulx v0.2d, v0.2d, v1.2d
; CHECK-NEXT:    ret
        %val = call <2 x double> @llvm.aarch64.neon.fmulx.v2f64(<2 x double> %lhs, <2 x double> %rhs)
        ret <2 x double> %val
}
