; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=arm64-apple-ios3.0.0 -aarch64-neon-syntax=apple -mcpu=cyclone | FileCheck %s
; ModuleID = 'arm64_vecCmpBr.c'
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-n32:64-S128"


define i32 @anyZero64(<4 x i16> %a) #0 {
; CHECK-LABEL: anyZero64:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    uminv.8b b0, v0
; CHECK-NEXT:    cmeq s0, s0, #0
; CHECK-NEXT:    fcmp s0, #0.0
; CHECK-NEXT:    b.vs LBB0_2
; CHECK-NEXT:  ; %bb.1: ; %return
; CHECK-NEXT:    mov w0, #0 ; =0x0
; CHECK-NEXT:    ret
; CHECK-NEXT:  LBB0_2: ; %if.then
; CHECK-NEXT:    b _bar
entry:
  %0 = bitcast <4 x i16> %a to <8 x i8>
  %vminv.i = tail call i32 @llvm.aarch64.neon.uminv.i32.v8i8(<8 x i8> %0) #3
  %1 = trunc i32 %vminv.i to i8
  %tobool = icmp eq i8 %1, 0
  br i1 %tobool, label %if.then, label %return

if.then:                                          ; preds = %entry
  %call1 = tail call i32 @bar() #4
  br label %return

return:                                           ; preds = %entry, %if.then
  %retval.0 = phi i32 [ %call1, %if.then ], [ 0, %entry ]
  ret i32 %retval.0
}

declare i32 @bar(...) #1

define i32 @anyZero128(<8 x i16> %a) #0 {
; CHECK-LABEL: anyZero128:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    uminv.16b b0, v0
; CHECK-NEXT:    cmeq s0, s0, #0
; CHECK-NEXT:    fcmp s0, #0.0
; CHECK-NEXT:    b.vs LBB1_2
; CHECK-NEXT:  ; %bb.1: ; %return
; CHECK-NEXT:    mov w0, #0 ; =0x0
; CHECK-NEXT:    ret
; CHECK-NEXT:  LBB1_2: ; %if.then
; CHECK-NEXT:    b _bar

entry:
  %0 = bitcast <8 x i16> %a to <16 x i8>
  %vminv.i = tail call i32 @llvm.aarch64.neon.uminv.i32.v16i8(<16 x i8> %0) #3
  %1 = trunc i32 %vminv.i to i8
  %tobool = icmp eq i8 %1, 0
  br i1 %tobool, label %if.then, label %return

if.then:                                          ; preds = %entry
  %call1 = tail call i32 @bar() #4
  br label %return

return:                                           ; preds = %entry, %if.then
  %retval.0 = phi i32 [ %call1, %if.then ], [ 0, %entry ]
  ret i32 %retval.0
}

define i32 @anyNonZero64(<4 x i16> %a) #0 {
; CHECK-LABEL: anyNonZero64:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    umaxv.8b b0, v0
; CHECK-NEXT:    cmeq s0, s0, #0
; CHECK-NEXT:    fcmp s0, #0.0
; CHECK-NEXT:    b.vs LBB2_2
; CHECK-NEXT:  ; %bb.1: ; %if.then
; CHECK-NEXT:    b _bar
; CHECK-NEXT:  LBB2_2: ; %return
; CHECK-NEXT:    mov w0, #0 ; =0x0
; CHECK-NEXT:    ret

entry:
  %0 = bitcast <4 x i16> %a to <8 x i8>
  %vmaxv.i = tail call i32 @llvm.aarch64.neon.umaxv.i32.v8i8(<8 x i8> %0) #3
  %1 = trunc i32 %vmaxv.i to i8
  %tobool = icmp eq i8 %1, 0
  br i1 %tobool, label %return, label %if.then

if.then:                                          ; preds = %entry
  %call1 = tail call i32 @bar() #4
  br label %return

return:                                           ; preds = %entry, %if.then
  %retval.0 = phi i32 [ %call1, %if.then ], [ 0, %entry ]
  ret i32 %retval.0
}

define i32 @anyNonZero128(<8 x i16> %a) #0 {
; CHECK-LABEL: anyNonZero128:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    umaxv.16b b0, v0
; CHECK-NEXT:    cmeq s0, s0, #0
; CHECK-NEXT:    fcmp s0, #0.0
; CHECK-NEXT:    b.vs LBB3_2
; CHECK-NEXT:  ; %bb.1: ; %if.then
; CHECK-NEXT:    b _bar
; CHECK-NEXT:  LBB3_2: ; %return
; CHECK-NEXT:    mov w0, #0 ; =0x0
; CHECK-NEXT:    ret
entry:
  %0 = bitcast <8 x i16> %a to <16 x i8>
  %vmaxv.i = tail call i32 @llvm.aarch64.neon.umaxv.i32.v16i8(<16 x i8> %0) #3
  %1 = trunc i32 %vmaxv.i to i8
  %tobool = icmp eq i8 %1, 0
  br i1 %tobool, label %return, label %if.then

if.then:                                          ; preds = %entry
  %call1 = tail call i32 @bar() #4
  br label %return

return:                                           ; preds = %entry, %if.then
  %retval.0 = phi i32 [ %call1, %if.then ], [ 0, %entry ]
  ret i32 %retval.0
}

define i32 @allZero64(<4 x i16> %a) #0 {
; CHECK-LABEL: allZero64:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    umaxv.8b b0, v0
; CHECK-NEXT:    cmeq s0, s0, #0
; CHECK-NEXT:    fcmp s0, #0.0
; CHECK-NEXT:    b.vs LBB4_2
; CHECK-NEXT:  ; %bb.1: ; %return
; CHECK-NEXT:    mov w0, #0 ; =0x0
; CHECK-NEXT:    ret
; CHECK-NEXT:  LBB4_2: ; %if.then
; CHECK-NEXT:    b _bar
entry:
  %0 = bitcast <4 x i16> %a to <8 x i8>
  %vmaxv.i = tail call i32 @llvm.aarch64.neon.umaxv.i32.v8i8(<8 x i8> %0) #3
  %1 = trunc i32 %vmaxv.i to i8
  %tobool = icmp eq i8 %1, 0
  br i1 %tobool, label %if.then, label %return

if.then:                                          ; preds = %entry
  %call1 = tail call i32 @bar() #4
  br label %return

return:                                           ; preds = %entry, %if.then
  %retval.0 = phi i32 [ %call1, %if.then ], [ 0, %entry ]
  ret i32 %retval.0
}

define i32 @allZero128(<8 x i16> %a) #0 {
; CHECK-LABEL: allZero128:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    umaxv.16b b0, v0
; CHECK-NEXT:    cmeq s0, s0, #0
; CHECK-NEXT:    fcmp s0, #0.0
; CHECK-NEXT:    b.vs LBB5_2
; CHECK-NEXT:  ; %bb.1: ; %return
; CHECK-NEXT:    mov w0, #0 ; =0x0
; CHECK-NEXT:    ret
; CHECK-NEXT:  LBB5_2: ; %if.then
; CHECK-NEXT:    b _bar
entry:
  %0 = bitcast <8 x i16> %a to <16 x i8>
  %vmaxv.i = tail call i32 @llvm.aarch64.neon.umaxv.i32.v16i8(<16 x i8> %0) #3
  %1 = trunc i32 %vmaxv.i to i8
  %tobool = icmp eq i8 %1, 0
  br i1 %tobool, label %if.then, label %return

if.then:                                          ; preds = %entry
  %call1 = tail call i32 @bar() #4
  br label %return

return:                                           ; preds = %entry, %if.then
  %retval.0 = phi i32 [ %call1, %if.then ], [ 0, %entry ]
  ret i32 %retval.0
}

define i32 @allNonZero64(<4 x i16> %a) #0 {
; CHECK-LABEL: allNonZero64:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    uminv.8b b0, v0
; CHECK-NEXT:    cmeq s0, s0, #0
; CHECK-NEXT:    fcmp s0, #0.0
; CHECK-NEXT:    b.vs LBB6_2
; CHECK-NEXT:  ; %bb.1: ; %if.then
; CHECK-NEXT:    b _bar
; CHECK-NEXT:  LBB6_2: ; %return
; CHECK-NEXT:    mov w0, #0 ; =0x0
; CHECK-NEXT:    ret
entry:
  %0 = bitcast <4 x i16> %a to <8 x i8>
  %vminv.i = tail call i32 @llvm.aarch64.neon.uminv.i32.v8i8(<8 x i8> %0) #3
  %1 = trunc i32 %vminv.i to i8
  %tobool = icmp eq i8 %1, 0
  br i1 %tobool, label %return, label %if.then

if.then:                                          ; preds = %entry
  %call1 = tail call i32 @bar() #4
  br label %return

return:                                           ; preds = %entry, %if.then
  %retval.0 = phi i32 [ %call1, %if.then ], [ 0, %entry ]
  ret i32 %retval.0
}

define i32 @allNonZero128(<8 x i16> %a) #0 {
; CHECK-LABEL: allNonZero128:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    uminv.16b b0, v0
; CHECK-NEXT:    cmeq s0, s0, #0
; CHECK-NEXT:    fcmp s0, #0.0
; CHECK-NEXT:    b.vs LBB7_2
; CHECK-NEXT:  ; %bb.1: ; %if.then
; CHECK-NEXT:    b _bar
; CHECK-NEXT:  LBB7_2: ; %return
; CHECK-NEXT:    mov w0, #0 ; =0x0
; CHECK-NEXT:    ret
entry:
  %0 = bitcast <8 x i16> %a to <16 x i8>
  %vminv.i = tail call i32 @llvm.aarch64.neon.uminv.i32.v16i8(<16 x i8> %0) #3
  %1 = trunc i32 %vminv.i to i8
  %tobool = icmp eq i8 %1, 0
  br i1 %tobool, label %return, label %if.then

if.then:                                          ; preds = %entry
  %call1 = tail call i32 @bar() #4
  br label %return

return:                                           ; preds = %entry, %if.then
  %retval.0 = phi i32 [ %call1, %if.then ], [ 0, %entry ]
  ret i32 %retval.0
}

declare i32 @llvm.aarch64.neon.umaxv.i32.v16i8(<16 x i8>) #2

declare i32 @llvm.aarch64.neon.umaxv.i32.v8i8(<8 x i8>) #2

declare i32 @llvm.aarch64.neon.uminv.i32.v16i8(<16 x i8>) #2

declare i32 @llvm.aarch64.neon.uminv.i32.v8i8(<8 x i8>) #2

attributes #0 = { nounwind ssp "target-cpu"="cyclone" }
attributes #1 = { "target-cpu"="cyclone" }
attributes #2 = { nounwind readnone }
attributes #3 = { nounwind }
attributes #4 = { nobuiltin nounwind }
