; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=aarch64 -mattr=+sve2-bitperm | FileCheck %s --check-prefix=BITPERM
; RUN: llc < %s -mtriple=aarch64 -mattr=+sve2 | FileCheck %s --check-prefix=NOSVE2BITPERM

define i8 @bext_i8(i8 %val, i8 %mask) nounwind {
; BITPERM-LABEL: bext_i8:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    and w8, w0, #0xff
; BITPERM-NEXT:    and w9, w1, #0xff
; BITPERM-NEXT:    fmov s0, w8
; BITPERM-NEXT:    fmov s1, w9
; BITPERM-NEXT:    bext z0.s, z0.s, z1.s
; BITPERM-NEXT:    fmov w0, s0
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bext_i8:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    mvn w9, w1
; NOSVE2BITPERM-NEXT:    mov w8, #-1 // =0xffffffff
; NOSVE2BITPERM-NEXT:    and w10, w0, w1
; NOSVE2BITPERM-NEXT:    lsl w9, w9, #1
; NOSVE2BITPERM-NEXT:    fmov s0, w8
; NOSVE2BITPERM-NEXT:    fmov s1, w9
; NOSVE2BITPERM-NEXT:    pmul v1.8b, v1.8b, v0.8b
; NOSVE2BITPERM-NEXT:    fmov w8, s1
; NOSVE2BITPERM-NEXT:    bic w9, w9, w8
; NOSVE2BITPERM-NEXT:    and w8, w8, w1
; NOSVE2BITPERM-NEXT:    fmov s1, w9
; NOSVE2BITPERM-NEXT:    and w11, w10, w8
; NOSVE2BITPERM-NEXT:    eor w13, w1, w8
; NOSVE2BITPERM-NEXT:    and w8, w8, #0xfe
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11
; NOSVE2BITPERM-NEXT:    and w11, w11, #0xfe
; NOSVE2BITPERM-NEXT:    orr w8, w13, w8, lsr #1
; NOSVE2BITPERM-NEXT:    pmul v1.8b, v1.8b, v0.8b
; NOSVE2BITPERM-NEXT:    fmov w12, s1
; NOSVE2BITPERM-NEXT:    bic w9, w9, w12
; NOSVE2BITPERM-NEXT:    fmov s1, w9
; NOSVE2BITPERM-NEXT:    orr w9, w10, w11, lsr #1
; NOSVE2BITPERM-NEXT:    and w10, w12, w8
; NOSVE2BITPERM-NEXT:    eor w8, w8, w10
; NOSVE2BITPERM-NEXT:    and w11, w9, w10
; NOSVE2BITPERM-NEXT:    and w10, w10, #0xfc
; NOSVE2BITPERM-NEXT:    pmul v0.8b, v1.8b, v0.8b
; NOSVE2BITPERM-NEXT:    orr w8, w8, w10, lsr #2
; NOSVE2BITPERM-NEXT:    eor w9, w9, w11
; NOSVE2BITPERM-NEXT:    and w11, w11, #0xfc
; NOSVE2BITPERM-NEXT:    orr w9, w9, w11, lsr #2
; NOSVE2BITPERM-NEXT:    fmov w10, s0
; NOSVE2BITPERM-NEXT:    and w8, w10, w8
; NOSVE2BITPERM-NEXT:    and w8, w9, w8
; NOSVE2BITPERM-NEXT:    eor w9, w9, w8
; NOSVE2BITPERM-NEXT:    and w8, w8, #0xf0
; NOSVE2BITPERM-NEXT:    orr w0, w9, w8, lsr #4
; NOSVE2BITPERM-NEXT:    ret
  %res = call i8 @llvm.bext.i8(i8 %val, i8 %mask)
  ret i8 %res
}

define i8 @bdep_i8(i8 %val, i8 %mask) nounwind {
; BITPERM-LABEL: bdep_i8:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    and w8, w0, #0xff
; BITPERM-NEXT:    and w9, w1, #0xff
; BITPERM-NEXT:    fmov s0, w8
; BITPERM-NEXT:    fmov s1, w9
; BITPERM-NEXT:    bdep z0.s, z0.s, z1.s
; BITPERM-NEXT:    fmov w0, s0
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bdep_i8:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    mvn w9, w1
; NOSVE2BITPERM-NEXT:    mov w8, #-1 // =0xffffffff
; NOSVE2BITPERM-NEXT:    lsl w9, w9, #1
; NOSVE2BITPERM-NEXT:    fmov s0, w8
; NOSVE2BITPERM-NEXT:    fmov s1, w9
; NOSVE2BITPERM-NEXT:    pmul v1.8b, v1.8b, v0.8b
; NOSVE2BITPERM-NEXT:    fmov w8, s1
; NOSVE2BITPERM-NEXT:    bic w9, w9, w8
; NOSVE2BITPERM-NEXT:    and w8, w8, w1
; NOSVE2BITPERM-NEXT:    fmov s1, w9
; NOSVE2BITPERM-NEXT:    eor w11, w1, w8
; NOSVE2BITPERM-NEXT:    and w12, w8, #0xfe
; NOSVE2BITPERM-NEXT:    orr w11, w11, w12, lsr #1
; NOSVE2BITPERM-NEXT:    pmul v1.8b, v1.8b, v0.8b
; NOSVE2BITPERM-NEXT:    fmov w10, s1
; NOSVE2BITPERM-NEXT:    bic w9, w9, w10
; NOSVE2BITPERM-NEXT:    fmov s1, w9
; NOSVE2BITPERM-NEXT:    and w9, w10, w11
; NOSVE2BITPERM-NEXT:    eor w10, w11, w9
; NOSVE2BITPERM-NEXT:    and w11, w9, #0xfc
; NOSVE2BITPERM-NEXT:    orr w10, w10, w11, lsr #2
; NOSVE2BITPERM-NEXT:    pmul v0.8b, v1.8b, v0.8b
; NOSVE2BITPERM-NEXT:    fmov w11, s0
; NOSVE2BITPERM-NEXT:    and w10, w11, w10
; NOSVE2BITPERM-NEXT:    and w11, w10, w0, lsl #4
; NOSVE2BITPERM-NEXT:    bic w10, w0, w10
; NOSVE2BITPERM-NEXT:    orr w10, w10, w11
; NOSVE2BITPERM-NEXT:    and w11, w9, w10, lsl #2
; NOSVE2BITPERM-NEXT:    bic w9, w10, w9
; NOSVE2BITPERM-NEXT:    orr w9, w9, w11
; NOSVE2BITPERM-NEXT:    and w10, w8, w9, lsl #1
; NOSVE2BITPERM-NEXT:    bic w8, w9, w8
; NOSVE2BITPERM-NEXT:    orr w8, w8, w10
; NOSVE2BITPERM-NEXT:    and w0, w8, w1
; NOSVE2BITPERM-NEXT:    ret
  %res = call i8 @llvm.bdep.i8(i8 %val, i8 %mask)
  ret i8 %res
}

define i16 @bext_i16(i16 %val, i16 %mask) nounwind {
; BITPERM-LABEL: bext_i16:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    and w8, w0, #0xffff
; BITPERM-NEXT:    and w9, w1, #0xffff
; BITPERM-NEXT:    fmov s0, w8
; BITPERM-NEXT:    fmov s1, w9
; BITPERM-NEXT:    bext z0.s, z0.s, z1.s
; BITPERM-NEXT:    fmov w0, s0
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bext_i16:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    mvn w8, w1
; NOSVE2BITPERM-NEXT:    and w14, w0, w1
; NOSVE2BITPERM-NEXT:    lsl w9, w8, #1
; NOSVE2BITPERM-NEXT:    neg w11, w8, lsl #16
; NOSVE2BITPERM-NEXT:    eor w10, w9, w8, lsl #2
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #3
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #4
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #5
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #6
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #7
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #8
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #9
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #10
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #11
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #12
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #13
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #14
; NOSVE2BITPERM-NEXT:    eor w8, w10, w8, lsl #15
; NOSVE2BITPERM-NEXT:    eor w8, w8, w11
; NOSVE2BITPERM-NEXT:    bic w9, w9, w8
; NOSVE2BITPERM-NEXT:    and w8, w8, w1
; NOSVE2BITPERM-NEXT:    eor w10, w9, w9, lsl #1
; NOSVE2BITPERM-NEXT:    neg w11, w9, lsl #15
; NOSVE2BITPERM-NEXT:    eor w13, w1, w8
; NOSVE2BITPERM-NEXT:    and w15, w8, #0xfffe
; NOSVE2BITPERM-NEXT:    and w8, w14, w8
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #2
; NOSVE2BITPERM-NEXT:    orr w13, w13, w15, lsr #1
; NOSVE2BITPERM-NEXT:    eor w14, w14, w8
; NOSVE2BITPERM-NEXT:    and w8, w8, #0xfffe
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #3
; NOSVE2BITPERM-NEXT:    orr w8, w14, w8, lsr #1
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #4
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #5
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #6
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #7
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #8
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #9
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #10
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #11
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #12
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #13
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #14
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11
; NOSVE2BITPERM-NEXT:    bic w9, w9, w10
; NOSVE2BITPERM-NEXT:    and w10, w10, w13
; NOSVE2BITPERM-NEXT:    eor w11, w9, w9, lsl #1
; NOSVE2BITPERM-NEXT:    neg w12, w9, lsl #15
; NOSVE2BITPERM-NEXT:    and w14, w8, w10
; NOSVE2BITPERM-NEXT:    eor w13, w13, w10
; NOSVE2BITPERM-NEXT:    and w10, w10, #0xfffc
; NOSVE2BITPERM-NEXT:    eor w8, w8, w14
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #2
; NOSVE2BITPERM-NEXT:    and w14, w14, #0xfffc
; NOSVE2BITPERM-NEXT:    orr w10, w13, w10, lsr #2
; NOSVE2BITPERM-NEXT:    orr w8, w8, w14, lsr #2
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #3
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #4
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #5
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #6
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #7
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #8
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #9
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #10
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #11
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #12
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #13
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #14
; NOSVE2BITPERM-NEXT:    eor w11, w11, w12
; NOSVE2BITPERM-NEXT:    bic w9, w9, w11
; NOSVE2BITPERM-NEXT:    and w11, w11, w10
; NOSVE2BITPERM-NEXT:    eor w12, w9, w9, lsl #1
; NOSVE2BITPERM-NEXT:    and w13, w8, w11
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11
; NOSVE2BITPERM-NEXT:    eor w8, w8, w13
; NOSVE2BITPERM-NEXT:    and w13, w13, #0xfff0
; NOSVE2BITPERM-NEXT:    and w11, w11, #0xfff0
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #2
; NOSVE2BITPERM-NEXT:    orr w8, w8, w13, lsr #4
; NOSVE2BITPERM-NEXT:    orr w10, w10, w11, lsr #4
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #3
; NOSVE2BITPERM-NEXT:    and w10, w8, w10
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #4
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #5
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #6
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #7
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #8
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #9
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #10
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #11
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #12
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #13
; NOSVE2BITPERM-NEXT:    eor w11, w12, w9, lsl #14
; NOSVE2BITPERM-NEXT:    neg w9, w9, lsl #15
; NOSVE2BITPERM-NEXT:    eor w9, w11, w9
; NOSVE2BITPERM-NEXT:    and w9, w10, w9
; NOSVE2BITPERM-NEXT:    eor w8, w8, w9
; NOSVE2BITPERM-NEXT:    and w9, w9, #0xff00
; NOSVE2BITPERM-NEXT:    orr w0, w8, w9, lsr #8
; NOSVE2BITPERM-NEXT:    ret
  %res = call i16 @llvm.bext.i16(i16 %val, i16 %mask)
  ret i16 %res
}

define i16 @bdep_i16(i16 %val, i16 %mask) nounwind {
; BITPERM-LABEL: bdep_i16:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    and w8, w0, #0xffff
; BITPERM-NEXT:    and w9, w1, #0xffff
; BITPERM-NEXT:    fmov s0, w8
; BITPERM-NEXT:    fmov s1, w9
; BITPERM-NEXT:    bdep z0.s, z0.s, z1.s
; BITPERM-NEXT:    fmov w0, s0
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bdep_i16:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    mvn w8, w1
; NOSVE2BITPERM-NEXT:    lsl w9, w8, #1
; NOSVE2BITPERM-NEXT:    neg w11, w8, lsl #16
; NOSVE2BITPERM-NEXT:    eor w10, w9, w8, lsl #2
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #3
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #4
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #5
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #6
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #7
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #8
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #9
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #10
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #11
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #12
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #13
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #14
; NOSVE2BITPERM-NEXT:    eor w8, w10, w8, lsl #15
; NOSVE2BITPERM-NEXT:    eor w8, w8, w11
; NOSVE2BITPERM-NEXT:    bic w9, w9, w8
; NOSVE2BITPERM-NEXT:    and w8, w8, w1
; NOSVE2BITPERM-NEXT:    eor w10, w9, w9, lsl #1
; NOSVE2BITPERM-NEXT:    neg w11, w9, lsl #15
; NOSVE2BITPERM-NEXT:    eor w13, w1, w8
; NOSVE2BITPERM-NEXT:    and w14, w8, #0xfffe
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #2
; NOSVE2BITPERM-NEXT:    orr w13, w13, w14, lsr #1
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #3
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #4
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #5
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #6
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #7
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #8
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #9
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #10
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #11
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #12
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #13
; NOSVE2BITPERM-NEXT:    eor w10, w10, w9, lsl #14
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11
; NOSVE2BITPERM-NEXT:    bic w9, w9, w10
; NOSVE2BITPERM-NEXT:    and w10, w10, w13
; NOSVE2BITPERM-NEXT:    eor w11, w9, w9, lsl #1
; NOSVE2BITPERM-NEXT:    neg w12, w9, lsl #15
; NOSVE2BITPERM-NEXT:    eor w13, w13, w10
; NOSVE2BITPERM-NEXT:    and w14, w10, #0xfffc
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #2
; NOSVE2BITPERM-NEXT:    orr w13, w13, w14, lsr #2
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #3
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #4
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #5
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #6
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #7
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #8
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #9
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #10
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #11
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #12
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #13
; NOSVE2BITPERM-NEXT:    eor w11, w11, w9, lsl #14
; NOSVE2BITPERM-NEXT:    eor w11, w11, w12
; NOSVE2BITPERM-NEXT:    bic w9, w9, w11
; NOSVE2BITPERM-NEXT:    and w11, w11, w13
; NOSVE2BITPERM-NEXT:    eor w12, w9, w9, lsl #1
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11
; NOSVE2BITPERM-NEXT:    and w14, w11, #0xfff0
; NOSVE2BITPERM-NEXT:    orr w13, w13, w14, lsr #4
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #2
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #3
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #4
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #5
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #6
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #7
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #8
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #9
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #10
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #11
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #12
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #13
; NOSVE2BITPERM-NEXT:    eor w12, w12, w9, lsl #14
; NOSVE2BITPERM-NEXT:    neg w9, w9, lsl #15
; NOSVE2BITPERM-NEXT:    eor w9, w12, w9
; NOSVE2BITPERM-NEXT:    and w9, w9, w13
; NOSVE2BITPERM-NEXT:    and w12, w9, w0, lsl #8
; NOSVE2BITPERM-NEXT:    bic w9, w0, w9
; NOSVE2BITPERM-NEXT:    orr w9, w9, w12
; NOSVE2BITPERM-NEXT:    and w12, w11, w9, lsl #4
; NOSVE2BITPERM-NEXT:    bic w9, w9, w11
; NOSVE2BITPERM-NEXT:    orr w9, w9, w12
; NOSVE2BITPERM-NEXT:    and w11, w10, w9, lsl #2
; NOSVE2BITPERM-NEXT:    bic w9, w9, w10
; NOSVE2BITPERM-NEXT:    orr w9, w9, w11
; NOSVE2BITPERM-NEXT:    and w10, w8, w9, lsl #1
; NOSVE2BITPERM-NEXT:    bic w8, w9, w8
; NOSVE2BITPERM-NEXT:    orr w8, w8, w10
; NOSVE2BITPERM-NEXT:    and w0, w8, w1
; NOSVE2BITPERM-NEXT:    ret
  %res = call i16 @llvm.bdep.i16(i16 %val, i16 %mask)
  ret i16 %res
}

define i32 @bext_i32(i32 %val, i32 %mask) nounwind {
; BITPERM-LABEL: bext_i32:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    fmov s0, w0
; BITPERM-NEXT:    fmov s1, w1
; BITPERM-NEXT:    bext z0.s, z0.s, z1.s
; BITPERM-NEXT:    fmov w0, s0
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bext_i32:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    mvn w8, w1
; NOSVE2BITPERM-NEXT:    and w14, w0, w1
; NOSVE2BITPERM-NEXT:    lsl w9, w8, #1
; NOSVE2BITPERM-NEXT:    eor w10, w9, w8, lsl #2
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #3
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #4
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #5
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #6
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #7
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #8
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #9
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #10
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #11
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #12
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #13
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #14
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #15
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #16
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #17
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #18
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #19
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #20
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #21
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #22
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #23
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #24
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #25
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #26
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #27
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #28
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #29
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #30
; NOSVE2BITPERM-NEXT:    eor w8, w10, w8, lsl #31
; NOSVE2BITPERM-NEXT:    bic w10, w9, w8
; NOSVE2BITPERM-NEXT:    and w8, w8, w1
; NOSVE2BITPERM-NEXT:    eor w9, w10, w10, lsl #1
; NOSVE2BITPERM-NEXT:    and w15, w14, w8
; NOSVE2BITPERM-NEXT:    eor w16, w1, w8
; NOSVE2BITPERM-NEXT:    orr w8, w16, w8, lsr #1
; NOSVE2BITPERM-NEXT:    eor w14, w14, w15
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #2
; NOSVE2BITPERM-NEXT:    orr w14, w14, w15, lsr #1
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #3
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #4
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #5
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #6
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #7
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #8
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #9
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #10
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #11
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #12
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #13
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #14
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #15
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #16
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #17
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #18
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #19
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #20
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #21
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #22
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #23
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #24
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #25
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #26
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #27
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #28
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #29
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #30
; NOSVE2BITPERM-NEXT:    bic w11, w10, w9
; NOSVE2BITPERM-NEXT:    and w9, w9, w8
; NOSVE2BITPERM-NEXT:    eor w10, w11, w11, lsl #1
; NOSVE2BITPERM-NEXT:    and w15, w14, w9
; NOSVE2BITPERM-NEXT:    eor w8, w8, w9
; NOSVE2BITPERM-NEXT:    orr w8, w8, w9, lsr #2
; NOSVE2BITPERM-NEXT:    eor w9, w14, w15
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #2
; NOSVE2BITPERM-NEXT:    orr w9, w9, w15, lsr #2
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #3
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #4
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #5
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #6
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #7
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #8
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #9
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #10
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #11
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #12
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #13
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #14
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #15
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #16
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #17
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #18
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #19
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #20
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #21
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #22
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #23
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #24
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #25
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #26
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #27
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #28
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #29
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #30
; NOSVE2BITPERM-NEXT:    bic w11, w11, w10
; NOSVE2BITPERM-NEXT:    and w10, w10, w8
; NOSVE2BITPERM-NEXT:    eor w12, w11, w11, lsl #1
; NOSVE2BITPERM-NEXT:    and w14, w9, w10
; NOSVE2BITPERM-NEXT:    eor w8, w8, w10
; NOSVE2BITPERM-NEXT:    orr w8, w8, w10, lsr #4
; NOSVE2BITPERM-NEXT:    eor w9, w9, w14
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #2
; NOSVE2BITPERM-NEXT:    orr w9, w9, w14, lsr #4
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #3
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #4
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #5
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #6
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #7
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #8
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #9
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #10
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #11
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #12
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #13
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #14
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #15
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #16
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #17
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #18
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #19
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #20
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #21
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #22
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #23
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #24
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #25
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #26
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #27
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #28
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #29
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #30
; NOSVE2BITPERM-NEXT:    bic w11, w11, w12
; NOSVE2BITPERM-NEXT:    and w12, w12, w8
; NOSVE2BITPERM-NEXT:    eor w13, w11, w11, lsl #1
; NOSVE2BITPERM-NEXT:    eor w8, w8, w12
; NOSVE2BITPERM-NEXT:    orr w8, w8, w12, lsr #8
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #2
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #3
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #4
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #5
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #6
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #7
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #8
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #9
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #10
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #11
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #12
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #13
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #14
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #15
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #16
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #17
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #18
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #19
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #20
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #21
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #22
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #23
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #24
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #25
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #26
; NOSVE2BITPERM-NEXT:    eor w10, w13, w11, lsl #27
; NOSVE2BITPERM-NEXT:    and w13, w9, w12
; NOSVE2BITPERM-NEXT:    eor w9, w9, w13
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #28
; NOSVE2BITPERM-NEXT:    orr w9, w9, w13, lsr #8
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #29
; NOSVE2BITPERM-NEXT:    and w8, w9, w8
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #30
; NOSVE2BITPERM-NEXT:    and w8, w8, w10
; NOSVE2BITPERM-NEXT:    eor w9, w9, w8
; NOSVE2BITPERM-NEXT:    orr w0, w9, w8, lsr #16
; NOSVE2BITPERM-NEXT:    ret
  %res = call i32 @llvm.bext.i32(i32 %val, i32 %mask)
  ret i32 %res
}

define i32 @bdep_i32(i32 %val, i32 %mask) nounwind {
; BITPERM-LABEL: bdep_i32:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    fmov s0, w0
; BITPERM-NEXT:    fmov s1, w1
; BITPERM-NEXT:    bdep z0.s, z0.s, z1.s
; BITPERM-NEXT:    fmov w0, s0
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bdep_i32:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    mvn w8, w1
; NOSVE2BITPERM-NEXT:    lsl w9, w8, #1
; NOSVE2BITPERM-NEXT:    eor w10, w9, w8, lsl #2
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #3
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #4
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #5
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #6
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #7
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #8
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #9
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #10
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #11
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #12
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #13
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #14
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #15
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #16
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #17
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #18
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #19
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #20
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #21
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #22
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #23
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #24
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #25
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #26
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #27
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #28
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #29
; NOSVE2BITPERM-NEXT:    eor w10, w10, w8, lsl #30
; NOSVE2BITPERM-NEXT:    eor w8, w10, w8, lsl #31
; NOSVE2BITPERM-NEXT:    bic w10, w9, w8
; NOSVE2BITPERM-NEXT:    and w8, w8, w1
; NOSVE2BITPERM-NEXT:    eor w9, w10, w10, lsl #1
; NOSVE2BITPERM-NEXT:    eor w14, w1, w8
; NOSVE2BITPERM-NEXT:    orr w14, w14, w8, lsr #1
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #2
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #3
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #4
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #5
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #6
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #7
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #8
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #9
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #10
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #11
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #12
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #13
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #14
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #15
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #16
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #17
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #18
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #19
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #20
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #21
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #22
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #23
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #24
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #25
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #26
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #27
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #28
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #29
; NOSVE2BITPERM-NEXT:    eor w9, w9, w10, lsl #30
; NOSVE2BITPERM-NEXT:    bic w11, w10, w9
; NOSVE2BITPERM-NEXT:    and w9, w9, w14
; NOSVE2BITPERM-NEXT:    eor w10, w11, w11, lsl #1
; NOSVE2BITPERM-NEXT:    eor w14, w14, w9
; NOSVE2BITPERM-NEXT:    orr w14, w14, w9, lsr #2
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #2
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #3
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #4
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #5
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #6
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #7
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #8
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #9
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #10
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #11
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #12
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #13
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #14
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #15
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #16
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #17
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #18
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #19
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #20
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #21
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #22
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #23
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #24
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #25
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #26
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #27
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #28
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #29
; NOSVE2BITPERM-NEXT:    eor w10, w10, w11, lsl #30
; NOSVE2BITPERM-NEXT:    bic w11, w11, w10
; NOSVE2BITPERM-NEXT:    and w10, w10, w14
; NOSVE2BITPERM-NEXT:    eor w12, w11, w11, lsl #1
; NOSVE2BITPERM-NEXT:    eor w14, w14, w10
; NOSVE2BITPERM-NEXT:    orr w14, w14, w10, lsr #4
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #2
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #3
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #4
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #5
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #6
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #7
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #8
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #9
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #10
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #11
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #12
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #13
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #14
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #15
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #16
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #17
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #18
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #19
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #20
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #21
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #22
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #23
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #24
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #25
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #26
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #27
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #28
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #29
; NOSVE2BITPERM-NEXT:    eor w12, w12, w11, lsl #30
; NOSVE2BITPERM-NEXT:    bic w11, w11, w12
; NOSVE2BITPERM-NEXT:    and w12, w12, w14
; NOSVE2BITPERM-NEXT:    eor w13, w11, w11, lsl #1
; NOSVE2BITPERM-NEXT:    eor w14, w14, w12
; NOSVE2BITPERM-NEXT:    orr w14, w14, w12, lsr #8
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #2
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #3
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #4
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #5
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #6
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #7
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #8
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #9
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #10
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #11
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #12
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #13
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #14
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #15
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #16
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #17
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #18
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #19
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #20
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #21
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #22
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #23
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #24
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #25
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #26
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #27
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #28
; NOSVE2BITPERM-NEXT:    eor w13, w13, w11, lsl #29
; NOSVE2BITPERM-NEXT:    eor w11, w13, w11, lsl #30
; NOSVE2BITPERM-NEXT:    and w11, w11, w14
; NOSVE2BITPERM-NEXT:    and w13, w11, w0, lsl #16
; NOSVE2BITPERM-NEXT:    bic w11, w0, w11
; NOSVE2BITPERM-NEXT:    orr w11, w11, w13
; NOSVE2BITPERM-NEXT:    and w13, w12, w11, lsl #8
; NOSVE2BITPERM-NEXT:    bic w11, w11, w12
; NOSVE2BITPERM-NEXT:    orr w11, w11, w13
; NOSVE2BITPERM-NEXT:    and w12, w10, w11, lsl #4
; NOSVE2BITPERM-NEXT:    bic w10, w11, w10
; NOSVE2BITPERM-NEXT:    orr w10, w10, w12
; NOSVE2BITPERM-NEXT:    and w11, w9, w10, lsl #2
; NOSVE2BITPERM-NEXT:    bic w9, w10, w9
; NOSVE2BITPERM-NEXT:    orr w9, w9, w11
; NOSVE2BITPERM-NEXT:    and w10, w8, w9, lsl #1
; NOSVE2BITPERM-NEXT:    bic w8, w9, w8
; NOSVE2BITPERM-NEXT:    orr w8, w8, w10
; NOSVE2BITPERM-NEXT:    and w0, w8, w1
; NOSVE2BITPERM-NEXT:    ret
  %res = call i32 @llvm.bdep.i32(i32 %val, i32 %mask)
  ret i32 %res
}

define i64 @bext_i64(i64 %val, i64 %mask) nounwind {
; BITPERM-LABEL: bext_i64:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    fmov d0, x0
; BITPERM-NEXT:    fmov d1, x1
; BITPERM-NEXT:    bext z0.d, z0.d, z1.d
; BITPERM-NEXT:    fmov x0, d0
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bext_i64:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    mvn x8, x1
; NOSVE2BITPERM-NEXT:    and x15, x0, x1
; NOSVE2BITPERM-NEXT:    lsl x9, x8, #1
; NOSVE2BITPERM-NEXT:    eor x10, x9, x8, lsl #2
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #3
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #4
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #5
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #6
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #7
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #8
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #9
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #10
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #11
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #12
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #13
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #14
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #15
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #16
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #17
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #18
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #19
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #20
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #21
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #22
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #23
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #24
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #25
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #26
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #27
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #28
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #29
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #30
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #31
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #32
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #33
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #34
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #35
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #36
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #37
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #38
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #39
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #40
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #41
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #42
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #43
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #44
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #45
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #46
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #47
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #48
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #49
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #50
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #51
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #52
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #53
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #54
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #55
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #56
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #57
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #58
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #59
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #60
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #61
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #62
; NOSVE2BITPERM-NEXT:    eor x8, x10, x8, lsl #63
; NOSVE2BITPERM-NEXT:    bic x10, x9, x8
; NOSVE2BITPERM-NEXT:    and x8, x8, x1
; NOSVE2BITPERM-NEXT:    eor x9, x10, x10, lsl #1
; NOSVE2BITPERM-NEXT:    and x16, x15, x8
; NOSVE2BITPERM-NEXT:    eor x17, x1, x8
; NOSVE2BITPERM-NEXT:    orr x8, x17, x8, lsr #1
; NOSVE2BITPERM-NEXT:    eor x15, x15, x16
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #2
; NOSVE2BITPERM-NEXT:    orr x15, x15, x16, lsr #1
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #3
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #4
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #5
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #6
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #7
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #8
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #9
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #10
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #11
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #12
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #13
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #14
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #15
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #16
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #17
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #18
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #19
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #20
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #21
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #22
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #23
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #24
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #25
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #26
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #27
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #28
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #29
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #30
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #31
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #32
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #33
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #34
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #35
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #36
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #37
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #38
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #39
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #40
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #41
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #42
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #43
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #44
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #45
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #46
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #47
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #48
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #49
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #50
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #51
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #52
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #53
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #54
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #55
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #56
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #57
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #58
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #59
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #60
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #61
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #62
; NOSVE2BITPERM-NEXT:    bic x11, x10, x9
; NOSVE2BITPERM-NEXT:    and x9, x9, x8
; NOSVE2BITPERM-NEXT:    eor x10, x11, x11, lsl #1
; NOSVE2BITPERM-NEXT:    and x16, x15, x9
; NOSVE2BITPERM-NEXT:    eor x8, x8, x9
; NOSVE2BITPERM-NEXT:    orr x8, x8, x9, lsr #2
; NOSVE2BITPERM-NEXT:    eor x9, x15, x16
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #2
; NOSVE2BITPERM-NEXT:    orr x9, x9, x16, lsr #2
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #3
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #4
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #5
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #6
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #7
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #8
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #9
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #10
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #11
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #12
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #13
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #14
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #15
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #16
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #17
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #18
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #19
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #20
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #21
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #22
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #23
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #24
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #25
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #26
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #27
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #28
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #29
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #30
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #31
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #32
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #33
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #34
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #35
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #36
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #37
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #38
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #39
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #40
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #41
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #42
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #43
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #44
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #45
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #46
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #47
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #48
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #49
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #50
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #51
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #52
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #53
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #54
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #55
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #56
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #57
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #58
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #59
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #60
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #61
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #62
; NOSVE2BITPERM-NEXT:    bic x12, x11, x10
; NOSVE2BITPERM-NEXT:    and x10, x10, x8
; NOSVE2BITPERM-NEXT:    eor x11, x12, x12, lsl #1
; NOSVE2BITPERM-NEXT:    and x15, x9, x10
; NOSVE2BITPERM-NEXT:    eor x8, x8, x10
; NOSVE2BITPERM-NEXT:    orr x8, x8, x10, lsr #4
; NOSVE2BITPERM-NEXT:    eor x9, x9, x15
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #2
; NOSVE2BITPERM-NEXT:    orr x9, x9, x15, lsr #4
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #3
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #4
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #5
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #6
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #7
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #8
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #9
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #10
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #11
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #12
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #13
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #14
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #15
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #16
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #17
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #18
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #19
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #20
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #21
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #22
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #23
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #24
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #25
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #26
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #27
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #28
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #29
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #30
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #31
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #32
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #33
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #34
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #35
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #36
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #37
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #38
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #39
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #40
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #41
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #42
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #43
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #44
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #45
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #46
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #47
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #48
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #49
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #50
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #51
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #52
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #53
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #54
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #55
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #56
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #57
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #58
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #59
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #60
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #61
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #62
; NOSVE2BITPERM-NEXT:    bic x12, x12, x11
; NOSVE2BITPERM-NEXT:    and x11, x11, x8
; NOSVE2BITPERM-NEXT:    eor x13, x12, x12, lsl #1
; NOSVE2BITPERM-NEXT:    eor x8, x8, x11
; NOSVE2BITPERM-NEXT:    orr x8, x8, x11, lsr #8
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #2
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #3
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #4
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #5
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #6
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #7
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #8
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #9
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #10
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #11
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #12
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #13
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #14
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #15
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #16
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #17
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #18
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #19
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #20
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #21
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #22
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #23
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #24
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #25
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #26
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #27
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #28
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #29
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #30
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #31
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #32
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #33
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #34
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #35
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #36
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #37
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #38
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #39
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #40
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #41
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #42
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #43
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #44
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #45
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #46
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #47
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #48
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #49
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #50
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #51
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #52
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #53
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #54
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #55
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #56
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #57
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #58
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #59
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #60
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #61
; NOSVE2BITPERM-NEXT:    eor x13, x13, x12, lsl #62
; NOSVE2BITPERM-NEXT:    bic x12, x12, x13
; NOSVE2BITPERM-NEXT:    eor x14, x12, x12, lsl #1
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #2
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #3
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #4
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #5
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #6
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #7
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #8
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #9
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #10
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #11
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #12
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #13
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #14
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #15
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #16
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #17
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #18
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #19
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #20
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #21
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #22
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #23
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #24
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #25
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #26
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #27
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #28
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #29
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #30
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #31
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #32
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #33
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #34
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #35
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #36
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #37
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #38
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #39
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #40
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #41
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #42
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #43
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #44
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #45
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #46
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #47
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #48
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #49
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #50
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #51
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #52
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #53
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #54
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #55
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #56
; NOSVE2BITPERM-NEXT:    eor x14, x14, x12, lsl #57
; NOSVE2BITPERM-NEXT:    eor x10, x14, x12, lsl #58
; NOSVE2BITPERM-NEXT:    and x14, x9, x11
; NOSVE2BITPERM-NEXT:    and x11, x13, x8
; NOSVE2BITPERM-NEXT:    eor x9, x9, x14
; NOSVE2BITPERM-NEXT:    eor x8, x8, x11
; NOSVE2BITPERM-NEXT:    eor x10, x10, x12, lsl #59
; NOSVE2BITPERM-NEXT:    orr x9, x9, x14, lsr #8
; NOSVE2BITPERM-NEXT:    orr x8, x8, x11, lsr #16
; NOSVE2BITPERM-NEXT:    eor x10, x10, x12, lsl #60
; NOSVE2BITPERM-NEXT:    and x13, x9, x11
; NOSVE2BITPERM-NEXT:    eor x9, x9, x13
; NOSVE2BITPERM-NEXT:    eor x10, x10, x12, lsl #61
; NOSVE2BITPERM-NEXT:    orr x9, x9, x13, lsr #16
; NOSVE2BITPERM-NEXT:    eor x10, x10, x12, lsl #62
; NOSVE2BITPERM-NEXT:    and x8, x9, x8
; NOSVE2BITPERM-NEXT:    eor x10, x10, x12, lsl #63
; NOSVE2BITPERM-NEXT:    and x8, x8, x10
; NOSVE2BITPERM-NEXT:    eor x9, x9, x8
; NOSVE2BITPERM-NEXT:    orr x0, x9, x8, lsr #32
; NOSVE2BITPERM-NEXT:    ret
  %res = call i64 @llvm.bext.i64(i64 %val, i64 %mask)
  ret i64 %res
}

define i64 @bdep_i64(i64 %val, i64 %mask) nounwind {
; BITPERM-LABEL: bdep_i64:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    fmov d0, x0
; BITPERM-NEXT:    fmov d1, x1
; BITPERM-NEXT:    bdep z0.d, z0.d, z1.d
; BITPERM-NEXT:    fmov x0, d0
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bdep_i64:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    mvn x8, x1
; NOSVE2BITPERM-NEXT:    lsl x9, x8, #1
; NOSVE2BITPERM-NEXT:    eor x10, x9, x8, lsl #2
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #3
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #4
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #5
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #6
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #7
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #8
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #9
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #10
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #11
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #12
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #13
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #14
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #15
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #16
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #17
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #18
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #19
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #20
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #21
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #22
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #23
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #24
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #25
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #26
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #27
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #28
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #29
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #30
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #31
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #32
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #33
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #34
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #35
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #36
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #37
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #38
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #39
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #40
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #41
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #42
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #43
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #44
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #45
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #46
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #47
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #48
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #49
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #50
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #51
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #52
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #53
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #54
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #55
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #56
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #57
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #58
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #59
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #60
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #61
; NOSVE2BITPERM-NEXT:    eor x10, x10, x8, lsl #62
; NOSVE2BITPERM-NEXT:    eor x8, x10, x8, lsl #63
; NOSVE2BITPERM-NEXT:    bic x10, x9, x8
; NOSVE2BITPERM-NEXT:    and x8, x8, x1
; NOSVE2BITPERM-NEXT:    eor x9, x10, x10, lsl #1
; NOSVE2BITPERM-NEXT:    eor x15, x1, x8
; NOSVE2BITPERM-NEXT:    orr x15, x15, x8, lsr #1
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #2
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #3
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #4
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #5
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #6
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #7
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #8
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #9
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #10
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #11
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #12
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #13
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #14
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #15
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #16
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #17
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #18
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #19
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #20
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #21
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #22
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #23
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #24
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #25
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #26
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #27
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #28
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #29
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #30
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #31
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #32
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #33
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #34
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #35
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #36
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #37
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #38
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #39
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #40
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #41
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #42
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #43
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #44
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #45
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #46
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #47
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #48
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #49
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #50
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #51
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #52
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #53
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #54
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #55
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #56
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #57
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #58
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #59
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #60
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #61
; NOSVE2BITPERM-NEXT:    eor x9, x9, x10, lsl #62
; NOSVE2BITPERM-NEXT:    bic x11, x10, x9
; NOSVE2BITPERM-NEXT:    and x9, x9, x15
; NOSVE2BITPERM-NEXT:    eor x10, x11, x11, lsl #1
; NOSVE2BITPERM-NEXT:    eor x15, x15, x9
; NOSVE2BITPERM-NEXT:    orr x15, x15, x9, lsr #2
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #2
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #3
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #4
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #5
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #6
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #7
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #8
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #9
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #10
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #11
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #12
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #13
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #14
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #15
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #16
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #17
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #18
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #19
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #20
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #21
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #22
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #23
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #24
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #25
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #26
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #27
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #28
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #29
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #30
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #31
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #32
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #33
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #34
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #35
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #36
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #37
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #38
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #39
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #40
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #41
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #42
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #43
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #44
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #45
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #46
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #47
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #48
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #49
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #50
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #51
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #52
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #53
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #54
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #55
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #56
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #57
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #58
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #59
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #60
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #61
; NOSVE2BITPERM-NEXT:    eor x10, x10, x11, lsl #62
; NOSVE2BITPERM-NEXT:    bic x12, x11, x10
; NOSVE2BITPERM-NEXT:    and x10, x10, x15
; NOSVE2BITPERM-NEXT:    eor x11, x12, x12, lsl #1
; NOSVE2BITPERM-NEXT:    eor x15, x15, x10
; NOSVE2BITPERM-NEXT:    orr x15, x15, x10, lsr #4
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #2
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #3
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #4
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #5
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #6
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #7
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #8
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #9
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #10
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #11
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #12
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #13
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #14
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #15
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #16
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #17
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #18
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #19
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #20
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #21
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #22
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #23
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #24
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #25
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #26
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #27
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #28
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #29
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #30
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #31
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #32
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #33
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #34
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #35
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #36
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #37
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #38
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #39
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #40
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #41
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #42
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #43
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #44
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #45
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #46
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #47
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #48
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #49
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #50
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #51
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #52
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #53
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #54
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #55
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #56
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #57
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #58
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #59
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #60
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #61
; NOSVE2BITPERM-NEXT:    eor x11, x11, x12, lsl #62
; NOSVE2BITPERM-NEXT:    bic x13, x12, x11
; NOSVE2BITPERM-NEXT:    and x11, x11, x15
; NOSVE2BITPERM-NEXT:    eor x12, x13, x13, lsl #1
; NOSVE2BITPERM-NEXT:    eor x15, x15, x11
; NOSVE2BITPERM-NEXT:    orr x15, x15, x11, lsr #8
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #2
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #3
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #4
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #5
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #6
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #7
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #8
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #9
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #10
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #11
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #12
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #13
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #14
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #15
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #16
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #17
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #18
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #19
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #20
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #21
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #22
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #23
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #24
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #25
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #26
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #27
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #28
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #29
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #30
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #31
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #32
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #33
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #34
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #35
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #36
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #37
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #38
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #39
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #40
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #41
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #42
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #43
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #44
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #45
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #46
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #47
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #48
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #49
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #50
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #51
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #52
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #53
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #54
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #55
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #56
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #57
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #58
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #59
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #60
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #61
; NOSVE2BITPERM-NEXT:    eor x12, x12, x13, lsl #62
; NOSVE2BITPERM-NEXT:    bic x13, x13, x12
; NOSVE2BITPERM-NEXT:    and x12, x12, x15
; NOSVE2BITPERM-NEXT:    eor x14, x13, x13, lsl #1
; NOSVE2BITPERM-NEXT:    eor x15, x15, x12
; NOSVE2BITPERM-NEXT:    orr x15, x15, x12, lsr #16
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #2
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #3
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #4
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #5
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #6
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #7
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #8
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #9
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #10
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #11
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #12
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #13
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #14
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #15
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #16
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #17
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #18
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #19
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #20
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #21
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #22
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #23
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #24
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #25
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #26
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #27
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #28
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #29
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #30
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #31
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #32
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #33
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #34
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #35
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #36
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #37
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #38
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #39
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #40
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #41
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #42
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #43
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #44
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #45
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #46
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #47
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #48
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #49
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #50
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #51
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #52
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #53
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #54
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #55
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #56
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #57
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #58
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #59
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #60
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #61
; NOSVE2BITPERM-NEXT:    eor x14, x14, x13, lsl #62
; NOSVE2BITPERM-NEXT:    eor x13, x14, x13, lsl #63
; NOSVE2BITPERM-NEXT:    and x13, x13, x15
; NOSVE2BITPERM-NEXT:    and x14, x13, x0, lsl #32
; NOSVE2BITPERM-NEXT:    bic x13, x0, x13
; NOSVE2BITPERM-NEXT:    orr x13, x13, x14
; NOSVE2BITPERM-NEXT:    and x14, x12, x13, lsl #16
; NOSVE2BITPERM-NEXT:    bic x12, x13, x12
; NOSVE2BITPERM-NEXT:    orr x12, x12, x14
; NOSVE2BITPERM-NEXT:    and x13, x11, x12, lsl #8
; NOSVE2BITPERM-NEXT:    bic x11, x12, x11
; NOSVE2BITPERM-NEXT:    orr x11, x11, x13
; NOSVE2BITPERM-NEXT:    and x12, x10, x11, lsl #4
; NOSVE2BITPERM-NEXT:    bic x10, x11, x10
; NOSVE2BITPERM-NEXT:    orr x10, x10, x12
; NOSVE2BITPERM-NEXT:    and x11, x9, x10, lsl #2
; NOSVE2BITPERM-NEXT:    bic x9, x10, x9
; NOSVE2BITPERM-NEXT:    orr x9, x9, x11
; NOSVE2BITPERM-NEXT:    and x10, x8, x9, lsl #1
; NOSVE2BITPERM-NEXT:    bic x8, x9, x8
; NOSVE2BITPERM-NEXT:    orr x8, x8, x10
; NOSVE2BITPERM-NEXT:    and x0, x8, x1
; NOSVE2BITPERM-NEXT:    ret
  %res = call i64 @llvm.bdep.i64(i64 %val, i64 %mask)
  ret i64 %res
}

define <vscale x 16 x i8> @bext_nxv16i8(<vscale x 16 x i8> %val, <vscale x 16 x i8> %mask) nounwind {
; BITPERM-LABEL: bext_nxv16i8:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    bext z0.b, z0.b, z1.b
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bext_nxv16i8:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    movprfx z3, z1
; NOSVE2BITPERM-NEXT:    subr z3.b, z3.b, #255 // =0xff
; NOSVE2BITPERM-NEXT:    mov z2.b, #-1 // =0xffffffffffffffff
; NOSVE2BITPERM-NEXT:    and z0.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    lsl z3.b, z3.b, #1
; NOSVE2BITPERM-NEXT:    pmul z4.b, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    and z5.d, z4.d, z1.d
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z4.d
; NOSVE2BITPERM-NEXT:    and z4.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    eor z1.d, z1.d, z5.d
; NOSVE2BITPERM-NEXT:    lsr z5.b, z5.b, #1
; NOSVE2BITPERM-NEXT:    pmul z6.b, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    eor z0.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    lsr z4.b, z4.b, #1
; NOSVE2BITPERM-NEXT:    orr z1.d, z1.d, z5.d
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z6.d
; NOSVE2BITPERM-NEXT:    orr z0.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    and z4.d, z6.d, z1.d
; NOSVE2BITPERM-NEXT:    pmul z2.b, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    and z5.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    eor z1.d, z1.d, z4.d
; NOSVE2BITPERM-NEXT:    lsr z4.b, z4.b, #2
; NOSVE2BITPERM-NEXT:    eor z0.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    lsr z3.b, z5.b, #2
; NOSVE2BITPERM-NEXT:    orr z1.d, z1.d, z4.d
; NOSVE2BITPERM-NEXT:    orr z0.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    and z1.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    and z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor z0.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    lsr z1.b, z1.b, #4
; NOSVE2BITPERM-NEXT:    orr z0.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    ret
  %res = call <vscale x 16 x i8> @llvm.bext.nxv16i8(<vscale x 16 x i8> %val, <vscale x 16 x i8> %mask)
  ret <vscale x 16 x i8> %res
}

define <vscale x 16 x i8> @bdep_nxv16i8(<vscale x 16 x i8> %val, <vscale x 16 x i8> %mask) nounwind {
; BITPERM-LABEL: bdep_nxv16i8:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    bdep z0.b, z0.b, z1.b
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bdep_nxv16i8:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    movprfx z3, z1
; NOSVE2BITPERM-NEXT:    subr z3.b, z3.b, #255 // =0xff
; NOSVE2BITPERM-NEXT:    mov z2.b, #-1 // =0xffffffffffffffff
; NOSVE2BITPERM-NEXT:    lsl z3.b, z3.b, #1
; NOSVE2BITPERM-NEXT:    pmul z4.b, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    and z5.d, z4.d, z1.d
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z4.d
; NOSVE2BITPERM-NEXT:    eor z4.d, z1.d, z5.d
; NOSVE2BITPERM-NEXT:    lsr z6.b, z5.b, #1
; NOSVE2BITPERM-NEXT:    pmul z7.b, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    orr z4.d, z4.d, z6.d
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z7.d
; NOSVE2BITPERM-NEXT:    and z6.d, z7.d, z4.d
; NOSVE2BITPERM-NEXT:    pmul z2.b, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    eor z4.d, z4.d, z6.d
; NOSVE2BITPERM-NEXT:    lsr z7.b, z6.b, #2
; NOSVE2BITPERM-NEXT:    orr z3.d, z4.d, z7.d
; NOSVE2BITPERM-NEXT:    and z2.d, z2.d, z3.d
; NOSVE2BITPERM-NEXT:    lsl z3.b, z0.b, #4
; NOSVE2BITPERM-NEXT:    bsl z3.d, z3.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    lsl z0.b, z3.b, #2
; NOSVE2BITPERM-NEXT:    bsl z0.d, z0.d, z3.d, z6.d
; NOSVE2BITPERM-NEXT:    lsl z2.b, z0.b, #1
; NOSVE2BITPERM-NEXT:    bsl z2.d, z2.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    and z0.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    ret
  %res = call <vscale x 16 x i8> @llvm.bdep.nxv16i8(<vscale x 16 x i8> %val, <vscale x 16 x i8> %mask)
  ret <vscale x 16 x i8> %res
}

define <vscale x 8 x i16> @bext_nxv8i16(<vscale x 8 x i16> %val, <vscale x 8 x i16> %mask) nounwind {
; BITPERM-LABEL: bext_nxv8i16:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    bext z0.h, z0.h, z1.h
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bext_nxv8i16:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    movprfx z3, z1
; NOSVE2BITPERM-NEXT:    subr z3.b, z3.b, #255 // =0xff
; NOSVE2BITPERM-NEXT:    mov z2.h, #-1 // =0xffffffffffffffff
; NOSVE2BITPERM-NEXT:    and z0.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    lsl z3.h, z3.h, #1
; NOSVE2BITPERM-NEXT:    trn1 z4.b, z2.b, z3.b
; NOSVE2BITPERM-NEXT:    trn2 z5.b, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    pmullb z6.h, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    pmul z4.b, z5.b, z4.b
; NOSVE2BITPERM-NEXT:    eorbt z4.b, z4.b, z4.b
; NOSVE2BITPERM-NEXT:    eortb z6.b, z6.b, z4.b
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z6.d
; NOSVE2BITPERM-NEXT:    trn1 z4.b, z2.b, z3.b
; NOSVE2BITPERM-NEXT:    trn2 z5.b, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    pmullb z7.h, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    pmul z4.b, z5.b, z4.b
; NOSVE2BITPERM-NEXT:    eorbt z4.b, z4.b, z4.b
; NOSVE2BITPERM-NEXT:    eortb z7.b, z7.b, z4.b
; NOSVE2BITPERM-NEXT:    and z4.d, z6.d, z1.d
; NOSVE2BITPERM-NEXT:    eor z1.d, z1.d, z4.d
; NOSVE2BITPERM-NEXT:    lsr z24.h, z4.h, #1
; NOSVE2BITPERM-NEXT:    and z4.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z7.d
; NOSVE2BITPERM-NEXT:    orr z1.d, z1.d, z24.d
; NOSVE2BITPERM-NEXT:    eor z0.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    lsr z4.h, z4.h, #1
; NOSVE2BITPERM-NEXT:    trn1 z5.b, z2.b, z3.b
; NOSVE2BITPERM-NEXT:    trn2 z6.b, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    pmullb z25.h, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    orr z0.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    pmul z5.b, z6.b, z5.b
; NOSVE2BITPERM-NEXT:    and z6.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    and z4.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    eor z1.d, z1.d, z6.d
; NOSVE2BITPERM-NEXT:    lsr z6.h, z6.h, #2
; NOSVE2BITPERM-NEXT:    eorbt z5.b, z5.b, z5.b
; NOSVE2BITPERM-NEXT:    eor z0.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    lsr z4.h, z4.h, #2
; NOSVE2BITPERM-NEXT:    orr z1.d, z1.d, z6.d
; NOSVE2BITPERM-NEXT:    eortb z25.b, z25.b, z5.b
; NOSVE2BITPERM-NEXT:    orr z0.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z25.d
; NOSVE2BITPERM-NEXT:    and z4.d, z25.d, z1.d
; NOSVE2BITPERM-NEXT:    trn1 z5.b, z2.b, z3.b
; NOSVE2BITPERM-NEXT:    trn2 z6.b, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    pmullb z2.h, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    and z7.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    eor z1.d, z1.d, z4.d
; NOSVE2BITPERM-NEXT:    lsr z4.h, z4.h, #4
; NOSVE2BITPERM-NEXT:    pmul z3.b, z6.b, z5.b
; NOSVE2BITPERM-NEXT:    eor z0.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    lsr z5.h, z7.h, #4
; NOSVE2BITPERM-NEXT:    orr z1.d, z1.d, z4.d
; NOSVE2BITPERM-NEXT:    eorbt z3.b, z3.b, z3.b
; NOSVE2BITPERM-NEXT:    orr z0.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    and z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eortb z2.b, z2.b, z3.b
; NOSVE2BITPERM-NEXT:    and z1.d, z1.d, z2.d
; NOSVE2BITPERM-NEXT:    eor z0.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    lsr z1.h, z1.h, #8
; NOSVE2BITPERM-NEXT:    orr z0.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    ret
  %res = call <vscale x 8 x i16> @llvm.bext.nxv8i16(<vscale x 8 x i16> %val, <vscale x 8 x i16> %mask)
  ret <vscale x 8 x i16> %res
}

define <vscale x 8 x i16> @bdep_nxv8i16(<vscale x 8 x i16> %val, <vscale x 8 x i16> %mask) nounwind {
; BITPERM-LABEL: bdep_nxv8i16:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    bdep z0.h, z0.h, z1.h
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bdep_nxv8i16:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    movprfx z3, z1
; NOSVE2BITPERM-NEXT:    subr z3.b, z3.b, #255 // =0xff
; NOSVE2BITPERM-NEXT:    mov z2.h, #-1 // =0xffffffffffffffff
; NOSVE2BITPERM-NEXT:    lsl z3.h, z3.h, #1
; NOSVE2BITPERM-NEXT:    trn1 z4.b, z2.b, z3.b
; NOSVE2BITPERM-NEXT:    trn2 z5.b, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    pmullb z6.h, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    pmul z4.b, z5.b, z4.b
; NOSVE2BITPERM-NEXT:    eorbt z4.b, z4.b, z4.b
; NOSVE2BITPERM-NEXT:    eortb z6.b, z6.b, z4.b
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z6.d
; NOSVE2BITPERM-NEXT:    trn1 z4.b, z2.b, z3.b
; NOSVE2BITPERM-NEXT:    trn2 z5.b, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    pmullb z7.h, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    pmul z4.b, z5.b, z4.b
; NOSVE2BITPERM-NEXT:    eorbt z4.b, z4.b, z4.b
; NOSVE2BITPERM-NEXT:    eortb z7.b, z7.b, z4.b
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z7.d
; NOSVE2BITPERM-NEXT:    trn1 z4.b, z2.b, z3.b
; NOSVE2BITPERM-NEXT:    trn2 z5.b, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    pmullb z24.h, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    pmul z4.b, z5.b, z4.b
; NOSVE2BITPERM-NEXT:    and z5.d, z6.d, z1.d
; NOSVE2BITPERM-NEXT:    eor z6.d, z1.d, z5.d
; NOSVE2BITPERM-NEXT:    lsr z25.h, z5.h, #1
; NOSVE2BITPERM-NEXT:    eorbt z4.b, z4.b, z4.b
; NOSVE2BITPERM-NEXT:    orr z6.d, z6.d, z25.d
; NOSVE2BITPERM-NEXT:    eortb z24.b, z24.b, z4.b
; NOSVE2BITPERM-NEXT:    and z4.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z24.d
; NOSVE2BITPERM-NEXT:    eor z6.d, z6.d, z4.d
; NOSVE2BITPERM-NEXT:    lsr z7.h, z4.h, #2
; NOSVE2BITPERM-NEXT:    trn1 z25.b, z2.b, z3.b
; NOSVE2BITPERM-NEXT:    trn2 z26.b, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    pmullb z2.h, z3.b, z2.b
; NOSVE2BITPERM-NEXT:    orr z3.d, z6.d, z7.d
; NOSVE2BITPERM-NEXT:    pmul z6.b, z26.b, z25.b
; NOSVE2BITPERM-NEXT:    and z7.d, z24.d, z3.d
; NOSVE2BITPERM-NEXT:    eorbt z6.b, z6.b, z6.b
; NOSVE2BITPERM-NEXT:    eor z3.d, z3.d, z7.d
; NOSVE2BITPERM-NEXT:    lsr z24.h, z7.h, #4
; NOSVE2BITPERM-NEXT:    orr z3.d, z3.d, z24.d
; NOSVE2BITPERM-NEXT:    eortb z2.b, z2.b, z6.b
; NOSVE2BITPERM-NEXT:    and z2.d, z2.d, z3.d
; NOSVE2BITPERM-NEXT:    lsl z3.h, z0.h, #8
; NOSVE2BITPERM-NEXT:    bsl z3.d, z3.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    lsl z0.h, z3.h, #4
; NOSVE2BITPERM-NEXT:    bsl z0.d, z0.d, z3.d, z7.d
; NOSVE2BITPERM-NEXT:    lsl z2.h, z0.h, #2
; NOSVE2BITPERM-NEXT:    bsl z2.d, z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    lsl z0.h, z2.h, #1
; NOSVE2BITPERM-NEXT:    bsl z0.d, z0.d, z2.d, z5.d
; NOSVE2BITPERM-NEXT:    and z0.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    ret
  %res = call <vscale x 8 x i16> @llvm.bdep.nxv8i16(<vscale x 8 x i16> %val, <vscale x 8 x i16> %mask)
  ret <vscale x 8 x i16> %res
}

define <vscale x 4 x i32> @bext_nxv4i32(<vscale x 4 x i32> %val, <vscale x 4 x i32> %mask) nounwind {
; BITPERM-LABEL: bext_nxv4i32:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    bext z0.s, z0.s, z1.s
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bext_nxv4i32:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    movprfx z3, z1
; NOSVE2BITPERM-NEXT:    subr z3.b, z3.b, #255 // =0xff
; NOSVE2BITPERM-NEXT:    mov z2.s, #-1 // =0xffffffffffffffff
; NOSVE2BITPERM-NEXT:    and z0.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    lsl z3.s, z3.s, #1
; NOSVE2BITPERM-NEXT:    pmullt z4.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    pmullb z5.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    trn1 z4.s, z5.s, z4.s
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z4.d
; NOSVE2BITPERM-NEXT:    and z4.d, z4.d, z1.d
; NOSVE2BITPERM-NEXT:    pmullt z5.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    eor z1.d, z1.d, z4.d
; NOSVE2BITPERM-NEXT:    lsr z24.s, z4.s, #1
; NOSVE2BITPERM-NEXT:    pmullb z6.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    and z4.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    orr z1.d, z1.d, z24.d
; NOSVE2BITPERM-NEXT:    eor z0.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    lsr z4.s, z4.s, #1
; NOSVE2BITPERM-NEXT:    orr z0.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    trn1 z5.s, z6.s, z5.s
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z5.d
; NOSVE2BITPERM-NEXT:    and z5.d, z5.d, z1.d
; NOSVE2BITPERM-NEXT:    pmullt z6.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    eor z1.d, z1.d, z5.d
; NOSVE2BITPERM-NEXT:    pmullb z7.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    trn1 z4.s, z7.s, z6.s
; NOSVE2BITPERM-NEXT:    lsr z6.s, z5.s, #2
; NOSVE2BITPERM-NEXT:    and z5.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z4.d
; NOSVE2BITPERM-NEXT:    orr z1.d, z1.d, z6.d
; NOSVE2BITPERM-NEXT:    eor z0.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    lsr z5.s, z5.s, #2
; NOSVE2BITPERM-NEXT:    pmullt z6.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    and z4.d, z4.d, z1.d
; NOSVE2BITPERM-NEXT:    pmullb z7.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    orr z0.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    eor z1.d, z1.d, z4.d
; NOSVE2BITPERM-NEXT:    and z5.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    lsr z4.s, z4.s, #4
; NOSVE2BITPERM-NEXT:    eor z0.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    lsr z5.s, z5.s, #4
; NOSVE2BITPERM-NEXT:    orr z1.d, z1.d, z4.d
; NOSVE2BITPERM-NEXT:    trn1 z4.s, z7.s, z6.s
; NOSVE2BITPERM-NEXT:    orr z0.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    and z5.d, z4.d, z1.d
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z4.d
; NOSVE2BITPERM-NEXT:    and z4.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    pmullt z6.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    eor z1.d, z1.d, z5.d
; NOSVE2BITPERM-NEXT:    pmullb z2.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    eor z0.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    lsr z3.s, z4.s, #8
; NOSVE2BITPERM-NEXT:    lsr z4.s, z5.s, #8
; NOSVE2BITPERM-NEXT:    orr z0.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    orr z1.d, z1.d, z4.d
; NOSVE2BITPERM-NEXT:    and z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    trn1 z2.s, z2.s, z6.s
; NOSVE2BITPERM-NEXT:    and z1.d, z1.d, z2.d
; NOSVE2BITPERM-NEXT:    eor z0.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    lsr z1.s, z1.s, #16
; NOSVE2BITPERM-NEXT:    orr z0.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    ret
  %res = call <vscale x 4 x i32> @llvm.bext.nxv4i32(<vscale x 4 x i32> %val, <vscale x 4 x i32> %mask)
  ret <vscale x 4 x i32> %res
}

define <vscale x 4 x i32> @bdep_nxv4i32(<vscale x 4 x i32> %val, <vscale x 4 x i32> %mask) nounwind {
; BITPERM-LABEL: bdep_nxv4i32:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    bdep z0.s, z0.s, z1.s
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bdep_nxv4i32:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    movprfx z3, z1
; NOSVE2BITPERM-NEXT:    subr z3.b, z3.b, #255 // =0xff
; NOSVE2BITPERM-NEXT:    mov z2.s, #-1 // =0xffffffffffffffff
; NOSVE2BITPERM-NEXT:    lsl z3.s, z3.s, #1
; NOSVE2BITPERM-NEXT:    pmullt z4.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    pmullb z5.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    trn1 z4.s, z5.s, z4.s
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z4.d
; NOSVE2BITPERM-NEXT:    and z4.d, z4.d, z1.d
; NOSVE2BITPERM-NEXT:    pmullt z5.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    lsr z24.s, z4.s, #1
; NOSVE2BITPERM-NEXT:    pmullb z6.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    trn1 z5.s, z6.s, z5.s
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z5.d
; NOSVE2BITPERM-NEXT:    pmullt z6.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    pmullb z7.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    trn1 z6.s, z7.s, z6.s
; NOSVE2BITPERM-NEXT:    eor z7.d, z1.d, z4.d
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z6.d
; NOSVE2BITPERM-NEXT:    orr z7.d, z7.d, z24.d
; NOSVE2BITPERM-NEXT:    pmullt z24.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    and z5.d, z5.d, z7.d
; NOSVE2BITPERM-NEXT:    pmullb z25.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    eor z7.d, z7.d, z5.d
; NOSVE2BITPERM-NEXT:    lsr z26.s, z5.s, #2
; NOSVE2BITPERM-NEXT:    orr z7.d, z7.d, z26.d
; NOSVE2BITPERM-NEXT:    and z6.d, z6.d, z7.d
; NOSVE2BITPERM-NEXT:    trn1 z24.s, z25.s, z24.s
; NOSVE2BITPERM-NEXT:    eor z7.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    lsr z25.s, z6.s, #4
; NOSVE2BITPERM-NEXT:    bic z3.d, z3.d, z24.d
; NOSVE2BITPERM-NEXT:    orr z7.d, z7.d, z25.d
; NOSVE2BITPERM-NEXT:    pmullt z26.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    pmullb z2.d, z3.s, z2.s
; NOSVE2BITPERM-NEXT:    and z3.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    eor z7.d, z7.d, z3.d
; NOSVE2BITPERM-NEXT:    lsr z24.s, z3.s, #8
; NOSVE2BITPERM-NEXT:    orr z7.d, z7.d, z24.d
; NOSVE2BITPERM-NEXT:    trn1 z2.s, z2.s, z26.s
; NOSVE2BITPERM-NEXT:    and z2.d, z2.d, z7.d
; NOSVE2BITPERM-NEXT:    lsl z7.s, z0.s, #16
; NOSVE2BITPERM-NEXT:    bsl z7.d, z7.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    lsl z0.s, z7.s, #8
; NOSVE2BITPERM-NEXT:    bsl z0.d, z0.d, z7.d, z3.d
; NOSVE2BITPERM-NEXT:    lsl z2.s, z0.s, #4
; NOSVE2BITPERM-NEXT:    bsl z2.d, z2.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    lsl z0.s, z2.s, #2
; NOSVE2BITPERM-NEXT:    bsl z0.d, z0.d, z2.d, z5.d
; NOSVE2BITPERM-NEXT:    lsl z2.s, z0.s, #1
; NOSVE2BITPERM-NEXT:    bsl z2.d, z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    and z0.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    ret
  %res = call <vscale x 4 x i32> @llvm.bdep.nxv4i32(<vscale x 4 x i32> %val, <vscale x 4 x i32> %mask)
  ret <vscale x 4 x i32> %res
}

define <vscale x 2 x i64> @bext_nxv2i64(<vscale x 2 x i64> %val, <vscale x 2 x i64> %mask) nounwind {
; BITPERM-LABEL: bext_nxv2i64:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    bext z0.d, z0.d, z1.d
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bext_nxv2i64:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; NOSVE2BITPERM-NEXT:    addvl sp, sp, #-16
; NOSVE2BITPERM-NEXT:    str z23, [sp] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z22, [sp, #1, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z21, [sp, #2, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z20, [sp, #3, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z19, [sp, #4, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z18, [sp, #5, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z17, [sp, #6, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z16, [sp, #7, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z15, [sp, #8, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z14, [sp, #9, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z13, [sp, #10, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z12, [sp, #11, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z11, [sp, #12, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z10, [sp, #13, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z9, [sp, #14, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z8, [sp, #15, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    addvl sp, sp, #-2
; NOSVE2BITPERM-NEXT:    str z0, [sp, #1, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    movprfx z0, z1
; NOSVE2BITPERM-NEXT:    subr z0.b, z0.b, #255 // =0xff
; NOSVE2BITPERM-NEXT:    mov z5.d, #128 // =0x80
; NOSVE2BITPERM-NEXT:    str z1, [sp] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    mov z28.d, #0x20000
; NOSVE2BITPERM-NEXT:    mov z29.d, #0x10000
; NOSVE2BITPERM-NEXT:    mov z30.d, #0x40000
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x2000000
; NOSVE2BITPERM-NEXT:    mov z26.d, #128 // =0x80
; NOSVE2BITPERM-NEXT:    lsl z0.d, z0.d, #1
; NOSVE2BITPERM-NEXT:    mov z31.d, #512 // =0x200
; NOSVE2BITPERM-NEXT:    mov z25.d, #256 // =0x100
; NOSVE2BITPERM-NEXT:    mov z6.d, #2048 // =0x800
; NOSVE2BITPERM-NEXT:    mov z7.d, #1024 // =0x400
; NOSVE2BITPERM-NEXT:    mov z21.d, #16384 // =0x4000
; NOSVE2BITPERM-NEXT:    mov z22.d, #0x20000
; NOSVE2BITPERM-NEXT:    mov z23.d, #0x10000
; NOSVE2BITPERM-NEXT:    mov z8.d, #0x2000000
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #2
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #1
; NOSVE2BITPERM-NEXT:    movprfx z3, z0
; NOSVE2BITPERM-NEXT:    mul z3.d, z3.d, #8
; NOSVE2BITPERM-NEXT:    movprfx z4, z0
; NOSVE2BITPERM-NEXT:    mul z4.d, z4.d, #4
; NOSVE2BITPERM-NEXT:    mov z9.d, #0x1000000
; NOSVE2BITPERM-NEXT:    mov z10.d, #0x8000000
; NOSVE2BITPERM-NEXT:    mov z11.d, #0x4000000
; NOSVE2BITPERM-NEXT:    mov z13.d, #0x20000000
; NOSVE2BITPERM-NEXT:    mov z14.d, #0x10000000
; NOSVE2BITPERM-NEXT:    mov z16.d, #0x40000000
; NOSVE2BITPERM-NEXT:    mov z12.d, #0x80000000
; NOSVE2BITPERM-NEXT:    mov z15.d, #0x200000000
; NOSVE2BITPERM-NEXT:    eor z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #32
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #16
; NOSVE2BITPERM-NEXT:    mov z18.d, #0x100000000
; NOSVE2BITPERM-NEXT:    mov z17.d, #0x800000000
; NOSVE2BITPERM-NEXT:    mov z19.d, #0x20000000000
; NOSVE2BITPERM-NEXT:    mov z20.d, #0x10000000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z3.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    movprfx z4, z0
; NOSVE2BITPERM-NEXT:    mul z4.d, z4.d, #64
; NOSVE2BITPERM-NEXT:    mov z5.d, #32768 // =0x8000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #512 // =0x200
; NOSVE2BITPERM-NEXT:    mov z2.d, #256 // =0x100
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #2048 // =0x800
; NOSVE2BITPERM-NEXT:    mov z4.d, #1024 // =0x400
; NOSVE2BITPERM-NEXT:    mul z3.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z4.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #8192 // =0x2000
; NOSVE2BITPERM-NEXT:    mov z2.d, #4096 // =0x1000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    mov z4.d, #16384 // =0x4000
; NOSVE2BITPERM-NEXT:    mul z3.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x80000
; NOSVE2BITPERM-NEXT:    mul z4.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z29.d
; NOSVE2BITPERM-NEXT:    mov z28.d, #0x200000
; NOSVE2BITPERM-NEXT:    mov z29.d, #0x100000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z3.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z4.d, z0.d, z30.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x800000
; NOSVE2BITPERM-NEXT:    mov z30.d, #0x400000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z29.d
; NOSVE2BITPERM-NEXT:    mov z28.d, #0x1000000
; NOSVE2BITPERM-NEXT:    mov z29.d, #0x4000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z3.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z4.d, z0.d, z30.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x8000000
; NOSVE2BITPERM-NEXT:    mov z30.d, #0x800000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x20000000
; NOSVE2BITPERM-NEXT:    mov z28.d, #0x10000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z3.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z4.d, z0.d, z29.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x80000000
; NOSVE2BITPERM-NEXT:    mov z29.d, #0x40000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x4000000000
; NOSVE2BITPERM-NEXT:    mov z28.d, #0x200000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z3.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x100000000
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x400000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z29.d
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x200000000
; NOSVE2BITPERM-NEXT:    mov z29.d, #0x100000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z1.d, z3.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x800000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x1000000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x2000000000
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x8000000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x80000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x20000000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x10000000000
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x40000000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x800000000000
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x200000000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x100000000000
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x400000000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x8000000000000
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x4000000000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x2000000000000
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x1000000000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x20000000000000
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x10000000000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x80000000000000
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x40000000000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x800000000000000
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x400000000000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x200000000000000
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x100000000000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x1000000000000000
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x4000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x2000000000000000
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x8000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x40000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    eor3 z24.d, z24.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    bic z0.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #2
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #1
; NOSVE2BITPERM-NEXT:    movprfx z3, z0
; NOSVE2BITPERM-NEXT:    mul z3.d, z3.d, #8
; NOSVE2BITPERM-NEXT:    movprfx z4, z0
; NOSVE2BITPERM-NEXT:    mul z4.d, z4.d, #4
; NOSVE2BITPERM-NEXT:    eor z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #32
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #16
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #64
; NOSVE2BITPERM-NEXT:    mov z26.d, #0x80000
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z31.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z25.d
; NOSVE2BITPERM-NEXT:    mov z25.d, #32768 // =0x8000
; NOSVE2BITPERM-NEXT:    mov z31.d, #0x400000
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #8192 // =0x2000
; NOSVE2BITPERM-NEXT:    mov z7.d, #4096 // =0x1000
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z25.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z21.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z22.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z23.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z29.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z30.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z31.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z8.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z9.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z10.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z11.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z13.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z14.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z12.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z16.d
; NOSVE2BITPERM-NEXT:    mov z16.d, #0x2000000000
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z15.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z18.d
; NOSVE2BITPERM-NEXT:    mov z18.d, #0x8000000000
; NOSVE2BITPERM-NEXT:    mov z15.d, #0x4000000000
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x400000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z17.d
; NOSVE2BITPERM-NEXT:    mov z17.d, #0x1000000000
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z16.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z17.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z18.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z15.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z19.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z20.d
; NOSVE2BITPERM-NEXT:    mov z19.d, #0x80000000000
; NOSVE2BITPERM-NEXT:    mov z20.d, #0x40000000000
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z19.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z20.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x100000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x400000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x2000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x1000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x8000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x4000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x10000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x80000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x40000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x100000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x400000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x2000000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x1000000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x8000000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x4000000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    bic z0.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    movprfx z4, z0
; NOSVE2BITPERM-NEXT:    mul z4.d, z4.d, #2
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #1
; NOSVE2BITPERM-NEXT:    movprfx z3, z0
; NOSVE2BITPERM-NEXT:    mul z3.d, z3.d, #8
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #4
; NOSVE2BITPERM-NEXT:    eor z4.d, z2.d, z4.d
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #16
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z1.d, z3.d
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #32
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #128 // =0x80
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #64
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #512 // =0x200
; NOSVE2BITPERM-NEXT:    mov z2.d, #256 // =0x100
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #2048 // =0x800
; NOSVE2BITPERM-NEXT:    mov z2.d, #1024 // =0x400
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x8000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z25.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z21.d
; NOSVE2BITPERM-NEXT:    mov z21.d, #0x40000000000
; NOSVE2BITPERM-NEXT:    mov z25.d, #0x4000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z22.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z23.d
; NOSVE2BITPERM-NEXT:    mov z22.d, #0x20000000000
; NOSVE2BITPERM-NEXT:    mov z23.d, #0x10000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mov z26.d, #0x2000000000000000
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x1000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z29.d
; NOSVE2BITPERM-NEXT:    mov z29.d, #0x80000000000000
; NOSVE2BITPERM-NEXT:    mov z28.d, #0x400000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z30.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z31.d
; NOSVE2BITPERM-NEXT:    mov z31.d, #0x20000000000000
; NOSVE2BITPERM-NEXT:    mov z30.d, #0x40000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z8.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z9.d
; NOSVE2BITPERM-NEXT:    mov z9.d, #0x8000000000000
; NOSVE2BITPERM-NEXT:    mov z8.d, #0x10000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z10.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z11.d
; NOSVE2BITPERM-NEXT:    mov z11.d, #0x2000000000000
; NOSVE2BITPERM-NEXT:    mov z10.d, #0x4000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z13.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z14.d
; NOSVE2BITPERM-NEXT:    mov z13.d, #0x800000000000
; NOSVE2BITPERM-NEXT:    mov z14.d, #0x400000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x40000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z12.d
; NOSVE2BITPERM-NEXT:    mov z12.d, #0x1000000000000
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x100000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x400000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z16.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z17.d
; NOSVE2BITPERM-NEXT:    mov z16.d, #0x200000000000
; NOSVE2BITPERM-NEXT:    mov z17.d, #0x100000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z18.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z15.d
; NOSVE2BITPERM-NEXT:    mov z18.d, #0x100000000000
; NOSVE2BITPERM-NEXT:    mov z15.d, #0x200000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x10000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z19.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z20.d
; NOSVE2BITPERM-NEXT:    mov z19.d, #0x80000000000
; NOSVE2BITPERM-NEXT:    mov z20.d, #0x800000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x100000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x400000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x2000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x1000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x8000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x4000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x10000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x80000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x40000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x100000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x400000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x2000000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x1000000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x8000000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x4000000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    bic z0.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    movprfx z3, z0
; NOSVE2BITPERM-NEXT:    mul z3.d, z3.d, #2
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #1
; NOSVE2BITPERM-NEXT:    movprfx z7, z0
; NOSVE2BITPERM-NEXT:    mul z7.d, z7.d, #8
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #4
; NOSVE2BITPERM-NEXT:    eor z3.d, z2.d, z3.d
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #16
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z1.d, z7.d
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #32
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #128 // =0x80
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #64
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #512 // =0x200
; NOSVE2BITPERM-NEXT:    mov z2.d, #256 // =0x100
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #2048 // =0x800
; NOSVE2BITPERM-NEXT:    mov z2.d, #1024 // =0x400
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #8192 // =0x2000
; NOSVE2BITPERM-NEXT:    mov z2.d, #4096 // =0x1000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #32768 // =0x8000
; NOSVE2BITPERM-NEXT:    mov z2.d, #16384 // =0x4000
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x10000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x80000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x40000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x100000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x400000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x2000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x1000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x8000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x4000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x10000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x80000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x40000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x100000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x400000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x2000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x1000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x8000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x4000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z22.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z23.d
; NOSVE2BITPERM-NEXT:    mov z23.d, #0x80000000000
; NOSVE2BITPERM-NEXT:    mov z22.d, #0x100000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z19.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z21.d
; NOSVE2BITPERM-NEXT:    mov z21.d, #0x200000000000
; NOSVE2BITPERM-NEXT:    mov z19.d, #0x400000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z16.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z18.d
; NOSVE2BITPERM-NEXT:    mov z18.d, #0x800000000000
; NOSVE2BITPERM-NEXT:    mov z16.d, #0x1000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z13.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z14.d
; NOSVE2BITPERM-NEXT:    mov z13.d, #0x2000000000000
; NOSVE2BITPERM-NEXT:    mov z14.d, #0x200000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z11.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z12.d
; NOSVE2BITPERM-NEXT:    mov z11.d, #0x8000000000000
; NOSVE2BITPERM-NEXT:    mov z12.d, #0x4000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z9.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z10.d
; NOSVE2BITPERM-NEXT:    mov z9.d, #0x20000000000000
; NOSVE2BITPERM-NEXT:    mov z10.d, #0x10000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z31.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z8.d
; NOSVE2BITPERM-NEXT:    mov z31.d, #0x80000000000000
; NOSVE2BITPERM-NEXT:    mov z8.d, #0x40000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z29.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z30.d
; NOSVE2BITPERM-NEXT:    mov z29.d, #0x400000000000000
; NOSVE2BITPERM-NEXT:    mov z30.d, #8192 // =0x2000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z15.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z17.d
; NOSVE2BITPERM-NEXT:    mov z17.d, #0x100000000000000
; NOSVE2BITPERM-NEXT:    mov z15.d, #4096 // =0x1000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z20.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    mov z20.d, #0x800000000000000
; NOSVE2BITPERM-NEXT:    mov z28.d, #0x2000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x1000000000000000
; NOSVE2BITPERM-NEXT:    mov z26.d, #0x8000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z25.d
; NOSVE2BITPERM-NEXT:    mov z25.d, #0x4000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    bic z0.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    movprfx z6, z0
; NOSVE2BITPERM-NEXT:    mul z6.d, z6.d, #2
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #1
; NOSVE2BITPERM-NEXT:    movprfx z7, z0
; NOSVE2BITPERM-NEXT:    mul z7.d, z7.d, #8
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #4
; NOSVE2BITPERM-NEXT:    eor z2.d, z2.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #256 // =0x100
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z1.d, z7.d
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #32
; NOSVE2BITPERM-NEXT:    movprfx z7, z0
; NOSVE2BITPERM-NEXT:    mul z7.d, z7.d, #16
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #128 // =0x80
; NOSVE2BITPERM-NEXT:    movprfx z7, z0
; NOSVE2BITPERM-NEXT:    mul z7.d, z7.d, #64
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #512 // =0x200
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #1024 // =0x400
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #2048 // =0x800
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #4096 // =0x1000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #8192 // =0x2000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #16384 // =0x4000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #32768 // =0x8000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x10000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x40000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x80000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x100000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x400000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x1000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x2000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x4000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x8000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x10000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x40000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x80000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x100000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x400000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x1000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x2000000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x4000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x8000000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x10000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x40000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z23.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z23.d, #0x40000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z21.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z22.d
; NOSVE2BITPERM-NEXT:    mov z21.d, #0x200000000000
; NOSVE2BITPERM-NEXT:    mov z22.d, #0x100000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z18.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z19.d
; NOSVE2BITPERM-NEXT:    mov z18.d, #0x800000000000
; NOSVE2BITPERM-NEXT:    mov z19.d, #0x400000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z13.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z16.d
; NOSVE2BITPERM-NEXT:    mov z13.d, #0x1000000000000
; NOSVE2BITPERM-NEXT:    mov z16.d, #0x8000000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z11.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z12.d
; NOSVE2BITPERM-NEXT:    mov z11.d, #0x4000000000000
; NOSVE2BITPERM-NEXT:    mov z12.d, #0x20000000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z9.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z10.d
; NOSVE2BITPERM-NEXT:    mov z9.d, #0x10000000000000
; NOSVE2BITPERM-NEXT:    mov z10.d, #0x80000000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z31.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z8.d
; NOSVE2BITPERM-NEXT:    mov z31.d, #0x40000000000000
; NOSVE2BITPERM-NEXT:    mov z8.d, #0x200000000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z14.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z17.d
; NOSVE2BITPERM-NEXT:    mov z14.d, #0x100000000000000
; NOSVE2BITPERM-NEXT:    mov z17.d, #0x800000000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z20.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z29.d
; NOSVE2BITPERM-NEXT:    mov z29.d, #0x400000000000000
; NOSVE2BITPERM-NEXT:    mov z20.d, #0x1000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mov z28.d, #0x2000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z25.d
; NOSVE2BITPERM-NEXT:    ldr z26, [sp] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    bic z0.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #2
; NOSVE2BITPERM-NEXT:    movprfx z7, z0
; NOSVE2BITPERM-NEXT:    mul z7.d, z7.d, #1
; NOSVE2BITPERM-NEXT:    movprfx z25, z0
; NOSVE2BITPERM-NEXT:    mul z25.d, z25.d, #8
; NOSVE2BITPERM-NEXT:    movprfx z6, z0
; NOSVE2BITPERM-NEXT:    mul z6.d, z6.d, #4
; NOSVE2BITPERM-NEXT:    eor z1.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    movprfx z7, z0
; NOSVE2BITPERM-NEXT:    mul z7.d, z7.d, #16
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z6.d, z25.d
; NOSVE2BITPERM-NEXT:    movprfx z6, z0
; NOSVE2BITPERM-NEXT:    mul z6.d, z6.d, #32
; NOSVE2BITPERM-NEXT:    mov z25.d, #0x10000000000
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #128 // =0x80
; NOSVE2BITPERM-NEXT:    movprfx z7, z0
; NOSVE2BITPERM-NEXT:    mul z7.d, z7.d, #64
; NOSVE2BITPERM-NEXT:    mul z25.d, z0.d, z25.d
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #512 // =0x200
; NOSVE2BITPERM-NEXT:    mov z7.d, #256 // =0x100
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #2048 // =0x800
; NOSVE2BITPERM-NEXT:    mov z7.d, #1024 // =0x400
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z30.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z15.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #32768 // =0x8000
; NOSVE2BITPERM-NEXT:    mov z7.d, #16384 // =0x4000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x20000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x10000
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x80000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x40000
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x200000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x100000
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x800000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x400000
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x2000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x1000000
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x8000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x4000000
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x20000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x10000000
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x80000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x40000000
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x200000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x100000000
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x800000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x400000000
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x2000000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x1000000000
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x8000000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x4000000000
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    and z7.d, z24.d, z26.d
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x20000000000
; NOSVE2BITPERM-NEXT:    ldr z6, [sp, #1, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    eor z27.d, z26.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    and z6.d, z6.d, z26.d
; NOSVE2BITPERM-NEXT:    lsr z26.d, z7.d, #1
; NOSVE2BITPERM-NEXT:    and z7.d, z6.d, z7.d
; NOSVE2BITPERM-NEXT:    orr z26.d, z27.d, z26.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z25.d, z24.d
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x80000000000
; NOSVE2BITPERM-NEXT:    mul z25.d, z0.d, z23.d
; NOSVE2BITPERM-NEXT:    eor z6.d, z6.d, z7.d
; NOSVE2BITPERM-NEXT:    lsr z7.d, z7.d, #1
; NOSVE2BITPERM-NEXT:    and z5.d, z5.d, z26.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    orr z6.d, z6.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z25.d, z24.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z21.d
; NOSVE2BITPERM-NEXT:    mul z25.d, z0.d, z22.d
; NOSVE2BITPERM-NEXT:    and z7.d, z6.d, z5.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z25.d, z24.d
; NOSVE2BITPERM-NEXT:    eor z24.d, z26.d, z5.d
; NOSVE2BITPERM-NEXT:    lsr z5.d, z5.d, #2
; NOSVE2BITPERM-NEXT:    mul z25.d, z0.d, z18.d
; NOSVE2BITPERM-NEXT:    mul z26.d, z0.d, z19.d
; NOSVE2BITPERM-NEXT:    eor z6.d, z6.d, z7.d
; NOSVE2BITPERM-NEXT:    lsr z7.d, z7.d, #2
; NOSVE2BITPERM-NEXT:    orr z5.d, z24.d, z5.d
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x2000000000000
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z26.d, z25.d
; NOSVE2BITPERM-NEXT:    mul z25.d, z0.d, z13.d
; NOSVE2BITPERM-NEXT:    orr z6.d, z6.d, z7.d
; NOSVE2BITPERM-NEXT:    and z4.d, z4.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z16.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor z5.d, z5.d, z4.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z25.d, z24.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z11.d
; NOSVE2BITPERM-NEXT:    and z25.d, z6.d, z4.d
; NOSVE2BITPERM-NEXT:    lsr z4.d, z4.d, #4
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    orr z4.d, z5.d, z4.d
; NOSVE2BITPERM-NEXT:    eor z5.d, z6.d, z25.d
; NOSVE2BITPERM-NEXT:    lsr z6.d, z25.d, #4
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z12.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z9.d
; NOSVE2BITPERM-NEXT:    and z3.d, z3.d, z4.d
; NOSVE2BITPERM-NEXT:    orr z5.d, z5.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z10.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z31.d
; NOSVE2BITPERM-NEXT:    eor z4.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    and z24.d, z5.d, z3.d
; NOSVE2BITPERM-NEXT:    lsr z3.d, z3.d, #8
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z8.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z14.d
; NOSVE2BITPERM-NEXT:    eor z5.d, z5.d, z24.d
; NOSVE2BITPERM-NEXT:    lsr z24.d, z24.d, #8
; NOSVE2BITPERM-NEXT:    orr z3.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z6.d
; NOSVE2BITPERM-NEXT:    orr z4.d, z5.d, z24.d
; NOSVE2BITPERM-NEXT:    mul z5.d, z0.d, z17.d
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z29.d
; NOSVE2BITPERM-NEXT:    and z2.d, z2.d, z3.d
; NOSVE2BITPERM-NEXT:    and z7.d, z4.d, z2.d
; NOSVE2BITPERM-NEXT:    eor z3.d, z3.d, z2.d
; NOSVE2BITPERM-NEXT:    lsr z2.d, z2.d, #16
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z6.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z5.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    mul z6.d, z0.d, z20.d
; NOSVE2BITPERM-NEXT:    eor z4.d, z4.d, z7.d
; NOSVE2BITPERM-NEXT:    lsr z7.d, z7.d, #16
; NOSVE2BITPERM-NEXT:    orr z2.d, z3.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z6.d, z5.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x8000000000000000
; NOSVE2BITPERM-NEXT:    mov z6.d, #0x4000000000000000
; NOSVE2BITPERM-NEXT:    orr z4.d, z4.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z5.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z0.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    and z0.d, z4.d, z2.d
; NOSVE2BITPERM-NEXT:    and z0.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor z1.d, z4.d, z0.d
; NOSVE2BITPERM-NEXT:    lsr z0.d, z0.d, #32
; NOSVE2BITPERM-NEXT:    orr z0.d, z1.d, z0.d
; NOSVE2BITPERM-NEXT:    addvl sp, sp, #2
; NOSVE2BITPERM-NEXT:    ldr z23, [sp] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z22, [sp, #1, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z21, [sp, #2, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z20, [sp, #3, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z19, [sp, #4, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z18, [sp, #5, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z17, [sp, #6, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z16, [sp, #7, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z15, [sp, #8, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z14, [sp, #9, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z13, [sp, #10, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z12, [sp, #11, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z11, [sp, #12, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z10, [sp, #13, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z9, [sp, #14, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z8, [sp, #15, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    addvl sp, sp, #16
; NOSVE2BITPERM-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ret
  %res = call <vscale x 2 x i64> @llvm.bext.nxv2i64(<vscale x 2 x i64> %val, <vscale x 2 x i64> %mask)
  ret <vscale x 2 x i64> %res
}

define <vscale x 2 x i64> @bdep_nxv2i64(<vscale x 2 x i64> %val, <vscale x 2 x i64> %mask) nounwind {
; BITPERM-LABEL: bdep_nxv2i64:
; BITPERM:       // %bb.0:
; BITPERM-NEXT:    bdep z0.d, z0.d, z1.d
; BITPERM-NEXT:    ret
;
; NOSVE2BITPERM-LABEL: bdep_nxv2i64:
; NOSVE2BITPERM:       // %bb.0:
; NOSVE2BITPERM-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; NOSVE2BITPERM-NEXT:    addvl sp, sp, #-16
; NOSVE2BITPERM-NEXT:    str z23, [sp] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z22, [sp, #1, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z21, [sp, #2, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z20, [sp, #3, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z19, [sp, #4, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z18, [sp, #5, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z17, [sp, #6, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z16, [sp, #7, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z15, [sp, #8, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z14, [sp, #9, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z13, [sp, #10, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z12, [sp, #11, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z11, [sp, #12, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z10, [sp, #13, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z9, [sp, #14, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    str z8, [sp, #15, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    addvl sp, sp, #-2
; NOSVE2BITPERM-NEXT:    str z0, [sp, #1, mul vl] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    movprfx z0, z1
; NOSVE2BITPERM-NEXT:    subr z0.b, z0.b, #255 // =0xff
; NOSVE2BITPERM-NEXT:    mov z5.d, #128 // =0x80
; NOSVE2BITPERM-NEXT:    str z1, [sp] // 16-byte Folded Spill
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x20000
; NOSVE2BITPERM-NEXT:    mov z28.d, #0x10000
; NOSVE2BITPERM-NEXT:    mov z29.d, #0x40000
; NOSVE2BITPERM-NEXT:    mov z26.d, #0x200000
; NOSVE2BITPERM-NEXT:    mov z30.d, #128 // =0x80
; NOSVE2BITPERM-NEXT:    lsl z0.d, z0.d, #1
; NOSVE2BITPERM-NEXT:    mov z31.d, #512 // =0x200
; NOSVE2BITPERM-NEXT:    mov z25.d, #256 // =0x100
; NOSVE2BITPERM-NEXT:    mov z7.d, #2048 // =0x800
; NOSVE2BITPERM-NEXT:    mov z24.d, #1024 // =0x400
; NOSVE2BITPERM-NEXT:    mov z22.d, #8192 // =0x2000
; NOSVE2BITPERM-NEXT:    mov z8.d, #0x100000
; NOSVE2BITPERM-NEXT:    mov z9.d, #0x800000
; NOSVE2BITPERM-NEXT:    mov z10.d, #0x400000
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #2
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #1
; NOSVE2BITPERM-NEXT:    movprfx z3, z0
; NOSVE2BITPERM-NEXT:    mul z3.d, z3.d, #8
; NOSVE2BITPERM-NEXT:    movprfx z4, z0
; NOSVE2BITPERM-NEXT:    mul z4.d, z4.d, #4
; NOSVE2BITPERM-NEXT:    mov z11.d, #0x2000000
; NOSVE2BITPERM-NEXT:    mov z12.d, #0x1000000
; NOSVE2BITPERM-NEXT:    mov z13.d, #0x8000000
; NOSVE2BITPERM-NEXT:    mov z14.d, #0x4000000
; NOSVE2BITPERM-NEXT:    mov z16.d, #0x20000000
; NOSVE2BITPERM-NEXT:    mov z17.d, #0x10000000
; NOSVE2BITPERM-NEXT:    mov z18.d, #0x40000000
; NOSVE2BITPERM-NEXT:    mov z15.d, #0x80000000
; NOSVE2BITPERM-NEXT:    eor z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #32
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #16
; NOSVE2BITPERM-NEXT:    mov z19.d, #0x800000000
; NOSVE2BITPERM-NEXT:    mov z20.d, #0x400000000
; NOSVE2BITPERM-NEXT:    mov z21.d, #0x20000000000
; NOSVE2BITPERM-NEXT:    mov z23.d, #0x200000000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z3.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    movprfx z4, z0
; NOSVE2BITPERM-NEXT:    mul z4.d, z4.d, #64
; NOSVE2BITPERM-NEXT:    mov z5.d, #32768 // =0x8000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #512 // =0x200
; NOSVE2BITPERM-NEXT:    mov z2.d, #256 // =0x100
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #2048 // =0x800
; NOSVE2BITPERM-NEXT:    mov z4.d, #1024 // =0x400
; NOSVE2BITPERM-NEXT:    mul z3.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z4.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #8192 // =0x2000
; NOSVE2BITPERM-NEXT:    mov z2.d, #4096 // =0x1000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    mov z4.d, #16384 // =0x4000
; NOSVE2BITPERM-NEXT:    mul z3.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x80000
; NOSVE2BITPERM-NEXT:    mul z4.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x100000
; NOSVE2BITPERM-NEXT:    mov z28.d, #0x400000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z3.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z4.d, z0.d, z29.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x800000
; NOSVE2BITPERM-NEXT:    mov z29.d, #0x80000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mov z26.d, #0x2000000
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x1000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z3.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z4.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x8000000
; NOSVE2BITPERM-NEXT:    mov z28.d, #0x4000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mov z26.d, #0x20000000
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x10000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z3.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z4.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x80000000
; NOSVE2BITPERM-NEXT:    mov z28.d, #0x40000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mov z26.d, #0x4000000000
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x20000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z3.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x100000000
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x400000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x200000000
; NOSVE2BITPERM-NEXT:    mov z28.d, #0x10000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z1.d, z3.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x800000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x1000000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x2000000000
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x8000000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x10000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x20000000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x80000000000
; NOSVE2BITPERM-NEXT:    mov z26.d, #0x40000000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x200000000000
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x100000000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x800000000000
; NOSVE2BITPERM-NEXT:    mov z26.d, #0x400000000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x2000000000000
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x1000000000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x8000000000000
; NOSVE2BITPERM-NEXT:    mov z26.d, #0x4000000000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x20000000000000
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x10000000000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x80000000000000
; NOSVE2BITPERM-NEXT:    mov z26.d, #0x40000000000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x200000000000000
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x100000000000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x800000000000000
; NOSVE2BITPERM-NEXT:    mov z26.d, #0x400000000000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    mov z3.d, #0x2000000000000000
; NOSVE2BITPERM-NEXT:    mov z4.d, #0x1000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mov z5.d, #0x8000000000000000
; NOSVE2BITPERM-NEXT:    mov z26.d, #0x4000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mov z26.d, #16384 // =0x4000
; NOSVE2BITPERM-NEXT:    eor3 z6.d, z6.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    bic z0.d, z0.d, z6.d
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #2
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #1
; NOSVE2BITPERM-NEXT:    movprfx z3, z0
; NOSVE2BITPERM-NEXT:    mul z3.d, z3.d, #8
; NOSVE2BITPERM-NEXT:    movprfx z4, z0
; NOSVE2BITPERM-NEXT:    mul z4.d, z4.d, #4
; NOSVE2BITPERM-NEXT:    eor z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #32
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #16
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z4.d, z3.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z30.d
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #64
; NOSVE2BITPERM-NEXT:    mov z30.d, #0x40000
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z31.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z25.d
; NOSVE2BITPERM-NEXT:    mov z25.d, #32768 // =0x8000
; NOSVE2BITPERM-NEXT:    mov z31.d, #0x200000
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x10000000000
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x100000000000
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z2.d, #4096 // =0x1000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z22.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z25.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z29.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z30.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z31.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z8.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z9.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z10.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z11.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z12.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z13.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z14.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z16.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z17.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z15.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z18.d
; NOSVE2BITPERM-NEXT:    mov z18.d, #0x8000000000
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x100000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z19.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z20.d
; NOSVE2BITPERM-NEXT:    mov z19.d, #0x2000000000
; NOSVE2BITPERM-NEXT:    mov z20.d, #0x1000000000
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z19.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z20.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x4000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z18.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z21.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z21.d, #0x80000000000
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x40000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z21.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z23.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    mov z23.d, #0x800000000000
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x400000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z23.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x2000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x1000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x8000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x4000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x10000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x80000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x40000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x100000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x400000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x2000000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x1000000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x8000000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x4000000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z5.d, z5.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    bic z0.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    movprfx z4, z0
; NOSVE2BITPERM-NEXT:    mul z4.d, z4.d, #2
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #1
; NOSVE2BITPERM-NEXT:    movprfx z3, z0
; NOSVE2BITPERM-NEXT:    mul z3.d, z3.d, #8
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #4
; NOSVE2BITPERM-NEXT:    eor z4.d, z2.d, z4.d
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #16
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z1.d, z3.d
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #32
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #128 // =0x80
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #64
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #512 // =0x200
; NOSVE2BITPERM-NEXT:    mov z2.d, #256 // =0x100
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #2048 // =0x800
; NOSVE2BITPERM-NEXT:    mov z2.d, #1024 // =0x400
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z2.d, #4096 // =0x1000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z22.d
; NOSVE2BITPERM-NEXT:    mov z22.d, #8192 // =0x2000
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z25.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mov z26.d, #16384 // =0x4000
; NOSVE2BITPERM-NEXT:    mov z25.d, #0x4000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x2000000000000000
; NOSVE2BITPERM-NEXT:    mov z28.d, #0x1000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z29.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z30.d
; NOSVE2BITPERM-NEXT:    mov z29.d, #0x800000000000000
; NOSVE2BITPERM-NEXT:    mov z30.d, #0x400000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z31.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z8.d
; NOSVE2BITPERM-NEXT:    mov z31.d, #0x200000000000000
; NOSVE2BITPERM-NEXT:    mov z8.d, #0x100000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z9.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z10.d
; NOSVE2BITPERM-NEXT:    mov z9.d, #0x80000000000000
; NOSVE2BITPERM-NEXT:    mov z10.d, #0x40000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z11.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z12.d
; NOSVE2BITPERM-NEXT:    mov z11.d, #0x20000000000000
; NOSVE2BITPERM-NEXT:    mov z12.d, #0x10000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z13.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z14.d
; NOSVE2BITPERM-NEXT:    mov z13.d, #0x8000000000000
; NOSVE2BITPERM-NEXT:    mov z14.d, #0x4000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z16.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z17.d
; NOSVE2BITPERM-NEXT:    mov z17.d, #0x400000000000
; NOSVE2BITPERM-NEXT:    mov z16.d, #0x1000000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x40000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z15.d
; NOSVE2BITPERM-NEXT:    mov z15.d, #0x2000000000000
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x100000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x400000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z19.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z20.d
; NOSVE2BITPERM-NEXT:    mov z19.d, #0x2000000000
; NOSVE2BITPERM-NEXT:    mov z20.d, #0x1000000000
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x4000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z18.d
; NOSVE2BITPERM-NEXT:    mov z18.d, #0x8000000000
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000000000
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x40000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z21.d
; NOSVE2BITPERM-NEXT:    mov z21.d, #0x800000000000
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000000
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x8000000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x400000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z23.d
; NOSVE2BITPERM-NEXT:    mov z23.d, #4096 // =0x1000
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x2000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x1000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x8000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x4000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x10000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x80000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x40000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x100000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x400000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x2000000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x1000000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x8000000000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x4000000000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z4.d, z4.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    bic z0.d, z0.d, z4.d
; NOSVE2BITPERM-NEXT:    movprfx z3, z0
; NOSVE2BITPERM-NEXT:    mul z3.d, z3.d, #2
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #1
; NOSVE2BITPERM-NEXT:    movprfx z7, z0
; NOSVE2BITPERM-NEXT:    mul z7.d, z7.d, #8
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #4
; NOSVE2BITPERM-NEXT:    eor z3.d, z2.d, z3.d
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #16
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z1.d, z7.d
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #32
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #128 // =0x80
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #64
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #512 // =0x200
; NOSVE2BITPERM-NEXT:    mov z2.d, #256 // =0x100
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #2048 // =0x800
; NOSVE2BITPERM-NEXT:    mov z2.d, #1024 // =0x400
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z2.d, #4096 // =0x1000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z22.d
; NOSVE2BITPERM-NEXT:    mov z22.d, #8192 // =0x2000
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #32768 // =0x8000
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mov z26.d, #8192 // =0x2000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x10000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x80000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x40000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x100000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x400000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x2000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x1000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x8000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x4000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x10000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x80000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x40000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x100000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x400000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z19.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z20.d
; NOSVE2BITPERM-NEXT:    mov z20.d, #0x400000000000
; NOSVE2BITPERM-NEXT:    mov z19.d, #0x20000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x4000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z18.d
; NOSVE2BITPERM-NEXT:    mov z18.d, #0x1000000000000
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x10000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x80000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x40000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000000
; NOSVE2BITPERM-NEXT:    mov z2.d, #0x100000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z21.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z17.d
; NOSVE2BITPERM-NEXT:    mov z21.d, #0x800000000000
; NOSVE2BITPERM-NEXT:    mov z17.d, #0x2000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z15.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z16.d
; NOSVE2BITPERM-NEXT:    mov z16.d, #0x8000000000000
; NOSVE2BITPERM-NEXT:    mov z15.d, #0x4000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z13.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z14.d
; NOSVE2BITPERM-NEXT:    mov z13.d, #0x20000000000000
; NOSVE2BITPERM-NEXT:    mov z14.d, #0x10000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z11.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z12.d
; NOSVE2BITPERM-NEXT:    mov z12.d, #0x80000000000000
; NOSVE2BITPERM-NEXT:    mov z11.d, #0x40000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z9.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z10.d
; NOSVE2BITPERM-NEXT:    mov z9.d, #0x200000000000000
; NOSVE2BITPERM-NEXT:    mov z10.d, #0x100000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z31.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z8.d
; NOSVE2BITPERM-NEXT:    mov z8.d, #0x800000000000000
; NOSVE2BITPERM-NEXT:    mov z31.d, #0x400000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z29.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z30.d
; NOSVE2BITPERM-NEXT:    mov z29.d, #0x2000000000000000
; NOSVE2BITPERM-NEXT:    mov z30.d, #0x1000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x8000000000000000
; NOSVE2BITPERM-NEXT:    mov z28.d, #16384 // =0x4000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    mul z2.d, z0.d, z25.d
; NOSVE2BITPERM-NEXT:    mov z25.d, #0x4000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z3.d, z3.d, z2.d, z1.d
; NOSVE2BITPERM-NEXT:    bic z0.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    movprfx z24, z0
; NOSVE2BITPERM-NEXT:    mul z24.d, z24.d, #2
; NOSVE2BITPERM-NEXT:    movprfx z2, z0
; NOSVE2BITPERM-NEXT:    mul z2.d, z2.d, #1
; NOSVE2BITPERM-NEXT:    movprfx z7, z0
; NOSVE2BITPERM-NEXT:    mul z7.d, z7.d, #8
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #4
; NOSVE2BITPERM-NEXT:    eor z2.d, z2.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z1.d, z7.d
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #32
; NOSVE2BITPERM-NEXT:    movprfx z7, z0
; NOSVE2BITPERM-NEXT:    mul z7.d, z7.d, #16
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #128 // =0x80
; NOSVE2BITPERM-NEXT:    movprfx z7, z0
; NOSVE2BITPERM-NEXT:    mul z7.d, z7.d, #64
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #512 // =0x200
; NOSVE2BITPERM-NEXT:    mov z7.d, #256 // =0x100
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #2048 // =0x800
; NOSVE2BITPERM-NEXT:    mov z7.d, #1024 // =0x400
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z22.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z23.d
; NOSVE2BITPERM-NEXT:    mov z22.d, #4096 // =0x1000
; NOSVE2BITPERM-NEXT:    mov z23.d, #32768 // =0x8000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #32768 // =0x8000
; NOSVE2BITPERM-NEXT:    mov z7.d, #16384 // =0x4000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x10000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x80000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x40000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x100000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x400000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x2000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x1000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x8000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x4000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x10000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x80000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x40000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x100000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x800000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x400000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x2000000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x1000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x8000000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x4000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x20000000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x10000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x80000000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x40000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mov z1.d, #0x200000000000
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x100000000000
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z21.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z20.d
; NOSVE2BITPERM-NEXT:    mov z21.d, #0x800000000000
; NOSVE2BITPERM-NEXT:    mov z20.d, #0x400000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z17.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z18.d
; NOSVE2BITPERM-NEXT:    mov z17.d, #0x1000000000000
; NOSVE2BITPERM-NEXT:    mov z18.d, #0x20000000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z16.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z15.d
; NOSVE2BITPERM-NEXT:    mov z15.d, #0x4000000000000
; NOSVE2BITPERM-NEXT:    mov z16.d, #0x8000000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z13.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z14.d
; NOSVE2BITPERM-NEXT:    mov z13.d, #0x10000000000000
; NOSVE2BITPERM-NEXT:    mov z14.d, #0x200000000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z12.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z11.d
; NOSVE2BITPERM-NEXT:    mov z12.d, #0x80000000000000
; NOSVE2BITPERM-NEXT:    mov z11.d, #0x40000000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z9.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z10.d
; NOSVE2BITPERM-NEXT:    mov z9.d, #0x100000000000000
; NOSVE2BITPERM-NEXT:    mov z10.d, #0x2000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z8.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z31.d
; NOSVE2BITPERM-NEXT:    mov z8.d, #0x800000000000000
; NOSVE2BITPERM-NEXT:    mov z31.d, #0x400000000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z29.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z30.d
; NOSVE2BITPERM-NEXT:    mov z29.d, #0x1000000000000000
; NOSVE2BITPERM-NEXT:    mov z30.d, #0x4000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    mul z1.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z25.d
; NOSVE2BITPERM-NEXT:    mov z27.d, #0x8000000000000000
; NOSVE2BITPERM-NEXT:    eor3 z2.d, z2.d, z7.d, z1.d
; NOSVE2BITPERM-NEXT:    bic z0.d, z0.d, z2.d
; NOSVE2BITPERM-NEXT:    movprfx z25, z0
; NOSVE2BITPERM-NEXT:    mul z25.d, z25.d, #2
; NOSVE2BITPERM-NEXT:    movprfx z1, z0
; NOSVE2BITPERM-NEXT:    mul z1.d, z1.d, #1
; NOSVE2BITPERM-NEXT:    movprfx z24, z0
; NOSVE2BITPERM-NEXT:    mul z24.d, z24.d, #8
; NOSVE2BITPERM-NEXT:    movprfx z7, z0
; NOSVE2BITPERM-NEXT:    mul z7.d, z7.d, #4
; NOSVE2BITPERM-NEXT:    eor z1.d, z1.d, z25.d
; NOSVE2BITPERM-NEXT:    mul z25.d, z0.d, z21.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z7.d, z24.d
; NOSVE2BITPERM-NEXT:    movprfx z7, z0
; NOSVE2BITPERM-NEXT:    mul z7.d, z7.d, #32
; NOSVE2BITPERM-NEXT:    movprfx z24, z0
; NOSVE2BITPERM-NEXT:    mul z24.d, z24.d, #16
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #128 // =0x80
; NOSVE2BITPERM-NEXT:    movprfx z24, z0
; NOSVE2BITPERM-NEXT:    mul z24.d, z24.d, #64
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #512 // =0x200
; NOSVE2BITPERM-NEXT:    mov z24.d, #256 // =0x100
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #2048 // =0x800
; NOSVE2BITPERM-NEXT:    mov z24.d, #1024 // =0x400
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z22.d
; NOSVE2BITPERM-NEXT:    ldr z26, [sp] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z23.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z28.d
; NOSVE2BITPERM-NEXT:    and z6.d, z6.d, z26.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x10000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z19.d
; NOSVE2BITPERM-NEXT:    mul z19.d, z0.d, z20.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x80000
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x40000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x200000
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x100000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x800000
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x400000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x2000000
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x1000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x8000000
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x4000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x20000000
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x10000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x80000000
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x40000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x200000000
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x100000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x800000000
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x400000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x2000000000
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x1000000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x8000000000
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x4000000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x20000000000
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x10000000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x80000000000
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x40000000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    mov z7.d, #0x200000000000
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x100000000000
; NOSVE2BITPERM-NEXT:    mul z7.d, z0.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z24.d, z7.d
; NOSVE2BITPERM-NEXT:    eor z7.d, z26.d, z6.d
; NOSVE2BITPERM-NEXT:    lsr z24.d, z6.d, #1
; NOSVE2BITPERM-NEXT:    orr z7.d, z7.d, z24.d
; NOSVE2BITPERM-NEXT:    mov z24.d, #0x2000000000000
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z19.d, z25.d
; NOSVE2BITPERM-NEXT:    mul z25.d, z0.d, z17.d
; NOSVE2BITPERM-NEXT:    and z5.d, z5.d, z7.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    eor z7.d, z7.d, z5.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z25.d, z24.d
; NOSVE2BITPERM-NEXT:    mul z25.d, z0.d, z15.d
; NOSVE2BITPERM-NEXT:    lsr z15.d, z5.d, #2
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z16.d
; NOSVE2BITPERM-NEXT:    orr z7.d, z7.d, z15.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z25.d, z24.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z18.d
; NOSVE2BITPERM-NEXT:    mul z25.d, z0.d, z13.d
; NOSVE2BITPERM-NEXT:    and z4.d, z4.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z25.d, z24.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z12.d
; NOSVE2BITPERM-NEXT:    mul z25.d, z0.d, z11.d
; NOSVE2BITPERM-NEXT:    eor z7.d, z7.d, z4.d
; NOSVE2BITPERM-NEXT:    lsr z11.d, z4.d, #4
; NOSVE2BITPERM-NEXT:    orr z7.d, z7.d, z11.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z25.d, z24.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z14.d
; NOSVE2BITPERM-NEXT:    mul z25.d, z0.d, z9.d
; NOSVE2BITPERM-NEXT:    and z3.d, z3.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z25.d, z24.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z8.d
; NOSVE2BITPERM-NEXT:    mul z25.d, z0.d, z31.d
; NOSVE2BITPERM-NEXT:    eor z7.d, z7.d, z3.d
; NOSVE2BITPERM-NEXT:    lsr z31.d, z3.d, #8
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z25.d, z24.d
; NOSVE2BITPERM-NEXT:    orr z7.d, z7.d, z31.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z10.d
; NOSVE2BITPERM-NEXT:    mul z25.d, z0.d, z29.d
; NOSVE2BITPERM-NEXT:    and z2.d, z2.d, z7.d
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z25.d, z24.d
; NOSVE2BITPERM-NEXT:    mul z24.d, z0.d, z27.d
; NOSVE2BITPERM-NEXT:    mul z0.d, z0.d, z30.d
; NOSVE2BITPERM-NEXT:    eor z7.d, z7.d, z2.d
; NOSVE2BITPERM-NEXT:    lsr z25.d, z2.d, #16
; NOSVE2BITPERM-NEXT:    eor3 z1.d, z1.d, z0.d, z24.d
; NOSVE2BITPERM-NEXT:    orr z0.d, z7.d, z25.d
; NOSVE2BITPERM-NEXT:    ldr z7, [sp, #1, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    and z0.d, z1.d, z0.d
; NOSVE2BITPERM-NEXT:    lsl z1.d, z7.d, #32
; NOSVE2BITPERM-NEXT:    bsl z1.d, z1.d, z7.d, z0.d
; NOSVE2BITPERM-NEXT:    lsl z0.d, z1.d, #16
; NOSVE2BITPERM-NEXT:    bsl z0.d, z0.d, z1.d, z2.d
; NOSVE2BITPERM-NEXT:    lsl z1.d, z0.d, #8
; NOSVE2BITPERM-NEXT:    bsl z1.d, z1.d, z0.d, z3.d
; NOSVE2BITPERM-NEXT:    lsl z0.d, z1.d, #4
; NOSVE2BITPERM-NEXT:    bsl z0.d, z0.d, z1.d, z4.d
; NOSVE2BITPERM-NEXT:    lsl z1.d, z0.d, #2
; NOSVE2BITPERM-NEXT:    bsl z1.d, z1.d, z0.d, z5.d
; NOSVE2BITPERM-NEXT:    lsl z0.d, z1.d, #1
; NOSVE2BITPERM-NEXT:    bsl z0.d, z0.d, z1.d, z6.d
; NOSVE2BITPERM-NEXT:    and z0.d, z0.d, z26.d
; NOSVE2BITPERM-NEXT:    addvl sp, sp, #2
; NOSVE2BITPERM-NEXT:    ldr z23, [sp] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z22, [sp, #1, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z21, [sp, #2, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z20, [sp, #3, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z19, [sp, #4, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z18, [sp, #5, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z17, [sp, #6, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z16, [sp, #7, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z15, [sp, #8, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z14, [sp, #9, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z13, [sp, #10, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z12, [sp, #11, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z11, [sp, #12, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z10, [sp, #13, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z9, [sp, #14, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ldr z8, [sp, #15, mul vl] // 16-byte Folded Reload
; NOSVE2BITPERM-NEXT:    addvl sp, sp, #16
; NOSVE2BITPERM-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; NOSVE2BITPERM-NEXT:    ret
  %res = call <vscale x 2 x i64> @llvm.bdep.nxv2i64(<vscale x 2 x i64> %val, <vscale x 2 x i64> %mask)
  ret <vscale x 2 x i64> %res
}

declare i8 @llvm.bext.i8(i8, i8)
declare i16 @llvm.bext.i16(i16, i16)
declare i32 @llvm.bext.i32(i32, i32)
declare i64 @llvm.bext.i64(i64, i64)
declare i8 @llvm.bdep.i8(i8, i8)
declare i16 @llvm.bdep.i16(i16, i16)
declare i32 @llvm.bdep.i32(i32, i32)
declare i64 @llvm.bdep.i64(i64, i64)
declare <vscale x 16 x i8> @llvm.bext.nxv16i8(<vscale x 16 x i8>, <vscale x 16 x i8>)
declare <vscale x 8 x i16> @llvm.bext.nxv8i16(<vscale x 8 x i16>, <vscale x 8 x i16>)
declare <vscale x 4 x i32> @llvm.bext.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.bext.nxv2i64(<vscale x 2 x i64>, <vscale x 2 x i64>)
declare <vscale x 16 x i8> @llvm.bdep.nxv16i8(<vscale x 16 x i8>, <vscale x 16 x i8>)
declare <vscale x 8 x i16> @llvm.bdep.nxv8i16(<vscale x 8 x i16>, <vscale x 8 x i16>)
declare <vscale x 4 x i32> @llvm.bdep.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.bdep.nxv2i64(<vscale x 2 x i64>, <vscale x 2 x i64>)
