; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=aarch64-apple-ios -disable-post-ra | FileCheck %s

; Part of PR21549: going through the stack isn't ideal but is correct.

define i16 @test_bitcast_v2i8_to_i16(<2 x i8> %a) {
; CHECK-LABEL: test_bitcast_v2i8_to_i16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub sp, sp, #16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    ; kill: def $d0 killed $d0 def $q0
; CHECK-NEXT:    mov.s v1[0], v0[1]
; CHECK-NEXT:    str b0, [sp, #14]
; CHECK-NEXT:    stur b1, [sp, #15]
; CHECK-NEXT:    ldrh w0, [sp, #14]
; CHECK-NEXT:    add sp, sp, #16
; CHECK-NEXT:    ret

  %aa = bitcast <2 x i8> %a to i16
  ret i16 %aa
}
