; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -o - -O0 %s | FileCheck %s
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
target triple = "arm64-apple-ios5.0.0"

; This test checks we don't fail isel due to unhandled build_pair nodes.
define void @compare_and_swap128() {
; CHECK-LABEL: compare_and_swap128:
; CHECK:       // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    nop
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    // implicit-def: $x9
; CHECK-NEXT:    mov w9, w10
; CHECK-NEXT:    mov w8, w8
; CHECK-NEXT:    // kill: def $x8 killed $w8
; CHECK-NEXT:    orr x8, x8, x9, lsl #32
; CHECK-NEXT:    // implicit-def: $x9
; CHECK-NEXT:    str x8, [x9]
; CHECK-NEXT:    ret
  %1 = call i128 asm sideeffect "nop", "=r,~{memory}"()
  store i128 %1, i128* undef, align 16
  ret void
}
