; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64 -mattr=+fuse-adrp-add < %s | FileCheck %s --check-prefixes=CHECK,FUSE
; RUN: llc -mtriple=aarch64 -mattr=-fuse-adrp-add < %s | FileCheck %s --check-prefixes=CHECK,NO-FUSE

@str = private constant [1 x i8] c"\00"

declare void @clobber_regs()

define ptr @test_movaddr_cheap_rematerialization() {
; FUSE-LABEL: test_movaddr_cheap_rematerialization:
; FUSE:       // %bb.0:
; FUSE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; FUSE-NEXT:    .cfi_def_cfa_offset 16
; FUSE-NEXT:    .cfi_offset w30, -16
; FUSE-NEXT:    bl clobber_regs
; FUSE-NEXT:    adrp x0, .Lstr
; FUSE-NEXT:    add x0, x0, :lo12:.Lstr
; FUSE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; FUSE-NEXT:    ret
;
; NO-FUSE-LABEL: test_movaddr_cheap_rematerialization:
; NO-FUSE:       // %bb.0:
; NO-FUSE-NEXT:    stp x30, x19, [sp, #-16]! // 16-byte Folded Spill
; NO-FUSE-NEXT:    .cfi_def_cfa_offset 16
; NO-FUSE-NEXT:    .cfi_offset w19, -8
; NO-FUSE-NEXT:    .cfi_offset w30, -16
; NO-FUSE-NEXT:    adrp x19, .Lstr
; NO-FUSE-NEXT:    add x19, x19, :lo12:.Lstr
; NO-FUSE-NEXT:    bl clobber_regs
; NO-FUSE-NEXT:    mov x0, x19
; NO-FUSE-NEXT:    ldp x30, x19, [sp], #16 // 16-byte Folded Reload
; NO-FUSE-NEXT:    ret
  %p = getelementptr [10 x i8], ptr @str, i64 0, i64 0
  call void @clobber_regs()
  ret ptr %p
}

define ptr @test_movaddr_not_cheap_with_tagged() "target-features"="+tagged-globals" {
; CHECK-LABEL: test_movaddr_not_cheap_with_tagged:
; CHECK:       // %bb.0:
; CHECK-NEXT:    stp x30, x19, [sp, #-16]! // 16-byte Folded Spill
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset w19, -8
; CHECK-NEXT:    .cfi_offset w30, -16
; CHECK-NEXT:    adrp x19, :pg_hi21_nc:.Lstr
; CHECK-NEXT:    movk x19, #:prel_g3:.Lstr+4294967296
; CHECK-NEXT:    add x19, x19, :lo12:.Lstr
; CHECK-NEXT:    bl clobber_regs
; CHECK-NEXT:    mov x0, x19
; CHECK-NEXT:    ldp x30, x19, [sp], #16 // 16-byte Folded Reload
; CHECK-NEXT:    ret
  %p = getelementptr [10 x i8], ptr @str, i64 0, i64 0
  call void @clobber_regs()
  ret ptr %p
}
