; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-linux-unknown-gnu %s -o - | FileCheck %s --check-prefixes=CHECK,CHECK-NEON
; RUN: llc -mtriple=aarch64-linux-unknown-gnu %s -o - -mattr=+aes | FileCheck %s --check-prefixes=CHECK,CHECK-AES

define i8 @clmul_i8(i8 %x, i8 %y) {
; CHECK-LABEL: clmul_i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fmov s0, w1
; CHECK-NEXT:    fmov s1, w0
; CHECK-NEXT:    pmul v0.8b, v1.8b, v0.8b
; CHECK-NEXT:    fmov w0, s0
; CHECK-NEXT:    ret
  %a = call i8 @llvm.clmul.i8(i8 %x, i8 %y)
  ret i8 %a
}

define i16 @clmul_i16(i16 %x, i16 %y) {
; CHECK-NEON-LABEL: clmul_i16:
; CHECK-NEON:       // %bb.0:
; CHECK-NEON-NEXT:    mov w8, #-28087 // =0xffff9249
; CHECK-NEON-NEXT:    mov w9, #9362 // =0x2492
; CHECK-NEON-NEXT:    mov w15, #18724 // =0x4924
; CHECK-NEON-NEXT:    and w10, w1, w8
; CHECK-NEON-NEXT:    and w11, w0, w9
; CHECK-NEON-NEXT:    and w12, w1, w9
; CHECK-NEON-NEXT:    and w13, w0, w8
; CHECK-NEON-NEXT:    and w17, w1, w15
; CHECK-NEON-NEXT:    and w18, w0, w15
; CHECK-NEON-NEXT:    mul w14, w11, w10
; CHECK-NEON-NEXT:    mul w16, w13, w12
; CHECK-NEON-NEXT:    mul w0, w18, w17
; CHECK-NEON-NEXT:    mul w1, w11, w17
; CHECK-NEON-NEXT:    mul w17, w13, w17
; CHECK-NEON-NEXT:    eor w14, w16, w14
; CHECK-NEON-NEXT:    mul w13, w13, w10
; CHECK-NEON-NEXT:    eor w14, w14, w0
; CHECK-NEON-NEXT:    mul w11, w11, w12
; CHECK-NEON-NEXT:    and w9, w14, w9
; CHECK-NEON-NEXT:    mul w12, w18, w12
; CHECK-NEON-NEXT:    mul w10, w18, w10
; CHECK-NEON-NEXT:    eor w13, w13, w1
; CHECK-NEON-NEXT:    eor w11, w17, w11
; CHECK-NEON-NEXT:    eor w12, w13, w12
; CHECK-NEON-NEXT:    and w8, w12, w8
; CHECK-NEON-NEXT:    eor w10, w11, w10
; CHECK-NEON-NEXT:    orr w8, w8, w9
; CHECK-NEON-NEXT:    and w9, w10, w15
; CHECK-NEON-NEXT:    orr w0, w8, w9
; CHECK-NEON-NEXT:    ret
;
; CHECK-AES-LABEL: clmul_i16:
; CHECK-AES:       // %bb.0:
; CHECK-AES-NEXT:    fmov s0, w1
; CHECK-AES-NEXT:    fmov s1, w0
; CHECK-AES-NEXT:    pmull v0.1q, v1.1d, v0.1d
; CHECK-AES-NEXT:    fmov w0, s0
; CHECK-AES-NEXT:    ret
  %a = call i16 @llvm.clmul.i16(i16 %x, i16 %y)
  ret i16 %a
}

define i32 @clmul_i32(i32 %x, i32 %y) {
; CHECK-NEON-LABEL: clmul_i32:
; CHECK-NEON:       // %bb.0:
; CHECK-NEON-NEXT:    and w8, w1, #0x11111111
; CHECK-NEON-NEXT:    and w9, w0, #0x22222222
; CHECK-NEON-NEXT:    and w10, w1, #0x22222222
; CHECK-NEON-NEXT:    and w11, w0, #0x11111111
; CHECK-NEON-NEXT:    and w13, w1, #0x88888888
; CHECK-NEON-NEXT:    and w15, w0, #0x44444444
; CHECK-NEON-NEXT:    and w17, w1, #0x44444444
; CHECK-NEON-NEXT:    and w18, w0, #0x88888888
; CHECK-NEON-NEXT:    mul w12, w9, w8
; CHECK-NEON-NEXT:    mul w14, w11, w10
; CHECK-NEON-NEXT:    mul w16, w15, w13
; CHECK-NEON-NEXT:    mul w0, w18, w17
; CHECK-NEON-NEXT:    mul w1, w9, w13
; CHECK-NEON-NEXT:    eor w12, w14, w12
; CHECK-NEON-NEXT:    mul w2, w11, w8
; CHECK-NEON-NEXT:    mul w3, w15, w17
; CHECK-NEON-NEXT:    eor w14, w16, w0
; CHECK-NEON-NEXT:    mul w4, w18, w10
; CHECK-NEON-NEXT:    eor w12, w12, w14
; CHECK-NEON-NEXT:    mul w5, w9, w10
; CHECK-NEON-NEXT:    eor w14, w2, w1
; CHECK-NEON-NEXT:    and w12, w12, #0x22222222
; CHECK-NEON-NEXT:    mul w9, w9, w17
; CHECK-NEON-NEXT:    mul w17, w11, w17
; CHECK-NEON-NEXT:    eor w16, w3, w4
; CHECK-NEON-NEXT:    mul w10, w15, w10
; CHECK-NEON-NEXT:    mul w15, w15, w8
; CHECK-NEON-NEXT:    mul w11, w11, w13
; CHECK-NEON-NEXT:    eor w17, w17, w5
; CHECK-NEON-NEXT:    mul w13, w18, w13
; CHECK-NEON-NEXT:    mul w8, w18, w8
; CHECK-NEON-NEXT:    eor w9, w11, w9
; CHECK-NEON-NEXT:    eor w13, w15, w13
; CHECK-NEON-NEXT:    eor w8, w10, w8
; CHECK-NEON-NEXT:    eor w10, w14, w16
; CHECK-NEON-NEXT:    eor w11, w17, w13
; CHECK-NEON-NEXT:    eor w8, w9, w8
; CHECK-NEON-NEXT:    and w9, w10, #0x11111111
; CHECK-NEON-NEXT:    and w10, w11, #0x44444444
; CHECK-NEON-NEXT:    and w8, w8, #0x88888888
; CHECK-NEON-NEXT:    orr w9, w9, w12
; CHECK-NEON-NEXT:    orr w8, w10, w8
; CHECK-NEON-NEXT:    orr w0, w9, w8
; CHECK-NEON-NEXT:    ret
;
; CHECK-AES-LABEL: clmul_i32:
; CHECK-AES:       // %bb.0:
; CHECK-AES-NEXT:    fmov s0, w0
; CHECK-AES-NEXT:    fmov s1, w1
; CHECK-AES-NEXT:    pmull v0.1q, v0.1d, v1.1d
; CHECK-AES-NEXT:    fmov w0, s0
; CHECK-AES-NEXT:    ret
  %a = call i32 @llvm.clmul.i32(i32 %x, i32 %y)
  ret i32 %a
}

define i64 @clmul_i64(i64 %x, i64 %y) {
; CHECK-NEON-LABEL: clmul_i64:
; CHECK-NEON:       // %bb.0:
; CHECK-NEON-NEXT:    and x8, x1, #0x1111111111111111
; CHECK-NEON-NEXT:    and x9, x0, #0x2222222222222222
; CHECK-NEON-NEXT:    and x11, x1, #0x2222222222222222
; CHECK-NEON-NEXT:    and x12, x0, #0x1111111111111111
; CHECK-NEON-NEXT:    and x14, x1, #0x8888888888888888
; CHECK-NEON-NEXT:    and x15, x0, #0x4444444444444444
; CHECK-NEON-NEXT:    and x17, x1, #0x4444444444444444
; CHECK-NEON-NEXT:    and x18, x0, #0x8888888888888888
; CHECK-NEON-NEXT:    mul x10, x9, x8
; CHECK-NEON-NEXT:    mul x13, x12, x11
; CHECK-NEON-NEXT:    mul x16, x15, x14
; CHECK-NEON-NEXT:    mul x0, x18, x17
; CHECK-NEON-NEXT:    eor x10, x13, x10
; CHECK-NEON-NEXT:    mul x1, x9, x14
; CHECK-NEON-NEXT:    mul x2, x12, x8
; CHECK-NEON-NEXT:    eor x13, x16, x0
; CHECK-NEON-NEXT:    mul x3, x15, x17
; CHECK-NEON-NEXT:    eor x10, x10, x13
; CHECK-NEON-NEXT:    and x10, x10, #0x2222222222222222
; CHECK-NEON-NEXT:    mul x4, x18, x11
; CHECK-NEON-NEXT:    eor x13, x2, x1
; CHECK-NEON-NEXT:    mul x5, x9, x11
; CHECK-NEON-NEXT:    mul x9, x9, x17
; CHECK-NEON-NEXT:    eor x16, x3, x4
; CHECK-NEON-NEXT:    mul x17, x12, x17
; CHECK-NEON-NEXT:    mul x11, x15, x11
; CHECK-NEON-NEXT:    mul x15, x15, x8
; CHECK-NEON-NEXT:    eor x17, x17, x5
; CHECK-NEON-NEXT:    mul x12, x12, x14
; CHECK-NEON-NEXT:    mul x14, x18, x14
; CHECK-NEON-NEXT:    mul x8, x18, x8
; CHECK-NEON-NEXT:    eor x9, x12, x9
; CHECK-NEON-NEXT:    eor x14, x15, x14
; CHECK-NEON-NEXT:    eor x12, x17, x14
; CHECK-NEON-NEXT:    eor x8, x11, x8
; CHECK-NEON-NEXT:    eor x11, x13, x16
; CHECK-NEON-NEXT:    eor x8, x9, x8
; CHECK-NEON-NEXT:    and x9, x11, #0x1111111111111111
; CHECK-NEON-NEXT:    and x11, x12, #0x4444444444444444
; CHECK-NEON-NEXT:    and x8, x8, #0x8888888888888888
; CHECK-NEON-NEXT:    orr x9, x9, x10
; CHECK-NEON-NEXT:    orr x8, x11, x8
; CHECK-NEON-NEXT:    orr x0, x9, x8
; CHECK-NEON-NEXT:    ret
;
; CHECK-AES-LABEL: clmul_i64:
; CHECK-AES:       // %bb.0:
; CHECK-AES-NEXT:    fmov d0, x1
; CHECK-AES-NEXT:    fmov d1, x0
; CHECK-AES-NEXT:    pmull v0.1q, v1.1d, v0.1d
; CHECK-AES-NEXT:    fmov x0, d0
; CHECK-AES-NEXT:    ret
  %a = call i64 @llvm.clmul.i64(i64 %x, i64 %y)
  ret i64 %a
}


define i128 @clmul_i128(i128 %x, i128 %y) {
; CHECK-NEON-LABEL: clmul_i128:
; CHECK-NEON:       // %bb.0:
; CHECK-NEON-NEXT:    sub sp, sp, #352
; CHECK-NEON-NEXT:    stp x29, x30, [sp, #256] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    stp x28, x27, [sp, #272] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    stp x26, x25, [sp, #288] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    stp x24, x23, [sp, #304] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    stp x22, x21, [sp, #320] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    stp x20, x19, [sp, #336] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    .cfi_def_cfa_offset 352
; CHECK-NEON-NEXT:    .cfi_offset w19, -8
; CHECK-NEON-NEXT:    .cfi_offset w20, -16
; CHECK-NEON-NEXT:    .cfi_offset w21, -24
; CHECK-NEON-NEXT:    .cfi_offset w22, -32
; CHECK-NEON-NEXT:    .cfi_offset w23, -40
; CHECK-NEON-NEXT:    .cfi_offset w24, -48
; CHECK-NEON-NEXT:    .cfi_offset w25, -56
; CHECK-NEON-NEXT:    .cfi_offset w26, -64
; CHECK-NEON-NEXT:    .cfi_offset w27, -72
; CHECK-NEON-NEXT:    .cfi_offset w28, -80
; CHECK-NEON-NEXT:    .cfi_offset w30, -88
; CHECK-NEON-NEXT:    .cfi_offset w29, -96
; CHECK-NEON-NEXT:    and x10, x2, #0x2222222222222222
; CHECK-NEON-NEXT:    and x12, x1, #0x1111111111111111
; CHECK-NEON-NEXT:    and x11, x2, #0x8888888888888888
; CHECK-NEON-NEXT:    mul x8, x12, x10
; CHECK-NEON-NEXT:    and x5, x1, #0x4444444444444444
; CHECK-NEON-NEXT:    and x21, x1, #0x2222222222222222
; CHECK-NEON-NEXT:    and x6, x2, #0x1111111111111111
; CHECK-NEON-NEXT:    rbit x13, x0
; CHECK-NEON-NEXT:    and x29, x0, #0x2222222222222222
; CHECK-NEON-NEXT:    mul x14, x21, x10
; CHECK-NEON-NEXT:    and x15, x13, #0x2222222222222222
; CHECK-NEON-NEXT:    and x17, x13, #0x1111111111111111
; CHECK-NEON-NEXT:    and x4, x13, #0x4444444444444444
; CHECK-NEON-NEXT:    and x13, x13, #0x8888888888888888
; CHECK-NEON-NEXT:    mul x26, x12, x11
; CHECK-NEON-NEXT:    str x8, [sp, #248] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x8, x5, x11
; CHECK-NEON-NEXT:    str x14, [sp, #88] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x9, x21, x6
; CHECK-NEON-NEXT:    mul x20, x5, x6
; CHECK-NEON-NEXT:    str x8, [sp, #240] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x8, x21, x11
; CHECK-NEON-NEXT:    mul x22, x5, x10
; CHECK-NEON-NEXT:    str x8, [sp, #232] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x8, x12, x6
; CHECK-NEON-NEXT:    str x8, [sp, #224] // 8-byte Spill
; CHECK-NEON-NEXT:    rbit x8, x2
; CHECK-NEON-NEXT:    and x14, x8, #0x1111111111111111
; CHECK-NEON-NEXT:    mul x16, x15, x14
; CHECK-NEON-NEXT:    str x16, [sp, #216] // 8-byte Spill
; CHECK-NEON-NEXT:    and x16, x8, #0x2222222222222222
; CHECK-NEON-NEXT:    mul x18, x17, x16
; CHECK-NEON-NEXT:    str x18, [sp, #208] // 8-byte Spill
; CHECK-NEON-NEXT:    and x18, x8, #0x8888888888888888
; CHECK-NEON-NEXT:    and x8, x8, #0x4444444444444444
; CHECK-NEON-NEXT:    mul x7, x4, x18
; CHECK-NEON-NEXT:    str x7, [sp, #200] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x7, x13, x8
; CHECK-NEON-NEXT:    str x7, [sp, #192] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x7, x15, x18
; CHECK-NEON-NEXT:    str x7, [sp, #184] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x7, x17, x14
; CHECK-NEON-NEXT:    str x7, [sp, #176] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x7, x4, x8
; CHECK-NEON-NEXT:    str x7, [sp, #168] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x7, x13, x16
; CHECK-NEON-NEXT:    str x7, [sp, #160] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x7, x15, x16
; CHECK-NEON-NEXT:    mul x15, x15, x8
; CHECK-NEON-NEXT:    mul x8, x17, x8
; CHECK-NEON-NEXT:    stp x15, x7, [sp, #144] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    str x8, [sp, #128] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x8, x4, x16
; CHECK-NEON-NEXT:    str x8, [sp, #136] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x8, x4, x14
; CHECK-NEON-NEXT:    str x8, [sp, #104] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x8, x17, x18
; CHECK-NEON-NEXT:    str x8, [sp, #120] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x8, x13, x18
; CHECK-NEON-NEXT:    str x8, [sp, #96] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x8, x13, x14
; CHECK-NEON-NEXT:    str x8, [sp, #112] // 8-byte Spill
; CHECK-NEON-NEXT:    and x8, x2, #0x4444444444444444
; CHECK-NEON-NEXT:    and x2, x0, #0x1111111111111111
; CHECK-NEON-NEXT:    mul x24, x12, x8
; CHECK-NEON-NEXT:    and x12, x1, #0x8888888888888888
; CHECK-NEON-NEXT:    and x1, x0, #0x8888888888888888
; CHECK-NEON-NEXT:    mul x27, x21, x8
; CHECK-NEON-NEXT:    and x21, x0, #0x4444444444444444
; CHECK-NEON-NEXT:    mul x14, x12, x8
; CHECK-NEON-NEXT:    mul x15, x12, x10
; CHECK-NEON-NEXT:    mul x18, x12, x11
; CHECK-NEON-NEXT:    mul x4, x12, x6
; CHECK-NEON-NEXT:    and x12, x3, #0x4444444444444444
; CHECK-NEON-NEXT:    mul x30, x1, x12
; CHECK-NEON-NEXT:    eor x18, x20, x18
; CHECK-NEON-NEXT:    eor x20, x26, x27
; CHECK-NEON-NEXT:    mul x28, x21, x12
; CHECK-NEON-NEXT:    eor x4, x22, x4
; CHECK-NEON-NEXT:    mul x13, x2, x12
; CHECK-NEON-NEXT:    mul x12, x29, x12
; CHECK-NEON-NEXT:    mul x19, x5, x8
; CHECK-NEON-NEXT:    and x5, x3, #0x2222222222222222
; CHECK-NEON-NEXT:    mul x16, x2, x5
; CHECK-NEON-NEXT:    stp x13, x12, [sp, #48] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    and x12, x3, #0x8888888888888888
; CHECK-NEON-NEXT:    and x3, x3, #0x1111111111111111
; CHECK-NEON-NEXT:    mul x0, x21, x12
; CHECK-NEON-NEXT:    eor x15, x19, x15
; CHECK-NEON-NEXT:    mul x7, x29, x12
; CHECK-NEON-NEXT:    mul x13, x1, x12
; CHECK-NEON-NEXT:    mul x12, x2, x12
; CHECK-NEON-NEXT:    mul x17, x1, x5
; CHECK-NEON-NEXT:    mul x25, x29, x5
; CHECK-NEON-NEXT:    str x12, [sp, #40] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x12, x21, x5
; CHECK-NEON-NEXT:    eor x17, x28, x17
; CHECK-NEON-NEXT:    ldp x28, x27, [sp, #272] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    mul x5, x21, x3
; CHECK-NEON-NEXT:    mul x23, x1, x3
; CHECK-NEON-NEXT:    stp x12, x13, [sp, #16] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    mul x12, x29, x3
; CHECK-NEON-NEXT:    mul x13, x2, x3
; CHECK-NEON-NEXT:    mul x3, x29, x6
; CHECK-NEON-NEXT:    eor x12, x16, x12
; CHECK-NEON-NEXT:    eor x16, x0, x30
; CHECK-NEON-NEXT:    eor x12, x12, x16
; CHECK-NEON-NEXT:    mul x0, x1, x10
; CHECK-NEON-NEXT:    eor x13, x13, x7
; CHECK-NEON-NEXT:    and x12, x12, #0x2222222222222222
; CHECK-NEON-NEXT:    eor x13, x13, x17
; CHECK-NEON-NEXT:    str x3, [sp, #80] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x3, x29, x11
; CHECK-NEON-NEXT:    and x13, x13, #0x1111111111111111
; CHECK-NEON-NEXT:    orr x12, x13, x12
; CHECK-NEON-NEXT:    ldp x17, x13, [sp, #40] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    eor x13, x13, x25
; CHECK-NEON-NEXT:    ldp x26, x25, [sp, #288] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    str x3, [sp, #72] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x3, x29, x10
; CHECK-NEON-NEXT:    str x3, [sp, #64] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x3, x29, x8
; CHECK-NEON-NEXT:    str x3, [sp, #32] // 8-byte Spill
; CHECK-NEON-NEXT:    ldr x3, [sp, #248] // 8-byte Reload
; CHECK-NEON-NEXT:    eor x3, x3, x9
; CHECK-NEON-NEXT:    ldr x9, [sp, #240] // 8-byte Reload
; CHECK-NEON-NEXT:    eor x9, x9, x14
; CHECK-NEON-NEXT:    mul x14, x1, x8
; CHECK-NEON-NEXT:    eor x9, x3, x9
; CHECK-NEON-NEXT:    ldp x29, x3, [sp, #224] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    and x9, x9, #0x2222222222222222
; CHECK-NEON-NEXT:    eor x3, x29, x3
; CHECK-NEON-NEXT:    ldp x29, x30, [sp, #256] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    eor x3, x3, x15
; CHECK-NEON-NEXT:    ldr x15, [sp, #88] // 8-byte Reload
; CHECK-NEON-NEXT:    and x3, x3, #0x1111111111111111
; CHECK-NEON-NEXT:    eor x19, x24, x15
; CHECK-NEON-NEXT:    orr x9, x3, x9
; CHECK-NEON-NEXT:    eor x3, x20, x4
; CHECK-NEON-NEXT:    eor x18, x19, x18
; CHECK-NEON-NEXT:    and x3, x3, #0x8888888888888888
; CHECK-NEON-NEXT:    mul x15, x21, x8
; CHECK-NEON-NEXT:    and x18, x18, #0x4444444444444444
; CHECK-NEON-NEXT:    orr x18, x18, x3
; CHECK-NEON-NEXT:    mul x4, x2, x10
; CHECK-NEON-NEXT:    orr x9, x9, x18
; CHECK-NEON-NEXT:    ldp x18, x16, [sp, #16] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    mul x10, x21, x10
; CHECK-NEON-NEXT:    eor x16, x5, x16
; CHECK-NEON-NEXT:    ldp x5, x3, [sp, #208] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    eor x13, x13, x16
; CHECK-NEON-NEXT:    ldr x16, [sp, #56] // 8-byte Reload
; CHECK-NEON-NEXT:    eor x18, x18, x23
; CHECK-NEON-NEXT:    and x13, x13, #0x4444444444444444
; CHECK-NEON-NEXT:    mul x8, x2, x8
; CHECK-NEON-NEXT:    eor x3, x5, x3
; CHECK-NEON-NEXT:    ldp x7, x5, [sp, #192] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    eor x16, x17, x16
; CHECK-NEON-NEXT:    mul x17, x21, x11
; CHECK-NEON-NEXT:    eor x16, x16, x18
; CHECK-NEON-NEXT:    ldp x24, x23, [sp, #304] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    eor x5, x5, x7
; CHECK-NEON-NEXT:    ldp x19, x7, [sp, #176] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    eor x18, x3, x5
; CHECK-NEON-NEXT:    ldr x5, [sp, #152] // 8-byte Reload
; CHECK-NEON-NEXT:    and x16, x16, #0x8888888888888888
; CHECK-NEON-NEXT:    and x18, x18, #0x2222222222222222
; CHECK-NEON-NEXT:    orr x13, x13, x16
; CHECK-NEON-NEXT:    eor x7, x19, x7
; CHECK-NEON-NEXT:    ldp x20, x19, [sp, #160] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    orr x12, x12, x13
; CHECK-NEON-NEXT:    eor x14, x17, x14
; CHECK-NEON-NEXT:    eor x9, x12, x9
; CHECK-NEON-NEXT:    eor x19, x19, x20
; CHECK-NEON-NEXT:    mul x20, x2, x6
; CHECK-NEON-NEXT:    eor x3, x7, x19
; CHECK-NEON-NEXT:    ldr x7, [sp, #128] // 8-byte Reload
; CHECK-NEON-NEXT:    and x3, x3, #0x1111111111111111
; CHECK-NEON-NEXT:    mul x2, x2, x11
; CHECK-NEON-NEXT:    eor x5, x7, x5
; CHECK-NEON-NEXT:    ldp x19, x7, [sp, #96] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    orr x16, x3, x18
; CHECK-NEON-NEXT:    mul x11, x1, x11
; CHECK-NEON-NEXT:    eor x7, x7, x19
; CHECK-NEON-NEXT:    mul x19, x21, x6
; CHECK-NEON-NEXT:    ldp x22, x21, [sp, #112] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    eor x5, x5, x7
; CHECK-NEON-NEXT:    ldr x7, [sp, #144] // 8-byte Reload
; CHECK-NEON-NEXT:    and x5, x5, #0x4444444444444444
; CHECK-NEON-NEXT:    eor x7, x21, x7
; CHECK-NEON-NEXT:    ldr x21, [sp, #136] // 8-byte Reload
; CHECK-NEON-NEXT:    eor x11, x19, x11
; CHECK-NEON-NEXT:    eor x21, x21, x22
; CHECK-NEON-NEXT:    eor x7, x7, x21
; CHECK-NEON-NEXT:    ldp x22, x21, [sp, #320] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    and x7, x7, #0x8888888888888888
; CHECK-NEON-NEXT:    orr x18, x5, x7
; CHECK-NEON-NEXT:    orr x13, x16, x18
; CHECK-NEON-NEXT:    ldr x18, [sp, #80] // 8-byte Reload
; CHECK-NEON-NEXT:    mul x16, x1, x6
; CHECK-NEON-NEXT:    rbit x13, x13
; CHECK-NEON-NEXT:    eor x18, x4, x18
; CHECK-NEON-NEXT:    eor x12, x18, x14
; CHECK-NEON-NEXT:    eor x1, x9, x13, lsr #1
; CHECK-NEON-NEXT:    eor x13, x15, x0
; CHECK-NEON-NEXT:    and x9, x12, #0x2222222222222222
; CHECK-NEON-NEXT:    ldp x14, x12, [sp, #64] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    eor x10, x10, x16
; CHECK-NEON-NEXT:    eor x8, x8, x14
; CHECK-NEON-NEXT:    ldr x14, [sp, #32] // 8-byte Reload
; CHECK-NEON-NEXT:    eor x12, x20, x12
; CHECK-NEON-NEXT:    eor x12, x12, x13
; CHECK-NEON-NEXT:    eor x8, x8, x11
; CHECK-NEON-NEXT:    eor x14, x2, x14
; CHECK-NEON-NEXT:    and x11, x12, #0x1111111111111111
; CHECK-NEON-NEXT:    and x8, x8, #0x4444444444444444
; CHECK-NEON-NEXT:    eor x10, x14, x10
; CHECK-NEON-NEXT:    ldp x20, x19, [sp, #336] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    and x10, x10, #0x8888888888888888
; CHECK-NEON-NEXT:    orr x9, x11, x9
; CHECK-NEON-NEXT:    orr x8, x8, x10
; CHECK-NEON-NEXT:    orr x0, x9, x8
; CHECK-NEON-NEXT:    add sp, sp, #352
; CHECK-NEON-NEXT:    ret
;
; CHECK-AES-LABEL: clmul_i128:
; CHECK-AES:       // %bb.0:
; CHECK-AES-NEXT:    rbit x8, x2
; CHECK-AES-NEXT:    rbit x9, x0
; CHECK-AES-NEXT:    fmov d0, x3
; CHECK-AES-NEXT:    fmov d1, x0
; CHECK-AES-NEXT:    fmov d2, x2
; CHECK-AES-NEXT:    fmov d3, x8
; CHECK-AES-NEXT:    fmov d4, x9
; CHECK-AES-NEXT:    pmull v0.1q, v1.1d, v0.1d
; CHECK-AES-NEXT:    pmull v3.1q, v4.1d, v3.1d
; CHECK-AES-NEXT:    fmov d4, x1
; CHECK-AES-NEXT:    pmull v1.1q, v1.1d, v2.1d
; CHECK-AES-NEXT:    pmull v4.1q, v4.1d, v2.1d
; CHECK-AES-NEXT:    fmov x10, d0
; CHECK-AES-NEXT:    fmov x8, d3
; CHECK-AES-NEXT:    fmov x0, d1
; CHECK-AES-NEXT:    fmov x9, d4
; CHECK-AES-NEXT:    rbit x8, x8
; CHECK-AES-NEXT:    eor x9, x10, x9
; CHECK-AES-NEXT:    eor x1, x9, x8, lsr #1
; CHECK-AES-NEXT:    ret
  %a = call i128 @llvm.clmul.i128(i128 %x, i128 %y)
  ret i128 %a
}

define i16 @clmul_i16_zext(i8 %x, i8 %y) {
; CHECK-NEON-LABEL: clmul_i16_zext:
; CHECK-NEON:       // %bb.0:
; CHECK-NEON-NEXT:    mov w8, #73 // =0x49
; CHECK-NEON-NEXT:    mov w9, #146 // =0x92
; CHECK-NEON-NEXT:    mov w13, #36 // =0x24
; CHECK-NEON-NEXT:    and w10, w1, w8
; CHECK-NEON-NEXT:    and w11, w0, w9
; CHECK-NEON-NEXT:    and w9, w1, w9
; CHECK-NEON-NEXT:    and w8, w0, w8
; CHECK-NEON-NEXT:    and w15, w1, w13
; CHECK-NEON-NEXT:    and w13, w0, w13
; CHECK-NEON-NEXT:    mul w12, w11, w10
; CHECK-NEON-NEXT:    mul w14, w8, w9
; CHECK-NEON-NEXT:    mul w16, w13, w15
; CHECK-NEON-NEXT:    mul w17, w11, w15
; CHECK-NEON-NEXT:    mul w15, w8, w15
; CHECK-NEON-NEXT:    eor w12, w14, w12
; CHECK-NEON-NEXT:    mov w14, #9362 // =0x2492
; CHECK-NEON-NEXT:    mul w8, w8, w10
; CHECK-NEON-NEXT:    eor w12, w12, w16
; CHECK-NEON-NEXT:    mul w11, w11, w9
; CHECK-NEON-NEXT:    and w12, w12, w14
; CHECK-NEON-NEXT:    mul w9, w13, w9
; CHECK-NEON-NEXT:    mul w10, w13, w10
; CHECK-NEON-NEXT:    eor w8, w8, w17
; CHECK-NEON-NEXT:    eor w11, w15, w11
; CHECK-NEON-NEXT:    eor w8, w8, w9
; CHECK-NEON-NEXT:    mov w9, #4681 // =0x1249
; CHECK-NEON-NEXT:    and w8, w8, w9
; CHECK-NEON-NEXT:    eor w9, w11, w10
; CHECK-NEON-NEXT:    mov w10, #18724 // =0x4924
; CHECK-NEON-NEXT:    orr w8, w8, w12
; CHECK-NEON-NEXT:    and w9, w9, w10
; CHECK-NEON-NEXT:    orr w0, w8, w9
; CHECK-NEON-NEXT:    ret
;
; CHECK-AES-LABEL: clmul_i16_zext:
; CHECK-AES:       // %bb.0:
; CHECK-AES-NEXT:    and w8, w0, #0xff
; CHECK-AES-NEXT:    and w9, w1, #0xff
; CHECK-AES-NEXT:    fmov s0, w9
; CHECK-AES-NEXT:    fmov s1, w8
; CHECK-AES-NEXT:    pmull v0.1q, v1.1d, v0.1d
; CHECK-AES-NEXT:    fmov w0, s0
; CHECK-AES-NEXT:    ret
  %zextx = zext i8 %x to i16
  %zexty = zext i8 %y to i16
  %a = call i16 @llvm.clmul.i16(i16 %zextx, i16 %zexty)
  ret i16 %a
}

define i32 @clmul_i32_zext(i16 %x, i16 %y) {
; CHECK-NEON-LABEL: clmul_i32_zext:
; CHECK-NEON:       // %bb.0:
; CHECK-NEON-NEXT:    mov w8, #4369 // =0x1111
; CHECK-NEON-NEXT:    mov w9, #8738 // =0x2222
; CHECK-NEON-NEXT:    mov w13, #34952 // =0x8888
; CHECK-NEON-NEXT:    mov w14, #17476 // =0x4444
; CHECK-NEON-NEXT:    and w10, w1, w8
; CHECK-NEON-NEXT:    and w11, w0, w9
; CHECK-NEON-NEXT:    and w9, w1, w9
; CHECK-NEON-NEXT:    and w8, w0, w8
; CHECK-NEON-NEXT:    and w16, w1, w13
; CHECK-NEON-NEXT:    and w17, w0, w14
; CHECK-NEON-NEXT:    and w14, w1, w14
; CHECK-NEON-NEXT:    and w13, w0, w13
; CHECK-NEON-NEXT:    mul w12, w11, w10
; CHECK-NEON-NEXT:    mul w15, w8, w9
; CHECK-NEON-NEXT:    mul w18, w17, w16
; CHECK-NEON-NEXT:    mul w0, w13, w14
; CHECK-NEON-NEXT:    mul w1, w11, w16
; CHECK-NEON-NEXT:    eor w12, w15, w12
; CHECK-NEON-NEXT:    mul w2, w8, w10
; CHECK-NEON-NEXT:    mul w3, w17, w14
; CHECK-NEON-NEXT:    eor w15, w18, w0
; CHECK-NEON-NEXT:    mul w4, w13, w9
; CHECK-NEON-NEXT:    eor w12, w12, w15
; CHECK-NEON-NEXT:    mul w5, w11, w9
; CHECK-NEON-NEXT:    and w12, w12, #0x22222222
; CHECK-NEON-NEXT:    mul w11, w11, w14
; CHECK-NEON-NEXT:    mul w14, w8, w14
; CHECK-NEON-NEXT:    eor w15, w3, w4
; CHECK-NEON-NEXT:    mul w9, w17, w9
; CHECK-NEON-NEXT:    mul w17, w17, w10
; CHECK-NEON-NEXT:    mul w8, w8, w16
; CHECK-NEON-NEXT:    eor w14, w14, w5
; CHECK-NEON-NEXT:    mul w16, w13, w16
; CHECK-NEON-NEXT:    mul w10, w13, w10
; CHECK-NEON-NEXT:    eor w13, w2, w1
; CHECK-NEON-NEXT:    eor w8, w8, w11
; CHECK-NEON-NEXT:    eor w16, w17, w16
; CHECK-NEON-NEXT:    eor w9, w9, w10
; CHECK-NEON-NEXT:    eor w10, w13, w15
; CHECK-NEON-NEXT:    eor w11, w14, w16
; CHECK-NEON-NEXT:    eor w8, w8, w9
; CHECK-NEON-NEXT:    and w9, w10, #0x11111111
; CHECK-NEON-NEXT:    and w10, w11, #0x44444444
; CHECK-NEON-NEXT:    and w8, w8, #0x88888888
; CHECK-NEON-NEXT:    orr w9, w9, w12
; CHECK-NEON-NEXT:    orr w8, w10, w8
; CHECK-NEON-NEXT:    orr w0, w9, w8
; CHECK-NEON-NEXT:    ret
;
; CHECK-AES-LABEL: clmul_i32_zext:
; CHECK-AES:       // %bb.0:
; CHECK-AES-NEXT:    and w8, w0, #0xffff
; CHECK-AES-NEXT:    and w9, w1, #0xffff
; CHECK-AES-NEXT:    fmov s0, w8
; CHECK-AES-NEXT:    fmov s1, w9
; CHECK-AES-NEXT:    pmull v0.1q, v0.1d, v1.1d
; CHECK-AES-NEXT:    fmov w0, s0
; CHECK-AES-NEXT:    ret
  %zextx = zext i16 %x to i32
  %zexty = zext i16 %y to i32
  %a = call i32 @llvm.clmul.i32(i32 %zextx, i32 %zexty)
  ret i32 %a
}

define i64 @clmul_i64_zext(i32 %x, i32 %y) {
; CHECK-NEON-LABEL: clmul_i64_zext:
; CHECK-NEON:       // %bb.0:
; CHECK-NEON-NEXT:    mov w8, w0
; CHECK-NEON-NEXT:    mov w9, w1
; CHECK-NEON-NEXT:    and x10, x9, #0x1111111111111111
; CHECK-NEON-NEXT:    and x11, x8, #0x2222222222222222
; CHECK-NEON-NEXT:    and x13, x9, #0x2222222222222222
; CHECK-NEON-NEXT:    and x14, x8, #0x1111111111111111
; CHECK-NEON-NEXT:    and x16, x9, #0x8888888888888888
; CHECK-NEON-NEXT:    and x17, x8, #0x4444444444444444
; CHECK-NEON-NEXT:    and x9, x9, #0x4444444444444444
; CHECK-NEON-NEXT:    and x8, x8, #0x8888888888888888
; CHECK-NEON-NEXT:    mul x12, x11, x10
; CHECK-NEON-NEXT:    mul x15, x14, x13
; CHECK-NEON-NEXT:    mul x18, x17, x16
; CHECK-NEON-NEXT:    mul x0, x8, x9
; CHECK-NEON-NEXT:    mul x1, x11, x16
; CHECK-NEON-NEXT:    mul x2, x14, x10
; CHECK-NEON-NEXT:    mul x3, x17, x9
; CHECK-NEON-NEXT:    mul x4, x8, x13
; CHECK-NEON-NEXT:    mul x5, x11, x13
; CHECK-NEON-NEXT:    mul x11, x11, x9
; CHECK-NEON-NEXT:    mul x9, x14, x9
; CHECK-NEON-NEXT:    mul x13, x17, x13
; CHECK-NEON-NEXT:    mul x17, x17, x10
; CHECK-NEON-NEXT:    eor x9, x9, x5
; CHECK-NEON-NEXT:    mul x14, x14, x16
; CHECK-NEON-NEXT:    mul x16, x8, x16
; CHECK-NEON-NEXT:    mul x8, x8, x10
; CHECK-NEON-NEXT:    eor x10, x15, x12
; CHECK-NEON-NEXT:    eor x12, x18, x0
; CHECK-NEON-NEXT:    eor x10, x10, x12
; CHECK-NEON-NEXT:    eor x12, x2, x1
; CHECK-NEON-NEXT:    eor x15, x3, x4
; CHECK-NEON-NEXT:    eor x11, x14, x11
; CHECK-NEON-NEXT:    eor x12, x12, x15
; CHECK-NEON-NEXT:    and x10, x10, #0x2222222222222222
; CHECK-NEON-NEXT:    eor x16, x17, x16
; CHECK-NEON-NEXT:    eor x9, x9, x16
; CHECK-NEON-NEXT:    eor x8, x13, x8
; CHECK-NEON-NEXT:    and x9, x9, #0x4444444444444444
; CHECK-NEON-NEXT:    eor x8, x11, x8
; CHECK-NEON-NEXT:    and x11, x12, #0x1111111111111111
; CHECK-NEON-NEXT:    and x8, x8, #0x8888888888888888
; CHECK-NEON-NEXT:    orr x10, x11, x10
; CHECK-NEON-NEXT:    orr x8, x9, x8
; CHECK-NEON-NEXT:    orr x0, x10, x8
; CHECK-NEON-NEXT:    ret
;
; CHECK-AES-LABEL: clmul_i64_zext:
; CHECK-AES:       // %bb.0:
; CHECK-AES-NEXT:    mov w8, w0
; CHECK-AES-NEXT:    mov w9, w1
; CHECK-AES-NEXT:    fmov d0, x8
; CHECK-AES-NEXT:    fmov d1, x9
; CHECK-AES-NEXT:    pmull v0.1q, v0.1d, v1.1d
; CHECK-AES-NEXT:    fmov x0, d0
; CHECK-AES-NEXT:    ret
  %zextx = zext i32 %x to i64
  %zexty = zext i32 %y to i64
  %a = call i64 @llvm.clmul.i64(i64 %zextx, i64 %zexty)
  ret i64 %a
}

define i128 @clmul_i128_zext(i64 %x, i64 %y) {
; CHECK-NEON-LABEL: clmul_i128_zext:
; CHECK-NEON:       // %bb.0:
; CHECK-NEON-NEXT:    sub sp, sp, #144
; CHECK-NEON-NEXT:    stp x29, x30, [sp, #48] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    stp x28, x27, [sp, #64] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    stp x26, x25, [sp, #80] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    stp x24, x23, [sp, #96] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    stp x22, x21, [sp, #112] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    stp x20, x19, [sp, #128] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    .cfi_def_cfa_offset 144
; CHECK-NEON-NEXT:    .cfi_offset w19, -8
; CHECK-NEON-NEXT:    .cfi_offset w20, -16
; CHECK-NEON-NEXT:    .cfi_offset w21, -24
; CHECK-NEON-NEXT:    .cfi_offset w22, -32
; CHECK-NEON-NEXT:    .cfi_offset w23, -40
; CHECK-NEON-NEXT:    .cfi_offset w24, -48
; CHECK-NEON-NEXT:    .cfi_offset w25, -56
; CHECK-NEON-NEXT:    .cfi_offset w26, -64
; CHECK-NEON-NEXT:    .cfi_offset w27, -72
; CHECK-NEON-NEXT:    .cfi_offset w28, -80
; CHECK-NEON-NEXT:    .cfi_offset w30, -88
; CHECK-NEON-NEXT:    .cfi_offset w29, -96
; CHECK-NEON-NEXT:    and x12, x1, #0x1111111111111111
; CHECK-NEON-NEXT:    and x13, x0, #0x2222222222222222
; CHECK-NEON-NEXT:    and x14, x1, #0x2222222222222222
; CHECK-NEON-NEXT:    and x11, x0, #0x1111111111111111
; CHECK-NEON-NEXT:    mul x8, x13, x12
; CHECK-NEON-NEXT:    and x10, x1, #0x8888888888888888
; CHECK-NEON-NEXT:    and x16, x0, #0x4444444444444444
; CHECK-NEON-NEXT:    and x2, x1, #0x4444444444444444
; CHECK-NEON-NEXT:    rbit x1, x1
; CHECK-NEON-NEXT:    mul x9, x11, x14
; CHECK-NEON-NEXT:    and x7, x1, #0x1111111111111111
; CHECK-NEON-NEXT:    and x21, x1, #0x2222222222222222
; CHECK-NEON-NEXT:    and x24, x1, #0x8888888888888888
; CHECK-NEON-NEXT:    mul x4, x11, x12
; CHECK-NEON-NEXT:    and x1, x1, #0x4444444444444444
; CHECK-NEON-NEXT:    mul x5, x16, x2
; CHECK-NEON-NEXT:    stp x8, x9, [sp, #32] // 16-byte Folded Spill
; CHECK-NEON-NEXT:    and x9, x0, #0x8888888888888888
; CHECK-NEON-NEXT:    rbit x0, x0
; CHECK-NEON-NEXT:    mul x8, x16, x10
; CHECK-NEON-NEXT:    and x19, x0, #0x2222222222222222
; CHECK-NEON-NEXT:    and x22, x0, #0x1111111111111111
; CHECK-NEON-NEXT:    and x25, x0, #0x4444444444444444
; CHECK-NEON-NEXT:    mul x6, x9, x14
; CHECK-NEON-NEXT:    and x0, x0, #0x8888888888888888
; CHECK-NEON-NEXT:    mul x28, x19, x24
; CHECK-NEON-NEXT:    str x8, [sp, #24] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x8, x9, x2
; CHECK-NEON-NEXT:    mul x29, x22, x7
; CHECK-NEON-NEXT:    mul x30, x25, x1
; CHECK-NEON-NEXT:    str x8, [sp, #16] // 8-byte Spill
; CHECK-NEON-NEXT:    mul x8, x13, x10
; CHECK-NEON-NEXT:    mul x17, x0, x21
; CHECK-NEON-NEXT:    mul x20, x19, x7
; CHECK-NEON-NEXT:    str x8, [sp, #8] // 8-byte Spill
; CHECK-NEON-NEXT:    ldp x18, x8, [sp, #32] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    mul x23, x22, x21
; CHECK-NEON-NEXT:    eor x17, x30, x17
; CHECK-NEON-NEXT:    eor x8, x8, x18
; CHECK-NEON-NEXT:    ldp x3, x18, [sp, #16] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    mul x26, x25, x24
; CHECK-NEON-NEXT:    mul x27, x0, x1
; CHECK-NEON-NEXT:    eor x18, x18, x3
; CHECK-NEON-NEXT:    ldr x3, [sp, #8] // 8-byte Reload
; CHECK-NEON-NEXT:    eor x8, x8, x18
; CHECK-NEON-NEXT:    mul x15, x19, x21
; CHECK-NEON-NEXT:    eor x3, x4, x3
; CHECK-NEON-NEXT:    eor x4, x5, x6
; CHECK-NEON-NEXT:    eor x18, x3, x4
; CHECK-NEON-NEXT:    eor x4, x29, x28
; CHECK-NEON-NEXT:    eor x5, x23, x20
; CHECK-NEON-NEXT:    mul x19, x19, x1
; CHECK-NEON-NEXT:    eor x17, x4, x17
; CHECK-NEON-NEXT:    and x8, x8, #0x2222222222222222
; CHECK-NEON-NEXT:    eor x6, x26, x27
; CHECK-NEON-NEXT:    and x17, x17, #0x1111111111111111
; CHECK-NEON-NEXT:    mul x1, x22, x1
; CHECK-NEON-NEXT:    eor x3, x5, x6
; CHECK-NEON-NEXT:    ldp x28, x27, [sp, #64] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    mul x21, x25, x21
; CHECK-NEON-NEXT:    ldp x29, x30, [sp, #48] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    mul x25, x25, x7
; CHECK-NEON-NEXT:    eor x15, x1, x15
; CHECK-NEON-NEXT:    mul x22, x22, x24
; CHECK-NEON-NEXT:    mul x24, x0, x24
; CHECK-NEON-NEXT:    mul x0, x0, x7
; CHECK-NEON-NEXT:    eor x4, x22, x19
; CHECK-NEON-NEXT:    ldp x20, x19, [sp, #128] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    mul x7, x13, x14
; CHECK-NEON-NEXT:    eor x1, x25, x24
; CHECK-NEON-NEXT:    ldp x24, x23, [sp, #96] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    mul x13, x13, x2
; CHECK-NEON-NEXT:    ldp x26, x25, [sp, #80] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    eor x0, x21, x0
; CHECK-NEON-NEXT:    ldp x22, x21, [sp, #112] // 16-byte Folded Reload
; CHECK-NEON-NEXT:    mul x2, x11, x2
; CHECK-NEON-NEXT:    mul x14, x16, x14
; CHECK-NEON-NEXT:    mul x16, x16, x12
; CHECK-NEON-NEXT:    mul x11, x11, x10
; CHECK-NEON-NEXT:    mul x10, x9, x10
; CHECK-NEON-NEXT:    mul x9, x9, x12
; CHECK-NEON-NEXT:    eor x12, x15, x1
; CHECK-NEON-NEXT:    eor x15, x4, x0
; CHECK-NEON-NEXT:    and x0, x3, #0x2222222222222222
; CHECK-NEON-NEXT:    and x12, x12, #0x4444444444444444
; CHECK-NEON-NEXT:    and x15, x15, #0x8888888888888888
; CHECK-NEON-NEXT:    orr x17, x17, x0
; CHECK-NEON-NEXT:    orr x12, x12, x15
; CHECK-NEON-NEXT:    eor x15, x2, x7
; CHECK-NEON-NEXT:    eor x10, x16, x10
; CHECK-NEON-NEXT:    eor x11, x11, x13
; CHECK-NEON-NEXT:    orr x12, x17, x12
; CHECK-NEON-NEXT:    eor x10, x15, x10
; CHECK-NEON-NEXT:    rbit x12, x12
; CHECK-NEON-NEXT:    and x13, x18, #0x1111111111111111
; CHECK-NEON-NEXT:    eor x9, x14, x9
; CHECK-NEON-NEXT:    and x10, x10, #0x4444444444444444
; CHECK-NEON-NEXT:    orr x8, x13, x8
; CHECK-NEON-NEXT:    eor x9, x11, x9
; CHECK-NEON-NEXT:    lsr x1, x12, #1
; CHECK-NEON-NEXT:    and x9, x9, #0x8888888888888888
; CHECK-NEON-NEXT:    orr x9, x10, x9
; CHECK-NEON-NEXT:    orr x0, x8, x9
; CHECK-NEON-NEXT:    add sp, sp, #144
; CHECK-NEON-NEXT:    ret
;
; CHECK-AES-LABEL: clmul_i128_zext:
; CHECK-AES:       // %bb.0:
; CHECK-AES-NEXT:    rbit x8, x1
; CHECK-AES-NEXT:    rbit x9, x0
; CHECK-AES-NEXT:    fmov d2, x0
; CHECK-AES-NEXT:    fmov d0, x8
; CHECK-AES-NEXT:    fmov d1, x9
; CHECK-AES-NEXT:    pmull v0.1q, v1.1d, v0.1d
; CHECK-AES-NEXT:    fmov d1, x1
; CHECK-AES-NEXT:    pmull v1.1q, v2.1d, v1.1d
; CHECK-AES-NEXT:    fmov x8, d0
; CHECK-AES-NEXT:    rbit x8, x8
; CHECK-AES-NEXT:    fmov x0, d1
; CHECK-AES-NEXT:    lsr x1, x8, #1
; CHECK-AES-NEXT:    ret
  %zextx = zext i64 %x to i128
  %zexty = zext i64 %y to i128
  %a = call i128 @llvm.clmul.i128(i128 %zextx, i128 %zexty)
  ret i128 %a
}
