; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-linux-unknown-gnu %s -o - -mattr=+sve | FileCheck %s --check-prefix=CHECK-SVE
; RUN: llc -mtriple=aarch64-linux-unknown-gnu %s -o - -mattr=+sve,sve-aes | FileCheck %s --check-prefix=CHECK-SVE-AES
; RUN: llc -mtriple=aarch64-linux-unknown-gnu %s -o - -mattr=+sme -force-streaming | FileCheck %s --check-prefix=CHECK-SME-STREAMING
; RUN: llc -mtriple=aarch64-linux-unknown-gnu %s -o - -mattr=+sme,ssve-aes -force-streaming | FileCheck %s --check-prefix=CHECK-SME-STREAMING-SSVE-AES
; RUN: llc -mtriple=aarch64-linux-unknown-gnu %s -o - -mattr=+sve2 | FileCheck %s --check-prefix=CHECK-SVE2
; RUN: llc -mtriple=aarch64-linux-unknown-gnu %s -o - -mattr=+sve2-aes | FileCheck %s --check-prefix=CHECK-SVE2-AES

define <vscale x 16 x i8> @clmul_nxv16i8(<vscale x 16 x i8> %x, <vscale x 16 x i8> %y) {
; CHECK-SVE-LABEL: clmul_nxv16i8:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    movprfx z2, z1
; CHECK-SVE-NEXT:    and z2.b, z2.b, #0x55
; CHECK-SVE-NEXT:    movprfx z3, z0
; CHECK-SVE-NEXT:    and z3.b, z3.b, #0xaa
; CHECK-SVE-NEXT:    and z1.b, z1.b, #0xaa
; CHECK-SVE-NEXT:    and z0.b, z0.b, #0x55
; CHECK-SVE-NEXT:    ptrue p0.b
; CHECK-SVE-NEXT:    movprfx z4, z3
; CHECK-SVE-NEXT:    mul z4.b, p0/m, z4.b, z2.b
; CHECK-SVE-NEXT:    movprfx z5, z0
; CHECK-SVE-NEXT:    mul z5.b, p0/m, z5.b, z1.b
; CHECK-SVE-NEXT:    mul z1.b, p0/m, z1.b, z3.b
; CHECK-SVE-NEXT:    mul z0.b, p0/m, z0.b, z2.b
; CHECK-SVE-NEXT:    eor z2.d, z5.d, z4.d
; CHECK-SVE-NEXT:    eor z0.d, z0.d, z1.d
; CHECK-SVE-NEXT:    and z2.b, z2.b, #0xaa
; CHECK-SVE-NEXT:    and z0.b, z0.b, #0x55
; CHECK-SVE-NEXT:    orr z0.d, z0.d, z2.d
; CHECK-SVE-NEXT:    ret
;
; CHECK-SVE-AES-LABEL: clmul_nxv16i8:
; CHECK-SVE-AES:       // %bb.0:
; CHECK-SVE-AES-NEXT:    movprfx z2, z1
; CHECK-SVE-AES-NEXT:    and z2.b, z2.b, #0x55
; CHECK-SVE-AES-NEXT:    movprfx z3, z0
; CHECK-SVE-AES-NEXT:    and z3.b, z3.b, #0xaa
; CHECK-SVE-AES-NEXT:    and z1.b, z1.b, #0xaa
; CHECK-SVE-AES-NEXT:    and z0.b, z0.b, #0x55
; CHECK-SVE-AES-NEXT:    ptrue p0.b
; CHECK-SVE-AES-NEXT:    movprfx z4, z3
; CHECK-SVE-AES-NEXT:    mul z4.b, p0/m, z4.b, z2.b
; CHECK-SVE-AES-NEXT:    movprfx z5, z0
; CHECK-SVE-AES-NEXT:    mul z5.b, p0/m, z5.b, z1.b
; CHECK-SVE-AES-NEXT:    mul z1.b, p0/m, z1.b, z3.b
; CHECK-SVE-AES-NEXT:    mul z0.b, p0/m, z0.b, z2.b
; CHECK-SVE-AES-NEXT:    eor z2.d, z5.d, z4.d
; CHECK-SVE-AES-NEXT:    eor z0.d, z0.d, z1.d
; CHECK-SVE-AES-NEXT:    and z2.b, z2.b, #0xaa
; CHECK-SVE-AES-NEXT:    and z0.b, z0.b, #0x55
; CHECK-SVE-AES-NEXT:    orr z0.d, z0.d, z2.d
; CHECK-SVE-AES-NEXT:    ret
;
; CHECK-SME-STREAMING-LABEL: clmul_nxv16i8:
; CHECK-SME-STREAMING:       // %bb.0:
; CHECK-SME-STREAMING-NEXT:    pmul z0.b, z0.b, z1.b
; CHECK-SME-STREAMING-NEXT:    ret
;
; CHECK-SME-STREAMING-SSVE-AES-LABEL: clmul_nxv16i8:
; CHECK-SME-STREAMING-SSVE-AES:       // %bb.0:
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    pmul z0.b, z0.b, z1.b
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    ret
;
; CHECK-SVE2-LABEL: clmul_nxv16i8:
; CHECK-SVE2:       // %bb.0:
; CHECK-SVE2-NEXT:    pmul z0.b, z0.b, z1.b
; CHECK-SVE2-NEXT:    ret
;
; CHECK-SVE2-AES-LABEL: clmul_nxv16i8:
; CHECK-SVE2-AES:       // %bb.0:
; CHECK-SVE2-AES-NEXT:    pmul z0.b, z0.b, z1.b
; CHECK-SVE2-AES-NEXT:    ret
  %a = call <vscale x 16 x i8> @llvm.clmul.nxv16i8(<vscale x 16 x i8> %x, <vscale x 16 x i8> %y)
  ret <vscale x 16 x i8> %a
}

define <vscale x 8 x i16> @clmul_nxv8i16(<vscale x 8 x i16> %x, <vscale x 8 x i16> %y) {
; CHECK-SVE-LABEL: clmul_nxv8i16:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    mov w8, #37449 // =0x9249
; CHECK-SVE-NEXT:    ptrue p0.h
; CHECK-SVE-NEXT:    mov z2.h, w8
; CHECK-SVE-NEXT:    mov w8, #9362 // =0x2492
; CHECK-SVE-NEXT:    mov z3.h, w8
; CHECK-SVE-NEXT:    mov w8, #18724 // =0x4924
; CHECK-SVE-NEXT:    mov z4.h, w8
; CHECK-SVE-NEXT:    and z5.d, z1.d, z2.d
; CHECK-SVE-NEXT:    and z24.d, z0.d, z2.d
; CHECK-SVE-NEXT:    and z6.d, z0.d, z3.d
; CHECK-SVE-NEXT:    and z7.d, z1.d, z3.d
; CHECK-SVE-NEXT:    and z1.d, z1.d, z4.d
; CHECK-SVE-NEXT:    and z0.d, z0.d, z4.d
; CHECK-SVE-NEXT:    movprfx z28, z24
; CHECK-SVE-NEXT:    mul z28.h, p0/m, z28.h, z5.h
; CHECK-SVE-NEXT:    movprfx z25, z6
; CHECK-SVE-NEXT:    mul z25.h, p0/m, z25.h, z5.h
; CHECK-SVE-NEXT:    movprfx z26, z24
; CHECK-SVE-NEXT:    mul z26.h, p0/m, z26.h, z7.h
; CHECK-SVE-NEXT:    movprfx z27, z6
; CHECK-SVE-NEXT:    mul z27.h, p0/m, z27.h, z1.h
; CHECK-SVE-NEXT:    mul z24.h, p0/m, z24.h, z1.h
; CHECK-SVE-NEXT:    mul z1.h, p0/m, z1.h, z0.h
; CHECK-SVE-NEXT:    mul z6.h, p0/m, z6.h, z7.h
; CHECK-SVE-NEXT:    mul z7.h, p0/m, z7.h, z0.h
; CHECK-SVE-NEXT:    mul z0.h, p0/m, z0.h, z5.h
; CHECK-SVE-NEXT:    eor z25.d, z26.d, z25.d
; CHECK-SVE-NEXT:    eor z26.d, z28.d, z27.d
; CHECK-SVE-NEXT:    eor z6.d, z24.d, z6.d
; CHECK-SVE-NEXT:    eor z1.d, z25.d, z1.d
; CHECK-SVE-NEXT:    eor z5.d, z26.d, z7.d
; CHECK-SVE-NEXT:    eor z0.d, z6.d, z0.d
; CHECK-SVE-NEXT:    and z1.d, z1.d, z3.d
; CHECK-SVE-NEXT:    and z2.d, z5.d, z2.d
; CHECK-SVE-NEXT:    and z0.d, z0.d, z4.d
; CHECK-SVE-NEXT:    orr z1.d, z2.d, z1.d
; CHECK-SVE-NEXT:    orr z0.d, z1.d, z0.d
; CHECK-SVE-NEXT:    ret
;
; CHECK-SVE-AES-LABEL: clmul_nxv8i16:
; CHECK-SVE-AES:       // %bb.0:
; CHECK-SVE-AES-NEXT:    mov w8, #37449 // =0x9249
; CHECK-SVE-AES-NEXT:    ptrue p0.h
; CHECK-SVE-AES-NEXT:    mov z2.h, w8
; CHECK-SVE-AES-NEXT:    mov w8, #9362 // =0x2492
; CHECK-SVE-AES-NEXT:    mov z3.h, w8
; CHECK-SVE-AES-NEXT:    mov w8, #18724 // =0x4924
; CHECK-SVE-AES-NEXT:    mov z4.h, w8
; CHECK-SVE-AES-NEXT:    and z5.d, z1.d, z2.d
; CHECK-SVE-AES-NEXT:    and z24.d, z0.d, z2.d
; CHECK-SVE-AES-NEXT:    and z6.d, z0.d, z3.d
; CHECK-SVE-AES-NEXT:    and z7.d, z1.d, z3.d
; CHECK-SVE-AES-NEXT:    and z1.d, z1.d, z4.d
; CHECK-SVE-AES-NEXT:    and z0.d, z0.d, z4.d
; CHECK-SVE-AES-NEXT:    movprfx z28, z24
; CHECK-SVE-AES-NEXT:    mul z28.h, p0/m, z28.h, z5.h
; CHECK-SVE-AES-NEXT:    movprfx z25, z6
; CHECK-SVE-AES-NEXT:    mul z25.h, p0/m, z25.h, z5.h
; CHECK-SVE-AES-NEXT:    movprfx z26, z24
; CHECK-SVE-AES-NEXT:    mul z26.h, p0/m, z26.h, z7.h
; CHECK-SVE-AES-NEXT:    movprfx z27, z6
; CHECK-SVE-AES-NEXT:    mul z27.h, p0/m, z27.h, z1.h
; CHECK-SVE-AES-NEXT:    mul z24.h, p0/m, z24.h, z1.h
; CHECK-SVE-AES-NEXT:    mul z1.h, p0/m, z1.h, z0.h
; CHECK-SVE-AES-NEXT:    mul z6.h, p0/m, z6.h, z7.h
; CHECK-SVE-AES-NEXT:    mul z7.h, p0/m, z7.h, z0.h
; CHECK-SVE-AES-NEXT:    mul z0.h, p0/m, z0.h, z5.h
; CHECK-SVE-AES-NEXT:    eor z25.d, z26.d, z25.d
; CHECK-SVE-AES-NEXT:    eor z26.d, z28.d, z27.d
; CHECK-SVE-AES-NEXT:    eor z6.d, z24.d, z6.d
; CHECK-SVE-AES-NEXT:    eor z1.d, z25.d, z1.d
; CHECK-SVE-AES-NEXT:    eor z5.d, z26.d, z7.d
; CHECK-SVE-AES-NEXT:    eor z0.d, z6.d, z0.d
; CHECK-SVE-AES-NEXT:    and z1.d, z1.d, z3.d
; CHECK-SVE-AES-NEXT:    and z2.d, z5.d, z2.d
; CHECK-SVE-AES-NEXT:    and z0.d, z0.d, z4.d
; CHECK-SVE-AES-NEXT:    orr z1.d, z2.d, z1.d
; CHECK-SVE-AES-NEXT:    orr z0.d, z1.d, z0.d
; CHECK-SVE-AES-NEXT:    ret
;
; CHECK-SME-STREAMING-LABEL: clmul_nxv8i16:
; CHECK-SME-STREAMING:       // %bb.0:
; CHECK-SME-STREAMING-NEXT:    trn1 z2.b, z1.b, z0.b
; CHECK-SME-STREAMING-NEXT:    trn2 z3.b, z0.b, z1.b
; CHECK-SME-STREAMING-NEXT:    pmullb z0.h, z0.b, z1.b
; CHECK-SME-STREAMING-NEXT:    pmul z1.b, z3.b, z2.b
; CHECK-SME-STREAMING-NEXT:    eorbt z1.b, z1.b, z1.b
; CHECK-SME-STREAMING-NEXT:    eortb z0.b, z0.b, z1.b
; CHECK-SME-STREAMING-NEXT:    ret
;
; CHECK-SME-STREAMING-SSVE-AES-LABEL: clmul_nxv8i16:
; CHECK-SME-STREAMING-SSVE-AES:       // %bb.0:
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    trn1 z2.b, z1.b, z0.b
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    trn2 z3.b, z0.b, z1.b
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    pmullb z0.h, z0.b, z1.b
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    pmul z1.b, z3.b, z2.b
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    eorbt z1.b, z1.b, z1.b
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    eortb z0.b, z0.b, z1.b
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    ret
;
; CHECK-SVE2-LABEL: clmul_nxv8i16:
; CHECK-SVE2:       // %bb.0:
; CHECK-SVE2-NEXT:    trn1 z2.b, z1.b, z0.b
; CHECK-SVE2-NEXT:    trn2 z3.b, z0.b, z1.b
; CHECK-SVE2-NEXT:    pmullb z0.h, z0.b, z1.b
; CHECK-SVE2-NEXT:    pmul z1.b, z3.b, z2.b
; CHECK-SVE2-NEXT:    eorbt z1.b, z1.b, z1.b
; CHECK-SVE2-NEXT:    eortb z0.b, z0.b, z1.b
; CHECK-SVE2-NEXT:    ret
;
; CHECK-SVE2-AES-LABEL: clmul_nxv8i16:
; CHECK-SVE2-AES:       // %bb.0:
; CHECK-SVE2-AES-NEXT:    trn1 z2.b, z1.b, z0.b
; CHECK-SVE2-AES-NEXT:    trn2 z3.b, z0.b, z1.b
; CHECK-SVE2-AES-NEXT:    pmullb z0.h, z0.b, z1.b
; CHECK-SVE2-AES-NEXT:    pmul z1.b, z3.b, z2.b
; CHECK-SVE2-AES-NEXT:    eorbt z1.b, z1.b, z1.b
; CHECK-SVE2-AES-NEXT:    eortb z0.b, z0.b, z1.b
; CHECK-SVE2-AES-NEXT:    ret
  %a = call <vscale x 8 x i16> @llvm.clmul.nxv8i16(<vscale x 8 x i16> %x, <vscale x 8 x i16> %y)
  ret <vscale x 8 x i16> %a
}

define <vscale x 4 x i32> @clmul_nxv4i32(<vscale x 4 x i32> %x, <vscale x 4 x i32> %y) {
; CHECK-SVE-LABEL: clmul_nxv4i32:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SVE-NEXT:    addvl sp, sp, #-1
; CHECK-SVE-NEXT:    str z8, [sp] // 16-byte Folded Spill
; CHECK-SVE-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x38, 0x1e, 0x22 // sp + 16 + 8 * VG
; CHECK-SVE-NEXT:    .cfi_offset w29, -16
; CHECK-SVE-NEXT:    .cfi_escape 0x10, 0x48, 0x09, 0x92, 0x2e, 0x00, 0x11, 0x78, 0x1e, 0x22, 0x40, 0x1c // $d8 @ cfa - 8 * VG - 16
; CHECK-SVE-NEXT:    movprfx z2, z1
; CHECK-SVE-NEXT:    and z2.b, z2.b, #0x11
; CHECK-SVE-NEXT:    movprfx z3, z0
; CHECK-SVE-NEXT:    and z3.b, z3.b, #0x22
; CHECK-SVE-NEXT:    movprfx z4, z1
; CHECK-SVE-NEXT:    and z4.b, z4.b, #0x22
; CHECK-SVE-NEXT:    movprfx z5, z0
; CHECK-SVE-NEXT:    and z5.b, z5.b, #0x11
; CHECK-SVE-NEXT:    movprfx z6, z1
; CHECK-SVE-NEXT:    and z6.b, z6.b, #0x88
; CHECK-SVE-NEXT:    movprfx z7, z0
; CHECK-SVE-NEXT:    and z7.b, z7.b, #0x44
; CHECK-SVE-NEXT:    and z1.b, z1.b, #0x44
; CHECK-SVE-NEXT:    and z0.b, z0.b, #0x88
; CHECK-SVE-NEXT:    ptrue p0.s
; CHECK-SVE-NEXT:    movprfx z24, z3
; CHECK-SVE-NEXT:    mul z24.s, p0/m, z24.s, z2.s
; CHECK-SVE-NEXT:    movprfx z25, z5
; CHECK-SVE-NEXT:    mul z25.s, p0/m, z25.s, z4.s
; CHECK-SVE-NEXT:    movprfx z26, z7
; CHECK-SVE-NEXT:    mul z26.s, p0/m, z26.s, z6.s
; CHECK-SVE-NEXT:    movprfx z27, z0
; CHECK-SVE-NEXT:    mul z27.s, p0/m, z27.s, z1.s
; CHECK-SVE-NEXT:    movprfx z28, z3
; CHECK-SVE-NEXT:    mul z28.s, p0/m, z28.s, z6.s
; CHECK-SVE-NEXT:    movprfx z29, z5
; CHECK-SVE-NEXT:    mul z29.s, p0/m, z29.s, z2.s
; CHECK-SVE-NEXT:    movprfx z30, z7
; CHECK-SVE-NEXT:    mul z30.s, p0/m, z30.s, z1.s
; CHECK-SVE-NEXT:    movprfx z31, z0
; CHECK-SVE-NEXT:    mul z31.s, p0/m, z31.s, z4.s
; CHECK-SVE-NEXT:    movprfx z8, z3
; CHECK-SVE-NEXT:    mul z8.s, p0/m, z8.s, z4.s
; CHECK-SVE-NEXT:    mul z3.s, p0/m, z3.s, z1.s
; CHECK-SVE-NEXT:    mul z1.s, p0/m, z1.s, z5.s
; CHECK-SVE-NEXT:    mul z4.s, p0/m, z4.s, z7.s
; CHECK-SVE-NEXT:    mul z7.s, p0/m, z7.s, z2.s
; CHECK-SVE-NEXT:    mul z5.s, p0/m, z5.s, z6.s
; CHECK-SVE-NEXT:    mul z6.s, p0/m, z6.s, z0.s
; CHECK-SVE-NEXT:    mul z0.s, p0/m, z0.s, z2.s
; CHECK-SVE-NEXT:    eor z2.d, z25.d, z24.d
; CHECK-SVE-NEXT:    eor z24.d, z26.d, z27.d
; CHECK-SVE-NEXT:    eor z25.d, z29.d, z28.d
; CHECK-SVE-NEXT:    eor z26.d, z30.d, z31.d
; CHECK-SVE-NEXT:    eor z1.d, z1.d, z8.d
; CHECK-SVE-NEXT:    ldr z8, [sp] // 16-byte Folded Reload
; CHECK-SVE-NEXT:    eor z6.d, z7.d, z6.d
; CHECK-SVE-NEXT:    eor z3.d, z5.d, z3.d
; CHECK-SVE-NEXT:    eor z2.d, z2.d, z24.d
; CHECK-SVE-NEXT:    eor z0.d, z4.d, z0.d
; CHECK-SVE-NEXT:    eor z4.d, z25.d, z26.d
; CHECK-SVE-NEXT:    eor z1.d, z1.d, z6.d
; CHECK-SVE-NEXT:    and z2.b, z2.b, #0x22
; CHECK-SVE-NEXT:    eor z0.d, z3.d, z0.d
; CHECK-SVE-NEXT:    and z4.b, z4.b, #0x11
; CHECK-SVE-NEXT:    and z1.b, z1.b, #0x44
; CHECK-SVE-NEXT:    and z0.b, z0.b, #0x88
; CHECK-SVE-NEXT:    orr z2.d, z4.d, z2.d
; CHECK-SVE-NEXT:    orr z0.d, z1.d, z0.d
; CHECK-SVE-NEXT:    orr z0.d, z2.d, z0.d
; CHECK-SVE-NEXT:    addvl sp, sp, #1
; CHECK-SVE-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-SVE-NEXT:    ret
;
; CHECK-SVE-AES-LABEL: clmul_nxv4i32:
; CHECK-SVE-AES:       // %bb.0:
; CHECK-SVE-AES-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SVE-AES-NEXT:    addvl sp, sp, #-1
; CHECK-SVE-AES-NEXT:    str z8, [sp] // 16-byte Folded Spill
; CHECK-SVE-AES-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x38, 0x1e, 0x22 // sp + 16 + 8 * VG
; CHECK-SVE-AES-NEXT:    .cfi_offset w29, -16
; CHECK-SVE-AES-NEXT:    .cfi_escape 0x10, 0x48, 0x09, 0x92, 0x2e, 0x00, 0x11, 0x78, 0x1e, 0x22, 0x40, 0x1c // $d8 @ cfa - 8 * VG - 16
; CHECK-SVE-AES-NEXT:    movprfx z2, z1
; CHECK-SVE-AES-NEXT:    and z2.b, z2.b, #0x11
; CHECK-SVE-AES-NEXT:    movprfx z3, z0
; CHECK-SVE-AES-NEXT:    and z3.b, z3.b, #0x22
; CHECK-SVE-AES-NEXT:    movprfx z4, z1
; CHECK-SVE-AES-NEXT:    and z4.b, z4.b, #0x22
; CHECK-SVE-AES-NEXT:    movprfx z5, z0
; CHECK-SVE-AES-NEXT:    and z5.b, z5.b, #0x11
; CHECK-SVE-AES-NEXT:    movprfx z6, z1
; CHECK-SVE-AES-NEXT:    and z6.b, z6.b, #0x88
; CHECK-SVE-AES-NEXT:    movprfx z7, z0
; CHECK-SVE-AES-NEXT:    and z7.b, z7.b, #0x44
; CHECK-SVE-AES-NEXT:    and z1.b, z1.b, #0x44
; CHECK-SVE-AES-NEXT:    and z0.b, z0.b, #0x88
; CHECK-SVE-AES-NEXT:    ptrue p0.s
; CHECK-SVE-AES-NEXT:    movprfx z24, z3
; CHECK-SVE-AES-NEXT:    mul z24.s, p0/m, z24.s, z2.s
; CHECK-SVE-AES-NEXT:    movprfx z25, z5
; CHECK-SVE-AES-NEXT:    mul z25.s, p0/m, z25.s, z4.s
; CHECK-SVE-AES-NEXT:    movprfx z26, z7
; CHECK-SVE-AES-NEXT:    mul z26.s, p0/m, z26.s, z6.s
; CHECK-SVE-AES-NEXT:    movprfx z27, z0
; CHECK-SVE-AES-NEXT:    mul z27.s, p0/m, z27.s, z1.s
; CHECK-SVE-AES-NEXT:    movprfx z28, z3
; CHECK-SVE-AES-NEXT:    mul z28.s, p0/m, z28.s, z6.s
; CHECK-SVE-AES-NEXT:    movprfx z29, z5
; CHECK-SVE-AES-NEXT:    mul z29.s, p0/m, z29.s, z2.s
; CHECK-SVE-AES-NEXT:    movprfx z30, z7
; CHECK-SVE-AES-NEXT:    mul z30.s, p0/m, z30.s, z1.s
; CHECK-SVE-AES-NEXT:    movprfx z31, z0
; CHECK-SVE-AES-NEXT:    mul z31.s, p0/m, z31.s, z4.s
; CHECK-SVE-AES-NEXT:    movprfx z8, z3
; CHECK-SVE-AES-NEXT:    mul z8.s, p0/m, z8.s, z4.s
; CHECK-SVE-AES-NEXT:    mul z3.s, p0/m, z3.s, z1.s
; CHECK-SVE-AES-NEXT:    mul z1.s, p0/m, z1.s, z5.s
; CHECK-SVE-AES-NEXT:    mul z4.s, p0/m, z4.s, z7.s
; CHECK-SVE-AES-NEXT:    mul z7.s, p0/m, z7.s, z2.s
; CHECK-SVE-AES-NEXT:    mul z5.s, p0/m, z5.s, z6.s
; CHECK-SVE-AES-NEXT:    mul z6.s, p0/m, z6.s, z0.s
; CHECK-SVE-AES-NEXT:    mul z0.s, p0/m, z0.s, z2.s
; CHECK-SVE-AES-NEXT:    eor z2.d, z25.d, z24.d
; CHECK-SVE-AES-NEXT:    eor z24.d, z26.d, z27.d
; CHECK-SVE-AES-NEXT:    eor z25.d, z29.d, z28.d
; CHECK-SVE-AES-NEXT:    eor z26.d, z30.d, z31.d
; CHECK-SVE-AES-NEXT:    eor z1.d, z1.d, z8.d
; CHECK-SVE-AES-NEXT:    ldr z8, [sp] // 16-byte Folded Reload
; CHECK-SVE-AES-NEXT:    eor z6.d, z7.d, z6.d
; CHECK-SVE-AES-NEXT:    eor z3.d, z5.d, z3.d
; CHECK-SVE-AES-NEXT:    eor z2.d, z2.d, z24.d
; CHECK-SVE-AES-NEXT:    eor z0.d, z4.d, z0.d
; CHECK-SVE-AES-NEXT:    eor z4.d, z25.d, z26.d
; CHECK-SVE-AES-NEXT:    eor z1.d, z1.d, z6.d
; CHECK-SVE-AES-NEXT:    and z2.b, z2.b, #0x22
; CHECK-SVE-AES-NEXT:    eor z0.d, z3.d, z0.d
; CHECK-SVE-AES-NEXT:    and z4.b, z4.b, #0x11
; CHECK-SVE-AES-NEXT:    and z1.b, z1.b, #0x44
; CHECK-SVE-AES-NEXT:    and z0.b, z0.b, #0x88
; CHECK-SVE-AES-NEXT:    orr z2.d, z4.d, z2.d
; CHECK-SVE-AES-NEXT:    orr z0.d, z1.d, z0.d
; CHECK-SVE-AES-NEXT:    orr z0.d, z2.d, z0.d
; CHECK-SVE-AES-NEXT:    addvl sp, sp, #1
; CHECK-SVE-AES-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-SVE-AES-NEXT:    ret
;
; CHECK-SME-STREAMING-LABEL: clmul_nxv4i32:
; CHECK-SME-STREAMING:       // %bb.0:
; CHECK-SME-STREAMING-NEXT:    pmullt z2.d, z0.s, z1.s
; CHECK-SME-STREAMING-NEXT:    pmullb z0.d, z0.s, z1.s
; CHECK-SME-STREAMING-NEXT:    trn1 z0.s, z0.s, z2.s
; CHECK-SME-STREAMING-NEXT:    ret
;
; CHECK-SME-STREAMING-SSVE-AES-LABEL: clmul_nxv4i32:
; CHECK-SME-STREAMING-SSVE-AES:       // %bb.0:
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    pmullt z2.d, z0.s, z1.s
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    pmullb z0.d, z0.s, z1.s
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    trn1 z0.s, z0.s, z2.s
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    ret
;
; CHECK-SVE2-LABEL: clmul_nxv4i32:
; CHECK-SVE2:       // %bb.0:
; CHECK-SVE2-NEXT:    pmullt z2.d, z0.s, z1.s
; CHECK-SVE2-NEXT:    pmullb z0.d, z0.s, z1.s
; CHECK-SVE2-NEXT:    trn1 z0.s, z0.s, z2.s
; CHECK-SVE2-NEXT:    ret
;
; CHECK-SVE2-AES-LABEL: clmul_nxv4i32:
; CHECK-SVE2-AES:       // %bb.0:
; CHECK-SVE2-AES-NEXT:    pmullt z2.d, z0.s, z1.s
; CHECK-SVE2-AES-NEXT:    pmullb z0.d, z0.s, z1.s
; CHECK-SVE2-AES-NEXT:    trn1 z0.s, z0.s, z2.s
; CHECK-SVE2-AES-NEXT:    ret
  %a = call <vscale x 4 x i32> @llvm.clmul.nxv4i32(<vscale x 4 x i32> %x, <vscale x 4 x i32> %y)
  ret <vscale x 4 x i32> %a
}

define <vscale x 2 x i64> @clmul_nxv2i64(<vscale x 2 x i64> %x, <vscale x 2 x i64> %y) {
; CHECK-SVE-LABEL: clmul_nxv2i64:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SVE-NEXT:    addvl sp, sp, #-1
; CHECK-SVE-NEXT:    str z8, [sp] // 16-byte Folded Spill
; CHECK-SVE-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x38, 0x1e, 0x22 // sp + 16 + 8 * VG
; CHECK-SVE-NEXT:    .cfi_offset w29, -16
; CHECK-SVE-NEXT:    .cfi_escape 0x10, 0x48, 0x09, 0x92, 0x2e, 0x00, 0x11, 0x78, 0x1e, 0x22, 0x40, 0x1c // $d8 @ cfa - 8 * VG - 16
; CHECK-SVE-NEXT:    movprfx z2, z1
; CHECK-SVE-NEXT:    and z2.b, z2.b, #0x11
; CHECK-SVE-NEXT:    movprfx z3, z0
; CHECK-SVE-NEXT:    and z3.b, z3.b, #0x22
; CHECK-SVE-NEXT:    movprfx z4, z1
; CHECK-SVE-NEXT:    and z4.b, z4.b, #0x22
; CHECK-SVE-NEXT:    movprfx z5, z0
; CHECK-SVE-NEXT:    and z5.b, z5.b, #0x11
; CHECK-SVE-NEXT:    movprfx z6, z1
; CHECK-SVE-NEXT:    and z6.b, z6.b, #0x88
; CHECK-SVE-NEXT:    movprfx z7, z0
; CHECK-SVE-NEXT:    and z7.b, z7.b, #0x44
; CHECK-SVE-NEXT:    and z1.b, z1.b, #0x44
; CHECK-SVE-NEXT:    and z0.b, z0.b, #0x88
; CHECK-SVE-NEXT:    ptrue p0.d
; CHECK-SVE-NEXT:    movprfx z24, z3
; CHECK-SVE-NEXT:    mul z24.d, p0/m, z24.d, z2.d
; CHECK-SVE-NEXT:    movprfx z25, z5
; CHECK-SVE-NEXT:    mul z25.d, p0/m, z25.d, z4.d
; CHECK-SVE-NEXT:    movprfx z26, z7
; CHECK-SVE-NEXT:    mul z26.d, p0/m, z26.d, z6.d
; CHECK-SVE-NEXT:    movprfx z27, z0
; CHECK-SVE-NEXT:    mul z27.d, p0/m, z27.d, z1.d
; CHECK-SVE-NEXT:    movprfx z28, z3
; CHECK-SVE-NEXT:    mul z28.d, p0/m, z28.d, z6.d
; CHECK-SVE-NEXT:    movprfx z29, z5
; CHECK-SVE-NEXT:    mul z29.d, p0/m, z29.d, z2.d
; CHECK-SVE-NEXT:    movprfx z30, z7
; CHECK-SVE-NEXT:    mul z30.d, p0/m, z30.d, z1.d
; CHECK-SVE-NEXT:    movprfx z31, z0
; CHECK-SVE-NEXT:    mul z31.d, p0/m, z31.d, z4.d
; CHECK-SVE-NEXT:    movprfx z8, z3
; CHECK-SVE-NEXT:    mul z8.d, p0/m, z8.d, z4.d
; CHECK-SVE-NEXT:    mul z3.d, p0/m, z3.d, z1.d
; CHECK-SVE-NEXT:    mul z1.d, p0/m, z1.d, z5.d
; CHECK-SVE-NEXT:    mul z4.d, p0/m, z4.d, z7.d
; CHECK-SVE-NEXT:    mul z7.d, p0/m, z7.d, z2.d
; CHECK-SVE-NEXT:    mul z5.d, p0/m, z5.d, z6.d
; CHECK-SVE-NEXT:    mul z6.d, p0/m, z6.d, z0.d
; CHECK-SVE-NEXT:    mul z0.d, p0/m, z0.d, z2.d
; CHECK-SVE-NEXT:    eor z2.d, z25.d, z24.d
; CHECK-SVE-NEXT:    eor z24.d, z26.d, z27.d
; CHECK-SVE-NEXT:    eor z25.d, z29.d, z28.d
; CHECK-SVE-NEXT:    eor z26.d, z30.d, z31.d
; CHECK-SVE-NEXT:    eor z1.d, z1.d, z8.d
; CHECK-SVE-NEXT:    ldr z8, [sp] // 16-byte Folded Reload
; CHECK-SVE-NEXT:    eor z6.d, z7.d, z6.d
; CHECK-SVE-NEXT:    eor z3.d, z5.d, z3.d
; CHECK-SVE-NEXT:    eor z2.d, z2.d, z24.d
; CHECK-SVE-NEXT:    eor z0.d, z4.d, z0.d
; CHECK-SVE-NEXT:    eor z4.d, z25.d, z26.d
; CHECK-SVE-NEXT:    eor z1.d, z1.d, z6.d
; CHECK-SVE-NEXT:    and z2.b, z2.b, #0x22
; CHECK-SVE-NEXT:    eor z0.d, z3.d, z0.d
; CHECK-SVE-NEXT:    and z4.b, z4.b, #0x11
; CHECK-SVE-NEXT:    and z1.b, z1.b, #0x44
; CHECK-SVE-NEXT:    and z0.b, z0.b, #0x88
; CHECK-SVE-NEXT:    orr z2.d, z4.d, z2.d
; CHECK-SVE-NEXT:    orr z0.d, z1.d, z0.d
; CHECK-SVE-NEXT:    orr z0.d, z2.d, z0.d
; CHECK-SVE-NEXT:    addvl sp, sp, #1
; CHECK-SVE-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-SVE-NEXT:    ret
;
; CHECK-SVE-AES-LABEL: clmul_nxv2i64:
; CHECK-SVE-AES:       // %bb.0:
; CHECK-SVE-AES-NEXT:    pmullt z2.q, z0.d, z1.d
; CHECK-SVE-AES-NEXT:    pmullb z0.q, z0.d, z1.d
; CHECK-SVE-AES-NEXT:    trn1 z0.d, z0.d, z2.d
; CHECK-SVE-AES-NEXT:    ret
;
; CHECK-SME-STREAMING-LABEL: clmul_nxv2i64:
; CHECK-SME-STREAMING:       // %bb.0:
; CHECK-SME-STREAMING-NEXT:    trn1 z2.s, z1.s, z0.s
; CHECK-SME-STREAMING-NEXT:    trn2 z3.s, z0.s, z1.s
; CHECK-SME-STREAMING-NEXT:    pmullb z0.d, z0.s, z1.s
; CHECK-SME-STREAMING-NEXT:    pmullt z4.d, z3.s, z2.s
; CHECK-SME-STREAMING-NEXT:    pmullb z2.d, z3.s, z2.s
; CHECK-SME-STREAMING-NEXT:    trn1 z1.s, z2.s, z4.s
; CHECK-SME-STREAMING-NEXT:    eorbt z1.s, z1.s, z1.s
; CHECK-SME-STREAMING-NEXT:    eortb z0.s, z0.s, z1.s
; CHECK-SME-STREAMING-NEXT:    ret
;
; CHECK-SME-STREAMING-SSVE-AES-LABEL: clmul_nxv2i64:
; CHECK-SME-STREAMING-SSVE-AES:       // %bb.0:
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    pmullt z2.q, z0.d, z1.d
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    pmullb z0.q, z0.d, z1.d
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    trn1 z0.d, z0.d, z2.d
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    ret
;
; CHECK-SVE2-LABEL: clmul_nxv2i64:
; CHECK-SVE2:       // %bb.0:
; CHECK-SVE2-NEXT:    trn1 z2.s, z1.s, z0.s
; CHECK-SVE2-NEXT:    trn2 z3.s, z0.s, z1.s
; CHECK-SVE2-NEXT:    pmullb z0.d, z0.s, z1.s
; CHECK-SVE2-NEXT:    pmullt z4.d, z3.s, z2.s
; CHECK-SVE2-NEXT:    pmullb z2.d, z3.s, z2.s
; CHECK-SVE2-NEXT:    trn1 z1.s, z2.s, z4.s
; CHECK-SVE2-NEXT:    eorbt z1.s, z1.s, z1.s
; CHECK-SVE2-NEXT:    eortb z0.s, z0.s, z1.s
; CHECK-SVE2-NEXT:    ret
;
; CHECK-SVE2-AES-LABEL: clmul_nxv2i64:
; CHECK-SVE2-AES:       // %bb.0:
; CHECK-SVE2-AES-NEXT:    pmullt z2.q, z0.d, z1.d
; CHECK-SVE2-AES-NEXT:    pmullb z0.q, z0.d, z1.d
; CHECK-SVE2-AES-NEXT:    trn1 z0.d, z0.d, z2.d
; CHECK-SVE2-AES-NEXT:    ret
  %a = call <vscale x 2 x i64> @llvm.clmul.nxv2i64(<vscale x 2 x i64> %x, <vscale x 2 x i64> %y)
  ret <vscale x 2 x i64> %a
}

; TODO: fix
; define <vscale x 1 x i128> @clmul_nxv1i128(<vscale x 1 x i128> %x, <vscale x 1 x i128> %y) {
;   %a = call <vscale x 1 x i128> @llvm.clmul.nxv1i128(<vscale x 1 x i128> %x, <vscale x 1 x i128> %y)
;   ret <vscale x 1 x i128> %a
; }

define <vscale x 16 x i8> @clmul_nxv16i8_zext(<vscale x 16 x i4> %x, <vscale x 16 x i4> %y) {
; CHECK-SVE-LABEL: clmul_nxv16i8_zext:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    mov z2.b, #5 // =0x5
; CHECK-SVE-NEXT:    mov z3.b, #10 // =0xa
; CHECK-SVE-NEXT:    ptrue p0.b
; CHECK-SVE-NEXT:    and z4.d, z1.d, z2.d
; CHECK-SVE-NEXT:    and z5.d, z0.d, z3.d
; CHECK-SVE-NEXT:    and z1.d, z1.d, z3.d
; CHECK-SVE-NEXT:    and z0.d, z0.d, z2.d
; CHECK-SVE-NEXT:    movprfx z2, z5
; CHECK-SVE-NEXT:    mul z2.b, p0/m, z2.b, z4.b
; CHECK-SVE-NEXT:    movprfx z3, z0
; CHECK-SVE-NEXT:    mul z3.b, p0/m, z3.b, z1.b
; CHECK-SVE-NEXT:    mul z1.b, p0/m, z1.b, z5.b
; CHECK-SVE-NEXT:    mul z0.b, p0/m, z0.b, z4.b
; CHECK-SVE-NEXT:    eor z2.d, z3.d, z2.d
; CHECK-SVE-NEXT:    eor z0.d, z0.d, z1.d
; CHECK-SVE-NEXT:    and z2.b, z2.b, #0xaa
; CHECK-SVE-NEXT:    and z0.b, z0.b, #0x55
; CHECK-SVE-NEXT:    orr z0.d, z0.d, z2.d
; CHECK-SVE-NEXT:    ret
;
; CHECK-SVE-AES-LABEL: clmul_nxv16i8_zext:
; CHECK-SVE-AES:       // %bb.0:
; CHECK-SVE-AES-NEXT:    mov z2.b, #5 // =0x5
; CHECK-SVE-AES-NEXT:    mov z3.b, #10 // =0xa
; CHECK-SVE-AES-NEXT:    ptrue p0.b
; CHECK-SVE-AES-NEXT:    and z4.d, z1.d, z2.d
; CHECK-SVE-AES-NEXT:    and z5.d, z0.d, z3.d
; CHECK-SVE-AES-NEXT:    and z1.d, z1.d, z3.d
; CHECK-SVE-AES-NEXT:    and z0.d, z0.d, z2.d
; CHECK-SVE-AES-NEXT:    movprfx z2, z5
; CHECK-SVE-AES-NEXT:    mul z2.b, p0/m, z2.b, z4.b
; CHECK-SVE-AES-NEXT:    movprfx z3, z0
; CHECK-SVE-AES-NEXT:    mul z3.b, p0/m, z3.b, z1.b
; CHECK-SVE-AES-NEXT:    mul z1.b, p0/m, z1.b, z5.b
; CHECK-SVE-AES-NEXT:    mul z0.b, p0/m, z0.b, z4.b
; CHECK-SVE-AES-NEXT:    eor z2.d, z3.d, z2.d
; CHECK-SVE-AES-NEXT:    eor z0.d, z0.d, z1.d
; CHECK-SVE-AES-NEXT:    and z2.b, z2.b, #0xaa
; CHECK-SVE-AES-NEXT:    and z0.b, z0.b, #0x55
; CHECK-SVE-AES-NEXT:    orr z0.d, z0.d, z2.d
; CHECK-SVE-AES-NEXT:    ret
;
; CHECK-SME-STREAMING-LABEL: clmul_nxv16i8_zext:
; CHECK-SME-STREAMING:       // %bb.0:
; CHECK-SME-STREAMING-NEXT:    and z0.b, z0.b, #0xf
; CHECK-SME-STREAMING-NEXT:    and z1.b, z1.b, #0xf
; CHECK-SME-STREAMING-NEXT:    pmul z0.b, z0.b, z1.b
; CHECK-SME-STREAMING-NEXT:    ret
;
; CHECK-SME-STREAMING-SSVE-AES-LABEL: clmul_nxv16i8_zext:
; CHECK-SME-STREAMING-SSVE-AES:       // %bb.0:
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    and z0.b, z0.b, #0xf
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    and z1.b, z1.b, #0xf
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    pmul z0.b, z0.b, z1.b
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    ret
;
; CHECK-SVE2-LABEL: clmul_nxv16i8_zext:
; CHECK-SVE2:       // %bb.0:
; CHECK-SVE2-NEXT:    and z0.b, z0.b, #0xf
; CHECK-SVE2-NEXT:    and z1.b, z1.b, #0xf
; CHECK-SVE2-NEXT:    pmul z0.b, z0.b, z1.b
; CHECK-SVE2-NEXT:    ret
;
; CHECK-SVE2-AES-LABEL: clmul_nxv16i8_zext:
; CHECK-SVE2-AES:       // %bb.0:
; CHECK-SVE2-AES-NEXT:    and z0.b, z0.b, #0xf
; CHECK-SVE2-AES-NEXT:    and z1.b, z1.b, #0xf
; CHECK-SVE2-AES-NEXT:    pmul z0.b, z0.b, z1.b
; CHECK-SVE2-AES-NEXT:    ret
  %zextx = zext <vscale x 16 x i4> %x to <vscale x 16 x i8>
  %zexty = zext <vscale x 16 x i4> %y to <vscale x 16 x i8>
  %a = call <vscale x 16 x i8> @llvm.clmul.nxv16i8(<vscale x 16 x i8> %zextx, <vscale x 16 x i8> %zexty)
  ret <vscale x 16 x i8> %a
}

define <vscale x 8 x i16> @clmul_nxv8i16_zext(<vscale x 8 x i8> %x, <vscale x 8 x i8> %y) {
; CHECK-SVE-LABEL: clmul_nxv8i16_zext:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    mov w8, #146 // =0x92
; CHECK-SVE-NEXT:    mov z2.h, #73 // =0x49
; CHECK-SVE-NEXT:    mov z4.h, #36 // =0x24
; CHECK-SVE-NEXT:    mov z3.h, w8
; CHECK-SVE-NEXT:    ptrue p0.h
; CHECK-SVE-NEXT:    mov w8, #9362 // =0x2492
; CHECK-SVE-NEXT:    and z5.d, z1.d, z2.d
; CHECK-SVE-NEXT:    and z2.d, z0.d, z2.d
; CHECK-SVE-NEXT:    and z6.d, z0.d, z3.d
; CHECK-SVE-NEXT:    and z3.d, z1.d, z3.d
; CHECK-SVE-NEXT:    and z1.d, z1.d, z4.d
; CHECK-SVE-NEXT:    and z0.d, z0.d, z4.d
; CHECK-SVE-NEXT:    movprfx z24, z2
; CHECK-SVE-NEXT:    mul z24.h, p0/m, z24.h, z5.h
; CHECK-SVE-NEXT:    movprfx z4, z6
; CHECK-SVE-NEXT:    mul z4.h, p0/m, z4.h, z5.h
; CHECK-SVE-NEXT:    movprfx z7, z2
; CHECK-SVE-NEXT:    mul z7.h, p0/m, z7.h, z3.h
; CHECK-SVE-NEXT:    movprfx z25, z6
; CHECK-SVE-NEXT:    mul z25.h, p0/m, z25.h, z1.h
; CHECK-SVE-NEXT:    mul z2.h, p0/m, z2.h, z1.h
; CHECK-SVE-NEXT:    mul z1.h, p0/m, z1.h, z0.h
; CHECK-SVE-NEXT:    mul z5.h, p0/m, z5.h, z0.h
; CHECK-SVE-NEXT:    mul z0.h, p0/m, z0.h, z3.h
; CHECK-SVE-NEXT:    mul z3.h, p0/m, z3.h, z6.h
; CHECK-SVE-NEXT:    eor z4.d, z7.d, z4.d
; CHECK-SVE-NEXT:    eor z7.d, z24.d, z25.d
; CHECK-SVE-NEXT:    mov z24.h, w8
; CHECK-SVE-NEXT:    mov w8, #37449 // =0x9249
; CHECK-SVE-NEXT:    eor z2.d, z2.d, z5.d
; CHECK-SVE-NEXT:    eor z1.d, z4.d, z1.d
; CHECK-SVE-NEXT:    mov z4.h, w8
; CHECK-SVE-NEXT:    eor z0.d, z7.d, z0.d
; CHECK-SVE-NEXT:    mov w8, #18724 // =0x4924
; CHECK-SVE-NEXT:    eor z2.d, z2.d, z3.d
; CHECK-SVE-NEXT:    mov z3.h, w8
; CHECK-SVE-NEXT:    and z1.d, z1.d, z24.d
; CHECK-SVE-NEXT:    and z0.d, z0.d, z4.d
; CHECK-SVE-NEXT:    orr z0.d, z0.d, z1.d
; CHECK-SVE-NEXT:    and z1.d, z2.d, z3.d
; CHECK-SVE-NEXT:    orr z0.d, z0.d, z1.d
; CHECK-SVE-NEXT:    ret
;
; CHECK-SVE-AES-LABEL: clmul_nxv8i16_zext:
; CHECK-SVE-AES:       // %bb.0:
; CHECK-SVE-AES-NEXT:    mov w8, #146 // =0x92
; CHECK-SVE-AES-NEXT:    mov z2.h, #73 // =0x49
; CHECK-SVE-AES-NEXT:    mov z4.h, #36 // =0x24
; CHECK-SVE-AES-NEXT:    mov z3.h, w8
; CHECK-SVE-AES-NEXT:    ptrue p0.h
; CHECK-SVE-AES-NEXT:    mov w8, #9362 // =0x2492
; CHECK-SVE-AES-NEXT:    and z5.d, z1.d, z2.d
; CHECK-SVE-AES-NEXT:    and z2.d, z0.d, z2.d
; CHECK-SVE-AES-NEXT:    and z6.d, z0.d, z3.d
; CHECK-SVE-AES-NEXT:    and z3.d, z1.d, z3.d
; CHECK-SVE-AES-NEXT:    and z1.d, z1.d, z4.d
; CHECK-SVE-AES-NEXT:    and z0.d, z0.d, z4.d
; CHECK-SVE-AES-NEXT:    movprfx z24, z2
; CHECK-SVE-AES-NEXT:    mul z24.h, p0/m, z24.h, z5.h
; CHECK-SVE-AES-NEXT:    movprfx z4, z6
; CHECK-SVE-AES-NEXT:    mul z4.h, p0/m, z4.h, z5.h
; CHECK-SVE-AES-NEXT:    movprfx z7, z2
; CHECK-SVE-AES-NEXT:    mul z7.h, p0/m, z7.h, z3.h
; CHECK-SVE-AES-NEXT:    movprfx z25, z6
; CHECK-SVE-AES-NEXT:    mul z25.h, p0/m, z25.h, z1.h
; CHECK-SVE-AES-NEXT:    mul z2.h, p0/m, z2.h, z1.h
; CHECK-SVE-AES-NEXT:    mul z1.h, p0/m, z1.h, z0.h
; CHECK-SVE-AES-NEXT:    mul z5.h, p0/m, z5.h, z0.h
; CHECK-SVE-AES-NEXT:    mul z0.h, p0/m, z0.h, z3.h
; CHECK-SVE-AES-NEXT:    mul z3.h, p0/m, z3.h, z6.h
; CHECK-SVE-AES-NEXT:    eor z4.d, z7.d, z4.d
; CHECK-SVE-AES-NEXT:    eor z7.d, z24.d, z25.d
; CHECK-SVE-AES-NEXT:    mov z24.h, w8
; CHECK-SVE-AES-NEXT:    mov w8, #37449 // =0x9249
; CHECK-SVE-AES-NEXT:    eor z2.d, z2.d, z5.d
; CHECK-SVE-AES-NEXT:    eor z1.d, z4.d, z1.d
; CHECK-SVE-AES-NEXT:    mov z4.h, w8
; CHECK-SVE-AES-NEXT:    eor z0.d, z7.d, z0.d
; CHECK-SVE-AES-NEXT:    mov w8, #18724 // =0x4924
; CHECK-SVE-AES-NEXT:    eor z2.d, z2.d, z3.d
; CHECK-SVE-AES-NEXT:    mov z3.h, w8
; CHECK-SVE-AES-NEXT:    and z1.d, z1.d, z24.d
; CHECK-SVE-AES-NEXT:    and z0.d, z0.d, z4.d
; CHECK-SVE-AES-NEXT:    orr z0.d, z0.d, z1.d
; CHECK-SVE-AES-NEXT:    and z1.d, z2.d, z3.d
; CHECK-SVE-AES-NEXT:    orr z0.d, z0.d, z1.d
; CHECK-SVE-AES-NEXT:    ret
;
; CHECK-SME-STREAMING-LABEL: clmul_nxv8i16_zext:
; CHECK-SME-STREAMING:       // %bb.0:
; CHECK-SME-STREAMING-NEXT:    and z0.h, z0.h, #0xff
; CHECK-SME-STREAMING-NEXT:    and z1.h, z1.h, #0xff
; CHECK-SME-STREAMING-NEXT:    pmullb z0.h, z0.b, z1.b
; CHECK-SME-STREAMING-NEXT:    ret
;
; CHECK-SME-STREAMING-SSVE-AES-LABEL: clmul_nxv8i16_zext:
; CHECK-SME-STREAMING-SSVE-AES:       // %bb.0:
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    and z0.h, z0.h, #0xff
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    and z1.h, z1.h, #0xff
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    pmullb z0.h, z0.b, z1.b
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    ret
;
; CHECK-SVE2-LABEL: clmul_nxv8i16_zext:
; CHECK-SVE2:       // %bb.0:
; CHECK-SVE2-NEXT:    and z0.h, z0.h, #0xff
; CHECK-SVE2-NEXT:    and z1.h, z1.h, #0xff
; CHECK-SVE2-NEXT:    pmullb z0.h, z0.b, z1.b
; CHECK-SVE2-NEXT:    ret
;
; CHECK-SVE2-AES-LABEL: clmul_nxv8i16_zext:
; CHECK-SVE2-AES:       // %bb.0:
; CHECK-SVE2-AES-NEXT:    and z0.h, z0.h, #0xff
; CHECK-SVE2-AES-NEXT:    and z1.h, z1.h, #0xff
; CHECK-SVE2-AES-NEXT:    pmullb z0.h, z0.b, z1.b
; CHECK-SVE2-AES-NEXT:    ret
  %zextx = zext <vscale x 8 x i8> %x to <vscale x 8 x i16>
  %zexty = zext <vscale x 8 x i8> %y to <vscale x 8 x i16>
  %a = call <vscale x 8 x i16> @llvm.clmul.nxv8i16(<vscale x 8 x i16> %zextx, <vscale x 8 x i16> %zexty)
  ret <vscale x 8 x i16> %a
}

define <vscale x 4 x i32> @clmul_nxv4i32_zext(<vscale x 4 x i16> %x, <vscale x 4 x i16> %y) {
; CHECK-SVE-LABEL: clmul_nxv4i32_zext:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SVE-NEXT:    addvl sp, sp, #-1
; CHECK-SVE-NEXT:    str z8, [sp] // 16-byte Folded Spill
; CHECK-SVE-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x38, 0x1e, 0x22 // sp + 16 + 8 * VG
; CHECK-SVE-NEXT:    .cfi_offset w29, -16
; CHECK-SVE-NEXT:    .cfi_escape 0x10, 0x48, 0x09, 0x92, 0x2e, 0x00, 0x11, 0x78, 0x1e, 0x22, 0x40, 0x1c // $d8 @ cfa - 8 * VG - 16
; CHECK-SVE-NEXT:    mov w8, #4369 // =0x1111
; CHECK-SVE-NEXT:    mov w9, #8738 // =0x2222
; CHECK-SVE-NEXT:    ptrue p0.s
; CHECK-SVE-NEXT:    mov z2.s, w8
; CHECK-SVE-NEXT:    mov w8, #34952 // =0x8888
; CHECK-SVE-NEXT:    mov z3.s, w9
; CHECK-SVE-NEXT:    mov z4.s, w8
; CHECK-SVE-NEXT:    mov w8, #17476 // =0x4444
; CHECK-SVE-NEXT:    mov z5.s, w8
; CHECK-SVE-NEXT:    and z6.d, z1.d, z2.d
; CHECK-SVE-NEXT:    and z7.d, z0.d, z3.d
; CHECK-SVE-NEXT:    and z3.d, z1.d, z3.d
; CHECK-SVE-NEXT:    and z2.d, z0.d, z2.d
; CHECK-SVE-NEXT:    and z24.d, z1.d, z4.d
; CHECK-SVE-NEXT:    and z25.d, z0.d, z5.d
; CHECK-SVE-NEXT:    and z1.d, z1.d, z5.d
; CHECK-SVE-NEXT:    and z0.d, z0.d, z4.d
; CHECK-SVE-NEXT:    movprfx z4, z7
; CHECK-SVE-NEXT:    mul z4.s, p0/m, z4.s, z6.s
; CHECK-SVE-NEXT:    movprfx z8, z7
; CHECK-SVE-NEXT:    mul z8.s, p0/m, z8.s, z3.s
; CHECK-SVE-NEXT:    movprfx z5, z2
; CHECK-SVE-NEXT:    mul z5.s, p0/m, z5.s, z3.s
; CHECK-SVE-NEXT:    movprfx z28, z7
; CHECK-SVE-NEXT:    mul z28.s, p0/m, z28.s, z24.s
; CHECK-SVE-NEXT:    movprfx z29, z2
; CHECK-SVE-NEXT:    mul z29.s, p0/m, z29.s, z6.s
; CHECK-SVE-NEXT:    movprfx z26, z25
; CHECK-SVE-NEXT:    mul z26.s, p0/m, z26.s, z24.s
; CHECK-SVE-NEXT:    movprfx z27, z0
; CHECK-SVE-NEXT:    mul z27.s, p0/m, z27.s, z1.s
; CHECK-SVE-NEXT:    movprfx z30, z25
; CHECK-SVE-NEXT:    mul z30.s, p0/m, z30.s, z1.s
; CHECK-SVE-NEXT:    movprfx z31, z0
; CHECK-SVE-NEXT:    mul z31.s, p0/m, z31.s, z3.s
; CHECK-SVE-NEXT:    mul z7.s, p0/m, z7.s, z1.s
; CHECK-SVE-NEXT:    mul z1.s, p0/m, z1.s, z2.s
; CHECK-SVE-NEXT:    mul z3.s, p0/m, z3.s, z25.s
; CHECK-SVE-NEXT:    mul z25.s, p0/m, z25.s, z6.s
; CHECK-SVE-NEXT:    mul z2.s, p0/m, z2.s, z24.s
; CHECK-SVE-NEXT:    mul z24.s, p0/m, z24.s, z0.s
; CHECK-SVE-NEXT:    eor z4.d, z5.d, z4.d
; CHECK-SVE-NEXT:    mul z0.s, p0/m, z0.s, z6.s
; CHECK-SVE-NEXT:    eor z5.d, z26.d, z27.d
; CHECK-SVE-NEXT:    eor z6.d, z29.d, z28.d
; CHECK-SVE-NEXT:    eor z26.d, z30.d, z31.d
; CHECK-SVE-NEXT:    eor z1.d, z1.d, z8.d
; CHECK-SVE-NEXT:    ldr z8, [sp] // 16-byte Folded Reload
; CHECK-SVE-NEXT:    eor z24.d, z25.d, z24.d
; CHECK-SVE-NEXT:    eor z2.d, z2.d, z7.d
; CHECK-SVE-NEXT:    eor z0.d, z3.d, z0.d
; CHECK-SVE-NEXT:    eor z3.d, z4.d, z5.d
; CHECK-SVE-NEXT:    eor z4.d, z6.d, z26.d
; CHECK-SVE-NEXT:    eor z1.d, z1.d, z24.d
; CHECK-SVE-NEXT:    eor z0.d, z2.d, z0.d
; CHECK-SVE-NEXT:    and z3.b, z3.b, #0x22
; CHECK-SVE-NEXT:    and z4.b, z4.b, #0x11
; CHECK-SVE-NEXT:    and z1.b, z1.b, #0x44
; CHECK-SVE-NEXT:    and z0.b, z0.b, #0x88
; CHECK-SVE-NEXT:    orr z2.d, z4.d, z3.d
; CHECK-SVE-NEXT:    orr z0.d, z1.d, z0.d
; CHECK-SVE-NEXT:    orr z0.d, z2.d, z0.d
; CHECK-SVE-NEXT:    addvl sp, sp, #1
; CHECK-SVE-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-SVE-NEXT:    ret
;
; CHECK-SVE-AES-LABEL: clmul_nxv4i32_zext:
; CHECK-SVE-AES:       // %bb.0:
; CHECK-SVE-AES-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SVE-AES-NEXT:    addvl sp, sp, #-1
; CHECK-SVE-AES-NEXT:    str z8, [sp] // 16-byte Folded Spill
; CHECK-SVE-AES-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x38, 0x1e, 0x22 // sp + 16 + 8 * VG
; CHECK-SVE-AES-NEXT:    .cfi_offset w29, -16
; CHECK-SVE-AES-NEXT:    .cfi_escape 0x10, 0x48, 0x09, 0x92, 0x2e, 0x00, 0x11, 0x78, 0x1e, 0x22, 0x40, 0x1c // $d8 @ cfa - 8 * VG - 16
; CHECK-SVE-AES-NEXT:    mov w8, #4369 // =0x1111
; CHECK-SVE-AES-NEXT:    mov w9, #8738 // =0x2222
; CHECK-SVE-AES-NEXT:    ptrue p0.s
; CHECK-SVE-AES-NEXT:    mov z2.s, w8
; CHECK-SVE-AES-NEXT:    mov w8, #34952 // =0x8888
; CHECK-SVE-AES-NEXT:    mov z3.s, w9
; CHECK-SVE-AES-NEXT:    mov z4.s, w8
; CHECK-SVE-AES-NEXT:    mov w8, #17476 // =0x4444
; CHECK-SVE-AES-NEXT:    mov z5.s, w8
; CHECK-SVE-AES-NEXT:    and z6.d, z1.d, z2.d
; CHECK-SVE-AES-NEXT:    and z7.d, z0.d, z3.d
; CHECK-SVE-AES-NEXT:    and z3.d, z1.d, z3.d
; CHECK-SVE-AES-NEXT:    and z2.d, z0.d, z2.d
; CHECK-SVE-AES-NEXT:    and z24.d, z1.d, z4.d
; CHECK-SVE-AES-NEXT:    and z25.d, z0.d, z5.d
; CHECK-SVE-AES-NEXT:    and z1.d, z1.d, z5.d
; CHECK-SVE-AES-NEXT:    and z0.d, z0.d, z4.d
; CHECK-SVE-AES-NEXT:    movprfx z4, z7
; CHECK-SVE-AES-NEXT:    mul z4.s, p0/m, z4.s, z6.s
; CHECK-SVE-AES-NEXT:    movprfx z8, z7
; CHECK-SVE-AES-NEXT:    mul z8.s, p0/m, z8.s, z3.s
; CHECK-SVE-AES-NEXT:    movprfx z5, z2
; CHECK-SVE-AES-NEXT:    mul z5.s, p0/m, z5.s, z3.s
; CHECK-SVE-AES-NEXT:    movprfx z28, z7
; CHECK-SVE-AES-NEXT:    mul z28.s, p0/m, z28.s, z24.s
; CHECK-SVE-AES-NEXT:    movprfx z29, z2
; CHECK-SVE-AES-NEXT:    mul z29.s, p0/m, z29.s, z6.s
; CHECK-SVE-AES-NEXT:    movprfx z26, z25
; CHECK-SVE-AES-NEXT:    mul z26.s, p0/m, z26.s, z24.s
; CHECK-SVE-AES-NEXT:    movprfx z27, z0
; CHECK-SVE-AES-NEXT:    mul z27.s, p0/m, z27.s, z1.s
; CHECK-SVE-AES-NEXT:    movprfx z30, z25
; CHECK-SVE-AES-NEXT:    mul z30.s, p0/m, z30.s, z1.s
; CHECK-SVE-AES-NEXT:    movprfx z31, z0
; CHECK-SVE-AES-NEXT:    mul z31.s, p0/m, z31.s, z3.s
; CHECK-SVE-AES-NEXT:    mul z7.s, p0/m, z7.s, z1.s
; CHECK-SVE-AES-NEXT:    mul z1.s, p0/m, z1.s, z2.s
; CHECK-SVE-AES-NEXT:    mul z3.s, p0/m, z3.s, z25.s
; CHECK-SVE-AES-NEXT:    mul z25.s, p0/m, z25.s, z6.s
; CHECK-SVE-AES-NEXT:    mul z2.s, p0/m, z2.s, z24.s
; CHECK-SVE-AES-NEXT:    mul z24.s, p0/m, z24.s, z0.s
; CHECK-SVE-AES-NEXT:    eor z4.d, z5.d, z4.d
; CHECK-SVE-AES-NEXT:    mul z0.s, p0/m, z0.s, z6.s
; CHECK-SVE-AES-NEXT:    eor z5.d, z26.d, z27.d
; CHECK-SVE-AES-NEXT:    eor z6.d, z29.d, z28.d
; CHECK-SVE-AES-NEXT:    eor z26.d, z30.d, z31.d
; CHECK-SVE-AES-NEXT:    eor z1.d, z1.d, z8.d
; CHECK-SVE-AES-NEXT:    ldr z8, [sp] // 16-byte Folded Reload
; CHECK-SVE-AES-NEXT:    eor z24.d, z25.d, z24.d
; CHECK-SVE-AES-NEXT:    eor z2.d, z2.d, z7.d
; CHECK-SVE-AES-NEXT:    eor z0.d, z3.d, z0.d
; CHECK-SVE-AES-NEXT:    eor z3.d, z4.d, z5.d
; CHECK-SVE-AES-NEXT:    eor z4.d, z6.d, z26.d
; CHECK-SVE-AES-NEXT:    eor z1.d, z1.d, z24.d
; CHECK-SVE-AES-NEXT:    eor z0.d, z2.d, z0.d
; CHECK-SVE-AES-NEXT:    and z3.b, z3.b, #0x22
; CHECK-SVE-AES-NEXT:    and z4.b, z4.b, #0x11
; CHECK-SVE-AES-NEXT:    and z1.b, z1.b, #0x44
; CHECK-SVE-AES-NEXT:    and z0.b, z0.b, #0x88
; CHECK-SVE-AES-NEXT:    orr z2.d, z4.d, z3.d
; CHECK-SVE-AES-NEXT:    orr z0.d, z1.d, z0.d
; CHECK-SVE-AES-NEXT:    orr z0.d, z2.d, z0.d
; CHECK-SVE-AES-NEXT:    addvl sp, sp, #1
; CHECK-SVE-AES-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-SVE-AES-NEXT:    ret
;
; CHECK-SME-STREAMING-LABEL: clmul_nxv4i32_zext:
; CHECK-SME-STREAMING:       // %bb.0:
; CHECK-SME-STREAMING-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-SME-STREAMING-NEXT:    and z1.s, z1.s, #0xffff
; CHECK-SME-STREAMING-NEXT:    pmullt z2.d, z0.s, z1.s
; CHECK-SME-STREAMING-NEXT:    pmullb z0.d, z0.s, z1.s
; CHECK-SME-STREAMING-NEXT:    trn1 z0.s, z0.s, z2.s
; CHECK-SME-STREAMING-NEXT:    ret
;
; CHECK-SME-STREAMING-SSVE-AES-LABEL: clmul_nxv4i32_zext:
; CHECK-SME-STREAMING-SSVE-AES:       // %bb.0:
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    and z1.s, z1.s, #0xffff
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    pmullt z2.d, z0.s, z1.s
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    pmullb z0.d, z0.s, z1.s
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    trn1 z0.s, z0.s, z2.s
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    ret
;
; CHECK-SVE2-LABEL: clmul_nxv4i32_zext:
; CHECK-SVE2:       // %bb.0:
; CHECK-SVE2-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-SVE2-NEXT:    and z1.s, z1.s, #0xffff
; CHECK-SVE2-NEXT:    pmullt z2.d, z0.s, z1.s
; CHECK-SVE2-NEXT:    pmullb z0.d, z0.s, z1.s
; CHECK-SVE2-NEXT:    trn1 z0.s, z0.s, z2.s
; CHECK-SVE2-NEXT:    ret
;
; CHECK-SVE2-AES-LABEL: clmul_nxv4i32_zext:
; CHECK-SVE2-AES:       // %bb.0:
; CHECK-SVE2-AES-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-SVE2-AES-NEXT:    and z1.s, z1.s, #0xffff
; CHECK-SVE2-AES-NEXT:    pmullt z2.d, z0.s, z1.s
; CHECK-SVE2-AES-NEXT:    pmullb z0.d, z0.s, z1.s
; CHECK-SVE2-AES-NEXT:    trn1 z0.s, z0.s, z2.s
; CHECK-SVE2-AES-NEXT:    ret
  %zextx = zext <vscale x 4 x i16> %x to <vscale x 4 x i32>
  %zexty = zext <vscale x 4 x i16> %y to <vscale x 4 x i32>
  %a = call <vscale x 4 x i32> @llvm.clmul.nxv4i32(<vscale x 4 x i32> %zextx, <vscale x 4 x i32> %zexty)
  ret <vscale x 4 x i32> %a
}

define <vscale x 2 x i64> @clmul_nxv2i64_zext(<vscale x 2 x i32> %x, <vscale x 2 x i32> %y) {
; CHECK-SVE-LABEL: clmul_nxv2i64_zext:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SVE-NEXT:    addvl sp, sp, #-1
; CHECK-SVE-NEXT:    str z8, [sp] // 16-byte Folded Spill
; CHECK-SVE-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x38, 0x1e, 0x22 // sp + 16 + 8 * VG
; CHECK-SVE-NEXT:    .cfi_offset w29, -16
; CHECK-SVE-NEXT:    .cfi_escape 0x10, 0x48, 0x09, 0x92, 0x2e, 0x00, 0x11, 0x78, 0x1e, 0x22, 0x40, 0x1c // $d8 @ cfa - 8 * VG - 16
; CHECK-SVE-NEXT:    mov w8, #286331153 // =0x11111111
; CHECK-SVE-NEXT:    mov w9, #572662306 // =0x22222222
; CHECK-SVE-NEXT:    ptrue p0.d
; CHECK-SVE-NEXT:    mov z2.d, x8
; CHECK-SVE-NEXT:    mov w8, #-2004318072 // =0x88888888
; CHECK-SVE-NEXT:    mov z3.d, x9
; CHECK-SVE-NEXT:    mov z4.d, x8
; CHECK-SVE-NEXT:    mov w8, #1145324612 // =0x44444444
; CHECK-SVE-NEXT:    mov z5.d, x8
; CHECK-SVE-NEXT:    and z6.d, z1.d, z2.d
; CHECK-SVE-NEXT:    and z7.d, z0.d, z3.d
; CHECK-SVE-NEXT:    and z3.d, z1.d, z3.d
; CHECK-SVE-NEXT:    and z2.d, z0.d, z2.d
; CHECK-SVE-NEXT:    and z24.d, z1.d, z4.d
; CHECK-SVE-NEXT:    and z25.d, z0.d, z5.d
; CHECK-SVE-NEXT:    and z1.d, z1.d, z5.d
; CHECK-SVE-NEXT:    and z0.d, z0.d, z4.d
; CHECK-SVE-NEXT:    movprfx z4, z7
; CHECK-SVE-NEXT:    mul z4.d, p0/m, z4.d, z6.d
; CHECK-SVE-NEXT:    movprfx z8, z7
; CHECK-SVE-NEXT:    mul z8.d, p0/m, z8.d, z3.d
; CHECK-SVE-NEXT:    movprfx z5, z2
; CHECK-SVE-NEXT:    mul z5.d, p0/m, z5.d, z3.d
; CHECK-SVE-NEXT:    movprfx z28, z7
; CHECK-SVE-NEXT:    mul z28.d, p0/m, z28.d, z24.d
; CHECK-SVE-NEXT:    movprfx z29, z2
; CHECK-SVE-NEXT:    mul z29.d, p0/m, z29.d, z6.d
; CHECK-SVE-NEXT:    movprfx z26, z25
; CHECK-SVE-NEXT:    mul z26.d, p0/m, z26.d, z24.d
; CHECK-SVE-NEXT:    movprfx z27, z0
; CHECK-SVE-NEXT:    mul z27.d, p0/m, z27.d, z1.d
; CHECK-SVE-NEXT:    movprfx z30, z25
; CHECK-SVE-NEXT:    mul z30.d, p0/m, z30.d, z1.d
; CHECK-SVE-NEXT:    movprfx z31, z0
; CHECK-SVE-NEXT:    mul z31.d, p0/m, z31.d, z3.d
; CHECK-SVE-NEXT:    mul z7.d, p0/m, z7.d, z1.d
; CHECK-SVE-NEXT:    mul z1.d, p0/m, z1.d, z2.d
; CHECK-SVE-NEXT:    mul z3.d, p0/m, z3.d, z25.d
; CHECK-SVE-NEXT:    mul z25.d, p0/m, z25.d, z6.d
; CHECK-SVE-NEXT:    mul z2.d, p0/m, z2.d, z24.d
; CHECK-SVE-NEXT:    mul z24.d, p0/m, z24.d, z0.d
; CHECK-SVE-NEXT:    eor z4.d, z5.d, z4.d
; CHECK-SVE-NEXT:    mul z0.d, p0/m, z0.d, z6.d
; CHECK-SVE-NEXT:    eor z5.d, z26.d, z27.d
; CHECK-SVE-NEXT:    eor z6.d, z29.d, z28.d
; CHECK-SVE-NEXT:    eor z26.d, z30.d, z31.d
; CHECK-SVE-NEXT:    eor z1.d, z1.d, z8.d
; CHECK-SVE-NEXT:    ldr z8, [sp] // 16-byte Folded Reload
; CHECK-SVE-NEXT:    eor z24.d, z25.d, z24.d
; CHECK-SVE-NEXT:    eor z2.d, z2.d, z7.d
; CHECK-SVE-NEXT:    eor z0.d, z3.d, z0.d
; CHECK-SVE-NEXT:    eor z3.d, z4.d, z5.d
; CHECK-SVE-NEXT:    eor z4.d, z6.d, z26.d
; CHECK-SVE-NEXT:    eor z1.d, z1.d, z24.d
; CHECK-SVE-NEXT:    eor z0.d, z2.d, z0.d
; CHECK-SVE-NEXT:    and z3.b, z3.b, #0x22
; CHECK-SVE-NEXT:    and z4.b, z4.b, #0x11
; CHECK-SVE-NEXT:    and z1.b, z1.b, #0x44
; CHECK-SVE-NEXT:    and z0.b, z0.b, #0x88
; CHECK-SVE-NEXT:    orr z2.d, z4.d, z3.d
; CHECK-SVE-NEXT:    orr z0.d, z1.d, z0.d
; CHECK-SVE-NEXT:    orr z0.d, z2.d, z0.d
; CHECK-SVE-NEXT:    addvl sp, sp, #1
; CHECK-SVE-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-SVE-NEXT:    ret
;
; CHECK-SVE-AES-LABEL: clmul_nxv2i64_zext:
; CHECK-SVE-AES:       // %bb.0:
; CHECK-SVE-AES-NEXT:    and z0.d, z0.d, #0xffffffff
; CHECK-SVE-AES-NEXT:    and z1.d, z1.d, #0xffffffff
; CHECK-SVE-AES-NEXT:    pmullt z2.q, z0.d, z1.d
; CHECK-SVE-AES-NEXT:    pmullb z0.q, z0.d, z1.d
; CHECK-SVE-AES-NEXT:    trn1 z0.d, z0.d, z2.d
; CHECK-SVE-AES-NEXT:    ret
;
; CHECK-SME-STREAMING-LABEL: clmul_nxv2i64_zext:
; CHECK-SME-STREAMING:       // %bb.0:
; CHECK-SME-STREAMING-NEXT:    and z0.d, z0.d, #0xffffffff
; CHECK-SME-STREAMING-NEXT:    and z1.d, z1.d, #0xffffffff
; CHECK-SME-STREAMING-NEXT:    pmullb z0.d, z0.s, z1.s
; CHECK-SME-STREAMING-NEXT:    ret
;
; CHECK-SME-STREAMING-SSVE-AES-LABEL: clmul_nxv2i64_zext:
; CHECK-SME-STREAMING-SSVE-AES:       // %bb.0:
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    and z0.d, z0.d, #0xffffffff
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    and z1.d, z1.d, #0xffffffff
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    pmullb z0.d, z0.s, z1.s
; CHECK-SME-STREAMING-SSVE-AES-NEXT:    ret
;
; CHECK-SVE2-LABEL: clmul_nxv2i64_zext:
; CHECK-SVE2:       // %bb.0:
; CHECK-SVE2-NEXT:    and z0.d, z0.d, #0xffffffff
; CHECK-SVE2-NEXT:    and z1.d, z1.d, #0xffffffff
; CHECK-SVE2-NEXT:    pmullb z0.d, z0.s, z1.s
; CHECK-SVE2-NEXT:    ret
;
; CHECK-SVE2-AES-LABEL: clmul_nxv2i64_zext:
; CHECK-SVE2-AES:       // %bb.0:
; CHECK-SVE2-AES-NEXT:    and z0.d, z0.d, #0xffffffff
; CHECK-SVE2-AES-NEXT:    and z1.d, z1.d, #0xffffffff
; CHECK-SVE2-AES-NEXT:    pmullb z0.d, z0.s, z1.s
; CHECK-SVE2-AES-NEXT:    ret
  %zextx = zext <vscale x 2 x i32> %x to <vscale x 2 x i64>
  %zexty = zext <vscale x 2 x i32> %y to <vscale x 2 x i64>
  %a = call <vscale x 2 x i64> @llvm.clmul.nxv2i64(<vscale x 2 x i64> %zextx, <vscale x 2 x i64> %zexty)
  ret <vscale x 2 x i64> %a
}

; TODO: fix
; define <vscale x 1 x i128> @clmul_nxv1i128_zext(<vscale x 1 x i64> %x, <vscale x 1 x i64> %y) {
;   %zextx = zext <vscale x 1 x i64> %x to <vscale x 1 x i128>
;   %zexty = zext <vscale x 1 x i64> %y to <vscale x 1 x i128>
;   %a = call <vscale x 1 x i128> @llvm.clmul.nxv1i128(<vscale x 1 x i128> %zextx, <vscale x 1 x i128> %zexty)
;   ret <vscale x 1 x i128> %a
; }
