; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-none-linux-gnu < %s | FileCheck %s

;; Verify the Register Coalescer's trivial remat does not duplicate
;; multi-instruction "cheap as a move" pseudos when the original def
;; would survive. AArch64 MOVi64imm with a 2-instruction expansion
;; (MOVZ + MOVK) exercises the code path: 0x1234000000005678 has two
;; non-zero 16-bit fields.

declare i64 @sink_two(i64, i64) nounwind
declare i64 @sink_one(i64) nounwind

;; Multiple uses across a call: the def must be kept alive in a
;; callee-saved register, and the call argument should be set up by a
;; mov from that register. Without the gate, the coalescer would
;; rematerialize a second MOVZ+MOVK into x1 before the call, growing
;; code size by 4 bytes.
define i64 @multi_use_across_call(i64 %x) nounwind {
; CHECK-LABEL: multi_use_across_call:
; CHECK:       // %bb.0:
; CHECK-NEXT:    stp x30, x19, [sp, #-16]! // 16-byte Folded Spill
; CHECK-NEXT:    mov x19, #22136 // =0x5678
; CHECK-NEXT:    movk x19, #4660, lsl #48
; CHECK-NEXT:    mov x1, x19
; CHECK-NEXT:    bl sink_two
; CHECK-NEXT:    add x0, x0, x19
; CHECK-NEXT:    ldp x30, x19, [sp], #16 // 16-byte Folded Reload
; CHECK-NEXT:    ret
  %v = call i64 @sink_two(i64 %x, i64 1311673391471679096)
  %r = add i64 %v, 1311673391471679096
  ret i64 %r
}

;; Single use across a call: the remat should still fire, placing the
;; MOVZ+MOVK directly into the argument register and avoiding the
;; callee-saved spill entirely.
define i64 @single_use_across_call(i64 %x) nounwind {
; CHECK-LABEL: single_use_across_call:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    mov x1, #22136 // =0x5678
; CHECK-NEXT:    movk x1, #4660, lsl #48
; CHECK-NEXT:    bl sink_two
; CHECK-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %v = call i64 @sink_two(i64 %x, i64 1311673391471679096)
  ret i64 %v
}
