; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc --mtriple=aarch64 --mattr=+fullfp16 < %s | FileCheck  %s --check-prefixes=CHECK,FP16
; RUN: llc --mtriple=aarch64 --mattr=-fullfp16 < %s | FileCheck  %s --check-prefixes=CHECK,NOFP16

define float @maxf(float %a, float %b) {
; CHECK-LABEL: maxf:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fmaxnm s0, s0, s1
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp nnan nsz oge float %a, %b
  %cond = select nnan nsz i1 %cmp, float %a, float %b
  ret float %cond
}

define float @minf(float %a, float %b) {
; CHECK-LABEL: minf:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fminnm s0, s0, s1
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp nnan nsz olt float %a, %b
  %cond = select nnan nsz i1 %cmp, float %a, float %b
  ret float %cond
}

define double @maxd(double %a, double %b) {
; CHECK-LABEL: maxd:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fmaxnm d0, d0, d1
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp nnan nsz oge double %a, %b
  %cond = select nnan nsz i1 %cmp, double %a, double %b
  ret double %cond
}

define double @mind(double %a, double %b) {
; CHECK-LABEL: mind:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fminnm d0, d0, d1
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp nnan nsz olt double %a, %b
  %cond = select nnan nsz i1 %cmp, double %a, double %b
  ret double %cond
}

define half @maxh(half %a, half %b) {
; FP16-LABEL: maxh:
; FP16:       // %bb.0: // %entry
; FP16-NEXT:    fmaxnm h0, h0, h1
; FP16-NEXT:    ret
;
; NOFP16-LABEL: maxh:
; NOFP16:       // %bb.0: // %entry
; NOFP16-NEXT:    // kill: def $h1 killed $h1 def $s1
; NOFP16-NEXT:    // kill: def $h0 killed $h0 def $s0
; NOFP16-NEXT:    fcvt s2, h1
; NOFP16-NEXT:    fcvt s3, h0
; NOFP16-NEXT:    fcmp s3, s2
; NOFP16-NEXT:    fcsel s0, s0, s1, ge
; NOFP16-NEXT:    // kill: def $h0 killed $h0 killed $s0
; NOFP16-NEXT:    ret
entry:
  %cmp = fcmp nnan nsz oge half %a, %b
  %cond = select nnan nsz i1 %cmp, half %a, half %b
  ret half %cond
}

define half @minh(half %a, half %b) {
; FP16-LABEL: minh:
; FP16:       // %bb.0: // %entry
; FP16-NEXT:    fminnm h0, h0, h1
; FP16-NEXT:    ret
;
; NOFP16-LABEL: minh:
; NOFP16:       // %bb.0: // %entry
; NOFP16-NEXT:    // kill: def $h1 killed $h1 def $s1
; NOFP16-NEXT:    // kill: def $h0 killed $h0 def $s0
; NOFP16-NEXT:    fcvt s2, h1
; NOFP16-NEXT:    fcvt s3, h0
; NOFP16-NEXT:    fcmp s3, s2
; NOFP16-NEXT:    fcsel s0, s0, s1, lt
; NOFP16-NEXT:    // kill: def $h0 killed $h0 killed $s0
; NOFP16-NEXT:    ret
entry:
  %cmp = fcmp nnan nsz olt half %a, %b
  %cond = select nnan nsz i1 %cmp, half %a, half %b
  ret half %cond
}
