; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -enable-machine-outliner=never -verify-machineinstrs < %s -mtriple=aarch64-none-linux-gnu -mcpu=cyclone | FileCheck %s
; RUN: llc -enable-machine-outliner=never -verify-machineinstrs < %s -mtriple=aarch64-none-linux-gnu -mattr=-fp-armv8 | FileCheck --check-prefix=CHECK-NOFP %s

@var32 = global i32 0
@var64 = global i64 0

define void @test_csel(i32 %lhs32, i32 %rhs32, i64 %lhs64) minsize {
; CHECK-LABEL: test_csel:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-NEXT:    cmp w0, w1
; CHECK-NEXT:    mov w8, #52 // =0x34
; CHECK-NEXT:    mov w9, #42 // =0x2a
; CHECK-NEXT:    csel w8, w9, w8, hi
; CHECK-NEXT:    adrp x9, :got:var32
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var32]
; CHECK-NEXT:    str w8, [x9]
; CHECK-NEXT:    sxtw x8, w1
; CHECK-NEXT:    cmp x2, w1, sxtw
; CHECK-NEXT:    csel x8, x2, x8, lt
; CHECK-NEXT:    adrp x9, :got:var64
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var64]
; CHECK-NEXT:    str x8, [x9]
; CHECK-NEXT:    ret
;
; CHECK-NOFP-LABEL: test_csel:
; CHECK-NOFP:       // %bb.0:
; CHECK-NOFP-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-NOFP-NEXT:    mov w8, #52 // =0x34
; CHECK-NOFP-NEXT:    mov w9, #42 // =0x2a
; CHECK-NOFP-NEXT:    cmp w0, w1
; CHECK-NOFP-NEXT:    adrp x10, :got:var32
; CHECK-NOFP-NEXT:    csel w8, w9, w8, hi
; CHECK-NOFP-NEXT:    sxtw x9, w1
; CHECK-NOFP-NEXT:    ldr x10, [x10, :got_lo12:var32]
; CHECK-NOFP-NEXT:    adrp x11, :got:var64
; CHECK-NOFP-NEXT:    cmp x2, w1, sxtw
; CHECK-NOFP-NEXT:    ldr x11, [x11, :got_lo12:var64]
; CHECK-NOFP-NEXT:    str w8, [x10]
; CHECK-NOFP-NEXT:    csel x8, x2, x9, lt
; CHECK-NOFP-NEXT:    str x8, [x11]
; CHECK-NOFP-NEXT:    ret

  %tst1 = icmp ugt i32 %lhs32, %rhs32
  %val1 = select i1 %tst1, i32 42, i32 52
  store i32 %val1, ptr @var32

  %rhs64 = sext i32 %rhs32 to i64
  %tst2 = icmp sle i64 %lhs64, %rhs64
  %val2 = select i1 %tst2, i64 %lhs64, i64 %rhs64
  store i64 %val2, ptr @var64

  ret void
}

define void @test_floatcsel(float %lhs32, float %rhs32, double %lhs64, double %rhs64) {
; CHECK-LABEL: test_floatcsel:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcmp s0, s1
; CHECK-NEXT:    mov w8, #52 // =0x34
; CHECK-NEXT:    mov w9, #42 // =0x2a
; CHECK-NEXT:    csel w8, w9, w8, mi
; CHECK-NEXT:    csel w8, w9, w8, gt
; CHECK-NEXT:    adrp x9, :got:var32
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var32]
; CHECK-NEXT:    str w8, [x9]
; CHECK-NEXT:    fcmp d2, d3
; CHECK-NEXT:    mov w8, #15 // =0xf
; CHECK-NEXT:    mov w9, #9 // =0x9
; CHECK-NEXT:    csel x8, x9, x8, eq
; CHECK-NEXT:    csel x8, x9, x8, vs
; CHECK-NEXT:    adrp x9, :got:var64
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var64]
; CHECK-NEXT:    str x8, [x9]
; CHECK-NEXT:    ret
;
; CHECK-NOFP-LABEL: test_floatcsel:
; CHECK-NOFP:       // %bb.0:
; CHECK-NOFP-NEXT:    stp x30, x23, [sp, #-48]! // 16-byte Folded Spill
; CHECK-NOFP-NEXT:    stp x22, x21, [sp, #16] // 16-byte Folded Spill
; CHECK-NOFP-NEXT:    stp x20, x19, [sp, #32] // 16-byte Folded Spill
; CHECK-NOFP-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NOFP-NEXT:    .cfi_offset w19, -8
; CHECK-NOFP-NEXT:    .cfi_offset w20, -16
; CHECK-NOFP-NEXT:    .cfi_offset w21, -24
; CHECK-NOFP-NEXT:    .cfi_offset w22, -32
; CHECK-NOFP-NEXT:    .cfi_offset w23, -40
; CHECK-NOFP-NEXT:    .cfi_offset w30, -48
; CHECK-NOFP-NEXT:    mov x19, x3
; CHECK-NOFP-NEXT:    mov x20, x2
; CHECK-NOFP-NEXT:    mov w21, w1
; CHECK-NOFP-NEXT:    mov w22, w0
; CHECK-NOFP-NEXT:    bl __unordsf2
; CHECK-NOFP-NEXT:    mov w23, w0
; CHECK-NOFP-NEXT:    mov w0, w22
; CHECK-NOFP-NEXT:    mov w1, w21
; CHECK-NOFP-NEXT:    bl __eqsf2
; CHECK-NOFP-NEXT:    cmp w0, #0
; CHECK-NOFP-NEXT:    adrp x10, :got:var32
; CHECK-NOFP-NEXT:    mov w8, #52 // =0x34
; CHECK-NOFP-NEXT:    ccmp w23, #0, #0, ne
; CHECK-NOFP-NEXT:    mov w9, #42 // =0x2a
; CHECK-NOFP-NEXT:    ldr x10, [x10, :got_lo12:var32]
; CHECK-NOFP-NEXT:    csel w8, w9, w8, eq
; CHECK-NOFP-NEXT:    mov x0, x20
; CHECK-NOFP-NEXT:    mov x1, x19
; CHECK-NOFP-NEXT:    str w8, [x10]
; CHECK-NOFP-NEXT:    bl __unorddf2
; CHECK-NOFP-NEXT:    mov w21, w0
; CHECK-NOFP-NEXT:    mov x0, x20
; CHECK-NOFP-NEXT:    mov x1, x19
; CHECK-NOFP-NEXT:    bl __eqdf2
; CHECK-NOFP-NEXT:    cmp w0, #0
; CHECK-NOFP-NEXT:    adrp x10, :got:var64
; CHECK-NOFP-NEXT:    mov w8, #15 // =0xf
; CHECK-NOFP-NEXT:    csinc w9, w21, wzr, ne
; CHECK-NOFP-NEXT:    ldr x10, [x10, :got_lo12:var64]
; CHECK-NOFP-NEXT:    cmp w9, #0
; CHECK-NOFP-NEXT:    mov w9, #9 // =0x9
; CHECK-NOFP-NEXT:    ldp x20, x19, [sp, #32] // 16-byte Folded Reload
; CHECK-NOFP-NEXT:    csel x8, x9, x8, ne
; CHECK-NOFP-NEXT:    ldp x22, x21, [sp, #16] // 16-byte Folded Reload
; CHECK-NOFP-NEXT:    str x8, [x10]
; CHECK-NOFP-NEXT:    ldp x30, x23, [sp], #48 // 16-byte Folded Reload
; CHECK-NOFP-NEXT:    ret

  %tst1 = fcmp one float %lhs32, %rhs32
  %val1 = select i1 %tst1, i32 42, i32 52
  store i32 %val1, ptr @var32


  %tst2 = fcmp ueq double %lhs64, %rhs64
  %val2 = select i1 %tst2, i64 9, i64 15
  store i64 %val2, ptr @var64

  ret void
}


define void @test_csinc(i32 %lhs32, i32 %rhs32, i64 %lhs64) minsize {
; CHECK-LABEL: test_csinc:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-NEXT:    cmp w0, w1
; CHECK-NEXT:    csinc w8, w0, w1, ls
; CHECK-NEXT:    adrp x9, :got:var32
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var32]
; CHECK-NEXT:    str w8, [x9]
; CHECK-NEXT:    add w8, w1, #42
; CHECK-NEXT:    cmp w0, w8
; CHECK-NEXT:    csinc w8, w0, w1, le
; CHECK-NEXT:    str w8, [x9]
; CHECK-NEXT:    sxtw x8, w1
; CHECK-NEXT:    cmp x2, w1, sxtw
; CHECK-NEXT:    adrp x9, :got:var64
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var64]
; CHECK-NEXT:    csinc x8, x2, x8, ls
; CHECK-NEXT:    str x8, [x9]
; CHECK-NEXT:    mov w8, w1
; CHECK-NEXT:    cmp x2, w1, uxtw
; CHECK-NEXT:    csinc x8, x2, x8, le
; CHECK-NEXT:    str x8, [x9]
; CHECK-NEXT:    ret
;
; CHECK-NOFP-LABEL: test_csinc:
; CHECK-NOFP:       // %bb.0:
; CHECK-NOFP-NEXT:    adrp x8, :got:var32
; CHECK-NOFP-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-NOFP-NEXT:    cmp w0, w1
; CHECK-NOFP-NEXT:    add w9, w1, #42
; CHECK-NOFP-NEXT:    ldr x8, [x8, :got_lo12:var32]
; CHECK-NOFP-NEXT:    csinc w10, w0, w1, ls
; CHECK-NOFP-NEXT:    cmp w0, w9
; CHECK-NOFP-NEXT:    sxtw x9, w1
; CHECK-NOFP-NEXT:    str w10, [x8]
; CHECK-NOFP-NEXT:    csinc w10, w0, w1, le
; CHECK-NOFP-NEXT:    cmp x2, w1, sxtw
; CHECK-NOFP-NEXT:    str w10, [x8]
; CHECK-NOFP-NEXT:    adrp x8, :got:var64
; CHECK-NOFP-NEXT:    csinc x9, x2, x9, ls
; CHECK-NOFP-NEXT:    ldr x8, [x8, :got_lo12:var64]
; CHECK-NOFP-NEXT:    mov w10, w1
; CHECK-NOFP-NEXT:    cmp x2, w1, uxtw
; CHECK-NOFP-NEXT:    str x9, [x8]
; CHECK-NOFP-NEXT:    csinc x9, x2, x10, le
; CHECK-NOFP-NEXT:    str x9, [x8]
; CHECK-NOFP-NEXT:    ret

; Note that commuting rhs and lhs in the select changes ugt to ule (i.e. hi to ls).
  %tst1 = icmp ugt i32 %lhs32, %rhs32
  %inc1 = add i32 %rhs32, 1
  %val1 = select i1 %tst1, i32 %inc1, i32 %lhs32
  store volatile i32 %val1, ptr @var32

  %rhs2 = add i32 %rhs32, 42
  %tst2 = icmp sle i32 %lhs32, %rhs2
  %inc2 = add i32 %rhs32, 1
  %val2 = select i1 %tst2, i32 %lhs32, i32 %inc2
  store volatile i32 %val2, ptr @var32

; Note that commuting rhs and lhs in the select changes ugt to ule (i.e. hi to ls).
  %rhs3 = sext i32 %rhs32 to i64
  %tst3 = icmp ugt i64 %lhs64, %rhs3
  %inc3 = add i64 %rhs3, 1
  %val3 = select i1 %tst3, i64 %inc3, i64 %lhs64
  store volatile i64 %val3, ptr @var64

  %rhs4 = zext i32 %rhs32 to i64
  %tst4 = icmp sle i64 %lhs64, %rhs4
  %inc4 = add i64 %rhs4, 1
  %val4 = select i1 %tst4, i64 %lhs64, i64 %inc4
  store volatile i64 %val4, ptr @var64

  ret void
}

define void @test_csinv(i32 %lhs32, i32 %rhs32, i64 %lhs64) minsize {
; CHECK-LABEL: test_csinv:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-NEXT:    cmp w0, w1
; CHECK-NEXT:    csinv w8, w0, w1, ls
; CHECK-NEXT:    adrp x9, :got:var32
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var32]
; CHECK-NEXT:    str w8, [x9]
; CHECK-NEXT:    add w8, w1, #42
; CHECK-NEXT:    cmp w0, w8
; CHECK-NEXT:    csinv w8, w0, w1, le
; CHECK-NEXT:    str w8, [x9]
; CHECK-NEXT:    sxtw x8, w1
; CHECK-NEXT:    cmp x2, w1, sxtw
; CHECK-NEXT:    adrp x9, :got:var64
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var64]
; CHECK-NEXT:    csinv x8, x2, x8, ls
; CHECK-NEXT:    str x8, [x9]
; CHECK-NEXT:    mov w8, w1
; CHECK-NEXT:    cmp x2, w1, uxtw
; CHECK-NEXT:    csinv x8, x2, x8, le
; CHECK-NEXT:    str x8, [x9]
; CHECK-NEXT:    ret
;
; CHECK-NOFP-LABEL: test_csinv:
; CHECK-NOFP:       // %bb.0:
; CHECK-NOFP-NEXT:    adrp x8, :got:var32
; CHECK-NOFP-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-NOFP-NEXT:    cmp w0, w1
; CHECK-NOFP-NEXT:    add w9, w1, #42
; CHECK-NOFP-NEXT:    ldr x8, [x8, :got_lo12:var32]
; CHECK-NOFP-NEXT:    csinv w10, w0, w1, ls
; CHECK-NOFP-NEXT:    cmp w0, w9
; CHECK-NOFP-NEXT:    sxtw x9, w1
; CHECK-NOFP-NEXT:    str w10, [x8]
; CHECK-NOFP-NEXT:    csinv w10, w0, w1, le
; CHECK-NOFP-NEXT:    cmp x2, w1, sxtw
; CHECK-NOFP-NEXT:    str w10, [x8]
; CHECK-NOFP-NEXT:    adrp x8, :got:var64
; CHECK-NOFP-NEXT:    csinv x9, x2, x9, ls
; CHECK-NOFP-NEXT:    ldr x8, [x8, :got_lo12:var64]
; CHECK-NOFP-NEXT:    mov w10, w1
; CHECK-NOFP-NEXT:    cmp x2, w1, uxtw
; CHECK-NOFP-NEXT:    str x9, [x8]
; CHECK-NOFP-NEXT:    csinv x9, x2, x10, le
; CHECK-NOFP-NEXT:    str x9, [x8]
; CHECK-NOFP-NEXT:    ret

; Note that commuting rhs and lhs in the select changes ugt to ule (i.e. hi to ls).
  %tst1 = icmp ugt i32 %lhs32, %rhs32
  %inc1 = xor i32 -1, %rhs32
  %val1 = select i1 %tst1, i32 %inc1, i32 %lhs32
  store volatile i32 %val1, ptr @var32

  %rhs2 = add i32 %rhs32, 42
  %tst2 = icmp sle i32 %lhs32, %rhs2
  %inc2 = xor i32 -1, %rhs32
  %val2 = select i1 %tst2, i32 %lhs32, i32 %inc2
  store volatile i32 %val2, ptr @var32

; Note that commuting rhs and lhs in the select changes ugt to ule (i.e. hi to ls).
  %rhs3 = sext i32 %rhs32 to i64
  %tst3 = icmp ugt i64 %lhs64, %rhs3
  %inc3 = xor i64 -1, %rhs3
  %val3 = select i1 %tst3, i64 %inc3, i64 %lhs64
  store volatile i64 %val3, ptr @var64

  %rhs4 = zext i32 %rhs32 to i64
  %tst4 = icmp sle i64 %lhs64, %rhs4
  %inc4 = xor i64 -1, %rhs4
  %val4 = select i1 %tst4, i64 %lhs64, i64 %inc4
  store volatile i64 %val4, ptr @var64

  ret void
}

define void @test_csinv0(i32 %lhs32, i32 %rhs32, i64 %lhs64, i64 %rhs64) minsize {
; CHECK-LABEL: test_csinv0:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmp w0, w1
; CHECK-NEXT:    csetm w8, ls
; CHECK-NEXT:    adrp x9, :got:var32
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var32]
; CHECK-NEXT:    str w8, [x9]
; CHECK-NEXT:    add w8, w1, #42
; CHECK-NEXT:    cmp w0, w8
; CHECK-NEXT:    csinv w8, w8, wzr, gt
; CHECK-NEXT:    str w8, [x9]
; CHECK-NEXT:    mov w8, #19 // =0x13
; CHECK-NEXT:    mul x8, x3, x8
; CHECK-NEXT:    cmp x2, x8
; CHECK-NEXT:    csinv x8, x8, xzr, hi
; CHECK-NEXT:    adrp x9, :got:var64
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var64]
; CHECK-NEXT:    str x8, [x9]
; CHECK-NEXT:    ret
;
; CHECK-NOFP-LABEL: test_csinv0:
; CHECK-NOFP:       // %bb.0:
; CHECK-NOFP-NEXT:    mov w8, #19 // =0x13
; CHECK-NOFP-NEXT:    adrp x9, :got:var32
; CHECK-NOFP-NEXT:    cmp w0, w1
; CHECK-NOFP-NEXT:    mul x8, x3, x8
; CHECK-NOFP-NEXT:    ldr x9, [x9, :got_lo12:var32]
; CHECK-NOFP-NEXT:    add w10, w1, #42
; CHECK-NOFP-NEXT:    csetm w11, ls
; CHECK-NOFP-NEXT:    cmp w0, w10
; CHECK-NOFP-NEXT:    str w11, [x9]
; CHECK-NOFP-NEXT:    adrp x11, :got:var64
; CHECK-NOFP-NEXT:    csinv w10, w10, wzr, gt
; CHECK-NOFP-NEXT:    ldr x11, [x11, :got_lo12:var64]
; CHECK-NOFP-NEXT:    str w10, [x9]
; CHECK-NOFP-NEXT:    cmp x2, x8
; CHECK-NOFP-NEXT:    csinv x8, x8, xzr, hi
; CHECK-NOFP-NEXT:    str x8, [x11]
; CHECK-NOFP-NEXT:    ret

  %tst1 = icmp ugt i32 %lhs32, %rhs32
  %val1 = select i1 %tst1, i32 0, i32 -1
  store volatile i32 %val1, ptr @var32

  %rhs2 = add i32 %rhs32, 42
  %tst2 = icmp sle i32 %lhs32, %rhs2
  %val2 = select i1 %tst2, i32 -1, i32 %rhs2
  store volatile i32 %val2, ptr @var32

; Note that commuting rhs and lhs in the select changes ugt to ule (i.e. hi to ls).
  %rhs3 = mul i64 %rhs64, 19
  %tst3 = icmp ugt i64 %lhs64, %rhs3
  %val3 = select i1 %tst3, i64 %rhs3, i64 -1
  store volatile i64 %val3, ptr @var64

  ret void
}

define void @test_csneg(i32 %lhs32, i32 %rhs32, i64 %lhs64) minsize {
; CHECK-LABEL: test_csneg:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-NEXT:    cmp w0, w1
; CHECK-NEXT:    csneg w8, w0, w1, ls
; CHECK-NEXT:    adrp x9, :got:var32
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var32]
; CHECK-NEXT:    str w8, [x9]
; CHECK-NEXT:    add w8, w1, #42
; CHECK-NEXT:    cmp w0, w8
; CHECK-NEXT:    csneg w8, w0, w1, le
; CHECK-NEXT:    str w8, [x9]
; CHECK-NEXT:    sxtw x8, w1
; CHECK-NEXT:    cmp x2, w1, sxtw
; CHECK-NEXT:    adrp x9, :got:var64
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var64]
; CHECK-NEXT:    csneg x8, x2, x8, ls
; CHECK-NEXT:    str x8, [x9]
; CHECK-NEXT:    mov w8, w1
; CHECK-NEXT:    cmp x2, w1, uxtw
; CHECK-NEXT:    csneg x8, x2, x8, le
; CHECK-NEXT:    str x8, [x9]
; CHECK-NEXT:    ret
;
; CHECK-NOFP-LABEL: test_csneg:
; CHECK-NOFP:       // %bb.0:
; CHECK-NOFP-NEXT:    adrp x8, :got:var32
; CHECK-NOFP-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-NOFP-NEXT:    cmp w0, w1
; CHECK-NOFP-NEXT:    add w9, w1, #42
; CHECK-NOFP-NEXT:    ldr x8, [x8, :got_lo12:var32]
; CHECK-NOFP-NEXT:    csneg w10, w0, w1, ls
; CHECK-NOFP-NEXT:    cmp w0, w9
; CHECK-NOFP-NEXT:    sxtw x9, w1
; CHECK-NOFP-NEXT:    str w10, [x8]
; CHECK-NOFP-NEXT:    csneg w10, w0, w1, le
; CHECK-NOFP-NEXT:    cmp x2, w1, sxtw
; CHECK-NOFP-NEXT:    str w10, [x8]
; CHECK-NOFP-NEXT:    adrp x8, :got:var64
; CHECK-NOFP-NEXT:    csneg x9, x2, x9, ls
; CHECK-NOFP-NEXT:    ldr x8, [x8, :got_lo12:var64]
; CHECK-NOFP-NEXT:    mov w10, w1
; CHECK-NOFP-NEXT:    cmp x2, w1, uxtw
; CHECK-NOFP-NEXT:    str x9, [x8]
; CHECK-NOFP-NEXT:    csneg x9, x2, x10, le
; CHECK-NOFP-NEXT:    str x9, [x8]
; CHECK-NOFP-NEXT:    ret

; Note that commuting rhs and lhs in the select changes ugt to ule (i.e. hi to ls).
  %tst1 = icmp ugt i32 %lhs32, %rhs32
  %inc1 = sub i32 0, %rhs32
  %val1 = select i1 %tst1, i32 %inc1, i32 %lhs32
  store volatile i32 %val1, ptr @var32

  %rhs2 = add i32 %rhs32, 42
  %tst2 = icmp sle i32 %lhs32, %rhs2
  %inc2 = sub i32 0, %rhs32
  %val2 = select i1 %tst2, i32 %lhs32, i32 %inc2
  store volatile i32 %val2, ptr @var32

; Note that commuting rhs and lhs in the select changes ugt to ule (i.e. hi to ls).
  %rhs3 = sext i32 %rhs32 to i64
  %tst3 = icmp ugt i64 %lhs64, %rhs3
  %inc3 = sub i64 0, %rhs3
  %val3 = select i1 %tst3, i64 %inc3, i64 %lhs64
  store volatile i64 %val3, ptr @var64

  %rhs4 = zext i32 %rhs32 to i64
  %tst4 = icmp sle i64 %lhs64, %rhs4
  %inc4 = sub i64 0, %rhs4
  %val4 = select i1 %tst4, i64 %lhs64, i64 %inc4
  store volatile i64 %val4, ptr @var64

  ret void
}

define void @test_cset(i32 %lhs, i32 %rhs, i64 %lhs64) {
; CHECK-LABEL: test_cset:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmp w0, w1
; CHECK-NEXT:    cset w8, eq
; CHECK-NEXT:    adrp x9, :got:var32
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var32]
; CHECK-NEXT:    str w8, [x9]
; CHECK-NEXT:    cmp x2, w1, sxtw
; CHECK-NEXT:    cset w8, ls
; CHECK-NEXT:    adrp x9, :got:var64
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var64]
; CHECK-NEXT:    str x8, [x9]
; CHECK-NEXT:    ret
;
; CHECK-NOFP-LABEL: test_cset:
; CHECK-NOFP:       // %bb.0:
; CHECK-NOFP-NEXT:    adrp x8, :got:var32
; CHECK-NOFP-NEXT:    cmp w0, w1
; CHECK-NOFP-NEXT:    adrp x10, :got:var64
; CHECK-NOFP-NEXT:    ldr x8, [x8, :got_lo12:var32]
; CHECK-NOFP-NEXT:    cset w9, eq
; CHECK-NOFP-NEXT:    cmp x2, w1, sxtw
; CHECK-NOFP-NEXT:    ldr x10, [x10, :got_lo12:var64]
; CHECK-NOFP-NEXT:    str w9, [x8]
; CHECK-NOFP-NEXT:    cset w8, ls
; CHECK-NOFP-NEXT:    str x8, [x10]
; CHECK-NOFP-NEXT:    ret

; N.b. code is not optimal here (32-bit csinc would be better) but
; incoming DAG is too complex
  %tst1 = icmp eq i32 %lhs, %rhs
  %val1 = zext i1 %tst1 to i32
  store i32 %val1, ptr @var32

  %rhs64 = sext i32 %rhs to i64
  %tst2 = icmp ule i64 %lhs64, %rhs64
  %val2 = zext i1 %tst2 to i64
  store i64 %val2, ptr @var64

  ret void
}

define void @test_csetm(i32 %lhs, i32 %rhs, i64 %lhs64) {
; CHECK-LABEL: test_csetm:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmp w0, w1
; CHECK-NEXT:    csetm w8, eq
; CHECK-NEXT:    adrp x9, :got:var32
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var32]
; CHECK-NEXT:    str w8, [x9]
; CHECK-NEXT:    cmp x2, w1, sxtw
; CHECK-NEXT:    csetm x8, ls
; CHECK-NEXT:    adrp x9, :got:var64
; CHECK-NEXT:    ldr x9, [x9, :got_lo12:var64]
; CHECK-NEXT:    str x8, [x9]
; CHECK-NEXT:    ret
;
; CHECK-NOFP-LABEL: test_csetm:
; CHECK-NOFP:       // %bb.0:
; CHECK-NOFP-NEXT:    adrp x8, :got:var32
; CHECK-NOFP-NEXT:    cmp w0, w1
; CHECK-NOFP-NEXT:    adrp x10, :got:var64
; CHECK-NOFP-NEXT:    ldr x8, [x8, :got_lo12:var32]
; CHECK-NOFP-NEXT:    csetm w9, eq
; CHECK-NOFP-NEXT:    cmp x2, w1, sxtw
; CHECK-NOFP-NEXT:    ldr x10, [x10, :got_lo12:var64]
; CHECK-NOFP-NEXT:    str w9, [x8]
; CHECK-NOFP-NEXT:    csetm x8, ls
; CHECK-NOFP-NEXT:    str x8, [x10]
; CHECK-NOFP-NEXT:    ret

  %tst1 = icmp eq i32 %lhs, %rhs
  %val1 = sext i1 %tst1 to i32
  store i32 %val1, ptr @var32

  %rhs64 = sext i32 %rhs to i64
  %tst2 = icmp ule i64 %lhs64, %rhs64
  %val2 = sext i1 %tst2 to i64
  store i64 %val2, ptr @var64

  ret void
}

define <1 x i1> @test_wide_comparison(i32 %in) {
; CHECK-LABEL: test_wide_comparison:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmp w0, #1234
; CHECK-NEXT:    cset w0, gt
; CHECK-NEXT:    ret
;
; CHECK-NOFP-LABEL: test_wide_comparison:
; CHECK-NOFP:       // %bb.0:
; CHECK-NOFP-NEXT:    cmp w0, #1234
; CHECK-NOFP-NEXT:    cset w0, gt
; CHECK-NOFP-NEXT:    ret

  %tmp = icmp sgt i32 %in, 1234
  %res = select i1 %tmp, <1 x i1> <i1 1>, <1 x i1> zeroinitializer
  ret <1 x i1> %res
}

define i32 @test_select_undef() {
; CHECK-LABEL: test_select_undef:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w0, #0 // =0x0
; CHECK-NEXT:    ret
;
; CHECK-NOFP-LABEL: test_select_undef:
; CHECK-NOFP:       // %bb.0:
; CHECK-NOFP-NEXT:    mov w0, wzr
; CHECK-NOFP-NEXT:    ret
  %res = select i1 undef, i32 0, i32 42
  ret i32 %res
}
