# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=aarch64 -mattr=+sve -run-pass=aarch64-expand-pseudo -verify-machineinstrs %s -o - | FileCheck %s

# Test the expansion of constructive binary operations into their
# destructive counterparts.


# BIC_ZPmZ_B

---
name:            test_bic_zpzz_unique_regs
body:             |
  bb.0:
    ; CHECK-LABEL: name: test_bic_zpzz_unique_regs
    ; CHECK: BUNDLE implicit-def $z2, implicit-def $q2, implicit-def $d2, implicit-def $s2, implicit-def $h2, implicit-def $b2, implicit-def $b2_hi, implicit-def $h2_hi, implicit-def $s2_hi, implicit-def $d2_hi, implicit-def $q2_hi, implicit killed $p0, implicit $z0, implicit killed $z1 {
    ; CHECK-NEXT:   $z2 = MOVPRFX_ZPzZ_B $p0, $z0
    ; CHECK-NEXT:   $z2 = BIC_ZPmZ_B killed $p0, internal killed $z2, killed $z1
    ; CHECK-NEXT: }
    ; CHECK-NEXT: RET undef $lr, implicit killed $z2
    $z2 = BIC_ZPZZ_B_ZERO killed $p0, killed $z0, killed $z1
    RET_ReallyLR implicit killed $z2
...

---
name:            test_bic_zpzz_not_unique_regs
body:             |
  bb.0:
    ; CHECK-LABEL: name: test_bic_zpzz_not_unique_regs
    ; CHECK: BUNDLE implicit-def $z2, implicit-def $q2, implicit-def $d2, implicit-def $s2, implicit-def $h2, implicit-def $b2, implicit-def $b2_hi, implicit-def $h2_hi, implicit-def $s2_hi, implicit-def $d2_hi, implicit-def $q2_hi, implicit killed $p0, implicit $z0 {
    ; CHECK-NEXT:   $z2 = MOVPRFX_ZPzZ_B $p0, $z0
    ; CHECK-NEXT:   $z2 = LSL_ZPmI_B killed $p0, internal $z2, 0
    ; CHECK-NEXT:   $z2 = BIC_ZPmZ_B killed $p0, internal killed $z2, internal killed $z2
    ; CHECK-NEXT: }
    ; CHECK-NEXT: RET undef $lr, implicit killed $z2
    $z2 = BIC_ZPZZ_B_ZERO killed $p0, killed $z0, killed $z2
    RET_ReallyLR implicit killed $z2
...

---
name:            test_bic_zpzz_implicit_ops
body:             |
  bb.0:
    ; CHECK-LABEL: name: test_bic_zpzz_implicit_ops
    ; CHECK: BUNDLE implicit-def $z2, implicit-def $q2, implicit-def $d2, implicit-def $s2, implicit-def $h2, implicit-def $b2, implicit-def $b2_hi, implicit-def $h2_hi, implicit-def $s2_hi, implicit-def $d2_hi, implicit-def $q2_hi, implicit killed $p0, implicit $z0, implicit killed $q0, implicit killed $q1, implicit killed $z1 {
    ; CHECK-NEXT:   $z2 = MOVPRFX_ZPzZ_B $p0, $z0, implicit killed $q0, implicit killed $q1
    ; CHECK-NEXT:   $z2 = BIC_ZPmZ_B killed $p0, internal killed $z2, killed $z1, implicit-def $q2
    ; CHECK-NEXT: }
    ; CHECK-NEXT: RET undef $lr, implicit killed $z2, implicit killed $q2
    $z2 = BIC_ZPZZ_B_ZERO killed $p0, killed $z0, killed $z1, implicit-def $q2, implicit killed $q0, implicit killed $q1
    RET_ReallyLR implicit killed $z2, implicit killed $q2
...

---
name:            test_bic_zpzz_undef
body:             |
  bb.0:
    ; CHECK-LABEL: name: test_bic_zpzz_undef
    ; CHECK: BUNDLE implicit-def $z2, implicit-def $q2, implicit-def $d2, implicit-def $s2, implicit-def $h2, implicit-def $b2, implicit-def $b2_hi, implicit-def $h2_hi, implicit-def $s2_hi, implicit-def $d2_hi, implicit-def $q2_hi, implicit $p0, implicit undef $z0, implicit undef $z1 {
    ; CHECK-NEXT:   $z2 = MOVPRFX_ZPzZ_B $p0, undef $z0
    ; CHECK-NEXT:   $z2 = BIC_ZPmZ_B undef $p0, internal killed $z2, undef $z1
    ; CHECK-NEXT: }
    ; CHECK-NEXT: RET undef $lr, implicit killed $z2
    $z2 = BIC_ZPZZ_B_ZERO undef $p0, undef $z0, undef $z1
    RET_ReallyLR implicit killed $z2
...

# ADD_ZPmZ_B

---
name:            test_add_zpzz_unique_regs
body:             |
  bb.0:
    ; CHECK-LABEL: name: test_add_zpzz_unique_regs
    ; CHECK: BUNDLE implicit-def $z2, implicit-def $q2, implicit-def $d2, implicit-def $s2, implicit-def $h2, implicit-def $b2, implicit-def $b2_hi, implicit-def $h2_hi, implicit-def $s2_hi, implicit-def $d2_hi, implicit-def $q2_hi, implicit killed $p0, implicit $z0, implicit killed $z1 {
    ; CHECK-NEXT:   $z2 = MOVPRFX_ZPzZ_B $p0, $z0
    ; CHECK-NEXT:   $z2 = ADD_ZPmZ_B killed $p0, internal killed $z2, killed $z1
    ; CHECK-NEXT: }
    ; CHECK-NEXT: RET undef $lr, implicit killed $z2
    $z2 = ADD_ZPZZ_B_ZERO killed $p0, killed $z0, killed $z1
    RET_ReallyLR implicit killed $z2
...

---
name:            test_add_zpzz_not_unique_regs
body:             |
  bb.0:
    ; CHECK-LABEL: name: test_add_zpzz_not_unique_regs
    ; CHECK: BUNDLE implicit-def $z2, implicit-def $q2, implicit-def $d2, implicit-def $s2, implicit-def $h2, implicit-def $b2, implicit-def $b2_hi, implicit-def $h2_hi, implicit-def $s2_hi, implicit-def $d2_hi, implicit-def $q2_hi, implicit killed $p0, implicit $z2, implicit killed $z0 {
    ; CHECK-NEXT:   $z2 = MOVPRFX_ZPzZ_B $p0, $z2
    ; CHECK-NEXT:   $z2 = ADD_ZPmZ_B killed $p0, internal killed $z2, killed $z0
    ; CHECK-NEXT: }
    ; CHECK-NEXT: RET undef $lr, implicit killed $z2
    $z2 = ADD_ZPZZ_B_ZERO killed $p0, killed $z0, killed $z2
    RET_ReallyLR implicit killed $z2
...
