# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sme2 -run-pass=aarch64-expand-pseudo -verify-machineinstrs %s -o - | FileCheck %s

# Post-RA tests for FORM_TRANSPOSED_REG_TUPLE_*_PSEUDO expansion.
#
# This test covers unlikely cases that ideally we'll never encounter in
# practice, but still need to handle for correctness.
#
# Ideally, we should make it impossible for the register allocator to pick cases
# with costly expansions (i.e., those that require swaps).


# Naive copy lowering would clobber $z19 before $z20 is formed.
---
name:            form_transposed_reg_tuple_x2_overlap
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $z17, $z19
    ; CHECK-LABEL: name: form_transposed_reg_tuple_x2_overlap
    ; CHECK: liveins: $z17, $z19
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $z20 = ORR_ZZZ $z19, $z19
    ; CHECK-NEXT: $z19 = ORR_ZZZ $z17, $z17
    ; CHECK-NEXT: RET undef $lr, implicit killed $z19, implicit killed $z20
    $z19_z20 = FORM_TRANSPOSED_REG_TUPLE_X2_PSEUDO $z17, $z19
    RET_ReallyLR implicit killed $z19, implicit killed $z20
...

# Pure X2 permutation: this must use the fallback swap sequence.
---
name:            form_transposed_reg_tuple_x2_swap
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $z19, $z20
    ; CHECK-LABEL: name: form_transposed_reg_tuple_x2_swap
    ; CHECK: liveins: $z19, $z20
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z20
    ; CHECK-NEXT: $z20 = EOR_ZZZ $z20, $z19
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z20
    ; CHECK-NEXT: RET undef $lr, implicit killed $z19, implicit killed $z20
    $z19_z20 = FORM_TRANSPOSED_REG_TUPLE_X2_PSEUDO $z20, $z19
    RET_ReallyLR implicit killed $z19, implicit killed $z20
...
# Pure X2 permutation: this must use the fallback swap sequence (z31_z0).
---
name:            form_transposed_reg_tuple_x2_swap_reg_wrap
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $z0, $z31
    ; CHECK-LABEL: name: form_transposed_reg_tuple_x2_swap_reg_wrap
    ; CHECK: liveins: $z0, $z31
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $z31 = EOR_ZZZ $z31, $z0
    ; CHECK-NEXT: $z0 = EOR_ZZZ $z0, $z31
    ; CHECK-NEXT: $z31 = EOR_ZZZ $z31, $z0
    ; CHECK-NEXT: RET undef $lr, implicit killed $z31, implicit killed $z0
    $z31_z0 = FORM_TRANSPOSED_REG_TUPLE_X2_PSEUDO $z0, $z31
    RET_ReallyLR implicit killed $z31, implicit killed $z0
...
# Identity tuple: the pseudo should disappear without emitting copies.
---
name:            form_transposed_reg_tuple_x2_identity
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $z19, $z20
    ; CHECK-LABEL: name: form_transposed_reg_tuple_x2_identity
    ; CHECK: liveins: $z19, $z20
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: RET undef $lr, implicit killed $z19, implicit killed $z20
    $z19_z20 = FORM_TRANSPOSED_REG_TUPLE_X2_PSEUDO $z19, $z20
    RET_ReallyLR implicit killed $z19, implicit killed $z20
...

# Duplicate the first tuple source into the second lane.
---
name:            form_transposed_reg_tuple_x2_duplicate_first_source
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $z19
    ; CHECK-LABEL: name: form_transposed_reg_tuple_x2_duplicate_first_source
    ; CHECK: liveins: $z19
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $z20 = ORR_ZZZ $z19, $z19
    ; CHECK-NEXT: RET undef $lr, implicit killed $z19, implicit killed $z20
    $z19_z20 = FORM_TRANSPOSED_REG_TUPLE_X2_PSEUDO $z19, $z19
    RET_ReallyLR implicit killed $z19, implicit killed $z20
...

# Duplicate the second tuple source into the first lane.
---
name:            form_transposed_reg_tuple_x2_duplicate_second_source
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $z20
    ; CHECK-LABEL: name: form_transposed_reg_tuple_x2_duplicate_second_source
    ; CHECK: liveins: $z20
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $z19 = ORR_ZZZ $z20, $z20
    ; CHECK-NEXT: RET undef $lr, implicit killed $z19, implicit killed $z20
    $z19_z20 = FORM_TRANSPOSED_REG_TUPLE_X2_PSEUDO $z20, $z20
    RET_ReallyLR implicit killed $z19, implicit killed $z20
...

# Identity tuple: the pseudo should disappear without emitting copies.
---
name:            form_transposed_reg_tuple_x4_identity
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $z19, $z20, $z21, $z22
    ; CHECK-LABEL: name: form_transposed_reg_tuple_x4_identity
    ; CHECK: liveins: $z19, $z20, $z21, $z22
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: RET undef $lr, implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
    $z19_z20_z21_z22 = FORM_TRANSPOSED_REG_TUPLE_X4_PSEUDO $z19, $z20, $z21, $z22
    RET_ReallyLR implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
...

# Splat one tuple member across the whole X4 tuple.
---
name:            form_transposed_reg_tuple_x4_splat_from_tuple_member
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $z19
    ; CHECK-LABEL: name: form_transposed_reg_tuple_x4_splat_from_tuple_member
    ; CHECK: liveins: $z19
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $z22 = ORR_ZZZ $z19, $z19
    ; CHECK-NEXT: $z21 = ORR_ZZZ $z19, $z19
    ; CHECK-NEXT: $z20 = ORR_ZZZ $z19, $z19
    ; CHECK-NEXT: RET undef $lr, implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
    $z19_z20_z21_z22 = FORM_TRANSPOSED_REG_TUPLE_X4_PSEUDO $z19, $z19, $z19, $z19
    RET_ReallyLR implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
...

# Mixed external source plus tuple-member splat.
---
name:            form_transposed_reg_tuple_x4_external_and_splat
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $z17, $z19
    ; CHECK-LABEL: name: form_transposed_reg_tuple_x4_external_and_splat
    ; CHECK: liveins: $z17, $z19
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $z22 = ORR_ZZZ $z19, $z19
    ; CHECK-NEXT: $z21 = ORR_ZZZ $z19, $z19
    ; CHECK-NEXT: $z20 = ORR_ZZZ $z19, $z19
    ; CHECK-NEXT: $z19 = ORR_ZZZ $z17, $z17
    ; CHECK-NEXT: RET undef $lr, implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
    $z19_z20_z21_z22 = FORM_TRANSPOSED_REG_TUPLE_X4_PSEUDO $z17, $z19, $z19, $z19
    RET_ReallyLR implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
...
# Overlapping X4 tuple with no permutation: copies must be emitted in reverse dependency order.
---
name:            form_transposed_reg_tuple_x4_overlap
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $z17, $z19, $z20, $z21
    ; CHECK-LABEL: name: form_transposed_reg_tuple_x4_overlap
    ; CHECK: liveins: $z17, $z19, $z20, $z21
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $z22 = ORR_ZZZ $z21, $z21
    ; CHECK-NEXT: $z21 = ORR_ZZZ $z20, $z20
    ; CHECK-NEXT: $z20 = ORR_ZZZ $z19, $z19
    ; CHECK-NEXT: $z19 = ORR_ZZZ $z17, $z17
    ; CHECK-NEXT: RET undef $lr, implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
    $z19_z20_z21_z22 = FORM_TRANSPOSED_REG_TUPLE_X4_PSEUDO $z17, $z19, $z20, $z21
    RET_ReallyLR implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
...

# Mixed X4 case: independent copies first, then swap the remaining 2-cycle.
---
name:            form_transposed_reg_tuple_x4_contains_swap
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $z17, $z18, $z19, $z20
    ; CHECK-LABEL: name: form_transposed_reg_tuple_x4_contains_swap
    ; CHECK: liveins: $z17, $z18, $z19, $z20
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $z22 = ORR_ZZZ $z18, $z18
    ; CHECK-NEXT: $z21 = ORR_ZZZ $z17, $z17
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z20
    ; CHECK-NEXT: $z20 = EOR_ZZZ $z20, $z19
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z20
    ; CHECK-NEXT: RET undef $lr, implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
    $z19_z20_z21_z22 = FORM_TRANSPOSED_REG_TUPLE_X4_PSEUDO $z20, $z19, $z17, $z18
    RET_ReallyLR implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
...

# Pure X4 permutation: expand into a sequence of swaps over the cycle.
---
name:            form_transposed_reg_tuple_x4_rotate
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $z19, $z20, $z21, $z22
    ; CHECK-LABEL: name: form_transposed_reg_tuple_x4_rotate
    ; CHECK: liveins: $z19, $z20, $z21, $z22
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z22
    ; CHECK-NEXT: $z22 = EOR_ZZZ $z22, $z19
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z22
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z21
    ; CHECK-NEXT: $z21 = EOR_ZZZ $z21, $z19
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z21
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z20
    ; CHECK-NEXT: $z20 = EOR_ZZZ $z20, $z19
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z20
    ; CHECK-NEXT: RET undef $lr, implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
    $z19_z20_z21_z22 = FORM_TRANSPOSED_REG_TUPLE_X4_PSEUDO $z20, $z21, $z22, $z19
    RET_ReallyLR implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
...

# Non-contiguous remaining 2-cycle after removing an identity and an external copy.
---
name:            form_transposed_reg_tuple_x4_noncontiguous_2cycle
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $z18, $z19, $z20, $z21
    ; CHECK-LABEL: name: form_transposed_reg_tuple_x4_noncontiguous_2cycle
    ; CHECK: liveins: $z18, $z19, $z20, $z21
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $z22 = ORR_ZZZ $z18, $z18
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z21
    ; CHECK-NEXT: $z21 = EOR_ZZZ $z21, $z19
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z21
    ; CHECK-NEXT: RET undef $lr, implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
    $z19_z20_z21_z22 = FORM_TRANSPOSED_REG_TUPLE_X4_PSEUDO $z21, $z20, $z19, $z18
    RET_ReallyLR implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
...

# Non-contiguous remaining 3-cycle with one identity tuple member.
---
name:            form_transposed_reg_tuple_x4_noncontiguous_3cycle
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $z19, $z20, $z21, $z22
    ; CHECK-LABEL: name: form_transposed_reg_tuple_x4_noncontiguous_3cycle
    ; CHECK: liveins: $z19, $z20, $z21, $z22
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z21
    ; CHECK-NEXT: $z21 = EOR_ZZZ $z21, $z19
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z21
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z22
    ; CHECK-NEXT: $z22 = EOR_ZZZ $z22, $z19
    ; CHECK-NEXT: $z19 = EOR_ZZZ $z19, $z22
    ; CHECK-NEXT: RET undef $lr, implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
    $z19_z20_z21_z22 = FORM_TRANSPOSED_REG_TUPLE_X4_PSEUDO $z22, $z20, $z19, $z21
    RET_ReallyLR implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
...

# Mixed identity-plus-cycle case where only non-adjacent tuple members must swap.
---
name:            form_transposed_reg_tuple_x4_identity_plus_cycle
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $z19, $z20, $z21, $z22
    ; CHECK-LABEL: name: form_transposed_reg_tuple_x4_identity_plus_cycle
    ; CHECK: liveins: $z19, $z20, $z21, $z22
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $z20 = EOR_ZZZ $z20, $z22
    ; CHECK-NEXT: $z22 = EOR_ZZZ $z22, $z20
    ; CHECK-NEXT: $z20 = EOR_ZZZ $z20, $z22
    ; CHECK-NEXT: RET undef $lr, implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
    $z19_z20_z21_z22 = FORM_TRANSPOSED_REG_TUPLE_X4_PSEUDO $z19, $z22, $z21, $z20
    RET_ReallyLR implicit killed $z19, implicit killed $z20, implicit killed $z21, implicit killed $z22
...
