; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve < %s | FileCheck %s --check-prefixes=CHECK,VL-UNKNOWN
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve -aarch64-sve-vector-bits-min=128 -aarch64-sve-vector-bits-max=128 < %s | FileCheck %s --check-prefixes=CHECK,VL-128
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve -aarch64-sve-vector-bits-min=256 -aarch64-sve-vector-bits-max=256 < %s | FileCheck %s --check-prefixes=CHECK,VL-256
; RUN: llc -mtriple=aarch64_be-linux-gnu -mattr=+sve -aarch64-sve-vector-bits-min=128 -aarch64-sve-vector-bits-max=128 < %s | FileCheck %s --check-prefixes=CHECK,VL-128-BE

define <16 x i8> @sext_v16i1_v16i8(ptr %p) {
; VL-UNKNOWN-LABEL: sext_v16i1_v16i8:
; VL-UNKNOWN:       // %bb.0:
; VL-UNKNOWN-NEXT:    adrp x8, .LCPI0_0
; VL-UNKNOWN-NEXT:    ldr h1, [x0]
; VL-UNKNOWN-NEXT:    ldr q0, [x8, :lo12:.LCPI0_0]
; VL-UNKNOWN-NEXT:    adrp x8, .LCPI0_1
; VL-UNKNOWN-NEXT:    tbl v0.16b, { v1.16b }, v0.16b
; VL-UNKNOWN-NEXT:    ldr q1, [x8, :lo12:.LCPI0_1]
; VL-UNKNOWN-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-UNKNOWN-NEXT:    ret
;
; VL-128-LABEL: sext_v16i1_v16i8:
; VL-128:       // %bb.0:
; VL-128-NEXT:    adrp x8, .LCPI0_0
; VL-128-NEXT:    ldr h1, [x0]
; VL-128-NEXT:    ldr q0, [x8, :lo12:.LCPI0_0]
; VL-128-NEXT:    adrp x8, .LCPI0_1
; VL-128-NEXT:    tbl v0.16b, { v1.16b }, v0.16b
; VL-128-NEXT:    ldr q1, [x8, :lo12:.LCPI0_1]
; VL-128-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-128-NEXT:    ret
;
; VL-256-LABEL: sext_v16i1_v16i8:
; VL-256:       // %bb.0:
; VL-256-NEXT:    adrp x8, .LCPI0_0
; VL-256-NEXT:    ldr h1, [x0]
; VL-256-NEXT:    ldr q0, [x8, :lo12:.LCPI0_0]
; VL-256-NEXT:    adrp x8, .LCPI0_1
; VL-256-NEXT:    tbl v0.16b, { v1.16b }, v0.16b
; VL-256-NEXT:    ldr q1, [x8, :lo12:.LCPI0_1]
; VL-256-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-256-NEXT:    ret
;
; VL-128-BE-LABEL: sext_v16i1_v16i8:
; VL-128-BE:       // %bb.0:
; VL-128-BE-NEXT:    ldr h0, [x0]
; VL-128-BE-NEXT:    adrp x8, .LCPI0_0
; VL-128-BE-NEXT:    add x8, x8, :lo12:.LCPI0_0
; VL-128-BE-NEXT:    ld1 { v1.16b }, [x8]
; VL-128-BE-NEXT:    adrp x8, .LCPI0_1
; VL-128-BE-NEXT:    add x8, x8, :lo12:.LCPI0_1
; VL-128-BE-NEXT:    rev16 v0.16b, v0.16b
; VL-128-BE-NEXT:    tbl v0.16b, { v0.16b }, v1.16b
; VL-128-BE-NEXT:    ld1 { v1.16b }, [x8]
; VL-128-BE-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-128-BE-NEXT:    rev64 v0.16b, v0.16b
; VL-128-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; VL-128-BE-NEXT:    ret
    %l = load <16 x i1>, ptr %p, align 4
    %e = sext <16 x i1> %l to <16 x i8>
    ret <16 x i8> %e
}

define <16 x i8> @zext_v16i1_v16i8(ptr %p) {
; VL-UNKNOWN-LABEL: zext_v16i1_v16i8:
; VL-UNKNOWN:       // %bb.0:
; VL-UNKNOWN-NEXT:    adrp x8, .LCPI1_0
; VL-UNKNOWN-NEXT:    ldr h1, [x0]
; VL-UNKNOWN-NEXT:    ldr q0, [x8, :lo12:.LCPI1_0]
; VL-UNKNOWN-NEXT:    adrp x8, .LCPI1_1
; VL-UNKNOWN-NEXT:    tbl v0.16b, { v1.16b }, v0.16b
; VL-UNKNOWN-NEXT:    ldr q1, [x8, :lo12:.LCPI1_1]
; VL-UNKNOWN-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-UNKNOWN-NEXT:    ushr v0.16b, v0.16b, #7
; VL-UNKNOWN-NEXT:    ret
;
; VL-128-LABEL: zext_v16i1_v16i8:
; VL-128:       // %bb.0:
; VL-128-NEXT:    adrp x8, .LCPI1_0
; VL-128-NEXT:    ldr h1, [x0]
; VL-128-NEXT:    ldr q0, [x8, :lo12:.LCPI1_0]
; VL-128-NEXT:    adrp x8, .LCPI1_1
; VL-128-NEXT:    tbl v0.16b, { v1.16b }, v0.16b
; VL-128-NEXT:    ldr q1, [x8, :lo12:.LCPI1_1]
; VL-128-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-128-NEXT:    ushr v0.16b, v0.16b, #7
; VL-128-NEXT:    ret
;
; VL-256-LABEL: zext_v16i1_v16i8:
; VL-256:       // %bb.0:
; VL-256-NEXT:    adrp x8, .LCPI1_0
; VL-256-NEXT:    ldr h1, [x0]
; VL-256-NEXT:    ldr q0, [x8, :lo12:.LCPI1_0]
; VL-256-NEXT:    adrp x8, .LCPI1_1
; VL-256-NEXT:    tbl v0.16b, { v1.16b }, v0.16b
; VL-256-NEXT:    ldr q1, [x8, :lo12:.LCPI1_1]
; VL-256-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-256-NEXT:    ushr v0.16b, v0.16b, #7
; VL-256-NEXT:    ret
;
; VL-128-BE-LABEL: zext_v16i1_v16i8:
; VL-128-BE:       // %bb.0:
; VL-128-BE-NEXT:    ldr h0, [x0]
; VL-128-BE-NEXT:    adrp x8, .LCPI1_0
; VL-128-BE-NEXT:    add x8, x8, :lo12:.LCPI1_0
; VL-128-BE-NEXT:    ld1 { v1.16b }, [x8]
; VL-128-BE-NEXT:    adrp x8, .LCPI1_1
; VL-128-BE-NEXT:    add x8, x8, :lo12:.LCPI1_1
; VL-128-BE-NEXT:    rev16 v0.16b, v0.16b
; VL-128-BE-NEXT:    tbl v0.16b, { v0.16b }, v1.16b
; VL-128-BE-NEXT:    ld1 { v1.16b }, [x8]
; VL-128-BE-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-128-BE-NEXT:    ushr v0.16b, v0.16b, #7
; VL-128-BE-NEXT:    rev64 v0.16b, v0.16b
; VL-128-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; VL-128-BE-NEXT:    ret
    %l = load <16 x i1>, ptr %p, align 4
    %e = zext <16 x i1> %l to <16 x i8>
    ret <16 x i8> %e
}

define <16 x i16> @sext_v16i1_v16i16(ptr %p) {
; VL-UNKNOWN-LABEL: sext_v16i1_v16i16:
; VL-UNKNOWN:       // %bb.0:
; VL-UNKNOWN-NEXT:    adrp x8, .LCPI2_0
; VL-UNKNOWN-NEXT:    ld1r { v1.8h }, [x0]
; VL-UNKNOWN-NEXT:    adrp x9, .LCPI2_1
; VL-UNKNOWN-NEXT:    ldr q0, [x8, :lo12:.LCPI2_0]
; VL-UNKNOWN-NEXT:    ldr q2, [x9, :lo12:.LCPI2_1]
; VL-UNKNOWN-NEXT:    cmtst v0.8h, v1.8h, v0.8h
; VL-UNKNOWN-NEXT:    cmtst v1.8h, v1.8h, v2.8h
; VL-UNKNOWN-NEXT:    ret
;
; VL-128-LABEL: sext_v16i1_v16i16:
; VL-128:       // %bb.0:
; VL-128-NEXT:    adrp x8, .LCPI2_0
; VL-128-NEXT:    ld1r { v1.8h }, [x0]
; VL-128-NEXT:    adrp x9, .LCPI2_1
; VL-128-NEXT:    ldr q0, [x8, :lo12:.LCPI2_0]
; VL-128-NEXT:    ldr q2, [x9, :lo12:.LCPI2_1]
; VL-128-NEXT:    cmtst v0.8h, v1.8h, v0.8h
; VL-128-NEXT:    cmtst v1.8h, v1.8h, v2.8h
; VL-128-NEXT:    ret
;
; VL-256-LABEL: sext_v16i1_v16i16:
; VL-256:       // %bb.0:
; VL-256-NEXT:    ptrue p0.h
; VL-256-NEXT:    adrp x8, .LCPI2_0
; VL-256-NEXT:    add x8, x8, :lo12:.LCPI2_0
; VL-256-NEXT:    ldr z1, [x8]
; VL-256-NEXT:    ld1rh { z0.h }, p0/z, [x0]
; VL-256-NEXT:    and z0.d, z0.d, z1.d
; VL-256-NEXT:    cmpne p1.h, p0/z, z0.h, #0
; VL-256-NEXT:    mov z0.h, p1/z, #-1 // =0xffffffffffffffff
; VL-256-NEXT:    movprfx z1, z0
; VL-256-NEXT:    ext z1.b, z1.b, z0.b, #16
; VL-256-NEXT:    // kill: def $q0 killed $q0 killed $z0
; VL-256-NEXT:    // kill: def $q1 killed $q1 killed $z1
; VL-256-NEXT:    ret
;
; VL-128-BE-LABEL: sext_v16i1_v16i16:
; VL-128-BE:       // %bb.0:
; VL-128-BE-NEXT:    adrp x8, .LCPI2_0
; VL-128-BE-NEXT:    add x8, x8, :lo12:.LCPI2_0
; VL-128-BE-NEXT:    ld1r { v1.8h }, [x0]
; VL-128-BE-NEXT:    ld1 { v0.8h }, [x8]
; VL-128-BE-NEXT:    adrp x8, .LCPI2_1
; VL-128-BE-NEXT:    add x8, x8, :lo12:.LCPI2_1
; VL-128-BE-NEXT:    ld1 { v2.8h }, [x8]
; VL-128-BE-NEXT:    cmtst v0.8h, v1.8h, v0.8h
; VL-128-BE-NEXT:    cmtst v1.8h, v1.8h, v2.8h
; VL-128-BE-NEXT:    rev64 v2.8h, v0.8h
; VL-128-BE-NEXT:    rev64 v1.8h, v1.8h
; VL-128-BE-NEXT:    ext v0.16b, v1.16b, v1.16b, #8
; VL-128-BE-NEXT:    ext v1.16b, v2.16b, v2.16b, #8
; VL-128-BE-NEXT:    ret
    %l = load <16 x i1>, ptr %p, align 4
    %e = sext <16 x i1> %l to <16 x i16>
    ret <16 x i16> %e
}

define <16 x i8> @sext_v16i1_strictalign_align1(ptr %p) #0 {
; VL-UNKNOWN-LABEL: sext_v16i1_strictalign_align1:
; VL-UNKNOWN:       // %bb.0:
; VL-UNKNOWN-NEXT:    ldrb w9, [x0, #1]
; VL-UNKNOWN-NEXT:    ldrb w10, [x0]
; VL-UNKNOWN-NEXT:    adrp x8, .LCPI3_0
; VL-UNKNOWN-NEXT:    ldr q0, [x8, :lo12:.LCPI3_0]
; VL-UNKNOWN-NEXT:    adrp x8, .LCPI3_1
; VL-UNKNOWN-NEXT:    orr w9, w10, w9, lsl #8
; VL-UNKNOWN-NEXT:    fmov s1, w9
; VL-UNKNOWN-NEXT:    tbl v0.16b, { v1.16b }, v0.16b
; VL-UNKNOWN-NEXT:    ldr q1, [x8, :lo12:.LCPI3_1]
; VL-UNKNOWN-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-UNKNOWN-NEXT:    ret
;
; VL-128-LABEL: sext_v16i1_strictalign_align1:
; VL-128:       // %bb.0:
; VL-128-NEXT:    ldrb w9, [x0, #1]
; VL-128-NEXT:    ldrb w10, [x0]
; VL-128-NEXT:    adrp x8, .LCPI3_0
; VL-128-NEXT:    ldr q0, [x8, :lo12:.LCPI3_0]
; VL-128-NEXT:    adrp x8, .LCPI3_1
; VL-128-NEXT:    orr w9, w10, w9, lsl #8
; VL-128-NEXT:    fmov s1, w9
; VL-128-NEXT:    tbl v0.16b, { v1.16b }, v0.16b
; VL-128-NEXT:    ldr q1, [x8, :lo12:.LCPI3_1]
; VL-128-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-128-NEXT:    ret
;
; VL-256-LABEL: sext_v16i1_strictalign_align1:
; VL-256:       // %bb.0:
; VL-256-NEXT:    ldrb w9, [x0, #1]
; VL-256-NEXT:    ldrb w10, [x0]
; VL-256-NEXT:    adrp x8, .LCPI3_0
; VL-256-NEXT:    ldr q0, [x8, :lo12:.LCPI3_0]
; VL-256-NEXT:    adrp x8, .LCPI3_1
; VL-256-NEXT:    orr w9, w10, w9, lsl #8
; VL-256-NEXT:    fmov s1, w9
; VL-256-NEXT:    tbl v0.16b, { v1.16b }, v0.16b
; VL-256-NEXT:    ldr q1, [x8, :lo12:.LCPI3_1]
; VL-256-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-256-NEXT:    ret
;
; VL-128-BE-LABEL: sext_v16i1_strictalign_align1:
; VL-128-BE:       // %bb.0:
; VL-128-BE-NEXT:    ldrb w8, [x0]
; VL-128-BE-NEXT:    ldrb w9, [x0, #1]
; VL-128-BE-NEXT:    orr w8, w9, w8, lsl #8
; VL-128-BE-NEXT:    fmov s0, w8
; VL-128-BE-NEXT:    adrp x8, .LCPI3_0
; VL-128-BE-NEXT:    add x8, x8, :lo12:.LCPI3_0
; VL-128-BE-NEXT:    ld1 { v1.16b }, [x8]
; VL-128-BE-NEXT:    adrp x8, .LCPI3_1
; VL-128-BE-NEXT:    add x8, x8, :lo12:.LCPI3_1
; VL-128-BE-NEXT:    rev16 v0.16b, v0.16b
; VL-128-BE-NEXT:    tbl v0.16b, { v0.16b }, v1.16b
; VL-128-BE-NEXT:    ld1 { v1.16b }, [x8]
; VL-128-BE-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-128-BE-NEXT:    rev64 v0.16b, v0.16b
; VL-128-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; VL-128-BE-NEXT:    ret
    %l = load <16 x i1>, ptr %p, align 1
    %e = sext <16 x i1> %l to <16 x i8>
    ret <16 x i8> %e
}

define <16 x i8> @sext_v16i1_strictalign_align2(ptr %p) #0 {
; VL-UNKNOWN-LABEL: sext_v16i1_strictalign_align2:
; VL-UNKNOWN:       // %bb.0:
; VL-UNKNOWN-NEXT:    adrp x8, .LCPI4_0
; VL-UNKNOWN-NEXT:    ldr h1, [x0]
; VL-UNKNOWN-NEXT:    ldr q0, [x8, :lo12:.LCPI4_0]
; VL-UNKNOWN-NEXT:    adrp x8, .LCPI4_1
; VL-UNKNOWN-NEXT:    tbl v0.16b, { v1.16b }, v0.16b
; VL-UNKNOWN-NEXT:    ldr q1, [x8, :lo12:.LCPI4_1]
; VL-UNKNOWN-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-UNKNOWN-NEXT:    ret
;
; VL-128-LABEL: sext_v16i1_strictalign_align2:
; VL-128:       // %bb.0:
; VL-128-NEXT:    adrp x8, .LCPI4_0
; VL-128-NEXT:    ldr h1, [x0]
; VL-128-NEXT:    ldr q0, [x8, :lo12:.LCPI4_0]
; VL-128-NEXT:    adrp x8, .LCPI4_1
; VL-128-NEXT:    tbl v0.16b, { v1.16b }, v0.16b
; VL-128-NEXT:    ldr q1, [x8, :lo12:.LCPI4_1]
; VL-128-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-128-NEXT:    ret
;
; VL-256-LABEL: sext_v16i1_strictalign_align2:
; VL-256:       // %bb.0:
; VL-256-NEXT:    adrp x8, .LCPI4_0
; VL-256-NEXT:    ldr h1, [x0]
; VL-256-NEXT:    ldr q0, [x8, :lo12:.LCPI4_0]
; VL-256-NEXT:    adrp x8, .LCPI4_1
; VL-256-NEXT:    tbl v0.16b, { v1.16b }, v0.16b
; VL-256-NEXT:    ldr q1, [x8, :lo12:.LCPI4_1]
; VL-256-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-256-NEXT:    ret
;
; VL-128-BE-LABEL: sext_v16i1_strictalign_align2:
; VL-128-BE:       // %bb.0:
; VL-128-BE-NEXT:    ldr h0, [x0]
; VL-128-BE-NEXT:    adrp x8, .LCPI4_0
; VL-128-BE-NEXT:    add x8, x8, :lo12:.LCPI4_0
; VL-128-BE-NEXT:    ld1 { v1.16b }, [x8]
; VL-128-BE-NEXT:    adrp x8, .LCPI4_1
; VL-128-BE-NEXT:    add x8, x8, :lo12:.LCPI4_1
; VL-128-BE-NEXT:    rev16 v0.16b, v0.16b
; VL-128-BE-NEXT:    tbl v0.16b, { v0.16b }, v1.16b
; VL-128-BE-NEXT:    ld1 { v1.16b }, [x8]
; VL-128-BE-NEXT:    cmtst v0.16b, v0.16b, v1.16b
; VL-128-BE-NEXT:    rev64 v0.16b, v0.16b
; VL-128-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; VL-128-BE-NEXT:    ret
    %l = load <16 x i1>, ptr %p, align 2
    %e = sext <16 x i1> %l to <16 x i8>
    ret <16 x i8> %e
}

define <32 x i8> @sext_v32i1_v32i8(ptr %p) {
; VL-UNKNOWN-LABEL: sext_v32i1_v32i8:
; VL-UNKNOWN:       // %bb.0:
; VL-UNKNOWN-NEXT:    adrp x8, .LCPI5_0
; VL-UNKNOWN-NEXT:    adrp x9, .LCPI5_2
; VL-UNKNOWN-NEXT:    ldr s1, [x0]
; VL-UNKNOWN-NEXT:    ldr q0, [x8, :lo12:.LCPI5_0]
; VL-UNKNOWN-NEXT:    ldr q2, [x9, :lo12:.LCPI5_2]
; VL-UNKNOWN-NEXT:    adrp x8, .LCPI5_1
; VL-UNKNOWN-NEXT:    tbl v0.16b, { v1.16b }, v0.16b
; VL-UNKNOWN-NEXT:    tbl v1.16b, { v1.16b }, v2.16b
; VL-UNKNOWN-NEXT:    ldr q2, [x8, :lo12:.LCPI5_1]
; VL-UNKNOWN-NEXT:    cmtst v0.16b, v0.16b, v2.16b
; VL-UNKNOWN-NEXT:    cmtst v1.16b, v1.16b, v2.16b
; VL-UNKNOWN-NEXT:    ret
;
; VL-128-LABEL: sext_v32i1_v32i8:
; VL-128:       // %bb.0:
; VL-128-NEXT:    adrp x8, .LCPI5_0
; VL-128-NEXT:    adrp x9, .LCPI5_2
; VL-128-NEXT:    ldr s1, [x0]
; VL-128-NEXT:    ldr q0, [x8, :lo12:.LCPI5_0]
; VL-128-NEXT:    ldr q2, [x9, :lo12:.LCPI5_2]
; VL-128-NEXT:    adrp x8, .LCPI5_1
; VL-128-NEXT:    tbl v0.16b, { v1.16b }, v0.16b
; VL-128-NEXT:    tbl v1.16b, { v1.16b }, v2.16b
; VL-128-NEXT:    ldr q2, [x8, :lo12:.LCPI5_1]
; VL-128-NEXT:    cmtst v0.16b, v0.16b, v2.16b
; VL-128-NEXT:    cmtst v1.16b, v1.16b, v2.16b
; VL-128-NEXT:    ret
;
; VL-256-LABEL: sext_v32i1_v32i8:
; VL-256:       // %bb.0:
; VL-256-NEXT:    stp x29, x30, [sp, #-16]! // 16-byte Folded Spill
; VL-256-NEXT:    sub x9, sp, #48
; VL-256-NEXT:    mov x29, sp
; VL-256-NEXT:    and sp, x9, #0xffffffffffffffe0
; VL-256-NEXT:    .cfi_def_cfa w29, 16
; VL-256-NEXT:    .cfi_offset w30, -8
; VL-256-NEXT:    .cfi_offset w29, -16
; VL-256-NEXT:    ldr w9, [x0]
; VL-256-NEXT:    adrp x8, .LCPI5_0
; VL-256-NEXT:    add x8, x8, :lo12:.LCPI5_0
; VL-256-NEXT:    ldr z0, [x8]
; VL-256-NEXT:    adrp x8, .LCPI5_1
; VL-256-NEXT:    add x8, x8, :lo12:.LCPI5_1
; VL-256-NEXT:    str w9, [sp]
; VL-256-NEXT:    mov x9, sp
; VL-256-NEXT:    ptrue p0.b
; VL-256-NEXT:    ldr z1, [x9]
; VL-256-NEXT:    tbl z0.b, { z1.b }, z0.b
; VL-256-NEXT:    ldr z1, [x8]
; VL-256-NEXT:    and z0.d, z0.d, z1.d
; VL-256-NEXT:    cmpne p1.b, p0/z, z0.b, #0
; VL-256-NEXT:    mov z0.b, p1/z, #-1 // =0xffffffffffffffff
; VL-256-NEXT:    movprfx z1, z0
; VL-256-NEXT:    ext z1.b, z1.b, z0.b, #16
; VL-256-NEXT:    // kill: def $q0 killed $q0 killed $z0
; VL-256-NEXT:    // kill: def $q1 killed $q1 killed $z1
; VL-256-NEXT:    mov sp, x29
; VL-256-NEXT:    ldp x29, x30, [sp], #16 // 16-byte Folded Reload
; VL-256-NEXT:    ret
;
; VL-128-BE-LABEL: sext_v32i1_v32i8:
; VL-128-BE:       // %bb.0:
; VL-128-BE-NEXT:    ldr s0, [x0]
; VL-128-BE-NEXT:    adrp x8, .LCPI5_0
; VL-128-BE-NEXT:    add x8, x8, :lo12:.LCPI5_0
; VL-128-BE-NEXT:    ld1 { v1.16b }, [x8]
; VL-128-BE-NEXT:    adrp x8, .LCPI5_2
; VL-128-BE-NEXT:    add x8, x8, :lo12:.LCPI5_2
; VL-128-BE-NEXT:    rev32 v0.16b, v0.16b
; VL-128-BE-NEXT:    ld1 { v2.16b }, [x8]
; VL-128-BE-NEXT:    adrp x8, .LCPI5_1
; VL-128-BE-NEXT:    add x8, x8, :lo12:.LCPI5_1
; VL-128-BE-NEXT:    tbl v1.16b, { v0.16b }, v1.16b
; VL-128-BE-NEXT:    tbl v0.16b, { v0.16b }, v2.16b
; VL-128-BE-NEXT:    ld1 { v2.16b }, [x8]
; VL-128-BE-NEXT:    cmtst v1.16b, v1.16b, v2.16b
; VL-128-BE-NEXT:    cmtst v0.16b, v0.16b, v2.16b
; VL-128-BE-NEXT:    rev64 v0.16b, v0.16b
; VL-128-BE-NEXT:    rev64 v1.16b, v1.16b
; VL-128-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; VL-128-BE-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; VL-128-BE-NEXT:    ret
    %l = load <32 x i1>, ptr %p, align 4
    %e = sext <32 x i1> %l to <32 x i8>
    ret <32 x i8> %e
}

attributes #0 = { "target-features"="+sve,+strict-align" }
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
