; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-linux-gnu -verify-machineinstrs -o - %s | FileCheck %s --check-prefixes=CHECK,CHECK-NO16,CHECK-NO16-SD
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+fullfp16 -verify-machineinstrs -o - %s | FileCheck %s --check-prefixes=CHECK,CHECK-FP16,CHECK-FP16-SD
; RUN: llc -mtriple=aarch64-linux-gnu -verify-machineinstrs -global-isel -o - %s | FileCheck %s --check-prefixes=CHECK,CHECK-NO16,CHECK-NO16-GI
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+fullfp16 -verify-machineinstrs -global-isel -o - %s | FileCheck %s --check-prefixes=CHECK,CHECK-FP16,CHECK-FP16-GI

define <2 x i32> @test1(<2 x float> %f) {
; CHECK-LABEL: test1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.2s, v0.2s, #4
; CHECK-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 16.000000e+00, float 16.000000e+00>
  %vcvt.i = fptosi <2 x float> %mul.i to <2 x i32>
  ret <2 x i32> %vcvt.i
}

define <4 x i32> @test2(<4 x float> %f) {
; CHECK-LABEL: test2:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.4s, v0.4s, #3
; CHECK-NEXT:    ret
  %mul.i = fmul <4 x float> %f, <float 8.000000e+00, float 8.000000e+00, float 8.000000e+00, float 8.000000e+00>
  %vcvt.i = fptosi <4 x float> %mul.i to <4 x i32>
  ret <4 x i32> %vcvt.i
}

define <2 x i64> @test3(<2 x double> %d) {
; CHECK-LABEL: test3:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.2d, v0.2d, #5
; CHECK-NEXT:    ret
  %mul.i = fmul <2 x double> %d, <double 32.000000e+00, double 32.000000e+00>
  %vcvt.i = fptosi <2 x double> %mul.i to <2 x i64>
  ret <2 x i64> %vcvt.i
}

; Truncate double to i32
define <2 x i32> @test4(<2 x double> %d) {
; CHECK-LABEL: test4:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.2d, v0.2d, #4
; CHECK-NEXT:    xtn v0.2s, v0.2d
; CHECK-NEXT:    ret
  %mul.i = fmul <2 x double> %d, <double 16.000000e+00, double 16.000000e+00>
  %vcvt.i = fptosi <2 x double> %mul.i to <2 x i32>
  ret <2 x i32> %vcvt.i
}

; Truncate float to i16
define <2 x i16> @test5(<2 x float> %f) {
; CHECK-LABEL: test5:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.2s, v0.2s, #4
; CHECK-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 16.000000e+00, float 16.000000e+00>
  %vcvt.i = fptosi <2 x float> %mul.i to <2 x i16>
  ret <2 x i16> %vcvt.i
}

; Don't convert float to i64
define <2 x i64> @test6(<2 x float> %f) {
; CHECK-NO16-SD-LABEL: test6:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fmov v1.2s, #16.00000000
; CHECK-NO16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-SD-NEXT:    fcvtl v0.2d, v0.2s
; CHECK-NO16-SD-NEXT:    fcvtzs v0.2d, v0.2d
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test6:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    fmov v1.2s, #16.00000000
; CHECK-FP16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-SD-NEXT:    fcvtl v0.2d, v0.2s
; CHECK-FP16-SD-NEXT:    fcvtzs v0.2d, v0.2d
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test6:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    fmov s1, #16.00000000
; CHECK-NO16-GI-NEXT:    fmul v0.2s, v0.2s, v1.s[0]
; CHECK-NO16-GI-NEXT:    fcvtl v0.2d, v0.2s
; CHECK-NO16-GI-NEXT:    fcvtzs v0.2d, v0.2d
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test6:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    fmov s1, #16.00000000
; CHECK-FP16-GI-NEXT:    fmul v0.2s, v0.2s, v1.s[0]
; CHECK-FP16-GI-NEXT:    fcvtl v0.2d, v0.2s
; CHECK-FP16-GI-NEXT:    fcvtzs v0.2d, v0.2d
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 16.000000e+00, float 16.000000e+00>
  %vcvt.i = fptosi <2 x float> %mul.i to <2 x i64>
  ret <2 x i64> %vcvt.i
}

define <2 x i32> @test7(<2 x float> %f) {
; CHECK-LABEL: test7:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzu v0.2s, v0.2s, #4
; CHECK-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 16.000000e+00, float 16.000000e+00>
  %vcvt.i = fptoui <2 x float> %mul.i to <2 x i32>
  ret <2 x i32> %vcvt.i
}

; Test which should not fold due to non-power of 2.
define <2 x i32> @test8(<2 x float> %f) {
; CHECK-NO16-SD-LABEL: test8:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fmov v1.2s, #17.00000000
; CHECK-NO16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-SD-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test8:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    fmov v1.2s, #17.00000000
; CHECK-FP16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-SD-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test8:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    fmov s1, #17.00000000
; CHECK-NO16-GI-NEXT:    fmul v0.2s, v0.2s, v1.s[0]
; CHECK-NO16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test8:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    fmov s1, #17.00000000
; CHECK-FP16-GI-NEXT:    fmul v0.2s, v0.2s, v1.s[0]
; CHECK-FP16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 17.000000e+00, float 17.000000e+00>
  %vcvt.i = fptoui <2 x float> %mul.i to <2 x i32>
  ret <2 x i32> %vcvt.i
}

; Test which should not fold due to non-matching power of 2.
define <2 x i32> @test9(<2 x float> %f) {
; CHECK-NO16-SD-LABEL: test9:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    mov x8, #1098907648 // =0x41800000
; CHECK-NO16-SD-NEXT:    movk x8, #16640, lsl #48
; CHECK-NO16-SD-NEXT:    fmov d1, x8
; CHECK-NO16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-SD-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test9:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    mov x8, #1098907648 // =0x41800000
; CHECK-FP16-SD-NEXT:    movk x8, #16640, lsl #48
; CHECK-FP16-SD-NEXT:    fmov d1, x8
; CHECK-FP16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-SD-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test9:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    adrp x8, .LCPI8_0
; CHECK-NO16-GI-NEXT:    ldr d1, [x8, :lo12:.LCPI8_0]
; CHECK-NO16-GI-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test9:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    adrp x8, .LCPI8_0
; CHECK-FP16-GI-NEXT:    ldr d1, [x8, :lo12:.LCPI8_0]
; CHECK-FP16-GI-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 16.000000e+00, float 8.000000e+00>
  %vcvt.i = fptoui <2 x float> %mul.i to <2 x i32>
  ret <2 x i32> %vcvt.i
}

; Combine all undefs.
define <2 x i32> @test10(<2 x float> %f) {
; CHECK-NO16-SD-LABEL: test10:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    mvni v0.2s, #63, msl #16
; CHECK-NO16-SD-NEXT:    fneg v0.2s, v0.2s
; CHECK-NO16-SD-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test10:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    mvni v0.2s, #63, msl #16
; CHECK-FP16-SD-NEXT:    fneg v0.2s, v0.2s
; CHECK-FP16-SD-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test10:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    fmul v0.2s, v0.2s, v0.2s
; CHECK-NO16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test10:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    fmul v0.2s, v0.2s, v0.2s
; CHECK-FP16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float undef, float undef>
  %vcvt.i = fptoui <2 x float> %mul.i to <2 x i32>
  ret <2 x i32> %vcvt.i
}

; Combine if mix of undef and pow2.
define <2 x i32> @test11(<2 x float> %f) {
; CHECK-NO16-SD-LABEL: test11:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fcvtzu v0.2s, v0.2s, #3
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test11:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    fcvtzu v0.2s, v0.2s, #3
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test11:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    fmov s1, #8.00000000
; CHECK-NO16-GI-NEXT:    mov v1.s[1], v1.s[0]
; CHECK-NO16-GI-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test11:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    fmov s1, #8.00000000
; CHECK-FP16-GI-NEXT:    mov v1.s[1], v1.s[0]
; CHECK-FP16-GI-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float undef, float 8.000000e+00>
  %vcvt.i = fptoui <2 x float> %mul.i to <2 x i32>
  ret <2 x i32> %vcvt.i
}

; Don't combine when multiplied by 0.0.
define <2 x i32> @test12(<2 x float> %f) {
; CHECK-NO16-SD-LABEL: test12:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    movi d1, #0000000000000000
; CHECK-NO16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-SD-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test12:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    movi d1, #0000000000000000
; CHECK-FP16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-SD-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test12:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    movi v1.2d, #0000000000000000
; CHECK-NO16-GI-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-GI-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test12:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    movi v1.2d, #0000000000000000
; CHECK-FP16-GI-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-GI-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 0.000000e+00, float 0.000000e+00>
  %vcvt.i = fptosi <2 x float> %mul.i to <2 x i32>
  ret <2 x i32> %vcvt.i
}

; Test which should not fold due to power of 2 out of range (i.e., 2^33).
define <2 x i32> @test13(<2 x float> %f) {
; CHECK-NO16-SD-LABEL: test13:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    movi v1.2s, #80, lsl #24
; CHECK-NO16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-SD-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test13:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    movi v1.2s, #80, lsl #24
; CHECK-FP16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-SD-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test13:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    movi v1.2s, #80, lsl #24
; CHECK-NO16-GI-NEXT:    fmul v0.2s, v0.2s, v1.s[0]
; CHECK-NO16-GI-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test13:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    movi v1.2s, #80, lsl #24
; CHECK-FP16-GI-NEXT:    fmul v0.2s, v0.2s, v1.s[0]
; CHECK-FP16-GI-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 0x4200000000000000, float 0x4200000000000000>
  %vcvt.i = fptosi <2 x float> %mul.i to <2 x i32>
  ret <2 x i32> %vcvt.i
}

; Test case where const is max power of 2 (i.e., 2^32).
define <2 x i32> @test14(<2 x float> %f) {
; CHECK-LABEL: test14:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.2s, v0.2s, #32
; CHECK-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 0x41F0000000000000, float 0x41F0000000000000>
  %vcvt.i = fptosi <2 x float> %mul.i to <2 x i32>
  ret <2 x i32> %vcvt.i
}

define <3 x i32> @test_illegal_fp_to_int(<3 x float> %in) {
; CHECK-LABEL: test_illegal_fp_to_int:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.4s, v0.4s, #2
; CHECK-NEXT:    ret
  %scale = fmul <3 x float> %in, <float 4.0, float 4.0, float 4.0>
  %val = fptosi <3 x float> %scale to <3 x i32>
  ret <3 x i32> %val
}

define <8 x i16> @test_v8f16(<8 x half> %in) {
; CHECK-NO16-SD-LABEL: test_v8f16:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fmov v1.4s, #4.00000000
; CHECK-NO16-SD-NEXT:    fcvtl v2.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtl2 v0.4s, v0.8h
; CHECK-NO16-SD-NEXT:    fmul v2.4s, v2.4s, v1.4s
; CHECK-NO16-SD-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-NO16-SD-NEXT:    fcvtn v1.4h, v2.4s
; CHECK-NO16-SD-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-SD-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtzs v1.4s, v1.4s
; CHECK-NO16-SD-NEXT:    uzp1 v0.8h, v1.8h, v0.8h
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-LABEL: test_v8f16:
; CHECK-FP16:       // %bb.0:
; CHECK-FP16-NEXT:    fcvtzs v0.8h, v0.8h, #2
; CHECK-FP16-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test_v8f16:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    movi v1.4h, #68, lsl #8
; CHECK-NO16-GI-NEXT:    fcvtl v2.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtl2 v0.4s, v0.8h
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-GI-NEXT:    fmul v2.4s, v2.4s, v1.4s
; CHECK-NO16-GI-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtn v1.4h, v2.4s
; CHECK-NO16-GI-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtzs v1.4s, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-NO16-GI-NEXT:    uzp1 v0.8h, v1.8h, v0.8h
; CHECK-NO16-GI-NEXT:    ret
  %scale = fmul <8 x half> %in, <half 4.0, half 4.0, half 4.0, half 4.0, half 4.0, half 4.0, half 4.0, half 4.0>
  %val = fptosi <8 x half> %scale to <8 x i16>
  ret <8 x i16> %val
}

define <4 x i16> @test_v4f16(<4 x half> %in) {
; CHECK-NO16-SD-LABEL: test_v4f16:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fmov v1.4s, #4.00000000
; CHECK-NO16-SD-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-NO16-SD-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-NO16-SD-NEXT:    xtn v0.4h, v0.4s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-LABEL: test_v4f16:
; CHECK-FP16:       // %bb.0:
; CHECK-FP16-NEXT:    fcvtzu v0.4h, v0.4h, #2
; CHECK-FP16-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test_v4f16:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    movi v1.4h, #68, lsl #8
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-GI-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-NO16-GI-NEXT:    xtn v0.4h, v0.4s
; CHECK-NO16-GI-NEXT:    ret
  %scale = fmul <4 x half> %in, <half 4.0, half 4.0, half 4.0, half 4.0>
  %val = fptoui <4 x half> %scale to <4 x i16>
  ret <4 x i16> %val
}

define <4 x i32> @test_v4f16_i32(<4 x half> %in) {
; CHECK-NO16-SD-LABEL: test_v4f16_i32:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fmov v1.4s, #4.00000000
; CHECK-NO16-SD-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-NO16-SD-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-LABEL: test_v4f16_i32:
; CHECK-FP16:       // %bb.0:
; CHECK-FP16-NEXT:    movi v1.4h, #68, lsl #8
; CHECK-FP16-NEXT:    fmul v0.4h, v0.4h, v1.4h
; CHECK-FP16-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-FP16-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-FP16-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test_v4f16_i32:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    movi v1.4h, #68, lsl #8
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-GI-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-NO16-GI-NEXT:    ret
  %scale = fmul <4 x half> %in, <half 4.0, half 4.0, half 4.0, half 4.0>
  %val = fptosi <4 x half> %scale to <4 x i32>
  ret <4 x i32> %val
}

; Test conversion with NaN value.
define <8 x i16> @test_v8f16_nan(<8 x half> %a) {
; CHECK-NO16-SD-LABEL: test_v8f16_nan:
; CHECK-NO16-SD:       // %bb.0: // %entry
; CHECK-NO16-SD-NEXT:    mvni v1.4s, #63, msl #16
; CHECK-NO16-SD-NEXT:    fcvtl v2.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtl2 v0.4s, v0.8h
; CHECK-NO16-SD-NEXT:    fneg v1.4s, v1.4s
; CHECK-NO16-SD-NEXT:    fmul v2.4s, v2.4s, v1.4s
; CHECK-NO16-SD-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-NO16-SD-NEXT:    fcvtn v1.4h, v2.4s
; CHECK-NO16-SD-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-SD-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtzs v1.4s, v1.4s
; CHECK-NO16-SD-NEXT:    uzp1 v0.8h, v1.8h, v0.8h
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-LABEL: test_v8f16_nan:
; CHECK-FP16:       // %bb.0: // %entry
; CHECK-FP16-NEXT:    movi v1.8h, #126, lsl #8
; CHECK-FP16-NEXT:    fmul v0.8h, v0.8h, v1.8h
; CHECK-FP16-NEXT:    fcvtzs v0.8h, v0.8h
; CHECK-FP16-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test_v8f16_nan:
; CHECK-NO16-GI:       // %bb.0: // %entry
; CHECK-NO16-GI-NEXT:    movi v1.4h, #126, lsl #8
; CHECK-NO16-GI-NEXT:    fcvtl v2.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtl2 v0.4s, v0.8h
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-GI-NEXT:    fmul v2.4s, v2.4s, v1.4s
; CHECK-NO16-GI-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtn v1.4h, v2.4s
; CHECK-NO16-GI-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtzs v1.4s, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-NO16-GI-NEXT:    uzp1 v0.8h, v1.8h, v0.8h
; CHECK-NO16-GI-NEXT:    ret
entry:
  %fmul = fmul <8 x half> %a, splat (half 0xH7E00)
  %fptosi = fptosi <8 x half> %fmul to <8 x i16>
  ret <8 x i16> %fptosi
}

declare <2 x i32> @llvm.fptosi.sat.v2i32.v2f32(<2 x float>)
declare <2 x i32> @llvm.fptoui.sat.v2i32.v2f32(<2 x float>)
declare <2 x i32> @llvm.fptosi.sat.v2i32.v2f64(<2 x double>)
declare <2 x i64> @llvm.fptosi.sat.v2i64.v2f64(<2 x double>)
declare <4 x i32> @llvm.fptosi.sat.v4i32.v4f32(<4 x float>)
declare <2 x i16> @llvm.fptosi.sat.v2i16.v2f32(<2 x float>)
declare <4 x i16> @llvm.fptosi.sat.v4i16.v4f32(<4 x float>)
declare <2 x i64> @llvm.fptosi.sat.v2i64.v2f32(<2 x float>)
declare <3 x i32> @llvm.fptosi.sat.v3i32.v3f32(<3 x float>)
declare <8 x i16> @llvm.fptosi.sat.v8i16.v8f16(<8 x half>)
declare <4 x i16> @llvm.fptoui.sat.v4i16.v4f16(<4 x half>)
declare <4 x i32> @llvm.fptosi.sat.v4i32.v4f16(<4 x half>)
declare <4 x i24> @llvm.fptoui.sat.v4i24.v4f32(<4 x float>)

define <2 x i32> @test1_sat(<2 x float> %f) {
; CHECK-LABEL: test1_sat:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.2s, v0.2s, #4
; CHECK-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 16.000000e+00, float 16.000000e+00>
  %vcvt.i = call <2 x i32> @llvm.fptosi.sat.v2i32.v2f32(<2 x float> %mul.i)
  ret <2 x i32> %vcvt.i
}

define <4 x i32> @test2_sat(<4 x float> %f) {
; CHECK-LABEL: test2_sat:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.4s, v0.4s, #3
; CHECK-NEXT:    ret
  %mul.i = fmul <4 x float> %f, <float 8.000000e+00, float 8.000000e+00, float 8.000000e+00, float 8.000000e+00>
  %vcvt.i = call <4 x i32> @llvm.fptosi.sat.v4i32.v4f32(<4 x float> %mul.i)
  ret <4 x i32> %vcvt.i
}

define <2 x i64> @test3_sat(<2 x double> %d) {
; CHECK-LABEL: test3_sat:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.2d, v0.2d, #5
; CHECK-NEXT:    ret
  %mul.i = fmul <2 x double> %d, <double 32.000000e+00, double 32.000000e+00>
  %vcvt.i = call <2 x i64> @llvm.fptosi.sat.v2i64.v2f64(<2 x double> %mul.i)
  ret <2 x i64> %vcvt.i
}

; Truncate double to i32
define <2 x i32> @test4_sat(<2 x double> %d) {
; CHECK-NO16-SD-LABEL: test4_sat:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fmov v1.2d, #16.00000000
; CHECK-NO16-SD-NEXT:    fmul v0.2d, v0.2d, v1.2d
; CHECK-NO16-SD-NEXT:    mov d1, v0.d[1]
; CHECK-NO16-SD-NEXT:    fcvtzs w8, d0
; CHECK-NO16-SD-NEXT:    fcvtzs w9, d1
; CHECK-NO16-SD-NEXT:    fmov s0, w8
; CHECK-NO16-SD-NEXT:    mov v0.s[1], w9
; CHECK-NO16-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test4_sat:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    fmov v1.2d, #16.00000000
; CHECK-FP16-SD-NEXT:    fmul v0.2d, v0.2d, v1.2d
; CHECK-FP16-SD-NEXT:    mov d1, v0.d[1]
; CHECK-FP16-SD-NEXT:    fcvtzs w8, d0
; CHECK-FP16-SD-NEXT:    fcvtzs w9, d1
; CHECK-FP16-SD-NEXT:    fmov s0, w8
; CHECK-FP16-SD-NEXT:    mov v0.s[1], w9
; CHECK-FP16-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test4_sat:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    fcvtzs v0.2d, v0.2d, #4
; CHECK-NO16-GI-NEXT:    adrp x8, .LCPI22_1
; CHECK-NO16-GI-NEXT:    ldr q1, [x8, :lo12:.LCPI22_1]
; CHECK-NO16-GI-NEXT:    adrp x8, .LCPI22_0
; CHECK-NO16-GI-NEXT:    cmgt v2.2d, v1.2d, v0.2d
; CHECK-NO16-GI-NEXT:    bif v0.16b, v1.16b, v2.16b
; CHECK-NO16-GI-NEXT:    ldr q1, [x8, :lo12:.LCPI22_0]
; CHECK-NO16-GI-NEXT:    cmgt v2.2d, v0.2d, v1.2d
; CHECK-NO16-GI-NEXT:    bif v0.16b, v1.16b, v2.16b
; CHECK-NO16-GI-NEXT:    xtn v0.2s, v0.2d
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test4_sat:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    fcvtzs v0.2d, v0.2d, #4
; CHECK-FP16-GI-NEXT:    adrp x8, .LCPI22_1
; CHECK-FP16-GI-NEXT:    ldr q1, [x8, :lo12:.LCPI22_1]
; CHECK-FP16-GI-NEXT:    adrp x8, .LCPI22_0
; CHECK-FP16-GI-NEXT:    cmgt v2.2d, v1.2d, v0.2d
; CHECK-FP16-GI-NEXT:    bif v0.16b, v1.16b, v2.16b
; CHECK-FP16-GI-NEXT:    ldr q1, [x8, :lo12:.LCPI22_0]
; CHECK-FP16-GI-NEXT:    cmgt v2.2d, v0.2d, v1.2d
; CHECK-FP16-GI-NEXT:    bif v0.16b, v1.16b, v2.16b
; CHECK-FP16-GI-NEXT:    xtn v0.2s, v0.2d
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x double> %d, <double 16.000000e+00, double 16.000000e+00>
  %vcvt.i = call <2 x i32> @llvm.fptosi.sat.v2i32.v2f64(<2 x double> %mul.i)
  ret <2 x i32> %vcvt.i
}

; Truncate float to i16
define <2 x i16> @test5_sat(<2 x float> %f) {
; CHECK-NO16-SD-LABEL: test5_sat:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fcvtzs v0.2s, v0.2s, #4
; CHECK-NO16-SD-NEXT:    mvni v1.2s, #127, msl #8
; CHECK-NO16-SD-NEXT:    movi v2.2s, #127, msl #8
; CHECK-NO16-SD-NEXT:    smax v0.2s, v0.2s, v1.2s
; CHECK-NO16-SD-NEXT:    smin v0.2s, v0.2s, v2.2s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test5_sat:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    fcvtzs v0.2s, v0.2s, #4
; CHECK-FP16-SD-NEXT:    mvni v1.2s, #127, msl #8
; CHECK-FP16-SD-NEXT:    movi v2.2s, #127, msl #8
; CHECK-FP16-SD-NEXT:    smax v0.2s, v0.2s, v1.2s
; CHECK-FP16-SD-NEXT:    smin v0.2s, v0.2s, v2.2s
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test5_sat:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    movi v1.2s, #127, msl #8
; CHECK-NO16-GI-NEXT:    fcvtzs v0.2s, v0.2s, #4
; CHECK-NO16-GI-NEXT:    mvni v2.2s, #127, msl #8
; CHECK-NO16-GI-NEXT:    smin v0.2s, v0.2s, v1.2s
; CHECK-NO16-GI-NEXT:    smax v0.2s, v0.2s, v2.2s
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test5_sat:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    movi v1.2s, #127, msl #8
; CHECK-FP16-GI-NEXT:    fcvtzs v0.2s, v0.2s, #4
; CHECK-FP16-GI-NEXT:    mvni v2.2s, #127, msl #8
; CHECK-FP16-GI-NEXT:    smin v0.2s, v0.2s, v1.2s
; CHECK-FP16-GI-NEXT:    smax v0.2s, v0.2s, v2.2s
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 16.000000e+00, float 16.000000e+00>
  %vcvt.i = call <2 x i16> @llvm.fptosi.sat.v2i16.v2f32(<2 x float> %mul.i)
  ret <2 x i16> %vcvt.i
}

; Truncate float to i16
define <4 x i16> @test5l_sat(<4 x float> %f) {
; CHECK-LABEL: test5l_sat:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.4s, v0.4s, #4
; CHECK-NEXT:    sqxtn v0.4h, v0.4s
; CHECK-NEXT:    ret
  %mul.i = fmul <4 x float> %f, <float 16.000000e+00, float 16.000000e+00, float 16.000000e+00, float 16.000000e+00>
  %vcvt.i = call <4 x i16> @llvm.fptosi.sat.v4i16.v4f32(<4 x float> %mul.i)
  ret <4 x i16> %vcvt.i
}

; Don't convert float to i64
define <2 x i64> @test6_sat(<2 x float> %f) {
; CHECK-NO16-SD-LABEL: test6_sat:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fmov v1.2s, #16.00000000
; CHECK-NO16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-SD-NEXT:    fcvtl v0.2d, v0.2s
; CHECK-NO16-SD-NEXT:    fcvtzs v0.2d, v0.2d
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test6_sat:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    fmov v1.2s, #16.00000000
; CHECK-FP16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-SD-NEXT:    fcvtl v0.2d, v0.2s
; CHECK-FP16-SD-NEXT:    fcvtzs v0.2d, v0.2d
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test6_sat:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    fmov s1, #16.00000000
; CHECK-NO16-GI-NEXT:    fmul v0.2s, v0.2s, v1.s[0]
; CHECK-NO16-GI-NEXT:    fcvtl v0.2d, v0.2s
; CHECK-NO16-GI-NEXT:    fcvtzs v0.2d, v0.2d
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test6_sat:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    fmov s1, #16.00000000
; CHECK-FP16-GI-NEXT:    fmul v0.2s, v0.2s, v1.s[0]
; CHECK-FP16-GI-NEXT:    fcvtl v0.2d, v0.2s
; CHECK-FP16-GI-NEXT:    fcvtzs v0.2d, v0.2d
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 16.000000e+00, float 16.000000e+00>
  %vcvt.i = call <2 x i64> @llvm.fptosi.sat.v2i64.v2f32(<2 x float> %mul.i)
  ret <2 x i64> %vcvt.i
}

define <2 x i32> @test7_sat(<2 x float> %f) {
; CHECK-LABEL: test7_sat:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzu v0.2s, v0.2s, #4
; CHECK-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 16.000000e+00, float 16.000000e+00>
  %vcvt.i = call <2 x i32> @llvm.fptoui.sat.v2i32.v2f32(<2 x float> %mul.i)
  ret <2 x i32> %vcvt.i
}

; Test which should not fold due to non-power of 2.
define <2 x i32> @test8_sat(<2 x float> %f) {
; CHECK-NO16-SD-LABEL: test8_sat:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fmov v1.2s, #17.00000000
; CHECK-NO16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-SD-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test8_sat:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    fmov v1.2s, #17.00000000
; CHECK-FP16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-SD-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test8_sat:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    fmov s1, #17.00000000
; CHECK-NO16-GI-NEXT:    fmul v0.2s, v0.2s, v1.s[0]
; CHECK-NO16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test8_sat:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    fmov s1, #17.00000000
; CHECK-FP16-GI-NEXT:    fmul v0.2s, v0.2s, v1.s[0]
; CHECK-FP16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 17.000000e+00, float 17.000000e+00>
  %vcvt.i = call <2 x i32> @llvm.fptoui.sat.v2i32.v2f32(<2 x float> %mul.i)
  ret <2 x i32> %vcvt.i
}

; Test which should not fold due to non-matching power of 2.
define <2 x i32> @test9_sat(<2 x float> %f) {
; CHECK-NO16-SD-LABEL: test9_sat:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    mov x8, #1098907648 // =0x41800000
; CHECK-NO16-SD-NEXT:    movk x8, #16640, lsl #48
; CHECK-NO16-SD-NEXT:    fmov d1, x8
; CHECK-NO16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-SD-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test9_sat:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    mov x8, #1098907648 // =0x41800000
; CHECK-FP16-SD-NEXT:    movk x8, #16640, lsl #48
; CHECK-FP16-SD-NEXT:    fmov d1, x8
; CHECK-FP16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-SD-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test9_sat:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    adrp x8, .LCPI28_0
; CHECK-NO16-GI-NEXT:    ldr d1, [x8, :lo12:.LCPI28_0]
; CHECK-NO16-GI-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test9_sat:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    adrp x8, .LCPI28_0
; CHECK-FP16-GI-NEXT:    ldr d1, [x8, :lo12:.LCPI28_0]
; CHECK-FP16-GI-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 16.000000e+00, float 8.000000e+00>
  %vcvt.i = call <2 x i32> @llvm.fptoui.sat.v2i32.v2f32(<2 x float> %mul.i)
  ret <2 x i32> %vcvt.i
}

; Combine all undefs.
define <2 x i32> @test10_sat(<2 x float> %f) {
; CHECK-NO16-SD-LABEL: test10_sat:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    mvni v0.2s, #63, msl #16
; CHECK-NO16-SD-NEXT:    fneg v0.2s, v0.2s
; CHECK-NO16-SD-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test10_sat:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    mvni v0.2s, #63, msl #16
; CHECK-FP16-SD-NEXT:    fneg v0.2s, v0.2s
; CHECK-FP16-SD-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test10_sat:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    fmul v0.2s, v0.2s, v0.2s
; CHECK-NO16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test10_sat:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    fmul v0.2s, v0.2s, v0.2s
; CHECK-FP16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float undef, float undef>
  %vcvt.i = call <2 x i32> @llvm.fptoui.sat.v2i32.v2f32(<2 x float> %mul.i)
  ret <2 x i32> %vcvt.i
}

; Combine if mix of undef and pow2.
define <2 x i32> @test11_sat(<2 x float> %f) {
; CHECK-NO16-SD-LABEL: test11_sat:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fcvtzu v0.2s, v0.2s, #3
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test11_sat:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    fcvtzu v0.2s, v0.2s, #3
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test11_sat:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    fmov s1, #8.00000000
; CHECK-NO16-GI-NEXT:    mov v1.s[1], v1.s[0]
; CHECK-NO16-GI-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test11_sat:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    fmov s1, #8.00000000
; CHECK-FP16-GI-NEXT:    mov v1.s[1], v1.s[0]
; CHECK-FP16-GI-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-GI-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float undef, float 8.000000e+00>
  %vcvt.i = call <2 x i32> @llvm.fptoui.sat.v2i32.v2f32(<2 x float> %mul.i)
  ret <2 x i32> %vcvt.i
}

; Don't combine when multiplied by 0.0.
define <2 x i32> @test12_sat(<2 x float> %f) {
; CHECK-NO16-SD-LABEL: test12_sat:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    movi d1, #0000000000000000
; CHECK-NO16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-SD-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test12_sat:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    movi d1, #0000000000000000
; CHECK-FP16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-SD-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test12_sat:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    movi v1.2d, #0000000000000000
; CHECK-NO16-GI-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-GI-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test12_sat:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    movi v1.2d, #0000000000000000
; CHECK-FP16-GI-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-GI-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 0.000000e+00, float 0.000000e+00>
  %vcvt.i = call <2 x i32> @llvm.fptosi.sat.v2i32.v2f32(<2 x float> %mul.i)
  ret <2 x i32> %vcvt.i
}

; Test which should not fold due to power of 2 out of range (i.e., 2^33).
define <2 x i32> @test13_sat(<2 x float> %f) {
; CHECK-NO16-SD-LABEL: test13_sat:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    movi v1.2s, #80, lsl #24
; CHECK-NO16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-NO16-SD-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: test13_sat:
; CHECK-FP16-SD:       // %bb.0:
; CHECK-FP16-SD-NEXT:    movi v1.2s, #80, lsl #24
; CHECK-FP16-SD-NEXT:    fmul v0.2s, v0.2s, v1.2s
; CHECK-FP16-SD-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test13_sat:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    movi v1.2s, #80, lsl #24
; CHECK-NO16-GI-NEXT:    fmul v0.2s, v0.2s, v1.s[0]
; CHECK-NO16-GI-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-NO16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: test13_sat:
; CHECK-FP16-GI:       // %bb.0:
; CHECK-FP16-GI-NEXT:    movi v1.2s, #80, lsl #24
; CHECK-FP16-GI-NEXT:    fmul v0.2s, v0.2s, v1.s[0]
; CHECK-FP16-GI-NEXT:    fcvtzs v0.2s, v0.2s
; CHECK-FP16-GI-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 0x4200000000000000, float 0x4200000000000000>
  %vcvt.i = call <2 x i32> @llvm.fptosi.sat.v2i32.v2f32(<2 x float> %mul.i)
  ret <2 x i32> %vcvt.i
}

; Test case where const is max power of 2 (i.e., 2^32).
define <2 x i32> @test14_sat(<2 x float> %f) {
; CHECK-LABEL: test14_sat:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.2s, v0.2s, #32
; CHECK-NEXT:    ret
  %mul.i = fmul <2 x float> %f, <float 0x41F0000000000000, float 0x41F0000000000000>
  %vcvt.i = call <2 x i32> @llvm.fptosi.sat.v2i32.v2f32(<2 x float> %mul.i)
  ret <2 x i32> %vcvt.i
}

define <3 x i32> @test_illegal_fp_to_int_sat_sat(<3 x float> %in) {
; CHECK-LABEL: test_illegal_fp_to_int_sat_sat:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.4s, v0.4s, #2
; CHECK-NEXT:    ret
  %mul.i = fmul <3 x float> %in, <float 4.0, float 4.0, float 4.0>
  %vcvt.i = call <3 x i32> @llvm.fptosi.sat.v3i32.v3f32(<3 x float> %mul.i)
  ret <3 x i32> %vcvt.i
}

define <8 x i16> @test_v8f16_sat(<8 x half> %in) {
; CHECK-NO16-SD-LABEL: test_v8f16_sat:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fmov v1.4s, #4.00000000
; CHECK-NO16-SD-NEXT:    fcvtl v2.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtl2 v0.4s, v0.8h
; CHECK-NO16-SD-NEXT:    fmul v2.4s, v2.4s, v1.4s
; CHECK-NO16-SD-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-NO16-SD-NEXT:    fcvtn v1.4h, v2.4s
; CHECK-NO16-SD-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-SD-NEXT:    fcvtl v2.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtzs v1.4s, v1.4s
; CHECK-NO16-SD-NEXT:    sqxtn v0.4h, v1.4s
; CHECK-NO16-SD-NEXT:    fcvtzs v1.4s, v2.4s
; CHECK-NO16-SD-NEXT:    sqxtn2 v0.8h, v1.4s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-LABEL: test_v8f16_sat:
; CHECK-FP16:       // %bb.0:
; CHECK-FP16-NEXT:    fcvtzs v0.8h, v0.8h, #2
; CHECK-FP16-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test_v8f16_sat:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    movi v1.4h, #68, lsl #8
; CHECK-NO16-GI-NEXT:    fcvtl v2.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtl2 v0.4s, v0.8h
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-GI-NEXT:    fmul v2.4s, v2.4s, v1.4s
; CHECK-NO16-GI-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtn v1.4h, v2.4s
; CHECK-NO16-GI-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtzs v1.4s, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtzs v2.4s, v0.4s
; CHECK-NO16-GI-NEXT:    sqxtn v0.4h, v1.4s
; CHECK-NO16-GI-NEXT:    sqxtn2 v0.8h, v2.4s
; CHECK-NO16-GI-NEXT:    ret
  %mul.i = fmul <8 x half> %in, <half 4.0, half 4.0, half 4.0, half 4.0, half 4.0, half 4.0, half 4.0, half 4.0>
  %val = call <8 x i16> @llvm.fptosi.sat.v8i16.v8f16(<8 x half> %mul.i)
  ret <8 x i16> %val
}

define <4 x i16> @test_v4f16_sat(<4 x half> %in) {
; CHECK-NO16-SD-LABEL: test_v4f16_sat:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fmov v1.4s, #4.00000000
; CHECK-NO16-SD-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-NO16-SD-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-NO16-SD-NEXT:    uqxtn v0.4h, v0.4s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-LABEL: test_v4f16_sat:
; CHECK-FP16:       // %bb.0:
; CHECK-FP16-NEXT:    fcvtzu v0.4h, v0.4h, #2
; CHECK-FP16-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test_v4f16_sat:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    movi v1.4h, #68, lsl #8
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-GI-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-NO16-GI-NEXT:    uqxtn v0.4h, v0.4s
; CHECK-NO16-GI-NEXT:    ret
  %mul.i = fmul <4 x half> %in, <half 4.0, half 4.0, half 4.0, half 4.0>
  %val = call <4 x i16> @llvm.fptoui.sat.v4i16.v4f16(<4 x half> %mul.i)
  ret <4 x i16> %val
}

define <4 x i32> @test_v4f16_i32_sat(<4 x half> %in) {
; CHECK-NO16-SD-LABEL: test_v4f16_i32_sat:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fmov v1.4s, #4.00000000
; CHECK-NO16-SD-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-NO16-SD-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-LABEL: test_v4f16_i32_sat:
; CHECK-FP16:       // %bb.0:
; CHECK-FP16-NEXT:    movi v1.4h, #68, lsl #8
; CHECK-FP16-NEXT:    fmul v0.4h, v0.4h, v1.4h
; CHECK-FP16-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-FP16-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-FP16-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: test_v4f16_i32_sat:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    movi v1.4h, #68, lsl #8
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-GI-NEXT:    fmul v0.4s, v0.4s, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-NO16-GI-NEXT:    ret
  %mul.i = fmul <4 x half> %in, <half 4.0, half 4.0, half 4.0, half 4.0>
  %val = call <4 x i32> @llvm.fptosi.sat.v4i32.v4f16(<4 x half> %mul.i)
  ret <4 x i32> %val
}

define <4 x i32> @test_extrasat(<4 x float> %f) {
; CHECK-LABEL: test_extrasat:
; CHECK:       // %bb.0:
; CHECK-NEXT:    movi v1.2d, #0xffffff00ffffff
; CHECK-NEXT:    fcvtzu v0.4s, v0.4s, #3
; CHECK-NEXT:    umin v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
  %mul.i = fmul <4 x float> %f, <float 8.000000e+00, float 8.000000e+00, float 8.000000e+00, float 8.000000e+00>
  %vcvt.i = call <4 x i24> @llvm.fptoui.sat.v4i24.v4f32(<4 x float> %mul.i)
  %t = zext <4 x i24> %vcvt.i to <4 x i32>
  ret <4 x i32> %t
}

; Test fadd patterns, that can arise instead of fmul 2.0

define <2 x i64> @tests_v2i64_fadd(<2 x double> %f) {
; CHECK-LABEL: tests_v2i64_fadd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.2d, v0.2d, #1
; CHECK-NEXT:    ret
  %mul.i = fadd <2 x double> %f, %f
  %vcvt.i = fptosi <2 x double> %mul.i to <2 x i64>
  ret <2 x i64> %vcvt.i
}

define <2 x i32> @tests_v2i32_fadd(<2 x float> %f) {
; CHECK-LABEL: tests_v2i32_fadd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.2s, v0.2s, #1
; CHECK-NEXT:    ret
  %mul.i = fadd <2 x float> %f, %f
  %vcvt.i = fptosi <2 x float> %mul.i to <2 x i32>
  ret <2 x i32> %vcvt.i
}

define <4 x i32> @tests_v4i32_fadd(<4 x float> %f) {
; CHECK-LABEL: tests_v4i32_fadd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.4s, v0.4s, #1
; CHECK-NEXT:    ret
  %mul.i = fadd <4 x float> %f, %f
  %vcvt.i = fptosi <4 x float> %mul.i to <4 x i32>
  ret <4 x i32> %vcvt.i
}

define <4 x i16> @tests_v2i16_fadd(<4 x half> %f) {
; CHECK-NO16-LABEL: tests_v2i16_fadd:
; CHECK-NO16:       // %bb.0:
; CHECK-NO16-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-NEXT:    fadd v0.4s, v0.4s, v0.4s
; CHECK-NO16-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-NO16-NEXT:    xtn v0.4h, v0.4s
; CHECK-NO16-NEXT:    ret
;
; CHECK-FP16-LABEL: tests_v2i16_fadd:
; CHECK-FP16:       // %bb.0:
; CHECK-FP16-NEXT:    fcvtzs v0.4h, v0.4h, #1
; CHECK-FP16-NEXT:    ret
  %mul.i = fadd <4 x half> %f, %f
  %vcvt.i = fptosi <4 x half> %mul.i to <4 x i16>
  ret <4 x i16> %vcvt.i
}

define <8 x i16> @tests_v8i16_fadd(<8 x half> %f) {
; CHECK-NO16-SD-LABEL: tests_v8i16_fadd:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fcvtl v1.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtl2 v0.4s, v0.8h
; CHECK-NO16-SD-NEXT:    fadd v1.4s, v1.4s, v1.4s
; CHECK-NO16-SD-NEXT:    fadd v0.4s, v0.4s, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtn v1.4h, v1.4s
; CHECK-NO16-SD-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-SD-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtzs v1.4s, v1.4s
; CHECK-NO16-SD-NEXT:    uzp1 v0.8h, v1.8h, v0.8h
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-LABEL: tests_v8i16_fadd:
; CHECK-FP16:       // %bb.0:
; CHECK-FP16-NEXT:    fcvtzs v0.8h, v0.8h, #1
; CHECK-FP16-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: tests_v8i16_fadd:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtl2 v2.4s, v0.8h
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fadd v0.4s, v1.4s, v0.4s
; CHECK-NO16-GI-NEXT:    fadd v1.4s, v2.4s, v2.4s
; CHECK-NO16-GI-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-GI-NEXT:    fcvtn v1.4h, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-GI-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-NO16-GI-NEXT:    fcvtzs v1.4s, v1.4s
; CHECK-NO16-GI-NEXT:    uzp1 v0.8h, v0.8h, v1.8h
; CHECK-NO16-GI-NEXT:    ret
  %mul.i = fadd <8 x half> %f, %f
  %vcvt.i = fptosi <8 x half> %mul.i to <8 x i16>
  ret <8 x i16> %vcvt.i
}

define <2 x i64> @testu_v2i64_fadd(<2 x double> %f) {
; CHECK-LABEL: testu_v2i64_fadd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzu v0.2d, v0.2d, #1
; CHECK-NEXT:    ret
  %mul.i = fadd <2 x double> %f, %f
  %vcvt.i = fptoui <2 x double> %mul.i to <2 x i64>
  ret <2 x i64> %vcvt.i
}

define <2 x i32> @testu_v2i32_fadd(<2 x float> %f) {
; CHECK-LABEL: testu_v2i32_fadd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzu v0.2s, v0.2s, #1
; CHECK-NEXT:    ret
  %mul.i = fadd <2 x float> %f, %f
  %vcvt.i = fptoui <2 x float> %mul.i to <2 x i32>
  ret <2 x i32> %vcvt.i
}

define <4 x i32> @testu_v4i32_fadd(<4 x float> %f) {
; CHECK-LABEL: testu_v4i32_fadd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzu v0.4s, v0.4s, #1
; CHECK-NEXT:    ret
  %mul.i = fadd <4 x float> %f, %f
  %vcvt.i = fptoui <4 x float> %mul.i to <4 x i32>
  ret <4 x i32> %vcvt.i
}

define <4 x i16> @testu_v2i16_fadd(<4 x half> %f) {
; CHECK-NO16-LABEL: testu_v2i16_fadd:
; CHECK-NO16:       // %bb.0:
; CHECK-NO16-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-NEXT:    fadd v0.4s, v0.4s, v0.4s
; CHECK-NO16-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-NO16-NEXT:    xtn v0.4h, v0.4s
; CHECK-NO16-NEXT:    ret
;
; CHECK-FP16-LABEL: testu_v2i16_fadd:
; CHECK-FP16:       // %bb.0:
; CHECK-FP16-NEXT:    fcvtzu v0.4h, v0.4h, #1
; CHECK-FP16-NEXT:    ret
  %mul.i = fadd <4 x half> %f, %f
  %vcvt.i = fptoui <4 x half> %mul.i to <4 x i16>
  ret <4 x i16> %vcvt.i
}

define <8 x i16> @testu_v8i16_fadd(<8 x half> %f) {
; CHECK-NO16-SD-LABEL: testu_v8i16_fadd:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fcvtl v1.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtl2 v0.4s, v0.8h
; CHECK-NO16-SD-NEXT:    fadd v1.4s, v1.4s, v1.4s
; CHECK-NO16-SD-NEXT:    fadd v0.4s, v0.4s, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtn v1.4h, v1.4s
; CHECK-NO16-SD-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-SD-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-NO16-SD-NEXT:    uzp1 v0.8h, v1.8h, v0.8h
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-LABEL: testu_v8i16_fadd:
; CHECK-FP16:       // %bb.0:
; CHECK-FP16-NEXT:    fcvtzu v0.8h, v0.8h, #1
; CHECK-FP16-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: testu_v8i16_fadd:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtl2 v2.4s, v0.8h
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fadd v0.4s, v1.4s, v0.4s
; CHECK-NO16-GI-NEXT:    fadd v1.4s, v2.4s, v2.4s
; CHECK-NO16-GI-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-GI-NEXT:    fcvtn v1.4h, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-GI-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-NO16-GI-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-NO16-GI-NEXT:    uzp1 v0.8h, v0.8h, v1.8h
; CHECK-NO16-GI-NEXT:    ret
  %mul.i = fadd <8 x half> %f, %f
  %vcvt.i = fptoui <8 x half> %mul.i to <8 x i16>
  ret <8 x i16> %vcvt.i
}






define <2 x i64> @tests_sat_v2i64_fadd(<2 x double> %f) {
; CHECK-LABEL: tests_sat_v2i64_fadd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.2d, v0.2d, #1
; CHECK-NEXT:    ret
  %mul.i = fadd <2 x double> %f, %f
  %vcvt.i = call <2 x i64> @llvm.fptosi.sat.v2i64.v2f64(<2 x double> %mul.i)
  ret <2 x i64> %vcvt.i
}

define <2 x i32> @tests_sat_v2i32_fadd(<2 x float> %f) {
; CHECK-LABEL: tests_sat_v2i32_fadd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.2s, v0.2s, #1
; CHECK-NEXT:    ret
  %mul.i = fadd <2 x float> %f, %f
  %vcvt.i = call <2 x i32> @llvm.fptosi.sat.v2i32.v2f32(<2 x float> %mul.i)
  ret <2 x i32> %vcvt.i
}

define <4 x i32> @tests_sat_v4i32_fadd(<4 x float> %f) {
; CHECK-LABEL: tests_sat_v4i32_fadd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzs v0.4s, v0.4s, #1
; CHECK-NEXT:    ret
  %mul.i = fadd <4 x float> %f, %f
  %vcvt.i = call <4 x i32> @llvm.fptosi.sat.v4i32.v4f32(<4 x float> %mul.i)
  ret <4 x i32> %vcvt.i
}

define <4 x i16> @tests_sat_v2i16_fadd(<4 x half> %f) {
; CHECK-NO16-LABEL: tests_sat_v2i16_fadd:
; CHECK-NO16:       // %bb.0:
; CHECK-NO16-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-NEXT:    fadd v0.4s, v0.4s, v0.4s
; CHECK-NO16-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-NO16-NEXT:    sqxtn v0.4h, v0.4s
; CHECK-NO16-NEXT:    ret
;
; CHECK-FP16-LABEL: tests_sat_v2i16_fadd:
; CHECK-FP16:       // %bb.0:
; CHECK-FP16-NEXT:    fcvtzs v0.4h, v0.4h, #1
; CHECK-FP16-NEXT:    ret
  %mul.i = fadd <4 x half> %f, %f
  %vcvt.i = call <4 x i16> @llvm.fptosi.sat.v4i16.v4f16(<4 x half> %mul.i)
  ret <4 x i16> %vcvt.i
}

define <8 x i16> @tests_sat_v8i16_fadd(<8 x half> %f) {
; CHECK-NO16-SD-LABEL: tests_sat_v8i16_fadd:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fcvtl v1.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtl2 v0.4s, v0.8h
; CHECK-NO16-SD-NEXT:    fadd v1.4s, v1.4s, v1.4s
; CHECK-NO16-SD-NEXT:    fadd v0.4s, v0.4s, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtn v1.4h, v1.4s
; CHECK-NO16-SD-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-SD-NEXT:    fcvtl v2.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtzs v1.4s, v1.4s
; CHECK-NO16-SD-NEXT:    sqxtn v0.4h, v1.4s
; CHECK-NO16-SD-NEXT:    fcvtzs v1.4s, v2.4s
; CHECK-NO16-SD-NEXT:    sqxtn2 v0.8h, v1.4s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-LABEL: tests_sat_v8i16_fadd:
; CHECK-FP16:       // %bb.0:
; CHECK-FP16-NEXT:    fcvtzs v0.8h, v0.8h, #1
; CHECK-FP16-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: tests_sat_v8i16_fadd:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtl v2.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtl2 v0.4s, v0.8h
; CHECK-NO16-GI-NEXT:    fadd v1.4s, v1.4s, v2.4s
; CHECK-NO16-GI-NEXT:    fadd v0.4s, v0.4s, v0.4s
; CHECK-NO16-GI-NEXT:    fcvtn v1.4h, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtzs v1.4s, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtzs v2.4s, v0.4s
; CHECK-NO16-GI-NEXT:    sqxtn v0.4h, v1.4s
; CHECK-NO16-GI-NEXT:    sqxtn2 v0.8h, v2.4s
; CHECK-NO16-GI-NEXT:    ret
  %mul.i = fadd <8 x half> %f, %f
  %vcvt.i = call <8 x i16> @llvm.fptosi.sat.v8i16.v8f16(<8 x half> %mul.i)
  ret <8 x i16> %vcvt.i
}

define <2 x i64> @testu_sat_v2i64_fadd(<2 x double> %f) {
; CHECK-LABEL: testu_sat_v2i64_fadd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzu v0.2d, v0.2d, #1
; CHECK-NEXT:    ret
  %mul.i = fadd <2 x double> %f, %f
  %vcvt.i = call <2 x i64> @llvm.fptoui.sat.v2i64.v2f64(<2 x double> %mul.i)
  ret <2 x i64> %vcvt.i
}

define <2 x i32> @testu_sat_v2i32_fadd(<2 x float> %f) {
; CHECK-LABEL: testu_sat_v2i32_fadd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzu v0.2s, v0.2s, #1
; CHECK-NEXT:    ret
  %mul.i = fadd <2 x float> %f, %f
  %vcvt.i = call <2 x i32> @llvm.fptoui.sat.v2i32.v2f32(<2 x float> %mul.i)
  ret <2 x i32> %vcvt.i
}

define <4 x i32> @testu_sat_v4i32_fadd(<4 x float> %f) {
; CHECK-LABEL: testu_sat_v4i32_fadd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcvtzu v0.4s, v0.4s, #1
; CHECK-NEXT:    ret
  %mul.i = fadd <4 x float> %f, %f
  %vcvt.i = call <4 x i32> @llvm.fptoui.sat.v4i32.v4f32(<4 x float> %mul.i)
  ret <4 x i32> %vcvt.i
}

define <4 x i16> @testu_sat_v2i16_fadd(<4 x half> %f) {
; CHECK-NO16-LABEL: testu_sat_v2i16_fadd:
; CHECK-NO16:       // %bb.0:
; CHECK-NO16-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-NEXT:    fadd v0.4s, v0.4s, v0.4s
; CHECK-NO16-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-NO16-NEXT:    uqxtn v0.4h, v0.4s
; CHECK-NO16-NEXT:    ret
;
; CHECK-FP16-LABEL: testu_sat_v2i16_fadd:
; CHECK-FP16:       // %bb.0:
; CHECK-FP16-NEXT:    fcvtzu v0.4h, v0.4h, #1
; CHECK-FP16-NEXT:    ret
  %mul.i = fadd <4 x half> %f, %f
  %vcvt.i = call <4 x i16> @llvm.fptoui.sat.v4i16.v4f16(<4 x half> %mul.i)
  ret <4 x i16> %vcvt.i
}

define <8 x i16> @testu_sat_v8i16_fadd(<8 x half> %f) {
; CHECK-NO16-SD-LABEL: testu_sat_v8i16_fadd:
; CHECK-NO16-SD:       // %bb.0:
; CHECK-NO16-SD-NEXT:    fcvtl v1.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtl2 v0.4s, v0.8h
; CHECK-NO16-SD-NEXT:    fadd v1.4s, v1.4s, v1.4s
; CHECK-NO16-SD-NEXT:    fadd v0.4s, v0.4s, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtn v1.4h, v1.4s
; CHECK-NO16-SD-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-SD-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-SD-NEXT:    fcvtl v2.4s, v0.4h
; CHECK-NO16-SD-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-NO16-SD-NEXT:    uqxtn v0.4h, v1.4s
; CHECK-NO16-SD-NEXT:    fcvtzu v1.4s, v2.4s
; CHECK-NO16-SD-NEXT:    uqxtn2 v0.8h, v1.4s
; CHECK-NO16-SD-NEXT:    ret
;
; CHECK-FP16-LABEL: testu_sat_v8i16_fadd:
; CHECK-FP16:       // %bb.0:
; CHECK-FP16-NEXT:    fcvtzu v0.8h, v0.8h, #1
; CHECK-FP16-NEXT:    ret
;
; CHECK-NO16-GI-LABEL: testu_sat_v8i16_fadd:
; CHECK-NO16-GI:       // %bb.0:
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtl v2.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtl2 v0.4s, v0.8h
; CHECK-NO16-GI-NEXT:    fadd v1.4s, v1.4s, v2.4s
; CHECK-NO16-GI-NEXT:    fadd v0.4s, v0.4s, v0.4s
; CHECK-NO16-GI-NEXT:    fcvtn v1.4h, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-NO16-GI-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NO16-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NO16-GI-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-NO16-GI-NEXT:    fcvtzu v2.4s, v0.4s
; CHECK-NO16-GI-NEXT:    uqxtn v0.4h, v1.4s
; CHECK-NO16-GI-NEXT:    uqxtn2 v0.8h, v2.4s
; CHECK-NO16-GI-NEXT:    ret
  %mul.i = fadd <8 x half> %f, %f
  %vcvt.i = call <8 x i16> @llvm.fptoui.sat.v8i16.v8f16(<8 x half> %mul.i)
  ret <8 x i16> %vcvt.i
}

