; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64--linux-gnu -mattr=+sve -mattr=+sve2p2 -enable-subreg-liveness -aarch64-sve-vector-bits-min=256 < %s | FileCheck %s --check-prefix=CHECK-EXPAND
; RUN: llc -mtriple=aarch64--linux-gnu -mattr=+sve -mattr=+sme2p2 -enable-subreg-liveness -aarch64-sve-vector-bits-min=256 < %s | FileCheck %s --check-prefix=CHECK-EXPAND
; RUN: llc -mtriple=aarch64--linux-gnu -mattr=+sve -mattr=+sme2p2 -force-streaming -enable-subreg-liveness -aarch64-sve-vector-bits-min=256 < %s | FileCheck %s --check-prefix=CHECK-EXPAND-STREAMING
; RUN: llc -mtriple=aarch64--linux-gnu -mattr=+sve2p2 -mattr=+sme-fa64 -force-streaming -enable-subreg-liveness -aarch64-sve-vector-bits-min=256 < %s | FileCheck %s --check-prefix=CHECK-EXPAND

; RUN: llc -mtriple=aarch64--linux-gnu -mattr=+sve2p2 -mattr=+sme -force-streaming -enable-subreg-liveness -aarch64-sve-vector-bits-min=256 < %s | FileCheck %s --check-prefix=CHECK-NO-EXPAND-STREAMING
; RUN: llc -mtriple=aarch64--linux-gnu -mattr=+sme2p2 -enable-subreg-liveness -aarch64-sve-vector-bits-min=256 < %s | FileCheck %s --check-prefix=CHECK-NO-SVE
; RUN: llc -mtriple=aarch64--linux-gnu -mattr=+sve -mattr=+sve2p2 -enable-subreg-liveness < %s | FileCheck %s --check-prefix=CHECK-USE-NEON

define <2 x i64> @test_fixed_expandload(ptr %base, <2 x i64> %passthru, <2 x i1> %pred) {
; CHECK-EXPAND-LABEL: test_fixed_expandload:
; CHECK-EXPAND:       // %bb.0:
; CHECK-EXPAND-NEXT:    ushll v1.2d, v1.2s, #0
; CHECK-EXPAND-NEXT:    ptrue p0.d, vl2
; CHECK-EXPAND-NEXT:    shl v1.2d, v1.2d, #63
; CHECK-EXPAND-NEXT:    cmpne p0.d, p0/z, z1.d, #0
; CHECK-EXPAND-NEXT:    cntp x8, p0, p0.d
; CHECK-EXPAND-NEXT:    whilelo p1.d, xzr, x8
; CHECK-EXPAND-NEXT:    ld1d { z1.d }, p1/z, [x0]
; CHECK-EXPAND-NEXT:    expand z1.d, p0, z1.d
; CHECK-EXPAND-NEXT:    mov z0.d, p0/m, z1.d
; CHECK-EXPAND-NEXT:    ret
;
; CHECK-EXPAND-STREAMING-LABEL: test_fixed_expandload:
; CHECK-EXPAND-STREAMING:       // %bb.0:
; CHECK-EXPAND-STREAMING-NEXT:    uunpklo z1.d, z1.s
; CHECK-EXPAND-STREAMING-NEXT:    ptrue p0.d, vl2
; CHECK-EXPAND-STREAMING-NEXT:    lsl z1.d, z1.d, #63
; CHECK-EXPAND-STREAMING-NEXT:    asr z1.d, z1.d, #63
; CHECK-EXPAND-STREAMING-NEXT:    cmpne p0.d, p0/z, z1.d, #0
; CHECK-EXPAND-STREAMING-NEXT:    cntp x8, p0, p0.d
; CHECK-EXPAND-STREAMING-NEXT:    whilelo p1.d, xzr, x8
; CHECK-EXPAND-STREAMING-NEXT:    ld1d { z1.d }, p1/z, [x0]
; CHECK-EXPAND-STREAMING-NEXT:    expand z1.d, p0, z1.d
; CHECK-EXPAND-STREAMING-NEXT:    mov z0.d, p0/m, z1.d
; CHECK-EXPAND-STREAMING-NEXT:    ret
;
; CHECK-NO-EXPAND-STREAMING-LABEL: test_fixed_expandload:
; CHECK-NO-EXPAND-STREAMING:       // %bb.0:
; CHECK-NO-EXPAND-STREAMING-NEXT:    sub sp, sp, #16
; CHECK-NO-EXPAND-STREAMING-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NO-EXPAND-STREAMING-NEXT:    lsl z1.s, z1.s, #31
; CHECK-NO-EXPAND-STREAMING-NEXT:    index z2.s, #1, #1
; CHECK-NO-EXPAND-STREAMING-NEXT:    ptrue p0.s, vl2
; CHECK-NO-EXPAND-STREAMING-NEXT:    asr z1.s, z1.s, #31
; CHECK-NO-EXPAND-STREAMING-NEXT:    and z1.d, z1.d, z2.d
; CHECK-NO-EXPAND-STREAMING-NEXT:    uaddv d1, p0, z1.s
; CHECK-NO-EXPAND-STREAMING-NEXT:    str b1, [sp, #12]
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldrb w8, [sp, #12]
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbnz w8, #0, .LBB0_3
; CHECK-NO-EXPAND-STREAMING-NEXT:  // %bb.1: // %else
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbnz w8, #1, .LBB0_4
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB0_2: // %else2
; CHECK-NO-EXPAND-STREAMING-NEXT:    add sp, sp, #16
; CHECK-NO-EXPAND-STREAMING-NEXT:    ret
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB0_3: // %cond.load
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldr x9, [x0], #8
; CHECK-NO-EXPAND-STREAMING-NEXT:    ptrue p0.d, vl1
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z0.d, p0/m, x9
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbz w8, #1, .LBB0_2
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB0_4: // %cond.load1
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov w8, #1 // =0x1
; CHECK-NO-EXPAND-STREAMING-NEXT:    index z1.d, #0, #1
; CHECK-NO-EXPAND-STREAMING-NEXT:    ptrue p0.d
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z2.d, x8
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldr x8, [x0]
; CHECK-NO-EXPAND-STREAMING-NEXT:    cmpeq p0.d, p0/z, z1.d, z2.d
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z0.d, p0/m, x8
; CHECK-NO-EXPAND-STREAMING-NEXT:    add sp, sp, #16
; CHECK-NO-EXPAND-STREAMING-NEXT:    ret
;
; CHECK-NO-SVE-LABEL: test_fixed_expandload:
; CHECK-NO-SVE:       // %bb.0:
; CHECK-NO-SVE-NEXT:    shl v1.2s, v1.2s, #31
; CHECK-NO-SVE-NEXT:    mov x8, #1 // =0x1
; CHECK-NO-SVE-NEXT:    movk x8, #2, lsl #32
; CHECK-NO-SVE-NEXT:    fmov d2, x8
; CHECK-NO-SVE-NEXT:    cmlt v1.2s, v1.2s, #0
; CHECK-NO-SVE-NEXT:    and v1.8b, v1.8b, v2.8b
; CHECK-NO-SVE-NEXT:    addp v1.2s, v1.2s, v1.2s
; CHECK-NO-SVE-NEXT:    fmov w8, s1
; CHECK-NO-SVE-NEXT:    tbnz w8, #0, .LBB0_3
; CHECK-NO-SVE-NEXT:  // %bb.1: // %else
; CHECK-NO-SVE-NEXT:    tbnz w8, #1, .LBB0_4
; CHECK-NO-SVE-NEXT:  .LBB0_2: // %else2
; CHECK-NO-SVE-NEXT:    ret
; CHECK-NO-SVE-NEXT:  .LBB0_3: // %cond.load
; CHECK-NO-SVE-NEXT:    ld1 { v0.d }[0], [x0], #8
; CHECK-NO-SVE-NEXT:    tbz w8, #1, .LBB0_2
; CHECK-NO-SVE-NEXT:  .LBB0_4: // %cond.load1
; CHECK-NO-SVE-NEXT:    ld1 { v0.d }[1], [x0]
; CHECK-NO-SVE-NEXT:    ret
;
; CHECK-USE-NEON-LABEL: test_fixed_expandload:
; CHECK-USE-NEON:       // %bb.0:
; CHECK-USE-NEON-NEXT:    shl v1.2s, v1.2s, #31
; CHECK-USE-NEON-NEXT:    index z2.s, #1, #1
; CHECK-USE-NEON-NEXT:    cmlt v1.2s, v1.2s, #0
; CHECK-USE-NEON-NEXT:    and v1.8b, v1.8b, v2.8b
; CHECK-USE-NEON-NEXT:    addp v1.2s, v1.2s, v1.2s
; CHECK-USE-NEON-NEXT:    fmov w8, s1
; CHECK-USE-NEON-NEXT:    tbnz w8, #0, .LBB0_3
; CHECK-USE-NEON-NEXT:  // %bb.1: // %else
; CHECK-USE-NEON-NEXT:    tbnz w8, #1, .LBB0_4
; CHECK-USE-NEON-NEXT:  .LBB0_2: // %else2
; CHECK-USE-NEON-NEXT:    ret
; CHECK-USE-NEON-NEXT:  .LBB0_3: // %cond.load
; CHECK-USE-NEON-NEXT:    ld1 { v0.d }[0], [x0], #8
; CHECK-USE-NEON-NEXT:    tbz w8, #1, .LBB0_2
; CHECK-USE-NEON-NEXT:  .LBB0_4: // %cond.load1
; CHECK-USE-NEON-NEXT:    ld1 { v0.d }[1], [x0]
; CHECK-USE-NEON-NEXT:    ret
  %res = call <2 x i64> @llvm.masked.expandload(ptr align 1 %base, <2 x i1> %pred, <2 x i64> %passthru)
  ret <2 x i64> %res
}

define <4 x double> @test_split_fixed_expandload(ptr %base, <4 x double> %passthru, <4 x i1> %pred) {
; CHECK-EXPAND-LABEL: test_split_fixed_expandload:
; CHECK-EXPAND:       // %bb.0:
; CHECK-EXPAND-NEXT:    uunpklo z2.s, z2.h
; CHECK-EXPAND-NEXT:    ptrue p0.d, vl4
; CHECK-EXPAND-NEXT:    ptrue p1.d, vl2
; CHECK-EXPAND-NEXT:    splice z0.d, p1, { z0.d, z1.d }
; CHECK-EXPAND-NEXT:    uunpklo z2.d, z2.s
; CHECK-EXPAND-NEXT:    lsl z2.d, z2.d, #63
; CHECK-EXPAND-NEXT:    asr z2.d, z2.d, #63
; CHECK-EXPAND-NEXT:    cmpne p0.d, p0/z, z2.d, #0
; CHECK-EXPAND-NEXT:    cntp x8, p0, p0.d
; CHECK-EXPAND-NEXT:    whilelo p2.d, xzr, x8
; CHECK-EXPAND-NEXT:    ld1d { z1.d }, p2/z, [x0]
; CHECK-EXPAND-NEXT:    expand z1.d, p0, z1.d
; CHECK-EXPAND-NEXT:    mov z0.d, p0/m, z1.d
; CHECK-EXPAND-NEXT:    movprfx z1, z0
; CHECK-EXPAND-NEXT:    ext z1.b, z1.b, z0.b, #16
; CHECK-EXPAND-NEXT:    ret
;
; CHECK-EXPAND-STREAMING-LABEL: test_split_fixed_expandload:
; CHECK-EXPAND-STREAMING:       // %bb.0:
; CHECK-EXPAND-STREAMING-NEXT:    uunpklo z2.s, z2.h
; CHECK-EXPAND-STREAMING-NEXT:    ptrue p0.d, vl4
; CHECK-EXPAND-STREAMING-NEXT:    ptrue p1.d, vl2
; CHECK-EXPAND-STREAMING-NEXT:    splice z0.d, p1, { z0.d, z1.d }
; CHECK-EXPAND-STREAMING-NEXT:    uunpklo z2.d, z2.s
; CHECK-EXPAND-STREAMING-NEXT:    lsl z2.d, z2.d, #63
; CHECK-EXPAND-STREAMING-NEXT:    asr z2.d, z2.d, #63
; CHECK-EXPAND-STREAMING-NEXT:    cmpne p0.d, p0/z, z2.d, #0
; CHECK-EXPAND-STREAMING-NEXT:    cntp x8, p0, p0.d
; CHECK-EXPAND-STREAMING-NEXT:    whilelo p2.d, xzr, x8
; CHECK-EXPAND-STREAMING-NEXT:    ld1d { z1.d }, p2/z, [x0]
; CHECK-EXPAND-STREAMING-NEXT:    expand z1.d, p0, z1.d
; CHECK-EXPAND-STREAMING-NEXT:    mov z0.d, p0/m, z1.d
; CHECK-EXPAND-STREAMING-NEXT:    movprfx z1, z0
; CHECK-EXPAND-STREAMING-NEXT:    ext z1.b, z1.b, z0.b, #16
; CHECK-EXPAND-STREAMING-NEXT:    ret
;
; CHECK-NO-EXPAND-STREAMING-LABEL: test_split_fixed_expandload:
; CHECK-NO-EXPAND-STREAMING:       // %bb.0:
; CHECK-NO-EXPAND-STREAMING-NEXT:    sub sp, sp, #16
; CHECK-NO-EXPAND-STREAMING-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NO-EXPAND-STREAMING-NEXT:    lsl z2.h, z2.h, #15
; CHECK-NO-EXPAND-STREAMING-NEXT:    adrp x8, .LCPI1_0
; CHECK-NO-EXPAND-STREAMING-NEXT:    ptrue p0.h, vl4
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldr d3, [x8, :lo12:.LCPI1_0]
; CHECK-NO-EXPAND-STREAMING-NEXT:    asr z2.h, z2.h, #15
; CHECK-NO-EXPAND-STREAMING-NEXT:    and z2.d, z2.d, z3.d
; CHECK-NO-EXPAND-STREAMING-NEXT:    uaddv d2, p0, z2.h
; CHECK-NO-EXPAND-STREAMING-NEXT:    ptrue p0.d, vl2
; CHECK-NO-EXPAND-STREAMING-NEXT:    splice z0.d, p0, { z0.d, z1.d }
; CHECK-NO-EXPAND-STREAMING-NEXT:    str b2, [sp, #12]
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldrb w8, [sp, #12]
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbnz w8, #0, .LBB1_6
; CHECK-NO-EXPAND-STREAMING-NEXT:  // %bb.1: // %else
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbnz w8, #1, .LBB1_7
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB1_2: // %else2
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbnz w8, #2, .LBB1_8
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB1_3: // %else6
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbz w8, #3, .LBB1_5
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB1_4: // %cond.load9
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov w8, #3 // =0x3
; CHECK-NO-EXPAND-STREAMING-NEXT:    index z1.d, #0, #1
; CHECK-NO-EXPAND-STREAMING-NEXT:    ptrue p0.d
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z2.d, x8
; CHECK-NO-EXPAND-STREAMING-NEXT:    cmpeq p0.d, p0/z, z1.d, z2.d
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldr d1, [x0]
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z0.d, p0/m, d1
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB1_5: // %else10
; CHECK-NO-EXPAND-STREAMING-NEXT:    movprfx z1, z0
; CHECK-NO-EXPAND-STREAMING-NEXT:    ext z1.b, z1.b, z0.b, #16
; CHECK-NO-EXPAND-STREAMING-NEXT:    add sp, sp, #16
; CHECK-NO-EXPAND-STREAMING-NEXT:    ret
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB1_6: // %cond.load
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldr d1, [x0], #8
; CHECK-NO-EXPAND-STREAMING-NEXT:    ptrue p0.d, vl1
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z0.d, p0/m, z1.d
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbz w8, #1, .LBB1_2
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB1_7: // %cond.load1
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov w9, #1 // =0x1
; CHECK-NO-EXPAND-STREAMING-NEXT:    index z1.d, #0, #1
; CHECK-NO-EXPAND-STREAMING-NEXT:    ptrue p0.d
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z2.d, x9
; CHECK-NO-EXPAND-STREAMING-NEXT:    cmpeq p0.d, p0/z, z1.d, z2.d
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldr d1, [x0], #8
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z0.d, p0/m, d1
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbz w8, #2, .LBB1_3
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB1_8: // %cond.load5
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov w9, #2 // =0x2
; CHECK-NO-EXPAND-STREAMING-NEXT:    index z1.d, #0, #1
; CHECK-NO-EXPAND-STREAMING-NEXT:    ptrue p0.d
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z2.d, x9
; CHECK-NO-EXPAND-STREAMING-NEXT:    cmpeq p0.d, p0/z, z1.d, z2.d
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldr d1, [x0], #8
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z0.d, p0/m, d1
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbnz w8, #3, .LBB1_4
; CHECK-NO-EXPAND-STREAMING-NEXT:    b .LBB1_5
;
; CHECK-NO-SVE-LABEL: test_split_fixed_expandload:
; CHECK-NO-SVE:       // %bb.0:
; CHECK-NO-SVE-NEXT:    shl v2.4h, v2.4h, #15
; CHECK-NO-SVE-NEXT:    adrp x8, .LCPI1_0
; CHECK-NO-SVE-NEXT:    ldr d3, [x8, :lo12:.LCPI1_0]
; CHECK-NO-SVE-NEXT:    cmlt v2.4h, v2.4h, #0
; CHECK-NO-SVE-NEXT:    and v2.8b, v2.8b, v3.8b
; CHECK-NO-SVE-NEXT:    addv h2, v2.4h
; CHECK-NO-SVE-NEXT:    fmov w8, s2
; CHECK-NO-SVE-NEXT:    tbnz w8, #0, .LBB1_5
; CHECK-NO-SVE-NEXT:  // %bb.1: // %else
; CHECK-NO-SVE-NEXT:    tbnz w8, #1, .LBB1_6
; CHECK-NO-SVE-NEXT:  .LBB1_2: // %else2
; CHECK-NO-SVE-NEXT:    tbnz w8, #2, .LBB1_7
; CHECK-NO-SVE-NEXT:  .LBB1_3: // %else6
; CHECK-NO-SVE-NEXT:    tbnz w8, #3, .LBB1_8
; CHECK-NO-SVE-NEXT:  .LBB1_4: // %else10
; CHECK-NO-SVE-NEXT:    ret
; CHECK-NO-SVE-NEXT:  .LBB1_5: // %cond.load
; CHECK-NO-SVE-NEXT:    ld1 { v0.d }[0], [x0], #8
; CHECK-NO-SVE-NEXT:    tbz w8, #1, .LBB1_2
; CHECK-NO-SVE-NEXT:  .LBB1_6: // %cond.load1
; CHECK-NO-SVE-NEXT:    ld1 { v0.d }[1], [x0], #8
; CHECK-NO-SVE-NEXT:    tbz w8, #2, .LBB1_3
; CHECK-NO-SVE-NEXT:  .LBB1_7: // %cond.load5
; CHECK-NO-SVE-NEXT:    ld1 { v1.d }[0], [x0], #8
; CHECK-NO-SVE-NEXT:    tbz w8, #3, .LBB1_4
; CHECK-NO-SVE-NEXT:  .LBB1_8: // %cond.load9
; CHECK-NO-SVE-NEXT:    ld1 { v1.d }[1], [x0]
; CHECK-NO-SVE-NEXT:    ret
;
; CHECK-USE-NEON-LABEL: test_split_fixed_expandload:
; CHECK-USE-NEON:       // %bb.0:
; CHECK-USE-NEON-NEXT:    shl v2.4h, v2.4h, #15
; CHECK-USE-NEON-NEXT:    adrp x8, .LCPI1_0
; CHECK-USE-NEON-NEXT:    ldr d3, [x8, :lo12:.LCPI1_0]
; CHECK-USE-NEON-NEXT:    cmlt v2.4h, v2.4h, #0
; CHECK-USE-NEON-NEXT:    and v2.8b, v2.8b, v3.8b
; CHECK-USE-NEON-NEXT:    addv h2, v2.4h
; CHECK-USE-NEON-NEXT:    fmov w8, s2
; CHECK-USE-NEON-NEXT:    tbnz w8, #0, .LBB1_5
; CHECK-USE-NEON-NEXT:  // %bb.1: // %else
; CHECK-USE-NEON-NEXT:    tbnz w8, #1, .LBB1_6
; CHECK-USE-NEON-NEXT:  .LBB1_2: // %else2
; CHECK-USE-NEON-NEXT:    tbnz w8, #2, .LBB1_7
; CHECK-USE-NEON-NEXT:  .LBB1_3: // %else6
; CHECK-USE-NEON-NEXT:    tbnz w8, #3, .LBB1_8
; CHECK-USE-NEON-NEXT:  .LBB1_4: // %else10
; CHECK-USE-NEON-NEXT:    ret
; CHECK-USE-NEON-NEXT:  .LBB1_5: // %cond.load
; CHECK-USE-NEON-NEXT:    ld1 { v0.d }[0], [x0], #8
; CHECK-USE-NEON-NEXT:    tbz w8, #1, .LBB1_2
; CHECK-USE-NEON-NEXT:  .LBB1_6: // %cond.load1
; CHECK-USE-NEON-NEXT:    ld1 { v0.d }[1], [x0], #8
; CHECK-USE-NEON-NEXT:    tbz w8, #2, .LBB1_3
; CHECK-USE-NEON-NEXT:  .LBB1_7: // %cond.load5
; CHECK-USE-NEON-NEXT:    ld1 { v1.d }[0], [x0], #8
; CHECK-USE-NEON-NEXT:    tbz w8, #3, .LBB1_4
; CHECK-USE-NEON-NEXT:  .LBB1_8: // %cond.load9
; CHECK-USE-NEON-NEXT:    ld1 { v1.d }[1], [x0]
; CHECK-USE-NEON-NEXT:    ret
  %res = call <4 x double> @llvm.masked.expandload(ptr align 1 %base, <4 x i1> %pred, <4 x double> %passthru)
  ret <4 x double> %res
}

define <3 x i32> @test_widen_fixed_expandload(ptr %base, <3 x i32> %passthru, <3 x i1> %pred) {
; CHECK-EXPAND-LABEL: test_widen_fixed_expandload:
; CHECK-EXPAND:       // %bb.0:
; CHECK-EXPAND-NEXT:    movi v1.2d, #0000000000000000
; CHECK-EXPAND-NEXT:    ptrue p0.s, vl4
; CHECK-EXPAND-NEXT:    mov v1.h[0], w1
; CHECK-EXPAND-NEXT:    mov v1.h[1], w2
; CHECK-EXPAND-NEXT:    mov v1.h[2], w3
; CHECK-EXPAND-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-EXPAND-NEXT:    shl v1.4s, v1.4s, #31
; CHECK-EXPAND-NEXT:    cmpne p0.s, p0/z, z1.s, #0
; CHECK-EXPAND-NEXT:    cntp x8, p0, p0.s
; CHECK-EXPAND-NEXT:    whilelo p1.s, xzr, x8
; CHECK-EXPAND-NEXT:    ld1w { z1.s }, p1/z, [x0]
; CHECK-EXPAND-NEXT:    expand z1.s, p0, z1.s
; CHECK-EXPAND-NEXT:    mov z0.s, p0/m, z1.s
; CHECK-EXPAND-NEXT:    ret
;
; CHECK-EXPAND-STREAMING-LABEL: test_widen_fixed_expandload:
; CHECK-EXPAND-STREAMING:       // %bb.0:
; CHECK-EXPAND-STREAMING-NEXT:    fmov s1, w2
; CHECK-EXPAND-STREAMING-NEXT:    fmov s2, w1
; CHECK-EXPAND-STREAMING-NEXT:    adrp x8, .LCPI2_0
; CHECK-EXPAND-STREAMING-NEXT:    ptrue p0.s, vl4
; CHECK-EXPAND-STREAMING-NEXT:    zip1 z1.h, z2.h, z1.h
; CHECK-EXPAND-STREAMING-NEXT:    fmov s2, w3
; CHECK-EXPAND-STREAMING-NEXT:    zip1 z1.s, z1.s, z2.s
; CHECK-EXPAND-STREAMING-NEXT:    ldr d2, [x8, :lo12:.LCPI2_0]
; CHECK-EXPAND-STREAMING-NEXT:    and z1.d, z1.d, z2.d
; CHECK-EXPAND-STREAMING-NEXT:    uunpklo z1.s, z1.h
; CHECK-EXPAND-STREAMING-NEXT:    lsl z1.s, z1.s, #31
; CHECK-EXPAND-STREAMING-NEXT:    asr z1.s, z1.s, #31
; CHECK-EXPAND-STREAMING-NEXT:    cmpne p0.s, p0/z, z1.s, #0
; CHECK-EXPAND-STREAMING-NEXT:    cntp x8, p0, p0.s
; CHECK-EXPAND-STREAMING-NEXT:    whilelo p1.s, xzr, x8
; CHECK-EXPAND-STREAMING-NEXT:    ld1w { z1.s }, p1/z, [x0]
; CHECK-EXPAND-STREAMING-NEXT:    expand z1.s, p0, z1.s
; CHECK-EXPAND-STREAMING-NEXT:    mov z0.s, p0/m, z1.s
; CHECK-EXPAND-STREAMING-NEXT:    ret
;
; CHECK-NO-EXPAND-STREAMING-LABEL: test_widen_fixed_expandload:
; CHECK-NO-EXPAND-STREAMING:       // %bb.0:
; CHECK-NO-EXPAND-STREAMING-NEXT:    sub sp, sp, #16
; CHECK-NO-EXPAND-STREAMING-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NO-EXPAND-STREAMING-NEXT:    and w8, w1, #0x1
; CHECK-NO-EXPAND-STREAMING-NEXT:    bfi w8, w2, #1, #1
; CHECK-NO-EXPAND-STREAMING-NEXT:    bfi w8, w3, #2, #1
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbnz w8, #0, .LBB2_4
; CHECK-NO-EXPAND-STREAMING-NEXT:  // %bb.1: // %else
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbnz w8, #1, .LBB2_5
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB2_2: // %else2
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbnz w8, #2, .LBB2_6
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB2_3: // %else6
; CHECK-NO-EXPAND-STREAMING-NEXT:    add sp, sp, #16
; CHECK-NO-EXPAND-STREAMING-NEXT:    ret
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB2_4: // %cond.load
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldr w9, [x0], #4
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z1.s, z0.s[1]
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z0.s, z0.s[2]
; CHECK-NO-EXPAND-STREAMING-NEXT:    fmov s2, w9
; CHECK-NO-EXPAND-STREAMING-NEXT:    zip1 z1.s, z2.s, z1.s
; CHECK-NO-EXPAND-STREAMING-NEXT:    zip1 z0.d, z1.d, z0.d
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbz w8, #1, .LBB2_2
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB2_5: // %cond.load1
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldr w9, [x0], #4
; CHECK-NO-EXPAND-STREAMING-NEXT:    fmov s1, w9
; CHECK-NO-EXPAND-STREAMING-NEXT:    zip1 z1.s, z0.s, z1.s
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z0.s, z0.s[2]
; CHECK-NO-EXPAND-STREAMING-NEXT:    zip1 z0.d, z1.d, z0.d
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbz w8, #2, .LBB2_3
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB2_6: // %cond.load5
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z1.s, z0.s[1]
; CHECK-NO-EXPAND-STREAMING-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldr s1, [x0]
; CHECK-NO-EXPAND-STREAMING-NEXT:    zip1 z0.d, z0.d, z1.d
; CHECK-NO-EXPAND-STREAMING-NEXT:    add sp, sp, #16
; CHECK-NO-EXPAND-STREAMING-NEXT:    ret
;
; CHECK-NO-SVE-LABEL: test_widen_fixed_expandload:
; CHECK-NO-SVE:       // %bb.0:
; CHECK-NO-SVE-NEXT:    sub sp, sp, #16
; CHECK-NO-SVE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NO-SVE-NEXT:    and w8, w1, #0x1
; CHECK-NO-SVE-NEXT:    bfi w8, w2, #1, #1
; CHECK-NO-SVE-NEXT:    bfi w8, w3, #2, #1
; CHECK-NO-SVE-NEXT:    tbnz w8, #0, .LBB2_4
; CHECK-NO-SVE-NEXT:  // %bb.1: // %else
; CHECK-NO-SVE-NEXT:    tbnz w8, #1, .LBB2_5
; CHECK-NO-SVE-NEXT:  .LBB2_2: // %else2
; CHECK-NO-SVE-NEXT:    tbnz w8, #2, .LBB2_6
; CHECK-NO-SVE-NEXT:  .LBB2_3: // %else6
; CHECK-NO-SVE-NEXT:    add sp, sp, #16
; CHECK-NO-SVE-NEXT:    ret
; CHECK-NO-SVE-NEXT:  .LBB2_4: // %cond.load
; CHECK-NO-SVE-NEXT:    ldr w9, [x0], #4
; CHECK-NO-SVE-NEXT:    fmov s1, w9
; CHECK-NO-SVE-NEXT:    mov v1.s[1], v0.s[1]
; CHECK-NO-SVE-NEXT:    mov v1.s[2], v0.s[2]
; CHECK-NO-SVE-NEXT:    mov v0.16b, v1.16b
; CHECK-NO-SVE-NEXT:    tbz w8, #1, .LBB2_2
; CHECK-NO-SVE-NEXT:  .LBB2_5: // %cond.load1
; CHECK-NO-SVE-NEXT:    mov v1.16b, v0.16b
; CHECK-NO-SVE-NEXT:    ld1 { v1.s }[1], [x0], #4
; CHECK-NO-SVE-NEXT:    mov v1.s[2], v0.s[2]
; CHECK-NO-SVE-NEXT:    mov v0.16b, v1.16b
; CHECK-NO-SVE-NEXT:    tbz w8, #2, .LBB2_3
; CHECK-NO-SVE-NEXT:  .LBB2_6: // %cond.load5
; CHECK-NO-SVE-NEXT:    ld1 { v0.s }[2], [x0]
; CHECK-NO-SVE-NEXT:    add sp, sp, #16
; CHECK-NO-SVE-NEXT:    ret
;
; CHECK-USE-NEON-LABEL: test_widen_fixed_expandload:
; CHECK-USE-NEON:       // %bb.0:
; CHECK-USE-NEON-NEXT:    sub sp, sp, #16
; CHECK-USE-NEON-NEXT:    .cfi_def_cfa_offset 16
; CHECK-USE-NEON-NEXT:    and w8, w1, #0x1
; CHECK-USE-NEON-NEXT:    bfi w8, w2, #1, #1
; CHECK-USE-NEON-NEXT:    bfi w8, w3, #2, #1
; CHECK-USE-NEON-NEXT:    tbnz w8, #0, .LBB2_4
; CHECK-USE-NEON-NEXT:  // %bb.1: // %else
; CHECK-USE-NEON-NEXT:    tbnz w8, #1, .LBB2_5
; CHECK-USE-NEON-NEXT:  .LBB2_2: // %else2
; CHECK-USE-NEON-NEXT:    tbnz w8, #2, .LBB2_6
; CHECK-USE-NEON-NEXT:  .LBB2_3: // %else6
; CHECK-USE-NEON-NEXT:    add sp, sp, #16
; CHECK-USE-NEON-NEXT:    ret
; CHECK-USE-NEON-NEXT:  .LBB2_4: // %cond.load
; CHECK-USE-NEON-NEXT:    ldr w9, [x0], #4
; CHECK-USE-NEON-NEXT:    fmov s1, w9
; CHECK-USE-NEON-NEXT:    mov v1.s[1], v0.s[1]
; CHECK-USE-NEON-NEXT:    mov v1.s[2], v0.s[2]
; CHECK-USE-NEON-NEXT:    mov v0.16b, v1.16b
; CHECK-USE-NEON-NEXT:    tbz w8, #1, .LBB2_2
; CHECK-USE-NEON-NEXT:  .LBB2_5: // %cond.load1
; CHECK-USE-NEON-NEXT:    mov v1.16b, v0.16b
; CHECK-USE-NEON-NEXT:    ld1 { v1.s }[1], [x0], #4
; CHECK-USE-NEON-NEXT:    mov v1.s[2], v0.s[2]
; CHECK-USE-NEON-NEXT:    mov v0.16b, v1.16b
; CHECK-USE-NEON-NEXT:    tbz w8, #2, .LBB2_3
; CHECK-USE-NEON-NEXT:  .LBB2_6: // %cond.load5
; CHECK-USE-NEON-NEXT:    ld1 { v0.s }[2], [x0]
; CHECK-USE-NEON-NEXT:    add sp, sp, #16
; CHECK-USE-NEON-NEXT:    ret
  %res = call <3 x i32> @llvm.masked.expandload(ptr align 1 %base, <3 x i1> %pred, <3 x i32> %passthru)
  ret <3 x i32> %res
}

define <4 x i8> @test_promote_fixed_expandload(ptr %base, <4 x i8> %passthru, <4 x i1> %pred) {
; CHECK-EXPAND-LABEL: test_promote_fixed_expandload:
; CHECK-EXPAND:       // %bb.0:
; CHECK-EXPAND-NEXT:    shl v1.4h, v1.4h, #15
; CHECK-EXPAND-NEXT:    ptrue p0.h, vl4
; CHECK-EXPAND-NEXT:    cmpne p0.h, p0/z, z1.h, #0
; CHECK-EXPAND-NEXT:    cntp x8, p0, p0.h
; CHECK-EXPAND-NEXT:    whilelo p1.h, xzr, x8
; CHECK-EXPAND-NEXT:    ld1b { z1.h }, p1/z, [x0]
; CHECK-EXPAND-NEXT:    expand z1.h, p0, z1.h
; CHECK-EXPAND-NEXT:    mov z0.h, p0/m, z1.h
; CHECK-EXPAND-NEXT:    ret
;
; CHECK-EXPAND-STREAMING-LABEL: test_promote_fixed_expandload:
; CHECK-EXPAND-STREAMING:       // %bb.0:
; CHECK-EXPAND-STREAMING-NEXT:    lsl z1.h, z1.h, #15
; CHECK-EXPAND-STREAMING-NEXT:    ptrue p0.h, vl4
; CHECK-EXPAND-STREAMING-NEXT:    asr z1.h, z1.h, #15
; CHECK-EXPAND-STREAMING-NEXT:    cmpne p0.h, p0/z, z1.h, #0
; CHECK-EXPAND-STREAMING-NEXT:    cntp x8, p0, p0.h
; CHECK-EXPAND-STREAMING-NEXT:    whilelo p1.h, xzr, x8
; CHECK-EXPAND-STREAMING-NEXT:    ld1b { z1.h }, p1/z, [x0]
; CHECK-EXPAND-STREAMING-NEXT:    expand z1.h, p0, z1.h
; CHECK-EXPAND-STREAMING-NEXT:    mov z0.h, p0/m, z1.h
; CHECK-EXPAND-STREAMING-NEXT:    ret
;
; CHECK-NO-EXPAND-STREAMING-LABEL: test_promote_fixed_expandload:
; CHECK-NO-EXPAND-STREAMING:       // %bb.0:
; CHECK-NO-EXPAND-STREAMING-NEXT:    sub sp, sp, #16
; CHECK-NO-EXPAND-STREAMING-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NO-EXPAND-STREAMING-NEXT:    lsl z1.h, z1.h, #15
; CHECK-NO-EXPAND-STREAMING-NEXT:    adrp x8, .LCPI3_0
; CHECK-NO-EXPAND-STREAMING-NEXT:    ptrue p0.h, vl4
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldr d2, [x8, :lo12:.LCPI3_0]
; CHECK-NO-EXPAND-STREAMING-NEXT:    asr z1.h, z1.h, #15
; CHECK-NO-EXPAND-STREAMING-NEXT:    and z1.d, z1.d, z2.d
; CHECK-NO-EXPAND-STREAMING-NEXT:    uaddv d1, p0, z1.h
; CHECK-NO-EXPAND-STREAMING-NEXT:    str b1, [sp, #12]
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldrb w8, [sp, #12]
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbnz w8, #0, .LBB3_5
; CHECK-NO-EXPAND-STREAMING-NEXT:  // %bb.1: // %else
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbnz w8, #1, .LBB3_6
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB3_2: // %else2
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbnz w8, #2, .LBB3_7
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB3_3: // %else6
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbnz w8, #3, .LBB3_8
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB3_4: // %else10
; CHECK-NO-EXPAND-STREAMING-NEXT:    add sp, sp, #16
; CHECK-NO-EXPAND-STREAMING-NEXT:    ret
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB3_5: // %cond.load
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldrb w9, [x0], #1
; CHECK-NO-EXPAND-STREAMING-NEXT:    ptrue p0.h, vl1
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z0.h, p0/m, w9
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbz w8, #1, .LBB3_2
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB3_6: // %cond.load1
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov w9, #1 // =0x1
; CHECK-NO-EXPAND-STREAMING-NEXT:    index z1.h, #0, #1
; CHECK-NO-EXPAND-STREAMING-NEXT:    ptrue p0.h
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z2.h, w9
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldrb w9, [x0], #1
; CHECK-NO-EXPAND-STREAMING-NEXT:    cmpeq p0.h, p0/z, z1.h, z2.h
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z0.h, p0/m, w9
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbz w8, #2, .LBB3_3
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB3_7: // %cond.load5
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov w9, #2 // =0x2
; CHECK-NO-EXPAND-STREAMING-NEXT:    index z1.h, #0, #1
; CHECK-NO-EXPAND-STREAMING-NEXT:    ptrue p0.h
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z2.h, w9
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldrb w9, [x0], #1
; CHECK-NO-EXPAND-STREAMING-NEXT:    cmpeq p0.h, p0/z, z1.h, z2.h
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z0.h, p0/m, w9
; CHECK-NO-EXPAND-STREAMING-NEXT:    tbz w8, #3, .LBB3_4
; CHECK-NO-EXPAND-STREAMING-NEXT:  .LBB3_8: // %cond.load9
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov w8, #3 // =0x3
; CHECK-NO-EXPAND-STREAMING-NEXT:    index z1.h, #0, #1
; CHECK-NO-EXPAND-STREAMING-NEXT:    ptrue p0.h
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z2.h, w8
; CHECK-NO-EXPAND-STREAMING-NEXT:    ldrb w8, [x0]
; CHECK-NO-EXPAND-STREAMING-NEXT:    cmpeq p0.h, p0/z, z1.h, z2.h
; CHECK-NO-EXPAND-STREAMING-NEXT:    mov z0.h, p0/m, w8
; CHECK-NO-EXPAND-STREAMING-NEXT:    add sp, sp, #16
; CHECK-NO-EXPAND-STREAMING-NEXT:    ret
;
; CHECK-NO-SVE-LABEL: test_promote_fixed_expandload:
; CHECK-NO-SVE:       // %bb.0:
; CHECK-NO-SVE-NEXT:    shl v1.4h, v1.4h, #15
; CHECK-NO-SVE-NEXT:    adrp x8, .LCPI3_0
; CHECK-NO-SVE-NEXT:    ldr d2, [x8, :lo12:.LCPI3_0]
; CHECK-NO-SVE-NEXT:    cmlt v1.4h, v1.4h, #0
; CHECK-NO-SVE-NEXT:    and v1.8b, v1.8b, v2.8b
; CHECK-NO-SVE-NEXT:    addv h1, v1.4h
; CHECK-NO-SVE-NEXT:    fmov w8, s1
; CHECK-NO-SVE-NEXT:    tbnz w8, #0, .LBB3_5
; CHECK-NO-SVE-NEXT:  // %bb.1: // %else
; CHECK-NO-SVE-NEXT:    tbnz w8, #1, .LBB3_6
; CHECK-NO-SVE-NEXT:  .LBB3_2: // %else2
; CHECK-NO-SVE-NEXT:    tbnz w8, #2, .LBB3_7
; CHECK-NO-SVE-NEXT:  .LBB3_3: // %else6
; CHECK-NO-SVE-NEXT:    tbnz w8, #3, .LBB3_8
; CHECK-NO-SVE-NEXT:  .LBB3_4: // %else10
; CHECK-NO-SVE-NEXT:    ret
; CHECK-NO-SVE-NEXT:  .LBB3_5: // %cond.load
; CHECK-NO-SVE-NEXT:    ldrb w9, [x0], #1
; CHECK-NO-SVE-NEXT:    mov v0.h[0], w9
; CHECK-NO-SVE-NEXT:    tbz w8, #1, .LBB3_2
; CHECK-NO-SVE-NEXT:  .LBB3_6: // %cond.load1
; CHECK-NO-SVE-NEXT:    ldrb w9, [x0], #1
; CHECK-NO-SVE-NEXT:    mov v0.h[1], w9
; CHECK-NO-SVE-NEXT:    tbz w8, #2, .LBB3_3
; CHECK-NO-SVE-NEXT:  .LBB3_7: // %cond.load5
; CHECK-NO-SVE-NEXT:    ldrb w9, [x0], #1
; CHECK-NO-SVE-NEXT:    mov v0.h[2], w9
; CHECK-NO-SVE-NEXT:    tbz w8, #3, .LBB3_4
; CHECK-NO-SVE-NEXT:  .LBB3_8: // %cond.load9
; CHECK-NO-SVE-NEXT:    ld1 { v0.b }[6], [x0]
; CHECK-NO-SVE-NEXT:    ret
;
; CHECK-USE-NEON-LABEL: test_promote_fixed_expandload:
; CHECK-USE-NEON:       // %bb.0:
; CHECK-USE-NEON-NEXT:    shl v1.4h, v1.4h, #15
; CHECK-USE-NEON-NEXT:    adrp x8, .LCPI3_0
; CHECK-USE-NEON-NEXT:    ldr d2, [x8, :lo12:.LCPI3_0]
; CHECK-USE-NEON-NEXT:    cmlt v1.4h, v1.4h, #0
; CHECK-USE-NEON-NEXT:    and v1.8b, v1.8b, v2.8b
; CHECK-USE-NEON-NEXT:    addv h1, v1.4h
; CHECK-USE-NEON-NEXT:    fmov w8, s1
; CHECK-USE-NEON-NEXT:    tbnz w8, #0, .LBB3_5
; CHECK-USE-NEON-NEXT:  // %bb.1: // %else
; CHECK-USE-NEON-NEXT:    tbnz w8, #1, .LBB3_6
; CHECK-USE-NEON-NEXT:  .LBB3_2: // %else2
; CHECK-USE-NEON-NEXT:    tbnz w8, #2, .LBB3_7
; CHECK-USE-NEON-NEXT:  .LBB3_3: // %else6
; CHECK-USE-NEON-NEXT:    tbnz w8, #3, .LBB3_8
; CHECK-USE-NEON-NEXT:  .LBB3_4: // %else10
; CHECK-USE-NEON-NEXT:    ret
; CHECK-USE-NEON-NEXT:  .LBB3_5: // %cond.load
; CHECK-USE-NEON-NEXT:    ldrb w9, [x0], #1
; CHECK-USE-NEON-NEXT:    mov v0.h[0], w9
; CHECK-USE-NEON-NEXT:    tbz w8, #1, .LBB3_2
; CHECK-USE-NEON-NEXT:  .LBB3_6: // %cond.load1
; CHECK-USE-NEON-NEXT:    ldrb w9, [x0], #1
; CHECK-USE-NEON-NEXT:    mov v0.h[1], w9
; CHECK-USE-NEON-NEXT:    tbz w8, #2, .LBB3_3
; CHECK-USE-NEON-NEXT:  .LBB3_7: // %cond.load5
; CHECK-USE-NEON-NEXT:    ldrb w9, [x0], #1
; CHECK-USE-NEON-NEXT:    mov v0.h[2], w9
; CHECK-USE-NEON-NEXT:    tbz w8, #3, .LBB3_4
; CHECK-USE-NEON-NEXT:  .LBB3_8: // %cond.load9
; CHECK-USE-NEON-NEXT:    ld1 { v0.b }[6], [x0]
; CHECK-USE-NEON-NEXT:    ret
  %res = call <4 x i8> @llvm.masked.expandload(ptr align 1 %base, <4 x i1> %pred, <4 x i8> %passthru)
  ret <4 x i8> %res
}
