; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=aarch64-unknown-linux -mattr=+neon,+fullfp16 | FileCheck %s

define <2 x double> @manual_fmaxp_v2f64(<2 x double> %a, <2 x double> %b) {
; CHECK-LABEL: manual_fmaxp_v2f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fmaxp v0.2d, v0.2d, v1.2d
; CHECK-NEXT:    ret
  %e = shufflevector <2 x double> %a, <2 x double> %b, <2 x i32> <i32 0, i32 2>
  %o = shufflevector <2 x double> %a, <2 x double> %b, <2 x i32> <i32 1, i32 3>
  %r = call <2 x double> @llvm.maximum.v2f64(<2 x double> %e, <2 x double> %o)
  ret <2 x double> %r
}

define <2 x double> @manual_fminp_v2f64(<2 x double> %a, <2 x double> %b) {
; CHECK-LABEL: manual_fminp_v2f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fminp v0.2d, v0.2d, v1.2d
; CHECK-NEXT:    ret
  %e = shufflevector <2 x double> %a, <2 x double> %b, <2 x i32> <i32 0, i32 2>
  %o = shufflevector <2 x double> %a, <2 x double> %b, <2 x i32> <i32 1, i32 3>
  %r = call <2 x double> @llvm.minimum.v2f64(<2 x double> %e, <2 x double> %o)
  ret <2 x double> %r
}

define <2 x float> @manual_fmaxp_v2f32(<2 x float> %a, <2 x float> %b) {
; CHECK-LABEL: manual_fmaxp_v2f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fmaxp v0.2s, v0.2s, v1.2s
; CHECK-NEXT:    ret
  %e = shufflevector <2 x float> %a, <2 x float> %b, <2 x i32> <i32 0, i32 2>
  %o = shufflevector <2 x float> %a, <2 x float> %b, <2 x i32> <i32 1, i32 3>
  %r = call <2 x float> @llvm.maximum.v2f32(<2 x float> %e, <2 x float> %o)
  ret <2 x float> %r
}

define <2 x float> @manual_fminp_v2f32(<2 x float> %a, <2 x float> %b) {
; CHECK-LABEL: manual_fminp_v2f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fminp v0.2s, v0.2s, v1.2s
; CHECK-NEXT:    ret
  %e = shufflevector <2 x float> %a, <2 x float> %b, <2 x i32> <i32 0, i32 2>
  %o = shufflevector <2 x float> %a, <2 x float> %b, <2 x i32> <i32 1, i32 3>
  %r = call <2 x float> @llvm.minimum.v2f32(<2 x float> %e, <2 x float> %o)
  ret <2 x float> %r
}

define <4 x float> @manual_fmaxp_v4f32(<4 x float> %a, <4 x float> %b) {
; CHECK-LABEL: manual_fmaxp_v4f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fmaxp v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
  %e = shufflevector <4 x float> %a, <4 x float> %b, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %o = shufflevector <4 x float> %a, <4 x float> %b, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %r = call <4 x float> @llvm.maximum.v4f32(<4 x float> %e, <4 x float> %o)
  ret <4 x float> %r
}

define <4 x float> @manual_fminp_v4f32(<4 x float> %a, <4 x float> %b) {
; CHECK-LABEL: manual_fminp_v4f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fminp v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
  %e = shufflevector <4 x float> %a, <4 x float> %b, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %o = shufflevector <4 x float> %a, <4 x float> %b, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %r = call <4 x float> @llvm.minimum.v4f32(<4 x float> %e, <4 x float> %o)
  ret <4 x float> %r
}

declare <2 x double> @llvm.maximum.v2f64(<2 x double>, <2 x double>)
declare <2 x double> @llvm.minimum.v2f64(<2 x double>, <2 x double>)
declare <2 x float> @llvm.maximum.v2f32(<2 x float>, <2 x float>)
declare <2 x float> @llvm.minimum.v2f32(<2 x float>, <2 x float>)
declare <4 x float> @llvm.maximum.v4f32(<4 x float>, <4 x float>)
declare <4 x float> @llvm.minimum.v4f32(<4 x float>, <4 x float>)
