; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=aarch64 -verify-machineinstrs %s -o - | FileCheck %s

define half @min(half noundef %a, half noundef %b) {
; CHECK-LABEL: min:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fcvt s1, h1
; CHECK-NEXT:    fcvt s0, h0
; CHECK-NEXT:    fminnm s0, s0, s1
; CHECK-NEXT:    fcvt h0, s0
; CHECK-NEXT:    ret
entry:
  %0 = tail call half @llvm.minimumnum.f16(half %a, half %b)
  ret half %0
}

define half @max(half noundef %a, half noundef %b) {
; CHECK-LABEL: max:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fcvt s1, h1
; CHECK-NEXT:    fcvt s0, h0
; CHECK-NEXT:    fmaxnm s0, s0, s1
; CHECK-NEXT:    fcvt h0, s0
; CHECK-NEXT:    ret
entry:
  %0 = tail call half @llvm.maximumnum.f16(half %a, half %b)
  ret half %0
}
