; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=aarch64 -verify-machineinstrs %s -o - | FileCheck %s --check-prefixes=CHECK,CHECK-NOFP16,CHECK-NOFP16-SD
; RUN: llc -mtriple=aarch64 -mattr=+fullfp16 -verify-machineinstrs %s -o - | FileCheck %s --check-prefixes=CHECK,CHECK-FP16,CHECK-FP16-SD
; RUN: llc -mtriple=aarch64 -global-isel -global-isel-abort=2 -verify-machineinstrs %s -o - -global-isel-abort=2 | FileCheck %s --check-prefixes=CHECK,CHECK-NOFP16,CHECK-NOFP16-GI
; RUN: llc -mtriple=aarch64 -mattr=+fullfp16 -global-isel -global-isel-abort=2 -verify-machineinstrs %s -o - -global-isel-abort=2 | FileCheck %s --check-prefixes=CHECK,CHECK-FP16,CHECK-FP16-GI

define double @fneg_f64(double %a) {
; CHECK-LABEL: fneg_f64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fneg d0, d0
; CHECK-NEXT:    ret
entry:
  %c = fneg double %a
  ret double %c
}

define float @fneg_f32(float %a) {
; CHECK-LABEL: fneg_f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fneg s0, s0
; CHECK-NEXT:    ret
entry:
  %c = fneg float %a
  ret float %c
}

define half @fneg_f16(half %a) {
; CHECK-NOFP16-SD-LABEL: fneg_f16:
; CHECK-NOFP16-SD:       // %bb.0: // %entry
; CHECK-NOFP16-SD-NEXT:    // kill: def $h0 killed $h0 def $s0
; CHECK-NOFP16-SD-NEXT:    fmov w8, s0
; CHECK-NOFP16-SD-NEXT:    eor w8, w8, #0x8000
; CHECK-NOFP16-SD-NEXT:    fmov s0, w8
; CHECK-NOFP16-SD-NEXT:    // kill: def $h0 killed $h0 killed $s0
; CHECK-NOFP16-SD-NEXT:    ret
;
; CHECK-FP16-LABEL: fneg_f16:
; CHECK-FP16:       // %bb.0: // %entry
; CHECK-FP16-NEXT:    fneg h0, h0
; CHECK-FP16-NEXT:    ret
;
; CHECK-NOFP16-GI-LABEL: fneg_f16:
; CHECK-NOFP16-GI:       // %bb.0: // %entry
; CHECK-NOFP16-GI-NEXT:    // kill: def $h0 killed $h0 def $s0
; CHECK-NOFP16-GI-NEXT:    fmov w8, s0
; CHECK-NOFP16-GI-NEXT:    eor w8, w8, #0xffff8000
; CHECK-NOFP16-GI-NEXT:    fmov s0, w8
; CHECK-NOFP16-GI-NEXT:    // kill: def $h0 killed $h0 killed $s0
; CHECK-NOFP16-GI-NEXT:    ret
entry:
  %c = fneg half %a
  ret half %c
}

define bfloat @fneg_bf16(bfloat %a) {
; CHECK-NOFP16-LABEL: fneg_bf16:
; CHECK-NOFP16:       // %bb.0: // %entry
; CHECK-NOFP16-NEXT:    // kill: def $h0 killed $h0 def $s0
; CHECK-NOFP16-NEXT:    fmov w8, s0
; CHECK-NOFP16-NEXT:    eor w8, w8, #0x8000
; CHECK-NOFP16-NEXT:    fmov s0, w8
; CHECK-NOFP16-NEXT:    // kill: def $h0 killed $h0 killed $s0
; CHECK-NOFP16-NEXT:    ret
;
; CHECK-FP16-LABEL: fneg_bf16:
; CHECK-FP16:       // %bb.0: // %entry
; CHECK-FP16-NEXT:    fneg h0, h0
; CHECK-FP16-NEXT:    ret
entry:
  %c = fneg bfloat %a
  ret bfloat %c
}

define <2 x double> @fneg_v2f64(<2 x double> %a) {
; CHECK-LABEL: fneg_v2f64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fneg v0.2d, v0.2d
; CHECK-NEXT:    ret
entry:
  %c = fneg <2 x double> %a
  ret <2 x double> %c
}

define <3 x double> @fneg_v3f64(<3 x double> %a) {
; CHECK-NOFP16-SD-LABEL: fneg_v3f64:
; CHECK-NOFP16-SD:       // %bb.0: // %entry
; CHECK-NOFP16-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-NOFP16-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-NOFP16-SD-NEXT:    // kill: def $d2 killed $d2 def $q2
; CHECK-NOFP16-SD-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-NOFP16-SD-NEXT:    fneg v2.2d, v2.2d
; CHECK-NOFP16-SD-NEXT:    // kill: def $d2 killed $d2 killed $q2
; CHECK-NOFP16-SD-NEXT:    fneg v0.2d, v0.2d
; CHECK-NOFP16-SD-NEXT:    mov d1, v0.d[1]
; CHECK-NOFP16-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-NOFP16-SD-NEXT:    ret
;
; CHECK-FP16-SD-LABEL: fneg_v3f64:
; CHECK-FP16-SD:       // %bb.0: // %entry
; CHECK-FP16-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-FP16-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-FP16-SD-NEXT:    // kill: def $d2 killed $d2 def $q2
; CHECK-FP16-SD-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-FP16-SD-NEXT:    fneg v2.2d, v2.2d
; CHECK-FP16-SD-NEXT:    // kill: def $d2 killed $d2 killed $q2
; CHECK-FP16-SD-NEXT:    fneg v0.2d, v0.2d
; CHECK-FP16-SD-NEXT:    mov d1, v0.d[1]
; CHECK-FP16-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-FP16-SD-NEXT:    ret
;
; CHECK-NOFP16-GI-LABEL: fneg_v3f64:
; CHECK-NOFP16-GI:       // %bb.0: // %entry
; CHECK-NOFP16-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-NOFP16-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-NOFP16-GI-NEXT:    fneg d2, d2
; CHECK-NOFP16-GI-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-NOFP16-GI-NEXT:    fneg v0.2d, v0.2d
; CHECK-NOFP16-GI-NEXT:    mov d1, v0.d[1]
; CHECK-NOFP16-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-NOFP16-GI-NEXT:    ret
;
; CHECK-FP16-GI-LABEL: fneg_v3f64:
; CHECK-FP16-GI:       // %bb.0: // %entry
; CHECK-FP16-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-FP16-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-FP16-GI-NEXT:    fneg d2, d2
; CHECK-FP16-GI-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-FP16-GI-NEXT:    fneg v0.2d, v0.2d
; CHECK-FP16-GI-NEXT:    mov d1, v0.d[1]
; CHECK-FP16-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-FP16-GI-NEXT:    ret
entry:
  %c = fneg <3 x double> %a
  ret <3 x double> %c
}

define <4 x double> @fneg_v4f64(<4 x double> %a) {
; CHECK-LABEL: fneg_v4f64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fneg v0.2d, v0.2d
; CHECK-NEXT:    fneg v1.2d, v1.2d
; CHECK-NEXT:    ret
entry:
  %c = fneg <4 x double> %a
  ret <4 x double> %c
}

define <2 x float> @fneg_v2f32(<2 x float> %a) {
; CHECK-LABEL: fneg_v2f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fneg v0.2s, v0.2s
; CHECK-NEXT:    ret
entry:
  %c = fneg <2 x float> %a
  ret <2 x float> %c
}

define <3 x float> @fneg_v3f32(<3 x float> %a) {
; CHECK-LABEL: fneg_v3f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fneg v0.4s, v0.4s
; CHECK-NEXT:    ret
entry:
  %c = fneg <3 x float> %a
  ret <3 x float> %c
}

define <4 x float> @fneg_v4f32(<4 x float> %a) {
; CHECK-LABEL: fneg_v4f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fneg v0.4s, v0.4s
; CHECK-NEXT:    ret
entry:
  %c = fneg <4 x float> %a
  ret <4 x float> %c
}

define <8 x float> @fneg_v8f32(<8 x float> %a) {
; CHECK-LABEL: fneg_v8f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fneg v0.4s, v0.4s
; CHECK-NEXT:    fneg v1.4s, v1.4s
; CHECK-NEXT:    ret
entry:
  %c = fneg <8 x float> %a
  ret <8 x float> %c
}

define <7 x half> @fneg_v7f16(<7 x half> %a) {
; CHECK-NOFP16-LABEL: fneg_v7f16:
; CHECK-NOFP16:       // %bb.0: // %entry
; CHECK-NOFP16-NEXT:    movi v1.8h, #128, lsl #8
; CHECK-NOFP16-NEXT:    eor v0.16b, v0.16b, v1.16b
; CHECK-NOFP16-NEXT:    ret
;
; CHECK-FP16-LABEL: fneg_v7f16:
; CHECK-FP16:       // %bb.0: // %entry
; CHECK-FP16-NEXT:    fneg v0.8h, v0.8h
; CHECK-FP16-NEXT:    ret
entry:
  %c = fneg <7 x half> %a
  ret <7 x half> %c
}

define <4 x half> @fneg_v4f16(<4 x half> %a) {
; CHECK-NOFP16-LABEL: fneg_v4f16:
; CHECK-NOFP16:       // %bb.0: // %entry
; CHECK-NOFP16-NEXT:    movi v1.4h, #128, lsl #8
; CHECK-NOFP16-NEXT:    eor v0.8b, v0.8b, v1.8b
; CHECK-NOFP16-NEXT:    ret
;
; CHECK-FP16-LABEL: fneg_v4f16:
; CHECK-FP16:       // %bb.0: // %entry
; CHECK-FP16-NEXT:    fneg v0.4h, v0.4h
; CHECK-FP16-NEXT:    ret
entry:
  %c = fneg <4 x half> %a
  ret <4 x half> %c
}

define <8 x half> @fneg_v8f16(<8 x half> %a) {
; CHECK-NOFP16-LABEL: fneg_v8f16:
; CHECK-NOFP16:       // %bb.0: // %entry
; CHECK-NOFP16-NEXT:    movi v1.8h, #128, lsl #8
; CHECK-NOFP16-NEXT:    eor v0.16b, v0.16b, v1.16b
; CHECK-NOFP16-NEXT:    ret
;
; CHECK-FP16-LABEL: fneg_v8f16:
; CHECK-FP16:       // %bb.0: // %entry
; CHECK-FP16-NEXT:    fneg v0.8h, v0.8h
; CHECK-FP16-NEXT:    ret
entry:
  %c = fneg <8 x half> %a
  ret <8 x half> %c
}

define <16 x half> @fneg_v16f16(<16 x half> %a) {
; CHECK-NOFP16-LABEL: fneg_v16f16:
; CHECK-NOFP16:       // %bb.0: // %entry
; CHECK-NOFP16-NEXT:    movi v2.8h, #128, lsl #8
; CHECK-NOFP16-NEXT:    eor v0.16b, v0.16b, v2.16b
; CHECK-NOFP16-NEXT:    eor v1.16b, v1.16b, v2.16b
; CHECK-NOFP16-NEXT:    ret
;
; CHECK-FP16-LABEL: fneg_v16f16:
; CHECK-FP16:       // %bb.0: // %entry
; CHECK-FP16-NEXT:    fneg v0.8h, v0.8h
; CHECK-FP16-NEXT:    fneg v1.8h, v1.8h
; CHECK-FP16-NEXT:    ret
entry:
  %c = fneg <16 x half> %a
  ret <16 x half> %c
}

define <7 x bfloat> @fneg_v7bf16(<7 x bfloat> %a) {
; CHECK-NOFP16-LABEL: fneg_v7bf16:
; CHECK-NOFP16:       // %bb.0: // %entry
; CHECK-NOFP16-NEXT:    movi v1.8h, #128, lsl #8
; CHECK-NOFP16-NEXT:    eor v0.16b, v0.16b, v1.16b
; CHECK-NOFP16-NEXT:    ret
;
; CHECK-FP16-LABEL: fneg_v7bf16:
; CHECK-FP16:       // %bb.0: // %entry
; CHECK-FP16-NEXT:    fneg v0.8h, v0.8h
; CHECK-FP16-NEXT:    ret
entry:
  %c = fneg <7 x bfloat> %a
  ret <7 x bfloat> %c
}

define <4 x bfloat> @fneg_v4bf16(<4 x bfloat> %a) {
; CHECK-NOFP16-LABEL: fneg_v4bf16:
; CHECK-NOFP16:       // %bb.0: // %entry
; CHECK-NOFP16-NEXT:    movi v1.4h, #128, lsl #8
; CHECK-NOFP16-NEXT:    eor v0.8b, v0.8b, v1.8b
; CHECK-NOFP16-NEXT:    ret
;
; CHECK-FP16-LABEL: fneg_v4bf16:
; CHECK-FP16:       // %bb.0: // %entry
; CHECK-FP16-NEXT:    fneg v0.4h, v0.4h
; CHECK-FP16-NEXT:    ret
entry:
  %c = fneg <4 x bfloat> %a
  ret <4 x bfloat> %c
}

define <8 x bfloat> @fneg_v8bf16(<8 x bfloat> %a) {
; CHECK-NOFP16-LABEL: fneg_v8bf16:
; CHECK-NOFP16:       // %bb.0: // %entry
; CHECK-NOFP16-NEXT:    movi v1.8h, #128, lsl #8
; CHECK-NOFP16-NEXT:    eor v0.16b, v0.16b, v1.16b
; CHECK-NOFP16-NEXT:    ret
;
; CHECK-FP16-LABEL: fneg_v8bf16:
; CHECK-FP16:       // %bb.0: // %entry
; CHECK-FP16-NEXT:    fneg v0.8h, v0.8h
; CHECK-FP16-NEXT:    ret
entry:
  %c = fneg <8 x bfloat> %a
  ret <8 x bfloat> %c
}

define <16 x bfloat> @fneg_v16bf16(<16 x bfloat> %a) {
; CHECK-NOFP16-LABEL: fneg_v16bf16:
; CHECK-NOFP16:       // %bb.0: // %entry
; CHECK-NOFP16-NEXT:    movi v2.8h, #128, lsl #8
; CHECK-NOFP16-NEXT:    eor v0.16b, v0.16b, v2.16b
; CHECK-NOFP16-NEXT:    eor v1.16b, v1.16b, v2.16b
; CHECK-NOFP16-NEXT:    ret
;
; CHECK-FP16-LABEL: fneg_v16bf16:
; CHECK-FP16:       // %bb.0: // %entry
; CHECK-FP16-NEXT:    fneg v0.8h, v0.8h
; CHECK-FP16-NEXT:    fneg v1.8h, v1.8h
; CHECK-FP16-NEXT:    ret
entry:
  %c = fneg <16 x bfloat> %a
  ret <16 x bfloat> %c
}
