; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -verify-machineinstrs -mtriple=aarch64-none-linux-gnu -disable-post-ra --frame-pointer=all < %s | FileCheck %s

; The purpose of this test is to verify that frame pointer (x29)
; is correctly setup in the presence of callee-saved floating
; point registers.  The frame pointer should point to the frame
; record, which is located 16 bytes above the end of the CSR
; space when a single FP CSR is in use.
define void @test1(i32) nounwind {
; CHECK-LABEL: test1:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    str d8, [sp, #-32]! // 8-byte Folded Spill
; CHECK-NEXT:    stp x29, x30, [sp, #16] // 16-byte Folded Spill
; CHECK-NEXT:    add x29, sp, #16
; CHECK-NEXT:    //APP
; CHECK-NEXT:    nop
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ldp x29, x30, [sp, #16] // 16-byte Folded Reload
; CHECK-NEXT:    ldr d8, [sp], #32 // 8-byte Folded Reload
; CHECK-NEXT:    ret
entry:
  call void asm sideeffect "nop", "~{d8}"()
  ret void
}

; The purpose of this test is to verify q8 is assigned a 16-byte aligned offset
; after the x10 is assigned an offset. The CSR (on Linux) are assigned offsets
; in the order GPRs then FPRs. The stack size of this function is 48
; (alignTo((16 + 8 * 3), 16)), so after x8 is given the offset 24, q8 originally
; would be assigned offset 8, which is not 16-byte aligned.
define preserve_allcc void @d(ptr %ptr) nounwind {
; CHECK-LABEL: d:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    str q8, [sp, #-48]! // 16-byte Folded Spill
; CHECK-NEXT:    str x10, [sp, #24] // 8-byte Spill
; CHECK-NEXT:    stp x29, x30, [sp, #32] // 16-byte Folded Spill
; CHECK-NEXT:    add x29, sp, #32
; CHECK-NEXT:    //APP
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ldp x29, x30, [sp, #32] // 16-byte Folded Reload
; CHECK-NEXT:    ldr x10, [sp, #24] // 8-byte Reload
; CHECK-NEXT:    ldr q8, [sp], #48 // 16-byte Folded Reload
; CHECK-NEXT:    ret
entry:
  tail call void asm sideeffect "", "~{x10},~{q8}"()
  ret void
}
