; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=aarch64-unknown-linux-gnu < %s | FileCheck %s --check-prefixes=CHECK,CHECK-SD
; RUN: llc --mtriple=aarch64-unknown-linux-gnu < %s -global-isel | FileCheck %s --check-prefixes=CHECK,CHECK-GI

; Check that the following does not crash
; See https://github.com/llvm/llvm-project/issues/123029 for details

define ptr @fn(ptr %in, ptr %out) {
; CHECK-SD-LABEL: fn:
; CHECK-SD:       // %bb.0: // %fn
; CHECK-SD-NEXT:    ldr d1, [x0]
; CHECK-SD-NEXT:    movi v0.4h, #60, lsl #8
; CHECK-SD-NEXT:    adrp x8, .LCPI0_0
; CHECK-SD-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-SD-NEXT:    fcmgt v2.4s, v1.4s, #0.0
; CHECK-SD-NEXT:    fcmlt v1.4s, v1.4s, #0.0
; CHECK-SD-NEXT:    orr v1.16b, v1.16b, v2.16b
; CHECK-SD-NEXT:    ldr h2, [x8, :lo12:.LCPI0_0]
; CHECK-SD-NEXT:    xtn v1.4h, v1.4s
; CHECK-SD-NEXT:    and v0.8b, v1.8b, v0.8b
; CHECK-SD-NEXT:    movi d1, #0000000000000000
; CHECK-SD-NEXT:    str d0, [x1]
; CHECK-SD-NEXT:    ldr h0, [x0, #8]
; CHECK-SD-NEXT:    mov x0, xzr
; CHECK-SD-NEXT:    fcvt s0, h0
; CHECK-SD-NEXT:    fcmp s0, #0.0
; CHECK-SD-NEXT:    fcsel s1, s2, s1, mi
; CHECK-SD-NEXT:    fcsel s1, s2, s1, gt
; CHECK-SD-NEXT:    mvni v2.4s, #128, lsl #24
; CHECK-SD-NEXT:    fcvt s1, h1
; CHECK-SD-NEXT:    bit v0.16b, v1.16b, v2.16b
; CHECK-SD-NEXT:    fcvt h0, s0
; CHECK-SD-NEXT:    str h0, [x1, #8]
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: fn:
; CHECK-GI:       // %bb.0: // %fn
; CHECK-GI-NEXT:    movi v0.2d, #0000000000000000
; CHECK-GI-NEXT:    ldr d1, [x0]
; CHECK-GI-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-GI-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-GI-NEXT:    fcmgt v2.4s, v1.4s, v0.4s
; CHECK-GI-NEXT:    fcmgt v0.4s, v0.4s, v1.4s
; CHECK-GI-NEXT:    movi v1.4s, #1
; CHECK-GI-NEXT:    orr v0.16b, v0.16b, v2.16b
; CHECK-GI-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-GI-NEXT:    mvni v1.4h, #128, lsl #8
; CHECK-GI-NEXT:    ucvtf v0.4s, v0.4s
; CHECK-GI-NEXT:    fcvtn v0.4h, v0.4s
; CHECK-GI-NEXT:    str d0, [x1]
; CHECK-GI-NEXT:    ldr h0, [x0, #8]
; CHECK-GI-NEXT:    ldr h2, [x0, #8]
; CHECK-GI-NEXT:    mov x0, xzr
; CHECK-GI-NEXT:    fcvt s0, h0
; CHECK-GI-NEXT:    fcmp s0, #0.0
; CHECK-GI-NEXT:    cset w8, mi
; CHECK-GI-NEXT:    csinc w8, w8, wzr, le
; CHECK-GI-NEXT:    ucvtf s0, w8
; CHECK-GI-NEXT:    fcvt h0, s0
; CHECK-GI-NEXT:    bif v0.8b, v2.8b, v1.8b
; CHECK-GI-NEXT:    str h0, [x1, #8]
; CHECK-GI-NEXT:    ret
fn:
  %1 = load <4 x half>, ptr %in
  %2 = fcmp one <4 x half> %1, zeroinitializer
  %3 = uitofp <4 x i1> %2 to <4 x half>
  store <4 x half> %3, ptr %out

  %4 = getelementptr inbounds nuw i8, ptr %in, i64 8
  %5 = load half, ptr %4
  %6 = fcmp one half %5, 0xH0000
  %7 = uitofp i1 %6 to half
  %8 = call half @llvm.copysign.f16(half %7, half %5)
  %9 = getelementptr inbounds nuw i8, ptr %out, i64 8
  store half %8, ptr %9
  ret ptr null
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
