; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=aarch64-linux-gnu        | FileCheck %s --check-prefix=LINUX-A64
; RUN: llc < %s -mtriple=arm64-apple-macosx       | FileCheck %s --check-prefix=DARWIN-A64
; RUN: llc < %s -mtriple=arm64_32-apple-watchos   | FileCheck %s --check-prefix=WATCHOS

define void @sdivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; LINUX-A64-LABEL: sdivrem_i128:
; LINUX-A64:       // %bb.0:
; LINUX-A64-NEXT:    sub sp, sp, #48
; LINUX-A64-NEXT:    str x30, [sp, #16] // 8-byte Spill
; LINUX-A64-NEXT:    stp x20, x19, [sp, #32] // 16-byte Folded Spill
; LINUX-A64-NEXT:    .cfi_def_cfa_offset 48
; LINUX-A64-NEXT:    .cfi_offset w19, -8
; LINUX-A64-NEXT:    .cfi_offset w20, -16
; LINUX-A64-NEXT:    .cfi_offset w30, -32
; LINUX-A64-NEXT:    mov x8, x4
; LINUX-A64-NEXT:    mov x19, x1
; LINUX-A64-NEXT:    mov x20, x0
; LINUX-A64-NEXT:    mov x4, sp
; LINUX-A64-NEXT:    mov x0, x2
; LINUX-A64-NEXT:    mov x1, x3
; LINUX-A64-NEXT:    mov x2, x8
; LINUX-A64-NEXT:    mov x3, x5
; LINUX-A64-NEXT:    bl __divmodti4
; LINUX-A64-NEXT:    ldp x9, x8, [sp]
; LINUX-A64-NEXT:    stp x0, x1, [x20]
; LINUX-A64-NEXT:    ldr x30, [sp, #16] // 8-byte Reload
; LINUX-A64-NEXT:    stp x9, x8, [x19]
; LINUX-A64-NEXT:    ldp x20, x19, [sp, #32] // 16-byte Folded Reload
; LINUX-A64-NEXT:    add sp, sp, #48
; LINUX-A64-NEXT:    ret
;
; DARWIN-A64-LABEL: sdivrem_i128:
; DARWIN-A64:       ; %bb.0:
; DARWIN-A64-NEXT:    sub sp, sp, #48
; DARWIN-A64-NEXT:    stp x20, x19, [sp, #16] ; 16-byte Folded Spill
; DARWIN-A64-NEXT:    stp x29, x30, [sp, #32] ; 16-byte Folded Spill
; DARWIN-A64-NEXT:    .cfi_def_cfa_offset 48
; DARWIN-A64-NEXT:    .cfi_offset w30, -8
; DARWIN-A64-NEXT:    .cfi_offset w29, -16
; DARWIN-A64-NEXT:    .cfi_offset w19, -24
; DARWIN-A64-NEXT:    .cfi_offset w20, -32
; DARWIN-A64-NEXT:    mov x8, x4
; DARWIN-A64-NEXT:    mov x19, x1
; DARWIN-A64-NEXT:    mov x20, x0
; DARWIN-A64-NEXT:    mov x4, sp
; DARWIN-A64-NEXT:    mov x0, x2
; DARWIN-A64-NEXT:    mov x1, x3
; DARWIN-A64-NEXT:    mov x2, x8
; DARWIN-A64-NEXT:    mov x3, x5
; DARWIN-A64-NEXT:    bl ___divmodti4
; DARWIN-A64-NEXT:    ldp x9, x8, [sp]
; DARWIN-A64-NEXT:    stp x0, x1, [x20]
; DARWIN-A64-NEXT:    ldp x29, x30, [sp, #32] ; 16-byte Folded Reload
; DARWIN-A64-NEXT:    stp x9, x8, [x19]
; DARWIN-A64-NEXT:    ldp x20, x19, [sp, #16] ; 16-byte Folded Reload
; DARWIN-A64-NEXT:    add sp, sp, #48
; DARWIN-A64-NEXT:    ret
;
; WATCHOS-LABEL: sdivrem_i128:
; WATCHOS:       ; %bb.0:
; WATCHOS-NEXT:    stp x26, x25, [sp, #-80]! ; 16-byte Folded Spill
; WATCHOS-NEXT:    stp x24, x23, [sp, #16] ; 16-byte Folded Spill
; WATCHOS-NEXT:    stp x22, x21, [sp, #32] ; 16-byte Folded Spill
; WATCHOS-NEXT:    stp x20, x19, [sp, #48] ; 16-byte Folded Spill
; WATCHOS-NEXT:    stp x29, x30, [sp, #64] ; 16-byte Folded Spill
; WATCHOS-NEXT:    .cfi_def_cfa_offset 80
; WATCHOS-NEXT:    .cfi_offset w30, -8
; WATCHOS-NEXT:    .cfi_offset w29, -16
; WATCHOS-NEXT:    .cfi_offset w19, -24
; WATCHOS-NEXT:    .cfi_offset w20, -32
; WATCHOS-NEXT:    .cfi_offset w21, -40
; WATCHOS-NEXT:    .cfi_offset w22, -48
; WATCHOS-NEXT:    .cfi_offset w23, -56
; WATCHOS-NEXT:    .cfi_offset w24, -64
; WATCHOS-NEXT:    .cfi_offset w25, -72
; WATCHOS-NEXT:    .cfi_offset w26, -80
; WATCHOS-NEXT:    mov x21, x3
; WATCHOS-NEXT:    mov x22, x2
; WATCHOS-NEXT:    mov x23, x1
; WATCHOS-NEXT:    mov x24, x0
; WATCHOS-NEXT:    mov x0, x2
; WATCHOS-NEXT:    mov x1, x3
; WATCHOS-NEXT:    mov x2, x4
; WATCHOS-NEXT:    mov x3, x5
; WATCHOS-NEXT:    mov x19, x5
; WATCHOS-NEXT:    mov x20, x4
; WATCHOS-NEXT:    bl ___divti3
; WATCHOS-NEXT:    mov x25, x0
; WATCHOS-NEXT:    mov x26, x1
; WATCHOS-NEXT:    mov x0, x22
; WATCHOS-NEXT:    mov x1, x21
; WATCHOS-NEXT:    mov x2, x20
; WATCHOS-NEXT:    mov x3, x19
; WATCHOS-NEXT:    bl ___modti3
; WATCHOS-NEXT:    stp x25, x26, [x24]
; WATCHOS-NEXT:    ldp x29, x30, [sp, #64] ; 16-byte Folded Reload
; WATCHOS-NEXT:    stp x0, x1, [x23]
; WATCHOS-NEXT:    ldp x20, x19, [sp, #48] ; 16-byte Folded Reload
; WATCHOS-NEXT:    ldp x22, x21, [sp, #32] ; 16-byte Folded Reload
; WATCHOS-NEXT:    ldp x24, x23, [sp, #16] ; 16-byte Folded Reload
; WATCHOS-NEXT:    ldp x26, x25, [sp], #80 ; 16-byte Folded Reload
; WATCHOS-NEXT:    ret
  %q = sdiv i128 %n, %d
  %r = srem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}

define void @udivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; LINUX-A64-LABEL: udivrem_i128:
; LINUX-A64:       // %bb.0:
; LINUX-A64-NEXT:    sub sp, sp, #48
; LINUX-A64-NEXT:    str x30, [sp, #16] // 8-byte Spill
; LINUX-A64-NEXT:    stp x20, x19, [sp, #32] // 16-byte Folded Spill
; LINUX-A64-NEXT:    .cfi_def_cfa_offset 48
; LINUX-A64-NEXT:    .cfi_offset w19, -8
; LINUX-A64-NEXT:    .cfi_offset w20, -16
; LINUX-A64-NEXT:    .cfi_offset w30, -32
; LINUX-A64-NEXT:    mov x8, x4
; LINUX-A64-NEXT:    mov x19, x1
; LINUX-A64-NEXT:    mov x20, x0
; LINUX-A64-NEXT:    mov x4, sp
; LINUX-A64-NEXT:    mov x0, x2
; LINUX-A64-NEXT:    mov x1, x3
; LINUX-A64-NEXT:    mov x2, x8
; LINUX-A64-NEXT:    mov x3, x5
; LINUX-A64-NEXT:    bl __udivmodti4
; LINUX-A64-NEXT:    ldp x9, x8, [sp]
; LINUX-A64-NEXT:    stp x0, x1, [x20]
; LINUX-A64-NEXT:    ldr x30, [sp, #16] // 8-byte Reload
; LINUX-A64-NEXT:    stp x9, x8, [x19]
; LINUX-A64-NEXT:    ldp x20, x19, [sp, #32] // 16-byte Folded Reload
; LINUX-A64-NEXT:    add sp, sp, #48
; LINUX-A64-NEXT:    ret
;
; DARWIN-A64-LABEL: udivrem_i128:
; DARWIN-A64:       ; %bb.0:
; DARWIN-A64-NEXT:    sub sp, sp, #48
; DARWIN-A64-NEXT:    stp x20, x19, [sp, #16] ; 16-byte Folded Spill
; DARWIN-A64-NEXT:    stp x29, x30, [sp, #32] ; 16-byte Folded Spill
; DARWIN-A64-NEXT:    .cfi_def_cfa_offset 48
; DARWIN-A64-NEXT:    .cfi_offset w30, -8
; DARWIN-A64-NEXT:    .cfi_offset w29, -16
; DARWIN-A64-NEXT:    .cfi_offset w19, -24
; DARWIN-A64-NEXT:    .cfi_offset w20, -32
; DARWIN-A64-NEXT:    mov x8, x4
; DARWIN-A64-NEXT:    mov x19, x1
; DARWIN-A64-NEXT:    mov x20, x0
; DARWIN-A64-NEXT:    mov x4, sp
; DARWIN-A64-NEXT:    mov x0, x2
; DARWIN-A64-NEXT:    mov x1, x3
; DARWIN-A64-NEXT:    mov x2, x8
; DARWIN-A64-NEXT:    mov x3, x5
; DARWIN-A64-NEXT:    bl ___udivmodti4
; DARWIN-A64-NEXT:    ldp x9, x8, [sp]
; DARWIN-A64-NEXT:    stp x0, x1, [x20]
; DARWIN-A64-NEXT:    ldp x29, x30, [sp, #32] ; 16-byte Folded Reload
; DARWIN-A64-NEXT:    stp x9, x8, [x19]
; DARWIN-A64-NEXT:    ldp x20, x19, [sp, #16] ; 16-byte Folded Reload
; DARWIN-A64-NEXT:    add sp, sp, #48
; DARWIN-A64-NEXT:    ret
;
; WATCHOS-LABEL: udivrem_i128:
; WATCHOS:       ; %bb.0:
; WATCHOS-NEXT:    stp x26, x25, [sp, #-80]! ; 16-byte Folded Spill
; WATCHOS-NEXT:    stp x24, x23, [sp, #16] ; 16-byte Folded Spill
; WATCHOS-NEXT:    stp x22, x21, [sp, #32] ; 16-byte Folded Spill
; WATCHOS-NEXT:    stp x20, x19, [sp, #48] ; 16-byte Folded Spill
; WATCHOS-NEXT:    stp x29, x30, [sp, #64] ; 16-byte Folded Spill
; WATCHOS-NEXT:    .cfi_def_cfa_offset 80
; WATCHOS-NEXT:    .cfi_offset w30, -8
; WATCHOS-NEXT:    .cfi_offset w29, -16
; WATCHOS-NEXT:    .cfi_offset w19, -24
; WATCHOS-NEXT:    .cfi_offset w20, -32
; WATCHOS-NEXT:    .cfi_offset w21, -40
; WATCHOS-NEXT:    .cfi_offset w22, -48
; WATCHOS-NEXT:    .cfi_offset w23, -56
; WATCHOS-NEXT:    .cfi_offset w24, -64
; WATCHOS-NEXT:    .cfi_offset w25, -72
; WATCHOS-NEXT:    .cfi_offset w26, -80
; WATCHOS-NEXT:    mov x21, x3
; WATCHOS-NEXT:    mov x22, x2
; WATCHOS-NEXT:    mov x23, x1
; WATCHOS-NEXT:    mov x24, x0
; WATCHOS-NEXT:    mov x0, x2
; WATCHOS-NEXT:    mov x1, x3
; WATCHOS-NEXT:    mov x2, x4
; WATCHOS-NEXT:    mov x3, x5
; WATCHOS-NEXT:    mov x19, x5
; WATCHOS-NEXT:    mov x20, x4
; WATCHOS-NEXT:    bl ___udivti3
; WATCHOS-NEXT:    mov x25, x0
; WATCHOS-NEXT:    mov x26, x1
; WATCHOS-NEXT:    mov x0, x22
; WATCHOS-NEXT:    mov x1, x21
; WATCHOS-NEXT:    mov x2, x20
; WATCHOS-NEXT:    mov x3, x19
; WATCHOS-NEXT:    bl ___umodti3
; WATCHOS-NEXT:    stp x25, x26, [x24]
; WATCHOS-NEXT:    ldp x29, x30, [sp, #64] ; 16-byte Folded Reload
; WATCHOS-NEXT:    stp x0, x1, [x23]
; WATCHOS-NEXT:    ldp x20, x19, [sp, #48] ; 16-byte Folded Reload
; WATCHOS-NEXT:    ldp x22, x21, [sp, #32] ; 16-byte Folded Reload
; WATCHOS-NEXT:    ldp x24, x23, [sp, #16] ; 16-byte Folded Reload
; WATCHOS-NEXT:    ldp x26, x25, [sp], #80 ; 16-byte Folded Reload
; WATCHOS-NEXT:    ret
  %q = udiv i128 %n, %d
  %r = urem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}
