; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-unknown-linux-gnu --global-isel=true --fast-isel=false --regalloc=greedy < %s \
; RUN:     | FileCheck --check-prefix=GLOBAL_ISEL_GREEDY_RA %s
; RUN: llc -mtriple=aarch64-unknown-linux-gnu --global-isel=true --fast-isel=false --regalloc=fast < %s \
; RUN:     | FileCheck --check-prefix=GLOBAL_ISEL_FAST_RA %s
; RUN: llc -mtriple=aarch64-unknown-linux-gnu --global-isel=false --fast-isel=true --regalloc=greedy < %s \
; RUN:     | FileCheck --check-prefix=FAST_ISEL_GREEDY_RA %s
; RUN: llc -mtriple=aarch64-unknown-linux-gnu --global-isel=false --fast-isel=true --regalloc=fast < %s \
; RUN:     | FileCheck --check-prefix=FAST_ISEL_FAST_RA %s
; RUN: llc -mtriple=aarch64-unknown-linux-gnu --global-isel=false --fast-isel=false --regalloc=greedy < %s \
; RUN:     | FileCheck --check-prefix=GREEDY_RA %s
; RUN: llc -mtriple=aarch64-unknown-linux-gnu --global-isel=false --fast-isel=false --regalloc=fast < %s \
; RUN:     | FileCheck --check-prefix=FAST_RA %s

; Test rm constraints on AArch64 under both ISel frameworks.

define i64 @test_rm_output() {
; GLOBAL_ISEL_GREEDY_RA-LABEL: test_rm_output:
; GLOBAL_ISEL_GREEDY_RA:       // %bb.0: // %entry
; GLOBAL_ISEL_GREEDY_RA-NEXT:    sub sp, sp, #16
; GLOBAL_ISEL_GREEDY_RA-NEXT:    .cfi_def_cfa_offset 16
; GLOBAL_ISEL_GREEDY_RA-NEXT:    //APP
; GLOBAL_ISEL_GREEDY_RA-NEXT:    // x0
; GLOBAL_ISEL_GREEDY_RA-NEXT:    //NO_APP
; GLOBAL_ISEL_GREEDY_RA-NEXT:    add sp, sp, #16
; GLOBAL_ISEL_GREEDY_RA-NEXT:    ret
;
; GLOBAL_ISEL_FAST_RA-LABEL: test_rm_output:
; GLOBAL_ISEL_FAST_RA:       // %bb.0: // %entry
; GLOBAL_ISEL_FAST_RA-NEXT:    sub sp, sp, #16
; GLOBAL_ISEL_FAST_RA-NEXT:    .cfi_def_cfa_offset 16
; GLOBAL_ISEL_FAST_RA-NEXT:    //APP
; GLOBAL_ISEL_FAST_RA-NEXT:    // x0
; GLOBAL_ISEL_FAST_RA-NEXT:    //NO_APP
; GLOBAL_ISEL_FAST_RA-NEXT:    add sp, sp, #16
; GLOBAL_ISEL_FAST_RA-NEXT:    ret
;
; FAST_ISEL_GREEDY_RA-LABEL: test_rm_output:
; FAST_ISEL_GREEDY_RA:       // %bb.0: // %entry
; FAST_ISEL_GREEDY_RA-NEXT:    sub sp, sp, #16
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_def_cfa_offset 16
; FAST_ISEL_GREEDY_RA-NEXT:    //APP
; FAST_ISEL_GREEDY_RA-NEXT:    // x8
; FAST_ISEL_GREEDY_RA-NEXT:    //NO_APP
; FAST_ISEL_GREEDY_RA-NEXT:    str x8, [sp, #8]
; FAST_ISEL_GREEDY_RA-NEXT:    mov x0, x8
; FAST_ISEL_GREEDY_RA-NEXT:    add sp, sp, #16
; FAST_ISEL_GREEDY_RA-NEXT:    ret
;
; FAST_ISEL_FAST_RA-LABEL: test_rm_output:
; FAST_ISEL_FAST_RA:       // %bb.0: // %entry
; FAST_ISEL_FAST_RA-NEXT:    sub sp, sp, #16
; FAST_ISEL_FAST_RA-NEXT:    .cfi_def_cfa_offset 16
; FAST_ISEL_FAST_RA-NEXT:    //APP
; FAST_ISEL_FAST_RA-NEXT:    // x8
; FAST_ISEL_FAST_RA-NEXT:    //NO_APP
; FAST_ISEL_FAST_RA-NEXT:    str x8, [sp, #8]
; FAST_ISEL_FAST_RA-NEXT:    mov x0, x8
; FAST_ISEL_FAST_RA-NEXT:    add sp, sp, #16
; FAST_ISEL_FAST_RA-NEXT:    ret
;
; GREEDY_RA-LABEL: test_rm_output:
; GREEDY_RA:       // %bb.0: // %entry
; GREEDY_RA-NEXT:    sub sp, sp, #16
; GREEDY_RA-NEXT:    .cfi_def_cfa_offset 16
; GREEDY_RA-NEXT:    //APP
; GREEDY_RA-NEXT:    // x0
; GREEDY_RA-NEXT:    //NO_APP
; GREEDY_RA-NEXT:    add sp, sp, #16
; GREEDY_RA-NEXT:    ret
;
; FAST_RA-LABEL: test_rm_output:
; FAST_RA:       // %bb.0: // %entry
; FAST_RA-NEXT:    sub sp, sp, #16
; FAST_RA-NEXT:    .cfi_def_cfa_offset 16
; FAST_RA-NEXT:    //APP
; FAST_RA-NEXT:    // x0
; FAST_RA-NEXT:    //NO_APP
; FAST_RA-NEXT:    add sp, sp, #16
; FAST_RA-NEXT:    ret
entry:
  %out = alloca i64, align 8
  callbr void @llvm.asm.constraint.br()
      to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:
  %0 = tail call i64 asm "# $0", "=rm"()
  br label %asm.merge

asm.pref.mem:
  call void asm "# $0", "=*rm"(ptr elementtype(i64) %out)
  %1 = load i64, ptr %out, align 8
  br label %asm.merge

asm.merge:
  %2 = phi i64 [ %0, %asm.pref.reg ], [ %1, %asm.pref.mem ]
  ret i64 %2
}

declare void @llvm.asm.constraint.br()
