; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=aarch64-apple-darwin -verify-machineinstrs %s -o - | FileCheck %s --check-prefixes=CHECK-DARWIN
; RUN: llc -mtriple=aarch64-unknown-unknown -verify-machineinstrs %s -o - | FileCheck %s --check-prefixes=CHECK

define <4 x float> @insert_zero(ptr %a) {
; CHECK-DARWIN-LABEL: insert_zero:
; CHECK-DARWIN:       ; %bb.0: ; %entry
; CHECK-DARWIN-NEXT:  Lloh0:
; CHECK-DARWIN-NEXT:    adrp x8, lCPI0_0@PAGE
; CHECK-DARWIN-NEXT:    ldr q0, [x0]
; CHECK-DARWIN-NEXT:  Lloh1:
; CHECK-DARWIN-NEXT:    ldr q1, [x8, lCPI0_0@PAGEOFF]
; CHECK-DARWIN-NEXT:    and.16b v0, v0, v1
; CHECK-DARWIN-NEXT:    ret
; CHECK-DARWIN-NEXT:    .loh AdrpLdr Lloh0, Lloh1
;
; CHECK-LABEL: insert_zero:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ldr q0, [x0]
; CHECK-NEXT:    mov v0.s[3], wzr
; CHECK-NEXT:    ret

entry:
  %vec = load <4 x float>, ptr %a, align 4
  %vec_set_lane = insertelement <4 x float> %vec, float 0.000000e+00, i64 3
  ret <4 x float> %vec_set_lane
}
