; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64 -verify-machineinstrs -global-isel=0 %s -o - | FileCheck %s --check-prefixes=CHECK,CHECK-SD
; RUN: llc -mtriple=aarch64 -verify-machineinstrs -mattr=-fp-armv8 %s -o - | FileCheck %s --check-prefix=CHECK-NOFP

define i1 @isfinite_bf16(bfloat %x) {
; CHECK-LABEL: isfinite_bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    // kill: def $h0 killed $h0 def $s0
; CHECK-NEXT:    fmov w9, s0
; CHECK-NEXT:    mov w8, #32640 // =0x7f80
; CHECK-NEXT:    and w9, w9, #0x7fff
; CHECK-NEXT:    cmp w9, w8
; CHECK-NEXT:    cset w0, lt
; CHECK-NEXT:    ret
;
; CHECK-NOFP-LABEL: isfinite_bf16:
; CHECK-NOFP:       // %bb.0: // %entry
; CHECK-NOFP-NEXT:    mov w8, #32640 // =0x7f80
; CHECK-NOFP-NEXT:    and w9, w0, #0x7fff
; CHECK-NOFP-NEXT:    cmp w9, w8
; CHECK-NOFP-NEXT:    cset w0, lt
; CHECK-NOFP-NEXT:    ret
entry:
  %0 = tail call i1 @llvm.is.fpclass.bf16(bfloat %x, i32 504)  ; 0x1f8 = "finite"
  ret i1 %0
}

define i1 @not_isfinite_bf16(bfloat %x) {
; CHECK-LABEL: not_isfinite_bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    // kill: def $h0 killed $h0 def $s0
; CHECK-NEXT:    fmov w9, s0
; CHECK-NEXT:    mov w8, #32639 // =0x7f7f
; CHECK-NEXT:    and w9, w9, #0x7fff
; CHECK-NEXT:    cmp w9, w8
; CHECK-NEXT:    cset w0, gt
; CHECK-NEXT:    ret
;
; CHECK-NOFP-LABEL: not_isfinite_bf16:
; CHECK-NOFP:       // %bb.0: // %entry
; CHECK-NOFP-NEXT:    mov w8, #32639 // =0x7f7f
; CHECK-NOFP-NEXT:    and w9, w0, #0x7fff
; CHECK-NOFP-NEXT:    cmp w9, w8
; CHECK-NOFP-NEXT:    cset w0, gt
; CHECK-NOFP-NEXT:    ret
entry:
  %0 = tail call i1 @llvm.is.fpclass.bf16(bfloat %x, i32 519)  ; ~0x1f8 = "~finite"
  ret i1 %0
}


define <4 x i1> @isfinite_v4bf16(<4 x bfloat> %x) {
; CHECK-LABEL: isfinite_v4bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov w8, #32640 // =0x7f80
; CHECK-NEXT:    bic v0.4h, #128, lsl #8
; CHECK-NEXT:    dup v1.4h, w8
; CHECK-NEXT:    cmgt v0.4h, v1.4h, v0.4h
; CHECK-NEXT:    ret
;
; CHECK-NOFP-LABEL: isfinite_v4bf16:
; CHECK-NOFP:       // %bb.0: // %entry
; CHECK-NOFP-NEXT:    mov w8, #32640 // =0x7f80
; CHECK-NOFP-NEXT:    and w9, w0, #0x7fff
; CHECK-NOFP-NEXT:    cmp w9, w8
; CHECK-NOFP-NEXT:    and w9, w1, #0x7fff
; CHECK-NOFP-NEXT:    cset w0, lt
; CHECK-NOFP-NEXT:    cmp w9, w8
; CHECK-NOFP-NEXT:    and w9, w2, #0x7fff
; CHECK-NOFP-NEXT:    cset w1, lt
; CHECK-NOFP-NEXT:    cmp w9, w8
; CHECK-NOFP-NEXT:    and w9, w3, #0x7fff
; CHECK-NOFP-NEXT:    cset w2, lt
; CHECK-NOFP-NEXT:    cmp w9, w8
; CHECK-NOFP-NEXT:    cset w3, lt
; CHECK-NOFP-NEXT:    ret
entry:
  %0 = tail call <4 x i1> @llvm.is.fpclass.v4bf16(<4 x bfloat> %x, i32 504)  ; 0x1f8 = "finite"
  ret <4 x i1> %0
}

define <4 x i1> @not_isfinite_v4bf16(<4 x bfloat> %x) {
; CHECK-LABEL: not_isfinite_v4bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov w8, #32640 // =0x7f80
; CHECK-NEXT:    bic v0.4h, #128, lsl #8
; CHECK-NEXT:    dup v1.4h, w8
; CHECK-NEXT:    cmge v0.4h, v0.4h, v1.4h
; CHECK-NEXT:    ret
;
; CHECK-NOFP-LABEL: not_isfinite_v4bf16:
; CHECK-NOFP:       // %bb.0: // %entry
; CHECK-NOFP-NEXT:    mov w8, #32639 // =0x7f7f
; CHECK-NOFP-NEXT:    and w9, w0, #0x7fff
; CHECK-NOFP-NEXT:    cmp w9, w8
; CHECK-NOFP-NEXT:    and w9, w1, #0x7fff
; CHECK-NOFP-NEXT:    cset w0, gt
; CHECK-NOFP-NEXT:    cmp w9, w8
; CHECK-NOFP-NEXT:    and w9, w2, #0x7fff
; CHECK-NOFP-NEXT:    cset w1, gt
; CHECK-NOFP-NEXT:    cmp w9, w8
; CHECK-NOFP-NEXT:    and w9, w3, #0x7fff
; CHECK-NOFP-NEXT:    cset w2, gt
; CHECK-NOFP-NEXT:    cmp w9, w8
; CHECK-NOFP-NEXT:    cset w3, gt
; CHECK-NOFP-NEXT:    ret
entry:
  %0 = tail call <4 x i1> @llvm.is.fpclass.v4bf16(<4 x bfloat> %x, i32 519)  ; ~0x1f8 = "~finite"
  ret <4 x i1> %0
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK-SD: {{.*}}
