; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=arm64-apple-macosx10.9 < %s | FileCheck %s

define { half, half } @test_sincospi_f16(half %a) #0 {
; CHECK-LABEL: test_sincospi_f16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub sp, sp, #32
; CHECK-NEXT:    stp x29, x30, [sp, #16] ; 16-byte Folded Spill
; CHECK-NEXT:    fcvt s0, h0
; CHECK-NEXT:    add x0, sp, #12
; CHECK-NEXT:    add x1, sp, #8
; CHECK-NEXT:    bl ___sincospif
; CHECK-NEXT:    ldp s1, s0, [sp, #8]
; CHECK-NEXT:    ldp x29, x30, [sp, #16] ; 16-byte Folded Reload
; CHECK-NEXT:    fcvt h0, s0
; CHECK-NEXT:    fcvt h1, s1
; CHECK-NEXT:    add sp, sp, #32
; CHECK-NEXT:    ret
  %result = call { half, half } @llvm.sincospi.f16(half %a)
  ret { half, half } %result
}

define half @test_sincospi_f16_only_use_sin(half %a) #0 {
; CHECK-LABEL: test_sincospi_f16_only_use_sin:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub sp, sp, #32
; CHECK-NEXT:    stp x29, x30, [sp, #16] ; 16-byte Folded Spill
; CHECK-NEXT:    fcvt s0, h0
; CHECK-NEXT:    add x0, sp, #12
; CHECK-NEXT:    add x1, sp, #8
; CHECK-NEXT:    bl ___sincospif
; CHECK-NEXT:    ldr s0, [sp, #12]
; CHECK-NEXT:    ldp x29, x30, [sp, #16] ; 16-byte Folded Reload
; CHECK-NEXT:    fcvt h0, s0
; CHECK-NEXT:    add sp, sp, #32
; CHECK-NEXT:    ret
  %result = call { half, half } @llvm.sincospi.f16(half %a)
  %result.0 = extractvalue { half, half } %result, 0
  ret half %result.0
}

define half @test_sincospi_f16_only_use_cos(half %a) #0 {
; CHECK-LABEL: test_sincospi_f16_only_use_cos:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub sp, sp, #32
; CHECK-NEXT:    stp x29, x30, [sp, #16] ; 16-byte Folded Spill
; CHECK-NEXT:    fcvt s0, h0
; CHECK-NEXT:    add x0, sp, #12
; CHECK-NEXT:    add x1, sp, #8
; CHECK-NEXT:    bl ___sincospif
; CHECK-NEXT:    ldr s0, [sp, #8]
; CHECK-NEXT:    ldp x29, x30, [sp, #16] ; 16-byte Folded Reload
; CHECK-NEXT:    fcvt h0, s0
; CHECK-NEXT:    add sp, sp, #32
; CHECK-NEXT:    ret
  %result = call { half, half } @llvm.sincospi.f16(half %a)
  %result.1 = extractvalue { half, half } %result, 1
  ret half %result.1
}

define { <2 x half>, <2 x half> } @test_sincospi_v2f16(<2 x half> %a) #0 {
; CHECK-LABEL: test_sincospi_v2f16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub sp, sp, #64
; CHECK-NEXT:    ; kill: def $d0 killed $d0 def $q0
; CHECK-NEXT:    mov h1, v0[1]
; CHECK-NEXT:    stp x29, x30, [sp, #48] ; 16-byte Folded Spill
; CHECK-NEXT:    add x0, sp, #28
; CHECK-NEXT:    str q0, [sp] ; 16-byte Spill
; CHECK-NEXT:    add x1, sp, #24
; CHECK-NEXT:    fcvt s0, h1
; CHECK-NEXT:    bl ___sincospif
; CHECK-NEXT:    ldr q0, [sp] ; 16-byte Reload
; CHECK-NEXT:    add x0, sp, #20
; CHECK-NEXT:    add x1, sp, #16
; CHECK-NEXT:    fcvt s0, h0
; CHECK-NEXT:    bl ___sincospif
; CHECK-NEXT:    ldr q0, [sp] ; 16-byte Reload
; CHECK-NEXT:    add x0, sp, #36
; CHECK-NEXT:    add x1, sp, #32
; CHECK-NEXT:    mov h0, v0[2]
; CHECK-NEXT:    fcvt s0, h0
; CHECK-NEXT:    bl ___sincospif
; CHECK-NEXT:    ldr q0, [sp] ; 16-byte Reload
; CHECK-NEXT:    add x0, sp, #44
; CHECK-NEXT:    add x1, sp, #40
; CHECK-NEXT:    mov h0, v0[3]
; CHECK-NEXT:    fcvt s0, h0
; CHECK-NEXT:    bl ___sincospif
; CHECK-NEXT:    ldp s2, s0, [sp, #24]
; CHECK-NEXT:    ldp s3, s1, [sp, #16]
; CHECK-NEXT:    ldp x29, x30, [sp, #48] ; 16-byte Folded Reload
; CHECK-NEXT:    fcvt h4, s0
; CHECK-NEXT:    fcvt h2, s2
; CHECK-NEXT:    fcvt h0, s1
; CHECK-NEXT:    fcvt h1, s3
; CHECK-NEXT:    ldp s5, s3, [sp, #32]
; CHECK-NEXT:    fcvt h3, s3
; CHECK-NEXT:    mov.h v0[1], v4[0]
; CHECK-NEXT:    fcvt h4, s5
; CHECK-NEXT:    mov.h v1[1], v2[0]
; CHECK-NEXT:    ldp s5, s2, [sp, #40]
; CHECK-NEXT:    mov.h v0[2], v3[0]
; CHECK-NEXT:    fcvt h2, s2
; CHECK-NEXT:    fcvt h3, s5
; CHECK-NEXT:    mov.h v1[2], v4[0]
; CHECK-NEXT:    mov.h v0[3], v2[0]
; CHECK-NEXT:    mov.h v1[3], v3[0]
; CHECK-NEXT:    ; kill: def $d0 killed $d0 killed $q0
; CHECK-NEXT:    ; kill: def $d1 killed $d1 killed $q1
; CHECK-NEXT:    add sp, sp, #64
; CHECK-NEXT:    ret
  %result = call { <2 x half>, <2 x half> } @llvm.sincospi.v2f16(<2 x half> %a)
  ret { <2 x half>, <2 x half> } %result
}

define { float, float } @test_sincospi_f32(float %a) #0 {
; CHECK-LABEL: test_sincospi_f32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub sp, sp, #32
; CHECK-NEXT:    stp x29, x30, [sp, #16] ; 16-byte Folded Spill
; CHECK-NEXT:    add x0, sp, #12
; CHECK-NEXT:    add x1, sp, #8
; CHECK-NEXT:    bl ___sincospif
; CHECK-NEXT:    ldp s1, s0, [sp, #8]
; CHECK-NEXT:    ldp x29, x30, [sp, #16] ; 16-byte Folded Reload
; CHECK-NEXT:    add sp, sp, #32
; CHECK-NEXT:    ret
  %result = call { float, float } @llvm.sincospi.f32(float %a)
  ret { float, float } %result
}

define { <3 x float>, <3 x float> } @test_sincospi_v3f32(<3 x float> %a) #0 {
; CHECK-LABEL: test_sincospi_v3f32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub sp, sp, #96
; CHECK-NEXT:    stp x22, x21, [sp, #48] ; 16-byte Folded Spill
; CHECK-NEXT:    add x0, sp, #28
; CHECK-NEXT:    add x1, sp, #24
; CHECK-NEXT:    stp x20, x19, [sp, #64] ; 16-byte Folded Spill
; CHECK-NEXT:    stp x29, x30, [sp, #80] ; 16-byte Folded Spill
; CHECK-NEXT:    str q0, [sp] ; 16-byte Spill
; CHECK-NEXT:    ; kill: def $s0 killed $s0 killed $q0
; CHECK-NEXT:    bl ___sincospif
; CHECK-NEXT:    ldr q0, [sp] ; 16-byte Reload
; CHECK-NEXT:    add x19, sp, #36
; CHECK-NEXT:    add x20, sp, #32
; CHECK-NEXT:    add x0, sp, #36
; CHECK-NEXT:    add x1, sp, #32
; CHECK-NEXT:    mov s0, v0[1]
; CHECK-NEXT:    bl ___sincospif
; CHECK-NEXT:    ldr q0, [sp] ; 16-byte Reload
; CHECK-NEXT:    add x21, sp, #44
; CHECK-NEXT:    add x22, sp, #40
; CHECK-NEXT:    add x0, sp, #44
; CHECK-NEXT:    add x1, sp, #40
; CHECK-NEXT:    mov s0, v0[2]
; CHECK-NEXT:    bl ___sincospif
; CHECK-NEXT:    ldp s1, s0, [sp, #24]
; CHECK-NEXT:    ldp x29, x30, [sp, #80] ; 16-byte Folded Reload
; CHECK-NEXT:    ld1.s { v0 }[1], [x19]
; CHECK-NEXT:    ld1.s { v1 }[1], [x20]
; CHECK-NEXT:    ldp x20, x19, [sp, #64] ; 16-byte Folded Reload
; CHECK-NEXT:    ld1.s { v0 }[2], [x21]
; CHECK-NEXT:    ld1.s { v1 }[2], [x22]
; CHECK-NEXT:    ldp x22, x21, [sp, #48] ; 16-byte Folded Reload
; CHECK-NEXT:    add sp, sp, #96
; CHECK-NEXT:    ret
  %result = call { <3 x float>, <3 x float> } @llvm.sincospi.v3f32(<3 x float> %a)
  ret { <3 x float>, <3 x float> } %result
}

define { <2 x float>, <2 x float> } @test_sincospi_v2f32(<2 x float> %a) #0 {
; CHECK-LABEL: test_sincospi_v2f32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub sp, sp, #64
; CHECK-NEXT:    ; kill: def $d0 killed $d0 def $q0
; CHECK-NEXT:    stp x20, x19, [sp, #32] ; 16-byte Folded Spill
; CHECK-NEXT:    add x0, sp, #28
; CHECK-NEXT:    add x1, sp, #24
; CHECK-NEXT:    stp x29, x30, [sp, #48] ; 16-byte Folded Spill
; CHECK-NEXT:    str q0, [sp] ; 16-byte Spill
; CHECK-NEXT:    ; kill: def $s0 killed $s0 killed $q0
; CHECK-NEXT:    bl ___sincospif
; CHECK-NEXT:    ldr q0, [sp] ; 16-byte Reload
; CHECK-NEXT:    add x19, sp, #20
; CHECK-NEXT:    add x20, sp, #16
; CHECK-NEXT:    add x0, sp, #20
; CHECK-NEXT:    add x1, sp, #16
; CHECK-NEXT:    mov s0, v0[1]
; CHECK-NEXT:    bl ___sincospif
; CHECK-NEXT:    ldp s1, s0, [sp, #24]
; CHECK-NEXT:    ldp x29, x30, [sp, #48] ; 16-byte Folded Reload
; CHECK-NEXT:    ld1.s { v0 }[1], [x19]
; CHECK-NEXT:    ld1.s { v1 }[1], [x20]
; CHECK-NEXT:    ldp x20, x19, [sp, #32] ; 16-byte Folded Reload
; CHECK-NEXT:    ; kill: def $d0 killed $d0 killed $q0
; CHECK-NEXT:    ; kill: def $d1 killed $d1 killed $q1
; CHECK-NEXT:    add sp, sp, #64
; CHECK-NEXT:    ret
  %result = call { <2 x float>, <2 x float> } @llvm.sincospi.v2f32(<2 x float> %a)
  ret { <2 x float>, <2 x float> } %result
}

define { double, double } @test_sincospi_f64(double %a) #0 {
; CHECK-LABEL: test_sincospi_f64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub sp, sp, #32
; CHECK-NEXT:    stp x29, x30, [sp, #16] ; 16-byte Folded Spill
; CHECK-NEXT:    add x0, sp, #8
; CHECK-NEXT:    mov x1, sp
; CHECK-NEXT:    bl ___sincospi
; CHECK-NEXT:    ldp d1, d0, [sp]
; CHECK-NEXT:    ldp x29, x30, [sp, #16] ; 16-byte Folded Reload
; CHECK-NEXT:    add sp, sp, #32
; CHECK-NEXT:    ret
  %result = call { double, double } @llvm.sincospi.f64(double %a)
  ret { double, double } %result
}

define { <2 x double>, <2 x double> } @test_sincospi_v2f64(<2 x double> %a) #0 {
; CHECK-LABEL: test_sincospi_v2f64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub sp, sp, #80
; CHECK-NEXT:    stp x20, x19, [sp, #48] ; 16-byte Folded Spill
; CHECK-NEXT:    add x0, sp, #40
; CHECK-NEXT:    add x1, sp, #32
; CHECK-NEXT:    stp x29, x30, [sp, #64] ; 16-byte Folded Spill
; CHECK-NEXT:    str q0, [sp] ; 16-byte Spill
; CHECK-NEXT:    ; kill: def $d0 killed $d0 killed $q0
; CHECK-NEXT:    bl ___sincospi
; CHECK-NEXT:    ldr q0, [sp] ; 16-byte Reload
; CHECK-NEXT:    add x19, sp, #24
; CHECK-NEXT:    add x20, sp, #16
; CHECK-NEXT:    add x0, sp, #24
; CHECK-NEXT:    add x1, sp, #16
; CHECK-NEXT:    mov d0, v0[1]
; CHECK-NEXT:    bl ___sincospi
; CHECK-NEXT:    ldp d1, d0, [sp, #32]
; CHECK-NEXT:    ldp x29, x30, [sp, #64] ; 16-byte Folded Reload
; CHECK-NEXT:    ld1.d { v0 }[1], [x19]
; CHECK-NEXT:    ld1.d { v1 }[1], [x20]
; CHECK-NEXT:    ldp x20, x19, [sp, #48] ; 16-byte Folded Reload
; CHECK-NEXT:    add sp, sp, #80
; CHECK-NEXT:    ret
  %result = call { <2 x double>, <2 x double> } @llvm.sincospi.v2f64(<2 x double> %a)
  ret { <2 x double>, <2 x double> } %result
}

attributes #0 = { nounwind }
