; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-apple-macosx < %s | FileCheck %s --check-prefix=LE
; RUN: llc -mtriple=aarch64_be-unknown < %s | FileCheck %s --check-prefix=BE

; Test that consecutive byte loads combined via OR with AND masks on individual
; loads are folded into a single wider load + mask at the DAG level.
; This is the pattern from manual bitfield extraction code.
; https://github.com/llvm/llvm-project/issues/191193

; --- Positive tests (should fold to wide load + mask) ---

; High byte masked.
define i16 @load_2_bytes_high_masked(ptr %p) {
; LE-LABEL: load_2_bytes_high_masked:
; LE:       ; %bb.0:
; LE-NEXT:    ldrh w8, [x0]
; LE-NEXT:    and w0, w8, #0x3ff
; LE-NEXT:    ret
;
; BE-LABEL: load_2_bytes_high_masked:
; BE:       // %bb.0:
; BE-NEXT:    ldrh w8, [x0]
; BE-NEXT:    rev w8, w8
; BE-NEXT:    ubfx w0, w8, #16, #10
; BE-NEXT:    ret
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %lo = load i8, ptr %p, align 1
  %hi = load i8, ptr %p1, align 1
  %hi.m = and i8 %hi, 3
  %lo.ext = zext i8 %lo to i16
  %hi.ext = zext i8 %hi.m to i16
  %hi.shift = shl i16 %hi.ext, 8
  %result = or i16 %hi.shift, %lo.ext
  ret i16 %result
}

; Low byte masked.
define i16 @load_2_bytes_low_masked(ptr %p) {
; LE-LABEL: load_2_bytes_low_masked:
; LE:       ; %bb.0:
; LE-NEXT:    ldrh w8, [x0]
; LE-NEXT:    and w0, w8, #0xffffff3f
; LE-NEXT:    ret
;
; BE-LABEL: load_2_bytes_low_masked:
; BE:       // %bb.0:
; BE-NEXT:    ldrh w8, [x0]
; BE-NEXT:    rev w8, w8
; BE-NEXT:    lsr w8, w8, #16
; BE-NEXT:    and w0, w8, #0xffffff3f
; BE-NEXT:    ret
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %lo = load i8, ptr %p, align 1
  %hi = load i8, ptr %p1, align 1
  %lo.m = and i8 %lo, 63
  %lo.ext = zext i8 %lo.m to i16
  %hi.ext = zext i8 %hi to i16
  %hi.shift = shl i16 %hi.ext, 8
  %result = or i16 %hi.shift, %lo.ext
  ret i16 %result
}

; Both bytes masked.
define i16 @load_2_bytes_both_masked(ptr %p) {
; LE-LABEL: load_2_bytes_both_masked:
; LE:       ; %bb.0:
; LE-NEXT:    ldrh w8, [x0]
; LE-NEXT:    mov w9, #783 ; =0x30f
; LE-NEXT:    and w0, w8, w9
; LE-NEXT:    ret
;
; BE-LABEL: load_2_bytes_both_masked:
; BE:       // %bb.0:
; BE-NEXT:    ldrh w9, [x0]
; BE-NEXT:    mov w8, #783 // =0x30f
; BE-NEXT:    rev w9, w9
; BE-NEXT:    and w0, w8, w9, lsr #16
; BE-NEXT:    ret
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %lo = load i8, ptr %p, align 1
  %hi = load i8, ptr %p1, align 1
  %lo.m = and i8 %lo, 15
  %hi.m = and i8 %hi, 3
  %lo.ext = zext i8 %lo.m to i16
  %hi.ext = zext i8 %hi.m to i16
  %hi.shift = shl i16 %hi.ext, 8
  %result = or i16 %hi.shift, %lo.ext
  ret i16 %result
}

; Non-low-bit masks (high bits and non-contiguous).
define i16 @load_2_bytes_noncontiguous_masked(ptr %p) {
; LE-LABEL: load_2_bytes_noncontiguous_masked:
; LE:       ; %bb.0:
; LE-NEXT:    ldrh w8, [x0]
; LE-NEXT:    mov w9, #23205 ; =0x5aa5
; LE-NEXT:    and w0, w8, w9
; LE-NEXT:    ret
;
; BE-LABEL: load_2_bytes_noncontiguous_masked:
; BE:       // %bb.0:
; BE-NEXT:    ldrh w9, [x0]
; BE-NEXT:    mov w8, #23205 // =0x5aa5
; BE-NEXT:    rev w9, w9
; BE-NEXT:    and w0, w8, w9, lsr #16
; BE-NEXT:    ret
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %lo = load i8, ptr %p, align 1
  %hi = load i8, ptr %p1, align 1
  %lo.m = and i8 %lo, 165
  %hi.m = and i8 %hi, 90
  %lo.ext = zext i8 %lo.m to i16
  %hi.ext = zext i8 %hi.m to i16
  %hi.shift = shl i16 %hi.ext, 8
  %result = or i16 %hi.shift, %lo.ext
  ret i16 %result
}

; Four bytes, last byte masked.
define i32 @load_4_bytes_last_masked(ptr %p) {
; LE-LABEL: load_4_bytes_last_masked:
; LE:       ; %bb.0:
; LE-NEXT:    ldr w8, [x0]
; LE-NEXT:    and w0, w8, #0x3fffffff
; LE-NEXT:    ret
;
; BE-LABEL: load_4_bytes_last_masked:
; BE:       // %bb.0:
; BE-NEXT:    ldr w8, [x0]
; BE-NEXT:    rev w8, w8
; BE-NEXT:    and w0, w8, #0x3fffffff
; BE-NEXT:    ret
  %p1 = getelementptr i8, ptr %p, i64 1
  %p2 = getelementptr i8, ptr %p, i64 2
  %p3 = getelementptr i8, ptr %p, i64 3
  %l0 = load i8, ptr %p, align 1
  %l1 = load i8, ptr %p1, align 1
  %l2 = load i8, ptr %p2, align 1
  %l3 = load i8, ptr %p3, align 1
  %l3.m = and i8 %l3, 63
  %e0 = zext i8 %l0 to i32
  %e1 = zext i8 %l1 to i32
  %e2 = zext i8 %l2 to i32
  %e3 = zext i8 %l3.m to i32
  %s1 = shl i32 %e1, 8
  %s2 = shl i32 %e2, 16
  %s3 = shl i32 %e3, 24
  %o1 = or i32 %e0, %s1
  %o2 = or i32 %o1, %s2
  %o3 = or i32 %o2, %s3
  ret i32 %o3
}

; Big-endian byte order on LE target (requires bswap + mask).
; Both targets should fold.
define i16 @load_2_bytes_bswap_masked(ptr %p) {
; LE-LABEL: load_2_bytes_bswap_masked:
; LE:       ; %bb.0:
; LE-NEXT:    ldrh w8, [x0]
; LE-NEXT:    rev w8, w8
; LE-NEXT:    lsr w8, w8, #16
; LE-NEXT:    and w0, w8, #0xffffff03
; LE-NEXT:    ret
;
; BE-LABEL: load_2_bytes_bswap_masked:
; BE:       // %bb.0:
; BE-NEXT:    ldrh w8, [x0]
; BE-NEXT:    and w0, w8, #0xffffff03
; BE-NEXT:    ret
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %lo = load i8, ptr %p, align 1
  %hi = load i8, ptr %p1, align 1
  %hi.m = and i8 %hi, 3
  %lo.ext = zext i8 %lo to i16
  %hi.ext = zext i8 %hi.m to i16
  %lo.shift = shl i16 %lo.ext, 8
  %result = or i16 %lo.shift, %hi.ext
  ret i16 %result
}

; --- Negative tests (should NOT fold) ---

; Non-adjacent loads (gap between them).
define i16 @negative_non_adjacent(ptr %p) {
; LE-LABEL: negative_non_adjacent:
; LE:       ; %bb.0:
; LE-NEXT:    ldrb w8, [x0]
; LE-NEXT:    ldrb w9, [x0, #2]
; LE-NEXT:    bfi w8, w9, #8, #2
; LE-NEXT:    mov w0, w8
; LE-NEXT:    ret
;
; BE-LABEL: negative_non_adjacent:
; BE:       // %bb.0:
; BE-NEXT:    ldrb w8, [x0]
; BE-NEXT:    ldrb w9, [x0, #2]
; BE-NEXT:    bfi w8, w9, #8, #2
; BE-NEXT:    mov w0, w8
; BE-NEXT:    ret
  %p2 = getelementptr inbounds i8, ptr %p, i64 2
  %lo = load i8, ptr %p, align 1
  %hi = load i8, ptr %p2, align 1
  %hi.m = and i8 %hi, 3
  %lo.ext = zext i8 %lo to i16
  %hi.ext = zext i8 %hi.m to i16
  %hi.shift = shl i16 %hi.ext, 8
  %result = or i16 %hi.shift, %lo.ext
  ret i16 %result
}

; Volatile load cannot be combined.
define i16 @negative_volatile(ptr %p) {
; LE-LABEL: negative_volatile:
; LE:       ; %bb.0:
; LE-NEXT:    ldrb w8, [x0]
; LE-NEXT:    ldrb w9, [x0, #1]
; LE-NEXT:    bfi w8, w9, #8, #2
; LE-NEXT:    mov w0, w8
; LE-NEXT:    ret
;
; BE-LABEL: negative_volatile:
; BE:       // %bb.0:
; BE-NEXT:    ldrb w8, [x0]
; BE-NEXT:    ldrb w9, [x0, #1]
; BE-NEXT:    bfi w8, w9, #8, #2
; BE-NEXT:    mov w0, w8
; BE-NEXT:    ret
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %lo = load volatile i8, ptr %p, align 1
  %hi = load i8, ptr %p1, align 1
  %hi.m = and i8 %hi, 3
  %lo.ext = zext i8 %lo to i16
  %hi.ext = zext i8 %hi.m to i16
  %hi.shift = shl i16 %hi.ext, 8
  %result = or i16 %hi.shift, %lo.ext
  ret i16 %result
}

; Non-constant mask.
define i16 @negative_variable_mask(ptr %p, i8 %mask) {
; LE-LABEL: negative_variable_mask:
; LE:       ; %bb.0:
; LE-NEXT:    ldrb w8, [x0, #1]
; LE-NEXT:    ldrb w9, [x0]
; LE-NEXT:    and w8, w8, w1
; LE-NEXT:    orr w0, w9, w8, lsl #8
; LE-NEXT:    ret
;
; BE-LABEL: negative_variable_mask:
; BE:       // %bb.0:
; BE-NEXT:    ldrb w8, [x0, #1]
; BE-NEXT:    ldrb w9, [x0]
; BE-NEXT:    and w8, w8, w1
; BE-NEXT:    orr w0, w9, w8, lsl #8
; BE-NEXT:    ret
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %lo = load i8, ptr %p, align 1
  %hi = load i8, ptr %p1, align 1
  %hi.m = and i8 %hi, %mask
  %lo.ext = zext i8 %lo to i16
  %hi.ext = zext i8 %hi.m to i16
  %hi.shift = shl i16 %hi.ext, 8
  %result = or i16 %hi.shift, %lo.ext
  ret i16 %result
}

; Multi-use: AND result is used elsewhere. The one-use check in
; calculateByteProvider should prevent combining since the AND can't be removed.
declare void @use.i8(i8)
define i16 @negative_multiuse_and(ptr %p) {
; LE-LABEL: negative_multiuse_and:
; LE:       ; %bb.0:
; LE-NEXT:    stp x20, x19, [sp, #-32]! ; 16-byte Folded Spill
; LE-NEXT:    stp x29, x30, [sp, #16] ; 16-byte Folded Spill
; LE-NEXT:    .cfi_def_cfa_offset 32
; LE-NEXT:    .cfi_offset w30, -8
; LE-NEXT:    .cfi_offset w29, -16
; LE-NEXT:    .cfi_offset w19, -24
; LE-NEXT:    .cfi_offset w20, -32
; LE-NEXT:    ldrb w20, [x0, #1]
; LE-NEXT:    ldrb w19, [x0]
; LE-NEXT:    and w0, w20, #0x3
; LE-NEXT:    bl _use.i8
; LE-NEXT:    bfi w19, w20, #8, #2
; LE-NEXT:    ldp x29, x30, [sp, #16] ; 16-byte Folded Reload
; LE-NEXT:    mov w0, w19
; LE-NEXT:    ldp x20, x19, [sp], #32 ; 16-byte Folded Reload
; LE-NEXT:    ret
;
; BE-LABEL: negative_multiuse_and:
; BE:       // %bb.0:
; BE-NEXT:    str x30, [sp, #-32]! // 8-byte Folded Spill
; BE-NEXT:    stp x20, x19, [sp, #16] // 16-byte Folded Spill
; BE-NEXT:    .cfi_def_cfa_offset 32
; BE-NEXT:    .cfi_offset w19, -8
; BE-NEXT:    .cfi_offset w20, -16
; BE-NEXT:    .cfi_offset w30, -32
; BE-NEXT:    ldrb w20, [x0, #1]
; BE-NEXT:    ldrb w19, [x0]
; BE-NEXT:    and w0, w20, #0x3
; BE-NEXT:    bl use.i8
; BE-NEXT:    bfi w19, w20, #8, #2
; BE-NEXT:    mov w0, w19
; BE-NEXT:    ldp x20, x19, [sp, #16] // 16-byte Folded Reload
; BE-NEXT:    ldr x30, [sp], #32 // 8-byte Folded Reload
; BE-NEXT:    ret
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %lo = load i8, ptr %p, align 1
  %hi = load i8, ptr %p1, align 1
  %hi.m = and i8 %hi, 3
  call void @use.i8(i8 %hi.m)
  %lo.ext = zext i8 %lo to i16
  %hi.ext = zext i8 %hi.m to i16
  %hi.shift = shl i16 %hi.ext, 8
  %result = or i16 %hi.shift, %lo.ext
  ret i16 %result
}
