; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple aarch64-none-linux-gnu < %s | FileCheck %s --check-prefixes=CHECK-BASE
; RUN: llc -mtriple aarch64-none-linux-gnu -aggressive-machine-cse < %s | FileCheck %s --check-prefixes=CHECK-AGGRESSIVE-CSE

define void @foo(ptr %buf, <8 x i16> %a) {
; CHECK-BASE-LABEL: foo:
; CHECK-BASE:       // %bb.0: // %entry
; CHECK-BASE-NEXT:    movi v2.2d, #0000000000000000
; CHECK-BASE-NEXT:    // kill: def $q0 killed $q0 def $q0_q1
; CHECK-BASE-NEXT:    zip2 v2.8h, v0.8h, v2.8h
; CHECK-BASE-NEXT:    movi v1.2d, #0000000000000000
; CHECK-BASE-NEXT:    st2 { v0.4h, v1.4h }, [x0], #16
; CHECK-BASE-NEXT:    str q2, [x0]
; CHECK-BASE-NEXT:    ret
;
; CHECK-AGGRESSIVE-CSE-LABEL: foo:
; CHECK-AGGRESSIVE-CSE:       // %bb.0: // %entry
; CHECK-AGGRESSIVE-CSE-NEXT:    // kill: def $q0 killed $q0 def $q0_q1
; CHECK-AGGRESSIVE-CSE-NEXT:    movi v1.2d, #0000000000000000
; CHECK-AGGRESSIVE-CSE-NEXT:    zip2 v2.8h, v0.8h, v1.8h
; CHECK-AGGRESSIVE-CSE-NEXT:    st2 { v0.4h, v1.4h }, [x0], #16
; CHECK-AGGRESSIVE-CSE-NEXT:    str q2, [x0]
; CHECK-AGGRESSIVE-CSE-NEXT:    ret
entry:
  %vzip.i = shufflevector <8 x i16> %a, <8 x i16> <i16 0, i16 0, i16 0, i16 0, i16 poison, i16 poison, i16 poison, i16 poison>, <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 2, i32 10, i32 3, i32 11>
  %vzip1.i = shufflevector <8 x i16> %a, <8 x i16> <i16 poison, i16 poison, i16 poison, i16 poison, i16 0, i16 0, i16 0, i16 0>, <8 x i32> <i32 4, i32 12, i32 5, i32 13, i32 6, i32 14, i32 7, i32 15>
  store <8 x i16> %vzip.i, ptr %buf, align 4
  %add.ptr = getelementptr inbounds i32, ptr %buf, i64 4
  store <8 x i16> %vzip1.i, ptr %add.ptr, align 4
  ret void
}
