# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=aarch64-apple-unknown -run-pass=machine-outliner -verify-machineinstrs -enable-machine-outliner=always %s -o - | FileCheck %s

# Outlining CFI instructions is unsafe if it is not tail called, but otherwise,
# it requires fixups. Show that we don't include CFI instructions in non
# tail call outlined sequences right now. Show that we count CFI instructions
# correctly in the presence of debug info.

--- |
  define void @foo() #0 { ret void }
  define void @bar() #0 { ret void }
  define void @baz() #0 { ret void }
  attributes #0 = { noredzone }

...
---
name:            foo
tracksRegLiveness: true
body:             |
  bb.0:
  liveins: $lr
    ; CHECK-LABEL: name: foo
    ; CHECK: liveins: $lr
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $w9 = ORRWri $wzr, 1
    ; CHECK-NEXT: $w10 = ORRWri $wzr, 2
    ; CHECK-NEXT: $w11 = ORRWri $wzr, 3
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION def_cfa $w29, 16
    ; CHECK-NEXT: $w20 = ORRWri $wzr, 1
    ; CHECK-NEXT: TCRETURNdi @OUTLINED_FUNCTION_0, 0, implicit $sp, implicit-def $w12, implicit-def $w13, implicit-def $w14, implicit-def $w15, implicit $wzr, implicit $sp
    $w9 = ORRWri $wzr, 1
    $w10 = ORRWri $wzr, 2
    $w11 = ORRWri $wzr, 3
    DBG_VALUE $w9, $noreg
    DBG_VALUE $w9, $noreg
    DBG_VALUE $w9, $noreg
    DBG_VALUE $w9, $noreg
    DBG_VALUE $w9, $noreg
    DBG_VALUE $w9, $noreg
    frame-setup CFI_INSTRUCTION def_cfa $w29, 16
    $w20 = ORRWri $wzr, 1
    $w12 = ORRWri $wzr, 1
    $w13 = ORRWri $wzr, 2
    $w14 = ORRWri $wzr, 3
    $w15 = ORRWri $wzr, 4
    RET undef $lr
...
---
name:            bar
tracksRegLiveness: true
body:             |
  bb.0:
  liveins: $lr
    ; CHECK-LABEL: name: bar
    ; CHECK: liveins: $lr
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $w9 = ORRWri $wzr, 1
    ; CHECK-NEXT: $w10 = ORRWri $wzr, 2
    ; CHECK-NEXT: $w11 = ORRWri $wzr, 3
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION def_cfa $w29, 16
    ; CHECK-NEXT: $w21 = ORRWri $wzr, 1
    ; CHECK-NEXT: TCRETURNdi @OUTLINED_FUNCTION_0, 0, implicit $sp, implicit-def $w12, implicit-def $w13, implicit-def $w14, implicit-def $w15, implicit $wzr, implicit $sp
    $w9 = ORRWri $wzr, 1
    $w10 = ORRWri $wzr, 2
    $w11 = ORRWri $wzr, 3
    DBG_VALUE $w9, $noreg
    DBG_VALUE $w9, $noreg
    DBG_VALUE $w9, $noreg
    DBG_VALUE $w9, $noreg
    DBG_VALUE $w9, $noreg
    DBG_VALUE $w9, $noreg
    frame-setup CFI_INSTRUCTION def_cfa $w29, 16
    $w21 = ORRWri $wzr, 1
    $w12 = ORRWri $wzr, 1
    $w13 = ORRWri $wzr, 2
    $w14 = ORRWri $wzr, 3
    $w15 = ORRWri $wzr, 4
    RET undef $lr
...
---
name:            baz
tracksRegLiveness: true
body:             |
  bb.0:
  liveins: $lr
    ; CHECK-LABEL: name: baz
    ; CHECK: liveins: $lr
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $w9 = ORRWri $wzr, 1
    ; CHECK-NEXT: $w10 = ORRWri $wzr, 2
    ; CHECK-NEXT: $w11 = ORRWri $wzr, 3
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: DBG_VALUE $w9, $noreg
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION def_cfa $w29, 16
    ; CHECK-NEXT: $w22 = ORRWri $wzr, 1
    ; CHECK-NEXT: TCRETURNdi @OUTLINED_FUNCTION_0, 0, implicit $sp, implicit-def $w12, implicit-def $w13, implicit-def $w14, implicit-def $w15, implicit $wzr, implicit $sp
    $w9 = ORRWri $wzr, 1
    $w10 = ORRWri $wzr, 2
    $w11 = ORRWri $wzr, 3
    DBG_VALUE $w9, $noreg
    DBG_VALUE $w9, $noreg
    DBG_VALUE $w9, $noreg
    DBG_VALUE $w9, $noreg
    DBG_VALUE $w9, $noreg
    DBG_VALUE $w9, $noreg
    frame-setup CFI_INSTRUCTION def_cfa $w29, 16
    $w22 = ORRWri $wzr, 1
    $w12 = ORRWri $wzr, 1
    $w13 = ORRWri $wzr, 2
    $w14 = ORRWri $wzr, 3
    $w15 = ORRWri $wzr, 4
    RET undef $lr
