# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=aarch64-gnu-linux -mcpu=neoverse-n2 -run-pass=machine-combiner -o - %s | FileCheck %s

# Make sure machine combiner doesn't drop subregister indexes.

---
name:            reassociate_adds2_reassoc
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $q0, $q1, $q2, $q3

    ; CHECK-LABEL: name: reassociate_adds2_reassoc
    ; CHECK: liveins: $q0, $q1, $q2, $q3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fpr128 = COPY $q0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:fpr128 = COPY $q1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:fpr128 = COPY $q2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:fpr128 = COPY $q3
    ; CHECK-NEXT: [[FADDSrr:%[0-9]+]]:fpr32 = nsz reassoc nofpexcept FADDSrr [[COPY]].ssub, [[COPY1]].ssub, implicit $fpcr
    ; CHECK-NEXT: [[FADDSrr1:%[0-9]+]]:fpr32 = nsz reassoc nofpexcept FADDSrr [[COPY2]].ssub, [[COPY3]].ssub, implicit $fpcr
    ; CHECK-NEXT: [[FADDSrr2:%[0-9]+]]:fpr32 = nsz reassoc nofpexcept FADDSrr killed [[FADDSrr1]], killed [[FADDSrr]], implicit $fpcr
    ; CHECK-NEXT: $s0 = COPY [[FADDSrr2]]
    ; CHECK-NEXT: RET_ReallyLR implicit $s0
    %0:fpr128 = COPY $q0
    %1:fpr128 = COPY $q1
    %2:fpr128 = COPY $q2
    %3:fpr128 = COPY $q3
    %4:fpr32 = nsz reassoc nofpexcept FADDSrr %0.ssub, %1.ssub, implicit $fpcr
    %5:fpr32 = nsz reassoc nofpexcept FADDSrr %2.ssub, killed %4, implicit $fpcr
    %6:fpr32 = nsz reassoc nofpexcept FADDSrr killed %5, %3.ssub, implicit $fpcr
    $s0 = COPY %6
    RET_ReallyLR implicit $s0

...
