; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple aarch64 -mattr=+sve | FileCheck %s

define <vscale x 16 x i1> @nxv16i1(<vscale x 16 x i1> %m) {
; CHECK-LABEL: nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p1.b
; CHECK-NEXT:    brkb p0.b, p1/z, p0.b
; CHECK-NEXT:    ret
  %x = call <vscale x 16 x i1> @llvm.mask.beforefirst(<vscale x 16 x i1> %m)
  ret <vscale x 16 x i1> %x
}

define <vscale x 8 x i1> @nxv8i1(<vscale x 8 x i1> %m) {
; CHECK-LABEL: nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p1.h
; CHECK-NEXT:    brkb p0.b, p1/z, p0.b
; CHECK-NEXT:    ret
  %x = call <vscale x 8 x i1> @llvm.mask.beforefirst(<vscale x 8 x i1> %m)
  ret <vscale x 8 x i1> %x
}

define <vscale x 4 x i1> @nxv4i1(<vscale x 4 x i1> %m) {
; CHECK-LABEL: nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p1.s
; CHECK-NEXT:    brkb p0.b, p1/z, p0.b
; CHECK-NEXT:    ret
  %x = call <vscale x 4 x i1> @llvm.mask.beforefirst(<vscale x 4 x i1> %m)
  ret <vscale x 4 x i1> %x
}

define <vscale x 2 x i1> @nxv2i1(<vscale x 2 x i1> %m) {
; CHECK-LABEL: nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    brkb p0.b, p1/z, p0.b
; CHECK-NEXT:    ret
  %x = call <vscale x 2 x i1> @llvm.mask.beforefirst(<vscale x 2 x i1> %m)
  ret <vscale x 2 x i1> %x
}

define <16 x i1> @v16i1(<16 x i1> %m) {
; CHECK-LABEL: v16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    shl v0.16b, v0.16b, #7
; CHECK-NEXT:    mov w8, #16 // =0x10
; CHECK-NEXT:    index z1.b, w8, #-1
; CHECK-NEXT:    cmlt v0.16b, v0.16b, #0
; CHECK-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    umaxv b0, v0.16b
; CHECK-NEXT:    fmov w9, s0
; CHECK-NEXT:    index z0.b, #0, #1
; CHECK-NEXT:    sub w8, w8, w9, uxtb
; CHECK-NEXT:    dup v1.16b, w8
; CHECK-NEXT:    cmhi v0.16b, v1.16b, v0.16b
; CHECK-NEXT:    ret
  %x = call <16 x i1> @llvm.mask.beforefirst(<16 x i1> %m)
  ret <16 x i1> %x
}

define <8 x i1> @v8i1(<8 x i1> %m) {
; CHECK-LABEL: v8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    shl v0.8b, v0.8b, #7
; CHECK-NEXT:    index z1.b, #8, #-1
; CHECK-NEXT:    mov w9, #8 // =0x8
; CHECK-NEXT:    cmlt v0.8b, v0.8b, #0
; CHECK-NEXT:    and v0.8b, v0.8b, v1.8b
; CHECK-NEXT:    index z1.b, #0, #1
; CHECK-NEXT:    umaxv b0, v0.8b
; CHECK-NEXT:    fmov w8, s0
; CHECK-NEXT:    sub w8, w9, w8, uxtb
; CHECK-NEXT:    dup v0.8b, w8
; CHECK-NEXT:    cmhi v0.8b, v0.8b, v1.8b
; CHECK-NEXT:    ret
  %x = call <8 x i1> @llvm.mask.beforefirst(<8 x i1> %m)
  ret <8 x i1> %x
}

define <4 x i1> @v4i1(<4 x i1> %m) {
; CHECK-LABEL: v4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    shl v0.4h, v0.4h, #15
; CHECK-NEXT:    index z1.h, #4, #-1
; CHECK-NEXT:    mov w9, #4 // =0x4
; CHECK-NEXT:    cmlt v0.4h, v0.4h, #0
; CHECK-NEXT:    and v0.8b, v0.8b, v1.8b
; CHECK-NEXT:    index z1.h, #0, #1
; CHECK-NEXT:    umaxv h0, v0.4h
; CHECK-NEXT:    fmov w8, s0
; CHECK-NEXT:    sub w8, w9, w8
; CHECK-NEXT:    dup v0.4h, w8
; CHECK-NEXT:    bic v0.4h, #255, lsl #8
; CHECK-NEXT:    cmhi v0.4h, v0.4h, v1.4h
; CHECK-NEXT:    ret
  %x = call <4 x i1> @llvm.mask.beforefirst(<4 x i1> %m)
  ret <4 x i1> %x
}

define <2 x i1> @v2i1(<2 x i1> %m) {
; CHECK-LABEL: v2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    shl v0.2s, v0.2s, #31
; CHECK-NEXT:    index z1.s, #2, #-1
; CHECK-NEXT:    mov w9, #2 // =0x2
; CHECK-NEXT:    index z2.s, #0, #1
; CHECK-NEXT:    cmlt v0.2s, v0.2s, #0
; CHECK-NEXT:    and v0.8b, v0.8b, v1.8b
; CHECK-NEXT:    movi d1, #0x0000ff000000ff
; CHECK-NEXT:    umaxp v0.2s, v0.2s, v0.2s
; CHECK-NEXT:    fmov w8, s0
; CHECK-NEXT:    sub w8, w9, w8
; CHECK-NEXT:    dup v0.2s, w8
; CHECK-NEXT:    and v0.8b, v0.8b, v1.8b
; CHECK-NEXT:    cmhi v0.2s, v0.2s, v2.2s
; CHECK-NEXT:    ret
  %x = call <2 x i1> @llvm.mask.beforefirst(<2 x i1> %m)
  ret <2 x i1> %x
}

; Widening

define <vscale x 3 x i1> @nxv3i1(<vscale x 3 x i1> %m) {
; CHECK-LABEL: nxv3i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p1.s
; CHECK-NEXT:    brkb p0.b, p1/z, p0.b
; CHECK-NEXT:    ret
  %x = call <vscale x 3 x i1> @llvm.mask.beforefirst(<vscale x 3 x i1> %m)
  ret <vscale x 3 x i1> %x
}

; Splitting

define <vscale x 32 x i1> @nxv32i1(<vscale x 32 x i1> %m) {
; CHECK-LABEL: nxv32i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.b
; CHECK-NEXT:    brkb p0.b, p2/z, p0.b
; CHECK-NEXT:    brkb p1.b, p2/z, p1.b
; CHECK-NEXT:    ptest p0, p0.b
; CHECK-NEXT:    cset w8, ne
; CHECK-NEXT:    sbfx x8, x8, #0, #1
; CHECK-NEXT:    whilelo p3.b, xzr, x8
; CHECK-NEXT:    bic p1.b, p1/z, p1.b, p3.b
; CHECK-NEXT:    ret
  %x = call <vscale x 32 x i1> @llvm.mask.beforefirst(<vscale x 32 x i1> %m)
  ret <vscale x 32 x i1> %x
}
