; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=aarch64-linux-gnu < %s | FileCheck %s

define { <4 x i32>, <4 x i1> } @speculative_load_v4i32_neon(ptr %p, <4 x i1> %mask) {
; CHECK-LABEL: speculative_load_v4i32_neon:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-NEXT:    umov w8, v0.h[0]
; CHECK-NEXT:    tbz w8, #0, .LBB0_2
; CHECK-NEXT:  // %bb.1: // %speculative.load.first.lane
; CHECK-NEXT:    adrp x8, .LCPI0_0
; CHECK-NEXT:    ldr s0, [x0]
; CHECK-NEXT:    ldr d1, [x8, :lo12:.LCPI0_0]
; CHECK-NEXT:    // kill: def $d1 killed $d1 killed $q1
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    movi v1.2d, #0000000000000000
; CHECK-NEXT:    // implicit-def: $q0
; CHECK-NEXT:    // kill: def $d1 killed $d1 killed $q1
; CHECK-NEXT:    ret
  %res = call { <4 x i32>, <4 x i1> } @llvm.masked.speculative.load.v4i32.p0(ptr %p, i32 16, <4 x i1> %mask)
  ret { <4 x i32>, <4 x i1> } %res
}

;; FIXME: If we know the input mask is all-true and the vector is fully aligned,
;;        we should be able to use a normal NEON load here.
define { <2 x double>, <2 x i1> } @speculative_load_v2f64_all_true_fully_aligned_neon(ptr %p) {
; CHECK-LABEL: speculative_load_v2f64_all_true_fully_aligned_neon:
; CHECK:       // %bb.0: // %speculative.load.first.lane
; CHECK-NEXT:    adrp x8, .LCPI1_0
; CHECK-NEXT:    ldr d0, [x0]
; CHECK-NEXT:    ldr d1, [x8, :lo12:.LCPI1_0]
; CHECK-NEXT:    ret
  %res = call { <2 x double>, <2 x i1> } @llvm.masked.speculative.load.v2f64.p0(ptr %p, i32 16, <2 x i1> <i1 true, i1 true>)
  ret { <2 x double>, <2 x i1> } %res
}

define { <2 x double>, <2 x i1> } @speculative_load_v2f64_all_true_partially_aligned_neon(ptr %p) {
; CHECK-LABEL: speculative_load_v2f64_all_true_partially_aligned_neon:
; CHECK:       // %bb.0: // %speculative.load.first.lane
; CHECK-NEXT:    adrp x8, .LCPI2_0
; CHECK-NEXT:    ldr d0, [x0]
; CHECK-NEXT:    ldr d1, [x8, :lo12:.LCPI2_0]
; CHECK-NEXT:    ret
  %res = call { <2 x double>, <2 x i1> } @llvm.masked.speculative.load.v2f64.p0(ptr %p, i32 8, <2 x i1> <i1 true, i1 true>)
  ret { <2 x double>, <2 x i1> } %res
}

define { <vscale x 16 x i8>, <vscale x 16 x i1> } @speculative_load_nxv16i8(ptr %p, <vscale x 16 x i1> %mask) #0 {
; CHECK-LABEL: speculative_load_nxv16i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    setffr
; CHECK-NEXT:    ldff1b { z0.b }, p0/z, [x0]
; CHECK-NEXT:    rdffr p0.b, p0/z
; CHECK-NEXT:    ret
  %res = call { <vscale x 16 x i8>, <vscale x 16 x i1> } @llvm.masked.speculative.load.nxv16i8.p0(ptr %p, i32 1, <vscale x 16 x i1> %mask)
  ret { <vscale x 16 x i8>, <vscale x 16 x i1> } %res
}

define { <vscale x 8 x i16>, <vscale x 8 x i1> } @speculative_load_nxv8i16(ptr %p, <vscale x 8 x i1> %mask) #0 {
; CHECK-LABEL: speculative_load_nxv8i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    setffr
; CHECK-NEXT:    ldff1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    rdffr p0.b, p0/z
; CHECK-NEXT:    ret
  %res = call { <vscale x 8 x i16>, <vscale x 8 x i1> } @llvm.masked.speculative.load.nxv8i16.p0(ptr %p, i32 4, <vscale x 8 x i1> %mask)
  ret { <vscale x 8 x i16>, <vscale x 8 x i1> } %res
}

define { <vscale x 4 x i32>, <vscale x 4 x i1> } @speculative_load_nxv4i32(ptr %p, <vscale x 4 x i1> %mask) #0 {
; CHECK-LABEL: speculative_load_nxv4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    setffr
; CHECK-NEXT:    ldff1w { z0.s }, p0/z, [x0]
; CHECK-NEXT:    rdffr p0.b, p0/z
; CHECK-NEXT:    ret
  %res = call { <vscale x 4 x i32>, <vscale x 4 x i1> } @llvm.masked.speculative.load.nxv4i32.p0(ptr %p, i32 4, <vscale x 4 x i1> %mask)
  ret { <vscale x 4 x i32>, <vscale x 4 x i1> } %res
}

define { <vscale x 2 x i64>, <vscale x 2 x i1> } @speculative_load_nxv2i64(ptr %p, <vscale x 2 x i1> %mask) #0 {
; CHECK-LABEL: speculative_load_nxv2i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    setffr
; CHECK-NEXT:    ldff1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    rdffr p0.b, p0/z
; CHECK-NEXT:    ret
  %res = call { <vscale x 2 x i64>, <vscale x 2 x i1> } @llvm.masked.speculative.load.nxv2i64.p0(ptr %p, i32 8, <vscale x 2 x i1> %mask)
  ret { <vscale x 2 x i64>, <vscale x 2 x i1> } %res
}

define { <vscale x 8 x half>, <vscale x 8 x i1> } @speculative_load_nxv8f16(ptr %p, <vscale x 8 x i1> %mask) #0 {
; CHECK-LABEL: speculative_load_nxv8f16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    setffr
; CHECK-NEXT:    ldff1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    rdffr p0.b, p0/z
; CHECK-NEXT:    ret
  %res = call { <vscale x 8 x half>, <vscale x 8 x i1> } @llvm.masked.speculative.load.nxv8f16.p0(ptr %p, i32 4, <vscale x 8 x i1> %mask)
  ret { <vscale x 8 x half>, <vscale x 8 x i1> } %res
}

define { <vscale x 8 x bfloat>, <vscale x 8 x i1> } @speculative_load_nxv8bf16(ptr %p, <vscale x 8 x i1> %mask) #0 {
; CHECK-LABEL: speculative_load_nxv8bf16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    setffr
; CHECK-NEXT:    ldff1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    rdffr p0.b, p0/z
; CHECK-NEXT:    ret
  %res = call { <vscale x 8 x bfloat>, <vscale x 8 x i1> } @llvm.masked.speculative.load.nxv8bf16.p0(ptr %p, i32 4, <vscale x 8 x i1> %mask)
  ret { <vscale x 8 x bfloat>, <vscale x 8 x i1> } %res
}

define { <vscale x 4 x float>, <vscale x 4 x i1> } @speculative_load_nxv4f32(ptr %p, <vscale x 4 x i1> %mask) #0 {
; CHECK-LABEL: speculative_load_nxv4f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    setffr
; CHECK-NEXT:    ldff1w { z0.s }, p0/z, [x0]
; CHECK-NEXT:    rdffr p0.b, p0/z
; CHECK-NEXT:    ret
  %res = call { <vscale x 4 x float>, <vscale x 4 x i1> } @llvm.masked.speculative.load.nxv4f32.p0(ptr %p, i32 4, <vscale x 4 x i1> %mask)
  ret { <vscale x 4 x float>, <vscale x 4 x i1> } %res
}

define { <vscale x 2 x double>, <vscale x 2 x i1> } @speculative_load_nxv2f64(ptr %p, <vscale x 2 x i1> %mask) #0 {
; CHECK-LABEL: speculative_load_nxv2f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    setffr
; CHECK-NEXT:    ldff1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    rdffr p0.b, p0/z
; CHECK-NEXT:    ret
  %res = call { <vscale x 2 x double>, <vscale x 2 x i1> } @llvm.masked.speculative.load.nxv2f64.p0(ptr %p, i32 8, <vscale x 2 x i1> %mask)
  ret { <vscale x 2 x double>, <vscale x 2 x i1> } %res
}

;; Test basic legalization.

define { <vscale x 2 x i32>, <vscale x 2 x i1> } @speculative_load_nxv2i32_promote(ptr %p, <vscale x 2 x i1> %mask) #0 {
; CHECK-LABEL: speculative_load_nxv2i32_promote:
; CHECK:       // %bb.0:
; CHECK-NEXT:    setffr
; CHECK-NEXT:    ldff1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    rdffr p0.b, p0/z
; CHECK-NEXT:    ret
  %res = call { <vscale x 2 x i32>, <vscale x 2 x i1> } @llvm.masked.speculative.load.nxv2i32.p0(ptr %p, i32 4, <vscale x 2 x i1> %mask)
  ret { <vscale x 2 x i32>, <vscale x 2 x i1> } %res
}

;; FIXME: We can do an AArch64-specific split and use ldnf1w + brkn here.
define { <vscale x 8 x i32>, <vscale x 8 x i1> } @speculative_load_nxv8i32_split(ptr %p, <vscale x 8 x i1> %mask) #0 {
; CHECK-LABEL: speculative_load_nxv8i32_split:
; CHECK:       // %bb.0:
; CHECK-NEXT:    punpklo p0.h, p0.b
; CHECK-NEXT:    setffr
; CHECK-NEXT:    pfalse p1.b
; CHECK-NEXT:    ldff1w { z0.s }, p0/z, [x0]
; CHECK-NEXT:    rdffr p0.b, p0/z
; CHECK-NEXT:    uzp1 p0.h, p0.h, p1.h
; CHECK-NEXT:    ret
  %res = call { <vscale x 8 x i32>, <vscale x 8 x i1> } @llvm.masked.speculative.load.nxv8i32.p0(ptr %p, i32 4, <vscale x 8 x i1> %mask)
  ret { <vscale x 8 x i32>, <vscale x 8 x i1> } %res
}

define { <vscale x 1 x i64>, <vscale x 1 x i1> } @speculative_load_nxv1i64_widen(ptr %p, <vscale x 1 x i1> %mask) #0 {
; CHECK-LABEL: speculative_load_nxv1i64_widen:
; CHECK:       // %bb.0:
; CHECK-NEXT:    setffr
; CHECK-NEXT:    ldff1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    rdffr p0.b, p0/z
; CHECK-NEXT:    ret
  %res = call { <vscale x 1 x i64>, <vscale x 1 x i1> } @llvm.masked.speculative.load.nxv1i64.p0(ptr %p, i32 8, <vscale x 1 x i1> %mask)
  ret { <vscale x 1 x i64>, <vscale x 1 x i1> } %res
}

declare { <4 x i32>, <4 x i1> } @llvm.masked.speculative.load.v4i32.p0(ptr, i32, <4 x i1>)
declare { <2 x double>, <2 x i1> } @llvm.masked.speculative.load.v2f64.p0(ptr, i32, <2 x i1>)
declare { <vscale x 16 x i8>, <vscale x 16 x i1> } @llvm.masked.speculative.load.nxv16i8.p0(ptr, i32, <vscale x 16 x i1>)
declare { <vscale x 8 x i16>, <vscale x 8 x i1> } @llvm.masked.speculative.load.nxv8i16.p0(ptr, i32, <vscale x 8 x i1>)
declare { <vscale x 2 x i32>, <vscale x 2 x i1> } @llvm.masked.speculative.load.nxv2i32.p0(ptr, i32, <vscale x 2 x i1>)
declare { <vscale x 4 x i32>, <vscale x 4 x i1> } @llvm.masked.speculative.load.nxv4i32.p0(ptr, i32, <vscale x 4 x i1>)
declare { <vscale x 8 x i32>, <vscale x 8 x i1> } @llvm.masked.speculative.load.nxv8i32.p0(ptr, i32, <vscale x 8 x i1>)
declare { <vscale x 1 x i64>, <vscale x 1 x i1> } @llvm.masked.speculative.load.nxv1i64.p0(ptr, i32, <vscale x 1 x i1>)
declare { <vscale x 2 x i64>, <vscale x 2 x i1> } @llvm.masked.speculative.load.nxv2i64.p0(ptr, i32, <vscale x 2 x i1>)
declare { <vscale x 8 x half>, <vscale x 8 x i1> } @llvm.masked.speculative.load.nxv8f16.p0(ptr, i32, <vscale x 8 x i1>)
declare { <vscale x 8 x bfloat>, <vscale x 8 x i1> } @llvm.masked.speculative.load.nxv8bf16.p0(ptr, i32, <vscale x 8 x i1>)
declare { <vscale x 4 x float>, <vscale x 4 x i1> } @llvm.masked.speculative.load.nxv4f32.p0(ptr, i32, <vscale x 4 x i1>)
declare { <vscale x 2 x double>, <vscale x 2 x i1> } @llvm.masked.speculative.load.nxv2f64.p0(ptr, i32, <vscale x 2 x i1>)


attributes #0 = { "target-features"="+sve" }
