; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-none-linux-gnu -fast-isel=0 -global-isel=false \
; RUN:     -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,NOLSE
; RUN: llc -mtriple=aarch64-none-linux-gnu -mattr=+lse -fast-isel=0 \
; RUN:     -global-isel=false -verify-machineinstrs < %s | FileCheck %s

; Tests for the __cas* MS builtins on AArch64.  These lower to
; llvm.aarch64.cas* intrinsics and must select the corresponding CAS instruction
; regardless of whether +lse is present in the target features (the _cg ISel
; variants have no feature predicate). When +lse is absent, the AsmPrinter
; brackets the instruction with .arch_extension directives so that assembly
; output re-assembles.

define i32 @test_cas8(ptr %p, i32 %rs, i32 %rt) {
; CHECK-LABEL: test_cas8:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    casb w1, w2, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    mov w0, w1
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.cas8(ptr %p, i32 %rs, i32 %rt)
  ret i32 %r
}

define i32 @test_cas16(ptr %p, i32 %rs, i32 %rt) {
; CHECK-LABEL: test_cas16:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    cash w1, w2, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    mov w0, w1
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.cas16(ptr %p, i32 %rs, i32 %rt)
  ret i32 %r
}

define i32 @test_cas32(ptr %p, i32 %rs, i32 %rt) {
; CHECK-LABEL: test_cas32:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    cas w1, w2, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    mov w0, w1
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.cas32(ptr %p, i32 %rs, i32 %rt)
  ret i32 %r
}

define i64 @test_cas64(ptr %p, i64 %rs, i64 %rt) {
; CHECK-LABEL: test_cas64:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    cas x1, x2, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    mov x0, x1
; CHECK-NEXT:    ret
  %r = call i64 @llvm.aarch64.cas64(ptr %p, i64 %rs, i64 %rt)
  ret i64 %r
}

define i32 @test_casa8(ptr %p, i32 %rs, i32 %rt) {
; CHECK-LABEL: test_casa8:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    casab w1, w2, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    mov w0, w1
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.casa8(ptr %p, i32 %rs, i32 %rt)
  ret i32 %r
}

define i32 @test_casa16(ptr %p, i32 %rs, i32 %rt) {
; CHECK-LABEL: test_casa16:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    casah w1, w2, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    mov w0, w1
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.casa16(ptr %p, i32 %rs, i32 %rt)
  ret i32 %r
}

define i32 @test_casa32(ptr %p, i32 %rs, i32 %rt) {
; CHECK-LABEL: test_casa32:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    casa w1, w2, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    mov w0, w1
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.casa32(ptr %p, i32 %rs, i32 %rt)
  ret i32 %r
}

define i64 @test_casa64(ptr %p, i64 %rs, i64 %rt) {
; CHECK-LABEL: test_casa64:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    casa x1, x2, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    mov x0, x1
; CHECK-NEXT:    ret
  %r = call i64 @llvm.aarch64.casa64(ptr %p, i64 %rs, i64 %rt)
  ret i64 %r
}

define i32 @test_casl8(ptr %p, i32 %rs, i32 %rt) {
; CHECK-LABEL: test_casl8:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    caslb w1, w2, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    mov w0, w1
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.casl8(ptr %p, i32 %rs, i32 %rt)
  ret i32 %r
}

define i32 @test_casl16(ptr %p, i32 %rs, i32 %rt) {
; CHECK-LABEL: test_casl16:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    caslh w1, w2, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    mov w0, w1
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.casl16(ptr %p, i32 %rs, i32 %rt)
  ret i32 %r
}

define i32 @test_casl32(ptr %p, i32 %rs, i32 %rt) {
; CHECK-LABEL: test_casl32:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    casl w1, w2, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    mov w0, w1
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.casl32(ptr %p, i32 %rs, i32 %rt)
  ret i32 %r
}

define i64 @test_casl64(ptr %p, i64 %rs, i64 %rt) {
; CHECK-LABEL: test_casl64:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    casl x1, x2, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    mov x0, x1
; CHECK-NEXT:    ret
  %r = call i64 @llvm.aarch64.casl64(ptr %p, i64 %rs, i64 %rt)
  ret i64 %r
}
