; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-windows-msvc -fast-isel=0 -global-isel=false \
; RUN:     -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,NOLSE
; RUN: llc -mtriple=aarch64-windows-msvc -mattr=+lse -fast-isel=0 \
; RUN:     -global-isel=false -verify-machineinstrs < %s | FileCheck %s

; Tests for the __swp* MS builtins on AArch64. These lower to
; llvm.aarch64.swp* intrinsics and must select SWP* regardless of whether
; +lse is present in the target features (the _cg ISel variants have no
; feature predicate). When +lse is absent, the AsmPrinter brackets the
; instruction with .arch_extension directives so that assembly output
; re-assembles.

define i32 @test_swp8(ptr %p, i32 %v) {
; CHECK-LABEL: test_swp8:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swpb w1, w0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.swp8(ptr %p, i32 %v)
  ret i32 %r
}

define i32 @test_swp16(ptr %p, i32 %v) {
; CHECK-LABEL: test_swp16:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swph w1, w0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.swp16(ptr %p, i32 %v)
  ret i32 %r
}

define i32 @test_swp32(ptr %p, i32 %v) {
; CHECK-LABEL: test_swp32:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swp w1, w0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.swp32(ptr %p, i32 %v)
  ret i32 %r
}

define i64 @test_swp64(ptr %p, i64 %v) {
; CHECK-LABEL: test_swp64:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swp x1, x0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i64 @llvm.aarch64.swp64(ptr %p, i64 %v)
  ret i64 %r
}

define i32 @test_swpa8(ptr %p, i32 %v) {
; CHECK-LABEL: test_swpa8:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swpab w1, w0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.swpa8(ptr %p, i32 %v)
  ret i32 %r
}

define i32 @test_swpa16(ptr %p, i32 %v) {
; CHECK-LABEL: test_swpa16:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swpah w1, w0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.swpa16(ptr %p, i32 %v)
  ret i32 %r
}

define i32 @test_swpa32(ptr %p, i32 %v) {
; CHECK-LABEL: test_swpa32:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swpa w1, w0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.swpa32(ptr %p, i32 %v)
  ret i32 %r
}

define i64 @test_swpa64(ptr %p, i64 %v) {
; CHECK-LABEL: test_swpa64:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swpa x1, x0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i64 @llvm.aarch64.swpa64(ptr %p, i64 %v)
  ret i64 %r
}

define i32 @test_swpl8(ptr %p, i32 %v) {
; CHECK-LABEL: test_swpl8:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swplb w1, w0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.swpl8(ptr %p, i32 %v)
  ret i32 %r
}

define i32 @test_swpl16(ptr %p, i32 %v) {
; CHECK-LABEL: test_swpl16:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swplh w1, w0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.swpl16(ptr %p, i32 %v)
  ret i32 %r
}

define i32 @test_swpl32(ptr %p, i32 %v) {
; CHECK-LABEL: test_swpl32:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swpl w1, w0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.swpl32(ptr %p, i32 %v)
  ret i32 %r
}

define i64 @test_swpl64(ptr %p, i64 %v) {
; CHECK-LABEL: test_swpl64:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swpl x1, x0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i64 @llvm.aarch64.swpl64(ptr %p, i64 %v)
  ret i64 %r
}

define i32 @test_swpal8(ptr %p, i32 %v) {
; CHECK-LABEL: test_swpal8:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swpalb w1, w0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.swpal8(ptr %p, i32 %v)
  ret i32 %r
}

define i32 @test_swpal16(ptr %p, i32 %v) {
; CHECK-LABEL: test_swpal16:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swpalh w1, w0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.swpal16(ptr %p, i32 %v)
  ret i32 %r
}

define i32 @test_swpal32(ptr %p, i32 %v) {
; CHECK-LABEL: test_swpal32:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swpal w1, w0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.swpal32(ptr %p, i32 %v)
  ret i32 %r
}

define i64 @test_swpal64(ptr %p, i64 %v) {
; CHECK-LABEL: test_swpal64:
; CHECK:       // %bb.0:
; NOLSE-NEXT:    .arch_extension lse
; CHECK-NEXT:    swpal x1, x0, [x0]
; NOLSE-NEXT:    .arch_extension nolse
; CHECK-NEXT:    ret
  %r = call i64 @llvm.aarch64.swpal64(ptr %p, i64 %v)
  ret i64 %r
}
