; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-windows-msvc -fast-isel=0 -global-isel=false \
; RUN:     -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=aarch64-windows-msvc -mattr=+rcpc -fast-isel=0 \
; RUN:     -global-isel=false -verify-machineinstrs < %s | FileCheck %s

; Tests for the __ldapr* MS builtins on AArch64. These lower to the
; llvm.aarch64.ldaprN intrinsics and must select ldaprb/h/w/x regardless
; of whether +rcpc is present in the target features (the _cg ISel variants
; have no feature predicate).

define i32 @test_ldapr8(ptr %p) {
; CHECK-LABEL: test_ldapr8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldaprb w0, [x0]
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.ldapr8(ptr %p)
  ret i32 %r
}

define i32 @test_ldapr16(ptr %p) {
; CHECK-LABEL: test_ldapr16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldaprh w0, [x0]
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.ldapr16(ptr %p)
  ret i32 %r
}

define i32 @test_ldapr32(ptr %p) {
; CHECK-LABEL: test_ldapr32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldapr w0, [x0]
; CHECK-NEXT:    ret
  %r = call i32 @llvm.aarch64.ldapr32(ptr %p)
  ret i32 %r
}

define i64 @test_ldapr64(ptr %p) {
; CHECK-LABEL: test_ldapr64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldapr x0, [x0]
; CHECK-NEXT:    ret
  %r = call i64 @llvm.aarch64.ldapr64(ptr %p)
  ret i64 %r
}