; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-linux-gnu --mattr=+neon,+fptoint < %s | FileCheck %s

; Check that fp -> int -> fp conversions can be
; lowered to the NEON FRINT*Z instructions for
; fixed vectors.

; FRINT32Z

define <2 x float> @frint32z_v2_f32_i32_f32(<2 x float> %in) {
; CHECK-LABEL: frint32z_v2_f32_i32_f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint32z v0.2s, v0.2s
; CHECK-NEXT:    ret
    %res = fptosi <2 x float> %in to <2 x i32>
    %res2 = sitofp <2 x i32> %res to <2 x float>
    ret <2 x float> %res2
}

define <4 x float> @frint32z_v4_f32_i32_f32(<4 x float> %in) {
; CHECK-LABEL: frint32z_v4_f32_i32_f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint32z v0.4s, v0.4s
; CHECK-NEXT:    ret
    %res = fptosi <4 x float> %in to <4 x i32>
    %res2 = sitofp <4 x i32> %res to <4 x float>
    ret <4 x float> %res2
}

define <2 x double> @frint32z_f64_i32_f64(<2 x double> %in) {
; CHECK-LABEL: frint32z_f64_i32_f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint32z v0.2d, v0.2d
; CHECK-NEXT:    ret
    %res = fptosi <2 x double> %in to <2 x i32>
    %res2 = sitofp <2 x i32> %res to <2 x double>
    ret <2 x double> %res2
}

; FRINT64Z

define <2 x double> @frint64z_f64_i64_f64(<2 x double> %in) {
; CHECK-LABEL: frint64z_f64_i64_f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint64z v0.2d, v0.2d
; CHECK-NEXT:    ret
    %res = fptosi <2 x double> %in to <2 x i64>
    %res2 = sitofp <2 x i64> %res to <2 x double>
    ret <2 x double> %res2
}

define <2 x float> @frint64z_v2_f32_i64_f32(<2 x float> %in) {
; CHECK-LABEL: frint64z_v2_f32_i64_f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint64z v0.2s, v0.2s
; CHECK-NEXT:    ret
    %res = fptosi <2 x float> %in to <2 x i64>
    %res2 = sitofp <2 x i64> %res to <2 x float>
    ret <2 x float> %res2
}

define <4 x float> @frint64z_v4_f32_i64_f32(<4 x float> %in) {
; CHECK-LABEL: frint64z_v4_f32_i64_f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint64z v0.4s, v0.4s
; CHECK-NEXT:    ret
    %res = fptosi <4 x float> %in to <4 x i64>
    %res2 = sitofp <4 x i64> %res to <4 x float>
    ret <4 x float> %res2
}
