; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple aarch64 | FileCheck %s
; RUN: llc < %s -mtriple aarch64_be | FileCheck %s

; Representative tests for each class of STNP lowering logic that shouldn't apply
; when optimizing for size.

define void @test_stnp_v2f64_Os(ptr %p, <2 x double> %v) #0 {
; CHECK-LABEL: test_stnp_v2f64_Os:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str q0, [x0]
; CHECK-NEXT:    ret
  store <2 x double> %v, ptr %p, align 1, !nontemporal !0
  ret void
}

define void @test_stnp_v2f64_Oz(ptr %p, <2 x double> %v) #1 {
; CHECK-LABEL: test_stnp_v2f64_Oz:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str q0, [x0]
; CHECK-NEXT:    ret
  store <2 x double> %v, ptr %p, align 1, !nontemporal !0
  ret void
}

define void @test_stnp_v2f32_Os(ptr %p, <2 x float> %v) #0 {
; CHECK-LABEL: test_stnp_v2f32_Os:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str d0, [x0]
; CHECK-NEXT:    ret
  store <2 x float> %v, ptr %p, align 1, !nontemporal !0
  ret void
}

define void @test_stnp_v2f32_Oz(ptr %p, <2 x float> %v) #1 {
; CHECK-LABEL: test_stnp_v2f32_Oz:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str d0, [x0]
; CHECK-NEXT:    ret
  store <2 x float> %v, ptr %p, align 1, !nontemporal !0
  ret void
}

define void @test_stnp_i64_Os(ptr %p, i64 %v) #0 {
; CHECK-LABEL: test_stnp_i64_Os:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x1, [x0]
; CHECK-NEXT:    ret
  store i64 %v, ptr %p, align 1, !nontemporal !0
  ret void
}

define void @test_stnp_i64_Oz(ptr %p, i64 %v) #1 {
; CHECK-LABEL: test_stnp_i64_Oz:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x1, [x0]
; CHECK-NEXT:    ret
  store i64 %v, ptr %p, align 1, !nontemporal !0
  ret void
}

define void @test_stnp_v32i8_Os(<32 x i8> %v, ptr %ptr) #0 {
; CHECK-LABEL: test_stnp_v32i8_Os:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    stp q0, q1, [x0]
; CHECK-NEXT:    ret
entry:
  store <32 x i8> %v, ptr %ptr, align 4, !nontemporal !0
  ret void
}

define void @test_stnp_v32i8_Oz(<32 x i8> %v, ptr %ptr) #1 {
; CHECK-LABEL: test_stnp_v32i8_Oz:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    stp q0, q1, [x0]
; CHECK-NEXT:    ret
entry:
  store <32 x i8> %v, ptr %ptr, align 4, !nontemporal !0
  ret void
}

!0 = !{ i32 1 }

attributes #0 = { optsize }
attributes #1 = { minsize optsize }
