# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=aarch64 -run-pass=postra-machine-sink -o - %s | FileCheck %s

---
name:            test_undef_use_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_undef_use_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $x1 = COPY killed renamable $x0, implicit undef $x2
  ; CHECK-NEXT:   $x2 = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   RET_ReallyLR implicit $x1
  bb.0:
    liveins: $x0, $x2
    successors: %bb.1

    renamable $x1 = COPY killed renamable $x0, implicit undef $x2
    $x2 = COPY $xzr

  bb.1:
    liveins: $x1
    RET_ReallyLR implicit $x1
...
---
name:            test_internal_read_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_internal_read_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $x1 = COPY killed renamable $x0, implicit-def $x2, implicit internal $x2
  ; CHECK-NEXT:   $x3 = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   RET_ReallyLR implicit $x1
  bb.0:
    liveins: $x0
    successors: %bb.1

    renamable $x1 = COPY killed renamable $x0, implicit-def $x2, implicit internal $x2
    $x3 = COPY $xzr

  bb.1:
    liveins: $x1
    RET_ReallyLR implicit $x1
...
