; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-linux-gnu < %s | FileCheck %s
;
; Test ensures that the compiler generates no extra instructions
; for __builtin_clzg output type conversion
;
; IR for this test was generated from the following source code:
; #include <stdint.h>
; int32_t foo8(uint8_t x) { return __builtin_clzg(x); }
; int32_t foo16(uint16_t x) { return __builtin_clzg(x); }

define i32 @foo8(i8 %0) {
; CHECK-LABEL: foo8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and w8, w0, #0xff
; CHECK-NEXT:    clz w8, w8
; CHECK-NEXT:    sub w0, w8, #24
; CHECK-NEXT:    ret
  %2 = tail call i8 @llvm.ctlz.i8(i8 %0, i1 false)
  %3 = zext nneg i8 %2 to i32
  ret i32 %3
}

define i32 @foo16(i16 %0) {
; CHECK-LABEL: foo16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and w8, w0, #0xffff
; CHECK-NEXT:    clz w8, w8
; CHECK-NEXT:    sub w0, w8, #16
; CHECK-NEXT:    ret
  %2 = tail call i16 @llvm.ctlz.i16(i16 %0, i1 false)
  %3 = zext nneg i16 %2 to i32
  ret i32 %3
}
