# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=aarch64-none-linux-gnu -run-pass prologepilog -frame-pointer=none -o - %s | FileCheck %s
---
name: test_addsxri_scalable_offset
stack:
  - { id: 0, type: default, size: 4, alignment: 4, stack-id: default }
  - { id: 1, type: default, size: 16, alignment: 16, stack-id: scalable-vector }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_addsxri_scalable_offset
    ; CHECK: liveins: $fp
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: early-clobber $sp = frame-setup STRXpre killed $fp, $sp, -16 :: (store (s64) into %stack.2)
    ; CHECK-NEXT: $sp = frame-setup ADDVL_XXI $sp, -1, implicit $vg
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x38, 0x1e, 0x22
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION offset $w29, -16
    ; CHECK-NEXT: $x8 = ADDXri $sp, 12, 0
    ; CHECK-NEXT: $x8 = ADDVL_XXI $x8, 1, implicit $vg
    ; CHECK-NEXT: $x8 = ADDSXri $x8, 0, 0, implicit-def $nzcv
    ; CHECK-NEXT: $sp = frame-destroy ADDVL_XXI $sp, 1, implicit $vg
    ; CHECK-NEXT: early-clobber $sp, $fp = frame-destroy LDRXpost $sp, 16 :: (load (s64) from %stack.2)
    ; CHECK-NEXT: RET_ReallyLR implicit $x8
    $x8 = ADDSXri %stack.0, 0, 0, implicit-def $nzcv
    RET_ReallyLR implicit $x8
...
