# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=aarch64 -run-pass=register-coalescer -o - %s | FileCheck %s
---
name:            reproducer
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: reproducer
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $w0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr32 = COPY $w0
  ; CHECK-NEXT:   undef [[MOVIv2d_ns:%[0-9]+]].qsub1:zpr2 = MOVIv2d_ns 0, implicit-def [[MOVIv2d_ns]]
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64sp = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   TBNZW [[COPY1]], 0, %bb.3
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVIv2d_ns:%[0-9]+]].dsub:zpr2 = LDRDui [[COPY2]], 0, implicit-def [[MOVIv2d_ns]].zsub
  ; CHECK-NEXT:   ST2Twov2d [[MOVIv2d_ns]].zsub_qsub1, [[COPY]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   STR_ZXI [[MOVIv2d_ns]].zsub1, [[COPY]], 1
  ; CHECK-NEXT:   STR_ZXI [[MOVIv2d_ns]].zsub1, [[COPY]], 0
  ; CHECK-NEXT:   B %bb.1
  bb.0:
    liveins: $w0, $x1
    %0:gpr64common = COPY $x1
    %1:gpr32 = COPY $w0
    %2:gpr32 = COPY %1:gpr32
    undef %8.qsub1:qq = MOVIv2d_ns 0
    %4:zpr = SUBREG_TO_REG 0, %8.qsub1:qq, %subreg.zsub
    %5:gpr64sp = COPY $xzr

  bb.1:
    TBNZW %2:gpr32, 0, %bb.3
    B %bb.2

  bb.2:
    %8.dsub:qq = LDRDui %5:gpr64sp, 0, implicit-def %8.qsub0:qq
    ST2Twov2d %8:qq, %0:gpr64common

  bb.3:
    STR_ZXI %4:zpr, %0:gpr64common, 1
    STR_ZXI %4:zpr, %0:gpr64common, 0
    B %bb.1
...
---
name:            reproducer2
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: reproducer2
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $w0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr32 = COPY $w0
  ; CHECK-NEXT:   undef [[MOVIv2d_ns:%[0-9]+]].zsub:zpr2 = MOVIv2d_ns 0
  ; CHECK-NEXT:   [[MOVIv2d_ns:%[0-9]+]].qsub1:zpr2 = MOVIv2d_ns 0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64sp = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   TBNZW [[COPY1]], 0, %bb.3
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVIv2d_ns:%[0-9]+]].dsub:zpr2 = LDRDui [[COPY2]], 0, implicit-def [[MOVIv2d_ns]].zsub
  ; CHECK-NEXT:   ST2Twov2d [[MOVIv2d_ns]].zsub_qsub1, [[COPY]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   STR_ZXI [[MOVIv2d_ns]].zsub1, [[COPY]], 1
  ; CHECK-NEXT:   STR_ZXI [[MOVIv2d_ns]].zsub1, [[COPY]], 0
  ; CHECK-NEXT:   B %bb.1
  bb.0:
    liveins: $w0, $x1
    %0:gpr64common = COPY $x1
    %1:gpr32 = COPY $w0
    %2:gpr32 = COPY %1:gpr32
    undef %8.qsub0:qq = MOVIv2d_ns 0
    %8.qsub1:qq = MOVIv2d_ns 0
    %4:zpr = SUBREG_TO_REG 0, %8.qsub1:qq, %subreg.zsub
    %5:gpr64sp = COPY $xzr

  bb.1:
    TBNZW %2:gpr32, 0, %bb.3
    B %bb.2

  bb.2:
    %8.dsub:qq = LDRDui %5:gpr64sp, 0, implicit-def %8.qsub0:qq
    ST2Twov2d %8:qq, %0:gpr64common

  bb.3:
    STR_ZXI %4:zpr, %0:gpr64common, 1
    STR_ZXI %4:zpr, %0:gpr64common, 0
    B %bb.1
...
---
name:            reproducer3
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: reproducer3
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $w0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr32 = COPY $w0
  ; CHECK-NEXT:   undef [[MOVIv2d_ns:%[0-9]+]].qsub1:zpr2 = MOVIv2d_ns 0
  ; CHECK-NEXT:   [[MOVIv2d_ns:%[0-9]+]].zsub:zpr2 = MOVIv2d_ns 0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64sp = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   TBNZW [[COPY1]], 0, %bb.3
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVIv2d_ns:%[0-9]+]].dsub1:zpr2 = LDRDui [[COPY2]], 0, implicit-def [[MOVIv2d_ns]].qsub1
  ; CHECK-NEXT:   ST2Twov2d [[MOVIv2d_ns]].zsub_qsub1, [[COPY]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   STR_ZXI [[MOVIv2d_ns]].zsub0, [[COPY]], 1
  ; CHECK-NEXT:   STR_ZXI [[MOVIv2d_ns]].zsub0, [[COPY]], 0
  ; CHECK-NEXT:   B %bb.1
  bb.0:
    liveins: $w0, $x1
    %0:gpr64common = COPY $x1
    %1:gpr32 = COPY $w0
    %2:gpr32 = COPY %1:gpr32
    undef %8.qsub1:qq = MOVIv2d_ns 0
    %8.qsub0:qq = MOVIv2d_ns 0
    %4:zpr = SUBREG_TO_REG 0, %8.qsub0:qq, %subreg.zsub
    %5:gpr64sp = COPY $xzr

  bb.1:
    TBNZW %2:gpr32, 0, %bb.3
    B %bb.2

  bb.2:
    %8.dsub1:qq = LDRDui %5:gpr64sp, 0, implicit-def %8.qsub1:qq
    ST2Twov2d %8:qq, %0:gpr64common

  bb.3:
    STR_ZXI %4:zpr, %0:gpr64common, 1
    STR_ZXI %4:zpr, %0:gpr64common, 0
    B %bb.1
...
