; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
;
; This is a reduced version of pr164181.ll, which failed with subreg liveness enabled
; after adding the implicit-def for a SUBREG_TO_REG to mark the top 32-bits of a register
; being written by a MOVi32imm instruction. This previously failed the machine verifier
; because the liverange for the top 32-bits weren't updated when rematerializing the
; MOVi32imm.
;
; RUN: llc -verify-machineinstrs -enable-subreg-liveness=true < %s | FileCheck %s
; RUN: llc -verify-machineinstrs -enable-subreg-liveness=false < %s | FileCheck %s
target triple = "aarch64-unknown-linux-gnu"

define void @f(i1 %var_0, i64 %var_2, i64 %var_11, ptr %arr_3, ptr %arr_4, ptr %arr_7, ptr %arr_13, ptr %invariant.gep875.us, ptr %arrayidx384.us, i16 %0, i1 %tobool435.not.us, ptr %gep876.us, i16 %cond464.in.us, ptr %1, i16 %conv227.us, i1 %cmp378.us) #0 {
; CHECK-LABEL: f:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    str x30, [sp, #-96]! // 8-byte Folded Spill
; CHECK-NEXT:    stp x28, x27, [sp, #16] // 16-byte Folded Spill
; CHECK-NEXT:    stp x26, x25, [sp, #32] // 16-byte Folded Spill
; CHECK-NEXT:    stp x24, x23, [sp, #48] // 16-byte Folded Spill
; CHECK-NEXT:    stp x22, x21, [sp, #64] // 16-byte Folded Spill
; CHECK-NEXT:    stp x20, x19, [sp, #80] // 16-byte Folded Spill
; CHECK-NEXT:    .cfi_def_cfa_offset 96
; CHECK-NEXT:    .cfi_offset w19, -8
; CHECK-NEXT:    .cfi_offset w20, -16
; CHECK-NEXT:    .cfi_offset w21, -24
; CHECK-NEXT:    .cfi_offset w22, -32
; CHECK-NEXT:    .cfi_offset w23, -40
; CHECK-NEXT:    .cfi_offset w24, -48
; CHECK-NEXT:    .cfi_offset w25, -56
; CHECK-NEXT:    .cfi_offset w26, -64
; CHECK-NEXT:    .cfi_offset w27, -72
; CHECK-NEXT:    .cfi_offset w28, -80
; CHECK-NEXT:    .cfi_offset w30, -96
; CHECK-NEXT:    ldrb w9, [sp, #152]
; CHECK-NEXT:    ldrh w10, [sp, #144]
; CHECK-NEXT:    mov x19, #-18403 // =0xffffffffffffb81d
; CHECK-NEXT:    ldr x11, [sp, #136]
; CHECK-NEXT:    ldrh w12, [sp, #128]
; CHECK-NEXT:    mov x8, xzr
; CHECK-NEXT:    ldr x13, [sp, #120]
; CHECK-NEXT:    ldrb w14, [sp, #112]
; CHECK-NEXT:    mov w15, wzr
; CHECK-NEXT:    ldrh w16, [sp, #104]
; CHECK-NEXT:    ldr x17, [sp, #96]
; CHECK-NEXT:    mov w18, #149 // =0x95
; CHECK-NEXT:    movk x19, #58909, lsl #16
; CHECK-NEXT:    mov w20, #-18978 // =0xffffb5de
; CHECK-NEXT:    mov w21, #1 // =0x1
; CHECK-NEXT:    mov w22, #-7680 // =0xffffe200
; CHECK-NEXT:    mov w23, #36006 // =0x8ca6
; CHECK-NEXT:    mov x25, xzr
; CHECK-NEXT:    mov x24, xzr
; CHECK-NEXT:  .LBB0_1: // %for.body99.us
; CHECK-NEXT:    // =>This Loop Header: Depth=1
; CHECK-NEXT:    // Child Loop BB0_4 Depth 2
; CHECK-NEXT:    // Child Loop BB0_10 Depth 2
; CHECK-NEXT:    mov w27, w15
; CHECK-NEXT:    mov x26, x25
; CHECK-NEXT:    mov x28, x24
; CHECK-NEXT:    b .LBB0_4
; CHECK-NEXT:  .LBB0_2: // in Loop: Header=BB0_4 Depth=2
; CHECK-NEXT:    mov w25, #1 // =0x1
; CHECK-NEXT:  .LBB0_3: // %for.inc371.us
; CHECK-NEXT:    // in Loop: Header=BB0_4 Depth=2
; CHECK-NEXT:    mul w27, w15, w20
; CHECK-NEXT:    mov x28, xzr
; CHECK-NEXT:    mov x26, x2
; CHECK-NEXT:    tbz w0, #0, .LBB0_9
; CHECK-NEXT:  .LBB0_4: // %for.body194.us
; CHECK-NEXT:    // Parent Loop BB0_1 Depth=1
; CHECK-NEXT:    // => This Inner Loop Header: Depth=2
; CHECK-NEXT:    orr x15, x28, x19
; CHECK-NEXT:    mov x24, x28
; CHECK-NEXT:    strh w10, [x13]
; CHECK-NEXT:    strb w18, [x5]
; CHECK-NEXT:    str x15, [x4]
; CHECK-NEXT:    mov w15, w27
; CHECK-NEXT:    str x8, [x11]
; CHECK-NEXT:    str x1, [x3]
; CHECK-NEXT:    tbz w14, #0, .LBB0_2
; CHECK-NEXT:  // %bb.5: // %if.then327.us
; CHECK-NEXT:    // in Loop: Header=BB0_4 Depth=2
; CHECK-NEXT:    cbnz w21, .LBB0_7
; CHECK-NEXT:  // %bb.6: // %cond.true331.us
; CHECK-NEXT:    // in Loop: Header=BB0_4 Depth=2
; CHECK-NEXT:    ldrsb w27, [x8]
; CHECK-NEXT:    b .LBB0_8
; CHECK-NEXT:  .LBB0_7: // in Loop: Header=BB0_4 Depth=2
; CHECK-NEXT:    mov w27, wzr
; CHECK-NEXT:  .LBB0_8: // %cond.end345.us
; CHECK-NEXT:    // in Loop: Header=BB0_4 Depth=2
; CHECK-NEXT:    mov x25, xzr
; CHECK-NEXT:    strh w27, [x3]
; CHECK-NEXT:    str x26, [x6]
; CHECK-NEXT:    b .LBB0_3
; CHECK-NEXT:  .LBB0_9: // %for.cond376.preheader.us
; CHECK-NEXT:    // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    mov x26, xzr
; CHECK-NEXT:    mov w27, wzr
; CHECK-NEXT:  .LBB0_10: // %for.body380.us
; CHECK-NEXT:    // Parent Loop BB0_1 Depth=1
; CHECK-NEXT:    // => This Inner Loop Header: Depth=2
; CHECK-NEXT:    ands w28, w0, #0x1
; CHECK-NEXT:    orr x26, x26, #0x1
; CHECK-NEXT:    strh w16, [x7]
; CHECK-NEXT:    csel w30, w23, w22, ne
; CHECK-NEXT:    tst w12, #0xffff
; CHECK-NEXT:    csel w21, wzr, w27, eq
; CHECK-NEXT:    cmp w28, #0
; CHECK-NEXT:    str w30, [x17]
; CHECK-NEXT:    csel w27, w27, w21, ne
; CHECK-NEXT:    tbnz w9, #0, .LBB0_10
; CHECK-NEXT:  // %bb.11: // in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    mov w21, #1 // =0x1
; CHECK-NEXT:    b .LBB0_1
entry:
  br label %for.body99.us

for.body99.us:                                    ; preds = %for.inc505.us, %entry
  %mul287985.us = phi i16 [ 0, %entry ], [ %mul287986.us, %for.inc505.us ]
  %mul354905.us = phi i64 [ 0, %entry ], [ %mul354907.us, %for.inc505.us ]
  %sub283896.us = phi i64 [ 0, %entry ], [ %sub283897.us, %for.inc505.us ]
  %conv96880.us4 = phi i64 [ 0, %entry ], [ 0, %for.inc505.us ]
  br label %for.body194.us

for.body380.us:                                   ; preds = %for.cond376.preheader.us, %for.inc505.us
  %indvars.iv10181 = phi i64 [ 0, %for.cond376.preheader.us ], [ %indvars.iv.next1019, %for.inc505.us ]
  %2 = phi i8 [ 0, %for.cond376.preheader.us ], [ %3, %for.inc505.us ]
  store i16 %0, ptr %invariant.gep875.us, align 2
  %arrayidx416.us = getelementptr i16, ptr %arr_13, i64 %indvars.iv10181
  %conv419.us = select i1 %var_0, i32 36006, i32 -7680
  store i32 %conv419.us, ptr %arrayidx384.us, align 4
  br i1 %var_0, label %for.inc505.us, label %if.then436.us

if.then436.us:                                    ; preds = %for.body380.us
  %cond464.in.us6 = load i16, ptr null, align 2
  %tobool465.not.us = icmp eq i16 %cond464.in.us, 0
  %spec.select = select i1 %tobool465.not.us, i8 0, i8 %2
  br label %for.inc505.us

for.inc505.us:                                    ; preds = %if.then436.us, %for.body380.us
  %3 = phi i8 [ %2, %for.body380.us ], [ %spec.select, %if.then436.us ]
  %indvars.iv.next1019 = or i64 %indvars.iv10181, 1
  br i1 %cmp378.us, label %for.body380.us, label %for.body99.us

for.body194.us:                                   ; preds = %for.inc371.us, %for.body99.us
  %mul287986.us = phi i16 [ %mul287985.us, %for.body99.us ], [ %mul287.us, %for.inc371.us ]
  %mul354906.us = phi i64 [ %mul354905.us, %for.body99.us ], [ %var_11, %for.inc371.us ]
  %sub283897.us = phi i64 [ %sub283896.us, %for.body99.us ], [ 0, %for.inc371.us ]
  store i16 %conv227.us, ptr %gep876.us, align 2
  store i8 -107, ptr %arr_7, align 1
  %sub283.us = or i64 %sub283897.us, -434259939
  store i64 %sub283.us, ptr %arr_4, align 8
  %mul287.us = mul i16 %mul287986.us, -18978
  store i64 0, ptr %1, align 8
  store i64 %var_2, ptr %arr_3, align 8
  br i1 %tobool435.not.us, label %if.then327.us, label %for.inc371.us

if.then327.us:                                    ; preds = %for.body194.us
  %tobool330.not.us = icmp eq i32 0, 0
  br i1 %tobool330.not.us, label %cond.end345.us, label %cond.true331.us

cond.true331.us:                                  ; preds = %if.then327.us
  %4 = load i8, ptr null, align 1
  %5 = sext i8 %4 to i16
  br label %cond.end345.us

cond.end345.us:                                   ; preds = %cond.true331.us, %if.then327.us
  %cond346.us = phi i16 [ %5, %cond.true331.us ], [ 0, %if.then327.us ]
  store i16 %cond346.us, ptr %arr_3, align 2
  store i64 %mul354906.us, ptr %arr_13, align 8
  br label %for.inc371.us

for.inc371.us:                                    ; preds = %cond.end345.us, %for.body194.us
  %mul354907.us = phi i64 [ 1, %for.body194.us ], [ 0, %cond.end345.us ]
  br i1 %var_0, label %for.body194.us, label %for.cond376.preheader.us

for.cond376.preheader.us:                         ; preds = %for.inc371.us
  %arrayidx384.us9 = getelementptr i16, ptr null, i64 %conv96880.us4
  br label %for.body380.us
}

attributes #0 = { "frame-pointer"="non-leaf" }
