; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O0 -mtriple=aarch64-unknown-linux-gnu -verify-machineinstrs < %s | FileCheck %s

define void @test() nounwind {
; CHECK-LABEL: test:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sub sp, sp, #32
; CHECK-NEXT:    str x30, [sp, #16] // 8-byte Spill
; CHECK-NEXT:    mov x0, xzr
; CHECK-NEXT:    str x0, [sp] // 8-byte Spill
; CHECK-NEXT:    mov x1, xzr
; CHECK-NEXT:    str x1, [sp, #8] // 8-byte Spill
; CHECK-NEXT:    bl returns_arg
; CHECK-NEXT:    ldr x0, [sp] // 8-byte Reload
; CHECK-NEXT:    ldr x1, [sp, #8] // 8-byte Reload
; CHECK-NEXT:    bl accepts_arg
; CHECK-NEXT:    ldr x30, [sp, #16] // 8-byte Reload
; CHECK-NEXT:    add sp, sp, #32
; CHECK-NEXT:    ret
  %x = call i128 @returns_arg(i128 0)
  call void @accepts_arg(i128 %x)
  ret void
}

declare i128 @returns_arg(i128 returned)
declare void @accepts_arg(i128)
