; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -mtriple=aarch64 | FileCheck %s

define i64 @f(i64 %0, i64 %1) {
; CHECK-LABEL: f:
; CHECK:       // %bb.0:
; CHECK-NEXT:    orr x8, x1, #0x1
; CHECK-NEXT:    mov x10, #-9223372036854775808 // =0x8000000000000000
; CHECK-NEXT:    add x8, x8, x0
; CHECK-NEXT:    adds x8, x8, x0
; CHECK-NEXT:    lsl x9, x8, #1
; CHECK-NEXT:    cinv x10, x10, pl
; CHECK-NEXT:    cmp x8, x9, asr #1
; CHECK-NEXT:    csel x0, x10, x9, ne
; CHECK-NEXT:    ret
  %3 = or i64 1, %1
  %4 = add i64 %3, %0
  %5 = add nsw i64 %4, %0
  %6 = call i64 @llvm.sshl.sat.i64(i64 %5, i64 1)
  ret i64 %6
}

declare i64 @llvm.sshl.sat.i64(i64, i64)
