; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -mtriple=aarch64 | FileCheck %s

define i8 @f(<16 x i8> %vec, i32 %idx) {
; CHECK-LABEL: f:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sub sp, sp, #16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mov w8, #1 // =0x1
; CHECK-NEXT:    mov x9, sp
; CHECK-NEXT:    str q0, [sp]
; CHECK-NEXT:    sub w8, w8, w0
; CHECK-NEXT:    bfxil x9, x8, #0, #4
; CHECK-NEXT:    ldrb w0, [x9]
; CHECK-NEXT:    add sp, sp, #16
; CHECK-NEXT:    ret
  %sub = sub nuw i32 1, %idx
  %extract = extractelement <16 x i8> %vec, i32 %sub
  ret i8 %extract
}
