; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=arm64-apple-ios-8.0.0 | FileCheck -check-prefix CHECK -check-prefix CHECK-DARWIN %s
; RUN: llc < %s -mtriple=aarch64-unknown-windows-msvc | FileCheck -check-prefix CHECK -check-prefix CHECK-WIN %s

declare void @standard_cc_func()
declare preserve_mostcc void @preserve_mostcc_func()

; Registers r9-r15 should be saved before the call of a function
; with a standard calling convention.
define preserve_mostcc void @preserve_mostcc1() nounwind {
; CHECK-DARWIN-LABEL: preserve_mostcc1:
; CHECK-DARWIN:       ; %bb.0: ; %entry
; CHECK-DARWIN-NEXT:    str x15, [sp, #-80]! ; 8-byte Folded Spill
; CHECK-DARWIN-NEXT:    stp x14, x13, [sp, #16] ; 16-byte Folded Spill
; CHECK-DARWIN-NEXT:    stp x12, x11, [sp, #32] ; 16-byte Folded Spill
; CHECK-DARWIN-NEXT:    stp x10, x9, [sp, #48] ; 16-byte Folded Spill
; CHECK-DARWIN-NEXT:    stp x29, x30, [sp, #64] ; 16-byte Folded Spill
; CHECK-DARWIN-NEXT:    bl _standard_cc_func
; CHECK-DARWIN-NEXT:    ldp x29, x30, [sp, #64] ; 16-byte Folded Reload
; CHECK-DARWIN-NEXT:    ldp x10, x9, [sp, #48] ; 16-byte Folded Reload
; CHECK-DARWIN-NEXT:    ldp x12, x11, [sp, #32] ; 16-byte Folded Reload
; CHECK-DARWIN-NEXT:    ldp x14, x13, [sp, #16] ; 16-byte Folded Reload
; CHECK-DARWIN-NEXT:    ldr x15, [sp], #80 ; 8-byte Folded Reload
; CHECK-DARWIN-NEXT:    ret
;
; CHECK-WIN-LABEL: preserve_mostcc1:
; CHECK-WIN:       // %bb.0: // %entry
; CHECK-WIN-NEXT:    stp x30, x9, [sp, #-64]! // 16-byte Folded Spill
; CHECK-WIN-NEXT:    stp x10, x11, [sp, #16] // 16-byte Folded Spill
; CHECK-WIN-NEXT:    stp x12, x13, [sp, #32] // 16-byte Folded Spill
; CHECK-WIN-NEXT:    stp x14, x15, [sp, #48] // 16-byte Folded Spill
; CHECK-WIN-NEXT:    bl standard_cc_func
; CHECK-WIN-NEXT:    ldp x14, x15, [sp, #48] // 16-byte Folded Reload
; CHECK-WIN-NEXT:    ldp x12, x13, [sp, #32] // 16-byte Folded Reload
; CHECK-WIN-NEXT:    ldp x10, x11, [sp, #16] // 16-byte Folded Reload
; CHECK-WIN-NEXT:    ldp x30, x9, [sp], #64 // 16-byte Folded Reload
; CHECK-WIN-NEXT:    ret
entry:
  call void @standard_cc_func()
  ret void
}

; Registers r9-r15 don't need to be saved if one
; function with preserve_mostcc calling convention calls another
; function with preserve_mostcc calling convention, because the
; callee wil save these registers anyways.
define preserve_mostcc void @preserve_mostcc2() nounwind {
; CHECK-DARWIN-LABEL: preserve_mostcc2:
; CHECK-DARWIN:       ; %bb.0: ; %entry
; CHECK-DARWIN-NEXT:    stp x29, x30, [sp, #-16]! ; 16-byte Folded Spill
; CHECK-DARWIN-NEXT:    bl _preserve_mostcc_func
; CHECK-DARWIN-NEXT:    ldp x29, x30, [sp], #16 ; 16-byte Folded Reload
; CHECK-DARWIN-NEXT:    ret
;
; CHECK-WIN-LABEL: preserve_mostcc2:
; CHECK-WIN:       // %bb.0: // %entry
; CHECK-WIN-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-WIN-NEXT:    bl preserve_mostcc_func
; CHECK-WIN-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-WIN-NEXT:    ret
entry:
  call preserve_mostcc void @preserve_mostcc_func()
  ret void
}

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
