; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple arm64e-apple-darwin -mattr=+pauth-lr -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -mtriple arm64e-apple-darwin -mattr=+pauth-lr -global-isel -global-isel-abort=1 -verify-machineinstrs | FileCheck %s

; TODO: The 171615 instructions are always unchecked, so auth-check modes don't change output

target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"

define i64 @test_resign_with_pc_ia_ia(i64 %arg, i64 %arg1, i64 %arg2, i64 %arg3) {
; CHECK-LABEL: test_resign_with_pc_ia_ia:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov x17, x0
; CHECK-NEXT:    mov x16, x1
; CHECK-NEXT:    mov x15, x2
; CHECK-NEXT:    autia171615
; CHECK-NEXT:    mov x0, x17
; CHECK-NEXT:    pacia x0, x3
; CHECK-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth.with.pc.and.resign(i64 %arg, i32 0, i64 %arg1, i64 %arg2, i32 0, i64 %arg3)
  ret i64 %tmp
}

define i64 @test_resign_with_pc_ib_ia(i64 %arg, i64 %arg1, i64 %arg2, i64 %arg3) {
; CHECK-LABEL: test_resign_with_pc_ib_ia:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov x17, x0
; CHECK-NEXT:    mov x16, x1
; CHECK-NEXT:    mov x15, x2
; CHECK-NEXT:    autib171615
; CHECK-NEXT:    mov x0, x17
; CHECK-NEXT:    pacia x0, x3
; CHECK-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth.with.pc.and.resign(i64 %arg, i32 1, i64 %arg1, i64 %arg2, i32 0, i64 %arg3)
  ret i64 %tmp
}

define i64 @test_resign_with_pc_ia_ib(i64 %arg, i64 %arg1, i64 %arg2, i64 %arg3) {
; CHECK-LABEL: test_resign_with_pc_ia_ib:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov x17, x0
; CHECK-NEXT:    mov x16, x1
; CHECK-NEXT:    mov x15, x2
; CHECK-NEXT:    autia171615
; CHECK-NEXT:    mov x0, x17
; CHECK-NEXT:    pacib x0, x3
; CHECK-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth.with.pc.and.resign(i64 %arg, i32 0, i64 %arg1, i64 %arg2, i32 1, i64 %arg3)
  ret i64 %tmp
}

define i64 @test_resign_with_pc_ib_ib(i64 %arg, i64 %arg1, i64 %arg2, i64 %arg3) {
; CHECK-LABEL: test_resign_with_pc_ib_ib:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov x17, x0
; CHECK-NEXT:    mov x16, x1
; CHECK-NEXT:    mov x15, x2
; CHECK-NEXT:    autib171615
; CHECK-NEXT:    mov x0, x17
; CHECK-NEXT:    pacib x0, x3
; CHECK-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth.with.pc.and.resign(i64 %arg, i32 1, i64 %arg1, i64 %arg2, i32 1, i64 %arg3)
  ret i64 %tmp
}

define i64 @test_resign_with_pc_iza_ib(i64 %arg, i64 %arg1, i64 %arg2) {
; CHECK-LABEL: test_resign_with_pc_iza_ib:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov x17, x0
; CHECK-NEXT:    mov x16, #0 ; =0x0
; CHECK-NEXT:    mov x15, x1
; CHECK-NEXT:    autia171615
; CHECK-NEXT:    mov x0, x17
; CHECK-NEXT:    pacib x0, x2
; CHECK-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth.with.pc.and.resign(i64 %arg, i32 0, i64 0, i64 %arg1, i32 1, i64 %arg2)
  ret i64 %tmp
}

define i64 @test_resign_with_pc_ia_izb(i64 %arg, i64 %arg1, i64 %arg2) {
; CHECK-LABEL: test_resign_with_pc_ia_izb:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov x17, x0
; CHECK-NEXT:    mov x16, x1
; CHECK-NEXT:    mov x15, x2
; CHECK-NEXT:    autia171615
; CHECK-NEXT:    mov x0, x17
; CHECK-NEXT:    pacizb x0
; CHECK-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth.with.pc.and.resign(i64 %arg, i32 0, i64 %arg1, i64 %arg2, i32 1, i64 0)
  ret i64 %tmp
}

declare i64 @llvm.ptrauth.auth.with.pc.and.resign(i64, i32, i64, i64, i32, i64)
