# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=aarch64 -start-before=register-coalescer -stop-after=virtregrewriter -enable-subreg-liveness=false -o - %s | FileCheck %s
# RUN: llc -mtriple=aarch64 -start-before=register-coalescer -stop-after=virtregrewriter -enable-subreg-liveness=true -o - %s | FileCheck %s
---
name: test
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x1
    ; CHECK-LABEL: name: test
    ; CHECK: liveins: $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $x0 = COPY $x1
    ; CHECK-NEXT: renamable $w1 = ORRWrr $wzr, renamable $w0, implicit-def renamable $x1
    ; CHECK-NEXT: RET_ReallyLR implicit $x1, implicit $x0
    %190:gpr64 = COPY killed $x1
    %191:gpr32 = COPY %190.sub_32:gpr64
    %192:gpr32 = ORRWrr $wzr, killed %191:gpr32
    %193:gpr64all = SUBREG_TO_REG 0, killed %192:gpr32, %subreg.sub_32
    $x0 = COPY killed %190:gpr64
    $x1 = COPY killed %193:gpr64all
    RET_ReallyLR implicit $x1, implicit $x0
...

# In this test, we should avoid adding an implicit-def to ORRXri, because
# the register class will already be gpr64sp.
---
name: test2
tracksRegLiveness: true
frameInfo:
  adjustsStack:    true
body:             |
  bb.0:
    ; CHECK-LABEL: name: test2
    ; CHECK: renamable $x8 = IMPLICIT_DEF
    ; CHECK-NEXT: renamable $x9 = ORRXri renamable $x8, 8128
    ; CHECK-NEXT: $x2 = ORRXri renamable $x8, 8128
    ; CHECK-NEXT: RET_ReallyLR implicit killed renamable $x8, implicit killed renamable $x9
    %0:gpr64 = IMPLICIT_DEF
    %1:gpr64sp = ORRXri %0, 8128
    %3:gpr64 = SUBREG_TO_REG 0, %1.sub_32, %subreg.sub_32
    %2:gpr64all = COPY killed %1
    $x2 = COPY killed %2
    RET_ReallyLR implicit %0, implicit %3
...
