; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64-none-linux-gnu -mattr=+neon | FileCheck %s

define ptr @test_scalar_msub(ptr %a, ptr %b) {
; CHECK-LABEL: test_scalar_msub:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ldp w8, w11, [x1]
; CHECK-NEXT:    ldp w9, w10, [x0]
; CHECK-NEXT:    mul w12, w8, w9
; CHECK-NEXT:    mul w8, w10, w8
; CHECK-NEXT:    madd w8, w11, w9, w8
; CHECK-NEXT:    msub w9, w11, w10, w12
; CHECK-NEXT:    stp w9, w8, [x0]
; CHECK-NEXT:    ret
entry:
  %0 = load i32, ptr %a, align 4
  %1 = load i32, ptr %b, align 4
  %mul = mul nsw i32 %1, %0
  %_M_imag = getelementptr inbounds i8, ptr %a, i64 4
  %2 = load i32, ptr %_M_imag, align 4
  %_M_imag.i = getelementptr inbounds i8, ptr %b, i64 4
  %3 = load i32, ptr %_M_imag.i, align 4
  %mul3 = mul nsw i32 %3, %2
  %sub = sub nsw i32 %mul, %mul3
  %mul6 = mul nsw i32 %3, %0
  %mul9 = mul nsw i32 %2, %1
  %add = add nsw i32 %mul6, %mul9
  store i32 %add, ptr %_M_imag, align 4
  store i32 %sub, ptr %a, align 4
  ret ptr %a
}
