; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; NOTE: AArch64 inventory: exhaustive sdiv by every signed power-of-2 divisor for
;   i32: +2^k, k=0..30; -2^k, k=0..30; and -2^31 (INT32_MIN).  (63 cases)
;   i64: +2^k, k=0..62; -2^k, k=0..62; and -2^63 (INT64_MIN).  (127 cases)
; RUN: llc -mtriple=aarch64-linux-gnu -fast-isel=0 -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,ISEL
; RUN: llc -mtriple=aarch64-linux-gnu -fast-isel=1 -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,FAST

define i32 @sdiv_i32_u0(i32 %x) {
; ISEL-LABEL: sdiv_i32_u0:
; ISEL:       // %bb.0:
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u0:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #0
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w0, w8, w0, lt
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 1
  ret i32 %r
}

define i32 @sdiv_i32_u1(i32 %x) {
; ISEL-LABEL: sdiv_i32_u1:
; ISEL:       // %bb.0:
; ISEL-NEXT:    add w8, w0, w0, lsr #31
; ISEL-NEXT:    asr w0, w8, #1
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u1:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #1
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #1
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 2
  ret i32 %r
}

define i32 @sdiv_i32_u2(i32 %x) {
; ISEL-LABEL: sdiv_i32_u2:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #30
; ISEL-NEXT:    asr w0, w8, #2
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u2:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #3
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #2
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 4
  ret i32 %r
}

define i32 @sdiv_i32_u3(i32 %x) {
; ISEL-LABEL: sdiv_i32_u3:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #29
; ISEL-NEXT:    asr w0, w8, #3
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u3:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #7
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #3
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 8
  ret i32 %r
}

define i32 @sdiv_i32_u4(i32 %x) {
; ISEL-LABEL: sdiv_i32_u4:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #28
; ISEL-NEXT:    asr w0, w8, #4
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u4:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #15
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #4
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 16
  ret i32 %r
}

define i32 @sdiv_i32_u5(i32 %x) {
; ISEL-LABEL: sdiv_i32_u5:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #27
; ISEL-NEXT:    asr w0, w8, #5
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u5:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #31
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #5
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 32
  ret i32 %r
}

define i32 @sdiv_i32_u6(i32 %x) {
; ISEL-LABEL: sdiv_i32_u6:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #26
; ISEL-NEXT:    asr w0, w8, #6
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u6:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #63
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #6
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 64
  ret i32 %r
}

define i32 @sdiv_i32_u7(i32 %x) {
; ISEL-LABEL: sdiv_i32_u7:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #25
; ISEL-NEXT:    asr w0, w8, #7
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u7:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #127
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #7
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 128
  ret i32 %r
}

define i32 @sdiv_i32_u8(i32 %x) {
; ISEL-LABEL: sdiv_i32_u8:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #24
; ISEL-NEXT:    asr w0, w8, #8
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u8:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #255
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #8
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 256
  ret i32 %r
}

define i32 @sdiv_i32_u9(i32 %x) {
; ISEL-LABEL: sdiv_i32_u9:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #23
; ISEL-NEXT:    asr w0, w8, #9
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u9:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #511
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #9
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 512
  ret i32 %r
}

define i32 @sdiv_i32_u10(i32 %x) {
; ISEL-LABEL: sdiv_i32_u10:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #22
; ISEL-NEXT:    asr w0, w8, #10
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u10:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #1023
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #10
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 1024
  ret i32 %r
}

define i32 @sdiv_i32_u11(i32 %x) {
; ISEL-LABEL: sdiv_i32_u11:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #21
; ISEL-NEXT:    asr w0, w8, #11
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u11:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #2047
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #11
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 2048
  ret i32 %r
}

define i32 @sdiv_i32_u12(i32 %x) {
; ISEL-LABEL: sdiv_i32_u12:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #20
; ISEL-NEXT:    asr w0, w8, #12
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u12:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #4095
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #12
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 4096
  ret i32 %r
}

define i32 @sdiv_i32_u13(i32 %x) {
; ISEL-LABEL: sdiv_i32_u13:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #19
; ISEL-NEXT:    asr w0, w8, #13
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u13:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #8191 // =0x1fff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #13
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 8192
  ret i32 %r
}

define i32 @sdiv_i32_u14(i32 %x) {
; ISEL-LABEL: sdiv_i32_u14:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #18
; ISEL-NEXT:    asr w0, w8, #14
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u14:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #16383 // =0x3fff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #14
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 16384
  ret i32 %r
}

define i32 @sdiv_i32_u15(i32 %x) {
; ISEL-LABEL: sdiv_i32_u15:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #17
; ISEL-NEXT:    asr w0, w8, #15
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u15:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #32767 // =0x7fff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #15
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 32768
  ret i32 %r
}

define i32 @sdiv_i32_u16(i32 %x) {
; ISEL-LABEL: sdiv_i32_u16:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #16
; ISEL-NEXT:    asr w0, w8, #16
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u16:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #65535 // =0xffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #16
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 65536
  ret i32 %r
}

define i32 @sdiv_i32_u17(i32 %x) {
; ISEL-LABEL: sdiv_i32_u17:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #15
; ISEL-NEXT:    asr w0, w8, #17
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u17:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #131071 // =0x1ffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #17
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 131072
  ret i32 %r
}

define i32 @sdiv_i32_u18(i32 %x) {
; ISEL-LABEL: sdiv_i32_u18:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #14
; ISEL-NEXT:    asr w0, w8, #18
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u18:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #262143 // =0x3ffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #18
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 262144
  ret i32 %r
}

define i32 @sdiv_i32_u19(i32 %x) {
; ISEL-LABEL: sdiv_i32_u19:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #13
; ISEL-NEXT:    asr w0, w8, #19
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u19:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #524287 // =0x7ffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #19
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 524288
  ret i32 %r
}

define i32 @sdiv_i32_u20(i32 %x) {
; ISEL-LABEL: sdiv_i32_u20:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #12
; ISEL-NEXT:    asr w0, w8, #20
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u20:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #1048575 // =0xfffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #20
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 1048576
  ret i32 %r
}

define i32 @sdiv_i32_u21(i32 %x) {
; ISEL-LABEL: sdiv_i32_u21:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #11
; ISEL-NEXT:    asr w0, w8, #21
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u21:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #2097151 // =0x1fffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #21
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 2097152
  ret i32 %r
}

define i32 @sdiv_i32_u22(i32 %x) {
; ISEL-LABEL: sdiv_i32_u22:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #10
; ISEL-NEXT:    asr w0, w8, #22
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u22:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #4194303 // =0x3fffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #22
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 4194304
  ret i32 %r
}

define i32 @sdiv_i32_u23(i32 %x) {
; ISEL-LABEL: sdiv_i32_u23:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #9
; ISEL-NEXT:    asr w0, w8, #23
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u23:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #8388607 // =0x7fffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #23
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 8388608
  ret i32 %r
}

define i32 @sdiv_i32_u24(i32 %x) {
; ISEL-LABEL: sdiv_i32_u24:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #8
; ISEL-NEXT:    asr w0, w8, #24
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u24:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #16777215 // =0xffffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #24
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 16777216
  ret i32 %r
}

define i32 @sdiv_i32_u25(i32 %x) {
; ISEL-LABEL: sdiv_i32_u25:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #7
; ISEL-NEXT:    asr w0, w8, #25
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u25:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #33554431 // =0x1ffffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #25
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 33554432
  ret i32 %r
}

define i32 @sdiv_i32_u26(i32 %x) {
; ISEL-LABEL: sdiv_i32_u26:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #6
; ISEL-NEXT:    asr w0, w8, #26
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u26:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #67108863 // =0x3ffffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #26
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 67108864
  ret i32 %r
}

define i32 @sdiv_i32_u27(i32 %x) {
; ISEL-LABEL: sdiv_i32_u27:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #5
; ISEL-NEXT:    asr w0, w8, #27
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u27:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #134217727 // =0x7ffffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #27
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 134217728
  ret i32 %r
}

define i32 @sdiv_i32_u28(i32 %x) {
; ISEL-LABEL: sdiv_i32_u28:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #4
; ISEL-NEXT:    asr w0, w8, #28
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u28:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #268435455 // =0xfffffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #28
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 268435456
  ret i32 %r
}

define i32 @sdiv_i32_u29(i32 %x) {
; ISEL-LABEL: sdiv_i32_u29:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #3
; ISEL-NEXT:    asr w0, w8, #29
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u29:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #536870911 // =0x1fffffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #29
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 536870912
  ret i32 %r
}

define i32 @sdiv_i32_u30(i32 %x) {
; ISEL-LABEL: sdiv_i32_u30:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #2
; ISEL-NEXT:    asr w0, w8, #30
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_u30:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #1073741823 // =0x3fffffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    asr w0, w8, #30
; FAST-NEXT:    ret
  %r = sdiv i32 %x, 1073741824
  ret i32 %r
}

define i32 @sdiv_i32_n0(i32 %x) {
; ISEL-LABEL: sdiv_i32_n0:
; ISEL:       // %bb.0:
; ISEL-NEXT:    neg w0, w0
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n0:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #0
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #0
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -1
  ret i32 %r
}

define i32 @sdiv_i32_n1(i32 %x) {
; ISEL-LABEL: sdiv_i32_n1:
; ISEL:       // %bb.0:
; ISEL-NEXT:    add w8, w0, w0, lsr #31
; ISEL-NEXT:    neg w0, w8, asr #1
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n1:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #1
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #1
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -2
  ret i32 %r
}

define i32 @sdiv_i32_n2(i32 %x) {
; ISEL-LABEL: sdiv_i32_n2:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #30
; ISEL-NEXT:    neg w0, w8, asr #2
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n2:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #3
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #2
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -4
  ret i32 %r
}

define i32 @sdiv_i32_n3(i32 %x) {
; ISEL-LABEL: sdiv_i32_n3:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #29
; ISEL-NEXT:    neg w0, w8, asr #3
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n3:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #7
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #3
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -8
  ret i32 %r
}

define i32 @sdiv_i32_n4(i32 %x) {
; ISEL-LABEL: sdiv_i32_n4:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #28
; ISEL-NEXT:    neg w0, w8, asr #4
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n4:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #15
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #4
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -16
  ret i32 %r
}

define i32 @sdiv_i32_n5(i32 %x) {
; ISEL-LABEL: sdiv_i32_n5:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #27
; ISEL-NEXT:    neg w0, w8, asr #5
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n5:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #31
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #5
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -32
  ret i32 %r
}

define i32 @sdiv_i32_n6(i32 %x) {
; ISEL-LABEL: sdiv_i32_n6:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #26
; ISEL-NEXT:    neg w0, w8, asr #6
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n6:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #63
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #6
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -64
  ret i32 %r
}

define i32 @sdiv_i32_n7(i32 %x) {
; ISEL-LABEL: sdiv_i32_n7:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #25
; ISEL-NEXT:    neg w0, w8, asr #7
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n7:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #127
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #7
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -128
  ret i32 %r
}

define i32 @sdiv_i32_n8(i32 %x) {
; ISEL-LABEL: sdiv_i32_n8:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #24
; ISEL-NEXT:    neg w0, w8, asr #8
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n8:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #255
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #8
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -256
  ret i32 %r
}

define i32 @sdiv_i32_n9(i32 %x) {
; ISEL-LABEL: sdiv_i32_n9:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #23
; ISEL-NEXT:    neg w0, w8, asr #9
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n9:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #511
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #9
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -512
  ret i32 %r
}

define i32 @sdiv_i32_n10(i32 %x) {
; ISEL-LABEL: sdiv_i32_n10:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #22
; ISEL-NEXT:    neg w0, w8, asr #10
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n10:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #1023
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #10
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -1024
  ret i32 %r
}

define i32 @sdiv_i32_n11(i32 %x) {
; ISEL-LABEL: sdiv_i32_n11:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #21
; ISEL-NEXT:    neg w0, w8, asr #11
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n11:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #2047
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #11
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -2048
  ret i32 %r
}

define i32 @sdiv_i32_n12(i32 %x) {
; ISEL-LABEL: sdiv_i32_n12:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #20
; ISEL-NEXT:    neg w0, w8, asr #12
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n12:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #4095
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #12
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -4096
  ret i32 %r
}

define i32 @sdiv_i32_n13(i32 %x) {
; ISEL-LABEL: sdiv_i32_n13:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #19
; ISEL-NEXT:    neg w0, w8, asr #13
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n13:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #8191 // =0x1fff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #13
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -8192
  ret i32 %r
}

define i32 @sdiv_i32_n14(i32 %x) {
; ISEL-LABEL: sdiv_i32_n14:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #18
; ISEL-NEXT:    neg w0, w8, asr #14
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n14:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #16383 // =0x3fff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #14
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -16384
  ret i32 %r
}

define i32 @sdiv_i32_n15(i32 %x) {
; ISEL-LABEL: sdiv_i32_n15:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #17
; ISEL-NEXT:    neg w0, w8, asr #15
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n15:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #32767 // =0x7fff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #15
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -32768
  ret i32 %r
}

define i32 @sdiv_i32_n16(i32 %x) {
; ISEL-LABEL: sdiv_i32_n16:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #16
; ISEL-NEXT:    neg w0, w8, asr #16
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n16:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #65535 // =0xffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #16
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -65536
  ret i32 %r
}

define i32 @sdiv_i32_n17(i32 %x) {
; ISEL-LABEL: sdiv_i32_n17:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #15
; ISEL-NEXT:    neg w0, w8, asr #17
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n17:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #131071 // =0x1ffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #17
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -131072
  ret i32 %r
}

define i32 @sdiv_i32_n18(i32 %x) {
; ISEL-LABEL: sdiv_i32_n18:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #14
; ISEL-NEXT:    neg w0, w8, asr #18
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n18:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #262143 // =0x3ffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #18
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -262144
  ret i32 %r
}

define i32 @sdiv_i32_n19(i32 %x) {
; ISEL-LABEL: sdiv_i32_n19:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #13
; ISEL-NEXT:    neg w0, w8, asr #19
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n19:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #524287 // =0x7ffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #19
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -524288
  ret i32 %r
}

define i32 @sdiv_i32_n20(i32 %x) {
; ISEL-LABEL: sdiv_i32_n20:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #12
; ISEL-NEXT:    neg w0, w8, asr #20
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n20:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #1048575 // =0xfffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #20
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -1048576
  ret i32 %r
}

define i32 @sdiv_i32_n21(i32 %x) {
; ISEL-LABEL: sdiv_i32_n21:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #11
; ISEL-NEXT:    neg w0, w8, asr #21
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n21:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #2097151 // =0x1fffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #21
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -2097152
  ret i32 %r
}

define i32 @sdiv_i32_n22(i32 %x) {
; ISEL-LABEL: sdiv_i32_n22:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #10
; ISEL-NEXT:    neg w0, w8, asr #22
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n22:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #4194303 // =0x3fffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #22
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -4194304
  ret i32 %r
}

define i32 @sdiv_i32_n23(i32 %x) {
; ISEL-LABEL: sdiv_i32_n23:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #9
; ISEL-NEXT:    neg w0, w8, asr #23
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n23:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #8388607 // =0x7fffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #23
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -8388608
  ret i32 %r
}

define i32 @sdiv_i32_n24(i32 %x) {
; ISEL-LABEL: sdiv_i32_n24:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #8
; ISEL-NEXT:    neg w0, w8, asr #24
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n24:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #16777215 // =0xffffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #24
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -16777216
  ret i32 %r
}

define i32 @sdiv_i32_n25(i32 %x) {
; ISEL-LABEL: sdiv_i32_n25:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #7
; ISEL-NEXT:    neg w0, w8, asr #25
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n25:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #33554431 // =0x1ffffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #25
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -33554432
  ret i32 %r
}

define i32 @sdiv_i32_n26(i32 %x) {
; ISEL-LABEL: sdiv_i32_n26:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #6
; ISEL-NEXT:    neg w0, w8, asr #26
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n26:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #67108863 // =0x3ffffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #26
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -67108864
  ret i32 %r
}

define i32 @sdiv_i32_n27(i32 %x) {
; ISEL-LABEL: sdiv_i32_n27:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #5
; ISEL-NEXT:    neg w0, w8, asr #27
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n27:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #134217727 // =0x7ffffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #27
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -134217728
  ret i32 %r
}

define i32 @sdiv_i32_n28(i32 %x) {
; ISEL-LABEL: sdiv_i32_n28:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #4
; ISEL-NEXT:    neg w0, w8, asr #28
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n28:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #268435455 // =0xfffffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #28
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -268435456
  ret i32 %r
}

define i32 @sdiv_i32_n29(i32 %x) {
; ISEL-LABEL: sdiv_i32_n29:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #3
; ISEL-NEXT:    neg w0, w8, asr #29
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n29:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #536870911 // =0x1fffffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #29
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -536870912
  ret i32 %r
}

define i32 @sdiv_i32_n30(i32 %x) {
; ISEL-LABEL: sdiv_i32_n30:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr w8, w0, #31
; ISEL-NEXT:    add w8, w0, w8, lsr #2
; ISEL-NEXT:    neg w0, w8, asr #30
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n30:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #1073741823 // =0x3fffffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #30
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -1073741824
  ret i32 %r
}

define i32 @sdiv_i32_n31_intmin(i32 %x) {
; ISEL-LABEL: sdiv_i32_n31_intmin:
; ISEL:       // %bb.0:
; ISEL-NEXT:    mov w8, #-2147483648 // =0x80000000
; ISEL-NEXT:    cmp w0, w8
; ISEL-NEXT:    cset w0, eq
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i32_n31_intmin:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #2147483647 // =0x7fffffff
; FAST-NEXT:    cmp w0, #0
; FAST-NEXT:    add w8, w0, w8
; FAST-NEXT:    csel w8, w8, w0, lt
; FAST-NEXT:    neg w0, w8, asr #31
; FAST-NEXT:    ret
  %r = sdiv i32 %x, -2147483648
  ret i32 %r
}

define i64 @sdiv_i64_u0(i64 %x) {
; ISEL-LABEL: sdiv_i64_u0:
; ISEL:       // %bb.0:
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u0:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #0
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x0, x8, x0, lt
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 1
  ret i64 %r
}

define i64 @sdiv_i64_u1(i64 %x) {
; ISEL-LABEL: sdiv_i64_u1:
; ISEL:       // %bb.0:
; ISEL-NEXT:    add x8, x0, x0, lsr #63
; ISEL-NEXT:    asr x0, x8, #1
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u1:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #1
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #1
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 2
  ret i64 %r
}

define i64 @sdiv_i64_u2(i64 %x) {
; ISEL-LABEL: sdiv_i64_u2:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #62
; ISEL-NEXT:    asr x0, x8, #2
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u2:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #3
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #2
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 4
  ret i64 %r
}

define i64 @sdiv_i64_u3(i64 %x) {
; ISEL-LABEL: sdiv_i64_u3:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #61
; ISEL-NEXT:    asr x0, x8, #3
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u3:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #7
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #3
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 8
  ret i64 %r
}

define i64 @sdiv_i64_u4(i64 %x) {
; ISEL-LABEL: sdiv_i64_u4:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #60
; ISEL-NEXT:    asr x0, x8, #4
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u4:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #15
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #4
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 16
  ret i64 %r
}

define i64 @sdiv_i64_u5(i64 %x) {
; ISEL-LABEL: sdiv_i64_u5:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #59
; ISEL-NEXT:    asr x0, x8, #5
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u5:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #31
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #5
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 32
  ret i64 %r
}

define i64 @sdiv_i64_u6(i64 %x) {
; ISEL-LABEL: sdiv_i64_u6:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #58
; ISEL-NEXT:    asr x0, x8, #6
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u6:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #63
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #6
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 64
  ret i64 %r
}

define i64 @sdiv_i64_u7(i64 %x) {
; ISEL-LABEL: sdiv_i64_u7:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #57
; ISEL-NEXT:    asr x0, x8, #7
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u7:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #127
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #7
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 128
  ret i64 %r
}

define i64 @sdiv_i64_u8(i64 %x) {
; ISEL-LABEL: sdiv_i64_u8:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #56
; ISEL-NEXT:    asr x0, x8, #8
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u8:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #255
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #8
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 256
  ret i64 %r
}

define i64 @sdiv_i64_u9(i64 %x) {
; ISEL-LABEL: sdiv_i64_u9:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #55
; ISEL-NEXT:    asr x0, x8, #9
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u9:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #511
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #9
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 512
  ret i64 %r
}

define i64 @sdiv_i64_u10(i64 %x) {
; ISEL-LABEL: sdiv_i64_u10:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #54
; ISEL-NEXT:    asr x0, x8, #10
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u10:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #1023
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #10
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 1024
  ret i64 %r
}

define i64 @sdiv_i64_u11(i64 %x) {
; ISEL-LABEL: sdiv_i64_u11:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #53
; ISEL-NEXT:    asr x0, x8, #11
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u11:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #2047
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #11
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 2048
  ret i64 %r
}

define i64 @sdiv_i64_u12(i64 %x) {
; ISEL-LABEL: sdiv_i64_u12:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #52
; ISEL-NEXT:    asr x0, x8, #12
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u12:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #4095
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #12
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 4096
  ret i64 %r
}

define i64 @sdiv_i64_u13(i64 %x) {
; ISEL-LABEL: sdiv_i64_u13:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #51
; ISEL-NEXT:    asr x0, x8, #13
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u13:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #8191 // =0x1fff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #13
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 8192
  ret i64 %r
}

define i64 @sdiv_i64_u14(i64 %x) {
; ISEL-LABEL: sdiv_i64_u14:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #50
; ISEL-NEXT:    asr x0, x8, #14
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u14:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #16383 // =0x3fff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #14
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 16384
  ret i64 %r
}

define i64 @sdiv_i64_u15(i64 %x) {
; ISEL-LABEL: sdiv_i64_u15:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #49
; ISEL-NEXT:    asr x0, x8, #15
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u15:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #32767 // =0x7fff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #15
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 32768
  ret i64 %r
}

define i64 @sdiv_i64_u16(i64 %x) {
; ISEL-LABEL: sdiv_i64_u16:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #48
; ISEL-NEXT:    asr x0, x8, #16
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u16:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #65535 // =0xffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #16
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 65536
  ret i64 %r
}

define i64 @sdiv_i64_u17(i64 %x) {
; ISEL-LABEL: sdiv_i64_u17:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #47
; ISEL-NEXT:    asr x0, x8, #17
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u17:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #131071 // =0x1ffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #17
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 131072
  ret i64 %r
}

define i64 @sdiv_i64_u18(i64 %x) {
; ISEL-LABEL: sdiv_i64_u18:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #46
; ISEL-NEXT:    asr x0, x8, #18
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u18:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #262143 // =0x3ffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #18
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 262144
  ret i64 %r
}

define i64 @sdiv_i64_u19(i64 %x) {
; ISEL-LABEL: sdiv_i64_u19:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #45
; ISEL-NEXT:    asr x0, x8, #19
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u19:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #524287 // =0x7ffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #19
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 524288
  ret i64 %r
}

define i64 @sdiv_i64_u20(i64 %x) {
; ISEL-LABEL: sdiv_i64_u20:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #44
; ISEL-NEXT:    asr x0, x8, #20
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u20:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #1048575 // =0xfffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #20
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 1048576
  ret i64 %r
}

define i64 @sdiv_i64_u21(i64 %x) {
; ISEL-LABEL: sdiv_i64_u21:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #43
; ISEL-NEXT:    asr x0, x8, #21
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u21:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #2097151 // =0x1fffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #21
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 2097152
  ret i64 %r
}

define i64 @sdiv_i64_u22(i64 %x) {
; ISEL-LABEL: sdiv_i64_u22:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #42
; ISEL-NEXT:    asr x0, x8, #22
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u22:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #4194303 // =0x3fffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #22
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 4194304
  ret i64 %r
}

define i64 @sdiv_i64_u23(i64 %x) {
; ISEL-LABEL: sdiv_i64_u23:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #41
; ISEL-NEXT:    asr x0, x8, #23
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u23:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #8388607 // =0x7fffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #23
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 8388608
  ret i64 %r
}

define i64 @sdiv_i64_u24(i64 %x) {
; ISEL-LABEL: sdiv_i64_u24:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #40
; ISEL-NEXT:    asr x0, x8, #24
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u24:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #16777215 // =0xffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #24
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 16777216
  ret i64 %r
}

define i64 @sdiv_i64_u25(i64 %x) {
; ISEL-LABEL: sdiv_i64_u25:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #39
; ISEL-NEXT:    asr x0, x8, #25
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u25:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #33554431 // =0x1ffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #25
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 33554432
  ret i64 %r
}

define i64 @sdiv_i64_u26(i64 %x) {
; ISEL-LABEL: sdiv_i64_u26:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #38
; ISEL-NEXT:    asr x0, x8, #26
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u26:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #67108863 // =0x3ffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #26
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 67108864
  ret i64 %r
}

define i64 @sdiv_i64_u27(i64 %x) {
; ISEL-LABEL: sdiv_i64_u27:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #37
; ISEL-NEXT:    asr x0, x8, #27
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u27:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #134217727 // =0x7ffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #27
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 134217728
  ret i64 %r
}

define i64 @sdiv_i64_u28(i64 %x) {
; ISEL-LABEL: sdiv_i64_u28:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #36
; ISEL-NEXT:    asr x0, x8, #28
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u28:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #268435455 // =0xfffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #28
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 268435456
  ret i64 %r
}

define i64 @sdiv_i64_u29(i64 %x) {
; ISEL-LABEL: sdiv_i64_u29:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #35
; ISEL-NEXT:    asr x0, x8, #29
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u29:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #536870911 // =0x1fffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #29
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 536870912
  ret i64 %r
}

define i64 @sdiv_i64_u30(i64 %x) {
; ISEL-LABEL: sdiv_i64_u30:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #34
; ISEL-NEXT:    asr x0, x8, #30
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u30:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #1073741823 // =0x3fffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #30
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 1073741824
  ret i64 %r
}

define i64 @sdiv_i64_u31(i64 %x) {
; ISEL-LABEL: sdiv_i64_u31:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #33
; ISEL-NEXT:    asr x0, x8, #31
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u31:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #2147483647 // =0x7fffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #31
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 2147483648
  ret i64 %r
}

define i64 @sdiv_i64_u32(i64 %x) {
; ISEL-LABEL: sdiv_i64_u32:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #32
; ISEL-NEXT:    asr x0, x8, #32
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u32:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #4294967295 // =0xffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #32
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 4294967296
  ret i64 %r
}

define i64 @sdiv_i64_u33(i64 %x) {
; ISEL-LABEL: sdiv_i64_u33:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #31
; ISEL-NEXT:    asr x0, x8, #33
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u33:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #8589934591 // =0x1ffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #33
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 8589934592
  ret i64 %r
}

define i64 @sdiv_i64_u34(i64 %x) {
; ISEL-LABEL: sdiv_i64_u34:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #30
; ISEL-NEXT:    asr x0, x8, #34
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u34:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #17179869183 // =0x3ffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #34
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 17179869184
  ret i64 %r
}

define i64 @sdiv_i64_u35(i64 %x) {
; ISEL-LABEL: sdiv_i64_u35:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #29
; ISEL-NEXT:    asr x0, x8, #35
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u35:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #34359738367 // =0x7ffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #35
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 34359738368
  ret i64 %r
}

define i64 @sdiv_i64_u36(i64 %x) {
; ISEL-LABEL: sdiv_i64_u36:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #28
; ISEL-NEXT:    asr x0, x8, #36
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u36:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #68719476735 // =0xfffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #36
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 68719476736
  ret i64 %r
}

define i64 @sdiv_i64_u37(i64 %x) {
; ISEL-LABEL: sdiv_i64_u37:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #27
; ISEL-NEXT:    asr x0, x8, #37
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u37:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #137438953471 // =0x1fffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #37
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 137438953472
  ret i64 %r
}

define i64 @sdiv_i64_u38(i64 %x) {
; ISEL-LABEL: sdiv_i64_u38:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #26
; ISEL-NEXT:    asr x0, x8, #38
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u38:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #274877906943 // =0x3fffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #38
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 274877906944
  ret i64 %r
}

define i64 @sdiv_i64_u39(i64 %x) {
; ISEL-LABEL: sdiv_i64_u39:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #25
; ISEL-NEXT:    asr x0, x8, #39
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u39:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #549755813887 // =0x7fffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #39
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 549755813888
  ret i64 %r
}

define i64 @sdiv_i64_u40(i64 %x) {
; ISEL-LABEL: sdiv_i64_u40:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #24
; ISEL-NEXT:    asr x0, x8, #40
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u40:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #1099511627775 // =0xffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #40
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 1099511627776
  ret i64 %r
}

define i64 @sdiv_i64_u41(i64 %x) {
; ISEL-LABEL: sdiv_i64_u41:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #23
; ISEL-NEXT:    asr x0, x8, #41
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u41:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #2199023255551 // =0x1ffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #41
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 2199023255552
  ret i64 %r
}

define i64 @sdiv_i64_u42(i64 %x) {
; ISEL-LABEL: sdiv_i64_u42:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #22
; ISEL-NEXT:    asr x0, x8, #42
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u42:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #4398046511103 // =0x3ffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #42
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 4398046511104
  ret i64 %r
}

define i64 @sdiv_i64_u43(i64 %x) {
; ISEL-LABEL: sdiv_i64_u43:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #21
; ISEL-NEXT:    asr x0, x8, #43
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u43:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #8796093022207 // =0x7ffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #43
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 8796093022208
  ret i64 %r
}

define i64 @sdiv_i64_u44(i64 %x) {
; ISEL-LABEL: sdiv_i64_u44:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #20
; ISEL-NEXT:    asr x0, x8, #44
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u44:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #17592186044415 // =0xfffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #44
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 17592186044416
  ret i64 %r
}

define i64 @sdiv_i64_u45(i64 %x) {
; ISEL-LABEL: sdiv_i64_u45:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #19
; ISEL-NEXT:    asr x0, x8, #45
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u45:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #35184372088831 // =0x1fffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #45
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 35184372088832
  ret i64 %r
}

define i64 @sdiv_i64_u46(i64 %x) {
; ISEL-LABEL: sdiv_i64_u46:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #18
; ISEL-NEXT:    asr x0, x8, #46
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u46:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #70368744177663 // =0x3fffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #46
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 70368744177664
  ret i64 %r
}

define i64 @sdiv_i64_u47(i64 %x) {
; ISEL-LABEL: sdiv_i64_u47:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #17
; ISEL-NEXT:    asr x0, x8, #47
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u47:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #140737488355327 // =0x7fffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #47
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 140737488355328
  ret i64 %r
}

define i64 @sdiv_i64_u48(i64 %x) {
; ISEL-LABEL: sdiv_i64_u48:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #16
; ISEL-NEXT:    asr x0, x8, #48
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u48:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #281474976710655 // =0xffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #48
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 281474976710656
  ret i64 %r
}

define i64 @sdiv_i64_u49(i64 %x) {
; ISEL-LABEL: sdiv_i64_u49:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #15
; ISEL-NEXT:    asr x0, x8, #49
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u49:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #562949953421311 // =0x1ffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #49
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 562949953421312
  ret i64 %r
}

define i64 @sdiv_i64_u50(i64 %x) {
; ISEL-LABEL: sdiv_i64_u50:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #14
; ISEL-NEXT:    asr x0, x8, #50
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u50:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #1125899906842623 // =0x3ffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #50
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 1125899906842624
  ret i64 %r
}

define i64 @sdiv_i64_u51(i64 %x) {
; ISEL-LABEL: sdiv_i64_u51:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #13
; ISEL-NEXT:    asr x0, x8, #51
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u51:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #2251799813685247 // =0x7ffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #51
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 2251799813685248
  ret i64 %r
}

define i64 @sdiv_i64_u52(i64 %x) {
; ISEL-LABEL: sdiv_i64_u52:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #12
; ISEL-NEXT:    asr x0, x8, #52
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u52:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #4503599627370495 // =0xfffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #52
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 4503599627370496
  ret i64 %r
}

define i64 @sdiv_i64_u53(i64 %x) {
; ISEL-LABEL: sdiv_i64_u53:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #11
; ISEL-NEXT:    asr x0, x8, #53
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u53:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #9007199254740991 // =0x1fffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #53
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 9007199254740992
  ret i64 %r
}

define i64 @sdiv_i64_u54(i64 %x) {
; ISEL-LABEL: sdiv_i64_u54:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #10
; ISEL-NEXT:    asr x0, x8, #54
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u54:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #18014398509481983 // =0x3fffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #54
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 18014398509481984
  ret i64 %r
}

define i64 @sdiv_i64_u55(i64 %x) {
; ISEL-LABEL: sdiv_i64_u55:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #9
; ISEL-NEXT:    asr x0, x8, #55
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u55:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #36028797018963967 // =0x7fffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #55
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 36028797018963968
  ret i64 %r
}

define i64 @sdiv_i64_u56(i64 %x) {
; ISEL-LABEL: sdiv_i64_u56:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #8
; ISEL-NEXT:    asr x0, x8, #56
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u56:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #72057594037927935 // =0xffffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #56
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 72057594037927936
  ret i64 %r
}

define i64 @sdiv_i64_u57(i64 %x) {
; ISEL-LABEL: sdiv_i64_u57:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #7
; ISEL-NEXT:    asr x0, x8, #57
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u57:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #144115188075855871 // =0x1ffffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #57
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 144115188075855872
  ret i64 %r
}

define i64 @sdiv_i64_u58(i64 %x) {
; ISEL-LABEL: sdiv_i64_u58:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #6
; ISEL-NEXT:    asr x0, x8, #58
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u58:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #288230376151711743 // =0x3ffffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #58
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 288230376151711744
  ret i64 %r
}

define i64 @sdiv_i64_u59(i64 %x) {
; ISEL-LABEL: sdiv_i64_u59:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #5
; ISEL-NEXT:    asr x0, x8, #59
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u59:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #576460752303423487 // =0x7ffffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #59
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 576460752303423488
  ret i64 %r
}

define i64 @sdiv_i64_u60(i64 %x) {
; ISEL-LABEL: sdiv_i64_u60:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #4
; ISEL-NEXT:    asr x0, x8, #60
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u60:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #1152921504606846975 // =0xfffffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #60
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 1152921504606846976
  ret i64 %r
}

define i64 @sdiv_i64_u61(i64 %x) {
; ISEL-LABEL: sdiv_i64_u61:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #3
; ISEL-NEXT:    asr x0, x8, #61
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u61:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #2305843009213693951 // =0x1fffffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #61
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 2305843009213693952
  ret i64 %r
}

define i64 @sdiv_i64_u62(i64 %x) {
; ISEL-LABEL: sdiv_i64_u62:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #2
; ISEL-NEXT:    asr x0, x8, #62
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_u62:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #4611686018427387903 // =0x3fffffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #62
; FAST-NEXT:    ret
  %r = sdiv i64 %x, 4611686018427387904
  ret i64 %r
}

define i64 @sdiv_i64_n0(i64 %x) {
; ISEL-LABEL: sdiv_i64_n0:
; ISEL:       // %bb.0:
; ISEL-NEXT:    neg x0, x0
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n0:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #0
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #0
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -1
  ret i64 %r
}

define i64 @sdiv_i64_n1(i64 %x) {
; ISEL-LABEL: sdiv_i64_n1:
; ISEL:       // %bb.0:
; ISEL-NEXT:    add x8, x0, x0, lsr #63
; ISEL-NEXT:    neg x0, x8, asr #1
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n1:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #1
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #1
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -2
  ret i64 %r
}

define i64 @sdiv_i64_n2(i64 %x) {
; ISEL-LABEL: sdiv_i64_n2:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #62
; ISEL-NEXT:    neg x0, x8, asr #2
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n2:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #3
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #2
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -4
  ret i64 %r
}

define i64 @sdiv_i64_n3(i64 %x) {
; ISEL-LABEL: sdiv_i64_n3:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #61
; ISEL-NEXT:    neg x0, x8, asr #3
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n3:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #7
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #3
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -8
  ret i64 %r
}

define i64 @sdiv_i64_n4(i64 %x) {
; ISEL-LABEL: sdiv_i64_n4:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #60
; ISEL-NEXT:    neg x0, x8, asr #4
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n4:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #15
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #4
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -16
  ret i64 %r
}

define i64 @sdiv_i64_n5(i64 %x) {
; ISEL-LABEL: sdiv_i64_n5:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #59
; ISEL-NEXT:    neg x0, x8, asr #5
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n5:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #31
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #5
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -32
  ret i64 %r
}

define i64 @sdiv_i64_n6(i64 %x) {
; ISEL-LABEL: sdiv_i64_n6:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #58
; ISEL-NEXT:    neg x0, x8, asr #6
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n6:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #63
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #6
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -64
  ret i64 %r
}

define i64 @sdiv_i64_n7(i64 %x) {
; ISEL-LABEL: sdiv_i64_n7:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #57
; ISEL-NEXT:    neg x0, x8, asr #7
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n7:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #127
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #7
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -128
  ret i64 %r
}

define i64 @sdiv_i64_n8(i64 %x) {
; ISEL-LABEL: sdiv_i64_n8:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #56
; ISEL-NEXT:    neg x0, x8, asr #8
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n8:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #255
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #8
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -256
  ret i64 %r
}

define i64 @sdiv_i64_n9(i64 %x) {
; ISEL-LABEL: sdiv_i64_n9:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #55
; ISEL-NEXT:    neg x0, x8, asr #9
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n9:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #511
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #9
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -512
  ret i64 %r
}

define i64 @sdiv_i64_n10(i64 %x) {
; ISEL-LABEL: sdiv_i64_n10:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #54
; ISEL-NEXT:    neg x0, x8, asr #10
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n10:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #1023
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #10
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -1024
  ret i64 %r
}

define i64 @sdiv_i64_n11(i64 %x) {
; ISEL-LABEL: sdiv_i64_n11:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #53
; ISEL-NEXT:    neg x0, x8, asr #11
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n11:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #2047
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #11
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -2048
  ret i64 %r
}

define i64 @sdiv_i64_n12(i64 %x) {
; ISEL-LABEL: sdiv_i64_n12:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #52
; ISEL-NEXT:    neg x0, x8, asr #12
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n12:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #4095
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #12
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -4096
  ret i64 %r
}

define i64 @sdiv_i64_n13(i64 %x) {
; ISEL-LABEL: sdiv_i64_n13:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #51
; ISEL-NEXT:    neg x0, x8, asr #13
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n13:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #8191 // =0x1fff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #13
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -8192
  ret i64 %r
}

define i64 @sdiv_i64_n14(i64 %x) {
; ISEL-LABEL: sdiv_i64_n14:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #50
; ISEL-NEXT:    neg x0, x8, asr #14
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n14:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #16383 // =0x3fff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #14
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -16384
  ret i64 %r
}

define i64 @sdiv_i64_n15(i64 %x) {
; ISEL-LABEL: sdiv_i64_n15:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #49
; ISEL-NEXT:    neg x0, x8, asr #15
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n15:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #32767 // =0x7fff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #15
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -32768
  ret i64 %r
}

define i64 @sdiv_i64_n16(i64 %x) {
; ISEL-LABEL: sdiv_i64_n16:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #48
; ISEL-NEXT:    neg x0, x8, asr #16
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n16:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #65535 // =0xffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #16
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -65536
  ret i64 %r
}

define i64 @sdiv_i64_n17(i64 %x) {
; ISEL-LABEL: sdiv_i64_n17:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #47
; ISEL-NEXT:    neg x0, x8, asr #17
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n17:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #131071 // =0x1ffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #17
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -131072
  ret i64 %r
}

define i64 @sdiv_i64_n18(i64 %x) {
; ISEL-LABEL: sdiv_i64_n18:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #46
; ISEL-NEXT:    neg x0, x8, asr #18
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n18:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #262143 // =0x3ffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #18
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -262144
  ret i64 %r
}

define i64 @sdiv_i64_n19(i64 %x) {
; ISEL-LABEL: sdiv_i64_n19:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #45
; ISEL-NEXT:    neg x0, x8, asr #19
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n19:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #524287 // =0x7ffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #19
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -524288
  ret i64 %r
}

define i64 @sdiv_i64_n20(i64 %x) {
; ISEL-LABEL: sdiv_i64_n20:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #44
; ISEL-NEXT:    neg x0, x8, asr #20
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n20:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #1048575 // =0xfffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #20
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -1048576
  ret i64 %r
}

define i64 @sdiv_i64_n21(i64 %x) {
; ISEL-LABEL: sdiv_i64_n21:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #43
; ISEL-NEXT:    neg x0, x8, asr #21
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n21:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #2097151 // =0x1fffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #21
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -2097152
  ret i64 %r
}

define i64 @sdiv_i64_n22(i64 %x) {
; ISEL-LABEL: sdiv_i64_n22:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #42
; ISEL-NEXT:    neg x0, x8, asr #22
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n22:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #4194303 // =0x3fffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #22
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -4194304
  ret i64 %r
}

define i64 @sdiv_i64_n23(i64 %x) {
; ISEL-LABEL: sdiv_i64_n23:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #41
; ISEL-NEXT:    neg x0, x8, asr #23
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n23:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #8388607 // =0x7fffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #23
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -8388608
  ret i64 %r
}

define i64 @sdiv_i64_n24(i64 %x) {
; ISEL-LABEL: sdiv_i64_n24:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #40
; ISEL-NEXT:    neg x0, x8, asr #24
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n24:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #16777215 // =0xffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #24
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -16777216
  ret i64 %r
}

define i64 @sdiv_i64_n25(i64 %x) {
; ISEL-LABEL: sdiv_i64_n25:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #39
; ISEL-NEXT:    neg x0, x8, asr #25
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n25:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #33554431 // =0x1ffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #25
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -33554432
  ret i64 %r
}

define i64 @sdiv_i64_n26(i64 %x) {
; ISEL-LABEL: sdiv_i64_n26:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #38
; ISEL-NEXT:    neg x0, x8, asr #26
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n26:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #67108863 // =0x3ffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #26
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -67108864
  ret i64 %r
}

define i64 @sdiv_i64_n27(i64 %x) {
; ISEL-LABEL: sdiv_i64_n27:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #37
; ISEL-NEXT:    neg x0, x8, asr #27
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n27:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #134217727 // =0x7ffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #27
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -134217728
  ret i64 %r
}

define i64 @sdiv_i64_n28(i64 %x) {
; ISEL-LABEL: sdiv_i64_n28:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #36
; ISEL-NEXT:    neg x0, x8, asr #28
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n28:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #268435455 // =0xfffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #28
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -268435456
  ret i64 %r
}

define i64 @sdiv_i64_n29(i64 %x) {
; ISEL-LABEL: sdiv_i64_n29:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #35
; ISEL-NEXT:    neg x0, x8, asr #29
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n29:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #536870911 // =0x1fffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #29
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -536870912
  ret i64 %r
}

define i64 @sdiv_i64_n30(i64 %x) {
; ISEL-LABEL: sdiv_i64_n30:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #34
; ISEL-NEXT:    neg x0, x8, asr #30
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n30:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #1073741823 // =0x3fffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #30
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -1073741824
  ret i64 %r
}

define i64 @sdiv_i64_n31(i64 %x) {
; ISEL-LABEL: sdiv_i64_n31:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #33
; ISEL-NEXT:    neg x0, x8, asr #31
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n31:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #2147483647 // =0x7fffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #31
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -2147483648
  ret i64 %r
}

define i64 @sdiv_i64_n32(i64 %x) {
; ISEL-LABEL: sdiv_i64_n32:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #32
; ISEL-NEXT:    neg x0, x8, asr #32
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n32:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #4294967295 // =0xffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #32
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -4294967296
  ret i64 %r
}

define i64 @sdiv_i64_n33(i64 %x) {
; ISEL-LABEL: sdiv_i64_n33:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #31
; ISEL-NEXT:    neg x0, x8, asr #33
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n33:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #8589934591 // =0x1ffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #33
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -8589934592
  ret i64 %r
}

define i64 @sdiv_i64_n34(i64 %x) {
; ISEL-LABEL: sdiv_i64_n34:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #30
; ISEL-NEXT:    neg x0, x8, asr #34
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n34:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #17179869183 // =0x3ffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #34
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -17179869184
  ret i64 %r
}

define i64 @sdiv_i64_n35(i64 %x) {
; ISEL-LABEL: sdiv_i64_n35:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #29
; ISEL-NEXT:    neg x0, x8, asr #35
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n35:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #34359738367 // =0x7ffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #35
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -34359738368
  ret i64 %r
}

define i64 @sdiv_i64_n36(i64 %x) {
; ISEL-LABEL: sdiv_i64_n36:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #28
; ISEL-NEXT:    neg x0, x8, asr #36
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n36:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #68719476735 // =0xfffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #36
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -68719476736
  ret i64 %r
}

define i64 @sdiv_i64_n37(i64 %x) {
; ISEL-LABEL: sdiv_i64_n37:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #27
; ISEL-NEXT:    neg x0, x8, asr #37
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n37:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #137438953471 // =0x1fffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #37
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -137438953472
  ret i64 %r
}

define i64 @sdiv_i64_n38(i64 %x) {
; ISEL-LABEL: sdiv_i64_n38:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #26
; ISEL-NEXT:    neg x0, x8, asr #38
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n38:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #274877906943 // =0x3fffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #38
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -274877906944
  ret i64 %r
}

define i64 @sdiv_i64_n39(i64 %x) {
; ISEL-LABEL: sdiv_i64_n39:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #25
; ISEL-NEXT:    neg x0, x8, asr #39
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n39:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #549755813887 // =0x7fffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #39
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -549755813888
  ret i64 %r
}

define i64 @sdiv_i64_n40(i64 %x) {
; ISEL-LABEL: sdiv_i64_n40:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #24
; ISEL-NEXT:    neg x0, x8, asr #40
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n40:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #1099511627775 // =0xffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #40
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -1099511627776
  ret i64 %r
}

define i64 @sdiv_i64_n41(i64 %x) {
; ISEL-LABEL: sdiv_i64_n41:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #23
; ISEL-NEXT:    neg x0, x8, asr #41
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n41:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #2199023255551 // =0x1ffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #41
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -2199023255552
  ret i64 %r
}

define i64 @sdiv_i64_n42(i64 %x) {
; ISEL-LABEL: sdiv_i64_n42:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #22
; ISEL-NEXT:    neg x0, x8, asr #42
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n42:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #4398046511103 // =0x3ffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #42
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -4398046511104
  ret i64 %r
}

define i64 @sdiv_i64_n43(i64 %x) {
; ISEL-LABEL: sdiv_i64_n43:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #21
; ISEL-NEXT:    neg x0, x8, asr #43
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n43:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #8796093022207 // =0x7ffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #43
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -8796093022208
  ret i64 %r
}

define i64 @sdiv_i64_n44(i64 %x) {
; ISEL-LABEL: sdiv_i64_n44:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #20
; ISEL-NEXT:    neg x0, x8, asr #44
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n44:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #17592186044415 // =0xfffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #44
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -17592186044416
  ret i64 %r
}

define i64 @sdiv_i64_n45(i64 %x) {
; ISEL-LABEL: sdiv_i64_n45:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #19
; ISEL-NEXT:    neg x0, x8, asr #45
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n45:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #35184372088831 // =0x1fffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #45
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -35184372088832
  ret i64 %r
}

define i64 @sdiv_i64_n46(i64 %x) {
; ISEL-LABEL: sdiv_i64_n46:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #18
; ISEL-NEXT:    neg x0, x8, asr #46
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n46:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #70368744177663 // =0x3fffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #46
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -70368744177664
  ret i64 %r
}

define i64 @sdiv_i64_n47(i64 %x) {
; ISEL-LABEL: sdiv_i64_n47:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #17
; ISEL-NEXT:    neg x0, x8, asr #47
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n47:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #140737488355327 // =0x7fffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #47
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -140737488355328
  ret i64 %r
}

define i64 @sdiv_i64_n48(i64 %x) {
; ISEL-LABEL: sdiv_i64_n48:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #16
; ISEL-NEXT:    neg x0, x8, asr #48
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n48:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #281474976710655 // =0xffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #48
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -281474976710656
  ret i64 %r
}

define i64 @sdiv_i64_n49(i64 %x) {
; ISEL-LABEL: sdiv_i64_n49:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #15
; ISEL-NEXT:    neg x0, x8, asr #49
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n49:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #562949953421311 // =0x1ffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #49
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -562949953421312
  ret i64 %r
}

define i64 @sdiv_i64_n50(i64 %x) {
; ISEL-LABEL: sdiv_i64_n50:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #14
; ISEL-NEXT:    neg x0, x8, asr #50
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n50:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #1125899906842623 // =0x3ffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #50
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -1125899906842624
  ret i64 %r
}

define i64 @sdiv_i64_n51(i64 %x) {
; ISEL-LABEL: sdiv_i64_n51:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #13
; ISEL-NEXT:    neg x0, x8, asr #51
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n51:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #2251799813685247 // =0x7ffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #51
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -2251799813685248
  ret i64 %r
}

define i64 @sdiv_i64_n52(i64 %x) {
; ISEL-LABEL: sdiv_i64_n52:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #12
; ISEL-NEXT:    neg x0, x8, asr #52
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n52:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #4503599627370495 // =0xfffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #52
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -4503599627370496
  ret i64 %r
}

define i64 @sdiv_i64_n53(i64 %x) {
; ISEL-LABEL: sdiv_i64_n53:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #11
; ISEL-NEXT:    neg x0, x8, asr #53
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n53:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #9007199254740991 // =0x1fffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #53
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -9007199254740992
  ret i64 %r
}

define i64 @sdiv_i64_n54(i64 %x) {
; ISEL-LABEL: sdiv_i64_n54:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #10
; ISEL-NEXT:    neg x0, x8, asr #54
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n54:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #18014398509481983 // =0x3fffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #54
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -18014398509481984
  ret i64 %r
}

define i64 @sdiv_i64_n55(i64 %x) {
; ISEL-LABEL: sdiv_i64_n55:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #9
; ISEL-NEXT:    neg x0, x8, asr #55
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n55:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #36028797018963967 // =0x7fffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #55
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -36028797018963968
  ret i64 %r
}

define i64 @sdiv_i64_n56(i64 %x) {
; ISEL-LABEL: sdiv_i64_n56:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #8
; ISEL-NEXT:    neg x0, x8, asr #56
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n56:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #72057594037927935 // =0xffffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #56
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -72057594037927936
  ret i64 %r
}

define i64 @sdiv_i64_n57(i64 %x) {
; ISEL-LABEL: sdiv_i64_n57:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #7
; ISEL-NEXT:    neg x0, x8, asr #57
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n57:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #144115188075855871 // =0x1ffffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #57
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -144115188075855872
  ret i64 %r
}

define i64 @sdiv_i64_n58(i64 %x) {
; ISEL-LABEL: sdiv_i64_n58:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #6
; ISEL-NEXT:    neg x0, x8, asr #58
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n58:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #288230376151711743 // =0x3ffffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #58
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -288230376151711744
  ret i64 %r
}

define i64 @sdiv_i64_n59(i64 %x) {
; ISEL-LABEL: sdiv_i64_n59:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #5
; ISEL-NEXT:    neg x0, x8, asr #59
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n59:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #576460752303423487 // =0x7ffffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #59
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -576460752303423488
  ret i64 %r
}

define i64 @sdiv_i64_n60(i64 %x) {
; ISEL-LABEL: sdiv_i64_n60:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #4
; ISEL-NEXT:    neg x0, x8, asr #60
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n60:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #1152921504606846975 // =0xfffffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #60
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -1152921504606846976
  ret i64 %r
}

define i64 @sdiv_i64_n61(i64 %x) {
; ISEL-LABEL: sdiv_i64_n61:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #3
; ISEL-NEXT:    neg x0, x8, asr #61
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n61:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #2305843009213693951 // =0x1fffffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #61
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -2305843009213693952
  ret i64 %r
}

define i64 @sdiv_i64_n62(i64 %x) {
; ISEL-LABEL: sdiv_i64_n62:
; ISEL:       // %bb.0:
; ISEL-NEXT:    asr x8, x0, #63
; ISEL-NEXT:    add x8, x0, x8, lsr #2
; ISEL-NEXT:    neg x0, x8, asr #62
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n62:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #4611686018427387903 // =0x3fffffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #62
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -4611686018427387904
  ret i64 %r
}

define i64 @sdiv_i64_n63_intmin(i64 %x) {
; ISEL-LABEL: sdiv_i64_n63_intmin:
; ISEL:       // %bb.0:
; ISEL-NEXT:    mov x8, #-9223372036854775808 // =0x8000000000000000
; ISEL-NEXT:    cmp x0, x8
; ISEL-NEXT:    cset x0, eq
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_i64_n63_intmin:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #9223372036854775807 // =0x7fffffffffffffff
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    add x8, x0, x8
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    neg x0, x8, asr #63
; FAST-NEXT:    ret
  %r = sdiv i64 %x, -9223372036854775808
  ret i64 %r
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
