# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=aarch64-linux-gnu -mcp-use-is-copy-instr -run-pass=machine-cp -o - %s | FileCheck %s

---
name:            wreg_self_copy_not_deleted
alignment:       4
noPhis:          true
isSSA:           false
liveins:
  - { reg: '$w0' }
frameInfo:
  maxAlignment:    1
  maxCallFrameSize: 0
  isCalleeSavedInfoValid: true
machineFunctionInfo: {}
body:             |
  bb.0:
    liveins: $w0
    ; CHECK-LABEL: name: wreg_self_copy_not_deleted
    ; CHECK: liveins: $w0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $w0 = ORRWrs $wzr, $w0, 0
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    $w0 = ORRWrs $wzr, $w0, 0
    RET_ReallyLR implicit $w0
...
---
name:            wreg_self_copy_zero_extends_to_xreg_not_deleted
alignment:       4
noPhis:          true
isSSA:           false
liveins:
  - { reg: '$x0' }
frameInfo:
  maxAlignment:    1
  maxCallFrameSize: 0
  isCalleeSavedInfoValid: true
machineFunctionInfo: {}
body:             |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: wreg_self_copy_zero_extends_to_xreg_not_deleted
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $w0 = ORRWrs $wzr, $w0, 0, implicit-def $x0
    ; CHECK-NEXT: RET_ReallyLR implicit $x0
    $w0 = ORRWrs $wzr, $w0, 0, implicit-def $x0
    RET_ReallyLR implicit $x0
...
---
name:            xreg_self_copy_deleted
alignment:       4
noPhis:          true
isSSA:           false
liveins:
  - { reg: '$x0' }
frameInfo:
  maxAlignment:    1
  maxCallFrameSize: 0
  isCalleeSavedInfoValid: true
machineFunctionInfo: {}
body:             |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: xreg_self_copy_deleted
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: RET_ReallyLR implicit $x0
    $x0 = ORRXrs $xzr, $x0, 0
    RET_ReallyLR implicit $x0
...
---
name:            wreg_self_copy_kill_uses_xreg_not_deleted
alignment:       4
noPhis:          true
isSSA:           false
liveins:
  - { reg: '$x0' }
frameInfo:
  maxAlignment:    1
  maxCallFrameSize: 0
  isCalleeSavedInfoValid: true
machineFunctionInfo: {}
body:             |
  bb.0:
    liveins: $x0
    ; CHECK-LABEL: name: wreg_self_copy_kill_uses_xreg_not_deleted
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $w0 = ORRWrs $wzr, $w0, 0
    ; CHECK-NEXT: $x0 = KILL $w0
    ; CHECK-NEXT: RET_ReallyLR implicit $x0
    $w0 = ORRWrs $wzr, $w0, 0
    $x0 = KILL $w0
    RET_ReallyLR implicit $x0
...
