; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-linux-gnu < %s | FileCheck %s

define i1 @setcc_neverzero_eq_folding(i32 %x) {
; CHECK-LABEL: setcc_neverzero_eq_folding:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:    ret
    %1 = or i32 %x, 2
    %cmp = icmp eq i32 %1, 0
    ret i1 %cmp
}

define i1 @setcc_neverzero_ne_folding(i32 %x) {
; CHECK-LABEL: setcc_neverzero_ne_folding:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w0, #1 // =0x1
; CHECK-NEXT:    ret
    %1 = or i32 %x, 1
    %cmp = icmp ne i32 %1, 0
    ret i1 %cmp
}


define i1 @setcc_neverzero_uge_folding(i32 %x) {
; CHECK-LABEL: setcc_neverzero_uge_folding:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w0, #1 // =0x1
; CHECK-NEXT:    ret
    %cmp = icmp uge i32 %x, 0
    ret i1 %cmp
}

define <4 x i1> @setcc_neverzero_vector_uge_folding(<4 x i32> %v) {
; CHECK-LABEL: setcc_neverzero_vector_uge_folding:
; CHECK:       // %bb.0:
; CHECK-NEXT:    movi v0.2d, #0xffffffffffffffff
; CHECK-NEXT:    ret
    %forced_vector = or <4 x i32> %v, <i32 1, i32 1, i32 1, i32 1>
    %cmp = icmp uge <4 x i32> %forced_vector, zeroinitializer
    ret <4 x i1> %cmp
}
