; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=arm64-apple-ios -o - %s | FileCheck %s

@exception = external hidden constant { ptr, ptr, ptr }

define noundef i32 @call_with_no_ret(i32 %in) personality ptr @__gxx_personality_v0 {
; CHECK-LABEL: call_with_no_ret:
; CHECK:       Lfunc_begin0:
; CHECK-NEXT:    .cfi_startproc
; CHECK-NEXT:    .cfi_personality 155, ___gxx_personality_v0
; CHECK-NEXT:    .cfi_lsda 16, Lexception0
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    cmp w0, #1
; CHECK-NEXT:    b.eq LBB0_2
; CHECK-NEXT:  ; %bb.1: ; %exit
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:    ret
; CHECK-NEXT:  LBB0_2: ; %setup
; CHECK-NEXT:    stp x20, x19, [sp, #-32]! ; 16-byte Folded Spill
; CHECK-NEXT:    stp x29, x30, [sp, #16] ; 16-byte Folded Spill
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    .cfi_offset w30, -8
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    .cfi_offset w19, -24
; CHECK-NEXT:    .cfi_offset w20, -32
; CHECK-NEXT:    mov w0, #32 ; =0x20
; CHECK-NEXT:    bl ___cxa_allocate_exception
; CHECK-NEXT:  Ltmp0: ; EH_LABEL
; CHECK-NEXT:    bl _construct_exception
; CHECK-NEXT:  Ltmp1: ; EH_LABEL
; CHECK-NEXT:    ldp x29, x30, [sp, #16] ; 16-byte Folded Reload
; CHECK-NEXT:    ldp x20, x19, [sp], #32 ; 16-byte Folded Reload
; CHECK-NEXT:  ; %bb.3: ; %throw
; CHECK-NEXT:  Lloh0:
; CHECK-NEXT:    adrp x2, _destruct_exception@GOTPAGE
; CHECK-NEXT:  Lloh1:
; CHECK-NEXT:    adrp x1, _exception@PAGE
; CHECK-NEXT:  Lloh2:
; CHECK-NEXT:    add x1, x1, _exception@PAGEOFF
; CHECK-NEXT:  Lloh3:
; CHECK-NEXT:    ldr x2, [x2, _destruct_exception@GOTPAGEOFF]
; CHECK-NEXT:    mov x0, x19
; CHECK-NEXT:    bl ___cxa_throw
; CHECK-NEXT:  LBB0_4: ; %teardown
; CHECK-NEXT:  Ltmp2: ; EH_LABEL
; CHECK-NEXT:    mov x20, x0
; CHECK-NEXT:    mov x0, x19
; CHECK-NEXT:    bl ___cxa_free_exception
; CHECK-NEXT:    mov x0, x20
; CHECK-NEXT:    bl __Unwind_Resume
; CHECK-NEXT:    .loh AdrpAdd Lloh1, Lloh2
; CHECK-NEXT:    .loh AdrpLdrGot Lloh0, Lloh3
; CHECK-NEXT:  Lfunc_end0:
; CHECK-NEXT:    .cfi_endproc
; CHECK-NEXT:    .section __TEXT,__gcc_except_tab
; CHECK-NEXT:    .p2align 2, 0x0
; CHECK-NEXT:  GCC_except_table0:
; CHECK-NEXT:  Lexception0:
; CHECK-NEXT:    .byte 255 ; @LPStart Encoding = omit
; CHECK-NEXT:    .byte 255 ; @TType Encoding = omit
; CHECK-NEXT:    .byte 1 ; Call site Encoding = uleb128
; CHECK-NEXT:    .uleb128 Lcst_end0-Lcst_begin0
; CHECK-NEXT:  Lcst_begin0:
; CHECK-NEXT:    .uleb128 Lfunc_begin0-Lfunc_begin0 ; >> Call Site 1 <<
; CHECK-NEXT:    .uleb128 Ltmp0-Lfunc_begin0 ; Call between Lfunc_begin0 and Ltmp0
; CHECK-NEXT:    .byte 0 ; has no landing pad
; CHECK-NEXT:    .byte 0 ; On action: cleanup
; CHECK-NEXT:    .uleb128 Ltmp0-Lfunc_begin0 ; >> Call Site 2 <<
; CHECK-NEXT:    .uleb128 Ltmp1-Ltmp0 ; Call between Ltmp0 and Ltmp1
; CHECK-NEXT:    .uleb128 Ltmp2-Lfunc_begin0 ; jumps to Ltmp2
; CHECK-NEXT:    .byte 0 ; On action: cleanup
; CHECK-NEXT:    .uleb128 Ltmp1-Lfunc_begin0 ; >> Call Site 3 <<
; CHECK-NEXT:    .uleb128 Lfunc_end0-Ltmp1 ; Call between Ltmp1 and Lfunc_end0
; CHECK-NEXT:    .byte 0 ; has no landing pad
; CHECK-NEXT:    .byte 0 ; On action: cleanup
; CHECK-NEXT:  Lcst_end0:
; CHECK-NEXT:    .p2align 2, 0x0
entry:
  %cmp = icmp eq i32 %in, 1
  br i1 %cmp, label %setup, label %exit

setup:
  %exception = tail call ptr @__cxa_allocate_exception(i64 32) nounwind
  %call = invoke noundef ptr @construct_exception(ptr noundef nonnull %exception) to label %throw unwind label %teardown

throw:
  tail call void @__cxa_throw(ptr nonnull %exception, ptr nonnull @exception, ptr nonnull @destruct_exception) noreturn
  unreachable

teardown:
  %caught = landingpad { ptr, i32 } cleanup
  tail call void @__cxa_free_exception(ptr nonnull %exception) nounwind
  resume { ptr, i32 } %caught

exit:
  ret i32 0
}

declare i32 @__gxx_personality_v0(...)

declare ptr @__cxa_allocate_exception(i64) local_unnamed_addr
declare void @__cxa_free_exception(ptr) local_unnamed_addr
declare void @__cxa_throw(ptr, ptr, ptr) local_unnamed_addr cold noreturn

declare noundef ptr @construct_exception(ptr noundef nonnull returned) unnamed_addr
declare noundef ptr @destruct_exception(ptr noundef nonnull returned) unnamed_addr mustprogress nounwind ssp uwtable(sync)
