; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -O3 %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK-SD
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -O3 -global-isel -global-isel-abort=1 %s -verify-machineinstrs -o - | FileCheck %s --check-prefixes=CHECK-GI

%struct.p = type { i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32 }

define i32 @f(ptr byval(%struct.p) align 4 %q) nounwind {
; CHECK-SD-LABEL: f:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    b g
;
; CHECK-GI-LABEL: f:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    b g
entry:
  %call = tail call i32 @g(ptr byval(%struct.p) align 4 %q) nounwind
  ret i32 %call
}

declare i32 @g(ptr byval(%struct.p) align 4)

define i32 @h(ptr byval(%struct.p) align 4 %q, i32 %r) nounwind {
; CHECK-SD-LABEL: h:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    b i
;
; CHECK-GI-LABEL: h:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    b i
entry:
  %call = tail call i32 @i(ptr byval(%struct.p) align 4 %q, i32 %r) nounwind
  ret i32 %call
}

declare i32 @i(ptr byval(%struct.p) align 4, i32)

; The data on the stack overlaps with the space used to pass arguments to the tail call. To prevent
; stepping on our own tail, the byval argument should pass through a temporary in the stack frame.
define i32 @overlap_forward(i64 %a0, i64 %a1, i64 %a2, i64 %a3, i64 %a4, i64 %a5, i64 %a6, i64 %a7, ptr byval(%struct.p) align 8 %q, i64 %pad) nounwind {
; CHECK-SD-LABEL: overlap_forward:
; CHECK-SD:       // %bb.0: // %entry
; CHECK-SD-NEXT:    sub sp, sp, #48
; CHECK-SD-NEXT:    ldp q0, q1, [sp, #48]
; CHECK-SD-NEXT:    mov w8, #99 // =0x63
; CHECK-SD-NEXT:    ldr q2, [sp, #80]
; CHECK-SD-NEXT:    stp q0, q1, [sp]
; CHECK-SD-NEXT:    str q2, [sp, #32]
; CHECK-SD-NEXT:    stur q0, [sp, #56]
; CHECK-SD-NEXT:    stur q1, [sp, #72]
; CHECK-SD-NEXT:    stur q2, [sp, #88]
; CHECK-SD-NEXT:    str x8, [sp, #48]!
; CHECK-SD-NEXT:    b overlap_callee
;
; CHECK-GI-LABEL: overlap_forward:
; CHECK-GI:       // %bb.0: // %entry
; CHECK-GI-NEXT:    sub sp, sp, #48
; CHECK-GI-NEXT:    mov w8, #99 // =0x63
; CHECK-GI-NEXT:    str x8, [sp, #48]
; CHECK-GI-NEXT:    ldp q1, q0, [sp, #48]
; CHECK-GI-NEXT:    stp q1, q0, [sp]
; CHECK-GI-NEXT:    ldr q0, [sp, #80]
; CHECK-GI-NEXT:    ldr q1, [sp]
; CHECK-GI-NEXT:    str q0, [sp, #32]
; CHECK-GI-NEXT:    stur q1, [sp, #56]
; CHECK-GI-NEXT:    ldp q1, q0, [sp, #16]
; CHECK-GI-NEXT:    stur q1, [sp, #72]
; CHECK-GI-NEXT:    stur q0, [sp, #88]
; CHECK-GI-NEXT:    add sp, sp, #48
; CHECK-GI-NEXT:    b overlap_callee
entry:
  %call = tail call i32 @overlap_callee(i64 %a0, i64 %a1, i64 %a2, i64 %a3, i64 %a4, i64 %a5, i64 %a6, i64 %a7, i64 99, ptr byval(%struct.p) align 8 %q) nounwind
  ret i32 %call
}

declare i32 @overlap_callee(i64, i64, i64, i64, i64, i64, i64, i64, i64, ptr byval(%struct.p) align 8)
