; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-none-linux-gnu %s -o - | FileCheck %s --check-prefix=CHECK-NO-PAUTH
; RUN: llc -mtriple=aarch64-none-linux-gnu -mattr=+pauth %s -o - | FileCheck %s --check-prefix=CHECK-PAUTH
; RUN: llc -mtriple=aarch64-none-linux-gnu -mattr=+pauth-lr %s -o - | FileCheck %s --check-prefix=CHECK-PAUTHLR
; RUN: llc -mtriple=aarch64-none-linux-gnu -mattr=+pauth,+pauth-lr %s -o - | FileCheck %s --check-prefix=CHECK-PAUTH-PAUTHLR

define i32 @f() #0 {
; CHECK-NO-PAUTH-LABEL: f:
; CHECK-NO-PAUTH:       // %bb.0: // %entry
; CHECK-NO-PAUTH-NEXT:    dsb sy
; CHECK-NO-PAUTH-NEXT:    isb
; CHECK-NO-PAUTH-NEXT:    hint #39
; CHECK-NO-PAUTH-NEXT:    .cfi_llvm_set_ra_state 2, .Ltmp0
; CHECK-NO-PAUTH-NEXT:  .Ltmp0:
; CHECK-NO-PAUTH-NEXT:    hint #25
; CHECK-NO-PAUTH-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NO-PAUTH-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NO-PAUTH-NEXT:    .cfi_offset w30, -16
; CHECK-NO-PAUTH-NEXT:    hint #7
; CHECK-NO-PAUTH-NEXT:    mov w0, wzr
; CHECK-NO-PAUTH-NEXT:    //APP
; CHECK-NO-PAUTH-NEXT:    //NO_APP
; CHECK-NO-PAUTH-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-NO-PAUTH-NEXT:    adrp x16, .Ltmp0
; CHECK-NO-PAUTH-NEXT:    add x16, x16, :lo12:.Ltmp0
; CHECK-NO-PAUTH-NEXT:    hint #39
; CHECK-NO-PAUTH-NEXT:    hint #29
; CHECK-NO-PAUTH-NEXT:    ret
;
; CHECK-PAUTH-LABEL: f:
; CHECK-PAUTH:       // %bb.0: // %entry
; CHECK-PAUTH-NEXT:    dsb sy
; CHECK-PAUTH-NEXT:    isb
; CHECK-PAUTH-NEXT:    hint #39
; CHECK-PAUTH-NEXT:    .cfi_llvm_set_ra_state 2, .Ltmp0
; CHECK-PAUTH-NEXT:  .Ltmp0:
; CHECK-PAUTH-NEXT:    paciasp
; CHECK-PAUTH-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-PAUTH-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PAUTH-NEXT:    .cfi_offset w30, -16
; CHECK-PAUTH-NEXT:    xpaci x30
; CHECK-PAUTH-NEXT:    mov w0, wzr
; CHECK-PAUTH-NEXT:    //APP
; CHECK-PAUTH-NEXT:    //NO_APP
; CHECK-PAUTH-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-PAUTH-NEXT:    adrp x16, .Ltmp0
; CHECK-PAUTH-NEXT:    add x16, x16, :lo12:.Ltmp0
; CHECK-PAUTH-NEXT:    hint #39
; CHECK-PAUTH-NEXT:    retaa
;
; CHECK-PAUTHLR-LABEL: f:
; CHECK-PAUTHLR:       // %bb.0: // %entry
; CHECK-PAUTHLR-NEXT:    cmp sp, #0
; CHECK-PAUTHLR-NEXT:    csetm x16, ne
; CHECK-PAUTHLR-NEXT:    .cfi_llvm_set_ra_state 2, .Ltmp0
; CHECK-PAUTHLR-NEXT:  .Ltmp0:
; CHECK-PAUTHLR-NEXT:    paciasppc
; CHECK-PAUTHLR-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-PAUTHLR-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PAUTHLR-NEXT:    .cfi_offset w30, -16
; CHECK-PAUTHLR-NEXT:    hint #7
; CHECK-PAUTHLR-NEXT:    mov w0, wzr
; CHECK-PAUTHLR-NEXT:    //APP
; CHECK-PAUTHLR-NEXT:    //NO_APP
; CHECK-PAUTHLR-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-PAUTHLR-NEXT:    and x30, x30, x16
; CHECK-PAUTHLR-NEXT:    csdb
; CHECK-PAUTHLR-NEXT:    mov x1, sp
; CHECK-PAUTHLR-NEXT:    autiasppc .Ltmp0
; CHECK-PAUTHLR-NEXT:    and x1, x1, x16
; CHECK-PAUTHLR-NEXT:    mov sp, x1
; CHECK-PAUTHLR-NEXT:    ret
;
; CHECK-PAUTH-PAUTHLR-LABEL: f:
; CHECK-PAUTH-PAUTHLR:       // %bb.0: // %entry
; CHECK-PAUTH-PAUTHLR-NEXT:    cmp sp, #0
; CHECK-PAUTH-PAUTHLR-NEXT:    csetm x16, ne
; CHECK-PAUTH-PAUTHLR-NEXT:    .cfi_llvm_set_ra_state 2, .Ltmp0
; CHECK-PAUTH-PAUTHLR-NEXT:  .Ltmp0:
; CHECK-PAUTH-PAUTHLR-NEXT:    paciasppc
; CHECK-PAUTH-PAUTHLR-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-PAUTH-PAUTHLR-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PAUTH-PAUTHLR-NEXT:    .cfi_offset w30, -16
; CHECK-PAUTH-PAUTHLR-NEXT:    xpaci x30
; CHECK-PAUTH-PAUTHLR-NEXT:    mov w0, wzr
; CHECK-PAUTH-PAUTHLR-NEXT:    //APP
; CHECK-PAUTH-PAUTHLR-NEXT:    //NO_APP
; CHECK-PAUTH-PAUTHLR-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-PAUTH-PAUTHLR-NEXT:    and x30, x30, x16
; CHECK-PAUTH-PAUTHLR-NEXT:    csdb
; CHECK-PAUTH-PAUTHLR-NEXT:    mov x1, sp
; CHECK-PAUTH-PAUTHLR-NEXT:    and x1, x1, x16
; CHECK-PAUTH-PAUTHLR-NEXT:    mov sp, x1
; CHECK-PAUTH-PAUTHLR-NEXT:    retaasppc .Ltmp0
entry:
  %0 = tail call ptr @llvm.returnaddress(i32 0)
  tail call void asm sideeffect "", "r"(ptr %0)
  ret i32 0
}

declare ptr @llvm.returnaddress(i32 immarg)

attributes #0 = { speculative_load_hardening "branch-protection-pauth-lr" "sign-return-address"="all" "sign-return-address-key"="a_key" }
