; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py

; RUN: llc -mtriple=aarch64 -stop-after=aarch64-ptrauth              < %s | FileCheck --check-prefixes=CHECK-MIR,COMPAT-MIR %s
; RUN: llc -mtriple=aarch64 -stop-after=aarch64-ptrauth -mattr=v8.3a < %s | FileCheck --check-prefixes=CHECK-MIR,V83A-MIR %s
; RUN: llc -mtriple=aarch64 -stop-after=aarch64-ptrauth -mattr=v9a -mattr=pauth-lr < %s | FileCheck --check-prefixes=PAUTHLR-MIR %s

; See also: sign-return-address-pauth-lr.ll

define i32 @leaf(i32 %x) "branch-protection-pauth-lr" {
  ; CHECK-MIR-LABEL: name: leaf
  ; CHECK-MIR: bb.0 (%ir-block.0):
  ; CHECK-MIR-NEXT:   liveins: $w0
  ; CHECK-MIR-NEXT: {{  $}}
  ; CHECK-MIR-NEXT:   RET undef $lr, implicit killed $w0
  ;
  ; PAUTHLR-MIR-LABEL: name: leaf
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $w0
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   RET undef $lr, implicit killed $w0
  ret i32 %x
}

define i32 @leaf_sign_none(i32 %x) "branch-protection-pauth-lr"   {
  ; CHECK-MIR-LABEL: name: leaf_sign_none
  ; CHECK-MIR: bb.0 (%ir-block.0):
  ; CHECK-MIR-NEXT:   liveins: $w0
  ; CHECK-MIR-NEXT: {{  $}}
  ; CHECK-MIR-NEXT:   RET undef $lr, implicit killed $w0
  ;
  ; PAUTHLR-MIR-LABEL: name: leaf_sign_none
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $w0
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   RET undef $lr, implicit killed $w0
  ret i32 %x
}

define i32 @leaf_sign_non_leaf(i32 %x) "branch-protection-pauth-lr" "sign-return-address"="non-leaf"  {
  ; CHECK-MIR-LABEL: name: leaf_sign_non_leaf
  ; CHECK-MIR: bb.0 (%ir-block.0):
  ; CHECK-MIR-NEXT:   liveins: $w0
  ; CHECK-MIR-NEXT: {{  $}}
  ; CHECK-MIR-NEXT:   RET undef $lr, implicit killed $w0
  ;
  ; PAUTHLR-MIR-LABEL: name: leaf_sign_non_leaf
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $w0
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   RET undef $lr, implicit killed $w0
  ret i32 %x
}

define i32 @leaf_sign_all(i32 %x) "branch-protection-pauth-lr" "sign-return-address"="all" {
  ; COMPAT-MIR-LABEL: name: leaf_sign_all
  ; COMPAT-MIR: bb.0 (%ir-block.0):
  ; COMPAT-MIR-NEXT:   liveins: $w0
  ; COMPAT-MIR-NEXT: {{  $}}
  ; COMPAT-MIR-NEXT:   frame-setup PACM
  ; COMPAT-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; COMPAT-MIR-NEXT:   frame-setup PACIASP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; COMPAT-MIR-NEXT:   frame-destroy PACM
  ; COMPAT-MIR-NEXT:   frame-destroy AUTIASP implicit-def $lr, implicit $lr, implicit $sp
  ; COMPAT-MIR-NEXT:   RET undef $lr, implicit killed $w0
  ;
  ; V83A-MIR-LABEL: name: leaf_sign_all
  ; V83A-MIR: bb.0 (%ir-block.0):
  ; V83A-MIR-NEXT:   liveins: $w0
  ; V83A-MIR-NEXT: {{  $}}
  ; V83A-MIR-NEXT:   frame-setup PACM
  ; V83A-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; V83A-MIR-NEXT:   frame-setup PACIASP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; V83A-MIR-NEXT:   frame-destroy PACM
  ; V83A-MIR-NEXT:   frame-destroy RETAA implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp, implicit-def $x16
  ;
  ; PAUTHLR-MIR-LABEL: name: leaf_sign_all
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $w0
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; PAUTHLR-MIR-NEXT:   frame-setup PACIASPPC implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; PAUTHLR-MIR-NEXT:   frame-destroy RETAASPPCi <mcsymbol >, implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp
  ret i32 %x
}

define i64 @leaf_clobbers_lr(i64 %x) "branch-protection-pauth-lr" "sign-return-address"="non-leaf"  {
  ; COMPAT-MIR-LABEL: name: leaf_clobbers_lr
  ; COMPAT-MIR: bb.0 (%ir-block.0):
  ; COMPAT-MIR-NEXT:   liveins: $x0, $lr
  ; COMPAT-MIR-NEXT: {{  $}}
  ; COMPAT-MIR-NEXT:   frame-setup PACM
  ; COMPAT-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; COMPAT-MIR-NEXT:   frame-setup PACIASP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; COMPAT-MIR-NEXT:   early-clobber $sp = frame-setup STRXpre killed $lr, $sp, -16 :: (store (s64) into %stack.0)
  ; COMPAT-MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
  ; COMPAT-MIR-NEXT:   frame-setup CFI_INSTRUCTION offset $w30, -16
  ; COMPAT-MIR-NEXT:   INLINEASM &"mov x30, $0", sideeffect attdialect, reguse:GPR64common, renamable $x0, clobber, implicit-def dead $lr
  ; COMPAT-MIR-NEXT:   early-clobber $sp, $lr = frame-destroy LDRXpost $sp, 16 :: (load (s64) from %stack.0)
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; COMPAT-MIR-NEXT:   frame-destroy PACM
  ; COMPAT-MIR-NEXT:   frame-destroy AUTIASP implicit-def $lr, implicit $lr, implicit $sp
  ; COMPAT-MIR-NEXT:   RET undef $lr, implicit killed $x0
  ;
  ; V83A-MIR-LABEL: name: leaf_clobbers_lr
  ; V83A-MIR: bb.0 (%ir-block.0):
  ; V83A-MIR-NEXT:   liveins: $x0, $lr
  ; V83A-MIR-NEXT: {{  $}}
  ; V83A-MIR-NEXT:   frame-setup PACM
  ; V83A-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; V83A-MIR-NEXT:   frame-setup PACIASP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; V83A-MIR-NEXT:   early-clobber $sp = frame-setup STRXpre killed $lr, $sp, -16 :: (store (s64) into %stack.0)
  ; V83A-MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
  ; V83A-MIR-NEXT:   frame-setup CFI_INSTRUCTION offset $w30, -16
  ; V83A-MIR-NEXT:   INLINEASM &"mov x30, $0", sideeffect attdialect, reguse:GPR64common, renamable $x0, clobber, implicit-def dead $lr
  ; V83A-MIR-NEXT:   early-clobber $sp, $lr = frame-destroy LDRXpost $sp, 16 :: (load (s64) from %stack.0)
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; V83A-MIR-NEXT:   frame-destroy PACM
  ; V83A-MIR-NEXT:   frame-destroy RETAA implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp, implicit-def $x16
  ;
  ; PAUTHLR-MIR-LABEL: name: leaf_clobbers_lr
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $x0, $lr
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; PAUTHLR-MIR-NEXT:   frame-setup PACIASPPC implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; PAUTHLR-MIR-NEXT:   early-clobber $sp = frame-setup STRXpre killed $lr, $sp, -16 :: (store (s64) into %stack.0)
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION offset $w30, -16
  ; PAUTHLR-MIR-NEXT:   INLINEASM &"mov x30, $0", sideeffect attdialect, reguse:GPR64common, renamable $x0, clobber, implicit-def dead $lr
  ; PAUTHLR-MIR-NEXT:   early-clobber $sp, $lr = frame-destroy LDRXpost $sp, 16 :: (load (s64) from %stack.0)
  ; PAUTHLR-MIR-NEXT:   frame-destroy RETAASPPCi <mcsymbol >, implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp
  call void asm sideeffect "mov x30, $0", "r,~{lr}"(i64 %x) #1
  ret i64 %x
}

declare i32 @foo(i32)

define i32 @non_leaf_sign_all(i32 %x) "branch-protection-pauth-lr" "sign-return-address"="all" {
  ; COMPAT-MIR-LABEL: name: non_leaf_sign_all
  ; COMPAT-MIR: bb.0 (%ir-block.0):
  ; COMPAT-MIR-NEXT:   liveins: $w0, $lr
  ; COMPAT-MIR-NEXT: {{  $}}
  ; COMPAT-MIR-NEXT:   frame-setup PACM
  ; COMPAT-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; COMPAT-MIR-NEXT:   frame-setup PACIASP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; COMPAT-MIR-NEXT:   early-clobber $sp = frame-setup STRXpre killed $lr, $sp, -16 :: (store (s64) into %stack.0)
  ; COMPAT-MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
  ; COMPAT-MIR-NEXT:   frame-setup CFI_INSTRUCTION offset $w30, -16
  ; COMPAT-MIR-NEXT:   BL @foo, csr_aarch64_aapcs, implicit-def dead $lr, implicit $sp, implicit killed $w0, implicit-def $sp, implicit-def $w0
  ; COMPAT-MIR-NEXT:   early-clobber $sp, $lr = frame-destroy LDRXpost $sp, 16 :: (load (s64) from %stack.0)
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; COMPAT-MIR-NEXT:   frame-destroy PACM
  ; COMPAT-MIR-NEXT:   frame-destroy AUTIASP implicit-def $lr, implicit $lr, implicit $sp
  ; COMPAT-MIR-NEXT:   RET undef $lr, implicit killed $w0
  ;
  ; V83A-MIR-LABEL: name: non_leaf_sign_all
  ; V83A-MIR: bb.0 (%ir-block.0):
  ; V83A-MIR-NEXT:   liveins: $w0, $lr
  ; V83A-MIR-NEXT: {{  $}}
  ; V83A-MIR-NEXT:   frame-setup PACM
  ; V83A-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; V83A-MIR-NEXT:   frame-setup PACIASP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; V83A-MIR-NEXT:   early-clobber $sp = frame-setup STRXpre killed $lr, $sp, -16 :: (store (s64) into %stack.0)
  ; V83A-MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
  ; V83A-MIR-NEXT:   frame-setup CFI_INSTRUCTION offset $w30, -16
  ; V83A-MIR-NEXT:   BL @foo, csr_aarch64_aapcs, implicit-def dead $lr, implicit $sp, implicit killed $w0, implicit-def $sp, implicit-def $w0
  ; V83A-MIR-NEXT:   early-clobber $sp, $lr = frame-destroy LDRXpost $sp, 16 :: (load (s64) from %stack.0)
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; V83A-MIR-NEXT:   frame-destroy PACM
  ; V83A-MIR-NEXT:   frame-destroy RETAA implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp, implicit-def $x16
  ;
  ; PAUTHLR-MIR-LABEL: name: non_leaf_sign_all
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $w0, $lr
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; PAUTHLR-MIR-NEXT:   frame-setup PACIASPPC implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; PAUTHLR-MIR-NEXT:   early-clobber $sp = frame-setup STRXpre killed $lr, $sp, -16 :: (store (s64) into %stack.0)
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION offset $w30, -16
  ; PAUTHLR-MIR-NEXT:   BL @foo, csr_aarch64_aapcs, implicit-def dead $lr, implicit $sp, implicit killed $w0, implicit-def $sp, implicit-def $w0
  ; PAUTHLR-MIR-NEXT:   early-clobber $sp, $lr = frame-destroy LDRXpost $sp, 16 :: (load (s64) from %stack.0)
  ; PAUTHLR-MIR-NEXT:   frame-destroy RETAASPPCi <mcsymbol >, implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp
  %call = call i32 @foo(i32 %x)
  ret i32 %call
}

define i32 @non_leaf_sign_non_leaf(i32 %x) "branch-protection-pauth-lr" "sign-return-address"="non-leaf"  {
  ; COMPAT-MIR-LABEL: name: non_leaf_sign_non_leaf
  ; COMPAT-MIR: bb.0 (%ir-block.0):
  ; COMPAT-MIR-NEXT:   liveins: $w0, $lr
  ; COMPAT-MIR-NEXT: {{  $}}
  ; COMPAT-MIR-NEXT:   frame-setup PACM
  ; COMPAT-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; COMPAT-MIR-NEXT:   frame-setup PACIASP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; COMPAT-MIR-NEXT:   early-clobber $sp = frame-setup STRXpre killed $lr, $sp, -16 :: (store (s64) into %stack.0)
  ; COMPAT-MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
  ; COMPAT-MIR-NEXT:   frame-setup CFI_INSTRUCTION offset $w30, -16
  ; COMPAT-MIR-NEXT:   BL @foo, csr_aarch64_aapcs, implicit-def dead $lr, implicit $sp, implicit killed $w0, implicit-def $sp, implicit-def $w0
  ; COMPAT-MIR-NEXT:   early-clobber $sp, $lr = frame-destroy LDRXpost $sp, 16 :: (load (s64) from %stack.0)
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; COMPAT-MIR-NEXT:   frame-destroy PACM
  ; COMPAT-MIR-NEXT:   frame-destroy AUTIASP implicit-def $lr, implicit $lr, implicit $sp
  ; COMPAT-MIR-NEXT:   RET undef $lr, implicit killed $w0
  ;
  ; V83A-MIR-LABEL: name: non_leaf_sign_non_leaf
  ; V83A-MIR: bb.0 (%ir-block.0):
  ; V83A-MIR-NEXT:   liveins: $w0, $lr
  ; V83A-MIR-NEXT: {{  $}}
  ; V83A-MIR-NEXT:   frame-setup PACM
  ; V83A-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; V83A-MIR-NEXT:   frame-setup PACIASP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; V83A-MIR-NEXT:   early-clobber $sp = frame-setup STRXpre killed $lr, $sp, -16 :: (store (s64) into %stack.0)
  ; V83A-MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
  ; V83A-MIR-NEXT:   frame-setup CFI_INSTRUCTION offset $w30, -16
  ; V83A-MIR-NEXT:   BL @foo, csr_aarch64_aapcs, implicit-def dead $lr, implicit $sp, implicit killed $w0, implicit-def $sp, implicit-def $w0
  ; V83A-MIR-NEXT:   early-clobber $sp, $lr = frame-destroy LDRXpost $sp, 16 :: (load (s64) from %stack.0)
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; V83A-MIR-NEXT:   frame-destroy PACM
  ; V83A-MIR-NEXT:   frame-destroy RETAA implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp, implicit-def $x16
  ;
  ; PAUTHLR-MIR-LABEL: name: non_leaf_sign_non_leaf
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $w0, $lr
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; PAUTHLR-MIR-NEXT:   frame-setup PACIASPPC implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; PAUTHLR-MIR-NEXT:   early-clobber $sp = frame-setup STRXpre killed $lr, $sp, -16 :: (store (s64) into %stack.0)
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION offset $w30, -16
  ; PAUTHLR-MIR-NEXT:   BL @foo, csr_aarch64_aapcs, implicit-def dead $lr, implicit $sp, implicit killed $w0, implicit-def $sp, implicit-def $w0
  ; PAUTHLR-MIR-NEXT:   early-clobber $sp, $lr = frame-destroy LDRXpost $sp, 16 :: (load (s64) from %stack.0)
  ; PAUTHLR-MIR-NEXT:   frame-destroy RETAASPPCi <mcsymbol >, implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp
  %call = call i32 @foo(i32 %x)
  ret i32 %call
}

define i32 @non_leaf_scs(i32 %x) "branch-protection-pauth-lr" "sign-return-address"="non-leaf" shadowcallstack "target-features"="+v8.3a,+reserve-x18"  {
  ; CHECK-MIR-LABEL: name: non_leaf_scs
  ; CHECK-MIR: bb.0 (%ir-block.0):
  ; CHECK-MIR-NEXT:   liveins: $w0, $lr, $x18
  ; CHECK-MIR-NEXT: {{  $}}
  ; CHECK-MIR-NEXT:   frame-setup PACM
  ; CHECK-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; CHECK-MIR-NEXT:   frame-setup PACIASP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; CHECK-MIR-NEXT:   early-clobber $x18 = frame-setup STRXpost $lr, $x18, 8
  ; CHECK-MIR-NEXT:   frame-setup CFI_INSTRUCTION escape 0x16, 0x12, 0x02, 0x82, 0x78
  ; CHECK-MIR-NEXT:   early-clobber $sp = frame-setup STRXpre killed $lr, $sp, -16 :: (store (s64) into %stack.0)
  ; CHECK-MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
  ; CHECK-MIR-NEXT:   frame-setup CFI_INSTRUCTION offset $w30, -16
  ; CHECK-MIR-NEXT:   BL @foo, csr_aarch64_aapcs_scs, implicit-def dead $lr, implicit $sp, implicit killed $w0, implicit-def $sp, implicit-def $w0
  ; CHECK-MIR-NEXT:   early-clobber $sp, $lr = frame-destroy LDRXpost $sp, 16 :: (load (s64) from %stack.0)
  ; CHECK-MIR-NEXT:   early-clobber $x18, $lr = frame-destroy LDRXpre $x18, -8
  ; CHECK-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; CHECK-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; CHECK-MIR-NEXT:   frame-destroy PACM
  ; CHECK-MIR-NEXT:   frame-destroy AUTIASP implicit-def $lr, implicit $lr, implicit $sp
  ; CHECK-MIR-NEXT:   RET undef $lr, implicit killed $w0
  ;
  ; PAUTHLR-MIR-LABEL: name: non_leaf_scs
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $w0, $lr, $x18
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; PAUTHLR-MIR-NEXT:   frame-setup PACIASPPC implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; PAUTHLR-MIR-NEXT:   early-clobber $x18 = frame-setup STRXpost $lr, $x18, 8
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION escape 0x16, 0x12, 0x02, 0x82, 0x78
  ; PAUTHLR-MIR-NEXT:   early-clobber $sp = frame-setup STRXpre killed $lr, $sp, -16 :: (store (s64) into %stack.0)
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION offset $w30, -16
  ; PAUTHLR-MIR-NEXT:   BL @foo, csr_aarch64_aapcs_scs, implicit-def dead $lr, implicit $sp, implicit killed $w0, implicit-def $sp, implicit-def $w0
  ; PAUTHLR-MIR-NEXT:   early-clobber $sp, $lr = frame-destroy LDRXpost $sp, 16 :: (load (s64) from %stack.0)
  ; PAUTHLR-MIR-NEXT:   early-clobber $x18, $lr = frame-destroy LDRXpre $x18, -8
  ; PAUTHLR-MIR-NEXT:   frame-destroy AUTIASPPCi <mcsymbol >, implicit-def $lr, implicit $lr, implicit $sp
  ; PAUTHLR-MIR-NEXT:   RET undef $lr, implicit killed $w0
  %call = call i32 @foo(i32 %x)
  ret i32 %call
}

define i32 @leaf_sign_all_v83(i32 %x) "branch-protection-pauth-lr" "sign-return-address"="all" "target-features"="+v8.3a" {
  ; CHECK-MIR-LABEL: name: leaf_sign_all_v83
  ; CHECK-MIR: bb.0 (%ir-block.0):
  ; CHECK-MIR-NEXT:   liveins: $w0
  ; CHECK-MIR-NEXT: {{  $}}
  ; CHECK-MIR-NEXT:   frame-setup PACM
  ; CHECK-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; CHECK-MIR-NEXT:   frame-setup PACIASP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; CHECK-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; CHECK-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; CHECK-MIR-NEXT:   frame-destroy PACM
  ; CHECK-MIR-NEXT:   frame-destroy RETAA implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp, implicit-def $x16
  ;
  ; PAUTHLR-MIR-LABEL: name: leaf_sign_all_v83
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $w0
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; PAUTHLR-MIR-NEXT:   frame-setup PACIASPPC implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; PAUTHLR-MIR-NEXT:   frame-destroy RETAASPPCi <mcsymbol >, implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp
  ret i32 %x
}

declare fastcc i64 @bar(i64)

define fastcc void @spill_lr_and_tail_call(i64 %x) "branch-protection-pauth-lr" "sign-return-address"="all" {
  ; CHECK-MIR-LABEL: name: spill_lr_and_tail_call
  ; CHECK-MIR: bb.0 (%ir-block.0):
  ; CHECK-MIR-NEXT:   liveins: $x0, $lr
  ; CHECK-MIR-NEXT: {{  $}}
  ; CHECK-MIR-NEXT:   frame-setup PACM
  ; CHECK-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; CHECK-MIR-NEXT:   frame-setup PACIASP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; CHECK-MIR-NEXT:   early-clobber $sp = frame-setup STRXpre killed $lr, $sp, -16 :: (store (s64) into %stack.0)
  ; CHECK-MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
  ; CHECK-MIR-NEXT:   frame-setup CFI_INSTRUCTION offset $w30, -16
  ; CHECK-MIR-NEXT:   INLINEASM &"mov x30, $0", sideeffect attdialect, reguse:GPR64common, renamable $x0, clobber, implicit-def dead $lr
  ; CHECK-MIR-NEXT:   early-clobber $sp, $lr = frame-destroy LDRXpost $sp, 16 :: (load (s64) from %stack.0)
  ; CHECK-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; CHECK-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; CHECK-MIR-NEXT:   frame-destroy PACM
  ; CHECK-MIR-NEXT:   frame-destroy AUTIASP implicit-def $lr, implicit $lr, implicit $sp
  ; CHECK-MIR-NEXT:   TCRETURNdi @bar, 0, csr_aarch64_aapcs, implicit $sp, implicit killed $x0
  ;
  ; PAUTHLR-MIR-LABEL: name: spill_lr_and_tail_call
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $x0, $lr
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; PAUTHLR-MIR-NEXT:   frame-setup PACIASPPC implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; PAUTHLR-MIR-NEXT:   early-clobber $sp = frame-setup STRXpre killed $lr, $sp, -16 :: (store (s64) into %stack.0)
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION offset $w30, -16
  ; PAUTHLR-MIR-NEXT:   INLINEASM &"mov x30, $0", sideeffect attdialect, reguse:GPR64common, renamable $x0, clobber, implicit-def dead $lr
  ; PAUTHLR-MIR-NEXT:   early-clobber $sp, $lr = frame-destroy LDRXpost $sp, 16 :: (load (s64) from %stack.0)
  ; PAUTHLR-MIR-NEXT:   frame-destroy AUTIASPPCi <mcsymbol >, implicit-def $lr, implicit $lr, implicit $sp
  ; PAUTHLR-MIR-NEXT:   TCRETURNdi @bar, 0, csr_aarch64_aapcs, implicit $sp, implicit killed $x0
  call void asm sideeffect "mov x30, $0", "r,~{lr}"(i64 %x) #1
  tail call fastcc i64 @bar(i64 %x)
  ret void
}

define i32 @leaf_sign_all_a_key(i32 %x) "branch-protection-pauth-lr" "sign-return-address"="all" "sign-return-address-key"="a_key" {
  ; COMPAT-MIR-LABEL: name: leaf_sign_all_a_key
  ; COMPAT-MIR: bb.0 (%ir-block.0):
  ; COMPAT-MIR-NEXT:   liveins: $w0
  ; COMPAT-MIR-NEXT: {{  $}}
  ; COMPAT-MIR-NEXT:   frame-setup PACM
  ; COMPAT-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; COMPAT-MIR-NEXT:   frame-setup PACIASP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; COMPAT-MIR-NEXT:   frame-destroy PACM
  ; COMPAT-MIR-NEXT:   frame-destroy AUTIASP implicit-def $lr, implicit $lr, implicit $sp
  ; COMPAT-MIR-NEXT:   RET undef $lr, implicit killed $w0
  ;
  ; V83A-MIR-LABEL: name: leaf_sign_all_a_key
  ; V83A-MIR: bb.0 (%ir-block.0):
  ; V83A-MIR-NEXT:   liveins: $w0
  ; V83A-MIR-NEXT: {{  $}}
  ; V83A-MIR-NEXT:   frame-setup PACM
  ; V83A-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; V83A-MIR-NEXT:   frame-setup PACIASP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; V83A-MIR-NEXT:   frame-destroy PACM
  ; V83A-MIR-NEXT:   frame-destroy RETAA implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp, implicit-def $x16
  ;
  ; PAUTHLR-MIR-LABEL: name: leaf_sign_all_a_key
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $w0
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; PAUTHLR-MIR-NEXT:   frame-setup PACIASPPC implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; PAUTHLR-MIR-NEXT:   frame-destroy RETAASPPCi <mcsymbol >, implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp
  ret i32 %x
}

define i32 @leaf_sign_all_b_key(i32 %x) "branch-protection-pauth-lr" "sign-return-address"="all" "sign-return-address-key"="b_key" {
  ; COMPAT-MIR-LABEL: name: leaf_sign_all_b_key
  ; COMPAT-MIR: bb.0 (%ir-block.0):
  ; COMPAT-MIR-NEXT:   liveins: $w0
  ; COMPAT-MIR-NEXT: {{  $}}
  ; COMPAT-MIR-NEXT:   frame-setup EMITBKEY
  ; COMPAT-MIR-NEXT:   frame-setup PACM
  ; COMPAT-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; COMPAT-MIR-NEXT:   frame-setup PACIBSP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; COMPAT-MIR-NEXT:   frame-destroy PACM
  ; COMPAT-MIR-NEXT:   frame-destroy AUTIBSP implicit-def $lr, implicit $lr, implicit $sp
  ; COMPAT-MIR-NEXT:   RET undef $lr, implicit killed $w0
  ;
  ; V83A-MIR-LABEL: name: leaf_sign_all_b_key
  ; V83A-MIR: bb.0 (%ir-block.0):
  ; V83A-MIR-NEXT:   liveins: $w0
  ; V83A-MIR-NEXT: {{  $}}
  ; V83A-MIR-NEXT:   frame-setup EMITBKEY
  ; V83A-MIR-NEXT:   frame-setup PACM
  ; V83A-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; V83A-MIR-NEXT:   frame-setup PACIBSP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; V83A-MIR-NEXT:   frame-destroy PACM
  ; V83A-MIR-NEXT:   frame-destroy RETAB implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp, implicit-def $x16
  ;
  ; PAUTHLR-MIR-LABEL: name: leaf_sign_all_b_key
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $w0
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   frame-setup EMITBKEY
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; PAUTHLR-MIR-NEXT:   frame-setup PACIBSPPC implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; PAUTHLR-MIR-NEXT:   frame-destroy RETABSPPCi <mcsymbol >, implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp
  ret i32 %x
}

define i32 @leaf_sign_all_v83_b_key(i32 %x) "branch-protection-pauth-lr" "sign-return-address"="all" "target-features"="+v8.3a" "sign-return-address-key"="b_key" {
  ; CHECK-MIR-LABEL: name: leaf_sign_all_v83_b_key
  ; CHECK-MIR: bb.0 (%ir-block.0):
  ; CHECK-MIR-NEXT:   liveins: $w0
  ; CHECK-MIR-NEXT: {{  $}}
  ; CHECK-MIR-NEXT:   frame-setup EMITBKEY
  ; CHECK-MIR-NEXT:   frame-setup PACM
  ; CHECK-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; CHECK-MIR-NEXT:   frame-setup PACIBSP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; CHECK-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; CHECK-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; CHECK-MIR-NEXT:   frame-destroy PACM
  ; CHECK-MIR-NEXT:   frame-destroy RETAB implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp, implicit-def $x16
  ;
  ; PAUTHLR-MIR-LABEL: name: leaf_sign_all_v83_b_key
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $w0
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   frame-setup EMITBKEY
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; PAUTHLR-MIR-NEXT:   frame-setup PACIBSPPC implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; PAUTHLR-MIR-NEXT:   frame-destroy RETABSPPCi <mcsymbol >, implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp
  ret i32 %x
}

define i32 @leaf_sign_all_a_key_bti(i32 %x) "branch-protection-pauth-lr" "sign-return-address"="all" "sign-return-address-key"="a_key" "branch-target-enforcement" {
  ; COMPAT-MIR-LABEL: name: leaf_sign_all_a_key_bti
  ; COMPAT-MIR: bb.0 (%ir-block.0):
  ; COMPAT-MIR-NEXT:   liveins: $w0
  ; COMPAT-MIR-NEXT: {{  $}}
  ; COMPAT-MIR-NEXT:   frame-setup PACM
  ; COMPAT-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; COMPAT-MIR-NEXT:   frame-setup PACIASP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; COMPAT-MIR-NEXT:   frame-destroy PACM
  ; COMPAT-MIR-NEXT:   frame-destroy AUTIASP implicit-def $lr, implicit $lr, implicit $sp
  ; COMPAT-MIR-NEXT:   RET undef $lr, implicit killed $w0
  ;
  ; V83A-MIR-LABEL: name: leaf_sign_all_a_key_bti
  ; V83A-MIR: bb.0 (%ir-block.0):
  ; V83A-MIR-NEXT:   liveins: $w0
  ; V83A-MIR-NEXT: {{  $}}
  ; V83A-MIR-NEXT:   frame-setup PACM
  ; V83A-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; V83A-MIR-NEXT:   frame-setup PACIASP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; V83A-MIR-NEXT:   frame-destroy PACM
  ; V83A-MIR-NEXT:   frame-destroy RETAA implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp, implicit-def $x16
  ;
  ; PAUTHLR-MIR-LABEL: name: leaf_sign_all_a_key_bti
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $w0
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; PAUTHLR-MIR-NEXT:   frame-setup PACIASPPC implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; PAUTHLR-MIR-NEXT:   frame-destroy RETAASPPCi <mcsymbol >, implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp
  ret i32 %x
}

define i32 @leaf_sign_all_b_key_bti(i32 %x) "branch-protection-pauth-lr" "sign-return-address"="all" "sign-return-address-key"="b_key" "branch-target-enforcement" {
  ; COMPAT-MIR-LABEL: name: leaf_sign_all_b_key_bti
  ; COMPAT-MIR: bb.0 (%ir-block.0):
  ; COMPAT-MIR-NEXT:   liveins: $w0
  ; COMPAT-MIR-NEXT: {{  $}}
  ; COMPAT-MIR-NEXT:   frame-setup EMITBKEY
  ; COMPAT-MIR-NEXT:   frame-setup PACM
  ; COMPAT-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; COMPAT-MIR-NEXT:   frame-setup PACIBSP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; COMPAT-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; COMPAT-MIR-NEXT:   frame-destroy PACM
  ; COMPAT-MIR-NEXT:   frame-destroy AUTIBSP implicit-def $lr, implicit $lr, implicit $sp
  ; COMPAT-MIR-NEXT:   RET undef $lr, implicit killed $w0
  ;
  ; V83A-MIR-LABEL: name: leaf_sign_all_b_key_bti
  ; V83A-MIR: bb.0 (%ir-block.0):
  ; V83A-MIR-NEXT:   liveins: $w0
  ; V83A-MIR-NEXT: {{  $}}
  ; V83A-MIR-NEXT:   frame-setup EMITBKEY
  ; V83A-MIR-NEXT:   frame-setup PACM
  ; V83A-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; V83A-MIR-NEXT:   frame-setup PACIBSP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; V83A-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; V83A-MIR-NEXT:   frame-destroy PACM
  ; V83A-MIR-NEXT:   frame-destroy RETAB implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp, implicit-def $x16
  ;
  ; PAUTHLR-MIR-LABEL: name: leaf_sign_all_b_key_bti
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $w0
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   frame-setup EMITBKEY
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; PAUTHLR-MIR-NEXT:   frame-setup PACIBSPPC implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; PAUTHLR-MIR-NEXT:   frame-destroy RETABSPPCi <mcsymbol >, implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp
  ret i32 %x
}

define i32 @leaf_sign_all_v83_b_key_bti(i32 %x) "branch-protection-pauth-lr" "sign-return-address"="all" "target-features"="+v8.3a" "sign-return-address-key"="b_key" "branch-target-enforcement" {
  ; CHECK-MIR-LABEL: name: leaf_sign_all_v83_b_key_bti
  ; CHECK-MIR: bb.0 (%ir-block.0):
  ; CHECK-MIR-NEXT:   liveins: $w0
  ; CHECK-MIR-NEXT: {{  $}}
  ; CHECK-MIR-NEXT:   frame-setup EMITBKEY
  ; CHECK-MIR-NEXT:   frame-setup PACM
  ; CHECK-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; CHECK-MIR-NEXT:   frame-setup PACIBSP implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; CHECK-MIR-NEXT:   $x16 = frame-destroy ADRP target-flags(aarch64-page) <mcsymbol >
  ; CHECK-MIR-NEXT:   $x16 = frame-destroy ADDXri $x16, target-flags(aarch64-pageoff, aarch64-nc) <mcsymbol >, 0
  ; CHECK-MIR-NEXT:   frame-destroy PACM
  ; CHECK-MIR-NEXT:   frame-destroy RETAB implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp, implicit-def $x16
  ;
  ; PAUTHLR-MIR-LABEL: name: leaf_sign_all_v83_b_key_bti
  ; PAUTHLR-MIR: bb.0 (%ir-block.0):
  ; PAUTHLR-MIR-NEXT:   liveins: $w0
  ; PAUTHLR-MIR-NEXT: {{  $}}
  ; PAUTHLR-MIR-NEXT:   frame-setup EMITBKEY
  ; PAUTHLR-MIR-NEXT:   frame-setup CFI_INSTRUCTION negate_ra_sign_state_with_pc
  ; PAUTHLR-MIR-NEXT:   frame-setup PACIBSPPC implicit-def $lr, implicit $lr, implicit $sp, pre-instr-symbol <mcsymbol >
  ; PAUTHLR-MIR-NEXT:   frame-destroy RETABSPPCi <mcsymbol >, implicit $lr, implicit $sp, implicit-def $lr, implicit killed $lr, implicit $sp
  ret i32 %x
}
