; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=aarch64-linux-gnu | FileCheck %s

define i1 @ord_nnan(float nofpclass(nan) %a, float nofpclass(nan) %b) nounwind {
; CHECK-LABEL: ord_nnan:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov w0, #1 // =0x1
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp ord float %a, %b
  ret i1 %cmp
}

define <4 x i1> @ord_nnan_v4(<4 x float> nofpclass(nan) %a, <4 x float> nofpclass(nan) %b) nounwind {
; CHECK-LABEL: ord_nnan_v4:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    movi v0.2d, #0xffffffffffffffff
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp ord <4 x float> %a, %b
  ret <4 x i1> %cmp
}


define i1 @uno_nnan(float nofpclass(nan) %a, float nofpclass(nan) %b) nounwind {
; CHECK-LABEL: uno_nnan:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp uno float %a, %b
  ret i1 %cmp
}

define <4 x i1> @uno_nnan_v4(<4 x float> nofpclass(nan) %a, <4 x float> nofpclass(nan) %b) nounwind {
; CHECK-LABEL: uno_nnan_v4:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    movi v0.2d, #0000000000000000
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp uno <4 x float> %a, %b
  ret <4 x i1> %cmp
}


