; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=aarch64-linux -O2 | FileCheck %s --check-prefixes=NOCSSC
; RUN: llc < %s -mtriple=aarch64-linux -O2 -mattr=+cssc | FileCheck %s --check-prefixes=CSSC
;
; Verify smax(X,-1) and smin(X,0) fold to shifted bitwise forms on AArch64
; without CSSC (1 shifted ORR/AND), and use native instructions with CSSC.
; LLVM issue #206153.

define i32 @smax_allones_i32(i32 %x) {
; NOCSSC-LABEL: smax_allones_i32:
; NOCSSC:       // %bb.0:
; NOCSSC-NEXT:    orr w0, w0, w0, asr #31
; NOCSSC-NEXT:    ret
;
; CSSC-LABEL: smax_allones_i32:
; CSSC:       // %bb.0:
; CSSC-NEXT:    smax w0, w0, #-1
; CSSC-NEXT:    ret
  %r = call i32 @llvm.smax.i32(i32 %x, i32 -1)
  ret i32 %r
}

define i64 @smax_allones_i64(i64 %x) {
; NOCSSC-LABEL: smax_allones_i64:
; NOCSSC:       // %bb.0:
; NOCSSC-NEXT:    orr x0, x0, x0, asr #63
; NOCSSC-NEXT:    ret
;
; CSSC-LABEL: smax_allones_i64:
; CSSC:       // %bb.0:
; CSSC-NEXT:    smax x0, x0, #-1
; CSSC-NEXT:    ret
  %r = call i64 @llvm.smax.i64(i64 %x, i64 -1)
  ret i64 %r
}

define i32 @smin_zero_i32(i32 %x) {
; NOCSSC-LABEL: smin_zero_i32:
; NOCSSC:       // %bb.0:
; NOCSSC-NEXT:    and w0, w0, w0, asr #31
; NOCSSC-NEXT:    ret
;
; CSSC-LABEL: smin_zero_i32:
; CSSC:       // %bb.0:
; CSSC-NEXT:    smin w0, w0, #0
; CSSC-NEXT:    ret
  %r = call i32 @llvm.smin.i32(i32 %x, i32 0)
  ret i32 %r
}

define i64 @smin_zero_i64(i64 %x) {
; NOCSSC-LABEL: smin_zero_i64:
; NOCSSC:       // %bb.0:
; NOCSSC-NEXT:    and x0, x0, x0, asr #63
; NOCSSC-NEXT:    ret
;
; CSSC-LABEL: smin_zero_i64:
; CSSC:       // %bb.0:
; CSSC-NEXT:    smin x0, x0, #0
; CSSC-NEXT:    ret
  %r = call i64 @llvm.smin.i64(i64 %x, i64 0)
  ret i64 %r
}
