; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=aarch64-windows-msvc -aarch64-streaming-hazard-size=0 -mattr=+sve,+sme < %s | FileCheck %s

declare void @private_za_callee()
declare void @shared_za_callee() "aarch64_inout_za"

define void @test_lazy_save() nounwind "aarch64_inout_za" {
; CHECK-LABEL: test_lazy_save:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x19, [sp, #-32]! // 8-byte Folded Spill
; CHECK-NEXT:    stp x29, x30, [sp, #8] // 16-byte Folded Spill
; CHECK-NEXT:    add x29, sp, #8
; CHECK-NEXT:    sub sp, sp, #16
; CHECK-NEXT:    rdsvl x8, #1
; CHECK-NEXT:    mul x9, x8, x8
; CHECK-NEXT:    lsr x15, x9, #4
; CHECK-NEXT:    bl __chkstk
; CHECK-NEXT:    lsl x9, x15, #4
; CHECK-NEXT:    sub x9, sp, x9
; CHECK-NEXT:    mov sp, x9
; CHECK-NEXT:    sub x10, x29, #24
; CHECK-NEXT:    stp x9, x8, [x29, #-24]
; CHECK-NEXT:    msr TPIDR2_EL0, x10
; CHECK-NEXT:    bl private_za_callee
; CHECK-NEXT:    smstart za
; CHECK-NEXT:    mrs x8, TPIDR2_EL0
; CHECK-NEXT:    sub x0, x29, #24
; CHECK-NEXT:    cbnz x8, .LBB0_2
; CHECK-NEXT:  // %bb.1:
; CHECK-NEXT:    bl __arm_tpidr2_restore
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    msr TPIDR2_EL0, xzr
; CHECK-NEXT:    sub sp, x29, #8
; CHECK-NEXT:    ldp x29, x30, [sp, #8] // 16-byte Folded Reload
; CHECK-NEXT:    ldr x19, [sp], #32 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  call void @private_za_callee()
  ret void
}
