; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=aarch64-unknown-linux -O3 | FileCheck %s

define <8 x i8> @manual_sminp_v8i8(<8 x i8> %a, <8 x i8> %b) {
; CHECK-LABEL: manual_sminp_v8i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sminp v0.8b, v0.8b, v1.8b
; CHECK-NEXT:    ret
  %e = shufflevector <8 x i8> %a, <8 x i8> %b, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %o = shufflevector <8 x i8> %a, <8 x i8> %b, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %r = call <8 x i8> @llvm.smin.v8i8(<8 x i8> %e, <8 x i8> %o)
  ret <8 x i8> %r
}

define <16 x i8> @manual_sminp_v16i8(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: manual_sminp_v16i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sminp v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    ret
  %e = shufflevector <16 x i8> %a, <16 x i8> %b, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
  %o = shufflevector <16 x i8> %a, <16 x i8> %b, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>
  %r = call <16 x i8> @llvm.smin.v16i8(<16 x i8> %e, <16 x i8> %o)
  ret <16 x i8> %r
}

define <4 x i16> @manual_sminp_v4i16(<4 x i16> %a, <4 x i16> %b) {
; CHECK-LABEL: manual_sminp_v4i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sminp v0.4h, v0.4h, v1.4h
; CHECK-NEXT:    ret
  %e = shufflevector <4 x i16> %a, <4 x i16> %b, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %o = shufflevector <4 x i16> %a, <4 x i16> %b, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %r = call <4 x i16> @llvm.smin.v4i16(<4 x i16> %e, <4 x i16> %o)
  ret <4 x i16> %r
}

define <8 x i16> @manual_sminp_v8i16(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: manual_sminp_v8i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sminp v0.8h, v0.8h, v1.8h
; CHECK-NEXT:    ret
  %e = shufflevector <8 x i16> %a, <8 x i16> %b, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %o = shufflevector <8 x i16> %a, <8 x i16> %b, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %r = call <8 x i16> @llvm.smin.v8i16(<8 x i16> %e, <8 x i16> %o)
  ret <8 x i16> %r
}

define <2 x i32> @manual_sminp_v2i32(<2 x i32> %a, <2 x i32> %b) {
; CHECK-LABEL: manual_sminp_v2i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sminp v0.2s, v0.2s, v1.2s
; CHECK-NEXT:    ret
  %e = shufflevector <2 x i32> %a, <2 x i32> %b, <2 x i32> <i32 0, i32 2>
  %o = shufflevector <2 x i32> %a, <2 x i32> %b, <2 x i32> <i32 1, i32 3>
  %r = call <2 x i32> @llvm.smin.v2i32(<2 x i32> %e, <2 x i32> %o)
  ret <2 x i32> %r
}

define <4 x i32> @manual_sminp_v4i32(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: manual_sminp_v4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sminp v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
  %e = shufflevector <4 x i32> %a, <4 x i32> %b, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %o = shufflevector <4 x i32> %a, <4 x i32> %b, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %r = call <4 x i32> @llvm.smin.v4i32(<4 x i32> %e, <4 x i32> %o)
  ret <4 x i32> %r
}

define <8 x i8> @manual_smaxp_v8i8(<8 x i8> %a, <8 x i8> %b) {
; CHECK-LABEL: manual_smaxp_v8i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    smaxp v0.8b, v0.8b, v1.8b
; CHECK-NEXT:    ret
  %e = shufflevector <8 x i8> %a, <8 x i8> %b, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %o = shufflevector <8 x i8> %a, <8 x i8> %b, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %r = call <8 x i8> @llvm.smax.v8i8(<8 x i8> %e, <8 x i8> %o)
  ret <8 x i8> %r
}

define <16 x i8> @manual_smaxp_v16i8(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: manual_smaxp_v16i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    smaxp v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    ret
  %e = shufflevector <16 x i8> %a, <16 x i8> %b, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
  %o = shufflevector <16 x i8> %a, <16 x i8> %b, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>
  %r = call <16 x i8> @llvm.smax.v16i8(<16 x i8> %e, <16 x i8> %o)
  ret <16 x i8> %r
}

define <4 x i16> @manual_smaxp_v4i16(<4 x i16> %a, <4 x i16> %b) {
; CHECK-LABEL: manual_smaxp_v4i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    smaxp v0.4h, v0.4h, v1.4h
; CHECK-NEXT:    ret
  %e = shufflevector <4 x i16> %a, <4 x i16> %b, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %o = shufflevector <4 x i16> %a, <4 x i16> %b, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %r = call <4 x i16> @llvm.smax.v4i16(<4 x i16> %e, <4 x i16> %o)
  ret <4 x i16> %r
}

define <8 x i16> @manual_smaxp_v8i16(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: manual_smaxp_v8i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    smaxp v0.8h, v0.8h, v1.8h
; CHECK-NEXT:    ret
  %e = shufflevector <8 x i16> %a, <8 x i16> %b, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %o = shufflevector <8 x i16> %a, <8 x i16> %b, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %r = call <8 x i16> @llvm.smax.v8i16(<8 x i16> %e, <8 x i16> %o)
  ret <8 x i16> %r
}

define <2 x i32> @manual_smaxp_v2i32(<2 x i32> %a, <2 x i32> %b) {
; CHECK-LABEL: manual_smaxp_v2i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    smaxp v0.2s, v0.2s, v1.2s
; CHECK-NEXT:    ret
  %e = shufflevector <2 x i32> %a, <2 x i32> %b, <2 x i32> <i32 0, i32 2>
  %o = shufflevector <2 x i32> %a, <2 x i32> %b, <2 x i32> <i32 1, i32 3>
  %r = call <2 x i32> @llvm.smax.v2i32(<2 x i32> %e, <2 x i32> %o)
  ret <2 x i32> %r
}

define <4 x i32> @manual_smaxp_v4i32(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: manual_smaxp_v4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    smaxp v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
  %e = shufflevector <4 x i32> %a, <4 x i32> %b, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %o = shufflevector <4 x i32> %a, <4 x i32> %b, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %r = call <4 x i32> @llvm.smax.v4i32(<4 x i32> %e, <4 x i32> %o)
  ret <4 x i32> %r
}

declare <8 x i8> @llvm.smin.v8i8(<8 x i8>, <8 x i8>)
declare <16 x i8> @llvm.smin.v16i8(<16 x i8>, <16 x i8>)
declare <4 x i16> @llvm.smin.v4i16(<4 x i16>, <4 x i16>)
declare <8 x i16> @llvm.smin.v8i16(<8 x i16>, <8 x i16>)
declare <2 x i32> @llvm.smin.v2i32(<2 x i32>, <2 x i32>)
declare <4 x i32> @llvm.smin.v4i32(<4 x i32>, <4 x i32>)

declare <8 x i8> @llvm.smax.v8i8(<8 x i8>, <8 x i8>)
declare <16 x i8> @llvm.smax.v16i8(<16 x i8>, <16 x i8>)
declare <4 x i16> @llvm.smax.v4i16(<4 x i16>, <4 x i16>)
declare <8 x i16> @llvm.smax.v8i16(<8 x i16>, <8 x i16>)
declare <2 x i32> @llvm.smax.v2i32(<2 x i32>, <2 x i32>)
declare <4 x i32> @llvm.smax.v4i32(<4 x i32>, <4 x i32>)
