; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -mattr=+sve < %s | FileCheck %s

; Test that @llvm.speculative.load is lowered to a regular load
; in SelectionDAG for fixed vectors, scalable vectors, and bytes.

; Byte-type tests

define b128 @speculative_load_b128(ptr %ptr) {
; CHECK-LABEL: speculative_load_b128:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldp x8, x1, [x0]
; CHECK-NEXT:    mov x0, x8
; CHECK-NEXT:    ret
  %load = call b128 (ptr, i1, ...) @llvm.speculative.load.b128.p0(ptr align 16 %ptr, i1 false, i64 12)
  ret b128 %load
}

define b64 @speculative_load_b64(ptr %ptr) {
; CHECK-LABEL: speculative_load_b64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldr x0, [x0]
; CHECK-NEXT:    ret
  %load = call b64 (ptr, i1, ...) @llvm.speculative.load.b64.p0(ptr align 8 %ptr, i1 false, i64 8)
  ret b64 %load
}

; Fixed-vector tests

define <4 x i32> @speculative_load_v4i32(ptr %ptr) {
; CHECK-LABEL: speculative_load_v4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldr q0, [x0]
; CHECK-NEXT:    ret
  %load = call <4 x i32> (ptr, i1, ...) @llvm.speculative.load.v4i32.p0(ptr align 16 %ptr, i1 false, i64 12)
  ret <4 x i32> %load
}

define <2 x double> @speculative_load_v2f64(ptr %ptr) {
; CHECK-LABEL: speculative_load_v2f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldr q0, [x0]
; CHECK-NEXT:    ret
  %load = call <2 x double> (ptr, i1, ...) @llvm.speculative.load.v2f64.p0(ptr align 16 %ptr, i1 false, i64 8)
  ret <2 x double> %load
}

; Scalable vector tests

define <vscale x 4 x i32> @speculative_load_nxv4i32(ptr %ptr) {
; CHECK-LABEL: speculative_load_nxv4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldr z0, [x0]
; CHECK-NEXT:    ret
  %load = call <vscale x 4 x i32> (ptr, i1, ...) @llvm.speculative.load.nxv4i32.p0(ptr align 16 %ptr, i1 false, i64 8)
  ret <vscale x 4 x i32> %load
}

define <vscale x 2 x double> @speculative_load_nxv2f64(ptr %ptr) {
; CHECK-LABEL: speculative_load_nxv2f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldr z0, [x0]
; CHECK-NEXT:    ret
  %load = call <vscale x 2 x double> (ptr, i1, ...) @llvm.speculative.load.nxv2f64.p0(ptr align 16 %ptr, i1 false, i64 4)
  ret <vscale x 2 x double> %load
}

; Oracle form tests

declare i64 @oracle(ptr, i64) memory(argmem: read)

define b128 @speculative_load_b128_oracle(ptr %ptr, i64 %n) {
; CHECK-LABEL: speculative_load_b128_oracle:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldp x8, x1, [x0]
; CHECK-NEXT:    mov x0, x8
; CHECK-NEXT:    ret
  %load = call b128 (ptr, i1, ...) @llvm.speculative.load.b128.p0(ptr align 16 %ptr, i1 false, ptr @oracle, ptr %ptr, i64 %n)
  ret b128 %load
}

define <4 x i32> @speculative_load_v4i32_oracle(ptr %ptr, i64 %n) {
; CHECK-LABEL: speculative_load_v4i32_oracle:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldr q0, [x0]
; CHECK-NEXT:    ret
  %load = call <4 x i32> (ptr, i1, ...) @llvm.speculative.load.v4i32.p0(ptr align 16 %ptr, i1 false, ptr @oracle, ptr %ptr, i64 %n)
  ret <4 x i32> %load
}

define <vscale x 4 x i32> @speculative_load_nxv4i32_oracle(ptr %ptr, i64 %n) {
; CHECK-LABEL: speculative_load_nxv4i32_oracle:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldr z0, [x0]
; CHECK-NEXT:    ret
  %load = call <vscale x 4 x i32> (ptr, i1, ...) @llvm.speculative.load.nxv4i32.p0(ptr align 16 %ptr, i1 false, ptr @oracle, ptr %ptr, i64 %n)
  ret <vscale x 4 x i32> %load
}

; from_end tests

define b128 @speculative_load_b128_from_end(ptr %ptr) {
; CHECK-LABEL: speculative_load_b128_from_end:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldp x8, x1, [x0]
; CHECK-NEXT:    mov x0, x8
; CHECK-NEXT:    ret
  %load = call b128 (ptr, i1, ...) @llvm.speculative.load.b128.p0(ptr align 16 %ptr, i1 true, i64 12)
  ret b128 %load
}

define <4 x i32> @speculative_load_v4i32_from_end(ptr %ptr) {
; CHECK-LABEL: speculative_load_v4i32_from_end:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldr q0, [x0]
; CHECK-NEXT:    ret
  %load = call <4 x i32> (ptr, i1, ...) @llvm.speculative.load.v4i32.p0(ptr align 16 %ptr, i1 true, i64 12)
  ret <4 x i32> %load
}

define <vscale x 4 x i32> @speculative_load_nxv4i32_from_end(ptr %ptr) {
; CHECK-LABEL: speculative_load_nxv4i32_from_end:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldr z0, [x0]
; CHECK-NEXT:    ret
  %load = call <vscale x 4 x i32> (ptr, i1, ...) @llvm.speculative.load.nxv4i32.p0(ptr align 16 %ptr, i1 true, i64 8)
  ret <vscale x 4 x i32> %load
}

define b128 @speculative_load_b128_oracle_from_end(ptr %ptr, i64 %n) {
; CHECK-LABEL: speculative_load_b128_oracle_from_end:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldp x8, x1, [x0]
; CHECK-NEXT:    mov x0, x8
; CHECK-NEXT:    ret
  %load = call b128 (ptr, i1, ...) @llvm.speculative.load.b128.p0(ptr align 16 %ptr, i1 true, ptr @oracle, ptr %ptr, i64 %n)
  ret b128 %load
}

define <vscale x 4 x i32> @speculative_load_nxv4i32_oracle_from_end(ptr %ptr, i64 %n) {
; CHECK-LABEL: speculative_load_nxv4i32_oracle_from_end:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldr z0, [x0]
; CHECK-NEXT:    ret
  %load = call <vscale x 4 x i32> (ptr, i1, ...) @llvm.speculative.load.nxv4i32.p0(ptr align 16 %ptr, i1 true, ptr @oracle, ptr %ptr, i64 %n)
  ret <vscale x 4 x i32> %load
}
