; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=aarch64 -mcpu=cortex-a57 2>&1 | FileCheck %s



define i64 @read_encoded_register() nounwind {
; CHECK-LABEL: read_encoded_register:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mrs x0, S3_2_C3_C4_5
; CHECK-NEXT:    ret
entry:
  %reg = call i64 @llvm.read_register.i64(metadata !0)
  ret i64 %reg
}

define i64 @read_daif() nounwind {
; CHECK-LABEL: read_daif:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mrs x0, DAIF
; CHECK-NEXT:    ret
entry:
  %reg = call i64 @llvm.read_register.i64(metadata !1)
  ret i64 %reg
}

define void @write_encoded_register(i64 %x) nounwind {
; CHECK-LABEL: write_encoded_register:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    msr S3_2_C3_C4_5, x0
; CHECK-NEXT:    ret
entry:
  call void @llvm.write_register.i64(metadata !0, i64 %x)
  ret void
}

define void @write_daif(i64 %x) nounwind {
; CHECK-LABEL: write_daif:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    msr DAIF, x0
; CHECK-NEXT:    ret
entry:
  call void @llvm.write_register.i64(metadata !1, i64 %x)
  ret void
}

define void @write_daifset() nounwind {
; CHECK-LABEL: write_daifset:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    msr DAIFSet, #2
; CHECK-NEXT:    ret
entry:
  call void @llvm.write_register.i64(metadata !2, i64 2)
  ret void
}

declare i64 @llvm.read_register.i64(metadata) nounwind
declare void @llvm.write_register.i64(metadata, i64) nounwind

!0 = !{!"3:2:3:4:5"}
!1 = !{!"daif"}
!2 = !{!"daifset"}
