# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=aarch64 -mattr=+mte -run-pass=prologepilog %s -o - | FileCheck %s

--- |
  target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
  target triple = "aarch64-arm-none-eabi"

  define void @F76(i32 %0, ...) #0 {
    ret void
  }

...
---
name:            F76
fixedStack:
  - { id: 0, type: default, offset: 0, size: 4, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 4080, alignment: 16,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      local-offset: -4080, debug-info-variable: '', debug-info-expression: '',
      debug-info-location: '' }
  - { id: 1, name: '', type: default, offset: 0, size: 32, alignment: 16,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      local-offset: -4112, debug-info-variable: '', debug-info-expression: '',
      debug-info-location: '' }
  - { id: 2, name: '', type: default, offset: 0, size: 3888, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      local-offset: -8000, debug-info-variable: '', debug-info-expression: '',
      debug-info-location: '' }
  - { id: 3, name: '', type: default, offset: 0, size: 56, alignment: 8,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      local-offset: -8056, debug-info-variable: '', debug-info-expression: '',
      debug-info-location: '' }
  - { id: 4, name: '', type: default, offset: 0, size: 128, alignment: 16,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      local-offset: -8192, debug-info-variable: '', debug-info-expression: '',
      debug-info-location: '' }
body:             |
  bb.0 (%ir-block.1):
    liveins: $q0, $q1, $q2, $q3, $q4, $q5, $q6, $q7, $x1, $x2, $x3, $x4, $x5, $x6, $x7

    ; CHECK-LABEL: name: F76
    ; CHECK: liveins: $q0, $q1, $q2, $q3, $q4, $q5, $q6, $q7, $x1, $x2, $x3, $x4, $x5, $x6, $x7, $fp
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: early-clobber $sp = frame-setup STRXpre killed $fp, $sp, -16 :: (store (s64) into %stack.5)
    ; CHECK-NEXT: $sp = frame-setup SUBXri $sp, 2, 12
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION def_cfa_offset 8208
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION offset $w29, -16
    ; CHECK-NEXT: renamable $x8 = IRGstack $sp, $xzr
    ; CHECK-NEXT: renamable $x9 = TAGPstack $x8, 2, renamable $x8, 1
    ; CHECK-NEXT: renamable $x10 = COPY renamable $x9
    ; CHECK-NEXT: dead early-clobber renamable $x11, dead early-clobber renamable $x10 = STGloop_wback 4080, killed renamable $x10, implicit-def dead $nzcv
    ; CHECK-NEXT: ST2Gi renamable $x8, renamable $x8, 0
    ; CHECK-NEXT: dead early-clobber $x8, early-clobber $sp = frame-destroy STGloop_wback 4096, $sp, implicit-def $nzcv
    ; CHECK-NEXT: $sp = frame-destroy STGPostIndex $sp, $sp, 256
    ; CHECK-NEXT: early-clobber $sp, $fp = frame-destroy LDRXpost $sp, 16 :: (load (s64) from %stack.5)
    ; CHECK-NEXT: RET_ReallyLR
    /* Prologue */
    renamable $x8 = IRGstack $sp, $xzr
    renamable $x9 = TAGPstack %stack.0, 0, renamable $x8, 1
    renamable $x10 = COPY renamable $x9
    dead early-clobber renamable $x11, dead early-clobber renamable $x10 = STGloop_wback 4080, killed renamable $x10, implicit-def dead $nzcv
    ST2Gi renamable $x8, renamable $x8, 0

    /* Epilogue */
    dead early-clobber renamable $x8, dead early-clobber renamable $x9 = STGloop 4080, %stack.0, implicit-def dead $nzcv
    ST2Gi $sp, %stack.1, 0
    RET_ReallyLR
...
