# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=aarch64 -run-pass aarch64-ldst-opt %s -o - | FileCheck %s

---
name:            StrHazards
tracksRegLiveness: true
liveins:
  - { reg: '$x0', virtual-reg: '' }
body:             |
  bb.0.entry:
    liveins: $x0

    ; This test demonstrates a hazard where x8 is both the index and the value being stored.
    ; The optimization converts:
    ;   mov x8, #LargeImm
    ;   str x8, [x0, x8]
    ; into:
    ;   add x8, x0, #LargeBase
    ;   str x8, [x8, #SmallImm]
    ; When this happens, the STR stores the *modified* x8 (address) instead of the original value.

    ; CHECK-LABEL: name: StrHazards
    ; CHECK: liveins: $x0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $w8 = MOVZWi 56952, 0
    ; CHECK-NEXT: renamable $w8 = MOVKWi $w8, 15, 16, implicit-def $x8
    ; CHECK-NEXT: STRXroX killed renamable $x8, killed renamable $x0, renamable $x8, 0, 0
    ; CHECK-NEXT: RET undef $lr
    renamable $w8 = MOVZWi 56952, 0
    renamable $w8 = MOVKWi $w8, 15, 16, implicit-def $x8
    STRXroX killed renamable $x8, killed renamable $x0, renamable $x8, 0, 0
    RET undef $lr
...
---
name:            StrValid
tracksRegLiveness: true
liveins:
  - { reg: '$x0', virtual-reg: '' }
  - { reg: '$x1', virtual-reg: '' }
body:             |
  bb.0.entry:
    liveins: $x0, $x1

    ; This is a valid case that SHOULD be optimized.

    ; CHECK-LABEL: name: StrValid
    ; CHECK: liveins: $x0, $x1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $w8 = MOVZWi 56952, 0
    ; CHECK-NEXT: renamable $w8 = MOVKWi $w8, 15, 16, implicit-def $x8
    ; CHECK-NEXT: STRXroX killed renamable $x1, killed renamable $x0, killed renamable $x8, 0, 0
    ; CHECK-NEXT: RET undef $lr
    renamable $w8 = MOVZWi 56952, 0
    renamable $w8 = MOVKWi $w8, 15, 16, implicit-def $x8
    STRXroX killed renamable $x1, killed renamable $x0, killed renamable $x8, 0, 0
    RET undef $lr
...
