; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64-linux-gnu    | FileCheck %s
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64_be-linux-gnu | FileCheck %s
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64-linux-gnu    -mcpu=exynos-m3 | FileCheck %s
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64_be-linux-gnu -mcpu=exynos-m3 | FileCheck %s

define void @test_split_f(<4 x float> %val, ptr %addr) {
; CHECK-LABEL: test_split_f:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str q0, [x0]
; CHECK-NEXT:    ret
  store <4 x float> %val, ptr %addr, align 8
  ret void
}

define void @test_split_d(<2 x double> %val, ptr %addr) {
; CHECK-LABEL: test_split_d:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str q0, [x0]
; CHECK-NEXT:    ret
  store <2 x double> %val, ptr %addr, align 8
  ret void
}

define void @test_split_128(fp128 %val, ptr %addr) {
; CHECK-LABEL: test_split_128:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str q0, [x0]
; CHECK-NEXT:    ret
  store fp128 %val, ptr %addr, align 8
  ret void
}
