; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -debugify-and-strip-all-safe -enable-machine-outliner=never -verify-machineinstrs %s -o - -mtriple=aarch64-linux-gnu -aarch64-enable-atomic-cfg-tidy=0 | FileCheck %s

define i4 @sub_fixedwidth_i4(i4 %a0, i4 %a1)  {
; CHECK-LABEL: sub_fixedwidth_i4:
; CHECK:       // %bb.0:
; CHECK-NEXT:    eor w8, w0, w1
; CHECK-NEXT:    orr w9, w0, w1
; CHECK-NEXT:    and w8, w8, #0xe
; CHECK-NEXT:    sub w0, w9, w8, lsr #1
; CHECK-NEXT:    ret
  %or = or i4 %a0, %a1
  %xor = xor i4 %a0, %a1
  %srl = lshr i4 %xor, 1
  %res = sub i4 %or, %srl
  ret i4 %res
}

define <4 x i32> @sub_fixedwidth_v4i32(<4 x i32> %a0, <4 x i32> %a1)  {
; CHECK-LABEL: sub_fixedwidth_v4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    eor v2.16b, v0.16b, v1.16b
; CHECK-NEXT:    orr v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    ushr v1.4s, v2.4s, #1
; CHECK-NEXT:    sub v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
  %or = or <4 x i32> %a0, %a1
  %xor = xor <4 x i32> %a0, %a1
  %srl = lshr <4 x i32> %xor, <i32 1,i32 1,i32 1,i32 1>
  %res = sub <4 x i32> %or, %srl
  ret <4 x i32> %res
}


