# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=aarch64 -O3 -start-before=register-coalescer -stop-before=aarch64-expand-pseudo -enable-subreg-liveness=true  -o - %s | FileCheck %s --check-prefix=SRLT
# RUN: llc -mtriple=aarch64 -O3 -start-before=register-coalescer -stop-before=aarch64-expand-pseudo -enable-subreg-liveness=false -o - %s | FileCheck %s --check-prefix=NOSRLT

# Test that the ORRWrr is not copy-propagated away,
# because the ORRWrr exists to zero the top bits of x1.
---
name: dont_remove_orr_w
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $x1
    ; SRLT-LABEL: name: dont_remove_orr_w
    ; SRLT: liveins: $x1
    ; SRLT-NEXT: {{  $}}
    ; SRLT-NEXT: $x0 = ORRXrr $xzr, $x1
    ; SRLT-NEXT: renamable $w1 = ORRWrr $wzr, renamable $w0, implicit-def renamable $x1
    ; SRLT-NEXT: RET_ReallyLR implicit $x1, implicit $x0
    ;
    ; NOSRLT-LABEL: name: dont_remove_orr_w
    ; NOSRLT: liveins: $x1
    ; NOSRLT-NEXT: {{  $}}
    ; NOSRLT-NEXT: $x0 = ORRXrr $xzr, $x1
    ; NOSRLT-NEXT: renamable $w1 = ORRWrr $wzr, renamable $w0, implicit-def $x1
    ; NOSRLT-NEXT: RET_ReallyLR implicit $x1, implicit $x0
    %0:gpr64 = COPY killed $x1
    %1:gpr32 = COPY %0.sub_32:gpr64
    %2:gpr32 = ORRWrr $wzr, killed %1:gpr32
    %3:gpr64all = SUBREG_TO_REG 0, killed %2:gpr32, %subreg.sub_32
    $x0 = COPY killed %0:gpr64
    $x1 = COPY killed %3:gpr64all
    RET_ReallyLR implicit $x1, implicit $x0
...
