; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=+sve2p1 -aarch64-enable-subreg-liveness-tracking < %s -verify-machineinstrs | FileCheck %s --check-prefix=SVE2p1
; RUN: llc -mattr=+sme2 --force-streaming < %s -verify-machineinstrs | FileCheck %s --check-prefix=SME2

target triple = "aarch64-unknown-linux-gnu"

define <vscale x 16 x float> @ld1_x4_f32_alloca() {
; SVE2p1-LABEL: ld1_x4_f32_alloca:
; SVE2p1:       // %bb.0:
; SVE2p1-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; SVE2p1-NEXT:    addvl sp, sp, #-1
; SVE2p1-NEXT:    str p8, [sp, #7, mul vl] // 2-byte Spill
; SVE2p1-NEXT:    addvl sp, sp, #-4
; SVE2p1-NEXT:    .cfi_escape 0x0f, 0x09, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x11, 0x28, 0x1e, 0x22 // sp + 16 + 40 * VG
; SVE2p1-NEXT:    .cfi_offset w29, -16
; SVE2p1-NEXT:    ptrue pn8.s
; SVE2p1-NEXT:    ld1w { z0.s - z3.s }, pn8/z, [sp]
; SVE2p1-NEXT:    addvl sp, sp, #4
; SVE2p1-NEXT:    ldr p8, [sp, #7, mul vl] // 2-byte Reload
; SVE2p1-NEXT:    addvl sp, sp, #1
; SVE2p1-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; SVE2p1-NEXT:    ret
;
; SME2-LABEL: ld1_x4_f32_alloca:
; SME2:       // %bb.0:
; SME2-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; SME2-NEXT:    addvl sp, sp, #-1
; SME2-NEXT:    str p8, [sp, #7, mul vl] // 2-byte Spill
; SME2-NEXT:    addvl sp, sp, #-4
; SME2-NEXT:    .cfi_escape 0x0f, 0x09, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x11, 0x28, 0x1e, 0x22 // sp + 16 + 40 * VG
; SME2-NEXT:    .cfi_offset w29, -16
; SME2-NEXT:    ptrue pn8.s
; SME2-NEXT:    ld1w { z0.s - z3.s }, pn8/z, [sp]
; SME2-NEXT:    addvl sp, sp, #4
; SME2-NEXT:    ldr p8, [sp, #7, mul vl] // 2-byte Reload
; SME2-NEXT:    addvl sp, sp, #1
; SME2-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; SME2-NEXT:    ret
  %a = alloca <vscale x 16 x float>, align 16
  %v = load <vscale x 16 x float>, ptr %a, align 16
  ret <vscale x 16 x float> %v
}

define <vscale x 8 x float> @ld1_x2_f32_alloca() {
; SVE2p1-LABEL: ld1_x2_f32_alloca:
; SVE2p1:       // %bb.0:
; SVE2p1-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; SVE2p1-NEXT:    addvl sp, sp, #-1
; SVE2p1-NEXT:    str p8, [sp, #7, mul vl] // 2-byte Spill
; SVE2p1-NEXT:    addvl sp, sp, #-2
; SVE2p1-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x48, 0x1e, 0x22 // sp + 16 + 24 * VG
; SVE2p1-NEXT:    .cfi_offset w29, -16
; SVE2p1-NEXT:    ptrue pn8.s
; SVE2p1-NEXT:    ld1w { z0.s, z1.s }, pn8/z, [sp]
; SVE2p1-NEXT:    addvl sp, sp, #2
; SVE2p1-NEXT:    ldr p8, [sp, #7, mul vl] // 2-byte Reload
; SVE2p1-NEXT:    addvl sp, sp, #1
; SVE2p1-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; SVE2p1-NEXT:    ret
;
; SME2-LABEL: ld1_x2_f32_alloca:
; SME2:       // %bb.0:
; SME2-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; SME2-NEXT:    addvl sp, sp, #-1
; SME2-NEXT:    str p8, [sp, #7, mul vl] // 2-byte Spill
; SME2-NEXT:    addvl sp, sp, #-2
; SME2-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x48, 0x1e, 0x22 // sp + 16 + 24 * VG
; SME2-NEXT:    .cfi_offset w29, -16
; SME2-NEXT:    ptrue pn8.s
; SME2-NEXT:    ld1w { z0.s, z1.s }, pn8/z, [sp]
; SME2-NEXT:    addvl sp, sp, #2
; SME2-NEXT:    ldr p8, [sp, #7, mul vl] // 2-byte Reload
; SME2-NEXT:    addvl sp, sp, #1
; SME2-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; SME2-NEXT:    ret
  %a = alloca <vscale x 8 x float>, align 16
  %v = load <vscale x 8 x float>, ptr %a, align 16
  ret <vscale x 8 x float> %v
}
