; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve < %s | FileCheck %s
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sme --force-streaming < %s | FileCheck %s


; From <vscale x 1 x i1> predicates

define <vscale x 2 x i1> @broadcast_pred_i64_from_i128(<vscale x 1 x i1> %a) {
; CHECK-LABEL: broadcast_pred_i64_from_i128:
; CHECK:       // %bb.0:
; CHECK-NEXT:    trn1 p0.d, p0.d, p0.d
; CHECK-NEXT:    ret
  %out = call <vscale x 2 x i1> @llvm.vector.stretch.nxv2i1.nxv1i1(<vscale x 1 x i1> %a)
  ret <vscale x 2 x i1> %out
}

; "Unpack" an i64 predicate to a i128 one before stretching its bits back to a i64 predicate.
define <vscale x 2 x i1> @widen_then_broadcast_pred_i64_from_i64_lo(<vscale x 2 x i1> %a) {
; CHECK-LABEL: widen_then_broadcast_pred_i64_from_i64_lo:
; CHECK:       // %bb.0:
; CHECK-NEXT:    zip1 p0.d, p0.d, p0.d
; CHECK-NEXT:    ret
  %widen = call <vscale x 1 x i1> @llvm.vector.extract.nxv1i1.nxv2i1(<vscale x 2 x i1> %a, i64 0)
  %stretch = call <vscale x 2 x i1> @llvm.vector.stretch.nxv2i1.nxv1i1(<vscale x 1 x i1> %widen)
  ret <vscale x 2 x i1> %stretch
}

define <vscale x 2 x i1> @widen_upper_then_broadcast_pred_i64_from_i64_lo(<vscale x 2 x i1> %a) {
; CHECK-LABEL: widen_upper_then_broadcast_pred_i64_from_i64_lo:
; CHECK:       // %bb.0:
; CHECK-NEXT:    zip2 p0.d, p0.d, p0.d
; CHECK-NEXT:    ret
  %widen = call <vscale x 1 x i1> @llvm.vector.extract.nxv1i1.nxv2i1(<vscale x 2 x i1> %a, i64 1)
  %stretch = call <vscale x 2 x i1> @llvm.vector.stretch.nxv2i1.nxv1i1(<vscale x 1 x i1> %widen)
  ret <vscale x 2 x i1> %stretch
}

define <vscale x 4 x i1> @broadcast_pred_i32_from_i128(<vscale x 1 x i1> %a) {
; CHECK-LABEL: broadcast_pred_i32_from_i128:
; CHECK:       // %bb.0:
; CHECK-NEXT:    trn1 p0.d, p0.d, p0.d
; CHECK-NEXT:    trn1 p0.s, p0.s, p0.s
; CHECK-NEXT:    ret
  %out = call <vscale x 4 x i1> @llvm.vector.stretch.nxv4i1.nxv1i1(<vscale x 1 x i1> %a)
  ret <vscale x 4 x i1> %out
}

define <vscale x 8 x i1> @broadcast_pred_i16_from_i128(<vscale x 1 x i1> %a) {
; CHECK-LABEL: broadcast_pred_i16_from_i128:
; CHECK:       // %bb.0:
; CHECK-NEXT:    trn1 p0.d, p0.d, p0.d
; CHECK-NEXT:    trn1 p0.s, p0.s, p0.s
; CHECK-NEXT:    trn1 p0.h, p0.h, p0.h
; CHECK-NEXT:    ret
  %out = call <vscale x 8 x i1> @llvm.vector.stretch.nxv8i1.nxv1i1(<vscale x 1 x i1> %a)
  ret <vscale x 8 x i1> %out
}

define <vscale x 16 x i1> @broadcast_pred_i8_from_i128(<vscale x 1 x i1> %a) {
; CHECK-LABEL: broadcast_pred_i8_from_i128:
; CHECK:       // %bb.0:
; CHECK-NEXT:    trn1 p0.d, p0.d, p0.d
; CHECK-NEXT:    trn1 p0.s, p0.s, p0.s
; CHECK-NEXT:    trn1 p0.h, p0.h, p0.h
; CHECK-NEXT:    trn1 p0.b, p0.b, p0.b
; CHECK-NEXT:    ret
  %out = call <vscale x 16 x i1> @llvm.vector.stretch.nxv16i1.nxv1i1(<vscale x 1 x i1> %a)
  ret <vscale x 16 x i1> %out
}


; From <vscale x 2 x i1> predicates

define <vscale x 4 x i1> @broadcast_pred_i32_from_i64(<vscale x 2 x i1> %a) {
; CHECK-LABEL: broadcast_pred_i32_from_i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    trn1 p0.s, p0.s, p0.s
; CHECK-NEXT:    ret
  %out = call <vscale x 4 x i1> @llvm.vector.stretch.nxv4i1.nxv2i1(<vscale x 2 x i1> %a)
  ret <vscale x 4 x i1> %out
}

define <vscale x 8 x i1> @broadcast_pred_i16_from_i64(<vscale x 2 x i1> %a) {
; CHECK-LABEL: broadcast_pred_i16_from_i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    trn1 p0.s, p0.s, p0.s
; CHECK-NEXT:    trn1 p0.h, p0.h, p0.h
; CHECK-NEXT:    ret
  %out = call <vscale x 8 x i1> @llvm.vector.stretch.nxv8i1.nxv2i1(<vscale x 2 x i1> %a)
  ret <vscale x 8 x i1> %out
}

define <vscale x 16 x i1> @broadcast_pred_i8_from_i64(<vscale x 2 x i1> %a) {
; CHECK-LABEL: broadcast_pred_i8_from_i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    trn1 p0.s, p0.s, p0.s
; CHECK-NEXT:    trn1 p0.h, p0.h, p0.h
; CHECK-NEXT:    trn1 p0.b, p0.b, p0.b
; CHECK-NEXT:    ret
  %out = call <vscale x 16 x i1> @llvm.vector.stretch.nxv16i1.nxv2i1(<vscale x 2 x i1> %a)
  ret <vscale x 16 x i1> %out
}


; From <vscale x 4 x i1> predicates

define <vscale x 8 x i1> @broadcast_pred_i16_from_i32(<vscale x 4 x i1> %a) {
; CHECK-LABEL: broadcast_pred_i16_from_i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    trn1 p0.h, p0.h, p0.h
; CHECK-NEXT:    ret
  %out = call <vscale x 8 x i1> @llvm.vector.stretch.nxv8i1.nxv4i1(<vscale x 4 x i1> %a)
  ret <vscale x 8 x i1> %out
}

define <vscale x 16 x i1> @broadcast_pred_i8_from_i32(<vscale x 4 x i1> %a) {
; CHECK-LABEL: broadcast_pred_i8_from_i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    trn1 p0.h, p0.h, p0.h
; CHECK-NEXT:    trn1 p0.b, p0.b, p0.b
; CHECK-NEXT:    ret
  %out = call <vscale x 16 x i1> @llvm.vector.stretch.nxv16i1.nxv4i1(<vscale x 4 x i1> %a)
  ret <vscale x 16 x i1> %out
}


; From <vscale x 8 x i1> predicates

define <vscale x 16 x i1> @broadcast_pred_i8_from_i16(<vscale x 8 x i1> %a) {
; CHECK-LABEL: broadcast_pred_i8_from_i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    trn1 p0.b, p0.b, p0.b
; CHECK-NEXT:    ret
  %out = call <vscale x 16 x i1> @llvm.vector.stretch.nxv16i1.nxv8i1(<vscale x 8 x i1> %a)
  ret <vscale x 16 x i1> %out
}
