; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O3 < %s | FileCheck %s

target triple = "aarch64"

define void @zext_nxv8i16_to_nxv8i64_deinterleave_in_loop(ptr %src, ptr %dst, <vscale x 8 x i1> %mask) #0 {
; CHECK-LABEL: zext_nxv8i16_to_nxv8i64_deinterleave_in_loop:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    index z7.d, #0, #4
; CHECK-NEXT:    mov z4.d, #0xffffffffffff0000
; CHECK-NEXT:    mov z5.d, #0xffffffffffff0001
; CHECK-NEXT:    mov x8, #-65534 // =0xffffffffffff0002
; CHECK-NEXT:    mov z24.d, #0xffffffffffff0003
; CHECK-NEXT:    movi v0.2d, #0000000000000000
; CHECK-NEXT:    mov z6.d, x8
; CHECK-NEXT:    movi v1.2d, #0000000000000000
; CHECK-NEXT:    mov w8, #2048 // =0x800
; CHECK-NEXT:    movi v2.2d, #0000000000000000
; CHECK-NEXT:    movi v3.2d, #0000000000000000
; CHECK-NEXT:    cntd x9
; CHECK-NEXT:    add z4.d, z7.d, z4.d
; CHECK-NEXT:    add z5.d, z7.d, z5.d
; CHECK-NEXT:    rdvl x10, #1
; CHECK-NEXT:    add z6.d, z7.d, z6.d
; CHECK-NEXT:    add z7.d, z7.d, z24.d
; CHECK-NEXT:  .LBB0_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ld1h { z24.h }, p0/z, [x0]
; CHECK-NEXT:    subs x8, x8, x9
; CHECK-NEXT:    add x0, x0, x10
; CHECK-NEXT:    tbl z25.h, { z24.h }, z4.h
; CHECK-NEXT:    tbl z26.h, { z24.h }, z5.h
; CHECK-NEXT:    tbl z27.h, { z24.h }, z6.h
; CHECK-NEXT:    tbl z24.h, { z24.h }, z7.h
; CHECK-NEXT:    add z0.d, z0.d, z25.d
; CHECK-NEXT:    add z1.d, z1.d, z26.d
; CHECK-NEXT:    add z2.d, z2.d, z27.d
; CHECK-NEXT:    add z3.d, z3.d, z24.d
; CHECK-NEXT:    b.ne .LBB0_1
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    str z0, [x1]
; CHECK-NEXT:    str z1, [x1, #1, mul vl]
; CHECK-NEXT:    str z2, [x1, #2, mul vl]
; CHECK-NEXT:    str z3, [x1, #3, mul vl]
; CHECK-NEXT:    ret
entry:
  %vscale = tail call i64 @llvm.vscale.i64()
  %stride = shl nuw nsw i64 %vscale, 1
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %acc.b.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.b.i64, %loop ]
  %acc.g.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.g.i64, %loop ]
  %acc.r.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.r.i64, %loop ]
  %acc.a.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.a.i64, %loop ]
  %src.gep = getelementptr inbounds nuw [4 x i16], ptr %src, i64 %iv
  %bgra = call <vscale x 8 x i16> @llvm.masked.load(ptr %src.gep, <vscale x 8 x i1> %mask, <vscale x 8 x i16> zeroinitializer)
  %deinterleave = tail call { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } @llvm.vector.deinterleave4(<vscale x 8 x i16> %bgra)
  %b.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 0
  %g.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 1
  %r.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 2
  %a.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 3
  %b.i64 = zext <vscale x 2 x i16> %b.i16 to <vscale x 2 x i64>
  %g.i64 = zext <vscale x 2 x i16> %g.i16 to <vscale x 2 x i64>
  %r.i64 = zext <vscale x 2 x i16> %r.i16 to <vscale x 2 x i64>
  %a.i64 = zext <vscale x 2 x i16> %a.i16 to <vscale x 2 x i64>
  %add.b.i64 = add <vscale x 2 x i64> %acc.b.i64, %b.i64
  %add.g.i64 = add <vscale x 2 x i64> %acc.g.i64, %g.i64
  %add.r.i64 = add <vscale x 2 x i64> %acc.r.i64, %r.i64
  %add.a.i64 = add <vscale x 2 x i64> %acc.a.i64, %a.i64
  %iv.next = add nuw i64 %iv, %stride
  %ec = icmp eq i64 %iv.next, 2048
  br i1 %ec, label %exit, label %loop

exit:
  store <vscale x 2 x i64> %add.b.i64, ptr %dst
  %g.i64.gep = getelementptr <vscale x 2 x i64>, ptr %dst, i64 1
  store <vscale x 2 x i64> %add.g.i64, ptr %g.i64.gep
  %r.i64.gep = getelementptr <vscale x 2 x i64>, ptr %dst, i64 2
  store <vscale x 2 x i64> %add.r.i64, ptr %r.i64.gep
  %a.i64.gep = getelementptr <vscale x 2 x i64>, ptr %dst, i64 3
  store <vscale x 2 x i64> %add.a.i64, ptr %a.i64.gep
  ret void
}

;; TODO: Do we want to perform the sext equivalent? Requires a splat of the
;;       sign bits into another register (using asr) and a more complex tbl
;;       mask to choose; more instructions, but may still be worthwhile if
;;       we find cases in real code.
define void @sext_nxv8i16_to_nxv8i64_deinterleave_in_loop(ptr %src, ptr %dst, <vscale x 8 x i1> %mask) #0 {
; CHECK-LABEL: sext_nxv8i16_to_nxv8i64_deinterleave_in_loop:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    movi v0.2d, #0000000000000000
; CHECK-NEXT:    movi v1.2d, #0000000000000000
; CHECK-NEXT:    mov w8, #2048 // =0x800
; CHECK-NEXT:    movi v2.2d, #0000000000000000
; CHECK-NEXT:    movi v3.2d, #0000000000000000
; CHECK-NEXT:    cntd x9
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    rdvl x10, #1
; CHECK-NEXT:  .LBB1_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ld1h { z4.h }, p0/z, [x0]
; CHECK-NEXT:    subs x8, x8, x9
; CHECK-NEXT:    add x0, x0, x10
; CHECK-NEXT:    uunpkhi z5.s, z4.h
; CHECK-NEXT:    uunpklo z4.s, z4.h
; CHECK-NEXT:    uunpkhi z6.d, z5.s
; CHECK-NEXT:    uunpklo z5.d, z5.s
; CHECK-NEXT:    uunpkhi z7.d, z4.s
; CHECK-NEXT:    uunpklo z4.d, z4.s
; CHECK-NEXT:    uzp1 z24.d, z5.d, z6.d
; CHECK-NEXT:    uzp2 z5.d, z5.d, z6.d
; CHECK-NEXT:    uzp1 z25.d, z4.d, z7.d
; CHECK-NEXT:    uzp2 z4.d, z4.d, z7.d
; CHECK-NEXT:    uzp1 z6.d, z25.d, z24.d
; CHECK-NEXT:    uzp2 z7.d, z4.d, z5.d
; CHECK-NEXT:    uzp2 z24.d, z25.d, z24.d
; CHECK-NEXT:    uzp1 z4.d, z4.d, z5.d
; CHECK-NEXT:    sxth z6.d, p1/m, z6.d
; CHECK-NEXT:    sxth z24.d, p1/m, z24.d
; CHECK-NEXT:    sxth z7.d, p1/m, z7.d
; CHECK-NEXT:    sxth z4.d, p1/m, z4.d
; CHECK-NEXT:    add z0.d, z0.d, z6.d
; CHECK-NEXT:    add z2.d, z2.d, z24.d
; CHECK-NEXT:    add z3.d, z3.d, z7.d
; CHECK-NEXT:    add z1.d, z1.d, z4.d
; CHECK-NEXT:    b.ne .LBB1_1
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    str z0, [x1]
; CHECK-NEXT:    str z1, [x1, #1, mul vl]
; CHECK-NEXT:    str z2, [x1, #2, mul vl]
; CHECK-NEXT:    str z3, [x1, #3, mul vl]
; CHECK-NEXT:    ret
entry:
  %vscale = tail call i64 @llvm.vscale.i64()
  %stride = shl nuw nsw i64 %vscale, 1
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %acc.b.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.b.i64, %loop ]
  %acc.g.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.g.i64, %loop ]
  %acc.r.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.r.i64, %loop ]
  %acc.a.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.a.i64, %loop ]
  %src.gep = getelementptr inbounds nuw [4 x i16], ptr %src, i64 %iv
  %bgra = call <vscale x 8 x i16> @llvm.masked.load(ptr %src.gep, <vscale x 8 x i1> %mask, <vscale x 8 x i16> zeroinitializer)
  %deinterleave = tail call { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } @llvm.vector.deinterleave4(<vscale x 8 x i16> %bgra)
  %b.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 0
  %g.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 1
  %r.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 2
  %a.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 3
  %b.i64 = sext <vscale x 2 x i16> %b.i16 to <vscale x 2 x i64>
  %g.i64 = sext <vscale x 2 x i16> %g.i16 to <vscale x 2 x i64>
  %r.i64 = sext <vscale x 2 x i16> %r.i16 to <vscale x 2 x i64>
  %a.i64 = sext <vscale x 2 x i16> %a.i16 to <vscale x 2 x i64>
  %add.b.i64 = add <vscale x 2 x i64> %acc.b.i64, %b.i64
  %add.g.i64 = add <vscale x 2 x i64> %acc.g.i64, %g.i64
  %add.r.i64 = add <vscale x 2 x i64> %acc.r.i64, %r.i64
  %add.a.i64 = add <vscale x 2 x i64> %acc.a.i64, %a.i64
  %iv.next = add nuw i64 %iv, %stride
  %ec = icmp eq i64 %iv.next, 2048
  br i1 %ec, label %exit, label %loop

exit:
  store <vscale x 2 x i64> %add.b.i64, ptr %dst
  %g.i64.gep = getelementptr <vscale x 2 x i64>, ptr %dst, i64 1
  store <vscale x 2 x i64> %add.g.i64, ptr %g.i64.gep
  %r.i64.gep = getelementptr <vscale x 2 x i64>, ptr %dst, i64 2
  store <vscale x 2 x i64> %add.r.i64, ptr %r.i64.gep
  %a.i64.gep = getelementptr <vscale x 2 x i64>, ptr %dst, i64 3
  store <vscale x 2 x i64> %add.a.i64, ptr %a.i64.gep
  ret void
}

;; Check that we reuse tbl masks for the same shuffle type.
define void @zext_2x_nxv8i16_to_nxv8i64_deinterleave_in_loop(ptr %src, ptr %dst, <vscale x 8 x i1> %mask) #0 {
; CHECK-LABEL: zext_2x_nxv8i16_to_nxv8i64_deinterleave_in_loop:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-2
; CHECK-NEXT:    str z9, [sp] // 16-byte Folded Spill
; CHECK-NEXT:    str z8, [sp, #1, mul vl] // 16-byte Folded Spill
; CHECK-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x40, 0x1e, 0x22 // sp + 16 + 16 * VG
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    .cfi_escape 0x10, 0x48, 0x09, 0x92, 0x2e, 0x00, 0x11, 0x78, 0x1e, 0x22, 0x40, 0x1c // $d8 @ cfa - 8 * VG - 16
; CHECK-NEXT:    .cfi_escape 0x10, 0x49, 0x09, 0x92, 0x2e, 0x00, 0x11, 0x70, 0x1e, 0x22, 0x40, 0x1c // $d9 @ cfa - 16 * VG - 16
; CHECK-NEXT:    index z6.d, #0, #4
; CHECK-NEXT:    mov z1.d, #0xffffffffffff0000
; CHECK-NEXT:    mov z2.d, #0xffffffffffff0001
; CHECK-NEXT:    mov x8, #-65534 // =0xffffffffffff0002
; CHECK-NEXT:    mov z24.d, #0xffffffffffff0003
; CHECK-NEXT:    movi v0.2d, #0000000000000000
; CHECK-NEXT:    mov z4.d, x8
; CHECK-NEXT:    movi v3.2d, #0000000000000000
; CHECK-NEXT:    mov w8, #2048 // =0x800
; CHECK-NEXT:    movi v5.2d, #0000000000000000
; CHECK-NEXT:    movi v7.2d, #0000000000000000
; CHECK-NEXT:    cntw x9
; CHECK-NEXT:    add z1.d, z6.d, z1.d
; CHECK-NEXT:    add z2.d, z6.d, z2.d
; CHECK-NEXT:    rdvl x10, #2
; CHECK-NEXT:    add z4.d, z6.d, z4.d
; CHECK-NEXT:    add z6.d, z6.d, z24.d
; CHECK-NEXT:  .LBB2_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ld1h { z24.h }, p0/z, [x0]
; CHECK-NEXT:    ld1h { z25.h }, p0/z, [x0, #1, mul vl]
; CHECK-NEXT:    subs x8, x8, x9
; CHECK-NEXT:    add x0, x0, x10
; CHECK-NEXT:    tbl z26.h, { z24.h }, z1.h
; CHECK-NEXT:    tbl z27.h, { z24.h }, z2.h
; CHECK-NEXT:    tbl z28.h, { z24.h }, z4.h
; CHECK-NEXT:    tbl z29.h, { z24.h }, z6.h
; CHECK-NEXT:    tbl z30.h, { z25.h }, z1.h
; CHECK-NEXT:    tbl z31.h, { z25.h }, z2.h
; CHECK-NEXT:    tbl z8.h, { z25.h }, z4.h
; CHECK-NEXT:    tbl z9.h, { z25.h }, z6.h
; CHECK-NEXT:    add z24.d, z0.d, z26.d
; CHECK-NEXT:    add z25.d, z3.d, z27.d
; CHECK-NEXT:    add z26.d, z5.d, z28.d
; CHECK-NEXT:    add z27.d, z7.d, z29.d
; CHECK-NEXT:    add z0.d, z24.d, z30.d
; CHECK-NEXT:    add z3.d, z25.d, z31.d
; CHECK-NEXT:    add z5.d, z26.d, z8.d
; CHECK-NEXT:    add z7.d, z27.d, z9.d
; CHECK-NEXT:    b.ne .LBB2_1
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    ldr z9, [sp] // 16-byte Folded Reload
; CHECK-NEXT:    ldr z8, [sp, #1, mul vl] // 16-byte Folded Reload
; CHECK-NEXT:    str z24, [x1]
; CHECK-NEXT:    str z25, [x1, #1, mul vl]
; CHECK-NEXT:    str z26, [x1, #2, mul vl]
; CHECK-NEXT:    str z27, [x1, #3, mul vl]
; CHECK-NEXT:    addvl sp, sp, #2
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
entry:
  %vscale = tail call i64 @llvm.vscale.i64()
  %stride = shl nuw nsw i64 %vscale, 2
  %midpoint = shl nuw nsw i64 %vscale, 1
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %acc.b.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.b.i64.2, %loop ]
  %acc.g.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.g.i64.2, %loop ]
  %acc.r.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.r.i64.2, %loop ]
  %acc.a.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.a.i64.2, %loop ]
  %src.gep = getelementptr inbounds nuw [4 x i16], ptr %src, i64 %iv
  %bgra = call <vscale x 8 x i16> @llvm.masked.load(ptr %src.gep, <vscale x 8 x i1> %mask, <vscale x 8 x i16> zeroinitializer)
  %deinterleave = tail call { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } @llvm.vector.deinterleave4(<vscale x 8 x i16> %bgra)
  %b.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 0
  %g.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 1
  %r.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 2
  %a.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 3
  %b.i64 = zext <vscale x 2 x i16> %b.i16 to <vscale x 2 x i64>
  %g.i64 = zext <vscale x 2 x i16> %g.i16 to <vscale x 2 x i64>
  %r.i64 = zext <vscale x 2 x i16> %r.i16 to <vscale x 2 x i64>
  %a.i64 = zext <vscale x 2 x i16> %a.i16 to <vscale x 2 x i64>
  %add.b.i64 = add <vscale x 2 x i64> %acc.b.i64, %b.i64
  %add.g.i64 = add <vscale x 2 x i64> %acc.g.i64, %g.i64
  %add.r.i64 = add <vscale x 2 x i64> %acc.r.i64, %r.i64
  %add.a.i64 = add <vscale x 2 x i64> %acc.a.i64, %a.i64
  %src.gep.2 = getelementptr inbounds nuw [4 x i16], ptr %src.gep, i64 %midpoint
  %bgra.2 = call <vscale x 8 x i16> @llvm.masked.load(ptr %src.gep.2, <vscale x 8 x i1> %mask, <vscale x 8 x i16> zeroinitializer)
  %deinterleave.2 = tail call { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } @llvm.vector.deinterleave4(<vscale x 8 x i16> %bgra.2)
  %b.i16.2 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave.2, 0
  %g.i16.2 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave.2, 1
  %r.i16.2 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave.2, 2
  %a.i16.2 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave.2, 3
  %b.i64.2 = zext <vscale x 2 x i16> %b.i16.2 to <vscale x 2 x i64>
  %g.i64.2 = zext <vscale x 2 x i16> %g.i16.2 to <vscale x 2 x i64>
  %r.i64.2 = zext <vscale x 2 x i16> %r.i16.2 to <vscale x 2 x i64>
  %a.i64.2 = zext <vscale x 2 x i16> %a.i16.2 to <vscale x 2 x i64>
  %add.b.i64.2 = add <vscale x 2 x i64> %add.b.i64, %b.i64.2
  %add.g.i64.2 = add <vscale x 2 x i64> %add.g.i64, %g.i64.2
  %add.r.i64.2 = add <vscale x 2 x i64> %add.r.i64, %r.i64.2
  %add.a.i64.2 = add <vscale x 2 x i64> %add.a.i64, %a.i64.2
  %iv.next = add nuw i64 %iv, %stride
  %ec = icmp eq i64 %iv.next, 2048
  br i1 %ec, label %exit, label %loop

exit:
  store <vscale x 2 x i64> %add.b.i64, ptr %dst
  %g.i64.gep = getelementptr <vscale x 2 x i64>, ptr %dst, i64 1
  store <vscale x 2 x i64> %add.g.i64, ptr %g.i64.gep
  %r.i64.gep = getelementptr <vscale x 2 x i64>, ptr %dst, i64 2
  store <vscale x 2 x i64> %add.r.i64, ptr %r.i64.gep
  %a.i64.gep = getelementptr <vscale x 2 x i64>, ptr %dst, i64 3
  store <vscale x 2 x i64> %add.a.i64, ptr %a.i64.gep
  ret void
}

define void @uitofp_nxv8i16_to_nxv8f64_deinterleave_in_loop(ptr %src, ptr %dst, <vscale x 8 x i1> %mask) #0 {
; CHECK-LABEL: uitofp_nxv8i16_to_nxv8f64_deinterleave_in_loop:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    index z7.d, #0, #4
; CHECK-NEXT:    mov z4.d, #0xffffffffffff0000
; CHECK-NEXT:    mov z5.d, #0xffffffffffff0001
; CHECK-NEXT:    mov x8, #-65534 // =0xffffffffffff0002
; CHECK-NEXT:    mov z24.d, #0xffffffffffff0003
; CHECK-NEXT:    movi v0.2d, #0000000000000000
; CHECK-NEXT:    mov z6.d, x8
; CHECK-NEXT:    movi v1.2d, #0000000000000000
; CHECK-NEXT:    mov w8, #2048 // =0x800
; CHECK-NEXT:    movi v2.2d, #0000000000000000
; CHECK-NEXT:    movi v3.2d, #0000000000000000
; CHECK-NEXT:    cntw x9
; CHECK-NEXT:    add z4.d, z7.d, z4.d
; CHECK-NEXT:    add z5.d, z7.d, z5.d
; CHECK-NEXT:    rdvl x10, #2
; CHECK-NEXT:    add z6.d, z7.d, z6.d
; CHECK-NEXT:    add z7.d, z7.d, z24.d
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:  .LBB3_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ld1h { z24.h }, p0/z, [x0]
; CHECK-NEXT:    subs x8, x8, x9
; CHECK-NEXT:    add x0, x0, x10
; CHECK-NEXT:    tbl z25.h, { z24.h }, z4.h
; CHECK-NEXT:    tbl z26.h, { z24.h }, z5.h
; CHECK-NEXT:    tbl z27.h, { z24.h }, z6.h
; CHECK-NEXT:    tbl z24.h, { z24.h }, z7.h
; CHECK-NEXT:    ucvtf z25.d, p1/m, z25.d
; CHECK-NEXT:    ucvtf z26.d, p1/m, z26.d
; CHECK-NEXT:    ucvtf z27.d, p1/m, z27.d
; CHECK-NEXT:    ucvtf z24.d, p1/m, z24.d
; CHECK-NEXT:    fadd z0.d, z0.d, z25.d
; CHECK-NEXT:    fadd z1.d, z1.d, z26.d
; CHECK-NEXT:    fadd z2.d, z2.d, z27.d
; CHECK-NEXT:    fadd z3.d, z3.d, z24.d
; CHECK-NEXT:    b.ne .LBB3_1
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    str z0, [x1]
; CHECK-NEXT:    str z1, [x1, #1, mul vl]
; CHECK-NEXT:    str z2, [x1, #2, mul vl]
; CHECK-NEXT:    str z3, [x1, #3, mul vl]
; CHECK-NEXT:    ret
entry:
  %vscale = tail call i64 @llvm.vscale.i64()
  %stride = shl nuw nsw i64 %vscale, 2
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %acc.b.f64 = phi <vscale x 2 x double> [ splat(double 0.000000e+00), %entry ], [ %fadd.b.f64, %loop ]
  %acc.g.f64 = phi <vscale x 2 x double> [ splat(double 0.000000e+00), %entry ], [ %fadd.g.f64, %loop ]
  %acc.r.f64 = phi <vscale x 2 x double> [ splat(double 0.000000e+00), %entry ], [ %fadd.r.f64, %loop ]
  %acc.a.f64 = phi <vscale x 2 x double> [ splat(double 0.000000e+00), %entry ], [ %fadd.a.f64, %loop ]
  %src.gep = getelementptr inbounds nuw [4 x i16], ptr %src, i64 %iv
  %bgra = call <vscale x 8 x i16> @llvm.masked.load(ptr %src.gep, <vscale x 8 x i1> %mask, <vscale x 8 x i16> zeroinitializer)
  %deinterleave = tail call { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } @llvm.vector.deinterleave4(<vscale x 8 x i16> %bgra)
  %b.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 0
  %g.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 1
  %r.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 2
  %a.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 3
  %b.f64 = uitofp <vscale x 2 x i16> %b.i16 to <vscale x 2 x double>
  %g.f64 = uitofp <vscale x 2 x i16> %g.i16 to <vscale x 2 x double>
  %r.f64 = uitofp <vscale x 2 x i16> %r.i16 to <vscale x 2 x double>
  %a.f64 = uitofp <vscale x 2 x i16> %a.i16 to <vscale x 2 x double>
  %fadd.b.f64 = fadd <vscale x 2 x double> %acc.b.f64, %b.f64
  %fadd.g.f64 = fadd <vscale x 2 x double> %acc.g.f64, %g.f64
  %fadd.r.f64 = fadd <vscale x 2 x double> %acc.r.f64, %r.f64
  %fadd.a.f64 = fadd <vscale x 2 x double> %acc.a.f64, %a.f64
  %iv.next = add nuw i64 %iv, %stride
  %ec = icmp eq i64 %iv.next, 2048
  br i1 %ec, label %exit, label %loop

exit:
  store <vscale x 2 x double> %fadd.b.f64, ptr %dst
  %g.f64.gep = getelementptr <vscale x 2 x double>, ptr %dst, i64 1
  store <vscale x 2 x double> %fadd.g.f64, ptr %g.f64.gep
  %r.f64.gep = getelementptr <vscale x 2 x double>, ptr %dst, i64 2
  store <vscale x 2 x double> %fadd.r.f64, ptr %r.f64.gep
  %a.f64.gep = getelementptr <vscale x 2 x double>, ptr %dst, i64 3
  store <vscale x 2 x double> %fadd.a.f64, ptr %a.f64.gep
  ret void
}

define void @zext_nxv16i8_to_nxv16i32_deinterleave_in_loop(ptr %src, ptr %dst, <vscale x 16 x i1> %mask) #0 {
; CHECK-LABEL: zext_nxv16i8_to_nxv16i32_deinterleave_in_loop:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    movi v0.2d, #0000000000000000
; CHECK-NEXT:    movi v1.2d, #0000000000000000
; CHECK-NEXT:    mov w8, #2048 // =0x800
; CHECK-NEXT:    movi v2.2d, #0000000000000000
; CHECK-NEXT:    movi v3.2d, #0000000000000000
; CHECK-NEXT:    cntd x9
; CHECK-NEXT:    cnth x10
; CHECK-NEXT:  .LBB4_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ld1b { z4.b }, p0/z, [x0]
; CHECK-NEXT:    subs x8, x8, x9
; CHECK-NEXT:    add x0, x0, x10
; CHECK-NEXT:    uunpkhi z5.h, z4.b
; CHECK-NEXT:    uunpklo z4.h, z4.b
; CHECK-NEXT:    uunpkhi z6.s, z5.h
; CHECK-NEXT:    uunpklo z5.s, z5.h
; CHECK-NEXT:    uunpkhi z7.s, z4.h
; CHECK-NEXT:    uunpklo z4.s, z4.h
; CHECK-NEXT:    uzp1 z24.s, z5.s, z6.s
; CHECK-NEXT:    uzp2 z5.s, z5.s, z6.s
; CHECK-NEXT:    uzp1 z25.s, z4.s, z7.s
; CHECK-NEXT:    uzp2 z4.s, z4.s, z7.s
; CHECK-NEXT:    uzp1 z6.s, z25.s, z24.s
; CHECK-NEXT:    uzp2 z7.s, z4.s, z5.s
; CHECK-NEXT:    uzp2 z24.s, z25.s, z24.s
; CHECK-NEXT:    uzp1 z4.s, z4.s, z5.s
; CHECK-NEXT:    and z6.s, z6.s, #0xff
; CHECK-NEXT:    and z24.s, z24.s, #0xff
; CHECK-NEXT:    and z7.s, z7.s, #0xff
; CHECK-NEXT:    and z4.s, z4.s, #0xff
; CHECK-NEXT:    add z0.s, z0.s, z6.s
; CHECK-NEXT:    add z2.s, z2.s, z24.s
; CHECK-NEXT:    add z3.s, z3.s, z7.s
; CHECK-NEXT:    add z1.s, z1.s, z4.s
; CHECK-NEXT:    b.ne .LBB4_1
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    str z0, [x1]
; CHECK-NEXT:    str z1, [x1, #1, mul vl]
; CHECK-NEXT:    str z2, [x1, #2, mul vl]
; CHECK-NEXT:    str z3, [x1, #3, mul vl]
; CHECK-NEXT:    ret
entry:
  %vscale = tail call i64 @llvm.vscale.i64()
  %stride = shl nuw nsw i64 %vscale, 1
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %acc.b.i64 = phi <vscale x 4 x i32> [ splat(i32 0), %entry ], [ %add.b.i64, %loop ]
  %acc.g.i64 = phi <vscale x 4 x i32> [ splat(i32 0), %entry ], [ %add.g.i64, %loop ]
  %acc.r.i64 = phi <vscale x 4 x i32> [ splat(i32 0), %entry ], [ %add.r.i64, %loop ]
  %acc.a.i64 = phi <vscale x 4 x i32> [ splat(i32 0), %entry ], [ %add.a.i64, %loop ]
  %src.gep = getelementptr inbounds nuw [4 x i8], ptr %src, i64 %iv
  %bgra = call <vscale x 16 x i8> @llvm.masked.load(ptr %src.gep, <vscale x 16 x i1> %mask, <vscale x 16 x i8> zeroinitializer)
  %deinterleave = tail call { <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8> } @llvm.vector.deinterleave4(<vscale x 16 x i8> %bgra)
  %b.i16 = extractvalue { <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8> } %deinterleave, 0
  %g.i16 = extractvalue { <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8> } %deinterleave, 1
  %r.i16 = extractvalue { <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8> } %deinterleave, 2
  %a.i16 = extractvalue { <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8> } %deinterleave, 3
  %b.i64 = zext <vscale x 4 x i8> %b.i16 to <vscale x 4 x i32>
  %g.i64 = zext <vscale x 4 x i8> %g.i16 to <vscale x 4 x i32>
  %r.i64 = zext <vscale x 4 x i8> %r.i16 to <vscale x 4 x i32>
  %a.i64 = zext <vscale x 4 x i8> %a.i16 to <vscale x 4 x i32>
  %add.b.i64 = add <vscale x 4 x i32> %acc.b.i64, %b.i64
  %add.g.i64 = add <vscale x 4 x i32> %acc.g.i64, %g.i64
  %add.r.i64 = add <vscale x 4 x i32> %acc.r.i64, %r.i64
  %add.a.i64 = add <vscale x 4 x i32> %acc.a.i64, %a.i64
  %iv.next = add nuw i64 %iv, %stride
  %ec = icmp eq i64 %iv.next, 2048
  br i1 %ec, label %exit, label %loop

exit:
  store <vscale x 4 x i32> %add.b.i64, ptr %dst
  %g.i64.gep = getelementptr <vscale x 4 x i32>, ptr %dst, i64 1
  store <vscale x 4 x i32> %add.g.i64, ptr %g.i64.gep
  %r.i64.gep = getelementptr <vscale x 4 x i32>, ptr %dst, i64 2
  store <vscale x 4 x i32> %add.r.i64, ptr %r.i64.gep
  %a.i64.gep = getelementptr <vscale x 4 x i32>, ptr %dst, i64 3
  store <vscale x 4 x i32> %add.a.i64, ptr %a.i64.gep
  ret void
}

;; TODO: If we know vscale is small enough, then we can do extensions via tbl
;;       even for 8b elements.
define void @zext_nxv16i8_to_nxv16i32_deinterleave_in_loop_max_vscale_8(ptr %src, ptr %dst, <vscale x 16 x i1> %mask) #1 {
; CHECK-LABEL: zext_nxv16i8_to_nxv16i32_deinterleave_in_loop_max_vscale_8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    movi v0.2d, #0000000000000000
; CHECK-NEXT:    movi v1.2d, #0000000000000000
; CHECK-NEXT:    mov x8, xzr
; CHECK-NEXT:    movi v2.2d, #0000000000000000
; CHECK-NEXT:    movi v3.2d, #0000000000000000
; CHECK-NEXT:    cnth x9
; CHECK-NEXT:  .LBB5_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ld1b { z4.b }, p0/z, [x0, x8]
; CHECK-NEXT:    add x8, x8, x9
; CHECK-NEXT:    cmp x8, #2, lsl #12 // =8192
; CHECK-NEXT:    uunpkhi z5.h, z4.b
; CHECK-NEXT:    uunpklo z4.h, z4.b
; CHECK-NEXT:    uunpkhi z6.s, z5.h
; CHECK-NEXT:    uunpklo z5.s, z5.h
; CHECK-NEXT:    uunpkhi z7.s, z4.h
; CHECK-NEXT:    uunpklo z4.s, z4.h
; CHECK-NEXT:    uzp1 z24.s, z5.s, z6.s
; CHECK-NEXT:    uzp2 z5.s, z5.s, z6.s
; CHECK-NEXT:    uzp1 z25.s, z4.s, z7.s
; CHECK-NEXT:    uzp2 z4.s, z4.s, z7.s
; CHECK-NEXT:    uzp1 z6.s, z25.s, z24.s
; CHECK-NEXT:    uzp2 z7.s, z4.s, z5.s
; CHECK-NEXT:    uzp2 z24.s, z25.s, z24.s
; CHECK-NEXT:    uzp1 z4.s, z4.s, z5.s
; CHECK-NEXT:    and z6.s, z6.s, #0xff
; CHECK-NEXT:    and z24.s, z24.s, #0xff
; CHECK-NEXT:    and z7.s, z7.s, #0xff
; CHECK-NEXT:    and z4.s, z4.s, #0xff
; CHECK-NEXT:    add z0.s, z0.s, z6.s
; CHECK-NEXT:    add z2.s, z2.s, z24.s
; CHECK-NEXT:    add z3.s, z3.s, z7.s
; CHECK-NEXT:    add z1.s, z1.s, z4.s
; CHECK-NEXT:    b.ne .LBB5_1
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    str z0, [x1]
; CHECK-NEXT:    str z1, [x1, #1, mul vl]
; CHECK-NEXT:    str z2, [x1, #2, mul vl]
; CHECK-NEXT:    str z3, [x1, #3, mul vl]
; CHECK-NEXT:    ret
entry:
  %vscale = tail call i64 @llvm.vscale.i64()
  %stride = shl nuw nsw i64 %vscale, 1
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %acc.b.i64 = phi <vscale x 4 x i32> [ splat(i32 0), %entry ], [ %add.b.i64, %loop ]
  %acc.g.i64 = phi <vscale x 4 x i32> [ splat(i32 0), %entry ], [ %add.g.i64, %loop ]
  %acc.r.i64 = phi <vscale x 4 x i32> [ splat(i32 0), %entry ], [ %add.r.i64, %loop ]
  %acc.a.i64 = phi <vscale x 4 x i32> [ splat(i32 0), %entry ], [ %add.a.i64, %loop ]
  %src.gep = getelementptr inbounds nuw [4 x i8], ptr %src, i64 %iv
  %bgra = call <vscale x 16 x i8> @llvm.masked.load(ptr %src.gep, <vscale x 16 x i1> %mask, <vscale x 16 x i8> zeroinitializer)
  %deinterleave = tail call { <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8> } @llvm.vector.deinterleave4(<vscale x 16 x i8> %bgra)
  %b.i16 = extractvalue { <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8> } %deinterleave, 0
  %g.i16 = extractvalue { <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8> } %deinterleave, 1
  %r.i16 = extractvalue { <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8> } %deinterleave, 2
  %a.i16 = extractvalue { <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8> } %deinterleave, 3
  %b.i64 = zext <vscale x 4 x i8> %b.i16 to <vscale x 4 x i32>
  %g.i64 = zext <vscale x 4 x i8> %g.i16 to <vscale x 4 x i32>
  %r.i64 = zext <vscale x 4 x i8> %r.i16 to <vscale x 4 x i32>
  %a.i64 = zext <vscale x 4 x i8> %a.i16 to <vscale x 4 x i32>
  %add.b.i64 = add <vscale x 4 x i32> %acc.b.i64, %b.i64
  %add.g.i64 = add <vscale x 4 x i32> %acc.g.i64, %g.i64
  %add.r.i64 = add <vscale x 4 x i32> %acc.r.i64, %r.i64
  %add.a.i64 = add <vscale x 4 x i32> %acc.a.i64, %a.i64
  %iv.next = add nuw i64 %iv, %stride
  %ec = icmp eq i64 %iv.next, 2048
  br i1 %ec, label %exit, label %loop

exit:
  store <vscale x 4 x i32> %add.b.i64, ptr %dst
  %g.i64.gep = getelementptr <vscale x 4 x i32>, ptr %dst, i64 1
  store <vscale x 4 x i32> %add.g.i64, ptr %g.i64.gep
  %r.i64.gep = getelementptr <vscale x 4 x i32>, ptr %dst, i64 2
  store <vscale x 4 x i32> %add.r.i64, ptr %r.i64.gep
  %a.i64.gep = getelementptr <vscale x 4 x i32>, ptr %dst, i64 3
  store <vscale x 4 x i32> %add.a.i64, ptr %a.i64.gep
  ret void
}

;; If not in a loop, don't perform the transform, since the setup costs more
;; than the unpacks.
define void @zext_nxv8i16_to_nxv8i64_out_of_loop(ptr %src, ptr %dst, <vscale x 8 x i1> %mask) #0 {
; CHECK-LABEL: zext_nxv8i16_to_nxv8i64_out_of_loop:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    uunpkhi z1.s, z0.h
; CHECK-NEXT:    uunpklo z0.s, z0.h
; CHECK-NEXT:    uunpkhi z2.d, z1.s
; CHECK-NEXT:    uunpklo z1.d, z1.s
; CHECK-NEXT:    uunpkhi z3.d, z0.s
; CHECK-NEXT:    uunpklo z0.d, z0.s
; CHECK-NEXT:    uzp1 z4.d, z1.d, z2.d
; CHECK-NEXT:    uzp2 z1.d, z1.d, z2.d
; CHECK-NEXT:    uzp1 z5.d, z0.d, z3.d
; CHECK-NEXT:    uzp2 z0.d, z0.d, z3.d
; CHECK-NEXT:    uzp1 z2.d, z5.d, z4.d
; CHECK-NEXT:    uzp1 z3.d, z0.d, z1.d
; CHECK-NEXT:    uzp2 z4.d, z5.d, z4.d
; CHECK-NEXT:    uzp2 z0.d, z0.d, z1.d
; CHECK-NEXT:    and z2.d, z2.d, #0xffff
; CHECK-NEXT:    and z3.d, z3.d, #0xffff
; CHECK-NEXT:    and z4.d, z4.d, #0xffff
; CHECK-NEXT:    and z0.d, z0.d, #0xffff
; CHECK-NEXT:    str z2, [x1]
; CHECK-NEXT:    str z3, [x1, #1, mul vl]
; CHECK-NEXT:    str z4, [x1, #2, mul vl]
; CHECK-NEXT:    str z0, [x1, #3, mul vl]
; CHECK-NEXT:    ret
entry:
  %bgra = call <vscale x 8 x i16> @llvm.masked.load(ptr %src, <vscale x 8 x i1> %mask, <vscale x 8 x i16> zeroinitializer)
  %deinterleave = tail call { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } @llvm.vector.deinterleave4(<vscale x 8 x i16> %bgra)
  %b.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 0
  %g.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 1
  %r.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 2
  %a.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 3
  %b.i64 = zext <vscale x 2 x i16> %b.i16 to <vscale x 2 x i64>
  %g.i64 = zext <vscale x 2 x i16> %g.i16 to <vscale x 2 x i64>
  %r.i64 = zext <vscale x 2 x i16> %r.i16 to <vscale x 2 x i64>
  %a.i64 = zext <vscale x 2 x i16> %a.i16 to <vscale x 2 x i64>
  store <vscale x 2 x i64> %b.i64, ptr %dst
  %g.i64.gep = getelementptr <vscale x 2 x i64>, ptr %dst, i64 1
  store <vscale x 2 x i64> %g.i64, ptr %g.i64.gep
  %r.i64.gep = getelementptr <vscale x 2 x i64>, ptr %dst, i64 2
  store <vscale x 2 x i64> %r.i64, ptr %r.i64.gep
  %a.i64.gep = getelementptr <vscale x 2 x i64>, ptr %dst, i64 3
  store <vscale x 2 x i64> %a.i64, ptr %a.i64.gep
  ret void
}

define void @zext_nxv8i16_to_nxv8i64_deinterleave_single_lane_used(ptr %src, ptr %dst, <vscale x 8 x i1> %mask) #0 {
; CHECK-LABEL: zext_nxv8i16_to_nxv8i64_deinterleave_single_lane_used:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov x8, #-65536 // =0xffffffffffff0000
; CHECK-NEXT:    movi v0.2d, #0000000000000000
; CHECK-NEXT:    cntd x9
; CHECK-NEXT:    index z1.d, x8, #4
; CHECK-NEXT:    mov w8, #2048 // =0x800
; CHECK-NEXT:    rdvl x10, #1
; CHECK-NEXT:  .LBB7_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ld1h { z2.h }, p0/z, [x0]
; CHECK-NEXT:    subs x8, x8, x9
; CHECK-NEXT:    add x0, x0, x10
; CHECK-NEXT:    tbl z2.h, { z2.h }, z1.h
; CHECK-NEXT:    add z0.d, z0.d, z2.d
; CHECK-NEXT:    b.ne .LBB7_1
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    str z0, [x1]
; CHECK-NEXT:    ret
entry:
  %vscale = tail call i64 @llvm.vscale.i64()
  %stride = shl nuw nsw i64 %vscale, 1
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %acc.b.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.b.i64, %loop ]
  %src.gep = getelementptr inbounds nuw [4 x i16], ptr %src, i64 %iv
  %bgra = call <vscale x 8 x i16> @llvm.masked.load(ptr %src.gep, <vscale x 8 x i1> %mask, <vscale x 8 x i16> zeroinitializer)
  %deinterleave = tail call { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } @llvm.vector.deinterleave4(<vscale x 8 x i16> %bgra)
  %b.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 0
  %b.i64 = zext <vscale x 2 x i16> %b.i16 to <vscale x 2 x i64>
  %add.b.i64 = add <vscale x 2 x i64> %acc.b.i64, %b.i64
  %iv.next = add nuw i64 %iv, %stride
  %ec = icmp eq i64 %iv.next, 2048
  br i1 %ec, label %exit, label %loop

exit:
  store <vscale x 2 x i64> %add.b.i64, ptr %dst
  ret void
}

attributes #0 = { "target-features"="+sve" }
attributes #1 = { "target-features"="+sve" vscale_range(1, 8) }
