; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc < %s -mtriple aarch64 -mattr=+sve -aarch64-disable-sve-gisel=false | FileCheck %s
; RUN: llc < %s -mtriple aarch64 -mattr=+sve -global-isel -aarch64-disable-sve-gisel=false | FileCheck %s

define <vscale x 2 x double> @addnxv2f64(<vscale x 2 x double> %a, <vscale x 2 x double> %b) {
; CHECK-LABEL: addnxv2f64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fadd z0.d, z0.d, z1.d
; CHECK-NEXT:    ret
entry:
  %c = fadd <vscale x 2 x double> %a, %b
  ret <vscale x 2 x double> %c
}

define <vscale x 4 x float> @addnxv4f32(<vscale x 4 x float> %a, <vscale x 4 x float> %b) {
; CHECK-LABEL: addnxv4f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fadd z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %c = fadd <vscale x 4 x float> %a, %b
  ret <vscale x 4 x float> %c
}

define <vscale x 8 x half> @addnxv8f16(<vscale x 8 x half> %a, <vscale x 8 x half> %b) {
; CHECK-LABEL: addnxv8f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fadd z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %c = fadd <vscale x 8 x half> %a, %b
  ret <vscale x 8 x half> %c
}
