; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mattr=+sve2p1,+f64mm | FileCheck %s

target triple = "aarch64-unknown-linux-gnu"

; TODO: To upstream the deinterleave.segments intrinsics, we'll need more tests:
; - Predicate types
; - Illegal types that need splitting like <vscale x 4 x i64>
; - "packed" types like <vscale x 4 x half>


define <vscale x 16 x half> @interleave2_nxv16f16(<vscale x 8 x half> %vec0, <vscale x 8 x half> %vec1) {
; CHECK-LABEL: interleave2_nxv16f16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    zip1 z2.q, z0.q, z1.q
; CHECK-NEXT:    zip2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call <vscale x 16 x half> @llvm.vector.interleave.segments2.nxv16f16(<vscale x 8 x half> %vec0, <vscale x 8 x half> %vec1)
  ret <vscale x 16 x half> %retval
}

define <vscale x 8 x float> @interleave2_nxv8f32(<vscale x 4 x float> %vec0, <vscale x 4 x float> %vec1) {
; CHECK-LABEL: interleave2_nxv8f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    zip1 z2.q, z0.q, z1.q
; CHECK-NEXT:    zip2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call <vscale x 8 x float> @llvm.vector.interleave.segments2.nxv8f32(<vscale x 4 x float> %vec0, <vscale x 4 x float> %vec1)
  ret <vscale x 8 x float> %retval
}

define <vscale x 8 x half> @interleave2_nxv8f16(<vscale x 4 x half> %vec0, <vscale x 4 x half> %vec1) {
; CHECK-LABEL: interleave2_nxv8f16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzpq1 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
  %retval = call <vscale x 8 x half> @llvm.vector.interleave.segments2.nxv8f16(<vscale x 4 x half> %vec0, <vscale x 4 x half> %vec1)
  ret <vscale x 8 x half> %retval
}

define <vscale x 4 x double> @interleave2_nxv4f64(<vscale x 2 x double> %vec0, <vscale x 2 x double> %vec1) {
; CHECK-LABEL: interleave2_nxv4f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    zip1 z2.q, z0.q, z1.q
; CHECK-NEXT:    zip2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call <vscale x 4 x double>@llvm.vector.interleave.segments2.nxv4f64(<vscale x 2 x double> %vec0, <vscale x 2 x double> %vec1)
  ret <vscale x 4 x double> %retval
}

define <vscale x 4 x float> @interleave2_nxv4f32(<vscale x 2 x float> %vec0, <vscale x 2 x float> %vec1) {
; CHECK-LABEL: interleave2_nxv4f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzpq1 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
  %retval = call <vscale x 4 x float> @llvm.vector.interleave.segments2.nxv4f32(<vscale x 2 x float> %vec0, <vscale x 2 x float> %vec1)
  ret <vscale x 4 x float> %retval
}

define <vscale x 16 x bfloat> @interleave2_nxv16bf16(<vscale x 8 x bfloat> %vec0, <vscale x 8 x bfloat> %vec1) {
; CHECK-LABEL: interleave2_nxv16bf16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    zip1 z2.q, z0.q, z1.q
; CHECK-NEXT:    zip2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call <vscale x 16 x bfloat> @llvm.vector.interleave.segments2.nxv16bf16(<vscale x 8 x bfloat> %vec0, <vscale x 8 x bfloat> %vec1)
  ret <vscale x 16 x bfloat> %retval
}

; Integers

define <vscale x 32 x i8> @interleave2_nxv32i8(<vscale x 16 x i8> %vec0, <vscale x 16 x i8> %vec1) {
; CHECK-LABEL: interleave2_nxv32i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    zip1 z2.q, z0.q, z1.q
; CHECK-NEXT:    zip2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call <vscale x 32 x i8> @llvm.vector.interleave.segments2.nxv32i8(<vscale x 16 x i8> %vec0, <vscale x 16 x i8> %vec1)
  ret <vscale x 32 x i8> %retval
}

define <vscale x 16 x i16> @interleave2_nxv16i16(<vscale x 8 x i16> %vec0, <vscale x 8 x i16> %vec1) {
; CHECK-LABEL: interleave2_nxv16i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    zip1 z2.q, z0.q, z1.q
; CHECK-NEXT:    zip2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call <vscale x 16 x i16> @llvm.vector.interleave.segments2.nxv16i16(<vscale x 8 x i16> %vec0, <vscale x 8 x i16> %vec1)
  ret <vscale x 16 x i16> %retval
}

define <vscale x 16 x i8> @interleave2_nxv16i8(<vscale x 8 x i16> %vec0, <vscale x 8 x i16> %vec1) {
; CHECK-LABEL: interleave2_nxv16i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzpq1 z0.b, z0.b, z1.b
; CHECK-NEXT:    ret
  %leg0 = trunc <vscale x 8 x i16> %vec0 to <vscale x 8 x i8>
  %leg1 = trunc <vscale x 8 x i16> %vec1 to <vscale x 8 x i8>
  %retval = call <vscale x 16 x i8> @llvm.vector.interleave.segments2.nxv16i8(<vscale x 8 x i8> %leg0, <vscale x 8 x i8> %leg1)
  ret <vscale x 16 x i8> %retval
}

define <vscale x 8 x i32> @interleave2_nxv8i32(<vscale x 4 x i32> %vec0, <vscale x 4 x i32> %vec1) {
; CHECK-LABEL: interleave2_nxv8i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    zip1 z2.q, z0.q, z1.q
; CHECK-NEXT:    zip2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call <vscale x 8 x i32> @llvm.vector.interleave.segments2.nxv8i32(<vscale x 4 x i32> %vec0, <vscale x 4 x i32> %vec1)
  ret <vscale x 8 x i32> %retval
}

define <vscale x 8 x i16> @interleave2_nxv8i16(<vscale x 4 x i32> %vec0, <vscale x 4 x i32> %vec1) {
; CHECK-LABEL: interleave2_nxv8i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzpq1 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
  %leg0 = trunc <vscale x 4 x i32> %vec0 to <vscale x 4 x i16>
  %leg1 = trunc <vscale x 4 x i32> %vec1 to <vscale x 4 x i16>
  %retval = call <vscale x 8 x i16> @llvm.vector.interleave.segments2.nxv8i16(<vscale x 4 x i16> %leg0, <vscale x 4 x i16> %leg1)
  ret <vscale x 8 x i16> %retval
}

define <vscale x 4 x i64> @interleave2_nxv4i64(<vscale x 2 x i64> %vec0, <vscale x 2 x i64> %vec1) {
; CHECK-LABEL: interleave2_nxv4i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    zip1 z2.q, z0.q, z1.q
; CHECK-NEXT:    zip2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call <vscale x 4 x i64> @llvm.vector.interleave.segments2.nxv4i64(<vscale x 2 x i64> %vec0, <vscale x 2 x i64> %vec1)
  ret <vscale x 4 x i64> %retval
}

define <vscale x 4 x i32> @interleave2_nxv4i32(<vscale x 2 x i64> %vec0, <vscale x 2 x i64> %vec1) {
; CHECK-LABEL: interleave2_nxv4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzpq1 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
  %leg0 = trunc <vscale x 2 x i64> %vec0 to <vscale x 2 x i32>
  %leg1 = trunc <vscale x 2 x i64> %vec1 to <vscale x 2 x i32>
  %retval = call <vscale x 4 x i32> @llvm.vector.interleave.segments2.nxv4i32(<vscale x 2 x i32> %leg0, <vscale x 2 x i32> %leg1)
  ret <vscale x 4 x i32> %retval
}

define <vscale x 64 x i8> @interleave4_nxv16i8(<vscale x 16 x i8> %vec0, <vscale x 16 x i8> %vec1, <vscale x 16 x i8> %vec2, <vscale x 16 x i8> %vec3) {
; CHECK-LABEL: interleave4_nxv16i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    zip1 z4.q, z1.q, z3.q
; CHECK-NEXT:    zip1 z5.q, z0.q, z2.q
; CHECK-NEXT:    zip2 z3.q, z1.q, z3.q
; CHECK-NEXT:    zip2 z6.q, z0.q, z2.q
; CHECK-NEXT:    zip1 z0.q, z5.q, z4.q
; CHECK-NEXT:    zip2 z1.q, z5.q, z4.q
; CHECK-NEXT:    zip1 z2.q, z6.q, z3.q
; CHECK-NEXT:    zip2 z3.q, z6.q, z3.q
; CHECK-NEXT:    ret
  %retval = call <vscale x 64 x i8> @llvm.vector.interleave.segments4.nxv16i8(<vscale x 16 x i8> %vec0, <vscale x 16 x i8> %vec1, <vscale x 16 x i8> %vec2, <vscale x 16 x i8> %vec3)
  ret <vscale x 64 x i8> %retval
}

define <vscale x 32 x i16> @interleave4_nxv8i16(<vscale x 8 x i16> %vec0, <vscale x 8 x i16> %vec1, <vscale x 8 x i16> %vec2, <vscale x 8 x i16> %vec3) {
; CHECK-LABEL: interleave4_nxv8i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    zip1 z4.q, z1.q, z3.q
; CHECK-NEXT:    zip1 z5.q, z0.q, z2.q
; CHECK-NEXT:    zip2 z3.q, z1.q, z3.q
; CHECK-NEXT:    zip2 z6.q, z0.q, z2.q
; CHECK-NEXT:    zip1 z0.q, z5.q, z4.q
; CHECK-NEXT:    zip2 z1.q, z5.q, z4.q
; CHECK-NEXT:    zip1 z2.q, z6.q, z3.q
; CHECK-NEXT:    zip2 z3.q, z6.q, z3.q
; CHECK-NEXT:    ret
  %retval = call <vscale x 32 x i16> @llvm.vector.interleave.segments4.nxv32i16(<vscale x 8 x i16> %vec0, <vscale x 8 x i16> %vec1, <vscale x 8 x i16> %vec2, <vscale x 8 x i16> %vec3)
  ret <vscale x 32 x i16> %retval
}

define <vscale x 16 x i32> @interleave4_nxv4i32(<vscale x 4 x i32> %vec0, <vscale x 4 x i32> %vec1, <vscale x 4 x i32> %vec2, <vscale x 4 x i32> %vec3) {
; CHECK-LABEL: interleave4_nxv4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    zip1 z4.q, z1.q, z3.q
; CHECK-NEXT:    zip1 z5.q, z0.q, z2.q
; CHECK-NEXT:    zip2 z3.q, z1.q, z3.q
; CHECK-NEXT:    zip2 z6.q, z0.q, z2.q
; CHECK-NEXT:    zip1 z0.q, z5.q, z4.q
; CHECK-NEXT:    zip2 z1.q, z5.q, z4.q
; CHECK-NEXT:    zip1 z2.q, z6.q, z3.q
; CHECK-NEXT:    zip2 z3.q, z6.q, z3.q
; CHECK-NEXT:    ret
  %retval = call <vscale x 16 x i32> @llvm.vector.interleave.segments4.nxv4i32(<vscale x 4 x i32> %vec0, <vscale x 4 x i32> %vec1, <vscale x 4 x i32> %vec2, <vscale x 4 x i32> %vec3)
  ret <vscale x 16 x i32> %retval
}

define <vscale x 8 x i64> @interleave4_nxv8i64(<vscale x 2 x i64> %vec0, <vscale x 2 x i64> %vec1, <vscale x 2 x i64> %vec2, <vscale x 2 x i64> %vec3) {
; CHECK-LABEL: interleave4_nxv8i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    zip1 z4.q, z1.q, z3.q
; CHECK-NEXT:    zip1 z5.q, z0.q, z2.q
; CHECK-NEXT:    zip2 z3.q, z1.q, z3.q
; CHECK-NEXT:    zip2 z6.q, z0.q, z2.q
; CHECK-NEXT:    zip1 z0.q, z5.q, z4.q
; CHECK-NEXT:    zip2 z1.q, z5.q, z4.q
; CHECK-NEXT:    zip1 z2.q, z6.q, z3.q
; CHECK-NEXT:    zip2 z3.q, z6.q, z3.q
; CHECK-NEXT:    ret
  %retval = call <vscale x 8 x i64> @llvm.vector.interleave.segments4.nxv8i64(<vscale x 2 x i64> %vec0, <vscale x 2 x i64> %vec1, <vscale x 2 x i64> %vec2, <vscale x 2 x i64> %vec3)
  ret <vscale x 8 x i64> %retval
}

; define <vscale x 4 x half> @interleave2_nxv4f16(<vscale x 2 x half> %vec0, <vscale x 2 x half> %vec1) {
;   %retval = call <vscale x 4 x half> @llvm.vector.interleave.segments2.nxv4f16(<vscale x 2 x half> %vec0, <vscale x 2 x half> %vec1)
;   ret <vscale x 4 x half> %retval
; }

; define <vscale x 8 x half> @interleave2_nxv8f16(<vscale x 4 x half> %vec0, <vscale x 4 x half> %vec1) {
;   %retval = call <vscale x 8 x half> @llvm.vector.interleave.segments2.nxv8f16(<vscale x 4 x half> %vec0, <vscale x 4 x half> %vec1)
;   ret <vscale x 8 x half> %retval
; }

; define <vscale x 4 x float> @interleave2_nxv4f32(<vscale x 2 x float> %vec0, <vscale x 2 x float> %vec1) {
;   %retval = call <vscale x 4 x float> @llvm.vector.interleave.segments2.nxv4f32(<vscale x 2 x float> %vec0, <vscale x 2 x float> %vec1)
;   ret <vscale x 4 x float> %retval
; }

; define <vscale x 4 x bfloat> @interleave2_nxv4bf16(<vscale x 2 x bfloat> %vec0, <vscale x 2 x bfloat> %vec1) {
;   %retval = call <vscale x 4 x bfloat> @llvm.vector.interleave.segments2.nxv4bf16(<vscale x 2 x bfloat> %vec0, <vscale x 2 x bfloat> %vec1)
;   ret <vscale x 4 x bfloat> %retval
; }

; define <vscale x 8 x bfloat> @interleave2_nxv8bf16(<vscale x 4 x bfloat> %vec0, <vscale x 4 x bfloat> %vec1) {
;   %retval = call <vscale x 8 x bfloat> @llvm.vector.interleave.segments2.nxv8bf16(<vscale x 4 x bfloat> %vec0, <vscale x 4 x bfloat> %vec1)
;   ret <vscale x 8 x bfloat> %retval
; }
