; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve2p1 -enable-subreg-liveness=true < %s | FileCheck %s

;; Normal multi-vector loads/stores:

define void @store_2x_vectors_offset_mul_vl(<vscale x 16 x i8> %zn0, <vscale x 16 x i8> %zn1, target("aarch64.svcount") %pn, ptr %addr) nounwind {
; CHECK-LABEL: store_2x_vectors_offset_mul_vl:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    str p8, [sp, #7, mul vl] // 2-byte Spill
; CHECK-NEXT:    mov p8.b, p0.b
; CHECK-NEXT:    st1b { z0.b, z1.b }, pn8, [x0, #14, mul vl]
; CHECK-NEXT:    ldr p8, [sp, #7, mul vl] // 2-byte Reload
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %vscale = call i64 @llvm.vscale.i64()
  %offset.addr = getelementptr <vscale x 16 x i8>, ptr %addr, i64 14
  call void @llvm.aarch64.sve.st1.pn.x2.nxv16i8(<vscale x 16 x i8> %zn0, <vscale x 16 x i8> %zn1, target("aarch64.svcount") %pn, ptr %offset.addr)
  ret void
}

define void @store_4x_vectors_offset_mul_vl(<vscale x 16 x i8> %zn0, <vscale x 16 x i8> %zn1, <vscale x 16 x i8> %zn2, <vscale x 16 x i8> %zn3, target("aarch64.svcount") %pn, ptr %addr) nounwind {
; CHECK-LABEL: store_4x_vectors_offset_mul_vl:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    str p8, [sp, #7, mul vl] // 2-byte Spill
; CHECK-NEXT:    mov p8.b, p0.b
; CHECK-NEXT:    st1b { z0.b - z3.b }, pn8, [x0, #28, mul vl]
; CHECK-NEXT:    ldr p8, [sp, #7, mul vl] // 2-byte Reload
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %vscale = call i64 @llvm.vscale.i64()
  %offset.addr = getelementptr <vscale x 16 x i8>, ptr %addr, i64 28
  call void @llvm.aarch64.sve.st1.pn.x4.nxv16i8(<vscale x 16 x i8> %zn0, <vscale x 16 x i8> %zn1, <vscale x 16 x i8> %zn2, <vscale x 16 x i8> %zn3, target("aarch64.svcount") %pn, ptr %offset.addr)
  ret void
}

define { <vscale x 16 x i8>, <vscale x 16 x i8> } @load_x2_vectors_offset_mul_vl(target("aarch64.svcount") %pn, ptr %addr) nounwind {
; CHECK-LABEL: load_x2_vectors_offset_mul_vl:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    str p8, [sp, #7, mul vl] // 2-byte Spill
; CHECK-NEXT:    mov p8.b, p0.b
; CHECK-NEXT:    ld1b { z0.b, z1.b }, pn8/z, [x0, #-2, mul vl]
; CHECK-NEXT:    ldr p8, [sp, #7, mul vl] // 2-byte Reload
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %vscale = call i64 @llvm.vscale.i64()
  %offset.addr = getelementptr <vscale x 16 x i8>, ptr %addr, i64 -2
  %res = call { <vscale x 16 x i8>, <vscale x 16 x i8> } @llvm.aarch64.sve.ld1.pn.x2.nxv16i8(target("aarch64.svcount") %pn, ptr %offset.addr);
  ret { <vscale x 16 x i8>, <vscale x 16 x i8> } %res
}

define { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8> } @load_x4_vectors_offset_mul_vl(target("aarch64.svcount") %pn, ptr %addr) nounwind {
; CHECK-LABEL: load_x4_vectors_offset_mul_vl:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    str p8, [sp, #7, mul vl] // 2-byte Spill
; CHECK-NEXT:    mov p8.b, p0.b
; CHECK-NEXT:    ld1b { z0.b - z3.b }, pn8/z, [x0, #-4, mul vl]
; CHECK-NEXT:    ldr p8, [sp, #7, mul vl] // 2-byte Reload
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %vscale = call i64 @llvm.vscale.i64()
  %offset.addr = getelementptr <vscale x 16 x i8>, ptr %addr, i64 -4
  %res = call { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8> } @llvm.aarch64.sve.ld1.pn.x4.nxv16i8(target("aarch64.svcount") %pn, ptr %offset.addr);
  ret { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8> } %res
}

;; Non-temporal multi-vector loads/stores:

define void @store_2x_vectors_offset_mul_vl_nt(<vscale x 16 x i8> %zn0, <vscale x 16 x i8> %zn1, target("aarch64.svcount") %pn, ptr %addr) nounwind {
; CHECK-LABEL: store_2x_vectors_offset_mul_vl_nt:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    str p8, [sp, #7, mul vl] // 2-byte Spill
; CHECK-NEXT:    mov p8.b, p0.b
; CHECK-NEXT:    stnt1b { z0.b, z1.b }, pn8, [x0, #14, mul vl]
; CHECK-NEXT:    ldr p8, [sp, #7, mul vl] // 2-byte Reload
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %vscale = call i64 @llvm.vscale.i64()
  %offset.addr = getelementptr <vscale x 16 x i8>, ptr %addr, i64 14
  call void @llvm.aarch64.sve.stnt1.pn.x2.nxv16i8(<vscale x 16 x i8> %zn0, <vscale x 16 x i8> %zn1, target("aarch64.svcount") %pn, ptr %offset.addr)
  ret void
}

define void @store_4x_vectors_offset_mul_vl_nt(<vscale x 16 x i8> %zn0, <vscale x 16 x i8> %zn1, <vscale x 16 x i8> %zn2, <vscale x 16 x i8> %zn3, target("aarch64.svcount") %pn, ptr %addr) nounwind {
; CHECK-LABEL: store_4x_vectors_offset_mul_vl_nt:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    str p8, [sp, #7, mul vl] // 2-byte Spill
; CHECK-NEXT:    mov p8.b, p0.b
; CHECK-NEXT:    stnt1b { z0.b - z3.b }, pn8, [x0, #28, mul vl]
; CHECK-NEXT:    ldr p8, [sp, #7, mul vl] // 2-byte Reload
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %vscale = call i64 @llvm.vscale.i64()
  %offset.addr = getelementptr <vscale x 16 x i8>, ptr %addr, i64 28
  call void @llvm.aarch64.sve.stnt1.pn.x4.nxv16i8(<vscale x 16 x i8> %zn0, <vscale x 16 x i8> %zn1, <vscale x 16 x i8> %zn2, <vscale x 16 x i8> %zn3, target("aarch64.svcount") %pn, ptr %offset.addr)
  ret void
}

define { <vscale x 16 x i8>, <vscale x 16 x i8> } @load_x2_vectors_offset_mul_vl_nt(target("aarch64.svcount") %pn, ptr %addr) nounwind {
; CHECK-LABEL: load_x2_vectors_offset_mul_vl_nt:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    str p8, [sp, #7, mul vl] // 2-byte Spill
; CHECK-NEXT:    mov p8.b, p0.b
; CHECK-NEXT:    ldnt1b { z0.b, z1.b }, pn8/z, [x0, #-2, mul vl]
; CHECK-NEXT:    ldr p8, [sp, #7, mul vl] // 2-byte Reload
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %vscale = call i64 @llvm.vscale.i64()
  %offset.addr = getelementptr <vscale x 16 x i8>, ptr %addr, i64 -2
  %res = call { <vscale x 16 x i8>, <vscale x 16 x i8> } @llvm.aarch64.sve.ldnt1.pn.x2.nxv16i8(target("aarch64.svcount") %pn, ptr %offset.addr);
  ret { <vscale x 16 x i8>, <vscale x 16 x i8> } %res
}

define { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8> } @load_x4_vectors_offset_mul_vl_nt(target("aarch64.svcount") %pn, ptr %addr) nounwind {
; CHECK-LABEL: load_x4_vectors_offset_mul_vl_nt:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    str p8, [sp, #7, mul vl] // 2-byte Spill
; CHECK-NEXT:    mov p8.b, p0.b
; CHECK-NEXT:    ldnt1b { z0.b - z3.b }, pn8/z, [x0, #-4, mul vl]
; CHECK-NEXT:    ldr p8, [sp, #7, mul vl] // 2-byte Reload
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %vscale = call i64 @llvm.vscale.i64()
  %offset.addr = getelementptr <vscale x 16 x i8>, ptr %addr, i64 -4
  %res = call { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8> } @llvm.aarch64.sve.ldnt1.pn.x4.nxv16i8(target("aarch64.svcount") %pn, ptr %offset.addr);
  ret { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8> } %res
}
