; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -enable-subreg-liveness -mattr=+sve,+bf16 -force-streaming-compatible  < %s | FileCheck %s
; RUN: llc -enable-subreg-liveness -mattr=+sme,+bf16 -force-streaming  < %s | FileCheck %s
; RUN: llc -enable-subreg-liveness -mattr=+bf16 -force-streaming-compatible < %s | FileCheck %s --check-prefix=NONEON-NOSVE

target triple = "aarch64-unknown-linux-gnu"

;
; Partial reduce (BFMLALT/B)
;

define <4 x float> @partial_reduce_to_v4f32(<4 x float> %acc, <8 x bfloat> %a, <8 x bfloat> %b) {
; CHECK-LABEL: partial_reduce_to_v4f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uunpklo z3.s, z1.h
; CHECK-NEXT:    stp q1, q2, [sp, #-32]!
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    uunpklo z1.s, z2.h
; CHECK-NEXT:    ldr d4, [sp, #8]
; CHECK-NEXT:    ldr d2, [sp, #24]
; CHECK-NEXT:    lsl z3.s, z3.s, #16
; CHECK-NEXT:    ptrue p0.s, vl4
; CHECK-NEXT:    uunpklo z4.s, z4.h
; CHECK-NEXT:    uunpklo z2.s, z2.h
; CHECK-NEXT:    lsl z1.s, z1.s, #16
; CHECK-NEXT:    lsl z2.s, z2.s, #16
; CHECK-NEXT:    fmul z1.s, p0/m, z1.s, z3.s
; CHECK-NEXT:    lsl z3.s, z4.s, #16
; CHECK-NEXT:    fmul z2.s, p0/m, z2.s, z3.s
; CHECK-NEXT:    fadd z0.s, p0/m, z0.s, z1.s
; CHECK-NEXT:    fadd z0.s, p0/m, z0.s, z2.s
; CHECK-NEXT:    add sp, sp, #32
; CHECK-NEXT:    ret
;
; NONEON-NOSVE-LABEL: partial_reduce_to_v4f32:
; NONEON-NOSVE:       // %bb.0: // %entry
; NONEON-NOSVE-NEXT:    stp q1, q2, [sp, #-96]!
; NONEON-NOSVE-NEXT:    .cfi_def_cfa_offset 96
; NONEON-NOSVE-NEXT:    ldp d2, d1, [sp]
; NONEON-NOSVE-NEXT:    str q0, [sp, #32]
; NONEON-NOSVE-NEXT:    ldr s0, [sp, #44]
; NONEON-NOSVE-NEXT:    stp d1, d2, [sp, #48]
; NONEON-NOSVE-NEXT:    ldr d2, [sp, #16]
; NONEON-NOSVE-NEXT:    ldr h16, [sp, #62]
; NONEON-NOSVE-NEXT:    ldr h17, [sp, #54]
; NONEON-NOSVE-NEXT:    ldr h7, [sp, #60]
; NONEON-NOSVE-NEXT:    str d2, [sp, #72]
; NONEON-NOSVE-NEXT:    ldr d2, [sp, #24]
; NONEON-NOSVE-NEXT:    ldr h6, [sp, #52]
; NONEON-NOSVE-NEXT:    fmov w8, s16
; NONEON-NOSVE-NEXT:    ldr h5, [sp, #58]
; NONEON-NOSVE-NEXT:    ldr h19, [sp, #74]
; NONEON-NOSVE-NEXT:    str d2, [sp, #64]
; NONEON-NOSVE-NEXT:    ldr h2, [sp, #78]
; NONEON-NOSVE-NEXT:    ldr h4, [sp, #50]
; NONEON-NOSVE-NEXT:    ldr h18, [sp, #68]
; NONEON-NOSVE-NEXT:    ldr h20, [sp, #66]
; NONEON-NOSVE-NEXT:    ldr h3, [sp, #56]
; NONEON-NOSVE-NEXT:    fmov w9, s2
; NONEON-NOSVE-NEXT:    lsl w8, w8, #16
; NONEON-NOSVE-NEXT:    ldr h2, [sp, #70]
; NONEON-NOSVE-NEXT:    ldr h1, [sp, #48]
; NONEON-NOSVE-NEXT:    ldr h21, [sp, #64]
; NONEON-NOSVE-NEXT:    fmov s16, w8
; NONEON-NOSVE-NEXT:    fmov w8, s17
; NONEON-NOSVE-NEXT:    lsl w9, w9, #16
; NONEON-NOSVE-NEXT:    fmov s17, w9
; NONEON-NOSVE-NEXT:    fmov w9, s2
; NONEON-NOSVE-NEXT:    lsl w8, w8, #16
; NONEON-NOSVE-NEXT:    ldr h2, [sp, #76]
; NONEON-NOSVE-NEXT:    fmov s22, w8
; NONEON-NOSVE-NEXT:    fmov w8, s7
; NONEON-NOSVE-NEXT:    lsl w9, w9, #16
; NONEON-NOSVE-NEXT:    fmul s16, s16, s17
; NONEON-NOSVE-NEXT:    ldr h17, [sp, #72]
; NONEON-NOSVE-NEXT:    fmov s23, w9
; NONEON-NOSVE-NEXT:    fmov w9, s2
; NONEON-NOSVE-NEXT:    lsl w8, w8, #16
; NONEON-NOSVE-NEXT:    fadd s0, s0, s16
; NONEON-NOSVE-NEXT:    fmov s2, w8
; NONEON-NOSVE-NEXT:    fmov w8, s6
; NONEON-NOSVE-NEXT:    lsl w9, w9, #16
; NONEON-NOSVE-NEXT:    fmul s22, s22, s23
; NONEON-NOSVE-NEXT:    fmov s7, w9
; NONEON-NOSVE-NEXT:    fmov w9, s18
; NONEON-NOSVE-NEXT:    lsl w8, w8, #16
; NONEON-NOSVE-NEXT:    fadd s0, s0, s22
; NONEON-NOSVE-NEXT:    fmov s6, w8
; NONEON-NOSVE-NEXT:    fmov w8, s5
; NONEON-NOSVE-NEXT:    lsl w9, w9, #16
; NONEON-NOSVE-NEXT:    fmul s2, s2, s7
; NONEON-NOSVE-NEXT:    fmov s7, w9
; NONEON-NOSVE-NEXT:    fmov w9, s19
; NONEON-NOSVE-NEXT:    lsl w8, w8, #16
; NONEON-NOSVE-NEXT:    str s0, [sp, #92]
; NONEON-NOSVE-NEXT:    ldr s0, [sp, #40]
; NONEON-NOSVE-NEXT:    lsl w9, w9, #16
; NONEON-NOSVE-NEXT:    fadd s0, s0, s2
; NONEON-NOSVE-NEXT:    fmov s2, w8
; NONEON-NOSVE-NEXT:    fmov w8, s4
; NONEON-NOSVE-NEXT:    fmul s6, s6, s7
; NONEON-NOSVE-NEXT:    fmov s5, w9
; NONEON-NOSVE-NEXT:    fmov w9, s20
; NONEON-NOSVE-NEXT:    lsl w8, w8, #16
; NONEON-NOSVE-NEXT:    lsl w9, w9, #16
; NONEON-NOSVE-NEXT:    fmul s2, s2, s5
; NONEON-NOSVE-NEXT:    fadd s7, s0, s6
; NONEON-NOSVE-NEXT:    fmov s4, w8
; NONEON-NOSVE-NEXT:    fmov w8, s3
; NONEON-NOSVE-NEXT:    ldr s0, [sp, #36]
; NONEON-NOSVE-NEXT:    fmov s5, w9
; NONEON-NOSVE-NEXT:    fmov w9, s17
; NONEON-NOSVE-NEXT:    fadd s0, s0, s2
; NONEON-NOSVE-NEXT:    lsl w8, w8, #16
; NONEON-NOSVE-NEXT:    fmul s4, s4, s5
; NONEON-NOSVE-NEXT:    lsl w9, w9, #16
; NONEON-NOSVE-NEXT:    fmov s2, w8
; NONEON-NOSVE-NEXT:    fmov w8, s1
; NONEON-NOSVE-NEXT:    fmov s3, w9
; NONEON-NOSVE-NEXT:    fmov w9, s21
; NONEON-NOSVE-NEXT:    fadd s0, s0, s4
; NONEON-NOSVE-NEXT:    lsl w8, w8, #16
; NONEON-NOSVE-NEXT:    lsl w9, w9, #16
; NONEON-NOSVE-NEXT:    fmul s1, s2, s3
; NONEON-NOSVE-NEXT:    fmov s2, w8
; NONEON-NOSVE-NEXT:    fmov s3, w9
; NONEON-NOSVE-NEXT:    stp s0, s7, [sp, #84]
; NONEON-NOSVE-NEXT:    ldr s0, [sp, #32]
; NONEON-NOSVE-NEXT:    fmul s2, s2, s3
; NONEON-NOSVE-NEXT:    fadd s0, s0, s1
; NONEON-NOSVE-NEXT:    fadd s0, s0, s2
; NONEON-NOSVE-NEXT:    str s0, [sp, #80]
; NONEON-NOSVE-NEXT:    ldr q0, [sp, #80]
; NONEON-NOSVE-NEXT:    add sp, sp, #96
; NONEON-NOSVE-NEXT:    ret
entry:
  %a.wide = fpext <8 x bfloat> %a to <8 x float>
  %b.wide = fpext <8 x bfloat> %b to <8 x float>
  %mult = fmul <8 x float> %a.wide, %b.wide
  %partial.reduce = call <4 x float> @llvm.vector.partial.reduce.fadd(<4 x float> %acc, <8 x float> %mult)
  ret <4 x float> %partial.reduce
}
