; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=+sve,+bf16 < %s | FileCheck %s

target triple = "aarch64-unknown-linux-gnu"

define bfloat @fadd_ordered_nxv2bf16(bfloat %a, <vscale x 2 x bfloat> %b) {
; CHECK-LABEL: fadd_ordered_nxv2bf16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $h0 killed $h0 def $d0
; CHECK-NEXT:    lsl z1.s, z1.s, #16
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    shll v0.4s, v0.4h, #16
; CHECK-NEXT:    fadda s0, p0, s0, z1.s
; CHECK-NEXT:    bfcvt h0, s0
; CHECK-NEXT:    ret
  %res = call bfloat @llvm.vector.reduce.fadd(bfloat %a, <vscale x 2 x bfloat> %b)
  ret bfloat %res
}

define bfloat @fadd_ordered_nxv4bf16(bfloat %a, <vscale x 4 x bfloat> %b) {
; CHECK-LABEL: fadd_ordered_nxv4bf16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $h0 killed $h0 def $d0
; CHECK-NEXT:    lsl z1.s, z1.s, #16
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    shll v0.4s, v0.4h, #16
; CHECK-NEXT:    fadda s0, p0, s0, z1.s
; CHECK-NEXT:    bfcvt h0, s0
; CHECK-NEXT:    ret
  %res = call bfloat @llvm.vector.reduce.fadd(bfloat %a, <vscale x 4 x bfloat> %b)
  ret bfloat %res
}

define bfloat @fadd_ordered_nxv8bf16(bfloat %a, <vscale x 8 x bfloat> %b) {
; CHECK-LABEL: fadd_ordered_nxv8bf16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    movi v2.2d, #0000000000000000
; CHECK-NEXT:    // kill: def $h0 killed $h0 def $d0
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    shll v0.4s, v0.4h, #16
; CHECK-NEXT:    zip1 z3.h, z2.h, z1.h
; CHECK-NEXT:    zip2 z1.h, z2.h, z1.h
; CHECK-NEXT:    fadda s0, p0, s0, z3.s
; CHECK-NEXT:    fadda s0, p0, s0, z1.s
; CHECK-NEXT:    bfcvt h0, s0
; CHECK-NEXT:    ret
  %res = call bfloat @llvm.vector.reduce.fadd(bfloat %a, <vscale x 8 x bfloat> %b)
  ret bfloat %res
}
