; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -O3 < %s | FileCheck %s

target triple = "aarch64"

; Check the backend lowering for factor-4 deinterleave when the result
; sub-vectors are smaller than the interleave factor.

define void @deinterleave4_nxv8i16_uitofp_f64(<vscale x 8 x i16> %wide.vec, <vscale x 2 x double> %mul, ptr %out) #0 {
; CHECK-LABEL: deinterleave4_nxv8i16_uitofp_f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uunpkhi z2.s, z0.h
; CHECK-NEXT:    uunpklo z0.s, z0.h
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    movi d7, #0000000000000000
; CHECK-NEXT:    uunpkhi z3.d, z2.s
; CHECK-NEXT:    uunpklo z2.d, z2.s
; CHECK-NEXT:    uunpkhi z4.d, z0.s
; CHECK-NEXT:    uunpklo z0.d, z0.s
; CHECK-NEXT:    uzp1 z5.d, z2.d, z3.d
; CHECK-NEXT:    uzp2 z2.d, z2.d, z3.d
; CHECK-NEXT:    uzp1 z6.d, z0.d, z4.d
; CHECK-NEXT:    uzp2 z0.d, z0.d, z4.d
; CHECK-NEXT:    uzp1 z3.d, z6.d, z5.d
; CHECK-NEXT:    uzp1 z4.d, z0.d, z2.d
; CHECK-NEXT:    uzp2 z5.d, z6.d, z5.d
; CHECK-NEXT:    uzp2 z0.d, z0.d, z2.d
; CHECK-NEXT:    movi d2, #0000000000000000
; CHECK-NEXT:    movi d6, #0000000000000000
; CHECK-NEXT:    and z3.d, z3.d, #0xffff
; CHECK-NEXT:    and z4.d, z4.d, #0xffff
; CHECK-NEXT:    and z5.d, z5.d, #0xffff
; CHECK-NEXT:    and z0.d, z0.d, #0xffff
; CHECK-NEXT:    ucvtf z3.d, p0/m, z3.d
; CHECK-NEXT:    ucvtf z4.d, p0/m, z4.d
; CHECK-NEXT:    ucvtf z5.d, p0/m, z5.d
; CHECK-NEXT:    ucvtf z0.d, p0/m, z0.d
; CHECK-NEXT:    fmul z3.d, z1.d, z3.d
; CHECK-NEXT:    fmul z4.d, z1.d, z4.d
; CHECK-NEXT:    fmul z5.d, z1.d, z5.d
; CHECK-NEXT:    fmul z0.d, z1.d, z0.d
; CHECK-NEXT:    movi d1, #0000000000000000
; CHECK-NEXT:    fadda d2, p0, d2, z3.d
; CHECK-NEXT:    fadda d6, p0, d6, z4.d
; CHECK-NEXT:    fadda d7, p0, d7, z5.d
; CHECK-NEXT:    fadda d1, p0, d1, z0.d
; CHECK-NEXT:    mov v2.d[1], v6.d[0]
; CHECK-NEXT:    mov v7.d[1], v1.d[0]
; CHECK-NEXT:    stp q2, q7, [x0]
; CHECK-NEXT:    ret
  %d = call { <vscale x 2 x i16>, <vscale x 2 x i16>,
              <vscale x 2 x i16>, <vscale x 2 x i16> }
       @llvm.vector.deinterleave4.nxv8i16(<vscale x 8 x i16> %wide.vec)
  %b = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>,
                      <vscale x 2 x i16>, <vscale x 2 x i16> } %d, 0
  %g = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>,
                      <vscale x 2 x i16>, <vscale x 2 x i16> } %d, 1
  %r = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>,
                      <vscale x 2 x i16>, <vscale x 2 x i16> } %d, 2
  %a = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>,
                      <vscale x 2 x i16>, <vscale x 2 x i16> } %d, 3
  %fb = uitofp <vscale x 2 x i16> %b to <vscale x 2 x double>
  %fg = uitofp <vscale x 2 x i16> %g to <vscale x 2 x double>
  %fr = uitofp <vscale x 2 x i16> %r to <vscale x 2 x double>
  %fa = uitofp <vscale x 2 x i16> %a to <vscale x 2 x double>
  %mb = fmul <vscale x 2 x double> %mul, %fb
  %mg = fmul <vscale x 2 x double> %mul, %fg
  %mr = fmul <vscale x 2 x double> %mul, %fr
  %ma = fmul <vscale x 2 x double> %mul, %fa
  %sb = call double @llvm.vector.reduce.fadd.nxv2f64(double 0.0, <vscale x 2 x double> %mb)
  %sg = call double @llvm.vector.reduce.fadd.nxv2f64(double 0.0, <vscale x 2 x double> %mg)
  %sr = call double @llvm.vector.reduce.fadd.nxv2f64(double 0.0, <vscale x 2 x double> %mr)
  %sa = call double @llvm.vector.reduce.fadd.nxv2f64(double 0.0, <vscale x 2 x double> %ma)
  store double %sb, ptr %out, align 8
  %out.1 = getelementptr inbounds double, ptr %out, i64 1
  store double %sg, ptr %out.1, align 8
  %out.2 = getelementptr inbounds double, ptr %out, i64 2
  store double %sr, ptr %out.2, align 8
  %out.3 = getelementptr inbounds double, ptr %out, i64 3
  store double %sa, ptr %out.3, align 8
  ret void
}


define void @deinterleave4_nxv8i16_zext_i64(<vscale x 8 x i16> %wide.vec, ptr %out) #0 {
; CHECK-LABEL: deinterleave4_nxv8i16_zext_i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uunpkhi z1.s, z0.h
; CHECK-NEXT:    uunpklo z0.s, z0.h
; CHECK-NEXT:    uunpkhi z2.d, z1.s
; CHECK-NEXT:    uunpklo z1.d, z1.s
; CHECK-NEXT:    uunpkhi z3.d, z0.s
; CHECK-NEXT:    uunpklo z0.d, z0.s
; CHECK-NEXT:    uzp1 z4.d, z1.d, z2.d
; CHECK-NEXT:    uzp2 z1.d, z1.d, z2.d
; CHECK-NEXT:    uzp1 z5.d, z0.d, z3.d
; CHECK-NEXT:    uzp2 z0.d, z0.d, z3.d
; CHECK-NEXT:    uzp1 z2.d, z5.d, z4.d
; CHECK-NEXT:    uzp1 z3.d, z0.d, z1.d
; CHECK-NEXT:    uzp2 z4.d, z5.d, z4.d
; CHECK-NEXT:    uzp2 z0.d, z0.d, z1.d
; CHECK-NEXT:    and z2.d, z2.d, #0xffff
; CHECK-NEXT:    and z3.d, z3.d, #0xffff
; CHECK-NEXT:    and z4.d, z4.d, #0xffff
; CHECK-NEXT:    and z0.d, z0.d, #0xffff
; CHECK-NEXT:    str z2, [x0]
; CHECK-NEXT:    str z3, [x0, #1, mul vl]
; CHECK-NEXT:    str z4, [x0, #2, mul vl]
; CHECK-NEXT:    str z0, [x0, #3, mul vl]
; CHECK-NEXT:    ret
  %d = call { <vscale x 2 x i16>, <vscale x 2 x i16>,
              <vscale x 2 x i16>, <vscale x 2 x i16> }
       @llvm.vector.deinterleave4.nxv8i16(<vscale x 8 x i16> %wide.vec)
  %b = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>,
                      <vscale x 2 x i16>, <vscale x 2 x i16> } %d, 0
  %g = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>,
                      <vscale x 2 x i16>, <vscale x 2 x i16> } %d, 1
  %r = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>,
                      <vscale x 2 x i16>, <vscale x 2 x i16> } %d, 2
  %a = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>,
                      <vscale x 2 x i16>, <vscale x 2 x i16> } %d, 3
  %eb = zext <vscale x 2 x i16> %b to <vscale x 2 x i64>
  %eg = zext <vscale x 2 x i16> %g to <vscale x 2 x i64>
  %er = zext <vscale x 2 x i16> %r to <vscale x 2 x i64>
  %ea = zext <vscale x 2 x i16> %a to <vscale x 2 x i64>
  store <vscale x 2 x i64> %eb, ptr %out, align 8
  %out.1 = getelementptr inbounds <vscale x 2 x i64>, ptr %out, i64 1
  store <vscale x 2 x i64> %eg, ptr %out.1, align 8
  %out.2 = getelementptr inbounds <vscale x 2 x i64>, ptr %out, i64 2
  store <vscale x 2 x i64> %er, ptr %out.2, align 8
  %out.3 = getelementptr inbounds <vscale x 2 x i64>, ptr %out, i64 3
  store <vscale x 2 x i64> %ea, ptr %out.3, align 8
  ret void
}

; Shuffle optimization pass should be used for the in loop
; test and replace uunpk/uzp with tbl shuffles.

define void @deinterleave4_nxv8i16_zext_i64_in_loop(ptr noalias %in, ptr noalias %out, i64 %n) #0 {
; CHECK-LABEL: deinterleave4_nxv8i16_zext_i64_in_loop:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    index z7.d, #0, #4
; CHECK-NEXT:    mov z4.d, #0xffffffffffff0000
; CHECK-NEXT:    mov z5.d, #0xffffffffffff0001
; CHECK-NEXT:    mov x9, #-65534 // =0xffffffffffff0002
; CHECK-NEXT:    mov z16.d, #0xffffffffffff0003
; CHECK-NEXT:    movi v0.2d, #0000000000000000
; CHECK-NEXT:    mov z6.d, x9
; CHECK-NEXT:    movi v1.2d, #0000000000000000
; CHECK-NEXT:    mov x8, xzr
; CHECK-NEXT:    movi v2.2d, #0000000000000000
; CHECK-NEXT:    movi v3.2d, #0000000000000000
; CHECK-NEXT:    cnth x9
; CHECK-NEXT:    add z4.d, z7.d, z4.d
; CHECK-NEXT:    add z5.d, z7.d, z5.d
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    add z6.d, z7.d, z6.d
; CHECK-NEXT:    add z7.d, z7.d, z16.d
; CHECK-NEXT:  .LBB2_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ld1h { z16.h }, p0/z, [x0, x8, lsl #1]
; CHECK-NEXT:    add x8, x8, x9
; CHECK-NEXT:    cmp x8, x2
; CHECK-NEXT:    tbl z17.h, { z16.h }, z4.h
; CHECK-NEXT:    tbl z18.h, { z16.h }, z5.h
; CHECK-NEXT:    tbl z19.h, { z16.h }, z6.h
; CHECK-NEXT:    tbl z16.h, { z16.h }, z7.h
; CHECK-NEXT:    add z0.d, z0.d, z17.d
; CHECK-NEXT:    add z1.d, z1.d, z18.d
; CHECK-NEXT:    add z2.d, z2.d, z19.d
; CHECK-NEXT:    add z3.d, z3.d, z16.d
; CHECK-NEXT:    b.lo .LBB2_1
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    str z0, [x1]
; CHECK-NEXT:    str z1, [x1, #1, mul vl]
; CHECK-NEXT:    str z2, [x1, #2, mul vl]
; CHECK-NEXT:    str z3, [x1, #3, mul vl]
; CHECK-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %acc.b = phi <vscale x 2 x i64> [ zeroinitializer, %entry ], [ %add.b, %loop ]
  %acc.g = phi <vscale x 2 x i64> [ zeroinitializer, %entry ], [ %add.g, %loop ]
  %acc.r = phi <vscale x 2 x i64> [ zeroinitializer, %entry ], [ %add.r, %loop ]
  %acc.a = phi <vscale x 2 x i64> [ zeroinitializer, %entry ], [ %add.a, %loop ]
  %gep = getelementptr inbounds i16, ptr %in, i64 %iv
  %wide.vec = load <vscale x 8 x i16>, ptr %gep, align 2
  %d = call { <vscale x 2 x i16>, <vscale x 2 x i16>,
              <vscale x 2 x i16>, <vscale x 2 x i16> }
       @llvm.vector.deinterleave4.nxv8i16(<vscale x 8 x i16> %wide.vec)
  %b = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>,
                      <vscale x 2 x i16>, <vscale x 2 x i16> } %d, 0
  %g = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>,
                      <vscale x 2 x i16>, <vscale x 2 x i16> } %d, 1
  %r = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>,
                      <vscale x 2 x i16>, <vscale x 2 x i16> } %d, 2
  %a = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>,
                      <vscale x 2 x i16>, <vscale x 2 x i16> } %d, 3
  %eb = zext <vscale x 2 x i16> %b to <vscale x 2 x i64>
  %eg = zext <vscale x 2 x i16> %g to <vscale x 2 x i64>
  %er = zext <vscale x 2 x i16> %r to <vscale x 2 x i64>
  %ea = zext <vscale x 2 x i16> %a to <vscale x 2 x i64>
  %add.b = add <vscale x 2 x i64> %acc.b, %eb
  %add.g = add <vscale x 2 x i64> %acc.g, %eg
  %add.r = add <vscale x 2 x i64> %acc.r, %er
  %add.a = add <vscale x 2 x i64> %acc.a, %ea
  %vscale = call i64 @llvm.vscale.i64()
  %step = shl nuw nsw i64 %vscale, 3
  %iv.next = add nuw nsw i64 %iv, %step
  %ec = icmp ult i64 %iv.next, %n
  br i1 %ec, label %loop, label %exit

exit:
  store <vscale x 2 x i64> %add.b, ptr %out, align 8
  %out.1 = getelementptr inbounds <vscale x 2 x i64>, ptr %out, i64 1
  store <vscale x 2 x i64> %add.g, ptr %out.1, align 8
  %out.2 = getelementptr inbounds <vscale x 2 x i64>, ptr %out, i64 2
  store <vscale x 2 x i64> %add.r, ptr %out.2, align 8
  %out.3 = getelementptr inbounds <vscale x 2 x i64>, ptr %out, i64 3
  store <vscale x 2 x i64> %add.a, ptr %out.3, align 8
  ret void
}

attributes #0 = { "target-features"="+sve" }

declare { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> }
    @llvm.vector.deinterleave4.nxv8i16(<vscale x 8 x i16>)
declare double @llvm.vector.reduce.fadd.nxv2f64(double, <vscale x 2 x double>)
declare i64 @llvm.vscale.i64()
