; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; RUN: opt -passes=aarch64-sve-shuffle-opts -mtriple=aarch64-linux-gnu -mattr=+sve -S < %s | FileCheck %s

define void @zext_nxv8i16_to_nxv8i64_deinterleave_in_loop(ptr %src, ptr %dst, <vscale x 8 x i1> %mask) #0 {
; CHECK-LABEL: define void @zext_nxv8i16_to_nxv8i64_deinterleave_in_loop(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]], <vscale x 8 x i1> [[MASK:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[VSCALE:%.*]] = tail call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[STRIDE:%.*]] = shl nuw nsw i64 [[VSCALE]], 1
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC_B_I64:%.*]] = phi <vscale x 2 x i64> [ zeroinitializer, %[[ENTRY]] ], [ [[ADD_B_I64:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC_G_I64:%.*]] = phi <vscale x 2 x i64> [ zeroinitializer, %[[ENTRY]] ], [ [[ADD_G_I64:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC_R_I64:%.*]] = phi <vscale x 2 x i64> [ zeroinitializer, %[[ENTRY]] ], [ [[ADD_R_I64:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC_A_I64:%.*]] = phi <vscale x 2 x i64> [ zeroinitializer, %[[ENTRY]] ], [ [[ADD_A_I64:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[SRC_GEP:%.*]] = getelementptr inbounds nuw [4 x i16], ptr [[SRC]], i64 [[IV]]
; CHECK-NEXT:    [[BGRA:%.*]] = call <vscale x 8 x i16> @llvm.masked.load.nxv8i16.p0(ptr [[SRC_GEP]], <vscale x 8 x i1> [[MASK]], <vscale x 8 x i16> zeroinitializer)
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.stepvector.nxv2i64()
; CHECK-NEXT:    [[TMP1:%.*]] = mul nuw <vscale x 2 x i64> [[TMP0]], splat (i64 4)
; CHECK-NEXT:    [[TMP2:%.*]] = add nuw <vscale x 2 x i64> [[TMP1]], splat (i64 -65536)
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <vscale x 2 x i64> [[TMP2]] to <vscale x 8 x i16>
; CHECK-NEXT:    [[TMP4:%.*]] = call <vscale x 8 x i16> @llvm.aarch64.sve.tbl.nxv8i16(<vscale x 8 x i16> [[BGRA]], <vscale x 8 x i16> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = bitcast <vscale x 8 x i16> [[TMP4]] to <vscale x 2 x i64>
; CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 2 x i64> @llvm.stepvector.nxv2i64()
; CHECK-NEXT:    [[TMP7:%.*]] = mul nuw <vscale x 2 x i64> [[TMP6]], splat (i64 4)
; CHECK-NEXT:    [[TMP8:%.*]] = add nuw <vscale x 2 x i64> [[TMP7]], splat (i64 -65535)
; CHECK-NEXT:    [[TMP9:%.*]] = bitcast <vscale x 2 x i64> [[TMP8]] to <vscale x 8 x i16>
; CHECK-NEXT:    [[TMP10:%.*]] = call <vscale x 8 x i16> @llvm.aarch64.sve.tbl.nxv8i16(<vscale x 8 x i16> [[BGRA]], <vscale x 8 x i16> [[TMP9]])
; CHECK-NEXT:    [[TMP11:%.*]] = bitcast <vscale x 8 x i16> [[TMP10]] to <vscale x 2 x i64>
; CHECK-NEXT:    [[TMP12:%.*]] = call <vscale x 2 x i64> @llvm.stepvector.nxv2i64()
; CHECK-NEXT:    [[TMP13:%.*]] = mul nuw <vscale x 2 x i64> [[TMP12]], splat (i64 4)
; CHECK-NEXT:    [[TMP14:%.*]] = add nuw <vscale x 2 x i64> [[TMP13]], splat (i64 -65534)
; CHECK-NEXT:    [[TMP15:%.*]] = bitcast <vscale x 2 x i64> [[TMP14]] to <vscale x 8 x i16>
; CHECK-NEXT:    [[TMP16:%.*]] = call <vscale x 8 x i16> @llvm.aarch64.sve.tbl.nxv8i16(<vscale x 8 x i16> [[BGRA]], <vscale x 8 x i16> [[TMP15]])
; CHECK-NEXT:    [[TMP17:%.*]] = bitcast <vscale x 8 x i16> [[TMP16]] to <vscale x 2 x i64>
; CHECK-NEXT:    [[TMP18:%.*]] = call <vscale x 2 x i64> @llvm.stepvector.nxv2i64()
; CHECK-NEXT:    [[TMP19:%.*]] = mul nuw <vscale x 2 x i64> [[TMP18]], splat (i64 4)
; CHECK-NEXT:    [[TMP20:%.*]] = add nuw <vscale x 2 x i64> [[TMP19]], splat (i64 -65533)
; CHECK-NEXT:    [[TMP21:%.*]] = bitcast <vscale x 2 x i64> [[TMP20]] to <vscale x 8 x i16>
; CHECK-NEXT:    [[TMP22:%.*]] = call <vscale x 8 x i16> @llvm.aarch64.sve.tbl.nxv8i16(<vscale x 8 x i16> [[BGRA]], <vscale x 8 x i16> [[TMP21]])
; CHECK-NEXT:    [[TMP23:%.*]] = bitcast <vscale x 8 x i16> [[TMP22]] to <vscale x 2 x i64>
; CHECK-NEXT:    [[ADD_B_I64]] = add <vscale x 2 x i64> [[ACC_B_I64]], [[TMP5]]
; CHECK-NEXT:    [[ADD_G_I64]] = add <vscale x 2 x i64> [[ACC_G_I64]], [[TMP11]]
; CHECK-NEXT:    [[ADD_R_I64]] = add <vscale x 2 x i64> [[ACC_R_I64]], [[TMP17]]
; CHECK-NEXT:    [[ADD_A_I64]] = add <vscale x 2 x i64> [[ACC_A_I64]], [[TMP23]]
; CHECK-NEXT:    [[IV_NEXT]] = add nuw i64 [[IV]], [[STRIDE]]
; CHECK-NEXT:    [[EC:%.*]] = icmp eq i64 [[IV_NEXT]], 2048
; CHECK-NEXT:    br i1 [[EC]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ADD_B_I64_LCSSA:%.*]] = phi <vscale x 2 x i64> [ [[ADD_B_I64]], %[[LOOP]] ]
; CHECK-NEXT:    [[ADD_G_I64_LCSSA:%.*]] = phi <vscale x 2 x i64> [ [[ADD_G_I64]], %[[LOOP]] ]
; CHECK-NEXT:    [[ADD_R_I64_LCSSA:%.*]] = phi <vscale x 2 x i64> [ [[ADD_R_I64]], %[[LOOP]] ]
; CHECK-NEXT:    [[ADD_A_I64_LCSSA:%.*]] = phi <vscale x 2 x i64> [ [[ADD_A_I64]], %[[LOOP]] ]
; CHECK-NEXT:    store <vscale x 2 x i64> [[ADD_B_I64_LCSSA]], ptr [[DST]], align 16
; CHECK-NEXT:    [[G_I64_GEP:%.*]] = getelementptr <vscale x 2 x i64>, ptr [[DST]], i64 1
; CHECK-NEXT:    store <vscale x 2 x i64> [[ADD_G_I64_LCSSA]], ptr [[G_I64_GEP]], align 16
; CHECK-NEXT:    [[R_I64_GEP:%.*]] = getelementptr <vscale x 2 x i64>, ptr [[DST]], i64 2
; CHECK-NEXT:    store <vscale x 2 x i64> [[ADD_R_I64_LCSSA]], ptr [[R_I64_GEP]], align 16
; CHECK-NEXT:    [[A_I64_GEP:%.*]] = getelementptr <vscale x 2 x i64>, ptr [[DST]], i64 3
; CHECK-NEXT:    store <vscale x 2 x i64> [[ADD_A_I64_LCSSA]], ptr [[A_I64_GEP]], align 16
; CHECK-NEXT:    ret void
;
entry:
  %vscale = tail call i64 @llvm.vscale.i64()
  %stride = shl nuw nsw i64 %vscale, 1
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %acc.b.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.b.i64, %loop ]
  %acc.g.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.g.i64, %loop ]
  %acc.r.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.r.i64, %loop ]
  %acc.a.i64 = phi <vscale x 2 x i64> [ splat(i64 0), %entry ], [ %add.a.i64, %loop ]
  %src.gep = getelementptr inbounds nuw [4 x i16], ptr %src, i64 %iv
  %bgra = call <vscale x 8 x i16> @llvm.masked.load(ptr %src.gep, <vscale x 8 x i1> %mask, <vscale x 8 x i16> zeroinitializer)
  %deinterleave = tail call { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } @llvm.vector.deinterleave4(<vscale x 8 x i16> %bgra)
  %b.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 0
  %g.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 1
  %r.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 2
  %a.i16 = extractvalue { <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16> } %deinterleave, 3
  %b.i64 = zext <vscale x 2 x i16> %b.i16 to <vscale x 2 x i64>
  %g.i64 = zext <vscale x 2 x i16> %g.i16 to <vscale x 2 x i64>
  %r.i64 = zext <vscale x 2 x i16> %r.i16 to <vscale x 2 x i64>
  %a.i64 = zext <vscale x 2 x i16> %a.i16 to <vscale x 2 x i64>
  %add.b.i64 = add <vscale x 2 x i64> %acc.b.i64, %b.i64
  %add.g.i64 = add <vscale x 2 x i64> %acc.g.i64, %g.i64
  %add.r.i64 = add <vscale x 2 x i64> %acc.r.i64, %r.i64
  %add.a.i64 = add <vscale x 2 x i64> %acc.a.i64, %a.i64
  %iv.next = add nuw i64 %iv, %stride
  %ec = icmp eq i64 %iv.next, 2048
  br i1 %ec, label %exit, label %loop

exit:
  store <vscale x 2 x i64> %add.b.i64, ptr %dst
  %g.i64.gep = getelementptr <vscale x 2 x i64>, ptr %dst, i64 1
  store <vscale x 2 x i64> %add.g.i64, ptr %g.i64.gep
  %r.i64.gep = getelementptr <vscale x 2 x i64>, ptr %dst, i64 2
  store <vscale x 2 x i64> %add.r.i64, ptr %r.i64.gep
  %a.i64.gep = getelementptr <vscale x 2 x i64>, ptr %dst, i64 3
  store <vscale x 2 x i64> %add.a.i64, ptr %a.i64.gep
  ret void
}

attributes #0 = { "target-features"="+sve" }
