; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64--linux-gnu -mattr=+sve2p1 -asm-verbose=0 < %s | FileCheck %s

define <vscale x 2 x i64> @segment_gather_64_i32(<vscale x 2 x ptr> %wide.ptrs, <vscale x 1 x i1> %mask) {
; CHECK-LABEL: segment_gather_64_i32:
; CHECK:         pfalse p1.b
; CHECK-NEXT:    uzp1 p0.d, p0.d, p1.d
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [z0.d]
; CHECK-NEXT:    uunpklo z0.d, z0.s
; CHECK-NEXT:    ret
  %ptrs = call <vscale x 1 x ptr> @llvm.vector.extract.nxv1p0.nxv2p0(
      <vscale x 2 x ptr> %wide.ptrs, i64 0)
  %r = call <vscale x 2 x i32> @llvm.masked.segment.gather.nxv2i32.nxv1p0(
      <vscale x 1 x ptr> align 8 %ptrs, <vscale x 1 x i1> %mask,
      <vscale x 2 x i32> poison)
  %r.legal = zext <vscale x 2 x i32> %r to <vscale x 2 x i64>
  ret <vscale x 2 x i64> %r.legal
}

define <vscale x 4 x i32> @segment_gather_64_i16(<vscale x 2 x ptr> %wide.ptrs, <vscale x 1 x i1> %mask) {
; CHECK-LABEL: segment_gather_64_i16:
; CHECK:         pfalse p1.b
; CHECK-NEXT:    uzp1 p0.d, p0.d, p1.d
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [z0.d]
; CHECK-NEXT:    uunpklo z0.s, z0.h
; CHECK-NEXT:    ret
  %ptrs = call <vscale x 1 x ptr> @llvm.vector.extract.nxv1p0.nxv2p0(
      <vscale x 2 x ptr> %wide.ptrs, i64 0)
  %r = call <vscale x 4 x i16> @llvm.masked.segment.gather.nxv4i16.nxv1p0(
      <vscale x 1 x ptr> align 8 %ptrs, <vscale x 1 x i1> %mask,
      <vscale x 4 x i16> poison)
  %r.legal = zext <vscale x 4 x i16> %r to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %r.legal
}

define <vscale x 4 x i32> @segment_gather_64_i16_load_ptrs(ptr %ptrs.addr, <vscale x 1 x i1> %mask) {
; CHECK-LABEL: segment_gather_64_i16_load_ptrs:
; CHECK:         rdvl x8, #1
; CHECK-NEXT:    pfalse p2.b
; CHECK-NEXT:    lsr x8, x8, #4
; CHECK-NEXT:    uzp1 p0.d, p0.d, p2.d
; CHECK-NEXT:    whilelo p1.d, xzr, x8
; CHECK-NEXT:    ld1d { z0.d }, p1/z, [x0]
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [z0.d]
; CHECK-NEXT:    uunpklo z0.s, z0.h
; CHECK-NEXT:    ret
  %ptrs = load <vscale x 1 x ptr>, ptr %ptrs.addr
  %r = call <vscale x 4 x i16> @llvm.masked.segment.gather.nxv4i16.nxv1p0(
      <vscale x 1 x ptr> align 8 %ptrs, <vscale x 1 x i1> %mask,
      <vscale x 4 x i16> poison)
  %r.legal = zext <vscale x 4 x i16> %r to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %r.legal
}

define <vscale x 4 x half> @segment_gather_64_f16(<vscale x 2 x ptr> %wide.ptrs, <vscale x 1 x i1> %mask) {
; CHECK-LABEL: segment_gather_64_f16:
; CHECK:         pfalse p1.b
; CHECK-NEXT:    uzp1 p0.d, p0.d, p1.d
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [z0.d]
; CHECK-NEXT:    uunpklo z0.s, z0.h
; CHECK-NEXT:    ret
  %ptrs = call <vscale x 1 x ptr> @llvm.vector.extract.nxv1p0.nxv2p0(
      <vscale x 2 x ptr> %wide.ptrs, i64 0)
  %r = call <vscale x 4 x half> @llvm.masked.segment.gather.nxv4f16.nxv1p0(
      <vscale x 1 x ptr> align 8 %ptrs, <vscale x 1 x i1> %mask,
      <vscale x 4 x half> poison)
  ret <vscale x 4 x half> %r
}

define <vscale x 4 x half> @segment_gather_64_f16_load_ptrs(ptr %ptrs.addr, <vscale x 1 x i1> %mask) {
; CHECK-LABEL: segment_gather_64_f16_load_ptrs:
; CHECK:         rdvl x8, #1
; CHECK-NEXT:    pfalse p2.b
; CHECK-NEXT:    lsr x8, x8, #4
; CHECK-NEXT:    uzp1 p0.d, p0.d, p2.d
; CHECK-NEXT:    whilelo p1.d, xzr, x8
; CHECK-NEXT:    ld1d { z0.d }, p1/z, [x0]
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [z0.d]
; CHECK-NEXT:    uunpklo z0.s, z0.h
; CHECK-NEXT:    ret
  %ptrs = load <vscale x 1 x ptr>, ptr %ptrs.addr
  %r = call <vscale x 4 x half> @llvm.masked.segment.gather.nxv4f16.nxv1p0(
      <vscale x 1 x ptr> align 8 %ptrs, <vscale x 1 x i1> %mask,
      <vscale x 4 x half> poison)
  ret <vscale x 4 x half> %r
}

define void @segment_scatter_64_i32(<vscale x 2 x i64> %wide.data, <vscale x 2 x ptr> %wide.ptrs, <vscale x 1 x i1> %mask) {
; CHECK-LABEL: segment_scatter_64_i32:
; CHECK:         pfalse p1.b
; CHECK-NEXT:    uzp1 z0.s, z0.s, z0.s
; CHECK-NEXT:    uzp1 p0.d, p0.d, p1.d
; CHECK-NEXT:    st1d { z0.d }, p0, [z1.d]
; CHECK-NEXT:    ret
  %data = trunc <vscale x 2 x i64> %wide.data to <vscale x 2 x i32>
  %ptrs = call <vscale x 1 x ptr> @llvm.vector.extract.nxv1p0.nxv2p0(
      <vscale x 2 x ptr> %wide.ptrs, i64 0)
  call void @llvm.masked.segment.scatter.nxv2i32.nxv1p0(
      <vscale x 2 x i32> %data, <vscale x 1 x ptr> align 8 %ptrs,
      <vscale x 1 x i1> %mask)
  ret void
}

define void @segment_scatter_64_i16(<vscale x 4 x i32> %wide.data, <vscale x 2 x ptr> %wide.ptrs, <vscale x 1 x i1> %mask) {
; CHECK-LABEL: segment_scatter_64_i16:
; CHECK:         pfalse p1.b
; CHECK-NEXT:    uzp1 z0.h, z0.h, z0.h
; CHECK-NEXT:    uzp1 p0.d, p0.d, p1.d
; CHECK-NEXT:    st1d { z0.d }, p0, [z1.d]
; CHECK-NEXT:    ret
  %data = trunc <vscale x 4 x i32> %wide.data to <vscale x 4 x i16>
  %ptrs = call <vscale x 1 x ptr> @llvm.vector.extract.nxv1p0.nxv2p0(
      <vscale x 2 x ptr> %wide.ptrs, i64 0)
  call void @llvm.masked.segment.scatter.nxv4i16.nxv1p0(
      <vscale x 4 x i16> %data, <vscale x 1 x ptr> align 8 %ptrs,
      <vscale x 1 x i1> %mask)
  ret void
}

define void @segment_scatter_64_f16(<vscale x 4 x half> %data, <vscale x 2 x ptr> %wide.ptrs, <vscale x 1 x i1> %mask) {
; CHECK-LABEL: segment_scatter_64_f16:
; CHECK:         pfalse p1.b
; CHECK-NEXT:    uzp1 z0.h, z0.h, z0.h
; CHECK-NEXT:    uzp1 p0.d, p0.d, p1.d
; CHECK-NEXT:    st1d { z0.d }, p0, [z1.d]
; CHECK-NEXT:    ret
  %ptrs = call <vscale x 1 x ptr> @llvm.vector.extract.nxv1p0.nxv2p0(
      <vscale x 2 x ptr> %wide.ptrs, i64 0)
  call void @llvm.masked.segment.scatter.nxv4f16.nxv1p0(
      <vscale x 4 x half> %data, <vscale x 1 x ptr> align 8 %ptrs,
      <vscale x 1 x i1> %mask)
  ret void
}

define <vscale x 4 x i32> @segment_gather_128_i32(<vscale x 2 x ptr> %wide.ptrs, <vscale x 1 x i1> %mask) {
; CHECK-LABEL: segment_gather_128_i32:
; CHECK:         zip1 z0.d, z0.d, z0.d
; CHECK-NEXT:    ld1q { z0.q }, p0/z, [z0.d]
; CHECK-NEXT:    ret
  %ptrs = call <vscale x 1 x ptr> @llvm.vector.extract.nxv1p0.nxv2p0(
      <vscale x 2 x ptr> %wide.ptrs, i64 0)
  %r = call <vscale x 4 x i32> @llvm.masked.segment.gather.nxv4i32.nxv1p0(
      <vscale x 1 x ptr> align 16 %ptrs, <vscale x 1 x i1> %mask,
      <vscale x 4 x i32> zeroinitializer)
  ret <vscale x 4 x i32> %r
}

define <vscale x 4 x i32> @segment_gather_128_i32_load_ptrs(ptr %ptrs.addr, <vscale x 1 x i1> %mask) {
; CHECK-LABEL: segment_gather_128_i32_load_ptrs:
; CHECK:         rdvl x8, #1
; CHECK-NEXT:    lsr x8, x8, #4
; CHECK-NEXT:    whilelo p1.d, xzr, x8
; CHECK-NEXT:    ld1d { z0.d }, p1/z, [x0]
; CHECK-NEXT:    zip1 z0.d, z0.d, z0.d
; CHECK-NEXT:    ld1q { z0.q }, p0/z, [z0.d]
; CHECK-NEXT:    ret
  %ptrs = load <vscale x 1 x ptr>, ptr %ptrs.addr
  %r = call <vscale x 4 x i32> @llvm.masked.segment.gather.nxv4i32.nxv1p0(
      <vscale x 1 x ptr> align 16 %ptrs, <vscale x 1 x i1> %mask,
      <vscale x 4 x i32> zeroinitializer)
  ret <vscale x 4 x i32> %r
}

define void @segment_scatter_128_i32(<vscale x 4 x i32> %data, <vscale x 2 x ptr> %wide.ptrs, <vscale x 1 x i1> %mask) {
; CHECK-LABEL: segment_scatter_128_i32:
; CHECK:         zip1 z1.d, z1.d, z1.d
; CHECK-NEXT:    st1q { z0.q }, p0, [z1.d]
; CHECK-NEXT:    ret
  %ptrs = call <vscale x 1 x ptr> @llvm.vector.extract.nxv1p0.nxv2p0(
      <vscale x 2 x ptr> %wide.ptrs, i64 0)
  call void @llvm.masked.segment.scatter.nxv4i32.nxv1p0(
      <vscale x 4 x i32> %data, <vscale x 1 x ptr> align 16 %ptrs,
      <vscale x 1 x i1> %mask)
  ret void
}
