; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple aarch64 -mattr=+sve -global-isel=0  | FileCheck %s
; RUN: llc < %s -mtriple aarch64 -mattr=+sve -global-isel -aarch64-enable-gisel-sve=1 | FileCheck %s

;; fneg
define <vscale x 2 x double> @fnegnxv2double(<vscale x 2 x double> %a) {
; CHECK-LABEL: fnegnxv2double:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    fneg z0.d, p0/m, z0.d
; CHECK-NEXT:    ret
entry:
  %c = fneg <vscale x 2 x double> %a
  ret <vscale x 2 x double> %c
}

define <vscale x 4 x float> @fnegnxv4float(<vscale x 4 x float> %a) {
; CHECK-LABEL: fnegnxv4float:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    fneg z0.s, p0/m, z0.s
; CHECK-NEXT:    ret
entry:
  %c = fneg <vscale x 4 x float> %a
  ret <vscale x 4 x float> %c
}

define <vscale x 8 x half> @fnegnxv8half(<vscale x 8 x half> %a) {
; CHECK-LABEL: fnegnxv8half:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    fneg z0.h, p0/m, z0.h
; CHECK-NEXT:    ret
entry:
  %c = fneg <vscale x 8 x half> %a
  ret <vscale x 8 x half> %c
}

;; fabs
define <vscale x 2 x double> @fabsnxv2double(<vscale x 2 x double> %a) {
; CHECK-LABEL: fabsnxv2double:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    fabs z0.d, p0/m, z0.d
; CHECK-NEXT:    ret
entry:
  %c = tail call <vscale x 2 x double> @llvm.fabs.nxv2f64(<vscale x 2 x double> %a)
  ret <vscale x 2 x double> %c
}

define <vscale x 4 x float> @fabsnxv4float(<vscale x 4 x float> %a) {
; CHECK-LABEL: fabsnxv4float:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    fabs z0.s, p0/m, z0.s
; CHECK-NEXT:    ret
entry:
  %c = tail call <vscale x 4 x float> @llvm.fabs.nxv4f32(<vscale x 4 x float> %a)
  ret <vscale x 4 x float> %c
}

define <vscale x 8 x half> @fabsnxv8half(<vscale x 8 x half> %a) {
; CHECK-LABEL: fabsnxv8half:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    fabs z0.h, p0/m, z0.h
; CHECK-NEXT:    ret
entry:
   %c = tail call <vscale x 8 x half> @llvm.fabs.nxv8f16(<vscale x 8 x half> %a)
  ret <vscale x 8 x half> %c
}
