; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -mattr=+sve < %s | FileCheck %s

define <vscale x 16 x i1> @and_nxv16i1(<vscale x 16 x i1> %a, <vscale x 16 x i1> %b) {
; CHECK-LABEL: and_nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and p0.b, p0/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %res = and <vscale x 16 x i1> %a, %b
  ret <vscale x 16 x i1> %res
}

define <vscale x 8 x i1> @and_nxv8i1(<vscale x 8 x i1> %a, <vscale x 8 x i1> %b) {
; CHECK-LABEL: and_nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and p0.b, p0/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %res = and <vscale x 8 x i1> %a, %b
  ret <vscale x 8 x i1> %res
}

define <vscale x 4 x i1> @and_nxv4i1(<vscale x 4 x i1> %a, <vscale x 4 x i1> %b) {
; CHECK-LABEL: and_nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and p0.b, p0/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %res = and <vscale x 4 x i1> %a, %b
  ret <vscale x 4 x i1> %res
}

define <vscale x 2 x i1> @and_nxv2i1(<vscale x 2 x i1> %a, <vscale x 2 x i1> %b) {
; CHECK-LABEL: and_nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and p0.b, p0/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %res = and <vscale x 2 x i1> %a, %b
  ret <vscale x 2 x i1> %res
}

define <vscale x 1 x i1> @and_nxv1i1(<vscale x 1 x i1> %a, <vscale x 1 x i1> %b) {
; CHECK-LABEL: and_nxv1i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and p0.b, p0/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %res = and <vscale x 1 x i1> %a, %b
  ret <vscale x 1 x i1> %res
}

define <vscale x 16 x i1> @and_and_nxv16i1(<vscale x 16 x i1> %pg, <vscale x 16 x i1> %a, <vscale x 16 x i1> %b) {
; CHECK-LABEL: and_and_nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %op = and <vscale x 16 x i1> %a, %b
  %res = and <vscale x 16 x i1> %pg, %op
  ret <vscale x 16 x i1> %res
}

define <vscale x 8 x i1> @and_and_nxv8i1(<vscale x 8 x i1> %pg, <vscale x 8 x i1> %a, <vscale x 8 x i1> %b) {
; CHECK-LABEL: and_and_nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %op = and <vscale x 8 x i1> %a, %b
  %res = and <vscale x 8 x i1> %pg, %op
  ret <vscale x 8 x i1> %res
}

define <vscale x 4 x i1> @and_and_nxv4i1(<vscale x 4 x i1> %pg, <vscale x 4 x i1> %a, <vscale x 4 x i1> %b) {
; CHECK-LABEL: and_and_nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %op = and <vscale x 4 x i1> %a, %b
  %res = and <vscale x 4 x i1> %pg, %op
  ret <vscale x 4 x i1> %res
}

define <vscale x 2 x i1> @and_and_nxv2i1(<vscale x 2 x i1> %pg, <vscale x 2 x i1> %a, <vscale x 2 x i1> %b) {
; CHECK-LABEL: and_and_nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %op = and <vscale x 2 x i1> %a, %b
  %res = and <vscale x 2 x i1> %pg, %op
  ret <vscale x 2 x i1> %res
}

define <vscale x 1 x i1> @and_and_nxv1i1(<vscale x 1 x i1> %pg, <vscale x 1 x i1> %a, <vscale x 1 x i1> %b) {
; CHECK-LABEL: and_and_nxv1i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %op = and <vscale x 1 x i1> %a, %b
  %res = and <vscale x 1 x i1> %pg, %op
  ret <vscale x 1 x i1> %res
}

define <vscale x 16 x i1> @and_bic_nxv16i1(<vscale x 16 x i1> %pg, <vscale x 16 x i1> %a, <vscale x 16 x i1> %b) {
; CHECK-LABEL: and_bic_nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    bic p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 16 x i1> %b, splat (i1 true)
  %op = and <vscale x 16 x i1> %a, %not.b
  %res = and <vscale x 16 x i1> %pg, %op
  ret <vscale x 16 x i1> %res
}

define <vscale x 8 x i1> @and_bic_nxv8i1(<vscale x 8 x i1> %pg, <vscale x 8 x i1> %a, <vscale x 8 x i1> %b) {
; CHECK-LABEL: and_bic_nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    bic p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 8 x i1> %b, splat (i1 true)
  %op = and <vscale x 8 x i1> %a, %not.b
  %res = and <vscale x 8 x i1> %pg, %op
  ret <vscale x 8 x i1> %res
}

define <vscale x 4 x i1> @and_bic_nxv4i1(<vscale x 4 x i1> %pg, <vscale x 4 x i1> %a, <vscale x 4 x i1> %b) {
; CHECK-LABEL: and_bic_nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    bic p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 4 x i1> %b, splat (i1 true)
  %op = and <vscale x 4 x i1> %a, %not.b
  %res = and <vscale x 4 x i1> %pg, %op
  ret <vscale x 4 x i1> %res
}

define <vscale x 2 x i1> @and_bic_nxv2i1(<vscale x 2 x i1> %pg, <vscale x 2 x i1> %a, <vscale x 2 x i1> %b) {
; CHECK-LABEL: and_bic_nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    bic p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 2 x i1> %b, splat (i1 true)
  %op = and <vscale x 2 x i1> %a, %not.b
  %res = and <vscale x 2 x i1> %pg, %op
  ret <vscale x 2 x i1> %res
}

define <vscale x 1 x i1> @and_bic_nxv1i1(<vscale x 1 x i1> %pg, <vscale x 1 x i1> %a, <vscale x 1 x i1> %b) {
; CHECK-LABEL: and_bic_nxv1i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    bic p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 1 x i1> %b, splat (i1 true)
  %op = and <vscale x 1 x i1> %a, %not.b
  %res = and <vscale x 1 x i1> %pg, %op
  ret <vscale x 1 x i1> %res
}

define <vscale x 16 x i1> @and_eor_nxv16i1(<vscale x 16 x i1> %pg, <vscale x 16 x i1> %a, <vscale x 16 x i1> %b) {
; CHECK-LABEL: and_eor_nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    eor p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %op = xor <vscale x 16 x i1> %a, %b
  %res = and <vscale x 16 x i1> %pg, %op
  ret <vscale x 16 x i1> %res
}

define <vscale x 8 x i1> @and_eor_nxv8i1(<vscale x 8 x i1> %pg, <vscale x 8 x i1> %a, <vscale x 8 x i1> %b) {
; CHECK-LABEL: and_eor_nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    eor p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %op = xor <vscale x 8 x i1> %a, %b
  %res = and <vscale x 8 x i1> %pg, %op
  ret <vscale x 8 x i1> %res
}

define <vscale x 4 x i1> @and_eor_nxv4i1(<vscale x 4 x i1> %pg, <vscale x 4 x i1> %a, <vscale x 4 x i1> %b) {
; CHECK-LABEL: and_eor_nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    eor p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %op = xor <vscale x 4 x i1> %a, %b
  %res = and <vscale x 4 x i1> %pg, %op
  ret <vscale x 4 x i1> %res
}

define <vscale x 2 x i1> @and_eor_nxv2i1(<vscale x 2 x i1> %pg, <vscale x 2 x i1> %a, <vscale x 2 x i1> %b) {
; CHECK-LABEL: and_eor_nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    eor p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %op = xor <vscale x 2 x i1> %a, %b
  %res = and <vscale x 2 x i1> %pg, %op
  ret <vscale x 2 x i1> %res
}

define <vscale x 1 x i1> @and_eor_nxv1i1(<vscale x 1 x i1> %pg, <vscale x 1 x i1> %a, <vscale x 1 x i1> %b) {
; CHECK-LABEL: and_eor_nxv1i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    eor p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %op = xor <vscale x 1 x i1> %a, %b
  %res = and <vscale x 1 x i1> %pg, %op
  ret <vscale x 1 x i1> %res
}

define <vscale x 16 x i1> @and_orn_nxv16i1(<vscale x 16 x i1> %pg, <vscale x 16 x i1> %a, <vscale x 16 x i1> %b) {
; CHECK-LABEL: and_orn_nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    orn p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 16 x i1> %b, splat (i1 true)
  %op = or <vscale x 16 x i1> %a, %not.b
  %res = and <vscale x 16 x i1> %pg, %op
  ret <vscale x 16 x i1> %res
}

define <vscale x 8 x i1> @and_orn_nxv8i1(<vscale x 8 x i1> %pg, <vscale x 8 x i1> %a, <vscale x 8 x i1> %b) {
; CHECK-LABEL: and_orn_nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    orn p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 8 x i1> %b, splat (i1 true)
  %op = or <vscale x 8 x i1> %a, %not.b
  %res = and <vscale x 8 x i1> %pg, %op
  ret <vscale x 8 x i1> %res
}

define <vscale x 4 x i1> @and_orn_nxv4i1(<vscale x 4 x i1> %pg, <vscale x 4 x i1> %a, <vscale x 4 x i1> %b) {
; CHECK-LABEL: and_orn_nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    orn p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 4 x i1> %b, splat (i1 true)
  %op = or <vscale x 4 x i1> %a, %not.b
  %res = and <vscale x 4 x i1> %pg, %op
  ret <vscale x 4 x i1> %res
}

define <vscale x 2 x i1> @and_orn_nxv2i1(<vscale x 2 x i1> %pg, <vscale x 2 x i1> %a, <vscale x 2 x i1> %b) {
; CHECK-LABEL: and_orn_nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    orn p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 2 x i1> %b, splat (i1 true)
  %op = or <vscale x 2 x i1> %a, %not.b
  %res = and <vscale x 2 x i1> %pg, %op
  ret <vscale x 2 x i1> %res
}

define <vscale x 1 x i1> @and_orn_nxv1i1(<vscale x 1 x i1> %pg, <vscale x 1 x i1> %a, <vscale x 1 x i1> %b) {
; CHECK-LABEL: and_orn_nxv1i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    orn p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 1 x i1> %b, splat (i1 true)
  %op = or <vscale x 1 x i1> %a, %not.b
  %res = and <vscale x 1 x i1> %pg, %op
  ret <vscale x 1 x i1> %res
}

define <vscale x 16 x i1> @and_orr_nxv16i1(<vscale x 16 x i1> %pg, <vscale x 16 x i1> %a, <vscale x 16 x i1> %b) {
; CHECK-LABEL: and_orr_nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    orr p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %op = or <vscale x 16 x i1> %a, %b
  %res = and <vscale x 16 x i1> %pg, %op
  ret <vscale x 16 x i1> %res
}

define <vscale x 8 x i1> @and_orr_nxv8i1(<vscale x 8 x i1> %pg, <vscale x 8 x i1> %a, <vscale x 8 x i1> %b) {
; CHECK-LABEL: and_orr_nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    orr p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %op = or <vscale x 8 x i1> %a, %b
  %res = and <vscale x 8 x i1> %pg, %op
  ret <vscale x 8 x i1> %res
}

define <vscale x 4 x i1> @and_orr_nxv4i1(<vscale x 4 x i1> %pg, <vscale x 4 x i1> %a, <vscale x 4 x i1> %b) {
; CHECK-LABEL: and_orr_nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    orr p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %op = or <vscale x 4 x i1> %a, %b
  %res = and <vscale x 4 x i1> %pg, %op
  ret <vscale x 4 x i1> %res
}

define <vscale x 2 x i1> @and_orr_nxv2i1(<vscale x 2 x i1> %pg, <vscale x 2 x i1> %a, <vscale x 2 x i1> %b) {
; CHECK-LABEL: and_orr_nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    orr p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %op = or <vscale x 2 x i1> %a, %b
  %res = and <vscale x 2 x i1> %pg, %op
  ret <vscale x 2 x i1> %res
}

define <vscale x 1 x i1> @and_orr_nxv1i1(<vscale x 1 x i1> %pg, <vscale x 1 x i1> %a, <vscale x 1 x i1> %b) {
; CHECK-LABEL: and_orr_nxv1i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    orr p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %op = or <vscale x 1 x i1> %a, %b
  %res = and <vscale x 1 x i1> %pg, %op
  ret <vscale x 1 x i1> %res
}

define <vscale x 16 x i1> @and_nand_nxv16i1(<vscale x 16 x i1> %pg, <vscale x 16 x i1> %a, <vscale x 16 x i1> %b) {
; CHECK-LABEL: and_nand_nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    nand p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %and = and <vscale x 16 x i1> %a, %b
  %op = xor <vscale x 16 x i1> %and, splat (i1 true)
  %res = and <vscale x 16 x i1> %pg, %op
  ret <vscale x 16 x i1> %res
}

define <vscale x 8 x i1> @and_nand_nxv8i1(<vscale x 8 x i1> %pg, <vscale x 8 x i1> %a, <vscale x 8 x i1> %b) {
; CHECK-LABEL: and_nand_nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    nand p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %and = and <vscale x 8 x i1> %a, %b
  %op = xor <vscale x 8 x i1> %and, splat (i1 true)
  %res = and <vscale x 8 x i1> %pg, %op
  ret <vscale x 8 x i1> %res
}

define <vscale x 4 x i1> @and_nand_nxv4i1(<vscale x 4 x i1> %pg, <vscale x 4 x i1> %a, <vscale x 4 x i1> %b) {
; CHECK-LABEL: and_nand_nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    nand p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %and = and <vscale x 4 x i1> %a, %b
  %op = xor <vscale x 4 x i1> %and, splat (i1 true)
  %res = and <vscale x 4 x i1> %pg, %op
  ret <vscale x 4 x i1> %res
}

define <vscale x 2 x i1> @and_nand_nxv2i1(<vscale x 2 x i1> %pg, <vscale x 2 x i1> %a, <vscale x 2 x i1> %b) {
; CHECK-LABEL: and_nand_nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    nand p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %and = and <vscale x 2 x i1> %a, %b
  %op = xor <vscale x 2 x i1> %and, splat (i1 true)
  %res = and <vscale x 2 x i1> %pg, %op
  ret <vscale x 2 x i1> %res
}

define <vscale x 1 x i1> @and_nand_nxv1i1(<vscale x 1 x i1> %pg, <vscale x 1 x i1> %a, <vscale x 1 x i1> %b) {
; CHECK-LABEL: and_nand_nxv1i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    nand p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %and = and <vscale x 1 x i1> %a, %b
  %op = xor <vscale x 1 x i1> %and, splat (i1 true)
  %res = and <vscale x 1 x i1> %pg, %op
  ret <vscale x 1 x i1> %res
}

define <vscale x 16 x i1> @and_nor_nxv16i1(<vscale x 16 x i1> %pg, <vscale x 16 x i1> %a, <vscale x 16 x i1> %b) {
; CHECK-LABEL: and_nor_nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    nor p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %or = or <vscale x 16 x i1> %a, %b
  %op = xor <vscale x 16 x i1> %or, splat (i1 true)
  %res = and <vscale x 16 x i1> %pg, %op
  ret <vscale x 16 x i1> %res
}

define <vscale x 8 x i1> @and_nor_nxv8i1(<vscale x 8 x i1> %pg, <vscale x 8 x i1> %a, <vscale x 8 x i1> %b) {
; CHECK-LABEL: and_nor_nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    nor p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %or = or <vscale x 8 x i1> %a, %b
  %op = xor <vscale x 8 x i1> %or, splat (i1 true)
  %res = and <vscale x 8 x i1> %pg, %op
  ret <vscale x 8 x i1> %res
}

define <vscale x 4 x i1> @and_nor_nxv4i1(<vscale x 4 x i1> %pg, <vscale x 4 x i1> %a, <vscale x 4 x i1> %b) {
; CHECK-LABEL: and_nor_nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    nor p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %or = or <vscale x 4 x i1> %a, %b
  %op = xor <vscale x 4 x i1> %or, splat (i1 true)
  %res = and <vscale x 4 x i1> %pg, %op
  ret <vscale x 4 x i1> %res
}

define <vscale x 2 x i1> @and_nor_nxv2i1(<vscale x 2 x i1> %pg, <vscale x 2 x i1> %a, <vscale x 2 x i1> %b) {
; CHECK-LABEL: and_nor_nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    nor p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %or = or <vscale x 2 x i1> %a, %b
  %op = xor <vscale x 2 x i1> %or, splat (i1 true)
  %res = and <vscale x 2 x i1> %pg, %op
  ret <vscale x 2 x i1> %res
}

define <vscale x 1 x i1> @and_nor_nxv1i1(<vscale x 1 x i1> %pg, <vscale x 1 x i1> %a, <vscale x 1 x i1> %b) {
; CHECK-LABEL: and_nor_nxv1i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    nor p0.b, p0/z, p1.b, p2.b
; CHECK-NEXT:    ret
  %or = or <vscale x 1 x i1> %a, %b
  %op = xor <vscale x 1 x i1> %or, splat (i1 true)
  %res = and <vscale x 1 x i1> %pg, %op
  ret <vscale x 1 x i1> %res
}

define <vscale x 16 x i1> @bic_nxv16i1(<vscale x 16 x i1> %a, <vscale x 16 x i1> %b) {
; CHECK-LABEL: bic_nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    bic p0.b, p0/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 16 x i1> %b, splat (i1 true)
  %res = and <vscale x 16 x i1> %a, %not.b
  ret <vscale x 16 x i1> %res
}

define <vscale x 8 x i1> @bic_nxv8i1(<vscale x 8 x i1> %a, <vscale x 8 x i1> %b) {
; CHECK-LABEL: bic_nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    bic p0.b, p0/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 8 x i1> %b, splat (i1 true)
  %res = and <vscale x 8 x i1> %a, %not.b
  ret <vscale x 8 x i1> %res
}

define <vscale x 4 x i1> @bic_nxv4i1(<vscale x 4 x i1> %a, <vscale x 4 x i1> %b) {
; CHECK-LABEL: bic_nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    bic p0.b, p0/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 4 x i1> %b, splat (i1 true)
  %res = and <vscale x 4 x i1> %a, %not.b
  ret <vscale x 4 x i1> %res
}

define <vscale x 2 x i1> @bic_nxv2i1(<vscale x 2 x i1> %a, <vscale x 2 x i1> %b) {
; CHECK-LABEL: bic_nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    bic p0.b, p0/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 2 x i1> %b, splat (i1 true)
  %res = and <vscale x 2 x i1> %a, %not.b
  ret <vscale x 2 x i1> %res
}

define <vscale x 1 x i1> @bic_nxv1i1(<vscale x 1 x i1> %a, <vscale x 1 x i1> %b) {
; CHECK-LABEL: bic_nxv1i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    bic p0.b, p0/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 1 x i1> %b, splat (i1 true)
  %res = and <vscale x 1 x i1> %a, %not.b
  ret <vscale x 1 x i1> %res
}

define <vscale x 16 x i1> @eor_nxv16i1(<vscale x 16 x i1> %a, <vscale x 16 x i1> %b) {
; CHECK-LABEL: eor_nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.b
; CHECK-NEXT:    eor p0.b, p2/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %res = xor <vscale x 16 x i1> %a, %b
  ret <vscale x 16 x i1> %res
}

define <vscale x 8 x i1> @eor_nxv8i1(<vscale x 8 x i1> %a, <vscale x 8 x i1> %b) {
; CHECK-LABEL: eor_nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.h
; CHECK-NEXT:    eor p0.b, p2/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %res = xor <vscale x 8 x i1> %a, %b
  ret <vscale x 8 x i1> %res
}

define <vscale x 4 x i1> @eor_nxv4i1(<vscale x 4 x i1> %a, <vscale x 4 x i1> %b) {
; CHECK-LABEL: eor_nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.s
; CHECK-NEXT:    eor p0.b, p2/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %res = xor <vscale x 4 x i1> %a, %b
  ret <vscale x 4 x i1> %res
}

define <vscale x 2 x i1> @eor_nxv2i1(<vscale x 2 x i1> %a, <vscale x 2 x i1> %b) {
; CHECK-LABEL: eor_nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.d
; CHECK-NEXT:    eor p0.b, p2/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %res = xor <vscale x 2 x i1> %a, %b
  ret <vscale x 2 x i1> %res
}

define <vscale x 1 x i1> @eor_nxv1i1(<vscale x 1 x i1> %a, <vscale x 1 x i1> %b) {
; CHECK-LABEL: eor_nxv1i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.d
; CHECK-NEXT:    eor p0.b, p2/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %res = xor <vscale x 1 x i1> %a, %b
  ret <vscale x 1 x i1> %res
}

define <vscale x 16 x i1> @orn_nxv16i1(<vscale x 16 x i1> %a, <vscale x 16 x i1> %b) {
; CHECK-LABEL: orn_nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.b
; CHECK-NEXT:    not p1.b, p2/z, p1.b
; CHECK-NEXT:    sel p0.b, p0, p0.b, p1.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 16 x i1> %b, splat (i1 true)
  %res = or <vscale x 16 x i1> %a, %not.b
  ret <vscale x 16 x i1> %res
}

define <vscale x 8 x i1> @orn_nxv8i1(<vscale x 8 x i1> %a, <vscale x 8 x i1> %b) {
; CHECK-LABEL: orn_nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.h
; CHECK-NEXT:    not p1.b, p2/z, p1.b
; CHECK-NEXT:    sel p0.b, p0, p0.b, p1.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 8 x i1> %b, splat (i1 true)
  %res = or <vscale x 8 x i1> %a, %not.b
  ret <vscale x 8 x i1> %res
}

define <vscale x 4 x i1> @orn_nxv4i1(<vscale x 4 x i1> %a, <vscale x 4 x i1> %b) {
; CHECK-LABEL: orn_nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.s
; CHECK-NEXT:    not p1.b, p2/z, p1.b
; CHECK-NEXT:    sel p0.b, p0, p0.b, p1.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 4 x i1> %b, splat (i1 true)
  %res = or <vscale x 4 x i1> %a, %not.b
  ret <vscale x 4 x i1> %res
}

define <vscale x 2 x i1> @orn_nxv2i1(<vscale x 2 x i1> %a, <vscale x 2 x i1> %b) {
; CHECK-LABEL: orn_nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.d
; CHECK-NEXT:    not p1.b, p2/z, p1.b
; CHECK-NEXT:    sel p0.b, p0, p0.b, p1.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 2 x i1> %b, splat (i1 true)
  %res = or <vscale x 2 x i1> %a, %not.b
  ret <vscale x 2 x i1> %res
}

define <vscale x 1 x i1> @orn_nxv1i1(<vscale x 1 x i1> %a, <vscale x 1 x i1> %b) {
; CHECK-LABEL: orn_nxv1i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.d
; CHECK-NEXT:    punpklo p3.h, p2.b
; CHECK-NEXT:    eor p1.b, p2/z, p1.b, p3.b
; CHECK-NEXT:    sel p0.b, p0, p0.b, p1.b
; CHECK-NEXT:    ret
  %not.b = xor <vscale x 1 x i1> %b, splat (i1 true)
  %res = or <vscale x 1 x i1> %a, %not.b
  ret <vscale x 1 x i1> %res
}

define <vscale x 16 x i1> @orr_nxv16i1(<vscale x 16 x i1> %a, <vscale x 16 x i1> %b) {
; CHECK-LABEL: orr_nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sel p0.b, p0, p0.b, p1.b
; CHECK-NEXT:    ret
  %res = or <vscale x 16 x i1> %a, %b
  ret <vscale x 16 x i1> %res
}

define <vscale x 8 x i1> @orr_nxv8i1(<vscale x 8 x i1> %a, <vscale x 8 x i1> %b) {
; CHECK-LABEL: orr_nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sel p0.b, p0, p0.b, p1.b
; CHECK-NEXT:    ret
  %res = or <vscale x 8 x i1> %a, %b
  ret <vscale x 8 x i1> %res
}

define <vscale x 4 x i1> @orr_nxv4i1(<vscale x 4 x i1> %a, <vscale x 4 x i1> %b) {
; CHECK-LABEL: orr_nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sel p0.b, p0, p0.b, p1.b
; CHECK-NEXT:    ret
  %res = or <vscale x 4 x i1> %a, %b
  ret <vscale x 4 x i1> %res
}

define <vscale x 2 x i1> @orr_nxv2i1(<vscale x 2 x i1> %a, <vscale x 2 x i1> %b) {
; CHECK-LABEL: orr_nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sel p0.b, p0, p0.b, p1.b
; CHECK-NEXT:    ret
  %res = or <vscale x 2 x i1> %a, %b
  ret <vscale x 2 x i1> %res
}

define <vscale x 1 x i1> @orr_nxv1i1(<vscale x 1 x i1> %a, <vscale x 1 x i1> %b) {
; CHECK-LABEL: orr_nxv1i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sel p0.b, p0, p0.b, p1.b
; CHECK-NEXT:    ret
  %res = or <vscale x 1 x i1> %a, %b
  ret <vscale x 1 x i1> %res
}

define <vscale x 16 x i1> @nand_nxv16i1(<vscale x 16 x i1> %a, <vscale x 16 x i1> %b) {
; CHECK-LABEL: nand_nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.b
; CHECK-NEXT:    and p1.b, p0/z, p0.b, p1.b
; CHECK-NEXT:    not p0.b, p2/z, p1.b
; CHECK-NEXT:    ret
  %and = and <vscale x 16 x i1> %a, %b
  %res = xor <vscale x 16 x i1> %and, splat (i1 true)
  ret <vscale x 16 x i1> %res
}

define <vscale x 8 x i1> @nand_nxv8i1(<vscale x 8 x i1> %a, <vscale x 8 x i1> %b) {
; CHECK-LABEL: nand_nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.h
; CHECK-NEXT:    and p1.b, p0/z, p0.b, p1.b
; CHECK-NEXT:    not p0.b, p2/z, p1.b
; CHECK-NEXT:    ret
  %and = and <vscale x 8 x i1> %a, %b
  %res = xor <vscale x 8 x i1> %and, splat (i1 true)
  ret <vscale x 8 x i1> %res
}

define <vscale x 4 x i1> @nand_nxv4i1(<vscale x 4 x i1> %a, <vscale x 4 x i1> %b) {
; CHECK-LABEL: nand_nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.s
; CHECK-NEXT:    and p1.b, p0/z, p0.b, p1.b
; CHECK-NEXT:    not p0.b, p2/z, p1.b
; CHECK-NEXT:    ret
  %and = and <vscale x 4 x i1> %a, %b
  %res = xor <vscale x 4 x i1> %and, splat (i1 true)
  ret <vscale x 4 x i1> %res
}

define <vscale x 2 x i1> @nand_nxv2i1(<vscale x 2 x i1> %a, <vscale x 2 x i1> %b) {
; CHECK-LABEL: nand_nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.d
; CHECK-NEXT:    and p1.b, p0/z, p0.b, p1.b
; CHECK-NEXT:    not p0.b, p2/z, p1.b
; CHECK-NEXT:    ret
  %and = and <vscale x 2 x i1> %a, %b
  %res = xor <vscale x 2 x i1> %and, splat (i1 true)
  ret <vscale x 2 x i1> %res
}

define <vscale x 1 x i1> @nand_nxv1i1(<vscale x 1 x i1> %a, <vscale x 1 x i1> %b) {
; CHECK-LABEL: nand_nxv1i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.d
; CHECK-NEXT:    and p1.b, p0/z, p0.b, p1.b
; CHECK-NEXT:    punpklo p0.h, p2.b
; CHECK-NEXT:    eor p0.b, p2/z, p1.b, p0.b
; CHECK-NEXT:    ret
  %and = and <vscale x 1 x i1> %a, %b
  %res = xor <vscale x 1 x i1> %and, splat (i1 true)
  ret <vscale x 1 x i1> %res
}

define <vscale x 16 x i1> @nor_nxv16i1(<vscale x 16 x i1> %a, <vscale x 16 x i1> %b) {
; CHECK-LABEL: nor_nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.b
; CHECK-NEXT:    sel p0.b, p0, p0.b, p1.b
; CHECK-NEXT:    not p0.b, p2/z, p0.b
; CHECK-NEXT:    ret
  %or = or <vscale x 16 x i1> %a, %b
  %res = xor <vscale x 16 x i1> %or, splat (i1 true)
  ret <vscale x 16 x i1> %res
}

define <vscale x 8 x i1> @nor_nxv8i1(<vscale x 8 x i1> %a, <vscale x 8 x i1> %b) {
; CHECK-LABEL: nor_nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.h
; CHECK-NEXT:    sel p0.b, p0, p0.b, p1.b
; CHECK-NEXT:    not p0.b, p2/z, p0.b
; CHECK-NEXT:    ret
  %or = or <vscale x 8 x i1> %a, %b
  %res = xor <vscale x 8 x i1> %or, splat (i1 true)
  ret <vscale x 8 x i1> %res
}

define <vscale x 4 x i1> @nor_nxv4i1(<vscale x 4 x i1> %a, <vscale x 4 x i1> %b) {
; CHECK-LABEL: nor_nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.s
; CHECK-NEXT:    sel p0.b, p0, p0.b, p1.b
; CHECK-NEXT:    not p0.b, p2/z, p0.b
; CHECK-NEXT:    ret
  %or = or <vscale x 4 x i1> %a, %b
  %res = xor <vscale x 4 x i1> %or, splat (i1 true)
  ret <vscale x 4 x i1> %res
}

define <vscale x 2 x i1> @nor_nxv2i1(<vscale x 2 x i1> %a, <vscale x 2 x i1> %b) {
; CHECK-LABEL: nor_nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.d
; CHECK-NEXT:    sel p0.b, p0, p0.b, p1.b
; CHECK-NEXT:    not p0.b, p2/z, p0.b
; CHECK-NEXT:    ret
  %or = or <vscale x 2 x i1> %a, %b
  %res = xor <vscale x 2 x i1> %or, splat (i1 true)
  ret <vscale x 2 x i1> %res
}

define <vscale x 1 x i1> @nor_nxv1i1(<vscale x 1 x i1> %a, <vscale x 1 x i1> %b) {
; CHECK-LABEL: nor_nxv1i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p2.d
; CHECK-NEXT:    sel p0.b, p0, p0.b, p1.b
; CHECK-NEXT:    punpklo p1.h, p2.b
; CHECK-NEXT:    eor p0.b, p2/z, p0.b, p1.b
; CHECK-NEXT:    ret
  %or = or <vscale x 1 x i1> %a, %b
  %res = xor <vscale x 1 x i1> %or, splat (i1 true)
  ret <vscale x 1 x i1> %res
}

define <vscale x 16 x i1> @not_nxv16i1(<vscale x 16 x i1> %a) {
; CHECK-LABEL: not_nxv16i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p1.b
; CHECK-NEXT:    not p0.b, p1/z, p0.b
; CHECK-NEXT:    ret
  %res = xor <vscale x 16 x i1> %a, splat (i1 true)
  ret <vscale x 16 x i1> %res
}

define <vscale x 8 x i1> @not_nxv8i1(<vscale x 8 x i1> %a) {
; CHECK-LABEL: not_nxv8i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p1.h
; CHECK-NEXT:    not p0.b, p1/z, p0.b
; CHECK-NEXT:    ret
  %res = xor <vscale x 8 x i1> %a, splat (i1 true)
  ret <vscale x 8 x i1> %res
}

define <vscale x 4 x i1> @not_nxv4i1(<vscale x 4 x i1> %a) {
; CHECK-LABEL: not_nxv4i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p1.s
; CHECK-NEXT:    not p0.b, p1/z, p0.b
; CHECK-NEXT:    ret
  %res = xor <vscale x 4 x i1> %a, splat (i1 true)
  ret <vscale x 4 x i1> %res
}

define <vscale x 2 x i1> @not_nxv2i1(<vscale x 2 x i1> %a) {
; CHECK-LABEL: not_nxv2i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    not p0.b, p1/z, p0.b
; CHECK-NEXT:    ret
  %res = xor <vscale x 2 x i1> %a, splat (i1 true)
  ret <vscale x 2 x i1> %res
}

define <vscale x 1 x i1> @not_nxv1i1(<vscale x 1 x i1> %a) {
; CHECK-LABEL: not_nxv1i1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    punpklo p2.h, p1.b
; CHECK-NEXT:    eor p0.b, p1/z, p0.b, p2.b
; CHECK-NEXT:    ret
  %res = xor <vscale x 1 x i1> %a, splat (i1 true)
  ret <vscale x 1 x i1> %res
}
