; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mattr=+sve,+f64mm | FileCheck %s --check-prefixes=CHECK,CHECK-SVE
; RUN: llc < %s -mattr=+sve2p1,+f64mm | FileCheck %s --check-prefixes=CHECK,CHECK-SVE2p1

target triple = "aarch64-unknown-linux-gnu"

; TODO: To upstream the deinterleave.segments intrinsics, we'll need more tests:
; - Predicate types
; - Illegal types that need splitting like <vscale x 4 x i64>
; - "packed" types like <vscale x 4 x half>

define {<vscale x 8 x half>, <vscale x 8 x half>} @vector_deinterleave_nxv8f16_nxv16f16(<vscale x 16 x half> %vec) {
; CHECK-LABEL: vector_deinterleave_nxv8f16_nxv16f16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzp1 z2.q, z0.q, z1.q
; CHECK-NEXT:    uzp2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call {<vscale x 8 x half>, <vscale x 8 x half>} @llvm.vector.deinterleave.segments2.nxv16f16(<vscale x 16 x half> %vec)
  ret {<vscale x 8 x half>, <vscale x 8 x half>} %retval
}

define {<vscale x 4 x float>, <vscale x 4 x float>} @vector_deinterleave_nxv4f32_nxv8f32(<vscale x 8 x float> %vec) {
; CHECK-LABEL: vector_deinterleave_nxv4f32_nxv8f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzp1 z2.q, z0.q, z1.q
; CHECK-NEXT:    uzp2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call {<vscale x 4 x float>, <vscale x 4 x float>} @llvm.vector.deinterleave.segments2.nxv8f32(<vscale x 8 x float> %vec)
  ret {<vscale x 4 x float>, <vscale x 4 x float>} %retval
}

define {<vscale x 2 x double>, <vscale x 2 x double>} @vector_deinterleave_nxv2f64_nxv4f64(<vscale x 4 x double> %vec) {
; CHECK-LABEL: vector_deinterleave_nxv2f64_nxv4f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzp1 z2.q, z0.q, z1.q
; CHECK-NEXT:    uzp2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call {<vscale x 2 x double>, <vscale x 2 x double>} @llvm.vector.deinterleave.segments2.nxv4f64(<vscale x 4 x double> %vec)
  ret {<vscale x 2 x double>, <vscale x 2 x double>} %retval
}

define {<vscale x 8 x bfloat>, <vscale x 8 x bfloat>} @vector_deinterleave_nxv8bf16_nxv16bf16(<vscale x 16 x bfloat> %vec) {
; CHECK-LABEL: vector_deinterleave_nxv8bf16_nxv16bf16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzp1 z2.q, z0.q, z1.q
; CHECK-NEXT:    uzp2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call {<vscale x 8 x bfloat>, <vscale x 8 x bfloat>} @llvm.vector.deinterleave.segments2.nxv16bf16(<vscale x 16 x bfloat> %vec)
  ret {<vscale x 8 x bfloat>, <vscale x 8 x bfloat>} %retval
}

; Integers

define {<vscale x 16 x i8>, <vscale x 16 x i8>} @vector_deinterleave_nxv16i8_nxv32i8(<vscale x 32 x i8> %vec) {
; CHECK-LABEL: vector_deinterleave_nxv16i8_nxv32i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzp1 z2.q, z0.q, z1.q
; CHECK-NEXT:    uzp2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call {<vscale x 16 x i8>, <vscale x 16 x i8>} @llvm.vector.deinterleave.segments2.nxv32i8(<vscale x 32 x i8> %vec)
  ret {<vscale x 16 x i8>, <vscale x 16 x i8>} %retval
}

define {<vscale x 8 x i16>, <vscale x 8 x i16>} @vector_deinterleave_nxv8i16_nxv16i16(<vscale x 16 x i16> %vec) {
; CHECK-LABEL: vector_deinterleave_nxv8i16_nxv16i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzp1 z2.q, z0.q, z1.q
; CHECK-NEXT:    uzp2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call {<vscale x 8 x i16>, <vscale x 8 x i16>} @llvm.vector.deinterleave.segments2.nxv16i16(<vscale x 16 x i16> %vec)
  ret {<vscale x 8 x i16>, <vscale x 8 x i16>} %retval
}

; Deinterleaving into 2 64-bit vectors
define <vscale x 4 x i32> @vector_deinterleave_nxv4i16_nxv8i16(<vscale x 8 x i16> %vec) {
; CHECK-SVE-LABEL: vector_deinterleave_nxv4i16_nxv8i16:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    uzp2 z1.d, z0.d, z0.d
; CHECK-SVE-NEXT:    uzp1 z0.d, z0.d, z0.d
; CHECK-SVE-NEXT:    uunpklo z1.s, z1.h
; CHECK-SVE-NEXT:    uunpklo z0.s, z0.h
; CHECK-SVE-NEXT:    sub z0.s, z0.s, z1.s
; CHECK-SVE-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-SVE-NEXT:    ret
;
; CHECK-SVE2p1-LABEL: vector_deinterleave_nxv4i16_nxv8i16:
; CHECK-SVE2p1:       // %bb.0:
; CHECK-SVE2p1-NEXT:    zipq2 z1.h, z0.h, z0.h
; CHECK-SVE2p1-NEXT:    zipq1 z0.h, z0.h, z0.h
; CHECK-SVE2p1-NEXT:    sub z0.s, z0.s, z1.s
; CHECK-SVE2p1-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-SVE2p1-NEXT:    ret
  %retval = call {<vscale x 4 x i16>, <vscale x 4 x i16>} @llvm.vector.deinterleave.segments2.nxv8i16(<vscale x 8 x i16> %vec)
  %res.even = extractvalue {<vscale x 4 x i16>, <vscale x 4 x i16>} %retval, 0
  %res.odd = extractvalue {<vscale x 4 x i16>, <vscale x 4 x i16>} %retval, 1
  %res = sub <vscale x 4 x i16> %res.even, %res.odd
  %res2 = zext <vscale x 4 x i16> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res2
}

; Deinterleaving into 2 32-bit vectors
define <vscale x 2 x i64> @vector_deinterleave_nxv2i16_nxv4i16(<vscale x 4 x i32> %vec) {
; CHECK-LABEL: vector_deinterleave_nxv2i16_nxv4i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uunpkhi z1.d, z0.s
; CHECK-NEXT:    uunpklo z0.d, z0.s
; CHECK-NEXT:    uzp2 z2.q, z0.q, z1.q
; CHECK-NEXT:    uzp1 z0.q, z0.q, z1.q
; CHECK-NEXT:    sub z0.d, z0.d, z2.d
; CHECK-NEXT:    and z0.d, z0.d, #0xffff
; CHECK-NEXT:    ret
  %vec2 = trunc <vscale x 4 x i32> %vec to <vscale x 4 x i16>
  %retval = call {<vscale x 2 x i16>, <vscale x 2 x i16>} @llvm.vector.deinterleave.segments2.nxv4i16(<vscale x 4 x i16> %vec2)
  %res.even = extractvalue {<vscale x 2 x i16>, <vscale x 2 x i16>} %retval, 0
  %res.odd = extractvalue {<vscale x 2 x i16>, <vscale x 2 x i16>} %retval, 1
  %res = sub <vscale x 2 x i16> %res.even, %res.odd
  %res2 = zext <vscale x 2 x i16> %res to <vscale x 2 x i64>
  ret <vscale x 2 x i64> %res2
}

define {<vscale x 4 x i32>, <vscale x 4 x i32>} @vector_deinterleave_nxv4i32_nxvv8i32(<vscale x 8 x i32> %vec) {
; CHECK-LABEL: vector_deinterleave_nxv4i32_nxvv8i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzp1 z2.q, z0.q, z1.q
; CHECK-NEXT:    uzp2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call {<vscale x 4 x i32>, <vscale x 4 x i32>} @llvm.vector.deinterleave.segments2.nxv8i32(<vscale x 8 x i32> %vec)
  ret {<vscale x 4 x i32>, <vscale x 4 x i32>} %retval
}

; Deinterleaving into 2 64-bit vectors
define <vscale x 2 x i64> @vector_deinterleave_nxv2i32_nxv4i32(<vscale x 4 x i32> %vec) {
; CHECK-SVE-LABEL: vector_deinterleave_nxv2i32_nxv4i32:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    uzp2 z1.d, z0.d, z0.d
; CHECK-SVE-NEXT:    uzp1 z0.d, z0.d, z0.d
; CHECK-SVE-NEXT:    ptrue p0.d
; CHECK-SVE-NEXT:    uunpklo z1.d, z1.s
; CHECK-SVE-NEXT:    uunpklo z0.d, z0.s
; CHECK-SVE-NEXT:    sub z0.d, z0.d, z1.d
; CHECK-SVE-NEXT:    sxtw z0.d, p0/m, z0.d
; CHECK-SVE-NEXT:    ret
;
; CHECK-SVE2p1-LABEL: vector_deinterleave_nxv2i32_nxv4i32:
; CHECK-SVE2p1:       // %bb.0:
; CHECK-SVE2p1-NEXT:    zipq2 z1.s, z0.s, z0.s
; CHECK-SVE2p1-NEXT:    zipq1 z0.s, z0.s, z0.s
; CHECK-SVE2p1-NEXT:    ptrue p0.d
; CHECK-SVE2p1-NEXT:    sub z0.d, z0.d, z1.d
; CHECK-SVE2p1-NEXT:    sxtw z0.d, p0/m, z0.d
; CHECK-SVE2p1-NEXT:    ret
  %retval = call {<vscale x 2 x i32>, <vscale x 2 x i32>} @llvm.vector.deinterleave.segments2.nxv4i32(<vscale x 4 x i32> %vec)
  %res.even = extractvalue {<vscale x 2 x i32>, <vscale x 2 x i32>} %retval, 0
  %res.odd = extractvalue {<vscale x 2 x i32>, <vscale x 2 x i32>} %retval, 1
  %res = sub <vscale x 2 x i32> %res.even, %res.odd
  %res2 = sext <vscale x 2 x i32> %res to <vscale x 2 x i64>
  ret <vscale x 2 x i64> %res2
}

define {<vscale x 2 x i64>, <vscale x 2 x i64>} @vector_deinterleave_nxv2i64_nxv4i64(<vscale x 4 x i64> %vec) {
; CHECK-LABEL: vector_deinterleave_nxv2i64_nxv4i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzp1 z2.q, z0.q, z1.q
; CHECK-NEXT:    uzp2 z1.q, z0.q, z1.q
; CHECK-NEXT:    mov z0.d, z2.d
; CHECK-NEXT:    ret
  %retval = call {<vscale x 2 x i64>, <vscale x 2 x i64>} @llvm.vector.deinterleave.segments2.nxv4i64(<vscale x 4 x i64> %vec)
  ret {<vscale x 2 x i64>, <vscale x 2 x i64>} %retval
}

define {<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>} @vector_deinterleave_nxv16i8_nxv64i8(<vscale x 64 x i8> %vec) {
; CHECK-LABEL: vector_deinterleave_nxv16i8_nxv64i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzp1 z4.q, z2.q, z3.q
; CHECK-NEXT:    uzp1 z5.q, z0.q, z1.q
; CHECK-NEXT:    uzp2 z3.q, z2.q, z3.q
; CHECK-NEXT:    uzp2 z6.q, z0.q, z1.q
; CHECK-NEXT:    uzp1 z0.q, z5.q, z4.q
; CHECK-NEXT:    uzp2 z2.q, z5.q, z4.q
; CHECK-NEXT:    uzp1 z1.q, z6.q, z3.q
; CHECK-NEXT:    uzp2 z3.q, z6.q, z3.q
; CHECK-NEXT:    ret
  %retval = call {<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>} @llvm.vector.deinterleave.segments4.nxv64i8(<vscale x 64 x i8> %vec)
  ret {<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>} %retval
}

define {<vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>} @vector_deinterleave_nxv8i16_nxv32i16(<vscale x 32 x i16> %vec) {
; CHECK-LABEL: vector_deinterleave_nxv8i16_nxv32i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzp1 z4.q, z2.q, z3.q
; CHECK-NEXT:    uzp1 z5.q, z0.q, z1.q
; CHECK-NEXT:    uzp2 z3.q, z2.q, z3.q
; CHECK-NEXT:    uzp2 z6.q, z0.q, z1.q
; CHECK-NEXT:    uzp1 z0.q, z5.q, z4.q
; CHECK-NEXT:    uzp2 z2.q, z5.q, z4.q
; CHECK-NEXT:    uzp1 z1.q, z6.q, z3.q
; CHECK-NEXT:    uzp2 z3.q, z6.q, z3.q
; CHECK-NEXT:    ret
  %retval = call {<vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>} @llvm.vector.deinterleave.segments4.nxv32i16(<vscale x 32 x i16> %vec)
  ret {<vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>} %retval
}

define {<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>} @vector_deinterleave_nxv4i32_nxv16i32(<vscale x 16 x i32> %vec) {
; CHECK-LABEL: vector_deinterleave_nxv4i32_nxv16i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzp1 z4.q, z2.q, z3.q
; CHECK-NEXT:    uzp1 z5.q, z0.q, z1.q
; CHECK-NEXT:    uzp2 z3.q, z2.q, z3.q
; CHECK-NEXT:    uzp2 z6.q, z0.q, z1.q
; CHECK-NEXT:    uzp1 z0.q, z5.q, z4.q
; CHECK-NEXT:    uzp2 z2.q, z5.q, z4.q
; CHECK-NEXT:    uzp1 z1.q, z6.q, z3.q
; CHECK-NEXT:    uzp2 z3.q, z6.q, z3.q
; CHECK-NEXT:    ret
  %retval = call {<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>} @llvm.vector.deinterleave.segments4.nxv16i32(<vscale x 16 x i32> %vec)
  ret {<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>} %retval
}

define {<vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>} @vector_deinterleave_nxv2i64_nxv8i64(<vscale x 8 x i64> %vec) {
; CHECK-LABEL: vector_deinterleave_nxv2i64_nxv8i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    uzp1 z4.q, z2.q, z3.q
; CHECK-NEXT:    uzp1 z5.q, z0.q, z1.q
; CHECK-NEXT:    uzp2 z3.q, z2.q, z3.q
; CHECK-NEXT:    uzp2 z6.q, z0.q, z1.q
; CHECK-NEXT:    uzp1 z0.q, z5.q, z4.q
; CHECK-NEXT:    uzp2 z2.q, z5.q, z4.q
; CHECK-NEXT:    uzp1 z1.q, z6.q, z3.q
; CHECK-NEXT:    uzp2 z3.q, z6.q, z3.q
; CHECK-NEXT:    ret
  %retval = call {<vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>} @llvm.vector.deinterleave.segments4.nxv8i64(<vscale x 8 x i64> %vec)
  ret {<vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>} %retval
}


define {<vscale x 2 x half>, <vscale x 2 x half>} @vector_deinterleave_nxv2f16_nxv4f16(<vscale x 4 x half> %vec) {
; CHECK-LABEL: vector_deinterleave_nxv2f16_nxv4f16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-2
; CHECK-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x40, 0x1e, 0x22 // sp + 16 + 16 * VG
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    st1h { z0.s }, p0, [sp, #3, mul vl]
; CHECK-NEXT:    ld1w { z0.d }, p1/z, [sp, #3, mul vl]
; CHECK-NEXT:    uzp1 z1.d, z0.d, z0.d
; CHECK-NEXT:    uzp2 z0.d, z0.d, z0.d
; CHECK-NEXT:    st1w { z1.d }, p1, [sp, #2, mul vl]
; CHECK-NEXT:    st1w { z0.d }, p1, [sp, #1, mul vl]
; CHECK-NEXT:    ld1h { z0.d }, p1/z, [sp, #4, mul vl]
; CHECK-NEXT:    ld1h { z1.d }, p1/z, [sp, #2, mul vl]
; CHECK-NEXT:    addvl sp, sp, #2
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %retval = call {<vscale x 2 x half>, <vscale x 2 x half>} @llvm.vector.deinterleave.segments2.nxv4f16(<vscale x 4 x half> %vec)
  ret {<vscale x 2 x half>, <vscale x 2 x half>} %retval
}

define {<vscale x 4 x half>, <vscale x 4 x half>} @vector_deinterleave_nxv4f16_nxv8f16(<vscale x 8 x half> %vec) {
; CHECK-SVE-LABEL: vector_deinterleave_nxv4f16_nxv8f16:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    uzp1 z1.d, z0.d, z0.d
; CHECK-SVE-NEXT:    uzp2 z2.d, z0.d, z0.d
; CHECK-SVE-NEXT:    uunpklo z0.s, z1.h
; CHECK-SVE-NEXT:    uunpklo z1.s, z2.h
; CHECK-SVE-NEXT:    ret
;
; CHECK-SVE2p1-LABEL: vector_deinterleave_nxv4f16_nxv8f16:
; CHECK-SVE2p1:       // %bb.0:
; CHECK-SVE2p1-NEXT:    zipq1 z2.h, z0.h, z0.h
; CHECK-SVE2p1-NEXT:    zipq2 z1.h, z0.h, z0.h
; CHECK-SVE2p1-NEXT:    mov z0.d, z2.d
; CHECK-SVE2p1-NEXT:    ret
  %retval = call {<vscale x 4 x half>, <vscale x 4 x half>} @llvm.vector.deinterleave.segments2.nxv8f16(<vscale x 8 x half> %vec)
  ret {<vscale x 4 x half>, <vscale x 4 x half>} %retval
}

define {<vscale x 2 x float>, <vscale x 2 x float>} @vector_deinterleave_nxv2f32_nxv4f32(<vscale x 4 x float> %vec) {
; CHECK-SVE-LABEL: vector_deinterleave_nxv2f32_nxv4f32:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    uzp1 z1.d, z0.d, z0.d
; CHECK-SVE-NEXT:    uzp2 z2.d, z0.d, z0.d
; CHECK-SVE-NEXT:    uunpklo z0.d, z1.s
; CHECK-SVE-NEXT:    uunpklo z1.d, z2.s
; CHECK-SVE-NEXT:    ret
;
; CHECK-SVE2p1-LABEL: vector_deinterleave_nxv2f32_nxv4f32:
; CHECK-SVE2p1:       // %bb.0:
; CHECK-SVE2p1-NEXT:    zipq1 z2.s, z0.s, z0.s
; CHECK-SVE2p1-NEXT:    zipq2 z1.s, z0.s, z0.s
; CHECK-SVE2p1-NEXT:    mov z0.d, z2.d
; CHECK-SVE2p1-NEXT:    ret
  %retval = call {<vscale x 2 x float>, <vscale x 2 x float>} @llvm.vector.deinterleave.segments2.nxv4f32(<vscale x 4 x float> %vec)
  ret {<vscale x 2 x float>, <vscale x 2 x float>} %retval
}

define {<vscale x 2 x bfloat>, <vscale x 2 x bfloat>} @vector_deinterleave_nxv2bf16_nxv4bf16(<vscale x 4 x bfloat> %vec) {
; CHECK-LABEL: vector_deinterleave_nxv2bf16_nxv4bf16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-2
; CHECK-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x40, 0x1e, 0x22 // sp + 16 + 16 * VG
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    st1h { z0.s }, p0, [sp, #3, mul vl]
; CHECK-NEXT:    ld1w { z0.d }, p1/z, [sp, #3, mul vl]
; CHECK-NEXT:    uzp1 z1.d, z0.d, z0.d
; CHECK-NEXT:    uzp2 z0.d, z0.d, z0.d
; CHECK-NEXT:    st1w { z1.d }, p1, [sp, #2, mul vl]
; CHECK-NEXT:    st1w { z0.d }, p1, [sp, #1, mul vl]
; CHECK-NEXT:    ld1h { z0.d }, p1/z, [sp, #4, mul vl]
; CHECK-NEXT:    ld1h { z1.d }, p1/z, [sp, #2, mul vl]
; CHECK-NEXT:    addvl sp, sp, #2
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %retval = call {<vscale x 2 x bfloat>, <vscale x 2 x bfloat>} @llvm.vector.deinterleave.segments2.nxv4bf16(<vscale x 4 x bfloat> %vec)
  ret {<vscale x 2 x bfloat>, <vscale x 2 x bfloat>} %retval
}

define {<vscale x 4 x bfloat>, <vscale x 4 x bfloat>} @vector_deinterleave_nxv4bf16_nxv8bf16(<vscale x 8 x bfloat> %vec) {
; CHECK-SVE-LABEL: vector_deinterleave_nxv4bf16_nxv8bf16:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    uzp1 z1.d, z0.d, z0.d
; CHECK-SVE-NEXT:    uzp2 z2.d, z0.d, z0.d
; CHECK-SVE-NEXT:    uunpklo z0.s, z1.h
; CHECK-SVE-NEXT:    uunpklo z1.s, z2.h
; CHECK-SVE-NEXT:    ret
;
; CHECK-SVE2p1-LABEL: vector_deinterleave_nxv4bf16_nxv8bf16:
; CHECK-SVE2p1:       // %bb.0:
; CHECK-SVE2p1-NEXT:    zipq1 z2.h, z0.h, z0.h
; CHECK-SVE2p1-NEXT:    zipq2 z1.h, z0.h, z0.h
; CHECK-SVE2p1-NEXT:    mov z0.d, z2.d
; CHECK-SVE2p1-NEXT:    ret
  %retval = call {<vscale x 4 x bfloat>, <vscale x 4 x bfloat>} @llvm.vector.deinterleave.segments2.nxv8bf16(<vscale x 8 x bfloat> %vec)
  ret {<vscale x 4 x bfloat>, <vscale x 4 x bfloat>} %retval
}
