; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc --enable-no-signed-zeros-fp-math -mattr=+sve < %s | FileCheck %s
; RUN: llc -mattr=+sve < %s | FileCheck %s --check-prefix=SIGNED-ZEROS

target triple = "aarch64-unknown-linux-gnu"

; Check that fp -> int -> fp conversions can be
; lowered to the SVE FRINTZ instructions for
; scalable vectors.

define <vscale x 4 x float> @frintz_f32_i32_f32(<vscale x 4 x float> %in) {
; CHECK-LABEL: frintz_f32_i32_f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    frintz z0.s, p0/m, z0.s
; CHECK-NEXT:    ret
;
; SIGNED-ZEROS-LABEL: frintz_f32_i32_f32:
; SIGNED-ZEROS:       // %bb.0:
; SIGNED-ZEROS-NEXT:    ptrue p0.s
; SIGNED-ZEROS-NEXT:    fcvtzs z0.s, p0/m, z0.s
; SIGNED-ZEROS-NEXT:    scvtf z0.s, p0/m, z0.s
; SIGNED-ZEROS-NEXT:    ret
  %res = fptosi <vscale x 4 x float> %in to <vscale x 4 x i32>
  %res2 = sitofp <vscale x 4 x i32> %res to <vscale x 4 x float>
  ret <vscale x 4 x float> %res2
}

define <vscale x 2 x double> @frintz_f64_i32_f64(<vscale x 2 x double> %in) {
; CHECK-LABEL: frintz_f64_i32_f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    frintz z0.d, p0/m, z0.d
; CHECK-NEXT:    ret
;
; SIGNED-ZEROS-LABEL: frintz_f64_i32_f64:
; SIGNED-ZEROS:       // %bb.0:
; SIGNED-ZEROS-NEXT:    ptrue p0.d
; SIGNED-ZEROS-NEXT:    fcvtzs z0.d, p0/m, z0.d
; SIGNED-ZEROS-NEXT:    scvtf z0.d, p0/m, z0.d
; SIGNED-ZEROS-NEXT:    ret
  %res = fptosi <vscale x 2 x double> %in to <vscale x 2 x i32>
  %res2 = sitofp <vscale x 2 x i32> %res to <vscale x 2 x double>
  ret <vscale x 2 x double> %res2
}

define <vscale x 8 x float> @frintz_f32_i32_f32_nxv8i32(<vscale x 8 x float> %in) {
; CHECK-LABEL: frintz_f32_i32_f32_nxv8i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    frintz z0.s, p0/m, z0.s
; CHECK-NEXT:    frintz z1.s, p0/m, z1.s
; CHECK-NEXT:    ret
;
; SIGNED-ZEROS-LABEL: frintz_f32_i32_f32_nxv8i32:
; SIGNED-ZEROS:       // %bb.0:
; SIGNED-ZEROS-NEXT:    ptrue p0.s
; SIGNED-ZEROS-NEXT:    fcvtzs z1.s, p0/m, z1.s
; SIGNED-ZEROS-NEXT:    fcvtzs z0.s, p0/m, z0.s
; SIGNED-ZEROS-NEXT:    scvtf z0.s, p0/m, z0.s
; SIGNED-ZEROS-NEXT:    scvtf z1.s, p0/m, z1.s
; SIGNED-ZEROS-NEXT:    ret
  %res = fptosi <vscale x 8 x float> %in to <vscale x 8 x i32>
  %res2 = sitofp <vscale x 8 x i32> %res to <vscale x 8 x float>
  ret <vscale x 8 x float> %res2
}

define <vscale x 2 x double> @frintz_f64_i64_f64(<vscale x 2 x double> %in) {
; CHECK-LABEL: frintz_f64_i64_f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    frintz z0.d, p0/m, z0.d
; CHECK-NEXT:    ret
;
; SIGNED-ZEROS-LABEL: frintz_f64_i64_f64:
; SIGNED-ZEROS:       // %bb.0:
; SIGNED-ZEROS-NEXT:    ptrue p0.d
; SIGNED-ZEROS-NEXT:    fcvtzs z0.d, p0/m, z0.d
; SIGNED-ZEROS-NEXT:    scvtf z0.d, p0/m, z0.d
; SIGNED-ZEROS-NEXT:    ret
  %res = fptosi <vscale x 2 x double> %in to <vscale x 2 x i64>
  %res2 = sitofp <vscale x 2 x i64> %res to <vscale x 2 x double>
  ret <vscale x 2 x double> %res2
}

define <vscale x 4 x float> @frintz_f32_i64_f32(<vscale x 4 x float> %in) {
; CHECK-LABEL: frintz_f32_i64_f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    frintz z0.s, p0/m, z0.s
; CHECK-NEXT:    ret
;
; SIGNED-ZEROS-LABEL: frintz_f32_i64_f32:
; SIGNED-ZEROS:       // %bb.0:
; SIGNED-ZEROS-NEXT:    uunpklo z1.d, z0.s
; SIGNED-ZEROS-NEXT:    uunpkhi z0.d, z0.s
; SIGNED-ZEROS-NEXT:    ptrue p0.d
; SIGNED-ZEROS-NEXT:    fcvtzs z1.d, p0/m, z1.s
; SIGNED-ZEROS-NEXT:    fcvtzs z0.d, p0/m, z0.s
; SIGNED-ZEROS-NEXT:    scvtf z0.s, p0/m, z0.d
; SIGNED-ZEROS-NEXT:    scvtf z1.s, p0/m, z1.d
; SIGNED-ZEROS-NEXT:    uzp1 z0.s, z1.s, z0.s
; SIGNED-ZEROS-NEXT:    ret
  %res = fptosi <vscale x 4 x float> %in to <vscale x 4 x i64>
  %res2 = sitofp <vscale x 4 x i64> %res to <vscale x 4 x float>
  ret <vscale x 4 x float> %res2
}

define <vscale x 4 x double> @frintz_f64_i64_f64_nxv4i64(<vscale x 4 x double> %in) {
; CHECK-LABEL: frintz_f64_i64_f64_nxv4i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    frintz z0.d, p0/m, z0.d
; CHECK-NEXT:    frintz z1.d, p0/m, z1.d
; CHECK-NEXT:    ret
;
; SIGNED-ZEROS-LABEL: frintz_f64_i64_f64_nxv4i64:
; SIGNED-ZEROS:       // %bb.0:
; SIGNED-ZEROS-NEXT:    ptrue p0.d
; SIGNED-ZEROS-NEXT:    fcvtzs z1.d, p0/m, z1.d
; SIGNED-ZEROS-NEXT:    fcvtzs z0.d, p0/m, z0.d
; SIGNED-ZEROS-NEXT:    scvtf z0.d, p0/m, z0.d
; SIGNED-ZEROS-NEXT:    scvtf z1.d, p0/m, z1.d
; SIGNED-ZEROS-NEXT:    ret
  %res = fptosi <vscale x 4 x double> %in to <vscale x 4 x i64>
  %res2 = sitofp <vscale x 4 x i64> %res to <vscale x 4 x double>
  ret <vscale x 4 x double> %res2
}
