; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s | FileCheck %s

target triple = "aarch64-unknown-linux-gnu"

define void @pred_store_v2i8(<vscale x 16 x i1> %pred, ptr %addr) #0 {
; CHECK-LABEL: pred_store_v2i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x38, 0x1e, 0x22 // sp + 16 + 8 * VG
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    str p0, [sp, #7, mul vl]
; CHECK-NEXT:    ld1b { z0.d }, p1/z, [sp, #7, mul vl]
; CHECK-NEXT:    mov z1.s, z0.s[2]
; CHECK-NEXT:    str b0, [x0]
; CHECK-NEXT:    stur b1, [x0, #1]
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %bitcast = bitcast <vscale x 16 x i1> %pred to <vscale x 2 x i8>
  %extract = tail call <2 x i8> @llvm.vector.extract.v2i8.nxv2i8(<vscale x 2 x i8> %bitcast, i64 0)
  store <2 x i8> %extract, ptr %addr, align 4
  ret void
}

define void @pred_store_v4i8(<vscale x 16 x i1> %pred, ptr %addr) #1 {
; CHECK-LABEL: pred_store_v4i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x38, 0x1e, 0x22 // sp + 16 + 8 * VG
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    str p0, [sp, #7, mul vl]
; CHECK-NEXT:    ptrue p0.h, vl4
; CHECK-NEXT:    ld1b { z0.d }, p1/z, [sp, #7, mul vl]
; CHECK-NEXT:    mov w8, v0.s[2]
; CHECK-NEXT:    mov v1.16b, v0.16b
; CHECK-NEXT:    mov z2.s, z0.s[4]
; CHECK-NEXT:    mov z0.s, z0.s[6]
; CHECK-NEXT:    mov v1.h[1], w8
; CHECK-NEXT:    fmov w8, s2
; CHECK-NEXT:    mov v1.h[2], w8
; CHECK-NEXT:    fmov w8, s0
; CHECK-NEXT:    mov v1.h[3], w8
; CHECK-NEXT:    st1b { z1.h }, p0, [x0]
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %bitcast = bitcast <vscale x 16 x i1> %pred to <vscale x 2 x i8>
  %extract = tail call <4 x i8> @llvm.vector.extract.v4i8.nxv2i8(<vscale x 2 x i8> %bitcast, i64 0)
  store <4 x i8> %extract, ptr %addr, align 4
  ret void
}

define void @pred_store_v8i8(<vscale x 16 x i1> %pred, ptr %addr) #2 {
; CHECK-LABEL: pred_store_v8i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x38, 0x1e, 0x22 // sp + 16 + 8 * VG
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    str p0, [sp, #7, mul vl]
; CHECK-NEXT:    ld1b { z0.d }, p1/z, [sp, #7, mul vl]
; CHECK-NEXT:    st1b { z0.d }, p1, [x0]
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %bitcast = bitcast <vscale x 16 x i1> %pred to <vscale x 2 x i8>
  %extract = tail call <8 x i8> @llvm.vector.extract.v8i8.nxv2i8(<vscale x 2 x i8> %bitcast, i64 0)
  store <8 x i8> %extract, ptr %addr, align 4
  ret void
}


; Check that too small of a vscale prevents optimization
define void @pred_store_neg1(<vscale x 16 x i1> %pred, ptr %addr) #0 {
; CHECK-LABEL: pred_store_neg1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x38, 0x1e, 0x22 // sp + 16 + 8 * VG
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    str p0, [sp, #7, mul vl]
; CHECK-NEXT:    ld1b { z0.d }, p1/z, [sp, #7, mul vl]
; CHECK-NEXT:    mov w8, v0.s[2]
; CHECK-NEXT:    mov z2.s, z0.s[4]
; CHECK-NEXT:    mov z1.s, z0.s[6]
; CHECK-NEXT:    mov v0.h[1], w8
; CHECK-NEXT:    fmov w8, s2
; CHECK-NEXT:    mov v0.h[2], w8
; CHECK-NEXT:    fmov w8, s1
; CHECK-NEXT:    mov v0.h[3], w8
; CHECK-NEXT:    xtn v0.8b, v0.8h
; CHECK-NEXT:    str s0, [x0]
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %bitcast = bitcast <vscale x 16 x i1> %pred to <vscale x 2 x i8>
  %extract = tail call <4 x i8> @llvm.vector.extract.v4i8.nxv2i8(<vscale x 2 x i8> %bitcast, i64 0)
  store <4 x i8> %extract, ptr %addr, align 4
  ret void
}

; Check that too large of a vscale prevents optimization
define void @pred_store_neg2(<vscale x 16 x i1> %pred, ptr %addr) #2 {
; CHECK-LABEL: pred_store_neg2:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x38, 0x1e, 0x22 // sp + 16 + 8 * VG
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    str p0, [sp, #7, mul vl]
; CHECK-NEXT:    ptrue p0.h, vl4
; CHECK-NEXT:    ld1b { z0.d }, p1/z, [sp, #7, mul vl]
; CHECK-NEXT:    mov w8, v0.s[2]
; CHECK-NEXT:    mov v1.16b, v0.16b
; CHECK-NEXT:    mov z2.s, z0.s[4]
; CHECK-NEXT:    mov z0.s, z0.s[6]
; CHECK-NEXT:    mov v1.h[1], w8
; CHECK-NEXT:    fmov w8, s2
; CHECK-NEXT:    mov v1.h[2], w8
; CHECK-NEXT:    fmov w8, s0
; CHECK-NEXT:    mov v1.h[3], w8
; CHECK-NEXT:    st1b { z1.h }, p0, [x0]
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %bitcast = bitcast <vscale x 16 x i1> %pred to <vscale x 2 x i8>
  %extract = tail call <4 x i8> @llvm.vector.extract.v4i8.nxv2i8(<vscale x 2 x i8> %bitcast, i64 0)
  store <4 x i8> %extract, ptr %addr, align 4
  ret void
}

; Check that a non-zero index prevents optimization
define void @pred_store_neg3(<vscale x 16 x i1> %pred, ptr %addr) #1 {
; CHECK-LABEL: pred_store_neg3:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x38, 0x1e, 0x22 // sp + 16 + 8 * VG
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    str p0, [sp, #7, mul vl]
; CHECK-NEXT:    ptrue p0.h, vl4
; CHECK-NEXT:    ld1b { z0.d }, p1/z, [sp, #7, mul vl]
; CHECK-NEXT:    mov z1.s, z0.s[10]
; CHECK-NEXT:    mov z2.s, z0.s[8]
; CHECK-NEXT:    fmov w8, s1
; CHECK-NEXT:    mov z1.s, z0.s[12]
; CHECK-NEXT:    mov z0.s, z0.s[14]
; CHECK-NEXT:    mov v2.h[1], w8
; CHECK-NEXT:    fmov w8, s1
; CHECK-NEXT:    mov v2.h[2], w8
; CHECK-NEXT:    fmov w8, s0
; CHECK-NEXT:    mov v2.h[3], w8
; CHECK-NEXT:    st1b { z2.h }, p0, [x0]
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %bitcast = bitcast <vscale x 16 x i1> %pred to <vscale x 2 x i8>
  %extract = tail call <4 x i8> @llvm.vector.extract.v4i8.nxv2i8(<vscale x 2 x i8> %bitcast, i64 4)
  store <4 x i8> %extract, ptr %addr, align 4
  ret void
}

; Check that differing vscale min/max prevents optimization
define void @pred_store_neg4(<vscale x 16 x i1> %pred, ptr %addr) #3 {
; CHECK-LABEL: pred_store_neg4:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x38, 0x1e, 0x22 // sp + 16 + 8 * VG
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    str p0, [sp, #7, mul vl]
; CHECK-NEXT:    ptrue p0.h, vl4
; CHECK-NEXT:    ld1b { z0.d }, p1/z, [sp, #7, mul vl]
; CHECK-NEXT:    mov w8, v0.s[2]
; CHECK-NEXT:    mov v1.16b, v0.16b
; CHECK-NEXT:    mov z2.s, z0.s[4]
; CHECK-NEXT:    mov z0.s, z0.s[6]
; CHECK-NEXT:    mov v1.h[1], w8
; CHECK-NEXT:    fmov w8, s2
; CHECK-NEXT:    mov v1.h[2], w8
; CHECK-NEXT:    fmov w8, s0
; CHECK-NEXT:    mov v1.h[3], w8
; CHECK-NEXT:    st1b { z1.h }, p0, [x0]
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %bitcast = bitcast <vscale x 16 x i1> %pred to <vscale x 2 x i8>
  %extract = tail call <4 x i8> @llvm.vector.extract.v4i8.nxv2i8(<vscale x 2 x i8> %bitcast, i64 0)
  store <4 x i8> %extract, ptr %addr, align 4
  ret void
}

; Variant of pred_store_v2i8 where <2 x i8> has other uses.
define void @pred_store_v2i8_multiuse(<vscale x 16 x i1> %pred, ptr %addr) #0 {
; CHECK-LABEL: pred_store_v2i8_multiuse:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x38, 0x1e, 0x22 // sp + 16 + 8 * VG
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    str p0, [sp, #7, mul vl]
; CHECK-NEXT:    ld1b { z0.d }, p1/z, [sp, #7, mul vl]
; CHECK-NEXT:    movprfx z1, z0
; CHECK-NEXT:    ext z1.b, z1.b, z0.b, #8
; CHECK-NEXT:    uzp1 v1.2s, v0.2s, v1.2s
; CHECK-NEXT:    // fake_use: $d1
; CHECK-NEXT:    mov z1.s, z0.s[2]
; CHECK-NEXT:    str b0, [x0]
; CHECK-NEXT:    stur b1, [x0, #1]
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %bitcast = bitcast <vscale x 16 x i1> %pred to <vscale x 2 x i8>
  %extract = tail call <2 x i8> @llvm.vector.extract.v2i8.nxv2i8(<vscale x 2 x i8> %bitcast, i64 0)
  call void (...) @llvm.fake.use(<2 x i8> %extract)
  store <2 x i8> %extract, ptr %addr, align 4
  ret void
}

attributes #0 = { "target-features"="+sve" vscale_range(1,1) }
attributes #1 = { "target-features"="+sve" vscale_range(2,2) }
attributes #2 = { "target-features"="+sve" vscale_range(4,4) }
attributes #3 = { "target-features"="+sve" vscale_range(2,4) }
