; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -mattr=+sve2p2 < %s | FileCheck %s

define <vscale x 4 x i32> @lrint_nxv4f16_nxv4i32(<vscale x 4 x half> %x) {
; CHECK-LABEL: lrint_nxv4f16_nxv4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov z1.h, #-1025 // =0xfffffffffffffbff
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    mov w8, #31743 // =0x7bff
; CHECK-NEXT:    mov z2.s, #0x80000000
; CHECK-NEXT:    frintx z0.h, p0/z, z0.h
; CHECK-NEXT:    fcmge p1.h, p0/z, z0.h, z1.h
; CHECK-NEXT:    mov z1.h, w8
; CHECK-NEXT:    fcvtzs z2.s, p1/m, z0.h
; CHECK-NEXT:    fcmgt p1.h, p0/z, z0.h, z1.h
; CHECK-NEXT:    mov z1.s, #0x7fffffff
; CHECK-NEXT:    fcmuo p0.h, p0/z, z0.h, z0.h
; CHECK-NEXT:    sel z0.s, p1, z1.s, z2.s
; CHECK-NEXT:    mov z0.s, p0/m, #0 // =0x0
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i32> @llvm.lrint.nxv4i32.nxv4f16(<vscale x 4 x half> %x)
  ret <vscale x 4 x i32> %a
}

define <4 x i32> @lrint_v4f16_v4i32(<4 x half> %x) {
; CHECK-LABEL: lrint_v4f16_v4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frintx v0.4h, v0.4h
; CHECK-NEXT:    fcvtl v0.4s, v0.4h
; CHECK-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-NEXT:    ret
  %a = call <4 x i32> @llvm.lrint.v4i32.v4f16(<4 x half> %x)
  ret <4 x i32> %a
}

define <vscale x 4 x i32> @lrint_nxv4f32_nxv4i32(<vscale x 4 x float> %x) {
; CHECK-LABEL: lrint_nxv4f32_nxv4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    frint32x z0.s, p0/z, z0.s
; CHECK-NEXT:    fcvtzs z0.s, p0/z, z0.s
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i32> @llvm.lrint.nxv4i32.nxv4f32(<vscale x 4 x float> %x)
  ret <vscale x 4 x i32> %a
}

define <4 x i32> @lrint_v4f32_v4i32(<4 x float> %x) {
; CHECK-LABEL: lrint_v4f32_v4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frintx v0.4s, v0.4s
; CHECK-NEXT:    fcvtzs v0.4s, v0.4s
; CHECK-NEXT:    ret
  %a = call <4 x i32> @llvm.lrint.v4f32.v4i32(<4 x float> %x)
  ret <4 x i32> %a
}

define <vscale x 2 x i32> @lrint_v2_nxv2f64_nxv2i32(<vscale x 2 x double> %x) {
; CHECK-LABEL: lrint_v2_nxv2f64_nxv2i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    frint64x z0.d, p0/z, z0.d
; CHECK-NEXT:    fcvtzs z0.d, p0/z, z0.d
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i32> @llvm.lrint.nxv2i32.nxv2f64(<vscale x 2 x double> %x)
  ret <vscale x 2 x i32> %a
}

define <2 x i32> @lrint_v2f64_v2i32(<2 x double> %x) {
; CHECK-LABEL: lrint_v2f64_v2i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frintx v0.2d, v0.2d
; CHECK-NEXT:    mov d1, v0.d[1]
; CHECK-NEXT:    fcvtzs w8, d0
; CHECK-NEXT:    fcvtzs w9, d1
; CHECK-NEXT:    fmov s0, w8
; CHECK-NEXT:    mov v0.s[1], w9
; CHECK-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-NEXT:    ret
  %a = call <2 x i32> @llvm.lrint.v2f64.v2i32(<2 x double> %x)
  ret <2 x i32> %a
}

define <vscale x 2 x i64> @lrint_nxv2f32_nxvi64(<vscale x 2 x float> %x) {
; CHECK-LABEL: lrint_nxv2f32_nxvi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    frint64x z0.s, p0/z, z0.s
; CHECK-NEXT:    fcvtzs z0.d, p0/m, z0.s
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i64> @llvm.lrint.nxv2i64.nxv2f32(<vscale x 2 x float> %x)
  ret <vscale x 2 x i64> %a
}

define <2 x i64> @lrint_v2f32_v2i64(<2 x float> %x) {
; CHECK-LABEL: lrint_v2f32_v2i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frintx v0.2s, v0.2s
; CHECK-NEXT:    fcvtl v0.2d, v0.2s
; CHECK-NEXT:    fcvtzs v0.2d, v0.2d
; CHECK-NEXT:    ret
  %a = call <2 x i64> @llvm.lrint.v2f32.v2i64(<2 x float> %x)
  ret <2 x i64> %a
}

define <vscale x 2 x i64> @lrint_v2_nxv2f64_nxv2i64(<vscale x 2 x double> %x) {
; CHECK-LABEL: lrint_v2_nxv2f64_nxv2i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    frint64x z0.d, p0/z, z0.d
; CHECK-NEXT:    fcvtzs z0.d, p0/z, z0.d
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i64> @llvm.lrint.nxv2i64.nxv2f64(<vscale x 2 x double> %x)
  ret <vscale x 2 x i64> %a
}

define <2 x i64> @lrint_v2f64_v2i64(<2 x double> %x) {
; CHECK-LABEL: lrint_v2f64_v2i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frintx v0.2d, v0.2d
; CHECK-NEXT:    fcvtzs v0.2d, v0.2d
; CHECK-NEXT:    ret
  %a = call <2 x i64> @llvm.lrint.v2f64.v2i64(<2 x double> %x)
  ret <2 x i64> %a
}

define void @lrint_v4f32_v4i64(<4 x float> %x, ptr %dst) vscale_range(2, 16) {
; CHECK-LABEL: lrint_v4f32_v4i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-NEXT:    frint64x z0.s, p0/z, z0.s
; CHECK-NEXT:    fcvtzs z0.d, p0/m, z0.s
; CHECK-NEXT:    ptrue p0.d, vl4
; CHECK-NEXT:    st1d { z0.d }, p0, [x0]
; CHECK-NEXT:    ret
  %a = call <4 x i64> @llvm.lrint.v4i64.v4f32(<4 x float> %x)
  store <4 x i64> %a, ptr %dst
  ret void
}

define <vscale x 2 x i64> @llrint_nxv2f32_nxv2i64(<vscale x 2 x float> %x) {
; CHECK-LABEL: llrint_nxv2f32_nxv2i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    frint64x z0.s, p0/z, z0.s
; CHECK-NEXT:    fcvtzs z0.d, p0/m, z0.s
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i64> @llvm.llrint.nxv2i64.nxv2f32(<vscale x 2 x float> %x)
  ret <vscale x 2 x i64> %a
}

define <2 x i64> @llrint_v2f32_v2i64(<2 x float> %x) {
; CHECK-LABEL: llrint_v2f32_v2i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frintx v0.2s, v0.2s
; CHECK-NEXT:    fcvtl v0.2d, v0.2s
; CHECK-NEXT:    fcvtzs v0.2d, v0.2d
; CHECK-NEXT:    ret
  %a = call <2 x i64> @llvm.lrint.v2f32.v2i64(<2 x float> %x)
  ret <2 x i64> %a
}

define <vscale x 2 x i64> @llrint_nxv2f64_nxv2f64(<vscale x 2 x double> %x) {
; CHECK-LABEL: llrint_nxv2f64_nxv2f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    frint64x z0.d, p0/z, z0.d
; CHECK-NEXT:    fcvtzs z0.d, p0/z, z0.d
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i64> @llvm.llrint.nxv2i64.nxv2f64(<vscale x 2 x double> %x)
  ret <vscale x 2 x i64> %a
}

define <2 x i64> @llrint_v2f64_v2i64(<2 x double> %x) {
; CHECK-LABEL: llrint_v2f64_v2i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frintx v0.2d, v0.2d
; CHECK-NEXT:    fcvtzs v0.2d, v0.2d
; CHECK-NEXT:    ret
  %a = call <2 x i64> @llvm.lrint.v2f64.v2i64(<2 x double> %x)
  ret <2 x i64> %a
}

define void @llrint_v4f32_v4i64(<4 x float> %x, ptr %dst) vscale_range(2, 16) {
; CHECK-LABEL: llrint_v4f32_v4i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-NEXT:    frint64x z0.s, p0/z, z0.s
; CHECK-NEXT:    fcvtzs z0.d, p0/m, z0.s
; CHECK-NEXT:    ptrue p0.d, vl4
; CHECK-NEXT:    st1d { z0.d }, p0, [x0]
; CHECK-NEXT:    ret
  %a = call <4 x i64> @llvm.llrint.v4i64.v4f32(<4 x float> %x)
  store <4 x i64> %a, ptr %dst
  ret void
}


