; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=aarch64 -mattr=+sve2p1 -o - %s | FileCheck %s

define <16 x i8> @partial_reduce_scalable_zero_v16i8(<16 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_scalable_zero_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    addqv v0.16b, p0, z1.b
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <16 x i8> @llvm.vector.partial.reduce.add.v16i8.v16i8.nxv16i8(<16 x i8> zeroinitializer, <vscale x 16 x i8> %0)
  ret <16 x i8> %partial.reduce
}

define <8 x i8> @partial_reduce_scalable_zero_nxv16i8_v8i8(<8 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_scalable_zero_nxv16i8_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    addqv v0.16b, p0, z1.b
; CHECK-NEXT:    mov d1, v0.d[1]
; CHECK-NEXT:    add v0.8b, v0.8b, v1.8b
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <8 x i8> @llvm.vector.partial.reduce.add.v8i8.v8i8.nxv16i8(<8 x i8> zeroinitializer, <vscale x 16 x i8> %0)
  ret <8 x i8> %partial.reduce
}

define <8 x i8> @partial_reduce_scalable_zero_nxv8i8_v8i8(<8 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_scalable_zero_nxv8i8_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uunpklo z0.h, z1.b
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    addqv v0.8h, p0, z0.h
; CHECK-NEXT:    xtn v0.8b, v0.8h
; CHECK-NEXT:    ret
entry:
  %1 = call <vscale x 8 x i8> @llvm.vector.extract.nxv8i8.nxv16i8(<vscale x 16 x i8> %0, i64 0)
  %partial.reduce = call <8 x i8> @llvm.vector.partial.reduce.add.v8i8.v8i8.nxv8i8(<8 x i8> zeroinitializer, <vscale x 8 x i8> %1)
  ret <8 x i8> %partial.reduce
}

define <16 x i8> @partial_reduce_scalable_acc_v16i8(<16 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_scalable_acc_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    addqv v1.16b, p0, z1.b
; CHECK-NEXT:    add v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <16 x i8> @llvm.vector.partial.reduce.add.v16i8.v16i8.nxv16i8(<16 x i8> %accumulator, <vscale x 16 x i8> %0)
  ret <16 x i8> %partial.reduce
}

define <8 x i8> @partial_reduce_scalable_acc_nxv16i8_v8i8(<8 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_scalable_acc_nxv16i8_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    addqv v1.16b, p0, z1.b
; CHECK-NEXT:    mov d2, v1.d[1]
; CHECK-NEXT:    add v0.8b, v1.8b, v0.8b
; CHECK-NEXT:    add v0.8b, v0.8b, v2.8b
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <8 x i8> @llvm.vector.partial.reduce.add.v8i8.v8i8.nxv16i8(<8 x i8> %accumulator, <vscale x 16 x i8> %0)
  ret <8 x i8> %partial.reduce
}

define <8 x i8> @partial_reduce_scalable_acc_nxv8i8_v8i8(<8 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_scalable_acc_nxv8i8_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uunpklo z1.h, z1.b
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    addqv v1.8h, p0, z1.h
; CHECK-NEXT:    uaddw v0.8h, v1.8h, v0.8b
; CHECK-NEXT:    xtn v0.8b, v0.8h
; CHECK-NEXT:    ret
entry:
  %1 = call <vscale x 8 x i8> @llvm.vector.extract.nxv8i8.nxv16i8(<vscale x 16 x i8> %0, i64 0)
  %partial.reduce = call <8 x i8> @llvm.vector.partial.reduce.add.v8i8.v8i8.nxv8i8(<8 x i8> %accumulator, <vscale x 8 x i8> %1)
  ret <8 x i8> %partial.reduce
}

define <8 x i16> @partial_reduce_scalable_zero_v8i16(<8 x i16> %accumulator, <vscale x 8 x i16> %0) #0 {
; CHECK-LABEL: partial_reduce_scalable_zero_v8i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    addqv v0.8h, p0, z1.h
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <8 x i16> @llvm.vector.partial.reduce.add.v8i16.v8i16.nxv8i16(<8 x i16> zeroinitializer, <vscale x 8 x i16> %0)
  ret <8 x i16> %partial.reduce
}

define <8 x i16> @partial_reduce_scalable_acc_v8i16(<8 x i16> %accumulator, <vscale x 8 x i16> %0) #0 {
; CHECK-LABEL: partial_reduce_scalable_acc_v8i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    addqv v1.8h, p0, z1.h
; CHECK-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <8 x i16> @llvm.vector.partial.reduce.add.v8i16.v8i16.nxv8i16(<8 x i16> %accumulator, <vscale x 8 x i16> %0)
  ret <8 x i16> %partial.reduce
}

define <4 x i32> @partial_reduce_scalable_zero_v4i32(<4 x i32> %accumulator, <vscale x 4 x i32> %0) #0 {
; CHECK-LABEL: partial_reduce_scalable_zero_v4i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    addqv v0.4s, p0, z1.s
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v4i32.nxv4i32(<4 x i32> zeroinitializer, <vscale x 4 x i32> %0)
  ret <4 x i32> %partial.reduce
}

define <4 x i32> @partial_reduce_scalable_acc_v4i32(<4 x i32> %accumulator, <vscale x 4 x i32> %0) #0 {
; CHECK-LABEL: partial_reduce_scalable_acc_v4i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    addqv v1.4s, p0, z1.s
; CHECK-NEXT:    add v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v4i32.nxv4i32(<4 x i32> %accumulator, <vscale x 4 x i32> %0)
  ret <4 x i32> %partial.reduce
}

define <2 x i64> @partial_reduce_scalable_zero_v2i64(<2 x i64> %accumulator, <vscale x 2 x i64> %0) #0 {
; CHECK-LABEL: partial_reduce_scalable_zero_v2i64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    addqv v0.2d, p0, z1.d
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <2 x i64> @llvm.vector.partial.reduce.add.v2i64.v2i64.nxv2i64(<2 x i64> zeroinitializer, <vscale x 2 x i64> %0)
  ret <2 x i64> %partial.reduce
}

define <2 x i64> @partial_reduce_scalable_acc_v2i64(<2 x i64> %accumulator, <vscale x 2 x i64> %0) #0 {
; CHECK-LABEL: partial_reduce_scalable_acc_v2i64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    addqv v1.2d, p0, z1.d
; CHECK-NEXT:    add v0.2d, v0.2d, v1.2d
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <2 x i64> @llvm.vector.partial.reduce.add.v2i64.v2i64.nxv2i64(<2 x i64> %accumulator, <vscale x 2 x i64> %0)
  ret <2 x i64> %partial.reduce
}
