; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -mattr=+sve2p1 -o - %s | FileCheck %s

define <16 x i8> @partial_reduce_smax_scalable_zero_v16i8(<16 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_smax_scalable_zero_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    smaxqv v0.16b, p0, z1.b
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <16 x i8> @llvm.vector.partial.reduce.smax.v16i8.v16i8.nxv16i8(<16 x i8> splat (i8 -128), <vscale x 16 x i8> %0)
  ret <16 x i8> %partial.reduce
}

define <16 x i8> @partial_reduce_smax_scalable_acc_v16i8(<16 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_smax_scalable_acc_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    smaxqv v1.16b, p0, z1.b
; CHECK-NEXT:    smax v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <16 x i8> @llvm.vector.partial.reduce.smax.v16i8.v16i8.nxv16i8(<16 x i8> %accumulator, <vscale x 16 x i8> %0)
  ret <16 x i8> %partial.reduce
}

define <8 x i8> @partial_reduce_smax_scalable_neutral_nxv16i8_v8i8(<8 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_smax_scalable_neutral_nxv16i8_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    smaxqv v0.16b, p0, z1.b
; CHECK-NEXT:    mov d1, v0.d[1]
; CHECK-NEXT:    smax v0.8b, v0.8b, v1.8b
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <8 x i8> @llvm.vector.partial.reduce.smax.v8i8.v8i8.nxv16i8(<8 x i8> splat (i8 -128), <vscale x 16 x i8> %0)
  ret <8 x i8> %partial.reduce
}

define <8 x i8> @partial_reduce_smax_scalable_acc_nxv16i8_v8i8(<8 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_smax_scalable_acc_nxv16i8_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    smaxqv v1.16b, p0, z1.b
; CHECK-NEXT:    mov d2, v1.d[1]
; CHECK-NEXT:    smax v1.8b, v1.8b, v2.8b
; CHECK-NEXT:    smax v0.8b, v1.8b, v0.8b
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <8 x i8> @llvm.vector.partial.reduce.smax.v8i8.v8i8.nxv16i8(<8 x i8> %accumulator, <vscale x 16 x i8> %0)
  ret <8 x i8> %partial.reduce
}

define <8 x i8> @partial_reduce_smax_scalable_neutral_nxv8i8_v8i8(<8 x i8> %accumulator, <vscale x 8 x i16> %0) #0 {
; CHECK-LABEL: partial_reduce_smax_scalable_neutral_nxv8i8_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    sxtb z1.h, p0/m, z1.h
; CHECK-NEXT:    smaxqv v0.8h, p0, z1.h
; CHECK-NEXT:    xtn v0.8b, v0.8h
; CHECK-NEXT:    ret
entry:
  %leg = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %partial.reduce = call <8 x i8> @llvm.vector.partial.reduce.smax.v8i8.v8i8.nxv8i8(<8 x i8> splat (i8 -128), <vscale x 8 x i8> %leg)
  ret <8 x i8> %partial.reduce
}

define <8 x i8> @partial_reduce_smax_scalable_acc_nxv8i8_v8i8(<8 x i8> %accumulator, <vscale x 8 x i16> %0) #0 {
; CHECK-LABEL: partial_reduce_smax_scalable_acc_nxv8i8_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-NEXT:    sxtb z1.h, p0/m, z1.h
; CHECK-NEXT:    smaxqv v1.8h, p0, z1.h
; CHECK-NEXT:    smax v0.8h, v0.8h, v1.8h
; CHECK-NEXT:    xtn v0.8b, v0.8h
; CHECK-NEXT:    ret
entry:
  %leg = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %partial.reduce = call <8 x i8> @llvm.vector.partial.reduce.smax.v8i8.v8i8.nxv8i8(<8 x i8> %accumulator, <vscale x 8 x i8> %leg)
  ret <8 x i8> %partial.reduce
}

define <8 x i16> @partial_reduce_smax_scalable_zero_v8i16(<8 x i16> %accumulator, <vscale x 8 x i16> %0) #0 {
; CHECK-LABEL: partial_reduce_smax_scalable_zero_v8i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    smaxqv v0.8h, p0, z1.h
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <8 x i16> @llvm.vector.partial.reduce.smax.v8i16.v8i16.nxv8i16(<8 x i16> splat (i16 -32768), <vscale x 8 x i16> %0)
  ret <8 x i16> %partial.reduce
}

define <4 x i32> @partial_reduce_smax_scalable_zero_v4i32(<4 x i32> %accumulator, <vscale x 4 x i32> %0) #0 {
; CHECK-LABEL: partial_reduce_smax_scalable_zero_v4i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    smaxqv v0.4s, p0, z1.s
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <4 x i32> @llvm.vector.partial.reduce.smax.v4i32.v4i32.nxv4i32(<4 x i32> splat (i32 -2147483648), <vscale x 4 x i32> %0)
  ret <4 x i32> %partial.reduce
}

define <2 x i64> @partial_reduce_smax_scalable_zero_v2i64(<2 x i64> %accumulator, <vscale x 2 x i64> %0) #0 {
; CHECK-LABEL: partial_reduce_smax_scalable_zero_v2i64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    smaxqv v0.2d, p0, z1.d
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <2 x i64> @llvm.vector.partial.reduce.smax.v2i64.v2i64.nxv2i64(<2 x i64> splat (i64 -9223372036854775808), <vscale x 2 x i64> %0)
  ret <2 x i64> %partial.reduce
}

; The lowering is the same for umax/smin/umin, so just test them for one type.

define <16 x i8> @partial_reduce_umax_scalable_zero_v16i8(<16 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_umax_scalable_zero_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    umaxqv v0.16b, p0, z1.b
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <16 x i8> @llvm.vector.partial.reduce.umax.v16i8.v16i8.nxv16i8(<16 x i8> zeroinitializer, <vscale x 16 x i8> %0)
  ret <16 x i8> %partial.reduce
}

define <8 x i8> @partial_reduce_umax_scalable_neutral_nxv16i8_v8i8(<8 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_umax_scalable_neutral_nxv16i8_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    umaxqv v0.16b, p0, z1.b
; CHECK-NEXT:    mov d1, v0.d[1]
; CHECK-NEXT:    umax v0.8b, v0.8b, v1.8b
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <8 x i8> @llvm.vector.partial.reduce.umax.v8i8.v8i8.nxv16i8(<8 x i8> splat (i8 0), <vscale x 16 x i8> %0)
  ret <8 x i8> %partial.reduce
}

define <8 x i8> @partial_reduce_umax_scalable_neutral_nxv8i8_v8i8(<8 x i8> %accumulator, <vscale x 8 x i16> %0) #0 {
; CHECK-LABEL: partial_reduce_umax_scalable_neutral_nxv8i8_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    and z1.h, z1.h, #0xff
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    umaxqv v0.8h, p0, z1.h
; CHECK-NEXT:    xtn v0.8b, v0.8h
; CHECK-NEXT:    ret
entry:
  %leg = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %partial.reduce = call <8 x i8> @llvm.vector.partial.reduce.umax.v8i8.v8i8.nxv8i8(<8 x i8> splat (i8 0), <vscale x 8 x i8> %leg)
  ret <8 x i8> %partial.reduce
}

define <16 x i8> @partial_reduce_smin_scalable_zero_v16i8(<16 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_smin_scalable_zero_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    sminqv v0.16b, p0, z1.b
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <16 x i8> @llvm.vector.partial.reduce.smin.v16i8.v16i8.nxv16i8(<16 x i8> splat (i8 127), <vscale x 16 x i8> %0)
  ret <16 x i8> %partial.reduce
}

define <8 x i8> @partial_reduce_smin_scalable_neutral_nxv16i8_v8i8(<8 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_smin_scalable_neutral_nxv16i8_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    sminqv v0.16b, p0, z1.b
; CHECK-NEXT:    mov d1, v0.d[1]
; CHECK-NEXT:    smin v0.8b, v0.8b, v1.8b
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <8 x i8> @llvm.vector.partial.reduce.smin.v8i8.v8i8.nxv16i8(<8 x i8> splat (i8 127), <vscale x 16 x i8> %0)
  ret <8 x i8> %partial.reduce
}

define <8 x i8> @partial_reduce_smin_scalable_neutral_nxv8i8_v8i8(<8 x i8> %accumulator, <vscale x 8 x i16> %0) #0 {
; CHECK-LABEL: partial_reduce_smin_scalable_neutral_nxv8i8_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    sxtb z1.h, p0/m, z1.h
; CHECK-NEXT:    sminqv v0.8h, p0, z1.h
; CHECK-NEXT:    xtn v0.8b, v0.8h
; CHECK-NEXT:    ret
entry:
  %leg = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %partial.reduce = call <8 x i8> @llvm.vector.partial.reduce.smin.v8i8.v8i8.nxv8i8(<8 x i8> splat (i8 127), <vscale x 8 x i8> %leg)
  ret <8 x i8> %partial.reduce
}

define <16 x i8> @partial_reduce_umin_scalable_zero_v16i8(<16 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_umin_scalable_zero_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    uminqv v0.16b, p0, z1.b
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <16 x i8> @llvm.vector.partial.reduce.umin.v16i8.v16i8.nxv16i8(<16 x i8> splat (i8 -1), <vscale x 16 x i8> %0)
  ret <16 x i8> %partial.reduce
}

define <8 x i8> @partial_reduce_umin_scalable_neutral_nxv16i8_v8i8(<8 x i8> %accumulator, <vscale x 16 x i8> %0) #0 {
; CHECK-LABEL: partial_reduce_umin_scalable_neutral_nxv16i8_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    uminqv v0.16b, p0, z1.b
; CHECK-NEXT:    mov d1, v0.d[1]
; CHECK-NEXT:    umin v0.8b, v0.8b, v1.8b
; CHECK-NEXT:    ret
entry:
  %partial.reduce = call <8 x i8> @llvm.vector.partial.reduce.umin.v8i8.v8i8.nxv16i8(<8 x i8> splat (i8 -1), <vscale x 16 x i8> %0)
  ret <8 x i8> %partial.reduce
}

define <8 x i8> @partial_reduce_umin_scalable_neutral_nxv8i8_v8i8(<8 x i8> %accumulator, <vscale x 8 x i16> %0) #0 {
; CHECK-LABEL: partial_reduce_umin_scalable_neutral_nxv8i8_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    and z1.h, z1.h, #0xff
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    uminqv v0.8h, p0, z1.h
; CHECK-NEXT:    xtn v0.8b, v0.8h
; CHECK-NEXT:    ret
entry:
  %leg = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %partial.reduce = call <8 x i8> @llvm.vector.partial.reduce.umin.v8i8.v8i8.nxv8i8(<8 x i8> splat (i8 -1), <vscale x 8 x i8> %leg)
  ret <8 x i8> %partial.reduce
}
