; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -mattr=+sve2p2 -o - %s | FileCheck %s

; Test SVE2.2 instructions for segmented shuffles.



; rev: Should use the zeroing variant. 

define <vscale x 16 x i8> @rev_v16i8(<vscale x 16 x i8> %0, <vscale x 16 x i8> %1) {
; CHECK-LABEL: rev_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/z, z0.q
; CHECK-NEXT:    revb z0.d, p1/z, z0.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(
    <vscale x 16 x i8> %0, <vscale x 16 x i8> %1, <16 x i32> <i32 15, i32 14, i32 13, i32 12, i32 11, i32 10, i32 9, i32 8, i32 7, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 16 x i8> %res
}

define <vscale x 8 x i16> @rev_v8i16(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: rev_v8i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/z, z0.q
; CHECK-NEXT:    revh z0.d, p1/z, z0.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(
    <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, <8 x i32> <i32 7, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 8 x i16> %res
}

define <vscale x 8 x i16> @rev_v8i8(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: rev_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/z, z0.q
; CHECK-NEXT:    revh z0.d, p1/z, z0.d
; CHECK-NEXT:    and z0.h, z0.h, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %leg1 = trunc <vscale x 8 x i16> %1 to <vscale x 8 x i8>
  %res = call <vscale x 8 x i8> @llvm.vector.segmented.shuffle.nxv8i8.v8i32(
    <vscale x 8 x i8> %leg0, <vscale x 8 x i8> %leg1, <8 x i32> <i32 7, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>)
  %res.leg = zext <vscale x 8 x i8> %res to <vscale x 8 x i16>
  ret <vscale x 8 x i16> %res.leg
}

define <vscale x 8 x half> @rev_v8f16(<vscale x 8 x half> %0, <vscale x 8 x half> %1) {
; CHECK-LABEL: rev_v8f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/z, z0.q
; CHECK-NEXT:    revh z0.d, p1/z, z0.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x half> @llvm.vector.segmented.shuffle.nxv8f16.v8i32(
    <vscale x 8 x half> %0, <vscale x 8 x half> %1, <8 x i32> <i32 7, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 8 x half> %res
}

define <vscale x 8 x bfloat> @rev_v8bf16(<vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1) {
; CHECK-LABEL: rev_v8bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/z, z0.q
; CHECK-NEXT:    revh z0.d, p1/z, z0.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x bfloat> @llvm.vector.segmented.shuffle.nxv8bf16.v8i32(
    <vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1, <8 x i32> <i32 7, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 8 x bfloat> %res
}

define <vscale x 4 x i32> @rev_v4i32(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: rev_v4i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/z, z0.q
; CHECK-NEXT:    revw z0.d, p1/z, z0.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x i32> @llvm.vector.segmented.shuffle.nxv4i32.v4i32(
    <vscale x 4 x i32> %0, <vscale x 4 x i32> %1, <4 x i32> <i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 4 x i32> %res
}

define <vscale x 4 x i32> @rev_v4i16(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: rev_v4i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/z, z0.q
; CHECK-NEXT:    revw z0.d, p1/z, z0.d
; CHECK-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %res = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(
    <vscale x 4 x i16> %leg0, <vscale x 4 x i16> %leg1, <4 x i32> <i32 3, i32 2, i32 1, i32 0>)
  %res.leg = zext <vscale x 4 x i16> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x i32> @rev_v4i8(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: rev_v4i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/z, z0.q
; CHECK-NEXT:    revw z0.d, p1/z, z0.d
; CHECK-NEXT:    and z0.s, z0.s, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %res = call <vscale x 4 x i8> @llvm.vector.segmented.shuffle.nxv4i8.v4i32(
    <vscale x 4 x i8> %leg0, <vscale x 4 x i8> %leg1, <4 x i32> <i32 3, i32 2, i32 1, i32 0>)
  %res.leg = zext <vscale x 4 x i8> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x float> @rev_v4f32(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: rev_v4f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/z, z0.q
; CHECK-NEXT:    revw z0.d, p1/z, z0.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> %1, <4 x i32> <i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 4 x float> %res
}

define <vscale x 4 x half> @rev_v4f16(<vscale x 4 x half> %0, <vscale x 4 x half> %1) {
; CHECK-LABEL: rev_v4f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/z, z0.q
; CHECK-NEXT:    revw z0.d, p1/z, z0.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x half> @llvm.vector.segmented.shuffle.nxv4f16.v4i32(
    <vscale x 4 x half> %0, <vscale x 4 x half> %1, <4 x i32> <i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 4 x half> %res
}

define <vscale x 2 x i64> @rev_v2i64(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1) {
; CHECK-LABEL: rev_v2i64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    revd z0.q, p0/z, z0.q
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x i64> @llvm.vector.segmented.shuffle.nxv2i64.v2i32(
    <vscale x 2 x i64> %0, <vscale x 2 x i64> %1, <2 x i32> <i32 1, i32 0>)
  ret <vscale x 2 x i64> %res
}

define <vscale x 2 x i64> @rev_v2i32(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1) {
; CHECK-LABEL: rev_v2i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    revd z0.q, p0/z, z0.q
; CHECK-NEXT:    and z0.d, z0.d, #0xffffffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 2 x i64> %0 to <vscale x 2 x i32>
  %leg1 = trunc <vscale x 2 x i64> %0 to <vscale x 2 x i32>
  %res = call <vscale x 2 x i32> @llvm.vector.segmented.shuffle.nxv2i32.v2i32(
    <vscale x 2 x i32> %leg0, <vscale x 2 x i32> %leg1, <2 x i32> <i32 1, i32 0>)
  %res.leg = zext <vscale x 2 x i32> %res to <vscale x 2 x i64>
  ret <vscale x 2 x i64> %res.leg
}

define <vscale x 2 x double> @rev_v2f64(<vscale x 2 x double> %0, <vscale x 2 x double> %1) {
; CHECK-LABEL: rev_v2f64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    revd z0.q, p0/z, z0.q
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x double> @llvm.vector.segmented.shuffle.nxv2f64.v2i32(
    <vscale x 2 x double> %0, <vscale x 2 x double> %1, <2 x i32> <i32 1, i32 0>)
  ret <vscale x 2 x double> %res
}

define <vscale x 2 x float> @rev_v2f32(<vscale x 2 x float> %0, <vscale x 2 x float> %1) {
; CHECK-LABEL: rev_v2f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    revd z0.q, p0/z, z0.q
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x float> @llvm.vector.segmented.shuffle.nxv2f32.v2i32(
    <vscale x 2 x float> %0, <vscale x 2 x float> %1, <2 x i32> <i32 1, i32 0>)
  ret <vscale x 2 x float> %res
}
