; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve2p2 < %s | FileCheck %s

;
; FRINT32X
;

define <vscale x 4 x float> @frint32x_m_s(<vscale x 4 x float> %a, <vscale x 4 x i1> %pg, <vscale x 4 x float> %b) {
; CHECK-LABEL: frint32x_m_s:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint32x z0.s, p0/m, z1.s
; CHECK-NEXT:    ret
  %out = call <vscale x 4 x float> @llvm.aarch64.sve.frint32x.nxv4f32(<vscale x 4 x float> %a,
                                                                    <vscale x 4 x i1> %pg,
                                                                    <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %out
}

define <vscale x 2 x double> @frint32x_m_d(<vscale x 2 x double> %a, <vscale x 2 x i1> %pg, <vscale x 2 x double> %b) {
; CHECK-LABEL: frint32x_m_d:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint32x z0.d, p0/m, z1.d
; CHECK-NEXT:    ret
  %out = call <vscale x 2 x double> @llvm.aarch64.sve.frint32x.nxv2f64(<vscale x 2 x double> %a,
                                                                     <vscale x 2 x i1> %pg,
                                                                     <vscale x 2 x double> %b)
  ret <vscale x 2 x double> %out
}

define <vscale x 4 x float> @frint32x_x_s(<vscale x 4 x i1> %pg, <vscale x 4 x float> %b) {
; CHECK-LABEL: frint32x_x_s:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint32x z0.s, p0/z, z0.s
; CHECK-NEXT:    ret
  %out = call <vscale x 4 x float> @llvm.aarch64.sve.frint32x.nxv4f32(<vscale x 4 x float> poison,
                                                                    <vscale x 4 x i1> %pg,
                                                                    <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %out
}

define <vscale x 2 x double> @frint32x_x_d(<vscale x 2 x i1> %pg, <vscale x 2 x double> %b) {
; CHECK-LABEL: frint32x_x_d:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint32x z0.d, p0/z, z0.d
; CHECK-NEXT:    ret
  %out = call <vscale x 2 x double> @llvm.aarch64.sve.frint32x.nxv2f64(<vscale x 2 x double> poison,
                                                                     <vscale x 2 x i1> %pg,
                                                                     <vscale x 2 x double> %b)
  ret <vscale x 2 x double> %out
}

define <vscale x 4 x float> @frint32x_z_s(<vscale x 4 x float> %a, <vscale x 4 x i1> %pg, <vscale x 4 x float> %b) {
; CHECK-LABEL: frint32x_z_s:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint32x z0.s, p0/z, z1.s
; CHECK-NEXT:    ret
  %out = call <vscale x 4 x float> @llvm.aarch64.sve.frint32x.nxv4f32(<vscale x 4 x float> zeroinitializer,
                                                                    <vscale x 4 x i1> %pg,
                                                                    <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %out
}

define <vscale x 2 x double> @frint32x_z_d(<vscale x 2 x double> %a, <vscale x 2 x i1> %pg, <vscale x 2 x double> %b) {
; CHECK-LABEL: frint32x_z_d:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint32x z0.d, p0/z, z1.d
; CHECK-NEXT:    ret
  %out = call <vscale x 2 x double> @llvm.aarch64.sve.frint32x.nxv2f64(<vscale x 2 x double> zeroinitializer,
                                                                     <vscale x 2 x i1> %pg,
                                                                     <vscale x 2 x double> %b)
  ret <vscale x 2 x double> %out
}

;
; FRINT32Z
;

define <vscale x 4 x float> @frint32z_m_s(<vscale x 4 x float> %a, <vscale x 4 x i1> %pg, <vscale x 4 x float> %b) {
; CHECK-LABEL: frint32z_m_s:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint32z z0.s, p0/m, z1.s
; CHECK-NEXT:    ret
  %out = call <vscale x 4 x float> @llvm.aarch64.sve.frint32z.nxv4f32(<vscale x 4 x float> %a,
                                                                    <vscale x 4 x i1> %pg,
                                                                    <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %out
}

define <vscale x 2 x double> @frint32z_m_d(<vscale x 2 x double> %a, <vscale x 2 x i1> %pg, <vscale x 2 x double> %b) {
; CHECK-LABEL: frint32z_m_d:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint32z z0.d, p0/m, z1.d
; CHECK-NEXT:    ret
  %out = call <vscale x 2 x double> @llvm.aarch64.sve.frint32z.nxv2f64(<vscale x 2 x double> %a,
                                                                     <vscale x 2 x i1> %pg,
                                                                     <vscale x 2 x double> %b)
  ret <vscale x 2 x double> %out
}

define <vscale x 4 x float> @frint32z_x_s(<vscale x 4 x i1> %pg, <vscale x 4 x float> %b) {
; CHECK-LABEL: frint32z_x_s:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint32z z0.s, p0/z, z0.s
; CHECK-NEXT:    ret
  %out = call <vscale x 4 x float> @llvm.aarch64.sve.frint32z.nxv4f32(<vscale x 4 x float> poison,
                                                                    <vscale x 4 x i1> %pg,
                                                                    <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %out
}

define <vscale x 2 x double> @frint32z_x_d(<vscale x 2 x i1> %pg, <vscale x 2 x double> %b) {
; CHECK-LABEL: frint32z_x_d:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint32z z0.d, p0/z, z0.d
; CHECK-NEXT:    ret
  %out = call <vscale x 2 x double> @llvm.aarch64.sve.frint32z.nxv2f64(<vscale x 2 x double> poison,
                                                                     <vscale x 2 x i1> %pg,
                                                                     <vscale x 2 x double> %b)
  ret <vscale x 2 x double> %out
}

define <vscale x 4 x float> @frint32z_z_s(<vscale x 4 x float> %a, <vscale x 4 x i1> %pg, <vscale x 4 x float> %b) {
; CHECK-LABEL: frint32z_z_s:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint32z z0.s, p0/z, z1.s
; CHECK-NEXT:    ret
  %out = call <vscale x 4 x float> @llvm.aarch64.sve.frint32z.nxv4f32(<vscale x 4 x float> zeroinitializer,
                                                                    <vscale x 4 x i1> %pg,
                                                                    <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %out
}

define <vscale x 2 x double> @frint32z_z_d(<vscale x 2 x double> %a, <vscale x 2 x i1> %pg, <vscale x 2 x double> %b) {
; CHECK-LABEL: frint32z_z_d:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint32z z0.d, p0/z, z1.d
; CHECK-NEXT:    ret
  %out = call <vscale x 2 x double> @llvm.aarch64.sve.frint32z.nxv2f64(<vscale x 2 x double> zeroinitializer,
                                                                     <vscale x 2 x i1> %pg,
                                                                     <vscale x 2 x double> %b)
  ret <vscale x 2 x double> %out
}

;
; FRINT64X
;

define <vscale x 4 x float> @frint64x_m_s(<vscale x 4 x float> %a, <vscale x 4 x i1> %pg, <vscale x 4 x float> %b) {
; CHECK-LABEL: frint64x_m_s:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint64x z0.s, p0/m, z1.s
; CHECK-NEXT:    ret
  %out = call <vscale x 4 x float> @llvm.aarch64.sve.frint64x.nxv4f32(<vscale x 4 x float> %a,
                                                                      <vscale x 4 x i1> %pg,
							              <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %out
}

define <vscale x 2 x double> @frint64x_m_d(<vscale x 2 x double> %a, <vscale x 2 x i1> %pg, <vscale x 2 x double> %b) {
; CHECK-LABEL: frint64x_m_d:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint64x z0.d, p0/m, z1.d
; CHECK-NEXT:    ret
  %out = call <vscale x 2 x double> @llvm.aarch64.sve.frint64x.nxv2f64(<vscale x 2 x double> %a,
                                                                     <vscale x 2 x i1> %pg,
                                                                     <vscale x 2 x double> %b)
  ret <vscale x 2 x double> %out
}

define <vscale x 4 x float> @frint64x_x_s(<vscale x 4 x i1> %pg, <vscale x 4 x float> %b) {
; CHECK-LABEL: frint64x_x_s:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint64x z0.s, p0/z, z0.s
; CHECK-NEXT:    ret
  %out = call <vscale x 4 x float> @llvm.aarch64.sve.frint64x.nxv4f32(<vscale x 4 x float> poison,
                                                                    <vscale x 4 x i1> %pg,
                                                                    <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %out
}

define <vscale x 2 x double> @frint64x_x_d(<vscale x 2 x i1> %pg, <vscale x 2 x double> %b) {
; CHECK-LABEL: frint64x_x_d:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint64x z0.d, p0/z, z0.d
; CHECK-NEXT:    ret
  %out = call <vscale x 2 x double> @llvm.aarch64.sve.frint64x.nxv2f64(<vscale x 2 x double> poison,
                                                                     <vscale x 2 x i1> %pg,
                                                                     <vscale x 2 x double> %b)
  ret <vscale x 2 x double> %out
}

define <vscale x 4 x float> @frint64x_z_s(<vscale x 4 x float> %a, <vscale x 4 x i1> %pg, <vscale x 4 x float> %b) {
; CHECK-LABEL: frint64x_z_s:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint64x z0.s, p0/z, z1.s
; CHECK-NEXT:    ret
  %out = call <vscale x 4 x float> @llvm.aarch64.sve.frint64x.nxv4f32(<vscale x 4 x float> zeroinitializer,
                                                                    <vscale x 4 x i1> %pg,
                                                                    <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %out
}

define <vscale x 2 x double> @frint64x_z_d(<vscale x 2 x double> %a, <vscale x 2 x i1> %pg, <vscale x 2 x double> %b) {
; CHECK-LABEL: frint64x_z_d:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint64x z0.d, p0/z, z1.d
; CHECK-NEXT:    ret
  %out = call <vscale x 2 x double> @llvm.aarch64.sve.frint64x.nxv2f64(<vscale x 2 x double> zeroinitializer,
                                                                     <vscale x 2 x i1> %pg,
                                                                     <vscale x 2 x double> %b)
  ret <vscale x 2 x double> %out
}

;
; FRINT64Z
;

define <vscale x 4 x float> @frint64z_m_s(<vscale x 4 x float> %a, <vscale x 4 x i1> %pg, <vscale x 4 x float> %b) {
; CHECK-LABEL: frint64z_m_s:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint64z z0.s, p0/m, z1.s
; CHECK-NEXT:    ret
  %out = call <vscale x 4 x float> @llvm.aarch64.sve.frint64z.nxv4f32(<vscale x 4 x float> %a,
                                                                    <vscale x 4 x i1> %pg,
                                                                    <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %out
}

define <vscale x 2 x double> @frint64z_m_d(<vscale x 2 x double> %a, <vscale x 2 x i1> %pg, <vscale x 2 x double> %b) {
; CHECK-LABEL: frint64z_m_d:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint64z z0.d, p0/m, z1.d
; CHECK-NEXT:    ret
  %out = call <vscale x 2 x double> @llvm.aarch64.sve.frint64z.nxv2f64(<vscale x 2 x double> %a,
                                                                     <vscale x 2 x i1> %pg,
                                                                     <vscale x 2 x double> %b)
  ret <vscale x 2 x double> %out
}

define <vscale x 4 x float> @frint64z_x_s(<vscale x 4 x i1> %pg, <vscale x 4 x float> %b) {
; CHECK-LABEL: frint64z_x_s:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint64z z0.s, p0/z, z0.s
; CHECK-NEXT:    ret
  %out = call <vscale x 4 x float> @llvm.aarch64.sve.frint64z.nxv4f32(<vscale x 4 x float> poison,
                                                                    <vscale x 4 x i1> %pg,
                                                                    <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %out
}

define <vscale x 2 x double> @frint64z_x_d(<vscale x 2 x i1> %pg, <vscale x 2 x double> %b) {
; CHECK-LABEL: frint64z_x_d:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint64z z0.d, p0/z, z0.d
; CHECK-NEXT:    ret
  %out = call <vscale x 2 x double> @llvm.aarch64.sve.frint64z.nxv2f64(<vscale x 2 x double> poison,
                                                                     <vscale x 2 x i1> %pg,
                                                                     <vscale x 2 x double> %b)
  ret <vscale x 2 x double> %out
}

define <vscale x 4 x float> @frint64z_z_s(<vscale x 4 x float> %a, <vscale x 4 x i1> %pg, <vscale x 4 x float> %b) {
; CHECK-LABEL: frint64z_z_s:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint64z z0.s, p0/z, z1.s
; CHECK-NEXT:    ret
  %out = call <vscale x 4 x float> @llvm.aarch64.sve.frint64z.nxv4f32(<vscale x 4 x float> zeroinitializer,
                                                                    <vscale x 4 x i1> %pg,
                                                                    <vscale x 4 x float> %b)
  ret <vscale x 4 x float> %out
}

define <vscale x 2 x double> @frint64z_z_d(<vscale x 2 x double> %a, <vscale x 2 x i1> %pg, <vscale x 2 x double> %b) {
; CHECK-LABEL: frint64z_z_d:
; CHECK:       // %bb.0:
; CHECK-NEXT:    frint64z z0.d, p0/z, z1.d
; CHECK-NEXT:    ret
  %out = call <vscale x 2 x double> @llvm.aarch64.sve.frint64z.nxv2f64(<vscale x 2 x double> zeroinitializer,
                                                                     <vscale x 2 x i1> %pg,
                                                                     <vscale x 2 x double> %b)
  ret <vscale x 2 x double> %out
}

