; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve2p1,+bf16 < %s | FileCheck %s

;
; ST1Q: vector base +  unscaled offset
;   e.g. st1q { z0.q }, p0, [z1.d, x0]
;

define void @sst1_scatter_u64base_offset_i8(<vscale x 16 x i8> %data, <vscale x 1 x i1> %pg, <vscale x 2 x i64> %b, i64 %offset) {
; CHECK-LABEL: sst1_scatter_u64base_offset_i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    st1q { z0.q }, p0, [z1.d, x0]
; CHECK-NEXT:    ret
  call void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv16i8.nxv2i64(<vscale x 16 x i8> %data,
                                                           <vscale x 1 x i1> %pg,
                                                           <vscale x 2 x i64> %b,
                                                           i64 %offset)
  ret void
}

define void @sst1_scatter_u64base_offset_i16(<vscale x 8 x i16> %data, <vscale x 1 x i1> %pg, <vscale x 2 x i64> %b, i64 %offset) {
; CHECK-LABEL: sst1_scatter_u64base_offset_i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    st1q { z0.q }, p0, [z1.d, x0]
; CHECK-NEXT:    ret
  call void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv8i16.nxv2i64(<vscale x 8 x i16> %data,
                                                           <vscale x 1 x i1> %pg,
                                                           <vscale x 2 x i64> %b,
                                                           i64 %offset)
  ret void
}

define void @sst1_scatter_u64base_offset_i32(<vscale x 4 x i32> %data, <vscale x 1 x i1> %pg, <vscale x 2 x i64> %b, i64 %offset) {
; CHECK-LABEL: sst1_scatter_u64base_offset_i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    st1q { z0.q }, p0, [z1.d, x0]
; CHECK-NEXT:    ret
  call void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv4i32.nxv2i64(<vscale x 4 x i32> %data,
                                                           <vscale x 1 x i1> %pg,
                                                           <vscale x 2 x i64> %b,
                                                           i64 %offset)
  ret void
}

define void @sst1_scatter_u64base_offset_i64(<vscale x 2 x i64> %data, <vscale x 1 x i1> %pg, <vscale x 2 x i64> %b, i64 %offset) {
; CHECK-LABEL: sst1_scatter_u64base_offset_i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    st1q { z0.q }, p0, [z1.d, x0]
; CHECK-NEXT:    ret
  call void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv2i64.nxv2i64(<vscale x 2 x i64> %data,
                                                           <vscale x 1 x i1> %pg,
                                                           <vscale x 2 x i64> %b,
                                                           i64 %offset)
  ret void
}

define void @sst1_scatter_u64base_offset_f16(<vscale x 8 x half> %data, <vscale x 1 x i1> %pg, <vscale x 2 x i64> %base, i64 %offset) {
; CHECK-LABEL: sst1_scatter_u64base_offset_f16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    st1q { z0.q }, p0, [z1.d, x0]
; CHECK-NEXT:    ret
   call void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv8f16.nxv2i64(<vscale x 8 x half> %data,
                                                            <vscale x 1 x i1> %pg,
                                                            <vscale x 2 x i64> %base,
                                                            i64 %offset)
  ret void
}

define void @sst1_scatter_u64base_offset_f32(<vscale x 4 x float> %data, <vscale x 1 x i1> %pg, <vscale x 2 x i64> %b, i64 %offset) {
; CHECK-LABEL: sst1_scatter_u64base_offset_f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    st1q { z0.q }, p0, [z1.d, x0]
; CHECK-NEXT:    ret
  call void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv4f32.nxv2i64(<vscale x 4 x float> %data,
                                                           <vscale x 1 x i1> %pg,
                                                           <vscale x 2 x i64> %b,
                                                           i64 %offset)
  ret void
}

define void @sst1_scatter_u64base_offset_f64(<vscale x 2 x double> %data, <vscale x 1 x i1> %pg, <vscale x 2 x i64> %b, i64 %offset) {
; CHECK-LABEL: sst1_scatter_u64base_offset_f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    st1q { z0.q }, p0, [z1.d, x0]
; CHECK-NEXT:    ret
  call void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv2f64.nxv2i64(<vscale x 2 x double> %data,
                                                           <vscale x 1 x i1> %pg,
                                                           <vscale x 2 x i64> %b,
                                                           i64 %offset)
  ret void
}

define void @sst1_scatter_u64base_offset_bf16(<vscale x 8 x bfloat> %data, <vscale x 1 x i1> %pg, <vscale x 2 x i64> %b, i64 %offset) {
; CHECK-LABEL: sst1_scatter_u64base_offset_bf16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    st1q { z0.q }, p0, [z1.d, x0]
; CHECK-NEXT:    ret
  call void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv8bf16.nxv2i64(<vscale x 8 x bfloat> %data,
                                                            <vscale x 1 x i1> %pg,
                                                            <vscale x 2 x i64> %b,
                                                             i64 %offset)
  ret void
}

declare void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv16i8.nxv2i64(<vscale x 16 x i8>, <vscale x 1 x i1>, <vscale x 2 x i64>, i64)
declare void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv8i16.nxv2i64(<vscale x 8 x i16>, <vscale x 1 x i1>, <vscale x 2 x i64>, i64)
declare void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv4i32.nxv2i64(<vscale x 4 x i32>, <vscale x 1 x i1>, <vscale x 2 x i64>, i64)
declare void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv2i64.nxv2i64(<vscale x 2 x i64>, <vscale x 1 x i1>, <vscale x 2 x i64>, i64)

declare void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv8f16.nxv2i64(<vscale x 8 x half>, <vscale x 1 x i1>, <vscale x 2 x i64>, i64)
declare void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv4f32.nxv2i64(<vscale x 4 x float>, <vscale x 1 x i1>, <vscale x 2 x i64>, i64)
declare void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv2f64.nxv2i64(<vscale x 2 x double>, <vscale x 1 x i1>, <vscale x 2 x i64>, i64)
declare void @llvm.aarch64.sve.st1q.scatter.scalar.offset.nxv8bf16.nxv2i64(<vscale x 8 x bfloat>, <vscale x 1 x i1>, <vscale x 2 x i64>, i64)
