; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -mattr=+sve2p1 -o - %s | FileCheck %s

; trn1

define <vscale x 16 x i8> @trn1_v16i8(<vscale x 16 x i8> %0, <vscale x 16 x i8> %1) {
; CHECK-LABEL: trn1_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn1 z0.b, z0.b, z1.b
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(
    <vscale x 16 x i8> %0, <vscale x 16 x i8> %1, <16 x i32> <i32 0, i32 16, i32 2, i32 18, i32 4, i32 20, i32 6, i32 22, i32 8, i32 24, i32 10, i32 26, i32 12, i32 28, i32 14, i32 30>)
  ret <vscale x 16 x i8> %res
}

define <vscale x 8 x i16> @trn1_v8i16(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: trn1_v8i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn1 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(
    <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, <8 x i32> <i32 0, i32 8, i32 2, i32 10, i32 4, i32 12, i32 6, i32 14>)
  ret <vscale x 8 x i16> %res
}

define <vscale x 8 x i16> @trn1_v8i8(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: trn1_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn1 z0.h, z0.h, z1.h
; CHECK-NEXT:    and z0.h, z0.h, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %leg1 = trunc <vscale x 8 x i16> %1 to <vscale x 8 x i8>
  %res = call <vscale x 8 x i8> @llvm.vector.segmented.shuffle.nxv8i8.v8i32(
    <vscale x 8 x i8> %leg0, <vscale x 8 x i8> %leg1, <8 x i32> <i32 0, i32 8, i32 2, i32 10, i32 4, i32 12, i32 6, i32 14>)
  %res.leg = zext <vscale x 8 x i8> %res to <vscale x 8 x i16>
  ret <vscale x 8 x i16> %res.leg
}

define <vscale x 8 x half> @trn1_v8f16(<vscale x 8 x half> %0, <vscale x 8 x half> %1) {
; CHECK-LABEL: trn1_v8f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn1 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x half> @llvm.vector.segmented.shuffle.nxv8f16.v8i32(
    <vscale x 8 x half> %0, <vscale x 8 x half> %1, <8 x i32> <i32 0, i32 8, i32 2, i32 10, i32 4, i32 12, i32 6, i32 14>)
  ret <vscale x 8 x half> %res
}

define <vscale x 8 x bfloat> @trn1_v8bf16(<vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1) {
; CHECK-LABEL: trn1_v8bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn1 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x bfloat> @llvm.vector.segmented.shuffle.nxv8bf16.v8i32(
    <vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1, <8 x i32> <i32 0, i32 8, i32 2, i32 10, i32 4, i32 12, i32 6, i32 14>)
  ret <vscale x 8 x bfloat> %res
}

define <vscale x 4 x i32> @trn1_v4i32(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: trn1_v4i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn1 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x i32> @llvm.vector.segmented.shuffle.nxv4i32.v4i32(
    <vscale x 4 x i32> %0, <vscale x 4 x i32> %1, <4 x i32> <i32 0, i32 4, i32 2, i32 6>)
  ret <vscale x 4 x i32> %res
}

define <vscale x 4 x i32> @trn1_v4i16(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: trn1_v4i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn1 z0.s, z0.s, z0.s
; CHECK-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %res = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(
    <vscale x 4 x i16> %leg0, <vscale x 4 x i16> %leg1, <4 x i32> <i32 0, i32 4, i32 2, i32 6>)
  %res.leg = zext <vscale x 4 x i16> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x i32> @trn1_v4i8(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: trn1_v4i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn1 z0.s, z0.s, z0.s
; CHECK-NEXT:    and z0.s, z0.s, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %res = call <vscale x 4 x i8> @llvm.vector.segmented.shuffle.nxv4i8.v4i32(
    <vscale x 4 x i8> %leg0, <vscale x 4 x i8> %leg1, <4 x i32> <i32 0, i32 4, i32 2, i32 6>)
  %res.leg = zext <vscale x 4 x i8> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x float> @trn1_v4f32(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: trn1_v4f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn1 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> %1, <4 x i32> <i32 0, i32 4, i32 2, i32 6>)
  ret <vscale x 4 x float> %res
}

define <vscale x 4 x half> @trn1_v4f16(<vscale x 4 x half> %0, <vscale x 4 x half> %1) {
; CHECK-LABEL: trn1_v4f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn1 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x half> @llvm.vector.segmented.shuffle.nxv4f16.v4i32(
    <vscale x 4 x half> %0, <vscale x 4 x half> %1, <4 x i32> <i32 0, i32 4, i32 2, i32 6>)
  ret <vscale x 4 x half> %res
}

define <vscale x 2 x i64> @trn1_uzp1_zip1_v2i64(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1) {
; CHECK-LABEL: trn1_uzp1_zip1_v2i64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq1 z0.d, z0.d, z1.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x i64> @llvm.vector.segmented.shuffle.nxv2i64.v2i32(
    <vscale x 2 x i64> %0, <vscale x 2 x i64> %1, <2 x i32> <i32 0, i32 2>)
  ret <vscale x 2 x i64> %res
}

define <vscale x 2 x i64> @trn1_uzp1_zip1_v2i32(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1) {
; CHECK-LABEL: trn1_uzp1_zip1_v2i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq1 z0.d, z0.d, z0.d
; CHECK-NEXT:    and z0.d, z0.d, #0xffffffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 2 x i64> %0 to <vscale x 2 x i32>
  %leg1 = trunc <vscale x 2 x i64> %0 to <vscale x 2 x i32>
  %res = call <vscale x 2 x i32> @llvm.vector.segmented.shuffle.nxv2i32.v2i32(
    <vscale x 2 x i32> %leg0, <vscale x 2 x i32> %leg1, <2 x i32> <i32 0, i32 2>)
  %res.leg = zext <vscale x 2 x i32> %res to <vscale x 2 x i64>
  ret <vscale x 2 x i64> %res.leg
}

define <vscale x 2 x double> @trn1_uzp1_zip1_v2f64(<vscale x 2 x double> %0, <vscale x 2 x double> %1) {
; CHECK-LABEL: trn1_uzp1_zip1_v2f64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq1 z0.d, z0.d, z1.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x double> @llvm.vector.segmented.shuffle.nxv2f64.v2i32(
    <vscale x 2 x double> %0, <vscale x 2 x double> %1, <2 x i32> <i32 0, i32 2>)
  ret <vscale x 2 x double> %res
}

define <vscale x 2 x float> @trn1_uzp1_zip1_v2f32(<vscale x 2 x float> %0, <vscale x 2 x float> %1) {
; CHECK-LABEL: trn1_uzp1_zip1_v2f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq1 z0.d, z0.d, z1.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x float> @llvm.vector.segmented.shuffle.nxv2f32.v2i32(
    <vscale x 2 x float> %0, <vscale x 2 x float> %1, <2 x i32> <i32 0, i32 2>)
  ret <vscale x 2 x float> %res
}

define <vscale x 4 x float> @trn1_v_undef(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: trn1_v_undef:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn1 z0.s, z0.s, z0.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>)
  ret <vscale x 4 x float> %res
}


; trn2

define <vscale x 16 x i8> @trn2_v16i8(<vscale x 16 x i8> %0, <vscale x 16 x i8> %1) {
; CHECK-LABEL: trn2_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn2 z0.b, z0.b, z1.b
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(
    <vscale x 16 x i8> %0, <vscale x 16 x i8> %1, <16 x i32> <i32 1, i32 17, i32 3, i32 19, i32 5, i32 21, i32 7, i32 23, i32 9, i32 25, i32 11, i32 27, i32 13, i32 29, i32 15, i32 31>)
  ret <vscale x 16 x i8> %res
}

define <vscale x 8 x i16> @trn2_v8i16(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: trn2_v8i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn2 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(
    <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, <8 x i32> <i32 1, i32 9, i32 3, i32 11, i32 5, i32 13, i32 7, i32 15>)
  ret <vscale x 8 x i16> %res
}

define <vscale x 8 x i16> @trn2_v8i8(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: trn2_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn2 z0.h, z0.h, z1.h
; CHECK-NEXT:    and z0.h, z0.h, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %leg1 = trunc <vscale x 8 x i16> %1 to <vscale x 8 x i8>
  %res = call <vscale x 8 x i8> @llvm.vector.segmented.shuffle.nxv8i8.v8i32(
    <vscale x 8 x i8> %leg0, <vscale x 8 x i8> %leg1, <8 x i32> <i32 1, i32 9, i32 3, i32 11, i32 5, i32 13, i32 7, i32 15>)
  %res.leg = zext <vscale x 8 x i8> %res to <vscale x 8 x i16>
  ret <vscale x 8 x i16> %res.leg
}

define <vscale x 8 x half> @trn2_v8f16(<vscale x 8 x half> %0, <vscale x 8 x half> %1) {
; CHECK-LABEL: trn2_v8f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn2 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x half> @llvm.vector.segmented.shuffle.nxv8f16.v8i32(
    <vscale x 8 x half> %0, <vscale x 8 x half> %1, <8 x i32> <i32 1, i32 9, i32 3, i32 11, i32 5, i32 13, i32 7, i32 15>)
  ret <vscale x 8 x half> %res
}

define <vscale x 8 x bfloat> @trn2_v8bf16(<vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1) {
; CHECK-LABEL: trn2_v8bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn2 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x bfloat> @llvm.vector.segmented.shuffle.nxv8bf16.v8i32(
    <vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1, <8 x i32> <i32 1, i32 9, i32 3, i32 11, i32 5, i32 13, i32 7, i32 15>)
  ret <vscale x 8 x bfloat> %res
}

define <vscale x 4 x i32> @trn2_v4i32(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: trn2_v4i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn2 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x i32> @llvm.vector.segmented.shuffle.nxv4i32.v4i32(
    <vscale x 4 x i32> %0, <vscale x 4 x i32> %1, <4 x i32> <i32 1, i32 5, i32 3, i32 7>)
  ret <vscale x 4 x i32> %res
}

define <vscale x 4 x i32> @trn2_v4i16(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: trn2_v4i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn2 z0.s, z0.s, z0.s
; CHECK-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %res = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(
    <vscale x 4 x i16> %leg0, <vscale x 4 x i16> %leg1, <4 x i32> <i32 1, i32 5, i32 3, i32 7>)
  %res.leg = zext <vscale x 4 x i16> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x i32> @trn2_v4i8(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: trn2_v4i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn2 z0.s, z0.s, z0.s
; CHECK-NEXT:    and z0.s, z0.s, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %res = call <vscale x 4 x i8> @llvm.vector.segmented.shuffle.nxv4i8.v4i32(
    <vscale x 4 x i8> %leg0, <vscale x 4 x i8> %leg1, <4 x i32> <i32 1, i32 5, i32 3, i32 7>)
  %res.leg = zext <vscale x 4 x i8> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x float> @trn2_v4f32(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: trn2_v4f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn2 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> %1, <4 x i32> <i32 1, i32 5, i32 3, i32 7>)
  ret <vscale x 4 x float> %res
}

define <vscale x 4 x half> @trn2_v4f16(<vscale x 4 x half> %0, <vscale x 4 x half> %1) {
; CHECK-LABEL: trn2_v4f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn2 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x half> @llvm.vector.segmented.shuffle.nxv4f16.v4i32(
    <vscale x 4 x half> %0, <vscale x 4 x half> %1, <4 x i32> <i32 1, i32 5, i32 3, i32 7>)
  ret <vscale x 4 x half> %res
}

define <vscale x 2 x i64> @trn2_uzp2_zip2_v2i64(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1) {
; CHECK-LABEL: trn2_uzp2_zip2_v2i64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq2 z0.d, z0.d, z1.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x i64> @llvm.vector.segmented.shuffle.nxv2i64.v2i32(
    <vscale x 2 x i64> %0, <vscale x 2 x i64> %1, <2 x i32> <i32 1, i32 3>)
  ret <vscale x 2 x i64> %res
}

define <vscale x 2 x i64> @trn2_uzp2_zip2_v2i32(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1) {
; CHECK-LABEL: trn2_uzp2_zip2_v2i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq2 z0.d, z0.d, z0.d
; CHECK-NEXT:    and z0.d, z0.d, #0xffffffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 2 x i64> %0 to <vscale x 2 x i32>
  %leg1 = trunc <vscale x 2 x i64> %0 to <vscale x 2 x i32>
  %res = call <vscale x 2 x i32> @llvm.vector.segmented.shuffle.nxv2i32.v2i32(
    <vscale x 2 x i32> %leg0, <vscale x 2 x i32> %leg1, <2 x i32> <i32 1, i32 3>)
  %res.leg = zext <vscale x 2 x i32> %res to <vscale x 2 x i64>
  ret <vscale x 2 x i64> %res.leg
}

define <vscale x 2 x double> @trn2_uzp2_zip2_v2f64(<vscale x 2 x double> %0, <vscale x 2 x double> %1) {
; CHECK-LABEL: trn2_uzp2_zip2_v2f64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq2 z0.d, z0.d, z1.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x double> @llvm.vector.segmented.shuffle.nxv2f64.v2i32(
    <vscale x 2 x double> %0, <vscale x 2 x double> %1, <2 x i32> <i32 1, i32 3>)
  ret <vscale x 2 x double> %res
}

define <vscale x 2 x float> @trn2_uzp2_zip2_v2f32(<vscale x 2 x float> %0, <vscale x 2 x float> %1) {
; CHECK-LABEL: trn2_uzp2_zip2_v2f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq2 z0.d, z0.d, z1.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x float> @llvm.vector.segmented.shuffle.nxv2f32.v2i32(
    <vscale x 2 x float> %0, <vscale x 2 x float> %1, <2 x i32> <i32 1, i32 3>)
  ret <vscale x 2 x float> %res
}

define <vscale x 4 x float> @trn2_v_undef(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: trn2_v_undef:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    trn2 z0.s, z0.s, z0.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>)
  ret <vscale x 4 x float> %res
}



; uzp1

define <vscale x 16 x i8> @uzp1_v16i8(<vscale x 16 x i8> %0, <vscale x 16 x i8> %1) {
; CHECK-LABEL: uzp1_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq1 z0.b, z0.b, z1.b
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(
    <vscale x 16 x i8> %0, <vscale x 16 x i8> %1, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>)
  ret <vscale x 16 x i8> %res
}

define <vscale x 8 x i16> @uzp1_v8i16(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: uzp1_v8i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq1 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(
    <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>)
  ret <vscale x 8 x i16> %res
}

define <vscale x 8 x i16> @uzp1_v8i8(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: uzp1_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq1 z0.h, z0.h, z1.h
; CHECK-NEXT:    and z0.h, z0.h, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %leg1 = trunc <vscale x 8 x i16> %1 to <vscale x 8 x i8>
  %res = call <vscale x 8 x i8> @llvm.vector.segmented.shuffle.nxv8i8.v8i32(
    <vscale x 8 x i8> %leg0, <vscale x 8 x i8> %leg1, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>)
  %res.leg = zext <vscale x 8 x i8> %res to <vscale x 8 x i16>
  ret <vscale x 8 x i16> %res.leg
}

define <vscale x 8 x half> @uzp1_v8f16(<vscale x 8 x half> %0, <vscale x 8 x half> %1) {
; CHECK-LABEL: uzp1_v8f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq1 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x half> @llvm.vector.segmented.shuffle.nxv8f16.v8i32(
    <vscale x 8 x half> %0, <vscale x 8 x half> %1, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>)
  ret <vscale x 8 x half> %res
}

define <vscale x 8 x bfloat> @uzp1_v8bf16(<vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1) {
; CHECK-LABEL: uzp1_v8bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq1 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x bfloat> @llvm.vector.segmented.shuffle.nxv8bf16.v8i32(
    <vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>)
  ret <vscale x 8 x bfloat> %res
}

define <vscale x 4 x i32> @uzp1_v4i32(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: uzp1_v4i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq1 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x i32> @llvm.vector.segmented.shuffle.nxv4i32.v4i32(
    <vscale x 4 x i32> %0, <vscale x 4 x i32> %1, <4 x i32> <i32 0, i32 2, i32 4, i32 6>)
  ret <vscale x 4 x i32> %res
}

define <vscale x 4 x i32> @uzp1_v4i16(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: uzp1_v4i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq1 z0.s, z0.s, z0.s
; CHECK-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %res = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(
    <vscale x 4 x i16> %leg0, <vscale x 4 x i16> %leg1, <4 x i32> <i32 0, i32 2, i32 4, i32 6>)
  %res.leg = zext <vscale x 4 x i16> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x i32> @uzp1_v4i8(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: uzp1_v4i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq1 z0.s, z0.s, z0.s
; CHECK-NEXT:    and z0.s, z0.s, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %res = call <vscale x 4 x i8> @llvm.vector.segmented.shuffle.nxv4i8.v4i32(
    <vscale x 4 x i8> %leg0, <vscale x 4 x i8> %leg1, <4 x i32> <i32 0, i32 2, i32 4, i32 6>)
  %res.leg = zext <vscale x 4 x i8> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x float> @uzp1_v4f32(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: uzp1_v4f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq1 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> %1, <4 x i32> <i32 0, i32 2, i32 4, i32 6>)
  ret <vscale x 4 x float> %res
}

define <vscale x 4 x half> @uzp1_v4f16(<vscale x 4 x half> %0, <vscale x 4 x half> %1) {
; CHECK-LABEL: uzp1_v4f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq1 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x half> @llvm.vector.segmented.shuffle.nxv4f16.v4i32(
    <vscale x 4 x half> %0, <vscale x 4 x half> %1, <4 x i32> <i32 0, i32 2, i32 4, i32 6>)
  ret <vscale x 4 x half> %res
}

define <vscale x 4 x float> @uzp1_v_undef(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: uzp1_v_undef:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq1 z0.s, z0.s, z0.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> poison, <4 x i32> <i32 0, i32 2, i32 0, i32 2>)
  ret <vscale x 4 x float> %res
}



; uzp2

define <vscale x 16 x i8> @uzp2_v16i8(<vscale x 16 x i8> %0, <vscale x 16 x i8> %1) {
; CHECK-LABEL: uzp2_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq2 z0.b, z0.b, z1.b
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(
    <vscale x 16 x i8> %0, <vscale x 16 x i8> %1, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>)
  ret <vscale x 16 x i8> %res
}

define <vscale x 8 x i16> @uzp2_v8i16(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: uzp2_v8i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq2 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(
    <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>)
  ret <vscale x 8 x i16> %res
}

define <vscale x 8 x i16> @uzp2_v8i8(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: uzp2_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq2 z0.h, z0.h, z1.h
; CHECK-NEXT:    and z0.h, z0.h, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %leg1 = trunc <vscale x 8 x i16> %1 to <vscale x 8 x i8>
  %res = call <vscale x 8 x i8> @llvm.vector.segmented.shuffle.nxv8i8.v8i32(
    <vscale x 8 x i8> %leg0, <vscale x 8 x i8> %leg1, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>)
  %res.leg = zext <vscale x 8 x i8> %res to <vscale x 8 x i16>
  ret <vscale x 8 x i16> %res.leg
}

define <vscale x 8 x half> @uzp2_v8f16(<vscale x 8 x half> %0, <vscale x 8 x half> %1) {
; CHECK-LABEL: uzp2_v8f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq2 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x half> @llvm.vector.segmented.shuffle.nxv8f16.v8i32(
    <vscale x 8 x half> %0, <vscale x 8 x half> %1, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>)
  ret <vscale x 8 x half> %res
}

define <vscale x 8 x bfloat> @uzp2_v8bf16(<vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1) {
; CHECK-LABEL: uzp2_v8bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq2 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x bfloat> @llvm.vector.segmented.shuffle.nxv8bf16.v8i32(
    <vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>)
  ret <vscale x 8 x bfloat> %res
}

define <vscale x 4 x i32> @uzp2_v4i32(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: uzp2_v4i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq2 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x i32> @llvm.vector.segmented.shuffle.nxv4i32.v4i32(
    <vscale x 4 x i32> %0, <vscale x 4 x i32> %1, <4 x i32> <i32 1, i32 3, i32 5, i32 7>)
  ret <vscale x 4 x i32> %res
}

define <vscale x 4 x i32> @uzp2_v4i16(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: uzp2_v4i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq2 z0.s, z0.s, z0.s
; CHECK-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %res = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(
    <vscale x 4 x i16> %leg0, <vscale x 4 x i16> %leg1, <4 x i32> <i32 1, i32 3, i32 5, i32 7>)
  %res.leg = zext <vscale x 4 x i16> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x i32> @uzp2_v4i8(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: uzp2_v4i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq2 z0.s, z0.s, z0.s
; CHECK-NEXT:    and z0.s, z0.s, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %res = call <vscale x 4 x i8> @llvm.vector.segmented.shuffle.nxv4i8.v4i32(
    <vscale x 4 x i8> %leg0, <vscale x 4 x i8> %leg1, <4 x i32> <i32 1, i32 3, i32 5, i32 7>)
  %res.leg = zext <vscale x 4 x i8> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x float> @uzp2_v4f32(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: uzp2_v4f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq2 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> %1, <4 x i32> <i32 1, i32 3, i32 5, i32 7>)
  ret <vscale x 4 x float> %res
}

define <vscale x 4 x half> @uzp2_v4f16(<vscale x 4 x half> %0, <vscale x 4 x half> %1) {
; CHECK-LABEL: uzp2_v4f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq2 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x half> @llvm.vector.segmented.shuffle.nxv4f16.v4i32(
    <vscale x 4 x half> %0, <vscale x 4 x half> %1, <4 x i32> <i32 1, i32 3, i32 5, i32 7>)
  ret <vscale x 4 x half> %res
}

define <vscale x 4 x float> @uzp2_v_undef(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: uzp2_v_undef:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    uzpq2 z0.s, z0.s, z0.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> poison, <4 x i32> <i32 1, i32 3, i32 1, i32 3>)
  ret <vscale x 4 x float> %res
}



; zip1

define <vscale x 16 x i8> @zip1_v16i8(<vscale x 16 x i8> %0, <vscale x 16 x i8> %1) {
; CHECK-LABEL: zip1_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq1 z0.b, z0.b, z1.b
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(
    <vscale x 16 x i8> %0, <vscale x 16 x i8> %1, <16 x i32> <i32 0, i32 16, i32 1, i32 17, i32 2, i32 18, i32 3, i32 19, i32 4, i32 20, i32 5, i32 21, i32 6, i32 22, i32 7, i32 23>)
  ret <vscale x 16 x i8> %res
}

define <vscale x 8 x i16> @zip1_v8i16(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: zip1_v8i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq1 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(
    <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 2, i32 10, i32 3, i32 11>)
  ret <vscale x 8 x i16> %res
}

define <vscale x 8 x i16> @zip1_v8i8(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: zip1_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq1 z0.h, z0.h, z1.h
; CHECK-NEXT:    and z0.h, z0.h, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %leg1 = trunc <vscale x 8 x i16> %1 to <vscale x 8 x i8>
  %res = call <vscale x 8 x i8> @llvm.vector.segmented.shuffle.nxv8i8.v8i32(
    <vscale x 8 x i8> %leg0, <vscale x 8 x i8> %leg1, <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 2, i32 10, i32 3, i32 11>)
  %res.leg = zext <vscale x 8 x i8> %res to <vscale x 8 x i16>
  ret <vscale x 8 x i16> %res.leg
}

define <vscale x 8 x half> @zip1_v8f16(<vscale x 8 x half> %0, <vscale x 8 x half> %1) {
; CHECK-LABEL: zip1_v8f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq1 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x half> @llvm.vector.segmented.shuffle.nxv8f16.v8i32(
    <vscale x 8 x half> %0, <vscale x 8 x half> %1, <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 2, i32 10, i32 3, i32 11>)
  ret <vscale x 8 x half> %res
}

define <vscale x 8 x bfloat> @zip1_v8bf16(<vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1) {
; CHECK-LABEL: zip1_v8bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq1 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x bfloat> @llvm.vector.segmented.shuffle.nxv8bf16.v8i32(
    <vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1, <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 2, i32 10, i32 3, i32 11>)
  ret <vscale x 8 x bfloat> %res
}

define <vscale x 4 x i32> @zip1_v4i32(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: zip1_v4i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq1 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x i32> @llvm.vector.segmented.shuffle.nxv4i32.v4i32(
    <vscale x 4 x i32> %0, <vscale x 4 x i32> %1, <4 x i32> <i32 0, i32 4, i32 1, i32 5>)
  ret <vscale x 4 x i32> %res
}

define <vscale x 4 x i32> @zip1_v4i16(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: zip1_v4i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq1 z0.s, z0.s, z0.s
; CHECK-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %res = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(
    <vscale x 4 x i16> %leg0, <vscale x 4 x i16> %leg1, <4 x i32> <i32 0, i32 4, i32 1, i32 5>)
  %res.leg = zext <vscale x 4 x i16> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x i32> @zip1_v4i8(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: zip1_v4i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq1 z0.s, z0.s, z0.s
; CHECK-NEXT:    and z0.s, z0.s, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %res = call <vscale x 4 x i8> @llvm.vector.segmented.shuffle.nxv4i8.v4i32(
    <vscale x 4 x i8> %leg0, <vscale x 4 x i8> %leg1, <4 x i32> <i32 0, i32 4, i32 1, i32 5>)
  %res.leg = zext <vscale x 4 x i8> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x float> @zip1_v4f32(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: zip1_v4f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq1 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> %1, <4 x i32> <i32 0, i32 4, i32 1, i32 5>)
  ret <vscale x 4 x float> %res
}

define <vscale x 4 x half> @zip1_v4f16(<vscale x 4 x half> %0, <vscale x 4 x half> %1) {
; CHECK-LABEL: zip1_v4f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq1 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x half> @llvm.vector.segmented.shuffle.nxv4f16.v4i32(
    <vscale x 4 x half> %0, <vscale x 4 x half> %1, <4 x i32> <i32 0, i32 4, i32 1, i32 5>)
  ret <vscale x 4 x half> %res
}

define <vscale x 4 x float> @zip1_v_undef(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: zip1_v_undef:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq1 z0.s, z0.s, z0.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> poison, <4 x i32> <i32 0, i32 0, i32 1, i32 1>)
  ret <vscale x 4 x float> %res
}



; zip2

define <vscale x 16 x i8> @zip2_v16i8(<vscale x 16 x i8> %0, <vscale x 16 x i8> %1) {
; CHECK-LABEL: zip2_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq2 z0.b, z0.b, z1.b
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(
    <vscale x 16 x i8> %0, <vscale x 16 x i8> %1, <16 x i32> <i32 8, i32 24, i32 9, i32 25, i32 10, i32 26, i32 11, i32 27, i32 12, i32 28, i32 13, i32 29, i32 14, i32 30, i32 15, i32 31>)
  ret <vscale x 16 x i8> %res
}

define <vscale x 8 x i16> @zip2_v8i16(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: zip2_v8i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq2 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(
    <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, <8 x i32> <i32 4, i32 12, i32 5, i32 13, i32 6, i32 14, i32 7, i32 15>)
  ret <vscale x 8 x i16> %res
}

define <vscale x 8 x i16> @zip2_v8i8(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: zip2_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq2 z0.h, z0.h, z1.h
; CHECK-NEXT:    and z0.h, z0.h, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %leg1 = trunc <vscale x 8 x i16> %1 to <vscale x 8 x i8>
  %res = call <vscale x 8 x i8> @llvm.vector.segmented.shuffle.nxv8i8.v8i32(
    <vscale x 8 x i8> %leg0, <vscale x 8 x i8> %leg1, <8 x i32> <i32 4, i32 12, i32 5, i32 13, i32 6, i32 14, i32 7, i32 15>)
  %res.leg = zext <vscale x 8 x i8> %res to <vscale x 8 x i16>
  ret <vscale x 8 x i16> %res.leg
}

define <vscale x 8 x half> @zip2_v8f16(<vscale x 8 x half> %0, <vscale x 8 x half> %1) {
; CHECK-LABEL: zip2_v8f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq2 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x half> @llvm.vector.segmented.shuffle.nxv8f16.v8i32(
    <vscale x 8 x half> %0, <vscale x 8 x half> %1, <8 x i32> <i32 4, i32 12, i32 5, i32 13, i32 6, i32 14, i32 7, i32 15>)
  ret <vscale x 8 x half> %res
}

define <vscale x 8 x bfloat> @zip2_v8bf16(<vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1) {
; CHECK-LABEL: zip2_v8bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq2 z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x bfloat> @llvm.vector.segmented.shuffle.nxv8bf16.v8i32(
    <vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1, <8 x i32> <i32 4, i32 12, i32 5, i32 13, i32 6, i32 14, i32 7, i32 15>)
  ret <vscale x 8 x bfloat> %res
}

define <vscale x 4 x i32> @zip2_v4i32(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: zip2_v4i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq2 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x i32> @llvm.vector.segmented.shuffle.nxv4i32.v4i32(
    <vscale x 4 x i32> %0, <vscale x 4 x i32> %1, <4 x i32> <i32 2, i32 6, i32 3, i32 7>)
  ret <vscale x 4 x i32> %res
}

define <vscale x 4 x i32> @zip2_v4i16(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: zip2_v4i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq2 z0.s, z0.s, z0.s
; CHECK-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %res = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(
    <vscale x 4 x i16> %leg0, <vscale x 4 x i16> %leg1, <4 x i32> <i32 2, i32 6, i32 3, i32 7>)
  %res.leg = zext <vscale x 4 x i16> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x i32> @zip2_v4i8(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: zip2_v4i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq2 z0.s, z0.s, z0.s
; CHECK-NEXT:    and z0.s, z0.s, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %res = call <vscale x 4 x i8> @llvm.vector.segmented.shuffle.nxv4i8.v4i32(
    <vscale x 4 x i8> %leg0, <vscale x 4 x i8> %leg1, <4 x i32> <i32 2, i32 6, i32 3, i32 7>)
  %res.leg = zext <vscale x 4 x i8> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x float> @zip2_v4f32(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: zip2_v4f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq2 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> %1, <4 x i32> <i32 2, i32 6, i32 3, i32 7>)
  ret <vscale x 4 x float> %res
}

define <vscale x 4 x half> @zip2_v4f16(<vscale x 4 x half> %0, <vscale x 4 x half> %1) {
; CHECK-LABEL: zip2_v4f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq2 z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x half> @llvm.vector.segmented.shuffle.nxv4f16.v4i32(
    <vscale x 4 x half> %0, <vscale x 4 x half> %1, <4 x i32> <i32 2, i32 6, i32 3, i32 7>)
  ret <vscale x 4 x half> %res
}

define <vscale x 4 x float> @zip2_v_undef(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: zip2_v_undef:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    zipq2 z0.s, z0.s, z0.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> poison, <4 x i32> <i32 2, i32 2, i32 3, i32 3>)
  ret <vscale x 4 x float> %res
}



; ext

define <vscale x 16 x i8> @ext_v16i8(<vscale x 16 x i8> %0, <vscale x 16 x i8> %1) {
; CHECK-LABEL: ext_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    extq z0.b, z0.b, z1.b, #5
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(
    <vscale x 16 x i8> %0, <vscale x 16 x i8> %1, <16 x i32> <i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20>)
  ret <vscale x 16 x i8> %res
}

define <vscale x 8 x i16> @ext_v8i16(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: ext_v8i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    extq z0.b, z0.b, z1.b, #10
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(
    <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, <8 x i32> <i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12>)
  ret <vscale x 8 x i16> %res
}

define <vscale x 8 x i16> @ext_v8i8(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: ext_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    extq z0.b, z0.b, z1.b, #10
; CHECK-NEXT:    and z0.h, z0.h, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %leg1 = trunc <vscale x 8 x i16> %1 to <vscale x 8 x i8>
  %res = call <vscale x 8 x i8> @llvm.vector.segmented.shuffle.nxv8i8.v8i32(
    <vscale x 8 x i8> %leg0, <vscale x 8 x i8> %leg1, <8 x i32> <i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12>)
  %res.leg = zext <vscale x 8 x i8> %res to <vscale x 8 x i16>
  ret <vscale x 8 x i16> %res.leg
}

define <vscale x 8 x half> @ext_v8f16(<vscale x 8 x half> %0, <vscale x 8 x half> %1) {
; CHECK-LABEL: ext_v8f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    extq z0.b, z0.b, z1.b, #10
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x half> @llvm.vector.segmented.shuffle.nxv8f16.v8i32(
    <vscale x 8 x half> %0, <vscale x 8 x half> %1, <8 x i32> <i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12>)
  ret <vscale x 8 x half> %res
}

define <vscale x 8 x bfloat> @ext_v8bf16(<vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1) {
; CHECK-LABEL: ext_v8bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    extq z0.b, z0.b, z1.b, #10
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x bfloat> @llvm.vector.segmented.shuffle.nxv8bf16.v8i32(
    <vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1, <8 x i32> <i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12>)
  ret <vscale x 8 x bfloat> %res
}

define <vscale x 4 x i32> @ext_v4i32(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: ext_v4i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    extq z0.b, z0.b, z1.b, #12
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x i32> @llvm.vector.segmented.shuffle.nxv4i32.v4i32(
    <vscale x 4 x i32> %0, <vscale x 4 x i32> %1, <4 x i32> <i32 3, i32 4, i32 5, i32 6>)
  ret <vscale x 4 x i32> %res
}

define <vscale x 4 x i32> @ext_v4i16(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: ext_v4i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    extq z0.b, z0.b, z0.b, #12
; CHECK-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %res = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(
    <vscale x 4 x i16> %leg0, <vscale x 4 x i16> %leg1, <4 x i32> <i32 3, i32 4, i32 5, i32 6>)
  %res.leg = zext <vscale x 4 x i16> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x i32> @ext_v4i8(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: ext_v4i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    extq z0.b, z0.b, z0.b, #12
; CHECK-NEXT:    and z0.s, z0.s, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %res = call <vscale x 4 x i8> @llvm.vector.segmented.shuffle.nxv4i8.v4i32(
    <vscale x 4 x i8> %leg0, <vscale x 4 x i8> %leg1, <4 x i32> <i32 3, i32 4, i32 5, i32 6>)
  %res.leg = zext <vscale x 4 x i8> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x float> @ext_v4f32(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: ext_v4f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    extq z0.b, z0.b, z1.b, #12
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> %1, <4 x i32> <i32 3, i32 4, i32 5, i32 6>)
  ret <vscale x 4 x float> %res
}

define <vscale x 4 x half> @ext_v4f16(<vscale x 4 x half> %0, <vscale x 4 x half> %1) {
; CHECK-LABEL: ext_v4f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    extq z0.b, z0.b, z1.b, #12
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x half> @llvm.vector.segmented.shuffle.nxv4f16.v4i32(
    <vscale x 4 x half> %0, <vscale x 4 x half> %1, <4 x i32> <i32 3, i32 4, i32 5, i32 6>)
  ret <vscale x 4 x half> %res
}

define <vscale x 2 x i64> @ext_v2i64(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1) {
; CHECK-LABEL: ext_v2i64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    extq z0.b, z0.b, z1.b, #8
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x i64> @llvm.vector.segmented.shuffle.nxv2i64.v2i32(
    <vscale x 2 x i64> %0, <vscale x 2 x i64> %1, <2 x i32> <i32 1, i32 2>)
  ret <vscale x 2 x i64> %res
}

define <vscale x 2 x i64> @ext_v2i32(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1) {
; CHECK-LABEL: ext_v2i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    extq z0.b, z0.b, z0.b, #8
; CHECK-NEXT:    and z0.d, z0.d, #0xffffffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 2 x i64> %0 to <vscale x 2 x i32>
  %leg1 = trunc <vscale x 2 x i64> %0 to <vscale x 2 x i32>
  %res = call <vscale x 2 x i32> @llvm.vector.segmented.shuffle.nxv2i32.v2i32(
    <vscale x 2 x i32> %leg0, <vscale x 2 x i32> %leg1, <2 x i32> <i32 1, i32 2>)
  %res.leg = zext <vscale x 2 x i32> %res to <vscale x 2 x i64>
  ret <vscale x 2 x i64> %res.leg
}

define <vscale x 2 x double> @ext_v2f64(<vscale x 2 x double> %0, <vscale x 2 x double> %1) {
; CHECK-LABEL: ext_v2f64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    extq z0.b, z0.b, z1.b, #8
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x double> @llvm.vector.segmented.shuffle.nxv2f64.v2i32(
    <vscale x 2 x double> %0, <vscale x 2 x double> %1, <2 x i32> <i32 1, i32 2>)
  ret <vscale x 2 x double> %res
}

define <vscale x 2 x float> @ext_v2f32(<vscale x 2 x float> %0, <vscale x 2 x float> %1) {
; CHECK-LABEL: ext_v2f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    extq z0.b, z0.b, z1.b, #8
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x float> @llvm.vector.segmented.shuffle.nxv2f32.v2i32(
    <vscale x 2 x float> %0, <vscale x 2 x float> %1, <2 x i32> <i32 1, i32 2>)
  ret <vscale x 2 x float> %res
}



; dup

define <vscale x 16 x i8> @dup_v16i8(<vscale x 16 x i8> %0, <vscale x 16 x i8> %1) {
; CHECK-LABEL: dup_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    dupq z0.b, z0.b[7]
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(
    <vscale x 16 x i8> %0, <vscale x 16 x i8> %1, <16 x i32> <i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7>)
  ret <vscale x 16 x i8> %res
}

define <vscale x 8 x i16> @dup_v8i16(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: dup_v8i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    dupq z0.h, z0.h[7]
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(
    <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, <8 x i32> <i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7>)
  ret <vscale x 8 x i16> %res
}

define <vscale x 8 x i16> @dup_v8i8(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: dup_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    dupq z0.h, z0.h[7]
; CHECK-NEXT:    and z0.h, z0.h, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %leg1 = trunc <vscale x 8 x i16> %1 to <vscale x 8 x i8>
  %res = call <vscale x 8 x i8> @llvm.vector.segmented.shuffle.nxv8i8.v8i32(
    <vscale x 8 x i8> %leg0, <vscale x 8 x i8> %leg1, <8 x i32> <i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7>)
  %res.leg = zext <vscale x 8 x i8> %res to <vscale x 8 x i16>
  ret <vscale x 8 x i16> %res.leg
}

define <vscale x 8 x half> @dup_v8f16(<vscale x 8 x half> %0, <vscale x 8 x half> %1) {
; CHECK-LABEL: dup_v8f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    dupq z0.h, z0.h[7]
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x half> @llvm.vector.segmented.shuffle.nxv8f16.v8i32(
    <vscale x 8 x half> %0, <vscale x 8 x half> %1, <8 x i32> <i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7>)
  ret <vscale x 8 x half> %res
}

define <vscale x 8 x bfloat> @dup_v8bf16(<vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1) {
; CHECK-LABEL: dup_v8bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    dupq z0.h, z0.h[7]
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x bfloat> @llvm.vector.segmented.shuffle.nxv8bf16.v8i32(
    <vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1, <8 x i32> <i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7>)
  ret <vscale x 8 x bfloat> %res
}

define <vscale x 4 x i32> @dup_v4i32(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: dup_v4i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    dupq z0.s, z0.s[2]
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x i32> @llvm.vector.segmented.shuffle.nxv4i32.v4i32(
    <vscale x 4 x i32> %0, <vscale x 4 x i32> %1, <4 x i32> <i32 2, i32 2, i32 2, i32 2>)
  ret <vscale x 4 x i32> %res
}

define <vscale x 4 x i32> @dup_v4i16(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: dup_v4i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    dupq z0.s, z0.s[2]
; CHECK-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %res = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(
    <vscale x 4 x i16> %leg0, <vscale x 4 x i16> %leg1, <4 x i32> <i32 2, i32 2, i32 2, i32 2>)
  %res.leg = zext <vscale x 4 x i16> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x i32> @dup_v4i8(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: dup_v4i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    dupq z0.s, z0.s[2]
; CHECK-NEXT:    and z0.s, z0.s, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %res = call <vscale x 4 x i8> @llvm.vector.segmented.shuffle.nxv4i8.v4i32(
    <vscale x 4 x i8> %leg0, <vscale x 4 x i8> %leg1, <4 x i32> <i32 2, i32 2, i32 2, i32 2>)
  %res.leg = zext <vscale x 4 x i8> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x float> @dup_v4f32(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: dup_v4f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    dupq z0.s, z0.s[2]
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> %1, <4 x i32> <i32 2, i32 2, i32 2, i32 2>)
  ret <vscale x 4 x float> %res
}

define <vscale x 4 x half> @dup_v4f16(<vscale x 4 x half> %0, <vscale x 4 x half> %1) {
; CHECK-LABEL: dup_v4f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    dupq z0.s, z0.s[2]
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x half> @llvm.vector.segmented.shuffle.nxv4f16.v4i32(
    <vscale x 4 x half> %0, <vscale x 4 x half> %1, <4 x i32> <i32 2, i32 2, i32 2, i32 2>)
  ret <vscale x 4 x half> %res
}

define <vscale x 2 x i64> @dup_v2i64(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1) {
; CHECK-LABEL: dup_v2i64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    dupq z0.d, z0.d[1]
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x i64> @llvm.vector.segmented.shuffle.nxv2i64.v2i32(
    <vscale x 2 x i64> %0, <vscale x 2 x i64> %1, <2 x i32> <i32 1, i32 1>)
  ret <vscale x 2 x i64> %res
}

define <vscale x 2 x i64> @dup_v2i32(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1) {
; CHECK-LABEL: dup_v2i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    dupq z0.d, z0.d[1]
; CHECK-NEXT:    and z0.d, z0.d, #0xffffffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 2 x i64> %0 to <vscale x 2 x i32>
  %leg1 = trunc <vscale x 2 x i64> %0 to <vscale x 2 x i32>
  %res = call <vscale x 2 x i32> @llvm.vector.segmented.shuffle.nxv2i32.v2i32(
    <vscale x 2 x i32> %leg0, <vscale x 2 x i32> %leg1, <2 x i32> <i32 1, i32 1>)
  %res.leg = zext <vscale x 2 x i32> %res to <vscale x 2 x i64>
  ret <vscale x 2 x i64> %res.leg
}

define <vscale x 2 x double> @dup_v2f64(<vscale x 2 x double> %0, <vscale x 2 x double> %1) {
; CHECK-LABEL: dup_v2f64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    dupq z0.d, z0.d[1]
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x double> @llvm.vector.segmented.shuffle.nxv2f64.v2i32(
    <vscale x 2 x double> %0, <vscale x 2 x double> %1, <2 x i32> <i32 1, i32 1>)
  ret <vscale x 2 x double> %res
}

define <vscale x 2 x float> @dup_v2f32(<vscale x 2 x float> %0, <vscale x 2 x float> %1) {
; CHECK-LABEL: dup_v2f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    dupq z0.d, z0.d[1]
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x float> @llvm.vector.segmented.shuffle.nxv2f32.v2i32(
    <vscale x 2 x float> %0, <vscale x 2 x float> %1, <2 x i32> <i32 1, i32 1>)
  ret <vscale x 2 x float> %res
}



; rev

define <vscale x 16 x i8> @rev_v16i8(<vscale x 16 x i8> %0, <vscale x 16 x i8> %1) {
; CHECK-LABEL: rev_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/m, z0.q
; CHECK-NEXT:    revb z0.d, p1/m, z0.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(
    <vscale x 16 x i8> %0, <vscale x 16 x i8> %1, <16 x i32> <i32 15, i32 14, i32 13, i32 12, i32 11, i32 10, i32 9, i32 8, i32 7, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 16 x i8> %res
}

define <vscale x 8 x i16> @rev_v8i16(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: rev_v8i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/m, z0.q
; CHECK-NEXT:    revh z0.d, p1/m, z0.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(
    <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, <8 x i32> <i32 7, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 8 x i16> %res
}

define <vscale x 8 x i16> @rev_v8i8(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: rev_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/m, z0.q
; CHECK-NEXT:    revh z0.d, p1/m, z0.d
; CHECK-NEXT:    and z0.h, z0.h, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %leg1 = trunc <vscale x 8 x i16> %1 to <vscale x 8 x i8>
  %res = call <vscale x 8 x i8> @llvm.vector.segmented.shuffle.nxv8i8.v8i32(
    <vscale x 8 x i8> %leg0, <vscale x 8 x i8> %leg1, <8 x i32> <i32 7, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>)
  %res.leg = zext <vscale x 8 x i8> %res to <vscale x 8 x i16>
  ret <vscale x 8 x i16> %res.leg
}

define <vscale x 8 x half> @rev_v8f16(<vscale x 8 x half> %0, <vscale x 8 x half> %1) {
; CHECK-LABEL: rev_v8f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/m, z0.q
; CHECK-NEXT:    revh z0.d, p1/m, z0.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x half> @llvm.vector.segmented.shuffle.nxv8f16.v8i32(
    <vscale x 8 x half> %0, <vscale x 8 x half> %1, <8 x i32> <i32 7, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 8 x half> %res
}

define <vscale x 8 x bfloat> @rev_v8bf16(<vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1) {
; CHECK-LABEL: rev_v8bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/m, z0.q
; CHECK-NEXT:    revh z0.d, p1/m, z0.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x bfloat> @llvm.vector.segmented.shuffle.nxv8bf16.v8i32(
    <vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1, <8 x i32> <i32 7, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 8 x bfloat> %res
}

define <vscale x 4 x i32> @rev_v4i32(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: rev_v4i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/m, z0.q
; CHECK-NEXT:    revw z0.d, p1/m, z0.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x i32> @llvm.vector.segmented.shuffle.nxv4i32.v4i32(
    <vscale x 4 x i32> %0, <vscale x 4 x i32> %1, <4 x i32> <i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 4 x i32> %res
}

define <vscale x 4 x i32> @rev_v4i16(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: rev_v4i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/m, z0.q
; CHECK-NEXT:    revw z0.d, p1/m, z0.d
; CHECK-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %res = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(
    <vscale x 4 x i16> %leg0, <vscale x 4 x i16> %leg1, <4 x i32> <i32 3, i32 2, i32 1, i32 0>)
  %res.leg = zext <vscale x 4 x i16> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x i32> @rev_v4i8(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: rev_v4i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/m, z0.q
; CHECK-NEXT:    revw z0.d, p1/m, z0.d
; CHECK-NEXT:    and z0.s, z0.s, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %res = call <vscale x 4 x i8> @llvm.vector.segmented.shuffle.nxv4i8.v4i32(
    <vscale x 4 x i8> %leg0, <vscale x 4 x i8> %leg1, <4 x i32> <i32 3, i32 2, i32 1, i32 0>)
  %res.leg = zext <vscale x 4 x i8> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x float> @rev_v4f32(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: rev_v4f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/m, z0.q
; CHECK-NEXT:    revw z0.d, p1/m, z0.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> %1, <4 x i32> <i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 4 x float> %res
}

define <vscale x 4 x half> @rev_v4f16(<vscale x 4 x half> %0, <vscale x 4 x half> %1) {
; CHECK-LABEL: rev_v4f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    ptrue p1.d
; CHECK-NEXT:    revd z0.q, p0/m, z0.q
; CHECK-NEXT:    revw z0.d, p1/m, z0.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x half> @llvm.vector.segmented.shuffle.nxv4f16.v4i32(
    <vscale x 4 x half> %0, <vscale x 4 x half> %1, <4 x i32> <i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 4 x half> %res
}

define <vscale x 2 x i64> @rev_v2i64(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1) {
; CHECK-LABEL: rev_v2i64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    revd z0.q, p0/m, z0.q
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x i64> @llvm.vector.segmented.shuffle.nxv2i64.v2i32(
    <vscale x 2 x i64> %0, <vscale x 2 x i64> %1, <2 x i32> <i32 1, i32 0>)
  ret <vscale x 2 x i64> %res
}

define <vscale x 2 x i64> @rev_v2i32(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1) {
; CHECK-LABEL: rev_v2i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    revd z0.q, p0/m, z0.q
; CHECK-NEXT:    and z0.d, z0.d, #0xffffffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 2 x i64> %0 to <vscale x 2 x i32>
  %leg1 = trunc <vscale x 2 x i64> %0 to <vscale x 2 x i32>
  %res = call <vscale x 2 x i32> @llvm.vector.segmented.shuffle.nxv2i32.v2i32(
    <vscale x 2 x i32> %leg0, <vscale x 2 x i32> %leg1, <2 x i32> <i32 1, i32 0>)
  %res.leg = zext <vscale x 2 x i32> %res to <vscale x 2 x i64>
  ret <vscale x 2 x i64> %res.leg
}

define <vscale x 2 x double> @rev_v2f64(<vscale x 2 x double> %0, <vscale x 2 x double> %1) {
; CHECK-LABEL: rev_v2f64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    revd z0.q, p0/m, z0.q
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x double> @llvm.vector.segmented.shuffle.nxv2f64.v2i32(
    <vscale x 2 x double> %0, <vscale x 2 x double> %1, <2 x i32> <i32 1, i32 0>)
  ret <vscale x 2 x double> %res
}

define <vscale x 2 x float> @rev_v2f32(<vscale x 2 x float> %0, <vscale x 2 x float> %1) {
; CHECK-LABEL: rev_v2f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    revd z0.q, p0/m, z0.q
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x float> @llvm.vector.segmented.shuffle.nxv2f32.v2i32(
    <vscale x 2 x float> %0, <vscale x 2 x float> %1, <2 x i32> <i32 1, i32 0>)
  ret <vscale x 2 x float> %res
}



; tbl1; arbitrary 2-input shuffle

define <vscale x 16 x i8> @tbl1_v16i8(<vscale x 16 x i8> %0, <vscale x 16 x i8> %1) {
; CHECK-LABEL: tbl1_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    adrp x8, .LCPI116_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI116_0
; CHECK-NEXT:    ld1rqb { z1.b }, p0/z, [x8]
; CHECK-NEXT:    tblq z0.b, { z0.b }, z1.b
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(
    <vscale x 16 x i8> %0, <vscale x 16 x i8> %1, <16 x i32> <i32 15, i32 14, i32 10, i32 12, i32 11, i32 10, i32 9, i32 8, i32 10, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 16 x i8> %res
}

define <vscale x 8 x i16> @tbl1_v8i16(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: tbl1_v8i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    adrp x8, .LCPI117_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI117_0
; CHECK-NEXT:    ld1rqh { z1.h }, p0/z, [x8]
; CHECK-NEXT:    tblq z0.h, { z0.h }, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(
    <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, <8 x i32> <i32 7, i32 6, i32 3, i32 4, i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 8 x i16> %res
}

define <vscale x 8 x i16> @tbl1_v8i8(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: tbl1_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    adrp x8, .LCPI118_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI118_0
; CHECK-NEXT:    ld1rqh { z1.h }, p0/z, [x8]
; CHECK-NEXT:    tblq z0.h, { z0.h }, z1.h
; CHECK-NEXT:    and z0.h, z0.h, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %leg1 = trunc <vscale x 8 x i16> %1 to <vscale x 8 x i8>
  %res = call <vscale x 8 x i8> @llvm.vector.segmented.shuffle.nxv8i8.v8i32(
    <vscale x 8 x i8> %leg0, <vscale x 8 x i8> %leg1, <8 x i32> <i32 7, i32 6, i32 3, i32 4, i32 3, i32 2, i32 1, i32 0>)
  %res.leg = zext <vscale x 8 x i8> %res to <vscale x 8 x i16>
  ret <vscale x 8 x i16> %res.leg
}

define <vscale x 8 x half> @tbl1_v8f16(<vscale x 8 x half> %0, <vscale x 8 x half> %1) {
; CHECK-LABEL: tbl1_v8f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    adrp x8, .LCPI119_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI119_0
; CHECK-NEXT:    ld1rqh { z1.h }, p0/z, [x8]
; CHECK-NEXT:    tblq z0.h, { z0.h }, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x half> @llvm.vector.segmented.shuffle.nxv8f16.v8i32(
    <vscale x 8 x half> %0, <vscale x 8 x half> %1, <8 x i32> <i32 7, i32 6, i32 5, i32 3, i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 8 x half> %res
}

define <vscale x 8 x bfloat> @tbl1_v8bf16(<vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1) {
; CHECK-LABEL: tbl1_v8bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    adrp x8, .LCPI120_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI120_0
; CHECK-NEXT:    ld1rqh { z1.h }, p0/z, [x8]
; CHECK-NEXT:    tblq z0.h, { z0.h }, z1.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x bfloat> @llvm.vector.segmented.shuffle.nxv8bf16.v8i32(
    <vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1, <8 x i32> <i32 7, i32 6, i32 5, i32 3, i32 3, i32 2, i32 1, i32 0>)
  ret <vscale x 8 x bfloat> %res
}

define <vscale x 4 x i32> @tbl1_v4i32(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: tbl1_v4i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    adrp x8, .LCPI121_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI121_0
; CHECK-NEXT:    ld1rqw { z1.s }, p0/z, [x8]
; CHECK-NEXT:    tblq z0.s, { z0.s }, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x i32> @llvm.vector.segmented.shuffle.nxv4i32.v4i32(
    <vscale x 4 x i32> %0, <vscale x 4 x i32> %1, <4 x i32> <i32 3, i32 3, i32 1, i32 0>)
  ret <vscale x 4 x i32> %res
}

define <vscale x 4 x i32> @tbl1_v4i16(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: tbl1_v4i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    adrp x8, .LCPI122_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI122_0
; CHECK-NEXT:    ld1rqw { z1.s }, p0/z, [x8]
; CHECK-NEXT:    tblq z0.s, { z0.s }, z1.s
; CHECK-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %res = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(
    <vscale x 4 x i16> %leg0, <vscale x 4 x i16> %leg1, <4 x i32> <i32 3, i32 3, i32 1, i32 0>)
  %res.leg = zext <vscale x 4 x i16> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x i32> @tbl1_v4i8(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: tbl1_v4i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    adrp x8, .LCPI123_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI123_0
; CHECK-NEXT:    ld1rqw { z1.s }, p0/z, [x8]
; CHECK-NEXT:    tblq z0.s, { z0.s }, z1.s
; CHECK-NEXT:    and z0.s, z0.s, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %res = call <vscale x 4 x i8> @llvm.vector.segmented.shuffle.nxv4i8.v4i32(
    <vscale x 4 x i8> %leg0, <vscale x 4 x i8> %leg1, <4 x i32> <i32 3, i32 3, i32 1, i32 0>)
  %res.leg = zext <vscale x 4 x i8> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x float> @tbl1_v4f32(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: tbl1_v4f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    adrp x8, .LCPI124_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI124_0
; CHECK-NEXT:    ld1rqw { z1.s }, p0/z, [x8]
; CHECK-NEXT:    tblq z0.s, { z0.s }, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> %1, <4 x i32> <i32 3, i32 3, i32 1, i32 0>)
  ret <vscale x 4 x float> %res
}

define <vscale x 4 x half> @tbl1_v4f16(<vscale x 4 x half> %0, <vscale x 4 x half> %1) {
; CHECK-LABEL: tbl1_v4f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    adrp x8, .LCPI125_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI125_0
; CHECK-NEXT:    ld1rqw { z1.s }, p0/z, [x8]
; CHECK-NEXT:    tblq z0.s, { z0.s }, z1.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x half> @llvm.vector.segmented.shuffle.nxv4f16.v4i32(
    <vscale x 4 x half> %0, <vscale x 4 x half> %1, <4 x i32> <i32 3, i32 3, i32 1, i32 0>)
  ret <vscale x 4 x half> %res
}



; tbl2; arbitrary 1-input shuffle

define <vscale x 16 x i8> @tbl2_v16i8(<vscale x 16 x i8> %0, <vscale x 16 x i8> %1) {
; CHECK-LABEL: tbl2_v16i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.b
; CHECK-NEXT:    adrp x8, .LCPI126_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI126_0
; CHECK-NEXT:    ld1rqb { z2.b }, p0/z, [x8]
; CHECK-NEXT:    movprfx z3, z2
; CHECK-NEXT:    sub z3.b, z3.b, #16 // =0x10
; CHECK-NEXT:    tblq z0.b, { z0.b }, z2.b
; CHECK-NEXT:    tbxq z0.b, z1.b, z3.b
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(
    <vscale x 16 x i8> %0, <vscale x 16 x i8> %1, <16 x i32> <i32 5, i32 6, i32 2, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20>)
  ret <vscale x 16 x i8> %res
}

define <vscale x 8 x i16> @tbl2_v8i16(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: tbl2_v8i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    adrp x8, .LCPI127_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI127_0
; CHECK-NEXT:    ld1rqh { z2.h }, p0/z, [x8]
; CHECK-NEXT:    movprfx z3, z2
; CHECK-NEXT:    sub z3.h, z3.h, #8 // =0x8
; CHECK-NEXT:    tblq z0.h, { z0.h }, z2.h
; CHECK-NEXT:    tbxq z0.h, z1.h, z3.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(
    <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, <8 x i32> <i32 5, i32 6, i32 2, i32 8, i32 9, i32 10, i32 11, i32 12>)
  ret <vscale x 8 x i16> %res
}

define <vscale x 8 x i16> @tbl2_v8i8(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1) {
; CHECK-LABEL: tbl2_v8i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    adrp x8, .LCPI128_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI128_0
; CHECK-NEXT:    ld1rqh { z2.h }, p0/z, [x8]
; CHECK-NEXT:    movprfx z3, z2
; CHECK-NEXT:    sub z3.h, z3.h, #8 // =0x8
; CHECK-NEXT:    tblq z0.h, { z0.h }, z2.h
; CHECK-NEXT:    tbxq z0.h, z1.h, z3.h
; CHECK-NEXT:    and z0.h, z0.h, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 8 x i16> %0 to <vscale x 8 x i8>
  %leg1 = trunc <vscale x 8 x i16> %1 to <vscale x 8 x i8>
  %res = call <vscale x 8 x i8> @llvm.vector.segmented.shuffle.nxv8i8.v8i32(
    <vscale x 8 x i8> %leg0, <vscale x 8 x i8> %leg1, <8 x i32> <i32 5, i32 6, i32 2, i32 8, i32 9, i32 10, i32 11, i32 12>)
  %res.leg = zext <vscale x 8 x i8> %res to <vscale x 8 x i16>
  ret <vscale x 8 x i16> %res.leg
}

define <vscale x 8 x half> @tbl2_v8f16(<vscale x 8 x half> %0, <vscale x 8 x half> %1) {
; CHECK-LABEL: tbl2_v8f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    adrp x8, .LCPI129_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI129_0
; CHECK-NEXT:    ld1rqh { z2.h }, p0/z, [x8]
; CHECK-NEXT:    movprfx z3, z2
; CHECK-NEXT:    sub z3.h, z3.h, #8 // =0x8
; CHECK-NEXT:    tblq z0.h, { z0.h }, z2.h
; CHECK-NEXT:    tbxq z0.h, z1.h, z3.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x half> @llvm.vector.segmented.shuffle.nxv8f16.v8i32(
    <vscale x 8 x half> %0, <vscale x 8 x half> %1, <8 x i32> <i32 5, i32 6, i32 2, i32 8, i32 9, i32 10, i32 11, i32 12>)
  ret <vscale x 8 x half> %res
}

define <vscale x 8 x bfloat> @tbl2_v8bf16(<vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1) {
; CHECK-LABEL: tbl2_v8bf16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    adrp x8, .LCPI130_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI130_0
; CHECK-NEXT:    ld1rqh { z2.h }, p0/z, [x8]
; CHECK-NEXT:    movprfx z3, z2
; CHECK-NEXT:    sub z3.h, z3.h, #8 // =0x8
; CHECK-NEXT:    tblq z0.h, { z0.h }, z2.h
; CHECK-NEXT:    tbxq z0.h, z1.h, z3.h
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 8 x bfloat> @llvm.vector.segmented.shuffle.nxv8bf16.v8i32(
    <vscale x 8 x bfloat> %0, <vscale x 8 x bfloat> %1, <8 x i32> <i32 5, i32 3, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12>)
  ret <vscale x 8 x bfloat> %res
}

define <vscale x 4 x i32> @tbl2_v4i32(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: tbl2_v4i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    adrp x8, .LCPI131_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI131_0
; CHECK-NEXT:    ld1rqw { z2.s }, p0/z, [x8]
; CHECK-NEXT:    movprfx z3, z2
; CHECK-NEXT:    sub z3.s, z3.s, #4 // =0x4
; CHECK-NEXT:    tblq z0.s, { z0.s }, z2.s
; CHECK-NEXT:    tbxq z0.s, z1.s, z3.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x i32> @llvm.vector.segmented.shuffle.nxv4i32.v4i32(
    <vscale x 4 x i32> %0, <vscale x 4 x i32> %1, <4 x i32> <i32 3, i32 3, i32 5, i32 6>)
  ret <vscale x 4 x i32> %res
}

define <vscale x 4 x i32> @tbl2_v4i16(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: tbl2_v4i16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    adrp x8, .LCPI132_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI132_0
; CHECK-NEXT:    ld1rqw { z1.s }, p0/z, [x8]
; CHECK-NEXT:    movprfx z2, z1
; CHECK-NEXT:    sub z2.s, z2.s, #4 // =0x4
; CHECK-NEXT:    tblq z1.s, { z0.s }, z1.s
; CHECK-NEXT:    tbxq z1.s, z0.s, z2.s
; CHECK-NEXT:    movprfx z0, z1
; CHECK-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i16>
  %res = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(
    <vscale x 4 x i16> %leg0, <vscale x 4 x i16> %leg1, <4 x i32> <i32 3, i32 3, i32 5, i32 6>)
  %res.leg = zext <vscale x 4 x i16> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x i32> @tbl2_v4i8(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1) {
; CHECK-LABEL: tbl2_v4i8:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    adrp x8, .LCPI133_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI133_0
; CHECK-NEXT:    ld1rqw { z1.s }, p0/z, [x8]
; CHECK-NEXT:    movprfx z2, z1
; CHECK-NEXT:    sub z2.s, z2.s, #4 // =0x4
; CHECK-NEXT:    tblq z1.s, { z0.s }, z1.s
; CHECK-NEXT:    tbxq z1.s, z0.s, z2.s
; CHECK-NEXT:    movprfx z0, z1
; CHECK-NEXT:    and z0.s, z0.s, #0xff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %leg1 = trunc <vscale x 4 x i32> %0 to <vscale x 4 x i8>
  %res = call <vscale x 4 x i8> @llvm.vector.segmented.shuffle.nxv4i8.v4i32(
    <vscale x 4 x i8> %leg0, <vscale x 4 x i8> %leg1, <4 x i32> <i32 3, i32 3, i32 5, i32 6>)
  %res.leg = zext <vscale x 4 x i8> %res to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %res.leg
}

define <vscale x 4 x float> @tbl2_v4f32(<vscale x 4 x float> %0, <vscale x 4 x float> %1) {
; CHECK-LABEL: tbl2_v4f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    adrp x8, .LCPI134_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI134_0
; CHECK-NEXT:    ld1rqw { z2.s }, p0/z, [x8]
; CHECK-NEXT:    movprfx z3, z2
; CHECK-NEXT:    sub z3.s, z3.s, #4 // =0x4
; CHECK-NEXT:    tblq z0.s, { z0.s }, z2.s
; CHECK-NEXT:    tbxq z0.s, z1.s, z3.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x float> @llvm.vector.segmented.shuffle.nxv4f32.v4i32(
    <vscale x 4 x float> %0, <vscale x 4 x float> %1, <4 x i32> <i32 3, i32 3, i32 5, i32 6>)
  ret <vscale x 4 x float> %res
}

define <vscale x 4 x half> @tbl2_v4f16(<vscale x 4 x half> %0, <vscale x 4 x half> %1) {
; CHECK-LABEL: tbl2_v4f16:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    adrp x8, .LCPI135_0
; CHECK-NEXT:    add x8, x8, :lo12:.LCPI135_0
; CHECK-NEXT:    ld1rqw { z2.s }, p0/z, [x8]
; CHECK-NEXT:    movprfx z3, z2
; CHECK-NEXT:    sub z3.s, z3.s, #4 // =0x4
; CHECK-NEXT:    tblq z0.s, { z0.s }, z2.s
; CHECK-NEXT:    tbxq z0.s, z1.s, z3.s
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 4 x half> @llvm.vector.segmented.shuffle.nxv4f16.v4i32(
    <vscale x 4 x half> %0, <vscale x 4 x half> %1, <4 x i32> <i32 3, i32 3, i32 5, i32 6>)
  ret <vscale x 4 x half> %res
}

define <vscale x 2 x i64> @tbl2_v2i64(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1) {
; CHECK-LABEL: tbl2_v2i64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    index z2.d, #0, #3
; CHECK-NEXT:    mov z2.q, q2
; CHECK-NEXT:    movprfx z3, z2
; CHECK-NEXT:    sub z3.d, z3.d, #2 // =0x2
; CHECK-NEXT:    tblq z0.d, { z0.d }, z2.d
; CHECK-NEXT:    tbxq z0.d, z1.d, z3.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x i64> @llvm.vector.segmented.shuffle.nxv2i64.v2i32(
    <vscale x 2 x i64> %0, <vscale x 2 x i64> %1, <2 x i32> <i32 0, i32 3>)
  ret <vscale x 2 x i64> %res
}

define <vscale x 2 x i64> @tbl2_v2i32(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1) {
; CHECK-LABEL: tbl2_v2i32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    index z1.d, #0, #3
; CHECK-NEXT:    mov z1.q, q1
; CHECK-NEXT:    movprfx z2, z1
; CHECK-NEXT:    sub z2.d, z2.d, #2 // =0x2
; CHECK-NEXT:    tblq z1.d, { z0.d }, z1.d
; CHECK-NEXT:    tbxq z1.d, z0.d, z2.d
; CHECK-NEXT:    movprfx z0, z1
; CHECK-NEXT:    and z0.d, z0.d, #0xffffffff
; CHECK-NEXT:    ret
entry:
  %leg0 = trunc <vscale x 2 x i64> %0 to <vscale x 2 x i32>
  %leg1 = trunc <vscale x 2 x i64> %0 to <vscale x 2 x i32>
  %res = call <vscale x 2 x i32> @llvm.vector.segmented.shuffle.nxv2i32.v2i32(
    <vscale x 2 x i32> %leg0, <vscale x 2 x i32> %leg1, <2 x i32> <i32 0, i32 3>)
  %res.leg = zext <vscale x 2 x i32> %res to <vscale x 2 x i64>
  ret <vscale x 2 x i64> %res.leg
}

define <vscale x 2 x double> @tbl2_v2f64(<vscale x 2 x double> %0, <vscale x 2 x double> %1) {
; CHECK-LABEL: tbl2_v2f64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    index z2.d, #0, #3
; CHECK-NEXT:    mov z2.q, q2
; CHECK-NEXT:    movprfx z3, z2
; CHECK-NEXT:    sub z3.d, z3.d, #2 // =0x2
; CHECK-NEXT:    tblq z0.d, { z0.d }, z2.d
; CHECK-NEXT:    tbxq z0.d, z1.d, z3.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x double> @llvm.vector.segmented.shuffle.nxv2f64.v2i32(
    <vscale x 2 x double> %0, <vscale x 2 x double> %1, <2 x i32> <i32 0, i32 3>)
  ret <vscale x 2 x double> %res
}

define <vscale x 2 x float> @tbl2_v2f32(<vscale x 2 x float> %0, <vscale x 2 x float> %1) {
; CHECK-LABEL: tbl2_v2f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    index z2.d, #0, #3
; CHECK-NEXT:    mov z2.q, q2
; CHECK-NEXT:    movprfx z3, z2
; CHECK-NEXT:    sub z3.d, z3.d, #2 // =0x2
; CHECK-NEXT:    tblq z0.d, { z0.d }, z2.d
; CHECK-NEXT:    tbxq z0.d, z1.d, z3.d
; CHECK-NEXT:    ret
entry:
  %res = call <vscale x 2 x float> @llvm.vector.segmented.shuffle.nxv2f32.v2i32(
    <vscale x 2 x float> %0, <vscale x 2 x float> %1, <2 x i32> <i32 0, i32 3>)
  ret <vscale x 2 x float> %res
}
