; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-linux-gnu --enable-no-signed-zeros-fp-math -mattr=+sve2p2 -aarch64-sve-vector-bits-min=256 < %s | FileCheck %s

; Check that fp -> int -> fp conversions can be
; lowered to the SVE FRINTZ instructions for
; fixed vectors.

define <8 x float> @frintz_f32_i32_f32(<8 x float> %in) {
; CHECK-LABEL: frintz_f32_i32_f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $q1 killed $q1 killed $z0_z1 def $z0_z1
; CHECK-NEXT:    ptrue p0.s, vl4
; CHECK-NEXT:    // kill: def $q0 killed $q0 killed $z0_z1 def $z0_z1
; CHECK-NEXT:    splice z0.s, p0, { z0.s, z1.s }
; CHECK-NEXT:    ptrue p0.s, vl8
; CHECK-NEXT:    frintz z0.s, p0/z, z0.s
; CHECK-NEXT:    movprfx z1, z0
; CHECK-NEXT:    ext z1.b, z1.b, z0.b, #16
; CHECK-NEXT:    // kill: def $q0 killed $q0 killed $z0
; CHECK-NEXT:    // kill: def $q1 killed $q1 killed $z1
; CHECK-NEXT:    ret
    %res = fptosi <8 x float> %in to <8 x i32>
    %res2 = sitofp <8 x i32> %res to <8 x float>
    ret <8 x float> %res2
}

define <4 x double> @frintz_f64_i32_f64(<4 x double> %in) {
; CHECK-LABEL: frintz_f64_i32_f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $q1 killed $q1 killed $z0_z1 def $z0_z1
; CHECK-NEXT:    ptrue p0.d, vl2
; CHECK-NEXT:    // kill: def $q0 killed $q0 killed $z0_z1 def $z0_z1
; CHECK-NEXT:    splice z0.d, p0, { z0.d, z1.d }
; CHECK-NEXT:    ptrue p0.d, vl4
; CHECK-NEXT:    frintz z0.d, p0/z, z0.d
; CHECK-NEXT:    movprfx z1, z0
; CHECK-NEXT:    ext z1.b, z1.b, z0.b, #16
; CHECK-NEXT:    // kill: def $q0 killed $q0 killed $z0
; CHECK-NEXT:    // kill: def $q1 killed $q1 killed $z1
; CHECK-NEXT:    ret
    %res = fptosi <4 x double> %in to <4 x i32>
    %res2 = sitofp <4 x i32> %res to <4 x double>
    ret <4 x double> %res2
}

define <4 x double> @frintz_f64_i64_f64(<4 x double> %in) {
; CHECK-LABEL: frintz_f64_i64_f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $q1 killed $q1 killed $z0_z1 def $z0_z1
; CHECK-NEXT:    ptrue p0.d, vl2
; CHECK-NEXT:    // kill: def $q0 killed $q0 killed $z0_z1 def $z0_z1
; CHECK-NEXT:    splice z0.d, p0, { z0.d, z1.d }
; CHECK-NEXT:    ptrue p0.d, vl4
; CHECK-NEXT:    frintz z0.d, p0/z, z0.d
; CHECK-NEXT:    movprfx z1, z0
; CHECK-NEXT:    ext z1.b, z1.b, z0.b, #16
; CHECK-NEXT:    // kill: def $q0 killed $q0 killed $z0
; CHECK-NEXT:    // kill: def $q1 killed $q1 killed $z1
; CHECK-NEXT:    ret
    %res = fptosi <4 x double> %in to <4 x i64>
    %res2 = sitofp <4 x i64> %res to <4 x double>
    ret <4 x double> %res2
}

define <8 x float> @frintz_f32_i64_f32(<8 x float> %in) {
; CHECK-LABEL: frintz_f32_i64_f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $q1 killed $q1 killed $z0_z1 def $z0_z1
; CHECK-NEXT:    ptrue p0.s, vl4
; CHECK-NEXT:    // kill: def $q0 killed $q0 killed $z0_z1 def $z0_z1
; CHECK-NEXT:    splice z0.s, p0, { z0.s, z1.s }
; CHECK-NEXT:    ptrue p0.s, vl8
; CHECK-NEXT:    frintz z0.s, p0/z, z0.s
; CHECK-NEXT:    movprfx z1, z0
; CHECK-NEXT:    ext z1.b, z1.b, z0.b, #16
; CHECK-NEXT:    // kill: def $q0 killed $q0 killed $z0
; CHECK-NEXT:    // kill: def $q1 killed $q1 killed $z1
; CHECK-NEXT:    ret
    %res = fptosi <8 x float> %in to <8 x i64>
    %res2 = sitofp <8 x i64> %res to <8 x float>
    ret <8 x float> %res2
}
