; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve2p1 -mattr=+sve-b16b16 -mattr=+use-experimental-zeroing-pseudos -verify-machineinstrs < %s \
; RUN: | FileCheck %s

define <vscale x 8 x bfloat> @bfadd_8_bf(<vscale x 8 x bfloat> %a, <vscale x 8 x bfloat> %b){
; CHECK-LABEL: bfadd_8_bf:
; CHECK:       // %bb.0:
; CHECK-NEXT:    bfadd z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
  %res = fadd <vscale x 8 x bfloat> %a, %b
  ret <vscale x 8 x bfloat> %res
}

define <vscale x 4 x bfloat> @bfadd_4_bf(<vscale x 4 x bfloat> %a, <vscale x 4 x bfloat> %b){
; CHECK-LABEL: bfadd_4_bf:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    bfadd z0.h, p0/m, z0.h, z1.h
; CHECK-NEXT:    ret
  %res = fadd <vscale x 4 x bfloat> %a, %b
  ret <vscale x 4 x bfloat> %res
}

define <vscale x 2 x bfloat> @bfadd_2_bf(<vscale x 2 x bfloat> %a, <vscale x 2 x bfloat> %b){
; CHECK-LABEL: bfadd_2_bf:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    bfadd z0.h, p0/m, z0.h, z1.h
; CHECK-NEXT:    ret
  %res = fadd <vscale x 2 x bfloat> %a, %b
  ret <vscale x 2 x bfloat> %res
}
