; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve,+sve2,+f8f16mm < %s | FileCheck %s --check-prefixes=CHECK

define <vscale x 8 x half> @_Z5test2u13__SVFloat16_tu13__SVMfloat8_tS0_m(<vscale x 8 x half> %acc, <vscale x 16 x i8> %a, <vscale x 16 x i8> %b, i64 %fpmr) {
; CHECK-LABEL: _Z5test2u13__SVFloat16_tu13__SVMfloat8_tS0_m:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    str x29, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-3
; CHECK-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x10, 0x92, 0x2e, 0x00, 0x48, 0x1e, 0x22 // sp + 16 + 24 * VG
; CHECK-NEXT:    .cfi_offset w29, -16
; CHECK-NEXT:    addvl x8, sp, #3
; CHECK-NEXT:    str z1, [sp, #1, mul vl]
; CHECK-NEXT:    str z0, [sp, #2, mul vl]
; CHECK-NEXT:    str z2, [sp]
; CHECK-NEXT:    str x0, [x8, #8]
; CHECK-NEXT:    msr FPMR, x0
; CHECK-NEXT:    fmmla z0.h, z1.b, z2.b
; CHECK-NEXT:    addvl sp, sp, #3
; CHECK-NEXT:    ldr x29, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
entry:
  %acc.addr = alloca <vscale x 8 x half>, align 16
  %a.addr = alloca <vscale x 16 x i8>, align 16
  %b.addr = alloca <vscale x 16 x i8>, align 16
  %fpmr.addr = alloca i64, align 8
  store <vscale x 8 x half> %acc, ptr %acc.addr, align 16
  store <vscale x 16 x i8> %a, ptr %a.addr, align 16
  store <vscale x 16 x i8> %b, ptr %b.addr, align 16
  store i64 %fpmr, ptr %fpmr.addr, align 8
  %0 = load <vscale x 8 x half>, ptr %acc.addr, align 16
  %1 = load <vscale x 16 x i8>, ptr %a.addr, align 16
  %2 = load <vscale x 16 x i8>, ptr %b.addr, align 16
  %3 = load i64, ptr %fpmr.addr, align 8
  call void @llvm.aarch64.set.fpmr(i64 %3)
  %4 = call <vscale x 8 x half> @llvm.aarch64.sve.fmmla.mf8f16(<vscale x 8 x half> %0, <vscale x 16 x i8> %1, <vscale x 16 x i8> %2)
  ret <vscale x 8 x half> %4
}

declare <vscale x 8 x half> @llvm.aarch64.sve.fmmla.mf8f16(<vscale x 8 x half>, <vscale x 16 x i8>, <vscale x 16 x i8>)
