; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-none-linux-gnu %s -o - 2>&1 | FileCheck %s --check-prefixes=CHECK,CHECK-GI

define i32 @f32(i32 %A) nounwind {
; CHECK-LABEL: f32:
; CHECK-GI:      // %bb.0:
; CHECK-GI-NEXT: ubfiz w0, w0, #3, #3
; CHECK-GI-NEXT: ret
entry:
  %tmp = call i32 @llvm.aarch64.ubfx.i32(i32 %A, i32 3, i32 3)
  ret i32 %tmp
}

define i64 @f64(i64 %A) nounwind {
; CHECK-LABEL: f64:
; CHECK-GI:      // %bb.0:
; CHECK-GI-NEXT: ubfiz x0, x0, #38, #4
; CHECK-GI-NEXT: ret
entry:
  %tmp = call i64 @llvm.aarch64.ubfx.i64(i64 %A, i64 38, i64 4)
  ret i64 %tmp
}

define i64 @f64_1(i64 %A) nounwind {
; CHECK-LABEL: f64_1:
; CHECK-GI:      // %bb.0:
; CHECK-GI-NEXT: ubfx x0, x0, #50, #3
; CHECK-GI-NEXT: ret
entry:
  %tmp = call i64 @llvm.aarch64.ubfx.i64(i64 %A, i64 14, i64 53)
  ret i64 %tmp
}

declare i32 @llvm.aarch64.ubfx.i32(i32, i32, i32)
declare i64 @llvm.aarch64.ubfx.i64(i64, i64, i64)

