; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=aarch64-linux-gnu -global-isel=0 | FileCheck %s --check-prefixes=CHECK,CHECK-SD
; RUN: llc < %s -mtriple=aarch64-linux-gnu -global-isel | FileCheck %s --check-prefixes=CHECK,CHECK-GI

define i32 @func(i32 %x, i32 %y) nounwind {
; CHECK-SD-LABEL: func:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    umull x8, w0, w1
; CHECK-SD-NEXT:    lsr x9, x8, #32
; CHECK-SD-NEXT:    extr w8, w9, w8, #2
; CHECK-SD-NEXT:    cmp w9, #3
; CHECK-SD-NEXT:    csinv w0, w8, wzr, ls
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: func:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    umull x8, w0, w1
; CHECK-GI-NEXT:    mov w9, #-1 // =0xffffffff
; CHECK-GI-NEXT:    lsr x8, x8, #2
; CHECK-GI-NEXT:    cmp x9, x8
; CHECK-GI-NEXT:    csel x0, x9, x8, lo
; CHECK-GI-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-GI-NEXT:    ret
  %tmp = call i32 @llvm.umul.fix.sat.i32(i32 %x, i32 %y, i32 2)
  ret i32 %tmp
}

define i64 @func2(i64 %x, i64 %y) nounwind {
; CHECK-SD-LABEL: func2:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    mul x8, x0, x1
; CHECK-SD-NEXT:    umulh x9, x0, x1
; CHECK-SD-NEXT:    extr x8, x9, x8, #2
; CHECK-SD-NEXT:    cmp x9, #3
; CHECK-SD-NEXT:    csinv x0, x8, xzr, ls
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: func2:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    mul x9, x0, x1
; CHECK-GI-NEXT:    mov x8, #-1 // =0xffffffffffffffff
; CHECK-GI-NEXT:    umulh x10, x0, x1
; CHECK-GI-NEXT:    extr x9, x10, x9, #2
; CHECK-GI-NEXT:    lsr x10, x10, #2
; CHECK-GI-NEXT:    cmp x8, x9
; CHECK-GI-NEXT:    cset w8, lo
; CHECK-GI-NEXT:    cmp xzr, x10
; CHECK-GI-NEXT:    cset w10, lo
; CHECK-GI-NEXT:    csel w8, w8, w10, eq
; CHECK-GI-NEXT:    tst w8, #0x1
; CHECK-GI-NEXT:    csinv x0, x9, xzr, eq
; CHECK-GI-NEXT:    ret
  %tmp = call i64 @llvm.umul.fix.sat.i64(i64 %x, i64 %y, i32 2)
  ret i64 %tmp
}

define i4 @func3(i4 %x, i4 %y) nounwind {
; CHECK-SD-LABEL: func3:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    lsl w8, w0, #28
; CHECK-SD-NEXT:    and w9, w1, #0xf
; CHECK-SD-NEXT:    umull x8, w8, w9
; CHECK-SD-NEXT:    lsr x9, x8, #32
; CHECK-SD-NEXT:    extr w8, w9, w8, #2
; CHECK-SD-NEXT:    cmp w9, #3
; CHECK-SD-NEXT:    csinv w8, w8, wzr, ls
; CHECK-SD-NEXT:    lsr w0, w8, #28
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: func3:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    and w8, w0, #0xf
; CHECK-GI-NEXT:    and w9, w1, #0xf
; CHECK-GI-NEXT:    mul w8, w8, w9
; CHECK-GI-NEXT:    mov w9, #15 // =0xf
; CHECK-GI-NEXT:    lsr w8, w8, #2
; CHECK-GI-NEXT:    cmp w9, w8
; CHECK-GI-NEXT:    csel w0, w9, w8, lo
; CHECK-GI-NEXT:    ret
  %tmp = call i4 @llvm.umul.fix.sat.i4(i4 %x, i4 %y, i32 2)
  ret i4 %tmp
}

;; These result in regular integer multiplication with a saturation check.
define i32 @func4(i32 %x, i32 %y) nounwind {
; CHECK-SD-LABEL: func4:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    umull x8, w0, w1
; CHECK-SD-NEXT:    tst x8, #0xffffffff00000000
; CHECK-SD-NEXT:    csinv w0, w8, wzr, eq
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: func4:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    umull x8, w0, w1
; CHECK-GI-NEXT:    mov w9, #-1 // =0xffffffff
; CHECK-GI-NEXT:    cmp x9, x8
; CHECK-GI-NEXT:    csel x0, x9, x8, lo
; CHECK-GI-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-GI-NEXT:    ret
  %tmp = call i32 @llvm.umul.fix.sat.i32(i32 %x, i32 %y, i32 0)
  ret i32 %tmp
}

define i64 @func5(i64 %x, i64 %y) {
; CHECK-SD-LABEL: func5:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    umulh x8, x0, x1
; CHECK-SD-NEXT:    mul x9, x0, x1
; CHECK-SD-NEXT:    cmp xzr, x8
; CHECK-SD-NEXT:    csinv x0, x9, xzr, eq
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: func5:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    mul x8, x0, x1
; CHECK-GI-NEXT:    mov x10, #-1 // =0xffffffffffffffff
; CHECK-GI-NEXT:    umulh x9, x0, x1
; CHECK-GI-NEXT:    cmp x10, x8
; CHECK-GI-NEXT:    cset w10, lo
; CHECK-GI-NEXT:    cmp xzr, x9
; CHECK-GI-NEXT:    cset w9, lo
; CHECK-GI-NEXT:    csel w9, w10, w9, eq
; CHECK-GI-NEXT:    tst w9, #0x1
; CHECK-GI-NEXT:    csinv x0, x8, xzr, eq
; CHECK-GI-NEXT:    ret
  %tmp = call i64 @llvm.umul.fix.sat.i64(i64 %x, i64 %y, i32 0)
  ret i64 %tmp
}

define i4 @func6(i4 %x, i4 %y) nounwind {
; CHECK-SD-LABEL: func6:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    lsl w8, w0, #28
; CHECK-SD-NEXT:    and w9, w1, #0xf
; CHECK-SD-NEXT:    umull x8, w8, w9
; CHECK-SD-NEXT:    tst x8, #0xffffffff00000000
; CHECK-SD-NEXT:    csinv w8, w8, wzr, eq
; CHECK-SD-NEXT:    lsr w0, w8, #28
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: func6:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    and w8, w0, #0xf
; CHECK-GI-NEXT:    and w9, w1, #0xf
; CHECK-GI-NEXT:    mul w8, w8, w9
; CHECK-GI-NEXT:    mov w9, #15 // =0xf
; CHECK-GI-NEXT:    cmp w9, w8
; CHECK-GI-NEXT:    csel w0, w9, w8, lo
; CHECK-GI-NEXT:    ret
  %tmp = call i4 @llvm.umul.fix.sat.i4(i4 %x, i4 %y, i32 0)
  ret i4 %tmp
}

define <2 x i32> @vec(<2 x i32> %x, <2 x i32> %y) nounwind {
; CHECK-SD-LABEL: vec:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-NEXT:    mov w8, v1.s[1]
; CHECK-SD-NEXT:    mov w9, v0.s[1]
; CHECK-SD-NEXT:    fmov w10, s0
; CHECK-SD-NEXT:    umull x8, w9, w8
; CHECK-SD-NEXT:    fmov w9, s1
; CHECK-SD-NEXT:    umull x9, w10, w9
; CHECK-SD-NEXT:    tst x8, #0xffffffff00000000
; CHECK-SD-NEXT:    csinv w8, w8, wzr, eq
; CHECK-SD-NEXT:    tst x9, #0xffffffff00000000
; CHECK-SD-NEXT:    csinv w9, w9, wzr, eq
; CHECK-SD-NEXT:    fmov s0, w9
; CHECK-SD-NEXT:    mov v0.s[1], w8
; CHECK-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: vec:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    umull v0.2d, v0.2s, v1.2s
; CHECK-GI-NEXT:    uqxtn v0.2s, v0.2d
; CHECK-GI-NEXT:    ret
  %tmp = call <2 x i32> @llvm.umul.fix.sat.v2i32(<2 x i32> %x, <2 x i32> %y, i32 0)
  ret <2 x i32> %tmp
}

define <4 x i32> @vec2(<4 x i32> %x, <4 x i32> %y) nounwind {
; CHECK-SD-LABEL: vec2:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    mov w8, v1.s[1]
; CHECK-SD-NEXT:    mov w9, v0.s[1]
; CHECK-SD-NEXT:    fmov w10, s0
; CHECK-SD-NEXT:    mov w11, v0.s[2]
; CHECK-SD-NEXT:    mov w13, v0.s[3]
; CHECK-SD-NEXT:    mov w12, v1.s[3]
; CHECK-SD-NEXT:    umull x8, w9, w8
; CHECK-SD-NEXT:    fmov w9, s1
; CHECK-SD-NEXT:    umull x9, w10, w9
; CHECK-SD-NEXT:    tst x8, #0xffffffff00000000
; CHECK-SD-NEXT:    mov w10, v1.s[2]
; CHECK-SD-NEXT:    csinv w8, w8, wzr, eq
; CHECK-SD-NEXT:    tst x9, #0xffffffff00000000
; CHECK-SD-NEXT:    csinv w9, w9, wzr, eq
; CHECK-SD-NEXT:    fmov s0, w9
; CHECK-SD-NEXT:    umull x9, w11, w10
; CHECK-SD-NEXT:    mov v0.s[1], w8
; CHECK-SD-NEXT:    tst x9, #0xffffffff00000000
; CHECK-SD-NEXT:    csinv w8, w9, wzr, eq
; CHECK-SD-NEXT:    umull x9, w13, w12
; CHECK-SD-NEXT:    mov v0.s[2], w8
; CHECK-SD-NEXT:    tst x9, #0xffffffff00000000
; CHECK-SD-NEXT:    csinv w8, w9, wzr, eq
; CHECK-SD-NEXT:    mov v0.s[3], w8
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: vec2:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    umull v2.2d, v0.2s, v1.2s
; CHECK-GI-NEXT:    umull2 v1.2d, v0.4s, v1.4s
; CHECK-GI-NEXT:    uqxtn v0.2s, v2.2d
; CHECK-GI-NEXT:    uqxtn2 v0.4s, v1.2d
; CHECK-GI-NEXT:    ret
  %tmp = call <4 x i32> @llvm.umul.fix.sat.v4i32(<4 x i32> %x, <4 x i32> %y, i32 0)
  ret <4 x i32> %tmp
}

define <4 x i64> @vec3(<4 x i64> %x, <4 x i64> %y) nounwind {
; CHECK-SD-LABEL: vec3:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    mov x8, v2.d[1]
; CHECK-SD-NEXT:    mov x9, v0.d[1]
; CHECK-SD-NEXT:    mov x14, v3.d[1]
; CHECK-SD-NEXT:    mov x15, v1.d[1]
; CHECK-SD-NEXT:    fmov x10, d2
; CHECK-SD-NEXT:    fmov x11, d0
; CHECK-SD-NEXT:    mul x12, x11, x10
; CHECK-SD-NEXT:    mul x13, x9, x8
; CHECK-SD-NEXT:    umulh x8, x9, x8
; CHECK-SD-NEXT:    umulh x9, x11, x10
; CHECK-SD-NEXT:    mul x10, x15, x14
; CHECK-SD-NEXT:    extr x13, x8, x13, #32
; CHECK-SD-NEXT:    umulh x11, x15, x14
; CHECK-SD-NEXT:    fmov x14, d3
; CHECK-SD-NEXT:    fmov x15, d1
; CHECK-SD-NEXT:    mul x16, x15, x14
; CHECK-SD-NEXT:    umulh x14, x15, x14
; CHECK-SD-NEXT:    mov w15, #-1 // =0xffffffff
; CHECK-SD-NEXT:    cmp x8, x15
; CHECK-SD-NEXT:    extr x8, x9, x12, #32
; CHECK-SD-NEXT:    csinv x12, x13, xzr, ls
; CHECK-SD-NEXT:    cmp x9, x15
; CHECK-SD-NEXT:    extr x9, x11, x10, #32
; CHECK-SD-NEXT:    csinv x8, x8, xzr, ls
; CHECK-SD-NEXT:    cmp x11, x15
; CHECK-SD-NEXT:    csinv x9, x9, xzr, ls
; CHECK-SD-NEXT:    fmov d0, x8
; CHECK-SD-NEXT:    extr x10, x14, x16, #32
; CHECK-SD-NEXT:    cmp x14, x15
; CHECK-SD-NEXT:    csinv x10, x10, xzr, ls
; CHECK-SD-NEXT:    mov v0.d[1], x12
; CHECK-SD-NEXT:    fmov d1, x10
; CHECK-SD-NEXT:    mov v1.d[1], x9
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: vec3:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    mov d4, v0.d[1]
; CHECK-GI-NEXT:    mov d5, v2.d[1]
; CHECK-GI-NEXT:    mov x16, #-1 // =0xffffffffffffffff
; CHECK-GI-NEXT:    fmov x8, d0
; CHECK-GI-NEXT:    fmov x9, d2
; CHECK-GI-NEXT:    mov d0, v1.d[1]
; CHECK-GI-NEXT:    mov d2, v3.d[1]
; CHECK-GI-NEXT:    fmov x13, d3
; CHECK-GI-NEXT:    mul x10, x8, x9
; CHECK-GI-NEXT:    fmov x11, d5
; CHECK-GI-NEXT:    fmov x15, d0
; CHECK-GI-NEXT:    umulh x8, x8, x9
; CHECK-GI-NEXT:    fmov x9, d4
; CHECK-GI-NEXT:    mul x12, x9, x11
; CHECK-GI-NEXT:    umulh x9, x9, x11
; CHECK-GI-NEXT:    fmov x11, d1
; CHECK-GI-NEXT:    extr x10, x8, x10, #32
; CHECK-GI-NEXT:    lsr x8, x8, #32
; CHECK-GI-NEXT:    cmp x16, x10
; CHECK-GI-NEXT:    mul x14, x11, x13
; CHECK-GI-NEXT:    cset w18, lo
; CHECK-GI-NEXT:    cmp xzr, x8
; CHECK-GI-NEXT:    umulh x11, x11, x13
; CHECK-GI-NEXT:    fmov x13, d2
; CHECK-GI-NEXT:    extr x8, x9, x12, #32
; CHECK-GI-NEXT:    lsr x9, x9, #32
; CHECK-GI-NEXT:    mul x17, x15, x13
; CHECK-GI-NEXT:    umulh x12, x15, x13
; CHECK-GI-NEXT:    cset w13, lo
; CHECK-GI-NEXT:    extr x14, x11, x14, #32
; CHECK-GI-NEXT:    csel w13, w18, w13, eq
; CHECK-GI-NEXT:    cmp x16, x8
; CHECK-GI-NEXT:    cset w15, lo
; CHECK-GI-NEXT:    cmp xzr, x9
; CHECK-GI-NEXT:    lsr x9, x11, #32
; CHECK-GI-NEXT:    cset w11, lo
; CHECK-GI-NEXT:    csel w11, w15, w11, eq
; CHECK-GI-NEXT:    cmp x16, x14
; CHECK-GI-NEXT:    extr x15, x12, x17, #32
; CHECK-GI-NEXT:    cset w17, lo
; CHECK-GI-NEXT:    cmp xzr, x9
; CHECK-GI-NEXT:    lsr x9, x12, #32
; CHECK-GI-NEXT:    cset w12, lo
; CHECK-GI-NEXT:    csel w12, w17, w12, eq
; CHECK-GI-NEXT:    cmp x16, x15
; CHECK-GI-NEXT:    cset w16, lo
; CHECK-GI-NEXT:    cmp xzr, x9
; CHECK-GI-NEXT:    cset w9, lo
; CHECK-GI-NEXT:    csel w9, w16, w9, eq
; CHECK-GI-NEXT:    tst w13, #0x1
; CHECK-GI-NEXT:    csinv x10, x10, xzr, eq
; CHECK-GI-NEXT:    tst w11, #0x1
; CHECK-GI-NEXT:    csinv x8, x8, xzr, eq
; CHECK-GI-NEXT:    tst w12, #0x1
; CHECK-GI-NEXT:    fmov d0, x10
; CHECK-GI-NEXT:    csinv x11, x14, xzr, eq
; CHECK-GI-NEXT:    tst w9, #0x1
; CHECK-GI-NEXT:    fmov d1, x11
; CHECK-GI-NEXT:    csinv x9, x15, xzr, eq
; CHECK-GI-NEXT:    mov v0.d[1], x8
; CHECK-GI-NEXT:    mov v1.d[1], x9
; CHECK-GI-NEXT:    ret
  %tmp = call <4 x i64> @llvm.umul.fix.sat.v4i64(<4 x i64> %x, <4 x i64> %y, i32 32)
  ret <4 x i64> %tmp
}

define i64 @func7(i64 %x, i64 %y) nounwind {
; CHECK-SD-LABEL: func7:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    mul x9, x0, x1
; CHECK-SD-NEXT:    mov w8, #-1 // =0xffffffff
; CHECK-SD-NEXT:    umulh x10, x0, x1
; CHECK-SD-NEXT:    extr x9, x10, x9, #32
; CHECK-SD-NEXT:    cmp x10, x8
; CHECK-SD-NEXT:    csinv x0, x9, xzr, ls
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: func7:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    mul x9, x0, x1
; CHECK-GI-NEXT:    mov x8, #-1 // =0xffffffffffffffff
; CHECK-GI-NEXT:    umulh x10, x0, x1
; CHECK-GI-NEXT:    extr x9, x10, x9, #32
; CHECK-GI-NEXT:    lsr x10, x10, #32
; CHECK-GI-NEXT:    cmp x8, x9
; CHECK-GI-NEXT:    cset w8, lo
; CHECK-GI-NEXT:    cmp xzr, x10
; CHECK-GI-NEXT:    cset w10, lo
; CHECK-GI-NEXT:    csel w8, w8, w10, eq
; CHECK-GI-NEXT:    tst w8, #0x1
; CHECK-GI-NEXT:    csinv x0, x9, xzr, eq
; CHECK-GI-NEXT:    ret
  %tmp = call i64 @llvm.umul.fix.sat.i64(i64 %x, i64 %y, i32 32)
  ret i64 %tmp
}

define i64 @func8(i64 %x, i64 %y) nounwind {
; CHECK-SD-LABEL: func8:
; CHECK-SD:       // %bb.0:
; CHECK-SD-NEXT:    mul x9, x0, x1
; CHECK-SD-NEXT:    mov x8, #9223372036854775807 // =0x7fffffffffffffff
; CHECK-SD-NEXT:    umulh x10, x0, x1
; CHECK-SD-NEXT:    extr x9, x10, x9, #63
; CHECK-SD-NEXT:    cmp x10, x8
; CHECK-SD-NEXT:    csinv x0, x9, xzr, ls
; CHECK-SD-NEXT:    ret
;
; CHECK-GI-LABEL: func8:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    mul x9, x0, x1
; CHECK-GI-NEXT:    mov x8, #-1 // =0xffffffffffffffff
; CHECK-GI-NEXT:    umulh x10, x0, x1
; CHECK-GI-NEXT:    extr x9, x10, x9, #63
; CHECK-GI-NEXT:    lsr x10, x10, #63
; CHECK-GI-NEXT:    cmp x8, x9
; CHECK-GI-NEXT:    cset w8, lo
; CHECK-GI-NEXT:    cmp xzr, x10
; CHECK-GI-NEXT:    cset w10, lo
; CHECK-GI-NEXT:    csel w8, w8, w10, eq
; CHECK-GI-NEXT:    tst w8, #0x1
; CHECK-GI-NEXT:    csinv x0, x9, xzr, eq
; CHECK-GI-NEXT:    ret
  %tmp = call i64 @llvm.umul.fix.sat.i64(i64 %x, i64 %y, i32 63)
  ret i64 %tmp
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
