; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 %s -o - | FileCheck %s

define void @convert_v3f32() {
; CHECK-LABEL: convert_v3f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    sub sp, sp, #16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    str wzr, [sp, #12]
; CHECK-NEXT:    ldr s0, [sp, #12]
; CHECK-NEXT:    strb wzr, [x8]
; CHECK-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-NEXT:    str h0, [x8]
; CHECK-NEXT:    add sp, sp, #16
; CHECK-NEXT:    ret
entry:
  br label %bb

bb:
  %0 = shufflevector <4 x float> zeroinitializer, <4 x float> undef, <3 x i32> <i32 0, i32 1, i32 2>
  %1 = fmul reassoc nnan ninf nsz contract afn <3 x float> %0, <float 2.550000e+02, float 2.550000e+02, float 2.550000e+02>
  %2 = fptoui <3 x float> %1 to <3 x i8>
  %3 = bitcast ptr undef to ptr
  store <3 x i8> %2, ptr %3, align 1
  ret void
}
