; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 < %s | FileCheck %s

define <4 x i32> @dup_trunc_sext_v4i32(<4 x i32> %a, <4 x i32> %b, <4 x i32> %x, <4 x i32> %y) {
; CHECK-LABEL: dup_trunc_sext_v4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmgt v0.4s, v1.4s, v0.4s
; CHECK-NEXT:    dup v0.4s, v0.s[2]
; CHECK-NEXT:    bsl v0.16b, v2.16b, v3.16b
; CHECK-NEXT:    ret
  %cmp = icmp slt <4 x i32> %a, %b
  %splat = shufflevector <4 x i1> %cmp, <4 x i1> poison, <4 x i32> <i32 2, i32 2, i32 2, i32 2>
  %sel = select <4 x i1> %splat, <4 x i32> %x, <4 x i32> %y
  ret <4 x i32> %sel
}

define <2 x i64> @dup_trunc_sext_v2i64(<2 x i64> %a, <2 x i64> %b, <2 x i64> %x, <2 x i64> %y) {
; CHECK-LABEL: dup_trunc_sext_v2i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmgt v0.2d, v1.2d, v0.2d
; CHECK-NEXT:    dup v0.2d, v0.d[0]
; CHECK-NEXT:    bsl v0.16b, v2.16b, v3.16b
; CHECK-NEXT:    ret
  %cmp = icmp slt <2 x i64> %a, %b
  %splat = shufflevector <2 x i1> %cmp, <2 x i1> poison, <2 x i32> <i32 0, i32 0>
  %sel = select <2 x i1> %splat, <2 x i64> %x, <2 x i64> %y
  ret <2 x i64> %sel
}

define <4 x float> @dup_trunc_sext_v4f32(<4 x float> %a, <4 x float> %b, <4 x float> %x, <4 x float> %y) {
; CHECK-LABEL: dup_trunc_sext_v4f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcmge v0.4s, v1.4s, v0.4s
; CHECK-NEXT:    dup v0.4s, v0.s[3]
; CHECK-NEXT:    bsl v0.16b, v2.16b, v3.16b
; CHECK-NEXT:    ret
  %cmp = fcmp ole <4 x float> %a, %b
  %splat = shufflevector <4 x i1> %cmp, <4 x i1> poison, <4 x i32> <i32 3, i32 3, i32 3, i32 3>
  %sel = select <4 x i1> %splat, <4 x float> %x, <4 x float> %y
  ret <4 x float> %sel
}

define <2 x double> @dup_trunc_sext_v2f64(<2 x double> %a, <2 x double> %b, <2 x double> %x, <2 x double> %y) {
; CHECK-LABEL: dup_trunc_sext_v2f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcmge v0.2d, v1.2d, v0.2d
; CHECK-NEXT:    dup v0.2d, v0.d[1]
; CHECK-NEXT:    bsl v0.16b, v2.16b, v3.16b
; CHECK-NEXT:    ret
  %cmp = fcmp ole <2 x double> %a, %b
  %splat = shufflevector <2 x i1> %cmp, <2 x i1> poison, <2 x i32> <i32 1, i32 1>
  %sel = select <2 x i1> %splat, <2 x double> %x, <2 x double> %y
  ret <2 x double> %sel
}

define <4 x i32> @dup_trunc_sext_v4i32_idx0(<4 x i32> %a, <4 x i32> %b, <4 x i32> %x, <4 x i32> %y) {
; CHECK-LABEL: dup_trunc_sext_v4i32_idx0:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmgt v0.4s, v1.4s, v0.4s
; CHECK-NEXT:    dup v0.4s, v0.s[0]
; CHECK-NEXT:    bsl v0.16b, v2.16b, v3.16b
; CHECK-NEXT:    ret
  %cmp = icmp slt <4 x i32> %a, %b
  %splat = shufflevector <4 x i1> %cmp, <4 x i1> poison, <4 x i32> zeroinitializer
  %sel = select <4 x i1> %splat, <4 x i32> %x, <4 x i32> %y
  ret <4 x i32> %sel
}

define <2 x i32> @dup_trunc_sext_v2i32(<2 x i32> %a, <2 x i32> %b, <2 x i32> %x, <2 x i32> %y) {
; CHECK-LABEL: dup_trunc_sext_v2i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmgt v0.2s, v1.2s, v0.2s
; CHECK-NEXT:    dup v0.2s, v0.s[1]
; CHECK-NEXT:    bsl v0.8b, v2.8b, v3.8b
; CHECK-NEXT:    ret
  %cmp = icmp slt <2 x i32> %a, %b
  %splat = shufflevector <2 x i1> %cmp, <2 x i1> poison, <2 x i32> <i32 1, i32 1>
  %sel = select <2 x i1> %splat, <2 x i32> %x, <2 x i32> %y
  ret <2 x i32> %sel
}

define <8 x i16> @dup_trunc_sext_v8i16(<8 x i16> %a, <8 x i16> %b, <8 x i16> %x, <8 x i16> %y) {
; CHECK-LABEL: dup_trunc_sext_v8i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmgt v0.8h, v1.8h, v0.8h
; CHECK-NEXT:    dup v0.8h, v0.h[2]
; CHECK-NEXT:    bsl v0.16b, v2.16b, v3.16b
; CHECK-NEXT:    ret
  %cmp = icmp slt <8 x i16> %a, %b
  %splat = shufflevector <8 x i1> %cmp, <8 x i1> poison, <8 x i32> <i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2>
  %sel = select <8 x i1> %splat, <8 x i16> %x, <8 x i16> %y
  ret <8 x i16> %sel
}

define <4 x i32> @negative_arbitrary_input(<4 x i32> %mask, <4 x i32> %x, <4 x i32> %y) {
; CHECK-LABEL: negative_arbitrary_input:
; CHECK:       // %bb.0:
; CHECK-NEXT:    xtn v0.4h, v0.4s
; CHECK-NEXT:    dup v0.4h, v0.h[2]
; CHECK-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-NEXT:    shl v0.4s, v0.4s, #31
; CHECK-NEXT:    cmlt v0.4s, v0.4s, #0
; CHECK-NEXT:    bsl v0.16b, v1.16b, v2.16b
; CHECK-NEXT:    ret
  %trunc = trunc <4 x i32> %mask to <4 x i1>
  %splat = shufflevector <4 x i1> %trunc, <4 x i1> poison, <4 x i32> <i32 2, i32 2, i32 2, i32 2>
  %sel = select <4 x i1> %splat, <4 x i32> %x, <4 x i32> %y
  ret <4 x i32> %sel
}
