; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,CHECK-LE
; RUN: llc -mtriple=aarch64_be -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,CHECK-BE

; Bitmasks (bitcast <N x i1> to iN) from masks legalized out of >128-bit
; sources. These all lower by narrowing the per-lane width until the mask fits
; a 128-bit vector (the lane count, and so the bitmask, is unchanged), then
; reusing the register-only compare->bitmask lowering. None of them may touch
; the stack: the old lowering bailed here and fell into the generic
; bitcast-through-memory legalization, leaving behind a dead frame.

; 256-bit source, 4 lanes: narrowed <4 x i64> -> <4 x i32>.
define i4 @bitmask_v4i64(<4 x i64> %v) {
; CHECK-LE-LABEL: bitmask_v4i64:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    cmeq v1.2d, v1.2d, #0
; CHECK-LE-NEXT:    cmeq v0.2d, v0.2d, #0
; CHECK-LE-NEXT:    adrp x8, .LCPI0_0
; CHECK-LE-NEXT:    uzp1 v0.4s, v0.4s, v1.4s
; CHECK-LE-NEXT:    ldr q1, [x8, :lo12:.LCPI0_0]
; CHECK-LE-NEXT:    bic v0.16b, v1.16b, v0.16b
; CHECK-LE-NEXT:    addv s0, v0.4s
; CHECK-LE-NEXT:    fmov w0, s0
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: bitmask_v4i64:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-NEXT:    adrp x8, .LCPI0_0
; CHECK-BE-NEXT:    add x8, x8, :lo12:.LCPI0_0
; CHECK-BE-NEXT:    cmeq v1.2d, v1.2d, #0
; CHECK-BE-NEXT:    cmeq v0.2d, v0.2d, #0
; CHECK-BE-NEXT:    uzp1 v0.4s, v0.4s, v1.4s
; CHECK-BE-NEXT:    ld1 { v1.4s }, [x8]
; CHECK-BE-NEXT:    bic v0.16b, v1.16b, v0.16b
; CHECK-BE-NEXT:    addv s0, v0.4s
; CHECK-BE-NEXT:    fmov w0, s0
; CHECK-BE-NEXT:    ret
  %c = icmp ne <4 x i64> %v, zeroinitializer
  %b = bitcast <4 x i1> %c to i4
  ret i4 %b
}

; 256-bit source, 8 lanes: narrowed <8 x i32> -> <8 x i16>.
define i8 @bitmask_v8i32(<8 x i32> %v) {
; CHECK-LE-LABEL: bitmask_v8i32:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    cmeq v1.4s, v1.4s, #0
; CHECK-LE-NEXT:    cmeq v0.4s, v0.4s, #0
; CHECK-LE-NEXT:    adrp x8, .LCPI1_0
; CHECK-LE-NEXT:    uzp1 v0.8h, v0.8h, v1.8h
; CHECK-LE-NEXT:    ldr q1, [x8, :lo12:.LCPI1_0]
; CHECK-LE-NEXT:    bic v0.16b, v1.16b, v0.16b
; CHECK-LE-NEXT:    addv h0, v0.8h
; CHECK-LE-NEXT:    fmov w0, s0
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: bitmask_v8i32:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-NEXT:    adrp x8, .LCPI1_0
; CHECK-BE-NEXT:    add x8, x8, :lo12:.LCPI1_0
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-NEXT:    cmeq v1.4s, v1.4s, #0
; CHECK-BE-NEXT:    cmeq v0.4s, v0.4s, #0
; CHECK-BE-NEXT:    uzp1 v0.8h, v0.8h, v1.8h
; CHECK-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-BE-NEXT:    bic v0.16b, v1.16b, v0.16b
; CHECK-BE-NEXT:    addv h0, v0.8h
; CHECK-BE-NEXT:    fmov w0, s0
; CHECK-BE-NEXT:    ret
  %c = icmp ne <8 x i32> %v, zeroinitializer
  %b = bitcast <8 x i1> %c to i8
  ret i8 %b
}

; 512-bit source, 8 lanes: narrowed <8 x i64> -> <8 x i16>.
define i8 @bitmask_v8i64(<8 x i64> %v) {
; CHECK-LE-LABEL: bitmask_v8i64:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    cmeq v3.2d, v3.2d, #0
; CHECK-LE-NEXT:    cmeq v2.2d, v2.2d, #0
; CHECK-LE-NEXT:    adrp x8, .LCPI2_0
; CHECK-LE-NEXT:    cmeq v1.2d, v1.2d, #0
; CHECK-LE-NEXT:    cmeq v0.2d, v0.2d, #0
; CHECK-LE-NEXT:    uzp1 v2.4s, v2.4s, v3.4s
; CHECK-LE-NEXT:    uzp1 v0.4s, v0.4s, v1.4s
; CHECK-LE-NEXT:    ldr q1, [x8, :lo12:.LCPI2_0]
; CHECK-LE-NEXT:    uzp1 v0.8h, v0.8h, v2.8h
; CHECK-LE-NEXT:    bic v0.16b, v1.16b, v0.16b
; CHECK-LE-NEXT:    addv h0, v0.8h
; CHECK-LE-NEXT:    fmov w0, s0
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: bitmask_v8i64:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ext v3.16b, v3.16b, v3.16b, #8
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    adrp x8, .LCPI2_0
; CHECK-BE-NEXT:    add x8, x8, :lo12:.LCPI2_0
; CHECK-BE-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-NEXT:    ext v2.16b, v2.16b, v2.16b, #8
; CHECK-BE-NEXT:    cmeq v3.2d, v3.2d, #0
; CHECK-BE-NEXT:    cmeq v0.2d, v0.2d, #0
; CHECK-BE-NEXT:    cmeq v2.2d, v2.2d, #0
; CHECK-BE-NEXT:    cmeq v1.2d, v1.2d, #0
; CHECK-BE-NEXT:    uzp1 v2.4s, v2.4s, v3.4s
; CHECK-BE-NEXT:    uzp1 v0.4s, v0.4s, v1.4s
; CHECK-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-BE-NEXT:    uzp1 v0.8h, v0.8h, v2.8h
; CHECK-BE-NEXT:    bic v0.16b, v1.16b, v0.16b
; CHECK-BE-NEXT:    addv h0, v0.8h
; CHECK-BE-NEXT:    fmov w0, s0
; CHECK-BE-NEXT:    ret
  %c = icmp ne <8 x i64> %v, zeroinitializer
  %b = bitcast <8 x i1> %c to i8
  ret i8 %b
}

; 512-bit source, 16 lanes: narrowed <16 x i32> -> <16 x i8>.
define i16 @bitmask_v16i32(<16 x i32> %v) {
; CHECK-LE-LABEL: bitmask_v16i32:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    cmeq v3.4s, v3.4s, #0
; CHECK-LE-NEXT:    cmeq v2.4s, v2.4s, #0
; CHECK-LE-NEXT:    adrp x8, .LCPI3_0
; CHECK-LE-NEXT:    cmeq v1.4s, v1.4s, #0
; CHECK-LE-NEXT:    cmeq v0.4s, v0.4s, #0
; CHECK-LE-NEXT:    uzp1 v2.8h, v2.8h, v3.8h
; CHECK-LE-NEXT:    uzp1 v0.8h, v0.8h, v1.8h
; CHECK-LE-NEXT:    ldr q1, [x8, :lo12:.LCPI3_0]
; CHECK-LE-NEXT:    uzp1 v0.16b, v0.16b, v2.16b
; CHECK-LE-NEXT:    bic v0.16b, v1.16b, v0.16b
; CHECK-LE-NEXT:    addp v0.16b, v0.16b, v0.16b
; CHECK-LE-NEXT:    addp v0.16b, v0.16b, v0.16b
; CHECK-LE-NEXT:    addp v0.16b, v0.16b, v0.16b
; CHECK-LE-NEXT:    umov w0, v0.h[0]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: bitmask_v16i32:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    rev64 v3.4s, v3.4s
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    adrp x8, .LCPI3_0
; CHECK-BE-NEXT:    add x8, x8, :lo12:.LCPI3_0
; CHECK-BE-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-NEXT:    rev64 v2.4s, v2.4s
; CHECK-BE-NEXT:    ext v3.16b, v3.16b, v3.16b, #8
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-NEXT:    ext v2.16b, v2.16b, v2.16b, #8
; CHECK-BE-NEXT:    cmeq v3.4s, v3.4s, #0
; CHECK-BE-NEXT:    cmeq v0.4s, v0.4s, #0
; CHECK-BE-NEXT:    cmeq v2.4s, v2.4s, #0
; CHECK-BE-NEXT:    cmeq v1.4s, v1.4s, #0
; CHECK-BE-NEXT:    uzp1 v2.8h, v2.8h, v3.8h
; CHECK-BE-NEXT:    uzp1 v0.8h, v0.8h, v1.8h
; CHECK-BE-NEXT:    ld1 { v1.16b }, [x8]
; CHECK-BE-NEXT:    uzp1 v0.16b, v0.16b, v2.16b
; CHECK-BE-NEXT:    bic v0.16b, v1.16b, v0.16b
; CHECK-BE-NEXT:    addp v0.16b, v0.16b, v0.16b
; CHECK-BE-NEXT:    addp v0.16b, v0.16b, v0.16b
; CHECK-BE-NEXT:    addp v0.16b, v0.16b, v0.16b
; CHECK-BE-NEXT:    rev16 v0.16b, v0.16b
; CHECK-BE-NEXT:    umov w0, v0.h[0]
; CHECK-BE-NEXT:    ret
  %c = icmp ne <16 x i32> %v, zeroinitializer
  %b = bitcast <16 x i1> %c to i16
  ret i16 %b
}

; 1024-bit source, 16 lanes: narrowed <16 x i64> -> <16 x i8> (maximum
; narrowing ratio: 8x).
define i16 @bitmask_v16i64(<16 x i64> %v) {
; CHECK-LE-LABEL: bitmask_v16i64:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    cmeq v7.2d, v7.2d, #0
; CHECK-LE-NEXT:    cmeq v6.2d, v6.2d, #0
; CHECK-LE-NEXT:    adrp x8, .LCPI4_0
; CHECK-LE-NEXT:    cmeq v5.2d, v5.2d, #0
; CHECK-LE-NEXT:    cmeq v4.2d, v4.2d, #0
; CHECK-LE-NEXT:    cmeq v3.2d, v3.2d, #0
; CHECK-LE-NEXT:    cmeq v2.2d, v2.2d, #0
; CHECK-LE-NEXT:    cmeq v1.2d, v1.2d, #0
; CHECK-LE-NEXT:    cmeq v0.2d, v0.2d, #0
; CHECK-LE-NEXT:    uzp1 v6.4s, v6.4s, v7.4s
; CHECK-LE-NEXT:    uzp1 v4.4s, v4.4s, v5.4s
; CHECK-LE-NEXT:    uzp1 v2.4s, v2.4s, v3.4s
; CHECK-LE-NEXT:    uzp1 v0.4s, v0.4s, v1.4s
; CHECK-LE-NEXT:    uzp1 v1.8h, v4.8h, v6.8h
; CHECK-LE-NEXT:    uzp1 v0.8h, v0.8h, v2.8h
; CHECK-LE-NEXT:    mvn v1.16b, v1.16b
; CHECK-LE-NEXT:    mvn v0.16b, v0.16b
; CHECK-LE-NEXT:    uzp1 v0.16b, v0.16b, v1.16b
; CHECK-LE-NEXT:    ldr q1, [x8, :lo12:.LCPI4_0]
; CHECK-LE-NEXT:    shl v0.16b, v0.16b, #7
; CHECK-LE-NEXT:    cmlt v0.16b, v0.16b, #0
; CHECK-LE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-LE-NEXT:    addp v0.16b, v0.16b, v0.16b
; CHECK-LE-NEXT:    addp v0.16b, v0.16b, v0.16b
; CHECK-LE-NEXT:    addp v0.16b, v0.16b, v0.16b
; CHECK-LE-NEXT:    umov w0, v0.h[0]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: bitmask_v16i64:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ext v6.16b, v6.16b, v6.16b, #8
; CHECK-BE-NEXT:    ext v7.16b, v7.16b, v7.16b, #8
; CHECK-BE-NEXT:    adrp x8, .LCPI4_0
; CHECK-BE-NEXT:    add x8, x8, :lo12:.LCPI4_0
; CHECK-BE-NEXT:    ext v3.16b, v3.16b, v3.16b, #8
; CHECK-BE-NEXT:    ext v4.16b, v4.16b, v4.16b, #8
; CHECK-BE-NEXT:    ext v5.16b, v5.16b, v5.16b, #8
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-NEXT:    ext v2.16b, v2.16b, v2.16b, #8
; CHECK-BE-NEXT:    cmeq v7.2d, v7.2d, #0
; CHECK-BE-NEXT:    cmeq v6.2d, v6.2d, #0
; CHECK-BE-NEXT:    cmeq v4.2d, v4.2d, #0
; CHECK-BE-NEXT:    cmeq v3.2d, v3.2d, #0
; CHECK-BE-NEXT:    cmeq v5.2d, v5.2d, #0
; CHECK-BE-NEXT:    cmeq v1.2d, v1.2d, #0
; CHECK-BE-NEXT:    cmeq v0.2d, v0.2d, #0
; CHECK-BE-NEXT:    cmeq v2.2d, v2.2d, #0
; CHECK-BE-NEXT:    uzp1 v6.4s, v6.4s, v7.4s
; CHECK-BE-NEXT:    uzp1 v4.4s, v4.4s, v5.4s
; CHECK-BE-NEXT:    uzp1 v0.4s, v0.4s, v1.4s
; CHECK-BE-NEXT:    uzp1 v2.4s, v2.4s, v3.4s
; CHECK-BE-NEXT:    uzp1 v1.8h, v4.8h, v6.8h
; CHECK-BE-NEXT:    uzp1 v0.8h, v0.8h, v2.8h
; CHECK-BE-NEXT:    mvn v1.16b, v1.16b
; CHECK-BE-NEXT:    mvn v0.16b, v0.16b
; CHECK-BE-NEXT:    uzp1 v0.16b, v0.16b, v1.16b
; CHECK-BE-NEXT:    ld1 { v1.16b }, [x8]
; CHECK-BE-NEXT:    shl v0.16b, v0.16b, #7
; CHECK-BE-NEXT:    cmlt v0.16b, v0.16b, #0
; CHECK-BE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-BE-NEXT:    addp v0.16b, v0.16b, v0.16b
; CHECK-BE-NEXT:    addp v0.16b, v0.16b, v0.16b
; CHECK-BE-NEXT:    addp v0.16b, v0.16b, v0.16b
; CHECK-BE-NEXT:    rev16 v0.16b, v0.16b
; CHECK-BE-NEXT:    umov w0, v0.h[0]
; CHECK-BE-NEXT:    ret
  %c = icmp ne <16 x i64> %v, zeroinitializer
  %b = bitcast <16 x i1> %c to i16
  ret i16 %b
}

; Float compares from a wide source take the same path.
define i8 @bitmask_v8f32(<8 x float> %a, <8 x float> %b) {
; CHECK-LE-LABEL: bitmask_v8f32:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    fcmeq v1.4s, v1.4s, v3.4s
; CHECK-LE-NEXT:    fcmeq v0.4s, v0.4s, v2.4s
; CHECK-LE-NEXT:    adrp x8, .LCPI5_0
; CHECK-LE-NEXT:    uzp1 v0.8h, v0.8h, v1.8h
; CHECK-LE-NEXT:    ldr q1, [x8, :lo12:.LCPI5_0]
; CHECK-LE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-LE-NEXT:    addv h0, v0.8h
; CHECK-LE-NEXT:    fmov w0, s0
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: bitmask_v8f32:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    rev64 v2.4s, v2.4s
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    adrp x8, .LCPI5_0
; CHECK-BE-NEXT:    add x8, x8, :lo12:.LCPI5_0
; CHECK-BE-NEXT:    rev64 v3.4s, v3.4s
; CHECK-BE-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-NEXT:    ext v2.16b, v2.16b, v2.16b, #8
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    ext v3.16b, v3.16b, v3.16b, #8
; CHECK-BE-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-NEXT:    fcmeq v0.4s, v0.4s, v2.4s
; CHECK-BE-NEXT:    fcmeq v1.4s, v1.4s, v3.4s
; CHECK-BE-NEXT:    uzp1 v0.8h, v0.8h, v1.8h
; CHECK-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-BE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-BE-NEXT:    addv h0, v0.8h
; CHECK-BE-NEXT:    fmov w0, s0
; CHECK-BE-NEXT:    ret
  %c = fcmp oeq <8 x float> %a, %b
  %m = bitcast <8 x i1> %c to i8
  ret i8 %m
}

; With SVE the wide compare stays in a predicate; the bitmask is still built
; register-only (predicate -> Z register -> narrow -> weights+reduce).
; TODO: a predicated UADDV over the weight vector would shorten this further.
define i8 @bitmask_v8i32_sve(<8 x i32> %v) vscale_range(2,2) "target-features"="+sve" {
; CHECK-LE-LABEL: bitmask_v8i32_sve:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    ptrue p0.s, vl4
; CHECK-LE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-LE-NEXT:    // kill: def $q1 killed $q1 def $z1
; CHECK-LE-NEXT:    adrp x8, .LCPI6_0
; CHECK-LE-NEXT:    splice z0.s, p0, z0.s, z1.s
; CHECK-LE-NEXT:    ptrue p0.s
; CHECK-LE-NEXT:    ldr q1, [x8, :lo12:.LCPI6_0]
; CHECK-LE-NEXT:    cmpne p1.s, p0/z, z0.s, #0
; CHECK-LE-NEXT:    mov z0.s, p1/z, #-1 // =0xffffffffffffffff
; CHECK-LE-NEXT:    uzp1 z0.h, z0.h, z0.h
; CHECK-LE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-LE-NEXT:    addv h0, v0.8h
; CHECK-LE-NEXT:    fmov w0, s0
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: bitmask_v8i32_sve:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    adrp x8, .LCPI6_0
; CHECK-BE-NEXT:    add x8, x8, :lo12:.LCPI6_0
; CHECK-BE-NEXT:    ptrue p0.s, vl4
; CHECK-BE-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    splice z0.s, p0, z0.s, z1.s
; CHECK-BE-NEXT:    ptrue p0.s
; CHECK-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-BE-NEXT:    cmpne p1.s, p0/z, z0.s, #0
; CHECK-BE-NEXT:    mov z0.s, p1/z, #-1 // =0xffffffffffffffff
; CHECK-BE-NEXT:    revb z0.s, p0/m, z0.s
; CHECK-BE-NEXT:    ptrue p0.h
; CHECK-BE-NEXT:    revb z0.h, p0/m, z0.h
; CHECK-BE-NEXT:    uzp1 z0.h, z0.h, z0.h
; CHECK-BE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-BE-NEXT:    addv h0, v0.8h
; CHECK-BE-NEXT:    fmov w0, s0
; CHECK-BE-NEXT:    ret
  %c = icmp ne <8 x i32> %v, zeroinitializer
  %b = bitcast <8 x i1> %c to i8
  ret i8 %b
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
