; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=aarch64-unknown-linux-gnu -O0 | FileCheck %s -check-prefix=O0
; RUN: llc < %s -mtriple=aarch64-unknown-linux-gnu -O1 | FileCheck %s -check-prefix=O1

declare float @llvm.vector.reduce.fdot.v4f32(float, <4 x float>, <4 x float>)
declare double @llvm.vector.reduce.fdot.v4f64(double, <4 x double>, <4 x double>)

define float @fdot_f32(float %acc, <4 x float> %a, <4 x float> %b) {
; O0-LABEL: fdot_f32:
; O0:       // %bb.0:
; O0-NEXT:    mov v5.16b, v1.16b
; O0-NEXT:    mov s1, v5.s[3]
; O0-NEXT:    mov s3, v5.s[2]
; O0-NEXT:    mov s4, v5.s[1]
; O0-NEXT:    fmul s4, s4, v2.s[1]
; O0-NEXT:    fmov w0, s5
; O0-NEXT:    fmov s5, w0
; O0-NEXT:    fmul s5, s5, v2.s[0]
; O0-NEXT:    fadd s0, s0, s5
; O0-NEXT:    fadd s0, s0, s4
; O0-NEXT:    fmul s3, s3, v2.s[2]
; O0-NEXT:    fadd s0, s0, s3
; O0-NEXT:    fmul s1, s1, v2.s[3]
; O0-NEXT:    fadd s0, s0, s1
; O0-NEXT:    ret
;
; O1-LABEL: fdot_f32:
; O1:       // %bb.0:
; O1-NEXT:    mov s3, v1.s[1]
; O1-NEXT:    fmul s4, s1, v2.s[0]
; O1-NEXT:    mov s5, v1.s[2]
; O1-NEXT:    mov s1, v1.s[3]
; O1-NEXT:    fmul s3, s3, v2.s[1]
; O1-NEXT:    fadd s0, s0, s4
; O1-NEXT:    fmul s1, s1, v2.s[3]
; O1-NEXT:    fadd s0, s0, s3
; O1-NEXT:    fmul s3, s5, v2.s[2]
; O1-NEXT:    fadd s0, s0, s3
; O1-NEXT:    fadd s0, s0, s1
; O1-NEXT:    ret
  %res = call float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

define float @fdot_f32_contract(float %acc, <4 x float> %a, <4 x float> %b) {
; O0-LABEL: fdot_f32_contract:
; O0:       // %bb.0:
; O0-NEXT:    sub sp, sp, #16
; O0-NEXT:    .cfi_def_cfa_offset 16
; O0-NEXT:    str q2, [sp] // 16-byte Spill
; O0-NEXT:    mov v2.16b, v1.16b
; O0-NEXT:    fmov s6, s0
; O0-NEXT:    ldr q0, [sp] // 16-byte Reload
; O0-NEXT:    mov s1, v0.s[3]
; O0-NEXT:    mov s3, v0.s[2]
; O0-NEXT:    mov s4, v0.s[1]
; O0-NEXT:    fmov w0, s0
; O0-NEXT:    fmov w1, s2
; O0-NEXT:    fmov s0, w1
; O0-NEXT:    fmov s5, w0
; O0-NEXT:    fmadd s0, s0, s5, s6
; O0-NEXT:    fmla s0, s4, v2.s[1]
; O0-NEXT:    fmla s0, s3, v2.s[2]
; O0-NEXT:    fmla s0, s1, v2.s[3]
; O0-NEXT:    add sp, sp, #16
; O0-NEXT:    ret
;
; O1-LABEL: fdot_f32_contract:
; O1:       // %bb.0:
; O1-NEXT:    mov s3, v2.s[1]
; O1-NEXT:    fmadd s0, s1, s2, s0
; O1-NEXT:    mov s4, v2.s[2]
; O1-NEXT:    mov s2, v2.s[3]
; O1-NEXT:    fmla s0, s3, v1.s[1]
; O1-NEXT:    fmla s0, s4, v1.s[2]
; O1-NEXT:    fmla s0, s2, v1.s[3]
; O1-NEXT:    ret
  %res = call contract float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

define float @fdot_f32_reassoc(float %acc, <4 x float> %a, <4 x float> %b) {
; O0-LABEL: fdot_f32_reassoc:
; O0:       // %bb.0:
; O0-NEXT:    fmul v1.4s, v1.4s, v2.4s
; O0-NEXT:    faddp v1.4s, v1.4s, v1.4s
; O0-NEXT:    fmov x0, d1
; O0-NEXT:    fmov d1, x0
; O0-NEXT:    faddp s1, v1.2s
; O0-NEXT:    fadd s0, s0, s1
; O0-NEXT:    ret
;
; O1-LABEL: fdot_f32_reassoc:
; O1:       // %bb.0:
; O1-NEXT:    fmul v1.4s, v1.4s, v2.4s
; O1-NEXT:    faddp v1.4s, v1.4s, v1.4s
; O1-NEXT:    faddp s1, v1.2s
; O1-NEXT:    fadd s0, s0, s1
; O1-NEXT:    ret
  %res = call reassoc float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

define float @fdot_f32_reassoc_contract(float %acc, <4 x float> %a, <4 x float> %b) {
; O0-LABEL: fdot_f32_reassoc_contract:
; O0:       // %bb.0:
; O0-NEXT:    fmul v1.4s, v1.4s, v2.4s
; O0-NEXT:    faddp v1.4s, v1.4s, v1.4s
; O0-NEXT:    fmov x0, d1
; O0-NEXT:    fmov d1, x0
; O0-NEXT:    faddp s1, v1.2s
; O0-NEXT:    fadd s0, s0, s1
; O0-NEXT:    ret
;
; O1-LABEL: fdot_f32_reassoc_contract:
; O1:       // %bb.0:
; O1-NEXT:    fmul v1.4s, v1.4s, v2.4s
; O1-NEXT:    faddp v1.4s, v1.4s, v1.4s
; O1-NEXT:    faddp s1, v1.2s
; O1-NEXT:    fadd s0, s0, s1
; O1-NEXT:    ret
  %res = call reassoc contract float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

define double @fdot_f64(double %acc, <4 x double> %a, <4 x double> %b) {
; O0-LABEL: fdot_f64:
; O0:       // %bb.0:
; O0-NEXT:    mov v6.16b, v3.16b
; O0-NEXT:    mov v5.16b, v1.16b
; O0-NEXT:    mov d1, v2.d[1]
; O0-NEXT:    mov d3, v5.d[1]
; O0-NEXT:    fmul d3, d3, v6.d[1]
; O0-NEXT:    fmov x0, d5
; O0-NEXT:    fmov d5, x0
; O0-NEXT:    fmul d5, d5, v6.d[0]
; O0-NEXT:    fadd d0, d0, d5
; O0-NEXT:    fadd d0, d0, d3
; O0-NEXT:    fmov x0, d2
; O0-NEXT:    fmov d2, x0
; O0-NEXT:    fmul d2, d2, v4.d[0]
; O0-NEXT:    fadd d0, d0, d2
; O0-NEXT:    fmul d1, d1, v4.d[1]
; O0-NEXT:    fadd d0, d0, d1
; O0-NEXT:    ret
;
; O1-LABEL: fdot_f64:
; O1:       // %bb.0:
; O1-NEXT:    mov d6, v1.d[1]
; O1-NEXT:    fmul d1, d1, v3.d[0]
; O1-NEXT:    mov d5, v2.d[1]
; O1-NEXT:    fmul d3, d6, v3.d[1]
; O1-NEXT:    fadd d0, d0, d1
; O1-NEXT:    fmul d1, d2, v4.d[0]
; O1-NEXT:    fadd d0, d0, d3
; O1-NEXT:    fadd d0, d0, d1
; O1-NEXT:    fmul d1, d5, v4.d[1]
; O1-NEXT:    fadd d0, d0, d1
; O1-NEXT:    ret
  %res = call double @llvm.vector.reduce.fdot.v4f64(double %acc, <4 x double> %a, <4 x double> %b)
  ret double %res
}

define double @fdot_f64_contract(double %acc, <4 x double> %a, <4 x double> %b) {
; O0-LABEL: fdot_f64_contract:
; O0:       // %bb.0:
; O0-NEXT:    sub sp, sp, #16
; O0-NEXT:    .cfi_def_cfa_offset 16
; O0-NEXT:    str q4, [sp] // 16-byte Spill
; O0-NEXT:    mov v4.16b, v3.16b
; O0-NEXT:    mov v5.16b, v1.16b
; O0-NEXT:    fmov d7, d0
; O0-NEXT:    ldr q0, [sp] // 16-byte Reload
; O0-NEXT:    mov d1, v0.d[1]
; O0-NEXT:    mov d3, v4.d[1]
; O0-NEXT:    fmov x0, d4
; O0-NEXT:    fmov x1, d5
; O0-NEXT:    fmov d4, x1
; O0-NEXT:    fmov d6, x0
; O0-NEXT:    fmadd d4, d4, d6, d7
; O0-NEXT:    fmla d4, d3, v5.d[1]
; O0-NEXT:    fmov x0, d0
; O0-NEXT:    fmov x1, d2
; O0-NEXT:    fmov d0, x1
; O0-NEXT:    fmov d3, x0
; O0-NEXT:    fmadd d0, d0, d3, d4
; O0-NEXT:    fmla d0, d1, v2.d[1]
; O0-NEXT:    add sp, sp, #16
; O0-NEXT:    ret
;
; O1-LABEL: fdot_f64_contract:
; O1:       // %bb.0:
; O1-NEXT:    mov d5, v3.d[1]
; O1-NEXT:    fmadd d0, d1, d3, d0
; O1-NEXT:    fmla d0, d5, v1.d[1]
; O1-NEXT:    mov d1, v4.d[1]
; O1-NEXT:    fmadd d0, d2, d4, d0
; O1-NEXT:    fmla d0, d1, v2.d[1]
; O1-NEXT:    ret
  %res = call contract double @llvm.vector.reduce.fdot.v4f64(double %acc, <4 x double> %a, <4 x double> %b)
  ret double %res
}

define double @fdot_f64_reassoc(double %acc, <4 x double> %a, <4 x double> %b) {
; O0-LABEL: fdot_f64_reassoc:
; O0:       // %bb.0:
; O0-NEXT:    fmul v2.2d, v2.2d, v4.2d
; O0-NEXT:    faddp d2, v2.2d
; O0-NEXT:    fmul v1.2d, v1.2d, v3.2d
; O0-NEXT:    faddp d1, v1.2d
; O0-NEXT:    fadd d1, d1, d2
; O0-NEXT:    fadd d0, d0, d1
; O0-NEXT:    ret
;
; O1-LABEL: fdot_f64_reassoc:
; O1:       // %bb.0:
; O1-NEXT:    fmul v2.2d, v2.2d, v4.2d
; O1-NEXT:    fmul v1.2d, v1.2d, v3.2d
; O1-NEXT:    faddp d2, v2.2d
; O1-NEXT:    faddp d1, v1.2d
; O1-NEXT:    fadd d1, d1, d2
; O1-NEXT:    fadd d0, d0, d1
; O1-NEXT:    ret
  %res = call reassoc double @llvm.vector.reduce.fdot.v4f64(double %acc, <4 x double> %a, <4 x double> %b)
  ret double %res
}

define double @fdot_f64_reassoc_contract(double %acc, <4 x double> %a, <4 x double> %b) {
; O0-LABEL: fdot_f64_reassoc_contract:
; O0:       // %bb.0:
; O0-NEXT:    fmul v2.2d, v2.2d, v4.2d
; O0-NEXT:    faddp d2, v2.2d
; O0-NEXT:    fmul v1.2d, v1.2d, v3.2d
; O0-NEXT:    faddp d1, v1.2d
; O0-NEXT:    fadd d1, d1, d2
; O0-NEXT:    fadd d0, d0, d1
; O0-NEXT:    ret
;
; O1-LABEL: fdot_f64_reassoc_contract:
; O1:       // %bb.0:
; O1-NEXT:    fmul v2.2d, v2.2d, v4.2d
; O1-NEXT:    fmul v1.2d, v1.2d, v3.2d
; O1-NEXT:    faddp d2, v2.2d
; O1-NEXT:    faddp d1, v1.2d
; O1-NEXT:    fadd d1, d1, d2
; O1-NEXT:    fadd d0, d0, d1
; O1-NEXT:    ret
  %res = call reassoc contract double @llvm.vector.reduce.fdot.v4f64(double %acc, <4 x double> %a, <4 x double> %b)
  ret double %res
}
