; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-unknown-linux-gnu < %s | FileCheck %s

define void @volatile_store(ptr %start, ptr %end) {
; CHECK-LABEL: volatile_store:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov w8, #42 // =0x2a
; CHECK-NEXT:  .LBB0_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    str w8, [x0], #4
; CHECK-NEXT:    cmp x0, x1
; CHECK-NEXT:    b.ne .LBB0_1
; CHECK-NEXT:  // %bb.2: // %bb2
; CHECK-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi ptr [ %iv.next, %loop ], [ %start, %entry ]
  %iv.next = getelementptr inbounds nuw i8, ptr %iv, i64 4
  store volatile i32 42, ptr %iv, align 4
  %cmp = icmp eq ptr %iv.next, %end
  br i1 %cmp, label %bb2, label %loop

bb2:
  ret void
}

define void @volatile_load(ptr %start, ptr %end) {
; CHECK-LABEL: volatile_load:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:  .LBB1_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldr wzr, [x0], #4
; CHECK-NEXT:    cmp x0, x1
; CHECK-NEXT:    b.ne .LBB1_1
; CHECK-NEXT:  // %bb.2: // %bb2
; CHECK-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi ptr [ %iv.next, %loop ], [ %start, %entry ]
  %iv.next = getelementptr inbounds nuw i8, ptr %iv, i64 4
  load volatile i32, ptr %iv, align 4
  %cmp = icmp eq ptr %iv.next, %end
  br i1 %cmp, label %bb2, label %loop

bb2:
  ret void
}
