; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-unknown-linux-gnu < %s | FileCheck %s --check-prefixes=CHECK,SDAG
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -global-isel < %s | FileCheck %s --check-prefixes=CHECK,GISEL

; Make sure postinc/preinc addressing mode is not used for volatile accesses,
; see https://github.com/llvm/llvm-project/issues/173014.

define ptr @volatile_store_postinc(ptr %p) {
; SDAG-LABEL: volatile_store_postinc:
; SDAG:       // %bb.0:
; SDAG-NEXT:    mov x8, x0
; SDAG-NEXT:    add x0, x0, #4
; SDAG-NEXT:    str wzr, [x8]
; SDAG-NEXT:    ret
;
; GISEL-LABEL: volatile_store_postinc:
; GISEL:       // %bb.0:
; GISEL-NEXT:    str wzr, [x0], #4
; GISEL-NEXT:    ret
  store volatile i32 0, ptr %p
  %gep = getelementptr i8, ptr %p, i64 4
  ret ptr %gep
}

define ptr @volatile_load_postinc(ptr %p) {
; SDAG-LABEL: volatile_load_postinc:
; SDAG:       // %bb.0:
; SDAG-NEXT:    ldr wzr, [x0]
; SDAG-NEXT:    add x0, x0, #4
; SDAG-NEXT:    ret
;
; GISEL-LABEL: volatile_load_postinc:
; GISEL:       // %bb.0:
; GISEL-NEXT:    ldr wzr, [x0], #4
; GISEL-NEXT:    ret
  load volatile i32, ptr %p
  %gep = getelementptr i8, ptr %p, i64 4
  ret ptr %gep
}

define ptr @volatile_store_preinc(ptr %p) {
; SDAG-LABEL: volatile_store_preinc:
; SDAG:       // %bb.0:
; SDAG-NEXT:    mov x8, x0
; SDAG-NEXT:    add x0, x0, #4
; SDAG-NEXT:    str wzr, [x8, #4]
; SDAG-NEXT:    ret
;
; GISEL-LABEL: volatile_store_preinc:
; GISEL:       // %bb.0:
; GISEL-NEXT:    str wzr, [x0, #4]!
; GISEL-NEXT:    ret
  %gep = getelementptr i8, ptr %p, i64 4
  store volatile i32 0, ptr %gep
  ret ptr %gep
}

define ptr @volatile_load_preinc(ptr %p) {
; SDAG-LABEL: volatile_load_preinc:
; SDAG:       // %bb.0:
; SDAG-NEXT:    ldr wzr, [x0, #4]
; SDAG-NEXT:    add x0, x0, #4
; SDAG-NEXT:    ret
;
; GISEL-LABEL: volatile_load_preinc:
; GISEL:       // %bb.0:
; GISEL-NEXT:    ldr wzr, [x0, #4]!
; GISEL-NEXT:    ret
  %gep = getelementptr i8, ptr %p, i64 4
  load volatile i32, ptr %gep
  ret ptr %gep
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
