; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=arm64-apple-ios -o - %s | FileCheck %s

define <4 x i32> @freeze_or_setcc(<4 x i32> %a, <4 x i32> %b, <4 x i32> %x, <4 x i32> %y) {
; CHECK-LABEL: freeze_or_setcc:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add.4s v4, v0, v1
; CHECK-NEXT:    cmgt.4s v0, v1, v0
; CHECK-NEXT:    cmgt.4s v4, v4, #0
; CHECK-NEXT:    orr.16b v0, v4, v0
; CHECK-NEXT:    bsl.16b v0, v2, v3
; CHECK-NEXT:    ret
  %add = add nsw <4 x i32> %a, %b
  %cmp1 = icmp sgt <4 x i32> %add, zeroinitializer
  %sub = sub nsw <4 x i32> %a, %b
  %cmp2 = icmp slt <4 x i32> %sub, zeroinitializer
  %or = or <4 x i1> %cmp1, %cmp2
  %fr = freeze <4 x i1> %or
  %sel = select <4 x i1> %fr, <4 x i32> %x, <4 x i32> %y
  ret <4 x i32> %sel
}

define <4 x i32> @select_allones_or_setcc(<4 x i32> %a, <4 x i32> %x, <4 x i32> %y, i1 %cond) {
; CHECK-LABEL: select_allones_or_setcc:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    tst w0, #0x1
; CHECK-NEXT:    cmgt.4s v0, v0, #0
; CHECK-NEXT:    csetm w8, ne
; CHECK-NEXT:    dup.4s v3, w8
; CHECK-NEXT:    orr.16b v0, v0, v3
; CHECK-NEXT:    bsl.16b v0, v1, v2
; CHECK-NEXT:    ret
  %cmp = icmp sgt <4 x i32> %a, zeroinitializer
  %mask = select i1 %cond, <4 x i1> <i1 true, i1 true, i1 true, i1 true>, <4 x i1> %cmp
  %sel = select <4 x i1> %mask, <4 x i32> %x, <4 x i32> %y
  ret <4 x i32> %sel
}

define <4 x i32> @select_setcc_or_allzeros(<4 x i32> %a, <4 x i32> %x, <4 x i32> %y, i1 %cond) {
; CHECK-LABEL: select_setcc_or_allzeros:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    tst w0, #0x1
; CHECK-NEXT:    cmgt.4s v0, v0, #0
; CHECK-NEXT:    csetm w8, ne
; CHECK-NEXT:    dup.4s v3, w8
; CHECK-NEXT:    and.16b v0, v0, v3
; CHECK-NEXT:    bsl.16b v0, v1, v2
; CHECK-NEXT:    ret
  %cmp = icmp sgt <4 x i32> %a, zeroinitializer
  %mask = select i1 %cond, <4 x i1> %cmp, <4 x i1> zeroinitializer
  %sel = select <4 x i1> %mask, <4 x i32> %x, <4 x i32> %y
  ret <4 x i32> %sel
}

define <4 x i32> @select_allzeros_or_allones(<4 x i32> %x, <4 x i32> %y, i1 %cond) {
; CHECK-LABEL: select_allzeros_or_allones:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    tst w0, #0x1
; CHECK-NEXT:    csetm w8, ne
; CHECK-NEXT:    dup.4s v2, w8
; CHECK-NEXT:    bit.16b v0, v1, v2
; CHECK-NEXT:    ret
  %mask = select i1 %cond, <4 x i1> zeroinitializer, <4 x i1> <i1 true, i1 true, i1 true, i1 true>
  %sel = select <4 x i1> %mask, <4 x i32> %x, <4 x i32> %y
  ret <4 x i32> %sel
}

define <4 x i32> @vselect_of_setccs(<4 x i32> %a, <4 x i32> %b, <4 x i32> %x, <4 x i32> %y) {
; CHECK-LABEL: vselect_of_setccs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    movi.4s v4, #100
; CHECK-NEXT:    cmgt.4s v5, v0, #0
; CHECK-NEXT:    cmeq.4s v1, v1, #0
; CHECK-NEXT:    cmgt.4s v0, v4, v0
; CHECK-NEXT:    bit.16b v0, v5, v1
; CHECK-NEXT:    bsl.16b v0, v2, v3
; CHECK-NEXT:    ret
  %cmp1 = icmp sgt <4 x i32> %a, zeroinitializer
  %cmp2 = icmp slt <4 x i32> %a, <i32 100, i32 100, i32 100, i32 100>
  %cond = icmp eq <4 x i32> %b, zeroinitializer
  %mask = select <4 x i1> %cond, <4 x i1> %cmp1, <4 x i1> %cmp2
  %sel = select <4 x i1> %mask, <4 x i32> %x, <4 x i32> %y
  ret <4 x i32> %sel
}

define <4 x i32> @select_scalar_cond_setccs(<4 x i32> %a, <4 x i32> %x, <4 x i32> %y, i1 %cond) {
; CHECK-LABEL: select_scalar_cond_setccs:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    movi.4s v3, #100
; CHECK-NEXT:    tst w0, #0x1
; CHECK-NEXT:    cmgt.4s v4, v0, #0
; CHECK-NEXT:    csetm w8, ne
; CHECK-NEXT:    cmgt.4s v0, v3, v0
; CHECK-NEXT:    dup.4s v3, w8
; CHECK-NEXT:    bif.16b v0, v4, v3
; CHECK-NEXT:    bsl.16b v0, v1, v2
; CHECK-NEXT:    ret
entry:
  %cmp1 = icmp sgt <4 x i32> %a, zeroinitializer
  br i1 %cond, label %then, label %else

then:
  %cmp2 = icmp slt <4 x i32> %a, <i32 100, i32 100, i32 100, i32 100>
  br label %merge

else:
  br label %merge

merge:
  %mask = phi <4 x i1> [ %cmp2, %then ], [ %cmp1, %else ]
  %fr = freeze <4 x i1> %mask
  %sel = select <4 x i1> %fr, <4 x i32> %x, <4 x i32> %y
  ret <4 x i32> %sel
}

define <3 x i64> @or_setcc_i16_i32_sel_i64(<3 x i16> %a, <3 x i16> %b, <3 x i32> %c, <3 x i32> %d, <3 x i64> %x, <3 x i64> %y) {
; CHECK-LABEL: or_setcc_i16_i32_sel_i64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    cmgt.4h v0, v0, v1
; CHECK-NEXT:    cmgt.4s v1, v2, v3
; CHECK-NEXT:    ; kill: def $d7 killed $d7 def $q7
; CHECK-NEXT:    ; kill: def $d4 killed $d4 def $q4
; CHECK-NEXT:    ; kill: def $d5 killed $d5 def $q5
; CHECK-NEXT:    ; kill: def $d6 killed $d6 def $q6
; CHECK-NEXT:    mov.d v4[1], v5[0]
; CHECK-NEXT:    sshll.4s v0, v0, #0
; CHECK-NEXT:    orr.16b v1, v0, v1
; CHECK-NEXT:    ldp d0, d2, [sp]
; CHECK-NEXT:    mov.d v7[1], v0[0]
; CHECK-NEXT:    sshll.2d v0, v1, #0
; CHECK-NEXT:    sshll2.2d v1, v1, #0
; CHECK-NEXT:    bit.16b v2, v6, v1
; CHECK-NEXT:    bsl.16b v0, v4, v7
; CHECK-NEXT:    ; kill: def $d2 killed $d2 killed $q2
; CHECK-NEXT:    ext.16b v1, v0, v0, #8
; CHECK-NEXT:    ; kill: def $d0 killed $d0 killed $q0
; CHECK-NEXT:    ; kill: def $d1 killed $d1 killed $q1
; CHECK-NEXT:    ret
  %cmp0 = icmp sgt <3 x i16> %a, %b
  %cmp1 = icmp sgt <3 x i32> %c, %d
  %or = or <3 x i1> %cmp0, %cmp1
  %sel = select <3 x i1> %or, <3 x i64> %x, <3 x i64> %y
  ret <3 x i64> %sel
}

define <3 x i64> @and_setcc_i32_i32_sel_i64(<3 x i32> %a, <3 x i32> %b, <3 x i32> %c, <3 x i32> %d, <3 x i64> %x, <3 x i64> %y) {
; CHECK-LABEL: and_setcc_i32_i32_sel_i64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    cmgt.4s v2, v2, v3
; CHECK-NEXT:    cmgt.4s v0, v0, v1
; CHECK-NEXT:    ; kill: def $d7 killed $d7 def $q7
; CHECK-NEXT:    ; kill: def $d4 killed $d4 def $q4
; CHECK-NEXT:    ; kill: def $d5 killed $d5 def $q5
; CHECK-NEXT:    ; kill: def $d6 killed $d6 def $q6
; CHECK-NEXT:    mov.d v4[1], v5[0]
; CHECK-NEXT:    and.16b v1, v0, v2
; CHECK-NEXT:    ldp d0, d2, [sp]
; CHECK-NEXT:    mov.d v7[1], v0[0]
; CHECK-NEXT:    sshll.2d v0, v1, #0
; CHECK-NEXT:    sshll2.2d v1, v1, #0
; CHECK-NEXT:    bit.16b v2, v6, v1
; CHECK-NEXT:    bsl.16b v0, v4, v7
; CHECK-NEXT:    ; kill: def $d2 killed $d2 killed $q2
; CHECK-NEXT:    ext.16b v1, v0, v0, #8
; CHECK-NEXT:    ; kill: def $d0 killed $d0 killed $q0
; CHECK-NEXT:    ; kill: def $d1 killed $d1 killed $q1
; CHECK-NEXT:    ret
  %cmp0 = icmp sgt <3 x i32> %a, %b
  %cmp1 = icmp sgt <3 x i32> %c, %d
  %and = and <3 x i1> %cmp0, %cmp1
  %sel = select <3 x i1> %and, <3 x i64> %x, <3 x i64> %y
  ret <3 x i64> %sel
}

define <3 x i64> @or_setcc_i16_i16_sel_i64(<3 x i16> %a, <3 x i16> %b, <3 x i16> %c, <3 x i16> %d, <3 x i64> %x, <3 x i64> %y) {
; CHECK-LABEL: or_setcc_i16_i16_sel_i64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    cmgt.4h v2, v2, v3
; CHECK-NEXT:    cmgt.4h v0, v0, v1
; CHECK-NEXT:    ; kill: def $d7 killed $d7 def $q7
; CHECK-NEXT:    ; kill: def $d4 killed $d4 def $q4
; CHECK-NEXT:    ; kill: def $d5 killed $d5 def $q5
; CHECK-NEXT:    ; kill: def $d6 killed $d6 def $q6
; CHECK-NEXT:    mov.d v4[1], v5[0]
; CHECK-NEXT:    orr.8b v0, v0, v2
; CHECK-NEXT:    sshll.4s v1, v0, #0
; CHECK-NEXT:    ldp d0, d2, [sp]
; CHECK-NEXT:    mov.d v7[1], v0[0]
; CHECK-NEXT:    sshll.2d v0, v1, #0
; CHECK-NEXT:    sshll2.2d v1, v1, #0
; CHECK-NEXT:    bit.16b v2, v6, v1
; CHECK-NEXT:    bsl.16b v0, v4, v7
; CHECK-NEXT:    ; kill: def $d2 killed $d2 killed $q2
; CHECK-NEXT:    ext.16b v1, v0, v0, #8
; CHECK-NEXT:    ; kill: def $d0 killed $d0 killed $q0
; CHECK-NEXT:    ; kill: def $d1 killed $d1 killed $q1
; CHECK-NEXT:    ret
  %cmp0 = icmp sgt <3 x i16> %a, %b
  %cmp1 = icmp sgt <3 x i16> %c, %d
  %or = or <3 x i1> %cmp0, %cmp1
  %sel = select <3 x i1> %or, <3 x i64> %x, <3 x i64> %y
  ret <3 x i64> %sel
}
