; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=aarch64 | FileCheck %s

; Test that (xor x, (select_cc fp_a, fp_b, cc, 0, -1)) folds to CSINV
; with an FCMP instead of falling back to CSETM + EOR.

define i32 @xor_fp_ogt_f32(float %a, float %b, i32 %x) {
; CHECK-LABEL: xor_fp_ogt_f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcmp s0, s1
; CHECK-NEXT:    csetm w8, gt
; CHECK-NEXT:    eor w0, w0, w8
; CHECK-NEXT:    ret
  %cmp = fcmp ogt float %a, %b
  %mask = sext i1 %cmp to i32
  %result = xor i32 %x, %mask
  ret i32 %result
}

define i32 @xor_fp_olt_f64(double %a, double %b, i32 %x) {
; CHECK-LABEL: xor_fp_olt_f64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcmp d0, d1
; CHECK-NEXT:    csetm w8, mi
; CHECK-NEXT:    eor w0, w0, w8
; CHECK-NEXT:    ret
  %cmp = fcmp olt double %a, %b
  %mask = sext i1 %cmp to i32
  %result = xor i32 %x, %mask
  ret i32 %result
}

; Inverted pattern: TVal=-1, FVal=0 (should still fold via CC inversion)
define i32 @xor_fp_ole_f32_inverted(float %a, float %b, i32 %x) {
; CHECK-LABEL: xor_fp_ole_f32_inverted:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcmp s0, s1
; CHECK-NEXT:    csetm w8, ls
; CHECK-NEXT:    eor w0, w0, w8
; CHECK-NEXT:    ret
  %cmp = fcmp ole float %a, %b
  %mask = sext i1 %cmp to i32
  %result = xor i32 %x, %mask
  ret i32 %result
}

; 64-bit integer result
define i64 @xor_fp_oge_f32_i64(float %a, float %b, i64 %x) {
; CHECK-LABEL: xor_fp_oge_f32_i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcmp s0, s1
; CHECK-NEXT:    csetm x8, ge
; CHECK-NEXT:    eor x0, x0, x8
; CHECK-NEXT:    ret
  %cmp = fcmp oge float %a, %b
  %mask = sext i1 %cmp to i64
  %result = xor i64 %x, %mask
  ret i64 %result
}

; Dual-CC condition (SETONE) — should NOT fold to CSINV (bails out)
define i32 @xor_fp_one_f32(float %a, float %b, i32 %x) {
; CHECK-LABEL: xor_fp_one_f32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    fcmp s0, s1
; CHECK-NEXT:    csetm w8, mi
; CHECK-NEXT:    csinv w8, w8, wzr, le
; CHECK-NEXT:    eor w0, w0, w8
; CHECK-NEXT:    ret
  %cmp = fcmp one float %a, %b
  %mask = sext i1 %cmp to i32
  %result = xor i32 %x, %mask
  ret i32 %result
}
