; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -slp-threshold=-19 -mattr=+v -mtriple riscv32 < %s | FileCheck %s
; RUN: opt -passes=slp-vectorizer -S -slp-threshold=-55 -mattr=+v -mtriple riscv32 < %s | FileCheck %s --check-prefix=EXP

define void @test(ptr %__last.addr.011.i.i, ptr %call3) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[__LAST_ADDR_011_I_I:%.*]], ptr [[CALL3:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[NEWFUNCROOT:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x ptr> poison, ptr [[__LAST_ADDR_011_I_I]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <2 x ptr> [[TMP0]], ptr [[CALL3]], i32 1
; CHECK-NEXT:    br label %[[WHILE_BODY_I_I:.*]]
; CHECK:       [[WHILE_BODY_I_I]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi <2 x ptr> [ [[TMP1]], %[[NEWFUNCROOT]] ], [ [[TMP76:%.*]], %[[WHILE_BODY_I_I]] ]
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x ptr> [[TMP2]], i32 1
; CHECK-NEXT:    [[TMP5:%.*]] = load float, ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <2 x ptr> [[TMP2]], i32 0
; CHECK-NEXT:    [[TMP6:%.*]] = load float, ptr [[TMP4]], align 4
; CHECK-NEXT:    store float [[TMP6]], ptr [[TMP3]], align 4
; CHECK-NEXT:    store float [[TMP5]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP3]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I:%.*]] = getelementptr inbounds i8, ptr [[TMP4]], i32 -4
; CHECK-NEXT:    [[TMP17:%.*]] = load float, ptr [[INCDEC_PTR2_I_I]], align 4
; CHECK-NEXT:    [[TMP18:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I]], align 4
; CHECK-NEXT:    store float [[TMP18]], ptr [[INCDEC_PTR2_I_I]], align 4
; CHECK-NEXT:    store float [[TMP17]], ptr [[__LAST_ADDR_0_I_I]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_1:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I]], i32 -4
; CHECK-NEXT:    [[TMP20:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_1]], align 4
; CHECK-NEXT:    [[TMP21:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_1]], align 4
; CHECK-NEXT:    store float [[TMP21]], ptr [[INCDEC_PTR2_I_I_1]], align 4
; CHECK-NEXT:    store float [[TMP20]], ptr [[__LAST_ADDR_0_I_I_1]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_2:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_1]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_2:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_1]], i32 -4
; CHECK-NEXT:    [[TMP23:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_2]], align 4
; CHECK-NEXT:    [[TMP24:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_2]], align 4
; CHECK-NEXT:    store float [[TMP24]], ptr [[INCDEC_PTR2_I_I_2]], align 4
; CHECK-NEXT:    store float [[TMP23]], ptr [[__LAST_ADDR_0_I_I_2]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_3:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_2]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_3:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_2]], i32 -4
; CHECK-NEXT:    [[TMP26:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_3]], align 4
; CHECK-NEXT:    [[TMP27:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_3]], align 4
; CHECK-NEXT:    store float [[TMP27]], ptr [[INCDEC_PTR2_I_I_3]], align 4
; CHECK-NEXT:    store float [[TMP26]], ptr [[__LAST_ADDR_0_I_I_3]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_4:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_3]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_4:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_3]], i32 -4
; CHECK-NEXT:    [[TMP29:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_4]], align 4
; CHECK-NEXT:    [[TMP30:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_4]], align 4
; CHECK-NEXT:    store float [[TMP30]], ptr [[INCDEC_PTR2_I_I_4]], align 4
; CHECK-NEXT:    store float [[TMP29]], ptr [[__LAST_ADDR_0_I_I_4]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_5:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_4]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_5:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_4]], i32 -4
; CHECK-NEXT:    [[TMP32:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_5]], align 4
; CHECK-NEXT:    [[TMP33:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_5]], align 4
; CHECK-NEXT:    store float [[TMP33]], ptr [[INCDEC_PTR2_I_I_5]], align 4
; CHECK-NEXT:    store float [[TMP32]], ptr [[__LAST_ADDR_0_I_I_5]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_6:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_5]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_6:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_5]], i32 -4
; CHECK-NEXT:    [[TMP35:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_6]], align 4
; CHECK-NEXT:    [[TMP36:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_6]], align 4
; CHECK-NEXT:    store float [[TMP36]], ptr [[INCDEC_PTR2_I_I_6]], align 4
; CHECK-NEXT:    store float [[TMP35]], ptr [[__LAST_ADDR_0_I_I_6]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_7:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_6]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_7:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_6]], i32 -4
; CHECK-NEXT:    [[TMP38:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_7]], align 4
; CHECK-NEXT:    [[TMP39:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_7]], align 4
; CHECK-NEXT:    store float [[TMP39]], ptr [[INCDEC_PTR2_I_I_7]], align 4
; CHECK-NEXT:    store float [[TMP38]], ptr [[__LAST_ADDR_0_I_I_7]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_8:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_7]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_8:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_7]], i32 -4
; CHECK-NEXT:    [[TMP41:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_8]], align 4
; CHECK-NEXT:    [[TMP42:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_8]], align 4
; CHECK-NEXT:    store float [[TMP42]], ptr [[INCDEC_PTR2_I_I_8]], align 4
; CHECK-NEXT:    store float [[TMP41]], ptr [[__LAST_ADDR_0_I_I_8]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_9:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_8]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_9:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_8]], i32 -4
; CHECK-NEXT:    [[TMP56:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_9]], align 4
; CHECK-NEXT:    [[TMP57:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_9]], align 4
; CHECK-NEXT:    store float [[TMP57]], ptr [[INCDEC_PTR2_I_I_9]], align 4
; CHECK-NEXT:    store float [[TMP56]], ptr [[__LAST_ADDR_0_I_I_9]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_10:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_9]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_10:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_9]], i32 -4
; CHECK-NEXT:    [[TMP59:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_10]], align 4
; CHECK-NEXT:    [[TMP60:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_10]], align 4
; CHECK-NEXT:    store float [[TMP60]], ptr [[INCDEC_PTR2_I_I_10]], align 4
; CHECK-NEXT:    store float [[TMP59]], ptr [[__LAST_ADDR_0_I_I_10]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_11:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_10]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_11:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_10]], i32 -4
; CHECK-NEXT:    [[TMP62:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_11]], align 4
; CHECK-NEXT:    [[TMP63:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_11]], align 4
; CHECK-NEXT:    store float [[TMP63]], ptr [[INCDEC_PTR2_I_I_11]], align 4
; CHECK-NEXT:    store float [[TMP62]], ptr [[__LAST_ADDR_0_I_I_11]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_12:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_11]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_12:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_11]], i32 -4
; CHECK-NEXT:    [[TMP65:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_12]], align 4
; CHECK-NEXT:    [[TMP66:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_12]], align 4
; CHECK-NEXT:    store float [[TMP66]], ptr [[INCDEC_PTR2_I_I_12]], align 4
; CHECK-NEXT:    store float [[TMP65]], ptr [[__LAST_ADDR_0_I_I_12]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_13:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_12]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_13:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_12]], i32 -4
; CHECK-NEXT:    [[TMP68:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_13]], align 4
; CHECK-NEXT:    [[TMP69:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_13]], align 4
; CHECK-NEXT:    store float [[TMP69]], ptr [[INCDEC_PTR2_I_I_13]], align 4
; CHECK-NEXT:    store float [[TMP68]], ptr [[__LAST_ADDR_0_I_I_13]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_14:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_13]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_14:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_13]], i32 -4
; CHECK-NEXT:    [[TMP71:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_14]], align 4
; CHECK-NEXT:    [[TMP72:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_14]], align 4
; CHECK-NEXT:    store float [[TMP72]], ptr [[INCDEC_PTR2_I_I_14]], align 4
; CHECK-NEXT:    store float [[TMP71]], ptr [[__LAST_ADDR_0_I_I_14]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_15:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_14]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_15:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_14]], i32 -4
; CHECK-NEXT:    [[TMP74:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_15]], align 4
; CHECK-NEXT:    [[TMP75:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_15]], align 4
; CHECK-NEXT:    store float [[TMP75]], ptr [[INCDEC_PTR2_I_I_15]], align 4
; CHECK-NEXT:    store float [[TMP74]], ptr [[__LAST_ADDR_0_I_I_15]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_16:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_15]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_16:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_15]], i32 -4
; CHECK-NEXT:    [[TMP77:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_16]], align 4
; CHECK-NEXT:    [[TMP78:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_16]], align 4
; CHECK-NEXT:    store float [[TMP78]], ptr [[INCDEC_PTR2_I_I_16]], align 4
; CHECK-NEXT:    store float [[TMP77]], ptr [[__LAST_ADDR_0_I_I_16]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_17:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_16]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_17:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_16]], i32 -4
; CHECK-NEXT:    [[TMP80:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_17]], align 4
; CHECK-NEXT:    [[TMP81:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_17]], align 4
; CHECK-NEXT:    store float [[TMP81]], ptr [[INCDEC_PTR2_I_I_17]], align 4
; CHECK-NEXT:    store float [[TMP80]], ptr [[__LAST_ADDR_0_I_I_17]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_18:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_17]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_18:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_17]], i32 -4
; CHECK-NEXT:    [[TMP83:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_18]], align 4
; CHECK-NEXT:    [[TMP84:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_18]], align 4
; CHECK-NEXT:    store float [[TMP84]], ptr [[INCDEC_PTR2_I_I_18]], align 4
; CHECK-NEXT:    store float [[TMP83]], ptr [[__LAST_ADDR_0_I_I_18]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_19:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_18]], i32 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_19:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_18]], i32 -4
; CHECK-NEXT:    [[TMP86:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_19]], align 4
; CHECK-NEXT:    [[TMP87:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_19]], align 4
; CHECK-NEXT:    store float [[TMP87]], ptr [[INCDEC_PTR2_I_I_19]], align 4
; CHECK-NEXT:    store float [[TMP86]], ptr [[__LAST_ADDR_0_I_I_19]], align 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_30:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_19]], i32 -4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_30:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_19]], i32 4
; CHECK-NEXT:    [[TMP47:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_30]], align 4
; CHECK-NEXT:    [[TMP48:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_30]], align 4
; CHECK-NEXT:    store float [[TMP48]], ptr [[INCDEC_PTR2_I_I_30]], align 4
; CHECK-NEXT:    store float [[TMP47]], ptr [[__LAST_ADDR_0_I_I_30]], align 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_21:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_30]], i32 -4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_21:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_30]], i32 4
; CHECK-NEXT:    [[TMP49:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_21]], align 4
; CHECK-NEXT:    [[TMP50:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_21]], align 4
; CHECK-NEXT:    store float [[TMP50]], ptr [[INCDEC_PTR2_I_I_21]], align 4
; CHECK-NEXT:    store float [[TMP49]], ptr [[__LAST_ADDR_0_I_I_21]], align 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_22:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_21]], i32 -4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_22:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_21]], i32 4
; CHECK-NEXT:    [[TMP51:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_22]], align 4
; CHECK-NEXT:    [[TMP67:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_22]], align 4
; CHECK-NEXT:    store float [[TMP67]], ptr [[INCDEC_PTR2_I_I_22]], align 4
; CHECK-NEXT:    store float [[TMP51]], ptr [[__LAST_ADDR_0_I_I_22]], align 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_23:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_22]], i32 -4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_23:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_22]], i32 4
; CHECK-NEXT:    [[TMP70:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_23]], align 4
; CHECK-NEXT:    [[TMP54:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_23]], align 4
; CHECK-NEXT:    store float [[TMP54]], ptr [[INCDEC_PTR2_I_I_23]], align 4
; CHECK-NEXT:    store float [[TMP70]], ptr [[__LAST_ADDR_0_I_I_23]], align 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_24:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_23]], i32 -4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_24:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_23]], i32 4
; CHECK-NEXT:    [[TMP55:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_24]], align 4
; CHECK-NEXT:    [[TMP73:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_24]], align 4
; CHECK-NEXT:    store float [[TMP73]], ptr [[INCDEC_PTR2_I_I_24]], align 4
; CHECK-NEXT:    store float [[TMP55]], ptr [[__LAST_ADDR_0_I_I_24]], align 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_25:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_24]], i32 -4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_25:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_24]], i32 4
; CHECK-NEXT:    [[TMP79:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_25]], align 4
; CHECK-NEXT:    [[TMP58:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_25]], align 4
; CHECK-NEXT:    store float [[TMP58]], ptr [[INCDEC_PTR2_I_I_25]], align 4
; CHECK-NEXT:    store float [[TMP79]], ptr [[__LAST_ADDR_0_I_I_25]], align 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_26:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_25]], i32 -4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_26:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_25]], i32 4
; CHECK-NEXT:    [[TMP82:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_26]], align 4
; CHECK-NEXT:    [[TMP85:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_26]], align 4
; CHECK-NEXT:    store float [[TMP85]], ptr [[INCDEC_PTR2_I_I_26]], align 4
; CHECK-NEXT:    store float [[TMP82]], ptr [[__LAST_ADDR_0_I_I_26]], align 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_27:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_26]], i32 -4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_27:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_26]], i32 4
; CHECK-NEXT:    [[TMP61:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_27]], align 4
; CHECK-NEXT:    [[TMP88:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_27]], align 4
; CHECK-NEXT:    store float [[TMP88]], ptr [[INCDEC_PTR2_I_I_27]], align 4
; CHECK-NEXT:    store float [[TMP61]], ptr [[__LAST_ADDR_0_I_I_27]], align 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_28:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_27]], i32 -4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_28:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_27]], i32 4
; CHECK-NEXT:    [[TMP89:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_28]], align 4
; CHECK-NEXT:    [[TMP64:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_28]], align 4
; CHECK-NEXT:    store float [[TMP64]], ptr [[INCDEC_PTR2_I_I_28]], align 4
; CHECK-NEXT:    store float [[TMP89]], ptr [[__LAST_ADDR_0_I_I_28]], align 4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_29:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_28]], i32 -4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_29:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_28]], i32 4
; CHECK-NEXT:    [[TMP90:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_29]], align 4
; CHECK-NEXT:    [[TMP91:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_29]], align 4
; CHECK-NEXT:    store float [[TMP91]], ptr [[INCDEC_PTR2_I_I_29]], align 4
; CHECK-NEXT:    store float [[TMP90]], ptr [[__LAST_ADDR_0_I_I_29]], align 4
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_20:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_29]], i32 -4
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_20:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_29]], i32 4
; CHECK-NEXT:    [[TMP102:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_20]], align 4
; CHECK-NEXT:    [[TMP101:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_20]], align 4
; CHECK-NEXT:    store float [[TMP101]], ptr [[__LAST_ADDR_0_I_I_20]], align 4
; CHECK-NEXT:    store float [[TMP102]], ptr [[INCDEC_PTR2_I_I_20]], align 4
; CHECK-NEXT:    [[TMP52:%.*]] = insertelement <2 x ptr> poison, ptr [[__LAST_ADDR_0_I_I_20]], i32 0
; CHECK-NEXT:    [[TMP53:%.*]] = insertelement <2 x ptr> [[TMP52]], ptr [[INCDEC_PTR2_I_I_20]], i32 1
; CHECK-NEXT:    [[TMP92:%.*]] = getelementptr i8, <2 x ptr> [[TMP53]], <2 x i32> <i32 4, i32 -4>
; CHECK-NEXT:    [[INCDEC_PTR2_I_I_31:%.*]] = extractelement <2 x ptr> [[TMP92]], i32 0
; CHECK-NEXT:    [[__LAST_ADDR_0_I_I_31:%.*]] = extractelement <2 x ptr> [[TMP92]], i32 1
; CHECK-NEXT:    [[CMP1_I_I_31:%.*]] = icmp ult ptr [[INCDEC_PTR2_I_I_31]], [[__LAST_ADDR_0_I_I_31]]
; CHECK-NEXT:    [[TMP76]] = shufflevector <2 x ptr> [[TMP92]], <2 x ptr> poison, <2 x i32> <i32 1, i32 0>
; CHECK-NEXT:    br i1 [[CMP1_I_I_31]], label %[[WHILE_BODY_I_I]], label %[[INVOKE_CONT21_EXITSTUB:.*]]
; CHECK:       [[INVOKE_CONT21_EXITSTUB]]:
; CHECK-NEXT:    ret void
;
; EXP-LABEL: define void @test(
; EXP-SAME: ptr [[__LAST_ADDR_011_I_I:%.*]], ptr [[CALL3:%.*]]) #[[ATTR0:[0-9]+]] {
; EXP-NEXT:  [[NEWFUNCROOT:.*]]:
; EXP-NEXT:    [[TMP0:%.*]] = insertelement <2 x ptr> poison, ptr [[__LAST_ADDR_011_I_I]], i32 0
; EXP-NEXT:    [[TMP1:%.*]] = insertelement <2 x ptr> [[TMP0]], ptr [[CALL3]], i32 1
; EXP-NEXT:    br label %[[WHILE_BODY_I_I:.*]]
; EXP:       [[WHILE_BODY_I_I]]:
; EXP-NEXT:    [[TMP2:%.*]] = phi <2 x ptr> [ [[TMP1]], %[[NEWFUNCROOT]] ], [ [[TMP94:%.*]], %[[WHILE_BODY_I_I]] ]
; EXP-NEXT:    [[TMP3:%.*]] = extractelement <2 x ptr> [[TMP2]], i32 1
; EXP-NEXT:    [[TMP4:%.*]] = load float, ptr [[TMP3]], align 4
; EXP-NEXT:    [[TMP5:%.*]] = extractelement <2 x ptr> [[TMP2]], i32 0
; EXP-NEXT:    [[TMP6:%.*]] = load float, ptr [[TMP5]], align 4
; EXP-NEXT:    store float [[TMP6]], ptr [[TMP3]], align 4
; EXP-NEXT:    store float [[TMP4]], ptr [[TMP5]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP3]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I:%.*]] = getelementptr inbounds i8, ptr [[TMP5]], i32 -4
; EXP-NEXT:    [[TMP7:%.*]] = load float, ptr [[INCDEC_PTR2_I_I]], align 4
; EXP-NEXT:    [[TMP8:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I]], align 4
; EXP-NEXT:    store float [[TMP8]], ptr [[INCDEC_PTR2_I_I]], align 4
; EXP-NEXT:    store float [[TMP7]], ptr [[__LAST_ADDR_0_I_I]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_1:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I]], i32 -4
; EXP-NEXT:    [[TMP9:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_1]], align 4
; EXP-NEXT:    [[TMP10:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_1]], align 4
; EXP-NEXT:    store float [[TMP10]], ptr [[INCDEC_PTR2_I_I_1]], align 4
; EXP-NEXT:    store float [[TMP9]], ptr [[__LAST_ADDR_0_I_I_1]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_2:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_1]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_2:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_1]], i32 -4
; EXP-NEXT:    [[TMP11:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_2]], align 4
; EXP-NEXT:    [[TMP12:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_2]], align 4
; EXP-NEXT:    store float [[TMP12]], ptr [[INCDEC_PTR2_I_I_2]], align 4
; EXP-NEXT:    store float [[TMP11]], ptr [[__LAST_ADDR_0_I_I_2]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_3:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_2]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_3:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_2]], i32 -4
; EXP-NEXT:    [[TMP13:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_3]], align 4
; EXP-NEXT:    [[TMP14:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_3]], align 4
; EXP-NEXT:    store float [[TMP14]], ptr [[INCDEC_PTR2_I_I_3]], align 4
; EXP-NEXT:    store float [[TMP13]], ptr [[__LAST_ADDR_0_I_I_3]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_4:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_3]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_4:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_3]], i32 -4
; EXP-NEXT:    [[TMP15:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_4]], align 4
; EXP-NEXT:    [[TMP16:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_4]], align 4
; EXP-NEXT:    store float [[TMP16]], ptr [[INCDEC_PTR2_I_I_4]], align 4
; EXP-NEXT:    store float [[TMP15]], ptr [[__LAST_ADDR_0_I_I_4]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_5:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_4]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_5:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_4]], i32 -4
; EXP-NEXT:    [[TMP17:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_5]], align 4
; EXP-NEXT:    [[TMP18:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_5]], align 4
; EXP-NEXT:    store float [[TMP18]], ptr [[INCDEC_PTR2_I_I_5]], align 4
; EXP-NEXT:    store float [[TMP17]], ptr [[__LAST_ADDR_0_I_I_5]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_6:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_5]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_6:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_5]], i32 -4
; EXP-NEXT:    [[TMP19:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_6]], align 4
; EXP-NEXT:    [[TMP20:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_6]], align 4
; EXP-NEXT:    store float [[TMP20]], ptr [[INCDEC_PTR2_I_I_6]], align 4
; EXP-NEXT:    store float [[TMP19]], ptr [[__LAST_ADDR_0_I_I_6]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_7:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_6]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_7:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_6]], i32 -4
; EXP-NEXT:    [[TMP21:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_7]], align 4
; EXP-NEXT:    [[TMP22:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_7]], align 4
; EXP-NEXT:    store float [[TMP22]], ptr [[INCDEC_PTR2_I_I_7]], align 4
; EXP-NEXT:    store float [[TMP21]], ptr [[__LAST_ADDR_0_I_I_7]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_8:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_7]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_8:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_7]], i32 -4
; EXP-NEXT:    [[TMP23:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_8]], align 4
; EXP-NEXT:    [[TMP24:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_8]], align 4
; EXP-NEXT:    store float [[TMP24]], ptr [[INCDEC_PTR2_I_I_8]], align 4
; EXP-NEXT:    store float [[TMP23]], ptr [[__LAST_ADDR_0_I_I_8]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_9:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_8]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_9:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_8]], i32 -4
; EXP-NEXT:    [[TMP25:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_9]], align 4
; EXP-NEXT:    [[TMP26:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_9]], align 4
; EXP-NEXT:    store float [[TMP26]], ptr [[INCDEC_PTR2_I_I_9]], align 4
; EXP-NEXT:    store float [[TMP25]], ptr [[__LAST_ADDR_0_I_I_9]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_10:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_9]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_10:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_9]], i32 -4
; EXP-NEXT:    [[TMP27:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_10]], align 4
; EXP-NEXT:    [[TMP28:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_10]], align 4
; EXP-NEXT:    store float [[TMP28]], ptr [[INCDEC_PTR2_I_I_10]], align 4
; EXP-NEXT:    store float [[TMP27]], ptr [[__LAST_ADDR_0_I_I_10]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_11:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_10]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_11:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_10]], i32 -4
; EXP-NEXT:    [[TMP29:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_11]], align 4
; EXP-NEXT:    [[TMP30:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_11]], align 4
; EXP-NEXT:    store float [[TMP30]], ptr [[INCDEC_PTR2_I_I_11]], align 4
; EXP-NEXT:    store float [[TMP29]], ptr [[__LAST_ADDR_0_I_I_11]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_12:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_11]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_12:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_11]], i32 -4
; EXP-NEXT:    [[TMP31:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_12]], align 4
; EXP-NEXT:    [[TMP32:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_12]], align 4
; EXP-NEXT:    store float [[TMP32]], ptr [[INCDEC_PTR2_I_I_12]], align 4
; EXP-NEXT:    store float [[TMP31]], ptr [[__LAST_ADDR_0_I_I_12]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_13:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_12]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_13:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_12]], i32 -4
; EXP-NEXT:    [[TMP33:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_13]], align 4
; EXP-NEXT:    [[TMP34:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_13]], align 4
; EXP-NEXT:    store float [[TMP34]], ptr [[INCDEC_PTR2_I_I_13]], align 4
; EXP-NEXT:    store float [[TMP33]], ptr [[__LAST_ADDR_0_I_I_13]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_14:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_13]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_14:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_13]], i32 -4
; EXP-NEXT:    [[TMP35:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_14]], align 4
; EXP-NEXT:    [[TMP36:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_14]], align 4
; EXP-NEXT:    store float [[TMP36]], ptr [[INCDEC_PTR2_I_I_14]], align 4
; EXP-NEXT:    store float [[TMP35]], ptr [[__LAST_ADDR_0_I_I_14]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_15:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_14]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_15:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_14]], i32 -4
; EXP-NEXT:    [[TMP37:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_15]], align 4
; EXP-NEXT:    [[TMP38:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_15]], align 4
; EXP-NEXT:    store float [[TMP38]], ptr [[INCDEC_PTR2_I_I_15]], align 4
; EXP-NEXT:    store float [[TMP37]], ptr [[__LAST_ADDR_0_I_I_15]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_16:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_15]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_16:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_15]], i32 -4
; EXP-NEXT:    [[TMP39:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_16]], align 4
; EXP-NEXT:    [[TMP40:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_16]], align 4
; EXP-NEXT:    store float [[TMP40]], ptr [[INCDEC_PTR2_I_I_16]], align 4
; EXP-NEXT:    store float [[TMP39]], ptr [[__LAST_ADDR_0_I_I_16]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_17:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_16]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_17:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_16]], i32 -4
; EXP-NEXT:    [[TMP41:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_17]], align 4
; EXP-NEXT:    [[TMP42:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_17]], align 4
; EXP-NEXT:    store float [[TMP42]], ptr [[INCDEC_PTR2_I_I_17]], align 4
; EXP-NEXT:    store float [[TMP41]], ptr [[__LAST_ADDR_0_I_I_17]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_18:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_17]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_18:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_17]], i32 -4
; EXP-NEXT:    [[TMP43:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_18]], align 4
; EXP-NEXT:    [[TMP44:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_18]], align 4
; EXP-NEXT:    store float [[TMP44]], ptr [[INCDEC_PTR2_I_I_18]], align 4
; EXP-NEXT:    store float [[TMP43]], ptr [[__LAST_ADDR_0_I_I_18]], align 4
; EXP-NEXT:    [[INCDEC_PTR2_I_I_19:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_18]], i32 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_19:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_18]], i32 -4
; EXP-NEXT:    [[TMP45:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_19]], align 4
; EXP-NEXT:    [[TMP46:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_19]], align 4
; EXP-NEXT:    store float [[TMP46]], ptr [[INCDEC_PTR2_I_I_19]], align 4
; EXP-NEXT:    store float [[TMP45]], ptr [[__LAST_ADDR_0_I_I_19]], align 4
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_20:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_19]], i32 -4
; EXP-NEXT:    [[TMP47:%.*]] = insertelement <2 x ptr> poison, ptr [[INCDEC_PTR2_I_I_19]], i32 0
; EXP-NEXT:    [[TMP48:%.*]] = insertelement <2 x ptr> [[TMP47]], ptr [[__LAST_ADDR_0_I_I_19]], i32 1
; EXP-NEXT:    [[TMP49:%.*]] = getelementptr i8, <2 x ptr> [[TMP48]], <2 x i32> <i32 4, i32 -4>
; EXP-NEXT:    [[INCDEC_PTR2_I_I_20:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_19]], i32 4
; EXP-NEXT:    [[TMP50:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_20]], align 4
; EXP-NEXT:    [[TMP51:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_20]], align 4
; EXP-NEXT:    store float [[TMP51]], ptr [[INCDEC_PTR2_I_I_20]], align 4
; EXP-NEXT:    store float [[TMP50]], ptr [[__LAST_ADDR_0_I_I_20]], align 4
; EXP-NEXT:    [[TMP52:%.*]] = insertelement <2 x ptr> poison, ptr [[__LAST_ADDR_0_I_I_20]], i32 0
; EXP-NEXT:    [[TMP53:%.*]] = insertelement <2 x ptr> [[TMP52]], ptr [[INCDEC_PTR2_I_I_20]], i32 1
; EXP-NEXT:    [[TMP54:%.*]] = getelementptr i8, <2 x ptr> [[TMP53]], <2 x i32> <i32 -4, i32 4>
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_21:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_20]], i32 -4
; EXP-NEXT:    [[TMP55:%.*]] = getelementptr i8, <2 x ptr> [[TMP49]], <2 x i32> <i32 4, i32 -4>
; EXP-NEXT:    [[INCDEC_PTR2_I_I_21:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_20]], i32 4
; EXP-NEXT:    [[TMP56:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_21]], align 4
; EXP-NEXT:    [[TMP57:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_21]], align 4
; EXP-NEXT:    store float [[TMP57]], ptr [[INCDEC_PTR2_I_I_21]], align 4
; EXP-NEXT:    store float [[TMP56]], ptr [[__LAST_ADDR_0_I_I_21]], align 4
; EXP-NEXT:    [[TMP58:%.*]] = getelementptr i8, <2 x ptr> [[TMP54]], <2 x i32> <i32 -4, i32 4>
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_22:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_21]], i32 -4
; EXP-NEXT:    [[TMP59:%.*]] = getelementptr i8, <2 x ptr> [[TMP55]], <2 x i32> <i32 4, i32 -4>
; EXP-NEXT:    [[INCDEC_PTR2_I_I_22:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_21]], i32 4
; EXP-NEXT:    [[TMP60:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_22]], align 4
; EXP-NEXT:    [[TMP61:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_22]], align 4
; EXP-NEXT:    store float [[TMP61]], ptr [[INCDEC_PTR2_I_I_22]], align 4
; EXP-NEXT:    store float [[TMP60]], ptr [[__LAST_ADDR_0_I_I_22]], align 4
; EXP-NEXT:    [[TMP62:%.*]] = getelementptr i8, <2 x ptr> [[TMP58]], <2 x i32> <i32 -4, i32 4>
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_23:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_22]], i32 -4
; EXP-NEXT:    [[TMP63:%.*]] = getelementptr i8, <2 x ptr> [[TMP59]], <2 x i32> <i32 4, i32 -4>
; EXP-NEXT:    [[INCDEC_PTR2_I_I_23:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_22]], i32 4
; EXP-NEXT:    [[TMP64:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_23]], align 4
; EXP-NEXT:    [[TMP65:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_23]], align 4
; EXP-NEXT:    store float [[TMP65]], ptr [[INCDEC_PTR2_I_I_23]], align 4
; EXP-NEXT:    store float [[TMP64]], ptr [[__LAST_ADDR_0_I_I_23]], align 4
; EXP-NEXT:    [[TMP66:%.*]] = getelementptr i8, <2 x ptr> [[TMP62]], <2 x i32> <i32 -4, i32 4>
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_24:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_23]], i32 -4
; EXP-NEXT:    [[TMP67:%.*]] = getelementptr i8, <2 x ptr> [[TMP63]], <2 x i32> <i32 4, i32 -4>
; EXP-NEXT:    [[INCDEC_PTR2_I_I_24:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_23]], i32 4
; EXP-NEXT:    [[TMP68:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_24]], align 4
; EXP-NEXT:    [[TMP69:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_24]], align 4
; EXP-NEXT:    store float [[TMP69]], ptr [[INCDEC_PTR2_I_I_24]], align 4
; EXP-NEXT:    store float [[TMP68]], ptr [[__LAST_ADDR_0_I_I_24]], align 4
; EXP-NEXT:    [[TMP70:%.*]] = getelementptr i8, <2 x ptr> [[TMP66]], <2 x i32> <i32 -4, i32 4>
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_25:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_24]], i32 -4
; EXP-NEXT:    [[TMP71:%.*]] = getelementptr i8, <2 x ptr> [[TMP67]], <2 x i32> <i32 4, i32 -4>
; EXP-NEXT:    [[INCDEC_PTR2_I_I_25:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_24]], i32 4
; EXP-NEXT:    [[TMP72:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_25]], align 4
; EXP-NEXT:    [[TMP73:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_25]], align 4
; EXP-NEXT:    store float [[TMP73]], ptr [[INCDEC_PTR2_I_I_25]], align 4
; EXP-NEXT:    store float [[TMP72]], ptr [[__LAST_ADDR_0_I_I_25]], align 4
; EXP-NEXT:    [[TMP74:%.*]] = getelementptr i8, <2 x ptr> [[TMP70]], <2 x i32> <i32 -4, i32 4>
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_26:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_25]], i32 -4
; EXP-NEXT:    [[TMP75:%.*]] = getelementptr i8, <2 x ptr> [[TMP71]], <2 x i32> <i32 4, i32 -4>
; EXP-NEXT:    [[INCDEC_PTR2_I_I_26:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_25]], i32 4
; EXP-NEXT:    [[TMP76:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_26]], align 4
; EXP-NEXT:    [[TMP77:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_26]], align 4
; EXP-NEXT:    store float [[TMP77]], ptr [[INCDEC_PTR2_I_I_26]], align 4
; EXP-NEXT:    store float [[TMP76]], ptr [[__LAST_ADDR_0_I_I_26]], align 4
; EXP-NEXT:    [[TMP78:%.*]] = getelementptr i8, <2 x ptr> [[TMP74]], <2 x i32> <i32 -4, i32 4>
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_27:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_26]], i32 -4
; EXP-NEXT:    [[TMP79:%.*]] = getelementptr i8, <2 x ptr> [[TMP75]], <2 x i32> <i32 4, i32 -4>
; EXP-NEXT:    [[INCDEC_PTR2_I_I_27:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_26]], i32 4
; EXP-NEXT:    [[TMP80:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_27]], align 4
; EXP-NEXT:    [[TMP81:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_27]], align 4
; EXP-NEXT:    store float [[TMP81]], ptr [[INCDEC_PTR2_I_I_27]], align 4
; EXP-NEXT:    store float [[TMP80]], ptr [[__LAST_ADDR_0_I_I_27]], align 4
; EXP-NEXT:    [[TMP82:%.*]] = getelementptr i8, <2 x ptr> [[TMP78]], <2 x i32> <i32 -4, i32 4>
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_28:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_27]], i32 -4
; EXP-NEXT:    [[TMP83:%.*]] = getelementptr i8, <2 x ptr> [[TMP79]], <2 x i32> <i32 4, i32 -4>
; EXP-NEXT:    [[INCDEC_PTR2_I_I_28:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_27]], i32 4
; EXP-NEXT:    [[TMP84:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_28]], align 4
; EXP-NEXT:    [[TMP85:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_28]], align 4
; EXP-NEXT:    store float [[TMP85]], ptr [[INCDEC_PTR2_I_I_28]], align 4
; EXP-NEXT:    store float [[TMP84]], ptr [[__LAST_ADDR_0_I_I_28]], align 4
; EXP-NEXT:    [[TMP86:%.*]] = getelementptr i8, <2 x ptr> [[TMP82]], <2 x i32> <i32 -4, i32 4>
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_29:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_28]], i32 -4
; EXP-NEXT:    [[TMP87:%.*]] = getelementptr i8, <2 x ptr> [[TMP83]], <2 x i32> <i32 4, i32 -4>
; EXP-NEXT:    [[INCDEC_PTR2_I_I_29:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_28]], i32 4
; EXP-NEXT:    [[TMP88:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_29]], align 4
; EXP-NEXT:    [[TMP89:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_29]], align 4
; EXP-NEXT:    store float [[TMP89]], ptr [[INCDEC_PTR2_I_I_29]], align 4
; EXP-NEXT:    store float [[TMP88]], ptr [[__LAST_ADDR_0_I_I_29]], align 4
; EXP-NEXT:    [[TMP90:%.*]] = getelementptr i8, <2 x ptr> [[TMP86]], <2 x i32> <i32 -4, i32 4>
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_30:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_29]], i32 -4
; EXP-NEXT:    [[TMP91:%.*]] = getelementptr i8, <2 x ptr> [[TMP87]], <2 x i32> <i32 4, i32 -4>
; EXP-NEXT:    [[INCDEC_PTR2_I_I_30:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_29]], i32 4
; EXP-NEXT:    [[TMP92:%.*]] = load float, ptr [[INCDEC_PTR2_I_I_30]], align 4
; EXP-NEXT:    [[TMP93:%.*]] = load float, ptr [[__LAST_ADDR_0_I_I_30]], align 4
; EXP-NEXT:    store float [[TMP93]], ptr [[INCDEC_PTR2_I_I_30]], align 4
; EXP-NEXT:    store float [[TMP92]], ptr [[__LAST_ADDR_0_I_I_30]], align 4
; EXP-NEXT:    [[TMP94]] = getelementptr i8, <2 x ptr> [[TMP90]], <2 x i32> <i32 -4, i32 4>
; EXP-NEXT:    [[__LAST_ADDR_0_I_I_31:%.*]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I_I_30]], i32 -4
; EXP-NEXT:    [[TMP95:%.*]] = getelementptr i8, <2 x ptr> [[TMP91]], <2 x i32> <i32 4, i32 -4>
; EXP-NEXT:    [[INCDEC_PTR2_I_I_31:%.*]] = getelementptr inbounds nuw i8, ptr [[INCDEC_PTR2_I_I_30]], i32 4
; EXP-NEXT:    [[CMP1_I_I_31:%.*]] = icmp ult ptr [[INCDEC_PTR2_I_I_31]], [[__LAST_ADDR_0_I_I_31]]
; EXP-NEXT:    br i1 [[CMP1_I_I_31]], label %[[WHILE_BODY_I_I]], label %[[INVOKE_CONT21_EXITSTUB:.*]]
; EXP:       [[INVOKE_CONT21_EXITSTUB]]:
; EXP-NEXT:    ret void
;
newFuncRoot:
  br label %while.body.i.i

while.body.i.i:
  %__last.addr.014.i.i = phi ptr [ %__last.addr.011.i.i, %newFuncRoot ], [ %__last.addr.0.i.i.31, %while.body.i.i ]
  %__first.addr.013.i.i = phi ptr [ %call3, %newFuncRoot ], [ %incdec.ptr2.i.i.31, %while.body.i.i ]
  %0 = load float, ptr %__first.addr.013.i.i, align 4
  %1 = load float, ptr %__last.addr.014.i.i, align 4
  store float %1, ptr %__first.addr.013.i.i, align 4
  store float %0, ptr %__last.addr.014.i.i, align 4
  %incdec.ptr2.i.i = getelementptr inbounds nuw i8, ptr %__first.addr.013.i.i, i32 4
  %__last.addr.0.i.i = getelementptr inbounds i8, ptr %__last.addr.014.i.i, i32 -4
  %2 = load float, ptr %incdec.ptr2.i.i, align 4
  %3 = load float, ptr %__last.addr.0.i.i, align 4
  store float %3, ptr %incdec.ptr2.i.i, align 4
  store float %2, ptr %__last.addr.0.i.i, align 4
  %incdec.ptr2.i.i.1 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i, i32 4
  %__last.addr.0.i.i.1 = getelementptr inbounds i8, ptr %__last.addr.0.i.i, i32 -4
  %4 = load float, ptr %incdec.ptr2.i.i.1, align 4
  %5 = load float, ptr %__last.addr.0.i.i.1, align 4
  store float %5, ptr %incdec.ptr2.i.i.1, align 4
  store float %4, ptr %__last.addr.0.i.i.1, align 4
  %incdec.ptr2.i.i.2 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.1, i32 4
  %__last.addr.0.i.i.2 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.1, i32 -4
  %6 = load float, ptr %incdec.ptr2.i.i.2, align 4
  %7 = load float, ptr %__last.addr.0.i.i.2, align 4
  store float %7, ptr %incdec.ptr2.i.i.2, align 4
  store float %6, ptr %__last.addr.0.i.i.2, align 4
  %incdec.ptr2.i.i.3 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.2, i32 4
  %__last.addr.0.i.i.3 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.2, i32 -4
  %8 = load float, ptr %incdec.ptr2.i.i.3, align 4
  %9 = load float, ptr %__last.addr.0.i.i.3, align 4
  store float %9, ptr %incdec.ptr2.i.i.3, align 4
  store float %8, ptr %__last.addr.0.i.i.3, align 4
  %incdec.ptr2.i.i.4 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.3, i32 4
  %__last.addr.0.i.i.4 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.3, i32 -4
  %10 = load float, ptr %incdec.ptr2.i.i.4, align 4
  %11 = load float, ptr %__last.addr.0.i.i.4, align 4
  store float %11, ptr %incdec.ptr2.i.i.4, align 4
  store float %10, ptr %__last.addr.0.i.i.4, align 4
  %incdec.ptr2.i.i.5 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.4, i32 4
  %__last.addr.0.i.i.5 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.4, i32 -4
  %12 = load float, ptr %incdec.ptr2.i.i.5, align 4
  %13 = load float, ptr %__last.addr.0.i.i.5, align 4
  store float %13, ptr %incdec.ptr2.i.i.5, align 4
  store float %12, ptr %__last.addr.0.i.i.5, align 4
  %incdec.ptr2.i.i.6 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.5, i32 4
  %__last.addr.0.i.i.6 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.5, i32 -4
  %14 = load float, ptr %incdec.ptr2.i.i.6, align 4
  %15 = load float, ptr %__last.addr.0.i.i.6, align 4
  store float %15, ptr %incdec.ptr2.i.i.6, align 4
  store float %14, ptr %__last.addr.0.i.i.6, align 4
  %incdec.ptr2.i.i.7 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.6, i32 4
  %__last.addr.0.i.i.7 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.6, i32 -4
  %16 = load float, ptr %incdec.ptr2.i.i.7, align 4
  %17 = load float, ptr %__last.addr.0.i.i.7, align 4
  store float %17, ptr %incdec.ptr2.i.i.7, align 4
  store float %16, ptr %__last.addr.0.i.i.7, align 4
  %incdec.ptr2.i.i.8 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.7, i32 4
  %__last.addr.0.i.i.8 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.7, i32 -4
  %18 = load float, ptr %incdec.ptr2.i.i.8, align 4
  %19 = load float, ptr %__last.addr.0.i.i.8, align 4
  store float %19, ptr %incdec.ptr2.i.i.8, align 4
  store float %18, ptr %__last.addr.0.i.i.8, align 4
  %incdec.ptr2.i.i.9 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.8, i32 4
  %__last.addr.0.i.i.9 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.8, i32 -4
  %20 = load float, ptr %incdec.ptr2.i.i.9, align 4
  %21 = load float, ptr %__last.addr.0.i.i.9, align 4
  store float %21, ptr %incdec.ptr2.i.i.9, align 4
  store float %20, ptr %__last.addr.0.i.i.9, align 4
  %incdec.ptr2.i.i.10 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.9, i32 4
  %__last.addr.0.i.i.10 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.9, i32 -4
  %22 = load float, ptr %incdec.ptr2.i.i.10, align 4
  %23 = load float, ptr %__last.addr.0.i.i.10, align 4
  store float %23, ptr %incdec.ptr2.i.i.10, align 4
  store float %22, ptr %__last.addr.0.i.i.10, align 4
  %incdec.ptr2.i.i.11 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.10, i32 4
  %__last.addr.0.i.i.11 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.10, i32 -4
  %24 = load float, ptr %incdec.ptr2.i.i.11, align 4
  %25 = load float, ptr %__last.addr.0.i.i.11, align 4
  store float %25, ptr %incdec.ptr2.i.i.11, align 4
  store float %24, ptr %__last.addr.0.i.i.11, align 4
  %incdec.ptr2.i.i.12 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.11, i32 4
  %__last.addr.0.i.i.12 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.11, i32 -4
  %26 = load float, ptr %incdec.ptr2.i.i.12, align 4
  %27 = load float, ptr %__last.addr.0.i.i.12, align 4
  store float %27, ptr %incdec.ptr2.i.i.12, align 4
  store float %26, ptr %__last.addr.0.i.i.12, align 4
  %incdec.ptr2.i.i.13 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.12, i32 4
  %__last.addr.0.i.i.13 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.12, i32 -4
  %28 = load float, ptr %incdec.ptr2.i.i.13, align 4
  %29 = load float, ptr %__last.addr.0.i.i.13, align 4
  store float %29, ptr %incdec.ptr2.i.i.13, align 4
  store float %28, ptr %__last.addr.0.i.i.13, align 4
  %incdec.ptr2.i.i.14 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.13, i32 4
  %__last.addr.0.i.i.14 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.13, i32 -4
  %30 = load float, ptr %incdec.ptr2.i.i.14, align 4
  %31 = load float, ptr %__last.addr.0.i.i.14, align 4
  store float %31, ptr %incdec.ptr2.i.i.14, align 4
  store float %30, ptr %__last.addr.0.i.i.14, align 4
  %incdec.ptr2.i.i.15 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.14, i32 4
  %__last.addr.0.i.i.15 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.14, i32 -4
  %32 = load float, ptr %incdec.ptr2.i.i.15, align 4
  %33 = load float, ptr %__last.addr.0.i.i.15, align 4
  store float %33, ptr %incdec.ptr2.i.i.15, align 4
  store float %32, ptr %__last.addr.0.i.i.15, align 4
  %incdec.ptr2.i.i.16 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.15, i32 4
  %__last.addr.0.i.i.16 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.15, i32 -4
  %34 = load float, ptr %incdec.ptr2.i.i.16, align 4
  %35 = load float, ptr %__last.addr.0.i.i.16, align 4
  store float %35, ptr %incdec.ptr2.i.i.16, align 4
  store float %34, ptr %__last.addr.0.i.i.16, align 4
  %incdec.ptr2.i.i.17 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.16, i32 4
  %__last.addr.0.i.i.17 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.16, i32 -4
  %36 = load float, ptr %incdec.ptr2.i.i.17, align 4
  %37 = load float, ptr %__last.addr.0.i.i.17, align 4
  store float %37, ptr %incdec.ptr2.i.i.17, align 4
  store float %36, ptr %__last.addr.0.i.i.17, align 4
  %incdec.ptr2.i.i.18 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.17, i32 4
  %__last.addr.0.i.i.18 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.17, i32 -4
  %38 = load float, ptr %incdec.ptr2.i.i.18, align 4
  %39 = load float, ptr %__last.addr.0.i.i.18, align 4
  store float %39, ptr %incdec.ptr2.i.i.18, align 4
  store float %38, ptr %__last.addr.0.i.i.18, align 4
  %incdec.ptr2.i.i.19 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.18, i32 4
  %__last.addr.0.i.i.19 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.18, i32 -4
  %40 = load float, ptr %incdec.ptr2.i.i.19, align 4
  %41 = load float, ptr %__last.addr.0.i.i.19, align 4
  store float %41, ptr %incdec.ptr2.i.i.19, align 4
  store float %40, ptr %__last.addr.0.i.i.19, align 4
  %incdec.ptr2.i.i.20 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.19, i32 4
  %__last.addr.0.i.i.20 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.19, i32 -4
  %42 = load float, ptr %incdec.ptr2.i.i.20, align 4
  %43 = load float, ptr %__last.addr.0.i.i.20, align 4
  store float %43, ptr %incdec.ptr2.i.i.20, align 4
  store float %42, ptr %__last.addr.0.i.i.20, align 4
  %incdec.ptr2.i.i.21 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.20, i32 4
  %__last.addr.0.i.i.21 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.20, i32 -4
  %44 = load float, ptr %incdec.ptr2.i.i.21, align 4
  %45 = load float, ptr %__last.addr.0.i.i.21, align 4
  store float %45, ptr %incdec.ptr2.i.i.21, align 4
  store float %44, ptr %__last.addr.0.i.i.21, align 4
  %incdec.ptr2.i.i.22 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.21, i32 4
  %__last.addr.0.i.i.22 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.21, i32 -4
  %46 = load float, ptr %incdec.ptr2.i.i.22, align 4
  %47 = load float, ptr %__last.addr.0.i.i.22, align 4
  store float %47, ptr %incdec.ptr2.i.i.22, align 4
  store float %46, ptr %__last.addr.0.i.i.22, align 4
  %incdec.ptr2.i.i.23 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.22, i32 4
  %__last.addr.0.i.i.23 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.22, i32 -4
  %48 = load float, ptr %incdec.ptr2.i.i.23, align 4
  %49 = load float, ptr %__last.addr.0.i.i.23, align 4
  store float %49, ptr %incdec.ptr2.i.i.23, align 4
  store float %48, ptr %__last.addr.0.i.i.23, align 4
  %incdec.ptr2.i.i.24 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.23, i32 4
  %__last.addr.0.i.i.24 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.23, i32 -4
  %50 = load float, ptr %incdec.ptr2.i.i.24, align 4
  %51 = load float, ptr %__last.addr.0.i.i.24, align 4
  store float %51, ptr %incdec.ptr2.i.i.24, align 4
  store float %50, ptr %__last.addr.0.i.i.24, align 4
  %incdec.ptr2.i.i.25 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.24, i32 4
  %__last.addr.0.i.i.25 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.24, i32 -4
  %52 = load float, ptr %incdec.ptr2.i.i.25, align 4
  %53 = load float, ptr %__last.addr.0.i.i.25, align 4
  store float %53, ptr %incdec.ptr2.i.i.25, align 4
  store float %52, ptr %__last.addr.0.i.i.25, align 4
  %incdec.ptr2.i.i.26 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.25, i32 4
  %__last.addr.0.i.i.26 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.25, i32 -4
  %54 = load float, ptr %incdec.ptr2.i.i.26, align 4
  %55 = load float, ptr %__last.addr.0.i.i.26, align 4
  store float %55, ptr %incdec.ptr2.i.i.26, align 4
  store float %54, ptr %__last.addr.0.i.i.26, align 4
  %incdec.ptr2.i.i.27 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.26, i32 4
  %__last.addr.0.i.i.27 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.26, i32 -4
  %56 = load float, ptr %incdec.ptr2.i.i.27, align 4
  %57 = load float, ptr %__last.addr.0.i.i.27, align 4
  store float %57, ptr %incdec.ptr2.i.i.27, align 4
  store float %56, ptr %__last.addr.0.i.i.27, align 4
  %incdec.ptr2.i.i.28 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.27, i32 4
  %__last.addr.0.i.i.28 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.27, i32 -4
  %58 = load float, ptr %incdec.ptr2.i.i.28, align 4
  %59 = load float, ptr %__last.addr.0.i.i.28, align 4
  store float %59, ptr %incdec.ptr2.i.i.28, align 4
  store float %58, ptr %__last.addr.0.i.i.28, align 4
  %incdec.ptr2.i.i.29 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.28, i32 4
  %__last.addr.0.i.i.29 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.28, i32 -4
  %60 = load float, ptr %incdec.ptr2.i.i.29, align 4
  %61 = load float, ptr %__last.addr.0.i.i.29, align 4
  store float %61, ptr %incdec.ptr2.i.i.29, align 4
  store float %60, ptr %__last.addr.0.i.i.29, align 4
  %incdec.ptr2.i.i.30 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.29, i32 4
  %__last.addr.0.i.i.30 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.29, i32 -4
  %62 = load float, ptr %incdec.ptr2.i.i.30, align 4
  %63 = load float, ptr %__last.addr.0.i.i.30, align 4
  store float %63, ptr %incdec.ptr2.i.i.30, align 4
  store float %62, ptr %__last.addr.0.i.i.30, align 4
  %incdec.ptr2.i.i.31 = getelementptr inbounds nuw i8, ptr %incdec.ptr2.i.i.30, i32 4
  %__last.addr.0.i.i.31 = getelementptr inbounds i8, ptr %__last.addr.0.i.i.30, i32 -4
  %cmp1.i.i.31 = icmp ult ptr %incdec.ptr2.i.i.31, %__last.addr.0.i.i.31
  br i1 %cmp1.i.i.31, label %while.body.i.i, label %invoke.cont21.exitStub

invoke.cont21.exitStub:
  ret void
}
