; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=slp-vectorizer -mtriple=riscv64 -mattr=+v -slp-threshold=-5 -S | FileCheck %s

; Not profitable with VF=4, but we only we try smaller VFs if the load can fit in a single vector
; register found by BoUpSLP::getVectorElementSize(). Requires proprogation of bit widths through
; the fmuladd intrinsic
define void @bar(ptr %0, i64 %1, double %2, i64 %3, double %4, double %5, double %6, double %7, double %8) {
; CHECK-LABEL: define void @bar(
; CHECK-SAME: ptr [[TMP0:%.*]], i64 [[TMP1:%.*]], double [[TMP2:%.*]], i64 [[TMP3:%.*]], double [[TMP4:%.*]], double [[TMP5:%.*]], double [[TMP6:%.*]], double [[TMP7:%.*]], double [[TMP8:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[E:.*]]:
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw [8 x i8], ptr [[TMP0]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP9]], i64 6
; CHECK-NEXT:    [[TMP11:%.*]] = add i64 [[TMP3]], 1
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP9]], i64 2
; CHECK-NEXT:    [[TMP13:%.*]] = load <2 x i16>, ptr [[TMP12]], align 2
; CHECK-NEXT:    [[TMP14:%.*]] = uitofp <2 x i16> [[TMP13]] to <2 x double>
; CHECK-NEXT:    [[TMP15:%.*]] = call <2 x i16> @llvm.experimental.vp.strided.load.v2i16.p0.i64(ptr align 2 [[TMP9]], i64 6, <2 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    [[TMP16:%.*]] = load i16, ptr [[TMP10]], align 2
; CHECK-NEXT:    [[TMP17:%.*]] = xor i16 [[TMP16]], -1
; CHECK-NEXT:    [[TMP18:%.*]] = uitofp i16 [[TMP17]] to double
; CHECK-NEXT:    [[TMP19:%.*]] = fmul nnan double [[TMP18]], f0x3EF0001000100010
; CHECK-NEXT:    [[TMP20:%.*]] = fmul double [[TMP2]], [[TMP19]]
; CHECK-NEXT:    [[TMP21:%.*]] = fadd double [[TMP4]], [[TMP20]]
; CHECK-NEXT:    [[TMP22:%.*]] = insertelement <2 x double> poison, double [[TMP20]], i32 0
; CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <2 x double> [[TMP22]], <2 x double> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP24:%.*]] = insertelement <2 x double> poison, double [[TMP6]], i32 0
; CHECK-NEXT:    [[TMP25:%.*]] = insertelement <2 x double> [[TMP24]], double [[TMP5]], i32 1
; CHECK-NEXT:    [[TMP26:%.*]] = call <2 x double> @llvm.fmuladd.v2f64(<2 x double> [[TMP23]], <2 x double> [[TMP14]], <2 x double> [[TMP25]])
; CHECK-NEXT:    [[TMP27:%.*]] = uitofp <2 x i16> [[TMP15]] to <2 x double>
; CHECK-NEXT:    [[TMP28:%.*]] = insertelement <2 x double> poison, double [[TMP2]], i32 1
; CHECK-NEXT:    [[TMP29:%.*]] = insertelement <2 x double> [[TMP28]], double [[TMP20]], i32 0
; CHECK-NEXT:    [[TMP30:%.*]] = insertelement <2 x double> poison, double [[TMP7]], i32 0
; CHECK-NEXT:    [[TMP31:%.*]] = insertelement <2 x double> [[TMP30]], double [[TMP8]], i32 1
; CHECK-NEXT:    [[TMP32:%.*]] = call <2 x double> @llvm.fmuladd.v2f64(<2 x double> [[TMP29]], <2 x double> [[TMP27]], <2 x double> [[TMP31]])
; CHECK-NEXT:    br label %[[R:.*]]
; CHECK:       [[R]]:
; CHECK-NEXT:    [[TMP33:%.*]] = phi <2 x double> [ [[TMP32]], %[[E]] ]
; CHECK-NEXT:    [[TMP34:%.*]] = phi <2 x double> [ [[TMP26]], %[[E]] ]
; CHECK-NEXT:    ret void
;
e:
  %2652 = getelementptr inbounds nuw [8 x i8], ptr %0, i64 %1
  %2653 = getelementptr inbounds nuw i8, ptr %2652, i64 6
  %2654 = load i16, ptr %2653, align 2
  %2655 = xor i16 %2654, -1
  %2656 = uitofp i16 %2655 to double
  %2657 = fmul nnan double %2656, f0x3EF0001000100010
  %2658 = add i64 %3, 1
  %2659 = fmul double %2, %2657
  %2660 = fadd double %4, %2659
  %2661 = getelementptr inbounds nuw i8, ptr %2652, i64 4
  %2662 = load i16, ptr %2661, align 2
  %2663 = uitofp i16 %2662 to double
  %2664 = call double @llvm.fmuladd.f64(double %2659, double %2663, double %5)
  %2665 = getelementptr inbounds nuw i8, ptr %2652, i64 2
  %2666 = load i16, ptr %2665, align 2
  %2667 = uitofp i16 %2666 to double
  %2668 = call double @llvm.fmuladd.f64(double %2659, double %2667, double %6)
  %2669 = load i16, ptr %2652, align 2
  %2670 = uitofp i16 %2669 to double
  %2671 = call double @llvm.fmuladd.f64(double %2659, double %2670, double %7)
  %2672 = uitofp i16 %2654 to double
  %2673 = call double @llvm.fmuladd.f64(double %2, double %2672, double %8)
  br label %r
r:
  %d0 = phi double [ %2673, %e ]
  %d1 = phi double [ %2671, %e ]
  %d2 = phi double [ %2668, %e ]
  %d3 = phi double [ %2664, %e ]
  ret void
}
