; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S --passes=slp-vectorizer -mtriple=riscv64-unknown-linux -mattr=+v < %s | FileCheck %s

define void @test(ptr %dest) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[DEST:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[INC3:%.*]] = getelementptr inbounds i32, ptr [[DEST]], i64 3
; CHECK-NEXT:    store i32 1, ptr [[INC3]], align 2
; CHECK-NEXT:    store i32 1, ptr [[DEST]], align 4
; CHECK-NEXT:    [[INC1:%.*]] = getelementptr inbounds i32, ptr [[DEST]], i64 1
; CHECK-NEXT:    store i32 1, ptr [[INC1]], align 2
; CHECK-NEXT:    [[INC2:%.*]] = getelementptr inbounds i32, ptr [[DEST]], i64 2
; CHECK-NEXT:    store i32 1, ptr [[INC2]], align 2
; CHECK-NEXT:    store i32 2, ptr [[DEST]], align 2
; CHECK-NEXT:    store i32 1, ptr [[INC3]], align 2
; CHECK-NEXT:    ret void
;
entry:
  %inc3 = getelementptr inbounds i32, ptr %dest, i64 3
  store i32 1, ptr %inc3, align 2

  store i32 1, ptr %dest, align 4
  %inc1 = getelementptr inbounds i32, ptr %dest, i64 1
  store i32 1, ptr %inc1, align 2
  %inc2 = getelementptr inbounds i32, ptr %dest, i64 2
  store i32 1, ptr %inc2, align 2
  store i32 2, ptr %dest, align 2
  store i32 1, ptr %inc3, align 2
  ret void
}
