; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple=riscv64 -mcpu=sifive-p870-d -passes=slp-vectorizer -S -slp-revec -slp-enable-strided-stores -slp-threshold=-100 %s | FileCheck %s

; Strided load into strided store
define void @strided_load_and_store(ptr %in, ptr %out) {
; CHECK-LABEL: @strided_load_and_store(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <2 x i64> @llvm.experimental.vp.strided.load.v2i64.p0.i64(ptr align 2 [[IN:%.*]], i64 16, <2 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <2 x i64> [[TMP0]] to <16 x i8>
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP4]] to <2 x i64>
; CHECK-NEXT:    call void @llvm.experimental.vp.strided.store.v2i64.p0.i64(<2 x i64> [[TMP2]], ptr align 2 [[OUT:%.*]], i64 16, <2 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    ret void
;
entry:
  %0 = getelementptr i8, ptr %in, i64 16
  %1 = load <8 x i8>, ptr %in, align 2
  %2 = load <8 x i8>, ptr %0, align 2
  %5 = getelementptr i8, ptr %out, i64 16
  store <8 x i8> %1, ptr %out, align 2
  store <8 x i8> %2, ptr %5, align 2
  ret void
}

; Base case of strided store, implicitly is widened
define void @widened_strided_store(ptr %out0) {
; CHECK-LABEL: @widened_strided_store(
; CHECK-NEXT:    call void @llvm.experimental.vp.strided.store.v2i64.p0.i64(<2 x i64> zeroinitializer, ptr align 2 null, i64 32, <2 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    ret void
;
  %1 = getelementptr i16, ptr null, i64 16
  store <4 x i16> zeroinitializer, ptr %1, align 2
  store <4 x i16> zeroinitializer, ptr null, align 2
  ret void
}

; Widened strided store pattern but vectorized types
define void @doubly_widened_strided_store(ptr %out0) {
; CHECK-LABEL: @doubly_widened_strided_store(
; CHECK-NEXT:    [[OUT2:%.*]] = getelementptr i8, ptr [[OUT0:%.*]], i64 12
; CHECK-NEXT:    store <4 x i8> zeroinitializer, ptr [[OUT0]], align 2
; CHECK-NEXT:    store <4 x i8> zeroinitializer, ptr [[OUT2]], align 2
; CHECK-NEXT:    ret void
;
  %out1 = getelementptr i8, ptr %out0, i64 2
  %out2 = getelementptr i8, ptr %out0, i64 12
  %out3 = getelementptr i8, ptr %out0, i64 14
  store <2 x i8> zeroinitializer, ptr %out0, align 2
  store <2 x i8> zeroinitializer, ptr %out1, align 2
  store <2 x i8> zeroinitializer, ptr %out2, align 2
  store <2 x i8> zeroinitializer, ptr %out3, align 2
  ret void
}

; The resulting widened type isn't legal
define void @too_wide(ptr %out0) {
; CHECK-LABEL: @too_wide(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    store <16 x i16> zeroinitializer, ptr [[OUT0:%.*]], align 2
; CHECK-NEXT:    ret void
;
entry:
  %out1 = getelementptr i16, ptr %out0, i64 8
  store <8 x i16> zeroinitializer, ptr %out0, align 2
  store <8 x i16> zeroinitializer, ptr %out1, align 2
  ret void
}

; Stride size isn't aligned to the vector size
define void @non_aligned_stride(ptr %out0) {
; CHECK-LABEL: @non_aligned_stride(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[OUT1:%.*]] = getelementptr i8, ptr [[OUT0:%.*]], i64 3
; CHECK-NEXT:    store <2 x i8> zeroinitializer, ptr [[OUT0]], align 2
; CHECK-NEXT:    store <2 x i8> zeroinitializer, ptr [[OUT1]], align 2
; CHECK-NEXT:    ret void
;
entry:
  %out1 = getelementptr i8, ptr %out0, i64 3
  store <2 x i8> zeroinitializer, ptr %out0, align 2
  store <2 x i8> zeroinitializer, ptr %out1, align 2
  ret void
}

; Stride size isn't aligned to the vector size
; Scalar version of @non_aligned_stride
define void @non_aligned_stride_scalar(ptr %out0) {
; CHECK-LABEL: @non_aligned_stride_scalar(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[OUT2:%.*]] = getelementptr i8, ptr [[OUT0:%.*]], i64 3
; CHECK-NEXT:    store <2 x i8> zeroinitializer, ptr [[OUT0]], align 2
; CHECK-NEXT:    store <2 x i8> zeroinitializer, ptr [[OUT2]], align 2
; CHECK-NEXT:    ret void
;
entry:
  %out1 = getelementptr i8, ptr %out0, i64 1
  %out2 = getelementptr i8, ptr %out0, i64 3
  %out3 = getelementptr i8, ptr %out0, i64 4
  store i8 0, ptr %out0, align 2
  store i8 0, ptr %out1, align 2
  store i8 0, ptr %out2, align 2
  store i8 0, ptr %out3, align 2
  ret void
}
