; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=slp-vectorizer -mtriple=riscv64 -mattr=+v -S | FileCheck %s

define void @test_max_reg_vf_boundary(ptr %pl, ptr %ps) {
; CHECK-LABEL: define void @test_max_reg_vf_boundary(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[GEP_L_UNRELATED_1:%.*]] = getelementptr inbounds i32, ptr [[PL]], i32 100
; CHECK-NEXT:    [[GEP_L_UNRELATED_2:%.*]] = getelementptr inbounds i32, ptr [[PL]], i32 200
; CHECK-NEXT:    [[GEP_L_CONTIGUOUS:%.*]] = getelementptr inbounds i32, ptr [[PL]], i32 2
; CHECK-NEXT:    [[GEP_L_OP_MISMATCH_1:%.*]] = getelementptr inbounds i32, ptr [[PL]], i32 300
; CHECK-NEXT:    [[GEP_L_OP_MISMATCH_2:%.*]] = getelementptr inbounds i32, ptr [[PL]], i32 400
; CHECK-NEXT:    [[LOAD0:%.*]] = load i32, ptr [[GEP_L_UNRELATED_1]], align 4
; CHECK-NEXT:    [[LOAD1:%.*]] = load i32, ptr [[GEP_L_UNRELATED_2]], align 4
; CHECK-NEXT:    [[LOAD6:%.*]] = load i32, ptr [[GEP_L_OP_MISMATCH_1]], align 4
; CHECK-NEXT:    [[LOAD7:%.*]] = load i32, ptr [[GEP_L_OP_MISMATCH_2]], align 4
; CHECK-NEXT:    [[ADD6:%.*]] = add i32 [[LOAD6]], 1
; CHECK-NEXT:    [[ADD7:%.*]] = add i32 [[LOAD7]], 1
; CHECK-NEXT:    [[GEP_S0:%.*]] = getelementptr inbounds i32, ptr [[PS]], i32 0
; CHECK-NEXT:    [[GEP_S1:%.*]] = getelementptr inbounds i32, ptr [[PS]], i32 1
; CHECK-NEXT:    [[GEP_S2:%.*]] = getelementptr inbounds i32, ptr [[PS]], i32 2
; CHECK-NEXT:    [[GEP_S6:%.*]] = getelementptr inbounds i32, ptr [[PS]], i32 6
; CHECK-NEXT:    [[GEP_S7:%.*]] = getelementptr inbounds i32, ptr [[PS]], i32 7
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr [[GEP_L_CONTIGUOUS]], align 4
; CHECK-NEXT:    store i32 [[LOAD0]], ptr [[GEP_S0]], align 4
; CHECK-NEXT:    store i32 [[LOAD1]], ptr [[GEP_S1]], align 4
; CHECK-NEXT:    store <4 x i32> [[TMP1]], ptr [[GEP_S2]], align 4
; CHECK-NEXT:    store i32 [[ADD6]], ptr [[GEP_S6]], align 4
; CHECK-NEXT:    store i32 [[ADD7]], ptr [[GEP_S7]], align 4
; CHECK-NEXT:    ret void
;


  %gep_l_unrelated_1 = getelementptr inbounds i32, ptr %pl, i32 100
  %gep_l_unrelated_2 = getelementptr inbounds i32, ptr %pl, i32 200

  ; contagious loads- to fit exactly one register
  %gep_l_contiguous = getelementptr inbounds i32, ptr %pl, i32 2
  %gep_l3 = getelementptr inbounds i32, ptr %pl, i32 3
  %gep_l4 = getelementptr inbounds i32, ptr %pl, i32 4
  %gep_l5 = getelementptr inbounds i32, ptr %pl, i32 5

  %gep_l_op_mismatch_1 = getelementptr inbounds i32, ptr %pl, i32 300
  %gep_l_op_mismatch_2 = getelementptr inbounds i32, ptr %pl, i32 400

  %load0 = load i32, ptr %gep_l_unrelated_1, align 4
  %load1 = load i32, ptr %gep_l_unrelated_2, align 4
  %load2 = load i32, ptr %gep_l_contiguous, align 4
  %load3 = load i32, ptr %gep_l3, align 4
  %load4 = load i32, ptr %gep_l4, align 4
  %load5 = load i32, ptr %gep_l5, align 4
  %load6 = load i32, ptr %gep_l_op_mismatch_1, align 4
  %load7 = load i32, ptr %gep_l_op_mismatch_2, align 4
  %add6 = add i32 %load6, 1
  %add7 = add i32 %load7, 1

  %gep_s0 = getelementptr inbounds i32, ptr %ps, i32 0
  %gep_s1 = getelementptr inbounds i32, ptr %ps, i32 1
  %gep_s2 = getelementptr inbounds i32, ptr %ps, i32 2
  %gep_s3 = getelementptr inbounds i32, ptr %ps, i32 3
  %gep_s4 = getelementptr inbounds i32, ptr %ps, i32 4
  %gep_s5 = getelementptr inbounds i32, ptr %ps, i32 5
  %gep_s6 = getelementptr inbounds i32, ptr %ps, i32 6
  %gep_s7 = getelementptr inbounds i32, ptr %ps, i32 7

  store i32 %load0, ptr %gep_s0, align 4
  store i32 %load1, ptr %gep_s1, align 4
  store i32 %load2, ptr %gep_s2, align 4
  store i32 %load3, ptr %gep_s3, align 4
  store i32 %load4, ptr %gep_s4, align 4
  store i32 %load5, ptr %gep_s5, align 4
  store i32 %add6, ptr %gep_s6, align 4
  store i32 %add7, ptr %gep_s7, align 4

  ret void

}
