; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S -mattr=+v -mtriple=riscv64-unknown-unknown < %s | FileCheck %s

define i32 @test(ptr %pix1, i32 %i_pix1, ptr %pix2, i32 %i_pix2) {
; CHECK-LABEL: define i32 @test(
; CHECK-SAME: ptr [[PIX1:%.*]], i32 [[I_PIX1:%.*]], ptr [[PIX2:%.*]], i32 [[I_PIX2:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[I_PIX1]] to i64
; CHECK-NEXT:    [[IDX_EXT31:%.*]] = sext i32 [[I_PIX2]] to i64
; CHECK-NEXT:    [[TMP0:%.*]] = load <4 x i8>, ptr [[PIX1]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i8> [[TMP0]], <4 x i8> poison, <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP2:%.*]] = zext <2 x i8> [[TMP1]] to <2 x i32>
; CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i8>, ptr [[PIX2]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i8> [[TMP3]], <4 x i8> poison, <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP5:%.*]] = zext <2 x i8> [[TMP4]] to <2 x i32>
; CHECK-NEXT:    [[TMP6:%.*]] = sub nsw <2 x i32> [[TMP2]], [[TMP5]]
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <4 x i8> [[TMP0]], <4 x i8> poison, <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP8:%.*]] = zext <2 x i8> [[TMP7]] to <2 x i32>
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i8> [[TMP3]], <4 x i8> poison, <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP10:%.*]] = zext <2 x i8> [[TMP9]] to <2 x i32>
; CHECK-NEXT:    [[TMP11:%.*]] = sub nsw <2 x i32> [[TMP8]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = add nsw <2 x i32> [[TMP11]], [[TMP6]]
; CHECK-NEXT:    [[TMP13:%.*]] = sub nsw <2 x i32> [[TMP6]], [[TMP11]]
; CHECK-NEXT:    [[TMP14:%.*]] = shl nsw <2 x i32> [[TMP13]], splat (i32 16)
; CHECK-NEXT:    [[TMP15:%.*]] = add nsw <2 x i32> [[TMP12]], [[TMP14]]
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[PIX1]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[ADD_PTR32:%.*]] = getelementptr inbounds i8, ptr [[PIX2]], i64 [[IDX_EXT31]]
; CHECK-NEXT:    [[TMP16:%.*]] = load <4 x i8>, ptr [[ADD_PTR]], align 1
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <4 x i8> [[TMP16]], <4 x i8> poison, <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP18:%.*]] = zext <2 x i8> [[TMP17]] to <2 x i32>
; CHECK-NEXT:    [[TMP19:%.*]] = load <4 x i8>, ptr [[ADD_PTR32]], align 1
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <4 x i8> [[TMP19]], <4 x i8> poison, <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP21:%.*]] = zext <2 x i8> [[TMP20]] to <2 x i32>
; CHECK-NEXT:    [[TMP22:%.*]] = sub nsw <2 x i32> [[TMP18]], [[TMP21]]
; CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <4 x i8> [[TMP16]], <4 x i8> poison, <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP24:%.*]] = zext <2 x i8> [[TMP23]] to <2 x i32>
; CHECK-NEXT:    [[TMP25:%.*]] = shufflevector <4 x i8> [[TMP19]], <4 x i8> poison, <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP26:%.*]] = zext <2 x i8> [[TMP25]] to <2 x i32>
; CHECK-NEXT:    [[TMP27:%.*]] = sub nsw <2 x i32> [[TMP24]], [[TMP26]]
; CHECK-NEXT:    [[TMP28:%.*]] = add nsw <2 x i32> [[TMP27]], [[TMP22]]
; CHECK-NEXT:    [[TMP29:%.*]] = sub nsw <2 x i32> [[TMP22]], [[TMP27]]
; CHECK-NEXT:    [[TMP30:%.*]] = shl nsw <2 x i32> [[TMP29]], splat (i32 16)
; CHECK-NEXT:    [[TMP31:%.*]] = add nsw <2 x i32> [[TMP28]], [[TMP30]]
; CHECK-NEXT:    [[ADD_PTR_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[ADD_PTR32_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR32]], i64 [[IDX_EXT31]]
; CHECK-NEXT:    [[TMP32:%.*]] = load <4 x i8>, ptr [[ADD_PTR_1]], align 1
; CHECK-NEXT:    [[TMP33:%.*]] = shufflevector <4 x i8> [[TMP32]], <4 x i8> poison, <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP34:%.*]] = zext <2 x i8> [[TMP33]] to <2 x i32>
; CHECK-NEXT:    [[TMP35:%.*]] = load <4 x i8>, ptr [[ADD_PTR32_1]], align 1
; CHECK-NEXT:    [[TMP36:%.*]] = shufflevector <4 x i8> [[TMP35]], <4 x i8> poison, <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP37:%.*]] = zext <2 x i8> [[TMP36]] to <2 x i32>
; CHECK-NEXT:    [[TMP38:%.*]] = sub nsw <2 x i32> [[TMP34]], [[TMP37]]
; CHECK-NEXT:    [[TMP39:%.*]] = shufflevector <4 x i8> [[TMP32]], <4 x i8> poison, <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP40:%.*]] = zext <2 x i8> [[TMP39]] to <2 x i32>
; CHECK-NEXT:    [[TMP41:%.*]] = shufflevector <4 x i8> [[TMP35]], <4 x i8> poison, <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP42:%.*]] = zext <2 x i8> [[TMP41]] to <2 x i32>
; CHECK-NEXT:    [[TMP43:%.*]] = sub nsw <2 x i32> [[TMP40]], [[TMP42]]
; CHECK-NEXT:    [[TMP44:%.*]] = add nsw <2 x i32> [[TMP43]], [[TMP38]]
; CHECK-NEXT:    [[TMP45:%.*]] = sub nsw <2 x i32> [[TMP38]], [[TMP43]]
; CHECK-NEXT:    [[TMP46:%.*]] = shl nsw <2 x i32> [[TMP45]], splat (i32 16)
; CHECK-NEXT:    [[TMP47:%.*]] = add nsw <2 x i32> [[TMP44]], [[TMP46]]
; CHECK-NEXT:    [[ADD_PTR_2:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_1]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[ADD_PTR32_2:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR32_1]], i64 [[IDX_EXT31]]
; CHECK-NEXT:    [[TMP48:%.*]] = load <4 x i8>, ptr [[ADD_PTR_2]], align 1
; CHECK-NEXT:    [[TMP49:%.*]] = shufflevector <4 x i8> [[TMP48]], <4 x i8> poison, <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP50:%.*]] = zext <2 x i8> [[TMP49]] to <2 x i32>
; CHECK-NEXT:    [[TMP51:%.*]] = load <4 x i8>, ptr [[ADD_PTR32_2]], align 1
; CHECK-NEXT:    [[TMP52:%.*]] = shufflevector <4 x i8> [[TMP51]], <4 x i8> poison, <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP53:%.*]] = zext <2 x i8> [[TMP52]] to <2 x i32>
; CHECK-NEXT:    [[TMP54:%.*]] = sub nsw <2 x i32> [[TMP50]], [[TMP53]]
; CHECK-NEXT:    [[TMP55:%.*]] = shufflevector <4 x i8> [[TMP48]], <4 x i8> poison, <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP56:%.*]] = zext <2 x i8> [[TMP55]] to <2 x i32>
; CHECK-NEXT:    [[TMP57:%.*]] = shufflevector <4 x i8> [[TMP51]], <4 x i8> poison, <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP58:%.*]] = zext <2 x i8> [[TMP57]] to <2 x i32>
; CHECK-NEXT:    [[TMP59:%.*]] = sub nsw <2 x i32> [[TMP56]], [[TMP58]]
; CHECK-NEXT:    [[TMP60:%.*]] = add nsw <2 x i32> [[TMP59]], [[TMP54]]
; CHECK-NEXT:    [[TMP61:%.*]] = sub nsw <2 x i32> [[TMP54]], [[TMP59]]
; CHECK-NEXT:    [[TMP62:%.*]] = shl nsw <2 x i32> [[TMP61]], splat (i32 16)
; CHECK-NEXT:    [[TMP63:%.*]] = add nsw <2 x i32> [[TMP60]], [[TMP62]]
; CHECK-NEXT:    [[TMP64:%.*]] = extractelement <2 x i32> [[TMP15]], i32 0
; CHECK-NEXT:    [[TMP65:%.*]] = extractelement <2 x i32> [[TMP15]], i32 1
; CHECK-NEXT:    [[SUB27:%.*]] = sub nsw i32 [[TMP64]], [[TMP65]]
; CHECK-NEXT:    [[ADD24:%.*]] = add nsw i32 [[TMP65]], [[TMP64]]
; CHECK-NEXT:    [[TMP66:%.*]] = extractelement <2 x i32> [[TMP31]], i32 0
; CHECK-NEXT:    [[TMP67:%.*]] = extractelement <2 x i32> [[TMP31]], i32 1
; CHECK-NEXT:    [[SUB27_1:%.*]] = sub nsw i32 [[TMP66]], [[TMP67]]
; CHECK-NEXT:    [[ADD24_1:%.*]] = add nsw i32 [[TMP67]], [[TMP66]]
; CHECK-NEXT:    [[TMP68:%.*]] = extractelement <2 x i32> [[TMP47]], i32 0
; CHECK-NEXT:    [[TMP69:%.*]] = extractelement <2 x i32> [[TMP47]], i32 1
; CHECK-NEXT:    [[SUB27_2:%.*]] = sub nsw i32 [[TMP68]], [[TMP69]]
; CHECK-NEXT:    [[ADD24_2:%.*]] = add nsw i32 [[TMP69]], [[TMP68]]
; CHECK-NEXT:    [[TMP70:%.*]] = extractelement <2 x i32> [[TMP63]], i32 0
; CHECK-NEXT:    [[TMP71:%.*]] = extractelement <2 x i32> [[TMP63]], i32 1
; CHECK-NEXT:    [[SUB27_3:%.*]] = sub nsw i32 [[TMP70]], [[TMP71]]
; CHECK-NEXT:    [[ADD24_3:%.*]] = add nsw i32 [[TMP71]], [[TMP70]]
; CHECK-NEXT:    [[ADD45_1:%.*]] = add nsw i32 [[SUB27_1]], [[SUB27]]
; CHECK-NEXT:    [[ADD45:%.*]] = add nsw i32 [[ADD24_1]], [[ADD24]]
; CHECK-NEXT:    [[TMP72:%.*]] = insertelement <2 x i32> poison, i32 [[ADD24]], i32 0
; CHECK-NEXT:    [[TMP73:%.*]] = insertelement <2 x i32> [[TMP72]], i32 [[SUB27]], i32 1
; CHECK-NEXT:    [[TMP74:%.*]] = insertelement <2 x i32> poison, i32 [[ADD24_1]], i32 0
; CHECK-NEXT:    [[TMP75:%.*]] = insertelement <2 x i32> [[TMP74]], i32 [[SUB27_1]], i32 1
; CHECK-NEXT:    [[TMP76:%.*]] = sub nsw <2 x i32> [[TMP73]], [[TMP75]]
; CHECK-NEXT:    [[ADD59_1:%.*]] = add nsw i32 [[SUB27_3]], [[SUB27_2]]
; CHECK-NEXT:    [[ADD59:%.*]] = add nsw i32 [[ADD24_3]], [[ADD24_2]]
; CHECK-NEXT:    [[TMP77:%.*]] = insertelement <2 x i32> poison, i32 [[ADD24_2]], i32 0
; CHECK-NEXT:    [[TMP78:%.*]] = insertelement <2 x i32> [[TMP77]], i32 [[SUB27_2]], i32 1
; CHECK-NEXT:    [[TMP79:%.*]] = insertelement <2 x i32> poison, i32 [[ADD24_3]], i32 0
; CHECK-NEXT:    [[TMP80:%.*]] = insertelement <2 x i32> [[TMP79]], i32 [[SUB27_3]], i32 1
; CHECK-NEXT:    [[TMP81:%.*]] = sub nsw <2 x i32> [[TMP78]], [[TMP80]]
; CHECK-NEXT:    [[ADD67_1:%.*]] = add nsw i32 [[ADD59_1]], [[ADD45_1]]
; CHECK-NEXT:    [[ADD67:%.*]] = add nsw i32 [[ADD59]], [[ADD45]]
; CHECK-NEXT:    [[TMP82:%.*]] = insertelement <2 x i32> poison, i32 [[ADD45]], i32 0
; CHECK-NEXT:    [[TMP83:%.*]] = insertelement <2 x i32> [[TMP82]], i32 [[ADD45_1]], i32 1
; CHECK-NEXT:    [[TMP84:%.*]] = insertelement <2 x i32> poison, i32 [[ADD59]], i32 0
; CHECK-NEXT:    [[TMP85:%.*]] = insertelement <2 x i32> [[TMP84]], i32 [[ADD59_1]], i32 1
; CHECK-NEXT:    [[TMP86:%.*]] = sub nsw <2 x i32> [[TMP83]], [[TMP85]]
; CHECK-NEXT:    [[TMP87:%.*]] = add nsw <2 x i32> [[TMP81]], [[TMP76]]
; CHECK-NEXT:    [[TMP88:%.*]] = sub nsw <2 x i32> [[TMP76]], [[TMP81]]
; CHECK-NEXT:    [[TMP89:%.*]] = insertelement <2 x i32> poison, i32 [[ADD67]], i32 0
; CHECK-NEXT:    [[TMP90:%.*]] = insertelement <2 x i32> [[TMP89]], i32 [[ADD67_1]], i32 1
; CHECK-NEXT:    [[TMP91:%.*]] = lshr <2 x i32> [[TMP90]], splat (i32 15)
; CHECK-NEXT:    [[TMP92:%.*]] = and <2 x i32> [[TMP91]], splat (i32 65537)
; CHECK-NEXT:    [[TMP93:%.*]] = mul nuw <2 x i32> [[TMP92]], splat (i32 65535)
; CHECK-NEXT:    [[TMP94:%.*]] = add <2 x i32> [[TMP93]], [[TMP90]]
; CHECK-NEXT:    [[TMP95:%.*]] = xor <2 x i32> [[TMP94]], [[TMP93]]
; CHECK-NEXT:    [[TMP96:%.*]] = lshr <2 x i32> [[TMP87]], splat (i32 15)
; CHECK-NEXT:    [[TMP97:%.*]] = and <2 x i32> [[TMP96]], splat (i32 65537)
; CHECK-NEXT:    [[TMP98:%.*]] = mul nuw <2 x i32> [[TMP97]], splat (i32 65535)
; CHECK-NEXT:    [[TMP99:%.*]] = add <2 x i32> [[TMP98]], [[TMP87]]
; CHECK-NEXT:    [[TMP100:%.*]] = xor <2 x i32> [[TMP99]], [[TMP98]]
; CHECK-NEXT:    [[TMP101:%.*]] = add <2 x i32> [[TMP95]], [[TMP100]]
; CHECK-NEXT:    [[TMP102:%.*]] = lshr <2 x i32> [[TMP86]], splat (i32 15)
; CHECK-NEXT:    [[TMP103:%.*]] = and <2 x i32> [[TMP102]], splat (i32 65537)
; CHECK-NEXT:    [[TMP104:%.*]] = mul nuw <2 x i32> [[TMP103]], splat (i32 65535)
; CHECK-NEXT:    [[TMP105:%.*]] = add <2 x i32> [[TMP104]], [[TMP86]]
; CHECK-NEXT:    [[TMP106:%.*]] = xor <2 x i32> [[TMP105]], [[TMP104]]
; CHECK-NEXT:    [[TMP107:%.*]] = add <2 x i32> [[TMP101]], [[TMP106]]
; CHECK-NEXT:    [[TMP108:%.*]] = lshr <2 x i32> [[TMP88]], splat (i32 15)
; CHECK-NEXT:    [[TMP109:%.*]] = and <2 x i32> [[TMP108]], splat (i32 65537)
; CHECK-NEXT:    [[TMP110:%.*]] = mul nuw <2 x i32> [[TMP109]], splat (i32 65535)
; CHECK-NEXT:    [[TMP111:%.*]] = add <2 x i32> [[TMP110]], [[TMP88]]
; CHECK-NEXT:    [[TMP112:%.*]] = xor <2 x i32> [[TMP111]], [[TMP110]]
; CHECK-NEXT:    [[TMP113:%.*]] = add <2 x i32> [[TMP107]], [[TMP112]]
; CHECK-NEXT:    [[TMP114:%.*]] = shufflevector <2 x i32> [[TMP113]], <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 0, i32 1>
; CHECK-NEXT:    [[TMP115:%.*]] = and <4 x i32> [[TMP114]], <i32 65535, i32 65535, i32 16, i32 16>
; CHECK-NEXT:    [[TMP116:%.*]] = lshr <4 x i32> [[TMP114]], <i32 65535, i32 65535, i32 16, i32 16>
; CHECK-NEXT:    [[TMP117:%.*]] = shufflevector <4 x i32> [[TMP115]], <4 x i32> [[TMP116]], <4 x i32> <i32 0, i32 1, i32 6, i32 7>
; CHECK-NEXT:    [[TMP118:%.*]] = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[TMP117]])
; CHECK-NEXT:    [[SHR84:%.*]] = lshr i32 [[TMP118]], 1
; CHECK-NEXT:    ret i32 [[SHR84]]
;
entry:
  %idx.ext = sext i32 %i_pix1 to i64
  %idx.ext31 = sext i32 %i_pix2 to i64
  %0 = load i8, ptr %pix1, align 1
  %conv = zext i8 %0 to i32
  %1 = load i8, ptr %pix2, align 1
  %conv2 = zext i8 %1 to i32
  %sub = sub nsw i32 %conv, %conv2
  %arrayidx3 = getelementptr inbounds nuw i8, ptr %pix1, i64 1
  %2 = load i8, ptr %arrayidx3, align 1
  %conv4 = zext i8 %2 to i32
  %arrayidx5 = getelementptr inbounds nuw i8, ptr %pix2, i64 1
  %3 = load i8, ptr %arrayidx5, align 1
  %conv6 = zext i8 %3 to i32
  %sub7 = sub nsw i32 %conv4, %conv6
  %add = add nsw i32 %sub7, %sub
  %sub8 = sub nsw i32 %sub, %sub7
  %shl = shl nsw i32 %sub8, 16
  %add9 = add nsw i32 %add, %shl
  %arrayidx10 = getelementptr inbounds nuw i8, ptr %pix1, i64 2
  %4 = load i8, ptr %arrayidx10, align 1
  %conv11 = zext i8 %4 to i32
  %arrayidx12 = getelementptr inbounds nuw i8, ptr %pix2, i64 2
  %5 = load i8, ptr %arrayidx12, align 1
  %conv13 = zext i8 %5 to i32
  %sub14 = sub nsw i32 %conv11, %conv13
  %arrayidx15 = getelementptr inbounds nuw i8, ptr %pix1, i64 3
  %6 = load i8, ptr %arrayidx15, align 1
  %conv16 = zext i8 %6 to i32
  %arrayidx17 = getelementptr inbounds nuw i8, ptr %pix2, i64 3
  %7 = load i8, ptr %arrayidx17, align 1
  %conv18 = zext i8 %7 to i32
  %sub19 = sub nsw i32 %conv16, %conv18
  %add20 = add nsw i32 %sub19, %sub14
  %sub21 = sub nsw i32 %sub14, %sub19
  %shl22 = shl nsw i32 %sub21, 16
  %add23 = add nsw i32 %add20, %shl22
  %add24 = add nsw i32 %add23, %add9
  %sub27 = sub nsw i32 %add9, %add23
  %add.ptr = getelementptr inbounds i8, ptr %pix1, i64 %idx.ext
  %add.ptr32 = getelementptr inbounds i8, ptr %pix2, i64 %idx.ext31
  %8 = load i8, ptr %add.ptr, align 1
  %conv.1 = zext i8 %8 to i32
  %9 = load i8, ptr %add.ptr32, align 1
  %conv2.1 = zext i8 %9 to i32
  %sub.1 = sub nsw i32 %conv.1, %conv2.1
  %arrayidx3.1 = getelementptr inbounds nuw i8, ptr %add.ptr, i64 1
  %10 = load i8, ptr %arrayidx3.1, align 1
  %conv4.1 = zext i8 %10 to i32
  %arrayidx5.1 = getelementptr inbounds nuw i8, ptr %add.ptr32, i64 1
  %11 = load i8, ptr %arrayidx5.1, align 1
  %conv6.1 = zext i8 %11 to i32
  %sub7.1 = sub nsw i32 %conv4.1, %conv6.1
  %add.1 = add nsw i32 %sub7.1, %sub.1
  %sub8.1 = sub nsw i32 %sub.1, %sub7.1
  %shl.1 = shl nsw i32 %sub8.1, 16
  %add9.1 = add nsw i32 %add.1, %shl.1
  %arrayidx10.1 = getelementptr inbounds nuw i8, ptr %add.ptr, i64 2
  %12 = load i8, ptr %arrayidx10.1, align 1
  %conv11.1 = zext i8 %12 to i32
  %arrayidx12.1 = getelementptr inbounds nuw i8, ptr %add.ptr32, i64 2
  %13 = load i8, ptr %arrayidx12.1, align 1
  %conv13.1 = zext i8 %13 to i32
  %sub14.1 = sub nsw i32 %conv11.1, %conv13.1
  %arrayidx15.1 = getelementptr inbounds nuw i8, ptr %add.ptr, i64 3
  %14 = load i8, ptr %arrayidx15.1, align 1
  %conv16.1 = zext i8 %14 to i32
  %arrayidx17.1 = getelementptr inbounds nuw i8, ptr %add.ptr32, i64 3
  %15 = load i8, ptr %arrayidx17.1, align 1
  %conv18.1 = zext i8 %15 to i32
  %sub19.1 = sub nsw i32 %conv16.1, %conv18.1
  %add20.1 = add nsw i32 %sub19.1, %sub14.1
  %sub21.1 = sub nsw i32 %sub14.1, %sub19.1
  %shl22.1 = shl nsw i32 %sub21.1, 16
  %add23.1 = add nsw i32 %add20.1, %shl22.1
  %add24.1 = add nsw i32 %add23.1, %add9.1
  %sub27.1 = sub nsw i32 %add9.1, %add23.1
  %add.ptr.1 = getelementptr inbounds i8, ptr %add.ptr, i64 %idx.ext
  %add.ptr32.1 = getelementptr inbounds i8, ptr %add.ptr32, i64 %idx.ext31
  %16 = load i8, ptr %add.ptr.1, align 1
  %conv.2 = zext i8 %16 to i32
  %17 = load i8, ptr %add.ptr32.1, align 1
  %conv2.2 = zext i8 %17 to i32
  %sub.2 = sub nsw i32 %conv.2, %conv2.2
  %arrayidx3.2 = getelementptr inbounds nuw i8, ptr %add.ptr.1, i64 1
  %18 = load i8, ptr %arrayidx3.2, align 1
  %conv4.2 = zext i8 %18 to i32
  %arrayidx5.2 = getelementptr inbounds nuw i8, ptr %add.ptr32.1, i64 1
  %19 = load i8, ptr %arrayidx5.2, align 1
  %conv6.2 = zext i8 %19 to i32
  %sub7.2 = sub nsw i32 %conv4.2, %conv6.2
  %add.2 = add nsw i32 %sub7.2, %sub.2
  %sub8.2 = sub nsw i32 %sub.2, %sub7.2
  %shl.2 = shl nsw i32 %sub8.2, 16
  %add9.2 = add nsw i32 %add.2, %shl.2
  %arrayidx10.2 = getelementptr inbounds nuw i8, ptr %add.ptr.1, i64 2
  %20 = load i8, ptr %arrayidx10.2, align 1
  %conv11.2 = zext i8 %20 to i32
  %arrayidx12.2 = getelementptr inbounds nuw i8, ptr %add.ptr32.1, i64 2
  %21 = load i8, ptr %arrayidx12.2, align 1
  %conv13.2 = zext i8 %21 to i32
  %sub14.2 = sub nsw i32 %conv11.2, %conv13.2
  %arrayidx15.2 = getelementptr inbounds nuw i8, ptr %add.ptr.1, i64 3
  %22 = load i8, ptr %arrayidx15.2, align 1
  %conv16.2 = zext i8 %22 to i32
  %arrayidx17.2 = getelementptr inbounds nuw i8, ptr %add.ptr32.1, i64 3
  %23 = load i8, ptr %arrayidx17.2, align 1
  %conv18.2 = zext i8 %23 to i32
  %sub19.2 = sub nsw i32 %conv16.2, %conv18.2
  %add20.2 = add nsw i32 %sub19.2, %sub14.2
  %sub21.2 = sub nsw i32 %sub14.2, %sub19.2
  %shl22.2 = shl nsw i32 %sub21.2, 16
  %add23.2 = add nsw i32 %add20.2, %shl22.2
  %add24.2 = add nsw i32 %add23.2, %add9.2
  %sub27.2 = sub nsw i32 %add9.2, %add23.2
  %add.ptr.2 = getelementptr inbounds i8, ptr %add.ptr.1, i64 %idx.ext
  %add.ptr32.2 = getelementptr inbounds i8, ptr %add.ptr32.1, i64 %idx.ext31
  %24 = load i8, ptr %add.ptr.2, align 1
  %conv.3 = zext i8 %24 to i32
  %25 = load i8, ptr %add.ptr32.2, align 1
  %conv2.3 = zext i8 %25 to i32
  %sub.3 = sub nsw i32 %conv.3, %conv2.3
  %arrayidx3.3 = getelementptr inbounds nuw i8, ptr %add.ptr.2, i64 1
  %26 = load i8, ptr %arrayidx3.3, align 1
  %conv4.3 = zext i8 %26 to i32
  %arrayidx5.3 = getelementptr inbounds nuw i8, ptr %add.ptr32.2, i64 1
  %27 = load i8, ptr %arrayidx5.3, align 1
  %conv6.3 = zext i8 %27 to i32
  %sub7.3 = sub nsw i32 %conv4.3, %conv6.3
  %add.3 = add nsw i32 %sub7.3, %sub.3
  %sub8.3 = sub nsw i32 %sub.3, %sub7.3
  %shl.3 = shl nsw i32 %sub8.3, 16
  %add9.3 = add nsw i32 %add.3, %shl.3
  %arrayidx10.3 = getelementptr inbounds nuw i8, ptr %add.ptr.2, i64 2
  %28 = load i8, ptr %arrayidx10.3, align 1
  %conv11.3 = zext i8 %28 to i32
  %arrayidx12.3 = getelementptr inbounds nuw i8, ptr %add.ptr32.2, i64 2
  %29 = load i8, ptr %arrayidx12.3, align 1
  %conv13.3 = zext i8 %29 to i32
  %sub14.3 = sub nsw i32 %conv11.3, %conv13.3
  %arrayidx15.3 = getelementptr inbounds nuw i8, ptr %add.ptr.2, i64 3
  %30 = load i8, ptr %arrayidx15.3, align 1
  %conv16.3 = zext i8 %30 to i32
  %arrayidx17.3 = getelementptr inbounds nuw i8, ptr %add.ptr32.2, i64 3
  %31 = load i8, ptr %arrayidx17.3, align 1
  %conv18.3 = zext i8 %31 to i32
  %sub19.3 = sub nsw i32 %conv16.3, %conv18.3
  %add20.3 = add nsw i32 %sub19.3, %sub14.3
  %sub21.3 = sub nsw i32 %sub14.3, %sub19.3
  %shl22.3 = shl nsw i32 %sub21.3, 16
  %add23.3 = add nsw i32 %add20.3, %shl22.3
  %add24.3 = add nsw i32 %add23.3, %add9.3
  %sub27.3 = sub nsw i32 %add9.3, %add23.3
  %add45 = add nsw i32 %add24.1, %add24
  %sub52 = sub nsw i32 %add24, %add24.1
  %add59 = add nsw i32 %add24.3, %add24.2
  %sub66 = sub nsw i32 %add24.2, %add24.3
  %add67 = add nsw i32 %add59, %add45
  %sub68 = sub nsw i32 %add45, %add59
  %add69 = add nsw i32 %sub66, %sub52
  %sub70 = sub nsw i32 %sub52, %sub66
  %shr.i = lshr i32 %add67, 15
  %and.i = and i32 %shr.i, 65537
  %mul.i = mul nuw i32 %and.i, 65535
  %add.i = add i32 %mul.i, %add67
  %xor.i = xor i32 %add.i, %mul.i
  %shr.i122 = lshr i32 %add69, 15
  %and.i123 = and i32 %shr.i122, 65537
  %mul.i124 = mul nuw i32 %and.i123, 65535
  %add.i125 = add i32 %mul.i124, %add69
  %xor.i126 = xor i32 %add.i125, %mul.i124
  %add72 = add i32 %xor.i, %xor.i126
  %shr.i127 = lshr i32 %sub68, 15
  %and.i128 = and i32 %shr.i127, 65537
  %mul.i129 = mul nuw i32 %and.i128, 65535
  %add.i130 = add i32 %mul.i129, %sub68
  %xor.i131 = xor i32 %add.i130, %mul.i129
  %add74 = add i32 %add72, %xor.i131
  %shr.i132 = lshr i32 %sub70, 15
  %and.i133 = and i32 %shr.i132, 65537
  %mul.i134 = mul nuw i32 %and.i133, 65535
  %add.i135 = add i32 %mul.i134, %sub70
  %xor.i136 = xor i32 %add.i135, %mul.i134
  %add76 = add i32 %add74, %xor.i136
  %conv78 = and i32 %add76, 65535
  %shr = lshr i32 %add76, 16
  %add80 = add nuw nsw i32 %shr, %conv78
  %add45.1 = add nsw i32 %sub27.1, %sub27
  %sub52.1 = sub nsw i32 %sub27, %sub27.1
  %add59.1 = add nsw i32 %sub27.3, %sub27.2
  %sub66.1 = sub nsw i32 %sub27.2, %sub27.3
  %add67.1 = add nsw i32 %add59.1, %add45.1
  %sub68.1 = sub nsw i32 %add45.1, %add59.1
  %add69.1 = add nsw i32 %sub66.1, %sub52.1
  %sub70.1 = sub nsw i32 %sub52.1, %sub66.1
  %shr.i.1 = lshr i32 %add67.1, 15
  %and.i.1 = and i32 %shr.i.1, 65537
  %mul.i.1 = mul nuw i32 %and.i.1, 65535
  %add.i.1 = add i32 %mul.i.1, %add67.1
  %xor.i.1 = xor i32 %add.i.1, %mul.i.1
  %shr.i122.1 = lshr i32 %add69.1, 15
  %and.i123.1 = and i32 %shr.i122.1, 65537
  %mul.i124.1 = mul nuw i32 %and.i123.1, 65535
  %add.i125.1 = add i32 %mul.i124.1, %add69.1
  %xor.i126.1 = xor i32 %add.i125.1, %mul.i124.1
  %add72.1 = add i32 %xor.i.1, %xor.i126.1
  %shr.i127.1 = lshr i32 %sub68.1, 15
  %and.i128.1 = and i32 %shr.i127.1, 65537
  %mul.i129.1 = mul nuw i32 %and.i128.1, 65535
  %add.i130.1 = add i32 %mul.i129.1, %sub68.1
  %xor.i131.1 = xor i32 %add.i130.1, %mul.i129.1
  %add74.1 = add i32 %add72.1, %xor.i131.1
  %shr.i132.1 = lshr i32 %sub70.1, 15
  %and.i133.1 = and i32 %shr.i132.1, 65537
  %mul.i134.1 = mul nuw i32 %and.i133.1, 65535
  %add.i135.1 = add i32 %mul.i134.1, %sub70.1
  %xor.i136.1 = xor i32 %add.i135.1, %mul.i134.1
  %add76.1 = add i32 %add74.1, %xor.i136.1
  %conv78.1 = and i32 %add76.1, 65535
  %shr.1 = lshr i32 %add76.1, 16
  %add79.1 = add nuw nsw i32 %shr.1, %add80
  %add80.1 = add nuw nsw i32 %add79.1, %conv78.1
  %shr84 = lshr i32 %add80.1, 1
  ret i32 %shr84
}
