; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --check-attributes --check-globals
; RUN: opt -aa-pipeline=basic-aa -passes=attributor -attributor-manifest-internal  -attributor-max-iterations-verify -attributor-annotate-decl-cs -attributor-max-iterations=2 -S < %s | FileCheck %s --check-prefixes=CHECK,TUNIT
; RUN: opt -aa-pipeline=basic-aa -passes=attributor-cgscc -attributor-manifest-internal  -attributor-annotate-decl-cs -S < %s | FileCheck %s --check-prefixes=CHECK,CGSCC

define internal fastcc i32 @term_SharingList(i32* %Term, i32* %List) nounwind {
; CGSCC: Function Attrs: nofree norecurse nosync nounwind willreturn memory(none)
; CGSCC-LABEL: define {{[^@]+}}@term_SharingList
; CGSCC-SAME: () #[[ATTR0:[0-9]+]] {
; CGSCC-NEXT:  entry:
; CGSCC-NEXT:    br i1 false, label [[BB:%.*]], label [[BB5:%.*]]
; CGSCC:       bb:
; CGSCC-NEXT:    unreachable
; CGSCC:       bb5:
; CGSCC-NEXT:    ret i32 undef
;
entry:
  br i1 false, label %bb, label %bb5

bb:		; preds = %entry
  %0 = call fastcc i32 @term_SharingList( i32* null, i32* %List ) nounwind		; <i32> [#uses=0]
  unreachable

bb5:		; preds = %entry
  ret i32 0
}

define i32 @term_Sharing(i32* %Term) nounwind {
; CHECK: Function Attrs: nofree norecurse nosync nounwind willreturn memory(none)
; CHECK-LABEL: define {{[^@]+}}@term_Sharing
; CHECK-SAME: (i32* nocapture nofree readnone [[TERM:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 false, label [[BB_I:%.*]], label [[BB14:%.*]]
; CHECK:       bb.i:
; CHECK-NEXT:    unreachable
; CHECK:       bb14:
; CHECK-NEXT:    ret i32 0
;
entry:
  br i1 false, label %bb.i, label %bb14

bb.i:		; preds = %entry
  %0 = call fastcc i32 @term_SharingList( i32* null, i32* null ) nounwind		; <i32> [#uses=0]
  ret i32 1

bb14:		; preds = %entry
  ret i32 0
}
;.
; CHECK: attributes #[[ATTR0]] = { nofree norecurse nosync nounwind willreturn memory(none) }
;.
