; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --check-attributes --check-globals
; RUN: opt -aa-pipeline=basic-aa -passes=attributor -attributor-manifest-internal  -attributor-max-iterations-verify -attributor-annotate-decl-cs -attributor-max-iterations=1 -S < %s | FileCheck %s --check-prefixes=CHECK,TUNIT
; RUN: opt -aa-pipeline=basic-aa -passes=attributor-cgscc -attributor-manifest-internal  -attributor-annotate-decl-cs -S < %s | FileCheck %s --check-prefixes=CHECK,CGSCC
target datalayout = "E-p:64:64:64-a0:0:8-f32:32:32-f64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-v64:64:64-v128:128:128"

; Checks if !prof metadata is corret in deadargelim.

define void @caller() #0 {
; TUNIT-LABEL: define {{[^@]+}}@caller() {
; TUNIT-NEXT:    [[X:%.*]] = alloca i32, align 4
; TUNIT-NEXT:    store i32 42, ptr [[X]], align 4
; TUNIT-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X]], align 4
; TUNIT-NEXT:    call void @promote_i32_ptr(i32 [[TMP1]]), !prof [[PROF0:![0-9]+]]
; TUNIT-NEXT:    ret void
;
; CGSCC-LABEL: define {{[^@]+}}@caller() {
; CGSCC-NEXT:    call void @promote_i32_ptr(i32 noundef 42), !prof [[PROF0:![0-9]+]]
; CGSCC-NEXT:    ret void
;
  %x = alloca i32
  store i32 42, ptr %x
  call void @promote_i32_ptr(ptr %x), !prof !0
  ret void
}

define internal void @promote_i32_ptr(ptr %xp) {
; CHECK-LABEL: define {{[^@]+}}@promote_i32_ptr
; CHECK-SAME: (i32 [[TMP0:%.*]]) {
; CHECK-NEXT:    [[XP_PRIV:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[XP_PRIV]], align 4
; CHECK-NEXT:    [[X:%.*]] = load i32, ptr [[XP_PRIV]], align 4
; CHECK-NEXT:    call void @use_i32(i32 [[X]])
; CHECK-NEXT:    ret void
;
  %x = load i32, ptr %xp
  call void @use_i32(i32 %x)
  ret void
}

declare void @use_i32(i32)

!0 = !{!"branch_weights", i32 30}
;.
; CHECK: [[META0:![0-9]+]] = !{!"branch_weights", i32 30}
;.
