; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -S -passes=infer-address-spaces %s | FileCheck %s

define amdgpu_kernel void @subclass_data_assert() {
; CHECK-LABEL: @subclass_data_assert(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    unreachable
; CHECK:       strlen.while11:
; CHECK-NEXT:    [[I:%.*]] = getelementptr i8, ptr [[I]], i64 1
; CHECK-NEXT:    [[I1:%.*]] = load i8, ptr [[I]], align 1
; CHECK-NEXT:    [[I2:%.*]] = icmp eq i8 [[I1]], 0
; CHECK-NEXT:    br i1 [[I2]], label [[STRLEN_WHILE_DONE12:%.*]], label [[STRLEN_WHILE11:%.*]]
; CHECK:       strlen.while.done12:
; CHECK-NEXT:    ret void
;
entry:
  unreachable

strlen.while11:                                   ; preds = %strlen.while11
  %i = getelementptr i8, ptr %i, i64 1
  %i1 = load i8, ptr %i, align 1
  %i2 = icmp eq i8 %i1, 0
  br i1 %i2, label %strlen.while.done12, label %strlen.while11

strlen.while.done12:                              ; preds = %strlen.while11
  ret void
}
