// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v -disable-O0-optnone \
// RUN:   -emit-llvm %s -o - | opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s
// RUN: %clang_cc1 -triple riscv64 -target-feature +v -disable-O0-optnone \
// RUN:   -mvscale-min=2 -mvscale-max=2 -emit-llvm %s -o - | opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64-FIXED %s

#include <riscv_vector.h>

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e8mf8
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 0, i64 5)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 2
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e8mf8
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 0, i64 5)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 2
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 4
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 2
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e8mf8(size_t avl) {
  return __riscv_vsetvl_e8mf8(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e8mf4
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 0, i64 6)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 4
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e8mf4
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 0, i64 6)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 4
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 8
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 4
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e8mf4(size_t avl) {
  return __riscv_vsetvl_e8mf4(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e8mf2
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 0, i64 7)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 8
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e8mf2
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 0, i64 7)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 8
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 16
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 8
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e8mf2(size_t avl) {
  return __riscv_vsetvl_e8mf2(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e8m1
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 0, i64 0)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 16
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e8m1
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 0, i64 0)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 16
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 32
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 16
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e8m1(size_t avl) {
  return __riscv_vsetvl_e8m1(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e8m2
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 0, i64 1)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 32
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e8m2
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 0, i64 1)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 32
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 64
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 32
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e8m2(size_t avl) {
  return __riscv_vsetvl_e8m2(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e8m4
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 0, i64 2)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 64
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e8m4
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 0, i64 2)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 64
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 128
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 64
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e8m4(size_t avl) {
  return __riscv_vsetvl_e8m4(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e8m8
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 0, i64 3)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 128
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e8m8
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 0, i64 3)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 128
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 256
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 128
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e8m8(size_t avl) {
  return __riscv_vsetvl_e8m8(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e16mf4
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 1, i64 6)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 2
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e16mf4
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 1, i64 6)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 2
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 4
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 2
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e16mf4(size_t avl) {
  return __riscv_vsetvl_e16mf4(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e16mf2
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 1, i64 7)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 4
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e16mf2
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 1, i64 7)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 4
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 8
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 4
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e16mf2(size_t avl) {
  return __riscv_vsetvl_e16mf2(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e16m1
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 1, i64 0)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 8
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e16m1
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 1, i64 0)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 8
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 16
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 8
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e16m1(size_t avl) {
  return __riscv_vsetvl_e16m1(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e16m2
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 1, i64 1)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 16
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e16m2
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 1, i64 1)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 16
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 32
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 16
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e16m2(size_t avl) {
  return __riscv_vsetvl_e16m2(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e16m4
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 1, i64 2)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 32
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e16m4
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 1, i64 2)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 32
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 64
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 32
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e16m4(size_t avl) {
  return __riscv_vsetvl_e16m4(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e16m8
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 1, i64 3)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 64
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e16m8
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 1, i64 3)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 64
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 128
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 64
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e16m8(size_t avl) {
  return __riscv_vsetvl_e16m8(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e32mf2
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 2, i64 7)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 2
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e32mf2
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 2, i64 7)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 2
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 4
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 2
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e32mf2(size_t avl) {
  return __riscv_vsetvl_e32mf2(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e32m1
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 2, i64 0)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 4
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e32m1
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 2, i64 0)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 4
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 8
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 4
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e32m1(size_t avl) {
  return __riscv_vsetvl_e32m1(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e32m2
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 2, i64 1)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 8
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e32m2
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 2, i64 1)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 8
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 16
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 8
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e32m2(size_t avl) {
  return __riscv_vsetvl_e32m2(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e32m4
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 2, i64 2)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 16
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e32m4
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 2, i64 2)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 16
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 32
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 16
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e32m4(size_t avl) {
  return __riscv_vsetvl_e32m4(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e32m8
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 2, i64 3)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 32
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e32m8
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 2, i64 3)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 32
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 64
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 32
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e32m8(size_t avl) {
  return __riscv_vsetvl_e32m8(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e64m1
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 3, i64 0)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 2
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e64m1
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 3, i64 0)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 2
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 4
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 2
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e64m1(size_t avl) {
  return __riscv_vsetvl_e64m1(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e64m2
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 3, i64 1)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 4
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e64m2
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 3, i64 1)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 4
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 8
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 4
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e64m2(size_t avl) {
  return __riscv_vsetvl_e64m2(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e64m4
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 3, i64 2)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 8
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e64m4
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 3, i64 2)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 8
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 16
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 8
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e64m4(size_t avl) {
  return __riscv_vsetvl_e64m4(avl);
}

// CHECK-RV64-LABEL: define dso_local i64 @test_vsetvl_e64m8
// CHECK-RV64-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 3, i64 3)
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 16
// CHECK-RV64-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64:       assumption:
// CHECK-RV64-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64:       assumption_end:
// CHECK-RV64-NEXT:    ret i64 [[VL]]
//
// CHECK-RV64-FIXED-LABEL: define dso_local i64 @test_vsetvl_e64m8
// CHECK-RV64-FIXED-SAME: (i64 noundef [[AVL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-FIXED-NEXT:  entry:
// CHECK-RV64-FIXED-NEXT:    [[VL:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 3, i64 3)
// CHECK-RV64-FIXED-NEXT:    [[TMP0:%.*]] = icmp ule i64 [[AVL]], 16
// CHECK-RV64-FIXED-NEXT:    br i1 [[TMP0]], label [[ASSUMPTION:%.*]], label [[ASSUMPTION_END:%.*]]
// CHECK-RV64-FIXED:       assumption:
// CHECK-RV64-FIXED-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[VL]], [[AVL]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP1]])
// CHECK-RV64-FIXED-NEXT:    br label [[ASSUMPTION_END]]
// CHECK-RV64-FIXED:       assumption_end:
// CHECK-RV64-FIXED-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[AVL]], 32
// CHECK-RV64-FIXED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[VL]], 16
// CHECK-RV64-FIXED-NEXT:    [[TMP4:%.*]] = select i1 [[TMP2]], i1 true, i1 [[TMP3]]
// CHECK-RV64-FIXED-NEXT:    call void @llvm.assume(i1 [[TMP4]])
// CHECK-RV64-FIXED-NEXT:    ret i64 [[VL]]
//
size_t test_vsetvl_e64m8(size_t avl) {
  return __riscv_vsetvl_e64m8(avl);
}

