; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes="function(scalable-to-fixed-vectors)" -S %s | FileCheck %s

; Store of a splat vector
define void @const_store(ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @const_store(
; CHECK-SAME: ptr [[DST:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    store <4 x i32> splat (i32 2), ptr [[DST]], align 16
; CHECK-NEXT:    ret void
;
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> splat (i32 2), ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

; Simple load-store chain, VL < MinVScaleVL
define void @load_store(ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @load_store(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = load <4 x i32>, ptr [[SRC]], align 16
; CHECK-NEXT:    store <4 x i32> [[LOAD]], ptr [[DST]], align 16
; CHECK-NEXT:    ret void
;
  %load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 4)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

; Simple load-binop-store chain, VL < MinVScaleVL
define void @load_binop_store(ptr %src0, ptr %src1, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @load_binop_store(
; CHECK-SAME: ptr [[SRC0:%.*]], ptr [[SRC1:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD0:%.*]] = load <4 x i32>, ptr [[SRC0]], align 16
; CHECK-NEXT:    [[LOAD1:%.*]] = load <4 x i32>, ptr [[SRC1]], align 16
; CHECK-NEXT:    [[ADD:%.*]] = add <4 x i32> [[LOAD0]], [[LOAD1]]
; CHECK-NEXT:    store <4 x i32> [[ADD]], ptr [[DST]], align 16
; CHECK-NEXT:    ret void
;
  %load0 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src0, <vscale x 4 x i1> splat (i1 true), i32 4)
  %load1 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src1, <vscale x 4 x i1> splat (i1 true), i32 4)
  %add = add <vscale x 4 x i32> %load0, %load1
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %add, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

; Binary op with splat
define void @binop_splat(ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @binop_splat(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = load <4 x i32>, ptr [[SRC]], align 16
; CHECK-NEXT:    [[ADD:%.*]] = add <4 x i32> [[LOAD]], splat (i32 2)
; CHECK-NEXT:    store <4 x i32> [[ADD]], ptr [[DST]], align 16
; CHECK-NEXT:    ret void
;
  %load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 4)
  %add = add <vscale x 4 x i32> %load, splat (i32 2)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %add, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

; Simple load-store chain, VL == MinVScaleVL
define void @vl_eq_minvscalevl(ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @vl_eq_minvscalevl(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = load <8 x i32>, ptr [[SRC]], align 32
; CHECK-NEXT:    store <8 x i32> [[LOAD]], ptr [[DST]], align 32
; CHECK-NEXT:    ret void
;
  %load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 8)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 8)
  ret void
}

; Simple load-store chain, VL > MinVScaleVL
; Should not convert
define void @vl_gt_minvscalevl(ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @vl_gt_minvscalevl(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC]], <vscale x 4 x i1> splat (i1 true), i32 10)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 10)
; CHECK-NEXT:    ret void
;
  %load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 10)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 10)
  ret void
}

; Load and store have different < MinVScaleVL VL's
; Should not convert
define void @different_vls0(ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @different_vls0(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    ret void
;
  %load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 4)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 2)
  ret void
}

; Load and store have different < MinVScaleVL VL's
; Should not convert
define void @different_vls1(ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @different_vls1(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC]], <vscale x 4 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    ret void
;
  %load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 2)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

; Load and store have different VLs, one > MinVScaleVL, one < MinVScaleVL
; Should not convert
define void @different_vls2(ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @different_vls2(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 16)
; CHECK-NEXT:    ret void
;
  %load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 4)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 16)
  ret void
}

; Load and store have different VLs, one > MinVScaleVL, one < MinVScaleVL
; Should not convert
define void @different_vls3(ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @different_vls3(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC]], <vscale x 4 x i1> splat (i1 true), i32 16)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    ret void
;
  %load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 16)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

; Store of a splat vector of non-constant value
; Should not convert
define void @splat_non_const(i32 %SV, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @splat_non_const(
; CHECK-SAME: i32 [[SV:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 4 x i32> poison, i32 [[SV]], i32 0
; CHECK-NEXT:    [[SPLAT:%.*]] = shufflevector <vscale x 4 x i32> [[INS]], <vscale x 4 x i32> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[SPLAT]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    ret void
;
  %ins = insertelement <vscale x 4 x i32> poison, i32 %SV, i32 0
  %splat = shufflevector <vscale x 4 x i32> %ins, <vscale x 4 x i32> poison, <vscale x 4 x i32> zeroinitializer
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %splat, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

; No vscale given
define void @no_vscale0(ptr %src, ptr %dst) {
; CHECK-LABEL: define void @no_vscale0(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:    [[LOAD:%.*]] = load <2 x i32>, ptr [[SRC]], align 8
; CHECK-NEXT:    store <2 x i32> [[LOAD]], ptr [[DST]], align 8
; CHECK-NEXT:    ret void
;
  %load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 2)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 2)
  ret void
}

; No vscale given
; Should use min-vscale of 1
; Should not convert
define void @no_vscale1(ptr %src, ptr %dst) {
; CHECK-LABEL: define void @no_vscale1(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:    [[LOAD:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC]], <vscale x 4 x i1> splat (i1 true), i32 8)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 8)
; CHECK-NEXT:    ret void
;
  %load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 8)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 8)
  ret void
}

; No VL or Mask given
; Should not convert
define void @no_vl_no_mask(ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @no_vl_no_mask(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC]], <vscale x 4 x i1> poison, i32 poison)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD]], ptr [[DST]], <vscale x 4 x i1> poison, i32 poison)
; CHECK-NEXT:    ret void
;
  %load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> poison, i32 poison)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load, ptr %dst, <vscale x 4 x i1> poison, i32 poison)
  ret void
}

; All false mask used
; Should not convert
define void @false_mask(ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @false_mask(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC]], <vscale x 4 x i1> zeroinitializer, i32 4)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    ret void
;
  %load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 false), i32 4)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

; Non-constant mask
; Should not convert
define void @non_constant_mask(<vscale x 4 x i1> %mask, ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @non_constant_mask(
; CHECK-SAME: <vscale x 4 x i1> [[MASK:%.*]], ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC]], <vscale x 4 x i1> [[MASK]], i32 4)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    ret void
;
  %load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> %mask, i32 4)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

; Non-constant VL
; Should not convert
define void @non_constant_vl(i32 %vl, ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @non_constant_vl(
; CHECK-SAME: i32 [[VL:%.*]], ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC]], <vscale x 4 x i1> splat (i1 true), i32 [[VL]])
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 [[VL]])
; CHECK-NEXT:    ret void
;
  %load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 %vl)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 %vl)
  ret void
}

; Already fixed vector
; Should not convert
define void @fixed_vector(i32 %vl, ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @fixed_vector(
; CHECK-SAME: i32 [[VL:%.*]], ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = tail call <4 x i32> @llvm.vp.load.v4i32.p0(ptr [[SRC]], <4 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    call void @llvm.vp.store.v4i32.p0(<4 x i32> [[LOAD]], ptr [[DST]], <4 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    ret void
;
  %load = tail call <4 x i32> @llvm.vp.load.v4i32.p0(ptr %src, <4 x i1> splat (i1 true), i32 2)
  call void @llvm.vp.store.v4i32.p0(<4 x i32> %load, ptr %dst, <4 x i1> splat (i1 true), i32 2)
  ret void
}

; Multiple load store chains, both convert
define void @multiple_chains0(ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @multiple_chains0(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD0:%.*]] = load <4 x i32>, ptr [[SRC]], align 16
; CHECK-NEXT:    store <4 x i32> [[LOAD0]], ptr [[DST]], align 16
; CHECK-NEXT:    [[LOAD1:%.*]] = load <4 x i32>, ptr [[SRC]], align 16
; CHECK-NEXT:    store <4 x i32> [[LOAD1]], ptr [[DST]], align 16
; CHECK-NEXT:    ret void
;
  %load0 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 4)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load0, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  %load1 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 4)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load1, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

; Multiple load store chains, only one converts
define void @multiple_chains1(ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @multiple_chains1(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD0:%.*]] = load <4 x i32>, ptr [[SRC]], align 16
; CHECK-NEXT:    store <4 x i32> [[LOAD0]], ptr [[DST]], align 16
; CHECK-NEXT:    [[LOAD1:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC]], <vscale x 4 x i1> splat (i1 true), i32 16)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD1]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    ret void
;
  %load0 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 4)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load0, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  %load1 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 16)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load1, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

; Multiple load store chains, neither convert
define void @multiple_chains2(ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @multiple_chains2(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD0:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC]], <vscale x 4 x i1> splat (i1 true), i32 16)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD0]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    [[LOAD1:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD1]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 16)
; CHECK-NEXT:    ret void
;
  %load0 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 16)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load0, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  %load1 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 4)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load1, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 16)
  ret void
}

; Non-supported operation in chain
; Should not convert
define void @not_supported_op(ptr %src0, ptr %src1, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @not_supported_op(
; CHECK-SAME: ptr [[SRC0:%.*]], ptr [[SRC1:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD0:%.*]] = load <4 x i32>, ptr [[SRC0]], align 16
; CHECK-NEXT:    [[ZEXT:%.*]] = zext <4 x i32> [[LOAD0]] to <4 x i64>
; CHECK-NEXT:    store <4 x i64> [[ZEXT]], ptr [[DST]], align 32
; CHECK-NEXT:    ret void
;
  %load0 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src0, <vscale x 4 x i1> splat (i1 true), i32 4)
  %zext = zext <vscale x 4 x i32> %load0 to <vscale x 4 x i64>
  call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %zext, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

; Flags and metadata should get saved
define void @flags_meta(ptr %src0, ptr %src1, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @flags_meta(
; CHECK-SAME: ptr [[SRC0:%.*]], ptr [[SRC1:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD0:%.*]] = load <4 x i32>, ptr [[SRC0]], align 16, !example [[META0:![0-9]+]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load <4 x i32>, ptr [[SRC1]], align 16
; CHECK-NEXT:    [[ADD:%.*]] = add nuw <4 x i32> [[LOAD0]], [[LOAD1]]
; CHECK-NEXT:    store <4 x i32> [[ADD]], ptr [[DST]], align 4
; CHECK-NEXT:    ret void
;
  %load0 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src0, <vscale x 4 x i1> splat (i1 true), i32 4), !example !0
  %load1 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src1, <vscale x 4 x i1> splat (i1 true), i32 4)
  %add = add nuw <vscale x 4 x i32> %load0, %load1
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %add, ptr align 4 %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

; Joined store chains
define void @branched_chain0(ptr %src0, ptr %src1, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @branched_chain0(
; CHECK-SAME: ptr [[SRC0:%.*]], ptr [[SRC1:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD0:%.*]] = load <4 x i32>, ptr [[SRC0]], align 16
; CHECK-NEXT:    [[LOAD1:%.*]] = load <4 x i32>, ptr [[SRC1]], align 16
; CHECK-NEXT:    [[ADD:%.*]] = add <4 x i32> [[LOAD0]], [[LOAD1]]
; CHECK-NEXT:    store <4 x i32> [[LOAD1]], ptr [[DST]], align 16
; CHECK-NEXT:    store <4 x i32> [[ADD]], ptr [[DST]], align 16
; CHECK-NEXT:    ret void
;
  %load0 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src0, <vscale x 4 x i1> splat (i1 true), i32 4)
  %load1 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src1, <vscale x 4 x i1> splat (i1 true), i32 4)
  %add = add <vscale x 4 x i32> %load0, %load1
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load1, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %add, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}


; Joined store chains, one has too large VL
; Should not convert
define void @branched_chain1(ptr %src0, ptr %src1, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @branched_chain1(
; CHECK-SAME: ptr [[SRC0:%.*]], ptr [[SRC1:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD0:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC0]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    [[LOAD1:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC1]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 4 x i32> [[LOAD0]], [[LOAD1]]
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD1]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[ADD]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 16)
; CHECK-NEXT:    ret void
;
  %load0 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src0, <vscale x 4 x i1> splat (i1 true), i32 4)
  %load1 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src1, <vscale x 4 x i1> splat (i1 true), i32 4)
  %add = add <vscale x 4 x i32> %load0, %load1
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load1, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %add, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 16)
  ret void
}

; Joined store chains, one store isn't supported
; Should not convert
define void @branched_chain2(ptr %src0, ptr %src1, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @branched_chain2(
; CHECK-SAME: ptr [[SRC0:%.*]], ptr [[SRC1:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD0:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC0]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    [[LOAD1:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC1]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 4 x i32> [[LOAD0]], [[LOAD1]]
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD1]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    store <vscale x 4 x i32> [[ADD]], ptr [[DST]], align 16
; CHECK-NEXT:    ret void
;
  %load0 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src0, <vscale x 4 x i1> splat (i1 true), i32 4)
  %load1 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src1, <vscale x 4 x i1> splat (i1 true), i32 4)
  %add = add <vscale x 4 x i32> %load0, %load1
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load1, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  store <vscale x 4 x i32> %add, ptr %dst
  ret void
}

; Joined store chains, one load has too large VL
; Should not convert
define void @branched_chain3(ptr %src0, ptr %src1, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @branched_chain3(
; CHECK-SAME: ptr [[SRC0:%.*]], ptr [[SRC1:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD0:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC0]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    [[LOAD1:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC1]], <vscale x 4 x i1> splat (i1 true), i32 16)
; CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 4 x i32> [[LOAD0]], [[LOAD1]]
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[LOAD1]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[ADD]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    ret void
;
  %load0 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src0, <vscale x 4 x i1> splat (i1 true), i32 4)
  %load1 = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src1, <vscale x 4 x i1> splat (i1 true), i32 16)
  %add = add <vscale x 4 x i32> %load0, %load1
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %load1, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %add, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

; Unsupported store instruction
; Should not convert
define void @unsupported_store(ptr %src, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @unsupported_store(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[SRC]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    call void @llvm.experimental.vp.strided.store.nxv4i32.p0.i32(<vscale x 4 x i32> [[LOAD]], ptr [[DST]], i32 2, <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    ret void
;
  %load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr %src, <vscale x 4 x i1> splat (i1 true), i32 4)
  call void @llvm.experimental.vp.strided.store.nxv4i32.p0.i32(<vscale x 4 x i32> %load, ptr %dst, i32 2, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

; Store of an argument
; Should not convert
define void @store_argument(<vscale x 4 x i32> %data, ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @store_argument(
; CHECK-SAME: <vscale x 4 x i32> [[DATA:%.*]], ptr [[DST:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[DATA]], ptr [[DST]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    ret void
;
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %data, ptr %dst, <vscale x 4 x i1> splat (i1 true), i32 4)
  ret void
}

!0 = !{!"example"}
;.
; CHECK: [[META0]] = !{!"example"}
;.
