; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=instcombine < %s | FileCheck %s

target triple = "aarch64-unknown-linux-gnu"

define <vscale x 16 x i1> @ptrue_pow2(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_pow2(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 0)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 0)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_vl1(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_vl1(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 1)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 1)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_vl2(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_vl2(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 2)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 2)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_vl3(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_vl3(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 3)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 3)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_vl4(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_vl4(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 4)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 4)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_vl5(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_vl5(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 5)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 5)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_vl6(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_vl6(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 6)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 6)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_vl7(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_vl7(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 7)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 7)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_vl8(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_vl8(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 8)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 8)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_vl16(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_vl16(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 9)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 9)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_vl32(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_vl32(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 10)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 10)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_vl64(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_vl64(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 11)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 11)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_vl128(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_vl128(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 12)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 12)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_vl256(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_vl256(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 13)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 13)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_mul4(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_mul4(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 29)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 29)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_mul3(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_mul3(
; CHECK-NEXT:    [[MASK:%.*]] = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 30)
; CHECK-NEXT:    ret <vscale x 16 x i1> [[MASK]]
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 30)
  ret <vscale x 16 x i1> %mask
}

define <vscale x 16 x i1> @ptrue_all(<vscale x 16 x i1> %a) #0 {
; CHECK-LABEL: @ptrue_all(
; CHECK-NEXT:    ret <vscale x 16 x i1> splat (i1 true)
;
  %mask = tail call <vscale x 16 x i1> @llvm.aarch64.sve.ptrue(i32 31)
  ret <vscale x 16 x i1> %mask
}

attributes #0 = { "target-features"="+sve" }
