; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple m68k | FileCheck %s -check-prefixes=CHECK

declare dso_local void @main()

define dso_local void @naked() naked "frame-pointer"="all" {
; CHECK-LABEL: naked:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    jsr main
  call void @main()
  unreachable
}

define dso_local void @normal() "frame-pointer"="all" {
; CHECK-LABEL: normal:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    link.w %a6, #0
; CHECK-NEXT:    .cfi_def_cfa_offset -8
; CHECK-NEXT:    .cfi_offset %a6, -8
; CHECK-NEXT:    .cfi_def_cfa_register %a6
; CHECK-NEXT:    jsr main
  call void @main()
  unreachable
}
