; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=m68k < %s | FileCheck %s

define i8 @scalar_setcc_lt0(i8 %a, i8 %b, i8 %x, i8 %y) {
; CHECK-LABEL: scalar_setcc_lt0:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    move.b (7,%sp), %d0
; CHECK-NEXT:    sub.b (11,%sp), %d0
; CHECK-NEXT:    blt .LBB0_1
; CHECK-NEXT:  ; %bb.2:
; CHECK-NEXT:    lea (19,%sp), %a0
; CHECK-NEXT:    move.b (%a0), %d0
; CHECK-NEXT:    rts
; CHECK-NEXT:  .LBB0_1:
; CHECK-NEXT:    lea (15,%sp), %a0
; CHECK-NEXT:    move.b (%a0), %d0
; CHECK-NEXT:    rts
  %cmp = icmp slt i8 %a, %b
  %sext = sext i1 %cmp to i8
  %lt0 = icmp slt i8 %sext, 0
  %sel = select i1 %lt0, i8 %x, i8 %y
  ret i8 %sel
}

define i8 @scalar_setcc_ne0(i8 %a, i8 %b, i8 %x, i8 %y) {
; CHECK-LABEL: scalar_setcc_ne0:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    move.b (7,%sp), %d0
; CHECK-NEXT:    sub.b (11,%sp), %d0
; CHECK-NEXT:    blt .LBB1_1
; CHECK-NEXT:  ; %bb.2:
; CHECK-NEXT:    lea (19,%sp), %a0
; CHECK-NEXT:    move.b (%a0), %d0
; CHECK-NEXT:    rts
; CHECK-NEXT:  .LBB1_1:
; CHECK-NEXT:    lea (15,%sp), %a0
; CHECK-NEXT:    move.b (%a0), %d0
; CHECK-NEXT:    rts
  %cmp = icmp slt i8 %a, %b
  %sext = sext i1 %cmp to i8
  %ne0 = icmp ne i8 %sext, 0
  %sel = select i1 %ne0, i8 %x, i8 %y
  ret i8 %sel
}
