set(CMAKE_CLC_OUTPUT_EXTENSION .o)
set(CMAKE_INCLUDE_FLAG_CLC "-I")

set(CMAKE_CLC_DEPFILE_FORMAT gcc)
set(CMAKE_DEPFILE_FLAGS_CLC "-MD -MT <DEP_TARGET> -MF <DEP_FILE>")

cmake_initialize_per_config_variable(CMAKE_CLC_FLAGS "Flags used by the CLC compiler")

if(NOT CMAKE_CLC_COMPILE_OBJECT)
  set(CMAKE_CLC_COMPILE_OBJECT
    "<CMAKE_CLC_COMPILER> -x cl <DEFINES> <INCLUDES> <FLAGS> -c -o <OBJECT> <SOURCE>")
endif()

if(NOT DEFINED CMAKE_CLC_ARCHIVE_CREATE)
  set(CMAKE_CLC_ARCHIVE_CREATE "<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>")
endif()
if(NOT DEFINED CMAKE_CLC_ARCHIVE_APPEND)
  set(CMAKE_CLC_ARCHIVE_APPEND "<CMAKE_AR> q <TARGET> <LINK_FLAGS> <OBJECTS>")
endif()
if(NOT DEFINED CMAKE_CLC_ARCHIVE_FINISH)
  set(CMAKE_CLC_ARCHIVE_FINISH "<CMAKE_RANLIB> <TARGET>")
endif()

set(CMAKE_CLC_USE_LINKER_INFORMATION FALSE)

set(CMAKE_CLC_INFORMATION_LOADED 1)
