; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=loop-reduce -S -mcpu=gfx942 %s | FileCheck %s
;
; Verify that LSR produces well-typed icmp operands when ICmpZero uses a
; pointer-typed operand from a narrow address space (addrspace(5), 32-bit)
; but the chosen IV is wider (i64, from flat-pointer address uses).

target triple = "amdgcn-amd-amdhsa"

define amdgpu_kernel void @icmpzero_mixed_ptr_width(ptr addrspace(5) %scratch) {
; CHECK-LABEL: define amdgpu_kernel void @icmpzero_mixed_ptr_width(
; CHECK-SAME: ptr addrspace(5) [[SCRATCH:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[SCEVGEP4:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[SRC_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[DST:%.*]] = phi ptr addrspace(5) [ [[SCRATCH]], %[[ENTRY]] ], [ [[DST_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[D0:%.*]] = load double, ptr addrspace(5) [[DST]], align 8
; CHECK-NEXT:    [[S0:%.*]] = load double, ptr [[SCEVGEP4]], align 8
; CHECK-NEXT:    [[DST_1:%.*]] = getelementptr i8, ptr addrspace(5) [[DST]], i32 8
; CHECK-NEXT:    [[D1:%.*]] = load double, ptr addrspace(5) [[DST_1]], align 8
; CHECK-NEXT:    [[SCEVGEP3:%.*]] = getelementptr i8, ptr [[SCEVGEP4]], i64 8
; CHECK-NEXT:    [[S1:%.*]] = load double, ptr [[SCEVGEP3]], align 8
; CHECK-NEXT:    [[DST_2:%.*]] = getelementptr i8, ptr addrspace(5) [[DST]], i32 16
; CHECK-NEXT:    [[D2:%.*]] = load double, ptr addrspace(5) [[DST_2]], align 8
; CHECK-NEXT:    [[SCEVGEP1:%.*]] = getelementptr i8, ptr [[SCEVGEP4]], i64 16
; CHECK-NEXT:    [[S2:%.*]] = load double, ptr [[SCEVGEP1]], align 8
; CHECK-NEXT:    [[DST_NEXT]] = getelementptr i8, ptr addrspace(5) [[DST]], i32 96
; CHECK-NEXT:    [[SRC_NEXT]] = getelementptr i8, ptr [[SCEVGEP4]], i64 96
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq ptr addrspace(5) [[DST]], [[SCRATCH]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %src = phi ptr [ null, %entry ], [ %src.next, %loop ]
  %dst = phi ptr addrspace(5) [ %scratch, %entry ], [ %dst.next, %loop ]
  %d0 = load double, ptr addrspace(5) %dst, align 8
  %s0 = load double, ptr %src, align 8
  %dst.1 = getelementptr i8, ptr addrspace(5) %dst, i32 8
  %d1 = load double, ptr addrspace(5) %dst.1, align 8
  %src.1 = getelementptr i8, ptr %src, i64 8
  %s1 = load double, ptr %src.1, align 8
  %dst.2 = getelementptr i8, ptr addrspace(5) %dst, i32 16
  %d2 = load double, ptr addrspace(5) %dst.2, align 8
  %src.2 = getelementptr i8, ptr %src, i64 16
  %s2 = load double, ptr %src.2, align 8
  %dst.next = getelementptr i8, ptr addrspace(5) %dst, i32 96
  %src.next = getelementptr i8, ptr %src, i64 96
  %done = icmp eq ptr addrspace(5) %dst, %scratch
  br i1 %done, label %exit, label %loop

exit:
  ret void
}
