// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
 // REQUIRES: amdgpu-registered-target
 // RUN: %clang_cc1 -triple amdgcn-unknown-unknown -target-cpu verde -emit-llvm -o - %s | FileCheck %s

#define __shared__ __attribute__((shared))

__shared__ __amdgpu_semaphore0_t sem;
__shared__ __amdgpu_semaphore0_t arr[2];
__shared__ struct {
  __amdgpu_semaphore0_t x;
  __amdgpu_semaphore0_t y;
} str;

__amdgpu_semaphore0_t *getSem();
void useSem(__amdgpu_semaphore0_t *);

// CHECK-LABEL: define {{[^@]+}}@_Z7testSemPu21__amdgpu_semaphore0_t
// CHECK-SAME: (ptr noundef [[P:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-NEXT:    [[RETVAL_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[RETVAL]] to ptr
// CHECK-NEXT:    [[P_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[P_ADDR]] to ptr
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR_ASCAST]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR_ASCAST]], align 8
// CHECK-NEXT:    call void @_Z6useSemPu21__amdgpu_semaphore0_t(ptr noundef [[TMP0]])
// CHECK-NEXT:    call void @_Z6useSemPu21__amdgpu_semaphore0_t(ptr noundef addrspacecast (ptr addrspace(1) @sem to ptr))
// CHECK-NEXT:    call void @_Z6useSemPu21__amdgpu_semaphore0_t(ptr noundef getelementptr inbounds ([2 x target("amdgcn.semaphore", 0)], ptr addrspacecast (ptr addrspace(1) @arr to ptr), i64 0, i64 1))
// CHECK-NEXT:    call void @_Z6useSemPu21__amdgpu_semaphore0_t(ptr noundef getelementptr inbounds nuw ([[STRUCT_ANON:%.*]], ptr addrspacecast (ptr addrspace(1) @str to ptr), i32 0, i32 1))
// CHECK-NEXT:    [[CALL:%.*]] = call noundef ptr @_Z6getSemv()
// CHECK-NEXT:    call void @_Z6useSemPu21__amdgpu_semaphore0_t(ptr noundef [[CALL]])
// CHECK-NEXT:    [[CALL1:%.*]] = call noundef ptr @_Z6getSemv()
// CHECK-NEXT:    ret ptr [[CALL1]]
//
__amdgpu_semaphore0_t *testSem(__amdgpu_semaphore0_t *p) {
  useSem(p);
  useSem(&sem);
  useSem(&arr[1]);
  useSem(&str.y);
  useSem(getSem());
  return getSem();
}
