// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature --check-attributes --check-globals
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-amd-amdhsa -x hip -fno-ident -fcuda-is-device -emit-llvm -o - %s | FileCheck %s

// COM: Most tests are in the OpenCL semastics, this is just a verification for HIP

#define __global__ __attribute__((global))

//.
// CHECK: @__hip_cuid_ = addrspace(1) global i8 0
// CHECK: @llvm.compiler.used = appending addrspace(1) global [1 x ptr] [ptr addrspacecast (ptr addrspace(1) @__hip_cuid_ to ptr)], section "llvm.metadata"
//.
// CHECK: Function Attrs: convergent mustprogress noinline norecurse nounwind optnone
// CHECK-LABEL: define {{[^@]+}}@_Z21kernel_waves_per_eu_0v
// CHECK-SAME: () #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
__global__ __attribute__((amdgpu_waves_per_eu(0))) void kernel_waves_per_eu_0() {}

// Equivalent to kernel_waves_per_eu_0.
// CHECK: Function Attrs: convergent mustprogress noinline norecurse nounwind optnone
// CHECK-LABEL: define {{[^@]+}}@_Z23kernel_waves_per_eu_0_0v
// CHECK-SAME: () #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
__global__ __attribute__((amdgpu_waves_per_eu(0, 0))) void kernel_waves_per_eu_0_0() {}

// CHECK: Function Attrs: convergent mustprogress noinline norecurse nounwind optnone
// CHECK-LABEL: define {{[^@]+}}@_Z23kernel_waves_per_eu_0_4v
// CHECK-SAME: () #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
__global__ __attribute__((amdgpu_waves_per_eu(0, 4))) void kernel_waves_per_eu_0_4() {}

// CHECK: Function Attrs: convergent mustprogress noinline norecurse nounwind optnone
// CHECK-LABEL: define {{[^@]+}}@_Z23kernel_waves_per_eu_1_4v
// CHECK-SAME: () #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
__global__ __attribute__((amdgpu_waves_per_eu(1, 4))) void kernel_waves_per_eu_1_4() {}
//.
// CHECK: attributes #[[ATTR0]] = { convergent mustprogress noinline norecurse nounwind optnone "amdgpu-flat-work-group-size"="1,1024" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "uniform-work-group-size"="true" }
// CHECK: attributes #[[ATTR1]] = { convergent mustprogress noinline norecurse nounwind optnone "amdgpu-flat-work-group-size"="1,1024" "amdgpu-waves-per-eu"="0,4" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "uniform-work-group-size"="true" }
// CHECK: attributes #[[ATTR2]] = { convergent mustprogress noinline norecurse nounwind optnone "amdgpu-flat-work-group-size"="1,1024" "amdgpu-waves-per-eu"="1,4" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "uniform-work-group-size"="true" }
//.
// CHECK: [[META0:![0-9]+]] = !{i32 1, !"amdhsa_code_object_version", i32 600}
// CHECK: [[META1:![0-9]+]] = !{i32 1, !"amdgpu_printf_kind", !"hostcall"}
// CHECK: [[META2:![0-9]+]] = !{i32 1, !"wchar_size", i32 4}
//.
