// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-amd-amdhsa -target-cpu gfx950 -emit-llvm -fcuda-is-device -o - %s | FileCheck %s

#define __device__ __attribute__((device))

typedef _Float16 v4h __attribute__((ext_vector_type(4)));

// ds_read_tr16_b64_v4f16: _ExtVector<4, _Float16>(_ExtVector<4, _Float16> address_space<3> *)
// CHECK-LABEL: define dso_local void @_Z27test_ds_read_tr16_b64_v4f16PDv4_DF16_PU3AS3S_(
// CHECK-SAME: ptr noundef [[OUT:%.*]], ptr addrspace(3) noundef [[INPTR:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[OUT_ADDR:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-NEXT:    [[INPTR_ADDR:%.*]] = alloca ptr addrspace(3), align 4, addrspace(5)
// CHECK-NEXT:    [[OUT_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[OUT_ADDR]] to ptr
// CHECK-NEXT:    [[INPTR_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[INPTR_ADDR]] to ptr
// CHECK-NEXT:    store ptr [[OUT]], ptr [[OUT_ADDR_ASCAST]], align 8
// CHECK-NEXT:    store ptr addrspace(3) [[INPTR]], ptr [[INPTR_ADDR_ASCAST]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(3), ptr [[INPTR_ADDR_ASCAST]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call contract <4 x half> @llvm.amdgcn.ds.read.tr16.b64.v4f16(ptr addrspace(3) [[TMP0]])
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[OUT_ADDR_ASCAST]], align 8
// CHECK-NEXT:    store <4 x half> [[TMP1]], ptr [[TMP2]], align 8
// CHECK-NEXT:    ret void
//
__device__ void test_ds_read_tr16_b64_v4f16(v4h *out, v4h __attribute__((address_space(3))) *inptr) {
  *out = __builtin_amdgcn_ds_read_tr16_b64_v4f16(inptr);
}
