// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-amd-amdhsa -target-cpu gfx1250 -emit-llvm -fcuda-is-device -o - %s | FileCheck %s

#define __device__ __attribute__((device))

typedef _Float16 v8h __attribute__((ext_vector_type(8)));

// global_load_tr16_b128_v8f16: _ExtVector<8, _Float16>(_ExtVector<8, _Float16> address_space<1> *)
// Requires gfx1250-insts,wavefrontsize32
// CHECK-LABEL: define dso_local void @_Z32test_global_load_tr16_b128_v8f16PDv8_DF16_PU3AS1S_(
// CHECK-SAME: ptr noundef [[OUT:%.*]], ptr addrspace(1) noundef [[INPTR:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[OUT_ADDR:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-NEXT:    [[INPTR_ADDR:%.*]] = alloca ptr addrspace(1), align 8, addrspace(5)
// CHECK-NEXT:    [[OUT_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[OUT_ADDR]] to ptr
// CHECK-NEXT:    [[INPTR_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[INPTR_ADDR]] to ptr
// CHECK-NEXT:    store ptr [[OUT]], ptr [[OUT_ADDR_ASCAST]], align 8
// CHECK-NEXT:    store ptr addrspace(1) [[INPTR]], ptr [[INPTR_ADDR_ASCAST]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(1), ptr [[INPTR_ADDR_ASCAST]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = call contract <8 x half> @llvm.amdgcn.global.load.tr.b128.v8f16(ptr addrspace(1) [[TMP0]])
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[OUT_ADDR_ASCAST]], align 8
// CHECK-NEXT:    store <8 x half> [[TMP1]], ptr [[TMP2]], align 16
// CHECK-NEXT:    ret void
//
__device__ void test_global_load_tr16_b128_v8f16(v8h *out, v8h __attribute__((address_space(1))) *inptr) {
  *out = __builtin_amdgcn_global_load_tr16_b128_v8f16(inptr);
}

// ds_load_tr16_b128_v8f16: _ExtVector<8, _Float16>(_ExtVector<8, _Float16> address_space<3> *)
// Requires gfx1250-insts,wavefrontsize32
// CHECK-LABEL: define dso_local void @_Z28test_ds_load_tr16_b128_v8f16PDv8_DF16_PU3AS3S_(
// CHECK-SAME: ptr noundef [[OUT:%.*]], ptr addrspace(3) noundef [[INPTR:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[OUT_ADDR:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-NEXT:    [[INPTR_ADDR:%.*]] = alloca ptr addrspace(3), align 4, addrspace(5)
// CHECK-NEXT:    [[OUT_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[OUT_ADDR]] to ptr
// CHECK-NEXT:    [[INPTR_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[INPTR_ADDR]] to ptr
// CHECK-NEXT:    store ptr [[OUT]], ptr [[OUT_ADDR_ASCAST]], align 8
// CHECK-NEXT:    store ptr addrspace(3) [[INPTR]], ptr [[INPTR_ADDR_ASCAST]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(3), ptr [[INPTR_ADDR_ASCAST]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call contract <8 x half> @llvm.amdgcn.ds.load.tr16.b128.v8f16(ptr addrspace(3) [[TMP0]])
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[OUT_ADDR_ASCAST]], align 8
// CHECK-NEXT:    store <8 x half> [[TMP1]], ptr [[TMP2]], align 16
// CHECK-NEXT:    ret void
//
__device__ void test_ds_load_tr16_b128_v8f16(v8h *out, v8h __attribute__((address_space(3))) *inptr) {
  *out = __builtin_amdgcn_ds_load_tr16_b128_v8f16(inptr);
}

// tanhh: _Float16(_Float16)
// Requires tanh-insts
// CHECK-LABEL: define dso_local void @_Z10test_tanhhPDF16_DF16_(
// CHECK-SAME: ptr noundef [[OUT:%.*]], half noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[OUT_ADDR:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca half, align 2, addrspace(5)
// CHECK-NEXT:    [[OUT_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[OUT_ADDR]] to ptr
// CHECK-NEXT:    [[A_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[A_ADDR]] to ptr
// CHECK-NEXT:    store ptr [[OUT]], ptr [[OUT_ADDR_ASCAST]], align 8
// CHECK-NEXT:    store half [[A]], ptr [[A_ADDR_ASCAST]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load half, ptr [[A_ADDR_ASCAST]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call contract half @llvm.amdgcn.tanh.f16(half [[TMP0]])
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[OUT_ADDR_ASCAST]], align 8
// CHECK-NEXT:    store half [[TMP1]], ptr [[TMP2]], align 2
// CHECK-NEXT:    ret void
//
__device__ void test_tanhh(_Float16 *out, _Float16 a) {
  *out = __builtin_amdgcn_tanhh(a);
}
