// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang --cuda-device-only -nogpuinc -nogpulib -emit-llvm -S -o - %s | FileCheck %s
#include <math.h>
#define __device__ __attribute__((device))

// CHECK-LABEL: define hidden void @_Z9my_kernelv(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[D1:%.*]] = alloca float, align 4, addrspace(5)
// CHECK-NEXT:    [[D2:%.*]] = alloca float, align 4, addrspace(5)
// CHECK-NEXT:    [[D1_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[D1]] to ptr
// CHECK-NEXT:    [[D2_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[D2]] to ptr
// CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.amdgcn.frexp.exp.i32.f64(double 1.600000e+01)
// CHECK-NEXT:    [[TMP1:%.*]] = add nsw i32 [[TMP0]], -1
// CHECK-NEXT:    [[TMP2:%.*]] = sitofp i32 [[TMP1]] to double
// CHECK-NEXT:    [[TMP3:%.*]] = call contract double @llvm.fabs.f64(double 1.600000e+01)
// CHECK-NEXT:    [[TMP4:%.*]] = fcmp contract one double [[TMP3]], 0x7FF0000000000000
// CHECK-NEXT:    [[TMP5:%.*]] = select contract i1 [[TMP4]], double [[TMP2]], double [[TMP3]]
// CHECK-NEXT:    [[TMP6:%.*]] = select contract i1 false, double 0xFFF0000000000000, double [[TMP5]]
// CHECK-NEXT:    [[CONV:%.*]] = fptrunc contract double [[TMP6]] to float
// CHECK-NEXT:    store float [[CONV]], ptr [[D1_ASCAST]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = call contract double @llvm.ldexp.f64.i32(double 1.600000e+01, i32 10)
// CHECK-NEXT:    [[CONV1:%.*]] = fptrunc contract double [[TMP7]] to float
// CHECK-NEXT:    store float [[CONV1]], ptr [[D2_ASCAST]], align 4
// CHECK-NEXT:    ret void
//
__device__ void my_kernel(){

  float D1 = __builtin_logb((float)16);
  float D2 = __builtin_scalbn((float)16, 10);
}

