// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -triple amdgcn-amd-amdhsa -target-cpu gfx1300 -x hip -emit-llvm -fcuda-is-device \
// RUN:   -o - %s | FileCheck %s

// Check that the amdgpu-spatial-cluster
// IR attributes are generated correctly.

#define __global__ __attribute__((global))
#define __shared__ __attribute__((shared))
#define __exp_amd_wavegroup_kernel(num_wavegroups, wave_size, block_x, block_y, block_z) \
    __attribute__((amdgpu_wavegroup_kernel(num_wavegroups, wave_size, block_x, block_y, block_z)))
#define __exp_amd_spatial_cluster__ __attribute__((amdgpu_spatial_cluster_kernel))
#define __cluster_dims__(...) __attribute__((cluster_dims(__VA_ARGS__)))

__shared__ __amdgpu_semaphore0_t sema;
__shared__ __amdgpu_semaphore0_t sema_refl;

__exp_amd_wavegroup_kernel(
    /* num_wavegroups */ 4,
    /* wave size */ 32,
    /* block size */ 128, 1, 1)
__cluster_dims__(8, 1, 1)
__exp_amd_spatial_cluster__
__global__
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z37test_amdgcn_spatial_cluster_send_nextPiS_(
// CHECK-SAME: ptr addrspace(1) noundef [[DST_COERCE:%.*]], ptr addrspace(1) noundef [[DST_REFL_COERCE:%.*]]) #[[ATTR0:[0-9]+]] !reqd_work_group_size [[META4:![0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[DST:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-NEXT:    [[DST_REFL:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-NEXT:    [[DST_ADDR:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-NEXT:    [[DST_REFL_ADDR:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-NEXT:    [[DST_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DST]] to ptr
// CHECK-NEXT:    [[DST_REFL_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DST_REFL]] to ptr
// CHECK-NEXT:    [[DST_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DST_ADDR]] to ptr
// CHECK-NEXT:    [[DST_REFL_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DST_REFL_ADDR]] to ptr
// CHECK-NEXT:    store ptr addrspace(1) [[DST_COERCE]], ptr [[DST_ASCAST]], align 8
// CHECK-NEXT:    [[DST1:%.*]] = load ptr, ptr [[DST_ASCAST]], align 8
// CHECK-NEXT:    store ptr addrspace(1) [[DST_REFL_COERCE]], ptr [[DST_REFL_ASCAST]], align 8
// CHECK-NEXT:    [[DST_REFL2:%.*]] = load ptr, ptr [[DST_REFL_ASCAST]], align 8
// CHECK-NEXT:    store ptr [[DST1]], ptr [[DST_ADDR_ASCAST]], align 8
// CHECK-NEXT:    store ptr [[DST_REFL2]], ptr [[DST_REFL_ADDR_ASCAST]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[DST_ADDR_ASCAST]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = addrspacecast ptr [[TMP0]] to ptr addrspace(10)
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[DST_REFL_ADDR_ASCAST]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = addrspacecast ptr [[TMP2]] to ptr addrspace(10)
// CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.next(i32 42, ptr addrspace(10) [[TMP1]], ptr addrspace(3) @sema, ptr addrspace(10) [[TMP3]], ptr addrspace(3) @sema_refl, i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_spatial_cluster_send_next(int *dst, int *dst_refl)
{
  __builtin_amdgcn_spatial_cluster_send_next(42, dst, &sema, dst_refl, &sema_refl, 0);
}

__exp_amd_wavegroup_kernel(
    /* num_wavegroups */ 4,
    /* wave size */ 32,
    /* block size */ 128, 1, 1)
__cluster_dims__(8, 1, 1)
__exp_amd_spatial_cluster__
__global__
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z37test_amdgcn_spatial_cluster_send_prevPiS_(
// CHECK-SAME: ptr addrspace(1) noundef [[DST_COERCE:%.*]], ptr addrspace(1) noundef [[DST_REFL_COERCE:%.*]]) #[[ATTR0]] !reqd_work_group_size [[META4]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[DST:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-NEXT:    [[DST_REFL:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-NEXT:    [[DST_ADDR:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-NEXT:    [[DST_REFL_ADDR:%.*]] = alloca ptr, align 8, addrspace(5)
// CHECK-NEXT:    [[DST_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DST]] to ptr
// CHECK-NEXT:    [[DST_REFL_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DST_REFL]] to ptr
// CHECK-NEXT:    [[DST_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DST_ADDR]] to ptr
// CHECK-NEXT:    [[DST_REFL_ADDR_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DST_REFL_ADDR]] to ptr
// CHECK-NEXT:    store ptr addrspace(1) [[DST_COERCE]], ptr [[DST_ASCAST]], align 8
// CHECK-NEXT:    [[DST1:%.*]] = load ptr, ptr [[DST_ASCAST]], align 8
// CHECK-NEXT:    store ptr addrspace(1) [[DST_REFL_COERCE]], ptr [[DST_REFL_ASCAST]], align 8
// CHECK-NEXT:    [[DST_REFL2:%.*]] = load ptr, ptr [[DST_REFL_ASCAST]], align 8
// CHECK-NEXT:    store ptr [[DST1]], ptr [[DST_ADDR_ASCAST]], align 8
// CHECK-NEXT:    store ptr [[DST_REFL2]], ptr [[DST_REFL_ADDR_ASCAST]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[DST_ADDR_ASCAST]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = addrspacecast ptr [[TMP0]] to ptr addrspace(10)
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[DST_REFL_ADDR_ASCAST]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = addrspacecast ptr [[TMP2]] to ptr addrspace(10)
// CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.send.prev(i32 42, ptr addrspace(10) [[TMP1]], ptr addrspace(3) @sema, ptr addrspace(10) [[TMP3]], ptr addrspace(3) @sema_refl, i32 0)
// CHECK-NEXT:    ret void
//
void test_amdgcn_spatial_cluster_send_prev(int *dst, int *dst_refl)
{
  __builtin_amdgcn_spatial_cluster_send_prev(42, dst, &sema, dst_refl, &sema_refl, 0);
}

__exp_amd_wavegroup_kernel(
    /* num_wavegroups */ 4,
    /* wave size */ 32,
    /* block size */ 128, 1, 1)
__cluster_dims__(8, 1, 1)
__exp_amd_spatial_cluster__
__global__
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z39test_amdgcn_spatial_cluster_signal_nextv(
// CHECK-SAME: ) #[[ATTR0]] !reqd_work_group_size [[META4]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.signal.next(ptr addrspace(3) @sema, ptr addrspace(3) @sema_refl)
// CHECK-NEXT:    ret void
//
void test_amdgcn_spatial_cluster_signal_next()
{
  __builtin_amdgcn_spatial_cluster_signal_next(&sema, &sema_refl);
}

__exp_amd_wavegroup_kernel(
    /* num_wavegroups */ 4,
    /* wave size */ 32,
    /* block size */ 128, 1, 1)
__cluster_dims__(8, 1, 1)
__exp_amd_spatial_cluster__
__global__
// CHECK-LABEL: define dso_local amdgpu_kernel void @_Z39test_amdgcn_spatial_cluster_signal_prevv(
// CHECK-SAME: ) #[[ATTR0]] !reqd_work_group_size [[META4]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    call void @llvm.amdgcn.spatial.cluster.signal.next(ptr addrspace(3) @sema, ptr addrspace(3) @sema_refl)
// CHECK-NEXT:    ret void
//
void test_amdgcn_spatial_cluster_signal_prev()
{
  __builtin_amdgcn_spatial_cluster_signal_next(&sema, &sema_refl);
}
//.
// CHECK: [[META4]] = !{i32 128, i32 1, i32 1}
//.
