; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=function-attrs -S | FileCheck %s

define ptr @a(ptr %p) {
; CHECK-LABEL: define ptr @a(
; CHECK-SAME: ptr readonly captures(none) [[P:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP:%.*]] = load ptr, ptr [[P]], align 8
; CHECK-NEXT:    ret ptr [[TMP]]
;
  %tmp = load ptr, ptr %p
  ret ptr %tmp
}

define ptr @b(ptr %q) {
; CHECK-LABEL: define ptr @b(
; CHECK-SAME: ptr [[Q:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    [[MEM:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[Q]], ptr [[MEM]], align 8
; CHECK-NEXT:    [[TMP:%.*]] = call ptr @a(ptr [[MEM]])
; CHECK-NEXT:    ret ptr [[TMP]]
;
  %mem = alloca ptr
  store ptr %q, ptr %mem
  %tmp = call ptr @a(ptr %mem)
  ret ptr %tmp
}

@g = global i32 0
define ptr @c(ptr %r) {
; CHECK-LABEL: define ptr @c(
; CHECK-SAME: ptr readnone returned captures(address_is_null, ret: address, provenance) [[R:%.*]]) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:    [[A:%.*]] = icmp eq ptr [[R]], null
; CHECK-NEXT:    store i32 1, ptr @g, align 4
; CHECK-NEXT:    ret ptr [[R]]
;
  %a = icmp eq ptr %r, null
  store i32 1, ptr @g
  ret ptr %r
}
