; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-attributes --version 5
; RUN: opt < %s -passes=norecurse-lto-inference -S | FileCheck %s

; This test includes a call to a library function which is not marked as
; NoCallback. All functions except main() are internal and main is marked
; norecurse, so as to not block norecurse to be added to bob().

@.str = private unnamed_addr constant [12 x i8] c"Hello World\00", align 1

; Function Attrs: nofree noinline nounwind uwtable
define internal void @bob() {
; CHECK: Function Attrs: norecurse
; CHECK-LABEL: define internal void @bob(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CALL:%.*]] = tail call i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str)
; CHECK-NEXT:    ret void
;
entry:
  %call = tail call i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str)
  ret void
}

; Function Attrs: nofree nounwind
declare noundef i32 @printf(ptr noundef readonly captures(none), ...)

; Function Attrs: nofree norecurse nounwind uwtable
define dso_local noundef i32 @main() norecurse {
; CHECK: Function Attrs: norecurse
; CHECK-LABEL: define dso_local noundef i32 @main(
; CHECK-SAME: ) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @bob()
; CHECK-NEXT:    ret i32 0
;
entry:
  tail call void @bob()
  ret i32 0
}
