; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-attributes --version 5
; RUN: opt < %s -passes="lto<O2>" -S | FileCheck %s

; This test includes a call graph with multiple SCCs. The purpose of this is
; to check that norecurse is not added when a function is part of non-singular
; SCC.
; There are three different SCCs in this test:
;  SCC#1:  main, foo, bar, foo1, bar1
;  SCC#2:  bar2, bar3, bar4
;  SCC#3:  baz, fun
; None of these functions should be marked as norecurse

; Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
define internal void @bar1() local_unnamed_addr #0 {
; CHECK: Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
; CHECK-LABEL: define internal fastcc void @bar1(
; CHECK-SAME: ) unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CALL:%.*]] = tail call i32 @main()
; CHECK-NEXT:    ret void
;
entry:
  %call = tail call i32 @main()
  ret void
}

; Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
define dso_local noundef i32 @main() local_unnamed_addr #0 {
; CHECK: Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
; CHECK-LABEL: define dso_local noundef i32 @main(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call fastcc void @foo()
; CHECK-NEXT:    tail call fastcc void @bar2()
; CHECK-NEXT:    tail call fastcc void @baz()
; CHECK-NEXT:    ret i32 0
;
entry:
  tail call void @foo()
  tail call void @bar2()
  tail call void @baz()
  ret i32 0
}

; Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
define internal void @foo1() local_unnamed_addr #0 {
; CHECK: Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
; CHECK-LABEL: define internal fastcc void @foo1(
; CHECK-SAME: ) unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call fastcc void @bar1()
; CHECK-NEXT:    ret void
;
entry:
  tail call void @bar1()
  ret void
}

; Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
define internal void @bar() local_unnamed_addr #0 {
; CHECK: Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
; CHECK-LABEL: define internal fastcc void @bar(
; CHECK-SAME: ) unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call fastcc void @foo1()
; CHECK-NEXT:    ret void
;
entry:
  tail call void @foo1()
  ret void
}

; Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
define internal void @foo() local_unnamed_addr #0 {
; CHECK: Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
; CHECK-LABEL: define internal fastcc void @foo(
; CHECK-SAME: ) unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call fastcc void @bar()
; CHECK-NEXT:    ret void
;
entry:
  tail call void @bar()
  ret void
}

; Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
define internal void @bar4() local_unnamed_addr #0 {
; CHECK: Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
; CHECK-LABEL: define internal fastcc void @bar4(
; CHECK-SAME: ) unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call fastcc void @bar2()
; CHECK-NEXT:    ret void
;
entry:
  tail call void @bar2()
  ret void
}

; Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
define internal void @bar2() local_unnamed_addr #0 {
; CHECK: Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
; CHECK-LABEL: define internal fastcc void @bar2(
; CHECK-SAME: ) unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call fastcc void @bar3()
; CHECK-NEXT:    ret void
;
entry:
  tail call void @bar3()
  ret void
}

; Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
define internal void @bar3() local_unnamed_addr #0 {
; CHECK: Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
; CHECK-LABEL: define internal fastcc void @bar3(
; CHECK-SAME: ) unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call fastcc void @bar4()
; CHECK-NEXT:    ret void
;
entry:
  tail call void @bar4()
  ret void
}

; Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
define internal void @fun() local_unnamed_addr #0 {
; CHECK: Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
; CHECK-LABEL: define internal fastcc void @fun(
; CHECK-SAME: ) unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call fastcc void @baz()
; CHECK-NEXT:    ret void
;
entry:
  tail call void @baz()
  ret void
}

; Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
define internal void @baz() local_unnamed_addr #0 {
; CHECK: Function Attrs: nofree noinline nosync nounwind memory(none) uwtable
; CHECK-LABEL: define internal fastcc void @baz(
; CHECK-SAME: ) unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call fastcc void @fun()
; CHECK-NEXT:    ret void
;
entry:
  tail call void @fun()
  ret void
}

attributes #0 = { nofree noinline nosync nounwind memory(none) uwtable }
