; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-attributes --version 5
; RUN: opt < %s -passes="lto<O2>" -S | FileCheck %s

@.str = private unnamed_addr constant [7 x i8] c"Hello \00", align 1

; Function Attrs: nofree noinline nounwind uwtable vscale_range(1,16)
define internal void @bob() local_unnamed_addr #0 {
; CHECK: Function Attrs: nofree noinline norecurse nounwind uwtable
; CHECK-LABEL: define internal fastcc void @bob(
; CHECK-SAME: ) unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str)
; CHECK-NEXT:    ret void
;
  %1 = tail call i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str)
  ret void
}

; Function Attrs: nofree nounwind
declare noundef i32 @printf(ptr nocapture noundef readonly, ...) local_unnamed_addr #1

; Function Attrs: nofree norecurse nounwind uwtable vscale_range(1,16)
define dso_local noundef i32 @main() local_unnamed_addr #2 {
; CHECK: Function Attrs: nofree norecurse nounwind uwtable
; CHECK-LABEL: define dso_local noundef i32 @main(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:    tail call fastcc void @bob()
; CHECK-NEXT:    ret i32 0
;
  tail call void @bob()
  ret i32 0
}


attributes #0 = { nofree noinline nounwind uwtable }
attributes #1 = { nofree nounwind }
attributes #2 = { nofree norecurse nounwind uwtable }
