; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-attributes --version 5
; RUN: opt < %s -passes=norecurse-lto-inference -S | FileCheck %s

; This test includes a call graph with multiple SCCs. The purpose of this is
; to check that norecurse is added to a function which calls a function which
; is indirectly recursive but is not part of the recursive chain.
; There are two SCCs in this test:
;  SCC#1:  bar2, bar3, bar4
;  SCC#2:  baz, fun
; f1() calls bar2 and baz, both of which are part of some indirect recursive
; chain. but does not call back f1() and hence f1() can be marked as
; norecurse.

define dso_local noundef i32 @main() norecurse {
; CHECK: Function Attrs: norecurse
; CHECK-LABEL: define dso_local noundef i32 @main(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @f1()
; CHECK-NEXT:    ret i32 0
;
entry:
  tail call void @f1()
  ret i32 0
}

define internal void @f1() {
; CHECK: Function Attrs: norecurse
; CHECK-LABEL: define internal void @f1(
; CHECK-SAME: ) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @bar2()
; CHECK-NEXT:    tail call void @baz()
; CHECK-NEXT:    ret void
;
entry:
  tail call void @bar2()
  tail call void @baz()
  ret void
}

define internal void @bar4() {
; CHECK-LABEL: define internal void @bar4() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @bar2()
; CHECK-NEXT:    ret void
;
entry:
  tail call void @bar2()
  ret void
}

define internal void @bar2() {
; CHECK-LABEL: define internal void @bar2() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @bar3()
; CHECK-NEXT:    ret void
;
entry:
  tail call void @bar3()
  ret void
}

define internal void @bar3() {
; CHECK-LABEL: define internal void @bar3() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @bar4()
; CHECK-NEXT:    ret void
;
entry:
  tail call void @bar4()
  ret void
}

define internal void @fun() {
; CHECK-LABEL: define internal void @fun() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @baz()
; CHECK-NEXT:    ret void
;
entry:
  tail call void @baz()
  ret void
}

define internal void @baz() {
; CHECK-LABEL: define internal void @baz() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @fun()
; CHECK-NEXT:    ret void
;
entry:
  tail call void @fun()
  ret void
}
