; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=function-attrs -S < %s | FileCheck %s

; This checks for a previously existing iterator wraparound bug in
; FunctionAttrs, and in the process covers corner cases with varargs.

declare void @llvm.va_start(ptr)
declare void @llvm.va_end(ptr)

define void @va_func(ptr readonly %b, ...) readonly nounwind willreturn {
; CHECK-LABEL: define void @va_func(
; CHECK-SAME: ptr readonly captures(none) [[B:%.*]], ...) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VALIST:%.*]] = alloca i8, align 1
; CHECK-NEXT:    call void @llvm.va_start.p0(ptr [[VALIST]])
; CHECK-NEXT:    call void @llvm.va_end.p0(ptr [[VALIST]])
; CHECK-NEXT:    [[X:%.*]] = call i32 @caller(ptr [[B]])
; CHECK-NEXT:    ret void
;
  entry:
  %valist = alloca i8
  call void @llvm.va_start(ptr %valist)
  call void @llvm.va_end(ptr %valist)
  %x = call i32 @caller(ptr %b)
  ret void
}

define i32 @caller(ptr %x) {
; CHECK-LABEL: define noundef i32 @caller(
; CHECK-SAME: ptr readonly captures(address) [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void (ptr, ...) @va_func(ptr null, i32 0, i32 0, i32 0, ptr [[X]])
; CHECK-NEXT:    ret i32 42
;
  entry:
  call void(ptr,...) @va_func(ptr null, i32 0, i32 0, i32 0, ptr %x)
  ret i32 42
}

define void @va_func2(ptr readonly %b, ...) {
; CHECK-LABEL: define void @va_func2(
; CHECK-SAME: ptr readonly captures(address) [[B:%.*]], ...) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VALIST:%.*]] = alloca i8, align 1
; CHECK-NEXT:    call void @llvm.va_start.p0(ptr [[VALIST]])
; CHECK-NEXT:    call void @llvm.va_end.p0(ptr [[VALIST]])
; CHECK-NEXT:    [[X:%.*]] = call i32 @caller(ptr [[B]])
; CHECK-NEXT:    ret void
;
  entry:
  %valist = alloca i8
  call void @llvm.va_start(ptr %valist)
  call void @llvm.va_end(ptr %valist)
  %x = call i32 @caller(ptr %b)
  ret void
}

define i32 @caller2(ptr %x, ptr %y) {
; CHECK-LABEL: define noundef i32 @caller2(
; CHECK-SAME: ptr readonly captures(address) [[X:%.*]], ptr [[Y:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void (ptr, ...) @va_func2(ptr [[X]], i32 0, i32 0, i32 0, ptr [[Y]])
; CHECK-NEXT:    ret i32 42
;
  entry:
  call void(ptr,...) @va_func2(ptr %x, i32 0, i32 0, i32 0, ptr %y)
  ret i32 42
}

