; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-attributes --check-globals --version 2
; RUN: opt -passes=function-attrs -S < %s | FileCheck --check-prefixes=FNATTRS %s
; RUN: opt -passes=attributor-light -S < %s | FileCheck --check-prefixes=ATTRIBUTOR %s

define i32 @test_read_errno() {
; FNATTRS: Function Attrs: mustprogress nofree nosync nounwind willreturn memory(errnomem: read)
; FNATTRS-LABEL: define i32 @test_read_errno
; FNATTRS-SAME: () #[[ATTR0:[0-9]+]] {
; FNATTRS-NEXT:    [[CALL:%.*]] = call ptr @__errno_location() #[[ATTR4:[0-9]+]]
; FNATTRS-NEXT:    [[ERRNO:%.*]] = load i32, ptr [[CALL]], align 4
; FNATTRS-NEXT:    ret i32 [[ERRNO]]
;
; ATTRIBUTOR: Function Attrs: mustprogress nofree nosync nounwind willreturn memory(read)
; ATTRIBUTOR-LABEL: define i32 @test_read_errno
; ATTRIBUTOR-SAME: () #[[ATTR0:[0-9]+]] {
; ATTRIBUTOR-NEXT:    [[CALL:%.*]] = call ptr @__errno_location() #[[ATTR4:[0-9]+]]
; ATTRIBUTOR-NEXT:    [[ERRNO:%.*]] = load i32, ptr [[CALL]], align 4
; ATTRIBUTOR-NEXT:    ret i32 [[ERRNO]]
;
  %call = call ptr @__errno_location() #2
  %errno = load i32, ptr %call
  ret i32 %errno
}

define ptr @test_write_errno() {
; FNATTRS: Function Attrs: mustprogress nofree nosync nounwind willreturn memory(errnomem: write)
; FNATTRS-LABEL: define noundef ptr @test_write_errno
; FNATTRS-SAME: () #[[ATTR1:[0-9]+]] {
; FNATTRS-NEXT:    [[CALL:%.*]] = call ptr @__errno_location() #[[ATTR4]]
; FNATTRS-NEXT:    store i32 0, ptr [[CALL]], align 4
; FNATTRS-NEXT:    ret ptr [[CALL]]
;
; ATTRIBUTOR: Function Attrs: mustprogress nofree nosync nounwind willreturn memory(write)
; ATTRIBUTOR-LABEL: define ptr @test_write_errno
; ATTRIBUTOR-SAME: () #[[ATTR1:[0-9]+]] {
; ATTRIBUTOR-NEXT:    [[CALL:%.*]] = call ptr @__errno_location() #[[ATTR4]]
; ATTRIBUTOR-NEXT:    store i32 0, ptr [[CALL]], align 4
; ATTRIBUTOR-NEXT:    ret ptr [[CALL]]
;
  %call = call ptr @__errno_location() #2
  store i32 0, ptr %call
  ret ptr %call
}

define i32 @test_readwrite_errno() {
; FNATTRS: Function Attrs: mustprogress nofree nosync nounwind willreturn memory(errnomem: readwrite)
; FNATTRS-LABEL: define i32 @test_readwrite_errno
; FNATTRS-SAME: () #[[ATTR2:[0-9]+]] {
; FNATTRS-NEXT:    [[CALL:%.*]] = call ptr @__errno_location() #[[ATTR4]]
; FNATTRS-NEXT:    store i32 0, ptr [[CALL]], align 4
; FNATTRS-NEXT:    [[ERRNO:%.*]] = load i32, ptr [[CALL]], align 4
; FNATTRS-NEXT:    ret i32 [[ERRNO]]
;
; ATTRIBUTOR: Function Attrs: mustprogress nofree nosync nounwind willreturn
; ATTRIBUTOR-LABEL: define i32 @test_readwrite_errno
; ATTRIBUTOR-SAME: () #[[ATTR2:[0-9]+]] {
; ATTRIBUTOR-NEXT:    [[CALL:%.*]] = call ptr @__errno_location() #[[ATTR4]]
; ATTRIBUTOR-NEXT:    store i32 0, ptr [[CALL]], align 4
; ATTRIBUTOR-NEXT:    [[ERRNO:%.*]] = load i32, ptr [[CALL]], align 4
; ATTRIBUTOR-NEXT:    ret i32 [[ERRNO]]
;
  %call = call ptr @__errno_location() #2
  store i32 0, ptr %call
  %errno = load i32, ptr %call
  ret i32 %errno
}

declare ptr @__errno_location() #1

attributes #1 = { mustprogress nofree nosync nounwind willreturn memory(none) }
attributes #2 = { nounwind willreturn memory(none) }
