; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-attributes --version 6
; RUN: opt -passes=function-attrs -S < %s | FileCheck --check-prefixes=FNATTRS %s
; RUN: opt -passes=attributor-light -S < %s | FileCheck --check-prefixes=ATTRIBUTOR %s

define i32 @test_read_errno_location() {
; FNATTRS: Function Attrs: nofree memory(errnomem: read)
; FNATTRS-LABEL: define i32 @test_read_errno_location(
; FNATTRS-SAME: ) #[[ATTR0:[0-9]+]] {
; FNATTRS-NEXT:    [[CALL:%.*]] = call ptr @__errno_location()
; FNATTRS-NEXT:    [[ERRNO:%.*]] = load i32, ptr [[CALL]], align 4
; FNATTRS-NEXT:    ret i32 [[ERRNO]]
;
; ATTRIBUTOR-LABEL: define i32 @test_read_errno_location() {
; ATTRIBUTOR-NEXT:    [[CALL:%.*]] = call ptr @__errno_location()
; ATTRIBUTOR-NEXT:    [[ERRNO:%.*]] = load i32, ptr [[CALL]], align 4
; ATTRIBUTOR-NEXT:    ret i32 [[ERRNO]]
;
  %call = call ptr @__errno_location()
  %errno = load i32, ptr %call
  ret i32 %errno
}

define ptr @test_write_errno_location() {
; FNATTRS: Function Attrs: memory(errnomem: write)
; FNATTRS-LABEL: define noundef ptr @test_write_errno_location(
; FNATTRS-SAME: ) #[[ATTR1:[0-9]+]] {
; FNATTRS-NEXT:    [[CALL:%.*]] = call ptr @__errno_location()
; FNATTRS-NEXT:    store i32 0, ptr [[CALL]], align 4
; FNATTRS-NEXT:    ret ptr [[CALL]]
;
; ATTRIBUTOR-LABEL: define ptr @test_write_errno_location() {
; ATTRIBUTOR-NEXT:    [[CALL:%.*]] = call ptr @__errno_location()
; ATTRIBUTOR-NEXT:    store i32 0, ptr [[CALL]], align 4
; ATTRIBUTOR-NEXT:    ret ptr [[CALL]]
;
  %call = call ptr @__errno_location()
  store i32 0, ptr %call
  ret ptr %call
}

define i32 @test_readwrite_errno_location() {
; FNATTRS: Function Attrs: memory(errnomem: readwrite)
; FNATTRS-LABEL: define i32 @test_readwrite_errno_location(
; FNATTRS-SAME: ) #[[ATTR2:[0-9]+]] {
; FNATTRS-NEXT:    [[CALL:%.*]] = call ptr @__errno_location()
; FNATTRS-NEXT:    store i32 0, ptr [[CALL]], align 4
; FNATTRS-NEXT:    [[ERRNO:%.*]] = load i32, ptr [[CALL]], align 4
; FNATTRS-NEXT:    ret i32 [[ERRNO]]
;
; ATTRIBUTOR-LABEL: define i32 @test_readwrite_errno_location() {
; ATTRIBUTOR-NEXT:    [[CALL:%.*]] = call ptr @__errno_location()
; ATTRIBUTOR-NEXT:    store i32 0, ptr [[CALL]], align 4
; ATTRIBUTOR-NEXT:    [[ERRNO:%.*]] = load i32, ptr [[CALL]], align 4
; ATTRIBUTOR-NEXT:    ret i32 [[ERRNO]]
;
  %call = call ptr @__errno_location()
  store i32 0, ptr %call
  %errno = load i32, ptr %call
  ret i32 %errno
}

declare ptr @__errno_location()
