# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv32 -mattr=+m,+v -run-pass=regbankselect \
# RUN:   -disable-gisel-legality-check -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck %s
# RUN: llc -mtriple=riscv64 -mattr=+m,+v -run-pass=regbankselect \
# RUN:   -disable-gisel-legality-check -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck %s

---
name:            icmp_nxv1i1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv1i1
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 1 x s1>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 1 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 1 x s1>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 1 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 1 x s1>) = G_IMPLICIT_DEF
    %1:_(<vscale x 1 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 1 x s1>), %0
    $v8 = COPY %1(<vscale x 1 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv2i1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv2i1
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 2 x s1>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 2 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 2 x s1>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 2 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 2 x s1>) = G_IMPLICIT_DEF
    %1:_(<vscale x 2 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 2 x s1>), %0
    $v8 = COPY %1(<vscale x 2 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv4i1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv4i1
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 4 x s1>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 4 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 4 x s1>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 4 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 4 x s1>) = G_IMPLICIT_DEF
    %1:_(<vscale x 4 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 4 x s1>), %0
    $v8 = COPY %1(<vscale x 4 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv8i1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv8i1
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 8 x s1>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 8 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 8 x s1>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 8 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 8 x s1>) = G_IMPLICIT_DEF
    %1:_(<vscale x 8 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 8 x s1>), %0
    $v8 = COPY %1(<vscale x 8 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv16i1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv16i1
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 16 x s1>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 16 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 16 x s1>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 16 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 16 x s1>) = G_IMPLICIT_DEF
    %1:_(<vscale x 16 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 16 x s1>), %0
    $v8 = COPY %1(<vscale x 16 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv32i1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv32i1
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 32 x s1>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 32 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 32 x s1>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 32 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 32 x s1>) = G_IMPLICIT_DEF
    %1:_(<vscale x 32 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 32 x s1>), %0
    $v8 = COPY %1(<vscale x 32 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv64i1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv64i1
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 64 x s1>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 64 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 64 x s1>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 64 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 64 x s1>) = G_IMPLICIT_DEF
    %1:_(<vscale x 64 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 64 x s1>), %0
    $v8 = COPY %1(<vscale x 64 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv1i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv1i8
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 1 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 1 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 1 x s8>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 1 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 1 x s8>) = G_IMPLICIT_DEF
    %1:_(<vscale x 1 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 1 x s8>), %0
    $v8 = COPY %1(<vscale x 1 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv2i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv2i8
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 2 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 2 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 2 x s8>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 2 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 2 x s8>) = G_IMPLICIT_DEF
    %1:_(<vscale x 2 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 2 x s8>), %0
    $v8 = COPY %1(<vscale x 2 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv4i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv4i8
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 4 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 4 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 4 x s8>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 4 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 4 x s8>) = G_IMPLICIT_DEF
    %1:_(<vscale x 4 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 4 x s8>), %0
    $v8 = COPY %1(<vscale x 4 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv8i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv8i8
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 8 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 8 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 8 x s8>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 8 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 8 x s8>) = G_IMPLICIT_DEF
    %1:_(<vscale x 8 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 8 x s8>), %0
    $v8 = COPY %1(<vscale x 8 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv16i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv16i8
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 16 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 16 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 16 x s8>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 16 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 16 x s8>) = G_IMPLICIT_DEF
    %1:_(<vscale x 16 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 16 x s8>), %0
    $v8 = COPY %1(<vscale x 16 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv32i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv32i8
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 32 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 32 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 32 x s8>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 32 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 32 x s8>) = G_IMPLICIT_DEF
    %1:_(<vscale x 32 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 32 x s8>), %0
    $v8 = COPY %1(<vscale x 32 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv64i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv64i8
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 64 x s8>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 64 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 64 x s8>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 64 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 64 x s8>) = G_IMPLICIT_DEF
    %1:_(<vscale x 64 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 64 x s8>), %0
    $v8 = COPY %1(<vscale x 64 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv1i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv1i16
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 1 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 1 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 1 x s16>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 1 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 1 x s16>) = G_IMPLICIT_DEF
    %1:_(<vscale x 1 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 1 x s16>), %0
    $v8 = COPY %1(<vscale x 1 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv2i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv2i16
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 2 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 2 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 2 x s16>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 2 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 2 x s16>) = G_IMPLICIT_DEF
    %1:_(<vscale x 2 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 2 x s16>), %0
    $v8 = COPY %1(<vscale x 2 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv4i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv4i16
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 4 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 4 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 4 x s16>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 4 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 4 x s16>) = G_IMPLICIT_DEF
    %1:_(<vscale x 4 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 4 x s16>), %0
    $v8 = COPY %1(<vscale x 4 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv8i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv8i16
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 8 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 8 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 8 x s16>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 8 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 8 x s16>) = G_IMPLICIT_DEF
    %1:_(<vscale x 8 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 8 x s16>), %0
    $v8 = COPY %1(<vscale x 8 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv16i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv16i16
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 16 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 16 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 16 x s16>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 16 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 16 x s16>) = G_IMPLICIT_DEF
    %1:_(<vscale x 16 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 16 x s16>), %0
    $v8 = COPY %1(<vscale x 16 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv32i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv32i16
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 32 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 32 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 32 x s16>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 32 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 32 x s16>) = G_IMPLICIT_DEF
    %1:_(<vscale x 32 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 32 x s16>), %0
    $v8 = COPY %1(<vscale x 32 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv1i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv1i32
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 1 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 1 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 1 x s32>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 1 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 1 x s32>) = G_IMPLICIT_DEF
    %1:_(<vscale x 1 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 1 x s32>), %0
    $v8 = COPY %1(<vscale x 1 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv2i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv2i32
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 2 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 2 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 2 x s32>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 2 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 2 x s32>) = G_IMPLICIT_DEF
    %1:_(<vscale x 2 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 2 x s32>), %0
    $v8 = COPY %1(<vscale x 2 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv4i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv4i32
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 4 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 4 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 4 x s32>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 4 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 4 x s32>) = G_IMPLICIT_DEF
    %1:_(<vscale x 4 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 4 x s32>), %0
    $v8 = COPY %1(<vscale x 4 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv8i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv8i32
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 8 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 8 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 8 x s32>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 8 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 8 x s32>) = G_IMPLICIT_DEF
    %1:_(<vscale x 8 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 8 x s32>), %0
    $v8 = COPY %1(<vscale x 8 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv16i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv16i32
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 16 x s32>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 16 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 16 x s32>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 16 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 16 x s32>) = G_IMPLICIT_DEF
    %1:_(<vscale x 16 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 16 x s32>), %0
    $v8 = COPY %1(<vscale x 16 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv1i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv1i64
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 1 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 1 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 1 x s64>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 1 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 1 x s64>) = G_IMPLICIT_DEF
    %1:_(<vscale x 1 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 1 x s64>), %0
    $v8 = COPY %1(<vscale x 1 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv2i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv2i64
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 2 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 2 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 2 x s64>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 2 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 2 x s64>) = G_IMPLICIT_DEF
    %1:_(<vscale x 2 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 2 x s64>), %0
    $v8 = COPY %1(<vscale x 2 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv4i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv4i64
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 4 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 4 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 4 x s64>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 4 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 4 x s64>) = G_IMPLICIT_DEF
    %1:_(<vscale x 4 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 4 x s64>), %0
    $v8 = COPY %1(<vscale x 4 x s1>)
    PseudoRET implicit $v8

...
---
name:            icmp_nxv8i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: icmp_nxv8i64
    ; CHECK: [[DEF:%[0-9]+]]:vrb(<vscale x 8 x s64>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:vrb(<vscale x 8 x s1>) = G_ICMP intpred(sgt), [[DEF]](<vscale x 8 x s64>), [[DEF]]
    ; CHECK-NEXT: $v8 = COPY [[ICMP]](<vscale x 8 x s1>)
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:_(<vscale x 8 x s64>) = G_IMPLICIT_DEF
    %1:_(<vscale x 8 x s1>) = G_ICMP intpred(sgt), %0(<vscale x 8 x s64>), %0
    $v8 = COPY %1(<vscale x 8 x s1>)
    PseudoRET implicit $v8

...
