; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=expand-reductions -S | FileCheck %s

declare float @llvm.vector.reduce.fdot.v4f32(float, <4 x float>, <4 x float>)

; Default (no fast-math flags): sequential fmul + fadd chain.
define float @fdot_ordered(float %acc, <4 x float> %a, <4 x float> %b) {
; CHECK-LABEL: @fdot_ordered(
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <4 x float> [[A:%.*]], i64 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x float> [[B:%.*]], i64 0
; CHECK-NEXT:    [[TMP3:%.*]] = fmul float [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = fadd float [[ACC:%.*]], [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <4 x float> [[A]], i64 1
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x float> [[B]], i64 1
; CHECK-NEXT:    [[TMP7:%.*]] = fmul float [[TMP5]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = fadd float [[TMP4]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x float> [[A]], i64 2
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x float> [[B]], i64 2
; CHECK-NEXT:    [[TMP11:%.*]] = fmul float [[TMP9]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = fadd float [[TMP8]], [[TMP11]]
; CHECK-NEXT:    [[TMP13:%.*]] = extractelement <4 x float> [[A]], i64 3
; CHECK-NEXT:    [[TMP14:%.*]] = extractelement <4 x float> [[B]], i64 3
; CHECK-NEXT:    [[TMP15:%.*]] = fmul float [[TMP13]], [[TMP14]]
; CHECK-NEXT:    [[TMP16:%.*]] = fadd float [[TMP12]], [[TMP15]]
; CHECK-NEXT:    ret float [[TMP16]]
;
  %res = call float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

; With reassoc flag: vector fmul then shuffle-tree fadd, then add accumulator.
define float @fdot_reassoc(float %acc, <4 x float> %a, <4 x float> %b) {
; CHECK-LABEL: @fdot_reassoc(
; CHECK-NEXT:    [[TMP1:%.*]] = fmul reassoc <4 x float> [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    [[RDX_SHUF:%.*]] = shufflevector <4 x float> [[TMP1]], <4 x float> poison, <4 x i32> <i32 2, i32 3, i32 poison, i32 poison>
; CHECK-NEXT:    [[BIN_RDX:%.*]] = fadd reassoc <4 x float> [[TMP1]], [[RDX_SHUF]]
; CHECK-NEXT:    [[RDX_SHUF1:%.*]] = shufflevector <4 x float> [[BIN_RDX]], <4 x float> poison, <4 x i32> <i32 1, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[BIN_RDX2:%.*]] = fadd reassoc <4 x float> [[BIN_RDX]], [[RDX_SHUF1]]
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x float> [[BIN_RDX2]], i32 0
; CHECK-NEXT:    [[BIN_RDX3:%.*]] = fadd reassoc float [[ACC:%.*]], [[TMP2]]
; CHECK-NEXT:    ret float [[BIN_RDX3]]
;
  %res = call reassoc float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

; With reassoc+contract: reassoc takes priority, so vector fmul then shuffle-tree
; fadd; both flags preserved on the generated operations.
define float @fdot_reassoc_contract(float %acc, <4 x float> %a, <4 x float> %b) {
; CHECK-LABEL: @fdot_reassoc_contract(
; CHECK-NEXT:    [[TMP1:%.*]] = fmul reassoc contract <4 x float> [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    [[RDX_SHUF:%.*]] = shufflevector <4 x float> [[TMP1]], <4 x float> poison, <4 x i32> <i32 2, i32 3, i32 poison, i32 poison>
; CHECK-NEXT:    [[BIN_RDX:%.*]] = fadd reassoc contract <4 x float> [[TMP1]], [[RDX_SHUF]]
; CHECK-NEXT:    [[RDX_SHUF1:%.*]] = shufflevector <4 x float> [[BIN_RDX]], <4 x float> poison, <4 x i32> <i32 1, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[BIN_RDX2:%.*]] = fadd reassoc contract <4 x float> [[BIN_RDX]], [[RDX_SHUF1]]
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x float> [[BIN_RDX2]], i32 0
; CHECK-NEXT:    [[BIN_RDX3:%.*]] = fadd reassoc contract float [[ACC:%.*]], [[TMP2]]
; CHECK-NEXT:    ret float [[BIN_RDX3]]
;
  %res = call reassoc contract float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

; With contract flag: sequential fmul+fadd chain with contract flags preserved;
; the backend may fuse each pair into an FMA.
define float @fdot_contract(float %acc, <4 x float> %a, <4 x float> %b) {
; CHECK-LABEL: @fdot_contract(
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <4 x float> [[A:%.*]], i64 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x float> [[B:%.*]], i64 0
; CHECK-NEXT:    [[TMP3:%.*]] = fmul contract float [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = fadd contract float [[ACC:%.*]], [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <4 x float> [[A]], i64 1
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x float> [[B]], i64 1
; CHECK-NEXT:    [[TMP7:%.*]] = fmul contract float [[TMP5]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = fadd contract float [[TMP4]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x float> [[A]], i64 2
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x float> [[B]], i64 2
; CHECK-NEXT:    [[TMP11:%.*]] = fmul contract float [[TMP9]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = fadd contract float [[TMP8]], [[TMP11]]
; CHECK-NEXT:    [[TMP13:%.*]] = extractelement <4 x float> [[A]], i64 3
; CHECK-NEXT:    [[TMP14:%.*]] = extractelement <4 x float> [[B]], i64 3
; CHECK-NEXT:    [[TMP15:%.*]] = fmul contract float [[TMP13]], [[TMP14]]
; CHECK-NEXT:    [[TMP16:%.*]] = fadd contract float [[TMP12]], [[TMP15]]
; CHECK-NEXT:    ret float [[TMP16]]
;
  %res = call contract float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

