; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=i386-unknown-linux-gnu              < %s | FileCheck %s --check-prefixes=CHECK,X86
; RUN: llc -mtriple=x86_64-unknown-linux-gnu            < %s | FileCheck %s --check-prefixes=CHECK,X64
; RUN: llc -mtriple=aarch64-unknown-linux-gnu           < %s | FileCheck %s --check-prefixes=CHECK,AARCH64
; RUN: llc -mtriple=riscv32-unknown-linux-gnu -mattr=+m < %s | FileCheck %s --check-prefixes=CHECK,RV32
; RUN: llc -mtriple=riscv64-unknown-linux-gnu -mattr=+m < %s | FileCheck %s --check-prefixes=CHECK,RV64

; When a narrow udiv-by-constant (i8, i16) is lowered via BuildUDIV, the
; Granlund-Montgomery (GM) algorithm may need an expensive add-and-shift fixup
; for IsAdd=true divisors. A wider legal type (e.g. i32 for i16) has enough
; headroom for a simple magic = ceil(2^Shift / C) that needs no fixup at all.
;
; i16 IsAdd=true divisors (e.g. 7): on targets with i32 UMUL_LOHI (i386,
; x86-64) we emit a shiftless 32x32->64 multiply and take the high 32 bits.
; On AArch64 (no i32 UMUL_LOHI) we fall back to FullMultiply via i64.

; --- i8 cases ---

define i8 @udiv_i8_by7(i8 %x) nounwind {
; X86-LABEL: udiv_i8_by7:
; X86:       # %bb.0:
; X86-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    leal (%eax,%eax,8), %ecx
; X86-NEXT:    leal (%eax,%ecx,4), %ecx
; X86-NEXT:    subb %ch, %al
; X86-NEXT:    shrb %al
; X86-NEXT:    addb %ch, %al
; X86-NEXT:    shrb $2, %al
; X86-NEXT:    # kill: def $al killed $al killed $eax
; X86-NEXT:    retl
;
; X64-LABEL: udiv_i8_by7:
; X64:       # %bb.0:
; X64-NEXT:    movzbl %dil, %eax
; X64-NEXT:    imull $293, %eax, %eax # imm = 0x125
; X64-NEXT:    shrl $11, %eax
; X64-NEXT:    # kill: def $al killed $al killed $eax
; X64-NEXT:    retq
;
; AARCH64-LABEL: udiv_i8_by7:
; AARCH64:       // %bb.0:
; AARCH64-NEXT:    // kill: def $w0 killed $w0 def $x0
; AARCH64-NEXT:    mov w8, #293 // =0x125
; AARCH64-NEXT:    and x9, x0, #0xff
; AARCH64-NEXT:    umull x8, w9, w8
; AARCH64-NEXT:    lsr x0, x8, #11
; AARCH64-NEXT:    // kill: def $w0 killed $w0 killed $x0
; AARCH64-NEXT:    ret
;
; RV32-LABEL: udiv_i8_by7:
; RV32:       # %bb.0:
; RV32-NEXT:    zext.b a1, a0
; RV32-NEXT:    li a2, 37
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    srli a1, a1, 8
; RV32-NEXT:    sub a0, a0, a1
; RV32-NEXT:    slli a0, a0, 24
; RV32-NEXT:    srli a0, a0, 25
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    srli a0, a0, 2
; RV32-NEXT:    ret
;
; RV64-LABEL: udiv_i8_by7:
; RV64:       # %bb.0:
; RV64-NEXT:    zext.b a0, a0
; RV64-NEXT:    li a1, 293
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    srli a0, a0, 11
; RV64-NEXT:    ret
  %d = udiv i8 %x, 7
  ret i8 %d
}

define i8 @udiv_i8_by5(i8 %x) nounwind {
; X86-LABEL: udiv_i8_by5:
; X86:       # %bb.0:
; X86-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    imull $205, %eax, %eax
; X86-NEXT:    shrl $10, %eax
; X86-NEXT:    # kill: def $al killed $al killed $eax
; X86-NEXT:    retl
;
; X64-LABEL: udiv_i8_by5:
; X64:       # %bb.0:
; X64-NEXT:    movzbl %dil, %eax
; X64-NEXT:    imull $205, %eax, %eax
; X64-NEXT:    shrl $10, %eax
; X64-NEXT:    # kill: def $al killed $al killed $eax
; X64-NEXT:    retq
;
; AARCH64-LABEL: udiv_i8_by5:
; AARCH64:       // %bb.0:
; AARCH64-NEXT:    mov w8, #205 // =0xcd
; AARCH64-NEXT:    and w9, w0, #0xff
; AARCH64-NEXT:    mul w8, w9, w8
; AARCH64-NEXT:    lsr w0, w8, #10
; AARCH64-NEXT:    ret
;
; RV32-LABEL: udiv_i8_by5:
; RV32:       # %bb.0:
; RV32-NEXT:    zext.b a0, a0
; RV32-NEXT:    li a1, 205
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    srli a0, a0, 10
; RV32-NEXT:    ret
;
; RV64-LABEL: udiv_i8_by5:
; RV64:       # %bb.0:
; RV64-NEXT:    zext.b a0, a0
; RV64-NEXT:    li a1, 205
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    srli a0, a0, 10
; RV64-NEXT:    ret
  %d = udiv i8 %x, 5
  ret i8 %d
}

define i8 @udiv_i8_by3(i8 %x) nounwind {
; X86-LABEL: udiv_i8_by3:
; X86:       # %bb.0:
; X86-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    imull $171, %eax, %eax
; X86-NEXT:    shrl $9, %eax
; X86-NEXT:    # kill: def $al killed $al killed $eax
; X86-NEXT:    retl
;
; X64-LABEL: udiv_i8_by3:
; X64:       # %bb.0:
; X64-NEXT:    movzbl %dil, %eax
; X64-NEXT:    imull $171, %eax, %eax
; X64-NEXT:    shrl $9, %eax
; X64-NEXT:    # kill: def $al killed $al killed $eax
; X64-NEXT:    retq
;
; AARCH64-LABEL: udiv_i8_by3:
; AARCH64:       // %bb.0:
; AARCH64-NEXT:    mov w8, #171 // =0xab
; AARCH64-NEXT:    and w9, w0, #0xff
; AARCH64-NEXT:    mul w8, w9, w8
; AARCH64-NEXT:    lsr w0, w8, #9
; AARCH64-NEXT:    ret
;
; RV32-LABEL: udiv_i8_by3:
; RV32:       # %bb.0:
; RV32-NEXT:    zext.b a0, a0
; RV32-NEXT:    li a1, 171
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    srli a0, a0, 9
; RV32-NEXT:    ret
;
; RV64-LABEL: udiv_i8_by3:
; RV64:       # %bb.0:
; RV64-NEXT:    zext.b a0, a0
; RV64-NEXT:    li a1, 171
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    srli a0, a0, 9
; RV64-NEXT:    ret
  %d = udiv i8 %x, 3
  ret i8 %d
}

; Even divisor - stock uses pre-shift + magic; simple magic avoids pre-shift.
define i8 @udiv_i8_by78(i8 %x) nounwind {
; X86-LABEL: udiv_i8_by78:
; X86:       # %bb.0:
; X86-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    shrb %al
; X86-NEXT:    movzbl %al, %eax
; X86-NEXT:    imull $211, %eax, %eax
; X86-NEXT:    shrl $13, %eax
; X86-NEXT:    # kill: def $al killed $al killed $eax
; X86-NEXT:    retl
;
; X64-LABEL: udiv_i8_by78:
; X64:       # %bb.0:
; X64-NEXT:    shrb %dil
; X64-NEXT:    movzbl %dil, %eax
; X64-NEXT:    imull $211, %eax, %eax
; X64-NEXT:    shrl $13, %eax
; X64-NEXT:    # kill: def $al killed $al killed $eax
; X64-NEXT:    retq
;
; AARCH64-LABEL: udiv_i8_by78:
; AARCH64:       // %bb.0:
; AARCH64-NEXT:    ubfx w8, w0, #1, #7
; AARCH64-NEXT:    mov w9, #211 // =0xd3
; AARCH64-NEXT:    mul w8, w8, w9
; AARCH64-NEXT:    lsr w0, w8, #13
; AARCH64-NEXT:    ret
;
; RV32-LABEL: udiv_i8_by78:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a0, a0, 24
; RV32-NEXT:    srli a0, a0, 25
; RV32-NEXT:    li a1, 211
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    srli a0, a0, 13
; RV32-NEXT:    ret
;
; RV64-LABEL: udiv_i8_by78:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a0, a0, 56
; RV64-NEXT:    srli a0, a0, 57
; RV64-NEXT:    li a1, 211
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    srli a0, a0, 13
; RV64-NEXT:    ret
  %d = udiv i8 %x, 78
  ret i8 %d
}

define i8 @udiv_i8_by116(i8 %x) nounwind {
; X86-LABEL: udiv_i8_by116:
; X86:       # %bb.0:
; X86-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    shrb $2, %al
; X86-NEXT:    movzbl %al, %eax
; X86-NEXT:    imull $71, %eax, %eax
; X86-NEXT:    shrl $11, %eax
; X86-NEXT:    # kill: def $al killed $al killed $eax
; X86-NEXT:    retl
;
; X64-LABEL: udiv_i8_by116:
; X64:       # %bb.0:
; X64-NEXT:    shrb $2, %dil
; X64-NEXT:    movzbl %dil, %eax
; X64-NEXT:    imull $71, %eax, %eax
; X64-NEXT:    shrl $11, %eax
; X64-NEXT:    # kill: def $al killed $al killed $eax
; X64-NEXT:    retq
;
; AARCH64-LABEL: udiv_i8_by116:
; AARCH64:       // %bb.0:
; AARCH64-NEXT:    ubfx w8, w0, #2, #6
; AARCH64-NEXT:    mov w9, #71 // =0x47
; AARCH64-NEXT:    mul w8, w8, w9
; AARCH64-NEXT:    lsr w0, w8, #11
; AARCH64-NEXT:    ret
;
; RV32-LABEL: udiv_i8_by116:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a0, a0, 24
; RV32-NEXT:    srli a0, a0, 26
; RV32-NEXT:    li a1, 71
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    srli a0, a0, 11
; RV32-NEXT:    ret
;
; RV64-LABEL: udiv_i8_by116:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a0, a0, 56
; RV64-NEXT:    srli a0, a0, 58
; RV64-NEXT:    li a1, 71
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    srli a0, a0, 11
; RV64-NEXT:    ret
  %d = udiv i8 %x, 116
  ret i8 %d
}

; Power of 2 - should NOT fire (already lowered to shift).
define i8 @udiv_i8_by4(i8 %x) nounwind {
; X86-LABEL: udiv_i8_by4:
; X86:       # %bb.0:
; X86-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    shrb $2, %al
; X86-NEXT:    retl
;
; X64-LABEL: udiv_i8_by4:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    shrb $2, %al
; X64-NEXT:    # kill: def $al killed $al killed $eax
; X64-NEXT:    retq
;
; AARCH64-LABEL: udiv_i8_by4:
; AARCH64:       // %bb.0:
; AARCH64-NEXT:    ubfx w0, w0, #2, #6
; AARCH64-NEXT:    ret
;
; RV32-LABEL: udiv_i8_by4:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a0, a0, 24
; RV32-NEXT:    srli a0, a0, 26
; RV32-NEXT:    ret
;
; RV64-LABEL: udiv_i8_by4:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a0, a0, 56
; RV64-NEXT:    srli a0, a0, 58
; RV64-NEXT:    ret
  %d = udiv i8 %x, 4
  ret i8 %d
}

; Division by 1 - should NOT fire.
define i8 @udiv_i8_by1(i8 %x) nounwind {
; X86-LABEL: udiv_i8_by1:
; X86:       # %bb.0:
; X86-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    retl
;
; X64-LABEL: udiv_i8_by1:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    # kill: def $al killed $al killed $eax
; X64-NEXT:    retq
;
; AARCH64-LABEL: udiv_i8_by1:
; AARCH64:       // %bb.0:
; AARCH64-NEXT:    ret
;
; RV32-LABEL: udiv_i8_by1:
; RV32:       # %bb.0:
; RV32-NEXT:    ret
;
; RV64-LABEL: udiv_i8_by1:
; RV64:       # %bb.0:
; RV64-NEXT:    ret
  %d = udiv i8 %x, 1
  ret i8 %d
}

; Bare i8 udiv feeding another i8 op (no zext).
define i8 @udiv_i8_then_add(i8 %x, i8 %y) nounwind {
; X86-LABEL: udiv_i8_then_add:
; X86:       # %bb.0:
; X86-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    leal (%eax,%eax,8), %ecx
; X86-NEXT:    leal (%eax,%ecx,4), %ecx
; X86-NEXT:    subb %ch, %al
; X86-NEXT:    shrb %al
; X86-NEXT:    addb %ch, %al
; X86-NEXT:    shrb $2, %al
; X86-NEXT:    addb {{[0-9]+}}(%esp), %al
; X86-NEXT:    # kill: def $al killed $al killed $eax
; X86-NEXT:    retl
;
; X64-LABEL: udiv_i8_then_add:
; X64:       # %bb.0:
; X64-NEXT:    movzbl %dil, %eax
; X64-NEXT:    imull $293, %eax, %eax # imm = 0x125
; X64-NEXT:    shrl $11, %eax
; X64-NEXT:    addb %sil, %al
; X64-NEXT:    # kill: def $al killed $al killed $eax
; X64-NEXT:    retq
;
; AARCH64-LABEL: udiv_i8_then_add:
; AARCH64:       // %bb.0:
; AARCH64-NEXT:    mov w8, #293 // =0x125
; AARCH64-NEXT:    and w9, w0, #0xff
; AARCH64-NEXT:    mul w8, w9, w8
; AARCH64-NEXT:    add w0, w1, w8, lsr #11
; AARCH64-NEXT:    ret
;
; RV32-LABEL: udiv_i8_then_add:
; RV32:       # %bb.0:
; RV32-NEXT:    zext.b a2, a0
; RV32-NEXT:    li a3, 37
; RV32-NEXT:    mul a2, a2, a3
; RV32-NEXT:    srli a2, a2, 8
; RV32-NEXT:    sub a0, a0, a2
; RV32-NEXT:    slli a0, a0, 24
; RV32-NEXT:    srli a0, a0, 25
; RV32-NEXT:    add a0, a0, a2
; RV32-NEXT:    srli a0, a0, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    ret
;
; RV64-LABEL: udiv_i8_then_add:
; RV64:       # %bb.0:
; RV64-NEXT:    zext.b a0, a0
; RV64-NEXT:    li a2, 293
; RV64-NEXT:    mul a0, a0, a2
; RV64-NEXT:    srli a0, a0, 11
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    ret
  %d = udiv i8 %x, 7
  %r = add i8 %d, %y
  ret i8 %r
}

; --- i16 cases ---

; IsAdd=true: i386 uses shiftless mull (UMUL_LOHI), x86-64 uses imulq+shrq $32,
; AArch64 falls back to umull+lsr (FullMultiply via i64).
define i16 @udiv_i16_by7(i16 %x) nounwind {
; X86-LABEL: udiv_i16_by7:
; X86:       # %bb.0:
; X86-NEXT:    movzwl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl $613572608, %ecx # imm = 0x24926000
; X86-NEXT:    mull %ecx
; X86-NEXT:    movl %edx, %eax
; X86-NEXT:    # kill: def $ax killed $ax killed $eax
; X86-NEXT:    retl
;
; X64-LABEL: udiv_i16_by7:
; X64:       # %bb.0:
; X64-NEXT:    movzwl %di, %eax
; X64-NEXT:    imulq $613572608, %rax, %rax # imm = 0x24926000
; X64-NEXT:    shrq $32, %rax
; X64-NEXT:    # kill: def $ax killed $ax killed $rax
; X64-NEXT:    retq
;
; AARCH64-LABEL: udiv_i16_by7:
; AARCH64:       // %bb.0:
; AARCH64-NEXT:    mov w8, #9363 // =0x2493
; AARCH64-NEXT:    // kill: def $w0 killed $w0 def $x0
; AARCH64-NEXT:    and x9, x0, #0xffff
; AARCH64-NEXT:    movk w8, #1, lsl #16
; AARCH64-NEXT:    umull x8, w9, w8
; AARCH64-NEXT:    lsr x0, x8, #19
; AARCH64-NEXT:    // kill: def $w0 killed $w0 killed $x0
; AARCH64-NEXT:    ret
;
; RV32-LABEL: udiv_i16_by7:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a0, a0, 16
; RV32-NEXT:    srli a0, a0, 16
; RV32-NEXT:    lui a1, 149798
; RV32-NEXT:    mulhu a0, a0, a1
; RV32-NEXT:    ret
;
; RV64-LABEL: udiv_i16_by7:
; RV64:       # %bb.0:
; RV64-NEXT:    lui a1, 74899
; RV64-NEXT:    slli a1, a1, 4
; RV64-NEXT:    slli a0, a0, 48
; RV64-NEXT:    mulhu a0, a0, a1
; RV64-NEXT:    srli a0, a0, 19
; RV64-NEXT:    ret
  %d = udiv i16 %x, 7
  ret i16 %d
}

define i16 @udiv_i16_by100(i16 %x) nounwind {
; X86-LABEL: udiv_i16_by100:
; X86:       # %bb.0:
; X86-NEXT:    movzwl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    shrl $2, %eax
; X86-NEXT:    imull $5243, %eax, %eax # imm = 0x147B
; X86-NEXT:    shrl $17, %eax
; X86-NEXT:    # kill: def $ax killed $ax killed $eax
; X86-NEXT:    retl
;
; X64-LABEL: udiv_i16_by100:
; X64:       # %bb.0:
; X64-NEXT:    movzwl %di, %eax
; X64-NEXT:    shrl $2, %eax
; X64-NEXT:    imull $5243, %eax, %eax # imm = 0x147B
; X64-NEXT:    shrl $17, %eax
; X64-NEXT:    # kill: def $ax killed $ax killed $eax
; X64-NEXT:    retq
;
; AARCH64-LABEL: udiv_i16_by100:
; AARCH64:       // %bb.0:
; AARCH64-NEXT:    ubfx w8, w0, #2, #14
; AARCH64-NEXT:    mov w9, #5243 // =0x147b
; AARCH64-NEXT:    mul w8, w8, w9
; AARCH64-NEXT:    lsr w0, w8, #17
; AARCH64-NEXT:    ret
;
; RV32-LABEL: udiv_i16_by100:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a0, a0, 16
; RV32-NEXT:    lui a1, 1
; RV32-NEXT:    srli a0, a0, 18
; RV32-NEXT:    addi a1, a1, 1147
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    srli a0, a0, 17
; RV32-NEXT:    ret
;
; RV64-LABEL: udiv_i16_by100:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a0, a0, 48
; RV64-NEXT:    lui a1, 1
; RV64-NEXT:    srli a0, a0, 50
; RV64-NEXT:    addi a1, a1, 1147
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    srli a0, a0, 17
; RV64-NEXT:    ret
  %d = udiv i16 %x, 100
  ret i16 %d
}

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
