; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='loop-simplify,lcssa,loop-split-test,verify' \
; RUN:   -loop-split-points=50 -S < %s | FileCheck %s

; A signed counting-down loop (step -1) split into two partitions. The guard and
; latch predicates flip to >=, and the end clamp uses smax instead of smin.

define void @descending(ptr %a, i64 %n) {
; CHECK-LABEL: define void @descending(
; CHECK-SAME: ptr [[A:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[LS_GUARD0:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -49
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[N]], -1
; CHECK-NEXT:    [[SMIN:%.*]] = call i64 @llvm.smin.i64(i64 [[TMP1]], i64 -1)
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw i64 [[SMIN]], 1
; CHECK-NEXT:    [[SMAX:%.*]] = call i64 @llvm.smax.i64(i64 [[TMP0]], i64 [[TMP2]])
; CHECK-NEXT:    [[TMP3:%.*]] = add i64 [[N]], -50
; CHECK-NEXT:    [[ITR_CHK:%.*]] = icmp sge i64 [[N]], [[SMAX]]
; CHECK-NEXT:    br i1 [[ITR_CHK]], label %[[ENTRY:.*]], label %[[LS_GUARD1:.*]]
; CHECK:       [[ENTRY]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[N]], %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr i64, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    store i64 [[I]], ptr [[P]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], -1
; CHECK-NEXT:    [[ITR_CHK1:%.*]] = icmp sge i64 [[I_NEXT]], [[SMAX]]
; CHECK-NEXT:    br i1 [[ITR_CHK1]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    br label %[[LS_GUARD1]]
; CHECK:       [[LS_GUARD1]]:
; CHECK-NEXT:    [[ITR_CHK2:%.*]] = icmp sge i64 [[TMP3]], [[TMP2]]
; CHECK-NEXT:    br i1 [[ITR_CHK2]], label %[[ENTRY_LS1:.*]], label %[[LS_FINAL_EXIT:.*]]
; CHECK:       [[ENTRY_LS1]]:
; CHECK-NEXT:    br label %[[LOOP_LS1:.*]]
; CHECK:       [[LOOP_LS1]]:
; CHECK-NEXT:    [[I_LS1:%.*]] = phi i64 [ [[TMP3]], %[[ENTRY_LS1]] ], [ [[I_NEXT_LS1:%.*]], %[[LOOP_LS1]] ]
; CHECK-NEXT:    [[P_LS1:%.*]] = getelementptr i64, ptr [[A]], i64 [[I_LS1]]
; CHECK-NEXT:    store i64 [[I_LS1]], ptr [[P_LS1]], align 4
; CHECK-NEXT:    [[I_NEXT_LS1]] = add i64 [[I_LS1]], -1
; CHECK-NEXT:    [[ITR_CHK3:%.*]] = icmp sge i64 [[I_NEXT_LS1]], [[TMP2]]
; CHECK-NEXT:    br i1 [[ITR_CHK3]], label %[[LOOP_LS1]], label %[[LS_EXIT1:.*]]
; CHECK:       [[LS_EXIT1]]:
; CHECK-NEXT:    br label %[[LS_FINAL_EXIT]]
; CHECK:       [[LS_FINAL_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ %n, %entry ], [ %i.next, %loop ]
  %p = getelementptr i64, ptr %a, i64 %i
  store i64 %i, ptr %p
  %i.next = add i64 %i, -1
  %c = icmp sge i64 %i.next, 0
  br i1 %c, label %loop, label %exit

exit:
  ret void
}
