; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='loop-simplify,lcssa,loop-split-test,verify' \
; RUN:   -loop-split-points=0 -S < %s | FileCheck %s

; A leading split point of 0 makes partition 0 empty ([Start, Start-1]). The
; loop is bottom-tested, so without an entry guard partition 0 would still run
; one iteration and the loop would execute its first iteration twice. The empty
; partition is detected at compile time (its width S - E folds to a constant)
; and skipped: partition 0's guard unconditionally falls through to partition 1,
; which runs the whole iteration space and seeds from the chain-entry value (0).

define i64 @reduction(ptr %a, i64 %n) {
; CHECK-LABEL: define i64 @reduction(
; CHECK-SAME: ptr [[A:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[LS_GUARD0:.*]]:
; CHECK-NEXT:    [[SMAX:%.*]] = call i64 @llvm.smax.i64(i64 [[N]], i64 1)
; CHECK-NEXT:    [[TMP0:%.*]] = add nsw i64 [[SMAX]], -1
; CHECK-NEXT:    br label %[[LS_GUARD1:.*]]
; CHECK:       [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[SUM:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[SUM_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr i64, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    [[V:%.*]] = load i64, ptr [[P]], align 4
; CHECK-NEXT:    [[SUM_NEXT]] = add i64 [[SUM]], [[V]]
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 1
; CHECK-NEXT:    [[ITR_CHK:%.*]] = icmp sle i64 [[I_NEXT]], -1
; CHECK-NEXT:    br i1 [[ITR_CHK]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    br label %[[LS_GUARD1]]
; CHECK:       [[LS_GUARD1]]:
; CHECK-NEXT:    [[SUM_NEXT4:%.*]] = phi i64 [ [[SUM_NEXT]], %[[EXIT]] ], [ 0, %[[LS_GUARD0]] ]
; CHECK-NEXT:    [[ITR_CHK1:%.*]] = icmp sle i64 0, [[TMP0]]
; CHECK-NEXT:    br i1 [[ITR_CHK1]], label %[[ENTRY_LS1:.*]], label %[[LS_FINAL_EXIT:.*]]
; CHECK:       [[ENTRY_LS1]]:
; CHECK-NEXT:    br label %[[LOOP_LS1:.*]]
; CHECK:       [[LOOP_LS1]]:
; CHECK-NEXT:    [[I_LS1:%.*]] = phi i64 [ 0, %[[ENTRY_LS1]] ], [ [[I_NEXT_LS1:%.*]], %[[LOOP_LS1]] ]
; CHECK-NEXT:    [[SUM_LS1:%.*]] = phi i64 [ [[SUM_NEXT4]], %[[ENTRY_LS1]] ], [ [[SUM_NEXT_LS1:%.*]], %[[LOOP_LS1]] ]
; CHECK-NEXT:    [[P_LS1:%.*]] = getelementptr i64, ptr [[A]], i64 [[I_LS1]]
; CHECK-NEXT:    [[V_LS1:%.*]] = load i64, ptr [[P_LS1]], align 4
; CHECK-NEXT:    [[SUM_NEXT_LS1]] = add i64 [[SUM_LS1]], [[V_LS1]]
; CHECK-NEXT:    [[I_NEXT_LS1]] = add i64 [[I_LS1]], 1
; CHECK-NEXT:    [[ITR_CHK2:%.*]] = icmp sle i64 [[I_NEXT_LS1]], [[TMP0]]
; CHECK-NEXT:    br i1 [[ITR_CHK2]], label %[[LOOP_LS1]], label %[[LS_EXIT1:.*]]
; CHECK:       [[LS_EXIT1]]:
; CHECK-NEXT:    br label %[[LS_FINAL_EXIT]]
; CHECK:       [[LS_FINAL_EXIT]]:
; CHECK-NEXT:    [[SUM_NEXT3:%.*]] = phi i64 [ [[SUM_NEXT_LS1]], %[[LS_EXIT1]] ], [ [[SUM_NEXT4]], %[[LS_GUARD1]] ]
; CHECK-NEXT:    ret i64 [[SUM_NEXT3]]
;
; The empty leading partition is never entered: an unconditional fall-through.
; The original loop body is now dead (unreachable), proving it is not executed.
; The surviving partition runs the full range, seeded from the chain-entry value.
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %sum = phi i64 [ 0, %entry ], [ %sum.next, %loop ]
  %p = getelementptr i64, ptr %a, i64 %i
  %v = load i64, ptr %p
  %sum.next = add i64 %sum, %v
  %i.next = add i64 %i, 1
  %c = icmp slt i64 %i.next, %n
  br i1 %c, label %loop, label %exit

exit:
  %sum.lcssa = phi i64 [ %sum.next, %loop ]
  ret i64 %sum.lcssa
}
