; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='loop-simplify,lcssa,loop-split-test,verify' \
; RUN:   -loop-split-points=50,100 -S < %s | FileCheck %s

; A loop split into three partitions: [0,49], [50,99], [100,n-1].

define void @three_way(ptr %a, i64 %n) {
; CHECK-LABEL: define void @three_way(
; CHECK-SAME: ptr [[A:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[LS_GUARD0:.*:]]
; CHECK-NEXT:    [[SMAX:%.*]] = call i64 @llvm.smax.i64(i64 [[N]], i64 1)
; CHECK-NEXT:    [[TMP0:%.*]] = add nsw i64 [[SMAX]], -1
; CHECK-NEXT:    [[SMIN:%.*]] = call i64 @llvm.smin.i64(i64 [[TMP0]], i64 49)
; CHECK-NEXT:    [[SMIN1:%.*]] = call i64 @llvm.smin.i64(i64 [[TMP0]], i64 99)
; CHECK-NEXT:    [[ITR_CHK:%.*]] = icmp sle i64 0, [[SMIN]]
; CHECK-NEXT:    br i1 [[ITR_CHK]], label %[[ENTRY:.*]], label %[[LS_GUARD1:.*]]
; CHECK:       [[ENTRY]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr i64, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    store i64 [[I]], ptr [[P]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 1
; CHECK-NEXT:    [[ITR_CHK2:%.*]] = icmp sle i64 [[I_NEXT]], [[SMIN]]
; CHECK-NEXT:    br i1 [[ITR_CHK2]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    br label %[[LS_GUARD1]]
; CHECK:       [[LS_GUARD1]]:
; CHECK-NEXT:    [[ITR_CHK3:%.*]] = icmp sle i64 50, [[SMIN1]]
; CHECK-NEXT:    br i1 [[ITR_CHK3]], label %[[ENTRY_LS1:.*]], label %[[LS_GUARD2:.*]]
; CHECK:       [[ENTRY_LS1]]:
; CHECK-NEXT:    br label %[[LOOP_LS1:.*]]
; CHECK:       [[LOOP_LS1]]:
; CHECK-NEXT:    [[I_LS1:%.*]] = phi i64 [ 50, %[[ENTRY_LS1]] ], [ [[I_NEXT_LS1:%.*]], %[[LOOP_LS1]] ]
; CHECK-NEXT:    [[P_LS1:%.*]] = getelementptr i64, ptr [[A]], i64 [[I_LS1]]
; CHECK-NEXT:    store i64 [[I_LS1]], ptr [[P_LS1]], align 4
; CHECK-NEXT:    [[I_NEXT_LS1]] = add i64 [[I_LS1]], 1
; CHECK-NEXT:    [[ITR_CHK4:%.*]] = icmp sle i64 [[I_NEXT_LS1]], [[SMIN1]]
; CHECK-NEXT:    br i1 [[ITR_CHK4]], label %[[LOOP_LS1]], label %[[LS_EXIT1:.*]]
; CHECK:       [[LS_EXIT1]]:
; CHECK-NEXT:    br label %[[LS_GUARD2]]
; CHECK:       [[LS_GUARD2]]:
; CHECK-NEXT:    [[ITR_CHK5:%.*]] = icmp sle i64 100, [[TMP0]]
; CHECK-NEXT:    br i1 [[ITR_CHK5]], label %[[ENTRY_LS2:.*]], label %[[LS_FINAL_EXIT:.*]]
; CHECK:       [[ENTRY_LS2]]:
; CHECK-NEXT:    br label %[[LOOP_LS2:.*]]
; CHECK:       [[LOOP_LS2]]:
; CHECK-NEXT:    [[I_LS2:%.*]] = phi i64 [ 100, %[[ENTRY_LS2]] ], [ [[I_NEXT_LS2:%.*]], %[[LOOP_LS2]] ]
; CHECK-NEXT:    [[P_LS2:%.*]] = getelementptr i64, ptr [[A]], i64 [[I_LS2]]
; CHECK-NEXT:    store i64 [[I_LS2]], ptr [[P_LS2]], align 4
; CHECK-NEXT:    [[I_NEXT_LS2]] = add i64 [[I_LS2]], 1
; CHECK-NEXT:    [[ITR_CHK6:%.*]] = icmp sle i64 [[I_NEXT_LS2]], [[TMP0]]
; CHECK-NEXT:    br i1 [[ITR_CHK6]], label %[[LOOP_LS2]], label %[[LS_EXIT2:.*]]
; CHECK:       [[LS_EXIT2]]:
; CHECK-NEXT:    br label %[[LS_FINAL_EXIT]]
; CHECK:       [[LS_FINAL_EXIT]]:
; CHECK-NEXT:    ret void
;
; Each partition is entered only if a runtime min/iteration check passes; the
; min(partitionEnd, loopEnd) clamp is a signed-min intrinsic.
; The original loop plus two clones cover [0,49], [50,99] and [100,n-1], and a
; dedicated final-exit block joins all three partitions.
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %p = getelementptr i64, ptr %a, i64 %i
  store i64 %i, ptr %p
  %i.next = add i64 %i, 1
  %c = icmp slt i64 %i.next, %n
  br i1 %c, label %loop, label %exit

exit:
  ret void
}
