# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -mattr=-sign-ext -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s -check-prefixes=CHECK,NO-SIGNEXT
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -mattr=+sign-ext -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s -check-prefixes=CHECK,SIGNEXT

---
name:            add_i8_zext
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: add_i8_zext
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:i32(s32) = G_AND [[ADD]], [[C]]
    ; CHECK-NEXT: RETURN [[AND]](s32), implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s8) = G_TRUNC %2(s32)
    %3:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s8) = G_TRUNC %3(s32)
    %4:_(s8) = G_ADD %0, %1
    %5:i32(s32) = G_ZEXT %4(s8)
    RETURN %5(s32), implicit-def $arguments
...

---
name:            add_i8_sext
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: add_i8_sext
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]]
    ; NO-SIGNEXT-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; NO-SIGNEXT-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ADD]], [[C]](s32)
    ; NO-SIGNEXT-NEXT: [[ASHR:%[0-9]+]]:i32(s32) = G_ASHR [[SHL]], [[C]](s32)
    ; NO-SIGNEXT-NEXT: RETURN [[ASHR]](s32), implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: add_i8_sext
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; SIGNEXT-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; SIGNEXT-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]]
    ; SIGNEXT-NEXT: [[SEXT_INREG:%[0-9]+]]:i32(s32) = G_SEXT_INREG [[ADD]], 8
    ; SIGNEXT-NEXT: RETURN [[SEXT_INREG]](s32), implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s8) = G_TRUNC %2(s32)
    %3:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s8) = G_TRUNC %3(s32)
    %4:_(s8) = G_ADD %0, %1
    %5:i32(s32) = G_SEXT %4(s8)
    RETURN %5(s32), implicit-def $arguments
...

---
name:            add_i8_aext
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: add_i8_aext
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]]
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:i32(s32) = COPY [[ADD]](s32)
    ; CHECK-NEXT: RETURN [[COPY]](s32), implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s8) = G_TRUNC %2(s32)
    %3:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s8) = G_TRUNC %3(s32)
    %4:_(s8) = G_ADD %0, %1
    %5:i32(s32) = G_ANYEXT %4(s8)
    RETURN %5(s32), implicit-def $arguments
...

---
name:            add_i16_zext
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: add_i16_zext
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]]
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK-NEXT: [[AND:%[0-9]+]]:i32(s32) = G_AND [[ADD]], [[C]]
    ; CHECK-NEXT: RETURN [[AND]](s32), implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s16) = G_TRUNC %2(s32)
    %3:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s16) = G_TRUNC %3(s32)
    %4:_(s16) = G_ADD %0, %1
    %5:i32(s32) = G_ZEXT %4(s16)
    RETURN %5(s32), implicit-def $arguments
...

---
name:            add_i16_sext
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: add_i16_sext
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]]
    ; NO-SIGNEXT-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; NO-SIGNEXT-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ADD]], [[C]](s32)
    ; NO-SIGNEXT-NEXT: [[ASHR:%[0-9]+]]:i32(s32) = G_ASHR [[SHL]], [[C]](s32)
    ; NO-SIGNEXT-NEXT: RETURN [[ASHR]](s32), implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: add_i16_sext
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; SIGNEXT-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; SIGNEXT-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]]
    ; SIGNEXT-NEXT: [[SEXT_INREG:%[0-9]+]]:i32(s32) = G_SEXT_INREG [[ADD]], 16
    ; SIGNEXT-NEXT: RETURN [[SEXT_INREG]](s32), implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s16) = G_TRUNC %2(s32)
    %3:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s16) = G_TRUNC %3(s32)
    %4:_(s16) = G_ADD %0, %1
    %5:i32(s32) = G_SEXT %4(s16)
    RETURN %5(s32), implicit-def $arguments
...

---
name:            add_i16_aext
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: add_i16_aext
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]]
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:i32(s32) = COPY [[ADD]](s32)
    ; CHECK-NEXT: RETURN [[COPY]](s32), implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s16) = G_TRUNC %2(s32)
    %3:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s16) = G_TRUNC %3(s32)
    %4:_(s16) = G_ADD %0, %1
    %5:i32(s32) = G_ANYEXT %4(s16)
    RETURN %5(s32), implicit-def $arguments
...

---
name:            add_i32
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: add_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = G_ADD [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]]
    ; CHECK-NEXT: RETURN [[ADD]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %2:_(s32) = G_ADD %0, %1
    RETURN %2(s32), implicit-def $arguments
...

---
name:            add_i64
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: add_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i64_1:%[0-9]+]]:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s64) = G_ADD [[ARGUMENT_i64_]], [[ARGUMENT_i64_1]]
    ; CHECK-NEXT: RETURN [[ADD]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    %2:_(s64) = G_ADD %0, %1
    RETURN %2(s64), implicit-def $arguments
...
