# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -mattr=-sign-ext -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s -check-prefixes=CHECK,NO-SIGNEXT
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -mattr=+sign-ext -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s -check-prefixes=CHECK,SIGNEXT

---
name: ashr_i8
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: ashr_i8
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; NO-SIGNEXT-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; NO-SIGNEXT-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ARGUMENT_i32_]], [[C1]](s32)
    ; NO-SIGNEXT-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SHL]], [[C1]](s32)
    ; NO-SIGNEXT-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[ASHR]], [[C]](s32)
    ; NO-SIGNEXT-NEXT: RETURN [[ASHR1]](s32), implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: ashr_i8
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; SIGNEXT-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; SIGNEXT-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[ARGUMENT_i32_]], 8
    ; SIGNEXT-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; SIGNEXT-NEXT: RETURN [[ASHR]](s32), implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s8) = G_TRUNC %2(s32)
    %1:_(s8) = G_CONSTANT i8 5
    %3:_(s8) = G_ASHR %0, %1
    %4:_(s32) = G_ANYEXT %3(s8)
    RETURN %4(s32), implicit-def $arguments

...
---
name: ashrv_i8
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: ashrv_i8
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; NO-SIGNEXT-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ARGUMENT_i32_]], [[C]](s32)
    ; NO-SIGNEXT-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SHL]], [[C]](s32)
    ; NO-SIGNEXT-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; NO-SIGNEXT-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ARGUMENT_i32_1]], [[C1]]
    ; NO-SIGNEXT-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[ASHR]], [[AND]](s32)
    ; NO-SIGNEXT-NEXT: RETURN [[ASHR1]](s32), implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: ashrv_i8
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; SIGNEXT-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; SIGNEXT-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[ARGUMENT_i32_]], 8
    ; SIGNEXT-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; SIGNEXT-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ARGUMENT_i32_1]], [[C]]
    ; SIGNEXT-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[AND]](s32)
    ; SIGNEXT-NEXT: RETURN [[ASHR]](s32), implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s8) = G_TRUNC %2(s32)
    %3:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s8) = G_TRUNC %3(s32)
    %4:_(s8) = G_ASHR %0, %1
    %5:_(s32) = G_ANYEXT %4(s8)
    RETURN %5(s32), implicit-def $arguments

...
---
name: ashr_i16
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: ashr_i16
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; NO-SIGNEXT-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; NO-SIGNEXT-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ARGUMENT_i32_]], [[C1]](s32)
    ; NO-SIGNEXT-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SHL]], [[C1]](s32)
    ; NO-SIGNEXT-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[ASHR]], [[C]](s32)
    ; NO-SIGNEXT-NEXT: RETURN [[ASHR1]](s32), implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: ashr_i16
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; SIGNEXT-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; SIGNEXT-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[ARGUMENT_i32_]], 16
    ; SIGNEXT-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[C]](s32)
    ; SIGNEXT-NEXT: RETURN [[ASHR]](s32), implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s16) = G_TRUNC %2(s32)
    %1:_(s16) = G_CONSTANT i16 13
    %3:_(s16) = G_ASHR %0, %1
    %4:_(s32) = G_ANYEXT %3(s16)
    RETURN %4(s32), implicit-def $arguments

...
---
name: ashrv_i16
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: ashrv_i16
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; NO-SIGNEXT-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ARGUMENT_i32_]], [[C]](s32)
    ; NO-SIGNEXT-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SHL]], [[C]](s32)
    ; NO-SIGNEXT-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; NO-SIGNEXT-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ARGUMENT_i32_1]], [[C1]]
    ; NO-SIGNEXT-NEXT: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[ASHR]], [[AND]](s32)
    ; NO-SIGNEXT-NEXT: RETURN [[ASHR1]](s32), implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: ashrv_i16
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; SIGNEXT-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; SIGNEXT-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[ARGUMENT_i32_]], 16
    ; SIGNEXT-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; SIGNEXT-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ARGUMENT_i32_1]], [[C]]
    ; SIGNEXT-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SEXT_INREG]], [[AND]](s32)
    ; SIGNEXT-NEXT: RETURN [[ASHR]](s32), implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s16) = G_TRUNC %2(s32)
    %3:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s16) = G_TRUNC %3(s32)
    %4:_(s16) = G_ASHR %0, %1
    %5:_(s32) = G_ANYEXT %4(s16)
    RETURN %5(s32), implicit-def $arguments

...
---
name: ashr_i32
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ashr_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[ARGUMENT_i32_]], [[C]](s32)
    ; CHECK-NEXT: RETURN [[ASHR]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s32) = G_CONSTANT i32 21
    %2:_(s32) = G_ASHR %0, %1
    RETURN %2(s32), implicit-def $arguments

...
---
name: ashrv_i32
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ashrv_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]](s32)
    ; CHECK-NEXT: RETURN [[ASHR]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %2:_(s32) = G_ASHR %0, %1
    RETURN %2(s32), implicit-def $arguments

...
---
name: ashr_i32_i8
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ashr_i32_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[ARGUMENT_i32_]], [[C]](s32)
    ; CHECK-NEXT: RETURN [[ASHR]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s8) = G_CONSTANT i8 21
    %2:_(s32) = G_ASHR %0, %1
    RETURN %2(s32), implicit-def $arguments

...
---
name: ashrv_i32_i8
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ashrv_i32_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ARGUMENT_i32_1]], [[C]]
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[ARGUMENT_i32_]], [[AND]](s32)
    ; CHECK-NEXT: RETURN [[ASHR]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %2:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s8) = G_TRUNC %2(s32)
    %3:_(s32) = G_ASHR %0, %1
    RETURN %3(s32), implicit-def $arguments

...
---
name: ashr_i64
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ashr_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 37
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[ARGUMENT_i64_]], [[C]](s64)
    ; CHECK-NEXT: RETURN [[ASHR]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_CONSTANT i64 37
    %2:_(s64) = G_ASHR %0, %1
    RETURN %2(s64), implicit-def $arguments

...
---
name: ashrv_i64
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ashrv_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i64_1:%[0-9]+]]:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[ARGUMENT_i64_]], [[ARGUMENT_i64_1]](s64)
    ; CHECK-NEXT: RETURN [[ASHR]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    %2:_(s64) = G_ASHR %0, %1
    RETURN %2(s64), implicit-def $arguments

...
---
name: ashr_i64_i8
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ashr_i64_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 37
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[C]], [[C1]]
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[ARGUMENT_i64_]], [[AND]](s64)
    ; CHECK-NEXT: RETURN [[ASHR]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s8) = G_CONSTANT i8 37
    %2:_(s64) = G_ASHR %0, %1
    RETURN %2(s64), implicit-def $arguments

...
---
name: ashrv_i64_i8
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ashrv_i64_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s64) = G_ANYEXT [[ARGUMENT_i32_]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[ANYEXT]], [[C]]
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[ARGUMENT_i64_]], [[AND]](s64)
    ; CHECK-NEXT: RETURN [[ASHR]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %2:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s8) = G_TRUNC %2(s32)
    %3:_(s64) = G_ASHR %0, %1
    RETURN %3(s64), implicit-def $arguments

...
