# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s

---
name:            const_i8_zext
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: const_i8_zext
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK-NEXT: RETURN [[C]](s32), implicit-def $arguments
    %0:_(s8) = G_CONSTANT i8 255
    %1:_(s32) = G_ZEXT %0(s8)
    RETURN %1(s32), implicit-def $arguments
...

---
name:            const_i8_sext
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: const_i8_sext
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: RETURN [[C]](s32), implicit-def $arguments
    %0:_(s8) = G_CONSTANT i8 255
    %1:_(s32) = G_SEXT %0(s8)
    RETURN %1(s32), implicit-def $arguments
...

---
name:            const_i8_aext
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: const_i8_aext
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: RETURN [[C]](s32), implicit-def $arguments
    %0:_(s8) = G_CONSTANT i8 255
    %1:_(s32) = G_ANYEXT %0(s8)
    RETURN %1(s32), implicit-def $arguments
...


---
name:            const_i16_zext
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: const_i16_zext
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK-NEXT: RETURN [[C]](s32), implicit-def $arguments
    %0:_(s16) = G_CONSTANT i16 65535
    %1:_(s32) = G_ZEXT %0(s16)
    RETURN %1(s32), implicit-def $arguments
...

---
name:            const_i16_sext
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: const_i16_sext
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: RETURN [[C]](s32), implicit-def $arguments
    %0:_(s16) = G_CONSTANT i16 65535
    %1:_(s32) = G_SEXT %0(s16)
    RETURN %1(s32), implicit-def $arguments
...

---
name:            const_i16_aext
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: const_i16_aext
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: RETURN [[C]](s32), implicit-def $arguments
    %0:_(s16) = G_CONSTANT i16 65535
    %1:_(s32) = G_ANYEXT %0(s16)
    RETURN %1(s32), implicit-def $arguments
...

---
name:            const_i32
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: const_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
    ; CHECK-NEXT: RETURN [[C]](s32), implicit-def $arguments
    %0:_(s32) = G_CONSTANT i32 4294967295
    RETURN %0(s32), implicit-def $arguments
...

---
name:            const_i64
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: const_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 -1
    ; CHECK-NEXT: RETURN [[C]](s64), implicit-def $arguments
    %0:_(s64) = G_CONSTANT i64 18446744073709551615
    RETURN %0(s64), implicit-def $arguments
...
