# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s

---
name:            implicit_def_i8
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: implicit_def_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: RETURN [[DEF]](s32), implicit-def $arguments
    %0:_(s8) = G_IMPLICIT_DEF
    %1:_(s32) = G_ANYEXT %0(s8)
    RETURN %1(s32), implicit-def $arguments
...

---
name:            implicit_def_i16
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: implicit_def_i16
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: RETURN [[DEF]](s32), implicit-def $arguments
    %0:_(s16) = G_IMPLICIT_DEF
    %1:_(s32) = G_ANYEXT %0(s16)
    RETURN %1(s32), implicit-def $arguments
...

---
name:            implicit_def_i32
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: implicit_def_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: RETURN [[DEF]](s32), implicit-def $arguments
    %0:_(s32) = G_IMPLICIT_DEF
    RETURN %0(s32), implicit-def $arguments
...

---
name:            implicit_def_i64
alignment:       1
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: implicit_def_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK-NEXT: RETURN [[DEF]](s64), implicit-def $arguments
    %0:_(s64) = G_IMPLICIT_DEF
    RETURN %0(s64), implicit-def $arguments
...
