# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s


---
name: rotl_i8
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotl_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ARGUMENT_i32_]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ARGUMENT_i32_]], [[C2]]
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[AND]], [[C1]](s32)
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s32) = disjoint G_OR [[SHL]], [[LSHR]]
    ; CHECK-NEXT: RETURN [[OR]](s32), implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s8) = G_TRUNC %2(s32)
    %1:_(s8) = G_CONSTANT i8 5
    %3:_(s8) = G_ROTL %0, %1
    %4:_(s32) = G_ANYEXT %3(s8)
    RETURN %4(s32), implicit-def $arguments

...
---
name: rotlv_i8
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotlv_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C]], [[ARGUMENT_i32_1]]
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ARGUMENT_i32_1]], [[C1]]
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ARGUMENT_i32_]], [[AND]](s32)
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[SUB]], [[C1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK-NEXT: [[AND2:%[0-9]+]]:_(s32) = G_AND [[ARGUMENT_i32_]], [[C2]]
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[AND2]], [[AND1]](s32)
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s32) = disjoint G_OR [[SHL]], [[LSHR]]
    ; CHECK-NEXT: RETURN [[OR]](s32), implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s8) = G_TRUNC %2(s32)
    %3:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s8) = G_TRUNC %3(s32)
    %4:_(s8) = G_ROTL %0, %1
    %5:_(s32) = G_ANYEXT %4(s8)
    RETURN %5(s32), implicit-def $arguments

...
---
name: rotl_i16
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotl_i16
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ARGUMENT_i32_]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ARGUMENT_i32_]], [[C2]]
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[AND]], [[C1]](s32)
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s32) = disjoint G_OR [[SHL]], [[LSHR]]
    ; CHECK-NEXT: RETURN [[OR]](s32), implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s16) = G_TRUNC %2(s32)
    %1:_(s16) = G_CONSTANT i16 13
    %3:_(s16) = G_ROTL %0, %1
    %4:_(s32) = G_ANYEXT %3(s16)
    RETURN %4(s32), implicit-def $arguments

...
---
name: rotlv_i16
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotlv_i16
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C]], [[ARGUMENT_i32_1]]
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ARGUMENT_i32_1]], [[C1]]
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[ARGUMENT_i32_]], [[AND]](s32)
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[SUB]], [[C1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK-NEXT: [[AND2:%[0-9]+]]:_(s32) = G_AND [[ARGUMENT_i32_]], [[C2]]
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[AND2]], [[AND1]](s32)
    ; CHECK-NEXT: [[OR:%[0-9]+]]:_(s32) = disjoint G_OR [[SHL]], [[LSHR]]
    ; CHECK-NEXT: RETURN [[OR]](s32), implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s16) = G_TRUNC %2(s32)
    %3:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s16) = G_TRUNC %3(s32)
    %4:_(s16) = G_ROTL %0, %1
    %5:_(s32) = G_ANYEXT %4(s16)
    RETURN %5(s32), implicit-def $arguments

...
---
name: rotl_i32
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotl_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK-NEXT: [[ROTL:%[0-9]+]]:_(s32) = G_ROTL [[ARGUMENT_i32_]], [[C]](s32)
    ; CHECK-NEXT: RETURN [[ROTL]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s32) = G_CONSTANT i32 21
    %2:_(s32) = G_ROTL %0, %1
    RETURN %2(s32), implicit-def $arguments

...
---
name: rotlv_i32
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotlv_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[ROTL:%[0-9]+]]:_(s32) = G_ROTL [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]](s32)
    ; CHECK-NEXT: RETURN [[ROTL]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %2:_(s32) = G_ROTL %0, %1
    RETURN %2(s32), implicit-def $arguments

...
---
name: rotl_i32_i8
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotl_i32_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK-NEXT: [[ROTL:%[0-9]+]]:_(s32) = G_ROTL [[ARGUMENT_i32_]], [[C]](s32)
    ; CHECK-NEXT: RETURN [[ROTL]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s8) = G_CONSTANT i8 21
    %2:_(s32) = G_ROTL %0, %1
    RETURN %2(s32), implicit-def $arguments

...
---
name: rotlv_i32_i8
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotlv_i32_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ARGUMENT_i32_1]], [[C]]
    ; CHECK-NEXT: [[ROTL:%[0-9]+]]:_(s32) = G_ROTL [[ARGUMENT_i32_]], [[AND]](s32)
    ; CHECK-NEXT: RETURN [[ROTL]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %2:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s8) = G_TRUNC %2(s32)
    %3:_(s32) = G_ROTL %0, %1
    RETURN %3(s32), implicit-def $arguments

...
---
name: rotl_i64
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotl_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 37
    ; CHECK-NEXT: [[ROTL:%[0-9]+]]:_(s64) = G_ROTL [[ARGUMENT_i64_]], [[C]](s64)
    ; CHECK-NEXT: RETURN [[ROTL]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_CONSTANT i64 37
    %2:_(s64) = G_ROTL %0, %1
    RETURN %2(s64), implicit-def $arguments

...
---
name: rotlv_i64
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotlv_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i64_1:%[0-9]+]]:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    ; CHECK-NEXT: [[ROTL:%[0-9]+]]:_(s64) = G_ROTL [[ARGUMENT_i64_]], [[ARGUMENT_i64_1]](s64)
    ; CHECK-NEXT: RETURN [[ROTL]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    %2:_(s64) = G_ROTL %0, %1
    RETURN %2(s64), implicit-def $arguments

...
---
name: rotl_i64_i8
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotl_i64_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 37
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[C]], [[C1]]
    ; CHECK-NEXT: [[ROTL:%[0-9]+]]:_(s64) = G_ROTL [[ARGUMENT_i64_]], [[AND]](s64)
    ; CHECK-NEXT: RETURN [[ROTL]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s8) = G_CONSTANT i8 37
    %2:_(s64) = G_ROTL %0, %1
    RETURN %2(s64), implicit-def $arguments

...
---
name: rotlv_i64_i8
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotlv_i64_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[ANYEXT:%[0-9]+]]:_(s64) = G_ANYEXT [[ARGUMENT_i32_]](s32)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[ANYEXT]], [[C]]
    ; CHECK-NEXT: [[ROTL:%[0-9]+]]:_(s64) = G_ROTL [[ARGUMENT_i64_]], [[AND]](s64)
    ; CHECK-NEXT: RETURN [[ROTL]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %2:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s8) = G_TRUNC %2(s32)
    %3:_(s64) = G_ROTL %0, %1
    RETURN %3(s64), implicit-def $arguments

...
