# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -mattr=-sign-ext -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s -check-prefixes=CHECK,NO-SIGNEXT
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -mattr=+sign-ext -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s -check-prefixes=CHECK,SIGNEXT

---
name: sext_inreg_i1_i32
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: sext_inreg_i1_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL %1, [[C]](s32)
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SHL]], [[C]](s32)
    ; CHECK-NEXT: RETURN [[ASHR]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s32) = G_SEXT_INREG %1(s32), 1
    RETURN %1(s32), implicit-def $arguments
...
---
name: sext_inreg_i8_i32
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: sext_inreg_i8_i32
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; NO-SIGNEXT-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL %1, [[C]](s32)
    ; NO-SIGNEXT-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SHL]], [[C]](s32)
    ; NO-SIGNEXT-NEXT: RETURN [[ASHR]](s32), implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: sext_inreg_i8_i32
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; SIGNEXT-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[SEXT_INREG]], 8
    ; SIGNEXT-NEXT: RETURN [[SEXT_INREG]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s32) = G_SEXT_INREG %1(s32), 8
    RETURN %1(s32), implicit-def $arguments
...
---
name: sext_inreg_i16_i32
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: sext_inreg_i16_i32
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; NO-SIGNEXT-NEXT: [[SHL:%[0-9]+]]:_(s32) = G_SHL %1, [[C]](s32)
    ; NO-SIGNEXT-NEXT: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[SHL]], [[C]](s32)
    ; NO-SIGNEXT-NEXT: RETURN [[ASHR]](s32), implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: sext_inreg_i16_i32
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; SIGNEXT-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[SEXT_INREG]], 16
    ; SIGNEXT-NEXT: RETURN [[SEXT_INREG]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s32) = G_SEXT_INREG %1(s32), 16
    RETURN %1(s32), implicit-def $arguments
...

---
name: sext_inreg_i1_i64
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: sext_inreg_i1_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 63
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:_(s64) = G_SHL %1, [[C]](s64)
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[SHL]], [[C]](s64)
    ; CHECK-NEXT: RETURN [[ASHR]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_SEXT_INREG %1(s64), 1
    RETURN %1(s64), implicit-def $arguments
...
---
name: sext_inreg_i8_i64
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: sext_inreg_i8_i64
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 56
    ; NO-SIGNEXT-NEXT: [[SHL:%[0-9]+]]:_(s64) = G_SHL %1, [[C]](s64)
    ; NO-SIGNEXT-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[SHL]], [[C]](s64)
    ; NO-SIGNEXT-NEXT: RETURN [[ASHR]](s64), implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: sext_inreg_i8_i64
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; SIGNEXT-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s64) = G_SEXT_INREG [[SEXT_INREG]], 8
    ; SIGNEXT-NEXT: RETURN [[SEXT_INREG]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_SEXT_INREG %1(s64), 8
    RETURN %1(s64), implicit-def $arguments
...
---
name: sext_inreg_i16_i64
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: sext_inreg_i16_i64
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 48
    ; NO-SIGNEXT-NEXT: [[SHL:%[0-9]+]]:_(s64) = G_SHL %1, [[C]](s64)
    ; NO-SIGNEXT-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[SHL]], [[C]](s64)
    ; NO-SIGNEXT-NEXT: RETURN [[ASHR]](s64), implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: sext_inreg_i16_i64
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; SIGNEXT-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s64) = G_SEXT_INREG [[SEXT_INREG]], 16
    ; SIGNEXT-NEXT: RETURN [[SEXT_INREG]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_SEXT_INREG %1(s64), 16
    RETURN %1(s64), implicit-def $arguments
...

---
name: sext_inreg_i32_i64
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: sext_inreg_i32_i64
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 32
    ; NO-SIGNEXT-NEXT: [[SHL:%[0-9]+]]:_(s64) = G_SHL %1, [[C]](s64)
    ; NO-SIGNEXT-NEXT: [[ASHR:%[0-9]+]]:_(s64) = G_ASHR [[SHL]], [[C]](s64)
    ; NO-SIGNEXT-NEXT: RETURN [[ASHR]](s64), implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: sext_inreg_i32_i64
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; SIGNEXT-NEXT: [[SEXT_INREG:%[0-9]+]]:_(s64) = G_SEXT_INREG [[SEXT_INREG]], 32
    ; SIGNEXT-NEXT: RETURN [[SEXT_INREG]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_SEXT_INREG %1(s64), 32
    RETURN %1(s64), implicit-def $arguments
...
