; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; PR1271
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

%struct..0anon = type { i32, i32 }
%struct..1anon = type { double }

define i32 @main() {
; CHECK-LABEL: @main(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[U:%.*]] = alloca [[STRUCT__1ANON:%.*]], align 8
; CHECK-NEXT:    store double 0x7FF0000000000000, ptr [[U]], align 8
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [[STRUCT__0ANON:%.*]], ptr [[U]], i64 0, i32 1
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[TMP5]], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = and i32 [[TMP6]], 2146435072
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i32 [[TMP0]], 2146435072
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[COND_FALSE:%.*]], label [[COND_TRUE:%.*]]
; CHECK:       cond_true:
; CHECK-NEXT:    ret i32 0
; CHECK:       cond_false:
; CHECK-NEXT:    ret i32 1
;
entry:
  %u = alloca %struct..1anon, align 8
  store double 0x7FF0000000000000, ptr %u
  %tmp5 = getelementptr %struct..0anon, ptr %u, i32 0, i32 1
  %tmp6 = load i32, ptr %tmp5
  %tmp7 = shl i32 %tmp6, 1
  %tmp8 = lshr i32 %tmp7, 21
  %tmp89 = trunc i32 %tmp8 to i16
  icmp ne i16 %tmp89, 2047
  zext i1 %0 to i8
  icmp ne i8 %1, 0
  br i1 %2, label %cond_true, label %cond_false

cond_true:
  ret i32 0

cond_false:
  ret i32 1
}

