; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define i1 @foo1(i1 %a, i1 %b) {
; CHECK-LABEL: define i1 @foo1(
; CHECK-SAME: i1 [[A:%.*]], i1 [[B:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = xor i1 [[B]], [[A]]
; CHECK-NEXT:    ret i1 [[R]]
;
  %r = sub i1 %a, %b
  ret i1 %r
}

define i1 @foo2(i1 %a, i1 %b) {
; CHECK-LABEL: define i1 @foo2(
; CHECK-SAME: i1 [[A:%.*]], i1 [[B:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = and i1 [[A]], [[B]]
; CHECK-NEXT:    ret i1 [[R]]
;
  %r = mul i1 %a, %b
  ret i1 %r
}

define i1 @foo3(i1 %a, i1 %b) {
; CHECK-LABEL: define i1 @foo3(
; CHECK-SAME: i1 [[A:%.*]], i1 [[B:%.*]]) {
; CHECK-NEXT:    ret i1 [[A]]
;
  %r = udiv i1 %a, %b
  ret i1 %r
}

define i1 @foo4(i1 %a, i1 %b) {
; CHECK-LABEL: define i1 @foo4(
; CHECK-SAME: i1 [[A:%.*]], i1 [[B:%.*]]) {
; CHECK-NEXT:    ret i1 [[A]]
;
  %r = sdiv i1 %a, %b
  ret i1 %r
}
