; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; Fold the div_ceil idiom:
;   add(zext(udiv(A, C)), zext(icmp ne(urem(A, C), 0)))
;     -> zext(udiv(add nuw(A, C - 1), C))
; when A + (C-1) is provably non-wrapping.

declare void @use(i64)

; Basic case: range-bounded i8 dividend, divisor 7.
; bits in [1, 32], so bits + 6 <= 38, no overflow.
define i64 @divceil_i8_bounded(i8 range(i8 1, 33) %bits) {
; CHECK-LABEL: @divceil_i8_bounded(
; CHECK-NEXT:    [[TMP1:%.*]] = add nuw nsw i8 [[BITS:%.*]], 6
; CHECK-NEXT:    [[TMP2:%.*]] = udiv i8 [[TMP1]], 7
; CHECK-NEXT:    [[RESULT:%.*]] = zext nneg i8 [[TMP2]] to i64
; CHECK-NEXT:    ret i64 [[RESULT]]
;
  %d = udiv i8 %bits, 7
  %d.ext = zext i8 %d to i64
  %r = urem i8 %bits, 7
  %cond = icmp ne i8 %r, 0
  %round = zext i1 %cond to i64
  %result = add i64 %d.ext, %round
  ret i64 %result
}

; Commuted: zext(icmp) on the left, zext(udiv) on the right.
define i64 @divceil_i8_bounded_commuted(i8 range(i8 1, 33) %bits) {
; CHECK-LABEL: @divceil_i8_bounded_commuted(
; CHECK-NEXT:    [[TMP1:%.*]] = add nuw nsw i8 [[BITS:%.*]], 6
; CHECK-NEXT:    [[TMP2:%.*]] = udiv i8 [[TMP1]], 7
; CHECK-NEXT:    [[RESULT:%.*]] = zext nneg i8 [[TMP2]] to i64
; CHECK-NEXT:    ret i64 [[RESULT]]
;
  %d = udiv i8 %bits, 7
  %d.ext = zext i8 %d to i64
  %r = urem i8 %bits, 7
  %cond = icmp ne i8 %r, 0
  %round = zext i1 %cond to i64
  %result = add i64 %round, %d.ext
  ret i64 %result
}

; Negative: unbounded i8 dividend -- bits could be 250+, overflow possible.
define i64 @divceil_i8_unbounded(i8 %bits) {
; CHECK-LABEL: @divceil_i8_unbounded(
; CHECK-NEXT:    [[D:%.*]] = udiv i8 [[BITS:%.*]], 7
; CHECK-NEXT:    [[D_EXT:%.*]] = zext nneg i8 [[D]] to i64
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[BITS]], 7
; CHECK-NEXT:    [[COND:%.*]] = icmp ne i8 [[R]], 0
; CHECK-NEXT:    [[ROUND:%.*]] = zext i1 [[COND]] to i64
; CHECK-NEXT:    [[RESULT:%.*]] = add nuw nsw i64 [[D_EXT]], [[ROUND]]
; CHECK-NEXT:    ret i64 [[RESULT]]
;
  %d = udiv i8 %bits, 7
  %d.ext = zext i8 %d to i64
  %r = urem i8 %bits, 7
  %cond = icmp ne i8 %r, 0
  %round = zext i1 %cond to i64
  %result = add i64 %d.ext, %round
  ret i64 %result
}

; Negative: udiv has multiple uses, one-use requirement not met.
define i64 @divceil_i8_udiv_multiuse(i8 range(i8 1, 33) %bits) {
; CHECK-LABEL: @divceil_i8_udiv_multiuse(
; CHECK-NEXT:    [[TMP2:%.*]] = udiv i8 [[TMP1:%.*]], 7
; CHECK-NEXT:    [[RESULT:%.*]] = zext nneg i8 [[TMP2]] to i64
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[TMP1]], 7
; CHECK-NEXT:    [[COND:%.*]] = icmp ne i8 [[R]], 0
; CHECK-NEXT:    [[ROUND:%.*]] = zext i1 [[COND]] to i64
; CHECK-NEXT:    [[RESULT1:%.*]] = add nuw nsw i64 [[RESULT]], [[ROUND]]
; CHECK-NEXT:    call void @use(i64 [[RESULT]])
; CHECK-NEXT:    ret i64 [[RESULT1]]
;
  %d = udiv i8 %bits, 7
  %d.ext = zext i8 %d to i64
  %r = urem i8 %bits, 7
  %cond = icmp ne i8 %r, 0
  %round = zext i1 %cond to i64
  %result = add i64 %d.ext, %round
  call void @use(i64 %d.ext)
  ret i64 %result
}
