; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

declare i16 @llvm.smin.i16(i16, i16)
declare i32 @llvm.smin.i32(i32, i32)
declare <2 x i16> @llvm.smin.v2i16(<2 x i16>, <2 x i16>)
declare void @use_i16(i16)

define i16 @test_issue_166885(i16 %arg0, i16 %arg1) {
; CHECK-LABEL: @test_issue_166885(
; CHECK-NEXT:    %v2 = icmp slt i16 %arg1, 1
; CHECK-NEXT:    %v3 = sub nsw i16 %arg1, 1
; CHECK-NEXT:    %v4 = tail call i16 @llvm.smin.i16(i16 %arg0, i16 %v3)
; CHECK-NEXT:    %v5 = select i1 %v2, i16 0, i16 %v4
; CHECK-NEXT:    ret i16 %v5
;
  %v0 = sub nsw i16 0, %arg1
  %v1 = sub nsw i16 %arg0, %arg1
  %v2 = icmp slt i16 %arg1, 1
  %v3 = tail call i16 @llvm.smin.i16(i16 %v1, i16 -1)
  %v4 = select i1 %v2, i16 %v0, i16 %v3
  %v5 = add nsw i16 %v4, %arg1
  ret i16 %v5
}

define i16 @test_commutative(i16 %a, i16 %b) {
; CHECK-LABEL: @test_commutative(
; CHECK-NEXT:    %v2 = icmp slt i16 %b, 1
; CHECK-NEXT:    %v3 = sub nsw i16 %b, 1
; CHECK-NEXT:    %v4 = tail call i16 @llvm.smin.i16(i16 %a, i16 %v3)
; CHECK-NEXT:    %v5 = select i1 %v2, i16 0, i16 %v4
; CHECK-NEXT:    ret i16 %v5
;
  %v0 = sub nsw i16 0, %b
  %v1 = sub nsw i16 %a, %b
  %v2 = icmp slt i16 %b, 1
  %v3 = tail call i16 @llvm.smin.i16(i16 %v1, i16 -1)
  %v4 = select i1 %v2, i16 %v0, i16 %v3
  %v5 = add nsw i16 %b, %v4
  ret i16 %v5
}

define i32 @test_i32(i32 %a, i32 %b) {
; CHECK-LABEL: @test_i32(
; CHECK-NEXT:    %v2 = icmp slt i32 %b, 1
; CHECK-NEXT:    %v3 = sub nsw i32 %b, 1
; CHECK-NEXT:    %v4 = tail call i32 @llvm.smin.i32(i32 %a, i32 %v3)
; CHECK-NEXT:    %v5 = select i1 %v2, i32 0, i32 %v4
; CHECK-NEXT:    ret i32 %v5
;
  %v0 = sub nsw i32 0, %b
  %v1 = sub nsw i32 %a, %b
  %v2 = icmp slt i32 %b, 1
  %v3 = tail call i32 @llvm.smin.i32(i32 %v1, i32 -1)
  %v4 = select i1 %v2, i32 %v0, i32 %v3
  %v5 = add nsw i32 %v4, %b
  ret i32 %v5
}

define <2 x i16> @test_vector(<2 x i16> %a, <2 x i16> %b) {
; CHECK-LABEL: @test_vector(
; CHECK-NEXT:    %v2 = icmp slt <2 x i16> %b, <i16 1, i16 1>
; CHECK-NEXT:    %v_minus_one = sub nsw <2 x i16> zeroinitializer, <i16 1, i16 1>
; CHECK-NEXT:    %v3 = add <2 x i16> %b, %v_minus_one
; CHECK-NEXT:    %v4 = tail call <2 x i16> @llvm.smin.v2i16(<2 x i16> %a, <2 x i16> %v3)
; CHECK-NEXT:    %v5 = select <2 x i1> %v2, <2 x i16> zeroinitializer, <2 x i16> %v4
; CHECK-NEXT:    ret <2 x i16> %v5
;
  %v0 = sub nsw <2 x i16> zeroinitializer, %b
  %v1 = sub nsw <2 x i16> %a, %b
  %v2 = icmp slt <2 x i16> %b, <i16 1, i16 1>
  %v_minus_one = sub nsw <2 x i16> zeroinitializer, <i16 1, i16 1>

  %v3 = tail call <2 x i16> @llvm.smin.v2i16(<2 x i16> %v1, <2 x i16> %v_minus_one)
  %v4 = select <2 x i1> %v2, <2 x i16> %v0, <2 x i16> %v3
  %v5 = add nsw <2 x i16> %v4, %b
  ret <2 x i16> %v5
}

define i16 @test_multi_use(i16 %a, i16 %b) {
; CHECK-LABEL: @test_multi_use(
; CHECK-NEXT:    %v1 = sub nsw i16 %a, %b
; CHECK-NEXT:    %v2 = icmp slt i16 %b, 1
; CHECK-NEXT:    %v3 = tail call i16 @llvm.smin.i16(i16 %v1, i16 -1)
; CHECK-NEXT:    call void @use_i16(i16 %v3)
; CHECK-NEXT:    %v0 = sub nsw i16 0, %b
; CHECK-NEXT:    %v4 = select i1 %v2, i16 %v0, i16 %v3
; CHECK-NEXT:    %v5 = add nsw i16 %v4, %b
; CHECK-NEXT:    ret i16 %v5
;
  %v0 = sub nsw i16 0, %b
  %v1 = sub nsw i16 %a, %b
  %v2 = icmp slt i16 %b, 1
  %v3 = tail call i16 @llvm.smin.i16(i16 %v1, i16 -1)
  call void @use_i16(i16 %v3)
  %v4 = select i1 %v2, i16 %v0, i16 %v3
  %v5 = add nsw i16 %v4, %b
  ret i16 %v5
}


define i16 @test_negative_no_nsw_add(i16 %a, i16 %b) {
; CHECK-LABEL: @test_negative_no_nsw_add(
; CHECK-NEXT:    %v0 = sub nsw i16 0, %b
; CHECK-NEXT:    %v1 = sub nsw i16 %a, %b
; CHECK-NEXT:    %v2 = icmp slt i16 %b, 1
; CHECK-NEXT:    %v3 = tail call i16 @llvm.smin.i16(i16 %v1, i16 -1)
; CHECK-NEXT:    %v4 = select i1 %v2, i16 %v0, i16 %v3
; CHECK-NEXT:    %v5 = add i16 %v4, %b
; CHECK-NEXT:    ret i16 %v5
;
  %v0 = sub nsw i16 0, %b
  %v1 = sub nsw i16 %a, %b
  %v2 = icmp slt i16 %b, 1
  %v3 = tail call i16 @llvm.smin.i16(i16 %v1, i16 -1)
  %v4 = select i1 %v2, i16 %v0, i16 %v3
  %v5 = add i16 %v4, %b
  ret i16 %v5
}

define i16 @test_negative_no_nsw_sub(i16 %a, i16 %b) {
; CHECK-LABEL: @test_negative_no_nsw_sub(
; CHECK-NEXT:    %v0 = sub nsw i16 0, %b
; CHECK-NEXT:    %v1 = sub i16 %a, %b
; CHECK-NEXT:    %v2 = icmp slt i16 %b, 1
; CHECK-NEXT:    %v3 = tail call i16 @llvm.smin.i16(i16 %v1, i16 -1)
; CHECK-NEXT:    %v4 = select i1 %v2, i16 %v0, i16 %v3
; CHECK-NEXT:    %v5 = add nsw i16 %v4, %b
; CHECK-NEXT:    ret i16 %v5
;
  %v0 = sub nsw i16 0, %b
  %v1 = sub i16 %a, %b
  %v2 = icmp slt i16 %b, 1
  %v3 = tail call i16 @llvm.smin.i16(i16 %v1, i16 -1)
  %v4 = select i1 %v2, i16 %v0, i16 %v3
  %v5 = add nsw i16 %v4, %b
  ret i16 %v5
}