; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; Test reassociation of: ((X | C1) >> N) & C2 --> ((X >> N) & C2) | ((C1 >> N) & C2)
; This is valid when the or is disjoint, exposing a constant for GEP offset folding.

define i32 @and_lshr_disjoint_or(i32 %val) {
; CHECK-LABEL: @and_lshr_disjoint_or(
; CHECK-NEXT:    [[TMP1:%.*]] = lshr i32 [[VAL:%.*]], 4
; CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[TMP1]], 752
; CHECK-NEXT:    [[AND:%.*]] = or disjoint i32 [[TMP2]], 2048
; CHECK-NEXT:    ret i32 [[AND]]
;
  %or = or disjoint i32 %val, 32768
  %lshr = lshr i32 %or, 4
  %and = and i32 %lshr, 2800
  ret i32 %and
}

define i32 @and_lshr_disjoint_or_exact(i32 %val) {
; CHECK-LABEL: @and_lshr_disjoint_or_exact(
; CHECK-NEXT:    [[TMP1:%.*]] = lshr i32 [[VAL:%.*]], 4
; CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[TMP1]], 752
; CHECK-NEXT:    [[AND:%.*]] = or disjoint i32 [[TMP2]], 2048
; CHECK-NEXT:    ret i32 [[AND]]
;
  %or = or disjoint i32 %val, 32768
  %lshr = lshr exact i32 %or, 4
  %and = and i32 %lshr, 2800
  ret i32 %and
}

define i32 @and_lshr_disjoint_or_different_constant(i32 %val) {
; CHECK-LABEL: @and_lshr_disjoint_or_different_constant(
; CHECK-NEXT:    [[TMP1:%.*]] = lshr i32 [[VAL:%.*]], 4
; CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[TMP1]], 752
; CHECK-NEXT:    [[AND:%.*]] = or disjoint i32 [[TMP2]], 2048
; CHECK-NEXT:    ret i32 [[AND]]
;
  %or = or disjoint i32 %val, 32800
  %lshr = lshr exact i32 %or, 4
  %and = and i32 %lshr, 2800
  ret i32 %and
}

; Negative test: non-disjoint or should not be transformed
define i32 @and_lshr_or_non_disjoint(i32 %val) {
; CHECK-LABEL: @and_lshr_or_non_disjoint(
; CHECK-NEXT:    [[LSHR:%.*]] = lshr i32 [[OR:%.*]], 4
; CHECK-NEXT:    [[LSHR1:%.*]] = and i32 [[LSHR]], 752
; CHECK-NEXT:    [[AND:%.*]] = or disjoint i32 [[LSHR1]], 2048
; CHECK-NEXT:    ret i32 [[AND]]
;
  %or = or i32 %val, 32768
  %lshr = lshr i32 %or, 4
  %and = and i32 %lshr, 2800
  ret i32 %and
}

; Negative test: multi-use lshr should not be transformed
define i32 @and_lshr_disjoint_or_multi_use(i32 %val, ptr %p) {
; CHECK-LABEL: @and_lshr_disjoint_or_multi_use(
; CHECK-NEXT:    [[OR:%.*]] = lshr i32 [[VAL:%.*]], 4
; CHECK-NEXT:    [[LSHR:%.*]] = or i32 [[OR]], 2048
; CHECK-NEXT:    store i32 [[LSHR]], ptr [[P:%.*]], align 4
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[LSHR]], 2800
; CHECK-NEXT:    ret i32 [[AND]]
;
  %or = or disjoint i32 %val, 32768
  %lshr = lshr i32 %or, 4
  store i32 %lshr, ptr %p
  %and = and i32 %lshr, 2800
  ret i32 %and
}

; Test with larger shift amount
define i32 @and_lshr_disjoint_or_larger_shift(i32 %val) {
; CHECK-LABEL: @and_lshr_disjoint_or_larger_shift(
; CHECK-NEXT:    [[TMP1:%.*]] = lshr i32 [[VAL:%.*]], 8
; CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[TMP1]], 240
; CHECK-NEXT:    [[AND:%.*]] = or disjoint i32 [[TMP2]], 15
; CHECK-NEXT:    ret i32 [[AND]]
;
  %or = or disjoint i32 %val, 4080
  %lshr = lshr i32 %or, 8
  %and = and i32 %lshr, 255
  ret i32 %and
}

; Test with i64
define i64 @and_lshr_disjoint_or_i64(i64 %val) {
; CHECK-LABEL: @and_lshr_disjoint_or_i64(
; CHECK-NEXT:    [[TMP1:%.*]] = lshr i64 [[VAL:%.*]], 4
; CHECK-NEXT:    [[TMP2:%.*]] = and i64 [[TMP1]], 752
; CHECK-NEXT:    [[AND:%.*]] = or disjoint i64 [[TMP2]], 2048
; CHECK-NEXT:    ret i64 [[AND]]
;
  %or = or disjoint i64 %val, 32768
  %lshr = lshr i64 %or, 4
  %and = and i64 %lshr, 2800
  ret i64 %and
}

; Test with vector types
define <4 x i32> @and_lshr_disjoint_or_vec(<4 x i32> %val) {
; CHECK-LABEL: @and_lshr_disjoint_or_vec(
; CHECK-NEXT:    [[TMP1:%.*]] = lshr <4 x i32> [[VAL:%.*]], splat (i32 4)
; CHECK-NEXT:    [[TMP2:%.*]] = and <4 x i32> [[TMP1]], splat (i32 752)
; CHECK-NEXT:    [[AND:%.*]] = or disjoint <4 x i32> [[TMP2]], splat (i32 2048)
; CHECK-NEXT:    ret <4 x i32> [[AND]]
;
  %or = or disjoint <4 x i32> %val, <i32 32768, i32 32768, i32 32768, i32 32768>
  %lshr = lshr <4 x i32> %or, <i32 4, i32 4, i32 4, i32 4>
  %and = and <4 x i32> %lshr, <i32 2800, i32 2800, i32 2800, i32 2800>
  ret <4 x i32> %and
}

; Negative test: ashr should not be transformed (this pattern is for lshr only)
define i32 @and_ashr_disjoint_or(i32 %val) {
; CHECK-LABEL: @and_ashr_disjoint_or(
; CHECK-NEXT:    [[OR:%.*]] = lshr i32 [[VAL:%.*]], 4
; CHECK-NEXT:    [[ASHR:%.*]] = and i32 [[OR]], 752
; CHECK-NEXT:    [[AND:%.*]] = or disjoint i32 [[ASHR]], 2048
; CHECK-NEXT:    ret i32 [[AND]]
;
  %or = or disjoint i32 %val, 32768
  %ashr = ashr i32 %or, 4
  %and = and i32 %ashr, 2800
  ret i32 %and
}

; Test when result constant is zero (optimization opportunity)
define i32 @and_lshr_disjoint_or_const_result_zero(i32 %val) {
; CHECK-LABEL: @and_lshr_disjoint_or_const_result_zero(
; CHECK-NEXT:    [[TMP1:%.*]] = lshr i32 [[VAL:%.*]], 8
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[TMP1]], 255
; CHECK-NEXT:    ret i32 [[AND]]
;
  %or = or disjoint i32 %val, 128
  %lshr = lshr i32 %or, 8
  %and = and i32 %lshr, 255
  ret i32 %and
}
