; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare void @llvm.assume(i1) #1
declare ptr @get_ptr()
declare void @use_i64(i64)

; Check that the assume has not been removed:

define i32 @align_to_bundle(ptr %a) #0 {
; CHECK-LABEL: @align_to_bundle(
; CHECK-NEXT:    [[T0:%.*]] = load i32, ptr [[A:%.*]], align 4
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[A]], i64 32) ]
; CHECK-NEXT:    ret i32 [[T0]]
;
  %t0 = load i32, ptr %a, align 4
  %ptrint = ptrtoint ptr %a to i64
  %maskedptr = and i64 %ptrint, 31
  %maskcond = icmp eq i64 %maskedptr, 0
  tail call void @llvm.assume(i1 %maskcond)
  ret i32 %t0
}

define i32 @align_to_bundle_ptrtoaddr(ptr %a) #0 {
; CHECK-LABEL: @align_to_bundle_ptrtoaddr(
; CHECK-NEXT:    [[T0:%.*]] = load i32, ptr [[A:%.*]], align 4
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[A]], i64 32) ]
; CHECK-NEXT:    ret i32 [[T0]]
;
  %t0 = load i32, ptr %a, align 4
  %ptrint = ptrtoaddr ptr %a to i64
  %maskedptr = and i64 %ptrint, 31
  %maskcond = icmp eq i64 %maskedptr, 0
  tail call void @llvm.assume(i1 %maskcond)
  ret i32 %t0
}

define i32 @align_assume_trunc_cond(ptr %a) #0 {
; CHECK-LABEL: @align_assume_trunc_cond(
; CHECK-NEXT:    [[T0:%.*]] = load i32, ptr [[A:%.*]], align 4
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[A]], i64 2) ]
; CHECK-NEXT:    ret i32 [[T0]]
;
  %t0 = load i32, ptr %a, align 4
  %ptrint = ptrtoint ptr %a to i64
  %trunc = trunc i64 %ptrint to i1
  %maskcond = xor i1 %trunc, true
  tail call void @llvm.assume(i1 %maskcond)
  ret i32 %t0
}

define void @align_32bit(ptr %ptr) {
; CHECK-LABEL: @align_32bit(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[PTR:%.*]], i64 4294967296) ]
; CHECK-NEXT:    ret void
;
entry:
  %0 = ptrtoint ptr %ptr to i64
  %trunc = trunc i64 %0 to i32
  %cmp = icmp eq i32 0, %trunc
  call void @llvm.assume(i1 %cmp)
  ret void
}

define void @align_63bit(ptr %ptr) {
; CHECK-LABEL: @align_63bit(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[PTR:%.*]], i64 -9223372036854775808) ]
; CHECK-NEXT:    ret void
;
entry:
  %0 = ptrtoint ptr %ptr to i64
  %trunc = trunc i64 %0 to i63
  %cmp = icmp eq i63 0, %trunc
  call void @llvm.assume(i1 %cmp)
  ret void
}

define void @align_with_offset_less_than_align(ptr %ptr) {
; CHECK-LABEL: @align_with_offset_less_than_align(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[INT:%.*]] = ptrtoint ptr [[PTR:%.*]] to i64
; CHECK-NEXT:    [[ADD:%.*]] = add i64 [[INT]], 3
; CHECK-NEXT:    [[AND:%.*]] = and i64 [[ADD]], 7
; CHECK-NEXT:    call void @use_i64(i64 [[AND]])
; CHECK-NEXT:    ret void
;
entry:
  %int = ptrtoint ptr %ptr to i64
  %add = add i64 %int, 3
  %and = and i64 %add, 7
  %cmp = icmp eq i64 0, %and
  call void @llvm.assume(i1 %cmp)
  call void @use_i64(i64 %and)
  ret void
}

define void @align_with_offset_greater_than_align(ptr %ptr) {
; CHECK-LABEL: @align_with_offset_greater_than_align(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[INT:%.*]] = ptrtoint ptr [[PTR:%.*]] to i64
; CHECK-NEXT:    [[ADD:%.*]] = add i64 [[INT]], 6
; CHECK-NEXT:    [[AND:%.*]] = and i64 [[ADD]], 6
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[PTR]], i64 2) ]
; CHECK-NEXT:    call void @use_i64(i64 [[AND]])
; CHECK-NEXT:    ret void
;
entry:
  %int = ptrtoint ptr %ptr to i64
  %add = add i64 %int, 14
  %and = and i64 %add, 7
  %cmp = icmp eq i64 0, %and
  call void @llvm.assume(i1 %cmp)
  call void @use_i64(i64 %and)
  ret void
}

define void @align_with_constant_offset_0(ptr %ptr) {
; CHECK-LABEL: @align_with_constant_offset_0(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[PTR:%.*]], i64 16) ]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[PTR]], i64 8, i64 0) ]
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "align"(ptr %ptr, i64 16) ]
  call void @llvm.assume(i1 true) [ "align"(ptr %ptr, i64 8, i64 0) ]
  ret void
}

define void @align_with_constant_offset_1(ptr %ptr) {
; CHECK-LABEL: @align_with_constant_offset_1(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[PTR:%.*]], i64 16) ]
; CHECK-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr [[PTR]], i64 9
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[PTR2]], i64 8, i64 1) ]
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "align"(ptr %ptr, i64 16) ]
  %ptr2 = getelementptr i8, ptr %ptr, i64 9
  call void @llvm.assume(i1 true) [ "align"(ptr %ptr2, i64 8, i64 1) ]
  ret void
}

define void @align_with_constant_offset_4(ptr %ptr) {
; CHECK-LABEL: @align_with_constant_offset_4(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[PTR:%.*]], i64 16) ]
; CHECK-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr [[PTR]], i64 4
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[PTR2]], i64 8, i64 4) ]
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "align"(ptr %ptr, i64 16) ]
  %ptr2 = getelementptr i8, ptr %ptr, i64 4
  call void @llvm.assume(i1 true) [ "align"(ptr %ptr2, i64 8, i64 4) ]
  ret void
}

define void @align_with_constant_offset_8(ptr %ptr) {
; CHECK-LABEL: @align_with_constant_offset_8(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[PTR:%.*]], i64 16) ]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[PTR]], i64 8, i64 8) ]
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "align"(ptr %ptr, i64 16) ]
  call void @llvm.assume(i1 true) [ "align"(ptr %ptr, i64 8, i64 8) ]
  ret void
}

define void @align_with_variable_offset(ptr %ptr, i64 %offset) {
; CHECK-LABEL: @align_with_variable_offset(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[PTR:%.*]], i64 16) ]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[PTR]], i64 8, i64 [[OFFSET:%.*]]) ]
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "align"(ptr %ptr, i64 16) ]
  call void @llvm.assume(i1 true) [ "align"(ptr %ptr, i64 8, i64 %offset) ]
  ret void
}

define void @redundant_align() {
; CHECK-LABEL: @redundant_align(
; CHECK-NEXT:    [[PTR:%.*]] = call ptr @get_ptr()
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[PTR]], i64 8) ]
; CHECK-NEXT:    ret void
;
  %ptr = call ptr @get_ptr()
  call void @llvm.assume(i1 true) [ "align"(ptr %ptr, i64 8) ]
  call void @llvm.assume(i1 true) [ "align"(ptr %ptr, i64 8) ]
  ret void
}

define void @non_power_of_two_align(ptr %ptr) {
; CHECK-LABEL: @non_power_of_two_align(
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "align"(ptr %ptr, i64 3) ]
  ret void
}

; Same check as in @foo1, but make sure it works if the assume is first too.

define i32 @foo2(ptr %a) #0 {
; CHECK-LABEL: @foo2(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[A:%.*]], i64 32) ]
; CHECK-NEXT:    [[T0:%.*]] = load i32, ptr [[A]], align 4
; CHECK-NEXT:    ret i32 [[T0]]
;
  %ptrint = ptrtoint ptr %a to i64
  %maskedptr = and i64 %ptrint, 31
  %maskcond = icmp eq i64 %maskedptr, 0
  tail call void @llvm.assume(i1 %maskcond)
  %t0 = load i32, ptr %a, align 4
  ret i32 %t0
}

define i32 @simple(i32 %a) #1 {
; CHECK-LABEL: @simple(
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[A:%.*]], 4
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    ret i32 [[A]]
;
  %cmp = icmp eq i32 %a, 4
  tail call void @llvm.assume(i1 %cmp)
  ret i32 %a
}

define i32 @can1(i1 %a, i1 %b, i1 %c) {
; CHECK-LABEL: @can1(
; CHECK-NEXT:    call void @llvm.assume(i1 [[A:%.*]])
; CHECK-NEXT:    call void @llvm.assume(i1 [[B:%.*]])
; CHECK-NEXT:    call void @llvm.assume(i1 [[C:%.*]])
; CHECK-NEXT:    ret i32 5
;
  %and1 = and i1 %a, %b
  %and  = and i1 %and1, %c
  tail call void @llvm.assume(i1 %and)
  ret i32 5
}

define i32 @can1_logical(i1 %a, i1 %b, i1 %c) {
; CHECK-LABEL: @can1_logical(
; CHECK-NEXT:    call void @llvm.assume(i1 [[A:%.*]])
; CHECK-NEXT:    call void @llvm.assume(i1 [[B:%.*]])
; CHECK-NEXT:    call void @llvm.assume(i1 [[C:%.*]])
; CHECK-NEXT:    ret i32 5
;
  %and1 = select i1 %a, i1 %b, i1 false
  %and  = select i1 %and1, i1 %c, i1 false
  tail call void @llvm.assume(i1 %and)
  ret i32 5
}

define i32 @can2(i1 %a, i1 %b, i1 %c) {
; CHECK-LABEL: @can2(
; CHECK-NEXT:    [[TMP1:%.*]] = xor i1 [[A:%.*]], true
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP1]])
; CHECK-NEXT:    [[TMP2:%.*]] = xor i1 [[B:%.*]], true
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP2]])
; CHECK-NEXT:    ret i32 5
;
  %v = or i1 %a, %b
  %w = xor i1 %v, 1
  tail call void @llvm.assume(i1 %w)
  ret i32 5
}

define i32 @can2_logical(i1 %a, i1 %b, i1 %c) {
; CHECK-LABEL: @can2_logical(
; CHECK-NEXT:    [[TMP1:%.*]] = xor i1 [[A:%.*]], true
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP1]])
; CHECK-NEXT:    [[TMP2:%.*]] = xor i1 [[B:%.*]], true
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP2]])
; CHECK-NEXT:    ret i32 5
;
  %v = select i1 %a, i1 true, i1 %b
  %w = xor i1 %v, 1
  tail call void @llvm.assume(i1 %w)
  ret i32 5
}

define i32 @bar1(i32 %a) #0 {
; CHECK-LABEL: @bar1(
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[A:%.*]], 7
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[AND]], 1
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    ret i32 1
;
  %and1 = and i32 %a, 3
  %and = and i32 %a, 7
  %cmp = icmp eq i32 %and, 1
  tail call void @llvm.assume(i1 %cmp)
  ret i32 %and1
}

define i32 @bar2(i32 %a) #0 {
; CHECK-LABEL: @bar2(
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[A:%.*]], 7
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[AND]], 1
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    ret i32 1
;
  %and = and i32 %a, 7
  %cmp = icmp eq i32 %and, 1
  tail call void @llvm.assume(i1 %cmp)
  %and1 = and i32 %a, 3
  ret i32 %and1
}

define i32 @bar3(i32 %a, i1 %x, i1 %y) #0 {
; CHECK-LABEL: @bar3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[X:%.*]])
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[A:%.*]], 7
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[AND]], 1
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[Y:%.*]])
; CHECK-NEXT:    ret i32 1
;
entry:
  %and1 = and i32 %a, 3

; Don't be fooled by other assumes around.

  tail call void @llvm.assume(i1 %x)

  %and = and i32 %a, 7
  %cmp = icmp eq i32 %and, 1
  tail call void @llvm.assume(i1 %cmp)

  tail call void @llvm.assume(i1 %y)

  ret i32 %and1
}

; If we allow recursive known bits queries based on
; assumptions, we could do better here:
; a == b and a & 7 == 1, so b & 7 == 1, so b & 3 == 1, so return 1.

define i32 @known_bits_recursion_via_assumes(i32 %a, i32 %b) {
; CHECK-LABEL: @known_bits_recursion_via_assumes(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[AND1:%.*]] = and i32 [[B:%.*]], 3
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[A:%.*]], 7
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[AND]], 1
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[A]], [[B]]
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP2]])
; CHECK-NEXT:    ret i32 [[AND1]]
;
entry:
  %and1 = and i32 %b, 3
  %and = and i32 %a, 7
  %cmp = icmp eq i32 %and, 1
  tail call void @llvm.assume(i1 %cmp)
  %cmp2 = icmp eq i32 %a, %b
  tail call void @llvm.assume(i1 %cmp2)
  ret i32 %and1
}

define i32 @icmp1(i32 %a) #0 {
; CHECK-LABEL: @icmp1(
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[A:%.*]], 5
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %cmp = icmp sgt i32 %a, 5
  tail call void @llvm.assume(i1 %cmp)
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @icmp2(i32 %a) #0 {
; CHECK-LABEL: @icmp2(
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[A:%.*]], 5
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    ret i32 0
;
  %cmp = icmp sgt i32 %a, 5
  tail call void @llvm.assume(i1 %cmp)
  %t0 = zext i1 %cmp to i32
  %lnot.ext = xor i32 %t0, 1
  ret i32 %lnot.ext
}

; If the 'not' of a condition is known true, then the condition must be false.

define i1 @assume_not(i1 %cond) {
; CHECK-LABEL: @assume_not(
; CHECK-NEXT:    [[NOTCOND:%.*]] = xor i1 [[COND:%.*]], true
; CHECK-NEXT:    call void @llvm.assume(i1 [[NOTCOND]])
; CHECK-NEXT:    ret i1 [[COND]]
;
  %notcond = xor i1 %cond, true
  call void @llvm.assume(i1 %notcond)
  ret i1 %cond
}

declare void @escape(ptr %a)

; Canonicalize a nonnull assumption on a load into metadata form.

define i32 @bundle1(ptr %P) {
; CHECK-LABEL: @bundle1(
; CHECK-NEXT:    tail call void @llvm.assume(i1 true) [ "nonnull"(ptr [[P:%.*]]) ]
; CHECK-NEXT:    [[LOAD:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    ret i32 [[LOAD]]
;
  tail call void @llvm.assume(i1 true) ["nonnull"(ptr %P)]
  %load = load i32, ptr %P
  ret i32 %load
}

define i32 @bundle2(ptr %P) {
; CHECK-LABEL: @bundle2(
; CHECK-NEXT:    [[LOAD:%.*]] = load i32, ptr [[P:%.*]], align 4
; CHECK-NEXT:    ret i32 [[LOAD]]
;
  tail call void @llvm.assume(i1 true) ["ignore"(ptr undef)]
  %load = load i32, ptr %P
  ret i32 %load
}

define i1 @nonnull1(ptr %a) {
; CHECK-LABEL: @nonnull1(
; CHECK-NEXT:    [[LOAD:%.*]] = load ptr, ptr [[A:%.*]], align 8, !nonnull [[META6:![0-9]+]], !noundef [[META6]]
; CHECK-NEXT:    tail call void @escape(ptr nonnull [[LOAD]])
; CHECK-NEXT:    ret i1 false
;
  %load = load ptr, ptr %a
  %cmp = icmp ne ptr %load, null
  tail call void @llvm.assume(i1 %cmp)
  tail call void @escape(ptr %load)
  %rval = icmp eq ptr %load, null
  ret i1 %rval
}

; Make sure the above canonicalization applies only
; to pointer types.  Doing otherwise would be illegal.

define i1 @nonnull2(ptr %a) {
; CHECK-LABEL: @nonnull2(
; CHECK-NEXT:    [[LOAD:%.*]] = load i32, ptr [[A:%.*]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i32 [[LOAD]], 0
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    ret i1 false
;
  %load = load i32, ptr %a
  %cmp = icmp ne i32 %load, 0
  tail call void @llvm.assume(i1 %cmp)
  %rval = icmp eq i32 %load, 0
  ret i1 %rval
}

; Make sure the above canonicalization does not trigger
; if the assume is control dependent on something else

define i1 @nonnull3(ptr %a, i1 %control) {
; FIXME: we could duplicate the load and keep the assume nonnull.
; CHECK-LABEL: @nonnull3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[CONTROL:%.*]], label [[TAKEN:%.*]], label [[NOT_TAKEN:%.*]]
; CHECK:       taken:
; CHECK-NEXT:    ret i1 false
; CHECK:       not_taken:
; CHECK-NEXT:    [[LOAD:%.*]] = load ptr, ptr [[A:%.*]], align 8
; CHECK-NEXT:    [[RVAL_2:%.*]] = icmp sgt ptr [[LOAD]], null
; CHECK-NEXT:    ret i1 [[RVAL_2]]
;
entry:
  %load = load ptr, ptr %a
  %cmp = icmp ne ptr %load, null
  br i1 %control, label %taken, label %not_taken
taken:
  tail call void @llvm.assume(i1 %cmp)
  %rval = icmp eq ptr %load, null
  ret i1 %rval
not_taken:
  %rval.2 = icmp sgt ptr %load, null
  ret i1 %rval.2
}

; Make sure the above canonicalization does not trigger
; if the path from the load to the assume is potentially
; interrupted by an exception being thrown

define i1 @nonnull4(ptr %a) {
; CHECK-LABEL: @nonnull4(
; CHECK-NEXT:    [[LOAD:%.*]] = load ptr, ptr [[A:%.*]], align 8
; CHECK-NEXT:    tail call void @escape(ptr [[LOAD]])
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[LOAD]]) ]
; CHECK-NEXT:    ret i1 false
;
  %load = load ptr, ptr %a
  ;; This call may throw!
  tail call void @escape(ptr %load)
  %cmp = icmp ne ptr %load, null
  tail call void @llvm.assume(i1 %cmp)
  %rval = icmp eq ptr %load, null
  ret i1 %rval
}
define i1 @nonnull5(ptr %a) {
; CHECK-LABEL: @nonnull5(
; CHECK-NEXT:    [[LOAD:%.*]] = load ptr, ptr [[A:%.*]], align 8
; CHECK-NEXT:    tail call void @escape(ptr [[LOAD]])
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt ptr [[LOAD]], null
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    ret i1 false
;
  %load = load ptr, ptr %a
  ;; This call may throw!
  tail call void @escape(ptr %load)
  %integral = ptrtoint ptr %load to i64
  %cmp = icmp slt i64 %integral, 0
  tail call void @llvm.assume(i1 %cmp) ; %load has at least highest bit set
  %rval = icmp eq ptr %load, null
  ret i1 %rval
}

define void @redundant_nonnull1(ptr nonnull %ptr) {
; CHECK-LABEL: @redundant_nonnull1(
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "nonnull"(ptr %ptr) ]
  ret void
}

define void @redundant_nonnull2(ptr %ptr) {
; CHECK-LABEL: @redundant_nonnull2(
; CHECK-NEXT:    [[NULL_CMP_NOT:%.*]] = icmp eq ptr [[PTR:%.*]], null
; CHECK-NEXT:    br i1 [[NULL_CMP_NOT]], label [[FALSE:%.*]], label [[TRUE:%.*]]
; CHECK:       true:
; CHECK-NEXT:    ret void
; CHECK:       false:
; CHECK-NEXT:    ret void
;
  %cmp = icmp ne ptr %ptr, null
  br i1 %cmp, label %true, label %false
true:
  call void @llvm.assume(i1 true) [ "nonnull"(ptr %ptr) ]
  ret void

false:
  ret void
}

define void @redundant_nonnull3(ptr %ptr) {
; CHECK-LABEL: @redundant_nonnull3(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[PTR:%.*]]) ]
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "nonnull"(ptr %ptr) ]
  call void @llvm.assume(i1 true) [ "nonnull"(ptr %ptr) ]
  ret void
}

define void @partially_redundant(ptr %ptr, ptr %ptr2, ptr %ptr3, ptr %ptr4, ptr %ptr5) {
; CHECK-LABEL: @partially_redundant(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[PTR2:%.*]]) ]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[PTR:%.*]]) ]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[PTR4:%.*]]), "nonnull"(ptr [[PTR3:%.*]]) ]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[PTR5:%.*]]) ]
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "nonnull"(ptr %ptr), "nonnull"(ptr %ptr2) ]
  call void @llvm.assume(i1 true) [ "nonnull"(ptr %ptr), "nonnull"(ptr %ptr3) ]
  call void @llvm.assume(i1 true) [ "nonnull"(ptr %ptr4), "nonnull"(ptr %ptr5), "nonnull"(ptr %ptr3) ]
  call void @llvm.assume(i1 true) [ "nonnull"(ptr %ptr5) ]
  ret void
}

; PR35846 - https://bugs.llvm.org/show_bug.cgi?id=35846

define i32 @assumption_conflicts_with_known_bits(i32 %a, i32 %b) {
; CHECK-LABEL: @assumption_conflicts_with_known_bits(
; CHECK-NEXT:    store i1 true, ptr poison, align 1
; CHECK-NEXT:    ret i32 poison
;
  %and1 = and i32 %b, 3
  %B1 = lshr i32 %and1, %and1
  %B3 = shl nuw nsw i32 %and1, %B1
  %cmp = icmp eq i32 %B3, 1
  tail call void @llvm.assume(i1 %cmp)
  %cmp2 = icmp eq i32 %B1, %B3
  tail call void @llvm.assume(i1 %cmp2)
  ret i32 %and1
}

; PR37726 - https://bugs.llvm.org/show_bug.cgi?id=37726
; There's a loophole in eliminating a redundant assumption when
; we have conflicting assumptions. Verify that debuginfo doesn't
; get in the way of the fold.

define void @debug_interference(i8 %x) {
; CHECK-LABEL: @debug_interference(
; CHECK-NEXT:    store i1 true, ptr poison, align 1
; CHECK-NEXT:    ret void
;
  %cmp1 = icmp eq i8 %x, 0
  %cmp2 = icmp ne i8 %x, 0
  tail call void @llvm.assume(i1 %cmp1)
  tail call void @llvm.dbg.value(metadata i32 5, metadata !1, metadata !DIExpression()), !dbg !9
  tail call void @llvm.assume(i1 %cmp1)
  tail call void @llvm.dbg.value(metadata i32 5, metadata !1, metadata !DIExpression()), !dbg !9
  tail call void @llvm.assume(i1 %cmp2)
  tail call void @llvm.dbg.value(metadata i32 5, metadata !1, metadata !DIExpression()), !dbg !9
  tail call void @llvm.assume(i1 %cmp2)
  ret void
}

; This would crash.
; Does it ever make sense to peek through a bitcast of the icmp operand?

define i32 @PR40940(<4 x i8> %x) {
; CHECK-LABEL: @PR40940(
; CHECK-NEXT:    [[SHUF:%.*]] = shufflevector <4 x i8> [[X:%.*]], <4 x i8> poison, <4 x i32> <i32 1, i32 1, i32 2, i32 3>
; CHECK-NEXT:    [[T2:%.*]] = bitcast <4 x i8> [[SHUF]] to i32
; CHECK-NEXT:    [[T3:%.*]] = icmp ult i32 [[T2]], 65536
; CHECK-NEXT:    call void @llvm.assume(i1 [[T3]])
; CHECK-NEXT:    ret i32 [[T2]]
;
  %shuf = shufflevector <4 x i8> %x, <4 x i8> undef, <4 x i32> <i32 1, i32 1, i32 2, i32 3>
  %t2 = bitcast <4 x i8> %shuf to i32
  %t3 = icmp ult i32 %t2, 65536
  call void @llvm.assume(i1 %t3)
  ret i32 %t2
}

define i1 @nonnull3A(ptr %a, i1 %control) {
; CHECK-LABEL: @nonnull3A(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[CONTROL:%.*]], label [[TAKEN:%.*]], label [[NOT_TAKEN:%.*]]
; CHECK:       taken:
; CHECK-NEXT:    ret i1 true
; CHECK:       not_taken:
; CHECK-NEXT:    [[LOAD:%.*]] = load ptr, ptr [[A:%.*]], align 8
; CHECK-NEXT:    [[RVAL_2:%.*]] = icmp sgt ptr [[LOAD]], null
; CHECK-NEXT:    ret i1 [[RVAL_2]]
;
entry:
  %load = load ptr, ptr %a
  %cmp = icmp ne ptr %load, null
  br i1 %control, label %taken, label %not_taken
taken:
  call void @llvm.assume(i1 %cmp)
  ret i1 %cmp
not_taken:
  call void @llvm.assume(i1 %cmp)
  %rval.2 = icmp sgt ptr %load, null
  ret i1 %rval.2
}

define i1 @nonnull3B(ptr %a, i1 %control) {
; CHECK-LABEL: @nonnull3B(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[LOAD:%.*]] = load ptr, ptr [[A:%.*]], align 8
; CHECK-NEXT:    br i1 [[CONTROL:%.*]], label [[TAKEN:%.*]], label [[NOT_TAKEN:%.*]]
; CHECK:       taken:
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[LOAD]]) ]
; CHECK-NEXT:    ret i1 true
; CHECK:       not_taken:
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[LOAD]]) ]
; CHECK-NEXT:    ret i1 false
;
entry:
  %load = load ptr, ptr %a
  %cmp = icmp ne ptr %load, null
  br i1 %control, label %taken, label %not_taken
taken:
  call void @llvm.assume(i1 true) ["nonnull"(ptr %load)]
  ret i1 %cmp
not_taken:
  call void @llvm.assume(i1 true) ["nonnull"(ptr %load)]
  ret i1 %control
}

declare i1 @tmp1(i1)

define i1 @nonnull3C(ptr %a, i1 %control) {
; CHECK-LABEL: @nonnull3C(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[CONTROL:%.*]], label [[TAKEN:%.*]], label [[NOT_TAKEN:%.*]]
; CHECK:       taken:
; CHECK-NEXT:    [[LOAD:%.*]] = load ptr, ptr [[A:%.*]], align 8
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne ptr [[LOAD]], null
; CHECK-NEXT:    [[CMP2:%.*]] = call i1 @tmp1(i1 [[CMP]])
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret i1 [[CMP2]]
; CHECK:       not_taken:
; CHECK-NEXT:    ret i1 false
;
entry:
  %load = load ptr, ptr %a
  %cmp = icmp ne ptr %load, null
  br i1 %control, label %taken, label %not_taken
taken:
  %cmp2 = call i1 @tmp1(i1 %cmp)
  br label %exit
exit:
  ; FIXME: this shouldn't be dropped because it is still dominated by the new position of %load
  call void @llvm.assume(i1 %cmp)
  ret i1 %cmp2
not_taken:
  call void @llvm.assume(i1 %cmp)
  ret i1 %control
}

define i1 @nonnull3D(ptr %a, i1 %control) {
; CHECK-LABEL: @nonnull3D(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[CONTROL:%.*]], label [[TAKEN:%.*]], label [[NOT_TAKEN:%.*]]
; CHECK:       taken:
; CHECK-NEXT:    [[LOAD:%.*]] = load ptr, ptr [[A:%.*]], align 8
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne ptr [[LOAD]], null
; CHECK-NEXT:    [[CMP2:%.*]] = call i1 @tmp1(i1 [[CMP]])
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret i1 [[CMP2]]
; CHECK:       not_taken:
; CHECK-NEXT:    ret i1 false
;
entry:
  %load = load ptr, ptr %a
  %cmp = icmp ne ptr %load, null
  br i1 %control, label %taken, label %not_taken
taken:
  %cmp2 = call i1 @tmp1(i1 %cmp)
  br label %exit
exit:
  ret i1 %cmp2
not_taken:
  call void @llvm.assume(i1 %cmp)
  ret i1 %control
}

define void @nonnull_only_ephemeral_use(ptr %p) {
; CHECK-LABEL: @nonnull_only_ephemeral_use(
; CHECK-NEXT:    ret void
;
  %a = load ptr, ptr %p
  %cmp = icmp ne ptr %a, null
  tail call void @llvm.assume(i1 %cmp)
  ret void
}

define void @nonnull_gep_inbounds_bundle(ptr %p, i64 %i) {
; CHECK-LABEL: @nonnull_gep_inbounds_bundle(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[P:%.*]]) ]
; CHECK-NEXT:    ret void
;
  %p2 = getelementptr inbounds i8, ptr %p, i64 %i
  call void @llvm.assume(i1 true) ["nonnull"(ptr %p2)]
  ret void
}

define void @nonnull_gep_inbounds_bundle_null_is_valid(ptr %p, i64 %i) null_pointer_is_valid {
; CHECK-LABEL: @nonnull_gep_inbounds_bundle_null_is_valid(
; CHECK-NEXT:    [[P2:%.*]] = getelementptr inbounds i8, ptr [[P:%.*]], i64 [[I:%.*]]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[P2]]) ]
; CHECK-NEXT:    ret void
;
  %p2 = getelementptr inbounds i8, ptr %p, i64 %i
  call void @llvm.assume(i1 true) ["nonnull"(ptr %p2)]
  ret void
}

define void @nonnull_gep_inbounds(ptr %p, i64 %i) {
; CHECK-LABEL: @nonnull_gep_inbounds(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[P:%.*]]) ]
; CHECK-NEXT:    ret void
;
  %p2 = getelementptr inbounds i8, ptr %p, i64 %i
  %cmp = icmp ne ptr %p2, null
  call void @llvm.assume(i1 %cmp)
  ret void
}

define void @nonnull_gep_not_inbounds(ptr %p, i64 %i) {
; CHECK-LABEL: @nonnull_gep_not_inbounds(
; CHECK-NEXT:    [[P:%.*]] = getelementptr i8, ptr [[P1:%.*]], i64 [[I:%.*]]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[P]]) ]
; CHECK-NEXT:    ret void
;
  %p2 = getelementptr i8, ptr %p, i64 %i
  %cmp = icmp ne ptr %p2, null
  call void @llvm.assume(i1 %cmp)
  ret void
}

define void @always_true_assumption() {
; CHECK-LABEL: @always_true_assumption(
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true)
  ret void
}

; The alloca guarantees that the low bits of %a are zero because of alignment.
; The assume says the opposite. Make sure we don't crash.

define i64 @PR31809() {
; CHECK-LABEL: @PR31809(
; CHECK-NEXT:    store i1 true, ptr poison, align 1
; CHECK-NEXT:    ret i64 poison
;
  %a = alloca i32
  %t1 = ptrtoint ptr %a to i64
  %cond = icmp eq i64 %t1, 3
  call void @llvm.assume(i1 %cond)
  ret i64 %t1
}

; Similar to above: there's no way to know which assumption is truthful,
; so just don't crash.

define i8 @conflicting_assumptions(i8 %x){
; CHECK-LABEL: @conflicting_assumptions(
; CHECK-NEXT:    store i1 true, ptr poison, align 1
; CHECK-NEXT:    ret i8 poison
;
  %add = add i8 %x, 1
  %cond1 = icmp eq i8 %x, 3
  call void @llvm.assume(i1 %cond1)
  %cond2 = icmp eq i8 %x, 4
  call void @llvm.assume(i1 %cond2)
  ret i8 %add
}

; Another case of conflicting assumptions. This would crash because we'd
; try to set more known bits than existed in the known bits struct.

define void @PR36270(i32 %b) {
; CHECK-LABEL: @PR36270(
; CHECK-NEXT:    unreachable
;
  %B7 = xor i32 -1, 2147483647
  %and1 = and i32 %b, 3
  %B12 = lshr i32 %B7, %and1
  %C1 = icmp ult i32 %and1, %B12
  tail call void @llvm.assume(i1 %C1)
  %cmp2 = icmp eq i32 0, %B12
  tail call void @llvm.assume(i1 %cmp2)
  unreachable
}

; PR47416

define i32 @unreachable_assume(i32 %x, i32 %y) {
; CHECK-LABEL: @unreachable_assume(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP0:%.*]] = icmp sgt i32 [[X:%.*]], 1
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[Y:%.*]], 1
; CHECK-NEXT:    [[OR:%.*]] = or i1 [[CMP0]], [[CMP1]]
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[OR]])
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[X]], 1
; CHECK-NEXT:    br i1 [[CMP2]], label [[IF:%.*]], label [[EXIT:%.*]]
; CHECK:       if:
; CHECK-NEXT:    [[A:%.*]] = and i32 [[Y]], -2
; CHECK-NEXT:    [[CMP3:%.*]] = icmp ne i32 [[A]], 104
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP3]])
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    unreachable
;
entry:
  %cmp0 = icmp sgt i32 %x, 1
  %cmp1 = icmp eq i32 %y, 1
  %or = or i1 %cmp0, %cmp1
  tail call void @llvm.assume(i1 %or)
  %cmp2 = icmp eq i32 %x, 1
  br i1 %cmp2, label %if, label %exit

if:
  %a = and i32 %y, -2
  %cmp3 = icmp ne i32 %a, 104
  tail call void @llvm.assume(i1 %cmp3)
  br label %exit

exit:
  %cmp4 = icmp eq i32 %x, 2
  tail call void @llvm.assume(i1 %cmp4)
  unreachable
}

define i32 @unreachable_assume_logical(i32 %x, i32 %y) {
; CHECK-LABEL: @unreachable_assume_logical(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP0:%.*]] = icmp sgt i32 [[X:%.*]], 1
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[Y:%.*]], 1
; CHECK-NEXT:    [[OR:%.*]] = select i1 [[CMP0]], i1 true, i1 [[CMP1]]
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[OR]])
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[X]], 1
; CHECK-NEXT:    br i1 [[CMP2]], label [[IF:%.*]], label [[EXIT:%.*]]
; CHECK:       if:
; CHECK-NEXT:    [[A:%.*]] = and i32 [[Y]], -2
; CHECK-NEXT:    [[CMP3:%.*]] = icmp ne i32 [[A]], 104
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP3]])
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    unreachable
;
entry:
  %cmp0 = icmp sgt i32 %x, 1
  %cmp1 = icmp eq i32 %y, 1
  %or = select i1 %cmp0, i1 true, i1 %cmp1
  tail call void @llvm.assume(i1 %or)
  %cmp2 = icmp eq i32 %x, 1
  br i1 %cmp2, label %if, label %exit

if:
  %a = and i32 %y, -2
  %cmp3 = icmp ne i32 %a, 104
  tail call void @llvm.assume(i1 %cmp3)
  br label %exit

exit:
  %cmp4 = icmp eq i32 %x, 2
  tail call void @llvm.assume(i1 %cmp4)
  unreachable
}

define i32 @unreachable_assumes_and_store(i32 %x, i32 %y, ptr %p) {
; CHECK-LABEL: @unreachable_assumes_and_store(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP0:%.*]] = icmp sgt i32 [[X:%.*]], 1
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[Y:%.*]], 1
; CHECK-NEXT:    [[OR:%.*]] = or i1 [[CMP0]], [[CMP1]]
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[OR]])
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[X]], 1
; CHECK-NEXT:    br i1 [[CMP2]], label [[IF:%.*]], label [[EXIT:%.*]]
; CHECK:       if:
; CHECK-NEXT:    [[A:%.*]] = and i32 [[Y]], -2
; CHECK-NEXT:    [[CMP3:%.*]] = icmp ne i32 [[A]], 104
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP3]])
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    unreachable
;
entry:
  %cmp0 = icmp sgt i32 %x, 1
  %cmp1 = icmp eq i32 %y, 1
  %or = or i1 %cmp0, %cmp1
  tail call void @llvm.assume(i1 %or)
  %cmp2 = icmp eq i32 %x, 1
  br i1 %cmp2, label %if, label %exit

if:
  %a = and i32 %y, -2
  %cmp3 = icmp ne i32 %a, 104
  tail call void @llvm.assume(i1 %cmp3)
  br label %exit

exit:
  %cmp4 = icmp eq i32 %x, 2
  tail call void @llvm.assume(i1 %cmp4)
  %cmp5 = icmp ugt i32 %y, 42
  tail call void @llvm.assume(i1 %cmp5)
  store i32 %x, ptr %p
  unreachable
}

define i32 @unreachable_assumes_and_store_logical(i32 %x, i32 %y, ptr %p) {
; CHECK-LABEL: @unreachable_assumes_and_store_logical(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP0:%.*]] = icmp sgt i32 [[X:%.*]], 1
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[Y:%.*]], 1
; CHECK-NEXT:    [[OR:%.*]] = select i1 [[CMP0]], i1 true, i1 [[CMP1]]
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[OR]])
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[X]], 1
; CHECK-NEXT:    br i1 [[CMP2]], label [[IF:%.*]], label [[EXIT:%.*]]
; CHECK:       if:
; CHECK-NEXT:    [[A:%.*]] = and i32 [[Y]], -2
; CHECK-NEXT:    [[CMP3:%.*]] = icmp ne i32 [[A]], 104
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP3]])
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    unreachable
;
entry:
  %cmp0 = icmp sgt i32 %x, 1
  %cmp1 = icmp eq i32 %y, 1
  %or = select i1 %cmp0, i1 true, i1 %cmp1
  tail call void @llvm.assume(i1 %or)
  %cmp2 = icmp eq i32 %x, 1
  br i1 %cmp2, label %if, label %exit

if:
  %a = and i32 %y, -2
  %cmp3 = icmp ne i32 %a, 104
  tail call void @llvm.assume(i1 %cmp3)
  br label %exit

exit:
  %cmp4 = icmp eq i32 %x, 2
  tail call void @llvm.assume(i1 %cmp4)
  %cmp5 = icmp ugt i32 %y, 42
  tail call void @llvm.assume(i1 %cmp5)
  store i32 %x, ptr %p
  unreachable
}

define void @canonicalize_assume(ptr %0) {
; CHECK-LABEL: @canonicalize_assume(
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP0:%.*]], i64 8
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[TMP2]], i64 16) ]
; CHECK-NEXT:    ret void
;
  %2 = getelementptr inbounds i32, ptr %0, i64 2
  call void @llvm.assume(i1 true) [ "align"(ptr %2, i64 16) ]
  ret void
}

define void @assume_makes_and_known_assume_on_arg(ptr %p, i32 %x) {
; CHECK-LABEL: @assume_makes_and_known_assume_on_arg(
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[X:%.*]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[AND]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    store i32 0, ptr [[P:%.*]], align 4
; CHECK-NEXT:    ret void
;
  %and = and i32 %x, 1
  %cmp = icmp eq i32 %and, 0
  call void @llvm.assume(i1 %cmp)
  %and2 = and i32 %x, 1
  store i32 %and2, ptr %p
  ret void
}

define void @assume_makes_and_known_assume_on_mul(ptr %p, i32 %a, i32 %b) {
; CHECK-LABEL: @assume_makes_and_known_assume_on_mul(
; CHECK-NEXT:    [[X:%.*]] = mul i32 [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[X]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[AND]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    store i32 0, ptr [[P:%.*]], align 4
; CHECK-NEXT:    ret void
;
  %x = mul i32 %a, %b
  %and = and i32 %x, 1
  %cmp = icmp eq i32 %and, 0
  call void @llvm.assume(i1 %cmp)
  %and2 = and i32 %x, 1
  store i32 %and2, ptr %p
  ret void
}

define void @assume_makes_and_known_assume_on_bitwise(ptr %p, i32 %a, i32 %b) {
; CHECK-LABEL: @assume_makes_and_known_assume_on_bitwise(
; CHECK-NEXT:    [[X:%.*]] = or i32 [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[X]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[AND]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    store i32 0, ptr [[P:%.*]], align 4
; CHECK-NEXT:    ret void
;
  %x = or i32 %a, %b
  %and = and i32 %x, 1
  %cmp = icmp eq i32 %and, 0
  call void @llvm.assume(i1 %cmp)
  %and2 = and i32 %x, 1
  store i32 %and2, ptr %p
  ret void
}

define i32 @range_16_31_top28(i32 %x) {
; CHECK-LABEL: @range_16_31_top28(
; CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[X:%.*]], -16
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP1]], 16
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    ret i32 16
;
  %add = add i32 %x, -16
  %cmp = icmp ult i32 %add, 16
  call void @llvm.assume(i1 %cmp)
  %res = and i32 %x, u0xfffffff0
  ret i32 %res
}

define i32 @range_16_31_top29(i32 %x) {
; CHECK-LABEL: @range_16_31_top29(
; CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[X:%.*]], -16
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP1]], 16
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[RES:%.*]] = and i32 [[X]], 24
; CHECK-NEXT:    ret i32 [[RES]]
;
  %add = add i32 %x, -16
  %cmp = icmp ult i32 %add, 16
  call void @llvm.assume(i1 %cmp)
  %res = and i32 %x, u0xfffffff8
  ret i32 %res
}

define i32 @range_16_30_top28(i32 %x) {
; CHECK-LABEL: @range_16_30_top28(
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[X:%.*]], -16
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[ADD]], 15
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    ret i32 16
;
  %add = add i32 %x, -16
  %cmp = icmp ult i32 %add, 15
  call void @llvm.assume(i1 %cmp)
  %res = and i32 %x, u0xfffffff0
  ret i32 %res
}

define i32 @range_16_32_top28(i32 %x) {
; CHECK-LABEL: @range_16_32_top28(
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[X:%.*]], -16
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[ADD]], 17
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[RES:%.*]] = and i32 [[X]], 48
; CHECK-NEXT:    ret i32 [[RES]]
;
  %add = add i32 %x, -16
  %cmp = icmp ult i32 %add, 17
  call void @llvm.assume(i1 %cmp)
  %res = and i32 %x, u0xfffffff0
  ret i32 %res
}

define i32 @range_16_32_top27(i32 %x) {
; CHECK-LABEL: @range_16_32_top27(
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[X:%.*]], -16
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[ADD]], 17
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[RES:%.*]] = and i32 [[X]], 32
; CHECK-NEXT:    ret i32 [[RES]]
;
  %add = add i32 %x, -16
  %cmp = icmp ult i32 %add, 17
  call void @llvm.assume(i1 %cmp)
  %res = and i32 %x, u0xffffffe0
  ret i32 %res
}

define i32 @range_16_32_top26(i32 %x) {
; CHECK-LABEL: @range_16_32_top26(
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[X:%.*]], -16
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[ADD]], 17
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    ret i32 0
;
  %add = add i32 %x, -16
  %cmp = icmp ult i32 %add, 17
  call void @llvm.assume(i1 %cmp)
  %res = and i32 %x, u0xffffffc0
  ret i32 %res
}

define i32 @range_15_31_top28(i32 %x) {
; CHECK-LABEL: @range_15_31_top28(
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[X:%.*]], -15
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[ADD]], 16
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[RES:%.*]] = and i32 [[X]], 16
; CHECK-NEXT:    ret i32 [[RES]]
;
  %add = add i32 %x, -15
  %cmp = icmp ult i32 %add, 16
  call void @llvm.assume(i1 %cmp)
  %res = and i32 %x, u0xfffffff0
  ret i32 %res
}

define i32 @range_15_31_top27(i32 %x) {
; CHECK-LABEL: @range_15_31_top27(
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[X:%.*]], -15
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[ADD]], 16
; CHECK-NEXT:    call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    ret i32 0
;
  %add = add i32 %x, -15
  %cmp = icmp ult i32 %add, 16
  call void @llvm.assume(i1 %cmp)
  %res = and i32 %x, u0xffffffe0
  ret i32 %res
}

define i1 @not_cond_use(i8 %x) {
; CHECK-LABEL: @not_cond_use(
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i8 [[X:%.*]], 0
; CHECK-NEXT:    tail call void @use(i1 [[CMP]])
; CHECK-NEXT:    [[NOT:%.*]] = xor i1 [[CMP]], true
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[NOT]])
; CHECK-NEXT:    [[RVAL:%.*]] = icmp eq i8 [[X]], 0
; CHECK-NEXT:    ret i1 [[RVAL]]
;
  %cmp = icmp eq i8 %x, 0
  tail call void @use(i1 %cmp)
  %not = xor i1 %cmp, true
  tail call void @llvm.assume(i1 %not)
  %rval = icmp eq i8 %x, 0
  ret i1 %rval
}

define i1 @assume_trunc_nuw_eq_one(i8 %x) {
; CHECK-LABEL: @assume_trunc_nuw_eq_one(
; CHECK-NEXT:    [[A:%.*]] = trunc nuw i8 [[X:%.*]] to i1
; CHECK-NEXT:    call void @llvm.assume(i1 [[A]])
; CHECK-NEXT:    ret i1 true
;
  %a = trunc nuw i8 %x to i1
  call void @llvm.assume(i1 %a)
  %q = icmp eq i8 %x, 1
  ret i1 %q
}

define i1 @neg_assume_trunc_eq_one(i8 %x) {
; CHECK-LABEL: @neg_assume_trunc_eq_one(
; CHECK-NEXT:    [[A:%.*]] = trunc i8 [[X:%.*]] to i1
; CHECK-NEXT:    call void @llvm.assume(i1 [[A]])
; CHECK-NEXT:    [[Q:%.*]] = icmp eq i8 [[X]], 1
; CHECK-NEXT:    ret i1 [[Q]]
;
  %a = trunc i8 %x to i1
  call void @llvm.assume(i1 %a)
  %q = icmp eq i8 %x, 1
  ret i1 %q
}

define void @assume_dereferenceable_0(ptr %ptr) {
; CHECK-LABEL: @assume_dereferenceable_0(
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %ptr, i64 0) ]
  ret void
}

define void @assume_dereferenceable_1(ptr %ptr) {
; CHECK-LABEL: @assume_dereferenceable_1(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "dereferenceable"(ptr [[PTR:%.*]], i64 1) ]
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %ptr, i64 1) ]
  ret void
}

define void @assume_dereferenceable_variable(ptr %ptr, i64 %count) {
; CHECK-LABEL: @assume_dereferenceable_variable(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "dereferenceable"(ptr [[PTR:%.*]], i64 [[COUNT:%.*]]) ]
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %ptr, i64 %count) ]
  ret void
}

define void @assume_dereferenceable_variable_on_nullptr(i64 %count) {
; CHECK-LABEL: @assume_dereferenceable_variable_on_nullptr(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "dereferenceable"(ptr null, i64 [[COUNT:%.*]]) ]
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr null, i64 %count) ]
  ret void
}

define void @redundant_assume_dereferenceable_2(ptr dereferenceable(2) %ptr) {
; CHECK-LABEL: @redundant_assume_dereferenceable_2(
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %ptr, i64 2) ]
  ret void
}
define void @redundant_assume_dereferenceable_2_via_assume(ptr %ptr) {
; CHECK-LABEL: @redundant_assume_dereferenceable_2_via_assume(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "dereferenceable"(ptr [[PTR:%.*]], i64 2) ]
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %ptr, i64 2) ]
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %ptr, i64 2) ]
  ret void
}

define void @not_redundant_assume_dereferenceable_2(ptr dereferenceable(1) %ptr) {
; CHECK-LABEL: @not_redundant_assume_dereferenceable_2(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "dereferenceable"(ptr [[PTR:%.*]], i64 2) ]
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %ptr, i64 2) ]
  ret void
}

define void @assume_noundef(i32 %val) {
; CHECK-LABEL: @assume_noundef(
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "noundef"(i32 [[VAL:%.*]]) ]
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "noundef"(i32 %val) ]
  ret void
}

define void @redundant_assume_noundef(i32 noundef %val) {
; CHECK-LABEL: @redundant_assume_noundef(
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "noundef"(i32 %val) ]
  ret void
}

define i32 @assume_noundef_on_load(ptr %ptr) {
; CHECK-LABEL: @assume_noundef_on_load(
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[PTR:%.*]], align 4, !noundef [[META6]]
; CHECK-NEXT:    ret i32 [[VAL]]
;
  %val = load i32, ptr %ptr
  call void @llvm.assume(i1 true) [ "noundef"(i32 %val) ]
  ret i32 %val
}

define i32 @assume_noundef_on_load_after_call(ptr %ptr) {
; CHECK-LABEL: @assume_noundef_on_load_after_call(
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[PTR:%.*]], align 4
; CHECK-NEXT:    call void @block()
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "noundef"(i32 [[VAL]]) ]
; CHECK-NEXT:    ret i32 [[VAL]]
;
  %val = load i32, ptr %ptr
  call void @block()
  call void @llvm.assume(i1 true) [ "noundef"(i32 %val) ]
  ret i32 %val
}

declare void @use(i1)
declare void @block()
declare void @llvm.dbg.value(metadata, metadata, metadata)

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!5, !6, !7, !8}

!0 = distinct !DICompileUnit(language: DW_LANG_C, file: !3, producer: "Me", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: null, retainedTypes: null, imports: null)
!1 = !DILocalVariable(name: "", arg: 1, scope: !2, file: null, line: 1, type: null)
!2 = distinct !DISubprogram(name: "debug", linkageName: "debug", scope: null, file: null, line: 0, type: !10, isLocal: false, isDefinition: true, scopeLine: 1, flags: DIFlagPrototyped, isOptimized: true, unit: !0)
!3 = !DIFile(filename: "consecutive-fences.ll", directory: "")
!5 = !{i32 2, !"Dwarf Version", i32 4}
!6 = !{i32 2, !"Debug Info Version", i32 3}
!7 = !{i32 1, !"wchar_size", i32 4}
!8 = !{i32 7, !"PIC Level", i32 2}
!9 = !DILocation(line: 0, column: 0, scope: !2)


attributes #0 = { nounwind uwtable }
attributes #1 = { nounwind }
!10 = !DISubroutineType(types: !11)
!11 = !{null}
