; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

target datalayout = "p:128:128"

define void @align_on_i128_offset(ptr %p) {
; CHECK-LABEL: define void @align_on_i128_offset(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[P]], i128 18446744073709551616
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[GEP]], i64 16) ]
; CHECK-NEXT:    ret void
;
  %gep = getelementptr i8, ptr %p, i128 18446744073709551616
  call void @llvm.assume(i1 true) ["align"(ptr %gep, i64 16)]
  ret void
}

define void @align_on_i128_offset_unaligned(ptr %p) {
; CHECK-LABEL: define void @align_on_i128_offset_unaligned(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[P]], i128 18446744073709551615
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[GEP]], i64 16) ]
; CHECK-NEXT:    ret void
;
  %gep = getelementptr i8, ptr %p, i128 18446744073709551615
  call void @llvm.assume(i1 true) ["align"(ptr %gep, i64 16)]
  ret void
}
