; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare void @llvm.assume(i1) #0

; PR199095: with `assume %x sge 0` the sign bit of %x is known-zero, so
; SimplifyDemandedBits would shrink `and %x, -4` to
; `and %x, 0x7FFFFFFFFFFFFFFC`, replacing a sign-extendable small immediate
; with one that requires an i64 movabs on x86. The fix in
; ShrinkDemandedConstant must keep the original `-4` mask.

define i64 @pr199095_align4(i64 %x) {
; CHECK-LABEL: @pr199095_align4(
; CHECK-NEXT:    [[NN:%.*]] = icmp sgt i64 [[X:%.*]], -1
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[NN]])
; CHECK-NEXT:    [[R:%.*]] = and i64 [[X]], -4
; CHECK-NEXT:    ret i64 [[R]]
;
  %nn = icmp sge i64 %x, 0
  tail call void @llvm.assume(i1 %nn)
  %r = and i64 %x, -4
  ret i64 %r
}

define i64 @pr199095_align16(i64 %x) {
; CHECK-LABEL: @pr199095_align16(
; CHECK-NEXT:    [[NN:%.*]] = icmp sgt i64 [[X:%.*]], -1
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[NN]])
; CHECK-NEXT:    [[R:%.*]] = and i64 [[X]], -16
; CHECK-NEXT:    ret i64 [[R]]
;
  %nn = icmp sge i64 %x, 0
  tail call void @llvm.assume(i1 %nn)
  %r = and i64 %x, -16
  ret i64 %r
}

define <2 x i64> @pr199095_vector(<2 x i64> %x) {
; CHECK-LABEL: @pr199095_vector(
; CHECK-NEXT:    [[NN:%.*]] = icmp sgt <2 x i64> [[X:%.*]], splat (i64 -1)
; CHECK-NEXT:    [[NN0:%.*]] = extractelement <2 x i1> [[NN]], i64 0
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[NN0]])
; CHECK-NEXT:    [[NN1:%.*]] = extractelement <2 x i1> [[NN]], i64 1
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[NN1]])
; CHECK-NEXT:    [[R:%.*]] = and <2 x i64> [[X]], splat (i64 -4)
; CHECK-NEXT:    ret <2 x i64> [[R]]
;
  %nn = icmp sge <2 x i64> %x, zeroinitializer
  %nn0 = extractelement <2 x i1> %nn, i64 0
  tail call void @llvm.assume(i1 %nn0)
  %nn1 = extractelement <2 x i1> %nn, i64 1
  tail call void @llvm.assume(i1 %nn1)
  %r = and <2 x i64> %x, splat (i64 -4)
  ret <2 x i64> %r
}

attributes #0 = { nounwind }
