; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=instcombine -S %s | FileCheck %s

; Regression case: atomicrmw sub with variable is left unchanged
define i64 @fn_sub(ptr %a, i64 %n) {
; CHECK-LABEL: define i64 @fn_sub(
; CHECK-SAME: ptr [[A:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = atomicrmw sub ptr [[A]], i64 [[N]] monotonic, align 8
; CHECK-NEXT:    ret i64 [[TMP1]]
;
  %1 = atomicrmw sub ptr %a, i64 %n monotonic
  ret i64 %1
}

; Canonicalize atomicrmw add(ptr, neg(n)) -> atomicrmw sub(ptr, n)
define i64 @fn_add(ptr %a, i64 %n) {
; CHECK-LABEL: define i64 @fn_add(
; CHECK-SAME: ptr [[A:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = atomicrmw sub ptr [[A]], i64 [[N]] monotonic, align 8
; CHECK-NEXT:    ret i64 [[TMP1]]
;
  %sub = sub i64 0, %n
  %1 = atomicrmw add ptr %a, i64 %sub monotonic
  ret i64 %1
}

; Canonicalize atomicrmw add(ptr, neg(n)) -> atomicrmw sub(ptr, n)
; even when the negation is nsw
define i64 @fn_adds(ptr %a, i64 %n) {
; CHECK-LABEL: define i64 @fn_adds(
; CHECK-SAME: ptr [[A:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:    [[OLD:%.*]] = atomicrmw sub ptr [[A]], i64 [[N]] monotonic, align 8
; CHECK-NEXT:    ret i64 [[OLD]]
;
  %neg = sub nsw i64 0, %n
  %old = atomicrmw add ptr %a, i64 %neg monotonic
  ret i64 %old
}

; Canonicalize atomicrmw sub(ptr, neg(n)) -> atomicrmw add(ptr, n)
define void @fn_sub_neg(ptr %a, i64 %n) {
; CHECK-LABEL: define void @fn_sub_neg(
; CHECK-SAME: ptr [[A:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = atomicrmw add ptr [[A]], i64 [[N]] monotonic, align 8
; CHECK-NEXT:    ret void
;
  %neg = sub i64 0, %n
  atomicrmw sub ptr %a, i64 %neg monotonic
  ret void
}

; Don't canonicalize if the negated value has multiple uses -- that would add an extra instruction.
define void @fn_add_1_with_use(ptr %a, i64 %n) {
; CHECK-LABEL: define void @fn_add_1_with_use(
; CHECK-SAME: ptr [[A:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:    [[ADD:%.*]] = add i64 [[N]], 1
; CHECK-NEXT:    call void @use(i64 [[ADD]])
; CHECK-NEXT:    [[TMP1:%.*]] = atomicrmw add ptr [[A]], i64 [[ADD]] monotonic, align 8
; CHECK-NEXT:    ret void
;
  %add = add i64 %n, 1
  call void @use(i64 %add)
  atomicrmw add ptr %a, i64 %add monotonic
  ret void
}

declare void @use(i64)
