; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; splat-vec to mul is related to target arch.
; E.g., i256 mul is not efficient in x86_64.
target triple = "x86_64-pc-linux-gnu"

define i32 @issue185694_i1(i64 %arg0, i64 %arg1) {
; CHECK-LABEL: define i32 @issue185694_i1(
; CHECK-SAME: i64 [[ARG0:%.*]], i64 [[ARG1:%.*]]) {
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[ARG1]], [[ARG0]]
; CHECK-NEXT:    [[EXT:%.*]] = select i1 [[CMP]], i32 15, i32 0
; CHECK-NEXT:    ret i32 [[EXT]]
;
  %cmp = icmp eq i64 %arg1, %arg0
  %ins = insertelement <4 x i1> poison, i1 %cmp, i64 0
  %splat = shufflevector <4 x i1> %ins, <4 x i1> poison, <4 x i32> zeroinitializer
  %bc = bitcast <4 x i1> %splat to i4
  %ext = zext i4 %bc to i32
  ret i32 %ext
}

define i32 @splat_i8_nonzero_lane(i8 %x) {
; CHECK-LABEL: define i32 @splat_i8_nonzero_lane(
; CHECK-SAME: i8 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = zext i8 [[X]] to i32
; CHECK-NEXT:    [[MUL:%.*]] = mul nuw i32 [[TMP1]], 16843009
; CHECK-NEXT:    ret i32 [[MUL]]
;
  %ins = insertelement <4 x i8> poison, i8 %x, i64 2
  %splat = shufflevector <4 x i8> %ins, <4 x i8> poison, <4 x i32> <i32 2, i32 2, i32 2, i32 2>
  %bc = bitcast <4 x i8> %splat to i32
  ret i32 %bc
}

define i64 @zext_splat_i8_to_i64(i8 %x) {
; CHECK-LABEL: define i64 @zext_splat_i8_to_i64(
; CHECK-SAME: i8 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = zext i8 [[X]] to i64
; CHECK-NEXT:    [[EXT:%.*]] = mul nuw nsw i64 [[TMP1]], 257
; CHECK-NEXT:    ret i64 [[EXT]]
;
  %ins = insertelement <2 x i8> poison, i8 %x, i64 0
  %splat = shufflevector <2 x i8> %ins, <2 x i8> poison, <2 x i32> zeroinitializer
  %bc = bitcast <2 x i8> %splat to i16
  %ext = zext i16 %bc to i64
  ret i64 %ext
}

define i64 @splat_float(float %x) {
; CHECK-LABEL: define i64 @splat_float(
; CHECK-SAME: float [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <2 x float> poison, float [[X]], i64 0
; CHECK-NEXT:    [[SPLAT:%.*]] = shufflevector <2 x float> [[TMP1]], <2 x float> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[BC:%.*]] = bitcast <2 x float> [[SPLAT]] to i64
; CHECK-NEXT:    ret i64 [[BC]]
;
  %ins = insertelement <2 x float> poison, float %x, i64 1
  %splat = shufflevector <2 x float> %ins, <2 x float> poison, <2 x i32> <i32 1, i32 1>
  %bc = bitcast <2 x float> %splat to i64
  ret i64 %bc
}

define i128 @splat_float_to_i128(float %x) {
; CHECK-LABEL: define i128 @splat_float_to_i128(
; CHECK-SAME: float [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <4 x float> poison, float [[X]], i64 0
; CHECK-NEXT:    [[SPLAT:%.*]] = shufflevector <4 x float> [[TMP1]], <4 x float> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[BC:%.*]] = bitcast <4 x float> [[SPLAT]] to i128
; CHECK-NEXT:    ret i128 [[BC]]
;
  %ins = insertelement <4 x float> poison, float %x, i64 3
  %splat = shufflevector <4 x float> %ins, <4 x float> poison,
  <4 x i32> <i32 3, i32 3, i32 3, i32 3>
  %bc = bitcast <4 x float> %splat to i128
  ret i128 %bc
}

define i128 @splat_i32_to_i128(i32 %x) {
; CHECK-LABEL: define i128 @splat_i32_to_i128(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <4 x i32> poison, i32 [[X]], i64 0
; CHECK-NEXT:    [[SPLAT:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[MUL:%.*]] = bitcast <4 x i32> [[SPLAT]] to i128
; CHECK-NEXT:    ret i128 [[MUL]]
;
  %ins = insertelement <4 x i32> poison, i32 %x, i64 1
  %splat = shufflevector <4 x i32> %ins, <4 x i32> poison,
  <4 x i32> <i32 1, i32 1, i32 1, i32 1>
  %bc = bitcast <4 x i32> %splat to i128
  ret i128 %bc
}

define i32 @nonsplat_shuffle(<4 x i8> %x) {
; CHECK-LABEL: define i32 @nonsplat_shuffle(
; CHECK-SAME: <4 x i8> [[X:%.*]]) {
; CHECK-NEXT:    [[SHUF:%.*]] = shufflevector <4 x i8> [[X]], <4 x i8> poison, <4 x i32> <i32 0, i32 1, i32 0, i32 1>
; CHECK-NEXT:    [[BC:%.*]] = bitcast <4 x i8> [[SHUF]] to i32
; CHECK-NEXT:    ret i32 [[BC]]
;
  %shuf = shufflevector <4 x i8> %x, <4 x i8> poison, <4 x i32> <i32 0, i32 1, i32 0, i32 1>
  %bc = bitcast <4 x i8> %shuf to i32
  ret i32 %bc
}
