; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=instcombine -S < %s | FileCheck %s

define i32 @sadd_min_max_assoc(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @sadd_min_max_assoc(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:    [[LHS:%.*]] = add i32 [[X]], [[Y]]
; CHECK-NEXT:    [[TMP5:%.*]] = add i32 [[Z]], [[LHS]]
; CHECK-NEXT:    ret i32 [[TMP5]]
;
  %min = call i32 @llvm.smin.i32(i32 %x, i32 %y)
  %lhs = add i32 %z, %min
  %max = call i32 @llvm.smax.i32(i32 %x, i32 %y)
  %ret = add i32 %lhs, %max
  ret i32 %ret
}

define i32 @sadd_min_max_assoc2(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @sadd_min_max_assoc2(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:    [[RHS:%.*]] = add i32 [[X]], [[Y]]
; CHECK-NEXT:    [[RET:%.*]] = add i32 [[RHS]], [[Z]]
; CHECK-NEXT:    ret i32 [[RET]]
;
  %min = call i32 @llvm.smin.i32(i32 %x, i32 %y)
  %rhs = add i32 %min, %z
  %max = call i32 @llvm.smax.i32(i32 %x, i32 %y)
  %ret = add i32 %max, %rhs
  ret i32 %ret
}

define i32 @sadd_min_max_assoc_comm(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @sadd_min_max_assoc_comm(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:    [[RHS:%.*]] = add i32 [[X]], [[Y]]
; CHECK-NEXT:    [[RET:%.*]] = add i32 [[Z]], [[RHS]]
; CHECK-NEXT:    ret i32 [[RET]]
;
  %min = call i32 @llvm.smin.i32(i32 %x, i32 %y)
  %rhs = add i32 %z, %min
  %max = call i32 @llvm.smax.i32(i32 %x, i32 %y)
  %ret = add i32 %max, %rhs
  ret i32 %ret
}

define i32 @or_min_max_assoc(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @or_min_max_assoc(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:    [[LHS:%.*]] = or i32 [[X]], [[Y]]
; CHECK-NEXT:    [[TMP5:%.*]] = or i32 [[Z]], [[LHS]]
; CHECK-NEXT:    ret i32 [[TMP5]]
;
  %min = call i32 @llvm.smin.i32(i32 %x, i32 %y)
  %lhs = or i32 %z, %min
  %max = call i32 @llvm.smax.i32(i32 %x, i32 %y)
  %ret = or i32 %lhs, %max
  ret i32 %ret
}

define i32 @or_disjoint_min_max_assoc(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @or_disjoint_min_max_assoc(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:    [[LHS:%.*]] = or i32 [[X]], [[Y]]
; CHECK-NEXT:    [[TMP5:%.*]] = or i32 [[Z]], [[LHS]]
; CHECK-NEXT:    ret i32 [[TMP5]]
;
  %min = call i32 @llvm.smin.i32(i32 %x, i32 %y)
  %lhs = or disjoint i32 %z, %min
  %max = call i32 @llvm.smax.i32(i32 %x, i32 %y)
  %ret = or i32 %lhs, %max
  ret i32 %ret
}

define i32 @or_outer_disjoint_min_max_assoc(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @or_outer_disjoint_min_max_assoc(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:    [[LHS:%.*]] = or i32 [[X]], [[Y]]
; CHECK-NEXT:    [[RET:%.*]] = or i32 [[Z]], [[LHS]]
; CHECK-NEXT:    ret i32 [[RET]]
;
  %min = call i32 @llvm.smin.i32(i32 %x, i32 %y)
  %lhs = or i32 %z, %min
  %max = call i32 @llvm.smax.i32(i32 %x, i32 %y)
  %ret = or disjoint i32 %lhs, %max
  ret i32 %ret
}

define i32 @smul_min_max_assoc(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @smul_min_max_assoc(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:    [[LHS:%.*]] = mul i32 [[X]], [[Y]]
; CHECK-NEXT:    [[TMP5:%.*]] = mul i32 [[Z]], [[LHS]]
; CHECK-NEXT:    ret i32 [[TMP5]]
;
  %min = call i32 @llvm.smin.i32(i32 %x, i32 %y)
  %lhs = mul i32 %z, %min
  %max = call i32 @llvm.smax.i32(i32 %x, i32 %y)
  %ret = mul i32 %lhs, %max
  ret i32 %ret
}

define i32 @smul_min_max_assoc_comm(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @smul_min_max_assoc_comm(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:    [[LHS:%.*]] = mul i32 [[X]], [[Y]]
; CHECK-NEXT:    [[RET:%.*]] = mul i32 [[LHS]], [[Z]]
; CHECK-NEXT:    ret i32 [[RET]]
;
  %min = call i32 @llvm.smin.i32(i32 %x, i32 %y)
  %lhs = mul i32 %min, %z
  %max = call i32 @llvm.smax.i32(i32 %x, i32 %y)
  %ret = mul i32 %lhs, %max
  ret i32 %ret
}

define i32 @uadd_min_max_assoc(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @uadd_min_max_assoc(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:    [[LHS:%.*]] = add i32 [[X]], [[Y]]
; CHECK-NEXT:    [[TMP5:%.*]] = add i32 [[Z]], [[LHS]]
; CHECK-NEXT:    ret i32 [[TMP5]]
;
  %min = call i32 @llvm.umin.i32(i32 %x, i32 %y)
  %lhs = add i32 %z, %min
  %max = call i32 @llvm.umax.i32(i32 %x, i32 %y)
  %ret = add i32 %lhs, %max
  ret i32 %ret
}

define i32 @umul_min_max_assoc(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @umul_min_max_assoc(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:    [[LHS:%.*]] = mul i32 [[X]], [[Y]]
; CHECK-NEXT:    [[TMP5:%.*]] = mul i32 [[Z]], [[LHS]]
; CHECK-NEXT:    ret i32 [[TMP5]]
;
  %min = call i32 @llvm.umin.i32(i32 %x, i32 %y)
  %lhs = mul i32 %z, %min
  %max = call i32 @llvm.umax.i32(i32 %x, i32 %y)
  %ret = mul i32 %lhs, %max
  ret i32 %ret
}

define i32 @add_min_max_assoc_wrong(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @add_min_max_assoc_wrong(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:    [[MIN:%.*]] = call i32 @llvm.smin.i32(i32 [[X]], i32 [[Y]])
; CHECK-NEXT:    [[TMP5:%.*]] = add i32 [[Z]], [[MIN]]
; CHECK-NEXT:    [[TMP6:%.*]] = call i32 @llvm.umax.i32(i32 [[X]], i32 [[Y]])
; CHECK-NEXT:    [[TMP7:%.*]] = add i32 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    ret i32 [[TMP7]]
;
  %min = call i32 @llvm.smin.i32(i32 %x, i32 %y)
  %lhs = add i32 %z, %min
  %max = call i32 @llvm.umax.i32(i32 %x, i32 %y)
  %ret = add i32 %lhs, %max
  ret i32 %ret
}

define i32 @add_min_max_assoc_wrong2(i32 %x, i32 %y, i32 %z, ptr %p) {
; CHECK-LABEL: define i32 @add_min_max_assoc_wrong2(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:    [[MIN:%.*]] = call i32 @llvm.smin.i32(i32 [[X]], i32 [[Y]])
; CHECK-NEXT:    [[TMP5:%.*]] = add i32 [[Z]], [[MIN]]
; CHECK-NEXT:    [[TMP6:%.*]] = call i32 @llvm.smax.i32(i32 [[X]], i32 [[Y]])
; CHECK-NEXT:    [[TMP7:%.*]] = add i32 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[P]], align 4
; CHECK-NEXT:    ret i32 [[TMP7]]
;
  %min = call i32 @llvm.smin.i32(i32 %x, i32 %y)
  %lhs = add i32 %z, %min
  %max = call i32 @llvm.smax.i32(i32 %x, i32 %y)
  %ret = add i32 %lhs, %max
  store i32 %lhs, ptr %p
  ret i32 %ret
}

define i32 @mul_min_max_assoc_wrong(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @mul_min_max_assoc_wrong(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:    [[MIN:%.*]] = call i32 @llvm.smin.i32(i32 [[X]], i32 [[Y]])
; CHECK-NEXT:    [[TMP5:%.*]] = mul i32 [[Z]], [[MIN]]
; CHECK-NEXT:    [[TMP6:%.*]] = call i32 @llvm.umax.i32(i32 [[X]], i32 [[Y]])
; CHECK-NEXT:    [[TMP7:%.*]] = add i32 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    ret i32 [[TMP7]]
;
  %min = call i32 @llvm.smin.i32(i32 %x, i32 %y)
  %lhs = mul i32 %z, %min
  %max = call i32 @llvm.umax.i32(i32 %x, i32 %y)
  %ret = add i32 %lhs, %max
  ret i32 %ret
}

define i32 @sadd_nsw_min_max_assoc(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @sadd_nsw_min_max_assoc(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:    [[LHS:%.*]] = add i32 [[Y]], [[X]]
; CHECK-NEXT:    [[RET:%.*]] = add i32 [[Z]], [[LHS]]
; CHECK-NEXT:    ret i32 [[RET]]
;
  %min = call i32 @llvm.smin.i32(i32 %y, i32 %x)
  %lhs = add nsw i32 %z, %min
  %max = call i32 @llvm.smax.i32(i32 %x, i32 %y)
  %ret = add i32 %lhs, %max
  ret i32 %ret
}

define i32 @sadd_nuw_min_max_assoc(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @sadd_nuw_min_max_assoc(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:    [[LHS:%.*]] = add i32 [[Y]], [[X]]
; CHECK-NEXT:    [[RET:%.*]] = add i32 [[Z]], [[LHS]]
; CHECK-NEXT:    ret i32 [[RET]]
;
  %min = call i32 @llvm.smin.i32(i32 %y, i32 %x)
  %lhs = add nuw i32 %z, %min
  %max = call i32 @llvm.smax.i32(i32 %x, i32 %y)
  %ret = add i32 %lhs, %max
  ret i32 %ret
}

define i32 @sadd_inner_metadata_outer_annotations(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @sadd_inner_metadata_outer_annotations(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:    [[LHS:%.*]] = add i32 [[Y]], [[X]]
; CHECK-NEXT:    [[RET:%.*]] = add i32 [[Z]], [[LHS]]
; CHECK-NEXT:    ret i32 [[RET]]
;
  %min = call i32 @llvm.smin.i32(i32 %y, i32 %x)
  %lhs = add i32 %z, %min, !noundef !0
  %max = call i32 @llvm.smax.i32(i32 %x, i32 %y)
  %ret = add nuw nsw i32 %lhs, %max, !noundef !0
  ret i32 %ret
}

define float @fp_inner_no_reassoc_cmp(i1 %c, float %a, float %x, float %y) {
; CHECK-LABEL: define float @fp_inner_no_reassoc_cmp(
; CHECK-SAME: i1 [[C:%.*]], float [[A:%.*]], float [[X:%.*]], float [[Y:%.*]]) {
; CHECK-NEXT:    [[S0:%.*]] = select i1 [[C]], float [[X]], float [[Y]]
; CHECK-NEXT:    [[S1:%.*]] = select i1 [[C]], float [[Y]], float [[X]]
; CHECK-NEXT:    [[INNER:%.*]] = fadd float [[A]], [[S0]]
; CHECK-NEXT:    [[RETF:%.*]] = fadd reassoc nsz float [[INNER]], [[S1]]
; CHECK-NEXT:    ret float [[RETF]]
;
  %s0 = select i1 %c, float %x, float %y
  %s1 = select i1 %c, float %y, float %x
  %inner = fadd float %a, %s0
  %retf = fadd reassoc nsz float %inner, %s1
  ret float %retf
}

define float @fp_mixed_fmf_cmp(i1 %c, float %a, float %x, float %y) {
; CHECK-LABEL: define float @fp_mixed_fmf_cmp(
; CHECK-SAME: i1 [[C:%.*]], float [[A:%.*]], float [[X:%.*]], float [[Y:%.*]]) {
; CHECK-NEXT:    [[S0:%.*]] = select i1 [[C]], float [[X]], float [[Y]]
; CHECK-NEXT:    [[S1:%.*]] = select i1 [[C]], float [[Y]], float [[X]]
; CHECK-NEXT:    [[INNER:%.*]] = fadd nnan float [[A]], [[S0]]
; CHECK-NEXT:    [[RETF:%.*]] = fadd reassoc nnan ninf nsz float [[INNER]], [[S1]]
; CHECK-NEXT:    ret float [[RETF]]
;
  %s0 = select i1 %c, float %x, float %y
  %s1 = select i1 %c, float %y, float %x
  %inner = fadd nnan float %a, %s0
  %retf = fadd reassoc nsz nnan ninf float %inner, %s1
  ret float %retf
}

define float @fp_outer_fmf_metadata(i1 %c, float %a, float %x, float %y) {
; CHECK-LABEL: define float @fp_outer_fmf_metadata(
; CHECK-SAME: i1 [[C:%.*]], float [[A:%.*]], float [[X:%.*]], float [[Y:%.*]]) {
; CHECK-NEXT:    [[INNER:%.*]] = fadd reassoc nsz float [[X]], [[Y]]
; CHECK-NEXT:    [[RETF:%.*]] = fadd reassoc nnan ninf nsz float [[A]], [[INNER]]
; CHECK-NEXT:    ret float [[RETF]]
;
  %s0 = select i1 %c, float %x, float %y
  %s1 = select i1 %c, float %y, float %x
  %inner = fadd reassoc nnan ninf nsz float %a, %s0, !noundef !0
  %retf = fadd reassoc nnan ninf nsz float %inner, %s1, !noundef !0
  ret float %retf
}

!0 = !{}
