; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; fcmp ogt (select (fcmp ogt x, C1), x, C1), C2 --> fcmp ogt x, C2 when C2 > C1

define i1 @fcmp_ogt_select_ogt(float %x) {
; CHECK-LABEL: @fcmp_ogt_select_ogt(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp ogt float [[X1:%.*]], 0.000000e+00
; CHECK-NEXT:    [[X:%.*]] = select i1 [[CMP1]], float [[X1]], float 0.000000e+00
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp ogt float [[X]], 1.000000e+00
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp ogt float %x, 0.0
  %sel = select i1 %cmp1, float %x, float 0.0
  %cmp2 = fcmp ogt float %sel, 1.0
  ret i1 %cmp2
}

; oge variant with C2 > C1
define i1 @fcmp_oge_select_ogt(float %x) {
; CHECK-LABEL: @fcmp_oge_select_ogt(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp ogt float [[X1:%.*]], 0.000000e+00
; CHECK-NEXT:    [[X:%.*]] = select i1 [[CMP1]], float [[X1]], float 0.000000e+00
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp oge float [[X]], 1.000000e+00
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp ogt float %x, 0.0
  %sel = select i1 %cmp1, float %x, float 0.0
  %cmp2 = fcmp oge float %sel, 1.0
  ret i1 %cmp2
}

; min variant: fcmp olt (select (fcmp olt x, C1), x, C1), C2 --> fcmp olt x, C2 when C2 < C1
define i1 @fcmp_olt_select_olt(float %x) {
; CHECK-LABEL: @fcmp_olt_select_olt(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp olt float [[X1:%.*]], 0.000000e+00
; CHECK-NEXT:    [[X:%.*]] = select i1 [[CMP1]], float [[X1]], float 0.000000e+00
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp olt float [[X]], -1.000000e+00
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp olt float %x, 0.0
  %sel = select i1 %cmp1, float %x, float 0.0
  %cmp2 = fcmp olt float %sel, -1.0
  ret i1 %cmp2
}

; ole variant with C2 < C1
define i1 @fcmp_ole_select_olt(float %x) {
; CHECK-LABEL: @fcmp_ole_select_olt(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp olt float [[X1:%.*]], 0.000000e+00
; CHECK-NEXT:    [[X:%.*]] = select i1 [[CMP1]], float [[X1]], float 0.000000e+00
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp ole float [[X]], -1.000000e+00
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp olt float %x, 0.0
  %sel = select i1 %cmp1, float %x, float 0.0
  %cmp2 = fcmp ole float %sel, -1.0
  ret i1 %cmp2
}

; Inner oge, outer ogt
define i1 @fcmp_ogt_select_oge(float %x) {
; CHECK-LABEL: @fcmp_ogt_select_oge(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp oge float [[X1:%.*]], 0.000000e+00
; CHECK-NEXT:    [[X:%.*]] = select i1 [[CMP1]], float [[X1]], float 0.000000e+00
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp ogt float [[X]], 1.000000e+00
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp oge float %x, 0.0
  %sel = select i1 %cmp1, float %x, float 0.0
  %cmp2 = fcmp ogt float %sel, 1.0
  ret i1 %cmp2
}

; Unordered inner, ordered outer
define i1 @fcmp_ogt_select_ugt(float %x) {
; CHECK-LABEL: @fcmp_ogt_select_ugt(
; CHECK-NEXT:    [[CMP1_INV:%.*]] = fcmp ole float [[X1:%.*]], 0.000000e+00
; CHECK-NEXT:    [[X:%.*]] = select i1 [[CMP1_INV]], float 0.000000e+00, float [[X1]]
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp ogt float [[X]], 1.000000e+00
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp ugt float %x, 0.0
  %sel = select i1 %cmp1, float %x, float 0.0
  %cmp2 = fcmp ogt float %sel, 1.0
  ret i1 %cmp2
}

; Negative constants
define i1 @fcmp_ogt_select_ogt_neg(float %x) {
; CHECK-LABEL: @fcmp_ogt_select_ogt_neg(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp ogt float [[X1:%.*]], -5.000000e+00
; CHECK-NEXT:    [[X:%.*]] = select i1 [[CMP1]], float [[X1]], float -5.000000e+00
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp ogt float [[X]], -1.000000e+00
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp ogt float %x, -5.0
  %sel = select i1 %cmp1, float %x, float -5.0
  %cmp2 = fcmp ogt float %sel, -1.0
  ret i1 %cmp2
}

; Swapped select arms: select (fcmp olt x, C1), C1, x = max(x, C1)
define i1 @fcmp_ogt_select_swapped(float %x) {
; CHECK-LABEL: @fcmp_ogt_select_swapped(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp olt float [[X1:%.*]], 0.000000e+00
; CHECK-NEXT:    [[X:%.*]] = select i1 [[CMP1]], float 0.000000e+00, float [[X1]]
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp ogt float [[X]], 1.000000e+00
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp olt float %x, 0.0
  %sel = select i1 %cmp1, float 0.0, float %x
  %cmp2 = fcmp ogt float %sel, 1.0
  ret i1 %cmp2
}

; Multi-use of select (should still fold)
define i1 @fcmp_ogt_select_multiuse(float %x, ptr %p) {
; CHECK-LABEL: @fcmp_ogt_select_multiuse(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp ogt float [[X:%.*]], 0.000000e+00
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP1]], float [[X]], float 0.000000e+00
; CHECK-NEXT:    store float [[SEL]], ptr [[P:%.*]], align 4
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp ogt float [[SEL]], 1.000000e+00
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp ogt float %x, 0.0
  %sel = select i1 %cmp1, float %x, float 0.0
  store float %sel, ptr %p
  %cmp2 = fcmp ogt float %sel, 1.0
  ret i1 %cmp2
}

; ---- Negative tests ----

; C2 < C1 for max, should NOT fold
define i1 @fcmp_ogt_select_ogt_c2_less(float %x) {
; CHECK-LABEL: @fcmp_ogt_select_ogt_c2_less(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp ogt float [[X:%.*]], 5.000000e+00
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP1]], float [[X]], float 5.000000e+00
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp ogt float [[SEL]], 1.000000e+00
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp ogt float %x, 5.0
  %sel = select i1 %cmp1, float %x, float 5.0
  %cmp2 = fcmp ogt float %sel, 1.0
  ret i1 %cmp2
}

; C2 > C1 for min, should NOT fold
define i1 @fcmp_olt_select_olt_c2_greater(float %x) {
; CHECK-LABEL: @fcmp_olt_select_olt_c2_greater(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp olt float [[X:%.*]], -5.000000e+00
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP1]], float [[X]], float -5.000000e+00
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp olt float [[SEL]], -1.000000e+00
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp olt float %x, -5.0
  %sel = select i1 %cmp1, float %x, float -5.0
  %cmp2 = fcmp olt float %sel, -1.0
  ret i1 %cmp2
}

; Wrong direction: min with ogt, should NOT fold
define i1 @fcmp_ogt_select_olt_neg(float %x) {
; CHECK-LABEL: @fcmp_ogt_select_olt_neg(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp olt float [[X:%.*]], 0.000000e+00
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP1]], float [[X]], float 0.000000e+00
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp ogt float [[SEL]], 1.000000e+00
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp olt float %x, 0.0
  %sel = select i1 %cmp1, float %x, float 0.0
  %cmp2 = fcmp ogt float %sel, 1.0
  ret i1 %cmp2
}
