; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt --mtriple "arm-apple-macosx15.0.0" -S -passes=instcombine < %s | FileCheck %s
; RUN: opt --mtriple "x86_64-apple-macosx14.7.0" -S -passes=instcombine < %s | FileCheck %s
; RUN: opt --mtriple "x86_64-microsoft-windows" -S -passes=instcombine < %s | FileCheck %s

define double @fdiv_cosh_sinh(double %a) {
; CHECK-LABEL: @fdiv_cosh_sinh(
; CHECK-NEXT:    [[TMP1:%.*]] = call double @cosh(double [[A:%.*]])
; CHECK-NEXT:    [[TMP2:%.*]] = call double @sinh(double [[A]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv double [[TMP1]], [[TMP2]]
; CHECK-NEXT:    ret double [[DIV]]
;
  %cosh = call double @cosh(double %a)
  %sinh = call double @sinh(double %a)
  %div = fdiv double %cosh, %sinh
  ret double %div
}

define double @fdiv_strict_cosh_strict_sinh_reassoc(double %a) {
; CHECK-LABEL: @fdiv_strict_cosh_strict_sinh_reassoc(
; CHECK-NEXT:    [[TMP1:%.*]] = call double @cosh(double [[A:%.*]])
; CHECK-NEXT:    [[TMP2:%.*]] = call reassoc double @sinh(double [[A]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv double [[TMP1]], [[TMP2]]
; CHECK-NEXT:    ret double [[DIV]]
;
  %cosh = call double @cosh(double %a)
  %sinh = call reassoc double @sinh(double %a)
  %div = fdiv double %cosh, %sinh
  ret double %div
}

define double @fdiv_reassoc_cosh_strict_sinh_strict(double %a, ptr dereferenceable(2) %dummy) {
; CHECK-LABEL: @fdiv_reassoc_cosh_strict_sinh_strict(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc double @tanh(double [[A:%.*]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc double 1.000000e+00, [[TANH]]
; CHECK-NEXT:    ret double [[DIV]]
;
  %cosh = call double @cosh(double %a)
  %sinh = call double @sinh(double %a)
  %div = fdiv reassoc double %cosh, %sinh
  ret double %div
}

define double @fdiv_contract_reassoc_cosh_strict_sinh_strict(double %a, ptr dereferenceable(2) %dummy) {
; CHECK-LABEL: @fdiv_contract_reassoc_cosh_strict_sinh_strict(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc contract double @tanh(double [[A:%.*]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc contract double 1.000000e+00, [[TANH]]
; CHECK-NEXT:    ret double [[DIV]]
;
  %cosh = call double @cosh(double %a)
  %sinh = call double @sinh(double %a)
  %div = fdiv contract reassoc double %cosh, %sinh
  ret double %div
}

define double @fdiv_reassoc_cosh_reassoc_sinh_strict(double %a) {
; CHECK-LABEL: @fdiv_reassoc_cosh_reassoc_sinh_strict(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc double @tanh(double [[A:%.*]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc double 1.000000e+00, [[TANH]]
; CHECK-NEXT:    ret double [[DIV]]
;
  %cosh = call reassoc double @cosh(double %a)
  %sinh = call double @sinh(double %a)
  %div = fdiv reassoc double %cosh, %sinh
  ret double %div
}

define double @fdiv_contract_reassoc_cosh_reassoc_sinh_strict(double %a) {
; CHECK-LABEL: @fdiv_contract_reassoc_cosh_reassoc_sinh_strict(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc contract double @tanh(double [[A:%.*]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc contract double 1.000000e+00, [[TANH]]
; CHECK-NEXT:    ret double [[DIV]]
;
  %cosh = call reassoc double @cosh(double %a)
  %sinh = call double @sinh(double %a)
  %div = fdiv contract reassoc double %cosh, %sinh
  ret double %div
}

define double @fdiv_reassoc_cosh_sinh_reassoc_multiple_uses_sinh(double %a) {
; CHECK-LABEL: @fdiv_reassoc_cosh_sinh_reassoc_multiple_uses_sinh(
; CHECK-NEXT:    [[COSH:%.*]] = call reassoc double @cosh(double [[A:%.*]])
; CHECK-NEXT:    [[SINH:%.*]] = call reassoc double @sinh(double [[A]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc double [[COSH]], [[SINH]]
; CHECK-NEXT:    call void @use(double [[SINH]])
; CHECK-NEXT:    ret double [[DIV]]
;
  %cosh = call reassoc double @cosh(double %a)
  %sinh = call reassoc double @sinh(double %a)
  %div = fdiv reassoc double %cosh, %sinh
  call void @use(double %sinh)
  ret double %div
}

define double @fdiv_contract_reassoc_cosh_sinh_reassoc_multiple_uses_sinh(double %a) {
; CHECK-LABEL: @fdiv_contract_reassoc_cosh_sinh_reassoc_multiple_uses_sinh(
; CHECK-NEXT:    [[TMP1:%.*]] = call reassoc double @cosh(double [[A:%.*]])
; CHECK-NEXT:    [[TMP2:%.*]] = call reassoc double @sinh(double [[A]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc contract double [[TMP1]], [[TMP2]]
; CHECK-NEXT:    call void @use(double [[TMP2]])
; CHECK-NEXT:    ret double [[DIV]]
;
  %cosh = call reassoc double @cosh(double %a)
  %sinh = call reassoc double @sinh(double %a)
  %div = fdiv contract reassoc double %cosh, %sinh
  call void @use(double %sinh)
  ret double %div
}

define double @fdiv_cosh_sinh_reassoc(double %a){
; CHECK-LABEL: @fdiv_cosh_sinh_reassoc(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc double @tanh(double [[A:%.*]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc double 1.000000e+00, [[TANH]]
; CHECK-NEXT:    ret double [[DIV]]
;
  %cosh = call reassoc double @cosh(double %a)
  %sinh = call reassoc double @sinh(double %a)
  %div = fdiv reassoc double %cosh, %sinh
  ret double %div
}

define double @fdiv_contract_reassoc_cosh_sinh_reassoc(double %a){
; CHECK-LABEL: @fdiv_contract_reassoc_cosh_sinh_reassoc(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc contract double @tanh(double [[A:%.*]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc contract double 1.000000e+00, [[TANH]]
; CHECK-NEXT:    ret double [[DIV]]
;
  %cosh = call reassoc double @cosh(double %a)
  %sinh = call reassoc double @sinh(double %a)
  %div = fdiv contract reassoc double %cosh, %sinh
  ret double %div
}

define fp128 @fdiv_coshl_sinhl_reassoc(fp128 %a){
  %cosh = call reassoc fp128 @coshl(fp128 %a)
  %sinh = call reassoc fp128 @sinhl(fp128 %a)
  %div = fdiv reassoc fp128 %cosh, %sinh
  ret fp128 %div
}

define float @fdiv_coshf_sinhf_reassoc(float %a){
; CHECK-LABEL: @fdiv_coshf_sinhf_reassoc(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc float @tanhf(float [[A:%.*]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc float 1.000000e+00, [[TANH]]
; CHECK-NEXT:    ret float [[DIV]]
;
  %coshf = call reassoc float @coshf(float %a)
  %sinhf = call reassoc float @sinhf(float %a)
  %div = fdiv reassoc float %coshf, %sinhf
  ret float %div
}

define double @fdiv_fast_reassoc_cosh_sinh_reassoc(double %a){
; CHECK-LABEL: @fdiv_fast_reassoc_cosh_sinh_reassoc(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc ninf double @tanh(double [[A:%.*]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc ninf double 1.000000e+00, [[TANH]]
; CHECK-NEXT:    ret double [[DIV]]
;
  %cosh = call reassoc double @cosh(double %a)
  %sinh = call reassoc double @sinh(double %a)
  %div = fdiv ninf  reassoc double %cosh, %sinh
  ret double %div
}

define double @fdiv_nnan_reassoc_cosh_sinh_reassoc(double %a){
; CHECK-LABEL: @fdiv_nnan_reassoc_cosh_sinh_reassoc(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc nnan double @tanh(double [[A:%.*]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc nnan double 1.000000e+00, [[TANH]]
; CHECK-NEXT:    ret double [[DIV]]
;
  %cosh = call reassoc double @cosh(double %a)
  %sinh = call reassoc double @sinh(double %a)
  %div = fdiv nnan reassoc double %cosh, %sinh
  ret double %div
}

define double @fdiv_nsz_reassoc_cosh_sinh_reassoc(double %a){
; CHECK-LABEL: @fdiv_nsz_reassoc_cosh_sinh_reassoc(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc nsz double @tanh(double [[A:%.*]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc nsz double 1.000000e+00, [[TANH]]
; CHECK-NEXT:    ret double [[DIV]]
;
  %cosh = call reassoc double @cosh(double %a)
  %sinh = call reassoc double @sinh(double %a)
  %div = fdiv nsz reassoc double %cosh, %sinh
  ret double %div
}

define double @fdiv_arcp_reassoc_cosh_sinh_reassoc(double %a){
; CHECK-LABEL: @fdiv_arcp_reassoc_cosh_sinh_reassoc(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc arcp double @tanh(double [[A:%.*]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc arcp double 1.000000e+00, [[TANH]]
; CHECK-NEXT:    ret double [[DIV]]
;
  %cosh = call reassoc double @cosh(double %a)
  %sinh = call reassoc double @sinh(double %a)
  %div = fdiv arcp reassoc double %cosh, %sinh
  ret double %div
}

define double @fdiv_afn_reassoc_cosh_sinh_reassoc(double %a){
; CHECK-LABEL: @fdiv_afn_reassoc_cosh_sinh_reassoc(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc afn double @tanh(double [[A:%.*]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc afn double 1.000000e+00, [[TANH]]
; CHECK-NEXT:    ret double [[DIV]]
;
  %cosh = call reassoc double @cosh(double %a)
  %sinh = call reassoc double @sinh(double %a)
  %div = fdiv afn reassoc double %cosh, %sinh
  ret double %div
}

declare double @cosh(double)
declare float @coshf(float)
declare fp128 @coshl(fp128)

declare double @sinh(double)
declare float @sinhf(float)
declare fp128 @sinhl(fp128)

declare void @use(double)
