; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt --mtriple "arm-apple-macosx15.0.0" -S -passes=instcombine < %s | FileCheck %s
; RUN: opt --mtriple "x86_64-apple-macosx14.7.0" -S -passes=instcombine < %s | FileCheck %s
; RUN: opt --mtriple "x86_64-microsoft-windows" -S -passes=instcombine < %s | FileCheck %s

define double @fdiv_sinh_cosh(double %a) {
; CHECK-LABEL: @fdiv_sinh_cosh(
; CHECK-NEXT:    [[TMP1:%.*]] = call double @sinh(double [[A:%.*]])
; CHECK-NEXT:    [[TMP2:%.*]] = call double @cosh(double [[A]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv double [[TMP1]], [[TMP2]]
; CHECK-NEXT:    ret double [[DIV]]
;
  %sinh = call double @sinh(double %a)
  %cosh = call double @cosh(double %a)
  %div = fdiv double %sinh, %cosh
  ret double %div
}

define double @fdiv_reassoc_sinh_strict_cosh_strict(double %a, ptr dereferenceable(2) %dummy) {
; CHECK-LABEL: @fdiv_reassoc_sinh_strict_cosh_strict(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc double @tanh(double [[A:%.*]])
; CHECK-NEXT:    ret double [[TANH]]
;
  %sinh = call double @sinh(double %a)
  %cosh = call double @cosh(double %a)
  %div = fdiv reassoc double %sinh, %cosh
  ret double %div
}

define double @fdiv_contract_reassoc_sinh_strict_cosh_strict(double %a, ptr dereferenceable(2) %dummy) {
; CHECK-LABEL: @fdiv_contract_reassoc_sinh_strict_cosh_strict(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc contract double @tanh(double [[A:%.*]])
; CHECK-NEXT:    ret double [[TANH]]
;
  %sinh = call double @sinh(double %a)
  %cosh = call double @cosh(double %a)
  %div = fdiv contract reassoc double %sinh, %cosh
  ret double %div
}

define double @fdiv_reassoc_sinh_reassoc_cosh_strict(double %a) {
; CHECK-LABEL: @fdiv_reassoc_sinh_reassoc_cosh_strict(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc double @tanh(double [[A:%.*]])
; CHECK-NEXT:    ret double [[TANH]]
;
  %sinh = call reassoc double @sinh(double %a)
  %cosh = call double @cosh(double %a)
  %div = fdiv reassoc double %sinh, %cosh
  ret double %div
}

define double @fdiv_reassoc_sinh_contract_reassoc_cosh_strict(double %a) {
; CHECK-LABEL: @fdiv_reassoc_sinh_contract_reassoc_cosh_strict(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc double @tanh(double [[A:%.*]])
; CHECK-NEXT:    ret double [[TANH]]
;
  %sinh = call contract reassoc double @sinh(double %a)
  %cosh = call double @cosh(double %a)
  %div = fdiv reassoc double %sinh, %cosh
  ret double %div
}

define double @fdiv_contract_reassoc_sinh_reassoc_cosh_strict(double %a) {
; CHECK-LABEL: @fdiv_contract_reassoc_sinh_reassoc_cosh_strict(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc contract double @tanh(double [[A:%.*]])
; CHECK-NEXT:    ret double [[TANH]]
;
  %sinh = call reassoc double @sinh(double %a)
  %cosh = call double @cosh(double %a)
  %div = fdiv contract reassoc double %sinh, %cosh
  ret double %div
}

define double @fdiv_sinh_cosh_reassoc_multiple_uses_sinh(double %a) {
; CHECK-LABEL: @fdiv_sinh_cosh_reassoc_multiple_uses_sinh(
; CHECK-NEXT:    [[TMP1:%.*]] = call reassoc double @sinh(double [[A:%.*]])
; CHECK-NEXT:    [[TMP2:%.*]] = call reassoc double @cosh(double [[A]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc double [[TMP1]], [[TMP2]]
; CHECK-NEXT:    call void @use(double [[TMP1]])
; CHECK-NEXT:    ret double [[DIV]]
;
  %sinh = call reassoc double @sinh(double %a)
  %cosh = call reassoc double @cosh(double %a)
  %div = fdiv reassoc double %sinh, %cosh
  call void @use(double %sinh)
  ret double %div
}

define double @fdiv_contract_reassoc_sinh_cosh_reassoc_multiple_uses_sinh(double %a) {
; CHECK-LABEL: @fdiv_contract_reassoc_sinh_cosh_reassoc_multiple_uses_sinh(
; CHECK-NEXT:    [[SINH:%.*]] = call reassoc double @sinh(double [[A:%.*]])
; CHECK-NEXT:    [[COSH:%.*]] = call reassoc double @cosh(double [[A]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc contract double [[SINH]], [[COSH]]
; CHECK-NEXT:    call void @use(double [[SINH]])
; CHECK-NEXT:    ret double [[DIV]]
;
  %sinh = call reassoc double @sinh(double %a)
  %cosh = call reassoc double @cosh(double %a)
  %div = fdiv contract reassoc double %sinh, %cosh
  call void @use(double %sinh)
  ret double %div
}

define double @fdiv_sinh_cosh_reassoc_multiple_uses_cosh(double %a) {
; CHECK-LABEL: @fdiv_sinh_cosh_reassoc_multiple_uses_cosh(
; CHECK-NEXT:    [[TMP1:%.*]] = call reassoc double @sinh(double [[A:%.*]])
; CHECK-NEXT:    [[TMP2:%.*]] = call reassoc double @cosh(double [[A]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc double [[TMP1]], [[TMP2]]
; CHECK-NEXT:    call void @use(double [[TMP2]])
; CHECK-NEXT:    ret double [[DIV]]
;
  %sinh = call reassoc double @sinh(double %a)
  %cosh = call reassoc double @cosh(double %a)
  %div = fdiv reassoc double %sinh, %cosh
  call void @use(double %cosh)
  ret double %div
}

define double @fdiv_contract_reassocsinh_cosh_reassoc_multiple_uses_cosh(double %a) {
; CHECK-LABEL: @fdiv_contract_reassocsinh_cosh_reassoc_multiple_uses_cosh(
; CHECK-NEXT:    [[SINH:%.*]] = call reassoc double @sinh(double [[A:%.*]])
; CHECK-NEXT:    [[COSH:%.*]] = call reassoc double @cosh(double [[A]])
; CHECK-NEXT:    [[DIV:%.*]] = fdiv reassoc contract double [[SINH]], [[COSH]]
; CHECK-NEXT:    call void @use(double [[COSH]])
; CHECK-NEXT:    ret double [[DIV]]
;
  %sinh = call reassoc double @sinh(double %a)
  %cosh = call reassoc double @cosh(double %a)
  %div = fdiv contract reassoc double %sinh, %cosh
  call void @use(double %cosh)
  ret double %div
}

define double @fdiv_sinh_cosh_reassoc(double %a) {
; CHECK-LABEL: @fdiv_sinh_cosh_reassoc(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc double @tanh(double [[A:%.*]])
; CHECK-NEXT:    ret double [[TANH]]
;
  %sinh = call reassoc double @sinh(double %a)
  %cosh = call reassoc double @cosh(double %a)
  %div = fdiv reassoc double %sinh, %cosh
  ret double %div
}

define float @fdiv_sinhf_coshf_reassoc(float %a) {
; CHECK-LABEL: @fdiv_sinhf_coshf_reassoc(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc float @tanhf(float [[A:%.*]])
; CHECK-NEXT:    ret float [[TANH]]
;
  %sinhf = call reassoc float @sinhf(float %a)
  %coshf = call reassoc float @coshf(float %a)
  %div = fdiv reassoc float %sinhf, %coshf
  ret float %div
}

define fp128 @fdiv_sinhl_coshl_reassoc(fp128 %a) {
  %sinhl = call reassoc fp128 @sinhl(fp128 %a)
  %coshl = call reassoc fp128 @coshl(fp128 %a)
  %div = fdiv reassoc fp128 %sinhl, %coshl
  ret fp128 %div
}

define double @fdiv_fast_reassoc_sinh_strict_cosh_strict(double %a) {
; CHECK-LABEL: @fdiv_fast_reassoc_sinh_strict_cosh_strict(
; CHECK-NEXT:    [[TANH:%.*]] = call fast double @tanh(double [[A:%.*]])
; CHECK-NEXT:    ret double [[TANH]]
;
  %sinh = call double @sinh(double %a)
  %cosh = call double @cosh(double %a)
  %div = fdiv fast reassoc double %sinh, %cosh
  ret double %div
}

define double @fdiv_ninf_reassoc_sinh_strict_cosh_strict(double %a) {
; CHECK-LABEL: @fdiv_ninf_reassoc_sinh_strict_cosh_strict(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc ninf double @tanh(double [[A:%.*]])
; CHECK-NEXT:    ret double [[TANH]]
;
  %sinh = call double @sinh(double %a)
  %cosh = call double @cosh(double %a)
  %div = fdiv ninf reassoc double %sinh, %cosh
  ret double %div
}

define double @fdiv_nnan_reassoc_sinh_strict_cosh_strict(double %a) {
; CHECK-LABEL: @fdiv_nnan_reassoc_sinh_strict_cosh_strict(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc nnan double @tanh(double [[A:%.*]])
; CHECK-NEXT:    ret double [[TANH]]
;
  %sinh = call double @sinh(double %a)
  %cosh = call double @cosh(double %a)
  %div = fdiv nnan reassoc double %sinh, %cosh
  ret double %div
}

define double @fdiv_nsz_reassoc_sinh_strict_cosh_strict(double %a) {
; CHECK-LABEL: @fdiv_nsz_reassoc_sinh_strict_cosh_strict(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc nsz double @tanh(double [[A:%.*]])
; CHECK-NEXT:    ret double [[TANH]]
;
  %sinh = call double @sinh(double %a)
  %cosh = call double @cosh(double %a)
  %div = fdiv nsz reassoc double %sinh, %cosh
  ret double %div
}

define double @fdiv_arcp_reassoc_sinh_strict_cosh_strict(double %a) {
; CHECK-LABEL: @fdiv_arcp_reassoc_sinh_strict_cosh_strict(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc arcp double @tanh(double [[A:%.*]])
; CHECK-NEXT:    ret double [[TANH]]
;
  %sinh = call double @sinh(double %a)
  %cosh = call double @cosh(double %a)
  %div = fdiv arcp reassoc double %sinh, %cosh
  ret double %div
}

define double @fdiv_afn_reassoc_sinh_strict_cosh_strict(double %a) {
; CHECK-LABEL: @fdiv_afn_reassoc_sinh_strict_cosh_strict(
; CHECK-NEXT:    [[TANH:%.*]] = call reassoc afn double @tanh(double [[A:%.*]])
; CHECK-NEXT:    ret double [[TANH]]
;
  %sinh = call double @sinh(double %a)
  %cosh = call double @cosh(double %a)
  %div = fdiv afn reassoc double %sinh, %cosh
  ret double %div
}

declare double @cosh(double)
declare float @coshf(float)
declare fp128 @coshl(fp128)

declare double @sinh(double)
declare float @sinhf(float)
declare fp128 @sinhl(fp128)

declare void @use(double)
