; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define float @src(float %arg0) {
; CHECK-LABEL: define float @src(
; CHECK-SAME: float [[ARG0:%.*]]) {
; CHECK-NEXT:    [[V1:%.*]] = call nsz float @llvm.maxnum.f32(float [[ARG0]], float 0.000000e+00)
; CHECK-NEXT:    [[V3:%.*]] = call nsz float @llvm.minnum.f32(float [[V1]], float 0x3FE96C8000000000)
; CHECK-NEXT:    ret float [[V3]]
;
  %v0 = fcmp nsz ogt float %arg0, 0.000000e+00
  %v1 = select nsz i1 %v0, float %arg0, float 0.000000e+00
  %v2 = fcmp nsz ogt float %v1, 0x3FE96C8000000000
  %v3 = select nsz i1 %v2, float 0x3FE96C8000000000, float %v1
  ret float %v3
}

define float @src2(float %arg0) {
; CHECK-LABEL: define float @src2(
; CHECK-SAME: float [[ARG0:%.*]]) {
; CHECK-NEXT:    [[V1:%.*]] = call nsz float @llvm.minnum.f32(float [[ARG0]], float 0.000000e+00)
; CHECK-NEXT:    [[V3:%.*]] = call nsz float @llvm.maxnum.f32(float [[V1]], float -1.000000e+02)
; CHECK-NEXT:    ret float [[V3]]
;
  %v0 = fcmp nsz olt float %arg0, 0.000000e+00
  %v1 = select nsz i1 %v0, float %arg0, float 0.000000e+00
  %v2 = fcmp nsz olt float %v1, -100.00e+00
  %v3 = select nsz i1 %v2, float -100.00e+00, float %v1
  ret float %v3
}
