; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; X * Y (when Y is a boolean) --> Y ? X : 0

define float @fmul_bool(float %x, i1 %y) !prof !0 {
; CHECK-LABEL: define float @fmul_bool(
; CHECK-SAME: float [[X:%.*]], i1 [[Y:%.*]]) !prof [[PROF0:![0-9]+]] {
; CHECK-NEXT:    [[M:%.*]] = select nnan nsz i1 [[Y]], float [[X]], float 0.000000e+00, !prof [[PROF1:![0-9]+]]
; CHECK-NEXT:    ret float [[M]]
;
  %z = uitofp i1 %y to float
  %m = fmul nnan nsz float %z, %x
  ret float %m
}

define float @fmul_bool_bool_first(float %x, i1 %y) !prof !0 {
; CHECK-LABEL: define float @fmul_bool_bool_first(
; CHECK-SAME: float [[X:%.*]], i1 [[Y:%.*]]) !prof [[PROF0]] {
; CHECK-NEXT:    [[M:%.*]] = select nnan nsz i1 [[Y]], float [[X]], float 0.000000e+00, !prof [[PROF1]]
; CHECK-NEXT:    ret float [[M]]
;
  %z = uitofp i1 %y to float
  %m = fmul nnan nsz float %x, %z
  ret float %m
}

define <2 x float> @fmul_bool_vec(<2 x float> %x, <2 x i1> %y) {
; CHECK-LABEL: define <2 x float> @fmul_bool_vec(
; CHECK-SAME: <2 x float> [[X:%.*]], <2 x i1> [[Y:%.*]]) {
; CHECK-NEXT:    [[M:%.*]] = select nnan nsz <2 x i1> [[Y]], <2 x float> [[X]], <2 x float> zeroinitializer
; CHECK-NEXT:    ret <2 x float> [[M]]
;
  %z = uitofp <2 x i1> %y to <2 x float>
  %m = fmul nnan nsz <2 x float> %z, %x
  ret <2 x float> %m
}

define <2 x float> @fmul_bool_vec_commute(<2 x float> %px, <2 x i1> %y) {
; CHECK-LABEL: define <2 x float> @fmul_bool_vec_commute(
; CHECK-SAME: <2 x float> [[PX:%.*]], <2 x i1> [[Y:%.*]]) {
; CHECK-NEXT:    [[X:%.*]] = fmul nnan nsz <2 x float> [[PX]], [[PX]]
; CHECK-NEXT:    [[M:%.*]] = select nnan nsz <2 x i1> [[Y]], <2 x float> [[X]], <2 x float> zeroinitializer
; CHECK-NEXT:    ret <2 x float> [[M]]
;
  %x = fmul nnan nsz <2 x float> %px, %px  ; thwart complexity-based canonicalization
  %z = uitofp <2 x i1> %y to <2 x float>
  %m = fmul nnan nsz <2 x float> %x, %z
  ret <2 x float> %m
}

!0 = !{!"function_entry_count", i64 1000}
;.
; CHECK: [[PROF0]] = !{!"function_entry_count", i64 1000}
; CHECK: [[PROF1]] = !{!"unknown", !"instcombine"}
;.
