; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; BASE FORM - V2I64
define <4 x i32> @icmp_eq_v2i64_using_v4i32(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; CHECK-LABEL: define <4 x i32> @icmp_eq_v2i64_using_v4i32(
; CHECK-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to <2 x i64>
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[B]] to <2 x i64>
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq <2 x i64> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = sext <2 x i1> [[TMP3]] to <2 x i64>
; CHECK-NEXT:    [[SELECT:%.*]] = bitcast <2 x i64> [[TMP4]] to <4 x i32>
; CHECK-NEXT:    ret <4 x i32> [[SELECT]]
;
  %cmp = icmp eq <4 x i32> %a, %b
  %sext = sext <4 x i1> %cmp to <4 x i32>
  %shuffle = shufflevector <4 x i32> %sext, <4 x i32> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
  %select = select <4 x i1> %cmp, <4 x i32> %shuffle, <4 x i32> zeroinitializer
  ret <4 x i32> %select
}

; ALTERNATE FORM 1 - WITH AND
define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_and(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; CHECK-LABEL: define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_and(
; CHECK-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to <2 x i64>
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[B]] to <2 x i64>
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq <2 x i64> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = sext <2 x i1> [[TMP3]] to <2 x i64>
; CHECK-NEXT:    [[AND:%.*]] = bitcast <2 x i64> [[TMP4]] to <4 x i32>
; CHECK-NEXT:    ret <4 x i32> [[AND]]
;
  %cmp = icmp eq <4 x i32> %a, %b
  %sext = sext <4 x i1> %cmp to <4 x i32>
  %shuffle = shufflevector <4 x i32> %sext, <4 x i32> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
  %and = and <4 x i32> %sext, %shuffle
  ret <4 x i32> %and
}

; ALTERNATE FORM 2 - WITH COMMUTATED AND
define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_commutated_and(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; CHECK-LABEL: define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_commutated_and(
; CHECK-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to <2 x i64>
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[B]] to <2 x i64>
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq <2 x i64> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = sext <2 x i1> [[TMP3]] to <2 x i64>
; CHECK-NEXT:    [[AND:%.*]] = bitcast <2 x i64> [[TMP4]] to <4 x i32>
; CHECK-NEXT:    ret <4 x i32> [[AND]]
;
  %cmp = icmp eq <4 x i32> %a, %b
  %sext = sext <4 x i1> %cmp to <4 x i32>
  %shuffle = shufflevector <4 x i32> %sext, <4 x i32> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
  %and = and <4 x i32> %shuffle, %sext
  ret <4 x i32> %and
}

; ALTERNATE FORM 3 - WITH SEXT PUT LAST
define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_sext_put_last(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; CHECK-LABEL: define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_sext_put_last(
; CHECK-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to <2 x i64>
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[B]] to <2 x i64>
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq <2 x i64> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = sext <2 x i1> [[TMP3]] to <2 x i64>
; CHECK-NEXT:    [[SEXT:%.*]] = bitcast <2 x i64> [[TMP4]] to <4 x i32>
; CHECK-NEXT:    ret <4 x i32> [[SEXT]]
;
  %cmp = icmp eq <4 x i32> %a, %b
  %shuffle = shufflevector <4 x i1> %cmp, <4 x i1> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
  %and = and <4 x i1> %shuffle, %cmp
  %sext = sext <4 x i1> %and to <4 x i32>
  ret <4 x i32> %sext
}

; DIFFERENT VECTOR SIZES - V3I64
define <6 x i32> @icmp_eq_v3i64_using_v6i32(<6 x i32> noundef %a, <6 x i32> noundef %b) {
; CHECK-LABEL: define <6 x i32> @icmp_eq_v3i64_using_v6i32(
; CHECK-SAME: <6 x i32> noundef [[A:%.*]], <6 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <6 x i32> [[A]] to <3 x i64>
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <6 x i32> [[B]] to <3 x i64>
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq <3 x i64> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = sext <3 x i1> [[TMP3]] to <3 x i64>
; CHECK-NEXT:    [[AND:%.*]] = bitcast <3 x i64> [[TMP4]] to <6 x i32>
; CHECK-NEXT:    ret <6 x i32> [[AND]]
;
  %cmp = icmp eq <6 x i32> %a, %b
  %sext = sext <6 x i1> %cmp to <6 x i32>
  %shuffle = shufflevector <6 x i32> %sext, <6 x i32> poison, <6 x i32> <i32 1, i32 0, i32 3, i32 2, i32 5, i32 4>
  %and = and <6 x i32> %sext, %shuffle
  ret <6 x i32> %and
}

; DIFFERENT VECTOR SIZES - V4I64
define <8 x i32> @icmp_eq_v4i64_using_v8i32(<8 x i32> noundef %a, <8 x i32> noundef %b) {
; CHECK-LABEL: define <8 x i32> @icmp_eq_v4i64_using_v8i32(
; CHECK-SAME: <8 x i32> noundef [[A:%.*]], <8 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[A]] to <4 x i64>
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[B]] to <4 x i64>
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq <4 x i64> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = sext <4 x i1> [[TMP3]] to <4 x i64>
; CHECK-NEXT:    [[AND:%.*]] = bitcast <4 x i64> [[TMP4]] to <8 x i32>
; CHECK-NEXT:    ret <8 x i32> [[AND]]
;
  %cmp = icmp eq <8 x i32> %a, %b
  %sext = sext <8 x i1> %cmp to <8 x i32>
  %shuffle = shufflevector <8 x i32> %sext, <8 x i32> poison, <8 x i32> <i32 1, i32 0, i32 3, i32 2, i32 5, i32 4, i32 7, i32 6>
  %and = and <8 x i32> %sext, %shuffle
  ret <8 x i32> %and
}

; DIFFERENT VECTOR SIZES - V4I32
define <8 x i16> @icmp_eq_v4i32_using_v8i16(<8 x i16> noundef %a, <8 x i16> noundef %b) {
; CHECK-LABEL: define <8 x i16> @icmp_eq_v4i32_using_v8i16(
; CHECK-SAME: <8 x i16> noundef [[A:%.*]], <8 x i16> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i16> [[A]] to <4 x i32>
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i16> [[B]] to <4 x i32>
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq <4 x i32> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = sext <4 x i1> [[TMP3]] to <4 x i32>
; CHECK-NEXT:    [[AND:%.*]] = bitcast <4 x i32> [[TMP4]] to <8 x i16>
; CHECK-NEXT:    ret <8 x i16> [[AND]]
;
  %cmp = icmp eq <8 x i16> %a, %b
  %sext = sext <8 x i1> %cmp to <8 x i16>
  %shuffle = shufflevector <8 x i16> %sext, <8 x i16> poison, <8 x i32> <i32 1, i32 0, i32 3, i32 2, i32 5, i32 4, i32 7, i32 6>
  %and = and <8 x i16> %sext, %shuffle
  ret <8 x i16> %and
}

; DIFFERENT VECTOR SIZES - V1I64
define <2 x i32> @icmp_eq_v1i64_using_v2i32(<2 x i32> noundef %a, <2 x i32> noundef %b) {
; CHECK-LABEL: define <2 x i32> @icmp_eq_v1i64_using_v2i32(
; CHECK-SAME: <2 x i32> noundef [[A:%.*]], <2 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[A]] to <1 x i64>
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[B]] to <1 x i64>
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq <1 x i64> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = sext <1 x i1> [[TMP3]] to <1 x i64>
; CHECK-NEXT:    [[AND:%.*]] = bitcast <1 x i64> [[TMP4]] to <2 x i32>
; CHECK-NEXT:    ret <2 x i32> [[AND]]
;
  %cmp = icmp eq <2 x i32> %a, %b
  %sext = sext <2 x i1> %cmp to <2 x i32>
  %shuffle = shufflevector <2 x i32> %sext, <2 x i32> poison, <2 x i32> <i32 1, i32 0>
  %and = and <2 x i32> %sext, %shuffle
  ret <2 x i32> %and
}

; NEGATIVE - WRONG ICMP COND CODE
define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_wrong_icmp_cond_code(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; CHECK-LABEL: define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_wrong_icmp_cond_code(
; CHECK-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[SEXT:%.*]] = sext <4 x i1> [[CMP]] to <4 x i32>
; CHECK-NEXT:    [[SHUFFLE:%.*]] = shufflevector <4 x i32> [[SEXT]], <4 x i32> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
; CHECK-NEXT:    [[SELECT:%.*]] = select <4 x i1> [[CMP]], <4 x i32> [[SHUFFLE]], <4 x i32> zeroinitializer
; CHECK-NEXT:    ret <4 x i32> [[SELECT]]
;
  %cmp = icmp sgt <4 x i32> %a, %b
  %sext = sext <4 x i1> %cmp to <4 x i32>
  %shuffle = shufflevector <4 x i32> %sext, <4 x i32> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
  %select = select <4 x i1> %cmp, <4 x i32> %shuffle, <4 x i32> zeroinitializer
  ret <4 x i32> %select
}

; NEGATIVE - WRONG EXTENSION SIGNEDNESS
define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_wrong_ext_signedness(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; CHECK-LABEL: define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_wrong_ext_signedness(
; CHECK-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[SEXT:%.*]] = zext <4 x i1> [[CMP]] to <4 x i32>
; CHECK-NEXT:    [[SHUFFLE:%.*]] = shufflevector <4 x i32> [[SEXT]], <4 x i32> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
; CHECK-NEXT:    [[AND:%.*]] = and <4 x i32> [[SHUFFLE]], [[SEXT]]
; CHECK-NEXT:    ret <4 x i32> [[AND]]
;
  %cmp = icmp eq <4 x i32> %a, %b
  %sext = zext <4 x i1> %cmp to <4 x i32>
  %shuffle = shufflevector <4 x i32> %sext, <4 x i32> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
  %and = and <4 x i32> %sext, %shuffle
  ret <4 x i32> %and
}

; NEGATIVE - WRONG SHUFFLE VECTOR
define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_wrong_shuffle_vec(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; CHECK-LABEL: define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_wrong_shuffle_vec(
; CHECK-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[SEXT:%.*]] = sext <4 x i1> [[CMP]] to <4 x i32>
; CHECK-NEXT:    [[SHUFFLE:%.*]] = shufflevector <4 x i32> [[SEXT]], <4 x i32> poison, <4 x i32> <i32 3, i32 2, i32 1, i32 0>
; CHECK-NEXT:    [[SELECT:%.*]] = select <4 x i1> [[CMP]], <4 x i32> [[SHUFFLE]], <4 x i32> zeroinitializer
; CHECK-NEXT:    ret <4 x i32> [[SELECT]]
;
  %cmp = icmp eq <4 x i32> %a, %b
  %sext = sext <4 x i1> %cmp to <4 x i32>
  %shuffle = shufflevector <4 x i32> %sext, <4 x i32> poison, <4 x i32> <i32 3, i32 2, i32 1, i32 0>
  %select = select <4 x i1> %cmp, <4 x i32> %shuffle, <4 x i32> zeroinitializer
  ret <4 x i32> %select
}

; NEGATIVE - WRONG AND USING SELECT
define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_wrong_and_using_select(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; CHECK-LABEL: define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_wrong_and_using_select(
; CHECK-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[SEXT:%.*]] = sext <4 x i1> [[CMP]] to <4 x i32>
; CHECK-NEXT:    [[SHUFFLE:%.*]] = shufflevector <4 x i32> [[SEXT]], <4 x i32> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
; CHECK-NEXT:    [[SELECT:%.*]] = select <4 x i1> [[CMP]], <4 x i32> [[SHUFFLE]], <4 x i32> splat (i32 1)
; CHECK-NEXT:    ret <4 x i32> [[SELECT]]
;
  %cmp = icmp eq <4 x i32> %a, %b
  %sext = sext <4 x i1> %cmp to <4 x i32>
  %shuffle = shufflevector <4 x i32> %sext, <4 x i32> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
  %select = select <4 x i1> %cmp, <4 x i32> %shuffle, <4 x i32> <i32 1, i32 1, i32 1, i32 1>
  ret <4 x i32> %select
}

; NEGATIVE - POSSIBLY POISONED INPUT
define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_possibly_poisoned_input_using_select(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_possibly_poisoned_input_using_select(
; CHECK-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]]) {
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[SEXT:%.*]] = sext <4 x i1> [[CMP]] to <4 x i32>
; CHECK-NEXT:    [[SHUFFLE:%.*]] = shufflevector <4 x i32> [[SEXT]], <4 x i32> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
; CHECK-NEXT:    [[SELECT:%.*]] = select <4 x i1> [[CMP]], <4 x i32> [[SHUFFLE]], <4 x i32> zeroinitializer
; CHECK-NEXT:    ret <4 x i32> [[SELECT]]
;
  %cmp = icmp eq <4 x i32> %a, %b
  %sext = sext <4 x i1> %cmp to <4 x i32>
  %shuffle = shufflevector <4 x i32> %sext, <4 x i32> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
  %select = select <4 x i1> %cmp, <4 x i32> %shuffle, <4 x i32> zeroinitializer
  ret <4 x i32> %select
}

; POSITIVE - POSSIBLY POISONED INPUT USING AND
define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_possibly_poisoned_input_using_and(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: define <4 x i32> @icmp_eq_v2i64_using_v4i32_with_possibly_poisoned_input_using_and(
; CHECK-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to <2 x i64>
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[B]] to <2 x i64>
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq <2 x i64> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = sext <2 x i1> [[TMP3]] to <2 x i64>
; CHECK-NEXT:    [[AND:%.*]] = bitcast <2 x i64> [[TMP4]] to <4 x i32>
; CHECK-NEXT:    ret <4 x i32> [[AND]]
;
  %cmp = icmp eq <4 x i32> %a, %b
  %sext = sext <4 x i1> %cmp to <4 x i32>
  %shuffle = shufflevector <4 x i32> %sext, <4 x i32> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
  %and = and <4 x i32> %sext, %shuffle
  ret <4 x i32> %and
}
