; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

%foo = type { i16, i16, i16 }

define <16 x ptr> @test(i1 %tobool, i1 %end, <16 x i64> %varidx) {
; CHECK-LABEL: define <16 x ptr> @test(
; CHECK-SAME: i1 [[TOBOOL:%.*]], i1 [[END:%.*]], <16 x i64> [[VARIDX:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[LANE_0:%.*]] = alloca [[FOO:%.*]], align 16
; CHECK-NEXT:    [[LANE_15:%.*]] = insertelement <16 x ptr> poison, ptr [[LANE_0]], i64 0
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <16 x ptr> [ [[MM_VECTORGEP11:%.*]], %[[F0:.*]] ], [ [[MM_VECTORGEP22:%.*]], %[[F1:.*]] ], [ zeroinitializer, %[[ENTRY]] ]
; CHECK-NEXT:    br i1 [[TOBOOL]], label %[[F1]], label %[[F0]]
; CHECK:       [[F0]]:
; CHECK-NEXT:    [[MM_VECTORGEP11_SPLIT:%.*]] = getelementptr inbounds [[FOO]], <16 x ptr> [[LANE_15]], <16 x i64> [[VARIDX]]
; CHECK-NEXT:    [[MM_VECTORGEP11]] = getelementptr inbounds i8, <16 x ptr> [[MM_VECTORGEP11_SPLIT]], i64 2
; CHECK-NEXT:    br i1 [[END]], label %[[LOOP]], label %[[MERGE:.*]]
; CHECK:       [[F1]]:
; CHECK-NEXT:    [[MM_VECTORGEP22_SPLIT:%.*]] = getelementptr inbounds [[FOO]], <16 x ptr> [[LANE_15]], <16 x i64> [[VARIDX]]
; CHECK-NEXT:    [[MM_VECTORGEP22]] = getelementptr inbounds i8, <16 x ptr> [[MM_VECTORGEP22_SPLIT]], i64 4
; CHECK-NEXT:    br i1 [[END]], label %[[LOOP]], label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    ret <16 x ptr> [[VEC_PHI]]
;
entry:
  %lane.0 = alloca %foo, align 16
  %lane.15 = insertelement <16 x ptr> poison, ptr %lane.0, i64 0
  br label %loop

loop:
  %vec.phi = phi <16 x ptr> [ %mm_vectorGEP1, %f0], [ %mm_vectorGEP2, %f1 ], [ zeroinitializer, %entry]
  %mm_vectorGEP1 = getelementptr inbounds %foo, <16 x ptr> %lane.15, <16 x i64> %varidx, <16 x i32> splat (i32 1)
  %mm_vectorGEP2 = getelementptr inbounds %foo, <16 x ptr> %lane.15, <16 x i64> %varidx, <16 x i32> splat (i32 2)
  br i1 %tobool, label %f1, label %f0

f0:
  br i1 %end, label %loop, label %merge

f1:
  br i1 %end, label %loop, label %merge

merge:
  ret <16 x ptr> %vec.phi
}

