; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -p instcombine < %s | FileCheck %s

define <8 x i64> @zext_shufflevector(<16 x i32> %v) {
; CHECK-LABEL: define <8 x i64> @zext_shufflevector(
; CHECK-SAME: <16 x i32> [[V:%.*]]) {
; CHECK-NEXT:    [[TMP2:%.*]] = freeze <16 x i32> [[V]]
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP2]] to <8 x i64>
; CHECK-NEXT:    [[Z0:%.*]] = and <8 x i64> [[TMP1]], splat (i64 4294967295)
; CHECK-NEXT:    [[Z1:%.*]] = lshr <8 x i64> [[TMP1]], splat (i64 32)
; CHECK-NEXT:    [[R:%.*]] = mul nuw <8 x i64> [[Z0]], [[Z1]]
; CHECK-NEXT:    ret <8 x i64> [[R]]
;
  %f0 = shufflevector <16 x i32> %v, <16 x i32> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %f1 = shufflevector <16 x i32> %v, <16 x i32> poison, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %z0 = zext <8 x i32> %f0 to <8 x i64>
  %z1 = zext <8 x i32> %f1 to <8 x i64>
  %r = mul <8 x i64> %z0, %z1
  ret <8 x i64> %r
}

define <8 x i64> @zext_shufflevector_single_field(<16 x i32> %v) {
; CHECK-LABEL: define <8 x i64> @zext_shufflevector_single_field(
; CHECK-SAME: <16 x i32> [[V:%.*]]) {
; CHECK-NEXT:    [[TMP2:%.*]] = freeze <16 x i32> [[V]]
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <16 x i32> [[TMP2]] to <8 x i64>
; CHECK-NEXT:    [[Z0:%.*]] = and <8 x i64> [[TMP1]], splat (i64 4294967295)
; CHECK-NEXT:    ret <8 x i64> [[Z0]]
;
  %f0 = shufflevector <16 x i32> %v, <16 x i32> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %z0 = zext <8 x i32> %f0 to <8 x i64>
  ret <8 x i64> %z0
}

define <vscale x 8 x i64> @zext_deinterleave(<vscale x 16 x i32> %v) {
; CHECK-LABEL: define <vscale x 8 x i64> @zext_deinterleave(
; CHECK-SAME: <vscale x 16 x i32> [[V:%.*]]) {
; CHECK-NEXT:    [[TMP2:%.*]] = freeze <vscale x 16 x i32> [[V]]
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <vscale x 16 x i32> [[TMP2]] to <vscale x 8 x i64>
; CHECK-NEXT:    [[Z0:%.*]] = and <vscale x 8 x i64> [[TMP1]], splat (i64 4294967295)
; CHECK-NEXT:    [[Z1:%.*]] = lshr <vscale x 8 x i64> [[TMP1]], splat (i64 32)
; CHECK-NEXT:    [[R:%.*]] = mul nuw <vscale x 8 x i64> [[Z0]], [[Z1]]
; CHECK-NEXT:    ret <vscale x 8 x i64> [[R]]
;
  %d = call {<vscale x 8 x i32>, <vscale x 8 x i32>} @llvm.vector.deinterleave2(<vscale x 16 x i32> %v)
  %f0 = extractvalue {<vscale x 8 x i32>, <vscale x 8 x i32>} %d, 0
  %f1 = extractvalue {<vscale x 8 x i32>, <vscale x 8 x i32>} %d, 1
  %z0 = zext <vscale x 8 x i32> %f0 to <vscale x 8 x i64>
  %z1 = zext <vscale x 8 x i32> %f1 to <vscale x 8 x i64>
  %r = mul <vscale x 8 x i64> %z0, %z1
  ret <vscale x 8 x i64> %r
}

define <vscale x 8 x i64> @zext_deinterleave_multi_zext_per_field(<vscale x 16 x i32> %v) {
; CHECK-LABEL: define <vscale x 8 x i64> @zext_deinterleave_multi_zext_per_field(
; CHECK-SAME: <vscale x 16 x i32> [[V:%.*]]) {
; CHECK-NEXT:    [[TMP2:%.*]] = freeze <vscale x 16 x i32> [[V]]
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <vscale x 16 x i32> [[TMP2]] to <vscale x 8 x i64>
; CHECK-NEXT:    [[Z0:%.*]] = and <vscale x 8 x i64> [[TMP1]], splat (i64 4294967295)
; CHECK-NEXT:    [[Z1:%.*]] = lshr <vscale x 8 x i64> [[TMP1]], splat (i64 32)
; CHECK-NEXT:    [[R:%.*]] = mul nuw <vscale x 8 x i64> [[Z0]], [[Z1]]
; CHECK-NEXT:    [[R2:%.*]] = mul <vscale x 8 x i64> [[R]], [[Z0]]
; CHECK-NEXT:    ret <vscale x 8 x i64> [[R2]]
;
  %d = call {<vscale x 8 x i32>, <vscale x 8 x i32>} @llvm.vector.deinterleave2(<vscale x 16 x i32> %v)
  %f0 = extractvalue {<vscale x 8 x i32>, <vscale x 8 x i32>} %d, 0
  %f1 = extractvalue {<vscale x 8 x i32>, <vscale x 8 x i32>} %d, 1
  %z0 = zext <vscale x 8 x i32> %f0 to <vscale x 8 x i64>
  %z0.1 = zext <vscale x 8 x i32> %f0 to <vscale x 8 x i64>
  %z1 = zext <vscale x 8 x i32> %f1 to <vscale x 8 x i64>
  %r = mul <vscale x 8 x i64> %z0, %z1
  %r2 = mul <vscale x 8 x i64> %r, %z0.1
  ret <vscale x 8 x i64> %r2
}

define <vscale x 8 x i64> @zext_deinterleave_single_field(<vscale x 16 x i32> %v) {
; CHECK-LABEL: define <vscale x 8 x i64> @zext_deinterleave_single_field(
; CHECK-SAME: <vscale x 16 x i32> [[V:%.*]]) {
; CHECK-NEXT:    [[TMP2:%.*]] = freeze <vscale x 16 x i32> [[V]]
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <vscale x 16 x i32> [[TMP2]] to <vscale x 8 x i64>
; CHECK-NEXT:    [[Z1:%.*]] = lshr <vscale x 8 x i64> [[TMP1]], splat (i64 32)
; CHECK-NEXT:    ret <vscale x 8 x i64> [[Z1]]
;
  %d = call {<vscale x 8 x i32>, <vscale x 8 x i32>} @llvm.vector.deinterleave2(<vscale x 16 x i32> %v)
  %f1 = extractvalue {<vscale x 8 x i32>, <vscale x 8 x i32>} %d, 1
  %z1 = zext <vscale x 8 x i32> %f1 to <vscale x 8 x i64>
  ret <vscale x 8 x i64> %z1
}

; This code is effectively just doing bitcast on the loaded value.
define <8 x i64> @to_bitcast(ptr %p) {
; CHECK-LABEL: define <8 x i64> @to_bitcast(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[LD:%.*]] = load <16 x i32>, ptr [[P]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = freeze <16 x i32> [[LD]]
; CHECK-NEXT:    [[LD1:%.*]] = bitcast <16 x i32> [[TMP1]] to <8 x i64>
; CHECK-NEXT:    ret <8 x i64> [[LD1]]
;
  %ld = load <16 x i32>, ptr %p, align 4
  %f1 = shufflevector <16 x i32> %ld, <16 x i32> poison, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %z1 = zext <8 x i32> %f1 to <8 x i64>
  %part1 = shl nuw <8 x i64> %z1, splat (i64 32)
  %f0 = shufflevector <16 x i32> %ld, <16 x i32> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %part0 = zext <8 x i32> %f0 to <8 x i64>
  %r = or disjoint <8 x i64> %part1, %part0
  ret <8 x i64> %r
}

define <vscale x 8 x i64> @to_bitcast_deinterleave(ptr %p) {
; CHECK-LABEL: define <vscale x 8 x i64> @to_bitcast_deinterleave(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[LD:%.*]] = load <vscale x 16 x i32>, ptr [[P]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = freeze <vscale x 16 x i32> [[LD]]
; CHECK-NEXT:    [[LD1:%.*]] = bitcast <vscale x 16 x i32> [[TMP1]] to <vscale x 8 x i64>
; CHECK-NEXT:    ret <vscale x 8 x i64> [[LD1]]
;
  %ld = load <vscale x 16 x i32>, ptr %p, align 4
  %d = call {<vscale x 8 x i32>, <vscale x 8 x i32>} @llvm.vector.deinterleave2(<vscale x 16 x i32> %ld)
  %f1 = extractvalue {<vscale x 8 x i32>, <vscale x 8 x i32>} %d, 1
  %z1 = zext <vscale x 8 x i32> %f1 to <vscale x 8 x i64>
  %part1 = shl nuw <vscale x 8 x i64> %z1, splat (i64 32)
  %f0 = extractvalue {<vscale x 8 x i32>, <vscale x 8 x i32>} %d, 0
  %part0 = zext <vscale x 8 x i32> %f0 to <vscale x 8 x i64>
  %r = or disjoint <vscale x 8 x i64> %part1, %part0
  ret <vscale x 8 x i64> %r
}

; Regression test for a crash: https://github.com/llvm/llvm-project/pull/195330#issuecomment-4635245035
define <16 x i16> @zext_shufflevector_correct_insertpoint(<16 x i8> %load) {
; CHECK-LABEL: define <16 x i16> @zext_shufflevector_correct_insertpoint(
; CHECK-SAME: <16 x i8> [[LOAD:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = freeze <16 x i8> [[LOAD]]
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <8 x i16>
; CHECK-NEXT:    [[ZEXT:%.*]] = and <8 x i16> [[TMP2]], splat (i16 255)
; CHECK-NEXT:    [[ZEXT9:%.*]] = lshr <8 x i16> [[TMP2]], splat (i16 8)
; CHECK-NEXT:    [[ADD:%.*]] = add nuw nsw <8 x i16> [[ZEXT]], splat (i16 1)
; CHECK-NEXT:    [[TMP3:%.*]] = or <8 x i16> [[ADD]], [[ZEXT9]]
; CHECK-NEXT:    [[OR:%.*]] = shufflevector <8 x i16> [[TMP3]], <8 x i16> zeroinitializer, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    ret <16 x i16> [[OR]]
;
  %shufflevector4 = shufflevector <16 x i8> %load, <16 x i8> zeroinitializer, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %shufflevector = shufflevector <16 x i8> %load, <16 x i8> zeroinitializer, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %zext = zext <8 x i8> %shufflevector to <8 x i16>
  %shufflevector7 = shufflevector <8 x i8> %shufflevector4, <8 x i8> zeroinitializer, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %shufflevector8 = shufflevector <16 x i8> %shufflevector7, <16 x i8> zeroinitializer, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %add = add <8 x i16> %zext, splat (i16 1)
  %shufflevector6 = shufflevector <8 x i16> %add, <8 x i16> zeroinitializer, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %zext9 = zext <8 x i8> %shufflevector8 to <8 x i16>
  %shufflevector10 = shufflevector <8 x i16> %zext9, <8 x i16> zeroinitializer, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %or = or <16 x i16> %shufflevector6, %shufflevector10
  ret <16 x i16> %or
}

define <8 x i64> @negative_zext_shufflevector_not_zext(<16 x i32> %v) {
; CHECK-LABEL: define <8 x i64> @negative_zext_shufflevector_not_zext(
; CHECK-SAME: <16 x i32> [[V:%.*]]) {
; CHECK-NEXT:    [[F0:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
; CHECK-NEXT:    [[F1:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
; CHECK-NEXT:    [[Z0:%.*]] = zext <8 x i32> [[F0]] to <8 x i64>
; CHECK-NEXT:    [[A:%.*]] = add <8 x i32> [[F1]], splat (i32 7)
; CHECK-NEXT:    [[Z1:%.*]] = zext <8 x i32> [[A]] to <8 x i64>
; CHECK-NEXT:    [[R:%.*]] = mul nuw <8 x i64> [[Z0]], [[Z1]]
; CHECK-NEXT:    ret <8 x i64> [[R]]
;
  %f0 = shufflevector <16 x i32> %v, <16 x i32> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %f1 = shufflevector <16 x i32> %v, <16 x i32> poison, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %z0 = zext <8 x i32> %f0 to <8 x i64>
  %a = add <8 x i32> %f1, splat (i32 7)
  %z1 = zext <8 x i32> %a to <8 x i64>
  %r = mul <8 x i64> %z0, %z1
  ret <8 x i64> %r
}

define <vscale x 8 x i64> @negative_zext_deinterleave_not_zext(<vscale x 16 x i32> %v) {
; CHECK-LABEL: define <vscale x 8 x i64> @negative_zext_deinterleave_not_zext(
; CHECK-SAME: <vscale x 16 x i32> [[V:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = call { <vscale x 8 x i32>, <vscale x 8 x i32> } @llvm.vector.deinterleave2.nxv16i32(<vscale x 16 x i32> [[V]])
; CHECK-NEXT:    [[F0:%.*]] = extractvalue { <vscale x 8 x i32>, <vscale x 8 x i32> } [[D]], 0
; CHECK-NEXT:    [[F1:%.*]] = extractvalue { <vscale x 8 x i32>, <vscale x 8 x i32> } [[D]], 1
; CHECK-NEXT:    [[A:%.*]] = add <vscale x 8 x i32> [[F0]], splat (i32 7)
; CHECK-NEXT:    [[Z0:%.*]] = zext <vscale x 8 x i32> [[A]] to <vscale x 8 x i64>
; CHECK-NEXT:    [[Z1:%.*]] = zext <vscale x 8 x i32> [[F1]] to <vscale x 8 x i64>
; CHECK-NEXT:    [[R:%.*]] = mul nuw <vscale x 8 x i64> [[Z0]], [[Z1]]
; CHECK-NEXT:    ret <vscale x 8 x i64> [[R]]
;
  %d = call {<vscale x 8 x i32>, <vscale x 8 x i32>} @llvm.vector.deinterleave2(<vscale x 16 x i32> %v)
  %f0 = extractvalue {<vscale x 8 x i32>, <vscale x 8 x i32>} %d, 0
  %f1 = extractvalue {<vscale x 8 x i32>, <vscale x 8 x i32>} %d, 1
  %a = add <vscale x 8 x i32> %f0, splat (i32 7)
  %z0 = zext <vscale x 8 x i32> %a to <vscale x 8 x i64>
  %z1 = zext <vscale x 8 x i32> %f1 to <vscale x 8 x i64>
  %r = mul <vscale x 8 x i64> %z0, %z1
  ret <vscale x 8 x i64> %r
}

define <8 x i64> @negative_zext_shufflevector_invalid_zext(<16 x i16> %v) {
; CHECK-LABEL: define <8 x i64> @negative_zext_shufflevector_invalid_zext(
; CHECK-SAME: <16 x i16> [[V:%.*]]) {
; CHECK-NEXT:    [[F0:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
; CHECK-NEXT:    [[F1:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
; CHECK-NEXT:    [[Z0:%.*]] = zext <8 x i16> [[F0]] to <8 x i64>
; CHECK-NEXT:    [[Z1:%.*]] = zext <8 x i16> [[F1]] to <8 x i64>
; CHECK-NEXT:    [[R:%.*]] = mul nuw nsw <8 x i64> [[Z0]], [[Z1]]
; CHECK-NEXT:    ret <8 x i64> [[R]]
;
  %f0 = shufflevector <16 x i16> %v, <16 x i16> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %f1 = shufflevector <16 x i16> %v, <16 x i16> poison, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %z0 = zext <8 x i16> %f0 to <8 x i64>
  %z1 = zext <8 x i16> %f1 to <8 x i64>
  %r = mul <8 x i64> %z0, %z1
  ret <8 x i64> %r
}

define <2 x i64> @negative_zext_shufflevector_invalid_shuffle_mask1(<2 x i32> %v) {
; CHECK-LABEL: define <2 x i64> @negative_zext_shufflevector_invalid_shuffle_mask1(
; CHECK-SAME: <2 x i32> [[V:%.*]]) {
; CHECK-NEXT:    [[F1:%.*]] = shufflevector <2 x i32> [[V]], <2 x i32> poison, <2 x i32> <i32 1, i32 poison>
; CHECK-NEXT:    [[Z1:%.*]] = zext <2 x i32> [[F1]] to <2 x i64>
; CHECK-NEXT:    ret <2 x i64> [[Z1]]
;
  %f1 = shufflevector <2 x i32> %v, <2 x i32> poison, <2 x i32> <i32 1, i32 3>
  %z1 = zext <2 x i32> %f1 to <2 x i64>
  ret <2 x i64> %z1
}

define <2 x i64> @negative_zext_shufflevector_invalid_shuffle_mask2(<8 x i32> %v) {
; CHECK-LABEL: define <2 x i64> @negative_zext_shufflevector_invalid_shuffle_mask2(
; CHECK-SAME: <8 x i32> [[V:%.*]]) {
; CHECK-NEXT:    [[F1:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[Z1:%.*]] = zext <2 x i32> [[F1]] to <2 x i64>
; CHECK-NEXT:    ret <2 x i64> [[Z1]]
;
  %f1 = shufflevector <8 x i32> %v, <8 x i32> poison, <2 x i32> <i32 0, i32 2>
  %z1 = zext <2 x i32> %f1 to <2 x i64>
  ret <2 x i64> %z1
}
