; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s --check-prefixes=CHECK,LITTLE
; RUN: sed 's/target datalayout = "e"/target datalayout = "E"/' %s \
; RUN: | opt -passes=instcombine -S | FileCheck %s --check-prefixes=CHECK,BIG
target datalayout = "e"

; BASE FORM - V2I64
define <4 x i32> @icmp_sgt_v2i64_using_v4i32(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; LITTLE-LABEL: define <4 x i32> @icmp_sgt_v2i64_using_v4i32(
; LITTLE-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; LITTLE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to <2 x i64>
; LITTLE-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[B]] to <2 x i64>
; LITTLE-NEXT:    [[TMP3:%.*]] = icmp sgt <2 x i64> [[TMP1]], [[TMP2]]
; LITTLE-NEXT:    [[TMP4:%.*]] = sext <2 x i1> [[TMP3]] to <2 x i64>
; LITTLE-NEXT:    [[OR:%.*]] = bitcast <2 x i64> [[TMP4]] to <4 x i32>
; LITTLE-NEXT:    ret <4 x i32> [[OR]]
;
; BIG-LABEL: define <4 x i32> @icmp_sgt_v2i64_using_v4i32(
; BIG-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; BIG-NEXT:    [[XOR_A:%.*]] = xor <4 x i32> [[A]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[XOR_B:%.*]] = xor <4 x i32> [[B]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[GT:%.*]] = icmp sgt <4 x i32> [[XOR_A]], [[XOR_B]]
; BIG-NEXT:    [[SEXT_GT:%.*]] = sext <4 x i1> [[GT]] to <4 x i32>
; BIG-NEXT:    [[GT_0:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; BIG-NEXT:    [[GT_1:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[EQ:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; BIG-NEXT:    [[SEXT_EQ:%.*]] = sext <4 x i1> [[EQ]] to <4 x i32>
; BIG-NEXT:    [[EQ_0:%.*]] = shufflevector <4 x i32> [[SEXT_EQ]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[AND:%.*]] = and <4 x i32> [[GT_0]], [[EQ_0]]
; BIG-NEXT:    [[OR:%.*]] = or <4 x i32> [[AND]], [[GT_1]]
; BIG-NEXT:    ret <4 x i32> [[OR]]
;
  %xor.a = xor <4 x i32> %a, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %xor.b = xor <4 x i32> %b, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %gt = icmp sgt <4 x i32> %xor.a, %xor.b
  %sext.gt = sext <4 x i1> %gt to <4 x i32>
  %gt.0 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %gt.1 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %eq = icmp eq <4 x i32> %a, %b
  %sext.eq = sext <4 x i1> %eq to <4 x i32>
  %eq.0 = shufflevector <4 x i32> %sext.eq, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %and = and <4 x i32> %gt.0, %eq.0
  %or = or <4 x i32> %and, %gt.1
  ret <4 x i32> %or
}

; ALTERNATE FORM - WITH SELECT
define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_select(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; LITTLE-LABEL: define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_select(
; LITTLE-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; LITTLE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to <2 x i64>
; LITTLE-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[B]] to <2 x i64>
; LITTLE-NEXT:    [[TMP3:%.*]] = icmp sgt <2 x i64> [[TMP1]], [[TMP2]]
; LITTLE-NEXT:    [[TMP4:%.*]] = sext <2 x i1> [[TMP3]] to <2 x i64>
; LITTLE-NEXT:    [[OR:%.*]] = bitcast <2 x i64> [[TMP4]] to <4 x i32>
; LITTLE-NEXT:    ret <4 x i32> [[OR]]
;
; BIG-LABEL: define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_select(
; BIG-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; BIG-NEXT:    [[XOR_A:%.*]] = xor <4 x i32> [[A]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[XOR_B:%.*]] = xor <4 x i32> [[B]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[GT:%.*]] = icmp sgt <4 x i32> [[XOR_A]], [[XOR_B]]
; BIG-NEXT:    [[SEXT_GT:%.*]] = sext <4 x i1> [[GT]] to <4 x i32>
; BIG-NEXT:    [[GT_0:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; BIG-NEXT:    [[GT_1:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[EQ:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; BIG-NEXT:    [[EQ_0:%.*]] = shufflevector <4 x i1> [[EQ]], <4 x i1> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[SELECT:%.*]] = select <4 x i1> [[EQ_0]], <4 x i32> [[GT_0]], <4 x i32> zeroinitializer
; BIG-NEXT:    [[OR:%.*]] = or <4 x i32> [[SELECT]], [[GT_1]]
; BIG-NEXT:    ret <4 x i32> [[OR]]
;
  %xor.a = xor <4 x i32> %a, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %xor.b = xor <4 x i32> %b, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %gt = icmp sgt <4 x i32> %xor.a, %xor.b
  %sext.gt = sext <4 x i1> %gt to <4 x i32>
  %gt.0 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %gt.1 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %eq = icmp eq <4 x i32> %a, %b
  %eq.0 = shufflevector <4 x i1> %eq, <4 x i1> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %select = select <4 x i1> %eq.0, <4 x i32> %gt.0, <4 x i32> zeroinitializer
  %or = or <4 x i32> %select, %gt.1
  ret <4 x i32> %or
}

; ALTERNATE FORM - WITH SEXT PUT LAST
define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_sext_put_last(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; LITTLE-LABEL: define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_sext_put_last(
; LITTLE-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; LITTLE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to <2 x i64>
; LITTLE-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[B]] to <2 x i64>
; LITTLE-NEXT:    [[TMP3:%.*]] = icmp sgt <2 x i64> [[TMP1]], [[TMP2]]
; LITTLE-NEXT:    [[TMP4:%.*]] = sext <2 x i1> [[TMP3]] to <2 x i64>
; LITTLE-NEXT:    [[SEXT_OR:%.*]] = bitcast <2 x i64> [[TMP4]] to <4 x i32>
; LITTLE-NEXT:    ret <4 x i32> [[SEXT_OR]]
;
; BIG-LABEL: define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_sext_put_last(
; BIG-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; BIG-NEXT:    [[XOR_A:%.*]] = xor <4 x i32> [[A]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[XOR_B:%.*]] = xor <4 x i32> [[B]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[GT:%.*]] = icmp sgt <4 x i32> [[XOR_A]], [[XOR_B]]
; BIG-NEXT:    [[GT_0:%.*]] = shufflevector <4 x i1> [[GT]], <4 x i1> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; BIG-NEXT:    [[GT_1:%.*]] = shufflevector <4 x i1> [[GT]], <4 x i1> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[EQ:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; BIG-NEXT:    [[EQ_0:%.*]] = shufflevector <4 x i1> [[EQ]], <4 x i1> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[SELECT:%.*]] = select <4 x i1> [[EQ_0]], <4 x i1> [[GT_0]], <4 x i1> zeroinitializer
; BIG-NEXT:    [[OR:%.*]] = or <4 x i1> [[SELECT]], [[GT_1]]
; BIG-NEXT:    [[SEXT_OR:%.*]] = sext <4 x i1> [[OR]] to <4 x i32>
; BIG-NEXT:    ret <4 x i32> [[SEXT_OR]]
;
  %xor.a = xor <4 x i32> %a, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %xor.b = xor <4 x i32> %b, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %gt = icmp sgt <4 x i32> %xor.a, %xor.b
  %gt.0 = shufflevector <4 x i1> %gt, <4 x i1> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %gt.1 = shufflevector <4 x i1> %gt, <4 x i1> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %eq = icmp eq <4 x i32> %a, %b
  %eq.0 = shufflevector <4 x i1> %eq, <4 x i1> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %select = select <4 x i1> %eq.0, <4 x i1> %gt.0, <4 x i1> zeroinitializer
  %or = or <4 x i1> %select, %gt.1
  %sext.or = sext <4 x i1> %or to <4 x i32>
  ret <4 x i32> %sext.or
}

; DIFFERENT VECTOR SIZES - V3I64
define <6 x i32> @icmp_sgt_v3i64_using_v6i32(<6 x i32> noundef %a, <6 x i32> noundef %b) {
; LITTLE-LABEL: define <6 x i32> @icmp_sgt_v3i64_using_v6i32(
; LITTLE-SAME: <6 x i32> noundef [[A:%.*]], <6 x i32> noundef [[B:%.*]]) {
; LITTLE-NEXT:    [[TMP1:%.*]] = bitcast <6 x i32> [[A]] to <3 x i64>
; LITTLE-NEXT:    [[TMP2:%.*]] = bitcast <6 x i32> [[B]] to <3 x i64>
; LITTLE-NEXT:    [[TMP3:%.*]] = icmp sgt <3 x i64> [[TMP1]], [[TMP2]]
; LITTLE-NEXT:    [[TMP4:%.*]] = sext <3 x i1> [[TMP3]] to <3 x i64>
; LITTLE-NEXT:    [[OR:%.*]] = bitcast <3 x i64> [[TMP4]] to <6 x i32>
; LITTLE-NEXT:    ret <6 x i32> [[OR]]
;
; BIG-LABEL: define <6 x i32> @icmp_sgt_v3i64_using_v6i32(
; BIG-SAME: <6 x i32> noundef [[A:%.*]], <6 x i32> noundef [[B:%.*]]) {
; BIG-NEXT:    [[XOR_A:%.*]] = xor <6 x i32> [[A]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[XOR_B:%.*]] = xor <6 x i32> [[B]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[GT:%.*]] = icmp sgt <6 x i32> [[XOR_A]], [[XOR_B]]
; BIG-NEXT:    [[SEXT_GT:%.*]] = sext <6 x i1> [[GT]] to <6 x i32>
; BIG-NEXT:    [[GT_0:%.*]] = shufflevector <6 x i32> [[SEXT_GT]], <6 x i32> poison, <6 x i32> <i32 0, i32 0, i32 2, i32 2, i32 4, i32 4>
; BIG-NEXT:    [[GT_1:%.*]] = shufflevector <6 x i32> [[SEXT_GT]], <6 x i32> poison, <6 x i32> <i32 1, i32 1, i32 3, i32 3, i32 5, i32 5>
; BIG-NEXT:    [[EQ:%.*]] = icmp eq <6 x i32> [[A]], [[B]]
; BIG-NEXT:    [[EQ_0:%.*]] = shufflevector <6 x i1> [[EQ]], <6 x i1> poison, <6 x i32> <i32 1, i32 1, i32 3, i32 3, i32 5, i32 5>
; BIG-NEXT:    [[SELECT:%.*]] = select <6 x i1> [[EQ_0]], <6 x i32> [[GT_0]], <6 x i32> zeroinitializer
; BIG-NEXT:    [[OR:%.*]] = or <6 x i32> [[SELECT]], [[GT_1]]
; BIG-NEXT:    ret <6 x i32> [[OR]]
;
  %xor.a = xor <6 x i32> %a, <i32 -2147483648, i32 0, i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %xor.b = xor <6 x i32> %b, <i32 -2147483648, i32 0, i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %gt = icmp sgt <6 x i32> %xor.a, %xor.b
  %sext.gt = sext <6 x i1> %gt to <6 x i32>
  %gt.0 = shufflevector <6 x i32> %sext.gt, <6 x i32> poison, <6 x i32> <i32 0, i32 0, i32 2, i32 2, i32 4, i32 4>
  %gt.1 = shufflevector <6 x i32> %sext.gt, <6 x i32> poison, <6 x i32> <i32 1, i32 1, i32 3, i32 3, i32 5, i32 5>
  %eq = icmp eq <6 x i32> %a, %b
  %eq.0 = shufflevector <6 x i1> %eq, <6 x i1> poison, <6 x i32> <i32 1, i32 1, i32 3, i32 3, i32 5, i32 5>
  %select = select <6 x i1> %eq.0, <6 x i32> %gt.0, <6 x i32> zeroinitializer
  %or = or <6 x i32> %select, %gt.1
  ret <6 x i32> %or
}

; DIFFERENT VECTOR SIZES - V4I64
define <8 x i32> @icmp_sgt_v4i64_using_v6i32(<8 x i32> noundef %a, <8 x i32> noundef %b) {
; LITTLE-LABEL: define <8 x i32> @icmp_sgt_v4i64_using_v6i32(
; LITTLE-SAME: <8 x i32> noundef [[A:%.*]], <8 x i32> noundef [[B:%.*]]) {
; LITTLE-NEXT:    [[TMP1:%.*]] = bitcast <8 x i32> [[A]] to <4 x i64>
; LITTLE-NEXT:    [[TMP2:%.*]] = bitcast <8 x i32> [[B]] to <4 x i64>
; LITTLE-NEXT:    [[TMP3:%.*]] = icmp sgt <4 x i64> [[TMP1]], [[TMP2]]
; LITTLE-NEXT:    [[TMP4:%.*]] = sext <4 x i1> [[TMP3]] to <4 x i64>
; LITTLE-NEXT:    [[OR:%.*]] = bitcast <4 x i64> [[TMP4]] to <8 x i32>
; LITTLE-NEXT:    ret <8 x i32> [[OR]]
;
; BIG-LABEL: define <8 x i32> @icmp_sgt_v4i64_using_v6i32(
; BIG-SAME: <8 x i32> noundef [[A:%.*]], <8 x i32> noundef [[B:%.*]]) {
; BIG-NEXT:    [[XOR_A:%.*]] = xor <8 x i32> [[A]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0, i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[XOR_B:%.*]] = xor <8 x i32> [[B]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0, i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[GT:%.*]] = icmp sgt <8 x i32> [[XOR_A]], [[XOR_B]]
; BIG-NEXT:    [[SEXT_GT:%.*]] = sext <8 x i1> [[GT]] to <8 x i32>
; BIG-NEXT:    [[GT_0:%.*]] = shufflevector <8 x i32> [[SEXT_GT]], <8 x i32> poison, <8 x i32> <i32 0, i32 0, i32 2, i32 2, i32 4, i32 4, i32 6, i32 6>
; BIG-NEXT:    [[GT_1:%.*]] = shufflevector <8 x i32> [[SEXT_GT]], <8 x i32> poison, <8 x i32> <i32 1, i32 1, i32 3, i32 3, i32 5, i32 5, i32 7, i32 7>
; BIG-NEXT:    [[EQ:%.*]] = icmp eq <8 x i32> [[A]], [[B]]
; BIG-NEXT:    [[EQ_0:%.*]] = shufflevector <8 x i1> [[EQ]], <8 x i1> poison, <8 x i32> <i32 1, i32 1, i32 3, i32 3, i32 5, i32 5, i32 7, i32 7>
; BIG-NEXT:    [[SELECT:%.*]] = select <8 x i1> [[EQ_0]], <8 x i32> [[GT_0]], <8 x i32> zeroinitializer
; BIG-NEXT:    [[OR:%.*]] = or <8 x i32> [[SELECT]], [[GT_1]]
; BIG-NEXT:    ret <8 x i32> [[OR]]
;
  %xor.a = xor <8 x i32> %a, <i32 -2147483648, i32 0, i32 -2147483648, i32 0, i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %xor.b = xor <8 x i32> %b, <i32 -2147483648, i32 0, i32 -2147483648, i32 0, i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %gt = icmp sgt <8 x i32> %xor.a, %xor.b
  %sext.gt = sext <8 x i1> %gt to <8 x i32>
  %gt.0 = shufflevector <8 x i32> %sext.gt, <8 x i32> poison, <8 x i32> <i32 0, i32 0, i32 2, i32 2, i32 4, i32 4, i32 6, i32 6>
  %gt.1 = shufflevector <8 x i32> %sext.gt, <8 x i32> poison, <8 x i32> <i32 1, i32 1, i32 3, i32 3, i32 5, i32 5, i32 7, i32 7>
  %eq = icmp eq <8 x i32> %a, %b
  %eq.0 = shufflevector <8 x i1> %eq, <8 x i1> poison, <8 x i32> <i32 1, i32 1, i32 3, i32 3, i32 5, i32 5, i32 7, i32 7>
  %select = select <8 x i1> %eq.0, <8 x i32> %gt.0, <8 x i32> zeroinitializer
  %or = or <8 x i32> %select, %gt.1
  ret <8 x i32> %or
}

; DIFFERENT VECTOR SIZES - V4I32
define <8 x i16> @icmp_sgt_v4i32_using_v8i16(<8 x i16> noundef %a, <8 x i16> noundef %b) {
; LITTLE-LABEL: define <8 x i16> @icmp_sgt_v4i32_using_v8i16(
; LITTLE-SAME: <8 x i16> noundef [[A:%.*]], <8 x i16> noundef [[B:%.*]]) {
; LITTLE-NEXT:    [[TMP1:%.*]] = bitcast <8 x i16> [[A]] to <4 x i32>
; LITTLE-NEXT:    [[TMP2:%.*]] = bitcast <8 x i16> [[B]] to <4 x i32>
; LITTLE-NEXT:    [[TMP3:%.*]] = icmp sgt <4 x i32> [[TMP1]], [[TMP2]]
; LITTLE-NEXT:    [[TMP4:%.*]] = sext <4 x i1> [[TMP3]] to <4 x i32>
; LITTLE-NEXT:    [[OR:%.*]] = bitcast <4 x i32> [[TMP4]] to <8 x i16>
; LITTLE-NEXT:    ret <8 x i16> [[OR]]
;
; BIG-LABEL: define <8 x i16> @icmp_sgt_v4i32_using_v8i16(
; BIG-SAME: <8 x i16> noundef [[A:%.*]], <8 x i16> noundef [[B:%.*]]) {
; BIG-NEXT:    [[XOR_A:%.*]] = xor <8 x i16> [[A]], <i16 -32768, i16 0, i16 -32768, i16 0, i16 -32768, i16 0, i16 -32768, i16 0>
; BIG-NEXT:    [[XOR_B:%.*]] = xor <8 x i16> [[B]], <i16 -32768, i16 0, i16 -32768, i16 0, i16 -32768, i16 0, i16 -32768, i16 0>
; BIG-NEXT:    [[GT:%.*]] = icmp sgt <8 x i16> [[XOR_A]], [[XOR_B]]
; BIG-NEXT:    [[SEXT_GT:%.*]] = sext <8 x i1> [[GT]] to <8 x i16>
; BIG-NEXT:    [[GT_0:%.*]] = shufflevector <8 x i16> [[SEXT_GT]], <8 x i16> poison, <8 x i32> <i32 0, i32 0, i32 2, i32 2, i32 4, i32 4, i32 6, i32 6>
; BIG-NEXT:    [[GT_1:%.*]] = shufflevector <8 x i16> [[SEXT_GT]], <8 x i16> poison, <8 x i32> <i32 1, i32 1, i32 3, i32 3, i32 5, i32 5, i32 7, i32 7>
; BIG-NEXT:    [[EQ:%.*]] = icmp eq <8 x i16> [[A]], [[B]]
; BIG-NEXT:    [[EQ_0:%.*]] = shufflevector <8 x i1> [[EQ]], <8 x i1> poison, <8 x i32> <i32 1, i32 1, i32 3, i32 3, i32 5, i32 5, i32 7, i32 7>
; BIG-NEXT:    [[SELECT:%.*]] = select <8 x i1> [[EQ_0]], <8 x i16> [[GT_0]], <8 x i16> zeroinitializer
; BIG-NEXT:    [[OR:%.*]] = or <8 x i16> [[SELECT]], [[GT_1]]
; BIG-NEXT:    ret <8 x i16> [[OR]]
;
  %xor.a = xor <8 x i16> %a, <i16 u0x8000, i16 0, i16 u0x8000, i16 0, i16 u0x8000, i16 0, i16 u0x8000, i16 0>
  %xor.b = xor <8 x i16> %b, <i16 u0x8000, i16 0, i16 u0x8000, i16 0, i16 u0x8000, i16 0, i16 u0x8000, i16 0>
  %gt = icmp sgt <8 x i16> %xor.a, %xor.b
  %sext.gt = sext <8 x i1> %gt to <8 x i16>
  %gt.0 = shufflevector <8 x i16> %sext.gt, <8 x i16> poison, <8 x i32> <i32 0, i32 0, i32 2, i32 2, i32 4, i32 4, i32 6, i32 6>
  %gt.1 = shufflevector <8 x i16> %sext.gt, <8 x i16> poison, <8 x i32> <i32 1, i32 1, i32 3, i32 3, i32 5, i32 5, i32 7, i32 7>
  %eq = icmp eq <8 x i16> %a, %b
  %eq.0 = shufflevector <8 x i1> %eq, <8 x i1> poison, <8 x i32> <i32 1, i32 1, i32 3, i32 3, i32 5, i32 5, i32 7, i32 7>
  %select = select <8 x i1> %eq.0, <8 x i16> %gt.0, <8 x i16> zeroinitializer
  %or = or <8 x i16> %select, %gt.1
  ret <8 x i16> %or
}

; DIFFERENT VECTOR SIZES - V1I64
define <2 x i32> @icmp_sgt_v1i64_using_v2i32(<2 x i32> noundef %a, <2 x i32> noundef %b) {
; LITTLE-LABEL: define <2 x i32> @icmp_sgt_v1i64_using_v2i32(
; LITTLE-SAME: <2 x i32> noundef [[A:%.*]], <2 x i32> noundef [[B:%.*]]) {
; LITTLE-NEXT:    [[TMP1:%.*]] = bitcast <2 x i32> [[A]] to <1 x i64>
; LITTLE-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[B]] to <1 x i64>
; LITTLE-NEXT:    [[TMP3:%.*]] = icmp sgt <1 x i64> [[TMP1]], [[TMP2]]
; LITTLE-NEXT:    [[TMP4:%.*]] = sext <1 x i1> [[TMP3]] to <1 x i64>
; LITTLE-NEXT:    [[OR:%.*]] = bitcast <1 x i64> [[TMP4]] to <2 x i32>
; LITTLE-NEXT:    ret <2 x i32> [[OR]]
;
; BIG-LABEL: define <2 x i32> @icmp_sgt_v1i64_using_v2i32(
; BIG-SAME: <2 x i32> noundef [[A:%.*]], <2 x i32> noundef [[B:%.*]]) {
; BIG-NEXT:    [[XOR_A:%.*]] = xor <2 x i32> [[A]], <i32 -2147483648, i32 0>
; BIG-NEXT:    [[XOR_B:%.*]] = xor <2 x i32> [[B]], <i32 -2147483648, i32 0>
; BIG-NEXT:    [[GT:%.*]] = icmp sgt <2 x i32> [[XOR_A]], [[XOR_B]]
; BIG-NEXT:    [[SEXT_GT:%.*]] = sext <2 x i1> [[GT]] to <2 x i32>
; BIG-NEXT:    [[GT_0:%.*]] = shufflevector <2 x i32> [[SEXT_GT]], <2 x i32> poison, <2 x i32> zeroinitializer
; BIG-NEXT:    [[GT_1:%.*]] = shufflevector <2 x i32> [[SEXT_GT]], <2 x i32> poison, <2 x i32> <i32 1, i32 1>
; BIG-NEXT:    [[EQ:%.*]] = icmp eq <2 x i32> [[A]], [[B]]
; BIG-NEXT:    [[EQ_0:%.*]] = shufflevector <2 x i1> [[EQ]], <2 x i1> poison, <2 x i32> <i32 1, i32 1>
; BIG-NEXT:    [[SELECT:%.*]] = select <2 x i1> [[EQ_0]], <2 x i32> [[GT_0]], <2 x i32> zeroinitializer
; BIG-NEXT:    [[OR:%.*]] = or <2 x i32> [[SELECT]], [[GT_1]]
; BIG-NEXT:    ret <2 x i32> [[OR]]
;
  %xor.a = xor <2 x i32> %a, <i32 -2147483648, i32 0>
  %xor.b = xor <2 x i32> %b, <i32 -2147483648, i32 0>
  %gt = icmp sgt <2 x i32> %xor.a, %xor.b
  %sext.gt = sext <2 x i1> %gt to <2 x i32>
  %gt.0 = shufflevector <2 x i32> %sext.gt, <2 x i32> poison, <2 x i32> <i32 0, i32 0>
  %gt.1 = shufflevector <2 x i32> %sext.gt, <2 x i32> poison, <2 x i32> <i32 1, i32 1>
  %eq = icmp eq <2 x i32> %a, %b
  %eq.0 = shufflevector <2 x i1> %eq, <2 x i1> poison, <2 x i32> <i32 1, i32 1>
  %select = select <2 x i1> %eq.0, <2 x i32> %gt.0, <2 x i32> zeroinitializer
  %or = or <2 x i32> %select, %gt.1
  ret <2 x i32> %or
}

; BASE FORM - UNSIGNED GREATER THAN
define <4 x i32> @icmp_ugt_v2i64_using_v4i32(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; LITTLE-LABEL: define <4 x i32> @icmp_ugt_v2i64_using_v4i32(
; LITTLE-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; LITTLE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to <2 x i64>
; LITTLE-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[B]] to <2 x i64>
; LITTLE-NEXT:    [[TMP3:%.*]] = icmp ugt <2 x i64> [[TMP1]], [[TMP2]]
; LITTLE-NEXT:    [[TMP4:%.*]] = sext <2 x i1> [[TMP3]] to <2 x i64>
; LITTLE-NEXT:    [[OR:%.*]] = bitcast <2 x i64> [[TMP4]] to <4 x i32>
; LITTLE-NEXT:    ret <4 x i32> [[OR]]
;
; BIG-LABEL: define <4 x i32> @icmp_ugt_v2i64_using_v4i32(
; BIG-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; BIG-NEXT:    [[GT:%.*]] = icmp ugt <4 x i32> [[A]], [[B]]
; BIG-NEXT:    [[SEXT_GT:%.*]] = sext <4 x i1> [[GT]] to <4 x i32>
; BIG-NEXT:    [[GT_0:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; BIG-NEXT:    [[GT_1:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[EQ:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; BIG-NEXT:    [[SEXT_EQ:%.*]] = sext <4 x i1> [[EQ]] to <4 x i32>
; BIG-NEXT:    [[EQ_0:%.*]] = shufflevector <4 x i32> [[SEXT_EQ]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[AND:%.*]] = and <4 x i32> [[GT_0]], [[EQ_0]]
; BIG-NEXT:    [[OR:%.*]] = or <4 x i32> [[AND]], [[GT_1]]
; BIG-NEXT:    ret <4 x i32> [[OR]]
;
  %gt = icmp ugt <4 x i32> %a, %b
  %sext.gt = sext <4 x i1> %gt to <4 x i32>
  %gt.0 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %gt.1 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %eq = icmp eq <4 x i32> %a, %b
  %sext.eq = sext <4 x i1> %eq to <4 x i32>
  %eq.0 = shufflevector <4 x i32> %sext.eq, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %and = and <4 x i32> %gt.0, %eq.0
  %or = or <4 x i32> %and, %gt.1
  ret <4 x i32> %or
}

; ALTERNATE FORM - UNSIGNED GREATER THAN - WITH SIGNED GREATER THAN
define <4 x i32> @icmp_ugt_v2i64_using_v4i32_with_sgt(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; LITTLE-LABEL: define <4 x i32> @icmp_ugt_v2i64_using_v4i32_with_sgt(
; LITTLE-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; LITTLE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to <2 x i64>
; LITTLE-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[B]] to <2 x i64>
; LITTLE-NEXT:    [[TMP3:%.*]] = icmp ugt <2 x i64> [[TMP1]], [[TMP2]]
; LITTLE-NEXT:    [[TMP4:%.*]] = sext <2 x i1> [[TMP3]] to <2 x i64>
; LITTLE-NEXT:    [[OR:%.*]] = bitcast <2 x i64> [[TMP4]] to <4 x i32>
; LITTLE-NEXT:    ret <4 x i32> [[OR]]
;
; BIG-LABEL: define <4 x i32> @icmp_ugt_v2i64_using_v4i32_with_sgt(
; BIG-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; BIG-NEXT:    [[GT:%.*]] = icmp ugt <4 x i32> [[A]], [[B]]
; BIG-NEXT:    [[SEXT_GT:%.*]] = sext <4 x i1> [[GT]] to <4 x i32>
; BIG-NEXT:    [[GT_0:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; BIG-NEXT:    [[GT_1:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[EQ:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; BIG-NEXT:    [[SEXT_EQ:%.*]] = sext <4 x i1> [[EQ]] to <4 x i32>
; BIG-NEXT:    [[EQ_0:%.*]] = shufflevector <4 x i32> [[SEXT_EQ]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[AND:%.*]] = and <4 x i32> [[GT_0]], [[EQ_0]]
; BIG-NEXT:    [[OR:%.*]] = or <4 x i32> [[AND]], [[GT_1]]
; BIG-NEXT:    ret <4 x i32> [[OR]]
;
  %xor.a = xor <4 x i32> %a, <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648>
  %xor.b = xor <4 x i32> %b, <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648>
  %gt = icmp sgt <4 x i32> %xor.a, %xor.b
  %sext.gt = sext <4 x i1> %gt to <4 x i32>
  %gt.0 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %gt.1 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %eq = icmp eq <4 x i32> %a, %b
  %sext.eq = sext <4 x i1> %eq to <4 x i32>
  %eq.0 = shufflevector <4 x i32> %sext.eq, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %and = and <4 x i32> %gt.0, %eq.0
  %or = or <4 x i32> %and, %gt.1
  ret <4 x i32> %or
}

; BASE FORM - SIGNED LESS THAN
define <4 x i32> @icmp_slt_v2i64_using_v4i32(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; LITTLE-LABEL: define <4 x i32> @icmp_slt_v2i64_using_v4i32(
; LITTLE-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; LITTLE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to <2 x i64>
; LITTLE-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[B]] to <2 x i64>
; LITTLE-NEXT:    [[TMP3:%.*]] = icmp slt <2 x i64> [[TMP1]], [[TMP2]]
; LITTLE-NEXT:    [[TMP4:%.*]] = sext <2 x i1> [[TMP3]] to <2 x i64>
; LITTLE-NEXT:    [[OR:%.*]] = bitcast <2 x i64> [[TMP4]] to <4 x i32>
; LITTLE-NEXT:    ret <4 x i32> [[OR]]
;
; BIG-LABEL: define <4 x i32> @icmp_slt_v2i64_using_v4i32(
; BIG-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; BIG-NEXT:    [[XOR_A:%.*]] = xor <4 x i32> [[A]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[XOR_B:%.*]] = xor <4 x i32> [[B]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[GT:%.*]] = icmp slt <4 x i32> [[XOR_A]], [[XOR_B]]
; BIG-NEXT:    [[SEXT_GT:%.*]] = sext <4 x i1> [[GT]] to <4 x i32>
; BIG-NEXT:    [[GT_0:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; BIG-NEXT:    [[GT_1:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[EQ:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; BIG-NEXT:    [[SEXT_EQ:%.*]] = sext <4 x i1> [[EQ]] to <4 x i32>
; BIG-NEXT:    [[EQ_0:%.*]] = shufflevector <4 x i32> [[SEXT_EQ]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[AND:%.*]] = and <4 x i32> [[GT_0]], [[EQ_0]]
; BIG-NEXT:    [[OR:%.*]] = or <4 x i32> [[AND]], [[GT_1]]
; BIG-NEXT:    ret <4 x i32> [[OR]]
;
  %xor.a = xor <4 x i32> %a, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %xor.b = xor <4 x i32> %b, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %gt = icmp slt <4 x i32> %xor.a, %xor.b
  %sext.gt = sext <4 x i1> %gt to <4 x i32>
  %gt.0 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %gt.1 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %eq = icmp eq <4 x i32> %a, %b
  %sext.eq = sext <4 x i1> %eq to <4 x i32>
  %eq.0 = shufflevector <4 x i32> %sext.eq, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %and = and <4 x i32> %gt.0, %eq.0
  %or = or <4 x i32> %and, %gt.1
  ret <4 x i32> %or
}

; ALTERNATE FORM - SIGNED LESS THAN - WITH COMMUTATED GREATER THAN
define <4 x i32> @icmp_slt_v2i64_using_v4i32_with_commutated_gt(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; LITTLE-LABEL: define <4 x i32> @icmp_slt_v2i64_using_v4i32_with_commutated_gt(
; LITTLE-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; LITTLE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to <2 x i64>
; LITTLE-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[B]] to <2 x i64>
; LITTLE-NEXT:    [[TMP3:%.*]] = icmp slt <2 x i64> [[TMP1]], [[TMP2]]
; LITTLE-NEXT:    [[TMP4:%.*]] = sext <2 x i1> [[TMP3]] to <2 x i64>
; LITTLE-NEXT:    [[OR:%.*]] = bitcast <2 x i64> [[TMP4]] to <4 x i32>
; LITTLE-NEXT:    ret <4 x i32> [[OR]]
;
; BIG-LABEL: define <4 x i32> @icmp_slt_v2i64_using_v4i32_with_commutated_gt(
; BIG-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; BIG-NEXT:    [[XOR_A:%.*]] = xor <4 x i32> [[A]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[XOR_B:%.*]] = xor <4 x i32> [[B]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[GT:%.*]] = icmp sgt <4 x i32> [[XOR_B]], [[XOR_A]]
; BIG-NEXT:    [[SEXT_GT:%.*]] = sext <4 x i1> [[GT]] to <4 x i32>
; BIG-NEXT:    [[GT_0:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; BIG-NEXT:    [[GT_1:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[EQ:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; BIG-NEXT:    [[SEXT_EQ:%.*]] = sext <4 x i1> [[EQ]] to <4 x i32>
; BIG-NEXT:    [[EQ_0:%.*]] = shufflevector <4 x i32> [[SEXT_EQ]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[AND:%.*]] = and <4 x i32> [[GT_0]], [[EQ_0]]
; BIG-NEXT:    [[OR:%.*]] = or <4 x i32> [[AND]], [[GT_1]]
; BIG-NEXT:    ret <4 x i32> [[OR]]
;
  %xor.a = xor <4 x i32> %a, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %xor.b = xor <4 x i32> %b, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %gt = icmp sgt <4 x i32> %xor.b, %xor.a
  %sext.gt = sext <4 x i1> %gt to <4 x i32>
  %gt.0 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %gt.1 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %eq = icmp eq <4 x i32> %a, %b
  %sext.eq = sext <4 x i1> %eq to <4 x i32>
  %eq.0 = shufflevector <4 x i32> %sext.eq, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %and = and <4 x i32> %gt.0, %eq.0
  %or = or <4 x i32> %and, %gt.1
  ret <4 x i32> %or
}

; ALTERNATE FORM - FOR BIG ENDIAN MACHINE
define <4 x i32> @icmp_sgt_v2i64_using_v4i32_for_big_endian_machine(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; LITTLE-LABEL: define <4 x i32> @icmp_sgt_v2i64_using_v4i32_for_big_endian_machine(
; LITTLE-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; LITTLE-NEXT:    [[XOR_A:%.*]] = xor <4 x i32> [[A]], <i32 0, i32 -2147483648, i32 0, i32 -2147483648>
; LITTLE-NEXT:    [[XOR_B:%.*]] = xor <4 x i32> [[B]], <i32 0, i32 -2147483648, i32 0, i32 -2147483648>
; LITTLE-NEXT:    [[GT:%.*]] = icmp sgt <4 x i32> [[XOR_A]], [[XOR_B]]
; LITTLE-NEXT:    [[SEXT_GT:%.*]] = sext <4 x i1> [[GT]] to <4 x i32>
; LITTLE-NEXT:    [[GT_0:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; LITTLE-NEXT:    [[GT_1:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; LITTLE-NEXT:    [[EQ:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; LITTLE-NEXT:    [[SEXT_EQ:%.*]] = sext <4 x i1> [[EQ]] to <4 x i32>
; LITTLE-NEXT:    [[EQ_0:%.*]] = shufflevector <4 x i32> [[SEXT_EQ]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; LITTLE-NEXT:    [[AND:%.*]] = and <4 x i32> [[GT_0]], [[EQ_0]]
; LITTLE-NEXT:    [[OR:%.*]] = or <4 x i32> [[AND]], [[GT_1]]
; LITTLE-NEXT:    ret <4 x i32> [[OR]]
;
; BIG-LABEL: define <4 x i32> @icmp_sgt_v2i64_using_v4i32_for_big_endian_machine(
; BIG-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; BIG-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to <2 x i64>
; BIG-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[B]] to <2 x i64>
; BIG-NEXT:    [[TMP3:%.*]] = icmp sgt <2 x i64> [[TMP1]], [[TMP2]]
; BIG-NEXT:    [[TMP4:%.*]] = sext <2 x i1> [[TMP3]] to <2 x i64>
; BIG-NEXT:    [[OR:%.*]] = bitcast <2 x i64> [[TMP4]] to <4 x i32>
; BIG-NEXT:    ret <4 x i32> [[OR]]
;
  %xor.a = xor <4 x i32> %a, <i32 0, i32 -2147483648, i32 0, i32 -2147483648>
  %xor.b = xor <4 x i32> %b, <i32 0, i32 -2147483648, i32 0, i32 -2147483648>
  %gt = icmp sgt <4 x i32> %xor.a, %xor.b
  %sext.gt = sext <4 x i1> %gt to <4 x i32>
  %gt.0 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %gt.1 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %eq = icmp eq <4 x i32> %a, %b
  %sext.eq = sext <4 x i1> %eq to <4 x i32>
  %eq.0 = shufflevector <4 x i32> %sext.eq, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %and = and <4 x i32> %gt.0, %eq.0
  %or = or <4 x i32> %and, %gt.1
  ret <4 x i32> %or
}

; NEGATIVE - WRONG XOR MASK
define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_wrong_xor_mask(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; CHECK-LABEL: define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_wrong_xor_mask(
; CHECK-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[XOR_A:%.*]] = xor <4 x i32> [[A]], <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 0>
; CHECK-NEXT:    [[XOR_B:%.*]] = xor <4 x i32> [[B]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; CHECK-NEXT:    [[GT:%.*]] = icmp sgt <4 x i32> [[XOR_A]], [[XOR_B]]
; CHECK-NEXT:    [[SEXT_GT:%.*]] = sext <4 x i1> [[GT]] to <4 x i32>
; CHECK-NEXT:    [[GT_0:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; CHECK-NEXT:    [[GT_1:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; CHECK-NEXT:    [[EQ:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[SEXT_EQ:%.*]] = sext <4 x i1> [[EQ]] to <4 x i32>
; CHECK-NEXT:    [[EQ_0:%.*]] = shufflevector <4 x i32> [[SEXT_EQ]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; CHECK-NEXT:    [[AND:%.*]] = and <4 x i32> [[GT_0]], [[EQ_0]]
; CHECK-NEXT:    [[OR:%.*]] = or <4 x i32> [[AND]], [[GT_1]]
; CHECK-NEXT:    ret <4 x i32> [[OR]]
;
  %xor.a = xor <4 x i32> %a, <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 0>
  %xor.b = xor <4 x i32> %b, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %gt = icmp sgt <4 x i32> %xor.a, %xor.b
  %sext.gt = sext <4 x i1> %gt to <4 x i32>
  %gt.0 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %gt.1 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %eq = icmp eq <4 x i32> %a, %b
  %sext.eq = sext <4 x i1> %eq to <4 x i32>
  %eq.0 = shufflevector <4 x i32> %sext.eq, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %and = and <4 x i32> %gt.0, %eq.0
  %or = or <4 x i32> %and, %gt.1
  ret <4 x i32> %or
}

; NEGATIVE - WRONG ICMP COND CODE
define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_wrong_icmp_cond_code(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; CHECK-LABEL: define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_wrong_icmp_cond_code(
; CHECK-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[XOR_A:%.*]] = xor <4 x i32> [[A]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; CHECK-NEXT:    [[XOR_B:%.*]] = xor <4 x i32> [[B]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; CHECK-NEXT:    [[GT:%.*]] = icmp ugt <4 x i32> [[XOR_A]], [[XOR_B]]
; CHECK-NEXT:    [[SEXT_GT:%.*]] = sext <4 x i1> [[GT]] to <4 x i32>
; CHECK-NEXT:    [[GT_0:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; CHECK-NEXT:    [[GT_1:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; CHECK-NEXT:    [[EQ:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[SEXT_EQ:%.*]] = sext <4 x i1> [[EQ]] to <4 x i32>
; CHECK-NEXT:    [[EQ_0:%.*]] = shufflevector <4 x i32> [[SEXT_EQ]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; CHECK-NEXT:    [[AND:%.*]] = and <4 x i32> [[GT_0]], [[EQ_0]]
; CHECK-NEXT:    [[OR:%.*]] = or <4 x i32> [[AND]], [[GT_1]]
; CHECK-NEXT:    ret <4 x i32> [[OR]]
;
  %xor.a = xor <4 x i32> %a, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %xor.b = xor <4 x i32> %b, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %gt = icmp ugt <4 x i32> %xor.a, %xor.b
  %sext.gt = sext <4 x i1> %gt to <4 x i32>
  %gt.0 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %gt.1 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %eq = icmp eq <4 x i32> %a, %b
  %sext.eq = sext <4 x i1> %eq to <4 x i32>
  %eq.0 = shufflevector <4 x i32> %sext.eq, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %and = and <4 x i32> %gt.0, %eq.0
  %or = or <4 x i32> %and, %gt.1
  ret <4 x i32> %or
}

; NEGATIVE - WRONG SHUFFLE VECTOR
define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_wrong_shuffle_vector(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; CHECK-LABEL: define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_wrong_shuffle_vector(
; CHECK-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[XOR_A:%.*]] = xor <4 x i32> [[A]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; CHECK-NEXT:    [[XOR_B:%.*]] = xor <4 x i32> [[B]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; CHECK-NEXT:    [[GT:%.*]] = icmp sgt <4 x i32> [[XOR_B]], [[XOR_A]]
; CHECK-NEXT:    [[SEXT_GT:%.*]] = sext <4 x i1> [[GT]] to <4 x i32>
; CHECK-NEXT:    [[GT_1:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; CHECK-NEXT:    [[EQ:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[TMP1:%.*]] = and <4 x i1> [[GT]], [[EQ]]
; CHECK-NEXT:    [[TMP2:%.*]] = sext <4 x i1> [[TMP1]] to <4 x i32>
; CHECK-NEXT:    [[AND:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; CHECK-NEXT:    [[OR:%.*]] = or <4 x i32> [[AND]], [[GT_1]]
; CHECK-NEXT:    ret <4 x i32> [[OR]]
;
  %xor.a = xor <4 x i32> %a, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %xor.b = xor <4 x i32> %b, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %gt = icmp sgt <4 x i32> %xor.b, %xor.a
  %sext.gt = sext <4 x i1> %gt to <4 x i32>
  %gt.0 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %gt.1 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %eq = icmp eq <4 x i32> %a, %b
  %sext.eq = sext <4 x i1> %eq to <4 x i32>
  %eq.0 = shufflevector <4 x i32> %sext.eq, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %and = and <4 x i32> %gt.0, %eq.0
  %or = or <4 x i32> %and, %gt.1
  ret <4 x i32> %or
}

; NEGATIVE - WRONG AND / OR ARGUMENTS
define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_wrong_and_or_args(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; CHECK-LABEL: define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_wrong_and_or_args(
; CHECK-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[XOR_A:%.*]] = xor <4 x i32> [[A]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; CHECK-NEXT:    [[XOR_B:%.*]] = xor <4 x i32> [[B]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; CHECK-NEXT:    [[GT:%.*]] = icmp sgt <4 x i32> [[XOR_B]], [[XOR_A]]
; CHECK-NEXT:    [[SEXT_GT:%.*]] = sext <4 x i1> [[GT]] to <4 x i32>
; CHECK-NEXT:    [[GT_0:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; CHECK-NEXT:    [[EQ:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[TMP1:%.*]] = and <4 x i1> [[GT]], [[EQ]]
; CHECK-NEXT:    [[TMP2:%.*]] = sext <4 x i1> [[TMP1]] to <4 x i32>
; CHECK-NEXT:    [[AND:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; CHECK-NEXT:    [[OR:%.*]] = or <4 x i32> [[AND]], [[GT_0]]
; CHECK-NEXT:    ret <4 x i32> [[OR]]
;
  %xor.a = xor <4 x i32> %a, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %xor.b = xor <4 x i32> %b, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %gt = icmp sgt <4 x i32> %xor.b, %xor.a
  %sext.gt = sext <4 x i1> %gt to <4 x i32>
  %gt.0 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %gt.1 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %eq = icmp eq <4 x i32> %a, %b
  %sext.eq = sext <4 x i1> %eq to <4 x i32>
  %eq.0 = shufflevector <4 x i32> %sext.eq, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %and = and <4 x i32> %gt.1, %eq.0
  %or = or <4 x i32> %and, %gt.0
  ret <4 x i32> %or
}

; NEGATIVE - UNSIGNED GREATER THAN - WRONG XOR MASK
define <4 x i32> @icmp_ugt_v2i64_using_v4i32_with_wrong_xor_mask(<4 x i32> noundef %a, <4 x i32> noundef %b) {
; CHECK-LABEL: define <4 x i32> @icmp_ugt_v2i64_using_v4i32_with_wrong_xor_mask(
; CHECK-SAME: <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[XOR_A:%.*]] = xor <4 x i32> [[A]], <i32 0, i32 -2147483648, i32 -2147483648, i32 -2147483648>
; CHECK-NEXT:    [[XOR_B:%.*]] = xor <4 x i32> [[B]], splat (i32 -2147483648)
; CHECK-NEXT:    [[GT:%.*]] = icmp sgt <4 x i32> [[XOR_A]], [[XOR_B]]
; CHECK-NEXT:    [[SEXT_GT:%.*]] = sext <4 x i1> [[GT]] to <4 x i32>
; CHECK-NEXT:    [[GT_0:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; CHECK-NEXT:    [[GT_1:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; CHECK-NEXT:    [[EQ:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[SEXT_EQ:%.*]] = sext <4 x i1> [[EQ]] to <4 x i32>
; CHECK-NEXT:    [[EQ_0:%.*]] = shufflevector <4 x i32> [[SEXT_EQ]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; CHECK-NEXT:    [[AND:%.*]] = and <4 x i32> [[GT_0]], [[EQ_0]]
; CHECK-NEXT:    [[OR:%.*]] = or <4 x i32> [[AND]], [[GT_1]]
; CHECK-NEXT:    ret <4 x i32> [[OR]]
;
  %xor.a = xor <4 x i32> %a, <i32 0, i32 -2147483648, i32 -2147483648, i32 -2147483648>
  %xor.b = xor <4 x i32> %b, <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648>
  %gt = icmp sgt <4 x i32> %xor.a, %xor.b
  %sext.gt = sext <4 x i1> %gt to <4 x i32>
  %gt.0 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %gt.1 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %eq = icmp eq <4 x i32> %a, %b
  %sext.eq = sext <4 x i1> %eq to <4 x i32>
  %eq.0 = shufflevector <4 x i32> %sext.eq, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %and = and <4 x i32> %gt.0, %eq.0
  %or = or <4 x i32> %and, %gt.1
  ret <4 x i32> %or
}

; NEGATIVE - POSSIBLY POISONED INPUT USING SELECT
define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_possibly_poisoned_input_using_select(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_possibly_poisoned_input_using_select(
; CHECK-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]]) {
; CHECK-NEXT:    [[XOR_A:%.*]] = xor <4 x i32> [[A]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; CHECK-NEXT:    [[XOR_B:%.*]] = xor <4 x i32> [[B]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; CHECK-NEXT:    [[GT:%.*]] = icmp sgt <4 x i32> [[XOR_A]], [[XOR_B]]
; CHECK-NEXT:    [[SEXT_GT:%.*]] = sext <4 x i1> [[GT]] to <4 x i32>
; CHECK-NEXT:    [[GT_0:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; CHECK-NEXT:    [[GT_1:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; CHECK-NEXT:    [[EQ:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[EQ_0:%.*]] = shufflevector <4 x i1> [[EQ]], <4 x i1> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; CHECK-NEXT:    [[SELECT:%.*]] = select <4 x i1> [[EQ_0]], <4 x i32> [[GT_0]], <4 x i32> zeroinitializer
; CHECK-NEXT:    [[OR:%.*]] = or <4 x i32> [[SELECT]], [[GT_1]]
; CHECK-NEXT:    ret <4 x i32> [[OR]]
;
  %xor.a = xor <4 x i32> %a, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %xor.b = xor <4 x i32> %b, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %gt = icmp sgt <4 x i32> %xor.a, %xor.b
  %sext.gt = sext <4 x i1> %gt to <4 x i32>
  %gt.0 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %gt.1 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %eq = icmp eq <4 x i32> %a, %b
  %eq.0 = shufflevector <4 x i1> %eq, <4 x i1> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %select = select <4 x i1> %eq.0, <4 x i32> %gt.0, <4 x i32> zeroinitializer
  %or = or <4 x i32> %select, %gt.1
  ret <4 x i32> %or
}

; POSITIVE - POSSIBLY POISONED INPUT USING AND
define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_possibly_poisoned_input_using_and(<4 x i32> %a, <4 x i32> %b) {
; LITTLE-LABEL: define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_possibly_poisoned_input_using_and(
; LITTLE-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]]) {
; LITTLE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A]] to <2 x i64>
; LITTLE-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[B]] to <2 x i64>
; LITTLE-NEXT:    [[TMP3:%.*]] = icmp sgt <2 x i64> [[TMP1]], [[TMP2]]
; LITTLE-NEXT:    [[TMP4:%.*]] = sext <2 x i1> [[TMP3]] to <2 x i64>
; LITTLE-NEXT:    [[OR:%.*]] = bitcast <2 x i64> [[TMP4]] to <4 x i32>
; LITTLE-NEXT:    ret <4 x i32> [[OR]]
;
; BIG-LABEL: define <4 x i32> @icmp_sgt_v2i64_using_v4i32_with_possibly_poisoned_input_using_and(
; BIG-SAME: <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]]) {
; BIG-NEXT:    [[XOR_A:%.*]] = xor <4 x i32> [[A]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[XOR_B:%.*]] = xor <4 x i32> [[B]], <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
; BIG-NEXT:    [[GT:%.*]] = icmp sgt <4 x i32> [[XOR_A]], [[XOR_B]]
; BIG-NEXT:    [[SEXT_GT:%.*]] = sext <4 x i1> [[GT]] to <4 x i32>
; BIG-NEXT:    [[GT_0:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
; BIG-NEXT:    [[GT_1:%.*]] = shufflevector <4 x i32> [[SEXT_GT]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[EQ:%.*]] = icmp eq <4 x i32> [[A]], [[B]]
; BIG-NEXT:    [[SEXT_EQ:%.*]] = sext <4 x i1> [[EQ]] to <4 x i32>
; BIG-NEXT:    [[EQ_0:%.*]] = shufflevector <4 x i32> [[SEXT_EQ]], <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
; BIG-NEXT:    [[AND:%.*]] = and <4 x i32> [[GT_0]], [[EQ_0]]
; BIG-NEXT:    [[OR:%.*]] = or <4 x i32> [[AND]], [[GT_1]]
; BIG-NEXT:    ret <4 x i32> [[OR]]
;
  %xor.a = xor <4 x i32> %a, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %xor.b = xor <4 x i32> %b, <i32 -2147483648, i32 0, i32 -2147483648, i32 0>
  %gt = icmp sgt <4 x i32> %xor.a, %xor.b
  %sext.gt = sext <4 x i1> %gt to <4 x i32>
  %gt.0 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 2, i32 2>
  %gt.1 = shufflevector <4 x i32> %sext.gt, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %eq = icmp eq <4 x i32> %a, %b
  %sext.eq = sext <4 x i1> %eq to <4 x i32>
  %eq.0 = shufflevector <4 x i32> %sext.eq, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 3, i32 3>
  %and = and <4 x i32> %gt.0, %eq.0
  %or = or <4 x i32> %and, %gt.1
  ret <4 x i32> %or
}
