; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=instcombine %s | FileCheck %s
;
; Test that FP intrinsics carrying fp.control / fp.except operand bundles
; are treated as having FP-environment side effects by InstCombine even when
; the enclosing function does NOT have the 'strictfp' attribute.
;
; The inputs use the legacy experimental.constrained.* form so that the
; assembler auto-upgrades them to the new bundle-based form before
; InstCombine runs.  The enclosing functions deliberately lack 'strictfp'.
;
; Key expected behaviors (DCE of unused results):
;   ebStrict  (default; no fp.except bundle) - call must be preserved.
;   ebMayTrap (fp.except="maytrap")          - call may be removed when unused.
;   ebIgnore  + explicit RM                  - call may be removed when unused.
;   ebIgnore  + dynamic RM                   - call may be removed when unused.

; ---------------------------------------------------------------------------
; Strict exception mode: unused result must not be DCE'd.
; The operation may raise an observable FP exception.
; ---------------------------------------------------------------------------

define float @unused_strict() {
; CHECK-LABEL: @unused_strict(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.fdiv.f32(float 1.000000e+00, float 3.000000e+00) [ "fp.control"(metadata !"rte") ]
; CHECK-NEXT:    ret float 1.000000e+00
;
entry:
  %r = call float @llvm.experimental.constrained.fdiv.f32(float 1.0, float 3.0, metadata !"round.tonearest", metadata !"fpexcept.strict")
  ret float 1.0
}

; ---------------------------------------------------------------------------
; Maytrap mode: unused result may be DCE'd (optional exception).
; ---------------------------------------------------------------------------

define float @unused_maytrap() {
; CHECK-LABEL: @unused_maytrap(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    ret float 1.000000e+00
;
entry:
  %r = call float @llvm.experimental.constrained.fdiv.f32(float 1.0, float 3.0, metadata !"round.tonearest", metadata !"fpexcept.maytrap")
  ret float 1.0
}

; ---------------------------------------------------------------------------
; Ignore mode + explicit rounding mode: no FP-env interaction, freely removed.
; ---------------------------------------------------------------------------

define float @unused_ignore_rte() {
; CHECK-LABEL: @unused_ignore_rte(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    ret float 1.000000e+00
;
entry:
  %r = call float @llvm.experimental.constrained.fdiv.f32(float 1.0, float 3.0, metadata !"round.tonearest", metadata !"fpexcept.ignore")
  ret float 1.0
}

define float @unused_ignore_rtp() {
; CHECK-LABEL: @unused_ignore_rtp(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    ret float 1.000000e+00
;
entry:
  %r = call float @llvm.experimental.constrained.fdiv.f32(float 1.0, float 3.0, metadata !"round.upward", metadata !"fpexcept.ignore")
  ret float 1.0
}

; ---------------------------------------------------------------------------
; Ignore mode + dynamic rounding mode: reads the FP env but result is unused;
; may still be DCE'd because no exception flag is written.
; ---------------------------------------------------------------------------

define float @unused_ignore_dyn() {
; CHECK-LABEL: @unused_ignore_dyn(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    ret float 1.000000e+00
;
entry:
  %r = call float @llvm.experimental.constrained.fdiv.f32(float 1.0, float 3.0, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret float 1.0
}

; ---------------------------------------------------------------------------
; Used results: verify the call is preserved and the value is returned.
; ---------------------------------------------------------------------------

; Strict, explicit RM: call preserved; result used directly.
define float @used_strict() {
; CHECK-LABEL: @used_strict(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.fdiv.f32(float 1.000000e+00, float 3.000000e+00) [ "fp.control"(metadata !"rtp") ]
; CHECK-NEXT:    ret float [[R]]
;
entry:
  %r = call float @llvm.experimental.constrained.fdiv.f32(float 1.0, float 3.0, metadata !"round.upward", metadata !"fpexcept.strict")
  ret float %r
}

; Ignore, explicit RM: imprecise result is constant-folded; call removed.
define float @used_ignore_folds() {
; CHECK-LABEL: @used_ignore_folds(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    ret float 0x3FD5555540000000
;
entry:
  %r = call float @llvm.experimental.constrained.fdiv.f32(float 1.0, float 3.0, metadata !"round.downward", metadata !"fpexcept.ignore")
  ret float %r
}

; Strict, imprecise: call preserved; result cannot be constant-folded.
define float @used_strict_imprecise() {
; CHECK-LABEL: @used_strict_imprecise(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.fdiv.f32(float 1.000000e+00, float 3.000000e+00) [ "fp.control"(metadata !"rtp") ]
; CHECK-NEXT:    ret float [[R]]
;
entry:
  %r = call float @llvm.experimental.constrained.fdiv.f32(float 1.0, float 3.0, metadata !"round.upward", metadata !"fpexcept.strict")
  ret float %r
}

; Maytrap, explicit RM: call preserved (side effect); result constant-folded.
define float @used_maytrap_folds() {
; CHECK-LABEL: @used_maytrap_folds(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.fdiv.f32(float 1.000000e+00, float 3.000000e+00) [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
; CHECK-NEXT:    ret float 0x3FD5555560000000
;
entry:
  %r = call float @llvm.experimental.constrained.fdiv.f32(float 1.0, float 3.0, metadata !"round.tonearest", metadata !"fpexcept.maytrap")
  ret float %r
}

declare float @llvm.experimental.constrained.fdiv.f32(float, float, metadata, metadata)
