; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; fptoui (fdiv (uitofp X), C) -> udiv X, C
; Sound when C >= 1 and N <= p (N = integer width, p = FP mantissa width).

define i32 @i32_double_const(i32 %x) {
; CHECK-LABEL: define i32 @i32_double_const(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = udiv i32 [[X]], 7
; CHECK-NEXT:    ret i32 [[R]]
;
  %a = uitofp i32 %x to double
  %d = fdiv double %a, 7.000000e+00
  %r = fptoui double %d to i32
  ret i32 %r
}

define i16 @i16_float_const(i16 %x) {
; CHECK-LABEL: define i16 @i16_float_const(
; CHECK-SAME: i16 [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = udiv i16 [[X]], 3
; CHECK-NEXT:    ret i16 [[R]]
;
  %a = uitofp i16 %x to float
  %d = fdiv float %a, 3.000000e+00
  %r = fptoui float %d to i16
  ret i16 %r
}

define <2 x i32> @vec_i32_double_const(<2 x i32> %x) {
; CHECK-LABEL: define <2 x i32> @vec_i32_double_const(
; CHECK-SAME: <2 x i32> [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = udiv <2 x i32> [[X]], splat (i32 7)
; CHECK-NEXT:    ret <2 x i32> [[R]]
;
  %a = uitofp <2 x i32> %x to <2 x double>
  %d = fdiv <2 x double> %a, splat (double 7.000000e+00)
  %r = fptoui <2 x double> %d to <2 x i32>
  ret <2 x i32> %r
}

define i32 @divisor_one(i32 %x) {
; CHECK-LABEL: define i32 @divisor_one(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    ret i32 [[X]]
;
  %a = uitofp i32 %x to double
  %d = fdiv double %a, 1.000000e+00
  %r = fptoui double %d to i32
  ret i32 %r
}

define i64 @i64_double_not_exact(i64 %x) {
; CHECK-LABEL: define i64 @i64_double_not_exact(
; CHECK-SAME: i64 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = uitofp i64 [[X]] to double
; CHECK-NEXT:    [[D:%.*]] = fdiv double [[A]], 7.000000e+00
; CHECK-NEXT:    [[R:%.*]] = fptoui double [[D]] to i64
; CHECK-NEXT:    ret i64 [[R]]
;
  %a = uitofp i64 %x to double
  %d = fdiv double %a, 7.000000e+00
  %r = fptoui double %d to i64
  ret i64 %r
}

define i32 @i32_float_not_exact(i32 %x) {
; CHECK-LABEL: define i32 @i32_float_not_exact(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = uitofp i32 [[X]] to float
; CHECK-NEXT:    [[D:%.*]] = fdiv float [[A]], 7.000000e+00
; CHECK-NEXT:    [[R:%.*]] = fptoui float [[D]] to i32
; CHECK-NEXT:    ret i32 [[R]]
;
  %a = uitofp i32 %x to float
  %d = fdiv float %a, 7.000000e+00
  %r = fptoui float %d to i32
  ret i32 %r
}

define i32 @fractional_divisor(i32 %x) {
; CHECK-LABEL: define i32 @fractional_divisor(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = uitofp i32 [[X]] to double
; CHECK-NEXT:    [[D:%.*]] = fdiv double [[A]], 2.500000e+00
; CHECK-NEXT:    [[R:%.*]] = fptoui double [[D]] to i32
; CHECK-NEXT:    ret i32 [[R]]
;
  %a = uitofp i32 %x to double
  %d = fdiv double %a, 2.500000e+00
  %r = fptoui double %d to i32
  ret i32 %r
}

define i32 @zero_divisor(i32 %x) {
; CHECK-LABEL: define i32 @zero_divisor(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = uitofp i32 [[X]] to double
; CHECK-NEXT:    [[D:%.*]] = fdiv double [[A]], 0.000000e+00
; CHECK-NEXT:    [[R:%.*]] = fptoui double [[D]] to i32
; CHECK-NEXT:    ret i32 [[R]]
;
  %a = uitofp i32 %x to double
  %d = fdiv double %a, 0.000000e+00
  %r = fptoui double %d to i32
  ret i32 %r
}

define i64 @width_mismatch(i32 %x) {
; CHECK-LABEL: define i64 @width_mismatch(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = uitofp i32 [[X]] to double
; CHECK-NEXT:    [[D:%.*]] = fdiv double [[A]], 7.000000e+00
; CHECK-NEXT:    [[R:%.*]] = fptoui double [[D]] to i64
; CHECK-NEXT:    ret i64 [[R]]
;
  %a = uitofp i32 %x to double
  %d = fdiv double %a, 7.000000e+00
  %r = fptoui double %d to i64
  ret i64 %r
}

define i32 @variable_divisor(i32 %x, i32 %y) {
; CHECK-LABEL: define i32 @variable_divisor(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = uitofp i32 [[X]] to double
; CHECK-NEXT:    [[B:%.*]] = uitofp i32 [[Y]] to double
; CHECK-NEXT:    [[D:%.*]] = fdiv double [[A]], [[B]]
; CHECK-NEXT:    [[R:%.*]] = fptoui double [[D]] to i32
; CHECK-NEXT:    ret i32 [[R]]
;
  %a = uitofp i32 %x to double
  %b = uitofp i32 %y to double
  %d = fdiv double %a, %b
  %r = fptoui double %d to i32
  ret i32 %r
}

define i32 @signed_source(i32 %x) {
; CHECK-LABEL: define i32 @signed_source(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = sitofp i32 [[X]] to double
; CHECK-NEXT:    [[D:%.*]] = fdiv double [[A]], 7.000000e+00
; CHECK-NEXT:    [[R:%.*]] = fptoui double [[D]] to i32
; CHECK-NEXT:    ret i32 [[R]]
;
  %a = sitofp i32 %x to double
  %d = fdiv double %a, 7.000000e+00
  %r = fptoui double %d to i32
  ret i32 %r
}

define i32 @overflow_divisor(i32 %x) {
; CHECK-LABEL: define i32 @overflow_divisor(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = uitofp i32 [[X]] to double
; CHECK-NEXT:    [[D:%.*]] = fdiv double [[A]], f0x4202A05F1FF80000
; CHECK-NEXT:    [[R:%.*]] = fptoui double [[D]] to i32
; CHECK-NEXT:    ret i32 [[R]]
;
  %a = uitofp i32 %x to double
  %d = fdiv double %a, 9999999999.0
  %r = fptoui double %d to i32
  ret i32 %r
}

define i128 @ppc_fp128_unknown_precision(i128 %x) {
; CHECK-LABEL: define i128 @ppc_fp128_unknown_precision(
; CHECK-SAME: i128 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = uitofp i128 [[X]] to ppc_fp128
; CHECK-NEXT:    [[D:%.*]] = fdiv ppc_fp128 [[A]], 7.000000e+00
; CHECK-NEXT:    [[R:%.*]] = fptoui ppc_fp128 [[D]] to i128
; CHECK-NEXT:    ret i128 [[R]]
;
  %a = uitofp i128 %x to ppc_fp128
  %d = fdiv ppc_fp128 %a, 7.000000e+00
  %r = fptoui ppc_fp128 %d to i128
  ret i128 %r
}

; Unsound when N(=32) > p(=24) even if %x canBeCastedExactlyIntToFP (%x mod 256 = 0).
define i32 @unsound_i32_float_shifted(i24 %a) {
; CHECK-LABEL: define i32 @unsound_i32_float_shifted(
; CHECK-SAME: i24 [[A:%.*]]) {
; CHECK-NEXT:    [[Z:%.*]] = zext i24 [[A]] to i32
; CHECK-NEXT:    [[X:%.*]] = shl nuw i32 [[Z]], 8
; CHECK-NEXT:    [[F:%.*]] = uitofp i32 [[X]] to float
; CHECK-NEXT:    [[D:%.*]] = fdiv float [[F]], 3.000000e+00
; CHECK-NEXT:    [[R:%.*]] = fptoui float [[D]] to i32
; CHECK-NEXT:    ret i32 [[R]]
;
  %z = zext i24 %a to i32
  %x = shl i32 %z, 8
  %f = uitofp i32 %x to float
  %d = fdiv float %f, 3.000000e+00
  %r = fptoui float %d to i32
  ret i32 %r
}
