; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; Fold select (fcmp uno/ord X, 0), 0, (fptosi/fptoui X) -> fptosi.sat/fptoui.sat(X)
; fptosi.sat returns 0 for NaN, matching the select's behavior.
; Also fold when the conversion result is AND-masked.

;; Positive tests

define i32 @nan_guard_fptosi_uno_f32(float %x) {
; CHECK-LABEL: @nan_guard_fptosi_uno_f32(
; CHECK-NEXT:    [[SEL:%.*]] = call i32 @llvm.fptosi.sat.i32.f32(float [[X:%.*]])
; CHECK-NEXT:    ret i32 [[SEL]]
;
  %cmp = fcmp uno float %x, 0.000000e+00
  %conv = fptosi float %x to i32
  %sel = select i1 %cmp, i32 0, i32 %conv
  ret i32 %sel
}

define i32 @nan_guard_fptosi_ord_f32(float %x) {
; CHECK-LABEL: @nan_guard_fptosi_ord_f32(
; CHECK-NEXT:    [[SEL:%.*]] = call i32 @llvm.fptosi.sat.i32.f32(float [[X:%.*]])
; CHECK-NEXT:    ret i32 [[SEL]]
;
  %cmp = fcmp ord float %x, 0.000000e+00
  %conv = fptosi float %x to i32
  %sel = select i1 %cmp, i32 %conv, i32 0
  ret i32 %sel
}

define i32 @nan_guard_fptoui_uno_f32(float %x) {
; CHECK-LABEL: @nan_guard_fptoui_uno_f32(
; CHECK-NEXT:    [[SEL:%.*]] = call i32 @llvm.fptoui.sat.i32.f32(float [[X:%.*]])
; CHECK-NEXT:    ret i32 [[SEL]]
;
  %cmp = fcmp uno float %x, 0.000000e+00
  %conv = fptoui float %x to i32
  %sel = select i1 %cmp, i32 0, i32 %conv
  ret i32 %sel
}

define i32 @nan_guard_fptoui_ord_f32(float %x) {
; CHECK-LABEL: @nan_guard_fptoui_ord_f32(
; CHECK-NEXT:    [[SEL:%.*]] = call i32 @llvm.fptoui.sat.i32.f32(float [[X:%.*]])
; CHECK-NEXT:    ret i32 [[SEL]]
;
  %cmp = fcmp ord float %x, 0.000000e+00
  %conv = fptoui float %x to i32
  %sel = select i1 %cmp, i32 %conv, i32 0
  ret i32 %sel
}

define i32 @nan_guard_fptosi_and_mask(float %x) {
; CHECK-LABEL: @nan_guard_fptosi_and_mask(
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fptosi.sat.i32.f32(float [[X:%.*]])
; CHECK-NEXT:    [[SEL:%.*]] = and i32 [[TMP1]], 3
; CHECK-NEXT:    ret i32 [[SEL]]
;
  %cmp = fcmp uno float %x, 0.000000e+00
  %conv = fptosi float %x to i32
  %and = and i32 %conv, 3
  %sel = select i1 %cmp, i32 0, i32 %and
  ret i32 %sel
}

define i32 @nan_guard_fptoui_and_mask(float %x) {
; CHECK-LABEL: @nan_guard_fptoui_and_mask(
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fptoui.sat.i32.f32(float [[X:%.*]])
; CHECK-NEXT:    [[SEL:%.*]] = and i32 [[TMP1]], 7
; CHECK-NEXT:    ret i32 [[SEL]]
;
  %cmp = fcmp uno float %x, 0.000000e+00
  %conv = fptoui float %x to i32
  %and = and i32 %conv, 7
  %sel = select i1 %cmp, i32 0, i32 %and
  ret i32 %sel
}

define i32 @nan_guard_fptosi_f64(double %x) {
; CHECK-LABEL: @nan_guard_fptosi_f64(
; CHECK-NEXT:    [[SEL:%.*]] = call i32 @llvm.fptosi.sat.i32.f64(double [[X:%.*]])
; CHECK-NEXT:    ret i32 [[SEL]]
;
  %cmp = fcmp uno double %x, 0.000000e+00
  %conv = fptosi double %x to i32
  %sel = select i1 %cmp, i32 0, i32 %conv
  ret i32 %sel
}

define i16 @nan_guard_fptosi_i16(float %x) {
; CHECK-LABEL: @nan_guard_fptosi_i16(
; CHECK-NEXT:    [[SEL:%.*]] = call i16 @llvm.fptosi.sat.i16.f32(float [[X:%.*]])
; CHECK-NEXT:    ret i16 [[SEL]]
;
  %cmp = fcmp uno float %x, 0.000000e+00
  %conv = fptosi float %x to i16
  %sel = select i1 %cmp, i16 0, i16 %conv
  ret i16 %sel
}

define <4 x i32> @nan_guard_fptosi_vec(<4 x float> %x) {
; CHECK-LABEL: @nan_guard_fptosi_vec(
; CHECK-NEXT:    [[SEL:%.*]] = call <4 x i32> @llvm.fptosi.sat.v4i32.v4f32(<4 x float> [[X:%.*]])
; CHECK-NEXT:    ret <4 x i32> [[SEL]]
;
  %cmp = fcmp uno <4 x float> %x, zeroinitializer
  %conv = fptosi <4 x float> %x to <4 x i32>
  %sel = select <4 x i1> %cmp, <4 x i32> zeroinitializer, <4 x i32> %conv
  ret <4 x i32> %sel
}

; Negative zero on the fcmp RHS should still match.
define i32 @nan_guard_fptosi_negzero(float %x) {
; CHECK-LABEL: @nan_guard_fptosi_negzero(
; CHECK-NEXT:    [[SEL:%.*]] = call i32 @llvm.fptosi.sat.i32.f32(float [[X:%.*]])
; CHECK-NEXT:    ret i32 [[SEL]]
;
  %cmp = fcmp uno float %x, -0.000000e+00
  %conv = fptosi float %x to i32
  %sel = select i1 %cmp, i32 0, i32 %conv
  ret i32 %sel
}

; AND-masked with ord predicate.
define i32 @nan_guard_fptosi_and_mask_ord(float %x) {
; CHECK-LABEL: @nan_guard_fptosi_and_mask_ord(
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fptosi.sat.i32.f32(float [[X:%.*]])
; CHECK-NEXT:    [[SEL:%.*]] = and i32 [[TMP1]], 3
; CHECK-NEXT:    ret i32 [[SEL]]
;
  %cmp = fcmp ord float %x, 0.000000e+00
  %conv = fptosi float %x to i32
  %and = and i32 %conv, 3
  %sel = select i1 %cmp, i32 %and, i32 0
  ret i32 %sel
}

; Vector AND-masked.
define <4 x i32> @nan_guard_fptosi_and_mask_vec(<4 x float> %x) {
; CHECK-LABEL: @nan_guard_fptosi_and_mask_vec(
; CHECK-NEXT:    [[TMP1:%.*]] = call <4 x i32> @llvm.fptosi.sat.v4i32.v4f32(<4 x float> [[X:%.*]])
; CHECK-NEXT:    [[SEL:%.*]] = and <4 x i32> [[TMP1]], splat (i32 3)
; CHECK-NEXT:    ret <4 x i32> [[SEL]]
;
  %cmp = fcmp uno <4 x float> %x, zeroinitializer
  %conv = fptosi <4 x float> %x to <4 x i32>
  %and = and <4 x i32> %conv, <i32 3, i32 3, i32 3, i32 3>
  %sel = select <4 x i1> %cmp, <4 x i32> zeroinitializer, <4 x i32> %and
  ret <4 x i32> %sel
}

; Vector fptoui.
define <4 x i32> @nan_guard_fptoui_vec(<4 x float> %x) {
; CHECK-LABEL: @nan_guard_fptoui_vec(
; CHECK-NEXT:    [[SEL:%.*]] = call <4 x i32> @llvm.fptoui.sat.v4i32.v4f32(<4 x float> [[X:%.*]])
; CHECK-NEXT:    ret <4 x i32> [[SEL]]
;
  %cmp = fcmp uno <4 x float> %x, zeroinitializer
  %conv = fptoui <4 x float> %x to <4 x i32>
  %sel = select <4 x i1> %cmp, <4 x i32> zeroinitializer, <4 x i32> %conv
  ret <4 x i32> %sel
}

; fptosi has multiple uses -- fold should still fire (replaces fcmp+select
; with fptosi.sat, net reduction even though original fptosi stays).
define i32 @nan_guard_fptosi_multi_use(float %x, ptr %p) {
; CHECK-LABEL: @nan_guard_fptosi_multi_use(
; CHECK-NEXT:    [[CONV:%.*]] = fptosi float [[X:%.*]] to i32
; CHECK-NEXT:    store i32 [[CONV]], ptr [[P:%.*]], align 4
; CHECK-NEXT:    [[SEL:%.*]] = call i32 @llvm.fptosi.sat.i32.f32(float [[X]])
; CHECK-NEXT:    ret i32 [[SEL]]
;
  %cmp = fcmp uno float %x, 0.000000e+00
  %conv = fptosi float %x to i32
  store i32 %conv, ptr %p
  %sel = select i1 %cmp, i32 0, i32 %conv
  ret i32 %sel
}

; AND has multiple uses -- fold should still fire (same reasoning).
define i32 @nan_guard_and_multi_use(float %x, ptr %p) {
; CHECK-LABEL: @nan_guard_and_multi_use(
; CHECK-NEXT:    [[CONV:%.*]] = fptosi float [[X:%.*]] to i32
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[CONV]], 3
; CHECK-NEXT:    store i32 [[AND]], ptr [[P:%.*]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fptosi.sat.i32.f32(float [[X]])
; CHECK-NEXT:    [[SEL:%.*]] = and i32 [[TMP1]], 3
; CHECK-NEXT:    ret i32 [[SEL]]
;
  %cmp = fcmp uno float %x, 0.000000e+00
  %conv = fptosi float %x to i32
  %and = and i32 %conv, 3
  store i32 %and, ptr %p
  %sel = select i1 %cmp, i32 0, i32 %and
  ret i32 %sel
}

;; Negative tests

define i32 @nan_guard_nonzero_nan_arm(float %x) {
; CHECK-LABEL: @nan_guard_nonzero_nan_arm(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp uno float [[X:%.*]], 0.000000e+00
; CHECK-NEXT:    [[CONV:%.*]] = fptosi float [[X]] to i32
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], i32 42, i32 [[CONV]]
; CHECK-NEXT:    ret i32 [[SEL]]
;
  %cmp = fcmp uno float %x, 0.000000e+00
  %conv = fptosi float %x to i32
  %sel = select i1 %cmp, i32 42, i32 %conv
  ret i32 %sel
}

define i32 @nan_guard_mismatched_operands(float %x, float %y) {
; CHECK-LABEL: @nan_guard_mismatched_operands(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp uno float [[X:%.*]], 0.000000e+00
; CHECK-NEXT:    [[CONV:%.*]] = fptosi float [[Y:%.*]] to i32
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], i32 0, i32 [[CONV]]
; CHECK-NEXT:    ret i32 [[SEL]]
;
  %cmp = fcmp uno float %x, 0.000000e+00
  %conv = fptosi float %y to i32
  %sel = select i1 %cmp, i32 0, i32 %conv
  ret i32 %sel
}

define i32 @nan_guard_wrong_predicate(float %x) {
; CHECK-LABEL: @nan_guard_wrong_predicate(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq float [[X:%.*]], 0.000000e+00
; CHECK-NEXT:    [[CONV:%.*]] = fptosi float [[X]] to i32
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], i32 0, i32 [[CONV]]
; CHECK-NEXT:    ret i32 [[SEL]]
;
  %cmp = fcmp oeq float %x, 0.000000e+00
  %conv = fptosi float %x to i32
  %sel = select i1 %cmp, i32 0, i32 %conv
  ret i32 %sel
}

define i32 @nan_guard_uno_wrong_arm(float %x) {
; CHECK-LABEL: @nan_guard_uno_wrong_arm(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp uno float [[X:%.*]], 0.000000e+00
; CHECK-NEXT:    [[CONV:%.*]] = fptosi float [[X]] to i32
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], i32 [[CONV]], i32 0
; CHECK-NEXT:    ret i32 [[SEL]]
;
  %cmp = fcmp uno float %x, 0.000000e+00
  %conv = fptosi float %x to i32
  %sel = select i1 %cmp, i32 %conv, i32 0
  ret i32 %sel
}
