; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

target datalayout = "e-p:64:64:64-p1:64:64:64:32-i8:8:8-i16:16:16-i32:32:32-i64:64:64"

@g = global [6 x i64] zeroinitializer, align 16
@g_as1_large = external addrspace(1) global [3000000000 x i8]

define ptr @freeze_gep_inbounds_global() {
; CHECK-LABEL: @freeze_gep_inbounds_global(
; CHECK-NEXT:    ret ptr getelementptr inbounds nuw (i8, ptr @g, i64 8)
;
  %fr = freeze ptr getelementptr inbounds (i8, ptr @g, i64 8)
  ret ptr %fr
}

define ptr @freeze_gep_inbounds_alloca() {
; CHECK-LABEL: @freeze_gep_inbounds_alloca(
; CHECK-NEXT:    [[A:%.*]] = alloca [32 x i8], align 1
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 16
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %a = alloca [32 x i8], align 1
  %gep = getelementptr inbounds i8, ptr %a, i64 16
  %fr = freeze ptr %gep
  ret ptr %fr
}

define ptr @freeze_gep_inbounds_global_boundary() {
; CHECK-LABEL: @freeze_gep_inbounds_global_boundary(
; CHECK-NEXT:    ret ptr getelementptr inbounds nuw (i8, ptr @g, i64 48)
;
  %fr = freeze ptr getelementptr inbounds (i8, ptr @g, i64 48)
  ret ptr %fr
}

define ptr @freeze_gep_inbounds_global_oob() {
; CHECK-LABEL: @freeze_gep_inbounds_global_oob(
; CHECK-NEXT:    [[FR:%.*]] = freeze ptr getelementptr inbounds nuw (i8, ptr @g, i64 49)
; CHECK-NEXT:    ret ptr [[FR]]
;
  %fr = freeze ptr getelementptr inbounds (i8, ptr @g, i64 49)
  ret ptr %fr
}

define ptr @freeze_gep_inbounds_global_negative() {
; CHECK-LABEL: @freeze_gep_inbounds_global_negative(
; CHECK-NEXT:    [[FR:%.*]] = freeze ptr getelementptr inbounds (i8, ptr @g, i64 -1)
; CHECK-NEXT:    ret ptr [[FR]]
;
  %fr = freeze ptr getelementptr inbounds (i8, ptr @g, i64 -1)
  ret ptr %fr
}

define ptr addrspace(1) @freeze_gep_inbounds_as1_truncation_violation() {
; CHECK-LABEL: @freeze_gep_inbounds_as1_truncation_violation(
; CHECK-NEXT:    [[FR:%.*]] = freeze ptr addrspace(1) getelementptr inbounds (i8, ptr addrspace(1) @g_as1_large, i32 -2094967296)
; CHECK-NEXT:    ret ptr addrspace(1) [[FR]]
;
  %fr = freeze ptr addrspace(1) getelementptr inbounds
  (i8, ptr addrspace(1) @g_as1_large, i64 2200000000)
  ret ptr addrspace(1) %fr
}

define ptr @freeze_gep_inbounds_alloca_variable_offset(i64 %n) {
; CHECK-LABEL: @freeze_gep_inbounds_alloca_variable_offset(
; CHECK-NEXT:    [[A:%.*]] = alloca [32 x i8], align 1
; CHECK-NEXT:    [[N_FR:%.*]] = freeze i64 [[N:%.*]]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[A]], i64 [[N_FR]]
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %a = alloca [32 x i8], align 1
  %gep = getelementptr inbounds i8, ptr %a, i64 %n
  %fr = freeze ptr %gep
  ret ptr %fr
}

define <4 x ptr> @freeze_gep_inbounds_alloca_splat_poison() {
; CHECK-LABEL: @freeze_gep_inbounds_alloca_splat_poison(
; CHECK-NEXT:    [[A:%.*]] = alloca [32 x i8], align 1
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 8
; CHECK-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <4 x ptr> poison, ptr [[GEP1]], i64 0
; CHECK-NEXT:    [[FR:%.*]] = shufflevector <4 x ptr> [[DOTSPLATINSERT]], <4 x ptr> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    ret <4 x ptr> [[FR]]
;
  %a = alloca [32 x i8], align 1
  %gep = getelementptr inbounds i8, ptr %a, <4 x i64> <i64 8, i64 poison, i64 8, i64 8>
  %fr = freeze <4 x ptr> %gep
  ret <4 x ptr> %fr
}
