; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

declare void @use(i8)

define i1 @icmp_eq_srem_mul(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_mul(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = srem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[TMP1]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, %z
  %b = mul nsw i8 %y, %z
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_mul_commuted1(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_mul_commuted1(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = srem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[TMP1]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %z, %x
  %b = mul nsw i8 %y, %z
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_mul_commuted2(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_mul_commuted2(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = srem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[TMP1]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, %z
  %b = mul nsw i8 %z, %y
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_mul_commuted3(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_mul_commuted3(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = srem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[TMP1]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %z, %x
  %b = mul nsw i8 %z, %y
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_mul_multi_use(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_mul_multi_use(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nsw i8 [[X]], [[Z]]
; CHECK-NEXT:    call void @use(i8 [[A]])
; CHECK-NEXT:    [[B:%.*]] = mul nsw i8 [[Y]], [[Z]]
; CHECK-NEXT:    call void @use(i8 [[B]])
; CHECK-NEXT:    [[R:%.*]] = srem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, %z
  call void @use(i8 %a)
  %b = mul nsw i8 %y, %z
  call void @use(i8 %b)
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_ne_srem_mul(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_ne_srem_mul(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = srem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp ne i8 [[TMP1]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, %z
  %b = mul nsw i8 %y, %z
  %r = srem i8 %a, %b
  %c = icmp ne i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_mul_const1(i8 %x, i8 %y) {
; CHECK-LABEL: define i1 @icmp_eq_srem_mul_const1(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, -2
  %b = mul nsw i8 %y, -2
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_mul_const2(i8 %x, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_mul_const2(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i8 [[X]], 3
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, %z
  %b = mul nsw i8 %z, -3
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_mul_const3(i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_mul_const3(
; CHECK-SAME: i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem i8 -3, [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %z, -3
  %b = mul nsw i8 %y, %z
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define <2 x i1> @icmp_eq_srem_mul_vec_splat(<2 x i8> %x, <2 x i8> %y, <2 x i8> %z) {
; CHECK-LABEL: define <2 x i1> @icmp_eq_srem_mul_vec_splat(
; CHECK-SAME: <2 x i8> [[X:%.*]], <2 x i8> [[Y:%.*]], <2 x i8> [[Z:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = srem <2 x i8> [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq <2 x i8> [[R]], zeroinitializer
; CHECK-NEXT:    ret <2 x i1> [[C]]
;
  %a = mul nsw <2 x i8> %x, %z
  %b = mul nsw <2 x i8> %y, %z
  %r = srem <2 x i8> %a, %b
  %c = icmp eq <2 x i8> %r, zeroinitializer
  ret <2 x i1> %c
}

define <2 x i1> @icmp_eq_srem_mul_vec_splat_poison(<2 x i8> %x, <2 x i8> %y, <2 x i8> %z) {
; CHECK-LABEL: define <2 x i1> @icmp_eq_srem_mul_vec_splat_poison(
; CHECK-SAME: <2 x i8> [[X:%.*]], <2 x i8> [[Y:%.*]], <2 x i8> [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nsw <2 x i8> [[X]], [[Z]]
; CHECK-NEXT:    [[B:%.*]] = mul nsw <2 x i8> [[Y]], [[Z]]
; CHECK-NEXT:    [[R:%.*]] = srem <2 x i8> [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq <2 x i8> [[R]], <i8 0, i8 poison>
; CHECK-NEXT:    ret <2 x i1> [[C]]
;
  %a = mul nsw <2 x i8> %x, %z
  %b = mul nsw <2 x i8> %y, %z
  %r = srem <2 x i8> %a, %b
  %c = icmp eq <2 x i8> %r, <i8 0, i8 poison>
  ret <2 x i1> %c
}

define <2 x i1> @icmp_eq_srem_mul_vec_non_splat(<2 x i8> %x, <2 x i8> %y, <2 x i8> %z) {
; CHECK-LABEL: define <2 x i1> @icmp_eq_srem_mul_vec_non_splat(
; CHECK-SAME: <2 x i8> [[X:%.*]], <2 x i8> [[Y:%.*]], <2 x i8> [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nsw <2 x i8> [[X]], [[Z]]
; CHECK-NEXT:    [[B:%.*]] = mul nsw <2 x i8> [[Y]], [[Z]]
; CHECK-NEXT:    [[R:%.*]] = srem <2 x i8> [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq <2 x i8> [[R]], <i8 0, i8 -1>
; CHECK-NEXT:    ret <2 x i1> [[C]]
;
  %a = mul nsw <2 x i8> %x, %z
  %b = mul nsw <2 x i8> %y, %z
  %r = srem <2 x i8> %a, %b
  %c = icmp eq <2 x i8> %r, <i8 0, i8 -1>
  ret <2 x i1> %c
}

define i1 @icmp_eq_srem_mul_negative_flags1(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_mul_negative_flags1(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul i8 [[X]], [[Z]]
; CHECK-NEXT:    [[B:%.*]] = mul nsw i8 [[Y]], [[Z]]
; CHECK-NEXT:    [[R:%.*]] = srem i8 [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul i8 %x, %z
  %b = mul nsw i8 %y, %z
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_mul_negative_flags2(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_mul_negative_flags2(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nsw i8 [[X]], [[Z]]
; CHECK-NEXT:    [[B:%.*]] = mul i8 [[Y]], [[Z]]
; CHECK-NEXT:    [[R:%.*]] = srem i8 [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, %z
  %b = mul i8 %y, %z
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_mul_negative_common_op(i8 %x, i8 %y, i8 %u, i8 %v) {
; CHECK-LABEL: define i1 @icmp_eq_srem_mul_negative_common_op(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[U:%.*]], i8 [[V:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nsw i8 [[X]], [[U]]
; CHECK-NEXT:    [[B:%.*]] = mul nsw i8 [[Y]], [[V]]
; CHECK-NEXT:    [[R:%.*]] = srem i8 [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, %u
  %b = mul nsw i8 %y, %v
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_mul_negative_multi_use(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_mul_negative_multi_use(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nsw i8 [[X]], [[Z]]
; CHECK-NEXT:    [[B:%.*]] = mul nsw i8 [[Y]], [[Z]]
; CHECK-NEXT:    [[R:%.*]] = srem i8 [[A]], [[B]]
; CHECK-NEXT:    call void @use(i8 [[R]])
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, %z
  %b = mul nsw i8 %y, %z
  %r = srem i8 %a, %b
  call void @use(i8 %r)
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_srem_mul_negative_wrong_constant(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_srem_mul_negative_wrong_constant(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nsw i8 [[X]], [[Z]]
; CHECK-NEXT:    [[B:%.*]] = mul nsw i8 [[Y]], [[Z]]
; CHECK-NEXT:    [[R:%.*]] = srem i8 [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], -1
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nsw i8 %x, %z
  %b = mul nsw i8 %y, %z
  %r = srem i8 %a, %b
  %c = icmp eq i8 %r, -1
  ret i1 %c
}

define i1 @icmp_eq_urem_mul(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_urem_mul(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nuw i8 %x, %z
  %b = mul nuw i8 %y, %z
  %r = urem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_urem_mul_commuted1(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_urem_mul_commuted1(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nuw i8 %z, %x
  %b = mul nuw i8 %y, %z
  %r = urem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_urem_mul_commuted2(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_urem_mul_commuted2(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nuw i8 %x, %z
  %b = mul nuw i8 %z, %y
  %r = urem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_urem_mul_commuted3(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_urem_mul_commuted3(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nuw i8 %z, %x
  %b = mul nuw i8 %z, %y
  %r = urem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_urem_mul_multi_use(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_urem_mul_multi_use(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nuw i8 [[X]], [[Z]]
; CHECK-NEXT:    call void @use(i8 [[A]])
; CHECK-NEXT:    [[B:%.*]] = mul nuw i8 [[Y]], [[Z]]
; CHECK-NEXT:    call void @use(i8 [[B]])
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nuw i8 %x, %z
  call void @use(i8 %a)
  %b = mul nuw i8 %y, %z
  call void @use(i8 %b)
  %r = urem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_ne_urem_mul(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_ne_urem_mul(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp ne i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nuw i8 %x, %z
  %b = mul nuw i8 %y, %z
  %r = urem i8 %a, %b
  %c = icmp ne i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_urem_mul_const1(i8 %x, i8 %y) {
; CHECK-LABEL: define i1 @icmp_eq_urem_mul_const1(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nuw i8 %x, 3
  %b = mul nuw i8 %y, 3
  %r = urem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_urem_mul_const2(i8 %x, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_urem_mul_const2(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[X]], 3
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nuw i8 %x, %z
  %b = mul nuw i8 %z, 3
  %r = urem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_urem_mul_const3(i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_urem_mul_const3(
; CHECK-SAME: i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = urem i8 3, [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nuw i8 %z, 3
  %b = mul nuw i8 %y, %z
  %r = urem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define <2 x i1> @icmp_eq_urem_mul_vec_splat(<2 x i8> %x, <2 x i8> %y, <2 x i8> %z) {
; CHECK-LABEL: define <2 x i1> @icmp_eq_urem_mul_vec_splat(
; CHECK-SAME: <2 x i8> [[X:%.*]], <2 x i8> [[Y:%.*]], <2 x i8> [[Z:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = urem <2 x i8> [[X]], [[Y]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq <2 x i8> [[R]], zeroinitializer
; CHECK-NEXT:    ret <2 x i1> [[C]]
;
  %a = mul nuw <2 x i8> %x, %z
  %b = mul nuw <2 x i8> %y, %z
  %r = urem <2 x i8> %a, %b
  %c = icmp eq <2 x i8> %r, zeroinitializer
  ret <2 x i1> %c
}

define <2 x i1> @icmp_eq_urem_mul_vec_splat_poison(<2 x i8> %x, <2 x i8> %y, <2 x i8> %z) {
; CHECK-LABEL: define <2 x i1> @icmp_eq_urem_mul_vec_splat_poison(
; CHECK-SAME: <2 x i8> [[X:%.*]], <2 x i8> [[Y:%.*]], <2 x i8> [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nuw <2 x i8> [[X]], [[Z]]
; CHECK-NEXT:    [[B:%.*]] = mul nuw <2 x i8> [[Y]], [[Z]]
; CHECK-NEXT:    [[R:%.*]] = urem <2 x i8> [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq <2 x i8> [[R]], <i8 0, i8 poison>
; CHECK-NEXT:    ret <2 x i1> [[C]]
;
  %a = mul nuw <2 x i8> %x, %z
  %b = mul nuw <2 x i8> %y, %z
  %r = urem <2 x i8> %a, %b
  %c = icmp eq <2 x i8> %r, <i8 0, i8 poison>
  ret <2 x i1> %c
}

define <2 x i1> @icmp_eq_urem_mul_vec_non_splat(<2 x i8> %x, <2 x i8> %y, <2 x i8> %z) {
; CHECK-LABEL: define <2 x i1> @icmp_eq_urem_mul_vec_non_splat(
; CHECK-SAME: <2 x i8> [[X:%.*]], <2 x i8> [[Y:%.*]], <2 x i8> [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nuw <2 x i8> [[X]], [[Z]]
; CHECK-NEXT:    [[B:%.*]] = mul nuw <2 x i8> [[Y]], [[Z]]
; CHECK-NEXT:    [[R:%.*]] = urem <2 x i8> [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq <2 x i8> [[R]], <i8 0, i8 1>
; CHECK-NEXT:    ret <2 x i1> [[C]]
;
  %a = mul nuw <2 x i8> %x, %z
  %b = mul nuw <2 x i8> %y, %z
  %r = urem <2 x i8> %a, %b
  %c = icmp eq <2 x i8> %r, <i8 0, i8 1>
  ret <2 x i1> %c
}

define i1 @icmp_eq_urem_mul_negative_flags1(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_urem_mul_negative_flags1(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul i8 [[X]], [[Z]]
; CHECK-NEXT:    [[B:%.*]] = mul nuw i8 [[Y]], [[Z]]
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul i8 %x, %z
  %b = mul nuw i8 %y, %z
  %r = urem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_urem_mul_negative_flags2(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_urem_mul_negative_flags2(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nuw i8 [[X]], [[Z]]
; CHECK-NEXT:    [[B:%.*]] = mul i8 [[Y]], [[Z]]
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nuw i8 %x, %z
  %b = mul i8 %y, %z
  %r = urem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_urem_mul_negative_common_op(i8 %x, i8 %y, i8 %u, i8 %v) {
; CHECK-LABEL: define i1 @icmp_eq_urem_mul_negative_common_op(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[U:%.*]], i8 [[V:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nuw i8 [[X]], [[U]]
; CHECK-NEXT:    [[B:%.*]] = mul nuw i8 [[Y]], [[V]]
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nuw i8 %x, %u
  %b = mul nuw i8 %y, %v
  %r = urem i8 %a, %b
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_urem_mul_negative_multi_use(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_urem_mul_negative_multi_use(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nuw i8 [[X]], [[Z]]
; CHECK-NEXT:    [[B:%.*]] = mul nuw i8 [[Y]], [[Z]]
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[A]], [[B]]
; CHECK-NEXT:    call void @use(i8 [[R]])
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 0
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nuw i8 %x, %z
  %b = mul nuw i8 %y, %z
  %r = urem i8 %a, %b
  call void @use(i8 %r)
  %c = icmp eq i8 %r, 0
  ret i1 %c
}

define i1 @icmp_eq_urem_mul_negative_wrong_constant(i8 %x, i8 %y, i8 %z) {
; CHECK-LABEL: define i1 @icmp_eq_urem_mul_negative_wrong_constant(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]], i8 [[Z:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = mul nuw i8 [[X]], [[Z]]
; CHECK-NEXT:    [[B:%.*]] = mul nuw i8 [[Y]], [[Z]]
; CHECK-NEXT:    [[R:%.*]] = urem i8 [[A]], [[B]]
; CHECK-NEXT:    [[C:%.*]] = icmp eq i8 [[R]], 1
; CHECK-NEXT:    ret i1 [[C]]
;
  %a = mul nuw i8 %x, %z
  %b = mul nuw i8 %y, %z
  %r = urem i8 %a, %b
  %c = icmp eq i8 %r, 1
  ret i1 %c
}

