; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=instcombine -S %s | FileCheck %s
target datalayout = "E-p:64:64:64-p1:64:64:64-a0:0:8-f32:32:32-f64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-v64:64:64-v128:128:128"

define i64 @inttoptr_used_by_phi_with_ptrtoint(i1 %c, ptr %src, ptr %p2) {
; CHECK-LABEL: define i64 @inttoptr_used_by_phi_with_ptrtoint(
; CHECK-SAME: i1 [[C:%.*]], ptr [[SRC:%.*]], ptr [[P2:%.*]]) {
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[I:%.*]] = ptrtoint ptr [[SRC]] to i64
; CHECK-NEXT:    [[A:%.*]] = add i64 [[I]], 10
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ [[A]], %[[THEN]] ], [ 0, %[[ELSE]] ]
; CHECK-NEXT:    ret i64 [[PHI]]
;
  %i = ptrtoint ptr %src to i64
  %a = add i64 %i, 10
  %p = inttoptr i64 %a to ptr
  br i1 %c, label %then, label %else

then:
  br label %exit

else:
  br label %exit

exit:
  %phi = phi ptr [ %p, %then ], [ null, %else ]
  %i.2 = ptrtoint ptr %phi to i64
  ret i64 %i.2
}

declare void @foo(ptr)

define i64 @inttoptr_used_by_phi_with_other_users(i1 %c, ptr %src, ptr %p2) {
; CHECK-LABEL: define i64 @inttoptr_used_by_phi_with_other_users(
; CHECK-SAME: i1 [[C:%.*]], ptr [[SRC:%.*]], ptr [[P2:%.*]]) {
; CHECK-NEXT:    [[I:%.*]] = ptrtoint ptr [[SRC]] to i64
; CHECK-NEXT:    [[A:%.*]] = add i64 [[I]], 10
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ [[A]], %[[THEN]] ], [ 0, %[[ELSE]] ]
; CHECK-NEXT:    [[P:%.*]] = inttoptr i64 [[A]] to ptr
; CHECK-NEXT:    call void @foo(ptr [[P]])
; CHECK-NEXT:    ret i64 [[PHI]]
;
  %i = ptrtoint ptr %src to i64
  %a = add i64 %i, 10
  %p = inttoptr i64 %a to ptr
  br i1 %c, label %then, label %else

then:
  br label %exit

else:
  br label %exit

exit:
  %phi = phi ptr [ %p, %then ], [ null, %else ]
  call void @foo(ptr %p)
  %i.2 = ptrtoint ptr %phi to i64
  ret i64 %i.2
}
