; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s
define float @missing_contract_cos_mul_tan(float %x) {
; CHECK-LABEL: define float @missing_contract_cos_mul_tan(
; CHECK-SAME: float [[X:%.*]]) {
; CHECK-NEXT:    [[TAN:%.*]] = call float @llvm.tan.f32(float [[X]])
; CHECK-NEXT:    [[COS:%.*]] = call float @llvm.cos.f32(float [[X]])
; CHECK-NEXT:    [[MUL:%.*]] = fmul contract float [[TAN]], [[COS]]
; CHECK-NEXT:    ret float [[MUL]]
;
  %tan = call float @llvm.tan.f32(float %x)
  %cos = call float @llvm.cos.f32(float %x)
  %mul = fmul contract float %tan, %cos
  ret float %mul
}

define float @cos_mul_tan(float %x) {
; CHECK-LABEL: define float @cos_mul_tan(
; CHECK-SAME: float [[X:%.*]]) {
; CHECK-NEXT:    [[MUL:%.*]] = call contract float @llvm.sin.f32(float [[X]])
; CHECK-NEXT:    ret float [[MUL]]
;
  %tan = call contract float @llvm.tan.f32(float %x)
  %cos = call contract float @llvm.cos.f32(float %x)
  %mul = fmul contract float %tan, %cos
  ret float %mul
}
