; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; Test known bits refinements for pattern: a * (b - c) + c * d
; where a > 0, c > 0, b > 0, d > 0, and b > c.
; This pattern is a generalization of lerp and it appears frequently in graphics operations.

define i32 @test_clamp(i8 %a, i8 %c, i8 %d) {
; CHECK-LABEL: define i32 @test_clamp(
; CHECK-SAME: i8 [[A:%.*]], i8 [[C:%.*]], i8 [[D:%.*]]) {
; CHECK-NEXT:    [[A32:%.*]] = zext i8 [[A]] to i32
; CHECK-NEXT:    [[C32:%.*]] = zext i8 [[C]] to i32
; CHECK-NEXT:    [[D32:%.*]] = zext i8 [[D]] to i32
; CHECK-NEXT:    [[SUB:%.*]] = xor i32 [[C32]], 255
; CHECK-NEXT:    [[MUL1:%.*]] = mul nuw nsw i32 [[SUB]], [[A32]]
; CHECK-NEXT:    [[MUL2:%.*]] = mul nuw nsw i32 [[C32]], [[D32]]
; CHECK-NEXT:    [[ADD:%.*]] = add nuw nsw i32 [[MUL1]], [[MUL2]]
; CHECK-NEXT:    ret i32 [[ADD]]
;
  %a32 = zext i8 %a to i32
  %c32 = zext i8 %c to i32
  %d32 = zext i8 %d to i32
  %sub = sub i32 255, %c32
  %mul1 = mul i32 %a32, %sub
  %mul2 = mul i32 %c32, %d32
  %add = add i32 %mul1, %mul2
  %cmp = icmp ugt i32 %add, 65535
  %result = select i1 %cmp, i32 65535, i32 %add
  ret i32 %result
}

define i1 @test_trunc_cmp(i8 %a, i8 %c, i8 %d) {
; CHECK-LABEL: define i1 @test_trunc_cmp(
; CHECK-SAME: i8 [[A:%.*]], i8 [[C:%.*]], i8 [[D:%.*]]) {
; CHECK-NEXT:    [[A32:%.*]] = zext i8 [[A]] to i16
; CHECK-NEXT:    [[C32:%.*]] = zext i8 [[C]] to i16
; CHECK-NEXT:    [[D32:%.*]] = zext i8 [[D]] to i16
; CHECK-NEXT:    [[SUB:%.*]] = xor i16 [[C32]], 255
; CHECK-NEXT:    [[MUL1:%.*]] = mul nuw i16 [[SUB]], [[A32]]
; CHECK-NEXT:    [[MUL2:%.*]] = mul nuw i16 [[C32]], [[D32]]
; CHECK-NEXT:    [[ADD:%.*]] = add i16 [[MUL1]], [[MUL2]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i16 [[ADD]], 1234
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %a32 = zext i8 %a to i32
  %c32 = zext i8 %c to i32
  %d32 = zext i8 %d to i32
  %sub = sub i32 255, %c32
  %mul1 = mul i32 %a32, %sub
  %mul2 = mul i32 %c32, %d32
  %add = add i32 %mul1, %mul2
  %trunc = trunc i32 %add to i16
  %cmp = icmp eq i16 %trunc, 1234
  ret i1 %cmp
}

define i1 @test_trunc_cmp_xor(i8 %a, i8 %c, i8 %d) {
; CHECK-LABEL: define i1 @test_trunc_cmp_xor(
; CHECK-SAME: i8 [[A:%.*]], i8 [[C:%.*]], i8 [[D:%.*]]) {
; CHECK-NEXT:    [[A32:%.*]] = zext i8 [[A]] to i16
; CHECK-NEXT:    [[C32:%.*]] = zext i8 [[C]] to i16
; CHECK-NEXT:    [[D32:%.*]] = zext i8 [[D]] to i16
; CHECK-NEXT:    [[SUB:%.*]] = xor i16 [[C32]], 255
; CHECK-NEXT:    [[MUL1:%.*]] = mul nuw i16 [[SUB]], [[A32]]
; CHECK-NEXT:    [[MUL2:%.*]] = mul nuw i16 [[C32]], [[D32]]
; CHECK-NEXT:    [[ADD:%.*]] = add i16 [[MUL1]], [[MUL2]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i16 [[ADD]], 1234
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %a32 = zext i8 %a to i32
  %c32 = zext i8 %c to i32
  %d32 = zext i8 %d to i32
  %sub = xor i32 255, %c32
  %mul1 = mul i32 %a32, %sub
  %mul2 = mul i32 %c32, %d32
  %add = add i32 %mul1, %mul2
  %trunc = trunc i32 %add to i16
  %cmp = icmp eq i16 %trunc, 1234
  ret i1 %cmp
}

define i1 @test_trunc_cmp_arbitrary_b(i8 %a, i8 %b, i8 %c, i8 %d) {
; CHECK-LABEL: define i1 @test_trunc_cmp_arbitrary_b(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]], i8 [[C:%.*]], i8 [[D:%.*]]) {
; CHECK-NEXT:    [[A32:%.*]] = zext i8 [[A]] to i16
; CHECK-NEXT:    [[B32:%.*]] = zext i8 [[B]] to i16
; CHECK-NEXT:    [[C32:%.*]] = zext i8 [[C]] to i16
; CHECK-NEXT:    [[D32:%.*]] = zext i8 [[D]] to i16
; CHECK-NEXT:    [[SUB:%.*]] = sub nsw i16 [[B32]], [[C32]]
; CHECK-NEXT:    [[MUL1:%.*]] = mul i16 [[SUB]], [[A32]]
; CHECK-NEXT:    [[MUL2:%.*]] = mul nuw i16 [[C32]], [[D32]]
; CHECK-NEXT:    [[ADD:%.*]] = add i16 [[MUL1]], [[MUL2]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i16 [[ADD]], 1234
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %a32 = zext i8 %a to i32
  %b32 = zext i8 %b to i32
  %c32 = zext i8 %c to i32
  %d32 = zext i8 %d to i32
  %sub = sub nsw nuw i32 %b32, %c32
  %mul1 = mul i32 %a32, %sub
  %mul2 = mul i32 %c32, %d32
  %add = add i32 %mul1, %mul2
  %trunc = trunc i32 %add to i16
  %cmp = icmp eq i16 %trunc, 1234
  ret i1 %cmp
}


define i1 @test_trunc_cmp_no_a(i8 %b, i8 %c, i8 %d) {
; CHECK-LABEL: define i1 @test_trunc_cmp_no_a(
; CHECK-SAME: i8 [[B:%.*]], i8 [[C:%.*]], i8 [[D:%.*]]) {
; CHECK-NEXT:    [[B32:%.*]] = zext i8 [[B]] to i16
; CHECK-NEXT:    [[C32:%.*]] = zext i8 [[C]] to i16
; CHECK-NEXT:    [[D32:%.*]] = zext i8 [[D]] to i16
; CHECK-NEXT:    [[SUB:%.*]] = sub nsw i16 [[B32]], [[C32]]
; CHECK-NEXT:    [[MUL2:%.*]] = mul nuw i16 [[C32]], [[D32]]
; CHECK-NEXT:    [[ADD:%.*]] = add i16 [[SUB]], [[MUL2]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i16 [[ADD]], 1234
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %b32 = zext i8 %b to i32
  %c32 = zext i8 %c to i32
  %d32 = zext i8 %d to i32
  %sub = sub nuw i32 %b32, %c32
  %mul2 = mul i32 %c32, %d32
  %add = add i32 %sub, %mul2
  %trunc = trunc i32 %add to i16
  %cmp = icmp eq i16 %trunc, 1234
  ret i1 %cmp
}

define i1 @test_trunc_cmp_no_d(i8 %a, i8 %b, i8 %c) {
; CHECK-LABEL: define i1 @test_trunc_cmp_no_d(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]], i8 [[C:%.*]]) {
; CHECK-NEXT:    [[A32:%.*]] = zext i8 [[A]] to i16
; CHECK-NEXT:    [[B32:%.*]] = zext i8 [[B]] to i16
; CHECK-NEXT:    [[C32:%.*]] = zext i8 [[C]] to i16
; CHECK-NEXT:    [[SUB:%.*]] = sub nsw i16 [[B32]], [[C32]]
; CHECK-NEXT:    [[MUL1:%.*]] = mul i16 [[SUB]], [[A32]]
; CHECK-NEXT:    [[ADD:%.*]] = add i16 [[MUL1]], [[C32]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i16 [[ADD]], 1234
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %a32 = zext i8 %a to i32
  %b32 = zext i8 %b to i32
  %c32 = zext i8 %c to i32
  %sub = sub nsw nuw i32 %b32, %c32
  %mul1 = mul i32 %a32, %sub
  %add = add i32 %mul1, %c32
  %trunc = trunc i32 %add to i16
  %cmp = icmp eq i16 %trunc, 1234
  ret i1 %cmp
}

define i1 @test_trunc_cmp_xor_negative(i8 %a, i8 %c, i8 %d) {
; CHECK-LABEL: define i1 @test_trunc_cmp_xor_negative(
; CHECK-SAME: i8 [[A:%.*]], i8 [[C:%.*]], i8 [[D:%.*]]) {
; CHECK-NEXT:    [[A32:%.*]] = zext i8 [[A]] to i16
; CHECK-NEXT:    [[C32:%.*]] = zext i8 [[C]] to i16
; CHECK-NEXT:    [[D32:%.*]] = zext i8 [[D]] to i16
; CHECK-NEXT:    [[SUB:%.*]] = xor i16 [[C32]], 234
; CHECK-NEXT:    [[MUL1:%.*]] = mul nuw i16 [[SUB]], [[A32]]
; CHECK-NEXT:    [[MUL2:%.*]] = mul nuw i16 [[C32]], [[D32]]
; CHECK-NEXT:    [[TRUNC:%.*]] = add i16 [[MUL1]], [[MUL2]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i16 [[TRUNC]], 1234
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %a32 = zext i8 %a to i32
  %c32 = zext i8 %c to i32
  %d32 = zext i8 %d to i32
  %sub = xor i32 234, %c32
  %mul1 = mul i32 %a32, %sub
  %mul2 = mul i32 %c32, %d32
  %add = add i32 %mul1, %mul2
  ; We should keep the trunc in this case
  %trunc = trunc i32 %add to i16
  %cmp = icmp eq i16 %trunc, 1234
  ret i1 %cmp
}
