; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=instcombine -S < %s | FileCheck %s

declare void @use(i8)

define i32 @lshr_add_or_low_bias(i32 %x, i32 %y) {
; CHECK-LABEL: define i32 @lshr_add_or_low_bias(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:    [[BIASED_Y:%.*]] = add i32 [[Y]], 1
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[BIASED_Y]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = add i32 [[SHR]], [[X]]
; CHECK-NEXT:    [[LSHR:%.*]] = and i32 [[TMP3]], 2147483647
; CHECK-NEXT:    ret i32 [[LSHR]]
;
  %shl = shl i32 %x, 1
  %biased = or i32 %shl, 1
  %add = add i32 %biased, %y
  %lshr = lshr i32 %add, 1
  ret i32 %lshr
}

define i8 @lshr_add_or_low_bias_commuted(i8 %x, i8 %y) {
; CHECK-LABEL: define i8 @lshr_add_or_low_bias_commuted(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]]) {
; CHECK-NEXT:    [[BIASED_Y:%.*]] = add i8 [[Y]], 1
; CHECK-NEXT:    [[SHR:%.*]] = lshr i8 [[BIASED_Y]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = add i8 [[SHR]], [[X]]
; CHECK-NEXT:    [[LSHR:%.*]] = and i8 [[TMP3]], 127
; CHECK-NEXT:    ret i8 [[LSHR]]
;
  %shl = shl i8 %x, 1
  %biased = or i8 %shl, 1
  %add = add i8 %y, %biased
  %lshr = lshr i8 %add, 1
  ret i8 %lshr
}

define i8 @lshr_add_or_max_low_bias(i8 %x, i8 %y) {
; CHECK-LABEL: define i8 @lshr_add_or_max_low_bias(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]]) {
; CHECK-NEXT:    [[BIASED_Y:%.*]] = add i8 [[Y]], 3
; CHECK-NEXT:    [[SHR:%.*]] = lshr i8 [[BIASED_Y]], 2
; CHECK-NEXT:    [[TMP3:%.*]] = add i8 [[SHR]], [[X]]
; CHECK-NEXT:    [[LSHR:%.*]] = and i8 [[TMP3]], 63
; CHECK-NEXT:    ret i8 [[LSHR]]
;
  %shl = shl i8 %x, 2
  %biased = or i8 %shl, 3
  %add = add i8 %biased, %y
  %lshr = lshr i8 %add, 2
  ret i8 %lshr
}

define i8 @filter14_like(i32 %x, i32 %y) {
; CHECK-LABEL: define i8 @filter14_like(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:    [[BIASED_Y:%.*]] = add i32 [[Y]], 1
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[BIASED_Y]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = add i32 [[SHR]], [[X]]
; CHECK-NEXT:    [[TR:%.*]] = trunc i32 [[TMP3]] to i8
; CHECK-NEXT:    ret i8 [[TR]]
;
  %reass.add = shl i32 %x, 1
  %biased = or i32 %reass.add, 1
  %sum = add i32 %biased, %y
  %shr = lshr i32 %sum, 1
  %tr = trunc i32 %shr to i8
  ret i8 %tr
}

define i32 @lshr_add_or_not_low_bias(i32 %x, i32 %y) {
; CHECK-LABEL: define i32 @lshr_add_or_not_low_bias(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:    [[SHL:%.*]] = shl i32 [[X]], 1
; CHECK-NEXT:    [[BIASED:%.*]] = or i32 [[SHL]], 2
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[BIASED]], [[Y]]
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[ADD]], 1
; CHECK-NEXT:    ret i32 [[SHR]]
;
  %shl = shl i32 %x, 1
  %biased = or i32 %shl, 2
  %add = add i32 %biased, %y
  %lshr = lshr i32 %add, 1
  ret i32 %lshr
}

define i8 @lshr_add_or_low_bias_extra_or_use(i8 %x, i8 %y) {
; CHECK-LABEL: define i8 @lshr_add_or_low_bias_extra_or_use(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]]) {
; CHECK-NEXT:    [[SHL:%.*]] = shl i8 [[X]], 1
; CHECK-NEXT:    [[BIASED:%.*]] = or disjoint i8 [[SHL]], 1
; CHECK-NEXT:    call void @use(i8 [[BIASED]])
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[BIASED]], [[Y]]
; CHECK-NEXT:    [[SHR:%.*]] = lshr i8 [[ADD]], 1
; CHECK-NEXT:    ret i8 [[SHR]]
;
  %shl = shl i8 %x, 1
  %biased = or i8 %shl, 1
  call void @use(i8 %biased)
  %add = add i8 %biased, %y
  %lshr = lshr i8 %add, 1
  ret i8 %lshr
}

define i8 @lshr_add_or_low_bias_extra_shl_use(i8 %x, i8 %y) {
; CHECK-LABEL: define i8 @lshr_add_or_low_bias_extra_shl_use(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]]) {
; CHECK-NEXT:    [[SHL:%.*]] = shl i8 [[X]], 1
; CHECK-NEXT:    call void @use(i8 [[SHL]])
; CHECK-NEXT:    [[BIASED:%.*]] = or disjoint i8 [[SHL]], 1
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[BIASED]], [[Y]]
; CHECK-NEXT:    [[SHR:%.*]] = lshr i8 [[ADD]], 1
; CHECK-NEXT:    ret i8 [[SHR]]
;
  %shl = shl i8 %x, 1
  call void @use(i8 %shl)
  %biased = or i8 %shl, 1
  %add = add i8 %biased, %y
  %lshr = lshr i8 %add, 1
  ret i8 %lshr
}
