; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

declare void @use(i32)

; (A & ~B) | (A ^ B) -> A ^ B

define i32 @test_basic(i32 %a, i32 %b) {
; CHECK-LABEL: @test_basic(
; CHECK-NEXT:    [[RES:%.*]] = xor i32 [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    ret i32 [[RES]]
;
  %not_b = xor i32 %b, -1
  %and = and i32 %a, %not_b
  %xor = xor i32 %a, %b
  %res = or i32 %and, %xor
  ret i32 %res
}

define <2 x i32> @test_vector(<2 x i32> %a, <2 x i32> %b) {
; CHECK-LABEL: @test_vector(
; CHECK-NEXT:    [[RES:%.*]] = xor <2 x i32> [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    ret <2 x i32> [[RES]]
;
  %not_b = xor <2 x i32> %b, <i32 -1, i32 -1>
  %and = and <2 x i32> %a, %not_b
  %xor = xor <2 x i32> %a, %b
  %res = or <2 x i32> %and, %xor
  ret <2 x i32> %res
}

define i32 @test_commute(i32 %a, i32 %b) {
; CHECK-LABEL: @test_commute(
; CHECK-NEXT:    [[RES:%.*]] = xor i32 [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    ret i32 [[RES]]
;
  %not_b = xor i32 %b, -1
  %and = and i32 %a, %not_b
  %xor = xor i32 %a, %b
  %res = or i32 %xor, %and  ;
  ret i32 %res
}

define i32 @test_multiuse(i32 %a, i32 %b) {
; CHECK-LABEL: @test_multiuse(
; CHECK-NEXT:    [[NOT_B:%.*]] = xor i32 [[B:%.*]], -1
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[A:%.*]], [[NOT_B]]
; CHECK-NEXT:    call void @use(i32 [[AND]])
; CHECK-NEXT:    [[XOR:%.*]] = xor i32 [[A]], [[B]]
; CHECK-NEXT:    ret i32 [[XOR]]
;
  %not_b = xor i32 %b, -1
  %and = and i32 %a, %not_b
  call void @use(i32 %and)
  %xor = xor i32 %a, %b
  %res = or i32 %and, %xor
  ret i32 %res
}
