; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define i32 @test_pdep_32_zero_src(i32 %x) nounwind readnone {
; CHECK-LABEL: @test_pdep_32_zero_src(
; CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.pdep.i32(i32 0, i32 [[X:%.*]])
; CHECK-NEXT:    ret i32 [[TMP1]]
;
  %1 = tail call i32 @llvm.pdep.i32(i32 0, i32 %x)
  ret i32 %1
}

define i64 @test_pdep_64_zero_src(i64 %x) nounwind readnone {
; CHECK-LABEL: @test_pdep_64_zero_src(
; CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.pdep.i64(i64 0, i64 [[X:%.*]])
; CHECK-NEXT:    ret i64 [[TMP1]]
;
  %1 = tail call i64 @llvm.pdep.i64(i64 0, i64 %x)
  ret i64 %1
}

define i32 @test_pdep_32_zero_mask(i32 %x) nounwind readnone {
; CHECK-LABEL: @test_pdep_32_zero_mask(
; CHECK-NEXT:    ret i32 0
;
  %1 = tail call i32 @llvm.pdep.i32(i32 %x, i32 0)
  ret i32 %1
}

define i64 @test_pdep_64_zero_mask(i64 %x) nounwind readnone {
; CHECK-LABEL: @test_pdep_64_zero_mask(
; CHECK-NEXT:    ret i64 0
;
  %1 = tail call i64 @llvm.pdep.i64(i64 %x, i64 0)
  ret i64 %1
}

define i32 @test_pdep_32_allones_mask(i32 %x) nounwind readnone {
; CHECK-LABEL: @test_pdep_32_allones_mask(
; CHECK-NEXT:    ret i32 [[TMP1:%.*]]
;
  %1 = tail call i32 @llvm.pdep.i32(i32 %x, i32 -1)
  ret i32 %1
}

define i64 @test_pdep_64_allones_mask(i64 %x) nounwind readnone {
; CHECK-LABEL: @test_pdep_64_allones_mask(
; CHECK-NEXT:    ret i64 [[TMP1:%.*]]
;
  %1 = tail call i64 @llvm.pdep.i64(i64 %x, i64 -1)
  ret i64 %1
}

define i32 @test_pdep_32_shifted_mask(i32 %x) nounwind readnone {
; CHECK-LABEL: @test_pdep_32_shifted_mask(
; CHECK-NEXT:    [[TMP2:%.*]] = shl i32 [[X:%.*]], 2
; CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[TMP2]], 12
; CHECK-NEXT:    ret i32 [[TMP1]]
;
  %1 = tail call i32 @llvm.pdep.i32(i32 %x, i32 12)
  ret i32 %1
}

define i64 @test_pdep_64_shifted_mask(i64 %x) nounwind readnone {
; CHECK-LABEL: @test_pdep_64_shifted_mask(
; CHECK-NEXT:    [[TMP2:%.*]] = shl i64 [[X:%.*]], 2
; CHECK-NEXT:    [[TMP1:%.*]] = and i64 [[TMP2]], 12
; CHECK-NEXT:    ret i64 [[TMP1]]
;
  %1 = tail call i64 @llvm.pdep.i64(i64 %x, i64 12)
  ret i64 %1
}

define i32 @test_pdep_32_constant_fold() nounwind readnone {
; CHECK-LABEL: @test_pdep_32_constant_fold(
; CHECK-NEXT:    ret i32 807407616
;
  %1 = tail call i32 @llvm.pdep.i32(i32 1985229328, i32 4042322160)
  ret i32 %1
}

define i64 @test_pdep_64_constant_fold() nounwind readnone {
; CHECK-LABEL: @test_pdep_64_constant_fold(
; CHECK-NEXT:    ret i64 -1089641583808049024
;
  %1 = tail call i64 @llvm.pdep.i64(i64 8526495043095935640, i64 -1085102592571150096)
  ret i64 %1
}

define i32 @test_pdep_32_constant_fold_2() nounwind readnone {
; CHECK-LABEL: @test_pdep_32_constant_fold_2(
; CHECK-NEXT:    ret i32 838860816
;
  %1 = tail call i32 @llvm.pdep.i32(i32 1985229328, i32 4278190335)
  ret i32 %1
}

define i64 @test_pdep_64_constant_fold_2() nounwind readnone {
; CHECK-LABEL: @test_pdep_64_constant_fold_2(
; CHECK-NEXT:    ret i64 -144114243170822144
;
  %1 = tail call i64 @llvm.pdep.i64(i64 8526495043095935640, i64 -72056498804490496)
  ret i64 %1
}
