; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=instcombine -S < %s | FileCheck %s

; The two case below should not fold because they overflow

define double @powi_mul_overflow(double %x) {
; CHECK-LABEL: define double @powi_mul_overflow(
; CHECK-SAME: double [[X:%.*]]) {
; CHECK-NEXT:    [[P1:%.*]] = call reassoc double @llvm.powi.f64.i32(double [[X]], i32 2147483640)
; CHECK-NEXT:    [[P2:%.*]] = call reassoc double @llvm.powi.f64.i32(double [[X]], i32 100)
; CHECK-NEXT:    [[R:%.*]] = fmul reassoc double [[P1]], [[P2]]
; CHECK-NEXT:    ret double [[R]]
;
  %p1 = call reassoc double @llvm.powi.f64.i32(double %x, i32 2147483640)
  %p2 = call reassoc double @llvm.powi.f64.i32(double %x, i32 100)
  %r = fmul reassoc double %p1, %p2
  ret double %r
}

define double @powi_mul_overflow_neg(double %x) {
; CHECK-LABEL: define double @powi_mul_overflow_neg(
; CHECK-SAME: double [[X:%.*]]) {
; CHECK-NEXT:    [[P1:%.*]] = call reassoc double @llvm.powi.f64.i32(double [[X]], i32 -2147483640)
; CHECK-NEXT:    [[P2:%.*]] = call reassoc double @llvm.powi.f64.i32(double [[X]], i32 -100)
; CHECK-NEXT:    [[R:%.*]] = fmul reassoc double [[P1]], [[P2]]
; CHECK-NEXT:    ret double [[R]]
;
  %p1 = call reassoc double @llvm.powi.f64.i32(double %x, i32 -2147483640)
  %p2 = call reassoc double @llvm.powi.f64.i32(double %x, i32 -100)
  %r = fmul reassoc double %p1, %p2
  ret double %r
}

; This one should fold
define double @powi_mul_no_overflow(double %x) {
; CHECK-LABEL: define double @powi_mul_no_overflow(
; CHECK-SAME: double [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = call reassoc double @llvm.powi.f64.i32(double [[X]], i32 3000)
; CHECK-NEXT:    ret double [[R]]
;
  %p1 = call reassoc double @llvm.powi.f64.i32(double %x, i32 1000)
  %p2 = call reassoc double @llvm.powi.f64.i32(double %x, i32 2000)
  %r = fmul reassoc double %p1, %p2
  ret double %r
}
