; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define zeroext i1 @_Z3fooPb(ptr nocapture %x) {
; CHECK-LABEL: define zeroext i1 @_Z3fooPb(
; CHECK-SAME: ptr captures(none) [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A:%.*]] = load i8, ptr [[X]], align 1, !range [[RNG0:![0-9]+]]
; CHECK-NEXT:    [[TOBOOL:%.*]] = trunc nuw i8 [[A]] to i1
; CHECK-NEXT:    ret i1 [[TOBOOL]]
;
entry:
  %a = load i8, ptr %x, align 1, !range !0
  %b = and i8 %a, 1
  %tobool = icmp ne i8 %b, 0
  ret i1 %tobool
}

; CHECK: %a = load i8, ptr %x, align 1, !range !0
; CHECK-NEXT: %tobool = icmp ne i8 %a, 0
; CHECK-NEXT: ret i1 %tobool

!0 = !{i8 0, i8 2}
;.
; CHECK: [[RNG0]] = !{i8 0, i8 2}
;.
