; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=instcombine < %s | FileCheck %s

define <4 x i1> @pr97730-1(<4 x i1> %val0, <4 x i1> %val1, <4 x i1> %val2) {
; CHECK-LABEL: define <4 x i1> @pr97730-1(
; CHECK-SAME: <4 x i1> [[VAL0:%.*]], <4 x i1> [[VAL1:%.*]], <4 x i1> [[VAL2:%.*]]) {
; CHECK-NEXT:    [[VAL3:%.*]] = xor <4 x i1> [[VAL1]], <i1 true, i1 true, i1 true, i1 true>
; CHECK-NEXT:    [[VAL4:%.*]] = xor <4 x i1> [[VAL0]], <i1 false, i1 undef, i1 undef, i1 true>
; CHECK-NEXT:    [[VAL5:%.*]] = and <4 x i1> [[VAL4]], [[VAL3]]
; CHECK-NEXT:    [[VAL6:%.*]] = xor <4 x i1> [[VAL0]], [[VAL5]]
; CHECK-NEXT:    ret <4 x i1> [[VAL6]]
;
  %val3 = add <4 x i1> %val1, <i1 true, i1 true, i1 true, i1 true>
  %val4 = xor <4 x i1> <i1 false, i1 undef, i1 undef, i1 true>, %val0
  %val5 = and <4 x i1> %val4, %val3
  %val6 = sub <4 x i1> %val5, %val0
  ret <4 x i1> %val6
}

define <4 x i1> @pr97730-2(<4 x i1> %val0, <4 x i1> %val1, <4 x i1> %val2) {
; CHECK-LABEL: define <4 x i1> @pr97730-2(
; CHECK-SAME: <4 x i1> [[VAL0:%.*]], <4 x i1> [[VAL1:%.*]], <4 x i1> [[VAL2:%.*]]) {
; CHECK-NEXT:    [[VAL3:%.*]] = xor <4 x i1> [[VAL1]], <i1 true, i1 true, i1 true, i1 true>
; CHECK-NEXT:    [[VAL4:%.*]] = xor <4 x i1> [[VAL0]], <i1 false, i1 undef, i1 undef, i1 true>
; CHECK-NEXT:    [[VAL5:%.*]] = and <4 x i1> [[VAL4]], [[VAL3]]
; CHECK-NEXT:    [[VAL6:%.*]] = xor <4 x i1> [[VAL0]], [[VAL5]]
; CHECK-NEXT:    ret <4 x i1> [[VAL6]]
;
  %val3 = xor <4 x i1> %val1, <i1 true, i1 true, i1 true, i1 true>
  %val4 = xor <4 x i1> <i1 false, i1 undef, i1 undef, i1 true>, %val0
  %val5 = and <4 x i1> %val4, %val3
  %val6 = sub <4 x i1> %val5, %val0
  ret <4 x i1> %val6
}
