; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; Test for GitHub issue #176554
; InstCombine should fold range comparisons even when the logical-and
; uses bitwise 'and' instead of 'select' form.

define i1 @test_mixed_and_select(i1 %cond, i32 %y) {
; CHECK-LABEL: @test_mixed_and_select(
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[Y:%.*]], -65536
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ult i32 [[TMP1]], 1048576
; CHECK-NEXT:    [[SEL2:%.*]] = and i1 [[COND:%.*]], [[TMP2]]
; CHECK-NEXT:    ret i1 [[SEL2]]
;
  %cmp1 = icmp samesign ugt i32 %y, 65535
  %sel11 = and i1 %cond, %cmp1
  %cmp2 = icmp samesign ult i32 %y, 1114112
  %sel2 = select i1 %sel11, i1 %cmp2, i1 false
  ret i1 %sel2
}

define i1 @test_bitwise_and_reassoc(i1 %cond, i32 %y) {
; CHECK-LABEL: @test_bitwise_and_reassoc(
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[Y:%.*]], -65536
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ult i32 [[TMP1]], 1048576
; CHECK-NEXT:    [[SEL2:%.*]] = and i1 [[COND:%.*]], [[TMP2]]
; CHECK-NEXT:    ret i1 [[SEL2]]
;
  %cmp1 = icmp samesign ugt i32 %y, 65535
  %sel11 = and i1 %cond, %cmp1
  %cmp2 = icmp samesign ult i32 %y, 1114112
  %sel2 = and i1 %sel11, %cmp2
  ret i1 %sel2
}

define i1 @test_mixed_or_select(i1 %cond, i32 %y) {
; CHECK-LABEL: @test_mixed_or_select(
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[Y:%.*]], -1114112
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ult i32 [[TMP1]], -1048576
; CHECK-NEXT:    [[SEL2:%.*]] = or i1 [[COND:%.*]], [[TMP2]]
; CHECK-NEXT:    ret i1 [[SEL2]]
;
  %cmp1 = icmp samesign ugt i32 %y, 1114111
  %sel11 = or i1 %cond, %cmp1
  %cmp2 = icmp samesign ult i32 %y, 65536
  %sel2 = select i1 %sel11, i1 true, i1 %cmp2
  ret i1 %sel2
}
