; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=instcombine < %s | FileCheck %s

; InstCombine was trying to fold the scalar GEP %getelementptr13, into
; the subsequent vector GEPs, resulting in a type mismatch.

define <8 x i64> @pluto.6(ptr %arg1, i64 %mul, <8 x i64> %shufflevector, <8 x i64> %add, <8 x i64> %phi16) {
; CHECK-LABEL: define <8 x i64> @pluto.6(
; CHECK-SAME: ptr [[ARG1:%.*]], i64 [[MUL:%.*]], <8 x i64> [[SHUFFLEVECTOR:%.*]], <8 x i64> [[ADD:%.*]], <8 x i64> [[PHI16:%.*]]) {
; CHECK-NEXT:  [[BB:.*:]]
; CHECK-NEXT:    [[GETELEMENTPTR19_IDX:%.*]] = shl <8 x i64> [[ADD]], splat (i64 3)
; CHECK-NEXT:    [[GETELEMENTPTR13_IDX:%.*]] = shl i64 [[MUL]], 3
; CHECK-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <8 x i64> poison, i64 [[GETELEMENTPTR13_IDX]], i64 0
; CHECK-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <8 x i64> [[DOTSPLATINSERT]], <8 x i64> poison, <8 x i32> zeroinitializer
; CHECK-NEXT:    [[GETELEMENTPTR13:%.*]] = getelementptr [8 x i8], ptr [[ARG1]], i64 [[MUL]]
; CHECK-NEXT:    [[GETELEMENTPTR24:%.*]] = getelementptr i8, ptr [[GETELEMENTPTR13]], <8 x i64> [[SHUFFLEVECTOR]]
; CHECK-NEXT:    [[ICMP25:%.*]] = icmp ne <8 x ptr> [[GETELEMENTPTR24]], zeroinitializer
; CHECK-NEXT:    [[TMP0:%.*]] = add <8 x i64> [[DOTSPLAT]], [[PHI16]]
; CHECK-NEXT:    [[ICMP:%.*]] = icmp ne <8 x i64> [[GETELEMENTPTR19_IDX]], [[TMP0]]
; CHECK-NEXT:    [[ADD211:%.*]] = or <8 x i1> [[ICMP25]], [[ICMP]]
; CHECK-NEXT:    [[ADD21:%.*]] = zext <8 x i1> [[ADD211]] to <8 x i64>
; CHECK-NEXT:    ret <8 x i64> [[ADD21]]
;
bb:
  %getelementptr19 = getelementptr i64, ptr %arg1, <8 x i64> %add
  %getelementptr13 = getelementptr i64, ptr %arg1, i64 %mul
  %getelementptr20 = getelementptr i8, ptr %getelementptr13, <8 x i64> %phi16
  %getelementptr24 = getelementptr i8, ptr %getelementptr13, <8 x i64> %shufflevector
  %icmp25 = icmp ne <8 x ptr> zeroinitializer, %getelementptr24
  %zext26 = zext <8 x i1> %icmp25 to <8 x i64>
  %icmp = icmp ne <8 x ptr> %getelementptr19, %getelementptr20
  %zext = zext <8 x i1> %icmp to <8 x i64>
  %add21 = or <8 x i64> %zext26, %zext
  ret <8 x i64> %add21
}

