; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -p instcombine -S < %s | FileCheck %s

; Don't fold these intrinsics into the select as they're not speculatable.

define i32 @smul(i1 %b, i32 %x) {
; CHECK-LABEL: define i32 @smul(
; CHECK-SAME: i1 [[B:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:    [[S:%.*]] = select i1 [[B]], i32 0, i32 [[X]]
; CHECK-NEXT:    [[C:%.*]] = call i32 @llvm.smul.fix.i32(i32 [[S]], i32 42, i32 1)
; CHECK-NEXT:    ret i32 [[C]]
;
  %s = select i1 %b, i32 0, i32 %x
  %c = call i32 @llvm.smul.fix(i32 %s, i32 42, i32 1)
  ret i32 %c
}

define i32 @umul(i1 %b, i32 %x) {
; CHECK-LABEL: define i32 @umul(
; CHECK-SAME: i1 [[B:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:    [[S:%.*]] = select i1 [[B]], i32 0, i32 [[X]]
; CHECK-NEXT:    [[C:%.*]] = call i32 @llvm.umul.fix.i32(i32 [[S]], i32 42, i32 1)
; CHECK-NEXT:    ret i32 [[C]]
;
  %s = select i1 %b, i32 0, i32 %x
  %c = call i32 @llvm.umul.fix(i32 %s, i32 42, i32 1)
  ret i32 %c
}
