; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; Test that b - smin(b, a) is recognized as non-negative
define i64 @func1(i32 %a, i32 %b) {
; CHECK-LABEL: define i64 @func1(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[SPEC_SELECT:%.*]] = tail call i32 @llvm.smin.i32(i32 [[B]], i32 [[A]])
; CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 [[B]], [[SPEC_SELECT]]
; CHECK-NEXT:    [[CONV:%.*]] = zext nneg i32 [[SUB]] to i64
; CHECK-NEXT:    ret i64 [[CONV]]
;
entry:
  %spec.select = tail call i32 @llvm.smin.i32(i32 %b, i32 %a)
  %sub = sub nsw i32 %b, %spec.select
  %conv = sext i32 %sub to i64
  ret i64 %conv
}

; Test commutative smin pattern: b - smin(a, b) should also optimize
define i64 @smin_commutative(i32 %a, i32 %b) {
; CHECK-LABEL: define i64 @smin_commutative(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[MIN:%.*]] = call i32 @llvm.smin.i32(i32 [[A]], i32 [[B]])
; CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 [[B]], [[MIN]]
; CHECK-NEXT:    [[EXT:%.*]] = zext nneg i32 [[SUB]] to i64
; CHECK-NEXT:    ret i64 [[EXT]]
;
  %min = call i32 @llvm.smin.i32(i32 %a, i32 %b)
  %sub = sub nsw i32 %b, %min
  %ext = sext i32 %sub to i64
  ret i64 %ext
}

; NEGATIVE TEST: mismatched operands should not optimize
define i64 @smin_mismatch(i32 %a, i32 %b, i32 %c) {
; CHECK-LABEL: define i64 @smin_mismatch(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[C:%.*]]) {
; CHECK-NEXT:    [[MIN:%.*]] = call i32 @llvm.smin.i32(i32 [[B]], i32 [[C]])
; CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 [[A]], [[MIN]]
; CHECK-NEXT:    [[EXT:%.*]] = sext i32 [[SUB]] to i64
; CHECK-NEXT:    ret i64 [[EXT]]
;
  %min = call i32 @llvm.smin.i32(i32 %b, i32 %c)
  %sub = sub nsw i32 %a, %min
  %ext = sext i32 %sub to i64
  ret i64 %ext
}


; NEGATIVE TEST: unguarded subtraction should NOT optimize
define i64 @neg_unguarded_sub(i32 %a, i32 %b) {
; CHECK-LABEL: define i64 @neg_unguarded_sub(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 [[B]], [[A]]
; CHECK-NEXT:    [[EXT:%.*]] = sext i32 [[SUB]] to i64
; CHECK-NEXT:    ret i64 [[EXT]]
;
  %sub = sub nsw i32 %b, %a
  %ext = sext i32 %sub to i64
  ret i64 %ext
}
