; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; Simple round up to next multiple of power-of-2 pattern that may arise
; from div_ceil(X, P) * P.

define i32 @round_up_pow2_2(i32 %x) {
; CHECK-LABEL: define i32 @round_up_pow2_2(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[AND:%.*]] = shl i32 [[X]], 1
; CHECK-NEXT:    [[SEL:%.*]] = and i32 [[AND]], 2
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[SEL]], [[X]]
; CHECK-NEXT:    [[RES:%.*]] = and i32 [[ADD]], -2
; CHECK-NEXT:    ret i32 [[RES]]
;
  %and = and i32 %x, 1
  %cond = icmp eq i32 %and, 0
  %sel = select i1 %cond, i32 0, i32 2
  %add = add i32 %sel, %x
  %res = and i32 %add, -2
  ret i32 %res
}

define i32 @round_up_pow2_64(i32 %x) {
; CHECK-LABEL: define i32 @round_up_pow2_64(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[X]], 63
; CHECK-NEXT:    [[RES:%.*]] = and i32 [[TMP1]], -64
; CHECK-NEXT:    ret i32 [[RES]]
;
  %and = and i32 %x, 63
  %cond = icmp eq i32 %and, 0
  %sel = select i1 %cond, i32 0, i32 64
  %add = add i32 %sel, %x
  %res = and i32 %add, -64
  ret i32 %res
}

define i32 @round_up_pow2_add_commuted(i32 %x) {
; CHECK-LABEL: define i32 @round_up_pow2_add_commuted(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[X]], 63
; CHECK-NEXT:    [[RES:%.*]] = and i32 [[TMP1]], -64
; CHECK-NEXT:    ret i32 [[RES]]
;
  %and = and i32 %x, 63
  %cond = icmp eq i32 %and, 0
  %sel = select i1 %cond, i32 0, i32 64
  %add = add i32 %x, %sel
  %res = and i32 %add, -64
  ret i32 %res
}

define i32 @round_up_pow2_icmp_ne(i32 %x) {
; CHECK-LABEL: define i32 @round_up_pow2_icmp_ne(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[X]], 63
; CHECK-NEXT:    [[RES:%.*]] = and i32 [[TMP1]], -64
; CHECK-NEXT:    ret i32 [[RES]]
;
  %and = and i32 %x, 63
  %cond = icmp ne i32 %and, 0
  %sel = select i1 %cond, i32 64, i32 0
  %add = add i32 %sel, %x
  %res = and i32 %add, -64
  ret i32 %res
}

define <2 x i32> @round_up_pow2_vector(<2 x i32> %x) {
; CHECK-LABEL: define <2 x i32> @round_up_pow2_vector(
; CHECK-SAME: <2 x i32> [[X:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = add <2 x i32> [[X]], splat (i32 63)
; CHECK-NEXT:    [[RES:%.*]] = and <2 x i32> [[TMP1]], splat (i32 -64)
; CHECK-NEXT:    ret <2 x i32> [[RES]]
;
  %and = and <2 x i32> %x, <i32 63, i32 63>
  %cond = icmp eq <2 x i32> %and, zeroinitializer
  %sel = select <2 x i1> %cond, <2 x i32> zeroinitializer, <2 x i32> <i32 64, i32 64>
  %add = add <2 x i32> %sel, %x
  %res = and <2 x i32> %add, <i32 -64, i32 -64>
  ret <2 x i32> %res
}

define <2 x i32> @round_up_pow2_vector_icmp_ne(<2 x i32> %x) {
; CHECK-LABEL: define <2 x i32> @round_up_pow2_vector_icmp_ne(
; CHECK-SAME: <2 x i32> [[X:%.*]]) {
; CHECK-NEXT:    [[ADD:%.*]] = add <2 x i32> [[X]], splat (i32 63)
; CHECK-NEXT:    [[RES:%.*]] = and <2 x i32> [[ADD]], splat (i32 -64)
; CHECK-NEXT:    ret <2 x i32> [[RES]]
;
  %and = and <2 x i32> %x, <i32 63, i32 63>
  %cond = icmp ne <2 x i32> %and, zeroinitializer
  %sel = select <2 x i1> %cond, <2 x i32> <i32 64, i32 64>, <2 x i32> zeroinitializer
  %add = add <2 x i32> %sel, %x
  %res = and <2 x i32> %add, <i32 -64, i32 -64>
  ret <2 x i32> %res
}

define i32 @round_up_pow2_multiuse_and(i32 %x) {
; CHECK-LABEL: define i32 @round_up_pow2_multiuse_and(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[X]], 63
; CHECK-NEXT:    call void @use(i32 [[AND]])
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[X]], 63
; CHECK-NEXT:    [[RES:%.*]] = and i32 [[TMP1]], -64
; CHECK-NEXT:    ret i32 [[RES]]
;
  %and = and i32 %x, 63
  call void @use(i32 %and)
  %cond = icmp eq i32 %and, 0
  %sel = select i1 %cond, i32 0, i32 64
  %add = add i32 %sel, %x
  %res = and i32 %add, -64
  ret i32 %res
}

; Negative tests.

define i32 @round_up_pow2_multiuse_add(i32 %x) {
; CHECK-LABEL: define i32 @round_up_pow2_multiuse_add(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[X]], 63
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i32 [[AND]], 0
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[COND]], i32 0, i32 64
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[SEL]], [[X]]
; CHECK-NEXT:    call void @use(i32 [[ADD]])
; CHECK-NEXT:    [[RES:%.*]] = and i32 [[ADD]], -64
; CHECK-NEXT:    ret i32 [[RES]]
;
  %and = and i32 %x, 63
  %cond = icmp eq i32 %and, 0
  %sel = select i1 %cond, i32 0, i32 64
  %add = add i32 %sel, %x
  call void @use(i32 %add)
  %res = and i32 %add, -64
  ret i32 %res
}

define i32 @round_up_pow2_wrong_mask(i32 %x) {
; CHECK-LABEL: define i32 @round_up_pow2_wrong_mask(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[X]], 31
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i32 [[AND]], 0
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[COND]], i32 0, i32 64
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[SEL]], [[X]]
; CHECK-NEXT:    [[RES:%.*]] = and i32 [[ADD]], -64
; CHECK-NEXT:    ret i32 [[RES]]
;
  %and = and i32 %x, 31
  %cond = icmp eq i32 %and, 0
  %sel = select i1 %cond, i32 0, i32 64
  %add = add i32 %sel, %x
  %res = and i32 %add, -64
  ret i32 %res
}

define i32 @round_up_pow2_wrong_negated_pow2(i32 %x) {
; CHECK-LABEL: define i32 @round_up_pow2_wrong_negated_pow2(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[X]], 63
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i32 [[AND]], 0
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[COND]], i32 0, i32 64
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[SEL]], [[X]]
; CHECK-NEXT:    [[RES:%.*]] = and i32 [[ADD]], -63
; CHECK-NEXT:    ret i32 [[RES]]
;
  %and = and i32 %x, 63
  %cond = icmp eq i32 %and, 0
  %sel = select i1 %cond, i32 0, i32 64
  %add = add i32 %sel, %x
  %res = and i32 %add, -63
  ret i32 %res
}

define i32 @round_up_pow2_wrong_select_arms(i32 %x) {
; CHECK-LABEL: define i32 @round_up_pow2_wrong_select_arms(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[X]], 63
; CHECK-NEXT:    [[COND_NOT:%.*]] = icmp eq i32 [[AND]], 0
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[COND_NOT]], i32 64, i32 0
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[SEL]], [[X]]
; CHECK-NEXT:    [[RES:%.*]] = and i32 [[ADD]], -64
; CHECK-NEXT:    ret i32 [[RES]]
;
  %and = and i32 %x, 63
  %cond = icmp ne i32 %and, 0
  %sel = select i1 %cond, i32 0, i32 64
  %add = add i32 %sel, %x
  %res = and i32 %add, -64
  ret i32 %res
}

define i32 @round_up_pow2_wrong_predicate(i32 %x) {
; CHECK-LABEL: define i32 @round_up_pow2_wrong_predicate(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[X]], 63
; CHECK-NEXT:    [[COND_NOT:%.*]] = icmp eq i32 [[AND]], 0
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[COND_NOT]], i32 64, i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[SEL]], [[X]]
; CHECK-NEXT:    [[RES:%.*]] = and i32 [[TMP1]], -64
; CHECK-NEXT:    ret i32 [[RES]]
;
  %and = and i32 %x, 63
  %cond = icmp sgt i32 %and, 0
  %sel = select i1 %cond, i32 0, i32 64
  %add = add i32 %sel, %x
  %res = and i32 %add, -64
  ret i32 %res
}

define <2 x i32> @round_up_pow2_vector_poison_lane(<2 x i32> %x) {
; CHECK-LABEL: define <2 x i32> @round_up_pow2_vector_poison_lane(
; CHECK-SAME: <2 x i32> [[X:%.*]]) {
; CHECK-NEXT:    [[AND:%.*]] = and <2 x i32> [[X]], splat (i32 63)
; CHECK-NEXT:    [[COND:%.*]] = icmp eq <2 x i32> [[AND]], zeroinitializer
; CHECK-NEXT:    [[SEL:%.*]] = select <2 x i1> [[COND]], <2 x i32> zeroinitializer, <2 x i32> <i32 64, i32 poison>
; CHECK-NEXT:    [[ADD:%.*]] = add <2 x i32> [[SEL]], [[X]]
; CHECK-NEXT:    [[RES:%.*]] = and <2 x i32> [[ADD]], splat (i32 -64)
; CHECK-NEXT:    ret <2 x i32> [[RES]]
;
  %and = and <2 x i32> %x, <i32 63, i32 63>
  %cond = icmp eq <2 x i32> %and, zeroinitializer
  %sel = select <2 x i1> %cond, <2 x i32> zeroinitializer, <2 x i32> <i32 64, i32 poison>
  %add = add <2 x i32> %sel, %x
  %res = and <2 x i32> %add, <i32 -64, i32 -64>
  ret <2 x i32> %res
}

declare void @use(i32)
