; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=instcombine -S < %s -mtriple=x86_64-apple-macosx10.9 | FileCheck %s --check-prefixes=CHECK,CHECK-DOUBLE-ALIGN8
; RUN: opt -passes=instcombine -S < %s -mtriple=arm-apple-ios7.0 | FileCheck %s --check-prefixes=CHECK,CHECK-DOUBLE-ALIGN4
; RUN: opt -passes=instcombine -S < %s -mtriple=x86_64-none-linux-gnu | FileCheck %s --check-prefixes=CHECK,CHECK-DOUBLE-ALIGN8-LINUX
; RUN: opt -passes=instcombine -S < %s -mtriple=x86_64-apple-macosx10.9 -enable-double-float-shrink | FileCheck %s --check-prefixes=CHECK-SHRINK
; REQUIRES: arm-registered-target, x86-registered-target

declare float @sinf(float) #0
declare float @cosf(float) #0
declare double @sin(double) #0
declare double @cos(double) #0

@var32 = global float 0.0
@var64 = global double 0.0

; Basic sin+cos combination for float
define float @sincos_f32() {
; CHECK-LABEL: @sincos_f32(
; CHECK-NEXT:    [[VAL:%.*]] = load float, ptr @var32, align 4
; CHECK-NEXT:    [[SINCOS:%.*]] = call { float, float } @llvm.sincos.f32(float [[VAL]])
; CHECK-NEXT:    [[SIN:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-NEXT:    [[COS:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-NEXT:    [[RES:%.*]] = fadd float [[SIN]], [[COS]]
; CHECK-NEXT:    ret float [[RES]]
;
; CHECK-SHRINK-LABEL: @sincos_f32(
; CHECK-SHRINK-NEXT:    [[VAL:%.*]] = load float, ptr @var32, align 4
; CHECK-SHRINK-NEXT:    [[SINCOS:%.*]] = call { float, float } @llvm.sincos.f32(float [[VAL]])
; CHECK-SHRINK-NEXT:    [[SIN:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-SHRINK-NEXT:    [[COS:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-SHRINK-NEXT:    [[RES:%.*]] = fadd float [[SIN]], [[COS]]
; CHECK-SHRINK-NEXT:    ret float [[RES]]
;
  %val = load float, ptr @var32
  %s = call float @sinf(float %val) #0
  %c = call float @cosf(float %val) #0
  %res = fadd float %s, %c
  ret float %res
}

; Basic sin+cos combination for double
define double @sincos_f64() {
; CHECK-DOUBLE-ALIGN8-LABEL: @sincos_f64(
; CHECK-DOUBLE-ALIGN8-NEXT:    [[VAL:%.*]] = load double, ptr @var64, align 8
; CHECK-DOUBLE-ALIGN8-NEXT:    [[SINCOS:%.*]] = call { double, double } @llvm.sincos.f64(double [[VAL]])
; CHECK-DOUBLE-ALIGN8-NEXT:    [[SIN:%.*]] = extractvalue { double, double } [[SINCOS]], 0
; CHECK-DOUBLE-ALIGN8-NEXT:    [[COS:%.*]] = extractvalue { double, double } [[SINCOS]], 1
; CHECK-DOUBLE-ALIGN8-NEXT:    [[RES:%.*]] = fadd double [[SIN]], [[COS]]
; CHECK-DOUBLE-ALIGN8-NEXT:    ret double [[RES]]
;
; CHECK-DOUBLE-ALIGN4-LABEL: @sincos_f64(
; CHECK-DOUBLE-ALIGN4-NEXT:    [[VAL:%.*]] = load double, ptr @var64, align 4
; CHECK-DOUBLE-ALIGN4-NEXT:    [[SINCOS:%.*]] = call { double, double } @llvm.sincos.f64(double [[VAL]])
; CHECK-DOUBLE-ALIGN4-NEXT:    [[SIN:%.*]] = extractvalue { double, double } [[SINCOS]], 0
; CHECK-DOUBLE-ALIGN4-NEXT:    [[COS:%.*]] = extractvalue { double, double } [[SINCOS]], 1
; CHECK-DOUBLE-ALIGN4-NEXT:    [[RES:%.*]] = fadd double [[SIN]], [[COS]]
; CHECK-DOUBLE-ALIGN4-NEXT:    ret double [[RES]]
;
; CHECK-DOUBLE-ALIGN8-LINUX-LABEL: @sincos_f64(
; CHECK-DOUBLE-ALIGN8-LINUX-NEXT:    [[VAL:%.*]] = load double, ptr @var64, align 8
; CHECK-DOUBLE-ALIGN8-LINUX-NEXT:    [[SINCOS:%.*]] = call { double, double } @llvm.sincos.f64(double [[VAL]])
; CHECK-DOUBLE-ALIGN8-LINUX-NEXT:    [[SIN:%.*]] = extractvalue { double, double } [[SINCOS]], 0
; CHECK-DOUBLE-ALIGN8-LINUX-NEXT:    [[COS:%.*]] = extractvalue { double, double } [[SINCOS]], 1
; CHECK-DOUBLE-ALIGN8-LINUX-NEXT:    [[RES:%.*]] = fadd double [[SIN]], [[COS]]
; CHECK-DOUBLE-ALIGN8-LINUX-NEXT:    ret double [[RES]]
;
; CHECK-SHRINK-LABEL: @sincos_f64(
; CHECK-SHRINK-NEXT:    [[VAL:%.*]] = load double, ptr @var64, align 8
; CHECK-SHRINK-NEXT:    [[SINCOS:%.*]] = call { double, double } @llvm.sincos.f64(double [[VAL]])
; CHECK-SHRINK-NEXT:    [[SIN:%.*]] = extractvalue { double, double } [[SINCOS]], 0
; CHECK-SHRINK-NEXT:    [[COS:%.*]] = extractvalue { double, double } [[SINCOS]], 1
; CHECK-SHRINK-NEXT:    [[RES:%.*]] = fadd double [[SIN]], [[COS]]
; CHECK-SHRINK-NEXT:    ret double [[RES]]
;
  %val = load double, ptr @var64
  %s = call double @sin(double %val) #0
  %c = call double @cos(double %val) #0
  %res = fadd double %s, %c
  ret double %res
}

; Only sin, no cos - should NOT combine
define float @sin_only_f32(float %x) {
; CHECK-LABEL: @sin_only_f32(
; CHECK-NEXT:    [[S:%.*]] = call float @llvm.sin.f32(float [[X:%.*]])
; CHECK-NEXT:    ret float [[S]]
;
; CHECK-SHRINK-LABEL: @sin_only_f32(
; CHECK-SHRINK-NEXT:    [[S:%.*]] = call float @llvm.sin.f32(float [[X:%.*]])
; CHECK-SHRINK-NEXT:    ret float [[S]]
;
  %s = call float @sinf(float %x) #0
  ret float %s
}

; Only cos, no sin - should NOT combine
define float @cos_only_f32(float %x) {
; CHECK-LABEL: @cos_only_f32(
; CHECK-NEXT:    [[C:%.*]] = call float @llvm.cos.f32(float [[X:%.*]])
; CHECK-NEXT:    ret float [[C]]
;
; CHECK-SHRINK-LABEL: @cos_only_f32(
; CHECK-SHRINK-NEXT:    [[C:%.*]] = call float @llvm.cos.f32(float [[X:%.*]])
; CHECK-SHRINK-NEXT:    ret float [[C]]
;
  %c = call float @cosf(float %x) #0
  ret float %c
}

; Different arguments - should NOT combine
define float @sincos_different_args(float %x, float %y) {
; CHECK-LABEL: @sincos_different_args(
; CHECK-NEXT:    [[S:%.*]] = call float @llvm.sin.f32(float [[X:%.*]])
; CHECK-NEXT:    [[C:%.*]] = call float @llvm.cos.f32(float [[Y:%.*]])
; CHECK-NEXT:    [[RES:%.*]] = fadd float [[S]], [[C]]
; CHECK-NEXT:    ret float [[RES]]
;
; CHECK-SHRINK-LABEL: @sincos_different_args(
; CHECK-SHRINK-NEXT:    [[S:%.*]] = call float @llvm.sin.f32(float [[X:%.*]])
; CHECK-SHRINK-NEXT:    [[C:%.*]] = call float @llvm.cos.f32(float [[Y:%.*]])
; CHECK-SHRINK-NEXT:    [[RES:%.*]] = fadd float [[S]], [[C]]
; CHECK-SHRINK-NEXT:    ret float [[RES]]
;
  %s = call float @sinf(float %x) #0
  %c = call float @cosf(float %y) #0
  %res = fadd float %s, %c
  ret float %res
}

; Multiple uses of sin and cos results
define float @sincos_multi_use(float %x) {
; CHECK-LABEL: @sincos_multi_use(
; CHECK-NEXT:    [[SINCOS:%.*]] = call { float, float } @llvm.sincos.f32(float [[X:%.*]])
; CHECK-NEXT:    [[SIN:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-NEXT:    [[COS:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-NEXT:    [[ADD:%.*]] = fadd float [[SIN]], [[COS]]
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[SIN]], [[COS]]
; CHECK-NEXT:    [[RES:%.*]] = fadd float [[ADD]], [[MUL]]
; CHECK-NEXT:    ret float [[RES]]
;
; CHECK-SHRINK-LABEL: @sincos_multi_use(
; CHECK-SHRINK-NEXT:    [[SINCOS:%.*]] = call { float, float } @llvm.sincos.f32(float [[X:%.*]])
; CHECK-SHRINK-NEXT:    [[SIN:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-SHRINK-NEXT:    [[COS:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-SHRINK-NEXT:    [[ADD:%.*]] = fadd float [[SIN]], [[COS]]
; CHECK-SHRINK-NEXT:    [[MUL:%.*]] = fmul float [[SIN]], [[COS]]
; CHECK-SHRINK-NEXT:    [[RES:%.*]] = fadd float [[ADD]], [[MUL]]
; CHECK-SHRINK-NEXT:    ret float [[RES]]
;
  %s = call float @sinf(float %x) #0
  %c = call float @cosf(float %x) #0
  %add = fadd float %s, %c
  %mul = fmul float %s, %c
  %res = fadd float %add, %mul
  ret float %res
}

; Intrinsic sin + intrinsic cos - should combine
define float @sincos_intrinsic_f32(float %x) {
; CHECK-LABEL: @sincos_intrinsic_f32(
; CHECK-NEXT:    [[SINCOS:%.*]] = call { float, float } @llvm.sincos.f32(float [[X:%.*]])
; CHECK-NEXT:    [[S:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-NEXT:    [[C:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-NEXT:    [[RES:%.*]] = fadd float [[S]], [[C]]
; CHECK-NEXT:    ret float [[RES]]
;
; CHECK-SHRINK-LABEL: @sincos_intrinsic_f32(
; CHECK-SHRINK-NEXT:    [[SINCOS:%.*]] = call { float, float } @llvm.sincos.f32(float [[X:%.*]])
; CHECK-SHRINK-NEXT:    [[SIN:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-SHRINK-NEXT:    [[COS:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-SHRINK-NEXT:    [[RES:%.*]] = fadd float [[SIN]], [[COS]]
; CHECK-SHRINK-NEXT:    ret float [[RES]]
;
  %s = call float @llvm.sin.f32(float %x)
  %c = call float @llvm.cos.f32(float %x)
  %res = fadd float %s, %c
  ret float %res
}

; Mixed: libcall sin + intrinsic cos
define float @sincos_mixed_libcall_sin_intrinsic_cos(float %x) {
; CHECK-LABEL: @sincos_mixed_libcall_sin_intrinsic_cos(
; CHECK-NEXT:    [[SINCOS:%.*]] = call { float, float } @llvm.sincos.f32(float [[X:%.*]])
; CHECK-NEXT:    [[S:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-NEXT:    [[C:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-NEXT:    [[RES:%.*]] = fadd float [[S]], [[C]]
; CHECK-NEXT:    ret float [[RES]]
;
; CHECK-SHRINK-LABEL: @sincos_mixed_libcall_sin_intrinsic_cos(
; CHECK-SHRINK-NEXT:    [[SINCOS:%.*]] = call { float, float } @llvm.sincos.f32(float [[X:%.*]])
; CHECK-SHRINK-NEXT:    [[SIN:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-SHRINK-NEXT:    [[COS:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-SHRINK-NEXT:    [[RES:%.*]] = fadd float [[SIN]], [[COS]]
; CHECK-SHRINK-NEXT:    ret float [[RES]]
;
  %s = call float @sinf(float %x) #0
  %c = call float @llvm.cos.f32(float %x)
  %res = fadd float %s, %c
  ret float %res
}

; Mixed: intrinsic sin + libcall cos
define float @sincos_mixed_intrinsic_sin_libcall_cos(float %x) {
; CHECK-LABEL: @sincos_mixed_intrinsic_sin_libcall_cos(
; CHECK-NEXT:    [[SINCOS:%.*]] = call { float, float } @llvm.sincos.f32(float [[X:%.*]])
; CHECK-NEXT:    [[S:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-NEXT:    [[C:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-NEXT:    [[RES:%.*]] = fadd float [[S]], [[C]]
; CHECK-NEXT:    ret float [[RES]]
;
; CHECK-SHRINK-LABEL: @sincos_mixed_intrinsic_sin_libcall_cos(
; CHECK-SHRINK-NEXT:    [[SINCOS:%.*]] = call { float, float } @llvm.sincos.f32(float [[X:%.*]])
; CHECK-SHRINK-NEXT:    [[SIN:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-SHRINK-NEXT:    [[COS:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-SHRINK-NEXT:    [[RES:%.*]] = fadd float [[SIN]], [[COS]]
; CHECK-SHRINK-NEXT:    ret float [[RES]]
;
  %s = call float @llvm.sin.f32(float %x)
  %c = call float @cosf(float %x) #0
  %res = fadd float %s, %c
  ret float %res
}

; UnsafeFPShrink: sin(fpext float) -> fpext(sinf(float))
; This should trigger optimizeUnaryDoubleFP before converting to intrinsic.
define float @sin_double_to_float_shrink(float %x) {
; CHECK-LABEL: @sin_double_to_float_shrink(
; CHECK-NEXT:    [[EXT:%.*]] = fpext float [[X:%.*]] to double
; CHECK-NEXT:    [[S:%.*]] = call double @llvm.sin.f64(double [[EXT]])
; CHECK-NEXT:    [[TRUNC:%.*]] = fptrunc double [[S]] to float
; CHECK-NEXT:    ret float [[TRUNC]]
;
; CHECK-SHRINK-LABEL: @sin_double_to_float_shrink(
; CHECK-SHRINK-NEXT:    [[SINF:%.*]] = call float @llvm.sin.f32(float [[X:%.*]])
; CHECK-SHRINK-NEXT:    ret float [[SINF]]
;
  %ext = fpext float %x to double
  %s = call double @sin(double %ext) #0
  %trunc = fptrunc double %s to float
  ret float %trunc
}

; UnsafeFPShrink: cos(fpext float) -> fpext(cosf(float))
define float @cos_double_to_float_shrink(float %x) {
; CHECK-LABEL: @cos_double_to_float_shrink(
; CHECK-NEXT:    [[EXT:%.*]] = fpext float [[X:%.*]] to double
; CHECK-NEXT:    [[C:%.*]] = call double @llvm.cos.f64(double [[EXT]])
; CHECK-NEXT:    [[TRUNC:%.*]] = fptrunc double [[C]] to float
; CHECK-NEXT:    ret float [[TRUNC]]
;
; CHECK-SHRINK-LABEL: @cos_double_to_float_shrink(
; CHECK-SHRINK-NEXT:    [[COSF:%.*]] = call float @llvm.cos.f32(float [[X:%.*]])
; CHECK-SHRINK-NEXT:    ret float [[COSF]]
;
  %ext = fpext float %x to double
  %c = call double @cos(double %ext) #0
  %trunc = fptrunc double %c to float
  ret float %trunc
}

; UnsafeFPShrink + sincos: sin(fpext float) + cos(fpext float) should
; first shrink to sinf/cosf, then combine into llvm.sincos.f32.
define { float, float } @sincos_double_to_float_shrink(float %x) {
; CHECK-LABEL: @sincos_double_to_float_shrink(
; CHECK-NEXT:    [[EXT:%.*]] = fpext float [[X:%.*]] to double
; CHECK-NEXT:    [[SINCOS:%.*]] = call { double, double } @llvm.sincos.f64(double [[EXT]])
; CHECK-NEXT:    [[SIN:%.*]] = extractvalue { double, double } [[SINCOS]], 0
; CHECK-NEXT:    [[COS:%.*]] = extractvalue { double, double } [[SINCOS]], 1
; CHECK-NEXT:    [[ST:%.*]] = fptrunc double [[SIN]] to float
; CHECK-NEXT:    [[CT:%.*]] = fptrunc double [[COS]] to float
; CHECK-NEXT:    [[R0:%.*]] = insertvalue { float, float } poison, float [[ST]], 0
; CHECK-NEXT:    [[R1:%.*]] = insertvalue { float, float } [[R0]], float [[CT]], 1
; CHECK-NEXT:    ret { float, float } [[R1]]
;
; CHECK-SHRINK-LABEL: @sincos_double_to_float_shrink(
; CHECK-SHRINK-NEXT:    [[SINCOS:%.*]] = call { float, float } @llvm.sincos.f32(float [[X:%.*]])
; CHECK-SHRINK-NEXT:    ret { float, float } [[SINCOS]]
;
  %ext = fpext float %x to double
  %s = call double @sin(double %ext) #0
  %c = call double @cos(double %ext) #0
  %st = fptrunc double %s to float
  %ct = fptrunc double %c to float
  %r0 = insertvalue { float, float } poison, float %st, 0
  %r1 = insertvalue { float, float } %r0, float %ct, 1
  ret { float, float } %r1
}

; FMF flags should be intersected when combining sin and cos.
define float @sincos_fmf_intersect(float %x) {
; CHECK-LABEL: @sincos_fmf_intersect(
; CHECK-NEXT:    [[SINCOS:%.*]] = call nnan ninf { float, float } @llvm.sincos.f32(float [[X:%.*]])
; CHECK-NEXT:    [[S:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-NEXT:    [[C:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-NEXT:    [[RES:%.*]] = fadd float [[S]], [[C]]
; CHECK-NEXT:    ret float [[RES]]
;
; CHECK-SHRINK-LABEL: @sincos_fmf_intersect(
; CHECK-SHRINK-NEXT:    [[SINCOS:%.*]] = call nnan ninf { float, float } @llvm.sincos.f32(float [[X:%.*]])
; CHECK-SHRINK-NEXT:    [[SIN:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-SHRINK-NEXT:    [[COS:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-SHRINK-NEXT:    [[RES:%.*]] = fadd float [[SIN]], [[COS]]
; CHECK-SHRINK-NEXT:    ret float [[RES]]
;
  %s = call nnan ninf nsz float @llvm.sin.f32(float %x)
  %c = call nnan ninf arcp float @llvm.cos.f32(float %x)
  %res = fadd float %s, %c
  ret float %res
}

; If one of the calls has no FMF, the combined call should have no FMF either.
define float @sincos_fmf_one_unset(float %x) {
; CHECK-LABEL: @sincos_fmf_one_unset(
; CHECK-NEXT:    [[SINCOS:%.*]] = call { float, float } @llvm.sincos.f32(float [[X:%.*]])
; CHECK-NEXT:    [[S:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-NEXT:    [[C:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-NEXT:    [[RES:%.*]] = fadd float [[S]], [[C]]
; CHECK-NEXT:    ret float [[RES]]
;
; CHECK-SHRINK-LABEL: @sincos_fmf_one_unset(
; CHECK-SHRINK-NEXT:    [[SINCOS:%.*]] = call { float, float } @llvm.sincos.f32(float [[X:%.*]])
; CHECK-SHRINK-NEXT:    [[SIN:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-SHRINK-NEXT:    [[COS:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-SHRINK-NEXT:    [[RES:%.*]] = fadd float [[SIN]], [[COS]]
; CHECK-SHRINK-NEXT:    ret float [[RES]]
;
  %s = call fast float @llvm.sin.f32(float %x)
  %c = call float @llvm.cos.f32(float %x)
  %res = fadd float %s, %c
  ret float %res
}

; Vector sin+cos intrinsics with the same operand should be combined into a
; single vector sincos intrinsic.
define <4 x float> @sincos_v4f32(<4 x float> %x) {
; CHECK-LABEL: @sincos_v4f32(
; CHECK-NEXT:    [[SINCOS:%.*]] = call { <4 x float>, <4 x float> } @llvm.sincos.v4f32(<4 x float> [[X:%.*]])
; CHECK-NEXT:    [[SIN:%.*]] = extractvalue { <4 x float>, <4 x float> } [[SINCOS]], 0
; CHECK-NEXT:    [[COS:%.*]] = extractvalue { <4 x float>, <4 x float> } [[SINCOS]], 1
; CHECK-NEXT:    [[RES:%.*]] = fadd <4 x float> [[SIN]], [[COS]]
; CHECK-NEXT:    ret <4 x float> [[RES]]
;
; CHECK-SHRINK-LABEL: @sincos_v4f32(
; CHECK-SHRINK-NEXT:    [[SINCOS:%.*]] = call { <4 x float>, <4 x float> } @llvm.sincos.v4f32(<4 x float> [[X:%.*]])
; CHECK-SHRINK-NEXT:    [[SIN:%.*]] = extractvalue { <4 x float>, <4 x float> } [[SINCOS]], 0
; CHECK-SHRINK-NEXT:    [[COS:%.*]] = extractvalue { <4 x float>, <4 x float> } [[SINCOS]], 1
; CHECK-SHRINK-NEXT:    [[RES:%.*]] = fadd <4 x float> [[SIN]], [[COS]]
; CHECK-SHRINK-NEXT:    ret <4 x float> [[RES]]
;
  %s = call <4 x float> @llvm.sin.v4f32(<4 x float> %x)
  %c = call <4 x float> @llvm.cos.v4f32(<4 x float> %x)
  %res = fadd <4 x float> %s, %c
  ret <4 x float> %res
}

define <2 x double> @sincos_v2f64(<2 x double> %x) {
; CHECK-LABEL: @sincos_v2f64(
; CHECK-NEXT:    [[SINCOS:%.*]] = call { <2 x double>, <2 x double> } @llvm.sincos.v2f64(<2 x double> [[X:%.*]])
; CHECK-NEXT:    [[SIN:%.*]] = extractvalue { <2 x double>, <2 x double> } [[SINCOS]], 0
; CHECK-NEXT:    [[COS:%.*]] = extractvalue { <2 x double>, <2 x double> } [[SINCOS]], 1
; CHECK-NEXT:    [[RES:%.*]] = fadd <2 x double> [[SIN]], [[COS]]
; CHECK-NEXT:    ret <2 x double> [[RES]]
;
; CHECK-SHRINK-LABEL: @sincos_v2f64(
; CHECK-SHRINK-NEXT:    [[SINCOS:%.*]] = call { <2 x double>, <2 x double> } @llvm.sincos.v2f64(<2 x double> [[X:%.*]])
; CHECK-SHRINK-NEXT:    [[SIN:%.*]] = extractvalue { <2 x double>, <2 x double> } [[SINCOS]], 0
; CHECK-SHRINK-NEXT:    [[COS:%.*]] = extractvalue { <2 x double>, <2 x double> } [[SINCOS]], 1
; CHECK-SHRINK-NEXT:    [[RES:%.*]] = fadd <2 x double> [[SIN]], [[COS]]
; CHECK-SHRINK-NEXT:    ret <2 x double> [[RES]]
;
  %s = call <2 x double> @llvm.sin.v2f64(<2 x double> %x)
  %c = call <2 x double> @llvm.cos.v2f64(<2 x double> %x)
  %res = fadd <2 x double> %s, %c
  ret <2 x double> %res
}

; Same for scalable vectors.
define <vscale x 4 x float> @sincos_nxv4f32(<vscale x 4 x float> %x) {
; CHECK-LABEL: @sincos_nxv4f32(
; CHECK-NEXT:    [[SINCOS:%.*]] = call { <vscale x 4 x float>, <vscale x 4 x float> } @llvm.sincos.nxv4f32(<vscale x 4 x float> [[X:%.*]])
; CHECK-NEXT:    [[SIN:%.*]] = extractvalue { <vscale x 4 x float>, <vscale x 4 x float> } [[SINCOS]], 0
; CHECK-NEXT:    [[COS:%.*]] = extractvalue { <vscale x 4 x float>, <vscale x 4 x float> } [[SINCOS]], 1
; CHECK-NEXT:    [[RES:%.*]] = fadd <vscale x 4 x float> [[SIN]], [[COS]]
; CHECK-NEXT:    ret <vscale x 4 x float> [[RES]]
;
; CHECK-SHRINK-LABEL: @sincos_nxv4f32(
; CHECK-SHRINK-NEXT:    [[SINCOS:%.*]] = call { <vscale x 4 x float>, <vscale x 4 x float> } @llvm.sincos.nxv4f32(<vscale x 4 x float> [[X:%.*]])
; CHECK-SHRINK-NEXT:    [[SIN:%.*]] = extractvalue { <vscale x 4 x float>, <vscale x 4 x float> } [[SINCOS]], 0
; CHECK-SHRINK-NEXT:    [[COS:%.*]] = extractvalue { <vscale x 4 x float>, <vscale x 4 x float> } [[SINCOS]], 1
; CHECK-SHRINK-NEXT:    [[RES:%.*]] = fadd <vscale x 4 x float> [[SIN]], [[COS]]
; CHECK-SHRINK-NEXT:    ret <vscale x 4 x float> [[RES]]
;
  %s = call <vscale x 4 x float> @llvm.sin.nxv4f32(<vscale x 4 x float> %x)
  %c = call <vscale x 4 x float> @llvm.cos.nxv4f32(<vscale x 4 x float> %x)
  %res = fadd <vscale x 4 x float> %s, %c
  ret <vscale x 4 x float> %res
}

; FMF flags should still be intersected for vector sin/cos.
define <4 x float> @sincos_v4f32_fmf_intersect(<4 x float> %x) {
; CHECK-LABEL: @sincos_v4f32_fmf_intersect(
; CHECK-NEXT:    [[SINCOS:%.*]] = call nnan ninf { <4 x float>, <4 x float> } @llvm.sincos.v4f32(<4 x float> [[X:%.*]])
; CHECK-NEXT:    [[SIN:%.*]] = extractvalue { <4 x float>, <4 x float> } [[SINCOS]], 0
; CHECK-NEXT:    [[COS:%.*]] = extractvalue { <4 x float>, <4 x float> } [[SINCOS]], 1
; CHECK-NEXT:    [[RES:%.*]] = fadd <4 x float> [[SIN]], [[COS]]
; CHECK-NEXT:    ret <4 x float> [[RES]]
;
; CHECK-SHRINK-LABEL: @sincos_v4f32_fmf_intersect(
; CHECK-SHRINK-NEXT:    [[SINCOS:%.*]] = call nnan ninf { <4 x float>, <4 x float> } @llvm.sincos.v4f32(<4 x float> [[X:%.*]])
; CHECK-SHRINK-NEXT:    [[SIN:%.*]] = extractvalue { <4 x float>, <4 x float> } [[SINCOS]], 0
; CHECK-SHRINK-NEXT:    [[COS:%.*]] = extractvalue { <4 x float>, <4 x float> } [[SINCOS]], 1
; CHECK-SHRINK-NEXT:    [[RES:%.*]] = fadd <4 x float> [[SIN]], [[COS]]
; CHECK-SHRINK-NEXT:    ret <4 x float> [[RES]]
;
  %s = call nnan ninf nsz <4 x float> @llvm.sin.v4f32(<4 x float> %x)
  %c = call nnan ninf arcp <4 x float> @llvm.cos.v4f32(<4 x float> %x)
  %res = fadd <4 x float> %s, %c
  ret <4 x float> %res
}

; When the shared argument is a PHI but the block has more PHIs after it,
; the sincos call must be placed after all PHIs, not next to the argument.
; Otherwise it would be sandwiched between PHIs and produce malformed IR.
define float @sincos_arg_is_phi_with_following_phi(i1 %cond, float %a, float %b, float %c) {
; CHECK-LABEL: @sincos_arg_is_phi_with_following_phi(
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    br label [[MERGE:%.*]]
; CHECK:       else:
; CHECK-NEXT:    br label [[MERGE]]
; CHECK:       merge:
; CHECK-NEXT:    [[X:%.*]] = phi float [ [[A:%.*]], [[THEN]] ], [ [[B:%.*]], [[ELSE]] ]
; CHECK-NEXT:    [[Y:%.*]] = phi float [ [[B]], [[THEN]] ], [ [[C:%.*]], [[ELSE]] ]
; CHECK-NEXT:    [[SINCOS:%.*]] = call { float, float } @llvm.sincos.f32(float [[X]])
; CHECK-NEXT:    [[SIN:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-NEXT:    [[COS:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-NEXT:    [[SUM:%.*]] = fadd float [[SIN]], [[COS]]
; CHECK-NEXT:    [[RES:%.*]] = fadd float [[SUM]], [[Y]]
; CHECK-NEXT:    ret float [[RES]]
;
; CHECK-SHRINK-LABEL: @sincos_arg_is_phi_with_following_phi(
; CHECK-SHRINK-NEXT:    br i1 [[COND:%.*]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK-SHRINK:       then:
; CHECK-SHRINK-NEXT:    br label [[MERGE:%.*]]
; CHECK-SHRINK:       else:
; CHECK-SHRINK-NEXT:    br label [[MERGE]]
; CHECK-SHRINK:       merge:
; CHECK-SHRINK-NEXT:    [[X:%.*]] = phi float [ [[A:%.*]], [[THEN]] ], [ [[B:%.*]], [[ELSE]] ]
; CHECK-SHRINK-NEXT:    [[Y:%.*]] = phi float [ [[B]], [[THEN]] ], [ [[C:%.*]], [[ELSE]] ]
; CHECK-SHRINK-NEXT:    [[SINCOS:%.*]] = call { float, float } @llvm.sincos.f32(float [[X]])
; CHECK-SHRINK-NEXT:    [[SIN:%.*]] = extractvalue { float, float } [[SINCOS]], 0
; CHECK-SHRINK-NEXT:    [[COS:%.*]] = extractvalue { float, float } [[SINCOS]], 1
; CHECK-SHRINK-NEXT:    [[SUM:%.*]] = fadd float [[SIN]], [[COS]]
; CHECK-SHRINK-NEXT:    [[RES:%.*]] = fadd float [[SUM]], [[Y]]
; CHECK-SHRINK-NEXT:    ret float [[RES]]
;
  br i1 %cond, label %then, label %else
then:
  br label %merge
else:
  br label %merge
merge:
  %x = phi float [ %a, %then ], [ %b, %else ]
  %y = phi float [ %b, %then ], [ %c, %else ]
  %s = call float @llvm.sin.f32(float %x)
  %c0 = call float @llvm.cos.f32(float %x)
  %sum = fadd float %s, %c0
  %res = fadd float %sum, %y
  ret float %res
}

attributes #0 = { nounwind memory(none) }
