; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -p instcombine -S %s | FileCheck %s

define i64 @test_dereferenceable_assume(ptr %p, ptr %q, i1 %c.0) {
; CHECK-LABEL: define i64 @test_dereferenceable_assume(
; CHECK-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], i1 [[C_0:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C_0]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[Q_INT:%.*]] = ptrtoint ptr [[Q]] to i64
; CHECK-NEXT:    [[P_INT:%.*]] = ptrtoint ptr [[P]] to i64
; CHECK-NEXT:    [[DIFF:%.*]] = sub i64 [[Q_INT]], [[P_INT]]
; CHECK-NEXT:    ret i64 [[DIFF]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i64 0
;
entry:
  %p_int = ptrtoint ptr %p to i64
  %q_int = ptrtoint ptr %q to i64
  %diff = sub i64 %q_int, %p_int
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %p, i64 %diff) ]
  br i1 %c.0, label %then, label %else

then:
  ret i64 %diff

else:
  ret i64 0
}

define i64 @test_sink_with_dereferenceable_assume_same_block_as_user(ptr %p, ptr %q, i1 %c.0) {
; CHECK-LABEL: define i64 @test_sink_with_dereferenceable_assume_same_block_as_user(
; CHECK-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], i1 [[C_0:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C_0]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[Q_INT:%.*]] = ptrtoint ptr [[Q]] to i64
; CHECK-NEXT:    [[P_INT:%.*]] = ptrtoint ptr [[P]] to i64
; CHECK-NEXT:    [[DIFF:%.*]] = sub i64 [[Q_INT]], [[P_INT]]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "dereferenceable"(ptr [[P]], i64 [[DIFF]]) ]
; CHECK-NEXT:    ret i64 [[DIFF]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i64 0
;
entry:
  %p_int = ptrtoint ptr %p to i64
  %q_int = ptrtoint ptr %q to i64
  %diff = sub i64 %q_int, %p_int
  br i1 %c.0, label %then, label %else

then:
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %p, i64 %diff) ]
  ret i64 %diff

else:
  ret i64 0
}

define i64 @test_sink_with_multiple_users_dominated_by_deref(ptr %p, ptr %q, i1 %c.0, i1 %c.1) {
; CHECK-LABEL: define i64 @test_sink_with_multiple_users_dominated_by_deref(
; CHECK-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], i1 [[C_0:%.*]], i1 [[C_1:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C_0]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    br i1 [[C_1]], label %[[THEN_2:.*]], label %[[ELSE]]
; CHECK:       [[THEN_2]]:
; CHECK-NEXT:    [[Q_INT:%.*]] = ptrtoint ptr [[Q]] to i64
; CHECK-NEXT:    [[P_INT:%.*]] = ptrtoint ptr [[P]] to i64
; CHECK-NEXT:    [[DIFF:%.*]] = sub i64 [[Q_INT]], [[P_INT]]
; CHECK-NEXT:    [[DOUBLED:%.*]] = shl i64 [[DIFF]], 1
; CHECK-NEXT:    ret i64 [[DOUBLED]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i64 0
;
entry:
  %p_int = ptrtoint ptr %p to i64
  %q_int = ptrtoint ptr %q to i64
  %diff = sub i64 %q_int, %p_int
  br i1 %c.0, label %then, label %else

then:
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %p, i64 %diff) ]
  br i1 %c.1, label %then.2, label %else

then.2:
  %doubled = mul i64 %diff, 2
  ret i64 %doubled

else:
  ret i64 0
}

define i64 @test_deref_user_does_not_dominate_other_user(ptr %p, ptr %q, i1 %c.0) {
; CHECK-LABEL: define i64 @test_deref_user_does_not_dominate_other_user(
; CHECK-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], i1 [[C_0:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C_0]], label %[[MIDDLE:.*]], label %[[EXIT:.*]]
; CHECK:       [[MIDDLE]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[Q_INT:%.*]] = ptrtoint ptr [[Q]] to i64
; CHECK-NEXT:    [[P_INT:%.*]] = ptrtoint ptr [[P]] to i64
; CHECK-NEXT:    [[DIFF:%.*]] = sub i64 [[Q_INT]], [[P_INT]]
; CHECK-NEXT:    ret i64 [[DIFF]]
;
entry:
  %p_int = ptrtoint ptr %p to i64
  %q_int = ptrtoint ptr %q to i64
  %diff = sub i64 %q_int, %p_int
  br i1 %c.0, label %middle, label %exit

middle:
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %p, i64 %diff) ]
  br label %exit

exit:
  ret i64 %diff
}

declare void @llvm.assume(i1 noundef)
