; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; Tests for narrowing `store <N x T> <V0, ..., Vk-1, undef, ..., undef>, ptr %p`
; to a narrower store of just the defined prefix.

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"

;------------------------------------------------------------
; prefix of one defined lane, rest undef.
;------------------------------------------------------------

define void @narrow_v4f32_one_defined_prefix(ptr %p) {
; CHECK-LABEL: define void @narrow_v4f32_one_defined_prefix(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store float 1.000000e+00, ptr [[P]], align 16
; CHECK-NEXT:    ret void
;
  store <4 x float> <float 1.000000e+00, float undef, float undef, float undef>, ptr %p, align 16
  ret void
}

define void @narrow_v4i32_one_defined_prefix(ptr %p) {
; CHECK-LABEL: define void @narrow_v4i32_one_defined_prefix(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store i32 7, ptr [[P]], align 16
; CHECK-NEXT:    ret void
;
  store <4 x i32> <i32 7, i32 undef, i32 undef, i32 undef>, ptr %p, align 16
  ret void
}

define void @narrow_v2i64_one_defined_prefix(ptr %p) {
; CHECK-LABEL: define void @narrow_v2i64_one_defined_prefix(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store i64 42, ptr [[P]], align 16
; CHECK-NEXT:    ret void
;
  store <2 x i64> <i64 42, i64 undef>, ptr %p, align 16
  ret void
}

define void @narrow_v8i8_one_defined_prefix(ptr %p) {
; CHECK-LABEL: define void @narrow_v8i8_one_defined_prefix(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store i8 9, ptr [[P]], align 8
; CHECK-NEXT:    ret void
;
  store <8 x i8> <i8 9, i8 undef, i8 undef, i8 undef, i8 undef, i8 undef, i8 undef, i8 undef>, ptr %p, align 8
  ret void
}

;------------------------------------------------------------
; defined prefix of length > 1.
;------------------------------------------------------------

define void @narrow_v4i32_two_defined_prefix(ptr %p) {
; CHECK-LABEL: define void @narrow_v4i32_two_defined_prefix(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store <2 x i32> <i32 1, i32 2>, ptr [[P]], align 16
; CHECK-NEXT:    ret void
;
  store <4 x i32> <i32 1, i32 2, i32 undef, i32 undef>, ptr %p, align 16
  ret void
}

define void @narrow_v4i32_three_defined_prefix(ptr %p) {
; CHECK-LABEL: define void @narrow_v4i32_three_defined_prefix(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store <3 x i32> <i32 1, i32 2, i32 3>, ptr [[P]], align 16
; CHECK-NEXT:    ret void
;
  store <4 x i32> <i32 1, i32 2, i32 3, i32 undef>, ptr %p, align 16
  ret void
}

;------------------------------------------------------------
; prefix of one defined lane, rest poison.
;------------------------------------------------------------

define void @narrow_v4i32_poison_suffix(ptr %p) {
; CHECK-LABEL: define void @narrow_v4i32_poison_suffix(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store i32 7, ptr [[P]], align 16
; CHECK-NEXT:    ret void
;
  store <4 x i32> <i32 7, i32 poison, i32 poison, i32 poison>, ptr %p, align 16
  ret void
}

;------------------------------------------------------------
; underaligned store is still narrowable; alignment carries over.
;------------------------------------------------------------

define void @narrow_v4i32_underaligned(ptr %p) {
; CHECK-LABEL: define void @narrow_v4i32_underaligned(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store i32 7, ptr [[P]], align 1
; CHECK-NEXT:    ret void
;
  store <4 x i32> <i32 7, i32 undef, i32 undef, i32 undef>, ptr %p, align 1
  ret void
}

;------------------------------------------------------------
; all lanes defined -- nothing to narrow.
;------------------------------------------------------------

define void @all_defined(ptr %p) {
; CHECK-LABEL: define void @all_defined(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store <4 x i32> <i32 1, i32 2, i32 3, i32 4>, ptr [[P]], align 16
; CHECK-NEXT:    ret void
;
  store <4 x i32> <i32 1, i32 2, i32 3, i32 4>, ptr %p, align 16
  ret void
}

;------------------------------------------------------------
; defined lane in the middle, undef on both sides.
; We only narrow when the undef forms a trailing suffix.
;------------------------------------------------------------

define void @defined_in_middle(ptr %p) {
; CHECK-LABEL: define void @defined_in_middle(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store <4 x i32> <i32 undef, i32 7, i32 undef, i32 undef>, ptr [[P]], align 16
; CHECK-NEXT:    ret void
;
  store <4 x i32> <i32 undef, i32 7, i32 undef, i32 undef>, ptr %p, align 16
  ret void
}

define void @undef_in_middle(ptr %p) {
; CHECK-LABEL: define void @undef_in_middle(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store <4 x i32> <i32 1, i32 undef, i32 3, i32 undef>, ptr [[P]], align 16
; CHECK-NEXT:    ret void
;
  store <4 x i32> <i32 1, i32 undef, i32 3, i32 undef>, ptr %p, align 16
  ret void
}

;------------------------------------------------------------
; undef prefix, defined suffix. Conservatively do not narrow
; because it would require a new GEP.
;------------------------------------------------------------

define void @undef_prefix(ptr %p) {
; CHECK-LABEL: define void @undef_prefix(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store <4 x i32> <i32 undef, i32 undef, i32 undef, i32 7>, ptr [[P]], align 16
; CHECK-NEXT:    ret void
;
  store <4 x i32> <i32 undef, i32 undef, i32 undef, i32 7>, ptr %p, align 16
  ret void
}

;------------------------------------------------------------
; : volatile -- never narrow.
;------------------------------------------------------------

define void @volatile(ptr %p) {
; CHECK-LABEL: define void @volatile(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store volatile <4 x i32> <i32 7, i32 undef, i32 undef, i32 undef>, ptr [[P]], align 16
; CHECK-NEXT:    ret void
;
  store volatile <4 x i32> <i32 7, i32 undef, i32 undef, i32 undef>, ptr %p, align 16
  ret void
}

;------------------------------------------------------------
; : atomic -- never narrow.
;------------------------------------------------------------

define void @_atomic(ptr %p) {
; CHECK-LABEL: define void @_atomic(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store atomic <4 x i32> <i32 7, i32 undef, i32 undef, i32 undef>, ptr [[P]] monotonic, align 16
; CHECK-NEXT:    ret void
;
  store atomic <4 x i32> <i32 7, i32 undef, i32 undef, i32 undef>, ptr %p monotonic, align 16
  ret void
}

;------------------------------------------------------------
; non-constant stored value with an undef lane.
; TODO: could we optimize this?
;------------------------------------------------------------

define void @nonconstant_insertelement(ptr %p, float %x) {
; CHECK-LABEL: define void @nonconstant_insertelement(
; CHECK-SAME: ptr [[P:%.*]], float [[X:%.*]]) {
; CHECK-NEXT:    [[V:%.*]] = insertelement <4 x float> <float poison, float undef, float undef, float undef>, float [[X]], i64 0
; CHECK-NEXT:    store <4 x float> [[V]], ptr [[P]], align 16
; CHECK-NEXT:    ret void
;
  %v = insertelement <4 x float> undef, float %x, i32 0
  store <4 x float> %v, ptr %p, align 16
  ret void
}

;------------------------------------------------------------
; Metadata preservation: TBAA should be carried to the narrowed store.
;------------------------------------------------------------

define void @narrow_v4i32_with_tbaa(ptr %p) {
; CHECK-LABEL: define void @narrow_v4i32_with_tbaa(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store i32 7, ptr [[P]], align 16, !tbaa [[INT_TBAA0:![0-9]+]]
; CHECK-NEXT:    ret void
;
  store <4 x i32> <i32 7, i32 undef, i32 undef, i32 undef>, ptr %p, align 16, !tbaa !0
  ret void
}

!0 = !{!1, !1, i64 0}
!1 = !{!"int", !2, i64 0}
!2 = !{!"omnipotent char", !3, i64 0}
!3 = !{!"Simple C/C++ TBAA"}
;.
; CHECK: [[INT_TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; CHECK: [[META1]] = !{!"int", [[META2:![0-9]+]], i64 0}
; CHECK: [[META2]] = !{!"omnipotent char", [[META3:![0-9]+]], i64 0}
; CHECK: [[META3]] = !{!"Simple C/C++ TBAA"}
;.
