; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; Test that __strlen_chk simplification works correctly.
;
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:128:128"

@hello = constant [6 x i8] c"hello\00"
@hello_no_nul = constant [5 x i8] c"hello"

declare i32 @__strlen_chk(ptr, i32)

; Check __strlen_chk(string constant) -> strlen or constants

define i32 @unknown_str_known_object_size(ptr %c) {
; CHECK-LABEL: define i32 @unknown_str_known_object_size(
; CHECK-SAME: ptr [[C:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @__strlen_chk(ptr [[C]], i32 8)
; CHECK-NEXT:    ret i32 [[TMP1]]
;
  %1 = call i32 @__strlen_chk(ptr %c, i32 8)
  ret i32 %1
}

define i32 @known_str_known_object_size(ptr %c) {
; CHECK-LABEL: define i32 @known_str_known_object_size(
; CHECK-SAME: ptr [[C:%.*]]) {
; CHECK-NEXT:    ret i32 5
;
  %1 = call i32 @__strlen_chk(ptr @hello, i32 6)
  ret i32 %1
}

define i32 @known_str_too_small_object_size(ptr %c) {
; CHECK-LABEL: define i32 @known_str_too_small_object_size(
; CHECK-SAME: ptr [[C:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @__strlen_chk(ptr nonnull dereferenceable(6) @hello, i32 5)
; CHECK-NEXT:    ret i32 [[TMP1]]
;
  %1 = call i32 @__strlen_chk(ptr @hello, i32 5)
  ret i32 %1
}

define i32 @known_str_no_nul(ptr %c) {
; CHECK-LABEL: define i32 @known_str_no_nul(
; CHECK-SAME: ptr [[C:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @__strlen_chk(ptr nonnull dereferenceable(6) @hello_no_nul, i32 5)
; CHECK-NEXT:    ret i32 [[TMP1]]
;
  %1 = call i32 @__strlen_chk(ptr @hello_no_nul, i32 5)
  ret i32 %1
}

define i32 @unknown_str_unknown_object_size(ptr %c) {
; CHECK-LABEL: define i32 @unknown_str_unknown_object_size(
; CHECK-SAME: ptr [[C:%.*]]) {
; CHECK-NEXT:    [[STRLEN:%.*]] = call i32 @strlen(ptr noundef nonnull dereferenceable(1) [[C]])
; CHECK-NEXT:    ret i32 [[STRLEN]]
;
  %1 = call i32 @__strlen_chk(ptr %c, i32 -1)
  ret i32 %1
}
