; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; Tests for folding splice.right(splice.left(poison, x, offset), poison, offset) -> x

declare <4 x i32> @llvm.vector.splice.left.v4i32(<4 x i32>, <4 x i32>, i32)
declare <4 x i32> @llvm.vector.splice.right.v4i32(<4 x i32>, <4 x i32>, i32)
declare <vscale x 4 x i32> @llvm.vector.splice.left.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, i32)
declare <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, i32)

; Construct splice roundtrip on input and return it with set offset of 2
define <4 x i32> @splice_left_right_cancel_offset_2(<4 x i32> %x) {
; CHECK-LABEL: define <4 x i32> @splice_left_right_cancel_offset_2(
; CHECK-SAME: <4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    ret <4 x i32> [[X]]
;
  %l = call <4 x i32> @llvm.vector.splice.left.v4i32(<4 x i32> poison, <4 x i32> %x, i32 2)
  %r = call <4 x i32> @llvm.vector.splice.right.v4i32(<4 x i32> %l, <4 x i32> poison, i32 2)
  ret <4 x i32> %r
}

; Construct splice roundtrip on input and return it with set offset of 0
define <4 x i32> @splice_left_right_cancel_offset_0(<4 x i32> %x) {
; CHECK-LABEL: define <4 x i32> @splice_left_right_cancel_offset_0(
; CHECK-SAME: <4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    ret <4 x i32> poison
;
  %l = call <4 x i32> @llvm.vector.splice.left.v4i32(<4 x i32> poison, <4 x i32> %x, i32 0)
  %r = call <4 x i32> @llvm.vector.splice.right.v4i32(<4 x i32> %l, <4 x i32> poison, i32 0)
  ret <4 x i32> %r
}

define <4 x i32> @splice_left_right_cancel_offset_dynamic(<4 x i32> %x, i32 %offset) {
; CHECK-LABEL: define <4 x i32> @splice_left_right_cancel_offset_dynamic(
; CHECK-SAME: <4 x i32> [[X:%.*]], i32 [[OFFSET:%.*]]) {
; CHECK-NEXT:    ret <4 x i32> [[X]]
;
  %l = call <4 x i32> @llvm.vector.splice.left.v4i32(<4 x i32> poison, <4 x i32> %x, i32 %offset)
  %r = call <4 x i32> @llvm.vector.splice.right.v4i32(<4 x i32> %l, <4 x i32> poison, i32 %offset)
  ret <4 x i32> %r
}


define <vscale x 4 x i32> @splice_left_right_cancel_offset_2_scalable(<vscale x 4 x i32> %x) {
; CHECK-LABEL: define <vscale x 4 x i32> @splice_left_right_cancel_offset_2_scalable(
; CHECK-SAME: <vscale x 4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    ret <vscale x 4 x i32> [[X]]
;
  %l = call <vscale x 4 x i32> @llvm.vector.splice.left.nxv4i32(<vscale x 4 x i32> poison, <vscale x 4 x i32> %x, i32 2)
  %r = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> %l, <vscale x 4 x i32> poison, i32 2)
  ret <vscale x 4 x i32> %r
}

define <4 x i32> @splice_left_right_non_poison_inner(<4 x i32> %x, <4 x i32> %y) {
; CHECK-LABEL: define <4 x i32> @splice_left_right_non_poison_inner(
; CHECK-SAME: <4 x i32> [[X:%.*]], <4 x i32> [[Y:%.*]]) {
; CHECK-NEXT:    [[L:%.*]] = call <4 x i32> @llvm.vector.splice.left.v4i32(<4 x i32> [[Y]], <4 x i32> [[X]], i32 2)
; CHECK-NEXT:    [[R:%.*]] = call <4 x i32> @llvm.vector.splice.right.v4i32(<4 x i32> [[L]], <4 x i32> poison, i32 2)
; CHECK-NEXT:    ret <4 x i32> [[R]]
;
  %l = call <4 x i32> @llvm.vector.splice.left.v4i32(<4 x i32> %y, <4 x i32> %x, i32 2)
  %r = call <4 x i32> @llvm.vector.splice.right.v4i32(<4 x i32> %l, <4 x i32> poison, i32 2)
  ret <4 x i32> %r
}

define <4 x i32> @splice_left_right_non_poison_outer(<4 x i32> %x, <4 x i32> %y) {
; CHECK-LABEL: define <4 x i32> @splice_left_right_non_poison_outer(
; CHECK-SAME: <4 x i32> [[X:%.*]], <4 x i32> [[Y:%.*]]) {
; CHECK-NEXT:    [[L:%.*]] = call <4 x i32> @llvm.vector.splice.left.v4i32(<4 x i32> poison, <4 x i32> [[X]], i32 2)
; CHECK-NEXT:    [[R:%.*]] = call <4 x i32> @llvm.vector.splice.right.v4i32(<4 x i32> [[L]], <4 x i32> [[Y]], i32 2)
; CHECK-NEXT:    ret <4 x i32> [[R]]
;
  %l = call <4 x i32> @llvm.vector.splice.left.v4i32(<4 x i32> poison, <4 x i32> %x, i32 2)
  %r = call <4 x i32> @llvm.vector.splice.right.v4i32(<4 x i32> %l, <4 x i32> %y, i32 2)
  ret <4 x i32> %r
}

; Different offsets
define <4 x i32> @splice_left_right_cancel_mismatch_offset(<4 x i32> %x) {
; CHECK-LABEL: define <4 x i32> @splice_left_right_cancel_mismatch_offset(
; CHECK-SAME: <4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    [[L:%.*]] = call <4 x i32> @llvm.vector.splice.left.v4i32(<4 x i32> poison, <4 x i32> [[X]], i32 2)
; CHECK-NEXT:    [[R:%.*]] = call <4 x i32> @llvm.vector.splice.right.v4i32(<4 x i32> [[L]], <4 x i32> poison, i32 1)
; CHECK-NEXT:    ret <4 x i32> [[R]]
;
  %l = call <4 x i32> @llvm.vector.splice.left.v4i32(<4 x i32> poison, <4 x i32> %x, i32 2)
  %r = call <4 x i32> @llvm.vector.splice.right.v4i32(<4 x i32> %l, <4 x i32> poison, i32 1)
  ret <4 x i32> %r
}

define <4 x i32> @splice_right_then_left(<4 x i32> %x) {
; CHECK-LABEL: define <4 x i32> @splice_right_then_left(
; CHECK-SAME: <4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = call <4 x i32> @llvm.vector.splice.right.v4i32(<4 x i32> poison, <4 x i32> [[X]], i32 2)
; CHECK-NEXT:    [[L:%.*]] = call <4 x i32> @llvm.vector.splice.left.v4i32(<4 x i32> [[R]], <4 x i32> poison, i32 2)
; CHECK-NEXT:    ret <4 x i32> [[L]]
;
  %r = call <4 x i32> @llvm.vector.splice.right.v4i32(<4 x i32> poison, <4 x i32> %x, i32 2)
  %l = call <4 x i32> @llvm.vector.splice.left.v4i32(<4 x i32> %r, <4 x i32> poison, i32 2)
  ret <4 x i32> %l
}
