; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define <vscale x 2 x i1> @sge(<vscale x 2 x i8> %x) {
; CHECK-LABEL: @sge(
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt <vscale x 2 x i8> [[X:%.*]], splat (i8 -1)
; CHECK-NEXT:    ret <vscale x 2 x i1> [[CMP]]
;
  %cmp = icmp sge <vscale x 2 x i8> %x, zeroinitializer
  ret <vscale x 2 x i1> %cmp
}

define <vscale x 2 x i1> @gep_scalevector1(ptr %X) nounwind {
; CHECK-LABEL: @gep_scalevector1(
; CHECK-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 2 x ptr> poison, ptr [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq <vscale x 2 x ptr> [[DOTSPLATINSERT]], zeroinitializer
; CHECK-NEXT:    [[C:%.*]] = shufflevector <vscale x 2 x i1> [[TMP1]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    ret <vscale x 2 x i1> [[C]]
;
  %A = getelementptr inbounds i32, ptr %X, <vscale x 2 x i64> zeroinitializer
  %C = icmp eq <vscale x 2 x ptr> %A, zeroinitializer
  ret <vscale x 2 x i1> %C
}

define <vscale x 2 x i1> @signbit_bitcast_fpext_scalevec(<vscale x 2 x half> %x) {
; CHECK-LABEL: @signbit_bitcast_fpext_scalevec(
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <vscale x 2 x half> [[X:%.*]] to <vscale x 2 x i16>
; CHECK-NEXT:    [[R:%.*]] = icmp slt <vscale x 2 x i16> [[TMP1]], zeroinitializer
; CHECK-NEXT:    ret <vscale x 2 x i1> [[R]]
;
  %f = fpext <vscale x 2 x half> %x to <vscale x 2 x float>
  %b = bitcast <vscale x 2 x float> %f to <vscale x 2 x i32>
  %r = icmp slt <vscale x 2 x i32> %b, zeroinitializer
  ret <vscale x 2 x i1> %r
}
