; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define i32 @basic(i32 %a, i32 %x) {
; CHECK-LABEL: @basic(
; CHECK-NEXT:    [[A:%.*]] = and i32 [[X:%.*]], -2
; CHECK-NEXT:    [[R:%.*]] = xor i32 [[TMP1:%.*]], [[A]]
; CHECK-NEXT:    [[R1:%.*]] = xor i32 [[R]], 1
; CHECK-NEXT:    ret i32 [[R1]]
;
  %masked = and i32 %x, -2
  %xor0 = xor i32 %a, %masked
  %r = xor i32 %xor0, 1
  ret i32 %r
}

define i32 @outer_xor_commuted(i32 %a, i32 %x) {
; CHECK-LABEL: @outer_xor_commuted(
; CHECK-NEXT:    [[A:%.*]] = and i32 [[X:%.*]], -2
; CHECK-NEXT:    [[R:%.*]] = xor i32 [[TMP1:%.*]], [[A]]
; CHECK-NEXT:    [[R1:%.*]] = xor i32 [[R]], 1
; CHECK-NEXT:    ret i32 [[R1]]
;
  %masked = and i32 %x, -2
  %xor0 = xor i32 %a, %masked
  %r = xor i32 1, %xor0
  ret i32 %r
}

define i32 @multi_bit_mask(i32 %a, i32 %x) {
; CHECK-LABEL: @multi_bit_mask(
; CHECK-NEXT:    [[A:%.*]] = and i32 [[X:%.*]], -43
; CHECK-NEXT:    [[R:%.*]] = xor i32 [[TMP1:%.*]], [[A]]
; CHECK-NEXT:    [[R1:%.*]] = xor i32 [[R]], 42
; CHECK-NEXT:    ret i32 [[R1]]
;
  %masked = and i32 %x, -43
  %xor0 = xor i32 %a, %masked
  %r = xor i32 %xor0, 42
  ret i32 %r
}

define i64 @wide_constant(i64 %a, i64 %x) {
; CHECK-LABEL: @wide_constant(
; CHECK-NEXT:    [[A:%.*]] = and i64 [[X:%.*]], -4294967297
; CHECK-NEXT:    [[R:%.*]] = xor i64 [[TMP1:%.*]], [[A]]
; CHECK-NEXT:    [[R1:%.*]] = xor i64 [[R]], 4294967296
; CHECK-NEXT:    ret i64 [[R1]]
;
  %masked = and i64 %x, -4294967297
  %xor0 = xor i64 %a, %masked
  %r = xor i64 %xor0, 4294967296
  ret i64 %r
}

define <2 x i32> @splat_vector(<2 x i32> %a, <2 x i32> %x) {
; CHECK-LABEL: @splat_vector(
; CHECK-NEXT:    [[A:%.*]] = and <2 x i32> [[X:%.*]], splat (i32 -2)
; CHECK-NEXT:    [[R:%.*]] = xor <2 x i32> [[TMP1:%.*]], [[A]]
; CHECK-NEXT:    [[R1:%.*]] = xor <2 x i32> [[R]], splat (i32 1)
; CHECK-NEXT:    ret <2 x i32> [[R1]]
;
  %masked = and <2 x i32> %x, <i32 -2, i32 -2>
  %xor0 = xor <2 x i32> %a, %masked
  %r = xor <2 x i32> %xor0, <i32 1, i32 1>
  ret <2 x i32> %r
}

define i32 @inner_xor_commuted(i32 %a, i32 %x) {
; CHECK-LABEL: @inner_xor_commuted(
; CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[X:%.*]], -2
; CHECK-NEXT:    [[R:%.*]] = xor i32 [[TMP1]], [[A:%.*]]
; CHECK-NEXT:    [[R1:%.*]] = xor i32 [[R]], 1
; CHECK-NEXT:    ret i32 [[R1]]
;
  %masked = and i32 %x, -2
  %xor0 = xor i32 %masked, %a
  %r = xor i32 %xor0, 1
  ret i32 %r
}

define i32 @extra_use_of_inner_xor_negative(i32 %a, i32 %x, ptr %p) {
; CHECK-LABEL: @extra_use_of_inner_xor_negative(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[X:%.*]], -2
; CHECK-NEXT:    [[XOR0:%.*]] = xor i32 [[A:%.*]], [[MASKED]]
; CHECK-NEXT:    store i32 [[XOR0]], ptr [[P:%.*]], align 4
; CHECK-NEXT:    [[R:%.*]] = xor i32 [[XOR0]], 1
; CHECK-NEXT:    ret i32 [[R]]
;
  %masked = and i32 %x, -2
  %xor0 = xor i32 %a, %masked
  store i32 %xor0, ptr %p, align 4
  %r = xor i32 %xor0, 1
  ret i32 %r
}

define i32 @non_complement_mask_negative(i32 %a, i32 %x) {
; CHECK-LABEL: @non_complement_mask_negative(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[X:%.*]], -4
; CHECK-NEXT:    [[XOR0:%.*]] = xor i32 [[A:%.*]], [[MASKED]]
; CHECK-NEXT:    [[R:%.*]] = xor i32 [[XOR0]], 1
; CHECK-NEXT:    ret i32 [[R]]
;
  %masked = and i32 %x, -4
  %xor0 = xor i32 %a, %masked
  %r = xor i32 %xor0, 1
  ret i32 %r
}

define i32 @wrong_xor_constant_negative(i32 %a, i32 %x) {
; CHECK-LABEL: @wrong_xor_constant_negative(
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[X:%.*]], -2
; CHECK-NEXT:    [[XOR0:%.*]] = xor i32 [[A:%.*]], [[MASKED]]
; CHECK-NEXT:    [[R:%.*]] = xor i32 [[XOR0]], 2
; CHECK-NEXT:    ret i32 [[R]]
;
  %masked = and i32 %x, -2
  %xor0 = xor i32 %a, %masked
  %r = xor i32 %xor0, 2
  ret i32 %r
}
