; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; (A ^ (X & ~C)) ^ C --> (X | C) ^ A

define i32 @basic(i32 %a, i32 %x) {
; CHECK-LABEL: @basic(
; CHECK-NEXT:    [[TMP1:%.*]] = or i32 [[X:%.*]], 42
; CHECK-NEXT:    [[R:%.*]] = xor i32 [[TMP1]], [[A:%.*]]
; CHECK-NEXT:    ret i32 [[R]]
;
  %and = and i32 %x, -43
  %xor0 = xor i32 %a, %and
  %r = xor i32 %xor0, 42
  ret i32 %r
}

define i32 @outer_xor_commuted(i32 %a, i32 %x) {
; CHECK-LABEL: @outer_xor_commuted(
; CHECK-NEXT:    [[TMP1:%.*]] = or i32 [[X:%.*]], 42
; CHECK-NEXT:    [[R:%.*]] = xor i32 [[TMP1]], [[A:%.*]]
; CHECK-NEXT:    ret i32 [[R]]
;
  %and = and i32 %x, -43
  %xor0 = xor i32 %a, %and
  %r = xor i32 42, %xor0
  ret i32 %r
}

define i32 @inner_xor_commuted(i32 %a, i32 %x) {
; CHECK-LABEL: @inner_xor_commuted(
; CHECK-NEXT:    [[TMP1:%.*]] = or i32 [[X:%.*]], 42
; CHECK-NEXT:    [[R:%.*]] = xor i32 [[TMP1]], [[A:%.*]]
; CHECK-NEXT:    ret i32 [[R]]
;
  %and = and i32 %x, -43
  %xor0 = xor i32 %and, %a
  %r = xor i32 %xor0, 42
  ret i32 %r
}

define i32 @and_commuted(i32 %a, i32 %x) {
; CHECK-LABEL: @and_commuted(
; CHECK-NEXT:    [[TMP1:%.*]] = or i32 [[X:%.*]], 42
; CHECK-NEXT:    [[R:%.*]] = xor i32 [[TMP1]], [[A:%.*]]
; CHECK-NEXT:    ret i32 [[R]]
;
  %and = and i32 -43, %x
  %xor0 = xor i32 %a, %and
  %r = xor i32 %xor0, 42
  ret i32 %r
}

define <2 x i8> @vector_splat(<2 x i8> %a, <2 x i8> %x) {
; CHECK-LABEL: @vector_splat(
; CHECK-NEXT:    [[TMP1:%.*]] = or <2 x i8> [[X:%.*]], splat (i8 42)
; CHECK-NEXT:    [[R:%.*]] = xor <2 x i8> [[TMP1]], [[A:%.*]]
; CHECK-NEXT:    ret <2 x i8> [[R]]
;
  %and = and <2 x i8> %x, <i8 -43, i8 -43>
  %xor0 = xor <2 x i8> %a, %and
  %r = xor <2 x i8> %xor0, <i8 42, i8 42>
  ret <2 x i8> %r
}

define <2 x i8> @vector_non_splat(<2 x i8> %a, <2 x i8> %x) {
; CHECK-LABEL: @vector_non_splat(
; CHECK-NEXT:    [[TMP1:%.*]] = or <2 x i8> [[X:%.*]], <i8 42, i8 12>
; CHECK-NEXT:    [[R:%.*]] = xor <2 x i8> [[TMP1]], [[A:%.*]]
; CHECK-NEXT:    ret <2 x i8> [[R]]
;
  %and = and <2 x i8> %x, <i8 -43, i8 -13>
  %xor0 = xor <2 x i8> %a, %and
  %r = xor <2 x i8> %xor0, <i8 42, i8 12>
  ret <2 x i8> %r
}

define i32 @mismatched_const(i32 %a, i32 %x) {
; CHECK-LABEL: @mismatched_const(
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[X:%.*]], -44
; CHECK-NEXT:    [[XOR0:%.*]] = xor i32 [[A:%.*]], [[AND]]
; CHECK-NEXT:    [[R:%.*]] = xor i32 [[XOR0]], 42
; CHECK-NEXT:    ret i32 [[R]]
;
  %and = and i32 %x, -44
  %xor0 = xor i32 %a, %and
  %r = xor i32 %xor0, 42
  ret i32 %r
}

define i32 @and_extra_use(i32 %a, i32 %x, ptr %p) {
; CHECK-LABEL: @and_extra_use(
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[X:%.*]], -43
; CHECK-NEXT:    store i32 [[AND]], ptr [[P:%.*]], align 4
; CHECK-NEXT:    [[XOR0:%.*]] = xor i32 [[A:%.*]], [[AND]]
; CHECK-NEXT:    [[R:%.*]] = xor i32 [[XOR0]], 42
; CHECK-NEXT:    ret i32 [[R]]
;
  %and = and i32 %x, -43
  store i32 %and, ptr %p
  %xor0 = xor i32 %a, %and
  %r = xor i32 %xor0, 42
  ret i32 %r
}

define i32 @inner_xor_extra_use(i32 %a, i32 %x, ptr %p) {
; CHECK-LABEL: @inner_xor_extra_use(
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[X:%.*]], -43
; CHECK-NEXT:    [[XOR0:%.*]] = xor i32 [[A:%.*]], [[AND]]
; CHECK-NEXT:    store i32 [[XOR0]], ptr [[P:%.*]], align 4
; CHECK-NEXT:    [[R:%.*]] = xor i32 [[XOR0]], 42
; CHECK-NEXT:    ret i32 [[R]]
;
  %and = and i32 %x, -43
  %xor0 = xor i32 %a, %and
  store i32 %xor0, ptr %p
  %r = xor i32 %xor0, 42
  ret i32 %r
}
