; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

target datalayout = "n64:128"

; Range-aware udiv strength reduction: zext(udiv X, C) -> lshr(mul nuw(zext X, Magic), Shift)
; when the known range of X allows a simple magic-multiply approximation.

; Basic case: i8 udiv with bounded range from sub nuw, widened to i64.
; X = sub nuw 38, %t where %t is truncated from i32, so X in [0, 38].
define i64 @udiv_i8_to_i64(i32 range(i32 0, 32) %x) {
; CHECK-LABEL: @udiv_i8_to_i64(
; CHECK-NEXT:    [[NARROW:%.*]] = sub nuw nsw i32 38, [[X:%.*]]
; CHECK-NEXT:    [[NARROW1:%.*]] = mul nuw nsw i32 [[NARROW]], 37
; CHECK-NEXT:    [[TMP1:%.*]] = lshr i32 [[NARROW1]], 8
; CHECK-NEXT:    [[Z:%.*]] = zext nneg i32 [[TMP1]] to i64
; CHECK-NEXT:    ret i64 [[Z]]
;
  %t = trunc nuw nsw i32 %x to i8
  %s = sub nuw nsw i8 38, %t
  %d = udiv i8 %s, 7
  %z = zext i8 %d to i64
  ret i64 %z
}

; Bounded i32 range, div by 7, widened to i64.
define i64 @udiv_i32_bounded(i32 range(i32 0, 201) %x) {
; CHECK-LABEL: @udiv_i32_bounded(
; CHECK-NEXT:    [[NARROW:%.*]] = mul nuw nsw i32 [[X:%.*]], 293
; CHECK-NEXT:    [[D:%.*]] = lshr i32 [[NARROW]], 11
; CHECK-NEXT:    [[Z:%.*]] = zext nneg i32 [[D]] to i64
; CHECK-NEXT:    ret i64 [[Z]]
;
  %d = udiv i32 %x, 7
  %z = zext i32 %d to i64
  ret i64 %z
}

; Bounded i16 range, div by 3, widened to i32.
define i32 @udiv_i16_to_i32(i16 range(i16 0, 100) %x) {
; CHECK-LABEL: @udiv_i16_to_i32(
; CHECK-NEXT:    [[NARROW:%.*]] = mul nuw nsw i16 [[X:%.*]], 43
; CHECK-NEXT:    [[D:%.*]] = lshr i16 [[NARROW]], 7
; CHECK-NEXT:    [[Z:%.*]] = zext nneg i16 [[D]] to i32
; CHECK-NEXT:    ret i32 [[Z]]
;
  %d = udiv i16 %x, 3
  %z = zext i16 %d to i32
  ret i32 %z
}

; Negative: full i8 range has no known range reduction, backend handles it.
define i64 @neg_full_range(i8 %x) {
; CHECK-LABEL: @neg_full_range(
; CHECK-NEXT:    [[D:%.*]] = udiv i8 [[X:%.*]], 7
; CHECK-NEXT:    [[Z:%.*]] = zext nneg i8 [[D]] to i64
; CHECK-NEXT:    ret i64 [[Z]]
;
  %d = udiv i8 %x, 7
  %z = zext i8 %d to i64
  ret i64 %z
}

; Negative: C = 1, division is identity.
define i64 @neg_div_by_one(i8 range(i8 0, 39) %x) {
; CHECK-LABEL: @neg_div_by_one(
; CHECK-NEXT:    [[Z:%.*]] = zext nneg i8 [[X:%.*]] to i64
; CHECK-NEXT:    ret i64 [[Z]]
;
  %d = udiv i8 %x, 1
  %z = zext i8 %d to i64
  ret i64 %z
}

; Negative: sibling urem with same divisor, do not run.
define i64 @neg_sibling_urem(i32 range(i32 1, 129) %x) {
; CHECK-LABEL: @neg_sibling_urem(
; CHECK-NEXT:    [[D:%.*]] = udiv i32 [[X:%.*]], 7
; CHECK-NEXT:    [[R:%.*]] = urem i32 [[X]], 7
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i32 [[R]], 0
; CHECK-NEXT:    [[ADJ:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    [[ADD:%.*]] = add nuw nsw i32 [[D]], [[ADJ]]
; CHECK-NEXT:    [[Z:%.*]] = zext nneg i32 [[ADD]] to i64
; CHECK-NEXT:    ret i64 [[Z]]
;
  %d = udiv i32 %x, 7
  %r = urem i32 %x, 7
  %cmp = icmp ne i32 %r, 0
  %adj = zext i1 %cmp to i32
  %add = add i32 %d, %adj
  %z = zext i32 %add to i64
  ret i64 %z
}

; Negative: multi-use udiv is not safe to destroy.
define i64 @neg_multi_use(i32 range(i32 0, 201) %x) {
; CHECK-LABEL: @neg_multi_use(
; CHECK-NEXT:    [[D:%.*]] = udiv i32 [[X:%.*]], 7
; CHECK-NEXT:    call void @use32(i32 [[D]])
; CHECK-NEXT:    [[Z:%.*]] = zext nneg i32 [[D]] to i64
; CHECK-NEXT:    ret i64 [[Z]]
;
  %d = udiv i32 %x, 7
  call void @use32(i32 %d)
  %z = zext i32 %d to i64
  ret i64 %z
}

; Negative: same type (no widening).
define i32 @neg_same_type(i32 range(i32 0, 201) %x) {
; CHECK-LABEL: @neg_same_type(
; CHECK-NEXT:    [[D:%.*]] = udiv i32 [[X:%.*]], 7
; CHECK-NEXT:    ret i32 [[D]]
;
  %d = udiv i32 %x, 7
  ret i32 %d
}

declare void @use32(i32)
