# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=mipsel-linux-gnu -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s -check-prefixes=MIPS32
---
name:            load_i32
alignment:       4
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $a0

    ; MIPS32-LABEL: name: load_i32
    ; MIPS32: liveins: $a0
    ; MIPS32-NEXT: {{  $}}
    ; MIPS32-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $a0
    ; MIPS32-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32))
    ; MIPS32-NEXT: $v0 = COPY [[LOAD]](s32)
    ; MIPS32-NEXT: RetRA implicit $v0
    %0:_(p0) = COPY $a0
    %1:_(s32) = G_LOAD %0(p0) :: (load (s32))
    $v0 = COPY %1(s32)
    RetRA implicit $v0

...
---
name:            load_i64
alignment:       4
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $a0

    ; MIPS32-LABEL: name: load_i64
    ; MIPS32: liveins: $a0
    ; MIPS32-NEXT: {{  $}}
    ; MIPS32-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $a0
    ; MIPS32-NEXT: [[LOAD:%[0-9]+]]:_(s64) = G_LOAD [[COPY]](p0) :: (load (s64))
    ; MIPS32-NEXT: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[LOAD]](s64)
    ; MIPS32-NEXT: $v0 = COPY [[UV]](s32)
    ; MIPS32-NEXT: $v1 = COPY [[UV1]](s32)
    ; MIPS32-NEXT: RetRA implicit $v0, implicit $v1
    %0:_(p0) = COPY $a0
    %1:_(s64) = G_LOAD %0(p0) :: (load (s64))
    %2:_(s32), %3:_(s32) = G_UNMERGE_VALUES %1(s64)
    $v0 = COPY %2(s32)
    $v1 = COPY %3(s32)
    RetRA implicit $v0, implicit $v1

...
---
name:            load_float
alignment:       4
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $a0

    ; MIPS32-LABEL: name: load_float
    ; MIPS32: liveins: $a0
    ; MIPS32-NEXT: {{  $}}
    ; MIPS32-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $a0
    ; MIPS32-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[COPY]](p0) :: (load (s32))
    ; MIPS32-NEXT: $f0 = COPY [[LOAD]](s32)
    ; MIPS32-NEXT: RetRA implicit $f0
    %0:_(p0) = COPY $a0
    %1:_(s32) = G_LOAD %0(p0) :: (load (s32))
    $f0 = COPY %1(s32)
    RetRA implicit $f0

...
---
name:            load_double
alignment:       4
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $a0

    ; MIPS32-LABEL: name: load_double
    ; MIPS32: liveins: $a0
    ; MIPS32-NEXT: {{  $}}
    ; MIPS32-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $a0
    ; MIPS32-NEXT: [[LOAD:%[0-9]+]]:_(s64) = G_LOAD [[COPY]](p0) :: (load (s64))
    ; MIPS32-NEXT: $d0 = COPY [[LOAD]](s64)
    ; MIPS32-NEXT: RetRA implicit $d0
    %0:_(p0) = COPY $a0
    %1:_(s64) = G_LOAD %0(p0) :: (load (s64))
    $d0 = COPY %1(s64)
    RetRA implicit $d0

...
