; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=lower-target-intrinsics -mtriple=x86_64-unknown-linux -mcpu=haswell < %s | FileCheck %s --check-prefix=HASWELL
; RUN: opt -S -passes=lower-target-intrinsics -mtriple=x86_64-unknown-linux < %s | FileCheck %s --check-prefix=DEFAULT

; Complex control flow tests to ensure all dead blocks are removed.

declare void @avx2_path()
declare void @avx512_path()
declare void @fallback_path()
declare void @common_work()
declare i32 @get_val()
declare void @sse2_only_path()
declare void @avx2_and_sse2_path()

define void @test_loop_with_check(i32 %n) {
; HASWELL-LABEL: define void @test_loop_with_check(
; HASWELL-SAME: i32 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; HASWELL-NEXT:  [[ENTRY:.*]]:
; HASWELL-NEXT:    br label %[[LOOP_HEADER:.*]]
; HASWELL:       [[LOOP_HEADER]]:
; HASWELL-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; HASWELL-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I]], [[N]]
; HASWELL-NEXT:    br i1 [[CMP]], label %[[LOOP_BODY:.*]], label %[[EXIT:.*]]
; HASWELL:       [[LOOP_BODY]]:
; HASWELL-NEXT:    br label %[[AVX2_BB:.*]]
; HASWELL:       [[AVX2_BB]]:
; HASWELL-NEXT:    call void @avx2_path()
; HASWELL-NEXT:    br label %[[LOOP_LATCH]]
; HASWELL:       [[LOOP_LATCH]]:
; HASWELL-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; HASWELL-NEXT:    br label %[[LOOP_HEADER]]
; HASWELL:       [[EXIT]]:
; HASWELL-NEXT:    ret void
;
; DEFAULT-LABEL: define void @test_loop_with_check(
; DEFAULT-SAME: i32 [[N:%.*]]) {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    br label %[[LOOP_HEADER:.*]]
; DEFAULT:       [[LOOP_HEADER]]:
; DEFAULT-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; DEFAULT-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I]], [[N]]
; DEFAULT-NEXT:    br i1 [[CMP]], label %[[LOOP_BODY:.*]], label %[[EXIT:.*]]
; DEFAULT:       [[LOOP_BODY]]:
; DEFAULT-NEXT:    br label %[[FALLBACK_BB:.*]]
; DEFAULT:       [[FALLBACK_BB]]:
; DEFAULT-NEXT:    call void @fallback_path()
; DEFAULT-NEXT:    br label %[[LOOP_LATCH]]
; DEFAULT:       [[LOOP_LATCH]]:
; DEFAULT-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; DEFAULT-NEXT:    br label %[[LOOP_HEADER]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
entry:
  br label %loop.header

loop.header:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop.latch ]
  %cmp = icmp slt i32 %i, %n
  br i1 %cmp, label %loop.body, label %exit

loop.body:
  %has_avx2 = call i1 @llvm.target.has.feature(metadata !"avx2")
  br i1 %has_avx2, label %avx2.bb, label %fallback.bb

avx2.bb:
  call void @avx2_path()
  br label %loop.latch

fallback.bb:
  call void @fallback_path()
  br label %loop.latch

loop.latch:
  %i.next = add i32 %i, 1
  br label %loop.header

exit:
  ret void
}

define void @test_multiple_checks() {
; HASWELL-LABEL: define void @test_multiple_checks(
; HASWELL-SAME: ) #[[ATTR0]] {
; HASWELL-NEXT:  [[ENTRY:.*:]]
; HASWELL-NEXT:    br label %[[DO_AVX2:.*]]
; HASWELL:       [[DO_AVX2]]:
; HASWELL-NEXT:    call void @avx2_path()
; HASWELL-NEXT:    br label %[[CHECK_AVX512:.*]]
; HASWELL:       [[CHECK_AVX512]]:
; HASWELL-NEXT:    br label %[[SKIP_AVX512:.*]]
; HASWELL:       [[SKIP_AVX512]]:
; HASWELL-NEXT:    call void @common_work()
; HASWELL-NEXT:    br label %[[DONE:.*]]
; HASWELL:       [[DONE]]:
; HASWELL-NEXT:    ret void
;
; DEFAULT-LABEL: define void @test_multiple_checks() {
; DEFAULT-NEXT:  [[ENTRY:.*:]]
; DEFAULT-NEXT:    br label %[[SKIP_AVX2:.*]]
; DEFAULT:       [[SKIP_AVX2]]:
; DEFAULT-NEXT:    br label %[[CHECK_AVX512:.*]]
; DEFAULT:       [[CHECK_AVX512]]:
; DEFAULT-NEXT:    br label %[[SKIP_AVX512:.*]]
; DEFAULT:       [[SKIP_AVX512]]:
; DEFAULT-NEXT:    call void @common_work()
; DEFAULT-NEXT:    br label %[[DONE:.*]]
; DEFAULT:       [[DONE]]:
; DEFAULT-NEXT:    ret void
;
entry:
  %has_avx2 = call i1 @llvm.target.has.feature(metadata !"avx2")
  br i1 %has_avx2, label %do_avx2, label %skip_avx2

do_avx2:
  call void @avx2_path()
  br label %check_avx512

skip_avx2:
  br label %check_avx512

check_avx512:
  %has_avx512 = call i1 @llvm.target.has.feature(metadata !"avx512f")
  br i1 %has_avx512, label %do_avx512, label %skip_avx512

do_avx512:
  call void @avx512_path()
  br label %done

skip_avx512:
  call void @common_work()
  br label %done

done:
  ret void
}

define i32 @test_phi_propagation() {
; CHECK-LABEL: define i32 @test_phi_propagation(
; CHECK-SAME: ) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret i32 1
;
; HASWELL-LABEL: define i32 @test_phi_propagation(
; HASWELL-SAME: ) #[[ATTR0]] {
; HASWELL-NEXT:  [[ENTRY:.*:]]
; HASWELL-NEXT:    ret i32 1
;
; DEFAULT-LABEL: define i32 @test_phi_propagation() {
; DEFAULT-NEXT:  [[ENTRY:.*:]]
; DEFAULT-NEXT:    ret i32 0
;
entry:
  %has_avx2 = call i1 @llvm.target.has.feature(metadata !"avx2")
  %val = zext i1 %has_avx2 to i32
  ret i32 %val
}

define void @test_cascade() {
; HASWELL-LABEL: define void @test_cascade(
; HASWELL-SAME: ) #[[ATTR0]] {
; HASWELL-NEXT:  [[ENTRY:.*:]]
; HASWELL-NEXT:    br label %[[TRY_AVX2:.*]]
; HASWELL:       [[TRY_AVX2]]:
; HASWELL-NEXT:    br label %[[USE_AVX2:.*]]
; HASWELL:       [[USE_AVX2]]:
; HASWELL-NEXT:    call void @avx2_path()
; HASWELL-NEXT:    br label %[[DONE:.*]]
; HASWELL:       [[DONE]]:
; HASWELL-NEXT:    ret void
;
; DEFAULT-LABEL: define void @test_cascade() {
; DEFAULT-NEXT:  [[ENTRY:.*:]]
; DEFAULT-NEXT:    br label %[[TRY_AVX2:.*]]
; DEFAULT:       [[TRY_AVX2]]:
; DEFAULT-NEXT:    br label %[[USE_FALLBACK:.*]]
; DEFAULT:       [[USE_FALLBACK]]:
; DEFAULT-NEXT:    call void @fallback_path()
; DEFAULT-NEXT:    br label %[[DONE:.*]]
; DEFAULT:       [[DONE]]:
; DEFAULT-NEXT:    ret void
;
entry:
  %has_avx512 = call i1 @llvm.target.has.feature(metadata !"avx512f")
  br i1 %has_avx512, label %use_avx512, label %try_avx2

use_avx512:
  call void @avx512_path()
  br label %done

try_avx2:
  %has_avx2 = call i1 @llvm.target.has.feature(metadata !"avx2")
  br i1 %has_avx2, label %use_avx2, label %use_fallback

use_avx2:
  call void @avx2_path()
  br label %done

use_fallback:
  call void @fallback_path()
  br label %done

done:
  ret void
}

define void @test_branch_fold() {
; HASWELL-LABEL: define void @test_branch_fold(
; HASWELL-SAME: ) #[[ATTR0]] {
; HASWELL-NEXT:  [[ENTRY:.*:]]
; HASWELL-NEXT:    br label %[[AVX2_BB:.*]]
; HASWELL:       [[AVX2_BB]]:
; HASWELL-NEXT:    call void @avx2_path()
; HASWELL-NEXT:    ret void
;
; DEFAULT-LABEL: define void @test_branch_fold() {
; DEFAULT-NEXT:  [[ENTRY:.*:]]
; DEFAULT-NEXT:    br label %[[FALLBACK_BB:.*]]
; DEFAULT:       [[FALLBACK_BB]]:
; DEFAULT-NEXT:    call void @fallback_path()
; DEFAULT-NEXT:    ret void
;
; GENERIC-LABEL: @test_branch_fold(
; GENERIC-NOT:   @avx2_path
; GENERIC:       call void @fallback_path()
; GENERIC-NEXT:  ret void
entry:
  %has_avx2 = call i1 @llvm.target.has.feature(metadata !"avx2")
  br i1 %has_avx2, label %avx2.bb, label %fallback.bb

avx2.bb:
  call void @avx2_path()
  ret void

fallback.bb:
  call void @fallback_path()
  ret void
}

define i32 @test_diamond_phi(i32 %x) {
; HASWELL-LABEL: define i32 @test_diamond_phi(
; HASWELL-SAME: i32 [[X:%.*]]) #[[ATTR0]] {
; HASWELL-NEXT:  [[ENTRY:.*:]]
; HASWELL-NEXT:    br label %[[AVX2_BB:.*]]
; HASWELL:       [[AVX2_BB]]:
; HASWELL-NEXT:    call void @avx2_path()
; HASWELL-NEXT:    br label %[[MERGE:.*]]
; HASWELL:       [[MERGE]]:
; HASWELL-NEXT:    ret i32 42
;
; DEFAULT-LABEL: define i32 @test_diamond_phi(
; DEFAULT-SAME: i32 [[X:%.*]]) {
; DEFAULT-NEXT:  [[ENTRY:.*:]]
; DEFAULT-NEXT:    br label %[[FALLBACK_BB:.*]]
; DEFAULT:       [[FALLBACK_BB]]:
; DEFAULT-NEXT:    call void @fallback_path()
; DEFAULT-NEXT:    br label %[[MERGE:.*]]
; DEFAULT:       [[MERGE]]:
; DEFAULT-NEXT:    ret i32 99
;
; GENERIC-LABEL: @test_diamond_phi(
; GENERIC-NOT:   @avx2_path
; GENERIC:       call void @fallback_path()
; GENERIC:       ret i32 99
entry:
  %has_avx2 = call i1 @llvm.target.has.feature(metadata !"avx2")
  br i1 %has_avx2, label %avx2.bb, label %fallback.bb

avx2.bb:
  call void @avx2_path()
  br label %merge

fallback.bb:
  call void @fallback_path()
  br label %merge

merge:
  %result = phi i32 [ 42, %avx2.bb ], [ 99, %fallback.bb ]
  ret i32 %result
}

define void @test_nested_branch() {
; HASWELL-LABEL: define void @test_nested_branch(
; HASWELL-SAME: ) #[[ATTR0]] {
; HASWELL-NEXT:  [[ENTRY:.*:]]
; HASWELL-NEXT:    br label %[[CHECK_SSE2:.*]]
; HASWELL:       [[CHECK_SSE2]]:
; HASWELL-NEXT:    br label %[[BOTH:.*]]
; HASWELL:       [[BOTH]]:
; HASWELL-NEXT:    call void @avx2_and_sse2_path()
; HASWELL-NEXT:    ret void
;
; DEFAULT-LABEL: define void @test_nested_branch() {
; DEFAULT-NEXT:  [[ENTRY:.*:]]
; DEFAULT-NEXT:    br label %[[NO_AVX2:.*]]
; DEFAULT:       [[NO_AVX2]]:
; DEFAULT-NEXT:    br label %[[SSE2_ONLY:.*]]
; DEFAULT:       [[SSE2_ONLY]]:
; DEFAULT-NEXT:    call void @sse2_only_path()
; DEFAULT-NEXT:    ret void
;
; GENERIC-LABEL: @test_nested_branch(
; GENERIC-NOT:   @avx2_and_sse2_path
; GENERIC-NOT:   @avx2_path
; GENERIC:       call void @sse2_only_path()
; GENERIC:       ret void
entry:
  %has_avx2 = call i1 @llvm.target.has.feature(metadata !"avx2")
  br i1 %has_avx2, label %check.sse2, label %no.avx2

check.sse2:
  %has_sse2 = call i1 @llvm.target.has.feature(metadata !"sse2")
  br i1 %has_sse2, label %both, label %avx2.only

both:
  call void @avx2_and_sse2_path()
  ret void

avx2.only:
  call void @avx2_path()
  ret void

no.avx2:
  %has_sse2_alt = call i1 @llvm.target.has.feature(metadata !"sse2")
  br i1 %has_sse2_alt, label %sse2.only, label %generic

sse2.only:
  call void @sse2_only_path()
  ret void

generic:
  call void @fallback_path()
  ret void
}
