// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-globals none --version 6
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -emit-llvm -o - %s -O1 -fexceptions -fcxx-exceptions | FileCheck %s
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -emit-llvm -o - %s -O1 -fexceptions -fcxx-exceptions -sloppy-temporary-lifetimes | FileCheck %s --check-prefix=SLOPPY

// COM: Note that this test case would break if we allowed tighter lifetimes to
// run when exceptions were enabled. If we make them work together this test
// will need to be updated.

extern "C" {

struct Trivial {
  int x[100];
};

void func_that_throws(Trivial t);

// TIGHT-LABEL: define dso_local void @test(
// TIGHT-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] personality ptr @__gxx_personality_v0 {
// TIGHT-NEXT:  [[ENTRY:.*:]]
// TIGHT-NEXT:    [[AGG_TMP:%.*]] = alloca [[STRUCT_TRIVIAL:%.*]], align 8
// TIGHT-NEXT:    [[AGG_TMP2:%.*]] = alloca [[STRUCT_TRIVIAL]], align 8
// TIGHT-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[AGG_TMP]]) #[[ATTR4:[0-9]+]]
// TIGHT-NEXT:    call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(400) [[AGG_TMP]], i8 0, i64 400, i1 false)
// TIGHT-NEXT:    invoke void @func_that_throws(ptr noundef nonnull byval([[STRUCT_TRIVIAL]]) align 8 [[AGG_TMP]])
// TIGHT-NEXT:            to label %[[INVOKE_CONT:.*]] unwind label %[[LPAD1:.*]]
// TIGHT:       [[INVOKE_CONT]]:
// TIGHT-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[AGG_TMP]]) #[[ATTR4]]
// TIGHT-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[AGG_TMP2]]) #[[ATTR4]]
// TIGHT-NEXT:    call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(400) [[AGG_TMP2]], i8 0, i64 400, i1 false)
// TIGHT-NEXT:    invoke void @func_that_throws(ptr noundef nonnull byval([[STRUCT_TRIVIAL]]) align 8 [[AGG_TMP2]])
// TIGHT-NEXT:            to label %[[INVOKE_CONT5:.*]] unwind label %[[LPAD4:.*]]
// TIGHT:       [[INVOKE_CONT5]]:
// TIGHT-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[AGG_TMP2]]) #[[ATTR4]]
// TIGHT-NEXT:    br label %[[TRY_CONT:.*]]
// TIGHT:       [[LPAD1]]:
// TIGHT-NEXT:    [[TMP0:%.*]] = landingpad { ptr, i32 }
// TIGHT-NEXT:            catch ptr null
// TIGHT-NEXT:    br label %[[EHCLEANUP:.*]]
// TIGHT:       [[LPAD4]]:
// TIGHT-NEXT:    [[TMP1:%.*]] = landingpad { ptr, i32 }
// TIGHT-NEXT:            catch ptr null
// TIGHT-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[AGG_TMP2]]) #[[ATTR4]]
// TIGHT-NEXT:    br label %[[EHCLEANUP]]
// TIGHT:       [[EHCLEANUP]]:
// TIGHT-NEXT:    [[DOTPN:%.*]] = phi { ptr, i32 } [ [[TMP1]], %[[LPAD4]] ], [ [[TMP0]], %[[LPAD1]] ]
// TIGHT-NEXT:    [[EXN_SLOT_0:%.*]] = extractvalue { ptr, i32 } [[DOTPN]], 0
// TIGHT-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[AGG_TMP]]) #[[ATTR4]]
// TIGHT-NEXT:    [[TMP2:%.*]] = tail call ptr @__cxa_begin_catch(ptr [[EXN_SLOT_0]]) #[[ATTR4]]
// TIGHT-NEXT:    tail call void @__cxa_end_catch()
// TIGHT-NEXT:    br label %[[TRY_CONT]]
// TIGHT:       [[TRY_CONT]]:
// TIGHT-NEXT:    ret void
// CHECK-LABEL: define dso_local void @test(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AGG_TMP:%.*]] = alloca [[STRUCT_TRIVIAL:%.*]], align 8
// CHECK-NEXT:    [[AGG_TMP2:%.*]] = alloca [[STRUCT_TRIVIAL]], align 8
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[AGG_TMP]]) #[[ATTR4:[0-9]+]]
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(400) [[AGG_TMP]], i8 0, i64 400, i1 false)
// CHECK-NEXT:    invoke void @func_that_throws(ptr noundef nonnull byval([[STRUCT_TRIVIAL]]) align 8 [[AGG_TMP]])
// CHECK-NEXT:            to label %[[INVOKE_CONT:.*]] unwind label %[[LPAD1:.*]]
// CHECK:       [[INVOKE_CONT]]:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[AGG_TMP]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[AGG_TMP2]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(400) [[AGG_TMP2]], i8 0, i64 400, i1 false)
// CHECK-NEXT:    invoke void @func_that_throws(ptr noundef nonnull byval([[STRUCT_TRIVIAL]]) align 8 [[AGG_TMP2]])
// CHECK-NEXT:            to label %[[INVOKE_CONT5:.*]] unwind label %[[LPAD4:.*]]
// CHECK:       [[INVOKE_CONT5]]:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[AGG_TMP2]]) #[[ATTR4]]
// CHECK-NEXT:    br label %[[TRY_CONT:.*]]
// CHECK:       [[LPAD1]]:
// CHECK-NEXT:    [[TMP0:%.*]] = landingpad { ptr, i32 }
// CHECK-NEXT:            catch ptr null
// CHECK-NEXT:    br label %[[EHCLEANUP:.*]]
// CHECK:       [[LPAD4]]:
// CHECK-NEXT:    [[TMP1:%.*]] = landingpad { ptr, i32 }
// CHECK-NEXT:            catch ptr null
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[AGG_TMP2]]) #[[ATTR4]]
// CHECK-NEXT:    br label %[[EHCLEANUP]]
// CHECK:       [[EHCLEANUP]]:
// CHECK-NEXT:    [[DOTPN:%.*]] = phi { ptr, i32 } [ [[TMP1]], %[[LPAD4]] ], [ [[TMP0]], %[[LPAD1]] ]
// CHECK-NEXT:    [[EXN_SLOT_0:%.*]] = extractvalue { ptr, i32 } [[DOTPN]], 0
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[AGG_TMP]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call ptr @__cxa_begin_catch(ptr [[EXN_SLOT_0]]) #[[ATTR4]]
// CHECK-NEXT:    tail call void @__cxa_end_catch()
// CHECK-NEXT:    br label %[[TRY_CONT]]
// CHECK:       [[TRY_CONT]]:
// CHECK-NEXT:    ret void
//
// SLOPPY-LABEL: define dso_local void @test(
// SLOPPY-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] personality ptr @__gxx_personality_v0 {
// SLOPPY-NEXT:  [[ENTRY:.*:]]
// SLOPPY-NEXT:    [[AGG_TMP:%.*]] = alloca [[STRUCT_TRIVIAL:%.*]], align 8
// SLOPPY-NEXT:    [[AGG_TMP1:%.*]] = alloca [[STRUCT_TRIVIAL]], align 8
// SLOPPY-NEXT:    call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(400) [[AGG_TMP]], i8 0, i64 400, i1 false)
// SLOPPY-NEXT:    invoke void @func_that_throws(ptr noundef nonnull byval([[STRUCT_TRIVIAL]]) align 8 [[AGG_TMP]])
// SLOPPY-NEXT:            to label %[[INVOKE_CONT:.*]] unwind label %[[LPAD:.*]]
// SLOPPY:       [[INVOKE_CONT]]:
// SLOPPY-NEXT:    call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(400) [[AGG_TMP1]], i8 0, i64 400, i1 false)
// SLOPPY-NEXT:    invoke void @func_that_throws(ptr noundef nonnull byval([[STRUCT_TRIVIAL]]) align 8 [[AGG_TMP1]])
// SLOPPY-NEXT:            to label %[[TRY_CONT:.*]] unwind label %[[LPAD]]
// SLOPPY:       [[LPAD]]:
// SLOPPY-NEXT:    [[TMP0:%.*]] = landingpad { ptr, i32 }
// SLOPPY-NEXT:            catch ptr null
// SLOPPY-NEXT:    [[TMP1:%.*]] = extractvalue { ptr, i32 } [[TMP0]], 0
// SLOPPY-NEXT:    [[TMP2:%.*]] = tail call ptr @__cxa_begin_catch(ptr [[TMP1]]) #[[ATTR3:[0-9]+]]
// SLOPPY-NEXT:    tail call void @__cxa_end_catch()
// SLOPPY-NEXT:    br label %[[TRY_CONT]]
// SLOPPY:       [[TRY_CONT]]:
// SLOPPY-NEXT:    ret void
//
void test() {
  try {
    func_that_throws(Trivial{0});
    func_that_throws(Trivial{0});
  } catch (...) {
  }
}
} // end extern "C"
