// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 %s -emit-llvm -o - -triple=i686-apple-darwin9 | FileCheck %s

namespace FetchMinMax {

// CHECK-LABEL: define void @_ZN11FetchMinMax16test_c11_min_ptrEPU7_AtomicPiS0_(
// CHECK-SAME: ptr noundef [[AIP:%.*]], ptr noundef [[IP:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AIP_ADDR:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    [[IP_ADDR:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    [[DOTATOMICTMP:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    store ptr [[AIP]], ptr [[AIP_ADDR]], align 4
// CHECK-NEXT:    store ptr [[IP]], ptr [[IP_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[AIP_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[IP_ADDR]], align 4
// CHECK-NEXT:    store ptr [[TMP1]], ptr [[DOTATOMICTMP]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[DOTATOMICTMP]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = atomicrmw umin ptr [[TMP0]], i32 [[TMP2]] monotonic, align 4
// CHECK-NEXT:    store i32 [[TMP3]], ptr [[ATOMIC_TEMP]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[ATOMIC_TEMP]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[AIP_ADDR]], align 4
// CHECK-NEXT:    store atomic ptr [[TMP4]], ptr [[TMP5]] seq_cst, align 4
// CHECK-NEXT:    ret void
//
void test_c11_min_ptr(_Atomic(int*) * aip, int* ip) {
  *aip = __c11_atomic_fetch_min(aip, ip, 0);
}

// CHECK-LABEL: define void @_ZN11FetchMinMax16test_c11_max_ptrEPU7_AtomicPiS0_(
// CHECK-SAME: ptr noundef [[AIP:%.*]], ptr noundef [[IP:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AIP_ADDR:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    [[IP_ADDR:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    [[DOTATOMICTMP:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    store ptr [[AIP]], ptr [[AIP_ADDR]], align 4
// CHECK-NEXT:    store ptr [[IP]], ptr [[IP_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[AIP_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[IP_ADDR]], align 4
// CHECK-NEXT:    store ptr [[TMP1]], ptr [[DOTATOMICTMP]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[DOTATOMICTMP]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = atomicrmw umax ptr [[TMP0]], i32 [[TMP2]] monotonic, align 4
// CHECK-NEXT:    store i32 [[TMP3]], ptr [[ATOMIC_TEMP]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[ATOMIC_TEMP]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[AIP_ADDR]], align 4
// CHECK-NEXT:    store atomic ptr [[TMP4]], ptr [[TMP5]] seq_cst, align 4
// CHECK-NEXT:    ret void
//
void test_c11_max_ptr(_Atomic(int*) * aip, int* ip) {
  *aip = __c11_atomic_fetch_max(aip, ip, 0);
}

// CHECK-LABEL: define void @_ZN11FetchMinMax20test_c11_min_nullptrEPU7_AtomicPiS0_(
// CHECK-SAME: ptr noundef [[AIP:%.*]], ptr noundef [[IP:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AIP_ADDR:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    [[IP_ADDR:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    [[DOTATOMICTMP:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    store ptr [[AIP]], ptr [[AIP_ADDR]], align 4
// CHECK-NEXT:    store ptr [[IP]], ptr [[IP_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[AIP_ADDR]], align 4
// CHECK-NEXT:    store ptr null, ptr [[DOTATOMICTMP]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[DOTATOMICTMP]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = atomicrmw umin ptr [[TMP0]], i32 [[TMP1]] monotonic, align 4
// CHECK-NEXT:    store i32 [[TMP2]], ptr [[ATOMIC_TEMP]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[ATOMIC_TEMP]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[AIP_ADDR]], align 4
// CHECK-NEXT:    store atomic ptr [[TMP3]], ptr [[TMP4]] seq_cst, align 4
// CHECK-NEXT:    ret void
//
void test_c11_min_nullptr(_Atomic(int*) * aip, int* ip) {
  *aip = __c11_atomic_fetch_min(aip, nullptr, 0);
}

// CHECK-LABEL: define void @_ZN11FetchMinMax20test_c11_max_nullptrEPU7_AtomicPiS0_(
// CHECK-SAME: ptr noundef [[AIP:%.*]], ptr noundef [[IP:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AIP_ADDR:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    [[IP_ADDR:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    [[DOTATOMICTMP:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    store ptr [[AIP]], ptr [[AIP_ADDR]], align 4
// CHECK-NEXT:    store ptr [[IP]], ptr [[IP_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[AIP_ADDR]], align 4
// CHECK-NEXT:    store ptr null, ptr [[DOTATOMICTMP]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[DOTATOMICTMP]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = atomicrmw umax ptr [[TMP0]], i32 [[TMP1]] monotonic, align 4
// CHECK-NEXT:    store i32 [[TMP2]], ptr [[ATOMIC_TEMP]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[ATOMIC_TEMP]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[AIP_ADDR]], align 4
// CHECK-NEXT:    store atomic ptr [[TMP3]], ptr [[TMP4]] seq_cst, align 4
// CHECK-NEXT:    ret void
//
void test_c11_max_nullptr(_Atomic(int*) * aip, int* ip) {
  *aip = __c11_atomic_fetch_max(aip, nullptr, 0);
}

}
