// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --filter "define" --version 6
// Check that we appropriately annotate destructors with a dead_on_return
// attribute.
//
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -emit-llvm %s -o - | FileCheck %s

void opaque(char*);

class Foo {
public:
// CHECK-LABEL: define linkonce_odr void @_ZN3FooD1Ev(
// CHECK-SAME: ptr noundef nonnull align 1 dead_on_return(4) dereferenceable(4) [[THIS:%.*]]) unnamed_addr #[[ATTR1:[0-9]+]] comdat align 2 {
  ~Foo() { opaque(FooVar); };

private:
  char FooVar[4];
};

class Bar {
public:
// CHECK-LABEL: define linkonce_odr void @_ZN3BarD1Ev(
// CHECK-SAME: ptr noundef nonnull align 1 dead_on_return(8) dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR1:[0-9]+]] comdat align 2 {
  ~Bar() { opaque(BarVar); };

private:
  char BarVar[8];
};

class BarInheritsFoo : public Foo {
public:
// CHECK-LABEL: define linkonce_odr void @_ZN14BarInheritsFooD1Ev(
// CHECK-SAME: ptr noundef nonnull align 1 dereferenceable(16) [[THIS:%.*]]) unnamed_addr #[[ATTR1:[0-9]+]] comdat align 2 {
  ~BarInheritsFoo() { opaque(BarVar); };

private:
  char BarVar[12];
};

class BarVirtualInheritsFoo : public virtual Foo {
public:
// CHECK-LABEL: define linkonce_odr void @_ZN21BarVirtualInheritsFooD1Ev(
// CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(24) [[THIS:%.*]]) unnamed_addr #[[ATTR1:[0-9]+]] comdat align 2 {
  ~BarVirtualInheritsFoo() { opaque(BarVar); };

private:
  char BarVar[16];
};

// CHECK-LABEL: define dso_local noundef i32 @main(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
int main() {
  Foo FooInstance;
  Bar BarInstance;
  BarInheritsFoo BarInheritsFooInstance;
  BarVirtualInheritsFoo BarVirtualInheritsFooInstance;
}
