// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -fcheck-new -triple x86_64-linux-gnu -disable-O0-optnone \
// RUN:   -emit-llvm -o - %s | FileCheck %s

struct A { A(); };

// CHECK-LABEL: @_Z5test0v(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CALL:%.*]] = call noalias noundef ptr @_Znwm(i64 noundef 1) #[[ATTR3:[0-9]+]]
// CHECK-NEXT:    [[NEW_ISNULL:%.*]] = icmp eq ptr [[CALL]], null
// CHECK-NEXT:    br i1 [[NEW_ISNULL]], label [[NEW_CONT:%.*]], label [[NEW_NOTNULL:%.*]]
// CHECK:       new.notnull:
// CHECK-NEXT:    call void @_ZN1AC1Ev(ptr noalias noundef nonnull align 1 dereferenceable(1) [[CALL]])
// CHECK-NEXT:    br label [[NEW_CONT]]
// CHECK:       new.cont:
// CHECK-NEXT:    [[TMP0:%.*]] = phi ptr [ [[CALL]], [[NEW_NOTNULL]] ], [ null, [[ENTRY:%.*]] ]
// CHECK-NEXT:    ret ptr [[TMP0]]
//
A *test0() {
  return new A();
}

// CHECK-LABEL: @_Z5test1v(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CALL:%.*]] = call noalias noundef ptr @_Znwm(i64 noundef 4) #[[ATTR3]]
// CHECK-NEXT:    ret ptr [[CALL]]
//
int *test1() {
  return new int;
}
