; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=aarch64-none-elf -loop-reduce < %s | FileCheck %s

; An unrolled loop that's too complex, causing LSR to collapse the unrolled
; LSRUses into one.
; The last LSRUse should be the one that the others are collased into, and IV
; increment GEP should happen at the end of the loop.

define void @unrolled_loop(ptr %src, ptr %dst, i32 %low, i32 %high, i64 %n) {
; CHECK-LABEL: define void @unrolled_loop(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]], i32 [[LOW:%.*]], i32 [[HIGH:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[SCEVGEP6:%.*]] = getelementptr i8, ptr [[DST]], i64 8
; CHECK-NEXT:    [[SCEVGEP15:%.*]] = getelementptr i8, ptr [[SRC]], i64 8
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[LSR_IV14:%.*]] = phi i64 [ [[LSR_IV_NEXT:%.*]], %[[FOR_INC_3:.*]] ], [ [[N]], %[[ENTRY]] ]
; CHECK-NEXT:    [[LSR_IV1:%.*]] = phi ptr [ [[SCEVGEP16:%.*]], %[[FOR_INC_3]] ], [ [[SCEVGEP15]], %[[ENTRY]] ]
; CHECK-NEXT:    [[LSR_IV7:%.*]] = phi ptr [ [[SCEVGEP8:%.*]], %[[FOR_INC_3]] ], [ [[SCEVGEP6]], %[[ENTRY]] ]
; CHECK-NEXT:    [[SCEVGEP3:%.*]] = getelementptr i8, ptr [[LSR_IV1]], i64 -8
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[SCEVGEP3]], align 4
; CHECK-NEXT:    [[CMP1:%.*]] = icmp sgt i32 [[VAL]], [[HIGH]]
; CHECK-NEXT:    br i1 [[CMP1]], label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    [[SCEVGEP10:%.*]] = getelementptr i8, ptr [[LSR_IV7]], i64 -8
; CHECK-NEXT:    store i32 [[HIGH]], ptr [[SCEVGEP10]], align 4
; CHECK-NEXT:    br label %[[FOR_INC:.*]]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    [[CMP2:%.*]] = icmp slt i32 [[VAL]], [[LOW]]
; CHECK-NEXT:    [[SCEVGEP9:%.*]] = getelementptr i8, ptr [[LSR_IV7]], i64 -8
; CHECK-NEXT:    br i1 [[CMP2]], label %[[IF_ELSE_THEN:.*]], label %[[IF_ELSE_ELSE:.*]]
; CHECK:       [[IF_ELSE_THEN]]:
; CHECK-NEXT:    store i32 [[LOW]], ptr [[SCEVGEP9]], align 4
; CHECK-NEXT:    br label %[[FOR_INC]]
; CHECK:       [[IF_ELSE_ELSE]]:
; CHECK-NEXT:    store i32 [[VAL]], ptr [[SCEVGEP9]], align 4
; CHECK-NEXT:    br label %[[FOR_INC]]
; CHECK:       [[FOR_INC]]:
; CHECK-NEXT:    [[SCEVGEP5:%.*]] = getelementptr i8, ptr [[LSR_IV1]], i64 -4
; CHECK-NEXT:    [[VAL_1:%.*]] = load i32, ptr [[SCEVGEP5]], align 4
; CHECK-NEXT:    [[CMP1_1:%.*]] = icmp sgt i32 [[VAL_1]], [[HIGH]]
; CHECK-NEXT:    br i1 [[CMP1_1]], label %[[IF_THEN_1:.*]], label %[[IF_ELSE_1:.*]]
; CHECK:       [[IF_ELSE_1]]:
; CHECK-NEXT:    [[CMP2_1:%.*]] = icmp slt i32 [[VAL_1]], [[LOW]]
; CHECK-NEXT:    [[SCEVGEP14:%.*]] = getelementptr i8, ptr [[LSR_IV7]], i64 -4
; CHECK-NEXT:    br i1 [[CMP2_1]], label %[[IF_ELSE_THEN_1:.*]], label %[[IF_ELSE_ELSE_1:.*]]
; CHECK:       [[IF_ELSE_ELSE_1]]:
; CHECK-NEXT:    store i32 [[VAL_1]], ptr [[SCEVGEP14]], align 4
; CHECK-NEXT:    br label %[[FOR_INC_1:.*]]
; CHECK:       [[IF_ELSE_THEN_1]]:
; CHECK-NEXT:    store i32 [[LOW]], ptr [[SCEVGEP14]], align 4
; CHECK-NEXT:    br label %[[FOR_INC_1]]
; CHECK:       [[IF_THEN_1]]:
; CHECK-NEXT:    [[SCEVGEP13:%.*]] = getelementptr i8, ptr [[LSR_IV7]], i64 -4
; CHECK-NEXT:    store i32 [[HIGH]], ptr [[SCEVGEP13]], align 4
; CHECK-NEXT:    br label %[[FOR_INC_1]]
; CHECK:       [[FOR_INC_1]]:
; CHECK-NEXT:    [[VAL_2:%.*]] = load i32, ptr [[LSR_IV1]], align 4
; CHECK-NEXT:    [[CMP1_2:%.*]] = icmp sgt i32 [[VAL_2]], [[HIGH]]
; CHECK-NEXT:    br i1 [[CMP1_2]], label %[[IF_THEN_2:.*]], label %[[IF_ELSE_2:.*]]
; CHECK:       [[IF_ELSE_2]]:
; CHECK-NEXT:    [[CMP2_2:%.*]] = icmp slt i32 [[VAL_2]], [[LOW]]
; CHECK-NEXT:    br i1 [[CMP2_2]], label %[[IF_ELSE_THEN_2:.*]], label %[[IF_ELSE_ELSE_2:.*]]
; CHECK:       [[IF_ELSE_ELSE_2]]:
; CHECK-NEXT:    store i32 [[VAL_2]], ptr [[LSR_IV7]], align 4
; CHECK-NEXT:    br label %[[FOR_INC_2:.*]]
; CHECK:       [[IF_ELSE_THEN_2]]:
; CHECK-NEXT:    store i32 [[LOW]], ptr [[LSR_IV7]], align 4
; CHECK-NEXT:    br label %[[FOR_INC_2]]
; CHECK:       [[IF_THEN_2]]:
; CHECK-NEXT:    store i32 [[HIGH]], ptr [[LSR_IV7]], align 4
; CHECK-NEXT:    br label %[[FOR_INC_2]]
; CHECK:       [[FOR_INC_2]]:
; CHECK-NEXT:    [[SCEVGEP4:%.*]] = getelementptr i8, ptr [[LSR_IV1]], i64 4
; CHECK-NEXT:    [[VAL_3:%.*]] = load i32, ptr [[SCEVGEP4]], align 4
; CHECK-NEXT:    [[CMP1_3:%.*]] = icmp sgt i32 [[VAL_3]], [[HIGH]]
; CHECK-NEXT:    [[SCEVGEP16]] = getelementptr i8, ptr [[LSR_IV1]], i64 16
; CHECK-NEXT:    br i1 [[CMP1_3]], label %[[IF_THEN_3:.*]], label %[[IF_ELSE_3:.*]]
; CHECK:       [[IF_ELSE_3]]:
; CHECK-NEXT:    [[CMP2_3:%.*]] = icmp slt i32 [[VAL_3]], [[LOW]]
; CHECK-NEXT:    [[SCEVGEP12:%.*]] = getelementptr i8, ptr [[LSR_IV7]], i64 4
; CHECK-NEXT:    br i1 [[CMP2_3]], label %[[IF_ELSE_THEN_3:.*]], label %[[IF_ELSE_ELSE_3:.*]]
; CHECK:       [[IF_ELSE_ELSE_3]]:
; CHECK-NEXT:    store i32 [[VAL_3]], ptr [[SCEVGEP12]], align 4
; CHECK-NEXT:    br label %[[FOR_INC_3]]
; CHECK:       [[IF_ELSE_THEN_3]]:
; CHECK-NEXT:    store i32 [[LOW]], ptr [[SCEVGEP12]], align 4
; CHECK-NEXT:    br label %[[FOR_INC_3]]
; CHECK:       [[IF_THEN_3]]:
; CHECK-NEXT:    [[SCEVGEP11:%.*]] = getelementptr i8, ptr [[LSR_IV7]], i64 4
; CHECK-NEXT:    store i32 [[HIGH]], ptr [[SCEVGEP11]], align 4
; CHECK-NEXT:    br label %[[FOR_INC_3]]
; CHECK:       [[FOR_INC_3]]:
; CHECK-NEXT:    [[SCEVGEP8]] = getelementptr i8, ptr [[LSR_IV7]], i64 16
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add i64 [[LSR_IV14]], -4
; CHECK-NEXT:    [[NITER_NCMP:%.*]] = icmp eq i64 [[LSR_IV_NEXT]], 0
; CHECK-NEXT:    br i1 [[NITER_NCMP]], label %[[EXIT:.*]], label %[[FOR_BODY]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %idx = phi i64 [ 0, %entry ], [ %idx.next, %for.inc.3 ]
  %niter = phi i64 [ 0, %entry ], [ %niter.next, %for.inc.3 ]
  %srcidx = getelementptr inbounds nuw i32, ptr %src, i64 %idx
  %val = load i32, ptr %srcidx, align 4
  %cmp1 = icmp sgt i32 %val, %high
  br i1 %cmp1, label %if.then, label %if.else

if.then:
  %dstidx1 = getelementptr inbounds nuw i32, ptr %dst, i64 %idx
  store i32 %high, ptr %dstidx1, align 4
  br label %for.inc

if.else:
  %cmp2 = icmp slt i32 %val, %low
  %dstidx2 = getelementptr inbounds nuw i32, ptr %dst, i64 %idx
  br i1 %cmp2, label %if.else.then, label %if.else.else

if.else.then:
  store i32 %low, ptr %dstidx2, align 4
  br label %for.inc

if.else.else:
  store i32 %val, ptr %dstidx2, align 4
  br label %for.inc

for.inc:
  %inc = or disjoint i64 %idx, 1
  %srcidx.1 = getelementptr inbounds nuw i32, ptr %src, i64 %inc
  %val.1 = load i32, ptr %srcidx.1, align 4
  %cmp1.1 = icmp sgt i32 %val.1, %high
  br i1 %cmp1.1, label %if.then.1, label %if.else.1

if.else.1:
  %cmp2.1 = icmp slt i32 %val.1, %low
  %dstidx2.1 = getelementptr inbounds nuw i32, ptr %dst, i64 %inc
  br i1 %cmp2.1, label %if.else.then.1, label %if.else.else.1

if.else.else.1:
  store i32 %val.1, ptr %dstidx2.1, align 4
  br label %for.inc.1

if.else.then.1:
  store i32 %low, ptr %dstidx2.1, align 4
  br label %for.inc.1

if.then.1:
  %dstidx1.1 = getelementptr inbounds nuw i32, ptr %dst, i64 %inc
  store i32 %high, ptr %dstidx1.1, align 4
  br label %for.inc.1

for.inc.1:
  %inc.1 = or disjoint i64 %idx, 2
  %srcidx.2 = getelementptr inbounds nuw i32, ptr %src, i64 %inc.1
  %val.2 = load i32, ptr %srcidx.2, align 4
  %cmp1.2 = icmp sgt i32 %val.2, %high
  br i1 %cmp1.2, label %if.then.2, label %if.else.2

if.else.2:
  %cmp2.2 = icmp slt i32 %val.2, %low
  %dstidx2.2 = getelementptr inbounds nuw i32, ptr %dst, i64 %inc.1
  br i1 %cmp2.2, label %if.else.then.2, label %if.else.else.2

if.else.else.2:
  store i32 %val.2, ptr %dstidx2.2, align 4
  br label %for.inc.2

if.else.then.2:
  store i32 %low, ptr %dstidx2.2, align 4
  br label %for.inc.2

if.then.2:
  %dstidx1.2 = getelementptr inbounds nuw i32, ptr %dst, i64 %inc.1
  store i32 %high, ptr %dstidx1.2, align 4
  br label %for.inc.2

for.inc.2:
  %inc.2 = or disjoint i64 %idx, 3
  %srcidx.3 = getelementptr inbounds nuw i32, ptr %src, i64 %inc.2
  %val.3 = load i32, ptr %srcidx.3, align 4
  %cmp1.3 = icmp sgt i32 %val.3, %high
  br i1 %cmp1.3, label %if.then.3, label %if.else.3

if.else.3:
  %cmp2.3 = icmp slt i32 %val.3, %low
  %dstidx2.3 = getelementptr inbounds nuw i32, ptr %dst, i64 %inc.2
  br i1 %cmp2.3, label %if.else.then.3, label %if.else.else.3

if.else.else.3:
  store i32 %val.3, ptr %dstidx2.3, align 4
  br label %for.inc.3

if.else.then.3:
  store i32 %low, ptr %dstidx2.3, align 4
  br label %for.inc.3

if.then.3:
  %dstidx1.3 = getelementptr inbounds nuw i32, ptr %dst, i64 %inc.2
  store i32 %high, ptr %dstidx1.3, align 4
  br label %for.inc.3

for.inc.3:
  %idx.next = add nuw i64 %idx, 4
  %niter.next = add i64 %niter, 4
  %niter.ncmp = icmp eq i64 %niter.next, %n
  br i1 %niter.ncmp, label %exit, label %for.body

exit:
  ret void
}
