; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S --passes=slp-vectorizer -mtriple=systemz -mcpu=z15 < %s -slp-threshold=-100 | FileCheck %s

define void @test(i32 %0, i64 %1, i32 %2, i32 %3, ptr %4) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i32 [[TMP0:%.*]], i64 [[TMP1:%.*]], i32 [[TMP2:%.*]], i32 [[TMP3:%.*]], ptr [[TMP4:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP56:%.*]] = trunc i64 [[TMP1]] to i32
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <2 x i32> poison, i32 [[TMP56]], i32 0
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP7]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP73:%.*]] = trunc i64 [[TMP1]] to i32
; CHECK-NEXT:    [[TMP98:%.*]] = trunc i64 [[TMP1]] to i32
; CHECK-NEXT:    [[TMP11:%.*]] = insertelement <60 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>, i32 [[TMP0]], i32 7
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <60 x i32> [[TMP11]], <60 x i32> poison, <60 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 7, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 7, i32 7, i32 7, i32 7, i32 7>
; CHECK-NEXT:    [[TMP13:%.*]] = insertelement <60 x i32> poison, i32 [[TMP3]], i32 1
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <60 x i32> [[TMP13]], i32 [[TMP2]], i32 7
; CHECK-NEXT:    [[TMP15:%.*]] = insertelement <60 x i32> [[TMP14]], i32 [[TMP98]], i32 0
; CHECK-NEXT:    [[TMP16:%.*]] = insertelement <60 x i32> [[TMP15]], i32 [[TMP73]], i32 6
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <60 x i32> [[TMP16]], <60 x i32> poison, <8 x i32> <i32 0, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 6, i32 7>
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <2 x i32> [[TMP8]], <2 x i32> poison, <8 x i32> <i32 0, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <2 x i32> [[TMP8]], <2 x i32> poison, <60 x i32> <i32 0, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <60 x i32> [[TMP16]], <60 x i32> [[TMP22]], <8 x i32> <i32 0, i32 1, i32 60, i32 61, i32 poison, i32 poison, i32 6, i32 7>
; CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <8 x i32> [[TMP23]], <8 x i32> [[TMP18]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 6, i32 7>
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <8 x i32> [[TMP19]], <8 x i32> poison, <60 x i32> <i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 4, i32 4, i32 4, i32 4, i32 4, i32 4, i32 4, i32 4, i32 5, i32 5, i32 5, i32 5, i32 5, i32 5, i32 5, i32 5, i32 6, i32 6, i32 6, i32 6, i32 6, i32 6, i32 6, i32 6, i32 7, i32 7, i32 7, i32 7>
; CHECK-NEXT:    [[TMP21:%.*]] = xor <60 x i32> [[TMP12]], [[TMP20]]
; CHECK-NEXT:    [[TMP130:%.*]] = call i32 @llvm.vector.reduce.or.v60i32(<60 x i32> [[TMP21]])
; CHECK-NEXT:    store i32 [[TMP130]], ptr [[TMP4]], align 4
; CHECK-NEXT:    ret void
;
  %6 = trunc i64 %1 to i32
  %7 = xor i32 %6, 1
  %8 = xor i32 %6, 1
  %9 = or i32 %7, %8
  %10 = xor i32 %6, 1
  %11 = or i32 %9, %10
  %12 = xor i32 %6, 1
  %13 = or i32 %11, %12
  %14 = xor i32 %6, 1
  %15 = or i32 %13, %14
  %16 = xor i32 %6, 1
  %17 = or i32 %15, %16
  %18 = xor i32 %6, 1
  %19 = or i32 %17, %18
  %20 = xor i32 %6, 1
  %21 = or i32 %19, %20
  %22 = trunc i64 %1 to i32
  %23 = xor i32 %22, 1
  %24 = or i32 %23, %21
  %25 = xor i32 %22, 1
  %26 = or i32 %24, %25
  %27 = xor i32 %22, 1
  %28 = or i32 %26, %27
  %29 = xor i32 %22, 1
  %30 = or i32 %28, %29
  %31 = xor i32 %22, 1
  %32 = or i32 %30, %31
  %33 = xor i32 %22, 1
  %34 = or i32 %32, %33
  %35 = xor i32 %22, 1
  %36 = or i32 %34, %35
  %37 = xor i32 %22, 1
  %38 = or i32 %36, %37
  %39 = trunc i64 %1 to i32
  %40 = xor i32 %39, 1
  %41 = or i32 %40, %38
  %42 = xor i32 %39, 1
  %43 = or i32 %41, %42
  %44 = xor i32 %39, 1
  %45 = or i32 %43, %44
  %46 = xor i32 %39, 1
  %47 = or i32 %45, %46
  %48 = xor i32 %39, 1
  %49 = or i32 %47, %48
  %50 = xor i32 %39, 1
  %51 = or i32 %49, %50
  %52 = xor i32 %39, 1
  %53 = or i32 %51, %52
  %54 = xor i32 %39, 1
  %55 = or i32 %53, %54
  %56 = trunc i64 %1 to i32
  %57 = xor i32 %56, 1
  %58 = or i32 %57, %55
  %59 = xor i32 %56, 1
  %60 = or i32 %58, %59
  %61 = xor i32 %56, 1
  %62 = or i32 %60, %61
  %63 = xor i32 %56, 1
  %64 = or i32 %62, %63
  %65 = xor i32 %56, 1
  %66 = or i32 %64, %65
  %67 = xor i32 %56, 1
  %68 = or i32 %66, %67
  %69 = xor i32 %56, 1
  %70 = or i32 %68, %69
  %71 = xor i32 %56, 1
  %72 = or i32 %70, %71
  %73 = trunc i64 %1 to i32
  %74 = xor i32 %73, 1
  %75 = or i32 %74, %72
  %76 = xor i32 %73, 1
  %77 = or i32 %75, %76
  %78 = xor i32 %73, 1
  %79 = or i32 %77, %78
  %80 = xor i32 %73, 1
  %81 = or i32 %79, %80
  %82 = xor i32 %73, 1
  %83 = or i32 %81, %82
  %84 = xor i32 %73, 1
  %85 = or i32 %83, %84
  %86 = xor i32 %73, 1
  %87 = or i32 %85, %86
  %88 = xor i32 %0, %73
  %89 = or i32 %87, %88
  %90 = xor i32 %0, %2
  %91 = or i32 %90, %89
  %92 = xor i32 %0, %2
  %93 = or i32 %91, %92
  %94 = xor i32 %0, %2
  %95 = or i32 %93, %94
  %96 = xor i32 %0, %2
  %97 = or i32 %95, %96
  %98 = trunc i64 %1 to i32
  %99 = xor i32 %98, 1
  %100 = xor i32 %98, 1
  %101 = or i32 %99, %100
  %102 = xor i32 %98, 1
  %103 = or i32 %101, %102
  %104 = xor i32 %98, 1
  %105 = or i32 %103, %104
  %106 = xor i32 %98, 1
  %107 = or i32 %105, %106
  %108 = xor i32 %98, 1
  %109 = or i32 %107, %108
  %110 = xor i32 %98, 1
  %111 = or i32 %109, %110
  %112 = xor i32 %0, %98
  %113 = or i32 %111, %112
  %114 = xor i32 %0, %3
  %115 = or i32 %113, %114
  %116 = xor i32 %0, %3
  %117 = or i32 %115, %116
  %118 = xor i32 %0, %3
  %119 = or i32 %117, %118
  %120 = xor i32 %0, %3
  %121 = or i32 %119, %120
  %122 = xor i32 %0, %3
  %123 = or i32 %121, %122
  %124 = xor i32 %0, %3
  %125 = or i32 %123, %124
  %126 = xor i32 %0, %3
  %127 = or i32 %125, %126
  %128 = xor i32 %0, %3
  %129 = or i32 %127, %128
  %130 = or i32 %129, %97
  store i32 %130, ptr %4, align 4
  ret void
}

