; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -passes=guard-widening < %s | FileCheck %s

; Make sure we don't hang here.
define i64 @test() {
; CHECK-LABEL: define i64 @test() {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    [[WIDE_CHK:%.*]] = and i1 poison, poison
; CHECK-NEXT:    call void (i1, ...) @llvm.experimental.guard(i1 [[WIDE_CHK]]) [ "deopt"() ]
; CHECK-NEXT:    br label [[BB2:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    br i1 poison, label [[BB3:%.*]], label [[BB2]]
; CHECK:       bb3:
; CHECK-NEXT:    [[CALL:%.*]] = call i64 (...) @llvm.experimental.deoptimize.i64() [ "deopt"() ]
; CHECK-NEXT:    ret i64 [[CALL]]
;
bb:
  call void (i1, ...) @llvm.experimental.guard(i1 poison) [ "deopt"() ]
  br label %bb2

bb2:                                              ; preds = %bb2, %bb
  br i1 poison, label %bb3, label %bb2

bb3:                                              ; preds = %bb2
  call void (i1, ...) @llvm.experimental.guard(i1 poison) [ "deopt"() ]
  %call = call i64 (...) @llvm.experimental.deoptimize.i64() [ "deopt"() ]
  ret i64 %call
}

declare i64 @llvm.experimental.deoptimize.i64(...)

declare void @llvm.experimental.guard(i1, ...)
