name: Get LLVM Version
description: >-
  Get the LLVM version from the llvm-project source tree.  This action assumes
  the llvm-project sources have already been checked out into GITHUB_WORKSPACE.

outputs:
  major:
    description: LLVM major version
    value: ${{ steps.version.outputs.major }}
  minor:
    description: LLVM minor version
    value: ${{ steps.version.outputs.minor }}
  patch:
    description: LLVM patch version
    value: ${{ steps.version.outputs.patch }}
  full-no-suffix:
    description: |
      The full LLVM vesion without any suffixes like `-rc` or `git`.  This will be `$major.$minor.$patch`
    value: ${{ steps.version.outputs.full-no-suffix }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
        path: get-llvm-version
        sparse-checkout: |
          llvm/utils/release/get-llvm-version.sh
          cmake/Modules/LLVMVersion.cmake
        sparse-checkout-cone-mode: false

    - name: Get Version
      shell: bash
      id: version
      run: |
        for v in major minor patch; do
          echo "$v=`./get-llvm-version/llvm/utils/release/get-llvm-version.sh --$v`" >> $GITHUB_OUTPUT
        done

        echo "full-no-suffix=$(./get-llvm-version/llvm/utils/release/get-llvm-version.sh)" >> $GITHUB_OUTPUT
