# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv64 -mattr=+d -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck %s

---
name:            fcmp_f32
legalized:       true
body:             |
  bb.1:
    liveins: $f10_f, $f11_f

    ; CHECK-LABEL: name: fcmp_f32
    ; CHECK: liveins: $f10_f, $f11_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fprb(s32) = COPY $f10_f
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:fprb(s32) = COPY $f11_f
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:gprb(s64) = G_FCMP floatpred(oeq), [[COPY]](s32), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = COPY $f11_f
    %4:_(s64) = G_FCMP floatpred(oeq), %0(s32), %1
    $x10 = COPY %4(s64)
    PseudoRET implicit $x10

...
---
name:            fcmp_f64
legalized:       true
body:             |
  bb.1:
    liveins: $f10_d, $f11_d

    ; CHECK-LABEL: name: fcmp_f64
    ; CHECK: liveins: $f10_d, $f11_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fprb(s64) = COPY $f10_d
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:fprb(s64) = COPY $f11_d
    ; CHECK-NEXT: [[FCMP:%[0-9]+]]:gprb(s64) = G_FCMP floatpred(oeq), [[COPY]](s64), [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[FCMP]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = COPY $f11_d
    %4:_(s64) = G_FCMP floatpred(oeq), %0(s64), %1
    $x10 = COPY %4(s64)
    PseudoRET implicit $x10

...
