# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv64 -mattr=+d -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck %s

---
name:            fptosi_s32_s32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $f10_f

    ; CHECK-LABEL: name: fptosi_s32_s32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fprb(s32) = COPY $f10_f
    ; CHECK-NEXT: [[FCVT_W_RV64_:%[0-9]+]]:gprb(s64) = G_FCVT_W_RV64 [[COPY]](s32), 1
    ; CHECK-NEXT: $x10 = COPY [[FCVT_W_RV64_]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s32) = COPY $f10_f
    %1:_(s64) = G_FCVT_W_RV64 %0(s32), 1
    $x10 = COPY %1(s64)
    PseudoRET implicit $x10

...
---
name:            fptoui_s32_s32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $f10_f

    ; CHECK-LABEL: name: fptoui_s32_s32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fprb(s32) = COPY $f10_f
    ; CHECK-NEXT: [[FCVT_WU_RV64_:%[0-9]+]]:gprb(s64) = G_FCVT_WU_RV64 [[COPY]](s32), 1
    ; CHECK-NEXT: $x10 = COPY [[FCVT_WU_RV64_]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s32) = COPY $f10_f
    %1:_(s64) = G_FCVT_WU_RV64 %0(s32), 1
    $x10 = COPY %1(s64)
    PseudoRET implicit $x10

...
---
name:            fptosi_s64_s32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $f10_f

    ; CHECK-LABEL: name: fptosi_s64_s32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fprb(s32) = COPY $f10_f
    ; CHECK-NEXT: [[FPTOSI:%[0-9]+]]:gprb(s64) = G_FPTOSI [[COPY]](s32)
    ; CHECK-NEXT: $x10 = COPY [[FPTOSI]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s32) = COPY $f10_f
    %1:_(s64) = G_FPTOSI %0(s32)
    $x10 = COPY %1(s64)
    PseudoRET implicit $x10

...
---
name:            fptoui_s64_s32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $f10_f

    ; CHECK-LABEL: name: fptoui_s64_s32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fprb(s32) = COPY $f10_f
    ; CHECK-NEXT: [[FPTOUI:%[0-9]+]]:gprb(s64) = G_FPTOUI [[COPY]](s32)
    ; CHECK-NEXT: $x10 = COPY [[FPTOUI]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s32) = COPY $f10_f
    %1:_(s64) = G_FPTOUI %0(s32)
    $x10 = COPY %1(s64)
    PseudoRET implicit $x10

...
---
name:            fptosi_s32_s64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $f10_d

    ; CHECK-LABEL: name: fptosi_s32_s64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fprb(s64) = COPY $f10_d
    ; CHECK-NEXT: [[FCVT_W_RV64_:%[0-9]+]]:gprb(s64) = G_FCVT_W_RV64 [[COPY]](s64), 1
    ; CHECK-NEXT: $x10 = COPY [[FCVT_W_RV64_]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = G_FCVT_W_RV64 %0(s64), 1
    $x10 = COPY %1(s64)
    PseudoRET implicit $x10

...
---
name:            fptoui_s32_s64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $f10_d

    ; CHECK-LABEL: name: fptoui_s32_s64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fprb(s64) = COPY $f10_d
    ; CHECK-NEXT: [[FCVT_W_RV64_:%[0-9]+]]:gprb(s64) = G_FCVT_W_RV64 [[COPY]](s64), 1
    ; CHECK-NEXT: $x10 = COPY [[FCVT_W_RV64_]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = G_FCVT_W_RV64 %0(s64), 1
    $x10 = COPY %1(s64)
    PseudoRET implicit $x10

...
---
name:            fptosi_s64_s64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $f10_d

    ; CHECK-LABEL: name: fptosi_s64_s64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fprb(s64) = COPY $f10_d
    ; CHECK-NEXT: [[FPTOSI:%[0-9]+]]:gprb(s64) = G_FPTOSI [[COPY]](s64)
    ; CHECK-NEXT: $x10 = COPY [[FPTOSI]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = G_FPTOSI %0(s64)
    $x10 = COPY %1(s64)
    PseudoRET implicit $x10

...
---
name:            fptoui_s64_s64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $f10_d

    ; CHECK-LABEL: name: fptoui_s64_s64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fprb(s64) = COPY $f10_d
    ; CHECK-NEXT: [[FPTOUI:%[0-9]+]]:gprb(s64) = G_FPTOUI [[COPY]](s64)
    ; CHECK-NEXT: $x10 = COPY [[FPTOUI]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $f10_d
    %1:_(s64) = G_FPTOUI %0(s64)
    $x10 = COPY %1(s64)
    PseudoRET implicit $x10

...
