# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv32 -mattr=+d -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck %s

---
name:            fptosi_s32_s32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $f10_f

    ; CHECK-LABEL: name: fptosi_s32_s32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fprb(s32) = COPY $f10_f
    ; CHECK-NEXT: [[FPTOSI:%[0-9]+]]:gprb(s32) = G_FPTOSI [[COPY]](s32)
    ; CHECK-NEXT: $x10 = COPY [[FPTOSI]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = G_FPTOSI %0(s32)
    $x10 = COPY %1(s32)
    PseudoRET implicit $x10

...
---
name:            fptoui_s32_s32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $f10_f

    ; CHECK-LABEL: name: fptoui_s32_s32
    ; CHECK: liveins: $f10_f
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fprb(s32) = COPY $f10_f
    ; CHECK-NEXT: [[FPTOUI:%[0-9]+]]:gprb(s32) = G_FPTOUI [[COPY]](s32)
    ; CHECK-NEXT: $x10 = COPY [[FPTOUI]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s32) = COPY $f10_f
    %1:_(s32) = G_FPTOUI %0(s32)
    $x10 = COPY %1(s32)
    PseudoRET implicit $x10

...
---
name:            fptosi_s32_s64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $f10_d

    ; CHECK-LABEL: name: fptosi_s32_s64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fprb(s64) = COPY $f10_d
    ; CHECK-NEXT: [[FPTOSI:%[0-9]+]]:gprb(s32) = G_FPTOSI [[COPY]](s64)
    ; CHECK-NEXT: $x10 = COPY [[FPTOSI]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $f10_d
    %1:_(s32) = G_FPTOSI %0(s64)
    $x10 = COPY %1(s32)
    PseudoRET implicit $x10

...
---
name:            fptoui_s32_s64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $f10_d

    ; CHECK-LABEL: name: fptoui_s32_s64
    ; CHECK: liveins: $f10_d
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:fprb(s64) = COPY $f10_d
    ; CHECK-NEXT: [[FPTOUI:%[0-9]+]]:gprb(s32) = G_FPTOUI [[COPY]](s64)
    ; CHECK-NEXT: $x10 = COPY [[FPTOUI]](s32)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $f10_d
    %1:_(s32) = G_FPTOUI %0(s64)
    $x10 = COPY %1(s32)
    PseudoRET implicit $x10

...
