# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv64 -mattr=+zbb -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=RV64I %s

---
name:            smax_i64
legalized:       true
body:             |
  bb.0.entry:
    ; RV64I-LABEL: name: smax_i64
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I-NEXT: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I-NEXT: [[SMAX:%[0-9]+]]:gprb(s64) = G_SMAX [[COPY]], [[COPY1]]
    ; RV64I-NEXT: $x10 = COPY [[SMAX]](s64)
    ; RV64I-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_SMAX %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            smin_i64
legalized:       true
body:             |
  bb.0.entry:
    ; RV64I-LABEL: name: smin_i64
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I-NEXT: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I-NEXT: [[SMIN:%[0-9]+]]:gprb(s64) = G_SMIN [[COPY]], [[COPY1]]
    ; RV64I-NEXT: $x10 = COPY [[SMIN]](s64)
    ; RV64I-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_SMIN %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            umax_i64
legalized:       true
body:             |
  bb.0.entry:
    ; RV64I-LABEL: name: umax_i64
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I-NEXT: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I-NEXT: [[UMAX:%[0-9]+]]:gprb(s64) = G_UMAX [[COPY]], [[COPY1]]
    ; RV64I-NEXT: $x10 = COPY [[UMAX]](s64)
    ; RV64I-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_UMAX %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            umin_i64
legalized:       true
body:             |
  bb.0.entry:
    ; RV64I-LABEL: name: umin_i64
    ; RV64I: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I-NEXT: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I-NEXT: [[UMIN:%[0-9]+]]:gprb(s64) = G_UMIN [[COPY]], [[COPY1]]
    ; RV64I-NEXT: $x10 = COPY [[UMIN]](s64)
    ; RV64I-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_UMIN %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
