# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv32 -run-pass=regbankselect \
# RUN:   -disable-gisel-legality-check -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=RV32I %s

---
name:            phi_i32
legalized:       true
tracksRegLiveness: true
body:             |
  ; RV32I-LABEL: name: phi_i32
  ; RV32I: bb.0:
  ; RV32I-NEXT:   liveins: $x10, $x11, $x12
  ; RV32I-NEXT: {{  $}}
  ; RV32I-NEXT:   [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
  ; RV32I-NEXT:   [[COPY1:%[0-9]+]]:gprb(s32) = COPY $x11
  ; RV32I-NEXT:   [[COPY2:%[0-9]+]]:gprb(s32) = COPY $x12
  ; RV32I-NEXT:   [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
  ; RV32I-NEXT:   [[AND:%[0-9]+]]:gprb(s32) = G_AND [[COPY]], [[C]]
  ; RV32I-NEXT:   G_BRCOND [[AND]](s32), %bb.2
  ; RV32I-NEXT:   G_BR %bb.1
  ; RV32I-NEXT: {{  $}}
  ; RV32I-NEXT: bb.1:
  ; RV32I-NEXT: {{  $}}
  ; RV32I-NEXT: bb.2:
  ; RV32I-NEXT:   [[PHI:%[0-9]+]]:gprb(s32) = G_PHI [[COPY2]](s32), %bb.1, [[COPY1]](s32), %bb.0
  ; RV32I-NEXT:   $x10 = COPY [[PHI]](s32)
  ; RV32I-NEXT:   PseudoRET implicit $x10
  bb.0:
    liveins: $x10, $x11, $x12

    %3:_(s32) = COPY $x10
    %1:_(s32) = COPY $x11
    %2:_(s32) = COPY $x12
    %6:_(s32) = G_CONSTANT i32 1
    %5:_(s32) = G_AND %3, %6
    G_BRCOND %5(s32), %bb.2
    G_BR %bb.1

  bb.1:

  bb.2:
    %4:_(s32) = G_PHI %2(s32), %bb.1, %1(s32), %bb.0
    $x10 = COPY %4(s32)
    PseudoRET implicit $x10

...
---
name:            phi_ptr
legalized:       true
tracksRegLiveness: true
body:             |
  ; RV32I-LABEL: name: phi_ptr
  ; RV32I: bb.0.entry:
  ; RV32I-NEXT:   liveins: $x10, $x11, $x12
  ; RV32I-NEXT: {{  $}}
  ; RV32I-NEXT:   [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
  ; RV32I-NEXT:   [[COPY1:%[0-9]+]]:gprb(p0) = COPY $x11
  ; RV32I-NEXT:   [[COPY2:%[0-9]+]]:gprb(p0) = COPY $x12
  ; RV32I-NEXT:   [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
  ; RV32I-NEXT:   [[AND:%[0-9]+]]:gprb(s32) = G_AND [[COPY]], [[C]]
  ; RV32I-NEXT:   G_BRCOND [[AND]](s32), %bb.2
  ; RV32I-NEXT:   G_BR %bb.1
  ; RV32I-NEXT: {{  $}}
  ; RV32I-NEXT: bb.1:
  ; RV32I-NEXT: {{  $}}
  ; RV32I-NEXT: bb.2:
  ; RV32I-NEXT:   [[PHI:%[0-9]+]]:gprb(p0) = G_PHI [[COPY2]](p0), %bb.1, [[COPY1]](p0), %bb.0
  ; RV32I-NEXT:   $x10 = COPY [[PHI]](p0)
  ; RV32I-NEXT:   PseudoRET implicit $x10
  bb.0.entry:
    liveins: $x10, $x11, $x12

    %3:_(s32) = COPY $x10
    %1:_(p0) = COPY $x11
    %2:_(p0) = COPY $x12
    %6:_(s32) = G_CONSTANT i32 1
    %5:_(s32) = G_AND %3, %6
    G_BRCOND %5(s32), %bb.2
    G_BR %bb.1

  bb.1:

  bb.2:
    %4:_(p0) = G_PHI %2(p0), %bb.1, %1(p0), %bb.0
    $x10 = COPY %4(p0)
    PseudoRET implicit $x10

...
