# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv64 -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=RV64I %s

---
name:            select_i64
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12

    ; RV64I-LABEL: name: select_i64
    ; RV64I: liveins: $x10, $x11, $x12
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I-NEXT: [[COPY1:%[0-9]+]]:gprb(s64) = COPY $x11
    ; RV64I-NEXT: [[COPY2:%[0-9]+]]:gprb(s64) = COPY $x12
    ; RV64I-NEXT: [[C:%[0-9]+]]:gprb(s64) = G_CONSTANT i64 1
    ; RV64I-NEXT: [[AND:%[0-9]+]]:gprb(s64) = G_AND [[COPY]], [[C]]
    ; RV64I-NEXT: [[SELECT:%[0-9]+]]:gprb(s64) = G_SELECT [[AND]](s64), [[COPY1]], [[COPY2]]
    ; RV64I-NEXT: $x10 = COPY [[SELECT]](s64)
    ; RV64I-NEXT: PseudoRET implicit $x10
    %3:_(s64) = COPY $x10
    %4:_(s64) = COPY $x11
    %5:_(s64) = COPY $x12
    %12:_(s64) = G_CONSTANT i64 1
    %11:_(s64) = G_AND %3, %12
    %10:_(s64) = G_SELECT %11(s64), %4, %5
    $x10 = COPY %10(s64)
    PseudoRET implicit $x10

...
---
name:            select_ptr
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12

    ; RV64I-LABEL: name: select_ptr
    ; RV64I: liveins: $x10, $x11, $x12
    ; RV64I-NEXT: {{  $}}
    ; RV64I-NEXT: [[COPY:%[0-9]+]]:gprb(s64) = COPY $x10
    ; RV64I-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $x11
    ; RV64I-NEXT: [[COPY2:%[0-9]+]]:gprb(p0) = COPY $x12
    ; RV64I-NEXT: [[C:%[0-9]+]]:gprb(s64) = G_CONSTANT i64 1
    ; RV64I-NEXT: [[AND:%[0-9]+]]:gprb(s64) = G_AND [[COPY]], [[C]]
    ; RV64I-NEXT: [[SELECT:%[0-9]+]]:gprb(p0) = G_SELECT [[AND]](s64), [[COPY1]], [[COPY2]]
    ; RV64I-NEXT: $x10 = COPY [[SELECT]](p0)
    ; RV64I-NEXT: PseudoRET implicit $x10
    %3:_(s64) = COPY $x10
    %4:_(p0) = COPY $x11
    %5:_(p0) = COPY $x12
    %12:_(s64) = G_CONSTANT i64 1
    %11:_(s64) = G_AND %3, %12
    %10:_(p0) = G_SELECT %11(s64), %4, %5
    $x10 = COPY %10(p0)
    PseudoRET implicit $x10

...
