# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv32 -run-pass=regbankselect \
# RUN:   -simplify-mir -verify-machineinstrs %s \
# RUN:   -o - | FileCheck -check-prefix=RV32I %s

---
name:            store_i8
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: store_i8
    ; RV32I: liveins: $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $x11
    ; RV32I-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s8))
    ; RV32I-NEXT: PseudoRET
    %2:_(s32) = COPY $x10
    %1:_(p0) = COPY $x11
    G_STORE %2(s32), %1(p0) :: (store (s8))
    PseudoRET

...
---
name:            store_i16
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: store_i16
    ; RV32I: liveins: $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $x11
    ; RV32I-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s16))
    ; RV32I-NEXT: PseudoRET
    %2:_(s32) = COPY $x10
    %1:_(p0) = COPY $x11
    G_STORE %2(s32), %1(p0) :: (store (s16))
    PseudoRET

...
---
name:            store_i32
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: store_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $x10
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $x11
    ; RV32I-NEXT: G_STORE [[COPY]](s32), [[COPY1]](p0) :: (store (s32))
    ; RV32I-NEXT: PseudoRET
    %0:_(s32) = COPY $x10
    %1:_(p0) = COPY $x11
    G_STORE %0(s32), %1(p0) :: (store (s32))
    PseudoRET

...
---
name:            store_ptr
legalized:       true
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: store_ptr
    ; RV32I: liveins: $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gprb(p0) = COPY $x10
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gprb(p0) = COPY $x11
    ; RV32I-NEXT: G_STORE [[COPY]](p0), [[COPY1]](p0) :: (store (p0), align 8)
    ; RV32I-NEXT: PseudoRET
    %0:_(p0) = COPY $x10
    %1:_(p0) = COPY $x11
    G_STORE %0(p0), %1(p0) :: (store (p0), align 8)
    PseudoRET

...
