; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=msp430 < %s | FileCheck %s

; Test custom lowering for 16-bit constant multiplication.

define i16 @mul_by_2(i16 %a) nounwind {
; CHECK-LABEL: mul_by_2:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add r12, r12
; CHECK-NEXT:    ret
  %1 = mul i16 %a, 2
  ret i16 %1
}

define i16 @mul_by_3(i16 %a) nounwind {
; CHECK-LABEL: mul_by_3:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r12, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r12
; CHECK-NEXT:    ret
  %1 = mul i16 %a, 3
  ret i16 %1
}

define i16 @mul_by_5(i16 %a) nounwind {
; CHECK-LABEL: mul_by_5:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r12, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r12
; CHECK-NEXT:    ret
  %1 = mul i16 %a, 5
  ret i16 %1
}

define i16 @mul_by_6(i16 %a) nounwind {
; CHECK-LABEL: mul_by_6:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r12, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    sub r12, r13
; CHECK-NEXT:    sub r12, r13
; CHECK-NEXT:    mov r13, r12
; CHECK-NEXT:    ret
  %1 = mul i16 %a, 6
  ret i16 %1
}

define i16 @mul_by_7(i16 %a) nounwind {
; CHECK-LABEL: mul_by_7:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r12, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    sub r12, r13
; CHECK-NEXT:    mov r13, r12
; CHECK-NEXT:    ret
  %1 = mul i16 %a, 7
  ret i16 %1
}

define i16 @mul_by_8(i16 %a) nounwind {
; CHECK-LABEL: mul_by_8:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add r12, r12
; CHECK-NEXT:    add r12, r12
; CHECK-NEXT:    add r12, r12
; CHECK-NEXT:    ret
  %1 = mul i16 %a, 8
  ret i16 %1
}

define i16 @mul_by_9(i16 %a) nounwind {
; CHECK-LABEL: mul_by_9:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r12, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r12
; CHECK-NEXT:    ret
  %1 = mul i16 %a, 9
  ret i16 %1
}

define i16 @mul_by_10(i16 %a) nounwind {
; CHECK-LABEL: mul_by_10:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r12, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r12
; CHECK-NEXT:    add r12, r12
; CHECK-NEXT:    ret
  %1 = mul i16 %a, 10
  ret i16 %1
}

define i16 @mul_by_15(i16 %a) nounwind {
; CHECK-LABEL: mul_by_15:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r12, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    sub r12, r13
; CHECK-NEXT:    mov r13, r12
; CHECK-NEXT:    ret
  %1 = mul i16 %a, 15
  ret i16 %1
}

define i16 @mul_by_16(i16 %a) nounwind {
; CHECK-LABEL: mul_by_16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add r12, r12
; CHECK-NEXT:    add r12, r12
; CHECK-NEXT:    add r12, r12
; CHECK-NEXT:    add r12, r12
; CHECK-NEXT:    ret
  %1 = mul i16 %a, 16
  ret i16 %1
}

define i16 @mul_by_17(i16 %a) nounwind {
; CHECK-LABEL: mul_by_17:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r12, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r12
; CHECK-NEXT:    ret
  %1 = mul i16 %a, 17
  ret i16 %1
}

define i16 @mul_by_neg3(i16 %a) nounwind {
; CHECK-LABEL: mul_by_neg3:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r12, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    sub r13, r12
; CHECK-NEXT:    ret
  %1 = mul i16 %a, -3
  ret i16 %1
}

define i16 @mul_by_neg7(i16 %a) nounwind {
; CHECK-LABEL: mul_by_neg7:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r12, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    sub r13, r12
; CHECK-NEXT:    ret
  %1 = mul i16 %a, -7
  ret i16 %1
}

define i16 @mul_by_neg9(i16 %a) nounwind {
; CHECK-LABEL: mul_by_neg9:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    clr r13
; CHECK-NEXT:    sub r12, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    sub r12, r13
; CHECK-NEXT:    mov r13, r12
; CHECK-NEXT:    ret
  %1 = mul i16 %a, -9
  ret i16 %1
}

define i16 @mul_by_12345(i16 %a) nounwind {
; CHECK-LABEL: mul_by_12345:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r12, r13
; CHECK-NEXT:    mov.b r13, r13
; CHECK-NEXT:    swpb r13
; CHECK-NEXT:    add r12, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r12, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    add r13, r13
; CHECK-NEXT:    sub r12, r13
; CHECK-NEXT:    mov r13, r12
; CHECK-NEXT:    add r12, r12
; CHECK-NEXT:    add r12, r12
; CHECK-NEXT:    sub r13, r12
; CHECK-NEXT:    ret
  %1 = mul i16 %a, 12345
  ret i16 %1
}

; Non-constant multiply should still use libcall.
define i16 @mul_variable(i16 %a, i16 %b) nounwind {
; CHECK-LABEL: mul_variable:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    call #__mspabi_mpyi
; CHECK-NEXT:    ret
  %1 = mul i16 %a, %b
  ret i16 %1
}
