; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple msp430 | FileCheck %s -check-prefixes=CHECK

declare dso_local void @main()

define dso_local void @naked() naked "frame-pointer"="all" {
; CHECK-LABEL: naked:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    call #main
  call void @main()
  unreachable
}

define dso_local void @normal() "frame-pointer"="all" {
; CHECK-LABEL: normal:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    push r4
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset r4, -4
; CHECK-NEXT:    mov r1, r4
; CHECK-NEXT:    .cfi_def_cfa_register r4
; CHECK-NEXT:    call #main
  call void @main()
  unreachable
}
