; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs --version 6
; Tests lowerings of different versions of coro.await.suspend
; RUN: opt < %s -passes='module(coro-early),cgscc(coro-split),simplifycfg' -S | FileCheck %s

%Awaiter = type {}

define void @f() presplitcoroutine {
entry:
  %awaiter = alloca %Awaiter
  %id = call token @llvm.coro.id(i32 0, ptr null, ptr null, ptr null)
  %size = call i32 @llvm.coro.size.i32()
  %alloc = call ptr @malloc(i32 %size)
  %hdl = call ptr @llvm.coro.begin(token %id, ptr %alloc)
  %suspend.init = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %suspend.init, label %ret [
  i8 0, label %step
  i8 1, label %cleanup
  ]

step:
  %save = call token @llvm.coro.save(ptr null)
  call void @llvm.coro.await.suspend.void(ptr %awaiter, ptr %hdl, ptr @await_suspend_wrapper_void)
  %suspend = call i8 @llvm.coro.suspend(token %save, i1 false)
  switch i8 %suspend, label %ret [
  i8 0, label %step1
  i8 1, label %cleanup
  ]

step1:
  %save1 = call token @llvm.coro.save(ptr null)
  %resume.bool = call i1 @llvm.coro.await.suspend.bool(ptr %awaiter, ptr %hdl, ptr @await_suspend_wrapper_bool)
  br i1 %resume.bool, label %suspend.cond, label %step2

suspend.cond:
  %suspend1 = call i8 @llvm.coro.suspend(token %save1, i1 false)
  switch i8 %suspend1, label %ret [
  i8 0, label %step2
  i8 1, label %cleanup
  ]

step2:
  %save2 = call token @llvm.coro.save(ptr null)
  call void @llvm.coro.await.suspend.handle(ptr %awaiter, ptr %hdl, ptr @await_suspend_wrapper_handle)
  %suspend2 = call i8 @llvm.coro.suspend(token %save2, i1 false)
  switch i8 %suspend2, label %ret [
  i8 0, label %step3
  i8 1, label %cleanup
  ]

step3:
  br label %cleanup

cleanup:
  %mem = call ptr @llvm.coro.free(token %id, ptr %hdl)
  call void @free(ptr %mem)
  br label %ret

ret:
  call void @llvm.coro.end(ptr %hdl, i1 0, token none)
  ret void
}

declare void @await_suspend_wrapper_void(ptr, ptr)
declare i1 @await_suspend_wrapper_bool(ptr, ptr)
declare ptr @await_suspend_wrapper_handle(ptr, ptr)

declare ptr @llvm.coro.free(token, ptr)
declare i32 @llvm.coro.size.i32()
declare i8  @llvm.coro.suspend(token, i1)
declare void @llvm.coro.resume(ptr)
declare void @llvm.coro.destroy(ptr)

declare token @llvm.coro.id(i32, ptr, ptr, ptr)
declare i1 @llvm.coro.alloc(token)
declare ptr @llvm.coro.begin(token, ptr)
declare void @llvm.coro.await.suspend.void(ptr, ptr, ptr)
declare i1 @llvm.coro.await.suspend.bool(ptr, ptr, ptr)
declare void @llvm.coro.await.suspend.handle(ptr, ptr, ptr)
declare void @llvm.coro.end(ptr, i1, token)

declare noalias ptr @malloc(i32)
declare void @free(ptr)
; CHECK-LABEL: define void @f() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ID:%.*]] = call token @llvm.coro.id(i32 0, ptr null, ptr @f, ptr @f.resumers)
; CHECK-NEXT:    [[ALLOC:%.*]] = call ptr @malloc(i32 24)
; CHECK-NEXT:    [[HDL:%.*]] = call noalias nonnull ptr @llvm.coro.begin(token [[ID]], ptr [[ALLOC]])
; CHECK-NEXT:    store ptr @f.resume, ptr [[HDL]], align 8
; CHECK-NEXT:    [[DESTROY_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 8
; CHECK-NEXT:    store ptr @f.destroy, ptr [[DESTROY_ADDR]], align 8
; CHECK-NEXT:    [[AWAITER_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 0
; CHECK-NEXT:    [[INDEX_ADDR12:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 16
; CHECK-NEXT:    store i2 0, ptr [[INDEX_ADDR12]], align 1
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal void @f.resume(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(24) [[HDL:%.*]]) {
; CHECK-NEXT:  [[ENTRY_RESUME:.*]]:
; CHECK-NEXT:    [[AWAITER_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 0
; CHECK-NEXT:    [[INDEX_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 16
; CHECK-NEXT:    [[INDEX:%.*]] = load i2, ptr [[INDEX_ADDR]], align 1
; CHECK-NEXT:    switch i2 [[INDEX]], label %[[UNREACHABLE:.*]] [
; CHECK-NEXT:      i2 0, label %[[COROSAVE1:.*]]
; CHECK-NEXT:      i2 1, label %[[AFTERCOROSUSPEND3:.*]]
; CHECK-NEXT:      i2 -2, label %[[AFTERCOROSUSPEND7:.*]]
; CHECK-NEXT:      i2 -1, label %[[CLEANUP:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[COROSAVE1]]:
; CHECK-NEXT:    [[INDEX_ADDR13:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 16
; CHECK-NEXT:    store i2 1, ptr [[INDEX_ADDR13]], align 1
; CHECK-NEXT:    call void @await_suspend_wrapper_void(ptr [[AWAITER_RELOAD_ADDR]], ptr [[HDL]])
; CHECK-NEXT:    br label %[[AFTERCOROSUSPEND3]]
; CHECK:       [[AFTERCOROSUSPEND3]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i8 [ -1, %[[COROSAVE1]] ], [ 0, %[[ENTRY_RESUME]] ]
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i8 [[TMP0]], 0
; CHECK-NEXT:    br i1 [[COND]], label %[[COROSAVE4:.*]], label %[[COROEND:.*]]
; CHECK:       [[COROSAVE4]]:
; CHECK-NEXT:    [[INDEX_ADDR14:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 16
; CHECK-NEXT:    store i2 -2, ptr [[INDEX_ADDR14]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = call i1 @await_suspend_wrapper_bool(ptr [[AWAITER_RELOAD_ADDR]], ptr [[HDL]])
; CHECK-NEXT:    br i1 [[TMP1]], label %[[AFTERCOROSUSPEND7]], label %[[COROSAVE8:.*]]
; CHECK:       [[AFTERCOROSUSPEND7]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi i8 [ -1, %[[COROSAVE4]] ], [ 0, %[[ENTRY_RESUME]] ]
; CHECK-NEXT:    [[COND1:%.*]] = icmp eq i8 [[TMP2]], 0
; CHECK-NEXT:    br i1 [[COND1]], label %[[COROSAVE8]], label %[[COROEND]]
; CHECK:       [[COROSAVE8]]:
; CHECK-NEXT:    [[INDEX_ADDR15:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 16
; CHECK-NEXT:    store i2 -1, ptr [[INDEX_ADDR15]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = call ptr @await_suspend_wrapper_handle(ptr [[AWAITER_RELOAD_ADDR]], ptr [[HDL]])
; CHECK-NEXT:    [[TMP4:%.*]] = call ptr @llvm.coro.subfn.addr(ptr [[TMP3]], i8 0)
; CHECK-NEXT:    musttail call void [[TMP4]](ptr [[TMP3]])
; CHECK-NEXT:    ret void
; CHECK:       [[CLEANUP]]:
; CHECK-NEXT:    [[MEM:%.*]] = call ptr @llvm.coro.free(token poison, ptr [[HDL]])
; CHECK-NEXT:    call void @free(ptr [[MEM]])
; CHECK-NEXT:    br label %[[COROEND]]
; CHECK:       [[COROEND]]:
; CHECK-NEXT:    ret void
; CHECK:       [[UNREACHABLE]]:
; CHECK-NEXT:    unreachable
;
;
; CHECK-LABEL: define internal void @f.destroy(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(24) [[HDL:%.*]]) {
; CHECK-NEXT:  [[ENTRY_DESTROY:.*:]]
; CHECK-NEXT:    [[AWAITER_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 0
; CHECK-NEXT:    [[MEM:%.*]] = call ptr @llvm.coro.free(token poison, ptr [[HDL]])
; CHECK-NEXT:    call void @free(ptr [[MEM]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal void @f.cleanup(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(24) [[HDL:%.*]]) {
; CHECK-NEXT:  [[ENTRY_CLEANUP:.*:]]
; CHECK-NEXT:    [[AWAITER_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 0
; CHECK-NEXT:    call void @free(ptr null)
; CHECK-NEXT:    ret void
;
