; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs --version 6
; Tests that coro-split will optimize the lifetime.start maker of each local variable,
; sink them to the places after the suspend block.
; RUN: opt < %s -passes='cgscc(coro-split),simplifycfg,early-cse' -S | FileCheck %s

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"

%"struct.std::coroutine_handle" = type { ptr }
%"struct.std::coroutine_handle.0" = type { %"struct.std::coroutine_handle" }
%"struct.lean_future<int>::Awaiter" = type { i32, %"struct.std::coroutine_handle.0" }

declare i1 @getcond()
declare ptr @malloc(i64)
declare void @print(i32)

define void @a() presplitcoroutine {
entry:
  %ref.tmp7 = alloca %"struct.lean_future<int>::Awaiter", align 8
  %testval = alloca i32
  ; lifetime of %testval starts here, but not used until await.ready.
  call void @llvm.lifetime.start.p0(ptr %testval)
  %id = call token @llvm.coro.id(i32 0, ptr null, ptr @a, ptr null)
  %alloc = call ptr @malloc(i64 16) #3
  %vFrame = call noalias nonnull ptr @llvm.coro.begin(token %id, ptr %alloc)
  %testcond = call i1 @getcond()
  br i1 %testcond, label %if.suspend, label %else.direct

if.suspend:
  %save = call token @llvm.coro.save(ptr null)
  %suspend = call i8 @llvm.coro.suspend(token %save, i1 false)
  switch i8 %suspend, label %exit [
    i8 0, label %await.ready
    i8 1, label %exit
  ]

else.direct:
  br label %after.await

await.ready:
  %StrayCoroSave = call token @llvm.coro.save(ptr null)
  %val = load i32, ptr %ref.tmp7
  %test = load i32, ptr %testval
  call void @print(i32 %test)
  call void @print(i32 %val)
  br label %after.await

after.await:
  %test1 = load i32, ptr %testval
  call void @print(i32 %test1)
  call void @llvm.lifetime.end.p0(ptr  %testval)
  br label %exit

exit:
  call void @llvm.coro.end(ptr null, i1 false, token none)
  ret void
}


declare token @llvm.coro.id(i32, ptr readnone, ptr nocapture readonly, ptr)
declare i1 @llvm.coro.alloc(token) #3
declare noalias nonnull ptr @"\01??2@YAPEAX_K@Z"(i64) local_unnamed_addr
declare i64 @llvm.coro.size.i64() #5
declare ptr @llvm.coro.begin(token, ptr writeonly) #3
declare void @"\01?puts@@YAXZZ"(...)
declare token @llvm.coro.save(ptr) #3
declare ptr @llvm.coro.frame() #5
declare i8 @llvm.coro.suspend(token, i1) #3
declare void @"\01??3@YAXPEAX@Z"(ptr) local_unnamed_addr #10
declare ptr @llvm.coro.free(token, ptr nocapture readonly) #2
declare void @llvm.coro.end(ptr, i1, token) #3
declare void @llvm.lifetime.start.p0(ptr nocapture) #4
declare void @llvm.lifetime.end.p0(ptr nocapture) #4
; CHECK-LABEL: define void @a() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[REF_TMP7:%.*]] = alloca %"struct.lean_future<int>::Awaiter", align 8
; CHECK-NEXT:    [[ID:%.*]] = call token @llvm.coro.id(i32 0, ptr null, ptr @a, ptr @a.resumers)
; CHECK-NEXT:    [[ALLOC:%.*]] = call ptr @malloc(i64 16)
; CHECK-NEXT:    [[VFRAME:%.*]] = call noalias nonnull ptr @llvm.coro.begin(token [[ID]], ptr [[ALLOC]])
; CHECK-NEXT:    store ptr @a.resume, ptr [[VFRAME]], align 8
; CHECK-NEXT:    [[DESTROY_ADDR:%.*]] = getelementptr inbounds i8, ptr [[VFRAME]], i64 8
; CHECK-NEXT:    store ptr @a.destroy, ptr [[DESTROY_ADDR]], align 8
; CHECK-NEXT:    [[TESTVAL_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[VFRAME]], i64 16
; CHECK-NEXT:    [[TESTCOND:%.*]] = call i1 @getcond()
; CHECK-NEXT:    br i1 [[TESTCOND]], label %[[COROSAVE:.*]], label %[[AFTER_AWAIT:.*]]
; CHECK:       [[COROSAVE]]:
; CHECK-NEXT:    [[INDEX_ADDR1:%.*]] = getelementptr inbounds i8, ptr [[VFRAME]], i64 20
; CHECK-NEXT:    store i1 false, ptr [[INDEX_ADDR1]], align 1
; CHECK-NEXT:    br i1 false, label %[[AWAIT_READY:.*]], label %[[AFTERCOROEND:.*]]
; CHECK:       [[AWAIT_READY]]:
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[REF_TMP7]], align 4
; CHECK-NEXT:    [[TEST:%.*]] = load i32, ptr [[TESTVAL_RELOAD_ADDR]], align 4
; CHECK-NEXT:    call void @print(i32 [[TEST]])
; CHECK-NEXT:    call void @print(i32 [[VAL]])
; CHECK-NEXT:    br label %[[AFTER_AWAIT]]
; CHECK:       [[AFTER_AWAIT]]:
; CHECK-NEXT:    [[TEST1:%.*]] = load i32, ptr [[TESTVAL_RELOAD_ADDR]], align 4
; CHECK-NEXT:    call void @print(i32 [[TEST1]])
; CHECK-NEXT:    br label %[[AFTERCOROEND]]
; CHECK:       [[AFTERCOROEND]]:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal fastcc void @a.resume(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(24) [[VFRAME:%.*]]) {
; CHECK-NEXT:  [[ENTRY_RESUME:.*:]]
; CHECK-NEXT:    [[REF_TMP7:%.*]] = alloca %"struct.lean_future<int>::Awaiter", align 8
; CHECK-NEXT:    [[TESTVAL_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[VFRAME]], i64 16
; CHECK-NEXT:    br i1 true, label %[[AWAIT_READY:.*]], label %[[COROEND:.*]]
; CHECK:       [[AWAIT_READY]]:
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[REF_TMP7]], align 4
; CHECK-NEXT:    [[TEST:%.*]] = load i32, ptr [[TESTVAL_RELOAD_ADDR]], align 4
; CHECK-NEXT:    call void @print(i32 [[TEST]])
; CHECK-NEXT:    call void @print(i32 [[VAL]])
; CHECK-NEXT:    [[TEST1:%.*]] = load i32, ptr [[TESTVAL_RELOAD_ADDR]], align 4
; CHECK-NEXT:    call void @print(i32 [[TEST1]])
; CHECK-NEXT:    br label %[[COROEND]]
; CHECK:       [[COROEND]]:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal fastcc void @a.destroy(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(24) [[VFRAME:%.*]]) {
; CHECK-NEXT:  [[ENTRY_DESTROY:.*:]]
; CHECK-NEXT:    [[REF_TMP7:%.*]] = alloca %"struct.lean_future<int>::Awaiter", align 8
; CHECK-NEXT:    [[TESTVAL_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[VFRAME]], i64 16
; CHECK-NEXT:    br i1 false, label %[[AWAIT_READY:.*]], label %[[COROEND:.*]]
; CHECK:       [[AWAIT_READY]]:
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[REF_TMP7]], align 4
; CHECK-NEXT:    [[TEST:%.*]] = load i32, ptr [[TESTVAL_RELOAD_ADDR]], align 4
; CHECK-NEXT:    call void @print(i32 [[TEST]])
; CHECK-NEXT:    call void @print(i32 [[VAL]])
; CHECK-NEXT:    [[TEST1:%.*]] = load i32, ptr [[TESTVAL_RELOAD_ADDR]], align 4
; CHECK-NEXT:    call void @print(i32 [[TEST1]])
; CHECK-NEXT:    br label %[[COROEND]]
; CHECK:       [[COROEND]]:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal fastcc void @a.cleanup(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(24) [[VFRAME:%.*]]) {
; CHECK-NEXT:  [[ENTRY_CLEANUP:.*:]]
; CHECK-NEXT:    [[REF_TMP7:%.*]] = alloca %"struct.lean_future<int>::Awaiter", align 8
; CHECK-NEXT:    [[TESTVAL_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[VFRAME]], i64 16
; CHECK-NEXT:    br i1 false, label %[[AWAIT_READY:.*]], label %[[COROEND:.*]]
; CHECK:       [[AWAIT_READY]]:
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[REF_TMP7]], align 4
; CHECK-NEXT:    [[TEST:%.*]] = load i32, ptr [[TESTVAL_RELOAD_ADDR]], align 4
; CHECK-NEXT:    call void @print(i32 [[TEST]])
; CHECK-NEXT:    call void @print(i32 [[VAL]])
; CHECK-NEXT:    [[TEST1:%.*]] = load i32, ptr [[TESTVAL_RELOAD_ADDR]], align 4
; CHECK-NEXT:    call void @print(i32 [[TEST1]])
; CHECK-NEXT:    br label %[[COROEND]]
; CHECK:       [[COROEND]]:
; CHECK-NEXT:    ret void
;
