; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs --version 6
; Check that the return value of @llvm.coro.suspend gets spilled to the frame
; if it may be used across suspend points.
; RUN: opt < %s -passes='cgscc(coro-split),simplifycfg,early-cse' -S | FileCheck %s

; %sp1 should be part of the frame (the i8 value).
; If the coro resumes, %sp1 is set to 0.
; In the coro destroy function, %sp1 is reloaded from the frame. Its value
; depends on whether the coroutine was resumed or not.
define ptr @f(i32 %n) presplitcoroutine {
entry:
  %id = call token @llvm.coro.id(i32 0, ptr null, ptr @f, ptr null)
  %size = call i32 @llvm.coro.size.i32()
  %alloc = call ptr @malloc(i32 %size)
  %hdl = call ptr @llvm.coro.begin(token %id, ptr %alloc)

  %sp1 = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %sp1, label %suspend [i8 0, label %resume1
  i8 1, label %cleanup]

resume1:
  %sp2 = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %sp2, label %suspend [i8 0, label %resume2
  i8 1, label %cleanup]

resume2:
  br label %cleanup

cleanup:
  ; This use of %sp1 may cross a suspend point (%sp2).
  call void @print(i8 %sp1)

  %mem = call ptr @llvm.coro.free(token %id, ptr %hdl)
  call void @free(ptr %mem)
  br label %suspend

suspend:
  call void @llvm.coro.end(ptr %hdl, i1 0, token none)
  ret ptr %hdl
}


declare noalias ptr @malloc(i32)
declare void @print(i8)
declare void @free(ptr)
; CHECK-LABEL: define ptr @f(
; CHECK-SAME: i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ID:%.*]] = call token @llvm.coro.id(i32 0, ptr null, ptr @f, ptr @f.resumers)
; CHECK-NEXT:    [[ALLOC:%.*]] = call ptr @malloc(i32 24)
; CHECK-NEXT:    [[HDL:%.*]] = call noalias nonnull ptr @llvm.coro.begin(token [[ID]], ptr [[ALLOC]])
; CHECK-NEXT:    store ptr @f.resume, ptr [[HDL]], align 8
; CHECK-NEXT:    [[DESTROY_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 8
; CHECK-NEXT:    store ptr @f.destroy, ptr [[DESTROY_ADDR]], align 8
; CHECK-NEXT:    [[INDEX_ADDR4:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 16
; CHECK-NEXT:    store i1 false, ptr [[INDEX_ADDR4]], align 1
; CHECK-NEXT:    [[SP1_SPILL_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 17
; CHECK-NEXT:    store i8 -1, ptr [[SP1_SPILL_ADDR]], align 1
; CHECK-NEXT:    ret ptr [[HDL]]
;
;
; CHECK-LABEL: define internal fastcc void @f.resume(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(24) [[HDL:%.*]]) {
; CHECK-NEXT:  [[ENTRY_RESUME:.*]]:
; CHECK-NEXT:    [[INDEX_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 16
; CHECK-NEXT:    [[INDEX:%.*]] = load i1, ptr [[INDEX_ADDR]], align 1
; CHECK-NEXT:    switch i1 [[INDEX]], label %[[UNREACHABLE:.*]] [
; CHECK-NEXT:      i1 false, label %[[AFTERCOROSUSPEND:.*]]
; CHECK-NEXT:      i1 true, label %[[AFTERCOROSUSPEND3:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[AFTERCOROSUSPEND]]:
; CHECK-NEXT:    [[SP1_SPILL_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 17
; CHECK-NEXT:    store i8 0, ptr [[SP1_SPILL_ADDR]], align 1
; CHECK-NEXT:    store i1 true, ptr [[INDEX_ADDR]], align 1
; CHECK-NEXT:    br label %[[AFTERCOROSUSPEND3]]
; CHECK:       [[AFTERCOROSUSPEND3]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i8 [ -1, %[[AFTERCOROSUSPEND]] ], [ 0, %[[ENTRY_RESUME]] ]
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i8 [[TMP0]], 0
; CHECK-NEXT:    br i1 [[COND]], label %[[CLEANUP:.*]], label %[[COROEND:.*]]
; CHECK:       [[CLEANUP]]:
; CHECK-NEXT:    [[SP1_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 17
; CHECK-NEXT:    [[SP1_RELOAD:%.*]] = load i8, ptr [[SP1_RELOAD_ADDR]], align 1
; CHECK-NEXT:    call void @print(i8 [[SP1_RELOAD]])
; CHECK-NEXT:    [[MEM:%.*]] = call ptr @llvm.coro.free(token poison, ptr [[HDL]])
; CHECK-NEXT:    call void @free(ptr [[MEM]])
; CHECK-NEXT:    br label %[[COROEND]]
; CHECK:       [[COROEND]]:
; CHECK-NEXT:    ret void
; CHECK:       [[UNREACHABLE]]:
; CHECK-NEXT:    unreachable
;
;
; CHECK-LABEL: define internal fastcc void @f.destroy(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(24) [[HDL:%.*]]) {
; CHECK-NEXT:  [[ENTRY_DESTROY:.*:]]
; CHECK-NEXT:    [[INDEX_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 16
; CHECK-NEXT:    [[INDEX:%.*]] = load i1, ptr [[INDEX_ADDR]], align 1
; CHECK-NEXT:    switch i1 [[INDEX]], label %[[UNREACHABLE:.*]] [
; CHECK-NEXT:      i1 false, label %[[AFTERCOROSUSPEND:.*]]
; CHECK-NEXT:      i1 true, label %[[CLEANUP:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[AFTERCOROSUSPEND]]:
; CHECK-NEXT:    [[SP1_SPILL_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 17
; CHECK-NEXT:    store i8 1, ptr [[SP1_SPILL_ADDR]], align 1
; CHECK-NEXT:    br label %[[CLEANUP]]
; CHECK:       [[CLEANUP]]:
; CHECK-NEXT:    [[SP1_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 17
; CHECK-NEXT:    [[SP1_RELOAD:%.*]] = load i8, ptr [[SP1_RELOAD_ADDR]], align 1
; CHECK-NEXT:    call void @print(i8 [[SP1_RELOAD]])
; CHECK-NEXT:    [[MEM:%.*]] = call ptr @llvm.coro.free(token poison, ptr [[HDL]])
; CHECK-NEXT:    call void @free(ptr [[MEM]])
; CHECK-NEXT:    ret void
; CHECK:       [[UNREACHABLE]]:
; CHECK-NEXT:    unreachable
;
;
; CHECK-LABEL: define internal fastcc void @f.cleanup(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(24) [[HDL:%.*]]) {
; CHECK-NEXT:  [[ENTRY_CLEANUP:.*:]]
; CHECK-NEXT:    [[INDEX_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 16
; CHECK-NEXT:    [[INDEX:%.*]] = load i1, ptr [[INDEX_ADDR]], align 1
; CHECK-NEXT:    switch i1 [[INDEX]], label %[[UNREACHABLE:.*]] [
; CHECK-NEXT:      i1 false, label %[[AFTERCOROSUSPEND:.*]]
; CHECK-NEXT:      i1 true, label %[[CLEANUP:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[AFTERCOROSUSPEND]]:
; CHECK-NEXT:    [[SP1_SPILL_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 17
; CHECK-NEXT:    store i8 1, ptr [[SP1_SPILL_ADDR]], align 1
; CHECK-NEXT:    br label %[[CLEANUP]]
; CHECK:       [[CLEANUP]]:
; CHECK-NEXT:    [[SP1_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 17
; CHECK-NEXT:    [[SP1_RELOAD:%.*]] = load i8, ptr [[SP1_RELOAD_ADDR]], align 1
; CHECK-NEXT:    call void @print(i8 [[SP1_RELOAD]])
; CHECK-NEXT:    call void @free(ptr null)
; CHECK-NEXT:    ret void
; CHECK:       [[UNREACHABLE]]:
; CHECK-NEXT:    unreachable
;
