; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; Verifies that we can insert the spill for a PHI preceding the catchswitch
; RUN: opt < %s -passes='cgscc(coro-split),simplifycfg,early-cse' -S | FileCheck %s

target datalayout = "e-m:x-p:32:32-i64:64-f80:32-n8:16:32-a:0:32-S32"
target triple = "i686-pc-windows-msvc"

define void @f(i1 %cond) presplitcoroutine personality i32 0 {
; CHECK-LABEL: define void @f(
; CHECK-SAME: i1 [[COND:%.*]]) personality i32 0 {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ID:%.*]] = call token @llvm.coro.id(i32 8, ptr null, ptr null, ptr @f.resumers)
; CHECK-NEXT:    [[ALLOC:%.*]] = call ptr @malloc(i32 16)
; CHECK-NEXT:    [[HDL:%.*]] = call noalias nonnull ptr @llvm.coro.begin(token [[ID]], ptr [[ALLOC]])
; CHECK-NEXT:    store ptr @f.resume, ptr [[HDL]], align 4
; CHECK-NEXT:    [[DESTROY_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 4
; CHECK-NEXT:    store ptr @f.destroy, ptr [[DESTROY_ADDR]], align 4
; CHECK-NEXT:    br i1 [[COND]], label %[[IF_ELSE:.*]], label %[[IF_THEN:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    invoke void @may_throw1()
; CHECK-NEXT:            to label %[[AFTERCOROEND:.*]] unwind label %[[CATCH_DISPATCH:.*]]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    invoke void @may_throw2()
; CHECK-NEXT:            to label %[[AFTERCOROEND]] unwind label %[[CATCH_DISPATCH]]
; CHECK:       [[CATCH_DISPATCH]]:
; CHECK-NEXT:    [[VAL:%.*]] = phi i32 [ 1, %[[IF_THEN]] ], [ 2, %[[IF_ELSE]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = cleanuppad within none []
; CHECK-NEXT:    [[VAL_SPILL_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 8
; CHECK-NEXT:    store i32 [[VAL]], ptr [[VAL_SPILL_ADDR]], align 4
; CHECK-NEXT:    cleanupret from [[TMP0]] unwind label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[SWITCH:%.*]] = catchswitch within none [label %[[CATCH:.*]]] unwind to caller
; CHECK:       [[CATCH]]:
; CHECK-NEXT:    [[PAD:%.*]] = catchpad within [[SWITCH]] [ptr null, i32 64, ptr null]
; CHECK-NEXT:    catchret from [[PAD]] to label %[[COROSAVE:.*]]
; CHECK:       [[COROSAVE]]:
; CHECK-NEXT:    [[INDEX_ADDR3:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 12
; CHECK-NEXT:    store i1 false, ptr [[INDEX_ADDR3]], align 1
; CHECK-NEXT:    br i1 false, label %[[RESUME:.*]], label %[[AFTERCOROEND]]
; CHECK:       [[RESUME]]:
; CHECK-NEXT:    [[VAL_RELOAD:%.*]] = load i32, ptr [[VAL_SPILL_ADDR]], align 4
; CHECK-NEXT:    call void @print(i32 [[VAL_RELOAD]])
; CHECK-NEXT:    br label %[[AFTERCOROEND]]
; CHECK:       [[AFTERCOROEND]]:
; CHECK-NEXT:    ret void
;
entry:
  %id = call token @llvm.coro.id(i32 8, ptr null, ptr null, ptr null)
  %size = call i32 @llvm.coro.size.i32()
  %alloc = call ptr @malloc(i32 %size)
  %hdl = call ptr @llvm.coro.begin(token %id, ptr %alloc)
  br i1 %cond, label %if.else, label %if.then

if.then:
  invoke void @may_throw1()
  to label %coro.ret unwind label %catch.dispatch

if.else:
  invoke void @may_throw2()
  to label %coro.ret unwind label %catch.dispatch

catch.dispatch:                                   ; preds = %if.else, %if.then
  %val = phi i32 [ 1, %if.then ], [ 2, %if.else ]
  %switch = catchswitch within none [label %catch] unwind label %cleanuppad

; Verifies that we split out the PHI into a separate block
; added a cleanuppad spill cleanupret unwinding into the catchswitch.



catch:                                            ; preds = %catch.dispatch
  %pad = catchpad within %switch [ptr null, i32 64, ptr null]
  catchret from %pad to label %suspend

suspend:
  %sp = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %sp, label %coro.ret [
  i8 0, label %resume
  i8 1, label %coro.ret
  ]

resume:                                   ; preds = %await2.suspend
  call void @print(i32 %val)
  br label %coro.ret

coro.ret:
  call void @llvm.coro.end(ptr %hdl, i1 0, token none)
  ret void

cleanuppad:
  %cpad = cleanuppad within none []
  cleanupret from %cpad unwind to caller
}

; Function Attrs: argmemonly nounwind readonly
declare token @llvm.coro.id(i32, ptr readnone, ptr nocapture readonly, ptr) #1

; Function Attrs: nounwind
declare i1 @llvm.coro.alloc(token) #2

; Function Attrs: nobuiltin
declare i32 @llvm.coro.size.i32() #4
declare ptr @llvm.coro.begin(token, ptr writeonly) #2
declare token @llvm.coro.save(ptr)
declare i8 @llvm.coro.suspend(token, i1)

declare void @may_throw1()
declare void @may_throw2()
declare void @print(i32)
declare noalias ptr @malloc(i32)
declare void @free(ptr)

declare void @llvm.coro.end(ptr, i1, token) #2

; Function Attrs: nobuiltin nounwind

; Function Attrs: argmemonly nounwind readonly
declare ptr @llvm.coro.free(token, ptr nocapture readonly) #1
