; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --include-generated-funcs --version 6

; RUN: opt < %s -S -passes=coro-cleanup | FileCheck %s

define ptr @noop() !prof !3 {
entry:
  %n = call ptr @llvm.coro.noop()
  ret ptr %n
}

declare ptr @llvm.coro.noop()

!llvm.module.flags = !{!0, !1, !2}

!0 = !{i32 8, !"branch-target-enforcement", i32 1}
!1 = !{i32 8, !"sign-return-address", i32 1}
!2 = !{i32 8, !"sign-return-address-all", i32 1}
!3 = !{!"function_entry_count", i64 1000}
;.
; CHECK: @NoopCoro.Frame.Const = private constant %NoopCoro.Frame { ptr @__NoopCoro_ResumeDestroy, ptr @__NoopCoro_ResumeDestroy }, no_sanitize_address, no_sanitize_hwaddress
;.
; CHECK-LABEL: define ptr @noop(
; CHECK-SAME: ) !prof [[PROF3:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret ptr @NoopCoro.Frame.Const
;
;
; CHECK-LABEL: define internal void @__NoopCoro_ResumeDestroy(
; CHECK-SAME: ptr [[TMP0:%.*]]) #[[ATTR1:[0-9]+]] !prof [[PROF4:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret void
;
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { nounwind memory(none) }
; CHECK: attributes #[[ATTR1]] = { "branch-target-enforcement" "sign-return-address"="all" "sign-return-address-key"="a_key" }
;.
; CHECK: [[META0:![0-9]+]] = !{i32 8, !"branch-target-enforcement", i32 1}
; CHECK: [[META1:![0-9]+]] = !{i32 8, !"sign-return-address", i32 1}
; CHECK: [[META2:![0-9]+]] = !{i32 8, !"sign-return-address-all", i32 1}
; CHECK: [[PROF3]] = !{!"function_entry_count", i64 1000}
; CHECK: [[PROF4]] = !{!"function_entry_count", i64 0}
;.
