; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes='cgscc(coro-split)' -S | FileCheck %s

; Test that nested structs in coroutine frames have correct debug info scoping.

; Minimal nested struct types that used to trigger a scoping issue:
; we used to set the wrong `scope` for the `DIDerivedType` member entries of the `DICompositeType`
; as well as the `scope` for `DICompositeType` for the inner struct itself.
%"struct.Inner" = type { i32, ptr }
%"struct.Outer" = type { %"struct.Inner", i64 }
%"class.Promise" = type { %"struct.Outer" }

define void @test_coro_function() presplitcoroutine !dbg !10 {
; CHECK-LABEL: define void @test_coro_function(
; CHECK-SAME: ) !dbg [[DBG3:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[__PROMISE:%.*]] = alloca [[CLASS_PROMISE:%.*]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = call token @llvm.coro.id(i32 0, ptr null, ptr null, ptr null)
; CHECK-NEXT:    br label %[[ALLOCASPILLBB:.*]]
; CHECK:       [[ALLOCASPILLBB]]:
; CHECK-NEXT:      #dbg_declare(ptr null, [[META7:![0-9]+]], !DIExpression(), [[META30:![0-9]+]])
; CHECK-NEXT:    br label %[[POSTSPILL:.*]]
; CHECK:       [[POSTSPILL]]:
; CHECK-NEXT:    ret void
;
entry:
  %__promise = alloca %"class.Promise", align 8
  %0 = call token @llvm.coro.id(i32 0, ptr %__promise, ptr null, ptr null)
  %1 = call ptr @llvm.coro.begin(token %0, ptr null)
  %2 = call token @llvm.coro.save(ptr null)
  ret void
}


; Check that frame debug info is generated
; Key validation: Check that nested structs have the correct scope hierarchy
; 1. Promise should be scoped to the frame
; 2. Members of Promise should be scoped to Promise (check this before Outer since it comes first in output)
; 3. Outer should be scoped to Promise (not the frame!)
; 4. First Outer member should be scoped to Outer
; 5. Inner should be scoped to Outer (proper nesting)
; 6. Members of Inner should be scoped to Inner
; 7. Second Outer member comes after Inner (due to output order)

declare token @llvm.coro.id(i32, ptr readnone, ptr readonly, ptr)
declare ptr @llvm.coro.begin(token, ptr writeonly)
declare token @llvm.coro.save(ptr)

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!9}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
!1 = !DIFile(filename: "test.cpp", directory: ".")
!9 = !{i32 2, !"Debug Info Version", i32 3}
!10 = distinct !DISubprogram(name: "test_coro_function", scope: !1, file: !1, line: 1, type: !11, spFlags: DISPFlagDefinition, unit: !0)
!11 = !DISubroutineType(types: !12)
!12 = !{null}
;.
; CHECK: [[META0:![0-9]+]] = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: [[META1:![0-9]+]], producer: "clang", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
; CHECK: [[META1]] = !DIFile(filename: "{{.*}}test.cpp", directory: {{.*}})
; CHECK: [[DBG3]] = distinct !DISubprogram(name: "test_coro_function", scope: [[META1]], file: [[META1]], line: 1, type: [[META4:![0-9]+]], spFlags: DISPFlagDefinition, unit: [[META0]], retainedNodes: [[META6:![0-9]+]])
; CHECK: [[META4]] = !DISubroutineType(types: [[META5:![0-9]+]])
; CHECK: [[META5]] = !{null}
; CHECK: [[META6]] = !{[[META7]]}
; CHECK: [[META7]] = !DILocalVariable(name: "__coro_frame", scope: [[DBG3]], file: [[META1]], line: 1, type: [[META8:![0-9]+]], flags: DIFlagArtificial)
; CHECK: [[META8]] = !DICompositeType(tag: DW_TAG_structure_type, name: "test_coro_function.coro_frame_ty", file: [[META1]], line: 1, size: 384, align: 64, flags: DIFlagArtificial, elements: [[META9:![0-9]+]])
; CHECK: [[META9]] = !{[[META10:![0-9]+]], [[META12:![0-9]+]], [[META13:![0-9]+]], [[META28:![0-9]+]]}
; CHECK: [[META10]] = !DIDerivedType(tag: DW_TAG_member, name: "__resume_fn", scope: [[META8]], file: [[META1]], line: 1, baseType: [[META11:![0-9]+]], size: 64, align: 64, flags: DIFlagArtificial)
; CHECK: [[META11]] = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: null, size: 64)
; CHECK: [[META12]] = !DIDerivedType(tag: DW_TAG_member, name: "__destroy_fn", scope: [[META8]], file: [[META1]], line: 1, baseType: [[META11]], size: 64, align: 64, offset: 64, flags: DIFlagArtificial)
; CHECK: [[META13]] = !DIDerivedType(tag: DW_TAG_member, name: "class_Promise_0", scope: [[META8]], file: [[META1]], line: 1, baseType: [[META14:![0-9]+]], size: 192, align: 64, offset: 128, flags: DIFlagArtificial)
; CHECK: [[META14]] = !DICompositeType(tag: DW_TAG_structure_type, name: "class_Promise", scope: [[META8]], file: [[META1]], line: 1, size: 192, align: 64, flags: DIFlagArtificial, elements: [[META15:![0-9]+]])
; CHECK: [[META15]] = !{[[META16:![0-9]+]]}
; CHECK: [[META16]] = !DIDerivedType(tag: DW_TAG_member, name: "struct_Outer", scope: [[META14]], file: [[META1]], line: 1, baseType: [[META17:![0-9]+]], size: 192, align: 64, flags: DIFlagArtificial)
; CHECK: [[META17]] = !DICompositeType(tag: DW_TAG_structure_type, name: "struct_Outer", scope: [[META14]], file: [[META1]], line: 1, size: 192, align: 64, flags: DIFlagArtificial, elements: [[META18:![0-9]+]])
; CHECK: [[META18]] = !{[[META19:![0-9]+]], [[META26:![0-9]+]]}
; CHECK: [[META19]] = !DIDerivedType(tag: DW_TAG_member, name: "struct_Inner", scope: [[META17]], file: [[META1]], line: 1, baseType: [[META20:![0-9]+]], size: 128, align: 64, flags: DIFlagArtificial)
; CHECK: [[META20]] = !DICompositeType(tag: DW_TAG_structure_type, name: "struct_Inner", scope: [[META17]], file: [[META1]], line: 1, size: 128, align: 64, flags: DIFlagArtificial, elements: [[META21:![0-9]+]])
; CHECK: [[META21]] = !{[[META22:![0-9]+]], [[META24:![0-9]+]]}
; CHECK: [[META22]] = !DIDerivedType(tag: DW_TAG_member, name: "__int_32", scope: [[META20]], file: [[META1]], line: 1, baseType: [[META23:![0-9]+]], size: 32, flags: DIFlagArtificial)
; CHECK: [[META23]] = !DIBasicType(name: "__int_32", size: 32, encoding: DW_ATE_signed, flags: DIFlagArtificial)
; CHECK: [[META24]] = !DIDerivedType(tag: DW_TAG_member, name: "PointerType", scope: [[META20]], file: [[META1]], line: 1, baseType: [[META25:![0-9]+]], size: 64, align: 64, offset: 64, flags: DIFlagArtificial)
; CHECK: [[META25]] = !DIDerivedType(tag: DW_TAG_pointer_type, name: "PointerType", baseType: null, size: 64, align: 64)
; CHECK: [[META26]] = !DIDerivedType(tag: DW_TAG_member, name: "__int_64", scope: [[META17]], file: [[META1]], line: 1, baseType: [[META27:![0-9]+]], size: 64, offset: 128, flags: DIFlagArtificial)
; CHECK: [[META27]] = !DIBasicType(name: "__int_64", size: 64, encoding: DW_ATE_signed, flags: DIFlagArtificial)
; CHECK: [[META28]] = !DIDerivedType(tag: DW_TAG_member, name: "__coro_index", scope: [[META8]], file: [[META1]], line: 1, baseType: [[META29:![0-9]+]], size: 64, align: 32, offset: 320, flags: DIFlagArtificial)
; CHECK: [[META29]] = !DIBasicType(name: "__coro_index", size: 64, encoding: DW_ATE_unsigned_char)
; CHECK: [[META30]] = !DILocation(line: 1, column: 1, scope: [[DBG3]])
;.
