; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -O0 -mtriple=mipsel-linux-gnu -global-isel -stop-after=irtranslator -verify-machineinstrs %s -o - | FileCheck %s -check-prefixes=MIPS32

@.str = private unnamed_addr constant [11 x i8] c"hello %d \0A\00"

define i32 @main() {
  ; MIPS32-LABEL: name: main
  ; MIPS32: bb.1.entry:
  ; MIPS32-NEXT:   [[GV:%[0-9]+]]:_(p0) = G_GLOBAL_VALUE @.str
  ; MIPS32-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1234567890
  ; MIPS32-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; MIPS32-NEXT:   ADJCALLSTACKDOWN 16, 0, implicit-def $sp, implicit $sp
  ; MIPS32-NEXT:   $a0 = COPY [[GV]](p0)
  ; MIPS32-NEXT:   $a1 = COPY [[C]](s32)
  ; MIPS32-NEXT:   JAL @printf, csr_o32, implicit-def $ra, implicit-def $sp, implicit $a0, implicit $a1, implicit-def $v0
  ; MIPS32-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $v0
  ; MIPS32-NEXT:   ADJCALLSTACKUP 16, 0, implicit-def $sp, implicit $sp
  ; MIPS32-NEXT:   $v0 = COPY [[C1]](s32)
  ; MIPS32-NEXT:   RetRA implicit $v0
entry:
  %call = call i32 (ptr, ...) @printf(ptr @.str, i32 signext 1234567890)
  ret i32 0
}

declare i32 @printf(ptr, ...)
