; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 5
; A two-entry PHI guarded by an *unpredictable* branch gets extra speculation
; budget equal to the target's branch-misprediction penalty, so a moderately
; sized block can be flattened into a branchless select. On AArch64 that select
; lowers to a `csel`, removing a branch the hardware cannot predict.
;
; The function below is Horner evaluation of a cubic, p(x)=((c3*x+c2)*x+c1)*x+c0,
; guarded by an unpredictable sign test:
;
;   int eval_if_positive(int x, int c0, int c1, int c2, int c3) {
;     if (__builtin_unpredictable(x > 0)) {
;       int p = c3;
;       p = p*x + c2; p = p*x + c1; p = p*x + c0;
;       return p;
;     }
;     return 0;
;   }
;
; The speculated block costs more than the default budget of 4, so without the
; misprediction bonus it stays a branch. With it (budget 4+10=14) it folds.
; RUN: opt -mtriple=aarch64 -mcpu=neoverse-v2 < %s -S -passes=simplifycfg | FileCheck --check-prefix=CHECK-NOFOLD %s
; RUN: opt -mtriple=aarch64 -mcpu=neoverse-v2 < %s -S -passes='simplifycfg<speculate-unpredictables>' | FileCheck --check-prefix=CHECK-FOLD %s

define i32 @eval_if_positive(i32 %x, i32 %c0, i32 %c1, i32 %c2, i32 %c3) {
; CHECK-NOFOLD-LABEL: define i32 @eval_if_positive(
; CHECK-NOFOLD-SAME: i32 [[X:%.*]], i32 [[C0:%.*]], i32 [[C1:%.*]], i32 [[C2:%.*]], i32 [[C3:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NOFOLD-NEXT:  [[ENTRY:.*]]:
; CHECK-NOFOLD-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[X]], 0
; CHECK-NOFOLD-NEXT:    br i1 [[CMP]], label %[[IF_THEN:.*]], label %[[RETURN:.*]], !unpredictable [[META0:![0-9]+]]
; CHECK-NOFOLD:       [[IF_THEN]]:
; CHECK-NOFOLD-NEXT:    [[MUL:%.*]] = mul nsw i32 [[C3]], [[X]]
; CHECK-NOFOLD-NEXT:    [[ADD:%.*]] = add nsw i32 [[MUL]], [[C2]]
; CHECK-NOFOLD-NEXT:    [[MUL2:%.*]] = mul nsw i32 [[ADD]], [[X]]
; CHECK-NOFOLD-NEXT:    [[ADD3:%.*]] = add nsw i32 [[MUL2]], [[C1]]
; CHECK-NOFOLD-NEXT:    [[MUL4:%.*]] = mul nsw i32 [[ADD3]], [[X]]
; CHECK-NOFOLD-NEXT:    [[ADD5:%.*]] = add nsw i32 [[MUL4]], [[C0]]
; CHECK-NOFOLD-NEXT:    br label %[[RETURN]]
; CHECK-NOFOLD:       [[RETURN]]:
; CHECK-NOFOLD-NEXT:    [[P:%.*]] = phi i32 [ [[ADD5]], %[[IF_THEN]] ], [ 0, %[[ENTRY]] ]
; CHECK-NOFOLD-NEXT:    ret i32 [[P]]
;
; CHECK-FOLD-LABEL: define i32 @eval_if_positive(
; CHECK-FOLD-SAME: i32 [[X:%.*]], i32 [[C0:%.*]], i32 [[C1:%.*]], i32 [[C2:%.*]], i32 [[C3:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-FOLD-NEXT:  [[ENTRY:.*:]]
; CHECK-FOLD-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[X]], 0
; CHECK-FOLD-NEXT:    [[MUL:%.*]] = mul nsw i32 [[C3]], [[X]]
; CHECK-FOLD-NEXT:    [[ADD:%.*]] = add nsw i32 [[MUL]], [[C2]]
; CHECK-FOLD-NEXT:    [[MUL2:%.*]] = mul nsw i32 [[ADD]], [[X]]
; CHECK-FOLD-NEXT:    [[ADD3:%.*]] = add nsw i32 [[MUL2]], [[C1]]
; CHECK-FOLD-NEXT:    [[MUL4:%.*]] = mul nsw i32 [[ADD3]], [[X]]
; CHECK-FOLD-NEXT:    [[ADD5:%.*]] = add nsw i32 [[MUL4]], [[C0]]
; CHECK-FOLD-NEXT:    [[P:%.*]] = select i1 [[CMP]], i32 [[ADD5]], i32 0, !unpredictable [[META0:![0-9]+]]
; CHECK-FOLD-NEXT:    ret i32 [[P]]
;
entry:
  %cmp = icmp sgt i32 %x, 0
  br i1 %cmp, label %if.then, label %return, !unpredictable !0

if.then:
  %mul = mul nsw i32 %c3, %x
  %add = add nsw i32 %mul, %c2
  %mul2 = mul nsw i32 %add, %x
  %add3 = add nsw i32 %mul2, %c1
  %mul4 = mul nsw i32 %add3, %x
  %add5 = add nsw i32 %mul4, %c0
  br label %return

return:
  %p = phi i32 [ %add5, %if.then ], [ 0, %entry ]
  ret i32 %p
}

!0 = !{}
