; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=mips -mattr=+msa,+fp64,+mips32r2 -relocation-model=pic < %s \
; RUN:   | FileCheck -check-prefixes=ALL,O32 %s
; RUN: llc -mtriple=mipsel -mattr=+msa,+fp64,+mips32r2 -relocation-model=pic < %s \
; RUN:   | FileCheck -check-prefixes=ALL,O32 %s
; RUN: llc -mtriple=mips64 -target-abi=n32 -mattr=+msa,+fp64 -relocation-model=pic < %s \
; RUN:   | FileCheck -check-prefixes=ALL,N32 %s
; RUN: llc -mtriple=mips64el -target-abi=n32 -mattr=+msa,+fp64 -relocation-model=pic < %s \
; RUN:   | FileCheck -check-prefixes=ALL,N32 %s
; RUN: llc -mtriple=mips64 -mattr=+msa,+fp64 -relocation-model=pic < %s \
; RUN:   | FileCheck -check-prefixes=ALL,N64 %s
; RUN: llc -mtriple=mips64el -mattr=+msa,+fp64 -relocation-model=pic < %s \
; RUN:   | FileCheck -check-prefixes=ALL,N64 %s

@v4f32 = global <4 x float> <float 0.0, float 0.0, float 0.0, float 0.0>
@v2f64 = global <2 x double> <double 0.0, double 0.0>
@i32 = global i32 0
@f32 = global float 0.0
@f64 = global double 0.0

define void @const_v4f32() nounwind {
; O32-LABEL: const_v4f32:
; O32:       # %bb.0:
; O32-NEXT:    lui $2, %hi(_gp_disp)
; O32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; O32-NEXT:    addu $1, $2, $25
; O32-NEXT:    lw $2, %got(v4f32)($1)
; O32-NEXT:    ldi.b $w0, 0
; O32-NEXT:    st.b $w0, 0($2)
; O32-NEXT:    lui $3, 16256
; O32-NEXT:    fill.w $w0, $3
; O32-NEXT:    st.w $w0, 0($2)
; O32-NEXT:    lw $3, %got($CPI0_0)($1)
; O32-NEXT:    addiu $3, $3, %lo($CPI0_0)
; O32-NEXT:    ld.w $w0, 0($3)
; O32-NEXT:    st.w $w0, 0($2)
; O32-NEXT:    lui $3, 18304
; O32-NEXT:    addiu $3, $3, 128
; O32-NEXT:    fill.w $w0, $3
; O32-NEXT:    st.w $w0, 0($2)
; O32-NEXT:    lw $3, %got($CPI0_1)($1)
; O32-NEXT:    addiu $3, $3, %lo($CPI0_1)
; O32-NEXT:    ld.w $w0, 0($3)
; O32-NEXT:    st.w $w0, 0($2)
; O32-NEXT:    lw $1, %got($CPI0_2)($1)
; O32-NEXT:    addiu $1, $1, %lo($CPI0_2)
; O32-NEXT:    ld.w $w0, 0($1)
; O32-NEXT:    jr $ra
; O32-NEXT:    st.w $w0, 0($2)
;
; N32-LABEL: const_v4f32:
; N32:       # %bb.0:
; N32-NEXT:    lui $1, %hi(%neg(%gp_rel(const_v4f32)))
; N32-NEXT:    addu $1, $1, $25
; N32-NEXT:    addiu $1, $1, %lo(%neg(%gp_rel(const_v4f32)))
; N32-NEXT:    lw $2, %got_disp(v4f32)($1)
; N32-NEXT:    ldi.b $w0, 0
; N32-NEXT:    st.b $w0, 0($2)
; N32-NEXT:    lui $3, 16256
; N32-NEXT:    fill.w $w0, $3
; N32-NEXT:    st.w $w0, 0($2)
; N32-NEXT:    lw $3, %got_page(.LCPI0_0)($1)
; N32-NEXT:    addiu $3, $3, %got_ofst(.LCPI0_0)
; N32-NEXT:    ld.w $w0, 0($3)
; N32-NEXT:    st.w $w0, 0($2)
; N32-NEXT:    lui $3, 18304
; N32-NEXT:    addiu $3, $3, 128
; N32-NEXT:    fill.w $w0, $3
; N32-NEXT:    st.w $w0, 0($2)
; N32-NEXT:    lw $3, %got_page(.LCPI0_1)($1)
; N32-NEXT:    addiu $3, $3, %got_ofst(.LCPI0_1)
; N32-NEXT:    ld.w $w0, 0($3)
; N32-NEXT:    st.w $w0, 0($2)
; N32-NEXT:    lw $1, %got_page(.LCPI0_2)($1)
; N32-NEXT:    addiu $1, $1, %got_ofst(.LCPI0_2)
; N32-NEXT:    ld.w $w0, 0($1)
; N32-NEXT:    jr $ra
; N32-NEXT:    st.w $w0, 0($2)
;
; N64-LABEL: const_v4f32:
; N64:       # %bb.0:
; N64-NEXT:    lui $1, %hi(%neg(%gp_rel(const_v4f32)))
; N64-NEXT:    daddu $1, $1, $25
; N64-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(const_v4f32)))
; N64-NEXT:    ld $2, %got_disp(v4f32)($1)
; N64-NEXT:    ldi.b $w0, 0
; N64-NEXT:    st.b $w0, 0($2)
; N64-NEXT:    lui $3, 16256
; N64-NEXT:    fill.w $w0, $3
; N64-NEXT:    st.w $w0, 0($2)
; N64-NEXT:    ld $3, %got_page(.LCPI0_0)($1)
; N64-NEXT:    daddiu $3, $3, %got_ofst(.LCPI0_0)
; N64-NEXT:    ld.w $w0, 0($3)
; N64-NEXT:    st.w $w0, 0($2)
; N64-NEXT:    lui $3, 18304
; N64-NEXT:    addiu $3, $3, 128
; N64-NEXT:    fill.w $w0, $3
; N64-NEXT:    st.w $w0, 0($2)
; N64-NEXT:    ld $3, %got_page(.LCPI0_1)($1)
; N64-NEXT:    daddiu $3, $3, %got_ofst(.LCPI0_1)
; N64-NEXT:    ld.w $w0, 0($3)
; N64-NEXT:    st.w $w0, 0($2)
; N64-NEXT:    ld $1, %got_page(.LCPI0_2)($1)
; N64-NEXT:    daddiu $1, $1, %got_ofst(.LCPI0_2)
; N64-NEXT:    ld.w $w0, 0($1)
; N64-NEXT:    jr $ra
; N64-NEXT:    st.w $w0, 0($2)

  store volatile <4 x float> <float 0.0, float 0.0, float 0.0, float 0.0>, ptr @v4f32

  store volatile <4 x float> <float 1.0, float 1.0, float 1.0, float 1.0>, ptr @v4f32

  store volatile <4 x float> <float 1.0, float 1.0, float 1.0, float 31.0>, ptr @v4f32

  store volatile <4 x float> <float 65537.0, float 65537.0, float 65537.0, float 65537.0>, ptr @v4f32

  store volatile <4 x float> <float 1.0, float 2.0, float 1.0, float 2.0>, ptr @v4f32

  store volatile <4 x float> <float 3.0, float 4.0, float 5.0, float 6.0>, ptr @v4f32

  ret void
}

define void @const_v2f64() nounwind {
; O32-LABEL: const_v2f64:
; O32:       # %bb.0:
; O32-NEXT:    lui $2, %hi(_gp_disp)
; O32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; O32-NEXT:    addu $1, $2, $25
; O32-NEXT:    lw $2, %got(v2f64)($1)
; O32-NEXT:    ldi.b $w0, 0
; O32-NEXT:    st.b $w0, 0($2)
; O32-NEXT:    lw $3, %got($CPI1_0)($1)
; O32-NEXT:    addiu $3, $3, %lo($CPI1_0)
; O32-NEXT:    ld.d $w0, 0($3)
; O32-NEXT:    st.d $w0, 0($2)
; O32-NEXT:    lw $3, %got($CPI1_1)($1)
; O32-NEXT:    addiu $3, $3, %lo($CPI1_1)
; O32-NEXT:    ld.d $w0, 0($3)
; O32-NEXT:    st.d $w0, 0($2)
; O32-NEXT:    lw $3, %got($CPI1_2)($1)
; O32-NEXT:    addiu $3, $3, %lo($CPI1_2)
; O32-NEXT:    ld.d $w0, 0($3)
; O32-NEXT:    st.d $w0, 0($2)
; O32-NEXT:    lw $3, %got($CPI1_3)($1)
; O32-NEXT:    addiu $3, $3, %lo($CPI1_3)
; O32-NEXT:    ld.d $w0, 0($3)
; O32-NEXT:    st.d $w0, 0($2)
; O32-NEXT:    lw $3, %got($CPI1_4)($1)
; O32-NEXT:    addiu $3, $3, %lo($CPI1_4)
; O32-NEXT:    ld.d $w0, 0($3)
; O32-NEXT:    st.d $w0, 0($2)
; O32-NEXT:    lw $1, %got($CPI1_5)($1)
; O32-NEXT:    addiu $1, $1, %lo($CPI1_5)
; O32-NEXT:    ld.d $w0, 0($1)
; O32-NEXT:    jr $ra
; O32-NEXT:    st.d $w0, 0($2)
;
; N32-LABEL: const_v2f64:
; N32:       # %bb.0:
; N32-NEXT:    lui $1, %hi(%neg(%gp_rel(const_v2f64)))
; N32-NEXT:    addu $1, $1, $25
; N32-NEXT:    addiu $1, $1, %lo(%neg(%gp_rel(const_v2f64)))
; N32-NEXT:    lw $2, %got_disp(v2f64)($1)
; N32-NEXT:    ldi.b $w0, 0
; N32-NEXT:    st.b $w0, 0($2)
; N32-NEXT:    lw $3, %got_page(.LCPI1_0)($1)
; N32-NEXT:    addiu $3, $3, %got_ofst(.LCPI1_0)
; N32-NEXT:    ld.d $w0, 0($3)
; N32-NEXT:    st.d $w0, 0($2)
; N32-NEXT:    lw $3, %got_page(.LCPI1_1)($1)
; N32-NEXT:    addiu $3, $3, %got_ofst(.LCPI1_1)
; N32-NEXT:    ld.d $w0, 0($3)
; N32-NEXT:    st.d $w0, 0($2)
; N32-NEXT:    lw $3, %got_page(.LCPI1_2)($1)
; N32-NEXT:    addiu $3, $3, %got_ofst(.LCPI1_2)
; N32-NEXT:    ld.d $w0, 0($3)
; N32-NEXT:    st.d $w0, 0($2)
; N32-NEXT:    lw $3, %got_page(.LCPI1_3)($1)
; N32-NEXT:    addiu $3, $3, %got_ofst(.LCPI1_3)
; N32-NEXT:    ld.d $w0, 0($3)
; N32-NEXT:    st.d $w0, 0($2)
; N32-NEXT:    lw $3, %got_page(.LCPI1_4)($1)
; N32-NEXT:    addiu $3, $3, %got_ofst(.LCPI1_4)
; N32-NEXT:    ld.d $w0, 0($3)
; N32-NEXT:    st.d $w0, 0($2)
; N32-NEXT:    lw $1, %got_page(.LCPI1_5)($1)
; N32-NEXT:    addiu $1, $1, %got_ofst(.LCPI1_5)
; N32-NEXT:    ld.d $w0, 0($1)
; N32-NEXT:    jr $ra
; N32-NEXT:    st.d $w0, 0($2)
;
; N64-LABEL: const_v2f64:
; N64:       # %bb.0:
; N64-NEXT:    lui $1, %hi(%neg(%gp_rel(const_v2f64)))
; N64-NEXT:    daddu $1, $1, $25
; N64-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(const_v2f64)))
; N64-NEXT:    ld $2, %got_disp(v2f64)($1)
; N64-NEXT:    ldi.b $w0, 0
; N64-NEXT:    st.b $w0, 0($2)
; N64-NEXT:    ld $3, %got_page(.LCPI1_0)($1)
; N64-NEXT:    daddiu $3, $3, %got_ofst(.LCPI1_0)
; N64-NEXT:    ld.d $w0, 0($3)
; N64-NEXT:    st.d $w0, 0($2)
; N64-NEXT:    ld $3, %got_page(.LCPI1_1)($1)
; N64-NEXT:    daddiu $3, $3, %got_ofst(.LCPI1_1)
; N64-NEXT:    ld.d $w0, 0($3)
; N64-NEXT:    st.d $w0, 0($2)
; N64-NEXT:    ld $3, %got_page(.LCPI1_2)($1)
; N64-NEXT:    daddiu $3, $3, %got_ofst(.LCPI1_2)
; N64-NEXT:    ld.d $w0, 0($3)
; N64-NEXT:    st.d $w0, 0($2)
; N64-NEXT:    ld $3, %got_page(.LCPI1_3)($1)
; N64-NEXT:    daddiu $3, $3, %got_ofst(.LCPI1_3)
; N64-NEXT:    ld.d $w0, 0($3)
; N64-NEXT:    st.d $w0, 0($2)
; N64-NEXT:    ld $3, %got_page(.LCPI1_4)($1)
; N64-NEXT:    daddiu $3, $3, %got_ofst(.LCPI1_4)
; N64-NEXT:    ld.d $w0, 0($3)
; N64-NEXT:    st.d $w0, 0($2)
; N64-NEXT:    ld $1, %got_page(.LCPI1_5)($1)
; N64-NEXT:    daddiu $1, $1, %got_ofst(.LCPI1_5)
; N64-NEXT:    ld.d $w0, 0($1)
; N64-NEXT:    jr $ra
; N64-NEXT:    st.d $w0, 0($2)

  store volatile <2 x double> <double 0.0, double 0.0>, ptr @v2f64

  store volatile <2 x double> <double 72340172838076673.0, double 72340172838076673.0>, ptr @v2f64

  store volatile <2 x double> <double 281479271743489.0, double 281479271743489.0>, ptr @v2f64

  store volatile <2 x double> <double 4294967297.0, double 4294967297.0>, ptr @v2f64

  store volatile <2 x double> <double 1.0, double 1.0>, ptr @v2f64

  store volatile <2 x double> <double 1.0, double 31.0>, ptr @v2f64

  store volatile <2 x double> <double 3.0, double 4.0>, ptr @v2f64

  ret void
}

define void @nonconst_v4f32() nounwind {
; O32-LABEL: nonconst_v4f32:
; O32:       # %bb.0:
; O32-NEXT:    lui $2, %hi(_gp_disp)
; O32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; O32-NEXT:    addu $1, $2, $25
; O32-NEXT:    lw $2, %got(f32)($1)
; O32-NEXT:    lwc1 $f0, 0($2)
; O32-NEXT:    splati.w $w0, $w0[0]
; O32-NEXT:    lw $1, %got(v4f32)($1)
; O32-NEXT:    jr $ra
; O32-NEXT:    st.w $w0, 0($1)
;
; N32-LABEL: nonconst_v4f32:
; N32:       # %bb.0:
; N32-NEXT:    lui $1, %hi(%neg(%gp_rel(nonconst_v4f32)))
; N32-NEXT:    addu $1, $1, $25
; N32-NEXT:    addiu $1, $1, %lo(%neg(%gp_rel(nonconst_v4f32)))
; N32-NEXT:    lw $2, %got_disp(f32)($1)
; N32-NEXT:    lwc1 $f0, 0($2)
; N32-NEXT:    splati.w $w0, $w0[0]
; N32-NEXT:    lw $1, %got_disp(v4f32)($1)
; N32-NEXT:    jr $ra
; N32-NEXT:    st.w $w0, 0($1)
;
; N64-LABEL: nonconst_v4f32:
; N64:       # %bb.0:
; N64-NEXT:    lui $1, %hi(%neg(%gp_rel(nonconst_v4f32)))
; N64-NEXT:    daddu $1, $1, $25
; N64-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(nonconst_v4f32)))
; N64-NEXT:    ld $2, %got_disp(f32)($1)
; N64-NEXT:    lwc1 $f0, 0($2)
; N64-NEXT:    splati.w $w0, $w0[0]
; N64-NEXT:    ld $1, %got_disp(v4f32)($1)
; N64-NEXT:    jr $ra
; N64-NEXT:    st.w $w0, 0($1)

  %1 = load float , ptr @f32
  %2 = insertelement <4 x float> undef, float %1, i32 0
  %3 = insertelement <4 x float> %2, float %1, i32 1
  %4 = insertelement <4 x float> %3, float %1, i32 2
  %5 = insertelement <4 x float> %4, float %1, i32 3
  store volatile <4 x float> %5, ptr @v4f32

  ret void
}

define void @nonconst_v2f64() nounwind {
; O32-LABEL: nonconst_v2f64:
; O32:       # %bb.0:
; O32-NEXT:    lui $2, %hi(_gp_disp)
; O32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; O32-NEXT:    addu $1, $2, $25
; O32-NEXT:    lw $2, %got(f64)($1)
; O32-NEXT:    ldc1 $f0, 0($2)
; O32-NEXT:    splati.d $w0, $w0[0]
; O32-NEXT:    lw $1, %got(v2f64)($1)
; O32-NEXT:    jr $ra
; O32-NEXT:    st.d $w0, 0($1)
;
; N32-LABEL: nonconst_v2f64:
; N32:       # %bb.0:
; N32-NEXT:    lui $1, %hi(%neg(%gp_rel(nonconst_v2f64)))
; N32-NEXT:    addu $1, $1, $25
; N32-NEXT:    addiu $1, $1, %lo(%neg(%gp_rel(nonconst_v2f64)))
; N32-NEXT:    lw $2, %got_disp(f64)($1)
; N32-NEXT:    ldc1 $f0, 0($2)
; N32-NEXT:    splati.d $w0, $w0[0]
; N32-NEXT:    lw $1, %got_disp(v2f64)($1)
; N32-NEXT:    jr $ra
; N32-NEXT:    st.d $w0, 0($1)
;
; N64-LABEL: nonconst_v2f64:
; N64:       # %bb.0:
; N64-NEXT:    lui $1, %hi(%neg(%gp_rel(nonconst_v2f64)))
; N64-NEXT:    daddu $1, $1, $25
; N64-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(nonconst_v2f64)))
; N64-NEXT:    ld $2, %got_disp(f64)($1)
; N64-NEXT:    ldc1 $f0, 0($2)
; N64-NEXT:    splati.d $w0, $w0[0]
; N64-NEXT:    ld $1, %got_disp(v2f64)($1)
; N64-NEXT:    jr $ra
; N64-NEXT:    st.d $w0, 0($1)

  %1 = load double , ptr @f64
  %2 = insertelement <2 x double> undef, double %1, i32 0
  %3 = insertelement <2 x double> %2, double %1, i32 1
  store volatile <2 x double> %3, ptr @v2f64

  ret void
}

define float @extract_v4f32() nounwind {
; O32-LABEL: extract_v4f32:
; O32:       # %bb.0:
; O32-NEXT:    lui $2, %hi(_gp_disp)
; O32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; O32-NEXT:    addu $1, $2, $25
; O32-NEXT:    lw $1, %got(v4f32)($1)
; O32-NEXT:    ld.w $w0, 0($1)
; O32-NEXT:    fadd.w $w0, $w0, $w0
; O32-NEXT:    jr $ra
; O32-NEXT:    splati.w $w0, $w0[1]
;
; N32-LABEL: extract_v4f32:
; N32:       # %bb.0:
; N32-NEXT:    lui $1, %hi(%neg(%gp_rel(extract_v4f32)))
; N32-NEXT:    addu $1, $1, $25
; N32-NEXT:    addiu $1, $1, %lo(%neg(%gp_rel(extract_v4f32)))
; N32-NEXT:    lw $1, %got_disp(v4f32)($1)
; N32-NEXT:    ld.w $w0, 0($1)
; N32-NEXT:    fadd.w $w0, $w0, $w0
; N32-NEXT:    jr $ra
; N32-NEXT:    splati.w $w0, $w0[1]
;
; N64-LABEL: extract_v4f32:
; N64:       # %bb.0:
; N64-NEXT:    lui $1, %hi(%neg(%gp_rel(extract_v4f32)))
; N64-NEXT:    daddu $1, $1, $25
; N64-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(extract_v4f32)))
; N64-NEXT:    ld $1, %got_disp(v4f32)($1)
; N64-NEXT:    ld.w $w0, 0($1)
; N64-NEXT:    fadd.w $w0, $w0, $w0
; N64-NEXT:    jr $ra
; N64-NEXT:    splati.w $w0, $w0[1]

  %1 = load <4 x float>, ptr @v4f32

  %2 = fadd <4 x float> %1, %1

  %3 = extractelement <4 x float> %2, i32 1
  ; Element 1 can be obtained by splatting it across the vector and extracting
  ; $w0:sub_lo

  ret float %3
}

define float @extract_v4f32_elt0() nounwind {
; O32-LABEL: extract_v4f32_elt0:
; O32:       # %bb.0:
; O32-NEXT:    lui $2, %hi(_gp_disp)
; O32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; O32-NEXT:    addu $1, $2, $25
; O32-NEXT:    lw $1, %got(v4f32)($1)
; O32-NEXT:    ld.w $w0, 0($1)
; O32-NEXT:    jr $ra
; O32-NEXT:    fadd.w $w0, $w0, $w0
;
; N32-LABEL: extract_v4f32_elt0:
; N32:       # %bb.0:
; N32-NEXT:    lui $1, %hi(%neg(%gp_rel(extract_v4f32_elt0)))
; N32-NEXT:    addu $1, $1, $25
; N32-NEXT:    addiu $1, $1, %lo(%neg(%gp_rel(extract_v4f32_elt0)))
; N32-NEXT:    lw $1, %got_disp(v4f32)($1)
; N32-NEXT:    ld.w $w0, 0($1)
; N32-NEXT:    jr $ra
; N32-NEXT:    fadd.w $w0, $w0, $w0
;
; N64-LABEL: extract_v4f32_elt0:
; N64:       # %bb.0:
; N64-NEXT:    lui $1, %hi(%neg(%gp_rel(extract_v4f32_elt0)))
; N64-NEXT:    daddu $1, $1, $25
; N64-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(extract_v4f32_elt0)))
; N64-NEXT:    ld $1, %got_disp(v4f32)($1)
; N64-NEXT:    ld.w $w0, 0($1)
; N64-NEXT:    jr $ra
; N64-NEXT:    fadd.w $w0, $w0, $w0

  %1 = load <4 x float>, ptr @v4f32

  %2 = fadd <4 x float> %1, %1

  %3 = extractelement <4 x float> %2, i32 0
  ; Element 0 can be obtained by extracting $w0:sub_lo ($f0)

  ret float %3
}

define float @extract_v4f32_elt2() nounwind {
; O32-LABEL: extract_v4f32_elt2:
; O32:       # %bb.0:
; O32-NEXT:    lui $2, %hi(_gp_disp)
; O32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; O32-NEXT:    addu $1, $2, $25
; O32-NEXT:    lw $1, %got(v4f32)($1)
; O32-NEXT:    ld.w $w0, 0($1)
; O32-NEXT:    fadd.w $w0, $w0, $w0
; O32-NEXT:    jr $ra
; O32-NEXT:    splati.w $w0, $w0[2]
;
; N32-LABEL: extract_v4f32_elt2:
; N32:       # %bb.0:
; N32-NEXT:    lui $1, %hi(%neg(%gp_rel(extract_v4f32_elt2)))
; N32-NEXT:    addu $1, $1, $25
; N32-NEXT:    addiu $1, $1, %lo(%neg(%gp_rel(extract_v4f32_elt2)))
; N32-NEXT:    lw $1, %got_disp(v4f32)($1)
; N32-NEXT:    ld.w $w0, 0($1)
; N32-NEXT:    fadd.w $w0, $w0, $w0
; N32-NEXT:    jr $ra
; N32-NEXT:    splati.w $w0, $w0[2]
;
; N64-LABEL: extract_v4f32_elt2:
; N64:       # %bb.0:
; N64-NEXT:    lui $1, %hi(%neg(%gp_rel(extract_v4f32_elt2)))
; N64-NEXT:    daddu $1, $1, $25
; N64-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(extract_v4f32_elt2)))
; N64-NEXT:    ld $1, %got_disp(v4f32)($1)
; N64-NEXT:    ld.w $w0, 0($1)
; N64-NEXT:    fadd.w $w0, $w0, $w0
; N64-NEXT:    jr $ra
; N64-NEXT:    splati.w $w0, $w0[2]

  %1 = load <4 x float>, ptr @v4f32

  %2 = fadd <4 x float> %1, %1

  %3 = extractelement <4 x float> %2, i32 2
  ; Element 2 can be obtained by splatting it across the vector and extracting
  ; $w0:sub_lo

  ret float %3
}

define float @extract_v4f32_vidx() nounwind {
; O32-LABEL: extract_v4f32_vidx:
; O32:       # %bb.0:
; O32-NEXT:    lui $2, %hi(_gp_disp)
; O32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; O32-NEXT:    addu $1, $2, $25
; O32-NEXT:    lw $2, %got(i32)($1)
; O32-NEXT:    lw $2, 0($2)
; O32-NEXT:    lw $1, %got(v4f32)($1)
; O32-NEXT:    ld.w $w0, 0($1)
; O32-NEXT:    fadd.w $w0, $w0, $w0
; O32-NEXT:    jr $ra
; O32-NEXT:    splat.w $w0, $w0[$2]
;
; N32-LABEL: extract_v4f32_vidx:
; N32:       # %bb.0:
; N32-NEXT:    lui $1, %hi(%neg(%gp_rel(extract_v4f32_vidx)))
; N32-NEXT:    addu $1, $1, $25
; N32-NEXT:    addiu $1, $1, %lo(%neg(%gp_rel(extract_v4f32_vidx)))
; N32-NEXT:    lw $2, %got_disp(i32)($1)
; N32-NEXT:    lw $2, 0($2)
; N32-NEXT:    lw $1, %got_disp(v4f32)($1)
; N32-NEXT:    ld.w $w0, 0($1)
; N32-NEXT:    fadd.w $w0, $w0, $w0
; N32-NEXT:    jr $ra
; N32-NEXT:    splat.w $w0, $w0[$2]
;
; N64-LABEL: extract_v4f32_vidx:
; N64:       # %bb.0:
; N64-NEXT:    lui $1, %hi(%neg(%gp_rel(extract_v4f32_vidx)))
; N64-NEXT:    daddu $1, $1, $25
; N64-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(extract_v4f32_vidx)))
; N64-NEXT:    ld $2, %got_disp(v4f32)($1)
; N64-NEXT:    ld.w $w0, 0($2)
; N64-NEXT:    fadd.w $w0, $w0, $w0
; N64-NEXT:    ld $1, %got_disp(i32)($1)
; N64-NEXT:    lwu $1, 0($1)
; N64-NEXT:    jr $ra
; N64-NEXT:    splat.w $w0, $w0[$1]

  %1 = load <4 x float>, ptr @v4f32

  %2 = fadd <4 x float> %1, %1

  %3 = load i32, ptr @i32

  %4 = extractelement <4 x float> %2, i32 %3

  ret float %4
}

define double @extract_v2f64() nounwind {
; O32-LABEL: extract_v2f64:
; O32:       # %bb.0:
; O32-NEXT:    lui $2, %hi(_gp_disp)
; O32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; O32-NEXT:    addu $1, $2, $25
; O32-NEXT:    lw $1, %got(v2f64)($1)
; O32-NEXT:    ld.d $w0, 0($1)
; O32-NEXT:    fadd.d $w0, $w0, $w0
; O32-NEXT:    jr $ra
; O32-NEXT:    splati.d $w0, $w0[1]
;
; N32-LABEL: extract_v2f64:
; N32:       # %bb.0:
; N32-NEXT:    lui $1, %hi(%neg(%gp_rel(extract_v2f64)))
; N32-NEXT:    addu $1, $1, $25
; N32-NEXT:    addiu $1, $1, %lo(%neg(%gp_rel(extract_v2f64)))
; N32-NEXT:    lw $1, %got_disp(v2f64)($1)
; N32-NEXT:    ld.d $w0, 0($1)
; N32-NEXT:    fadd.d $w0, $w0, $w0
; N32-NEXT:    jr $ra
; N32-NEXT:    splati.d $w0, $w0[1]
;
; N64-LABEL: extract_v2f64:
; N64:       # %bb.0:
; N64-NEXT:    lui $1, %hi(%neg(%gp_rel(extract_v2f64)))
; N64-NEXT:    daddu $1, $1, $25
; N64-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(extract_v2f64)))
; N64-NEXT:    ld $1, %got_disp(v2f64)($1)
; N64-NEXT:    ld.d $w0, 0($1)
; N64-NEXT:    fadd.d $w0, $w0, $w0
; N64-NEXT:    jr $ra
; N64-NEXT:    splati.d $w0, $w0[1]

  %1 = load <2 x double>, ptr @v2f64

  %2 = fadd <2 x double> %1, %1

  %3 = extractelement <2 x double> %2, i32 1
  ; Element 1 can be obtained by splatting it across the vector and extracting
  ; $w0:sub_64

  ret double %3
}

define double @extract_v2f64_elt0() nounwind {
; O32-LABEL: extract_v2f64_elt0:
; O32:       # %bb.0:
; O32-NEXT:    lui $2, %hi(_gp_disp)
; O32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; O32-NEXT:    addu $1, $2, $25
; O32-NEXT:    lw $1, %got(v2f64)($1)
; O32-NEXT:    ld.d $w0, 0($1)
; O32-NEXT:    jr $ra
; O32-NEXT:    fadd.d $w0, $w0, $w0
;
; N32-LABEL: extract_v2f64_elt0:
; N32:       # %bb.0:
; N32-NEXT:    lui $1, %hi(%neg(%gp_rel(extract_v2f64_elt0)))
; N32-NEXT:    addu $1, $1, $25
; N32-NEXT:    addiu $1, $1, %lo(%neg(%gp_rel(extract_v2f64_elt0)))
; N32-NEXT:    lw $1, %got_disp(v2f64)($1)
; N32-NEXT:    ld.d $w0, 0($1)
; N32-NEXT:    jr $ra
; N32-NEXT:    fadd.d $w0, $w0, $w0
;
; N64-LABEL: extract_v2f64_elt0:
; N64:       # %bb.0:
; N64-NEXT:    lui $1, %hi(%neg(%gp_rel(extract_v2f64_elt0)))
; N64-NEXT:    daddu $1, $1, $25
; N64-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(extract_v2f64_elt0)))
; N64-NEXT:    ld $1, %got_disp(v2f64)($1)
; N64-NEXT:    ld.d $w0, 0($1)
; N64-NEXT:    jr $ra
; N64-NEXT:    fadd.d $w0, $w0, $w0

  %1 = load <2 x double>, ptr @v2f64

  %2 = fadd <2 x double> %1, %1

  %3 = extractelement <2 x double> %2, i32 0
  ; Element 0 can be obtained by extracting $w0:sub_64 ($f0)

  ret double %3
}

define double @extract_v2f64_vidx() nounwind {
; O32-LABEL: extract_v2f64_vidx:
; O32:       # %bb.0:
; O32-NEXT:    lui $2, %hi(_gp_disp)
; O32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; O32-NEXT:    addu $1, $2, $25
; O32-NEXT:    lw $2, %got(i32)($1)
; O32-NEXT:    lw $2, 0($2)
; O32-NEXT:    lw $1, %got(v2f64)($1)
; O32-NEXT:    ld.d $w0, 0($1)
; O32-NEXT:    fadd.d $w0, $w0, $w0
; O32-NEXT:    jr $ra
; O32-NEXT:    splat.d $w0, $w0[$2]
;
; N32-LABEL: extract_v2f64_vidx:
; N32:       # %bb.0:
; N32-NEXT:    lui $1, %hi(%neg(%gp_rel(extract_v2f64_vidx)))
; N32-NEXT:    addu $1, $1, $25
; N32-NEXT:    addiu $1, $1, %lo(%neg(%gp_rel(extract_v2f64_vidx)))
; N32-NEXT:    lw $2, %got_disp(i32)($1)
; N32-NEXT:    lw $2, 0($2)
; N32-NEXT:    lw $1, %got_disp(v2f64)($1)
; N32-NEXT:    ld.d $w0, 0($1)
; N32-NEXT:    fadd.d $w0, $w0, $w0
; N32-NEXT:    jr $ra
; N32-NEXT:    splat.d $w0, $w0[$2]
;
; N64-LABEL: extract_v2f64_vidx:
; N64:       # %bb.0:
; N64-NEXT:    lui $1, %hi(%neg(%gp_rel(extract_v2f64_vidx)))
; N64-NEXT:    daddu $1, $1, $25
; N64-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(extract_v2f64_vidx)))
; N64-NEXT:    ld $2, %got_disp(v2f64)($1)
; N64-NEXT:    ld.d $w0, 0($2)
; N64-NEXT:    fadd.d $w0, $w0, $w0
; N64-NEXT:    ld $1, %got_disp(i32)($1)
; N64-NEXT:    lwu $1, 0($1)
; N64-NEXT:    jr $ra
; N64-NEXT:    splat.d $w0, $w0[$1]

  %1 = load <2 x double>, ptr @v2f64

  %2 = fadd <2 x double> %1, %1

  %3 = load i32, ptr @i32

  %4 = extractelement <2 x double> %2, i32 %3

  ret double %4
}

define void @insert_v4f32(float %a) nounwind {
; O32-LABEL: insert_v4f32:
; O32:       # %bb.0:
; O32-NEXT:    lui $2, %hi(_gp_disp)
; O32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; O32-NEXT:    addu $1, $2, $25
; O32-NEXT:    # kill: def $f12 killed $f12 def $w12
; O32-NEXT:    lw $1, %got(v4f32)($1)
; O32-NEXT:    ld.w $w0, 0($1)
; O32-NEXT:    insve.w $w0[1], $w12[0]
; O32-NEXT:    jr $ra
; O32-NEXT:    st.w $w0, 0($1)
;
; N32-LABEL: insert_v4f32:
; N32:       # %bb.0:
; N32-NEXT:    lui $1, %hi(%neg(%gp_rel(insert_v4f32)))
; N32-NEXT:    addu $1, $1, $25
; N32-NEXT:    addiu $1, $1, %lo(%neg(%gp_rel(insert_v4f32)))
; N32-NEXT:    # kill: def $f12 killed $f12 def $w12
; N32-NEXT:    lw $1, %got_disp(v4f32)($1)
; N32-NEXT:    ld.w $w0, 0($1)
; N32-NEXT:    insve.w $w0[1], $w12[0]
; N32-NEXT:    jr $ra
; N32-NEXT:    st.w $w0, 0($1)
;
; N64-LABEL: insert_v4f32:
; N64:       # %bb.0:
; N64-NEXT:    lui $1, %hi(%neg(%gp_rel(insert_v4f32)))
; N64-NEXT:    daddu $1, $1, $25
; N64-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(insert_v4f32)))
; N64-NEXT:    # kill: def $f12 killed $f12 def $w12
; N64-NEXT:    ld $1, %got_disp(v4f32)($1)
; N64-NEXT:    ld.w $w0, 0($1)
; N64-NEXT:    insve.w $w0[1], $w12[0]
; N64-NEXT:    jr $ra
; N64-NEXT:    st.w $w0, 0($1)

  %1 = load <4 x float>, ptr @v4f32

  %2 = insertelement <4 x float> %1, float %a, i32 1
  ; float argument passed in $f12

  store volatile <4 x float> %2, ptr @v4f32

  ret void
}

define void @insert_v2f64(double %a) nounwind {
; O32-LABEL: insert_v2f64:
; O32:       # %bb.0:
; O32-NEXT:    lui $2, %hi(_gp_disp)
; O32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; O32-NEXT:    addu $1, $2, $25
; O32-NEXT:    # kill: def $d12_64 killed $d12_64 def $w12
; O32-NEXT:    lw $1, %got(v2f64)($1)
; O32-NEXT:    ld.d $w0, 0($1)
; O32-NEXT:    insve.d $w0[1], $w12[0]
; O32-NEXT:    jr $ra
; O32-NEXT:    st.d $w0, 0($1)
;
; N32-LABEL: insert_v2f64:
; N32:       # %bb.0:
; N32-NEXT:    lui $1, %hi(%neg(%gp_rel(insert_v2f64)))
; N32-NEXT:    addu $1, $1, $25
; N32-NEXT:    addiu $1, $1, %lo(%neg(%gp_rel(insert_v2f64)))
; N32-NEXT:    # kill: def $d12_64 killed $d12_64 def $w12
; N32-NEXT:    lw $1, %got_disp(v2f64)($1)
; N32-NEXT:    ld.d $w0, 0($1)
; N32-NEXT:    insve.d $w0[1], $w12[0]
; N32-NEXT:    jr $ra
; N32-NEXT:    st.d $w0, 0($1)
;
; N64-LABEL: insert_v2f64:
; N64:       # %bb.0:
; N64-NEXT:    lui $1, %hi(%neg(%gp_rel(insert_v2f64)))
; N64-NEXT:    daddu $1, $1, $25
; N64-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(insert_v2f64)))
; N64-NEXT:    # kill: def $d12_64 killed $d12_64 def $w12
; N64-NEXT:    ld $1, %got_disp(v2f64)($1)
; N64-NEXT:    ld.d $w0, 0($1)
; N64-NEXT:    insve.d $w0[1], $w12[0]
; N64-NEXT:    jr $ra
; N64-NEXT:    st.d $w0, 0($1)

  %1 = load <2 x double>, ptr @v2f64

  %2 = insertelement <2 x double> %1, double %a, i32 1
  ; double argument passed in $f12

  store volatile <2 x double> %2, ptr @v2f64

  ret void
}

define void @insert_v4f32_vidx(float %a) nounwind {
; O32-LABEL: insert_v4f32_vidx:
; O32:       # %bb.0:
; O32-NEXT:    lui $2, %hi(_gp_disp)
; O32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; O32-NEXT:    addu $1, $2, $25
; O32-NEXT:    # kill: def $f12 killed $f12 def $w12
; O32-NEXT:    lw $2, %got(i32)($1)
; O32-NEXT:    lw $2, 0($2)
; O32-NEXT:    lw $1, %got(v4f32)($1)
; O32-NEXT:    ld.w $w0, 0($1)
; O32-NEXT:    sll $2, $2, 2
; O32-NEXT:    sld.b $w0, $w0[$2]
; O32-NEXT:    insve.w $w0[0], $w12[0]
; O32-NEXT:    neg $2, $2
; O32-NEXT:    sld.b $w0, $w0[$2]
; O32-NEXT:    jr $ra
; O32-NEXT:    st.w $w0, 0($1)
;
; N32-LABEL: insert_v4f32_vidx:
; N32:       # %bb.0:
; N32-NEXT:    lui $1, %hi(%neg(%gp_rel(insert_v4f32_vidx)))
; N32-NEXT:    addu $1, $1, $25
; N32-NEXT:    addiu $1, $1, %lo(%neg(%gp_rel(insert_v4f32_vidx)))
; N32-NEXT:    # kill: def $f12 killed $f12 def $w12
; N32-NEXT:    lw $2, %got_disp(i32)($1)
; N32-NEXT:    lw $2, 0($2)
; N32-NEXT:    lw $1, %got_disp(v4f32)($1)
; N32-NEXT:    ld.w $w0, 0($1)
; N32-NEXT:    sll $2, $2, 2
; N32-NEXT:    sld.b $w0, $w0[$2]
; N32-NEXT:    insve.w $w0[0], $w12[0]
; N32-NEXT:    neg $2, $2
; N32-NEXT:    sld.b $w0, $w0[$2]
; N32-NEXT:    jr $ra
; N32-NEXT:    st.w $w0, 0($1)
;
; N64-LABEL: insert_v4f32_vidx:
; N64:       # %bb.0:
; N64-NEXT:    lui $1, %hi(%neg(%gp_rel(insert_v4f32_vidx)))
; N64-NEXT:    daddu $1, $1, $25
; N64-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(insert_v4f32_vidx)))
; N64-NEXT:    # kill: def $f12 killed $f12 def $w12
; N64-NEXT:    ld $2, %got_disp(i32)($1)
; N64-NEXT:    lwu $2, 0($2)
; N64-NEXT:    ld $1, %got_disp(v4f32)($1)
; N64-NEXT:    ld.w $w0, 0($1)
; N64-NEXT:    dsll $2, $2, 2
; N64-NEXT:    sld.b $w0, $w0[$2]
; N64-NEXT:    insve.w $w0[0], $w12[0]
; N64-NEXT:    dneg $2, $2
; N64-NEXT:    sld.b $w0, $w0[$2]
; N64-NEXT:    jr $ra
; N64-NEXT:    st.w $w0, 0($1)

  %1 = load <4 x float>, ptr @v4f32

  %2 = load i32, ptr @i32

  %3 = insertelement <4 x float> %1, float %a, i32 %2
  ; float argument passed in $f12

  store volatile <4 x float> %3, ptr @v4f32

  ret void
}

define void @insert_v2f64_vidx(double %a) nounwind {
; O32-LABEL: insert_v2f64_vidx:
; O32:       # %bb.0:
; O32-NEXT:    lui $2, %hi(_gp_disp)
; O32-NEXT:    addiu $2, $2, %lo(_gp_disp)
; O32-NEXT:    addu $1, $2, $25
; O32-NEXT:    # kill: def $d12_64 killed $d12_64 def $w12
; O32-NEXT:    lw $2, %got(i32)($1)
; O32-NEXT:    lw $2, 0($2)
; O32-NEXT:    lw $1, %got(v2f64)($1)
; O32-NEXT:    ld.d $w0, 0($1)
; O32-NEXT:    sll $2, $2, 3
; O32-NEXT:    sld.b $w0, $w0[$2]
; O32-NEXT:    insve.d $w0[0], $w12[0]
; O32-NEXT:    neg $2, $2
; O32-NEXT:    sld.b $w0, $w0[$2]
; O32-NEXT:    jr $ra
; O32-NEXT:    st.d $w0, 0($1)
;
; N32-LABEL: insert_v2f64_vidx:
; N32:       # %bb.0:
; N32-NEXT:    lui $1, %hi(%neg(%gp_rel(insert_v2f64_vidx)))
; N32-NEXT:    addu $1, $1, $25
; N32-NEXT:    addiu $1, $1, %lo(%neg(%gp_rel(insert_v2f64_vidx)))
; N32-NEXT:    # kill: def $d12_64 killed $d12_64 def $w12
; N32-NEXT:    lw $2, %got_disp(i32)($1)
; N32-NEXT:    lw $2, 0($2)
; N32-NEXT:    lw $1, %got_disp(v2f64)($1)
; N32-NEXT:    ld.d $w0, 0($1)
; N32-NEXT:    sll $2, $2, 3
; N32-NEXT:    sld.b $w0, $w0[$2]
; N32-NEXT:    insve.d $w0[0], $w12[0]
; N32-NEXT:    neg $2, $2
; N32-NEXT:    sld.b $w0, $w0[$2]
; N32-NEXT:    jr $ra
; N32-NEXT:    st.d $w0, 0($1)
;
; N64-LABEL: insert_v2f64_vidx:
; N64:       # %bb.0:
; N64-NEXT:    lui $1, %hi(%neg(%gp_rel(insert_v2f64_vidx)))
; N64-NEXT:    daddu $1, $1, $25
; N64-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(insert_v2f64_vidx)))
; N64-NEXT:    # kill: def $d12_64 killed $d12_64 def $w12
; N64-NEXT:    ld $2, %got_disp(i32)($1)
; N64-NEXT:    lwu $2, 0($2)
; N64-NEXT:    ld $1, %got_disp(v2f64)($1)
; N64-NEXT:    ld.d $w0, 0($1)
; N64-NEXT:    dsll $2, $2, 3
; N64-NEXT:    sld.b $w0, $w0[$2]
; N64-NEXT:    insve.d $w0[0], $w12[0]
; N64-NEXT:    dneg $2, $2
; N64-NEXT:    sld.b $w0, $w0[$2]
; N64-NEXT:    jr $ra
; N64-NEXT:    st.d $w0, 0($1)

  %1 = load <2 x double>, ptr @v2f64

  %2 = load i32, ptr @i32

  %3 = insertelement <2 x double> %1, double %a, i32 %2
  ; double argument passed in $f12

  store volatile <2 x double> %3, ptr @v2f64

  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; ALL: {{.*}}
