; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=mips64 -mcpu=mips64r6 -mattr=+msa,+fp64 < %s | FileCheck %s

@v2i64 = global <2 x i64> <i64 0, i64 0>

define void @splat_edge1() nounwind {
; CHECK-LABEL: splat_edge1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lui $1, %highest(v2i64)
; CHECK-NEXT:    daddiu $1, $1, %higher(v2i64)
; CHECK-NEXT:    dsll $1, $1, 16
; CHECK-NEXT:    daddiu $1, $1, %hi(v2i64)
; CHECK-NEXT:    dsll $1, $1, 16
; CHECK-NEXT:    daddiu $1, $1, %lo(v2i64)
; CHECK-NEXT:    ori $2, $zero, 32769
; CHECK-NEXT:    daui $2, $2, 32768
; CHECK-NEXT:    dahi $2, $2, 32769
; CHECK-NEXT:    dati $2, $2, 32769
; CHECK-NEXT:    fill.d $w0, $2
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    st.d $w0, 0($1)
entry:
  store volatile <2 x i64> <i64 9223512776490647553, i64 9223512776490647553>, ptr @v2i64 ; 0x8000800080008001
  ret void
}

define void @splat_edge2() nounwind {
; CHECK-LABEL: splat_edge2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lui $1, %highest(v2i64)
; CHECK-NEXT:    daddiu $1, $1, %higher(v2i64)
; CHECK-NEXT:    dsll $1, $1, 16
; CHECK-NEXT:    daddiu $1, $1, %hi(v2i64)
; CHECK-NEXT:    dsll $1, $1, 16
; CHECK-NEXT:    daddiu $1, $1, %lo(v2i64)
; CHECK-NEXT:    ori $2, $zero, 32768
; CHECK-NEXT:    daui $2, $2, 65535
; CHECK-NEXT:    dahi $2, $2, 1
; CHECK-NEXT:    fill.d $w0, $2
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    st.d $w0, 0($1)
entry:
  store volatile <2 x i64> <i64 4294934528, i64 4294934528>, ptr @v2i64 ; 0x00000000FFFF8000
  ret void
}

define void @splat_generic() nounwind {
; CHECK-LABEL: splat_generic:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lui $1, %highest(v2i64)
; CHECK-NEXT:    daddiu $1, $1, %higher(v2i64)
; CHECK-NEXT:    dsll $1, $1, 16
; CHECK-NEXT:    daddiu $1, $1, %hi(v2i64)
; CHECK-NEXT:    dsll $1, $1, 16
; CHECK-NEXT:    daddiu $1, $1, %lo(v2i64)
; CHECK-NEXT:    ori $2, $zero, 57072
; CHECK-NEXT:    daui $2, $2, 39612
; CHECK-NEXT:    dahi $2, $2, 22137
; CHECK-NEXT:    dati $2, $2, 4660
; CHECK-NEXT:    fill.d $w0, $2
; CHECK-NEXT:    jr $ra
; CHECK-NEXT:    st.d $w0, 0($1)
entry:
  store volatile <2 x i64> <i64 1311768467463790320, i64 1311768467463790320>, ptr @v2i64 ; 0x123456789abcdef0
  ret void
}
