# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -mattr=-sign-ext -run-pass=legalizer,regbankselect,instruction-select -verify-machineinstrs %s -o - | FileCheck %s -check-prefixes=CHECK,NO-SIGNEXT
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -mattr=+sign-ext -run-pass=legalizer,regbankselect,instruction-select -verify-machineinstrs %s -o - | FileCheck %s -check-prefixes=CHECK,SIGNEXT

---
name: sext_inreg_i1_i32
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: sext_inreg_i1_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[CONST_I32_:%[0-9]+]]:i32 = CONST_I32 31, implicit-def dead $arguments
    ; CHECK-NEXT: [[SHL_I32_:%[0-9]+]]:i32 = SHL_I32 %1, [[CONST_I32_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[SHR_S_I32_:%[0-9]+]]:i32 = SHR_S_I32 [[SHL_I32_]], [[CONST_I32_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[SHR_S_I32_]], implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s32) = G_SEXT_INREG %1(s32), 1
    RETURN %1(s32), implicit-def $arguments
...
---
name: sext_inreg_i8_i32
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: sext_inreg_i8_i32
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[CONST_I32_:%[0-9]+]]:i32 = CONST_I32 24, implicit-def dead $arguments
    ; NO-SIGNEXT-NEXT: [[SHL_I32_:%[0-9]+]]:i32 = SHL_I32 %1, [[CONST_I32_]], implicit-def dead $arguments
    ; NO-SIGNEXT-NEXT: [[SHR_S_I32_:%[0-9]+]]:i32 = SHR_S_I32 [[SHL_I32_]], [[CONST_I32_]], implicit-def dead $arguments
    ; NO-SIGNEXT-NEXT: RETURN [[SHR_S_I32_]], implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: sext_inreg_i8_i32
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; SIGNEXT-NEXT: [[I32_EXTEND8_S_I32_:%[0-9]+]]:i32 = I32_EXTEND8_S_I32 [[I32_EXTEND8_S_I32_]], implicit-def dead $arguments
    ; SIGNEXT-NEXT: RETURN [[I32_EXTEND8_S_I32_]], implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s32) = G_SEXT_INREG %1(s32), 8
    RETURN %1(s32), implicit-def $arguments
...
---
name: sext_inreg_i16_i32
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: sext_inreg_i16_i32
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[CONST_I32_:%[0-9]+]]:i32 = CONST_I32 16, implicit-def dead $arguments
    ; NO-SIGNEXT-NEXT: [[SHL_I32_:%[0-9]+]]:i32 = SHL_I32 %1, [[CONST_I32_]], implicit-def dead $arguments
    ; NO-SIGNEXT-NEXT: [[SHR_S_I32_:%[0-9]+]]:i32 = SHR_S_I32 [[SHL_I32_]], [[CONST_I32_]], implicit-def dead $arguments
    ; NO-SIGNEXT-NEXT: RETURN [[SHR_S_I32_]], implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: sext_inreg_i16_i32
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; SIGNEXT-NEXT: [[I32_EXTEND16_S_I32_:%[0-9]+]]:i32 = I32_EXTEND16_S_I32 [[I32_EXTEND16_S_I32_]], implicit-def dead $arguments
    ; SIGNEXT-NEXT: RETURN [[I32_EXTEND16_S_I32_]], implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s32) = G_SEXT_INREG %1(s32), 16
    RETURN %1(s32), implicit-def $arguments
...

---
name: sext_inreg_i1_i64
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: sext_inreg_i1_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[CONST_I64_:%[0-9]+]]:i64 = CONST_I64 63, implicit-def dead $arguments
    ; CHECK-NEXT: [[SHL_I64_:%[0-9]+]]:i64 = SHL_I64 %1, [[CONST_I64_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[SHR_S_I64_:%[0-9]+]]:i64 = SHR_S_I64 [[SHL_I64_]], [[CONST_I64_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[SHR_S_I64_]], implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_SEXT_INREG %1(s64), 1
    RETURN %1(s64), implicit-def $arguments
...
---
name: sext_inreg_i8_i64
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: sext_inreg_i8_i64
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[CONST_I64_:%[0-9]+]]:i64 = CONST_I64 56, implicit-def dead $arguments
    ; NO-SIGNEXT-NEXT: [[SHL_I64_:%[0-9]+]]:i64 = SHL_I64 %1, [[CONST_I64_]], implicit-def dead $arguments
    ; NO-SIGNEXT-NEXT: [[SHR_S_I64_:%[0-9]+]]:i64 = SHR_S_I64 [[SHL_I64_]], [[CONST_I64_]], implicit-def dead $arguments
    ; NO-SIGNEXT-NEXT: RETURN [[SHR_S_I64_]], implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: sext_inreg_i8_i64
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; SIGNEXT-NEXT: [[I64_EXTEND8_S_I64_:%[0-9]+]]:i64 = I64_EXTEND8_S_I64 [[I64_EXTEND8_S_I64_]], implicit-def dead $arguments
    ; SIGNEXT-NEXT: RETURN [[I64_EXTEND8_S_I64_]], implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_SEXT_INREG %1(s64), 8
    RETURN %1(s64), implicit-def $arguments
...
---
name: sext_inreg_i16_i64
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: sext_inreg_i16_i64
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[CONST_I64_:%[0-9]+]]:i64 = CONST_I64 48, implicit-def dead $arguments
    ; NO-SIGNEXT-NEXT: [[SHL_I64_:%[0-9]+]]:i64 = SHL_I64 %1, [[CONST_I64_]], implicit-def dead $arguments
    ; NO-SIGNEXT-NEXT: [[SHR_S_I64_:%[0-9]+]]:i64 = SHR_S_I64 [[SHL_I64_]], [[CONST_I64_]], implicit-def dead $arguments
    ; NO-SIGNEXT-NEXT: RETURN [[SHR_S_I64_]], implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: sext_inreg_i16_i64
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; SIGNEXT-NEXT: [[I64_EXTEND16_S_I64_:%[0-9]+]]:i64 = I64_EXTEND16_S_I64 [[I64_EXTEND16_S_I64_]], implicit-def dead $arguments
    ; SIGNEXT-NEXT: RETURN [[I64_EXTEND16_S_I64_]], implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_SEXT_INREG %1(s64), 16
    RETURN %1(s64), implicit-def $arguments
...

---
name: sext_inreg_i32_i64
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; NO-SIGNEXT-LABEL: name: sext_inreg_i32_i64
    ; NO-SIGNEXT: liveins: $arguments
    ; NO-SIGNEXT-NEXT: {{  $}}
    ; NO-SIGNEXT-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; NO-SIGNEXT-NEXT: [[CONST_I64_:%[0-9]+]]:i64 = CONST_I64 32, implicit-def dead $arguments
    ; NO-SIGNEXT-NEXT: [[SHL_I64_:%[0-9]+]]:i64 = SHL_I64 %1, [[CONST_I64_]], implicit-def dead $arguments
    ; NO-SIGNEXT-NEXT: [[SHR_S_I64_:%[0-9]+]]:i64 = SHR_S_I64 [[SHL_I64_]], [[CONST_I64_]], implicit-def dead $arguments
    ; NO-SIGNEXT-NEXT: RETURN [[SHR_S_I64_]], implicit-def $arguments
    ;
    ; SIGNEXT-LABEL: name: sext_inreg_i32_i64
    ; SIGNEXT: liveins: $arguments
    ; SIGNEXT-NEXT: {{  $}}
    ; SIGNEXT-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; SIGNEXT-NEXT: [[I64_EXTEND32_S_I64_:%[0-9]+]]:i64 = I64_EXTEND32_S_I64 [[I64_EXTEND32_S_I64_]], implicit-def dead $arguments
    ; SIGNEXT-NEXT: RETURN [[I64_EXTEND32_S_I64_]], implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_SEXT_INREG %1(s64), 32
    RETURN %1(s64), implicit-def $arguments
...
