# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -run-pass=legalizer,regbankselect,instruction-select -verify-machineinstrs %s -o - | FileCheck %s

---
name: trunc_i32_i8
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: trunc_i32_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: RETURN [[ARGUMENT_i32_]], implicit-def $arguments
    %1:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s8) = G_TRUNC %1(s32)
    %2:i32(s32) = G_ANYEXT %0(s8)
    RETURN %2(s32), implicit-def $arguments
...
---
name: trunc_i32_i16
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: trunc_i32_i16
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: RETURN [[ARGUMENT_i32_]], implicit-def $arguments
    %1:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s16) = G_TRUNC %1(s32)
    %2:i32(s32) = G_ANYEXT %0(s16)
    RETURN %2(s32), implicit-def $arguments
...
---
name: trunc_i64_i8
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: trunc_i64_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[I32_WRAP_I64_:%[0-9]+]]:i32 = I32_WRAP_I64 [[ARGUMENT_i64_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[I32_WRAP_I64_]], implicit-def $arguments
    %1:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %0:_(s8) = G_TRUNC %1(s64)
    %2:i32(s32) = G_ANYEXT %0(s8)
    RETURN %2(s32), implicit-def $arguments
...
---
name: trunc_i64_i16
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: trunc_i64_i16
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[I32_WRAP_I64_:%[0-9]+]]:i32 = I32_WRAP_I64 [[ARGUMENT_i64_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[I32_WRAP_I64_]], implicit-def $arguments
    %1:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %0:_(s16) = G_TRUNC %1(s64)
    %2:i32(s32) = G_ANYEXT %0(s16)
    RETURN %2(s32), implicit-def $arguments
...
---
name: trunc_i64_i32
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: trunc_i64_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[I32_WRAP_I64_:%[0-9]+]]:i32 = I32_WRAP_I64 [[ARGUMENT_i64_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[I32_WRAP_I64_]], implicit-def $arguments
    %1:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %0:_(s32) = G_TRUNC %1(s64)
    RETURN %0(s32), implicit-def $arguments
...
