# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -run-pass=legalizer,regbankselect,instruction-select -verify-machineinstrs %s -o - | FileCheck %s

---
name: urem_i8
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: urem_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32 = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[CONST_I32_:%[0-9]+]]:i32 = CONST_I32 255, implicit-def dead $arguments
    ; CHECK-NEXT: [[AND_I32_:%[0-9]+]]:i32 = AND_I32 [[ARGUMENT_i32_]], [[CONST_I32_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[CONST_I32_1:%[0-9]+]]:i32 = CONST_I32 255, implicit-def dead $arguments
    ; CHECK-NEXT: [[AND_I32_1:%[0-9]+]]:i32 = AND_I32 [[ARGUMENT_i32_1]], [[CONST_I32_1]], implicit-def dead $arguments
    ; CHECK-NEXT: [[REM_U_I32_:%[0-9]+]]:i32 = REM_U_I32 [[AND_I32_]], [[AND_I32_1]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[REM_U_I32_]], implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s8) = G_TRUNC %2(s32)
    %3:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s8) = G_TRUNC %3(s32)
    %4:_(s8) = G_UREM %0, %1
    %5:i32(s32) = G_ANYEXT %4(s8)
    RETURN %5(s32), implicit-def $arguments
...
---
name: urem_i16
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: urem_i16
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32 = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[CONST_I32_:%[0-9]+]]:i32 = CONST_I32 65535, implicit-def dead $arguments
    ; CHECK-NEXT: [[AND_I32_:%[0-9]+]]:i32 = AND_I32 [[ARGUMENT_i32_]], [[CONST_I32_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[CONST_I32_1:%[0-9]+]]:i32 = CONST_I32 65535, implicit-def dead $arguments
    ; CHECK-NEXT: [[AND_I32_1:%[0-9]+]]:i32 = AND_I32 [[ARGUMENT_i32_1]], [[CONST_I32_1]], implicit-def dead $arguments
    ; CHECK-NEXT: [[REM_U_I32_:%[0-9]+]]:i32 = REM_U_I32 [[AND_I32_]], [[AND_I32_1]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[REM_U_I32_]], implicit-def $arguments
    %2:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %0:_(s16) = G_TRUNC %2(s32)
    %3:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(s16) = G_TRUNC %3(s32)
    %4:_(s16) = G_UREM %0, %1
    %5:i32(s32) = G_ANYEXT %4(s16)
    RETURN %5(s32), implicit-def $arguments
...
---
name: urem_i32
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: urem_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32 = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[REM_U_I32_:%[0-9]+]]:i32 = REM_U_I32 [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[REM_U_I32_]], implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %2:_(s32) = G_UREM %0, %1
    RETURN %2(s32), implicit-def $arguments
...
---
name: urem_i64
alignment: 1
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: urem_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i64_1:%[0-9]+]]:i64 = ARGUMENT_i64 1, implicit $arguments
    ; CHECK-NEXT: [[REM_U_I64_:%[0-9]+]]:i64 = REM_U_I64 [[ARGUMENT_i64_]], [[ARGUMENT_i64_1]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[REM_U_I64_]], implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    %2:_(s64) = G_UREM %0, %1
    RETURN %2(s64), implicit-def $arguments
...
