; REQUIRES: avr-registered-target
; Strip blank lines and inline attribute comments so the declaration
; stream is contiguous and can be checked with -NEXT: no unexpected call
; can sneak in between two checked declarations.
; RUN: opt -S -passes=declare-runtime-libcalls -mtriple=avr-none < %s | sed '/^$/d;/^; Function Attrs:/d' | FileCheck -check-prefix=CHECK %s

; CHECK: declare void @__adddf3(...) addrspace(1)
; CHECK-NEXT: declare void @__addsf3(...) addrspace(1)
; CHECK-NEXT: declare void @__addtf3(...) addrspace(1)
; CHECK-NEXT: declare void @__ashldi3(...) addrspace(1)
; CHECK-NEXT: declare void @__ashlhi3(...) addrspace(1)
; CHECK-NEXT: declare void @__ashlsi3(...) addrspace(1)
; CHECK-NEXT: declare void @__ashrdi3(...) addrspace(1)
; CHECK-NEXT: declare void @__ashrhi3(...) addrspace(1)
; CHECK-NEXT: declare void @__ashrsi3(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_compare_exchange(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_compare_exchange_1(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_compare_exchange_16(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_compare_exchange_2(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_compare_exchange_4(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_compare_exchange_8(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_exchange(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_exchange_1(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_exchange_16(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_exchange_2(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_exchange_4(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_exchange_8(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_add_1(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_add_16(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_add_2(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_add_4(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_add_8(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_and_1(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_and_16(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_and_2(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_and_4(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_and_8(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_nand_1(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_nand_16(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_nand_2(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_nand_4(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_nand_8(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_or_1(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_or_16(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_or_2(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_or_4(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_or_8(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_sub_1(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_sub_16(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_sub_2(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_sub_4(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_sub_8(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_xor_1(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_xor_16(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_xor_2(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_xor_4(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_fetch_xor_8(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_load(i16, ptr, ptr, i16) addrspace(1)
; CHECK-NEXT: declare void @__atomic_load_1(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_load_16(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_load_2(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_load_4(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_load_8(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_store(i16, ptr, ptr, i16) addrspace(1)
; CHECK-NEXT: declare void @__atomic_store_1(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_store_16(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_store_2(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_store_4(...) addrspace(1)
; CHECK-NEXT: declare void @__atomic_store_8(...) addrspace(1)
; CHECK-NEXT: declare void @__clear_cache(...) addrspace(1)
; CHECK-NEXT: declare void @__clzdi2(...) addrspace(1)
; CHECK-NEXT: declare void @__clzsi2(...) addrspace(1)
; CHECK-NEXT: declare void @__clzti2(...) addrspace(1)
; CHECK-NEXT: declare void @__divdf3(...) addrspace(1)
; CHECK-NEXT: declare void @__divdi3(...) addrspace(1)
; CHECK-NEXT: declare cc86 void @__divmodhi4(...) addrspace(1)
; CHECK-NEXT: declare cc86 void @__divmodqi4(...) addrspace(1)
; CHECK-NEXT: declare void @__divmodsi4(...) addrspace(1)
; CHECK-NEXT: declare void @__divsf3(...) addrspace(1)
; CHECK-NEXT: declare void @__divtf3(...) addrspace(1)
; CHECK-NEXT: declare void @__divti3(...) addrspace(1)
; CHECK-NEXT: declare void @__eqdf2(...) addrspace(1)
; CHECK-NEXT: declare void @__eqsf2(...) addrspace(1)
; CHECK-NEXT: declare void @__eqtf2(...) addrspace(1)
; CHECK-NEXT: declare double @__exp2_finite(double) addrspace(1)
; CHECK-NEXT: declare float @__exp2f_finite(float) addrspace(1)
; CHECK-NEXT: declare double @__exp_finite(double) addrspace(1)
; CHECK-NEXT: declare float @__expf_finite(float) addrspace(1)
; CHECK-NEXT: declare void @__extendbfsf2(...) addrspace(1)
; CHECK-NEXT: declare void @__extenddftf2(...) addrspace(1)
; CHECK-NEXT: declare void @__extendhfdf2(...) addrspace(1)
; CHECK-NEXT: declare void @__extendhfsf2(...) addrspace(1)
; CHECK-NEXT: declare void @__extendhftf2(...) addrspace(1)
; CHECK-NEXT: declare void @__extendsfdf2(...) addrspace(1)
; CHECK-NEXT: declare void @__extendsftf2(...) addrspace(1)
; CHECK-NEXT: declare void @__fixdfdi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixdfsi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixdfti(...) addrspace(1)
; CHECK-NEXT: declare void @__fixhfdi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixhfsi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixhfti(...) addrspace(1)
; CHECK-NEXT: declare void @__fixsfdi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixsfsi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixsfti(...) addrspace(1)
; CHECK-NEXT: declare void @__fixtfdi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixtfsi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixtfti(...) addrspace(1)
; CHECK-NEXT: declare void @__fixunsdfdi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixunsdfsi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixunsdfti(...) addrspace(1)
; CHECK-NEXT: declare void @__fixunshfdi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixunshfsi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixunshfti(...) addrspace(1)
; CHECK-NEXT: declare void @__fixunssfdi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixunssfsi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixunssfti(...) addrspace(1)
; CHECK-NEXT: declare void @__fixunstfdi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixunstfsi(...) addrspace(1)
; CHECK-NEXT: declare void @__fixunstfti(...) addrspace(1)
; CHECK-NEXT: declare void @__floatdibf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatdidf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatdihf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatdisf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatditf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatsidf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatsihf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatsisf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatsitf(...) addrspace(1)
; CHECK-NEXT: declare void @__floattidf(...) addrspace(1)
; CHECK-NEXT: declare void @__floattihf(...) addrspace(1)
; CHECK-NEXT: declare void @__floattisf(...) addrspace(1)
; CHECK-NEXT: declare void @__floattitf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatundibf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatundidf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatundihf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatundisf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatunditf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatunsidf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatunsihf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatunsisf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatunsitf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatuntidf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatuntihf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatuntisf(...) addrspace(1)
; CHECK-NEXT: declare void @__floatuntitf(...) addrspace(1)
; CHECK-NEXT: declare void @__gedf2(...) addrspace(1)
; CHECK-NEXT: declare void @__gesf2(...) addrspace(1)
; CHECK-NEXT: declare void @__getf2(...) addrspace(1)
; CHECK-NEXT: declare void @__gtdf2(...) addrspace(1)
; CHECK-NEXT: declare void @__gtsf2(...) addrspace(1)
; CHECK-NEXT: declare void @__gttf2(...) addrspace(1)
; CHECK-NEXT: declare void @__ledf2(...) addrspace(1)
; CHECK-NEXT: declare void @__lesf2(...) addrspace(1)
; CHECK-NEXT: declare void @__letf2(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_deoptimize(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_1(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_16(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_2(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_4(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_8(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_memmove_element_unordered_atomic_1(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_memmove_element_unordered_atomic_16(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_memmove_element_unordered_atomic_2(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_memmove_element_unordered_atomic_4(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_memmove_element_unordered_atomic_8(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_memset_element_unordered_atomic_1(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_memset_element_unordered_atomic_16(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_memset_element_unordered_atomic_2(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_memset_element_unordered_atomic_4(...) addrspace(1)
; CHECK-NEXT: declare void @__llvm_memset_element_unordered_atomic_8(...) addrspace(1)
; CHECK-NEXT: declare double @__log10_finite(double) addrspace(1)
; CHECK-NEXT: declare float @__log10f_finite(float) addrspace(1)
; CHECK-NEXT: declare double @__log2_finite(double) addrspace(1)
; CHECK-NEXT: declare float @__log2f_finite(float) addrspace(1)
; CHECK-NEXT: declare double @__log_finite(double) addrspace(1)
; CHECK-NEXT: declare float @__logf_finite(float) addrspace(1)
; CHECK-NEXT: declare void @__lshrdi3(...) addrspace(1)
; CHECK-NEXT: declare void @__lshrhi3(...) addrspace(1)
; CHECK-NEXT: declare void @__lshrsi3(...) addrspace(1)
; CHECK-NEXT: declare void @__ltdf2(...) addrspace(1)
; CHECK-NEXT: declare void @__ltsf2(...) addrspace(1)
; CHECK-NEXT: declare void @__lttf2(...) addrspace(1)
; CHECK-NEXT: declare ptr @__memcpy_chk(ptr, ptr, i16, i16) addrspace(1)
; CHECK-NEXT: declare ptr @__memmove_chk(ptr, ptr, i16, i16) addrspace(1)
; CHECK-NEXT: declare ptr @__memset_chk(ptr, i16, i16, i16) addrspace(1)
; CHECK-NEXT: declare void @__moddi3(...) addrspace(1)
; CHECK-NEXT: declare void @__modti3(...) addrspace(1)
; CHECK-NEXT: declare void @__muldf3(...) addrspace(1)
; CHECK-NEXT: declare void @__muldi3(...) addrspace(1)
; CHECK-NEXT: declare void @__mulhi3(...) addrspace(1)
; CHECK-NEXT: declare void @__mulosi4(...) addrspace(1)
; CHECK-NEXT: declare void @__mulqi3(...) addrspace(1)
; CHECK-NEXT: declare void @__mulsf3(...) addrspace(1)
; CHECK-NEXT: declare void @__mulsi3(...) addrspace(1)
; CHECK-NEXT: declare void @__multf3(...) addrspace(1)
; CHECK-NEXT: declare void @__nedf2(...) addrspace(1)
; CHECK-NEXT: declare void @__negdi2(...) addrspace(1)
; CHECK-NEXT: declare void @__negsi2(...) addrspace(1)
; CHECK-NEXT: declare void @__nesf2(...) addrspace(1)
; CHECK-NEXT: declare void @__netf2(...) addrspace(1)
; CHECK-NEXT: declare void @__popcountdi2(...) addrspace(1)
; CHECK-NEXT: declare void @__popcountsi2(...) addrspace(1)
; CHECK-NEXT: declare void @__popcountti2(...) addrspace(1)
; CHECK-NEXT: declare double @__pow_finite(double, double) addrspace(1)
; CHECK-NEXT: declare float @__powf_finite(float, float) addrspace(1)
; CHECK-NEXT: declare void @__powidf2(...) addrspace(1)
; CHECK-NEXT: declare void @__powisf2(...) addrspace(1)
; CHECK-NEXT: declare void @__powitf2(...) addrspace(1)
; CHECK-NEXT: declare void @__stack_chk_fail(...) addrspace(1)
; CHECK-NEXT: declare void @__stack_chk_guard(...) addrspace(1)
; CHECK-NEXT: declare void @__subdf3(...) addrspace(1)
; CHECK-NEXT: declare void @__subsf3(...) addrspace(1)
; CHECK-NEXT: declare void @__subtf3(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_add_1(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_add_16(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_add_2(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_add_4(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_add_8(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_and_1(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_and_16(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_and_2(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_and_4(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_and_8(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_max_1(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_max_16(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_max_2(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_max_4(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_max_8(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_min_1(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_min_16(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_min_2(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_min_4(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_min_8(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_nand_1(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_nand_16(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_nand_2(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_nand_4(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_nand_8(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_or_1(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_or_16(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_or_2(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_or_4(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_or_8(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_sub_1(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_sub_16(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_sub_2(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_sub_4(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_sub_8(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_umax_1(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_umax_16(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_umax_2(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_umax_4(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_umax_8(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_umin_1(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_umin_16(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_umin_2(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_umin_4(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_umin_8(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_xor_1(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_xor_16(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_xor_2(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_xor_4(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_fetch_and_xor_8(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_lock_test_and_set_1(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_lock_test_and_set_16(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_lock_test_and_set_2(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_lock_test_and_set_4(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_lock_test_and_set_8(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_val_compare_and_swap_1(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_val_compare_and_swap_16(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_val_compare_and_swap_2(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_val_compare_and_swap_4(...) addrspace(1)
; CHECK-NEXT: declare void @__sync_val_compare_and_swap_8(...) addrspace(1)
; CHECK-NEXT: declare void @__truncdfbf2(...) addrspace(1)
; CHECK-NEXT: declare void @__truncdfhf2(...) addrspace(1)
; CHECK-NEXT: declare void @__truncdfsf2(...) addrspace(1)
; CHECK-NEXT: declare void @__truncsfbf2(...) addrspace(1)
; CHECK-NEXT: declare void @__truncsfhf2(...) addrspace(1)
; CHECK-NEXT: declare void @__trunctfbf2(...) addrspace(1)
; CHECK-NEXT: declare void @__trunctfdf2(...) addrspace(1)
; CHECK-NEXT: declare void @__trunctfhf2(...) addrspace(1)
; CHECK-NEXT: declare void @__trunctfsf2(...) addrspace(1)
; CHECK-NEXT: declare void @__udivdi3(...) addrspace(1)
; CHECK-NEXT: declare cc86 void @__udivmodhi4(...) addrspace(1)
; CHECK-NEXT: declare cc86 void @__udivmodqi4(...) addrspace(1)
; CHECK-NEXT: declare void @__udivmodsi4(...) addrspace(1)
; CHECK-NEXT: declare void @__udivti3(...) addrspace(1)
; CHECK-NEXT: declare void @__umoddi3(...) addrspace(1)
; CHECK-NEXT: declare void @__umodti3(...) addrspace(1)
; CHECK-NEXT: declare void @__unorddf2(...) addrspace(1)
; CHECK-NEXT: declare void @__unordsf2(...) addrspace(1)
; CHECK-NEXT: declare void @__unordtf2(...) addrspace(1)
; CHECK-NEXT: declare double @acos(double) addrspace(1)
; CHECK-NEXT: declare float @acosf(float) addrspace(1)
; CHECK-NEXT: declare double @asin(double) addrspace(1)
; CHECK-NEXT: declare float @asinf(float) addrspace(1)
; CHECK-NEXT: declare double @atan(double) addrspace(1)
; CHECK-NEXT: declare double @atan2(double, double) addrspace(1)
; CHECK-NEXT: declare float @atan2f(float, float) addrspace(1)
; CHECK-NEXT: declare float @atanf(float) addrspace(1)
; CHECK-NEXT: declare void @cabs(...) addrspace(1)
; CHECK-NEXT: declare void @cabsf(...) addrspace(1)
; CHECK-NEXT: declare noalias noundef ptr @calloc(i16 noundef, i16 noundef) addrspace(1) [[CALLOC_ATTRS:#[0-9]+]]
; CHECK-NEXT: declare double @cbrt(double) addrspace(1)
; CHECK-NEXT: declare float @cbrtf(float) addrspace(1)
; CHECK-NEXT: declare double @ceil(double) addrspace(1)
; CHECK-NEXT: declare float @ceilf(float) addrspace(1)
; CHECK-NEXT: declare double @copysign(double, double) addrspace(1)
; CHECK-NEXT: declare float @copysignf(float, float) addrspace(1)
; CHECK-NEXT: declare float @cos(float) addrspace(1)
; CHECK-NEXT: declare double @cosh(double) addrspace(1)
; CHECK-NEXT: declare float @coshf(float) addrspace(1)
; CHECK-NEXT: declare double @exp(double) addrspace(1)
; CHECK-NEXT: declare double @exp10(double) addrspace(1)
; CHECK-NEXT: declare float @exp10f(float) addrspace(1)
; CHECK-NEXT: declare double @exp2(double) addrspace(1)
; CHECK-NEXT: declare float @exp2f(float) addrspace(1)
; CHECK-NEXT: declare float @expf(float) addrspace(1)
; CHECK-NEXT: declare double @fdim(double, double) addrspace(1)
; CHECK-NEXT: declare float @fdimf(float, float) addrspace(1)
; CHECK-NEXT: declare void @fegetenv(...) addrspace(1)
; CHECK-NEXT: declare void @fegetmode(...) addrspace(1)
; CHECK-NEXT: declare void @fesetenv(...) addrspace(1)
; CHECK-NEXT: declare void @fesetmode(...) addrspace(1)
; CHECK-NEXT: declare double @floor(double) addrspace(1)
; CHECK-NEXT: declare float @floorf(float) addrspace(1)
; CHECK-NEXT: declare void @fma(...) addrspace(1)
; CHECK-NEXT: declare void @fmaf(...) addrspace(1)
; CHECK-NEXT: declare float @fmax(float, float) addrspace(1)
; CHECK-NEXT: declare float @fmaxf(float, float) addrspace(1)
; CHECK-NEXT: declare void @fmaximum(...) addrspace(1)
; CHECK-NEXT: declare float @fmaximum_num(float, float) addrspace(1)
; CHECK-NEXT: declare float @fmaximum_numf(float, float) addrspace(1)
; CHECK-NEXT: declare void @fmaximumf(...) addrspace(1)
; CHECK-NEXT: declare float @fmin(float, float) addrspace(1)
; CHECK-NEXT: declare float @fminf(float, float) addrspace(1)
; CHECK-NEXT: declare void @fminimum(...) addrspace(1)
; CHECK-NEXT: declare float @fminimum_num(float, float) addrspace(1)
; CHECK-NEXT: declare float @fminimum_numf(float, float) addrspace(1)
; CHECK-NEXT: declare void @fminimumf(...) addrspace(1)
; CHECK-NEXT: declare double @fmod(double, double) addrspace(1)
; CHECK-NEXT: declare float @fmodf(float, float) addrspace(1)
; CHECK-NEXT: declare void @free(ptr allocptr noundef captures(none)) addrspace(1) [[FREE_ATTRS:#[0-9]+]]
; CHECK-NEXT: declare double @frexp(double, ptr) addrspace(1)
; CHECK-NEXT: declare float @frexpf(float, ptr) addrspace(1)
; CHECK-NEXT: declare double @ldexp(double, i16) addrspace(1)
; CHECK-NEXT: declare float @ldexpf(float, i16) addrspace(1)
; CHECK-NEXT: declare void @llrint(...) addrspace(1)
; CHECK-NEXT: declare void @llrintf(...) addrspace(1)
; CHECK-NEXT: declare void @llround(...) addrspace(1)
; CHECK-NEXT: declare void @llroundf(...) addrspace(1)
; CHECK-NEXT: declare double @log(double) addrspace(1)
; CHECK-NEXT: declare double @log10(double) addrspace(1)
; CHECK-NEXT: declare float @log10f(float) addrspace(1)
; CHECK-NEXT: declare double @log2(double) addrspace(1)
; CHECK-NEXT: declare float @log2f(float) addrspace(1)
; CHECK-NEXT: declare float @logf(float) addrspace(1)
; CHECK-NEXT: declare void @lrint(...) addrspace(1)
; CHECK-NEXT: declare void @lrintf(...) addrspace(1)
; CHECK-NEXT: declare void @lround(...) addrspace(1)
; CHECK-NEXT: declare void @lroundf(...) addrspace(1)
; CHECK-NEXT: declare noalias noundef ptr @malloc(i16 noundef) addrspace(1) [[MALLOC_ATTRS:#[0-9]+]]
; CHECK-NEXT: declare ptr @memcpy(ptr, ptr, i16) addrspace(1)
; CHECK-NEXT: declare ptr @memmove(ptr, ptr, i16) addrspace(1)
; CHECK-NEXT: declare ptr @memset(ptr, i16, i16) addrspace(1)
; CHECK-NEXT: declare double @modf(double, ptr) addrspace(1)
; CHECK-NEXT: declare float @modff(float, ptr) addrspace(1)
; CHECK-NEXT: declare double @nan(ptr) addrspace(1)
; CHECK-NEXT: declare float @nanf(ptr) addrspace(1)
; CHECK-NEXT: declare double @nearbyint(double) addrspace(1)
; CHECK-NEXT: declare float @nearbyintf(float) addrspace(1)
; CHECK-NEXT: declare double @nexttoward(double, double) addrspace(1)
; CHECK-NEXT: declare float @nexttowardf(float, double) addrspace(1)
; CHECK-NEXT: declare double @pow(double, double) addrspace(1)
; CHECK-NEXT: declare float @powf(float, float) addrspace(1)
; CHECK-NEXT: declare double @remainder(double, double) addrspace(1)
; CHECK-NEXT: declare float @remainderf(float, float) addrspace(1)
; CHECK-NEXT: declare double @remquo(double, double, ptr) addrspace(1)
; CHECK-NEXT: declare float @remquof(float, float, ptr) addrspace(1)
; CHECK-NEXT: declare double @rint(double) addrspace(1)
; CHECK-NEXT: declare float @rintf(float) addrspace(1)
; CHECK-NEXT: declare double @round(double) addrspace(1)
; CHECK-NEXT: declare double @roundeven(double) addrspace(1)
; CHECK-NEXT: declare float @roundevenf(float) addrspace(1)
; CHECK-NEXT: declare float @roundf(float) addrspace(1)
; CHECK-NEXT: declare double @scalbln(double, i16) addrspace(1)
; CHECK-NEXT: declare float @scalblnf(float, i16) addrspace(1)
; CHECK-NEXT: declare double @scalbn(double, i16) addrspace(1)
; CHECK-NEXT: declare float @scalbnf(float, i16) addrspace(1)
; CHECK-NEXT: declare float @sin(float) addrspace(1)
; CHECK-NEXT: declare double @sinh(double) addrspace(1)
; CHECK-NEXT: declare float @sinhf(float) addrspace(1)
; CHECK-NEXT: declare nofpclass(ninf nsub nnorm) double @sqrt(double) addrspace(1) [[SQRT_ATTRS:#[0-9]+]]
; CHECK-NEXT: declare nofpclass(ninf nsub nnorm) float @sqrtf(float) addrspace(1) [[SQRT_ATTRS:#[0-9]+]]
; CHECK-NEXT: declare double @tan(double) addrspace(1)
; CHECK-NEXT: declare float @tanf(float) addrspace(1)
; CHECK-NEXT: declare double @tanh(double) addrspace(1)
; CHECK-NEXT: declare float @tanhf(float) addrspace(1)
; CHECK-NEXT: declare double @tgamma(double) addrspace(1)
; CHECK-NEXT: declare float @tgammaf(float) addrspace(1)
; CHECK-NEXT: declare double @trunc(double) addrspace(1)
; CHECK-NEXT: declare float @truncf(float) addrspace(1)
; CHECK-NEXT: attributes [[CALLOC_ATTRS]] = { nofree nounwind willreturn allockind("alloc") allocsize(0,1) "alloc-family"="malloc" }
; CHECK-NEXT: attributes [[FREE_ATTRS]] = { nounwind willreturn allockind("free") "alloc-family"="malloc" }
; CHECK-NEXT: attributes [[MALLOC_ATTRS]] = { nofree nounwind willreturn allockind("alloc,uninitialized") allocsize(0) "alloc-family"="malloc" }
; CHECK-NEXT: attributes [[SQRT_ATTRS]] = { nocallback nofree nosync nounwind willreturn memory(errnomem: write) }
