; REQUIRES: x86-registered-target
; Strip blank lines and inline attribute comments so the declaration
; stream is contiguous and can be checked with -NEXT: no unexpected call
; can sneak in between two checked declarations.
; RUN: opt -S -passes=declare-runtime-libcalls -mtriple=x86_64-unknown-linux-gnu < %s | sed '/^$/d;/^; Function Attrs:/d' | FileCheck -check-prefix=LINUX %s
; RUN: opt -S -passes=declare-runtime-libcalls -mtriple=x86_64-unknown-freebsd < %s | sed '/^$/d;/^; Function Attrs:/d' | FileCheck -check-prefix=FREEBSD %s
; RUN: opt -S -passes=declare-runtime-libcalls -mtriple=x86_64-unknown-openbsd < %s | sed '/^$/d;/^; Function Attrs:/d' | FileCheck -check-prefix=OPENBSD %s

; LINUX: declare void @_Unwind_Resume(...)
; LINUX-NEXT: declare void @__adddf3(...)
; LINUX-NEXT: declare void @__addsf3(...)
; LINUX-NEXT: declare void @__addtf3(...)
; LINUX-NEXT: declare void @__addxf3(...)
; LINUX-NEXT: declare void @__ashldi3(...)
; LINUX-NEXT: declare void @__ashlhi3(...)
; LINUX-NEXT: declare void @__ashlsi3(...)
; LINUX-NEXT: declare void @__ashlti3(...)
; LINUX-NEXT: declare void @__ashrdi3(...)
; LINUX-NEXT: declare void @__ashrhi3(...)
; LINUX-NEXT: declare void @__ashrsi3(...)
; LINUX-NEXT: declare void @__ashrti3(...)
; LINUX-NEXT: declare void @__atomic_compare_exchange(...)
; LINUX-NEXT: declare void @__atomic_compare_exchange_1(...)
; LINUX-NEXT: declare void @__atomic_compare_exchange_16(...)
; LINUX-NEXT: declare void @__atomic_compare_exchange_2(...)
; LINUX-NEXT: declare void @__atomic_compare_exchange_4(...)
; LINUX-NEXT: declare void @__atomic_compare_exchange_8(...)
; LINUX-NEXT: declare void @__atomic_exchange(...)
; LINUX-NEXT: declare void @__atomic_exchange_1(...)
; LINUX-NEXT: declare void @__atomic_exchange_16(...)
; LINUX-NEXT: declare void @__atomic_exchange_2(...)
; LINUX-NEXT: declare void @__atomic_exchange_4(...)
; LINUX-NEXT: declare void @__atomic_exchange_8(...)
; LINUX-NEXT: declare void @__atomic_fetch_add_1(...)
; LINUX-NEXT: declare void @__atomic_fetch_add_16(...)
; LINUX-NEXT: declare void @__atomic_fetch_add_2(...)
; LINUX-NEXT: declare void @__atomic_fetch_add_4(...)
; LINUX-NEXT: declare void @__atomic_fetch_add_8(...)
; LINUX-NEXT: declare void @__atomic_fetch_and_1(...)
; LINUX-NEXT: declare void @__atomic_fetch_and_16(...)
; LINUX-NEXT: declare void @__atomic_fetch_and_2(...)
; LINUX-NEXT: declare void @__atomic_fetch_and_4(...)
; LINUX-NEXT: declare void @__atomic_fetch_and_8(...)
; LINUX-NEXT: declare void @__atomic_fetch_nand_1(...)
; LINUX-NEXT: declare void @__atomic_fetch_nand_16(...)
; LINUX-NEXT: declare void @__atomic_fetch_nand_2(...)
; LINUX-NEXT: declare void @__atomic_fetch_nand_4(...)
; LINUX-NEXT: declare void @__atomic_fetch_nand_8(...)
; LINUX-NEXT: declare void @__atomic_fetch_or_1(...)
; LINUX-NEXT: declare void @__atomic_fetch_or_16(...)
; LINUX-NEXT: declare void @__atomic_fetch_or_2(...)
; LINUX-NEXT: declare void @__atomic_fetch_or_4(...)
; LINUX-NEXT: declare void @__atomic_fetch_or_8(...)
; LINUX-NEXT: declare void @__atomic_fetch_sub_1(...)
; LINUX-NEXT: declare void @__atomic_fetch_sub_16(...)
; LINUX-NEXT: declare void @__atomic_fetch_sub_2(...)
; LINUX-NEXT: declare void @__atomic_fetch_sub_4(...)
; LINUX-NEXT: declare void @__atomic_fetch_sub_8(...)
; LINUX-NEXT: declare void @__atomic_fetch_xor_1(...)
; LINUX-NEXT: declare void @__atomic_fetch_xor_16(...)
; LINUX-NEXT: declare void @__atomic_fetch_xor_2(...)
; LINUX-NEXT: declare void @__atomic_fetch_xor_4(...)
; LINUX-NEXT: declare void @__atomic_fetch_xor_8(...)
; LINUX-NEXT: declare void @__atomic_load(i64, ptr, ptr, i32)
; LINUX-NEXT: declare void @__atomic_load_1(...)
; LINUX-NEXT: declare void @__atomic_load_16(...)
; LINUX-NEXT: declare void @__atomic_load_2(...)
; LINUX-NEXT: declare void @__atomic_load_4(...)
; LINUX-NEXT: declare void @__atomic_load_8(...)
; LINUX-NEXT: declare void @__atomic_store(i64, ptr, ptr, i32)
; LINUX-NEXT: declare void @__atomic_store_1(...)
; LINUX-NEXT: declare void @__atomic_store_16(...)
; LINUX-NEXT: declare void @__atomic_store_2(...)
; LINUX-NEXT: declare void @__atomic_store_4(...)
; LINUX-NEXT: declare void @__atomic_store_8(...)
; LINUX-NEXT: declare void @__clear_cache(...)
; LINUX-NEXT: declare void @__clzdi2(...)
; LINUX-NEXT: declare void @__clzsi2(...)
; LINUX-NEXT: declare void @__clzti2(...)
; LINUX-NEXT: declare void @__cxa_end_cleanup(...)
; LINUX-NEXT: declare void @__divdf3(...)
; LINUX-NEXT: declare void @__divhi3(...)
; LINUX-NEXT: declare void @__divqi3(...)
; LINUX-NEXT: declare void @__divsf3(...)
; LINUX-NEXT: declare void @__divsi3(...)
; LINUX-NEXT: declare void @__divtf3(...)
; LINUX-NEXT: declare void @__divti3(...)
; LINUX-NEXT: declare void @__divxf3(...)
; LINUX-NEXT: declare void @__eqdf2(...)
; LINUX-NEXT: declare void @__eqsf2(...)
; LINUX-NEXT: declare void @__eqtf2(...)
; LINUX-NEXT: declare double @__exp10f128_finite(double)
; LINUX-NEXT: declare double @__exp2_finite(double)
; LINUX-NEXT: declare double @__exp2f128_finite(double)
; LINUX-NEXT: declare float @__exp2f_finite(float)
; LINUX-NEXT: declare double @__exp2l_finite(double)
; LINUX-NEXT: declare double @__exp_finite(double)
; LINUX-NEXT: declare double @__expf128_finite(double)
; LINUX-NEXT: declare float @__expf_finite(float)
; LINUX-NEXT: declare double @__expl_finite(double)
; LINUX-NEXT: declare void @__extendbfsf2(...)
; LINUX-NEXT: declare void @__extenddftf2(...)
; LINUX-NEXT: declare void @__extendhfdf2(...)
; LINUX-NEXT: declare void @__extendhfsf2(...)
; LINUX-NEXT: declare void @__extendhftf2(...)
; LINUX-NEXT: declare void @__extendhfxf2(...)
; LINUX-NEXT: declare void @__extendsfdf2(...)
; LINUX-NEXT: declare void @__extendsftf2(...)
; LINUX-NEXT: declare void @__extendxftf2(...)
; LINUX-NEXT: declare void @__fixdfdi(...)
; LINUX-NEXT: declare void @__fixdfsi(...)
; LINUX-NEXT: declare void @__fixdfti(...)
; LINUX-NEXT: declare void @__fixhfdi(...)
; LINUX-NEXT: declare void @__fixhfsi(...)
; LINUX-NEXT: declare void @__fixhfti(...)
; LINUX-NEXT: declare void @__fixsfdi(...)
; LINUX-NEXT: declare void @__fixsfsi(...)
; LINUX-NEXT: declare void @__fixsfti(...)
; LINUX-NEXT: declare void @__fixtfdi(...)
; LINUX-NEXT: declare void @__fixtfsi(...)
; LINUX-NEXT: declare void @__fixtfti(...)
; LINUX-NEXT: declare void @__fixunsdfdi(...)
; LINUX-NEXT: declare void @__fixunsdfsi(...)
; LINUX-NEXT: declare void @__fixunsdfti(...)
; LINUX-NEXT: declare void @__fixunshfdi(...)
; LINUX-NEXT: declare void @__fixunshfsi(...)
; LINUX-NEXT: declare void @__fixunshfti(...)
; LINUX-NEXT: declare void @__fixunssfdi(...)
; LINUX-NEXT: declare void @__fixunssfsi(...)
; LINUX-NEXT: declare void @__fixunssfti(...)
; LINUX-NEXT: declare void @__fixunstfdi(...)
; LINUX-NEXT: declare void @__fixunstfsi(...)
; LINUX-NEXT: declare void @__fixunstfti(...)
; LINUX-NEXT: declare void @__fixunsxfdi(...)
; LINUX-NEXT: declare void @__fixunsxfsi(...)
; LINUX-NEXT: declare void @__fixunsxfti(...)
; LINUX-NEXT: declare void @__fixxfdi(...)
; LINUX-NEXT: declare void @__fixxfsi(...)
; LINUX-NEXT: declare void @__fixxfti(...)
; LINUX-NEXT: declare void @__floatdibf(...)
; LINUX-NEXT: declare void @__floatdidf(...)
; LINUX-NEXT: declare void @__floatdihf(...)
; LINUX-NEXT: declare void @__floatdisf(...)
; LINUX-NEXT: declare void @__floatditf(...)
; LINUX-NEXT: declare void @__floatdixf(...)
; LINUX-NEXT: declare void @__floatsidf(...)
; LINUX-NEXT: declare void @__floatsihf(...)
; LINUX-NEXT: declare void @__floatsisf(...)
; LINUX-NEXT: declare void @__floatsitf(...)
; LINUX-NEXT: declare void @__floatsixf(...)
; LINUX-NEXT: declare void @__floattidf(...)
; LINUX-NEXT: declare void @__floattihf(...)
; LINUX-NEXT: declare void @__floattisf(...)
; LINUX-NEXT: declare void @__floattitf(...)
; LINUX-NEXT: declare void @__floattixf(...)
; LINUX-NEXT: declare void @__floatundibf(...)
; LINUX-NEXT: declare void @__floatundidf(...)
; LINUX-NEXT: declare void @__floatundihf(...)
; LINUX-NEXT: declare void @__floatundisf(...)
; LINUX-NEXT: declare void @__floatunditf(...)
; LINUX-NEXT: declare void @__floatundixf(...)
; LINUX-NEXT: declare void @__floatunsidf(...)
; LINUX-NEXT: declare void @__floatunsihf(...)
; LINUX-NEXT: declare void @__floatunsisf(...)
; LINUX-NEXT: declare void @__floatunsitf(...)
; LINUX-NEXT: declare void @__floatunsixf(...)
; LINUX-NEXT: declare void @__floatuntidf(...)
; LINUX-NEXT: declare void @__floatuntihf(...)
; LINUX-NEXT: declare void @__floatuntisf(...)
; LINUX-NEXT: declare void @__floatuntitf(...)
; LINUX-NEXT: declare void @__floatuntixf(...)
; LINUX-NEXT: declare void @__gedf2(...)
; LINUX-NEXT: declare void @__gesf2(...)
; LINUX-NEXT: declare void @__getf2(...)
; LINUX-NEXT: declare void @__gtdf2(...)
; LINUX-NEXT: declare void @__gtsf2(...)
; LINUX-NEXT: declare void @__gttf2(...)
; LINUX-NEXT: declare void @__ledf2(...)
; LINUX-NEXT: declare void @__lesf2(...)
; LINUX-NEXT: declare void @__letf2(...)
; LINUX-NEXT: declare void @__llvm_deoptimize(...)
; LINUX-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_1(...)
; LINUX-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_16(...)
; LINUX-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_2(...)
; LINUX-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_4(...)
; LINUX-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_8(...)
; LINUX-NEXT: declare void @__llvm_memmove_element_unordered_atomic_1(...)
; LINUX-NEXT: declare void @__llvm_memmove_element_unordered_atomic_16(...)
; LINUX-NEXT: declare void @__llvm_memmove_element_unordered_atomic_2(...)
; LINUX-NEXT: declare void @__llvm_memmove_element_unordered_atomic_4(...)
; LINUX-NEXT: declare void @__llvm_memmove_element_unordered_atomic_8(...)
; LINUX-NEXT: declare void @__llvm_memset_element_unordered_atomic_1(...)
; LINUX-NEXT: declare void @__llvm_memset_element_unordered_atomic_16(...)
; LINUX-NEXT: declare void @__llvm_memset_element_unordered_atomic_2(...)
; LINUX-NEXT: declare void @__llvm_memset_element_unordered_atomic_4(...)
; LINUX-NEXT: declare void @__llvm_memset_element_unordered_atomic_8(...)
; LINUX-NEXT: declare double @__log10_finite(double)
; LINUX-NEXT: declare double @__log10f128_finite(double)
; LINUX-NEXT: declare float @__log10f_finite(float)
; LINUX-NEXT: declare double @__log10l_finite(double)
; LINUX-NEXT: declare double @__log2_finite(double)
; LINUX-NEXT: declare double @__log2f128_finite(double)
; LINUX-NEXT: declare float @__log2f_finite(float)
; LINUX-NEXT: declare double @__log2l_finite(double)
; LINUX-NEXT: declare double @__log_finite(double)
; LINUX-NEXT: declare double @__logf128_finite(double)
; LINUX-NEXT: declare float @__logf_finite(float)
; LINUX-NEXT: declare double @__logl_finite(double)
; LINUX-NEXT: declare void @__lshrdi3(...)
; LINUX-NEXT: declare void @__lshrhi3(...)
; LINUX-NEXT: declare void @__lshrsi3(...)
; LINUX-NEXT: declare void @__lshrti3(...)
; LINUX-NEXT: declare void @__ltdf2(...)
; LINUX-NEXT: declare void @__ltsf2(...)
; LINUX-NEXT: declare void @__lttf2(...)
; LINUX-NEXT: declare ptr @__memcpy_chk(ptr, ptr, i64, i64)
; LINUX-NEXT: declare ptr @__memmove_chk(ptr, ptr, i64, i64)
; LINUX-NEXT: declare ptr @__memset_chk(ptr, i32, i64, i64)
; LINUX-NEXT: declare void @__modhi3(...)
; LINUX-NEXT: declare void @__modqi3(...)
; LINUX-NEXT: declare void @__modsi3(...)
; LINUX-NEXT: declare void @__modti3(...)
; LINUX-NEXT: declare void @__muldf3(...)
; LINUX-NEXT: declare void @__mulhi3(...)
; LINUX-NEXT: declare void @__mulosi4(...)
; LINUX-NEXT: declare void @__mulqi3(...)
; LINUX-NEXT: declare void @__mulsf3(...)
; LINUX-NEXT: declare void @__mulsi3(...)
; LINUX-NEXT: declare void @__multf3(...)
; LINUX-NEXT: declare void @__multi3(...)
; LINUX-NEXT: declare void @__mulxf3(...)
; LINUX-NEXT: declare void @__nedf2(...)
; LINUX-NEXT: declare void @__negdi2(...)
; LINUX-NEXT: declare void @__negsi2(...)
; LINUX-NEXT: declare void @__nesf2(...)
; LINUX-NEXT: declare void @__netf2(...)
; LINUX-NEXT: declare void @__popcountdi2(...)
; LINUX-NEXT: declare void @__popcountsi2(...)
; LINUX-NEXT: declare void @__popcountti2(...)
; LINUX-NEXT: declare double @__pow_finite(double, double)
; LINUX-NEXT: declare double @__powf128_finite(double, double)
; LINUX-NEXT: declare float @__powf_finite(float, float)
; LINUX-NEXT: declare void @__powidf2(...)
; LINUX-NEXT: declare void @__powisf2(...)
; LINUX-NEXT: declare void @__powitf2(...)
; LINUX-NEXT: declare void @__powixf2(...)
; LINUX-NEXT: declare double @__powl_finite(double, double)
; LINUX-NEXT: declare void @__safestack_unsafe_stack_ptr(...)
; LINUX-NEXT: declare void @__stack_chk_fail(...)
; LINUX-NEXT: declare void @__stack_chk_guard(...)
; LINUX-NEXT: declare void @__subdf3(...)
; LINUX-NEXT: declare void @__subsf3(...)
; LINUX-NEXT: declare void @__subtf3(...)
; LINUX-NEXT: declare void @__subxf3(...)
; LINUX-NEXT: declare void @__sync_fetch_and_add_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_add_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_add_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_add_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_add_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_and_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_and_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_and_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_and_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_and_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_max_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_max_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_max_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_max_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_max_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_min_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_min_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_min_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_min_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_min_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_nand_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_nand_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_nand_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_nand_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_nand_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_or_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_or_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_or_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_or_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_or_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_sub_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_sub_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_sub_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_sub_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_sub_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umax_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umax_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umax_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umax_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umax_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umin_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umin_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umin_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umin_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umin_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_xor_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_xor_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_xor_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_xor_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_xor_8(...)
; LINUX-NEXT: declare void @__sync_lock_test_and_set_1(...)
; LINUX-NEXT: declare void @__sync_lock_test_and_set_16(...)
; LINUX-NEXT: declare void @__sync_lock_test_and_set_2(...)
; LINUX-NEXT: declare void @__sync_lock_test_and_set_4(...)
; LINUX-NEXT: declare void @__sync_lock_test_and_set_8(...)
; LINUX-NEXT: declare void @__sync_val_compare_and_swap_1(...)
; LINUX-NEXT: declare void @__sync_val_compare_and_swap_16(...)
; LINUX-NEXT: declare void @__sync_val_compare_and_swap_2(...)
; LINUX-NEXT: declare void @__sync_val_compare_and_swap_4(...)
; LINUX-NEXT: declare void @__sync_val_compare_and_swap_8(...)
; LINUX-NEXT: declare void @__truncdfbf2(...)
; LINUX-NEXT: declare void @__truncdfhf2(...)
; LINUX-NEXT: declare void @__truncdfsf2(...)
; LINUX-NEXT: declare void @__truncsfbf2(...)
; LINUX-NEXT: declare void @__truncsfhf2(...)
; LINUX-NEXT: declare void @__trunctfbf2(...)
; LINUX-NEXT: declare void @__trunctfdf2(...)
; LINUX-NEXT: declare void @__trunctfhf2(...)
; LINUX-NEXT: declare void @__trunctfsf2(...)
; LINUX-NEXT: declare void @__trunctfxf2(...)
; LINUX-NEXT: declare void @__truncxfbf2(...)
; LINUX-NEXT: declare void @__truncxfdf2(...)
; LINUX-NEXT: declare void @__truncxfhf2(...)
; LINUX-NEXT: declare void @__truncxfsf2(...)
; LINUX-NEXT: declare void @__udivhi3(...)
; LINUX-NEXT: declare void @__udivqi3(...)
; LINUX-NEXT: declare void @__udivsi3(...)
; LINUX-NEXT: declare void @__udivti3(...)
; LINUX-NEXT: declare void @__umodhi3(...)
; LINUX-NEXT: declare void @__umodqi3(...)
; LINUX-NEXT: declare void @__umodsi3(...)
; LINUX-NEXT: declare void @__umodti3(...)
; LINUX-NEXT: declare void @__unorddf2(...)
; LINUX-NEXT: declare void @__unordsf2(...)
; LINUX-NEXT: declare void @__unordtf2(...)
; LINUX-NEXT: declare double @acos(double)
; LINUX-NEXT: declare float @acosf(float)
; LINUX-NEXT: declare double @acosf128(double)
; LINUX-NEXT: declare double @acosl(double)
; LINUX-NEXT: declare double @asin(double)
; LINUX-NEXT: declare float @asinf(float)
; LINUX-NEXT: declare double @asinf128(double)
; LINUX-NEXT: declare double @asinl(double)
; LINUX-NEXT: declare double @atan(double)
; LINUX-NEXT: declare double @atan2(double, double)
; LINUX-NEXT: declare float @atan2f(float, float)
; LINUX-NEXT: declare double @atan2f128(double, double)
; LINUX-NEXT: declare double @atan2l(double, double)
; LINUX-NEXT: declare float @atanf(float)
; LINUX-NEXT: declare double @atanf128(double)
; LINUX-NEXT: declare double @atanl(double)
; LINUX-NEXT: declare void @cabs(...)
; LINUX-NEXT: declare void @cabsf(...)
; LINUX-NEXT: declare void @cabsl(...)
; LINUX-NEXT: declare noalias noundef ptr @calloc(i64 noundef, i64 noundef) [[CALLOC_ATTRS:#[0-9]+]]
; LINUX-NEXT: declare double @cbrt(double)
; LINUX-NEXT: declare float @cbrtf(float)
; LINUX-NEXT: declare double @cbrtf128(double)
; LINUX-NEXT: declare double @cbrtl(double)
; LINUX-NEXT: declare double @ceil(double)
; LINUX-NEXT: declare float @ceilf(float)
; LINUX-NEXT: declare double @ceilf128(double)
; LINUX-NEXT: declare double @ceill(double)
; LINUX-NEXT: declare double @copysign(double, double)
; LINUX-NEXT: declare float @copysignf(float, float)
; LINUX-NEXT: declare double @copysignf128(double, double)
; LINUX-NEXT: declare double @copysignl(double, double)
; LINUX-NEXT: declare double @cos(double)
; LINUX-NEXT: declare float @cosf(float)
; LINUX-NEXT: declare double @cosf128(double)
; LINUX-NEXT: declare double @cosh(double)
; LINUX-NEXT: declare float @coshf(float)
; LINUX-NEXT: declare double @coshf128(double)
; LINUX-NEXT: declare double @coshl(double)
; LINUX-NEXT: declare double @cosl(double)
; LINUX-NEXT: declare double @exp(double)
; LINUX-NEXT: declare double @exp10(double)
; LINUX-NEXT: declare float @exp10f(float)
; LINUX-NEXT: declare double @exp10f128(double)
; LINUX-NEXT: declare double @exp10l(double)
; LINUX-NEXT: declare double @exp2(double)
; LINUX-NEXT: declare float @exp2f(float)
; LINUX-NEXT: declare double @exp2f128(double)
; LINUX-NEXT: declare double @exp2l(double)
; LINUX-NEXT: declare float @expf(float)
; LINUX-NEXT: declare double @expf128(double)
; LINUX-NEXT: declare double @expl(double)
; LINUX-NEXT: declare double @fdim(double, double)
; LINUX-NEXT: declare float @fdimf(float, float)
; LINUX-NEXT: declare double @fdiml(double, double)
; LINUX-NEXT: declare void @fegetenv(...)
; LINUX-NEXT: declare void @fegetmode(...)
; LINUX-NEXT: declare void @fesetenv(...)
; LINUX-NEXT: declare void @fesetmode(...)
; LINUX-NEXT: declare double @floor(double)
; LINUX-NEXT: declare float @floorf(float)
; LINUX-NEXT: declare double @floorf128(double)
; LINUX-NEXT: declare double @floorl(double)
; LINUX-NEXT: declare void @fma(...)
; LINUX-NEXT: declare void @fmaf(...)
; LINUX-NEXT: declare void @fmaf128(...)
; LINUX-NEXT: declare void @fmal(...)
; LINUX-NEXT: declare float @fmax(float, float)
; LINUX-NEXT: declare float @fmaxf(float, float)
; LINUX-NEXT: declare float @fmaxf128(float, float)
; LINUX-NEXT: declare void @fmaximum(...)
; LINUX-NEXT: declare float @fmaximum_num(float, float)
; LINUX-NEXT: declare float @fmaximum_numf(float, float)
; LINUX-NEXT: declare float @fmaximum_numf128(float, float)
; LINUX-NEXT: declare float @fmaximum_numl(float, float)
; LINUX-NEXT: declare void @fmaximumf(...)
; LINUX-NEXT: declare void @fmaximumf128(...)
; LINUX-NEXT: declare void @fmaximuml(...)
; LINUX-NEXT: declare float @fmaxl(float, float)
; LINUX-NEXT: declare float @fmin(float, float)
; LINUX-NEXT: declare float @fminf(float, float)
; LINUX-NEXT: declare float @fminf128(float, float)
; LINUX-NEXT: declare void @fminimum(...)
; LINUX-NEXT: declare float @fminimum_num(float, float)
; LINUX-NEXT: declare float @fminimum_numf(float, float)
; LINUX-NEXT: declare float @fminimum_numf128(float, float)
; LINUX-NEXT: declare float @fminimum_numl(float, float)
; LINUX-NEXT: declare void @fminimumf(...)
; LINUX-NEXT: declare void @fminimumf128(...)
; LINUX-NEXT: declare void @fminimuml(...)
; LINUX-NEXT: declare float @fminl(float, float)
; LINUX-NEXT: declare double @fmod(double, double)
; LINUX-NEXT: declare float @fmodf(float, float)
; LINUX-NEXT: declare double @fmodf128(double, double)
; LINUX-NEXT: declare double @fmodl(double, double)
; LINUX-NEXT: declare void @free(ptr allocptr noundef captures(none)) [[FREE_ATTRS:#[0-9]+]]
; LINUX-NEXT: declare double @frexp(double, ptr)
; LINUX-NEXT: declare float @frexpf(float, ptr)
; LINUX-NEXT: declare double @frexpf128(double, ptr)
; LINUX-NEXT: declare double @frexpl(double, ptr)
; LINUX-NEXT: declare double @ldexp(double, i32)
; LINUX-NEXT: declare float @ldexpf(float, i32)
; LINUX-NEXT: declare double @ldexpf128(double, i32)
; LINUX-NEXT: declare double @ldexpl(double, i32)
; LINUX-NEXT: declare void @llrint(...)
; LINUX-NEXT: declare void @llrintf(...)
; LINUX-NEXT: declare void @llrintf128(...)
; LINUX-NEXT: declare void @llrintl(...)
; LINUX-NEXT: declare void @llround(...)
; LINUX-NEXT: declare void @llroundf(...)
; LINUX-NEXT: declare void @llroundf128(...)
; LINUX-NEXT: declare void @llroundl(...)
; LINUX-NEXT: declare double @log(double)
; LINUX-NEXT: declare double @log10(double)
; LINUX-NEXT: declare float @log10f(float)
; LINUX-NEXT: declare double @log10f128(double)
; LINUX-NEXT: declare double @log10l(double)
; LINUX-NEXT: declare double @log2(double)
; LINUX-NEXT: declare float @log2f(float)
; LINUX-NEXT: declare double @log2f128(double)
; LINUX-NEXT: declare double @log2l(double)
; LINUX-NEXT: declare float @logf(float)
; LINUX-NEXT: declare double @logf128(double)
; LINUX-NEXT: declare double @logl(double)
; LINUX-NEXT: declare void @lrint(...)
; LINUX-NEXT: declare void @lrintf(...)
; LINUX-NEXT: declare void @lrintf128(...)
; LINUX-NEXT: declare void @lrintl(...)
; LINUX-NEXT: declare void @lround(...)
; LINUX-NEXT: declare void @lroundf(...)
; LINUX-NEXT: declare void @lroundf128(...)
; LINUX-NEXT: declare void @lroundl(...)
; LINUX-NEXT: declare noalias noundef ptr @malloc(i64 noundef) [[MALLOC_ATTRS:#[0-9]+]]
; LINUX-NEXT: declare ptr @memcpy(ptr, ptr, i64)
; LINUX-NEXT: declare ptr @memmove(ptr, ptr, i64)
; LINUX-NEXT: declare ptr @memset(ptr, i32, i64)
; LINUX-NEXT: declare double @modf(double, ptr)
; LINUX-NEXT: declare float @modff(float, ptr)
; LINUX-NEXT: declare double @modff128(double, ptr)
; LINUX-NEXT: declare double @modfl(double, ptr)
; LINUX-NEXT: declare double @nan(ptr)
; LINUX-NEXT: declare float @nanf(ptr)
; LINUX-NEXT: declare double @nanl(ptr)
; LINUX-NEXT: declare double @nearbyint(double)
; LINUX-NEXT: declare float @nearbyintf(float)
; LINUX-NEXT: declare double @nearbyintf128(double)
; LINUX-NEXT: declare double @nearbyintl(double)
; LINUX-NEXT: declare double @nexttoward(double, double)
; LINUX-NEXT: declare float @nexttowardf(float, double)
; LINUX-NEXT: declare double @nexttowardl(double, double)
; LINUX-NEXT: declare double @pow(double, double)
; LINUX-NEXT: declare float @powf(float, float)
; LINUX-NEXT: declare double @powf128(double, double)
; LINUX-NEXT: declare double @powl(double, double)
; LINUX-NEXT: declare double @remainder(double, double)
; LINUX-NEXT: declare float @remainderf(float, float)
; LINUX-NEXT: declare double @remainderl(double, double)
; LINUX-NEXT: declare double @remquo(double, double, ptr)
; LINUX-NEXT: declare float @remquof(float, float, ptr)
; LINUX-NEXT: declare double @remquol(double, double, ptr)
; LINUX-NEXT: declare double @rint(double)
; LINUX-NEXT: declare float @rintf(float)
; LINUX-NEXT: declare double @rintf128(double)
; LINUX-NEXT: declare double @rintl(double)
; LINUX-NEXT: declare double @round(double)
; LINUX-NEXT: declare double @roundeven(double)
; LINUX-NEXT: declare float @roundevenf(float)
; LINUX-NEXT: declare double @roundevenf128(double)
; LINUX-NEXT: declare double @roundevenl(double)
; LINUX-NEXT: declare float @roundf(float)
; LINUX-NEXT: declare double @roundf128(double)
; LINUX-NEXT: declare double @roundl(double)
; LINUX-NEXT: declare double @scalbln(double, i32)
; LINUX-NEXT: declare float @scalblnf(float, i32)
; LINUX-NEXT: declare double @scalblnl(double, i32)
; LINUX-NEXT: declare double @scalbn(double, i32)
; LINUX-NEXT: declare float @scalbnf(float, i32)
; LINUX-NEXT: declare double @scalbnl(double, i32)
; LINUX-NEXT: declare double @sin(double)
; LINUX-NEXT: declare void @sincos(double, ptr, ptr)
; LINUX-NEXT: declare void @sincosf(float, ptr, ptr)
; LINUX-NEXT: declare void @sincosf128(double, ptr, ptr)
; LINUX-NEXT: declare void @sincosl(double, ptr, ptr)
; LINUX-NEXT: declare float @sinf(float)
; LINUX-NEXT: declare double @sinf128(double)
; LINUX-NEXT: declare double @sinh(double)
; LINUX-NEXT: declare float @sinhf(float)
; LINUX-NEXT: declare double @sinhf128(double)
; LINUX-NEXT: declare double @sinhl(double)
; LINUX-NEXT: declare double @sinl(double)
; LINUX-NEXT: declare nofpclass(ninf nsub nnorm) double @sqrt(double) [[SQRT_ATTRS:#[0-9]+]]
; LINUX-NEXT: declare nofpclass(ninf nsub nnorm) float @sqrtf(float) [[SQRT_ATTRS:#[0-9]+]]
; LINUX-NEXT: declare double @sqrtf128(double)
; LINUX-NEXT: declare double @sqrtl(double)
; LINUX-NEXT: declare double @tan(double)
; LINUX-NEXT: declare float @tanf(float)
; LINUX-NEXT: declare double @tanf128(double)
; LINUX-NEXT: declare double @tanh(double)
; LINUX-NEXT: declare float @tanhf(float)
; LINUX-NEXT: declare double @tanhf128(double)
; LINUX-NEXT: declare double @tanhl(double)
; LINUX-NEXT: declare double @tanl(double)
; LINUX-NEXT: declare double @tgamma(double)
; LINUX-NEXT: declare float @tgammaf(float)
; LINUX-NEXT: declare double @tgammal(double)
; LINUX-NEXT: declare double @trunc(double)
; LINUX-NEXT: declare float @truncf(float)
; LINUX-NEXT: declare double @truncf128(double)
; LINUX-NEXT: declare double @truncl(double)
; LINUX-NEXT: attributes [[CALLOC_ATTRS]] = { nofree nounwind willreturn allockind("alloc") allocsize(0,1) "alloc-family"="malloc" }
; LINUX-NEXT: attributes [[FREE_ATTRS]] = { nounwind willreturn allockind("free") "alloc-family"="malloc" }
; LINUX-NEXT: attributes [[MALLOC_ATTRS]] = { nofree nounwind willreturn allockind("alloc,uninitialized") allocsize(0) "alloc-family"="malloc" }
; LINUX-NEXT: attributes [[SQRT_ATTRS]] = { nocallback nofree nosync nounwind willreturn memory(errnomem: write) }

; FREEBSD: declare void @_Unwind_Resume(...)
; FREEBSD-NEXT: declare void @__adddf3(...)
; FREEBSD-NEXT: declare void @__addsf3(...)
; FREEBSD-NEXT: declare void @__addtf3(...)
; FREEBSD-NEXT: declare void @__addxf3(...)
; FREEBSD-NEXT: declare void @__ashldi3(...)
; FREEBSD-NEXT: declare void @__ashlhi3(...)
; FREEBSD-NEXT: declare void @__ashlsi3(...)
; FREEBSD-NEXT: declare void @__ashlti3(...)
; FREEBSD-NEXT: declare void @__ashrdi3(...)
; FREEBSD-NEXT: declare void @__ashrhi3(...)
; FREEBSD-NEXT: declare void @__ashrsi3(...)
; FREEBSD-NEXT: declare void @__ashrti3(...)
; FREEBSD-NEXT: declare void @__atomic_compare_exchange(...)
; FREEBSD-NEXT: declare void @__atomic_compare_exchange_1(...)
; FREEBSD-NEXT: declare void @__atomic_compare_exchange_16(...)
; FREEBSD-NEXT: declare void @__atomic_compare_exchange_2(...)
; FREEBSD-NEXT: declare void @__atomic_compare_exchange_4(...)
; FREEBSD-NEXT: declare void @__atomic_compare_exchange_8(...)
; FREEBSD-NEXT: declare void @__atomic_exchange(...)
; FREEBSD-NEXT: declare void @__atomic_exchange_1(...)
; FREEBSD-NEXT: declare void @__atomic_exchange_16(...)
; FREEBSD-NEXT: declare void @__atomic_exchange_2(...)
; FREEBSD-NEXT: declare void @__atomic_exchange_4(...)
; FREEBSD-NEXT: declare void @__atomic_exchange_8(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_add_1(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_add_16(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_add_2(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_add_4(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_add_8(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_and_1(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_and_16(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_and_2(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_and_4(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_and_8(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_nand_1(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_nand_16(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_nand_2(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_nand_4(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_nand_8(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_or_1(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_or_16(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_or_2(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_or_4(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_or_8(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_sub_1(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_sub_16(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_sub_2(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_sub_4(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_sub_8(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_xor_1(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_xor_16(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_xor_2(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_xor_4(...)
; FREEBSD-NEXT: declare void @__atomic_fetch_xor_8(...)
; FREEBSD-NEXT: declare void @__atomic_load(i64, ptr, ptr, i32)
; FREEBSD-NEXT: declare void @__atomic_load_1(...)
; FREEBSD-NEXT: declare void @__atomic_load_16(...)
; FREEBSD-NEXT: declare void @__atomic_load_2(...)
; FREEBSD-NEXT: declare void @__atomic_load_4(...)
; FREEBSD-NEXT: declare void @__atomic_load_8(...)
; FREEBSD-NEXT: declare void @__atomic_store(i64, ptr, ptr, i32)
; FREEBSD-NEXT: declare void @__atomic_store_1(...)
; FREEBSD-NEXT: declare void @__atomic_store_16(...)
; FREEBSD-NEXT: declare void @__atomic_store_2(...)
; FREEBSD-NEXT: declare void @__atomic_store_4(...)
; FREEBSD-NEXT: declare void @__atomic_store_8(...)
; FREEBSD-NEXT: declare void @__clear_cache(...)
; FREEBSD-NEXT: declare void @__clzdi2(...)
; FREEBSD-NEXT: declare void @__clzsi2(...)
; FREEBSD-NEXT: declare void @__clzti2(...)
; FREEBSD-NEXT: declare void @__cxa_end_cleanup(...)
; FREEBSD-NEXT: declare void @__divdf3(...)
; FREEBSD-NEXT: declare void @__divhi3(...)
; FREEBSD-NEXT: declare void @__divqi3(...)
; FREEBSD-NEXT: declare void @__divsf3(...)
; FREEBSD-NEXT: declare void @__divsi3(...)
; FREEBSD-NEXT: declare void @__divtf3(...)
; FREEBSD-NEXT: declare void @__divti3(...)
; FREEBSD-NEXT: declare void @__divxf3(...)
; FREEBSD-NEXT: declare void @__eqdf2(...)
; FREEBSD-NEXT: declare void @__eqsf2(...)
; FREEBSD-NEXT: declare void @__eqtf2(...)
; FREEBSD-NEXT: declare double @__exp2_finite(double)
; FREEBSD-NEXT: declare float @__exp2f_finite(float)
; FREEBSD-NEXT: declare double @__exp2l_finite(double)
; FREEBSD-NEXT: declare double @__exp_finite(double)
; FREEBSD-NEXT: declare float @__expf_finite(float)
; FREEBSD-NEXT: declare double @__expl_finite(double)
; FREEBSD-NEXT: declare void @__extendbfsf2(...)
; FREEBSD-NEXT: declare void @__extenddftf2(...)
; FREEBSD-NEXT: declare void @__extendhfdf2(...)
; FREEBSD-NEXT: declare void @__extendhfsf2(...)
; FREEBSD-NEXT: declare void @__extendhftf2(...)
; FREEBSD-NEXT: declare void @__extendhfxf2(...)
; FREEBSD-NEXT: declare void @__extendsfdf2(...)
; FREEBSD-NEXT: declare void @__extendsftf2(...)
; FREEBSD-NEXT: declare void @__extendxftf2(...)
; FREEBSD-NEXT: declare void @__fixdfdi(...)
; FREEBSD-NEXT: declare void @__fixdfsi(...)
; FREEBSD-NEXT: declare void @__fixdfti(...)
; FREEBSD-NEXT: declare void @__fixhfdi(...)
; FREEBSD-NEXT: declare void @__fixhfsi(...)
; FREEBSD-NEXT: declare void @__fixhfti(...)
; FREEBSD-NEXT: declare void @__fixsfdi(...)
; FREEBSD-NEXT: declare void @__fixsfsi(...)
; FREEBSD-NEXT: declare void @__fixsfti(...)
; FREEBSD-NEXT: declare void @__fixtfdi(...)
; FREEBSD-NEXT: declare void @__fixtfsi(...)
; FREEBSD-NEXT: declare void @__fixtfti(...)
; FREEBSD-NEXT: declare void @__fixunsdfdi(...)
; FREEBSD-NEXT: declare void @__fixunsdfsi(...)
; FREEBSD-NEXT: declare void @__fixunsdfti(...)
; FREEBSD-NEXT: declare void @__fixunshfdi(...)
; FREEBSD-NEXT: declare void @__fixunshfsi(...)
; FREEBSD-NEXT: declare void @__fixunshfti(...)
; FREEBSD-NEXT: declare void @__fixunssfdi(...)
; FREEBSD-NEXT: declare void @__fixunssfsi(...)
; FREEBSD-NEXT: declare void @__fixunssfti(...)
; FREEBSD-NEXT: declare void @__fixunstfdi(...)
; FREEBSD-NEXT: declare void @__fixunstfsi(...)
; FREEBSD-NEXT: declare void @__fixunstfti(...)
; FREEBSD-NEXT: declare void @__fixunsxfdi(...)
; FREEBSD-NEXT: declare void @__fixunsxfsi(...)
; FREEBSD-NEXT: declare void @__fixunsxfti(...)
; FREEBSD-NEXT: declare void @__fixxfdi(...)
; FREEBSD-NEXT: declare void @__fixxfsi(...)
; FREEBSD-NEXT: declare void @__fixxfti(...)
; FREEBSD-NEXT: declare void @__floatdibf(...)
; FREEBSD-NEXT: declare void @__floatdidf(...)
; FREEBSD-NEXT: declare void @__floatdihf(...)
; FREEBSD-NEXT: declare void @__floatdisf(...)
; FREEBSD-NEXT: declare void @__floatditf(...)
; FREEBSD-NEXT: declare void @__floatdixf(...)
; FREEBSD-NEXT: declare void @__floatsidf(...)
; FREEBSD-NEXT: declare void @__floatsihf(...)
; FREEBSD-NEXT: declare void @__floatsisf(...)
; FREEBSD-NEXT: declare void @__floatsitf(...)
; FREEBSD-NEXT: declare void @__floatsixf(...)
; FREEBSD-NEXT: declare void @__floattidf(...)
; FREEBSD-NEXT: declare void @__floattihf(...)
; FREEBSD-NEXT: declare void @__floattisf(...)
; FREEBSD-NEXT: declare void @__floattitf(...)
; FREEBSD-NEXT: declare void @__floattixf(...)
; FREEBSD-NEXT: declare void @__floatundibf(...)
; FREEBSD-NEXT: declare void @__floatundidf(...)
; FREEBSD-NEXT: declare void @__floatundihf(...)
; FREEBSD-NEXT: declare void @__floatundisf(...)
; FREEBSD-NEXT: declare void @__floatunditf(...)
; FREEBSD-NEXT: declare void @__floatundixf(...)
; FREEBSD-NEXT: declare void @__floatunsidf(...)
; FREEBSD-NEXT: declare void @__floatunsihf(...)
; FREEBSD-NEXT: declare void @__floatunsisf(...)
; FREEBSD-NEXT: declare void @__floatunsitf(...)
; FREEBSD-NEXT: declare void @__floatunsixf(...)
; FREEBSD-NEXT: declare void @__floatuntidf(...)
; FREEBSD-NEXT: declare void @__floatuntihf(...)
; FREEBSD-NEXT: declare void @__floatuntisf(...)
; FREEBSD-NEXT: declare void @__floatuntitf(...)
; FREEBSD-NEXT: declare void @__floatuntixf(...)
; FREEBSD-NEXT: declare void @__gedf2(...)
; FREEBSD-NEXT: declare void @__gesf2(...)
; FREEBSD-NEXT: declare void @__getf2(...)
; FREEBSD-NEXT: declare void @__gtdf2(...)
; FREEBSD-NEXT: declare void @__gtsf2(...)
; FREEBSD-NEXT: declare void @__gttf2(...)
; FREEBSD-NEXT: declare void @__ledf2(...)
; FREEBSD-NEXT: declare void @__lesf2(...)
; FREEBSD-NEXT: declare void @__letf2(...)
; FREEBSD-NEXT: declare void @__llvm_deoptimize(...)
; FREEBSD-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_1(...)
; FREEBSD-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_16(...)
; FREEBSD-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_2(...)
; FREEBSD-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_4(...)
; FREEBSD-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_8(...)
; FREEBSD-NEXT: declare void @__llvm_memmove_element_unordered_atomic_1(...)
; FREEBSD-NEXT: declare void @__llvm_memmove_element_unordered_atomic_16(...)
; FREEBSD-NEXT: declare void @__llvm_memmove_element_unordered_atomic_2(...)
; FREEBSD-NEXT: declare void @__llvm_memmove_element_unordered_atomic_4(...)
; FREEBSD-NEXT: declare void @__llvm_memmove_element_unordered_atomic_8(...)
; FREEBSD-NEXT: declare void @__llvm_memset_element_unordered_atomic_1(...)
; FREEBSD-NEXT: declare void @__llvm_memset_element_unordered_atomic_16(...)
; FREEBSD-NEXT: declare void @__llvm_memset_element_unordered_atomic_2(...)
; FREEBSD-NEXT: declare void @__llvm_memset_element_unordered_atomic_4(...)
; FREEBSD-NEXT: declare void @__llvm_memset_element_unordered_atomic_8(...)
; FREEBSD-NEXT: declare double @__log10_finite(double)
; FREEBSD-NEXT: declare float @__log10f_finite(float)
; FREEBSD-NEXT: declare double @__log10l_finite(double)
; FREEBSD-NEXT: declare double @__log2_finite(double)
; FREEBSD-NEXT: declare float @__log2f_finite(float)
; FREEBSD-NEXT: declare double @__log2l_finite(double)
; FREEBSD-NEXT: declare double @__log_finite(double)
; FREEBSD-NEXT: declare float @__logf_finite(float)
; FREEBSD-NEXT: declare double @__logl_finite(double)
; FREEBSD-NEXT: declare void @__lshrdi3(...)
; FREEBSD-NEXT: declare void @__lshrhi3(...)
; FREEBSD-NEXT: declare void @__lshrsi3(...)
; FREEBSD-NEXT: declare void @__lshrti3(...)
; FREEBSD-NEXT: declare void @__ltdf2(...)
; FREEBSD-NEXT: declare void @__ltsf2(...)
; FREEBSD-NEXT: declare void @__lttf2(...)
; FREEBSD-NEXT: declare ptr @__memcpy_chk(ptr, ptr, i64, i64)
; FREEBSD-NEXT: declare ptr @__memmove_chk(ptr, ptr, i64, i64)
; FREEBSD-NEXT: declare ptr @__memset_chk(ptr, i32, i64, i64)
; FREEBSD-NEXT: declare void @__modhi3(...)
; FREEBSD-NEXT: declare void @__modqi3(...)
; FREEBSD-NEXT: declare void @__modsi3(...)
; FREEBSD-NEXT: declare void @__modti3(...)
; FREEBSD-NEXT: declare void @__muldf3(...)
; FREEBSD-NEXT: declare void @__mulhi3(...)
; FREEBSD-NEXT: declare void @__mulosi4(...)
; FREEBSD-NEXT: declare void @__mulqi3(...)
; FREEBSD-NEXT: declare void @__mulsf3(...)
; FREEBSD-NEXT: declare void @__mulsi3(...)
; FREEBSD-NEXT: declare void @__multf3(...)
; FREEBSD-NEXT: declare void @__multi3(...)
; FREEBSD-NEXT: declare void @__mulxf3(...)
; FREEBSD-NEXT: declare void @__nedf2(...)
; FREEBSD-NEXT: declare void @__negdi2(...)
; FREEBSD-NEXT: declare void @__negsi2(...)
; FREEBSD-NEXT: declare void @__nesf2(...)
; FREEBSD-NEXT: declare void @__netf2(...)
; FREEBSD-NEXT: declare void @__popcountdi2(...)
; FREEBSD-NEXT: declare void @__popcountsi2(...)
; FREEBSD-NEXT: declare void @__popcountti2(...)
; FREEBSD-NEXT: declare double @__pow_finite(double, double)
; FREEBSD-NEXT: declare float @__powf_finite(float, float)
; FREEBSD-NEXT: declare void @__powidf2(...)
; FREEBSD-NEXT: declare void @__powisf2(...)
; FREEBSD-NEXT: declare void @__powitf2(...)
; FREEBSD-NEXT: declare void @__powixf2(...)
; FREEBSD-NEXT: declare double @__powl_finite(double, double)
; FREEBSD-NEXT: declare void @__safestack_unsafe_stack_ptr(...)
; FREEBSD-NEXT: declare void @__stack_chk_fail(...)
; FREEBSD-NEXT: declare void @__stack_chk_guard(...)
; FREEBSD-NEXT: declare void @__subdf3(...)
; FREEBSD-NEXT: declare void @__subsf3(...)
; FREEBSD-NEXT: declare void @__subtf3(...)
; FREEBSD-NEXT: declare void @__subxf3(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_add_1(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_add_16(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_add_2(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_add_4(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_add_8(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_and_1(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_and_16(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_and_2(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_and_4(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_and_8(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_max_1(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_max_16(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_max_2(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_max_4(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_max_8(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_min_1(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_min_16(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_min_2(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_min_4(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_min_8(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_nand_1(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_nand_16(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_nand_2(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_nand_4(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_nand_8(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_or_1(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_or_16(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_or_2(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_or_4(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_or_8(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_sub_1(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_sub_16(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_sub_2(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_sub_4(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_sub_8(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_umax_1(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_umax_16(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_umax_2(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_umax_4(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_umax_8(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_umin_1(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_umin_16(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_umin_2(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_umin_4(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_umin_8(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_xor_1(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_xor_16(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_xor_2(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_xor_4(...)
; FREEBSD-NEXT: declare void @__sync_fetch_and_xor_8(...)
; FREEBSD-NEXT: declare void @__sync_lock_test_and_set_1(...)
; FREEBSD-NEXT: declare void @__sync_lock_test_and_set_16(...)
; FREEBSD-NEXT: declare void @__sync_lock_test_and_set_2(...)
; FREEBSD-NEXT: declare void @__sync_lock_test_and_set_4(...)
; FREEBSD-NEXT: declare void @__sync_lock_test_and_set_8(...)
; FREEBSD-NEXT: declare void @__sync_val_compare_and_swap_1(...)
; FREEBSD-NEXT: declare void @__sync_val_compare_and_swap_16(...)
; FREEBSD-NEXT: declare void @__sync_val_compare_and_swap_2(...)
; FREEBSD-NEXT: declare void @__sync_val_compare_and_swap_4(...)
; FREEBSD-NEXT: declare void @__sync_val_compare_and_swap_8(...)
; FREEBSD-NEXT: declare void @__truncdfbf2(...)
; FREEBSD-NEXT: declare void @__truncdfhf2(...)
; FREEBSD-NEXT: declare void @__truncdfsf2(...)
; FREEBSD-NEXT: declare void @__truncsfbf2(...)
; FREEBSD-NEXT: declare void @__truncsfhf2(...)
; FREEBSD-NEXT: declare void @__trunctfbf2(...)
; FREEBSD-NEXT: declare void @__trunctfdf2(...)
; FREEBSD-NEXT: declare void @__trunctfhf2(...)
; FREEBSD-NEXT: declare void @__trunctfsf2(...)
; FREEBSD-NEXT: declare void @__trunctfxf2(...)
; FREEBSD-NEXT: declare void @__truncxfbf2(...)
; FREEBSD-NEXT: declare void @__truncxfdf2(...)
; FREEBSD-NEXT: declare void @__truncxfhf2(...)
; FREEBSD-NEXT: declare void @__truncxfsf2(...)
; FREEBSD-NEXT: declare void @__udivhi3(...)
; FREEBSD-NEXT: declare void @__udivqi3(...)
; FREEBSD-NEXT: declare void @__udivsi3(...)
; FREEBSD-NEXT: declare void @__udivti3(...)
; FREEBSD-NEXT: declare void @__umodhi3(...)
; FREEBSD-NEXT: declare void @__umodqi3(...)
; FREEBSD-NEXT: declare void @__umodsi3(...)
; FREEBSD-NEXT: declare void @__umodti3(...)
; FREEBSD-NEXT: declare void @__unorddf2(...)
; FREEBSD-NEXT: declare void @__unordsf2(...)
; FREEBSD-NEXT: declare void @__unordtf2(...)
; FREEBSD-NEXT: declare double @acos(double)
; FREEBSD-NEXT: declare float @acosf(float)
; FREEBSD-NEXT: declare double @acosl(double)
; FREEBSD-NEXT: declare double @asin(double)
; FREEBSD-NEXT: declare float @asinf(float)
; FREEBSD-NEXT: declare double @asinl(double)
; FREEBSD-NEXT: declare double @atan(double)
; FREEBSD-NEXT: declare double @atan2(double, double)
; FREEBSD-NEXT: declare float @atan2f(float, float)
; FREEBSD-NEXT: declare double @atan2l(double, double)
; FREEBSD-NEXT: declare float @atanf(float)
; FREEBSD-NEXT: declare double @atanl(double)
; FREEBSD-NEXT: declare void @cabs(...)
; FREEBSD-NEXT: declare void @cabsf(...)
; FREEBSD-NEXT: declare void @cabsl(...)
; FREEBSD-NEXT: declare noalias noundef ptr @calloc(i64 noundef, i64 noundef) [[CALLOC_ATTRS:#[0-9]+]]
; FREEBSD-NEXT: declare double @cbrt(double)
; FREEBSD-NEXT: declare float @cbrtf(float)
; FREEBSD-NEXT: declare double @cbrtl(double)
; FREEBSD-NEXT: declare double @ceil(double)
; FREEBSD-NEXT: declare float @ceilf(float)
; FREEBSD-NEXT: declare double @ceill(double)
; FREEBSD-NEXT: declare double @copysign(double, double)
; FREEBSD-NEXT: declare float @copysignf(float, float)
; FREEBSD-NEXT: declare double @copysignl(double, double)
; FREEBSD-NEXT: declare double @cos(double)
; FREEBSD-NEXT: declare float @cosf(float)
; FREEBSD-NEXT: declare double @cosh(double)
; FREEBSD-NEXT: declare float @coshf(float)
; FREEBSD-NEXT: declare double @coshl(double)
; FREEBSD-NEXT: declare double @cosl(double)
; FREEBSD-NEXT: declare double @exp(double)
; FREEBSD-NEXT: declare double @exp10(double)
; FREEBSD-NEXT: declare float @exp10f(float)
; FREEBSD-NEXT: declare double @exp10l(double)
; FREEBSD-NEXT: declare double @exp2(double)
; FREEBSD-NEXT: declare float @exp2f(float)
; FREEBSD-NEXT: declare double @exp2l(double)
; FREEBSD-NEXT: declare float @expf(float)
; FREEBSD-NEXT: declare double @expl(double)
; FREEBSD-NEXT: declare double @fdim(double, double)
; FREEBSD-NEXT: declare float @fdimf(float, float)
; FREEBSD-NEXT: declare double @fdiml(double, double)
; FREEBSD-NEXT: declare void @fegetenv(...)
; FREEBSD-NEXT: declare void @fegetmode(...)
; FREEBSD-NEXT: declare void @fesetenv(...)
; FREEBSD-NEXT: declare void @fesetmode(...)
; FREEBSD-NEXT: declare double @floor(double)
; FREEBSD-NEXT: declare float @floorf(float)
; FREEBSD-NEXT: declare double @floorl(double)
; FREEBSD-NEXT: declare void @fma(...)
; FREEBSD-NEXT: declare void @fmaf(...)
; FREEBSD-NEXT: declare void @fmal(...)
; FREEBSD-NEXT: declare float @fmax(float, float)
; FREEBSD-NEXT: declare float @fmaxf(float, float)
; FREEBSD-NEXT: declare void @fmaximum(...)
; FREEBSD-NEXT: declare float @fmaximum_num(float, float)
; FREEBSD-NEXT: declare float @fmaximum_numf(float, float)
; FREEBSD-NEXT: declare float @fmaximum_numl(float, float)
; FREEBSD-NEXT: declare void @fmaximumf(...)
; FREEBSD-NEXT: declare void @fmaximuml(...)
; FREEBSD-NEXT: declare float @fmaxl(float, float)
; FREEBSD-NEXT: declare float @fmin(float, float)
; FREEBSD-NEXT: declare float @fminf(float, float)
; FREEBSD-NEXT: declare void @fminimum(...)
; FREEBSD-NEXT: declare float @fminimum_num(float, float)
; FREEBSD-NEXT: declare float @fminimum_numf(float, float)
; FREEBSD-NEXT: declare float @fminimum_numl(float, float)
; FREEBSD-NEXT: declare void @fminimumf(...)
; FREEBSD-NEXT: declare void @fminimuml(...)
; FREEBSD-NEXT: declare float @fminl(float, float)
; FREEBSD-NEXT: declare double @fmod(double, double)
; FREEBSD-NEXT: declare float @fmodf(float, float)
; FREEBSD-NEXT: declare double @fmodl(double, double)
; FREEBSD-NEXT: declare void @free(ptr allocptr noundef captures(none)) [[FREE_ATTRS:#[0-9]+]]
; FREEBSD-NEXT: declare double @frexp(double, ptr)
; FREEBSD-NEXT: declare float @frexpf(float, ptr)
; FREEBSD-NEXT: declare double @frexpl(double, ptr)
; FREEBSD-NEXT: declare double @ldexp(double, i32)
; FREEBSD-NEXT: declare float @ldexpf(float, i32)
; FREEBSD-NEXT: declare double @ldexpl(double, i32)
; FREEBSD-NEXT: declare void @llrint(...)
; FREEBSD-NEXT: declare void @llrintf(...)
; FREEBSD-NEXT: declare void @llrintl(...)
; FREEBSD-NEXT: declare void @llround(...)
; FREEBSD-NEXT: declare void @llroundf(...)
; FREEBSD-NEXT: declare void @llroundl(...)
; FREEBSD-NEXT: declare double @log(double)
; FREEBSD-NEXT: declare double @log10(double)
; FREEBSD-NEXT: declare float @log10f(float)
; FREEBSD-NEXT: declare double @log10l(double)
; FREEBSD-NEXT: declare double @log2(double)
; FREEBSD-NEXT: declare float @log2f(float)
; FREEBSD-NEXT: declare double @log2l(double)
; FREEBSD-NEXT: declare float @logf(float)
; FREEBSD-NEXT: declare double @logl(double)
; FREEBSD-NEXT: declare void @lrint(...)
; FREEBSD-NEXT: declare void @lrintf(...)
; FREEBSD-NEXT: declare void @lrintl(...)
; FREEBSD-NEXT: declare void @lround(...)
; FREEBSD-NEXT: declare void @lroundf(...)
; FREEBSD-NEXT: declare void @lroundl(...)
; FREEBSD-NEXT: declare noalias noundef ptr @malloc(i64 noundef) [[MALLOC_ATTRS:#[0-9]+]]
; FREEBSD-NEXT: declare ptr @memcpy(ptr, ptr, i64)
; FREEBSD-NEXT: declare ptr @memmove(ptr, ptr, i64)
; FREEBSD-NEXT: declare ptr @memset(ptr, i32, i64)
; FREEBSD-NEXT: declare double @modf(double, ptr)
; FREEBSD-NEXT: declare float @modff(float, ptr)
; FREEBSD-NEXT: declare double @modfl(double, ptr)
; FREEBSD-NEXT: declare double @nan(ptr)
; FREEBSD-NEXT: declare float @nanf(ptr)
; FREEBSD-NEXT: declare double @nanl(ptr)
; FREEBSD-NEXT: declare double @nearbyint(double)
; FREEBSD-NEXT: declare float @nearbyintf(float)
; FREEBSD-NEXT: declare double @nearbyintl(double)
; FREEBSD-NEXT: declare double @nexttoward(double, double)
; FREEBSD-NEXT: declare float @nexttowardf(float, double)
; FREEBSD-NEXT: declare double @nexttowardl(double, double)
; FREEBSD-NEXT: declare double @pow(double, double)
; FREEBSD-NEXT: declare float @powf(float, float)
; FREEBSD-NEXT: declare double @powl(double, double)
; FREEBSD-NEXT: declare double @remainder(double, double)
; FREEBSD-NEXT: declare float @remainderf(float, float)
; FREEBSD-NEXT: declare double @remainderl(double, double)
; FREEBSD-NEXT: declare double @remquo(double, double, ptr)
; FREEBSD-NEXT: declare float @remquof(float, float, ptr)
; FREEBSD-NEXT: declare double @remquol(double, double, ptr)
; FREEBSD-NEXT: declare double @rint(double)
; FREEBSD-NEXT: declare float @rintf(float)
; FREEBSD-NEXT: declare double @rintl(double)
; FREEBSD-NEXT: declare double @round(double)
; FREEBSD-NEXT: declare double @roundeven(double)
; FREEBSD-NEXT: declare float @roundevenf(float)
; FREEBSD-NEXT: declare double @roundevenl(double)
; FREEBSD-NEXT: declare float @roundf(float)
; FREEBSD-NEXT: declare double @roundl(double)
; FREEBSD-NEXT: declare double @scalbln(double, i32)
; FREEBSD-NEXT: declare float @scalblnf(float, i32)
; FREEBSD-NEXT: declare double @scalblnl(double, i32)
; FREEBSD-NEXT: declare double @scalbn(double, i32)
; FREEBSD-NEXT: declare float @scalbnf(float, i32)
; FREEBSD-NEXT: declare double @scalbnl(double, i32)
; FREEBSD-NEXT: declare double @sin(double)
; FREEBSD-NEXT: declare float @sinf(float)
; FREEBSD-NEXT: declare double @sinh(double)
; FREEBSD-NEXT: declare float @sinhf(float)
; FREEBSD-NEXT: declare double @sinhl(double)
; FREEBSD-NEXT: declare double @sinl(double)
; FREEBSD-NEXT: declare nofpclass(ninf nsub nnorm) double @sqrt(double) [[SQRT_ATTRS:#[0-9]+]]
; FREEBSD-NEXT: declare nofpclass(ninf nsub nnorm) float @sqrtf(float) [[SQRT_ATTRS:#[0-9]+]]
; FREEBSD-NEXT: declare double @sqrtl(double)
; FREEBSD-NEXT: declare double @tan(double)
; FREEBSD-NEXT: declare float @tanf(float)
; FREEBSD-NEXT: declare double @tanh(double)
; FREEBSD-NEXT: declare float @tanhf(float)
; FREEBSD-NEXT: declare double @tanhl(double)
; FREEBSD-NEXT: declare double @tanl(double)
; FREEBSD-NEXT: declare double @tgamma(double)
; FREEBSD-NEXT: declare float @tgammaf(float)
; FREEBSD-NEXT: declare double @tgammal(double)
; FREEBSD-NEXT: declare double @trunc(double)
; FREEBSD-NEXT: declare float @truncf(float)
; FREEBSD-NEXT: declare double @truncl(double)
; FREEBSD-NEXT: attributes [[CALLOC_ATTRS]] = { nofree nounwind willreturn allockind("alloc") allocsize(0,1) "alloc-family"="malloc" }
; FREEBSD-NEXT: attributes [[FREE_ATTRS]] = { nounwind willreturn allockind("free") "alloc-family"="malloc" }
; FREEBSD-NEXT: attributes [[MALLOC_ATTRS]] = { nofree nounwind willreturn allockind("alloc,uninitialized") allocsize(0) "alloc-family"="malloc" }
; FREEBSD-NEXT: attributes [[SQRT_ATTRS]] = { nocallback nofree nosync nounwind willreturn memory(errnomem: write) }

; OPENBSD: declare void @_Unwind_Resume(...)
; OPENBSD-NEXT: declare void @__adddf3(...)
; OPENBSD-NEXT: declare void @__addsf3(...)
; OPENBSD-NEXT: declare void @__addtf3(...)
; OPENBSD-NEXT: declare void @__addxf3(...)
; OPENBSD-NEXT: declare void @__ashldi3(...)
; OPENBSD-NEXT: declare void @__ashlhi3(...)
; OPENBSD-NEXT: declare void @__ashlsi3(...)
; OPENBSD-NEXT: declare void @__ashlti3(...)
; OPENBSD-NEXT: declare void @__ashrdi3(...)
; OPENBSD-NEXT: declare void @__ashrhi3(...)
; OPENBSD-NEXT: declare void @__ashrsi3(...)
; OPENBSD-NEXT: declare void @__ashrti3(...)
; OPENBSD-NEXT: declare void @__atomic_compare_exchange(...)
; OPENBSD-NEXT: declare void @__atomic_compare_exchange_1(...)
; OPENBSD-NEXT: declare void @__atomic_compare_exchange_16(...)
; OPENBSD-NEXT: declare void @__atomic_compare_exchange_2(...)
; OPENBSD-NEXT: declare void @__atomic_compare_exchange_4(...)
; OPENBSD-NEXT: declare void @__atomic_compare_exchange_8(...)
; OPENBSD-NEXT: declare void @__atomic_exchange(...)
; OPENBSD-NEXT: declare void @__atomic_exchange_1(...)
; OPENBSD-NEXT: declare void @__atomic_exchange_16(...)
; OPENBSD-NEXT: declare void @__atomic_exchange_2(...)
; OPENBSD-NEXT: declare void @__atomic_exchange_4(...)
; OPENBSD-NEXT: declare void @__atomic_exchange_8(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_add_1(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_add_16(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_add_2(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_add_4(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_add_8(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_and_1(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_and_16(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_and_2(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_and_4(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_and_8(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_nand_1(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_nand_16(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_nand_2(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_nand_4(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_nand_8(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_or_1(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_or_16(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_or_2(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_or_4(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_or_8(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_sub_1(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_sub_16(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_sub_2(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_sub_4(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_sub_8(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_xor_1(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_xor_16(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_xor_2(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_xor_4(...)
; OPENBSD-NEXT: declare void @__atomic_fetch_xor_8(...)
; OPENBSD-NEXT: declare void @__atomic_load(i64, ptr, ptr, i32)
; OPENBSD-NEXT: declare void @__atomic_load_1(...)
; OPENBSD-NEXT: declare void @__atomic_load_16(...)
; OPENBSD-NEXT: declare void @__atomic_load_2(...)
; OPENBSD-NEXT: declare void @__atomic_load_4(...)
; OPENBSD-NEXT: declare void @__atomic_load_8(...)
; OPENBSD-NEXT: declare void @__atomic_store(i64, ptr, ptr, i32)
; OPENBSD-NEXT: declare void @__atomic_store_1(...)
; OPENBSD-NEXT: declare void @__atomic_store_16(...)
; OPENBSD-NEXT: declare void @__atomic_store_2(...)
; OPENBSD-NEXT: declare void @__atomic_store_4(...)
; OPENBSD-NEXT: declare void @__atomic_store_8(...)
; OPENBSD-NEXT: declare void @__clear_cache(...)
; OPENBSD-NEXT: declare void @__clzdi2(...)
; OPENBSD-NEXT: declare void @__clzsi2(...)
; OPENBSD-NEXT: declare void @__clzti2(...)
; OPENBSD-NEXT: declare void @__cxa_end_cleanup(...)
; OPENBSD-NEXT: declare void @__divdf3(...)
; OPENBSD-NEXT: declare void @__divhi3(...)
; OPENBSD-NEXT: declare void @__divqi3(...)
; OPENBSD-NEXT: declare void @__divsf3(...)
; OPENBSD-NEXT: declare void @__divsi3(...)
; OPENBSD-NEXT: declare void @__divtf3(...)
; OPENBSD-NEXT: declare void @__divti3(...)
; OPENBSD-NEXT: declare void @__divxf3(...)
; OPENBSD-NEXT: declare void @__eqdf2(...)
; OPENBSD-NEXT: declare void @__eqsf2(...)
; OPENBSD-NEXT: declare void @__eqtf2(...)
; OPENBSD-NEXT: declare double @__exp2_finite(double)
; OPENBSD-NEXT: declare float @__exp2f_finite(float)
; OPENBSD-NEXT: declare double @__exp2l_finite(double)
; OPENBSD-NEXT: declare double @__exp_finite(double)
; OPENBSD-NEXT: declare float @__expf_finite(float)
; OPENBSD-NEXT: declare double @__expl_finite(double)
; OPENBSD-NEXT: declare void @__extendbfsf2(...)
; OPENBSD-NEXT: declare void @__extenddftf2(...)
; OPENBSD-NEXT: declare void @__extendhfdf2(...)
; OPENBSD-NEXT: declare void @__extendhfsf2(...)
; OPENBSD-NEXT: declare void @__extendhftf2(...)
; OPENBSD-NEXT: declare void @__extendhfxf2(...)
; OPENBSD-NEXT: declare void @__extendsfdf2(...)
; OPENBSD-NEXT: declare void @__extendsftf2(...)
; OPENBSD-NEXT: declare void @__extendxftf2(...)
; OPENBSD-NEXT: declare void @__fixdfdi(...)
; OPENBSD-NEXT: declare void @__fixdfsi(...)
; OPENBSD-NEXT: declare void @__fixdfti(...)
; OPENBSD-NEXT: declare void @__fixhfdi(...)
; OPENBSD-NEXT: declare void @__fixhfsi(...)
; OPENBSD-NEXT: declare void @__fixhfti(...)
; OPENBSD-NEXT: declare void @__fixsfdi(...)
; OPENBSD-NEXT: declare void @__fixsfsi(...)
; OPENBSD-NEXT: declare void @__fixsfti(...)
; OPENBSD-NEXT: declare void @__fixtfdi(...)
; OPENBSD-NEXT: declare void @__fixtfsi(...)
; OPENBSD-NEXT: declare void @__fixtfti(...)
; OPENBSD-NEXT: declare void @__fixunsdfdi(...)
; OPENBSD-NEXT: declare void @__fixunsdfsi(...)
; OPENBSD-NEXT: declare void @__fixunsdfti(...)
; OPENBSD-NEXT: declare void @__fixunshfdi(...)
; OPENBSD-NEXT: declare void @__fixunshfsi(...)
; OPENBSD-NEXT: declare void @__fixunshfti(...)
; OPENBSD-NEXT: declare void @__fixunssfdi(...)
; OPENBSD-NEXT: declare void @__fixunssfsi(...)
; OPENBSD-NEXT: declare void @__fixunssfti(...)
; OPENBSD-NEXT: declare void @__fixunstfdi(...)
; OPENBSD-NEXT: declare void @__fixunstfsi(...)
; OPENBSD-NEXT: declare void @__fixunstfti(...)
; OPENBSD-NEXT: declare void @__fixunsxfdi(...)
; OPENBSD-NEXT: declare void @__fixunsxfsi(...)
; OPENBSD-NEXT: declare void @__fixunsxfti(...)
; OPENBSD-NEXT: declare void @__fixxfdi(...)
; OPENBSD-NEXT: declare void @__fixxfsi(...)
; OPENBSD-NEXT: declare void @__fixxfti(...)
; OPENBSD-NEXT: declare void @__floatdibf(...)
; OPENBSD-NEXT: declare void @__floatdidf(...)
; OPENBSD-NEXT: declare void @__floatdihf(...)
; OPENBSD-NEXT: declare void @__floatdisf(...)
; OPENBSD-NEXT: declare void @__floatditf(...)
; OPENBSD-NEXT: declare void @__floatdixf(...)
; OPENBSD-NEXT: declare void @__floatsidf(...)
; OPENBSD-NEXT: declare void @__floatsihf(...)
; OPENBSD-NEXT: declare void @__floatsisf(...)
; OPENBSD-NEXT: declare void @__floatsitf(...)
; OPENBSD-NEXT: declare void @__floatsixf(...)
; OPENBSD-NEXT: declare void @__floattidf(...)
; OPENBSD-NEXT: declare void @__floattihf(...)
; OPENBSD-NEXT: declare void @__floattisf(...)
; OPENBSD-NEXT: declare void @__floattitf(...)
; OPENBSD-NEXT: declare void @__floattixf(...)
; OPENBSD-NEXT: declare void @__floatundibf(...)
; OPENBSD-NEXT: declare void @__floatundidf(...)
; OPENBSD-NEXT: declare void @__floatundihf(...)
; OPENBSD-NEXT: declare void @__floatundisf(...)
; OPENBSD-NEXT: declare void @__floatunditf(...)
; OPENBSD-NEXT: declare void @__floatundixf(...)
; OPENBSD-NEXT: declare void @__floatunsidf(...)
; OPENBSD-NEXT: declare void @__floatunsihf(...)
; OPENBSD-NEXT: declare void @__floatunsisf(...)
; OPENBSD-NEXT: declare void @__floatunsitf(...)
; OPENBSD-NEXT: declare void @__floatunsixf(...)
; OPENBSD-NEXT: declare void @__floatuntidf(...)
; OPENBSD-NEXT: declare void @__floatuntihf(...)
; OPENBSD-NEXT: declare void @__floatuntisf(...)
; OPENBSD-NEXT: declare void @__floatuntitf(...)
; OPENBSD-NEXT: declare void @__floatuntixf(...)
; OPENBSD-NEXT: declare void @__gedf2(...)
; OPENBSD-NEXT: declare void @__gesf2(...)
; OPENBSD-NEXT: declare void @__getf2(...)
; OPENBSD-NEXT: declare void @__gtdf2(...)
; OPENBSD-NEXT: declare void @__gtsf2(...)
; OPENBSD-NEXT: declare void @__gttf2(...)
; OPENBSD-NEXT: declare void @__guard_local(...)
; OPENBSD-NEXT: declare void @__ledf2(...)
; OPENBSD-NEXT: declare void @__lesf2(...)
; OPENBSD-NEXT: declare void @__letf2(...)
; OPENBSD-NEXT: declare void @__llvm_deoptimize(...)
; OPENBSD-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_1(...)
; OPENBSD-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_16(...)
; OPENBSD-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_2(...)
; OPENBSD-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_4(...)
; OPENBSD-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_8(...)
; OPENBSD-NEXT: declare void @__llvm_memmove_element_unordered_atomic_1(...)
; OPENBSD-NEXT: declare void @__llvm_memmove_element_unordered_atomic_16(...)
; OPENBSD-NEXT: declare void @__llvm_memmove_element_unordered_atomic_2(...)
; OPENBSD-NEXT: declare void @__llvm_memmove_element_unordered_atomic_4(...)
; OPENBSD-NEXT: declare void @__llvm_memmove_element_unordered_atomic_8(...)
; OPENBSD-NEXT: declare void @__llvm_memset_element_unordered_atomic_1(...)
; OPENBSD-NEXT: declare void @__llvm_memset_element_unordered_atomic_16(...)
; OPENBSD-NEXT: declare void @__llvm_memset_element_unordered_atomic_2(...)
; OPENBSD-NEXT: declare void @__llvm_memset_element_unordered_atomic_4(...)
; OPENBSD-NEXT: declare void @__llvm_memset_element_unordered_atomic_8(...)
; OPENBSD-NEXT: declare double @__log10_finite(double)
; OPENBSD-NEXT: declare float @__log10f_finite(float)
; OPENBSD-NEXT: declare double @__log10l_finite(double)
; OPENBSD-NEXT: declare double @__log2_finite(double)
; OPENBSD-NEXT: declare float @__log2f_finite(float)
; OPENBSD-NEXT: declare double @__log2l_finite(double)
; OPENBSD-NEXT: declare double @__log_finite(double)
; OPENBSD-NEXT: declare float @__logf_finite(float)
; OPENBSD-NEXT: declare double @__logl_finite(double)
; OPENBSD-NEXT: declare void @__lshrdi3(...)
; OPENBSD-NEXT: declare void @__lshrhi3(...)
; OPENBSD-NEXT: declare void @__lshrsi3(...)
; OPENBSD-NEXT: declare void @__lshrti3(...)
; OPENBSD-NEXT: declare void @__ltdf2(...)
; OPENBSD-NEXT: declare void @__ltsf2(...)
; OPENBSD-NEXT: declare void @__lttf2(...)
; OPENBSD-NEXT: declare ptr @__memcpy_chk(ptr, ptr, i64, i64)
; OPENBSD-NEXT: declare ptr @__memmove_chk(ptr, ptr, i64, i64)
; OPENBSD-NEXT: declare ptr @__memset_chk(ptr, i32, i64, i64)
; OPENBSD-NEXT: declare void @__modhi3(...)
; OPENBSD-NEXT: declare void @__modqi3(...)
; OPENBSD-NEXT: declare void @__modsi3(...)
; OPENBSD-NEXT: declare void @__modti3(...)
; OPENBSD-NEXT: declare void @__muldf3(...)
; OPENBSD-NEXT: declare void @__mulhi3(...)
; OPENBSD-NEXT: declare void @__mulosi4(...)
; OPENBSD-NEXT: declare void @__mulqi3(...)
; OPENBSD-NEXT: declare void @__mulsf3(...)
; OPENBSD-NEXT: declare void @__mulsi3(...)
; OPENBSD-NEXT: declare void @__multf3(...)
; OPENBSD-NEXT: declare void @__multi3(...)
; OPENBSD-NEXT: declare void @__mulxf3(...)
; OPENBSD-NEXT: declare void @__nedf2(...)
; OPENBSD-NEXT: declare void @__negdi2(...)
; OPENBSD-NEXT: declare void @__negsi2(...)
; OPENBSD-NEXT: declare void @__nesf2(...)
; OPENBSD-NEXT: declare void @__netf2(...)
; OPENBSD-NEXT: declare void @__popcountdi2(...)
; OPENBSD-NEXT: declare void @__popcountsi2(...)
; OPENBSD-NEXT: declare void @__popcountti2(...)
; OPENBSD-NEXT: declare double @__pow_finite(double, double)
; OPENBSD-NEXT: declare float @__powf_finite(float, float)
; OPENBSD-NEXT: declare void @__powidf2(...)
; OPENBSD-NEXT: declare void @__powisf2(...)
; OPENBSD-NEXT: declare void @__powitf2(...)
; OPENBSD-NEXT: declare void @__powixf2(...)
; OPENBSD-NEXT: declare double @__powl_finite(double, double)
; OPENBSD-NEXT: declare void @__safestack_unsafe_stack_ptr(...)
; OPENBSD-NEXT: declare void @__stack_smash_handler(...)
; OPENBSD-NEXT: declare void @__subdf3(...)
; OPENBSD-NEXT: declare void @__subsf3(...)
; OPENBSD-NEXT: declare void @__subtf3(...)
; OPENBSD-NEXT: declare void @__subxf3(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_add_1(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_add_16(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_add_2(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_add_4(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_add_8(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_and_1(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_and_16(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_and_2(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_and_4(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_and_8(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_max_1(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_max_16(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_max_2(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_max_4(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_max_8(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_min_1(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_min_16(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_min_2(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_min_4(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_min_8(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_nand_1(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_nand_16(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_nand_2(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_nand_4(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_nand_8(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_or_1(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_or_16(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_or_2(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_or_4(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_or_8(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_sub_1(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_sub_16(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_sub_2(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_sub_4(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_sub_8(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_umax_1(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_umax_16(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_umax_2(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_umax_4(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_umax_8(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_umin_1(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_umin_16(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_umin_2(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_umin_4(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_umin_8(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_xor_1(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_xor_16(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_xor_2(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_xor_4(...)
; OPENBSD-NEXT: declare void @__sync_fetch_and_xor_8(...)
; OPENBSD-NEXT: declare void @__sync_lock_test_and_set_1(...)
; OPENBSD-NEXT: declare void @__sync_lock_test_and_set_16(...)
; OPENBSD-NEXT: declare void @__sync_lock_test_and_set_2(...)
; OPENBSD-NEXT: declare void @__sync_lock_test_and_set_4(...)
; OPENBSD-NEXT: declare void @__sync_lock_test_and_set_8(...)
; OPENBSD-NEXT: declare void @__sync_val_compare_and_swap_1(...)
; OPENBSD-NEXT: declare void @__sync_val_compare_and_swap_16(...)
; OPENBSD-NEXT: declare void @__sync_val_compare_and_swap_2(...)
; OPENBSD-NEXT: declare void @__sync_val_compare_and_swap_4(...)
; OPENBSD-NEXT: declare void @__sync_val_compare_and_swap_8(...)
; OPENBSD-NEXT: declare void @__truncdfbf2(...)
; OPENBSD-NEXT: declare void @__truncdfhf2(...)
; OPENBSD-NEXT: declare void @__truncdfsf2(...)
; OPENBSD-NEXT: declare void @__truncsfbf2(...)
; OPENBSD-NEXT: declare void @__truncsfhf2(...)
; OPENBSD-NEXT: declare void @__trunctfbf2(...)
; OPENBSD-NEXT: declare void @__trunctfdf2(...)
; OPENBSD-NEXT: declare void @__trunctfhf2(...)
; OPENBSD-NEXT: declare void @__trunctfsf2(...)
; OPENBSD-NEXT: declare void @__trunctfxf2(...)
; OPENBSD-NEXT: declare void @__truncxfbf2(...)
; OPENBSD-NEXT: declare void @__truncxfdf2(...)
; OPENBSD-NEXT: declare void @__truncxfhf2(...)
; OPENBSD-NEXT: declare void @__truncxfsf2(...)
; OPENBSD-NEXT: declare void @__udivhi3(...)
; OPENBSD-NEXT: declare void @__udivqi3(...)
; OPENBSD-NEXT: declare void @__udivsi3(...)
; OPENBSD-NEXT: declare void @__udivti3(...)
; OPENBSD-NEXT: declare void @__umodhi3(...)
; OPENBSD-NEXT: declare void @__umodqi3(...)
; OPENBSD-NEXT: declare void @__umodsi3(...)
; OPENBSD-NEXT: declare void @__umodti3(...)
; OPENBSD-NEXT: declare void @__unorddf2(...)
; OPENBSD-NEXT: declare void @__unordsf2(...)
; OPENBSD-NEXT: declare void @__unordtf2(...)
; OPENBSD-NEXT: declare double @acos(double)
; OPENBSD-NEXT: declare float @acosf(float)
; OPENBSD-NEXT: declare double @acosl(double)
; OPENBSD-NEXT: declare double @asin(double)
; OPENBSD-NEXT: declare float @asinf(float)
; OPENBSD-NEXT: declare double @asinl(double)
; OPENBSD-NEXT: declare double @atan(double)
; OPENBSD-NEXT: declare double @atan2(double, double)
; OPENBSD-NEXT: declare float @atan2f(float, float)
; OPENBSD-NEXT: declare double @atan2l(double, double)
; OPENBSD-NEXT: declare float @atanf(float)
; OPENBSD-NEXT: declare double @atanl(double)
; OPENBSD-NEXT: declare void @cabs(...)
; OPENBSD-NEXT: declare void @cabsf(...)
; OPENBSD-NEXT: declare void @cabsl(...)
; OPENBSD-NEXT: declare noalias noundef ptr @calloc(i64 noundef, i64 noundef) [[CALLOC_ATTRS:#[0-9]+]]
; OPENBSD-NEXT: declare double @cbrt(double)
; OPENBSD-NEXT: declare float @cbrtf(float)
; OPENBSD-NEXT: declare double @cbrtl(double)
; OPENBSD-NEXT: declare double @ceil(double)
; OPENBSD-NEXT: declare float @ceilf(float)
; OPENBSD-NEXT: declare double @ceill(double)
; OPENBSD-NEXT: declare double @copysign(double, double)
; OPENBSD-NEXT: declare float @copysignf(float, float)
; OPENBSD-NEXT: declare double @copysignl(double, double)
; OPENBSD-NEXT: declare double @cos(double)
; OPENBSD-NEXT: declare float @cosf(float)
; OPENBSD-NEXT: declare double @cosh(double)
; OPENBSD-NEXT: declare float @coshf(float)
; OPENBSD-NEXT: declare double @coshl(double)
; OPENBSD-NEXT: declare double @cosl(double)
; OPENBSD-NEXT: declare double @exp(double)
; OPENBSD-NEXT: declare double @exp10(double)
; OPENBSD-NEXT: declare float @exp10f(float)
; OPENBSD-NEXT: declare double @exp10l(double)
; OPENBSD-NEXT: declare double @exp2(double)
; OPENBSD-NEXT: declare float @exp2f(float)
; OPENBSD-NEXT: declare double @exp2l(double)
; OPENBSD-NEXT: declare float @expf(float)
; OPENBSD-NEXT: declare double @expl(double)
; OPENBSD-NEXT: declare double @fdim(double, double)
; OPENBSD-NEXT: declare float @fdimf(float, float)
; OPENBSD-NEXT: declare double @fdiml(double, double)
; OPENBSD-NEXT: declare void @fegetenv(...)
; OPENBSD-NEXT: declare void @fegetmode(...)
; OPENBSD-NEXT: declare void @fesetenv(...)
; OPENBSD-NEXT: declare void @fesetmode(...)
; OPENBSD-NEXT: declare double @floor(double)
; OPENBSD-NEXT: declare float @floorf(float)
; OPENBSD-NEXT: declare double @floorl(double)
; OPENBSD-NEXT: declare void @fma(...)
; OPENBSD-NEXT: declare void @fmaf(...)
; OPENBSD-NEXT: declare void @fmal(...)
; OPENBSD-NEXT: declare float @fmax(float, float)
; OPENBSD-NEXT: declare float @fmaxf(float, float)
; OPENBSD-NEXT: declare void @fmaximum(...)
; OPENBSD-NEXT: declare float @fmaximum_num(float, float)
; OPENBSD-NEXT: declare float @fmaximum_numf(float, float)
; OPENBSD-NEXT: declare float @fmaximum_numl(float, float)
; OPENBSD-NEXT: declare void @fmaximumf(...)
; OPENBSD-NEXT: declare void @fmaximuml(...)
; OPENBSD-NEXT: declare float @fmaxl(float, float)
; OPENBSD-NEXT: declare float @fmin(float, float)
; OPENBSD-NEXT: declare float @fminf(float, float)
; OPENBSD-NEXT: declare void @fminimum(...)
; OPENBSD-NEXT: declare float @fminimum_num(float, float)
; OPENBSD-NEXT: declare float @fminimum_numf(float, float)
; OPENBSD-NEXT: declare float @fminimum_numl(float, float)
; OPENBSD-NEXT: declare void @fminimumf(...)
; OPENBSD-NEXT: declare void @fminimuml(...)
; OPENBSD-NEXT: declare float @fminl(float, float)
; OPENBSD-NEXT: declare double @fmod(double, double)
; OPENBSD-NEXT: declare float @fmodf(float, float)
; OPENBSD-NEXT: declare double @fmodl(double, double)
; OPENBSD-NEXT: declare void @free(ptr allocptr noundef captures(none)) [[FREE_ATTRS:#[0-9]+]]
; OPENBSD-NEXT: declare double @frexp(double, ptr)
; OPENBSD-NEXT: declare float @frexpf(float, ptr)
; OPENBSD-NEXT: declare double @frexpl(double, ptr)
; OPENBSD-NEXT: declare double @ldexp(double, i32)
; OPENBSD-NEXT: declare float @ldexpf(float, i32)
; OPENBSD-NEXT: declare double @ldexpl(double, i32)
; OPENBSD-NEXT: declare void @llrint(...)
; OPENBSD-NEXT: declare void @llrintf(...)
; OPENBSD-NEXT: declare void @llrintl(...)
; OPENBSD-NEXT: declare void @llround(...)
; OPENBSD-NEXT: declare void @llroundf(...)
; OPENBSD-NEXT: declare void @llroundl(...)
; OPENBSD-NEXT: declare double @log(double)
; OPENBSD-NEXT: declare double @log10(double)
; OPENBSD-NEXT: declare float @log10f(float)
; OPENBSD-NEXT: declare double @log10l(double)
; OPENBSD-NEXT: declare double @log2(double)
; OPENBSD-NEXT: declare float @log2f(float)
; OPENBSD-NEXT: declare double @log2l(double)
; OPENBSD-NEXT: declare float @logf(float)
; OPENBSD-NEXT: declare double @logl(double)
; OPENBSD-NEXT: declare void @lrint(...)
; OPENBSD-NEXT: declare void @lrintf(...)
; OPENBSD-NEXT: declare void @lrintl(...)
; OPENBSD-NEXT: declare void @lround(...)
; OPENBSD-NEXT: declare void @lroundf(...)
; OPENBSD-NEXT: declare void @lroundl(...)
; OPENBSD-NEXT: declare noalias noundef ptr @malloc(i64 noundef) [[MALLOC_ATTRS:#[0-9]+]]
; OPENBSD-NEXT: declare ptr @memcpy(ptr, ptr, i64)
; OPENBSD-NEXT: declare ptr @memmove(ptr, ptr, i64)
; OPENBSD-NEXT: declare ptr @memset(ptr, i32, i64)
; OPENBSD-NEXT: declare double @modf(double, ptr)
; OPENBSD-NEXT: declare float @modff(float, ptr)
; OPENBSD-NEXT: declare double @modfl(double, ptr)
; OPENBSD-NEXT: declare double @nan(ptr)
; OPENBSD-NEXT: declare float @nanf(ptr)
; OPENBSD-NEXT: declare double @nanl(ptr)
; OPENBSD-NEXT: declare double @nearbyint(double)
; OPENBSD-NEXT: declare float @nearbyintf(float)
; OPENBSD-NEXT: declare double @nearbyintl(double)
; OPENBSD-NEXT: declare double @nexttoward(double, double)
; OPENBSD-NEXT: declare float @nexttowardf(float, double)
; OPENBSD-NEXT: declare double @nexttowardl(double, double)
; OPENBSD-NEXT: declare double @pow(double, double)
; OPENBSD-NEXT: declare float @powf(float, float)
; OPENBSD-NEXT: declare double @powl(double, double)
; OPENBSD-NEXT: declare double @remainder(double, double)
; OPENBSD-NEXT: declare float @remainderf(float, float)
; OPENBSD-NEXT: declare double @remainderl(double, double)
; OPENBSD-NEXT: declare double @remquo(double, double, ptr)
; OPENBSD-NEXT: declare float @remquof(float, float, ptr)
; OPENBSD-NEXT: declare double @remquol(double, double, ptr)
; OPENBSD-NEXT: declare double @rint(double)
; OPENBSD-NEXT: declare float @rintf(float)
; OPENBSD-NEXT: declare double @rintl(double)
; OPENBSD-NEXT: declare double @round(double)
; OPENBSD-NEXT: declare double @roundeven(double)
; OPENBSD-NEXT: declare float @roundevenf(float)
; OPENBSD-NEXT: declare double @roundevenl(double)
; OPENBSD-NEXT: declare float @roundf(float)
; OPENBSD-NEXT: declare double @roundl(double)
; OPENBSD-NEXT: declare double @scalbln(double, i32)
; OPENBSD-NEXT: declare float @scalblnf(float, i32)
; OPENBSD-NEXT: declare double @scalblnl(double, i32)
; OPENBSD-NEXT: declare double @scalbn(double, i32)
; OPENBSD-NEXT: declare float @scalbnf(float, i32)
; OPENBSD-NEXT: declare double @scalbnl(double, i32)
; OPENBSD-NEXT: declare double @sin(double)
; OPENBSD-NEXT: declare float @sinf(float)
; OPENBSD-NEXT: declare double @sinh(double)
; OPENBSD-NEXT: declare float @sinhf(float)
; OPENBSD-NEXT: declare double @sinhl(double)
; OPENBSD-NEXT: declare double @sinl(double)
; OPENBSD-NEXT: declare nofpclass(ninf nsub nnorm) double @sqrt(double) [[SQRT_ATTRS:#[0-9]+]]
; OPENBSD-NEXT: declare nofpclass(ninf nsub nnorm) float @sqrtf(float) [[SQRT_ATTRS:#[0-9]+]]
; OPENBSD-NEXT: declare double @sqrtl(double)
; OPENBSD-NEXT: declare double @tan(double)
; OPENBSD-NEXT: declare float @tanf(float)
; OPENBSD-NEXT: declare double @tanh(double)
; OPENBSD-NEXT: declare float @tanhf(float)
; OPENBSD-NEXT: declare double @tanhl(double)
; OPENBSD-NEXT: declare double @tanl(double)
; OPENBSD-NEXT: declare double @tgamma(double)
; OPENBSD-NEXT: declare float @tgammaf(float)
; OPENBSD-NEXT: declare double @tgammal(double)
; OPENBSD-NEXT: declare double @trunc(double)
; OPENBSD-NEXT: declare float @truncf(float)
; OPENBSD-NEXT: declare double @truncl(double)
; OPENBSD-NEXT: attributes [[CALLOC_ATTRS]] = { nofree nounwind willreturn allockind("alloc") allocsize(0,1) "alloc-family"="malloc" }
; OPENBSD-NEXT: attributes [[FREE_ATTRS]] = { nounwind willreturn allockind("free") "alloc-family"="malloc" }
; OPENBSD-NEXT: attributes [[MALLOC_ATTRS]] = { nofree nounwind willreturn allockind("alloc,uninitialized") allocsize(0) "alloc-family"="malloc" }
; OPENBSD-NEXT: attributes [[SQRT_ATTRS]] = { nocallback nofree nosync nounwind willreturn memory(errnomem: write) }
