; REQUIRES: m68k-registered-target
; Strip blank lines and inline attribute comments so the declaration
; stream is contiguous and can be checked with -NEXT: no unexpected call
; can sneak in between two checked declarations.
; RUN: opt -S -passes=declare-runtime-libcalls -mtriple=m68k-unknown-linux < %s | sed '/^$/d;/^; Function Attrs:/d' | FileCheck -check-prefix=M68K %s

; M68K: declare void @_Unwind_Resume(...)
; M68K-NEXT: declare void @__adddf3(...)
; M68K-NEXT: declare void @__addsf3(...)
; M68K-NEXT: declare void @__addtf3(...)
; M68K-NEXT: declare void @__ashldi3(...)
; M68K-NEXT: declare void @__ashlhi3(...)
; M68K-NEXT: declare void @__ashlsi3(...)
; M68K-NEXT: declare void @__ashrdi3(...)
; M68K-NEXT: declare void @__ashrhi3(...)
; M68K-NEXT: declare void @__ashrsi3(...)
; M68K-NEXT: declare void @__atomic_compare_exchange(...)
; M68K-NEXT: declare void @__atomic_compare_exchange_1(...)
; M68K-NEXT: declare void @__atomic_compare_exchange_16(...)
; M68K-NEXT: declare void @__atomic_compare_exchange_2(...)
; M68K-NEXT: declare void @__atomic_compare_exchange_4(...)
; M68K-NEXT: declare void @__atomic_compare_exchange_8(...)
; M68K-NEXT: declare void @__atomic_exchange(...)
; M68K-NEXT: declare void @__atomic_exchange_1(...)
; M68K-NEXT: declare void @__atomic_exchange_16(...)
; M68K-NEXT: declare void @__atomic_exchange_2(...)
; M68K-NEXT: declare void @__atomic_exchange_4(...)
; M68K-NEXT: declare void @__atomic_exchange_8(...)
; M68K-NEXT: declare void @__atomic_fetch_add_1(...)
; M68K-NEXT: declare void @__atomic_fetch_add_16(...)
; M68K-NEXT: declare void @__atomic_fetch_add_2(...)
; M68K-NEXT: declare void @__atomic_fetch_add_4(...)
; M68K-NEXT: declare void @__atomic_fetch_add_8(...)
; M68K-NEXT: declare void @__atomic_fetch_and_1(...)
; M68K-NEXT: declare void @__atomic_fetch_and_16(...)
; M68K-NEXT: declare void @__atomic_fetch_and_2(...)
; M68K-NEXT: declare void @__atomic_fetch_and_4(...)
; M68K-NEXT: declare void @__atomic_fetch_and_8(...)
; M68K-NEXT: declare void @__atomic_fetch_nand_1(...)
; M68K-NEXT: declare void @__atomic_fetch_nand_16(...)
; M68K-NEXT: declare void @__atomic_fetch_nand_2(...)
; M68K-NEXT: declare void @__atomic_fetch_nand_4(...)
; M68K-NEXT: declare void @__atomic_fetch_nand_8(...)
; M68K-NEXT: declare void @__atomic_fetch_or_1(...)
; M68K-NEXT: declare void @__atomic_fetch_or_16(...)
; M68K-NEXT: declare void @__atomic_fetch_or_2(...)
; M68K-NEXT: declare void @__atomic_fetch_or_4(...)
; M68K-NEXT: declare void @__atomic_fetch_or_8(...)
; M68K-NEXT: declare void @__atomic_fetch_sub_1(...)
; M68K-NEXT: declare void @__atomic_fetch_sub_16(...)
; M68K-NEXT: declare void @__atomic_fetch_sub_2(...)
; M68K-NEXT: declare void @__atomic_fetch_sub_4(...)
; M68K-NEXT: declare void @__atomic_fetch_sub_8(...)
; M68K-NEXT: declare void @__atomic_fetch_xor_1(...)
; M68K-NEXT: declare void @__atomic_fetch_xor_16(...)
; M68K-NEXT: declare void @__atomic_fetch_xor_2(...)
; M68K-NEXT: declare void @__atomic_fetch_xor_4(...)
; M68K-NEXT: declare void @__atomic_fetch_xor_8(...)
; M68K-NEXT: declare void @__atomic_load(i32, ptr, ptr, i32)
; M68K-NEXT: declare void @__atomic_load_1(...)
; M68K-NEXT: declare void @__atomic_load_16(...)
; M68K-NEXT: declare void @__atomic_load_2(...)
; M68K-NEXT: declare void @__atomic_load_4(...)
; M68K-NEXT: declare void @__atomic_load_8(...)
; M68K-NEXT: declare void @__atomic_store(i32, ptr, ptr, i32)
; M68K-NEXT: declare void @__atomic_store_1(...)
; M68K-NEXT: declare void @__atomic_store_16(...)
; M68K-NEXT: declare void @__atomic_store_2(...)
; M68K-NEXT: declare void @__atomic_store_4(...)
; M68K-NEXT: declare void @__atomic_store_8(...)
; M68K-NEXT: declare void @__clear_cache(...)
; M68K-NEXT: declare void @__clzdi2(...)
; M68K-NEXT: declare void @__clzsi2(...)
; M68K-NEXT: declare void @__clzti2(...)
; M68K-NEXT: declare void @__cxa_end_cleanup(...)
; M68K-NEXT: declare void @__divdf3(...)
; M68K-NEXT: declare void @__divdi3(...)
; M68K-NEXT: declare void @__divhi3(...)
; M68K-NEXT: declare void @__divqi3(...)
; M68K-NEXT: declare void @__divsf3(...)
; M68K-NEXT: declare void @__divsi3(...)
; M68K-NEXT: declare void @__divtf3(...)
; M68K-NEXT: declare void @__divti3(...)
; M68K-NEXT: declare void @__eqdf2(...)
; M68K-NEXT: declare void @__eqsf2(...)
; M68K-NEXT: declare void @__eqtf2(...)
; M68K-NEXT: declare double @__exp2_finite(double)
; M68K-NEXT: declare float @__exp2f_finite(float)
; M68K-NEXT: declare double @__exp_finite(double)
; M68K-NEXT: declare float @__expf_finite(float)
; M68K-NEXT: declare void @__extendbfsf2(...)
; M68K-NEXT: declare void @__extenddftf2(...)
; M68K-NEXT: declare void @__extendhfdf2(...)
; M68K-NEXT: declare void @__extendhfsf2(...)
; M68K-NEXT: declare void @__extendhftf2(...)
; M68K-NEXT: declare void @__extendsfdf2(...)
; M68K-NEXT: declare void @__extendsftf2(...)
; M68K-NEXT: declare void @__fixdfdi(...)
; M68K-NEXT: declare void @__fixdfsi(...)
; M68K-NEXT: declare void @__fixdfti(...)
; M68K-NEXT: declare void @__fixhfdi(...)
; M68K-NEXT: declare void @__fixhfsi(...)
; M68K-NEXT: declare void @__fixhfti(...)
; M68K-NEXT: declare void @__fixsfdi(...)
; M68K-NEXT: declare void @__fixsfsi(...)
; M68K-NEXT: declare void @__fixsfti(...)
; M68K-NEXT: declare void @__fixtfdi(...)
; M68K-NEXT: declare void @__fixtfsi(...)
; M68K-NEXT: declare void @__fixtfti(...)
; M68K-NEXT: declare void @__fixunsdfdi(...)
; M68K-NEXT: declare void @__fixunsdfsi(...)
; M68K-NEXT: declare void @__fixunsdfti(...)
; M68K-NEXT: declare void @__fixunshfdi(...)
; M68K-NEXT: declare void @__fixunshfsi(...)
; M68K-NEXT: declare void @__fixunshfti(...)
; M68K-NEXT: declare void @__fixunssfdi(...)
; M68K-NEXT: declare void @__fixunssfsi(...)
; M68K-NEXT: declare void @__fixunssfti(...)
; M68K-NEXT: declare void @__fixunstfdi(...)
; M68K-NEXT: declare void @__fixunstfsi(...)
; M68K-NEXT: declare void @__fixunstfti(...)
; M68K-NEXT: declare void @__floatdibf(...)
; M68K-NEXT: declare void @__floatdidf(...)
; M68K-NEXT: declare void @__floatdihf(...)
; M68K-NEXT: declare void @__floatdisf(...)
; M68K-NEXT: declare void @__floatditf(...)
; M68K-NEXT: declare void @__floatsidf(...)
; M68K-NEXT: declare void @__floatsihf(...)
; M68K-NEXT: declare void @__floatsisf(...)
; M68K-NEXT: declare void @__floatsitf(...)
; M68K-NEXT: declare void @__floattidf(...)
; M68K-NEXT: declare void @__floattihf(...)
; M68K-NEXT: declare void @__floattisf(...)
; M68K-NEXT: declare void @__floattitf(...)
; M68K-NEXT: declare void @__floatundibf(...)
; M68K-NEXT: declare void @__floatundidf(...)
; M68K-NEXT: declare void @__floatundihf(...)
; M68K-NEXT: declare void @__floatundisf(...)
; M68K-NEXT: declare void @__floatunditf(...)
; M68K-NEXT: declare void @__floatunsidf(...)
; M68K-NEXT: declare void @__floatunsihf(...)
; M68K-NEXT: declare void @__floatunsisf(...)
; M68K-NEXT: declare void @__floatunsitf(...)
; M68K-NEXT: declare void @__floatuntidf(...)
; M68K-NEXT: declare void @__floatuntihf(...)
; M68K-NEXT: declare void @__floatuntisf(...)
; M68K-NEXT: declare void @__floatuntitf(...)
; M68K-NEXT: declare void @__gedf2(...)
; M68K-NEXT: declare void @__gesf2(...)
; M68K-NEXT: declare void @__getf2(...)
; M68K-NEXT: declare void @__gtdf2(...)
; M68K-NEXT: declare void @__gtsf2(...)
; M68K-NEXT: declare void @__gttf2(...)
; M68K-NEXT: declare void @__ledf2(...)
; M68K-NEXT: declare void @__lesf2(...)
; M68K-NEXT: declare void @__letf2(...)
; M68K-NEXT: declare void @__llvm_deoptimize(...)
; M68K-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_1(...)
; M68K-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_16(...)
; M68K-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_2(...)
; M68K-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_4(...)
; M68K-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_8(...)
; M68K-NEXT: declare void @__llvm_memmove_element_unordered_atomic_1(...)
; M68K-NEXT: declare void @__llvm_memmove_element_unordered_atomic_16(...)
; M68K-NEXT: declare void @__llvm_memmove_element_unordered_atomic_2(...)
; M68K-NEXT: declare void @__llvm_memmove_element_unordered_atomic_4(...)
; M68K-NEXT: declare void @__llvm_memmove_element_unordered_atomic_8(...)
; M68K-NEXT: declare void @__llvm_memset_element_unordered_atomic_1(...)
; M68K-NEXT: declare void @__llvm_memset_element_unordered_atomic_16(...)
; M68K-NEXT: declare void @__llvm_memset_element_unordered_atomic_2(...)
; M68K-NEXT: declare void @__llvm_memset_element_unordered_atomic_4(...)
; M68K-NEXT: declare void @__llvm_memset_element_unordered_atomic_8(...)
; M68K-NEXT: declare double @__log10_finite(double)
; M68K-NEXT: declare float @__log10f_finite(float)
; M68K-NEXT: declare double @__log2_finite(double)
; M68K-NEXT: declare float @__log2f_finite(float)
; M68K-NEXT: declare double @__log_finite(double)
; M68K-NEXT: declare float @__logf_finite(float)
; M68K-NEXT: declare void @__lshrdi3(...)
; M68K-NEXT: declare void @__lshrhi3(...)
; M68K-NEXT: declare void @__lshrsi3(...)
; M68K-NEXT: declare void @__ltdf2(...)
; M68K-NEXT: declare void @__ltsf2(...)
; M68K-NEXT: declare void @__lttf2(...)
; M68K-NEXT: declare ptr @__memcpy_chk(ptr, ptr, i32, i32)
; M68K-NEXT: declare ptr @__memmove_chk(ptr, ptr, i32, i32)
; M68K-NEXT: declare ptr @__memset_chk(ptr, i32, i32, i32)
; M68K-NEXT: declare void @__moddi3(...)
; M68K-NEXT: declare void @__modhi3(...)
; M68K-NEXT: declare void @__modqi3(...)
; M68K-NEXT: declare void @__modsi3(...)
; M68K-NEXT: declare void @__modti3(...)
; M68K-NEXT: declare void @__muldf3(...)
; M68K-NEXT: declare void @__muldi3(...)
; M68K-NEXT: declare void @__mulhi3(...)
; M68K-NEXT: declare void @__mulosi4(...)
; M68K-NEXT: declare void @__mulqi3(...)
; M68K-NEXT: declare void @__mulsf3(...)
; M68K-NEXT: declare void @__mulsi3(...)
; M68K-NEXT: declare void @__multf3(...)
; M68K-NEXT: declare void @__nedf2(...)
; M68K-NEXT: declare void @__negdi2(...)
; M68K-NEXT: declare void @__negsi2(...)
; M68K-NEXT: declare void @__nesf2(...)
; M68K-NEXT: declare void @__netf2(...)
; M68K-NEXT: declare void @__popcountdi2(...)
; M68K-NEXT: declare void @__popcountsi2(...)
; M68K-NEXT: declare void @__popcountti2(...)
; M68K-NEXT: declare double @__pow_finite(double, double)
; M68K-NEXT: declare float @__powf_finite(float, float)
; M68K-NEXT: declare void @__powidf2(...)
; M68K-NEXT: declare void @__powisf2(...)
; M68K-NEXT: declare void @__powitf2(...)
; M68K-NEXT: declare void @__safestack_unsafe_stack_ptr(...)
; M68K-NEXT: declare void @__stack_chk_fail(...)
; M68K-NEXT: declare void @__stack_chk_guard(...)
; M68K-NEXT: declare void @__subdf3(...)
; M68K-NEXT: declare void @__subsf3(...)
; M68K-NEXT: declare void @__subtf3(...)
; M68K-NEXT: declare void @__sync_fetch_and_add_1(...)
; M68K-NEXT: declare void @__sync_fetch_and_add_16(...)
; M68K-NEXT: declare void @__sync_fetch_and_add_2(...)
; M68K-NEXT: declare void @__sync_fetch_and_add_4(...)
; M68K-NEXT: declare void @__sync_fetch_and_add_8(...)
; M68K-NEXT: declare void @__sync_fetch_and_and_1(...)
; M68K-NEXT: declare void @__sync_fetch_and_and_16(...)
; M68K-NEXT: declare void @__sync_fetch_and_and_2(...)
; M68K-NEXT: declare void @__sync_fetch_and_and_4(...)
; M68K-NEXT: declare void @__sync_fetch_and_and_8(...)
; M68K-NEXT: declare void @__sync_fetch_and_max_1(...)
; M68K-NEXT: declare void @__sync_fetch_and_max_16(...)
; M68K-NEXT: declare void @__sync_fetch_and_max_2(...)
; M68K-NEXT: declare void @__sync_fetch_and_max_4(...)
; M68K-NEXT: declare void @__sync_fetch_and_max_8(...)
; M68K-NEXT: declare void @__sync_fetch_and_min_1(...)
; M68K-NEXT: declare void @__sync_fetch_and_min_16(...)
; M68K-NEXT: declare void @__sync_fetch_and_min_2(...)
; M68K-NEXT: declare void @__sync_fetch_and_min_4(...)
; M68K-NEXT: declare void @__sync_fetch_and_min_8(...)
; M68K-NEXT: declare void @__sync_fetch_and_nand_1(...)
; M68K-NEXT: declare void @__sync_fetch_and_nand_16(...)
; M68K-NEXT: declare void @__sync_fetch_and_nand_2(...)
; M68K-NEXT: declare void @__sync_fetch_and_nand_4(...)
; M68K-NEXT: declare void @__sync_fetch_and_nand_8(...)
; M68K-NEXT: declare void @__sync_fetch_and_or_1(...)
; M68K-NEXT: declare void @__sync_fetch_and_or_16(...)
; M68K-NEXT: declare void @__sync_fetch_and_or_2(...)
; M68K-NEXT: declare void @__sync_fetch_and_or_4(...)
; M68K-NEXT: declare void @__sync_fetch_and_or_8(...)
; M68K-NEXT: declare void @__sync_fetch_and_sub_1(...)
; M68K-NEXT: declare void @__sync_fetch_and_sub_16(...)
; M68K-NEXT: declare void @__sync_fetch_and_sub_2(...)
; M68K-NEXT: declare void @__sync_fetch_and_sub_4(...)
; M68K-NEXT: declare void @__sync_fetch_and_sub_8(...)
; M68K-NEXT: declare void @__sync_fetch_and_umax_1(...)
; M68K-NEXT: declare void @__sync_fetch_and_umax_16(...)
; M68K-NEXT: declare void @__sync_fetch_and_umax_2(...)
; M68K-NEXT: declare void @__sync_fetch_and_umax_4(...)
; M68K-NEXT: declare void @__sync_fetch_and_umax_8(...)
; M68K-NEXT: declare void @__sync_fetch_and_umin_1(...)
; M68K-NEXT: declare void @__sync_fetch_and_umin_16(...)
; M68K-NEXT: declare void @__sync_fetch_and_umin_2(...)
; M68K-NEXT: declare void @__sync_fetch_and_umin_4(...)
; M68K-NEXT: declare void @__sync_fetch_and_umin_8(...)
; M68K-NEXT: declare void @__sync_fetch_and_xor_1(...)
; M68K-NEXT: declare void @__sync_fetch_and_xor_16(...)
; M68K-NEXT: declare void @__sync_fetch_and_xor_2(...)
; M68K-NEXT: declare void @__sync_fetch_and_xor_4(...)
; M68K-NEXT: declare void @__sync_fetch_and_xor_8(...)
; M68K-NEXT: declare void @__sync_lock_test_and_set_1(...)
; M68K-NEXT: declare void @__sync_lock_test_and_set_16(...)
; M68K-NEXT: declare void @__sync_lock_test_and_set_2(...)
; M68K-NEXT: declare void @__sync_lock_test_and_set_4(...)
; M68K-NEXT: declare void @__sync_lock_test_and_set_8(...)
; M68K-NEXT: declare void @__sync_val_compare_and_swap_1(...)
; M68K-NEXT: declare void @__sync_val_compare_and_swap_16(...)
; M68K-NEXT: declare void @__sync_val_compare_and_swap_2(...)
; M68K-NEXT: declare void @__sync_val_compare_and_swap_4(...)
; M68K-NEXT: declare void @__sync_val_compare_and_swap_8(...)
; M68K-NEXT: declare void @__truncdfbf2(...)
; M68K-NEXT: declare void @__truncdfhf2(...)
; M68K-NEXT: declare void @__truncdfsf2(...)
; M68K-NEXT: declare void @__truncsfbf2(...)
; M68K-NEXT: declare void @__truncsfhf2(...)
; M68K-NEXT: declare void @__trunctfbf2(...)
; M68K-NEXT: declare void @__trunctfdf2(...)
; M68K-NEXT: declare void @__trunctfhf2(...)
; M68K-NEXT: declare void @__trunctfsf2(...)
; M68K-NEXT: declare void @__udivdi3(...)
; M68K-NEXT: declare void @__udivhi3(...)
; M68K-NEXT: declare void @__udivqi3(...)
; M68K-NEXT: declare void @__udivsi3(...)
; M68K-NEXT: declare void @__udivti3(...)
; M68K-NEXT: declare void @__umoddi3(...)
; M68K-NEXT: declare void @__umodhi3(...)
; M68K-NEXT: declare void @__umodqi3(...)
; M68K-NEXT: declare void @__umodsi3(...)
; M68K-NEXT: declare void @__umodti3(...)
; M68K-NEXT: declare void @__unorddf2(...)
; M68K-NEXT: declare void @__unordsf2(...)
; M68K-NEXT: declare void @__unordtf2(...)
; M68K-NEXT: declare double @acos(double)
; M68K-NEXT: declare float @acosf(float)
; M68K-NEXT: declare double @asin(double)
; M68K-NEXT: declare float @asinf(float)
; M68K-NEXT: declare double @atan(double)
; M68K-NEXT: declare double @atan2(double, double)
; M68K-NEXT: declare float @atan2f(float, float)
; M68K-NEXT: declare float @atanf(float)
; M68K-NEXT: declare void @cabs(...)
; M68K-NEXT: declare void @cabsf(...)
; M68K-NEXT: declare noalias noundef ptr @calloc(i32 noundef, i32 noundef) [[CALLOC_ATTRS:#[0-9]+]]
; M68K-NEXT: declare double @cbrt(double)
; M68K-NEXT: declare float @cbrtf(float)
; M68K-NEXT: declare double @ceil(double)
; M68K-NEXT: declare float @ceilf(float)
; M68K-NEXT: declare double @copysign(double, double)
; M68K-NEXT: declare float @copysignf(float, float)
; M68K-NEXT: declare double @cos(double)
; M68K-NEXT: declare float @cosf(float)
; M68K-NEXT: declare double @cosh(double)
; M68K-NEXT: declare float @coshf(float)
; M68K-NEXT: declare double @exp(double)
; M68K-NEXT: declare double @exp10(double)
; M68K-NEXT: declare float @exp10f(float)
; M68K-NEXT: declare double @exp2(double)
; M68K-NEXT: declare float @exp2f(float)
; M68K-NEXT: declare float @expf(float)
; M68K-NEXT: declare double @fdim(double, double)
; M68K-NEXT: declare float @fdimf(float, float)
; M68K-NEXT: declare void @fegetenv(...)
; M68K-NEXT: declare void @fegetmode(...)
; M68K-NEXT: declare void @fesetenv(...)
; M68K-NEXT: declare void @fesetmode(...)
; M68K-NEXT: declare double @floor(double)
; M68K-NEXT: declare float @floorf(float)
; M68K-NEXT: declare void @fma(...)
; M68K-NEXT: declare void @fmaf(...)
; M68K-NEXT: declare float @fmax(float, float)
; M68K-NEXT: declare float @fmaxf(float, float)
; M68K-NEXT: declare void @fmaximum(...)
; M68K-NEXT: declare float @fmaximum_num(float, float)
; M68K-NEXT: declare float @fmaximum_numf(float, float)
; M68K-NEXT: declare void @fmaximumf(...)
; M68K-NEXT: declare float @fmin(float, float)
; M68K-NEXT: declare float @fminf(float, float)
; M68K-NEXT: declare void @fminimum(...)
; M68K-NEXT: declare float @fminimum_num(float, float)
; M68K-NEXT: declare float @fminimum_numf(float, float)
; M68K-NEXT: declare void @fminimumf(...)
; M68K-NEXT: declare double @fmod(double, double)
; M68K-NEXT: declare float @fmodf(float, float)
; M68K-NEXT: declare void @free(ptr allocptr noundef captures(none)) [[FREE_ATTRS:#[0-9]+]]
; M68K-NEXT: declare double @frexp(double, ptr)
; M68K-NEXT: declare float @frexpf(float, ptr)
; M68K-NEXT: declare double @ldexp(double, i32)
; M68K-NEXT: declare float @ldexpf(float, i32)
; M68K-NEXT: declare void @llrint(...)
; M68K-NEXT: declare void @llrintf(...)
; M68K-NEXT: declare void @llround(...)
; M68K-NEXT: declare void @llroundf(...)
; M68K-NEXT: declare double @log(double)
; M68K-NEXT: declare double @log10(double)
; M68K-NEXT: declare float @log10f(float)
; M68K-NEXT: declare double @log2(double)
; M68K-NEXT: declare float @log2f(float)
; M68K-NEXT: declare float @logf(float)
; M68K-NEXT: declare void @lrint(...)
; M68K-NEXT: declare void @lrintf(...)
; M68K-NEXT: declare void @lround(...)
; M68K-NEXT: declare void @lroundf(...)
; M68K-NEXT: declare noalias noundef ptr @malloc(i32 noundef) [[MALLOC_ATTRS:#[0-9]+]]
; M68K-NEXT: declare ptr @memcpy(ptr, ptr, i32)
; M68K-NEXT: declare ptr @memmove(ptr, ptr, i32)
; M68K-NEXT: declare ptr @memset(ptr, i32, i32)
; M68K-NEXT: declare double @modf(double, ptr)
; M68K-NEXT: declare float @modff(float, ptr)
; M68K-NEXT: declare double @nan(ptr)
; M68K-NEXT: declare float @nanf(ptr)
; M68K-NEXT: declare double @nearbyint(double)
; M68K-NEXT: declare float @nearbyintf(float)
; M68K-NEXT: declare double @nexttoward(double, double)
; M68K-NEXT: declare float @nexttowardf(float, double)
; M68K-NEXT: declare double @pow(double, double)
; M68K-NEXT: declare float @powf(float, float)
; M68K-NEXT: declare double @remainder(double, double)
; M68K-NEXT: declare float @remainderf(float, float)
; M68K-NEXT: declare double @remquo(double, double, ptr)
; M68K-NEXT: declare float @remquof(float, float, ptr)
; M68K-NEXT: declare double @rint(double)
; M68K-NEXT: declare float @rintf(float)
; M68K-NEXT: declare double @round(double)
; M68K-NEXT: declare double @roundeven(double)
; M68K-NEXT: declare float @roundevenf(float)
; M68K-NEXT: declare float @roundf(float)
; M68K-NEXT: declare double @scalbln(double, i32)
; M68K-NEXT: declare float @scalblnf(float, i32)
; M68K-NEXT: declare double @scalbn(double, i32)
; M68K-NEXT: declare float @scalbnf(float, i32)
; M68K-NEXT: declare double @sin(double)
; M68K-NEXT: declare float @sinf(float)
; M68K-NEXT: declare double @sinh(double)
; M68K-NEXT: declare float @sinhf(float)
; M68K-NEXT: declare nofpclass(ninf nsub nnorm) double @sqrt(double) [[SQRT_ATTRS:#[0-9]+]]
; M68K-NEXT: declare nofpclass(ninf nsub nnorm) float @sqrtf(float) [[SQRT_ATTRS:#[0-9]+]]
; M68K-NEXT: declare double @tan(double)
; M68K-NEXT: declare float @tanf(float)
; M68K-NEXT: declare double @tanh(double)
; M68K-NEXT: declare float @tanhf(float)
; M68K-NEXT: declare double @tgamma(double)
; M68K-NEXT: declare float @tgammaf(float)
; M68K-NEXT: declare double @trunc(double)
; M68K-NEXT: declare float @truncf(float)
; M68K-NEXT: attributes [[CALLOC_ATTRS]] = { nofree nounwind willreturn allockind("alloc") allocsize(0,1) "alloc-family"="malloc" }
; M68K-NEXT: attributes [[FREE_ATTRS]] = { nounwind willreturn allockind("free") "alloc-family"="malloc" }
; M68K-NEXT: attributes [[MALLOC_ATTRS]] = { nofree nounwind willreturn allockind("alloc,uninitialized") allocsize(0) "alloc-family"="malloc" }
; M68K-NEXT: attributes [[SQRT_ATTRS]] = { nocallback nofree nosync nounwind willreturn memory(errnomem: write) }
