; REQUIRES: systemz-registered-target
; Strip blank lines and inline attribute comments so the declaration stream is
; contiguous and can be checked with -NEXT (no call can sneak in unnoticed).
; RUN: opt -S -passes=declare-runtime-libcalls -mtriple=s390x-unknown-linux-gnu < %s | sed '/^$/d;/^; Function Attrs:/d' | FileCheck -check-prefix=LINUX %s
; RUN: opt -S -passes=declare-runtime-libcalls -mtriple=s390x-ibm-zos < %s | sed '/^$/d;/^; Function Attrs:/d' | FileCheck -check-prefix=ZOS %s

; LINUX: declare void @_Unwind_Resume(...)
; LINUX-NEXT: declare void @__adddf3(...)
; LINUX-NEXT: declare void @__addsf3(...)
; LINUX-NEXT: declare void @__addtf3(...)
; LINUX-NEXT: declare void @__ashldi3(...)
; LINUX-NEXT: declare void @__ashlhi3(...)
; LINUX-NEXT: declare void @__ashlsi3(...)
; LINUX-NEXT: declare void @__ashlti3(...)
; LINUX-NEXT: declare void @__ashrdi3(...)
; LINUX-NEXT: declare void @__ashrhi3(...)
; LINUX-NEXT: declare void @__ashrsi3(...)
; LINUX-NEXT: declare void @__ashrti3(...)
; LINUX-NEXT: declare void @__atomic_compare_exchange(...)
; LINUX-NEXT: declare void @__atomic_compare_exchange_1(...)
; LINUX-NEXT: declare void @__atomic_compare_exchange_16(...)
; LINUX-NEXT: declare void @__atomic_compare_exchange_2(...)
; LINUX-NEXT: declare void @__atomic_compare_exchange_4(...)
; LINUX-NEXT: declare void @__atomic_compare_exchange_8(...)
; LINUX-NEXT: declare void @__atomic_exchange(...)
; LINUX-NEXT: declare void @__atomic_exchange_1(...)
; LINUX-NEXT: declare void @__atomic_exchange_16(...)
; LINUX-NEXT: declare void @__atomic_exchange_2(...)
; LINUX-NEXT: declare void @__atomic_exchange_4(...)
; LINUX-NEXT: declare void @__atomic_exchange_8(...)
; LINUX-NEXT: declare void @__atomic_fetch_add_1(...)
; LINUX-NEXT: declare void @__atomic_fetch_add_16(...)
; LINUX-NEXT: declare void @__atomic_fetch_add_2(...)
; LINUX-NEXT: declare void @__atomic_fetch_add_4(...)
; LINUX-NEXT: declare void @__atomic_fetch_add_8(...)
; LINUX-NEXT: declare void @__atomic_fetch_and_1(...)
; LINUX-NEXT: declare void @__atomic_fetch_and_16(...)
; LINUX-NEXT: declare void @__atomic_fetch_and_2(...)
; LINUX-NEXT: declare void @__atomic_fetch_and_4(...)
; LINUX-NEXT: declare void @__atomic_fetch_and_8(...)
; LINUX-NEXT: declare void @__atomic_fetch_nand_1(...)
; LINUX-NEXT: declare void @__atomic_fetch_nand_16(...)
; LINUX-NEXT: declare void @__atomic_fetch_nand_2(...)
; LINUX-NEXT: declare void @__atomic_fetch_nand_4(...)
; LINUX-NEXT: declare void @__atomic_fetch_nand_8(...)
; LINUX-NEXT: declare void @__atomic_fetch_or_1(...)
; LINUX-NEXT: declare void @__atomic_fetch_or_16(...)
; LINUX-NEXT: declare void @__atomic_fetch_or_2(...)
; LINUX-NEXT: declare void @__atomic_fetch_or_4(...)
; LINUX-NEXT: declare void @__atomic_fetch_or_8(...)
; LINUX-NEXT: declare void @__atomic_fetch_sub_1(...)
; LINUX-NEXT: declare void @__atomic_fetch_sub_16(...)
; LINUX-NEXT: declare void @__atomic_fetch_sub_2(...)
; LINUX-NEXT: declare void @__atomic_fetch_sub_4(...)
; LINUX-NEXT: declare void @__atomic_fetch_sub_8(...)
; LINUX-NEXT: declare void @__atomic_fetch_xor_1(...)
; LINUX-NEXT: declare void @__atomic_fetch_xor_16(...)
; LINUX-NEXT: declare void @__atomic_fetch_xor_2(...)
; LINUX-NEXT: declare void @__atomic_fetch_xor_4(...)
; LINUX-NEXT: declare void @__atomic_fetch_xor_8(...)
; LINUX-NEXT: declare void @__atomic_load(i64, ptr, ptr, i32)
; LINUX-NEXT: declare void @__atomic_load_1(...)
; LINUX-NEXT: declare void @__atomic_load_16(...)
; LINUX-NEXT: declare void @__atomic_load_2(...)
; LINUX-NEXT: declare void @__atomic_load_4(...)
; LINUX-NEXT: declare void @__atomic_load_8(...)
; LINUX-NEXT: declare void @__atomic_store(i64, ptr, ptr, i32)
; LINUX-NEXT: declare void @__atomic_store_1(...)
; LINUX-NEXT: declare void @__atomic_store_16(...)
; LINUX-NEXT: declare void @__atomic_store_2(...)
; LINUX-NEXT: declare void @__atomic_store_4(...)
; LINUX-NEXT: declare void @__atomic_store_8(...)
; LINUX-NEXT: declare void @__clear_cache(...)
; LINUX-NEXT: declare void @__clzdi2(...)
; LINUX-NEXT: declare void @__clzsi2(...)
; LINUX-NEXT: declare void @__clzti2(...)
; LINUX-NEXT: declare void @__cxa_end_cleanup(...)
; LINUX-NEXT: declare void @__divdf3(...)
; LINUX-NEXT: declare void @__divdi3(...)
; LINUX-NEXT: declare void @__divhi3(...)
; LINUX-NEXT: declare void @__divqi3(...)
; LINUX-NEXT: declare void @__divsf3(...)
; LINUX-NEXT: declare void @__divsi3(...)
; LINUX-NEXT: declare void @__divtf3(...)
; LINUX-NEXT: declare void @__divti3(...)
; LINUX-NEXT: declare void @__eqdf2(...)
; LINUX-NEXT: declare void @__eqsf2(...)
; LINUX-NEXT: declare void @__eqtf2(...)
; LINUX-NEXT: declare double @__exp2_finite(double)
; LINUX-NEXT: declare float @__exp2f_finite(float)
; LINUX-NEXT: declare double @__exp2l_finite(double)
; LINUX-NEXT: declare double @__exp_finite(double)
; LINUX-NEXT: declare float @__expf_finite(float)
; LINUX-NEXT: declare double @__expl_finite(double)
; LINUX-NEXT: declare void @__extendbfsf2(...)
; LINUX-NEXT: declare void @__extenddftf2(...)
; LINUX-NEXT: declare void @__extendhfdf2(...)
; LINUX-NEXT: declare void @__extendhfsf2(...)
; LINUX-NEXT: declare void @__extendhftf2(...)
; LINUX-NEXT: declare void @__extendsfdf2(...)
; LINUX-NEXT: declare void @__extendsftf2(...)
; LINUX-NEXT: declare void @__fixdfdi(...)
; LINUX-NEXT: declare void @__fixdfsi(...)
; LINUX-NEXT: declare void @__fixdfti(...)
; LINUX-NEXT: declare void @__fixhfdi(...)
; LINUX-NEXT: declare void @__fixhfsi(...)
; LINUX-NEXT: declare void @__fixhfti(...)
; LINUX-NEXT: declare void @__fixsfdi(...)
; LINUX-NEXT: declare void @__fixsfsi(...)
; LINUX-NEXT: declare void @__fixsfti(...)
; LINUX-NEXT: declare void @__fixtfdi(...)
; LINUX-NEXT: declare void @__fixtfsi(...)
; LINUX-NEXT: declare void @__fixtfti(...)
; LINUX-NEXT: declare void @__fixunsdfdi(...)
; LINUX-NEXT: declare void @__fixunsdfsi(...)
; LINUX-NEXT: declare void @__fixunsdfti(...)
; LINUX-NEXT: declare void @__fixunshfdi(...)
; LINUX-NEXT: declare void @__fixunshfsi(...)
; LINUX-NEXT: declare void @__fixunshfti(...)
; LINUX-NEXT: declare void @__fixunssfdi(...)
; LINUX-NEXT: declare void @__fixunssfsi(...)
; LINUX-NEXT: declare void @__fixunssfti(...)
; LINUX-NEXT: declare void @__fixunstfdi(...)
; LINUX-NEXT: declare void @__fixunstfsi(...)
; LINUX-NEXT: declare void @__fixunstfti(...)
; LINUX-NEXT: declare void @__floatdibf(...)
; LINUX-NEXT: declare void @__floatdidf(...)
; LINUX-NEXT: declare void @__floatdihf(...)
; LINUX-NEXT: declare void @__floatdisf(...)
; LINUX-NEXT: declare void @__floatditf(...)
; LINUX-NEXT: declare void @__floatsidf(...)
; LINUX-NEXT: declare void @__floatsihf(...)
; LINUX-NEXT: declare void @__floatsisf(...)
; LINUX-NEXT: declare void @__floatsitf(...)
; LINUX-NEXT: declare void @__floattidf(...)
; LINUX-NEXT: declare void @__floattihf(...)
; LINUX-NEXT: declare void @__floattisf(...)
; LINUX-NEXT: declare void @__floattitf(...)
; LINUX-NEXT: declare void @__floatundibf(...)
; LINUX-NEXT: declare void @__floatundidf(...)
; LINUX-NEXT: declare void @__floatundihf(...)
; LINUX-NEXT: declare void @__floatundisf(...)
; LINUX-NEXT: declare void @__floatunditf(...)
; LINUX-NEXT: declare void @__floatunsidf(...)
; LINUX-NEXT: declare void @__floatunsihf(...)
; LINUX-NEXT: declare void @__floatunsisf(...)
; LINUX-NEXT: declare void @__floatunsitf(...)
; LINUX-NEXT: declare void @__floatuntidf(...)
; LINUX-NEXT: declare void @__floatuntihf(...)
; LINUX-NEXT: declare void @__floatuntisf(...)
; LINUX-NEXT: declare void @__floatuntitf(...)
; LINUX-NEXT: declare void @__gedf2(...)
; LINUX-NEXT: declare void @__gesf2(...)
; LINUX-NEXT: declare void @__getf2(...)
; LINUX-NEXT: declare void @__gtdf2(...)
; LINUX-NEXT: declare void @__gtsf2(...)
; LINUX-NEXT: declare void @__gttf2(...)
; LINUX-NEXT: declare void @__ledf2(...)
; LINUX-NEXT: declare void @__lesf2(...)
; LINUX-NEXT: declare void @__letf2(...)
; LINUX-NEXT: declare void @__llvm_deoptimize(...)
; LINUX-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_1(...)
; LINUX-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_16(...)
; LINUX-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_2(...)
; LINUX-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_4(...)
; LINUX-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_8(...)
; LINUX-NEXT: declare void @__llvm_memmove_element_unordered_atomic_1(...)
; LINUX-NEXT: declare void @__llvm_memmove_element_unordered_atomic_16(...)
; LINUX-NEXT: declare void @__llvm_memmove_element_unordered_atomic_2(...)
; LINUX-NEXT: declare void @__llvm_memmove_element_unordered_atomic_4(...)
; LINUX-NEXT: declare void @__llvm_memmove_element_unordered_atomic_8(...)
; LINUX-NEXT: declare void @__llvm_memset_element_unordered_atomic_1(...)
; LINUX-NEXT: declare void @__llvm_memset_element_unordered_atomic_16(...)
; LINUX-NEXT: declare void @__llvm_memset_element_unordered_atomic_2(...)
; LINUX-NEXT: declare void @__llvm_memset_element_unordered_atomic_4(...)
; LINUX-NEXT: declare void @__llvm_memset_element_unordered_atomic_8(...)
; LINUX-NEXT: declare double @__log10_finite(double)
; LINUX-NEXT: declare float @__log10f_finite(float)
; LINUX-NEXT: declare double @__log10l_finite(double)
; LINUX-NEXT: declare double @__log2_finite(double)
; LINUX-NEXT: declare float @__log2f_finite(float)
; LINUX-NEXT: declare double @__log2l_finite(double)
; LINUX-NEXT: declare double @__log_finite(double)
; LINUX-NEXT: declare float @__logf_finite(float)
; LINUX-NEXT: declare double @__logl_finite(double)
; LINUX-NEXT: declare void @__lshrdi3(...)
; LINUX-NEXT: declare void @__lshrhi3(...)
; LINUX-NEXT: declare void @__lshrsi3(...)
; LINUX-NEXT: declare void @__lshrti3(...)
; LINUX-NEXT: declare void @__ltdf2(...)
; LINUX-NEXT: declare void @__ltsf2(...)
; LINUX-NEXT: declare void @__lttf2(...)
; LINUX-NEXT: declare ptr @__memcpy_chk(ptr, ptr, i64, i64)
; LINUX-NEXT: declare ptr @__memmove_chk(ptr, ptr, i64, i64)
; LINUX-NEXT: declare ptr @__memset_chk(ptr, i32, i64, i64)
; LINUX-NEXT: declare void @__moddi3(...)
; LINUX-NEXT: declare void @__modhi3(...)
; LINUX-NEXT: declare void @__modqi3(...)
; LINUX-NEXT: declare void @__modsi3(...)
; LINUX-NEXT: declare void @__modti3(...)
; LINUX-NEXT: declare void @__muldf3(...)
; LINUX-NEXT: declare void @__muldi3(...)
; LINUX-NEXT: declare void @__mulhi3(...)
; LINUX-NEXT: declare void @__mulosi4(...)
; LINUX-NEXT: declare void @__mulqi3(...)
; LINUX-NEXT: declare void @__mulsf3(...)
; LINUX-NEXT: declare void @__mulsi3(...)
; LINUX-NEXT: declare void @__multf3(...)
; LINUX-NEXT: declare void @__multi3(...)
; LINUX-NEXT: declare void @__nedf2(...)
; LINUX-NEXT: declare void @__negdi2(...)
; LINUX-NEXT: declare void @__negsi2(...)
; LINUX-NEXT: declare void @__nesf2(...)
; LINUX-NEXT: declare void @__netf2(...)
; LINUX-NEXT: declare void @__popcountdi2(...)
; LINUX-NEXT: declare void @__popcountsi2(...)
; LINUX-NEXT: declare void @__popcountti2(...)
; LINUX-NEXT: declare double @__pow_finite(double, double)
; LINUX-NEXT: declare float @__powf_finite(float, float)
; LINUX-NEXT: declare void @__powidf2(...)
; LINUX-NEXT: declare void @__powisf2(...)
; LINUX-NEXT: declare void @__powitf2(...)
; LINUX-NEXT: declare double @__powl_finite(double, double)
; LINUX-NEXT: declare void @__safestack_unsafe_stack_ptr(...)
; LINUX-NEXT: declare void @__stack_chk_fail(...)
; LINUX-NEXT: declare void @__stack_chk_guard(...)
; LINUX-NEXT: declare void @__subdf3(...)
; LINUX-NEXT: declare void @__subsf3(...)
; LINUX-NEXT: declare void @__subtf3(...)
; LINUX-NEXT: declare void @__sync_fetch_and_add_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_add_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_add_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_add_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_add_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_and_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_and_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_and_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_and_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_and_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_max_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_max_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_max_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_max_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_max_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_min_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_min_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_min_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_min_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_min_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_nand_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_nand_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_nand_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_nand_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_nand_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_or_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_or_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_or_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_or_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_or_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_sub_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_sub_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_sub_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_sub_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_sub_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umax_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umax_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umax_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umax_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umax_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umin_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umin_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umin_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umin_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_umin_8(...)
; LINUX-NEXT: declare void @__sync_fetch_and_xor_1(...)
; LINUX-NEXT: declare void @__sync_fetch_and_xor_16(...)
; LINUX-NEXT: declare void @__sync_fetch_and_xor_2(...)
; LINUX-NEXT: declare void @__sync_fetch_and_xor_4(...)
; LINUX-NEXT: declare void @__sync_fetch_and_xor_8(...)
; LINUX-NEXT: declare void @__sync_lock_test_and_set_1(...)
; LINUX-NEXT: declare void @__sync_lock_test_and_set_16(...)
; LINUX-NEXT: declare void @__sync_lock_test_and_set_2(...)
; LINUX-NEXT: declare void @__sync_lock_test_and_set_4(...)
; LINUX-NEXT: declare void @__sync_lock_test_and_set_8(...)
; LINUX-NEXT: declare void @__sync_val_compare_and_swap_1(...)
; LINUX-NEXT: declare void @__sync_val_compare_and_swap_16(...)
; LINUX-NEXT: declare void @__sync_val_compare_and_swap_2(...)
; LINUX-NEXT: declare void @__sync_val_compare_and_swap_4(...)
; LINUX-NEXT: declare void @__sync_val_compare_and_swap_8(...)
; LINUX-NEXT: declare void @__truncdfbf2(...)
; LINUX-NEXT: declare void @__truncdfhf2(...)
; LINUX-NEXT: declare void @__truncdfsf2(...)
; LINUX-NEXT: declare void @__truncsfbf2(...)
; LINUX-NEXT: declare void @__truncsfhf2(...)
; LINUX-NEXT: declare void @__trunctfbf2(...)
; LINUX-NEXT: declare void @__trunctfdf2(...)
; LINUX-NEXT: declare void @__trunctfhf2(...)
; LINUX-NEXT: declare void @__trunctfsf2(...)
; LINUX-NEXT: declare void @__udivdi3(...)
; LINUX-NEXT: declare void @__udivhi3(...)
; LINUX-NEXT: declare void @__udivqi3(...)
; LINUX-NEXT: declare void @__udivsi3(...)
; LINUX-NEXT: declare void @__udivti3(...)
; LINUX-NEXT: declare void @__umoddi3(...)
; LINUX-NEXT: declare void @__umodhi3(...)
; LINUX-NEXT: declare void @__umodqi3(...)
; LINUX-NEXT: declare void @__umodsi3(...)
; LINUX-NEXT: declare void @__umodti3(...)
; LINUX-NEXT: declare void @__unorddf2(...)
; LINUX-NEXT: declare void @__unordsf2(...)
; LINUX-NEXT: declare void @__unordtf2(...)
; LINUX-NEXT: declare double @acos(double)
; LINUX-NEXT: declare float @acosf(float)
; LINUX-NEXT: declare double @acosl(double)
; LINUX-NEXT: declare double @asin(double)
; LINUX-NEXT: declare float @asinf(float)
; LINUX-NEXT: declare double @asinl(double)
; LINUX-NEXT: declare double @atan(double)
; LINUX-NEXT: declare double @atan2(double, double)
; LINUX-NEXT: declare float @atan2f(float, float)
; LINUX-NEXT: declare double @atan2l(double, double)
; LINUX-NEXT: declare float @atanf(float)
; LINUX-NEXT: declare double @atanl(double)
; LINUX-NEXT: declare void @cabs(...)
; LINUX-NEXT: declare void @cabsf(...)
; LINUX-NEXT: declare void @cabsl(...)
; LINUX-NEXT: declare noalias noundef ptr @calloc(i64 noundef, i64 noundef) [[CALLOC_ATTRS:#[0-9]+]]
; LINUX-NEXT: declare double @cbrt(double)
; LINUX-NEXT: declare float @cbrtf(float)
; LINUX-NEXT: declare double @cbrtl(double)
; LINUX-NEXT: declare double @ceil(double)
; LINUX-NEXT: declare float @ceilf(float)
; LINUX-NEXT: declare double @ceill(double)
; LINUX-NEXT: declare double @copysign(double, double)
; LINUX-NEXT: declare float @copysignf(float, float)
; LINUX-NEXT: declare double @copysignl(double, double)
; LINUX-NEXT: declare double @cos(double)
; LINUX-NEXT: declare float @cosf(float)
; LINUX-NEXT: declare double @cosh(double)
; LINUX-NEXT: declare float @coshf(float)
; LINUX-NEXT: declare double @coshl(double)
; LINUX-NEXT: declare double @cosl(double)
; LINUX-NEXT: declare double @exp(double)
; LINUX-NEXT: declare double @exp10(double)
; LINUX-NEXT: declare float @exp10f(float)
; LINUX-NEXT: declare double @exp10l(double)
; LINUX-NEXT: declare double @exp2(double)
; LINUX-NEXT: declare float @exp2f(float)
; LINUX-NEXT: declare double @exp2l(double)
; LINUX-NEXT: declare float @expf(float)
; LINUX-NEXT: declare double @expl(double)
; LINUX-NEXT: declare double @fdim(double, double)
; LINUX-NEXT: declare float @fdimf(float, float)
; LINUX-NEXT: declare double @fdiml(double, double)
; LINUX-NEXT: declare void @fegetenv(...)
; LINUX-NEXT: declare void @fegetmode(...)
; LINUX-NEXT: declare void @fesetenv(...)
; LINUX-NEXT: declare void @fesetmode(...)
; LINUX-NEXT: declare double @floor(double)
; LINUX-NEXT: declare float @floorf(float)
; LINUX-NEXT: declare double @floorl(double)
; LINUX-NEXT: declare void @fma(...)
; LINUX-NEXT: declare void @fmaf(...)
; LINUX-NEXT: declare void @fmal(...)
; LINUX-NEXT: declare float @fmax(float, float)
; LINUX-NEXT: declare float @fmaxf(float, float)
; LINUX-NEXT: declare void @fmaximum(...)
; LINUX-NEXT: declare float @fmaximum_num(float, float)
; LINUX-NEXT: declare float @fmaximum_numf(float, float)
; LINUX-NEXT: declare float @fmaximum_numl(float, float)
; LINUX-NEXT: declare void @fmaximumf(...)
; LINUX-NEXT: declare void @fmaximuml(...)
; LINUX-NEXT: declare float @fmaxl(float, float)
; LINUX-NEXT: declare float @fmin(float, float)
; LINUX-NEXT: declare float @fminf(float, float)
; LINUX-NEXT: declare void @fminimum(...)
; LINUX-NEXT: declare float @fminimum_num(float, float)
; LINUX-NEXT: declare float @fminimum_numf(float, float)
; LINUX-NEXT: declare float @fminimum_numl(float, float)
; LINUX-NEXT: declare void @fminimumf(...)
; LINUX-NEXT: declare void @fminimuml(...)
; LINUX-NEXT: declare float @fminl(float, float)
; LINUX-NEXT: declare double @fmod(double, double)
; LINUX-NEXT: declare float @fmodf(float, float)
; LINUX-NEXT: declare double @fmodl(double, double)
; LINUX-NEXT: declare void @free(ptr allocptr noundef captures(none)) [[FREE_ATTRS:#[0-9]+]]
; LINUX-NEXT: declare double @frexp(double, ptr)
; LINUX-NEXT: declare float @frexpf(float, ptr)
; LINUX-NEXT: declare double @frexpl(double, ptr)
; LINUX-NEXT: declare double @ldexp(double, i32)
; LINUX-NEXT: declare float @ldexpf(float, i32)
; LINUX-NEXT: declare double @ldexpl(double, i32)
; LINUX-NEXT: declare void @llrint(...)
; LINUX-NEXT: declare void @llrintf(...)
; LINUX-NEXT: declare void @llrintl(...)
; LINUX-NEXT: declare void @llround(...)
; LINUX-NEXT: declare void @llroundf(...)
; LINUX-NEXT: declare void @llroundl(...)
; LINUX-NEXT: declare double @log(double)
; LINUX-NEXT: declare double @log10(double)
; LINUX-NEXT: declare float @log10f(float)
; LINUX-NEXT: declare double @log10l(double)
; LINUX-NEXT: declare double @log2(double)
; LINUX-NEXT: declare float @log2f(float)
; LINUX-NEXT: declare double @log2l(double)
; LINUX-NEXT: declare float @logf(float)
; LINUX-NEXT: declare double @logl(double)
; LINUX-NEXT: declare void @lrint(...)
; LINUX-NEXT: declare void @lrintf(...)
; LINUX-NEXT: declare void @lrintl(...)
; LINUX-NEXT: declare void @lround(...)
; LINUX-NEXT: declare void @lroundf(...)
; LINUX-NEXT: declare void @lroundl(...)
; LINUX-NEXT: declare noalias noundef ptr @malloc(i64 noundef) [[MALLOC_ATTRS:#[0-9]+]]
; LINUX-NEXT: declare ptr @memcpy(ptr, ptr, i64)
; LINUX-NEXT: declare ptr @memmove(ptr, ptr, i64)
; LINUX-NEXT: declare ptr @memset(ptr, i32, i64)
; LINUX-NEXT: declare double @modf(double, ptr)
; LINUX-NEXT: declare float @modff(float, ptr)
; LINUX-NEXT: declare double @modfl(double, ptr)
; LINUX-NEXT: declare double @nan(ptr)
; LINUX-NEXT: declare float @nanf(ptr)
; LINUX-NEXT: declare double @nanl(ptr)
; LINUX-NEXT: declare double @nearbyint(double)
; LINUX-NEXT: declare float @nearbyintf(float)
; LINUX-NEXT: declare double @nearbyintl(double)
; LINUX-NEXT: declare double @nexttoward(double, double)
; LINUX-NEXT: declare float @nexttowardf(float, double)
; LINUX-NEXT: declare double @nexttowardl(double, double)
; LINUX-NEXT: declare double @pow(double, double)
; LINUX-NEXT: declare float @powf(float, float)
; LINUX-NEXT: declare double @powl(double, double)
; LINUX-NEXT: declare double @remainder(double, double)
; LINUX-NEXT: declare float @remainderf(float, float)
; LINUX-NEXT: declare double @remainderl(double, double)
; LINUX-NEXT: declare double @remquo(double, double, ptr)
; LINUX-NEXT: declare float @remquof(float, float, ptr)
; LINUX-NEXT: declare double @remquol(double, double, ptr)
; LINUX-NEXT: declare double @rint(double)
; LINUX-NEXT: declare float @rintf(float)
; LINUX-NEXT: declare double @rintl(double)
; LINUX-NEXT: declare double @round(double)
; LINUX-NEXT: declare double @roundeven(double)
; LINUX-NEXT: declare float @roundevenf(float)
; LINUX-NEXT: declare double @roundevenl(double)
; LINUX-NEXT: declare float @roundf(float)
; LINUX-NEXT: declare double @roundl(double)
; LINUX-NEXT: declare double @scalbln(double, i32)
; LINUX-NEXT: declare float @scalblnf(float, i32)
; LINUX-NEXT: declare double @scalblnl(double, i32)
; LINUX-NEXT: declare double @scalbn(double, i32)
; LINUX-NEXT: declare float @scalbnf(float, i32)
; LINUX-NEXT: declare double @scalbnl(double, i32)
; LINUX-NEXT: declare double @sin(double)
; LINUX-NEXT: declare void @sincos(double, ptr, ptr)
; LINUX-NEXT: declare void @sincosf(float, ptr, ptr)
; LINUX-NEXT: declare void @sincosl(double, ptr, ptr)
; LINUX-NEXT: declare float @sinf(float)
; LINUX-NEXT: declare double @sinh(double)
; LINUX-NEXT: declare float @sinhf(float)
; LINUX-NEXT: declare double @sinhl(double)
; LINUX-NEXT: declare double @sinl(double)
; LINUX-NEXT: declare nofpclass(ninf nsub nnorm) double @sqrt(double) [[SQRT_ATTRS:#[0-9]+]]
; LINUX-NEXT: declare nofpclass(ninf nsub nnorm) float @sqrtf(float) [[SQRT_ATTRS:#[0-9]+]]
; LINUX-NEXT: declare double @sqrtl(double)
; LINUX-NEXT: declare double @tan(double)
; LINUX-NEXT: declare float @tanf(float)
; LINUX-NEXT: declare double @tanh(double)
; LINUX-NEXT: declare float @tanhf(float)
; LINUX-NEXT: declare double @tanhl(double)
; LINUX-NEXT: declare double @tanl(double)
; LINUX-NEXT: declare double @tgamma(double)
; LINUX-NEXT: declare float @tgammaf(float)
; LINUX-NEXT: declare double @tgammal(double)
; LINUX-NEXT: declare double @trunc(double)
; LINUX-NEXT: declare float @truncf(float)
; LINUX-NEXT: declare double @truncl(double)
; LINUX-NEXT: attributes [[CALLOC_ATTRS]] = { nofree nounwind willreturn allockind("alloc") allocsize(0,1) "alloc-family"="malloc" }
; LINUX-NEXT: attributes [[FREE_ATTRS]] = { nounwind willreturn allockind("free") "alloc-family"="malloc" }
; LINUX-NEXT: attributes [[MALLOC_ATTRS]] = { nofree nounwind willreturn allockind("alloc,uninitialized") allocsize(0) "alloc-family"="malloc" }
; LINUX-NEXT: attributes [[SQRT_ATTRS]] = { nocallback nofree nosync nounwind willreturn memory(errnomem: write) }

; ZOS: declare double @"@@DCPY@B"(double, double)
; ZOS-NEXT: declare double @"@@EXP2@B"(double)
; ZOS-NEXT: declare float @"@@FACS@B"(float)
; ZOS-NEXT: declare float @"@@FASN@B"(float)
; ZOS-NEXT: declare float @"@@FAT2@B"(float, float)
; ZOS-NEXT: declare float @"@@FATN@B"(float)
; ZOS-NEXT: declare float @"@@FCBT@B"(float)
; ZOS-NEXT: declare float @"@@FCEL@B"(float)
; ZOS-NEXT: declare float @"@@FCOS@B"(float)
; ZOS-NEXT: declare float @"@@FCPY@B"(float, float)
; ZOS-NEXT: declare float @"@@FCSH@B"(float)
; ZOS-NEXT: declare float @"@@FEXP@B"(float)
; ZOS-NEXT: declare float @"@@FFLR@B"(float)
; ZOS-NEXT: declare float @"@@FFMD@B"(float, float)
; ZOS-NEXT: declare float @"@@FFXP@B"(float, ptr)
; ZOS-NEXT: declare float @"@@FLG1@B"(float)
; ZOS-NEXT: declare float @"@@FLG2@B"(float)
; ZOS-NEXT: declare float @"@@FLOG@B"(float)
; ZOS-NEXT: declare float @"@@FLXP@B"(float, i32)
; ZOS-NEXT: declare void @"@@FMA@B"(...)
; ZOS-NEXT: declare void @"@@FMAFB"(...)
; ZOS-NEXT: declare void @"@@FMALB"(...)
; ZOS-NEXT: declare float @"@@FMAX@B"(float, float)
; ZOS-NEXT: declare float @"@@FMAXFB"(float, float)
; ZOS-NEXT: declare float @"@@FMAXLB"(float, float)
; ZOS-NEXT: declare float @"@@FMIN@B"(float, float)
; ZOS-NEXT: declare float @"@@FMINFB"(float, float)
; ZOS-NEXT: declare float @"@@FMINLB"(float, float)
; ZOS-NEXT: declare float @"@@FPOW@B"(float, float)
; ZOS-NEXT: declare void @"@@FRND@B"(...)
; ZOS-NEXT: declare float @"@@FSIN@B"(float)
; ZOS-NEXT: declare float @"@@FSNH@B"(float)
; ZOS-NEXT: declare float @"@@FSQT@B"(float)
; ZOS-NEXT: declare float @"@@FTAN@B"(float)
; ZOS-NEXT: declare float @"@@FTNH@B"(float)
; ZOS-NEXT: declare float @"@@FTRC@B"(float)
; ZOS-NEXT: declare float @"@@FXP2@B"(float)
; ZOS-NEXT: declare double @"@@LACS@B"(double)
; ZOS-NEXT: declare double @"@@LASN@B"(double)
; ZOS-NEXT: declare double @"@@LAT2@B"(double, double)
; ZOS-NEXT: declare double @"@@LATN@B"(double)
; ZOS-NEXT: declare double @"@@LCBT@B"(double)
; ZOS-NEXT: declare double @"@@LCEL@B"(double)
; ZOS-NEXT: declare double @"@@LCOS@B"(double)
; ZOS-NEXT: declare double @"@@LCPY@B"(double, double)
; ZOS-NEXT: declare double @"@@LCSH@B"(double)
; ZOS-NEXT: declare double @"@@LEXP@B"(double)
; ZOS-NEXT: declare double @"@@LFLR@B"(double)
; ZOS-NEXT: declare double @"@@LFMD@B"(double, double)
; ZOS-NEXT: declare double @"@@LFXP@B"(double, ptr)
; ZOS-NEXT: declare double @"@@LLG1@B"(double)
; ZOS-NEXT: declare double @"@@LLG2@B"(double)
; ZOS-NEXT: declare double @"@@LLOG@B"(double)
; ZOS-NEXT: declare void @"@@LLRD@B"(...)
; ZOS-NEXT: declare void @"@@LLRDFB"(...)
; ZOS-NEXT: declare void @"@@LLRDLB"(...)
; ZOS-NEXT: declare void @"@@LLRT@B"(...)
; ZOS-NEXT: declare void @"@@LLRTFB"(...)
; ZOS-NEXT: declare void @"@@LLRTLB"(...)
; ZOS-NEXT: declare double @"@@LLXP@B"(double, i32)
; ZOS-NEXT: declare double @"@@LOG2@B"(double)
; ZOS-NEXT: declare double @"@@LPOW@B"(double, double)
; ZOS-NEXT: declare void @"@@LRND@B"(...)
; ZOS-NEXT: declare void @"@@LRNT@B"(...)
; ZOS-NEXT: declare void @"@@LRNTFB"(...)
; ZOS-NEXT: declare void @"@@LRNTLB"(...)
; ZOS-NEXT: declare double @"@@LSIN@B"(double)
; ZOS-NEXT: declare double @"@@LSNH@B"(double)
; ZOS-NEXT: declare double @"@@LSQT@B"(double)
; ZOS-NEXT: declare double @"@@LTAN@B"(double)
; ZOS-NEXT: declare double @"@@LTNH@B"(double)
; ZOS-NEXT: declare double @"@@LTRC@B"(double)
; ZOS-NEXT: declare double @"@@LXP2@B"(double)
; ZOS-NEXT: declare double @"@@NBYI@B"(double)
; ZOS-NEXT: declare float @"@@NBYIFB"(float)
; ZOS-NEXT: declare double @"@@NBYILB"(double)
; ZOS-NEXT: declare float @"@@RINTFB"(float)
; ZOS-NEXT: declare double @"@@RINTLB"(double)
; ZOS-NEXT: declare void @"@@ROND@B"(...)
; ZOS-NEXT: declare double @"@@ROUN@B"(double)
; ZOS-NEXT: declare float @"@@ROUNFB"(float)
; ZOS-NEXT: declare double @"@@ROUNLB"(double)
; ZOS-NEXT: declare double @"@@SATN@B"(double)
; ZOS-NEXT: declare double @"@@SCEL@B"(double)
; ZOS-NEXT: declare double @"@@SCOS@B"(double)
; ZOS-NEXT: declare double @"@@SCRT@B"(double)
; ZOS-NEXT: declare double @"@@SFLR@B"(double)
; ZOS-NEXT: declare double @"@@SFXP@B"(double, ptr)
; ZOS-NEXT: declare double @"@@SLXP@B"(double, i32)
; ZOS-NEXT: declare double @"@@SRNT@B"(double)
; ZOS-NEXT: declare double @"@@SSIN@B"(double)
; ZOS-NEXT: declare double @"@@STAN@B"(double)
; ZOS-NEXT: declare double @"@@STNH@B"(double)
; ZOS-NEXT: declare double @"@@TRNC@B"(double)
; ZOS-NEXT: declare double @"@@WACS@B"(double)
; ZOS-NEXT: declare double @"@@WASN@B"(double)
; ZOS-NEXT: declare double @"@@WAT2@B"(double, double)
; ZOS-NEXT: declare double @"@@WCSH@B"(double)
; ZOS-NEXT: declare double @"@@WEXP@B"(double)
; ZOS-NEXT: declare double @"@@WFMD@B"(double, double)
; ZOS-NEXT: declare double @"@@WLG1@B"(double)
; ZOS-NEXT: declare double @"@@WLOG@B"(double)
; ZOS-NEXT: declare double @"@@WPOW@B"(double, double)
; ZOS-NEXT: declare double @"@@WSNH@B"(double)
; ZOS-NEXT: declare double @"@@WSQT@B"(double)
; ZOS-NEXT: declare void @_Unwind_Resume(...)
; ZOS-NEXT: declare void @__adddf3(...)
; ZOS-NEXT: declare void @__addsf3(...)
; ZOS-NEXT: declare void @__addtf3(...)
; ZOS-NEXT: declare void @__ashldi3(...)
; ZOS-NEXT: declare void @__ashlhi3(...)
; ZOS-NEXT: declare void @__ashlsi3(...)
; ZOS-NEXT: declare void @__ashlti3(...)
; ZOS-NEXT: declare void @__ashrdi3(...)
; ZOS-NEXT: declare void @__ashrhi3(...)
; ZOS-NEXT: declare void @__ashrsi3(...)
; ZOS-NEXT: declare void @__ashrti3(...)
; ZOS-NEXT: declare void @__atomic_compare_exchange(...)
; ZOS-NEXT: declare void @__atomic_compare_exchange_1(...)
; ZOS-NEXT: declare void @__atomic_compare_exchange_16(...)
; ZOS-NEXT: declare void @__atomic_compare_exchange_2(...)
; ZOS-NEXT: declare void @__atomic_compare_exchange_4(...)
; ZOS-NEXT: declare void @__atomic_compare_exchange_8(...)
; ZOS-NEXT: declare void @__atomic_exchange(...)
; ZOS-NEXT: declare void @__atomic_exchange_1(...)
; ZOS-NEXT: declare void @__atomic_exchange_16(...)
; ZOS-NEXT: declare void @__atomic_exchange_2(...)
; ZOS-NEXT: declare void @__atomic_exchange_4(...)
; ZOS-NEXT: declare void @__atomic_exchange_8(...)
; ZOS-NEXT: declare void @__atomic_fetch_add_1(...)
; ZOS-NEXT: declare void @__atomic_fetch_add_16(...)
; ZOS-NEXT: declare void @__atomic_fetch_add_2(...)
; ZOS-NEXT: declare void @__atomic_fetch_add_4(...)
; ZOS-NEXT: declare void @__atomic_fetch_add_8(...)
; ZOS-NEXT: declare void @__atomic_fetch_and_1(...)
; ZOS-NEXT: declare void @__atomic_fetch_and_16(...)
; ZOS-NEXT: declare void @__atomic_fetch_and_2(...)
; ZOS-NEXT: declare void @__atomic_fetch_and_4(...)
; ZOS-NEXT: declare void @__atomic_fetch_and_8(...)
; ZOS-NEXT: declare void @__atomic_fetch_nand_1(...)
; ZOS-NEXT: declare void @__atomic_fetch_nand_16(...)
; ZOS-NEXT: declare void @__atomic_fetch_nand_2(...)
; ZOS-NEXT: declare void @__atomic_fetch_nand_4(...)
; ZOS-NEXT: declare void @__atomic_fetch_nand_8(...)
; ZOS-NEXT: declare void @__atomic_fetch_or_1(...)
; ZOS-NEXT: declare void @__atomic_fetch_or_16(...)
; ZOS-NEXT: declare void @__atomic_fetch_or_2(...)
; ZOS-NEXT: declare void @__atomic_fetch_or_4(...)
; ZOS-NEXT: declare void @__atomic_fetch_or_8(...)
; ZOS-NEXT: declare void @__atomic_fetch_sub_1(...)
; ZOS-NEXT: declare void @__atomic_fetch_sub_16(...)
; ZOS-NEXT: declare void @__atomic_fetch_sub_2(...)
; ZOS-NEXT: declare void @__atomic_fetch_sub_4(...)
; ZOS-NEXT: declare void @__atomic_fetch_sub_8(...)
; ZOS-NEXT: declare void @__atomic_fetch_xor_1(...)
; ZOS-NEXT: declare void @__atomic_fetch_xor_16(...)
; ZOS-NEXT: declare void @__atomic_fetch_xor_2(...)
; ZOS-NEXT: declare void @__atomic_fetch_xor_4(...)
; ZOS-NEXT: declare void @__atomic_fetch_xor_8(...)
; ZOS-NEXT: declare void @__atomic_load(i64, ptr, ptr, i32)
; ZOS-NEXT: declare void @__atomic_load_1(...)
; ZOS-NEXT: declare void @__atomic_load_16(...)
; ZOS-NEXT: declare void @__atomic_load_2(...)
; ZOS-NEXT: declare void @__atomic_load_4(...)
; ZOS-NEXT: declare void @__atomic_load_8(...)
; ZOS-NEXT: declare void @__atomic_store(i64, ptr, ptr, i32)
; ZOS-NEXT: declare void @__atomic_store_1(...)
; ZOS-NEXT: declare void @__atomic_store_16(...)
; ZOS-NEXT: declare void @__atomic_store_2(...)
; ZOS-NEXT: declare void @__atomic_store_4(...)
; ZOS-NEXT: declare void @__atomic_store_8(...)
; ZOS-NEXT: declare void @__clear_cache(...)
; ZOS-NEXT: declare void @__clzdi2(...)
; ZOS-NEXT: declare void @__clzsi2(...)
; ZOS-NEXT: declare void @__clzti2(...)
; ZOS-NEXT: declare void @__cxa_end_cleanup(...)
; ZOS-NEXT: declare void @__divdf3(...)
; ZOS-NEXT: declare void @__divdi3(...)
; ZOS-NEXT: declare void @__divhi3(...)
; ZOS-NEXT: declare void @__divqi3(...)
; ZOS-NEXT: declare void @__divsf3(...)
; ZOS-NEXT: declare void @__divsi3(...)
; ZOS-NEXT: declare void @__divtf3(...)
; ZOS-NEXT: declare void @__divti3(...)
; ZOS-NEXT: declare void @__eqdf2(...)
; ZOS-NEXT: declare void @__eqsf2(...)
; ZOS-NEXT: declare void @__eqtf2(...)
; ZOS-NEXT: declare double @__exp2_finite(double)
; ZOS-NEXT: declare float @__exp2f_finite(float)
; ZOS-NEXT: declare double @__exp2l_finite(double)
; ZOS-NEXT: declare double @__exp_finite(double)
; ZOS-NEXT: declare float @__expf_finite(float)
; ZOS-NEXT: declare double @__expl_finite(double)
; ZOS-NEXT: declare void @__extendbfsf2(...)
; ZOS-NEXT: declare void @__extenddftf2(...)
; ZOS-NEXT: declare void @__extendhfdf2(...)
; ZOS-NEXT: declare void @__extendhfsf2(...)
; ZOS-NEXT: declare void @__extendhftf2(...)
; ZOS-NEXT: declare void @__extendsfdf2(...)
; ZOS-NEXT: declare void @__extendsftf2(...)
; ZOS-NEXT: declare void @__fixdfdi(...)
; ZOS-NEXT: declare void @__fixdfsi(...)
; ZOS-NEXT: declare void @__fixdfti(...)
; ZOS-NEXT: declare void @__fixhfdi(...)
; ZOS-NEXT: declare void @__fixhfsi(...)
; ZOS-NEXT: declare void @__fixhfti(...)
; ZOS-NEXT: declare void @__fixsfdi(...)
; ZOS-NEXT: declare void @__fixsfsi(...)
; ZOS-NEXT: declare void @__fixsfti(...)
; ZOS-NEXT: declare void @__fixtfdi(...)
; ZOS-NEXT: declare void @__fixtfsi(...)
; ZOS-NEXT: declare void @__fixtfti(...)
; ZOS-NEXT: declare void @__fixunsdfdi(...)
; ZOS-NEXT: declare void @__fixunsdfsi(...)
; ZOS-NEXT: declare void @__fixunsdfti(...)
; ZOS-NEXT: declare void @__fixunshfdi(...)
; ZOS-NEXT: declare void @__fixunshfsi(...)
; ZOS-NEXT: declare void @__fixunshfti(...)
; ZOS-NEXT: declare void @__fixunssfdi(...)
; ZOS-NEXT: declare void @__fixunssfsi(...)
; ZOS-NEXT: declare void @__fixunssfti(...)
; ZOS-NEXT: declare void @__fixunstfdi(...)
; ZOS-NEXT: declare void @__fixunstfsi(...)
; ZOS-NEXT: declare void @__fixunstfti(...)
; ZOS-NEXT: declare void @__floatdibf(...)
; ZOS-NEXT: declare void @__floatdidf(...)
; ZOS-NEXT: declare void @__floatdihf(...)
; ZOS-NEXT: declare void @__floatdisf(...)
; ZOS-NEXT: declare void @__floatditf(...)
; ZOS-NEXT: declare void @__floatsidf(...)
; ZOS-NEXT: declare void @__floatsihf(...)
; ZOS-NEXT: declare void @__floatsisf(...)
; ZOS-NEXT: declare void @__floatsitf(...)
; ZOS-NEXT: declare void @__floattidf(...)
; ZOS-NEXT: declare void @__floattihf(...)
; ZOS-NEXT: declare void @__floattisf(...)
; ZOS-NEXT: declare void @__floattitf(...)
; ZOS-NEXT: declare void @__floatundibf(...)
; ZOS-NEXT: declare void @__floatundidf(...)
; ZOS-NEXT: declare void @__floatundihf(...)
; ZOS-NEXT: declare void @__floatundisf(...)
; ZOS-NEXT: declare void @__floatunditf(...)
; ZOS-NEXT: declare void @__floatunsidf(...)
; ZOS-NEXT: declare void @__floatunsihf(...)
; ZOS-NEXT: declare void @__floatunsisf(...)
; ZOS-NEXT: declare void @__floatunsitf(...)
; ZOS-NEXT: declare void @__floatuntidf(...)
; ZOS-NEXT: declare void @__floatuntihf(...)
; ZOS-NEXT: declare void @__floatuntisf(...)
; ZOS-NEXT: declare void @__floatuntitf(...)
; ZOS-NEXT: declare void @__gedf2(...)
; ZOS-NEXT: declare void @__gesf2(...)
; ZOS-NEXT: declare void @__getf2(...)
; ZOS-NEXT: declare void @__gtdf2(...)
; ZOS-NEXT: declare void @__gtsf2(...)
; ZOS-NEXT: declare void @__gttf2(...)
; ZOS-NEXT: declare void @__ledf2(...)
; ZOS-NEXT: declare void @__lesf2(...)
; ZOS-NEXT: declare void @__letf2(...)
; ZOS-NEXT: declare void @__llvm_deoptimize(...)
; ZOS-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_1(...)
; ZOS-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_16(...)
; ZOS-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_2(...)
; ZOS-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_4(...)
; ZOS-NEXT: declare void @__llvm_memcpy_element_unordered_atomic_8(...)
; ZOS-NEXT: declare void @__llvm_memmove_element_unordered_atomic_1(...)
; ZOS-NEXT: declare void @__llvm_memmove_element_unordered_atomic_16(...)
; ZOS-NEXT: declare void @__llvm_memmove_element_unordered_atomic_2(...)
; ZOS-NEXT: declare void @__llvm_memmove_element_unordered_atomic_4(...)
; ZOS-NEXT: declare void @__llvm_memmove_element_unordered_atomic_8(...)
; ZOS-NEXT: declare void @__llvm_memset_element_unordered_atomic_1(...)
; ZOS-NEXT: declare void @__llvm_memset_element_unordered_atomic_16(...)
; ZOS-NEXT: declare void @__llvm_memset_element_unordered_atomic_2(...)
; ZOS-NEXT: declare void @__llvm_memset_element_unordered_atomic_4(...)
; ZOS-NEXT: declare void @__llvm_memset_element_unordered_atomic_8(...)
; ZOS-NEXT: declare double @__log10_finite(double)
; ZOS-NEXT: declare float @__log10f_finite(float)
; ZOS-NEXT: declare double @__log10l_finite(double)
; ZOS-NEXT: declare double @__log2_finite(double)
; ZOS-NEXT: declare float @__log2f_finite(float)
; ZOS-NEXT: declare double @__log2l_finite(double)
; ZOS-NEXT: declare double @__log_finite(double)
; ZOS-NEXT: declare float @__logf_finite(float)
; ZOS-NEXT: declare double @__logl_finite(double)
; ZOS-NEXT: declare void @__lshrdi3(...)
; ZOS-NEXT: declare void @__lshrhi3(...)
; ZOS-NEXT: declare void @__lshrsi3(...)
; ZOS-NEXT: declare void @__lshrti3(...)
; ZOS-NEXT: declare void @__ltdf2(...)
; ZOS-NEXT: declare void @__ltsf2(...)
; ZOS-NEXT: declare void @__lttf2(...)
; ZOS-NEXT: declare ptr @__memcpy_chk(ptr, ptr, i64, i64)
; ZOS-NEXT: declare ptr @__memmove_chk(ptr, ptr, i64, i64)
; ZOS-NEXT: declare ptr @__memset_chk(ptr, i32, i64, i64)
; ZOS-NEXT: declare void @__moddi3(...)
; ZOS-NEXT: declare void @__modhi3(...)
; ZOS-NEXT: declare void @__modqi3(...)
; ZOS-NEXT: declare void @__modsi3(...)
; ZOS-NEXT: declare void @__modti3(...)
; ZOS-NEXT: declare void @__muldf3(...)
; ZOS-NEXT: declare void @__muldi3(...)
; ZOS-NEXT: declare void @__mulhi3(...)
; ZOS-NEXT: declare void @__mulosi4(...)
; ZOS-NEXT: declare void @__mulqi3(...)
; ZOS-NEXT: declare void @__mulsf3(...)
; ZOS-NEXT: declare void @__mulsi3(...)
; ZOS-NEXT: declare void @__multf3(...)
; ZOS-NEXT: declare void @__multi3(...)
; ZOS-NEXT: declare void @__nedf2(...)
; ZOS-NEXT: declare void @__negdi2(...)
; ZOS-NEXT: declare void @__negsi2(...)
; ZOS-NEXT: declare void @__nesf2(...)
; ZOS-NEXT: declare void @__netf2(...)
; ZOS-NEXT: declare void @__popcountdi2(...)
; ZOS-NEXT: declare void @__popcountsi2(...)
; ZOS-NEXT: declare void @__popcountti2(...)
; ZOS-NEXT: declare double @__pow_finite(double, double)
; ZOS-NEXT: declare float @__powf_finite(float, float)
; ZOS-NEXT: declare void @__powidf2(...)
; ZOS-NEXT: declare void @__powisf2(...)
; ZOS-NEXT: declare void @__powitf2(...)
; ZOS-NEXT: declare double @__powl_finite(double, double)
; ZOS-NEXT: declare void @__stack_chk_fail(...)
; ZOS-NEXT: declare void @__stack_chk_guard(...)
; ZOS-NEXT: declare void @__subdf3(...)
; ZOS-NEXT: declare void @__subsf3(...)
; ZOS-NEXT: declare void @__subtf3(...)
; ZOS-NEXT: declare void @__sync_fetch_and_add_1(...)
; ZOS-NEXT: declare void @__sync_fetch_and_add_16(...)
; ZOS-NEXT: declare void @__sync_fetch_and_add_2(...)
; ZOS-NEXT: declare void @__sync_fetch_and_add_4(...)
; ZOS-NEXT: declare void @__sync_fetch_and_add_8(...)
; ZOS-NEXT: declare void @__sync_fetch_and_and_1(...)
; ZOS-NEXT: declare void @__sync_fetch_and_and_16(...)
; ZOS-NEXT: declare void @__sync_fetch_and_and_2(...)
; ZOS-NEXT: declare void @__sync_fetch_and_and_4(...)
; ZOS-NEXT: declare void @__sync_fetch_and_and_8(...)
; ZOS-NEXT: declare void @__sync_fetch_and_max_1(...)
; ZOS-NEXT: declare void @__sync_fetch_and_max_16(...)
; ZOS-NEXT: declare void @__sync_fetch_and_max_2(...)
; ZOS-NEXT: declare void @__sync_fetch_and_max_4(...)
; ZOS-NEXT: declare void @__sync_fetch_and_max_8(...)
; ZOS-NEXT: declare void @__sync_fetch_and_min_1(...)
; ZOS-NEXT: declare void @__sync_fetch_and_min_16(...)
; ZOS-NEXT: declare void @__sync_fetch_and_min_2(...)
; ZOS-NEXT: declare void @__sync_fetch_and_min_4(...)
; ZOS-NEXT: declare void @__sync_fetch_and_min_8(...)
; ZOS-NEXT: declare void @__sync_fetch_and_nand_1(...)
; ZOS-NEXT: declare void @__sync_fetch_and_nand_16(...)
; ZOS-NEXT: declare void @__sync_fetch_and_nand_2(...)
; ZOS-NEXT: declare void @__sync_fetch_and_nand_4(...)
; ZOS-NEXT: declare void @__sync_fetch_and_nand_8(...)
; ZOS-NEXT: declare void @__sync_fetch_and_or_1(...)
; ZOS-NEXT: declare void @__sync_fetch_and_or_16(...)
; ZOS-NEXT: declare void @__sync_fetch_and_or_2(...)
; ZOS-NEXT: declare void @__sync_fetch_and_or_4(...)
; ZOS-NEXT: declare void @__sync_fetch_and_or_8(...)
; ZOS-NEXT: declare void @__sync_fetch_and_sub_1(...)
; ZOS-NEXT: declare void @__sync_fetch_and_sub_16(...)
; ZOS-NEXT: declare void @__sync_fetch_and_sub_2(...)
; ZOS-NEXT: declare void @__sync_fetch_and_sub_4(...)
; ZOS-NEXT: declare void @__sync_fetch_and_sub_8(...)
; ZOS-NEXT: declare void @__sync_fetch_and_umax_1(...)
; ZOS-NEXT: declare void @__sync_fetch_and_umax_16(...)
; ZOS-NEXT: declare void @__sync_fetch_and_umax_2(...)
; ZOS-NEXT: declare void @__sync_fetch_and_umax_4(...)
; ZOS-NEXT: declare void @__sync_fetch_and_umax_8(...)
; ZOS-NEXT: declare void @__sync_fetch_and_umin_1(...)
; ZOS-NEXT: declare void @__sync_fetch_and_umin_16(...)
; ZOS-NEXT: declare void @__sync_fetch_and_umin_2(...)
; ZOS-NEXT: declare void @__sync_fetch_and_umin_4(...)
; ZOS-NEXT: declare void @__sync_fetch_and_umin_8(...)
; ZOS-NEXT: declare void @__sync_fetch_and_xor_1(...)
; ZOS-NEXT: declare void @__sync_fetch_and_xor_16(...)
; ZOS-NEXT: declare void @__sync_fetch_and_xor_2(...)
; ZOS-NEXT: declare void @__sync_fetch_and_xor_4(...)
; ZOS-NEXT: declare void @__sync_fetch_and_xor_8(...)
; ZOS-NEXT: declare void @__sync_lock_test_and_set_1(...)
; ZOS-NEXT: declare void @__sync_lock_test_and_set_16(...)
; ZOS-NEXT: declare void @__sync_lock_test_and_set_2(...)
; ZOS-NEXT: declare void @__sync_lock_test_and_set_4(...)
; ZOS-NEXT: declare void @__sync_lock_test_and_set_8(...)
; ZOS-NEXT: declare void @__sync_val_compare_and_swap_1(...)
; ZOS-NEXT: declare void @__sync_val_compare_and_swap_16(...)
; ZOS-NEXT: declare void @__sync_val_compare_and_swap_2(...)
; ZOS-NEXT: declare void @__sync_val_compare_and_swap_4(...)
; ZOS-NEXT: declare void @__sync_val_compare_and_swap_8(...)
; ZOS-NEXT: declare void @__truncdfbf2(...)
; ZOS-NEXT: declare void @__truncdfhf2(...)
; ZOS-NEXT: declare void @__truncdfsf2(...)
; ZOS-NEXT: declare void @__truncsfbf2(...)
; ZOS-NEXT: declare void @__truncsfhf2(...)
; ZOS-NEXT: declare void @__trunctfbf2(...)
; ZOS-NEXT: declare void @__trunctfdf2(...)
; ZOS-NEXT: declare void @__trunctfhf2(...)
; ZOS-NEXT: declare void @__trunctfsf2(...)
; ZOS-NEXT: declare void @__udivdi3(...)
; ZOS-NEXT: declare void @__udivhi3(...)
; ZOS-NEXT: declare void @__udivqi3(...)
; ZOS-NEXT: declare void @__udivsi3(...)
; ZOS-NEXT: declare void @__udivti3(...)
; ZOS-NEXT: declare void @__umoddi3(...)
; ZOS-NEXT: declare void @__umodhi3(...)
; ZOS-NEXT: declare void @__umodqi3(...)
; ZOS-NEXT: declare void @__umodsi3(...)
; ZOS-NEXT: declare void @__umodti3(...)
; ZOS-NEXT: declare void @__unorddf2(...)
; ZOS-NEXT: declare void @__unordsf2(...)
; ZOS-NEXT: declare void @__unordtf2(...)
; ZOS-NEXT: declare double @acos(double)
; ZOS-NEXT: declare float @acosf(float)
; ZOS-NEXT: declare double @acosl(double)
; ZOS-NEXT: declare double @asin(double)
; ZOS-NEXT: declare float @asinf(float)
; ZOS-NEXT: declare double @asinl(double)
; ZOS-NEXT: declare double @atan(double)
; ZOS-NEXT: declare double @atan2(double, double)
; ZOS-NEXT: declare float @atan2f(float, float)
; ZOS-NEXT: declare double @atan2l(double, double)
; ZOS-NEXT: declare float @atanf(float)
; ZOS-NEXT: declare double @atanl(double)
; ZOS-NEXT: declare void @cabs(...)
; ZOS-NEXT: declare void @cabsf(...)
; ZOS-NEXT: declare void @cabsl(...)
; ZOS-NEXT: declare noalias noundef ptr @calloc(i64 noundef, i64 noundef) [[CALLOC_ATTRS:#[0-9]+]]
; ZOS-NEXT: declare double @cbrt(double)
; ZOS-NEXT: declare float @cbrtf(float)
; ZOS-NEXT: declare double @cbrtl(double)
; ZOS-NEXT: declare double @ceil(double)
; ZOS-NEXT: declare float @ceilf(float)
; ZOS-NEXT: declare double @ceill(double)
; ZOS-NEXT: declare double @copysign(double, double)
; ZOS-NEXT: declare float @copysignf(float, float)
; ZOS-NEXT: declare double @copysignl(double, double)
; ZOS-NEXT: declare double @cos(double)
; ZOS-NEXT: declare float @cosf(float)
; ZOS-NEXT: declare double @cosh(double)
; ZOS-NEXT: declare float @coshf(float)
; ZOS-NEXT: declare double @coshl(double)
; ZOS-NEXT: declare double @cosl(double)
; ZOS-NEXT: declare double @exp(double)
; ZOS-NEXT: declare double @exp10(double)
; ZOS-NEXT: declare float @exp10f(float)
; ZOS-NEXT: declare double @exp10l(double)
; ZOS-NEXT: declare double @exp2(double)
; ZOS-NEXT: declare float @exp2f(float)
; ZOS-NEXT: declare double @exp2l(double)
; ZOS-NEXT: declare float @expf(float)
; ZOS-NEXT: declare double @expl(double)
; ZOS-NEXT: declare double @fdim(double, double)
; ZOS-NEXT: declare float @fdimf(float, float)
; ZOS-NEXT: declare double @fdiml(double, double)
; ZOS-NEXT: declare void @fegetenv(...)
; ZOS-NEXT: declare void @fegetmode(...)
; ZOS-NEXT: declare void @fesetenv(...)
; ZOS-NEXT: declare void @fesetmode(...)
; ZOS-NEXT: declare double @floor(double)
; ZOS-NEXT: declare float @floorf(float)
; ZOS-NEXT: declare double @floorl(double)
; ZOS-NEXT: declare void @fma(...)
; ZOS-NEXT: declare void @fmaf(...)
; ZOS-NEXT: declare void @fmal(...)
; ZOS-NEXT: declare float @fmax(float, float)
; ZOS-NEXT: declare float @fmaxf(float, float)
; ZOS-NEXT: declare void @fmaximum(...)
; ZOS-NEXT: declare float @fmaximum_num(float, float)
; ZOS-NEXT: declare float @fmaximum_numf(float, float)
; ZOS-NEXT: declare float @fmaximum_numl(float, float)
; ZOS-NEXT: declare void @fmaximumf(...)
; ZOS-NEXT: declare void @fmaximuml(...)
; ZOS-NEXT: declare float @fmaxl(float, float)
; ZOS-NEXT: declare float @fmin(float, float)
; ZOS-NEXT: declare float @fminf(float, float)
; ZOS-NEXT: declare void @fminimum(...)
; ZOS-NEXT: declare float @fminimum_num(float, float)
; ZOS-NEXT: declare float @fminimum_numf(float, float)
; ZOS-NEXT: declare float @fminimum_numl(float, float)
; ZOS-NEXT: declare void @fminimumf(...)
; ZOS-NEXT: declare void @fminimuml(...)
; ZOS-NEXT: declare float @fminl(float, float)
; ZOS-NEXT: declare double @fmod(double, double)
; ZOS-NEXT: declare float @fmodf(float, float)
; ZOS-NEXT: declare double @fmodl(double, double)
; ZOS-NEXT: declare void @free(ptr allocptr noundef captures(none)) [[FREE_ATTRS:#[0-9]+]]
; ZOS-NEXT: declare double @frexp(double, ptr)
; ZOS-NEXT: declare float @frexpf(float, ptr)
; ZOS-NEXT: declare double @frexpl(double, ptr)
; ZOS-NEXT: declare double @ldexp(double, i32)
; ZOS-NEXT: declare float @ldexpf(float, i32)
; ZOS-NEXT: declare double @ldexpl(double, i32)
; ZOS-NEXT: declare void @llrint(...)
; ZOS-NEXT: declare void @llrintf(...)
; ZOS-NEXT: declare void @llrintl(...)
; ZOS-NEXT: declare void @llround(...)
; ZOS-NEXT: declare void @llroundf(...)
; ZOS-NEXT: declare void @llroundl(...)
; ZOS-NEXT: declare double @log(double)
; ZOS-NEXT: declare double @log10(double)
; ZOS-NEXT: declare float @log10f(float)
; ZOS-NEXT: declare double @log10l(double)
; ZOS-NEXT: declare double @log2(double)
; ZOS-NEXT: declare float @log2f(float)
; ZOS-NEXT: declare double @log2l(double)
; ZOS-NEXT: declare float @logf(float)
; ZOS-NEXT: declare double @logl(double)
; ZOS-NEXT: declare void @lrint(...)
; ZOS-NEXT: declare void @lrintf(...)
; ZOS-NEXT: declare void @lrintl(...)
; ZOS-NEXT: declare void @lround(...)
; ZOS-NEXT: declare void @lroundf(...)
; ZOS-NEXT: declare void @lroundl(...)
; ZOS-NEXT: declare noalias noundef ptr @malloc(i64 noundef) [[MALLOC_ATTRS:#[0-9]+]]
; ZOS-NEXT: declare ptr @memcpy(ptr, ptr, i64)
; ZOS-NEXT: declare ptr @memmove(ptr, ptr, i64)
; ZOS-NEXT: declare ptr @memset(ptr, i32, i64)
; ZOS-NEXT: declare double @modf(double, ptr)
; ZOS-NEXT: declare float @modff(float, ptr)
; ZOS-NEXT: declare double @modfl(double, ptr)
; ZOS-NEXT: declare double @nan(ptr)
; ZOS-NEXT: declare float @nanf(ptr)
; ZOS-NEXT: declare double @nanl(ptr)
; ZOS-NEXT: declare double @nearbyint(double)
; ZOS-NEXT: declare float @nearbyintf(float)
; ZOS-NEXT: declare double @nearbyintl(double)
; ZOS-NEXT: declare double @nexttoward(double, double)
; ZOS-NEXT: declare float @nexttowardf(float, double)
; ZOS-NEXT: declare double @nexttowardl(double, double)
; ZOS-NEXT: declare double @pow(double, double)
; ZOS-NEXT: declare float @powf(float, float)
; ZOS-NEXT: declare double @powl(double, double)
; ZOS-NEXT: declare double @remainder(double, double)
; ZOS-NEXT: declare float @remainderf(float, float)
; ZOS-NEXT: declare double @remainderl(double, double)
; ZOS-NEXT: declare double @remquo(double, double, ptr)
; ZOS-NEXT: declare float @remquof(float, float, ptr)
; ZOS-NEXT: declare double @remquol(double, double, ptr)
; ZOS-NEXT: declare double @rint(double)
; ZOS-NEXT: declare float @rintf(float)
; ZOS-NEXT: declare double @rintl(double)
; ZOS-NEXT: declare double @round(double)
; ZOS-NEXT: declare double @roundeven(double)
; ZOS-NEXT: declare float @roundevenf(float)
; ZOS-NEXT: declare double @roundevenl(double)
; ZOS-NEXT: declare float @roundf(float)
; ZOS-NEXT: declare double @roundl(double)
; ZOS-NEXT: declare double @scalbln(double, i32)
; ZOS-NEXT: declare float @scalblnf(float, i32)
; ZOS-NEXT: declare double @scalblnl(double, i32)
; ZOS-NEXT: declare double @scalbn(double, i32)
; ZOS-NEXT: declare float @scalbnf(float, i32)
; ZOS-NEXT: declare double @scalbnl(double, i32)
; ZOS-NEXT: declare double @sin(double)
; ZOS-NEXT: declare float @sinf(float)
; ZOS-NEXT: declare double @sinh(double)
; ZOS-NEXT: declare float @sinhf(float)
; ZOS-NEXT: declare double @sinhl(double)
; ZOS-NEXT: declare double @sinl(double)
; ZOS-NEXT: declare nofpclass(ninf nsub nnorm) double @sqrt(double) [[SQRT_ATTRS:#[0-9]+]]
; ZOS-NEXT: declare nofpclass(ninf nsub nnorm) float @sqrtf(float) [[SQRT_ATTRS:#[0-9]+]]
; ZOS-NEXT: declare double @sqrtl(double)
; ZOS-NEXT: declare double @tan(double)
; ZOS-NEXT: declare float @tanf(float)
; ZOS-NEXT: declare double @tanh(double)
; ZOS-NEXT: declare float @tanhf(float)
; ZOS-NEXT: declare double @tanhl(double)
; ZOS-NEXT: declare double @tanl(double)
; ZOS-NEXT: declare double @tgamma(double)
; ZOS-NEXT: declare float @tgammaf(float)
; ZOS-NEXT: declare double @tgammal(double)
; ZOS-NEXT: declare double @trunc(double)
; ZOS-NEXT: declare float @truncf(float)
; ZOS-NEXT: declare double @truncl(double)
; ZOS-NEXT: attributes [[CALLOC_ATTRS]] = { nofree nounwind willreturn allockind("alloc") allocsize(0,1) "alloc-family"="malloc" }
; ZOS-NEXT: attributes [[FREE_ATTRS]] = { nounwind willreturn allockind("free") "alloc-family"="malloc" }
; ZOS-NEXT: attributes [[MALLOC_ATTRS]] = { nofree nounwind willreturn allockind("alloc,uninitialized") allocsize(0) "alloc-family"="malloc" }
; ZOS-NEXT: attributes [[SQRT_ATTRS]] = { nocallback nofree nosync nounwind willreturn memory(errnomem: write) }
