; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch64 --mattr=+f,-d < %s | FileCheck %s --check-prefix=LA64F
; RUN: llc --mtriple=loongarch64 --mattr=+d < %s | FileCheck %s --check-prefix=LA64D

define float @float_fadd_acquire(ptr %p) nounwind {
; LA64F-LABEL: float_fadd_acquire:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, 260096
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB0_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB0_2 Depth 2
; LA64F-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB0_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB0_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB0_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB0_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB0_2
; LA64F-NEXT:    b .LBB0_5
; LA64F-NEXT:  .LBB0_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB0_1 Depth=1
; LA64F-NEXT:    dbar 20
; LA64F-NEXT:  .LBB0_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB0_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB0_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fadd_acquire:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1168
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB0_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB0_2 Depth 2
; LA64D-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB0_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB0_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB0_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB0_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB0_2
; LA64D-NEXT:    b .LBB0_5
; LA64D-NEXT:  .LBB0_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB0_1 Depth=1
; LA64D-NEXT:    dbar 20
; LA64D-NEXT:  .LBB0_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB0_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB0_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fadd ptr %p, float 1.0 acquire, align 4
  ret float %v
}

define float @float_fsub_acquire(ptr %p) nounwind {
; LA64F-LABEL: float_fsub_acquire:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, -264192
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB1_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB1_2 Depth 2
; LA64F-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB1_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB1_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB1_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB1_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB1_2
; LA64F-NEXT:    b .LBB1_5
; LA64F-NEXT:  .LBB1_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB1_1 Depth=1
; LA64F-NEXT:    dbar 20
; LA64F-NEXT:  .LBB1_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB1_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB1_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fsub_acquire:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1040
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB1_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB1_2 Depth 2
; LA64D-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB1_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB1_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB1_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB1_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB1_2
; LA64D-NEXT:    b .LBB1_5
; LA64D-NEXT:  .LBB1_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB1_1 Depth=1
; LA64D-NEXT:    dbar 20
; LA64D-NEXT:  .LBB1_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB1_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB1_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fsub ptr %p, float 1.0 acquire, align 4
  ret float %v
}

define float @float_fmin_acquire(ptr %p) nounwind {
; LA64F-LABEL: float_fmin_acquire:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, 260096
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB2_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB2_2 Depth 2
; LA64F-NEXT:    fmin.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB2_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB2_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB2_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB2_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB2_2
; LA64F-NEXT:    b .LBB2_5
; LA64F-NEXT:  .LBB2_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB2_1 Depth=1
; LA64F-NEXT:    dbar 20
; LA64F-NEXT:  .LBB2_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB2_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB2_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fmin_acquire:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1168
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB2_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB2_2 Depth 2
; LA64D-NEXT:    fmin.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB2_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB2_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB2_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB2_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB2_2
; LA64D-NEXT:    b .LBB2_5
; LA64D-NEXT:  .LBB2_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB2_1 Depth=1
; LA64D-NEXT:    dbar 20
; LA64D-NEXT:  .LBB2_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB2_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB2_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fmin ptr %p, float 1.0 acquire, align 4
  ret float %v
}

define float @float_fmax_acquire(ptr %p) nounwind {
; LA64F-LABEL: float_fmax_acquire:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, 260096
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB3_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB3_2 Depth 2
; LA64F-NEXT:    fmax.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB3_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB3_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB3_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB3_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB3_2
; LA64F-NEXT:    b .LBB3_5
; LA64F-NEXT:  .LBB3_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB3_1 Depth=1
; LA64F-NEXT:    dbar 20
; LA64F-NEXT:  .LBB3_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB3_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB3_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fmax_acquire:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1168
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB3_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB3_2 Depth 2
; LA64D-NEXT:    fmax.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB3_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB3_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB3_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB3_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB3_2
; LA64D-NEXT:    b .LBB3_5
; LA64D-NEXT:  .LBB3_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB3_1 Depth=1
; LA64D-NEXT:    dbar 20
; LA64D-NEXT:  .LBB3_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB3_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB3_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fmax ptr %p, float 1.0 acquire, align 4
  ret float %v
}

define double @double_fadd_acquire(ptr %p) nounwind {
; LA64F-LABEL: double_fadd_acquire:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, 1023
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB4_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(__adddf3)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 2
; LA64F-NEXT:    ori $a5, $zero, 2
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB4_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fadd_acquire:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB4_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -912
; LA64D-NEXT:    fadd.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 2
; LA64D-NEXT:    ori $a5, $zero, 2
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB4_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fadd ptr %p, double 1.0 acquire, align 4
  ret double %v
}

define double @double_fsub_acquire(ptr %p) nounwind {
; LA64F-LABEL: double_fsub_acquire:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, -1025
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB5_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(__adddf3)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 2
; LA64F-NEXT:    ori $a5, $zero, 2
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB5_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fsub_acquire:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB5_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -784
; LA64D-NEXT:    fadd.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 2
; LA64D-NEXT:    ori $a5, $zero, 2
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB5_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fsub ptr %p, double 1.0 acquire, align 4
  ret double %v
}

define double @double_fmin_acquire(ptr %p) nounwind {
; LA64F-LABEL: double_fmin_acquire:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, 1023
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB6_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(fmin)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 2
; LA64F-NEXT:    ori $a5, $zero, 2
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB6_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fmin_acquire:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB6_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -912
; LA64D-NEXT:    fmin.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 2
; LA64D-NEXT:    ori $a5, $zero, 2
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB6_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fmin ptr %p, double 1.0 acquire, align 4
  ret double %v
}

define double @double_fmax_acquire(ptr %p) nounwind {
; LA64F-LABEL: double_fmax_acquire:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, 1023
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB7_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(fmax)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 2
; LA64F-NEXT:    ori $a5, $zero, 2
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB7_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fmax_acquire:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB7_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -912
; LA64D-NEXT:    fmax.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 2
; LA64D-NEXT:    ori $a5, $zero, 2
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB7_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fmax ptr %p, double 1.0 acquire, align 4
  ret double %v
}

define float @float_fadd_release(ptr %p) nounwind {
; LA64F-LABEL: float_fadd_release:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, 260096
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB8_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB8_2 Depth 2
; LA64F-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB8_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB8_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB8_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB8_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB8_2
; LA64F-NEXT:    b .LBB8_5
; LA64F-NEXT:  .LBB8_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB8_1 Depth=1
; LA64F-NEXT:    dbar 1792
; LA64F-NEXT:  .LBB8_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB8_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB8_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fadd_release:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1168
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB8_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB8_2 Depth 2
; LA64D-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB8_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB8_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB8_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB8_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB8_2
; LA64D-NEXT:    b .LBB8_5
; LA64D-NEXT:  .LBB8_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB8_1 Depth=1
; LA64D-NEXT:    dbar 1792
; LA64D-NEXT:  .LBB8_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB8_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB8_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fadd ptr %p, float 1.0 release, align 4
  ret float %v
}

define float @float_fsub_release(ptr %p) nounwind {
; LA64F-LABEL: float_fsub_release:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, -264192
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB9_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB9_2 Depth 2
; LA64F-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB9_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB9_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB9_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB9_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB9_2
; LA64F-NEXT:    b .LBB9_5
; LA64F-NEXT:  .LBB9_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB9_1 Depth=1
; LA64F-NEXT:    dbar 1792
; LA64F-NEXT:  .LBB9_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB9_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB9_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fsub_release:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1040
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB9_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB9_2 Depth 2
; LA64D-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB9_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB9_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB9_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB9_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB9_2
; LA64D-NEXT:    b .LBB9_5
; LA64D-NEXT:  .LBB9_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB9_1 Depth=1
; LA64D-NEXT:    dbar 1792
; LA64D-NEXT:  .LBB9_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB9_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB9_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fsub ptr %p, float 1.0 release, align 4
  ret float %v
}

define float @float_fmin_release(ptr %p) nounwind {
; LA64F-LABEL: float_fmin_release:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, 260096
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB10_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB10_2 Depth 2
; LA64F-NEXT:    fmin.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB10_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB10_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB10_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB10_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB10_2
; LA64F-NEXT:    b .LBB10_5
; LA64F-NEXT:  .LBB10_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB10_1 Depth=1
; LA64F-NEXT:    dbar 1792
; LA64F-NEXT:  .LBB10_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB10_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB10_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fmin_release:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1168
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB10_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB10_2 Depth 2
; LA64D-NEXT:    fmin.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB10_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB10_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB10_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB10_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB10_2
; LA64D-NEXT:    b .LBB10_5
; LA64D-NEXT:  .LBB10_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB10_1 Depth=1
; LA64D-NEXT:    dbar 1792
; LA64D-NEXT:  .LBB10_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB10_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB10_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fmin ptr %p, float 1.0 release, align 4
  ret float %v
}

define float @float_fmax_release(ptr %p) nounwind {
; LA64F-LABEL: float_fmax_release:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, 260096
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB11_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB11_2 Depth 2
; LA64F-NEXT:    fmax.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB11_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB11_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB11_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB11_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB11_2
; LA64F-NEXT:    b .LBB11_5
; LA64F-NEXT:  .LBB11_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB11_1 Depth=1
; LA64F-NEXT:    dbar 1792
; LA64F-NEXT:  .LBB11_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB11_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB11_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fmax_release:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1168
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB11_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB11_2 Depth 2
; LA64D-NEXT:    fmax.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB11_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB11_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB11_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB11_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB11_2
; LA64D-NEXT:    b .LBB11_5
; LA64D-NEXT:  .LBB11_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB11_1 Depth=1
; LA64D-NEXT:    dbar 1792
; LA64D-NEXT:  .LBB11_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB11_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB11_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fmax ptr %p, float 1.0 release, align 4
  ret float %v
}

define double @double_fadd_release(ptr %p) nounwind {
; LA64F-LABEL: double_fadd_release:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, 1023
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB12_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(__adddf3)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 3
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    move $a5, $zero
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB12_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fadd_release:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB12_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -912
; LA64D-NEXT:    fadd.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 3
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    move $a5, $zero
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB12_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fadd ptr %p, double 1.0 release, align 4
  ret double %v
}

define double @double_fsub_release(ptr %p) nounwind {
; LA64F-LABEL: double_fsub_release:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, -1025
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB13_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(__adddf3)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 3
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    move $a5, $zero
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB13_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fsub_release:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB13_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -784
; LA64D-NEXT:    fadd.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 3
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    move $a5, $zero
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB13_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fsub ptr %p, double 1.0 release, align 4
  ret double %v
}

define double @double_fmin_release(ptr %p) nounwind {
; LA64F-LABEL: double_fmin_release:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, 1023
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB14_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(fmin)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 3
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    move $a5, $zero
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB14_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fmin_release:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB14_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -912
; LA64D-NEXT:    fmin.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 3
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    move $a5, $zero
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB14_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fmin ptr %p, double 1.0 release, align 4
  ret double %v
}

define double @double_fmax_release(ptr %p) nounwind {
; LA64F-LABEL: double_fmax_release:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, 1023
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB15_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(fmax)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 3
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    move $a5, $zero
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB15_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fmax_release:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB15_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -912
; LA64D-NEXT:    fmax.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 3
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    move $a5, $zero
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB15_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fmax ptr %p, double 1.0 release, align 4
  ret double %v
}

define float @float_fadd_acq_rel(ptr %p) nounwind {
; LA64F-LABEL: float_fadd_acq_rel:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, 260096
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB16_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB16_2 Depth 2
; LA64F-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB16_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB16_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB16_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB16_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB16_2
; LA64F-NEXT:    b .LBB16_5
; LA64F-NEXT:  .LBB16_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB16_1 Depth=1
; LA64F-NEXT:    dbar 20
; LA64F-NEXT:  .LBB16_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB16_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB16_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fadd_acq_rel:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1168
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB16_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB16_2 Depth 2
; LA64D-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB16_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB16_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB16_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB16_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB16_2
; LA64D-NEXT:    b .LBB16_5
; LA64D-NEXT:  .LBB16_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB16_1 Depth=1
; LA64D-NEXT:    dbar 20
; LA64D-NEXT:  .LBB16_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB16_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB16_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fadd ptr %p, float 1.0 acq_rel, align 4
  ret float %v
}

define float @float_fsub_acq_rel(ptr %p) nounwind {
; LA64F-LABEL: float_fsub_acq_rel:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, -264192
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB17_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB17_2 Depth 2
; LA64F-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB17_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB17_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB17_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB17_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB17_2
; LA64F-NEXT:    b .LBB17_5
; LA64F-NEXT:  .LBB17_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB17_1 Depth=1
; LA64F-NEXT:    dbar 20
; LA64F-NEXT:  .LBB17_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB17_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB17_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fsub_acq_rel:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1040
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB17_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB17_2 Depth 2
; LA64D-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB17_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB17_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB17_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB17_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB17_2
; LA64D-NEXT:    b .LBB17_5
; LA64D-NEXT:  .LBB17_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB17_1 Depth=1
; LA64D-NEXT:    dbar 20
; LA64D-NEXT:  .LBB17_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB17_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB17_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fsub ptr %p, float 1.0 acq_rel, align 4
  ret float %v
}

define float @float_fmin_acq_rel(ptr %p) nounwind {
; LA64F-LABEL: float_fmin_acq_rel:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, 260096
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB18_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB18_2 Depth 2
; LA64F-NEXT:    fmin.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB18_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB18_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB18_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB18_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB18_2
; LA64F-NEXT:    b .LBB18_5
; LA64F-NEXT:  .LBB18_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB18_1 Depth=1
; LA64F-NEXT:    dbar 20
; LA64F-NEXT:  .LBB18_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB18_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB18_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fmin_acq_rel:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1168
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB18_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB18_2 Depth 2
; LA64D-NEXT:    fmin.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB18_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB18_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB18_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB18_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB18_2
; LA64D-NEXT:    b .LBB18_5
; LA64D-NEXT:  .LBB18_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB18_1 Depth=1
; LA64D-NEXT:    dbar 20
; LA64D-NEXT:  .LBB18_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB18_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB18_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fmin ptr %p, float 1.0 acq_rel, align 4
  ret float %v
}

define float @float_fmax_acq_rel(ptr %p) nounwind {
; LA64F-LABEL: float_fmax_acq_rel:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, 260096
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB19_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB19_2 Depth 2
; LA64F-NEXT:    fmax.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB19_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB19_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB19_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB19_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB19_2
; LA64F-NEXT:    b .LBB19_5
; LA64F-NEXT:  .LBB19_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB19_1 Depth=1
; LA64F-NEXT:    dbar 20
; LA64F-NEXT:  .LBB19_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB19_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB19_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fmax_acq_rel:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1168
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB19_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB19_2 Depth 2
; LA64D-NEXT:    fmax.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB19_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB19_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB19_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB19_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB19_2
; LA64D-NEXT:    b .LBB19_5
; LA64D-NEXT:  .LBB19_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB19_1 Depth=1
; LA64D-NEXT:    dbar 20
; LA64D-NEXT:  .LBB19_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB19_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB19_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fmax ptr %p, float 1.0 acq_rel, align 4
  ret float %v
}

define double @double_fadd_acq_rel(ptr %p) nounwind {
; LA64F-LABEL: double_fadd_acq_rel:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, 1023
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB20_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(__adddf3)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 4
; LA64F-NEXT:    ori $a5, $zero, 2
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB20_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fadd_acq_rel:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB20_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -912
; LA64D-NEXT:    fadd.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 4
; LA64D-NEXT:    ori $a5, $zero, 2
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB20_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fadd ptr %p, double 1.0 acq_rel, align 4
  ret double %v
}

define double @double_fsub_acq_rel(ptr %p) nounwind {
; LA64F-LABEL: double_fsub_acq_rel:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, -1025
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB21_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(__adddf3)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 4
; LA64F-NEXT:    ori $a5, $zero, 2
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB21_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fsub_acq_rel:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB21_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -784
; LA64D-NEXT:    fadd.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 4
; LA64D-NEXT:    ori $a5, $zero, 2
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB21_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fsub ptr %p, double 1.0 acq_rel, align 4
  ret double %v
}

define double @double_fmin_acq_rel(ptr %p) nounwind {
; LA64F-LABEL: double_fmin_acq_rel:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, 1023
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB22_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(fmin)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 4
; LA64F-NEXT:    ori $a5, $zero, 2
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB22_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fmin_acq_rel:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB22_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -912
; LA64D-NEXT:    fmin.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 4
; LA64D-NEXT:    ori $a5, $zero, 2
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB22_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fmin ptr %p, double 1.0 acq_rel, align 4
  ret double %v
}

define double @double_fmax_acq_rel(ptr %p) nounwind {
; LA64F-LABEL: double_fmax_acq_rel:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, 1023
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB23_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(fmax)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 4
; LA64F-NEXT:    ori $a5, $zero, 2
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB23_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fmax_acq_rel:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB23_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -912
; LA64D-NEXT:    fmax.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 4
; LA64D-NEXT:    ori $a5, $zero, 2
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB23_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fmax ptr %p, double 1.0 acq_rel, align 4
  ret double %v
}

define float @float_fadd_seq_cst(ptr %p) nounwind {
; LA64F-LABEL: float_fadd_seq_cst:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, 260096
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB24_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB24_2 Depth 2
; LA64F-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB24_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB24_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB24_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB24_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB24_2
; LA64F-NEXT:    b .LBB24_5
; LA64F-NEXT:  .LBB24_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB24_1 Depth=1
; LA64F-NEXT:    dbar 20
; LA64F-NEXT:  .LBB24_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB24_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB24_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fadd_seq_cst:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1168
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB24_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB24_2 Depth 2
; LA64D-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB24_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB24_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB24_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB24_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB24_2
; LA64D-NEXT:    b .LBB24_5
; LA64D-NEXT:  .LBB24_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB24_1 Depth=1
; LA64D-NEXT:    dbar 20
; LA64D-NEXT:  .LBB24_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB24_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB24_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fadd ptr %p, float 1.0 seq_cst, align 4
  ret float %v
}

define float @float_fsub_seq_cst(ptr %p) nounwind {
; LA64F-LABEL: float_fsub_seq_cst:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, -264192
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB25_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB25_2 Depth 2
; LA64F-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB25_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB25_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB25_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB25_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB25_2
; LA64F-NEXT:    b .LBB25_5
; LA64F-NEXT:  .LBB25_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB25_1 Depth=1
; LA64F-NEXT:    dbar 20
; LA64F-NEXT:  .LBB25_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB25_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB25_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fsub_seq_cst:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1040
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB25_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB25_2 Depth 2
; LA64D-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB25_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB25_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB25_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB25_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB25_2
; LA64D-NEXT:    b .LBB25_5
; LA64D-NEXT:  .LBB25_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB25_1 Depth=1
; LA64D-NEXT:    dbar 20
; LA64D-NEXT:  .LBB25_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB25_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB25_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fsub ptr %p, float 1.0 seq_cst, align 4
  ret float %v
}

define float @float_fmin_seq_cst(ptr %p) nounwind {
; LA64F-LABEL: float_fmin_seq_cst:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, 260096
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB26_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB26_2 Depth 2
; LA64F-NEXT:    fmin.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB26_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB26_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB26_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB26_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB26_2
; LA64F-NEXT:    b .LBB26_5
; LA64F-NEXT:  .LBB26_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB26_1 Depth=1
; LA64F-NEXT:    dbar 20
; LA64F-NEXT:  .LBB26_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB26_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB26_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fmin_seq_cst:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1168
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB26_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB26_2 Depth 2
; LA64D-NEXT:    fmin.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB26_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB26_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB26_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB26_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB26_2
; LA64D-NEXT:    b .LBB26_5
; LA64D-NEXT:  .LBB26_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB26_1 Depth=1
; LA64D-NEXT:    dbar 20
; LA64D-NEXT:  .LBB26_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB26_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB26_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fmin ptr %p, float 1.0 seq_cst, align 4
  ret float %v
}

define float @float_fmax_seq_cst(ptr %p) nounwind {
; LA64F-LABEL: float_fmax_seq_cst:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, 260096
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB27_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB27_2 Depth 2
; LA64F-NEXT:    fmax.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB27_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB27_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB27_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB27_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB27_2
; LA64F-NEXT:    b .LBB27_5
; LA64F-NEXT:  .LBB27_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB27_1 Depth=1
; LA64F-NEXT:    dbar 20
; LA64F-NEXT:  .LBB27_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB27_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB27_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fmax_seq_cst:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1168
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB27_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB27_2 Depth 2
; LA64D-NEXT:    fmax.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB27_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB27_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB27_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB27_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB27_2
; LA64D-NEXT:    b .LBB27_5
; LA64D-NEXT:  .LBB27_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB27_1 Depth=1
; LA64D-NEXT:    dbar 20
; LA64D-NEXT:  .LBB27_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB27_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB27_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fmax ptr %p, float 1.0 seq_cst, align 4
  ret float %v
}

define double @double_fadd_seq_cst(ptr %p) nounwind {
; LA64F-LABEL: double_fadd_seq_cst:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, 1023
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB28_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(__adddf3)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 5
; LA64F-NEXT:    ori $a5, $zero, 5
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB28_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fadd_seq_cst:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB28_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -912
; LA64D-NEXT:    fadd.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 5
; LA64D-NEXT:    ori $a5, $zero, 5
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB28_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fadd ptr %p, double 1.0 seq_cst, align 4
  ret double %v
}

define double @double_fsub_seq_cst(ptr %p) nounwind {
; LA64F-LABEL: double_fsub_seq_cst:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, -1025
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB29_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(__adddf3)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 5
; LA64F-NEXT:    ori $a5, $zero, 5
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB29_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fsub_seq_cst:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB29_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -784
; LA64D-NEXT:    fadd.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 5
; LA64D-NEXT:    ori $a5, $zero, 5
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB29_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fsub ptr %p, double 1.0 seq_cst, align 4
  ret double %v
}

define double @double_fmin_seq_cst(ptr %p) nounwind {
; LA64F-LABEL: double_fmin_seq_cst:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, 1023
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB30_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(fmin)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 5
; LA64F-NEXT:    ori $a5, $zero, 5
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB30_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fmin_seq_cst:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB30_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -912
; LA64D-NEXT:    fmin.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 5
; LA64D-NEXT:    ori $a5, $zero, 5
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB30_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fmin ptr %p, double 1.0 seq_cst, align 4
  ret double %v
}

define double @double_fmax_seq_cst(ptr %p) nounwind {
; LA64F-LABEL: double_fmax_seq_cst:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, 1023
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB31_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(fmax)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    ori $a4, $zero, 5
; LA64F-NEXT:    ori $a5, $zero, 5
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB31_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fmax_seq_cst:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB31_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -912
; LA64D-NEXT:    fmax.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    ori $a4, $zero, 5
; LA64D-NEXT:    ori $a5, $zero, 5
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB31_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fmax ptr %p, double 1.0 seq_cst, align 4
  ret double %v
}

define float @float_fadd_monotonic(ptr %p) nounwind {
; LA64F-LABEL: float_fadd_monotonic:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, 260096
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB32_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB32_2 Depth 2
; LA64F-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB32_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB32_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB32_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB32_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB32_2
; LA64F-NEXT:    b .LBB32_5
; LA64F-NEXT:  .LBB32_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB32_1 Depth=1
; LA64F-NEXT:    dbar 1792
; LA64F-NEXT:  .LBB32_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB32_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB32_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fadd_monotonic:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1168
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB32_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB32_2 Depth 2
; LA64D-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB32_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB32_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB32_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB32_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB32_2
; LA64D-NEXT:    b .LBB32_5
; LA64D-NEXT:  .LBB32_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB32_1 Depth=1
; LA64D-NEXT:    dbar 1792
; LA64D-NEXT:  .LBB32_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB32_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB32_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fadd ptr %p, float 1.0 monotonic, align 4
  ret float %v
}

define float @float_fsub_monotonic(ptr %p) nounwind {
; LA64F-LABEL: float_fsub_monotonic:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, -264192
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB33_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB33_2 Depth 2
; LA64F-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB33_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB33_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB33_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB33_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB33_2
; LA64F-NEXT:    b .LBB33_5
; LA64F-NEXT:  .LBB33_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB33_1 Depth=1
; LA64F-NEXT:    dbar 1792
; LA64F-NEXT:  .LBB33_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB33_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB33_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fsub_monotonic:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1040
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB33_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB33_2 Depth 2
; LA64D-NEXT:    fadd.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB33_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB33_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB33_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB33_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB33_2
; LA64D-NEXT:    b .LBB33_5
; LA64D-NEXT:  .LBB33_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB33_1 Depth=1
; LA64D-NEXT:    dbar 1792
; LA64D-NEXT:  .LBB33_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB33_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB33_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fsub ptr %p, float 1.0 monotonic, align 4
  ret float %v
}

define float @float_fmin_monotonic(ptr %p) nounwind {
; LA64F-LABEL: float_fmin_monotonic:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, 260096
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB34_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB34_2 Depth 2
; LA64F-NEXT:    fmin.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB34_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB34_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB34_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB34_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB34_2
; LA64F-NEXT:    b .LBB34_5
; LA64F-NEXT:  .LBB34_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB34_1 Depth=1
; LA64F-NEXT:    dbar 1792
; LA64F-NEXT:  .LBB34_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB34_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB34_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fmin_monotonic:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1168
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB34_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB34_2 Depth 2
; LA64D-NEXT:    fmin.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB34_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB34_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB34_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB34_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB34_2
; LA64D-NEXT:    b .LBB34_5
; LA64D-NEXT:  .LBB34_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB34_1 Depth=1
; LA64D-NEXT:    dbar 1792
; LA64D-NEXT:  .LBB34_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB34_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB34_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fmin ptr %p, float 1.0 monotonic, align 4
  ret float %v
}

define float @float_fmax_monotonic(ptr %p) nounwind {
; LA64F-LABEL: float_fmax_monotonic:
; LA64F:       # %bb.0:
; LA64F-NEXT:    fld.s $fa0, $a0, 0
; LA64F-NEXT:    lu12i.w $a1, 260096
; LA64F-NEXT:    movgr2fr.w $fa1, $a1
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB35_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Loop Header: Depth=1
; LA64F-NEXT:    # Child Loop BB35_2 Depth 2
; LA64F-NEXT:    fmax.s $fa2, $fa0, $fa1
; LA64F-NEXT:    movfr2gr.s $a1, $fa2
; LA64F-NEXT:    movfr2gr.s $a2, $fa0
; LA64F-NEXT:  .LBB35_2: # %atomicrmw.start
; LA64F-NEXT:    # Parent Loop BB35_1 Depth=1
; LA64F-NEXT:    # => This Inner Loop Header: Depth=2
; LA64F-NEXT:    ll.w $a3, $a0, 0
; LA64F-NEXT:    bne $a3, $a2, .LBB35_4
; LA64F-NEXT:  # %bb.3: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB35_2 Depth=2
; LA64F-NEXT:    move $a4, $a1
; LA64F-NEXT:    sc.w $a4, $a0, 0
; LA64F-NEXT:    beq $a4, $zero, .LBB35_2
; LA64F-NEXT:    b .LBB35_5
; LA64F-NEXT:  .LBB35_4: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB35_1 Depth=1
; LA64F-NEXT:    dbar 1792
; LA64F-NEXT:  .LBB35_5: # %atomicrmw.start
; LA64F-NEXT:    # in Loop: Header=BB35_1 Depth=1
; LA64F-NEXT:    movgr2fr.w $fa0, $a3
; LA64F-NEXT:    bne $a3, $a2, .LBB35_1
; LA64F-NEXT:  # %bb.6: # %atomicrmw.end
; LA64F-NEXT:    ret
;
; LA64D-LABEL: float_fmax_monotonic:
; LA64D:       # %bb.0:
; LA64D-NEXT:    fld.s $fa0, $a0, 0
; LA64D-NEXT:    vldi $vr1, -1168
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB35_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Loop Header: Depth=1
; LA64D-NEXT:    # Child Loop BB35_2 Depth 2
; LA64D-NEXT:    fmax.s $fa2, $fa0, $fa1
; LA64D-NEXT:    movfr2gr.s $a1, $fa2
; LA64D-NEXT:    movfr2gr.s $a2, $fa0
; LA64D-NEXT:  .LBB35_2: # %atomicrmw.start
; LA64D-NEXT:    # Parent Loop BB35_1 Depth=1
; LA64D-NEXT:    # => This Inner Loop Header: Depth=2
; LA64D-NEXT:    ll.w $a3, $a0, 0
; LA64D-NEXT:    bne $a3, $a2, .LBB35_4
; LA64D-NEXT:  # %bb.3: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB35_2 Depth=2
; LA64D-NEXT:    move $a4, $a1
; LA64D-NEXT:    sc.w $a4, $a0, 0
; LA64D-NEXT:    beq $a4, $zero, .LBB35_2
; LA64D-NEXT:    b .LBB35_5
; LA64D-NEXT:  .LBB35_4: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB35_1 Depth=1
; LA64D-NEXT:    dbar 1792
; LA64D-NEXT:  .LBB35_5: # %atomicrmw.start
; LA64D-NEXT:    # in Loop: Header=BB35_1 Depth=1
; LA64D-NEXT:    movgr2fr.w $fa0, $a3
; LA64D-NEXT:    bne $a3, $a2, .LBB35_1
; LA64D-NEXT:  # %bb.6: # %atomicrmw.end
; LA64D-NEXT:    ret
  %v = atomicrmw fmax ptr %p, float 1.0 monotonic, align 4
  ret float %v
}

define double @double_fadd_monotonic(ptr %p) nounwind {
; LA64F-LABEL: double_fadd_monotonic:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, 1023
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB36_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(__adddf3)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    move $a4, $zero
; LA64F-NEXT:    move $a5, $zero
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB36_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fadd_monotonic:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB36_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -912
; LA64D-NEXT:    fadd.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    move $a4, $zero
; LA64D-NEXT:    move $a5, $zero
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB36_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fadd ptr %p, double 1.0 monotonic, align 4
  ret double %v
}

define double @double_fsub_monotonic(ptr %p) nounwind {
; LA64F-LABEL: double_fsub_monotonic:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, -1025
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB37_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(__adddf3)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    move $a4, $zero
; LA64F-NEXT:    move $a5, $zero
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB37_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fsub_monotonic:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB37_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -784
; LA64D-NEXT:    fadd.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    move $a4, $zero
; LA64D-NEXT:    move $a5, $zero
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB37_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fsub ptr %p, double 1.0 monotonic, align 4
  ret double %v
}

define double @double_fmin_monotonic(ptr %p) nounwind {
; LA64F-LABEL: double_fmin_monotonic:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, 1023
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB38_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(fmin)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    move $a4, $zero
; LA64F-NEXT:    move $a5, $zero
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB38_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fmin_monotonic:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB38_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -912
; LA64D-NEXT:    fmin.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    move $a4, $zero
; LA64D-NEXT:    move $a5, $zero
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB38_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fmin ptr %p, double 1.0 monotonic, align 4
  ret double %v
}

define double @double_fmax_monotonic(ptr %p) nounwind {
; LA64F-LABEL: double_fmax_monotonic:
; LA64F:       # %bb.0:
; LA64F-NEXT:    addi.d $sp, $sp, -48
; LA64F-NEXT:    st.d $ra, $sp, 40 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $fp, $sp, 32 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s0, $sp, 24 # 8-byte Folded Spill
; LA64F-NEXT:    st.d $s1, $sp, 16 # 8-byte Folded Spill
; LA64F-NEXT:    move $fp, $a0
; LA64F-NEXT:    ld.d $s1, $a0, 0
; LA64F-NEXT:    lu52i.d $s0, $zero, 1023
; LA64F-NEXT:    .p2align 4, , 16
; LA64F-NEXT:  .LBB39_1: # %atomicrmw.start
; LA64F-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    move $a1, $s0
; LA64F-NEXT:    pcaddu18i $ra, %call36(fmax)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    st.d $s1, $sp, 8
; LA64F-NEXT:    st.d $a0, $sp, 0
; LA64F-NEXT:    ori $a0, $zero, 8
; LA64F-NEXT:    addi.d $a2, $sp, 8
; LA64F-NEXT:    addi.d $a3, $sp, 0
; LA64F-NEXT:    move $a1, $fp
; LA64F-NEXT:    move $a4, $zero
; LA64F-NEXT:    move $a5, $zero
; LA64F-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64F-NEXT:    jirl $ra, $ra, 0
; LA64F-NEXT:    ld.d $s1, $sp, 8
; LA64F-NEXT:    beqz $a0, .LBB39_1
; LA64F-NEXT:  # %bb.2: # %atomicrmw.end
; LA64F-NEXT:    move $a0, $s1
; LA64F-NEXT:    ld.d $s1, $sp, 16 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $s0, $sp, 24 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $fp, $sp, 32 # 8-byte Folded Reload
; LA64F-NEXT:    ld.d $ra, $sp, 40 # 8-byte Folded Reload
; LA64F-NEXT:    addi.d $sp, $sp, 48
; LA64F-NEXT:    ret
;
; LA64D-LABEL: double_fmax_monotonic:
; LA64D:       # %bb.0:
; LA64D-NEXT:    addi.d $sp, $sp, -32
; LA64D-NEXT:    st.d $ra, $sp, 24 # 8-byte Folded Spill
; LA64D-NEXT:    st.d $fp, $sp, 16 # 8-byte Folded Spill
; LA64D-NEXT:    move $fp, $a0
; LA64D-NEXT:    fld.d $fa0, $a0, 0
; LA64D-NEXT:    .p2align 4, , 16
; LA64D-NEXT:  .LBB39_1: # %atomicrmw.start
; LA64D-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64D-NEXT:    vldi $vr1, -912
; LA64D-NEXT:    fmax.d $fa1, $fa0, $fa1
; LA64D-NEXT:    fst.d $fa0, $sp, 8
; LA64D-NEXT:    fst.d $fa1, $sp, 0
; LA64D-NEXT:    ori $a0, $zero, 8
; LA64D-NEXT:    addi.d $a2, $sp, 8
; LA64D-NEXT:    addi.d $a3, $sp, 0
; LA64D-NEXT:    move $a1, $fp
; LA64D-NEXT:    move $a4, $zero
; LA64D-NEXT:    move $a5, $zero
; LA64D-NEXT:    pcaddu18i $ra, %call36(__atomic_compare_exchange)
; LA64D-NEXT:    jirl $ra, $ra, 0
; LA64D-NEXT:    fld.d $fa0, $sp, 8
; LA64D-NEXT:    beqz $a0, .LBB39_1
; LA64D-NEXT:  # %bb.2: # %atomicrmw.end
; LA64D-NEXT:    ld.d $fp, $sp, 16 # 8-byte Folded Reload
; LA64D-NEXT:    ld.d $ra, $sp, 24 # 8-byte Folded Reload
; LA64D-NEXT:    addi.d $sp, $sp, 32
; LA64D-NEXT:    ret
  %v = atomicrmw fmax ptr %p, double 1.0 monotonic, align 4
  ret double %v
}
