; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc --mtriple=loongarch32 --mattr=+d < %s | FileCheck %s --check-prefix=LA32
; RUN: llc --mtriple=loongarch64 --mattr=+d < %s | FileCheck %s --check-prefix=LA64

declare float @llvm.log2.f32(float)
declare double @llvm.log2.f64(double)

define float @flog2_s(float %x) nounwind {
; LA32-LABEL: flog2_s:
; LA32:       # %bb.0:
; LA32-NEXT:    b log2f
;
; LA64-LABEL: flog2_s:
; LA64:       # %bb.0:
; LA64-NEXT:    flogb.s $fa0, $fa0
; LA64-NEXT:    ret
  %y = call float @llvm.log2.f32(float %x)
  ret float %y
}

define double @flog2_d(double %x) nounwind {
; LA32-LABEL: flog2_d:
; LA32:       # %bb.0:
; LA32-NEXT:    b log2
;
; LA64-LABEL: flog2_d:
; LA64:       # %bb.0:
; LA64-NEXT:    flogb.d $fa0, $fa0
; LA64-NEXT:    ret
  %y = call double @llvm.log2.f64(double %x)
  ret double %y
}
