//===-- LlvmOps.td - Entry point for llvm bind ---------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_LLVM_OPS
#define PYTHON_BINDINGS_LLVM_OPS

include "mlir/Dialect/LLVMIR/LLVMOps.td"

#endif
