//===-- TensorTransformOps.td ------------------------------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Entry point of the Python bindings generator for the transform ops provided
// by the tensor dialect.
//
//===----------------------------------------------------------------------===//


#ifndef PYTHON_BINDINGS_TENSOR_TRANSFORM_OPS
#define PYTHON_BINDINGS_TENSOR_TRANSFORM_OPS

include "mlir/Dialect/Tensor/TransformOps/TensorTransformOps.td"

#endif // PYTHON_BINDINGS_TENSOR_TRANSFORM_OPS
