//===-- TransformPDLExtensionOps.td - Binding entry point --*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Entry point of the generated Python bindings for the PDL extension of the
// Transform dialect.
//
//===----------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_TRANSFORM_PDL_EXTENSION_OPS
#define PYTHON_BINDINGS_TRANSFORM_PDL_EXTENSION_OPS

include "mlir/Dialect/Transform/PDLExtension/PDLExtensionOps.td"

#endif // PYTHON_BINDINGS_TRANSFORM_PDL_EXTENSION_OPS
