; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=jump-table-to-switch -S | FileCheck %s

;; Test that when target functions lack !guid metadata, the pass correctly
;; computes GUIDs from the target function names (not the caller's name)
;; for matching against value profile data. This is a regression test for
;; a bug where the caller function was used instead of the callee when
;; computing PGO function names for GUID lookup.

@jt = constant [2 x ptr] [ptr @jt_target_0, ptr @jt_target_1]

;; Note: these functions intentionally do NOT have !guid metadata,
;; forcing the pass to compute GUIDs via getIRPGOFuncName.
define i32 @jt_target_0() {
; CHECK-LABEL: define i32 @jt_target_0() {
; CHECK-NEXT:    ret i32 10
;
  ret i32 10
}

define i32 @jt_target_1() {
; CHECK-LABEL: define i32 @jt_target_1() {
; CHECK-NEXT:    ret i32 20
;
  ret i32 20
}

define i32 @caller(i32 %idx) {
; CHECK-LABEL: define i32 @caller(
; CHECK-SAME: i32 [[IDX:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [2 x ptr], ptr @jt, i32 0, i32 [[IDX]]
; CHECK-NEXT:    [[FPTR:%.*]] = load ptr, ptr [[GEP]], align 8
; CHECK-NEXT:    switch i32 [[IDX]], label %[[DEFAULT_SWITCH_CASE_UNREACHABLE:.*]] [
; CHECK-NEXT:      i32 0, label %[[CALL0:.*]]
; CHECK-NEXT:      i32 1, label %[[CALL1:.*]]
; CHECK-NEXT:    ], !prof [[PROF0:![0-9]+]]
; CHECK:       [[DEFAULT_SWITCH_CASE_UNREACHABLE]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[CALL0]]:
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @jt_target_0()
; CHECK-NEXT:    br [[DOTTAIL:label %.*]]
; CHECK:       [[CALL1]]:
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @jt_target_1()
; CHECK-NEXT:    br [[DOTTAIL]]
; CHECK:       [[_TAIL:.*:]]
; CHECK-NEXT:    [[TMP3:%.*]] = phi i32 [ [[TMP1]], %[[CALL0]] ], [ [[TMP2]], %[[CALL1]] ]
; CHECK-NEXT:    ret i32 [[TMP3]]
;
  %gep = getelementptr inbounds [2 x ptr], ptr @jt, i32 0, i32 %idx
  %fptr = load ptr, ptr %gep
  %r = call i32 %fptr(), !prof !0
  ret i32 %r
}

define i32 @caller_only_zero_guids(i32 %idx) {
; CHECK-LABEL: define i32 @caller_only_zero_guids(
; CHECK-SAME: i32 [[IDX:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [2 x ptr], ptr @jt, i32 0, i32 [[IDX]]
; CHECK-NEXT:    [[FPTR:%.*]] = load ptr, ptr [[GEP]], align 8
; CHECK-NEXT:    switch i32 [[IDX]], label %[[DEFAULT_SWITCH_CASE_UNREACHABLE:.*]] [
; CHECK-NEXT:      i32 0, label %[[CALL_0:.*]]
; CHECK-NEXT:      i32 1, label %[[CALL_1:.*]]
; CHECK-NEXT:    ], !prof [[PROF1:![0-9]+]]
; CHECK:       [[DEFAULT_SWITCH_CASE_UNREACHABLE]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[CALL_0]]:
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @jt_target_0()
; CHECK-NEXT:    br [[DOTTAIL:label %.*]]
; CHECK:       [[CALL_1]]:
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @jt_target_1()
; CHECK-NEXT:    br [[DOTTAIL]]
; CHECK:       [[_TAIL:.*:]]
; CHECK-NEXT:    [[TMP3:%.*]] = phi i32 [ [[TMP1]], %[[CALL_0]] ], [ [[TMP2]], %[[CALL_1]] ]
; CHECK-NEXT:    ret i32 [[TMP3]]
;
  %gep = getelementptr inbounds [2 x ptr], ptr @jt, i32 0, i32 %idx
  %fptr = load ptr, ptr %gep
  %r = call i32 %fptr(), !prof !1
  ret i32 %r
}

;; VP metadata: GUID 11912887233601027218 = MD5("jt_target_0"), count 100
;;              GUID 18156790114353049777 = MD5("jt_target_1"), count 50
!0 = !{!"VP", i32 0, i64 150, i64 11912887233601027218, i64 100, i64 18156790114353049777, i64 50}

;; VP metadata with only a zero value.
!1 = !{!"VP", i32 0, i64 150, i64 0, i64 40}

;.
; CHECK: [[PROF0]] = !{!"branch_weights", i32 0, i32 100, i32 50}
; CHECK: [[PROF1]] = !{!"unknown", !"jump-table-to-switch"}
;.
