; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -hexagon-autohvx -passes=loop-vectorize -S < %s | FileCheck %s
; Check that the loop has been interleaved.

target datalayout = "e-m:e-p:32:32:32-a:0-n16:32-i64:64:64-i32:32:32-i16:16:16-i1:8:8-f32:32:32-f64:64:64-v32:32:32-v64:64:64-v512:512:512-v1024:1024:1024-v2048:2048:2048"
target triple = "hexagon"

define void @f0(ptr noalias nocapture %a0, ptr noalias nocapture readonly %a1, i32 %a2) #0 {
; CHECK-LABEL: define void @f0(
; CHECK-SAME: ptr noalias captures(none) [[A0:%.*]], ptr noalias readonly captures(none) [[A1:%.*]], i32 [[A2:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[B0:.*:]]
; CHECK-NEXT:    [[V0:%.*]] = icmp eq i32 [[A2]], 0
; CHECK-NEXT:    br i1 [[V0]], label %[[B3:.*]], label %[[ITER_CHECK:.*]]
; CHECK:       [[ITER_CHECK]]:
; CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[A2]], -2
; CHECK-NEXT:    [[TMP1:%.*]] = lshr i32 [[TMP0]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = add nuw i32 [[TMP1]], 1
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i32 [[TMP2]], 16
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[VEC_EPILOG_SCALAR_PH:.*]], label %[[VECTOR_MAIN_LOOP_ITER_CHECK:.*]]
; CHECK:       [[VECTOR_MAIN_LOOP_ITER_CHECK]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK1:%.*]] = icmp ult i32 [[TMP2]], 32
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK1]], label %[[VEC_EPILOG_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i32 [[TMP2]], 16
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i32 [[TMP2]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP3:%.*]] = shl i32 [[N_VEC]], 1
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i32 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = shl i32 [[INDEX]], 1
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i32, ptr [[A1]], i32 [[TMP4]]
; CHECK-NEXT:    [[STRIDED_VEC2:%.*]] = load <32 x i32>, ptr [[TMP5]], align 4, !tbaa [[INT_TBAA1:![0-9]+]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i32, ptr [[A0]], i32 [[TMP4]]
; CHECK-NEXT:    [[STRIDED_VEC5:%.*]] = load <32 x i32>, ptr [[TMP6]], align 4, !tbaa [[INT_TBAA1]]
; CHECK-NEXT:    [[TMP8:%.*]] = add nsw <32 x i32> [[STRIDED_VEC5]], [[STRIDED_VEC2]]
; CHECK-NEXT:    store <32 x i32> [[TMP8]], ptr [[TMP6]], align 4, !tbaa [[INT_TBAA1]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i32 [[INDEX]], 16
; CHECK-NEXT:    [[TMP10:%.*]] = icmp eq i32 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP10]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i32 [[TMP2]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[B2:.*]], label %[[VEC_EPILOG_ITER_CHECK:.*]]
; CHECK:       [[VEC_EPILOG_ITER_CHECK]]:
; CHECK-NEXT:    [[MIN_EPILOG_ITERS_CHECK:%.*]] = icmp ult i32 [[N_MOD_VF]], 16
; CHECK-NEXT:    br i1 [[MIN_EPILOG_ITERS_CHECK]], label %[[VEC_EPILOG_SCALAR_PH]], label %[[VEC_EPILOG_PH]], !prof [[PROF9:![0-9]+]]
; CHECK:       [[VEC_EPILOG_PH]]:
; CHECK-NEXT:    [[VEC_EPILOG_RESUME_VAL:%.*]] = phi i32 [ [[N_VEC]], %[[VEC_EPILOG_ITER_CHECK]] ], [ 0, %[[VECTOR_MAIN_LOOP_ITER_CHECK]] ]
; CHECK-NEXT:    [[N_MOD_VF6:%.*]] = urem i32 [[TMP2]], 16
; CHECK-NEXT:    [[N_VEC7:%.*]] = sub i32 [[TMP2]], [[N_MOD_VF6]]
; CHECK-NEXT:    [[TMP11:%.*]] = shl i32 [[N_VEC7]], 1
; CHECK-NEXT:    br label %[[VEC_EPILOG_VECTOR_BODY:.*]]
; CHECK:       [[VEC_EPILOG_VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX8:%.*]] = phi i32 [ [[VEC_EPILOG_RESUME_VAL]], %[[VEC_EPILOG_PH]] ], [ [[INDEX_NEXT16:%.*]], %[[VEC_EPILOG_VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP12:%.*]] = shl i32 [[INDEX8]], 1
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i32, ptr [[A1]], i32 [[TMP12]]
; CHECK-NEXT:    [[WIDE_VEC9:%.*]] = load <32 x i32>, ptr [[TMP13]], align 4, !tbaa [[INT_TBAA1]]
; CHECK-NEXT:    [[STRIDED_VEC10:%.*]] = shufflevector <32 x i32> [[WIDE_VEC9]], <32 x i32> poison, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
; CHECK-NEXT:    [[STRIDED_VEC11:%.*]] = shufflevector <32 x i32> [[WIDE_VEC9]], <32 x i32> poison, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i32, ptr [[A0]], i32 [[TMP12]]
; CHECK-NEXT:    [[WIDE_VEC12:%.*]] = load <32 x i32>, ptr [[TMP14]], align 4, !tbaa [[INT_TBAA1]]
; CHECK-NEXT:    [[STRIDED_VEC13:%.*]] = shufflevector <32 x i32> [[WIDE_VEC12]], <32 x i32> poison, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
; CHECK-NEXT:    [[STRIDED_VEC14:%.*]] = shufflevector <32 x i32> [[WIDE_VEC12]], <32 x i32> poison, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>
; CHECK-NEXT:    [[TMP15:%.*]] = add nsw <16 x i32> [[STRIDED_VEC13]], [[STRIDED_VEC10]]
; CHECK-NEXT:    [[TMP16:%.*]] = add nsw <16 x i32> [[STRIDED_VEC14]], [[STRIDED_VEC11]]
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <16 x i32> [[TMP15]], <16 x i32> [[TMP16]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
; CHECK-NEXT:    [[INTERLEAVED_VEC15:%.*]] = shufflevector <32 x i32> [[TMP17]], <32 x i32> poison, <32 x i32> <i32 0, i32 16, i32 1, i32 17, i32 2, i32 18, i32 3, i32 19, i32 4, i32 20, i32 5, i32 21, i32 6, i32 22, i32 7, i32 23, i32 8, i32 24, i32 9, i32 25, i32 10, i32 26, i32 11, i32 27, i32 12, i32 28, i32 13, i32 29, i32 14, i32 30, i32 15, i32 31>
; CHECK-NEXT:    store <32 x i32> [[INTERLEAVED_VEC15]], ptr [[TMP14]], align 4, !tbaa [[INT_TBAA1]]
; CHECK-NEXT:    [[INDEX_NEXT16]] = add nuw i32 [[INDEX8]], 16
; CHECK-NEXT:    [[TMP18:%.*]] = icmp eq i32 [[INDEX_NEXT16]], [[N_VEC7]]
; CHECK-NEXT:    br i1 [[TMP18]], label %[[VEC_EPILOG_MIDDLE_BLOCK:.*]], label %[[VEC_EPILOG_VECTOR_BODY]], !llvm.loop [[LOOP10:![0-9]+]]
; CHECK:       [[VEC_EPILOG_MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N17:%.*]] = icmp eq i32 [[TMP2]], [[N_VEC7]]
; CHECK-NEXT:    br i1 [[CMP_N17]], label %[[B2]], label %[[VEC_EPILOG_SCALAR_PH]]
; CHECK:       [[VEC_EPILOG_SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL12:%.*]] = phi i32 [ [[TMP11]], %[[VEC_EPILOG_MIDDLE_BLOCK]] ], [ [[TMP3]], %[[VEC_EPILOG_ITER_CHECK]] ], [ 0, %[[ITER_CHECK]] ]
; CHECK-NEXT:    br label %[[B4:.*]]
; CHECK:       [[B2]]:
; CHECK-NEXT:    br label %[[B3]]
; CHECK:       [[B3]]:
; CHECK-NEXT:    ret void
; CHECK:       [[B4]]:
; CHECK-NEXT:    [[V1:%.*]] = phi i32 [ [[V13:%.*]], %[[B4]] ], [ [[BC_RESUME_VAL12]], %[[VEC_EPILOG_SCALAR_PH]] ]
; CHECK-NEXT:    [[V2:%.*]] = getelementptr inbounds i32, ptr [[A1]], i32 [[V1]]
; CHECK-NEXT:    [[V3:%.*]] = load i32, ptr [[V2]], align 4, !tbaa [[INT_TBAA1]]
; CHECK-NEXT:    [[V4:%.*]] = getelementptr inbounds i32, ptr [[A0]], i32 [[V1]]
; CHECK-NEXT:    [[V5:%.*]] = load i32, ptr [[V4]], align 4, !tbaa [[INT_TBAA1]]
; CHECK-NEXT:    [[V6:%.*]] = add nsw i32 [[V5]], [[V3]]
; CHECK-NEXT:    store i32 [[V6]], ptr [[V4]], align 4, !tbaa [[INT_TBAA1]]
; CHECK-NEXT:    [[V7:%.*]] = or disjoint i32 [[V1]], 1
; CHECK-NEXT:    [[V8:%.*]] = getelementptr inbounds i32, ptr [[A1]], i32 [[V7]]
; CHECK-NEXT:    [[V9:%.*]] = load i32, ptr [[V8]], align 4, !tbaa [[INT_TBAA1]]
; CHECK-NEXT:    [[V10:%.*]] = getelementptr inbounds i32, ptr [[A0]], i32 [[V7]]
; CHECK-NEXT:    [[V11:%.*]] = load i32, ptr [[V10]], align 4, !tbaa [[INT_TBAA1]]
; CHECK-NEXT:    [[V12:%.*]] = add nsw i32 [[V11]], [[V9]]
; CHECK-NEXT:    store i32 [[V12]], ptr [[V10]], align 4, !tbaa [[INT_TBAA1]]
; CHECK-NEXT:    [[V13]] = add nuw nsw i32 [[V1]], 2
; CHECK-NEXT:    [[V14:%.*]] = icmp eq i32 [[V13]], [[A2]]
; CHECK-NEXT:    br i1 [[V14]], label %[[B2]], label %[[B4]], !llvm.loop [[LOOP11:![0-9]+]]
;
b0:
  %v0 = icmp eq i32 %a2, 0
  br i1 %v0, label %b3, label %b1

b1:                                               ; preds = %b0
  br label %b4

b2:                                               ; preds = %b4
  br label %b3

b3:                                               ; preds = %b2, %b0
  ret void

b4:                                               ; preds = %b4, %b1
  %v1 = phi i32 [ %v13, %b4 ], [ 0, %b1 ]
  %v2 = getelementptr inbounds i32, ptr %a1, i32 %v1
  %v3 = load i32, ptr %v2, align 4, !tbaa !1
  %v4 = getelementptr inbounds i32, ptr %a0, i32 %v1
  %v5 = load i32, ptr %v4, align 4, !tbaa !1
  %v6 = add nsw i32 %v5, %v3
  store i32 %v6, ptr %v4, align 4, !tbaa !1
  %v7 = or disjoint i32 %v1, 1
  %v8 = getelementptr inbounds i32, ptr %a1, i32 %v7
  %v9 = load i32, ptr %v8, align 4, !tbaa !1
  %v10 = getelementptr inbounds i32, ptr %a0, i32 %v7
  %v11 = load i32, ptr %v10, align 4, !tbaa !1
  %v12 = add nsw i32 %v11, %v9
  store i32 %v12, ptr %v10, align 4, !tbaa !1
  %v13 = add nuw nsw i32 %v1, 2
  %v14 = icmp eq i32 %v13, %a2
  br i1 %v14, label %b2, label %b4, !llvm.loop !5
}

attributes #0 = { norecurse nounwind "target-cpu"="hexagonv60" "target-features"="+hvx-length128b,+hvxv60" }

!llvm.module.flags = !{!0}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!2, !2, i64 0}
!2 = !{!"int", !3, i64 0}
!3 = !{!"omnipotent char", !4, i64 0}
!4 = !{!"Simple C/C++ TBAA"}
!5 = distinct !{!5, !6}
!6 = !{!"llvm.loop.unroll.disable"}
;.
; CHECK: [[INT_TBAA1]] = !{[[META2:![0-9]+]], [[META2]], i64 0}
; CHECK: [[META2]] = !{!"int", [[META3:![0-9]+]], i64 0}
; CHECK: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
; CHECK: [[META4]] = !{!"Simple C/C++ TBAA"}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META6:![0-9]+]], [[META7:![0-9]+]], [[META8:![0-9]+]]}
; CHECK: [[META6]] = !{!"llvm.loop.unroll.disable"}
; CHECK: [[META7]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META8]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[PROF9]] = !{!"branch_weights", i32 16, i32 16}
; CHECK: [[LOOP10]] = distinct !{[[LOOP10]], [[META6]], [[META7]], [[META8]]}
; CHECK: [[LOOP11]] = distinct !{[[LOOP11]], [[META6]], [[META7]]}
;.
