; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

declare void @use(i1)

define void @symbolic_start_and_stride_slt_latch(i64 %start, i64 %step, i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @symbolic_start_and_stride_slt_latch(
; CHECK-SAME: i64 [[START:%.*]], i64 [[STEP:%.*]], i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp slt i64 [[START]], [[N]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[START]], %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = icmp slt i64 [[IV]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], [[STEP]]
; CHECK-NEXT:    [[EC:%.*]] = icmp slt i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp slt i64 %start, %n
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ %start, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp slt i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add i64 %iv, %step
  %ec = icmp slt i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

define void @symbolic_start_and_stride_ult_latch(i64 %start, i64 %step, i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @symbolic_start_and_stride_ult_latch(
; CHECK-SAME: i64 [[START:%.*]], i64 [[STEP:%.*]], i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp ult i64 [[START]], [[N]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[START]], %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = icmp ult i64 [[IV]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], [[STEP]]
; CHECK-NEXT:    [[EC:%.*]] = icmp ult i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp ult i64 %start, %n
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ %start, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp ult i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add i64 %iv, %step
  %ec = icmp ult i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

define void @stride2_slt_latch(i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @stride2_slt_latch(
; CHECK-SAME: i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp slt i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp sgt i64 %n, 0
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp slt i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nsw i64 %iv, 2
  %ec = icmp slt i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

define void @stride2_slt_header_is_latch(i64 %n) {
; CHECK-LABEL: define void @stride2_slt_header_is_latch(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp slt i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp sgt i64 %n, 0
  call void @llvm.assume(i1 %pre)
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %c = icmp slt i64 %iv, %n
  call void @use(i1 %c)
  %iv.next = add nsw i64 %iv, 2
  %ec = icmp slt i64 %iv.next, %n
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

define void @stride2_sge_latch(i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @stride2_sge_latch(
; CHECK-SAME: i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp sge i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[EXIT]], label %[[LOOP_HEADER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp sgt i64 %n, 0
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp slt i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nsw i64 %iv, 2
  %ec = icmp sge i64 %iv.next, %n
  br i1 %ec, label %exit, label %loop.header

exit:
  ret void
}

; The latch tests iv + 2, but the induction advances by 4.
define void @neg_compared_value_not_backedge(i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @neg_compared_value_not_backedge(
; CHECK-SAME: i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = icmp slt i64 [[IV]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[PROBE:%.*]] = add nsw i64 [[IV]], 2
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 4
; CHECK-NEXT:    [[EC:%.*]] = icmp slt i64 [[PROBE]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp sgt i64 %n, 0
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp slt i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %probe = add nsw i64 %iv, 2
  %iv.next = add nsw i64 %iv, 4
  %ec = icmp slt i64 %probe, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

; Test where bound is not loop-invariant.
define void @neg_variant_bound(ptr %p, i1 %header.ec) {
; CHECK-LABEL: define void @neg_variant_bound(
; CHECK-SAME: ptr [[P:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[N:%.*]] = load i64, ptr [[P]], align 4
; CHECK-NEXT:    [[C:%.*]] = icmp slt i64 [[IV]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp slt i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %n = load i64, ptr %p
  %c = icmp slt i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nsw i64 %iv, 2
  %ec = icmp slt i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

define void @negative_start_unsigned_precondition_blocks(i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @negative_start_unsigned_precondition_blocks(
; CHECK-SAME: i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ -4, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[C_U:%.*]] = icmp ult i64 [[IV]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[C_U]])
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp slt i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp sgt i64 %n, 0
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ -4, %entry ], [ %iv.next, %loop.latch ]
  %c.s = icmp slt i64 %iv, %n
  call void @use(i1 %c.s)
  %c.u = icmp ult i64 %iv, %n
  call void @use(i1 %c.u)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nsw i64 %iv, 2
  %ec = icmp slt i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

; Loop continues while iv + 2 s>= n.
define void @neg_wrong_polarity(i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @neg_wrong_polarity(
; CHECK-SAME: i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = icmp slt i64 [[IV]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp slt i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[EXIT]], label %[[LOOP_HEADER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp slt i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nsw i64 %iv, 2
  %ec = icmp slt i64 %iv.next, %n
  br i1 %ec, label %exit, label %loop.header

exit:
  ret void
}

define void @stride2_ult_latch(i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @stride2_ult_latch(
; CHECK-SAME: i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp ne i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nuw i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp ult i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp ne i64 %n, 0
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp ult i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nuw i64 %iv, 2
  %ec = icmp ult i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

define void @stride2_uge_latch(i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @stride2_uge_latch(
; CHECK-SAME: i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp ne i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nuw i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp uge i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[EXIT]], label %[[LOOP_HEADER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp ne i64 %n, 0
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp ult i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nuw i64 %iv, 2
  %ec = icmp uge i64 %iv.next, %n
  br i1 %ec, label %exit, label %loop.header

exit:
  ret void
}

define void @stride2_sle_latch(i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @stride2_sle_latch(
; CHECK-SAME: i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp sge i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp sle i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp sge i64 %n, 0
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp sle i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nsw i64 %iv, 2
  %ec = icmp sle i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

define void @unsigned_latch_signed_fact(i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @unsigned_latch_signed_fact(
; CHECK-SAME: i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nuw i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp ult i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp sgt i64 %n, 0
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp slt i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nuw i64 %iv, 2
  %ec = icmp ult i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

define void @neg_unsigned_latch_no_signed_fact(i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @neg_unsigned_latch_no_signed_fact(
; CHECK-SAME: i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp ne i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = icmp slt i64 [[IV]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp ult i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp ne i64 %n, 0
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp slt i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nsw i64 %iv, 2
  %ec = icmp ult i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

; Loop with step -1: the next header value is -1, which is u> n.
define void @neg_decreasing_no_unsigned_fact(i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @neg_decreasing_no_unsigned_fact(
; CHECK-SAME: i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[C_U:%.*]] = icmp ult i64 [[IV]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[C_U]])
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], -1
; CHECK-NEXT:    br i1 true, label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp sgt i64 %n, 0
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %c.s = icmp slt i64 %iv, %n
  call void @use(i1 %c.s)
  %c.u = icmp ult i64 %iv, %n
  call void @use(i1 %c.u)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nsw i64 %iv, -1
  %ec = icmp slt i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

define void @commuted_compare(i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @commuted_compare(
; CHECK-SAME: i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp sgt i64 [[N]], [[IV_NEXT]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp sgt i64 %n, 0
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp slt i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nsw i64 %iv, 2
  %ec = icmp sgt i64 %n, %iv.next
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

; Negative test: the loop exits with iv.next == n + 1, so the exit-block fact
; iv.next u<= n must not be derived.
define void @neg_no_exit_block_fact(i64 %n, i64 %z, i1 %header.ec) {
; CHECK-LABEL: define void @neg_no_exit_block_fact(
; CHECK-SAME: i64 [[N:%.*]], i64 [[Z:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE_0:%.*]] = icmp ult i64 [[N]], 100
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE_0]])
; CHECK-NEXT:    [[PRE_1:%.*]] = icmp ugt i64 [[N]], 5
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE_1]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ule i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[LOOP_EXIT:.*]]
; CHECK:       [[LOOP_EXIT]]:
; CHECK-NEXT:    [[C:%.*]] = icmp ult i64 [[Z]], 3
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre.0 = icmp ult i64 %n, 100
  call void @llvm.assume(i1 %pre.0)
  %pre.1 = icmp ugt i64 %n, 5
  call void @llvm.assume(i1 %pre.1)
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nuw nsw i64 %iv, 1
  %ec = icmp ule i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %loop.exit

loop.exit:
  %c = icmp ult i64 %z, 3
  call void @use(i1 %c)
  br label %exit

exit:
  ret void
}

; Same, but exiting via the header condition.
define void @neg_no_exit_block_fact_header(i64 %n, i64 %z) {
; CHECK-LABEL: define void @neg_no_exit_block_fact_header(
; CHECK-SAME: i64 [[N:%.*]], i64 [[Z:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE_0:%.*]] = icmp ult i64 [[N]], 100
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE_0]])
; CHECK-NEXT:    [[PRE_1:%.*]] = icmp ugt i64 [[N]], 5
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE_1]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ule i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_LATCH]], label %[[LOOP_EXIT:.*]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    br label %[[LOOP_HEADER]]
; CHECK:       [[LOOP_EXIT]]:
; CHECK-NEXT:    [[C:%.*]] = icmp ult i64 [[Z]], 3
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    ret void
;
entry:
  %pre.0 = icmp ult i64 %n, 100
  call void @llvm.assume(i1 %pre.0)
  %pre.1 = icmp ugt i64 %n, 5
  call void @llvm.assume(i1 %pre.1)
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %iv.next = add nuw nsw i64 %iv, 1
  %ec = icmp ule i64 %iv.next, %n
  br i1 %ec, label %loop.latch, label %loop.exit

loop.latch:
  br label %loop.header

loop.exit:
  %c = icmp ult i64 %z, 3
  call void @use(i1 %c)
  ret void
}

; %iv is known non-negative, so the signed condition in the latch can also be
; translated to an unsigned bound.
define void @signed_latch_unsigned_fact(i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @signed_latch_unsigned_fact(
; CHECK-SAME: i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp ne i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp slt i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp ne i64 %n, 0
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp ult i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nsw i64 %iv, 2
  %ec = icmp slt i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

; Same, but the step may wrap.
define void @neg_wrapping_step_no_unsigned_fact(i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @neg_wrapping_step_no_unsigned_fact(
; CHECK-SAME: i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp ne i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = icmp ult i64 [[IV]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp slt i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp ne i64 %n, 0
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp ult i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add i64 %iv, 2
  %ec = icmp slt i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

define void @signed_latch_unsigned_fact_variable_start(i64 %start, i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @signed_latch_unsigned_fact_variable_start(
; CHECK-SAME: i64 [[START:%.*]], i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp ult i64 [[START]], [[N]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    [[PRE_POS:%.*]] = icmp sge i64 [[START]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE_POS]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[START]], %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp slt i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre.1 = icmp ult i64 %start, %n
  call void @llvm.assume(i1 %pre.1)
  %start.pos = icmp sge i64 %start, 0
  call void @llvm.assume(i1 %start.pos)
  br label %loop.header

loop.header:
  %iv = phi i64 [ %start, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp ult i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nsw i64 %iv, 2
  %ec = icmp slt i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

; Same as above, but with missing %start < %n precondition.
define void @signed_latch_unsigned_fact_variable_start_missing_ult(i64 %start, i64 %n, i1 %header.ec) {
; CHECK-LABEL: define void @signed_latch_unsigned_fact_variable_start_missing_ult(
; CHECK-SAME: i64 [[START:%.*]], i64 [[N:%.*]], i1 [[HEADER_EC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE_POS:%.*]] = icmp sge i64 [[START]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE_POS]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[START]], %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = icmp ult i64 [[IV]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    br i1 [[HEADER_EC]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 2
; CHECK-NEXT:    [[EC:%.*]] = icmp slt i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %start.pos = icmp sge i64 %start, 0
  call void @llvm.assume(i1 %start.pos)
  br label %loop.header

loop.header:
  %iv = phi i64 [ %start, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp ult i64 %iv, %n
  call void @use(i1 %c)
  br i1 %header.ec, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nsw i64 %iv, 2
  %ec = icmp slt i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

; Continuing on sgt does not imply an unsigned lower bound. For n = -2,
; incrementing iv from -1 to 0 makes the unsigned comparison false.
define void @signed_gt_latch_no_unsigned_fact(i64 %n) {
; CHECK-LABEL: define void @signed_gt_latch_no_unsigned_fact(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp ugt i64 -1, [[N]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ -1, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i64 [[IV]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    [[STOP:%.*]] = icmp eq i64 [[IV]], 1
; CHECK-NEXT:    br i1 [[STOP]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp sgt i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp ugt i64 -1, %n
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ -1, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp ugt i64 %iv, %n
  call void @use(i1 %c)
  %stop = icmp eq i64 %iv, 1
  br i1 %stop, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nsw i64 %iv, 1
  %ec = icmp sgt i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

; Exiting on sgt instead gives a signed <= continuation, which does imply an
; unsigned upper bound for this non-negative induction.
define void @signed_gt_exit_unsigned_fact(i64 %n) {
; CHECK-LABEL: define void @signed_gt_exit_unsigned_fact(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[STOP:%.*]] = icmp eq i64 [[IV]], 4
; CHECK-NEXT:    br i1 [[STOP]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp sgt i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[EXIT]], label %[[LOOP_HEADER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp ule i64 %iv, %n
  call void @use(i1 %c)
  %stop = icmp eq i64 %iv, 4
  br i1 %stop, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nsw i64 %iv, 1
  %ec = icmp sgt i64 %iv.next, %n
  br i1 %ec, label %exit, label %loop.header

exit:
  ret void
}
