; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

define i1 @test_overflow_sub_coefficients(i8 %x, i64 %y) {
; CHECK-LABEL: define i1 @test_overflow_sub_coefficients
; CHECK-SAME: (i8 [[X:%.*]], i64 [[Y:%.*]]) {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    [[ZEXT:%.*]] = zext i8 [[X]] to i64
; CHECK-NEXT:    [[SHL:%.*]] = shl nuw nsw i64 [[ZEXT]], 63
; CHECK-NEXT:    [[ICMP:%.*]] = icmp uge i64 [[SHL]], [[Y]]
; CHECK-NEXT:    ret i1 [[ICMP]]
;
bb:
  %zext = zext i8 %x to i64
  %shl = shl nuw nsw i64 %zext, 63
  %icmp = icmp uge i64 %shl, %y
  ret i1 %icmp
}

define i1 @test_overflow_in_negate_constraint(i8 %x, i64 %y) {
; CHECK-LABEL: define i1 @test_overflow_in_negate_constraint
; CHECK-SAME: (i8 [[X:%.*]], i64 [[Y:%.*]]) {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    [[ZEXT:%.*]] = zext i8 [[X]] to i64
; CHECK-NEXT:    [[SHL:%.*]] = shl nuw nsw i64 [[ZEXT]], 63
; CHECK-NEXT:    ret i1 true
;
bb:
  %zext = zext i8 %x to i64
  %shl = shl nuw nsw i64 %zext, 63
  %icmp = icmp uge i64 %y, %shl
  ret i1 %icmp
}

