; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s

declare <16 x i8> @llvm.loongarch.lsx.vaddi.bu(<16 x i8>, i32)

define <16 x i8> @lsx_vaddi_bu(<16 x i8> %va) nounwind {
; CHECK-LABEL: lsx_vaddi_bu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vaddi.bu $vr0, $vr0, 31
; CHECK-NEXT:    ret
entry:
  %res = call <16 x i8> @llvm.loongarch.lsx.vaddi.bu(<16 x i8> %va, i32 31)
  ret <16 x i8> %res
}

declare <8 x i16> @llvm.loongarch.lsx.vaddi.hu(<8 x i16>, i32)

define <8 x i16> @lsx_vaddi_hu(<8 x i16> %va) nounwind {
; CHECK-LABEL: lsx_vaddi_hu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vaddi.hu $vr0, $vr0, 31
; CHECK-NEXT:    ret
entry:
  %res = call <8 x i16> @llvm.loongarch.lsx.vaddi.hu(<8 x i16> %va, i32 31)
  ret <8 x i16> %res
}

declare <4 x i32> @llvm.loongarch.lsx.vaddi.wu(<4 x i32>, i32)

define <4 x i32> @lsx_vaddi_wu(<4 x i32> %va) nounwind {
; CHECK-LABEL: lsx_vaddi_wu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vaddi.wu $vr0, $vr0, 31
; CHECK-NEXT:    ret
entry:
  %res = call <4 x i32> @llvm.loongarch.lsx.vaddi.wu(<4 x i32> %va, i32 31)
  ret <4 x i32> %res
}

declare <2 x i64> @llvm.loongarch.lsx.vaddi.du(<2 x i64>, i32)

define <2 x i64> @lsx_vaddi_du(<2 x i64> %va) nounwind {
; CHECK-LABEL: lsx_vaddi_du:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vaddi.du $vr0, $vr0, 31
; CHECK-NEXT:    ret
entry:
  %res = call <2 x i64> @llvm.loongarch.lsx.vaddi.du(<2 x i64> %va, i32 31)
  ret <2 x i64> %res
}
