; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx < %s | FileCheck %s --check-prefixes=CHECK,LA32
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s --check-prefixes=CHECK,LA64

declare i32 @llvm.loongarch.lsx.vpickve2gr.b(<16 x i8>, i32)

define i32 @lsx_vpickve2gr_b(<16 x i8> %va) nounwind {
; CHECK-LABEL: lsx_vpickve2gr_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vpickve2gr.b $a0, $vr0, 15
; CHECK-NEXT:    ret
entry:
  %res = call i32 @llvm.loongarch.lsx.vpickve2gr.b(<16 x i8> %va, i32 15)
  ret i32 %res
}

declare i32 @llvm.loongarch.lsx.vpickve2gr.h(<8 x i16>, i32)

define i32 @lsx_vpickve2gr_h(<8 x i16> %va) nounwind {
; CHECK-LABEL: lsx_vpickve2gr_h:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vpickve2gr.h $a0, $vr0, 7
; CHECK-NEXT:    ret
entry:
  %res = call i32 @llvm.loongarch.lsx.vpickve2gr.h(<8 x i16> %va, i32 7)
  ret i32 %res
}

declare i32 @llvm.loongarch.lsx.vpickve2gr.w(<4 x i32>, i32)

define i32 @lsx_vpickve2gr_w(<4 x i32> %va) nounwind {
; CHECK-LABEL: lsx_vpickve2gr_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vpickve2gr.w $a0, $vr0, 3
; CHECK-NEXT:    ret
entry:
  %res = call i32 @llvm.loongarch.lsx.vpickve2gr.w(<4 x i32> %va, i32 3)
  ret i32 %res
}

declare i32 @llvm.loongarch.lsx.vpickve2gr.bu(<16 x i8>, i32)

define i32 @lsx_vpickve2gr_bu(<16 x i8> %va) nounwind {
; CHECK-LABEL: lsx_vpickve2gr_bu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vpickve2gr.bu $a0, $vr0, 15
; CHECK-NEXT:    ret
entry:
  %res = call i32 @llvm.loongarch.lsx.vpickve2gr.bu(<16 x i8> %va, i32 15)
  ret i32 %res
}

define i1 @lsx_vpickve2gr_bu_cmp(<16 x i8> %va) nounwind {
; CHECK-LABEL: lsx_vpickve2gr_bu_cmp:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vpickve2gr.bu $a0, $vr0, 15
; CHECK-NEXT:    andi $a0, $a0, 255
; CHECK-NEXT:    sltui $a0, $a0, 1
; CHECK-NEXT:    ret
entry:
  %val = call i32 @llvm.loongarch.lsx.vpickve2gr.bu(<16 x i8> %va, i32 15)
  %tmp = and i32 %val, 255
  %res = icmp eq i32 %tmp, 0
  ret i1 %res
}

declare i32 @llvm.loongarch.lsx.vpickve2gr.hu(<8 x i16>, i32)

define i32 @lsx_vpickve2gr_hu(<8 x i16> %va) nounwind {
; CHECK-LABEL: lsx_vpickve2gr_hu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vpickve2gr.hu $a0, $vr0, 7
; CHECK-NEXT:    ret
entry:
  %res = call i32 @llvm.loongarch.lsx.vpickve2gr.hu(<8 x i16> %va, i32 7)
  ret i32 %res
}

define i1 @lsx_vpickve2gr_hu_cmp(<8 x i16> %va) nounwind {
; LA32-LABEL: lsx_vpickve2gr_hu_cmp:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    vpickve2gr.hu $a0, $vr0, 7
; LA32-NEXT:    bstrpick.w $a0, $a0, 15, 0
; LA32-NEXT:    sltui $a0, $a0, 1
; LA32-NEXT:    ret
;
; LA64-LABEL: lsx_vpickve2gr_hu_cmp:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    vpickve2gr.hu $a0, $vr0, 7
; LA64-NEXT:    bstrpick.d $a0, $a0, 15, 0
; LA64-NEXT:    sltui $a0, $a0, 1
; LA64-NEXT:    ret
entry:
  %val = call i32 @llvm.loongarch.lsx.vpickve2gr.hu(<8 x i16> %va, i32 7)
  %tmp = and i32 %val, 65535
  %res = icmp eq i32 %tmp, 0
  ret i1 %res
}

declare i32 @llvm.loongarch.lsx.vpickve2gr.wu(<4 x i32>, i32)

define i32 @lsx_vpickve2gr_wu(<4 x i32> %va) nounwind {
; CHECK-LABEL: lsx_vpickve2gr_wu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vpickve2gr.wu $a0, $vr0, 3
; CHECK-NEXT:    ret
entry:
  %res = call i32 @llvm.loongarch.lsx.vpickve2gr.wu(<4 x i32> %va, i32 3)
  ret i32 %res
}

define i1 @lsx_vpickve2gr_wu_cmp(<4 x i32> %va) nounwind {
; LA32-LABEL: lsx_vpickve2gr_wu_cmp:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    vpickve2gr.wu $a0, $vr0, 3
; LA32-NEXT:    sltui $a0, $a0, 1
; LA32-NEXT:    ret
;
; LA64-LABEL: lsx_vpickve2gr_wu_cmp:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    vpickve2gr.wu $a0, $vr0, 3
; LA64-NEXT:    addi.w $a0, $a0, 0
; LA64-NEXT:    sltui $a0, $a0, 1
; LA64-NEXT:    ret
entry:
  %val = call i32 @llvm.loongarch.lsx.vpickve2gr.wu(<4 x i32> %va, i32 3)
  %tmp = and i32 %val, 4294967295
  %res = icmp eq i32 %tmp, 0
  ret i1 %res
}
