; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s

declare <16 x i8> @llvm.loongarch.lsx.vsat.b(<16 x i8>, i32)

define <16 x i8> @lsx_vsat_b(<16 x i8> %va) nounwind {
; CHECK-LABEL: lsx_vsat_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsat.b $vr0, $vr0, 1
; CHECK-NEXT:    ret
entry:
  %res = call <16 x i8> @llvm.loongarch.lsx.vsat.b(<16 x i8> %va, i32 1)
  ret <16 x i8> %res
}

declare <8 x i16> @llvm.loongarch.lsx.vsat.h(<8 x i16>, i32)

define <8 x i16> @lsx_vsat_h(<8 x i16> %va) nounwind {
; CHECK-LABEL: lsx_vsat_h:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsat.h $vr0, $vr0, 1
; CHECK-NEXT:    ret
entry:
  %res = call <8 x i16> @llvm.loongarch.lsx.vsat.h(<8 x i16> %va, i32 1)
  ret <8 x i16> %res
}

declare <4 x i32> @llvm.loongarch.lsx.vsat.w(<4 x i32>, i32)

define <4 x i32> @lsx_vsat_w(<4 x i32> %va) nounwind {
; CHECK-LABEL: lsx_vsat_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsat.w $vr0, $vr0, 1
; CHECK-NEXT:    ret
entry:
  %res = call <4 x i32> @llvm.loongarch.lsx.vsat.w(<4 x i32> %va, i32 1)
  ret <4 x i32> %res
}

declare <2 x i64> @llvm.loongarch.lsx.vsat.d(<2 x i64>, i32)

define <2 x i64> @lsx_vsat_d(<2 x i64> %va) nounwind {
; CHECK-LABEL: lsx_vsat_d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsat.d $vr0, $vr0, 1
; CHECK-NEXT:    ret
entry:
  %res = call <2 x i64> @llvm.loongarch.lsx.vsat.d(<2 x i64> %va, i32 1)
  ret <2 x i64> %res
}

declare <16 x i8> @llvm.loongarch.lsx.vsat.bu(<16 x i8>, i32)

define <16 x i8> @lsx_vsat_bu(<16 x i8> %va) nounwind {
; CHECK-LABEL: lsx_vsat_bu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsat.bu $vr0, $vr0, 7
; CHECK-NEXT:    ret
entry:
  %res = call <16 x i8> @llvm.loongarch.lsx.vsat.bu(<16 x i8> %va, i32 7)
  ret <16 x i8> %res
}

declare <8 x i16> @llvm.loongarch.lsx.vsat.hu(<8 x i16>, i32)

define <8 x i16> @lsx_vsat_hu(<8 x i16> %va) nounwind {
; CHECK-LABEL: lsx_vsat_hu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsat.hu $vr0, $vr0, 15
; CHECK-NEXT:    ret
entry:
  %res = call <8 x i16> @llvm.loongarch.lsx.vsat.hu(<8 x i16> %va, i32 15)
  ret <8 x i16> %res
}

declare <4 x i32> @llvm.loongarch.lsx.vsat.wu(<4 x i32>, i32)

define <4 x i32> @lsx_vsat_wu(<4 x i32> %va) nounwind {
; CHECK-LABEL: lsx_vsat_wu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsat.wu $vr0, $vr0, 31
; CHECK-NEXT:    ret
entry:
  %res = call <4 x i32> @llvm.loongarch.lsx.vsat.wu(<4 x i32> %va, i32 31)
  ret <4 x i32> %res
}

declare <2 x i64> @llvm.loongarch.lsx.vsat.du(<2 x i64>, i32)

define <2 x i64> @lsx_vsat_du(<2 x i64> %va) nounwind {
; CHECK-LABEL: lsx_vsat_du:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsat.du $vr0, $vr0, 63
; CHECK-NEXT:    ret
entry:
  %res = call <2 x i64> @llvm.loongarch.lsx.vsat.du(<2 x i64> %va, i32 63)
  ret <2 x i64> %res
}
