; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s

declare <16 x i8> @llvm.loongarch.lsx.vshuf4i.b(<16 x i8>, i32)

define <16 x i8> @lsx_vshuf4i_b(<16 x i8> %va) nounwind {
; CHECK-LABEL: lsx_vshuf4i_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vshuf4i.b $vr0, $vr0, 255
; CHECK-NEXT:    ret
entry:
  %res = call <16 x i8> @llvm.loongarch.lsx.vshuf4i.b(<16 x i8> %va, i32 255)
  ret <16 x i8> %res
}

declare <8 x i16> @llvm.loongarch.lsx.vshuf4i.h(<8 x i16>, i32)

define <8 x i16> @lsx_vshuf4i_h(<8 x i16> %va) nounwind {
; CHECK-LABEL: lsx_vshuf4i_h:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vshuf4i.h $vr0, $vr0, 255
; CHECK-NEXT:    ret
entry:
  %res = call <8 x i16> @llvm.loongarch.lsx.vshuf4i.h(<8 x i16> %va, i32 255)
  ret <8 x i16> %res
}

declare <4 x i32> @llvm.loongarch.lsx.vshuf4i.w(<4 x i32>, i32)

define <4 x i32> @lsx_vshuf4i_w(<4 x i32> %va) nounwind {
; CHECK-LABEL: lsx_vshuf4i_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vshuf4i.w $vr0, $vr0, 255
; CHECK-NEXT:    ret
entry:
  %res = call <4 x i32> @llvm.loongarch.lsx.vshuf4i.w(<4 x i32> %va, i32 255)
  ret <4 x i32> %res
}

declare <2 x i64> @llvm.loongarch.lsx.vshuf4i.d(<2 x i64>, <2 x i64>, i32)

define <2 x i64> @lsx_vshuf4i_d(<2 x i64> %va, <2 x i64> %vb) nounwind {
; CHECK-LABEL: lsx_vshuf4i_d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vshuf4i.d $vr0, $vr1, 255
; CHECK-NEXT:    ret
entry:
  %res = call <2 x i64> @llvm.loongarch.lsx.vshuf4i.d(<2 x i64> %va, <2 x i64> %vb, i32 255)
  ret <2 x i64> %res
}
