; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx < %s | FileCheck %s --check-prefixes=CHECK,LA32
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s --check-prefixes=CHECK,LA64

declare <16 x i8> @llvm.loongarch.lsx.vsll.b(<16 x i8>, <16 x i8>)

define <16 x i8> @lsx_vsll_b(<16 x i8> %va, <16 x i8> %vb) nounwind {
; CHECK-LABEL: lsx_vsll_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsll.b $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %res = call <16 x i8> @llvm.loongarch.lsx.vsll.b(<16 x i8> %va, <16 x i8> %vb)
  ret <16 x i8> %res
}

declare <8 x i16> @llvm.loongarch.lsx.vsll.h(<8 x i16>, <8 x i16>)

define <8 x i16> @lsx_vsll_h(<8 x i16> %va, <8 x i16> %vb) nounwind {
; CHECK-LABEL: lsx_vsll_h:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsll.h $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %res = call <8 x i16> @llvm.loongarch.lsx.vsll.h(<8 x i16> %va, <8 x i16> %vb)
  ret <8 x i16> %res
}

declare <4 x i32> @llvm.loongarch.lsx.vsll.w(<4 x i32>, <4 x i32>)

define <4 x i32> @lsx_vsll_w(<4 x i32> %va, <4 x i32> %vb) nounwind {
; CHECK-LABEL: lsx_vsll_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsll.w $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %res = call <4 x i32> @llvm.loongarch.lsx.vsll.w(<4 x i32> %va, <4 x i32> %vb)
  ret <4 x i32> %res
}

declare <2 x i64> @llvm.loongarch.lsx.vsll.d(<2 x i64>, <2 x i64>)

define <2 x i64> @lsx_vsll_d(<2 x i64> %va, <2 x i64> %vb) nounwind {
; LA32-LABEL: lsx_vsll_d:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    vrepli.d $vr2, 63
; LA32-NEXT:    vand.v $vr1, $vr1, $vr2
; LA32-NEXT:    vsll.d $vr0, $vr0, $vr1
; LA32-NEXT:    ret
;
; LA64-LABEL: lsx_vsll_d:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    vsll.d $vr0, $vr0, $vr1
; LA64-NEXT:    ret
entry:
  %res = call <2 x i64> @llvm.loongarch.lsx.vsll.d(<2 x i64> %va, <2 x i64> %vb)
  ret <2 x i64> %res
}

declare <16 x i8> @llvm.loongarch.lsx.vslli.b(<16 x i8>, i32)

define <16 x i8> @lsx_vslli_b(<16 x i8> %va) nounwind {
; CHECK-LABEL: lsx_vslli_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vslli.b $vr0, $vr0, 7
; CHECK-NEXT:    ret
entry:
  %res = call <16 x i8> @llvm.loongarch.lsx.vslli.b(<16 x i8> %va, i32 7)
  ret <16 x i8> %res
}

declare <8 x i16> @llvm.loongarch.lsx.vslli.h(<8 x i16>, i32)

define <8 x i16> @lsx_vslli_h(<8 x i16> %va) nounwind {
; CHECK-LABEL: lsx_vslli_h:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vslli.h $vr0, $vr0, 15
; CHECK-NEXT:    ret
entry:
  %res = call <8 x i16> @llvm.loongarch.lsx.vslli.h(<8 x i16> %va, i32 15)
  ret <8 x i16> %res
}

declare <4 x i32> @llvm.loongarch.lsx.vslli.w(<4 x i32>, i32)

define <4 x i32> @lsx_vslli_w(<4 x i32> %va) nounwind {
; CHECK-LABEL: lsx_vslli_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vslli.w $vr0, $vr0, 31
; CHECK-NEXT:    ret
entry:
  %res = call <4 x i32> @llvm.loongarch.lsx.vslli.w(<4 x i32> %va, i32 31)
  ret <4 x i32> %res
}

declare <2 x i64> @llvm.loongarch.lsx.vslli.d(<2 x i64>, i32)

define <2 x i64> @lsx_vslli_d(<2 x i64> %va) nounwind {
; CHECK-LABEL: lsx_vslli_d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vslli.d $vr0, $vr0, 63
; CHECK-NEXT:    ret
entry:
  %res = call <2 x i64> @llvm.loongarch.lsx.vslli.d(<2 x i64> %va, i32 63)
  ret <2 x i64> %res
}
