; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple loongarch64 -mattr=+lsx < %s | FileCheck %s

define <4 x i32> @udot(<4 x i32> %acc, <16 x i8> %u, <16 x i8> %s) {
; CHECK-LABEL: udot:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmulwod.h.bu $vr3, $vr2, $vr1
; CHECK-NEXT:    vhaddw.w.h $vr3, $vr3, $vr3
; CHECK-NEXT:    vmulwev.h.bu $vr1, $vr2, $vr1
; CHECK-NEXT:    vhaddw.w.h $vr1, $vr1, $vr1
; CHECK-NEXT:    vadd.w $vr1, $vr1, $vr3
; CHECK-NEXT:    vadd.w $vr0, $vr1, $vr0
; CHECK-NEXT:    ret
  %u.wide = zext <16 x i8> %u to <16 x i32>
  %s.wide = zext <16 x i8> %s to <16 x i32>
  %mult = mul nuw nsw <16 x i32> %s.wide, %u.wide
  %partial.reduce = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> %acc, <16 x i32> %mult)
  ret <4 x i32> %partial.reduce
}

define <4 x i32> @udot_in_loop(ptr %p1, ptr %p2){
; CHECK-LABEL: udot_in_loop:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    move $a2, $zero
; CHECK-NEXT:    vrepli.b $vr1, 0
; CHECK-NEXT:    ori $a3, $zero, 16
; CHECK-NEXT:    .p2align 4, , 16
; CHECK-NEXT:  .LBB1_1: # %vector.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vldx $vr2, $a0, $a2
; CHECK-NEXT:    vldx $vr3, $a1, $a2
; CHECK-NEXT:    vori.b $vr0, $vr1, 0
; CHECK-NEXT:    vmulwod.h.bu $vr1, $vr2, $vr3
; CHECK-NEXT:    vhaddw.w.h $vr1, $vr1, $vr1
; CHECK-NEXT:    vmulwev.h.bu $vr2, $vr2, $vr3
; CHECK-NEXT:    vhaddw.w.h $vr2, $vr2, $vr2
; CHECK-NEXT:    vadd.w $vr1, $vr2, $vr1
; CHECK-NEXT:    addi.d $a2, $a2, 16
; CHECK-NEXT:    vadd.w $vr1, $vr1, $vr0
; CHECK-NEXT:    bne $a2, $a3, .LBB1_1
; CHECK-NEXT:  # %bb.2: # %end
; CHECK-NEXT:    ret
entry:
  br label %vector.body

vector.body:
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %acc = phi <4 x i32> [ zeroinitializer, %entry ], [ %partial.reduce, %vector.body ]
  %gep1 = getelementptr i8, ptr %p1, i64 %index
  %load1 = load <16 x i8>, ptr %gep1, align 16
  %load1.wide = zext <16 x i8> %load1 to <16 x i32>
  %gep2 = getelementptr i8, ptr %p2, i64 %index
  %load2 = load <16 x i8>, ptr %gep2, align 16
  %load2.wide = zext <16 x i8> %load2 to <16 x i32>
  %mul = mul nuw nsw <16 x i32> %load1.wide, %load2.wide
  %partial.reduce = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> %acc, <16 x i32> %mul)
  %index.next = add nuw i64 %index, 16
  %cmp = icmp eq i64 %index.next, 16
  br i1 %cmp, label %end, label %vector.body

end:
  ret <4 x i32> %acc
}

define <4 x i32> @sdot(<4 x i32> %acc, <16 x i8> %u, <16 x i8> %s) {
; CHECK-LABEL: sdot:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmulwod.h.b $vr3, $vr2, $vr1
; CHECK-NEXT:    vhaddw.w.h $vr3, $vr3, $vr3
; CHECK-NEXT:    vmulwev.h.b $vr1, $vr2, $vr1
; CHECK-NEXT:    vhaddw.w.h $vr1, $vr1, $vr1
; CHECK-NEXT:    vadd.w $vr1, $vr1, $vr3
; CHECK-NEXT:    vadd.w $vr0, $vr1, $vr0
; CHECK-NEXT:    ret
  %u.wide = sext <16 x i8> %u to <16 x i32>
  %s.wide = sext <16 x i8> %s to <16 x i32>
  %mult = mul nuw nsw <16 x i32> %s.wide, %u.wide
  %partial.reduce = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> %acc, <16 x i32> %mult)
  ret <4 x i32> %partial.reduce
}

define <4 x i32> @usdot(<4 x i32> %acc, <16 x i8> %u, <16 x i8> %s) {
; CHECK-LABEL: usdot:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmulwod.h.bu.b $vr3, $vr1, $vr2
; CHECK-NEXT:    vhaddw.w.h $vr3, $vr3, $vr3
; CHECK-NEXT:    vmulwev.h.bu.b $vr1, $vr1, $vr2
; CHECK-NEXT:    vhaddw.w.h $vr1, $vr1, $vr1
; CHECK-NEXT:    vadd.w $vr1, $vr1, $vr3
; CHECK-NEXT:    vadd.w $vr0, $vr1, $vr0
; CHECK-NEXT:    ret
  %u.wide = zext <16 x i8> %u to <16 x i32>
  %s.wide = sext <16 x i8> %s to <16 x i32>
  %mult = mul nuw nsw <16 x i32> %s.wide, %u.wide
  %partial.reduce = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> %acc, <16 x i32> %mult)
  ret <4 x i32> %partial.reduce
}

define <4 x i32> @usdot_in_loop(ptr %p1, ptr %p2){
; CHECK-LABEL: usdot_in_loop:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    move $a2, $zero
; CHECK-NEXT:    vrepli.b $vr1, 0
; CHECK-NEXT:    ori $a3, $zero, 16
; CHECK-NEXT:    .p2align 4, , 16
; CHECK-NEXT:  .LBB4_1: # %vector.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vldx $vr2, $a0, $a2
; CHECK-NEXT:    vldx $vr3, $a1, $a2
; CHECK-NEXT:    vori.b $vr0, $vr1, 0
; CHECK-NEXT:    vmulwod.h.bu.b $vr1, $vr3, $vr2
; CHECK-NEXT:    vhaddw.w.h $vr1, $vr1, $vr1
; CHECK-NEXT:    vmulwev.h.bu.b $vr2, $vr3, $vr2
; CHECK-NEXT:    vhaddw.w.h $vr2, $vr2, $vr2
; CHECK-NEXT:    vadd.w $vr1, $vr2, $vr1
; CHECK-NEXT:    addi.d $a2, $a2, 16
; CHECK-NEXT:    vadd.w $vr1, $vr1, $vr0
; CHECK-NEXT:    bne $a2, $a3, .LBB4_1
; CHECK-NEXT:  # %bb.2: # %end
; CHECK-NEXT:    ret
entry:
  br label %vector.body

vector.body:
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %acc = phi <4 x i32> [ zeroinitializer, %entry ], [ %partial.reduce, %vector.body ]
  %gep1 = getelementptr i8, ptr %p1, i64 %index
  %load1 = load <16 x i8>, ptr %gep1, align 16
  %load1.wide = sext <16 x i8> %load1 to <16 x i32>
  %gep2 = getelementptr i8, ptr %p2, i64 %index
  %load2 = load <16 x i8>, ptr %gep2, align 16
  %load2.wide = zext <16 x i8> %load2 to <16 x i32>
  %mul = mul nuw nsw <16 x i32> %load1.wide, %load2.wide
  %partial.reduce = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> %acc, <16 x i32> %mul)
  %index.next = add nuw i64 %index, 16
  %cmp = icmp eq i64 %index.next, 16
  br i1 %cmp, label %end, label %vector.body

end:
  ret <4 x i32> %acc
}

; Same as @usdot_in_loop, but with a non-zero initial accumulator carried
; across iterations. Validates that the SUMLA -> 2x udot identity composes
; correctly when the accumulator is not zero on entry.
define <4 x i32> @usdot_in_loop_nonzero_acc(ptr %p1, ptr %p2, <4 x i32> %init){
; CHECK-LABEL: usdot_in_loop_nonzero_acc:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    move $a2, $zero
; CHECK-NEXT:    ori $a3, $zero, 16
; CHECK-NEXT:    .p2align 4, , 16
; CHECK-NEXT:  .LBB5_1: # %vector.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vldx $vr2, $a0, $a2
; CHECK-NEXT:    vldx $vr3, $a1, $a2
; CHECK-NEXT:    vori.b $vr1, $vr0, 0
; CHECK-NEXT:    vmulwod.h.bu.b $vr0, $vr3, $vr2
; CHECK-NEXT:    vhaddw.w.h $vr0, $vr0, $vr0
; CHECK-NEXT:    vmulwev.h.bu.b $vr2, $vr3, $vr2
; CHECK-NEXT:    vhaddw.w.h $vr2, $vr2, $vr2
; CHECK-NEXT:    vadd.w $vr0, $vr2, $vr0
; CHECK-NEXT:    addi.d $a2, $a2, 16
; CHECK-NEXT:    vadd.w $vr0, $vr0, $vr1
; CHECK-NEXT:    bne $a2, $a3, .LBB5_1
; CHECK-NEXT:  # %bb.2: # %end
; CHECK-NEXT:    vori.b $vr0, $vr1, 0
; CHECK-NEXT:    ret
entry:
  br label %vector.body

vector.body:
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %acc = phi <4 x i32> [ %init, %entry ], [ %partial.reduce, %vector.body ]
  %gep1 = getelementptr i8, ptr %p1, i64 %index
  %load1 = load <16 x i8>, ptr %gep1, align 16
  %load1.wide = sext <16 x i8> %load1 to <16 x i32>
  %gep2 = getelementptr i8, ptr %p2, i64 %index
  %load2 = load <16 x i8>, ptr %gep2, align 16
  %load2.wide = zext <16 x i8> %load2 to <16 x i32>
  %mul = mul nuw nsw <16 x i32> %load1.wide, %load2.wide
  %partial.reduce = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> %acc, <16 x i32> %mul)
  %index.next = add nuw i64 %index, 16
  %cmp = icmp eq i64 %index.next, 16
  br i1 %cmp, label %end, label %vector.body

end:
  ret <4 x i32> %acc
}

define <4 x i32> @sudot(<4 x i32> %acc, <16 x i8> %u, <16 x i8> %s) #0{
; CHECK-LABEL: sudot:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmulwod.h.bu.b $vr3, $vr2, $vr1
; CHECK-NEXT:    vhaddw.w.h $vr3, $vr3, $vr3
; CHECK-NEXT:    vmulwev.h.bu.b $vr1, $vr2, $vr1
; CHECK-NEXT:    vhaddw.w.h $vr1, $vr1, $vr1
; CHECK-NEXT:    vadd.w $vr1, $vr1, $vr3
; CHECK-NEXT:    vadd.w $vr0, $vr1, $vr0
; CHECK-NEXT:    ret
  %s.wide = sext <16 x i8> %u to <16 x i32>
  %u.wide = zext <16 x i8> %s to <16 x i32>
  %mult = mul nuw nsw <16 x i32> %u.wide, %s.wide
  %partial.reduce = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> %acc, <16 x i32> %mult)
  ret <4 x i32> %partial.reduce
}

define <4 x i32> @sudot_in_loop(ptr %p1, ptr %p2){
; CHECK-LABEL: sudot_in_loop:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    move $a2, $zero
; CHECK-NEXT:    vrepli.b $vr1, 0
; CHECK-NEXT:    ori $a3, $zero, 16
; CHECK-NEXT:    .p2align 4, , 16
; CHECK-NEXT:  .LBB7_1: # %vector.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vldx $vr2, $a0, $a2
; CHECK-NEXT:    vldx $vr3, $a1, $a2
; CHECK-NEXT:    vori.b $vr0, $vr1, 0
; CHECK-NEXT:    vmulwod.h.bu.b $vr1, $vr2, $vr3
; CHECK-NEXT:    vhaddw.w.h $vr1, $vr1, $vr1
; CHECK-NEXT:    vmulwev.h.bu.b $vr2, $vr2, $vr3
; CHECK-NEXT:    vhaddw.w.h $vr2, $vr2, $vr2
; CHECK-NEXT:    vadd.w $vr1, $vr2, $vr1
; CHECK-NEXT:    addi.d $a2, $a2, 16
; CHECK-NEXT:    vadd.w $vr1, $vr1, $vr0
; CHECK-NEXT:    bne $a2, $a3, .LBB7_1
; CHECK-NEXT:  # %bb.2: # %end
; CHECK-NEXT:    ret
entry:
  br label %vector.body

vector.body:
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %acc = phi <4 x i32> [ zeroinitializer, %entry ], [ %partial.reduce, %vector.body ]
  %gep1 = getelementptr i8, ptr %p1, i64 %index
  %load1 = load <16 x i8>, ptr %gep1, align 16
  %load1.wide = zext <16 x i8> %load1 to <16 x i32>
  %gep2 = getelementptr i8, ptr %p2, i64 %index
  %load2 = load <16 x i8>, ptr %gep2, align 16
  %load2.wide = sext <16 x i8> %load2 to <16 x i32>
  %mul = mul nuw nsw <16 x i32> %load1.wide, %load2.wide
  %partial.reduce = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> %acc, <16 x i32> %mul)
  %index.next = add nuw i64 %index, 16
  %cmp = icmp eq i64 %index.next, 16
  br i1 %cmp, label %end, label %vector.body

end:
  ret <4 x i32> %acc
}

define <4 x i32> @udot_no_bin_op(<4 x i32> %acc, <16 x i8> %a){
; CHECK-LABEL: udot_no_bin_op:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vrepli.b $vr2, 1
; CHECK-NEXT:    vmulwod.h.bu $vr3, $vr1, $vr2
; CHECK-NEXT:    vhaddw.w.h $vr3, $vr3, $vr3
; CHECK-NEXT:    vmulwev.h.bu $vr1, $vr1, $vr2
; CHECK-NEXT:    vhaddw.w.h $vr1, $vr1, $vr1
; CHECK-NEXT:    vadd.w $vr1, $vr1, $vr3
; CHECK-NEXT:    vadd.w $vr0, $vr1, $vr0
; CHECK-NEXT:    ret
  %a.wide = zext <16 x i8> %a to <16 x i32>
  %partial.reduce = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> %acc, <16 x i32> %a.wide)
  ret <4 x i32> %partial.reduce
}

define <4 x i32> @udot_no_bin_op_in_loop(ptr %p){
; CHECK-LABEL: udot_no_bin_op_in_loop:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    move $a1, $zero
; CHECK-NEXT:    vrepli.b $vr2, 0
; CHECK-NEXT:    vrepli.b $vr1, 1
; CHECK-NEXT:    ori $a2, $zero, 16
; CHECK-NEXT:    .p2align 4, , 16
; CHECK-NEXT:  .LBB9_1: # %vector.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vldx $vr3, $a0, $a1
; CHECK-NEXT:    vori.b $vr0, $vr2, 0
; CHECK-NEXT:    vmulwod.h.bu $vr2, $vr3, $vr1
; CHECK-NEXT:    vhaddw.w.h $vr2, $vr2, $vr2
; CHECK-NEXT:    vmulwev.h.bu $vr3, $vr3, $vr1
; CHECK-NEXT:    vhaddw.w.h $vr3, $vr3, $vr3
; CHECK-NEXT:    vadd.w $vr2, $vr3, $vr2
; CHECK-NEXT:    addi.d $a1, $a1, 16
; CHECK-NEXT:    vadd.w $vr2, $vr2, $vr0
; CHECK-NEXT:    bne $a1, $a2, .LBB9_1
; CHECK-NEXT:  # %bb.2: # %end
; CHECK-NEXT:    ret
entry:
  br label %vector.body

vector.body:
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %acc = phi <4 x i32> [ zeroinitializer, %entry ], [ %partial.reduce, %vector.body ]
  %gep = getelementptr i8, ptr %p, i64 %index
  %load = load <16 x i8>, ptr %gep, align 16
  %load.wide = zext <16 x i8> %load to <16 x i32>
  %partial.reduce = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> %acc, <16 x i32> %load.wide)
  %index.next = add nuw i64 %index, 16
  %cmp = icmp eq i64 %index.next, 16
  br i1 %cmp, label %end, label %vector.body

end:
  ret <4 x i32> %acc
}

define <4 x i32> @sdot_no_bin_op(<4 x i32> %acc, <16 x i8> %a){
; CHECK-LABEL: sdot_no_bin_op:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vrepli.b $vr2, 1
; CHECK-NEXT:    vmulwod.h.b $vr3, $vr1, $vr2
; CHECK-NEXT:    vhaddw.w.h $vr3, $vr3, $vr3
; CHECK-NEXT:    vmulwev.h.b $vr1, $vr1, $vr2
; CHECK-NEXT:    vhaddw.w.h $vr1, $vr1, $vr1
; CHECK-NEXT:    vadd.w $vr1, $vr1, $vr3
; CHECK-NEXT:    vadd.w $vr0, $vr1, $vr0
; CHECK-NEXT:    ret
  %a.wide = sext <16 x i8> %a to <16 x i32>
  %partial.reduce = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> %acc, <16 x i32> %a.wide)
  ret <4 x i32> %partial.reduce
}
