; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc --mtriple=loongarch32 -mattr=+32s,+lsx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 -mattr=+lsx < %s | FileCheck %s

define <4 x float> @fadd_elt0_v4f32(float %a) nounwind {
; CHECK-LABEL: fadd_elt0_v4f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vldi $vr1, -1168
; CHECK-NEXT:    fadd.s $fa0, $fa0, $fa1
; CHECK-NEXT:    ret
entry:
  %b = insertelement <4 x float> poison, float %a, i32 0
  %c = fadd <4 x float> %b, <float 1.0, float poison, float poison, float poison>
  ret <4 x float> %c
}

define <2 x double> @fadd_elt0_v2f64(double %a) nounwind {
; CHECK-LABEL: fadd_elt0_v2f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vldi $vr1, -912
; CHECK-NEXT:    fadd.d $fa0, $fa0, $fa1
; CHECK-NEXT:    ret
entry:
  %b = insertelement <2 x double> poison, double %a, i32 0
  %c = fadd <2 x double> %b, <double 1.0, double poison>
  ret <2 x double> %c
}

define <4 x float> @fsub_splat_v4f32(float %b) nounwind {
; CHECK-LABEL: fsub_splat_v4f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vldi $vr1, -1168
; CHECK-NEXT:    fsub.s $fa0, $fa1, $fa0
; CHECK-NEXT:    vreplvei.w $vr0, $vr0, 0
; CHECK-NEXT:    ret
entry:
  %insa = insertelement <4 x float> poison, float 1.0, i32 0
  %insb = insertelement <4 x float> poison, float %b, i32 0
  %va = shufflevector <4 x float> %insa, <4 x float> poison, <4 x i32> zeroinitializer
  %vb = shufflevector <4 x float> %insb, <4 x float> poison, <4 x i32> zeroinitializer
  %c = fsub <4 x float> %va, %vb
  ret <4 x float> %c
}

define <2 x double> @fsub_splat_v2f64(double %a, double %b) nounwind {
; CHECK-LABEL: fsub_splat_v2f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fsub.d $fa0, $fa0, $fa1
; CHECK-NEXT:    vreplvei.d $vr0, $vr0, 0
; CHECK-NEXT:    ret
entry:
  %insa = insertelement <2 x double> poison, double %a, i32 0
  %insb = insertelement <2 x double> poison, double %b, i32 0
  %va = shufflevector <2 x double> %insa, <2 x double> poison, <2 x i32> zeroinitializer
  %vb = shufflevector <2 x double> %insb, <2 x double> poison, <2 x i32> zeroinitializer
  %c = fsub <2 x double> %va, %vb
  ret <2 x double> %c
}
