; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s

define <16 x i8> @srar_b(<16 x i8> %a, <16 x i8> %b) nounwind {
; CHECK-LABEL: srar_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsra.b $vr2, $vr0, $vr1
; CHECK-NEXT:    vsubi.bu $vr3, $vr1, 1
; CHECK-NEXT:    vsrl.b $vr3, $vr0, $vr3
; CHECK-NEXT:    vandi.b $vr3, $vr3, 1
; CHECK-NEXT:    vadd.b $vr2, $vr3, $vr2
; CHECK-NEXT:    vseqi.b $vr1, $vr1, 0
; CHECK-NEXT:    vbitsel.v $vr0, $vr2, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <16 x i8> %a, %b
  %1 = add <16 x i8> %b, splat (i8 -1)
  %2 = lshr <16 x i8> %a, %1
  %3 = and <16 x i8> %2, splat (i8 1)
  %4 = add <16 x i8> %3, %0
  %5 = icmp eq <16 x i8> %b, zeroinitializer
  %6 = select <16 x i1> %5, <16 x i8> %a, <16 x i8> %4
  ret <16 x i8> %6
}

define <8 x i16> @srar_h(<8 x i16> %a, <8 x i16> %b) nounwind {
; CHECK-LABEL: srar_h:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsra.h $vr2, $vr0, $vr1
; CHECK-NEXT:    vsubi.hu $vr3, $vr1, 1
; CHECK-NEXT:    vsrl.h $vr3, $vr0, $vr3
; CHECK-NEXT:    vrepli.h $vr4, 1
; CHECK-NEXT:    vand.v $vr3, $vr3, $vr4
; CHECK-NEXT:    vadd.h $vr2, $vr3, $vr2
; CHECK-NEXT:    vseqi.h $vr1, $vr1, 0
; CHECK-NEXT:    vbitsel.v $vr0, $vr2, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <8 x i16> %a, %b
  %1 = add <8 x i16> %b, splat (i16 -1)
  %2 = lshr <8 x i16> %a, %1
  %3 = and <8 x i16> %2, splat (i16 1)
  %4 = add <8 x i16> %3, %0
  %5 = icmp eq <8 x i16> %b, zeroinitializer
  %6 = select <8 x i1> %5, <8 x i16> %a, <8 x i16> %4
  ret <8 x i16> %6
}

define <4 x i32> @srar_w(<4 x i32> %a, <4 x i32> %b) nounwind {
; CHECK-LABEL: srar_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsra.w $vr2, $vr0, $vr1
; CHECK-NEXT:    vsubi.wu $vr3, $vr1, 1
; CHECK-NEXT:    vsrl.w $vr3, $vr0, $vr3
; CHECK-NEXT:    vrepli.w $vr4, 1
; CHECK-NEXT:    vand.v $vr3, $vr3, $vr4
; CHECK-NEXT:    vadd.w $vr2, $vr3, $vr2
; CHECK-NEXT:    vseqi.w $vr1, $vr1, 0
; CHECK-NEXT:    vbitsel.v $vr0, $vr2, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <4 x i32> %a, %b
  %1 = add <4 x i32> %b, splat (i32 -1)
  %2 = lshr <4 x i32> %a, %1
  %3 = and <4 x i32> %2, splat (i32 1)
  %4 = add <4 x i32> %3, %0
  %5 = icmp eq <4 x i32> %b, zeroinitializer
  %6 = select <4 x i1> %5, <4 x i32> %a, <4 x i32> %4
  ret <4 x i32> %6
}

define <2 x i64> @srar_d(<2 x i64> %a, <2 x i64> %b) nounwind {
; CHECK-LABEL: srar_d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsra.d $vr2, $vr0, $vr1
; CHECK-NEXT:    vsubi.du $vr3, $vr1, 1
; CHECK-NEXT:    vsrl.d $vr3, $vr0, $vr3
; CHECK-NEXT:    vrepli.d $vr4, 1
; CHECK-NEXT:    vand.v $vr3, $vr3, $vr4
; CHECK-NEXT:    vadd.d $vr2, $vr3, $vr2
; CHECK-NEXT:    vseqi.d $vr1, $vr1, 0
; CHECK-NEXT:    vbitsel.v $vr0, $vr2, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <2 x i64> %a, %b
  %1 = add <2 x i64> %b, splat (i64 -1)
  %2 = lshr <2 x i64> %a, %1
  %3 = and <2 x i64> %2, splat (i64 1)
  %4 = add <2 x i64> %3, %0
  %5 = icmp eq <2 x i64> %b, zeroinitializer
  %6 = select <2 x i1> %5, <2 x i64> %a, <2 x i64> %4
  ret <2 x i64> %6
}

define <16 x i8> @srar_b_1(<16 x i8> %a) nounwind {
; CHECK-LABEL: srar_b_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsrai.b $vr1, $vr0, 1
; CHECK-NEXT:    vandi.b $vr0, $vr0, 1
; CHECK-NEXT:    vadd.b $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <16 x i8> %a, splat (i8 1)
  %1 = and <16 x i8> %a, splat (i8 1)
  %2 = add nsw <16 x i8> %1, %0
  ret <16 x i8> %2
}

define <16 x i8> @srar_b_7(<16 x i8> %a) nounwind {
; CHECK-LABEL: srar_b_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsrai.b $vr1, $vr0, 7
; CHECK-NEXT:    vsrli.b $vr0, $vr0, 6
; CHECK-NEXT:    vandi.b $vr0, $vr0, 1
; CHECK-NEXT:    vadd.b $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <16 x i8> %a, splat (i8 7)
  %1 = lshr <16 x i8> %a, splat (i8 6)
  %2 = and <16 x i8> %1, splat (i8 1)
  %3 = add nsw <16 x i8> %2, %0
  ret <16 x i8> %3
}

define <8 x i16> @srar_h_1(<8 x i16> %a) nounwind {
; CHECK-LABEL: srar_h_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsrai.h $vr1, $vr0, 1
; CHECK-NEXT:    vrepli.h $vr2, 1
; CHECK-NEXT:    vand.v $vr0, $vr0, $vr2
; CHECK-NEXT:    vadd.h $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <8 x i16> %a, splat (i16 1)
  %1 = and <8 x i16> %a, splat (i16 1)
  %2 = add nsw <8 x i16> %1, %0
  ret <8 x i16> %2
}

define <8 x i16> @srar_h_15(<8 x i16> %a) nounwind {
; CHECK-LABEL: srar_h_15:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsrai.h $vr1, $vr0, 15
; CHECK-NEXT:    vsrli.h $vr0, $vr0, 14
; CHECK-NEXT:    vrepli.h $vr2, 1
; CHECK-NEXT:    vand.v $vr0, $vr0, $vr2
; CHECK-NEXT:    vadd.h $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <8 x i16> %a, splat (i16 15)
  %1 = lshr <8 x i16> %a, splat (i16 14)
  %2 = and <8 x i16> %1, splat (i16 1)
  %3 = add nsw <8 x i16> %2, %0
  ret <8 x i16> %3
}

define <4 x i32> @srar_w_1(<4 x i32> %a) nounwind {
; CHECK-LABEL: srar_w_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsrai.w $vr1, $vr0, 1
; CHECK-NEXT:    vrepli.w $vr2, 1
; CHECK-NEXT:    vand.v $vr0, $vr0, $vr2
; CHECK-NEXT:    vadd.w $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <4 x i32> %a, splat (i32 1)
  %1 = and <4 x i32> %a, splat (i32 1)
  %2 = add nsw <4 x i32> %1, %0
  ret <4 x i32> %2
}

define <4 x i32> @srar_w_31(<4 x i32> %a) nounwind {
; CHECK-LABEL: srar_w_31:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsrai.w $vr1, $vr0, 31
; CHECK-NEXT:    vsrli.w $vr0, $vr0, 30
; CHECK-NEXT:    vrepli.w $vr2, 1
; CHECK-NEXT:    vand.v $vr0, $vr0, $vr2
; CHECK-NEXT:    vadd.w $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <4 x i32> %a, splat (i32 31)
  %1 = lshr <4 x i32> %a, splat (i32 30)
  %2 = and <4 x i32> %1, splat (i32 1)
  %3 = add nsw <4 x i32> %2, %0
  ret <4 x i32> %3
}

define <2 x i64> @srar_d_1(<2 x i64> %a) nounwind {
; CHECK-LABEL: srar_d_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsrai.d $vr1, $vr0, 1
; CHECK-NEXT:    vrepli.d $vr2, 1
; CHECK-NEXT:    vand.v $vr0, $vr0, $vr2
; CHECK-NEXT:    vadd.d $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <2 x i64> %a, splat (i64 1)
  %1 = and <2 x i64> %a, splat (i64 1)
  %2 = add nsw <2 x i64> %1, %0
  ret <2 x i64> %2
}

define <2 x i64> @srar_d_63(<2 x i64> %a) nounwind {
; CHECK-LABEL: srar_d_63:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsrai.d $vr1, $vr0, 63
; CHECK-NEXT:    vsrli.d $vr0, $vr0, 62
; CHECK-NEXT:    vrepli.d $vr2, 1
; CHECK-NEXT:    vand.v $vr0, $vr0, $vr2
; CHECK-NEXT:    vadd.d $vr0, $vr0, $vr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <2 x i64> %a, splat (i64 63)
  %1 = lshr <2 x i64> %a, splat (i64 62)
  %2 = and <2 x i64> %1, splat (i64 1)
  %3 = add nsw <2 x i64> %2, %0
  ret <2 x i64> %3
}
