; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx %s -o - | FileCheck %s --check-prefix=LA32
; RUN: llc --mtriple=loongarch64 --mattr=+lsx %s -o - | FileCheck %s --check-prefix=LA64

define void @load_trunc_2i64_to_2i32(ptr %ptr, ptr %dst) nounwind {
; LA32-LABEL: load_trunc_2i64_to_2i32:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a0, 0
; LA32-NEXT:    vpickve2gr.w $a0, $vr0, 2
; LA32-NEXT:    st.w $a0, $a1, 4
; LA32-NEXT:    vpickve2gr.w $a0, $vr0, 0
; LA32-NEXT:    st.w $a0, $a1, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: load_trunc_2i64_to_2i32:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a0, 0
; LA64-NEXT:    vshuf4i.w $vr0, $vr0, 8
; LA64-NEXT:    vstelm.d $vr0, $a1, 0, 0
; LA64-NEXT:    ret
  %a = load <2 x i64>, ptr %ptr
  %trunc = trunc <2 x i64> %a to <2 x i32>
  store <2 x i32> %trunc, ptr %dst
  ret void
}

define void @load_trunc_2i64_to_2i16(ptr %ptr, ptr %dst) nounwind {
; LA32-LABEL: load_trunc_2i64_to_2i16:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a0, 0
; LA32-NEXT:    vreplvei.w $vr1, $vr0, 2
; LA32-NEXT:    vpackev.h $vr0, $vr1, $vr0
; LA32-NEXT:    vpickve2gr.w $a0, $vr0, 0
; LA32-NEXT:    st.w $a0, $a1, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: load_trunc_2i64_to_2i16:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a0, 0
; LA64-NEXT:    vreplvei.w $vr1, $vr0, 2
; LA64-NEXT:    vpackev.h $vr0, $vr1, $vr0
; LA64-NEXT:    vstelm.w $vr0, $a1, 0, 0
; LA64-NEXT:    ret
  %a = load <2 x i64>, ptr %ptr
  %trunc = trunc <2 x i64> %a to <2 x i16>
  store <2 x i16> %trunc, ptr %dst
  ret void
}

define void @load_trunc_2i64_to_2i8(ptr %ptr, ptr %dst) nounwind {
; LA32-LABEL: load_trunc_2i64_to_2i8:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a0, 0
; LA32-NEXT:    vreplvei.w $vr1, $vr0, 2
; LA32-NEXT:    vpackev.b $vr0, $vr1, $vr0
; LA32-NEXT:    vstelm.h $vr0, $a1, 0, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: load_trunc_2i64_to_2i8:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a0, 0
; LA64-NEXT:    vreplvei.w $vr1, $vr0, 2
; LA64-NEXT:    vpackev.b $vr0, $vr1, $vr0
; LA64-NEXT:    vstelm.h $vr0, $a1, 0, 0
; LA64-NEXT:    ret
  %a = load <2 x i64>, ptr %ptr
  %trunc = trunc <2 x i64> %a to <2 x i8>
  store <2 x i8> %trunc, ptr %dst
  ret void
}

define void @load_trunc_4i32_to_4i16(ptr %ptr, ptr %dst) nounwind {
; LA32-LABEL: load_trunc_4i32_to_4i16:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a0, 0
; LA32-NEXT:    vpickev.h $vr0, $vr0, $vr0
; LA32-NEXT:    vpickve2gr.w $a0, $vr0, 1
; LA32-NEXT:    st.w $a0, $a1, 4
; LA32-NEXT:    vpickve2gr.w $a0, $vr0, 0
; LA32-NEXT:    st.w $a0, $a1, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: load_trunc_4i32_to_4i16:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a0, 0
; LA64-NEXT:    vpickev.h $vr0, $vr0, $vr0
; LA64-NEXT:    vstelm.d $vr0, $a1, 0, 0
; LA64-NEXT:    ret
  %a = load <4 x i32>, ptr %ptr
  %trunc = trunc <4 x i32> %a to <4 x i16>
  store <4 x i16> %trunc, ptr %dst
  ret void
}

define void @load_trunc_4i32_to_4i8(ptr %ptr, ptr %dst) nounwind {
; LA32-LABEL: load_trunc_4i32_to_4i8:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a0, 0
; LA32-NEXT:    pcalau12i $a0, %pc_hi20(.LCPI4_0)
; LA32-NEXT:    vld $vr1, $a0, %pc_lo12(.LCPI4_0)
; LA32-NEXT:    vshuf.b $vr0, $vr0, $vr0, $vr1
; LA32-NEXT:    vpickve2gr.w $a0, $vr0, 0
; LA32-NEXT:    st.w $a0, $a1, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: load_trunc_4i32_to_4i8:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a0, 0
; LA64-NEXT:    pcalau12i $a0, %pc_hi20(.LCPI4_0)
; LA64-NEXT:    vld $vr1, $a0, %pc_lo12(.LCPI4_0)
; LA64-NEXT:    vshuf.b $vr0, $vr0, $vr0, $vr1
; LA64-NEXT:    vstelm.w $vr0, $a1, 0, 0
; LA64-NEXT:    ret
  %a = load <4 x i32>, ptr %ptr
  %trunc = trunc <4 x i32> %a to <4 x i8>
  store <4 x i8> %trunc, ptr %dst
  ret void
}

define void @load_trunc_8i16_to_8i8(ptr %ptr, ptr %dst) nounwind {
; LA32-LABEL: load_trunc_8i16_to_8i8:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a0, 0
; LA32-NEXT:    vpickev.b $vr0, $vr0, $vr0
; LA32-NEXT:    vpickve2gr.w $a0, $vr0, 1
; LA32-NEXT:    st.w $a0, $a1, 4
; LA32-NEXT:    vpickve2gr.w $a0, $vr0, 0
; LA32-NEXT:    st.w $a0, $a1, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: load_trunc_8i16_to_8i8:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a0, 0
; LA64-NEXT:    vpickev.b $vr0, $vr0, $vr0
; LA64-NEXT:    vstelm.d $vr0, $a1, 0, 0
; LA64-NEXT:    ret
  %a = load <8 x i16>, ptr %ptr
  %trunc = trunc <8 x i16> %a to <8 x i8>
  store <8 x i8> %trunc, ptr %dst
  ret void
}

define void @load_trunc_2i32_to_2i16(ptr %ptr, ptr %dst) nounwind {
; LA32-LABEL: load_trunc_2i32_to_2i16:
; LA32:       # %bb.0:
; LA32-NEXT:    ld.w $a2, $a0, 0
; LA32-NEXT:    ld.w $a0, $a0, 4
; LA32-NEXT:    vinsgr2vr.w $vr0, $a2, 0
; LA32-NEXT:    vinsgr2vr.w $vr0, $a0, 1
; LA32-NEXT:    vshuf4i.h $vr0, $vr0, 8
; LA32-NEXT:    vpickve2gr.w $a0, $vr0, 0
; LA32-NEXT:    st.w $a0, $a1, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: load_trunc_2i32_to_2i16:
; LA64:       # %bb.0:
; LA64-NEXT:    ld.d $a0, $a0, 0
; LA64-NEXT:    vinsgr2vr.d $vr0, $a0, 0
; LA64-NEXT:    vshuf4i.h $vr0, $vr0, 8
; LA64-NEXT:    vstelm.w $vr0, $a1, 0, 0
; LA64-NEXT:    ret
  %a = load <2 x i32>, ptr %ptr
  %trunc = trunc <2 x i32> %a to <2 x i16>
  store <2 x i16> %trunc, ptr %dst
  ret void
}

define void @load_trunc_2i32_to_2i8(ptr %ptr, ptr %dst) nounwind {
; LA32-LABEL: load_trunc_2i32_to_2i8:
; LA32:       # %bb.0:
; LA32-NEXT:    ld.w $a2, $a0, 0
; LA32-NEXT:    ld.w $a0, $a0, 4
; LA32-NEXT:    vinsgr2vr.w $vr0, $a2, 0
; LA32-NEXT:    vreplgr2vr.w $vr1, $a0
; LA32-NEXT:    vpackev.b $vr0, $vr1, $vr0
; LA32-NEXT:    vstelm.h $vr0, $a1, 0, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: load_trunc_2i32_to_2i8:
; LA64:       # %bb.0:
; LA64-NEXT:    ld.d $a0, $a0, 0
; LA64-NEXT:    vinsgr2vr.d $vr0, $a0, 0
; LA64-NEXT:    vreplvei.w $vr1, $vr0, 1
; LA64-NEXT:    vpackev.b $vr0, $vr1, $vr0
; LA64-NEXT:    vstelm.h $vr0, $a1, 0, 0
; LA64-NEXT:    ret
  %a = load <2 x i32>, ptr %ptr
  %trunc = trunc <2 x i32> %a to <2 x i8>
  store <2 x i8> %trunc, ptr %dst
  ret void
}

define void @load_trunc_4i16_to_4i8(ptr %ptr, ptr %dst) nounwind {
; LA32-LABEL: load_trunc_4i16_to_4i8:
; LA32:       # %bb.0:
; LA32-NEXT:    ld.w $a2, $a0, 0
; LA32-NEXT:    ld.w $a0, $a0, 4
; LA32-NEXT:    vinsgr2vr.w $vr0, $a2, 0
; LA32-NEXT:    vinsgr2vr.w $vr0, $a0, 1
; LA32-NEXT:    vpickev.b $vr0, $vr0, $vr0
; LA32-NEXT:    vpickve2gr.w $a0, $vr0, 0
; LA32-NEXT:    st.w $a0, $a1, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: load_trunc_4i16_to_4i8:
; LA64:       # %bb.0:
; LA64-NEXT:    ld.d $a0, $a0, 0
; LA64-NEXT:    vinsgr2vr.d $vr0, $a0, 0
; LA64-NEXT:    vpickev.b $vr0, $vr0, $vr0
; LA64-NEXT:    vstelm.w $vr0, $a1, 0, 0
; LA64-NEXT:    ret
  %a = load <4 x i16>, ptr %ptr
  %trunc = trunc <4 x i16> %a to <4 x i8>
  store <4 x i8> %trunc, ptr %dst
  ret void
}

define void @load_trunc_2i16_to_2i8(ptr %ptr, ptr %dst) nounwind {
; LA32-LABEL: load_trunc_2i16_to_2i8:
; LA32:       # %bb.0:
; LA32-NEXT:    ld.w $a0, $a0, 0
; LA32-NEXT:    vinsgr2vr.w $vr0, $a0, 0
; LA32-NEXT:    vshuf4i.b $vr0, $vr0, 8
; LA32-NEXT:    vstelm.h $vr0, $a1, 0, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: load_trunc_2i16_to_2i8:
; LA64:       # %bb.0:
; LA64-NEXT:    ld.w $a0, $a0, 0
; LA64-NEXT:    vinsgr2vr.w $vr0, $a0, 0
; LA64-NEXT:    vshuf4i.b $vr0, $vr0, 8
; LA64-NEXT:    vstelm.h $vr0, $a1, 0, 0
; LA64-NEXT:    ret
  %a = load <2 x i16>, ptr %ptr
  %trunc = trunc <2 x i16> %a to <2 x i8>
  store <2 x i8> %trunc, ptr %dst
  ret void
}
