; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx %s -o - | FileCheck %s --check-prefix=LA32
; RUN: llc --mtriple=loongarch64 --mattr=+lsx %s -o - | FileCheck %s --check-prefix=LA64

define <4 x i8> @test_trunc_v4i16_to_v4i8(<4 x i16> %arg) {
; LA32-LABEL: test_trunc_v4i16_to_v4i8:
; LA32:       # %bb.0:
; LA32-NEXT:    vpickev.b $vr0, $vr0, $vr0
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v4i16_to_v4i8:
; LA64:       # %bb.0:
; LA64-NEXT:    vpickev.b $vr0, $vr0, $vr0
; LA64-NEXT:    ret
  %trunc = trunc <4 x i16> %arg to <4 x i8>
  ret <4 x i8> %trunc
}

define <4 x i8> @test_trunc_v4i32_to_v4i8(<4 x i32> %arg) {
; LA32-LABEL: test_trunc_v4i32_to_v4i8:
; LA32:       # %bb.0:
; LA32-NEXT:    pcalau12i $a0, %pc_hi20(.LCPI1_0)
; LA32-NEXT:    vld $vr1, $a0, %pc_lo12(.LCPI1_0)
; LA32-NEXT:    vshuf.b $vr0, $vr0, $vr0, $vr1
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v4i32_to_v4i8:
; LA64:       # %bb.0:
; LA64-NEXT:    pcalau12i $a0, %pc_hi20(.LCPI1_0)
; LA64-NEXT:    vld $vr1, $a0, %pc_lo12(.LCPI1_0)
; LA64-NEXT:    vshuf.b $vr0, $vr0, $vr0, $vr1
; LA64-NEXT:    ret
  %trunc = trunc <4 x i32> %arg to <4 x i8>
  ret <4 x i8> %trunc
}

define <4 x i16> @test_trunc_v4i32_to_v4i16(<4 x i32> %arg) {
; LA32-LABEL: test_trunc_v4i32_to_v4i16:
; LA32:       # %bb.0:
; LA32-NEXT:    vpickev.h $vr0, $vr0, $vr0
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v4i32_to_v4i16:
; LA64:       # %bb.0:
; LA64-NEXT:    vpickev.h $vr0, $vr0, $vr0
; LA64-NEXT:    ret
  %trunc = trunc <4 x i32> %arg to <4 x i16>
  ret <4 x i16> %trunc
}

define <4 x i8> @test_trunc_v4i64_to_v4i8(<4 x i64> %arg) {
; LA32-LABEL: test_trunc_v4i64_to_v4i8:
; LA32:       # %bb.0:
; LA32-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA32-NEXT:    vpickev.h $vr0, $vr0, $vr0
; LA32-NEXT:    vpickev.b $vr0, $vr0, $vr0
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v4i64_to_v4i8:
; LA64:       # %bb.0:
; LA64-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA64-NEXT:    vpickev.h $vr0, $vr0, $vr0
; LA64-NEXT:    vpickev.b $vr0, $vr0, $vr0
; LA64-NEXT:    ret
  %trunc = trunc <4 x i64> %arg to <4 x i8>
  ret <4 x i8> %trunc
}

define <4 x i16> @test_trunc_v4i64_to_v4i16(<4 x i64> %arg) {
; LA32-LABEL: test_trunc_v4i64_to_v4i16:
; LA32:       # %bb.0:
; LA32-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA32-NEXT:    vpickev.h $vr0, $vr0, $vr0
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v4i64_to_v4i16:
; LA64:       # %bb.0:
; LA64-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA64-NEXT:    vpickev.h $vr0, $vr0, $vr0
; LA64-NEXT:    ret
  %trunc = trunc <4 x i64> %arg to <4 x i16>
  ret <4 x i16> %trunc
}

define <4 x i32> @test_trunc_v4i64_to_v4i32(<4 x i64> %arg) {
; LA32-LABEL: test_trunc_v4i64_to_v4i32:
; LA32:       # %bb.0:
; LA32-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v4i64_to_v4i32:
; LA64:       # %bb.0:
; LA64-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA64-NEXT:    ret
  %trunc = trunc <4 x i64> %arg to <4 x i32>
  ret <4 x i32> %trunc
}

define <8 x i8> @test_trunc_v8i32_to_v8i8(<8 x i32> %arg) {
; LA32-LABEL: test_trunc_v8i32_to_v8i8:
; LA32:       # %bb.0:
; LA32-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA32-NEXT:    vpickev.b $vr0, $vr0, $vr0
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v8i32_to_v8i8:
; LA64:       # %bb.0:
; LA64-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA64-NEXT:    vpickev.b $vr0, $vr0, $vr0
; LA64-NEXT:    ret
  %trunc = trunc <8 x i32> %arg to <8 x i8>
  ret <8 x i8> %trunc
}

define <8 x i16> @test_trunc_v8i32_to_v8i16(<8 x i32> %arg) {
; LA32-LABEL: test_trunc_v8i32_to_v8i16:
; LA32:       # %bb.0:
; LA32-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v8i32_to_v8i16:
; LA64:       # %bb.0:
; LA64-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA64-NEXT:    ret
  %trunc = trunc <8 x i32> %arg to <8 x i16>
  ret <8 x i16> %trunc
}

define <8 x i8> @test_trunc_v8i64_to_v8i8(<8 x i64> %arg) {
; LA32-LABEL: test_trunc_v8i64_to_v8i8:
; LA32:       # %bb.0:
; LA32-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA32-NEXT:    vpickev.w $vr1, $vr3, $vr2
; LA32-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA32-NEXT:    vpickev.b $vr0, $vr0, $vr0
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v8i64_to_v8i8:
; LA64:       # %bb.0:
; LA64-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA64-NEXT:    vpickev.w $vr1, $vr3, $vr2
; LA64-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA64-NEXT:    vpickev.b $vr0, $vr0, $vr0
; LA64-NEXT:    ret
  %trunc = trunc <8 x i64> %arg to <8 x i8>
  ret <8 x i8> %trunc
}

define <8 x i16> @test_trunc_v8i64_to_v8i16(<8 x i64> %arg) {
; LA32-LABEL: test_trunc_v8i64_to_v8i16:
; LA32:       # %bb.0:
; LA32-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA32-NEXT:    vpickev.w $vr1, $vr3, $vr2
; LA32-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v8i64_to_v8i16:
; LA64:       # %bb.0:
; LA64-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA64-NEXT:    vpickev.w $vr1, $vr3, $vr2
; LA64-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA64-NEXT:    ret
  %trunc = trunc <8 x i64> %arg to <8 x i16>
  ret <8 x i16> %trunc
}

define <8 x i32> @test_trunc_v8i64_to_v8i32(<8 x i64> %arg) {
; LA32-LABEL: test_trunc_v8i64_to_v8i32:
; LA32:       # %bb.0:
; LA32-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA32-NEXT:    vpickev.w $vr1, $vr3, $vr2
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v8i64_to_v8i32:
; LA64:       # %bb.0:
; LA64-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA64-NEXT:    vpickev.w $vr1, $vr3, $vr2
; LA64-NEXT:    ret
  %trunc = trunc <8 x i64> %arg to <8 x i32>
  ret <8 x i32> %trunc
}

define <16 x i8> @test_trunc_v16i32_to_v16i8(<16 x i32> %arg) {
; LA32-LABEL: test_trunc_v16i32_to_v16i8:
; LA32:       # %bb.0:
; LA32-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA32-NEXT:    vpickev.h $vr1, $vr3, $vr2
; LA32-NEXT:    vpickev.b $vr0, $vr1, $vr0
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v16i32_to_v16i8:
; LA64:       # %bb.0:
; LA64-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA64-NEXT:    vpickev.h $vr1, $vr3, $vr2
; LA64-NEXT:    vpickev.b $vr0, $vr1, $vr0
; LA64-NEXT:    ret
  %trunc = trunc <16 x i32> %arg to <16 x i8>
  ret <16 x i8> %trunc
}

define <16 x i16> @test_trunc_v16i32_to_v16i16(<16 x i32> %arg) {
; LA32-LABEL: test_trunc_v16i32_to_v16i16:
; LA32:       # %bb.0:
; LA32-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA32-NEXT:    vpickev.h $vr1, $vr3, $vr2
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v16i32_to_v16i16:
; LA64:       # %bb.0:
; LA64-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA64-NEXT:    vpickev.h $vr1, $vr3, $vr2
; LA64-NEXT:    ret
  %trunc = trunc <16 x i32> %arg to <16 x i16>
  ret <16 x i16> %trunc
}

define <16 x i8> @test_trunc_v16i64_to_v16i8(<16 x i64> %arg) {
; LA32-LABEL: test_trunc_v16i64_to_v16i8:
; LA32:       # %bb.0:
; LA32-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA32-NEXT:    vpickev.w $vr1, $vr3, $vr2
; LA32-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA32-NEXT:    vpickev.w $vr1, $vr5, $vr4
; LA32-NEXT:    vpickev.w $vr2, $vr7, $vr6
; LA32-NEXT:    vpickev.h $vr1, $vr2, $vr1
; LA32-NEXT:    vpickev.b $vr0, $vr1, $vr0
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v16i64_to_v16i8:
; LA64:       # %bb.0:
; LA64-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA64-NEXT:    vpickev.w $vr1, $vr3, $vr2
; LA64-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA64-NEXT:    vpickev.w $vr1, $vr5, $vr4
; LA64-NEXT:    vpickev.w $vr2, $vr7, $vr6
; LA64-NEXT:    vpickev.h $vr1, $vr2, $vr1
; LA64-NEXT:    vpickev.b $vr0, $vr1, $vr0
; LA64-NEXT:    ret
  %trunc = trunc <16 x i64> %arg to <16 x i8>
  ret <16 x i8> %trunc
}

define <16 x i16> @test_trunc_v16i64_to_v16i16(<16 x i64> %arg) {
; LA32-LABEL: test_trunc_v16i64_to_v16i16:
; LA32:       # %bb.0:
; LA32-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA32-NEXT:    vpickev.w $vr1, $vr3, $vr2
; LA32-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA32-NEXT:    vpickev.w $vr1, $vr5, $vr4
; LA32-NEXT:    vpickev.w $vr2, $vr7, $vr6
; LA32-NEXT:    vpickev.h $vr1, $vr2, $vr1
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v16i64_to_v16i16:
; LA64:       # %bb.0:
; LA64-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA64-NEXT:    vpickev.w $vr1, $vr3, $vr2
; LA64-NEXT:    vpickev.h $vr0, $vr1, $vr0
; LA64-NEXT:    vpickev.w $vr1, $vr5, $vr4
; LA64-NEXT:    vpickev.w $vr2, $vr7, $vr6
; LA64-NEXT:    vpickev.h $vr1, $vr2, $vr1
; LA64-NEXT:    ret
  %trunc = trunc <16 x i64> %arg to <16 x i16>
  ret <16 x i16> %trunc
}

define <16 x i32> @test_trunc_v16i64_to_v16i32(<16 x i64> %arg) {
; LA32-LABEL: test_trunc_v16i64_to_v16i32:
; LA32:       # %bb.0:
; LA32-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA32-NEXT:    vpickev.w $vr1, $vr3, $vr2
; LA32-NEXT:    vpickev.w $vr2, $vr5, $vr4
; LA32-NEXT:    vpickev.w $vr3, $vr7, $vr6
; LA32-NEXT:    vst $vr3, $a0, 48
; LA32-NEXT:    vst $vr2, $a0, 32
; LA32-NEXT:    vst $vr1, $a0, 16
; LA32-NEXT:    vst $vr0, $a0, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trunc_v16i64_to_v16i32:
; LA64:       # %bb.0:
; LA64-NEXT:    vpickev.w $vr0, $vr1, $vr0
; LA64-NEXT:    vpickev.w $vr1, $vr3, $vr2
; LA64-NEXT:    vpickev.w $vr2, $vr5, $vr4
; LA64-NEXT:    vpickev.w $vr3, $vr7, $vr6
; LA64-NEXT:    vst $vr3, $a0, 48
; LA64-NEXT:    vst $vr2, $a0, 32
; LA64-NEXT:    vst $vr1, $a0, 16
; LA64-NEXT:    vst $vr0, $a0, 0
; LA64-NEXT:    ret
  %trunc = trunc <16 x i64> %arg to <16 x i32>
  ret <16 x i32> %trunc
}
