; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx < %s | FileCheck %s --check-prefixes=CHECK,LA32
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s --check-prefixes=CHECK,LA64

define void @vhaddw_h_b_illegal(ptr %a, ptr %b, ptr %r) nounwind {
; LA32-LABEL: vhaddw_h_b_illegal:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    ld.w $a3, $a0, 0
; LA32-NEXT:    ld.w $a0, $a0, 4
; LA32-NEXT:    ld.w $a4, $a1, 0
; LA32-NEXT:    ld.w $a1, $a1, 4
; LA32-NEXT:    vinsgr2vr.w $vr0, $a3, 0
; LA32-NEXT:    vinsgr2vr.w $vr0, $a0, 1
; LA32-NEXT:    vinsgr2vr.w $vr1, $a4, 0
; LA32-NEXT:    vinsgr2vr.w $vr1, $a1, 1
; LA32-NEXT:    vpickod.b $vr0, $vr0, $vr0
; LA32-NEXT:    vpickev.b $vr1, $vr1, $vr1
; LA32-NEXT:    vslti.b $vr2, $vr0, 0
; LA32-NEXT:    vilvl.b $vr0, $vr2, $vr0
; LA32-NEXT:    vslti.b $vr2, $vr1, 0
; LA32-NEXT:    vilvl.b $vr1, $vr2, $vr1
; LA32-NEXT:    vadd.h $vr0, $vr0, $vr1
; LA32-NEXT:    vpickve2gr.w $a0, $vr0, 0
; LA32-NEXT:    st.w $a0, $a2, 0
; LA32-NEXT:    vpickve2gr.w $a0, $vr0, 1
; LA32-NEXT:    st.w $a0, $a2, 4
; LA32-NEXT:    ret
;
; LA64-LABEL: vhaddw_h_b_illegal:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    ld.d $a0, $a0, 0
; LA64-NEXT:    ld.d $a1, $a1, 0
; LA64-NEXT:    vinsgr2vr.d $vr0, $a0, 0
; LA64-NEXT:    vinsgr2vr.d $vr1, $a1, 0
; LA64-NEXT:    vpickod.b $vr0, $vr0, $vr0
; LA64-NEXT:    vpickev.b $vr1, $vr1, $vr1
; LA64-NEXT:    vslti.b $vr2, $vr0, 0
; LA64-NEXT:    vilvl.b $vr0, $vr2, $vr0
; LA64-NEXT:    vslti.b $vr2, $vr1, 0
; LA64-NEXT:    vilvl.b $vr1, $vr2, $vr1
; LA64-NEXT:    vadd.h $vr0, $vr0, $vr1
; LA64-NEXT:    vstelm.d $vr0, $a2, 0, 0
; LA64-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %a
  %1 = load <8 x i8>, ptr %b
  %2 = shufflevector <8 x i8> %0, <8 x i8> poison,
                     <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %3 = shufflevector <8 x i8> %1, <8 x i8> poison,
                     <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %4 = sext <4 x i8> %2 to <4 x i16>
  %5 = sext <4 x i8> %3 to <4 x i16>
  %6 = add <4 x i16> %4, %5
  store <4 x i16> %6, ptr %r
  ret void
}

define void @vhaddw_h_b(ptr %a, ptr %b, ptr %r) nounwind {
; CHECK-LABEL: vhaddw_h_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vld $vr1, $a1, 0
; CHECK-NEXT:    vpickod.b $vr0, $vr0, $vr0
; CHECK-NEXT:    vpickev.b $vr1, $vr1, $vr1
; CHECK-NEXT:    vslti.b $vr2, $vr0, 0
; CHECK-NEXT:    vilvl.b $vr0, $vr2, $vr0
; CHECK-NEXT:    vslti.b $vr2, $vr1, 0
; CHECK-NEXT:    vilvl.b $vr1, $vr2, $vr1
; CHECK-NEXT:    vadd.h $vr0, $vr0, $vr1
; CHECK-NEXT:    vst $vr0, $a2, 0
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %a
  %1 = load <16 x i8>, ptr %b
  %2 = shufflevector <16 x i8> %0, <16 x i8> poison,
                     <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %3 = shufflevector <16 x i8> %1, <16 x i8> poison,
                     <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %4 = sext <8 x i8> %2 to <8 x i16>
  %5 = sext <8 x i8> %3 to <8 x i16>
  %6 = add <8 x i16> %4, %5
  store <8 x i16> %6, ptr %r
  ret void
}

define void @vhaddw_w_h(ptr %a, ptr %b, ptr %r) nounwind {
; CHECK-LABEL: vhaddw_w_h:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vld $vr1, $a1, 0
; CHECK-NEXT:    vpickod.h $vr0, $vr0, $vr0
; CHECK-NEXT:    vpickev.h $vr1, $vr1, $vr1
; CHECK-NEXT:    vslti.h $vr2, $vr0, 0
; CHECK-NEXT:    vilvl.h $vr0, $vr2, $vr0
; CHECK-NEXT:    vslti.h $vr2, $vr1, 0
; CHECK-NEXT:    vilvl.h $vr1, $vr2, $vr1
; CHECK-NEXT:    vadd.w $vr0, $vr0, $vr1
; CHECK-NEXT:    vst $vr0, $a2, 0
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %a
  %1 = load <8 x i16>, ptr %b
  %2 = shufflevector <8 x i16> %0, <8 x i16> poison,
                     <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %3 = shufflevector <8 x i16> %1, <8 x i16> poison,
                     <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %4 = sext <4 x i16> %2 to <4 x i32>
  %5 = sext <4 x i16> %3 to <4 x i32>
  %6 = add <4 x i32> %4, %5
  store <4 x i32> %6, ptr %r
  ret void
}

define void @vhaddw_d_w(ptr %a, ptr %b, ptr %r) nounwind {
; CHECK-LABEL: vhaddw_d_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vld $vr1, $a1, 0
; CHECK-NEXT:    vshuf4i.w $vr0, $vr0, 13
; CHECK-NEXT:    vshuf4i.w $vr1, $vr1, 8
; CHECK-NEXT:    vslti.w $vr2, $vr0, 0
; CHECK-NEXT:    vilvl.w $vr0, $vr2, $vr0
; CHECK-NEXT:    vslti.w $vr2, $vr1, 0
; CHECK-NEXT:    vilvl.w $vr1, $vr2, $vr1
; CHECK-NEXT:    vadd.d $vr0, $vr0, $vr1
; CHECK-NEXT:    vst $vr0, $a2, 0
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %a
  %1 = load <4 x i32>, ptr %b
  %2 = shufflevector <4 x i32> %0, <4 x i32> poison, <2 x i32> <i32 1, i32 3>
  %3 = shufflevector <4 x i32> %1, <4 x i32> poison, <2 x i32> <i32 0, i32 2>
  %4 = sext <2 x i32> %2 to <2 x i64>
  %5 = sext <2 x i32> %3 to <2 x i64>
  %6 = add <2 x i64> %4, %5
  store <2 x i64> %6, ptr %r
  ret void
}

define void @vhaddw_hu_bu(ptr %a, ptr %b, ptr %r) nounwind {
; CHECK-LABEL: vhaddw_hu_bu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vld $vr1, $a1, 0
; CHECK-NEXT:    pcalau12i $a0, %pc_hi20(.LCPI4_0)
; CHECK-NEXT:    vld $vr2, $a0, %pc_lo12(.LCPI4_0)
; CHECK-NEXT:    vrepli.b $vr3, 0
; CHECK-NEXT:    vpackod.b $vr0, $vr3, $vr0
; CHECK-NEXT:    vshuf.b $vr1, $vr3, $vr1, $vr2
; CHECK-NEXT:    vadd.h $vr0, $vr0, $vr1
; CHECK-NEXT:    vst $vr0, $a2, 0
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %a
  %1 = load <16 x i8>, ptr %b
  %2 = shufflevector <16 x i8> %0, <16 x i8> poison,
                     <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %3 = shufflevector <16 x i8> %1, <16 x i8> poison,
                     <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %4 = zext <8 x i8> %2 to <8 x i16>
  %5 = zext <8 x i8> %3 to <8 x i16>
  %6 = add <8 x i16> %4, %5
  store <8 x i16> %6, ptr %r
  ret void
}

define void @vhaddw_wu_hu(ptr %a, ptr %b, ptr %r) nounwind {
; CHECK-LABEL: vhaddw_wu_hu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vld $vr1, $a1, 0
; CHECK-NEXT:    pcalau12i $a0, %pc_hi20(.LCPI5_0)
; CHECK-NEXT:    vld $vr2, $a0, %pc_lo12(.LCPI5_0)
; CHECK-NEXT:    vrepli.b $vr3, 0
; CHECK-NEXT:    vpackod.h $vr0, $vr3, $vr0
; CHECK-NEXT:    vshuf.h $vr2, $vr3, $vr1
; CHECK-NEXT:    vadd.w $vr0, $vr0, $vr2
; CHECK-NEXT:    vst $vr0, $a2, 0
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %a
  %1 = load <8 x i16>, ptr %b
  %2 = shufflevector <8 x i16> %0, <8 x i16> poison,
                     <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %3 = shufflevector <8 x i16> %1, <8 x i16> poison,
                     <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %4 = zext <4 x i16> %2 to <4 x i32>
  %5 = zext <4 x i16> %3 to <4 x i32>
  %6 = add <4 x i32> %4, %5
  store <4 x i32> %6, ptr %r
  ret void
}

define void @vhaddw_du_wu(ptr %a, ptr %b, ptr %r) nounwind {
; CHECK-LABEL: vhaddw_du_wu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vld $vr1, $a1, 0
; CHECK-NEXT:    pcalau12i $a0, %pc_hi20(.LCPI6_0)
; CHECK-NEXT:    vld $vr2, $a0, %pc_lo12(.LCPI6_0)
; CHECK-NEXT:    vrepli.b $vr3, 0
; CHECK-NEXT:    vpackod.w $vr0, $vr3, $vr0
; CHECK-NEXT:    vshuf.w $vr2, $vr3, $vr1
; CHECK-NEXT:    vadd.d $vr0, $vr0, $vr2
; CHECK-NEXT:    vst $vr0, $a2, 0
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %a
  %1 = load <4 x i32>, ptr %b
  %2 = shufflevector <4 x i32> %0, <4 x i32> poison, <2 x i32> <i32 1, i32 3>
  %3 = shufflevector <4 x i32> %1, <4 x i32> poison, <2 x i32> <i32 0, i32 2>
  %4 = zext <2 x i32> %2 to <2 x i64>
  %5 = zext <2 x i32> %3 to <2 x i64>
  %6 = add <2 x i64> %4, %5
  store <2 x i64> %6, ptr %r
  ret void
}
