; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s

define void @vsllwil_h_b(ptr %a, ptr %r) nounwind {
; CHECK-LABEL: vsllwil_h_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vslti.b $vr1, $vr0, 0
; CHECK-NEXT:    vilvl.b $vr0, $vr1, $vr0
; CHECK-NEXT:    vslli.h $vr0, $vr0, 1
; CHECK-NEXT:    vst $vr0, $a1, 0
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %a
  %1 = shufflevector <16 x i8> %0, <16 x i8> poison,
                     <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %2 = sext <8 x i8> %1 to <8 x i16>
  %3 = shl nsw <8 x i16> %2, splat (i16 1)
  store <8 x i16> %3, ptr %r
  ret void
}

define void @vsllwil_w_h(ptr %a, ptr %r) nounwind {
; CHECK-LABEL: vsllwil_w_h:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vslti.h $vr1, $vr0, 0
; CHECK-NEXT:    vilvl.h $vr0, $vr1, $vr0
; CHECK-NEXT:    vslli.w $vr0, $vr0, 15
; CHECK-NEXT:    vst $vr0, $a1, 0
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %a
  %1 = shufflevector <8 x i16> %0, <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %2 = sext <4 x i16> %1 to <4 x i32>
  %3 = shl nsw <4 x i32> %2, splat (i32 15)
  store <4 x i32> %3, ptr %r
  ret void
}

define void @vsllwil_d_w(ptr %a, ptr %r) nounwind {
; CHECK-LABEL: vsllwil_d_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vslti.w $vr1, $vr0, 0
; CHECK-NEXT:    vilvl.w $vr0, $vr1, $vr0
; CHECK-NEXT:    vslli.d $vr0, $vr0, 31
; CHECK-NEXT:    vst $vr0, $a1, 0
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %a
  %1 = shufflevector <4 x i32> %0, <4 x i32> poison, <2 x i32> <i32 0, i32 1>
  %2 = sext <2 x i32> %1 to <2 x i64>
  %3 = shl nsw <2 x i64> %2, splat (i64 31)
  store <2 x i64> %3, ptr %r
  ret void
}

define void @vsllwil_hu_bu(ptr %a, ptr %r) nounwind {
; CHECK-LABEL: vsllwil_hu_bu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vrepli.b $vr1, 0
; CHECK-NEXT:    vilvl.b $vr0, $vr1, $vr0
; CHECK-NEXT:    vslli.h $vr0, $vr0, 1
; CHECK-NEXT:    vst $vr0, $a1, 0
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %a
  %1 = shufflevector <16 x i8> %0, <16 x i8> poison,
                     <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %2 = zext <8 x i8> %1 to <8 x i16>
  %3 = shl nsw <8 x i16> %2, splat (i16 1)
  store <8 x i16> %3, ptr %r
  ret void
}

define void @vsllwil_wu_hu(ptr %a, ptr %r) nounwind {
; CHECK-LABEL: vsllwil_wu_hu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vrepli.b $vr1, 0
; CHECK-NEXT:    vilvl.h $vr0, $vr1, $vr0
; CHECK-NEXT:    vslli.w $vr0, $vr0, 15
; CHECK-NEXT:    vst $vr0, $a1, 0
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %a
  %1 = shufflevector <8 x i16> %0, <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %2 = zext <4 x i16> %1 to <4 x i32>
  %3 = shl nsw <4 x i32> %2, splat (i32 15)
  store <4 x i32> %3, ptr %r
  ret void
}

define void @vsllwil_du_wu(ptr %a, ptr %r) nounwind {
; CHECK-LABEL: vsllwil_du_wu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vrepli.b $vr1, 0
; CHECK-NEXT:    vilvl.w $vr0, $vr1, $vr0
; CHECK-NEXT:    vslli.d $vr0, $vr0, 31
; CHECK-NEXT:    vst $vr0, $a1, 0
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %a
  %1 = shufflevector <4 x i32> %0, <4 x i32> poison, <2 x i32> <i32 0, i32 1>
  %2 = zext <2 x i32> %1 to <2 x i64>
  %3 = shl nsw <2 x i64> %2, splat (i64 31)
  store <2 x i64> %3, ptr %r
  ret void
}
