; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=attributor -S < %s | FileCheck %s

target datalayout = "e-p:64:64-p1:64:64:64:64-p2:64:64:64:16"

; Regression test for GitHub issue #165691.

declare void @consume_as2(<1 x ptr addrspace(2)>)

define void @ptr_vector_bitcast_base(<1 x ptr> %v) {
; CHECK-LABEL: define void @ptr_vector_bitcast_base(
; CHECK-SAME: <1 x ptr> [[V:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    ret void
;
  %p = bitcast <1 x ptr> %v to ptr
  load i8, ptr %p, align 1
  ret void
}

define void @ptr_vector_ptrmask_from_bitcast(ptr %p) {
; CHECK-LABEL: define void @ptr_vector_ptrmask_from_bitcast(
; CHECK-SAME: ptr nofree readnone captures(none) [[P:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    ret void
;
  %v = bitcast ptr %p to <1 x ptr>
  %m = call <1 x ptr> @llvm.ptrmask.v1p0.v1i64(<1 x ptr> %v, <1 x i64> <i64 -8>)
  ret void
}

declare <1 x ptr> @llvm.ptrmask.v1p0.v1i64(<1 x ptr>, <1 x i64>)

define void @ptr_vector_addrspace_large_offset_gep(ptr %p) {
; CHECK-LABEL: define void @ptr_vector_addrspace_large_offset_gep(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[P1:%.*]] = addrspacecast ptr [[P]] to ptr addrspace(1)
; CHECK-NEXT:    [[VEC1:%.*]] = bitcast ptr addrspace(1) [[P1]] to <1 x ptr addrspace(1)>
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr i8, <1 x ptr addrspace(1)> [[VEC1]], i64 65536
; CHECK-NEXT:    [[V:%.*]] = addrspacecast <1 x ptr addrspace(1)> [[GEP1]] to <1 x ptr addrspace(2)>
; CHECK-NEXT:    call void @consume_as2(<1 x ptr addrspace(2)> [[V]])
; CHECK-NEXT:    ret void
;
  %p1 = addrspacecast ptr %p to ptr addrspace(1)
  %vec1 = bitcast ptr addrspace(1) %p1 to <1 x ptr addrspace(1)>
  %gep1 = getelementptr i8, <1 x ptr addrspace(1)> %vec1, i64 65536
  %v = addrspacecast <1 x ptr addrspace(1)> %gep1 to <1 x ptr addrspace(2)>
  call void @consume_as2(<1 x ptr addrspace(2)> %v)
  ret void
}
