; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -aa-pipeline=basic-aa -passes=attributor -attributor-manifest-internal -S < %s | FileCheck %s --check-prefixes=CHECK,TUNIT

declare float @llvm.canonicalize.f32(float)

define float @ret_canonicalize(float %arg0) {
; CHECK-LABEL: define nofpclass(snan) float @ret_canonicalize
; CHECK-SAME: (float [[ARG0:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan) float @llvm.canonicalize.f32(float [[ARG0]]) #[[ATTR12:[0-9]+]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %arg0)
  ret float %call
}

define float @ret_canonicalize_noinf(float nofpclass(inf) %arg0) {
; CHECK-LABEL: define nofpclass(snan inf) float @ret_canonicalize_noinf
; CHECK-SAME: (float nofpclass(inf) [[ARG0:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan inf) float @llvm.canonicalize.f32(float nofpclass(inf) [[ARG0]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %arg0)
  ret float %call
}

define float @ret_canonicalize_dynamic_denormal(float nofpclass(inf) %arg0) denormal_fpenv(dynamic) {
; CHECK-LABEL: define nofpclass(snan inf) float @ret_canonicalize_dynamic_denormal
; CHECK-SAME: (float nofpclass(inf) [[ARG0:%.*]]) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan inf) float @llvm.canonicalize.f32(float nofpclass(inf) [[ARG0]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %arg0)
  ret float %call
}

define float @ret_canonicalize_daz_denormal(float nofpclass(inf) %arg0) denormal_fpenv(dynamic|preservesign) {
; CHECK-LABEL: define nofpclass(snan inf sub) float @ret_canonicalize_daz_denormal
; CHECK-SAME: (float nofpclass(inf) [[ARG0:%.*]]) #[[ATTR3:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan inf sub) float @llvm.canonicalize.f32(float nofpclass(inf) [[ARG0]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %arg0)
  ret float %call
}

define float @ret_canonicalize_dapz_denormal(float nofpclass(inf) %arg0) denormal_fpenv(dynamic|positivezero) {
; CHECK-LABEL: define nofpclass(snan inf nzero sub) float @ret_canonicalize_dapz_denormal
; CHECK-SAME: (float nofpclass(inf) [[ARG0:%.*]]) #[[ATTR4:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan inf nzero sub) float @llvm.canonicalize.f32(float nofpclass(inf) [[ARG0]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %arg0)
  ret float %call
}

define float @ret_canonicalize_ftpz_dapz_denormal(float nofpclass(inf) %arg0) denormal_fpenv(positivezero|preservesign) {
; CHECK-LABEL: define nofpclass(snan inf sub) float @ret_canonicalize_ftpz_dapz_denormal
; CHECK-SAME: (float nofpclass(inf) [[ARG0:%.*]]) #[[ATTR5:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan inf sub) float @llvm.canonicalize.f32(float nofpclass(inf) [[ARG0]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %arg0)
  ret float %call
}

define float @ret_canonicalize_ftpz_ieee_denormal(float nofpclass(inf) %arg0) denormal_fpenv(positivezero|ieee) {
; CHECK-LABEL: define nofpclass(snan inf nzero sub) float @ret_canonicalize_ftpz_ieee_denormal
; CHECK-SAME: (float nofpclass(inf) [[ARG0:%.*]]) #[[ATTR6:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan inf nzero sub) float @llvm.canonicalize.f32(float nofpclass(inf) [[ARG0]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %arg0)
  ret float %call
}

define float @ret_canonicalize_ftpz_dynamic_denormal(float nofpclass(inf) %arg0) denormal_fpenv(positivezero|dynamic) {
; CHECK-LABEL: define nofpclass(snan inf sub) float @ret_canonicalize_ftpz_dynamic_denormal
; CHECK-SAME: (float nofpclass(inf) [[ARG0:%.*]]) #[[ATTR7:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan inf sub) float @llvm.canonicalize.f32(float nofpclass(inf) [[ARG0]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %arg0)
  ret float %call
}

define float @ret_canonicalize_ftz_denormal(float nofpclass(inf) %arg0) denormal_fpenv(preservesign|dynamic) {
; CHECK-LABEL: define nofpclass(snan inf sub) float @ret_canonicalize_ftz_denormal
; CHECK-SAME: (float nofpclass(inf) [[ARG0:%.*]]) #[[ATTR8:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan inf sub) float @llvm.canonicalize.f32(float nofpclass(inf) [[ARG0]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %arg0)
  ret float %call
}

define float @ret_canonicalize_ieee_denormal(float nofpclass(inf) %arg0) denormal_fpenv(ieee|ieee) {
; CHECK-LABEL: define nofpclass(snan inf) float @ret_canonicalize_ieee_denormal
; CHECK-SAME: (float nofpclass(inf) [[ARG0:%.*]]) #[[ATTR9:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan inf) float @llvm.canonicalize.f32(float nofpclass(inf) [[ARG0]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %arg0)
  ret float %call
}

define float @ret_canonicalize_ieee_constant_pos_denormal() denormal_fpenv(ieee|ieee) {
; CHECK-LABEL: define noundef nofpclass(nan inf zero nsub norm) float @ret_canonicalize_ieee_constant_pos_denormal
; CHECK-SAME: () #[[ATTR9]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf zero nsub norm) float @llvm.canonicalize.f32(float noundef 1.401300e-45) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x36A0000000000000)
  ret float %call
}

define float @ret_canonicalize_ieee_constant_neg_denormal() denormal_fpenv(ieee|ieee) {
; CHECK-LABEL: define noundef nofpclass(nan inf zero psub norm) float @ret_canonicalize_ieee_constant_neg_denormal
; CHECK-SAME: () #[[ATTR9]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf zero psub norm) float @llvm.canonicalize.f32(float noundef -1.401300e-45) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0xb6A0000000000000)
  ret float %call
}

define float @ret_canonicalize_ieee_constant_pos_zero() denormal_fpenv(ieee|ieee) {
; CHECK-LABEL: define noundef nofpclass(nan inf nzero sub norm) float @ret_canonicalize_ieee_constant_pos_zero
; CHECK-SAME: () #[[ATTR9]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf nzero sub norm) float @llvm.canonicalize.f32(float noundef 0.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0.0)
  ret float %call
}

define float @ret_canonicalize_ieee_constant_neg_zero() denormal_fpenv(ieee|ieee) {
; CHECK-LABEL: define noundef nofpclass(nan inf pzero sub norm) float @ret_canonicalize_ieee_constant_neg_zero
; CHECK-SAME: () #[[ATTR9]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf pzero sub norm) float @llvm.canonicalize.f32(float noundef -0.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float -0.0)
  ret float %call
}

define float @ret_canonicalize_ieee_constant_pos_normal() denormal_fpenv(ieee|ieee) {
; CHECK-LABEL: define noundef nofpclass(nan inf zero sub nnorm) float @ret_canonicalize_ieee_constant_pos_normal
; CHECK-SAME: () #[[ATTR9]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf zero sub nnorm) float @llvm.canonicalize.f32(float noundef 8.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 8.0)
  ret float %call
}

define float @ret_canonicalize_ieee_constant_neg_normal() denormal_fpenv(ieee|ieee) {
; CHECK-LABEL: define noundef nofpclass(nan inf zero sub pnorm) float @ret_canonicalize_ieee_constant_neg_normal
; CHECK-SAME: () #[[ATTR9]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf zero sub pnorm) float @llvm.canonicalize.f32(float noundef -8.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float -8.0)
  ret float %call
}

define float @ret_canonicalize_ieee_constant_pos_inf() denormal_fpenv(ieee|ieee) {
; CHECK-LABEL: define noundef nofpclass(nan ninf zero sub norm) float @ret_canonicalize_ieee_constant_pos_inf
; CHECK-SAME: () #[[ATTR9]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan ninf zero sub norm) float @llvm.canonicalize.f32(float noundef +inf) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x7FF0000000000000)
  ret float %call
}

define float @ret_canonicalize_ieee_constant_neg_inf() denormal_fpenv(ieee|ieee) {
; CHECK-LABEL: define noundef nofpclass(nan pinf zero sub norm) float @ret_canonicalize_ieee_constant_neg_inf
; CHECK-SAME: () #[[ATTR9]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan pinf zero sub norm) float @llvm.canonicalize.f32(float noundef -inf) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0xFFF0000000000000)
  ret float %call
}

define float @ret_canonicalize_ieee_constant_qnan() denormal_fpenv(ieee|ieee) {
; CHECK-LABEL: define noundef nofpclass(snan inf zero sub norm) float @ret_canonicalize_ieee_constant_qnan
; CHECK-SAME: () #[[ATTR9]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(snan inf zero sub norm) float @llvm.canonicalize.f32(float noundef +qnan) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x7FF8000000000000)
  ret float %call
}

define float @ret_canonicalize_ieee_constant_snan() denormal_fpenv(ieee|ieee) {
; CHECK-LABEL: define noundef nofpclass(snan inf zero sub norm) float @ret_canonicalize_ieee_constant_snan
; CHECK-SAME: () #[[ATTR9]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(snan inf zero sub norm) float @llvm.canonicalize.f32(float noundef +snan(0x80000)) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x7FF1000000000000)
  ret float %call
}

define float @ret_canonicalize_daz_constant_pos_denormal() denormal_fpenv(preservesign) {
; CHECK-LABEL: define noundef nofpclass(nan inf nzero sub norm) float @ret_canonicalize_daz_constant_pos_denormal
; CHECK-SAME: () #[[ATTR10:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf nzero sub norm) float @llvm.canonicalize.f32(float noundef 1.401300e-45) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x36A0000000000000)
  ret float %call
}

define float @ret_canonicalize_daz_constant_neg_denormal() denormal_fpenv(preservesign) {
; CHECK-LABEL: define noundef nofpclass(nan inf pzero sub norm) float @ret_canonicalize_daz_constant_neg_denormal
; CHECK-SAME: () #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf pzero sub norm) float @llvm.canonicalize.f32(float noundef -1.401300e-45) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0xb6A0000000000000)
  ret float %call
}

define float @ret_canonicalize_daz_constant_pos_zero() denormal_fpenv(preservesign) {
; CHECK-LABEL: define noundef nofpclass(nan inf nzero sub norm) float @ret_canonicalize_daz_constant_pos_zero
; CHECK-SAME: () #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf nzero sub norm) float @llvm.canonicalize.f32(float noundef 0.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0.0)
  ret float %call
}

define float @ret_canonicalize_daz_constant_neg_zero() denormal_fpenv(preservesign) {
; CHECK-LABEL: define noundef nofpclass(nan inf pzero sub norm) float @ret_canonicalize_daz_constant_neg_zero
; CHECK-SAME: () #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf pzero sub norm) float @llvm.canonicalize.f32(float noundef -0.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float -0.0)
  ret float %call
}

define float @ret_canonicalize_daz_constant_pos_normal() denormal_fpenv(preservesign) {
; CHECK-LABEL: define noundef nofpclass(nan inf zero sub nnorm) float @ret_canonicalize_daz_constant_pos_normal
; CHECK-SAME: () #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf zero sub nnorm) float @llvm.canonicalize.f32(float noundef 8.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 8.0)
  ret float %call
}

define float @ret_canonicalize_daz_constant_neg_normal() denormal_fpenv(preservesign) {
; CHECK-LABEL: define noundef nofpclass(nan inf zero sub pnorm) float @ret_canonicalize_daz_constant_neg_normal
; CHECK-SAME: () #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf zero sub pnorm) float @llvm.canonicalize.f32(float noundef -8.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float -8.0)
  ret float %call
}

define float @ret_canonicalize_daz_constant_pos_inf() denormal_fpenv(preservesign) {
; CHECK-LABEL: define noundef nofpclass(nan ninf zero sub norm) float @ret_canonicalize_daz_constant_pos_inf
; CHECK-SAME: () #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan ninf zero sub norm) float @llvm.canonicalize.f32(float noundef +inf) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x7FF0000000000000)
  ret float %call
}

define float @ret_canonicalize_daz_constant_neg_inf() denormal_fpenv(preservesign) {
; CHECK-LABEL: define noundef nofpclass(nan pinf zero sub norm) float @ret_canonicalize_daz_constant_neg_inf
; CHECK-SAME: () #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan pinf zero sub norm) float @llvm.canonicalize.f32(float noundef -inf) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0xFFF0000000000000)
  ret float %call
}

define float @ret_canonicalize_daz_constant_qnan() denormal_fpenv(preservesign) {
; CHECK-LABEL: define noundef nofpclass(snan inf zero sub norm) float @ret_canonicalize_daz_constant_qnan
; CHECK-SAME: () #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(snan inf zero sub norm) float @llvm.canonicalize.f32(float noundef +qnan) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x7FF8000000000000)
  ret float %call
}

define float @ret_canonicalize_daz_constant_snan() denormal_fpenv(preservesign) {
; CHECK-LABEL: define noundef nofpclass(snan inf zero sub norm) float @ret_canonicalize_daz_constant_snan
; CHECK-SAME: () #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(snan inf zero sub norm) float @llvm.canonicalize.f32(float noundef +snan(0x80000)) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x7FF1000000000000)
  ret float %call
}

define float @ret_canonicalize_dapz_constant_pos_denormal() denormal_fpenv(positivezero|positivezero) {
; CHECK-LABEL: define noundef nofpclass(nan inf nzero sub norm) float @ret_canonicalize_dapz_constant_pos_denormal
; CHECK-SAME: () #[[ATTR11:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf nzero sub norm) float @llvm.canonicalize.f32(float noundef 1.401300e-45) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x36A0000000000000)
  ret float %call
}

define float @ret_canonicalize_dapz_constant_neg_denormal() denormal_fpenv(positivezero|positivezero) {
; CHECK-LABEL: define noundef nofpclass(nan inf nzero sub norm) float @ret_canonicalize_dapz_constant_neg_denormal
; CHECK-SAME: () #[[ATTR11]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf nzero sub norm) float @llvm.canonicalize.f32(float noundef -1.401300e-45) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0xb6A0000000000000)
  ret float %call
}

define float @ret_canonicalize_dapz_constant_pos_zero() denormal_fpenv(positivezero|positivezero) {
; CHECK-LABEL: define noundef nofpclass(nan inf nzero sub norm) float @ret_canonicalize_dapz_constant_pos_zero
; CHECK-SAME: () #[[ATTR11]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf nzero sub norm) float @llvm.canonicalize.f32(float noundef 0.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0.0)
  ret float %call
}

define float @ret_canonicalize_dapz_constant_neg_zero() denormal_fpenv(positivezero|positivezero) {
; CHECK-LABEL: define noundef nofpclass(nan inf nzero sub norm) float @ret_canonicalize_dapz_constant_neg_zero
; CHECK-SAME: () #[[ATTR11]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf nzero sub norm) float @llvm.canonicalize.f32(float noundef -0.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float -0.0)
  ret float %call
}

define float @ret_canonicalize_dapz_constant_pos_normal() denormal_fpenv(positivezero|positivezero) {
; CHECK-LABEL: define noundef nofpclass(nan inf nzero sub nnorm) float @ret_canonicalize_dapz_constant_pos_normal
; CHECK-SAME: () #[[ATTR11]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf nzero sub nnorm) float @llvm.canonicalize.f32(float noundef 8.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 8.0)
  ret float %call
}

define float @ret_canonicalize_dapz_constant_neg_normal() denormal_fpenv(positivezero|positivezero) {
; CHECK-LABEL: define noundef nofpclass(nan inf nzero sub pnorm) float @ret_canonicalize_dapz_constant_neg_normal
; CHECK-SAME: () #[[ATTR11]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf nzero sub pnorm) float @llvm.canonicalize.f32(float noundef -8.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float -8.0)
  ret float %call
}

define float @ret_canonicalize_dapz_constant_pos_inf() denormal_fpenv(positivezero|positivezero) {
; CHECK-LABEL: define noundef nofpclass(nan ninf nzero sub norm) float @ret_canonicalize_dapz_constant_pos_inf
; CHECK-SAME: () #[[ATTR11]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan ninf nzero sub norm) float @llvm.canonicalize.f32(float noundef +inf) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x7FF0000000000000)
  ret float %call
}

define float @ret_canonicalize_dapz_constant_neg_inf() denormal_fpenv(positivezero|positivezero) {
; CHECK-LABEL: define noundef nofpclass(nan pinf nzero sub norm) float @ret_canonicalize_dapz_constant_neg_inf
; CHECK-SAME: () #[[ATTR11]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan pinf nzero sub norm) float @llvm.canonicalize.f32(float noundef -inf) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0xFFF0000000000000)
  ret float %call
}

define float @ret_canonicalize_dapz_constant_qnan() denormal_fpenv(positivezero|positivezero) {
; CHECK-LABEL: define noundef nofpclass(snan inf nzero sub norm) float @ret_canonicalize_dapz_constant_qnan
; CHECK-SAME: () #[[ATTR11]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(snan inf nzero sub norm) float @llvm.canonicalize.f32(float noundef +qnan) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x7FF8000000000000)
  ret float %call
}

define float @ret_canonicalize_dapz_constant_snan() denormal_fpenv(positivezero|positivezero) {
; CHECK-LABEL: define noundef nofpclass(snan inf nzero sub norm) float @ret_canonicalize_dapz_constant_snan
; CHECK-SAME: () #[[ATTR11]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(snan inf nzero sub norm) float @llvm.canonicalize.f32(float noundef +snan(0x80000)) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x7FF1000000000000)
  ret float %call
}

define float @ret_canonicalize_dynamic_constant_pos_denormal() denormal_fpenv(dynamic) {
; CHECK-LABEL: define noundef nofpclass(nan inf nsub norm) float @ret_canonicalize_dynamic_constant_pos_denormal
; CHECK-SAME: () #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf nsub norm) float @llvm.canonicalize.f32(float noundef 1.401300e-45) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x36A0000000000000)
  ret float %call
}

define float @ret_canonicalize_dynamic_constant_neg_denormal() denormal_fpenv(dynamic) {
; CHECK-LABEL: define noundef nofpclass(nan inf psub norm) float @ret_canonicalize_dynamic_constant_neg_denormal
; CHECK-SAME: () #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf psub norm) float @llvm.canonicalize.f32(float noundef -1.401300e-45) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0xb6A0000000000000)
  ret float %call
}

define float @ret_canonicalize_dynamic_constant_pos_zero() denormal_fpenv(dynamic) {
; CHECK-LABEL: define noundef nofpclass(nan inf sub norm) float @ret_canonicalize_dynamic_constant_pos_zero
; CHECK-SAME: () #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf sub norm) float @llvm.canonicalize.f32(float noundef 0.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0.0)
  ret float %call
}

define float @ret_canonicalize_dynamic_constant_neg_zero() denormal_fpenv(dynamic) {
; CHECK-LABEL: define noundef nofpclass(nan inf sub norm) float @ret_canonicalize_dynamic_constant_neg_zero
; CHECK-SAME: () #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf sub norm) float @llvm.canonicalize.f32(float noundef -0.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float -0.0)
  ret float %call
}

define float @ret_canonicalize_dynamic_constant_pos_normal() denormal_fpenv(dynamic) {
; CHECK-LABEL: define noundef nofpclass(nan inf sub nnorm) float @ret_canonicalize_dynamic_constant_pos_normal
; CHECK-SAME: () #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf sub nnorm) float @llvm.canonicalize.f32(float noundef 8.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 8.0)
  ret float %call
}

define float @ret_canonicalize_dynamic_constant_neg_normal() denormal_fpenv(dynamic) {
; CHECK-LABEL: define noundef nofpclass(nan inf sub pnorm) float @ret_canonicalize_dynamic_constant_neg_normal
; CHECK-SAME: () #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan inf sub pnorm) float @llvm.canonicalize.f32(float noundef -8.000000e+00) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float -8.0)
  ret float %call
}

define float @ret_canonicalize_dynamic_constant_pos_inf() denormal_fpenv(dynamic) {
; CHECK-LABEL: define noundef nofpclass(nan ninf sub norm) float @ret_canonicalize_dynamic_constant_pos_inf
; CHECK-SAME: () #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan ninf sub norm) float @llvm.canonicalize.f32(float noundef +inf) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x7FF0000000000000)
  ret float %call
}

define float @ret_canonicalize_dynamic_constant_neg_inf() denormal_fpenv(dynamic) {
; CHECK-LABEL: define noundef nofpclass(nan pinf sub norm) float @ret_canonicalize_dynamic_constant_neg_inf
; CHECK-SAME: () #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(nan pinf sub norm) float @llvm.canonicalize.f32(float noundef -inf) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0xFFF0000000000000)
  ret float %call
}

define float @ret_canonicalize_dynamic_constant_qnan() denormal_fpenv(dynamic) {
; CHECK-LABEL: define noundef nofpclass(snan inf sub norm) float @ret_canonicalize_dynamic_constant_qnan
; CHECK-SAME: () #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(snan inf sub norm) float @llvm.canonicalize.f32(float noundef +qnan) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x7FF8000000000000)
  ret float %call
}

define float @ret_canonicalize_dynamic_constant_snan() denormal_fpenv(dynamic) {
; CHECK-LABEL: define noundef nofpclass(snan inf sub norm) float @ret_canonicalize_dynamic_constant_snan
; CHECK-SAME: () #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call noundef nofpclass(snan inf sub norm) float @llvm.canonicalize.f32(float noundef +snan(0x80000)) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float 0x7FF1000000000000)
  ret float %call
}

define float @ret_canonicalize_daz_not_nzero_not_nsub(float nofpclass(nzero nsub) %x) denormal_fpenv(preservesign) {
; CHECK-LABEL: define nofpclass(snan nzero sub) float @ret_canonicalize_daz_not_nzero_not_nsub
; CHECK-SAME: (float nofpclass(nzero nsub) [[X:%.*]]) #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan nzero sub) float @llvm.canonicalize.f32(float nofpclass(nzero nsub) [[X]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %x)
  ret float %call
}

define float @ret_canonicalize_daz_not_nsub(float nofpclass(nsub) %x) denormal_fpenv(preservesign) {
; CHECK-LABEL: define nofpclass(snan sub) float @ret_canonicalize_daz_not_nsub
; CHECK-SAME: (float nofpclass(nsub) [[X:%.*]]) #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan sub) float @llvm.canonicalize.f32(float nofpclass(nsub) [[X]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %x)
  ret float %call
}

define float @ret_canonicalize_daz_not_nzero(float nofpclass(nzero) %x) denormal_fpenv(preservesign) {
; CHECK-LABEL: define nofpclass(snan sub) float @ret_canonicalize_daz_not_nzero
; CHECK-SAME: (float nofpclass(nzero) [[X:%.*]]) #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan sub) float @llvm.canonicalize.f32(float nofpclass(nzero) [[X]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %x)
  ret float %call
}

define float @ret_canonicalize_daz_not_pzero_not_psub(float nofpclass(pzero psub) %x) denormal_fpenv(preservesign) {
; CHECK-LABEL: define nofpclass(snan pzero sub) float @ret_canonicalize_daz_not_pzero_not_psub
; CHECK-SAME: (float nofpclass(pzero psub) [[X:%.*]]) #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan pzero sub) float @llvm.canonicalize.f32(float nofpclass(pzero psub) [[X]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %x)
  ret float %call
}

define float @ret_canonicalize_daz_not_psub(float nofpclass(psub) %x) denormal_fpenv(preservesign) {
; CHECK-LABEL: define nofpclass(snan sub) float @ret_canonicalize_daz_not_psub
; CHECK-SAME: (float nofpclass(psub) [[X:%.*]]) #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan sub) float @llvm.canonicalize.f32(float nofpclass(psub) [[X]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %x)
  ret float %call
}

define float @ret_canonicalize_daz_not_pzero(float nofpclass(pzero) %x) denormal_fpenv(preservesign) {
; CHECK-LABEL: define nofpclass(snan sub) float @ret_canonicalize_daz_not_pzero
; CHECK-SAME: (float nofpclass(pzero) [[X:%.*]]) #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan sub) float @llvm.canonicalize.f32(float nofpclass(pzero) [[X]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %x)
  ret float %call
}

define float @ret_canonicalize_daz_not_zero(float nofpclass(zero) %x) denormal_fpenv(preservesign) {
; CHECK-LABEL: define nofpclass(snan sub) float @ret_canonicalize_daz_not_zero
; CHECK-SAME: (float nofpclass(zero) [[X:%.*]]) #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan sub) float @llvm.canonicalize.f32(float nofpclass(zero) [[X]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %x)
  ret float %call
}

define float @ret_canonicalize_daz_not_sub(float nofpclass(sub) %x) denormal_fpenv(preservesign) {
; CHECK-LABEL: define nofpclass(snan sub) float @ret_canonicalize_daz_not_sub
; CHECK-SAME: (float nofpclass(sub) [[X:%.*]]) #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan sub) float @llvm.canonicalize.f32(float nofpclass(sub) [[X]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %x)
  ret float %call
}

define float @ret_canonicalize_daz_not_sub_not_nzero(float nofpclass(sub nzero) %x) denormal_fpenv(preservesign) {
; CHECK-LABEL: define nofpclass(snan nzero sub) float @ret_canonicalize_daz_not_sub_not_nzero
; CHECK-SAME: (float nofpclass(nzero sub) [[X:%.*]]) #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan nzero sub) float @llvm.canonicalize.f32(float nofpclass(nzero sub) [[X]]) #[[ATTR12]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.canonicalize.f32(float %x)
  ret float %call
}

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; TUNIT: {{.*}}
