; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=attributor %s -o - | FileCheck %s

@g = internal unnamed_addr addrspace(4) constant [3 x i8] c"12\00", align 16

define void @foo(i32 %a, i32 %b, ptr %p) {
; CHECK-LABEL: define void @foo(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], ptr nofree nonnull writeonly captures(none) dereferenceable(1) [[P:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[L1:.*]], label %[[L2:.*]]
; CHECK:       [[L1]]:
; CHECK-NEXT:    br label %[[L3:.*]]
; CHECK:       [[L2]]:
; CHECK-NEXT:    br label %[[L3]]
; CHECK:       [[L3]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi ptr addrspace(4) [ @g, %[[L1]] ], [ getelementptr inbounds nuw (i8, ptr addrspace(4) @g, i64 1), %[[L2]] ]
; CHECK-NEXT:    [[LOAD:%.*]] = load i8, ptr addrspace(4) [[PHI]], align 1
; CHECK-NEXT:    store i8 [[LOAD]], ptr [[P]], align 1
; CHECK-NEXT:    ret void
;
entry:
  %cmp = icmp ne i32 %a, %b
  br i1 %cmp, label %l1, label %l2
l1:
  br label %l3
l2:
  br label %l3
l3:
  %phi = phi ptr addrspace(4) [ @g, %l1 ], [ getelementptr inbounds nuw (i8, ptr addrspace(4) @g, i64 1), %l2 ]
  %load = load i8, ptr addrspace(4) %phi
  store i8 %load, ptr %p
  ret void
}
