; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --check-attributes --check-globals
; RUN: opt -aa-pipeline=basic-aa -passes=attributor -attributor-manifest-internal  -attributor-max-iterations-verify -attributor-annotate-decl-cs -attributor-max-iterations=2 -S < %s | FileCheck %s --check-prefixes=CHECK,TUNIT
; RUN: opt -aa-pipeline=basic-aa -passes=attributor-cgscc -attributor-manifest-internal  -attributor-annotate-decl-cs -S < %s | FileCheck %s --check-prefixes=CHECK,CGSCC

define void @non_recursive_asm_fn() #0 {
; CHECK: Function Attrs: norecurse
; CHECK-LABEL: define {{[^@]+}}@non_recursive_asm_fn
; CHECK-SAME: () #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void asm sideeffect "barrier.sync $0
; CHECK-NEXT:    ret void
;
entry:
  call void asm sideeffect "barrier.sync $0;", "r,~{memory},~{dirflag},~{fpsr},~{flags}"(i32 1)
  ret void
}

define void @non_recursive_asm_cs() {
; CHECK: Function Attrs: norecurse
; CHECK-LABEL: define {{[^@]+}}@non_recursive_asm_cs
; CHECK-SAME: () #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void asm sideeffect "barrier.sync $0
; CHECK-NEXT:    ret void
;
entry:
  call void asm sideeffect "barrier.sync $0;", "r,~{memory},~{dirflag},~{fpsr},~{flags}"(i32 1) #0
  ret void
}

define void @non_recursive_asm_no_sideffect() {
; CHECK: Function Attrs: norecurse
; CHECK-LABEL: define {{[^@]+}}@non_recursive_asm_no_sideffect
; CHECK-SAME: () #[[ATTR1]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void asm "foobar
; CHECK-NEXT:    ret void
;
entry:
  call void asm "foobar;", ""()
  ret void
}

define void @recursive_asm() {
; CHECK-LABEL: define {{[^@]+}}@recursive_asm() {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void asm sideeffect "barrier.sync $0
; CHECK-NEXT:    ret void
;
entry:
  call void asm sideeffect "barrier.sync $0;", "r,~{memory},~{dirflag},~{fpsr},~{flags}"(i32 1)
  ret void
}

attributes #0 = { "llvm.assume"="ompx_no_call_asm" }
;.
; CHECK: attributes #[[ATTR0]] = { norecurse "llvm.assume"="ompx_no_call_asm" }
; CHECK: attributes #[[ATTR1]] = { norecurse }
; CHECK: attributes #[[ATTR2:[0-9]+]] = { "llvm.assume"="ompx_no_call_asm" }
;.
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CGSCC: {{.*}}
; TUNIT: {{.*}}
