// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -no-opaque-pointers -triple riscv32 -target-feature +experimental-zbf -emit-llvm %s -o - \
// RUN:     | FileCheck %s  -check-prefix=RV32ZBF

// RV32ZBF-LABEL: @bfp32(
// RV32ZBF-NEXT:  entry:
// RV32ZBF-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// RV32ZBF-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// RV32ZBF-NEXT:    store i32 [[A:%.*]], i32* [[A_ADDR]], align 4
// RV32ZBF-NEXT:    store i32 [[B:%.*]], i32* [[B_ADDR]], align 4
// RV32ZBF-NEXT:    [[TMP0:%.*]] = load i32, i32* [[A_ADDR]], align 4
// RV32ZBF-NEXT:    [[TMP1:%.*]] = load i32, i32* [[B_ADDR]], align 4
// RV32ZBF-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.bfp.i32(i32 [[TMP0]], i32 [[TMP1]])
// RV32ZBF-NEXT:    ret i32 [[TMP2]]
//
int bfp32(int a, int b) {
  return __builtin_riscv_bfp_32(a, b);
}
