// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +zbkx -emit-llvm %s -o - \
// RUN:     | FileCheck %s  -check-prefix=RV32ZBKX

// RV32ZBKX-LABEL: @xperm8(
// RV32ZBKX-NEXT:  entry:
// RV32ZBKX-NEXT:    [[RS1_ADDR:%.*]] = alloca i32, align 4
// RV32ZBKX-NEXT:    [[RS2_ADDR:%.*]] = alloca i32, align 4
// RV32ZBKX-NEXT:    store i32 [[RS1:%.*]], ptr [[RS1_ADDR]], align 4
// RV32ZBKX-NEXT:    store i32 [[RS2:%.*]], ptr [[RS2_ADDR]], align 4
// RV32ZBKX-NEXT:    [[TMP0:%.*]] = load i32, ptr [[RS1_ADDR]], align 4
// RV32ZBKX-NEXT:    [[TMP1:%.*]] = load i32, ptr [[RS2_ADDR]], align 4
// RV32ZBKX-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.xperm8.i32(i32 [[TMP0]], i32 [[TMP1]])
// RV32ZBKX-NEXT:    ret i32 [[TMP2]]
//
int xperm8(int rs1, int rs2)
{
  return __builtin_riscv_xperm8_32(rs1, rs2);
}

// RV32ZBKX-LABEL: @xperm4(
// RV32ZBKX-NEXT:  entry:
// RV32ZBKX-NEXT:    [[RS1_ADDR:%.*]] = alloca i32, align 4
// RV32ZBKX-NEXT:    [[RS2_ADDR:%.*]] = alloca i32, align 4
// RV32ZBKX-NEXT:    store i32 [[RS1:%.*]], ptr [[RS1_ADDR]], align 4
// RV32ZBKX-NEXT:    store i32 [[RS2:%.*]], ptr [[RS2_ADDR]], align 4
// RV32ZBKX-NEXT:    [[TMP0:%.*]] = load i32, ptr [[RS1_ADDR]], align 4
// RV32ZBKX-NEXT:    [[TMP1:%.*]] = load i32, ptr [[RS2_ADDR]], align 4
// RV32ZBKX-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.xperm4.i32(i32 [[TMP0]], i32 [[TMP1]])
// RV32ZBKX-NEXT:    ret i32 [[TMP2]]
//
int xperm4(int rs1, int rs2)
{
  return __builtin_riscv_xperm4_32(rs1, rs2);
}
