; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S %s -passes=scalarize-masked-mem-intrin -mtriple=x86_64-linux-gnu | FileCheck %s

; The constant-mask scalarization fast paths must propagate the metadata of the
; original masked intrinsic onto the scalar loads/stores they create, matching
; the all-true and predicated paths.

define <2 x i64> @masked_load_const_mask(ptr %p, <2 x i64> %passthru) {
; CHECK-LABEL: @masked_load_const_mask(
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i64, ptr [[P:%.*]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[TMP1]], align 8, !range [[RNG0:![0-9]+]], !alias.scope [[META1:![0-9]+]], !noalias [[META1]], !nontemporal [[META4:![0-9]+]]
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <2 x i64> [[PASSTHRU:%.*]], i64 [[TMP2]], i64 0
; CHECK-NEXT:    ret <2 x i64> [[TMP3]]
;
  %ret = call <2 x i64> @llvm.masked.load.v2i64.p0(ptr %p, i32 8, <2 x i1> <i1 true, i1 false>, <2 x i64> %passthru), !range !0, !nontemporal !1, !alias.scope !2, !noalias !2
  ret <2 x i64> %ret
}

define void @masked_store_const_mask(ptr %p, <2 x i64> %val) {
; CHECK-LABEL: @masked_store_const_mask(
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x i64> [[VAL:%.*]], i64 0
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i64, ptr [[P:%.*]], i32 0
; CHECK-NEXT:    store i64 [[TMP1]], ptr [[TMP2]], align 8, !alias.scope [[META1]], !noalias [[META1]], !nontemporal [[META4]]
; CHECK-NEXT:    ret void
;
  call void @llvm.masked.store.v2i64.p0(<2 x i64> %val, ptr %p, i32 8, <2 x i1> <i1 true, i1 false>), !nontemporal !1, !alias.scope !2, !noalias !2
  ret void
}

define <2 x i64> @masked_gather_const_mask(<2 x ptr> %ptrs, <2 x i64> %passthru) {
; CHECK-LABEL: @masked_gather_const_mask(
; CHECK-NEXT:    [[PTR0:%.*]] = extractelement <2 x ptr> [[PTRS:%.*]], i64 0
; CHECK-NEXT:    [[LOAD0:%.*]] = load i64, ptr [[PTR0]], align 8, !range [[RNG0]], !alias.scope [[META1]], !noalias [[META1]], !nontemporal [[META4]]
; CHECK-NEXT:    [[RES0:%.*]] = insertelement <2 x i64> [[PASSTHRU:%.*]], i64 [[LOAD0]], i64 0
; CHECK-NEXT:    ret <2 x i64> [[RES0]]
;
  %ret = call <2 x i64> @llvm.masked.gather.v2i64.v2p0(<2 x ptr> %ptrs, i32 8, <2 x i1> <i1 true, i1 false>, <2 x i64> %passthru), !range !0, !nontemporal !1, !alias.scope !2, !noalias !2
  ret <2 x i64> %ret
}

define void @masked_scatter_const_mask(<2 x ptr> %ptrs, <2 x i64> %val) {
; CHECK-LABEL: @masked_scatter_const_mask(
; CHECK-NEXT:    [[ELT0:%.*]] = extractelement <2 x i64> [[VAL:%.*]], i64 0
; CHECK-NEXT:    [[PTR0:%.*]] = extractelement <2 x ptr> [[PTRS:%.*]], i64 0
; CHECK-NEXT:    store i64 [[ELT0]], ptr [[PTR0]], align 8, !alias.scope [[META1]], !noalias [[META1]], !nontemporal [[META4]]
; CHECK-NEXT:    ret void
;
  call void @llvm.masked.scatter.v2i64.v2p0(<2 x i64> %val, <2 x ptr> %ptrs, i32 8, <2 x i1> <i1 true, i1 false>), !nontemporal !1, !alias.scope !2, !noalias !2
  ret void
}

!0 = !{i64 0, i64 100}
!1 = !{i32 1}
!2 = !{!3}
!3 = distinct !{!3, !4}
!4 = distinct !{!4}
