; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 5
; RUN: opt < %s -passes=instrumentor -instrumentor-read-config-files=%S/call_flags_config.json -S | FileCheck %s

; This test checks that various CallIO flags are passed correctly:
; - callee address
; - callee_name
; - intrinsic_id (for both regular functions and intrinsics)
; - allocation_info (for allocation functions)
; - return_value (in post_call)
; - return_value_size (in post_call)
; - num_parameters
; - parameters (with replacement)
; - is_definition (different for declarations vs definitions)
; - id

target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

declare void @external_func(i32, i64)
declare ptr @malloc(i64) #0
declare void @free(ptr allocptr) #1
declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1)

;.
; CHECK: @__instrumentor_.str = private unnamed_addr constant [14 x i8] c"internal_func\00", align 1
; CHECK: @__instrumentor_value_pack = internal global <{ i32, i32, [4 x i8], i32 }> <{ i32 4, i32 12, [4 x i8] zeroinitializer, i32 0 }>
; CHECK: @__instrumentor_.str.1 = private unnamed_addr constant [14 x i8] c"external_func\00", align 1
; CHECK: @__instrumentor_value_pack.2 = internal global <{ i32, i32, [4 x i8], i32, i32, i32, i64 }> <{ i32 4, i32 12, [4 x i8] zeroinitializer, i32 0, i32 8, i32 12, i64 0 }>
; CHECK: @__instrumentor_.str.3 = private unnamed_addr constant [7 x i8] c"malloc\00", align 1
; CHECK: @__instrumentor_allocation_call_info = internal constant <{ ptr, i32, i32, i32, i8, i32 }> <{ ptr null, i32 0, i32 -1, i32 -1, i8 2, i32 0 }>
; CHECK: @__instrumentor_value_pack.4 = internal global <{ i32, i32, i64 }> <{ i32 8, i32 12, i64 100 }>
; CHECK: @__instrumentor_.str.5 = private unnamed_addr constant [19 x i8] c"llvm.memset.p0.i64\00", align 1
; CHECK: @__instrumentor_value_pack.6 = internal global <{ i32, i32, ptr, i32, i32, [7 x i8], i8, i32, i32, i64, i32, i32, [7 x i8], i1 }> <{ i32 8, i32 15, ptr null, i32 1, i32 12, [7 x i8] zeroinitializer, i8 0, i32 8, i32 12, i64 100, i32 1, i32 12, [7 x i8] zeroinitializer, i1 false }>
; CHECK: @__instrumentor_.str.7 = private unnamed_addr constant [5 x i8] c"free\00", align 1
; CHECK: @__instrumentor_deallocation_call_info = internal constant <{ ptr, i32, i32, i32 }> <{ ptr @__instrumentor_.str.3, i32 0, i32 -1, i32 -1 }>
; CHECK: @__instrumentor_value_pack.8 = internal global <{ i32, i32, ptr }> <{ i32 8, i32 15, ptr null }>
;.
define i32 @internal_func(i32 %x) {
; CHECK-LABEL: define i32 @internal_func(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[RESULT:%.*]] = add i32 [[X]], 42
; CHECK-NEXT:    ret i32 [[RESULT]]
;
entry:
  %result = add i32 %x, 42
  ret i32 %result
}

define i64 @test_calls(i32 %a, i64 %b) {
; CHECK-LABEL: define i64 @test_calls(
; CHECK-SAME: i32 [[A:%.*]], i64 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = alloca <{ i32, i32, ptr, i32, i32, [7 x i8], i8, i32, i32, i64, i32, i32, [7 x i8], i1 }>, align 8
; CHECK-NEXT:    [[TMP1:%.*]] = alloca <{ i32, i32, [4 x i8], i32, i32, i32, i64 }>, align 8
; CHECK-NEXT:    [[TMP2:%.*]] = alloca <{ i32, i32, [4 x i8], i32 }>, align 8
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP2]], ptr @__instrumentor_value_pack, i64 16, i1 false)
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw <{ i32, i32, [4 x i8], i32 }>, ptr [[TMP2]], i32 0, i32 3
; CHECK-NEXT:    store i32 [[A]], ptr [[TMP3]], align 4
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @internal_func, ptr @__instrumentor_.str, i64 0, ptr null, ptr null, i32 1, ptr [[TMP2]], i8 1, i32 1) #[[ATTR4:[0-9]+]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i8, ptr [[TMP2]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP4]], align 4
; CHECK-NEXT:    [[RESULT1:%.*]] = call i32 @internal_func(i32 [[TMP5]])
; CHECK-NEXT:    [[TMP6:%.*]] = zext i32 [[RESULT1]] to i64
; CHECK-NEXT:    [[TMP7:%.*]] = call i64 @__instrumentor_post_call(ptr @internal_func, ptr @__instrumentor_.str, i64 0, ptr null, ptr null, i64 [[TMP6]], i32 4, i32 1, ptr [[TMP2]], i8 1, i32 -1) #[[ATTR4]]
; CHECK-NEXT:    [[TMP8:%.*]] = trunc i64 [[TMP7]] to i32
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP1]], ptr @__instrumentor_value_pack.2, i64 32, i1 false)
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw <{ i32, i32, [4 x i8], i32, i32, i32, i64 }>, ptr [[TMP1]], i32 0, i32 3
; CHECK-NEXT:    store i32 [[TMP8]], ptr [[TMP9]], align 4
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw <{ i32, i32, [4 x i8], i32, i32, i32, i64 }>, ptr [[TMP1]], i32 0, i32 6
; CHECK-NEXT:    store i64 [[B]], ptr [[TMP10]], align 8
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @external_func, ptr @__instrumentor_.str.1, i64 0, ptr null, ptr null, i32 2, ptr [[TMP1]], i8 0, i32 2) #[[ATTR4]]
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i32 12
; CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[TMP11]], align 4
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i32 24
; CHECK-NEXT:    [[TMP14:%.*]] = load i64, ptr [[TMP13]], align 8
; CHECK-NEXT:    call void @external_func(i32 [[TMP12]], i64 [[TMP14]])
; CHECK-NEXT:    [[TMP15:%.*]] = call i64 @__instrumentor_post_call(ptr @external_func, ptr @__instrumentor_.str.1, i64 0, ptr null, ptr null, i64 0, i32 0, i32 2, ptr [[TMP1]], i8 0, i32 -2) #[[ATTR4]]
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP2]], ptr @__instrumentor_value_pack.4, i64 16, i1 false)
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @malloc, ptr @__instrumentor_.str.3, i64 0, ptr @__instrumentor_allocation_call_info, ptr null, i32 1, ptr [[TMP2]], i8 0, i32 3) #[[ATTR4]]
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i8, ptr [[TMP2]], i32 8
; CHECK-NEXT:    [[TMP17:%.*]] = load i64, ptr [[TMP16]], align 8
; CHECK-NEXT:    [[PTR:%.*]] = call ptr @malloc(i64 [[TMP17]])
; CHECK-NEXT:    [[TMP18:%.*]] = ptrtoint ptr [[PTR]] to i64
; CHECK-NEXT:    [[TMP19:%.*]] = call i64 @__instrumentor_post_call(ptr @malloc, ptr @__instrumentor_.str.3, i64 0, ptr @__instrumentor_allocation_call_info, ptr null, i64 [[TMP18]], i32 8, i32 1, ptr [[TMP2]], i8 0, i32 -3) #[[ATTR4]]
; CHECK-NEXT:    [[TMP20:%.*]] = inttoptr i64 [[TMP19]] to ptr
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP0]], ptr @__instrumentor_value_pack.6, i64 64, i1 false)
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw <{ i32, i32, ptr, i32, i32, [7 x i8], i8, i32, i32, i64, i32, i32, [7 x i8], i1 }>, ptr [[TMP0]], i32 0, i32 2
; CHECK-NEXT:    store ptr [[TMP20]], ptr [[TMP21]], align 8
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr null, ptr @__instrumentor_.str.5, i64 260, ptr null, ptr null, i32 4, ptr [[TMP0]], i8 0, i32 4) #[[ATTR4]]
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i32 8
; CHECK-NEXT:    [[TMP23:%.*]] = load ptr, ptr [[TMP22]], align 8
; CHECK-NEXT:    [[TMP24:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i32 31
; CHECK-NEXT:    [[TMP25:%.*]] = load i8, ptr [[TMP24]], align 1
; CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i32 40
; CHECK-NEXT:    [[TMP27:%.*]] = load i64, ptr [[TMP26]], align 8
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i32 63
; CHECK-NEXT:    [[TMP29:%.*]] = load i1, ptr [[TMP28]], align 1
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr [[TMP23]], i8 [[TMP25]], i64 [[TMP27]], i1 false)
; CHECK-NEXT:    [[TMP30:%.*]] = call i64 @__instrumentor_post_call(ptr null, ptr @__instrumentor_.str.5, i64 260, ptr null, ptr null, i64 0, i32 0, i32 4, ptr [[TMP0]], i8 0, i32 -4) #[[ATTR4]]
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP2]], ptr @__instrumentor_value_pack.8, i64 16, i1 false)
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr inbounds nuw <{ i32, i32, ptr }>, ptr [[TMP2]], i32 0, i32 2
; CHECK-NEXT:    store ptr [[TMP20]], ptr [[TMP31]], align 8
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @free, ptr @__instrumentor_.str.7, i64 0, ptr null, ptr @__instrumentor_deallocation_call_info, i32 1, ptr [[TMP2]], i8 0, i32 5) #[[ATTR4]]
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr inbounds i8, ptr [[TMP2]], i32 8
; CHECK-NEXT:    [[TMP33:%.*]] = load ptr, ptr [[TMP32]], align 8
; CHECK-NEXT:    call void @free(ptr [[TMP33]])
; CHECK-NEXT:    [[TMP34:%.*]] = call i64 @__instrumentor_post_call(ptr @free, ptr @__instrumentor_.str.7, i64 0, ptr null, ptr @__instrumentor_deallocation_call_info, i64 0, i32 0, i32 1, ptr [[TMP2]], i8 0, i32 -5) #[[ATTR4]]
; CHECK-NEXT:    [[RESULT2:%.*]] = zext i32 [[TMP8]] to i64
; CHECK-NEXT:    ret i64 [[RESULT2]]
;
entry:
  ; Test call to defined function - should have is_definition = true
  %result1 = call i32 @internal_func(i32 %a)

  ; Test call to external function - should have is_definition = false
  call void @external_func(i32 %result1, i64 %b)

  ; Test call to allocation function - should have allocation_info
  %ptr = call ptr @malloc(i64 100)

  ; Test call to intrinsic - should have intrinsic_id != 0, callee = nullptr
  call void @llvm.memset.p0.i64(ptr %ptr, i8 0, i64 100, i1 false)

  ; Test call to free function - should have deallocation_info
  call void @free(ptr %ptr)

  %result2 = zext i32 %result1 to i64
  ret i64 %result2
}

attributes #0 = { allockind("alloc,uninitialized") allocsize(0) }
attributes #1 = { allockind("free") "alloc-family"="malloc" }
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { allockind("alloc,uninitialized") allocsize(0) }
; CHECK: attributes #[[ATTR1:[0-9]+]] = { allockind("free") "alloc-family"="malloc" }
; CHECK: attributes #[[ATTR2:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(argmem: write) }
; CHECK: attributes #[[ATTR3:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
; CHECK: attributes #[[ATTR4]] = { willreturn }
;.
