; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 5
; RUN: opt < %s -passes=instrumentor -instrumentor-read-config-files=%S/call_filters_config.json -S | FileCheck %s

; This test checks that CallIO filters work correctly:
; - Only functions matching function_regex should be instrumented
; - Calls within filtered functions should be instrumented
; - Calls within non-matching functions should not be instrumented

target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

declare void @helper_func(i32)

; This function matches the filter "test_.*" and should be instrumented
;.
; CHECK: @__instrumentor_.str = private unnamed_addr constant [12 x i8] c"helper_func\00", align 1
;.
define void @test_filtered(i32 %x) {
; CHECK-LABEL: define void @test_filtered(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @helper_func, ptr @__instrumentor_.str, i32 1, i8 0, i32 1) #[[ATTR0:[0-9]+]]
; CHECK-NEXT:    call void @helper_func(i32 [[X]])
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @helper_func, ptr @__instrumentor_.str, i64 0, i32 0, i32 1, i8 0, i32 -1) #[[ATTR0]]
; CHECK-NEXT:    ret void
;
entry:
  call void @helper_func(i32 %x)
  ret void
}

; This function does NOT match the filter and should NOT be instrumented
define void @not_filtered(i32 %y) {
; CHECK-LABEL: define void @not_filtered(
; CHECK-SAME: i32 [[Y:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @helper_func(i32 [[Y]])
; CHECK-NEXT:    ret void
;
entry:
  call void @helper_func(i32 %y)
  ret void
}

; Another function matching the filter
define i32 @test_another(i32 %z) {
; CHECK-LABEL: define i32 @test_another(
; CHECK-SAME: i32 [[Z:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @helper_func, ptr @__instrumentor_.str, i32 1, i8 0, i32 2) #[[ATTR0]]
; CHECK-NEXT:    call void @helper_func(i32 [[Z]])
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @helper_func, ptr @__instrumentor_.str, i64 0, i32 0, i32 1, i8 0, i32 -2) #[[ATTR0]]
; CHECK-NEXT:    [[RESULT:%.*]] = add i32 [[Z]], 1
; CHECK-NEXT:    ret i32 [[RESULT]]
;
entry:
  call void @helper_func(i32 %z)
  %result = add i32 %z, 1
  ret i32 %result
}

; Edge case: function name contains "test_" but not at the start
define void @prefix_test_func(i32 %w) {
; CHECK-LABEL: define void @prefix_test_func(
; CHECK-SAME: i32 [[W:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @helper_func, ptr @__instrumentor_.str, i32 1, i8 0, i32 3) #[[ATTR0]]
; CHECK-NEXT:    call void @helper_func(i32 [[W]])
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @helper_func, ptr @__instrumentor_.str, i64 0, i32 0, i32 1, i8 0, i32 -3) #[[ATTR0]]
; CHECK-NEXT:    ret void
;
entry:
  call void @helper_func(i32 %w)
  ret void
}
;.
; CHECK: attributes #[[ATTR0]] = { willreturn }
;.
