; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 5
; RUN: opt < %s -passes="inferattrs,instrumentor" -instrumentor-read-config-files=%S/call_allocation_deallocation_config.json -S | FileCheck %s

; This test verifies that the Instrumentor pass correctly identifies and encodes
; allocation_info and deallocation_info for all C and C++ allocator and deallocator
; functions. The test checks:
; - C allocators: malloc, calloc, realloc, aligned_alloc
; - C deallocators: free
; - C++ allocators: operator new (various forms)
; - C++ deallocators: operator delete (various forms)
; - String duplicators: strdup, strndup

; ========== C Allocators ==========

; malloc(size_t size) - basic allocation
declare ptr @malloc(i64) #0

; calloc(size_t nmemb, size_t size) - zeroed allocation
declare ptr @calloc(i64, i64) #1

; realloc(void *ptr, size_t size) - reallocation
declare ptr @realloc(ptr, i64) #2

; aligned_alloc(size_t alignment, size_t size) - aligned allocation
declare ptr @aligned_alloc(i64, i64) #3

; ========== C Deallocators ==========

; free(void *ptr) - deallocation
declare void @free(ptr) #4

; ========== C++ Allocators (operator new) ==========

; operator new(unsigned long)
declare ptr @_Znwm(i64) #5

; operator new(unsigned long, nothrow)
declare ptr @_ZnwmRKSt9nothrow_t(i64, ptr) #6

; operator new(unsigned long, align_val_t)
declare ptr @_ZnwmSt11align_val_t(i64, i64) #7

; operator new(unsigned long, align_val_t, nothrow)
declare ptr @_ZnwmSt11align_val_tRKSt9nothrow_t(i64, i64, ptr) #8

; ========== C++ Allocators (operator new[]) ==========

; operator new[](unsigned long)
declare ptr @_Znam(i64) #9

; operator new[](unsigned long, nothrow)
declare ptr @_ZnamRKSt9nothrow_t(i64, ptr) #10

; operator new[](unsigned long, align_val_t)
declare ptr @_ZnamSt11align_val_t(i64, i64) #11

; operator new[](unsigned long, align_val_t, nothrow)
declare ptr @_ZnamSt11align_val_tRKSt9nothrow_t(i64, i64, ptr) #12

; ========== C++ Deallocators (operator delete) ==========

; operator delete(void*)
declare void @_ZdlPv(ptr) #13

; operator delete(void*, unsigned long) - sized delete
declare void @_ZdlPvm(ptr, i64) #14

; operator delete(void*, align_val_t)
declare void @_ZdlPvSt11align_val_t(ptr, i64) #15

; operator delete(void*, unsigned long, align_val_t) - sized aligned delete
declare void @_ZdlPvmSt11align_val_t(ptr, i64, i64) #16

; ========== C++ Deallocators (operator delete[]) ==========

; operator delete[](void*)
declare void @_ZdaPv(ptr) #17

; operator delete[](void*, unsigned long) - sized delete[]
declare void @_ZdaPvm(ptr, i64) #18

; operator delete[](void*, align_val_t)
declare void @_ZdaPvSt11align_val_t(ptr, i64) #19

; operator delete[](void*, unsigned long, align_val_t) - sized aligned delete[]
declare void @_ZdaPvmSt11align_val_t(ptr, i64, i64) #20

; ========== String Duplicators ==========

; strdup(const char *s)
declare ptr @strdup(ptr) #21

; strndup(const char *s, size_t n)
declare ptr @strndup(ptr, i64) #22

;.
; CHECK: @__instrumentor_.str = private unnamed_addr constant [7 x i8] c"malloc\00", align 1
; CHECK: @__instrumentor_allocation_call_info = internal constant <{ ptr, i32, i32, i32, i8, i32 }> <{ ptr @__instrumentor_.str, i32 0, i32 -1, i32 -1, i8 2, i32 0 }>
; CHECK: @__instrumentor_.str.1 = private unnamed_addr constant [7 x i8] c"calloc\00", align 1
; CHECK: @__instrumentor_allocation_call_info.2 = internal constant <{ ptr, i32, i32, i32, i8, i32 }> <{ ptr @__instrumentor_.str, i32 0, i32 1, i32 -1, i8 1, i32 0 }>
; CHECK: @__instrumentor_.str.3 = private unnamed_addr constant [8 x i8] c"realloc\00", align 1
; CHECK: @__instrumentor_allocation_call_info.4 = internal constant <{ ptr, i32, i32, i32, i8, i32 }> <{ ptr @__instrumentor_.str, i32 1, i32 -1, i32 -1, i8 0, i32 0 }>
; CHECK: @__instrumentor_.str.5 = private unnamed_addr constant [14 x i8] c"aligned_alloc\00", align 1
; CHECK: @__instrumentor_allocation_call_info.6 = internal constant <{ ptr, i32, i32, i32, i8, i32 }> <{ ptr @__instrumentor_.str, i32 1, i32 -1, i32 0, i8 2, i32 0 }>
; CHECK: @__instrumentor_.str.7 = private unnamed_addr constant [5 x i8] c"free\00", align 1
; CHECK: @__instrumentor_deallocation_call_info = internal constant <{ ptr, i32, i32, i32 }> <{ ptr @__instrumentor_.str, i32 0, i32 -1, i32 -1 }>
; CHECK: @__instrumentor_.str.8 = private unnamed_addr constant [6 x i8] c"_Znwm\00", align 1
; CHECK: @__instrumentor_allocation_call_info.9 = internal constant <{ ptr, i32, i32, i32, i8, i32 }> <{ ptr @__instrumentor_.str.8, i32 0, i32 -1, i32 -1, i8 2, i32 0 }>
; CHECK: @__instrumentor_.str.10 = private unnamed_addr constant [20 x i8] c"_ZnwmRKSt9nothrow_t\00", align 1
; CHECK: @__instrumentor_.str.11 = private unnamed_addr constant [21 x i8] c"_ZnwmSt11align_val_t\00", align 1
; CHECK: @__instrumentor_allocation_call_info.12 = internal constant <{ ptr, i32, i32, i32, i8, i32 }> <{ ptr @__instrumentor_.str.11, i32 0, i32 -1, i32 1, i8 2, i32 0 }>
; CHECK: @__instrumentor_.str.13 = private unnamed_addr constant [35 x i8] c"_ZnwmSt11align_val_tRKSt9nothrow_t\00", align 1
; CHECK: @__instrumentor_.str.14 = private unnamed_addr constant [6 x i8] c"_Znam\00", align 1
; CHECK: @__instrumentor_allocation_call_info.15 = internal constant <{ ptr, i32, i32, i32, i8, i32 }> <{ ptr @__instrumentor_.str.14, i32 0, i32 -1, i32 -1, i8 2, i32 0 }>
; CHECK: @__instrumentor_.str.16 = private unnamed_addr constant [20 x i8] c"_ZnamRKSt9nothrow_t\00", align 1
; CHECK: @__instrumentor_.str.17 = private unnamed_addr constant [21 x i8] c"_ZnamSt11align_val_t\00", align 1
; CHECK: @__instrumentor_allocation_call_info.18 = internal constant <{ ptr, i32, i32, i32, i8, i32 }> <{ ptr @__instrumentor_.str.17, i32 0, i32 -1, i32 1, i8 2, i32 0 }>
; CHECK: @__instrumentor_.str.19 = private unnamed_addr constant [35 x i8] c"_ZnamSt11align_val_tRKSt9nothrow_t\00", align 1
; CHECK: @__instrumentor_.str.20 = private unnamed_addr constant [7 x i8] c"_ZdlPv\00", align 1
; CHECK: @__instrumentor_deallocation_call_info.21 = internal constant <{ ptr, i32, i32, i32 }> <{ ptr @__instrumentor_.str.8, i32 0, i32 -1, i32 -1 }>
; CHECK: @__instrumentor_.str.22 = private unnamed_addr constant [8 x i8] c"_ZdlPvm\00", align 1
; CHECK: @__instrumentor_deallocation_call_info.23 = internal constant <{ ptr, i32, i32, i32 }> <{ ptr @__instrumentor_.str.8, i32 0, i32 1, i32 -1 }>
; CHECK: @__instrumentor_.str.24 = private unnamed_addr constant [22 x i8] c"_ZdlPvSt11align_val_t\00", align 1
; CHECK: @__instrumentor_deallocation_call_info.25 = internal constant <{ ptr, i32, i32, i32 }> <{ ptr @__instrumentor_.str.11, i32 0, i32 -1, i32 1 }>
; CHECK: @__instrumentor_.str.26 = private unnamed_addr constant [23 x i8] c"_ZdlPvmSt11align_val_t\00", align 1
; CHECK: @__instrumentor_deallocation_call_info.27 = internal constant <{ ptr, i32, i32, i32 }> <{ ptr @__instrumentor_.str.11, i32 0, i32 1, i32 2 }>
; CHECK: @__instrumentor_.str.28 = private unnamed_addr constant [7 x i8] c"_ZdaPv\00", align 1
; CHECK: @__instrumentor_deallocation_call_info.29 = internal constant <{ ptr, i32, i32, i32 }> <{ ptr @__instrumentor_.str.14, i32 0, i32 -1, i32 -1 }>
; CHECK: @__instrumentor_.str.30 = private unnamed_addr constant [8 x i8] c"_ZdaPvm\00", align 1
; CHECK: @__instrumentor_deallocation_call_info.31 = internal constant <{ ptr, i32, i32, i32 }> <{ ptr @__instrumentor_.str.14, i32 0, i32 1, i32 -1 }>
; CHECK: @__instrumentor_.str.32 = private unnamed_addr constant [22 x i8] c"_ZdaPvSt11align_val_t\00", align 1
; CHECK: @__instrumentor_deallocation_call_info.33 = internal constant <{ ptr, i32, i32, i32 }> <{ ptr @__instrumentor_.str.17, i32 0, i32 -1, i32 1 }>
; CHECK: @__instrumentor_.str.34 = private unnamed_addr constant [23 x i8] c"_ZdaPvmSt11align_val_t\00", align 1
; CHECK: @__instrumentor_deallocation_call_info.35 = internal constant <{ ptr, i32, i32, i32 }> <{ ptr @__instrumentor_.str.17, i32 0, i32 1, i32 2 }>
; CHECK: @__instrumentor_.str.36 = private unnamed_addr constant [7 x i8] c"strdup\00", align 1
; CHECK: @__instrumentor_allocation_call_info.37 = internal constant <{ ptr, i32, i32, i32, i8, i32 }> <{ ptr @__instrumentor_.str, i32 -1, i32 -1, i32 -1, i8 2, i32 0 }>
; CHECK: @__instrumentor_.str.38 = private unnamed_addr constant [8 x i8] c"strndup\00", align 1
; CHECK: @__instrumentor_allocation_call_info.39 = internal constant <{ ptr, i32, i32, i32, i8, i32 }> <{ ptr @__instrumentor_.str, i32 1, i32 -1, i32 -1, i8 2, i32 0 }>
;.
define void @test_c_allocators() {
; CHECK-LABEL: define void @test_c_allocators() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[P1:%.*]] = call ptr @malloc(i64 100)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @malloc, ptr @__instrumentor_.str, i64 0, ptr @__instrumentor_allocation_call_info, ptr null) #[[ATTR14:[0-9]+]]
; CHECK-NEXT:    [[P2:%.*]] = call ptr @calloc(i64 10, i64 20)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @calloc, ptr @__instrumentor_.str.1, i64 0, ptr @__instrumentor_allocation_call_info.2, ptr null) #[[ATTR14]]
; CHECK-NEXT:    [[P3:%.*]] = call ptr @realloc(ptr [[P1]], i64 200)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @realloc, ptr @__instrumentor_.str.3, i64 0, ptr @__instrumentor_allocation_call_info.4, ptr null) #[[ATTR14]]
; CHECK-NEXT:    [[P4:%.*]] = call ptr @aligned_alloc(i64 32, i64 256)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @aligned_alloc, ptr @__instrumentor_.str.5, i64 0, ptr @__instrumentor_allocation_call_info.6, ptr null) #[[ATTR14]]
; CHECK-NEXT:    ret void
;
entry:
  ; malloc(100)
  %p1 = call ptr @malloc(i64 100)

  ; calloc(10, 20) - should have both SizeLHS and SizeRHS
  %p2 = call ptr @calloc(i64 10, i64 20)

  ; realloc(p1, 200) - should have SizeLHS
  %p3 = call ptr @realloc(ptr %p1, i64 200)

  ; aligned_alloc(32, 256) - should have AlignmentArgNo
  %p4 = call ptr @aligned_alloc(i64 32, i64 256)

  ret void
}

define void @test_c_deallocators() {
; CHECK-LABEL: define void @test_c_deallocators() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[P:%.*]] = call ptr @malloc(i64 100)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @malloc, ptr @__instrumentor_.str, i64 0, ptr @__instrumentor_allocation_call_info, ptr null) #[[ATTR14]]
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @free, ptr @__instrumentor_.str.7, i64 0, ptr null, ptr @__instrumentor_deallocation_call_info) #[[ATTR14]]
; CHECK-NEXT:    call void @free(ptr [[P]])
; CHECK-NEXT:    ret void
;
entry:
  %p = call ptr @malloc(i64 100)
  ; free(p) - should have FreedOperandArgNo = 0
  call void @free(ptr %p)
  ret void
}

define void @test_cpp_new_allocators() {
; CHECK-LABEL: define void @test_cpp_new_allocators() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[P1:%.*]] = call ptr @_Znwm(i64 100)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_Znwm, ptr @__instrumentor_.str.8, i64 0, ptr @__instrumentor_allocation_call_info.9, ptr null) #[[ATTR14]]
; CHECK-NEXT:    [[NOTHROW:%.*]] = alloca i8, align 1
; CHECK-NEXT:    [[P2:%.*]] = call ptr @_ZnwmRKSt9nothrow_t(i64 100, ptr [[NOTHROW]])
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_ZnwmRKSt9nothrow_t, ptr @__instrumentor_.str.10, i64 0, ptr @__instrumentor_allocation_call_info.9, ptr null) #[[ATTR14]]
; CHECK-NEXT:    [[P3:%.*]] = call ptr @_ZnwmSt11align_val_t(i64 100, i64 32)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_ZnwmSt11align_val_t, ptr @__instrumentor_.str.11, i64 0, ptr @__instrumentor_allocation_call_info.12, ptr null) #[[ATTR14]]
; CHECK-NEXT:    [[P4:%.*]] = call ptr @_ZnwmSt11align_val_tRKSt9nothrow_t(i64 100, i64 32, ptr [[NOTHROW]])
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_ZnwmSt11align_val_tRKSt9nothrow_t, ptr @__instrumentor_.str.13, i64 0, ptr @__instrumentor_allocation_call_info.12, ptr null) #[[ATTR14]]
; CHECK-NEXT:    ret void
;
entry:
  ; operator new(100)
  %p1 = call ptr @_Znwm(i64 100)

  ; operator new(100, nothrow)
  %nothrow = alloca i8
  %p2 = call ptr @_ZnwmRKSt9nothrow_t(i64 100, ptr %nothrow)

  ; operator new(100, align_val_t(32))
  %p3 = call ptr @_ZnwmSt11align_val_t(i64 100, i64 32)

  ; operator new(100, align_val_t(32), nothrow)
  %p4 = call ptr @_ZnwmSt11align_val_tRKSt9nothrow_t(i64 100, i64 32, ptr %nothrow)

  ret void
}

define void @test_cpp_new_array_allocators() {
; CHECK-LABEL: define void @test_cpp_new_array_allocators() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[P1:%.*]] = call ptr @_Znam(i64 100)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_Znam, ptr @__instrumentor_.str.14, i64 0, ptr @__instrumentor_allocation_call_info.15, ptr null) #[[ATTR14]]
; CHECK-NEXT:    [[NOTHROW:%.*]] = alloca i8, align 1
; CHECK-NEXT:    [[P2:%.*]] = call ptr @_ZnamRKSt9nothrow_t(i64 100, ptr [[NOTHROW]])
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_ZnamRKSt9nothrow_t, ptr @__instrumentor_.str.16, i64 0, ptr @__instrumentor_allocation_call_info.15, ptr null) #[[ATTR14]]
; CHECK-NEXT:    [[P3:%.*]] = call ptr @_ZnamSt11align_val_t(i64 100, i64 32)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_ZnamSt11align_val_t, ptr @__instrumentor_.str.17, i64 0, ptr @__instrumentor_allocation_call_info.18, ptr null) #[[ATTR14]]
; CHECK-NEXT:    [[P4:%.*]] = call ptr @_ZnamSt11align_val_tRKSt9nothrow_t(i64 100, i64 32, ptr [[NOTHROW]])
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_ZnamSt11align_val_tRKSt9nothrow_t, ptr @__instrumentor_.str.19, i64 0, ptr @__instrumentor_allocation_call_info.18, ptr null) #[[ATTR14]]
; CHECK-NEXT:    ret void
;
entry:
  ; operator new[](100)
  %p1 = call ptr @_Znam(i64 100)

  ; operator new[](100, nothrow)
  %nothrow = alloca i8
  %p2 = call ptr @_ZnamRKSt9nothrow_t(i64 100, ptr %nothrow)

  ; operator new[](100, align_val_t(32))
  %p3 = call ptr @_ZnamSt11align_val_t(i64 100, i64 32)

  ; operator new[](100, align_val_t(32), nothrow)
  %p4 = call ptr @_ZnamSt11align_val_tRKSt9nothrow_t(i64 100, i64 32, ptr %nothrow)

  ret void
}

define void @test_cpp_delete_deallocators() {
; CHECK-LABEL: define void @test_cpp_delete_deallocators() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[P:%.*]] = call ptr @_Znwm(i64 100)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_Znwm, ptr @__instrumentor_.str.8, i64 0, ptr @__instrumentor_allocation_call_info.9, ptr null) #[[ATTR14]]
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @_ZdlPv, ptr @__instrumentor_.str.20, i64 0, ptr null, ptr @__instrumentor_deallocation_call_info.21) #[[ATTR14]]
; CHECK-NEXT:    call void @_ZdlPv(ptr [[P]])
; CHECK-NEXT:    [[P2:%.*]] = call ptr @_Znwm(i64 100)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_Znwm, ptr @__instrumentor_.str.8, i64 0, ptr @__instrumentor_allocation_call_info.9, ptr null) #[[ATTR14]]
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @_ZdlPvm, ptr @__instrumentor_.str.22, i64 0, ptr null, ptr @__instrumentor_deallocation_call_info.23) #[[ATTR14]]
; CHECK-NEXT:    call void @_ZdlPvm(ptr [[P2]], i64 100)
; CHECK-NEXT:    [[P3:%.*]] = call ptr @_ZnwmSt11align_val_t(i64 100, i64 32)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_ZnwmSt11align_val_t, ptr @__instrumentor_.str.11, i64 0, ptr @__instrumentor_allocation_call_info.12, ptr null) #[[ATTR14]]
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @_ZdlPvSt11align_val_t, ptr @__instrumentor_.str.24, i64 0, ptr null, ptr @__instrumentor_deallocation_call_info.25) #[[ATTR14]]
; CHECK-NEXT:    call void @_ZdlPvSt11align_val_t(ptr [[P3]], i64 32)
; CHECK-NEXT:    [[P4:%.*]] = call ptr @_ZnwmSt11align_val_t(i64 100, i64 32)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_ZnwmSt11align_val_t, ptr @__instrumentor_.str.11, i64 0, ptr @__instrumentor_allocation_call_info.12, ptr null) #[[ATTR14]]
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @_ZdlPvmSt11align_val_t, ptr @__instrumentor_.str.26, i64 0, ptr null, ptr @__instrumentor_deallocation_call_info.27) #[[ATTR14]]
; CHECK-NEXT:    call void @_ZdlPvmSt11align_val_t(ptr [[P4]], i64 100, i64 32)
; CHECK-NEXT:    ret void
;
entry:
  %p = call ptr @_Znwm(i64 100)
  ; operator delete(p)
  call void @_ZdlPv(ptr %p)

  %p2 = call ptr @_Znwm(i64 100)
  ; operator delete(p2, 100) - sized delete
  call void @_ZdlPvm(ptr %p2, i64 100)

  %p3 = call ptr @_ZnwmSt11align_val_t(i64 100, i64 32)
  ; operator delete(p3, align_val_t(32))
  call void @_ZdlPvSt11align_val_t(ptr %p3, i64 32)

  %p4 = call ptr @_ZnwmSt11align_val_t(i64 100, i64 32)
  ; operator delete(p4, 100, align_val_t(32)) - sized aligned delete
  call void @_ZdlPvmSt11align_val_t(ptr %p4, i64 100, i64 32)

  ret void
}

define void @test_cpp_delete_array_deallocators() {
; CHECK-LABEL: define void @test_cpp_delete_array_deallocators() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[P:%.*]] = call ptr @_Znam(i64 100)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_Znam, ptr @__instrumentor_.str.14, i64 0, ptr @__instrumentor_allocation_call_info.15, ptr null) #[[ATTR14]]
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @_ZdaPv, ptr @__instrumentor_.str.28, i64 0, ptr null, ptr @__instrumentor_deallocation_call_info.29) #[[ATTR14]]
; CHECK-NEXT:    call void @_ZdaPv(ptr [[P]])
; CHECK-NEXT:    [[P2:%.*]] = call ptr @_Znam(i64 100)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_Znam, ptr @__instrumentor_.str.14, i64 0, ptr @__instrumentor_allocation_call_info.15, ptr null) #[[ATTR14]]
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @_ZdaPvm, ptr @__instrumentor_.str.30, i64 0, ptr null, ptr @__instrumentor_deallocation_call_info.31) #[[ATTR14]]
; CHECK-NEXT:    call void @_ZdaPvm(ptr [[P2]], i64 100)
; CHECK-NEXT:    [[P3:%.*]] = call ptr @_ZnamSt11align_val_t(i64 100, i64 32)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_ZnamSt11align_val_t, ptr @__instrumentor_.str.17, i64 0, ptr @__instrumentor_allocation_call_info.18, ptr null) #[[ATTR14]]
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @_ZdaPvSt11align_val_t, ptr @__instrumentor_.str.32, i64 0, ptr null, ptr @__instrumentor_deallocation_call_info.33) #[[ATTR14]]
; CHECK-NEXT:    call void @_ZdaPvSt11align_val_t(ptr [[P3]], i64 32)
; CHECK-NEXT:    [[P4:%.*]] = call ptr @_ZnamSt11align_val_t(i64 100, i64 32)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @_ZnamSt11align_val_t, ptr @__instrumentor_.str.17, i64 0, ptr @__instrumentor_allocation_call_info.18, ptr null) #[[ATTR14]]
; CHECK-NEXT:    call void @__instrumentor_pre_call(ptr @_ZdaPvmSt11align_val_t, ptr @__instrumentor_.str.34, i64 0, ptr null, ptr @__instrumentor_deallocation_call_info.35) #[[ATTR14]]
; CHECK-NEXT:    call void @_ZdaPvmSt11align_val_t(ptr [[P4]], i64 100, i64 32)
; CHECK-NEXT:    ret void
;
entry:
  %p = call ptr @_Znam(i64 100)
  ; operator delete[](p)
  call void @_ZdaPv(ptr %p)

  %p2 = call ptr @_Znam(i64 100)
  ; operator delete[](p2, 100) - sized delete[]
  call void @_ZdaPvm(ptr %p2, i64 100)

  %p3 = call ptr @_ZnamSt11align_val_t(i64 100, i64 32)
  ; operator delete[](p3, align_val_t(32))
  call void @_ZdaPvSt11align_val_t(ptr %p3, i64 32)

  %p4 = call ptr @_ZnamSt11align_val_t(i64 100, i64 32)
  ; operator delete[](p4, 100, align_val_t(32)) - sized aligned delete[]
  call void @_ZdaPvmSt11align_val_t(ptr %p4, i64 100, i64 32)

  ret void
}

define void @test_string_duplicators() {
; CHECK-LABEL: define void @test_string_duplicators() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[STR:%.*]] = alloca [11 x i8], align 1
; CHECK-NEXT:    [[P1:%.*]] = call ptr @strdup(ptr [[STR]])
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @strdup, ptr @__instrumentor_.str.36, i64 0, ptr @__instrumentor_allocation_call_info.37, ptr null) #[[ATTR14]]
; CHECK-NEXT:    [[P2:%.*]] = call ptr @strndup(ptr [[STR]], i64 5)
; CHECK-NEXT:    call void @__instrumentor_post_call(ptr @strndup, ptr @__instrumentor_.str.38, i64 0, ptr @__instrumentor_allocation_call_info.39, ptr null) #[[ATTR14]]
; CHECK-NEXT:    ret void
;
entry:
  %str = alloca [11 x i8]
  ; strdup(str)
  %p1 = call ptr @strdup(ptr %str)

  ; strndup(str, 5) - should have SizeLHS = 1
  %p2 = call ptr @strndup(ptr %str, i64 5)

  ret void
}

; Attributes for C allocators
attributes #0 = { allockind("alloc,uninitialized") allocsize(0) "alloc-family"="malloc" }
attributes #1 = { allockind("alloc,zeroed") allocsize(0,1) "alloc-family"="malloc" }
attributes #2 = { allockind("realloc") allocsize(1) "alloc-family"="malloc" }
attributes #3 = { allockind("alloc,uninitialized,aligned") allocsize(1) "alloc-family"="malloc" }

; Attributes for C deallocator
attributes #4 = { allockind("free") "alloc-family"="malloc" }

; Attributes for C++ operator new
attributes #5 = { allockind("alloc,uninitialized") allocsize(0) "alloc-family"="_Znwm" }
attributes #6 = { allockind("alloc,uninitialized") allocsize(0) "alloc-family"="_Znwm" }
attributes #7 = { allockind("alloc,uninitialized,aligned") allocsize(0) "alloc-family"="_ZnwmSt11align_val_t" }
attributes #8 = { allockind("alloc,uninitialized,aligned") allocsize(0) "alloc-family"="_ZnwmSt11align_val_t" }

; Attributes for C++ operator new[]
attributes #9 = { allockind("alloc,uninitialized") allocsize(0) "alloc-family"="_Znam" }
attributes #10 = { allockind("alloc,uninitialized") allocsize(0) "alloc-family"="_Znam" }
attributes #11 = { allockind("alloc,uninitialized,aligned") allocsize(0) "alloc-family"="_ZnamSt11align_val_t" }
attributes #12 = { allockind("alloc,uninitialized,aligned") allocsize(0) "alloc-family"="_ZnamSt11align_val_t" }

; Attributes for C++ operator delete
attributes #13 = { allockind("free") "alloc-family"="_Znwm" }
attributes #14 = { allockind("free") "alloc-family"="_Znwm" }
attributes #15 = { allockind("free") "alloc-family"="_ZnwmSt11align_val_t" }
attributes #16 = { allockind("free") "alloc-family"="_ZnwmSt11align_val_t" }

; Attributes for C++ operator delete[]
attributes #17 = { allockind("free") "alloc-family"="_Znam" }
attributes #18 = { allockind("free") "alloc-family"="_Znam" }
attributes #19 = { allockind("free") "alloc-family"="_ZnamSt11align_val_t" }
attributes #20 = { allockind("free") "alloc-family"="_ZnamSt11align_val_t" }

; Attributes for string duplicators
attributes #21 = { allockind("alloc,uninitialized") "alloc-family"="malloc" }
attributes #22 = { allockind("alloc,uninitialized") "alloc-family"="malloc" }
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { mustprogress nofree nounwind willreturn allockind("alloc,uninitialized") allocsize(0) memory(inaccessiblemem: readwrite, errnomem: write) "alloc-family"="malloc" }
; CHECK: attributes #[[ATTR1:[0-9]+]] = { mustprogress nofree nounwind willreturn allockind("alloc,zeroed") allocsize(0,1) memory(inaccessiblemem: readwrite, errnomem: write) "alloc-family"="malloc" }
; CHECK: attributes #[[ATTR2:[0-9]+]] = { mustprogress nounwind willreturn allockind("realloc") allocsize(1) memory(argmem: readwrite, inaccessiblemem: readwrite, errnomem: write) "alloc-family"="malloc" }
; CHECK: attributes #[[ATTR3:[0-9]+]] = { mustprogress nofree nounwind willreturn allockind("alloc,uninitialized,aligned") allocsize(1) memory(inaccessiblemem: readwrite, errnomem: write) "alloc-family"="malloc" }
; CHECK: attributes #[[ATTR4:[0-9]+]] = { mustprogress nounwind willreturn allockind("free") memory(argmem: readwrite, inaccessiblemem: readwrite) "alloc-family"="malloc" }
; CHECK: attributes #[[ATTR5:[0-9]+]] = { nofree allockind("alloc,uninitialized") allocsize(0) "alloc-family"="_Znwm" }
; CHECK: attributes #[[ATTR6:[0-9]+]] = { nofree allockind("alloc,uninitialized,aligned") allocsize(0) "alloc-family"="_ZnwmSt11align_val_t" }
; CHECK: attributes #[[ATTR7:[0-9]+]] = { nofree allockind("alloc,uninitialized") allocsize(0) "alloc-family"="_Znam" }
; CHECK: attributes #[[ATTR8:[0-9]+]] = { nofree allockind("alloc,uninitialized,aligned") allocsize(0) "alloc-family"="_ZnamSt11align_val_t" }
; CHECK: attributes #[[ATTR9:[0-9]+]] = { allockind("free") "alloc-family"="_Znwm" }
; CHECK: attributes #[[ATTR10:[0-9]+]] = { allockind("free") "alloc-family"="_ZnwmSt11align_val_t" }
; CHECK: attributes #[[ATTR11:[0-9]+]] = { allockind("free") "alloc-family"="_Znam" }
; CHECK: attributes #[[ATTR12:[0-9]+]] = { allockind("free") "alloc-family"="_ZnamSt11align_val_t" }
; CHECK: attributes #[[ATTR13:[0-9]+]] = { mustprogress nofree nounwind willreturn allockind("alloc,uninitialized") memory(argmem: readwrite, inaccessiblemem: readwrite, errnomem: write) "alloc-family"="malloc" }
; CHECK: attributes #[[ATTR14]] = { willreturn }
;.
