; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6

; RUN: opt < %s -passes=instrumentor -S | FileCheck %s

define i128 @test_ext(i32 %p1) {
; CHECK-LABEL: define i128 @test_ext(
; CHECK-SAME: i32 [[P1:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = alloca i128, align 8
; CHECK-NEXT:    [[TMP2:%.*]] = alloca i64, align 8
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP1]], ptr @__instrumentor_value_pack, i64 16, i1 false)
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw <{ i32, i32, [4 x i8], i32 }>, ptr [[TMP1]], i32 0, i32 3
; CHECK-NEXT:    store i32 [[P1]], ptr [[TMP3]], align 4
; CHECK-NEXT:    call void @__instrumentor_pre_function(ptr @test_ext, ptr @__instrumentor_.str.2, i32 1, ptr [[TMP1]], i8 0, i32 4) #[[ATTR1:[0-9]+]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = zext i32 [[TMP5]] to i64
; CHECK-NEXT:    call void @__instrumentor_pre_cast(i64 [[TMP6]], i32 12, i32 4, i32 12, i32 16, i32 40, i32 3) #[[ATTR1]]
; CHECK-NEXT:    [[I1:%.*]] = zext i32 [[TMP5]] to i128
; CHECK-NEXT:    store i64 [[TMP6]], ptr [[TMP2]], align 4
; CHECK-NEXT:    store i128 [[I1]], ptr [[TMP1]], align 4
; CHECK-NEXT:    call void @__instrumentor_post_cast_ind(ptr [[TMP2]], i32 8, i32 12, i32 4, ptr [[TMP1]], i32 16, i32 12, i32 16, i32 40, i32 -3) #[[ATTR1]]
; CHECK-NEXT:    [[TMP7:%.*]] = load i128, ptr [[TMP1]], align 4
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP1]], ptr @__instrumentor_value_pack, i64 16, i1 false)
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw <{ i32, i32, [4 x i8], i32 }>, ptr [[TMP1]], i32 0, i32 3
; CHECK-NEXT:    store i32 [[P1]], ptr [[TMP8]], align 4
; CHECK-NEXT:    call void @__instrumentor_post_function(ptr @test_ext, ptr @__instrumentor_.str.2, i32 1, ptr [[TMP1]], i8 0, i32 -5) #[[ATTR1]]
; CHECK-NEXT:    ret i128 [[TMP7]]
;
  %i1 = zext i32 %p1 to i128
  ret i128 %i1
}
