; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instrumentor -instrumentor-read-config-files=%S/function_regex.json -S | FileCheck %s

define i32 @foo() {
; CHECK-LABEL: @foo(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca i32, align 4
; CHECK-NEXT:    call void @__instrumentor_pre_store() #[[ATTR0:[0-9]+]]
; CHECK-NEXT:    store i32 0, ptr [[TMP0]], align 4
; CHECK-NEXT:    call void @__instrumentor_post_store(i32 -1) #[[ATTR0]]
; CHECK-NEXT:    call void @__instrumentor_pre_load(i32 2) #[[ATTR0]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[TMP0]], align 4
; CHECK-NEXT:    call void @__instrumentor_post_load(i32 -2) #[[ATTR0]]
; CHECK-NEXT:    ret i32 [[TMP1]]
;
entry:
  %0 = alloca i32, align 4
  store i32 0, ptr %0, align 4
  %2 = load i32, ptr %0, align 4
  ret i32 %2
}

define i32 @bar() {
; CHECK-LABEL: @bar(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 0, ptr [[TMP0]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[TMP0]], align 4
; CHECK-NEXT:    ret i32 [[TMP1]]
;
entry:
  %0 = alloca i32, align 4
  store i32 0, ptr %0, align 4
  %2 = load i32, ptr %0, align 4
  ret i32 %2
}

define i32 @baz() {
; CHECK-LABEL: @baz(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca i32, align 4
; CHECK-NEXT:    call void @__instrumentor_pre_store() #[[ATTR0]]
; CHECK-NEXT:    store i32 0, ptr [[TMP0]], align 4
; CHECK-NEXT:    call void @__instrumentor_post_store(i32 -3) #[[ATTR0]]
; CHECK-NEXT:    call void @__instrumentor_pre_load(i32 4) #[[ATTR0]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[TMP0]], align 4
; CHECK-NEXT:    call void @__instrumentor_post_load(i32 -4) #[[ATTR0]]
; CHECK-NEXT:    ret i32 [[TMP1]]
;
entry:
  %0 = alloca i32, align 4
  store i32 0, ptr %0, align 4
  %2 = load i32, ptr %0, align 4
  ret i32 %2
}
