; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instrumentor -instrumentor-read-config-files=%S/custom_config.json -S | FileCheck %s

target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

define i32 @bar(i1 %c) {
; CHECK-LABEL: define i32 @bar(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[B:%.*]] = alloca i32, i32 5, align 4
; CHECK-NEXT:    [[S:%.*]] = select i1 [[C]], ptr [[A]], ptr [[B]]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[S]], align 4
; CHECK-NEXT:    call void @__custom_post_load() #[[ATTR0:[0-9]+]]
; CHECK-NEXT:    store i32 [[V]], ptr [[S]], align 4
; CHECK-NEXT:    call void @__custom_post_store() #[[ATTR0]]
; CHECK-NEXT:    ret i32 [[V]]
;
entry:
  %a = alloca i32
  %b = alloca i32, i32 5
  %s = select i1 %c, ptr %a, ptr %b
  %v = load i32, ptr %s
  store i32 %v, ptr %s
  ret i32 %v
}
