; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instrumentor -instrumentor-read-config-files=%S/test_filter_config.json -S | FileCheck %s

; Test file to demonstrate the filter functionality
; This file contains loads with different atomicity and volatile properties

define i32 @test_loads(ptr %ptr) {
; CHECK-LABEL: @test_loads(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr [[PTR:%.*]], align 4
; CHECK-NEXT:    [[V2:%.*]] = load atomic i32, ptr [[PTR]] acquire, align 4
; CHECK-NEXT:    [[TMP0:%.*]] = zext i32 [[V2]] to i64
; CHECK-NEXT:    call void @__test_filter_post_load(ptr [[PTR]], i64 [[TMP0]], i32 4, i32 -2) #[[ATTR0:[0-9]+]]
; CHECK-NEXT:    [[V3:%.*]] = load atomic i32, ptr [[PTR]] seq_cst, align 4
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[V3]] to i64
; CHECK-NEXT:    call void @__test_filter_post_load(ptr [[PTR]], i64 [[TMP1]], i32 7, i32 -3) #[[ATTR0]]
; CHECK-NEXT:    [[V4:%.*]] = load volatile i32, ptr [[PTR]], align 4
; CHECK-NEXT:    [[SUM1:%.*]] = add i32 [[V1]], [[V2]]
; CHECK-NEXT:    [[SUM2:%.*]] = add i32 [[SUM1]], [[V3]]
; CHECK-NEXT:    [[SUM3:%.*]] = add i32 [[SUM2]], [[V4]]
; CHECK-NEXT:    ret i32 [[SUM3]]
;
entry:
  ; Regular load (sync_scope_id=0, atomicity_ordering=0)
  %v1 = load i32, ptr %ptr, align 4

  ; Atomic load with acquire ordering (atomicity_ordering=4)
  %v2 = load atomic i32, ptr %ptr acquire, align 4

  ; Atomic load with seq_cst ordering (atomicity_ordering=5)
  %v3 = load atomic i32, ptr %ptr seq_cst, align 4

  ; Volatile load
  %v4 = load volatile i32, ptr %ptr, align 4

  %sum1 = add i32 %v1, %v2
  %sum2 = add i32 %sum1, %v3
  %sum3 = add i32 %sum2, %v4
  ret i32 %sum3
}

define i32 @test_stores(ptr %ptr, i32 %val) {
; CHECK-LABEL: @test_stores(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    store i32 [[VAL:%.*]], ptr [[PTR:%.*]], align 4
; CHECK-NEXT:    store atomic i32 [[VAL]], ptr [[PTR]] release, align 4
; CHECK-NEXT:    [[TMP0:%.*]] = zext i32 [[VAL]] to i64
; CHECK-NEXT:    call void @__test_filter_post_store(ptr [[PTR]], i64 [[TMP0]], i32 5, i8 0, i32 -6) #[[ATTR0]]
; CHECK-NEXT:    store atomic i32 [[VAL]], ptr [[PTR]] seq_cst, align 4
; CHECK-NEXT:    store volatile i32 [[VAL]], ptr [[PTR]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[VAL]] to i64
; CHECK-NEXT:    call void @__test_filter_post_store(ptr [[PTR]], i64 [[TMP1]], i32 0, i8 1, i32 -8) #[[ATTR0]]
; CHECK-NEXT:    ret i32 0
;
entry:
  ; Regular store (sync_scope_id=0, atomicity_ordering=0)
  store i32 %val, ptr %ptr, align 4

  ; Atomic store with release ordering (atomicity_ordering=5)
  store atomic i32 %val, ptr %ptr release, align 4

  ; Atomic store with seq_cst ordering (atomicity_ordering!=5)
  store atomic i32 %val, ptr %ptr seq_cst, align 4

  ; Volatile store
  store volatile i32 %val, ptr %ptr, align 4

  ret i32 0
}
