; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=amdgcn-amd-amdhsa -S -passes='require<libcall-lowering-info>,atomic-expand' -mcpu=gfx942 %s | FileCheck -check-prefixes=GFX942 %s
; RUN: opt -mtriple=amdgcn-amd-amdhsa -S -passes='require<libcall-lowering-info>,atomic-expand' -mcpu=gfx900 %s | FileCheck -check-prefixes=GFX900 %s

; gfx942 has ds_pk_add_f16/bf16, so atomicrmw fadd <2 x half> is natively
; supported as a whole-value operation. The elementwise modifier should be
; dropped and the instruction preserved.
;
; gfx900 lacks ds_pk_add, so the elementwise atomicrmw must be scalarized
; into per-lane scalar atomicrmw instructions.

define <2 x half> @elementwise_fadd_v2f16_lds(ptr addrspace(3) %ptr, <2 x half> %val) {
; GFX942-LABEL: define <2 x half> @elementwise_fadd_v2f16_lds(
; GFX942-SAME: ptr addrspace(3) [[PTR:%.*]], <2 x half> [[VAL:%.*]]) #[[ATTR0:[0-9]+]] {
; GFX942-NEXT:    [[RES:%.*]] = atomicrmw fadd ptr addrspace(3) [[PTR]], <2 x half> [[VAL]] monotonic, align 4
; GFX942-NEXT:    ret <2 x half> [[RES]]
;
; GFX900-LABEL: define <2 x half> @elementwise_fadd_v2f16_lds(
; GFX900-SAME: ptr addrspace(3) [[PTR:%.*]], <2 x half> [[VAL:%.*]]) #[[ATTR0:[0-9]+]] {
; GFX900-NEXT:    [[LANE_VAL:%.*]] = extractelement <2 x half> [[VAL]], i32 0
; GFX900-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(3) [[PTR]], align 4
; GFX900-NEXT:    br label %[[ATOMICRMW_START:.*]]
; GFX900:       [[ATOMICRMW_START]]:
; GFX900-NEXT:    [[LOADED:%.*]] = phi i32 [ [[TMP1]], [[TMP0:%.*]] ], [ [[NEWLOADED:%.*]], %[[ATOMICRMW_START]] ]
; GFX900-NEXT:    [[EXTRACTED:%.*]] = trunc i32 [[LOADED]] to i16
; GFX900-NEXT:    [[TMP2:%.*]] = bitcast i16 [[EXTRACTED]] to half
; GFX900-NEXT:    [[NEW:%.*]] = fadd half [[TMP2]], [[LANE_VAL]]
; GFX900-NEXT:    [[TMP3:%.*]] = bitcast half [[NEW]] to i16
; GFX900-NEXT:    [[EXTENDED:%.*]] = zext i16 [[TMP3]] to i32
; GFX900-NEXT:    [[UNMASKED:%.*]] = and i32 [[LOADED]], -65536
; GFX900-NEXT:    [[INSERTED:%.*]] = or i32 [[UNMASKED]], [[EXTENDED]]
; GFX900-NEXT:    [[TMP4:%.*]] = cmpxchg ptr addrspace(3) [[PTR]], i32 [[LOADED]], i32 [[INSERTED]] monotonic monotonic, align 4
; GFX900-NEXT:    [[SUCCESS:%.*]] = extractvalue { i32, i1 } [[TMP4]], 1
; GFX900-NEXT:    [[NEWLOADED]] = extractvalue { i32, i1 } [[TMP4]], 0
; GFX900-NEXT:    br i1 [[SUCCESS]], label %[[ATOMICRMW_END:.*]], label %[[ATOMICRMW_START]]
; GFX900:       [[ATOMICRMW_END]]:
; GFX900-NEXT:    [[EXTRACTED1:%.*]] = trunc i32 [[NEWLOADED]] to i16
; GFX900-NEXT:    [[TMP5:%.*]] = bitcast i16 [[EXTRACTED1]] to half
; GFX900-NEXT:    [[LANE_OLD:%.*]] = insertelement <2 x half> zeroinitializer, half [[TMP5]], i32 0
; GFX900-NEXT:    [[LANE_PTR:%.*]] = getelementptr inbounds <2 x half>, ptr addrspace(3) [[PTR]], i32 0, i32 1
; GFX900-NEXT:    [[LANE_VAL2:%.*]] = extractelement <2 x half> [[VAL]], i32 1
; GFX900-NEXT:    [[ALIGNEDADDR:%.*]] = call ptr addrspace(3) @llvm.ptrmask.p3.i32(ptr addrspace(3) [[LANE_PTR]], i32 -4)
; GFX900-NEXT:    [[TMP6:%.*]] = ptrtoint ptr addrspace(3) [[LANE_PTR]] to i32
; GFX900-NEXT:    [[PTRLSB:%.*]] = and i32 [[TMP6]], 3
; GFX900-NEXT:    [[TMP7:%.*]] = shl i32 [[PTRLSB]], 3
; GFX900-NEXT:    [[MASK:%.*]] = shl i32 65535, [[TMP7]]
; GFX900-NEXT:    [[INV_MASK:%.*]] = xor i32 [[MASK]], -1
; GFX900-NEXT:    [[TMP8:%.*]] = load i32, ptr addrspace(3) [[ALIGNEDADDR]], align 4
; GFX900-NEXT:    br label %[[ATOMICRMW_START5:.*]]
; GFX900:       [[ATOMICRMW_START5]]:
; GFX900-NEXT:    [[LOADED6:%.*]] = phi i32 [ [[TMP8]], %[[ATOMICRMW_END]] ], [ [[NEWLOADED14:%.*]], %[[ATOMICRMW_START5]] ]
; GFX900-NEXT:    [[SHIFTED:%.*]] = lshr i32 [[LOADED6]], [[TMP7]]
; GFX900-NEXT:    [[EXTRACTED7:%.*]] = trunc i32 [[SHIFTED]] to i16
; GFX900-NEXT:    [[TMP9:%.*]] = bitcast i16 [[EXTRACTED7]] to half
; GFX900-NEXT:    [[NEW8:%.*]] = fadd half [[TMP9]], [[LANE_VAL2]]
; GFX900-NEXT:    [[TMP10:%.*]] = bitcast half [[NEW8]] to i16
; GFX900-NEXT:    [[EXTENDED9:%.*]] = zext i16 [[TMP10]] to i32
; GFX900-NEXT:    [[SHIFTED10:%.*]] = shl nuw i32 [[EXTENDED9]], [[TMP7]]
; GFX900-NEXT:    [[UNMASKED11:%.*]] = and i32 [[LOADED6]], [[INV_MASK]]
; GFX900-NEXT:    [[INSERTED12:%.*]] = or i32 [[UNMASKED11]], [[SHIFTED10]]
; GFX900-NEXT:    [[TMP11:%.*]] = cmpxchg ptr addrspace(3) [[ALIGNEDADDR]], i32 [[LOADED6]], i32 [[INSERTED12]] monotonic monotonic, align 4
; GFX900-NEXT:    [[SUCCESS13:%.*]] = extractvalue { i32, i1 } [[TMP11]], 1
; GFX900-NEXT:    [[NEWLOADED14]] = extractvalue { i32, i1 } [[TMP11]], 0
; GFX900-NEXT:    br i1 [[SUCCESS13]], label %[[ATOMICRMW_END4:.*]], label %[[ATOMICRMW_START5]]
; GFX900:       [[ATOMICRMW_END4]]:
; GFX900-NEXT:    [[SHIFTED15:%.*]] = lshr i32 [[NEWLOADED14]], [[TMP7]]
; GFX900-NEXT:    [[EXTRACTED16:%.*]] = trunc i32 [[SHIFTED15]] to i16
; GFX900-NEXT:    [[TMP12:%.*]] = bitcast i16 [[EXTRACTED16]] to half
; GFX900-NEXT:    [[LANE_OLD3:%.*]] = insertelement <2 x half> [[LANE_OLD]], half [[TMP12]], i32 1
; GFX900-NEXT:    ret <2 x half> [[LANE_OLD3]]
;
  %res = atomicrmw elementwise fadd ptr addrspace(3) %ptr, <2 x half> %val monotonic, align 4
  ret <2 x half> %res
}

define <2 x bfloat> @elementwise_fadd_v2bf16_lds(ptr addrspace(3) %ptr, <2 x bfloat> %val) {
; GFX942-LABEL: define <2 x bfloat> @elementwise_fadd_v2bf16_lds(
; GFX942-SAME: ptr addrspace(3) [[PTR:%.*]], <2 x bfloat> [[VAL:%.*]]) #[[ATTR0]] {
; GFX942-NEXT:    [[RES:%.*]] = atomicrmw fadd ptr addrspace(3) [[PTR]], <2 x bfloat> [[VAL]] monotonic, align 4
; GFX942-NEXT:    ret <2 x bfloat> [[RES]]
;
; GFX900-LABEL: define <2 x bfloat> @elementwise_fadd_v2bf16_lds(
; GFX900-SAME: ptr addrspace(3) [[PTR:%.*]], <2 x bfloat> [[VAL:%.*]]) #[[ATTR0]] {
; GFX900-NEXT:    [[LANE_VAL:%.*]] = extractelement <2 x bfloat> [[VAL]], i32 0
; GFX900-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(3) [[PTR]], align 4
; GFX900-NEXT:    br label %[[ATOMICRMW_START:.*]]
; GFX900:       [[ATOMICRMW_START]]:
; GFX900-NEXT:    [[LOADED:%.*]] = phi i32 [ [[TMP1]], [[TMP0:%.*]] ], [ [[NEWLOADED:%.*]], %[[ATOMICRMW_START]] ]
; GFX900-NEXT:    [[EXTRACTED:%.*]] = trunc i32 [[LOADED]] to i16
; GFX900-NEXT:    [[TMP2:%.*]] = bitcast i16 [[EXTRACTED]] to bfloat
; GFX900-NEXT:    [[NEW:%.*]] = fadd bfloat [[TMP2]], [[LANE_VAL]]
; GFX900-NEXT:    [[TMP3:%.*]] = bitcast bfloat [[NEW]] to i16
; GFX900-NEXT:    [[EXTENDED:%.*]] = zext i16 [[TMP3]] to i32
; GFX900-NEXT:    [[UNMASKED:%.*]] = and i32 [[LOADED]], -65536
; GFX900-NEXT:    [[INSERTED:%.*]] = or i32 [[UNMASKED]], [[EXTENDED]]
; GFX900-NEXT:    [[TMP4:%.*]] = cmpxchg ptr addrspace(3) [[PTR]], i32 [[LOADED]], i32 [[INSERTED]] monotonic monotonic, align 4
; GFX900-NEXT:    [[SUCCESS:%.*]] = extractvalue { i32, i1 } [[TMP4]], 1
; GFX900-NEXT:    [[NEWLOADED]] = extractvalue { i32, i1 } [[TMP4]], 0
; GFX900-NEXT:    br i1 [[SUCCESS]], label %[[ATOMICRMW_END:.*]], label %[[ATOMICRMW_START]]
; GFX900:       [[ATOMICRMW_END]]:
; GFX900-NEXT:    [[EXTRACTED1:%.*]] = trunc i32 [[NEWLOADED]] to i16
; GFX900-NEXT:    [[TMP5:%.*]] = bitcast i16 [[EXTRACTED1]] to bfloat
; GFX900-NEXT:    [[LANE_OLD:%.*]] = insertelement <2 x bfloat> zeroinitializer, bfloat [[TMP5]], i32 0
; GFX900-NEXT:    [[LANE_PTR:%.*]] = getelementptr inbounds <2 x bfloat>, ptr addrspace(3) [[PTR]], i32 0, i32 1
; GFX900-NEXT:    [[LANE_VAL2:%.*]] = extractelement <2 x bfloat> [[VAL]], i32 1
; GFX900-NEXT:    [[ALIGNEDADDR:%.*]] = call ptr addrspace(3) @llvm.ptrmask.p3.i32(ptr addrspace(3) [[LANE_PTR]], i32 -4)
; GFX900-NEXT:    [[TMP6:%.*]] = ptrtoint ptr addrspace(3) [[LANE_PTR]] to i32
; GFX900-NEXT:    [[PTRLSB:%.*]] = and i32 [[TMP6]], 3
; GFX900-NEXT:    [[TMP7:%.*]] = shl i32 [[PTRLSB]], 3
; GFX900-NEXT:    [[MASK:%.*]] = shl i32 65535, [[TMP7]]
; GFX900-NEXT:    [[INV_MASK:%.*]] = xor i32 [[MASK]], -1
; GFX900-NEXT:    [[TMP8:%.*]] = load i32, ptr addrspace(3) [[ALIGNEDADDR]], align 4
; GFX900-NEXT:    br label %[[ATOMICRMW_START5:.*]]
; GFX900:       [[ATOMICRMW_START5]]:
; GFX900-NEXT:    [[LOADED6:%.*]] = phi i32 [ [[TMP8]], %[[ATOMICRMW_END]] ], [ [[NEWLOADED14:%.*]], %[[ATOMICRMW_START5]] ]
; GFX900-NEXT:    [[SHIFTED:%.*]] = lshr i32 [[LOADED6]], [[TMP7]]
; GFX900-NEXT:    [[EXTRACTED7:%.*]] = trunc i32 [[SHIFTED]] to i16
; GFX900-NEXT:    [[TMP9:%.*]] = bitcast i16 [[EXTRACTED7]] to bfloat
; GFX900-NEXT:    [[NEW8:%.*]] = fadd bfloat [[TMP9]], [[LANE_VAL2]]
; GFX900-NEXT:    [[TMP10:%.*]] = bitcast bfloat [[NEW8]] to i16
; GFX900-NEXT:    [[EXTENDED9:%.*]] = zext i16 [[TMP10]] to i32
; GFX900-NEXT:    [[SHIFTED10:%.*]] = shl nuw i32 [[EXTENDED9]], [[TMP7]]
; GFX900-NEXT:    [[UNMASKED11:%.*]] = and i32 [[LOADED6]], [[INV_MASK]]
; GFX900-NEXT:    [[INSERTED12:%.*]] = or i32 [[UNMASKED11]], [[SHIFTED10]]
; GFX900-NEXT:    [[TMP11:%.*]] = cmpxchg ptr addrspace(3) [[ALIGNEDADDR]], i32 [[LOADED6]], i32 [[INSERTED12]] monotonic monotonic, align 4
; GFX900-NEXT:    [[SUCCESS13:%.*]] = extractvalue { i32, i1 } [[TMP11]], 1
; GFX900-NEXT:    [[NEWLOADED14]] = extractvalue { i32, i1 } [[TMP11]], 0
; GFX900-NEXT:    br i1 [[SUCCESS13]], label %[[ATOMICRMW_END4:.*]], label %[[ATOMICRMW_START5]]
; GFX900:       [[ATOMICRMW_END4]]:
; GFX900-NEXT:    [[SHIFTED15:%.*]] = lshr i32 [[NEWLOADED14]], [[TMP7]]
; GFX900-NEXT:    [[EXTRACTED16:%.*]] = trunc i32 [[SHIFTED15]] to i16
; GFX900-NEXT:    [[TMP12:%.*]] = bitcast i16 [[EXTRACTED16]] to bfloat
; GFX900-NEXT:    [[LANE_OLD3:%.*]] = insertelement <2 x bfloat> [[LANE_OLD]], bfloat [[TMP12]], i32 1
; GFX900-NEXT:    ret <2 x bfloat> [[LANE_OLD3]]
;
  %res = atomicrmw elementwise fadd ptr addrspace(3) %ptr, <2 x bfloat> %val monotonic, align 4
  ret <2 x bfloat> %res
}
