; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=x86_64-- -mcpu=x86-64    -passes=vector-combine -S %s | FileCheck %s --check-prefix=V1
; RUN: opt -mtriple=x86_64-- -mcpu=x86-64-v2 -passes=vector-combine -S %s | FileCheck %s --check-prefix=V2
; RUN: opt -mtriple=x86_64-- -mcpu=x86-64-v3 -passes=vector-combine -S %s | FileCheck %s --check-prefix=V3
; RUN: opt -mtriple=x86_64-- -mcpu=x86-64-v4 -passes=vector-combine -S %s | FileCheck %s --check-prefix=V4

declare i8 @llvm.vector.reduce.or.v16i8(<16 x i8>)
declare i8 @llvm.vector.reduce.umax.v16i8(<16 x i8>)

define i1 @or_nonzero(<16 x i8> %x) {
; V1-LABEL: define i1 @or_nonzero(
; V1-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1:[0-9]+]] {
; V1-NEXT:    [[TMP1:%.*]] = icmp ne <16 x i8> [[X]], zeroinitializer
; V1-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.or.v16i1(<16 x i1> [[TMP1]])
; V1-NEXT:    ret i1 [[CMP]]
;
; V2-LABEL: define i1 @or_nonzero(
; V2-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1:[0-9]+]] {
; V2-NEXT:    [[TMP1:%.*]] = icmp ne <16 x i8> [[X]], zeroinitializer
; V2-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.or.v16i1(<16 x i1> [[TMP1]])
; V2-NEXT:    ret i1 [[CMP]]
;
; V3-LABEL: define i1 @or_nonzero(
; V3-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1:[0-9]+]] {
; V3-NEXT:    [[TMP1:%.*]] = icmp ne <16 x i8> [[X]], zeroinitializer
; V3-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.or.v16i1(<16 x i1> [[TMP1]])
; V3-NEXT:    ret i1 [[CMP]]
;
; V4-LABEL: define i1 @or_nonzero(
; V4-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1:[0-9]+]] {
; V4-NEXT:    [[TMP1:%.*]] = icmp ne <16 x i8> [[X]], zeroinitializer
; V4-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.or.v16i1(<16 x i1> [[TMP1]])
; V4-NEXT:    ret i1 [[CMP]]
;
  %reduction = call i8 @llvm.vector.reduce.or.v16i8(<16 x i8> %x)
  %cmp = icmp ne i8 %reduction, 0
  ret i1 %cmp
}

define i1 @or_zero(<16 x i8> %x) {
; V1-LABEL: define i1 @or_zero(
; V1-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1]] {
; V1-NEXT:    [[TMP1:%.*]] = icmp eq <16 x i8> [[X]], zeroinitializer
; V1-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.and.v16i1(<16 x i1> [[TMP1]])
; V1-NEXT:    ret i1 [[CMP]]
;
; V2-LABEL: define i1 @or_zero(
; V2-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1]] {
; V2-NEXT:    [[TMP1:%.*]] = icmp eq <16 x i8> [[X]], zeroinitializer
; V2-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.and.v16i1(<16 x i1> [[TMP1]])
; V2-NEXT:    ret i1 [[CMP]]
;
; V3-LABEL: define i1 @or_zero(
; V3-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1]] {
; V3-NEXT:    [[TMP1:%.*]] = icmp eq <16 x i8> [[X]], zeroinitializer
; V3-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.and.v16i1(<16 x i1> [[TMP1]])
; V3-NEXT:    ret i1 [[CMP]]
;
; V4-LABEL: define i1 @or_zero(
; V4-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1]] {
; V4-NEXT:    [[TMP1:%.*]] = icmp eq <16 x i8> [[X]], zeroinitializer
; V4-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.and.v16i1(<16 x i1> [[TMP1]])
; V4-NEXT:    ret i1 [[CMP]]
;
  %reduction = call i8 @llvm.vector.reduce.or.v16i8(<16 x i8> %x)
  %cmp = icmp eq i8 %reduction, 0
  ret i1 %cmp
}

define i1 @umax_nonzero(<16 x i8> %x) {
; V1-LABEL: define i1 @umax_nonzero(
; V1-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1]] {
; V1-NEXT:    [[TMP1:%.*]] = icmp ne <16 x i8> [[X]], zeroinitializer
; V1-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.or.v16i1(<16 x i1> [[TMP1]])
; V1-NEXT:    ret i1 [[CMP]]
;
; V2-LABEL: define i1 @umax_nonzero(
; V2-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1]] {
; V2-NEXT:    [[TMP1:%.*]] = icmp ne <16 x i8> [[X]], zeroinitializer
; V2-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.or.v16i1(<16 x i1> [[TMP1]])
; V2-NEXT:    ret i1 [[CMP]]
;
; V3-LABEL: define i1 @umax_nonzero(
; V3-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1]] {
; V3-NEXT:    [[TMP1:%.*]] = icmp ne <16 x i8> [[X]], zeroinitializer
; V3-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.or.v16i1(<16 x i1> [[TMP1]])
; V3-NEXT:    ret i1 [[CMP]]
;
; V4-LABEL: define i1 @umax_nonzero(
; V4-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1]] {
; V4-NEXT:    [[REDUCTION:%.*]] = call i8 @llvm.vector.reduce.umax.v16i8(<16 x i8> [[X]])
; V4-NEXT:    [[CMP:%.*]] = icmp ne i8 [[REDUCTION]], 0
; V4-NEXT:    ret i1 [[CMP]]
;
  %reduction = call i8 @llvm.vector.reduce.umax.v16i8(<16 x i8> %x)
  %cmp = icmp ne i8 %reduction, 0
  ret i1 %cmp
}

define i1 @umax_zero_commuted(<16 x i8> %x) {
; V1-LABEL: define i1 @umax_zero_commuted(
; V1-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1]] {
; V1-NEXT:    [[TMP1:%.*]] = icmp eq <16 x i8> [[X]], zeroinitializer
; V1-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.and.v16i1(<16 x i1> [[TMP1]])
; V1-NEXT:    ret i1 [[CMP]]
;
; V2-LABEL: define i1 @umax_zero_commuted(
; V2-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1]] {
; V2-NEXT:    [[TMP1:%.*]] = icmp eq <16 x i8> [[X]], zeroinitializer
; V2-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.and.v16i1(<16 x i1> [[TMP1]])
; V2-NEXT:    ret i1 [[CMP]]
;
; V3-LABEL: define i1 @umax_zero_commuted(
; V3-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1]] {
; V3-NEXT:    [[TMP1:%.*]] = icmp eq <16 x i8> [[X]], zeroinitializer
; V3-NEXT:    [[CMP:%.*]] = call i1 @llvm.vector.reduce.and.v16i1(<16 x i1> [[TMP1]])
; V3-NEXT:    ret i1 [[CMP]]
;
; V4-LABEL: define i1 @umax_zero_commuted(
; V4-SAME: <16 x i8> [[X:%.*]]) #[[ATTR1]] {
; V4-NEXT:    [[REDUCTION:%.*]] = call i8 @llvm.vector.reduce.umax.v16i8(<16 x i8> [[X]])
; V4-NEXT:    [[CMP:%.*]] = icmp eq i8 0, [[REDUCTION]]
; V4-NEXT:    ret i1 [[CMP]]
;
  %reduction = call i8 @llvm.vector.reduce.umax.v16i8(<16 x i8> %x)
  %cmp = icmp eq i8 0, %reduction
  ret i1 %cmp
}

define i1 @or_nonzero_multiuse(<16 x i8> %x, ptr %out) {
; V1-LABEL: define i1 @or_nonzero_multiuse(
; V1-SAME: <16 x i8> [[X:%.*]], ptr [[OUT:%.*]]) #[[ATTR1]] {
; V1-NEXT:    [[REDUCTION:%.*]] = call i8 @llvm.vector.reduce.or.v16i8(<16 x i8> [[X]])
; V1-NEXT:    store i8 [[REDUCTION]], ptr [[OUT]], align 1
; V1-NEXT:    [[CMP:%.*]] = icmp ne i8 [[REDUCTION]], 0
; V1-NEXT:    ret i1 [[CMP]]
;
; V2-LABEL: define i1 @or_nonzero_multiuse(
; V2-SAME: <16 x i8> [[X:%.*]], ptr [[OUT:%.*]]) #[[ATTR1]] {
; V2-NEXT:    [[REDUCTION:%.*]] = call i8 @llvm.vector.reduce.or.v16i8(<16 x i8> [[X]])
; V2-NEXT:    store i8 [[REDUCTION]], ptr [[OUT]], align 1
; V2-NEXT:    [[CMP:%.*]] = icmp ne i8 [[REDUCTION]], 0
; V2-NEXT:    ret i1 [[CMP]]
;
; V3-LABEL: define i1 @or_nonzero_multiuse(
; V3-SAME: <16 x i8> [[X:%.*]], ptr [[OUT:%.*]]) #[[ATTR1]] {
; V3-NEXT:    [[REDUCTION:%.*]] = call i8 @llvm.vector.reduce.or.v16i8(<16 x i8> [[X]])
; V3-NEXT:    store i8 [[REDUCTION]], ptr [[OUT]], align 1
; V3-NEXT:    [[CMP:%.*]] = icmp ne i8 [[REDUCTION]], 0
; V3-NEXT:    ret i1 [[CMP]]
;
; V4-LABEL: define i1 @or_nonzero_multiuse(
; V4-SAME: <16 x i8> [[X:%.*]], ptr [[OUT:%.*]]) #[[ATTR1]] {
; V4-NEXT:    [[REDUCTION:%.*]] = call i8 @llvm.vector.reduce.or.v16i8(<16 x i8> [[X]])
; V4-NEXT:    store i8 [[REDUCTION]], ptr [[OUT]], align 1
; V4-NEXT:    [[CMP:%.*]] = icmp ne i8 [[REDUCTION]], 0
; V4-NEXT:    ret i1 [[CMP]]
;
  %reduction = call i8 @llvm.vector.reduce.or.v16i8(<16 x i8> %x)
  store i8 %reduction, ptr %out, align 1
  %cmp = icmp ne i8 %reduction, 0
  ret i1 %cmp
}
