; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=vector-combine -mtriple=x86_64-unknown-linux-gnu -mcpu=x86-64 < %s | FileCheck %s --check-prefix=X64
; RUN: opt -S -passes=vector-combine -mtriple=x86_64-unknown-linux-gnu -mcpu=x86-64-v2 < %s | FileCheck %s --check-prefix=X64V2
; RUN: opt -S -passes=vector-combine -mtriple=x86_64-unknown-linux-gnu -mcpu=x86-64-v3 < %s | FileCheck %s --check-prefix=X64V3
; RUN: opt -S -passes=vector-combine -mtriple=x86_64-unknown-linux-gnu -mcpu=x86-64-v4 < %s | FileCheck %s --check-prefix=X64V4

define <2 x float> @f32_v2_one_insert_extra_use(ptr %p, float %x) {
;
; X64-LABEL: define <2 x float> @f32_v2_one_insert_extra_use(
; X64-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0:[0-9]+]] {
; X64-NEXT:    [[V:%.*]] = load <2 x float>, ptr [[P]], align 8
; X64-NEXT:    [[I0:%.*]] = insertelement <2 x float> [[V]], float [[X]], i32 0
; X64-NEXT:    store <2 x float> [[I0]], ptr [[P]], align 8
; X64-NEXT:    ret <2 x float> [[V]]
;
; X64V2-LABEL: define <2 x float> @f32_v2_one_insert_extra_use(
; X64V2-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0:[0-9]+]] {
; X64V2-NEXT:    [[V:%.*]] = load <2 x float>, ptr [[P]], align 8
; X64V2-NEXT:    [[I0:%.*]] = insertelement <2 x float> [[V]], float [[X]], i32 0
; X64V2-NEXT:    store <2 x float> [[I0]], ptr [[P]], align 8
; X64V2-NEXT:    ret <2 x float> [[V]]
;
; X64V3-LABEL: define <2 x float> @f32_v2_one_insert_extra_use(
; X64V3-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0:[0-9]+]] {
; X64V3-NEXT:    [[V:%.*]] = load <2 x float>, ptr [[P]], align 8
; X64V3-NEXT:    [[I0:%.*]] = insertelement <2 x float> [[V]], float [[X]], i32 0
; X64V3-NEXT:    store <2 x float> [[I0]], ptr [[P]], align 8
; X64V3-NEXT:    ret <2 x float> [[V]]
;
; X64V4-LABEL: define <2 x float> @f32_v2_one_insert_extra_use(
; X64V4-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0:[0-9]+]] {
; X64V4-NEXT:    [[V:%.*]] = load <2 x float>, ptr [[P]], align 8
; X64V4-NEXT:    [[I0:%.*]] = insertelement <2 x float> [[V]], float [[X]], i32 0
; X64V4-NEXT:    store <2 x float> [[I0]], ptr [[P]], align 8
; X64V4-NEXT:    ret <2 x float> [[V]]
;
  %v = load <2 x float>, ptr %p
  %i0 = insertelement <2 x float> %v, float %x, i32 0
  store <2 x float> %i0, ptr %p
  ret <2 x float> %v
}

define <4 x float> @f32_v4_two_inserts_extra_use(ptr %p, float %x) {
; X64-LABEL: define <4 x float> @f32_v4_two_inserts_extra_use(
; X64-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; X64-NEXT:    [[V:%.*]] = load <4 x float>, ptr [[P]], align 16
; X64-NEXT:    store float [[X]], ptr [[P]], align 16
; X64-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <4 x float>, ptr [[P]], i32 0, i32 1
; X64-NEXT:    store float [[X]], ptr [[TMP1]], align 4
; X64-NEXT:    ret <4 x float> [[V]]
;
; X64V2-LABEL: define <4 x float> @f32_v4_two_inserts_extra_use(
; X64V2-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; X64V2-NEXT:    [[V:%.*]] = load <4 x float>, ptr [[P]], align 16
; X64V2-NEXT:    [[I0:%.*]] = insertelement <4 x float> [[V]], float [[X]], i32 0
; X64V2-NEXT:    [[I1:%.*]] = insertelement <4 x float> [[I0]], float [[X]], i32 1
; X64V2-NEXT:    store <4 x float> [[I1]], ptr [[P]], align 16
; X64V2-NEXT:    ret <4 x float> [[V]]
;
; X64V3-LABEL: define <4 x float> @f32_v4_two_inserts_extra_use(
; X64V3-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; X64V3-NEXT:    [[V:%.*]] = load <4 x float>, ptr [[P]], align 16
; X64V3-NEXT:    [[I0:%.*]] = insertelement <4 x float> [[V]], float [[X]], i32 0
; X64V3-NEXT:    [[I1:%.*]] = insertelement <4 x float> [[I0]], float [[X]], i32 1
; X64V3-NEXT:    store <4 x float> [[I1]], ptr [[P]], align 16
; X64V3-NEXT:    ret <4 x float> [[V]]
;
; X64V4-LABEL: define <4 x float> @f32_v4_two_inserts_extra_use(
; X64V4-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; X64V4-NEXT:    [[V:%.*]] = load <4 x float>, ptr [[P]], align 16
; X64V4-NEXT:    [[I0:%.*]] = insertelement <4 x float> [[V]], float [[X]], i32 0
; X64V4-NEXT:    [[I1:%.*]] = insertelement <4 x float> [[I0]], float [[X]], i32 1
; X64V4-NEXT:    store <4 x float> [[I1]], ptr [[P]], align 16
; X64V4-NEXT:    ret <4 x float> [[V]]
;
  %v = load <4 x float>, ptr %p
  %i0 = insertelement <4 x float> %v, float %x, i32 0
  %i1 = insertelement <4 x float> %i0, float %x, i32 1
  store <4 x float> %i1, ptr %p
  ret <4 x float> %v
}

define <8 x float> @f32_v8_one_insert_extra_use(ptr %p, float %x) {
; X64-LABEL: define <8 x float> @f32_v8_one_insert_extra_use(
; X64-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; X64-NEXT:    [[V:%.*]] = load <8 x float>, ptr [[P]], align 32
; X64-NEXT:    store float [[X]], ptr [[P]], align 32
; X64-NEXT:    ret <8 x float> [[V]]
;
; X64V2-LABEL: define <8 x float> @f32_v8_one_insert_extra_use(
; X64V2-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; X64V2-NEXT:    [[V:%.*]] = load <8 x float>, ptr [[P]], align 32
; X64V2-NEXT:    store float [[X]], ptr [[P]], align 32
; X64V2-NEXT:    ret <8 x float> [[V]]
;
; X64V3-LABEL: define <8 x float> @f32_v8_one_insert_extra_use(
; X64V3-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; X64V3-NEXT:    [[V:%.*]] = load <8 x float>, ptr [[P]], align 32
; X64V3-NEXT:    [[I0:%.*]] = insertelement <8 x float> [[V]], float [[X]], i32 0
; X64V3-NEXT:    store <8 x float> [[I0]], ptr [[P]], align 32
; X64V3-NEXT:    ret <8 x float> [[V]]
;
; X64V4-LABEL: define <8 x float> @f32_v8_one_insert_extra_use(
; X64V4-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; X64V4-NEXT:    [[V:%.*]] = load <8 x float>, ptr [[P]], align 32
; X64V4-NEXT:    [[I0:%.*]] = insertelement <8 x float> [[V]], float [[X]], i32 0
; X64V4-NEXT:    store <8 x float> [[I0]], ptr [[P]], align 32
; X64V4-NEXT:    ret <8 x float> [[V]]
;
  %v = load <8 x float>, ptr %p
  %i0 = insertelement <8 x float> %v, float %x, i32 0
  store <8 x float> %i0, ptr %p
  ret <8 x float> %v
}

define <16 x float> @f32_v16_one_insert_extra_use(ptr %p, float %x) {
; X64-LABEL: define <16 x float> @f32_v16_one_insert_extra_use(
; X64-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; X64-NEXT:    [[V:%.*]] = load <16 x float>, ptr [[P]], align 64
; X64-NEXT:    store float [[X]], ptr [[P]], align 64
; X64-NEXT:    ret <16 x float> [[V]]
;
; X64V2-LABEL: define <16 x float> @f32_v16_one_insert_extra_use(
; X64V2-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; X64V2-NEXT:    [[V:%.*]] = load <16 x float>, ptr [[P]], align 64
; X64V2-NEXT:    store float [[X]], ptr [[P]], align 64
; X64V2-NEXT:    ret <16 x float> [[V]]
;
; X64V3-LABEL: define <16 x float> @f32_v16_one_insert_extra_use(
; X64V3-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; X64V3-NEXT:    [[V:%.*]] = load <16 x float>, ptr [[P]], align 64
; X64V3-NEXT:    store float [[X]], ptr [[P]], align 64
; X64V3-NEXT:    ret <16 x float> [[V]]
;
; X64V4-LABEL: define <16 x float> @f32_v16_one_insert_extra_use(
; X64V4-SAME: ptr [[P:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; X64V4-NEXT:    [[V:%.*]] = load <16 x float>, ptr [[P]], align 64
; X64V4-NEXT:    [[I0:%.*]] = insertelement <16 x float> [[V]], float [[X]], i32 0
; X64V4-NEXT:    store <16 x float> [[I0]], ptr [[P]], align 64
; X64V4-NEXT:    ret <16 x float> [[V]]
;
  %v = load <16 x float>, ptr %p
  %i0 = insertelement <16 x float> %v, float %x, i32 0
  store <16 x float> %i0, ptr %p
  ret <16 x float> %v
}

define <16 x i8> @i8_v16_two_inserts_high_indices(ptr %p, i8 %x) {
;
; X64-LABEL: define <16 x i8> @i8_v16_two_inserts_high_indices(
; X64-SAME: ptr [[P:%.*]], i8 [[X:%.*]]) #[[ATTR0]] {
; X64-NEXT:    [[V:%.*]] = load <16 x i8>, ptr [[P]], align 16
; X64-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 5
; X64-NEXT:    store i8 [[X]], ptr [[TMP1]], align 1
; X64-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 13
; X64-NEXT:    store i8 [[X]], ptr [[TMP2]], align 1
; X64-NEXT:    ret <16 x i8> [[V]]
;
; X64V2-LABEL: define <16 x i8> @i8_v16_two_inserts_high_indices(
; X64V2-SAME: ptr [[P:%.*]], i8 [[X:%.*]]) #[[ATTR0]] {
; X64V2-NEXT:    [[V:%.*]] = load <16 x i8>, ptr [[P]], align 16
; X64V2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 5
; X64V2-NEXT:    store i8 [[X]], ptr [[TMP1]], align 1
; X64V2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 13
; X64V2-NEXT:    store i8 [[X]], ptr [[TMP2]], align 1
; X64V2-NEXT:    ret <16 x i8> [[V]]
;
; X64V3-LABEL: define <16 x i8> @i8_v16_two_inserts_high_indices(
; X64V3-SAME: ptr [[P:%.*]], i8 [[X:%.*]]) #[[ATTR0]] {
; X64V3-NEXT:    [[V:%.*]] = load <16 x i8>, ptr [[P]], align 16
; X64V3-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 5
; X64V3-NEXT:    store i8 [[X]], ptr [[TMP1]], align 1
; X64V3-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 13
; X64V3-NEXT:    store i8 [[X]], ptr [[TMP2]], align 1
; X64V3-NEXT:    ret <16 x i8> [[V]]
;
; X64V4-LABEL: define <16 x i8> @i8_v16_two_inserts_high_indices(
; X64V4-SAME: ptr [[P:%.*]], i8 [[X:%.*]]) #[[ATTR0]] {
; X64V4-NEXT:    [[V:%.*]] = load <16 x i8>, ptr [[P]], align 16
; X64V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 5
; X64V4-NEXT:    store i8 [[X]], ptr [[TMP1]], align 1
; X64V4-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 13
; X64V4-NEXT:    store i8 [[X]], ptr [[TMP2]], align 1
; X64V4-NEXT:    ret <16 x i8> [[V]]
;
  %v = load <16 x i8>, ptr %p
  %i0 = insertelement <16 x i8> %v, i8 %x, i32 5
  %i1 = insertelement <16 x i8> %i0, i8 %x, i32 13
  store <16 x i8> %i1, ptr %p
  ret <16 x i8> %v
}

define <8 x i16> @i16_v8_two_inserts_mixed_indices(ptr %p, i16 %x) {
;
; X64-LABEL: define <8 x i16> @i16_v8_two_inserts_mixed_indices(
; X64-SAME: ptr [[P:%.*]], i16 [[X:%.*]]) #[[ATTR0]] {
; X64-NEXT:    [[V:%.*]] = load <8 x i16>, ptr [[P]], align 16
; X64-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 2
; X64-NEXT:    store i16 [[X]], ptr [[TMP1]], align 4
; X64-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 6
; X64-NEXT:    store i16 [[X]], ptr [[TMP2]], align 4
; X64-NEXT:    ret <8 x i16> [[V]]
;
; X64V2-LABEL: define <8 x i16> @i16_v8_two_inserts_mixed_indices(
; X64V2-SAME: ptr [[P:%.*]], i16 [[X:%.*]]) #[[ATTR0]] {
; X64V2-NEXT:    [[V:%.*]] = load <8 x i16>, ptr [[P]], align 16
; X64V2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 2
; X64V2-NEXT:    store i16 [[X]], ptr [[TMP1]], align 4
; X64V2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 6
; X64V2-NEXT:    store i16 [[X]], ptr [[TMP2]], align 4
; X64V2-NEXT:    ret <8 x i16> [[V]]
;
; X64V3-LABEL: define <8 x i16> @i16_v8_two_inserts_mixed_indices(
; X64V3-SAME: ptr [[P:%.*]], i16 [[X:%.*]]) #[[ATTR0]] {
; X64V3-NEXT:    [[V:%.*]] = load <8 x i16>, ptr [[P]], align 16
; X64V3-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 2
; X64V3-NEXT:    store i16 [[X]], ptr [[TMP1]], align 4
; X64V3-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 6
; X64V3-NEXT:    store i16 [[X]], ptr [[TMP2]], align 4
; X64V3-NEXT:    ret <8 x i16> [[V]]
;
; X64V4-LABEL: define <8 x i16> @i16_v8_two_inserts_mixed_indices(
; X64V4-SAME: ptr [[P:%.*]], i16 [[X:%.*]]) #[[ATTR0]] {
; X64V4-NEXT:    [[V:%.*]] = load <8 x i16>, ptr [[P]], align 16
; X64V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 2
; X64V4-NEXT:    store i16 [[X]], ptr [[TMP1]], align 4
; X64V4-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 6
; X64V4-NEXT:    store i16 [[X]], ptr [[TMP2]], align 4
; X64V4-NEXT:    ret <8 x i16> [[V]]
;
  %v = load <8 x i16>, ptr %p
  %i0 = insertelement <8 x i16> %v, i16 %x, i32 2
  %i1 = insertelement <8 x i16> %i0, i16 %x, i32 6
  store <8 x i16> %i1, ptr %p
  ret <8 x i16> %v
}

define <4 x i32> @i32_v4_one_insert_last_index(ptr %p, i32 %x) {
;
; X64-LABEL: define <4 x i32> @i32_v4_one_insert_last_index(
; X64-SAME: ptr [[P:%.*]], i32 [[X:%.*]]) #[[ATTR0]] {
; X64-NEXT:    [[V:%.*]] = load <4 x i32>, ptr [[P]], align 16
; X64-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <4 x i32>, ptr [[P]], i32 0, i32 3
; X64-NEXT:    store i32 [[X]], ptr [[TMP1]], align 4
; X64-NEXT:    ret <4 x i32> [[V]]
;
; X64V2-LABEL: define <4 x i32> @i32_v4_one_insert_last_index(
; X64V2-SAME: ptr [[P:%.*]], i32 [[X:%.*]]) #[[ATTR0]] {
; X64V2-NEXT:    [[V:%.*]] = load <4 x i32>, ptr [[P]], align 16
; X64V2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <4 x i32>, ptr [[P]], i32 0, i32 3
; X64V2-NEXT:    store i32 [[X]], ptr [[TMP1]], align 4
; X64V2-NEXT:    ret <4 x i32> [[V]]
;
; X64V3-LABEL: define <4 x i32> @i32_v4_one_insert_last_index(
; X64V3-SAME: ptr [[P:%.*]], i32 [[X:%.*]]) #[[ATTR0]] {
; X64V3-NEXT:    [[V:%.*]] = load <4 x i32>, ptr [[P]], align 16
; X64V3-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <4 x i32>, ptr [[P]], i32 0, i32 3
; X64V3-NEXT:    store i32 [[X]], ptr [[TMP1]], align 4
; X64V3-NEXT:    ret <4 x i32> [[V]]
;
; X64V4-LABEL: define <4 x i32> @i32_v4_one_insert_last_index(
; X64V4-SAME: ptr [[P:%.*]], i32 [[X:%.*]]) #[[ATTR0]] {
; X64V4-NEXT:    [[V:%.*]] = load <4 x i32>, ptr [[P]], align 16
; X64V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <4 x i32>, ptr [[P]], i32 0, i32 3
; X64V4-NEXT:    store i32 [[X]], ptr [[TMP1]], align 4
; X64V4-NEXT:    ret <4 x i32> [[V]]
;
  %v = load <4 x i32>, ptr %p
  %i0 = insertelement <4 x i32> %v, i32 %x, i32 3
  store <4 x i32> %i0, ptr %p
  ret <4 x i32> %v
}

define <8 x i64> @i64_v8_two_inserts_mixed_indices(ptr %p, i64 %x) {
;
; X64-LABEL: define <8 x i64> @i64_v8_two_inserts_mixed_indices(
; X64-SAME: ptr [[P:%.*]], i64 [[X:%.*]]) #[[ATTR0]] {
; X64-NEXT:    [[V:%.*]] = load <8 x i64>, ptr [[P]], align 64
; X64-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i64>, ptr [[P]], i32 0, i32 1
; X64-NEXT:    store i64 [[X]], ptr [[TMP1]], align 8
; X64-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i64>, ptr [[P]], i32 0, i32 5
; X64-NEXT:    store i64 [[X]], ptr [[TMP2]], align 8
; X64-NEXT:    ret <8 x i64> [[V]]
;
; X64V2-LABEL: define <8 x i64> @i64_v8_two_inserts_mixed_indices(
; X64V2-SAME: ptr [[P:%.*]], i64 [[X:%.*]]) #[[ATTR0]] {
; X64V2-NEXT:    [[V:%.*]] = load <8 x i64>, ptr [[P]], align 64
; X64V2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i64>, ptr [[P]], i32 0, i32 1
; X64V2-NEXT:    store i64 [[X]], ptr [[TMP1]], align 8
; X64V2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i64>, ptr [[P]], i32 0, i32 5
; X64V2-NEXT:    store i64 [[X]], ptr [[TMP2]], align 8
; X64V2-NEXT:    ret <8 x i64> [[V]]
;
; X64V3-LABEL: define <8 x i64> @i64_v8_two_inserts_mixed_indices(
; X64V3-SAME: ptr [[P:%.*]], i64 [[X:%.*]]) #[[ATTR0]] {
; X64V3-NEXT:    [[V:%.*]] = load <8 x i64>, ptr [[P]], align 64
; X64V3-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i64>, ptr [[P]], i32 0, i32 1
; X64V3-NEXT:    store i64 [[X]], ptr [[TMP1]], align 8
; X64V3-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i64>, ptr [[P]], i32 0, i32 5
; X64V3-NEXT:    store i64 [[X]], ptr [[TMP2]], align 8
; X64V3-NEXT:    ret <8 x i64> [[V]]
;
; X64V4-LABEL: define <8 x i64> @i64_v8_two_inserts_mixed_indices(
; X64V4-SAME: ptr [[P:%.*]], i64 [[X:%.*]]) #[[ATTR0]] {
; X64V4-NEXT:    [[V:%.*]] = load <8 x i64>, ptr [[P]], align 64
; X64V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i64>, ptr [[P]], i32 0, i32 1
; X64V4-NEXT:    store i64 [[X]], ptr [[TMP1]], align 8
; X64V4-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i64>, ptr [[P]], i32 0, i32 5
; X64V4-NEXT:    store i64 [[X]], ptr [[TMP2]], align 8
; X64V4-NEXT:    ret <8 x i64> [[V]]
;
  %v = load <8 x i64>, ptr %p
  %i0 = insertelement <8 x i64> %v, i64 %x, i32 1
  %i1 = insertelement <8 x i64> %i0, i64 %x, i32 5
  store <8 x i64> %i1, ptr %p
  ret <8 x i64> %v
}

define <4 x double> @f64_v4_two_inserts_mixed_indices(ptr %p, double %x) {
;
; X64-LABEL: define <4 x double> @f64_v4_two_inserts_mixed_indices(
; X64-SAME: ptr [[P:%.*]], double [[X:%.*]]) #[[ATTR0]] {
; X64-NEXT:    [[V:%.*]] = load <4 x double>, ptr [[P]], align 32
; X64-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <4 x double>, ptr [[P]], i32 0, i32 1
; X64-NEXT:    store double [[X]], ptr [[TMP1]], align 8
; X64-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <4 x double>, ptr [[P]], i32 0, i32 3
; X64-NEXT:    store double [[X]], ptr [[TMP2]], align 8
; X64-NEXT:    ret <4 x double> [[V]]
;
; X64V2-LABEL: define <4 x double> @f64_v4_two_inserts_mixed_indices(
; X64V2-SAME: ptr [[P:%.*]], double [[X:%.*]]) #[[ATTR0]] {
; X64V2-NEXT:    [[V:%.*]] = load <4 x double>, ptr [[P]], align 32
; X64V2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <4 x double>, ptr [[P]], i32 0, i32 1
; X64V2-NEXT:    store double [[X]], ptr [[TMP1]], align 8
; X64V2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <4 x double>, ptr [[P]], i32 0, i32 3
; X64V2-NEXT:    store double [[X]], ptr [[TMP2]], align 8
; X64V2-NEXT:    ret <4 x double> [[V]]
;
; X64V3-LABEL: define <4 x double> @f64_v4_two_inserts_mixed_indices(
; X64V3-SAME: ptr [[P:%.*]], double [[X:%.*]]) #[[ATTR0]] {
; X64V3-NEXT:    [[V:%.*]] = load <4 x double>, ptr [[P]], align 32
; X64V3-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <4 x double>, ptr [[P]], i32 0, i32 1
; X64V3-NEXT:    store double [[X]], ptr [[TMP1]], align 8
; X64V3-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <4 x double>, ptr [[P]], i32 0, i32 3
; X64V3-NEXT:    store double [[X]], ptr [[TMP2]], align 8
; X64V3-NEXT:    ret <4 x double> [[V]]
;
; X64V4-LABEL: define <4 x double> @f64_v4_two_inserts_mixed_indices(
; X64V4-SAME: ptr [[P:%.*]], double [[X:%.*]]) #[[ATTR0]] {
; X64V4-NEXT:    [[V:%.*]] = load <4 x double>, ptr [[P]], align 32
; X64V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <4 x double>, ptr [[P]], i32 0, i32 1
; X64V4-NEXT:    store double [[X]], ptr [[TMP1]], align 8
; X64V4-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <4 x double>, ptr [[P]], i32 0, i32 3
; X64V4-NEXT:    store double [[X]], ptr [[TMP2]], align 8
; X64V4-NEXT:    ret <4 x double> [[V]]
;
  %v = load <4 x double>, ptr %p
  %i0 = insertelement <4 x double> %v, double %x, i32 1
  %i1 = insertelement <4 x double> %i0, double %x, i32 3
  store <4 x double> %i1, ptr %p
  ret <4 x double> %v
}

define <8 x i16> @i16_v8_three_inserts(ptr %p, i16 %x) {
;
; X64-LABEL: define <8 x i16> @i16_v8_three_inserts(
; X64-SAME: ptr [[P:%.*]], i16 [[X:%.*]]) #[[ATTR0]] {
; X64-NEXT:    [[V:%.*]] = load <8 x i16>, ptr [[P]], align 16
; X64-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 1
; X64-NEXT:    store i16 [[X]], ptr [[TMP1]], align 2
; X64-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 4
; X64-NEXT:    store i16 [[X]], ptr [[TMP2]], align 8
; X64-NEXT:    [[TMP3:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 7
; X64-NEXT:    store i16 [[X]], ptr [[TMP3]], align 2
; X64-NEXT:    ret <8 x i16> [[V]]
;
; X64V2-LABEL: define <8 x i16> @i16_v8_three_inserts(
; X64V2-SAME: ptr [[P:%.*]], i16 [[X:%.*]]) #[[ATTR0]] {
; X64V2-NEXT:    [[V:%.*]] = load <8 x i16>, ptr [[P]], align 16
; X64V2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 1
; X64V2-NEXT:    store i16 [[X]], ptr [[TMP1]], align 2
; X64V2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 4
; X64V2-NEXT:    store i16 [[X]], ptr [[TMP2]], align 8
; X64V2-NEXT:    [[TMP3:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 7
; X64V2-NEXT:    store i16 [[X]], ptr [[TMP3]], align 2
; X64V2-NEXT:    ret <8 x i16> [[V]]
;
; X64V3-LABEL: define <8 x i16> @i16_v8_three_inserts(
; X64V3-SAME: ptr [[P:%.*]], i16 [[X:%.*]]) #[[ATTR0]] {
; X64V3-NEXT:    [[V:%.*]] = load <8 x i16>, ptr [[P]], align 16
; X64V3-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 1
; X64V3-NEXT:    store i16 [[X]], ptr [[TMP1]], align 2
; X64V3-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 4
; X64V3-NEXT:    store i16 [[X]], ptr [[TMP2]], align 8
; X64V3-NEXT:    [[TMP3:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 7
; X64V3-NEXT:    store i16 [[X]], ptr [[TMP3]], align 2
; X64V3-NEXT:    ret <8 x i16> [[V]]
;
; X64V4-LABEL: define <8 x i16> @i16_v8_three_inserts(
; X64V4-SAME: ptr [[P:%.*]], i16 [[X:%.*]]) #[[ATTR0]] {
; X64V4-NEXT:    [[V:%.*]] = load <8 x i16>, ptr [[P]], align 16
; X64V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 1
; X64V4-NEXT:    store i16 [[X]], ptr [[TMP1]], align 2
; X64V4-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 4
; X64V4-NEXT:    store i16 [[X]], ptr [[TMP2]], align 8
; X64V4-NEXT:    [[TMP3:%.*]] = getelementptr inbounds <8 x i16>, ptr [[P]], i32 0, i32 7
; X64V4-NEXT:    store i16 [[X]], ptr [[TMP3]], align 2
; X64V4-NEXT:    ret <8 x i16> [[V]]
;
  %v = load <8 x i16>, ptr %p
  %i0 = insertelement <8 x i16> %v, i16 %x, i32 1
  %i1 = insertelement <8 x i16> %i0, i16 %x, i32 4
  %i2 = insertelement <8 x i16> %i1, i16 %x, i32 7
  store <8 x i16> %i2, ptr %p
  ret <8 x i16> %v
}

define <16 x i8> @i8_v16_four_inserts(ptr %p, i8 %x) {
;
; X64-LABEL: define <16 x i8> @i8_v16_four_inserts(
; X64-SAME: ptr [[P:%.*]], i8 [[X:%.*]]) #[[ATTR0]] {
; X64-NEXT:    [[V:%.*]] = load <16 x i8>, ptr [[P]], align 16
; X64-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 2
; X64-NEXT:    store i8 [[X]], ptr [[TMP1]], align 2
; X64-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 5
; X64-NEXT:    store i8 [[X]], ptr [[TMP2]], align 1
; X64-NEXT:    [[TMP3:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 9
; X64-NEXT:    store i8 [[X]], ptr [[TMP3]], align 1
; X64-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 14
; X64-NEXT:    store i8 [[X]], ptr [[TMP4]], align 2
; X64-NEXT:    ret <16 x i8> [[V]]
;
; X64V2-LABEL: define <16 x i8> @i8_v16_four_inserts(
; X64V2-SAME: ptr [[P:%.*]], i8 [[X:%.*]]) #[[ATTR0]] {
; X64V2-NEXT:    [[V:%.*]] = load <16 x i8>, ptr [[P]], align 16
; X64V2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 2
; X64V2-NEXT:    store i8 [[X]], ptr [[TMP1]], align 2
; X64V2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 5
; X64V2-NEXT:    store i8 [[X]], ptr [[TMP2]], align 1
; X64V2-NEXT:    [[TMP3:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 9
; X64V2-NEXT:    store i8 [[X]], ptr [[TMP3]], align 1
; X64V2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 14
; X64V2-NEXT:    store i8 [[X]], ptr [[TMP4]], align 2
; X64V2-NEXT:    ret <16 x i8> [[V]]
;
; X64V3-LABEL: define <16 x i8> @i8_v16_four_inserts(
; X64V3-SAME: ptr [[P:%.*]], i8 [[X:%.*]]) #[[ATTR0]] {
; X64V3-NEXT:    [[V:%.*]] = load <16 x i8>, ptr [[P]], align 16
; X64V3-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 2
; X64V3-NEXT:    store i8 [[X]], ptr [[TMP1]], align 2
; X64V3-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 5
; X64V3-NEXT:    store i8 [[X]], ptr [[TMP2]], align 1
; X64V3-NEXT:    [[TMP3:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 9
; X64V3-NEXT:    store i8 [[X]], ptr [[TMP3]], align 1
; X64V3-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 14
; X64V3-NEXT:    store i8 [[X]], ptr [[TMP4]], align 2
; X64V3-NEXT:    ret <16 x i8> [[V]]
;
; X64V4-LABEL: define <16 x i8> @i8_v16_four_inserts(
; X64V4-SAME: ptr [[P:%.*]], i8 [[X:%.*]]) #[[ATTR0]] {
; X64V4-NEXT:    [[V:%.*]] = load <16 x i8>, ptr [[P]], align 16
; X64V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 2
; X64V4-NEXT:    store i8 [[X]], ptr [[TMP1]], align 2
; X64V4-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 5
; X64V4-NEXT:    store i8 [[X]], ptr [[TMP2]], align 1
; X64V4-NEXT:    [[TMP3:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 9
; X64V4-NEXT:    store i8 [[X]], ptr [[TMP3]], align 1
; X64V4-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <16 x i8>, ptr [[P]], i32 0, i32 14
; X64V4-NEXT:    store i8 [[X]], ptr [[TMP4]], align 2
; X64V4-NEXT:    ret <16 x i8> [[V]]
;
  %v = load <16 x i8>, ptr %p
  %i0 = insertelement <16 x i8> %v, i8 %x, i32 2
  %i1 = insertelement <16 x i8> %i0, i8 %x, i32 5
  %i2 = insertelement <16 x i8> %i1, i8 %x, i32 9
  %i3 = insertelement <16 x i8> %i2, i8 %x, i32 14
  store <16 x i8> %i3, ptr %p
  ret <16 x i8> %v
}

define <8 x i32> @i32_v8_five_inserts(ptr %p, i32 %x) {
;
; X64-LABEL: define <8 x i32> @i32_v8_five_inserts(
; X64-SAME: ptr [[P:%.*]], i32 [[X:%.*]]) #[[ATTR0]] {
; X64-NEXT:    [[V:%.*]] = load <8 x i32>, ptr [[P]], align 32
; X64-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 1
; X64-NEXT:    store i32 [[X]], ptr [[TMP1]], align 4
; X64-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 2
; X64-NEXT:    store i32 [[X]], ptr [[TMP2]], align 8
; X64-NEXT:    [[TMP3:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 4
; X64-NEXT:    store i32 [[X]], ptr [[TMP3]], align 16
; X64-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 6
; X64-NEXT:    store i32 [[X]], ptr [[TMP4]], align 8
; X64-NEXT:    [[TMP5:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 7
; X64-NEXT:    store i32 [[X]], ptr [[TMP5]], align 4
; X64-NEXT:    ret <8 x i32> [[V]]
;
; X64V2-LABEL: define <8 x i32> @i32_v8_five_inserts(
; X64V2-SAME: ptr [[P:%.*]], i32 [[X:%.*]]) #[[ATTR0]] {
; X64V2-NEXT:    [[V:%.*]] = load <8 x i32>, ptr [[P]], align 32
; X64V2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 1
; X64V2-NEXT:    store i32 [[X]], ptr [[TMP1]], align 4
; X64V2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 2
; X64V2-NEXT:    store i32 [[X]], ptr [[TMP2]], align 8
; X64V2-NEXT:    [[TMP3:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 4
; X64V2-NEXT:    store i32 [[X]], ptr [[TMP3]], align 16
; X64V2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 6
; X64V2-NEXT:    store i32 [[X]], ptr [[TMP4]], align 8
; X64V2-NEXT:    [[TMP5:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 7
; X64V2-NEXT:    store i32 [[X]], ptr [[TMP5]], align 4
; X64V2-NEXT:    ret <8 x i32> [[V]]
;
; X64V3-LABEL: define <8 x i32> @i32_v8_five_inserts(
; X64V3-SAME: ptr [[P:%.*]], i32 [[X:%.*]]) #[[ATTR0]] {
; X64V3-NEXT:    [[V:%.*]] = load <8 x i32>, ptr [[P]], align 32
; X64V3-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 1
; X64V3-NEXT:    store i32 [[X]], ptr [[TMP1]], align 4
; X64V3-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 2
; X64V3-NEXT:    store i32 [[X]], ptr [[TMP2]], align 8
; X64V3-NEXT:    [[TMP3:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 4
; X64V3-NEXT:    store i32 [[X]], ptr [[TMP3]], align 16
; X64V3-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 6
; X64V3-NEXT:    store i32 [[X]], ptr [[TMP4]], align 8
; X64V3-NEXT:    [[TMP5:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 7
; X64V3-NEXT:    store i32 [[X]], ptr [[TMP5]], align 4
; X64V3-NEXT:    ret <8 x i32> [[V]]
;
; X64V4-LABEL: define <8 x i32> @i32_v8_five_inserts(
; X64V4-SAME: ptr [[P:%.*]], i32 [[X:%.*]]) #[[ATTR0]] {
; X64V4-NEXT:    [[V:%.*]] = load <8 x i32>, ptr [[P]], align 32
; X64V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 1
; X64V4-NEXT:    store i32 [[X]], ptr [[TMP1]], align 4
; X64V4-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 2
; X64V4-NEXT:    store i32 [[X]], ptr [[TMP2]], align 8
; X64V4-NEXT:    [[TMP3:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 4
; X64V4-NEXT:    store i32 [[X]], ptr [[TMP3]], align 16
; X64V4-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 6
; X64V4-NEXT:    store i32 [[X]], ptr [[TMP4]], align 8
; X64V4-NEXT:    [[TMP5:%.*]] = getelementptr inbounds <8 x i32>, ptr [[P]], i32 0, i32 7
; X64V4-NEXT:    store i32 [[X]], ptr [[TMP5]], align 4
; X64V4-NEXT:    ret <8 x i32> [[V]]
;
  %v = load <8 x i32>, ptr %p
  %i0 = insertelement <8 x i32> %v, i32 %x, i32 1
  %i1 = insertelement <8 x i32> %i0, i32 %x, i32 2
  %i2 = insertelement <8 x i32> %i1, i32 %x, i32 4
  %i3 = insertelement <8 x i32> %i2, i32 %x, i32 6
  %i4 = insertelement <8 x i32> %i3, i32 %x, i32 7
  store <8 x i32> %i4, ptr %p
  ret <8 x i32> %v
}
