; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=vector-combine -mtriple=x86_64-- -mcpu=x86-64 -S < %s | FileCheck %s --check-prefixes=CHECK,SSE
; RUN: opt -passes=vector-combine -mtriple=x86_64-- -mcpu=x86-64-v3 -S < %s | FileCheck %s --check-prefixes=CHECK,AVX

define <8 x i32> @test_multiuse_one_side(<4 x i32> %0, <4 x i32> %1) {
; SSE-LABEL: define <8 x i32> @test_multiuse_one_side(
; SSE-SAME: <4 x i32> [[TMP0:%.*]], <4 x i32> [[TMP1:%.*]]) #[[ATTR0:[0-9]+]] {
; SSE-NEXT:  [[ENTRY:.*:]]
; SSE-NEXT:    [[A:%.*]] = call <4 x i32> @llvm.abs.v4i32(<4 x i32> [[TMP0]], i1 false)
; SSE-NEXT:    [[EXTRA_USE:%.*]] = extractelement <4 x i32> [[A]], i32 0
; SSE-NEXT:    [[B:%.*]] = call <4 x i32> @llvm.abs.v4i32(<4 x i32> [[TMP1]], i1 false)
; SSE-NEXT:    [[R:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> [[B]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; SSE-NEXT:    [[RES:%.*]] = add i32 [[EXTRA_USE]], 1
; SSE-NEXT:    ret <8 x i32> [[R]]
;
; AVX-LABEL: define <8 x i32> @test_multiuse_one_side(
; AVX-SAME: <4 x i32> [[TMP0:%.*]], <4 x i32> [[TMP1:%.*]]) #[[ATTR0:[0-9]+]] {
; AVX-NEXT:  [[ENTRY:.*:]]
; AVX-NEXT:    [[A:%.*]] = call <4 x i32> @llvm.abs.v4i32(<4 x i32> [[TMP0]], i1 false)
; AVX-NEXT:    [[EXTRA_USE:%.*]] = extractelement <4 x i32> [[A]], i32 0
; AVX-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; AVX-NEXT:    [[R:%.*]] = call <8 x i32> @llvm.abs.v8i32(<8 x i32> [[TMP2]], i1 false)
; AVX-NEXT:    [[RES:%.*]] = add i32 [[EXTRA_USE]], 1
; AVX-NEXT:    ret <8 x i32> [[R]]
;
entry:
  %a = call <4 x i32> @llvm.abs.v4i32(<4 x i32> %0, i1 false)
  %extra_use = extractelement <4 x i32> %a, i32 0
  %b = call <4 x i32> @llvm.abs.v4i32(<4 x i32> %1, i1 false)
  %r = shufflevector <4 x i32> %a, <4 x i32> %b, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %res = add i32 %extra_use, 1
  ret <8 x i32> %r
}

define <8 x i32> @test_multiuse_both_sides(<4 x i32> %0, <4 x i32> %1) {
; CHECK-LABEL: define <8 x i32> @test_multiuse_both_sides(
; CHECK-SAME: <4 x i32> [[TMP0:%.*]], <4 x i32> [[TMP1:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A:%.*]] = call <4 x i32> @llvm.abs.v4i32(<4 x i32> [[TMP0]], i1 false)
; CHECK-NEXT:    [[B:%.*]] = call <4 x i32> @llvm.abs.v4i32(<4 x i32> [[TMP1]], i1 false)
; CHECK-NEXT:    [[UA:%.*]] = extractelement <4 x i32> [[A]], i32 0
; CHECK-NEXT:    [[UB:%.*]] = extractelement <4 x i32> [[B]], i32 0
; CHECK-NEXT:    [[R:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> [[B]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    ret <8 x i32> [[R]]
;
entry:
  %a = call <4 x i32> @llvm.abs.v4i32(<4 x i32> %0, i1 false)
  %b = call <4 x i32> @llvm.abs.v4i32(<4 x i32> %1, i1 false)
  %ua = extractelement <4 x i32> %a, i32 0
  %ub = extractelement <4 x i32> %b, i32 0
  %r = shufflevector <4 x i32> %a, <4 x i32> %b, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i32> %r
}

define <8 x i32> @test_same_instruction_multi_use(<4 x i32> %0) {
; SSE-LABEL: define <8 x i32> @test_same_instruction_multi_use(
; SSE-SAME: <4 x i32> [[TMP0:%.*]]) #[[ATTR0]] {
; SSE-NEXT:  [[ENTRY:.*:]]
; SSE-NEXT:    [[A:%.*]] = call <4 x i32> @llvm.abs.v4i32(<4 x i32> [[TMP0]], i1 false)
; SSE-NEXT:    [[EXTRA:%.*]] = add <4 x i32> [[A]], [[A]]
; SSE-NEXT:    [[R:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> [[A]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; SSE-NEXT:    ret <8 x i32> [[R]]
;
; AVX-LABEL: define <8 x i32> @test_same_instruction_multi_use(
; AVX-SAME: <4 x i32> [[TMP0:%.*]]) #[[ATTR0]] {
; AVX-NEXT:  [[ENTRY:.*:]]
; AVX-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP0]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; AVX-NEXT:    [[R:%.*]] = call <8 x i32> @llvm.abs.v8i32(<8 x i32> [[TMP1]], i1 false)
; AVX-NEXT:    ret <8 x i32> [[R]]
;
entry:
  %a = call <4 x i32> @llvm.abs.v4i32(<4 x i32> %0, i1 false)
  %extra = add <4 x i32> %a, %a
  %r = shufflevector <4 x i32> %a, <4 x i32> %a, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i32> %r
}

define <8 x i32> @test_shared_operands(<4 x i32> %0, <4 x i32> %1) {
; CHECK-LABEL: define <8 x i32> @test_shared_operands(
; CHECK-SAME: <4 x i32> [[TMP0:%.*]], <4 x i32> [[TMP1:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[R:%.*]] = call <8 x i32> @llvm.smax.v8i32(<8 x i32> [[TMP2]], <8 x i32> [[TMP2]])
; CHECK-NEXT:    ret <8 x i32> [[R]]
;
entry:
  %a = call <4 x i32> @llvm.smax.v4i32(<4 x i32> %0, <4 x i32> %0)
  %b = call <4 x i32> @llvm.smax.v4i32(<4 x i32> %1, <4 x i32> %1)
  %r = shufflevector <4 x i32> %a, <4 x i32> %b, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i32> %r
}
