; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=vector-combine -S %s -mtriple=x86_64-- -mattr=+sse2 | FileCheck %s --check-prefixes=CHECK,SSE
; RUN: opt -passes=vector-combine -S %s -mtriple=x86_64-- -mattr=+avx2 | FileCheck %s --check-prefixes=CHECK,AVX

; Tests for foldShuffleToIdentity handling of bitcasts that change element count.
; Motivated by issue #96884: SSE/AVX code uses vXi64 for __m128i/__m256i types,
; requiring bitcasts to different element-count types for operations.

; Narrowing bitcast: split <4 x i32> through <2 x i64> bitcasts and rejoin.
define <4 x i32> @bitcast_i32_to_i64_add(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: @bitcast_i32_to_i64_add(
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i32> [[A:%.*]] to <2 x i64>
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32> [[B:%.*]] to <2 x i64>
; CHECK-NEXT:    [[TMP3:%.*]] = add <2 x i64> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <2 x i64> [[TMP3]] to <4 x i32>
; CHECK-NEXT:    ret <4 x i32> [[TMP4]]
;
  %a_lo = shufflevector <4 x i32> %a, <4 x i32> poison, <2 x i32> <i32 0, i32 1>
  %a_hi = shufflevector <4 x i32> %a, <4 x i32> poison, <2 x i32> <i32 2, i32 3>
  %b_lo = shufflevector <4 x i32> %b, <4 x i32> poison, <2 x i32> <i32 0, i32 1>
  %b_hi = shufflevector <4 x i32> %b, <4 x i32> poison, <2 x i32> <i32 2, i32 3>
  %bc_a_lo = bitcast <2 x i32> %a_lo to <1 x i64>
  %bc_a_hi = bitcast <2 x i32> %a_hi to <1 x i64>
  %bc_b_lo = bitcast <2 x i32> %b_lo to <1 x i64>
  %bc_b_hi = bitcast <2 x i32> %b_hi to <1 x i64>
  %add_lo = add <1 x i64> %bc_a_lo, %bc_b_lo
  %add_hi = add <1 x i64> %bc_a_hi, %bc_b_hi
  %bc_lo = bitcast <1 x i64> %add_lo to <2 x i32>
  %bc_hi = bitcast <1 x i64> %add_hi to <2 x i32>
  %result = shufflevector <2 x i32> %bc_lo, <2 x i32> %bc_hi, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %result
}

; Widening bitcast: split <2 x i64> through <4 x i32> bitcasts and rejoin.
; This is the typical SSE pattern: __m128i is <2 x i64>, operations on <4 x i32>.
define <2 x i64> @bitcast_i64_to_i32_xor(<2 x i64> %a, <2 x i64> %b) {
; CHECK-LABEL: @bitcast_i64_to_i32_xor(
; CHECK-NEXT:    [[B:%.*]] = xor <2 x i64> [[A:%.*]], [[B1:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[B]] to <4 x i32>
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <4 x i32> [[TMP2]] to <2 x i64>
; CHECK-NEXT:    ret <2 x i64> [[TMP4]]
;
  %a_lo = shufflevector <2 x i64> %a, <2 x i64> poison, <1 x i32> <i32 0>
  %a_hi = shufflevector <2 x i64> %a, <2 x i64> poison, <1 x i32> <i32 1>
  %b_lo = shufflevector <2 x i64> %b, <2 x i64> poison, <1 x i32> <i32 0>
  %b_hi = shufflevector <2 x i64> %b, <2 x i64> poison, <1 x i32> <i32 1>
  %bc_a_lo = bitcast <1 x i64> %a_lo to <2 x i32>
  %bc_a_hi = bitcast <1 x i64> %a_hi to <2 x i32>
  %bc_b_lo = bitcast <1 x i64> %b_lo to <2 x i32>
  %bc_b_hi = bitcast <1 x i64> %b_hi to <2 x i32>
  %xor_lo = xor <2 x i32> %bc_a_lo, %bc_b_lo
  %xor_hi = xor <2 x i32> %bc_a_hi, %bc_b_hi
  %bc_lo = bitcast <2 x i32> %xor_lo to <1 x i64>
  %bc_hi = bitcast <2 x i32> %xor_hi to <1 x i64>
  %result = shufflevector <1 x i64> %bc_lo, <1 x i64> %bc_hi, <2 x i32> <i32 0, i32 1>
  ret <2 x i64> %result
}

; i64 -> i16: wider ratio (4x), split and rejoin through <8 x i16> operations.
define <2 x i64> @bitcast_i64_to_i16_shl(<2 x i64> %a) {
; CHECK-LABEL: @bitcast_i64_to_i16_shl(
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <2 x i64> [[A:%.*]] to <8 x i16>
; CHECK-NEXT:    [[TMP2:%.*]] = shl <8 x i16> [[TMP1]], splat (i16 3)
; CHECK-NEXT:    [[RESULT:%.*]] = bitcast <8 x i16> [[TMP2]] to <2 x i64>
; CHECK-NEXT:    ret <2 x i64> [[RESULT]]
;
  %a_lo = shufflevector <2 x i64> %a, <2 x i64> poison, <1 x i32> <i32 0>
  %a_hi = shufflevector <2 x i64> %a, <2 x i64> poison, <1 x i32> <i32 1>
  %bc_lo = bitcast <1 x i64> %a_lo to <4 x i16>
  %bc_hi = bitcast <1 x i64> %a_hi to <4 x i16>
  %shl_lo = shl <4 x i16> %bc_lo, splat (i16 3)
  %shl_hi = shl <4 x i16> %bc_hi, splat (i16 3)
  %res_lo = bitcast <4 x i16> %shl_lo to <1 x i64>
  %res_hi = bitcast <4 x i16> %shl_hi to <1 x i64>
  %result = shufflevector <1 x i64> %res_lo, <1 x i64> %res_hi, <2 x i32> <i32 0, i32 1>
  ret <2 x i64> %result
}

; i64 -> i8: ratio of 8, split __m128i into halves, byte-shift, rejoin.
define <2 x i64> @bitcast_i64_to_i8_add(<2 x i64> %a, <2 x i64> %b) {
; CHECK-LABEL: @bitcast_i64_to_i8_add(
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <2 x i64> [[A:%.*]] to <16 x i8>
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64> [[B:%.*]] to <16 x i8>
; CHECK-NEXT:    [[TMP3:%.*]] = add <16 x i8> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[RESULT:%.*]] = bitcast <16 x i8> [[TMP3]] to <2 x i64>
; CHECK-NEXT:    ret <2 x i64> [[RESULT]]
;
  %a_lo = shufflevector <2 x i64> %a, <2 x i64> poison, <1 x i32> <i32 0>
  %a_hi = shufflevector <2 x i64> %a, <2 x i64> poison, <1 x i32> <i32 1>
  %b_lo = shufflevector <2 x i64> %b, <2 x i64> poison, <1 x i32> <i32 0>
  %b_hi = shufflevector <2 x i64> %b, <2 x i64> poison, <1 x i32> <i32 1>
  %bc_a_lo = bitcast <1 x i64> %a_lo to <8 x i8>
  %bc_a_hi = bitcast <1 x i64> %a_hi to <8 x i8>
  %bc_b_lo = bitcast <1 x i64> %b_lo to <8 x i8>
  %bc_b_hi = bitcast <1 x i64> %b_hi to <8 x i8>
  %add_lo = add <8 x i8> %bc_a_lo, %bc_b_lo
  %add_hi = add <8 x i8> %bc_a_hi, %bc_b_hi
  %bc_lo = bitcast <8 x i8> %add_lo to <1 x i64>
  %bc_hi = bitcast <8 x i8> %add_hi to <1 x i64>
  %result = shufflevector <1 x i64> %bc_lo, <1 x i64> %bc_hi, <2 x i32> <i32 0, i32 1>
  ret <2 x i64> %result
}

; AVX pattern: <4 x i64> (__m256i) split into two <2 x i64> halves,
; bitcast to <4 x i32>, operate, bitcast back, rejoin.
define <4 x i64> @avx_bitcast_i64_to_i32_and(<4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: @avx_bitcast_i64_to_i32_and(
; CHECK-NEXT:    [[B:%.*]] = and <4 x i64> [[A:%.*]], [[B1:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i64> [[B]] to <8 x i32>
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <8 x i32> [[TMP2]] to <4 x i64>
; CHECK-NEXT:    ret <4 x i64> [[TMP4]]
;
  %a_lo = shufflevector <4 x i64> %a, <4 x i64> poison, <2 x i32> <i32 0, i32 1>
  %a_hi = shufflevector <4 x i64> %a, <4 x i64> poison, <2 x i32> <i32 2, i32 3>
  %b_lo = shufflevector <4 x i64> %b, <4 x i64> poison, <2 x i32> <i32 0, i32 1>
  %b_hi = shufflevector <4 x i64> %b, <4 x i64> poison, <2 x i32> <i32 2, i32 3>
  %bc_a_lo = bitcast <2 x i64> %a_lo to <4 x i32>
  %bc_a_hi = bitcast <2 x i64> %a_hi to <4 x i32>
  %bc_b_lo = bitcast <2 x i64> %b_lo to <4 x i32>
  %bc_b_hi = bitcast <2 x i64> %b_hi to <4 x i32>
  %and_lo = and <4 x i32> %bc_a_lo, %bc_b_lo
  %and_hi = and <4 x i32> %bc_a_hi, %bc_b_hi
  %bc_lo = bitcast <4 x i32> %and_lo to <2 x i64>
  %bc_hi = bitcast <4 x i32> %and_hi to <2 x i64>
  %result = shufflevector <2 x i64> %bc_lo, <2 x i64> %bc_hi, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i64> %result
}

; Compare through bitcast: split, bitcast, icmp, select, bitcast back, rejoin.
define <4 x i64> @avx_bitcast_select(<4 x i64> %a, <4 x i64> %b) {
; SSE-LABEL: @avx_bitcast_select(
; SSE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i64> [[A:%.*]] to <8 x i32>
; SSE-NEXT:    [[TMP2:%.*]] = bitcast <4 x i64> [[B:%.*]] to <8 x i32>
; SSE-NEXT:    [[TMP3:%.*]] = icmp sgt <8 x i32> [[TMP1]], [[TMP2]]
; SSE-NEXT:    [[TMP4:%.*]] = select <8 x i1> [[TMP3]], <8 x i32> [[TMP1]], <8 x i32> [[TMP2]]
; SSE-NEXT:    [[RESULT:%.*]] = bitcast <8 x i32> [[TMP4]] to <4 x i64>
; SSE-NEXT:    ret <4 x i64> [[RESULT]]
;
; AVX-LABEL: @avx_bitcast_select(
; AVX-NEXT:    [[TMP1:%.*]] = bitcast <4 x i64> [[A:%.*]] to <8 x i32>
; AVX-NEXT:    [[TMP2:%.*]] = bitcast <4 x i64> [[B:%.*]] to <8 x i32>
; AVX-NEXT:    [[TMP3:%.*]] = icmp sgt <8 x i32> [[TMP1]], [[TMP2]]
; AVX-NEXT:    [[TMP4:%.*]] = bitcast <4 x i64> [[A]] to <8 x i32>
; AVX-NEXT:    [[TMP5:%.*]] = bitcast <4 x i64> [[B]] to <8 x i32>
; AVX-NEXT:    [[TMP6:%.*]] = select <8 x i1> [[TMP3]], <8 x i32> [[TMP4]], <8 x i32> [[TMP5]]
; AVX-NEXT:    [[RESULT:%.*]] = bitcast <8 x i32> [[TMP6]] to <4 x i64>
; AVX-NEXT:    ret <4 x i64> [[RESULT]]
;
  %a_lo = shufflevector <4 x i64> %a, <4 x i64> poison, <2 x i32> <i32 0, i32 1>
  %a_hi = shufflevector <4 x i64> %a, <4 x i64> poison, <2 x i32> <i32 2, i32 3>
  %b_lo = shufflevector <4 x i64> %b, <4 x i64> poison, <2 x i32> <i32 0, i32 1>
  %b_hi = shufflevector <4 x i64> %b, <4 x i64> poison, <2 x i32> <i32 2, i32 3>
  %bc_a_lo = bitcast <2 x i64> %a_lo to <4 x i32>
  %bc_a_hi = bitcast <2 x i64> %a_hi to <4 x i32>
  %bc_b_lo = bitcast <2 x i64> %b_lo to <4 x i32>
  %bc_b_hi = bitcast <2 x i64> %b_hi to <4 x i32>
  %cmp_lo = icmp sgt <4 x i32> %bc_a_lo, %bc_b_lo
  %cmp_hi = icmp sgt <4 x i32> %bc_a_hi, %bc_b_hi
  %sel_lo = select <4 x i1> %cmp_lo, <4 x i32> %bc_a_lo, <4 x i32> %bc_b_lo
  %sel_hi = select <4 x i1> %cmp_hi, <4 x i32> %bc_a_hi, <4 x i32> %bc_b_hi
  %bc_lo = bitcast <4 x i32> %sel_lo to <2 x i64>
  %bc_hi = bitcast <4 x i32> %sel_hi to <2 x i64>
  %result = shufflevector <2 x i64> %bc_lo, <2 x i64> %bc_hi, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i64> %result
}

; Negative test: misaligned lanes in widening bitcast should not fold.
define <8 x i16> @bitcast_widen_misaligned(<8 x i16> %a) {
; CHECK-LABEL: @bitcast_widen_misaligned(
; CHECK-NEXT:    [[LO:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 1, i32 2, i32 3, i32 4>
; CHECK-NEXT:    [[BC_LO:%.*]] = bitcast <4 x i16> [[LO]] to <2 x i32>
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i16> [[A]] to <4 x i32>
; CHECK-NEXT:    [[BC_HI:%.*]] = shufflevector <4 x i32> [[TMP1]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <2 x i32> [[BC_LO]], <2 x i32> [[BC_HI]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    [[TMP3:%.*]] = add <4 x i32> [[TMP2]], [[TMP2]]
; CHECK-NEXT:    [[RESULT:%.*]] = bitcast <4 x i32> [[TMP3]] to <8 x i16>
; CHECK-NEXT:    ret <8 x i16> [[RESULT]]
;
  %lo = shufflevector <8 x i16> %a, <8 x i16> poison, <4 x i32> <i32 1, i32 2, i32 3, i32 4>
  %hi = shufflevector <8 x i16> %a, <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %bc_lo = bitcast <4 x i16> %lo to <2 x i32>
  %bc_hi = bitcast <4 x i16> %hi to <2 x i32>
  %add_lo = add <2 x i32> %bc_lo, %bc_lo
  %add_hi = add <2 x i32> %bc_hi, %bc_hi
  %res_lo = bitcast <2 x i32> %add_lo to <4 x i16>
  %res_hi = bitcast <2 x i32> %add_hi to <4 x i16>
  %result = shufflevector <4 x i16> %res_lo, <4 x i16> %res_hi, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i16> %result
}

; Regression test: bitcast with non-divisible shuffle output size must not crash.
define <3 x i32> @bitcast_widening_non_divisible(<2 x i64> %x) {
; CHECK-LABEL: @bitcast_widening_non_divisible(
; CHECK-NEXT:    [[BC:%.*]] = bitcast <2 x i64> [[X:%.*]] to <4 x i32>
; CHECK-NEXT:    [[R:%.*]] = shufflevector <4 x i32> [[BC]], <4 x i32> poison, <3 x i32> <i32 0, i32 1, i32 2>
; CHECK-NEXT:    ret <3 x i32> [[R]]
;
  %bc = bitcast <2 x i64> %x to <4 x i32>
  %r = shufflevector <4 x i32> %bc, <4 x i32> poison, <3 x i32> <i32 0, i32 1, i32 2>
  ret <3 x i32> %r
}
