; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -O2 -S < %s | FileCheck %s

; Test that no optimization run at -O2 before InstCombine moves the loads into
; the exit block, as this causes unnecessary address escapes with pointer field
; protection.

define ptr @phi_prot_ptr(i1 %sel, ptr %p1, ptr %p2) {
; CHECK-LABEL: define ptr @phi_prot_ptr(
; CHECK-SAME: i1 [[SEL:%.*]], ptr readonly captures(none) [[P1:%.*]], ptr readonly captures(none) [[P2:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    br i1 [[SEL]], label %[[T:.*]], label %[[F:.*]]
; CHECK:       [[T]]:
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P1]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[TMP1]] to i64
; CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.ptrauth.auth(i64 [[TMP2]], i32 2, i64 1)
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[F]]:
; CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[P2]], align 8
; CHECK-NEXT:    [[TMP5:%.*]] = ptrtoint ptr [[TMP4]] to i64
; CHECK-NEXT:    [[TMP6:%.*]] = tail call i64 @llvm.ptrauth.auth(i64 [[TMP5]], i32 2, i64 2)
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RETVAL_IN:%.*]] = phi i64 [ [[TMP3]], %[[T]] ], [ [[TMP6]], %[[F]] ]
; CHECK-NEXT:    [[RETVAL:%.*]] = inttoptr i64 [[RETVAL_IN]] to ptr
; CHECK-NEXT:    ret ptr [[RETVAL]]
;
  br i1 %sel, label %t, label %f

t:
  %protp1 = call ptr @llvm.protected.field.ptr.p0(ptr %p1, i64 1, i1 true)
  %load1 = load ptr, ptr %protp1
  br label %exit

f:
  %protp2 = call ptr @llvm.protected.field.ptr.p0(ptr %p2, i64 2, i1 true)
  %load2 = load ptr, ptr %protp2
  br label %exit

exit:
  %retval = phi ptr [ %load1, %t ], [ %load2, %f ]
  ret ptr %retval
}
