import("//llvm/utils/gn/build/symbol_exports.gni")

symbol_exports("exports") {
  exports_file = "libCASPluginTest.exports"
}

shared_library("CASPluginTest") {
  if (current_os == "win") {
    output_dir = get_label_info("//llvm", "target_out_dir") + "/bin"
  } else {
    output_dir = get_label_info("//llvm", "target_out_dir") + "/lib"
  }
  output_name = "CASPluginTest"
  deps = [
    ":exports",
    "//llvm/lib/CAS",
    "//llvm/lib/Support",
  ]
  sources = [ "libCASPluginTest.cpp" ]

  if (current_os != "mac" && current_os != "win") {
    cflags = [ "-fPIC" ]
  }
}
