// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// RUN: %clang_cc1 -triple wasm64 -fsanitize=memtag -target-feature +reference-types -disable-O0-optnone -O3 -emit-llvm %s -o - | opt -S -passes=mem2reg | FileCheck %s
// REQUIRES: webassembly-registered-target

// CHECK-LABEL: define {{[^@]+}}@test_builtin_wasm_memory_randomtag
// CHECK-SAME: (ptr noundef readnone [[INDEX:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = {{[^@]+}}call ptr @llvm.wasm.memory.randomtag(ptr [[INDEX:%.*]])
// CHECK-NEXT:    ret ptr %0
//
void* test_builtin_wasm_memtag_random(void *p) {
  return __builtin_wasm_memtag_random(p);
}

// CHECK-LABEL: define {{[^@]+}}@test_builtin_wasm_memory_copytag
// CHECK-SAME: (ptr noundef readnone [[INDEX:%.*]], ptr noundef readnone [[INDEX:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = {{[^@]+}}call ptr @llvm.wasm.memory.copytag(ptr [[INDEX:%.*]], ptr [[INDEX:%.*]])
// CHECK-NEXT:    ret ptr %0
//
void* test_builtin_wasm_memory_copytag(void *p1, void *p2) {
  return __builtin_wasm_memory_copytag(p1, p2);
}

// CHECK-LABEL: define {{[^@]+}}@test_builtin_wasm_memory_subtag
// CHECK-SAME: (ptr noundef readnone [[INDEX:%.*]], ptr noundef readnone [[INDEX:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = {{[^@]+}}call i64 @llvm.wasm.memory.subtag.i64(ptr [[INDEX:%.*]], ptr [[INDEX:%.*]])
// CHECK-NEXT:    ret i64 %0
//
__PTRDIFF_TYPE__ test_builtin_wasm_memory_subtag(void *p1, void *p2) {
  return __builtin_wasm_memory_subtag(p1, p2);
}

// CHECK-LABEL: define {{[^@]+}}@test_builtin_wasm_memory_loadtag
// CHECK-SAME: (ptr noundef readonly [[INDEX:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = {{[^@]+}}call ptr @llvm.wasm.memory.loadtag(ptr [[INDEX:%.*]])
// CHECK-NEXT:    ret ptr %0
//
void* test_builtin_wasm_memory_loadtag(void *p) {
  return __builtin_wasm_memory_loadtag(p);
}

// CHECK-LABEL: define {{[^@]+}}@test_builtin_wasm_memory_storetag
// CHECK-SAME: (ptr noundef [[INDEX:%.*]], i64 noundef [[INDEX:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    {{[^@]+}}call void @llvm.wasm.memory.storetag.i64(ptr [[INDEX:%.*]], i64 [[INDEX:%.*]])
// CHECK-NEXT:    ret void
//
void test_builtin_wasm_memory_storetag(void *p, __SIZE_TYPE__ b16) {
  __builtin_wasm_memory_storetag(p, b16);
}

// CHECK-LABEL: define {{[^@]+}}@test_builtin_wasm_memory_storeztag
// CHECK-SAME: (ptr noundef [[INDEX:%.*]], i64 noundef [[INDEX:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    {{[^@]+}}call void @llvm.wasm.memory.storeztag.i64(ptr [[INDEX:%.*]], i64 [[INDEX:%.*]])
// CHECK-NEXT:    ret void
//
void test_builtin_wasm_memory_storeztag(void *p, __SIZE_TYPE__ b16) {
  __builtin_wasm_memory_storeztag(p, b16);
}

// CHECK-LABEL: define {{[^@]+}}@test_builtin_wasm_memory_store1tag
// CHECK-SAME: (ptr noundef [[INDEX:%.*]], i64 noundef [[INDEX:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    {{[^@]+}}call void @llvm.wasm.memory.store1tag.i64(ptr [[INDEX:%.*]], i64 [[INDEX:%.*]])
// CHECK-NEXT:    ret void
//
void test_builtin_wasm_memory_store1tag(void *p, __SIZE_TYPE__ b16) {
  __builtin_wasm_memory_store1tag(p, b16);
}

// CHECK-LABEL: define {{[^@]+}}@test_builtin_wasm_memory_storez1tag
// CHECK-SAME: (ptr noundef [[INDEX:%.*]], i64 noundef [[INDEX:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    {{[^@]+}}call void @llvm.wasm.memory.storez1tag.i64(ptr [[INDEX:%.*]], i64 [[INDEX:%.*]])
// CHECK-NEXT:    ret void
//
void test_builtin_wasm_memory_storez1tag(void *p, __SIZE_TYPE__ b16) {
  __builtin_wasm_memory_storez1tag(p, b16);
}

// CHECK-LABEL: define {{[^@]+}}@test_builtin_wasm_memory_randomstoretag
// CHECK-SAME: (ptr noundef [[INDEX:%.*]], i64 noundef [[INDEX:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    {{[^@]+}}call ptr @llvm.wasm.memory.randomstoretag.i64(ptr [[INDEX:%.*]], i64 [[INDEX:%.*]])
// CHECK-NEXT:    ret ptr
//
void* test_builtin_wasm_memory_randomstoretag(void *p, __SIZE_TYPE__ b16) {
  return __builtin_wasm_memory_randomstoretag(p, b16);
}

// CHECK-LABEL: define {{[^@]+}}@test_builtin_wasm_memory_randomstoreztag
// CHECK-SAME: (ptr noundef [[INDEX:%.*]], i64 noundef [[INDEX:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    {{[^@]+}}call ptr @llvm.wasm.memory.randomstoreztag.i64(ptr [[INDEX:%.*]], i64 [[INDEX:%.*]])
// CHECK-NEXT:    ret ptr
//
void* test_builtin_wasm_memory_randomstoreztag(void *p, __SIZE_TYPE__ b16) {
  return __builtin_wasm_memory_randomstoreztag(p, b16);
}

// CHECK-LABEL: define {{[^@]+}}@test_builtin_wasm_memory_randomstore1tag
// CHECK-SAME: (ptr noundef [[INDEX:%.*]], i64 noundef [[INDEX:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    {{[^@]+}}call ptr @llvm.wasm.memory.randomstore1tag.i64(ptr [[INDEX:%.*]], i64 [[INDEX:%.*]])
// CHECK-NEXT:    ret ptr
//
void* test_builtin_wasm_memory_randomstore1tag(void *p, __SIZE_TYPE__ b16) {
  return __builtin_wasm_memory_randomstore1tag(p, b16);
}

// CHECK-LABEL: define {{[^@]+}}@test_builtin_wasm_memory_randomstorez1tag
// CHECK-SAME: (ptr noundef [[INDEX:%.*]], i64 noundef [[INDEX:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    {{[^@]+}}call ptr @llvm.wasm.memory.randomstorez1tag.i64(ptr [[INDEX:%.*]], i64 [[INDEX:%.*]])
// CHECK-NEXT:    ret ptr
//
void* test_builtin_wasm_memory_randomstorez1tag(void *p, __SIZE_TYPE__ b16) {
  return __builtin_wasm_memory_randomstorez1tag(p, b16);
}
