// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple wasm32-unknown-unknown -target-feature +reference-types -emit-llvm -o - %s | FileCheck %s

// CHECK-LABEL: define ptr addrspace(10) @test_externref(
// CHECK-SAME: ptr addrspace(10) [[INPUT:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[INPUT_ADDR:%.*]] = alloca ptr addrspace(10), align 1, addrspace(1)
// CHECK-NEXT:    [[LOCAL:%.*]] = alloca ptr addrspace(10), align 1, addrspace(1)
// CHECK-NEXT:    store ptr addrspace(10) [[INPUT]], ptr addrspace(1) [[INPUT_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(10), ptr addrspace(1) [[INPUT_ADDR]], align 1
// CHECK-NEXT:    store ptr addrspace(10) [[TMP0]], ptr addrspace(1) [[LOCAL]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr addrspace(10), ptr addrspace(1) [[LOCAL]], align 1
// CHECK-NEXT:    ret ptr addrspace(10) [[TMP1]]
//
__externref_t test_externref(__externref_t input) {
  __externref_t local = input;
  return local;
}

typedef void (*__funcref funcref_t)();
// CHECK-LABEL: define ptr addrspace(20) @test_funcref(
// CHECK-SAME: ptr addrspace(20) noundef [[INPUT:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[INPUT_ADDR:%.*]] = alloca ptr addrspace(20), align 4, addrspace(1)
// CHECK-NEXT:    [[LOCAL:%.*]] = alloca ptr addrspace(20), align 4, addrspace(1)
// CHECK-NEXT:    store ptr addrspace(20) [[INPUT]], ptr addrspace(1) [[INPUT_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(20), ptr addrspace(1) [[INPUT_ADDR]], align 4
// CHECK-NEXT:    store ptr addrspace(20) [[TMP0]], ptr addrspace(1) [[LOCAL]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr addrspace(20), ptr addrspace(1) [[LOCAL]], align 4
// CHECK-NEXT:    ret ptr addrspace(20) [[TMP1]]
//
funcref_t test_funcref(funcref_t input) {
  funcref_t local = input;
  return local;
}
