; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple amdgcn-unknown-amdhsa -mcpu=gfx906 -passes=amdgpu-codegenprepare < %s | FileCheck --check-prefixes=CHECK,GFX9 %s
; RUN: opt -S -mtriple amdgcn-unknown-amdhsa -mcpu=gfx1030 -passes=amdgpu-codegenprepare < %s | FileCheck --check-prefixes=CHECK,GFX10 %s

; Test negative cases where mbcnt optimizations should NOT be applied

; =============================================================================
; NO WORK GROUP SIZE METADATA
; =============================================================================

; Test with no reqd_work_group_size
define i32 @test_mbcnt_no_work_group_size() {
; GFX9-LABEL: define i32 @test_mbcnt_no_work_group_size(
; GFX9-SAME: ) #[[ATTR0:[0-9]+]] {
; GFX9-NEXT:  [[ENTRY:.*:]]
; GFX9-NEXT:    [[A:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX9-NEXT:    [[B:%.*]] = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 [[A]])
; GFX9-NEXT:    ret i32 [[B]]
;
; GFX10-LABEL: define i32 @test_mbcnt_no_work_group_size(
; GFX10-SAME: ) #[[ATTR0:[0-9]+]] {
; GFX10-NEXT:  [[ENTRY:.*:]]
; GFX10-NEXT:    [[A:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX10-NEXT:    [[B:%.*]] = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 [[A]])
; GFX10-NEXT:    ret i32 [[B]]
;
entry:
  %a = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
  %b = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 %a)
  ret i32 %b
}

; Test mbcnt.lo with no work group size
define i32 @test_mbcnt_lo_no_work_group_size() {
; GFX9-LABEL: define i32 @test_mbcnt_lo_no_work_group_size(
; GFX9-SAME: ) #[[ATTR0]] {
; GFX9-NEXT:  [[ENTRY:.*:]]
; GFX9-NEXT:    [[A:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX9-NEXT:    ret i32 [[A]]
;
; GFX10-LABEL: define i32 @test_mbcnt_lo_no_work_group_size(
; GFX10-SAME: ) #[[ATTR0]] {
; GFX10-NEXT:  [[ENTRY:.*:]]
; GFX10-NEXT:    [[A:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX10-NEXT:    ret i32 [[A]]
;
entry:
  %a = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
  ret i32 %a
}

; =============================================================================
; PARTIAL MASKS AND NON-STANDARD PATTERNS
; =============================================================================

; Test with partial mask
define i32 @test_mbcnt_partial_mask() !reqd_work_group_size !0 {
; GFX9-LABEL: define i32 @test_mbcnt_partial_mask(
; GFX9-SAME: ) #[[ATTR0:[0-9]+]] !reqd_work_group_size [[META0:![0-9]+]] {
; GFX9-NEXT:  [[ENTRY:.*:]]
; GFX9-NEXT:    [[A:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 65535, i32 0)
; GFX9-NEXT:    [[B:%.*]] = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 [[A]])
; GFX9-NEXT:    ret i32 [[B]]
;
; GFX10-LABEL: define i32 @test_mbcnt_partial_mask(
; GFX10-SAME: ) #[[ATTR0:[0-9]+]] !reqd_work_group_size [[META0:![0-9]+]] {
; GFX10-NEXT:  [[ENTRY:.*:]]
; GFX10-NEXT:    [[A:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 65535, i32 0)
; GFX10-NEXT:    [[B:%.*]] = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 [[A]])
; GFX10-NEXT:    ret i32 [[B]]
;
entry:
  %a = call i32 @llvm.amdgcn.mbcnt.lo(i32 65535, i32 0)
  %b = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 %a)
  ret i32 %b
}

; Test with non-zero base
define i32 @test_mbcnt_non_zero_base() !reqd_work_group_size !0 {
; GFX9-LABEL: define i32 @test_mbcnt_non_zero_base(
; GFX9-SAME: ) #[[ATTR0]] !reqd_work_group_size [[META0]] {
; GFX9-NEXT:  [[ENTRY:.*:]]
; GFX9-NEXT:    [[A:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 5)
; GFX9-NEXT:    [[B:%.*]] = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 [[A]])
; GFX9-NEXT:    ret i32 [[B]]
;
; GFX10-LABEL: define i32 @test_mbcnt_non_zero_base(
; GFX10-SAME: ) #[[ATTR0]] !reqd_work_group_size [[META0]] {
; GFX10-NEXT:  [[ENTRY:.*:]]
; GFX10-NEXT:    [[A:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 5)
; GFX10-NEXT:    [[B:%.*]] = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 [[A]])
; GFX10-NEXT:    ret i32 [[B]]
;
entry:
  %a = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 5)
  %b = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 %a)
  ret i32 %b
}

; =============================================================================
; COPY OPTIMIZATION NEGATIVE CASES
; =============================================================================

; Test with no work group size
define i32 @test_mbcnt_hi_copy_no_wgs(i32 %val) {
; GFX9-LABEL: define i32 @test_mbcnt_hi_copy_no_wgs(
; GFX9-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX9-NEXT:  [[ENTRY:.*:]]
; GFX9-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 [[VAL]])
; GFX9-NEXT:    ret i32 [[RESULT]]
;
; GFX10-LABEL: define i32 @test_mbcnt_hi_copy_no_wgs(
; GFX10-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX10-NEXT:  [[ENTRY:.*:]]
; GFX10-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 [[VAL]])
; GFX10-NEXT:    ret i32 [[RESULT]]
;
entry:
  %result = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 %val)
  ret i32 %result
}

; Test with work group size = not a wave multiple (48)
define i32 @test_mbcnt_hi_copy_non_wave_multiple(i32 %val) !reqd_work_group_size !1 {
; GFX9-LABEL: define i32 @test_mbcnt_hi_copy_non_wave_multiple(
; GFX9-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] !reqd_work_group_size [[META1:![0-9]+]] {
; GFX9-NEXT:  [[ENTRY:.*:]]
; GFX9-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 [[VAL]])
; GFX9-NEXT:    ret i32 [[RESULT]]
;
; GFX10-LABEL: define i32 @test_mbcnt_hi_copy_non_wave_multiple(
; GFX10-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] !reqd_work_group_size [[META1:![0-9]+]] {
; GFX10-NEXT:  [[ENTRY:.*:]]
; GFX10-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 [[VAL]])
; GFX10-NEXT:    ret i32 [[RESULT]]
;
entry:
  %result = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 %val)
  ret i32 %result
}

; Test with zero mask
define i32 @test_mbcnt_hi_copy_zero_mask(i32 %val) !reqd_work_group_size !0 {
; GFX9-LABEL: define i32 @test_mbcnt_hi_copy_zero_mask(
; GFX9-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] !reqd_work_group_size [[META0]] {
; GFX9-NEXT:  [[ENTRY:.*:]]
; GFX9-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.mbcnt.hi(i32 0, i32 [[VAL]])
; GFX9-NEXT:    ret i32 [[RESULT]]
;
; GFX10-LABEL: define i32 @test_mbcnt_hi_copy_zero_mask(
; GFX10-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] !reqd_work_group_size [[META0]] {
; GFX10-NEXT:  [[ENTRY:.*:]]
; GFX10-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.mbcnt.hi(i32 0, i32 [[VAL]])
; GFX10-NEXT:    ret i32 [[RESULT]]
;
entry:
  %result = call i32 @llvm.amdgcn.mbcnt.hi(i32 0, i32 %val)
  ret i32 %result
}

; =============================================================================
; METADATA
; =============================================================================

!0 = !{i32 64, i32 1, i32 1}   ; X=64 (wave64 or 2*wave32)
!1 = !{i32 48, i32 1, i32 1}   ; X=48 (not wave multiple)

; =============================================================================
; FUNCTION DECLARATIONS
; =============================================================================

declare i32 @llvm.amdgcn.mbcnt.lo(i32, i32) #0
declare i32 @llvm.amdgcn.mbcnt.hi(i32, i32) #0

attributes #0 = { nounwind readnone speculatable willreturn }
;.
; GFX9: [[META0]] = !{i32 64, i32 1, i32 1}
; GFX9: [[META1]] = !{i32 48, i32 1, i32 1}
;.
; GFX10: [[META0]] = !{i32 64, i32 1, i32 1}
; GFX10: [[META1]] = !{i32 48, i32 1, i32 1}
;.
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
