# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("@rules_python//python:defs.bzl", "py_binary")

package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

# Invoked at build time to generate the kmp_i18n_id.inc and
# kmp_i18n_default.inc message catalog headers.
py_binary(
    name = "message-converter",
    srcs = [
        "libomputils.py",
        "message-converter.py",
    ],
    imports = ["."],
    main = "message-converter.py",
)
