// RUN: fir-opt --split-input-file --mif-convert %s | FileCheck %s

module attributes {dlti.dl_spec = #dlti.dl_spec<!llvm.ptr<270> = dense<32> : vector<4xi64>, !llvm.ptr<271> = dense<32> : vector<4xi64>, !llvm.ptr<272> = dense<64> : vector<4xi64>, i64 = dense<64> : vector<2xi64>, i128 = dense<128> : vector<2xi64>, f80 = dense<128> : vector<2xi64>, !llvm.ptr = dense<64> : vector<4xi64>, i1 = dense<8> : vector<2xi64>, i8 = dense<8> : vector<2xi64>, i16 = dense<16> : vector<2xi64>, i32 = dense<32> : vector<2xi64>, f16 = dense<16> : vector<2xi64>, f64 = dense<64> : vector<2xi64>, f128 = dense<128> : vector<2xi64>, "dlti.endianness" = "little", "dlti.mangling_mode" = "e", "dlti.legal_int_widths" = array<i32: 8, 16, 32, 64>, "dlti.stack_alignment" = 128 : i64>, fir.defaultkind = "a1c4d8i4l4r4", fir.kindmap = "", llvm.data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128", llvm.ident = "flang version 22.0.0 (git@github.com:SiPearl/llvm-project.git 666e4313ebc03587f27774139ad8f780bac15c3e)", llvm.target_triple = "x86_64-unknown-linux-gnu"} {
  func.func @_QQmain() attributes {fir.bindc_name = "TEST_INIT"} {
    %0 = fir.dummy_scope : !fir.dscope
    return
  }
  func.func private @_FortranAProgramStart(i32, !llvm.ptr, !llvm.ptr, !llvm.ptr)
  func.func private @_FortranAProgramEndStatement()
  func.func @main(%arg0: i32, %arg1: !llvm.ptr, %arg2: !llvm.ptr) -> i32 {
    %0 = fir.zero_bits !fir.ref<tuple<i32, !fir.ref<!fir.array<0xtuple<!fir.ref<i8>, !fir.ref<i8>>>>>>
    fir.call @_FortranAProgramStart(%arg0, %arg1, %arg2, %0) fastmath<contract> : (i32, !llvm.ptr, !llvm.ptr, !fir.ref<tuple<i32, !fir.ref<!fir.array<0xtuple<!fir.ref<i8>, !fir.ref<i8>>>>>>) -> ()
    %1 = mif.init -> i32
    fir.call @_QQmain() fastmath<contract> : () -> ()
    fir.call @_FortranAProgramEndStatement() fastmath<contract> : () -> ()
    %c0_i32 = arith.constant 0 : i32
    return %c0_i32 : i32
  }
}

// CHECK-LABEL: func.func @main
// CHECK: %[[VAL_0:.*]] = fir.alloca i32
// CHECK: %[[VAL_1:.*]] = fir.address_of(@_QMprifPprif_stop_termination_wrapper) : (i32) -> () 
// CHECK: fir.call @_FortranARegisterImagesNormalEndCallback({{.*}}) : (!fir.llvm_ptr<() -> ()>) -> ()
// CHECK: %[[VAL_2:.*]] = fir.address_of(@_QMprifPprif_error_stop_termination_wrapper) : (i32) -> () 
// CHECK: fir.call @_FortranARegisterImagesErrorCallback({{.*}}) : (!fir.llvm_ptr<() -> ()>) -> ()
// CHECK: %[[VAL_3:.*]] = fir.address_of(@_QMprifPprif_fail_image_termination_wrapper) : () -> ()
// CHECK: fir.call @_FortranARegisterFailImageCallback({{.*}}) : (!fir.llvm_ptr<() -> ()>) -> ()
// CHECK: fir.call @_QMprifPprif_init(%[[VAL_0]]) : (!fir.ref<i32>) -> ()

// CHECK:  func.func private @_QMprifPprif_stop_termination_wrapper(%[[ARG0:.*]]: i32)
// CHECK:  %[[VAL_0:.*]] = fir.alloca i32
// CHECK:  %[[VAL_1:.*]] = fir.alloca i1
// CHECK:  %[[TRUE:.*]] = arith.constant true
// CHECK:  fir.store %[[TRUE]] to %[[VAL_1]] : !fir.ref<i1>
// CHECK:  %[[VAL_2:.*]] = fir.absent !fir.boxchar<1>
// CHECK:  fir.store %[[ARG0]] to %[[VAL_0]] : !fir.ref<i32>
// CHECK:  fir.call @_QMprifPprif_stop(%[[VAL_1]], %[[VAL_0]], %[[VAL_2]]) : (!fir.ref<i1>, !fir.ref<i32>, !fir.boxchar<1>) -> ()
// CHECK:  return

// CHECK:  func.func private @_QMprifPprif_error_stop_termination_wrapper(%[[ARG0:.*]]: i32)
// CHECK:  %[[VAL_0:.*]] = fir.alloca i32
// CHECK:  %[[VAL_1:.*]] = fir.alloca i1
// CHECK:  %[[TRUE:.*]] = arith.constant true 
// CHECK:  fir.store %[[TRUE]] to %[[VAL_1]] : !fir.ref<i1>
// CHECK:  %[[VAL_2:.*]] = fir.absent !fir.boxchar<1>
// CHECK:  fir.store %[[ARG0]] to %[[VAL_0]] : !fir.ref<i32>
// CHECK:  fir.call @_QMprifPprif_error_stop(%[[VAL_1]], %[[VAL_0]], %[[VAL_2]]) : (!fir.ref<i1>, !fir.ref<i32>, !fir.boxchar<1>) -> ()
// CHECK:  return

// CHECK-LABEL:  func.func private @_QMprifPprif_fail_image_termination_wrapper
// CHECK:  fir.call @_QMprifPprif_fail_image() : () -> ()
// CHECK:  return

