; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -loop-reduce %s -o - | FileCheck %s

;; Ensure that debug value salvaging does not crash when encountering
;; SCEVPtrToAddrExpr in the SCEV expression tree.


target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define i64 @test(ptr %p) {
; CHECK-LABEL: define i64 @test(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[P1:%.*]] = ptrtoaddr ptr [[P]] to i64
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[P1]], -1
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[LSR_IV:%.*]] = phi i64 [ [[LSR_IV_NEXT1:%.*]], %[[LOOP]] ], [ [[TMP0]], %[[ENTRY]] ]
; CHECK-NEXT:      #dbg_value(i64 [[LSR_IV]], [[META4:![0-9]+]], !DIExpression(DW_OP_plus_uconst, 1, DW_OP_stack_value), [[META8:![0-9]+]])
; CHECK-NEXT:    [[LSR_IV_NEXT1]] = add i64 [[LSR_IV]], 1
; CHECK-NEXT:    br i1 false, label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[LSR_IV_NEXT:%.*]] = phi i64 [ [[LSR_IV_NEXT1]], %[[LOOP]] ]
; CHECK-NEXT:    ret i64 [[LSR_IV_NEXT]]
;
entry:
  br label %loop

loop:
  %iv = phi ptr [ %p, %entry ], [ %iv.next, %loop ]
  %addr = ptrtoaddr ptr %iv to i64
    #dbg_value(i64 %addr, !4, !DIExpression(), !9)
  %iv.next = getelementptr i8, ptr %iv, i64 1
  br i1 false, label %exit, label %loop

exit:
  ret i64 %addr
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C11, file: !1, producer: "clang", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, retainedTypes: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "test.c", directory: "/tmp")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = !DILocalVariable(name: "addr", scope: !5, file: !1, line: 2, type: !7)
!5 = distinct !DISubprogram(name: "test", scope: !1, file: !1, line: 1, type: !6, scopeLine: 1, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !2)
!6 = !DISubroutineType(types: !2)
!7 = !DIBasicType(name: "long", size: 64, encoding: DW_ATE_signed)
!9 = !DILocation(line: 2, scope: !5)
;.
; CHECK: [[META0:![0-9]+]] = distinct !DICompileUnit(language: DW_LANG_C11, file: [[META1:![0-9]+]], producer: "clang", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, retainedTypes: [[META2:![0-9]+]], splitDebugInlining: false, nameTableKind: None)
; CHECK: [[META1]] = !DIFile(filename: "{{.*}}test.c", directory: {{.*}})
; CHECK: [[META2]] = !{}
; CHECK: [[META4]] = !DILocalVariable(name: "addr", scope: [[META5:![0-9]+]], file: [[META1]], line: 2, type: [[META7:![0-9]+]])
; CHECK: [[META5]] = distinct !DISubprogram(name: "test", scope: [[META1]], file: [[META1]], line: 1, type: [[META6:![0-9]+]], scopeLine: 1, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: [[META0]], retainedNodes: [[META2]])
; CHECK: [[META6]] = !DISubroutineType(types: [[META2]])
; CHECK: [[META7]] = !DIBasicType(name: "long", size: 64, encoding: DW_ATE_signed)
; CHECK: [[META8]] = !DILocation(line: 2, scope: [[META5]])
;.
