; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-reduce -S %s | FileCheck %s
;
; Verify that LSR keeps ICmpZero comparisons in the integer domain when the
; original operands are pointers, avoiding inttoptr casts entirely. The loop
; has three pointer IVs sharing the same stride; LSR should produce a single
; integer IV and compare it directly against the precomputed bound.
; Target-dependent because TTI must report that scaled addressing is legal.

target triple = "x86_64-unknown-linux-gnu"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"

define void @test_no_inttoptr_casts(ptr %base1, ptr %base2, ptr %base3, i64 %n) {
; CHECK-LABEL: @test_no_inttoptr_casts(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = shl i64 [[N:%.*]], 3
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[LSR_IV:%.*]] = phi i64 [ [[LSR_IV_NEXT:%.*]], [[LOOP_LATCH:%.*]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[BASE1:%.*]], i64 [[LSR_IV]]
; CHECK-NEXT:    [[SCEVGEP1:%.*]] = getelementptr i8, ptr [[BASE2:%.*]], i64 [[LSR_IV]]
; CHECK-NEXT:    [[SCEVGEP2:%.*]] = getelementptr i8, ptr [[BASE3:%.*]], i64 [[LSR_IV]]
; CHECK-NEXT:    [[CMP_EXIT:%.*]] = icmp eq i64 [[TMP0]], [[LSR_IV]]
; CHECK-NEXT:    br i1 [[CMP_EXIT]], label [[CHECK:%.*]], label [[BODY:%.*]]
; CHECK:       check:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ne i64 [[TMP0]], [[LSR_IV]]
; CHECK-NEXT:    [[CMP3:%.*]] = icmp ne i64 [[TMP0]], [[LSR_IV]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP1]], i1 true, i1 [[CMP3]]
; CHECK-NEXT:    br i1 [[SEL]], label [[BODY]], label [[EXIT:%.*]]
; CHECK:       body:
; CHECK-NEXT:    [[V1:%.*]] = load i64, ptr [[SCEVGEP]], align 8
; CHECK-NEXT:    [[V2:%.*]] = load i64, ptr [[SCEVGEP1]], align 8
; CHECK-NEXT:    [[SUM:%.*]] = add i64 [[V1]], [[V2]]
; CHECK-NEXT:    store i64 [[SUM]], ptr [[SCEVGEP2]], align 8
; CHECK-NEXT:    br label [[LOOP_LATCH]]
; CHECK:       loop.latch:
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add i64 [[LSR_IV]], 8
; CHECK-NEXT:    br label [[LOOP]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %bound1 = getelementptr i64, ptr %base1, i64 %n
  %bound2 = getelementptr i64, ptr %base2, i64 %n
  %bound3 = getelementptr i64, ptr %base3, i64 %n
  br label %loop

loop:
  %p1 = phi ptr [ %base1, %entry ], [ %p1.next, %loop.latch ]
  %p2 = phi ptr [ %base2, %entry ], [ %p2.next, %loop.latch ]
  %p3 = phi ptr [ %base3, %entry ], [ %p3.next, %loop.latch ]
  %cmp.exit = icmp eq ptr %p2, %bound2
  br i1 %cmp.exit, label %check, label %body

check:
  %cmp1 = icmp ne ptr %p1, %bound1
  %cmp3 = icmp ne ptr %p3, %bound3
  %sel = select i1 %cmp1, i1 true, i1 %cmp3
  br i1 %sel, label %body, label %exit

body:
  %v1 = load i64, ptr %p1, align 8
  %v2 = load i64, ptr %p2, align 8
  %sum = add i64 %v1, %v2
  store i64 %sum, ptr %p3, align 8
  br label %loop.latch

loop.latch:
  %p1.next = getelementptr inbounds i8, ptr %p1, i64 8
  %p2.next = getelementptr inbounds i8, ptr %p2, i64 8
  %p3.next = getelementptr inbounds i8, ptr %p3, i64 8
  br label %loop

exit:
  ret void
}
