; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=x86_64 -passes=loop-reduce %s | FileCheck %s

declare i32 @foo(i32)

define i32 @test(i32 %count.limit, i32 %limit32, i64 %limit64, i1 %select.i32, i1 %outer.cond) {
; CHECK-LABEL: define i32 @test(
; CHECK-SAME: i32 [[COUNT_LIMIT:%.*]], i32 [[LIMIT32:%.*]], i64 [[LIMIT64:%.*]], i1 [[SELECT_I32:%.*]], i1 [[OUTER_COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER_HEADER:.*]]
; CHECK:       [[OUTER_HEADER_LOOPEXIT:.*]]:
; CHECK-NEXT:    [[SIBLING_ACC_NEXT_LCSSA:%.*]] = phi i32 [ [[SIBLING_ACC_NEXT:%.*]], %[[SIBLING_LOOP:.*]] ]
; CHECK-NEXT:    br label %[[OUTER_HEADER]]
; CHECK:       [[OUTER_HEADER]]:
; CHECK-NEXT:    [[OUTER_ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[SIBLING_ACC_NEXT_LCSSA]], %[[OUTER_HEADER_LOOPEXIT]] ]
; CHECK-NEXT:    br i1 [[OUTER_COND]], label %[[COUNT_LOOP_PREHEADER:.*]], label %[[EXIT:.*]]
; CHECK:       [[COUNT_LOOP_PREHEADER]]:
; CHECK-NEXT:    br label %[[COUNT_LOOP:.*]]
; CHECK:       [[COUNT_LOOP]]:
; CHECK-NEXT:    [[LSR_IV:%.*]] = phi i32 [ -1, %[[COUNT_LOOP_PREHEADER]] ], [ [[LSR_IV_NEXT:%.*]], %[[COUNT_LOOP]] ]
; CHECK-NEXT:    [[COUNT_ACC:%.*]] = phi i32 [ [[COUNT_ACC_NEXT:%.*]], %[[COUNT_LOOP]] ], [ [[OUTER_ACC]], %[[COUNT_LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[SIBLING_START:%.*]] = phi i32 [ 1, %[[COUNT_LOOP]] ], [ 0, %[[COUNT_LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[COUNT_ACC_NEXT]] = call i32 @foo(i32 [[COUNT_ACC]])
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add i32 [[LSR_IV]], 1
; CHECK-NEXT:    [[COUNT_CMP:%.*]] = icmp ult i32 [[LSR_IV_NEXT]], [[COUNT_LIMIT]]
; CHECK-NEXT:    br i1 [[COUNT_CMP]], label %[[COUNT_LOOP]], label %[[SIBLING_LOOP_PREHEADER:.*]]
; CHECK:       [[SIBLING_LOOP_PREHEADER]]:
; CHECK-NEXT:    [[SIBLING_START_LCSSA1:%.*]] = phi i32 [ [[SIBLING_START]], %[[COUNT_LOOP]] ]
; CHECK-NEXT:    [[COUNT_ACC_NEXT_LCSSA:%.*]] = phi i32 [ [[COUNT_ACC_NEXT]], %[[COUNT_LOOP]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = zext nneg i32 [[SIBLING_START_LCSSA1]] to i64
; CHECK-NEXT:    br label %[[SIBLING_LOOP]]
; CHECK:       [[SIBLING_LOOP]]:
; CHECK-NEXT:    [[SIBLING_ACC:%.*]] = phi i32 [ [[SIBLING_ACC_NEXT]], %[[SIBLING_LOOP]] ], [ [[COUNT_ACC_NEXT_LCSSA]], %[[SIBLING_LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[SIBLING_IV64:%.*]] = phi i64 [ [[SIBLING_IV64_NEXT:%.*]], %[[SIBLING_LOOP]] ], [ 0, %[[SIBLING_LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[TMP0]], [[SIBLING_IV64]]
; CHECK-NEXT:    [[TMP:%.*]] = trunc i64 [[TMP1]] to i32
; CHECK-NEXT:    [[SIBLING_CMP32:%.*]] = icmp ult i32 [[TMP]], [[LIMIT32]]
; CHECK-NEXT:    [[SIBLING_IV64_NEXT]] = add i64 [[SIBLING_IV64]], 1
; CHECK-NEXT:    [[SIBLING_CMP64:%.*]] = icmp ult i64 [[SIBLING_IV64]], [[LIMIT64]]
; CHECK-NEXT:    [[SIBLING_ACC_NEXT]] = call i32 @foo(i32 [[SIBLING_ACC]])
; CHECK-NEXT:    [[SIBLING_MORE:%.*]] = select i1 [[SELECT_I32]], i1 [[SIBLING_CMP32]], i1 [[SIBLING_CMP64]]
; CHECK-NEXT:    br i1 [[SIBLING_MORE]], label %[[SIBLING_LOOP]], label %[[OUTER_HEADER_LOOPEXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[OUTER_ACC_LCSSA:%.*]] = phi i32 [ [[OUTER_ACC]], %[[OUTER_HEADER]] ]
; CHECK-NEXT:    ret i32 [[OUTER_ACC_LCSSA]]
;
entry:
  br label %outer.header

outer.header:                                     ; preds = %sibling.loop, %entry
  %outer.acc = phi i32 [ 0, %entry ], [ %sibling.acc.next, %sibling.loop ]
  br i1 %outer.cond, label %count.loop, label %exit

count.loop:                                      ; preds = %count.loop, %outer.header
  %count.acc = phi i32 [ %outer.acc, %outer.header ], [ %count.acc.next, %count.loop ]
  %count.iv = phi i32 [ 0, %outer.header ], [ %count.iv.next, %count.loop ]
  %sibling.start = phi i32 [ 0, %outer.header ], [ 1, %count.loop ]
  %count.iv.next = add i32 %count.iv, 1
  %count.acc.next = call i32 @foo(i32 %count.acc)
  %count.cmp = icmp ult i32 %count.iv, %count.limit
  br i1 %count.cmp, label %count.loop, label %sibling.loop

sibling.loop:                                    ; preds = %sibling.loop, %count.loop
  %sibling.acc = phi i32 [ %count.acc.next, %count.loop ], [ %sibling.acc.next, %sibling.loop ]
  %sibling.iv64 = phi i64 [ %sibling.iv64.next, %sibling.loop ], [ 0, %count.loop ]
  %sibling.iv32 = phi i32 [ %sibling.iv32.next, %sibling.loop ], [ %sibling.start, %count.loop ]
  %sibling.iv32.next = add i32 %sibling.iv32, 1
  %sibling.cmp32 = icmp ult i32 %sibling.iv32, %limit32
  %sibling.iv64.next = add i64 %sibling.iv64, 1
  %sibling.cmp64 = icmp ult i64 %sibling.iv64, %limit64
  %sibling.acc.next = call i32 @foo(i32 %sibling.acc)
  %sibling.more = select i1 %select.i32, i1 %sibling.cmp32, i1 %sibling.cmp64
  br i1 %sibling.more, label %sibling.loop, label %outer.header

exit:                                             ; preds = %outer.header
  ret i32 %outer.acc
}
