; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=x86_64-unknown-linux-gnu -passes=loop-reduce %s | FileCheck %s

; LSR shouldn't introduce a redundant phi instead of reusing an existing one.
define void @reuse_existing_phi() {
; CHECK-LABEL: define void @reuse_existing_phi() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 8
; CHECK-NEXT:    [[IV_INC:%.*]] = add i64 [[IV]], 1
; CHECK-NEXT:    [[USE:%.*]] = add i64 [[IV_NEXT]], [[IV_INC]]
; CHECK-NEXT:    [[CHECK:%.*]] = icmp eq i64 [[IV_NEXT]], 100
; CHECK-NEXT:    br i1 [[CHECK]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %iv.next = add i64 %iv, 8
  %iv.inc = add i64 %iv, 1
  %use = add i64 %iv.next, %iv.inc
  %check = icmp eq i64 %iv.next, 100
  br i1 %check, label %exit, label %loop

exit:
  ret void
}
