; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=x86_64 -loop-reduce -S < %s | FileCheck %s

declare i1 @otherfn(ptr)

; The use of %ptr in %gep outside the loop uses a fixup of 8 which is
; incompatible with the use inside the loop as an argument to a call. We
; therefore can't merge the two, as it would cause an assertion failure.

define i64 @invalid_offset_outside_loop(ptr %ptr.arg, i64 %iv.arg) {
; CHECK-LABEL: define i64 @invalid_offset_outside_loop(
; CHECK-SAME: ptr [[PTR_ARG:%.*]], i64 [[IV_ARG:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[IV_ARG]], -2
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[LSR_IV:%.*]] = phi i64 [ [[LSR_IV_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ [[TMP0]], %[[ENTRY]] ]
; CHECK-NEXT:    [[PTR:%.*]] = phi ptr [ [[PTR_ARG]], %[[ENTRY]] ], [ [[PTR_NEXT:%.*]], %[[LOOP_INC]] ]
; CHECK-NEXT:    [[CALL:%.*]] = call i1 @otherfn(ptr [[PTR]])
; CHECK-NEXT:    br i1 [[CALL]], label %[[EXIT:.*]], label %[[LOOP_INC]]
; CHECK:       [[LOOP_INC]]:
; CHECK-NEXT:    [[PTR_NEXT]] = getelementptr i8, ptr [[PTR]], i64 16
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add i64 [[LSR_IV]], -1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[LSR_IV_NEXT]], -3
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[EXIT]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[LSR_IV]], 2
; CHECK-NEXT:    [[CMP1:%.*]] = icmp slt i64 [[TMP1]], [[IV_ARG]]
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i64 [[LSR_IV]], -1
; CHECK-NEXT:    [[SEL1:%.*]] = select i1 [[CMP1]], i64 1, i64 2
; CHECK-NEXT:    [[SEL2:%.*]] = select i1 [[CMP2]], i64 [[SEL1]], i64 3
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[PTR]], i64 8
; CHECK-NEXT:    store i64 [[SEL2]], ptr [[GEP]], align 8
; CHECK-NEXT:    ret i64 [[LSR_IV]]
;
entry:
  br label %loop

loop:
  %ptr = phi ptr [ %ptr.arg, %entry ], [ %ptr.next, %loop.inc ]
  %iv = phi i64 [ %iv.arg, %entry ], [ %iv.next, %loop.inc ]
  %call = call i1 @otherfn(ptr %ptr)
  br i1 %call, label %exit, label %loop.inc

loop.inc:
  %ptr.next = getelementptr i8, ptr %ptr, i64 16
  %iv.next = add i64 %iv, -1
  %exitcond = icmp eq i64 %iv, 0
  br i1 %exitcond, label %exit, label %loop

exit:
  %cmp1 = icmp slt i64 %iv, %iv.arg
  %cmp2 = icmp eq i64 %iv, 1
  %sel1 = select i1 %cmp1, i64 1, i64 2
  %sel2 = select i1 %cmp2, i64 %sel1, i64 3
  %gep = getelementptr i8, ptr %ptr, i64 8
  store i64 %sel2, ptr %gep, align 8
  %sub = add i64 %iv, -2
  ret i64 %sub
}
