; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 3
; RUN: llc -mtriple=riscv64 -mattr=+q -target-abi lp64q \
; RUN:    -global-isel -stop-after=irtranslator -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64I %s

; This file contains tests that should have identical output for the lp64 and
; lp64f ABIs.

define i64 @callee_fp128_in_regs(i64 %a, fp128 %b) nounwind {
  ; RV64I-LABEL: name: callee_fp128_in_regs
  ; RV64I: bb.1 (%ir-block.0):
  ; RV64I-NEXT:   liveins: $x10, $f10_q
  ; RV64I-NEXT: {{  $}}
  ; RV64I-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $x10
  ; RV64I-NEXT:   [[COPY1:%[0-9]+]]:_(s128) = COPY $f10_q
  ; RV64I-NEXT:   [[FPTOSI:%[0-9]+]]:_(s64) = G_FPTOSI [[COPY1]](s128)
  ; RV64I-NEXT:   [[ADD:%[0-9]+]]:_(s64) = G_ADD [[COPY]], [[FPTOSI]]
  ; RV64I-NEXT:   $x10 = COPY [[ADD]](s64)
  ; RV64I-NEXT:   PseudoRET implicit $x10
  %b_fptosi = fptosi fp128 %b to i64
  %1 = add i64 %a, %b_fptosi
  ret i64 %1
}

define i64 @caller_fp128_in_regs() nounwind {
  ; RV64I-LABEL: name: caller_fp128_in_regs
  ; RV64I: bb.1 (%ir-block.0):
  ; RV64I-NEXT:   [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 2.000000e+00
  ; RV64I-NEXT:   [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
  ; RV64I-NEXT:   [[FPEXT:%[0-9]+]]:_(s128) = G_FPEXT [[C]](s64)
  ; RV64I-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
  ; RV64I-NEXT:   $x10 = COPY [[C1]](s64)
  ; RV64I-NEXT:   $f10_q = COPY [[FPEXT]](s128)
  ; RV64I-NEXT:   PseudoCALL target-flags(riscv-call) @callee_fp128_in_regs, csr_ilp32q_lp64q, implicit-def $x1, implicit $x10, implicit $f10_q, implicit-def $x10
  ; RV64I-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
  ; RV64I-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $x10
  ; RV64I-NEXT:   $x10 = COPY [[COPY]](s64)
  ; RV64I-NEXT:   PseudoRET implicit $x10
  %1 = fpext double 2.0 to fp128
  %2 = call i64 @callee_fp128_in_regs(i64 1, fp128 %1)
  ret i64 %2
}

; Must keep define on a single line due to an update_llc_test_checks.py limitation
define i64 @callee_fp128_in_fpr_exhausted_gprs(i128 %a, i128 %b, i128 %c, i128 %d, i64 %e, fp128 %f) nounwind {
  ; RV64I-LABEL: name: callee_fp128_in_fpr_exhausted_gprs
  ; RV64I: bb.1 (%ir-block.0):
  ; RV64I-NEXT:   liveins: $x10, $x11, $x12, $x13, $x14, $x15, $x16, $x17, $f10_q
  ; RV64I-NEXT: {{  $}}
  ; RV64I-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $x10
  ; RV64I-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
  ; RV64I-NEXT:   [[MV:%[0-9]+]]:_(s128) = G_MERGE_VALUES [[COPY]](s64), [[COPY1]](s64)
  ; RV64I-NEXT:   [[COPY2:%[0-9]+]]:_(s64) = COPY $x12
  ; RV64I-NEXT:   [[COPY3:%[0-9]+]]:_(s64) = COPY $x13
  ; RV64I-NEXT:   [[MV1:%[0-9]+]]:_(s128) = G_MERGE_VALUES [[COPY2]](s64), [[COPY3]](s64)
  ; RV64I-NEXT:   [[COPY4:%[0-9]+]]:_(s64) = COPY $x14
  ; RV64I-NEXT:   [[COPY5:%[0-9]+]]:_(s64) = COPY $x15
  ; RV64I-NEXT:   [[MV2:%[0-9]+]]:_(s128) = G_MERGE_VALUES [[COPY4]](s64), [[COPY5]](s64)
  ; RV64I-NEXT:   [[COPY6:%[0-9]+]]:_(s64) = COPY $x16
  ; RV64I-NEXT:   [[COPY7:%[0-9]+]]:_(s64) = COPY $x17
  ; RV64I-NEXT:   [[MV3:%[0-9]+]]:_(s128) = G_MERGE_VALUES [[COPY6]](s64), [[COPY7]](s64)
  ; RV64I-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; RV64I-NEXT:   [[LOAD:%[0-9]+]]:_(s64) = G_LOAD [[FRAME_INDEX]](p0) :: (load (s64) from %fixed-stack.0, align 16)
  ; RV64I-NEXT:   [[COPY8:%[0-9]+]]:_(s128) = COPY $f10_q
  ; RV64I-NEXT:   [[FPTOSI:%[0-9]+]]:_(s64) = G_FPTOSI [[COPY8]](s128)
  ; RV64I-NEXT:   [[ADD:%[0-9]+]]:_(s64) = G_ADD [[LOAD]], [[FPTOSI]]
  ; RV64I-NEXT:   $x10 = COPY [[ADD]](s64)
  ; RV64I-NEXT:   PseudoRET implicit $x10
  %f_fptosi = fptosi fp128 %f to i64
  %1 = add i64 %e, %f_fptosi
  ret i64 %1
}

define i64 @caller_fp128_in_fpr_exhausted_gprs() nounwind {
  ; RV64I-LABEL: name: caller_fp128_in_fpr_exhausted_gprs
  ; RV64I: bb.1 (%ir-block.0):
  ; RV64I-NEXT:   [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 6.000000e+00
  ; RV64I-NEXT:   [[C1:%[0-9]+]]:_(s128) = G_CONSTANT i128 1
  ; RV64I-NEXT:   [[C2:%[0-9]+]]:_(s128) = G_CONSTANT i128 2
  ; RV64I-NEXT:   [[C3:%[0-9]+]]:_(s128) = G_CONSTANT i128 3
  ; RV64I-NEXT:   [[C4:%[0-9]+]]:_(s128) = G_CONSTANT i128 4
  ; RV64I-NEXT:   [[C5:%[0-9]+]]:_(s64) = G_CONSTANT i64 5
  ; RV64I-NEXT:   [[FPEXT:%[0-9]+]]:_(s128) = G_FPEXT [[C]](s64)
  ; RV64I-NEXT:   ADJCALLSTACKDOWN 8, 0, implicit-def $x2, implicit $x2
  ; RV64I-NEXT:   [[UV:%[0-9]+]]:_(s64), [[UV1:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[C1]](s128)
  ; RV64I-NEXT:   [[UV2:%[0-9]+]]:_(s64), [[UV3:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[C2]](s128)
  ; RV64I-NEXT:   [[UV4:%[0-9]+]]:_(s64), [[UV5:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[C3]](s128)
  ; RV64I-NEXT:   [[UV6:%[0-9]+]]:_(s64), [[UV7:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[C4]](s128)
  ; RV64I-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $x2
  ; RV64I-NEXT:   [[C6:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; RV64I-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s64)
  ; RV64I-NEXT:   G_STORE [[C5]](s64), [[PTR_ADD]](p0) :: (store (s64) into stack, align 16)
  ; RV64I-NEXT:   $x10 = COPY [[UV]](s64)
  ; RV64I-NEXT:   $x11 = COPY [[UV1]](s64)
  ; RV64I-NEXT:   $x12 = COPY [[UV2]](s64)
  ; RV64I-NEXT:   $x13 = COPY [[UV3]](s64)
  ; RV64I-NEXT:   $x14 = COPY [[UV4]](s64)
  ; RV64I-NEXT:   $x15 = COPY [[UV5]](s64)
  ; RV64I-NEXT:   $x16 = COPY [[UV6]](s64)
  ; RV64I-NEXT:   $x17 = COPY [[UV7]](s64)
  ; RV64I-NEXT:   $f10_q = COPY [[FPEXT]](s128)
  ; RV64I-NEXT:   PseudoCALL target-flags(riscv-call) @callee_fp128_in_fpr_exhausted_gprs, csr_ilp32q_lp64q, implicit-def $x1, implicit $x10, implicit $x11, implicit $x12, implicit $x13, implicit $x14, implicit $x15, implicit $x16, implicit $x17, implicit $f10_q, implicit-def $x10
  ; RV64I-NEXT:   ADJCALLSTACKUP 8, 0, implicit-def $x2, implicit $x2
  ; RV64I-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $x10
  ; RV64I-NEXT:   $x10 = COPY [[COPY1]](s64)
  ; RV64I-NEXT:   PseudoRET implicit $x10
  %1 = fpext double 6.0 to fp128
  %2 = call i64 @callee_fp128_in_fpr_exhausted_gprs(
      i128 1, i128 2, i128 3, i128 4, i64 5, fp128 %1)
  ret i64 %2
}

; Must keep define on a single line due to an update_llc_test_checks.py limitation
define i32 @callee_fp128_in_gpr_exhausted_fprs(fp128 %a, fp128 %b, fp128 %c, fp128 %d, fp128 %e, fp128 %f, fp128 %g, fp128 %h, fp128 %i) nounwind {
  ; RV64I-LABEL: name: callee_fp128_in_gpr_exhausted_fprs
  ; RV64I: bb.1 (%ir-block.0):
  ; RV64I-NEXT:   liveins: $x10, $x11, $f10_q, $f11_q, $f12_q, $f13_q, $f14_q, $f15_q, $f16_q, $f17_q
  ; RV64I-NEXT: {{  $}}
  ; RV64I-NEXT:   [[COPY:%[0-9]+]]:_(s128) = COPY $f10_q
  ; RV64I-NEXT:   [[COPY1:%[0-9]+]]:_(s128) = COPY $f11_q
  ; RV64I-NEXT:   [[COPY2:%[0-9]+]]:_(s128) = COPY $f12_q
  ; RV64I-NEXT:   [[COPY3:%[0-9]+]]:_(s128) = COPY $f13_q
  ; RV64I-NEXT:   [[COPY4:%[0-9]+]]:_(s128) = COPY $f14_q
  ; RV64I-NEXT:   [[COPY5:%[0-9]+]]:_(s128) = COPY $f15_q
  ; RV64I-NEXT:   [[COPY6:%[0-9]+]]:_(s128) = COPY $f16_q
  ; RV64I-NEXT:   [[COPY7:%[0-9]+]]:_(s128) = COPY $f17_q
  ; RV64I-NEXT:   [[COPY8:%[0-9]+]]:_(s64) = COPY $x10
  ; RV64I-NEXT:   [[COPY9:%[0-9]+]]:_(s64) = COPY $x11
  ; RV64I-NEXT:   [[MV:%[0-9]+]]:_(s128) = G_MERGE_VALUES [[COPY8]](s64), [[COPY9]](s64)
  ; RV64I-NEXT:   [[FPTOSI:%[0-9]+]]:_(s32) = G_FPTOSI [[COPY7]](s128)
  ; RV64I-NEXT:   [[FPTOSI1:%[0-9]+]]:_(s32) = G_FPTOSI [[MV]](s128)
  ; RV64I-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[FPTOSI]], [[FPTOSI1]]
  ; RV64I-NEXT:   [[ANYEXT:%[0-9]+]]:_(s64) = G_ANYEXT [[ADD]](s32)
  ; RV64I-NEXT:   $x10 = COPY [[ANYEXT]](s64)
  ; RV64I-NEXT:   PseudoRET implicit $x10
  %h_fptosi = fptosi fp128 %h to i32
  %i_fptosi = fptosi fp128 %i to i32
  %1 = add i32 %h_fptosi, %i_fptosi
  ret i32 %1
}

define i32 @caller_fp128_in_gpr_exhausted_fprs() nounwind {
  ; RV64I-LABEL: name: caller_fp128_in_gpr_exhausted_fprs
  ; RV64I: bb.1 (%ir-block.0):
  ; RV64I-NEXT:   [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.000000e+00
  ; RV64I-NEXT:   [[C1:%[0-9]+]]:_(s64) = G_FCONSTANT double 2.000000e+00
  ; RV64I-NEXT:   [[C2:%[0-9]+]]:_(s64) = G_FCONSTANT double 3.000000e+00
  ; RV64I-NEXT:   [[C3:%[0-9]+]]:_(s64) = G_FCONSTANT double 4.000000e+00
  ; RV64I-NEXT:   [[C4:%[0-9]+]]:_(s64) = G_FCONSTANT double 5.000000e+00
  ; RV64I-NEXT:   [[C5:%[0-9]+]]:_(s64) = G_FCONSTANT double 6.000000e+00
  ; RV64I-NEXT:   [[C6:%[0-9]+]]:_(s64) = G_FCONSTANT double 7.000000e+00
  ; RV64I-NEXT:   [[C7:%[0-9]+]]:_(s64) = G_FCONSTANT double 8.000000e+00
  ; RV64I-NEXT:   [[C8:%[0-9]+]]:_(s64) = G_FCONSTANT double 9.000000e+00
  ; RV64I-NEXT:   [[FPEXT:%[0-9]+]]:_(s128) = G_FPEXT [[C]](s64)
  ; RV64I-NEXT:   [[FPEXT1:%[0-9]+]]:_(s128) = G_FPEXT [[C1]](s64)
  ; RV64I-NEXT:   [[FPEXT2:%[0-9]+]]:_(s128) = G_FPEXT [[C2]](s64)
  ; RV64I-NEXT:   [[FPEXT3:%[0-9]+]]:_(s128) = G_FPEXT [[C3]](s64)
  ; RV64I-NEXT:   [[FPEXT4:%[0-9]+]]:_(s128) = G_FPEXT [[C4]](s64)
  ; RV64I-NEXT:   [[FPEXT5:%[0-9]+]]:_(s128) = G_FPEXT [[C5]](s64)
  ; RV64I-NEXT:   [[FPEXT6:%[0-9]+]]:_(s128) = G_FPEXT [[C6]](s64)
  ; RV64I-NEXT:   [[FPEXT7:%[0-9]+]]:_(s128) = G_FPEXT [[C7]](s64)
  ; RV64I-NEXT:   [[FPEXT8:%[0-9]+]]:_(s128) = G_FPEXT [[C8]](s64)
  ; RV64I-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
  ; RV64I-NEXT:   [[UV:%[0-9]+]]:_(s64), [[UV1:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[FPEXT8]](s128)
  ; RV64I-NEXT:   $f10_q = COPY [[FPEXT]](s128)
  ; RV64I-NEXT:   $f11_q = COPY [[FPEXT1]](s128)
  ; RV64I-NEXT:   $f12_q = COPY [[FPEXT2]](s128)
  ; RV64I-NEXT:   $f13_q = COPY [[FPEXT3]](s128)
  ; RV64I-NEXT:   $f14_q = COPY [[FPEXT4]](s128)
  ; RV64I-NEXT:   $f15_q = COPY [[FPEXT5]](s128)
  ; RV64I-NEXT:   $f16_q = COPY [[FPEXT6]](s128)
  ; RV64I-NEXT:   $f17_q = COPY [[FPEXT7]](s128)
  ; RV64I-NEXT:   $x10 = COPY [[UV]](s64)
  ; RV64I-NEXT:   $x11 = COPY [[UV1]](s64)
  ; RV64I-NEXT:   PseudoCALL target-flags(riscv-call) @callee_fp128_in_gpr_exhausted_fprs, csr_ilp32q_lp64q, implicit-def $x1, implicit $f10_q, implicit $f11_q, implicit $f12_q, implicit $f13_q, implicit $f14_q, implicit $f15_q, implicit $f16_q, implicit $f17_q, implicit $x10, implicit $x11, implicit-def $x10
  ; RV64I-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
  ; RV64I-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $x10
  ; RV64I-NEXT:   [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
  ; RV64I-NEXT:   [[ANYEXT:%[0-9]+]]:_(s64) = G_ANYEXT [[TRUNC]](s32)
  ; RV64I-NEXT:   $x10 = COPY [[ANYEXT]](s64)
  ; RV64I-NEXT:   PseudoRET implicit $x10
  %1 = fpext double 1.0 to fp128
  %2 = fpext double 2.0 to fp128
  %3 = fpext double 3.0 to fp128
  %4 = fpext double 4.0 to fp128
  %5 = fpext double 5.0 to fp128
  %6 = fpext double 6.0 to fp128
  %7 = fpext double 7.0 to fp128
  %8 = fpext double 8.0 to fp128
  %9 = fpext double 9.0 to fp128
  %10 = call i32 @callee_fp128_in_gpr_exhausted_fprs(
      fp128 %1, fp128 %2, fp128 %3, fp128 %4, fp128 %5, fp128 %6,
      fp128 %7, fp128 %8, fp128 %9)
  ret i32 %10
}

; Must keep define on a single line due to an update_llc_test_checks.py limitation
define i64 @callee_fp128_on_stack_exhausted_gprs_fprs(i128 %a, fp128 %b, i128 %c, fp128 %d, i128 %e, fp128 %f, i128 %g, fp128 %h, fp128 %i, fp128 %j, fp128 %k, fp128 %l, fp128 %m) nounwind {
  ; RV64I-LABEL: name: callee_fp128_on_stack_exhausted_gprs_fprs
  ; RV64I: bb.1 (%ir-block.0):
  ; RV64I-NEXT:   liveins: $x10, $x11, $x12, $x13, $x14, $x15, $x16, $x17, $f10_q, $f11_q, $f12_q, $f13_q, $f14_q, $f15_q, $f16_q, $f17_q
  ; RV64I-NEXT: {{  $}}
  ; RV64I-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $x10
  ; RV64I-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
  ; RV64I-NEXT:   [[MV:%[0-9]+]]:_(s128) = G_MERGE_VALUES [[COPY]](s64), [[COPY1]](s64)
  ; RV64I-NEXT:   [[COPY2:%[0-9]+]]:_(s128) = COPY $f10_q
  ; RV64I-NEXT:   [[COPY3:%[0-9]+]]:_(s64) = COPY $x12
  ; RV64I-NEXT:   [[COPY4:%[0-9]+]]:_(s64) = COPY $x13
  ; RV64I-NEXT:   [[MV1:%[0-9]+]]:_(s128) = G_MERGE_VALUES [[COPY3]](s64), [[COPY4]](s64)
  ; RV64I-NEXT:   [[COPY5:%[0-9]+]]:_(s128) = COPY $f11_q
  ; RV64I-NEXT:   [[COPY6:%[0-9]+]]:_(s64) = COPY $x14
  ; RV64I-NEXT:   [[COPY7:%[0-9]+]]:_(s64) = COPY $x15
  ; RV64I-NEXT:   [[MV2:%[0-9]+]]:_(s128) = G_MERGE_VALUES [[COPY6]](s64), [[COPY7]](s64)
  ; RV64I-NEXT:   [[COPY8:%[0-9]+]]:_(s128) = COPY $f12_q
  ; RV64I-NEXT:   [[COPY9:%[0-9]+]]:_(s64) = COPY $x16
  ; RV64I-NEXT:   [[COPY10:%[0-9]+]]:_(s64) = COPY $x17
  ; RV64I-NEXT:   [[MV3:%[0-9]+]]:_(s128) = G_MERGE_VALUES [[COPY9]](s64), [[COPY10]](s64)
  ; RV64I-NEXT:   [[COPY11:%[0-9]+]]:_(s128) = COPY $f13_q
  ; RV64I-NEXT:   [[COPY12:%[0-9]+]]:_(s128) = COPY $f14_q
  ; RV64I-NEXT:   [[COPY13:%[0-9]+]]:_(s128) = COPY $f15_q
  ; RV64I-NEXT:   [[COPY14:%[0-9]+]]:_(s128) = COPY $f16_q
  ; RV64I-NEXT:   [[COPY15:%[0-9]+]]:_(s128) = COPY $f17_q
  ; RV64I-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; RV64I-NEXT:   [[LOAD:%[0-9]+]]:_(s128) = G_LOAD [[FRAME_INDEX]](p0) :: (load (s128) from %fixed-stack.0)
  ; RV64I-NEXT:   [[TRUNC:%[0-9]+]]:_(s64) = G_TRUNC [[MV3]](s128)
  ; RV64I-NEXT:   [[FPTOSI:%[0-9]+]]:_(s64) = G_FPTOSI [[LOAD]](s128)
  ; RV64I-NEXT:   [[ADD:%[0-9]+]]:_(s64) = G_ADD [[TRUNC]], [[FPTOSI]]
  ; RV64I-NEXT:   $x10 = COPY [[ADD]](s64)
  ; RV64I-NEXT:   PseudoRET implicit $x10
  %g_trunc = trunc i128 %g to i64
  %m_fptosi = fptosi fp128 %m to i64
  %1 = add i64 %g_trunc, %m_fptosi
  ret i64 %1
}

define i64 @caller_fp128_on_stack_exhausted_gprs_fprs() nounwind {
  ; RV64I-LABEL: name: caller_fp128_on_stack_exhausted_gprs_fprs
  ; RV64I: bb.1 (%ir-block.0):
  ; RV64I-NEXT:   [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 2.000000e+00
  ; RV64I-NEXT:   [[C1:%[0-9]+]]:_(s64) = G_FCONSTANT double 4.000000e+00
  ; RV64I-NEXT:   [[C2:%[0-9]+]]:_(s64) = G_FCONSTANT double 6.000000e+00
  ; RV64I-NEXT:   [[C3:%[0-9]+]]:_(s64) = G_FCONSTANT double 8.000000e+00
  ; RV64I-NEXT:   [[C4:%[0-9]+]]:_(s64) = G_FCONSTANT double 9.000000e+00
  ; RV64I-NEXT:   [[C5:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.000000e+01
  ; RV64I-NEXT:   [[C6:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.100000e+01
  ; RV64I-NEXT:   [[C7:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.200000e+01
  ; RV64I-NEXT:   [[C8:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.300000e+01
  ; RV64I-NEXT:   [[C9:%[0-9]+]]:_(s128) = G_CONSTANT i128 1
  ; RV64I-NEXT:   [[C10:%[0-9]+]]:_(s128) = G_CONSTANT i128 3
  ; RV64I-NEXT:   [[C11:%[0-9]+]]:_(s128) = G_CONSTANT i128 5
  ; RV64I-NEXT:   [[C12:%[0-9]+]]:_(s128) = G_CONSTANT i128 7
  ; RV64I-NEXT:   [[FPEXT:%[0-9]+]]:_(s128) = G_FPEXT [[C]](s64)
  ; RV64I-NEXT:   [[FPEXT1:%[0-9]+]]:_(s128) = G_FPEXT [[C1]](s64)
  ; RV64I-NEXT:   [[FPEXT2:%[0-9]+]]:_(s128) = G_FPEXT [[C2]](s64)
  ; RV64I-NEXT:   [[FPEXT3:%[0-9]+]]:_(s128) = G_FPEXT [[C3]](s64)
  ; RV64I-NEXT:   [[FPEXT4:%[0-9]+]]:_(s128) = G_FPEXT [[C4]](s64)
  ; RV64I-NEXT:   [[FPEXT5:%[0-9]+]]:_(s128) = G_FPEXT [[C5]](s64)
  ; RV64I-NEXT:   [[FPEXT6:%[0-9]+]]:_(s128) = G_FPEXT [[C6]](s64)
  ; RV64I-NEXT:   [[FPEXT7:%[0-9]+]]:_(s128) = G_FPEXT [[C7]](s64)
  ; RV64I-NEXT:   [[FPEXT8:%[0-9]+]]:_(s128) = G_FPEXT [[C8]](s64)
  ; RV64I-NEXT:   ADJCALLSTACKDOWN 16, 0, implicit-def $x2, implicit $x2
  ; RV64I-NEXT:   [[UV:%[0-9]+]]:_(s64), [[UV1:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[C9]](s128)
  ; RV64I-NEXT:   [[UV2:%[0-9]+]]:_(s64), [[UV3:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[C10]](s128)
  ; RV64I-NEXT:   [[UV4:%[0-9]+]]:_(s64), [[UV5:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[C11]](s128)
  ; RV64I-NEXT:   [[UV6:%[0-9]+]]:_(s64), [[UV7:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[C12]](s128)
  ; RV64I-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $x2
  ; RV64I-NEXT:   [[C13:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; RV64I-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s64)
  ; RV64I-NEXT:   G_STORE [[FPEXT8]](s128), [[PTR_ADD]](p0) :: (store (s128) into stack)
  ; RV64I-NEXT:   $x10 = COPY [[UV]](s64)
  ; RV64I-NEXT:   $x11 = COPY [[UV1]](s64)
  ; RV64I-NEXT:   $f10_q = COPY [[FPEXT]](s128)
  ; RV64I-NEXT:   $x12 = COPY [[UV2]](s64)
  ; RV64I-NEXT:   $x13 = COPY [[UV3]](s64)
  ; RV64I-NEXT:   $f11_q = COPY [[FPEXT1]](s128)
  ; RV64I-NEXT:   $x14 = COPY [[UV4]](s64)
  ; RV64I-NEXT:   $x15 = COPY [[UV5]](s64)
  ; RV64I-NEXT:   $f12_q = COPY [[FPEXT2]](s128)
  ; RV64I-NEXT:   $x16 = COPY [[UV6]](s64)
  ; RV64I-NEXT:   $x17 = COPY [[UV7]](s64)
  ; RV64I-NEXT:   $f13_q = COPY [[FPEXT3]](s128)
  ; RV64I-NEXT:   $f14_q = COPY [[FPEXT4]](s128)
  ; RV64I-NEXT:   $f15_q = COPY [[FPEXT5]](s128)
  ; RV64I-NEXT:   $f16_q = COPY [[FPEXT6]](s128)
  ; RV64I-NEXT:   $f17_q = COPY [[FPEXT7]](s128)
  ; RV64I-NEXT:   PseudoCALL target-flags(riscv-call) @callee_fp128_on_stack_exhausted_gprs_fprs, csr_ilp32q_lp64q, implicit-def $x1, implicit $x10, implicit $x11, implicit $f10_q, implicit $x12, implicit $x13, implicit $f11_q, implicit $x14, implicit $x15, implicit $f12_q, implicit $x16, implicit $x17, implicit $f13_q, implicit $f14_q, implicit $f15_q, implicit $f16_q, implicit $f17_q, implicit-def $x10
  ; RV64I-NEXT:   ADJCALLSTACKUP 16, 0, implicit-def $x2, implicit $x2
  ; RV64I-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $x10
  ; RV64I-NEXT:   $x10 = COPY [[COPY1]](s64)
  ; RV64I-NEXT:   PseudoRET implicit $x10
  %2 = fpext double 2.0 to fp128
  %4 = fpext double 4.0 to fp128
  %6 = fpext double 6.0 to fp128
  %8 = fpext double 8.0 to fp128
  %9 = fpext double 9.0 to fp128
  %10 = fpext double 10.0 to fp128
  %11 = fpext double 11.0 to fp128
  %12 = fpext double 12.0 to fp128
  %13 = fpext double 13.0 to fp128
  %14 = call i64 @callee_fp128_on_stack_exhausted_gprs_fprs(
      i128 1, fp128 %2, i128 3, fp128 %4, i128 5, fp128 %6, i128 7, fp128 %8,
      fp128 %9, fp128 %10, fp128 %11, fp128 %12, fp128 %13)
  ret i64 %14
}

define fp128 @callee_fp128_ret() nounwind {
  ; RV64I-LABEL: name: callee_fp128_ret
  ; RV64I: bb.1 (%ir-block.0):
  ; RV64I-NEXT:   [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.000000e+00
  ; RV64I-NEXT:   [[FPEXT:%[0-9]+]]:_(s128) = G_FPEXT [[C]](s64)
  ; RV64I-NEXT:   $f10_q = COPY [[FPEXT]](s128)
  ; RV64I-NEXT:   PseudoRET implicit $f10_q
  %1 = fpext double 1.0 to fp128
  ret fp128 %1
}

define i128 @caller_fp128_ret() nounwind {
  ; RV64I-LABEL: name: caller_fp128_ret
  ; RV64I: bb.1 (%ir-block.0):
  ; RV64I-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
  ; RV64I-NEXT:   PseudoCALL target-flags(riscv-call) @callee_fp128_ret, csr_ilp32q_lp64q, implicit-def $x1, implicit-def $f10_q
  ; RV64I-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
  ; RV64I-NEXT:   [[COPY:%[0-9]+]]:_(s128) = COPY $f10_q
  ; RV64I-NEXT:   [[UV:%[0-9]+]]:_(s64), [[UV1:%[0-9]+]]:_(s64) = G_UNMERGE_VALUES [[COPY]](s128)
  ; RV64I-NEXT:   $x10 = COPY [[UV]](s64)
  ; RV64I-NEXT:   $x11 = COPY [[UV1]](s64)
  ; RV64I-NEXT:   PseudoRET implicit $x10, implicit $x11
  %1 = call fp128 @callee_fp128_ret()
  %2 = bitcast fp128 %1 to i128
  ret i128 %2
}
