; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 -mattr=+q -target-abi ilp32q \
; RUN:    -global-isel -stop-after=irtranslator -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=RV32-ILP32Q %s

; This file contains tests that will have differing output for the ilp32/ilp32f
; and ilp32d ABIs.

define i32 @callee_fp128_in_fpr(i32 %a, fp128 %b) nounwind {
  ; RV32-ILP32Q-LABEL: name: callee_fp128_in_fpr
  ; RV32-ILP32Q: bb.1 (%ir-block.0):
  ; RV32-ILP32Q-NEXT:   liveins: $x10, $f10_q
  ; RV32-ILP32Q-NEXT: {{  $}}
  ; RV32-ILP32Q-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $x10
  ; RV32-ILP32Q-NEXT:   [[COPY1:%[0-9]+]]:_(s128) = COPY $f10_q
  ; RV32-ILP32Q-NEXT:   [[FPTOSI:%[0-9]+]]:_(s32) = G_FPTOSI [[COPY1]](s128)
  ; RV32-ILP32Q-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY]], [[FPTOSI]]
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[ADD]](s32)
  ; RV32-ILP32Q-NEXT:   PseudoRET implicit $x10
  %b_fptosi = fptosi fp128 %b to i32
  %1 = add i32 %a, %b_fptosi
  ret i32 %1
}

define i32 @caller_fp128_in_fpr() nounwind {
  ; RV32-ILP32Q-LABEL: name: caller_fp128_in_fpr
  ; RV32-ILP32Q: bb.1 (%ir-block.0):
  ; RV32-ILP32Q-NEXT:   [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 2.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; RV32-ILP32Q-NEXT:   [[FPEXT:%[0-9]+]]:_(s128) = G_FPEXT [[C]](s64)
  ; RV32-ILP32Q-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[C1]](s32)
  ; RV32-ILP32Q-NEXT:   $f10_q = COPY [[FPEXT]](s128)
  ; RV32-ILP32Q-NEXT:   PseudoCALL target-flags(riscv-call) @callee_fp128_in_fpr, csr_ilp32q_lp64q, implicit-def $x1, implicit $x10, implicit $f10_q, implicit-def $x10
  ; RV32-ILP32Q-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
  ; RV32-ILP32Q-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $x10
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[COPY]](s32)
  ; RV32-ILP32Q-NEXT:   PseudoRET implicit $x10
  %1 = fpext double 2.0 to fp128
  %2 = call i32 @callee_fp128_in_fpr(i32 1, fp128 %1)
  ret i32 %2
}

; Must keep define on a single line due to an update_llc_test_checks.py limitation
define i32 @callee_fp128_in_fpr_exhausted_gprs(i64 %a, i64 %b, i64 %c, i64 %d, i32 %e, fp128 %f) nounwind {
  ; RV32-ILP32Q-LABEL: name: callee_fp128_in_fpr_exhausted_gprs
  ; RV32-ILP32Q: bb.1 (%ir-block.0):
  ; RV32-ILP32Q-NEXT:   liveins: $x10, $x11, $x12, $x13, $x14, $x15, $x16, $x17, $f10_q
  ; RV32-ILP32Q-NEXT: {{  $}}
  ; RV32-ILP32Q-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $x10
  ; RV32-ILP32Q-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $x11
  ; RV32-ILP32Q-NEXT:   [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY]](s32), [[COPY1]](s32)
  ; RV32-ILP32Q-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $x12
  ; RV32-ILP32Q-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $x13
  ; RV32-ILP32Q-NEXT:   [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY2]](s32), [[COPY3]](s32)
  ; RV32-ILP32Q-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $x14
  ; RV32-ILP32Q-NEXT:   [[COPY5:%[0-9]+]]:_(s32) = COPY $x15
  ; RV32-ILP32Q-NEXT:   [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY4]](s32), [[COPY5]](s32)
  ; RV32-ILP32Q-NEXT:   [[COPY6:%[0-9]+]]:_(s32) = COPY $x16
  ; RV32-ILP32Q-NEXT:   [[COPY7:%[0-9]+]]:_(s32) = COPY $x17
  ; RV32-ILP32Q-NEXT:   [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY6]](s32), [[COPY7]](s32)
  ; RV32-ILP32Q-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; RV32-ILP32Q-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (load (s32) from %fixed-stack.0, align 16)
  ; RV32-ILP32Q-NEXT:   [[COPY8:%[0-9]+]]:_(s128) = COPY $f10_q
  ; RV32-ILP32Q-NEXT:   [[FPTOSI:%[0-9]+]]:_(s32) = G_FPTOSI [[COPY8]](s128)
  ; RV32-ILP32Q-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[LOAD]], [[FPTOSI]]
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[ADD]](s32)
  ; RV32-ILP32Q-NEXT:   PseudoRET implicit $x10
  %f_fptosi = fptosi fp128 %f to i32
  %1 = add i32 %e, %f_fptosi
  ret i32 %1
}

define i32 @caller_fp128_in_fpr_exhausted_gprs() nounwind {
  ; RV32-ILP32Q-LABEL: name: caller_fp128_in_fpr_exhausted_gprs
  ; RV32-ILP32Q: bb.1 (%ir-block.0):
  ; RV32-ILP32Q-NEXT:   [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 6.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
  ; RV32-ILP32Q-NEXT:   [[C2:%[0-9]+]]:_(s64) = G_CONSTANT i64 2
  ; RV32-ILP32Q-NEXT:   [[C3:%[0-9]+]]:_(s64) = G_CONSTANT i64 3
  ; RV32-ILP32Q-NEXT:   [[C4:%[0-9]+]]:_(s64) = G_CONSTANT i64 4
  ; RV32-ILP32Q-NEXT:   [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
  ; RV32-ILP32Q-NEXT:   [[FPEXT:%[0-9]+]]:_(s128) = G_FPEXT [[C]](s64)
  ; RV32-ILP32Q-NEXT:   ADJCALLSTACKDOWN 4, 0, implicit-def $x2, implicit $x2
  ; RV32-ILP32Q-NEXT:   [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C1]](s64)
  ; RV32-ILP32Q-NEXT:   [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C2]](s64)
  ; RV32-ILP32Q-NEXT:   [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C3]](s64)
  ; RV32-ILP32Q-NEXT:   [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C4]](s64)
  ; RV32-ILP32Q-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $x2
  ; RV32-ILP32Q-NEXT:   [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; RV32-ILP32Q-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C6]](s32)
  ; RV32-ILP32Q-NEXT:   G_STORE [[C5]](s32), [[PTR_ADD]](p0) :: (store (s32) into stack, align 16)
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[UV]](s32)
  ; RV32-ILP32Q-NEXT:   $x11 = COPY [[UV1]](s32)
  ; RV32-ILP32Q-NEXT:   $x12 = COPY [[UV2]](s32)
  ; RV32-ILP32Q-NEXT:   $x13 = COPY [[UV3]](s32)
  ; RV32-ILP32Q-NEXT:   $x14 = COPY [[UV4]](s32)
  ; RV32-ILP32Q-NEXT:   $x15 = COPY [[UV5]](s32)
  ; RV32-ILP32Q-NEXT:   $x16 = COPY [[UV6]](s32)
  ; RV32-ILP32Q-NEXT:   $x17 = COPY [[UV7]](s32)
  ; RV32-ILP32Q-NEXT:   $f10_q = COPY [[FPEXT]](s128)
  ; RV32-ILP32Q-NEXT:   PseudoCALL target-flags(riscv-call) @callee_fp128_in_fpr_exhausted_gprs, csr_ilp32q_lp64q, implicit-def $x1, implicit $x10, implicit $x11, implicit $x12, implicit $x13, implicit $x14, implicit $x15, implicit $x16, implicit $x17, implicit $f10_q, implicit-def $x10
  ; RV32-ILP32Q-NEXT:   ADJCALLSTACKUP 4, 0, implicit-def $x2, implicit $x2
  ; RV32-ILP32Q-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $x10
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[COPY1]](s32)
  ; RV32-ILP32Q-NEXT:   PseudoRET implicit $x10
  %1 = fpext double 6.0 to fp128
  %2 = call i32 @callee_fp128_in_fpr_exhausted_gprs(
      i64 1, i64 2, i64 3, i64 4, i32 5, fp128 %1)
  ret i32 %2
}

; Must keep define on a single line due to an update_llc_test_checks.py limitation
define i32 @callee_fp128_in_gpr_exhausted_fprs(fp128 %a, fp128 %b, fp128 %c, fp128 %d, fp128 %e, fp128 %f, fp128 %g, fp128 %h, fp128 %i) nounwind {
  ; RV32-ILP32Q-LABEL: name: callee_fp128_in_gpr_exhausted_fprs
  ; RV32-ILP32Q: bb.1 (%ir-block.0):
  ; RV32-ILP32Q-NEXT:   liveins: $x10, $f10_q, $f11_q, $f12_q, $f13_q, $f14_q, $f15_q, $f16_q, $f17_q
  ; RV32-ILP32Q-NEXT: {{  $}}
  ; RV32-ILP32Q-NEXT:   [[COPY:%[0-9]+]]:_(s128) = COPY $f10_q
  ; RV32-ILP32Q-NEXT:   [[COPY1:%[0-9]+]]:_(s128) = COPY $f11_q
  ; RV32-ILP32Q-NEXT:   [[COPY2:%[0-9]+]]:_(s128) = COPY $f12_q
  ; RV32-ILP32Q-NEXT:   [[COPY3:%[0-9]+]]:_(s128) = COPY $f13_q
  ; RV32-ILP32Q-NEXT:   [[COPY4:%[0-9]+]]:_(s128) = COPY $f14_q
  ; RV32-ILP32Q-NEXT:   [[COPY5:%[0-9]+]]:_(s128) = COPY $f15_q
  ; RV32-ILP32Q-NEXT:   [[COPY6:%[0-9]+]]:_(s128) = COPY $f16_q
  ; RV32-ILP32Q-NEXT:   [[COPY7:%[0-9]+]]:_(s128) = COPY $f17_q
  ; RV32-ILP32Q-NEXT:   [[COPY8:%[0-9]+]]:_(p0) = COPY $x10
  ; RV32-ILP32Q-NEXT:   [[LOAD:%[0-9]+]]:_(s128) = G_LOAD [[COPY8]](p0) :: (load (s128))
  ; RV32-ILP32Q-NEXT:   [[FPTOSI:%[0-9]+]]:_(s32) = G_FPTOSI [[COPY7]](s128)
  ; RV32-ILP32Q-NEXT:   [[FPTOSI1:%[0-9]+]]:_(s32) = G_FPTOSI [[LOAD]](s128)
  ; RV32-ILP32Q-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[FPTOSI]], [[FPTOSI1]]
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[ADD]](s32)
  ; RV32-ILP32Q-NEXT:   PseudoRET implicit $x10
  %h_fptosi = fptosi fp128 %h to i32
  %i_fptosi = fptosi fp128 %i to i32
  %1 = add i32 %h_fptosi, %i_fptosi
  ret i32 %1
}

define i32 @caller_fp128_in_gpr_exhausted_fprs() nounwind {
  ; RV32-ILP32Q-LABEL: name: caller_fp128_in_gpr_exhausted_fprs
  ; RV32-ILP32Q: bb.1 (%ir-block.0):
  ; RV32-ILP32Q-NEXT:   [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C1:%[0-9]+]]:_(s64) = G_FCONSTANT double 2.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C2:%[0-9]+]]:_(s64) = G_FCONSTANT double 3.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C3:%[0-9]+]]:_(s64) = G_FCONSTANT double 4.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C4:%[0-9]+]]:_(s64) = G_FCONSTANT double 5.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C5:%[0-9]+]]:_(s64) = G_FCONSTANT double 6.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C6:%[0-9]+]]:_(s64) = G_FCONSTANT double 7.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C7:%[0-9]+]]:_(s64) = G_FCONSTANT double 8.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C8:%[0-9]+]]:_(s64) = G_FCONSTANT double 9.000000e+00
  ; RV32-ILP32Q-NEXT:   [[FPEXT:%[0-9]+]]:_(s128) = G_FPEXT [[C]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT1:%[0-9]+]]:_(s128) = G_FPEXT [[C1]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT2:%[0-9]+]]:_(s128) = G_FPEXT [[C2]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT3:%[0-9]+]]:_(s128) = G_FPEXT [[C3]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT4:%[0-9]+]]:_(s128) = G_FPEXT [[C4]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT5:%[0-9]+]]:_(s128) = G_FPEXT [[C5]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT6:%[0-9]+]]:_(s128) = G_FPEXT [[C6]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT7:%[0-9]+]]:_(s128) = G_FPEXT [[C7]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT8:%[0-9]+]]:_(s128) = G_FPEXT [[C8]](s64)
  ; RV32-ILP32Q-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
  ; RV32-ILP32Q-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0
  ; RV32-ILP32Q-NEXT:   G_STORE [[FPEXT8]](s128), [[FRAME_INDEX]](p0) :: (store (s128) into %stack.0)
  ; RV32-ILP32Q-NEXT:   $f10_q = COPY [[FPEXT]](s128)
  ; RV32-ILP32Q-NEXT:   $f11_q = COPY [[FPEXT1]](s128)
  ; RV32-ILP32Q-NEXT:   $f12_q = COPY [[FPEXT2]](s128)
  ; RV32-ILP32Q-NEXT:   $f13_q = COPY [[FPEXT3]](s128)
  ; RV32-ILP32Q-NEXT:   $f14_q = COPY [[FPEXT4]](s128)
  ; RV32-ILP32Q-NEXT:   $f15_q = COPY [[FPEXT5]](s128)
  ; RV32-ILP32Q-NEXT:   $f16_q = COPY [[FPEXT6]](s128)
  ; RV32-ILP32Q-NEXT:   $f17_q = COPY [[FPEXT7]](s128)
  ; RV32-ILP32Q-NEXT:   [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[FRAME_INDEX]](p0)
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[PTRTOINT]](s32)
  ; RV32-ILP32Q-NEXT:   PseudoCALL target-flags(riscv-call) @callee_fp128_in_gpr_exhausted_fprs, csr_ilp32q_lp64q, implicit-def $x1, implicit $f10_q, implicit $f11_q, implicit $f12_q, implicit $f13_q, implicit $f14_q, implicit $f15_q, implicit $f16_q, implicit $f17_q, implicit $x10, implicit-def $x10
  ; RV32-ILP32Q-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
  ; RV32-ILP32Q-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $x10
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[COPY]](s32)
  ; RV32-ILP32Q-NEXT:   PseudoRET implicit $x10
  %1 = fpext double 1.0 to fp128
  %2 = fpext double 2.0 to fp128
  %3 = fpext double 3.0 to fp128
  %4 = fpext double 4.0 to fp128
  %5 = fpext double 5.0 to fp128
  %6 = fpext double 6.0 to fp128
  %7 = fpext double 7.0 to fp128
  %8 = fpext double 8.0 to fp128
  %9 = fpext double 9.0 to fp128
  %10 = call i32 @callee_fp128_in_gpr_exhausted_fprs(
      fp128 %1, fp128 %2, fp128 %3, fp128 %4, fp128 %5, fp128 %6,
      fp128 %7, fp128 %8, fp128 %9)
  ret i32 %10
}

; Must keep define on a single line due to an update_llc_test_checks.py limitation
define i32 @callee_fp128_in_gpr_and_stack_almost_exhausted_gprs_fprs(i64 %a, fp128 %b, i64 %c, fp128 %d, i64 %e, fp128 %f, i32 %g, fp128 %h, fp128 %i, fp128 %j, fp128 %k, fp128 %l, fp128 %m) nounwind {
  ; RV32-ILP32Q-LABEL: name: callee_fp128_in_gpr_and_stack_almost_exhausted_gprs_fprs
  ; RV32-ILP32Q: bb.1 (%ir-block.0):
  ; RV32-ILP32Q-NEXT:   liveins: $x10, $x11, $x12, $x13, $x14, $x15, $x16, $x17, $f10_q, $f11_q, $f12_q, $f13_q, $f14_q, $f15_q, $f16_q, $f17_q
  ; RV32-ILP32Q-NEXT: {{  $}}
  ; RV32-ILP32Q-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $x10
  ; RV32-ILP32Q-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $x11
  ; RV32-ILP32Q-NEXT:   [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY]](s32), [[COPY1]](s32)
  ; RV32-ILP32Q-NEXT:   [[COPY2:%[0-9]+]]:_(s128) = COPY $f10_q
  ; RV32-ILP32Q-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $x12
  ; RV32-ILP32Q-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $x13
  ; RV32-ILP32Q-NEXT:   [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY3]](s32), [[COPY4]](s32)
  ; RV32-ILP32Q-NEXT:   [[COPY5:%[0-9]+]]:_(s128) = COPY $f11_q
  ; RV32-ILP32Q-NEXT:   [[COPY6:%[0-9]+]]:_(s32) = COPY $x14
  ; RV32-ILP32Q-NEXT:   [[COPY7:%[0-9]+]]:_(s32) = COPY $x15
  ; RV32-ILP32Q-NEXT:   [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY6]](s32), [[COPY7]](s32)
  ; RV32-ILP32Q-NEXT:   [[COPY8:%[0-9]+]]:_(s128) = COPY $f12_q
  ; RV32-ILP32Q-NEXT:   [[COPY9:%[0-9]+]]:_(s32) = COPY $x16
  ; RV32-ILP32Q-NEXT:   [[COPY10:%[0-9]+]]:_(s128) = COPY $f13_q
  ; RV32-ILP32Q-NEXT:   [[COPY11:%[0-9]+]]:_(s128) = COPY $f14_q
  ; RV32-ILP32Q-NEXT:   [[COPY12:%[0-9]+]]:_(s128) = COPY $f15_q
  ; RV32-ILP32Q-NEXT:   [[COPY13:%[0-9]+]]:_(s128) = COPY $f16_q
  ; RV32-ILP32Q-NEXT:   [[COPY14:%[0-9]+]]:_(s128) = COPY $f17_q
  ; RV32-ILP32Q-NEXT:   [[COPY15:%[0-9]+]]:_(p0) = COPY $x17
  ; RV32-ILP32Q-NEXT:   [[LOAD:%[0-9]+]]:_(s128) = G_LOAD [[COPY15]](p0) :: (load (s128))
  ; RV32-ILP32Q-NEXT:   [[FPTOSI:%[0-9]+]]:_(s32) = G_FPTOSI [[LOAD]](s128)
  ; RV32-ILP32Q-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[COPY9]], [[FPTOSI]]
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[ADD]](s32)
  ; RV32-ILP32Q-NEXT:   PseudoRET implicit $x10
  %m_fptosi = fptosi fp128 %m to i32
  %1 = add i32 %g, %m_fptosi
  ret i32 %1
}

define i32 @caller_fp128_in_gpr_and_stack_almost_exhausted_gprs_fprs() nounwind {
  ; RV32-ILP32Q-LABEL: name: caller_fp128_in_gpr_and_stack_almost_exhausted_gprs_fprs
  ; RV32-ILP32Q: bb.1 (%ir-block.0):
  ; RV32-ILP32Q-NEXT:   [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 2.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C1:%[0-9]+]]:_(s64) = G_FCONSTANT double 4.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C2:%[0-9]+]]:_(s64) = G_FCONSTANT double 6.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C3:%[0-9]+]]:_(s64) = G_FCONSTANT double 8.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C4:%[0-9]+]]:_(s64) = G_FCONSTANT double 9.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C5:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.000000e+01
  ; RV32-ILP32Q-NEXT:   [[C6:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.100000e+01
  ; RV32-ILP32Q-NEXT:   [[C7:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.200000e+01
  ; RV32-ILP32Q-NEXT:   [[C8:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.300000e+01
  ; RV32-ILP32Q-NEXT:   [[C9:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
  ; RV32-ILP32Q-NEXT:   [[C10:%[0-9]+]]:_(s64) = G_CONSTANT i64 3
  ; RV32-ILP32Q-NEXT:   [[C11:%[0-9]+]]:_(s64) = G_CONSTANT i64 5
  ; RV32-ILP32Q-NEXT:   [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
  ; RV32-ILP32Q-NEXT:   [[FPEXT:%[0-9]+]]:_(s128) = G_FPEXT [[C]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT1:%[0-9]+]]:_(s128) = G_FPEXT [[C1]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT2:%[0-9]+]]:_(s128) = G_FPEXT [[C2]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT3:%[0-9]+]]:_(s128) = G_FPEXT [[C3]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT4:%[0-9]+]]:_(s128) = G_FPEXT [[C4]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT5:%[0-9]+]]:_(s128) = G_FPEXT [[C5]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT6:%[0-9]+]]:_(s128) = G_FPEXT [[C6]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT7:%[0-9]+]]:_(s128) = G_FPEXT [[C7]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT8:%[0-9]+]]:_(s128) = G_FPEXT [[C8]](s64)
  ; RV32-ILP32Q-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
  ; RV32-ILP32Q-NEXT:   [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C9]](s64)
  ; RV32-ILP32Q-NEXT:   [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C10]](s64)
  ; RV32-ILP32Q-NEXT:   [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C11]](s64)
  ; RV32-ILP32Q-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0
  ; RV32-ILP32Q-NEXT:   G_STORE [[FPEXT8]](s128), [[FRAME_INDEX]](p0) :: (store (s128) into %stack.0)
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[UV]](s32)
  ; RV32-ILP32Q-NEXT:   $x11 = COPY [[UV1]](s32)
  ; RV32-ILP32Q-NEXT:   $f10_q = COPY [[FPEXT]](s128)
  ; RV32-ILP32Q-NEXT:   $x12 = COPY [[UV2]](s32)
  ; RV32-ILP32Q-NEXT:   $x13 = COPY [[UV3]](s32)
  ; RV32-ILP32Q-NEXT:   $f11_q = COPY [[FPEXT1]](s128)
  ; RV32-ILP32Q-NEXT:   $x14 = COPY [[UV4]](s32)
  ; RV32-ILP32Q-NEXT:   $x15 = COPY [[UV5]](s32)
  ; RV32-ILP32Q-NEXT:   $f12_q = COPY [[FPEXT2]](s128)
  ; RV32-ILP32Q-NEXT:   $x16 = COPY [[C12]](s32)
  ; RV32-ILP32Q-NEXT:   $f13_q = COPY [[FPEXT3]](s128)
  ; RV32-ILP32Q-NEXT:   $f14_q = COPY [[FPEXT4]](s128)
  ; RV32-ILP32Q-NEXT:   $f15_q = COPY [[FPEXT5]](s128)
  ; RV32-ILP32Q-NEXT:   $f16_q = COPY [[FPEXT6]](s128)
  ; RV32-ILP32Q-NEXT:   $f17_q = COPY [[FPEXT7]](s128)
  ; RV32-ILP32Q-NEXT:   [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[FRAME_INDEX]](p0)
  ; RV32-ILP32Q-NEXT:   $x17 = COPY [[PTRTOINT]](s32)
  ; RV32-ILP32Q-NEXT:   PseudoCALL target-flags(riscv-call) @callee_fp128_in_gpr_and_stack_almost_exhausted_gprs_fprs, csr_ilp32q_lp64q, implicit-def $x1, implicit $x10, implicit $x11, implicit $f10_q, implicit $x12, implicit $x13, implicit $f11_q, implicit $x14, implicit $x15, implicit $f12_q, implicit $x16, implicit $f13_q, implicit $f14_q, implicit $f15_q, implicit $f16_q, implicit $f17_q, implicit $x17, implicit-def $x10
  ; RV32-ILP32Q-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
  ; RV32-ILP32Q-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $x10
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[COPY]](s32)
  ; RV32-ILP32Q-NEXT:   PseudoRET implicit $x10
  %2 = fpext double 2.0 to fp128
  %4 = fpext double 4.0 to fp128
  %6 = fpext double 6.0 to fp128
  %8 = fpext double 8.0 to fp128
  %9 = fpext double 9.0 to fp128
  %10 = fpext double 10.0 to fp128
  %11 = fpext double 11.0 to fp128
  %12 = fpext double 12.0 to fp128
  %13 = fpext double 13.0 to fp128
  %14 = call i32 @callee_fp128_in_gpr_and_stack_almost_exhausted_gprs_fprs(
      i64 1, fp128 %2, i64 3, fp128 %4, i64 5, fp128 %6, i32 7, fp128 %8,
      fp128 %9, fp128 %10, fp128 %11, fp128 %12, fp128 %13)
  ret i32 %14
}


; Must keep define on a single line due to an update_llc_test_checks.py limitation
define i32 @callee_fp128_on_stack_exhausted_gprs_fprs(i64 %a, fp128 %b, i64 %c, fp128 %d, i64 %e, fp128 %f, i64 %g, fp128 %h, fp128 %i, fp128 %j, fp128 %k, fp128 %l, fp128 %m) nounwind {
  ; RV32-ILP32Q-LABEL: name: callee_fp128_on_stack_exhausted_gprs_fprs
  ; RV32-ILP32Q: bb.1 (%ir-block.0):
  ; RV32-ILP32Q-NEXT:   liveins: $x10, $x11, $x12, $x13, $x14, $x15, $x16, $x17, $f10_q, $f11_q, $f12_q, $f13_q, $f14_q, $f15_q, $f16_q, $f17_q
  ; RV32-ILP32Q-NEXT: {{  $}}
  ; RV32-ILP32Q-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $x10
  ; RV32-ILP32Q-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $x11
  ; RV32-ILP32Q-NEXT:   [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY]](s32), [[COPY1]](s32)
  ; RV32-ILP32Q-NEXT:   [[COPY2:%[0-9]+]]:_(s128) = COPY $f10_q
  ; RV32-ILP32Q-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $x12
  ; RV32-ILP32Q-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $x13
  ; RV32-ILP32Q-NEXT:   [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY3]](s32), [[COPY4]](s32)
  ; RV32-ILP32Q-NEXT:   [[COPY5:%[0-9]+]]:_(s128) = COPY $f11_q
  ; RV32-ILP32Q-NEXT:   [[COPY6:%[0-9]+]]:_(s32) = COPY $x14
  ; RV32-ILP32Q-NEXT:   [[COPY7:%[0-9]+]]:_(s32) = COPY $x15
  ; RV32-ILP32Q-NEXT:   [[MV2:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY6]](s32), [[COPY7]](s32)
  ; RV32-ILP32Q-NEXT:   [[COPY8:%[0-9]+]]:_(s128) = COPY $f12_q
  ; RV32-ILP32Q-NEXT:   [[COPY9:%[0-9]+]]:_(s32) = COPY $x16
  ; RV32-ILP32Q-NEXT:   [[COPY10:%[0-9]+]]:_(s32) = COPY $x17
  ; RV32-ILP32Q-NEXT:   [[MV3:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY9]](s32), [[COPY10]](s32)
  ; RV32-ILP32Q-NEXT:   [[COPY11:%[0-9]+]]:_(s128) = COPY $f13_q
  ; RV32-ILP32Q-NEXT:   [[COPY12:%[0-9]+]]:_(s128) = COPY $f14_q
  ; RV32-ILP32Q-NEXT:   [[COPY13:%[0-9]+]]:_(s128) = COPY $f15_q
  ; RV32-ILP32Q-NEXT:   [[COPY14:%[0-9]+]]:_(s128) = COPY $f16_q
  ; RV32-ILP32Q-NEXT:   [[COPY15:%[0-9]+]]:_(s128) = COPY $f17_q
  ; RV32-ILP32Q-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; RV32-ILP32Q-NEXT:   [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[FRAME_INDEX]](p0) :: (load (p0) from %fixed-stack.0, align 16)
  ; RV32-ILP32Q-NEXT:   [[LOAD1:%[0-9]+]]:_(s128) = G_LOAD [[LOAD]](p0) :: (load (s128))
  ; RV32-ILP32Q-NEXT:   [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[MV3]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPTOSI:%[0-9]+]]:_(s32) = G_FPTOSI [[LOAD1]](s128)
  ; RV32-ILP32Q-NEXT:   [[ADD:%[0-9]+]]:_(s32) = G_ADD [[TRUNC]], [[FPTOSI]]
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[ADD]](s32)
  ; RV32-ILP32Q-NEXT:   PseudoRET implicit $x10
  %g_trunc = trunc i64 %g to i32
  %m_fptosi = fptosi fp128 %m to i32
  %1 = add i32 %g_trunc, %m_fptosi
  ret i32 %1
}

define i32 @caller_fp128_on_stack_exhausted_gprs_fprs() nounwind {
  ; RV32-ILP32Q-LABEL: name: caller_fp128_on_stack_exhausted_gprs_fprs
  ; RV32-ILP32Q: bb.1 (%ir-block.0):
  ; RV32-ILP32Q-NEXT:   [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 2.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C1:%[0-9]+]]:_(s64) = G_FCONSTANT double 4.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C2:%[0-9]+]]:_(s64) = G_FCONSTANT double 6.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C3:%[0-9]+]]:_(s64) = G_FCONSTANT double 8.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C4:%[0-9]+]]:_(s64) = G_FCONSTANT double 9.000000e+00
  ; RV32-ILP32Q-NEXT:   [[C5:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.000000e+01
  ; RV32-ILP32Q-NEXT:   [[C6:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.100000e+01
  ; RV32-ILP32Q-NEXT:   [[C7:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.200000e+01
  ; RV32-ILP32Q-NEXT:   [[C8:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.300000e+01
  ; RV32-ILP32Q-NEXT:   [[C9:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
  ; RV32-ILP32Q-NEXT:   [[C10:%[0-9]+]]:_(s64) = G_CONSTANT i64 3
  ; RV32-ILP32Q-NEXT:   [[C11:%[0-9]+]]:_(s64) = G_CONSTANT i64 5
  ; RV32-ILP32Q-NEXT:   [[C12:%[0-9]+]]:_(s64) = G_CONSTANT i64 7
  ; RV32-ILP32Q-NEXT:   [[FPEXT:%[0-9]+]]:_(s128) = G_FPEXT [[C]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT1:%[0-9]+]]:_(s128) = G_FPEXT [[C1]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT2:%[0-9]+]]:_(s128) = G_FPEXT [[C2]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT3:%[0-9]+]]:_(s128) = G_FPEXT [[C3]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT4:%[0-9]+]]:_(s128) = G_FPEXT [[C4]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT5:%[0-9]+]]:_(s128) = G_FPEXT [[C5]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT6:%[0-9]+]]:_(s128) = G_FPEXT [[C6]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT7:%[0-9]+]]:_(s128) = G_FPEXT [[C7]](s64)
  ; RV32-ILP32Q-NEXT:   [[FPEXT8:%[0-9]+]]:_(s128) = G_FPEXT [[C8]](s64)
  ; RV32-ILP32Q-NEXT:   ADJCALLSTACKDOWN 4, 0, implicit-def $x2, implicit $x2
  ; RV32-ILP32Q-NEXT:   [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C9]](s64)
  ; RV32-ILP32Q-NEXT:   [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C10]](s64)
  ; RV32-ILP32Q-NEXT:   [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C11]](s64)
  ; RV32-ILP32Q-NEXT:   [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C12]](s64)
  ; RV32-ILP32Q-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0
  ; RV32-ILP32Q-NEXT:   G_STORE [[FPEXT8]](s128), [[FRAME_INDEX]](p0) :: (store (s128) into %stack.0)
  ; RV32-ILP32Q-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $x2
  ; RV32-ILP32Q-NEXT:   [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; RV32-ILP32Q-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C13]](s32)
  ; RV32-ILP32Q-NEXT:   [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[FRAME_INDEX]](p0)
  ; RV32-ILP32Q-NEXT:   G_STORE [[PTRTOINT]](s32), [[PTR_ADD]](p0) :: (store (p0) into stack, align 16)
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[UV]](s32)
  ; RV32-ILP32Q-NEXT:   $x11 = COPY [[UV1]](s32)
  ; RV32-ILP32Q-NEXT:   $f10_q = COPY [[FPEXT]](s128)
  ; RV32-ILP32Q-NEXT:   $x12 = COPY [[UV2]](s32)
  ; RV32-ILP32Q-NEXT:   $x13 = COPY [[UV3]](s32)
  ; RV32-ILP32Q-NEXT:   $f11_q = COPY [[FPEXT1]](s128)
  ; RV32-ILP32Q-NEXT:   $x14 = COPY [[UV4]](s32)
  ; RV32-ILP32Q-NEXT:   $x15 = COPY [[UV5]](s32)
  ; RV32-ILP32Q-NEXT:   $f12_q = COPY [[FPEXT2]](s128)
  ; RV32-ILP32Q-NEXT:   $x16 = COPY [[UV6]](s32)
  ; RV32-ILP32Q-NEXT:   $x17 = COPY [[UV7]](s32)
  ; RV32-ILP32Q-NEXT:   $f13_q = COPY [[FPEXT3]](s128)
  ; RV32-ILP32Q-NEXT:   $f14_q = COPY [[FPEXT4]](s128)
  ; RV32-ILP32Q-NEXT:   $f15_q = COPY [[FPEXT5]](s128)
  ; RV32-ILP32Q-NEXT:   $f16_q = COPY [[FPEXT6]](s128)
  ; RV32-ILP32Q-NEXT:   $f17_q = COPY [[FPEXT7]](s128)
  ; RV32-ILP32Q-NEXT:   PseudoCALL target-flags(riscv-call) @callee_fp128_on_stack_exhausted_gprs_fprs, csr_ilp32q_lp64q, implicit-def $x1, implicit $x10, implicit $x11, implicit $f10_q, implicit $x12, implicit $x13, implicit $f11_q, implicit $x14, implicit $x15, implicit $f12_q, implicit $x16, implicit $x17, implicit $f13_q, implicit $f14_q, implicit $f15_q, implicit $f16_q, implicit $f17_q, implicit-def $x10
  ; RV32-ILP32Q-NEXT:   ADJCALLSTACKUP 4, 0, implicit-def $x2, implicit $x2
  ; RV32-ILP32Q-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $x10
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[COPY1]](s32)
  ; RV32-ILP32Q-NEXT:   PseudoRET implicit $x10
  %2 = fpext double 2.0 to fp128
  %4 = fpext double 4.0 to fp128
  %6 = fpext double 6.0 to fp128
  %8 = fpext double 8.0 to fp128
  %9 = fpext double 9.0 to fp128
  %10 = fpext double 10.0 to fp128
  %11 = fpext double 11.0 to fp128
  %12 = fpext double 12.0 to fp128
  %13 = fpext double 13.0 to fp128
  %14 = call i32 @callee_fp128_on_stack_exhausted_gprs_fprs(
      i64 1, fp128 %2, i64 3, fp128 %4, i64 5, fp128 %6, i64 7, fp128 %8,
      fp128 %9, fp128 %10, fp128 %11, fp128 %12, fp128 %13)
  ret i32 %14
}

define fp128 @callee_fp128_ret() nounwind {
  ; RV32-ILP32Q-LABEL: name: callee_fp128_ret
  ; RV32-ILP32Q: bb.1 (%ir-block.0):
  ; RV32-ILP32Q-NEXT:   [[C:%[0-9]+]]:_(s64) = G_FCONSTANT double 1.000000e+00
  ; RV32-ILP32Q-NEXT:   [[FPEXT:%[0-9]+]]:_(s128) = G_FPEXT [[C]](s64)
  ; RV32-ILP32Q-NEXT:   $f10_q = COPY [[FPEXT]](s128)
  ; RV32-ILP32Q-NEXT:   PseudoRET implicit $f10_q
  %1 = fpext double 1.0 to fp128
  ret fp128 %1
}

define i32 @caller_fp128_ret() nounwind {
  ; RV32-ILP32Q-LABEL: name: caller_fp128_ret
  ; RV32-ILP32Q: bb.1 (%ir-block.0):
  ; RV32-ILP32Q-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $x2, implicit $x2
  ; RV32-ILP32Q-NEXT:   PseudoCALL target-flags(riscv-call) @callee_fp128_ret, csr_ilp32q_lp64q, implicit-def $x1, implicit-def $f10_q
  ; RV32-ILP32Q-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $x2, implicit $x2
  ; RV32-ILP32Q-NEXT:   [[COPY:%[0-9]+]]:_(s128) = COPY $f10_q
  ; RV32-ILP32Q-NEXT:   [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s128)
  ; RV32-ILP32Q-NEXT:   $x10 = COPY [[TRUNC]](s32)
  ; RV32-ILP32Q-NEXT:   PseudoRET implicit $x10
  %1 = call fp128 @callee_fp128_ret()
  %2 = bitcast fp128 %1 to i128
  %3 = trunc i128 %2 to i32
  ret i32 %3
}
