; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=correlated-propagation %s | FileCheck %s

define i1 @nonnull(ptr %ptr) {
; CHECK-LABEL: define i1 @nonnull(
; CHECK-SAME: ptr [[PTR:%.*]]) {
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[PTR]]) ]
; CHECK-NEXT:    ret i1 true
;
  call void @llvm.assume(i1 true) [ "nonnull"(ptr %ptr) ]
  %is_nonnull = icmp ne ptr %ptr, null
  ret i1 %is_nonnull
}

define i1 @nonnull_on_other_ptr(ptr %ptr, ptr %other_ptr) {
; CHECK-LABEL: define i1 @nonnull_on_other_ptr(
; CHECK-SAME: ptr [[PTR:%.*]], ptr [[OTHER_PTR:%.*]]) {
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[OTHER_PTR]]) ]
; CHECK-NEXT:    [[IS_NONNULL:%.*]] = icmp ne ptr [[PTR]], null
; CHECK-NEXT:    ret i1 [[IS_NONNULL]]
;
  call void @llvm.assume(i1 true) [ "nonnull"(ptr %other_ptr) ]
  %is_nonnull = icmp ne ptr %ptr, null
  ret i1 %is_nonnull
}

define i1 @dereferenceable(ptr %ptr) {
; CHECK-LABEL: define i1 @dereferenceable(
; CHECK-SAME: ptr [[PTR:%.*]]) {
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "dereferenceable"(ptr [[PTR]], i32 1) ]
; CHECK-NEXT:    ret i1 true
;
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %ptr, i32 1) ]
  %is_nonnull = icmp ne ptr %ptr, null
  ret i1 %is_nonnull
}
