; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=correlated-propagation -S | FileCheck %s

; Exercise the four getPredicateOnEdge() switch eq/ne cases using a live-in
; value defined in the switch block. This forces CVP to query
; getPredicateAt(), which in turn pushes the predicate onto the incoming switch
; edge via getPredicateOnEdge().

define i1 @case_eq_false(i32 %x) {
; CHECK-LABEL: define i1 @case_eq_false(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[PRED:%.*]] = add i32 [[X]], 1
; CHECK-NEXT:    switch i32 [[X]], label %[[OTHER:.*]] [
; CHECK-NEXT:      i32 1, label %[[CASE:.*]]
; CHECK-NEXT:      i32 3, label %[[CASE]]
; CHECK-NEXT:    ]
; CHECK:       [[OTHER]]:
; CHECK-NEXT:    ret i1 false
; CHECK:       [[CASE]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %pred = add i32 %x, 1
  switch i32 %x, label %other [
  i32 1, label %case
  i32 3, label %case
  ]

other:
  ret i1 false

case:
  %cmp = icmp eq i32 %pred, 3
  ret i1 %cmp
}

define i1 @case_ne_true(i32 %x) {
; CHECK-LABEL: define i1 @case_ne_true(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[PRED:%.*]] = add i32 [[X]], 1
; CHECK-NEXT:    switch i32 [[X]], label %[[OTHER:.*]] [
; CHECK-NEXT:      i32 1, label %[[CASE:.*]]
; CHECK-NEXT:      i32 3, label %[[CASE]]
; CHECK-NEXT:    ]
; CHECK:       [[OTHER]]:
; CHECK-NEXT:    ret i1 false
; CHECK:       [[CASE]]:
; CHECK-NEXT:    ret i1 true
;
entry:
  %pred = add i32 %x, 1
  switch i32 %x, label %other [
  i32 1, label %case
  i32 3, label %case
  ]

other:
  ret i1 false

case:
  %cmp = icmp ne i32 %pred, 3
  ret i1 %cmp
}

define i1 @default_eq_false(i32 %x) {
; CHECK-LABEL: define i1 @default_eq_false(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[PRED:%.*]] = add i32 [[X]], 1
; CHECK-NEXT:    switch i32 [[X]], label %[[DEFAULT:.*]] [
; CHECK-NEXT:      i32 2, label %[[OTHER:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[OTHER]]:
; CHECK-NEXT:    ret i1 false
; CHECK:       [[DEFAULT]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %pred = add i32 %x, 1
  switch i32 %x, label %default [
  i32 2, label %other
  ]

other:
  ret i1 false

default:
  %cmp = icmp eq i32 %pred, 3
  ret i1 %cmp
}

define i1 @default_ne_true(i32 %x) {
; CHECK-LABEL: define i1 @default_ne_true(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[PRED:%.*]] = add i32 [[X]], 1
; CHECK-NEXT:    switch i32 [[X]], label %[[DEFAULT:.*]] [
; CHECK-NEXT:      i32 2, label %[[OTHER:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[OTHER]]:
; CHECK-NEXT:    ret i1 false
; CHECK:       [[DEFAULT]]:
; CHECK-NEXT:    ret i1 true
;
entry:
  %pred = add i32 %x, 1
  switch i32 %x, label %default [
  i32 2, label %other
  ]

other:
  ret i1 false

default:
  %cmp = icmp ne i32 %pred, 3
  ret i1 %cmp
}

; Negative tests for default, as it requires the mapping injective.

define i1 @default_eq_noninjective(i32 %x) {
; CHECK-LABEL: define i1 @default_eq_noninjective(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[PRED:%.*]] = and i32 [[X]], 1
; CHECK-NEXT:    switch i32 [[X]], label %[[DEFAULT:.*]] [
; CHECK-NEXT:      i32 2, label %[[OTHER:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[OTHER]]:
; CHECK-NEXT:    ret i1 false
; CHECK:       [[DEFAULT]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %pred = and i32 %x, 1
  switch i32 %x, label %default [
  i32 2, label %other
  ]

other:
  ret i1 false

default:
  %cmp = icmp eq i32 %pred, 3
  ret i1 %cmp
}

define i1 @default_ne_noninjective(i32 %x) {
; CHECK-LABEL: define i1 @default_ne_noninjective(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[PRED:%.*]] = and i32 [[X]], 1
; CHECK-NEXT:    switch i32 [[X]], label %[[DEFAULT:.*]] [
; CHECK-NEXT:      i32 2, label %[[OTHER:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[OTHER]]:
; CHECK-NEXT:    ret i1 false
; CHECK:       [[DEFAULT]]:
; CHECK-NEXT:    ret i1 true
;
entry:
  %pred = and i32 %x, 1
  switch i32 %x, label %default [
  i32 2, label %other
  ]

other:
  ret i1 false

default:
  %cmp = icmp ne i32 %pred, 3
  ret i1 %cmp
}
