; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=correlated-propagation < %s | FileCheck %s

; Test for regression after 87f312aad6e from trying to use the uselist of constantdata

define ptr @_ZN4aiir6Region15getParentOfTypeINS_19FunctionOpInterfaceEEET_v() {
; CHECK-LABEL: define ptr @_ZN4aiir6Region15getParentOfTypeINS_19FunctionOpInterfaceEEET_v() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CALL_FCA_0_EXTRACT:%.*]] = extractvalue [2 x i64] zeroinitializer, 0
; CHECK-NEXT:    [[I2P:%.*]] = inttoptr i64 [[CALL_FCA_0_EXTRACT]] to ptr
; CHECK-NEXT:    [[CMP_I:%.*]] = icmp ne ptr [[I2P]], null
; CHECK-NEXT:    br i1 [[CMP_I]], label %[[CLEANUP:.*]], label %[[DO_COND:.*]]
; CHECK:       [[DO_COND]]:
; CHECK-NEXT:    br label %[[CLEANUP]]
; CHECK:       [[CLEANUP]]:
; CHECK-NEXT:    ret ptr [[I2P]]
;
entry:
  %call.fca.0.extract = extractvalue [2 x i64] zeroinitializer, 0
  %i2p = inttoptr i64 %call.fca.0.extract to ptr
  %cmp.i = icmp ne ptr %i2p, null
  br i1 %cmp.i, label %cleanup, label %do.cond

do.cond:                                          ; preds = %entry
  br label %cleanup

cleanup:                                          ; preds = %do.cond, %entry
  %phi = phi ptr [ %i2p, %entry ], [ null, %do.cond ]
  ret ptr %phi
}
