; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=correlated-propagation -S | FileCheck %s

define i32 @main() {
; CHECK-LABEL: define i32 @main() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[UNREACHABLE_BLOCK:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = insertvalue [2 x i32] [[TMP0]], i32 0, 1
; CHECK-NEXT:    [[EXTRACT_VALUE:%.*]] = extractvalue [2 x i32] [[TMP0]], 0
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[SINK_VALUE:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[EXTRACT_VALUE]], %[[UNREACHABLE_BLOCK]] ]
; CHECK-NEXT:    ret i32 0
;
entry:
  br label %exit

unreachable.block:                                ; No predecessors!
  %0 = insertvalue [2 x i32] %0, i32 0, 1
  %extract.value = extractvalue [2 x i32] %0, 0
  br label %exit

exit:                             ; preds = %unreachable.block, %entry
  %sink.value = phi i32 [ 0, %entry ], [ %extract.value, %unreachable.block ]
  ret i32 0
}
