; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=correlated-propagation < %s | FileCheck %s

; Basic case from issue #138636: zext(i1) stored in the false-branch successor
; should be folded to 0 because the branch condition is known false there.
define void @zext_i1_false_branch(ptr writeonly %p0, i1 %cond, ptr writeonly %p1) {
; CHECK-LABEL: @zext_i1_false_branch(
; CHECK-NEXT:    [[EXT:%.*]] = zext i1 [[COND:%.*]] to i8
; CHECK-NEXT:    store i8 [[EXT]], ptr [[P0:%.*]], align 1
; CHECK-NEXT:    br i1 [[COND]], label [[TRUE:%.*]], label [[FALSE:%.*]]
; CHECK:       false:
; CHECK-NEXT:    store i8 0, ptr [[P1:%.*]], align 1
; CHECK-NEXT:    br label [[END:%.*]]
; CHECK:       true:
; CHECK-NEXT:    br label [[END]]
; CHECK:       end:
; CHECK-NEXT:    ret void
;
  %ext = zext i1 %cond to i8
  store i8 %ext, ptr %p0, align 1
  br i1 %cond, label %true, label %false

false:
  store i8 %ext, ptr %p1, align 1
  br label %end

true:
  br label %end

end:
  ret void
}

; In the true-branch, zext(i1 true) == 1.
define void @zext_i1_true_branch(ptr writeonly %p0, i1 %cond, ptr writeonly %p1) {
; CHECK-LABEL: @zext_i1_true_branch(
; CHECK-NEXT:    [[EXT:%.*]] = zext i1 [[COND:%.*]] to i8
; CHECK-NEXT:    store i8 [[EXT]], ptr [[P0:%.*]], align 1
; CHECK-NEXT:    br i1 [[COND]], label [[TRUE:%.*]], label [[FALSE:%.*]]
; CHECK:       false:
; CHECK-NEXT:    br label [[END:%.*]]
; CHECK:       true:
; CHECK-NEXT:    store i8 1, ptr [[P1:%.*]], align 1
; CHECK-NEXT:    br label [[END]]
; CHECK:       end:
; CHECK-NEXT:    ret void
;
  %ext = zext i1 %cond to i8
  store i8 %ext, ptr %p0, align 1
  br i1 %cond, label %true, label %false

false:
  br label %end

true:
  store i8 %ext, ptr %p1, align 1
  br label %end

end:
  ret void
}

; The entry block store cannot be folded — %cond is not yet known there.
define void @no_fold_in_entry(ptr writeonly %p0, i1 %cond) {
; CHECK-LABEL: @no_fold_in_entry(
; CHECK-NEXT:    [[EXT:%.*]] = zext i1 [[COND:%.*]] to i8
; CHECK-NEXT:    store i8 [[EXT]], ptr [[P0:%.*]], align 1
; CHECK-NEXT:    br i1 [[COND]], label [[TRUE:%.*]], label [[FALSE:%.*]]
; CHECK:       false:
; CHECK-NEXT:    br label [[END:%.*]]
; CHECK:       true:
; CHECK-NEXT:    br label [[END]]
; CHECK:       end:
; CHECK-NEXT:    ret void
;
  %ext = zext i1 %cond to i8
  store i8 %ext, ptr %p0, align 1
  br i1 %cond, label %true, label %false

false:
  br label %end

true:
  br label %end

end:
  ret void
}

; zext i1 to i32 variant — same optimization applies.
define void @zext_i1_to_i32_false_branch(ptr writeonly %p0, i1 %cond, ptr writeonly %p1) {
; CHECK-LABEL: @zext_i1_to_i32_false_branch(
; CHECK-NEXT:    [[EXT:%.*]] = zext i1 [[COND:%.*]] to i32
; CHECK-NEXT:    store i32 [[EXT]], ptr [[P0:%.*]], align 4
; CHECK-NEXT:    br i1 [[COND]], label [[TRUE:%.*]], label [[FALSE:%.*]]
; CHECK:       false:
; CHECK-NEXT:    store i32 0, ptr [[P1:%.*]], align 4
; CHECK-NEXT:    br label [[END:%.*]]
; CHECK:       true:
; CHECK-NEXT:    br label [[END]]
; CHECK:       end:
; CHECK-NEXT:    ret void
;
  %ext = zext i1 %cond to i32
  store i32 %ext, ptr %p0, align 4
  br i1 %cond, label %true, label %false

false:
  store i32 %ext, ptr %p1, align 4
  br label %end

true:
  br label %end

end:
  ret void
}

; Value derived from icmp: %cmp == 0 is known false in the true branch,
; so %ext == 1.
define void @zext_icmp_true_branch(ptr writeonly %p0, i32 %x, ptr writeonly %p1) {
; CHECK-LABEL: @zext_icmp_true_branch(
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[X:%.*]], 0
; CHECK-NEXT:    [[EXT:%.*]] = zext i1 [[CMP]] to i8
; CHECK-NEXT:    store i8 [[EXT]], ptr [[P0:%.*]], align 1
; CHECK-NEXT:    br i1 [[CMP]], label [[TRUE:%.*]], label [[FALSE:%.*]]
; CHECK:       false:
; CHECK-NEXT:    store i8 0, ptr [[P1:%.*]], align 1
; CHECK-NEXT:    br label [[END:%.*]]
; CHECK:       true:
; CHECK-NEXT:    br label [[END]]
; CHECK:       end:
; CHECK-NEXT:    ret void
;
  %cmp = icmp eq i32 %x, 0
  %ext = zext i1 %cmp to i8
  store i8 %ext, ptr %p0, align 1
  br i1 %cmp, label %true, label %false

false:
  store i8 %ext, ptr %p1, align 1
  br label %end

true:
  br label %end

end:
  ret void
}

; Already a constant — nothing to do.
define void @already_constant(ptr writeonly %p) {
; CHECK-LABEL: @already_constant(
; CHECK-NEXT:    store i8 0, ptr [[P:%.*]], align 1
; CHECK-NEXT:    ret void
;
  store i8 0, ptr %p, align 1
  ret void
}
