; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=instcombine -mtriple=amdgcn-amd-amdhsa %s | FileCheck %s

; TODO: We should use UniformityAnalysis instead of just checking for
; trivially uniform constants. In that case, this test would also be optimized.
define amdgpu_kernel void @v_wave_match_sgpr(ptr addrspace(1) %out, i32 %src1, i32 %src2) {
; CHECK-LABEL: @v_wave_match_sgpr(
; CHECK-NEXT:    [[V:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[SRC1:%.*]], i32 [[SRC2:%.*]])
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[OUT:%.*]], align 4
; CHECK-NEXT:    ret void
;
  %v = call i32 @llvm.amdgcn.wave.match.b32(i32 %src1, i32 %src2)
  store i32 %v, ptr addrspace(1) %out
  ret void
}

define amdgpu_kernel void @v_wave_match_vgpr(i32 addrspace(1)* %out) {
; CHECK-LABEL: @v_wave_match_vgpr(
; CHECK-NEXT:    [[TIDX:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; CHECK-NEXT:    [[TIDY:%.*]] = call i32 @llvm.amdgcn.workitem.id.y()
; CHECK-NEXT:    [[V:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TIDX]], i32 [[TIDY]])
; CHECK-NEXT:    [[TMP1:%.*]] = sext i32 [[TIDX]] to i64
; CHECK-NEXT:    [[OUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT:%.*]], i64 [[TMP1]]
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[OUT_PTR]], align 4
; CHECK-NEXT:    ret void
;
  %tidx = call i32 @llvm.amdgcn.workitem.id.x()
  %tidy = call i32 @llvm.amdgcn.workitem.id.y()
  %v = call i32 @llvm.amdgcn.wave.match.b32(i32 %tidx, i32 %tidy)
  %out_ptr = getelementptr i32, i32 addrspace(1)* %out, i32 %tidx
  store i32 %v, i32 addrspace(1)* %out_ptr
  ret void
}

define amdgpu_kernel void @v_wave_match_vgpr_expression(i32 addrspace(1)* %out) {
; CHECK-LABEL: @v_wave_match_vgpr_expression(
; CHECK-NEXT:    [[TIDX:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; CHECK-NEXT:    [[TID2:%.*]] = add i32 [[TIDX]], 1
; CHECK-NEXT:    [[TIDY:%.*]] = call i32 @llvm.amdgcn.workitem.id.y()
; CHECK-NEXT:    [[V:%.*]] = call i32 @llvm.amdgcn.wave.match.b32(i32 [[TID2]], i32 [[TIDY]])
; CHECK-NEXT:    [[TMP1:%.*]] = sext i32 [[TIDX]] to i64
; CHECK-NEXT:    [[OUT_PTR:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT:%.*]], i64 [[TMP1]]
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[OUT_PTR]], align 4
; CHECK-NEXT:    ret void
;
  %tidx = call i32 @llvm.amdgcn.workitem.id.x()
  %tid2 = add i32 %tidx, 1
  %tidy = call i32 @llvm.amdgcn.workitem.id.y()
  %v = call i32 @llvm.amdgcn.wave.match.b32(i32 %tid2, i32 %tidy)
  %out_ptr = getelementptr i32, i32 addrspace(1)* %out, i32 %tidx
  store i32 %v, i32 addrspace(1)* %out_ptr
  ret void
}

define amdgpu_kernel void @v_wave_match_constant(ptr addrspace(1) %out, i32 %src) {
; CHECK-LABEL: @v_wave_match_constant(
; CHECK-NEXT:    [[V:%.*]] = call i32 @llvm.amdgcn.ballot.i32(i1 true)
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[OUT:%.*]], align 4
; CHECK-NEXT:    ret void
;
  %v = call i32 @llvm.amdgcn.wave.match.b32(i32 7, i32 7)
  store i32 %v, ptr addrspace(1) %out
  ret void
}

define amdgpu_kernel void @v_wave_match_undef(ptr addrspace(1) %out, i32 %src) {
; CHECK-LABEL: @v_wave_match_undef(
; CHECK-NEXT:    [[V:%.*]] = call i32 @llvm.amdgcn.ballot.i32(i1 true)
; CHECK-NEXT:    store i32 [[V]], ptr addrspace(1) [[OUT:%.*]], align 4
; CHECK-NEXT:    ret void
;
  %v = call i32 @llvm.amdgcn.wave.match.b32(i32 undef, i32 undef)
  store i32 %v, ptr addrspace(1) %out
  ret void
}
