; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1200 -passes=instcombine -S < %s | FileCheck -check-prefixes=GFX1200-W32 %s
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 -passes=instcombine -S < %s | FileCheck -check-prefixes=GFX11-W32 %s
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 -mattr=+wavefrontsize64 -passes=instcombine -S < %s | FileCheck -check-prefixes=GFX11-W64 %s
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -passes=instcombine -S < %s | FileCheck -check-prefixes=GFX9 %s

; ds_bpermute((tid ^ 1) << 2, val) -> update.dpp row_xmask:1
define i32 @test_bpermute_xor1(i32 %val) {
; GFX1200-W32-LABEL: define i32 @test_bpermute_xor1(
; GFX1200-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0:[0-9]+]] {
; GFX1200-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.update.dpp.i32(i32 poison, i32 [[VAL]], i32 353, i32 15, i32 15, i1 true)
; GFX1200-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W32-LABEL: define i32 @test_bpermute_xor1(
; GFX11-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0:[0-9]+]] {
; GFX11-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.update.dpp.i32(i32 poison, i32 [[VAL]], i32 353, i32 15, i32 15, i1 true)
; GFX11-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W64-LABEL: define i32 @test_bpermute_xor1(
; GFX11-W64-SAME: i32 [[VAL:%.*]]) #[[ATTR0:[0-9]+]] {
; GFX11-W64-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX11-W64-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX11-W64-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 4
; GFX11-W64-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX11-W64-NEXT:    ret i32 [[RESULT]]
;
; GFX9-LABEL: define i32 @test_bpermute_xor1(
; GFX9-SAME: i32 [[VAL:%.*]]) #[[ATTR0:[0-9]+]] {
; GFX9-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX9-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX9-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 4
; GFX9-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX9-NEXT:    ret i32 [[RESULT]]
;
  %lane_id = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
  %xor_lane = xor i32 %lane_id, 1
  %byte_offset = shl i32 %xor_lane, 2
  %result = call i32 @llvm.amdgcn.ds.bpermute(i32 %byte_offset, i32 %val)
  ret i32 %result
}

; ds_bpermute((tid ^ 2) << 2, val) -> update.dpp row_xmask:2
define i32 @test_bpermute_xor2(i32 %val) {
; GFX1200-W32-LABEL: define i32 @test_bpermute_xor2(
; GFX1200-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX1200-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.update.dpp.i32(i32 poison, i32 [[VAL]], i32 354, i32 15, i32 15, i1 true)
; GFX1200-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W32-LABEL: define i32 @test_bpermute_xor2(
; GFX11-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.update.dpp.i32(i32 poison, i32 [[VAL]], i32 354, i32 15, i32 15, i1 true)
; GFX11-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W64-LABEL: define i32 @test_bpermute_xor2(
; GFX11-W64-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W64-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX11-W64-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX11-W64-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 8
; GFX11-W64-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX11-W64-NEXT:    ret i32 [[RESULT]]
;
; GFX9-LABEL: define i32 @test_bpermute_xor2(
; GFX9-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX9-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX9-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX9-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 8
; GFX9-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX9-NEXT:    ret i32 [[RESULT]]
;
  %lane_id = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
  %xor_lane = xor i32 %lane_id, 2
  %byte_offset = shl i32 %xor_lane, 2
  %result = call i32 @llvm.amdgcn.ds.bpermute(i32 %byte_offset, i32 %val)
  ret i32 %result
}

; ds_bpermute((tid ^ 4) << 2, val) -> update.dpp row_xmask:4
define i32 @test_bpermute_xor4(i32 %val) {
; GFX1200-W32-LABEL: define i32 @test_bpermute_xor4(
; GFX1200-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX1200-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.update.dpp.i32(i32 poison, i32 [[VAL]], i32 356, i32 15, i32 15, i1 true)
; GFX1200-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W32-LABEL: define i32 @test_bpermute_xor4(
; GFX11-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.update.dpp.i32(i32 poison, i32 [[VAL]], i32 356, i32 15, i32 15, i1 true)
; GFX11-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W64-LABEL: define i32 @test_bpermute_xor4(
; GFX11-W64-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W64-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX11-W64-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX11-W64-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 16
; GFX11-W64-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX11-W64-NEXT:    ret i32 [[RESULT]]
;
; GFX9-LABEL: define i32 @test_bpermute_xor4(
; GFX9-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX9-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX9-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX9-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 16
; GFX9-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX9-NEXT:    ret i32 [[RESULT]]
;
  %lane_id = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
  %xor_lane = xor i32 %lane_id, 4
  %byte_offset = shl i32 %xor_lane, 2
  %result = call i32 @llvm.amdgcn.ds.bpermute(i32 %byte_offset, i32 %val)
  ret i32 %result
}

; ds_bpermute((tid ^ 8) << 2, val) -> update.dpp row_xmask:8
define i32 @test_bpermute_xor8(i32 %val) {
; GFX1200-W32-LABEL: define i32 @test_bpermute_xor8(
; GFX1200-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX1200-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.update.dpp.i32(i32 poison, i32 [[VAL]], i32 360, i32 15, i32 15, i1 true)
; GFX1200-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W32-LABEL: define i32 @test_bpermute_xor8(
; GFX11-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.update.dpp.i32(i32 poison, i32 [[VAL]], i32 360, i32 15, i32 15, i1 true)
; GFX11-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W64-LABEL: define i32 @test_bpermute_xor8(
; GFX11-W64-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W64-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX11-W64-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX11-W64-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 32
; GFX11-W64-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX11-W64-NEXT:    ret i32 [[RESULT]]
;
; GFX9-LABEL: define i32 @test_bpermute_xor8(
; GFX9-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX9-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX9-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX9-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 32
; GFX9-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX9-NEXT:    ret i32 [[RESULT]]
;
  %lane_id = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
  %xor_lane = xor i32 %lane_id, 8
  %byte_offset = shl i32 %xor_lane, 2
  %result = call i32 @llvm.amdgcn.ds.bpermute(i32 %byte_offset, i32 %val)
  ret i32 %result
}

; ds_bpermute((tid ^ 15) << 2, val) -> update.dpp row_xmask:15
define i32 @test_bpermute_xor15(i32 %val) {
; GFX1200-W32-LABEL: define i32 @test_bpermute_xor15(
; GFX1200-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX1200-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.update.dpp.i32(i32 poison, i32 [[VAL]], i32 367, i32 15, i32 15, i1 true)
; GFX1200-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W32-LABEL: define i32 @test_bpermute_xor15(
; GFX11-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.update.dpp.i32(i32 poison, i32 [[VAL]], i32 367, i32 15, i32 15, i1 true)
; GFX11-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W64-LABEL: define i32 @test_bpermute_xor15(
; GFX11-W64-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W64-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX11-W64-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX11-W64-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 60
; GFX11-W64-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX11-W64-NEXT:    ret i32 [[RESULT]]
;
; GFX9-LABEL: define i32 @test_bpermute_xor15(
; GFX9-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX9-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX9-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX9-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 60
; GFX9-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX9-NEXT:    ret i32 [[RESULT]]
;
  %lane_id = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
  %xor_lane = xor i32 %lane_id, 15
  %byte_offset = shl i32 %xor_lane, 2
  %result = call i32 @llvm.amdgcn.ds.bpermute(i32 %byte_offset, i32 %val)
  ret i32 %result
}

; ds_bpermute((tid ^ 16) << 2, val) -> permlanex16 with identity
define i32 @test_bpermute_xor16(i32 %val) {
; GFX1200-W32-LABEL: define i32 @test_bpermute_xor16(
; GFX1200-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX1200-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.permlanex16.i32(i32 poison, i32 [[VAL]], i32 1985229328, i32 -19088744, i1 false, i1 false)
; GFX1200-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W32-LABEL: define i32 @test_bpermute_xor16(
; GFX11-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.permlanex16.i32(i32 poison, i32 [[VAL]], i32 1985229328, i32 -19088744, i1 false, i1 false)
; GFX11-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W64-LABEL: define i32 @test_bpermute_xor16(
; GFX11-W64-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W64-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX11-W64-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX11-W64-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 64
; GFX11-W64-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX11-W64-NEXT:    ret i32 [[RESULT]]
;
; GFX9-LABEL: define i32 @test_bpermute_xor16(
; GFX9-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX9-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX9-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX9-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 64
; GFX9-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX9-NEXT:    ret i32 [[RESULT]]
;
  %lane_id = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
  %xor_lane = xor i32 %lane_id, 16
  %byte_offset = shl i32 %xor_lane, 2
  %result = call i32 @llvm.amdgcn.ds.bpermute(i32 %byte_offset, i32 %val)
  ret i32 %result
}

; wave64: ds_bpermute((tid ^ 4) << 2, val) -> update.dpp row_xmask:4
define i32 @test_bpermute_xor4_wave64(i32 %val) {
; GFX1200-W32-LABEL: define i32 @test_bpermute_xor4_wave64(
; GFX1200-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX1200-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.update.dpp.i32(i32 poison, i32 [[VAL]], i32 356, i32 15, i32 15, i1 true)
; GFX1200-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W32-LABEL: define i32 @test_bpermute_xor4_wave64(
; GFX11-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.update.dpp.i32(i32 poison, i32 [[VAL]], i32 356, i32 15, i32 15, i1 true)
; GFX11-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W64-LABEL: define i32 @test_bpermute_xor4_wave64(
; GFX11-W64-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W64-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.update.dpp.i32(i32 poison, i32 [[VAL]], i32 356, i32 15, i32 15, i1 true)
; GFX11-W64-NEXT:    ret i32 [[RESULT]]
;
; GFX9-LABEL: define i32 @test_bpermute_xor4_wave64(
; GFX9-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX9-NEXT:    [[LO:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX9-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 65) i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 [[LO]])
; GFX9-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX9-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 16
; GFX9-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX9-NEXT:    ret i32 [[RESULT]]
;
  %lo = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
  %lane_id = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 %lo)
  %xor_lane = xor i32 %lane_id, 4
  %byte_offset = shl i32 %xor_lane, 2
  %result = call i32 @llvm.amdgcn.ds.bpermute(i32 %byte_offset, i32 %val)
  ret i32 %result
}

; wave64: ds_bpermute((tid ^ 16) << 2, val) -> permlanex16
define i32 @test_bpermute_xor16_wave64(i32 %val) {
; GFX1200-W32-LABEL: define i32 @test_bpermute_xor16_wave64(
; GFX1200-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX1200-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.permlanex16.i32(i32 poison, i32 [[VAL]], i32 1985229328, i32 -19088744, i1 false, i1 false)
; GFX1200-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W32-LABEL: define i32 @test_bpermute_xor16_wave64(
; GFX11-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.permlanex16.i32(i32 poison, i32 [[VAL]], i32 1985229328, i32 -19088744, i1 false, i1 false)
; GFX11-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W64-LABEL: define i32 @test_bpermute_xor16_wave64(
; GFX11-W64-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W64-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.permlanex16.i32(i32 poison, i32 [[VAL]], i32 1985229328, i32 -19088744, i1 false, i1 false)
; GFX11-W64-NEXT:    ret i32 [[RESULT]]
;
; GFX9-LABEL: define i32 @test_bpermute_xor16_wave64(
; GFX9-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX9-NEXT:    [[LO:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX9-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 65) i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 [[LO]])
; GFX9-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX9-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 64
; GFX9-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX9-NEXT:    ret i32 [[RESULT]]
;
  %lo = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
  %lane_id = call i32 @llvm.amdgcn.mbcnt.hi(i32 -1, i32 %lo)
  %xor_lane = xor i32 %lane_id, 16
  %byte_offset = shl i32 %xor_lane, 2
  %result = call i32 @llvm.amdgcn.ds.bpermute(i32 %byte_offset, i32 %val)
  ret i32 %result
}

; Negative: XOR mask 17 (> 15 and != 16) should not be optimized
define i32 @test_bpermute_xor17_negative(i32 %val) {
; GFX1200-W32-LABEL: define i32 @test_bpermute_xor17_negative(
; GFX1200-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX1200-W32-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX1200-W32-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX1200-W32-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 68
; GFX1200-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX1200-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W32-LABEL: define i32 @test_bpermute_xor17_negative(
; GFX11-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W32-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX11-W32-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX11-W32-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 68
; GFX11-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX11-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W64-LABEL: define i32 @test_bpermute_xor17_negative(
; GFX11-W64-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W64-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX11-W64-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX11-W64-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 68
; GFX11-W64-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX11-W64-NEXT:    ret i32 [[RESULT]]
;
; GFX9-LABEL: define i32 @test_bpermute_xor17_negative(
; GFX9-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX9-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX9-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX9-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 68
; GFX9-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX9-NEXT:    ret i32 [[RESULT]]
;
  %lane_id = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
  %xor_lane = xor i32 %lane_id, 17
  %byte_offset = shl i32 %xor_lane, 2
  %result = call i32 @llvm.amdgcn.ds.bpermute(i32 %byte_offset, i32 %val)
  ret i32 %result
}

; Negative: XOR mask 32 should not be optimized
define i32 @test_bpermute_xor32_negative(i32 %val) {
; GFX1200-W32-LABEL: define i32 @test_bpermute_xor32_negative(
; GFX1200-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX1200-W32-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX1200-W32-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX1200-W32-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 128
; GFX1200-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX1200-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W32-LABEL: define i32 @test_bpermute_xor32_negative(
; GFX11-W32-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W32-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX11-W32-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX11-W32-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 128
; GFX11-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX11-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W64-LABEL: define i32 @test_bpermute_xor32_negative(
; GFX11-W64-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX11-W64-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX11-W64-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX11-W64-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 128
; GFX11-W64-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX11-W64-NEXT:    ret i32 [[RESULT]]
;
; GFX9-LABEL: define i32 @test_bpermute_xor32_negative(
; GFX9-SAME: i32 [[VAL:%.*]]) #[[ATTR0]] {
; GFX9-NEXT:    [[LANE_ID:%.*]] = call range(i32 0, 33) i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; GFX9-NEXT:    [[XOR_LANE:%.*]] = shl nuw nsw i32 [[LANE_ID]], 2
; GFX9-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 128
; GFX9-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX9-NEXT:    ret i32 [[RESULT]]
;
  %lane_id = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
  %xor_lane = xor i32 %lane_id, 32
  %byte_offset = shl i32 %xor_lane, 2
  %result = call i32 @llvm.amdgcn.ds.bpermute(i32 %byte_offset, i32 %val)
  ret i32 %result
}

; Negative: index not derived from thread ID
define i32 @test_bpermute_xor_not_tid(i32 %val, i32 %idx) {
; GFX1200-W32-LABEL: define i32 @test_bpermute_xor_not_tid(
; GFX1200-W32-SAME: i32 [[VAL:%.*]], i32 [[IDX:%.*]]) #[[ATTR0]] {
; GFX1200-W32-NEXT:    [[XOR_LANE:%.*]] = shl i32 [[IDX]], 2
; GFX1200-W32-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 16
; GFX1200-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX1200-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W32-LABEL: define i32 @test_bpermute_xor_not_tid(
; GFX11-W32-SAME: i32 [[VAL:%.*]], i32 [[IDX:%.*]]) #[[ATTR0]] {
; GFX11-W32-NEXT:    [[XOR_LANE:%.*]] = shl i32 [[IDX]], 2
; GFX11-W32-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 16
; GFX11-W32-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX11-W32-NEXT:    ret i32 [[RESULT]]
;
; GFX11-W64-LABEL: define i32 @test_bpermute_xor_not_tid(
; GFX11-W64-SAME: i32 [[VAL:%.*]], i32 [[IDX:%.*]]) #[[ATTR0]] {
; GFX11-W64-NEXT:    [[XOR_LANE:%.*]] = shl i32 [[IDX]], 2
; GFX11-W64-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 16
; GFX11-W64-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX11-W64-NEXT:    ret i32 [[RESULT]]
;
; GFX9-LABEL: define i32 @test_bpermute_xor_not_tid(
; GFX9-SAME: i32 [[VAL:%.*]], i32 [[IDX:%.*]]) #[[ATTR0]] {
; GFX9-NEXT:    [[XOR_LANE:%.*]] = shl i32 [[IDX]], 2
; GFX9-NEXT:    [[BYTE_OFFSET:%.*]] = xor i32 [[XOR_LANE]], 16
; GFX9-NEXT:    [[RESULT:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[BYTE_OFFSET]], i32 [[VAL]])
; GFX9-NEXT:    ret i32 [[RESULT]]
;
  %xor_lane = xor i32 %idx, 4
  %byte_offset = shl i32 %xor_lane, 2
  %result = call i32 @llvm.amdgcn.ds.bpermute(i32 %byte_offset, i32 %val)
  ret i32 %result
}

declare i32 @llvm.amdgcn.mbcnt.lo(i32, i32)
declare i32 @llvm.amdgcn.mbcnt.hi(i32, i32)
declare i32 @llvm.amdgcn.ds.bpermute(i32, i32)
