; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -passes=instcombine -S < %s | FileCheck -check-prefix=WAVE64 %s
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1010 -passes=instcombine -S < %s | FileCheck -check-prefix=WAVE32 %s

; The "always true" amdgcn.icmp/amdgcn.fcmp fold reads EXEC, which is wave-size
; bits wide. The read_register must use that width and register name regardless
; of the return type, then zext/trunc.

; Return type wider than the wave size on wave32: read i32 exec_lo, then zext.
define i64 @fcmp_true_i64(float %x, float %y) {
; WAVE64-LABEL: @fcmp_true_i64(
; WAVE64-NEXT:    [[R:%.*]] = call i64 @llvm.read_register.i64(metadata [[META0:![0-9]+]]) #[[ATTR3:[0-9]+]]
; WAVE64-NEXT:    ret i64 [[R]]
;
; WAVE32-LABEL: @fcmp_true_i64(
; WAVE32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.read_register.i32(metadata [[META0:![0-9]+]]) #[[ATTR3:[0-9]+]]
; WAVE32-NEXT:    [[R:%.*]] = zext i32 [[TMP1]] to i64
; WAVE32-NEXT:    ret i64 [[R]]
;
  %r = call i64 @llvm.amdgcn.fcmp.i64.f32(float 0.0, float 0.0, i32 1)
  ret i64 %r
}

define i64 @icmp_true_i64(i32 %x, i32 %y) {
; WAVE64-LABEL: @icmp_true_i64(
; WAVE64-NEXT:    [[R:%.*]] = call i64 @llvm.read_register.i64(metadata [[META0]]) #[[ATTR3]]
; WAVE64-NEXT:    ret i64 [[R]]
;
; WAVE32-LABEL: @icmp_true_i64(
; WAVE32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.read_register.i32(metadata [[META0]]) #[[ATTR3]]
; WAVE32-NEXT:    [[R:%.*]] = zext i32 [[TMP1]] to i64
; WAVE32-NEXT:    ret i64 [[R]]
;
  %r = call i64 @llvm.amdgcn.icmp.i64.i32(i32 9, i32 8, i32 34)
  ret i64 %r
}

; Return type narrower than the wave size on wave64: read i64 exec, then trunc.
define i32 @fcmp_true_i32(float %x, float %y) {
; WAVE64-LABEL: @fcmp_true_i32(
; WAVE64-NEXT:    [[TMP1:%.*]] = call i64 @llvm.read_register.i64(metadata [[META0]]) #[[ATTR3]]
; WAVE64-NEXT:    [[R:%.*]] = trunc i64 [[TMP1]] to i32
; WAVE64-NEXT:    ret i32 [[R]]
;
; WAVE32-LABEL: @fcmp_true_i32(
; WAVE32-NEXT:    [[R:%.*]] = call i32 @llvm.read_register.i32(metadata [[META0]]) #[[ATTR3]]
; WAVE32-NEXT:    ret i32 [[R]]
;
  %r = call i32 @llvm.amdgcn.fcmp.i32.f32(float 0.0, float 0.0, i32 1)
  ret i32 %r
}

declare i64 @llvm.amdgcn.fcmp.i64.f32(float, float, i32 immarg)
declare i64 @llvm.amdgcn.icmp.i64.i32(i32, i32, i32 immarg)
declare i32 @llvm.amdgcn.fcmp.i32.f32(float, float, i32 immarg)
;.
; WAVE64: attributes #[[ATTR0:[0-9]+]] = { "target-cpu"="gfx900" }
; WAVE64: attributes #[[ATTR1:[0-9]+]] = { convergent nocallback nofree nounwind willreturn memory(none) "target-cpu"="gfx900" }
; WAVE64: attributes #[[ATTR2:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(read) }
; WAVE64: attributes #[[ATTR3]] = { convergent }
;.
; WAVE32: attributes #[[ATTR0:[0-9]+]] = { "target-cpu"="gfx1010" }
; WAVE32: attributes #[[ATTR1:[0-9]+]] = { convergent nocallback nofree nounwind willreturn memory(none) "target-cpu"="gfx1010" }
; WAVE32: attributes #[[ATTR2:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(read) }
; WAVE32: attributes #[[ATTR3]] = { convergent }
;.
; WAVE64: [[META0]] = !{!"exec"}
;.
; WAVE32: [[META0]] = !{!"exec_lo"}
;.
