; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes='instcombine' -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 < %s | FileCheck %s --check-prefix=GFX1250

; When amdgpu-no-cluster-id-x is set, calling the intrinsic is UB and the
; call should be folded to poison on any target.
define i32 @no_cluster_id_x() #0 {
; GFX1250-LABEL: define i32 @no_cluster_id_x(
; GFX1250-SAME: ) #[[ATTR0:[0-9]+]] {
; GFX1250-NEXT:  [[ENTRY:.*:]]
; GFX1250-NEXT:    ret i32 poison
;
entry:
  %tmp = call i32 @llvm.amdgcn.cluster.id.x()
  ret i32 %tmp
}

define i32 @no_cluster_id_y() #1 {
; GFX1250-LABEL: define i32 @no_cluster_id_y(
; GFX1250-SAME: ) #[[ATTR1:[0-9]+]] {
; GFX1250-NEXT:  [[ENTRY:.*:]]
; GFX1250-NEXT:    ret i32 poison
;
entry:
  %tmp = call i32 @llvm.amdgcn.cluster.id.y()
  ret i32 %tmp
}

define i32 @no_cluster_id_z() #2 {
; GFX1250-LABEL: define i32 @no_cluster_id_z(
; GFX1250-SAME: ) #[[ATTR2:[0-9]+]] {
; GFX1250-NEXT:  [[ENTRY:.*:]]
; GFX1250-NEXT:    ret i32 poison
;
entry:
  %tmp = call i32 @llvm.amdgcn.cluster.id.z()
  ret i32 %tmp
}

; Without the attribute, the call folds to poison on targets without the
; cluster feature (gfx1100), but is kept on cluster-capable targets (gfx1250).
define i32 @cluster_id_x_no_attr() {
; GFX1250-LABEL: define i32 @cluster_id_x_no_attr(
; GFX1250-SAME: ) #[[ATTR3:[0-9]+]] {
; GFX1250-NEXT:  [[ENTRY:.*:]]
; GFX1250-NEXT:    [[TMP:%.*]] = call i32 @llvm.amdgcn.cluster.id.x()
; GFX1250-NEXT:    ret i32 [[TMP]]
;
entry:
  %tmp = call i32 @llvm.amdgcn.cluster.id.x()
  ret i32 %tmp
}

declare i32 @llvm.amdgcn.cluster.id.x()
declare i32 @llvm.amdgcn.cluster.id.y()
declare i32 @llvm.amdgcn.cluster.id.z()

attributes #0 = { "amdgpu-no-cluster-id-x" }
attributes #1 = { "amdgpu-no-cluster-id-y" }
attributes #2 = { "amdgpu-no-cluster-id-z" }
