; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes='instcombine' -mtriple=amdgcn-amd-amdhsa < %s | FileCheck %s

; When amdgpu-no-dispatch-ptr is set, calling the intrinsic is UB and the
; call should be folded to poison.
define ptr addrspace(4) @no_dispatch_ptr() #0 {
; CHECK-LABEL: define ptr addrspace(4) @no_dispatch_ptr(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret ptr addrspace(4) poison
;
entry:
  %tmp = call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
  ret ptr addrspace(4) %tmp
}

; When amdgpu-no-dispatch-ptr is set, a load from the intrinsic's returned
; pointer is also UB. The call folds to poison and loading from poison yields
; poison via existing InstCombine rules.
define i32 @no_dispatch_ptr_load() #0 {
; CHECK-LABEL: define i32 @no_dispatch_ptr_load(
; CHECK-SAME: ) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store i1 true, ptr poison, align 1
; CHECK-NEXT:    ret i32 poison
;
entry:
  %ptr = call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
  %val = load i32, ptr addrspace(4) %ptr
  ret i32 %val
}

; Without the attribute the call is kept.
define ptr addrspace(4) @dispatch_ptr_no_attr() {
; CHECK-LABEL: define ptr addrspace(4) @dispatch_ptr_no_attr() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP:%.*]] = call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
; CHECK-NEXT:    ret ptr addrspace(4) [[TMP]]
;
entry:
  %tmp = call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
  ret ptr addrspace(4) %tmp
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare ptr addrspace(4) @llvm.amdgcn.dispatch.ptr() #1

attributes #0 = { "amdgpu-no-dispatch-ptr" }
attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
