; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes='instcombine' -mtriple=amdgcn-amd-amdhsa < %s | FileCheck %s

; When amdgpu-no-workgroup-id-x is set, calling the intrinsic is UB and the
; call should be folded to poison.
define i32 @no_workgroup_id_x() #0 {
; CHECK-LABEL: define i32 @no_workgroup_id_x(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret i32 poison
;
entry:
  %tmp = call i32 @llvm.amdgcn.workgroup.id.x()
  ret i32 %tmp
}

define i32 @no_workgroup_id_y() #1 {
; CHECK-LABEL: define i32 @no_workgroup_id_y(
; CHECK-SAME: ) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret i32 poison
;
entry:
  %tmp = call i32 @llvm.amdgcn.workgroup.id.y()
  ret i32 %tmp
}

define i32 @no_workgroup_id_z() #2 {
; CHECK-LABEL: define i32 @no_workgroup_id_z(
; CHECK-SAME: ) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret i32 poison
;
entry:
  %tmp = call i32 @llvm.amdgcn.workgroup.id.z()
  ret i32 %tmp
}

; Without the attribute the calls are kept.
define i32 @workgroup_id_x_no_attr() {
; CHECK-LABEL: define i32 @workgroup_id_x_no_attr() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP:%.*]] = call i32 @llvm.amdgcn.workgroup.id.x()
; CHECK-NEXT:    ret i32 [[TMP]]
;
entry:
  %tmp = call i32 @llvm.amdgcn.workgroup.id.x()
  ret i32 %tmp
}

declare i32 @llvm.amdgcn.workgroup.id.x()
declare i32 @llvm.amdgcn.workgroup.id.y()
declare i32 @llvm.amdgcn.workgroup.id.z()

attributes #0 = { "amdgpu-no-workgroup-id-x" }
attributes #1 = { "amdgpu-no-workgroup-id-y" }
attributes #2 = { "amdgpu-no-workgroup-id-z" }
