; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=amdgcn -passes=instcombine -S | FileCheck %s --check-prefixes=CHECK,DEFAULT
; RUN: opt < %s -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -passes=instcombine -S | FileCheck %s --check-prefixes=CHECK,GFX9
; RUN: opt < %s -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1010 -passes=instcombine -S | FileCheck %s --check-prefixes=CHECK,GFX10
; RUN: opt < %s -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 -passes=instcombine -S | FileCheck %s --check-prefixes=CHECK,GFX11

; Test that the m0 operand is folded to poison for message types that don't use it.
; For the default target (no mcpu), conflicting encodings (IDs 2, 3) should NOT be folded.

; MSG_INTERRUPT (1) DOES use m0 - should NOT be folded
define void @test_sendmsg_interrupt(i32 %val) {
; CHECK-LABEL: @test_sendmsg_interrupt(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 1, i32 [[VAL:%.*]])
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 1, i32 %val)
  ret void
}

; MSG_GS (2) + GS_OP_EMIT (2 << 4) DOES use m0 (pre-GFX11) - should NOT be folded
; On GFX11+ this is MSG_HS_TESSFACTOR which also uses m0 - should NOT be folded
; On default target, this should NOT be folded (conflicting encoding)
define void @test_sendmsg_gs_emit(i32 %val) {
; DEFAULT-LABEL: @test_sendmsg_gs_emit(
; DEFAULT-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 34, i32 [[VAL:%.*]])
; DEFAULT-NEXT:    ret void
;
; GFX9-LABEL: @test_sendmsg_gs_emit(
; GFX9-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 34, i32 [[VAL:%.*]])
; GFX9-NEXT:    ret void
;
; GFX10-LABEL: @test_sendmsg_gs_emit(
; GFX10-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 34, i32 [[VAL:%.*]])
; GFX10-NEXT:    ret void
;
; GFX11-LABEL: @test_sendmsg_gs_emit(
; GFX11-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 34, i32 [[VAL:%.*]])
; GFX11-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 34, i32 %val)
  ret void
}

; MSG_GS_DONE (3) DOES use m0 (pre-GFX11) - should NOT be folded
; On GFX11+ this is ID_DEALLOC_VGPRS which doesn't use m0
; On default target, this should NOT be folded (conflicting encoding)
define void @test_sendmsg_gs_done(i32 %val) {
; DEFAULT-LABEL: @test_sendmsg_gs_done(
; DEFAULT-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 3, i32 [[VAL:%.*]])
; DEFAULT-NEXT:    ret void
;
; GFX9-LABEL: @test_sendmsg_gs_done(
; GFX9-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 3, i32 [[VAL:%.*]])
; GFX9-NEXT:    ret void
;
; GFX10-LABEL: @test_sendmsg_gs_done(
; GFX10-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 3, i32 [[VAL:%.*]])
; GFX10-NEXT:    ret void
;
; GFX11-LABEL: @test_sendmsg_gs_done(
; GFX11-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 3, i32 poison)
; GFX11-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 3, i32 %val)
  ret void
}

; MSG_SAVEWAVE (4) doesn't use m0 (GFX8-GFX10)
define void @test_sendmsg_savewave(i32 %val) {
; CHECK-LABEL: @test_sendmsg_savewave(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 4, i32 poison)
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 4, i32 %val)
  ret void
}

; MSG_STALL_WAVE_GEN (5) doesn't use m0 (GFX9-GFX11)
define void @test_sendmsg_stall_wave_gen(i32 %val) {
; CHECK-LABEL: @test_sendmsg_stall_wave_gen(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 5, i32 poison)
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 5, i32 %val)
  ret void
}

; MSG_HALT_WAVES (6) doesn't use m0 (GFX9-GFX11)
define void @test_sendmsg_halt_waves(i32 %val) {
; CHECK-LABEL: @test_sendmsg_halt_waves(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 6, i32 poison)
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 6, i32 %val)
  ret void
}

; MSG_ORDERED_PS_DONE (7) doesn't use m0 (GFX9-GFX10)
define void @test_sendmsg_ordered_ps_done(i32 %val) {
; CHECK-LABEL: @test_sendmsg_ordered_ps_done(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 7, i32 poison)
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 7, i32 %val)
  ret void
}

; MSG_EARLY_PRIM_DEALLOC (8) doesn't use m0 (GFX9 only)
define void @test_sendmsg_early_prim_dealloc(i32 %val) {
; CHECK-LABEL: @test_sendmsg_early_prim_dealloc(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 8, i32 poison)
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 8, i32 %val)
  ret void
}

; MSG_GS_ALLOC_REQ (9) DOES use m0 - should NOT be folded
define void @test_sendmsg_gs_alloc_req(i32 %val) {
; CHECK-LABEL: @test_sendmsg_gs_alloc_req(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 9, i32 [[VAL:%.*]])
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 9, i32 %val)
  ret void
}

; MSG_GET_DOORBELL (10) doesn't use m0 (GFX9-GFX10)
define void @test_sendmsg_get_doorbell(i32 %val) {
; CHECK-LABEL: @test_sendmsg_get_doorbell(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 10, i32 poison)
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 10, i32 %val)
  ret void
}

; MSG_GET_DDID (11) doesn't use m0 (GFX10 only)
define void @test_sendmsg_get_ddid(i32 %val) {
; CHECK-LABEL: @test_sendmsg_get_ddid(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 11, i32 poison)
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 11, i32 %val)
  ret void
}

; MSG_SYSMSG (15) doesn't use m0
define void @test_sendmsg_sysmsg(i32 %val) {
; CHECK-LABEL: @test_sendmsg_sysmsg(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 15, i32 poison)
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 15, i32 %val)
  ret void
}

; Test sendmsghalt as well - MSG_INTERRUPT (1) DOES use m0 - should NOT be folded
define void @test_sendmsghalt_interrupt(i32 %val) {
; CHECK-LABEL: @test_sendmsghalt_interrupt(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsghalt(i32 1, i32 [[VAL:%.*]])
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsghalt(i32 1, i32 %val)
  ret void
}

; Test sendmsghalt - MSG_GS_ALLOC_REQ (9) DOES use m0 - should NOT be folded
define void @test_sendmsghalt_gs_alloc_req(i32 %val) {
; CHECK-LABEL: @test_sendmsghalt_gs_alloc_req(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsghalt(i32 9, i32 [[VAL:%.*]])
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsghalt(i32 9, i32 %val)
  ret void
}

; m0 already poison - should be a no-op
define void @test_sendmsg_already_poison() {
; CHECK-LABEL: @test_sendmsg_already_poison(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 1, i32 poison)
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 1, i32 poison)
  ret void
}

; Test that noundef attribute is dropped when folding to poison
; Using MSG_SAVEWAVE (4) which doesn't use m0
define void @test_sendmsg_noundef(i32 noundef %val) {
; CHECK-LABEL: @test_sendmsg_noundef(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 4, i32 poison)
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 4, i32 noundef %val)
  ret void
}

; Test unknown message ID - should NOT be folded (future-proofing)
define void @test_sendmsg_unknown_id(i32 %val) {
; CHECK-LABEL: @test_sendmsg_unknown_id(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 14, i32 [[VAL:%.*]])
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 14, i32 %val)
  ret void
}

; Test MSG_HS_TESSFACTOR (2) on GFX11+ - DOES use m0, should NOT be folded
; On pre-GFX11, this is MSG_GS which also uses m0
define void @test_sendmsg_hs_tessfactor(i32 %val) {
; CHECK-LABEL: @test_sendmsg_hs_tessfactor(
; CHECK-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 2, i32 [[VAL:%.*]])
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 2, i32 %val)
  ret void
}

; Test MSG_DEALLOC_VGPRS (3) on GFX11+ - doesn't use m0
; On default target, this should NOT be folded (conflicting encoding with MSG_GS_DONE)
define void @test_sendmsg_dealloc_vgprs(i32 %val) {
; DEFAULT-LABEL: @test_sendmsg_dealloc_vgprs(
; DEFAULT-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 3, i32 [[VAL:%.*]])
; DEFAULT-NEXT:    ret void
;
; GFX9-LABEL: @test_sendmsg_dealloc_vgprs(
; GFX9-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 3, i32 [[VAL:%.*]])
; GFX9-NEXT:    ret void
;
; GFX10-LABEL: @test_sendmsg_dealloc_vgprs(
; GFX10-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 3, i32 [[VAL:%.*]])
; GFX10-NEXT:    ret void
;
; GFX11-LABEL: @test_sendmsg_dealloc_vgprs(
; GFX11-NEXT:    call void @llvm.amdgcn.s.sendmsg(i32 3, i32 poison)
; GFX11-NEXT:    ret void
;
  call void @llvm.amdgcn.s.sendmsg(i32 3, i32 %val)
  ret void
}

declare void @llvm.amdgcn.s.sendmsg(i32 immarg, i32)
declare void @llvm.amdgcn.s.sendmsghalt(i32 immarg, i32)
