; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --include-generated-funcs
; RUN: opt -S -passes=iroutliner -ir-outlining-no-cost < %s | FileCheck %s

target datalayout = "A5"

define i32 @func_with_outgoing_new_allocas() {
bb:
  %i = tail call i32 @func0(i32 0, i32 1)
  %i1 = or i32 0, %i
  %i2 = tail call i32 @func0(i32 %i1, i32 0)
  %i3 = or i32 %i1, %i2
  %i4 = tail call i32 @llvm.foo(i32 %i3, i32 0)
  ret i32 0
}

declare i32 @func0(i32, i32)
declare i32 @llvm.foo(i32, i32)

; CHECK-LABEL: define {{[^@]+}}@func_with_outgoing_new_allocas() {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    [[I3_LOC:%.*]] = alloca i32, align 4, addrspace(5)
; CHECK-NEXT:    [[I1_LOC:%.*]] = alloca i32, align 4, addrspace(5)
; CHECK-NEXT:    call void @llvm.lifetime.start.p5(ptr addrspace(5) [[I1_LOC]])
; CHECK-NEXT:    call void @outlined_ir_func_0(i32 0, i32 1, ptr addrspace(5) [[I1_LOC]])
; CHECK-NEXT:    [[I1_RELOAD:%.*]] = load i32, ptr addrspace(5) [[I1_LOC]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.end.p5(ptr addrspace(5) [[I1_LOC]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p5(ptr addrspace(5) [[I3_LOC]])
; CHECK-NEXT:    call void @outlined_ir_func_0(i32 [[I1_RELOAD]], i32 0, ptr addrspace(5) [[I3_LOC]])
; CHECK-NEXT:    [[I3_RELOAD:%.*]] = load i32, ptr addrspace(5) [[I3_LOC]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.end.p5(ptr addrspace(5) [[I3_LOC]])
; CHECK-NEXT:    [[I4:%.*]] = tail call i32 @llvm.foo(i32 [[I3_RELOAD]], i32 0)
; CHECK-NEXT:    ret i32 0
;
;
; CHECK-LABEL: define {{[^@]+}}@outlined_ir_func_0
; CHECK-SAME: (i32 [[TMP0:%.*]], i32 [[TMP1:%.*]], ptr addrspace(5) [[TMP2:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  newFuncRoot:
; CHECK-NEXT:    br label [[BB_TO_OUTLINE:%.*]]
; CHECK:       bb_to_outline:
; CHECK-NEXT:    [[I:%.*]] = tail call i32 @func0(i32 [[TMP0]], i32 [[TMP1]])
; CHECK-NEXT:    [[I1:%.*]] = or i32 [[TMP0]], [[I]]
; CHECK-NEXT:    br label [[BB_AFTER_OUTLINE_EXITSTUB:%.*]]
; CHECK:       bb_after_outline.exitStub:
; CHECK-NEXT:    store i32 [[I1]], ptr addrspace(5) [[TMP2]], align 4
; CHECK-NEXT:    ret void
;
