; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=verify,iroutliner -ir-outlining-no-cost < %s | FileCheck %s

; Do not outline structurally similar regions when doing so would replace a
; non-uniform immarg constant with an outlined-function argument.

declare void @llvm.memcpy.p0.p0.i64(ptr noalias writeonly captures(none), ptr noalias readonly captures(none), i64, i1 immarg)

@slot = global ptr null, align 8
@buf = global [1 x i8] zeroinitializer, align 1

define ptr @PR194733() {
; CHECK-LABEL: define ptr @PR194733() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 false, label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr @slot, align 8
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr @buf, ptr @buf, i64 0, i1 false)
; CHECK-NEXT:    ret ptr null
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr @slot, align 8
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr @buf, ptr @buf, i64 0, i1 true)
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr @slot, align 8
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr @buf, ptr @buf, i64 0, i1 false)
; CHECK-NEXT:    ret ptr null
;
entry:
  br i1 false, label %then, label %else

then:
  %0 = load ptr, ptr @slot, align 8
  call void @llvm.memcpy.p0.p0.i64(ptr @buf, ptr @buf, i64 0, i1 false)
  ret ptr null

else:
  %1 = load ptr, ptr @slot, align 8
  call void @llvm.memcpy.p0.p0.i64(ptr @buf, ptr @buf, i64 0, i1 true)
  %2 = load ptr, ptr @slot, align 8
  call void @llvm.memcpy.p0.p0.i64(ptr @buf, ptr @buf, i64 0, i1 false)
  ret ptr null
}
