; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs
; RUN: opt -S -passes=verify,iroutliner -ir-outlining-no-cost < %s | FileCheck %s

; Make sure that we outline from all three of these functions, and that
; the first instruction in the module is included when it is the only
; instruction in the first basic block.

define void @f1() {
bb:
  br label %bb1
bb1:
  br label %bb2
bb2:
  ret void
}

define void @f2() {
bb:
  br label %bb1
bb1:
  br label %bb2
bb2:
  ret void
}

define void @f3() {
bb:
  br label %bb1
bb1:
  br label %bb2
bb2:
  ret void
}
; CHECK-LABEL: @f1(
; CHECK-NEXT:  bb:
; CHECK-NEXT:    call void @outlined_ir_func_0()
; CHECK-NEXT:    br label [[BB2:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: @f2(
; CHECK-NEXT:  bb:
; CHECK-NEXT:    call void @outlined_ir_func_0()
; CHECK-NEXT:    br label [[BB2:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: @f3(
; CHECK-NEXT:  bb:
; CHECK-NEXT:    call void @outlined_ir_func_0()
; CHECK-NEXT:    br label [[BB2:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal void @outlined_ir_func_0(
; CHECK-NEXT:  newFuncRoot:
; CHECK-NEXT:    br label [[BB_TO_OUTLINE:%.*]]
; CHECK:       bb_to_outline:
; CHECK-NEXT:    br label [[BB1:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    br label [[BB2_EXITSTUB:%.*]]
; CHECK:       bb2.exitStub:
; CHECK-NEXT:    ret void
;
