; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs
; RUN: opt -S -passes=verify,iroutliner -ir-outlining-no-cost < %s | FileCheck %s

; Check that we do not outline musttail calls when swifttailcc is present.

declare swifttailcc void @musttail()

define swifttailcc void @f1() {
  %a = alloca i32, align 4
  store i32 2, ptr %a, align 4
  musttail call swifttailcc void @musttail()
  ret void
}

define swifttailcc void @f2() {
  %a = alloca i32, align 4
  store i32 2, ptr %a, align 4
  musttail call swifttailcc void @musttail()
  ret void
}
; CHECK-LABEL: @f1(
; CHECK-NEXT:    [[A:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 2, ptr [[A]], align 4
; CHECK-NEXT:    musttail call swifttailcc void @musttail()
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: @f2(
; CHECK-NEXT:    [[A:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 2, ptr [[A]], align 4
; CHECK-NEXT:    musttail call swifttailcc void @musttail()
; CHECK-NEXT:    ret void
;
