; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs --version 6
; RUN: opt -S -passes=verify,iroutliner -ir-outlining-no-cost < %s | FileCheck %s


define ptr @outliner_crash(ptr %arrayidx9.i) {
entry:
  %cmp = icmp eq i8 0, 4
  br i1 %cmp, label %if.then202.i, label %do.end213.i

if.then202.i:                                     ; preds = %do.body.i
  %0 = load i8, ptr null, align 1
  %arrayidx14.i290 = getelementptr [2 x [3 x i8]], ptr getelementptr inbounds nuw (i8, ptr null, i32 4), i32 0
  ret ptr %arrayidx14.i290

do.end213.i:                                      ; preds = %do.body.i, %do.body.i
  %1 = load i8, ptr %arrayidx9.i, align 1
  %arrayidx14.i265 = getelementptr [2 x [3 x i8]], ptr getelementptr inbounds nuw (i8, ptr null, i32 4), i32 0
  ret ptr null
}
; CHECK-LABEL: define ptr @outliner_crash(
; CHECK-SAME: ptr [[ARRAYIDX9_I:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ARRAYIDX14_I290_LOC:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i8 0, 4
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_THEN202_I:.*]], label %[[DO_END213_I:.*]]
; CHECK:       [[IF_THEN202_I]]:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[ARRAYIDX14_I290_LOC]])
; CHECK-NEXT:    call void @outlined_ir_func_0(ptr null, ptr [[ARRAYIDX14_I290_LOC]], i32 0)
; CHECK-NEXT:    [[ARRAYIDX14_I290_RELOAD:%.*]] = load ptr, ptr [[ARRAYIDX14_I290_LOC]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[ARRAYIDX14_I290_LOC]])
; CHECK-NEXT:    ret ptr [[ARRAYIDX14_I290_RELOAD]]
; CHECK:       [[DO_END213_I]]:
; CHECK-NEXT:    call void @outlined_ir_func_0(ptr [[ARRAYIDX9_I]], ptr null, i32 -1)
; CHECK-NEXT:    ret ptr null
;
;
; CHECK-LABEL: define internal void @outlined_ir_func_0(
; CHECK-SAME: ptr [[TMP0:%.*]], ptr [[TMP1:%.*]], i32 [[TMP2:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[NEWFUNCROOT:.*:]]
; CHECK-NEXT:    br label %[[IF_THEN202_I_TO_OUTLINE:.*]]
; CHECK:       [[IF_THEN202_I_TO_OUTLINE]]:
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP0]], align 1
; CHECK-NEXT:    [[ARRAYIDX14_I290:%.*]] = getelementptr [2 x [3 x i8]], ptr getelementptr inbounds nuw (i8, ptr null, i32 4), i32 0
; CHECK-NEXT:    br label %[[IF_THEN202_I_AFTER_OUTLINE_EXITSTUB:.*]]
; CHECK:       [[IF_THEN202_I_AFTER_OUTLINE_EXITSTUB]]:
; CHECK-NEXT:    switch i32 [[TMP2]], label %[[FINAL_BLOCK_0:.*]] [
; CHECK-NEXT:      i32 0, label %[[OUTPUT_BLOCK_0_0:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[OUTPUT_BLOCK_0_0]]:
; CHECK-NEXT:    store ptr [[ARRAYIDX14_I290]], ptr [[TMP1]], align 8
; CHECK-NEXT:    br label %[[FINAL_BLOCK_0]]
; CHECK:       [[FINAL_BLOCK_0]]:
; CHECK-NEXT:    ret void
;
