; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -structurizecfg %s | FileCheck %s

; r321751 introduced a bug where control flow branching from if to exit was
; not handled properly and instead ended up in an infinite loop.
define void @bug36015(i32 %cmp0, i32 %count) {
; CHECK-LABEL: define void @bug36015(
; CHECK-SAME: i32 [[CMP0:%.*]], i32 [[COUNT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP_OUTER:.*]]
; CHECK:       [[LOOP_OUTER]]:
; CHECK-NEXT:    [[CTR_LOOP_OUTER:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[TMP3:%.*]], %[[FLOW2:.*]] ]
; CHECK-NEXT:    call void @foo(i32 0)
; CHECK-NEXT:    br label %[[LOOP_INNER:.*]]
; CHECK:       [[LOOP_INNER]]:
; CHECK-NEXT:    [[CTR_LOOP_INNER:%.*]] = phi i32 [ [[CTR_LOOP_OUTER]], %[[LOOP_OUTER]] ], [ [[TMP0:%.*]], %[[FLOW:.*]] ]
; CHECK-NEXT:    call void @foo(i32 1)
; CHECK-NEXT:    [[COND_INNER:%.*]] = icmp eq i32 [[CMP0]], [[CTR_LOOP_INNER]]
; CHECK-NEXT:    br i1 [[COND_INNER]], label %[[IF:.*]], label %[[FLOW]]
; CHECK:       [[IF]]:
; CHECK-NEXT:    [[CTR_IF:%.*]] = add i32 [[CTR_LOOP_INNER]], 1
; CHECK-NEXT:    call void @foo(i32 2)
; CHECK-NEXT:    [[COND_IF:%.*]] = icmp sge i32 [[CTR_IF]], [[COUNT]]
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[TMP0]] = phi i32 [ [[CTR_IF]], %[[IF]] ], [ undef, %[[LOOP_INNER]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = phi i1 [ [[COND_IF]], %[[IF]] ], [ true, %[[LOOP_INNER]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = phi i1 [ false, %[[IF]] ], [ true, %[[LOOP_INNER]] ]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[FLOW1:.*]], label %[[LOOP_INNER]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    br i1 false, label %[[ELSE:.*]], label %[[FLOW2]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    [[CTR_ELSE:%.*]] = add i32 [[CTR_LOOP_INNER]], 1
; CHECK-NEXT:    call void @foo(i32 3)
; CHECK-NEXT:    [[COND_ELSE:%.*]] = icmp sge i32 [[CTR_ELSE]], [[COUNT]]
; CHECK-NEXT:    br label %[[FLOW2]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    [[TMP3]] = phi i32 [ [[CTR_ELSE]], %[[ELSE]] ], [ [[TMP0]], %[[FLOW1]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = phi i1 [ [[COND_ELSE]], %[[ELSE]] ], [ true, %[[FLOW1]] ]
; CHECK-NEXT:    br i1 [[TMP4]], label %[[EXIT:.*]], label %[[LOOP_OUTER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop.outer

loop.outer:
  %ctr.loop.outer = phi i32 [ 0, %entry ], [ %ctr.else, %else ]
  call void @foo(i32 0)
  br label %loop.inner

loop.inner:
  %ctr.loop.inner = phi i32 [ %ctr.loop.outer, %loop.outer ], [ %ctr.if, %if ]
  call void @foo(i32 1)
  %cond.inner = icmp eq i32 %cmp0, %ctr.loop.inner
  br i1 %cond.inner, label %if, label %else

if:
  %ctr.if = add i32 %ctr.loop.inner, 1
  call void @foo(i32 2)
  %cond.if = icmp slt i32 %ctr.if, %count
  br i1 %cond.if, label %loop.inner, label %exit



else:
  %ctr.else = add i32 %ctr.loop.inner, 1
  call void @foo(i32 3)
  %cond.else = icmp slt i32 %ctr.else, %count
  br i1 %cond.else, label %loop.outer, label %exit


exit:
  ret void
}

declare void @foo(i32)
