; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes='structurizecfg,verify<domtree>' < %s | FileCheck %s

; StructurizeCFG handles callbr by leaving the callbr terminator itself
; untouched and structurizing the surrounding CFG around it. Every callbr edge
; (if it's reachable and not already in a trivial bypass shape, aka an
; unconditional branch as the only instruction) is interposed with a bypass
; block (via SplitCallBrEdge) so the targets are not direct successors of the
; immutable callbr; the bypasses then converge into a Flow block whose
; "island.sel" phis recover, as data, which target the callbr selected, and a
; ladder of 2-way Flow branches re-dispatches to the targets.  Loop back-edges
; among the targets are routed so the normal loop machinery closes the loop. The
; callbr terminator itself is never rewritten.
;
; Tests are grouped by the structural situation they exercise.

; ===== Single callbr, no surrounding control flow =====

; Only callbr, nothing to do.
define void @callbr_simple() {
; CHECK-LABEL: define void @callbr_simple() {
; CHECK-NEXT:  [[CALLBR:.*:]]
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[FALLTHROUGH:.*]] [label %[[INDIRECT:.*]]]
; CHECK:       [[FALLTHROUGH]]:
; CHECK-NEXT:    br label %[[FLOW:.*]]
; CHECK:       [[INDIRECT]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[FALLTHROUGH]] ], [ false, %[[INDIRECT]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[FLOW1:.*]], label %[[EXIT:.*]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
callbr:
  callbr void asm "", "!i"() to label %fallthrough [label %indirect]
fallthrough:
  br label %exit
indirect:
  br label %exit
exit:
  ret void
}

; callbr with no indirect targets at all.
define void @callbr_no_indirect() {
; CHECK-LABEL: define void @callbr_no_indirect() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    callbr void asm "", ""()
; CHECK-NEXT:            to label %[[FT:.*]] []
; CHECK:       [[FT]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  callbr void asm "", ""() to label %ft []
ft:
  br label %exit
exit:
  ret void
}

; callbr with many (4) indirect targets.
define void @callbr_many_indirect(i1 %c) {
; CHECK-LABEL: define void @callbr_many_indirect(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    callbr void asm "", "!i,!i,!i,!i"()
; CHECK-NEXT:            to label %[[FT:.*]] [label %[[I0:.*]], label %[[I1:.*]], label %[[I2:.*]], label %[[I3:.*]]]
; CHECK:       [[FT]]:
; CHECK-NEXT:    br label %[[FLOW:.*]]
; CHECK:       [[I0]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[I1]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[I2]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[I3]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[FT]] ], [ false, %[[I0]] ], [ false, %[[I1]] ], [ false, %[[I2]] ], [ false, %[[I3]] ]
; CHECK-NEXT:    [[ISLAND_SEL1:%.*]] = phi i1 [ false, %[[FT]] ], [ true, %[[I0]] ], [ false, %[[I1]] ], [ false, %[[I2]] ], [ false, %[[I3]] ]
; CHECK-NEXT:    [[ISLAND_SEL2:%.*]] = phi i1 [ false, %[[FT]] ], [ false, %[[I0]] ], [ true, %[[I1]] ], [ false, %[[I2]] ], [ false, %[[I3]] ]
; CHECK-NEXT:    [[ISLAND_SEL3:%.*]] = phi i1 [ false, %[[FT]] ], [ false, %[[I0]] ], [ false, %[[I1]] ], [ true, %[[I2]] ], [ false, %[[I3]] ]
; CHECK-NEXT:    [[ISLAND_SEL3_INV:%.*]] = xor i1 [[ISLAND_SEL3]], true
; CHECK-NEXT:    [[ISLAND_SEL2_INV:%.*]] = xor i1 [[ISLAND_SEL2]], true
; CHECK-NEXT:    [[ISLAND_SEL1_INV:%.*]] = xor i1 [[ISLAND_SEL1]], true
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[FLOW4:.*]], label %[[FLOW8:.*]]
; CHECK:       [[FLOW4]]:
; CHECK-NEXT:    br i1 [[ISLAND_SEL1_INV]], label %[[FLOW5:.*]], label %[[FLOW9:.*]]
; CHECK:       [[FLOW8]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[FLOW5]]:
; CHECK-NEXT:    br i1 [[ISLAND_SEL2_INV]], label %[[FLOW6:.*]], label %[[FLOW10:.*]]
; CHECK:       [[FLOW9]]:
; CHECK-NEXT:    br label %[[FLOW8]]
; CHECK:       [[FLOW6]]:
; CHECK-NEXT:    br i1 [[ISLAND_SEL3_INV]], label %[[FLOW7:.*]], label %[[FLOW11:.*]]
; CHECK:       [[FLOW10]]:
; CHECK-NEXT:    br label %[[FLOW9]]
; CHECK:       [[FLOW7]]:
; CHECK-NEXT:    br label %[[FLOW11]]
; CHECK:       [[FLOW11]]:
; CHECK-NEXT:    br label %[[FLOW10]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  callbr void asm "", "!i,!i,!i,!i"() to label %ft [label %i0, label %i1, label %i2, label %i3]
ft:
  br label %exit
i0:
  br label %exit
i1:
  br label %exit
i2:
  br label %exit
i3:
  br label %exit
exit:
  ret void
}

; two callbr edges that share the same target block.
define void @callbr_shared_target() {
; CHECK-LABEL: define void @callbr_shared_target() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[ENTRY_TARGET_FT1:.*]] [label %[[ENTRY_TARGET_FT1]]]
; CHECK:       [[FLOW2:.*]]:
; CHECK-NEXT:    br label %[[FT:.*]]
; CHECK:       [[FT]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
; CHECK:       [[ENTRY_TARGET_FT1]]:
; CHECK-NEXT:    br label %[[FLOW2]]
;
entry:
  callbr void asm "", "!i"() to label %ft [label %ft]
ft:
  br label %exit
exit:
  ret void
}

; A target reached by two callbr edges that is *in-region* (a third target makes
; the convergence the region exit, not the shared target). The two edges to %x
; are indistinguishable, so %x is dispatched once, not duplicated in the ladder.
define void @callbr_shared_target_in_region() {
; CHECK-LABEL: define void @callbr_shared_target_in_region() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    callbr void asm "", "!i,!i"()
; CHECK-NEXT:            to label %[[X:.*]] [label %[[X]], label %[[Y:.*]]]
; CHECK:       [[X]]:
; CHECK-NEXT:    br label %[[FLOW:.*]]
; CHECK:       [[Y]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[X]] ], [ false, %[[Y]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[FLOW1:.*]], label %[[JOIN:.*]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    ret void
;
entry:
  callbr void asm "", "!i,!i"() to label %x [label %x, label %y]
x:
  br label %join
y:
  br label %join
join:
  ret void
}

; Same shape, but the shared in-region target is non-trivial (a conditional
; branch), so it is split per edge rather than reused.
define void @callbr_shared_target_in_region_nontrivial(i1 %c) {
; CHECK-LABEL: define void @callbr_shared_target_in_region_nontrivial(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    callbr void asm "", "!i,!i"()
; CHECK-NEXT:            to label %[[ENTRY_TARGET_X1:.*]] [label %[[ENTRY_TARGET_X1]], label %[[Y:.*]]]
; CHECK:       [[X:.*]]:
; CHECK-NEXT:    br i1 [[C]], label %[[A:.*]], label %[[FLOW:.*]]
; CHECK:       [[A]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[Y]]:
; CHECK-NEXT:    br label %[[FLOW2:.*]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    br label %[[JOIN:.*]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[ENTRY_TARGET_X1]] ], [ false, %[[Y]] ]
; CHECK-NEXT:    br i1 [[ISLAND_SEL]], label %[[X]], label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    ret void
; CHECK:       [[ENTRY_TARGET_X1]]:
; CHECK-NEXT:    br label %[[FLOW2]]
;
entry:
  callbr void asm "", "!i,!i"() to label %x [label %x, label %y]
x:
  br i1 %c, label %a, label %join
a:
  br label %join
y:
  br label %join
join:
  ret void
}

; A shared non-trivial target that carries a phi over its multiple callbr edges:
; the edges collapse to a single forwarder and the phi to a single incoming.
define i32 @callbr_shared_target_with_phi(i1 %c) {
; CHECK-LABEL: define i32 @callbr_shared_target_with_phi(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    callbr void asm "", "!i,!i"()
; CHECK-NEXT:            to label %[[ENTRY_TARGET_X:.*]] [label %[[ENTRY_TARGET_X]], label %[[Y:.*]]]
; CHECK:       [[X:.*]]:
; CHECK-NEXT:    br i1 [[C]], label %[[A:.*]], label %[[FLOW:.*]]
; CHECK:       [[A]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[Y]]:
; CHECK-NEXT:    br label %[[FLOW1:.*]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    br label %[[JOIN:.*]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[ENTRY_TARGET_X]] ], [ false, %[[Y]] ]
; CHECK-NEXT:    br i1 [[ISLAND_SEL]], label %[[X]], label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[Q:%.*]] = phi i32 [ 0, %[[FLOW1]] ], [ 7, %[[FLOW]] ]
; CHECK-NEXT:    ret i32 [[Q]]
; CHECK:       [[ENTRY_TARGET_X]]:
; CHECK-NEXT:    br label %[[FLOW1]]
;
entry:
  callbr void asm "", "!i,!i"() to label %x [label %x, label %y]
x:
  %p = phi i32 [ 7, %entry ], [ 7, %entry ]
  br i1 %c, label %a, label %join
a:
  br label %join
y:
  br label %join
join:
  %q = phi i32 [ %p, %a ], [ %p, %x ], [ 0, %y ]
  ret i32 %q
}

; A shared target that also has a non-callbr predecessor, so the callbr does not
; dominate it. SplitCallBrEdge then omits the forwarder->target dominator edge;
; collapsing the duplicate edge must still leave a correct dominator tree.
define void @callbr_shared_target_not_dominated(i1 %c, i1 %d) {
; CHECK-LABEL: define void @callbr_shared_target_not_dominated(
; CHECK-SAME: i1 [[C:%.*]], i1 [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br i1 [[C]], label %[[FLOW2:.*]], label %[[FLOW4:.*]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    br label %[[PRE:.*]]
; CHECK:       [[FLOW4]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ [[ISLAND_SEL:%.*]], %[[FLOW3:.*]] ], [ true, %[[ENTRY]] ]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[X:.*]], label %[[JOIN:.*]]
; CHECK:       [[PRE]]:
; CHECK-NEXT:    callbr void asm "", "!i,!i"()
; CHECK-NEXT:            to label %[[PRE_TARGET_X:.*]] [label %[[PRE_TARGET_X]], label %[[Y:.*]]]
; CHECK:       [[X]]:
; CHECK-NEXT:    br i1 [[D]], label %[[A:.*]], label %[[FLOW:.*]]
; CHECK:       [[A]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[Y]]:
; CHECK-NEXT:    br label %[[FLOW3]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[FLOW3]]:
; CHECK-NEXT:    [[ISLAND_SEL]] = phi i1 [ true, %[[PRE_TARGET_X]] ], [ false, %[[Y]] ]
; CHECK-NEXT:    br label %[[FLOW4]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    ret void
; CHECK:       [[PRE_TARGET_X]]:
; CHECK-NEXT:    br label %[[FLOW3]]
;
entry:
  br i1 %c, label %pre, label %x
pre:
  callbr void asm "", "!i,!i"() to label %x [label %x, label %y]
x:
  br i1 %d, label %a, label %join
a:
  br label %join
y:
  br label %join
join:
  ret void
}

; Three callbr edges to the same block: the collapse defers the edge/phi cleanup
; until the last duplicate is redirected onto the single forwarder.
define void @callbr_shared_target_thrice(i1 %d) {
; CHECK-LABEL: define void @callbr_shared_target_thrice(
; CHECK-SAME: i1 [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    callbr void asm "", "!i,!i"()
; CHECK-NEXT:            to label %[[ENTRY_TARGET_X:.*]] [label %[[ENTRY_TARGET_X]], label %[[ENTRY_TARGET_X]]]
; CHECK:       [[FLOW:.*]]:
; CHECK-NEXT:    br label %[[X:.*]]
; CHECK:       [[X]]:
; CHECK-NEXT:    br i1 [[D]], label %[[A:.*]], label %[[JOIN:.*]]
; CHECK:       [[A]]:
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    ret void
; CHECK:       [[ENTRY_TARGET_X]]:
; CHECK-NEXT:    br label %[[FLOW]]
;
entry:
  callbr void asm "", "!i,!i"() to label %x [label %x, label %x]
x:
  br i1 %d, label %a, label %join
a:
  br label %join
join:
  ret void
}

; One indirect target is already trivial (single unconditional branch);
; handleIsland leaves it as a direct callbr destination and only splits the
; non-trivial targets.
define void @callbr_multi_indirect_one_trivial(i1 %c, i1 %d) {
; CHECK-LABEL: define void @callbr_multi_indirect_one_trivial(
; CHECK-SAME: i1 [[C:%.*]], i1 [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    callbr void asm "", "!i,!i"()
; CHECK-NEXT:            to label %[[ENTRY_TARGET_FALLTHROUGH:.*]] [label %[[ENTRY_TARGET_INDIRECT0:.*]], label %[[INDIRECT1:.*]]]
; CHECK:       [[EXIT:.*]]:
; CHECK-NEXT:    br label %[[FLOW6:.*]]
; CHECK:       [[INDIRECT0:.*]]:
; CHECK-NEXT:    br i1 [[C]], label %[[A:.*]], label %[[FLOW1:.*]]
; CHECK:       [[A]]:
; CHECK-NEXT:    br label %[[FLOW1]]
; CHECK:       [[FLOW6]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ false, %[[EXIT]] ], [ true, %[[FLOW2:.*]] ]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[INDIRECT0]], label %[[FLOW8:.*]]
; CHECK:       [[FALLTHROUGH:.*]]:
; CHECK-NEXT:    br i1 [[D]], label %[[B:.*]], label %[[FLOW:.*]]
; CHECK:       [[B]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[INDIRECT1]]:
; CHECK-NEXT:    br label %[[FLOW2]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    br label %[[FLOW8]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[ENTRY_TARGET_FALLTHROUGH]] ], [ false, %[[ENTRY_TARGET_INDIRECT0]] ], [ false, %[[INDIRECT1]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = phi i1 [ false, %[[ENTRY_TARGET_FALLTHROUGH]] ], [ true, %[[ENTRY_TARGET_INDIRECT0]] ], [ false, %[[INDIRECT1]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[FLOW4:.*]], label %[[FLOW6]]
; CHECK:       [[FLOW4]]:
; CHECK-NEXT:    br i1 [[TMP1]], label %[[FALLTHROUGH]], label %[[EXIT]]
; CHECK:       [[FLOW8]]:
; CHECK-NEXT:    ret void
; CHECK:       [[ENTRY_TARGET_FALLTHROUGH]]:
; CHECK-NEXT:    br label %[[FLOW2]]
; CHECK:       [[ENTRY_TARGET_INDIRECT0]]:
; CHECK-NEXT:    br label %[[FLOW2]]
;
entry:
  callbr void asm "", "!i,!i"() to label %fallthrough [label %indirect0, label %indirect1]
fallthrough:
  br i1 %c, label %a, label %exit
a:
  br label %exit
indirect0:
  br i1 %d, label %b, label %exit
b:
  br label %exit
indirect1:
  br label %exit
exit:
  ret void
}

; ===== Intrinsic callees =====

; Intrinsic callee (llvm.amdgcn.kill) with an unreachable indirect target.
define void @callbr_kill_intrinsic(i1 %c) {
; CHECK-LABEL: define void @callbr_kill_intrinsic(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    callbr void @llvm.amdgcn.kill(i1 [[C]])
; CHECK-NEXT:            to label %[[CONT:.*]] [label %[[DEAD:.*]]]
; CHECK:       [[DEAD]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[CONT]]:
; CHECK-NEXT:    ret void
;
entry:
  callbr void @llvm.amdgcn.kill(i1 %c) to label %cont [label %dead]
dead:
  unreachable
cont:
  ret void
}

; Intrinsic callee whose dead target calls llvm.amdgcn.unreachable.
define void @callbr_kill_with_amdgcn_unreachable(i1 %c) {
; CHECK-LABEL: define void @callbr_kill_with_amdgcn_unreachable(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    callbr void @llvm.amdgcn.kill(i1 [[C]])
; CHECK-NEXT:            to label %[[CONT:.*]] [label %[[DEAD:.*]]]
; CHECK:       [[DEAD]]:
; CHECK-NEXT:    call void @llvm.amdgcn.unreachable()
; CHECK-NEXT:    unreachable
; CHECK:       [[CONT]]:
; CHECK-NEXT:    ret void
;
entry:
  callbr void @llvm.amdgcn.kill(i1 %c) to label %cont [label %dead]
dead:
  call void @llvm.amdgcn.unreachable()
  unreachable
cont:
  ret void
}

; An amdgcn.unreachable dead-lane target that branches on to the exit (the shape
; produced after exit unification). The callbr edge to it stays direct and the
; dead lane is kept out of the dispatch, but it still reconverges at the exit.
define void @callbr_kill_unreachable_with_successor(i1 %c) {
; CHECK-LABEL: define void @callbr_kill_unreachable_with_successor(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    callbr void @llvm.amdgcn.kill(i1 [[C]])
; CHECK-NEXT:            to label %[[CONT:.*]] [label %[[DEAD:.*]]]
; CHECK:       [[DEAD]]:
; CHECK-NEXT:    call void @llvm.amdgcn.unreachable()
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[CONT]]:
; CHECK-NEXT:    br label %[[FLOW:.*]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  callbr void @llvm.amdgcn.kill(i1 %c) to label %cont [label %dead]
dead:
  call void @llvm.amdgcn.unreachable()
  br label %exit
cont:
  br label %exit
exit:
  ret void
}

; Two unreachable targets: both stay direct dead lanes (out of the ladder) and
; reconverge at the exit, giving it three predecessors.
define void @callbr_two_unreachable_targets() {
; CHECK-LABEL: define void @callbr_two_unreachable_targets() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    callbr void asm "", "!i,!i"()
; CHECK-NEXT:            to label %[[LIVE:.*]] [label %[[DEAD1:.*]], label %[[DEAD2:.*]]]
; CHECK:       [[LIVE]]:
; CHECK-NEXT:    br label %[[FLOW:.*]]
; CHECK:       [[DEAD1]]:
; CHECK-NEXT:    call void @llvm.amdgcn.unreachable()
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[DEAD2]]:
; CHECK-NEXT:    call void @llvm.amdgcn.unreachable()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  callbr void asm "", "!i,!i"() to label %live [label %dead1, label %dead2]
live:
  br label %exit
dead1:
  call void @llvm.amdgcn.unreachable()
  br label %exit
dead2:
  call void @llvm.amdgcn.unreachable()
  br label %exit
exit:
  ret void
}

; Every target is unreachable: there is nothing to dispatch, so no ladder is
; built and the callbr is left untouched with both dead lanes direct.
define void @callbr_all_targets_unreachable() {
; CHECK-LABEL: define void @callbr_all_targets_unreachable() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[DEAD0:.*]] [label %[[DEAD1:.*]]]
; CHECK:       [[DEAD0]]:
; CHECK-NEXT:    call void @llvm.amdgcn.unreachable()
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[DEAD1]]:
; CHECK-NEXT:    call void @llvm.amdgcn.unreachable()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  callbr void asm "", "!i"() to label %dead0 [label %dead1]
dead0:
  call void @llvm.amdgcn.unreachable()
  br label %exit
dead1:
  call void @llvm.amdgcn.unreachable()
  br label %exit
exit:
  ret void
}

; ===== callbr nested in / surrounded by non-callbr control flow =====

; Callbr nested in non-callbr: non-callbr is transformed
define void @callbr_in_non_callbr(i1 %c) {
; CHECK-LABEL: define void @callbr_in_non_callbr(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:    [[C_INV:%.*]] = xor i1 [[C]], true
; CHECK-NEXT:    br i1 [[C_INV]], label %[[NOCALLBR:.*]], label %[[FLOW2:.*]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    [[TMP1:%.*]] = phi i1 [ false, %[[NOCALLBR]] ], [ true, [[TMP0:%.*]] ]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[CALLBR:.*]], label %[[EXIT:.*]]
; CHECK:       [[CALLBR]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[FALLTHROUGH:.*]] [label %[[INDIRECT:.*]]]
; CHECK:       [[FALLTHROUGH]]:
; CHECK-NEXT:    br label %[[FLOW:.*]]
; CHECK:       [[INDIRECT]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[NOCALLBR]]:
; CHECK-NEXT:    br label %[[FLOW2]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[FALLTHROUGH]] ], [ false, %[[INDIRECT]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[FLOW1:.*]], label %[[FLOW3:.*]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    br label %[[FLOW3]]
; CHECK:       [[FLOW3]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
  br i1 %c, label %callbr, label %nocallbr
callbr:
  callbr void asm "", "!i"() to label %fallthrough [label %indirect]
fallthrough:
  br label %exit
indirect:
  br label %exit
nocallbr:
  br label %exit
exit:
  ret void
}

; Callbr parent of non-callbr: non-callbr is transformed
define void @non_callbr_in_callbr(i1 %c) {
; CHECK-LABEL: define void @non_callbr_in_callbr(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:    [[C_INV:%.*]] = xor i1 [[C]], true
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[DOTTARGET_FALLTHROUGH:.*]] [label %[[INDIRECT:.*]]]
; CHECK:       [[FALLTHROUGH:.*]]:
; CHECK-NEXT:    br i1 [[C_INV]], label %[[FALLTHROUGH2:.*]], label %[[FLOW:.*]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi i1 [ false, %[[FALLTHROUGH2]] ], [ true, %[[FALLTHROUGH]] ]
; CHECK-NEXT:    br i1 [[TMP2]], label %[[FALLTHROUGH1:.*]], label %[[FLOW1:.*]]
; CHECK:       [[FALLTHROUGH1]]:
; CHECK-NEXT:    br label %[[FLOW1]]
; CHECK:       [[FALLTHROUGH2]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[INDIRECT]]:
; CHECK-NEXT:    br label %[[FLOW2:.*]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[DOTTARGET_FALLTHROUGH]] ], [ false, %[[INDIRECT]] ]
; CHECK-NEXT:    br i1 [[ISLAND_SEL]], label %[[FALLTHROUGH]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
; CHECK:       [[_TARGET_FALLTHROUGH:.*:]]
; CHECK-NEXT:    br label %[[FLOW2]]
;
  callbr void asm "", "!i"() to label %fallthrough [label %indirect]
fallthrough:
  br i1 %c, label %fallthrough1, label %fallthrough2
fallthrough1:
  br label %exit
fallthrough2:
  br label %exit
indirect:
  br label %exit
exit:
  ret void
}

; Callbr surrounded by non-callbr: all three regular branches are handled
; correctly
define void @callbr_nested_in_non_callbr(i1 %c, i1 %d, i1 %e, i1 %f) {
; CHECK-LABEL: define void @callbr_nested_in_non_callbr(
; CHECK-SAME: i1 [[C:%.*]], i1 [[D:%.*]], i1 [[E:%.*]], i1 [[F:%.*]]) {
; CHECK-NEXT:    [[C_INV:%.*]] = xor i1 [[C]], true
; CHECK-NEXT:    br i1 [[C_INV]], label %[[NOCALLBR:.*]], label %[[FLOW7:.*]]
; CHECK:       [[FLOW7]]:
; CHECK-NEXT:    [[TMP1:%.*]] = phi i1 [ false, %[[FLOW:.*]] ], [ true, [[TMP0:%.*]] ]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[CALLBR:.*]], label %[[RET:.*]]
; CHECK:       [[CALLBR]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[CALLBR_TARGET_FALLTHROUGH:.*]] [label %[[CALLBR_TARGET_INDIRECT:.*]]]
; CHECK:       [[FLOW5:.*]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi i1 [ false, %[[FLOW1:.*]] ], [ true, %[[FLOW3:.*]] ]
; CHECK-NEXT:    br i1 [[TMP2]], label %[[FALLTHROUGH:.*]], label %[[FLOW6:.*]]
; CHECK:       [[FALLTHROUGH]]:
; CHECK-NEXT:    br i1 [[D]], label %[[FALLTHROUGH1:.*]], label %[[FLOW2:.*]]
; CHECK:       [[FALLTHROUGH1]]:
; CHECK-NEXT:    br label %[[FLOW2]]
; CHECK:       [[FLOW4:.*]]:
; CHECK-NEXT:    br i1 [[E]], label %[[INDIRECT1:.*]], label %[[FLOW1]]
; CHECK:       [[INDIRECT1]]:
; CHECK-NEXT:    br label %[[FLOW1]]
; CHECK:       [[NOCALLBR]]:
; CHECK-NEXT:    br i1 [[F]], label %[[NOCALLBR1:.*]], label %[[FLOW]]
; CHECK:       [[NOCALLBR1]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    br label %[[FLOW7]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    br label %[[FLOW5]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    br label %[[FLOW6]]
; CHECK:       [[FLOW3]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[CALLBR_TARGET_FALLTHROUGH]] ], [ false, %[[CALLBR_TARGET_INDIRECT]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[FLOW4]], label %[[FLOW5]]
; CHECK:       [[FLOW6]]:
; CHECK-NEXT:    br label %[[RET]]
; CHECK:       [[RET]]:
; CHECK-NEXT:    ret void
; CHECK:       [[CALLBR_TARGET_FALLTHROUGH]]:
; CHECK-NEXT:    br label %[[FLOW3]]
; CHECK:       [[CALLBR_TARGET_INDIRECT]]:
; CHECK-NEXT:    br label %[[FLOW3]]
;
  br i1 %c, label %callbr, label %nocallbr
callbr:
  callbr void asm "", "!i"() to label %fallthrough [label %indirect]
fallthrough:
  br i1 %d, label %fallthrough1, label %ret
fallthrough1:
  br label %ret
indirect:
  br i1 %e, label %indirect1, label %ret
indirect1:
  br label %ret
nocallbr:
  br i1 %f, label %nocallbr1, label %ret
nocallbr1:
  br label %ret
ret:
  ret void
}

; non-trivial regions both before and after the island.
define void @callbr_regions_around(i1 %c, i1 %d, i1 %e) {
; CHECK-LABEL: define void @callbr_regions_around(
; CHECK-SAME: i1 [[C:%.*]], i1 [[D:%.*]], i1 [[E:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[C_INV:%.*]] = xor i1 [[C]], true
; CHECK-NEXT:    [[E_INV:%.*]] = xor i1 [[E]], true
; CHECK-NEXT:    br i1 [[C_INV]], label %[[PRE2:.*]], label %[[FLOW3:.*]]
; CHECK:       [[FLOW3]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ false, %[[PRE2]] ], [ true, %[[ENTRY]] ]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[PRE1:.*]], label %[[PRECONT:.*]]
; CHECK:       [[PRE1]]:
; CHECK-NEXT:    br label %[[PRECONT]]
; CHECK:       [[PRE2]]:
; CHECK-NEXT:    br label %[[FLOW3]]
; CHECK:       [[PRECONT]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[FT:.*]] [label %[[IND:.*]]]
; CHECK:       [[FT]]:
; CHECK-NEXT:    br label %[[FLOW1:.*]]
; CHECK:       [[IND]]:
; CHECK-NEXT:    br label %[[FLOW1]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[FT]] ], [ false, %[[IND]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[FLOW2:.*]], label %[[POST:.*]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    br label %[[POST]]
; CHECK:       [[POST]]:
; CHECK-NEXT:    br i1 [[E_INV]], label %[[POST2:.*]], label %[[FLOW:.*]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[TMP1:%.*]] = phi i1 [ false, %[[POST2]] ], [ true, %[[POST]] ]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[POST1:.*]], label %[[POSTCONT:.*]]
; CHECK:       [[POST1]]:
; CHECK-NEXT:    br label %[[POSTCONT]]
; CHECK:       [[POST2]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[POSTCONT]]:
; CHECK-NEXT:    ret void
;
entry:
  br i1 %c, label %pre1, label %pre2
pre1:
  br label %precont
pre2:
  br label %precont
precont:
  callbr void asm "", "!i"() to label %ft [label %ind]
ft:
  br label %post
ind:
  br label %post
post:
  br i1 %e, label %post1, label %post2
post1:
  br label %postcont
post2:
  br label %postcont
postcont:
  ret void
}

; callbr reached from the reconvergence of a non-trivial if-diamond subregion.
define void @callbr_pred_from_subregion(i1 %c, i1 %d) {
; CHECK-LABEL: define void @callbr_pred_from_subregion(
; CHECK-SAME: i1 [[C:%.*]], i1 [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[C_INV:%.*]] = xor i1 [[C]], true
; CHECK-NEXT:    br i1 [[C_INV]], label %[[B:.*]], label %[[FLOW3:.*]]
; CHECK:       [[FLOW3]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ false, %[[B]] ], [ true, %[[ENTRY]] ]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[A:.*]], label %[[MERGE:.*]]
; CHECK:       [[A]]:
; CHECK-NEXT:    br i1 [[D]], label %[[A1:.*]], label %[[FLOW2:.*]]
; CHECK:       [[A1]]:
; CHECK-NEXT:    br label %[[FLOW2]]
; CHECK:       [[B]]:
; CHECK-NEXT:    br label %[[FLOW3]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[CONT:.*]] [label %[[IND:.*]]]
; CHECK:       [[CONT]]:
; CHECK-NEXT:    br label %[[FLOW:.*]]
; CHECK:       [[IND]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[CONT]] ], [ false, %[[IND]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[FLOW1:.*]], label %[[EXIT:.*]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br i1 %c, label %A, label %B
A:
  br i1 %d, label %A1, label %merge
A1:
  br label %merge
B:
  br label %merge
merge:
  callbr void asm "", "!i"() to label %cont [label %ind]
cont:
  br label %exit
ind:
  br label %exit
exit:
  ret void
}

; ===== Structurizing the callbr targets' own subgraphs =====

; a callbr fallthrough target contains its own if-diamond.
define void @callbr_target_has_nested_region(i1 %c, i1 %d) {
; CHECK-LABEL: define void @callbr_target_has_nested_region(
; CHECK-SAME: i1 [[C:%.*]], i1 [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C_INV:%.*]] = xor i1 [[C]], true
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[ENTRY_TARGET_FT:.*]] [label %[[IND:.*]]]
; CHECK:       [[FT:.*]]:
; CHECK-NEXT:    br i1 [[C_INV]], label %[[T2:.*]], label %[[FLOW1:.*]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    [[TMP1:%.*]] = phi i1 [ false, %[[T2]] ], [ true, %[[FT]] ]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[T1:.*]], label %[[JOIN:.*]]
; CHECK:       [[T1]]:
; CHECK-NEXT:    br i1 [[D]], label %[[T1A:.*]], label %[[FLOW:.*]]
; CHECK:       [[T1A]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[T2]]:
; CHECK-NEXT:    br label %[[FLOW1]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[FLOW5:.*]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    br label %[[FLOW5]]
; CHECK:       [[IND]]:
; CHECK-NEXT:    br label %[[FLOW2:.*]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[ENTRY_TARGET_FT]] ], [ false, %[[IND]] ]
; CHECK-NEXT:    br i1 [[ISLAND_SEL]], label %[[FT]], label %[[FLOW5]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
; CHECK:       [[ENTRY_TARGET_FT]]:
; CHECK-NEXT:    br label %[[FLOW2]]
;
entry:
  callbr void asm "", "!i"() to label %ft [label %ind]
ft:
  br i1 %c, label %t1, label %t2
t1:
  br i1 %d, label %t1a, label %join
t1a:
  br label %join
t2:
  br label %join
join:
  br label %exit
ind:
  br label %exit
exit:
  ret void
}

; a callbr fallthrough target contains a loop.
define void @callbr_target_has_loop(i1 %c) {
; CHECK-LABEL: define void @callbr_target_has_loop(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C_INV:%.*]] = xor i1 [[C]], true
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[FT:.*]] [label %[[IND:.*]]]
; CHECK:       [[FT]]:
; CHECK-NEXT:    br label %[[FLOW:.*]]
; CHECK:       [[LOOP:.*]]:
; CHECK-NEXT:    br i1 [[C_INV]], label %[[FTEXIT:.*]], label %[[LOOP]]
; CHECK:       [[FLOW3:.*]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[FTEXIT]]:
; CHECK-NEXT:    br label %[[FLOW3]]
; CHECK:       [[IND]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[FT]] ], [ false, %[[IND]] ]
; CHECK-NEXT:    br i1 [[ISLAND_SEL]], label %[[LOOP]], label %[[FLOW3]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  callbr void asm "", "!i"() to label %ft [label %ind]
ft:
  br label %loop
loop:
  br i1 %c, label %loop, label %ftexit
ftexit:
  br label %exit
ind:
  br label %exit
exit:
  ret void
}

; one callbr target branches (conditionally) to another callbr target.
define void @callbr_target_branches_to_target(i1 %d) {
; CHECK-LABEL: define void @callbr_target_branches_to_target(
; CHECK-SAME: i1 [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[D_INV:%.*]] = xor i1 [[D]], true
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[ENTRY_TARGET_T0:.*]] [label %[[ENTRY_TARGET_T1:.*]]]
; CHECK:       [[T0:.*]]:
; CHECK-NEXT:    br label %[[FLOW3:.*]]
; CHECK:       [[FLOW4:.*]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi i1 [ false, %[[T1:.*]] ], [ [[TMP1:%.*]], %[[FLOW3]] ]
; CHECK-NEXT:    br i1 [[TMP2]], label %[[T0A:.*]], label %[[EXIT:.*]]
; CHECK:       [[T0A]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[FLOW3]]:
; CHECK-NEXT:    [[TMP1]] = phi i1 [ true, %[[T0]] ], [ false, %[[FLOW:.*]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = phi i1 [ [[D_INV]], %[[T0]] ], [ true, %[[FLOW]] ]
; CHECK-NEXT:    br i1 [[TMP4]], label %[[T1]], label %[[FLOW4]]
; CHECK:       [[T1]]:
; CHECK-NEXT:    br label %[[FLOW4]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[ENTRY_TARGET_T0]] ], [ false, %[[ENTRY_TARGET_T1]] ]
; CHECK-NEXT:    br i1 [[ISLAND_SEL]], label %[[T0]], label %[[FLOW3]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
; CHECK:       [[ENTRY_TARGET_T0]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[ENTRY_TARGET_T1]]:
; CHECK-NEXT:    br label %[[FLOW]]
;
entry:
  callbr void asm "", "!i"() to label %t0 [label %t1]
t0:
  br i1 %d, label %t0a, label %t1
t0a:
  br label %exit
t1:
  br label %exit
exit:
  ret void
}

; a chain: each callbr target falls into the next one.
define void @callbr_targets_chain(i1 %c, i1 %d) {
; CHECK-LABEL: define void @callbr_targets_chain(
; CHECK-SAME: i1 [[C:%.*]], i1 [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[D_INV:%.*]] = xor i1 [[D]], true
; CHECK-NEXT:    [[C_INV:%.*]] = xor i1 [[C]], true
; CHECK-NEXT:    callbr void asm "", "!i,!i"()
; CHECK-NEXT:            to label %[[ENTRY_TARGET_T0:.*]] [label %[[ENTRY_TARGET_T1:.*]], label %[[ENTRY_TARGET_T2:.*]]]
; CHECK:       [[FLOW5:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ true, %[[FLOW3:.*]] ], [ false, %[[FLOW:.*]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = phi i1 [ [[ISLAND_SEL1:%.*]], %[[FLOW3]] ], [ false, %[[FLOW]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = phi i1 [ false, %[[FLOW3]] ], [ true, %[[FLOW]] ]
; CHECK-NEXT:    br i1 [[TMP2]], label %[[T0:.*]], label %[[FLOW6:.*]]
; CHECK:       [[T0]]:
; CHECK-NEXT:    br label %[[FLOW6]]
; CHECK:       [[FLOW9:.*]]:
; CHECK-NEXT:    br i1 [[TMP5:%.*]], label %[[T0A:.*]], label %[[EXIT:.*]]
; CHECK:       [[T0A]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[FLOW6]]:
; CHECK-NEXT:    [[TMP6:%.*]] = phi i1 [ true, %[[T0]] ], [ false, %[[FLOW5]] ]
; CHECK-NEXT:    [[TMP3:%.*]] = phi i1 [ [[C_INV]], %[[T0]] ], [ [[TMP1]], %[[FLOW5]] ]
; CHECK-NEXT:    br i1 [[TMP3]], label %[[T1:.*]], label %[[FLOW7:.*]]
; CHECK:       [[T1]]:
; CHECK-NEXT:    br label %[[FLOW7]]
; CHECK:       [[FLOW8:.*]]:
; CHECK-NEXT:    [[TMP4:%.*]] = phi i1 [ false, %[[T2:.*]] ], [ [[TMP8:%.*]], %[[FLOW7]] ]
; CHECK-NEXT:    br i1 [[TMP4]], label %[[T1A:.*]], label %[[FLOW9]]
; CHECK:       [[T1A]]:
; CHECK-NEXT:    br label %[[FLOW9]]
; CHECK:       [[FLOW7]]:
; CHECK-NEXT:    [[TMP5]] = phi i1 [ false, %[[T1]] ], [ [[TMP6]], %[[FLOW6]] ]
; CHECK-NEXT:    [[TMP8]] = phi i1 [ true, %[[T1]] ], [ false, %[[FLOW6]] ]
; CHECK-NEXT:    [[TMP7:%.*]] = phi i1 [ [[D_INV]], %[[T1]] ], [ [[TMP0]], %[[FLOW6]] ]
; CHECK-NEXT:    br i1 [[TMP7]], label %[[T2]], label %[[FLOW8]]
; CHECK:       [[T2]]:
; CHECK-NEXT:    br label %[[FLOW8]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[ENTRY_TARGET_T0]] ], [ false, %[[ENTRY_TARGET_T1]] ], [ false, %[[ENTRY_TARGET_T2]] ]
; CHECK-NEXT:    [[ISLAND_SEL1]] = phi i1 [ false, %[[ENTRY_TARGET_T0]] ], [ true, %[[ENTRY_TARGET_T1]] ], [ false, %[[ENTRY_TARGET_T2]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[FLOW3]], label %[[FLOW5]]
; CHECK:       [[FLOW3]]:
; CHECK-NEXT:    br label %[[FLOW5]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
; CHECK:       [[ENTRY_TARGET_T0]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[ENTRY_TARGET_T1]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[ENTRY_TARGET_T2]]:
; CHECK-NEXT:    br label %[[FLOW]]
;
entry:
  callbr void asm "", "!i,!i"() to label %t0 [label %t1, label %t2]
t0:
  br i1 %c, label %t0a, label %t1
t0a:
  br label %exit
t1:
  br i1 %d, label %t1a, label %t2
t1a:
  br label %exit
t2:
  br label %exit
exit:
  ret void
}

; ===== callbr as the region exit (reconvergence point) =====

; callbr as the reconvergence (exit) of an if-diamond region
define void @callbr_as_region_exit(i1 %c) {
; CHECK-LABEL: define void @callbr_as_region_exit(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[C_INV:%.*]] = xor i1 [[C]], true
; CHECK-NEXT:    br i1 [[C_INV]], label %[[B:.*]], label %[[FLOW2:.*]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ false, %[[B]] ], [ true, %[[ENTRY]] ]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[A:.*]], label %[[MERGE:.*]]
; CHECK:       [[A]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[B]]:
; CHECK-NEXT:    br label %[[FLOW2]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[CONT:.*]] [label %[[IND:.*]]]
; CHECK:       [[CONT]]:
; CHECK-NEXT:    br label %[[FLOW:.*]]
; CHECK:       [[IND]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[CONT]] ], [ false, %[[IND]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[FLOW1:.*]], label %[[EXIT:.*]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br i1 %c, label %A, label %B
A:
  br label %merge
B:
  br label %merge
merge:
  callbr void asm "", "!i"() to label %cont [label %ind]
cont:
  br label %exit
ind:
  br label %exit
exit:
  ret void
}

; callbr exit that is also itself nested before another join
define void @callbr_exit_then_more(i1 %c, i1 %d) {
; CHECK-LABEL: define void @callbr_exit_then_more(
; CHECK-SAME: i1 [[C:%.*]], i1 [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[C_INV:%.*]] = xor i1 [[C]], true
; CHECK-NEXT:    br i1 [[C_INV]], label %[[B:.*]], label %[[FLOW4:.*]]
; CHECK:       [[FLOW4]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ false, %[[B]] ], [ true, %[[ENTRY]] ]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[A:.*]], label %[[MERGE:.*]]
; CHECK:       [[A]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[B]]:
; CHECK-NEXT:    br label %[[FLOW4]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[MERGE_TARGET_CONT:.*]] [label %[[IND:.*]]]
; CHECK:       [[CONT:.*]]:
; CHECK-NEXT:    br i1 [[D]], label %[[T:.*]], label %[[FLOW:.*]]
; CHECK:       [[T]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[IND]]:
; CHECK-NEXT:    br label %[[FLOW1:.*]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[MERGE_TARGET_CONT]] ], [ false, %[[IND]] ]
; CHECK-NEXT:    br i1 [[ISLAND_SEL]], label %[[CONT]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
; CHECK:       [[MERGE_TARGET_CONT]]:
; CHECK-NEXT:    br label %[[FLOW1]]
;
entry:
  br i1 %c, label %A, label %B
A:
  br label %merge
B:
  br label %merge
merge:
  callbr void asm "", "!i"() to label %cont [label %ind]
cont:
  br i1 %d, label %t, label %exit
t:
  br label %exit
ind:
  br label %exit
exit:
  ret void
}

; ===== Multiple / nested callbrs =====

; A callbr destination is itself another callbr block (two callbr
; terminators in one function): two nested islands.
define void @callbr_target_is_callbr() {
; CHECK-LABEL: define void @callbr_target_is_callbr() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[ENTRY_TARGET_CB1:.*]] [label %[[IND0:.*]]]
; CHECK:       [[CB1:.*]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[FT1:.*]] [label %[[IND1:.*]]]
; CHECK:       [[FT1]]:
; CHECK-NEXT:    br label %[[FLOW:.*]]
; CHECK:       [[IND1]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[IND0]]:
; CHECK-NEXT:    br label %[[FLOW2:.*]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[FT1]] ], [ false, %[[IND1]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[FLOW1:.*]], label %[[FLOW3:.*]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    br label %[[FLOW3]]
; CHECK:       [[FLOW3]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    [[ISLAND_SEL4:%.*]] = phi i1 [ true, %[[ENTRY_TARGET_CB1]] ], [ false, %[[IND0]] ]
; CHECK-NEXT:    br i1 [[ISLAND_SEL4]], label %[[CB1]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
; CHECK:       [[ENTRY_TARGET_CB1]]:
; CHECK-NEXT:    br label %[[FLOW2]]
;
entry:
  callbr void asm "", "!i"() to label %cb1 [label %ind0]
cb1:
  callbr void asm "", "!i"() to label %ft1 [label %ind1]
ft1:
  br label %exit
ind1:
  br label %exit
ind0:
  br label %exit
exit:
  ret void
}

; ===== Data flow across the island (return value / phis) =====

; A PHI in the join consumes the callbr return value across the bypass.
define i32 @callbr_phi_uses_return_value(i1 %c) {
; CHECK-LABEL: define i32 @callbr_phi_uses_return_value(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V:%.*]] = callbr i32 asm "", "=r,!i"()
; CHECK-NEXT:            to label %[[FT:.*]] [label %[[IND:.*]]]
; CHECK:       [[FT]]:
; CHECK-NEXT:    br label %[[FLOW:.*]]
; CHECK:       [[IND]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[FT]] ], [ false, %[[IND]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[FLOW1:.*]], label %[[JOIN:.*]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[P:%.*]] = phi i32 [ [[V]], %[[FLOW]] ], [ 0, %[[FLOW1]] ]
; CHECK-NEXT:    ret i32 [[P]]
;
entry:
  %v = callbr i32 asm "", "=r,!i"() to label %ft [label %ind]
ft:
  br label %join
ind:
  br label %join
join:
  %p = phi i32 [ %v, %ft ], [ 0, %ind ]
  ret i32 %p
}

; callbr return value used directly in the fallthrough block (not via a phi).
define i32 @callbr_return_value_in_fallthrough() {
; CHECK-LABEL: define i32 @callbr_return_value_in_fallthrough() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V:%.*]] = callbr i32 asm "", "=r,!i"()
; CHECK-NEXT:            to label %[[ENTRY_TARGET_FT:.*]] [label %[[IND:.*]]]
; CHECK:       [[FT:.*]]:
; CHECK-NEXT:    [[W:%.*]] = add i32 [[V]], 1
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[IND]]:
; CHECK-NEXT:    br label %[[FLOW:.*]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[ENTRY_TARGET_FT]] ], [ false, %[[IND]] ]
; CHECK-NEXT:    br i1 [[ISLAND_SEL]], label %[[FT]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[R:%.*]] = phi i32 [ 0, %[[FLOW]] ], [ [[W]], %[[FT]] ]
; CHECK-NEXT:    ret i32 [[R]]
; CHECK:       [[ENTRY_TARGET_FT]]:
; CHECK-NEXT:    br label %[[FLOW]]
;
entry:
  %v = callbr i32 asm "", "=r,!i"() to label %ft [label %ind]
ft:
  %w = add i32 %v, 1
  br label %exit
ind:
  br label %exit
exit:
  %r = phi i32 [ %w, %ft ], [ 0, %ind ]
  ret i32 %r
}

; ===== Loops =====

; The callbr fallthrough edge loops back to the callbr block.
define void @callbr_self_loop_fallthrough(i1 %c) {
; CHECK-LABEL: define void @callbr_self_loop_fallthrough(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[CB:.*]]
; CHECK:       [[CB]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[CB_TARGET_CB:.*]] [label %[[IND:.*]]]
; CHECK:       [[FLOW2:.*]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[CB_TARGET_CB]] ], [ false, %[[IND]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[FLOW3:.*]], label %[[CB]]
; CHECK:       [[FLOW3]]:
; CHECK-NEXT:    br label %[[EXIT1:.*]]
; CHECK:       [[EXIT1]]:
; CHECK-NEXT:    ret void
; CHECK:       [[CB_TARGET_CB]]:
; CHECK-NEXT:    br label %[[FLOW2]]
; CHECK:       [[IND]]:
; CHECK-NEXT:    br label %[[FLOW2]]
;
entry:
  br label %cb
cb:
  callbr void asm "", "!i"() to label %cb [label %ind]
ind:
  br label %exit
exit:
  ret void
}

; The callbr indirect edge loops back to the callbr block.
define void @callbr_self_loop_indirect(i1 %c) {
; CHECK-LABEL: define void @callbr_self_loop_indirect(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[CB:.*]]
; CHECK:       [[CB]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[FT:.*]] [label %[[CB_TARGET_CB:.*]]]
; CHECK:       [[EXIT:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ true, %[[FT]] ], [ false, %[[CB_TARGET_CB]] ]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[FT1:.*]], label %[[CB]]
; CHECK:       [[FT1]]:
; CHECK-NEXT:    br label %[[EXIT1:.*]]
; CHECK:       [[EXIT1]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[CB_TARGET_CB]]:
; CHECK-NEXT:    br label %[[EXIT]]
;
entry:
  br label %cb
cb:
  callbr void asm "", "!i"() to label %ft [label %cb]
ft:
  br label %exit
exit:
  ret void
}

; The callbr fallthrough self-loops and the indirect edge goes straight to the
; region's return block (no intermediate forwarder), so the loop's exit is a
; direct callbr target rather than a Flow.
define void @callbr_self_loop_exit_is_ret(i1 %c) {
; CHECK-LABEL: define void @callbr_self_loop_exit_is_ret(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[CB:.*]]
; CHECK:       [[CB]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[CB_TARGET_CB:.*]] [label %[[CB_TARGET_RET:.*]]]
; CHECK:       [[FLOW:.*]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[CB_TARGET_CB]] ], [ false, %[[CB_TARGET_RET]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[RET:.*]], label %[[CB]]
; CHECK:       [[RET]]:
; CHECK-NEXT:    ret void
; CHECK:       [[CB_TARGET_CB]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[CB_TARGET_RET]]:
; CHECK-NEXT:    br label %[[FLOW]]
;
entry:
  br label %cb
cb:
  callbr void asm "", "!i"() to label %cb [label %ret]
ret:
  ret void
}

; The callbr block is the header of a loop with a non-callbr latch.
define void @callbr_as_loop_header(i1 %c) {
; CHECK-LABEL: define void @callbr_as_loop_header(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[CB:.*]]
; CHECK:       [[EXIT:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ [[TMP2:%.*]], %[[FLOW5:.*]] ], [ true, %[[FLOW2:.*]] ]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[FLOW6:.*]], label %[[CB]]
; CHECK:       [[FLOW:.*]]:
; CHECK-NEXT:    br label %[[FLOW5]]
; CHECK:       [[CB]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[CB_TARGET_BODY:.*]] [label %[[CB_TARGET_EXIT:.*]]]
; CHECK:       [[FLOW3:.*]]:
; CHECK-NEXT:    br i1 [[C]], label %[[FLOW]], label %[[FLOW5]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    [[TMP1:%.*]] = phi i1 [ true, %[[CB_TARGET_BODY]] ], [ false, %[[CB_TARGET_EXIT]] ]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[FLOW3]], label %[[EXIT]]
; CHECK:       [[FLOW5]]:
; CHECK-NEXT:    [[TMP2]] = phi i1 [ false, %[[FLOW]] ], [ true, %[[FLOW3]] ]
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[FLOW6]]:
; CHECK-NEXT:    ret void
; CHECK:       [[CB_TARGET_BODY]]:
; CHECK-NEXT:    br label %[[FLOW2]]
; CHECK:       [[CB_TARGET_EXIT]]:
; CHECK-NEXT:    br label %[[FLOW2]]
;
entry:
  br label %cb
cb:
  callbr void asm "", "!i"() to label %body [label %exit]
body:
  br i1 %c, label %cb, label %exit
exit:
  ret void
}

; A back edge whose target is a callbr that is also a region exit: the
; if-diamond reconverges at %cb (callbr), and %cb's indirect target loops
; back to %cb. This makes %cb both a region exit and a loop header.
define void @callbr_exit_is_loop_header(i1 %c) {
; CHECK-LABEL: define void @callbr_exit_is_loop_header(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[C_INV:%.*]] = xor i1 [[C]], true
; CHECK-NEXT:    br i1 [[C_INV]], label %[[B:.*]], label %[[FLOW5:.*]]
; CHECK:       [[FLOW5]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ false, %[[B]] ], [ true, %[[ENTRY]] ]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[A:.*]], label %[[CB:.*]]
; CHECK:       [[A]]:
; CHECK-NEXT:    br label %[[CB]]
; CHECK:       [[B]]:
; CHECK-NEXT:    br label %[[FLOW5]]
; CHECK:       [[FLOW4:.*]]:
; CHECK-NEXT:    [[TMP1:%.*]] = phi i1 [ false, %[[FLOW:.*]] ], [ true, %[[FLOW2:.*]] ]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[OUT:.*]], label %[[CB]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    br label %[[FLOW4]]
; CHECK:       [[CB]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[CB_TARGET_OUT:.*]] [label %[[BODY:.*]]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    br label %[[FLOW2]]
; CHECK:       [[FLOW3:.*]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[CB_TARGET_OUT]] ], [ false, %[[BODY]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[FLOW3]], label %[[FLOW4]]
; CHECK:       [[OUT]]:
; CHECK-NEXT:    ret void
; CHECK:       [[CB_TARGET_OUT]]:
; CHECK-NEXT:    br label %[[FLOW2]]
;
entry:
  br i1 %c, label %A, label %B
A:
  br label %cb
B:
  br label %cb
cb:
  callbr void asm "", "!i"() to label %out [label %body]
body:
  br label %latch
latch:
  br label %cb
out:
  ret void
}

; The callbr is the LATCH of a loop whose header is a separate non-callbr block:
; %header dominates %cb, so the callbr's fallthrough edge %cb -> %header is a
; back edge, while the indirect edge %cb -> %out leaves the loop.
define void @callbr_latch_separate_header(i1 %c) {
; CHECK-LABEL: define void @callbr_latch_separate_header(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    br i1 [[C]], label %[[FLOW:.*]], label %[[FLOW4:.*]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    br label %[[CB:.*]]
; CHECK:       [[FLOW4]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ [[ISLAND_SEL_INV:%.*]], %[[FLOW2:.*]] ], [ true, %[[HEADER]] ]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[FLOW5:.*]], label %[[HEADER]]
; CHECK:       [[CB]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[CB_TARGET_HEADER:.*]] [label %[[OUT:.*]]]
; CHECK:       [[OUT]]:
; CHECK-NEXT:    br label %[[FLOW2]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[CB_TARGET_HEADER]] ], [ false, %[[OUT]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br label %[[FLOW4]]
; CHECK:       [[FLOW5]]:
; CHECK-NEXT:    ret void
; CHECK:       [[CB_TARGET_HEADER]]:
; CHECK-NEXT:    br label %[[FLOW2]]
;
entry:
  br label %header
header:
  br i1 %c, label %cb, label %exit
cb:
  callbr void asm "", "!i"() to label %header [label %out]
out:
  br label %exit
exit:
  ret void
}

; The callbr sits inside a loop with a non-callbr header and latch.
define void @callbr_inside_loop(i1 %c) {
; CHECK-LABEL: define void @callbr_inside_loop(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C_INV:%.*]] = xor i1 [[C]], true
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    br i1 [[C]], label %[[CB:.*]], label %[[FLOW2:.*]]
; CHECK:       [[CB]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[FT:.*]] [label %[[IND:.*]]]
; CHECK:       [[FT]]:
; CHECK-NEXT:    br label %[[FLOW:.*]]
; CHECK:       [[IND]]:
; CHECK-NEXT:    br label %[[FLOW]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[FT]] ], [ false, %[[IND]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV:%.*]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br i1 [[ISLAND_SEL_INV]], label %[[FLOW1:.*]], label %[[LATCH:.*]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ [[C_INV]], %[[LATCH]] ], [ true, %[[HEADER]] ]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[EXIT:.*]], label %[[HEADER]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    br label %[[FLOW2]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header
header:
  br i1 %c, label %cb, label %exit
cb:
  callbr void asm "", "!i"() to label %ft [label %ind]
ft:
  br label %latch
ind:
  br label %latch
latch:
  br i1 %c, label %header, label %exit
exit:
  ret void
}

; reducible loop among targets: only %t0 is a direct callbr target; %t0 and %body
; form the loop, %t1 is the exit target.
define void @callbr_target_starts_loop(i1 %c) {
; CHECK-LABEL: define void @callbr_target_starts_loop(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C_INV:%.*]] = xor i1 [[C]], true
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[ENTRY_TARGET_T0:.*]] [label %[[T1:.*]]]
; CHECK:       [[T0:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    br i1 [[C_INV]], label %[[FLOW:.*]], label %[[T0]]
; CHECK:       [[T1]]:
; CHECK-NEXT:    br label %[[FLOW1:.*]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[FLOW1]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[ENTRY_TARGET_T0]] ], [ false, %[[T1]] ]
; CHECK-NEXT:    br i1 [[ISLAND_SEL]], label %[[T0]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
; CHECK:       [[ENTRY_TARGET_T0]]:
; CHECK-NEXT:    br label %[[FLOW1]]
;
entry:
  callbr void asm "", "!i"() to label %t0 [label %t1]
t0:
  br label %body
body:
  br i1 %c, label %t0, label %exit
t1:
  br label %exit
exit:
  ret void
}

; callbr is the latch of the INNER of two nested loops.
define void @callbr_inner_latch_nested_loop(i1 %c, i1 %d) {
; CHECK-LABEL: define void @callbr_inner_latch_nested_loop(
; CHECK-SAME: i1 [[C:%.*]], i1 [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[D_INV:%.*]] = xor i1 [[D]], true
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    br i1 [[C]], label %[[FLOW:.*]], label %[[FLOW4:.*]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    br label %[[CB:.*]]
; CHECK:       [[FLOW4]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ [[ISLAND_SEL_INV:%.*]], %[[FLOW2:.*]] ], [ true, %[[INNER]] ]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[FLOW5:.*]], label %[[INNER]]
; CHECK:       [[CB]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[CB_TARGET_INNER:.*]] [label %[[CB_TARGET_INNER_EXIT:.*]]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    [[ISLAND_SEL:%.*]] = phi i1 [ true, %[[CB_TARGET_INNER]] ], [ false, %[[CB_TARGET_INNER_EXIT]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br label %[[FLOW4]]
; CHECK:       [[FLOW5]]:
; CHECK-NEXT:    br i1 [[D_INV]], label %[[EXIT:.*]], label %[[OUTER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
; CHECK:       [[CB_TARGET_INNER]]:
; CHECK-NEXT:    br label %[[FLOW2]]
; CHECK:       [[CB_TARGET_INNER_EXIT]]:
; CHECK-NEXT:    br label %[[FLOW2]]
;
entry:
  br label %outer
outer:
  br label %inner
inner:
  br i1 %c, label %cb, label %inner.exit
cb:
  callbr void asm "", "!i"() to label %inner [label %inner.exit]
inner.exit:
  br i1 %d, label %outer, label %exit
exit:
  ret void
}

; callbr with TWO back-edge successors: one to the inner header, one to the
; outer header (break-to-outer-loop).
define void @callbr_two_backedges(i1 %c, i1 %d) {
; CHECK-LABEL: define void @callbr_two_backedges(
; CHECK-SAME: i1 [[C:%.*]], i1 [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[D_INV:%.*]] = xor i1 [[D]], true
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    br i1 [[C]], label %[[FLOW:.*]], label %[[FLOW4:.*]]
; CHECK:       [[FLOW]]:
; CHECK-NEXT:    br label %[[CB:.*]]
; CHECK:       [[FLOW4]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi i1 [ [[ISLAND_SEL:%.*]], %[[FLOW2:.*]] ], [ true, %[[INNER]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ [[ISLAND_SEL_INV:%.*]], %[[FLOW2]] ], [ true, %[[INNER]] ]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[FLOW5:.*]], label %[[INNER]]
; CHECK:       [[CB]]:
; CHECK-NEXT:    callbr void asm "", "!i"()
; CHECK-NEXT:            to label %[[CB_TARGET_INNER:.*]] [label %[[CB_TARGET_OUTER:.*]]]
; CHECK:       [[FLOW2]]:
; CHECK-NEXT:    [[ISLAND_SEL]] = phi i1 [ true, %[[CB_TARGET_INNER]] ], [ false, %[[CB_TARGET_OUTER]] ]
; CHECK-NEXT:    [[ISLAND_SEL_INV]] = xor i1 [[ISLAND_SEL]], true
; CHECK-NEXT:    br label %[[FLOW4]]
; CHECK:       [[FLOW5]]:
; CHECK-NEXT:    br i1 [[TMP2]], label %[[INNER_EXIT:.*]], label %[[OUTER]]
; CHECK:       [[INNER_EXIT]]:
; CHECK-NEXT:    br i1 [[D_INV]], label %[[EXIT:.*]], label %[[OUTER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
; CHECK:       [[CB_TARGET_INNER]]:
; CHECK-NEXT:    br label %[[FLOW2]]
; CHECK:       [[CB_TARGET_OUTER]]:
; CHECK-NEXT:    br label %[[FLOW2]]
;
entry:
  br label %outer
outer:
  br label %inner
inner:
  br i1 %c, label %cb, label %inner.exit
cb:
  callbr void asm "", "!i"() to label %inner [label %outer]
inner.exit:
  br i1 %d, label %outer, label %exit
exit:
  ret void
}

; intrinsic callbr (kill) that is the latch of a loop.
define void @callbr_kill_in_loop(i1 %c, i1 %d) {
; CHECK-LABEL: define void @callbr_kill_in_loop(
; CHECK-SAME: i1 [[C:%.*]], i1 [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    br i1 [[C]], label %[[CB:.*]], label %[[EXIT:.*]]
; CHECK:       [[CB]]:
; CHECK-NEXT:    callbr void @llvm.amdgcn.kill(i1 [[D]])
; CHECK-NEXT:            to label %[[HEADER]] [label %[[DEAD:.*]]]
; CHECK:       [[DEAD]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header
header:
  br i1 %c, label %cb, label %exit
cb:
  callbr void @llvm.amdgcn.kill(i1 %d) to label %header [label %dead]
dead:
  unreachable
exit:
  ret void
}
