; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=reassociate < %s | FileCheck %s

define i32 @test(i1 %b) {
; CHECK-LABEL: @test(
; CHECK-NEXT:    [[RES:%.*]] = callbr i32 asm "", "=r,!i"()
; CHECK-NEXT:    to label [[NORMAL:%.*]] [label [[ABNORMAL:%.*]]]
; CHECK:       normal:
; CHECK-NEXT:    [[RES_NEG:%.*]] = sub i32 0, [[RES]]
; CHECK-NEXT:    [[RES_NEG1:%.*]] = sub i32 0, [[RES]]
; CHECK-NEXT:    [[SUB1:%.*]] = add i32 [[RES_NEG1]], [[RES_NEG]]
; CHECK-NEXT:    [[SUB2:%.*]] = add i32 [[SUB1]], 5
; CHECK-NEXT:    ret i32 [[SUB2]]
; CHECK:       abnormal:
; CHECK-NEXT:    ret i32 0
;
  %res = callbr i32 asm "", "=r,!i"()
  to label %normal [label %abnormal]

normal:
  %sub1 = sub nsw i32 5, %res
  %sub2 = sub nsw i32 %sub1, %res
  ret i32 %sub2

abnormal:
  ret i32 0
}
