; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt < %s -passes=reassociate -S | FileCheck %s

define <8 x i1> @vector0(<8 x i1> %b0, <8 x i1> %b1, <8 x i1> %b2, <8 x i1> %b3, <8 x i1> %b4, <8 x i1> %b5, <8 x i1> %b6, <8 x i1> %b7) {
; CHECK-LABEL: define <8 x i1> @vector0(
; CHECK-SAME: <8 x i1> [[B0:%.*]], <8 x i1> [[B1:%.*]], <8 x i1> [[B2:%.*]], <8 x i1> [[B3:%.*]], <8 x i1> [[B4:%.*]], <8 x i1> [[B5:%.*]], <8 x i1> [[B6:%.*]], <8 x i1> [[B7:%.*]]) {
; CHECK-NEXT:    [[OR67:%.*]] = or <8 x i1> [[B1]], [[B0]]
; CHECK-NEXT:    [[OR45:%.*]] = or <8 x i1> [[OR67]], [[B2]]
; CHECK-NEXT:    [[OR4567:%.*]] = or <8 x i1> [[OR45]], [[B3]]
; CHECK-NEXT:    [[OR23:%.*]] = or <8 x i1> [[OR4567]], [[B4]]
; CHECK-NEXT:    [[OR01:%.*]] = or <8 x i1> [[OR23]], [[B5]]
; CHECK-NEXT:    [[OR0123:%.*]] = or <8 x i1> [[OR01]], [[B6]]
; CHECK-NEXT:    [[OR01234567:%.*]] = or <8 x i1> [[OR0123]], [[B7]]
; CHECK-NEXT:    ret <8 x i1> [[OR01234567]]
;
  %or01 = or <8 x i1> %b0, %b1
  %or23 = or <8 x i1> %b2, %b3
  %or45 = or <8 x i1> %b4, %b5
  %or67 = or <8 x i1> %b6, %b7
  %or0123 = or <8 x i1> %or01, %or23
  %or4567 = or <8 x i1> %or45, %or67
  %or01234567 = or <8 x i1> %or0123, %or4567
  ret <8 x i1> %or01234567
}

define <8 x i1> @vector1(<8 x i1> %b0, <8 x i1> %b1, <8 x i1> %b2, <8 x i1> %b3, <8 x i1> %b4, <8 x i1> %b5, <8 x i1> %b6, <8 x i1> %b7) {
; CHECK-LABEL: define <8 x i1> @vector1(
; CHECK-SAME: <8 x i1> [[B0:%.*]], <8 x i1> [[B1:%.*]], <8 x i1> [[B2:%.*]], <8 x i1> [[B3:%.*]], <8 x i1> [[B4:%.*]], <8 x i1> [[B5:%.*]], <8 x i1> [[B6:%.*]], <8 x i1> [[B7:%.*]]) {
; CHECK-NEXT:    [[OR67:%.*]] = and <8 x i1> [[B1]], [[B0]]
; CHECK-NEXT:    [[OR45:%.*]] = and <8 x i1> [[OR67]], [[B2]]
; CHECK-NEXT:    [[OR4567:%.*]] = and <8 x i1> [[OR45]], [[B3]]
; CHECK-NEXT:    [[OR23:%.*]] = and <8 x i1> [[OR4567]], [[B4]]
; CHECK-NEXT:    [[OR01:%.*]] = and <8 x i1> [[OR23]], [[B5]]
; CHECK-NEXT:    [[OR0123:%.*]] = and <8 x i1> [[OR01]], [[B6]]
; CHECK-NEXT:    [[OR01234567:%.*]] = and <8 x i1> [[OR0123]], [[B7]]
; CHECK-NEXT:    ret <8 x i1> [[OR01234567]]
;
  %or01 = and <8 x i1> %b0, %b1
  %or23 = and <8 x i1> %b2, %b3
  %or45 = and <8 x i1> %b4, %b5
  %or67 = and <8 x i1> %b6, %b7
  %or0123 = and <8 x i1> %or01, %or23
  %or4567 = and <8 x i1> %or45, %or67
  %or01234567 = and <8 x i1> %or0123, %or4567
  ret <8 x i1> %or01234567
}

define <8 x i1> @vector2(<8 x i1> %a, <8 x i1> %b0, <8 x i1> %b1, <8 x i1> %b2, <8 x i1> %b3, <8 x i1> %b4, <8 x i1> %b5, <8 x i1> %b6, <8 x i1> %b7) {
; CHECK-LABEL: define <8 x i1> @vector2(
; CHECK-SAME: <8 x i1> [[A:%.*]], <8 x i1> [[B0:%.*]], <8 x i1> [[B1:%.*]], <8 x i1> [[B2:%.*]], <8 x i1> [[B3:%.*]], <8 x i1> [[B4:%.*]], <8 x i1> [[B5:%.*]], <8 x i1> [[B6:%.*]], <8 x i1> [[B7:%.*]]) {
; CHECK-NEXT:    [[OR0:%.*]] = or <8 x i1> [[B0]], [[A]]
; CHECK-NEXT:    [[OR1:%.*]] = or <8 x i1> [[B1]], [[A]]
; CHECK-NEXT:    [[OR2:%.*]] = or <8 x i1> [[B2]], [[A]]
; CHECK-NEXT:    [[OR3:%.*]] = or <8 x i1> [[B3]], [[A]]
; CHECK-NEXT:    [[OR4:%.*]] = or <8 x i1> [[B4]], [[A]]
; CHECK-NEXT:    [[OR5:%.*]] = or <8 x i1> [[B5]], [[A]]
; CHECK-NEXT:    [[OR6:%.*]] = or <8 x i1> [[B6]], [[A]]
; CHECK-NEXT:    [[OR7:%.*]] = or <8 x i1> [[B7]], [[A]]
; CHECK-NEXT:    [[XOR0:%.*]] = xor <8 x i1> [[OR1]], [[OR0]]
; CHECK-NEXT:    [[XOR1:%.*]] = xor <8 x i1> [[XOR0]], [[OR2]]
; CHECK-NEXT:    [[XOR2:%.*]] = xor <8 x i1> [[XOR1]], [[OR3]]
; CHECK-NEXT:    [[XOR3:%.*]] = xor <8 x i1> [[XOR2]], [[OR4]]
; CHECK-NEXT:    [[XOR4:%.*]] = xor <8 x i1> [[XOR3]], [[OR5]]
; CHECK-NEXT:    [[XOR5:%.*]] = xor <8 x i1> [[XOR4]], [[OR6]]
; CHECK-NEXT:    [[XOR6:%.*]] = xor <8 x i1> [[XOR5]], [[OR7]]
; CHECK-NEXT:    [[OR045:%.*]] = or <8 x i1> [[XOR1]], [[XOR0]]
; CHECK-NEXT:    [[OR4560:%.*]] = or <8 x i1> [[OR045]], [[XOR2]]
; CHECK-NEXT:    [[OR023:%.*]] = or <8 x i1> [[OR4560]], [[XOR3]]
; CHECK-NEXT:    [[OR001:%.*]] = or <8 x i1> [[OR023]], [[XOR4]]
; CHECK-NEXT:    [[OR0123:%.*]] = or <8 x i1> [[OR001]], [[XOR5]]
; CHECK-NEXT:    [[OR01234567:%.*]] = or <8 x i1> [[OR0123]], [[XOR6]]
; CHECK-NEXT:    ret <8 x i1> [[OR01234567]]
;
  %or0 = or <8 x i1> %b0, %a
  %or1 = or <8 x i1> %b1, %a
  %or2 = or <8 x i1> %b2, %a
  %or3 = or <8 x i1> %b3, %a
  %or4 = or <8 x i1> %b4, %a
  %or5 = or <8 x i1> %b5, %a
  %or6 = or <8 x i1> %b6, %a
  %or7 = or <8 x i1> %b7, %a
  %xor0 = xor <8 x i1> %or0, %or1
  %xor1 = xor <8 x i1> %xor0, %or2
  %xor2 = xor <8 x i1> %xor1, %or3
  %xor3 = xor <8 x i1> %xor2, %or4
  %xor4 = xor <8 x i1> %xor3, %or5
  %xor5 = xor <8 x i1> %xor4, %or6
  %xor6 = xor <8 x i1> %xor5, %or7
  %or001 = or <8 x i1> %xor0, %xor1
  %or023 = or <8 x i1> %xor2, %xor3
  %or045 = or <8 x i1> %xor4, %xor5
  %or060 = or <8 x i1> %xor6, %xor0
  %or0123 = or <8 x i1> %or001, %or023
  %or4560 = or <8 x i1> %or045, %or060
  %or01234567 = or <8 x i1> %or0123, %or4560
  ret <8 x i1> %or01234567
}

define <8 x i1> @vector3(<8 x i1> %a, <8 x i1> %b0, <8 x i1> %b1, <8 x i1> %b2, <8 x i1> %b3, <8 x i1> %b4, <8 x i1> %b5, <8 x i1> %b6, <8 x i1> %b7) {
; CHECK-LABEL: define <8 x i1> @vector3(
; CHECK-SAME: <8 x i1> [[A:%.*]], <8 x i1> [[B0:%.*]], <8 x i1> [[B1:%.*]], <8 x i1> [[B2:%.*]], <8 x i1> [[B3:%.*]], <8 x i1> [[B4:%.*]], <8 x i1> [[B5:%.*]], <8 x i1> [[B6:%.*]], <8 x i1> [[B7:%.*]]) {
; CHECK-NEXT:    [[OR0:%.*]] = or <8 x i1> [[B0]], [[A]]
; CHECK-NEXT:    [[OR1:%.*]] = or <8 x i1> [[B1]], [[A]]
; CHECK-NEXT:    [[OR2:%.*]] = or <8 x i1> [[B2]], [[A]]
; CHECK-NEXT:    [[OR3:%.*]] = or <8 x i1> [[B3]], [[A]]
; CHECK-NEXT:    [[OR4:%.*]] = or <8 x i1> [[B4]], [[A]]
; CHECK-NEXT:    [[OR5:%.*]] = or <8 x i1> [[B5]], [[A]]
; CHECK-NEXT:    [[OR6:%.*]] = or <8 x i1> [[B6]], [[A]]
; CHECK-NEXT:    [[OR7:%.*]] = or <8 x i1> [[B7]], [[A]]
; CHECK-NEXT:    [[XOR3:%.*]] = xor <8 x i1> [[OR1]], [[OR0]]
; CHECK-NEXT:    [[XOR2:%.*]] = xor <8 x i1> [[XOR3]], [[OR2]]
; CHECK-NEXT:    [[XOR7:%.*]] = xor <8 x i1> [[XOR2]], [[OR3]]
; CHECK-NEXT:    [[XOR0:%.*]] = xor <8 x i1> [[XOR7]], [[OR4]]
; CHECK-NEXT:    [[XOR4:%.*]] = xor <8 x i1> [[XOR0]], [[OR5]]
; CHECK-NEXT:    [[XOR5:%.*]] = xor <8 x i1> [[XOR4]], [[OR6]]
; CHECK-NEXT:    [[OR4560:%.*]] = xor <8 x i1> [[XOR5]], [[OR7]]
; CHECK-NEXT:    ret <8 x i1> [[OR4560]]
;
  %or0 = or <8 x i1> %b0, %a
  %or1 = or <8 x i1> %b1, %a
  %or2 = or <8 x i1> %b2, %a
  %or3 = or <8 x i1> %b3, %a
  %or4 = or <8 x i1> %b4, %a
  %or5 = or <8 x i1> %b5, %a
  %or6 = or <8 x i1> %b6, %a
  %or7 = or <8 x i1> %b7, %a
  %xor0 = xor <8 x i1> %or0, %or1
  %xor1 = xor <8 x i1> %or2, %or3
  %xor2 = xor <8 x i1> %or4, %or5
  %xor3 = xor <8 x i1> %or6, %or7
  %or01 = xor <8 x i1> %xor0, %xor1
  %or23 = xor <8 x i1> %xor2, %xor3
  %or0123 = xor <8 x i1> %or01, %or23
  ret <8 x i1> %or0123
}

define <8 x i1> @vector4(<8 x i1> %a, <8 x i1> %b0, <8 x i1> %b1, <8 x i1> %b2, <8 x i1> %b3, <8 x i1> %b4, <8 x i1> %b5, <8 x i1> %b6, <8 x i1> %b7) {
; CHECK-LABEL: define <8 x i1> @vector4(
; CHECK-SAME: <8 x i1> [[A:%.*]], <8 x i1> [[B0:%.*]], <8 x i1> [[B1:%.*]], <8 x i1> [[B2:%.*]], <8 x i1> [[B3:%.*]], <8 x i1> [[B4:%.*]], <8 x i1> [[B5:%.*]], <8 x i1> [[B6:%.*]], <8 x i1> [[B7:%.*]]) {
; CHECK-NEXT:    [[XOR0:%.*]] = xor <8 x i1> [[B0]], [[A]]
; CHECK-NEXT:    [[XOR1:%.*]] = xor <8 x i1> [[B1]], [[A]]
; CHECK-NEXT:    [[XOR2:%.*]] = xor <8 x i1> [[B2]], [[A]]
; CHECK-NEXT:    [[XOR3:%.*]] = xor <8 x i1> [[B3]], [[A]]
; CHECK-NEXT:    [[XOR4:%.*]] = xor <8 x i1> [[B4]], [[A]]
; CHECK-NEXT:    [[XOR5:%.*]] = xor <8 x i1> [[B5]], [[A]]
; CHECK-NEXT:    [[XOR6:%.*]] = xor <8 x i1> [[B6]], [[A]]
; CHECK-NEXT:    [[XOR7:%.*]] = xor <8 x i1> [[B7]], [[A]]
; CHECK-NEXT:    [[AND3:%.*]] = and <8 x i1> [[XOR1]], [[XOR0]]
; CHECK-NEXT:    [[AND2:%.*]] = and <8 x i1> [[AND3]], [[XOR2]]
; CHECK-NEXT:    [[OR23:%.*]] = and <8 x i1> [[AND2]], [[XOR3]]
; CHECK-NEXT:    [[AND1:%.*]] = and <8 x i1> [[OR23]], [[XOR4]]
; CHECK-NEXT:    [[AND0:%.*]] = and <8 x i1> [[AND1]], [[XOR5]]
; CHECK-NEXT:    [[OR01:%.*]] = and <8 x i1> [[AND0]], [[XOR6]]
; CHECK-NEXT:    [[OR0123:%.*]] = and <8 x i1> [[OR01]], [[XOR7]]
; CHECK-NEXT:    ret <8 x i1> [[OR0123]]
;
  %xor0 = xor <8 x i1> %b0, %a
  %xor1 = xor <8 x i1> %b1, %a
  %xor2 = xor <8 x i1> %b2, %a
  %xor3 = xor <8 x i1> %b3, %a
  %xor4 = xor <8 x i1> %b4, %a
  %xor5 = xor <8 x i1> %b5, %a
  %xor6 = xor <8 x i1> %b6, %a
  %xor7 = xor <8 x i1> %b7, %a
  %and0 = and <8 x i1> %xor0, %xor1
  %and1 = and <8 x i1> %xor2, %xor3
  %and2 = and <8 x i1> %xor4, %xor5
  %and3 = and <8 x i1> %xor6, %xor7
  %or01 = and <8 x i1> %and0, %and1
  %or23 = and <8 x i1> %and2, %and3
  %or0123 = and <8 x i1> %or01, %or23
  ret <8 x i1> %or0123
}

define <8 x i1> @vector5(<8 x i1> %a, <8 x i1> %b0, <8 x i1> %b1, <8 x i1> %b2, <8 x i1> %b3, <8 x i1> %b4, <8 x i1> %b5, <8 x i1> %b6, <8 x i1> %b7) {
; CHECK-LABEL: define <8 x i1> @vector5(
; CHECK-SAME: <8 x i1> [[A:%.*]], <8 x i1> [[B0:%.*]], <8 x i1> [[B1:%.*]], <8 x i1> [[B2:%.*]], <8 x i1> [[B3:%.*]], <8 x i1> [[B4:%.*]], <8 x i1> [[B5:%.*]], <8 x i1> [[B6:%.*]], <8 x i1> [[B7:%.*]]) {
; CHECK-NEXT:    [[XOR0:%.*]] = xor <8 x i1> [[B0]], [[A]]
; CHECK-NEXT:    [[XOR1:%.*]] = xor <8 x i1> [[B1]], [[A]]
; CHECK-NEXT:    [[XOR2:%.*]] = xor <8 x i1> [[B2]], [[A]]
; CHECK-NEXT:    [[XOR3:%.*]] = xor <8 x i1> [[B3]], [[A]]
; CHECK-NEXT:    [[XOR4:%.*]] = xor <8 x i1> [[B4]], [[A]]
; CHECK-NEXT:    [[XOR5:%.*]] = xor <8 x i1> [[B5]], [[A]]
; CHECK-NEXT:    [[XOR6:%.*]] = xor <8 x i1> [[B6]], [[A]]
; CHECK-NEXT:    [[XOR7:%.*]] = xor <8 x i1> [[B7]], [[A]]
; CHECK-NEXT:    [[OR3:%.*]] = or <8 x i1> [[B1]], [[B0]]
; CHECK-NEXT:    [[OR2:%.*]] = or <8 x i1> [[OR3]], [[XOR0]]
; CHECK-NEXT:    [[OR23:%.*]] = or <8 x i1> [[OR2]], [[B2]]
; CHECK-NEXT:    [[OR1:%.*]] = or <8 x i1> [[OR23]], [[XOR1]]
; CHECK-NEXT:    [[OR0:%.*]] = or <8 x i1> [[OR1]], [[B3]]
; CHECK-NEXT:    [[OR01:%.*]] = or <8 x i1> [[OR0]], [[XOR2]]
; CHECK-NEXT:    [[OR0123:%.*]] = or <8 x i1> [[OR01]], [[B4]]
; CHECK-NEXT:    [[OR7:%.*]] = or <8 x i1> [[OR0123]], [[XOR3]]
; CHECK-NEXT:    [[OR6:%.*]] = or <8 x i1> [[OR7]], [[B5]]
; CHECK-NEXT:    [[OR67:%.*]] = or <8 x i1> [[OR6]], [[XOR4]]
; CHECK-NEXT:    [[OR5:%.*]] = or <8 x i1> [[OR67]], [[B6]]
; CHECK-NEXT:    [[OR4:%.*]] = or <8 x i1> [[OR5]], [[XOR5]]
; CHECK-NEXT:    [[OR45:%.*]] = or <8 x i1> [[OR4]], [[B7]]
; CHECK-NEXT:    [[OR4567:%.*]] = or <8 x i1> [[OR45]], [[XOR6]]
; CHECK-NEXT:    [[OR01234567:%.*]] = or <8 x i1> [[OR4567]], [[XOR7]]
; CHECK-NEXT:    ret <8 x i1> [[OR01234567]]
;
  %xor0 = xor <8 x i1> %b0, %a
  %xor1 = xor <8 x i1> %b1, %a
  %xor2 = xor <8 x i1> %b2, %a
  %xor3 = xor <8 x i1> %b3, %a
  %xor4 = xor <8 x i1> %b4, %a
  %xor5 = xor <8 x i1> %b5, %a
  %xor6 = xor <8 x i1> %b6, %a
  %xor7 = xor <8 x i1> %b7, %a
  %or0 = or <8 x i1> %xor0, %xor1
  %or1 = or <8 x i1> %xor2, %xor3
  %or2 = or <8 x i1> %xor4, %xor5
  %or3 = or <8 x i1> %xor6, %xor7
  %or4 = or <8 x i1> %b0, %b1
  %or5 = or <8 x i1> %b2, %b3
  %or6 = or <8 x i1> %b4, %b5
  %or7 = or <8 x i1> %b6, %b7
  %or01 = or <8 x i1> %or0, %or1
  %or23 = or <8 x i1> %or2, %or3
  %or45 = or <8 x i1> %or4, %or5
  %or67 = or <8 x i1> %or6, %or7
  %or0123 = or <8 x i1> %or01, %or23
  %or4567 = or <8 x i1> %or45, %or67
  %or01234567 = or <8 x i1> %or0123, %or4567
  ret <8 x i1> %or01234567
}
