; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=dse -S < %s | FileCheck %s

@g = global [100 x i32] zeroinitializer

define i32 @test(i32 %i1, i32 %i2, i32 %i3) {
; CHECK-LABEL: define i32 @test(
; CHECK-SAME: i32 [[I1:%.*]], i32 [[I2:%.*]], i32 [[I3:%.*]]) {
; CHECK-NEXT:    [[P1:%.*]] = getelementptr i32, ptr @g, i32 [[I1]]
; CHECK-NEXT:    [[P2:%.*]] = getelementptr i32, ptr @g, i32 [[I2]]
; CHECK-NEXT:    [[P1_P:%.*]] = call ptr @llvm.experimental.provenance.begin.p0.p0(ptr [[P1]])
; CHECK-NEXT:    [[R:%.*]] = load i32, ptr [[P2]], align 4
; CHECK-NEXT:    store i32 1, ptr [[P1_P]], align 4
; CHECK-NEXT:    call void @llvm.experimental.provenance.end.p0(ptr [[P1_P]])
; CHECK-NEXT:    [[R1:%.*]] = load i32, ptr [[P1_P]], align 4
; CHECK-NEXT:    [[R2:%.*]] = add i32 [[R]], [[R1]]
; CHECK-NEXT:    ret i32 [[R2]]
;
  %p1 = getelementptr i32, ptr @g, i32 %i1
  %p2 = getelementptr i32, ptr @g, i32 %i2
  %p1.p = call ptr @llvm.experimental.provenance.begin(ptr %p1)
  store i32 0, ptr %p1.p
  %r = load i32, ptr %p2
  store i32 1, ptr %p1.p
  call void @llvm.experimental.provenance.end(ptr %p1.p)
  %r1 = load i32, ptr %p1.p
  %r2 = add i32 %r, %r1
  ret i32 %r2
}
