; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt < %s -passes=infer-alignment -S | FileCheck %s

define void @test_assume_then_load(ptr %base, i64 %idx) {
; CHECK-LABEL: define void @test_assume_then_load
; CHECK-SAME: (ptr [[BASE:%.*]], i64 [[IDX:%.*]]) {
; CHECK-NEXT:    [[IDX_SHIFTED:%.*]] = shl i64 [[IDX]], 2
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds float, ptr [[BASE]], i64 [[IDX_SHIFTED]]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[GEP1]], i64 16) ]
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds float, ptr [[BASE]], i64 [[IDX_SHIFTED]]
; CHECK-NEXT:    [[LOAD:%.*]] = load float, ptr [[GEP2]], align 16
; CHECK-NEXT:    ret void
;
  %idx.shifted = shl i64 %idx, 2
  %gep1 = getelementptr inbounds float, ptr %base, i64 %idx.shifted
  call void @llvm.assume(i1 true) [ "align"(ptr %gep1, i64 16) ]
  %gep2 = getelementptr inbounds float, ptr %base, i64 %idx.shifted
  %load = load float, ptr %gep2, align 4
  ret void
}

define void @test_assume_addrspace_cast(ptr %base, i64 %idx) {
; CHECK-LABEL: define void @test_assume_addrspace_cast
; CHECK-SAME: (ptr [[BASE:%.*]], i64 [[IDX:%.*]]) {
; CHECK-NEXT:    [[IDX_SHIFTED:%.*]] = shl i64 [[IDX]], 2
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds float, ptr [[BASE]], i64 [[IDX_SHIFTED]]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[GEP1]], i64 16) ]
; CHECK-NEXT:    [[CAST:%.*]] = addrspacecast ptr [[BASE]] to ptr addrspace(1)
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[CAST]], i64 [[IDX_SHIFTED]]
; CHECK-NEXT:    [[LOAD:%.*]] = load float, ptr addrspace(1) [[GEP2]], align 16
; CHECK-NEXT:    ret void
;
  %idx.shifted = shl i64 %idx, 2
  %gep1 = getelementptr inbounds float, ptr %base, i64 %idx.shifted
  call void @llvm.assume(i1 true) [ "align"(ptr %gep1, i64 16) ]
  %cast = addrspacecast ptr %base to ptr addrspace(1)
  %gep2 = getelementptr inbounds float, ptr addrspace(1) %cast, i64 %idx.shifted
  %load = load float, ptr addrspace(1) %gep2, align 4
  ret void
}

define void @test_multiple_assumes(ptr %base, i64 %idx1, i64 %idx2) {
; CHECK-LABEL: define void @test_multiple_assumes
; CHECK-SAME: (ptr [[BASE:%.*]], i64 [[IDX1:%.*]], i64 [[IDX2:%.*]]) {
; CHECK-NEXT:    [[IDX1_SHIFTED:%.*]] = shl i64 [[IDX1]], 2
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds float, ptr [[BASE]], i64 [[IDX1_SHIFTED]]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[GEP1]], i64 16) ]
; CHECK-NEXT:    [[IDX2_SHIFTED:%.*]] = shl i64 [[IDX2]], 1
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds float, ptr [[BASE]], i64 [[IDX2_SHIFTED]]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[GEP2]], i64 8) ]
; CHECK-NEXT:    [[IDX3_SHIFTED:%.*]] = shl i64 [[IDX1]], 2
; CHECK-NEXT:    [[GEP3:%.*]] = getelementptr inbounds float, ptr [[BASE]], i64 [[IDX3_SHIFTED]]
; CHECK-NEXT:    [[LOAD:%.*]] = load float, ptr [[GEP3]], align 16
; CHECK-NEXT:    ret void
;
  %idx1.shifted = shl i64 %idx1, 2
  %gep1 = getelementptr inbounds float, ptr %base, i64 %idx1.shifted
  call void @llvm.assume(i1 true) [ "align"(ptr %gep1, i64 16) ]
  %idx2.shifted = shl i64 %idx2, 1
  %gep2 = getelementptr inbounds float, ptr %base, i64 %idx2.shifted
  call void @llvm.assume(i1 true) [ "align"(ptr %gep2, i64 8) ]
  %idx3.shifted = shl i64 %idx1, 2
  %gep3 = getelementptr inbounds float, ptr %base, i64 %idx3.shifted
  %load = load float, ptr %gep3, align 4
  ret void
}

define void @test_base_align_then_variable_gep(ptr %base, i64 %idx) {
; CHECK-LABEL: define void @test_base_align_then_variable_gep
; CHECK-SAME: (ptr [[BASE:%.*]], i64 [[IDX:%.*]]) {
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[BASE]], align 16
; CHECK-NEXT:    [[IDX_SHIFTED:%.*]] = shl i64 [[IDX]], 1
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds float, ptr [[BASE]], i64 [[IDX_SHIFTED]]
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP]], align 8
; CHECK-NEXT:    ret void
;
  %load1 = load float, ptr %base, align 16
  %idx.shifted = shl i64 %idx, 1
  %gep = getelementptr inbounds float, ptr %base, i64 %idx.shifted
  %load2 = load float, ptr %gep, align 4
  ret void
}

declare void @llvm.assume(i1)
