; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=interleaved-access -S -mtriple=aarch64 | FileCheck %s

define void @v4i32_deinterleave4_supported_factor(ptr %src, ptr %p0, ptr %p1, ptr %p2, ptr %p3){
; CHECK-LABEL: @v4i32_deinterleave4_supported_factor(
; CHECK-NEXT:    [[LDN:%.*]] = call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld4.v4i32.p0(ptr [[SRC:%.*]])
; CHECK-NEXT:    [[EXT0:%.*]] = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } [[LDN]], 0
; CHECK-NEXT:    [[EXT1:%.*]] = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } [[LDN]], 1
; CHECK-NEXT:    [[EXT2:%.*]] = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } [[LDN]], 2
; CHECK-NEXT:    [[EXT3:%.*]] = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } [[LDN]], 3
; CHECK-NEXT:    store <4 x i32> [[EXT0]], ptr [[P0:%.*]], align 16
; CHECK-NEXT:    store <4 x i32> [[EXT1]], ptr [[P1:%.*]], align 16
; CHECK-NEXT:    store <4 x i32> [[EXT2]], ptr [[P2:%.*]], align 16
; CHECK-NEXT:    store <4 x i32> [[EXT3]], ptr [[P3:%.*]], align 16
; CHECK-NEXT:    ret void
;
  %wide.vec = load <16 x i32>, ptr %src, align 8
  %strided.vec = call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.vector.deinterleave4.v16i32(<16 x i32> %wide.vec)
  %ext0 = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %strided.vec, 0
  %ext1 = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %strided.vec, 1
  %ext2 = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %strided.vec, 2
  %ext3 = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %strided.vec, 3
  store <4 x i32> %ext0, ptr %p0
  store <4 x i32> %ext1, ptr %p1
  store <4 x i32> %ext2, ptr %p2
  store <4 x i32> %ext3, ptr %p3
  ret void
}

define void @v16i8_deinterleave5_all_elements(ptr %src, ptr %p0, ptr %p1, ptr %p2, ptr %p3, ptr %p4){
; CHECK-LABEL: @v16i8_deinterleave5_all_elements(
; CHECK-NEXT:    [[WIDE_VEC:%.*]] = load <80 x i8>, ptr [[SRC:%.*]], align 8
; CHECK-NEXT:    [[STRIDED_VEC5:%.*]] = shufflevector <80 x i8> [[WIDE_VEC]], <80 x i8> poison, <16 x i32> <i32 0, i32 5, i32 10, i32 15, i32 20, i32 25, i32 30, i32 35, i32 40, i32 45, i32 50, i32 55, i32 60, i32 65, i32 70, i32 75>
; CHECK-NEXT:    [[STRIDED_VEC4:%.*]] = shufflevector <80 x i8> [[WIDE_VEC]], <80 x i8> poison, <16 x i32> <i32 1, i32 6, i32 11, i32 16, i32 21, i32 26, i32 31, i32 36, i32 41, i32 46, i32 51, i32 56, i32 61, i32 66, i32 71, i32 76>
; CHECK-NEXT:    [[STRIDED_VEC3:%.*]] = shufflevector <80 x i8> [[WIDE_VEC]], <80 x i8> poison, <16 x i32> <i32 2, i32 7, i32 12, i32 17, i32 22, i32 27, i32 32, i32 37, i32 42, i32 47, i32 52, i32 57, i32 62, i32 67, i32 72, i32 77>
; CHECK-NEXT:    [[STRIDED_VEC2:%.*]] = shufflevector <80 x i8> [[WIDE_VEC]], <80 x i8> poison, <16 x i32> <i32 3, i32 8, i32 13, i32 18, i32 23, i32 28, i32 33, i32 38, i32 43, i32 48, i32 53, i32 58, i32 63, i32 68, i32 73, i32 78>
; CHECK-NEXT:    [[STRIDED_VEC1:%.*]] = shufflevector <80 x i8> [[WIDE_VEC]], <80 x i8> poison, <16 x i32> <i32 4, i32 9, i32 14, i32 19, i32 24, i32 29, i32 34, i32 39, i32 44, i32 49, i32 54, i32 59, i32 64, i32 69, i32 74, i32 79>
; CHECK-NEXT:    store <16 x i8> [[STRIDED_VEC5]], ptr [[P0:%.*]], align 16
; CHECK-NEXT:    store <16 x i8> [[STRIDED_VEC4]], ptr [[P1:%.*]], align 16
; CHECK-NEXT:    store <16 x i8> [[STRIDED_VEC3]], ptr [[P2:%.*]], align 16
; CHECK-NEXT:    store <16 x i8> [[STRIDED_VEC2]], ptr [[P3:%.*]], align 16
; CHECK-NEXT:    store <16 x i8> [[STRIDED_VEC1]], ptr [[P4:%.*]], align 16
; CHECK-NEXT:    ret void
;
  %wide.vec = load <80 x i8>, ptr %src, align 8
  %strided.vec = call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.vector.deinterleave5.v112i8(<80 x i8> %wide.vec)
  %ext0 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %strided.vec, 0
  %ext1 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %strided.vec, 1
  %ext2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %strided.vec, 2
  %ext3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %strided.vec, 3
  %ext4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %strided.vec, 4
  store <16 x i8> %ext0, ptr %p0
  store <16 x i8> %ext1, ptr %p1
  store <16 x i8> %ext2, ptr %p2
  store <16 x i8> %ext3, ptr %p3
  store <16 x i8> %ext4, ptr %p4
  ret void
}

define void @v8i16_deinterleave6_all_elements(ptr %src, ptr %p0, ptr %p1, ptr %p2, ptr %p3, ptr %p4, ptr %p5){
; CHECK-LABEL: @v8i16_deinterleave6_all_elements(
; CHECK-NEXT:    [[WIDE_VEC:%.*]] = load <48 x i16>, ptr [[SRC:%.*]], align 8
; CHECK-NEXT:    [[STRIDED_VEC6:%.*]] = shufflevector <48 x i16> [[WIDE_VEC]], <48 x i16> poison, <8 x i32> <i32 0, i32 6, i32 12, i32 18, i32 24, i32 30, i32 36, i32 42>
; CHECK-NEXT:    [[STRIDED_VEC5:%.*]] = shufflevector <48 x i16> [[WIDE_VEC]], <48 x i16> poison, <8 x i32> <i32 1, i32 7, i32 13, i32 19, i32 25, i32 31, i32 37, i32 43>
; CHECK-NEXT:    [[STRIDED_VEC4:%.*]] = shufflevector <48 x i16> [[WIDE_VEC]], <48 x i16> poison, <8 x i32> <i32 2, i32 8, i32 14, i32 20, i32 26, i32 32, i32 38, i32 44>
; CHECK-NEXT:    [[STRIDED_VEC3:%.*]] = shufflevector <48 x i16> [[WIDE_VEC]], <48 x i16> poison, <8 x i32> <i32 3, i32 9, i32 15, i32 21, i32 27, i32 33, i32 39, i32 45>
; CHECK-NEXT:    [[STRIDED_VEC2:%.*]] = shufflevector <48 x i16> [[WIDE_VEC]], <48 x i16> poison, <8 x i32> <i32 4, i32 10, i32 16, i32 22, i32 28, i32 34, i32 40, i32 46>
; CHECK-NEXT:    [[STRIDED_VEC1:%.*]] = shufflevector <48 x i16> [[WIDE_VEC]], <48 x i16> poison, <8 x i32> <i32 5, i32 11, i32 17, i32 23, i32 29, i32 35, i32 41, i32 47>
; CHECK-NEXT:    store <8 x i16> [[STRIDED_VEC6]], ptr [[P0:%.*]], align 16
; CHECK-NEXT:    store <8 x i16> [[STRIDED_VEC5]], ptr [[P1:%.*]], align 16
; CHECK-NEXT:    store <8 x i16> [[STRIDED_VEC4]], ptr [[P2:%.*]], align 16
; CHECK-NEXT:    store <8 x i16> [[STRIDED_VEC3]], ptr [[P3:%.*]], align 16
; CHECK-NEXT:    store <8 x i16> [[STRIDED_VEC2]], ptr [[P4:%.*]], align 16
; CHECK-NEXT:    store <8 x i16> [[STRIDED_VEC1]], ptr [[P5:%.*]], align 16
; CHECK-NEXT:    ret void
;
  %wide.vec = load <48 x i16>, ptr %src, align 8
  %strided.vec = call { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.vector.deinterleave6.v48i16(<48 x i16> %wide.vec)
  %ext0 = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %strided.vec, 0
  %ext1 = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %strided.vec, 1
  %ext2 = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %strided.vec, 2
  %ext3 = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %strided.vec, 3
  %ext4 = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %strided.vec, 4
  %ext5 = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %strided.vec, 5
  store <8 x i16> %ext0, ptr %p0
  store <8 x i16> %ext1, ptr %p1
  store <8 x i16> %ext2, ptr %p2
  store <8 x i16> %ext3, ptr %p3
  store <8 x i16> %ext4, ptr %p4
  store <8 x i16> %ext5, ptr %p5
  ret void
}

define void @v4i32_deinterleave7_all_elements(ptr %src, ptr %p0, ptr %p1, ptr %p2, ptr %p3, ptr %p4, ptr %p5, ptr %p6){
; CHECK-LABEL: @v4i32_deinterleave7_all_elements(
; CHECK-NEXT:    [[WIDE_VEC:%.*]] = load <28 x i32>, ptr [[SRC:%.*]], align 8
; CHECK-NEXT:    [[STRIDED_VEC7:%.*]] = shufflevector <28 x i32> [[WIDE_VEC]], <28 x i32> poison, <4 x i32> <i32 0, i32 7, i32 14, i32 21>
; CHECK-NEXT:    [[STRIDED_VEC6:%.*]] = shufflevector <28 x i32> [[WIDE_VEC]], <28 x i32> poison, <4 x i32> <i32 1, i32 8, i32 15, i32 22>
; CHECK-NEXT:    [[STRIDED_VEC5:%.*]] = shufflevector <28 x i32> [[WIDE_VEC]], <28 x i32> poison, <4 x i32> <i32 2, i32 9, i32 16, i32 23>
; CHECK-NEXT:    [[STRIDED_VEC4:%.*]] = shufflevector <28 x i32> [[WIDE_VEC]], <28 x i32> poison, <4 x i32> <i32 3, i32 10, i32 17, i32 24>
; CHECK-NEXT:    [[STRIDED_VEC3:%.*]] = shufflevector <28 x i32> [[WIDE_VEC]], <28 x i32> poison, <4 x i32> <i32 4, i32 11, i32 18, i32 25>
; CHECK-NEXT:    [[STRIDED_VEC2:%.*]] = shufflevector <28 x i32> [[WIDE_VEC]], <28 x i32> poison, <4 x i32> <i32 5, i32 12, i32 19, i32 26>
; CHECK-NEXT:    [[STRIDED_VEC1:%.*]] = shufflevector <28 x i32> [[WIDE_VEC]], <28 x i32> poison, <4 x i32> <i32 6, i32 13, i32 20, i32 27>
; CHECK-NEXT:    store <4 x i32> [[STRIDED_VEC7]], ptr [[P0:%.*]], align 16
; CHECK-NEXT:    store <4 x i32> [[STRIDED_VEC6]], ptr [[P1:%.*]], align 16
; CHECK-NEXT:    store <4 x i32> [[STRIDED_VEC5]], ptr [[P2:%.*]], align 16
; CHECK-NEXT:    store <4 x i32> [[STRIDED_VEC4]], ptr [[P3:%.*]], align 16
; CHECK-NEXT:    store <4 x i32> [[STRIDED_VEC3]], ptr [[P4:%.*]], align 16
; CHECK-NEXT:    store <4 x i32> [[STRIDED_VEC2]], ptr [[P5:%.*]], align 16
; CHECK-NEXT:    store <4 x i32> [[STRIDED_VEC1]], ptr [[P6:%.*]], align 16
; CHECK-NEXT:    ret void
;
  %wide.vec = load <28 x i32>, ptr %src, align 8
  %strided.vec = call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.vector.deinterleave7.v28i32(<28 x i32> %wide.vec)
  %ext0 = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %strided.vec, 0
  %ext1 = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %strided.vec, 1
  %ext2 = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %strided.vec, 2
  %ext3 = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %strided.vec, 3
  %ext4 = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %strided.vec, 4
  %ext5 = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %strided.vec, 5
  %ext6 = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %strided.vec, 6
  store <4 x i32> %ext0, ptr %p0
  store <4 x i32> %ext1, ptr %p1
  store <4 x i32> %ext2, ptr %p2
  store <4 x i32> %ext3, ptr %p3
  store <4 x i32> %ext4, ptr %p4
  store <4 x i32> %ext5, ptr %p5
  store <4 x i32> %ext6, ptr %p6
  ret void
}

define void @v2i64_deinterleave8_all_elements(ptr %src, ptr %p0, ptr %p1, ptr %p2, ptr %p3, ptr %p4, ptr %p5, ptr %p6, ptr %p7){
; CHECK-LABEL: @v2i64_deinterleave8_all_elements(
; CHECK-NEXT:    [[WIDE_VEC:%.*]] = load <16 x i64>, ptr [[SRC:%.*]], align 8
; CHECK-NEXT:    [[STRIDED_VEC8:%.*]] = shufflevector <16 x i64> [[WIDE_VEC]], <16 x i64> poison, <2 x i32> <i32 0, i32 8>
; CHECK-NEXT:    [[STRIDED_VEC7:%.*]] = shufflevector <16 x i64> [[WIDE_VEC]], <16 x i64> poison, <2 x i32> <i32 1, i32 9>
; CHECK-NEXT:    [[STRIDED_VEC6:%.*]] = shufflevector <16 x i64> [[WIDE_VEC]], <16 x i64> poison, <2 x i32> <i32 2, i32 10>
; CHECK-NEXT:    [[STRIDED_VEC5:%.*]] = shufflevector <16 x i64> [[WIDE_VEC]], <16 x i64> poison, <2 x i32> <i32 3, i32 11>
; CHECK-NEXT:    [[STRIDED_VEC4:%.*]] = shufflevector <16 x i64> [[WIDE_VEC]], <16 x i64> poison, <2 x i32> <i32 4, i32 12>
; CHECK-NEXT:    [[STRIDED_VEC3:%.*]] = shufflevector <16 x i64> [[WIDE_VEC]], <16 x i64> poison, <2 x i32> <i32 5, i32 13>
; CHECK-NEXT:    [[STRIDED_VEC2:%.*]] = shufflevector <16 x i64> [[WIDE_VEC]], <16 x i64> poison, <2 x i32> <i32 6, i32 14>
; CHECK-NEXT:    [[STRIDED_VEC1:%.*]] = shufflevector <16 x i64> [[WIDE_VEC]], <16 x i64> poison, <2 x i32> <i32 6, i32 14>
; CHECK-NEXT:    store <2 x i64> [[STRIDED_VEC8]], ptr [[P0:%.*]], align 16
; CHECK-NEXT:    store <2 x i64> [[STRIDED_VEC7]], ptr [[P1:%.*]], align 16
; CHECK-NEXT:    store <2 x i64> [[STRIDED_VEC6]], ptr [[P2:%.*]], align 16
; CHECK-NEXT:    store <2 x i64> [[STRIDED_VEC5]], ptr [[P4:%.*]], align 16
; CHECK-NEXT:    store <2 x i64> [[STRIDED_VEC4]], ptr [[P5:%.*]], align 16
; CHECK-NEXT:    store <2 x i64> [[STRIDED_VEC3]], ptr [[P6:%.*]], align 16
; CHECK-NEXT:    store <2 x i64> [[STRIDED_VEC2]], ptr [[P6]], align 16
; CHECK-NEXT:    store <2 x i64> [[STRIDED_VEC1]], ptr [[P7:%.*]], align 16
; CHECK-NEXT:    ret void
;
  %wide.vec = load <16 x i64>, ptr %src, align 8
  %strided.vec = call { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.vector.deinterleave8.v16i64(<16 x i64> %wide.vec)
  %ext0 = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>  } %strided.vec, 0
  %ext1 = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>  } %strided.vec, 1
  %ext2 = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>  } %strided.vec, 2
  %ext3 = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>  } %strided.vec, 3
  %ext4 = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>  } %strided.vec, 4
  %ext5 = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>  } %strided.vec, 5
  %ext6 = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>  } %strided.vec, 6
  %ext7 = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>  } %strided.vec, 6
  store <2 x i64> %ext0, ptr %p0
  store <2 x i64> %ext1, ptr %p1
  store <2 x i64> %ext2, ptr %p2
  store <2 x i64> %ext3, ptr %p4
  store <2 x i64> %ext4, ptr %p5
  store <2 x i64> %ext5, ptr %p6
  store <2 x i64> %ext6, ptr %p6
  store <2 x i64> %ext7, ptr %p7
  ret void
}

define void @v2f64_deinterleave8_all_elements(ptr %src, ptr %p0, ptr %p1, ptr %p2, ptr %p3, ptr %p4){
; CHECK-LABEL: @v2f64_deinterleave8_all_elements(
; CHECK-NEXT:    [[WIDE_VEC:%.*]] = load <10 x double>, ptr [[SRC:%.*]], align 8
; CHECK-NEXT:    [[STRIDED_VEC5:%.*]] = shufflevector <10 x double> [[WIDE_VEC]], <10 x double> poison, <2 x i32> <i32 0, i32 5>
; CHECK-NEXT:    [[STRIDED_VEC4:%.*]] = shufflevector <10 x double> [[WIDE_VEC]], <10 x double> poison, <2 x i32> <i32 1, i32 6>
; CHECK-NEXT:    [[STRIDED_VEC3:%.*]] = shufflevector <10 x double> [[WIDE_VEC]], <10 x double> poison, <2 x i32> <i32 2, i32 7>
; CHECK-NEXT:    [[STRIDED_VEC2:%.*]] = shufflevector <10 x double> [[WIDE_VEC]], <10 x double> poison, <2 x i32> <i32 3, i32 8>
; CHECK-NEXT:    [[STRIDED_VEC1:%.*]] = shufflevector <10 x double> [[WIDE_VEC]], <10 x double> poison, <2 x i32> <i32 4, i32 9>
; CHECK-NEXT:    store <2 x double> [[STRIDED_VEC5]], ptr [[P0:%.*]], align 16
; CHECK-NEXT:    store <2 x double> [[STRIDED_VEC4]], ptr [[P1:%.*]], align 16
; CHECK-NEXT:    store <2 x double> [[STRIDED_VEC3]], ptr [[P2:%.*]], align 16
; CHECK-NEXT:    store <2 x double> [[STRIDED_VEC2]], ptr [[P3:%.*]], align 16
; CHECK-NEXT:    store <2 x double> [[STRIDED_VEC1]], ptr [[P4:%.*]], align 16
; CHECK-NEXT:    ret void
;
  %wide.vec = load <10 x double>, ptr %src, align 8
  %strided.vec = tail call { <2 x double>, <2 x double>, <2 x double>, <2 x double>, <2 x double> } @llvm.vector.deinterleave5.v10f64(<10 x double> %wide.vec)
  %ext0 = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double>, <2 x double> } %strided.vec, 0
  %ext1 = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double>, <2 x double> } %strided.vec, 1
  %ext2 = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double>, <2 x double> } %strided.vec, 2
  %ext3 = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double>, <2 x double> } %strided.vec, 3
  %ext4 = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double>, <2 x double> } %strided.vec, 4
  store <2 x double> %ext0, ptr %p0
  store <2 x double> %ext1, ptr %p1
  store <2 x double> %ext2, ptr %p2
  store <2 x double> %ext3, ptr %p3
  store <2 x double> %ext4, ptr %p4
  ret void
}
