; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt < %s -passes=interleaved-access -mtriple=aarch64-linux-gnu -mattr=+sve2p1 -S | FileCheck %s

; SVE2p1 supports quad deinterleaving, i.e. segments of 128 bits.
; Verify we combine into ld2q/ld4q.

; TODO-REVEC: Test all types.

define void @deinterleave4(ptr %src) {
; CHECK-LABEL: define void @deinterleave4
; CHECK-SAME: (ptr [[SRC:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i1> @llvm.aarch64.sve.convert.to.svbool.nxv4i1(<vscale x 4 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[TMP1]])
; CHECK-NEXT:    [[LDN:%.*]] = call { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32> } @llvm.aarch64.sve.ld4q.qpred.nxv4i32(<vscale x 1 x i1> [[TMP2]], ptr [[SRC]])
; CHECK-NEXT:    ret void
;
  %load = load <vscale x 16 x i32>, ptr %src, align 4
  %deinterleave = tail call { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32> } @llvm.vector.deinterleave.segments4.nxv16i32(<vscale x 16 x i32> %load)
  ret void
}

define void @deinterleave4_masked(ptr %src, <vscale x 1 x i1> %mask) {
; CHECK-LABEL: define void @deinterleave4_masked
; CHECK-SAME: (ptr [[SRC:%.*]], <vscale x 1 x i1> [[MASK:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[MASK_WIDE:%.*]] = call <vscale x 16 x i1> @llvm.vector.stretch.nxv16i1.nxv1i1(<vscale x 1 x i1> [[MASK]])
; CHECK-NEXT:    [[LDN:%.*]] = call { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32> } @llvm.aarch64.sve.ld4q.qpred.nxv4i32(<vscale x 1 x i1> [[MASK]], ptr [[SRC]])
; CHECK-NEXT:    ret void
;
  %mask.wide = call <vscale x 16 x i1> @llvm.vector.stretch.nxv16i1.nxv1i1(<vscale x 1 x i1> %mask)
  %load = call <vscale x 16 x i32> @llvm.masked.load.nxv16i32.p0(ptr %src, i32 4, <vscale x 16 x i1> %mask.wide, <vscale x 16 x i32> poison)
  %deinterleave = tail call { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32> } @llvm.vector.deinterleave.segments4.nxv16i32(<vscale x 16 x i32> %load)
  ret void
}

define void @deinterleave2_i64(ptr %src) {
; CHECK-LABEL: define void @deinterleave2_i64
; CHECK-SAME: (ptr [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i1> @llvm.aarch64.sve.convert.to.svbool.nxv2i1(<vscale x 2 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[TMP1]])
; CHECK-NEXT:    [[LDN:%.*]] = call { <vscale x 2 x i64>, <vscale x 2 x i64> } @llvm.aarch64.sve.ld2q.qpred.nxv2i64(<vscale x 1 x i1> [[TMP2]], ptr [[SRC]])
; CHECK-NEXT:    ret void
;
  %load = load <vscale x 4 x i64>, ptr %src, align 4
  %deinterleave = tail call { <vscale x 2 x i64>, <vscale x 2 x i64> } @llvm.vector.deinterleave.segments2.nxv8i32(<vscale x 4 x i64> %load)
  ret void
}

define void @deinterleave2_f64(ptr %src) {
; CHECK-LABEL: define void @deinterleave2_f64
; CHECK-SAME: (ptr [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i1> @llvm.aarch64.sve.convert.to.svbool.nxv2i1(<vscale x 2 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[TMP1]])
; CHECK-NEXT:    [[LDN:%.*]] = call { <vscale x 2 x double>, <vscale x 2 x double> } @llvm.aarch64.sve.ld2q.qpred.nxv2f64(<vscale x 1 x i1> [[TMP2]], ptr [[SRC]])
; CHECK-NEXT:    ret void
;
  %load = load <vscale x 4 x double>, ptr %src, align 4
  %deinterleave = tail call { <vscale x 2 x double>, <vscale x 2 x double> } @llvm.vector.deinterleave.segments2.nxv8i32(<vscale x 4 x double> %load)
  ret void
}

define void @deinterleave2_i32(ptr %src) {
; CHECK-LABEL: define void @deinterleave2_i32
; CHECK-SAME: (ptr [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i1> @llvm.aarch64.sve.convert.to.svbool.nxv4i1(<vscale x 4 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[TMP1]])
; CHECK-NEXT:    [[LDN:%.*]] = call { <vscale x 4 x i32>, <vscale x 4 x i32> } @llvm.aarch64.sve.ld2q.qpred.nxv4i32(<vscale x 1 x i1> [[TMP2]], ptr [[SRC]])
; CHECK-NEXT:    ret void
;
  %load = load <vscale x 8 x i32>, ptr %src, align 4
  %deinterleave = tail call { <vscale x 4 x i32>, <vscale x 4 x i32> } @llvm.vector.deinterleave.segments2.nxv8i32(<vscale x 8 x i32> %load)
  ret void
}

define void @deinterleave2_f32(ptr %src) {
; CHECK-LABEL: define void @deinterleave2_f32
; CHECK-SAME: (ptr [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i1> @llvm.aarch64.sve.convert.to.svbool.nxv4i1(<vscale x 4 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[TMP1]])
; CHECK-NEXT:    [[LDN:%.*]] = call { <vscale x 4 x float>, <vscale x 4 x float> } @llvm.aarch64.sve.ld2q.qpred.nxv4f32(<vscale x 1 x i1> [[TMP2]], ptr [[SRC]])
; CHECK-NEXT:    ret void
;
  %load = load <vscale x 8 x float>, ptr %src, align 4
  %deinterleave = tail call { <vscale x 4 x float>, <vscale x 4 x float> } @llvm.vector.deinterleave.segments2.nxv8i32(<vscale x 8 x float> %load)
  ret void
}

define void @deinterleave2_i16(ptr %src) {
; CHECK-LABEL: define void @deinterleave2_i16
; CHECK-SAME: (ptr [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i1> @llvm.aarch64.sve.convert.to.svbool.nxv8i1(<vscale x 8 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[TMP1]])
; CHECK-NEXT:    [[LDN:%.*]] = call { <vscale x 8 x i16>, <vscale x 8 x i16> } @llvm.aarch64.sve.ld2q.qpred.nxv8i16(<vscale x 1 x i1> [[TMP2]], ptr [[SRC]])
; CHECK-NEXT:    ret void
;
  %load = load <vscale x 16 x i16>, ptr %src, align 4
  %deinterleave = tail call { <vscale x 8 x i16>, <vscale x 8 x i16> } @llvm.vector.deinterleave.segments2.nxv8i32(<vscale x 16 x i16> %load)
  ret void
}

define void @deinterleave2_i16_masked(ptr %src, <vscale x 1 x i1> %mask) {
; CHECK-LABEL: define void @deinterleave2_i16_masked
; CHECK-SAME: (ptr [[SRC:%.*]], <vscale x 1 x i1> [[MASK:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[MASK_WIDE:%.*]] = call <vscale x 16 x i1> @llvm.vector.stretch.nxv16i1.nxv1i1(<vscale x 1 x i1> [[MASK]])
; CHECK-NEXT:    [[LDN:%.*]] = call { <vscale x 8 x i16>, <vscale x 8 x i16> } @llvm.aarch64.sve.ld2q.qpred.nxv8i16(<vscale x 1 x i1> [[MASK]], ptr [[SRC]])
; CHECK-NEXT:    ret void
;
  %mask.wide = call <vscale x 16 x i1> @llvm.vector.stretch.nxv16i1.nxv1i1(<vscale x 1 x i1> %mask)
  %load = call <vscale x 16 x i16> @llvm.masked.load.nxv16i16.p0(ptr %src, i32 16, <vscale x 16 x i1> %mask.wide, <vscale x 16 x i16> poison)
  %deinterleave = tail call { <vscale x 8 x i16>, <vscale x 8 x i16> } @llvm.vector.deinterleave.segments2.nxv8i32(<vscale x 16 x i16> %load)
  ret void
}

define void @deinterleave2_f16(ptr %src) {
; CHECK-LABEL: define void @deinterleave2_f16
; CHECK-SAME: (ptr [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i1> @llvm.aarch64.sve.convert.to.svbool.nxv8i1(<vscale x 8 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[TMP1]])
; CHECK-NEXT:    [[LDN:%.*]] = call { <vscale x 8 x half>, <vscale x 8 x half> } @llvm.aarch64.sve.ld2q.qpred.nxv8f16(<vscale x 1 x i1> [[TMP2]], ptr [[SRC]])
; CHECK-NEXT:    ret void
;
  %load = load <vscale x 16 x half>, ptr %src, align 4
  %deinterleave = tail call { <vscale x 8 x half>, <vscale x 8 x half> } @llvm.vector.deinterleave.segments2.nxv8i32(<vscale x 16 x half> %load)
  ret void
}

define void @deinterleave2_bf16(ptr %src) {
; CHECK-LABEL: define void @deinterleave2_bf16
; CHECK-SAME: (ptr [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i1> @llvm.aarch64.sve.convert.to.svbool.nxv8i1(<vscale x 8 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[TMP1]])
; CHECK-NEXT:    [[LDN:%.*]] = call { <vscale x 8 x bfloat>, <vscale x 8 x bfloat> } @llvm.aarch64.sve.ld2q.qpred.nxv8bf16(<vscale x 1 x i1> [[TMP2]], ptr [[SRC]])
; CHECK-NEXT:    ret void
;
  %load = load <vscale x 16 x bfloat>, ptr %src, align 4
  %deinterleave = tail call { <vscale x 8 x bfloat>, <vscale x 8 x bfloat> } @llvm.vector.deinterleave.segments2.nxv8i32(<vscale x 16 x bfloat> %load)
  ret void
}

define void @deinterleave2_i8(ptr %src) {
; CHECK-LABEL: define void @deinterleave2_i8
; CHECK-SAME: (ptr [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i1> @llvm.aarch64.sve.convert.to.svbool.nxv16i1(<vscale x 16 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[TMP1]])
; CHECK-NEXT:    [[LDN:%.*]] = call { <vscale x 16 x i8>, <vscale x 16 x i8> } @llvm.aarch64.sve.ld2q.qpred.nxv16i8(<vscale x 1 x i1> [[TMP2]], ptr [[SRC]])
; CHECK-NEXT:    ret void
;
  %load = load <vscale x 32 x i8>, ptr %src, align 4
  %deinterleave = tail call { <vscale x 16 x i8>, <vscale x 16 x i8> } @llvm.vector.deinterleave.segments2.nxv8i32(<vscale x 32 x i8> %load)
  ret void
}

; Cannot deinterleave segments of 64 bits
define void @narrow_deinterleave2(ptr %src) {
; CHECK-LABEL: define void @narrow_deinterleave2
; CHECK-SAME: (ptr [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[SRC]], align 4
; CHECK-NEXT:    [[DEINTERLEAVE:%.*]] = tail call { <vscale x 2 x i32>, <vscale x 2 x i32> } @llvm.vector.deinterleave.segments2.nxv4i32(<vscale x 4 x i32> [[LOAD]])
; CHECK-NEXT:    ret void
;
  %load = load <vscale x 4 x i32>, ptr %src, align 4
  %deinterleave = tail call { <vscale x 2 x i32>, <vscale x 2 x i32> } @llvm.vector.deinterleave.segments2.nxv4i32(<vscale x 4 x i32> %load)
  ret void
}

; Cannot deinterleave segments of 256 bits
define void @wide_deinterleave2(ptr %src) {
; CHECK-LABEL: define void @wide_deinterleave2
; CHECK-SAME: (ptr [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = load <vscale x 16 x i32>, ptr [[SRC]], align 4
; CHECK-NEXT:    [[DEINTERLEAVE:%.*]] = tail call { <vscale x 8 x i32>, <vscale x 8 x i32> } @llvm.vector.deinterleave.segments2.nxv16i32(<vscale x 16 x i32> [[LOAD]])
; CHECK-NEXT:    ret void
;
  %load = load <vscale x 16 x i32>, ptr %src, align 4
  %deinterleave = tail call { <vscale x 8 x i32>, <vscale x 8 x i32> } @llvm.vector.deinterleave.segments2.nxv16i32(<vscale x 16 x i32> %load)
  ret void
}
