; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt < %s -passes=interleaved-access -mtriple=aarch64-linux-gnu -mattr=+sve2p1 -S | FileCheck %s

; SVE2p1 supports quad interleaving, i.e. segments of 128 bits.
; Verify we combine into st2q/st4q.

; TODO-REVEC: Test all types.

define void @interleave4(ptr %dst, <vscale x 4 x i32> %v0, <vscale x 4 x i32> %v1, <vscale x 4 x i32> %v2, <vscale x 4 x i32> %v3) {
; CHECK-LABEL: define void @interleave4
; CHECK-SAME: (ptr [[DST:%.*]], <vscale x 4 x i32> [[V0:%.*]], <vscale x 4 x i32> [[V1:%.*]], <vscale x 4 x i32> [[V2:%.*]], <vscale x 4 x i32> [[V3:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i1> @llvm.aarch64.sve.convert.to.svbool.nxv4i1(<vscale x 4 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[TMP1]])
; CHECK-NEXT:    call void @llvm.aarch64.sve.st4q.qpred.nxv4i32(<vscale x 4 x i32> [[V0]], <vscale x 4 x i32> [[V1]], <vscale x 4 x i32> [[V2]], <vscale x 4 x i32> [[V3]], <vscale x 1 x i1> [[TMP2]], ptr [[DST]])
; CHECK-NEXT:    ret void
;
  %interleaved.vec = call <vscale x 16 x i32> @llvm.vector.interleave.segments4.nxv16i32(<vscale x 4 x i32> %v0, <vscale x 4 x i32> %v1, <vscale x 4 x i32> %v2, <vscale x 4 x i32> %v3)
  store <vscale x 16 x i32> %interleaved.vec, ptr %dst, align 4
  ret void
}

define void @interleave4_masked(ptr %dst, <vscale x 4 x i32> %v0, <vscale x 4 x i32> %v1, <vscale x 4 x i32> %v2, <vscale x 4 x i32> %v3, <vscale x 1 x i1> %mask) {
; CHECK-LABEL: define void @interleave4_masked
; CHECK-SAME: (ptr [[DST:%.*]], <vscale x 4 x i32> [[V0:%.*]], <vscale x 4 x i32> [[V1:%.*]], <vscale x 4 x i32> [[V2:%.*]], <vscale x 4 x i32> [[V3:%.*]], <vscale x 1 x i1> [[MASK:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[MASK_WIDE:%.*]] = call <vscale x 16 x i1> @llvm.vector.stretch.nxv16i1.nxv1i1(<vscale x 1 x i1> [[MASK]])
; CHECK-NEXT:    call void @llvm.aarch64.sve.st4q.qpred.nxv4i32(<vscale x 4 x i32> [[V0]], <vscale x 4 x i32> [[V1]], <vscale x 4 x i32> [[V2]], <vscale x 4 x i32> [[V3]], <vscale x 1 x i1> [[MASK]], ptr [[DST]])
; CHECK-NEXT:    ret void
;
  %interleaved.vec = call <vscale x 16 x i32> @llvm.vector.interleave.segments4.nxv16i32(<vscale x 4 x i32> %v0, <vscale x 4 x i32> %v1, <vscale x 4 x i32> %v2, <vscale x 4 x i32> %v3)
  %mask.wide = call <vscale x 16 x i1> @llvm.vector.stretch.nxv32i1.nxv1i1(<vscale x 1 x i1> %mask)
  call void @llvm.masked.store.nxv16i32(<vscale x 16 x i32> %interleaved.vec, ptr %dst, i32 4, <vscale x 16 x i1> %mask.wide)
  ret void
}

; Cannot interleave segments of 64 bits.
define void @narrow_interleave4(ptr %dst, <vscale x 2 x i32> %v0, <vscale x 2 x i32> %v1, <vscale x 2 x i32> %v2, <vscale x 2 x i32> %v3) {
; CHECK-LABEL: define void @narrow_interleave4
; CHECK-SAME: (ptr [[DST:%.*]], <vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[INTERLEAVED_VEC:%.*]] = call <vscale x 8 x i32> @llvm.vector.interleave.segments4.nxv8i32(<vscale x 2 x i32> [[V0]], <vscale x 2 x i32> [[V1]], <vscale x 2 x i32> [[V2]], <vscale x 2 x i32> [[V3]])
; CHECK-NEXT:    store <vscale x 8 x i32> [[INTERLEAVED_VEC]], ptr [[DST]], align 4
; CHECK-NEXT:    ret void
;
  %interleaved.vec = call <vscale x 8 x i32> @llvm.vector.interleave.segments4.nxv16i32(<vscale x 2 x i32> %v0, <vscale x 2 x i32> %v1, <vscale x 2 x i32> %v2, <vscale x 2 x i32> %v3)
  store <vscale x 8 x i32> %interleaved.vec, ptr %dst, align 4
  ret void
}

; Cannot interleave segments of 256 bits.
define void @wide_interleave4(ptr %dst, <vscale x 8 x i32> %v0, <vscale x 8 x i32> %v1, <vscale x 8 x i32> %v2, <vscale x 8 x i32> %v3) {
; CHECK-LABEL: define void @wide_interleave4
; CHECK-SAME: (ptr [[DST:%.*]], <vscale x 8 x i32> [[V0:%.*]], <vscale x 8 x i32> [[V1:%.*]], <vscale x 8 x i32> [[V2:%.*]], <vscale x 8 x i32> [[V3:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[INTERLEAVED_VEC:%.*]] = call <vscale x 32 x i32> @llvm.vector.interleave.segments4.nxv32i32(<vscale x 8 x i32> [[V0]], <vscale x 8 x i32> [[V1]], <vscale x 8 x i32> [[V2]], <vscale x 8 x i32> [[V3]])
; CHECK-NEXT:    store <vscale x 32 x i32> [[INTERLEAVED_VEC]], ptr [[DST]], align 4
; CHECK-NEXT:    ret void
;
  %interleaved.vec = call <vscale x 32 x i32> @llvm.vector.interleave.segments4.nxv32i32(<vscale x 8 x i32> %v0, <vscale x 8 x i32> %v1, <vscale x 8 x i32> %v2, <vscale x 8 x i32> %v3)
  store <vscale x 32 x i32> %interleaved.vec, ptr %dst, align 4
  ret void
}

define void @interleave2(ptr %dst, <vscale x 4 x i32> %v0, <vscale x 4 x i32> %v1, <vscale x 4 x i32> %v2, <vscale x 4 x i32> %v3) {
; CHECK-LABEL: define void @interleave2
; CHECK-SAME: (ptr [[DST:%.*]], <vscale x 4 x i32> [[V0:%.*]], <vscale x 4 x i32> [[V1:%.*]], <vscale x 4 x i32> [[V2:%.*]], <vscale x 4 x i32> [[V3:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i1> @llvm.aarch64.sve.convert.to.svbool.nxv4i1(<vscale x 4 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[TMP1]])
; CHECK-NEXT:    call void @llvm.aarch64.sve.st2q.qpred.nxv4i32(<vscale x 4 x i32> [[V0]], <vscale x 4 x i32> [[V1]], <vscale x 1 x i1> [[TMP2]], ptr [[DST]])
; CHECK-NEXT:    ret void
;
  %interleaved.vec = call <vscale x 8 x i32> @llvm.vector.interleave.segments2.nxv8i32(<vscale x 4 x i32> %v0, <vscale x 4 x i32> %v1)
  store <vscale x 8 x i32> %interleaved.vec, ptr %dst, align 4
  ret void
}

define void @interleave2_nxi8_masked(ptr %ptr, <vscale x 16 x i8> %l, <vscale x 16 x i8> %r, <vscale x 1 x i1> %mask) #0 {
; CHECK-LABEL: define void @interleave2_nxi8_masked
; CHECK-SAME: (ptr [[PTR:%.*]], <vscale x 16 x i8> [[L:%.*]], <vscale x 16 x i8> [[R:%.*]], <vscale x 1 x i1> [[MASK:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[MASK_WIDE:%.*]] = call <vscale x 32 x i1> @llvm.vector.stretch.nxv32i1.nxv1i1(<vscale x 1 x i1> [[MASK]])
; CHECK-NEXT:    call void @llvm.aarch64.sve.st2q.qpred.nxv16i8(<vscale x 16 x i8> [[L]], <vscale x 16 x i8> [[R]], <vscale x 1 x i1> [[MASK]], ptr [[PTR]])
; CHECK-NEXT:    ret void
;
  %interleave = tail call <vscale x 32 x i8> @llvm.vector.interleave.segments2.nxv32i8(<vscale x 16 x i8> %l, <vscale x 16 x i8> %r)
  %mask.wide = call <vscale x 32 x i1> @llvm.vector.stretch.nxv32i1.nxv1i1(<vscale x 1 x i1> %mask)
  call void @llvm.masked.store.nxv32i8(<vscale x 32 x i8> %interleave, ptr %ptr, i32 8, <vscale x 32 x i1> %mask.wide)
  ret void
}
