// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +zkne -emit-llvm %s -o - \
// RUN:     | FileCheck %s  -check-prefix=RV32ZKNE

#include <stdint.h>

// RV32ZKNE-LABEL: @aes32esi(
// RV32ZKNE-NEXT:  entry:
// RV32ZKNE-NEXT:    [[RS1_ADDR:%.*]] = alloca i32, align 4
// RV32ZKNE-NEXT:    [[RS2_ADDR:%.*]] = alloca i32, align 4
// RV32ZKNE-NEXT:    store i32 [[RS1:%.*]], ptr [[RS1_ADDR]], align 4
// RV32ZKNE-NEXT:    store i32 [[RS2:%.*]], ptr [[RS2_ADDR]], align 4
// RV32ZKNE-NEXT:    [[TMP0:%.*]] = load i32, ptr [[RS1_ADDR]], align 4
// RV32ZKNE-NEXT:    [[TMP1:%.*]] = load i32, ptr [[RS2_ADDR]], align 4
// RV32ZKNE-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.aes32esi(i32 [[TMP0]], i32 [[TMP1]], i32 3)
// RV32ZKNE-NEXT:    ret i32 [[TMP2]]
//
uint32_t aes32esi(uint32_t rs1, uint32_t rs2) {
  return __builtin_riscv_aes32esi(rs1, rs2, 3);
}

// RV32ZKNE-LABEL: @aes32esmi(
// RV32ZKNE-NEXT:  entry:
// RV32ZKNE-NEXT:    [[RS1_ADDR:%.*]] = alloca i32, align 4
// RV32ZKNE-NEXT:    [[RS2_ADDR:%.*]] = alloca i32, align 4
// RV32ZKNE-NEXT:    store i32 [[RS1:%.*]], ptr [[RS1_ADDR]], align 4
// RV32ZKNE-NEXT:    store i32 [[RS2:%.*]], ptr [[RS2_ADDR]], align 4
// RV32ZKNE-NEXT:    [[TMP0:%.*]] = load i32, ptr [[RS1_ADDR]], align 4
// RV32ZKNE-NEXT:    [[TMP1:%.*]] = load i32, ptr [[RS2_ADDR]], align 4
// RV32ZKNE-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.aes32esmi(i32 [[TMP0]], i32 [[TMP1]], i32 3)
// RV32ZKNE-NEXT:    ret i32 [[TMP2]]
//
uint32_t aes32esmi(uint32_t rs1, uint32_t rs2) {
  return __builtin_riscv_aes32esmi(rs1, rs2, 3);
}
