// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +zksed -emit-llvm %s -o - \
// RUN:     | FileCheck %s  -check-prefix=RV32ZKSED

#include <stdint.h>

// RV32ZKSED-LABEL: @sm4ks(
// RV32ZKSED-NEXT:  entry:
// RV32ZKSED-NEXT:    [[RS1_ADDR:%.*]] = alloca i32, align 4
// RV32ZKSED-NEXT:    [[RS2_ADDR:%.*]] = alloca i32, align 4
// RV32ZKSED-NEXT:    store i32 [[RS1:%.*]], ptr [[RS1_ADDR]], align 4
// RV32ZKSED-NEXT:    store i32 [[RS2:%.*]], ptr [[RS2_ADDR]], align 4
// RV32ZKSED-NEXT:    [[TMP0:%.*]] = load i32, ptr [[RS1_ADDR]], align 4
// RV32ZKSED-NEXT:    [[TMP1:%.*]] = load i32, ptr [[RS2_ADDR]], align 4
// RV32ZKSED-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.sm4ks.i32(i32 [[TMP0]], i32 [[TMP1]], i32 0)
// RV32ZKSED-NEXT:    ret i32 [[TMP2]]
//
unsigned long sm4ks(unsigned long rs1, unsigned long rs2) {
  return __builtin_riscv_sm4ks(rs1, rs2, 0);
}


// RV32ZKSED-LABEL: @sm4ed(
// RV32ZKSED-NEXT:  entry:
// RV32ZKSED-NEXT:    [[RS1_ADDR:%.*]] = alloca i32, align 4
// RV32ZKSED-NEXT:    [[RS2_ADDR:%.*]] = alloca i32, align 4
// RV32ZKSED-NEXT:    store i32 [[RS1:%.*]], ptr [[RS1_ADDR]], align 4
// RV32ZKSED-NEXT:    store i32 [[RS2:%.*]], ptr [[RS2_ADDR]], align 4
// RV32ZKSED-NEXT:    [[TMP0:%.*]] = load i32, ptr [[RS1_ADDR]], align 4
// RV32ZKSED-NEXT:    [[TMP1:%.*]] = load i32, ptr [[RS2_ADDR]], align 4
// RV32ZKSED-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.sm4ed.i32(i32 [[TMP0]], i32 [[TMP1]], i32 0)
// RV32ZKSED-NEXT:    ret i32 [[TMP2]]
//
unsigned long sm4ed(unsigned long rs1, unsigned long rs2) {
  return __builtin_riscv_sm4ed(rs1, rs2, 0);
}
