// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +xsfmm32a16f \
// RUN: -target-feature +xsfmm32a32f -target-feature +xsfmm64a64f \
// RUN: -target-feature +zvfhmin -target-feature +zve64d -disable-O0-optnone \
// RUN: -emit-llvm %s -o - | \
// RUN:   opt -S -passes=mem2reg | FileCheck --check-prefix=CHECK-RV64 %s

#include <sifive_vector.h>

// CHECK-RV64-LABEL: define dso_local void @test_sf_mm_f_f_w2_f16m8(
// CHECK-RV64-SAME: <vscale x 32 x half> [[vs2:%.*]], <vscale x 32 x half> [[vs1:%.*]], i64 noundef [[TM:%.*]], i64 noundef [[TN:%.*]], i64 noundef [[TK:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.sf.mm.f.f.i64.nxv32f16(i64 0, <vscale x 32 x half> [[vs2]], <vscale x 32 x half> [[vs1]], i64 [[TM]], i64 [[TN]], i64 [[TK]], i64 2)
// CHECK-RV64-NEXT:    ret void
//
void test_sf_mm_f_f_w2_f16m8(vfloat16m8_t vs2, vfloat16m8_t vs1, size_t tm, size_t tn, size_t tk) {
  return __riscv_sf_mm_f_f_w2_f16m8(0, vs2, vs1, tm, tn, tk);
}

// CHECK-RV64-LABEL: define dso_local void @test_sf_mm_f_f_w1_f32m8(
// CHECK-RV64-SAME: <vscale x 16 x float> [[vs2:%.*]], <vscale x 16 x float> [[vs1:%.*]], i64 noundef [[TM:%.*]], i64 noundef [[TN:%.*]], i64 noundef [[TK:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.sf.mm.f.f.i64.nxvs26f32(i64 0, <vscale x 16 x float> [[vs2]], <vscale x 16 x float> [[vs1]], i64 [[TM]], i64 [[TN]], i64 [[TK]], i64 1)
// CHECK-RV64-NEXT:    ret void
//
void test_sf_mm_f_f_w1_f32m8(vfloat32m8_t vs2, vfloat32m8_t vs1, size_t tm, size_t tn, size_t tk) {
  return __riscv_sf_mm_f_f_w1_f32m8(0, vs2, vs1, tm, tn, tk);
}

// CHECK-RV64-LABEL: define dso_local void @test_sf_mm_f_f_w1_f64m8(
// CHECK-RV64-SAME: <vscale x 8 x double> [[vs2:%.*]], <vscale x 8 x double> [[vs1:%.*]], i64 noundef [[TM:%.*]], i64 noundef [[TN:%.*]], i64 noundef [[TK:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.sf.mm.f.f.i64.nxv8f64(i64 0, <vscale x 8 x double> [[vs2]], <vscale x 8 x double> [[vs1]], i64 [[TM]], i64 [[TN]], i64 [[TK]], i64 1)
// CHECK-RV64-NEXT:    ret void
//
void test_sf_mm_f_f_w1_f64m8(vfloat64m8_t vs2, vfloat64m8_t vs1, size_t tm, size_t tn, size_t tk) {
  return __riscv_sf_mm_f_f_w1_f64m8(0, vs2, vs1, tm, tn, tk);
}

