; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=amdgcn-amd-amdhsa -passes=load-store-vectorizer -S -o - %s | FileCheck %s
; RUN: opt -mtriple=amdgcn-amd-amdhsa -aa-pipeline=basic-aa -passes='function(load-store-vectorizer)' -S -o - %s | FileCheck %s

define amdgpu_kernel void @interleave(ptr addrspace(1) nocapture %a, ptr addrspace(1) nocapture %b, ptr addrspace(1) nocapture readonly %c) #0 {
; CHECK-LABEL: define amdgpu_kernel void @interleave(
; CHECK-SAME: ptr addrspace(1) captures(none) [[A:%.*]], ptr addrspace(1) captures(none) [[B:%.*]], ptr addrspace(1) readonly captures(none) [[C:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x double>, ptr addrspace(1) [[C]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x double> [[TMP0]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x double> [[TMP0]], i32 1
; CHECK-NEXT:    store <2 x double> zeroinitializer, ptr addrspace(1) [[A]], align 8
; CHECK-NEXT:    [[ADD:%.*]] = fadd double [[TMP1]], [[TMP2]]
; CHECK-NEXT:    store double [[ADD]], ptr addrspace(1) [[B]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %a.idx.1 = getelementptr inbounds double, ptr addrspace(1) %a, i64 1
  %c.idx.1 = getelementptr inbounds double, ptr addrspace(1) %c, i64 1

  %ld.c = load double, ptr addrspace(1) %c, align 8
  store double 0.0, ptr addrspace(1) %a, align 8 ; Cannot alias invariant load

  %ld.c.idx.1 = load double, ptr addrspace(1) %c.idx.1, align 8, !invariant.load !0
  store double 0.0, ptr addrspace(1) %a.idx.1, align 8

  %add = fadd double %ld.c, %ld.c.idx.1
  store double %add, ptr addrspace(1) %b

  ret void
}

attributes #0 = { nounwind }

!0 = !{}
