; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=amdgcn-amd-amdhsa -passes=load-store-vectorizer -S -o - %s | FileCheck %s

define amdgpu_kernel void @no_implicit_float(ptr addrspace(1) %out) #0 {
; CHECK-LABEL: define amdgpu_kernel void @no_implicit_float(
; CHECK-SAME: ptr addrspace(1) [[OUT:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[OUT_GEP_1:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 1
; CHECK-NEXT:    [[OUT_GEP_2:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 2
; CHECK-NEXT:    [[OUT_GEP_3:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 3
; CHECK-NEXT:    store i32 123, ptr addrspace(1) [[OUT_GEP_1]], align 4
; CHECK-NEXT:    store i32 456, ptr addrspace(1) [[OUT_GEP_2]], align 4
; CHECK-NEXT:    store i32 333, ptr addrspace(1) [[OUT_GEP_3]], align 4
; CHECK-NEXT:    store i32 1234, ptr addrspace(1) [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  %out.gep.1 = getelementptr i32, ptr addrspace(1) %out, i32 1
  %out.gep.2 = getelementptr i32, ptr addrspace(1) %out, i32 2
  %out.gep.3 = getelementptr i32, ptr addrspace(1) %out, i32 3

  store i32 123, ptr addrspace(1) %out.gep.1
  store i32 456, ptr addrspace(1) %out.gep.2
  store i32 333, ptr addrspace(1) %out.gep.3
  store i32 1234, ptr addrspace(1) %out
  ret void
}

attributes #0 = { nounwind noimplicitfloat }
