; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=amdgcn-amd-amdhsa -passes=load-store-vectorizer,dce -S -o - %s | FileCheck %s

define void @base_case(i1 %cnd, ptr addrspace(1) %a, ptr addrspace(1) %b, ptr addrspace(1) %out) {
; CHECK-LABEL: define void @base_case(
; CHECK-SAME: i1 [[CND:%.*]], ptr addrspace(1) [[A:%.*]], ptr addrspace(1) [[B:%.*]], ptr addrspace(1) [[OUT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[SELECTED:%.*]] = select i1 [[CND]], ptr addrspace(1) [[A]], ptr addrspace(1) [[B]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <3 x i32>, ptr addrspace(1) [[SELECTED]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <3 x i32> [[TMP0]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <3 x i32> [[TMP0]], i32 1
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <3 x i32> [[TMP0]], i32 2
; CHECK-NEXT:    [[T0:%.*]] = insertelement <3 x i32> poison, i32 [[TMP1]], i32 0
; CHECK-NEXT:    [[T1:%.*]] = insertelement <3 x i32> [[T0]], i32 [[TMP2]], i32 1
; CHECK-NEXT:    [[T2:%.*]] = insertelement <3 x i32> [[T1]], i32 [[TMP3]], i32 2
; CHECK-NEXT:    store <3 x i32> [[T2]], ptr addrspace(1) [[OUT]], align 16
; CHECK-NEXT:    ret void
;
entry:
  %gep1 = getelementptr inbounds i32, ptr addrspace(1) %a, i64 1
  %gep2 = getelementptr inbounds i32, ptr addrspace(1) %a, i64 2
  %gep4 = getelementptr inbounds i32, ptr addrspace(1) %b, i64 1
  %gep5 = getelementptr inbounds i32, ptr addrspace(1) %b, i64 2
  %selected = select i1 %cnd, ptr addrspace(1) %a, ptr addrspace(1) %b
  %selected14 = select i1 %cnd, ptr addrspace(1) %gep1, ptr addrspace(1) %gep4
  %selected25 = select i1 %cnd, ptr addrspace(1) %gep2, ptr addrspace(1) %gep5
  %val0 = load i32, ptr addrspace(1) %selected, align 4
  %val1 = load i32, ptr addrspace(1) %selected14, align 4
  %val2 = load i32, ptr addrspace(1) %selected25, align 4
  %t0 = insertelement <3 x i32> poison, i32 %val0, i32 0
  %t1 = insertelement <3 x i32> %t0, i32 %val1, i32 1
  %t2 = insertelement <3 x i32> %t1, i32 %val2, i32 2
  store <3 x i32> %t2, ptr addrspace(1) %out
  ret void
}

define void @scev_targeting_complex_case(i1 %cnd, ptr addrspace(1) %a, ptr addrspace(1) %b, i32 %base, ptr addrspace(1) %out) {
; CHECK-LABEL: define void @scev_targeting_complex_case(
; CHECK-SAME: i1 [[CND:%.*]], ptr addrspace(1) [[A:%.*]], ptr addrspace(1) [[B:%.*]], i32 [[BASE:%.*]], ptr addrspace(1) [[OUT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[BASE_X4:%.*]] = shl i32 [[BASE]], 2
; CHECK-NEXT:    [[BASE_X4_P1:%.*]] = add i32 [[BASE_X4]], 1
; CHECK-NEXT:    [[ZEXT_X4:%.*]] = zext i32 [[BASE_X4]] to i64
; CHECK-NEXT:    [[ZEXT_X4_P1:%.*]] = zext i32 [[BASE_X4_P1]] to i64
; CHECK-NEXT:    [[BASE_X16:%.*]] = mul i64 [[ZEXT_X4]], 4
; CHECK-NEXT:    [[BASE_X16_P4:%.*]] = shl i64 [[ZEXT_X4_P1]], 2
; CHECK-NEXT:    [[GEP_A_BASE_X16:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[A]], i64 [[BASE_X16]]
; CHECK-NEXT:    [[GEP_B_BASE_X16_P4:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[B]], i64 [[BASE_X16_P4]]
; CHECK-NEXT:    [[SELECTED_BASE_X16_P0_OR_4:%.*]] = select i1 [[CND]], ptr addrspace(1) [[GEP_A_BASE_X16]], ptr addrspace(1) [[GEP_B_BASE_X16_P4]]
; CHECK-NEXT:    [[SELECTED_BASE_X16_P40_OR_44:%.*]] = getelementptr inbounds i32, ptr addrspace(1) [[SELECTED_BASE_X16_P0_OR_4]], i64 10
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x i32>, ptr addrspace(1) [[SELECTED_BASE_X16_P40_OR_44]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x i32> [[TMP0]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x i32> [[TMP0]], i32 1
; CHECK-NEXT:    [[T0:%.*]] = insertelement <2 x i32> poison, i32 [[TMP1]], i32 0
; CHECK-NEXT:    [[T1:%.*]] = insertelement <2 x i32> [[T0]], i32 [[TMP2]], i32 1
; CHECK-NEXT:    store <2 x i32> [[T1]], ptr addrspace(1) [[OUT]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %base.x4 = shl i32 %base, 2
  %base.x4.p1 = add i32 %base.x4, 1
  %base.x4.p2 = add i32 %base.x4, 2
  %base.x4.p3 = add i32 %base.x4, 3
  %zext.x4 = zext i32 %base.x4 to i64
  %zext.x4.p1 = zext i32 %base.x4.p1 to i64
  %zext.x4.p2 = zext i32 %base.x4.p2 to i64
  %zext.x4.p3 = zext i32 %base.x4.p3 to i64
  %base.x16 = mul i64 %zext.x4, 4
  %base.x16.p4 = shl i64 %zext.x4.p1, 2
  %base.x16.p8 = shl i64 %zext.x4.p2, 2
  %base.x16.p12 = mul i64 %zext.x4.p3, 4
  %gep.a.base.x16 = getelementptr inbounds i8, ptr addrspace(1) %a, i64 %base.x16
  %gep.b.base.x16.p4 = getelementptr inbounds i8, ptr addrspace(1) %b, i64 %base.x16.p4
  %gep.a.base.x16.p8 = getelementptr inbounds i8, ptr addrspace(1) %a, i64 %base.x16.p8
  %gep.b.base.x16.p12 = getelementptr inbounds i8, ptr addrspace(1) %b, i64 %base.x16.p12
  %selected.base.x16.p0.or.4 = select i1 %cnd, ptr addrspace(1) %gep.a.base.x16, ptr addrspace(1) %gep.b.base.x16.p4
  %gep.selected.base.x16.p8.or.12 = select i1 %cnd, ptr addrspace(1) %gep.a.base.x16.p8, ptr addrspace(1) %gep.b.base.x16.p12
  %selected.base.x16.p40.or.44 = getelementptr inbounds i32, ptr addrspace(1) %selected.base.x16.p0.or.4, i64 10
  %selected.base.x16.p44.or.48 = getelementptr inbounds i32, ptr addrspace(1) %gep.selected.base.x16.p8.or.12, i64 9
  %val0 = load i32, ptr addrspace(1) %selected.base.x16.p40.or.44, align 4
  %val1 = load i32, ptr addrspace(1) %selected.base.x16.p44.or.48, align 4
  %t0 = insertelement <2 x i32> poison, i32 %val0, i32 0
  %t1 = insertelement <2 x i32> %t0, i32 %val1, i32 1
  store <2 x i32> %t1, ptr addrspace(1) %out
  ret void
}

define void @nested_selects(i1 %cnd0, i1 %cnd1, ptr addrspace(1) %a, ptr addrspace(1) %b, i32 %base, ptr addrspace(1) %out) {
; CHECK-LABEL: define void @nested_selects(
; CHECK-SAME: i1 [[CND0:%.*]], i1 [[CND1:%.*]], ptr addrspace(1) [[A:%.*]], ptr addrspace(1) [[B:%.*]], i32 [[BASE:%.*]], ptr addrspace(1) [[OUT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[BASE_P2:%.*]] = add i32 [[BASE]], 2
; CHECK-NEXT:    [[BASE_X4:%.*]] = mul i32 [[BASE]], 4
; CHECK-NEXT:    [[BASE_X4_P5:%.*]] = add i32 [[BASE_X4]], 5
; CHECK-NEXT:    [[SEXT:%.*]] = sext i32 [[BASE]] to i64
; CHECK-NEXT:    [[SEXT_P2:%.*]] = sext i32 [[BASE_P2]] to i64
; CHECK-NEXT:    [[SEXT_X4_P5:%.*]] = sext i32 [[BASE_X4_P5]] to i64
; CHECK-NEXT:    [[GEP_A_BASE:%.*]] = getelementptr inbounds i32, ptr addrspace(1) [[A]], i64 [[SEXT]]
; CHECK-NEXT:    [[GEP_A_BASE_P2:%.*]] = getelementptr inbounds i32, ptr addrspace(1) [[A]], i64 [[SEXT_P2]]
; CHECK-NEXT:    [[GEP_B_BASE_X4_P5:%.*]] = getelementptr inbounds i32, ptr addrspace(1) [[A]], i64 [[SEXT_X4_P5]]
; CHECK-NEXT:    [[SELECTED_1_L:%.*]] = select i1 [[CND1]], ptr addrspace(1) [[GEP_A_BASE_P2]], ptr addrspace(1) [[GEP_B_BASE_X4_P5]]
; CHECK-NEXT:    [[SELECTED_0_L:%.*]] = select i1 [[CND0]], ptr addrspace(1) [[GEP_A_BASE]], ptr addrspace(1) [[SELECTED_1_L]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x i32>, ptr addrspace(1) [[SELECTED_0_L]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x i32> [[TMP0]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x i32> [[TMP0]], i32 1
; CHECK-NEXT:    [[T0:%.*]] = insertelement <2 x i32> poison, i32 [[TMP1]], i32 0
; CHECK-NEXT:    [[T1:%.*]] = insertelement <2 x i32> [[T0]], i32 [[TMP2]], i32 1
; CHECK-NEXT:    store <2 x i32> [[T1]], ptr addrspace(1) [[OUT]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %base.p1 = add nsw i32 %base, 1
  %base.p2 = add i32 %base, 2
  %base.p3 = add nsw i32 %base, 3
  %base.x4 = mul i32 %base, 4
  %base.x4.p5 = add i32 %base.x4, 5
  %base.x4.p6 = add i32 %base.x4, 6
  %sext = sext i32 %base to i64
  %sext.p1 = sext i32 %base.p1 to i64
  %sext.p2 = sext i32 %base.p2 to i64
  %sext.p3 = sext i32 %base.p3 to i64
  %sext.x4.p5 = sext i32 %base.x4.p5 to i64
  %sext.x4.p6 = sext i32 %base.x4.p6 to i64
  %gep.a.base = getelementptr inbounds i32, ptr addrspace(1) %a, i64 %sext
  %gep.a.base.p1 = getelementptr inbounds i32, ptr addrspace(1) %a, i64 %sext.p1
  %gep.a.base.p2 = getelementptr inbounds i32, ptr addrspace(1) %a, i64 %sext.p2
  %gep.a.base.p3 = getelementptr inbounds i32, ptr addrspace(1) %a, i64 %sext.p3
  %gep.b.base.x4.p5 = getelementptr inbounds i32, ptr addrspace(1) %a, i64 %sext.x4.p5
  %gep.b.base.x4.p6 = getelementptr inbounds i32, ptr addrspace(1) %a, i64 %sext.x4.p6
  %selected.1.L = select i1 %cnd1, ptr addrspace(1) %gep.a.base.p2, ptr addrspace(1) %gep.b.base.x4.p5
  %selected.1.R = select i1 %cnd1, ptr addrspace(1) %gep.a.base.p3, ptr addrspace(1) %gep.b.base.x4.p6
  %selected.0.L = select i1 %cnd0, ptr addrspace(1) %gep.a.base, ptr addrspace(1) %selected.1.L
  %selected.0.R = select i1 %cnd0, ptr addrspace(1) %gep.a.base.p1, ptr addrspace(1) %selected.1.R
  %val0 = load i32, ptr addrspace(1) %selected.0.L, align 4
  %val1 = load i32, ptr addrspace(1) %selected.0.R, align 4
  %t0 = insertelement <2 x i32> poison, i32 %val0, i32 0
  %t1 = insertelement <2 x i32> %t0, i32 %val1, i32 1
  store <2 x i32> %t1, ptr addrspace(1) %out
  ret void
}
