; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -p instcombine -S %s | FileCheck %s

target datalayout = "b:16-p:32:32"

declare ptr @memcpy(ptr, ptr, i32)

define ptr @test_size_1(ptr %dst, ptr %src) {
; CHECK-LABEL: define ptr @test_size_1(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[SRC]], align 1
; CHECK-NEXT:    store i16 [[TMP1]], ptr [[DST]], align 1
; CHECK-NEXT:    ret ptr [[DST]]
;
  %call = call ptr @memcpy(ptr %dst, ptr %src, i32 1)
  ret ptr %call
}

define ptr @test_size_2(ptr %dst, ptr %src) {
; CHECK-LABEL: define ptr @test_size_2(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[SRC]], align 1
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[DST]], align 1
; CHECK-NEXT:    ret ptr [[DST]]
;
  %call = call ptr @memcpy(ptr %dst, ptr %src, i32 2)
  ret ptr %call
}

define ptr @test_size_3(ptr %dst, ptr %src) {
; CHECK-LABEL: define ptr @test_size_3(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(3) [[DST]], ptr noundef nonnull align 1 dereferenceable(3) [[SRC]], i32 3, i1 false)
; CHECK-NEXT:    ret ptr [[DST]]
;
  %call = call ptr @memcpy(ptr %dst, ptr %src, i32 3)
  ret ptr %call
}

define ptr @test_size_4(ptr %dst, ptr %src) {
; CHECK-LABEL: define ptr @test_size_4(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[SRC]], align 1
; CHECK-NEXT:    store i64 [[TMP1]], ptr [[DST]], align 1
; CHECK-NEXT:    ret ptr [[DST]]
;
  %call = call ptr @memcpy(ptr %dst, ptr %src, i32 4)
  ret ptr %call
}

define ptr @test_size_5(ptr %dst, ptr %src) {
; CHECK-LABEL: define ptr @test_size_5(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(5) [[DST]], ptr noundef nonnull align 1 dereferenceable(5) [[SRC]], i32 5, i1 false)
; CHECK-NEXT:    ret ptr [[DST]]
;
  %call = call ptr @memcpy(ptr %dst, ptr %src, i32 5)
  ret ptr %call
}

define ptr @test_size_8(ptr %dst, ptr %src) {
; CHECK-LABEL: define ptr @test_size_8(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(8) [[DST]], ptr noundef nonnull align 1 dereferenceable(8) [[SRC]], i32 8, i1 false)
; CHECK-NEXT:    ret ptr [[DST]]
;
  %call = call ptr @memcpy(ptr %dst, ptr %src, i32 8)
  ret ptr %call
}
