; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -p instcombine -S %s | FileCheck %s

target datalayout = "b:16-p:32:32"

declare ptr @memset(ptr, i32, i32)

define ptr @test_size_1(ptr %dst) {
; CHECK-LABEL: define ptr @test_size_1(
; CHECK-SAME: ptr [[DST:%.*]]) {
; CHECK-NEXT:    store i16 42, ptr [[DST]], align 1
; CHECK-NEXT:    ret ptr [[DST]]
;
  %call = call ptr @memset(ptr %dst, i32 42, i32 1)
  ret ptr %call
}

define ptr @test_size_2(ptr %dst) {
; CHECK-LABEL: define ptr @test_size_2(
; CHECK-SAME: ptr [[DST:%.*]]) {
; CHECK-NEXT:    store i32 2752554, ptr [[DST]], align 1
; CHECK-NEXT:    ret ptr [[DST]]
;
  %call = call ptr @memset(ptr %dst, i32 42, i32 2)
  ret ptr %call
}

define ptr @test_size_3(ptr %dst) {
; CHECK-LABEL: define ptr @test_size_3(
; CHECK-SAME: ptr [[DST:%.*]]) {
; CHECK-NEXT:    call void @llvm.memset.p0.i32(ptr noundef nonnull align 1 dereferenceable(3) [[DST]], i16 42, i32 3, i1 false)
; CHECK-NEXT:    ret ptr [[DST]]
;
  %call = call ptr @memset(ptr %dst, i32 42, i32 3)
  ret ptr %call
}

define ptr @test_size_4(ptr %dst) {
; CHECK-LABEL: define ptr @test_size_4(
; CHECK-SAME: ptr [[DST:%.*]]) {
; CHECK-NEXT:    store i64 11822129413226538, ptr [[DST]], align 1
; CHECK-NEXT:    ret ptr [[DST]]
;
  %call = call ptr @memset(ptr %dst, i32 42, i32 4)
  ret ptr %call
}

define ptr @test_size_5(ptr %dst) {
; CHECK-LABEL: define ptr @test_size_5(
; CHECK-SAME: ptr [[DST:%.*]]) {
; CHECK-NEXT:    call void @llvm.memset.p0.i32(ptr noundef nonnull align 1 dereferenceable(5) [[DST]], i16 42, i32 5, i1 false)
; CHECK-NEXT:    ret ptr [[DST]]
;
  %call = call ptr @memset(ptr %dst, i32 42, i32 5)
  ret ptr %call
}

define ptr @test_size_8(ptr %dst) {
; CHECK-LABEL: define ptr @test_size_8(
; CHECK-SAME: ptr [[DST:%.*]]) {
; CHECK-NEXT:    call void @llvm.memset.p0.i32(ptr noundef nonnull align 1 dereferenceable(8) [[DST]], i16 42, i32 8, i1 false)
; CHECK-NEXT:    ret ptr [[DST]]
;
  %call = call ptr @memset(ptr %dst, i32 42, i32 8)
  ret ptr %call
}
