; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -p instcombine -S %s | FileCheck %s

target datalayout = "b:16-p:32:32"

declare ptr @stpcpy(ptr, ptr)

@hello = constant [6 x i16] [i16 104, i16 101, i16 108, i16 108, i16 111, i16 0]

; stpcpy(x, x) -> x + strlen(x)
define ptr @test_1(ptr %str) {
; CHECK-LABEL: define ptr @test_1(
; CHECK-SAME: ptr [[STR:%.*]]) {
; CHECK-NEXT:    [[STRLEN:%.*]] = call i32 @strlen(ptr noundef nonnull dereferenceable(1) [[STR]])
; CHECK-NEXT:    [[CALL:%.*]] = getelementptr inbounds i16, ptr [[STR]], i32 [[STRLEN]]
; CHECK-NEXT:    ret ptr [[CALL]]
;
  %call = call ptr @stpcpy(ptr %str, ptr %str)
  ret ptr %call
}

define ptr @test_2(ptr %dst) {
; CHECK-LABEL: define ptr @test_2(
; CHECK-SAME: ptr [[DST:%.*]]) {
; CHECK-NEXT:    [[CALL:%.*]] = getelementptr inbounds nuw i16, ptr [[DST]], i32 5
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(6) [[DST]], ptr noundef nonnull align 16 dereferenceable(6) @hello, i32 6, i1 false)
; CHECK-NEXT:    ret ptr [[CALL]]
;
  %call = call ptr @stpcpy(ptr %dst, ptr @hello)
  ret ptr %call
}
