; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -p instcombine -S %s | FileCheck %s

target datalayout = "b:16-p:32:32"

declare ptr @__stpcpy_chk(ptr, ptr, i32)

@hello = constant [6 x i16] [i16 104, i16 101, i16 108, i16 108, i16 111, i16 0]

; __stpcpy_chk(str, str, n) -> str + strlen(x)
define ptr @test_1(ptr %str, i32 %n) {
; CHECK-LABEL: define ptr @test_1(
; CHECK-SAME: ptr [[STR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:    [[STRLEN:%.*]] = call i32 @strlen(ptr noundef nonnull dereferenceable(1) [[STR]])
; CHECK-NEXT:    [[CALL:%.*]] = getelementptr inbounds i16, ptr [[STR]], i32 [[STRLEN]]
; CHECK-NEXT:    ret ptr [[CALL]]
;
  %call = call ptr @__stpcpy_chk(ptr %str, ptr %str, i32 %n)
  ret ptr %call
}

; __stpcpy_chk(dst, src, n) -> stpcpy(dst, src)
define ptr @test_2(ptr %dst) {
; CHECK-LABEL: define ptr @test_2(
; CHECK-SAME: ptr [[DST:%.*]]) {
; CHECK-NEXT:    [[STPCPY:%.*]] = getelementptr inbounds nuw i16, ptr [[DST]], i32 5
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(6) [[DST]], ptr noundef nonnull align 16 dereferenceable(6) @hello, i32 6, i1 false)
; CHECK-NEXT:    ret ptr [[STPCPY]]
;
  %call = call ptr @__stpcpy_chk(ptr %dst, ptr @hello, i32 42)
  ret ptr %call
}

; __stpcpy_chk(dst, src, n) -> __memcpy_chk(dst, src, strlen(src), n), dst + strlen(src)
define ptr @test_3(ptr %dst, i32 %n) {
; CHECK-LABEL: define ptr @test_3(
; CHECK-SAME: ptr [[DST:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call ptr @__memcpy_chk(ptr [[DST]], ptr nonnull @hello, i32 6, i32 [[N]])
; CHECK-NEXT:    [[CALL:%.*]] = getelementptr inbounds nuw i16, ptr [[DST]], i32 5
; CHECK-NEXT:    ret ptr [[CALL]]
;
  %call = call ptr @__stpcpy_chk(ptr %dst, ptr @hello, i32 %n)
  ret ptr %call
}
