; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -p instcombine -S %s | FileCheck %s

target datalayout = "b:32-p:32:32"

declare i32 @strncmp(ptr, ptr, i32)

@empty = constant [1 x i32] [i32 0]

; strncmp("", rhs, n) -> sext(rhs[0] != '\0')
define i32 @test_1(ptr %rhs) {
; CHECK-LABEL: define i32 @test_1(
; CHECK-SAME: ptr [[RHS:%.*]]) {
; CHECK-NEXT:    [[STRCMPLOAD:%.*]] = load i32, ptr [[RHS]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ne i32 [[STRCMPLOAD]], 0
; CHECK-NEXT:    [[CALL:%.*]] = sext i1 [[TMP1]] to i32
; CHECK-NEXT:    ret i32 [[CALL]]
;
  %call = call i32 @strncmp(ptr @empty, ptr %rhs, i32 42)
  ret i32 %call
}

; strncmp(lhs, "", n) -> zext(lhs[0] != '\0')
define i32 @test_2(ptr %lhs) {
; CHECK-LABEL: define i32 @test_2(
; CHECK-SAME: ptr [[LHS:%.*]]) {
; CHECK-NEXT:    [[STRCMPLOAD:%.*]] = load i32, ptr [[LHS]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ne i32 [[STRCMPLOAD]], 0
; CHECK-NEXT:    [[CALL:%.*]] = zext i1 [[TMP1]] to i32
; CHECK-NEXT:    ret i32 [[CALL]]
;
  %call = call i32 @strncmp(ptr %lhs, ptr @empty, i32 42)
  ret i32 %call
}
