
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=avr -verify-machineinstrs < %s | FileCheck %s


define void @test_nop() {
; CHECK-LABEL: test_nop:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    nop
; CHECK-NEXT:    ret
  call void @llvm.avr.nop()
  ret void
}


define void @test_sei() {
; CHECK-LABEL: test_sei:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sei
; CHECK-NEXT:    ret
  call void @llvm.avr.sei()
  ret void
}


define void @test_cli() {
; CHECK-LABEL: test_cli:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    cli
; CHECK-NEXT:    ret
  call void @llvm.avr.cli()
  ret void
}


define void @test_sleep() {
; CHECK-LABEL: test_sleep:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sleep
; CHECK-NEXT:    ret
  call void @llvm.avr.sleep()
  ret void
}


define void @test_wdr() {
; CHECK-LABEL: test_wdr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    wdr
; CHECK-NEXT:    ret
  call void @llvm.avr.wdr()
  ret void
}


define i8 @test_swap(i8 %a) {
; CHECK-LABEL: test_swap:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    swap r24
; CHECK-NEXT:    ret
  %1 = call i8 @llvm.avr.swap(i8 %a)
  ret i8 %1
}

declare void @llvm.avr.nop()
declare void @llvm.avr.sei()
declare void @llvm.avr.cli()
declare void @llvm.avr.sleep()
declare void @llvm.avr.wdr()
declare i8 @llvm.avr.swap(i8)
