; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=avr -mcpu=attiny85 < %s | FileCheck %s

; Test mul-by-constant expansion for AVR without hardware multiply.
; attiny85 has no MUL instruction.

define i8 @mul_i8_by_3(i8 %a) nounwind {
; CHECK-LABEL: mul_i8_by_3:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r25, r24
; CHECK-NEXT:    lsl r25
; CHECK-NEXT:    add r24, r25
; CHECK-NEXT:    ret
  %1 = mul i8 %a, 3
  ret i8 %1
}

define i8 @mul_i8_by_5(i8 %a) nounwind {
; CHECK-LABEL: mul_i8_by_5:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r25, r24
; CHECK-NEXT:    lsl r25
; CHECK-NEXT:    lsl r25
; CHECK-NEXT:    add r24, r25
; CHECK-NEXT:    ret
  %1 = mul i8 %a, 5
  ret i8 %1
}

define i8 @mul_i8_by_7(i8 %a) nounwind {
; CHECK-LABEL: mul_i8_by_7:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r25, r24
; CHECK-NEXT:    lsl r25
; CHECK-NEXT:    lsl r25
; CHECK-NEXT:    lsl r25
; CHECK-NEXT:    sub r25, r24
; CHECK-NEXT:    mov r24, r25
; CHECK-NEXT:    ret
  %1 = mul i8 %a, 7
  ret i8 %1
}

define i8 @mul_i8_by_neg3(i8 %a) nounwind {
; CHECK-LABEL: mul_i8_by_neg3:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    mov r25, r24
; CHECK-NEXT:    lsl r25
; CHECK-NEXT:    lsl r25
; CHECK-NEXT:    sub r24, r25
; CHECK-NEXT:    ret
  %1 = mul i8 %a, -3
  ret i8 %1
}

define i16 @mul_i16_by_3(i16 %a) nounwind {
; CHECK-LABEL: mul_i16_by_3:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    movw r18, r24
; CHECK-NEXT:    lsl r18
; CHECK-NEXT:    rol r19
; CHECK-NEXT:    add r24, r18
; CHECK-NEXT:    adc r25, r19
; CHECK-NEXT:    ret
  %1 = mul i16 %a, 3
  ret i16 %1
}

define i16 @mul_i16_by_7(i16 %a) nounwind {
; CHECK-LABEL: mul_i16_by_7:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    movw r18, r24
; CHECK-NEXT:    lsl r18
; CHECK-NEXT:    rol r19
; CHECK-NEXT:    lsl r18
; CHECK-NEXT:    rol r19
; CHECK-NEXT:    lsl r18
; CHECK-NEXT:    rol r19
; CHECK-NEXT:    sub r18, r24
; CHECK-NEXT:    sbc r19, r25
; CHECK-NEXT:    movw r24, r18
; CHECK-NEXT:    ret
  %1 = mul i16 %a, 7
  ret i16 %1
}

define i16 @mul_i16_by_10(i16 %a) nounwind {
; CHECK-LABEL: mul_i16_by_10:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    movw r18, r24
; CHECK-NEXT:    lsl r18
; CHECK-NEXT:    rol r19
; CHECK-NEXT:    lsl r18
; CHECK-NEXT:    rol r19
; CHECK-NEXT:    add r24, r18
; CHECK-NEXT:    adc r25, r19
; CHECK-NEXT:    lsl r24
; CHECK-NEXT:    rol r25
; CHECK-NEXT:    ret
  %1 = mul i16 %a, 10
  ret i16 %1
}

define i16 @mul_i16_by_neg7(i16 %a) nounwind {
; CHECK-LABEL: mul_i16_by_neg7:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    movw r18, r24
; CHECK-NEXT:    lsl r18
; CHECK-NEXT:    rol r19
; CHECK-NEXT:    lsl r18
; CHECK-NEXT:    rol r19
; CHECK-NEXT:    lsl r18
; CHECK-NEXT:    rol r19
; CHECK-NEXT:    sub r24, r18
; CHECK-NEXT:    sbc r25, r19
; CHECK-NEXT:    ret
  %1 = mul i16 %a, -7
  ret i16 %1
}

; Non-constant multiply should still use the libcall.
define i16 @mul_variable(i16 %a, i16 %b) nounwind {
; CHECK-LABEL: mul_variable:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    rcall __mulhi3
; CHECK-NEXT:    ret
  %1 = mul i16 %a, %b
  ret i16 %1
}
