; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=avr | FileCheck %s

declare ptr @bar() addrspace(1)

declare void @baz() addrspace(1)

define void @test0(ptr %arg) addrspace(1) {
; CHECK-LABEL: test0:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    push r14
; CHECK-NEXT:    push r15
; CHECK-NEXT:    push r16
; CHECK-NEXT:    push r17
; CHECK-NEXT:    mov r16, r24
; CHECK-NEXT:    mov r17, r25
; CHECK-NEXT:    rcall bar
; CHECK-NEXT:    mov r14, r24
; CHECK-NEXT:    mov r15, r25
; CHECK-NEXT:    rcall baz
; CHECK-NEXT:    mov r30, r14
; CHECK-NEXT:    mov r31, r15
; CHECK-NEXT:    std Z+1, r1
; CHECK-NEXT:    ldi r24, 0
; CHECK-NEXT:    ldi r25, 0
; CHECK-NEXT:    mov r30, r16
; CHECK-NEXT:    mov r31, r17
; CHECK-NEXT:    std Z+3, r25
; CHECK-NEXT:    std Z+2, r24
; CHECK-NEXT:    mov r18, r30
; CHECK-NEXT:    mov r19, r31
; CHECK-NEXT:    mov r30, r14
; CHECK-NEXT:    mov r31, r15
; CHECK-NEXT:    adiw r30, 2
; CHECK-NEXT:    mov r24, r30
; CHECK-NEXT:    mov r25, r31
; CHECK-NEXT:    mov r30, r18
; CHECK-NEXT:    mov r31, r19
; CHECK-NEXT:    std Z+1, r25
; CHECK-NEXT:    st Z, r24
; CHECK-NEXT:    pop r17
; CHECK-NEXT:    pop r16
; CHECK-NEXT:    pop r15
; CHECK-NEXT:    pop r14
; CHECK-NEXT:    ret
entry:
  %val = call addrspace(1) ptr @bar()
  %gep1 = getelementptr { i8, i8, ptr }, ptr %val, i32 0, i32 1
  %gep2 = getelementptr { i8, i8, ptr }, ptr %val, i32 0, i32 2
  %gep3 = getelementptr { i8, i8, ptr }, ptr %arg, i32 0, i32 2
  call addrspace(1) void @baz()
  store i8 0, ptr %gep1, align 1
  store ptr %gep2, ptr %arg, align 1
  store ptr null, ptr %gep3, align 1
  ret void
}

define void @test1() {
; CHECK-LABEL: test1:
; CHECK:       ; %bb.0: ; %bb0
; CHECK-NEXT:    push r16
; CHECK-NEXT:    push r17
; CHECK-NEXT:    rcall bar
; CHECK-NEXT:    mov r16, r24
; CHECK-NEXT:    mov r17, r25
; CHECK-NEXT:    rcall bar
; CHECK-NEXT:    mov r30, r16
; CHECK-NEXT:    mov r31, r17
; CHECK-NEXT:    mov r18, r24
; CHECK-NEXT:    mov r19, r25
; CHECK-NEXT:    std Z+1, r19
; CHECK-NEXT:    st Z, r18
; CHECK-NEXT:    mov r30, r24
; CHECK-NEXT:    mov r31, r25
; CHECK-NEXT:    std Z+1, r17
; CHECK-NEXT:    st Z, r16
; CHECK-NEXT:    pop r17
; CHECK-NEXT:    pop r16
; CHECK-NEXT:    ret
bb0:
  %1 = call ptr @bar()
  %2 = call ptr @bar()
  store ptr %2, ptr %1
  store ptr %1, ptr %2
  ret void
}
