; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=avr -mcpu=atmega328p | FileCheck %s

; FIXME: crash "Input type needs to be promoted!"
; define i64 @testmsxh_builtin(half %x) {
; entry:
;   %0 = tail call i64 @llvm.llrint.i64.f16(half %x)
;   ret i64 %0
; }

define i64 @testmsxs_builtin(float %x) {
; CHECK-LABEL: testmsxs_builtin:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    call llrintf
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.llrint.i64.f32(float %x)
  ret i64 %0
}

define i64 @testmsxd_builtin(double %x) {
; CHECK-LABEL: testmsxd_builtin:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    call llrint
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.llrint.i64.f64(double %x)
  ret i64 %0
}

; FIXME(#44744): incorrect libcall
define i64 @testmsxq_builtin(fp128 %x) {
; CHECK-LABEL: testmsxq_builtin:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    call llrintl
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.llrint.i64.fp128(fp128 %x)
  ret i64 %0
}

declare i64 @llvm.llrint.i64.f32(float) nounwind readnone
declare i64 @llvm.llrint.i64.f64(double) nounwind readnone
