; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s -mtriple=avr -mcpu=attiny25 | FileCheck %s --check-prefix=SMALL-SP
; RUN: llc < %s -mtriple=avr -mcpu=attiny45 | FileCheck %s --check-prefix=BIG-SP

declare ptr @llvm.returnaddress(i32) nounwind readnone

define ptr @a() {
; SMALL-SP-LABEL: a:
; SMALL-SP:       ; %bb.0:
; SMALL-SP-NEXT:    push r28
; SMALL-SP-NEXT:    push r29
; SMALL-SP-NEXT:    in r28, 61
; SMALL-SP-NEXT:    ldi r29, 0
; SMALL-SP-NEXT:    ldd r24, Y+3
; SMALL-SP-NEXT:    ldd r25, Y+4
; SMALL-SP-NEXT:    pop r29
; SMALL-SP-NEXT:    pop r28
; SMALL-SP-NEXT:    ret
;
; BIG-SP-LABEL: a:
; BIG-SP:       ; %bb.0:
; BIG-SP-NEXT:    push r28
; BIG-SP-NEXT:    push r29
; BIG-SP-NEXT:    in r28, 61
; BIG-SP-NEXT:    in r29, 62
; BIG-SP-NEXT:    ldd r24, Y+3
; BIG-SP-NEXT:    ldd r25, Y+4
; BIG-SP-NEXT:    pop r29
; BIG-SP-NEXT:    pop r28
; BIG-SP-NEXT:    ret
  %1 = call ptr @llvm.returnaddress(i32 0)
  ret ptr %1
}
