; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=riscv32 -mattr=+xqcilia -passes=consthoist -S < %s \
; RUN:   | FileCheck %s --check-prefix=XQCILIA

; A 26-bit constant used several times. RISCVTargetLowering::isLegalAddImmediate
; only accepts 12-bit immediates, so constant hoisting (which queries it via
; getIntImmCostInst) considers the constant expensive and hoists it into a
; register shared by all the adds.
define void @hoist_simm26(i32 %a, i32 %b, i32 %c, ptr %p, ptr %q, ptr %r) {
; XQCILIA-LABEL: define void @hoist_simm26(
; XQCILIA-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[C:%.*]], ptr [[P:%.*]], ptr [[Q:%.*]], ptr [[R:%.*]]) #[[ATTR0:[0-9]+]] {
; XQCILIA-NEXT:    [[CONST:%.*]] = bitcast i32 32766 to i32
; XQCILIA-NEXT:    [[TMP1:%.*]] = add i32 [[A]], [[CONST]]
; XQCILIA-NEXT:    [[TMP2:%.*]] = add i32 [[B]], [[CONST]]
; XQCILIA-NEXT:    [[TMP3:%.*]] = add i32 [[C]], [[CONST]]
; XQCILIA-NEXT:    store i32 [[TMP1]], ptr [[P]], align 4
; XQCILIA-NEXT:    store i32 [[TMP2]], ptr [[Q]], align 4
; XQCILIA-NEXT:    store i32 [[TMP3]], ptr [[R]], align 4
; XQCILIA-NEXT:    ret void
;
  %1 = add i32 %a, 32766
  %2 = add i32 %b, 32766
  %3 = add i32 %c, 32766
  store i32 %1, ptr %p
  store i32 %2, ptr %q
  store i32 %3, ptr %r
  ret void
}
