 ; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-idiom -mtriple=sparc -mattr=+v9,+popc -S < %s | FileCheck %s --check-prefixes=SPARC-CPOP,SPARC32-CPOP
; RUN: opt -passes=loop-idiom -mtriple=sparcv9 -mattr=+popc -S < %s | FileCheck %s --check-prefixes=SPARC-CPOP,SPARC64-CPOP
; RUN: opt -passes=loop-idiom -mtriple=sparc -S < %s | FileCheck %s --check-prefixes=SPARC-NOCPOP,SPARC32-NOCPOP
; RUN: opt -passes=loop-idiom -mtriple=sparcv9 -S < %s | FileCheck %s --check-prefixes=SPARC-NOCPOP,SPARC64-NOCPOP

; Mostly copied from AMDGPU version.

;To recognize this pattern:
;int popcount(unsigned long long a) {
;    int c = 0;
;    while (a) {
;        c++;
;        a &= a - 1;
;    }
;    return c;
;}
;

define i32 @popcount_i64(i64 %a) nounwind uwtable readnone ssp {
; SPARC-CPOP-LABEL: @popcount_i64(
; SPARC-CPOP-NEXT:  entry:
; SPARC-CPOP-NEXT:    [[TMP0:%.*]] = call i64 @llvm.ctpop.i64(i64 [[A:%.*]])
; SPARC-CPOP-NEXT:    [[TMP1:%.*]] = trunc i64 [[TMP0]] to i32
; SPARC-CPOP-NEXT:    [[TOBOOL3:%.*]] = icmp eq i32 [[TMP1]], 0
; SPARC-CPOP-NEXT:    br i1 [[TOBOOL3]], label [[WHILE_END:%.*]], label [[WHILE_BODY_PREHEADER:%.*]]
; SPARC-CPOP:       while.body.preheader:
; SPARC-CPOP-NEXT:    br label [[WHILE_BODY:%.*]]
; SPARC-CPOP:       while.body:
; SPARC-CPOP-NEXT:    [[TCPHI:%.*]] = phi i32 [ [[TMP1]], [[WHILE_BODY_PREHEADER]] ], [ [[TCDEC:%.*]], [[WHILE_BODY]] ]
; SPARC-CPOP-NEXT:    [[C_05:%.*]] = phi i32 [ [[INC:%.*]], [[WHILE_BODY]] ], [ 0, [[WHILE_BODY_PREHEADER]] ]
; SPARC-CPOP-NEXT:    [[A_ADDR_04:%.*]] = phi i64 [ [[AND:%.*]], [[WHILE_BODY]] ], [ [[A]], [[WHILE_BODY_PREHEADER]] ]
; SPARC-CPOP-NEXT:    [[INC]] = add nsw i32 [[C_05]], 1
; SPARC-CPOP-NEXT:    [[SUB:%.*]] = add i64 [[A_ADDR_04]], -1
; SPARC-CPOP-NEXT:    [[AND]] = and i64 [[SUB]], [[A_ADDR_04]]
; SPARC-CPOP-NEXT:    [[TCDEC]] = sub nsw i32 [[TCPHI]], 1
; SPARC-CPOP-NEXT:    [[TOBOOL:%.*]] = icmp sle i32 [[TCDEC]], 0
; SPARC-CPOP-NEXT:    br i1 [[TOBOOL]], label [[WHILE_END_LOOPEXIT:%.*]], label [[WHILE_BODY]]
; SPARC-CPOP:       while.end.loopexit:
; SPARC-CPOP-NEXT:    [[INC_LCSSA:%.*]] = phi i32 [ [[TMP1]], [[WHILE_BODY]] ]
; SPARC-CPOP-NEXT:    br label [[WHILE_END]]
; SPARC-CPOP:       while.end:
; SPARC-CPOP-NEXT:    [[C_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC_LCSSA]], [[WHILE_END_LOOPEXIT]] ]
; SPARC-CPOP-NEXT:    ret i32 [[C_0_LCSSA]]
;
; SPARC-NOCPOP-LABEL: @popcount_i64(
; SPARC-NOCPOP-NEXT:  entry:
; SPARC-NOCPOP-NEXT:    [[TOBOOL3:%.*]] = icmp eq i64 [[A:%.*]], 0
; SPARC-NOCPOP-NEXT:    br i1 [[TOBOOL3]], label [[WHILE_END:%.*]], label [[WHILE_BODY_PREHEADER:%.*]]
; SPARC-NOCPOP:       while.body.preheader:
; SPARC-NOCPOP-NEXT:    br label [[WHILE_BODY:%.*]]
; SPARC-NOCPOP:       while.body:
; SPARC-NOCPOP-NEXT:    [[C_05:%.*]] = phi i32 [ [[INC:%.*]], [[WHILE_BODY]] ], [ 0, [[WHILE_BODY_PREHEADER]] ]
; SPARC-NOCPOP-NEXT:    [[A_ADDR_04:%.*]] = phi i64 [ [[AND:%.*]], [[WHILE_BODY]] ], [ [[A]], [[WHILE_BODY_PREHEADER]] ]
; SPARC-NOCPOP-NEXT:    [[INC]] = add nsw i32 [[C_05]], 1
; SPARC-NOCPOP-NEXT:    [[SUB:%.*]] = add i64 [[A_ADDR_04]], -1
; SPARC-NOCPOP-NEXT:    [[AND]] = and i64 [[SUB]], [[A_ADDR_04]]
; SPARC-NOCPOP-NEXT:    [[TOBOOL:%.*]] = icmp eq i64 [[AND]], 0
; SPARC-NOCPOP-NEXT:    br i1 [[TOBOOL]], label [[WHILE_END_LOOPEXIT:%.*]], label [[WHILE_BODY]]
; SPARC-NOCPOP:       while.end.loopexit:
; SPARC-NOCPOP-NEXT:    [[INC_LCSSA:%.*]] = phi i32 [ [[INC]], [[WHILE_BODY]] ]
; SPARC-NOCPOP-NEXT:    br label [[WHILE_END]]
; SPARC-NOCPOP:       while.end:
; SPARC-NOCPOP-NEXT:    [[C_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC_LCSSA]], [[WHILE_END_LOOPEXIT]] ]
; SPARC-NOCPOP-NEXT:    ret i32 [[C_0_LCSSA]]
;
entry:
  %tobool3 = icmp eq i64 %a, 0
  br i1 %tobool3, label %while.end, label %while.body

while.body:                                       ; preds = %entry, %while.body
  %c.05 = phi i32 [ %inc, %while.body ], [ 0, %entry ]
  %a.addr.04 = phi i64 [ %and, %while.body ], [ %a, %entry ]
  %inc = add nsw i32 %c.05, 1
  %sub = add i64 %a.addr.04, -1
  %and = and i64 %sub, %a.addr.04
  %tobool = icmp eq i64 %and, 0
  br i1 %tobool, label %while.end, label %while.body

while.end:                                        ; preds = %while.body, %entry
  %c.0.lcssa = phi i32 [ 0, %entry ], [ %inc, %while.body ]
  ret i32 %c.0.lcssa
}

define i32 @popcount_i32(i32 %a) nounwind uwtable readnone ssp {
; SPARC-CPOP-LABEL: @popcount_i32(
; SPARC-CPOP-NEXT:  entry:
; SPARC-CPOP-NEXT:    [[A:%.*]] = call i32 @llvm.ctpop.i32(i32 [[A1:%.*]])
; SPARC-CPOP-NEXT:    [[TOBOOL3:%.*]] = icmp eq i32 [[A]], 0
; SPARC-CPOP-NEXT:    br i1 [[TOBOOL3]], label [[WHILE_END:%.*]], label [[WHILE_BODY_PREHEADER:%.*]]
; SPARC-CPOP:       while.body.preheader:
; SPARC-CPOP-NEXT:    br label [[WHILE_BODY:%.*]]
; SPARC-CPOP:       while.body:
; SPARC-CPOP-NEXT:    [[TCPHI:%.*]] = phi i32 [ [[A]], [[WHILE_BODY_PREHEADER]] ], [ [[TCDEC:%.*]], [[WHILE_BODY]] ]
; SPARC-CPOP-NEXT:    [[C_05:%.*]] = phi i32 [ [[INC:%.*]], [[WHILE_BODY]] ], [ 0, [[WHILE_BODY_PREHEADER]] ]
; SPARC-CPOP-NEXT:    [[A_ADDR_04:%.*]] = phi i32 [ [[AND:%.*]], [[WHILE_BODY]] ], [ [[A1]], [[WHILE_BODY_PREHEADER]] ]
; SPARC-CPOP-NEXT:    [[INC]] = add nsw i32 [[C_05]], 1
; SPARC-CPOP-NEXT:    [[SUB:%.*]] = add i32 [[A_ADDR_04]], -1
; SPARC-CPOP-NEXT:    [[AND]] = and i32 [[SUB]], [[A_ADDR_04]]
; SPARC-CPOP-NEXT:    [[TCDEC]] = sub nsw i32 [[TCPHI]], 1
; SPARC-CPOP-NEXT:    [[TOBOOL:%.*]] = icmp sle i32 [[TCDEC]], 0
; SPARC-CPOP-NEXT:    br i1 [[TOBOOL]], label [[WHILE_END_LOOPEXIT:%.*]], label [[WHILE_BODY]]
; SPARC-CPOP:       while.end.loopexit:
; SPARC-CPOP-NEXT:    [[INC_LCSSA:%.*]] = phi i32 [ [[A]], [[WHILE_BODY]] ]
; SPARC-CPOP-NEXT:    br label [[WHILE_END]]
; SPARC-CPOP:       while.end:
; SPARC-CPOP-NEXT:    [[C_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC_LCSSA]], [[WHILE_END_LOOPEXIT]] ]
; SPARC-CPOP-NEXT:    ret i32 [[C_0_LCSSA]]
;
; SPARC-NOCPOP-LABEL: @popcount_i32(
; SPARC-NOCPOP-NEXT:  entry:
; SPARC-NOCPOP-NEXT:    [[TOBOOL3:%.*]] = icmp eq i32 [[A:%.*]], 0
; SPARC-NOCPOP-NEXT:    br i1 [[TOBOOL3]], label [[WHILE_END:%.*]], label [[WHILE_BODY_PREHEADER:%.*]]
; SPARC-NOCPOP:       while.body.preheader:
; SPARC-NOCPOP-NEXT:    br label [[WHILE_BODY:%.*]]
; SPARC-NOCPOP:       while.body:
; SPARC-NOCPOP-NEXT:    [[C_05:%.*]] = phi i32 [ [[INC:%.*]], [[WHILE_BODY]] ], [ 0, [[WHILE_BODY_PREHEADER]] ]
; SPARC-NOCPOP-NEXT:    [[A_ADDR_04:%.*]] = phi i32 [ [[AND:%.*]], [[WHILE_BODY]] ], [ [[A]], [[WHILE_BODY_PREHEADER]] ]
; SPARC-NOCPOP-NEXT:    [[INC]] = add nsw i32 [[C_05]], 1
; SPARC-NOCPOP-NEXT:    [[SUB:%.*]] = add i32 [[A_ADDR_04]], -1
; SPARC-NOCPOP-NEXT:    [[AND]] = and i32 [[SUB]], [[A_ADDR_04]]
; SPARC-NOCPOP-NEXT:    [[TOBOOL:%.*]] = icmp eq i32 [[AND]], 0
; SPARC-NOCPOP-NEXT:    br i1 [[TOBOOL]], label [[WHILE_END_LOOPEXIT:%.*]], label [[WHILE_BODY]]
; SPARC-NOCPOP:       while.end.loopexit:
; SPARC-NOCPOP-NEXT:    [[INC_LCSSA:%.*]] = phi i32 [ [[INC]], [[WHILE_BODY]] ]
; SPARC-NOCPOP-NEXT:    br label [[WHILE_END]]
; SPARC-NOCPOP:       while.end:
; SPARC-NOCPOP-NEXT:    [[C_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC_LCSSA]], [[WHILE_END_LOOPEXIT]] ]
; SPARC-NOCPOP-NEXT:    ret i32 [[C_0_LCSSA]]
;
entry:
  %tobool3 = icmp eq i32 %a, 0
  br i1 %tobool3, label %while.end, label %while.body

while.body:                                       ; preds = %entry, %while.body
  %c.05 = phi i32 [ %inc, %while.body ], [ 0, %entry ]
  %a.addr.04 = phi i32 [ %and, %while.body ], [ %a, %entry ]
  %inc = add nsw i32 %c.05, 1
  %sub = add i32 %a.addr.04, -1
  %and = and i32 %sub, %a.addr.04
  %tobool = icmp eq i32 %and, 0
  br i1 %tobool, label %while.end, label %while.body

while.end:                                        ; preds = %while.body, %entry
  %c.0.lcssa = phi i32 [ 0, %entry ], [ %inc, %while.body ]
  ret i32 %c.0.lcssa
}

define i32 @popcount_i128(i128 %a) nounwind uwtable readnone ssp {
; SPARC-CPOP-LABEL: @popcount_i128(
; SPARC-CPOP-NEXT:  entry:
; SPARC-CPOP-NEXT:    [[TMP0:%.*]] = call i128 @llvm.ctpop.i128(i128 [[A:%.*]])
; SPARC-CPOP-NEXT:    [[TMP1:%.*]] = trunc i128 [[TMP0]] to i32
; SPARC-CPOP-NEXT:    [[TOBOOL3:%.*]] = icmp eq i32 [[TMP1]], 0
; SPARC-CPOP-NEXT:    br i1 [[TOBOOL3]], label [[WHILE_END:%.*]], label [[WHILE_BODY_PREHEADER:%.*]]
; SPARC-CPOP:       while.body.preheader:
; SPARC-CPOP-NEXT:    br label [[WHILE_BODY:%.*]]
; SPARC-CPOP:       while.body:
; SPARC-CPOP-NEXT:    [[TCPHI:%.*]] = phi i32 [ [[TMP1]], [[WHILE_BODY_PREHEADER]] ], [ [[TCDEC:%.*]], [[WHILE_BODY]] ]
; SPARC-CPOP-NEXT:    [[C_05:%.*]] = phi i32 [ [[INC:%.*]], [[WHILE_BODY]] ], [ 0, [[WHILE_BODY_PREHEADER]] ]
; SPARC-CPOP-NEXT:    [[A_ADDR_04:%.*]] = phi i128 [ [[AND:%.*]], [[WHILE_BODY]] ], [ [[A]], [[WHILE_BODY_PREHEADER]] ]
; SPARC-CPOP-NEXT:    [[INC]] = add nsw i32 [[C_05]], 1
; SPARC-CPOP-NEXT:    [[SUB:%.*]] = add i128 [[A_ADDR_04]], -1
; SPARC-CPOP-NEXT:    [[AND]] = and i128 [[SUB]], [[A_ADDR_04]]
; SPARC-CPOP-NEXT:    [[TCDEC]] = sub nsw i32 [[TCPHI]], 1
; SPARC-CPOP-NEXT:    [[TOBOOL:%.*]] = icmp sle i32 [[TCDEC]], 0
; SPARC-CPOP-NEXT:    br i1 [[TOBOOL]], label [[WHILE_END_LOOPEXIT:%.*]], label [[WHILE_BODY]]
; SPARC-CPOP:       while.end.loopexit:
; SPARC-CPOP-NEXT:    [[INC_LCSSA:%.*]] = phi i32 [ [[TMP1]], [[WHILE_BODY]] ]
; SPARC-CPOP-NEXT:    br label [[WHILE_END]]
; SPARC-CPOP:       while.end:
; SPARC-CPOP-NEXT:    [[C_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC_LCSSA]], [[WHILE_END_LOOPEXIT]] ]
; SPARC-CPOP-NEXT:    ret i32 [[C_0_LCSSA]]
;
; SPARC-NOCPOP-LABEL: @popcount_i128(
; SPARC-NOCPOP-NEXT:  entry:
; SPARC-NOCPOP-NEXT:    [[TOBOOL3:%.*]] = icmp eq i128 [[A:%.*]], 0
; SPARC-NOCPOP-NEXT:    br i1 [[TOBOOL3]], label [[WHILE_END:%.*]], label [[WHILE_BODY_PREHEADER:%.*]]
; SPARC-NOCPOP:       while.body.preheader:
; SPARC-NOCPOP-NEXT:    br label [[WHILE_BODY:%.*]]
; SPARC-NOCPOP:       while.body:
; SPARC-NOCPOP-NEXT:    [[C_05:%.*]] = phi i32 [ [[INC:%.*]], [[WHILE_BODY]] ], [ 0, [[WHILE_BODY_PREHEADER]] ]
; SPARC-NOCPOP-NEXT:    [[A_ADDR_04:%.*]] = phi i128 [ [[AND:%.*]], [[WHILE_BODY]] ], [ [[A]], [[WHILE_BODY_PREHEADER]] ]
; SPARC-NOCPOP-NEXT:    [[INC]] = add nsw i32 [[C_05]], 1
; SPARC-NOCPOP-NEXT:    [[SUB:%.*]] = add i128 [[A_ADDR_04]], -1
; SPARC-NOCPOP-NEXT:    [[AND]] = and i128 [[SUB]], [[A_ADDR_04]]
; SPARC-NOCPOP-NEXT:    [[TOBOOL:%.*]] = icmp eq i128 [[AND]], 0
; SPARC-NOCPOP-NEXT:    br i1 [[TOBOOL]], label [[WHILE_END_LOOPEXIT:%.*]], label [[WHILE_BODY]]
; SPARC-NOCPOP:       while.end.loopexit:
; SPARC-NOCPOP-NEXT:    [[INC_LCSSA:%.*]] = phi i32 [ [[INC]], [[WHILE_BODY]] ]
; SPARC-NOCPOP-NEXT:    br label [[WHILE_END]]
; SPARC-NOCPOP:       while.end:
; SPARC-NOCPOP-NEXT:    [[C_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC_LCSSA]], [[WHILE_END_LOOPEXIT]] ]
; SPARC-NOCPOP-NEXT:    ret i32 [[C_0_LCSSA]]
;
entry:
  %tobool3 = icmp eq i128 %a, 0
  br i1 %tobool3, label %while.end, label %while.body

while.body:                                       ; preds = %entry, %while.body
  %c.05 = phi i32 [ %inc, %while.body ], [ 0, %entry ]
  %a.addr.04 = phi i128 [ %and, %while.body ], [ %a, %entry ]
  %inc = add nsw i32 %c.05, 1
  %sub = add i128 %a.addr.04, -1
  %and = and i128 %sub, %a.addr.04
  %tobool = icmp eq i128 %and, 0
  br i1 %tobool, label %while.end, label %while.body

while.end:                                        ; preds = %while.body, %entry
  %c.0.lcssa = phi i32 [ 0, %entry ], [ %inc, %while.body ]
  ret i32 %c.0.lcssa
}

; To recognize this pattern:
;int popcount(unsigned long long a, int mydata1, int mydata2) {
;    int c = 0;
;    while (a) {
;        c++;
;        a &= a - 1;
;        mydata1 *= c;
;        mydata2 *= (int)a;
;    }
;    return c + mydata1 + mydata2;
;}

define i32 @popcount2(i64 %a, i32 %mydata1, i32 %mydata2) nounwind uwtable readnone ssp {
; SPARC-CPOP-LABEL: @popcount2(
; SPARC-CPOP-NEXT:  entry:
; SPARC-CPOP-NEXT:    [[TMP0:%.*]] = call i64 @llvm.ctpop.i64(i64 [[A:%.*]])
; SPARC-CPOP-NEXT:    [[TMP1:%.*]] = trunc i64 [[TMP0]] to i32
; SPARC-CPOP-NEXT:    [[TOBOOL9:%.*]] = icmp eq i32 [[TMP1]], 0
; SPARC-CPOP-NEXT:    br i1 [[TOBOOL9]], label [[WHILE_END:%.*]], label [[WHILE_BODY_PREHEADER:%.*]]
; SPARC-CPOP:       while.body.preheader:
; SPARC-CPOP-NEXT:    br label [[WHILE_BODY:%.*]]
; SPARC-CPOP:       while.body:
; SPARC-CPOP-NEXT:    [[TCPHI:%.*]] = phi i32 [ [[TMP1]], [[WHILE_BODY_PREHEADER]] ], [ [[TCDEC:%.*]], [[WHILE_BODY]] ]
; SPARC-CPOP-NEXT:    [[C_013:%.*]] = phi i32 [ [[INC:%.*]], [[WHILE_BODY]] ], [ 0, [[WHILE_BODY_PREHEADER]] ]
; SPARC-CPOP-NEXT:    [[MYDATA2_ADDR_012:%.*]] = phi i32 [ [[MUL1:%.*]], [[WHILE_BODY]] ], [ [[MYDATA2:%.*]], [[WHILE_BODY_PREHEADER]] ]
; SPARC-CPOP-NEXT:    [[MYDATA1_ADDR_011:%.*]] = phi i32 [ [[MUL:%.*]], [[WHILE_BODY]] ], [ [[MYDATA1:%.*]], [[WHILE_BODY_PREHEADER]] ]
; SPARC-CPOP-NEXT:    [[A_ADDR_010:%.*]] = phi i64 [ [[AND:%.*]], [[WHILE_BODY]] ], [ [[A]], [[WHILE_BODY_PREHEADER]] ]
; SPARC-CPOP-NEXT:    [[INC]] = add nsw i32 [[C_013]], 1
; SPARC-CPOP-NEXT:    [[SUB:%.*]] = add i64 [[A_ADDR_010]], -1
; SPARC-CPOP-NEXT:    [[AND]] = and i64 [[SUB]], [[A_ADDR_010]]
; SPARC-CPOP-NEXT:    [[MUL]] = mul nsw i32 [[INC]], [[MYDATA1_ADDR_011]]
; SPARC-CPOP-NEXT:    [[CONV:%.*]] = trunc i64 [[AND]] to i32
; SPARC-CPOP-NEXT:    [[MUL1]] = mul nsw i32 [[CONV]], [[MYDATA2_ADDR_012]]
; SPARC-CPOP-NEXT:    [[TCDEC]] = sub nsw i32 [[TCPHI]], 1
; SPARC-CPOP-NEXT:    [[TOBOOL:%.*]] = icmp sle i32 [[TCDEC]], 0
; SPARC-CPOP-NEXT:    br i1 [[TOBOOL]], label [[WHILE_END_LOOPEXIT:%.*]], label [[WHILE_BODY]]
; SPARC-CPOP:       while.end.loopexit:
; SPARC-CPOP-NEXT:    [[INC_LCSSA:%.*]] = phi i32 [ [[TMP1]], [[WHILE_BODY]] ]
; SPARC-CPOP-NEXT:    [[MUL_LCSSA:%.*]] = phi i32 [ [[MUL]], [[WHILE_BODY]] ]
; SPARC-CPOP-NEXT:    [[MUL1_LCSSA:%.*]] = phi i32 [ [[MUL1]], [[WHILE_BODY]] ]
; SPARC-CPOP-NEXT:    br label [[WHILE_END]]
; SPARC-CPOP:       while.end:
; SPARC-CPOP-NEXT:    [[C_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC_LCSSA]], [[WHILE_END_LOOPEXIT]] ]
; SPARC-CPOP-NEXT:    [[MYDATA2_ADDR_0_LCSSA:%.*]] = phi i32 [ [[MYDATA2]], [[ENTRY]] ], [ [[MUL1_LCSSA]], [[WHILE_END_LOOPEXIT]] ]
; SPARC-CPOP-NEXT:    [[MYDATA1_ADDR_0_LCSSA:%.*]] = phi i32 [ [[MYDATA1]], [[ENTRY]] ], [ [[MUL_LCSSA]], [[WHILE_END_LOOPEXIT]] ]
; SPARC-CPOP-NEXT:    [[ADD:%.*]] = add i32 [[MYDATA2_ADDR_0_LCSSA]], [[MYDATA1_ADDR_0_LCSSA]]
; SPARC-CPOP-NEXT:    [[ADD2:%.*]] = add i32 [[ADD]], [[C_0_LCSSA]]
; SPARC-CPOP-NEXT:    ret i32 [[ADD2]]
;
; SPARC-NOCPOP-LABEL: @popcount2(
; SPARC-NOCPOP-NEXT:  entry:
; SPARC-NOCPOP-NEXT:    [[TOBOOL9:%.*]] = icmp eq i64 [[A:%.*]], 0
; SPARC-NOCPOP-NEXT:    br i1 [[TOBOOL9]], label [[WHILE_END:%.*]], label [[WHILE_BODY_PREHEADER:%.*]]
; SPARC-NOCPOP:       while.body.preheader:
; SPARC-NOCPOP-NEXT:    br label [[WHILE_BODY:%.*]]
; SPARC-NOCPOP:       while.body:
; SPARC-NOCPOP-NEXT:    [[C_013:%.*]] = phi i32 [ [[INC:%.*]], [[WHILE_BODY]] ], [ 0, [[WHILE_BODY_PREHEADER]] ]
; SPARC-NOCPOP-NEXT:    [[MYDATA2_ADDR_012:%.*]] = phi i32 [ [[MUL1:%.*]], [[WHILE_BODY]] ], [ [[MYDATA2:%.*]], [[WHILE_BODY_PREHEADER]] ]
; SPARC-NOCPOP-NEXT:    [[MYDATA1_ADDR_011:%.*]] = phi i32 [ [[MUL:%.*]], [[WHILE_BODY]] ], [ [[MYDATA1:%.*]], [[WHILE_BODY_PREHEADER]] ]
; SPARC-NOCPOP-NEXT:    [[A_ADDR_010:%.*]] = phi i64 [ [[AND:%.*]], [[WHILE_BODY]] ], [ [[A]], [[WHILE_BODY_PREHEADER]] ]
; SPARC-NOCPOP-NEXT:    [[INC]] = add nsw i32 [[C_013]], 1
; SPARC-NOCPOP-NEXT:    [[SUB:%.*]] = add i64 [[A_ADDR_010]], -1
; SPARC-NOCPOP-NEXT:    [[AND]] = and i64 [[SUB]], [[A_ADDR_010]]
; SPARC-NOCPOP-NEXT:    [[MUL]] = mul nsw i32 [[INC]], [[MYDATA1_ADDR_011]]
; SPARC-NOCPOP-NEXT:    [[CONV:%.*]] = trunc i64 [[AND]] to i32
; SPARC-NOCPOP-NEXT:    [[MUL1]] = mul nsw i32 [[CONV]], [[MYDATA2_ADDR_012]]
; SPARC-NOCPOP-NEXT:    [[TOBOOL:%.*]] = icmp eq i64 [[AND]], 0
; SPARC-NOCPOP-NEXT:    br i1 [[TOBOOL]], label [[WHILE_END_LOOPEXIT:%.*]], label [[WHILE_BODY]]
; SPARC-NOCPOP:       while.end.loopexit:
; SPARC-NOCPOP-NEXT:    [[INC_LCSSA:%.*]] = phi i32 [ [[INC]], [[WHILE_BODY]] ]
; SPARC-NOCPOP-NEXT:    [[MUL_LCSSA:%.*]] = phi i32 [ [[MUL]], [[WHILE_BODY]] ]
; SPARC-NOCPOP-NEXT:    [[MUL1_LCSSA:%.*]] = phi i32 [ [[MUL1]], [[WHILE_BODY]] ]
; SPARC-NOCPOP-NEXT:    br label [[WHILE_END]]
; SPARC-NOCPOP:       while.end:
; SPARC-NOCPOP-NEXT:    [[C_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC_LCSSA]], [[WHILE_END_LOOPEXIT]] ]
; SPARC-NOCPOP-NEXT:    [[MYDATA2_ADDR_0_LCSSA:%.*]] = phi i32 [ [[MYDATA2]], [[ENTRY]] ], [ [[MUL1_LCSSA]], [[WHILE_END_LOOPEXIT]] ]
; SPARC-NOCPOP-NEXT:    [[MYDATA1_ADDR_0_LCSSA:%.*]] = phi i32 [ [[MYDATA1]], [[ENTRY]] ], [ [[MUL_LCSSA]], [[WHILE_END_LOOPEXIT]] ]
; SPARC-NOCPOP-NEXT:    [[ADD:%.*]] = add i32 [[MYDATA2_ADDR_0_LCSSA]], [[MYDATA1_ADDR_0_LCSSA]]
; SPARC-NOCPOP-NEXT:    [[ADD2:%.*]] = add i32 [[ADD]], [[C_0_LCSSA]]
; SPARC-NOCPOP-NEXT:    ret i32 [[ADD2]]
;
entry:
  %tobool9 = icmp eq i64 %a, 0
  br i1 %tobool9, label %while.end, label %while.body

while.body:                                       ; preds = %entry, %while.body
  %c.013 = phi i32 [ %inc, %while.body ], [ 0, %entry ]
  %mydata2.addr.012 = phi i32 [ %mul1, %while.body ], [ %mydata2, %entry ]
  %mydata1.addr.011 = phi i32 [ %mul, %while.body ], [ %mydata1, %entry ]
  %a.addr.010 = phi i64 [ %and, %while.body ], [ %a, %entry ]
  %inc = add nsw i32 %c.013, 1
  %sub = add i64 %a.addr.010, -1
  %and = and i64 %sub, %a.addr.010
  %mul = mul nsw i32 %inc, %mydata1.addr.011
  %conv = trunc i64 %and to i32
  %mul1 = mul nsw i32 %conv, %mydata2.addr.012
  %tobool = icmp eq i64 %and, 0
  br i1 %tobool, label %while.end, label %while.body

while.end:                                        ; preds = %while.body, %entry
  %c.0.lcssa = phi i32 [ 0, %entry ], [ %inc, %while.body ]
  %mydata2.addr.0.lcssa = phi i32 [ %mydata2, %entry ], [ %mul1, %while.body ]
  %mydata1.addr.0.lcssa = phi i32 [ %mydata1, %entry ], [ %mul, %while.body ]
  %add = add i32 %mydata2.addr.0.lcssa, %mydata1.addr.0.lcssa
  %add2 = add i32 %add, %c.0.lcssa
  ret i32 %add2
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; SPARC32-CPOP: {{.*}}
; SPARC32-NOCPOP: {{.*}}
; SPARC64-CPOP: {{.*}}
; SPARC64-NOCPOP: {{.*}}
