; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --filter-out-after "^scalar.ph:" --version 4
; RUN: opt -passes=loop-vectorize -mattr=+lsx -S < %s | FileCheck %s --check-prefixes=CHECK,LSX
; RUN: opt -passes=loop-vectorize -mattr=+lsx --vectorizer-maximize-bandwidth -S < %s | FileCheck %s --check-prefixes=CHECK,LSX-MAXBW
; RUN: opt -passes=loop-vectorize -mattr=+lasx -S < %s | FileCheck %s --check-prefixes=CHECK,LASX
; RUN: opt -passes=loop-vectorize -mattr=+lasx --vectorizer-maximize-bandwidth -S < %s | FileCheck %s --check-prefixes=CHECK,LASX-MAXBW

target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n64-S128"
target triple = "loongarch64"

define i32 @vdot4a(ptr %a, ptr %b) #0 {
; LSX-LABEL: define i32 @vdot4a(
; LSX-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; LSX-NEXT:  entry:
; LSX-NEXT:    br label [[VECTOR_PH:%.*]]
; LSX:       vector.ph:
; LSX-NEXT:    br label [[VECTOR_BODY:%.*]]
; LSX:       vector.body:
; LSX-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LSX-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP10:%.*]], [[VECTOR_BODY]] ]
; LSX-NEXT:    [[VEC_PHI1:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP11:%.*]], [[VECTOR_BODY]] ]
; LSX-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LSX-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 4
; LSX-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[TMP0]], align 1
; LSX-NEXT:    [[WIDE_LOAD2:%.*]] = load <4 x i8>, ptr [[TMP1]], align 1
; LSX-NEXT:    [[TMP2:%.*]] = sext <4 x i8> [[WIDE_LOAD]] to <4 x i32>
; LSX-NEXT:    [[TMP3:%.*]] = sext <4 x i8> [[WIDE_LOAD2]] to <4 x i32>
; LSX-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LSX-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[TMP4]], i64 4
; LSX-NEXT:    [[WIDE_LOAD3:%.*]] = load <4 x i8>, ptr [[TMP4]], align 1
; LSX-NEXT:    [[WIDE_LOAD4:%.*]] = load <4 x i8>, ptr [[TMP5]], align 1
; LSX-NEXT:    [[TMP6:%.*]] = sext <4 x i8> [[WIDE_LOAD3]] to <4 x i32>
; LSX-NEXT:    [[TMP7:%.*]] = sext <4 x i8> [[WIDE_LOAD4]] to <4 x i32>
; LSX-NEXT:    [[TMP8:%.*]] = mul <4 x i32> [[TMP6]], [[TMP2]]
; LSX-NEXT:    [[TMP9:%.*]] = mul <4 x i32> [[TMP7]], [[TMP3]]
; LSX-NEXT:    [[TMP10]] = add <4 x i32> [[TMP8]], [[VEC_PHI]]
; LSX-NEXT:    [[TMP11]] = add <4 x i32> [[TMP9]], [[VEC_PHI1]]
; LSX-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; LSX-NEXT:    [[TMP12:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LSX-NEXT:    br i1 [[TMP12]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; LSX:       middle.block:
; LSX-NEXT:    [[BIN_RDX:%.*]] = add <4 x i32> [[TMP11]], [[TMP10]]
; LSX-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[BIN_RDX]])
; LSX-NEXT:    br label [[FOR_EXIT:%.*]]
; LSX:       for.exit:
; LSX-NEXT:    ret i32 [[TMP13]]
;
; LSX-MAXBW-LABEL: define i32 @vdot4a(
; LSX-MAXBW-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; LSX-MAXBW-NEXT:  entry:
; LSX-MAXBW-NEXT:    br label [[VECTOR_PH:%.*]]
; LSX-MAXBW:       vector.ph:
; LSX-MAXBW-NEXT:    br label [[VECTOR_BODY:%.*]]
; LSX-MAXBW:       vector.body:
; LSX-MAXBW-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LSX-MAXBW-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE:%.*]], [[VECTOR_BODY]] ]
; LSX-MAXBW-NEXT:    [[VEC_PHI1:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE5:%.*]], [[VECTOR_BODY]] ]
; LSX-MAXBW-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LSX-MAXBW-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 16
; LSX-MAXBW-NEXT:    [[WIDE_LOAD:%.*]] = load <16 x i8>, ptr [[TMP0]], align 1
; LSX-MAXBW-NEXT:    [[WIDE_LOAD2:%.*]] = load <16 x i8>, ptr [[TMP1]], align 1
; LSX-MAXBW-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LSX-MAXBW-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP2]], i64 16
; LSX-MAXBW-NEXT:    [[WIDE_LOAD3:%.*]] = load <16 x i8>, ptr [[TMP2]], align 1
; LSX-MAXBW-NEXT:    [[WIDE_LOAD4:%.*]] = load <16 x i8>, ptr [[TMP3]], align 1
; LSX-MAXBW-NEXT:    [[TMP4:%.*]] = sext <16 x i8> [[WIDE_LOAD3]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP5:%.*]] = sext <16 x i8> [[WIDE_LOAD]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP6:%.*]] = mul <16 x i32> [[TMP4]], [[TMP5]]
; LSX-MAXBW-NEXT:    [[PARTIAL_REDUCE]] = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[VEC_PHI]], <16 x i32> [[TMP6]])
; LSX-MAXBW-NEXT:    [[TMP7:%.*]] = sext <16 x i8> [[WIDE_LOAD4]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP8:%.*]] = sext <16 x i8> [[WIDE_LOAD2]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP9:%.*]] = mul <16 x i32> [[TMP7]], [[TMP8]]
; LSX-MAXBW-NEXT:    [[PARTIAL_REDUCE5]] = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[VEC_PHI1]], <16 x i32> [[TMP9]])
; LSX-MAXBW-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 32
; LSX-MAXBW-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LSX-MAXBW-NEXT:    br i1 [[TMP10]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; LSX-MAXBW:       middle.block:
; LSX-MAXBW-NEXT:    [[BIN_RDX:%.*]] = add <4 x i32> [[PARTIAL_REDUCE5]], [[PARTIAL_REDUCE]]
; LSX-MAXBW-NEXT:    [[TMP11:%.*]] = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[BIN_RDX]])
; LSX-MAXBW-NEXT:    br label [[FOR_EXIT:%.*]]
; LSX-MAXBW:       for.exit:
; LSX-MAXBW-NEXT:    ret i32 [[TMP11]]
;
; LASX-LABEL: define i32 @vdot4a(
; LASX-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; LASX-NEXT:  entry:
; LASX-NEXT:    br label [[VECTOR_PH:%.*]]
; LASX:       vector.ph:
; LASX-NEXT:    br label [[VECTOR_BODY:%.*]]
; LASX:       vector.body:
; LASX-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LASX-NEXT:    [[VEC_PHI:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP10:%.*]], [[VECTOR_BODY]] ]
; LASX-NEXT:    [[VEC_PHI1:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP11:%.*]], [[VECTOR_BODY]] ]
; LASX-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LASX-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 8
; LASX-NEXT:    [[WIDE_LOAD:%.*]] = load <8 x i8>, ptr [[TMP0]], align 1
; LASX-NEXT:    [[WIDE_LOAD2:%.*]] = load <8 x i8>, ptr [[TMP1]], align 1
; LASX-NEXT:    [[TMP2:%.*]] = sext <8 x i8> [[WIDE_LOAD]] to <8 x i32>
; LASX-NEXT:    [[TMP3:%.*]] = sext <8 x i8> [[WIDE_LOAD2]] to <8 x i32>
; LASX-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LASX-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[TMP4]], i64 8
; LASX-NEXT:    [[WIDE_LOAD3:%.*]] = load <8 x i8>, ptr [[TMP4]], align 1
; LASX-NEXT:    [[WIDE_LOAD4:%.*]] = load <8 x i8>, ptr [[TMP5]], align 1
; LASX-NEXT:    [[TMP6:%.*]] = sext <8 x i8> [[WIDE_LOAD3]] to <8 x i32>
; LASX-NEXT:    [[TMP7:%.*]] = sext <8 x i8> [[WIDE_LOAD4]] to <8 x i32>
; LASX-NEXT:    [[TMP8:%.*]] = mul <8 x i32> [[TMP6]], [[TMP2]]
; LASX-NEXT:    [[TMP9:%.*]] = mul <8 x i32> [[TMP7]], [[TMP3]]
; LASX-NEXT:    [[TMP10]] = add <8 x i32> [[TMP8]], [[VEC_PHI]]
; LASX-NEXT:    [[TMP11]] = add <8 x i32> [[TMP9]], [[VEC_PHI1]]
; LASX-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 16
; LASX-NEXT:    [[TMP12:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LASX-NEXT:    br i1 [[TMP12]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; LASX:       middle.block:
; LASX-NEXT:    [[BIN_RDX:%.*]] = add <8 x i32> [[TMP11]], [[TMP10]]
; LASX-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX]])
; LASX-NEXT:    br label [[FOR_EXIT:%.*]]
; LASX:       for.exit:
; LASX-NEXT:    ret i32 [[TMP13]]
;
; LASX-MAXBW-LABEL: define i32 @vdot4a(
; LASX-MAXBW-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; LASX-MAXBW-NEXT:  entry:
; LASX-MAXBW-NEXT:    br label [[VECTOR_PH:%.*]]
; LASX-MAXBW:       vector.ph:
; LASX-MAXBW-NEXT:    br label [[VECTOR_BODY:%.*]]
; LASX-MAXBW:       vector.body:
; LASX-MAXBW-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LASX-MAXBW-NEXT:    [[VEC_PHI:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE:%.*]], [[VECTOR_BODY]] ]
; LASX-MAXBW-NEXT:    [[VEC_PHI1:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE5:%.*]], [[VECTOR_BODY]] ]
; LASX-MAXBW-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LASX-MAXBW-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 32
; LASX-MAXBW-NEXT:    [[WIDE_LOAD:%.*]] = load <32 x i8>, ptr [[TMP0]], align 1
; LASX-MAXBW-NEXT:    [[WIDE_LOAD2:%.*]] = load <32 x i8>, ptr [[TMP1]], align 1
; LASX-MAXBW-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LASX-MAXBW-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP2]], i64 32
; LASX-MAXBW-NEXT:    [[WIDE_LOAD3:%.*]] = load <32 x i8>, ptr [[TMP2]], align 1
; LASX-MAXBW-NEXT:    [[WIDE_LOAD4:%.*]] = load <32 x i8>, ptr [[TMP3]], align 1
; LASX-MAXBW-NEXT:    [[TMP4:%.*]] = sext <32 x i8> [[WIDE_LOAD3]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP5:%.*]] = sext <32 x i8> [[WIDE_LOAD]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP6:%.*]] = mul <32 x i32> [[TMP4]], [[TMP5]]
; LASX-MAXBW-NEXT:    [[PARTIAL_REDUCE]] = call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> [[VEC_PHI]], <32 x i32> [[TMP6]])
; LASX-MAXBW-NEXT:    [[TMP7:%.*]] = sext <32 x i8> [[WIDE_LOAD4]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP8:%.*]] = sext <32 x i8> [[WIDE_LOAD2]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP9:%.*]] = mul <32 x i32> [[TMP7]], [[TMP8]]
; LASX-MAXBW-NEXT:    [[PARTIAL_REDUCE5]] = call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> [[VEC_PHI1]], <32 x i32> [[TMP9]])
; LASX-MAXBW-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 64
; LASX-MAXBW-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LASX-MAXBW-NEXT:    br i1 [[TMP10]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; LASX-MAXBW:       middle.block:
; LASX-MAXBW-NEXT:    [[BIN_RDX:%.*]] = add <8 x i32> [[PARTIAL_REDUCE5]], [[PARTIAL_REDUCE]]
; LASX-MAXBW-NEXT:    [[TMP11:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX]])
; LASX-MAXBW-NEXT:    br label [[FOR_EXIT:%.*]]
; LASX-MAXBW:       for.exit:
; LASX-MAXBW-NEXT:    ret i32 [[TMP11]]
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = sext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = sext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}


define i32 @vdot4au(ptr %a, ptr %b) #0 {
; LSX-LABEL: define i32 @vdot4au(
; LSX-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0]] {
; LSX-NEXT:  entry:
; LSX-NEXT:    br label [[VECTOR_PH:%.*]]
; LSX:       vector.ph:
; LSX-NEXT:    br label [[VECTOR_BODY:%.*]]
; LSX:       vector.body:
; LSX-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LSX-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP10:%.*]], [[VECTOR_BODY]] ]
; LSX-NEXT:    [[VEC_PHI1:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP11:%.*]], [[VECTOR_BODY]] ]
; LSX-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LSX-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 4
; LSX-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[TMP0]], align 1
; LSX-NEXT:    [[WIDE_LOAD2:%.*]] = load <4 x i8>, ptr [[TMP1]], align 1
; LSX-NEXT:    [[TMP2:%.*]] = zext <4 x i8> [[WIDE_LOAD]] to <4 x i32>
; LSX-NEXT:    [[TMP3:%.*]] = zext <4 x i8> [[WIDE_LOAD2]] to <4 x i32>
; LSX-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LSX-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[TMP4]], i64 4
; LSX-NEXT:    [[WIDE_LOAD3:%.*]] = load <4 x i8>, ptr [[TMP4]], align 1
; LSX-NEXT:    [[WIDE_LOAD4:%.*]] = load <4 x i8>, ptr [[TMP5]], align 1
; LSX-NEXT:    [[TMP6:%.*]] = zext <4 x i8> [[WIDE_LOAD3]] to <4 x i32>
; LSX-NEXT:    [[TMP7:%.*]] = zext <4 x i8> [[WIDE_LOAD4]] to <4 x i32>
; LSX-NEXT:    [[TMP8:%.*]] = mul <4 x i32> [[TMP6]], [[TMP2]]
; LSX-NEXT:    [[TMP9:%.*]] = mul <4 x i32> [[TMP7]], [[TMP3]]
; LSX-NEXT:    [[TMP10]] = add <4 x i32> [[TMP8]], [[VEC_PHI]]
; LSX-NEXT:    [[TMP11]] = add <4 x i32> [[TMP9]], [[VEC_PHI1]]
; LSX-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; LSX-NEXT:    [[TMP12:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LSX-NEXT:    br i1 [[TMP12]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; LSX:       middle.block:
; LSX-NEXT:    [[BIN_RDX:%.*]] = add <4 x i32> [[TMP11]], [[TMP10]]
; LSX-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[BIN_RDX]])
; LSX-NEXT:    br label [[FOR_EXIT:%.*]]
; LSX:       for.exit:
; LSX-NEXT:    ret i32 [[TMP13]]
;
; LSX-MAXBW-LABEL: define i32 @vdot4au(
; LSX-MAXBW-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0]] {
; LSX-MAXBW-NEXT:  entry:
; LSX-MAXBW-NEXT:    br label [[VECTOR_PH:%.*]]
; LSX-MAXBW:       vector.ph:
; LSX-MAXBW-NEXT:    br label [[VECTOR_BODY:%.*]]
; LSX-MAXBW:       vector.body:
; LSX-MAXBW-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LSX-MAXBW-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE:%.*]], [[VECTOR_BODY]] ]
; LSX-MAXBW-NEXT:    [[VEC_PHI1:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE5:%.*]], [[VECTOR_BODY]] ]
; LSX-MAXBW-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LSX-MAXBW-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 16
; LSX-MAXBW-NEXT:    [[WIDE_LOAD:%.*]] = load <16 x i8>, ptr [[TMP0]], align 1
; LSX-MAXBW-NEXT:    [[WIDE_LOAD2:%.*]] = load <16 x i8>, ptr [[TMP1]], align 1
; LSX-MAXBW-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LSX-MAXBW-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP2]], i64 16
; LSX-MAXBW-NEXT:    [[WIDE_LOAD3:%.*]] = load <16 x i8>, ptr [[TMP2]], align 1
; LSX-MAXBW-NEXT:    [[WIDE_LOAD4:%.*]] = load <16 x i8>, ptr [[TMP3]], align 1
; LSX-MAXBW-NEXT:    [[TMP4:%.*]] = zext <16 x i8> [[WIDE_LOAD3]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP5:%.*]] = zext <16 x i8> [[WIDE_LOAD]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP6:%.*]] = mul <16 x i32> [[TMP4]], [[TMP5]]
; LSX-MAXBW-NEXT:    [[PARTIAL_REDUCE]] = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[VEC_PHI]], <16 x i32> [[TMP6]])
; LSX-MAXBW-NEXT:    [[TMP7:%.*]] = zext <16 x i8> [[WIDE_LOAD4]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP8:%.*]] = zext <16 x i8> [[WIDE_LOAD2]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP9:%.*]] = mul <16 x i32> [[TMP7]], [[TMP8]]
; LSX-MAXBW-NEXT:    [[PARTIAL_REDUCE5]] = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[VEC_PHI1]], <16 x i32> [[TMP9]])
; LSX-MAXBW-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 32
; LSX-MAXBW-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LSX-MAXBW-NEXT:    br i1 [[TMP10]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; LSX-MAXBW:       middle.block:
; LSX-MAXBW-NEXT:    [[BIN_RDX:%.*]] = add <4 x i32> [[PARTIAL_REDUCE5]], [[PARTIAL_REDUCE]]
; LSX-MAXBW-NEXT:    [[TMP11:%.*]] = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[BIN_RDX]])
; LSX-MAXBW-NEXT:    br label [[FOR_EXIT:%.*]]
; LSX-MAXBW:       for.exit:
; LSX-MAXBW-NEXT:    ret i32 [[TMP11]]
;
; LASX-LABEL: define i32 @vdot4au(
; LASX-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0]] {
; LASX-NEXT:  entry:
; LASX-NEXT:    br label [[VECTOR_PH:%.*]]
; LASX:       vector.ph:
; LASX-NEXT:    br label [[VECTOR_BODY:%.*]]
; LASX:       vector.body:
; LASX-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LASX-NEXT:    [[VEC_PHI:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP10:%.*]], [[VECTOR_BODY]] ]
; LASX-NEXT:    [[VEC_PHI1:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP11:%.*]], [[VECTOR_BODY]] ]
; LASX-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LASX-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 8
; LASX-NEXT:    [[WIDE_LOAD:%.*]] = load <8 x i8>, ptr [[TMP0]], align 1
; LASX-NEXT:    [[WIDE_LOAD2:%.*]] = load <8 x i8>, ptr [[TMP1]], align 1
; LASX-NEXT:    [[TMP2:%.*]] = zext <8 x i8> [[WIDE_LOAD]] to <8 x i32>
; LASX-NEXT:    [[TMP3:%.*]] = zext <8 x i8> [[WIDE_LOAD2]] to <8 x i32>
; LASX-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LASX-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[TMP4]], i64 8
; LASX-NEXT:    [[WIDE_LOAD3:%.*]] = load <8 x i8>, ptr [[TMP4]], align 1
; LASX-NEXT:    [[WIDE_LOAD4:%.*]] = load <8 x i8>, ptr [[TMP5]], align 1
; LASX-NEXT:    [[TMP6:%.*]] = zext <8 x i8> [[WIDE_LOAD3]] to <8 x i32>
; LASX-NEXT:    [[TMP7:%.*]] = zext <8 x i8> [[WIDE_LOAD4]] to <8 x i32>
; LASX-NEXT:    [[TMP8:%.*]] = mul <8 x i32> [[TMP6]], [[TMP2]]
; LASX-NEXT:    [[TMP9:%.*]] = mul <8 x i32> [[TMP7]], [[TMP3]]
; LASX-NEXT:    [[TMP10]] = add <8 x i32> [[TMP8]], [[VEC_PHI]]
; LASX-NEXT:    [[TMP11]] = add <8 x i32> [[TMP9]], [[VEC_PHI1]]
; LASX-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 16
; LASX-NEXT:    [[TMP12:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LASX-NEXT:    br i1 [[TMP12]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; LASX:       middle.block:
; LASX-NEXT:    [[BIN_RDX:%.*]] = add <8 x i32> [[TMP11]], [[TMP10]]
; LASX-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX]])
; LASX-NEXT:    br label [[FOR_EXIT:%.*]]
; LASX:       for.exit:
; LASX-NEXT:    ret i32 [[TMP13]]
;
; LASX-MAXBW-LABEL: define i32 @vdot4au(
; LASX-MAXBW-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0]] {
; LASX-MAXBW-NEXT:  entry:
; LASX-MAXBW-NEXT:    br label [[VECTOR_PH:%.*]]
; LASX-MAXBW:       vector.ph:
; LASX-MAXBW-NEXT:    br label [[VECTOR_BODY:%.*]]
; LASX-MAXBW:       vector.body:
; LASX-MAXBW-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LASX-MAXBW-NEXT:    [[VEC_PHI:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE:%.*]], [[VECTOR_BODY]] ]
; LASX-MAXBW-NEXT:    [[VEC_PHI1:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE5:%.*]], [[VECTOR_BODY]] ]
; LASX-MAXBW-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LASX-MAXBW-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 32
; LASX-MAXBW-NEXT:    [[WIDE_LOAD:%.*]] = load <32 x i8>, ptr [[TMP0]], align 1
; LASX-MAXBW-NEXT:    [[WIDE_LOAD2:%.*]] = load <32 x i8>, ptr [[TMP1]], align 1
; LASX-MAXBW-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LASX-MAXBW-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP2]], i64 32
; LASX-MAXBW-NEXT:    [[WIDE_LOAD3:%.*]] = load <32 x i8>, ptr [[TMP2]], align 1
; LASX-MAXBW-NEXT:    [[WIDE_LOAD4:%.*]] = load <32 x i8>, ptr [[TMP3]], align 1
; LASX-MAXBW-NEXT:    [[TMP4:%.*]] = zext <32 x i8> [[WIDE_LOAD3]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP5:%.*]] = zext <32 x i8> [[WIDE_LOAD]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP6:%.*]] = mul <32 x i32> [[TMP4]], [[TMP5]]
; LASX-MAXBW-NEXT:    [[PARTIAL_REDUCE]] = call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> [[VEC_PHI]], <32 x i32> [[TMP6]])
; LASX-MAXBW-NEXT:    [[TMP7:%.*]] = zext <32 x i8> [[WIDE_LOAD4]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP8:%.*]] = zext <32 x i8> [[WIDE_LOAD2]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP9:%.*]] = mul <32 x i32> [[TMP7]], [[TMP8]]
; LASX-MAXBW-NEXT:    [[PARTIAL_REDUCE5]] = call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> [[VEC_PHI1]], <32 x i32> [[TMP9]])
; LASX-MAXBW-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 64
; LASX-MAXBW-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LASX-MAXBW-NEXT:    br i1 [[TMP10]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; LASX-MAXBW:       middle.block:
; LASX-MAXBW-NEXT:    [[BIN_RDX:%.*]] = add <8 x i32> [[PARTIAL_REDUCE5]], [[PARTIAL_REDUCE]]
; LASX-MAXBW-NEXT:    [[TMP11:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX]])
; LASX-MAXBW-NEXT:    br label [[FOR_EXIT:%.*]]
; LASX-MAXBW:       for.exit:
; LASX-MAXBW-NEXT:    ret i32 [[TMP11]]
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = zext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = zext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}


define i32 @vdot4asu(ptr %a, ptr %b) #0 {
; LSX-LABEL: define i32 @vdot4asu(
; LSX-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0]] {
; LSX-NEXT:  entry:
; LSX-NEXT:    br label [[VECTOR_PH:%.*]]
; LSX:       vector.ph:
; LSX-NEXT:    br label [[VECTOR_BODY:%.*]]
; LSX:       vector.body:
; LSX-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LSX-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP10:%.*]], [[VECTOR_BODY]] ]
; LSX-NEXT:    [[VEC_PHI1:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP11:%.*]], [[VECTOR_BODY]] ]
; LSX-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LSX-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 4
; LSX-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[TMP0]], align 1
; LSX-NEXT:    [[WIDE_LOAD2:%.*]] = load <4 x i8>, ptr [[TMP1]], align 1
; LSX-NEXT:    [[TMP2:%.*]] = zext <4 x i8> [[WIDE_LOAD]] to <4 x i32>
; LSX-NEXT:    [[TMP3:%.*]] = zext <4 x i8> [[WIDE_LOAD2]] to <4 x i32>
; LSX-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LSX-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[TMP4]], i64 4
; LSX-NEXT:    [[WIDE_LOAD3:%.*]] = load <4 x i8>, ptr [[TMP4]], align 1
; LSX-NEXT:    [[WIDE_LOAD4:%.*]] = load <4 x i8>, ptr [[TMP5]], align 1
; LSX-NEXT:    [[TMP6:%.*]] = sext <4 x i8> [[WIDE_LOAD3]] to <4 x i32>
; LSX-NEXT:    [[TMP7:%.*]] = sext <4 x i8> [[WIDE_LOAD4]] to <4 x i32>
; LSX-NEXT:    [[TMP8:%.*]] = mul <4 x i32> [[TMP6]], [[TMP2]]
; LSX-NEXT:    [[TMP9:%.*]] = mul <4 x i32> [[TMP7]], [[TMP3]]
; LSX-NEXT:    [[TMP10]] = add <4 x i32> [[TMP8]], [[VEC_PHI]]
; LSX-NEXT:    [[TMP11]] = add <4 x i32> [[TMP9]], [[VEC_PHI1]]
; LSX-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; LSX-NEXT:    [[TMP12:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LSX-NEXT:    br i1 [[TMP12]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; LSX:       middle.block:
; LSX-NEXT:    [[BIN_RDX:%.*]] = add <4 x i32> [[TMP11]], [[TMP10]]
; LSX-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[BIN_RDX]])
; LSX-NEXT:    br label [[FOR_EXIT:%.*]]
; LSX:       for.exit:
; LSX-NEXT:    ret i32 [[TMP13]]
;
; LSX-MAXBW-LABEL: define i32 @vdot4asu(
; LSX-MAXBW-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0]] {
; LSX-MAXBW-NEXT:  entry:
; LSX-MAXBW-NEXT:    br label [[VECTOR_PH:%.*]]
; LSX-MAXBW:       vector.ph:
; LSX-MAXBW-NEXT:    br label [[VECTOR_BODY:%.*]]
; LSX-MAXBW:       vector.body:
; LSX-MAXBW-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LSX-MAXBW-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE:%.*]], [[VECTOR_BODY]] ]
; LSX-MAXBW-NEXT:    [[VEC_PHI1:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE5:%.*]], [[VECTOR_BODY]] ]
; LSX-MAXBW-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LSX-MAXBW-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 16
; LSX-MAXBW-NEXT:    [[WIDE_LOAD:%.*]] = load <16 x i8>, ptr [[TMP0]], align 1
; LSX-MAXBW-NEXT:    [[WIDE_LOAD2:%.*]] = load <16 x i8>, ptr [[TMP1]], align 1
; LSX-MAXBW-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LSX-MAXBW-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP2]], i64 16
; LSX-MAXBW-NEXT:    [[WIDE_LOAD3:%.*]] = load <16 x i8>, ptr [[TMP2]], align 1
; LSX-MAXBW-NEXT:    [[WIDE_LOAD4:%.*]] = load <16 x i8>, ptr [[TMP3]], align 1
; LSX-MAXBW-NEXT:    [[TMP4:%.*]] = sext <16 x i8> [[WIDE_LOAD3]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP5:%.*]] = zext <16 x i8> [[WIDE_LOAD]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP6:%.*]] = mul <16 x i32> [[TMP4]], [[TMP5]]
; LSX-MAXBW-NEXT:    [[PARTIAL_REDUCE]] = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[VEC_PHI]], <16 x i32> [[TMP6]])
; LSX-MAXBW-NEXT:    [[TMP7:%.*]] = sext <16 x i8> [[WIDE_LOAD4]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP8:%.*]] = zext <16 x i8> [[WIDE_LOAD2]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP9:%.*]] = mul <16 x i32> [[TMP7]], [[TMP8]]
; LSX-MAXBW-NEXT:    [[PARTIAL_REDUCE5]] = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[VEC_PHI1]], <16 x i32> [[TMP9]])
; LSX-MAXBW-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 32
; LSX-MAXBW-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LSX-MAXBW-NEXT:    br i1 [[TMP10]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; LSX-MAXBW:       middle.block:
; LSX-MAXBW-NEXT:    [[BIN_RDX:%.*]] = add <4 x i32> [[PARTIAL_REDUCE5]], [[PARTIAL_REDUCE]]
; LSX-MAXBW-NEXT:    [[TMP11:%.*]] = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[BIN_RDX]])
; LSX-MAXBW-NEXT:    br label [[FOR_EXIT:%.*]]
; LSX-MAXBW:       for.exit:
; LSX-MAXBW-NEXT:    ret i32 [[TMP11]]
;
; LASX-LABEL: define i32 @vdot4asu(
; LASX-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0]] {
; LASX-NEXT:  entry:
; LASX-NEXT:    br label [[VECTOR_PH:%.*]]
; LASX:       vector.ph:
; LASX-NEXT:    br label [[VECTOR_BODY:%.*]]
; LASX:       vector.body:
; LASX-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LASX-NEXT:    [[VEC_PHI:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP10:%.*]], [[VECTOR_BODY]] ]
; LASX-NEXT:    [[VEC_PHI1:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP11:%.*]], [[VECTOR_BODY]] ]
; LASX-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LASX-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 8
; LASX-NEXT:    [[WIDE_LOAD:%.*]] = load <8 x i8>, ptr [[TMP0]], align 1
; LASX-NEXT:    [[WIDE_LOAD2:%.*]] = load <8 x i8>, ptr [[TMP1]], align 1
; LASX-NEXT:    [[TMP2:%.*]] = zext <8 x i8> [[WIDE_LOAD]] to <8 x i32>
; LASX-NEXT:    [[TMP3:%.*]] = zext <8 x i8> [[WIDE_LOAD2]] to <8 x i32>
; LASX-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LASX-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[TMP4]], i64 8
; LASX-NEXT:    [[WIDE_LOAD3:%.*]] = load <8 x i8>, ptr [[TMP4]], align 1
; LASX-NEXT:    [[WIDE_LOAD4:%.*]] = load <8 x i8>, ptr [[TMP5]], align 1
; LASX-NEXT:    [[TMP6:%.*]] = sext <8 x i8> [[WIDE_LOAD3]] to <8 x i32>
; LASX-NEXT:    [[TMP7:%.*]] = sext <8 x i8> [[WIDE_LOAD4]] to <8 x i32>
; LASX-NEXT:    [[TMP8:%.*]] = mul <8 x i32> [[TMP6]], [[TMP2]]
; LASX-NEXT:    [[TMP9:%.*]] = mul <8 x i32> [[TMP7]], [[TMP3]]
; LASX-NEXT:    [[TMP10]] = add <8 x i32> [[TMP8]], [[VEC_PHI]]
; LASX-NEXT:    [[TMP11]] = add <8 x i32> [[TMP9]], [[VEC_PHI1]]
; LASX-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 16
; LASX-NEXT:    [[TMP12:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LASX-NEXT:    br i1 [[TMP12]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; LASX:       middle.block:
; LASX-NEXT:    [[BIN_RDX:%.*]] = add <8 x i32> [[TMP11]], [[TMP10]]
; LASX-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX]])
; LASX-NEXT:    br label [[FOR_EXIT:%.*]]
; LASX:       for.exit:
; LASX-NEXT:    ret i32 [[TMP13]]
;
; LASX-MAXBW-LABEL: define i32 @vdot4asu(
; LASX-MAXBW-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0]] {
; LASX-MAXBW-NEXT:  entry:
; LASX-MAXBW-NEXT:    br label [[VECTOR_PH:%.*]]
; LASX-MAXBW:       vector.ph:
; LASX-MAXBW-NEXT:    br label [[VECTOR_BODY:%.*]]
; LASX-MAXBW:       vector.body:
; LASX-MAXBW-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LASX-MAXBW-NEXT:    [[VEC_PHI:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE:%.*]], [[VECTOR_BODY]] ]
; LASX-MAXBW-NEXT:    [[VEC_PHI1:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE5:%.*]], [[VECTOR_BODY]] ]
; LASX-MAXBW-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LASX-MAXBW-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 32
; LASX-MAXBW-NEXT:    [[WIDE_LOAD:%.*]] = load <32 x i8>, ptr [[TMP0]], align 1
; LASX-MAXBW-NEXT:    [[WIDE_LOAD2:%.*]] = load <32 x i8>, ptr [[TMP1]], align 1
; LASX-MAXBW-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LASX-MAXBW-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP2]], i64 32
; LASX-MAXBW-NEXT:    [[WIDE_LOAD3:%.*]] = load <32 x i8>, ptr [[TMP2]], align 1
; LASX-MAXBW-NEXT:    [[WIDE_LOAD4:%.*]] = load <32 x i8>, ptr [[TMP3]], align 1
; LASX-MAXBW-NEXT:    [[TMP4:%.*]] = sext <32 x i8> [[WIDE_LOAD3]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP5:%.*]] = zext <32 x i8> [[WIDE_LOAD]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP6:%.*]] = mul <32 x i32> [[TMP4]], [[TMP5]]
; LASX-MAXBW-NEXT:    [[PARTIAL_REDUCE]] = call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> [[VEC_PHI]], <32 x i32> [[TMP6]])
; LASX-MAXBW-NEXT:    [[TMP7:%.*]] = sext <32 x i8> [[WIDE_LOAD4]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP8:%.*]] = zext <32 x i8> [[WIDE_LOAD2]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP9:%.*]] = mul <32 x i32> [[TMP7]], [[TMP8]]
; LASX-MAXBW-NEXT:    [[PARTIAL_REDUCE5]] = call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> [[VEC_PHI1]], <32 x i32> [[TMP9]])
; LASX-MAXBW-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 64
; LASX-MAXBW-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LASX-MAXBW-NEXT:    br i1 [[TMP10]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; LASX-MAXBW:       middle.block:
; LASX-MAXBW-NEXT:    [[BIN_RDX:%.*]] = add <8 x i32> [[PARTIAL_REDUCE5]], [[PARTIAL_REDUCE]]
; LASX-MAXBW-NEXT:    [[TMP11:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX]])
; LASX-MAXBW-NEXT:    br label [[FOR_EXIT:%.*]]
; LASX-MAXBW:       for.exit:
; LASX-MAXBW-NEXT:    ret i32 [[TMP11]]
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = zext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = sext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}

define i32 @vdot4asu2(ptr %a, ptr %b) #0 {
; LSX-LABEL: define i32 @vdot4asu2(
; LSX-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0]] {
; LSX-NEXT:  entry:
; LSX-NEXT:    br label [[VECTOR_PH:%.*]]
; LSX:       vector.ph:
; LSX-NEXT:    br label [[VECTOR_BODY:%.*]]
; LSX:       vector.body:
; LSX-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LSX-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP10:%.*]], [[VECTOR_BODY]] ]
; LSX-NEXT:    [[VEC_PHI1:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP11:%.*]], [[VECTOR_BODY]] ]
; LSX-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LSX-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 4
; LSX-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[TMP0]], align 1
; LSX-NEXT:    [[WIDE_LOAD2:%.*]] = load <4 x i8>, ptr [[TMP1]], align 1
; LSX-NEXT:    [[TMP2:%.*]] = sext <4 x i8> [[WIDE_LOAD]] to <4 x i32>
; LSX-NEXT:    [[TMP3:%.*]] = sext <4 x i8> [[WIDE_LOAD2]] to <4 x i32>
; LSX-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LSX-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[TMP4]], i64 4
; LSX-NEXT:    [[WIDE_LOAD3:%.*]] = load <4 x i8>, ptr [[TMP4]], align 1
; LSX-NEXT:    [[WIDE_LOAD4:%.*]] = load <4 x i8>, ptr [[TMP5]], align 1
; LSX-NEXT:    [[TMP6:%.*]] = zext <4 x i8> [[WIDE_LOAD3]] to <4 x i32>
; LSX-NEXT:    [[TMP7:%.*]] = zext <4 x i8> [[WIDE_LOAD4]] to <4 x i32>
; LSX-NEXT:    [[TMP8:%.*]] = mul <4 x i32> [[TMP6]], [[TMP2]]
; LSX-NEXT:    [[TMP9:%.*]] = mul <4 x i32> [[TMP7]], [[TMP3]]
; LSX-NEXT:    [[TMP10]] = add <4 x i32> [[TMP8]], [[VEC_PHI]]
; LSX-NEXT:    [[TMP11]] = add <4 x i32> [[TMP9]], [[VEC_PHI1]]
; LSX-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; LSX-NEXT:    [[TMP12:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LSX-NEXT:    br i1 [[TMP12]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; LSX:       middle.block:
; LSX-NEXT:    [[BIN_RDX:%.*]] = add <4 x i32> [[TMP11]], [[TMP10]]
; LSX-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[BIN_RDX]])
; LSX-NEXT:    br label [[FOR_EXIT:%.*]]
; LSX:       for.exit:
; LSX-NEXT:    ret i32 [[TMP13]]
;
; LSX-MAXBW-LABEL: define i32 @vdot4asu2(
; LSX-MAXBW-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0]] {
; LSX-MAXBW-NEXT:  entry:
; LSX-MAXBW-NEXT:    br label [[VECTOR_PH:%.*]]
; LSX-MAXBW:       vector.ph:
; LSX-MAXBW-NEXT:    br label [[VECTOR_BODY:%.*]]
; LSX-MAXBW:       vector.body:
; LSX-MAXBW-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LSX-MAXBW-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE:%.*]], [[VECTOR_BODY]] ]
; LSX-MAXBW-NEXT:    [[VEC_PHI1:%.*]] = phi <4 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE5:%.*]], [[VECTOR_BODY]] ]
; LSX-MAXBW-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LSX-MAXBW-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 16
; LSX-MAXBW-NEXT:    [[WIDE_LOAD:%.*]] = load <16 x i8>, ptr [[TMP0]], align 1
; LSX-MAXBW-NEXT:    [[WIDE_LOAD2:%.*]] = load <16 x i8>, ptr [[TMP1]], align 1
; LSX-MAXBW-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LSX-MAXBW-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP2]], i64 16
; LSX-MAXBW-NEXT:    [[WIDE_LOAD3:%.*]] = load <16 x i8>, ptr [[TMP2]], align 1
; LSX-MAXBW-NEXT:    [[WIDE_LOAD4:%.*]] = load <16 x i8>, ptr [[TMP3]], align 1
; LSX-MAXBW-NEXT:    [[TMP4:%.*]] = zext <16 x i8> [[WIDE_LOAD3]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP5:%.*]] = sext <16 x i8> [[WIDE_LOAD]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP6:%.*]] = mul <16 x i32> [[TMP4]], [[TMP5]]
; LSX-MAXBW-NEXT:    [[PARTIAL_REDUCE]] = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[VEC_PHI]], <16 x i32> [[TMP6]])
; LSX-MAXBW-NEXT:    [[TMP7:%.*]] = zext <16 x i8> [[WIDE_LOAD4]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP8:%.*]] = sext <16 x i8> [[WIDE_LOAD2]] to <16 x i32>
; LSX-MAXBW-NEXT:    [[TMP9:%.*]] = mul <16 x i32> [[TMP7]], [[TMP8]]
; LSX-MAXBW-NEXT:    [[PARTIAL_REDUCE5]] = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[VEC_PHI1]], <16 x i32> [[TMP9]])
; LSX-MAXBW-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 32
; LSX-MAXBW-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LSX-MAXBW-NEXT:    br i1 [[TMP10]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; LSX-MAXBW:       middle.block:
; LSX-MAXBW-NEXT:    [[BIN_RDX:%.*]] = add <4 x i32> [[PARTIAL_REDUCE5]], [[PARTIAL_REDUCE]]
; LSX-MAXBW-NEXT:    [[TMP11:%.*]] = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[BIN_RDX]])
; LSX-MAXBW-NEXT:    br label [[FOR_EXIT:%.*]]
; LSX-MAXBW:       for.exit:
; LSX-MAXBW-NEXT:    ret i32 [[TMP11]]
;
; LASX-LABEL: define i32 @vdot4asu2(
; LASX-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0]] {
; LASX-NEXT:  entry:
; LASX-NEXT:    br label [[VECTOR_PH:%.*]]
; LASX:       vector.ph:
; LASX-NEXT:    br label [[VECTOR_BODY:%.*]]
; LASX:       vector.body:
; LASX-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LASX-NEXT:    [[VEC_PHI:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP10:%.*]], [[VECTOR_BODY]] ]
; LASX-NEXT:    [[VEC_PHI1:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP11:%.*]], [[VECTOR_BODY]] ]
; LASX-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LASX-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 8
; LASX-NEXT:    [[WIDE_LOAD:%.*]] = load <8 x i8>, ptr [[TMP0]], align 1
; LASX-NEXT:    [[WIDE_LOAD2:%.*]] = load <8 x i8>, ptr [[TMP1]], align 1
; LASX-NEXT:    [[TMP2:%.*]] = sext <8 x i8> [[WIDE_LOAD]] to <8 x i32>
; LASX-NEXT:    [[TMP3:%.*]] = sext <8 x i8> [[WIDE_LOAD2]] to <8 x i32>
; LASX-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LASX-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[TMP4]], i64 8
; LASX-NEXT:    [[WIDE_LOAD3:%.*]] = load <8 x i8>, ptr [[TMP4]], align 1
; LASX-NEXT:    [[WIDE_LOAD4:%.*]] = load <8 x i8>, ptr [[TMP5]], align 1
; LASX-NEXT:    [[TMP6:%.*]] = zext <8 x i8> [[WIDE_LOAD3]] to <8 x i32>
; LASX-NEXT:    [[TMP7:%.*]] = zext <8 x i8> [[WIDE_LOAD4]] to <8 x i32>
; LASX-NEXT:    [[TMP8:%.*]] = mul <8 x i32> [[TMP6]], [[TMP2]]
; LASX-NEXT:    [[TMP9:%.*]] = mul <8 x i32> [[TMP7]], [[TMP3]]
; LASX-NEXT:    [[TMP10]] = add <8 x i32> [[TMP8]], [[VEC_PHI]]
; LASX-NEXT:    [[TMP11]] = add <8 x i32> [[TMP9]], [[VEC_PHI1]]
; LASX-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 16
; LASX-NEXT:    [[TMP12:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LASX-NEXT:    br i1 [[TMP12]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; LASX:       middle.block:
; LASX-NEXT:    [[BIN_RDX:%.*]] = add <8 x i32> [[TMP11]], [[TMP10]]
; LASX-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX]])
; LASX-NEXT:    br label [[FOR_EXIT:%.*]]
; LASX:       for.exit:
; LASX-NEXT:    ret i32 [[TMP13]]
;
; LASX-MAXBW-LABEL: define i32 @vdot4asu2(
; LASX-MAXBW-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0]] {
; LASX-MAXBW-NEXT:  entry:
; LASX-MAXBW-NEXT:    br label [[VECTOR_PH:%.*]]
; LASX-MAXBW:       vector.ph:
; LASX-MAXBW-NEXT:    br label [[VECTOR_BODY:%.*]]
; LASX-MAXBW:       vector.body:
; LASX-MAXBW-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; LASX-MAXBW-NEXT:    [[VEC_PHI:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE:%.*]], [[VECTOR_BODY]] ]
; LASX-MAXBW-NEXT:    [[VEC_PHI1:%.*]] = phi <8 x i32> [ zeroinitializer, [[VECTOR_PH]] ], [ [[PARTIAL_REDUCE5:%.*]], [[VECTOR_BODY]] ]
; LASX-MAXBW-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 [[INDEX]]
; LASX-MAXBW-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 32
; LASX-MAXBW-NEXT:    [[WIDE_LOAD:%.*]] = load <32 x i8>, ptr [[TMP0]], align 1
; LASX-MAXBW-NEXT:    [[WIDE_LOAD2:%.*]] = load <32 x i8>, ptr [[TMP1]], align 1
; LASX-MAXBW-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[B]], i64 [[INDEX]]
; LASX-MAXBW-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP2]], i64 32
; LASX-MAXBW-NEXT:    [[WIDE_LOAD3:%.*]] = load <32 x i8>, ptr [[TMP2]], align 1
; LASX-MAXBW-NEXT:    [[WIDE_LOAD4:%.*]] = load <32 x i8>, ptr [[TMP3]], align 1
; LASX-MAXBW-NEXT:    [[TMP4:%.*]] = zext <32 x i8> [[WIDE_LOAD3]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP5:%.*]] = sext <32 x i8> [[WIDE_LOAD]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP6:%.*]] = mul <32 x i32> [[TMP4]], [[TMP5]]
; LASX-MAXBW-NEXT:    [[PARTIAL_REDUCE]] = call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> [[VEC_PHI]], <32 x i32> [[TMP6]])
; LASX-MAXBW-NEXT:    [[TMP7:%.*]] = zext <32 x i8> [[WIDE_LOAD4]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP8:%.*]] = sext <32 x i8> [[WIDE_LOAD2]] to <32 x i32>
; LASX-MAXBW-NEXT:    [[TMP9:%.*]] = mul <32 x i32> [[TMP7]], [[TMP8]]
; LASX-MAXBW-NEXT:    [[PARTIAL_REDUCE5]] = call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> [[VEC_PHI1]], <32 x i32> [[TMP9]])
; LASX-MAXBW-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 64
; LASX-MAXBW-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; LASX-MAXBW-NEXT:    br i1 [[TMP10]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; LASX-MAXBW:       middle.block:
; LASX-MAXBW-NEXT:    [[BIN_RDX:%.*]] = add <8 x i32> [[PARTIAL_REDUCE5]], [[PARTIAL_REDUCE]]
; LASX-MAXBW-NEXT:    [[TMP11:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX]])
; LASX-MAXBW-NEXT:    br label [[FOR_EXIT:%.*]]
; LASX-MAXBW:       for.exit:
; LASX-MAXBW-NEXT:    ret i32 [[TMP11]]
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %accum = phi i32 [ 0, %entry ], [ %add, %for.body ]
  %gep.a = getelementptr i8, ptr %a, i64 %iv
  %load.a = load i8, ptr %gep.a, align 1
  %ext.a = sext i8 %load.a to i32
  %gep.b = getelementptr i8, ptr %b, i64 %iv
  %load.b = load i8, ptr %gep.b, align 1
  %ext.b = zext i8 %load.b to i32
  %mul = mul i32 %ext.b, %ext.a
  %add = add i32 %mul, %accum
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1024
  br i1 %exitcond.not, label %for.exit, label %for.body

for.exit:
  ret i32 %add
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
