; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -mattr=-sign-ext -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s -check-prefixes=CHECK,NO-SIGNEXT
; RUN: llc < %s -O0 --global-isel -mattr=+sign-ext -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s -check-prefixes=CHECK,SIGNEXT

target triple = "wasm32-unknown-unknown"

define zeroext i8 @add_i8_zext(i8 zeroext %x, i8 zeroext %y) {
; CHECK-LABEL: add_i8_zext:
; CHECK:         .functype add_i8_zext (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    i32.add $push1=, $pop4, $pop3
; CHECK-NEXT:    i32.const $push2=, 255
; CHECK-NEXT:    i32.and $push0=, $pop1, $pop2
; CHECK-NEXT:    return $pop0
  %a = add i8 %x, %y
  ret i8 %a
}

define signext i8 @add_i8_sext(i8 signext %x, i8 signext %y) {
; NO-SIGNEXT-LABEL: add_i8_sext:
; NO-SIGNEXT:         .functype add_i8_sext (i32, i32) -> (i32)
; NO-SIGNEXT-NEXT:    .local i32, i32
; NO-SIGNEXT-NEXT:  # %bb.0:
; NO-SIGNEXT-NEXT:    local.get $push4=, 0
; NO-SIGNEXT-NEXT:    local.get $push3=, 1
; NO-SIGNEXT-NEXT:    i32.add $push2=, $pop4, $pop3
; NO-SIGNEXT-NEXT:    local.set 2, $pop2
; NO-SIGNEXT-NEXT:    i32.const $push5=, 24
; NO-SIGNEXT-NEXT:    local.set 3, $pop5
; NO-SIGNEXT-NEXT:    local.get $push7=, 2
; NO-SIGNEXT-NEXT:    local.get $push6=, 3
; NO-SIGNEXT-NEXT:    i32.shl $push1=, $pop7, $pop6
; NO-SIGNEXT-NEXT:    local.get $push8=, 3
; NO-SIGNEXT-NEXT:    i32.shr_s $push0=, $pop1, $pop8
; NO-SIGNEXT-NEXT:    return $pop0
;
; SIGNEXT-LABEL: add_i8_sext:
; SIGNEXT:         .functype add_i8_sext (i32, i32) -> (i32)
; SIGNEXT-NEXT:  # %bb.0:
; SIGNEXT-NEXT:    local.get $push3=, 0
; SIGNEXT-NEXT:    local.get $push2=, 1
; SIGNEXT-NEXT:    i32.add $push1=, $pop3, $pop2
; SIGNEXT-NEXT:    i32.extend8_s $push0=, $pop1
; SIGNEXT-NEXT:    return $pop0
  %a = add i8 %x, %y
  ret i8 %a
}

define i8 @add_i8_aext(i8 %x, i8 %y) {
; CHECK-LABEL: add_i8_aext:
; CHECK:         .functype add_i8_aext (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.add $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = add i8 %x, %y
  ret i8 %a
}

define zeroext i16 @add_i16_zext(i16 zeroext %x, i16 zeroext %y) {
; CHECK-LABEL: add_i16_zext:
; CHECK:         .functype add_i16_zext (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    i32.add $push1=, $pop4, $pop3
; CHECK-NEXT:    i32.const $push2=, 65535
; CHECK-NEXT:    i32.and $push0=, $pop1, $pop2
; CHECK-NEXT:    return $pop0
  %a = add i16 %x, %y
  ret i16 %a
}

define signext i16 @add_i16_sext(i16 signext %x, i16 signext %y) {
; NO-SIGNEXT-LABEL: add_i16_sext:
; NO-SIGNEXT:         .functype add_i16_sext (i32, i32) -> (i32)
; NO-SIGNEXT-NEXT:    .local i32, i32
; NO-SIGNEXT-NEXT:  # %bb.0:
; NO-SIGNEXT-NEXT:    local.get $push4=, 0
; NO-SIGNEXT-NEXT:    local.get $push3=, 1
; NO-SIGNEXT-NEXT:    i32.add $push2=, $pop4, $pop3
; NO-SIGNEXT-NEXT:    local.set 2, $pop2
; NO-SIGNEXT-NEXT:    i32.const $push5=, 16
; NO-SIGNEXT-NEXT:    local.set 3, $pop5
; NO-SIGNEXT-NEXT:    local.get $push7=, 2
; NO-SIGNEXT-NEXT:    local.get $push6=, 3
; NO-SIGNEXT-NEXT:    i32.shl $push1=, $pop7, $pop6
; NO-SIGNEXT-NEXT:    local.get $push8=, 3
; NO-SIGNEXT-NEXT:    i32.shr_s $push0=, $pop1, $pop8
; NO-SIGNEXT-NEXT:    return $pop0
;
; SIGNEXT-LABEL: add_i16_sext:
; SIGNEXT:         .functype add_i16_sext (i32, i32) -> (i32)
; SIGNEXT-NEXT:  # %bb.0:
; SIGNEXT-NEXT:    local.get $push3=, 0
; SIGNEXT-NEXT:    local.get $push2=, 1
; SIGNEXT-NEXT:    i32.add $push1=, $pop3, $pop2
; SIGNEXT-NEXT:    i32.extend16_s $push0=, $pop1
; SIGNEXT-NEXT:    return $pop0
  %a = add i16 %x, %y
  ret i16 %a
}

define i16 @add_i16_aext(i16 %x, i16 %y) {
; CHECK-LABEL: add_i16_aext:
; CHECK:         .functype add_i16_aext (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.add $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = add i16 %x, %y
  ret i16 %a
}

define i32 @add_i32(i32 %x, i32 %y) {
; CHECK-LABEL: add_i32:
; CHECK:         .functype add_i32 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.add $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = add i32 %x, %y
  ret i32 %a
}

define i64 @add_i64(i64 %x, i64 %y) {
; CHECK-LABEL: add_i64:
; CHECK:         .functype add_i64 (i64, i64) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i64.add $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = add i64 %x, %y
  ret i64 %a
}
