; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

define i1 @and_i1(i1 %x, i1 %y) {
; CHECK-LABEL: and_i1:
; CHECK:         .functype and_i1 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.and $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = and i1 %x, %y
  ret i1 %a
}

define i8 @and_i8(i8 %x, i8 %y) {
; CHECK-LABEL: and_i8:
; CHECK:         .functype and_i8 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.and $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = and i8 %x, %y
  ret i8 %a
}

define i16 @and_i16(i16 %x, i16 %y) {
; CHECK-LABEL: and_i16:
; CHECK:         .functype and_i16 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.and $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = and i16 %x, %y
  ret i16 %a
}

define i32 @and_i32(i32 %x, i32 %y) {
; CHECK-LABEL: and_i32:
; CHECK:         .functype and_i32 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.and $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = and i32 %x, %y
  ret i32 %a
}

define i64 @and_i64(i64 %x, i64 %y) {
; CHECK-LABEL: and_i64:
; CHECK:         .functype and_i64 (i64, i64) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i64.and $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = and i64 %x, %y
  ret i64 %a
}
