# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=wasm32-unknown-unknown -run-pass=legalizer,regbankselect,instruction-select %s -o - | FileCheck %s

---
name: ashr_i32_i8
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ashr_i32_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[CONST_I32_:%[0-9]+]]:i32 = CONST_I32 21, implicit-def dead $arguments
    ; CHECK-NEXT: [[SHR_S_I32_:%[0-9]+]]:i32 = SHR_S_I32 [[ARGUMENT_i32_]], [[CONST_I32_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[SHR_S_I32_]], implicit-def $arguments
    %0:i32(i32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(i8) = G_CONSTANT i8 21
    %2:_(i32) = G_ASHR %0, %1
    RETURN %2(i32), implicit-def $arguments
...
---
name: ashrv_i32_i8
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ashrv_i32_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32 = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[CONST_I32_:%[0-9]+]]:i32 = CONST_I32 255, implicit-def dead $arguments
    ; CHECK-NEXT: [[AND_I32_:%[0-9]+]]:i32 = AND_I32 [[ARGUMENT_i32_1]], [[CONST_I32_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[SHR_S_I32_:%[0-9]+]]:i32 = SHR_S_I32 [[ARGUMENT_i32_]], [[AND_I32_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[SHR_S_I32_]], implicit-def $arguments
    %0:i32(i32) = ARGUMENT_i32 0, implicit $arguments
    %2:i32(i32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(i8) = G_TRUNC %2(i32)
    %3:_(i32) = G_ASHR %0, %1
    RETURN %3(i32), implicit-def $arguments
...

---
name: ashr_i64_i8
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ashr_i64_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[CONST_I64_:%[0-9]+]]:i64 = CONST_I64 37, implicit-def dead $arguments
    ; CHECK-NEXT: [[CONST_I64_1:%[0-9]+]]:i64 = CONST_I64 255, implicit-def dead $arguments
    ; CHECK-NEXT: [[AND_I64_:%[0-9]+]]:i64 = AND_I64 [[CONST_I64_]], [[CONST_I64_1]], implicit-def dead $arguments
    ; CHECK-NEXT: [[SHR_S_I64_:%[0-9]+]]:i64 = SHR_S_I64 [[ARGUMENT_i64_]], [[AND_I64_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[SHR_S_I64_]], implicit-def $arguments
    %0:i64(i64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(i8) = G_CONSTANT i8 37
    %2:_(i64) = G_ASHR %0, %1
    RETURN %2(i64), implicit-def $arguments
...
---
name: ashrv_i64_i8
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ashrv_i64_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[I64_EXTEND_U_I32_:%[0-9]+]]:i64 = I64_EXTEND_U_I32 [[ARGUMENT_i32_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[CONST_I64_:%[0-9]+]]:i64 = CONST_I64 255, implicit-def dead $arguments
    ; CHECK-NEXT: [[AND_I64_:%[0-9]+]]:i64 = AND_I64 [[I64_EXTEND_U_I32_]], [[CONST_I64_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[SHR_S_I64_:%[0-9]+]]:i64 = SHR_S_I64 [[ARGUMENT_i64_]], [[AND_I64_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[SHR_S_I64_]], implicit-def $arguments
    %0:i64(i64) = ARGUMENT_i64 0, implicit $arguments
    %2:i32(i32) = ARGUMENT_i32 1, implicit $arguments
    %1:_(i8) = G_TRUNC %2(i32)
    %3:_(i64) = G_ASHR %0, %1
    RETURN %3(i64), implicit-def $arguments
...
