; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

declare i8 @llvm.ctlz.i8(i8, i1)
declare i16 @llvm.ctlz.i16(i16, i1)
declare i32 @llvm.ctlz.i32(i32, i1)
declare i64 @llvm.ctlz.i64(i64, i1)

define i8 @ctlz_i8(i8 %x) {
; CHECK-LABEL: ctlz_i8:
; CHECK:         .functype ctlz_i8 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    i32.const $push4=, 255
; CHECK-NEXT:    i32.and $push0=, $pop5, $pop4
; CHECK-NEXT:    i32.clz $push1=, $pop0
; CHECK-NEXT:    i32.const $push2=, 24
; CHECK-NEXT:    i32.sub $push3=, $pop1, $pop2
; CHECK-NEXT:    return $pop3
  %a = call i8 @llvm.ctlz.i8(i8 %x, i1 false)
  ret i8 %a
}

define i8 @ctlz_zundef_i8(i8 %x) {
; CHECK-LABEL: ctlz_zundef_i8:
; CHECK:         .functype ctlz_zundef_i8 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    i32.const $push4=, 255
; CHECK-NEXT:    i32.and $push0=, $pop5, $pop4
; CHECK-NEXT:    i32.clz $push1=, $pop0
; CHECK-NEXT:    i32.const $push2=, 24
; CHECK-NEXT:    i32.sub $push3=, $pop1, $pop2
; CHECK-NEXT:    return $pop3
  %a = call i8 @llvm.ctlz.i8(i8 %x, i1 true)
  ret i8 %a
}

define i16 @ctlz_i16(i16 %x) {
; CHECK-LABEL: ctlz_i16:
; CHECK:         .functype ctlz_i16 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    i32.const $push4=, 65535
; CHECK-NEXT:    i32.and $push0=, $pop5, $pop4
; CHECK-NEXT:    i32.clz $push1=, $pop0
; CHECK-NEXT:    i32.const $push2=, 16
; CHECK-NEXT:    i32.sub $push3=, $pop1, $pop2
; CHECK-NEXT:    return $pop3
  %a = call i16 @llvm.ctlz.i16(i16 %x, i1 false)
  ret i16 %a
}

define i16 @ctlz_zundef_i16(i16 %x) {
; CHECK-LABEL: ctlz_zundef_i16:
; CHECK:         .functype ctlz_zundef_i16 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    i32.const $push4=, 65535
; CHECK-NEXT:    i32.and $push0=, $pop5, $pop4
; CHECK-NEXT:    i32.clz $push1=, $pop0
; CHECK-NEXT:    i32.const $push2=, 16
; CHECK-NEXT:    i32.sub $push3=, $pop1, $pop2
; CHECK-NEXT:    return $pop3
  %a = call i16 @llvm.ctlz.i16(i16 %x, i1 true)
  ret i16 %a
}

define i32 @ctlz_i32(i32 %x) {
; CHECK-LABEL: ctlz_i32:
; CHECK:         .functype ctlz_i32 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i32.clz $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i32 @llvm.ctlz.i32(i32 %x, i1 false)
  ret i32 %a
}

define i32 @ctlz_zundef_i32(i32 %x) {
; CHECK-LABEL: ctlz_zundef_i32:
; CHECK:         .functype ctlz_zundef_i32 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i32.clz $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i32 @llvm.ctlz.i32(i32 %x, i1 true)
  ret i32 %a
}

define i64 @ctlz_i64(i64 %x) {
; CHECK-LABEL: ctlz_i64:
; CHECK:         .functype ctlz_i64 (i64) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i64.clz $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i64 @llvm.ctlz.i64(i64 %x, i1 false)
  ret i64 %a
}

define i64 @ctlz_zundef_i64(i64 %x) {
; CHECK-LABEL: ctlz_zundef_i64:
; CHECK:         .functype ctlz_zundef_i64 (i64) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i64.clz $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i64 @llvm.ctlz.i64(i64 %x, i1 true)
  ret i64 %a
}
