# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=wasm32-unknown-unknown -run-pass=legalizer,regbankselect,instruction-select %s -o - | FileCheck %s

---
name: ctpop_i32_i8
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ctpop_i32_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[POPCNT_I32_:%[0-9]+]]:i32 = POPCNT_I32 [[ARGUMENT_i32_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[POPCNT_I32_]], implicit-def $arguments
    %0:i32(i32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(i8) = G_CTPOP %0
    %2:_(i32) = G_ANYEXT %1(i8)
    RETURN %2(i32), implicit-def $arguments
...

---
name: ctpop_i64_i8
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ctpop_i64_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[POPCNT_I64_:%[0-9]+]]:i64 = POPCNT_I64 [[ARGUMENT_i64_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[I32_WRAP_I64_:%[0-9]+]]:i32 = I32_WRAP_I64 [[POPCNT_I64_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[I32_WRAP_I64_]], implicit-def $arguments
    %0:i64(i64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(i8) = G_CTPOP %0
    %2:_(i32) = G_ANYEXT %1(i8)
    RETURN %2(i32), implicit-def $arguments
...
---
name: ctpop_i64_i32
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ctpop_i64_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[POPCNT_I64_:%[0-9]+]]:i64 = POPCNT_I64 [[ARGUMENT_i64_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[I32_WRAP_I64_:%[0-9]+]]:i32 = I32_WRAP_I64 [[POPCNT_I64_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[I32_WRAP_I64_]], implicit-def $arguments
    %0:i64(i64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(i32) = G_CTPOP %0
    RETURN %1(i32), implicit-def $arguments
...
