; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

declare i8 @llvm.cttz.i8(i8, i1)
declare i16 @llvm.cttz.i16(i16, i1)
declare i32 @llvm.cttz.i32(i32, i1)
declare i64 @llvm.cttz.i64(i64, i1)

define i8 @cttz_i8(i8 %x) {
; CHECK-LABEL: cttz_i8:
; CHECK:         .functype cttz_i8 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push3=, 0
; CHECK-NEXT:    i32.const $push0=, 256
; CHECK-NEXT:    i32.or $push1=, $pop3, $pop0
; CHECK-NEXT:    i32.ctz $push2=, $pop1
; CHECK-NEXT:    return $pop2
  %a = call i8 @llvm.cttz.i8(i8 %x, i1 false)
  ret i8 %a
}

define i8 @cttz_zundef_i8(i8 %x) {
; CHECK-LABEL: cttz_zundef_i8:
; CHECK:         .functype cttz_zundef_i8 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push3=, 0
; CHECK-NEXT:    i32.const $push0=, 256
; CHECK-NEXT:    i32.or $push1=, $pop3, $pop0
; CHECK-NEXT:    i32.ctz $push2=, $pop1
; CHECK-NEXT:    return $pop2
  %a = call i8 @llvm.cttz.i8(i8 %x, i1 true)
  ret i8 %a
}

define i16 @cttz_i16(i16 %x) {
; CHECK-LABEL: cttz_i16:
; CHECK:         .functype cttz_i16 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push3=, 0
; CHECK-NEXT:    i32.const $push0=, 65536
; CHECK-NEXT:    i32.or $push1=, $pop3, $pop0
; CHECK-NEXT:    i32.ctz $push2=, $pop1
; CHECK-NEXT:    return $pop2
  %a = call i16 @llvm.cttz.i16(i16 %x, i1 false)
  ret i16 %a
}

define i16 @cttz_zundef_i16(i16 %x) {
; CHECK-LABEL: cttz_zundef_i16:
; CHECK:         .functype cttz_zundef_i16 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push3=, 0
; CHECK-NEXT:    i32.const $push0=, 65536
; CHECK-NEXT:    i32.or $push1=, $pop3, $pop0
; CHECK-NEXT:    i32.ctz $push2=, $pop1
; CHECK-NEXT:    return $pop2
  %a = call i16 @llvm.cttz.i16(i16 %x, i1 true)
  ret i16 %a
}

define i32 @cttz_i32(i32 %x) {
; CHECK-LABEL: cttz_i32:
; CHECK:         .functype cttz_i32 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i32.ctz $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i32 @llvm.cttz.i32(i32 %x, i1 false)
  ret i32 %a
}

define i32 @cttz_zundef_i32(i32 %x) {
; CHECK-LABEL: cttz_zundef_i32:
; CHECK:         .functype cttz_zundef_i32 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i32.ctz $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i32 @llvm.cttz.i32(i32 %x, i1 true)
  ret i32 %a
}

define i64 @cttz_i64(i64 %x) {
; CHECK-LABEL: cttz_i64:
; CHECK:         .functype cttz_i64 (i64) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i64.ctz $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i64 @llvm.cttz.i64(i64 %x, i1 false)
  ret i64 %a
}

define i64 @cttz_zundef_i64(i64 %x) {
; CHECK-LABEL: cttz_zundef_i64:
; CHECK:         .functype cttz_zundef_i64 (i64) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i64.ctz $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i64 @llvm.cttz.i64(i64 %x, i1 true)
  ret i64 %a
}
