; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

define float @fadd_f32(float %x, float %y) {
; CHECK-LABEL: fadd_f32:
; CHECK:         .functype fadd_f32 (f32, f32) -> (f32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f32.add $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fadd float %x, %y
  ret float %a
}

define double @fadd_f64(double %x, double %y) {
; CHECK-LABEL: fadd_f64:
; CHECK:         .functype fadd_f64 (f64, f64) -> (f64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f64.add $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fadd double %x, %y
  ret double %a
}
