; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

define i1 @fcmp_false_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_false_f32:
; CHECK:         .functype fcmp_false_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    i32.const $push0=, 0
; CHECK-NEXT:    return $pop0
  %a = fcmp false float %x, %y
  ret i1 %a
}

define i1 @fcmp_oeq_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_oeq_f32:
; CHECK:         .functype fcmp_oeq_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f32.eq $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp oeq float %x, %y
  ret i1 %a
}

define i1 @fcmp_ogt_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_ogt_f32:
; CHECK:         .functype fcmp_ogt_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f32.gt $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp ogt float %x, %y
  ret i1 %a
}

define i1 @fcmp_oge_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_oge_f32:
; CHECK:         .functype fcmp_oge_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f32.ge $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp oge float %x, %y
  ret i1 %a
}

define i1 @fcmp_olt_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_olt_f32:
; CHECK:         .functype fcmp_olt_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f32.lt $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp olt float %x, %y
  ret i1 %a
}

define i1 @fcmp_ole_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_ole_f32:
; CHECK:         .functype fcmp_ole_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f32.le $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp ole float %x, %y
  ret i1 %a
}

define i1 @fcmp_one_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_one_f32:
; CHECK:         .functype fcmp_one_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    f32.lt $push2=, $pop4, $pop3
; CHECK-NEXT:    local.get $push6=, 0
; CHECK-NEXT:    local.get $push5=, 1
; CHECK-NEXT:    f32.gt $push1=, $pop6, $pop5
; CHECK-NEXT:    i32.or $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp one float %x, %y
  ret i1 %a
}

define i1 @fcmp_ord_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_ord_f32:
; CHECK:         .functype fcmp_ord_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 1
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    f32.eq $push2=, $pop4, $pop3
; CHECK-NEXT:    local.get $push6=, 0
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    f32.eq $push1=, $pop6, $pop5
; CHECK-NEXT:    i32.and $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp ord float %x, %y
  ret i1 %a
}

define i1 @fcmp_ueq_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_ueq_f32:
; CHECK:         .functype fcmp_ueq_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push8=, 0
; CHECK-NEXT:    local.get $push7=, 1
; CHECK-NEXT:    f32.lt $push5=, $pop8, $pop7
; CHECK-NEXT:    local.get $push10=, 0
; CHECK-NEXT:    local.get $push9=, 1
; CHECK-NEXT:    f32.gt $push4=, $pop10, $pop9
; CHECK-NEXT:    i32.or $push3=, $pop5, $pop4
; CHECK-NEXT:    i32.const $push2=, 1
; CHECK-NEXT:    i32.xor $push1=, $pop3, $pop2
; CHECK-NEXT:    i32.const $push6=, 1
; CHECK-NEXT:    i32.and $push0=, $pop1, $pop6
; CHECK-NEXT:    return $pop0
  %a = fcmp ueq float %x, %y
  ret i1 %a
}

define i1 @fcmp_ugt_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_ugt_f32:
; CHECK:         .functype fcmp_ugt_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    f32.le $push2=, $pop4, $pop3
; CHECK-NEXT:    i32.const $push1=, 1
; CHECK-NEXT:    i32.xor $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp ugt float %x, %y
  ret i1 %a
}

define i1 @fcmp_uge_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_uge_f32:
; CHECK:         .functype fcmp_uge_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    f32.lt $push2=, $pop4, $pop3
; CHECK-NEXT:    i32.const $push1=, 1
; CHECK-NEXT:    i32.xor $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp uge float %x, %y
  ret i1 %a
}

define i1 @fcmp_ult_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_ult_f32:
; CHECK:         .functype fcmp_ult_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    f32.ge $push2=, $pop4, $pop3
; CHECK-NEXT:    i32.const $push1=, 1
; CHECK-NEXT:    i32.xor $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp ult float %x, %y
  ret i1 %a
}

define i1 @fcmp_ule_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_ule_f32:
; CHECK:         .functype fcmp_ule_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    f32.gt $push2=, $pop4, $pop3
; CHECK-NEXT:    i32.const $push1=, 1
; CHECK-NEXT:    i32.xor $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp ule float %x, %y
  ret i1 %a
}

define i1 @fcmp_une_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_une_f32:
; CHECK:         .functype fcmp_une_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f32.ne $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp une float %x, %y
  ret i1 %a
}

define i1 @fcmp_uno_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_uno_f32:
; CHECK:         .functype fcmp_uno_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 1
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    f32.ne $push2=, $pop4, $pop3
; CHECK-NEXT:    local.get $push6=, 0
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    f32.ne $push1=, $pop6, $pop5
; CHECK-NEXT:    i32.or $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp uno float %x, %y
  ret i1 %a
}

define i1 @fcmp_true_f32(float %x, float %y) {
; CHECK-LABEL: fcmp_true_f32:
; CHECK:         .functype fcmp_true_f32 (f32, f32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    i32.const $push0=, 1
; CHECK-NEXT:    return $pop0
  %a = fcmp true float %x, %y
  ret i1 %a
}

define i1 @fcmp_false_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_false_f64:
; CHECK:         .functype fcmp_false_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    i32.const $push0=, 0
; CHECK-NEXT:    return $pop0
  %a = fcmp false double %x, %y
  ret i1 %a
}

define i1 @fcmp_oeq_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_oeq_f64:
; CHECK:         .functype fcmp_oeq_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f64.eq $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp oeq double %x, %y
  ret i1 %a
}

define i1 @fcmp_ogt_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_ogt_f64:
; CHECK:         .functype fcmp_ogt_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f64.gt $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp ogt double %x, %y
  ret i1 %a
}

define i1 @fcmp_oge_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_oge_f64:
; CHECK:         .functype fcmp_oge_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f64.ge $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp oge double %x, %y
  ret i1 %a
}

define i1 @fcmp_olt_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_olt_f64:
; CHECK:         .functype fcmp_olt_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f64.lt $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp olt double %x, %y
  ret i1 %a
}

define i1 @fcmp_ole_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_ole_f64:
; CHECK:         .functype fcmp_ole_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f64.le $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp ole double %x, %y
  ret i1 %a
}

define i1 @fcmp_one_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_one_f64:
; CHECK:         .functype fcmp_one_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    f64.lt $push2=, $pop4, $pop3
; CHECK-NEXT:    local.get $push6=, 0
; CHECK-NEXT:    local.get $push5=, 1
; CHECK-NEXT:    f64.gt $push1=, $pop6, $pop5
; CHECK-NEXT:    i32.or $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp one double %x, %y
  ret i1 %a
}

define i1 @fcmp_ord_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_ord_f64:
; CHECK:         .functype fcmp_ord_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 1
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    f64.eq $push2=, $pop4, $pop3
; CHECK-NEXT:    local.get $push6=, 0
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    f64.eq $push1=, $pop6, $pop5
; CHECK-NEXT:    i32.and $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp ord double %x, %y
  ret i1 %a
}

define i1 @fcmp_ueq_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_ueq_f64:
; CHECK:         .functype fcmp_ueq_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push8=, 0
; CHECK-NEXT:    local.get $push7=, 1
; CHECK-NEXT:    f64.lt $push5=, $pop8, $pop7
; CHECK-NEXT:    local.get $push10=, 0
; CHECK-NEXT:    local.get $push9=, 1
; CHECK-NEXT:    f64.gt $push4=, $pop10, $pop9
; CHECK-NEXT:    i32.or $push3=, $pop5, $pop4
; CHECK-NEXT:    i32.const $push2=, 1
; CHECK-NEXT:    i32.xor $push1=, $pop3, $pop2
; CHECK-NEXT:    i32.const $push6=, 1
; CHECK-NEXT:    i32.and $push0=, $pop1, $pop6
; CHECK-NEXT:    return $pop0
  %a = fcmp ueq double %x, %y
  ret i1 %a
}

define i1 @fcmp_ugt_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_ugt_f64:
; CHECK:         .functype fcmp_ugt_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    f64.le $push2=, $pop4, $pop3
; CHECK-NEXT:    i32.const $push1=, 1
; CHECK-NEXT:    i32.xor $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp ugt double %x, %y
  ret i1 %a
}

define i1 @fcmp_uge_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_uge_f64:
; CHECK:         .functype fcmp_uge_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    f64.lt $push2=, $pop4, $pop3
; CHECK-NEXT:    i32.const $push1=, 1
; CHECK-NEXT:    i32.xor $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp uge double %x, %y
  ret i1 %a
}

define i1 @fcmp_ult_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_ult_f64:
; CHECK:         .functype fcmp_ult_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    f64.ge $push2=, $pop4, $pop3
; CHECK-NEXT:    i32.const $push1=, 1
; CHECK-NEXT:    i32.xor $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp ult double %x, %y
  ret i1 %a
}

define i1 @fcmp_ule_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_ule_f64:
; CHECK:         .functype fcmp_ule_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    f64.gt $push2=, $pop4, $pop3
; CHECK-NEXT:    i32.const $push1=, 1
; CHECK-NEXT:    i32.xor $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp ule double %x, %y
  ret i1 %a
}

define i1 @fcmp_une_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_une_f64:
; CHECK:         .functype fcmp_une_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f64.ne $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp une double %x, %y
  ret i1 %a
}

define i1 @fcmp_uno_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_uno_f64:
; CHECK:         .functype fcmp_uno_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 1
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    f64.ne $push2=, $pop4, $pop3
; CHECK-NEXT:    local.get $push6=, 0
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    f64.ne $push1=, $pop6, $pop5
; CHECK-NEXT:    i32.or $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = fcmp uno double %x, %y
  ret i1 %a
}

define i1 @fcmp_true_f64(double %x, double %y) {
; CHECK-LABEL: fcmp_true_f64:
; CHECK:         .functype fcmp_true_f64 (f64, f64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    i32.const $push0=, 1
; CHECK-NEXT:    return $pop0
  %a = fcmp true double %x, %y
  ret i1 %a
}
