# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=wasm32-unknown-unknown -run-pass=legalizer,regbankselect,instruction-select %s -o - | FileCheck %s

---
name: fcopysign_f32_from_f64
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: fcopysign_f32_from_f64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_f32_:%[0-9]+]]:f32 = ARGUMENT_f32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_f64_:%[0-9]+]]:f64 = ARGUMENT_f64 1, implicit $arguments
    ; CHECK-NEXT: [[F32_DEMOTE_F64_:%[0-9]+]]:f32 = F32_DEMOTE_F64 [[ARGUMENT_f64_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[COPYSIGN_F32_:%[0-9]+]]:f32 = COPYSIGN_F32 [[ARGUMENT_f32_]], [[F32_DEMOTE_F64_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[COPYSIGN_F32_]], implicit-def $arguments
    %0:f32(f32) = ARGUMENT_f32 0, implicit $arguments
    %1:f64(f64) = ARGUMENT_f64 1, implicit $arguments
    %2:_(f32) = G_FCOPYSIGN %0, %1(f64)
    RETURN %2(f32), implicit-def $arguments
...

---
name: fcopysign_f64_from_f32
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: fcopysign_f64_from_f32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_f64_:%[0-9]+]]:f64 = ARGUMENT_f64 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_f32_:%[0-9]+]]:f32 = ARGUMENT_f32 1, implicit $arguments
    ; CHECK-NEXT: [[F64_PROMOTE_F32_:%[0-9]+]]:f64 = F64_PROMOTE_F32 [[ARGUMENT_f32_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[COPYSIGN_F64_:%[0-9]+]]:f64 = COPYSIGN_F64 [[ARGUMENT_f64_]], [[F64_PROMOTE_F32_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[COPYSIGN_F64_]], implicit-def $arguments
    %0:f64(f64) = ARGUMENT_f64 0, implicit $arguments
    %1:f32(f32) = ARGUMENT_f32 1, implicit $arguments
    %2:_(f64) = G_FCOPYSIGN %0, %1(f32)
    RETURN %2(f64), implicit-def $arguments
...
