; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

declare float @llvm.minnum.f32(float, float)
declare double @llvm.minnum.f64(double, double)

define float @fminnum_f32(float %x, float %y) {
; CHECK-LABEL: fminnum_f32:
; CHECK:         .functype fminnum_f32 (f32, f32) -> (f32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    call $push0=, fminf, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = call float @llvm.minnum.f32(float %x, float %y)
  ret float %a
}

define double @fminnum_f64(double %x, double %y) {
; CHECK-LABEL: fminnum_f64:
; CHECK:         .functype fminnum_f64 (f64, f64) -> (f64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    call $push0=, fmin, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = call double @llvm.minnum.f64(double %x, double %y)
  ret double %a
}

define float @fminnum_f32_nnan(float %x, float %y) {
; CHECK-LABEL: fminnum_f32_nnan:
; CHECK:         .functype fminnum_f32_nnan (f32, f32) -> (f32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f32.min $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = call nnan float @llvm.minnum.f32(float %x, float %y)
  ret float %a
}

define double @fminnum_f64_nnan(double %x, double %y) {
; CHECK-LABEL: fminnum_f64_nnan:
; CHECK:         .functype fminnum_f64_nnan (f64, f64) -> (f64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    f64.min $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = call nnan double @llvm.minnum.f64(double %x, double %y)
  ret double %a
}
