# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=wasm32-unknown-unknown -run-pass=legalizer,regbankselect,instruction-select %s -o - | FileCheck %s

---
name: fneg_f32
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: fneg_f32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_f32_:%[0-9]+]]:f32 = ARGUMENT_f32 0, implicit $arguments
    ; CHECK-NEXT: [[NEG_F32_:%[0-9]+]]:f32 = NEG_F32 [[ARGUMENT_f32_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[NEG_F32_]], implicit-def $arguments
    %0:f32(f32) = ARGUMENT_f32 0, implicit $arguments
    %1:_(f32) = G_FNEG %0
    RETURN %1(f32), implicit-def $arguments
...
---
name: fneg_f64
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: fneg_f64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_f64_:%[0-9]+]]:f64 = ARGUMENT_f64 0, implicit $arguments
    ; CHECK-NEXT: [[NEG_F64_:%[0-9]+]]:f64 = NEG_F64 [[ARGUMENT_f64_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[NEG_F64_]], implicit-def $arguments
    %0:f64(f64) = ARGUMENT_f64 0, implicit $arguments
    %1:_(f64) = G_FNEG %0
    RETURN %1(f64), implicit-def $arguments
...
