# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=wasm32-unknown-unknown -run-pass=legalizer,regbankselect,instruction-select %s -o - | FileCheck %s

---
name: fshl_i32_i8
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: fshl_i32_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32 = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[CONST_I32_:%[0-9]+]]:i32 = CONST_I32 21, implicit-def dead $arguments
    ; CHECK-NEXT: [[CONST_I32_1:%[0-9]+]]:i32 = CONST_I32 11, implicit-def dead $arguments
    ; CHECK-NEXT: [[SHL_I32_:%[0-9]+]]:i32 = SHL_I32 [[ARGUMENT_i32_]], [[CONST_I32_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[SHR_U_I32_:%[0-9]+]]:i32 = SHR_U_I32 [[ARGUMENT_i32_1]], [[CONST_I32_1]], implicit-def dead $arguments
    ; CHECK-NEXT: [[OR_I32_:%[0-9]+]]:i32 = disjoint OR_I32 [[SHL_I32_]], [[SHR_U_I32_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[OR_I32_]], implicit-def $arguments
    %0:i32(i32) = ARGUMENT_i32 0, implicit $arguments
    %1:i32(i32) = ARGUMENT_i32 1, implicit $arguments
    %2:_(i8) = G_CONSTANT i8 21
    %3:_(i32) = G_FSHL %0, %1, %2(i8)
    RETURN %3(i32), implicit-def $arguments
...
---
name: fshlv_i32_i8
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: fshlv_i32_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32 = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_2:%[0-9]+]]:i32 = ARGUMENT_i32 2, implicit $arguments
    ; CHECK-NEXT: [[CONST_I32_:%[0-9]+]]:i32 = CONST_I32 -1, implicit-def dead $arguments
    ; CHECK-NEXT: [[XOR_I32_:%[0-9]+]]:i32 = XOR_I32 [[ARGUMENT_i32_2]], [[CONST_I32_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[CONST_I32_1:%[0-9]+]]:i32 = CONST_I32 1, implicit-def dead $arguments
    ; CHECK-NEXT: [[SHL_I32_:%[0-9]+]]:i32 = SHL_I32 [[ARGUMENT_i32_]], [[ARGUMENT_i32_2]], implicit-def dead $arguments
    ; CHECK-NEXT: [[SHR_U_I32_:%[0-9]+]]:i32 = SHR_U_I32 [[ARGUMENT_i32_1]], [[CONST_I32_1]], implicit-def dead $arguments
    ; CHECK-NEXT: [[SHR_U_I32_1:%[0-9]+]]:i32 = SHR_U_I32 [[SHR_U_I32_]], [[XOR_I32_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[OR_I32_:%[0-9]+]]:i32 = disjoint OR_I32 [[SHL_I32_]], [[SHR_U_I32_1]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[OR_I32_]], implicit-def $arguments
    %0:i32(i32) = ARGUMENT_i32 0, implicit $arguments
    %1:i32(i32) = ARGUMENT_i32 1, implicit $arguments
    %3:i32(i32) = ARGUMENT_i32 2, implicit $arguments
    %2:_(i8) = G_TRUNC %3(i32)
    %4:_(i32) = G_FSHL %0, %1, %2(i8)
    RETURN %4(i32), implicit-def $arguments
...


---
name: fshl_i64_i8
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: fshl_i64_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i64_1:%[0-9]+]]:i64 = ARGUMENT_i64 1, implicit $arguments
    ; CHECK-NEXT: [[CONST_I64_:%[0-9]+]]:i64 = CONST_I64 21, implicit-def dead $arguments
    ; CHECK-NEXT: [[CONST_I64_1:%[0-9]+]]:i64 = CONST_I64 255, implicit-def dead $arguments
    ; CHECK-NEXT: [[AND_I64_:%[0-9]+]]:i64 = AND_I64 [[CONST_I64_]], [[CONST_I64_1]], implicit-def dead $arguments
    ; CHECK-NEXT: [[SHL_I64_:%[0-9]+]]:i64 = SHL_I64 [[ARGUMENT_i64_]], [[AND_I64_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[CONST_I64_2:%[0-9]+]]:i64 = CONST_I64 43, implicit-def dead $arguments
    ; CHECK-NEXT: [[CONST_I64_3:%[0-9]+]]:i64 = CONST_I64 255, implicit-def dead $arguments
    ; CHECK-NEXT: [[AND_I64_1:%[0-9]+]]:i64 = AND_I64 [[CONST_I64_2]], [[CONST_I64_3]], implicit-def dead $arguments
    ; CHECK-NEXT: [[SHR_U_I64_:%[0-9]+]]:i64 = SHR_U_I64 [[ARGUMENT_i64_1]], [[AND_I64_1]], implicit-def dead $arguments
    ; CHECK-NEXT: [[OR_I64_:%[0-9]+]]:i64 = disjoint OR_I64 [[SHL_I64_]], [[SHR_U_I64_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[OR_I64_]], implicit-def $arguments
    %0:i64(i64) = ARGUMENT_i64 0, implicit $arguments
    %1:i64(i64) = ARGUMENT_i64 1, implicit $arguments
    %2:_(i8) = G_CONSTANT i8 21
    %3:_(i64) = G_FSHL %0, %1, %2(i8)
    RETURN %3(i64), implicit-def $arguments
...
---
name: fshlv_i64_i8
tracksRegLiveness: true
body: |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: fshlv_i64_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i64_1:%[0-9]+]]:i64 = ARGUMENT_i64 1, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 2, implicit $arguments
    ; CHECK-NEXT: [[CONST_I32_:%[0-9]+]]:i32 = CONST_I32 63, implicit-def dead $arguments
    ; CHECK-NEXT: [[AND_I32_:%[0-9]+]]:i32 = AND_I32 [[ARGUMENT_i32_]], [[CONST_I32_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[CONST_I32_1:%[0-9]+]]:i32 = CONST_I32 -1, implicit-def dead $arguments
    ; CHECK-NEXT: [[XOR_I32_:%[0-9]+]]:i32 = XOR_I32 [[ARGUMENT_i32_]], [[CONST_I32_1]], implicit-def dead $arguments
    ; CHECK-NEXT: [[AND_I32_1:%[0-9]+]]:i32 = AND_I32 [[XOR_I32_]], [[CONST_I32_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[I64_EXTEND_U_I32_:%[0-9]+]]:i64 = I64_EXTEND_U_I32 [[AND_I32_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[CONST_I64_:%[0-9]+]]:i64 = CONST_I64 255, implicit-def dead $arguments
    ; CHECK-NEXT: [[AND_I64_:%[0-9]+]]:i64 = AND_I64 [[I64_EXTEND_U_I32_]], [[CONST_I64_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[SHL_I64_:%[0-9]+]]:i64 = SHL_I64 [[ARGUMENT_i64_]], [[AND_I64_]], implicit-def dead $arguments
    ; CHECK-NEXT: [[CONST_I64_1:%[0-9]+]]:i64 = CONST_I64 1, implicit-def dead $arguments
    ; CHECK-NEXT: [[CONST_I64_2:%[0-9]+]]:i64 = CONST_I64 255, implicit-def dead $arguments
    ; CHECK-NEXT: [[AND_I64_1:%[0-9]+]]:i64 = AND_I64 [[CONST_I64_1]], [[CONST_I64_2]], implicit-def dead $arguments
    ; CHECK-NEXT: [[SHR_U_I64_:%[0-9]+]]:i64 = SHR_U_I64 [[ARGUMENT_i64_1]], [[AND_I64_1]], implicit-def dead $arguments
    ; CHECK-NEXT: [[I64_EXTEND_U_I32_1:%[0-9]+]]:i64 = I64_EXTEND_U_I32 [[AND_I32_1]], implicit-def dead $arguments
    ; CHECK-NEXT: [[CONST_I64_3:%[0-9]+]]:i64 = CONST_I64 255, implicit-def dead $arguments
    ; CHECK-NEXT: [[AND_I64_2:%[0-9]+]]:i64 = AND_I64 [[I64_EXTEND_U_I32_1]], [[CONST_I64_3]], implicit-def dead $arguments
    ; CHECK-NEXT: [[SHR_U_I64_1:%[0-9]+]]:i64 = SHR_U_I64 [[SHR_U_I64_]], [[AND_I64_2]], implicit-def dead $arguments
    ; CHECK-NEXT: [[OR_I64_:%[0-9]+]]:i64 = disjoint OR_I64 [[SHL_I64_]], [[SHR_U_I64_1]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[OR_I64_]], implicit-def $arguments
    %0:i64(i64) = ARGUMENT_i64 0, implicit $arguments
    %1:i64(i64) = ARGUMENT_i64 1, implicit $arguments
    %3:i32(i32) = ARGUMENT_i32 2, implicit $arguments
    %2:_(i8) = G_TRUNC %3(i32)
    %4:_(i64) = G_FSHL %0, %1, %2(i8)
    RETURN %4(i64), implicit-def $arguments
...
