# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=wasm32-unknown-unknown -run-pass=legalizer,regbankselect,instruction-select %s -o - | FileCheck %s

---
name:            implicit_def_i8
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: implicit_def_i8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:i32 = IMPLICIT_DEF
    ; CHECK-NEXT: RETURN [[DEF]], implicit-def $arguments
    %0:_(i8) = G_IMPLICIT_DEF
    %1:_(i32) = G_ANYEXT %0(i8)
    RETURN %1(i32), implicit-def $arguments
...

---
name:            implicit_def_i16
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: implicit_def_i16
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:i32 = IMPLICIT_DEF
    ; CHECK-NEXT: RETURN [[DEF]], implicit-def $arguments
    %0:_(i16) = G_IMPLICIT_DEF
    %1:_(i32) = G_ANYEXT %0(i16)
    RETURN %1(i32), implicit-def $arguments
...

---
name:            implicit_def_i32
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: implicit_def_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:i32 = IMPLICIT_DEF
    ; CHECK-NEXT: RETURN [[DEF]], implicit-def $arguments
    %0:_(i32) = G_IMPLICIT_DEF
    RETURN %0(i32), implicit-def $arguments
...

---
name:            implicit_def_i64
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: implicit_def_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:i64 = IMPLICIT_DEF
    ; CHECK-NEXT: RETURN [[DEF]], implicit-def $arguments
    %0:_(i64) = G_IMPLICIT_DEF
    RETURN %0(i64), implicit-def $arguments
...
