; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

declare i1 @llvm.is.fpclass.f32(float, i32)
declare i1 @llvm.is.fpclass.f64(double, i32)

define i1 @is_fpclass_f32_snan(float %x) {
; CHECK-LABEL: is_fpclass_f32_snan:
; CHECK:         .functype is_fpclass_f32_snan (f32) -> (i32)
; CHECK-NEXT:    .local i32, i32, i32, i32, i32, i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    i32.reinterpret_f32 $push4=, $pop5
; CHECK-NEXT:    local.set 1, $pop4
; CHECK-NEXT:    i32.const $push6=, 2147483647
; CHECK-NEXT:    local.set 2, $pop6
; CHECK-NEXT:    i32.const $push7=, 2139095040
; CHECK-NEXT:    local.set 3, $pop7
; CHECK-NEXT:    local.get $push10=, 1
; CHECK-NEXT:    local.get $push9=, 2
; CHECK-NEXT:    i32.and $push8=, $pop10, $pop9
; CHECK-NEXT:    local.set 4, $pop8
; CHECK-NEXT:    i32.const $push11=, 0
; CHECK-NEXT:    local.set 5, $pop11
; CHECK-NEXT:    i32.const $push12=, 2143289344
; CHECK-NEXT:    local.set 6, $pop12
; CHECK-NEXT:    local.get $push17=, 5
; CHECK-NEXT:    local.get $push14=, 4
; CHECK-NEXT:    local.get $push13=, 3
; CHECK-NEXT:    i32.gt_u $push0=, $pop14, $pop13
; CHECK-NEXT:    local.get $push16=, 4
; CHECK-NEXT:    local.get $push15=, 6
; CHECK-NEXT:    i32.lt_u $push1=, $pop16, $pop15
; CHECK-NEXT:    i32.and $push2=, $pop0, $pop1
; CHECK-NEXT:    i32.or $push3=, $pop17, $pop2
; CHECK-NEXT:    return $pop3
  %a = call i1 @llvm.is.fpclass.f32(float %x, i32 1)
  ret i1 %a
}

define i1 @is_fpclass_f32_qnan(float %x) {
; CHECK-LABEL: is_fpclass_f32_qnan:
; CHECK:         .functype is_fpclass_f32_qnan (f32) -> (i32)
; CHECK-NEXT:    .local i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push6=, 0
; CHECK-NEXT:    i32.reinterpret_f32 $push0=, $pop6
; CHECK-NEXT:    i32.const $push1=, 2147483647
; CHECK-NEXT:    i32.and $push7=, $pop0, $pop1
; CHECK-NEXT:    local.set 1, $pop7
; CHECK-NEXT:    i32.const $push2=, 0
; CHECK-NEXT:    local.get $push8=, 1
; CHECK-NEXT:    i32.const $push3=, 2143289344
; CHECK-NEXT:    i32.ge_u $push4=, $pop8, $pop3
; CHECK-NEXT:    i32.or $push5=, $pop2, $pop4
; CHECK-NEXT:    return $pop5
  %a = call i1 @llvm.is.fpclass.f32(float %x, i32 2)
  ret i1 %a
}

define i1 @is_fpclass_f32_neginf(float %x) {
; CHECK-LABEL: is_fpclass_f32_neginf:
; CHECK:         .functype is_fpclass_f32_neginf (f32) -> (i32)
; CHECK-NEXT:    .local i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    i32.reinterpret_f32 $push4=, $pop5
; CHECK-NEXT:    local.set 1, $pop4
; CHECK-NEXT:    i32.const $push0=, 0
; CHECK-NEXT:    local.get $push6=, 1
; CHECK-NEXT:    i32.const $push1=, -8388608
; CHECK-NEXT:    i32.eq $push2=, $pop6, $pop1
; CHECK-NEXT:    i32.or $push3=, $pop0, $pop2
; CHECK-NEXT:    return $pop3
  %a = call i1 @llvm.is.fpclass.f32(float %x, i32 4)
  ret i1 %a
}

define i1 @is_fpclass_f32_negnormal(float %x) {
; CHECK-LABEL: is_fpclass_f32_negnormal:
; CHECK:         .functype is_fpclass_f32_negnormal (f32) -> (i32)
; CHECK-NEXT:    .local i32, i32, i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push9=, 0
; CHECK-NEXT:    i32.reinterpret_f32 $push8=, $pop9
; CHECK-NEXT:    local.set 1, $pop8
; CHECK-NEXT:    local.get $push11=, 1
; CHECK-NEXT:    i32.const $push0=, 2147483647
; CHECK-NEXT:    i32.and $push10=, $pop11, $pop0
; CHECK-NEXT:    local.set 2, $pop10
; CHECK-NEXT:    local.get $push14=, 1
; CHECK-NEXT:    local.get $push13=, 2
; CHECK-NEXT:    i32.ne $push12=, $pop14, $pop13
; CHECK-NEXT:    local.set 3, $pop12
; CHECK-NEXT:    i32.const $push1=, 0
; CHECK-NEXT:    local.get $push16=, 3
; CHECK-NEXT:    local.get $push15=, 2
; CHECK-NEXT:    i32.const $push2=, 8388608
; CHECK-NEXT:    i32.sub $push3=, $pop15, $pop2
; CHECK-NEXT:    i32.const $push4=, 2130706432
; CHECK-NEXT:    i32.lt_u $push5=, $pop3, $pop4
; CHECK-NEXT:    i32.and $push6=, $pop16, $pop5
; CHECK-NEXT:    i32.or $push7=, $pop1, $pop6
; CHECK-NEXT:    return $pop7
  %a = call i1 @llvm.is.fpclass.f32(float %x, i32 8)
  ret i1 %a
}

define i1 @is_fpclass_f32_negsubnorm(float %x) {
; CHECK-LABEL: is_fpclass_f32_negsubnorm:
; CHECK:         .functype is_fpclass_f32_negsubnorm (f32) -> (i32)
; CHECK-NEXT:    .local i32, i32, i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push9=, 0
; CHECK-NEXT:    i32.reinterpret_f32 $push8=, $pop9
; CHECK-NEXT:    local.set 1, $pop8
; CHECK-NEXT:    local.get $push11=, 1
; CHECK-NEXT:    i32.const $push0=, 2147483647
; CHECK-NEXT:    i32.and $push10=, $pop11, $pop0
; CHECK-NEXT:    local.set 2, $pop10
; CHECK-NEXT:    local.get $push14=, 1
; CHECK-NEXT:    local.get $push13=, 2
; CHECK-NEXT:    i32.ne $push12=, $pop14, $pop13
; CHECK-NEXT:    local.set 3, $pop12
; CHECK-NEXT:    i32.const $push1=, 0
; CHECK-NEXT:    local.get $push16=, 3
; CHECK-NEXT:    local.get $push15=, 2
; CHECK-NEXT:    i32.const $push2=, 1
; CHECK-NEXT:    i32.sub $push3=, $pop15, $pop2
; CHECK-NEXT:    i32.const $push4=, 8388607
; CHECK-NEXT:    i32.lt_u $push5=, $pop3, $pop4
; CHECK-NEXT:    i32.and $push6=, $pop16, $pop5
; CHECK-NEXT:    i32.or $push7=, $pop1, $pop6
; CHECK-NEXT:    return $pop7
  %a = call i1 @llvm.is.fpclass.f32(float %x, i32 16)
  ret i1 %a
}

define i1 @is_fpclass_f32_negzero(float %x) {
; CHECK-LABEL: is_fpclass_f32_negzero:
; CHECK:         .functype is_fpclass_f32_negzero (f32) -> (i32)
; CHECK-NEXT:    .local i32, i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    i32.reinterpret_f32 $push3=, $pop4
; CHECK-NEXT:    local.set 1, $pop3
; CHECK-NEXT:    i32.const $push5=, -2147483648
; CHECK-NEXT:    local.set 2, $pop5
; CHECK-NEXT:    i32.const $push0=, 0
; CHECK-NEXT:    local.get $push7=, 1
; CHECK-NEXT:    local.get $push6=, 2
; CHECK-NEXT:    i32.eq $push1=, $pop7, $pop6
; CHECK-NEXT:    i32.or $push2=, $pop0, $pop1
; CHECK-NEXT:    return $pop2
  %a = call i1 @llvm.is.fpclass.f32(float %x, i32 32)
  ret i1 %a
}

define i1 @is_fpclass_f32_poszero(float %x) {
; CHECK-LABEL: is_fpclass_f32_poszero:
; CHECK:         .functype is_fpclass_f32_poszero (f32) -> (i32)
; CHECK-NEXT:    .local i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    i32.reinterpret_f32 $push3=, $pop4
; CHECK-NEXT:    local.set 1, $pop3
; CHECK-NEXT:    i32.const $push0=, 0
; CHECK-NEXT:    local.get $push5=, 1
; CHECK-NEXT:    i32.eqz $push1=, $pop5
; CHECK-NEXT:    i32.or $push2=, $pop0, $pop1
; CHECK-NEXT:    return $pop2
  %a = call i1 @llvm.is.fpclass.f32(float %x, i32 64)
  ret i1 %a
}

define i1 @is_fpclass_f32_possubnorm(float %x) {
; CHECK-LABEL: is_fpclass_f32_possubnorm:
; CHECK:         .functype is_fpclass_f32_possubnorm (f32) -> (i32)
; CHECK-NEXT:    .local i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push7=, 0
; CHECK-NEXT:    i32.reinterpret_f32 $push6=, $pop7
; CHECK-NEXT:    local.set 1, $pop6
; CHECK-NEXT:    i32.const $push0=, 0
; CHECK-NEXT:    local.get $push8=, 1
; CHECK-NEXT:    i32.const $push1=, 1
; CHECK-NEXT:    i32.sub $push2=, $pop8, $pop1
; CHECK-NEXT:    i32.const $push3=, 8388607
; CHECK-NEXT:    i32.lt_u $push4=, $pop2, $pop3
; CHECK-NEXT:    i32.or $push5=, $pop0, $pop4
; CHECK-NEXT:    return $pop5
  %a = call i1 @llvm.is.fpclass.f32(float %x, i32 128)
  ret i1 %a
}

define i1 @is_fpclass_f32_posnormal(float %x) {
; CHECK-LABEL: is_fpclass_f32_posnormal:
; CHECK:         .functype is_fpclass_f32_posnormal (f32) -> (i32)
; CHECK-NEXT:    .local i32, i32, i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push11=, 0
; CHECK-NEXT:    i32.reinterpret_f32 $push10=, $pop11
; CHECK-NEXT:    local.set 1, $pop10
; CHECK-NEXT:    local.get $push13=, 1
; CHECK-NEXT:    i32.const $push0=, 2147483647
; CHECK-NEXT:    i32.and $push12=, $pop13, $pop0
; CHECK-NEXT:    local.set 2, $pop12
; CHECK-NEXT:    local.get $push16=, 1
; CHECK-NEXT:    local.get $push15=, 2
; CHECK-NEXT:    i32.ne $push14=, $pop16, $pop15
; CHECK-NEXT:    local.set 3, $pop14
; CHECK-NEXT:    i32.const $push1=, 0
; CHECK-NEXT:    local.get $push17=, 2
; CHECK-NEXT:    i32.const $push2=, 8388608
; CHECK-NEXT:    i32.sub $push3=, $pop17, $pop2
; CHECK-NEXT:    i32.const $push4=, 2130706432
; CHECK-NEXT:    i32.lt_u $push5=, $pop3, $pop4
; CHECK-NEXT:    local.get $push18=, 3
; CHECK-NEXT:    i32.const $push6=, -1
; CHECK-NEXT:    i32.xor $push7=, $pop18, $pop6
; CHECK-NEXT:    i32.and $push8=, $pop5, $pop7
; CHECK-NEXT:    i32.or $push9=, $pop1, $pop8
; CHECK-NEXT:    return $pop9
  %a = call i1 @llvm.is.fpclass.f32(float %x, i32 256)
  ret i1 %a
}

define i1 @is_fpclass_f32_posinf(float %x) {
; CHECK-LABEL: is_fpclass_f32_posinf:
; CHECK:         .functype is_fpclass_f32_posinf (f32) -> (i32)
; CHECK-NEXT:    .local i32, i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    i32.reinterpret_f32 $push3=, $pop4
; CHECK-NEXT:    local.set 1, $pop3
; CHECK-NEXT:    i32.const $push5=, 2139095040
; CHECK-NEXT:    local.set 2, $pop5
; CHECK-NEXT:    i32.const $push0=, 0
; CHECK-NEXT:    local.get $push7=, 1
; CHECK-NEXT:    local.get $push6=, 2
; CHECK-NEXT:    i32.eq $push1=, $pop7, $pop6
; CHECK-NEXT:    i32.or $push2=, $pop0, $pop1
; CHECK-NEXT:    return $pop2
  %a = call i1 @llvm.is.fpclass.f32(float %x, i32 512)
  ret i1 %a
}


define i1 @is_fpclass_f64_snan(double %x) {
; CHECK-LABEL: is_fpclass_f64_snan:
; CHECK:         .functype is_fpclass_f64_snan (f64) -> (i32)
; CHECK-NEXT:    .local i64, i64, i64, i64, i32, i64
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    i64.reinterpret_f64 $push4=, $pop5
; CHECK-NEXT:    local.set 1, $pop4
; CHECK-NEXT:    i64.const $push6=, 9223372036854775807
; CHECK-NEXT:    local.set 2, $pop6
; CHECK-NEXT:    i64.const $push7=, 9218868437227405312
; CHECK-NEXT:    local.set 3, $pop7
; CHECK-NEXT:    local.get $push10=, 1
; CHECK-NEXT:    local.get $push9=, 2
; CHECK-NEXT:    i64.and $push8=, $pop10, $pop9
; CHECK-NEXT:    local.set 4, $pop8
; CHECK-NEXT:    i32.const $push11=, 0
; CHECK-NEXT:    local.set 5, $pop11
; CHECK-NEXT:    i64.const $push12=, 9221120237041090560
; CHECK-NEXT:    local.set 6, $pop12
; CHECK-NEXT:    local.get $push17=, 5
; CHECK-NEXT:    local.get $push14=, 4
; CHECK-NEXT:    local.get $push13=, 3
; CHECK-NEXT:    i64.gt_u $push0=, $pop14, $pop13
; CHECK-NEXT:    local.get $push16=, 4
; CHECK-NEXT:    local.get $push15=, 6
; CHECK-NEXT:    i64.lt_u $push1=, $pop16, $pop15
; CHECK-NEXT:    i32.and $push2=, $pop0, $pop1
; CHECK-NEXT:    i32.or $push3=, $pop17, $pop2
; CHECK-NEXT:    return $pop3
  %a = call i1 @llvm.is.fpclass.f64(double %x, i32 1)
  ret i1 %a
}

define i1 @is_fpclass_f64_qnan(double %x) {
; CHECK-LABEL: is_fpclass_f64_qnan:
; CHECK:         .functype is_fpclass_f64_qnan (f64) -> (i32)
; CHECK-NEXT:    .local i64
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push6=, 0
; CHECK-NEXT:    i64.reinterpret_f64 $push0=, $pop6
; CHECK-NEXT:    i64.const $push1=, 9223372036854775807
; CHECK-NEXT:    i64.and $push7=, $pop0, $pop1
; CHECK-NEXT:    local.set 1, $pop7
; CHECK-NEXT:    i32.const $push2=, 0
; CHECK-NEXT:    local.get $push8=, 1
; CHECK-NEXT:    i64.const $push3=, 9221120237041090560
; CHECK-NEXT:    i64.ge_u $push4=, $pop8, $pop3
; CHECK-NEXT:    i32.or $push5=, $pop2, $pop4
; CHECK-NEXT:    return $pop5
  %a = call i1 @llvm.is.fpclass.f64(double %x, i32 2)
  ret i1 %a
}

define i1 @is_fpclass_f64_neginf(double %x) {
; CHECK-LABEL: is_fpclass_f64_neginf:
; CHECK:         .functype is_fpclass_f64_neginf (f64) -> (i32)
; CHECK-NEXT:    .local i64
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    i64.reinterpret_f64 $push4=, $pop5
; CHECK-NEXT:    local.set 1, $pop4
; CHECK-NEXT:    i32.const $push0=, 0
; CHECK-NEXT:    local.get $push6=, 1
; CHECK-NEXT:    i64.const $push1=, -4503599627370496
; CHECK-NEXT:    i64.eq $push2=, $pop6, $pop1
; CHECK-NEXT:    i32.or $push3=, $pop0, $pop2
; CHECK-NEXT:    return $pop3
  %a = call i1 @llvm.is.fpclass.f64(double %x, i32 4)
  ret i1 %a
}

define i1 @is_fpclass_f64_negnormal(double %x) {
; CHECK-LABEL: is_fpclass_f64_negnormal:
; CHECK:         .functype is_fpclass_f64_negnormal (f64) -> (i32)
; CHECK-NEXT:    .local i64, i64, i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push9=, 0
; CHECK-NEXT:    i64.reinterpret_f64 $push8=, $pop9
; CHECK-NEXT:    local.set 1, $pop8
; CHECK-NEXT:    local.get $push11=, 1
; CHECK-NEXT:    i64.const $push0=, 9223372036854775807
; CHECK-NEXT:    i64.and $push10=, $pop11, $pop0
; CHECK-NEXT:    local.set 2, $pop10
; CHECK-NEXT:    local.get $push14=, 1
; CHECK-NEXT:    local.get $push13=, 2
; CHECK-NEXT:    i64.ne $push12=, $pop14, $pop13
; CHECK-NEXT:    local.set 3, $pop12
; CHECK-NEXT:    i32.const $push1=, 0
; CHECK-NEXT:    local.get $push16=, 3
; CHECK-NEXT:    local.get $push15=, 2
; CHECK-NEXT:    i64.const $push2=, 4503599627370496
; CHECK-NEXT:    i64.sub $push3=, $pop15, $pop2
; CHECK-NEXT:    i64.const $push4=, 9214364837600034816
; CHECK-NEXT:    i64.lt_u $push5=, $pop3, $pop4
; CHECK-NEXT:    i32.and $push6=, $pop16, $pop5
; CHECK-NEXT:    i32.or $push7=, $pop1, $pop6
; CHECK-NEXT:    return $pop7
  %a = call i1 @llvm.is.fpclass.f64(double %x, i32 8)
  ret i1 %a
}

define i1 @is_fpclass_f64_negsubnorm(double %x) {
; CHECK-LABEL: is_fpclass_f64_negsubnorm:
; CHECK:         .functype is_fpclass_f64_negsubnorm (f64) -> (i32)
; CHECK-NEXT:    .local i64, i64, i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push9=, 0
; CHECK-NEXT:    i64.reinterpret_f64 $push8=, $pop9
; CHECK-NEXT:    local.set 1, $pop8
; CHECK-NEXT:    local.get $push11=, 1
; CHECK-NEXT:    i64.const $push0=, 9223372036854775807
; CHECK-NEXT:    i64.and $push10=, $pop11, $pop0
; CHECK-NEXT:    local.set 2, $pop10
; CHECK-NEXT:    local.get $push14=, 1
; CHECK-NEXT:    local.get $push13=, 2
; CHECK-NEXT:    i64.ne $push12=, $pop14, $pop13
; CHECK-NEXT:    local.set 3, $pop12
; CHECK-NEXT:    i32.const $push1=, 0
; CHECK-NEXT:    local.get $push16=, 3
; CHECK-NEXT:    local.get $push15=, 2
; CHECK-NEXT:    i64.const $push2=, 1
; CHECK-NEXT:    i64.sub $push3=, $pop15, $pop2
; CHECK-NEXT:    i64.const $push4=, 4503599627370495
; CHECK-NEXT:    i64.lt_u $push5=, $pop3, $pop4
; CHECK-NEXT:    i32.and $push6=, $pop16, $pop5
; CHECK-NEXT:    i32.or $push7=, $pop1, $pop6
; CHECK-NEXT:    return $pop7
  %a = call i1 @llvm.is.fpclass.f64(double %x, i32 16)
  ret i1 %a
}

define i1 @is_fpclass_f64_negzero(double %x) {
; CHECK-LABEL: is_fpclass_f64_negzero:
; CHECK:         .functype is_fpclass_f64_negzero (f64) -> (i32)
; CHECK-NEXT:    .local i64, i64
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    i64.reinterpret_f64 $push3=, $pop4
; CHECK-NEXT:    local.set 1, $pop3
; CHECK-NEXT:    i64.const $push5=, -9223372036854775808
; CHECK-NEXT:    local.set 2, $pop5
; CHECK-NEXT:    i32.const $push0=, 0
; CHECK-NEXT:    local.get $push7=, 1
; CHECK-NEXT:    local.get $push6=, 2
; CHECK-NEXT:    i64.eq $push1=, $pop7, $pop6
; CHECK-NEXT:    i32.or $push2=, $pop0, $pop1
; CHECK-NEXT:    return $pop2
  %a = call i1 @llvm.is.fpclass.f64(double %x, i32 32)
  ret i1 %a
}

define i1 @is_fpclass_f64_poszero(double %x) {
; CHECK-LABEL: is_fpclass_f64_poszero:
; CHECK:         .functype is_fpclass_f64_poszero (f64) -> (i32)
; CHECK-NEXT:    .local i64
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    i64.reinterpret_f64 $push3=, $pop4
; CHECK-NEXT:    local.set 1, $pop3
; CHECK-NEXT:    i32.const $push0=, 0
; CHECK-NEXT:    local.get $push5=, 1
; CHECK-NEXT:    i64.eqz $push1=, $pop5
; CHECK-NEXT:    i32.or $push2=, $pop0, $pop1
; CHECK-NEXT:    return $pop2
  %a = call i1 @llvm.is.fpclass.f64(double %x, i32 64)
  ret i1 %a
}

define i1 @is_fpclass_f64_possubnorm(double %x) {
; CHECK-LABEL: is_fpclass_f64_possubnorm:
; CHECK:         .functype is_fpclass_f64_possubnorm (f64) -> (i32)
; CHECK-NEXT:    .local i64
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push7=, 0
; CHECK-NEXT:    i64.reinterpret_f64 $push6=, $pop7
; CHECK-NEXT:    local.set 1, $pop6
; CHECK-NEXT:    i32.const $push0=, 0
; CHECK-NEXT:    local.get $push8=, 1
; CHECK-NEXT:    i64.const $push1=, 1
; CHECK-NEXT:    i64.sub $push2=, $pop8, $pop1
; CHECK-NEXT:    i64.const $push3=, 4503599627370495
; CHECK-NEXT:    i64.lt_u $push4=, $pop2, $pop3
; CHECK-NEXT:    i32.or $push5=, $pop0, $pop4
; CHECK-NEXT:    return $pop5
  %a = call i1 @llvm.is.fpclass.f64(double %x, i32 128)
  ret i1 %a
}

define i1 @is_fpclass_f64_posnormal(double %x) {
; CHECK-LABEL: is_fpclass_f64_posnormal:
; CHECK:         .functype is_fpclass_f64_posnormal (f64) -> (i32)
; CHECK-NEXT:    .local i64, i64, i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push11=, 0
; CHECK-NEXT:    i64.reinterpret_f64 $push10=, $pop11
; CHECK-NEXT:    local.set 1, $pop10
; CHECK-NEXT:    local.get $push13=, 1
; CHECK-NEXT:    i64.const $push0=, 9223372036854775807
; CHECK-NEXT:    i64.and $push12=, $pop13, $pop0
; CHECK-NEXT:    local.set 2, $pop12
; CHECK-NEXT:    local.get $push16=, 1
; CHECK-NEXT:    local.get $push15=, 2
; CHECK-NEXT:    i64.ne $push14=, $pop16, $pop15
; CHECK-NEXT:    local.set 3, $pop14
; CHECK-NEXT:    i32.const $push1=, 0
; CHECK-NEXT:    local.get $push17=, 2
; CHECK-NEXT:    i64.const $push2=, 4503599627370496
; CHECK-NEXT:    i64.sub $push3=, $pop17, $pop2
; CHECK-NEXT:    i64.const $push4=, 9214364837600034816
; CHECK-NEXT:    i64.lt_u $push5=, $pop3, $pop4
; CHECK-NEXT:    local.get $push18=, 3
; CHECK-NEXT:    i32.const $push6=, -1
; CHECK-NEXT:    i32.xor $push7=, $pop18, $pop6
; CHECK-NEXT:    i32.and $push8=, $pop5, $pop7
; CHECK-NEXT:    i32.or $push9=, $pop1, $pop8
; CHECK-NEXT:    return $pop9
  %a = call i1 @llvm.is.fpclass.f64(double %x, i32 256)
  ret i1 %a
}

define i1 @is_fpclass_f64_posinf(double %x) {
; CHECK-LABEL: is_fpclass_f64_posinf:
; CHECK:         .functype is_fpclass_f64_posinf (f64) -> (i32)
; CHECK-NEXT:    .local i64, i64
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    i64.reinterpret_f64 $push3=, $pop4
; CHECK-NEXT:    local.set 1, $pop3
; CHECK-NEXT:    i64.const $push5=, 9218868437227405312
; CHECK-NEXT:    local.set 2, $pop5
; CHECK-NEXT:    i32.const $push0=, 0
; CHECK-NEXT:    local.get $push7=, 1
; CHECK-NEXT:    local.get $push6=, 2
; CHECK-NEXT:    i64.eq $push1=, $pop7, $pop6
; CHECK-NEXT:    i32.or $push2=, $pop0, $pop1
; CHECK-NEXT:    return $pop2
  %a = call i1 @llvm.is.fpclass.f64(double %x, i32 512)
  ret i1 %a
}
