; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

declare i2 @llvm.scmp.i2.i8(i8, i8)
declare i2 @llvm.scmp.i2.i16(i16, i16)
declare i2 @llvm.scmp.i2.i32(i32, i32)
declare i2 @llvm.scmp.i2.i64(i64, i64)

define i2 @scmp_i8(i8 %x, i8 %y) {
; CHECK-LABEL: scmp_i8:
; CHECK:         .functype scmp_i8 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push7=, 0
; CHECK-NEXT:    i32.extend8_s $push5=, $pop7
; CHECK-NEXT:    local.get $push8=, 1
; CHECK-NEXT:    i32.extend8_s $push6=, $pop8
; CHECK-NEXT:    i32.gt_s $push4=, $pop5, $pop6
; CHECK-NEXT:    local.get $push9=, 0
; CHECK-NEXT:    i32.extend8_s $push2=, $pop9
; CHECK-NEXT:    local.get $push10=, 1
; CHECK-NEXT:    i32.extend8_s $push3=, $pop10
; CHECK-NEXT:    i32.lt_s $push1=, $pop2, $pop3
; CHECK-NEXT:    i32.sub $push0=, $pop4, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i2 @llvm.scmp.i2.i8(i8 %x, i8 %y)
  ret i2 %a
}

define i2 @scmp_i16(i16 %x, i16 %y) {
; CHECK-LABEL: scmp_i16:
; CHECK:         .functype scmp_i16 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push7=, 0
; CHECK-NEXT:    i32.extend16_s $push5=, $pop7
; CHECK-NEXT:    local.get $push8=, 1
; CHECK-NEXT:    i32.extend16_s $push6=, $pop8
; CHECK-NEXT:    i32.gt_s $push4=, $pop5, $pop6
; CHECK-NEXT:    local.get $push9=, 0
; CHECK-NEXT:    i32.extend16_s $push2=, $pop9
; CHECK-NEXT:    local.get $push10=, 1
; CHECK-NEXT:    i32.extend16_s $push3=, $pop10
; CHECK-NEXT:    i32.lt_s $push1=, $pop2, $pop3
; CHECK-NEXT:    i32.sub $push0=, $pop4, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i2 @llvm.scmp.i2.i16(i16 %x, i16 %y)
  ret i2 %a
}

define i2 @scmp_i32(i32 %x, i32 %y) {
; CHECK-LABEL: scmp_i32:
; CHECK:         .functype scmp_i32 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    i32.gt_s $push2=, $pop4, $pop3
; CHECK-NEXT:    local.get $push6=, 0
; CHECK-NEXT:    local.get $push5=, 1
; CHECK-NEXT:    i32.lt_s $push1=, $pop6, $pop5
; CHECK-NEXT:    i32.sub $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i2 @llvm.scmp.i2.i32(i32 %x, i32 %y)
  ret i2 %a
}

define i2 @scmp_i64(i64 %x, i64 %y) {
; CHECK-LABEL: scmp_i64:
; CHECK:         .functype scmp_i64 (i64, i64) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    i64.gt_s $push2=, $pop4, $pop3
; CHECK-NEXT:    local.get $push6=, 0
; CHECK-NEXT:    local.get $push5=, 1
; CHECK-NEXT:    i64.lt_s $push1=, $pop6, $pop5
; CHECK-NEXT:    i32.sub $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = call i2 @llvm.scmp.i2.i64(i64 %x, i64 %y)
  ret i2 %a
}
