; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -mattr=-sign-ext -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s -check-prefixes=CHECK,NO-SIGNEXT
; RUN: llc < %s -O0 --global-isel -mattr=+sign-ext -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s -check-prefixes=CHECK,SIGNEXT

target triple = "wasm32-unknown-unknown"

define i32 @sext_i1_i32(i1 %x) {
; CHECK-LABEL: sext_i1_i32:
; CHECK:         .functype sext_i1_i32 (i32) -> (i32)
; CHECK-NEXT:    .local i32
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    i32.const $push2=, 31
; CHECK-NEXT:    local.set 1, $pop2
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    i32.shl $push1=, $pop4, $pop3
; CHECK-NEXT:    local.get $push5=, 1
; CHECK-NEXT:    i32.shr_s $push0=, $pop1, $pop5
; CHECK-NEXT:    return $pop0
  %a = sext i1 %x to i32
  ret i32 %a
}
define i64 @sext_i1_i64(i1 %x) {
; CHECK-LABEL: sext_i1_i64:
; CHECK:         .functype sext_i1_i64 (i32) -> (i64)
; CHECK-NEXT:    .local i64, i64
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push3=, 0
; CHECK-NEXT:    i64.extend_i32_u $push2=, $pop3
; CHECK-NEXT:    local.set 1, $pop2
; CHECK-NEXT:    i64.const $push4=, 63
; CHECK-NEXT:    local.set 2, $pop4
; CHECK-NEXT:    local.get $push6=, 1
; CHECK-NEXT:    local.get $push5=, 2
; CHECK-NEXT:    i64.shl $push1=, $pop6, $pop5
; CHECK-NEXT:    local.get $push7=, 2
; CHECK-NEXT:    i64.shr_s $push0=, $pop1, $pop7
; CHECK-NEXT:    return $pop0
  %a = sext i1 %x to i64
  ret i64 %a
}

define i32 @sext_i8_i32(i8 %x) {
; NO-SIGNEXT-LABEL: sext_i8_i32:
; NO-SIGNEXT:         .functype sext_i8_i32 (i32) -> (i32)
; NO-SIGNEXT-NEXT:    .local i32
; NO-SIGNEXT-NEXT:  # %bb.0:
; NO-SIGNEXT-NEXT:    i32.const $push2=, 24
; NO-SIGNEXT-NEXT:    local.set 1, $pop2
; NO-SIGNEXT-NEXT:    local.get $push4=, 0
; NO-SIGNEXT-NEXT:    local.get $push3=, 1
; NO-SIGNEXT-NEXT:    i32.shl $push1=, $pop4, $pop3
; NO-SIGNEXT-NEXT:    local.get $push5=, 1
; NO-SIGNEXT-NEXT:    i32.shr_s $push0=, $pop1, $pop5
; NO-SIGNEXT-NEXT:    return $pop0
;
; SIGNEXT-LABEL: sext_i8_i32:
; SIGNEXT:         .functype sext_i8_i32 (i32) -> (i32)
; SIGNEXT-NEXT:  # %bb.0:
; SIGNEXT-NEXT:    local.get $push1=, 0
; SIGNEXT-NEXT:    i32.extend8_s $push0=, $pop1
; SIGNEXT-NEXT:    return $pop0
  %a = sext i8 %x to i32
  ret i32 %a
}
define i64 @sext_i8_i64(i8 %x) {
; NO-SIGNEXT-LABEL: sext_i8_i64:
; NO-SIGNEXT:         .functype sext_i8_i64 (i32) -> (i64)
; NO-SIGNEXT-NEXT:    .local i64, i64
; NO-SIGNEXT-NEXT:  # %bb.0:
; NO-SIGNEXT-NEXT:    local.get $push3=, 0
; NO-SIGNEXT-NEXT:    i64.extend_i32_u $push2=, $pop3
; NO-SIGNEXT-NEXT:    local.set 1, $pop2
; NO-SIGNEXT-NEXT:    i64.const $push4=, 56
; NO-SIGNEXT-NEXT:    local.set 2, $pop4
; NO-SIGNEXT-NEXT:    local.get $push6=, 1
; NO-SIGNEXT-NEXT:    local.get $push5=, 2
; NO-SIGNEXT-NEXT:    i64.shl $push1=, $pop6, $pop5
; NO-SIGNEXT-NEXT:    local.get $push7=, 2
; NO-SIGNEXT-NEXT:    i64.shr_s $push0=, $pop1, $pop7
; NO-SIGNEXT-NEXT:    return $pop0
;
; SIGNEXT-LABEL: sext_i8_i64:
; SIGNEXT:         .functype sext_i8_i64 (i32) -> (i64)
; SIGNEXT-NEXT:  # %bb.0:
; SIGNEXT-NEXT:    local.get $push2=, 0
; SIGNEXT-NEXT:    i64.extend_i32_u $push1=, $pop2
; SIGNEXT-NEXT:    i64.extend8_s $push0=, $pop1
; SIGNEXT-NEXT:    return $pop0
  %a = sext i8 %x to i64
  ret i64 %a
}

define i32 @sext_i16_i32(i16 %x) {
; NO-SIGNEXT-LABEL: sext_i16_i32:
; NO-SIGNEXT:         .functype sext_i16_i32 (i32) -> (i32)
; NO-SIGNEXT-NEXT:    .local i32
; NO-SIGNEXT-NEXT:  # %bb.0:
; NO-SIGNEXT-NEXT:    i32.const $push2=, 16
; NO-SIGNEXT-NEXT:    local.set 1, $pop2
; NO-SIGNEXT-NEXT:    local.get $push4=, 0
; NO-SIGNEXT-NEXT:    local.get $push3=, 1
; NO-SIGNEXT-NEXT:    i32.shl $push1=, $pop4, $pop3
; NO-SIGNEXT-NEXT:    local.get $push5=, 1
; NO-SIGNEXT-NEXT:    i32.shr_s $push0=, $pop1, $pop5
; NO-SIGNEXT-NEXT:    return $pop0
;
; SIGNEXT-LABEL: sext_i16_i32:
; SIGNEXT:         .functype sext_i16_i32 (i32) -> (i32)
; SIGNEXT-NEXT:  # %bb.0:
; SIGNEXT-NEXT:    local.get $push1=, 0
; SIGNEXT-NEXT:    i32.extend16_s $push0=, $pop1
; SIGNEXT-NEXT:    return $pop0
  %a = sext i16 %x to i32
  ret i32 %a
}
define i64 @sext_i16_i64(i16 %x) {
; NO-SIGNEXT-LABEL: sext_i16_i64:
; NO-SIGNEXT:         .functype sext_i16_i64 (i32) -> (i64)
; NO-SIGNEXT-NEXT:    .local i64, i64
; NO-SIGNEXT-NEXT:  # %bb.0:
; NO-SIGNEXT-NEXT:    local.get $push3=, 0
; NO-SIGNEXT-NEXT:    i64.extend_i32_u $push2=, $pop3
; NO-SIGNEXT-NEXT:    local.set 1, $pop2
; NO-SIGNEXT-NEXT:    i64.const $push4=, 48
; NO-SIGNEXT-NEXT:    local.set 2, $pop4
; NO-SIGNEXT-NEXT:    local.get $push6=, 1
; NO-SIGNEXT-NEXT:    local.get $push5=, 2
; NO-SIGNEXT-NEXT:    i64.shl $push1=, $pop6, $pop5
; NO-SIGNEXT-NEXT:    local.get $push7=, 2
; NO-SIGNEXT-NEXT:    i64.shr_s $push0=, $pop1, $pop7
; NO-SIGNEXT-NEXT:    return $pop0
;
; SIGNEXT-LABEL: sext_i16_i64:
; SIGNEXT:         .functype sext_i16_i64 (i32) -> (i64)
; SIGNEXT-NEXT:  # %bb.0:
; SIGNEXT-NEXT:    local.get $push2=, 0
; SIGNEXT-NEXT:    i64.extend_i32_u $push1=, $pop2
; SIGNEXT-NEXT:    i64.extend16_s $push0=, $pop1
; SIGNEXT-NEXT:    return $pop0
  %a = sext i16 %x to i64
  ret i64 %a
}

define i64 @sext_i32_i64(i32 %x) {
; CHECK-LABEL: sext_i32_i64:
; CHECK:         .functype sext_i32_i64 (i32) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i64.extend_i32_s $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = sext i32 %x to i64
  ret i64 %a
}
