; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

define i8 @shl_i8(i8 %x) {
; CHECK-LABEL: shl_i8:
; CHECK:         .functype shl_i8 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    i32.const $push1=, 5
; CHECK-NEXT:    i32.shl $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = shl i8 %x, 5
  ret i8 %a
}

define i8 @shlv_i8(i8 %x, i8 %y) {
; CHECK-LABEL: shlv_i8:
; CHECK:         .functype shlv_i8 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    i32.const $push2=, 255
; CHECK-NEXT:    i32.and $push1=, $pop3, $pop2
; CHECK-NEXT:    i32.shl $push0=, $pop4, $pop1
; CHECK-NEXT:    return $pop0
  %a = shl i8 %x, %y
  ret i8 %a
}

define i16 @shl_i16(i16 %x) {
; CHECK-LABEL: shl_i16:
; CHECK:         .functype shl_i16 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    i32.const $push1=, 13
; CHECK-NEXT:    i32.shl $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = shl i16 %x, 13
  ret i16 %a
}

define i16 @shlv_i16(i16 %x, i16 %y) {
; CHECK-LABEL: shlv_i16:
; CHECK:         .functype shlv_i16 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push4=, 0
; CHECK-NEXT:    local.get $push3=, 1
; CHECK-NEXT:    i32.const $push2=, 65535
; CHECK-NEXT:    i32.and $push1=, $pop3, $pop2
; CHECK-NEXT:    i32.shl $push0=, $pop4, $pop1
; CHECK-NEXT:    return $pop0
  %a = shl i16 %x, %y
  ret i16 %a
}

define i32 @shl_i32(i32 %x) {
; CHECK-LABEL: shl_i32:
; CHECK:         .functype shl_i32 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    i32.const $push0=, 21
; CHECK-NEXT:    i32.shl $push1=, $pop2, $pop0
; CHECK-NEXT:    return $pop1
  %a = shl i32 %x, 21
  ret i32 %a
}

define i32 @shlv_i32(i32 %x, i32 %y) {
; CHECK-LABEL: shlv_i32:
; CHECK:         .functype shlv_i32 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.shl $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = shl i32 %x, %y
  ret i32 %a
}

define i64 @shl_i64(i64 %x) {
; CHECK-LABEL: shl_i64:
; CHECK:         .functype shl_i64 (i64) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    i64.const $push0=, 37
; CHECK-NEXT:    i64.shl $push1=, $pop2, $pop0
; CHECK-NEXT:    return $pop1
  %a = shl i64 %x, 37
  ret i64 %a
}

define i64 @shlv_i64(i64 %x, i64 %y) {
; CHECK-LABEL: shlv_i64:
; CHECK:         .functype shlv_i64 (i64, i64) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i64.shl $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = shl i64 %x, %y
  ret i64 %a
}
