; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s

target triple = "wasm32-unknown-unknown"

define i8 @udiv_i8(i8 %x, i8 %y) {
; CHECK-LABEL: udiv_i8:
; CHECK:         .functype udiv_i8 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    i32.const $push4=, 255
; CHECK-NEXT:    i32.and $push0=, $pop5, $pop4
; CHECK-NEXT:    local.get $push6=, 1
; CHECK-NEXT:    i32.const $push3=, 255
; CHECK-NEXT:    i32.and $push1=, $pop6, $pop3
; CHECK-NEXT:    i32.div_u $push2=, $pop0, $pop1
; CHECK-NEXT:    return $pop2
  %a = udiv i8 %x, %y
  ret i8 %a
}

define i16 @udiv_i16(i16 %x, i16 %y) {
; CHECK-LABEL: udiv_i16:
; CHECK:         .functype udiv_i16 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push5=, 0
; CHECK-NEXT:    i32.const $push4=, 65535
; CHECK-NEXT:    i32.and $push0=, $pop5, $pop4
; CHECK-NEXT:    local.get $push6=, 1
; CHECK-NEXT:    i32.const $push3=, 65535
; CHECK-NEXT:    i32.and $push1=, $pop6, $pop3
; CHECK-NEXT:    i32.div_u $push2=, $pop0, $pop1
; CHECK-NEXT:    return $pop2
  %a = udiv i16 %x, %y
  ret i16 %a
}

define i32 @udiv_i32(i32 %x, i32 %y) {
; CHECK-LABEL: udiv_i32:
; CHECK:         .functype udiv_i32 (i32, i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i32.div_u $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = udiv i32 %x, %y
  ret i32 %a
}

define i64 @udiv_i64(i64 %x, i64 %y) {
; CHECK-LABEL: udiv_i64:
; CHECK:         .functype udiv_i64 (i64, i64) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    local.get $push1=, 1
; CHECK-NEXT:    i64.div_u $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = udiv i64 %x, %y
  ret i64 %a
}
