; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -O0 --global-isel -mattr=-sign-ext -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s -check-prefixes=CHECK
; RUN: llc < %s -O0 --global-isel -mattr=+sign-ext -disable-wasm-fallthrough-return-opt -wasm-keep-registers | FileCheck %s -check-prefixes=CHECK

target triple = "wasm32-unknown-unknown"

define i32 @zext_i1_i32(i1 %x) {
; CHECK-LABEL: zext_i1_i32:
; CHECK:         .functype zext_i1_i32 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    i32.const $push1=, 1
; CHECK-NEXT:    i32.and $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = zext i1 %x to i32
  ret i32 %a
}
define i64 @zext_i1_i64(i1 %x) {
; CHECK-LABEL: zext_i1_i64:
; CHECK:         .functype zext_i1_i64 (i32) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push3=, 0
; CHECK-NEXT:    i64.extend_i32_u $push1=, $pop3
; CHECK-NEXT:    i64.const $push2=, 1
; CHECK-NEXT:    i64.and $push0=, $pop1, $pop2
; CHECK-NEXT:    return $pop0
  %a = zext i1 %x to i64
  ret i64 %a
}

define i32 @zext_i8_i32(i8 %x) {
; CHECK-LABEL: zext_i8_i32:
; CHECK:         .functype zext_i8_i32 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    i32.const $push1=, 255
; CHECK-NEXT:    i32.and $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = zext i8 %x to i32
  ret i32 %a
}
define i64 @zext_i8_i64(i8 %x) {
; CHECK-LABEL: zext_i8_i64:
; CHECK:         .functype zext_i8_i64 (i32) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push3=, 0
; CHECK-NEXT:    i64.extend_i32_u $push1=, $pop3
; CHECK-NEXT:    i64.const $push2=, 255
; CHECK-NEXT:    i64.and $push0=, $pop1, $pop2
; CHECK-NEXT:    return $pop0
  %a = zext i8 %x to i64
  ret i64 %a
}

define i32 @zext_i16_i32(i16 %x) {
; CHECK-LABEL: zext_i16_i32:
; CHECK:         .functype zext_i16_i32 (i32) -> (i32)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push2=, 0
; CHECK-NEXT:    i32.const $push1=, 65535
; CHECK-NEXT:    i32.and $push0=, $pop2, $pop1
; CHECK-NEXT:    return $pop0
  %a = zext i16 %x to i32
  ret i32 %a
}
define i64 @zext_i16_i64(i16 %x) {
; CHECK-LABEL: zext_i16_i64:
; CHECK:         .functype zext_i16_i64 (i32) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push3=, 0
; CHECK-NEXT:    i64.extend_i32_u $push1=, $pop3
; CHECK-NEXT:    i64.const $push2=, 65535
; CHECK-NEXT:    i64.and $push0=, $pop1, $pop2
; CHECK-NEXT:    return $pop0
  %a = zext i16 %x to i64
  ret i64 %a
}

define i64 @zext_i32_i64(i32 %x) {
; CHECK-LABEL: zext_i32_i64:
; CHECK:         .functype zext_i32_i64 (i32) -> (i64)
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    local.get $push1=, 0
; CHECK-NEXT:    i64.extend_i32_u $push0=, $pop1
; CHECK-NEXT:    return $pop0
  %a = zext i32 %x to i64
  ret i64 %a
}
