; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=nvptx64-nvidia-cuda -passes=load-store-vectorizer -S -o - %s | FileCheck %s

define void @ldg_f16(ptr nocapture align 16 %rd0) {
; CHECK-LABEL: define void @ldg_f16(
; CHECK-SAME: ptr align 16 captures(none) [[RD0:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = load <8 x b16>, ptr [[RD0]], align 16
; CHECK-NEXT:    [[LOAD12:%.*]] = shufflevector <8 x b16> [[TMP1]], <8 x b16> poison, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[LOAD11:%.*]] = bitcast <2 x b16> [[LOAD12]] to <2 x half>
; CHECK-NEXT:    [[LOAD23:%.*]] = shufflevector <8 x b16> [[TMP1]], <8 x b16> poison, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    [[LOAD22:%.*]] = bitcast <2 x b16> [[LOAD23]] to <2 x half>
; CHECK-NEXT:    [[LOAD34:%.*]] = shufflevector <8 x b16> [[TMP1]], <8 x b16> poison, <2 x i32> <i32 4, i32 5>
; CHECK-NEXT:    [[LOAD33:%.*]] = bitcast <2 x b16> [[LOAD34]] to <2 x half>
; CHECK-NEXT:    [[LOAD45:%.*]] = shufflevector <8 x b16> [[TMP1]], <8 x b16> poison, <2 x i32> <i32 6, i32 7>
; CHECK-NEXT:    [[LOAD44:%.*]] = bitcast <2 x b16> [[LOAD45]] to <2 x half>
; CHECK-NEXT:    [[P1:%.*]] = fcmp ogt <2 x half> [[LOAD11]], zeroinitializer
; CHECK-NEXT:    [[S1:%.*]] = select <2 x i1> [[P1]], <2 x half> [[LOAD11]], <2 x half> zeroinitializer
; CHECK-NEXT:    [[P2:%.*]] = fcmp ogt <2 x half> [[LOAD22]], zeroinitializer
; CHECK-NEXT:    [[S2:%.*]] = select <2 x i1> [[P2]], <2 x half> [[LOAD22]], <2 x half> zeroinitializer
; CHECK-NEXT:    [[P3:%.*]] = fcmp ogt <2 x half> [[LOAD33]], zeroinitializer
; CHECK-NEXT:    [[S3:%.*]] = select <2 x i1> [[P3]], <2 x half> [[LOAD33]], <2 x half> zeroinitializer
; CHECK-NEXT:    [[P4:%.*]] = fcmp ogt <2 x half> [[LOAD44]], zeroinitializer
; CHECK-NEXT:    [[S4:%.*]] = select <2 x i1> [[P4]], <2 x half> [[LOAD44]], <2 x half> zeroinitializer
; CHECK-NEXT:    [[TMP6:%.*]] = bitcast <2 x half> [[S1]] to <2 x b16>
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x b16> [[TMP6]], i32 0
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <8 x b16> poison, b16 [[TMP7]], i32 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <2 x b16> [[TMP6]], i32 1
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <8 x b16> [[TMP8]], b16 [[TMP9]], i32 1
; CHECK-NEXT:    [[TMP11:%.*]] = bitcast <2 x half> [[S2]] to <2 x b16>
; CHECK-NEXT:    [[TMP12:%.*]] = extractelement <2 x b16> [[TMP11]], i32 0
; CHECK-NEXT:    [[TMP13:%.*]] = insertelement <8 x b16> [[TMP10]], b16 [[TMP12]], i32 2
; CHECK-NEXT:    [[TMP14:%.*]] = extractelement <2 x b16> [[TMP11]], i32 1
; CHECK-NEXT:    [[TMP15:%.*]] = insertelement <8 x b16> [[TMP13]], b16 [[TMP14]], i32 3
; CHECK-NEXT:    [[TMP16:%.*]] = bitcast <2 x half> [[S3]] to <2 x b16>
; CHECK-NEXT:    [[TMP17:%.*]] = extractelement <2 x b16> [[TMP16]], i32 0
; CHECK-NEXT:    [[TMP18:%.*]] = insertelement <8 x b16> [[TMP15]], b16 [[TMP17]], i32 4
; CHECK-NEXT:    [[TMP19:%.*]] = extractelement <2 x b16> [[TMP16]], i32 1
; CHECK-NEXT:    [[TMP20:%.*]] = insertelement <8 x b16> [[TMP18]], b16 [[TMP19]], i32 5
; CHECK-NEXT:    [[TMP21:%.*]] = bitcast <2 x half> [[S4]] to <2 x b16>
; CHECK-NEXT:    [[TMP22:%.*]] = extractelement <2 x b16> [[TMP21]], i32 0
; CHECK-NEXT:    [[TMP23:%.*]] = insertelement <8 x b16> [[TMP20]], b16 [[TMP22]], i32 6
; CHECK-NEXT:    [[TMP24:%.*]] = extractelement <2 x b16> [[TMP21]], i32 1
; CHECK-NEXT:    [[TMP25:%.*]] = insertelement <8 x b16> [[TMP23]], b16 [[TMP24]], i32 7
; CHECK-NEXT:    store <8 x b16> [[TMP25]], ptr [[RD0]], align 16
; CHECK-NEXT:    ret void
;
  %load1 = load <2 x half>, ptr %rd0, align 16
  %p1 = fcmp ogt <2 x half> %load1, zeroinitializer
  %s1 = select <2 x i1> %p1, <2 x half> %load1, <2 x half> zeroinitializer
  store <2 x half> %s1, ptr %rd0, align 16
  %in2 = getelementptr half, ptr %rd0, i64 2
  %load2 = load <2 x half>, ptr %in2, align 4
  %p2 = fcmp ogt <2 x half> %load2, zeroinitializer
  %s2 = select <2 x i1> %p2, <2 x half> %load2, <2 x half> zeroinitializer
  store <2 x half> %s2, ptr %in2, align 4
  %in3 = getelementptr half, ptr %rd0, i64 4
  %load3 = load <2 x half>, ptr %in3, align 4
  %p3 = fcmp ogt <2 x half> %load3, zeroinitializer
  %s3 = select <2 x i1> %p3, <2 x half> %load3, <2 x half> zeroinitializer
  store <2 x half> %s3, ptr %in3, align 4
  %in4 = getelementptr half, ptr %rd0, i64 6
  %load4 = load <2 x half>, ptr %in4, align 4
  %p4 = fcmp ogt <2 x half> %load4, zeroinitializer
  %s4 = select <2 x i1> %p4, <2 x half> %load4, <2 x half> zeroinitializer
  store <2 x half> %s4, ptr %in4, align 4
  ret void

}

define void @no_nonpow2_vector(ptr nocapture align 16 %rd0) {
; CHECK-LABEL: define void @no_nonpow2_vector(
; CHECK-SAME: ptr align 16 captures(none) [[RD0:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call <8 x b16> @llvm.masked.load.v8b16.p0(ptr align 16 [[RD0]], <8 x i1> <i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 false, i1 false>, <8 x b16> poison)
; CHECK-NEXT:    [[LOAD14:%.*]] = shufflevector <8 x b16> [[TMP1]], <8 x b16> poison, <3 x i32> <i32 0, i32 1, i32 2>
; CHECK-NEXT:    [[LOAD13:%.*]] = bitcast <3 x b16> [[LOAD14]] to <3 x half>
; CHECK-NEXT:    [[LOAD25:%.*]] = shufflevector <8 x b16> [[TMP1]], <8 x b16> poison, <3 x i32> <i32 3, i32 4, i32 5>
; CHECK-NEXT:    [[LOAD24:%.*]] = bitcast <3 x b16> [[LOAD25]] to <3 x half>
; CHECK-NEXT:    [[EXTEND5:%.*]] = extractelement <8 x b16> [[TMP1]], i32 6
; CHECK-NEXT:    [[EXTEND26:%.*]] = extractelement <8 x b16> [[TMP1]], i32 7
; CHECK-NEXT:    [[P1:%.*]] = fcmp ogt <3 x half> [[LOAD13]], zeroinitializer
; CHECK-NEXT:    [[S1:%.*]] = select <3 x i1> [[P1]], <3 x half> [[LOAD13]], <3 x half> zeroinitializer
; CHECK-NEXT:    store <3 x half> [[S1]], ptr [[RD0]], align 16
; CHECK-NEXT:    [[IN2:%.*]] = getelementptr half, ptr [[RD0]], i64 3
; CHECK-NEXT:    [[P2:%.*]] = fcmp ogt <3 x half> [[LOAD24]], zeroinitializer
; CHECK-NEXT:    [[S2:%.*]] = select <3 x i1> [[P2]], <3 x half> [[LOAD24]], <3 x half> zeroinitializer
; CHECK-NEXT:    store <3 x half> [[S2]], ptr [[IN2]], align 4
; CHECK-NEXT:    [[IN3:%.*]] = getelementptr half, ptr [[RD0]], i64 6
; CHECK-NEXT:    [[LOAD3:%.*]] = load <3 x half>, ptr [[IN3]], align 4
; CHECK-NEXT:    [[P3:%.*]] = fcmp ogt <3 x half> [[LOAD3]], zeroinitializer
; CHECK-NEXT:    [[S3:%.*]] = select <3 x i1> [[P3]], <3 x half> [[LOAD3]], <3 x half> zeroinitializer
; CHECK-NEXT:    store <3 x half> [[S3]], ptr [[IN3]], align 4
; CHECK-NEXT:    [[IN4:%.*]] = getelementptr half, ptr [[RD0]], i64 9
; CHECK-NEXT:    [[LOAD4:%.*]] = load <3 x half>, ptr [[IN4]], align 4
; CHECK-NEXT:    [[P4:%.*]] = fcmp ogt <3 x half> [[LOAD4]], zeroinitializer
; CHECK-NEXT:    [[S4:%.*]] = select <3 x i1> [[P4]], <3 x half> [[LOAD4]], <3 x half> zeroinitializer
; CHECK-NEXT:    store <3 x half> [[S4]], ptr [[IN4]], align 4
; CHECK-NEXT:    ret void
;
  %load1 = load <3 x half>, ptr %rd0, align 16
  %p1 = fcmp ogt <3 x half> %load1, zeroinitializer
  %s1 = select <3 x i1> %p1, <3 x half> %load1, <3 x half> zeroinitializer
  store <3 x half> %s1, ptr %rd0, align 16
  %in2 = getelementptr half, ptr %rd0, i64 3
  %load2 = load <3 x half>, ptr %in2, align 4
  %p2 = fcmp ogt <3 x half> %load2, zeroinitializer
  %s2 = select <3 x i1> %p2, <3 x half> %load2, <3 x half> zeroinitializer
  store <3 x half> %s2, ptr %in2, align 4
  %in3 = getelementptr half, ptr %rd0, i64 6
  %load3 = load <3 x half>, ptr %in3, align 4
  %p3 = fcmp ogt <3 x half> %load3, zeroinitializer
  %s3 = select <3 x i1> %p3, <3 x half> %load3, <3 x half> zeroinitializer
  store <3 x half> %s3, ptr %in3, align 4
  %in4 = getelementptr half, ptr %rd0, i64 9
  %load4 = load <3 x half>, ptr %in4, align 4
  %p4 = fcmp ogt <3 x half> %load4, zeroinitializer
  %s4 = select <3 x i1> %p4, <3 x half> %load4, <3 x half> zeroinitializer
  store <3 x half> %s4, ptr %in4, align 4
  ret void
}

define void @no_pointer_vector(ptr nocapture align 16 %rd0) {
; CHECK-LABEL: define void @no_pointer_vector(
; CHECK-SAME: ptr align 16 captures(none) [[RD0:%.*]]) {
; CHECK-NEXT:    [[LOAD1:%.*]] = load <2 x ptr>, ptr [[RD0]], align 16
; CHECK-NEXT:    [[P1:%.*]] = icmp ne <2 x ptr> [[LOAD1]], splat (ptr null)
; CHECK-NEXT:    [[S1:%.*]] = select <2 x i1> [[P1]], <2 x ptr> [[LOAD1]], <2 x ptr> splat (ptr null)
; CHECK-NEXT:    store <2 x ptr> [[S1]], ptr [[RD0]], align 16
; CHECK-NEXT:    [[IN2:%.*]] = getelementptr ptr, ptr [[RD0]], i64 2
; CHECK-NEXT:    [[LOAD2:%.*]] = load <2 x ptr>, ptr [[IN2]], align 4
; CHECK-NEXT:    [[P2:%.*]] = icmp ne <2 x ptr> [[LOAD2]], splat (ptr null)
; CHECK-NEXT:    [[S2:%.*]] = select <2 x i1> [[P2]], <2 x ptr> [[LOAD2]], <2 x ptr> splat (ptr null)
; CHECK-NEXT:    store <2 x ptr> [[S2]], ptr [[IN2]], align 4
; CHECK-NEXT:    [[IN3:%.*]] = getelementptr ptr, ptr [[RD0]], i64 4
; CHECK-NEXT:    [[LOAD3:%.*]] = load <2 x ptr>, ptr [[IN3]], align 4
; CHECK-NEXT:    [[P3:%.*]] = icmp ne <2 x ptr> [[LOAD3]], splat (ptr null)
; CHECK-NEXT:    [[S3:%.*]] = select <2 x i1> [[P3]], <2 x ptr> [[LOAD3]], <2 x ptr> splat (ptr null)
; CHECK-NEXT:    store <2 x ptr> [[S3]], ptr [[IN3]], align 4
; CHECK-NEXT:    [[IN4:%.*]] = getelementptr ptr, ptr [[RD0]], i64 6
; CHECK-NEXT:    [[LOAD4:%.*]] = load <2 x ptr>, ptr [[IN4]], align 4
; CHECK-NEXT:    [[P4:%.*]] = icmp ne <2 x ptr> [[LOAD4]], splat (ptr null)
; CHECK-NEXT:    [[S4:%.*]] = select <2 x i1> [[P4]], <2 x ptr> [[LOAD4]], <2 x ptr> splat (ptr null)
; CHECK-NEXT:    store <2 x ptr> [[S4]], ptr [[IN4]], align 4
; CHECK-NEXT:    ret void
;
  %load1 = load <2 x ptr>, ptr %rd0, align 16
  %p1 = icmp ne <2 x ptr> %load1, zeroinitializer
  %s1 = select <2 x i1> %p1, <2 x ptr> %load1, <2 x ptr> zeroinitializer
  store <2 x ptr> %s1, ptr %rd0, align 16
  %in2 = getelementptr ptr, ptr %rd0, i64 2
  %load2 = load <2 x ptr>, ptr %in2, align 4
  %p2 = icmp ne <2 x ptr> %load2, zeroinitializer
  %s2 = select <2 x i1> %p2, <2 x ptr> %load2, <2 x ptr> zeroinitializer
  store <2 x ptr> %s2, ptr %in2, align 4
  %in3 = getelementptr ptr, ptr %rd0, i64 4
  %load3 = load <2 x ptr>, ptr %in3, align 4
  %p3 = icmp ne <2 x ptr> %load3, zeroinitializer
  %s3 = select <2 x i1> %p3, <2 x ptr> %load3, <2 x ptr> zeroinitializer
  store <2 x ptr> %s3, ptr %in3, align 4
  %in4 = getelementptr ptr, ptr %rd0, i64 6
  %load4 = load <2 x ptr>, ptr %in4, align 4
  %p4 = icmp ne <2 x ptr> %load4, zeroinitializer
  %s4 = select <2 x i1> %p4, <2 x ptr> %load4, <2 x ptr> zeroinitializer
  store <2 x ptr> %s4, ptr %in4, align 4
  ret void
}
