; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mtriple=nvptx64-nvidia-cuda -passes=load-store-vectorizer -S < %s | FileCheck %s

; Test that gap filled instructions get deleted if they are not used
%struct.S10 = type { i32, i32, i32, i32 }

; First, confirm that gap instructions get generated and would be vectorized if the alignment is correct
define void @fillTwoGapsCanVectorize(ptr %in) {
; CHECK-LABEL: define void @fillTwoGapsCanVectorize(
; CHECK-SAME: ptr [[IN:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call <4 x b32> @llvm.masked.load.v4b32.p0(ptr align 16 [[IN]], <4 x i1> <i1 true, i1 false, i1 false, i1 true>, <4 x b32> poison)
; CHECK-NEXT:    [[LOAD03:%.*]] = extractelement <4 x b32> [[TMP1]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast b32 [[LOAD03]] to i32
; CHECK-NEXT:    [[GAPFILL4:%.*]] = extractelement <4 x b32> [[TMP1]], i32 1
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast b32 [[GAPFILL4]] to i32
; CHECK-NEXT:    [[GAPFILL25:%.*]] = extractelement <4 x b32> [[TMP1]], i32 2
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast b32 [[GAPFILL25]] to i32
; CHECK-NEXT:    [[LOAD36:%.*]] = extractelement <4 x b32> [[TMP1]], i32 3
; CHECK-NEXT:    [[TMP5:%.*]] = bitcast b32 [[LOAD36]] to i32
; CHECK-NEXT:    ret void
;
  %load0 = load i32, ptr %in, align 16
  %getElem = getelementptr i8, ptr %in, i64 12
  %load3 = load i32, ptr %getElem, align 4
  ret void
}

; Then, confirm that gap instructions get deleted if the alignment prevents the vectorization
define void @fillTwoGapsCantVectorize(ptr %in) {
; CHECK-LABEL: define void @fillTwoGapsCantVectorize(
; CHECK-SAME: ptr [[IN:%.*]]) {
; CHECK-NEXT:    [[LOAD0:%.*]] = load i32, ptr [[IN]], align 4
; CHECK-NEXT:    [[GETELEM:%.*]] = getelementptr i8, ptr [[IN]], i64 12
; CHECK-NEXT:    [[LOAD3:%.*]] = load i32, ptr [[GETELEM]], align 4
; CHECK-NEXT:    ret void
;
  %load0 = load i32, ptr %in, align 4
  %getElem = getelementptr i8, ptr %in, i64 12
  %load3 = load i32, ptr %getElem, align 4
  ret void
}
