; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=powerpc-unknown-linux-gnu %s -o - | FileCheck %s --check-prefixes=CHECK,PPC32
; RUN: llc -mtriple=powerpc64-unknown-linux-gnu %s -o - | FileCheck %s --check-prefixes=CHECK,PPC64

;
; trunc(abs(sub(zext(a),zext(b)))) -> abdu(a,b)
;

define i8 @abd_ext_i8(i8 %a, i8 %b) nounwind {
; PPC32-LABEL: abd_ext_i8:
; PPC32:       # %bb.0:
; PPC32-NEXT:    clrlwi 3, 3, 24
; PPC32-NEXT:    clrlwi 4, 4, 24
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    srawi 4, 3, 31
; PPC32-NEXT:    xor 3, 3, 4
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_ext_i8:
; PPC64:       # %bb.0:
; PPC64-NEXT:    clrlwi 3, 3, 24
; PPC64-NEXT:    clrlwi 4, 4, 24
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    srawi 4, 3, 31
; PPC64-NEXT:    xor 3, 3, 4
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
  %aext = zext i8 %a to i64
  %bext = zext i8 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 false)
  %trunc = trunc i64 %abs to i8
  ret i8 %trunc
}

define i8 @abd_ext_i8_undef(i8 %a, i8 %b) nounwind {
; PPC32-LABEL: abd_ext_i8_undef:
; PPC32:       # %bb.0:
; PPC32-NEXT:    clrlwi 3, 3, 24
; PPC32-NEXT:    clrlwi 4, 4, 24
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    srawi 4, 3, 31
; PPC32-NEXT:    xor 3, 3, 4
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_ext_i8_undef:
; PPC64:       # %bb.0:
; PPC64-NEXT:    clrlwi 3, 3, 24
; PPC64-NEXT:    clrlwi 4, 4, 24
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    srawi 4, 3, 31
; PPC64-NEXT:    xor 3, 3, 4
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
  %aext = zext i8 %a to i64
  %bext = zext i8 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 true)
  %trunc = trunc i64 %abs to i8
  ret i8 %trunc
}

define i16 @abd_ext_i16(i16 %a, i16 %b) nounwind {
; PPC32-LABEL: abd_ext_i16:
; PPC32:       # %bb.0:
; PPC32-NEXT:    clrlwi 3, 3, 16
; PPC32-NEXT:    clrlwi 4, 4, 16
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    srawi 4, 3, 31
; PPC32-NEXT:    xor 3, 3, 4
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_ext_i16:
; PPC64:       # %bb.0:
; PPC64-NEXT:    clrlwi 3, 3, 16
; PPC64-NEXT:    clrlwi 4, 4, 16
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    srawi 4, 3, 31
; PPC64-NEXT:    xor 3, 3, 4
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
  %aext = zext i16 %a to i64
  %bext = zext i16 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 false)
  %trunc = trunc i64 %abs to i16
  ret i16 %trunc
}

define i16 @abd_ext_i16_i32(i16 %a, i32 %b) nounwind {
; PPC32-LABEL: abd_ext_i16_i32:
; PPC32:       # %bb.0:
; PPC32-NEXT:    clrlwi 3, 3, 16
; PPC32-NEXT:    cmplw 3, 4
; PPC32-NEXT:    bgt 0, .LBB3_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    sub 3, 4, 3
; PPC32-NEXT:    blr
; PPC32-NEXT:  .LBB3_2:
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_ext_i16_i32:
; PPC64:       # %bb.0:
; PPC64-NEXT:    clrlwi 3, 3, 16
; PPC64-NEXT:    cmplw 3, 4
; PPC64-NEXT:    bgt 0, .LBB3_2
; PPC64-NEXT:  # %bb.1:
; PPC64-NEXT:    sub 3, 4, 3
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
; PPC64-NEXT:  .LBB3_2:
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
  %aext = zext i16 %a to i64
  %bext = zext i32 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 false)
  %trunc = trunc i64 %abs to i16
  ret i16 %trunc
}

define i16 @abd_ext_i16_undef(i16 %a, i16 %b) nounwind {
; PPC32-LABEL: abd_ext_i16_undef:
; PPC32:       # %bb.0:
; PPC32-NEXT:    clrlwi 3, 3, 16
; PPC32-NEXT:    clrlwi 4, 4, 16
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    srawi 4, 3, 31
; PPC32-NEXT:    xor 3, 3, 4
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_ext_i16_undef:
; PPC64:       # %bb.0:
; PPC64-NEXT:    clrlwi 3, 3, 16
; PPC64-NEXT:    clrlwi 4, 4, 16
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    srawi 4, 3, 31
; PPC64-NEXT:    xor 3, 3, 4
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
  %aext = zext i16 %a to i64
  %bext = zext i16 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 true)
  %trunc = trunc i64 %abs to i16
  ret i16 %trunc
}

define i32 @abd_ext_i32(i32 %a, i32 %b) nounwind {
; PPC32-LABEL: abd_ext_i32:
; PPC32:       # %bb.0:
; PPC32-NEXT:    cmplw 3, 4
; PPC32-NEXT:    bgt 0, .LBB5_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    sub 3, 4, 3
; PPC32-NEXT:    blr
; PPC32-NEXT:  .LBB5_2:
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_ext_i32:
; PPC64:       # %bb.0:
; PPC64-NEXT:    cmplw 3, 4
; PPC64-NEXT:    bgt 0, .LBB5_2
; PPC64-NEXT:  # %bb.1:
; PPC64-NEXT:    sub 3, 4, 3
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
; PPC64-NEXT:  .LBB5_2:
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
  %aext = zext i32 %a to i64
  %bext = zext i32 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 false)
  %trunc = trunc i64 %abs to i32
  ret i32 %trunc
}

define i32 @abd_ext_i32_i16(i32 %a, i16 %b) nounwind {
; PPC32-LABEL: abd_ext_i32_i16:
; PPC32:       # %bb.0:
; PPC32-NEXT:    clrlwi 4, 4, 16
; PPC32-NEXT:    cmplw 3, 4
; PPC32-NEXT:    bgt 0, .LBB6_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    sub 3, 4, 3
; PPC32-NEXT:    blr
; PPC32-NEXT:  .LBB6_2:
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_ext_i32_i16:
; PPC64:       # %bb.0:
; PPC64-NEXT:    clrlwi 4, 4, 16
; PPC64-NEXT:    cmplw 3, 4
; PPC64-NEXT:    bgt 0, .LBB6_2
; PPC64-NEXT:  # %bb.1:
; PPC64-NEXT:    sub 3, 4, 3
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
; PPC64-NEXT:  .LBB6_2:
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
  %aext = zext i32 %a to i64
  %bext = zext i16 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 false)
  %trunc = trunc i64 %abs to i32
  ret i32 %trunc
}

define i32 @abd_ext_i32_undef(i32 %a, i32 %b) nounwind {
; PPC32-LABEL: abd_ext_i32_undef:
; PPC32:       # %bb.0:
; PPC32-NEXT:    cmplw 3, 4
; PPC32-NEXT:    bgt 0, .LBB7_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    sub 3, 4, 3
; PPC32-NEXT:    blr
; PPC32-NEXT:  .LBB7_2:
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_ext_i32_undef:
; PPC64:       # %bb.0:
; PPC64-NEXT:    cmplw 3, 4
; PPC64-NEXT:    bgt 0, .LBB7_2
; PPC64-NEXT:  # %bb.1:
; PPC64-NEXT:    sub 3, 4, 3
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
; PPC64-NEXT:  .LBB7_2:
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
  %aext = zext i32 %a to i64
  %bext = zext i32 %b to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 true)
  %trunc = trunc i64 %abs to i32
  ret i32 %trunc
}

define i64 @abd_ext_i64(i64 %a, i64 %b) nounwind {
; PPC32-LABEL: abd_ext_i64:
; PPC32:       # %bb.0:
; PPC32-NEXT:    subc 4, 4, 6
; PPC32-NEXT:    li 7, 0
; PPC32-NEXT:    subfe 3, 5, 3
; PPC32-NEXT:    addze. 5, 7
; PPC32-NEXT:    li 5, -1
; PPC32-NEXT:    bc 12, 2, .LBB8_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    li 5, 0
; PPC32-NEXT:  .LBB8_2:
; PPC32-NEXT:    xor 4, 4, 5
; PPC32-NEXT:    xor 3, 3, 5
; PPC32-NEXT:    subc 4, 4, 5
; PPC32-NEXT:    subfe 3, 5, 3
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_ext_i64:
; PPC64:       # %bb.0:
; PPC64-NEXT:    cmpld 3, 4
; PPC64-NEXT:    bgt 0, .LBB8_2
; PPC64-NEXT:  # %bb.1:
; PPC64-NEXT:    sub 3, 4, 3
; PPC64-NEXT:    blr
; PPC64-NEXT:  .LBB8_2:
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    blr
  %aext = zext i64 %a to i128
  %bext = zext i64 %b to i128
  %sub = sub i128 %aext, %bext
  %abs = call i128 @llvm.abs.i128(i128 %sub, i1 false)
  %trunc = trunc i128 %abs to i64
  ret i64 %trunc
}

define i64 @abd_ext_i64_undef(i64 %a, i64 %b) nounwind {
; PPC32-LABEL: abd_ext_i64_undef:
; PPC32:       # %bb.0:
; PPC32-NEXT:    subc 4, 4, 6
; PPC32-NEXT:    li 7, 0
; PPC32-NEXT:    subfe 3, 5, 3
; PPC32-NEXT:    addze. 5, 7
; PPC32-NEXT:    li 5, -1
; PPC32-NEXT:    bc 12, 2, .LBB9_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    li 5, 0
; PPC32-NEXT:  .LBB9_2:
; PPC32-NEXT:    xor 4, 4, 5
; PPC32-NEXT:    xor 3, 3, 5
; PPC32-NEXT:    subc 4, 4, 5
; PPC32-NEXT:    subfe 3, 5, 3
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_ext_i64_undef:
; PPC64:       # %bb.0:
; PPC64-NEXT:    cmpld 3, 4
; PPC64-NEXT:    bgt 0, .LBB9_2
; PPC64-NEXT:  # %bb.1:
; PPC64-NEXT:    sub 3, 4, 3
; PPC64-NEXT:    blr
; PPC64-NEXT:  .LBB9_2:
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    blr
  %aext = zext i64 %a to i128
  %bext = zext i64 %b to i128
  %sub = sub i128 %aext, %bext
  %abs = call i128 @llvm.abs.i128(i128 %sub, i1 true)
  %trunc = trunc i128 %abs to i64
  ret i64 %trunc
}

define i128 @abd_ext_i128(i128 %a, i128 %b) nounwind {
; PPC32-LABEL: abd_ext_i128:
; PPC32:       # %bb.0:
; PPC32-NEXT:    subc 6, 6, 10
; PPC32-NEXT:    subfe 5, 9, 5
; PPC32-NEXT:    subfe 4, 8, 4
; PPC32-NEXT:    li 11, 0
; PPC32-NEXT:    subfe 3, 7, 3
; PPC32-NEXT:    addze. 7, 11
; PPC32-NEXT:    li 7, -1
; PPC32-NEXT:    bc 12, 2, .LBB10_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    li 7, 0
; PPC32-NEXT:  .LBB10_2:
; PPC32-NEXT:    xor 6, 6, 7
; PPC32-NEXT:    xor 5, 5, 7
; PPC32-NEXT:    subc 6, 6, 7
; PPC32-NEXT:    xor 4, 4, 7
; PPC32-NEXT:    subfe 5, 7, 5
; PPC32-NEXT:    xor 3, 3, 7
; PPC32-NEXT:    subfe 4, 7, 4
; PPC32-NEXT:    subfe 3, 7, 3
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_ext_i128:
; PPC64:       # %bb.0:
; PPC64-NEXT:    subc 4, 4, 6
; PPC64-NEXT:    li 7, 0
; PPC64-NEXT:    subfe 3, 5, 3
; PPC64-NEXT:    addze 5, 7
; PPC64-NEXT:    addic 5, 5, -1
; PPC64-NEXT:    subfe 5, 5, 5
; PPC64-NEXT:    xor 4, 4, 5
; PPC64-NEXT:    xor 3, 3, 5
; PPC64-NEXT:    subc 4, 4, 5
; PPC64-NEXT:    subfe 3, 5, 3
; PPC64-NEXT:    blr
  %aext = zext i128 %a to i256
  %bext = zext i128 %b to i256
  %sub = sub i256 %aext, %bext
  %abs = call i256 @llvm.abs.i256(i256 %sub, i1 false)
  %trunc = trunc i256 %abs to i128
  ret i128 %trunc
}

define i128 @abd_ext_i128_undef(i128 %a, i128 %b) nounwind {
; PPC32-LABEL: abd_ext_i128_undef:
; PPC32:       # %bb.0:
; PPC32-NEXT:    subc 6, 6, 10
; PPC32-NEXT:    subfe 5, 9, 5
; PPC32-NEXT:    subfe 4, 8, 4
; PPC32-NEXT:    li 11, 0
; PPC32-NEXT:    subfe 3, 7, 3
; PPC32-NEXT:    addze. 7, 11
; PPC32-NEXT:    li 7, -1
; PPC32-NEXT:    bc 12, 2, .LBB11_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    li 7, 0
; PPC32-NEXT:  .LBB11_2:
; PPC32-NEXT:    xor 6, 6, 7
; PPC32-NEXT:    xor 5, 5, 7
; PPC32-NEXT:    subc 6, 6, 7
; PPC32-NEXT:    xor 4, 4, 7
; PPC32-NEXT:    subfe 5, 7, 5
; PPC32-NEXT:    xor 3, 3, 7
; PPC32-NEXT:    subfe 4, 7, 4
; PPC32-NEXT:    subfe 3, 7, 3
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_ext_i128_undef:
; PPC64:       # %bb.0:
; PPC64-NEXT:    subc 4, 4, 6
; PPC64-NEXT:    li 7, 0
; PPC64-NEXT:    subfe 3, 5, 3
; PPC64-NEXT:    addze 5, 7
; PPC64-NEXT:    addic 5, 5, -1
; PPC64-NEXT:    subfe 5, 5, 5
; PPC64-NEXT:    xor 4, 4, 5
; PPC64-NEXT:    xor 3, 3, 5
; PPC64-NEXT:    subc 4, 4, 5
; PPC64-NEXT:    subfe 3, 5, 3
; PPC64-NEXT:    blr
  %aext = zext i128 %a to i256
  %bext = zext i128 %b to i256
  %sub = sub i256 %aext, %bext
  %abs = call i256 @llvm.abs.i256(i256 %sub, i1 true)
  %trunc = trunc i256 %abs to i128
  ret i128 %trunc
}

;
define i4 @abd_ext_i4_to_i8(i4 %a, i4 %b) nounwind {
; PPC32-LABEL: abd_ext_i4_to_i8:
; PPC32:       # %bb.0:
; PPC32-NEXT:    clrlwi 3, 3, 28
; PPC32-NEXT:    clrlwi 4, 4, 28
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    srawi 4, 3, 31
; PPC32-NEXT:    xor 3, 3, 4
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_ext_i4_to_i8:
; PPC64:       # %bb.0:
; PPC64-NEXT:    clrlwi 3, 3, 28
; PPC64-NEXT:    clrlwi 4, 4, 28
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    srawi 4, 3, 31
; PPC64-NEXT:    xor 3, 3, 4
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
  %aext = zext i4 %a to i8
  %bext = zext i4 %b to i8
  %sub = sub i8 %aext, %bext
  %abs = call i8 @llvm.abs.i8(i8 %sub, i1 false)
  %trunc = trunc i8 %abs to i4
  ret i4 %trunc
}

define i8 @abd_ext_i8_to_i16(i8 %a, i8 %b) nounwind {
; PPC32-LABEL: abd_ext_i8_to_i16:
; PPC32:       # %bb.0:
; PPC32-NEXT:    clrlwi 3, 3, 24
; PPC32-NEXT:    clrlwi 4, 4, 24
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    srawi 4, 3, 31
; PPC32-NEXT:    xor 3, 3, 4
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_ext_i8_to_i16:
; PPC64:       # %bb.0:
; PPC64-NEXT:    clrlwi 3, 3, 24
; PPC64-NEXT:    clrlwi 4, 4, 24
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    srawi 4, 3, 31
; PPC64-NEXT:    xor 3, 3, 4
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
  %aext = zext i8 %a to i16
  %bext = zext i8 %b to i16
  %sub = sub i16 %aext, %bext
  %abs = call i16 @llvm.abs.i16(i16 %sub, i1 false)
  %trunc = trunc i16 %abs to i8
  ret i8 %trunc
}

define i16 @abd_ext_i16_to_i32(i16 %a, i16 %b) nounwind {
; PPC32-LABEL: abd_ext_i16_to_i32:
; PPC32:       # %bb.0:
; PPC32-NEXT:    clrlwi 3, 3, 16
; PPC32-NEXT:    clrlwi 4, 4, 16
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    srawi 4, 3, 31
; PPC32-NEXT:    xor 3, 3, 4
; PPC32-NEXT:    sub 3, 3, 4
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_ext_i16_to_i32:
; PPC64:       # %bb.0:
; PPC64-NEXT:    clrlwi 3, 3, 16
; PPC64-NEXT:    clrlwi 4, 4, 16
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    srawi 4, 3, 31
; PPC64-NEXT:    xor 3, 3, 4
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
  %aext = zext i16 %a to i32
  %bext = zext i16 %b to i32
  %sub = sub i32 %aext, %bext
  %abs = call i32 @llvm.abs.i32(i32 %sub, i1 false)
  %trunc = trunc i32 %abs to i16
  ret i16 %trunc
}

; sub(umin(a,b),umax(a,b)) -> abdu(a,b)
;

define i8 @abd_minmax_i8(i8 %a, i8 %b) nounwind {
; CHECK-LABEL: abd_minmax_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    clrlwi 3, 3, 24
; CHECK-NEXT:    clrlwi 4, 4, 24
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    srawi 4, 3, 31
; CHECK-NEXT:    xor 3, 3, 4
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    blr
  %min = call i8 @llvm.umin.i8(i8 %a, i8 %b)
  %max = call i8 @llvm.umax.i8(i8 %a, i8 %b)
  %sub = sub i8 %max, %min
  ret i8 %sub
}

define i16 @abd_minmax_i16(i16 %a, i16 %b) nounwind {
; CHECK-LABEL: abd_minmax_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    clrlwi 3, 3, 16
; CHECK-NEXT:    clrlwi 4, 4, 16
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    srawi 4, 3, 31
; CHECK-NEXT:    xor 3, 3, 4
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    blr
  %min = call i16 @llvm.umin.i16(i16 %a, i16 %b)
  %max = call i16 @llvm.umax.i16(i16 %a, i16 %b)
  %sub = sub i16 %max, %min
  ret i16 %sub
}

define i32 @abd_minmax_i32(i32 %a, i32 %b) nounwind {
; CHECK-LABEL: abd_minmax_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmplw 3, 4
; CHECK-NEXT:    bgt 0, .LBB14_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sub 3, 4, 3
; CHECK-NEXT:    blr
; CHECK-NEXT:  .LBB14_2:
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    blr
  %min = call i32 @llvm.umin.i32(i32 %a, i32 %b)
  %max = call i32 @llvm.umax.i32(i32 %a, i32 %b)
  %sub = sub i32 %max, %min
  ret i32 %sub
}

define i64 @abd_minmax_i64(i64 %a, i64 %b) nounwind {
; PPC32-LABEL: abd_minmax_i64:
; PPC32:       # %bb.0:
; PPC32-NEXT:    subc 4, 4, 6
; PPC32-NEXT:    li 7, 0
; PPC32-NEXT:    subfe 3, 5, 3
; PPC32-NEXT:    addze. 5, 7
; PPC32-NEXT:    li 5, -1
; PPC32-NEXT:    bc 12, 2, .LBB15_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    li 5, 0
; PPC32-NEXT:  .LBB15_2:
; PPC32-NEXT:    xor 4, 4, 5
; PPC32-NEXT:    xor 3, 3, 5
; PPC32-NEXT:    subc 4, 4, 5
; PPC32-NEXT:    subfe 3, 5, 3
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_minmax_i64:
; PPC64:       # %bb.0:
; PPC64-NEXT:    cmpld 3, 4
; PPC64-NEXT:    bgt 0, .LBB15_2
; PPC64-NEXT:  # %bb.1:
; PPC64-NEXT:    sub 3, 4, 3
; PPC64-NEXT:    blr
; PPC64-NEXT:  .LBB15_2:
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    blr
  %min = call i64 @llvm.umin.i64(i64 %a, i64 %b)
  %max = call i64 @llvm.umax.i64(i64 %a, i64 %b)
  %sub = sub i64 %max, %min
  ret i64 %sub
}

define i128 @abd_minmax_i128(i128 %a, i128 %b) nounwind {
; PPC32-LABEL: abd_minmax_i128:
; PPC32:       # %bb.0:
; PPC32-NEXT:    subc 6, 6, 10
; PPC32-NEXT:    subfe 5, 9, 5
; PPC32-NEXT:    subfe 4, 8, 4
; PPC32-NEXT:    li 11, 0
; PPC32-NEXT:    subfe 3, 7, 3
; PPC32-NEXT:    addze. 7, 11
; PPC32-NEXT:    li 7, -1
; PPC32-NEXT:    bc 12, 2, .LBB16_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    li 7, 0
; PPC32-NEXT:  .LBB16_2:
; PPC32-NEXT:    xor 6, 6, 7
; PPC32-NEXT:    xor 5, 5, 7
; PPC32-NEXT:    subc 6, 6, 7
; PPC32-NEXT:    xor 4, 4, 7
; PPC32-NEXT:    subfe 5, 7, 5
; PPC32-NEXT:    xor 3, 3, 7
; PPC32-NEXT:    subfe 4, 7, 4
; PPC32-NEXT:    subfe 3, 7, 3
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_minmax_i128:
; PPC64:       # %bb.0:
; PPC64-NEXT:    subc 4, 4, 6
; PPC64-NEXT:    li 7, 0
; PPC64-NEXT:    subfe 3, 5, 3
; PPC64-NEXT:    addze 5, 7
; PPC64-NEXT:    addic 5, 5, -1
; PPC64-NEXT:    subfe 5, 5, 5
; PPC64-NEXT:    xor 4, 4, 5
; PPC64-NEXT:    xor 3, 3, 5
; PPC64-NEXT:    subc 4, 4, 5
; PPC64-NEXT:    subfe 3, 5, 3
; PPC64-NEXT:    blr
  %min = call i128 @llvm.umin.i128(i128 %a, i128 %b)
  %max = call i128 @llvm.umax.i128(i128 %a, i128 %b)
  %sub = sub i128 %max, %min
  ret i128 %sub
}

;
; select(icmp(a,b),sub(a,b),sub(b,a)) -> abdu(a,b)
;

define i8 @abd_cmp_i8(i8 %a, i8 %b) nounwind {
; CHECK-LABEL: abd_cmp_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    clrlwi 3, 3, 24
; CHECK-NEXT:    clrlwi 4, 4, 24
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    srawi 4, 3, 31
; CHECK-NEXT:    xor 3, 3, 4
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    blr
  %cmp = icmp ugt i8 %a, %b
  %ab = sub i8 %a, %b
  %ba = sub i8 %b, %a
  %sel = select i1 %cmp, i8 %ab, i8 %ba
  ret i8 %sel
}

define i16 @abd_cmp_i16(i16 %a, i16 %b) nounwind {
; CHECK-LABEL: abd_cmp_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    clrlwi 3, 3, 16
; CHECK-NEXT:    clrlwi 4, 4, 16
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    srawi 4, 3, 31
; CHECK-NEXT:    xor 3, 3, 4
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    blr
  %cmp = icmp uge i16 %a, %b
  %ab = sub i16 %a, %b
  %ba = sub i16 %b, %a
  %sel = select i1 %cmp, i16 %ab, i16 %ba
  ret i16 %sel
}

define i32 @abd_cmp_i32(i32 %a, i32 %b) nounwind {
; CHECK-LABEL: abd_cmp_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmplw 3, 4
; CHECK-NEXT:    bgt 0, .LBB19_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sub 3, 4, 3
; CHECK-NEXT:    blr
; CHECK-NEXT:  .LBB19_2:
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    blr
  %cmp = icmp ult i32 %a, %b
  %ab = sub i32 %a, %b
  %ba = sub i32 %b, %a
  %sel = select i1 %cmp, i32 %ba, i32 %ab
  ret i32 %sel
}

define i64 @abd_cmp_i64(i64 %a, i64 %b) nounwind {
; PPC32-LABEL: abd_cmp_i64:
; PPC32:       # %bb.0:
; PPC32-NEXT:    subc 4, 4, 6
; PPC32-NEXT:    li 7, 0
; PPC32-NEXT:    subfe 3, 5, 3
; PPC32-NEXT:    addze. 5, 7
; PPC32-NEXT:    li 5, -1
; PPC32-NEXT:    bc 12, 2, .LBB20_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    li 5, 0
; PPC32-NEXT:  .LBB20_2:
; PPC32-NEXT:    xor 4, 4, 5
; PPC32-NEXT:    xor 3, 3, 5
; PPC32-NEXT:    subc 4, 4, 5
; PPC32-NEXT:    subfe 3, 5, 3
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_cmp_i64:
; PPC64:       # %bb.0:
; PPC64-NEXT:    cmpld 3, 4
; PPC64-NEXT:    bgt 0, .LBB20_2
; PPC64-NEXT:  # %bb.1:
; PPC64-NEXT:    sub 3, 4, 3
; PPC64-NEXT:    blr
; PPC64-NEXT:  .LBB20_2:
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    blr
  %cmp = icmp uge i64 %a, %b
  %ab = sub i64 %a, %b
  %ba = sub i64 %b, %a
  %sel = select i1 %cmp, i64 %ab, i64 %ba
  ret i64 %sel
}

define i128 @abd_cmp_i128(i128 %a, i128 %b) nounwind {
; PPC32-LABEL: abd_cmp_i128:
; PPC32:       # %bb.0:
; PPC32-NEXT:    subc 6, 6, 10
; PPC32-NEXT:    subfe 5, 9, 5
; PPC32-NEXT:    subfe 4, 8, 4
; PPC32-NEXT:    li 11, 0
; PPC32-NEXT:    subfe 3, 7, 3
; PPC32-NEXT:    addze. 7, 11
; PPC32-NEXT:    li 7, -1
; PPC32-NEXT:    bc 12, 2, .LBB21_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    li 7, 0
; PPC32-NEXT:  .LBB21_2:
; PPC32-NEXT:    xor 6, 6, 7
; PPC32-NEXT:    xor 5, 5, 7
; PPC32-NEXT:    subc 6, 6, 7
; PPC32-NEXT:    xor 4, 4, 7
; PPC32-NEXT:    subfe 5, 7, 5
; PPC32-NEXT:    xor 3, 3, 7
; PPC32-NEXT:    subfe 4, 7, 4
; PPC32-NEXT:    subfe 3, 7, 3
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_cmp_i128:
; PPC64:       # %bb.0:
; PPC64-NEXT:    subc 4, 4, 6
; PPC64-NEXT:    li 7, 0
; PPC64-NEXT:    subfe 3, 5, 3
; PPC64-NEXT:    addze 5, 7
; PPC64-NEXT:    addic 5, 5, -1
; PPC64-NEXT:    subfe 5, 5, 5
; PPC64-NEXT:    xor 4, 4, 5
; PPC64-NEXT:    xor 3, 3, 5
; PPC64-NEXT:    subc 4, 4, 5
; PPC64-NEXT:    subfe 3, 5, 3
; PPC64-NEXT:    blr
  %cmp = icmp uge i128 %a, %b
  %ab = sub i128 %a, %b
  %ba = sub i128 %b, %a
  %sel = select i1 %cmp, i128 %ab, i128 %ba
  ret i128 %sel
}

;
; sub(select(icmp(a,b),a,b),select(icmp(a,b),b,a)) -> abdu(a,b)
;

define i8 @abd_select_i8(i8 %a, i8 %b) nounwind {
; CHECK-LABEL: abd_select_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    clrlwi 3, 3, 24
; CHECK-NEXT:    clrlwi 4, 4, 24
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    srawi 4, 3, 31
; CHECK-NEXT:    xor 3, 3, 4
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    blr
  %cmp = icmp ult i8 %a, %b
  %ab = select i1 %cmp, i8 %a, i8 %b
  %ba = select i1 %cmp, i8 %b, i8 %a
  %sub = sub i8 %ba, %ab
  ret i8 %sub
}

define i16 @abd_select_i16(i16 %a, i16 %b) nounwind {
; CHECK-LABEL: abd_select_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    clrlwi 3, 3, 16
; CHECK-NEXT:    clrlwi 4, 4, 16
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    srawi 4, 3, 31
; CHECK-NEXT:    xor 3, 3, 4
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    blr
  %cmp = icmp ule i16 %a, %b
  %ab = select i1 %cmp, i16 %a, i16 %b
  %ba = select i1 %cmp, i16 %b, i16 %a
  %sub = sub i16 %ba, %ab
  ret i16 %sub
}

define i32 @abd_select_i32(i32 %a, i32 %b) nounwind {
; CHECK-LABEL: abd_select_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmplw 3, 4
; CHECK-NEXT:    bgt 0, .LBB24_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sub 3, 4, 3
; CHECK-NEXT:    blr
; CHECK-NEXT:  .LBB24_2:
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    blr
  %cmp = icmp ugt i32 %a, %b
  %ab = select i1 %cmp, i32 %a, i32 %b
  %ba = select i1 %cmp, i32 %b, i32 %a
  %sub = sub i32 %ab, %ba
  ret i32 %sub
}

define i64 @abd_select_i64(i64 %a, i64 %b) nounwind {
; PPC32-LABEL: abd_select_i64:
; PPC32:       # %bb.0:
; PPC32-NEXT:    subc 4, 4, 6
; PPC32-NEXT:    li 7, 0
; PPC32-NEXT:    subfe 3, 5, 3
; PPC32-NEXT:    addze. 5, 7
; PPC32-NEXT:    li 5, -1
; PPC32-NEXT:    bc 12, 2, .LBB25_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    li 5, 0
; PPC32-NEXT:  .LBB25_2:
; PPC32-NEXT:    xor 4, 4, 5
; PPC32-NEXT:    xor 3, 3, 5
; PPC32-NEXT:    subc 4, 4, 5
; PPC32-NEXT:    subfe 3, 5, 3
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_select_i64:
; PPC64:       # %bb.0:
; PPC64-NEXT:    cmpld 3, 4
; PPC64-NEXT:    bgt 0, .LBB25_2
; PPC64-NEXT:  # %bb.1:
; PPC64-NEXT:    sub 3, 4, 3
; PPC64-NEXT:    blr
; PPC64-NEXT:  .LBB25_2:
; PPC64-NEXT:    sub 3, 3, 4
; PPC64-NEXT:    blr
  %cmp = icmp uge i64 %a, %b
  %ab = select i1 %cmp, i64 %a, i64 %b
  %ba = select i1 %cmp, i64 %b, i64 %a
  %sub = sub i64 %ab, %ba
  ret i64 %sub
}

define i128 @abd_select_i128(i128 %a, i128 %b) nounwind {
; PPC32-LABEL: abd_select_i128:
; PPC32:       # %bb.0:
; PPC32-NEXT:    subc 6, 6, 10
; PPC32-NEXT:    subfe 5, 9, 5
; PPC32-NEXT:    subfe 4, 8, 4
; PPC32-NEXT:    li 11, 0
; PPC32-NEXT:    subfe 3, 7, 3
; PPC32-NEXT:    addze. 7, 11
; PPC32-NEXT:    li 7, -1
; PPC32-NEXT:    bc 12, 2, .LBB26_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    li 7, 0
; PPC32-NEXT:  .LBB26_2:
; PPC32-NEXT:    xor 6, 6, 7
; PPC32-NEXT:    xor 5, 5, 7
; PPC32-NEXT:    subc 6, 6, 7
; PPC32-NEXT:    xor 4, 4, 7
; PPC32-NEXT:    subfe 5, 7, 5
; PPC32-NEXT:    xor 3, 3, 7
; PPC32-NEXT:    subfe 4, 7, 4
; PPC32-NEXT:    subfe 3, 7, 3
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_select_i128:
; PPC64:       # %bb.0:
; PPC64-NEXT:    subc 4, 4, 6
; PPC64-NEXT:    li 7, 0
; PPC64-NEXT:    subfe 3, 5, 3
; PPC64-NEXT:    addze 5, 7
; PPC64-NEXT:    addic 5, 5, -1
; PPC64-NEXT:    subfe 5, 5, 5
; PPC64-NEXT:    xor 4, 4, 5
; PPC64-NEXT:    xor 3, 3, 5
; PPC64-NEXT:    subc 4, 4, 5
; PPC64-NEXT:    subfe 3, 5, 3
; PPC64-NEXT:    blr
  %cmp = icmp ult i128 %a, %b
  %ab = select i1 %cmp, i128 %a, i128 %b
  %ba = select i1 %cmp, i128 %b, i128 %a
  %sub = sub i128 %ba, %ab
  ret i128 %sub
}

;
; Operand is guaranteed non-zero: -(x | 1) cannot be 0
;

define i32 @abd_nonzero_rhs_i32(i32 %a, i32 %b) nounwind {
; PPC32-LABEL: abd_nonzero_rhs_i32:
; PPC32:       # %bb.0:
; PPC32-NEXT:    ori 4, 4, 1
; PPC32-NEXT:    neg 5, 4
; PPC32-NEXT:    cmplw 5, 3
; PPC32-NEXT:    blt 0, .LBB27_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    sub 3, 5, 3
; PPC32-NEXT:    blr
; PPC32-NEXT:  .LBB27_2:
; PPC32-NEXT:    add 3, 3, 4
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_nonzero_rhs_i32:
; PPC64:       # %bb.0:
; PPC64-NEXT:    ori 4, 4, 1
; PPC64-NEXT:    neg 5, 4
; PPC64-NEXT:    cmplw 5, 3
; PPC64-NEXT:    blt 0, .LBB27_2
; PPC64-NEXT:  # %bb.1:
; PPC64-NEXT:    sub 3, 5, 3
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
; PPC64-NEXT:  .LBB27_2:
; PPC64-NEXT:    add 3, 3, 4
; PPC64-NEXT:    clrldi 3, 3, 32
; PPC64-NEXT:    blr
  %b1 = or i32 %b, 1
  %nb = sub i32 0, %b1
  %aext = zext i32 %a to i64
  %bext = zext i32 %nb to i64
  %sub = sub i64 %aext, %bext
  %abs = call i64 @llvm.abs.i64(i64 %sub, i1 false)
  %trunc = trunc i64 %abs to i32
  ret i32 %trunc
}

define i64 @abd_nonzero_rhs_i64(i64 %a, i64 %b) nounwind {
; PPC32-LABEL: abd_nonzero_rhs_i64:
; PPC32:       # %bb.0:
; PPC32-NEXT:    ori 6, 6, 1
; PPC32-NEXT:    subfic 6, 6, 0
; PPC32-NEXT:    subfze 5, 5
; PPC32-NEXT:    subc 4, 4, 6
; PPC32-NEXT:    li 7, 0
; PPC32-NEXT:    subfe 3, 5, 3
; PPC32-NEXT:    addze. 5, 7
; PPC32-NEXT:    li 5, -1
; PPC32-NEXT:    bc 12, 2, .LBB28_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    li 5, 0
; PPC32-NEXT:  .LBB28_2:
; PPC32-NEXT:    xor 4, 4, 5
; PPC32-NEXT:    xor 3, 3, 5
; PPC32-NEXT:    subc 4, 4, 5
; PPC32-NEXT:    subfe 3, 5, 3
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_nonzero_rhs_i64:
; PPC64:       # %bb.0:
; PPC64-NEXT:    ori 4, 4, 1
; PPC64-NEXT:    neg 5, 4
; PPC64-NEXT:    cmpld 5, 3
; PPC64-NEXT:    blt 0, .LBB28_2
; PPC64-NEXT:  # %bb.1:
; PPC64-NEXT:    sub 3, 5, 3
; PPC64-NEXT:    blr
; PPC64-NEXT:  .LBB28_2:
; PPC64-NEXT:    add 3, 3, 4
; PPC64-NEXT:    blr
  %b1 = or i64 %b, 1
  %nb = sub i64 0, %b1
  %aext = zext i64 %a to i128
  %bext = zext i64 %nb to i128
  %sub = sub i128 %aext, %bext
  %abs = call i128 @llvm.abs.i128(i128 %sub, i1 false)
  %trunc = trunc i128 %abs to i64
  ret i64 %trunc
}

define i32 @abd_nonzero_rhs_i32_select(i32 %a, i32 %b) nounwind {
; CHECK-LABEL: abd_nonzero_rhs_i32_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori 4, 4, 1
; CHECK-NEXT:    neg 5, 4
; CHECK-NEXT:    cmplw 5, 3
; CHECK-NEXT:    blt 0, .LBB29_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sub 3, 5, 3
; CHECK-NEXT:    blr
; CHECK-NEXT:  .LBB29_2:
; CHECK-NEXT:    add 3, 3, 4
; CHECK-NEXT:    blr
  %b1 = or i32 %b, 1
  %nb = sub i32 0, %b1
  %cmp = icmp ugt i32 %a, %nb
  %ab = sub i32 %a, %nb
  %ba = sub i32 %nb, %a
  %sel = select i1 %cmp, i32 %ab, i32 %ba
  ret i32 %sel
}

define i64 @abd_nonzero_rhs_i64_select(i64 %a, i64 %b) nounwind {
; PPC32-LABEL: abd_nonzero_rhs_i64_select:
; PPC32:       # %bb.0:
; PPC32-NEXT:    ori 6, 6, 1
; PPC32-NEXT:    subfic 6, 6, 0
; PPC32-NEXT:    subfze 5, 5
; PPC32-NEXT:    subc 4, 4, 6
; PPC32-NEXT:    li 7, 0
; PPC32-NEXT:    subfe 3, 5, 3
; PPC32-NEXT:    addze. 5, 7
; PPC32-NEXT:    li 5, -1
; PPC32-NEXT:    bc 12, 2, .LBB30_2
; PPC32-NEXT:  # %bb.1:
; PPC32-NEXT:    li 5, 0
; PPC32-NEXT:  .LBB30_2:
; PPC32-NEXT:    xor 4, 4, 5
; PPC32-NEXT:    xor 3, 3, 5
; PPC32-NEXT:    subc 4, 4, 5
; PPC32-NEXT:    subfe 3, 5, 3
; PPC32-NEXT:    blr
;
; PPC64-LABEL: abd_nonzero_rhs_i64_select:
; PPC64:       # %bb.0:
; PPC64-NEXT:    ori 4, 4, 1
; PPC64-NEXT:    neg 5, 4
; PPC64-NEXT:    cmpld 5, 3
; PPC64-NEXT:    blt 0, .LBB30_2
; PPC64-NEXT:  # %bb.1:
; PPC64-NEXT:    sub 3, 5, 3
; PPC64-NEXT:    blr
; PPC64-NEXT:  .LBB30_2:
; PPC64-NEXT:    add 3, 3, 4
; PPC64-NEXT:    blr
  %b1 = or i64 %b, 1
  %nb = sub i64 0, %b1
  %cmp = icmp ugt i64 %a, %nb
  %ab = sub i64 %a, %nb
  %ba = sub i64 %nb, %a
  %sel = select i1 %cmp, i64 %ab, i64 %ba
  ret i64 %sel
}

declare i8 @llvm.abs.i8(i8, i1)
declare i16 @llvm.abs.i16(i16, i1)
declare i32 @llvm.abs.i32(i32, i1)
declare i64 @llvm.abs.i64(i64, i1)
declare i128 @llvm.abs.i128(i128, i1)

declare i8 @llvm.umax.i8(i8, i8)
declare i16 @llvm.umax.i16(i16, i16)
declare i32 @llvm.umax.i32(i32, i32)
declare i64 @llvm.umax.i64(i64, i64)

declare i8 @llvm.umin.i8(i8, i8)
declare i16 @llvm.umin.i16(i16, i16)
declare i32 @llvm.umin.i32(i32, i32)
declare i64 @llvm.umin.i64(i64, i64)
