; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=powerpc64-linux-gnu -o - < %s | FileCheck %s

define i64 @absdiff(i64 %0, i64 %1) {
; CHECK-LABEL: absdiff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sub 5, 3, 4
; CHECK-NEXT:    sub 6, 4, 3
; CHECK-NEXT:    cmpld 3, 4
; CHECK-NEXT:    bc 12, 0, .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    ori 3, 5, 0
; CHECK-NEXT:    blr
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    addi 3, 6, 0
; CHECK-NEXT:    blr
  %3 = icmp ult i64 %0, %1
  %4 = sub i64 %0, %1
  %5 = sub i64 %1, %0
  %6 = select i1 %3, i64 %5, i64 %4
  ret i64 %6
}

define i64 @absdiff1(i64 %0, i64 %1) {
; CHECK-LABEL: absdiff1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subc 5, 3, 4
; CHECK-NEXT:    subfe 5, 3, 3
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    xor 3, 3, 5
; CHECK-NEXT:    sub 3, 3, 5
; CHECK-NEXT:    blr
  %3 = icmp ult i64 %0, %1
  %4 = sext i1 %3 to i64
  %5 = sub i64 %0, %1
  %6 = xor i64 %5, %4
  %7 = sub i64 %6, %4
  ret i64 %7
}

define i64 @absdiff2(i64 %0, i64 %1) {
; CHECK-LABEL: absdiff2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sub 5, 3, 4
; CHECK-NEXT:    neg 6, 5
; CHECK-NEXT:    cmpld 3, 4
; CHECK-NEXT:    bc 12, 0, .LBB2_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    ori 3, 5, 0
; CHECK-NEXT:    blr
; CHECK-NEXT:  .LBB2_2:
; CHECK-NEXT:    addi 3, 6, 0
; CHECK-NEXT:    blr
  %3 = icmp ult i64 %0, %1
  %4 = sub i64 %0, %1
  %5 = sub i64 0, %4
  %6 = select i1 %3, i64 %5, i64 %4
  ret i64 %6
}
