; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Check the default code model for AIX targets.
; RUN: llc -mtriple powerpc-ibm-aix < %s | FileCheck --check-prefixes=CHECK-SMALL %s
; RUN: llc -mtriple powerpc64-ibm-aix < %s | FileCheck --check-prefixes=CHECK-LARGE %s

@e = external global i32, align 4

define i32 @A() local_unnamed_addr {
; CHECK-SMALL-LABEL: A:
; CHECK-SMALL:       # %bb.0: # %entry
; CHECK-SMALL-NEXT:    lwz 3, L..C0(2) # @e
; CHECK-SMALL-NEXT:    lwz 3, 0(3)
; CHECK-SMALL-NEXT:    blr
;
; CHECK-LARGE-LABEL: A:
; CHECK-LARGE:       # %bb.0: # %entry
; CHECK-LARGE-NEXT:    addis 3, L..C0@u(2)
; CHECK-LARGE-NEXT:    ld 3, L..C0@l(3)
; CHECK-LARGE-NEXT:    lwz 3, 0(3)
; CHECK-LARGE-NEXT:    blr
entry:
  %0 = load i32, ptr @e, align 4
  ret i32 %0
}
