; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc  -verify-machineinstrs -mcpu=pwr7 -ppc-asm-full-reg-names \
; RUN:      -mtriple powerpc64-ibm-aix-xcoff < %s \
; RUN:      | FileCheck %s --check-prefix=SMALL-LOCAL-DYNAMIC-SMALLCM64
; RUN: llc  -verify-machineinstrs -mcpu=pwr7 -ppc-asm-full-reg-names \
; RUN:      -mtriple powerpc64-ibm-aix-xcoff --code-model=large \
; RUN:      < %s | FileCheck %s \
; RUN:      --check-prefix=SMALL-LOCAL-DYNAMIC-LARGECM64

; Test disassembly of object.
; RUN: llc -verify-machineinstrs -mcpu=pwr7 \
; RUN:      -mtriple powerpc64-ibm-aix-xcoff -xcoff-traceback-table=false \
; RUN:      --code-model=large -filetype=obj -o %t.o < %s
; RUN: llvm-objdump -D -r --symbol-description %t.o | FileCheck -D#NFA=2 --check-prefix=DIS %s

@mySmallLocalDynamicTLS6 = external thread_local(localdynamic) global [60 x i64], align 8
@mySmallLocalDynamicTLS2 = thread_local(localdynamic) global [3000 x i64] zeroinitializer, align 8
@MyTLSGDVar = thread_local global [800 x i64] zeroinitializer, align 8
@mySmallLocalDynamicTLS3 = thread_local(localdynamic) global [3000 x i64] zeroinitializer, align 8
@mySmallLocalDynamicTLS4 = thread_local(localdynamic) global [3000 x i64] zeroinitializer, align 8
@mySmallLocalDynamicTLS5 = thread_local(localdynamic) global [3000 x i64] zeroinitializer, align 8
@mySmallLocalDynamicTLS = thread_local(localdynamic) local_unnamed_addr global [7800 x i64] zeroinitializer, align 8
declare nonnull ptr @llvm.threadlocal.address.p0(ptr nonnull) #1

; All accesses use a "faster" local-dynamic sequence directly off the thread pointer.
define i64 @StoreLargeAccess1() {
; SMALL-LOCAL-DYNAMIC-SMALLCM64-LABEL: StoreLargeAccess1:
; SMALL-LOCAL-DYNAMIC-SMALLCM64:       # %bb.0: # %entry
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    mflr r0
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    stdu r1, -48(r1)
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    ld r3, L..C0(r2) # target-flags(ppc-tlsldm) @"_$TLSML"
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    std r0, 64(r1)
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    bla .__tls_get_mod[PR]
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    ld r4, L..C1(r2) # target-flags(ppc-tlsld) @mySmallLocalDynamicTLS6
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    mr r6, r3
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    li r3, 212
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    add r4, r6, r4
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    std r3, 424(r4)
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    ld r3, L..C2(r2) # target-flags(ppc-tlsld) @mySmallLocalDynamicTLS2
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    li r4, 203
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    add r3, r6, r3
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    std r4, 1200(r3)
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    ld r3, L..C3(r2) # target-flags(ppc-tlsgdm) @MyTLSGDVar
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    ld r4, L..C4(r2) # target-flags(ppc-tlsgd) @MyTLSGDVar
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    bla .__tls_get_addr[PR]
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    li r4, 44
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    std r4, 440(r3)
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    ld r3, L..C5(r2) # target-flags(ppc-tlsld) @mySmallLocalDynamicTLS3
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    li r4, 6
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    add r3, r6, r3
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    std r4, 2000(r3)
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    ld r4, L..C6(r2) # target-flags(ppc-tlsld) @mySmallLocalDynamicTLS4
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    li r3, 100
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    add r4, r6, r4
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    std r3, 6800(r4)
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    ld r3, L..C7(r2) # target-flags(ppc-tlsld) @mySmallLocalDynamicTLS5
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    li r4, 882
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    add r3, r6, r3
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    std r4, 8400(r3)
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    li r3, 1191
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    addi r1, r1, 48
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    ld r0, 16(r1)
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    mtlr r0
; SMALL-LOCAL-DYNAMIC-SMALLCM64-NEXT:    blr
;
; SMALL-LOCAL-DYNAMIC-LARGECM64-LABEL: StoreLargeAccess1:
; SMALL-LOCAL-DYNAMIC-LARGECM64:       # %bb.0: # %entry
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    mflr r0
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    stdu r1, -48(r1)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    addis r3, L..C0@u(r2)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    std r0, 64(r1)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    addis r7, L..C1@u(r2)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    ld r3, L..C0@l(r3)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    bla .__tls_get_mod[PR]
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    li r4, 212
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    mr r6, r3
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    ld r3, L..C1@l(r7)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    add r3, r6, r3
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    std r4, 424(r3)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    addis r3, L..C2@u(r2)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    li r4, 203
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    ld r3, L..C2@l(r3)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    add r3, r6, r3
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    std r4, 1200(r3)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    addis r3, L..C3@u(r2)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    addis r4, L..C4@u(r2)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    ld r3, L..C3@l(r3)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    ld r4, L..C4@l(r4)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    bla .__tls_get_addr[PR]
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    li r4, 44
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    std r4, 440(r3)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    addis r3, L..C5@u(r2)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    li r4, 6
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    ld r3, L..C5@l(r3)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    add r3, r6, r3
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    std r4, 2000(r3)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    addis r3, L..C6@u(r2)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    li r4, 100
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    ld r3, L..C6@l(r3)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    add r3, r6, r3
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    std r4, 6800(r3)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    addis r3, L..C7@u(r2)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    li r4, 882
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    ld r3, L..C7@l(r3)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    add r3, r6, r3
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    std r4, 8400(r3)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    li r3, 1191
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    addi r1, r1, 48
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    ld r0, 16(r1)
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    mtlr r0
; SMALL-LOCAL-DYNAMIC-LARGECM64-NEXT:    blr
entry:
  %0 = tail call align 8 ptr @llvm.threadlocal.address.p0(ptr align 8 @mySmallLocalDynamicTLS6)
  %arrayidx = getelementptr inbounds [60 x i64], ptr %0, i64 0, i64 53
  store i64 212, ptr %arrayidx, align 8
  %1 = tail call align 8 ptr @llvm.threadlocal.address.p0(ptr align 8 @mySmallLocalDynamicTLS2)
  %arrayidx1 = getelementptr inbounds [3000 x i64], ptr %1, i64 0, i64 150
  store i64 203, ptr %arrayidx1, align 8
  %2 = tail call align 8 ptr @llvm.threadlocal.address.p0(ptr align 8 @MyTLSGDVar)
  %arrayidx2 = getelementptr inbounds [800 x i64], ptr %2, i64 0, i64 55
  store i64 44, ptr %arrayidx2, align 8
  %3 = tail call align 8 ptr @llvm.threadlocal.address.p0(ptr align 8 @mySmallLocalDynamicTLS3)
  %arrayidx3 = getelementptr inbounds [3000 x i64], ptr %3, i64 0, i64 250
  store i64 6, ptr %arrayidx3, align 8
  %4 = tail call align 8 ptr @llvm.threadlocal.address.p0(ptr align 8 @mySmallLocalDynamicTLS4)
  %arrayidx4 = getelementptr inbounds [3000 x i64], ptr %4, i64 0, i64 850
  store i64 100, ptr %arrayidx4, align 8
  %5 = tail call align 8 ptr @llvm.threadlocal.address.p0(ptr align 8 @mySmallLocalDynamicTLS5)
  %arrayidx5 = getelementptr inbounds [3000 x i64], ptr %5, i64 0, i64 1050
  store i64 882, ptr %arrayidx5, align 8
  %6 = load i64, ptr %arrayidx1, align 8
  %7 = load i64, ptr %arrayidx3, align 8
  %8 = load i64, ptr %arrayidx4, align 8
  %add = add i64 %6, 882
  %add9 = add i64 %add, %7
  %add11 = add i64 %add9, %8
  ret i64 %add11
}

; DIS:      0000000000000000 (idx: [[#NFA+9]]) .StoreLargeAccess1:
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                mflr 0
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                stdu 1, -48(1)
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                addis 3, 2, 0
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCU         (idx: [[#NFA+15]]) _$TLSML[TC]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                std 0, 64(1)
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                addis 7, 2, 0
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCU         (idx: [[#NFA+17]]) mySmallLocalDynamicTLS6[TE]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                ld 3, 0(3)
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCL	        (idx: [[#NFA+15]]) _$TLSML[TC]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                bla 0x0
; DIS-NEXT: {{0*}}[[#ADDR]]: R_RBA              (idx: [[#NFA+1]]) .__tls_get_mod[PR]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                li 4, 212
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                mr 6, 3
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                ld 3, 8(7)
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCL	        (idx: [[#NFA+17]]) mySmallLocalDynamicTLS6[TE]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                add 3, 6, 3
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                std 4, 424(3)
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                addis 3, 2, 0
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCU         (idx: [[#NFA+19]]) mySmallLocalDynamicTLS2[TE]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                li 4, 203
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                ld 3, 16(3)
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCL	        (idx: [[#NFA+19]]) mySmallLocalDynamicTLS2[TE]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                add 3, 6, 3
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                std 4, 1200(3)
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                addis 3, 2, 0
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCU         (idx: [[#NFA+21]]) .MyTLSGDVar[TE]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                addis 4, 2, 0
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCU         (idx: [[#NFA+23]]) MyTLSGDVar[TE]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                ld 3, 24(3)
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCL	        (idx: [[#NFA+21]]) .MyTLSGDVar[TE]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                ld 4, 32(4)
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCL	        (idx: [[#NFA+23]]) MyTLSGDVar[TE]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                bla 0x0
; DIS-NEXT: {{0*}}[[#ADDR]]: R_RBA              (idx: [[#NFA+3]]) .__tls_get_addr[PR]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                li 4, 44
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                std 4, 440(3)
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                addis 3, 2, 0
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCU         (idx: [[#NFA+25]]) mySmallLocalDynamicTLS3[TE]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                li 4, 6
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                ld 3, 40(3)
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCL	        (idx: [[#NFA+25]]) mySmallLocalDynamicTLS3[TE]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                add 3, 6, 3
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                std 4, 2000(3)
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                addis 3, 2, 0
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCU         (idx: [[#NFA+27]]) mySmallLocalDynamicTLS4[TE]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                li 4, 100
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                ld 3, 48(3)
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCL	        (idx: [[#NFA+27]]) mySmallLocalDynamicTLS4[TE]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                add 3, 6, 3
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                std 4, 6800(3)
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                addis 3, 2, 0
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCU         (idx: [[#NFA+29]]) mySmallLocalDynamicTLS5[TE]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                li 4, 882
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                ld 3, 56(3)
; DIS-NEXT: {{0*}}[[#ADDR + 2]]: R_TOCL	        (idx: [[#NFA+29]]) mySmallLocalDynamicTLS5[TE]
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                add 3, 6, 3
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                std 4, 8400(3)
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                li 3, 1191
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                addi 1, 1, 48
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                ld 0, 16(1)
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                mtlr 0
; DIS-NEXT: [[#%x, ADDR:]]: {{.*}}                blr

; DIS:      Disassembly of section .data:
; DIS:      00000000000000b0 (idx: [[#NFA+11]]) StoreLargeAccess1[DS]:
; DIS-NEXT:       b0: 00 00 00 00
; DIS-NEXT: 00000000000000b0:  R_POS    (idx: [[#NFA+9]]) .StoreLargeAccess1
; DIS-NEXT:       b4: 00 00 00 00
; DIS-NEXT:       b8: 00 00 00 00
; DIS-NEXT: 00000000000000b8:  R_POS        (idx: [[#NFA+13]]) TOC[TC0]
; DIS-NEXT:       bc: 00 00 00 c8

; DIS:      Disassembly of section .tdata:
; DIS:      0000000000000000 (idx: [[#NFA+31]]) mySmallLocalDynamicTLS2[TL]:
; DIS:      0000000000005dc0 (idx: [[#NFA+33]]) MyTLSGDVar[TL]:
; DIS:      00000000000076c0 (idx: [[#NFA+35]]) mySmallLocalDynamicTLS3[TL]:
; DIS:      000000000000d480 (idx: [[#NFA+37]]) mySmallLocalDynamicTLS4[TL]:
; DIS:      0000000000013240 (idx: [[#NFA+39]]) mySmallLocalDynamicTLS5[TL]:
; DIS:      0000000000019000 (idx: [[#NFA+41]]) mySmallLocalDynamicTLS[TL]:
