; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs < %s -mtriple=powerpc64le-- | FileCheck %s
; https://bugs.llvm.org/show_bug.cgi?id=50608

define dso_local signext i32 @main(i32 signext %argc, ptr %argv) {
; CHECK-LABEL: main:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    stw 3, -4(1)
; CHECK-NEXT:    addi 3, 1, -4
; CHECK-NEXT:    #APP
; CHECK-NEXT:    .ascii "-1@0(3)"
; CHECK-NEXT:    .byte 0
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    li 3, 0
; CHECK-NEXT:    blr
entry:
  call void asm sideeffect " .asciz \22${0:n}@${1:I}$1\22 ", "n,nZr"(i32 1, i32 %argc)
  ret i32 0
}
