; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=powerpc64le -mcpu=pwr10 < %s | FileCheck %s --check-prefix=CHECK-LE
; RUN: llc -mtriple=powerpc64 -mcpu=pwr10 < %s | FileCheck %s --check-prefix=CHECK-BE

; i16 = bitcast(v16i1 truncate(v16i8))
define fastcc <16 x i16> @test_v16i8_to_i16(<16 x i1> %0) {
; CHECK-LE-LABEL: test_v16i8_to_i16:
; CHECK-LE:       # %bb.0: # %Entry
; CHECK-LE-NEXT:    plxv 35, .LCPI0_0@PCREL(0), 1
; CHECK-LE-NEXT:    plxv 1, .LCPI0_1@PCREL(0), 1
; CHECK-LE-NEXT:    li 4, 0
; CHECK-LE-NEXT:    mtfprd 0, 4
; CHECK-LE-NEXT:    vbpermq 2, 2, 3
; CHECK-LE-NEXT:    xxlxor 35, 35, 35
; CHECK-LE-NEXT:    mfvsrwz 3, 34
; CHECK-LE-NEXT:    mtvsrd 34, 3
; CHECK-LE-NEXT:    xxperm 34, 0, 1
; CHECK-LE-NEXT:    blr
;
; CHECK-BE-LABEL: test_v16i8_to_i16:
; CHECK-BE:       # %bb.0: # %Entry
; CHECK-BE-NEXT:    addis 3, 2, .LCPI0_0@toc@ha
; CHECK-BE-NEXT:    addi 3, 3, .LCPI0_0@toc@l
; CHECK-BE-NEXT:    lxv 35, 0(3)
; CHECK-BE-NEXT:    vbpermq 2, 2, 3
; CHECK-BE-NEXT:    xxlxor 35, 35, 35
; CHECK-BE-NEXT:    mfvsrwz 3, 34
; CHECK-BE-NEXT:    mtfprwz 0, 3
; CHECK-BE-NEXT:    addis 3, 2, .LCPI0_1@toc@ha
; CHECK-BE-NEXT:    addi 3, 3, .LCPI0_1@toc@l
; CHECK-BE-NEXT:    lxv 1, 0(3)
; CHECK-BE-NEXT:    li 3, 0
; CHECK-BE-NEXT:    mtvsrwz 34, 3
; CHECK-BE-NEXT:    xxperm 34, 0, 1
; CHECK-BE-NEXT:    blr
Entry:
  %1 = bitcast <16 x i1> %0 to i16
  %2 = insertelement <16 x i16> zeroinitializer, i16 %1, i64 0
  ret <16 x i16> %2
}

; i8 = bitcast(v8i1 truncate(v8i16))
define fastcc <16 x i8> @test_v8i16_to_i8(<8 x i1> %0) {
; CHECK-LE-LABEL: test_v8i16_to_i8:
; CHECK-LE:       # %bb.0: # %Entry
; CHECK-LE-NEXT:    plxv 35, .LCPI1_0@PCREL(0), 1
; CHECK-LE-NEXT:    plxv 1, .LCPI1_1@PCREL(0), 1
; CHECK-LE-NEXT:    li 4, 0
; CHECK-LE-NEXT:    mtfprd 0, 4
; CHECK-LE-NEXT:    vbpermq 2, 2, 3
; CHECK-LE-NEXT:    mfvsrd 3, 34
; CHECK-LE-NEXT:    rldicl 3, 3, 56, 8
; CHECK-LE-NEXT:    mtvsrd 34, 3
; CHECK-LE-NEXT:    xxperm 34, 0, 1
; CHECK-LE-NEXT:    blr
;
; CHECK-BE-LABEL: test_v8i16_to_i8:
; CHECK-BE:       # %bb.0: # %Entry
; CHECK-BE-NEXT:    addis 3, 2, .LCPI1_0@toc@ha
; CHECK-BE-NEXT:    addi 3, 3, .LCPI1_0@toc@l
; CHECK-BE-NEXT:    lxv 35, 0(3)
; CHECK-BE-NEXT:    vbpermq 2, 2, 3
; CHECK-BE-NEXT:    mfvsrd 3, 34
; CHECK-BE-NEXT:    rldicl 3, 3, 56, 8
; CHECK-BE-NEXT:    mtfprwz 0, 3
; CHECK-BE-NEXT:    addis 3, 2, .LCPI1_1@toc@ha
; CHECK-BE-NEXT:    addi 3, 3, .LCPI1_1@toc@l
; CHECK-BE-NEXT:    lxv 1, 0(3)
; CHECK-BE-NEXT:    li 3, 0
; CHECK-BE-NEXT:    mtvsrwz 34, 3
; CHECK-BE-NEXT:    xxperm 34, 0, 1
; CHECK-BE-NEXT:    blr
Entry:
  %2 = bitcast <8 x i1> %0 to i8
  %3 = insertelement <16 x i8> zeroinitializer, i8 %2, i64 0
  ret <16 x i8> %3
}

; i8 = bitcast(v8i1 truncate(v8i8))
define i8 @test_v8i8_to_i8(<8 x i8> %a) {
; CHECK-LE-LABEL: test_v8i8_to_i8:
; CHECK-LE:       # %bb.0:
; CHECK-LE-NEXT:    plxv 35, .LCPI2_0@PCREL(0), 1
; CHECK-LE-NEXT:    vbpermd 2, 2, 3
; CHECK-LE-NEXT:    mfvsrld 3, 34
; CHECK-LE-NEXT:    blr
;
; CHECK-BE-LABEL: test_v8i8_to_i8:
; CHECK-BE:       # %bb.0:
; CHECK-BE-NEXT:    addis 3, 2, .LCPI2_0@toc@ha
; CHECK-BE-NEXT:    addi 3, 3, .LCPI2_0@toc@l
; CHECK-BE-NEXT:    lxv 35, 0(3)
; CHECK-BE-NEXT:    vbpermd 2, 2, 3
; CHECK-BE-NEXT:    mfvsrd 3, 34
; CHECK-BE-NEXT:    blr
  %1 = trunc <8 x i8> %a to <8 x i1>
  %2 = bitcast <8 x i1> %1 to i8
  ret i8 %2
}
