; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs -mtriple=powerpc64le-unknown-linux-gnu \
; RUN:   -mcpu=pwr9 < %s | FileCheck %s
; RUN: llc -verify-machineinstrs -mtriple=powerpc64-unknown-linux-gnu \
; RUN:   -mcpu=pwr9 < %s | FileCheck %s
; RUN: llc -verify-machineinstrs -mtriple=powerpc64-unknown-aix \
; RUN:   -mcpu=pwr9 < %s | FileCheck %s
; RUN: llc -verify-machineinstrs -mtriple=powerpc-unknown-aix \
; RUN:   -mcpu=pwr9 < %s | FileCheck %s --check-prefix=CHECK-32BIT

define dso_local zeroext i32 @extract_exp(double %d) {
; CHECK-LABEL: extract_exp:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xsxexpdp 3, 1
; CHECK-NEXT:    clrldi 3, 3, 32
; CHECK-NEXT:    blr
;
; CHECK-32BIT-LABEL: extract_exp:
; CHECK-32BIT:       # %bb.0: # %entry
; CHECK-32BIT-NEXT:    xsxexpdp 3, 1
; CHECK-32BIT-NEXT:    # kill: def $r3 killed $r3 killed $x3
; CHECK-32BIT-NEXT:    blr
entry:
  %0 = tail call i32 @llvm.ppc.extract.exp(double %d)
  ret i32 %0
}
declare i32 @llvm.ppc.extract.exp(double)
