; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -verify-machineinstrs -mcpu=pwr9 -mtriple=powerpc64le-unknown-linux-gnu \
; RUN:    < %s | FileCheck %s --check-prefix=POWERPC_64LE

; RUN: llc -verify-machineinstrs -mcpu=pwr9 -mtriple=powerpc64-ibm-aix \
; RUN:  < %s | FileCheck %s --check-prefix=POWERPC_64

; RUN: llc -verify-machineinstrs -mcpu=pwr9 -mtriple=powerpc-ibm-aix \
; RUN:   < %s | FileCheck %s --check-prefix=POWERPC_32

define i32 @test_Greater_than(ptr %colauths, i32 signext %ncols) {
; This testcase is manually reduced to isolate the critical code blocks.
; It is designed to check for vector comparison specifically for zero vectors.
; In the vector.body section, we are expecting a comparison instruction (vcmpequh),
; merge instructions (vmrghh and vmrglh) which use exactly 2 vectors.
; The output of the merge instruction is being used by xxland and finally
; accumulated by vadduwm instruction.
; POWERPC_64LE-LABEL: test_Greater_than:
; POWERPC_64LE:       # %bb.0: # %entry
; POWERPC_64LE-NEXT:    cmpwi 4, 0
; POWERPC_64LE-NEXT:    ble 0, .LBB0_3
; POWERPC_64LE-NEXT:  # %bb.1: # %iter.check
; POWERPC_64LE-NEXT:    clrldi 5, 4, 32
; POWERPC_64LE-NEXT:    cmplwi 4, 7
; POWERPC_64LE-NEXT:    bgt 0, .LBB0_4
; POWERPC_64LE-NEXT:  # %bb.2:
; POWERPC_64LE-NEXT:    li 4, 0
; POWERPC_64LE-NEXT:    li 6, 0
; POWERPC_64LE-NEXT:    b .LBB0_12
; POWERPC_64LE-NEXT:  .LBB0_3:
; POWERPC_64LE-NEXT:    li 4, 0
; POWERPC_64LE-NEXT:    mr 3, 4
; POWERPC_64LE-NEXT:    blr
; POWERPC_64LE-NEXT:  .LBB0_4: # %vector.main.loop.iter.check
; POWERPC_64LE-NEXT:    vspltisw 2, 1
; POWERPC_64LE-NEXT:    li 7, 0
; POWERPC_64LE-NEXT:    li 6, 0
; POWERPC_64LE-NEXT:    cmplwi 4, 64
; POWERPC_64LE-NEXT:    li 4, 0
; POWERPC_64LE-NEXT:    blt 0, .LBB0_9
; POWERPC_64LE-NEXT:  # %bb.5: # %vector.ph
; POWERPC_64LE-NEXT:    rlwinm 6, 5, 0, 1, 25
; POWERPC_64LE-NEXT:    addi 4, 3, 64
; POWERPC_64LE-NEXT:    xxlxor 35, 35, 35
; POWERPC_64LE-NEXT:    addi 8, 6, -64
; POWERPC_64LE-NEXT:    xxlxor 36, 36, 36
; POWERPC_64LE-NEXT:    rldicl 8, 8, 58, 6
; POWERPC_64LE-NEXT:    xxlxor 37, 37, 37
; POWERPC_64LE-NEXT:    xxlxor 32, 32, 32
; POWERPC_64LE-NEXT:    xxlxor 39, 39, 39
; POWERPC_64LE-NEXT:    xxlxor 33, 33, 33
; POWERPC_64LE-NEXT:    xxlxor 42, 42, 42
; POWERPC_64LE-NEXT:    xxlxor 40, 40, 40
; POWERPC_64LE-NEXT:    addi 8, 8, 1
; POWERPC_64LE-NEXT:    xxlxor 41, 41, 41
; POWERPC_64LE-NEXT:    mtctr 8
; POWERPC_64LE-NEXT:    xxlxor 38, 38, 38
; POWERPC_64LE-NEXT:    xxlxor 46, 46, 46
; POWERPC_64LE-NEXT:    xxlxor 43, 43, 43
; POWERPC_64LE-NEXT:    xxlxor 44, 44, 44
; POWERPC_64LE-NEXT:    xxlxor 45, 45, 45
; POWERPC_64LE-NEXT:    xxlxor 49, 49, 49
; POWERPC_64LE-NEXT:    xxlxor 47, 47, 47
; POWERPC_64LE-NEXT:    xxlxor 48, 48, 48
; POWERPC_64LE-NEXT:    .p2align 4
; POWERPC_64LE-NEXT:  .LBB0_6: # %vector.body
; POWERPC_64LE-NEXT:    #
; POWERPC_64LE-NEXT:    lxv 50, -64(4)
; POWERPC_64LE-NEXT:    vcmpequh 18, 18, 3
; POWERPC_64LE-NEXT:    xxlnor 50, 50, 50
; POWERPC_64LE-NEXT:    vmrghh 19, 18, 18
; POWERPC_64LE-NEXT:    vmrglh 18, 18, 18
; POWERPC_64LE-NEXT:    xxland 51, 51, 34
; POWERPC_64LE-NEXT:    xxland 50, 50, 34
; POWERPC_64LE-NEXT:    vadduwm 5, 5, 19
; POWERPC_64LE-NEXT:    lxv 51, -48(4)
; POWERPC_64LE-NEXT:    vadduwm 4, 4, 18
; POWERPC_64LE-NEXT:    vcmpequh 19, 19, 3
; POWERPC_64LE-NEXT:    xxlnor 51, 51, 51
; POWERPC_64LE-NEXT:    vmrghh 18, 19, 19
; POWERPC_64LE-NEXT:    vmrglh 19, 19, 19
; POWERPC_64LE-NEXT:    xxland 50, 50, 34
; POWERPC_64LE-NEXT:    xxland 51, 51, 34
; POWERPC_64LE-NEXT:    vadduwm 7, 7, 18
; POWERPC_64LE-NEXT:    lxv 50, -32(4)
; POWERPC_64LE-NEXT:    vadduwm 0, 0, 19
; POWERPC_64LE-NEXT:    vcmpequh 18, 18, 3
; POWERPC_64LE-NEXT:    xxlnor 50, 50, 50
; POWERPC_64LE-NEXT:    vmrghh 19, 18, 18
; POWERPC_64LE-NEXT:    vmrglh 18, 18, 18
; POWERPC_64LE-NEXT:    xxland 51, 51, 34
; POWERPC_64LE-NEXT:    xxland 50, 50, 34
; POWERPC_64LE-NEXT:    vadduwm 10, 10, 19
; POWERPC_64LE-NEXT:    lxv 51, -16(4)
; POWERPC_64LE-NEXT:    vadduwm 1, 1, 18
; POWERPC_64LE-NEXT:    vcmpequh 19, 19, 3
; POWERPC_64LE-NEXT:    xxlnor 51, 51, 51
; POWERPC_64LE-NEXT:    vmrghh 18, 19, 19
; POWERPC_64LE-NEXT:    vmrglh 19, 19, 19
; POWERPC_64LE-NEXT:    xxland 50, 50, 34
; POWERPC_64LE-NEXT:    xxland 51, 51, 34
; POWERPC_64LE-NEXT:    vadduwm 9, 9, 18
; POWERPC_64LE-NEXT:    lxv 50, 0(4)
; POWERPC_64LE-NEXT:    vadduwm 8, 8, 19
; POWERPC_64LE-NEXT:    vcmpequh 18, 18, 3
; POWERPC_64LE-NEXT:    xxlnor 50, 50, 50
; POWERPC_64LE-NEXT:    vmrghh 19, 18, 18
; POWERPC_64LE-NEXT:    vmrglh 18, 18, 18
; POWERPC_64LE-NEXT:    xxland 51, 51, 34
; POWERPC_64LE-NEXT:    xxland 50, 50, 34
; POWERPC_64LE-NEXT:    vadduwm 14, 14, 19
; POWERPC_64LE-NEXT:    lxv 51, 16(4)
; POWERPC_64LE-NEXT:    vadduwm 6, 6, 18
; POWERPC_64LE-NEXT:    vcmpequh 19, 19, 3
; POWERPC_64LE-NEXT:    xxlnor 51, 51, 51
; POWERPC_64LE-NEXT:    vmrghh 18, 19, 19
; POWERPC_64LE-NEXT:    vmrglh 19, 19, 19
; POWERPC_64LE-NEXT:    xxland 50, 50, 34
; POWERPC_64LE-NEXT:    xxland 51, 51, 34
; POWERPC_64LE-NEXT:    vadduwm 12, 12, 18
; POWERPC_64LE-NEXT:    lxv 50, 32(4)
; POWERPC_64LE-NEXT:    vadduwm 11, 11, 19
; POWERPC_64LE-NEXT:    vcmpequh 18, 18, 3
; POWERPC_64LE-NEXT:    xxlnor 50, 50, 50
; POWERPC_64LE-NEXT:    vmrghh 19, 18, 18
; POWERPC_64LE-NEXT:    vmrglh 18, 18, 18
; POWERPC_64LE-NEXT:    xxland 51, 51, 34
; POWERPC_64LE-NEXT:    xxland 50, 50, 34
; POWERPC_64LE-NEXT:    vadduwm 17, 17, 19
; POWERPC_64LE-NEXT:    lxv 51, 48(4)
; POWERPC_64LE-NEXT:    addi 4, 4, 128
; POWERPC_64LE-NEXT:    vadduwm 13, 13, 18
; POWERPC_64LE-NEXT:    vcmpequh 19, 19, 3
; POWERPC_64LE-NEXT:    xxlnor 51, 51, 51
; POWERPC_64LE-NEXT:    vmrghh 18, 19, 19
; POWERPC_64LE-NEXT:    xxland 50, 50, 34
; POWERPC_64LE-NEXT:    vadduwm 16, 16, 18
; POWERPC_64LE-NEXT:    vmrglh 18, 19, 19
; POWERPC_64LE-NEXT:    xxland 50, 50, 34
; POWERPC_64LE-NEXT:    vadduwm 15, 15, 18
; POWERPC_64LE-NEXT:    bdnz .LBB0_6
; POWERPC_64LE-NEXT:  # %bb.7: # %middle.block
; POWERPC_64LE-NEXT:    vadduwm 3, 0, 4
; POWERPC_64LE-NEXT:    vadduwm 4, 7, 5
; POWERPC_64LE-NEXT:    li 4, 0
; POWERPC_64LE-NEXT:    cmpld 6, 5
; POWERPC_64LE-NEXT:    vadduwm 4, 10, 4
; POWERPC_64LE-NEXT:    vadduwm 3, 1, 3
; POWERPC_64LE-NEXT:    vadduwm 3, 8, 3
; POWERPC_64LE-NEXT:    vadduwm 4, 9, 4
; POWERPC_64LE-NEXT:    vadduwm 4, 14, 4
; POWERPC_64LE-NEXT:    vadduwm 3, 6, 3
; POWERPC_64LE-NEXT:    vadduwm 3, 11, 3
; POWERPC_64LE-NEXT:    vadduwm 4, 12, 4
; POWERPC_64LE-NEXT:    vadduwm 4, 17, 4
; POWERPC_64LE-NEXT:    vadduwm 3, 13, 3
; POWERPC_64LE-NEXT:    vadduwm 3, 15, 3
; POWERPC_64LE-NEXT:    vadduwm 4, 16, 4
; POWERPC_64LE-NEXT:    vadduwm 3, 3, 4
; POWERPC_64LE-NEXT:    xxswapd 36, 35
; POWERPC_64LE-NEXT:    vadduwm 3, 3, 4
; POWERPC_64LE-NEXT:    xxspltw 36, 35, 2
; POWERPC_64LE-NEXT:    vadduwm 3, 3, 4
; POWERPC_64LE-NEXT:    vextuwrx 4, 4, 3
; POWERPC_64LE-NEXT:    beq 0, .LBB0_14
; POWERPC_64LE-NEXT:  # %bb.8: # %vec.epilog.iter.check
; POWERPC_64LE-NEXT:    andi. 8, 5, 56
; POWERPC_64LE-NEXT:    beq 0, .LBB0_12
; POWERPC_64LE-NEXT:  .LBB0_9: # %vec.epilog.ph
; POWERPC_64LE-NEXT:    mr 8, 6
; POWERPC_64LE-NEXT:    rlwinm 6, 5, 0, 1, 28
; POWERPC_64LE-NEXT:    rldimi 4, 7, 32, 0
; POWERPC_64LE-NEXT:    xxlxor 36, 36, 36
; POWERPC_64LE-NEXT:    xxlxor 37, 37, 37
; POWERPC_64LE-NEXT:    rldimi 7, 7, 32, 0
; POWERPC_64LE-NEXT:    mtvsrdd 35, 7, 4
; POWERPC_64LE-NEXT:    sub 7, 6, 8
; POWERPC_64LE-NEXT:    sldi 4, 8, 1
; POWERPC_64LE-NEXT:    addi 7, 7, -8
; POWERPC_64LE-NEXT:    add 4, 3, 4
; POWERPC_64LE-NEXT:    rldicl 7, 7, 61, 3
; POWERPC_64LE-NEXT:    addi 7, 7, 1
; POWERPC_64LE-NEXT:    mtctr 7
; POWERPC_64LE-NEXT:    .p2align 4
; POWERPC_64LE-NEXT:  .LBB0_10: # %vec.epilog.vector.body
; POWERPC_64LE-NEXT:    #
; POWERPC_64LE-NEXT:    lxv 32, 0(4)
; POWERPC_64LE-NEXT:    addi 4, 4, 16
; POWERPC_64LE-NEXT:    vcmpequh 0, 0, 4
; POWERPC_64LE-NEXT:    xxlnor 32, 32, 32
; POWERPC_64LE-NEXT:    vmrglh 1, 0, 0
; POWERPC_64LE-NEXT:    vmrghh 0, 0, 0
; POWERPC_64LE-NEXT:    xxland 33, 33, 34
; POWERPC_64LE-NEXT:    xxland 32, 32, 34
; POWERPC_64LE-NEXT:    vadduwm 5, 5, 0
; POWERPC_64LE-NEXT:    vadduwm 3, 3, 1
; POWERPC_64LE-NEXT:    bdnz .LBB0_10
; POWERPC_64LE-NEXT:  # %bb.11: # %vec.epilog.middle.block
; POWERPC_64LE-NEXT:    vadduwm 2, 3, 5
; POWERPC_64LE-NEXT:    li 4, 0
; POWERPC_64LE-NEXT:    cmpld 6, 5
; POWERPC_64LE-NEXT:    xxswapd 35, 34
; POWERPC_64LE-NEXT:    vadduwm 2, 2, 3
; POWERPC_64LE-NEXT:    xxspltw 35, 34, 2
; POWERPC_64LE-NEXT:    vadduwm 2, 2, 3
; POWERPC_64LE-NEXT:    vextuwrx 4, 4, 2
; POWERPC_64LE-NEXT:    beq 0, .LBB0_14
; POWERPC_64LE-NEXT:  .LBB0_12: # %for.body.preheader
; POWERPC_64LE-NEXT:    sldi 7, 6, 1
; POWERPC_64LE-NEXT:    sub 5, 5, 6
; POWERPC_64LE-NEXT:    add 3, 7, 3
; POWERPC_64LE-NEXT:    mtctr 5
; POWERPC_64LE-NEXT:    addi 3, 3, -2
; POWERPC_64LE-NEXT:    .p2align 5
; POWERPC_64LE-NEXT:  .LBB0_13: # %for.body
; POWERPC_64LE-NEXT:    #
; POWERPC_64LE-NEXT:    lhzu 5, 2(3)
; POWERPC_64LE-NEXT:    cntlzw 5, 5
; POWERPC_64LE-NEXT:    srwi 5, 5, 5
; POWERPC_64LE-NEXT:    xori 5, 5, 1
; POWERPC_64LE-NEXT:    add 4, 4, 5
; POWERPC_64LE-NEXT:    bdnz .LBB0_13
; POWERPC_64LE-NEXT:  .LBB0_14: # %for.cond.cleanup
; POWERPC_64LE-NEXT:    mr 3, 4
; POWERPC_64LE-NEXT:    blr
;
; POWERPC_64-LABEL: test_Greater_than:
; POWERPC_64:       # %bb.0: # %entry
; POWERPC_64-NEXT:    cmpwi 4, 1
; POWERPC_64-NEXT:    blt 0, L..BB0_3
; POWERPC_64-NEXT:  # %bb.1: # %iter.check
; POWERPC_64-NEXT:    clrldi 5, 4, 32
; POWERPC_64-NEXT:    cmplwi 4, 7
; POWERPC_64-NEXT:    bgt 0, L..BB0_4
; POWERPC_64-NEXT:  # %bb.2:
; POWERPC_64-NEXT:    li 4, 0
; POWERPC_64-NEXT:    li 6, 0
; POWERPC_64-NEXT:    b L..BB0_12
; POWERPC_64-NEXT:  L..BB0_3:
; POWERPC_64-NEXT:    li 4, 0
; POWERPC_64-NEXT:    mr 3, 4
; POWERPC_64-NEXT:    blr
; POWERPC_64-NEXT:  L..BB0_4: # %vector.main.loop.iter.check
; POWERPC_64-NEXT:    vspltisw 2, 1
; POWERPC_64-NEXT:    li 7, 0
; POWERPC_64-NEXT:    li 6, 0
; POWERPC_64-NEXT:    cmplwi 4, 64
; POWERPC_64-NEXT:    li 4, 0
; POWERPC_64-NEXT:    blt 0, L..BB0_9
; POWERPC_64-NEXT:  # %bb.5: # %vector.ph
; POWERPC_64-NEXT:    rlwinm 6, 5, 0, 1, 25
; POWERPC_64-NEXT:    addi 4, 3, 64
; POWERPC_64-NEXT:    xxlxor 35, 35, 35
; POWERPC_64-NEXT:    addi 8, 6, -64
; POWERPC_64-NEXT:    xxlxor 36, 36, 36
; POWERPC_64-NEXT:    rldicl 8, 8, 58, 6
; POWERPC_64-NEXT:    xxlxor 37, 37, 37
; POWERPC_64-NEXT:    xxlxor 32, 32, 32
; POWERPC_64-NEXT:    xxlxor 39, 39, 39
; POWERPC_64-NEXT:    xxlxor 33, 33, 33
; POWERPC_64-NEXT:    xxlxor 42, 42, 42
; POWERPC_64-NEXT:    xxlxor 40, 40, 40
; POWERPC_64-NEXT:    addi 8, 8, 1
; POWERPC_64-NEXT:    xxlxor 41, 41, 41
; POWERPC_64-NEXT:    mtctr 8
; POWERPC_64-NEXT:    xxlxor 38, 38, 38
; POWERPC_64-NEXT:    xxlxor 46, 46, 46
; POWERPC_64-NEXT:    xxlxor 43, 43, 43
; POWERPC_64-NEXT:    xxlxor 44, 44, 44
; POWERPC_64-NEXT:    xxlxor 45, 45, 45
; POWERPC_64-NEXT:    xxlxor 49, 49, 49
; POWERPC_64-NEXT:    xxlxor 47, 47, 47
; POWERPC_64-NEXT:    xxlxor 48, 48, 48
; POWERPC_64-NEXT:    .align 4
; POWERPC_64-NEXT:  L..BB0_6: # %vector.body
; POWERPC_64-NEXT:    #
; POWERPC_64-NEXT:    lxv 50, -64(4)
; POWERPC_64-NEXT:    vcmpequh 18, 18, 3
; POWERPC_64-NEXT:    xxlnor 50, 50, 50
; POWERPC_64-NEXT:    vmrglh 19, 18, 18
; POWERPC_64-NEXT:    vmrghh 18, 18, 18
; POWERPC_64-NEXT:    xxland 51, 51, 34
; POWERPC_64-NEXT:    xxland 50, 50, 34
; POWERPC_64-NEXT:    vadduwm 5, 5, 19
; POWERPC_64-NEXT:    lxv 51, -48(4)
; POWERPC_64-NEXT:    vadduwm 4, 4, 18
; POWERPC_64-NEXT:    vcmpequh 19, 19, 3
; POWERPC_64-NEXT:    xxlnor 51, 51, 51
; POWERPC_64-NEXT:    vmrglh 18, 19, 19
; POWERPC_64-NEXT:    vmrghh 19, 19, 19
; POWERPC_64-NEXT:    xxland 50, 50, 34
; POWERPC_64-NEXT:    xxland 51, 51, 34
; POWERPC_64-NEXT:    vadduwm 7, 7, 18
; POWERPC_64-NEXT:    lxv 50, -32(4)
; POWERPC_64-NEXT:    vadduwm 0, 0, 19
; POWERPC_64-NEXT:    vcmpequh 18, 18, 3
; POWERPC_64-NEXT:    xxlnor 50, 50, 50
; POWERPC_64-NEXT:    vmrglh 19, 18, 18
; POWERPC_64-NEXT:    vmrghh 18, 18, 18
; POWERPC_64-NEXT:    xxland 51, 51, 34
; POWERPC_64-NEXT:    xxland 50, 50, 34
; POWERPC_64-NEXT:    vadduwm 10, 10, 19
; POWERPC_64-NEXT:    lxv 51, -16(4)
; POWERPC_64-NEXT:    vadduwm 1, 1, 18
; POWERPC_64-NEXT:    vcmpequh 19, 19, 3
; POWERPC_64-NEXT:    xxlnor 51, 51, 51
; POWERPC_64-NEXT:    vmrglh 18, 19, 19
; POWERPC_64-NEXT:    vmrghh 19, 19, 19
; POWERPC_64-NEXT:    xxland 50, 50, 34
; POWERPC_64-NEXT:    xxland 51, 51, 34
; POWERPC_64-NEXT:    vadduwm 9, 9, 18
; POWERPC_64-NEXT:    lxv 50, 0(4)
; POWERPC_64-NEXT:    vadduwm 8, 8, 19
; POWERPC_64-NEXT:    vcmpequh 18, 18, 3
; POWERPC_64-NEXT:    xxlnor 50, 50, 50
; POWERPC_64-NEXT:    vmrglh 19, 18, 18
; POWERPC_64-NEXT:    vmrghh 18, 18, 18
; POWERPC_64-NEXT:    xxland 51, 51, 34
; POWERPC_64-NEXT:    xxland 50, 50, 34
; POWERPC_64-NEXT:    vadduwm 14, 14, 19
; POWERPC_64-NEXT:    lxv 51, 16(4)
; POWERPC_64-NEXT:    vadduwm 6, 6, 18
; POWERPC_64-NEXT:    vcmpequh 19, 19, 3
; POWERPC_64-NEXT:    xxlnor 51, 51, 51
; POWERPC_64-NEXT:    vmrglh 18, 19, 19
; POWERPC_64-NEXT:    vmrghh 19, 19, 19
; POWERPC_64-NEXT:    xxland 50, 50, 34
; POWERPC_64-NEXT:    xxland 51, 51, 34
; POWERPC_64-NEXT:    vadduwm 12, 12, 18
; POWERPC_64-NEXT:    lxv 50, 32(4)
; POWERPC_64-NEXT:    vadduwm 11, 11, 19
; POWERPC_64-NEXT:    vcmpequh 18, 18, 3
; POWERPC_64-NEXT:    xxlnor 50, 50, 50
; POWERPC_64-NEXT:    vmrglh 19, 18, 18
; POWERPC_64-NEXT:    vmrghh 18, 18, 18
; POWERPC_64-NEXT:    xxland 51, 51, 34
; POWERPC_64-NEXT:    xxland 50, 50, 34
; POWERPC_64-NEXT:    vadduwm 17, 17, 19
; POWERPC_64-NEXT:    lxv 51, 48(4)
; POWERPC_64-NEXT:    addi 4, 4, 128
; POWERPC_64-NEXT:    vadduwm 13, 13, 18
; POWERPC_64-NEXT:    vcmpequh 19, 19, 3
; POWERPC_64-NEXT:    xxlnor 51, 51, 51
; POWERPC_64-NEXT:    vmrglh 18, 19, 19
; POWERPC_64-NEXT:    xxland 50, 50, 34
; POWERPC_64-NEXT:    vadduwm 16, 16, 18
; POWERPC_64-NEXT:    vmrghh 18, 19, 19
; POWERPC_64-NEXT:    xxland 50, 50, 34
; POWERPC_64-NEXT:    vadduwm 15, 15, 18
; POWERPC_64-NEXT:    bdnz L..BB0_6
; POWERPC_64-NEXT:  # %bb.7: # %middle.block
; POWERPC_64-NEXT:    vadduwm 3, 0, 4
; POWERPC_64-NEXT:    vadduwm 4, 7, 5
; POWERPC_64-NEXT:    li 4, 0
; POWERPC_64-NEXT:    cmpld 6, 5
; POWERPC_64-NEXT:    vadduwm 4, 10, 4
; POWERPC_64-NEXT:    vadduwm 3, 1, 3
; POWERPC_64-NEXT:    vadduwm 3, 8, 3
; POWERPC_64-NEXT:    vadduwm 4, 9, 4
; POWERPC_64-NEXT:    vadduwm 4, 14, 4
; POWERPC_64-NEXT:    vadduwm 3, 6, 3
; POWERPC_64-NEXT:    vadduwm 3, 11, 3
; POWERPC_64-NEXT:    vadduwm 4, 12, 4
; POWERPC_64-NEXT:    vadduwm 4, 17, 4
; POWERPC_64-NEXT:    vadduwm 3, 13, 3
; POWERPC_64-NEXT:    vadduwm 3, 15, 3
; POWERPC_64-NEXT:    vadduwm 4, 16, 4
; POWERPC_64-NEXT:    vadduwm 3, 3, 4
; POWERPC_64-NEXT:    xxswapd 36, 35
; POWERPC_64-NEXT:    vadduwm 3, 3, 4
; POWERPC_64-NEXT:    xxspltw 36, 35, 1
; POWERPC_64-NEXT:    vadduwm 3, 3, 4
; POWERPC_64-NEXT:    vextuwlx 4, 4, 3
; POWERPC_64-NEXT:    beq 0, L..BB0_14
; POWERPC_64-NEXT:  # %bb.8: # %vec.epilog.iter.check
; POWERPC_64-NEXT:    andi. 8, 5, 56
; POWERPC_64-NEXT:    beq 0, L..BB0_12
; POWERPC_64-NEXT:  L..BB0_9: # %vec.epilog.ph
; POWERPC_64-NEXT:    li 9, 0
; POWERPC_64-NEXT:    mr 8, 6
; POWERPC_64-NEXT:    rlwinm 6, 5, 0, 1, 28
; POWERPC_64-NEXT:    rldimi 7, 7, 32, 0
; POWERPC_64-NEXT:    xxlxor 36, 36, 36
; POWERPC_64-NEXT:    rldimi 9, 4, 32, 0
; POWERPC_64-NEXT:    sldi 4, 8, 1
; POWERPC_64-NEXT:    xxlxor 37, 37, 37
; POWERPC_64-NEXT:    mtvsrdd 35, 9, 7
; POWERPC_64-NEXT:    sub 7, 6, 8
; POWERPC_64-NEXT:    add 4, 3, 4
; POWERPC_64-NEXT:    addi 7, 7, -8
; POWERPC_64-NEXT:    rldicl 7, 7, 61, 3
; POWERPC_64-NEXT:    addi 7, 7, 1
; POWERPC_64-NEXT:    mtctr 7
; POWERPC_64-NEXT:    .align 4
; POWERPC_64-NEXT:  L..BB0_10: # %vec.epilog.vector.body
; POWERPC_64-NEXT:    #
; POWERPC_64-NEXT:    lxv 32, 0(4)
; POWERPC_64-NEXT:    addi 4, 4, 16
; POWERPC_64-NEXT:    vcmpequh 0, 0, 4
; POWERPC_64-NEXT:    xxlnor 32, 32, 32
; POWERPC_64-NEXT:    vmrghh 1, 0, 0
; POWERPC_64-NEXT:    vmrglh 0, 0, 0
; POWERPC_64-NEXT:    xxland 33, 33, 34
; POWERPC_64-NEXT:    xxland 32, 32, 34
; POWERPC_64-NEXT:    vadduwm 5, 5, 0
; POWERPC_64-NEXT:    vadduwm 3, 3, 1
; POWERPC_64-NEXT:    bdnz L..BB0_10
; POWERPC_64-NEXT:  # %bb.11: # %vec.epilog.middle.block
; POWERPC_64-NEXT:    vadduwm 2, 3, 5
; POWERPC_64-NEXT:    li 4, 0
; POWERPC_64-NEXT:    cmpld 6, 5
; POWERPC_64-NEXT:    xxswapd 35, 34
; POWERPC_64-NEXT:    vadduwm 2, 2, 3
; POWERPC_64-NEXT:    xxspltw 35, 34, 1
; POWERPC_64-NEXT:    vadduwm 2, 2, 3
; POWERPC_64-NEXT:    vextuwlx 4, 4, 2
; POWERPC_64-NEXT:    beq 0, L..BB0_14
; POWERPC_64-NEXT:  L..BB0_12: # %for.body.preheader
; POWERPC_64-NEXT:    sldi 7, 6, 1
; POWERPC_64-NEXT:    sub 5, 5, 6
; POWERPC_64-NEXT:    add 3, 7, 3
; POWERPC_64-NEXT:    mtctr 5
; POWERPC_64-NEXT:    addi 3, 3, -2
; POWERPC_64-NEXT:    .align 5
; POWERPC_64-NEXT:  L..BB0_13: # %for.body
; POWERPC_64-NEXT:    #
; POWERPC_64-NEXT:    lhzu 5, 2(3)
; POWERPC_64-NEXT:    cntlzw 5, 5
; POWERPC_64-NEXT:    srwi 5, 5, 5
; POWERPC_64-NEXT:    xori 5, 5, 1
; POWERPC_64-NEXT:    add 4, 4, 5
; POWERPC_64-NEXT:    bdnz L..BB0_13
; POWERPC_64-NEXT:  L..BB0_14: # %for.cond.cleanup
; POWERPC_64-NEXT:    mr 3, 4
; POWERPC_64-NEXT:    blr
;
; POWERPC_32-LABEL: test_Greater_than:
; POWERPC_32:       # %bb.0: # %entry
; POWERPC_32-NEXT:    cmpwi 4, 0
; POWERPC_32-NEXT:    ble 0, L..BB0_3
; POWERPC_32-NEXT:  # %bb.1: # %iter.check
; POWERPC_32-NEXT:    cmplwi 4, 7
; POWERPC_32-NEXT:    bgt 0, L..BB0_4
; POWERPC_32-NEXT:  # %bb.2:
; POWERPC_32-NEXT:    li 7, 0
; POWERPC_32-NEXT:    li 6, 0
; POWERPC_32-NEXT:    li 5, 0
; POWERPC_32-NEXT:    b L..BB0_13
; POWERPC_32-NEXT:  L..BB0_3:
; POWERPC_32-NEXT:    li 5, 0
; POWERPC_32-NEXT:    mr 3, 5
; POWERPC_32-NEXT:    blr
; POWERPC_32-NEXT:  L..BB0_4: # %vector.main.loop.iter.check
; POWERPC_32-NEXT:    lis 6, 32767
; POWERPC_32-NEXT:    vspltisw 2, 1
; POWERPC_32-NEXT:    li 5, 0
; POWERPC_32-NEXT:    cmplwi 4, 64
; POWERPC_32-NEXT:    ori 8, 6, 65472
; POWERPC_32-NEXT:    bge 0, L..BB0_6
; POWERPC_32-NEXT:  # %bb.5:
; POWERPC_32-NEXT:    li 7, 0
; POWERPC_32-NEXT:    li 6, 0
; POWERPC_32-NEXT:    b L..BB0_10
; POWERPC_32-NEXT:  L..BB0_6: # %vector.ph
; POWERPC_32-NEXT:    and 6, 4, 8
; POWERPC_32-NEXT:    xxlxor 35, 35, 35
; POWERPC_32-NEXT:    li 7, 0
; POWERPC_32-NEXT:    li 9, 0
; POWERPC_32-NEXT:    mr 10, 3
; POWERPC_32-NEXT:    xxlxor 36, 36, 36
; POWERPC_32-NEXT:    xxlxor 37, 37, 37
; POWERPC_32-NEXT:    xxlxor 39, 39, 39
; POWERPC_32-NEXT:    xxlxor 40, 40, 40
; POWERPC_32-NEXT:    xxlxor 32, 32, 32
; POWERPC_32-NEXT:    xxlxor 45, 45, 45
; POWERPC_32-NEXT:    xxlxor 41, 41, 41
; POWERPC_32-NEXT:    xxlxor 42, 42, 42
; POWERPC_32-NEXT:    xxlxor 33, 33, 33
; POWERPC_32-NEXT:    xxlxor 46, 46, 46
; POWERPC_32-NEXT:    xxlxor 43, 43, 43
; POWERPC_32-NEXT:    xxlxor 44, 44, 44
; POWERPC_32-NEXT:    xxlxor 38, 38, 38
; POWERPC_32-NEXT:    xxlxor 48, 48, 48
; POWERPC_32-NEXT:    xxlxor 47, 47, 47
; POWERPC_32-NEXT:    xxlxor 49, 49, 49
; POWERPC_32-NEXT:    .align 4
; POWERPC_32-NEXT:  L..BB0_7: # %vector.body
; POWERPC_32-NEXT:    #
; POWERPC_32-NEXT:    lxv 50, 0(10)
; POWERPC_32-NEXT:    addic 9, 9, 64
; POWERPC_32-NEXT:    addze 5, 5
; POWERPC_32-NEXT:    xor 11, 9, 6
; POWERPC_32-NEXT:    or. 11, 11, 5
; POWERPC_32-NEXT:    vcmpequh 18, 18, 3
; POWERPC_32-NEXT:    xxlnor 50, 50, 50
; POWERPC_32-NEXT:    vmrglh 19, 18, 18
; POWERPC_32-NEXT:    vmrghh 18, 18, 18
; POWERPC_32-NEXT:    xxland 51, 51, 34
; POWERPC_32-NEXT:    xxland 50, 50, 34
; POWERPC_32-NEXT:    vadduwm 5, 5, 19
; POWERPC_32-NEXT:    lxv 51, 16(10)
; POWERPC_32-NEXT:    vadduwm 4, 4, 18
; POWERPC_32-NEXT:    vcmpequh 19, 19, 3
; POWERPC_32-NEXT:    xxlnor 51, 51, 51
; POWERPC_32-NEXT:    vmrglh 18, 19, 19
; POWERPC_32-NEXT:    vmrghh 19, 19, 19
; POWERPC_32-NEXT:    xxland 50, 50, 34
; POWERPC_32-NEXT:    xxland 51, 51, 34
; POWERPC_32-NEXT:    vadduwm 8, 8, 18
; POWERPC_32-NEXT:    lxv 50, 32(10)
; POWERPC_32-NEXT:    vadduwm 7, 7, 19
; POWERPC_32-NEXT:    vcmpequh 18, 18, 3
; POWERPC_32-NEXT:    xxlnor 50, 50, 50
; POWERPC_32-NEXT:    vmrglh 19, 18, 18
; POWERPC_32-NEXT:    vmrghh 18, 18, 18
; POWERPC_32-NEXT:    xxland 51, 51, 34
; POWERPC_32-NEXT:    xxland 50, 50, 34
; POWERPC_32-NEXT:    vadduwm 13, 13, 19
; POWERPC_32-NEXT:    lxv 51, 48(10)
; POWERPC_32-NEXT:    vadduwm 0, 0, 18
; POWERPC_32-NEXT:    vcmpequh 19, 19, 3
; POWERPC_32-NEXT:    xxlnor 51, 51, 51
; POWERPC_32-NEXT:    vmrglh 18, 19, 19
; POWERPC_32-NEXT:    vmrghh 19, 19, 19
; POWERPC_32-NEXT:    xxland 50, 50, 34
; POWERPC_32-NEXT:    xxland 51, 51, 34
; POWERPC_32-NEXT:    vadduwm 10, 10, 18
; POWERPC_32-NEXT:    lxv 50, 64(10)
; POWERPC_32-NEXT:    vadduwm 9, 9, 19
; POWERPC_32-NEXT:    vcmpequh 18, 18, 3
; POWERPC_32-NEXT:    xxlnor 50, 50, 50
; POWERPC_32-NEXT:    vmrglh 19, 18, 18
; POWERPC_32-NEXT:    vmrghh 18, 18, 18
; POWERPC_32-NEXT:    xxland 51, 51, 34
; POWERPC_32-NEXT:    xxland 50, 50, 34
; POWERPC_32-NEXT:    vadduwm 14, 14, 19
; POWERPC_32-NEXT:    lxv 51, 80(10)
; POWERPC_32-NEXT:    vadduwm 1, 1, 18
; POWERPC_32-NEXT:    vcmpequh 19, 19, 3
; POWERPC_32-NEXT:    xxlnor 51, 51, 51
; POWERPC_32-NEXT:    vmrglh 18, 19, 19
; POWERPC_32-NEXT:    vmrghh 19, 19, 19
; POWERPC_32-NEXT:    xxland 50, 50, 34
; POWERPC_32-NEXT:    xxland 51, 51, 34
; POWERPC_32-NEXT:    vadduwm 12, 12, 18
; POWERPC_32-NEXT:    lxv 50, 96(10)
; POWERPC_32-NEXT:    vadduwm 11, 11, 19
; POWERPC_32-NEXT:    vcmpequh 18, 18, 3
; POWERPC_32-NEXT:    xxlnor 50, 50, 50
; POWERPC_32-NEXT:    vmrglh 19, 18, 18
; POWERPC_32-NEXT:    vmrghh 18, 18, 18
; POWERPC_32-NEXT:    xxland 51, 51, 34
; POWERPC_32-NEXT:    xxland 50, 50, 34
; POWERPC_32-NEXT:    vadduwm 16, 16, 19
; POWERPC_32-NEXT:    lxv 51, 112(10)
; POWERPC_32-NEXT:    vadduwm 6, 6, 18
; POWERPC_32-NEXT:    addi 10, 10, 128
; POWERPC_32-NEXT:    vcmpequh 19, 19, 3
; POWERPC_32-NEXT:    xxlnor 51, 51, 51
; POWERPC_32-NEXT:    vmrglh 18, 19, 19
; POWERPC_32-NEXT:    xxland 50, 50, 34
; POWERPC_32-NEXT:    vadduwm 17, 17, 18
; POWERPC_32-NEXT:    vmrghh 18, 19, 19
; POWERPC_32-NEXT:    xxland 50, 50, 34
; POWERPC_32-NEXT:    vadduwm 15, 15, 18
; POWERPC_32-NEXT:    bne 0, L..BB0_7
; POWERPC_32-NEXT:  # %bb.8: # %middle.block
; POWERPC_32-NEXT:    vadduwm 3, 7, 4
; POWERPC_32-NEXT:    vadduwm 4, 8, 5
; POWERPC_32-NEXT:    xor. 9, 6, 4
; POWERPC_32-NEXT:    vadduwm 4, 13, 4
; POWERPC_32-NEXT:    vadduwm 3, 0, 3
; POWERPC_32-NEXT:    vadduwm 3, 9, 3
; POWERPC_32-NEXT:    vadduwm 4, 10, 4
; POWERPC_32-NEXT:    vadduwm 4, 14, 4
; POWERPC_32-NEXT:    vadduwm 3, 1, 3
; POWERPC_32-NEXT:    vadduwm 3, 11, 3
; POWERPC_32-NEXT:    vadduwm 4, 12, 4
; POWERPC_32-NEXT:    vadduwm 4, 16, 4
; POWERPC_32-NEXT:    vadduwm 3, 6, 3
; POWERPC_32-NEXT:    vadduwm 3, 15, 3
; POWERPC_32-NEXT:    vadduwm 4, 17, 4
; POWERPC_32-NEXT:    vadduwm 3, 3, 4
; POWERPC_32-NEXT:    xxswapd 36, 35
; POWERPC_32-NEXT:    vadduwm 3, 3, 4
; POWERPC_32-NEXT:    xxspltw 36, 35, 1
; POWERPC_32-NEXT:    vadduwm 3, 3, 4
; POWERPC_32-NEXT:    stxv 35, -16(1)
; POWERPC_32-NEXT:    lwz 5, -16(1)
; POWERPC_32-NEXT:    beq 0, L..BB0_15
; POWERPC_32-NEXT:  # %bb.9: # %vec.epilog.iter.check
; POWERPC_32-NEXT:    andi. 9, 4, 56
; POWERPC_32-NEXT:    beq 0, L..BB0_13
; POWERPC_32-NEXT:  L..BB0_10: # %vec.epilog.ph
; POWERPC_32-NEXT:    stw 5, -32(1)
; POWERPC_32-NEXT:    lwz 5, L..C0(2) # %const.0
; POWERPC_32-NEXT:    xxlxor 36, 36, 36
; POWERPC_32-NEXT:    mr 9, 6
; POWERPC_32-NEXT:    lxv 1, -32(1)
; POWERPC_32-NEXT:    addi 6, 8, 56
; POWERPC_32-NEXT:    and 6, 4, 6
; POWERPC_32-NEXT:    xxlxor 35, 35, 35
; POWERPC_32-NEXT:    xxlxor 37, 37, 37
; POWERPC_32-NEXT:    lxv 0, 0(5)
; POWERPC_32-NEXT:    xxperm 36, 1, 0
; POWERPC_32-NEXT:    .align 4
; POWERPC_32-NEXT:  L..BB0_11: # %vec.epilog.vector.body
; POWERPC_32-NEXT:    #
; POWERPC_32-NEXT:    slwi 5, 9, 1
; POWERPC_32-NEXT:    addic 9, 9, 8
; POWERPC_32-NEXT:    addze 7, 7
; POWERPC_32-NEXT:    lxvx 32, 3, 5
; POWERPC_32-NEXT:    xor 5, 9, 6
; POWERPC_32-NEXT:    or. 5, 5, 7
; POWERPC_32-NEXT:    vcmpequh 0, 0, 3
; POWERPC_32-NEXT:    xxlnor 32, 32, 32
; POWERPC_32-NEXT:    vmrghh 1, 0, 0
; POWERPC_32-NEXT:    vmrglh 0, 0, 0
; POWERPC_32-NEXT:    xxland 33, 33, 34
; POWERPC_32-NEXT:    xxland 32, 32, 34
; POWERPC_32-NEXT:    vadduwm 5, 5, 0
; POWERPC_32-NEXT:    vadduwm 4, 4, 1
; POWERPC_32-NEXT:    bne 0, L..BB0_11
; POWERPC_32-NEXT:  # %bb.12: # %vec.epilog.middle.block
; POWERPC_32-NEXT:    vadduwm 2, 4, 5
; POWERPC_32-NEXT:    xor. 7, 6, 4
; POWERPC_32-NEXT:    li 7, 0
; POWERPC_32-NEXT:    xxswapd 35, 34
; POWERPC_32-NEXT:    vadduwm 2, 2, 3
; POWERPC_32-NEXT:    xxspltw 35, 34, 1
; POWERPC_32-NEXT:    vadduwm 2, 2, 3
; POWERPC_32-NEXT:    stxv 34, -48(1)
; POWERPC_32-NEXT:    lwz 5, -48(1)
; POWERPC_32-NEXT:    beq 0, L..BB0_15
; POWERPC_32-NEXT:  L..BB0_13: # %for.body.preheader
; POWERPC_32-NEXT:    slwi 8, 6, 1
; POWERPC_32-NEXT:    add 3, 8, 3
; POWERPC_32-NEXT:    addi 3, 3, -2
; POWERPC_32-NEXT:    .align 4
; POWERPC_32-NEXT:  L..BB0_14: # %for.body
; POWERPC_32-NEXT:    #
; POWERPC_32-NEXT:    lhzu 8, 2(3)
; POWERPC_32-NEXT:    addic 6, 6, 1
; POWERPC_32-NEXT:    addze 7, 7
; POWERPC_32-NEXT:    cntlzw 8, 8
; POWERPC_32-NEXT:    not 8, 8
; POWERPC_32-NEXT:    rlwinm 8, 8, 27, 31, 31
; POWERPC_32-NEXT:    add 5, 5, 8
; POWERPC_32-NEXT:    xor 8, 6, 4
; POWERPC_32-NEXT:    or. 8, 8, 7
; POWERPC_32-NEXT:    bne 0, L..BB0_14
; POWERPC_32-NEXT:  L..BB0_15: # %for.cond.cleanup
; POWERPC_32-NEXT:    mr 3, 5
; POWERPC_32-NEXT:    blr
    entry:
  %cmp5 = icmp sgt i32 %ncols, 0
  br i1 %cmp5, label %iter.check, label %for.cond.cleanup

iter.check:                                       ; preds = %entry
  %wide.trip.count = zext nneg i32 %ncols to i64
  %min.iters.check = icmp ult i32 %ncols, 8
  br i1 %min.iters.check, label %for.body.preheader, label %vector.main.loop.iter.check

for.body.preheader:                               ; preds = %vec.epilog.iter.check, %vec.epilog.middle.block, %iter.check
  %indvars.iv.ph = phi i64 [ 0, %iter.check ], [ %n.vec, %vec.epilog.iter.check ], [ %n.vec31, %vec.epilog.middle.block ]
  %num_cols_needed.06.ph = phi i32 [ 0, %iter.check ], [ %33, %vec.epilog.iter.check ], [ %40, %vec.epilog.middle.block ]
  br label %for.body

vector.main.loop.iter.check:                      ; preds = %iter.check
  %min.iters.check9 = icmp ult i32 %ncols, 64
  br i1 %min.iters.check9, label %vec.epilog.ph, label %vector.ph

vector.ph:                                        ; preds = %vector.main.loop.iter.check
  %n.vec = and i64 %wide.trip.count, 2147483584
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %vec.phi = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %24, %vector.body ]
  %vec.phi10 = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %25, %vector.body ]
  %vec.phi11 = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %26, %vector.body ]
  %vec.phi12 = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %27, %vector.body ]
  %vec.phi13 = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %28, %vector.body ]
  %vec.phi14 = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %29, %vector.body ]
  %vec.phi15 = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %30, %vector.body ]
  %vec.phi16 = phi <8 x i32> [ zeroinitializer, %vector.ph ], [ %31, %vector.body ]
  %0 = getelementptr inbounds nuw i16, ptr %colauths, i64 %index
  %1 = getelementptr inbounds nuw i8, ptr %0, i64 16
  %2 = getelementptr inbounds nuw i8, ptr %0, i64 32
  %3 = getelementptr inbounds nuw i8, ptr %0, i64 48
  %4 = getelementptr inbounds nuw i8, ptr %0, i64 64
  %5 = getelementptr inbounds nuw i8, ptr %0, i64 80
  %6 = getelementptr inbounds nuw i8, ptr %0, i64 96
  %7 = getelementptr inbounds nuw i8, ptr %0, i64 112
  %wide.load = load <8 x i16>, ptr %0, align 2, !tbaa !5
  %wide.load17 = load <8 x i16>, ptr %1, align 2, !tbaa !5
  %wide.load18 = load <8 x i16>, ptr %2, align 2, !tbaa !5
  %wide.load19 = load <8 x i16>, ptr %3, align 2, !tbaa !5
  %wide.load20 = load <8 x i16>, ptr %4, align 2, !tbaa !5
  %wide.load21 = load <8 x i16>, ptr %5, align 2, !tbaa !5
  %wide.load22 = load <8 x i16>, ptr %6, align 2, !tbaa !5
  %wide.load23 = load <8 x i16>, ptr %7, align 2, !tbaa !5
  %8 = icmp ne <8 x i16> %wide.load, zeroinitializer
  %9 = icmp ne <8 x i16> %wide.load17, zeroinitializer
  %10 = icmp ne <8 x i16> %wide.load18, zeroinitializer
  %11 = icmp ne <8 x i16> %wide.load19, zeroinitializer
  %12 = icmp ne <8 x i16> %wide.load20, zeroinitializer
  %13 = icmp ne <8 x i16> %wide.load21, zeroinitializer
  %14 = icmp ne <8 x i16> %wide.load22, zeroinitializer
  %15 = icmp ne <8 x i16> %wide.load23, zeroinitializer
  %16 = zext <8 x i1> %8 to <8 x i32>
  %17 = zext <8 x i1> %9 to <8 x i32>
  %18 = zext <8 x i1> %10 to <8 x i32>
  %19 = zext <8 x i1> %11 to <8 x i32>
  %20 = zext <8 x i1> %12 to <8 x i32>
  %21 = zext <8 x i1> %13 to <8 x i32>
  %22 = zext <8 x i1> %14 to <8 x i32>
  %23 = zext <8 x i1> %15 to <8 x i32>
  %24 = add <8 x i32> %vec.phi, %16
  %25 = add <8 x i32> %vec.phi10, %17
  %26 = add <8 x i32> %vec.phi11, %18
  %27 = add <8 x i32> %vec.phi12, %19
  %28 = add <8 x i32> %vec.phi13, %20
  %29 = add <8 x i32> %vec.phi14, %21
  %30 = add <8 x i32> %vec.phi15, %22
  %31 = add <8 x i32> %vec.phi16, %23
  %index.next = add nuw i64 %index, 64
  %32 = icmp eq i64 %index.next, %n.vec
  br i1 %32, label %middle.block, label %vector.body, !llvm.loop !9

middle.block:                                     ; preds = %vector.body
  %bin.rdx = add <8 x i32> %25, %24
  %bin.rdx24 = add <8 x i32> %26, %bin.rdx
  %bin.rdx25 = add <8 x i32> %27, %bin.rdx24
  %bin.rdx26 = add <8 x i32> %28, %bin.rdx25
  %bin.rdx27 = add <8 x i32> %29, %bin.rdx26
  %bin.rdx28 = add <8 x i32> %30, %bin.rdx27
  %bin.rdx29 = add <8 x i32> %31, %bin.rdx28
  %33 = tail call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> %bin.rdx29)
  %cmp.n = icmp eq i64 %n.vec, %wide.trip.count
  br i1 %cmp.n, label %for.cond.cleanup, label %vec.epilog.iter.check

vec.epilog.iter.check:                            ; preds = %middle.block
  %n.vec.remaining = and i64 %wide.trip.count, 56
  %min.epilog.iters.check = icmp eq i64 %n.vec.remaining, 0
  br i1 %min.epilog.iters.check, label %for.body.preheader, label %vec.epilog.ph

vec.epilog.ph:                                    ; preds = %vec.epilog.iter.check, %vector.main.loop.iter.check
  %vec.epilog.resume.val = phi i64 [ %n.vec, %vec.epilog.iter.check ], [ 0, %vector.main.loop.iter.check ]
  %bc.merge.rdx = phi i32 [ %33, %vec.epilog.iter.check ], [ 0, %vector.main.loop.iter.check ]
  %n.vec31 = and i64 %wide.trip.count, 2147483640
  %34 = insertelement <8 x i32> <i32 poison, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>, i32 %bc.merge.rdx, i64 0
  br label %vec.epilog.vector.body

vec.epilog.vector.body:                           ; preds = %vec.epilog.vector.body, %vec.epilog.ph
  %index32 = phi i64 [ %vec.epilog.resume.val, %vec.epilog.ph ], [ %index.next35, %vec.epilog.vector.body ]
  %vec.phi33 = phi <8 x i32> [ %34, %vec.epilog.ph ], [ %38, %vec.epilog.vector.body ]
  %35 = getelementptr inbounds nuw i16, ptr %colauths, i64 %index32
  %wide.load34 = load <8 x i16>, ptr %35, align 2, !tbaa !5
  %36 = icmp ne <8 x i16> %wide.load34, zeroinitializer
  %37 = zext <8 x i1> %36 to <8 x i32>
  %38 = add <8 x i32> %vec.phi33, %37
  %index.next35 = add nuw i64 %index32, 8
  %39 = icmp eq i64 %index.next35, %n.vec31
  br i1 %39, label %vec.epilog.middle.block, label %vec.epilog.vector.body, !llvm.loop !13

vec.epilog.middle.block:                          ; preds = %vec.epilog.vector.body
  %40 = tail call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> %38)
  %cmp.n36 = icmp eq i64 %n.vec31, %wide.trip.count
  br i1 %cmp.n36, label %for.cond.cleanup, label %for.body.preheader

for.cond.cleanup:                                 ; preds = %for.body, %middle.block, %vec.epilog.middle.block, %entry
  %num_cols_needed.0.lcssa = phi i32 [ 0, %entry ], [ %33, %middle.block ], [ %40, %vec.epilog.middle.block ], [ %spec.select, %for.body ]
  ret i32 %num_cols_needed.0.lcssa

for.body:                                         ; preds = %for.body.preheader, %for.body
  %indvars.iv = phi i64 [ %indvars.iv.next, %for.body ], [ %indvars.iv.ph, %for.body.preheader ]
  %num_cols_needed.06 = phi i32 [ %spec.select, %for.body ], [ %num_cols_needed.06.ph, %for.body.preheader ]
  %arrayidx = getelementptr inbounds nuw i16, ptr %colauths, i64 %indvars.iv
  %41 = load i16, ptr %arrayidx, align 2, !tbaa !5
  %tobool.not = icmp ne i16 %41, 0
  %inc = zext i1 %tobool.not to i32
  %spec.select = add nuw nsw i32 %num_cols_needed.06, %inc
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, %wide.trip.count
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !14
}

!5 = !{!6, !6, i64 0}
!6 = !{!"short", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = distinct !{!9, !10, !11, !12}
!10 = !{!"llvm.loop.mustprogress"}
!11 = !{!"llvm.loop.isvectorized", i32 1}
!12 = !{!"llvm.loop.unroll.runtime.disable"}
!13 = distinct !{!13, !10, !11, !12}
!14 = distinct !{!14, !10, !12, !11}
