; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -verify-machineinstrs -mcpu=g5 -mtriple=powerpc64-unknown-linux-gnu -ppc-asm-full-reg-names < %s | FileCheck %s
; Check that the peephole optimizer knows about sext and zext instructions.
; CHECK: test1sext
define i32 @test1sext(i64 %A, i64 %B, ptr %P, ptr %P2) nounwind {
; CHECK-LABEL: test1sext:
; CHECK:       # %bb.0:
; CHECK-NEXT:    add r4, r3, r4
; CHECK-NEXT:    sldi r3, r4, 32
; CHECK-NEXT:    sradi r3, r3, 32
; CHECK-NEXT:    std r3, 0(r6)
; CHECK-NEXT:    add r3, r4, r4
; CHECK-NEXT:    stw r4, 0(r5)
; CHECK-NEXT:    blr
  %C = add i64 %A, %B
  %D = trunc i64 %C to i32
  %E = shl i64 %C, 32
  %F = ashr i64 %E, 32
  store volatile i64 %F, ptr %P2
  store volatile i32 %D, ptr %P
  ; Reuse low bits of extended register, don't extend live range of SUM.
  %R = add i32 %D, %D
  ret i32 %R
}
