# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=powerpc64-unknown-linux-gnu -run-pass=ppc-reduce-cr-ops \
# RUN:   -verify-machineinstrs -o - %s | FileCheck %s

---
name:            subreg_folding_regression
tracksRegLiveness: true
isSSA:           true
body:             |
  ; CHECK-LABEL: name: subreg_folding_regression
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:g8rc_and_g8rc_nox0 = COPY $x3
  ; CHECK-NEXT:   [[LD:%[0-9]+]]:g8rc = LD 0, [[COPY]] :: (load (s64))
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x20000000), %bb.3(0x60000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:g8rc_and_g8rc_nox0 = PHI [[LD]], %bb.0, %3, %bb.3, %4, %bb.2
  ; CHECK-NEXT:   [[LBZ:%[0-9]+]]:gprc = LBZ 0, [[PHI]] :: (load (s8))
  ; CHECK-NEXT:   [[CMPWI:%[0-9]+]]:crrc = CMPWI killed [[LBZ]], 0
  ; CHECK-NEXT:   [[ADDI8_:%[0-9]+]]:g8rc = nuw ADDI8 [[PHI]], 1
  ; CHECK-NEXT:   STD [[ADDI8_]], 0, [[COPY]] :: (store (s64))
  ; CHECK-NEXT:   [[LBZ1:%[0-9]+]]:gprc = LBZ 1, [[PHI]] :: (load (s8))
  ; CHECK-NEXT:   BCn [[CMPWI]].sub_lt, %bb.2
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.1(0x55555555), %bb.2(0x2aaaaaab)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[CMPWI1:%[0-9]+]]:crrc = CMPWI killed [[LBZ1]], 0
  ; CHECK-NEXT:   BC killed [[CMPWI1]].sub_eq, %bb.1
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDI8_1:%[0-9]+]]:g8rc = nuw ADDI8 [[PHI]], 2
  ; CHECK-NEXT:   STD [[ADDI8_1]], 0, [[COPY]] :: (store (s64))
  ; CHECK-NEXT:   B %bb.1
  bb.0:
    liveins: $x3

    %0:g8rc_and_g8rc_nox0 = COPY $x3
    %1:g8rc = LD 0, %0 :: (load (s64))

  bb.1:
    %2:g8rc_and_g8rc_nox0 = PHI %1, %bb.0, %3, %bb.1, %4, %bb.2
    %5:gprc = LBZ 0, %2 :: (load (s8))
    %6:crrc = CMPWI killed %5, 0
    %3:g8rc = nuw ADDI8 %2, 1
    STD %3, 0, %0 :: (store (s64))
    %7:gprc = LBZ 1, %2 :: (load (s8))
    %8:crrc = CMPWI killed %7, 0
    %9:crbitrc = CRAND %8.sub_eq, %6.sub_lt
    BC killed %9, %bb.1
    B %bb.2

  bb.2:
    %4:g8rc = nuw ADDI8 %2, 2
    STD %4, 0, %0 :: (store (s64))
    B %bb.1

...
