; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -verify-machineinstrs -mtriple=powerpc64-ibm-aix -mcpu=pwr9 \
; RUN:   -mattr=+float16,+vsx,+power9-vector < %s | FileCheck %s --check-prefix=P9-AIX-64
; RUN: llc -verify-machineinstrs -mtriple=powerpc-ibm-aix -mcpu=pwr9 \
; RUN:   -mattr=+float16,+vsx,+power9-vector < %s | FileCheck %s --check-prefix=P9-AIX-32

; 14th f16 argument goes to stack.
; The first 13 f16 args exhaust F1-F13. The 14th must come from the PSA.
; PSA starts at SP+48 on PPC64 AIX. With 8-byte slots, the 14th arg is at
; SP+48+(13*8)=SP+152. This confirms each preceding slot was 8 bytes wide.
define half @test_14th_arg(
; P9-AIX-64-LABEL: test_14th_arg:
; P9-AIX-64:       # %bb.0:
; P9-AIX-64-NEXT:    addi 3, 1, 152
; P9-AIX-64-NEXT:    lxsihzx 1, 0, 3
; P9-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_14th_arg:
; P9-AIX-32:       # %bb.0:
; P9-AIX-32-NEXT:    addi 3, 1, 76
; P9-AIX-32-NEXT:    lxsihzx 1, 0, 3
; P9-AIX-32-NEXT:    blr
    half %a0, half %a1, half %a2, half %a3,
    half %a4, half %a5, half %a6, half %a7,
    half %a8, half %a9, half %a10, half %a11,
    half %a12, half %a13) {
    ret half %a13
}

; Mixed f16 and i64 arguments.
; Verifies GPR shadow is consumed for each f16 argument.
; Expected register layout on PPC64 AIX:
;   %f0 (half) -> F1, GPR shadow consumes X3
;   %i0 (i64)  -> X4
;   %f1 (half) -> F2, GPR shadow consumes X5
;   %i1 (i64)  -> X6
; If GPR shadow is missing, %i1 would land in X4 instead of X6.
; The return value %i1 must come from X6 (mr 3, 6).
define i64 @test_mixed_args(half %f0, i64 %i0, half %f1, i64 %i1) {
; P9-AIX-64-LABEL: test_mixed_args:
; P9-AIX-64:       # %bb.0:
; P9-AIX-64-NEXT:    mr 3, 6
; P9-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_mixed_args:
; P9-AIX-32:       # %bb.0:
; P9-AIX-32-NEXT:    mr 4, 8
; P9-AIX-32-NEXT:    mr 3, 7
; P9-AIX-32-NEXT:    blr
    ret i64 %i1
}

; Vararg function receiving f16 arguments.
; Verifies GPR shadow slots are saved to PSA for vararg access.
; X4-X10 must be saved starting at SP+56 (immediately after %count slot).
; The first vararg f16 value must be loaded via lxsihzx from SP+56.
declare void @llvm.va_start(ptr)
declare void @llvm.va_end(ptr)

define half @test_vararg_f16(i32 %count, ...) {
; P9-AIX-64-LABEL: test_vararg_f16:
; P9-AIX-64:       # %bb.0: # %entry
; P9-AIX-64-NEXT:    addi 3, 1, 58
; P9-AIX-64-NEXT:    std 4, 56(1)
; P9-AIX-64-NEXT:    std 5, 64(1)
; P9-AIX-64-NEXT:    std 6, 72(1)
; P9-AIX-64-NEXT:    std 7, 80(1)
; P9-AIX-64-NEXT:    std 8, 88(1)
; P9-AIX-64-NEXT:    std 9, 96(1)
; P9-AIX-64-NEXT:    std 10, 104(1)
; P9-AIX-64-NEXT:    std 3, -8(1)
; P9-AIX-64-NEXT:    addi 3, 1, 56
; P9-AIX-64-NEXT:    lxsihzx 1, 0, 3
; P9-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_vararg_f16:
; P9-AIX-32:       # %bb.0: # %entry
; P9-AIX-32-NEXT:    addi 3, 1, 30
; P9-AIX-32-NEXT:    stw 4, 28(1)
; P9-AIX-32-NEXT:    stw 5, 32(1)
; P9-AIX-32-NEXT:    stw 6, 36(1)
; P9-AIX-32-NEXT:    stw 7, 40(1)
; P9-AIX-32-NEXT:    stw 8, 44(1)
; P9-AIX-32-NEXT:    stw 9, 48(1)
; P9-AIX-32-NEXT:    stw 10, 52(1)
; P9-AIX-32-NEXT:    stw 3, -4(1)
; P9-AIX-32-NEXT:    addi 3, 1, 28
; P9-AIX-32-NEXT:    lxsihzx 1, 0, 3
; P9-AIX-32-NEXT:    blr
entry:
    %va = alloca ptr
    call void @llvm.va_start(ptr %va)
    %val = va_arg ptr %va, half
    call void @llvm.va_end(ptr %va)
    ret half %val
}
