; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -verify-machineinstrs -mtriple=powerpc-ibm-aix -mcpu=pwr8 \
; RUN:   -mattr=+float16 < %s | FileCheck %s --check-prefix=P8-AIX-32
; RUN: llc -verify-machineinstrs -mtriple=powerpc64-ibm-aix -mcpu=pwr8 \
; RUN:   -mattr=+float16 < %s | FileCheck %s --check-prefix=P8-AIX-64
; RUN: llc -verify-machineinstrs -mtriple=powerpc-ibm-aix -mcpu=pwr9 \
; RUN:   -mattr=+float16,+vsx,+power9-vector < %s | FileCheck %s --check-prefixes=P9,P9-AIX-32
; RUN: llc -verify-machineinstrs -mtriple=powerpc64-ibm-aix -mcpu=pwr9 \
; RUN:   -mattr=+float16,+vsx,+power9-vector < %s | FileCheck %s --check-prefixes=P9,P9-AIX-64
; RUN: llc -verify-machineinstrs -mtriple=powerpc64le-linux-gnu -mcpu=pwr8 \
; RUN:   -mattr=+float16 < %s | FileCheck %s --check-prefix=P8-LINUX-64
; RUN: llc -verify-machineinstrs -mtriple=powerpc64le-linux-gnu -mcpu=pwr9 \
; RUN:   -mattr=+float16,+vsx,+power9-vector < %s | FileCheck %s --check-prefixes=P9,P9-LINUX-64

; ========================================================================================
; Load/Store Operations
; ISD::LOAD, ISD::STORE
; ========================================================================================

define half @load_half(ptr %p) nounwind {
; P8-AIX-32-LABEL: load_half:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    lhzx 3, 0, 3
; P8-AIX-32-NEXT:    mtfprwz 1, 3
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: load_half:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    lhzx 3, 0, 3
; P8-AIX-64-NEXT:    mtfprwz 1, 3
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: load_half:
; P9:       # %bb.0: # %entry
; P9-NEXT:    lxsihzx 1, 0, 3
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: load_half:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    lhzx 3, 0, 3
; P8-LINUX-64-NEXT:    mtfprwz 1, 3
; P8-LINUX-64-NEXT:    blr
entry:
  %v = load half, ptr %p
  ret half %v
}

define void @store_half(ptr %p, half %v) nounwind {
; P8-AIX-32-LABEL: store_half:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mffprwz 4, 1
; P8-AIX-32-NEXT:    sthx 4, 0, 3
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: store_half:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mffprwz 4, 1
; P8-AIX-64-NEXT:    sthx 4, 0, 3
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: store_half:
; P9:       # %bb.0: # %entry
; P9-NEXT:    stxsihx 1, 0, 3
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: store_half:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mffprwz 4, 1
; P8-LINUX-64-NEXT:    sthx 4, 0, 3
; P8-LINUX-64-NEXT:    blr
entry:
  store half %v, ptr %p
  ret void
}

; ========================================================================================
; Basic Arithmetic Operations
; ISD::FADD, ISD::FSUB, ISD::FMUL, ISD::FDIV
; ========================================================================================

define half @op_add(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: op_add:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xsaddsp 1, 1, 30
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_add:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xsaddsp 1, 1, 30
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_add:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 2
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    xsaddsp 0, 1, 0
; P9-NEXT:    xscvdphp 1, 0
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_add:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xsaddsp 1, 1, 30
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %unpromotion = fadd half %a, %b
  ret half %unpromotion
}

define half @op_sub(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: op_sub:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xssubsp 1, 1, 30
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_sub:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xssubsp 1, 1, 30
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_sub:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 2
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    xssubsp 0, 1, 0
; P9-NEXT:    xscvdphp 1, 0
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_sub:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xssubsp 1, 1, 30
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %unpromotion = fsub half %a, %b
  ret half %unpromotion
}

define half @op_mul(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: op_mul:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xsmulsp 1, 1, 30
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_mul:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xsmulsp 1, 1, 30
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_mul:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 2
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    xsmulsp 0, 1, 0
; P9-NEXT:    xscvdphp 1, 0
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_mul:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xsmulsp 1, 1, 30
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %unpromotion = fmul half %a, %b
  ret half %unpromotion
}

define half @op_div(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: op_div:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xsdivsp 1, 1, 30
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_div:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xsdivsp 1, 1, 30
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_div:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 2
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    xsdivsp 0, 1, 0
; P9-NEXT:    xscvdphp 1, 0
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_div:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xsdivsp 1, 1, 30
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %unpromotion = fdiv half %a, %b
  ret half %unpromotion
}

; ========================================================================================
; Advanced Arithmetic Operations
; ISD::FMA (promoted to f64), ISD::FSQRT, ISD::FREM
; ========================================================================================

define half @test_fma(half %a, half %b, half %c) nounwind {
; P8-AIX-32-LABEL: test_fma:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 29, 56(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 30, 2
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 3
; P8-AIX-32-NEXT:    bl .__extendhfdf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 29, 1
; P8-AIX-32-NEXT:    fmr 1, 30
; P8-AIX-32-NEXT:    bl .__extendhfdf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfdf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xsmaddadp 1, 29, 30
; P8-AIX-32-NEXT:    bl .__truncdfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 29, 56(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_fma:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -144(1)
; P8-AIX-64-NEXT:    std 0, 160(1)
; P8-AIX-64-NEXT:    stfd 29, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    stfd 30, 128(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 30, 2
; P8-AIX-64-NEXT:    stfd 31, 136(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 3
; P8-AIX-64-NEXT:    bl .__extendhfdf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 29, 1
; P8-AIX-64-NEXT:    fmr 1, 30
; P8-AIX-64-NEXT:    bl .__extendhfdf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfdf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xsmaddadp 1, 29, 30
; P8-AIX-64-NEXT:    bl .__truncdfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    lfd 31, 136(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 128(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 29, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    addi 1, 1, 144
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: test_fma:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 2
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    xscvhpdp 2, 3
; P9-NEXT:    xsmaddadp 2, 1, 0
; P9-NEXT:    xscvdphp 1, 2
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_fma:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 29, -24(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -64(1)
; P8-LINUX-64-NEXT:    std 0, 80(1)
; P8-LINUX-64-NEXT:    fmr 31, 3
; P8-LINUX-64-NEXT:    fmr 30, 2
; P8-LINUX-64-NEXT:    bl __extendhfdf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 29, 1
; P8-LINUX-64-NEXT:    fmr 1, 30
; P8-LINUX-64-NEXT:    bl __extendhfdf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfdf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xsmaddadp 1, 29, 30
; P8-LINUX-64-NEXT:    bl __truncdfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 64
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    lfd 29, -24(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    blr
entry:
    %r = call half @llvm.fma.f16(half %a, half %b, half %c)
    ret half %r
}

define half @test_sqrt(half %a) {
; P8-AIX-32-LABEL: test_sqrt:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xssqrtsp 1, 1
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_sqrt:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xssqrtsp 1, 1
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: test_sqrt:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 1
; P9-NEXT:    xssqrtsp 0, 0
; P9-NEXT:    xscvdphp 1, 0
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_sqrt:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    .cfi_def_cfa_offset 32
; P8-LINUX-64-NEXT:    .cfi_offset lr, 16
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xssqrtsp 1, 1
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
    %r = call half @llvm.sqrt.f16(half %a)
    ret half %r
}

define half @test_frem(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: test_frem:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 2, 30
; P8-AIX-32-NEXT:    bl .fmodf[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_frem:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 2, 30
; P8-AIX-64-NEXT:    bl .fmodf[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_frem:
; P9-AIX-32:       # %bb.0: # %entry
; P9-AIX-32-NEXT:    mflr 0
; P9-AIX-32-NEXT:    stwu 1, -64(1)
; P9-AIX-32-NEXT:    stw 0, 72(1)
; P9-AIX-32-NEXT:    xscvhpdp 1, 1
; P9-AIX-32-NEXT:    xscvhpdp 2, 2
; P9-AIX-32-NEXT:    bl .fmodf[PR]
; P9-AIX-32-NEXT:    nop
; P9-AIX-32-NEXT:    xscvdphp 1, 1
; P9-AIX-32-NEXT:    addi 1, 1, 64
; P9-AIX-32-NEXT:    lwz 0, 8(1)
; P9-AIX-32-NEXT:    mtlr 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: test_frem:
; P9-AIX-64:       # %bb.0: # %entry
; P9-AIX-64-NEXT:    mflr 0
; P9-AIX-64-NEXT:    stdu 1, -112(1)
; P9-AIX-64-NEXT:    std 0, 128(1)
; P9-AIX-64-NEXT:    xscvhpdp 1, 1
; P9-AIX-64-NEXT:    xscvhpdp 2, 2
; P9-AIX-64-NEXT:    bl .fmodf[PR]
; P9-AIX-64-NEXT:    nop
; P9-AIX-64-NEXT:    xscvdphp 1, 1
; P9-AIX-64-NEXT:    addi 1, 1, 112
; P9-AIX-64-NEXT:    ld 0, 16(1)
; P9-AIX-64-NEXT:    mtlr 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_frem:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 2, 30
; P8-LINUX-64-NEXT:    bl fmodf
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: test_frem:
; P9-LINUX-64:       # %bb.0: # %entry
; P9-LINUX-64-NEXT:    mflr 0
; P9-LINUX-64-NEXT:    stdu 1, -32(1)
; P9-LINUX-64-NEXT:    std 0, 48(1)
; P9-LINUX-64-NEXT:    xscvhpdp 1, 1
; P9-LINUX-64-NEXT:    xscvhpdp 2, 2
; P9-LINUX-64-NEXT:    bl fmodf
; P9-LINUX-64-NEXT:    nop
; P9-LINUX-64-NEXT:    xscvdphp 1, 1
; P9-LINUX-64-NEXT:    addi 1, 1, 32
; P9-LINUX-64-NEXT:    ld 0, 16(1)
; P9-LINUX-64-NEXT:    mtlr 0
; P9-LINUX-64-NEXT:    blr
entry:
    %r = frem half %a, %b
    ret half %r
}

; ========================================================================================
; Comparison Operations
; ISD::SETCC
; ========================================================================================

define zeroext i1 @op_eq(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: op_eq:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fcmpu 0, 1, 30
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    li 3, 0
; P8-AIX-32-NEXT:    li 4, 1
; P8-AIX-32-NEXT:    iseleq 3, 4, 3
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_eq:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fcmpu 0, 1, 30
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    li 3, 0
; P8-AIX-64-NEXT:    li 4, 1
; P8-AIX-64-NEXT:    iseleq 3, 4, 3
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_eq:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 2
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    li 3, 0
; P9-NEXT:    li 4, 1
; P9-NEXT:    fcmpu 0, 1, 0
; P9-NEXT:    iseleq 3, 4, 3
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_eq:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fcmpu 0, 1, 30
; P8-LINUX-64-NEXT:    li 3, 0
; P8-LINUX-64-NEXT:    li 4, 1
; P8-LINUX-64-NEXT:    iseleq 3, 4, 3
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %cmp = fcmp oeq half %a, %b
  ret i1 %cmp
}

define zeroext i1 @op_ne(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: op_ne:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fcmpu 0, 1, 30
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    li 3, 1
; P8-AIX-32-NEXT:    iseleq 3, 0, 3
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_ne:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fcmpu 0, 1, 30
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    li 3, 1
; P8-AIX-64-NEXT:    iseleq 3, 0, 3
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_ne:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 2
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    li 3, 1
; P9-NEXT:    fcmpu 0, 1, 0
; P9-NEXT:    iseleq 3, 0, 3
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_ne:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fcmpu 0, 1, 30
; P8-LINUX-64-NEXT:    li 3, 1
; P8-LINUX-64-NEXT:    iseleq 3, 0, 3
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %cmp = fcmp une half %a, %b
  ret i1 %cmp
}

define zeroext i1 @op_lt(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: op_lt:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fcmpu 0, 1, 30
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    li 3, 0
; P8-AIX-32-NEXT:    li 4, 1
; P8-AIX-32-NEXT:    isellt 3, 4, 3
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_lt:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fcmpu 0, 1, 30
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    li 3, 0
; P8-AIX-64-NEXT:    li 4, 1
; P8-AIX-64-NEXT:    isellt 3, 4, 3
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_lt:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 2
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    li 3, 0
; P9-NEXT:    li 4, 1
; P9-NEXT:    fcmpu 0, 1, 0
; P9-NEXT:    isellt 3, 4, 3
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_lt:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fcmpu 0, 1, 30
; P8-LINUX-64-NEXT:    li 3, 0
; P8-LINUX-64-NEXT:    li 4, 1
; P8-LINUX-64-NEXT:    isellt 3, 4, 3
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %cmp = fcmp olt half %a, %b
  ret i1 %cmp
}

define zeroext i1 @op_le(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: op_le:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fcmpu 0, 1, 30
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    li 3, 1
; P8-AIX-32-NEXT:    cror 20, 3, 1
; P8-AIX-32-NEXT:    isel 3, 0, 3, 20
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_le:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fcmpu 0, 1, 30
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    li 3, 1
; P8-AIX-64-NEXT:    cror 20, 3, 1
; P8-AIX-64-NEXT:    isel 3, 0, 3, 20
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_le:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 2
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    li 3, 1
; P9-NEXT:    fcmpu 0, 1, 0
; P9-NEXT:    cror 20, 3, 1
; P9-NEXT:    isel 3, 0, 3, 20
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_le:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fcmpu 0, 1, 30
; P8-LINUX-64-NEXT:    li 3, 1
; P8-LINUX-64-NEXT:    cror 20, 3, 1
; P8-LINUX-64-NEXT:    isel 3, 0, 3, 20
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %cmp = fcmp ole half %a, %b
  ret i1 %cmp
}

define zeroext i1 @op_gt(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: op_gt:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fcmpu 0, 1, 30
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    li 3, 0
; P8-AIX-32-NEXT:    li 4, 1
; P8-AIX-32-NEXT:    iselgt 3, 4, 3
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_gt:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fcmpu 0, 1, 30
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    li 3, 0
; P8-AIX-64-NEXT:    li 4, 1
; P8-AIX-64-NEXT:    iselgt 3, 4, 3
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_gt:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 2
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    li 3, 0
; P9-NEXT:    li 4, 1
; P9-NEXT:    fcmpu 0, 1, 0
; P9-NEXT:    iselgt 3, 4, 3
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_gt:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fcmpu 0, 1, 30
; P8-LINUX-64-NEXT:    li 3, 0
; P8-LINUX-64-NEXT:    li 4, 1
; P8-LINUX-64-NEXT:    iselgt 3, 4, 3
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %cmp = fcmp ogt half %a, %b
  ret i1 %cmp
}

define zeroext i1 @op_ge(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: op_ge:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fcmpu 0, 1, 30
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    li 3, 1
; P8-AIX-32-NEXT:    cror 20, 3, 0
; P8-AIX-32-NEXT:    isel 3, 0, 3, 20
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_ge:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fcmpu 0, 1, 30
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    li 3, 1
; P8-AIX-64-NEXT:    cror 20, 3, 0
; P8-AIX-64-NEXT:    isel 3, 0, 3, 20
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_ge:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 2
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    li 3, 1
; P9-NEXT:    fcmpu 0, 1, 0
; P9-NEXT:    cror 20, 3, 0
; P9-NEXT:    isel 3, 0, 3, 20
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_ge:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fcmpu 0, 1, 30
; P8-LINUX-64-NEXT:    li 3, 1
; P8-LINUX-64-NEXT:    cror 20, 3, 0
; P8-LINUX-64-NEXT:    isel 3, 0, 3, 20
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %cmp = fcmp oge half %a, %b
  ret i1 %cmp
}

; ========================================================================================
; Control Flow Operations
; ISD::SELECT, ISD::SELECT_CC
; ========================================================================================

define half @op_select(i1 %cond, half %a, half %b) nounwind {
; P8-AIX-32-LABEL: op_select:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mfcr 12
; P8-AIX-32-NEXT:    stw 12, 4(1)
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    andi. 3, 3, 1
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    crmove 8, 1
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 30
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bc 12, 8, L..BB15_2
; P8-AIX-32-NEXT:  # %bb.1: # %entry
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:  L..BB15_2: # %entry
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    lwz 12, 4(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    mtocrf 32, 12
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_select:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mfcr 12
; P8-AIX-64-NEXT:    stw 12, 8(1)
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    andi. 3, 3, 1
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    crmove 8, 1
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 30
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bc 12, 8, L..BB15_2
; P8-AIX-64-NEXT:  # %bb.1: # %entry
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:  L..BB15_2: # %entry
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    lwz 12, 8(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    mtocrf 32, 12
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: op_select:
; P9-AIX-32:       # %bb.0: # %entry
; P9-AIX-32-NEXT:    xscvhpdp 2, 2
; P9-AIX-32-NEXT:    xscvhpdp 0, 1
; P9-AIX-32-NEXT:    andi. 3, 3, 1
; P9-AIX-32-NEXT:    bc 12, 1, L..BB15_2
; P9-AIX-32-NEXT:  # %bb.1: # %entry
; P9-AIX-32-NEXT:    fmr 0, 2
; P9-AIX-32-NEXT:  L..BB15_2: # %entry
; P9-AIX-32-NEXT:    xscvdphp 1, 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: op_select:
; P9-AIX-64:       # %bb.0: # %entry
; P9-AIX-64-NEXT:    xscvhpdp 2, 2
; P9-AIX-64-NEXT:    xscvhpdp 0, 1
; P9-AIX-64-NEXT:    andi. 3, 3, 1
; P9-AIX-64-NEXT:    bc 12, 1, L..BB15_2
; P9-AIX-64-NEXT:  # %bb.1: # %entry
; P9-AIX-64-NEXT:    fmr 0, 2
; P9-AIX-64-NEXT:  L..BB15_2: # %entry
; P9-AIX-64-NEXT:    xscvdphp 1, 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_select:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mfocrf 12, 32
; P8-LINUX-64-NEXT:    stw 12, 8(1)
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    stfd 30, 32(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    andi. 3, 3, 1
; P8-LINUX-64-NEXT:    stfd 31, 40(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    crmove 8, 1
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 30
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bc 12, 8, .LBB15_2
; P8-LINUX-64-NEXT:  # %bb.1: # %entry
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:  .LBB15_2: # %entry
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    lfd 31, 40(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, 32(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lwz 12, 8(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    mtocrf 32, 12
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: op_select:
; P9-LINUX-64:       # %bb.0: # %entry
; P9-LINUX-64-NEXT:    xscvhpdp 2, 2
; P9-LINUX-64-NEXT:    xscvhpdp 0, 1
; P9-LINUX-64-NEXT:    andi. 3, 3, 1
; P9-LINUX-64-NEXT:    bc 12, 1, .LBB15_2
; P9-LINUX-64-NEXT:  # %bb.1: # %entry
; P9-LINUX-64-NEXT:    fmr 0, 2
; P9-LINUX-64-NEXT:  .LBB15_2: # %entry
; P9-LINUX-64-NEXT:    xscvdphp 1, 0
; P9-LINUX-64-NEXT:    blr
entry:
  %r = select i1 %cond, half %a, half %b
  ret half %r
}

define half @op_select_cc(half %a, half %b, half %c, half %d) nounwind {
; P8-AIX-32-LABEL: op_select_cc:
; P8-AIX-32:       # %bb.0:
; P8-AIX-32-NEXT:    mfcr 12
; P8-AIX-32-NEXT:    stw 12, 4(1)
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -96(1)
; P8-AIX-32-NEXT:    stw 0, 104(1)
; P8-AIX-32-NEXT:    stfd 29, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 29, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 28, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    stfd 30, 80(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 30, 3
; P8-AIX-32-NEXT:    stfd 31, 88(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 4
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 28, 1
; P8-AIX-32-NEXT:    fmr 1, 29
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fcmpu 2, 1, 28
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 30
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bc 12, 8, L..BB16_2
; P8-AIX-32-NEXT:  # %bb.1:
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:  L..BB16_2:
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    lfd 31, 88(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 80(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 29, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 28, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    addi 1, 1, 96
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    lwz 12, 4(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    mtocrf 32, 12
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_select_cc:
; P8-AIX-64:       # %bb.0:
; P8-AIX-64-NEXT:    mfcr 12
; P8-AIX-64-NEXT:    stw 12, 8(1)
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -144(1)
; P8-AIX-64-NEXT:    std 0, 160(1)
; P8-AIX-64-NEXT:    stfd 29, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 29, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 28, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    stfd 30, 128(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 30, 3
; P8-AIX-64-NEXT:    stfd 31, 136(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 4
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 28, 1
; P8-AIX-64-NEXT:    fmr 1, 29
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fcmpu 2, 1, 28
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 30
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bc 12, 8, L..BB16_2
; P8-AIX-64-NEXT:  # %bb.1:
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:  L..BB16_2:
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    lfd 31, 136(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 128(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 29, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 28, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    addi 1, 1, 144
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    lwz 12, 8(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    mtocrf 32, 12
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: op_select_cc:
; P9-AIX-32:       # %bb.0:
; P9-AIX-32-NEXT:    xscvhpdp 0, 2
; P9-AIX-32-NEXT:    xscvhpdp 1, 1
; P9-AIX-32-NEXT:    fcmpu 0, 1, 0
; P9-AIX-32-NEXT:    xscvhpdp 1, 4
; P9-AIX-32-NEXT:    xscvhpdp 0, 3
; P9-AIX-32-NEXT:    bc 12, 0, L..BB16_2
; P9-AIX-32-NEXT:  # %bb.1:
; P9-AIX-32-NEXT:    fmr 0, 1
; P9-AIX-32-NEXT:  L..BB16_2:
; P9-AIX-32-NEXT:    xscvdphp 1, 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: op_select_cc:
; P9-AIX-64:       # %bb.0:
; P9-AIX-64-NEXT:    xscvhpdp 0, 2
; P9-AIX-64-NEXT:    xscvhpdp 1, 1
; P9-AIX-64-NEXT:    fcmpu 0, 1, 0
; P9-AIX-64-NEXT:    xscvhpdp 1, 4
; P9-AIX-64-NEXT:    xscvhpdp 0, 3
; P9-AIX-64-NEXT:    bc 12, 0, L..BB16_2
; P9-AIX-64-NEXT:  # %bb.1:
; P9-AIX-64-NEXT:    fmr 0, 1
; P9-AIX-64-NEXT:  L..BB16_2:
; P9-AIX-64-NEXT:    xscvdphp 1, 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_select_cc:
; P8-LINUX-64:       # %bb.0:
; P8-LINUX-64-NEXT:    mfocrf 12, 32
; P8-LINUX-64-NEXT:    stw 12, 8(1)
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -64(1)
; P8-LINUX-64-NEXT:    std 0, 80(1)
; P8-LINUX-64-NEXT:    stfd 29, 40(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    fmr 29, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    stfd 28, 32(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 30, 48(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    fmr 30, 3
; P8-LINUX-64-NEXT:    stfd 31, 56(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    fmr 31, 4
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 28, 1
; P8-LINUX-64-NEXT:    fmr 1, 29
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fcmpu 2, 1, 28
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 30
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bc 12, 8, .LBB16_2
; P8-LINUX-64-NEXT:  # %bb.1:
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:  .LBB16_2:
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    lfd 31, 56(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, 48(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 29, 40(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 28, 32(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    addi 1, 1, 64
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lwz 12, 8(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    mtocrf 32, 12
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: op_select_cc:
; P9-LINUX-64:       # %bb.0:
; P9-LINUX-64-NEXT:    xscvhpdp 0, 2
; P9-LINUX-64-NEXT:    xscvhpdp 1, 1
; P9-LINUX-64-NEXT:    fcmpu 0, 1, 0
; P9-LINUX-64-NEXT:    xscvhpdp 1, 4
; P9-LINUX-64-NEXT:    xscvhpdp 0, 3
; P9-LINUX-64-NEXT:    bc 12, 0, .LBB16_2
; P9-LINUX-64-NEXT:  # %bb.1:
; P9-LINUX-64-NEXT:    fmr 0, 1
; P9-LINUX-64-NEXT:  .LBB16_2:
; P9-LINUX-64-NEXT:    xscvdphp 1, 0
; P9-LINUX-64-NEXT:    blr
  %cmp = fcmp olt half %a, %b
  %r = select i1 %cmp, half %c, half %d
  ret half %r
}

; ========================================================================================
; Min/Max Operations
; ISD::FMINNUM/FMAXNUM (non-NaN), ISD::FMINIMUM/FMAXIMUM (IEEE 754-2019, NaN-propagating)
; ========================================================================================

define half @op_fmin(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: op_fmin:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xsmindp 1, 1, 30
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_fmin:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xsmindp 1, 1, 30
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_fmin:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 2
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    xsmindp 0, 1, 0
; P9-NEXT:    xscvdphp 1, 0
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_fmin:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xsmindp 1, 1, 30
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %0 = tail call half @llvm.minnum.f16(half %a, half %b)
  ret half %0
}

define half @op_fmax(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: op_fmax:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xsmaxdp 1, 1, 30
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_fmax:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xsmaxdp 1, 1, 30
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_fmax:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 2
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    xsmaxdp 0, 1, 0
; P9-NEXT:    xscvdphp 1, 0
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_fmax:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xsmaxdp 1, 1, 30
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %0 = tail call half @llvm.maxnum.f16(half %a, half %b)
  ret half %0
}

define half @test_minimum(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: test_minimum:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 30
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fcmpu 0, 1, 31
; P8-AIX-32-NEXT:    bc 12, 3, L..BB19_2
; P8-AIX-32-NEXT:  # %bb.1: # %entry
; P8-AIX-32-NEXT:    xsmindp 1, 1, 31
; P8-AIX-32-NEXT:    b L..BB19_3
; P8-AIX-32-NEXT:  L..BB19_2:
; P8-AIX-32-NEXT:    lwz 3, L..C0(2) # %const.0
; P8-AIX-32-NEXT:    lfs 1, 0(3)
; P8-AIX-32-NEXT:  L..BB19_3: # %entry
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_minimum:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 30
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fcmpu 0, 1, 31
; P8-AIX-64-NEXT:    bc 12, 3, L..BB19_2
; P8-AIX-64-NEXT:  # %bb.1: # %entry
; P8-AIX-64-NEXT:    xsmindp 1, 1, 31
; P8-AIX-64-NEXT:    b L..BB19_3
; P8-AIX-64-NEXT:  L..BB19_2:
; P8-AIX-64-NEXT:    ld 3, L..C0(2) # %const.0
; P8-AIX-64-NEXT:    lfs 1, 0(3)
; P8-AIX-64-NEXT:  L..BB19_3: # %entry
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_minimum:
; P9-AIX-32:       # %bb.0: # %entry
; P9-AIX-32-NEXT:    xscvhpdp 0, 2
; P9-AIX-32-NEXT:    xscvhpdp 1, 1
; P9-AIX-32-NEXT:    fcmpu 0, 1, 0
; P9-AIX-32-NEXT:    bc 12, 3, L..BB19_2
; P9-AIX-32-NEXT:  # %bb.1: # %entry
; P9-AIX-32-NEXT:    xsmindp 0, 1, 0
; P9-AIX-32-NEXT:    xscvdphp 1, 0
; P9-AIX-32-NEXT:    blr
; P9-AIX-32-NEXT:  L..BB19_2:
; P9-AIX-32-NEXT:    lwz 3, L..C0(2) # %const.0
; P9-AIX-32-NEXT:    lfs 0, 0(3)
; P9-AIX-32-NEXT:    xscvdphp 1, 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: test_minimum:
; P9-AIX-64:       # %bb.0: # %entry
; P9-AIX-64-NEXT:    xscvhpdp 0, 2
; P9-AIX-64-NEXT:    xscvhpdp 1, 1
; P9-AIX-64-NEXT:    fcmpu 0, 1, 0
; P9-AIX-64-NEXT:    bc 12, 3, L..BB19_2
; P9-AIX-64-NEXT:  # %bb.1: # %entry
; P9-AIX-64-NEXT:    xsmindp 0, 1, 0
; P9-AIX-64-NEXT:    xscvdphp 1, 0
; P9-AIX-64-NEXT:    blr
; P9-AIX-64-NEXT:  L..BB19_2:
; P9-AIX-64-NEXT:    ld 3, L..C0(2) # %const.0
; P9-AIX-64-NEXT:    lfs 0, 0(3)
; P9-AIX-64-NEXT:    xscvdphp 1, 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_minimum:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 30
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fcmpu 0, 1, 31
; P8-LINUX-64-NEXT:    bc 12, 3, .LBB19_2
; P8-LINUX-64-NEXT:  # %bb.1: # %entry
; P8-LINUX-64-NEXT:    xsmindp 1, 1, 31
; P8-LINUX-64-NEXT:    b .LBB19_3
; P8-LINUX-64-NEXT:  .LBB19_2:
; P8-LINUX-64-NEXT:    addis 3, 2, .LCPI19_0@toc@ha
; P8-LINUX-64-NEXT:    lfs 1, .LCPI19_0@toc@l(3)
; P8-LINUX-64-NEXT:  .LBB19_3: # %entry
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: test_minimum:
; P9-LINUX-64:       # %bb.0: # %entry
; P9-LINUX-64-NEXT:    xscvhpdp 0, 2
; P9-LINUX-64-NEXT:    xscvhpdp 1, 1
; P9-LINUX-64-NEXT:    fcmpu 0, 1, 0
; P9-LINUX-64-NEXT:    bc 12, 3, .LBB19_2
; P9-LINUX-64-NEXT:  # %bb.1: # %entry
; P9-LINUX-64-NEXT:    xsmindp 0, 1, 0
; P9-LINUX-64-NEXT:    xscvdphp 1, 0
; P9-LINUX-64-NEXT:    blr
; P9-LINUX-64-NEXT:  .LBB19_2:
; P9-LINUX-64-NEXT:    addis 3, 2, .LCPI19_0@toc@ha
; P9-LINUX-64-NEXT:    lfs 0, .LCPI19_0@toc@l(3)
; P9-LINUX-64-NEXT:    xscvdphp 1, 0
; P9-LINUX-64-NEXT:    blr
entry:
    %r = call half @llvm.minimum.f16(half %a, half %b)
    ret half %r
}

define half @test_maximum(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: test_maximum:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 30
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fcmpu 0, 1, 31
; P8-AIX-32-NEXT:    bc 12, 3, L..BB20_2
; P8-AIX-32-NEXT:  # %bb.1: # %entry
; P8-AIX-32-NEXT:    xsmaxdp 1, 1, 31
; P8-AIX-32-NEXT:    b L..BB20_3
; P8-AIX-32-NEXT:  L..BB20_2:
; P8-AIX-32-NEXT:    lwz 3, L..C1(2) # %const.0
; P8-AIX-32-NEXT:    lfs 1, 0(3)
; P8-AIX-32-NEXT:  L..BB20_3: # %entry
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_maximum:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 30
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fcmpu 0, 1, 31
; P8-AIX-64-NEXT:    bc 12, 3, L..BB20_2
; P8-AIX-64-NEXT:  # %bb.1: # %entry
; P8-AIX-64-NEXT:    xsmaxdp 1, 1, 31
; P8-AIX-64-NEXT:    b L..BB20_3
; P8-AIX-64-NEXT:  L..BB20_2:
; P8-AIX-64-NEXT:    ld 3, L..C1(2) # %const.0
; P8-AIX-64-NEXT:    lfs 1, 0(3)
; P8-AIX-64-NEXT:  L..BB20_3: # %entry
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_maximum:
; P9-AIX-32:       # %bb.0: # %entry
; P9-AIX-32-NEXT:    xscvhpdp 0, 2
; P9-AIX-32-NEXT:    xscvhpdp 1, 1
; P9-AIX-32-NEXT:    fcmpu 0, 1, 0
; P9-AIX-32-NEXT:    bc 12, 3, L..BB20_2
; P9-AIX-32-NEXT:  # %bb.1: # %entry
; P9-AIX-32-NEXT:    xsmaxdp 0, 1, 0
; P9-AIX-32-NEXT:    xscvdphp 1, 0
; P9-AIX-32-NEXT:    blr
; P9-AIX-32-NEXT:  L..BB20_2:
; P9-AIX-32-NEXT:    lwz 3, L..C1(2) # %const.0
; P9-AIX-32-NEXT:    lfs 0, 0(3)
; P9-AIX-32-NEXT:    xscvdphp 1, 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: test_maximum:
; P9-AIX-64:       # %bb.0: # %entry
; P9-AIX-64-NEXT:    xscvhpdp 0, 2
; P9-AIX-64-NEXT:    xscvhpdp 1, 1
; P9-AIX-64-NEXT:    fcmpu 0, 1, 0
; P9-AIX-64-NEXT:    bc 12, 3, L..BB20_2
; P9-AIX-64-NEXT:  # %bb.1: # %entry
; P9-AIX-64-NEXT:    xsmaxdp 0, 1, 0
; P9-AIX-64-NEXT:    xscvdphp 1, 0
; P9-AIX-64-NEXT:    blr
; P9-AIX-64-NEXT:  L..BB20_2:
; P9-AIX-64-NEXT:    ld 3, L..C1(2) # %const.0
; P9-AIX-64-NEXT:    lfs 0, 0(3)
; P9-AIX-64-NEXT:    xscvdphp 1, 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_maximum:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 30
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fcmpu 0, 1, 31
; P8-LINUX-64-NEXT:    bc 12, 3, .LBB20_2
; P8-LINUX-64-NEXT:  # %bb.1: # %entry
; P8-LINUX-64-NEXT:    xsmaxdp 1, 1, 31
; P8-LINUX-64-NEXT:    b .LBB20_3
; P8-LINUX-64-NEXT:  .LBB20_2:
; P8-LINUX-64-NEXT:    addis 3, 2, .LCPI20_0@toc@ha
; P8-LINUX-64-NEXT:    lfs 1, .LCPI20_0@toc@l(3)
; P8-LINUX-64-NEXT:  .LBB20_3: # %entry
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: test_maximum:
; P9-LINUX-64:       # %bb.0: # %entry
; P9-LINUX-64-NEXT:    xscvhpdp 0, 2
; P9-LINUX-64-NEXT:    xscvhpdp 1, 1
; P9-LINUX-64-NEXT:    fcmpu 0, 1, 0
; P9-LINUX-64-NEXT:    bc 12, 3, .LBB20_2
; P9-LINUX-64-NEXT:  # %bb.1: # %entry
; P9-LINUX-64-NEXT:    xsmaxdp 0, 1, 0
; P9-LINUX-64-NEXT:    xscvdphp 1, 0
; P9-LINUX-64-NEXT:    blr
; P9-LINUX-64-NEXT:  .LBB20_2:
; P9-LINUX-64-NEXT:    addis 3, 2, .LCPI20_0@toc@ha
; P9-LINUX-64-NEXT:    lfs 0, .LCPI20_0@toc@l(3)
; P9-LINUX-64-NEXT:    xscvdphp 1, 0
; P9-LINUX-64-NEXT:    blr
entry:
    %r = call half @llvm.maximum.f16(half %a, half %b)
    ret half %r
}

; ========================================================================================
; Rounding Operations
; ISD::FCEIL, ISD::FFLOOR, ISD::FTRUNC, ISD::FROUND, ISD::FRINT, ISD::FNEARBYINT, ISD::FROUNDEVEN
; ========================================================================================

define half @op_ceil(half %a) nounwind {
; P8-AIX-32-LABEL: op_ceil:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xsrdpip 1, 1
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_ceil:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xsrdpip 1, 1
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_ceil:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 1
; P9-NEXT:    xsrdpip 0, 0
; P9-NEXT:    xscvdphp 1, 0
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_ceil:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xsrdpip 1, 1
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %0 = tail call half @llvm.ceil.f16(half %a)
  ret half %0
}

define half @op_floor(half %a) nounwind {
; P8-AIX-32-LABEL: op_floor:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xsrdpim 1, 1
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_floor:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xsrdpim 1, 1
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_floor:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 1
; P9-NEXT:    xsrdpim 0, 0
; P9-NEXT:    xscvdphp 1, 0
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_floor:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xsrdpim 1, 1
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %0 = tail call half @llvm.floor.f16(half %a)
  ret half %0
}

define half @op_trunc(half %a) nounwind {
; P8-AIX-32-LABEL: op_trunc:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xsrdpiz 1, 1
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_trunc:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xsrdpiz 1, 1
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_trunc:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 1
; P9-NEXT:    xsrdpiz 0, 0
; P9-NEXT:    xscvdphp 1, 0
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_trunc:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xsrdpiz 1, 1
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %0 = tail call half @llvm.trunc.f16(half %a)
  ret half %0
}

define half @op_round(half %a) nounwind {
; P8-AIX-32-LABEL: op_round:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xsrdpi 1, 1
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_round:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xsrdpi 1, 1
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_round:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 1
; P9-NEXT:    xsrdpi 0, 0
; P9-NEXT:    xscvdphp 1, 0
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_round:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xsrdpi 1, 1
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %0 = tail call half @llvm.round.f16(half %a)
  ret half %0
}

define half @op_rint(half %a) nounwind {
; P8-AIX-32-LABEL: op_rint:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xsrdpic 1, 1
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_rint:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xsrdpic 1, 1
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_rint:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 1
; P9-NEXT:    xsrdpic 0, 0
; P9-NEXT:    xscvdphp 1, 0
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_rint:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xsrdpic 1, 1
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %0 = tail call half @llvm.rint.f16(half %a)
  ret half %0
}

define half @op_nearbyint(half %a) nounwind {
; P8-AIX-32-LABEL: op_nearbyint:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .nearbyintf[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_nearbyint:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .nearbyintf[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: op_nearbyint:
; P9-AIX-32:       # %bb.0: # %entry
; P9-AIX-32-NEXT:    mflr 0
; P9-AIX-32-NEXT:    stwu 1, -64(1)
; P9-AIX-32-NEXT:    stw 0, 72(1)
; P9-AIX-32-NEXT:    xscvhpdp 1, 1
; P9-AIX-32-NEXT:    bl .nearbyintf[PR]
; P9-AIX-32-NEXT:    nop
; P9-AIX-32-NEXT:    xscvdphp 1, 1
; P9-AIX-32-NEXT:    addi 1, 1, 64
; P9-AIX-32-NEXT:    lwz 0, 8(1)
; P9-AIX-32-NEXT:    mtlr 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: op_nearbyint:
; P9-AIX-64:       # %bb.0: # %entry
; P9-AIX-64-NEXT:    mflr 0
; P9-AIX-64-NEXT:    stdu 1, -112(1)
; P9-AIX-64-NEXT:    std 0, 128(1)
; P9-AIX-64-NEXT:    xscvhpdp 1, 1
; P9-AIX-64-NEXT:    bl .nearbyintf[PR]
; P9-AIX-64-NEXT:    nop
; P9-AIX-64-NEXT:    xscvdphp 1, 1
; P9-AIX-64-NEXT:    addi 1, 1, 112
; P9-AIX-64-NEXT:    ld 0, 16(1)
; P9-AIX-64-NEXT:    mtlr 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_nearbyint:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl nearbyintf
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: op_nearbyint:
; P9-LINUX-64:       # %bb.0: # %entry
; P9-LINUX-64-NEXT:    mflr 0
; P9-LINUX-64-NEXT:    stdu 1, -32(1)
; P9-LINUX-64-NEXT:    std 0, 48(1)
; P9-LINUX-64-NEXT:    xscvhpdp 1, 1
; P9-LINUX-64-NEXT:    bl nearbyintf
; P9-LINUX-64-NEXT:    nop
; P9-LINUX-64-NEXT:    xscvdphp 1, 1
; P9-LINUX-64-NEXT:    addi 1, 1, 32
; P9-LINUX-64-NEXT:    ld 0, 16(1)
; P9-LINUX-64-NEXT:    mtlr 0
; P9-LINUX-64-NEXT:    blr
entry:
  %0 = tail call half @llvm.nearbyint.f16(half %a)
  ret half %0
}

define half @test_roundeven(half %a) nounwind {
; P8-AIX-32-LABEL: test_roundeven:
; P8-AIX-32:       # %bb.0:
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .roundevenf[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_roundeven:
; P8-AIX-64:       # %bb.0:
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .roundevenf[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_roundeven:
; P9-AIX-32:       # %bb.0:
; P9-AIX-32-NEXT:    mflr 0
; P9-AIX-32-NEXT:    stwu 1, -64(1)
; P9-AIX-32-NEXT:    stw 0, 72(1)
; P9-AIX-32-NEXT:    xscvhpdp 1, 1
; P9-AIX-32-NEXT:    bl .roundevenf[PR]
; P9-AIX-32-NEXT:    nop
; P9-AIX-32-NEXT:    xscvdphp 1, 1
; P9-AIX-32-NEXT:    addi 1, 1, 64
; P9-AIX-32-NEXT:    lwz 0, 8(1)
; P9-AIX-32-NEXT:    mtlr 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: test_roundeven:
; P9-AIX-64:       # %bb.0:
; P9-AIX-64-NEXT:    mflr 0
; P9-AIX-64-NEXT:    stdu 1, -112(1)
; P9-AIX-64-NEXT:    std 0, 128(1)
; P9-AIX-64-NEXT:    xscvhpdp 1, 1
; P9-AIX-64-NEXT:    bl .roundevenf[PR]
; P9-AIX-64-NEXT:    nop
; P9-AIX-64-NEXT:    xscvdphp 1, 1
; P9-AIX-64-NEXT:    addi 1, 1, 112
; P9-AIX-64-NEXT:    ld 0, 16(1)
; P9-AIX-64-NEXT:    mtlr 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_roundeven:
; P8-LINUX-64:       # %bb.0:
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl roundevenf
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: test_roundeven:
; P9-LINUX-64:       # %bb.0:
; P9-LINUX-64-NEXT:    mflr 0
; P9-LINUX-64-NEXT:    stdu 1, -32(1)
; P9-LINUX-64-NEXT:    std 0, 48(1)
; P9-LINUX-64-NEXT:    xscvhpdp 1, 1
; P9-LINUX-64-NEXT:    bl roundevenf
; P9-LINUX-64-NEXT:    nop
; P9-LINUX-64-NEXT:    xscvdphp 1, 1
; P9-LINUX-64-NEXT:    addi 1, 1, 32
; P9-LINUX-64-NEXT:    ld 0, 16(1)
; P9-LINUX-64-NEXT:    mtlr 0
; P9-LINUX-64-NEXT:    blr
    %r = call half @llvm.roundeven.f16(half %a)
    ret half %r
}

; ========================================================================================
; Bit Manipulation Operations
; ISD::FABS, ISD::FNEG, ISD::FCOPYSIGN
; ========================================================================================

define half @test_fabs(half %a) nounwind {
; P8-AIX-32-LABEL: test_fabs:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mffprwz 3, 1
; P8-AIX-32-NEXT:    clrlwi 3, 3, 17
; P8-AIX-32-NEXT:    mtfprwz 1, 3
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_fabs:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mffprwz 3, 1
; P8-AIX-64-NEXT:    clrlwi 3, 3, 17
; P8-AIX-64-NEXT:    mtfprwz 1, 3
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: test_fabs:
; P9:       # %bb.0: # %entry
; P9-NEXT:    mffprwz 3, 1
; P9-NEXT:    clrlwi 3, 3, 17
; P9-NEXT:    mtfprwz 1, 3
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_fabs:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mffprwz 3, 1
; P8-LINUX-64-NEXT:    clrlwi 3, 3, 17
; P8-LINUX-64-NEXT:    mtfprwz 1, 3
; P8-LINUX-64-NEXT:    blr
entry:
    %r = call half @llvm.fabs.f16(half %a)
    ret half %r
}

define half @test_fneg(half %a) nounwind {
; P8-AIX-32-LABEL: test_fneg:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mffprwz 3, 1
; P8-AIX-32-NEXT:    xori 3, 3, 32768
; P8-AIX-32-NEXT:    mtfprwz 1, 3
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_fneg:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mffprwz 3, 1
; P8-AIX-64-NEXT:    xori 3, 3, 32768
; P8-AIX-64-NEXT:    mtfprwz 1, 3
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: test_fneg:
; P9:       # %bb.0: # %entry
; P9-NEXT:    mffprwz 3, 1
; P9-NEXT:    xori 3, 3, 32768
; P9-NEXT:    mtfprwz 1, 3
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_fneg:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mffprwz 3, 1
; P8-LINUX-64-NEXT:    xori 3, 3, 32768
; P8-LINUX-64-NEXT:    mtfprwz 1, 3
; P8-LINUX-64-NEXT:    blr
entry:
    %r = fneg half %a
    ret half %r
}

define half @test_fcopysign(half %mag, half %sign) nounwind {
; P8-AIX-32-LABEL: test_fcopysign:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mffprwz 3, 2
; P8-AIX-32-NEXT:    mffprwz 4, 1
; P8-AIX-32-NEXT:    rlwinm 3, 3, 0, 16, 16
; P8-AIX-32-NEXT:    clrlwi 4, 4, 17
; P8-AIX-32-NEXT:    or 3, 4, 3
; P8-AIX-32-NEXT:    mtfprwz 1, 3
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_fcopysign:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mffprwz 3, 2
; P8-AIX-64-NEXT:    mffprwz 4, 1
; P8-AIX-64-NEXT:    rlwinm 3, 3, 0, 16, 16
; P8-AIX-64-NEXT:    clrlwi 4, 4, 17
; P8-AIX-64-NEXT:    or 3, 4, 3
; P8-AIX-64-NEXT:    mtfprwz 1, 3
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: test_fcopysign:
; P9:       # %bb.0: # %entry
; P9-NEXT:    mffprwz 3, 2
; P9-NEXT:    mffprwz 4, 1
; P9-NEXT:    rlwinm 3, 3, 0, 16, 16
; P9-NEXT:    clrlwi 4, 4, 17
; P9-NEXT:    or 3, 4, 3
; P9-NEXT:    mtfprwz 1, 3
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_fcopysign:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mffprwz 3, 2
; P8-LINUX-64-NEXT:    mffprwz 4, 1
; P8-LINUX-64-NEXT:    rlwinm 3, 3, 0, 16, 16
; P8-LINUX-64-NEXT:    clrlwi 4, 4, 17
; P8-LINUX-64-NEXT:    or 3, 4, 3
; P8-LINUX-64-NEXT:    mtfprwz 1, 3
; P8-LINUX-64-NEXT:    blr
entry:
    %r = call half @llvm.copysign.f16(half %mag, half %sign)
    ret half %r
}

; ========================================================================================
; Special Operations
; ISD::FCANONICALIZE - Canonicalize NaN representation
; ========================================================================================

define half @test_canonicalize(half %a) nounwind {
; P8-AIX-32-LABEL: test_canonicalize:
; P8-AIX-32:       # %bb.0:
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xsmaxdp 1, 1, 1
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_canonicalize:
; P8-AIX-64:       # %bb.0:
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xsmaxdp 1, 1, 1
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: test_canonicalize:
; P9:       # %bb.0:
; P9-NEXT:    xscvhpdp 0, 1
; P9-NEXT:    xsmaxdp 0, 0, 0
; P9-NEXT:    xscvdphp 1, 0
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_canonicalize:
; P8-LINUX-64:       # %bb.0:
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xsmaxdp 1, 1, 1
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
    %r = call half @llvm.canonicalize.f16(half %a)
    ret half %r
}

; ========================================================================================
; Transcendental Functions - Power
; ISD::FPOW , calls libm powf()
; ========================================================================================

define half @test_pow(half %a, half %b) nounwind {
; P8-AIX-32-LABEL: test_pow:
; P8-AIX-32:       # %bb.0:
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 2, 30
; P8-AIX-32-NEXT:    bl .powf[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_pow:
; P8-AIX-64:       # %bb.0:
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -128(1)
; P8-AIX-64-NEXT:    std 0, 144(1)
; P8-AIX-64-NEXT:    stfd 31, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 30, 112(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 2, 30
; P8-AIX-64-NEXT:    bl .powf[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    lfd 31, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 112(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    addi 1, 1, 128
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_pow:
; P9-AIX-32:       # %bb.0:
; P9-AIX-32-NEXT:    mflr 0
; P9-AIX-32-NEXT:    stwu 1, -64(1)
; P9-AIX-32-NEXT:    stw 0, 72(1)
; P9-AIX-32-NEXT:    xscvhpdp 1, 1
; P9-AIX-32-NEXT:    xscvhpdp 2, 2
; P9-AIX-32-NEXT:    bl .powf[PR]
; P9-AIX-32-NEXT:    nop
; P9-AIX-32-NEXT:    xscvdphp 1, 1
; P9-AIX-32-NEXT:    addi 1, 1, 64
; P9-AIX-32-NEXT:    lwz 0, 8(1)
; P9-AIX-32-NEXT:    mtlr 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: test_pow:
; P9-AIX-64:       # %bb.0:
; P9-AIX-64-NEXT:    mflr 0
; P9-AIX-64-NEXT:    stdu 1, -112(1)
; P9-AIX-64-NEXT:    std 0, 128(1)
; P9-AIX-64-NEXT:    xscvhpdp 1, 1
; P9-AIX-64-NEXT:    xscvhpdp 2, 2
; P9-AIX-64-NEXT:    bl .powf[PR]
; P9-AIX-64-NEXT:    nop
; P9-AIX-64-NEXT:    xscvdphp 1, 1
; P9-AIX-64-NEXT:    addi 1, 1, 112
; P9-AIX-64-NEXT:    ld 0, 16(1)
; P9-AIX-64-NEXT:    mtlr 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_pow:
; P8-LINUX-64:       # %bb.0:
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -48(1)
; P8-LINUX-64-NEXT:    fmr 31, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 64(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 2, 30
; P8-LINUX-64-NEXT:    bl powf
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 48
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: test_pow:
; P9-LINUX-64:       # %bb.0:
; P9-LINUX-64-NEXT:    mflr 0
; P9-LINUX-64-NEXT:    stdu 1, -32(1)
; P9-LINUX-64-NEXT:    std 0, 48(1)
; P9-LINUX-64-NEXT:    xscvhpdp 1, 1
; P9-LINUX-64-NEXT:    xscvhpdp 2, 2
; P9-LINUX-64-NEXT:    bl powf
; P9-LINUX-64-NEXT:    nop
; P9-LINUX-64-NEXT:    xscvdphp 1, 1
; P9-LINUX-64-NEXT:    addi 1, 1, 32
; P9-LINUX-64-NEXT:    ld 0, 16(1)
; P9-LINUX-64-NEXT:    mtlr 0
; P9-LINUX-64-NEXT:    blr
    %r = call half @llvm.pow.f16(half %a, half %b)
    ret half %r
}

; ========================================================================================
; Transcendental Functions - Logarithms
; ISD::FLOG, ISD::FLOG2, ISD::FLOG10 , calls libm
; ========================================================================================

define half @test_log(half %a) nounwind {
; P8-AIX-32-LABEL: test_log:
; P8-AIX-32:       # %bb.0:
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .logf[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_log:
; P8-AIX-64:       # %bb.0:
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .logf[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_log:
; P9-AIX-32:       # %bb.0:
; P9-AIX-32-NEXT:    mflr 0
; P9-AIX-32-NEXT:    stwu 1, -64(1)
; P9-AIX-32-NEXT:    stw 0, 72(1)
; P9-AIX-32-NEXT:    xscvhpdp 1, 1
; P9-AIX-32-NEXT:    bl .logf[PR]
; P9-AIX-32-NEXT:    nop
; P9-AIX-32-NEXT:    xscvdphp 1, 1
; P9-AIX-32-NEXT:    addi 1, 1, 64
; P9-AIX-32-NEXT:    lwz 0, 8(1)
; P9-AIX-32-NEXT:    mtlr 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: test_log:
; P9-AIX-64:       # %bb.0:
; P9-AIX-64-NEXT:    mflr 0
; P9-AIX-64-NEXT:    stdu 1, -112(1)
; P9-AIX-64-NEXT:    std 0, 128(1)
; P9-AIX-64-NEXT:    xscvhpdp 1, 1
; P9-AIX-64-NEXT:    bl .logf[PR]
; P9-AIX-64-NEXT:    nop
; P9-AIX-64-NEXT:    xscvdphp 1, 1
; P9-AIX-64-NEXT:    addi 1, 1, 112
; P9-AIX-64-NEXT:    ld 0, 16(1)
; P9-AIX-64-NEXT:    mtlr 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_log:
; P8-LINUX-64:       # %bb.0:
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl logf
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: test_log:
; P9-LINUX-64:       # %bb.0:
; P9-LINUX-64-NEXT:    mflr 0
; P9-LINUX-64-NEXT:    stdu 1, -32(1)
; P9-LINUX-64-NEXT:    std 0, 48(1)
; P9-LINUX-64-NEXT:    xscvhpdp 1, 1
; P9-LINUX-64-NEXT:    bl logf
; P9-LINUX-64-NEXT:    nop
; P9-LINUX-64-NEXT:    xscvdphp 1, 1
; P9-LINUX-64-NEXT:    addi 1, 1, 32
; P9-LINUX-64-NEXT:    ld 0, 16(1)
; P9-LINUX-64-NEXT:    mtlr 0
; P9-LINUX-64-NEXT:    blr
    %r = call half @llvm.log.f16(half %a)
    ret half %r
}

define half @test_log2(half %a) nounwind {
; P8-AIX-32-LABEL: test_log2:
; P8-AIX-32:       # %bb.0:
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .log2f[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_log2:
; P8-AIX-64:       # %bb.0:
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .log2f[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_log2:
; P9-AIX-32:       # %bb.0:
; P9-AIX-32-NEXT:    mflr 0
; P9-AIX-32-NEXT:    stwu 1, -64(1)
; P9-AIX-32-NEXT:    stw 0, 72(1)
; P9-AIX-32-NEXT:    xscvhpdp 1, 1
; P9-AIX-32-NEXT:    bl .log2f[PR]
; P9-AIX-32-NEXT:    nop
; P9-AIX-32-NEXT:    xscvdphp 1, 1
; P9-AIX-32-NEXT:    addi 1, 1, 64
; P9-AIX-32-NEXT:    lwz 0, 8(1)
; P9-AIX-32-NEXT:    mtlr 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: test_log2:
; P9-AIX-64:       # %bb.0:
; P9-AIX-64-NEXT:    mflr 0
; P9-AIX-64-NEXT:    stdu 1, -112(1)
; P9-AIX-64-NEXT:    std 0, 128(1)
; P9-AIX-64-NEXT:    xscvhpdp 1, 1
; P9-AIX-64-NEXT:    bl .log2f[PR]
; P9-AIX-64-NEXT:    nop
; P9-AIX-64-NEXT:    xscvdphp 1, 1
; P9-AIX-64-NEXT:    addi 1, 1, 112
; P9-AIX-64-NEXT:    ld 0, 16(1)
; P9-AIX-64-NEXT:    mtlr 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_log2:
; P8-LINUX-64:       # %bb.0:
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl log2f
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: test_log2:
; P9-LINUX-64:       # %bb.0:
; P9-LINUX-64-NEXT:    mflr 0
; P9-LINUX-64-NEXT:    stdu 1, -32(1)
; P9-LINUX-64-NEXT:    std 0, 48(1)
; P9-LINUX-64-NEXT:    xscvhpdp 1, 1
; P9-LINUX-64-NEXT:    bl log2f
; P9-LINUX-64-NEXT:    nop
; P9-LINUX-64-NEXT:    xscvdphp 1, 1
; P9-LINUX-64-NEXT:    addi 1, 1, 32
; P9-LINUX-64-NEXT:    ld 0, 16(1)
; P9-LINUX-64-NEXT:    mtlr 0
; P9-LINUX-64-NEXT:    blr
    %r = call half @llvm.log2.f16(half %a)
    ret half %r
}

define half @test_log10(half %a) nounwind {
; P8-AIX-32-LABEL: test_log10:
; P8-AIX-32:       # %bb.0:
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .log10f[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_log10:
; P8-AIX-64:       # %bb.0:
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .log10f[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_log10:
; P9-AIX-32:       # %bb.0:
; P9-AIX-32-NEXT:    mflr 0
; P9-AIX-32-NEXT:    stwu 1, -64(1)
; P9-AIX-32-NEXT:    stw 0, 72(1)
; P9-AIX-32-NEXT:    xscvhpdp 1, 1
; P9-AIX-32-NEXT:    bl .log10f[PR]
; P9-AIX-32-NEXT:    nop
; P9-AIX-32-NEXT:    xscvdphp 1, 1
; P9-AIX-32-NEXT:    addi 1, 1, 64
; P9-AIX-32-NEXT:    lwz 0, 8(1)
; P9-AIX-32-NEXT:    mtlr 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: test_log10:
; P9-AIX-64:       # %bb.0:
; P9-AIX-64-NEXT:    mflr 0
; P9-AIX-64-NEXT:    stdu 1, -112(1)
; P9-AIX-64-NEXT:    std 0, 128(1)
; P9-AIX-64-NEXT:    xscvhpdp 1, 1
; P9-AIX-64-NEXT:    bl .log10f[PR]
; P9-AIX-64-NEXT:    nop
; P9-AIX-64-NEXT:    xscvdphp 1, 1
; P9-AIX-64-NEXT:    addi 1, 1, 112
; P9-AIX-64-NEXT:    ld 0, 16(1)
; P9-AIX-64-NEXT:    mtlr 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_log10:
; P8-LINUX-64:       # %bb.0:
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl log10f
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: test_log10:
; P9-LINUX-64:       # %bb.0:
; P9-LINUX-64-NEXT:    mflr 0
; P9-LINUX-64-NEXT:    stdu 1, -32(1)
; P9-LINUX-64-NEXT:    std 0, 48(1)
; P9-LINUX-64-NEXT:    xscvhpdp 1, 1
; P9-LINUX-64-NEXT:    bl log10f
; P9-LINUX-64-NEXT:    nop
; P9-LINUX-64-NEXT:    xscvdphp 1, 1
; P9-LINUX-64-NEXT:    addi 1, 1, 32
; P9-LINUX-64-NEXT:    ld 0, 16(1)
; P9-LINUX-64-NEXT:    mtlr 0
; P9-LINUX-64-NEXT:    blr
    %r = call half @llvm.log10.f16(half %a)
    ret half %r
}

; ========================================================================================
; Transcendental Functions - Exponentials
; ISD::FEXP, ISD::FEXP2, ISD::FEXP10 , calls libm
; ========================================================================================

define half @test_exp(half %a) nounwind {
; P8-AIX-32-LABEL: test_exp:
; P8-AIX-32:       # %bb.0:
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .expf[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_exp:
; P8-AIX-64:       # %bb.0:
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .expf[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_exp:
; P9-AIX-32:       # %bb.0:
; P9-AIX-32-NEXT:    mflr 0
; P9-AIX-32-NEXT:    stwu 1, -64(1)
; P9-AIX-32-NEXT:    stw 0, 72(1)
; P9-AIX-32-NEXT:    xscvhpdp 1, 1
; P9-AIX-32-NEXT:    bl .expf[PR]
; P9-AIX-32-NEXT:    nop
; P9-AIX-32-NEXT:    xscvdphp 1, 1
; P9-AIX-32-NEXT:    addi 1, 1, 64
; P9-AIX-32-NEXT:    lwz 0, 8(1)
; P9-AIX-32-NEXT:    mtlr 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: test_exp:
; P9-AIX-64:       # %bb.0:
; P9-AIX-64-NEXT:    mflr 0
; P9-AIX-64-NEXT:    stdu 1, -112(1)
; P9-AIX-64-NEXT:    std 0, 128(1)
; P9-AIX-64-NEXT:    xscvhpdp 1, 1
; P9-AIX-64-NEXT:    bl .expf[PR]
; P9-AIX-64-NEXT:    nop
; P9-AIX-64-NEXT:    xscvdphp 1, 1
; P9-AIX-64-NEXT:    addi 1, 1, 112
; P9-AIX-64-NEXT:    ld 0, 16(1)
; P9-AIX-64-NEXT:    mtlr 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_exp:
; P8-LINUX-64:       # %bb.0:
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl expf
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: test_exp:
; P9-LINUX-64:       # %bb.0:
; P9-LINUX-64-NEXT:    mflr 0
; P9-LINUX-64-NEXT:    stdu 1, -32(1)
; P9-LINUX-64-NEXT:    std 0, 48(1)
; P9-LINUX-64-NEXT:    xscvhpdp 1, 1
; P9-LINUX-64-NEXT:    bl expf
; P9-LINUX-64-NEXT:    nop
; P9-LINUX-64-NEXT:    xscvdphp 1, 1
; P9-LINUX-64-NEXT:    addi 1, 1, 32
; P9-LINUX-64-NEXT:    ld 0, 16(1)
; P9-LINUX-64-NEXT:    mtlr 0
; P9-LINUX-64-NEXT:    blr
    %r = call half @llvm.exp.f16(half %a)
    ret half %r
}

define half @test_exp2(half %a) nounwind {
; P8-AIX-32-LABEL: test_exp2:
; P8-AIX-32:       # %bb.0:
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .exp2f[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_exp2:
; P8-AIX-64:       # %bb.0:
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .exp2f[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_exp2:
; P9-AIX-32:       # %bb.0:
; P9-AIX-32-NEXT:    mflr 0
; P9-AIX-32-NEXT:    stwu 1, -64(1)
; P9-AIX-32-NEXT:    stw 0, 72(1)
; P9-AIX-32-NEXT:    xscvhpdp 1, 1
; P9-AIX-32-NEXT:    bl .exp2f[PR]
; P9-AIX-32-NEXT:    nop
; P9-AIX-32-NEXT:    xscvdphp 1, 1
; P9-AIX-32-NEXT:    addi 1, 1, 64
; P9-AIX-32-NEXT:    lwz 0, 8(1)
; P9-AIX-32-NEXT:    mtlr 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: test_exp2:
; P9-AIX-64:       # %bb.0:
; P9-AIX-64-NEXT:    mflr 0
; P9-AIX-64-NEXT:    stdu 1, -112(1)
; P9-AIX-64-NEXT:    std 0, 128(1)
; P9-AIX-64-NEXT:    xscvhpdp 1, 1
; P9-AIX-64-NEXT:    bl .exp2f[PR]
; P9-AIX-64-NEXT:    nop
; P9-AIX-64-NEXT:    xscvdphp 1, 1
; P9-AIX-64-NEXT:    addi 1, 1, 112
; P9-AIX-64-NEXT:    ld 0, 16(1)
; P9-AIX-64-NEXT:    mtlr 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_exp2:
; P8-LINUX-64:       # %bb.0:
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl exp2f
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: test_exp2:
; P9-LINUX-64:       # %bb.0:
; P9-LINUX-64-NEXT:    mflr 0
; P9-LINUX-64-NEXT:    stdu 1, -32(1)
; P9-LINUX-64-NEXT:    std 0, 48(1)
; P9-LINUX-64-NEXT:    xscvhpdp 1, 1
; P9-LINUX-64-NEXT:    bl exp2f
; P9-LINUX-64-NEXT:    nop
; P9-LINUX-64-NEXT:    xscvdphp 1, 1
; P9-LINUX-64-NEXT:    addi 1, 1, 32
; P9-LINUX-64-NEXT:    ld 0, 16(1)
; P9-LINUX-64-NEXT:    mtlr 0
; P9-LINUX-64-NEXT:    blr
    %r = call half @llvm.exp2.f16(half %a)
    ret half %r
}

define half @test_exp10(half %a) nounwind {
; P8-AIX-32-LABEL: test_exp10:
; P8-AIX-32:       # %bb.0:
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .exp10f[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_exp10:
; P8-AIX-64:       # %bb.0:
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .exp10f[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_exp10:
; P9-AIX-32:       # %bb.0:
; P9-AIX-32-NEXT:    mflr 0
; P9-AIX-32-NEXT:    stwu 1, -64(1)
; P9-AIX-32-NEXT:    stw 0, 72(1)
; P9-AIX-32-NEXT:    xscvhpdp 1, 1
; P9-AIX-32-NEXT:    bl .exp10f[PR]
; P9-AIX-32-NEXT:    nop
; P9-AIX-32-NEXT:    xscvdphp 1, 1
; P9-AIX-32-NEXT:    addi 1, 1, 64
; P9-AIX-32-NEXT:    lwz 0, 8(1)
; P9-AIX-32-NEXT:    mtlr 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: test_exp10:
; P9-AIX-64:       # %bb.0:
; P9-AIX-64-NEXT:    mflr 0
; P9-AIX-64-NEXT:    stdu 1, -112(1)
; P9-AIX-64-NEXT:    std 0, 128(1)
; P9-AIX-64-NEXT:    xscvhpdp 1, 1
; P9-AIX-64-NEXT:    bl .exp10f[PR]
; P9-AIX-64-NEXT:    nop
; P9-AIX-64-NEXT:    xscvdphp 1, 1
; P9-AIX-64-NEXT:    addi 1, 1, 112
; P9-AIX-64-NEXT:    ld 0, 16(1)
; P9-AIX-64-NEXT:    mtlr 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_exp10:
; P8-LINUX-64:       # %bb.0:
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl exp10f
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: test_exp10:
; P9-LINUX-64:       # %bb.0:
; P9-LINUX-64-NEXT:    mflr 0
; P9-LINUX-64-NEXT:    stdu 1, -32(1)
; P9-LINUX-64-NEXT:    std 0, 48(1)
; P9-LINUX-64-NEXT:    xscvhpdp 1, 1
; P9-LINUX-64-NEXT:    bl exp10f
; P9-LINUX-64-NEXT:    nop
; P9-LINUX-64-NEXT:    xscvdphp 1, 1
; P9-LINUX-64-NEXT:    addi 1, 1, 32
; P9-LINUX-64-NEXT:    ld 0, 16(1)
; P9-LINUX-64-NEXT:    mtlr 0
; P9-LINUX-64-NEXT:    blr
    %r = call half @llvm.exp10.f16(half %a)
    ret half %r
}

; ========================================================================================
; Transcendental Functions - Trigonometric
; ISD::FSIN, ISD::FCOS , calls libm
; ========================================================================================

define half @test_sin(half %a) nounwind {
; P8-AIX-32-LABEL: test_sin:
; P8-AIX-32:       # %bb.0:
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .sinf[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_sin:
; P8-AIX-64:       # %bb.0:
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .sinf[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_sin:
; P9-AIX-32:       # %bb.0:
; P9-AIX-32-NEXT:    mflr 0
; P9-AIX-32-NEXT:    stwu 1, -64(1)
; P9-AIX-32-NEXT:    stw 0, 72(1)
; P9-AIX-32-NEXT:    xscvhpdp 1, 1
; P9-AIX-32-NEXT:    bl .sinf[PR]
; P9-AIX-32-NEXT:    nop
; P9-AIX-32-NEXT:    xscvdphp 1, 1
; P9-AIX-32-NEXT:    addi 1, 1, 64
; P9-AIX-32-NEXT:    lwz 0, 8(1)
; P9-AIX-32-NEXT:    mtlr 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: test_sin:
; P9-AIX-64:       # %bb.0:
; P9-AIX-64-NEXT:    mflr 0
; P9-AIX-64-NEXT:    stdu 1, -112(1)
; P9-AIX-64-NEXT:    std 0, 128(1)
; P9-AIX-64-NEXT:    xscvhpdp 1, 1
; P9-AIX-64-NEXT:    bl .sinf[PR]
; P9-AIX-64-NEXT:    nop
; P9-AIX-64-NEXT:    xscvdphp 1, 1
; P9-AIX-64-NEXT:    addi 1, 1, 112
; P9-AIX-64-NEXT:    ld 0, 16(1)
; P9-AIX-64-NEXT:    mtlr 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_sin:
; P8-LINUX-64:       # %bb.0:
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl sinf
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: test_sin:
; P9-LINUX-64:       # %bb.0:
; P9-LINUX-64-NEXT:    mflr 0
; P9-LINUX-64-NEXT:    stdu 1, -32(1)
; P9-LINUX-64-NEXT:    std 0, 48(1)
; P9-LINUX-64-NEXT:    xscvhpdp 1, 1
; P9-LINUX-64-NEXT:    bl sinf
; P9-LINUX-64-NEXT:    nop
; P9-LINUX-64-NEXT:    xscvdphp 1, 1
; P9-LINUX-64-NEXT:    addi 1, 1, 32
; P9-LINUX-64-NEXT:    ld 0, 16(1)
; P9-LINUX-64-NEXT:    mtlr 0
; P9-LINUX-64-NEXT:    blr
    %r = call half @llvm.sin.f16(half %a)
    ret half %r
}

define half @test_cos(half %a) nounwind {
; P8-AIX-32-LABEL: test_cos:
; P8-AIX-32:       # %bb.0:
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .cosf[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_cos:
; P8-AIX-64:       # %bb.0:
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .cosf[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_cos:
; P9-AIX-32:       # %bb.0:
; P9-AIX-32-NEXT:    mflr 0
; P9-AIX-32-NEXT:    stwu 1, -64(1)
; P9-AIX-32-NEXT:    stw 0, 72(1)
; P9-AIX-32-NEXT:    xscvhpdp 1, 1
; P9-AIX-32-NEXT:    bl .cosf[PR]
; P9-AIX-32-NEXT:    nop
; P9-AIX-32-NEXT:    xscvdphp 1, 1
; P9-AIX-32-NEXT:    addi 1, 1, 64
; P9-AIX-32-NEXT:    lwz 0, 8(1)
; P9-AIX-32-NEXT:    mtlr 0
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: test_cos:
; P9-AIX-64:       # %bb.0:
; P9-AIX-64-NEXT:    mflr 0
; P9-AIX-64-NEXT:    stdu 1, -112(1)
; P9-AIX-64-NEXT:    std 0, 128(1)
; P9-AIX-64-NEXT:    xscvhpdp 1, 1
; P9-AIX-64-NEXT:    bl .cosf[PR]
; P9-AIX-64-NEXT:    nop
; P9-AIX-64-NEXT:    xscvdphp 1, 1
; P9-AIX-64-NEXT:    addi 1, 1, 112
; P9-AIX-64-NEXT:    ld 0, 16(1)
; P9-AIX-64-NEXT:    mtlr 0
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_cos:
; P8-LINUX-64:       # %bb.0:
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl cosf
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: test_cos:
; P9-LINUX-64:       # %bb.0:
; P9-LINUX-64-NEXT:    mflr 0
; P9-LINUX-64-NEXT:    stdu 1, -32(1)
; P9-LINUX-64-NEXT:    std 0, 48(1)
; P9-LINUX-64-NEXT:    xscvhpdp 1, 1
; P9-LINUX-64-NEXT:    bl cosf
; P9-LINUX-64-NEXT:    nop
; P9-LINUX-64-NEXT:    xscvdphp 1, 1
; P9-LINUX-64-NEXT:    addi 1, 1, 32
; P9-LINUX-64-NEXT:    ld 0, 16(1)
; P9-LINUX-64-NEXT:    mtlr 0
; P9-LINUX-64-NEXT:    blr
    %r = call half @llvm.cos.f16(half %a)
    ret half %r
}

; ========================================================================================
; Type Conversion Operations
; ISD::FP_EXTEND (f16->f32/f64), ISD::FP_ROUND (f32/f64->f16)
; P9+: Hardware (xscvhpdp/xscvdphp), P8: Library calls
; ========================================================================================

define float @op_f16_to_f32(half %h) nounwind {
; P8-AIX-32-LABEL: op_f16_to_f32:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_f16_to_f32:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_f16_to_f32:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_f16_to_f32:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %conv = fpext half %h to float
  ret float %conv
}

define double @op_f16_to_f64(half %h) nounwind {
; P8-AIX-32-LABEL: op_f16_to_f64:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__extendhfdf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_f16_to_f64:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__extendhfdf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_f16_to_f64:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_f16_to_f64:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __extendhfdf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %conv = fpext half %h to double
  ret double %conv
}

define half @op_f32_to_f16(float %f) nounwind {
; P8-AIX-32-LABEL: op_f32_to_f16:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_f32_to_f16:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_f32_to_f16:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvdphp 1, 1
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_f32_to_f16:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %conv = fptrunc float %f to half
  ret half %conv
}

define half @op_f64_to_f16(double %d) nounwind {
; P8-AIX-32-LABEL: op_f64_to_f16:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -64(1)
; P8-AIX-32-NEXT:    stw 0, 72(1)
; P8-AIX-32-NEXT:    bl .__truncdfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    addi 1, 1, 64
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: op_f64_to_f16:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -112(1)
; P8-AIX-64-NEXT:    std 0, 128(1)
; P8-AIX-64-NEXT:    bl .__truncdfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    addi 1, 1, 112
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: op_f64_to_f16:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvdphp 1, 1
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: op_f64_to_f16:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stdu 1, -32(1)
; P8-LINUX-64-NEXT:    std 0, 48(1)
; P8-LINUX-64-NEXT:    bl __truncdfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 32
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    blr
entry:
  %conv = fptrunc double %d to half
  ret half %conv
}

; ========================================================================================
; Bitcast Operations
; Bitcast between f16 and i16 (no conversion, reinterpret bits)
; Test that bitcast between i16 and half is lossless when -mfloat16 is active.
; This verifies the fix for the miscompilation described in llvm/llvm-project#97981,
; where passing/returning half used lossy float conversion functions (__gnu_h2f_ieee,
; __gnu_f2h_ieee) that silenced signalling NaNs and corrupted NaN payloads.
; ========================================================================================

define half @to_half(i16 %bits) nounwind {
; P8-AIX-32-LABEL: to_half:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    sth 3, -2(1)
; P8-AIX-32-NEXT:    lhz 3, -2(1)
; P8-AIX-32-NEXT:    mtfprwz 1, 3
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: to_half:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    sth 3, -2(1)
; P8-AIX-64-NEXT:    lhz 3, -2(1)
; P8-AIX-64-NEXT:    mtfprwz 1, 3
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: to_half:
; P9:       # %bb.0: # %entry
; P9-NEXT:    sth 3, -2(1)
; P9-NEXT:    addi 3, 1, -2
; P9-NEXT:    lxsihzx 1, 0, 3
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: to_half:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    sth 3, -2(1)
; P8-LINUX-64-NEXT:    lhz 3, -2(1)
; P8-LINUX-64-NEXT:    mtfprwz 1, 3
; P8-LINUX-64-NEXT:    blr
entry:
    %f = bitcast i16 %bits to half
    ret half %f
}

define i16 @from_half(half %f) nounwind {
; P8-AIX-32-LABEL: from_half:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mffprwz 3, 1
; P8-AIX-32-NEXT:    sth 3, -2(1)
; P8-AIX-32-NEXT:    lhz 3, -2(1)
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: from_half:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mffprwz 3, 1
; P8-AIX-64-NEXT:    sth 3, -2(1)
; P8-AIX-64-NEXT:    lhz 3, -2(1)
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: from_half:
; P9:       # %bb.0: # %entry
; P9-NEXT:    addi 3, 1, -2
; P9-NEXT:    stxsihx 1, 0, 3
; P9-NEXT:    lhz 3, -2(1)
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: from_half:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mffprwz 3, 1
; P8-LINUX-64-NEXT:    sth 3, -2(1)
; P8-LINUX-64-NEXT:    lhz 3, -2(1)
; P8-LINUX-64-NEXT:    blr
entry:
    %bits = bitcast half %f to i16
    ret i16 %bits
}

; ========================================================================================
; Edge Cases and Correctness Tests
; llvm/llvm-project#97975
; ========================================================================================
; Test that consecutive half operations round intermediate results back to f16
; precision between each operation when -mfloat16 is active.
; This verifies the fix for the miscompilation described in llvm/llvm-project#97975,
; where backends kept intermediate results at f32 precision across consecutive
; half operations, causing incorrect results. For example:
;   65504.0 + 65504.0 + (-65504.0) should produce infinity at f16 precision
;   but produces 65504.0 if the intermediate is kept at f32 precision.
; ========================================================================================

define half @consecutive_add(half %a, half %b, half %c) nounwind {
; P8-AIX-32-LABEL: consecutive_add:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    mflr 0
; P8-AIX-32-NEXT:    stwu 1, -80(1)
; P8-AIX-32-NEXT:    stw 0, 88(1)
; P8-AIX-32-NEXT:    stfd 30, 64(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 2
; P8-AIX-32-NEXT:    stfd 29, 56(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    stfd 31, 72(1) # 8-byte Folded Spill
; P8-AIX-32-NEXT:    fmr 31, 3
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 29, 1
; P8-AIX-32-NEXT:    fmr 1, 30
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xsaddsp 1, 1, 29
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    fmr 30, 1
; P8-AIX-32-NEXT:    fmr 1, 31
; P8-AIX-32-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    xsaddsp 1, 30, 1
; P8-AIX-32-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-32-NEXT:    nop
; P8-AIX-32-NEXT:    lfd 31, 72(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 30, 64(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    lfd 29, 56(1) # 8-byte Folded Reload
; P8-AIX-32-NEXT:    addi 1, 1, 80
; P8-AIX-32-NEXT:    lwz 0, 8(1)
; P8-AIX-32-NEXT:    mtlr 0
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: consecutive_add:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    mflr 0
; P8-AIX-64-NEXT:    stdu 1, -144(1)
; P8-AIX-64-NEXT:    std 0, 160(1)
; P8-AIX-64-NEXT:    stfd 30, 128(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 2
; P8-AIX-64-NEXT:    stfd 29, 120(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    stfd 31, 136(1) # 8-byte Folded Spill
; P8-AIX-64-NEXT:    fmr 31, 3
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 29, 1
; P8-AIX-64-NEXT:    fmr 1, 30
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xsaddsp 1, 1, 29
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    fmr 30, 1
; P8-AIX-64-NEXT:    fmr 1, 31
; P8-AIX-64-NEXT:    bl .__extendhfsf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    xsaddsp 1, 30, 1
; P8-AIX-64-NEXT:    bl .__truncsfhf2[PR]
; P8-AIX-64-NEXT:    nop
; P8-AIX-64-NEXT:    lfd 31, 136(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 30, 128(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    lfd 29, 120(1) # 8-byte Folded Reload
; P8-AIX-64-NEXT:    addi 1, 1, 144
; P8-AIX-64-NEXT:    ld 0, 16(1)
; P8-AIX-64-NEXT:    mtlr 0
; P8-AIX-64-NEXT:    blr
;
; P9-LABEL: consecutive_add:
; P9:       # %bb.0: # %entry
; P9-NEXT:    xscvhpdp 0, 2
; P9-NEXT:    xscvhpdp 1, 1
; P9-NEXT:    xsaddsp 0, 1, 0
; P9-NEXT:    xscvdphp 0, 0
; P9-NEXT:    xscvhpdp 0, 0
; P9-NEXT:    xscvhpdp 1, 3
; P9-NEXT:    xsaddsp 0, 0, 1
; P9-NEXT:    xscvdphp 1, 0
; P9-NEXT:    blr
;
; P8-LINUX-64-LABEL: consecutive_add:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    mflr 0
; P8-LINUX-64-NEXT:    stfd 29, -24(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 30, -16(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stfd 31, -8(1) # 8-byte Folded Spill
; P8-LINUX-64-NEXT:    stdu 1, -64(1)
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 2
; P8-LINUX-64-NEXT:    std 0, 80(1)
; P8-LINUX-64-NEXT:    fmr 31, 3
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 29, 1
; P8-LINUX-64-NEXT:    fmr 1, 30
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xsaddsp 1, 1, 29
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    fmr 30, 1
; P8-LINUX-64-NEXT:    fmr 1, 31
; P8-LINUX-64-NEXT:    bl __extendhfsf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    xsaddsp 1, 30, 1
; P8-LINUX-64-NEXT:    bl __truncsfhf2
; P8-LINUX-64-NEXT:    nop
; P8-LINUX-64-NEXT:    addi 1, 1, 64
; P8-LINUX-64-NEXT:    ld 0, 16(1)
; P8-LINUX-64-NEXT:    lfd 31, -8(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    lfd 30, -16(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    mtlr 0
; P8-LINUX-64-NEXT:    lfd 29, -24(1) # 8-byte Folded Reload
; P8-LINUX-64-NEXT:    blr
entry:
    %d = fadd half %a, %b
    %e = fadd half %d, %c
    ret half %e
}

; ========================================================================================
; ConstantFP - Expand path, materialized as integer
; ========================================================================================

; 0xH3C00 = 1.0 in IEEE 754 f16 encoding
define half @test_constant_fp() nounwind {
; P8-AIX-32-LABEL: test_constant_fp:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    lwz 3, L..C2(2) # %const.0
; P8-AIX-32-NEXT:    lhzx 3, 0, 3
; P8-AIX-32-NEXT:    mtfprwz 1, 3
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_constant_fp:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    ld 3, L..C2(2) # %const.0
; P8-AIX-64-NEXT:    lhzx 3, 0, 3
; P8-AIX-64-NEXT:    mtfprwz 1, 3
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_constant_fp:
; P9-AIX-32:       # %bb.0: # %entry
; P9-AIX-32-NEXT:    lwz 3, L..C2(2) # %const.0
; P9-AIX-32-NEXT:    lxsihzx 1, 0, 3
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: test_constant_fp:
; P9-AIX-64:       # %bb.0: # %entry
; P9-AIX-64-NEXT:    ld 3, L..C2(2) # %const.0
; P9-AIX-64-NEXT:    lxsihzx 1, 0, 3
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_constant_fp:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    addis 3, 2, .LCPI48_0@toc@ha
; P8-LINUX-64-NEXT:    lhz 3, .LCPI48_0@toc@l(3)
; P8-LINUX-64-NEXT:    mtfprwz 1, 3
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: test_constant_fp:
; P9-LINUX-64:       # %bb.0: # %entry
; P9-LINUX-64-NEXT:    addis 3, 2, .LCPI48_0@toc@ha
; P9-LINUX-64-NEXT:    addi 3, 3, .LCPI48_0@toc@l
; P9-LINUX-64-NEXT:    lxsihzx 1, 0, 3
; P9-LINUX-64-NEXT:    blr
entry:
  ret half 0xH3C00
}

define half @test_constant_zero() nounwind {
; P8-AIX-32-LABEL: test_constant_zero:
; P8-AIX-32:       # %bb.0: # %entry
; P8-AIX-32-NEXT:    lwz 3, L..C3(2) # %const.0
; P8-AIX-32-NEXT:    lhzx 3, 0, 3
; P8-AIX-32-NEXT:    mtfprwz 1, 3
; P8-AIX-32-NEXT:    blr
;
; P8-AIX-64-LABEL: test_constant_zero:
; P8-AIX-64:       # %bb.0: # %entry
; P8-AIX-64-NEXT:    ld 3, L..C3(2) # %const.0
; P8-AIX-64-NEXT:    lhzx 3, 0, 3
; P8-AIX-64-NEXT:    mtfprwz 1, 3
; P8-AIX-64-NEXT:    blr
;
; P9-AIX-32-LABEL: test_constant_zero:
; P9-AIX-32:       # %bb.0: # %entry
; P9-AIX-32-NEXT:    lwz 3, L..C3(2) # %const.0
; P9-AIX-32-NEXT:    lxsihzx 1, 0, 3
; P9-AIX-32-NEXT:    blr
;
; P9-AIX-64-LABEL: test_constant_zero:
; P9-AIX-64:       # %bb.0: # %entry
; P9-AIX-64-NEXT:    ld 3, L..C3(2) # %const.0
; P9-AIX-64-NEXT:    lxsihzx 1, 0, 3
; P9-AIX-64-NEXT:    blr
;
; P8-LINUX-64-LABEL: test_constant_zero:
; P8-LINUX-64:       # %bb.0: # %entry
; P8-LINUX-64-NEXT:    addis 3, 2, .LCPI49_0@toc@ha
; P8-LINUX-64-NEXT:    lhz 3, .LCPI49_0@toc@l(3)
; P8-LINUX-64-NEXT:    mtfprwz 1, 3
; P8-LINUX-64-NEXT:    blr
;
; P9-LINUX-64-LABEL: test_constant_zero:
; P9-LINUX-64:       # %bb.0: # %entry
; P9-LINUX-64-NEXT:    addis 3, 2, .LCPI49_0@toc@ha
; P9-LINUX-64-NEXT:    addi 3, 3, .LCPI49_0@toc@l
; P9-LINUX-64-NEXT:    lxsihzx 1, 0, 3
; P9-LINUX-64-NEXT:    blr
entry:
  ret half 0.0
}

; ========================================================================================
; Intrinsic Declarations
; ========================================================================================

declare half @llvm.canonicalize.f16(half)
declare half @llvm.ceil.f16(half)
declare half @llvm.copysign.f16(half, half)
declare half @llvm.cos.f16(half)
declare half @llvm.exp.f16(half)
declare half @llvm.exp10.f16(half)
declare half @llvm.exp2.f16(half)
declare half @llvm.fabs.f16(half)
declare half @llvm.floor.f16(half)
declare half @llvm.fma.f16(half, half, half)
declare half @llvm.log.f16(half)
declare half @llvm.log10.f16(half)
declare half @llvm.log2.f16(half)
declare half @llvm.maximum.f16(half, half)
declare half @llvm.maxnum.f16(half, half)
declare half @llvm.minimum.f16(half, half)
declare half @llvm.minnum.f16(half, half)
declare half @llvm.nearbyint.f16(half)
declare half @llvm.pow.f16(half, half)
declare half @llvm.rint.f16(half)
declare half @llvm.round.f16(half)
declare half @llvm.roundeven.f16(half)
declare half @llvm.sin.f16(half)
declare half @llvm.sqrt.f16(half)
declare half @llvm.trunc.f16(half)
