; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=powerpc64-linux-gnu | FileCheck %s

define void @sdivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; CHECK-LABEL: sdivrem_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mflr 0
; CHECK-NEXT:    stdu 1, -192(1)
; CHECK-NEXT:    std 0, 208(1)
; CHECK-NEXT:    .cfi_def_cfa_offset 192
; CHECK-NEXT:    .cfi_offset lr, 16
; CHECK-NEXT:    .cfi_offset r23, -72
; CHECK-NEXT:    .cfi_offset r24, -64
; CHECK-NEXT:    .cfi_offset r25, -56
; CHECK-NEXT:    .cfi_offset r26, -48
; CHECK-NEXT:    .cfi_offset r27, -40
; CHECK-NEXT:    .cfi_offset r28, -32
; CHECK-NEXT:    .cfi_offset r29, -24
; CHECK-NEXT:    .cfi_offset r30, -16
; CHECK-NEXT:    std 25, 136(1) # 8-byte Folded Spill
; CHECK-NEXT:    mr 25, 3
; CHECK-NEXT:    mr 3, 5
; CHECK-NEXT:    std 26, 144(1) # 8-byte Folded Spill
; CHECK-NEXT:    mr 26, 4
; CHECK-NEXT:    mr 4, 6
; CHECK-NEXT:    std 27, 152(1) # 8-byte Folded Spill
; CHECK-NEXT:    mr 27, 5
; CHECK-NEXT:    mr 5, 7
; CHECK-NEXT:    std 28, 160(1) # 8-byte Folded Spill
; CHECK-NEXT:    mr 28, 6
; CHECK-NEXT:    mr 6, 8
; CHECK-NEXT:    std 23, 120(1) # 8-byte Folded Spill
; CHECK-NEXT:    std 24, 128(1) # 8-byte Folded Spill
; CHECK-NEXT:    std 29, 168(1) # 8-byte Folded Spill
; CHECK-NEXT:    mr 29, 7
; CHECK-NEXT:    std 30, 176(1) # 8-byte Folded Spill
; CHECK-NEXT:    mr 30, 8
; CHECK-NEXT:    bl __divti3
; CHECK-NEXT:    nop
; CHECK-NEXT:    mr 24, 3
; CHECK-NEXT:    mr 23, 4
; CHECK-NEXT:    mr 3, 27
; CHECK-NEXT:    mr 4, 28
; CHECK-NEXT:    mr 5, 29
; CHECK-NEXT:    mr 6, 30
; CHECK-NEXT:    bl __modti3
; CHECK-NEXT:    nop
; CHECK-NEXT:    std 24, 0(25)
; CHECK-NEXT:    std 23, 8(25)
; CHECK-NEXT:    std 3, 0(26)
; CHECK-NEXT:    std 4, 8(26)
; CHECK-NEXT:    ld 30, 176(1) # 8-byte Folded Reload
; CHECK-NEXT:    ld 29, 168(1) # 8-byte Folded Reload
; CHECK-NEXT:    ld 28, 160(1) # 8-byte Folded Reload
; CHECK-NEXT:    ld 27, 152(1) # 8-byte Folded Reload
; CHECK-NEXT:    ld 26, 144(1) # 8-byte Folded Reload
; CHECK-NEXT:    ld 25, 136(1) # 8-byte Folded Reload
; CHECK-NEXT:    ld 24, 128(1) # 8-byte Folded Reload
; CHECK-NEXT:    ld 23, 120(1) # 8-byte Folded Reload
; CHECK-NEXT:    addi 1, 1, 192
; CHECK-NEXT:    ld 0, 16(1)
; CHECK-NEXT:    mtlr 0
; CHECK-NEXT:    blr
  %q = sdiv i128 %n, %d
  %r = srem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}

define void @udivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; CHECK-LABEL: udivrem_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mflr 0
; CHECK-NEXT:    stdu 1, -192(1)
; CHECK-NEXT:    std 0, 208(1)
; CHECK-NEXT:    .cfi_def_cfa_offset 192
; CHECK-NEXT:    .cfi_offset lr, 16
; CHECK-NEXT:    .cfi_offset r23, -72
; CHECK-NEXT:    .cfi_offset r24, -64
; CHECK-NEXT:    .cfi_offset r25, -56
; CHECK-NEXT:    .cfi_offset r26, -48
; CHECK-NEXT:    .cfi_offset r27, -40
; CHECK-NEXT:    .cfi_offset r28, -32
; CHECK-NEXT:    .cfi_offset r29, -24
; CHECK-NEXT:    .cfi_offset r30, -16
; CHECK-NEXT:    std 25, 136(1) # 8-byte Folded Spill
; CHECK-NEXT:    mr 25, 3
; CHECK-NEXT:    mr 3, 5
; CHECK-NEXT:    std 26, 144(1) # 8-byte Folded Spill
; CHECK-NEXT:    mr 26, 4
; CHECK-NEXT:    mr 4, 6
; CHECK-NEXT:    std 27, 152(1) # 8-byte Folded Spill
; CHECK-NEXT:    mr 27, 5
; CHECK-NEXT:    mr 5, 7
; CHECK-NEXT:    std 28, 160(1) # 8-byte Folded Spill
; CHECK-NEXT:    mr 28, 6
; CHECK-NEXT:    mr 6, 8
; CHECK-NEXT:    std 23, 120(1) # 8-byte Folded Spill
; CHECK-NEXT:    std 24, 128(1) # 8-byte Folded Spill
; CHECK-NEXT:    std 29, 168(1) # 8-byte Folded Spill
; CHECK-NEXT:    mr 29, 7
; CHECK-NEXT:    std 30, 176(1) # 8-byte Folded Spill
; CHECK-NEXT:    mr 30, 8
; CHECK-NEXT:    bl __udivti3
; CHECK-NEXT:    nop
; CHECK-NEXT:    mr 24, 3
; CHECK-NEXT:    mr 23, 4
; CHECK-NEXT:    mr 3, 27
; CHECK-NEXT:    mr 4, 28
; CHECK-NEXT:    mr 5, 29
; CHECK-NEXT:    mr 6, 30
; CHECK-NEXT:    bl __umodti3
; CHECK-NEXT:    nop
; CHECK-NEXT:    std 24, 0(25)
; CHECK-NEXT:    std 23, 8(25)
; CHECK-NEXT:    std 3, 0(26)
; CHECK-NEXT:    std 4, 8(26)
; CHECK-NEXT:    ld 30, 176(1) # 8-byte Folded Reload
; CHECK-NEXT:    ld 29, 168(1) # 8-byte Folded Reload
; CHECK-NEXT:    ld 28, 160(1) # 8-byte Folded Reload
; CHECK-NEXT:    ld 27, 152(1) # 8-byte Folded Reload
; CHECK-NEXT:    ld 26, 144(1) # 8-byte Folded Reload
; CHECK-NEXT:    ld 25, 136(1) # 8-byte Folded Reload
; CHECK-NEXT:    ld 24, 128(1) # 8-byte Folded Reload
; CHECK-NEXT:    ld 23, 120(1) # 8-byte Folded Reload
; CHECK-NEXT:    addi 1, 1, 192
; CHECK-NEXT:    ld 0, 16(1)
; CHECK-NEXT:    mtlr 0
; CHECK-NEXT:    blr
  %q = udiv i128 %n, %d
  %r = urem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}
