; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -verify-machineinstrs < %s -mcpu=pwr8 \
; RUN:  -mtriple=powerpc64-ibm-aix-xcoff | FileCheck %s

define zeroext i32 @atomic_load(ptr %ptr, i32 zeroext range(i32 0, 256) %val) {
; CHECK-LABEL: atomic_load:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    mr 6, 4
; CHECK-NEXT:    lwat 5, 3, 0
; CHECK-NEXT:    mr 3, 5
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    clrldi 3, 3, 32
; CHECK-NEXT:    blr
entry:
  %0 = load i32, ptr %ptr, align 4
  %1 = tail call { i128, i32 } asm sideeffect "mr ${1:L},$3\0A\09 lwat $1,${0:P},$4\0A\09 mr $2,$1\0A", "=*Q,=&r,=r,r,n,0"(ptr nonnull elementtype(i32) %ptr, i32 %val, i32 0, i32 %0)
  %asmresult1 = extractvalue { i128, i32 } %1, 1
  ret i32 %asmresult1
}
