; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
; RUN: llc -verify-machineinstrs -mtriple=powerpc64-- -stop-after=finalize-isel < %s | FileCheck %s
; RUN: llc -verify-machineinstrs -mtriple=powerpc-- -stop-after=finalize-isel < %s | FileCheck --check-prefix=CHECK-32 %s
; FIXME: `implicit-def early-clobber $carry` should be generated for `call void asm sideeffect "", "~{ca}"()`.
define void @f() {
  ; CHECK-LABEL: name: f
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   INLINEASM &"", 1 /* sideeffect attdialect */, 12 /* clobber */, implicit-def early-clobber $xer
  ; CHECK-NEXT:   INLINEASM &"", 1 /* sideeffect attdialect */
  ; CHECK-NEXT:   BLR8 implicit $lr8, implicit $rm
  ;
  ; CHECK-32-LABEL: name: f
  ; CHECK-32: bb.0.entry:
  ; CHECK-32-NEXT:   INLINEASM &"", 1 /* sideeffect attdialect */, 12 /* clobber */, implicit-def early-clobber $xer
  ; CHECK-32-NEXT:   INLINEASM &"", 1 /* sideeffect attdialect */
  ; CHECK-32-NEXT:   BLR implicit $lr, implicit $rm
entry:
  call void asm sideeffect "", "~{xer}"()
  call void asm sideeffect "", "~{ca}"()
  ret void
}
