# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O3 -verify-machineinstrs -mtriple=powerpc64-unknown-unknown \
# RUN:   -simplify-mir -run-pass=machine-cp %s -o - | FileCheck %s

--- |
  declare void @foo()
  define void @test0() {
  entry:
    ret void
  }

  define void @test1() {
  entry:
    ret void
  }

  define void @test2() {
  entry:
    ret void
  }

  define void @test3() {
  entry:
    ret void
  }

  define void @test4() {
  entry:
    ret void
  }

  define void @test5() {
  entry:
    ret void
  }

  define void @test6() {
  entry:
    ret void
  }

...
---
name: test0
alignment: 4
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x4, $x5, $x20, $x21, $x22
    ; CHECK-LABEL: name: test0
    ; CHECK: liveins: $x4, $x5, $x20, $x21, $x22
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $x24 = COPY $x4
    ; CHECK-NEXT: $x23 = COPY renamable $x20
    ; CHECK-NEXT: renamable $x20 = ADD8 $x4, $x5
    ; CHECK-NEXT: renamable $x4 = COPY renamable $x20
    ; CHECK-NEXT: renamable $x20 = COPY $x23
    ; CHECK-NEXT: renamable $x23 = COPY renamable $x24
    ; CHECK-NEXT: $x3 = COPY renamable $x4
    ; CHECK-NEXT: BLR8 implicit $lr8, implicit undef $rm, implicit $x3, implicit $x20, implicit $x21, implicit $x22, implicit $x23
    renamable $x23 = COPY renamable $x4
    renamable $x24 = COPY renamable $x23
    renamable $x23 = COPY renamable $x22
    renamable $x22 = COPY renamable $x21
    renamable $x21 = COPY renamable $x20
    renamable $x20 = ADD8 $x4, $x5
    renamable $x4 = COPY renamable $x20
    renamable $x20 = COPY renamable $x21
    renamable $x21 = COPY renamable $x22
    renamable $x22 = COPY renamable $x23
    renamable $x23 = COPY renamable $x24
    $x3 = COPY renamable $x4
    BLR8 implicit $lr8, implicit undef $rm, implicit $x3, implicit $x20, implicit $x21, implicit $x22, implicit $x23

...

# Duplicated pairs.
---
name: test1
alignment: 4
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x3, $x20, $x21, $x22, $x23
    ; CHECK-LABEL: name: test1
    ; CHECK: liveins: $x3, $x20, $x21, $x22, $x23
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $x24 = COPY $x3
    ; CHECK-NEXT: renamable $x23 = COPY renamable $x22
    ; CHECK-NEXT: renamable $x22 = COPY renamable $x21
    ; CHECK-NEXT: renamable $x21 = COPY renamable $x20
    ; CHECK-NEXT: BLR8 implicit $lr8, implicit undef $rm, implicit $x3, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24
    renamable $x23 = COPY $x3
    renamable $x24 = COPY renamable $x23
    renamable $x23 = COPY renamable $x22
    renamable $x22 = COPY renamable $x21
    renamable $x21 = COPY renamable $x20
    renamable $x20 = COPY renamable $x21
    renamable $x21 = COPY renamable $x22
    renamable $x22 = COPY renamable $x23
    renamable $x23 = COPY renamable $x24
    renamable $x24 = COPY renamable $x23
    renamable $x23 = COPY renamable $x22
    renamable $x22 = COPY renamable $x21
    renamable $x21 = COPY renamable $x20
    BLR8 implicit $lr8, implicit undef $rm, implicit $x3, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24

...

# Chain one after one.
---
name: test2
alignment: 4
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x3, $x18, $x19, $x20, $x21, $x22, $x23, $x24
    ; CHECK-LABEL: name: test2
    ; CHECK: liveins: $x3, $x18, $x19, $x20, $x21, $x22, $x23, $x24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $x21 = COPY renamable $x20
    ; CHECK-NEXT: renamable $x20 = COPY renamable $x21
    ; CHECK-NEXT: renamable $x25 = COPY renamable $x24
    ; CHECK-NEXT: renamable $x24 = COPY renamable $x25
    ; CHECK-NEXT: BLR8 implicit $lr8, implicit undef $rm, implicit $x3, implicit $x18, implicit $x19, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24, implicit $x25
    renamable $x21 = COPY renamable $x20
    renamable $x20 = COPY renamable $x19
    renamable $x19 = COPY renamable $x18
    renamable $x18 = COPY renamable $x19
    renamable $x19 = COPY renamable $x20
    renamable $x20 = COPY renamable $x21
    renamable $x25 = COPY renamable $x24
    renamable $x24 = COPY renamable $x23
    renamable $x23 = COPY renamable $x22
    renamable $x22 = COPY renamable $x23
    renamable $x23 = COPY renamable $x24
    renamable $x24 = COPY renamable $x25
    BLR8 implicit $lr8, implicit undef $rm, implicit $x3, implicit $x18, implicit $x19, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24, implicit $x25

...

# Reorder code in test2, thus we have two chains in build simultaneously.
---
name: test3
alignment: 4
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x3, $x18, $x19, $x20, $x21, $x22, $x23, $x24
    ; CHECK-LABEL: name: test3
    ; CHECK: liveins: $x3, $x18, $x19, $x20, $x21, $x22, $x23, $x24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $x21 = COPY renamable $x20
    ; CHECK-NEXT: renamable $x25 = COPY renamable $x24
    ; CHECK-NEXT: renamable $x20 = COPY renamable $x21
    ; CHECK-NEXT: renamable $x24 = COPY renamable $x25
    ; CHECK-NEXT: BLR8 implicit $lr8, implicit undef $rm, implicit $x3, implicit $x18, implicit $x19, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24, implicit $x25
    renamable $x21 = COPY renamable $x20
    renamable $x25 = COPY renamable $x24
    renamable $x20 = COPY renamable $x19
    renamable $x24 = COPY renamable $x23
    renamable $x19 = COPY renamable $x18
    renamable $x23 = COPY renamable $x22
    renamable $x18 = COPY renamable $x19
    renamable $x22 = COPY renamable $x23
    renamable $x19 = COPY renamable $x20
    renamable $x23 = COPY renamable $x24
    renamable $x20 = COPY renamable $x21
    renamable $x24 = COPY renamable $x25
    BLR8 implicit $lr8, implicit undef $rm, implicit $x3, implicit $x18, implicit $x19, implicit $x20, implicit $x21, implicit $x22, implicit $x23, implicit $x24, implicit $x25

...

---
name: test4
alignment: 4
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x3, $x4, $x5
    ; CHECK-LABEL: name: test4
    ; CHECK: liveins: $x3, $x4, $x5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: BLR8 implicit $lr8, implicit undef $rm, implicit $x3
    renamable $x5 = COPY renamable $x3
    renamable $x4 = COPY renamable $x3
    renamable $x2 = COPY renamable $x3
    renamable $x3 = COPY renamable $x2
    renamable $x3 = COPY renamable $x4
    renamable $x3 = COPY renamable $x5
    BLR8 implicit $lr8, implicit undef $rm, implicit $x3

...

# Chain across regmask.
---
name: test5
alignment: 4
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x17, $x16, $x15, $x14, $x3
    ; CHECK-LABEL: name: test5
    ; CHECK: liveins: $x17, $x16, $x15, $x14, $x3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $x18 = COPY renamable $x17
    ; CHECK-NEXT: $x17 = COPY renamable $x3
    ; CHECK-NEXT: BL8_NOP @foo, csr_ppc64, implicit-def dead $lr8, implicit $rm, implicit-def $x3, implicit $x3
    ; CHECK-NEXT: renamable $x3 = COPY $x17
    ; CHECK-NEXT: BLR8 implicit $lr8, implicit undef $rm, implicit $x3
    renamable $x18 = COPY renamable $x17
    renamable $x17 = COPY renamable $x16
    renamable $x16 = COPY renamable $x15
    renamable $x15 = COPY renamable $x14
    renamable $x14 = COPY renamable $x3
    BL8_NOP @foo, csr_ppc64, implicit-def dead $lr8, implicit $rm, implicit-def $x3, implicit $x3
    renamable $x3 = COPY renamable $x14
    renamable $x14 = COPY renamable $x15
    renamable $x15 = COPY renamable $x16
    renamable $x16 = COPY renamable $x17
    renamable $x17 = COPY renamable $x18
    BLR8 implicit $lr8, implicit undef $rm, implicit $x3

...

# Two chains across regmask.
---
name: test6
alignment: 4
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x20, $x19, $x17, $x16, $x15, $x14, $x3, $x4
    ; CHECK-LABEL: name: test6
    ; CHECK: liveins: $x20, $x19, $x17, $x16, $x15, $x14, $x3, $x4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $x21 = COPY renamable $x20
    ; CHECK-NEXT: renamable $x18 = COPY renamable $x17
    ; CHECK-NEXT: $x17 = COPY renamable $x3
    ; CHECK-NEXT: $x20 = COPY renamable $x4
    ; CHECK-NEXT: BL8_NOP @foo, csr_ppc64, implicit-def dead $lr8, implicit $rm, implicit-def $x3, implicit $x3, implicit-def $x4, implicit $x4
    ; CHECK-NEXT: renamable $x3 = COPY $x17
    ; CHECK-NEXT: renamable $x4 = COPY $x20
    ; CHECK-NEXT: BLR8 implicit $lr8, implicit undef $rm, implicit $x3, implicit $x4
    renamable $x21 = COPY renamable $x20
    renamable $x18 = COPY renamable $x17
    renamable $x17 = COPY renamable $x16
    renamable $x16 = COPY renamable $x15
    renamable $x20 = COPY renamable $x19
    renamable $x15 = COPY renamable $x14
    renamable $x14 = COPY renamable $x3
    renamable $x19 = COPY renamable $x4
    BL8_NOP @foo, csr_ppc64, implicit-def dead $lr8, implicit $rm, implicit-def $x3, implicit $x3, implicit-def $x4, implicit $x4
    renamable $x3 = COPY renamable $x14
    renamable $x14 = COPY renamable $x15
    renamable $x4 = COPY renamable $x19
    renamable $x15 = COPY renamable $x16
    renamable $x19 = COPY renamable $x20
    renamable $x16 = COPY renamable $x17
    renamable $x20 = COPY renamable $x21
    renamable $x17 = COPY renamable $x18
    BLR8 implicit $lr8, implicit undef $rm, implicit $x3, implicit $x4

...

