; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=powerpc < %s | FileCheck %s -check-prefix PPC-32
; RUN: llc -mtriple=powerpc -mattr +altivec < %s | FileCheck %s -check-prefix PPC-32-ALTIVEC
; RUN: llc -mtriple=powerpc -mattr +vsx < %s | FileCheck %s -check-prefix PPC-32-VSX
; RUN: llc -mtriple=powerpc64 < %s | FileCheck %s -check-prefix PPC-64
; RUN: llc -mtriple=powerpc64 -mattr +altivec < %s | FileCheck %s -check-prefix PPC-64-ALTIVEC
; RUN: llc -mtriple=powerpc64 -mattr +vsx < %s | FileCheck %s -check-prefix PPC-64-VSX

define void @memop_soft_float() "use-soft-float"="true" {
; PPC-32-LABEL: memop_soft_float:
; PPC-32:       # %bb.0:
; PPC-32-NEXT:    lwz 3, 28(0)
; PPC-32-NEXT:    stw 3, 28(0)
; PPC-32-NEXT:    lwz 3, 24(0)
; PPC-32-NEXT:    stw 3, 24(0)
; PPC-32-NEXT:    lwz 3, 20(0)
; PPC-32-NEXT:    stw 3, 20(0)
; PPC-32-NEXT:    lwz 3, 16(0)
; PPC-32-NEXT:    stw 3, 16(0)
; PPC-32-NEXT:    lwz 3, 12(0)
; PPC-32-NEXT:    stw 3, 12(0)
; PPC-32-NEXT:    lwz 3, 8(0)
; PPC-32-NEXT:    stw 3, 8(0)
; PPC-32-NEXT:    lwz 3, 4(0)
; PPC-32-NEXT:    stw 3, 4(0)
; PPC-32-NEXT:    lwz 3, 0(0)
; PPC-32-NEXT:    stw 3, 0(0)
; PPC-32-NEXT:    li 3, 0
; PPC-32-NEXT:    stw 3, 28(0)
; PPC-32-NEXT:    stw 3, 24(0)
; PPC-32-NEXT:    stw 3, 20(0)
; PPC-32-NEXT:    stw 3, 16(0)
; PPC-32-NEXT:    stw 3, 12(0)
; PPC-32-NEXT:    stw 3, 8(0)
; PPC-32-NEXT:    stw 3, 4(0)
; PPC-32-NEXT:    stw 3, 0(0)
; PPC-32-NEXT:    blr
;
; PPC-32-ALTIVEC-LABEL: memop_soft_float:
; PPC-32-ALTIVEC:       # %bb.0:
; PPC-32-ALTIVEC-NEXT:    lwz 3, 28(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 28(0)
; PPC-32-ALTIVEC-NEXT:    lwz 3, 24(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 24(0)
; PPC-32-ALTIVEC-NEXT:    lwz 3, 20(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 20(0)
; PPC-32-ALTIVEC-NEXT:    lwz 3, 16(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 16(0)
; PPC-32-ALTIVEC-NEXT:    lwz 3, 12(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 12(0)
; PPC-32-ALTIVEC-NEXT:    lwz 3, 8(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 8(0)
; PPC-32-ALTIVEC-NEXT:    lwz 3, 4(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 4(0)
; PPC-32-ALTIVEC-NEXT:    lwz 3, 0(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 0(0)
; PPC-32-ALTIVEC-NEXT:    li 3, 0
; PPC-32-ALTIVEC-NEXT:    stw 3, 28(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 24(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 20(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 16(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 12(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 8(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 4(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 0(0)
; PPC-32-ALTIVEC-NEXT:    blr
;
; PPC-32-VSX-LABEL: memop_soft_float:
; PPC-32-VSX:       # %bb.0:
; PPC-32-VSX-NEXT:    lwz 3, 28(0)
; PPC-32-VSX-NEXT:    stw 3, 28(0)
; PPC-32-VSX-NEXT:    lwz 3, 24(0)
; PPC-32-VSX-NEXT:    stw 3, 24(0)
; PPC-32-VSX-NEXT:    lwz 3, 20(0)
; PPC-32-VSX-NEXT:    stw 3, 20(0)
; PPC-32-VSX-NEXT:    lwz 3, 16(0)
; PPC-32-VSX-NEXT:    stw 3, 16(0)
; PPC-32-VSX-NEXT:    lwz 3, 12(0)
; PPC-32-VSX-NEXT:    stw 3, 12(0)
; PPC-32-VSX-NEXT:    lwz 3, 8(0)
; PPC-32-VSX-NEXT:    stw 3, 8(0)
; PPC-32-VSX-NEXT:    lwz 3, 4(0)
; PPC-32-VSX-NEXT:    stw 3, 4(0)
; PPC-32-VSX-NEXT:    lwz 3, 0(0)
; PPC-32-VSX-NEXT:    stw 3, 0(0)
; PPC-32-VSX-NEXT:    li 3, 0
; PPC-32-VSX-NEXT:    stw 3, 28(0)
; PPC-32-VSX-NEXT:    stw 3, 24(0)
; PPC-32-VSX-NEXT:    stw 3, 20(0)
; PPC-32-VSX-NEXT:    stw 3, 16(0)
; PPC-32-VSX-NEXT:    stw 3, 12(0)
; PPC-32-VSX-NEXT:    stw 3, 8(0)
; PPC-32-VSX-NEXT:    stw 3, 4(0)
; PPC-32-VSX-NEXT:    stw 3, 0(0)
; PPC-32-VSX-NEXT:    blr
;
; PPC-64-LABEL: memop_soft_float:
; PPC-64:       # %bb.0:
; PPC-64-NEXT:    ld 3, 24(0)
; PPC-64-NEXT:    li 4, 0
; PPC-64-NEXT:    std 3, 24(0)
; PPC-64-NEXT:    ld 3, 16(0)
; PPC-64-NEXT:    std 3, 16(0)
; PPC-64-NEXT:    ld 3, 8(0)
; PPC-64-NEXT:    std 3, 8(0)
; PPC-64-NEXT:    ld 3, 0(0)
; PPC-64-NEXT:    std 3, 0(0)
; PPC-64-NEXT:    std 4, 24(0)
; PPC-64-NEXT:    std 4, 16(0)
; PPC-64-NEXT:    std 4, 8(0)
; PPC-64-NEXT:    std 4, 0(0)
; PPC-64-NEXT:    blr
;
; PPC-64-ALTIVEC-LABEL: memop_soft_float:
; PPC-64-ALTIVEC:       # %bb.0:
; PPC-64-ALTIVEC-NEXT:    ld 3, 24(0)
; PPC-64-ALTIVEC-NEXT:    li 4, 0
; PPC-64-ALTIVEC-NEXT:    std 3, 24(0)
; PPC-64-ALTIVEC-NEXT:    ld 3, 16(0)
; PPC-64-ALTIVEC-NEXT:    std 3, 16(0)
; PPC-64-ALTIVEC-NEXT:    ld 3, 8(0)
; PPC-64-ALTIVEC-NEXT:    std 3, 8(0)
; PPC-64-ALTIVEC-NEXT:    ld 3, 0(0)
; PPC-64-ALTIVEC-NEXT:    std 3, 0(0)
; PPC-64-ALTIVEC-NEXT:    std 4, 24(0)
; PPC-64-ALTIVEC-NEXT:    std 4, 16(0)
; PPC-64-ALTIVEC-NEXT:    std 4, 8(0)
; PPC-64-ALTIVEC-NEXT:    std 4, 0(0)
; PPC-64-ALTIVEC-NEXT:    blr
;
; PPC-64-VSX-LABEL: memop_soft_float:
; PPC-64-VSX:       # %bb.0:
; PPC-64-VSX-NEXT:    ld 3, 24(0)
; PPC-64-VSX-NEXT:    li 4, 0
; PPC-64-VSX-NEXT:    std 3, 24(0)
; PPC-64-VSX-NEXT:    ld 3, 16(0)
; PPC-64-VSX-NEXT:    std 3, 16(0)
; PPC-64-VSX-NEXT:    ld 3, 8(0)
; PPC-64-VSX-NEXT:    std 3, 8(0)
; PPC-64-VSX-NEXT:    ld 3, 0(0)
; PPC-64-VSX-NEXT:    std 3, 0(0)
; PPC-64-VSX-NEXT:    std 4, 24(0)
; PPC-64-VSX-NEXT:    std 4, 16(0)
; PPC-64-VSX-NEXT:    std 4, 8(0)
; PPC-64-VSX-NEXT:    std 4, 0(0)
; PPC-64-VSX-NEXT:    blr
    call void @llvm.memcpy.p0.p0.i32(ptr null, ptr null, i32 32, i1 true)
    call void @llvm.memset.p0.i32(ptr null, i8 0, i32 32, i1 true)
    ret void
}

define void @memop_noimplicitfloat() noimplicitfloat {
; PPC-32-LABEL: memop_noimplicitfloat:
; PPC-32:       # %bb.0:
; PPC-32-NEXT:    lwz 3, 28(0)
; PPC-32-NEXT:    stw 3, 28(0)
; PPC-32-NEXT:    lwz 3, 24(0)
; PPC-32-NEXT:    stw 3, 24(0)
; PPC-32-NEXT:    lwz 3, 20(0)
; PPC-32-NEXT:    stw 3, 20(0)
; PPC-32-NEXT:    lwz 3, 16(0)
; PPC-32-NEXT:    stw 3, 16(0)
; PPC-32-NEXT:    lwz 3, 12(0)
; PPC-32-NEXT:    stw 3, 12(0)
; PPC-32-NEXT:    lwz 3, 8(0)
; PPC-32-NEXT:    stw 3, 8(0)
; PPC-32-NEXT:    lwz 3, 4(0)
; PPC-32-NEXT:    stw 3, 4(0)
; PPC-32-NEXT:    lwz 3, 0(0)
; PPC-32-NEXT:    stw 3, 0(0)
; PPC-32-NEXT:    li 3, 0
; PPC-32-NEXT:    stw 3, 28(0)
; PPC-32-NEXT:    stw 3, 24(0)
; PPC-32-NEXT:    stw 3, 20(0)
; PPC-32-NEXT:    stw 3, 16(0)
; PPC-32-NEXT:    stw 3, 12(0)
; PPC-32-NEXT:    stw 3, 8(0)
; PPC-32-NEXT:    stw 3, 4(0)
; PPC-32-NEXT:    stw 3, 0(0)
; PPC-32-NEXT:    blr
;
; PPC-32-ALTIVEC-LABEL: memop_noimplicitfloat:
; PPC-32-ALTIVEC:       # %bb.0:
; PPC-32-ALTIVEC-NEXT:    lwz 3, 28(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 28(0)
; PPC-32-ALTIVEC-NEXT:    lwz 3, 24(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 24(0)
; PPC-32-ALTIVEC-NEXT:    lwz 3, 20(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 20(0)
; PPC-32-ALTIVEC-NEXT:    lwz 3, 16(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 16(0)
; PPC-32-ALTIVEC-NEXT:    lwz 3, 12(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 12(0)
; PPC-32-ALTIVEC-NEXT:    lwz 3, 8(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 8(0)
; PPC-32-ALTIVEC-NEXT:    lwz 3, 4(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 4(0)
; PPC-32-ALTIVEC-NEXT:    lwz 3, 0(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 0(0)
; PPC-32-ALTIVEC-NEXT:    li 3, 0
; PPC-32-ALTIVEC-NEXT:    stw 3, 28(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 24(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 20(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 16(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 12(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 8(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 4(0)
; PPC-32-ALTIVEC-NEXT:    stw 3, 0(0)
; PPC-32-ALTIVEC-NEXT:    blr
;
; PPC-32-VSX-LABEL: memop_noimplicitfloat:
; PPC-32-VSX:       # %bb.0:
; PPC-32-VSX-NEXT:    lwz 3, 28(0)
; PPC-32-VSX-NEXT:    stw 3, 28(0)
; PPC-32-VSX-NEXT:    lwz 3, 24(0)
; PPC-32-VSX-NEXT:    stw 3, 24(0)
; PPC-32-VSX-NEXT:    lwz 3, 20(0)
; PPC-32-VSX-NEXT:    stw 3, 20(0)
; PPC-32-VSX-NEXT:    lwz 3, 16(0)
; PPC-32-VSX-NEXT:    stw 3, 16(0)
; PPC-32-VSX-NEXT:    lwz 3, 12(0)
; PPC-32-VSX-NEXT:    stw 3, 12(0)
; PPC-32-VSX-NEXT:    lwz 3, 8(0)
; PPC-32-VSX-NEXT:    stw 3, 8(0)
; PPC-32-VSX-NEXT:    lwz 3, 4(0)
; PPC-32-VSX-NEXT:    stw 3, 4(0)
; PPC-32-VSX-NEXT:    lwz 3, 0(0)
; PPC-32-VSX-NEXT:    stw 3, 0(0)
; PPC-32-VSX-NEXT:    li 3, 0
; PPC-32-VSX-NEXT:    stw 3, 28(0)
; PPC-32-VSX-NEXT:    stw 3, 24(0)
; PPC-32-VSX-NEXT:    stw 3, 20(0)
; PPC-32-VSX-NEXT:    stw 3, 16(0)
; PPC-32-VSX-NEXT:    stw 3, 12(0)
; PPC-32-VSX-NEXT:    stw 3, 8(0)
; PPC-32-VSX-NEXT:    stw 3, 4(0)
; PPC-32-VSX-NEXT:    stw 3, 0(0)
; PPC-32-VSX-NEXT:    blr
;
; PPC-64-LABEL: memop_noimplicitfloat:
; PPC-64:       # %bb.0:
; PPC-64-NEXT:    ld 3, 24(0)
; PPC-64-NEXT:    li 4, 0
; PPC-64-NEXT:    std 3, 24(0)
; PPC-64-NEXT:    ld 3, 16(0)
; PPC-64-NEXT:    std 3, 16(0)
; PPC-64-NEXT:    ld 3, 8(0)
; PPC-64-NEXT:    std 3, 8(0)
; PPC-64-NEXT:    ld 3, 0(0)
; PPC-64-NEXT:    std 3, 0(0)
; PPC-64-NEXT:    std 4, 24(0)
; PPC-64-NEXT:    std 4, 16(0)
; PPC-64-NEXT:    std 4, 8(0)
; PPC-64-NEXT:    std 4, 0(0)
; PPC-64-NEXT:    blr
;
; PPC-64-ALTIVEC-LABEL: memop_noimplicitfloat:
; PPC-64-ALTIVEC:       # %bb.0:
; PPC-64-ALTIVEC-NEXT:    ld 3, 24(0)
; PPC-64-ALTIVEC-NEXT:    li 4, 0
; PPC-64-ALTIVEC-NEXT:    std 3, 24(0)
; PPC-64-ALTIVEC-NEXT:    ld 3, 16(0)
; PPC-64-ALTIVEC-NEXT:    std 3, 16(0)
; PPC-64-ALTIVEC-NEXT:    ld 3, 8(0)
; PPC-64-ALTIVEC-NEXT:    std 3, 8(0)
; PPC-64-ALTIVEC-NEXT:    ld 3, 0(0)
; PPC-64-ALTIVEC-NEXT:    std 3, 0(0)
; PPC-64-ALTIVEC-NEXT:    std 4, 24(0)
; PPC-64-ALTIVEC-NEXT:    std 4, 16(0)
; PPC-64-ALTIVEC-NEXT:    std 4, 8(0)
; PPC-64-ALTIVEC-NEXT:    std 4, 0(0)
; PPC-64-ALTIVEC-NEXT:    blr
;
; PPC-64-VSX-LABEL: memop_noimplicitfloat:
; PPC-64-VSX:       # %bb.0:
; PPC-64-VSX-NEXT:    ld 3, 24(0)
; PPC-64-VSX-NEXT:    li 4, 0
; PPC-64-VSX-NEXT:    std 3, 24(0)
; PPC-64-VSX-NEXT:    ld 3, 16(0)
; PPC-64-VSX-NEXT:    std 3, 16(0)
; PPC-64-VSX-NEXT:    ld 3, 8(0)
; PPC-64-VSX-NEXT:    std 3, 8(0)
; PPC-64-VSX-NEXT:    ld 3, 0(0)
; PPC-64-VSX-NEXT:    std 3, 0(0)
; PPC-64-VSX-NEXT:    std 4, 24(0)
; PPC-64-VSX-NEXT:    std 4, 16(0)
; PPC-64-VSX-NEXT:    std 4, 8(0)
; PPC-64-VSX-NEXT:    std 4, 0(0)
; PPC-64-VSX-NEXT:    blr
    call void @llvm.memcpy.p0.p0.i32(ptr null, ptr null, i32 32, i1 true)
    call void @llvm.memset.p0.i32(ptr null, i8 0, i32 32, i1 true)
    ret void
}

declare void @llvm.memcpy.p0.p0.i32(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i32, i1 immarg) nocallback nofree nounwind willreturn memory(argmem: readwrite)
declare void @llvm.memset.p0.i32(ptr nocapture writeonly, i8, i32, i1 immarg) nocallback nofree nounwind willreturn memory(argmem: write)
