; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=powerpc64le -mcpu=pwr10 < %s | FileCheck %s --check-prefix=CHECK-LE
; RUN: llc -mtriple=powerpc64 -mcpu=pwr10 < %s | FileCheck %s --check-prefix=CHECK-BE

define fastcc <16 x i16> @test(<16 x i1> %0) {
; CHECK-LE-LABEL: test:
; CHECK-LE:       # %bb.0: # %Entry
; CHECK-LE-NEXT:    clrldi 0, 1, 59
; CHECK-LE-NEXT:    std 30, -16(1)
; CHECK-LE-NEXT:    mr 30, 1
; CHECK-LE-NEXT:    subfic 0, 0, -96
; CHECK-LE-NEXT:    stdux 1, 1, 0
; CHECK-LE-NEXT:    .cfi_def_cfa_register r30
; CHECK-LE-NEXT:    .cfi_offset r30, -16
; CHECK-LE-NEXT:    li 3, 1
; CHECK-LE-NEXT:    xxlxor 35, 35, 35
; CHECK-LE-NEXT:    vextubrx 4, 3, 2
; CHECK-LE-NEXT:    li 3, 0
; CHECK-LE-NEXT:    vextubrx 3, 3, 2
; CHECK-LE-NEXT:    clrldi 3, 3, 63
; CHECK-LE-NEXT:    rlwimi 3, 4, 1, 30, 30
; CHECK-LE-NEXT:    li 4, 2
; CHECK-LE-NEXT:    vextubrx 4, 4, 2
; CHECK-LE-NEXT:    rlwimi 3, 4, 2, 29, 29
; CHECK-LE-NEXT:    li 4, 3
; CHECK-LE-NEXT:    vextubrx 4, 4, 2
; CHECK-LE-NEXT:    rlwimi 3, 4, 3, 28, 28
; CHECK-LE-NEXT:    li 4, 4
; CHECK-LE-NEXT:    vextubrx 4, 4, 2
; CHECK-LE-NEXT:    rlwimi 3, 4, 4, 27, 27
; CHECK-LE-NEXT:    li 4, 5
; CHECK-LE-NEXT:    vextubrx 4, 4, 2
; CHECK-LE-NEXT:    rlwimi 3, 4, 5, 26, 26
; CHECK-LE-NEXT:    li 4, 6
; CHECK-LE-NEXT:    vextubrx 4, 4, 2
; CHECK-LE-NEXT:    rlwimi 3, 4, 6, 25, 25
; CHECK-LE-NEXT:    li 4, 7
; CHECK-LE-NEXT:    vextubrx 4, 4, 2
; CHECK-LE-NEXT:    rlwimi 3, 4, 7, 24, 24
; CHECK-LE-NEXT:    li 4, 8
; CHECK-LE-NEXT:    vextubrx 4, 4, 2
; CHECK-LE-NEXT:    rlwimi 3, 4, 8, 23, 23
; CHECK-LE-NEXT:    li 4, 9
; CHECK-LE-NEXT:    vextubrx 4, 4, 2
; CHECK-LE-NEXT:    rlwimi 3, 4, 9, 22, 22
; CHECK-LE-NEXT:    li 4, 10
; CHECK-LE-NEXT:    vextubrx 4, 4, 2
; CHECK-LE-NEXT:    rlwimi 3, 4, 10, 21, 21
; CHECK-LE-NEXT:    li 4, 11
; CHECK-LE-NEXT:    vextubrx 4, 4, 2
; CHECK-LE-NEXT:    rlwimi 3, 4, 11, 20, 20
; CHECK-LE-NEXT:    li 4, 12
; CHECK-LE-NEXT:    vextubrx 4, 4, 2
; CHECK-LE-NEXT:    rlwimi 3, 4, 12, 19, 19
; CHECK-LE-NEXT:    li 4, 13
; CHECK-LE-NEXT:    vextubrx 4, 4, 2
; CHECK-LE-NEXT:    rlwimi 3, 4, 13, 18, 18
; CHECK-LE-NEXT:    li 4, 14
; CHECK-LE-NEXT:    vextubrx 4, 4, 2
; CHECK-LE-NEXT:    rlwimi 3, 4, 14, 17, 17
; CHECK-LE-NEXT:    li 4, 15
; CHECK-LE-NEXT:    vextubrx 4, 4, 2
; CHECK-LE-NEXT:    rlwimi 3, 4, 15, 16, 16
; CHECK-LE-NEXT:    mtvsrdd 34, 0, 3
; CHECK-LE-NEXT:    mr 1, 30
; CHECK-LE-NEXT:    ld 30, -16(1)
; CHECK-LE-NEXT:    blr
;
; CHECK-BE-LABEL: test:
; CHECK-BE:       # %bb.0: # %Entry
; CHECK-BE-NEXT:    clrldi 0, 1, 59
; CHECK-BE-NEXT:    std 30, -16(1)
; CHECK-BE-NEXT:    mr 30, 1
; CHECK-BE-NEXT:    subfic 0, 0, -128
; CHECK-BE-NEXT:    stdux 1, 1, 0
; CHECK-BE-NEXT:    .cfi_def_cfa_register r30
; CHECK-BE-NEXT:    .cfi_offset r30, -16
; CHECK-BE-NEXT:    li 3, 1
; CHECK-BE-NEXT:    xxlxor 35, 35, 35
; CHECK-BE-NEXT:    vextublx 5, 3, 2
; CHECK-BE-NEXT:    li 3, 0
; CHECK-BE-NEXT:    vextublx 4, 3, 2
; CHECK-BE-NEXT:    clrldi 4, 4, 63
; CHECK-BE-NEXT:    rlwimi 4, 5, 1, 30, 30
; CHECK-BE-NEXT:    li 5, 2
; CHECK-BE-NEXT:    vextublx 5, 5, 2
; CHECK-BE-NEXT:    rlwimi 4, 5, 2, 29, 29
; CHECK-BE-NEXT:    li 5, 3
; CHECK-BE-NEXT:    vextublx 5, 5, 2
; CHECK-BE-NEXT:    rlwimi 4, 5, 3, 28, 28
; CHECK-BE-NEXT:    li 5, 4
; CHECK-BE-NEXT:    vextublx 5, 5, 2
; CHECK-BE-NEXT:    rlwimi 4, 5, 4, 27, 27
; CHECK-BE-NEXT:    li 5, 5
; CHECK-BE-NEXT:    vextublx 5, 5, 2
; CHECK-BE-NEXT:    rlwimi 4, 5, 5, 26, 26
; CHECK-BE-NEXT:    li 5, 6
; CHECK-BE-NEXT:    vextublx 5, 5, 2
; CHECK-BE-NEXT:    rlwimi 4, 5, 6, 25, 25
; CHECK-BE-NEXT:    li 5, 7
; CHECK-BE-NEXT:    vextublx 5, 5, 2
; CHECK-BE-NEXT:    rlwimi 4, 5, 7, 24, 24
; CHECK-BE-NEXT:    li 5, 8
; CHECK-BE-NEXT:    vextublx 5, 5, 2
; CHECK-BE-NEXT:    rlwimi 4, 5, 8, 23, 23
; CHECK-BE-NEXT:    li 5, 9
; CHECK-BE-NEXT:    vextublx 5, 5, 2
; CHECK-BE-NEXT:    rlwimi 4, 5, 9, 22, 22
; CHECK-BE-NEXT:    li 5, 10
; CHECK-BE-NEXT:    vextublx 5, 5, 2
; CHECK-BE-NEXT:    rlwimi 4, 5, 10, 21, 21
; CHECK-BE-NEXT:    li 5, 11
; CHECK-BE-NEXT:    vextublx 5, 5, 2
; CHECK-BE-NEXT:    rlwimi 4, 5, 11, 20, 20
; CHECK-BE-NEXT:    li 5, 12
; CHECK-BE-NEXT:    vextublx 5, 5, 2
; CHECK-BE-NEXT:    rlwimi 4, 5, 12, 19, 19
; CHECK-BE-NEXT:    li 5, 13
; CHECK-BE-NEXT:    vextublx 5, 5, 2
; CHECK-BE-NEXT:    rlwimi 4, 5, 13, 18, 18
; CHECK-BE-NEXT:    li 5, 14
; CHECK-BE-NEXT:    vextublx 5, 5, 2
; CHECK-BE-NEXT:    rlwimi 4, 5, 14, 17, 17
; CHECK-BE-NEXT:    li 5, 15
; CHECK-BE-NEXT:    vextublx 5, 5, 2
; CHECK-BE-NEXT:    rlwimi 4, 5, 15, 16, 16
; CHECK-BE-NEXT:    mtvsrdd 34, 4, 3
; CHECK-BE-NEXT:    mr 1, 30
; CHECK-BE-NEXT:    ld 30, -16(1)
; CHECK-BE-NEXT:    blr
Entry:
  %1 = bitcast <16 x i1> %0 to i16
  %2 = insertelement <16 x i16> zeroinitializer, i16 %1, i64 0
  ret <16 x i16> %2
}
