; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple powerpc | FileCheck %s -check-prefixes=CHECK-32-BE
; RUN: llc < %s -mtriple powerpcle | FileCheck %s -check-prefixes=CHECK-32-LE
; RUN: llc < %s -mtriple powerpc64 | FileCheck %s -check-prefixes=CHECK-64-BE
; RUN: llc < %s -mtriple powerpc64le | FileCheck %s -check-prefixes=CHECK-64-LE

declare dso_local void @main()

define dso_local void @naked() naked "frame-pointer"="all" {
; CHECK-32-BE-LABEL: naked:
; CHECK-32-BE:       # %bb.0:
; CHECK-32-BE-NEXT:    bl main
;
; CHECK-32-LE-LABEL: naked:
; CHECK-32-LE:       # %bb.0:
; CHECK-32-LE-NEXT:    bl main
;
; CHECK-64-BE-LABEL: naked:
; CHECK-64-BE:       # %bb.0:
; CHECK-64-BE-NEXT:    bl main
; CHECK-64-BE-NEXT:    nop
;
; CHECK-64-LE-LABEL: naked:
; CHECK-64-LE:       # %bb.0:
; CHECK-64-LE-NEXT:    bl main
; CHECK-64-LE-NEXT:    nop
  call void @main()
  unreachable
}

define dso_local void @normal() "frame-pointer"="all" {
; CHECK-32-BE-LABEL: normal:
; CHECK-32-BE:       # %bb.0:
; CHECK-32-BE-NEXT:    mflr 0
; CHECK-32-BE-NEXT:    stwu 1, -16(1)
; CHECK-32-BE-NEXT:    stw 31, 12(1)
; CHECK-32-BE-NEXT:    stw 0, 20(1)
; CHECK-32-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-32-BE-NEXT:    .cfi_offset r31, -4
; CHECK-32-BE-NEXT:    .cfi_offset lr, 4
; CHECK-32-BE-NEXT:    mr 31, 1
; CHECK-32-BE-NEXT:    .cfi_def_cfa_register r31
; CHECK-32-BE-NEXT:    bl main
;
; CHECK-32-LE-LABEL: normal:
; CHECK-32-LE:       # %bb.0:
; CHECK-32-LE-NEXT:    mflr 0
; CHECK-32-LE-NEXT:    stwu 1, -16(1)
; CHECK-32-LE-NEXT:    stw 31, 12(1)
; CHECK-32-LE-NEXT:    stw 0, 20(1)
; CHECK-32-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-32-LE-NEXT:    .cfi_offset r31, -4
; CHECK-32-LE-NEXT:    .cfi_offset lr, 4
; CHECK-32-LE-NEXT:    mr 31, 1
; CHECK-32-LE-NEXT:    .cfi_def_cfa_register r31
; CHECK-32-LE-NEXT:    bl main
;
; CHECK-64-BE-LABEL: normal:
; CHECK-64-BE:       # %bb.0:
; CHECK-64-BE-NEXT:    mflr 0
; CHECK-64-BE-NEXT:    std 31, -8(1)
; CHECK-64-BE-NEXT:    stdu 1, -128(1)
; CHECK-64-BE-NEXT:    std 0, 144(1)
; CHECK-64-BE-NEXT:    .cfi_def_cfa_offset 128
; CHECK-64-BE-NEXT:    .cfi_offset r31, -8
; CHECK-64-BE-NEXT:    .cfi_offset lr, 16
; CHECK-64-BE-NEXT:    mr 31, 1
; CHECK-64-BE-NEXT:    .cfi_def_cfa_register r31
; CHECK-64-BE-NEXT:    bl main
; CHECK-64-BE-NEXT:    nop
;
; CHECK-64-LE-LABEL: normal:
; CHECK-64-LE:       # %bb.0:
; CHECK-64-LE-NEXT:    mflr 0
; CHECK-64-LE-NEXT:    std 31, -8(1)
; CHECK-64-LE-NEXT:    stdu 1, -48(1)
; CHECK-64-LE-NEXT:    std 0, 64(1)
; CHECK-64-LE-NEXT:    .cfi_def_cfa_offset 48
; CHECK-64-LE-NEXT:    .cfi_offset r31, -8
; CHECK-64-LE-NEXT:    .cfi_offset lr, 16
; CHECK-64-LE-NEXT:    mr 31, 1
; CHECK-64-LE-NEXT:    .cfi_def_cfa_register r31
; CHECK-64-LE-NEXT:    bl main
; CHECK-64-LE-NEXT:    nop
  call void @main()
  unreachable
}
