; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O0 -verify-machineinstrs < %s -mtriple=powerpc-ibm-aix-xcoff | FileCheck %s
; RUN: llc -O0 -verify-machineinstrs < %s -mtriple=powerpc64le-unknown-linux-gnu | FileCheck %s --check-prefix=PPC64

@byteVal = dso_local global i8 15, align 1

; Test writing i8 value to a named register
define dso_local void @testSetByteReg(i8 noundef signext %val) nounwind {
; CHECK-LABEL: testSetByteReg:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mr 5, 3
; CHECK-NEXT:    # kill: def $r3 killed $r5
; CHECK-NEXT:    blr
;
; PPC64-LABEL: testSetByteReg:
; PPC64:       # %bb.0: # %entry
; PPC64-NEXT:    mr 5, 3
; PPC64-NEXT:    blr
entry:
  tail call void @llvm.write_register.i8(metadata !0, i8 %val)
  ret void
}

declare void @llvm.write_register.i8(metadata, i8)

; Test reading i8 value from a named register
define dso_local signext i8 @testGetByteReg() nounwind {
; CHECK-LABEL: testGetByteReg:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    stw 23, -36(1) # 4-byte Folded Spill
; CHECK-NEXT:    stw 24, -32(1) # 4-byte Folded Spill
; CHECK-NEXT:    stw 25, -28(1) # 4-byte Folded Spill
; CHECK-NEXT:    stw 26, -24(1) # 4-byte Folded Spill
; CHECK-NEXT:    stw 27, -20(1) # 4-byte Folded Spill
; CHECK-NEXT:    stw 28, -16(1) # 4-byte Folded Spill
; CHECK-NEXT:    stw 29, -12(1) # 4-byte Folded Spill
; CHECK-NEXT:    stw 30, -8(1) # 4-byte Folded Spill
; CHECK-NEXT:    stw 31, -4(1) # 4-byte Folded Spill
; CHECK-NEXT:    li 23, 42
; CHECK-NEXT:    extsb 3, 23
; CHECK-NEXT:    lwz 31, -4(1) # 4-byte Folded Reload
; CHECK-NEXT:    lwz 30, -8(1) # 4-byte Folded Reload
; CHECK-NEXT:    lwz 29, -12(1) # 4-byte Folded Reload
; CHECK-NEXT:    lwz 28, -16(1) # 4-byte Folded Reload
; CHECK-NEXT:    lwz 27, -20(1) # 4-byte Folded Reload
; CHECK-NEXT:    lwz 26, -24(1) # 4-byte Folded Reload
; CHECK-NEXT:    lwz 25, -28(1) # 4-byte Folded Reload
; CHECK-NEXT:    lwz 24, -32(1) # 4-byte Folded Reload
; CHECK-NEXT:    lwz 23, -36(1) # 4-byte Folded Reload
; CHECK-NEXT:    blr
;
; PPC64-LABEL: testGetByteReg:
; PPC64:       # %bb.0: # %entry
; PPC64-NEXT:    std 23, -72(1) # 8-byte Folded Spill
; PPC64-NEXT:    li 23, 42
; PPC64-NEXT:    extsb 3, 23
; PPC64-NEXT:    ld 23, -72(1) # 8-byte Folded Reload
; PPC64-NEXT:    blr
entry:
  tail call void @llvm.write_register.i8(metadata !1, i8 42)
  %0 = tail call i8 @llvm.read_register.i8(metadata !1)
  ret i8 %0
}

declare i8 @llvm.read_register.i8(metadata)

; Test comparing i8 value from register with memory
define dso_local signext i32 @testCmpByteReg() nounwind {
; CHECK-LABEL: testCmpByteReg:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lwz 3, L..C0(2) # @byteVal
; CHECK-NEXT:    lbz 3, 0(3)
; CHECK-NEXT:    xori 3, 3, 15
; CHECK-NEXT:    cntlzw 3, 3
; CHECK-NEXT:    srwi 3, 3, 5
; CHECK-NEXT:    blr
;
; PPC64-LABEL: testCmpByteReg:
; PPC64:       # %bb.0: # %entry
; PPC64-NEXT:    addis 3, 2, byteVal@toc@ha
; PPC64-NEXT:    addi 3, 3, byteVal@toc@l
; PPC64-NEXT:    lbz 3, 0(3)
; PPC64-NEXT:    cmpwi 3, 15
; PPC64-NEXT:    crmove 20, 2
; PPC64-NEXT:    li 4, 0
; PPC64-NEXT:    li 3, 1
; PPC64-NEXT:    isel 3, 3, 4, 20
; PPC64-NEXT:    extsw 3, 3
; PPC64-NEXT:    blr
entry:
  tail call void @llvm.write_register.i8(metadata !0, i8 15)
  %0 = load i8, ptr @byteVal, align 1
  %1 = tail call i8 @llvm.read_register.i8(metadata !0)
  %cmp = icmp eq i8 %0, %1
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

; Test zero-extending i8 from register
define dso_local zeroext i8 @testZextByteReg(i8 noundef zeroext %val) nounwind {
; CHECK-LABEL: testZextByteReg:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mr 5, 3
; CHECK-NEXT:    # kill: def $r3 killed $r5
; CHECK-NEXT:    clrlwi 3, 5, 24
; CHECK-NEXT:    blr
;
; PPC64-LABEL: testZextByteReg:
; PPC64:       # %bb.0: # %entry
; PPC64-NEXT:    mr 5, 3
; PPC64-NEXT:    clrldi 3, 5, 56
; PPC64-NEXT:    blr
entry:
  tail call void @llvm.write_register.i8(metadata !0, i8 %val)
  %0 = tail call i8 @llvm.read_register.i8(metadata !0)
  ret i8 %0
}

!0 = !{!"r5"}
!1 = !{!"r23"}
