; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -verify-machineinstrs -mcpu=pwr8 -mtriple=powerpc64-ibm-aix \
; RUN:     -ppc-asm-full-reg-names --ppc-vsr-nums-as-vr < %s | FileCheck %s
define noundef i64 @swap8_openxl(i64 noundef %value) local_unnamed_addr #0 {
; CHECK-LABEL: swap8_openxl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rotldi r5, r3, 16
; CHECK-NEXT:    rotldi r4, r3, 8
; CHECK-NEXT:    rldimi r4, r5, 8, 48
; CHECK-NEXT:    rotldi r5, r3, 24
; CHECK-NEXT:    rldimi r4, r5, 16, 40
; CHECK-NEXT:    rotldi r5, r3, 32
; CHECK-NEXT:    rldimi r4, r5, 24, 32
; CHECK-NEXT:    rotldi r5, r3, 48
; CHECK-NEXT:    rldimi r4, r5, 40, 16
; CHECK-NEXT:    rotldi r5, r3, 56
; CHECK-NEXT:    rldimi r4, r5, 48, 8
; CHECK-NEXT:    rldimi r4, r3, 56, 0
; CHECK-NEXT:    mr r3, r4
; CHECK-NEXT:    blr
entry:
  %0 = tail call i64 @llvm.bswap.i64(i64 %value)
  ret i64 %0
}
