# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=powerpc64le -run-pass=postra-machine-sink -o - %s | FileCheck %s

---
name:            test_undef_use_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_undef_use_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $x3 = LI8 1
  ; CHECK-NEXT:   renamable $x4 = COPY killed renamable $x3, implicit undef $x5
  ; CHECK-NEXT:   $x5 = LI8 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $x4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BLR8 implicit $lr8, implicit $rm, implicit $x4
  bb.0:
    successors: %bb.1

    renamable $x3 = LI8 1
    renamable $x4 = COPY killed renamable $x3, implicit undef $x5
    $x5 = LI8 0

  bb.1:
    liveins: $x4
    BLR8 implicit $lr8, implicit $rm, implicit $x4
...
---
name:            test_internal_read_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_internal_read_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $x3 = LI8 1
  ; CHECK-NEXT:   renamable $x4 = COPY killed renamable $x3, implicit-def $x5, implicit internal $x5
  ; CHECK-NEXT:   $x6 = LI8 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $x4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BLR8 implicit $lr8, implicit $rm, implicit $x4
  bb.0:
    successors: %bb.1

    renamable $x3 = LI8 1
    renamable $x4 = COPY killed renamable $x3, implicit-def $x5, implicit internal $x5
    $x6 = LI8 0

  bb.1:
    liveins: $x4
    BLR8 implicit $lr8, implicit $rm, implicit $x4
...
