; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mcpu=pwr8 -ppc-asm-full-reg-names -mtriple=powerpc64-ibm-aix < %s | \
; RUN:   FileCheck %s --check-prefixes=COMMON,CHECK-AIX64
; RUN: llc -mcpu=pwr8 -ppc-asm-full-reg-names -mtriple=powerpc64le-unknown-linux-gnu < %s | \
; RUN:   FileCheck %s --check-prefixes=COMMON,CHECK-LINUX
; RUN: llc -mcpu=pwr8 -ppc-asm-full-reg-names -mtriple=powerpc-ibm-aix < %s | \
; RUN:   FileCheck %s --check-prefixes=COMMON,CHECK-AIX32

define i1 @test1() {
; CHECK-AIX64-LABEL: test1:
; CHECK-AIX64:       # %bb.0: # %bb
; CHECK-AIX64-NEXT:    ld r3, 0(0)
; CHECK-AIX64-NEXT:    ld r4, 8(0)
; CHECK-AIX64-NEXT:    or r3, r4, r3
; CHECK-AIX64-NEXT:    cntlzd r3, r3
; CHECK-AIX64-NEXT:    rldicl r3, r3, 58, 63
; CHECK-AIX64-NEXT:    blr
;
; CHECK-LINUX-LABEL: test1:
; CHECK-LINUX:       # %bb.0: # %bb
; CHECK-LINUX-NEXT:    ld r3, 8(0)
; CHECK-LINUX-NEXT:    ld r4, 0(0)
; CHECK-LINUX-NEXT:    or r3, r4, r3
; CHECK-LINUX-NEXT:    cntlzd r3, r3
; CHECK-LINUX-NEXT:    rldicl r3, r3, 58, 63
; CHECK-LINUX-NEXT:    blr
;
; CHECK-AIX32-LABEL: test1:
; CHECK-AIX32:       # %bb.0: # %bb
; CHECK-AIX32-NEXT:    li r3, 0
; CHECK-AIX32-NEXT:    xxlxor vs35, vs35, vs35
; CHECK-AIX32-NEXT:    lxvw4x vs34, 0, r3
; CHECK-AIX32-NEXT:    vcmpequb. v2, v2, v3
; CHECK-AIX32-NEXT:    mfocrf r3, 2
; CHECK-AIX32-NEXT:    rlwinm r3, r3, 25, 31, 31
; CHECK-AIX32-NEXT:    blr
bb:
  %load = load i128, ptr null, align 16
  %icmp = icmp eq i128 %load, 0
  ret i1 %icmp
}

define i1 @test2() {
; CHECK-AIX64-LABEL: test2:
; CHECK-AIX64:       # %bb.0: # %bb
; CHECK-AIX64-NEXT:    ld r4, 8(0)
; CHECK-AIX64-NEXT:    ld r3, 0(0)
; CHECK-AIX64-NEXT:    xori r4, r4, 10
; CHECK-AIX64-NEXT:    or r3, r4, r3
; CHECK-AIX64-NEXT:    cntlzd r3, r3
; CHECK-AIX64-NEXT:    rldicl r3, r3, 58, 63
; CHECK-AIX64-NEXT:    blr
;
; CHECK-LINUX-LABEL: test2:
; CHECK-LINUX:       # %bb.0: # %bb
; CHECK-LINUX-NEXT:    ld r4, 0(0)
; CHECK-LINUX-NEXT:    ld r3, 8(0)
; CHECK-LINUX-NEXT:    xori r4, r4, 10
; CHECK-LINUX-NEXT:    or r3, r4, r3
; CHECK-LINUX-NEXT:    cntlzd r3, r3
; CHECK-LINUX-NEXT:    rldicl r3, r3, 58, 63
; CHECK-LINUX-NEXT:    blr
;
; CHECK-AIX32-LABEL: test2:
; CHECK-AIX32:       # %bb.0: # %bb
; CHECK-AIX32-NEXT:    li r3, 0
; CHECK-AIX32-NEXT:    lxvw4x vs34, 0, r3
; CHECK-AIX32-NEXT:    lwz r3, L..C0(r2) # %const.0
; CHECK-AIX32-NEXT:    lxvw4x vs35, 0, r3
; CHECK-AIX32-NEXT:    vcmpequb. v2, v2, v3
; CHECK-AIX32-NEXT:    mfocrf r3, 2
; CHECK-AIX32-NEXT:    rlwinm r3, r3, 25, 31, 31
; CHECK-AIX32-NEXT:    blr
bb:
  %load = load i128, ptr null, align 16
  %icmp = icmp eq i128 %load, 10
  ret i1 %icmp
}

define i1 @test3() {
; CHECK-AIX64-LABEL: test3:
; CHECK-AIX64:       # %bb.0: # %bb
; CHECK-AIX64-NEXT:    ld r4, 8(0)
; CHECK-AIX64-NEXT:    ld r3, 0(0)
; CHECK-AIX64-NEXT:    xori r4, r4, 65535
; CHECK-AIX64-NEXT:    or r3, r4, r3
; CHECK-AIX64-NEXT:    cntlzd r3, r3
; CHECK-AIX64-NEXT:    rldicl r3, r3, 58, 63
; CHECK-AIX64-NEXT:    blr
;
; CHECK-LINUX-LABEL: test3:
; CHECK-LINUX:       # %bb.0: # %bb
; CHECK-LINUX-NEXT:    ld r4, 0(0)
; CHECK-LINUX-NEXT:    ld r3, 8(0)
; CHECK-LINUX-NEXT:    xori r4, r4, 65535
; CHECK-LINUX-NEXT:    or r3, r4, r3
; CHECK-LINUX-NEXT:    cntlzd r3, r3
; CHECK-LINUX-NEXT:    rldicl r3, r3, 58, 63
; CHECK-LINUX-NEXT:    blr
;
; CHECK-AIX32-LABEL: test3:
; CHECK-AIX32:       # %bb.0: # %bb
; CHECK-AIX32-NEXT:    li r3, 0
; CHECK-AIX32-NEXT:    lxvw4x vs34, 0, r3
; CHECK-AIX32-NEXT:    lwz r3, L..C1(r2) # %const.0
; CHECK-AIX32-NEXT:    lxvw4x vs35, 0, r3
; CHECK-AIX32-NEXT:    vcmpequb. v2, v2, v3
; CHECK-AIX32-NEXT:    mfocrf r3, 2
; CHECK-AIX32-NEXT:    rlwinm r3, r3, 25, 31, 31
; CHECK-AIX32-NEXT:    blr
bb:
  %load = load i128, ptr null, align 16
  %icmp = icmp eq i128 %load, 65535
  ret i1 %icmp
}

define i1 @test4() {
; CHECK-AIX64-LABEL: test4:
; CHECK-AIX64:       # %bb.0: # %bb
; CHECK-AIX64-NEXT:    li r3, 0
; CHECK-AIX64-NEXT:    lxvw4x vs34, 0, r3
; CHECK-AIX64-NEXT:    ld r3, L..C0(r2) # %const.0
; CHECK-AIX64-NEXT:    lxvd2x vs35, 0, r3
; CHECK-AIX64-NEXT:    vcmpequb. v2, v2, v3
; CHECK-AIX64-NEXT:    mfocrf r3, 2
; CHECK-AIX64-NEXT:    rlwinm r3, r3, 25, 31, 31
; CHECK-AIX64-NEXT:    blr
;
; CHECK-LINUX-LABEL: test4:
; CHECK-LINUX:       # %bb.0: # %bb
; CHECK-LINUX-NEXT:    li r3, 0
; CHECK-LINUX-NEXT:    lxvd2x vs34, 0, r3
; CHECK-LINUX-NEXT:    addis r3, r2, .LCPI3_0@toc@ha
; CHECK-LINUX-NEXT:    addi r3, r3, .LCPI3_0@toc@l
; CHECK-LINUX-NEXT:    lxvd2x vs35, 0, r3
; CHECK-LINUX-NEXT:    vcmpequb. v2, v2, v3
; CHECK-LINUX-NEXT:    mfocrf r3, 2
; CHECK-LINUX-NEXT:    rlwinm r3, r3, 25, 31, 31
; CHECK-LINUX-NEXT:    blr
;
; CHECK-AIX32-LABEL: test4:
; CHECK-AIX32:       # %bb.0: # %bb
; CHECK-AIX32-NEXT:    li r3, 0
; CHECK-AIX32-NEXT:    lxvw4x vs34, 0, r3
; CHECK-AIX32-NEXT:    lwz r3, L..C2(r2) # %const.0
; CHECK-AIX32-NEXT:    lxvw4x vs35, 0, r3
; CHECK-AIX32-NEXT:    vcmpequb. v2, v2, v3
; CHECK-AIX32-NEXT:    mfocrf r3, 2
; CHECK-AIX32-NEXT:    rlwinm r3, r3, 25, 31, 31
; CHECK-AIX32-NEXT:    blr
bb:
  %load = load i128, ptr null, align 16
  %icmp = icmp eq i128 %load, 65536
  ret i1 %icmp
}

; Test using the !range metadata
define i1 @test5() {
; CHECK-AIX64-LABEL: test5:
; CHECK-AIX64:       # %bb.0: # %bb
; CHECK-AIX64-NEXT:    ld r3, 0(0)
; CHECK-AIX64-NEXT:    ld r4, 8(0)
; CHECK-AIX64-NEXT:    or r3, r4, r3
; CHECK-AIX64-NEXT:    cntlzd r3, r3
; CHECK-AIX64-NEXT:    rldicl r3, r3, 58, 63
; CHECK-AIX64-NEXT:    blr
;
; CHECK-LINUX-LABEL: test5:
; CHECK-LINUX:       # %bb.0: # %bb
; CHECK-LINUX-NEXT:    ld r3, 8(0)
; CHECK-LINUX-NEXT:    ld r4, 0(0)
; CHECK-LINUX-NEXT:    or r3, r4, r3
; CHECK-LINUX-NEXT:    cntlzd r3, r3
; CHECK-LINUX-NEXT:    rldicl r3, r3, 58, 63
; CHECK-LINUX-NEXT:    blr
;
; CHECK-AIX32-LABEL: test5:
; CHECK-AIX32:       # %bb.0: # %bb
; CHECK-AIX32-NEXT:    li r3, 0
; CHECK-AIX32-NEXT:    xxlxor vs35, vs35, vs35
; CHECK-AIX32-NEXT:    lxvw4x vs34, 0, r3
; CHECK-AIX32-NEXT:    vcmpequb. v2, v2, v3
; CHECK-AIX32-NEXT:    mfocrf r3, 2
; CHECK-AIX32-NEXT:    rlwinm r3, r3, 25, 31, 31
; CHECK-AIX32-NEXT:    blr
bb:
  %load = load i128, ptr null, align 16, !range !0
  %icmp = icmp eq i128 %load, 0
  ret i1 %icmp
}

define i1 @test6() {
; CHECK-AIX64-LABEL: test6:
; CHECK-AIX64:       # %bb.0: # %bb
; CHECK-AIX64-NEXT:    ld r4, 8(0)
; CHECK-AIX64-NEXT:    ld r3, 0(0)
; CHECK-AIX64-NEXT:    xori r4, r4, 65535
; CHECK-AIX64-NEXT:    or r3, r4, r3
; CHECK-AIX64-NEXT:    cntlzd r3, r3
; CHECK-AIX64-NEXT:    rldicl r3, r3, 58, 63
; CHECK-AIX64-NEXT:    blr
;
; CHECK-LINUX-LABEL: test6:
; CHECK-LINUX:       # %bb.0: # %bb
; CHECK-LINUX-NEXT:    ld r4, 0(0)
; CHECK-LINUX-NEXT:    ld r3, 8(0)
; CHECK-LINUX-NEXT:    xori r4, r4, 65535
; CHECK-LINUX-NEXT:    or r3, r4, r3
; CHECK-LINUX-NEXT:    cntlzd r3, r3
; CHECK-LINUX-NEXT:    rldicl r3, r3, 58, 63
; CHECK-LINUX-NEXT:    blr
;
; CHECK-AIX32-LABEL: test6:
; CHECK-AIX32:       # %bb.0: # %bb
; CHECK-AIX32-NEXT:    li r3, 0
; CHECK-AIX32-NEXT:    lxvw4x vs34, 0, r3
; CHECK-AIX32-NEXT:    lwz r3, L..C3(r2) # %const.0
; CHECK-AIX32-NEXT:    lxvw4x vs35, 0, r3
; CHECK-AIX32-NEXT:    vcmpequb. v2, v2, v3
; CHECK-AIX32-NEXT:    mfocrf r3, 2
; CHECK-AIX32-NEXT:    rlwinm r3, r3, 25, 31, 31
; CHECK-AIX32-NEXT:    blr
bb:
  %load = load i128, ptr null, align 16, !range !1
  %icmp = icmp eq i128 %load, 65535
  ret i1 %icmp
}

define i1 @test7() {
; COMMON-LABEL: test7:
; COMMON:       # %bb.0: # %bb
; COMMON-NEXT:    li r3, 0
; COMMON-NEXT:    blr
bb:
  %load = load i128, ptr null, align 16, !range !1
  %icmp = icmp eq i128 %load, 65536
  ret i1 %icmp
}

define i1 @test8() {
; CHECK-AIX64-LABEL: test8:
; CHECK-AIX64:       # %bb.0: # %bb
; CHECK-AIX64-NEXT:    li r3, 0
; CHECK-AIX64-NEXT:    lxvw4x vs34, 0, r3
; CHECK-AIX64-NEXT:    ld r3, L..C1(r2) # %const.0
; CHECK-AIX64-NEXT:    lxvd2x vs35, 0, r3
; CHECK-AIX64-NEXT:    vcmpequb. v2, v2, v3
; CHECK-AIX64-NEXT:    mfocrf r3, 2
; CHECK-AIX64-NEXT:    rlwinm r3, r3, 25, 31, 31
; CHECK-AIX64-NEXT:    blr
;
; CHECK-LINUX-LABEL: test8:
; CHECK-LINUX:       # %bb.0: # %bb
; CHECK-LINUX-NEXT:    li r3, 0
; CHECK-LINUX-NEXT:    lxvd2x vs34, 0, r3
; CHECK-LINUX-NEXT:    addis r3, r2, .LCPI7_0@toc@ha
; CHECK-LINUX-NEXT:    addi r3, r3, .LCPI7_0@toc@l
; CHECK-LINUX-NEXT:    lxvd2x vs35, 0, r3
; CHECK-LINUX-NEXT:    vcmpequb. v2, v2, v3
; CHECK-LINUX-NEXT:    mfocrf r3, 2
; CHECK-LINUX-NEXT:    rlwinm r3, r3, 25, 31, 31
; CHECK-LINUX-NEXT:    blr
;
; CHECK-AIX32-LABEL: test8:
; CHECK-AIX32:       # %bb.0: # %bb
; CHECK-AIX32-NEXT:    li r3, 0
; CHECK-AIX32-NEXT:    lxvw4x vs34, 0, r3
; CHECK-AIX32-NEXT:    lwz r3, L..C4(r2) # %const.0
; CHECK-AIX32-NEXT:    lxvw4x vs35, 0, r3
; CHECK-AIX32-NEXT:    vcmpequb. v2, v2, v3
; CHECK-AIX32-NEXT:    mfocrf r3, 2
; CHECK-AIX32-NEXT:    rlwinm r3, r3, 25, 31, 31
; CHECK-AIX32-NEXT:    blr
bb:
  %load = load i128, ptr null, align 16, !range !2
  %icmp = icmp eq i128 %load, 65536
  ret i1 %icmp
}

!0 = !{i128 0, i128 2}
!1 = !{i128 0, i128 65536}
!2 = !{i128 0, i128 65537}
