; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mcpu=pwr9 -verify-machineinstrs < %s -mtriple=powerpc-unknown-linux-gnu | FileCheck %s

define internal fp128 @f(i128 %v) nounwind {
; CHECK-LABEL: f:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    stwu 1, -32(1)
; CHECK-NEXT:    stw 6, 28(1)
; CHECK-NEXT:    stw 5, 24(1)
; CHECK-NEXT:    stw 4, 20(1)
; CHECK-NEXT:    stw 3, 16(1)
; CHECK-NEXT:    lxv 34, 16(1)
; CHECK-NEXT:    addi 1, 1, 32
; CHECK-NEXT:    blr
entry:
  %cast = bitcast i128 %v to fp128
  ret fp128 %cast
}

