; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Test file to verify the prologue and epilogue insertion point computation by the shrink-wrap pass

; RUN: llc -verify-machineinstrs < %s -mtriple=powerpc64le-unknown-unknown -mcpu=pwr9 | FileCheck %s --check-prefixes=POWERPC64
; RUN: llc -verify-machineinstrs < %s -mtriple=powerpc-ibm-aix-xcoff -mcpu=pwr9 | FileCheck %s --check-prefixes=POWERPC32-AIX
; RUN: llc -verify-machineinstrs < %s -mtriple=powerpc64-ibm-aix-xcoff -mcpu=pwr9 | FileCheck %s --check-prefixes=POWERPC64-AIX

define void @foo(ptr noundef readnone %parent_frame_pointer) {
; POWERPC64-LABEL: foo:
; POWERPC64:       # %bb.0: # %entry
; POWERPC64-NEXT:    mflr 0
; POWERPC64-NEXT:    stdu 1, -32(1)
; POWERPC64-NEXT:    std 0, 48(1)
; POWERPC64-NEXT:    .cfi_def_cfa_offset 32
; POWERPC64-NEXT:    .cfi_offset lr, 16
; POWERPC64-NEXT:    cmpld 3, 1
; POWERPC64-NEXT:    ble- 0, .LBB0_2
; POWERPC64-NEXT:  # %bb.1: # %cond.end
; POWERPC64-NEXT:    addi 1, 1, 32
; POWERPC64-NEXT:    ld 0, 16(1)
; POWERPC64-NEXT:    mtlr 0
; POWERPC64-NEXT:    blr
; POWERPC64-NEXT:  .LBB0_2: # %cond.false
; POWERPC64-NEXT:    bl abort
; POWERPC64-NEXT:    nop
;
; POWERPC32-AIX-LABEL: foo:
; POWERPC32-AIX:       # %bb.0: # %entry
; POWERPC32-AIX-NEXT:    mflr 0
; POWERPC32-AIX-NEXT:    stwu 1, -64(1)
; POWERPC32-AIX-NEXT:    cmplw 3, 1
; POWERPC32-AIX-NEXT:    stw 0, 72(1)
; POWERPC32-AIX-NEXT:    ble- 0, L..BB0_2
; POWERPC32-AIX-NEXT:  # %bb.1: # %cond.end
; POWERPC32-AIX-NEXT:    addi 1, 1, 64
; POWERPC32-AIX-NEXT:    lwz 0, 8(1)
; POWERPC32-AIX-NEXT:    mtlr 0
; POWERPC32-AIX-NEXT:    blr
; POWERPC32-AIX-NEXT:  L..BB0_2: # %cond.false
; POWERPC32-AIX-NEXT:    bl .abort[PR]
; POWERPC32-AIX-NEXT:    nop
;
; POWERPC64-AIX-LABEL: foo:
; POWERPC64-AIX:       # %bb.0: # %entry
; POWERPC64-AIX-NEXT:    mflr 0
; POWERPC64-AIX-NEXT:    stdu 1, -112(1)
; POWERPC64-AIX-NEXT:    cmpld 3, 1
; POWERPC64-AIX-NEXT:    std 0, 128(1)
; POWERPC64-AIX-NEXT:    ble- 0, L..BB0_2
; POWERPC64-AIX-NEXT:  # %bb.1: # %cond.end
; POWERPC64-AIX-NEXT:    addi 1, 1, 112
; POWERPC64-AIX-NEXT:    ld 0, 16(1)
; POWERPC64-AIX-NEXT:    mtlr 0
; POWERPC64-AIX-NEXT:    blr
; POWERPC64-AIX-NEXT:  L..BB0_2: # %cond.false
; POWERPC64-AIX-NEXT:    bl .abort[PR]
; POWERPC64-AIX-NEXT:    nop



entry:
  %frameaddress = tail call ptr @llvm.frameaddress.p0(i32 0)
  %cmp = icmp ugt ptr %parent_frame_pointer, %frameaddress
  br i1 %cmp, label %cond.end, label %cond.false

cond.false:                                       ; preds = %entry
  tail call void @abort()
  unreachable

cond.end:                                         ; preds = %entry
  ret void
}

declare ptr @llvm.frameaddress.p0(i32 immarg)
declare void @abort()

define noundef i32 @main() {
; POWERPC64-LABEL: main:
; POWERPC64:       # %bb.0: # %entry
; POWERPC64-NEXT:    mflr 0
; POWERPC64-NEXT:    stdu 1, -32(1)
; POWERPC64-NEXT:    std 0, 48(1)
; POWERPC64-NEXT:    .cfi_def_cfa_offset 32
; POWERPC64-NEXT:    .cfi_offset lr, 16
; POWERPC64-NEXT:    mr 3, 1
; POWERPC64-NEXT:    bl foo
; POWERPC64-NEXT:    nop
; POWERPC64-NEXT:    li 3, 0
; POWERPC64-NEXT:    addi 1, 1, 32
; POWERPC64-NEXT:    ld 0, 16(1)
; POWERPC64-NEXT:    mtlr 0
; POWERPC64-NEXT:    blr
;
; POWERPC32-AIX-LABEL: main:
; POWERPC32-AIX:       # %bb.0: # %entry
; POWERPC32-AIX-NEXT:    mflr 0
; POWERPC32-AIX-NEXT:    stwu 1, -64(1)
; POWERPC32-AIX-NEXT:    stw 0, 72(1)
; POWERPC32-AIX-NEXT:    mr 3, 1
; POWERPC32-AIX-NEXT:    bl .foo
; POWERPC32-AIX-NEXT:    nop
; POWERPC32-AIX-NEXT:    li 3, 0
; POWERPC32-AIX-NEXT:    addi 1, 1, 64
; POWERPC32-AIX-NEXT:    lwz 0, 8(1)
; POWERPC32-AIX-NEXT:    mtlr 0
; POWERPC32-AIX-NEXT:    blr
;
; POWERPC64-AIX-LABEL: main:
; POWERPC64-AIX:       # %bb.0: # %entry
; POWERPC64-AIX-NEXT:    mflr 0
; POWERPC64-AIX-NEXT:    stdu 1, -112(1)
; POWERPC64-AIX-NEXT:    std 0, 128(1)
; POWERPC64-AIX-NEXT:    mr 3, 1
; POWERPC64-AIX-NEXT:    bl .foo
; POWERPC64-AIX-NEXT:    nop
; POWERPC64-AIX-NEXT:    li 3, 0
; POWERPC64-AIX-NEXT:    addi 1, 1, 112
; POWERPC64-AIX-NEXT:    ld 0, 16(1)
; POWERPC64-AIX-NEXT:    mtlr 0
; POWERPC64-AIX-NEXT:    blr



entry:
  %frameaddress = tail call ptr @llvm.frameaddress.p0(i32 0)
  tail call void @foo(ptr noundef %frameaddress)
  ret i32 0
}
