# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -run-pass=machine-sink -mtriple=powerpc64-unknown-linux-gnu -o - %s | FileCheck %s

---
name:            sink_crset_crunset
body:             |
  ; CHECK-LABEL: name: sink_crset_crunset
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $r3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %cond:crrc = CMPLWI killed renamable $r3, 0
  ; CHECK-NEXT:   BCC 76, killed %cond, %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %a:crbitrc = CRSET
  ; CHECK-NEXT:   %b:crbitrc = CRUNSET
  ; CHECK-NEXT:   %and:crbitrc = CRAND killed %a, %b
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   BLR implicit $lr, implicit $rm
  bb.0.entry:
    successors: %bb.1(0x40000000), %bb.2(0x40000000)
    liveins: $r3
    %cond:crrc = CMPLWI killed renamable $r3, 0
    %a:crbitrc = CRSET
    %b:crbitrc = CRUNSET
    BCC 76, killed %cond, %bb.2
  bb.1:
    %and:crbitrc = CRAND killed %a, %b
  bb.2:
    BLR implicit $lr, implicit $rm

...
