; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs < %s -mtriple=powerpc64le-unknown-linux-gnu | FileCheck %s
; RUN: llc -verify-machineinstrs < %s -mtriple=powerpc64-unknown-aix | FileCheck %s
; RUN: llc -verify-machineinstrs < %s -mtriple=powerpc-unknown-aix | FileCheck %s

define i1 @subovfi_i32(i32 noundef %a, i32 noundef %b, ptr %c)  {
; CHECK-LABEL: subovfi_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sub 6, 3, 4
; CHECK-NEXT:    cmpwi 1, 4, 0
; CHECK-NEXT:    cmpw 6, 3
; CHECK-NEXT:    li 3, 1
; CHECK-NEXT:    stw 6, 0(5)
; CHECK-NEXT:    creqv 20, 5, 0
; CHECK-NEXT:    isel 3, 0, 3, 20
; CHECK-NEXT:    blr
entry:
  %0 = call { i32, i1 } @llvm.ssub.with.overflow.i32(i32 %a, i32 %b)
  %1 = extractvalue { i32, i1 } %0, 1
  %2 = extractvalue { i32, i1 } %0, 0
  store i32 %2, ptr %c, align 4
  ret i1 %1
}

declare { i32, i1 } @llvm.ssub.with.overflow.i32(i32, i32)

