; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=powerpc64le-unknown-linux-gnu -O2 < %s | FileCheck %s

; Test sub x, (sext (setcc eq z, 0)) - should be optimizable to addze
define i64 @sub_sext_eq_zero(i64 %x, i64 %z) {
; CHECK-LABEL: sub_sext_eq_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addic 4, 4, -1
; CHECK-NEXT:    subfe 4, 4, 4
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    blr
  %cmp = icmp eq i64 %z, 0
  %sext = sext i1 %cmp to i64
  %sub = sub i64 %x, %sext
  ret i64 %sub
}

; Test sub x, (sext (setcc ne z, 0)) - should be optimizable to addze
define i64 @sub_sext_ne_zero(i64 %x, i64 %z) {
; CHECK-LABEL: sub_sext_ne_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subfic 4, 4, 0
; CHECK-NEXT:    subfe 4, 4, 4
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    blr
  %cmp = icmp ne i64 %z, 0
  %sext = sext i1 %cmp to i64
  %sub = sub i64 %x, %sext
  ret i64 %sub
}

; Test sub x, (sext (setcc eq z, C)) with non-zero constant
define i64 @sub_sext_eq_const(i64 %x, i64 %z) {
; CHECK-LABEL: sub_sext_eq_const:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xori 4, 4, 42
; CHECK-NEXT:    addic 4, 4, -1
; CHECK-NEXT:    subfe 4, 4, 4
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    blr
  %cmp = icmp eq i64 %z, 42
  %sext = sext i1 %cmp to i64
  %sub = sub i64 %x, %sext
  ret i64 %sub
}

; Test sub x, (sext (setcc ne z, C)) with non-zero constant
define i64 @sub_sext_ne_const(i64 %x, i64 %z) {
; CHECK-LABEL: sub_sext_ne_const:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xori 4, 4, 42
; CHECK-NEXT:    subfic 4, 4, 0
; CHECK-NEXT:    subfe 4, 4, 4
; CHECK-NEXT:    sub 3, 3, 4
; CHECK-NEXT:    blr
  %cmp = icmp ne i64 %z, 42
  %sext = sext i1 %cmp to i64
  %sub = sub i64 %x, %sext
  ret i64 %sub
}
