; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=powerpc64le-unknown-linux-gnu -O2 < %s | FileCheck %s

; Test sub x, (zext (setcc ult ...)) -> subc + subfe
define i64 @sub_zext_ult(i64 %a, i64 %b, i64 %c) {
; CHECK-LABEL: sub_zext_ult:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subc 4, 4, 5
; CHECK-NEXT:    li 4, 0
; CHECK-NEXT:    subfe 3, 4, 3
; CHECK-NEXT:    blr
  %cmp = icmp ult i64 %b, %c
  %zext = zext i1 %cmp to i64
  %sub = sub i64 %a, %zext
  ret i64 %sub
}

; Test add x, (sext (setcc ult ...)) -> subc + subfe
define i64 @add_sext_ult(i64 %a, i64 %b, i64 %c) {
; CHECK-LABEL: add_sext_ult:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subc 4, 4, 5
; CHECK-NEXT:    li 4, 0
; CHECK-NEXT:    subfe 3, 4, 3
; CHECK-NEXT:    blr
  %cmp = icmp ult i64 %b, %c
  %sext = sext i1 %cmp to i64
  %add = add i64 %a, %sext
  ret i64 %add
}

; Test sub x, (zext (setcc ugt ...)) -> subc + subfe (commuted comparison)
define i64 @sub_zext_ugt(i64 %a, i64 %b, i64 %c) {
; CHECK-LABEL: sub_zext_ugt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subc 4, 5, 4
; CHECK-NEXT:    li 4, 0
; CHECK-NEXT:    subfe 3, 4, 3
; CHECK-NEXT:    blr
  %cmp = icmp ugt i64 %b, %c
  %zext = zext i1 %cmp to i64
  %sub = sub i64 %a, %zext
  ret i64 %sub
}
