; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Check the miscellaneous logical vector operations added in P8
;
; RUN: llc -verify-machineinstrs -mtriple=powerpc64-unknown-linux-gnu -mcpu=pwr8 -mattr=-vsx < %s | FileCheck %s
; Test x eqv y
define <4 x i32> @test_veqv(<4 x i32> %x, <4 x i32> %y) nounwind {
; CHECK-LABEL: test_veqv:
; CHECK:       # %bb.0:
; CHECK-NEXT:    veqv 2, 2, 3
; CHECK-NEXT:    blr
       %tmp = xor <4 x i32> %x, %y
       %ret_val = xor <4 x i32> %tmp, < i32 -1, i32 -1, i32 -1, i32 -1>
       ret <4 x i32> %ret_val
}

; Test x vnand y
define <4 x i32> @test_vnand(<4 x i32> %x, <4 x i32> %y) nounwind {
; CHECK-LABEL: test_vnand:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vnand 2, 2, 3
; CHECK-NEXT:    blr
       %tmp = and <4 x i32> %x, %y
       %ret_val = xor <4 x i32> %tmp, <i32 -1, i32 -1, i32 -1, i32 -1>
       ret <4 x i32> %ret_val
}

; Test x vorc y and variants
define <4 x i32> @test_vorc(<4 x i32> %x, <4 x i32> %y) nounwind {
; CHECK-LABEL: test_vorc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vorc 3, 2, 3
; CHECK-NEXT:    vorc 2, 2, 3
; CHECK-NEXT:    blr
       %tmp1 = xor <4 x i32> %y, <i32 -1, i32 -1, i32 -1, i32 -1>
       %tmp2 = or <4 x i32> %x, %tmp1
       %tmp3 = xor <4 x i32> %tmp2, <i32 -1, i32 -1, i32 -1, i32 -1>
       %tmp4 = or <4 x i32> %tmp3, %x
       ret <4 x i32> %tmp4
}
