; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s

define i32 @bitcast_extract_v4f32(<4 x float> %a) nounwind {
; CHECK-LABEL: bitcast_extract_v4f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vreplvei.w $vr0, $vr0, 3
; CHECK-NEXT:    movfr2gr.s $a0, $fa0
; CHECK-NEXT:    ret
entry:
  %b = extractelement <4 x float> %a, i32 3
  %c = bitcast float %b to i32
  ret i32 %c
}

define i64 @bitcast_extract_v2f64(<2 x double> %a) nounwind {
; CHECK-LABEL: bitcast_extract_v2f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vreplvei.d $vr0, $vr0, 1
; CHECK-NEXT:    movfr2gr.d $a0, $fa0
; CHECK-NEXT:    ret
entry:
  %b = extractelement <2 x double> %a, i32 1
  %c = bitcast double %b to i64
  ret i64 %c
}
