; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx < %s | FileCheck %s --check-prefixes=CHECK,LA32
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s --check-prefixes=CHECK,LA64

define void @extract_16xi8(ptr %src, ptr %dst) nounwind {
; CHECK-LABEL: extract_16xi8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vstelm.b $vr0, $a1, 0, 1
; CHECK-NEXT:    ret
  %v = load volatile <16 x i8>, ptr %src
  %e = extractelement <16 x i8> %v, i32 1
  store i8 %e, ptr %dst
  ret void
}

define void @extract_8xi16(ptr %src, ptr %dst) nounwind {
; CHECK-LABEL: extract_8xi16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vstelm.h $vr0, $a1, 0, 1
; CHECK-NEXT:    ret
  %v = load volatile <8 x i16>, ptr %src
  %e = extractelement <8 x i16> %v, i32 1
  store i16 %e, ptr %dst
  ret void
}

define void @extract_4xi32(ptr %src, ptr %dst) nounwind {
; CHECK-LABEL: extract_4xi32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vstelm.w $vr0, $a1, 0, 1
; CHECK-NEXT:    ret
  %v = load volatile <4 x i32>, ptr %src
  %e = extractelement <4 x i32> %v, i32 1
  store i32 %e, ptr %dst
  ret void
}

define void @extract_2xi64(ptr %src, ptr %dst) nounwind {
; LA32-LABEL: extract_2xi64:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a0, 0
; LA32-NEXT:    vstelm.w $vr0, $a1, 4, 3
; LA32-NEXT:    vstelm.w $vr0, $a1, 0, 2
; LA32-NEXT:    ret
;
; LA64-LABEL: extract_2xi64:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a0, 0
; LA64-NEXT:    vstelm.d $vr0, $a1, 0, 1
; LA64-NEXT:    ret
  %v = load volatile <2 x i64>, ptr %src
  %e = extractelement <2 x i64> %v, i32 1
  store i64 %e, ptr %dst
  ret void
}

define void @extract_4xfloat(ptr %src, ptr %dst) nounwind {
; CHECK-LABEL: extract_4xfloat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vstelm.w $vr0, $a1, 0, 1
; CHECK-NEXT:    ret
  %v = load volatile <4 x float>, ptr %src
  %e = extractelement <4 x float> %v, i32 1
  store float %e, ptr %dst
  ret void
}

define void @extract_2xdouble(ptr %src, ptr %dst) nounwind {
; CHECK-LABEL: extract_2xdouble:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vld $vr0, $a0, 0
; CHECK-NEXT:    vstelm.d $vr0, $a1, 0, 1
; CHECK-NEXT:    ret
  %v = load volatile <2 x double>, ptr %src
  %e = extractelement <2 x double> %v, i32 1
  store double %e, ptr %dst
  ret void
}

define void @extract_16xi8_idx(ptr %src, ptr %dst, i32 %idx) nounwind {
; LA32-LABEL: extract_16xi8_idx:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a0, 0
; LA32-NEXT:    vreplve.b $vr0, $vr0, $a2
; LA32-NEXT:    movfr2gr.s $a0, $fa0
; LA32-NEXT:    srai.w $a0, $a0, 24
; LA32-NEXT:    st.b $a0, $a1, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: extract_16xi8_idx:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a0, 0
; LA64-NEXT:    bstrpick.d $a0, $a2, 31, 0
; LA64-NEXT:    vreplve.b $vr0, $vr0, $a0
; LA64-NEXT:    movfr2gr.s $a0, $fa0
; LA64-NEXT:    srai.w $a0, $a0, 24
; LA64-NEXT:    st.b $a0, $a1, 0
; LA64-NEXT:    ret
  %v = load volatile <16 x i8>, ptr %src
  %e = extractelement <16 x i8> %v, i32 %idx
  store i8 %e, ptr %dst
  ret void
}

define void @extract_8xi16_idx(ptr %src, ptr %dst, i32 %idx) nounwind {
; LA32-LABEL: extract_8xi16_idx:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a0, 0
; LA32-NEXT:    vreplve.h $vr0, $vr0, $a2
; LA32-NEXT:    movfr2gr.s $a0, $fa0
; LA32-NEXT:    srai.w $a0, $a0, 16
; LA32-NEXT:    st.h $a0, $a1, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: extract_8xi16_idx:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a0, 0
; LA64-NEXT:    bstrpick.d $a0, $a2, 31, 0
; LA64-NEXT:    vreplve.h $vr0, $vr0, $a0
; LA64-NEXT:    movfr2gr.s $a0, $fa0
; LA64-NEXT:    srai.w $a0, $a0, 16
; LA64-NEXT:    st.h $a0, $a1, 0
; LA64-NEXT:    ret
  %v = load volatile <8 x i16>, ptr %src
  %e = extractelement <8 x i16> %v, i32 %idx
  store i16 %e, ptr %dst
  ret void
}

define void @extract_4xi32_idx(ptr %src, ptr %dst, i32 %idx) nounwind {
; LA32-LABEL: extract_4xi32_idx:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a0, 0
; LA32-NEXT:    vreplve.w $vr0, $vr0, $a2
; LA32-NEXT:    movfr2gr.s $a0, $fa0
; LA32-NEXT:    st.w $a0, $a1, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: extract_4xi32_idx:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a0, 0
; LA64-NEXT:    bstrpick.d $a0, $a2, 31, 0
; LA64-NEXT:    vreplve.w $vr0, $vr0, $a0
; LA64-NEXT:    movfr2gr.s $a0, $fa0
; LA64-NEXT:    st.w $a0, $a1, 0
; LA64-NEXT:    ret
  %v = load volatile <4 x i32>, ptr %src
  %e = extractelement <4 x i32> %v, i32 %idx
  store i32 %e, ptr %dst
  ret void
}

define void @extract_2xi64_idx(ptr %src, ptr %dst, i32 %idx) nounwind {
; LA32-LABEL: extract_2xi64_idx:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a0, 0
; LA32-NEXT:    add.w $a0, $a2, $a2
; LA32-NEXT:    addi.w $a2, $a0, 1
; LA32-NEXT:    vreplve.w $vr1, $vr0, $a2
; LA32-NEXT:    vreplve.w $vr0, $vr0, $a0
; LA32-NEXT:    movfr2gr.s $a0, $fa1
; LA32-NEXT:    movfr2gr.s $a2, $fa0
; LA32-NEXT:    st.w $a2, $a1, 0
; LA32-NEXT:    st.w $a0, $a1, 4
; LA32-NEXT:    ret
;
; LA64-LABEL: extract_2xi64_idx:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a0, 0
; LA64-NEXT:    bstrpick.d $a0, $a2, 31, 0
; LA64-NEXT:    vreplve.d $vr0, $vr0, $a0
; LA64-NEXT:    movfr2gr.d $a0, $fa0
; LA64-NEXT:    st.d $a0, $a1, 0
; LA64-NEXT:    ret
  %v = load volatile <2 x i64>, ptr %src
  %e = extractelement <2 x i64> %v, i32 %idx
  store i64 %e, ptr %dst
  ret void
}

define void @extract_4xfloat_idx(ptr %src, ptr %dst, i32 %idx) nounwind {
; LA32-LABEL: extract_4xfloat_idx:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a0, 0
; LA32-NEXT:    vreplve.w $vr0, $vr0, $a2
; LA32-NEXT:    fst.s $fa0, $a1, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: extract_4xfloat_idx:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a0, 0
; LA64-NEXT:    bstrpick.d $a0, $a2, 31, 0
; LA64-NEXT:    vreplve.w $vr0, $vr0, $a0
; LA64-NEXT:    fst.s $fa0, $a1, 0
; LA64-NEXT:    ret
  %v = load volatile <4 x float>, ptr %src
  %e = extractelement <4 x float> %v, i32 %idx
  store float %e, ptr %dst
  ret void
}

define void @extract_2xdouble_idx(ptr %src, ptr %dst, i32 %idx) nounwind {
; LA32-LABEL: extract_2xdouble_idx:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a0, 0
; LA32-NEXT:    vreplve.d $vr0, $vr0, $a2
; LA32-NEXT:    fst.d $fa0, $a1, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: extract_2xdouble_idx:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a0, 0
; LA64-NEXT:    bstrpick.d $a0, $a2, 31, 0
; LA64-NEXT:    vreplve.d $vr0, $vr0, $a0
; LA64-NEXT:    fst.d $fa0, $a1, 0
; LA64-NEXT:    ret
  %v = load volatile <2 x double>, ptr %src
  %e = extractelement <2 x double> %v, i32 %idx
  store double %e, ptr %dst
  ret void
}

define void @eliminate_frame_index(<4 x i32> %a) nounwind {
; LA32-LABEL: eliminate_frame_index:
; LA32:       # %bb.0:
; LA32-NEXT:    addi.w $sp, $sp, -1040
; LA32-NEXT:    addi.w $a0, $sp, 524
; LA32-NEXT:    vstelm.w $vr0, $a0, 0, 1
; LA32-NEXT:    addi.w $sp, $sp, 1040
; LA32-NEXT:    ret
;
; LA64-LABEL: eliminate_frame_index:
; LA64:       # %bb.0:
; LA64-NEXT:    addi.d $sp, $sp, -1040
; LA64-NEXT:    addi.d $a0, $sp, 524
; LA64-NEXT:    vstelm.w $vr0, $a0, 0, 1
; LA64-NEXT:    addi.d $sp, $sp, 1040
; LA64-NEXT:    ret
  %1 = alloca [64 x [4 x i32]]
  %2 = getelementptr i8, ptr %1, i64 508
  %b = extractelement <4 x i32> %a, i64 1
  store i32 %b, ptr %2
  ret void
}
