; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx < %s | FileCheck %s --check-prefixes=CHECK,LA32
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s --check-prefixes=CHECK,LA64

define void @fptosi_v4f32_v4i32(ptr %res, ptr %in){
; CHECK-LABEL: fptosi_v4f32_v4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vftintrz.w.s $vr0, $vr0
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
  %v0 = load <4 x float>, ptr %in
  %v1 = fptosi <4 x float> %v0 to <4 x i32>
  store <4 x i32> %v1, ptr %res
  ret void
}

define void @fptosi_v2f64_v2i64(ptr %res, ptr %in){
; CHECK-LABEL: fptosi_v2f64_v2i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vftintrz.l.d $vr0, $vr0
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
  %v0 = load <2 x double>, ptr %in
  %v1 = fptosi <2 x double> %v0 to <2 x i64>
  store <2 x i64> %v1, ptr %res
  ret void
}

define void @fptosi_v2f64_v2i32(ptr %res, ptr %in){
; LA32-LABEL: fptosi_v2f64_v2i32:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a1, 0
; LA32-NEXT:    vftintrz.w.d $vr0, $vr0, $vr0
; LA32-NEXT:    vpickve2gr.w $a1, $vr0, 1
; LA32-NEXT:    st.w $a1, $a0, 4
; LA32-NEXT:    vpickve2gr.w $a1, $vr0, 0
; LA32-NEXT:    st.w $a1, $a0, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: fptosi_v2f64_v2i32:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a1, 0
; LA64-NEXT:    vftintrz.w.d $vr0, $vr0, $vr0
; LA64-NEXT:    vstelm.d $vr0, $a0, 0, 0
; LA64-NEXT:    ret
  %v0 = load <2 x double>, ptr %in
  %v1 = fptosi <2 x double> %v0 to <2 x i32>
  store <2 x i32> %v1, ptr %res
  ret void
}

define void @fptosi_v4f64_v4i32(ptr %res, ptr %in){
; CHECK-LABEL: fptosi_v4f64_v4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vld $vr1, $a1, 16
; CHECK-NEXT:    vftintrz.w.d $vr0, $vr1, $vr0
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
  %v0 = load <4 x double>, ptr %in
  %v1 = fptosi <4 x double> %v0 to <4 x i32>
  store <4 x i32> %v1, ptr %res
  ret void
}
