; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx < %s | FileCheck %s --check-prefixes=CHECK,LA32
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s --check-prefixes=CHECK,LA64

define void @fptoui_v4f32_v4i32(ptr %res, ptr %in){
; CHECK-LABEL: fptoui_v4f32_v4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vftintrz.wu.s $vr0, $vr0
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
  %v0 = load <4 x float>, ptr %in
  %v1 = fptoui <4 x float> %v0 to <4 x i32>
  store <4 x i32> %v1, ptr %res
  ret void
}

define void @fptoui_v2f64_v2i64(ptr %res, ptr %in){
; CHECK-LABEL: fptoui_v2f64_v2i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vftintrz.lu.d $vr0, $vr0
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
  %v0 = load <2 x double>, ptr %in
  %v1 = fptoui <2 x double> %v0 to <2 x i64>
  store <2 x i64> %v1, ptr %res
  ret void
}

define void @fptoui_v2f64_v2i32(ptr %res, ptr %in){
; LA32-LABEL: fptoui_v2f64_v2i32:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a1, 0
; LA32-NEXT:    vreplvei.d $vr1, $vr0, 0
; LA32-NEXT:    movgr2fr.w $fa2, $zero
; LA32-NEXT:    lu12i.w $a1, 269824
; LA32-NEXT:    movgr2frh.w $fa2, $a1
; LA32-NEXT:    fcmp.clt.d $fcc0, $fa1, $fa2
; LA32-NEXT:    fsub.d $fa3, $fa1, $fa2
; LA32-NEXT:    ftintrz.w.d $fa3, $fa3
; LA32-NEXT:    movfr2gr.s $a1, $fa3
; LA32-NEXT:    lu12i.w $a2, -524288
; LA32-NEXT:    xor $a1, $a1, $a2
; LA32-NEXT:    movcf2gr $a3, $fcc0
; LA32-NEXT:    masknez $a1, $a1, $a3
; LA32-NEXT:    ftintrz.w.d $fa1, $fa1
; LA32-NEXT:    movfr2gr.s $a4, $fa1
; LA32-NEXT:    maskeqz $a3, $a4, $a3
; LA32-NEXT:    or $a1, $a3, $a1
; LA32-NEXT:    vreplvei.d $vr0, $vr0, 1
; LA32-NEXT:    fcmp.clt.d $fcc0, $fa0, $fa2
; LA32-NEXT:    fsub.d $fa1, $fa0, $fa2
; LA32-NEXT:    ftintrz.w.d $fa1, $fa1
; LA32-NEXT:    movfr2gr.s $a3, $fa1
; LA32-NEXT:    xor $a2, $a3, $a2
; LA32-NEXT:    movcf2gr $a3, $fcc0
; LA32-NEXT:    masknez $a2, $a2, $a3
; LA32-NEXT:    ftintrz.w.d $fa0, $fa0
; LA32-NEXT:    movfr2gr.s $a4, $fa0
; LA32-NEXT:    maskeqz $a3, $a4, $a3
; LA32-NEXT:    or $a2, $a3, $a2
; LA32-NEXT:    st.w $a2, $a0, 4
; LA32-NEXT:    st.w $a1, $a0, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: fptoui_v2f64_v2i32:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a1, 0
; LA64-NEXT:    vreplvei.d $vr1, $vr0, 0
; LA64-NEXT:    ftintrz.l.d $fa1, $fa1
; LA64-NEXT:    movfr2gr.d $a1, $fa1
; LA64-NEXT:    vinsgr2vr.w $vr1, $a1, 0
; LA64-NEXT:    vreplvei.d $vr0, $vr0, 1
; LA64-NEXT:    ftintrz.l.d $fa0, $fa0
; LA64-NEXT:    movfr2gr.d $a1, $fa0
; LA64-NEXT:    vinsgr2vr.w $vr1, $a1, 1
; LA64-NEXT:    vstelm.d $vr1, $a0, 0, 0
; LA64-NEXT:    ret
  %v0 = load <2 x double>, ptr %in
  %v1 = fptoui <2 x double> %v0 to <2 x i32>
  store <2 x i32> %v1, ptr %res
  ret void
}

define void @fptoui_v4f64_v4i32(ptr %res, ptr %in){
; LA32-LABEL: fptoui_v4f64_v4i32:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a1, 0
; LA32-NEXT:    vld $vr1, $a1, 16
; LA32-NEXT:    vreplvei.d $vr2, $vr0, 1
; LA32-NEXT:    movgr2fr.w $fa3, $zero
; LA32-NEXT:    lu12i.w $a1, 269824
; LA32-NEXT:    movgr2frh.w $fa3, $a1
; LA32-NEXT:    fcmp.clt.d $fcc0, $fa2, $fa3
; LA32-NEXT:    fsub.d $fa4, $fa2, $fa3
; LA32-NEXT:    ftintrz.w.d $fa4, $fa4
; LA32-NEXT:    movfr2gr.s $a1, $fa4
; LA32-NEXT:    lu12i.w $a2, -524288
; LA32-NEXT:    xor $a1, $a1, $a2
; LA32-NEXT:    movcf2gr $a3, $fcc0
; LA32-NEXT:    masknez $a1, $a1, $a3
; LA32-NEXT:    ftintrz.w.d $fa2, $fa2
; LA32-NEXT:    movfr2gr.s $a4, $fa2
; LA32-NEXT:    maskeqz $a3, $a4, $a3
; LA32-NEXT:    or $a1, $a3, $a1
; LA32-NEXT:    vreplvei.d $vr0, $vr0, 0
; LA32-NEXT:    fcmp.clt.d $fcc0, $fa0, $fa3
; LA32-NEXT:    fsub.d $fa2, $fa0, $fa3
; LA32-NEXT:    ftintrz.w.d $fa2, $fa2
; LA32-NEXT:    movfr2gr.s $a3, $fa2
; LA32-NEXT:    xor $a3, $a3, $a2
; LA32-NEXT:    movcf2gr $a4, $fcc0
; LA32-NEXT:    masknez $a3, $a3, $a4
; LA32-NEXT:    ftintrz.w.d $fa0, $fa0
; LA32-NEXT:    movfr2gr.s $a5, $fa0
; LA32-NEXT:    maskeqz $a4, $a5, $a4
; LA32-NEXT:    or $a3, $a4, $a3
; LA32-NEXT:    vinsgr2vr.w $vr0, $a3, 0
; LA32-NEXT:    vinsgr2vr.w $vr0, $a1, 1
; LA32-NEXT:    vreplvei.d $vr2, $vr1, 0
; LA32-NEXT:    fcmp.clt.d $fcc0, $fa2, $fa3
; LA32-NEXT:    fsub.d $fa4, $fa2, $fa3
; LA32-NEXT:    ftintrz.w.d $fa4, $fa4
; LA32-NEXT:    movfr2gr.s $a1, $fa4
; LA32-NEXT:    xor $a1, $a1, $a2
; LA32-NEXT:    movcf2gr $a3, $fcc0
; LA32-NEXT:    masknez $a1, $a1, $a3
; LA32-NEXT:    ftintrz.w.d $fa2, $fa2
; LA32-NEXT:    movfr2gr.s $a4, $fa2
; LA32-NEXT:    maskeqz $a3, $a4, $a3
; LA32-NEXT:    or $a1, $a3, $a1
; LA32-NEXT:    vinsgr2vr.w $vr0, $a1, 2
; LA32-NEXT:    vreplvei.d $vr1, $vr1, 1
; LA32-NEXT:    fcmp.clt.d $fcc0, $fa1, $fa3
; LA32-NEXT:    fsub.d $fa2, $fa1, $fa3
; LA32-NEXT:    ftintrz.w.d $fa2, $fa2
; LA32-NEXT:    movfr2gr.s $a1, $fa2
; LA32-NEXT:    xor $a1, $a1, $a2
; LA32-NEXT:    movcf2gr $a2, $fcc0
; LA32-NEXT:    masknez $a1, $a1, $a2
; LA32-NEXT:    ftintrz.w.d $fa1, $fa1
; LA32-NEXT:    movfr2gr.s $a3, $fa1
; LA32-NEXT:    maskeqz $a2, $a3, $a2
; LA32-NEXT:    or $a1, $a2, $a1
; LA32-NEXT:    vinsgr2vr.w $vr0, $a1, 3
; LA32-NEXT:    vst $vr0, $a0, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: fptoui_v4f64_v4i32:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a1, 0
; LA64-NEXT:    vld $vr1, $a1, 16
; LA64-NEXT:    vreplvei.d $vr2, $vr0, 0
; LA64-NEXT:    ftintrz.l.d $fa2, $fa2
; LA64-NEXT:    movfr2gr.d $a1, $fa2
; LA64-NEXT:    vinsgr2vr.w $vr2, $a1, 0
; LA64-NEXT:    vreplvei.d $vr0, $vr0, 1
; LA64-NEXT:    ftintrz.l.d $fa0, $fa0
; LA64-NEXT:    movfr2gr.d $a1, $fa0
; LA64-NEXT:    vinsgr2vr.w $vr2, $a1, 1
; LA64-NEXT:    vreplvei.d $vr0, $vr1, 0
; LA64-NEXT:    ftintrz.l.d $fa0, $fa0
; LA64-NEXT:    movfr2gr.d $a1, $fa0
; LA64-NEXT:    vinsgr2vr.w $vr2, $a1, 2
; LA64-NEXT:    vreplvei.d $vr0, $vr1, 1
; LA64-NEXT:    ftintrz.l.d $fa0, $fa0
; LA64-NEXT:    movfr2gr.d $a1, $fa0
; LA64-NEXT:    vinsgr2vr.w $vr2, $a1, 3
; LA64-NEXT:    vst $vr2, $a0, 0
; LA64-NEXT:    ret
  %v0 = load <4 x double>, ptr %in
  %v1 = fptoui <4 x double> %v0 to <4 x i32>
  store <4 x i32> %v1, ptr %res
  ret void
}
