; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s

define void @nor_v16i8(ptr %res, ptr %a0, ptr %a1) nounwind {
; CHECK-LABEL: nor_v16i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vld $vr1, $a2, 0
; CHECK-NEXT:    vnor.v $vr0, $vr0, $vr1
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <16 x i8>, ptr %a0
  %v1 = load <16 x i8>, ptr %a1
  %v2 = or <16 x i8> %v0, %v1
  %v3 = xor <16 x i8> %v2, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  store <16 x i8> %v3, ptr %res
  ret void
}

define void @nor_v8i16(ptr %res, ptr %a0, ptr %a1) nounwind {
; CHECK-LABEL: nor_v8i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vld $vr1, $a2, 0
; CHECK-NEXT:    vnor.v $vr0, $vr0, $vr1
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <8 x i16>, ptr %a0
  %v1 = load <8 x i16>, ptr %a1
  %v2 = or <8 x i16> %v0, %v1
  %v3 = xor <8 x i16> %v2, <i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1>
  store <8 x i16> %v3, ptr %res
  ret void
}

define void @nor_v4i32(ptr %res, ptr %a0, ptr %a1) nounwind {
; CHECK-LABEL: nor_v4i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vld $vr1, $a2, 0
; CHECK-NEXT:    vnor.v $vr0, $vr0, $vr1
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <4 x i32>, ptr %a0
  %v1 = load <4 x i32>, ptr %a1
  %v2 = or <4 x i32> %v0, %v1
  %v3 = xor <4 x i32> %v2, <i32 -1, i32 -1, i32 -1, i32 -1>
  store <4 x i32> %v3, ptr %res
  ret void
}

define void @nor_v2i64(ptr %res, ptr %a0, ptr %a1) nounwind {
; CHECK-LABEL: nor_v2i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vld $vr1, $a2, 0
; CHECK-NEXT:    vnor.v $vr0, $vr0, $vr1
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <2 x i64>, ptr %a0
  %v1 = load <2 x i64>, ptr %a1
  %v2 = or <2 x i64> %v0, %v1
  %v3 = xor <2 x i64> %v2, <i64 -1, i64 -1>
  store <2 x i64> %v3, ptr %res
  ret void
}

define void @nor_u_v16i8(ptr %res, ptr %a0) nounwind {
; CHECK-LABEL: nor_u_v16i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vnori.b $vr0, $vr0, 31
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <16 x i8>, ptr %a0
  %v1 = or <16 x i8> %v0, <i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31>
  %v2 = xor <16 x i8> %v1, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  store <16 x i8> %v2, ptr %res
  ret void
}

define void @nor_u_v8i16(ptr %res, ptr %a0) nounwind {
; CHECK-LABEL: nor_u_v8i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vrepli.h $vr1, 31
; CHECK-NEXT:    vnor.v $vr0, $vr0, $vr1
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <8 x i16>, ptr %a0
  %v1 = or <8 x i16> %v0, <i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31>
  %v2 = xor <8 x i16> %v1, <i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1>
  store <8 x i16> %v2, ptr %res
  ret void
}

define void @nor_u_v4i32(ptr %res, ptr %a0) nounwind {
; CHECK-LABEL: nor_u_v4i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vrepli.w $vr1, 31
; CHECK-NEXT:    vnor.v $vr0, $vr0, $vr1
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <4 x i32>, ptr %a0
  %v1 = or <4 x i32> %v0, <i32 31, i32 31, i32 31, i32 31>
  %v2 = xor <4 x i32> %v1, <i32 -1, i32 -1, i32 -1, i32 -1>
  store <4 x i32> %v2, ptr %res
  ret void
}

define void @nor_u_v2i64(ptr %res, ptr %a0) nounwind {
; CHECK-LABEL: nor_u_v2i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vrepli.d $vr1, 31
; CHECK-NEXT:    vnor.v $vr0, $vr0, $vr1
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <2 x i64>, ptr %a0
  %v1 = or <2 x i64> %v0, <i64 31, i64 31>
  %v2 = xor <2 x i64> %v1, <i64 -1, i64 -1>
  store <2 x i64> %v2, ptr %res
  ret void
}

define <8 x i16> @nor_u_v8i16_1(<8 x i16> %a) nounwind {
; CHECK-LABEL: nor_u_v8i16_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vnori.b $vr0, $vr0, 1
; CHECK-NEXT:    ret
entry:
  %0 = or <8 x i16> %a, splat (i16 257)
  %1 = xor <8 x i16> %0, splat (i16 65535)
  ret <8 x i16> %1
}

define <4 x i32> @nor_u_v4i32_1(<4 x i32> %a) nounwind {
; CHECK-LABEL: nor_u_v4i32_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vnori.b $vr0, $vr0, 1
; CHECK-NEXT:    ret
entry:
  %0 = or <4 x i32> %a, splat (i32 16843009)
  %1 = xor <4 x i32> %0, splat (i32 4294967295)
  ret <4 x i32> %1
}

define <2 x i64> @nor_u_v2i64_1(<2 x i64> %a) nounwind {
; CHECK-LABEL: nor_u_v2i64_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vnori.b $vr0, $vr0, 1
; CHECK-NEXT:    ret
entry:
  %0 = or <2 x i64> %a, splat (i64 72340172838076673)
  %1 = xor <2 x i64> %0, splat (i64 18446744073709551615)
  ret <2 x i64> %1
}
