; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lsx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lsx < %s | FileCheck %s

define void @sitofp_v4i32_v4f32(ptr %res, ptr %in){
; CHECK-LABEL: sitofp_v4i32_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vffint.s.w $vr0, $vr0
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
  %v0 = load <4 x i32>, ptr %in
  %v1 = sitofp <4 x i32> %v0 to <4 x float>
  store <4 x float> %v1, ptr %res
  ret void
}

define void @sitofp_v2i64_v2f64(ptr %res, ptr %in){
; CHECK-LABEL: sitofp_v2i64_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vffint.d.l $vr0, $vr0
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
  %v0 = load <2 x i64>, ptr %in
  %v1 = sitofp <2 x i64> %v0 to <2 x double>
  store <2 x double> %v1, ptr %res
  ret void
}

define <4 x double> @sitofp_v4i64_v4f64(<4 x i64> %a) {
; CHECK-LABEL: sitofp_v4i64_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vffint.d.l $vr0, $vr0
; CHECK-NEXT:    vffint.d.l $vr1, $vr1
; CHECK-NEXT:    ret
  %cvt = sitofp <4 x i64> %a to <4 x double>
  ret <4 x double> %cvt
}

define <4 x double> @sitofp_v4i32_v4f64(<4 x i32> %a) {
; CHECK-LABEL: sitofp_v4i32_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpickve2gr.w $a0, $vr0, 1
; CHECK-NEXT:    movgr2fr.w $fa1, $a0
; CHECK-NEXT:    ffint.d.w $fa1, $fa1
; CHECK-NEXT:    vpickve2gr.w $a0, $vr0, 0
; CHECK-NEXT:    movgr2fr.w $fa2, $a0
; CHECK-NEXT:    ffint.d.w $fa2, $fa2
; CHECK-NEXT:    vextrins.d $vr2, $vr1, 16
; CHECK-NEXT:    vpickve2gr.w $a0, $vr0, 3
; CHECK-NEXT:    movgr2fr.w $fa1, $a0
; CHECK-NEXT:    ffint.d.w $fa3, $fa1
; CHECK-NEXT:    vpickve2gr.w $a0, $vr0, 2
; CHECK-NEXT:    movgr2fr.w $fa0, $a0
; CHECK-NEXT:    ffint.d.w $fa1, $fa0
; CHECK-NEXT:    vextrins.d $vr1, $vr3, 16
; CHECK-NEXT:    vori.b $vr0, $vr2, 0
; CHECK-NEXT:    ret
  %cvt = sitofp <4 x i32> %a to <4 x double>
  ret <4 x double> %cvt
}

define <2 x float> @sitofp_v2i32_v2f32(<2 x i32> %a) {
; CHECK-LABEL: sitofp_v2i32_v2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vffint.s.w $vr0, $vr0
; CHECK-NEXT:    ret
  %cvt = sitofp <2 x i32> %a to <2 x float>
  ret <2 x float> %cvt
}

define <2 x double> @sitofp_v4i32_v2f64(<4 x i32> %a) {
; CHECK-LABEL: sitofp_v4i32_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpickve2gr.w $a0, $vr0, 1
; CHECK-NEXT:    movgr2fr.w $fa1, $a0
; CHECK-NEXT:    ffint.d.w $fa1, $fa1
; CHECK-NEXT:    vpickve2gr.w $a0, $vr0, 0
; CHECK-NEXT:    movgr2fr.w $fa0, $a0
; CHECK-NEXT:    ffint.d.w $fa0, $fa0
; CHECK-NEXT:    vextrins.d $vr0, $vr1, 16
; CHECK-NEXT:    ret
  %cvt = sitofp <4 x i32> %a to <4 x double>
  %shuf = shufflevector <4 x double> %cvt, <4 x double> poison, <2 x i32> <i32 0, i32 1>
  ret <2 x double> %shuf
}

define <2 x double> @sitofp_v2i16_v2f64(<8 x i16> %a) {
; CHECK-LABEL: sitofp_v2i16_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpickve2gr.h $a0, $vr0, 1
; CHECK-NEXT:    ext.w.h $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa1, $a0
; CHECK-NEXT:    ffint.d.w $fa1, $fa1
; CHECK-NEXT:    vpickve2gr.h $a0, $vr0, 0
; CHECK-NEXT:    ext.w.h $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa0, $a0
; CHECK-NEXT:    ffint.d.w $fa0, $fa0
; CHECK-NEXT:    vextrins.d $vr0, $vr1, 16
; CHECK-NEXT:    ret
  %shuf = shufflevector <8 x i16> %a, <8 x i16> poison, <2 x i32> <i32 0, i32 1>
  %cvt = sitofp <2 x i16> %shuf to <2 x double>
  ret <2 x double> %cvt
}

define <2 x double> @sitofp_v8i16_v2f64(<8 x i16> %a) {
; CHECK-LABEL: sitofp_v8i16_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpickve2gr.h $a0, $vr0, 1
; CHECK-NEXT:    ext.w.h $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa1, $a0
; CHECK-NEXT:    ffint.d.w $fa1, $fa1
; CHECK-NEXT:    vpickve2gr.h $a0, $vr0, 0
; CHECK-NEXT:    ext.w.h $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa0, $a0
; CHECK-NEXT:    ffint.d.w $fa0, $fa0
; CHECK-NEXT:    vextrins.d $vr0, $vr1, 16
; CHECK-NEXT:    ret
  %cvt = sitofp <8 x i16> %a to <8 x double>
  %shuf = shufflevector <8 x double> %cvt, <8 x double> poison, <2 x i32> <i32 0, i32 1>
  ret <2 x double> %shuf
}

define <2 x double> @sitofp_v2i8_v2f64(<16 x i8> %a) {
; CHECK-LABEL: sitofp_v2i8_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpickve2gr.b $a0, $vr0, 1
; CHECK-NEXT:    ext.w.b $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa1, $a0
; CHECK-NEXT:    ffint.d.w $fa1, $fa1
; CHECK-NEXT:    vpickve2gr.b $a0, $vr0, 0
; CHECK-NEXT:    ext.w.b $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa0, $a0
; CHECK-NEXT:    ffint.d.w $fa0, $fa0
; CHECK-NEXT:    vextrins.d $vr0, $vr1, 16
; CHECK-NEXT:    ret
  %shuf = shufflevector <16 x i8> %a, <16 x i8> poison, <2 x i32> <i32 0, i32 1>
  %cvt = sitofp <2 x i8> %shuf to <2 x double>
  ret <2 x double> %cvt
}

define <2 x double> @sitofp_v16i8_v2f64(<16 x i8> %a) {
; CHECK-LABEL: sitofp_v16i8_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpickve2gr.b $a0, $vr0, 1
; CHECK-NEXT:    ext.w.b $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa1, $a0
; CHECK-NEXT:    ffint.d.w $fa1, $fa1
; CHECK-NEXT:    vpickve2gr.b $a0, $vr0, 0
; CHECK-NEXT:    ext.w.b $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa0, $a0
; CHECK-NEXT:    ffint.d.w $fa0, $fa0
; CHECK-NEXT:    vextrins.d $vr0, $vr1, 16
; CHECK-NEXT:    ret
  %cvt = sitofp <16 x i8> %a to <16 x double>
  %shuf = shufflevector <16 x double> %cvt, <16 x double> poison, <2 x i32> <i32 0, i32 1>
  ret <2 x double> %shuf
}

define <4 x double> @sitofp_v4i16_v4f64(<8 x i16> %a) {
; CHECK-LABEL: sitofp_v4i16_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpickve2gr.h $a0, $vr0, 1
; CHECK-NEXT:    ext.w.h $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa1, $a0
; CHECK-NEXT:    ffint.d.w $fa1, $fa1
; CHECK-NEXT:    vpickve2gr.h $a0, $vr0, 0
; CHECK-NEXT:    ext.w.h $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa2, $a0
; CHECK-NEXT:    ffint.d.w $fa2, $fa2
; CHECK-NEXT:    vextrins.d $vr2, $vr1, 16
; CHECK-NEXT:    vpickve2gr.h $a0, $vr0, 3
; CHECK-NEXT:    ext.w.h $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa1, $a0
; CHECK-NEXT:    ffint.d.w $fa3, $fa1
; CHECK-NEXT:    vpickve2gr.h $a0, $vr0, 2
; CHECK-NEXT:    ext.w.h $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa0, $a0
; CHECK-NEXT:    ffint.d.w $fa1, $fa0
; CHECK-NEXT:    vextrins.d $vr1, $vr3, 16
; CHECK-NEXT:    vori.b $vr0, $vr2, 0
; CHECK-NEXT:    ret
  %shuf = shufflevector <8 x i16> %a, <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %cvt = sitofp <4 x i16> %shuf to <4 x double>
  ret <4 x double> %cvt
}

define <4 x double> @sitofp_v8i16_v4f64(<8 x i16> %a) {
; CHECK-LABEL: sitofp_v8i16_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpickve2gr.h $a0, $vr0, 1
; CHECK-NEXT:    ext.w.h $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa1, $a0
; CHECK-NEXT:    ffint.d.w $fa1, $fa1
; CHECK-NEXT:    vpickve2gr.h $a0, $vr0, 0
; CHECK-NEXT:    ext.w.h $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa2, $a0
; CHECK-NEXT:    ffint.d.w $fa2, $fa2
; CHECK-NEXT:    vextrins.d $vr2, $vr1, 16
; CHECK-NEXT:    vpickve2gr.h $a0, $vr0, 3
; CHECK-NEXT:    ext.w.h $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa1, $a0
; CHECK-NEXT:    ffint.d.w $fa3, $fa1
; CHECK-NEXT:    vpickve2gr.h $a0, $vr0, 2
; CHECK-NEXT:    ext.w.h $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa0, $a0
; CHECK-NEXT:    ffint.d.w $fa1, $fa0
; CHECK-NEXT:    vextrins.d $vr1, $vr3, 16
; CHECK-NEXT:    vori.b $vr0, $vr2, 0
; CHECK-NEXT:    ret
  %cvt = sitofp <8 x i16> %a to <8 x double>
  %shuf = shufflevector <8 x double> %cvt, <8 x double> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x double> %shuf
}

define <4 x double> @sitofp_v4i8_v4f64(<16 x i8> %a) {
; CHECK-LABEL: sitofp_v4i8_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpickve2gr.b $a0, $vr0, 1
; CHECK-NEXT:    ext.w.b $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa1, $a0
; CHECK-NEXT:    ffint.d.w $fa1, $fa1
; CHECK-NEXT:    vpickve2gr.b $a0, $vr0, 0
; CHECK-NEXT:    ext.w.b $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa2, $a0
; CHECK-NEXT:    ffint.d.w $fa2, $fa2
; CHECK-NEXT:    vextrins.d $vr2, $vr1, 16
; CHECK-NEXT:    vpickve2gr.b $a0, $vr0, 3
; CHECK-NEXT:    ext.w.b $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa1, $a0
; CHECK-NEXT:    ffint.d.w $fa3, $fa1
; CHECK-NEXT:    vpickve2gr.b $a0, $vr0, 2
; CHECK-NEXT:    ext.w.b $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa0, $a0
; CHECK-NEXT:    ffint.d.w $fa1, $fa0
; CHECK-NEXT:    vextrins.d $vr1, $vr3, 16
; CHECK-NEXT:    vori.b $vr0, $vr2, 0
; CHECK-NEXT:    ret
  %shuf = shufflevector <16 x i8> %a, <16 x i8> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %cvt = sitofp <4 x i8> %shuf to <4 x double>
  ret <4 x double> %cvt
}

define <4 x double> @sitofp_v16i8_v4f64(<16 x i8> %a) {
; CHECK-LABEL: sitofp_v16i8_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpickve2gr.b $a0, $vr0, 1
; CHECK-NEXT:    ext.w.b $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa1, $a0
; CHECK-NEXT:    ffint.d.w $fa1, $fa1
; CHECK-NEXT:    vpickve2gr.b $a0, $vr0, 0
; CHECK-NEXT:    ext.w.b $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa2, $a0
; CHECK-NEXT:    ffint.d.w $fa2, $fa2
; CHECK-NEXT:    vextrins.d $vr2, $vr1, 16
; CHECK-NEXT:    vpickve2gr.b $a0, $vr0, 3
; CHECK-NEXT:    ext.w.b $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa1, $a0
; CHECK-NEXT:    ffint.d.w $fa3, $fa1
; CHECK-NEXT:    vpickve2gr.b $a0, $vr0, 2
; CHECK-NEXT:    ext.w.b $a0, $a0
; CHECK-NEXT:    movgr2fr.w $fa0, $a0
; CHECK-NEXT:    ffint.d.w $fa1, $fa0
; CHECK-NEXT:    vextrins.d $vr1, $vr3, 16
; CHECK-NEXT:    vori.b $vr0, $vr2, 0
; CHECK-NEXT:    ret
  %cvt = sitofp <16 x i8> %a to <16 x double>
  %shuf = shufflevector <16 x double> %cvt, <16 x double> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x double> %shuf
}
