; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=loop-fusion < %s | FileCheck %s

; DA used to classify the store/load dependence as non-linear even though the
; subscripts are identical addrecs in SameSD loops. This shape intentionally
; mirrors a loop nest where the first loop has another pointer recurrence and a
; readonly call; simply adding nsw to the induction increments is not enough for
; trunk to fuse it.
define i64 @fuse_identical_samesd_addrecs(ptr %a, ptr %x, ptr %y, i64 %stride, i64 %n) {
; CHECK-LABEL: define i64 @fuse_identical_samesd_addrecs(
; CHECK-SAME: ptr [[A:%.*]], ptr [[X:%.*]], ptr [[Y:%.*]], i64 [[STRIDE:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CMP0:%.*]] = icmp eq i64 [[N]], 0
; CHECK-NEXT:    br i1 [[CMP0]], label %[[EXIT:.*]], label %[[FOR_1_PREHEADER:.*]]
; CHECK:       [[FOR_1_PREHEADER]]:
; CHECK-NEXT:    br label %[[FOR_1:.*]]
; CHECK:       [[FOR_1]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], %[[FOR_1]] ], [ 0, %[[FOR_1_PREHEADER]] ]
; CHECK-NEXT:    [[P:%.*]] = phi ptr [ [[P_NEXT:%.*]], %[[FOR_1]] ], [ [[Y]], %[[FOR_1_PREHEADER]] ]
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ [[J_NEXT:%.*]], %[[FOR_1]] ], [ 0, %[[FOR_1_PREHEADER]] ]
; CHECK-NEXT:    [[BEST:%.*]] = phi float [ [[BEST_NEXT:%.*]], %[[FOR_1]] ], [ +inf, %[[FOR_1_PREHEADER]] ]
; CHECK-NEXT:    [[IDX:%.*]] = phi i64 [ [[IDX_NEXT:%.*]], %[[FOR_1]] ], [ 0, %[[FOR_1_PREHEADER]] ]
; CHECK-NEXT:    [[CALL:%.*]] = tail call float @readonly_call(ptr [[X]], ptr [[P]], i64 [[STRIDE]])
; CHECK-NEXT:    [[GEP_A_1:%.*]] = getelementptr inbounds nuw float, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    store float [[CALL]], ptr [[GEP_A_1]], align 4
; CHECK-NEXT:    [[P_NEXT]] = getelementptr inbounds nuw float, ptr [[P]], i64 [[STRIDE]]
; CHECK-NEXT:    [[I_NEXT]] = add nsw i64 [[I]], 1
; CHECK-NEXT:    [[DONE_1:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    [[GEP_A_2:%.*]] = getelementptr inbounds nuw float, ptr [[A]], i64 [[J]]
; CHECK-NEXT:    [[V:%.*]] = load float, ptr [[GEP_A_2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[V]], [[BEST]]
; CHECK-NEXT:    [[IDX_NEXT]] = select i1 [[CMP]], i64 [[J]], i64 [[IDX]]
; CHECK-NEXT:    [[BEST_NEXT]] = select i1 [[CMP]], float [[V]], float [[BEST]]
; CHECK-NEXT:    [[J_NEXT]] = add nsw i64 [[J]], 1
; CHECK-NEXT:    [[DONE_2:%.*]] = icmp eq i64 [[J_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[DONE_2]], label %[[EXIT_LOOPEXIT:.*]], label %[[FOR_1]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IDX_NEXT]], %[[EXIT_LOOPEXIT]] ]
; CHECK-NEXT:    ret i64 [[RES]]
;
entry:
  %cmp0 = icmp eq i64 %n, 0
  br i1 %cmp0, label %exit, label %for.1

for.1:
  %i = phi i64 [ 0, %entry ], [ %i.next, %for.1 ]
  %p = phi ptr [ %y, %entry ], [ %p.next, %for.1 ]
  %call = tail call float @readonly_call(ptr %x, ptr %p, i64 %stride)
  %gep.a.1 = getelementptr inbounds nuw float, ptr %a, i64 %i
  store float %call, ptr %gep.a.1, align 4
  %p.next = getelementptr inbounds nuw float, ptr %p, i64 %stride
  %i.next = add nsw i64 %i, 1
  %done.1 = icmp eq i64 %i.next, %n
  br i1 %done.1, label %for.2, label %for.1

for.2:
  %j = phi i64 [ 0, %for.1 ], [ %j.next, %for.2 ]
  %best = phi float [ 0x7FF0000000000000, %for.1 ], [ %best.next, %for.2 ]
  %idx = phi i64 [ 0, %for.1 ], [ %idx.next, %for.2 ]
  %gep.a.2 = getelementptr inbounds nuw float, ptr %a, i64 %j
  %v = load float, ptr %gep.a.2, align 4
  %cmp = fcmp olt float %v, %best
  %idx.next = select i1 %cmp, i64 %j, i64 %idx
  %best.next = select i1 %cmp, float %v, float %best
  %j.next = add nsw i64 %j, 1
  %done.2 = icmp eq i64 %j.next, %n
  br i1 %done.2, label %exit, label %for.2

exit:
  %res = phi i64 [ 0, %entry ], [ %idx.next, %for.2 ]
  ret i64 %res
}

declare float @readonly_call(ptr, ptr, i64) nounwind readonly
