; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=loop-fusion -loop-fusion-peel-max-count=8 < %s | FileCheck %s

define void @lcssa_peel_repro() {
; CHECK-LABEL: define void @lcssa_peel_repro() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER_HEADER:.*]]
; CHECK:       [[OUTER_HEADER_LOOPEXIT:.*]]:
; CHECK-NEXT:    br label %[[OUTER_HEADER]]
; CHECK:       [[OUTER_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[XOR:%.*]], %[[OUTER_HEADER_LOOPEXIT]] ]
; CHECK-NEXT:    br label %[[INNER1_PEEL_BEGIN:.*]]
; CHECK:       [[INNER1_PEEL_BEGIN]]:
; CHECK-NEXT:    br label %[[INNER1_PEEL:.*]]
; CHECK:       [[INNER1_PEEL]]:
; CHECK-NEXT:    [[XOR_PEEL:%.*]] = xor i64 0, 0
; CHECK-NEXT:    [[CMP_PEEL:%.*]] = icmp ult i64 0, 1
; CHECK-NEXT:    br label %[[INNER1_PEEL_NEXT:.*]]
; CHECK:       [[INNER1_PEEL_NEXT]]:
; CHECK-NEXT:    br label %[[INNER1_PEEL_NEXT1:.*]]
; CHECK:       [[INNER1_PEEL_NEXT1]]:
; CHECK-NEXT:    br label %[[OUTER_HEADER_PEEL_NEWPH:.*]]
; CHECK:       [[OUTER_HEADER_PEEL_NEWPH]]:
; CHECK-NEXT:    br label %[[INNER1:.*]]
; CHECK:       [[INNER1]]:
; CHECK-NEXT:    [[XOR]] = xor i64 0, 0
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 1, 1
; CHECK-NEXT:    br i1 false, label %[[INNER1]], label %[[OUTER_HEADER_LOOPEXIT]]
;
entry:
  br label %outer.header

outer.header:                                     ; preds = %inner2, %entry
  %iv = phi i64 [ 0, %entry ], [ %xor, %inner2 ]
  br label %inner1

inner1:                                           ; preds = %inner1, %outer.header
  %i = phi i64 [ 0, %outer.header ], [ 1, %inner1 ]
  %xor = xor i64 0, 0
  %cmp = icmp ult i64 %i, 1
  br i1 %cmp, label %inner1, label %inner2

inner2:                                           ; preds = %inner2, %inner1
  br i1 false, label %inner2, label %outer.header
}
