; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=loop-fusion -S < %s 2>&1 | FileCheck %s

; The non-loop block of loop for.cond.cleanup13 is not the immediate successor
; of its exit block, then it should not be eligible for fusion.

define void @non_immediate_exit() {
; CHECK-LABEL: define void @non_immediate_exit() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 false, label %[[IF_ELSE_1:.*]], label %[[FOR_COND_CLEANUP13_PREHEADER:.*]]
; CHECK:       [[FOR_COND_CLEANUP13_PREHEADER]]:
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP13:.*]]
; CHECK:       [[FOR_COND_CLEANUP13]]:
; CHECK-NEXT:    br i1 true, label %[[FOR_INC21:.*]], label %[[FOR_COND_CLEANUP13]]
; CHECK:       [[FOR_INC21]]:
; CHECK-NEXT:    br label %[[IF_THEN_1:.*]]
; CHECK:       [[IF_THEN_1]]:
; CHECK-NEXT:    br label %[[IF_ELSE_1]]
; CHECK:       [[IF_ELSE_1]]:
; CHECK-NEXT:    br i1 false, label %[[IF_ELSE_2:.*]], label %[[FOR_COND_CLEANUP13_1_PREHEADER:.*]]
; CHECK:       [[FOR_COND_CLEANUP13_1_PREHEADER]]:
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP13_1:.*]]
; CHECK:       [[FOR_COND_CLEANUP13_1]]:
; CHECK-NEXT:    br i1 true, label %[[IF_ELSE_2_LOOPEXIT:.*]], label %[[FOR_COND_CLEANUP13_1]]
; CHECK:       [[IF_ELSE_2_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[IF_ELSE_2]]
; CHECK:       [[IF_ELSE_2]]:
; CHECK-NEXT:    ret void
;
entry:
  br i1 false, label %if.else.1, label %for.cond.cleanup13

for.cond.cleanup13:                               ; preds = %for.cond.cleanup13, %entry
  br i1 true, label %for.inc21, label %for.cond.cleanup13

for.inc21:                                        ; preds = %for.cond.cleanup13
  br label %if.then.1

if.then.1:                                        ; preds = %for.inc21
  br label %if.else.1

if.else.1:                                        ; preds = %if.then.1, %entry
  br i1 false, label %if.else.2, label %for.cond.cleanup13.1

for.cond.cleanup13.1:                             ; preds = %for.cond.cleanup13.1, %if.else.1
  br i1 true, label %if.else.2, label %for.cond.cleanup13.1

if.else.2:                                        ; preds = %for.cond.cleanup13.1, %if.else.1
  ret void
}
