; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=loop-fusion < %s 2>&1 | FileCheck %s

%struct.widget = type { [3 x %struct.baz] }
%struct.baz = type { [3 x double] }

define void @snork() {
; CHECK-LABEL: define void @snork() {
; CHECK-NEXT:  [[BB:.*:]]
; CHECK-NEXT:    br i1 false, label %[[BB4:.*]], label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[LOAD:%.*]] = load ptr, ptr null, align 8
; CHECK-NEXT:    br label %[[BB2:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ 0, %[[BB1]] ], [ [[ADD:%.*]], %[[BB2]] ]
; CHECK-NEXT:    [[PHI6:%.*]] = phi i64 [ [[ADD8:%.*]], %[[BB2]] ], [ 0, %[[BB1]] ]
; CHECK-NEXT:    [[GETELEMENTPTR:%.*]] = getelementptr [[STRUCT_WIDGET:%.*]], ptr [[LOAD]], i64 [[PHI]]
; CHECK-NEXT:    store double 0.000000e+00, ptr [[GETELEMENTPTR]], align 8
; CHECK-NEXT:    [[ADD]] = add i64 [[PHI]], 1
; CHECK-NEXT:    [[ICMP:%.*]] = icmp eq i64 [[ADD]], 0
; CHECK-NEXT:    [[LOAD7:%.*]] = load double, ptr null, align 8
; CHECK-NEXT:    [[ADD8]] = add i64 [[PHI6]], 1
; CHECK-NEXT:    [[ICMP9:%.*]] = icmp eq i64 [[ADD8]], 0
; CHECK-NEXT:    br i1 [[ICMP9]], label %[[BB4_LOOPEXIT:.*]], label %[[BB2]]
; CHECK:       [[BB4_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[BB4]]
; CHECK:       [[BB4]]:
; CHECK-NEXT:    ret void
;
bb:
  br i1 false, label %bb3, label %bb1

bb1:                                              ; preds = %bb
  %load = load ptr, ptr null, align 8
  br label %bb2

bb2:                                              ; preds = %bb2, %bb1
  %phi = phi i64 [ 0, %bb1 ], [ %add, %bb2 ]
  %getelementptr = getelementptr %struct.widget, ptr %load, i64 %phi
  store double 0.000000e+00, ptr %getelementptr, align 8
  %add = add i64 %phi, 1
  %icmp = icmp eq i64 %add, 0
  br i1 %icmp, label %bb3, label %bb2

bb3:                                              ; preds = %bb2, %bb
  br i1 false, label %bb4, label %bb5

bb4:                                              ; preds = %bb5, %bb3
  ret void

bb5:                                              ; preds = %bb5, %bb3
  %phi6 = phi i64 [ %add8, %bb5 ], [ 0, %bb3 ]
  %load7 = load double, ptr null, align 8
  %add8 = add i64 %phi6, 1
  %icmp9 = icmp eq i64 %add8, 0
  br i1 %icmp9, label %bb4, label %bb5
}
