; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=next32 < %s | FileCheck %s

declare i128 @llvm.cttz.i128(i128, i1)
declare i64 @llvm.cttz.i64(i64, i1)
declare i32 @llvm.cttz.i32(i32, i1)
declare i16 @llvm.cttz.i16(i16, i1)
declare i8 @llvm.cttz.i8(i8, i1)

define i8 @ctz8(i8 %value) {
; CHECK-LABEL: ctz8
; CHECK:    ctz r1
  %result = call i8 @llvm.cttz.i8(i8 %value, i1 false)
  ret i8 %result
}

define i16 @ctz16(i16 %value) {
; CHECK-LABEL: ctz16
; CHECK:    ctz r1
  %result = call i16 @llvm.cttz.i16(i16 %value, i1 false)
  ret i16 %result
}

define i32 @ctz32(i32 %value) {
; CHECK-LABEL: ctz32
; CHECK:    ctz r1
  %result = call i32 @llvm.cttz.i32(i32 %value, i1 false)
  ret i32 %result
}

define i64 @ctz64(i64 %value) {
; CHECK-LABEL: ctz64
; CHECK:    ctz r2
; CHECK:    ctz r1
  %result = call i64 @llvm.cttz.i64(i64 %value, i1 false)
  ret i64 %result
}

define i128 @ctz128(i128 %value) {
; CHECK-LABEL: ctz128
; CHECK:    ctz r6
; CHECK:    ctz r8
; CHECK:    ctz r4
; CHECK:    ctz r3
  %result = call i128 @llvm.cttz.i128(i128 %value, i1 false)
  ret i128 %result
}
