; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=next32 -mcpu=next32gen2 < %s | FileCheck %s

define void @func() {
; CHECK-LABEL: func:
; CHECK:       LBB0_0:
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    feeder.32 tid
; CHECK-NEXT:    feeder.32 ret_fid
; CHECK-NEXT:    movl r1, 0x0
; CHECK-NEXT:    movl call_ret_fid, .Ltmp0
; CHECK-NEXT:    callptr r1, r1
; CHECK-NEXT:    writer.32 r1, tid
; CHECK-NEXT:    writer.32 r1, call_ret_fid
; CHECK-NEXT:    movl call_ret_bb, LBB0_1
; CHECK-NEXT:    chain call_ret_bb, 0x64
; CHECK-NEXT:    writer.32 call_ret_bb, tid
; CHECK-NEXT:    writer.32 call_ret_bb, ret_fid
; CHECK-NEXT:  LBB0_1:
; CHECK-NEXT:    feeder.p.32 tid
; CHECK-NEXT:    feeder.p.32 ret_fid
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    feeder.32 tid
; CHECK-NEXT:    feeder.p.64 r1
; CHECK-NEXT:    feeder.p.64 r2
; CHECK-NEXT:    feeder.p.64 r3
; CHECK-NEXT:    feeder.p.64 r4
; CHECK-NEXT:    feeder.p.32 r5
; CHECK-NEXT:    feeder.p.16 r6
; CHECK-NEXT:    feeder.p.8 r7
; CHECK-NEXT:    chain ret_fid, 0x64
; CHECK-NEXT:    writer.32 ret_fid, tid
    %1 = call { i64, i64, i32, i16, i8 } null()
    ret void
}
