; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=next32 < %s | FileCheck %s

define dso_local zeroext i8 @or1(i8 noundef zeroext %0, i8 noundef zeroext %1) {
; CHECK-LABEL: or1
; CHECK:    or r2, r1
  %3 = or i8 %1, %0
  ret i8 %3
}

define dso_local zeroext i16 @or2(i16 noundef zeroext %0, i16 noundef zeroext %1) {
; CHECK-LABEL: or2
; CHECK:    or r2, r1
  %3 = or i16 %1, %0
  ret i16 %3
}

define dso_local i32 @or3(i32 noundef %0, i32 noundef %1) {
; CHECK-LABEL: or3
; CHECK:    or r2, r1
  %3 = or i32 %1, %0
  ret i32 %3
}

define dso_local i64 @or4(i64 noundef %0, i64 noundef %1) {
; CHECK-LABEL: or4
; CHECK:    or r4, r2
; CHECK-NEXT:    or r3, r1
  %3 = or i64 %1, %0
  ret i64 %3
}

define dso_local i128 @or5(i128 noundef %0, i128 noundef %1) {
; CHECK-LABEL: or5
; CHECK:    or r8, r4
; CHECK-NEXT:    or r7, r3
; CHECK-NEXT:    or r6, r2
; CHECK-NEXT:    or r5, r1
  %3 = or i128 %1, %0
  ret i128 %3
}

define dso_local <8 x i32> @or6(<8 x i32> noundef %0, <8 x i32> noundef %1) {
; CHECK-LABEL: or6
; CHECK:    or r16, r8
; CHECK-NEXT:    or r15, r7
; CHECK-NEXT:    or r14, r6
; CHECK-NEXT:    or r13, r5
; CHECK-NEXT:    or r12, r4
; CHECK-NEXT:    or r11, r3
; CHECK-NEXT:    or r10, r2
; CHECK-NEXT:    or r9, r1
  %3 = or <8 x i32> %1, %0
  ret <8 x i32> %3
}

define dso_local <16 x i32> @or7(<16 x i32> noundef %0, <16 x i32> noundef %1) {
; CHECK-LABEL: or7
; CHECK:    or r32, r16
; CHECK-NEXT:    or r31, r15
; CHECK-NEXT:    or r30, r14
; CHECK-NEXT:    or r29, r13
; CHECK-NEXT:    or r28, r12
; CHECK-NEXT:    or r27, r11
; CHECK-NEXT:    or r26, r10
; CHECK-NEXT:    or r25, r9
; CHECK-NEXT:    or r24, r8
; CHECK-NEXT:    or r23, r7
; CHECK-NEXT:    or r22, r6
; CHECK-NEXT:    or r21, r5
; CHECK-NEXT:    or r20, r4
; CHECK-NEXT:    or r19, r3
; CHECK-NEXT:    or r18, r2
; CHECK-NEXT:    or r17, r1
  %3 = or <16 x i32> %1, %0
  ret <16 x i32> %3
}

define dso_local <32 x i32> @or8(<32 x i32> noundef %0, <32 x i32> noundef %1) {
; CHECK-LABEL: or8
; CHECK:    or r64, r32
; CHECK-NEXT:    or r63, r31
; CHECK-NEXT:    or r62, r30
; CHECK-NEXT:    or r61, r29
; CHECK-NEXT:    or r60, r28
; CHECK-NEXT:    or r59, r27
; CHECK-NEXT:    or r58, r26
; CHECK-NEXT:    or r57, r25
; CHECK-NEXT:    or r56, r24
; CHECK-NEXT:    or r55, r23
; CHECK-NEXT:    or r54, r22
; CHECK-NEXT:    or r53, r21
; CHECK-NEXT:    or r52, r20
; CHECK-NEXT:    or r51, r19
; CHECK-NEXT:    or r50, r18
; CHECK-NEXT:    or r49, r17
; CHECK-NEXT:    or r48, r16
; CHECK-NEXT:    or r47, r15
; CHECK-NEXT:    or r46, r14
; CHECK-NEXT:    or r45, r13
; CHECK-NEXT:    or r44, r12
; CHECK-NEXT:    or r43, r11
; CHECK-NEXT:    or r42, r10
; CHECK-NEXT:    or r41, r9
; CHECK-NEXT:    or r40, r8
; CHECK-NEXT:    or r39, r7
; CHECK-NEXT:    or r38, r6
; CHECK-NEXT:    or r37, r5
; CHECK-NEXT:    or r36, r4
; CHECK-NEXT:    or r35, r3
; CHECK-NEXT:    or r34, r2
; CHECK-NEXT:    or r33, r1
  %3 = or <32 x i32> %1, %0
  ret <32 x i32> %3
}
