; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=next32 < %s | FileCheck %s

define dso_local zeroext i8 @test1(i8 noundef zeroext %0, i8 noundef zeroext %1) {
; CHECK-LABEL: test1
; CHECK:    sub r1, r2
; CHECK-NEXT:    zext.8 r1
  %3 = sub i8 %0, %1
  ret i8 %3
}

define dso_local zeroext i16 @test2(i16 noundef zeroext %0, i16 noundef zeroext %1) {
; CHECK-LABEL: test2
; CHECK:    sub r1, r2
; CHECK-NEXT:    zext.16 r1
  %3 = sub i16 %0, %1
  ret i16 %3
}

define dso_local i32 @test3(i32 noundef %0, i32 noundef %1) {
; CHECK-LABEL: test3
; CHECK:    sub r1, r2
  %3 = sub i32 %0, %1
  ret i32 %3
}

define dso_local i64 @test4(i64 noundef %0, i64 noundef %1) {
; CHECK-LABEL: test4
; CHECK:    sub r1, r3
; CHECK-NEXT:    dup r3, r1
; CHECK-NEXT:    flags r3
; CHECK-NEXT:    sbb r2, r4 [r3]
  %3 = sub i64 %0, %1
  ret i64 %3
}

define dso_local i128 @test5(i128 noundef %0, i128 noundef %1) {
; CHECK-LABEL: test5
; CHECK:    sub r1, r5
; CHECK-NEXT:    dup r5, r1
; CHECK-NEXT:    flags r5
; CHECK-NEXT:    sbb r2, r6 [r5]
; CHECK-NEXT:    dup r5, r2
; CHECK-NEXT:    flags r5
; CHECK-NEXT:    sbb r3, r7 [r5]
; CHECK-NEXT:    dup r5, r3
; CHECK-NEXT:    flags r5
; CHECK-NEXT:    sbb r4, r8 [r5]
  %3 = sub i128 %0, %1
  ret i128 %3
}

define dso_local signext i8 @test6(i8 noundef signext %0, i8 noundef signext %1) {
; CHECK-LABEL: test6
; CHECK:    sub r1, r2
; CHECK-NEXT:    sext.8 r1
  %3 = sub i8 %0, %1
  ret i8 %3
}

define dso_local signext i16 @test7(i16 noundef signext %0, i16 noundef signext %1) {
; CHECK-LABEL: test7
; CHECK:    sub r1, r2
; CHECK-NEXT:    sext.16 r1
  %3 = sub i16 %0, %1
  ret i16 %3
}

define dso_local i32 @test8(i32 noundef %0, i32 noundef %1) {
; CHECK-LABEL: test8
; CHECK:    sub r1, r2
  %3 = sub nsw i32 %0, %1
  ret i32 %3
}

define dso_local i64 @test9(i64 noundef %0, i64 noundef %1) {
; CHECK-LABEL: test9
; CHECK:    sub r1, r3
; CHECK-NEXT:    dup r3, r1
; CHECK-NEXT:    flags r3
; CHECK-NEXT:    sbb r2, r4 [r3]
  %3 = sub nsw i64 %0, %1
  ret i64 %3
}

define dso_local i128 @test10(i128 noundef %0, i128 noundef %1) {
; CHECK-LABEL: test10
; CHECK:    sub r1, r5
; CHECK-NEXT:    dup r5, r1
; CHECK-NEXT:    flags r5
; CHECK-NEXT:    sbb r2, r6 [r5]
; CHECK-NEXT:    dup r5, r2
; CHECK-NEXT:    flags r5
; CHECK-NEXT:    sbb r3, r7 [r5]
; CHECK-NEXT:    dup r5, r3
; CHECK-NEXT:    flags r5
; CHECK-NEXT:    sbb r4, r8 [r5]
  %3 = sub i128 %0, %1
  ret i128 %3
}

define dso_local i128 @test11(i128 noundef %0, i128 noundef %1) {
; CHECK-LABEL: test11
; CHECK:    sub r1, r5
; CHECK-NEXT:    dup r5, r1
; CHECK-NEXT:    flags r5
; CHECK-NEXT:    sbb r2, r6 [r5]
; CHECK-NEXT:    dup r5, r2
; CHECK-NEXT:    flags r5
; CHECK-NEXT:    sbb r3, r7 [r5]
; CHECK-NEXT:    dup r5, r3
; CHECK-NEXT:    flags r5
; CHECK-NEXT:    sbb r4, r8 [r5]
  %3 = sub nsw i128 %0, %1
  ret i128 %3
}

define dso_local <8 x i32> @test12(<8 x i32> noundef %0, <8 x i32> noundef %1) {
; CHECK-LABEL: test12
; CHECK:    sub r8, r16
; CHECK-NEXT:    sub r7, r15
; CHECK-NEXT:    sub r6, r14
; CHECK-NEXT:    sub r5, r13
; CHECK-NEXT:    sub r4, r12
; CHECK-NEXT:    sub r3, r11
; CHECK-NEXT:    sub r2, r10
; CHECK-NEXT:    sub r1, r9
  %3 = sub <8 x i32> %0, %1
  ret <8 x i32> %3
}

define dso_local <16 x i32> @test13(<16 x i32> noundef %0, <16 x i32> noundef %1) {
; CHECK-LABEL: test13
; CHECK:    sub r16, r32
; CHECK-NEXT:    sub r15, r31
; CHECK-NEXT:    sub r14, r30
; CHECK-NEXT:    sub r13, r29
; CHECK-NEXT:    sub r12, r28
; CHECK-NEXT:    sub r11, r27
; CHECK-NEXT:    sub r10, r26
; CHECK-NEXT:    sub r9, r25
; CHECK-NEXT:    sub r8, r24
; CHECK-NEXT:    sub r7, r23
; CHECK-NEXT:    sub r6, r22
; CHECK-NEXT:    sub r5, r21
; CHECK-NEXT:    sub r4, r20
; CHECK-NEXT:    sub r3, r19
; CHECK-NEXT:    sub r2, r18
; CHECK-NEXT:    sub r1, r17
  %3 = sub <16 x i32> %0, %1
  ret <16 x i32> %3
}

define dso_local <32 x i32> @test14(<32 x i32> noundef %0, <32 x i32> noundef %1) {
; CHECK-LABEL: test14
; CHECK:    sub r32, r64
; CHECK-NEXT:    sub r31, r63
; CHECK-NEXT:    sub r30, r62
; CHECK-NEXT:    sub r29, r61
; CHECK-NEXT:    sub r28, r60
; CHECK-NEXT:    sub r27, r59
; CHECK-NEXT:    sub r26, r58
; CHECK-NEXT:    sub r25, r57
; CHECK-NEXT:    sub r24, r56
; CHECK-NEXT:    sub r23, r55
; CHECK-NEXT:    sub r22, r54
; CHECK-NEXT:    sub r21, r53
; CHECK-NEXT:    sub r20, r52
; CHECK-NEXT:    sub r19, r51
; CHECK-NEXT:    sub r18, r50
; CHECK-NEXT:    sub r17, r49
; CHECK-NEXT:    sub r16, r48
; CHECK-NEXT:    sub r15, r47
; CHECK-NEXT:    sub r14, r46
; CHECK-NEXT:    sub r13, r45
; CHECK-NEXT:    sub r12, r44
; CHECK-NEXT:    sub r11, r43
; CHECK-NEXT:    sub r10, r42
; CHECK-NEXT:    sub r9, r41
; CHECK-NEXT:    sub r8, r40
; CHECK-NEXT:    sub r7, r39
; CHECK-NEXT:    sub r6, r38
; CHECK-NEXT:    sub r5, r37
; CHECK-NEXT:    sub r4, r36
; CHECK-NEXT:    sub r3, r35
; CHECK-NEXT:    sub r2, r34
; CHECK-NEXT:    sub r1, r33
  %3 = sub <32 x i32> %0, %1
  ret <32 x i32> %3
}

define dso_local <8 x i32> @test15(<8 x i32> noundef %0, <8 x i32> noundef %1) {
; CHECK-LABEL: test15
; CHECK:    sub r8, r16
; CHECK-NEXT:    sub r7, r15
; CHECK-NEXT:    sub r6, r14
; CHECK-NEXT:    sub r5, r13
; CHECK-NEXT:    sub r4, r12
; CHECK-NEXT:    sub r3, r11
; CHECK-NEXT:    sub r2, r10
; CHECK-NEXT:    sub r1, r9
  %3 = sub <8 x i32> %0, %1
  ret <8 x i32> %3
}

define dso_local <16 x i32> @test16(<16 x i32> noundef %0, <16 x i32> noundef %1) {
; CHECK-LABEL: test16
; CHECK:    sub r16, r32
; CHECK-NEXT:    sub r15, r31
; CHECK-NEXT:    sub r14, r30
; CHECK-NEXT:    sub r13, r29
; CHECK-NEXT:    sub r12, r28
; CHECK-NEXT:    sub r11, r27
; CHECK-NEXT:    sub r10, r26
; CHECK-NEXT:    sub r9, r25
; CHECK-NEXT:    sub r8, r24
; CHECK-NEXT:    sub r7, r23
; CHECK-NEXT:    sub r6, r22
; CHECK-NEXT:    sub r5, r21
; CHECK-NEXT:    sub r4, r20
; CHECK-NEXT:    sub r3, r19
; CHECK-NEXT:    sub r2, r18
; CHECK-NEXT:    sub r1, r17
  %3 = sub <16 x i32> %0, %1
  ret <16 x i32> %3
}

define dso_local <32 x i32> @test17(<32 x i32> noundef %0, <32 x i32> noundef %1) {
; CHECK-LABEL: test17
; CHECK:    sub r32, r64
; CHECK-NEXT:    sub r31, r63
; CHECK-NEXT:    sub r30, r62
; CHECK-NEXT:    sub r29, r61
; CHECK-NEXT:    sub r28, r60
; CHECK-NEXT:    sub r27, r59
; CHECK-NEXT:    sub r26, r58
; CHECK-NEXT:    sub r25, r57
; CHECK-NEXT:    sub r24, r56
; CHECK-NEXT:    sub r23, r55
; CHECK-NEXT:    sub r22, r54
; CHECK-NEXT:    sub r21, r53
; CHECK-NEXT:    sub r20, r52
; CHECK-NEXT:    sub r19, r51
; CHECK-NEXT:    sub r18, r50
; CHECK-NEXT:    sub r17, r49
; CHECK-NEXT:    sub r16, r48
; CHECK-NEXT:    sub r15, r47
; CHECK-NEXT:    sub r14, r46
; CHECK-NEXT:    sub r13, r45
; CHECK-NEXT:    sub r12, r44
; CHECK-NEXT:    sub r11, r43
; CHECK-NEXT:    sub r10, r42
; CHECK-NEXT:    sub r9, r41
; CHECK-NEXT:    sub r8, r40
; CHECK-NEXT:    sub r7, r39
; CHECK-NEXT:    sub r6, r38
; CHECK-NEXT:    sub r5, r37
; CHECK-NEXT:    sub r4, r36
; CHECK-NEXT:    sub r3, r35
; CHECK-NEXT:    sub r2, r34
; CHECK-NEXT:    sub r1, r33
  %3 = sub <32 x i32> %0, %1
  ret <32 x i32> %3
}
