; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=next32 -mcpu=next32gen2 < %s | FileCheck %s

define void @test(ptr noalias nocapture %a, ptr noalias nocapture readonly %b) {
; CHECK-LABEL: test:
; CHECK:       LBB0_0:
; CHECK-NEXT:  # %bb.0: # %entry
; CHECK-NEXT:    feeder.32 tid
; CHECK-NEXT:    feeder.32 ret_fid
; CHECK-NEXT:    feeder.64 r1
; CHECK-NEXT:    feeder.64 r2
; CHECK-NEXT:    feeder.64 r3
; CHECK-NEXT:    feeder.64 r4
; CHECK-NEXT:    memread.2.64.align[4] r4, r3, tid
; CHECK-NEXT:    memdata r3
; CHECK-NEXT:    memdata r6
; CHECK-NEXT:    movl call_addr, __extendsfdf2
; CHECK-NEXT:    movl call_ret_fid, .Ltmp0
; CHECK-NEXT:    chain call_addr, 0x64
; CHECK-NEXT:    writer.32 call_addr, tid
; CHECK-NEXT:    writer.32 call_addr, call_ret_fid
; CHECK-NEXT:    writer.32 call_addr, r3
; CHECK-NEXT:    movl call_ret_bb, LBB0_1
; CHECK-NEXT:    chain.rn call_ret_bb, 0x64
; CHECK-NEXT:    writer.32 call_ret_bb, tid
; CHECK-NEXT:    writer.32 call_ret_bb, ret_fid
; CHECK-NEXT:    writer.32 call_ret_bb, r1
; CHECK-NEXT:    writer.32 call_ret_bb, r2
; CHECK-NEXT:    writer.32 call_ret_bb, r3
; CHECK-NEXT:    writer.32 call_ret_bb, r6
; CHECK-NEXT:  LBB0_1: # %entry
; CHECK-NEXT:    feeder.p.32 tid
; CHECK-NEXT:    feeder.p.32 ret_fid
; CHECK-NEXT:    feeder.p.32 r1
; CHECK-NEXT:    feeder.p.32 r2
; CHECK-NEXT:    feeder.p.32 r3
; CHECK-NEXT:    feeder.p.32 r6
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    feeder.32 tid
; CHECK-NEXT:    feeder.p.64 r5
; CHECK-NEXT:    feeder.p.64 r4
; CHECK-NEXT:    movl call_addr, __extendsfdf2
; CHECK-NEXT:    movl call_ret_fid, .Ltmp1
; CHECK-NEXT:    chain call_addr, 0x64
; CHECK-NEXT:    writer.32 call_addr, tid
; CHECK-NEXT:    writer.32 call_addr, call_ret_fid
; CHECK-NEXT:    writer.32 call_addr, r6
; CHECK-NEXT:    movl call_ret_bb, LBB0_2
; CHECK-NEXT:    chain.rn call_ret_bb, 0x64
; CHECK-NEXT:    writer.32 call_ret_bb, tid
; CHECK-NEXT:    writer.32 call_ret_bb, ret_fid
; CHECK-NEXT:    writer.32 call_ret_bb, r1
; CHECK-NEXT:    writer.32 call_ret_bb, r2
; CHECK-NEXT:    writer.32 call_ret_bb, r3
; CHECK-NEXT:    writer.32 call_ret_bb, r4
; CHECK-NEXT:    writer.32 call_ret_bb, r5
; CHECK-NEXT:  LBB0_2: # %entry
; CHECK-NEXT:    feeder.p.32 tid
; CHECK-NEXT:    feeder.p.32 ret_fid
; CHECK-NEXT:    feeder.p.32 r1
; CHECK-NEXT:    feeder.p.32 r2
; CHECK-NEXT:    feeder.p.32 r3
; CHECK-NEXT:    feeder.p.32 r4
; CHECK-NEXT:    feeder.p.32 r5
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    feeder.32 tid
; CHECK-NEXT:    feeder.64 r6
; CHECK-NEXT:    feeder.64 r7
; CHECK-NEXT:    memwrite.2.128.align[8] r2, r1, tid
; CHECK-NEXT:    memdata r4
; CHECK-NEXT:    memdata r5
; CHECK-NEXT:    memdata r7
; CHECK-NEXT:    memdata r6
; CHECK-NEXT:    dup r1, tid
; CHECK-NEXT:    barrier r1, r3
; CHECK-NEXT:    barrier r1, r4
; CHECK-NEXT:    dup tid, r1
; CHECK-NEXT:    chain ret_fid, 0x64
; CHECK-NEXT:    writer.32 ret_fid, tid
entry:
  %val = load <2 x float>, ptr %b, align 4
  %ext = fpext <2 x float> %val to <2 x double>
  store <2 x double> %ext, ptr %a, align 8
  ret void
}
