; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=next32 -mcpu=next32gen2 < %s | FileCheck %s

declare <8 x i32> @llvm.masked.load.v8i32.p0(ptr, i32, <8 x i1>, <8 x i32>)
declare void @llvm.masked.store.v8i32.p0(<8 x i32>, ptr, i32, <8 x i1>)
declare <16 x i32> @llvm.masked.load.v16i32.p0(ptr, i32, <16 x i1>, <16 x i32>)
declare void @llvm.masked.store.v16i32.p0(<16 x i32>, ptr, i32, <16 x i1>)
declare <32 x i32> @llvm.masked.load.v32i32.p0(ptr, i32, <32 x i1>, <32 x i32>)
declare void @llvm.masked.store.v32i32.p0(<32 x i32>, ptr, i32, <32 x i1>)

define void @vmemreadwrite8x32(ptr %dst, ptr %src, i8 %mask) {
; CHECK-LABEL: vmemreadwrite8x32
; CHECK:    vmemread.8.32.align[32] r4, r3, tid, r5
; CHECK:    vmemwrite.8.32.align[32] r2, r1, r12, r5
  %bitmask = bitcast i8 %mask to <8 x i1>
  %val = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr %src, i32 32, <8 x i1> %bitmask, <8 x i32> undef)
  call void @llvm.masked.store.v8i32.p0(<8 x i32> %val, ptr %dst, i32 32, <8 x i1> %bitmask)
  ret void
}

define void @vmemreadwrite16x32(ptr %dst, ptr %src, i16 %mask) {
; CHECK-LABEL: vmemreadwrite16x32
; CHECK:    vmemread.16.32.align[64] r4, r3, tid, r5
; CHECK:    vmemwrite.16.32.align[64] r2, r1, r20, r5
  %bitmask = bitcast i16 %mask to <16 x i1>
  %val = call <16 x i32> @llvm.masked.load.v16i32.p0(ptr %src, i32 64, <16 x i1> %bitmask, <16 x i32> undef)
  call void @llvm.masked.store.v16i32.p0(<16 x i32> %val, ptr %dst, i32 64, <16 x i1> %bitmask)
  ret void
}

define void @vmemreadwrite32x32(ptr %dst, ptr %src, i32 %mask) {
; CHECK-LABEL: vmemreadwrite32x32
; CHECK:    vmemread.16.32.align[64] r11, r9, tid, r7
; CHECK:    vmemread.16.32.align[128] r4, r3, tid, r5
; CHECK:    vmemwrite.16.32.align[64] r10, r8, r39, r7
; CHECK:    vmemwrite.16.32.align[128] r2, r1, r39, r5
  %bitmask = bitcast i32 %mask to <32 x i1>
  %val = call <32 x i32> @llvm.masked.load.v32i32.p0(ptr %src, i32 128, <32 x i1> %bitmask, <32 x i32> undef)
  call void @llvm.masked.store.v32i32.p0(<32 x i32> %val, ptr %dst, i32 128, <32 x i1> %bitmask)
  ret void
}
